### PR TITLE
Run4-hgx276x Use angle_units in the HGCal plugins for geometry

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Use angle_units in the HGCal plugins for geometry

#### PR validation:

Use the runTheMatrix test workflows

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
Test failure looks like a temporary glitch.

**Comment by cvuosalo** [comment]
+1

**Comment by cvuosalo** [comment]
@bsunanda Thanks for the clean-up.

**Comment by srimanob** [comment]
Seem the test fails of finding input, but input is available at CERN.
> ERROR failed to parse X509 proxy: crypto/tls: failed to parse key: asn1: syntax error: sequence truncated

Should we trigger the test again, or OK to go? @silviodonato @qliphy

**Comment by silviodonato** [comment]
> Seem the test fails of finding input, but input is available at CERN.
> 
> > ERROR failed to parse X509 proxy: crypto/tls: failed to parse key: asn1: syntax error: sequence truncated
> 
> Should we trigger the test again, or OK to go? @silviodonato @qliphy

It's ok from my side

**Comment by srimanob** [comment]
+Upgrade

**Comment by silviodonato** [comment]
merge

**Pull request merged**
