### PR TITLE
Phase2-TB67 Clean up the analyzers of HGCal TB applications in SimG4CMS/HGCalTestBeam/plugins

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Clean up the analyzers of HGCal TB applications in SimG4CMS/HGCalTestBeam/plugins

#### PR validation:

Use test workflows in SimG4CMS/HGCalTestBeam/test

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by srimanob** [comment]
@cmsbuild please test

**Comment by civanch** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade 

Technical PR, no change is expected. Fail comparisons come from MessageLogger.

**Comment by qliphy** [comment]
@bsunanda   There is some error message from StaticAnalyzers as below, although it is not directly from this PR, would you please have a look?

https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-c5beef/22527/llvm-analysis/runStaticChecks.log

/pool/condor/dir_11114/jenkins/workspace/ib-run-pr-tests/CMSSW_12_3_X_2022-02-19-1100/src/SimG4CMS/HGCalTestBeam/plugins/HGCalTBCheckGunPosition.cc:99:65: error: expected ';' after expression
    edm::LogVerbatim("HGCSim") << "isHandle valid: " << isHandle valid;
                                                                ^
                                                                ;
/pool/condor/dir_11114/jenkins/workspace/ib-run-pr-tests/CMSSW_12_3_X_2022-02-19-1100/src/SimG4CMS/HGCalTestBeam/plugins/HGCalTBCheckGunPosition.cc:99:57: error: use of undeclared identifier 'isHandle'; did you mean 'isnanl'?
    edm::LogVerbatim("HGCSim") << "isHandle valid: " << isHandle valid;


/pool/condor/dir_11114/jenkins/workspace/ib-run-pr-tests/CMSSW_12_3_X_2022-02-19-1100/src/SimG4CMS/HGCalTestBeam/plugins/HGCalTBCheckGunPosition.cc:99:66: error: use of undeclared identifier 'valid'
    edm::LogVerbatim("HGCSim") << "isHandle valid: " << isHandle valid;
                                                                 ^
/pool/condor/dir_11114/jenkins/workspace/ib-run-pr-tests/CMSSW_12_3_X_2022-02-19-1100/src/SimG4CMS/HGCalTestBeam/plugins/HGCalTBCheckGunPosition.cc:114:7: error: use of undeclared identifier 'z'
      z = (*p)->position().z() / 10.;  // in cm
      ^
/pool/condor/dir_11114/jenkins/workspace/ib-run-pr-tests/CMSSW_12_3_X_2022-02-19-1100/src/SimG4CMS/HGCalTestBeam/plugins/HGCalTBCheckGunPosition.cc:117:92: error: use of undeclared identifier 'z'
                                   << ":" << y << " z: " << (*p)->position().z() << ":" << z;
                                                                                           ^
5 errors generated.

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

Re-sign of the PR.

**Comment by qliphy** [comment]
+1

**Pull request merged**
