### PR TITLE
Do not modify HepMCProduct in place. It's not thread safe.

### PR DESCRIPTION
**Pull request by wmtan**
Yes, I know this PR is too huge to be visible in github, but it is not easily separable into independent chunks. I would be happy to break it up into separate pieces if there was some way to guarantee that they all get tested and merged at once. Most of the modifications are small changes to python config files.

Currently, a HepMCProduct object gets put into the event by the generator, and modified in place by a vertex smearer. This is not thread safe, and it violates the principle of modular design. This PR creates a new EVENTVERTEXGENERATOR plugin type for the vertex smearers, and runs the smearers inside the generators in almost all cases.  These smearers can also be run inside a new separate EDProducer, "EventVertexProducer", which is done in those configuration files where the smearer was run without the generator.  Virtually all such configuration files were unit tests.

The alternative of running the smearers in separate producers for production  was rejected because it would cause two copies of each HepMCProduct to go into each event, and every module that reads HepMCProduct would have to be modified to read the correct one,  It would be virtually impossible to get that right in every case.  The chosen implementation ensures that there is still only one HepMCProduct in each event, and that its label (used by getByLabel or getByToken) is unchanged.

### CODE REVIEW

**Comment by wmtan** [comment]
Actually, this PR involves 75 packages.
A full list is:
Configuration/EcalTB                                                                                                                                                                                      
Configuration/Generator                                                                                                                                                                                     
Configuration/StandardSequences                                                                                                                                                                             
FastSimulation/Calorimetry                                                                                                                                                                                  
FastSimulation/Configuration                                                                                                                                                                                
FastSimulation/ForwardDetectors                                                                                                                                                                             
FastSimulation/ParticleDecay                                                                                                                                                                                
FastSimulation/Tracking                                                                                                                                                                                     
GeneratorInterface/AMPTInterface                                                                                                                                                                            
GeneratorInterface/AlpgenInterface                                                                                                                                                                          
GeneratorInterface/BeamHaloGenerator                                                                                                                                                                        
GeneratorInterface/CascadeInterface                                                                                                                                                                     
GeneratorInterface/Core                                                                                                                                                                                     
GeneratorInterface/CosmicMuonGenerator                                                                                                                                                                      
GeneratorInterface/EvtGenInterface
GeneratorInterface/ExhumeInterface
GeneratorInterface/ExternalDecays
GeneratorInterface/GenExtensions
GeneratorInterface/GenFilters
GeneratorInterface/Herwig6Interface
GeneratorInterface/HiGenCommon
GeneratorInterface/HijingInterface
GeneratorInterface/Hydjet2Interface
GeneratorInterface/HydjetInterface
GeneratorInterface/LHEInterface
GeneratorInterface/MCatNLOInterface
GeneratorInterface/PhotosInterface
GeneratorInterface/PomwigInterface
GeneratorInterface/PyquenInterface
GeneratorInterface/Pythia6Interface
GeneratorInterface/Pythia8Interface
GeneratorInterface/ReggeGribovPartonMCInterface
GeneratorInterface/RivetInterface
GeneratorInterface/SherpaInterface
GeneratorInterface/TauolaInterface
GeneratorInterface/ThePEGInterface
Geometry/CMSCommonData
Geometry/HcalCommonData
Geometry/HcalTestBeamData
Geometry/MuonCommonData
IOMC/EventVertexGenerators
IOMC/Input
IOMC/ParticleGuns
L1Trigger/CSCTrackFinder
L1Trigger/CSCTriggerPrimitives
L1Trigger/L1TCalorimeter
L1Trigger/L1TGlobal
PhysicsTools/JetExamples
RecoLocalMuon/GEMRecHit
RecoParticleFlow/Configuration
RecoParticleFlow/PFTracking
SLHCUpgradeSimulations/Geometry
SimCalorimetry/CastorSim
SimCalorimetry/EcalTestBeam
SimDataFormats/GeneratorProducts
SimG4CMS/Calo
SimG4CMS/CherenkovAnalysis
SimG4CMS/Forward
SimG4CMS/HcalTestBeam
SimG4CMS/ShowerLibraryProducer
SimG4Core/CheckSecondary
SimG4Core/GFlash
SimG4Core/PrintGeomInfo
SimGeneral/MixingModule
SimTracker/SiPixelDigitizer
SimTracker/TrackerMaterialAnalysis
TauAnalysis/MCEmbeddingTools
Validation/CaloTowers
Validation/CheckOverlap
Validation/EcalDigis
Validation/EcalHits
Validation/Geometry
Validation/HcalDigis
Validation/HcalHits
Validation/RecoParticleFlow

**Comment by Dr15Jones** [comment]
please test

**Comment by slava77** [comment]
Hi Bill,

remind me please, if the following was considered:
Instead of this, could we just have 
- generators write a _unsmeared_ label
- VtxSmeared BeamProfileVtxGenerator make a copy
- EDAlias is defined which makes HepMCProduct_VtxSmeared become HepMCProduct_generator
(if a job has no VtxSmeared, an EDAlias makes generator_unsmeared to be visible as generator_ product) 
?

**Comment by wmtan** [comment]
Slava,
Yes, it was considered.
An EDAlias cannot be created with a name that is defined elsewhere.  So, the EDAlias solution does not work unless *every* current use of the module label "generator" is removed.  Also, that solution causes two HepMCProducts with different labels to be generated, which means that every reader of a HepMCProduct now has the possibility of reading the wrong one, and it would be very hard to ensure that the right one is read.
With the current solution, "NoSmear" is still an option for the generators, and, in such cases, the smearers can be run separately in a producer. The only cases I found anywhere where the smearers were currently run without a generator were in a handful of unit tests.

**Comment by wmtan** [comment]
Slava,
  Another complication with the EDAlias option is that the generators make other products besides "HepMCProduct". The label unsmeared would then apply to all products that have nothing to do with HepMCProducts.

**Comment by slava77** [comment]
I meant something like this:
- the generators do ``` produces<HepMCProduct>("unsmeared"); ``` [HepMCProduct_generator_unsmeared_PROCESSNAME is created] , unless a config is passed to do  ``` produces<HepMCProduct>(); ```  and the job has no VtxSmeared
    - VtxSmeared reads generator:unsmeared and creates  a new HepMCProduct_VtxSmeared__PROCESSNAME
        - EDAlias makes HepMCProduct_VtxSmeared__PROCESSNAME look like HepMCProduct_generator__PROCESSNAME
The net effect would be a few changes in a handful of files.
If the EDAlias doesn't work this way, then ok (OTOH, why not?)

**Comment by wmtan** [comment]
Slava,
  I don't think that EDAlias works, because the name "generator" is already used as a module label, so it cannot also be an alias. If I remember correctly, this caused a python error, as the same identifier cannot be used for both in python.
In any event, since (almost?) every current production scenario does both generation and smearing together, it is less of a change to continue to produce one and only one HepMCProduct in the current scenarios. The ability to do the spearing in a separate producer is still there when needed or desired.

**Comment by wmtan** [comment]
@slava77 @civanch There is an alternative to this implementation that has the generators creating a product of a new class (HepMcProductUnsmeared), and having the smearers read the HepProductUnsmeared product and writing the HepMCProduct.

**Comment by slava77** [comment]
-1
a different implementation is coming
Bill, if you are not going to update this PR with the other solution, please close it

**Comment by wmtan** [comment]
@slava77 I will close this PR as soon as the alternative PR is available. I prefer to keep it open in the meantime.

**Comment by wmtan** [comment]
I'm closing this PR, because PR #10858 (an alternate implementation) supersedes it.

**Pull request closed without merging**
