### PR TITLE
Implement ROOT read rules for PortableHostCollection [13.3.x]

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Implement ROOT read rules for `PortableHostCollection` instantiations.

These replace the user-defined read rules in the XML file
```xml
  <read
    sourceClass="portabletest::TestHostCollection"
    targetClass="portabletest::TestHostCollection"
    version="[1-]"
    source="portabletest::TestSoA layout_;"
    target="buffer_,layout_,view_"
    embed="false">
  <![CDATA[
    portabletest::TestHostCollection::ROOTReadStreamer(newObj, onfile.layout_);
  ]]>
  </read>
```
with a macro-based C++ implementation in `DataFormats/PortableTestObjects/src/classes.cc`:
```c++
#include "DataFormats/Portable/interface/PortableHostCollectionReadRules.h"
#include "DataFormats/PortableTestObjects/interface/TestHostCollection.h"

SET_PORTABLEHOSTCOLLECTION_READ_RULES(portabletest::TestHostCollection);
```

#### PR validation:

The `HeterogeneousCore/AlpakaTest/test/testHeterogeneousCoreAlpakaTestWriteRead.sh` unit test pass:
  - the `portabletest::TestHostCollection` is written to a ROOT file;
  - it is read back from the ROOT file using the user-defined streamer function;
  - the validation checks pass.

#### If this PR is a backport please specify the original PR and why you need to backport that PR.

Backport of #43219 to CMSSW_13_3_X.

### CODE REVIEW

**Comment by fwyzard** [comment]
backport #43219

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
+heterogeneous

**Comment by rappoccio** [comment]
+1

**Pull request merged**
