### PR TITLE
update a vertex smearing parameters for 2024 pp ref MC

### PR DESCRIPTION
**Pull request by ashleyahram**
#### PR description:
- This PR adds a vertex smearing for 2024 pp ref MC. Beamspot position derived from runs 387590 to 387721, barycentre location provided by Tracker Alignment Group ([cmsTalk](https://cms-talk.web.cern.ch/t/bpix-barycentre-values-for-the-2024-pp-ref-mc/59947/))

#### PR validation: 
- This PR has been modeled after a similar PR from 2022 and 2023: [2022 PR link](https://github.com/cms-sw/cmssw/pull/40496), [2023 PR link](https://github.com/cms-sw/cmssw/pull/43217)

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for: 
- We will need a backport for 14_1_X 

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by mmusich** [comment]
@ashleyahram shleyahram, just for your info, since this year in order to be able to consume the gen-level beam spot in production we need also a DB tag for `SimBeamSpotRcd`, see e.g PR https://github.com/cms-sw/cmssw/pull/43242

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by ashleyahram** [comment]
> @ashleyahram shleyahram, just for your info, since this year in order to be able to consume the gen-level beam spot in production we need also a DB tag for `SimBeamSpotRcd`, see e.g PR #43242

Thank you for your information. I'll implement this too.

**Comment by civanch** [comment]
+1

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
