### PR TITLE
L1T layout changes for online DQM (74x)

### PR DESCRIPTION
**Pull request by dmitrijus**
This is a rebase of https://github.com/cms-sw/cmssw/pull/10568
(https://github.com/cms-sw/cmssw/pull/10568 should be closed)

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1

**Comment by deguio** [comment]
please submit to 75 and 76 as well.
thanks

**Comment by deguio** [comment]
-1
accepting @jingyucms PRs.

**Comment by dmitrijus** [comment]
superseded

**Pull request closed without merging**
