### PR TITLE
add utility returning hashed version of firmware-uuid of a L1T menu

### PR DESCRIPTION
**Pull request by missirol**
#### PR description:

This PR adds a simple cpp program to get the hashed version of the firmware-uuid of a L1T menu.

This utility can be useful in debugging [exceptions thrown by `L1TGlobalProducer`](https://github.com/cms-sw/cmssw/blob/d636fedd54218a07737bf87fcb0f2c55318d4884/L1Trigger/L1TGlobal/plugins/L1TGlobalProducer.cc#L343) like the one below:
```
An exception of category 'ConditionsError' occurred while
[0] Processing Event run: 367301 lumi: 10 event: 105191 stream: 23
[1] Running path 'HLT_DoubleEle10_eta1p22_mMax6_trkHits10_v2'
[2] Calling method for module L1TGlobalProducer/'hltGtStage2ObjectMap'
Exception Message:
Error L1 menu loaded in via conditions does not match the L1 actually run -931659658 vs 1554451404.
This means that the mapping of the names to the bits may be incorrect.
Please check the L1TUtmTriggerMenuRcd record supplied.
Unless you know what you are doing, do not simply disable this check via the config
as this a major error and the indication of something very wrong
```

#### PR validation:

The corresponding executable works as expected. Example:
```bash
$ l1tHashMenuFirmwareUUID 7a1a9c0b-5e34-4c25-804f-2ae8094c4832
1554451404
```

#### If this PR is a backport, please specify the original PR and why you need to backport that PR. If this PR will be backported, please specify to which release cycle the backport is meant for:

N/A

### CODE REVIEW

**Comment by aloeliger** [comment]
+l1

**Comment by missirol** [comment]
please abort

**Comment by missirol** [comment]
Moved to `CondTools`, applied minor changes, and renamed the utility (`l1tHashMenuFirmwareUUID` is a bit clearer, arguably).

**Comment by missirol** [comment]
please test

**Comment by aloeliger** [comment]
+l1

@missirol Is this part of the ongoing packer/unpacker debugging?

**Comment by missirol** [comment]
> Is this part of the ongoing packer/unpacker debugging?

No, just a different unrelated issue that occurred in run-367301.

**Comment by francescobrivio** [comment]
+db

 - adding useful script for debugging of possible L1T firmware issues
 - tests are clean

**Comment by perrotta** [comment]
+1

**Pull request merged**
