### PR TITLE
Phase2-hgx346Y Fix the compilation error in CaloSD for debug mode

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Fix the compilation error in CaloSD for debug mode

#### PR validation:

Use the runTheMatrix test workflows

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
type BugFix

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by civanch** [comment]
It is the fix of #43015

**Comment by rappoccio** [comment]
@bsunanda there are conflicts here, can you fix them? thanks.

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
Just resolved the conflicts
________________________________

**Comment by civanch** [comment]
+1

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
