### PR TITLE
Refine RPCDigis Validation histograms

### PR DESCRIPTION
**Pull request by jhgoh**
#### PR description:

This PR is a follow-up PR of the previous one #45029. 
In this PR, we want to refine the RPCDigis validation plots.

There was a report in the RPC-DPG working meeting 14 Aug 2024: [link to the slide](https://indico.cern.ch/event/1445690/contributions/6087482/attachments/2911238/5107796/%5B2024.08.14%5D%20Followup%20PR%20RPCDigi%20Validation.pdf)

The proposed changes are
- Extend x-axis of digi-simhit residual plot for the Ring1, avoid too many underflows/overflows
- Set default drawing option of 2D histograms ("colz")
- Use era-modifiers to book timing plots only for Phase2 scenario

#### PR validation:

Performed tests on CMSSW_14_1_0_pre6 release

- runTheMatrix.py -l 13034.0 -> OK
  - Also checked the workflow number 12434.0 and 29634.0 with 1,000 events and works fine.
- code-checks OK
- code-format OK

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

We want to have backport to the currently active release cycles

 - 14_0_X
 - 14_1_X

Possible watchers: @mileva @mrcthiel

### CODE REVIEW

**Comment by tjavaid** [comment]
@jhgoh , just to confirm the [existing time plots](https://tinyurl.com/24bnpzxj) are now made hidden with this PR from switch introduced for phase-II, right ?

**Comment by jhgoh** [comment]
> @jhgoh , just to confirm the [existing time plots](https://tinyurl.com/24bnpzxj) are now made hidden with this PR from switch introduced for phase-II scenario, right ?

Yes, the timing plots will be hidden in Run3, because they are valid only after the phase-II upgrade.

**Comment by tjavaid** [comment]
+1

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
