### PR TITLE
Add HGC RecHits / Reco Geometry to Fireworks

### PR DESCRIPTION
**Pull request by lgray**
This PR adds the HGCal geometries (V5 and V7) such that they are processed and written to disk for the fireworks RECO geometry.

I also added a rechit proxy builder, showing that things look mostly reasonable (this is a jet gun event).
It would be useful if we could remove the scaling from RecHit view and just see the hits directly, right now they are scaled to be very tiny since they only contain energies of few tens-hundreds of keV.

Example of hex geometry:
screen shot 2016-02-05 at 13 25 42

@vandreev11 @sethzenz @kpedro88

### CODE REVIEW

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
@cseez FYI.

**Comment by lgray** [comment]
@alja please review when you are able. Thanks!

**Comment by alja** [comment]
@lgray
I will add option for seeing det hits without scaling. Currently I'm on a family leave and will be back on 29 of February. I will try to get this earlier.

**Comment by alja** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
