### PR TITLE
remove stuck-TBM specific workflows

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:
PR https://github.com/cms-sw/cmssw/pull/25524 introduced two specific workflows to be able to test the SiPixel Bad FED Channel simulation (a.k.a. stuck-TBM simulation).
With the activation of the feature by default in PR https://github.com/cms-sw/cmssw/pull/26275 and the provision of Ultra-Legacy conditions for the records `SiPixelStatusScenarioProbabilityRcd` and `SiPixelStatusScenariosRcd` for  the 2017 MC in PR https://github.com/cms-sw/cmssw/pull/27342 and for 2018 MC in PR https://github.com/cms-sw/cmssw/pull/27683, these workflows are now superfluous and can be removed.

#### PR validation:
Run the usual limited matrix tests:
```
$ runTheMatrix.py -l limited -t 4 -j 8 --ibeos
```
which completed without errors.

#### if this PR is a backport please specify the original PR:
This PR is not a backport

### CODE REVIEW

**Comment by fabiocos** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by fabiocos** [comment]
@prebello @zhenhu this move makes sense to me, could you please check and approve it?

**Comment by prebello** [comment]
+1

**Comment by fabiocos** [comment]
+1

@kpedro88 please have a look at your earliest convenience, I believe it is ok to move forward

**Comment by fabiocos** [comment]
merge

**Comment by kpedro88** [comment]
+upgrade

**Pull request merged**
