### PR TITLE
  extend PU Flat55To75 to 2024 workflows

### PR DESCRIPTION
**Pull request by slava77**
extend PU Flat55To75  to 2024 workflows

### CODE REVIEW

**Comment by slava77** [comment]
test parameters:
- workflow 13034.0

**Comment by slava77** [comment]
@cmsbuild please abort test

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
> Reco comparison results: 3233 differences found in the comparisons

as expected, changes are only in 13034.0 workflows, consistent with increased pileup.

**Comment by sunilUIET** [comment]
+pdmv

**Comment by mmusich** [comment]
@cms-sw/upgrade-l2 please have a look

**Comment by srimanob** [comment]
+Upgrade

**Comment by perrotta** [comment]
+1

**Pull request merged**
