### PR TITLE
Add emplace method to Event, LuminosityBlock and Run

### PR DESCRIPTION
**Pull request by Dr15Jones**
The emplace method allows one to avoid making a temporary std::unique_ptr and therefor avoid an unnecessary new/delete.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by Dr15Jones** [comment]
@fabiocos there is nothing in this change that can affect existing code.

**Comment by fabiocos** [comment]
@Dr15Jones I think that the 25 differences in DQM are spurious from overlapping commits, there is essentially addition of new code, apart for the replacements in the principal_get_adapter_detail::throwOnPutOfNullProduct calls

**Comment by fabiocos** [comment]
+1

**Pull request merged**
