### PR TITLE
relval updates after 8_0_0_pre2 relval

### PR DESCRIPTION
**Pull request by hengne**
Major updates: (similar to PR#12425 for 76x)
- update fullSim and fastSim mixing and premixing inputs.
- update golden json file for 2015 run2 data
- add high stats (~100k stats) ZMM and TTbar noPU and PU25ns workflows in highstats set. To be run in major X_Y_0 releases for various POGs studies. Can also be produced on demand for pre-releases with sufficient motivation but will not do that for pre-releases by default.
- add high stats HLTPhysics data 2015D workflow in highstats set for HLT studies.
- add workflow to test re-miniAOD using AOD as input, successful done, but cannot run DQM/Harvest in the 2nd miniAOD step because AOD input data contents missing part of the info that needed for the RECO-miniAOD comparison, which exists RECO datacontent not in AOD data contents by design.

### CODE REVIEW

**Comment by hengne** [comment]
please test

**Comment by fabozzi** [comment]
please test

**Comment by fabozzi** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
