### PR TITLE
[14_0] Backport of #45151 (HIon type def for pixel alpaka)

### PR DESCRIPTION
**Pull request by vince502**
This is a backport of PR [cmssw-45151](https://github.com/cms-sw/cmssw/pull/45151) onto CMSSW_14_0_X

### CODE REVIEW

**Comment by fwyzard** [comment]
enable gpu

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
backport #45151

**Comment by fwyzard** [comment]
+heterogeneous

**Comment by mandrenguyen** [comment]
+1

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
