### PR TITLE
Phase2-hgx352B Add an example of CMS scenario with only HGCal detector

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Add an example of a CMS scenario with only an HGCal detector

#### PR validation:

Tested with a configuration given in this PR

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

To be back ported to 14_0_0 using #43877

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@civanch, @rappoccio, @antoniovilela, @sextonkennedy The unit test failure is due to an error in reading a file and is disconnected from the changes in this PR. Please suggest

**Comment by bsunanda** [comment]
+geometry

**Comment by bsunanda** [comment]
@civanch @srimanob Please approve this PR

**Comment by bsunanda** [comment]
@civanch Please approve this. I shall backport this to 14_0_X

**Comment by civanch** [comment]
+1

**Comment by bsunanda** [comment]
@rappoccio, @antoniovilela Please integrate this to the master

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
