### PR TITLE
Run3-gex55 Remove duplicate materials from PPS files

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Remove duplicate materials from PPS files

#### PR validation:

Tested using scripts in SimG4Core/PrintGeomInfo/test/python

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
The failure was not due to this PR

**Comment by cvuosalo** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

**Comment by qliphy** [comment]
+1

**Pull request merged**
