### PR TITLE
add 11634.7 wf for 2021 ttbar mkFit to the short matrix

### PR DESCRIPTION
**Pull request by slava77**
in view of enabling mkFit in tracking some time soon, addition of this workflow to the short matrix should allow to regularly monitor that the workflow is working and the changes in outputs are checked in comparisons.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
> **Failed Tests**

need to re-test after CMSSW_12_1_X_2021-09-10-2300 is out

**Comment by slava77** [comment]
@cmsbuild please test

CMSSW_12_1_X_2021-09-11-1100 showed up around 17:30

**Comment by srimanob** [comment]
+Upgrade

This is to add new wfs to the short matrix, for PR test.

**Comment by slava77** [comment]
@cms-sw/pdmv-l2 
please check this PR.
Thank you.

**Comment by kskovpen** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
