### PR TITLE
clean-up unused inclusions in HLT paths in Phase2 HLT menu

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

Prompted by https://github.com/cms-sw/cmssw/pull/46924#discussion_r1886478283 I went through the phase-2 HLT menu with the following [script](https://github.com/mmusich/hltScripts/blob/master/upgrade/checkPathIncludes.py) and discovered that some of the inclusions in the paths are inconsequential.
I propose to clean-up these includes in the menu. 

#### PR validation:

Tested successfully:

- `hltPhase2UpgradeIntegrationTests` 
- `runTheMatrix.py -l 29634.75`

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

N/A

### CODE REVIEW

**Comment by mmusich** [comment]
test parameters:
   * enable = hlt_p2_integration

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
+hlt

**Comment by mmusich** [comment]
hold
   * https://github.com/cms-sw/cmssw/pull/46897 must enter first (I'll rebase this one if needed)

**Comment by mmusich** [comment]
unhold

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
+hlt

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
