### PR TITLE
Fix problem with global TPRegexp

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

Removed unused global or made global into member data. This fixes unit test failures seen in PhysicsTools/NanoAOD.

#### PR validation:

The unit test now passes where it had been failing in my tests.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
Running the unit test using gdb pinpointed the problem with a globally destroyed TPRegexp. Then running again in gdb I looked for construction of TPRegexp during shared library loads and found these two.

**Comment by smuzaffar** [comment]
@fabiocos , this should also fix all the failing CentOS8 Relvals.

**Comment by jfernan2** [comment]
+1

**Comment by fabiocos** [comment]
@smuzaffar I understand you tested it privately, anyway do we have the possibility to run a PR test on cc8_amd64_gcc820? I recall you were saying we have not yet a container for it

**Comment by fabiocos** [comment]
@qliphy @agrohsje please have a look, I plan to integrate this PR into next IB

**Comment by smuzaffar** [comment]
yes @fabiocos I have tested 3 workflows and they work[a] after merging this PR. 
We do have a container now and should be able to run cc8 PR tests. Should we try running CC8 PR tests for this?

[a]
```
> git cms-showtags
DQMServices/Components                                  3cc59f2bccd     fd611d6ba3c
GeneratorInterface/RivetInterface                       558b2724497     37e3d66550a
> $ tail -5 b.log 
1317.0_SingleElectronPt35_UP15+SingleElectronPt35_UP15INPUT+DIGIUP15+RECOUP15+HARVESTUP15+NANOUP15 Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Mon Dec  9 08:20:11 2019-date Mon Dec  9 08:11:23 2019; exit: 0 0 0 0 0
1318.0_SingleGammaPt10_UP15+SingleGammaPt10_UP15INPUT+DIGIUP15+RECOUP15+HARVESTUP15+NANOUP15 Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Mon Dec  9 08:20:10 2019-date Mon Dec  9 08:11:23 2019; exit: 0 0 0 0 0
1320.0_SingleMuPt10_UP15+SingleMuPt10_UP15INPUT+DIGIUP15+RECOUP15+HARVESTUP15+NANOUP15 Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Mon Dec  9 08:20:10 2019-date Mon Dec  9 08:11:24 2019; exit: 0 0 0 0 0
3 3 3 3 3 tests passed, 0 0 0 0 0 failed
```

**Comment by Dr15Jones** [comment]
@smuzaffar this should also fix the RelVal failures in the aarch64 IBs.

**Comment by fabiocos** [comment]
@smuzaffar why not? Let's give it a try

**Comment by fabiocos** [comment]
please test for cc8_amd64_gcc820

**Comment by fabiocos** [comment]
please test for cc8_amd64_gcc8

my fault...

**Comment by smuzaffar** [comment]
@Dr15Jones , aarch64 failures are due to a different reason ( libgomp.so uses `initial-exec` TLS model [a] )

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=91938
https://sourceware.org/bugzilla/show_bug.cgi?id=25051
https://sourceware.org/ml/libc-alpha/2019-09/msg00512.html

**Comment by Dr15Jones** [comment]
@smuzaffar this traceback is related to this pull request

https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_aarch64_gcc820/CMSSW_11_1_X_2019-12-08-2300/pyRelValMatrixLogs/run/1321.0_SingleMuPt100_UP15+SingleMuPt100_UP15INPUT+DIGIUP15+RECOUP15+HARVESTUP15+NANOUP15/step5_SingleMuPt100_UP15+SingleMuPt100_UP15INPUT+DIGIUP15+RECOUP15+HARVESTUP15+NANOUP15.log#/

**Comment by smuzaffar** [comment]
ah ok, till 2019-12-05-1100 aarch64 IBs were failing due to 
```
unable to load /cvmfs/cms-ib.cern.ch/nweek-02605/slc7_aarch64_gcc820/cms/cmssw-patch/CMSSW_11_1_X_2019-12-05-1100/lib/slc7_aarch64_gcc820/poisoned/plugin-poisoned-GeneratorInterfaceRivetInterface_plugins.so because /cvmfs/cms-ib.cern.ch/nweek-02605/slc7_aarch64_gcc820/cms/cmssw-patch/CMSSW_11_1_X_2019-12-05-1100/lib/slc7_aarch64_gcc820/poisoned/plugin-poisoned-GeneratorInterfaceRivetInterface_plugins.so: cannot open shared object file: No such file or directory
```
and it happened because edPluginRefresh failed to create .edmplugincache due to libgomp.so issue

**Comment by smuzaffar** [comment]
@fabiocos , looks like we are not yet ready for cc8 PR tests. We are missing few pytjon packages in the container . I have deleted the message to update the PR labels
```
Traceback (most recent call last):
  File "<https://cmssdt.cern.ch/jenkins/job/ib-run-pr-tests/ws/cms-bot/report-pull-request-results.py",> line 8, in <module>
    import requests
ImportError: No module named requests

```

**Comment by fabiocos** [comment]
@smuzaffar ok, it was a meaningful opportunity to test it. I will integrate this PR anyway in next IB

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Pull request merged**
