### PR TITLE
Update 2023 xml Scenatio Scripts

### PR DESCRIPTION
**Pull request by ianna**
* Add all existing 2023 scenarios
* Do not produce HGCal for the moment

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
please test

**Comment by kpedro88** [comment]
@ianna this seems to be out of date wrt #16965 (and also note currently open #16971)

**Comment by kpedro88** [comment]
@ianna never mind, didn't notice it was for 81X

**Comment by ianna** [comment]
@kpedro88 - do you think it is possible to decide on a default (or baseline) scenario at this point?

**Comment by kpedro88** [comment]
@ianna D4 is the baseline for the tracker TDR, but after that things will change again.

**Comment by ianna** [comment]
@kpedro88 - thanks! I just want to make sure that we have a consistent set of tags in a 2023 GT queue (since it's already there) and do not mix run 1, 2, and 3 tags in it. Besides, something may fall - we never know what people rely on in their code :-)

**Comment by ianna** [comment]
@ggovi - please review it

**Comment by ggovi** [comment]
+1

**Comment by ianna** [comment]
@davidlange6 - as discussed at ORP this is needed to go ahead with storing 2023 geometry in DB. 81x is chosen in order to tune the process on stable 2023 geometry.

**Pull request closed without merging**
