### PR TITLE
drop numba and llvmlite tests

### PR DESCRIPTION
**Pull request by smuzaffar**
`numba` and `llvmlite` and only used in couple of unit tests. `llvmlite` takes ages to support latest `llvm` versions. As these tools are only used in couple of unit tests, so I propose to drop these externals and remove the unit tests.

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@cms-sw/reconstruction-l2 can you please review this? Reco changes are simple (it is just the removal of couple of comments)
@perrotta  @rappoccio , can we get this in ? This allow us to drop numba and llvmlite from distribution

**Comment by perrotta** [comment]
+1

**Comment by perrotta** [comment]
merge

**Comment by smuzaffar** [comment]
thanks

**Comment by davidlange6** [comment]
Is it so obvious that there are not people depending on number in cmssw? (By the logic here we can drop lots of things)

**Pull request merged**
