### PR TITLE
Herwig7 fix seg fault102

### PR DESCRIPTION
**Pull request by Andrej-CMS**
Backport of #26905

### CODE REVIEW

**Comment by qliphy** [comment]
please test

**Comment by qliphy** [comment]
+1

**Comment by fabiocos** [comment]
@efeyazgan @qliphy @Andrej-CMS which is the level of validation of this fix? Before putting it in production I think we need to ensure it is behaving correctly in master, what was done so far about this, besides checking that it runs smoothly from the technical point fo view?

**Comment by Andrej-CMS** [comment]
@efeyazgan  @qliphy 
could you please test again after the update of WF 535

**Comment by qliphy** [comment]
please test workflow 535

**Comment by qliphy** [comment]
Although as shown with "comparisons for the following workflows were not done due to missing matrix map:",   Andrej has already checked locally, as mentioned in #26905

**Comment by qliphy** [comment]
+1

**Comment by Andrej-CMS** [comment]
@qliphy 
yes, I made DQM comparisons as mentioned in https://github.com/cms-sw/cmssw/pull/26905#issuecomment-496233771

**Comment by prebello** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade

**Comment by kpedro88** [comment]
+1

**Pull request merged**
