### PR TITLE
HCAL relval update for calo scan2

### PR DESCRIPTION
**Pull request by bcmcms**
Added HCAL SimHits to validation & cleaned up template.py

### CODE REVIEW

**Comment by hatakeyamak** [comment]
@dmitrijus, @jfernan2, @vanbesien can someone please type
"please test"

**Comment by hatakeyamak** [comment]
Pinging one more time...

**Comment by dmitrijus** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
