### PR TITLE
add warnings to L1TGlobalPrescaler (92x)

### PR DESCRIPTION
**Pull request by fwyzard**
- warn if `l1tPrescales` has the wrong number of elements
  - warn if the target prescales are lower than the original ones

### CODE REVIEW

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by fwyzard** [comment]
backport #20145

**Comment by fwyzard** [comment]
bugfix

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by rekovic** [comment]
> backport #20145
Correction,  backport of #20144.

**Comment by rekovic** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
