### PR TITLE
Phase2-hgx295B Remove 2 remaining obsolete cfg's

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Remove 2 remaining obsolete cfg's

#### PR validation:

Check the absence of cfg's not affecting any other testings

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by srimanob** [comment]
+Upgrade

Clean up PR, to remove obsolete cfg's.

**Comment by cvuosalo** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
