### PR TITLE
Add low lumi HI jet and photon triggers HLT DQM entries

### PR DESCRIPTION
**Pull request by cfmcginn**
These are HLT DQM modules meant to be used for the low-lumi PU=0.4 runs.

### CODE REVIEW

**Comment by cfmcginn** [comment]
I don't suppose I can ask if this has been seen?

**Comment by cfmcginn** [comment]
Apologies for above set of commits+reverts, accidental and not related to this PR. Thanks for your patience.

**Comment by mmusich** [comment]
-1
needs rebase

**Comment by slava77** [comment]
-1
(rebase; then reco signature will not be needed)

**Comment by ggovi** [comment]
-1

**Pull request closed without merging**
