### PR TITLE
Fix plugins in HLTrigger/JetMET

### PR DESCRIPTION
**Pull request by davidlange6**
move plugins into plugins directory (with other plugins) as not to rely on luck that exactly one plugin library links against HLTrigger/JetMET/src

### CODE REVIEW

**Comment by davidlange6** [comment]
@cmsbuild, please test

**Comment by davidlange6** [comment]
@cmsbuild, please test

**Comment by Dr15Jones** [comment]
@smuzaffar @davidlange6 Maybe we should start scanning lib*.so for plugins and issuing errors if they are found?

**Comment by smuzaffar** [comment]
I agree. Is there any symbol which one can look in the lib*.so?

**Comment by Dr15Jones** [comment]
@smuzaffar I don't believe a symbol exists. It is possible to make a simple executable that would return a particular value if a plugin was found in a loaded library.

**Pull request merged**
