### PR TITLE
Improve friendly class names of unordered_set and unordered_map

### LINKED ISSUE #29967: Can not produce std::unordered_map - illegal underscore
Trying to replace an `std::map` with an `std::unordered_map` [here](https://github.com/lecriste/cmssw/commit/2d7e96c18eada02ffb7c1f3754fb20e00255c749#diff-de159032ed18703ecac25de24a34f686), `cmsRun` throws the exception below.

The branch can be tested in `CMSSW_11_1_0_pre7`.

```
An exception of category 'IllegalCharacter' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing module: class=HGCalRecHitMapProducer label='hgcRecHitMapProducer'
Exception Message:
Class name 'DetIdconstHGCRecHitptrDetIdstdhashDetIdstdequal_tostdunordered_map' contains an underscore ('_'), which is illegal in the name of a product.
```

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

This PR is a follow-up to https://github.com/cms-sw/cmssw/pull/29987 to handle the default `Hash` and `KeyEqual` template arguments (they get ignored for the friendly class name), and also custom `Hash` template argument. Resolves #29967.

#### PR validation:

Unit test runs.

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
@Dr15Jones please review

**Comment by lecriste** [comment]
@makortel can this be merged?

**Comment by Dr15Jones** [comment]
I suggest adding a test where the Key and maybe the type are std::basic_string<char> to be sure that embedded <> work properly in the substitution.

**Comment by makortel** [comment]
> I suggest adding a test where the Key and maybe the type are std::basic_string to be sure that embedded <> work properly in the substitution.

Thanks, will do.

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by silviodonato** [comment]
+1

**Pull request merged**
