### PR TITLE
Out of time photons in miniAOD

### PR DESCRIPTION
**Pull request by kmcdermo**
This PR adds out-of-time photons to miniAOD, on top of PR #18844 .  This adds two new collections: slimmedOOTPhotons, slimmedOOTPhotonCores. The associated clusters, SCs, and ecal rec hits are added into the reducedEgamma collections.

The file size increase was estimated in the same way as 18844, using 1000 events from a single 2016H SinglePhoton raw file: /store/data/Run2016H/SinglePhoton/RAW/v1/000/284/035/00000/0A2C49D0-E29E-E611-92CB-02163E0142E4.root.

Adding up the size of the new collections and increases to related collections with edmEventSize -v, the uncompressed size increase is 1.4 kB / event, while the compressed size increase is 415.3 kB / event.  Simply doing ls -l, taking the difference between vanilla sequence and this sequence, the increase in size is 260.5 B / event.

Both this PR and 18844 were tested in 9_2_0_patch1 with signal MC produced in 90X (GMSB displaced photons, ctau = 6000mm) with 100 events.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by arizzi** [comment]
how can the file size increase less than what reported by edmEventSize? (if anything the opposite would be expected)
Can you run on the 9k events ttbar relvals?

Is it possible to also have a customization for re-miniaod from old-AOD that creates this collections from older AOD (we need for legacy datasets). I.e. can the whole "alternative PF sequence" be run off AOD? (or does it need to go with reco)

**Comment by kmcdermo** [comment]
The error is:
----- Begin Fatal Exception 19-May-2017 08:01:06 CEST-----------------------
An exception of category 'ProductNotFound' occurred while
   [0] Processing  Event run: 194533 lumi: 329 event: 461582793 stream: 0
   [1] Running path 'MINIAODoutput_step'
   [2] Prefetching for module PoolOutputModule/'MINIAODoutput'
   [3] Prefetching for module PATPhotonSlimmer/'slimmedOOTPhotons'
   [4] Prefetching for module PATPhotonSelector/'selectedPatOOTPhotons'
   [5] Prefetching for module PATPhotonProducer/'patOOTPhotons'
   [6] Calling method for module MCMatcher/'ootPhotonMatch'
Exception Message:
Principal::getByToken: Found zero products matching all criteria
Looking for type: std::vector<reco::GenParticle>
Looking for module label: prunedGenParticles
Looking for productInstanceName: 

I am a bit surprised it failed on finding the product "prunedGenParticles", as this is used by the other mcMatch modules.  How do I fix this?

**Comment by davidlange6** [comment]
it looks like the crashes are on real data - so you don't expect prunedGenParticles...

**Comment by kmcdermo** [comment]
Ah, duh.  Well, I cloned the photonProducer_cff.py, and was expecting to see addGenMatch = cms.bool(False)  in miniAOD_tools.py to override the default True, but I do not see it anywhere for the standard photon sequence.

What is the best option here?  Set addGenMatch = cms.bool(False) as the default inside ootPhotonProducer_cff.py, and then override it to True inside miniAOD_customizeMC?

**Comment by kmcdermo** [comment]
@arizzi I must admit I was very confused by the difference in size results between ls -l and edmEventSize... I am no expert on this.  

As for re-miniaod from old AOD I would assume is possible. This would require building a sequence that takes in the reducedRecHits as input for the EcalRecHits, but otherwise would be the same.  Is there an example of a config on how to do something similar?   I can make one quickly and test it locally, then commit it.

**Comment by kmcdermo** [comment]
okay, I managed to fix the problem. I simply ran step2.py and step3.py of https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-18845/19979/runTheMatrix-results/4.53_RunPhoton2012B+RunPhoton2012B+HLTD+RECODR1reHLT+HARVESTDR1reHLT/

and it worked.

**Comment by perrotta** [comment]
please test

**Comment by slava77** [comment]
On 5/19/17 1:24 AM, Kevin McDermott wrote:
> @arizzi <https://github.com/arizzi> I must admit I was very confused by
> the difference in size results between ls -l and edmEventSize... I am no
> expert on this.
> 
> As for re-miniaod from old AOD I would assume is possible. This would
> require building a sequence that takes in the reducedRecHits as input
> for the EcalRecHits, but otherwise would be the same. Is there an
> example of a config on how to do something similar? I can make one
> quickly and test it locally, then commit it.

Isn't the reducedRecHits from current standard AOD collection unsuitable
for you?
If instead it is suitable, why bother with all the changes to AOD/RECO?

**Comment by arizzi** [comment]
@slava77 because we do not want to run a part of RECO in miniAOD... so while AOD contains the information they better run the various producers in RECO (pretty much like "if Jets can be made from AOD  (or even miniAOD) why bother running them in RECO")

**Comment by kmcdermo** [comment]
Hi @slava77 ,  the reducedRecHits at AOD are suitable without the OOT cleaning.  As we have seen in signal MC, we have all of the seed recHits, and 99.9% of the recHits from the signal photons.  However, to produce the photon collections, we would still need to modify the PFSuperClusterAlgo in order to filter out on OOT SCs.  

And then when moving from AOD to miniAOD, the ReducedEGProducer drops all of our signal seed recHits -- so to keep the recHits it either requires making a new producer to save them, or running the RECO anyway.

**Comment by slava77** [comment]
On 5/19/17 5:35 AM, arizzi wrote:
> @slava77 <https://github.com/slava77> because we do not want to run a
> part of RECO in miniAOD... so while AOD contains the information they
> better run the various producers in RECO (pretty much like "if Jets can
> be made from AOD (or even miniAOD) why bother running them in RECO")

I guess the answer to the first question about reduced ECAL rechits be
suitable
is "yes", it is suitable.
In this case, the particleFlowSuperClusterOOTECAL should probably move
to it.

**Comment by arizzi** [comment]
@kmcdermo I think what we need for the legacy reminiaod is to have the RECO-recipe of this PR applied starting from reducedRecHits rather than all recHits (this will be non perfect by 100% vs 99.9%) that should be perfectly fine for the legacy dataset

**Comment by arizzi** [comment]
@slava77 exactly! (to both your comments.)

**Comment by kmcdermo** [comment]
@arizzi Yes, the only input into particleFlowOOTECALRecHits is EcalRecHits, so we could use reducedEcalRecHits.

However, to do the reminiaod from AOD, we would need the hcal CaloTowers to compute HoverE.  Or, we could redo making the hcal towers from the hcal recHits.  

@slava77 , so if we were to move to reducedRecHits as the input, then we would still need to run the reducedRecHits producer again -- also with the same caveat of the HoverE for the hcal recHits.

**Comment by slava77** [comment]
On 5/19/17 5:49 AM, Kevin McDermott wrote:
> @arizzi <https://github.com/arizzi> Yes, the only input into
> particleFlowOOTECALRecHits is EcalRecHits, so we could use
> reducedEcalRecHits.
> 
> However, to do the reminiaod from AOD, we would need the hcal CaloTowers
> to compute HoverE. Or, we could redo making the hcal towers from the
> hcal recHits.

There are no caloTowers or hcal rechits in AOD.

**Comment by arizzi** [comment]
mhh how about accessing HCAL information from PFClusters?

**Comment by kmcdermo** [comment]
@slava77 , if I edmDumpEventContent of one of the AOD file I produce from this sequence, I see the following collections:

edm::SortedCollection<HBHERecHit,edm::StrictWeakOrdering<HBHERecHit> >    "reducedHcalRecHits"        "hbhereco"        "RECO"    
edm::SortedCollection<HFRecHit,edm::StrictWeakOrdering<HFRecHit> >    "reducedHcalRecHits"        "hfreco"          "RECO"    
edm::SortedCollection<HORecHit,edm::StrictWeakOrdering<HORecHit> >    "reducedHcalRecHits"        "horeco"          "RECO"

is this enough to get HoverE?

**Comment by slava77** [comment]
On 5/19/17 6:19 AM, Kevin McDermott wrote:
> @slava77 <https://github.com/slava77> , if I edmDumpEventContent of one
> of the AOD file I produce from this sequence, I see the following
> collections:
> 
> edm::SortedCollection<HBHERecHit,edm::StrictWeakOrdering >
> "reducedHcalRecHits" "hbhereco" "RECO"
> edm::SortedCollection<HFRecHit,edm::StrictWeakOrdering >
> "reducedHcalRecHits" "hfreco" "RECO"
> edm::SortedCollection<HORecHit,edm::StrictWeakOrdering >
> "reducedHcalRecHits" "horeco" "RECO"
> 
> is this enough to get HoverE?

no.
IIRC, these include bad hits and hits crossed by muons

**Comment by arizzi** [comment]
https://github.com/cms-sw/cmssw/blob/09c3fce6626f70fd04223e7dacebf0b485f73f54/RecoEgamma/EgammaIsolationAlgos/python/interestingEgammaIsoDetIdsSequence_cff.py#L67

**Comment by arizzi** [comment]
i.e. I am afraid if no photons or ele was made near those hcal hits you would not get any hcal hit

**Comment by slava77** [comment]
On 5/19/17 6:38 AM, arizzi wrote:
> https://github.com/cms-sw/cmssw/blob/09c3fce6626f70fd04223e7dacebf0b485f73f54/RecoEgamma/EgammaIsolationAlgos/python/interestingEgammaIsoDetIdsSequence_cff.py#L67

Thanks, indeed, hcal hits for existing ged is in (I should remember this
addition from Sam)

**Comment by arizzi** [comment]
the only thing you can do is access PFCandidate::hcalEnergy() or something like that for candidates that are in the eta/phi of your interest.

how many jets would we start to add as OOT photons if we go for no h/e cut (i.e. we pass the interestingHCAL rechits and accept that this does nothing in many case) ?
If the "background" in the end is small we can go with this and cook something based on PFCandidate hcal fraction downstream

**Comment by slava77** [comment]
errors in runtestPhysicsToolsPatAlgos reported in https://github.com/cms-sw/cmssw/pull/18845#issuecomment-302677352 are related:

running patTuple_addTriggerInfo_cfg.py
```
   [2] Prefetching for module CandidateSummaryTable/'selectedPatCandidateSummary'
   [3] Prefetching for module PATPhotonSelector/'selectedPatOOTPhotons'
   [4] Prefetching for module PATPhotonProducer/'patOOTPhotons'
   [5] Calling method for module MCMatcher/'ootPhotonMatch'
Exception Message:
Principal::getByToken: Found zero products matching all criteria
Looking for type: std::vector<reco::GenParticle>
Looking for module label: prunedGenParticles
Looking for productInstanceName: 
```

**Comment by kmcdermo** [comment]
Hi @arizzi , so on the limited stats, we added only 7 photons out of 1k events to miniAOD (down from 26) using a random 2016H SinglePhoton file, filtering from AOD to miniAOD on pt() > 10 and hadTowerOverEm() < 0.15:

https://github.com/kmcdermo/cmssw/blob/66c8eacf6ee55cee922da2c40dfdf0c95c907d22/RecoEgamma/EgammaPhotonProducers/python/reducedEgamma_cfi.py#L7-L9

I can try to remove the HoverE cut and see how many more we push_back to miniAOD.

**Comment by kmcdermo** [comment]
Hi @slava77 , I tried playing with this a bit, and I think what is happening is that these files are trying to start straight from AOD and go to miniAOD and my collections do not yet exist.  So I need to make a special sequence that starts from AOD if the OOT sequence at RECO was not run, do the OOT sequence with the reducedEcalRecHits as input to the PFRecHit Producer, and keep this as a transient product.  However, this again comes back to the problem about computing HoverE...

**Comment by slava77** [comment]
On 5/22/17 8:31 AM, Kevin McDermott wrote:
> Hi @slava77 <https://github.com/slava77> , I tried playing with this a
> bit, and I think what is happening is that these files are trying to
> start straight from AOD and go to miniAOD and my collections do not yet
> exist. So I need to make a special sequence that starts from AOD if the
> OOT sequence at RECO was not run, do the OOT sequence with the
> reducedEcalRecHits as input to the PFRecHit Producer, and keep this as a
> transient product. However, this again comes back to the problem about
> computing HoverE...

If there is no significant urgency, then we can update AOD with the
other PR,
wait for relvals, update input in these tests, and then integrate this PR.

**Comment by kmcdermo** [comment]
That's fine by me, with the understanding that we will still need to make the re-miniAOD sequence, which can be integrated into this PR (or a new one).

Also, I want to add in regression / PFClusterIsolation into this PR. I am waiting to hear back from Josh and Sam on the best way to do this.

**Comment by kmcdermo** [comment]
To update:

- input collections from AOD changed in PR #18844 
- include PFClusterIsolations into slimmedOOTPhotons
- unmerge basic clusters and superclusters into separate collections for OOT photons
- include sequence for photon regression
- insert sequence to start from AOD to run over reducedRecHits for legacy reprocessing: will require 
some workarounds for HoverE and hadronic isolations

With all this in mind, would it be better to close this PR, and open a new one when it is ready?

**Comment by slava77** [comment]
On 5/31/17 12:48 PM, Kevin McDermott wrote:
> With all this in mind, would it be better to close this PR, and open a
> new one when it is ready?
> 

yes.
Well, you can reopen this one and update it after 18844 is merged

**Pull request closed without merging**
