### PR TITLE
Review occupancy test

### PR DESCRIPTION
**Pull request by fcavallo**

### CODE REVIEW

**Comment by dmitrijus** [comment]
+1
Code looks fine, but in order for this to be merged, you need a better title/description of this PR, and a link to 81x version if it (nothing in 80x is merged before 81x).

**Comment by davidlange6** [comment]
@fcavallo @dmitrijus - what is the 81x version of this?

**Comment by fcavallo** [comment]
Hi. sorry I kind of lost the thread. So am I supposed to make the same PR in 81x before having this one merged?

**Comment by davidlange6** [comment]
Hi @fcavallo - yes (as always, we test in the development release first)

**Comment by davidlange6** [comment]
+1

**Pull request merged**
