### PR TITLE
Use C++ concepts for edm::Ptr

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

Used to improve handling of constructors for edm::Ptr's related to other types.

#### PR validation:

The code compiles and the relevant unit test passes.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
please test

**Comment by mmusich** [comment]
> -1

failing tests will be fixed by https://github.com/cms-sw/cmssw/pull/45764 and https://github.com/cms-sw/cmssw/pull/45775

**Comment by makortel** [comment]
+core

**Comment by makortel** [comment]
ignore tests-rejected with ib-failure

**Comment by mandrenguyen** [comment]
+1

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
