### PR TITLE
SiPixelDynamicInefficiency DB object

### PR DESCRIPTION
**Pull request by bartokm**
New DB object for SiPixelDynamicInefficiency which will be used by SiPixelDigitizerAlgorithm. For more details see:
https://indico.cern.ch/event/368338/contribution/1/material/slides/0.pdf

### CODE REVIEW

**Comment by bartokm** [comment]
Dear experts,
Could you please take a look into the code and approve/suggest modifications to it? I'm planning another PR depending on this one, and it would be convinient if both of them could go in 7_5_X.
Thanks!

cheers,
Márton

**Comment by mmusich** [comment]
+1 
based on the discussion we had at the [AlCa/DB meeting 05.05.14](https://indico.cern.ch/event/368338/contribution/1/material/slides/0.pdf)

**Comment by hidaspal** [comment]
Hello, could you please also review and eventually sign it for db-pending? Thanks, Pal

**Comment by ggovi** [comment]
+1

**Comment by hidaspal** [comment]
Thanks, Giacomo. :-) Cheers, Pal

**Comment by davidlange6** [comment]
@bartokm , @ggovi - how big to we expect this payload to be in time? I wonder if we should future proof it by making the doubles into floats?

**Comment by veszpv** [comment]
David, the payload (sqlite file) size ranges between 10 KB to 12 KB. Changing the doubles to floats would mean a reduction of 30% at best, theoretically. We have just tested it in practice and got a ~10% reduction. If you insist, we could change the PR but not without a guarantee that it will be accepted today.

It is very important that this PR gets accepted today. We have already agreed with the AlCaDB guys that once there is a new build, they will give us a DB tag for testing the digitizer part that reads this payload. The modifications in the digitizer will go into another PR, which would also need to fit in 750, so that we can make the inefficiency simulation configurable for potential rereco.

**Comment by davidlange6** [comment]
Hi Viktor

so there is then no chance that the scope of this format expands to something like one entry per pixel Det Id?

**Comment by veszpv** [comment]
Hi David,

I consider that impossible. There may be some chance that eventually we 
introduce an additional efficiency loss mechanism for ROCs which would 
approximately double the size of the present payload (if using the 
present scheme for parameterization). But such a mechanism would be less 
motivated from the point of view of detector design than the dcol loss 
we have implemented. Also, it would require some significant study, 
which could probably take another year.

**Comment by davidlange6** [comment]
Thanks - a factor of 2 growth is no issue for me

**Comment by davidlange6** [comment]
+1

**Pull request merged**
