### PR TITLE
extendedO2O

### PR DESCRIPTION
**Pull request by kkotov**
For now we agreed to resort to the original version of the L1T O2O that pushes only the L1TMenu to the production CondDB.

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
@kkotov there are compilation errors in this branch. Can you please follow-up?
Thanks,
M.

**Comment by kkotov** [comment]
@mmusich , seems like CMSSW framework is migrating from boost the c++11 standard by replacing all boost:shared_ptr with std::shared_ptr. I'll make the change to the branch for new iteration, but this defeats the purpose of having this intermediate branch in the official release as the code will technically be different from what we ran all this time at p5.

**Comment by mmusich** [comment]
@kotov, well the backport of this PR in 80X won't be technically different from the one being run at P5, right?
Thanks,

Marco

**Comment by kkotov** [comment]
@mmusich , right, I can do that. How do I backport, then? Should I just try to submit this PR to 8_0_x? Would the change in CondFormats pose a problem in the old release?

**Comment by mmusich** [comment]
Thanks Khristian, about the change in CondFormats, if those were never been used (never been in a production GT), it should not be a problem. I let Giacomo @ggovi comment here, since he's the final word.

**Comment by kkotov** [comment]
@mmusich the only change to the CondFormats are the two new classes: L1TriggerKeyExt and L1TriggerKeyListExt, used solely for the L1T O2O bookkeeping and never meant to be requested for GT. I'm now submitting the PR to 8_0_x ...

**Comment by davidlange6** [comment]
please test

**Comment by ggovi** [comment]
@kkotov 
ping

**Comment by mulhearn** [comment]
(khristian is actually working on fix instead of just checking github like me!)

**Pull request closed without merging**
