### PR TITLE
multithreading fix for 74x: HLTrigReport

### PR DESCRIPTION
**Pull request by fwyzard**
Migrate summary modules
- HLTrigReport
  to one::EDAnalyzer. They could be migrated to global::EDAnalyzer, but since we do not run them online it's probably not worth it.

### CODE REVIEW

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
tracked at #11317

**Comment by fwyzard** [comment]
+1

**Comment by fwyzard** [comment]
backpot (part of) #11054 to 74x

**Comment by fwyzard** [comment]
rebased to merge on top of both CMSSW_7_4_X and CMSSW_7_4_12_patch4

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
