### PR TITLE
add missing-, inactive-, valid-hits and clusterChargePerCm TkMaps

### PR DESCRIPTION
**Pull request by rrabadan**
valid, missing and inactive recHit TrackerHistoMaps added. 
inclusiveClusterCharge, ClusterChargePerCMfromOrigin and ClusterChargePerCMfromTrack TkHistoMaps also added.
inclusiveClusterCharge and ClusterChargePerCMfromTrack configurable.
SiStripDQM_OfflineTkMap_Template_cfg_DB.py updated to create the corresponding new TkMaps

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
please submit to 76x and 80x as well.
thanks,
F.

**Comment by deguio** [comment]
seems ok to me

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
