### PR TITLE
Update trigger filters for jets stored in Nano for Run3 menu

### PR DESCRIPTION
**Pull request by johnalison**
#### PR description:

Updating the Jet Trigger objects stored in Nano with the filters from the Run3 menu
Expect the trigObj content of the Nano to change.

#### PR validation:

Tested producing new NanoAOD in 12_4_8

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

The original PR is https://github.com/cms-sw/cmssw/pull/39818
This is needed for NanoProduction

### CODE REVIEW

**Comment by perrotta** [comment]
backport of https://github.com/cms-sw/cmssw/pull/39818

**Comment by vlimant** [comment]
enable nano
please test

**Comment by swertz** [comment]
please test

**Comment by swertz** [comment]
enable none

**Comment by swertz** [comment]
please test

**Comment by swertz** [comment]
please test

One more try... the test failure looks spurious.

**Comment by swertz** [comment]
+1

**Comment by rappoccio** [comment]
+1 

* Changes in nanoDQM are expected.

**Pull request merged**
