### PR TITLE
Fixed materials discrepancies between DDD and DD4hep: remove duplicate definitions of Phase 1 materials (FPix_CFSkin and cie)

### PR DESCRIPTION
**Pull request by ghugo83**
A discrepancy in the DDD <-> DD4hep materials comparison was stemming from duplicate definitions of FPix_CFSkin (and FPix_CFSkin_OuterOuterRing, etc...).

With DDD the first definition was considered, in DD4hep the second. 
Chose the composition containing H and O in addition to C (a carbon fiber with C only does not seem realistic to manufacture anyway).

- DDD:
```
Material: FPix_CFSkin_OuterOuterRing  made of C only 
 Range cuts        :  gamma  1 mm     e-  1 mm     e+  1 mm  proton 1 mm 
 Energy thresholds :  gamma  3.34104 keV    e-  570.85 keV    e+  555.71 keV proton 100 keV
```

- DD4hep:
```
Material: pixfwdMaterials:FPix_CFSkin_OuterOuterRing made of C, H, O
Range cuts        :  gamma  1 mm     e-  1 mm     e+  1 mm  proton 1 mm 
Energy thresholds :  gamma  3.50195 keV    e-  602.38 keV    e+  578.575 keV proton 100 keV
```

Not sure how to proceed in terms of 2021 scenarios though, as this is a small fix. Created the v3 version.

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
@ghugo83 , I think, that we understand this probably correct would be using compound material both in DDD and DD4Hep. Because Run-3 geometry is not yet frozen we can do this. Also you are right making new version of the material file.

**Comment by ghugo83** [comment]
>Because Run-3 geometry is not yet frozen we can do this.

How do we proceed to include this file, is it fine to modify T3?

**Comment by ghugo83** [comment]
Alright, just added it to T3.

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
+1

**Comment by civanch** [comment]
@srimanob, please, have a look

**Comment by srimanob** [comment]
+Upgrade

**Comment by qliphy** [comment]
+1

**Pull request merged**
