### PR TITLE
Run4-hgx254 Remove usage of magic numbers in the HGCal geometry code

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Remove usage of magic numbers in the HGCal geometry code

#### PR validation:

Tested using runTheMatrix test workflows 

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by kpedro88** [comment]
+upgrade

**Comment by cvuosalo** [comment]
+1

**Comment by cvuosalo** [comment]
Thanks. This implementation is much cleaner.

**Comment by civanch** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
