### PR TITLE
Phase2-TB60 Add a scenario with 1mm production cutoff in HGCal TB

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Add a scenario with 1mm production cutoff in HGCal TB October 2018 setup

#### PR validation:

Tested using a test script in SimG4CMS/HGCalTestBeam/test

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

**Comment by qliphy** [comment]
+1

**Pull request merged**
