### PR TITLE
Use correct beamspot for 2016 MC + update MC tracker alignment scenario for 2016 pre-VFP era [11_0_X]

### PR DESCRIPTION
**Pull request by christopheralanwest**
#### PR description:

This PR is a trivial backport of PR #28624. The updates contained in this PR will be included in the 10_6_X 2016 UL production and the changes have already been merged in master. A 10_6_X backport PR will be prepared as well.

I'm not certain that an 11_0_X backport is strictly necessary as no 2016 production campaign is planned for 11_0_X; the 10_6_X backport is more important. But since these changes will be used in both 11_1_X and 10_6_X, it seems less confusing to have the changes in 11_0_X as well. Since this PR is mainly intended for the bookkeeping of sensible default values for RelVal workflows, I will let PdmV experts decide if they want it merged in 11_0_X as well.

#### PR validation:

The changes have been validated within the 2016 10_6_X UL campaign: https://indico.cern.ch/event/865993/#15-tracker-on-ul-16

In addition, a technical test was performed: `runTheMatrix.py -l limited,7.22 --ibeos`

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

This PR is a backport of PR #28624.

### CODE REVIEW

**Comment by christopheralanwest** [comment]
backport #28624

**Comment by christopheralanwest** [comment]
please test workflow 7.22

**Comment by chayanit** [comment]
+1

**Comment by christopheralanwest** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by silviodonato** [comment]
Kind reminder to
analysis: 
 @santocch
upgrade: 
 @kpedro88

**Comment by kpedro88** [comment]
+upgrade
@silviodonato i'm not sure if we will get analysis signatures any more

**Comment by silviodonato** [comment]
merge
(@santocch please have a look)

**Comment by santocch** [comment]
+1

**Pull request merged**
