### PR TITLE
Modernized TkTransientTrackingRecHitBuilderESProducer

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

- Removed headers and put declaration in .cc files
- Removed use of module.cc file
- Pulled out parameters in constructor
- Wrote fillDescriptions
- Used edm::ESGetToken

#### PR validation:

The code compiles. This is a refactoring and should not change any results.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
please test

**Comment by perrotta** [comment]
+1
- Technical
- Code changes in line with the PR description
- Jenkins tests pass and show no difference

**Comment by fabiocos** [comment]
+1

**Comment by makortel** [comment]
part of #26748

**Pull request merged**
