### PR TITLE
75 fireworks: port changes from 7_4_X, related to ROOT6 dictionaries 

### PR DESCRIPTION
**Pull request by alja**
This is port of changes in PR  #8662

### CODE REVIEW

**Comment by alja** [comment]
+1

**Comment by Dr15Jones** [comment]
The test failure is unrelated to this pull request.

**Comment by alja** [comment]
Why this PR was not included in 7_5_0_pre3?

**Comment by davidlange6** [comment]
@alja - sorry , was already in the process of building as this came in - as the tests failed (not due to this PR), I didn't try to include it.

**Pull request merged**
