### PR TITLE
Add new GEM electronics map to all GTs

### PR DESCRIPTION
**Pull request by tvami**
#### PR description:

This PR 
 * adds new GEM electronics map as requested in https://cms-talk.web.cern.ch/t/new-gem-electronics-mapping/10914
 * the same thing to the data GTs, thus we created new snapshotted (frozen) GTs 
 * took that chance to decouple the express and prompt tags for ECAL intercalibration as requested in https://cms-talk.web.cern.ch/t/gt-online-prompt-ecal-intercalibration-prompt-tag-for-run3/10789

This is a prerequisite of https://github.com/cms-sw/cmssw/pull/38062 (i.e. this has to merge first, or at the same time as 38062).

Diff of GTs:

**run2_data**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts//123X_dataRun2_v2/123X_dataRun2_v3

**run2_data_HEfail**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts//123X_dataRun2_HEfail_v2/123X_dataRun2_HEfail_v3

**run2_data_relval**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts//123X_dataRun2_relval_v2/123X_dataRun2_relval_v4

**run2_data_promptlike_hi**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts//123X_dataRun2_PromptLike_HI_v2/123X_dataRun2_PromptLike_HI_v3

**run2_hlt_relval**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts//123X_dataRun2_HLT_relval_v2/123X_dataRun2_HLT_relval_v3

**run3_hlt**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts//123X_dataRun3_HLT_frozen_v2/123X_dataRun3_HLT_frozen_v5

**run3_hlt_relval**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts//123X_dataRun3_HLT_relval_v5/123X_dataRun3_HLT_relval_v9

**run3_data_express**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts//123X_dataRun3_Express_frozen_v2/123X_dataRun3_Express_frozen_v4

**run3_data_prompt**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts//123X_dataRun3_Prompt_frozen_v2/123X_dataRun3_Prompt_frozen_v4

**run3_data**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts//123X_dataRun3_v5/123X_dataRun3_v7

**run3_data_relval**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts//123X_dataRun3_relval_v4/123X_dataRun3_relval_v6

**phase1_2017_design**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts//123X_mc2017_design_v1/123X_mc2017_design_v2

**phase1_2017_realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts//123X_mc2017_realistic_v1/123X_mc2017_realistic_v2

**phase1_2017_cosmics**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts//123X_mc2017cosmics_realistic_deco_v1/123X_mc2017cosmics_realistic_deco_v2

**phase1_2017_cosmics_peak**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts//123X_mc2017cosmics_realistic_peak_v1/123X_mc2017cosmics_realistic_peak_v2

**phase1_2018_design**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts//123X_upgrade2018_design_v2/123X_upgrade2018_design_v4

**phase1_2018_realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts//123X_upgrade2018_realistic_v1/123X_upgrade2018_realistic_v2

**phase1_2018_realistic_rd**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts//123X_upgrade2018_realistic_RD_v1/123X_upgrade2018_realistic_RD_v3

**phase1_2018_realistic_hi**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts//123X_upgrade2018_realistic_HI_v1/123X_upgrade2018_realistic_HI_v2

**phase1_2018_realistic_HEfail**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts//123X_upgrade2018_realistic_HEfail_v1/123X_upgrade2018_realistic_HEfail_v2

**phase1_2018_cosmics**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts//123X_upgrade2018cosmics_realistic_deco_v1/123X_upgrade2018cosmics_realistic_deco_v2

**phase1_2018_cosmics_peak**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts//123X_upgrade2018cosmics_realistic_peak_v1/123X_upgrade2018cosmics_realistic_peak_v2

**phase1_2021_design**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts//124X_mcRun3_2021_design_v1/124X_mcRun3_2021_design_v3

**phase1_2021_realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts//124X_mcRun3_2021_realistic_v1/124X_mcRun3_2021_realistic_v3

**phase1_2021_cosmics**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts//124X_mcRun3_2021cosmics_realistic_deco_v2/124X_mcRun3_2021cosmics_realistic_deco_v4

**phase1_2021_cosmics_design**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts//124X_mcRun3_2021cosmics_design_deco_v1/124X_mcRun3_2021cosmics_design_deco_v3

**phase1_2021_realistic_hi**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts//124X_mcRun3_2021_realistic_HI_v1/124X_mcRun3_2021_realistic_HI_v3

**phase1_2023_realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts//124X_mcRun3_2023_realistic_v1/124X_mcRun3_2023_realistic_v3

**phase1_2024_realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts//124X_mcRun3_2024_realistic_v1/124X_mcRun3_2024_realistic_v3

**phase2_realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts//124X_mcRun4_realistic_v2/124X_mcRun4_realistic_v4

They all contain the new GEM electronics map changes. 

Diffs for the snapshotted vs open GTs
* https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_dataRun3_HLT_v9/123X_dataRun3_HLT_frozen_v4
* https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_dataRun3_Express_v8/123X_dataRun3_Express_frozen_v4
* https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_dataRun3_Prompt_v10/123X_dataRun3_Prompt_frozen_v4
(here the only diff is the snapshot time)

#### PR validation:
test parameters:
  - workflows = 12034.0,11634.0,7.23,159.0,12434.0,12834.0

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Not a backport, but backport is needed in 12_3_X and 12_4_X too

### CODE REVIEW

**Comment by tvami** [comment]
test parameters:
  - workflows = 12034.0,11634.0,7.23,159.0,12434.0,12834.0

**Comment by tvami** [comment]
type gem,ecal

**Comment by tvami** [comment]
hold
 * we possible need to update the Run-2 GTs too, see https://github.com/cms-sw/cmssw/pull/38062#issuecomment-1137877530

**Comment by tvami** [comment]
unhold

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
@cmsbuild , please test with https://github.com/cms-sw/cmssw/pull/38062

**Comment by smuzaffar** [comment]
@cmsbuild , please test with #38062

**Comment by smuzaffar** [comment]
@tvami , no idea what had happened. Previous job https://cmssdt.cern.ch/jenkins/job/ib-run-pr-tests/25141/console was killed by bot itself. May be there were two pending jobs and both killed each other? Anyway, it is running now

**Comment by tvami** [comment]
+alca
 * no diffs are seen, 
 * tested together with https://github.com/cms-sw/cmssw/pull/38062 but this can go in first , @cms-sw/orp-l2 it would be nice to have this in the 11 AM IB

**Comment by qliphy** [comment]
+1

**Pull request merged**
