### PR TITLE
Pythia8 shower weights and labels saving

### PR DESCRIPTION
**Pull request by pmandrik**
Pythia8 shower weights and labels saving (http://home.thep.lu.se/~torbjorn/pythia82html/Variations.html) in GeneratorInterface/Pythia8Interface/plugins/Pythia8Hadronizer.cc

### CODE REVIEW

**Comment by pmandrik** [comment]
please test

**Comment by perrozzi** [comment]
please test

**Comment by perrozzi** [comment]
@davidlange6 any issue with the bot not starting tests?

**Comment by perrozzi** [comment]
please test

**Comment by pmandrik** [comment]
Similar to
https://github.com/cms-sw/cmssw/pull/16533
https://github.com/cms-sw/cmssw/pull/16535
https://github.com/cms-sw/cmssw/pull/16538

probably, not related to this PR

----- Begin Fatal Exception 10-Nov-2016 00:49:28 CET-----------------------
An exception of category 'DatabaseError ' occurred while
   [0] Processing run: 160960
   [1] Calling global beginRun for module LumiProducer/'lumiProducer'
Exception Message:
Can not get data (Additional Information: [frontier.c:1124]: No more proxies. Last error was: Request 83 on chan 2 failed at Thu Nov 10 00:49:28 2016: -8 [payload.c:101]: Server signalled payload error 1: LumiProd java.sql.SQLException: ORA-00942: table or view does not exist at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:456)) ( CORAL : "coral::FrontierAccess::Statement::execute" from "CORAL/RelationalPlugins/frontier" )
----- End Fatal Exception -------------------------------------------------

**Comment by perrozzi** [comment]
please test

**Comment by perrozzi** [comment]
@bendavid did you check this?

**Comment by bendavid** [comment]
Yes, I've looked at this and it should go into the release to facilitate testing.  (It's disabled by default at the pythia config level, and can be enabled in the default pythia options fragment after the physics implications have been more thoroughly tested.)

**Comment by perrozzi** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
