### PR TITLE
Conversion from lowPtGsfTracks backported to 10_2_x

### PR DESCRIPTION
**Pull request by nancymarinelli**

### CODE REVIEW

**Comment by nancymarinelli** [comment]
@perrotta @bainbrid

The fixes are on their way. I need, maybe from @bainbrid, hits about how 
to go for selecting the era



On 06/02/19 08:22, perrotta wrote:
> -1
> Please implement in this backport PR the same adjustments that were finally introduced in #25595, now merged in the master. Please keep in mind that in 10_2 will be produced only conditionally to the bParking era
>

-- 
________________________________________
Nancy Marinelli
Research Associate Professor
University of Notre Dame, IN, US
CERN, Bdg 40/3-A01, 1211 Geneva
SWITZERLAND
Phone +41-22-76-70809
fax +41-22-76-78940

**Comment by nancymarinelli** [comment]
@perrotta @bainbrid OK for the era, I see what has been done for lowPt electrons. I will follow the same lines

**Comment by perrotta** [comment]
backport of #25595

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
+1
- Correct backport of the corresponding pull request merged in the master
- In 10_2_X, lowPtElectrons reconstruction is only performed if the bParking era is enabled: there must be no changes in the default processing, and none is seen in the outputs of the jenkins tests
- Verified that the newly added modules/sequences correctly run when the bParking era is enabed

**Comment by nancymarinelli** [comment]
@perrotta What else is needed to be merged ?

**Comment by kpedro88** [comment]
It will be merged for the next 10_2_X release

**Comment by fabiocos** [comment]
+operations

the backport of modifications to the StandardSequences differs from the master version in the request of being activated only for the bParking Era

**Comment by fabiocos** [comment]
+1

**Pull request merged**
