### PR TITLE
cleanup HLTHcalCalibTypeFilter

### PR DESCRIPTION
**Pull request by fwyzard**
Remove unused variables, and merge the header file into the implementation.

### CODE REVIEW

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
please test

**Comment by Martin-Grunewald** [comment]
It seems you need to code a customisation function in customiseHLTforCMSSW which deletes the removed parameter(s) in all instances of the plugin where they are still present. (if hasattr... delattr)

**Comment by fwyzard** [comment]
Yeah... will do.

**Comment by fwyzard** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
