### PR TITLE
fixes for running in unscheduled mode, rebase to 76X

### PR DESCRIPTION
**Pull request by webermat**
this PR is the rebased version of PR #9939 thus should superseed it.

### CODE REVIEW

**Comment by webermat** [comment]
tested locally that both process 1302 and 11325 finish successfully

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1

**Comment by deguio** [comment]
thanks @webermat 
can you submit the same to 75 as well?
thanks,
F.

**Comment by webermat** [comment]
PR #10295 is the 75X equivalent

**Comment by davidlange6** [comment]
@cmsbuild, please test (das error before)

**Comment by webermat** [comment]
a minor fix which explains unnatural peaks around 0 in plots a la https://goo.gl/dYQ91w 
here we check that we have the PFCandidate species we fill present in the event. The check is implemented correct, but the name of the variable is not filled at the correct spot, but flipped (i.e. if the photon is in the minus endcap we fill the plus endcap pt_sum and vice versa).

**Comment by deguio** [comment]
+1

**Comment by makortel** [comment]
Hi,

(not sure if this is a proper place to ask, but I'll start here nevertheless)

Was the addition of EventContentAnalyzer to METValidationMiniAOD sequence (with module label `dump`) intentional? Running step3 of e.g. workflow 25202 in a recent IB is now very verbose unless one removes it by hand.

Cheers,
Matti

**Comment by davidlange6** [comment]
seems we like printouts in cms…
 sorry we missed that during integration

**Comment by deguio** [comment]
thanks @davidlange6 for the fix.
F.

**Pull request merged**
