### PR TITLE
Fix of path names in HLT Higgs validation code - 75X

### PR DESCRIPTION
**Pull request by silviodonato**
This PR fixes the trigger path names in the HLT validation code of Higgs group, accordingly to:
https://its.cern.ch/jira/browse/CMSHLT-405

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
@cmsbuild, please test

**Comment by davidlange6** [comment]
+1

**Pull request merged**
