### PR TITLE
Updating the upgrade queue

### PR DESCRIPTION
**Pull request by mmusich**
# Summary of changes
## 2017 Upgrade

 [75X_upgrade2017_design_v4](https://cms-conddb.cern.ch/browser/#search/Prod/75X_upgrade2017_design_v4) as  with these changes [75X_upgrade2017_design_v1](https://cms-conddb.cern.ch/browser/#search/Prod/75X_upgrade2017_design_v1) with the following [changes](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/75X_upgrade2017_design_v1/75X_upgrade2017_design_v4) : 
- new e/gamma regression for run2 
- correct Sim geometry for upgrade 
- Tracker Reco params and reco geometry for 2017 upgrade 
- New JECs from Run2 25ns 
-  Updated Hcal zero suppresion threshold 
- Updated L1 menu for Stage1

### CODE REVIEW

**Comment by mmusich** [comment]
please test 
(irrelevant not tested in IB relvals)

**Comment by diguida** [comment]
cross-PR #11599

**Comment by mmusich** [comment]
@diguida, AlCa is overdoing...

**Comment by mmusich** [comment]
@ianna you might want to follow it

**Comment by diguida** [comment]
mmhh, I move mine to 76X...

**Comment by diguida** [comment]
#11600 is the corresponding one in 76X.

**Comment by diguida** [comment]
+1

**Pull request closed without merging**
