### PR TITLE
SciLayer8 4mm sipm rad max added

### PR DESCRIPTION
**Pull request by suhokimHEP**
#### PR description:

<For GeometryD86, it's adding the 4mm sipm for HGCal scintillator tiles in Layer8 (instead of 2mm)-->

#### PR validation:

<SimCalorimetry/HGCalSimAlgos/test/hgchebacksignalscaler_cfg.py with sipmMap argument>

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by srimanob** [comment]
@cmsbuild please test workflow 38634.0

**Comment by civanch** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

This PR updates the mapping of sipm size as title said. The PR test run fine.

**Comment by qliphy** [comment]
+1

**Pull request merged**
