### PR TITLE
added NanoAOD to PromptReco

### PR DESCRIPTION
**Pull request by drkovalskyi**
#### PR description:

Added NanoAOD option to the prompt reco configuration building to be used at Tier0. This PR is critical for NanoAOD integration at Tier0 and targets first collisions. Other developments outside CMSSW (in WMCore) are on hold till we have a working pre-release or IB to use in Tier0 replays.

#### PR validation:

- Executed scram unit tests
- Tested that one can create a working configuration that produces valid output

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
Do I understand correctly that the unit tests should now pick up the new config, which will therefore get tested already in the IB tests then?

Do I understand correctly that this PR adds the `nanoAODStep` to the prompt reco by default?

You need eventually a backport to 12_3, I guess. As you know a 12_3_2 release was built just a few hours ago, mostly to satisfy the request from the T0 crew. What are the plans to deploy these further developments in the Tier0 release?

**Comment by davidlange6** [comment]
are there relvals/ (eg, runTheMatrix) workflows configured like this? cms should be testing the planned tier0 configuration..

**Comment by mariadalfonso** [comment]
> are there relvals/ (eg, runTheMatrix) workflows configured like this? cms should be testing the planned tier0 configuration..

@[davidlange6]
we have one that runs mini and nano with Run2 inputs (not in the default run3)
https://github.com/cms-sw/cmssw/blob/master/Configuration/PyReleaseValidation/python/relval_steps.py#L3297-L3305

we should eventually add more for run3

**Comment by drkovalskyi** [comment]
The only thing that is not being tested in RelVals or the matrix is the simultaneous running or reco, pat and nano. This would be good to test. I can add a test like that to the matrix.

**Comment by drkovalskyi** [comment]
Thanks @mariadalfonso. It would be good to have a test that has all 3 components, i.e. reco, pat and nano.

**Comment by davidlange6** [comment]
Yes, exactly the point. But its not just a run-without-crashing test that should be done here

**Comment by drkovalskyi** [comment]
> Yes, exactly the point. But its not just a run-without-crashing test that should be done here

There are many things that would be great to do. I would prefer to focus on the task at hands at the moment though. We can expand Tier0 testing in future.

**Comment by davidlange6** [comment]
Surely we must test what we run... not saying "you" should do it of course..

**Comment by perrotta** [comment]
@drkovalskyi @mariadalfonso should we expect such a test for Run3 to be added already to this PR, so that it can be tested (as working) at once with the new option?

**Comment by drkovalskyi** [comment]
@perrotta Having all 3 steps in one test is just a nice to have thing, because RECO and PAT are used/tested routinely at Tier0. PAT and NANO are tested by X-POG and it's the most non-trivial part. Let's integrate the changes so that we can continue integration.

**Comment by davidlange6** [comment]
This assumes that combining a+b yields the same results as running them separately... [wasn't immediately the case back when mini was added to reco for example]

**Comment by perrotta** [comment]
> > are there relvals/ (eg, runTheMatrix) workflows configured like this? cms should be testing the planned tier0 configuration..
> 
> @[davidlange6] we have one that runs mini and nano with Run2 inputs (not in the default run3) https://github.com/cms-sw/cmssw/blob/master/Configuration/PyReleaseValidation/python/relval_steps.py#L3297-L3305
> 
> we should eventually add more for run3

@mariadalfonso is that Run3 version of the workflow something that you can setup quickly? Do you think that it can be already included in this PR, to allow at least some initial "testability" for it?

**Comment by drkovalskyi** [comment]
@perrotta Could we just turn the request for additional tests into a github issue and proceed with the integration of this PR? I don't see anything urgent about having extra test implemented now and Maria may have many other urgent things to work on. At the same time this PR holds us from integrating NanoAOD into prompt reco at Tier0.

**Comment by mariadalfonso** [comment]
@perrotta @drkovalskyi 
I think it's easier for me to add more WF Run3 mini/nano on a separate followup PR. 
Also need to figure out the Run3 data we have for runTheMatrix/ Relvals .
MINI/NANO/both DQM Run2 is already there and tested at any PRs.

**Comment by perrotta** [comment]
+1
- The new option is added in view of further developments: some testing capability is expected to get provided in parallel
- Standard workflows are not affected

**Comment by davidlange6** [comment]
I mean specifically that (some) things that get validated should match with the procedure done in production . So from raw to nano. Indeed, run3 is the most relevant configuration for this validation.

**Pull request merged**
