### PR TITLE
Initialisation of CaloParticle data members

### PR DESCRIPTION
**Pull request by civanch**
#### PR description:
Address #32905. Should not affect anything.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:
no

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by perrotta** [comment]
These `nsimhits_` and `simhit_energy_` enter in a somehow complicate way in the code, and I am not sure that they are really used anywhere (if so, better to clean and avoid losing time in maintaining them).

A few questions that show up:
- shouldn't `nsimhits_` get cleared once again inside `clearHitsAndFractions()`?
- shouldnt `simhit_energy_` et cleared once again inside `clearHitsEnergy()`?

**Comment by civanch** [comment]
@perrotta , in these containers there are SimHits information and vectors of RecHits. When RecHits are cleared SimHits may be not. The purpose of this PR is to have initialisation of class members at construction - this is always a correct thing. In the update I put counting of SimHits in the correct place.

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
