### PR TITLE
Removed unnecessary caching for consumes failures

### PR DESCRIPTION
**Pull request by Dr15Jones**
Removed the caching of requests which were not registered for consumes since now we trigger a fatal exception in that case.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by Dr15Jones** [comment]
This gets rid of an unlikely thread safety issue which would happen if a module tries to get a data product for which it did not call 'consumes'. This code dates back to before that was a fatal exception.

**Comment by davidlange6** [comment]
merge

**Pull request merged**
