### PR TITLE
Backport of #19293: EXOtrigger MET & HT prompt monitoring 92X

### PR DESCRIPTION
**Pull request by rappoccio**
Backport of #19293 to 92x, since that was automatically moved to 93x.

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by fwyzard** [comment]
backport of #19293

**Comment by dmitrijus** [comment]
+1

**Comment by mtosi** [comment]
tracked by https://github.com/cms-sw/cmssw/issues/19142

**Comment by rappoccio** [comment]
Similarly to the main PR #19293, I have updated the 92x backports to include the jet+mass paths. 

https://github.com/cms-sw/cmssw/compare/CMSSW_9_2_X...rappoccio:EXOB2G_HLTMON_92xbackport_Part2

As in the other PR, once the two prerequisite PRs are merged, I will rebase this to the new IB and submit another PR for the next paths.

**Comment by rappoccio** [comment]
@davidlange6 Is this going in "as is" or do you want the changes from #19293 backported?

**Comment by rappoccio** [comment]
@davidlange6 what should I do here? The changes are ready if you want them in.

**Comment by fwyzard** [comment]
Hi,
given the amount of stuff that needs to be backported, I plan to do it in a single PR as soon as the DQM for the HLT menu v2.1 is fully integrated in 9.3.x.
If the 9.3.x equivalent of this PR has already been merged, or is listed as "Open" at #19412, can you close this PR ?

**Comment by rappoccio** [comment]
The only bit left to backport is #19820

Should I handle that or do you want to add it?

**Comment by fwyzard** [comment]
I'll do that centrally.

**Comment by rappoccio** [comment]
OK thanks!

**Pull request closed without merging**
