### PR TITLE
Fix the signature of SiStripTrivialClusterSource::beginRun()

### PR DESCRIPTION
**Pull request by makortel**
This means that earlier the `beginRun()` was not called by the framework, and as a knock-on effect the `produce()` didn't do much useful work.

Tested in CMSSW_10_5_X_2019-01-13-0000.

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
I'm a bit tempted to ask whether this class is still useful (the last non-technical commit was in 2007)?

**Comment by slava77** [comment]
> I'm a bit tempted to ask whether this class is still useful (the last non-technical commit was in 2007)?

since we can always revert a remove, why not try it now. it's not used in production (based on git grep)

@OlivierBondu @alesaggio @pieterdavid

**Comment by pieterdavid** [comment]
Indeed, it seems to be only used for purely technical testing of SiStripFEDRawDataAnalyzer (from [this config](https://github.com/cms-sw/cmssw/blob/master/EventFilter/SiStripRawToDigi/python/test/SiStripFEDRawDataAnalyzer_cfg.py)). To be honest I did not know about this class, for the latest developments we used raw files as a starting point instead.

If you think it is best to remove this I won't object, but there is more such test code in the package... I created a [task on Jira](https://its.cern.ch/jira/browse/CMSTRACK-165) to review/update that in any case (I will work on this as an EPR task in 2019).

**Comment by makortel** [comment]
@pieterdavid 
> If you think it is best to remove this I won't object, but there is more such test code in the package... I created a task on Jira to review/update that in any case (I will work on this as an EPR task in 2019).

Thanks for the comments. If you're going to review the contents of the test code in this package, I think it is easiest to leave this class as part of that exercise.

**Comment by perrotta** [comment]
+1
- technical
- jenkins tests pass
- (the class can be eventually removed if not needed any more: in the meanwhile better to have it fixed)

**Pull request merged**
