### PR TITLE
New DQM Offline sequence to be run on Express Stream 13_1_X

### PR DESCRIPTION
**Pull request by rvenditti**
Backport of https://github.com/cms-sw/cmssw/pull/42018

### CODE REVIEW

**Comment by emanueleusai** [comment]
please test

**Comment by perrotta** [comment]
+1
- The identical backport in 13_0_X was already signed and merged, as well as the PR in master. I assume that this can also get fully signed: let merge it in this intermediate release, to avoid remaining asynchronous

**Comment by perrotta** [comment]
merge

**Comment by emanueleusai** [comment]
+1

**Pull request merged**
