### PR TITLE
Make FED Occupancy plot a TProfile

### PR DESCRIPTION
**Pull request by fioriNTU**
Move to TProfile the Pixel FED occupancy plot and remove some commented code

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1

**Comment by fioriNTU** [comment]
@davidlange6 can someone restart the approval of this, the errors in the test are not depending by this PR

**Comment by smuzaffar** [comment]
@fioriNTU , this has been merged since 8th of OCT.

**Pull request merged**
