### PR TITLE
[DD4hep][Simulation] Use regex Comparison if Selection is a Regular Expression

### PR DESCRIPTION
**Pull request by ianna**
#### PR description:

* Allow to select correct sensitive detectors when their SpecPars defined as regular expressions

Note: needs a https://github.com/cms-sw/cmsdist/pull/6315

@bsunanda - FYI

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by ianna** [comment]
please test with https://github.com/cms-sw/cmsdist/pull/6315

**Comment by ianna** [comment]
@bsunanda - EB simhits are there now. I used CMSSW_11_2_X_2020-10-13-2300, so it may not have all the fixes for numbering yet.
Screenshot 2020-10-15 at 21 10 16

**Comment by bsunanda** [comment]
Yana please try #31813 on top this. It will clear the other issues hopefully
________________________________

**Comment by ianna** [comment]
> Yana please try #31813 on top this. It will clear the other issues hopefully
> […](#)

Thanks, @bsunanda ! Yes, Ecal Barrel simhits look reasonable now:
Screenshot 2020-10-15 at 23 14 32

The Ecal endcap looks like its reflected volumes are missing or mis-placed.

**Comment by ianna** [comment]
merged in #31879

**Pull request closed without merging**
