### PR TITLE
Further modification to new Scouting path in HLT (11_3_X)

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
#### PR description:

Further modification to new Scouting path in HLT (11_3_X)
Based on CMSSW_11_3_X_2021-02-09-2300

#### PR validation:

TSG tests

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
type bugfix

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
