### PR TITLE
Revive beam information, physics declared bit, and HLT event selection for online DQM 80X

### PR DESCRIPTION
**Pull request by diguida**
The PR allows the DQM module `DQMProvInfo` (run by central online DQM) to retrieve the beam information from TCDS FED raw data, by reading the corresponding address for the Beam Synchronous Timing (BST) record. This is currently done using an utility in `EventFilter/Utilities`, which has been enhanced for this scope.
From this information, the Physics Declared bit is computed, and added into the report summary profile.
NOTA BENE: this is a **temporary** solution, until a well implemented unpacker for TCDS is made available in CMSSW.

The PR also resurrects a `MonitorElement` in `DQMEventInfo` showing the HLT path selection in the DQM input source `DQMStreamerReader`.

This is a back-port in 80X of #14763

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
+1

For #14764 95457daf5666e2770a69735f92a6fc12fe4d4d6f

Saving beam info for online DQM. There should be no change in monitored offline Reco quantities.

#14763 is the 81X version of this PR, and it has already been approved by Reco.

The code changes are satisfactory, and Jenkins tests against baseline CMSSW_8_0_X_2016-06-01-1100 show no significant differences, as expected.

**Comment by dmitrijus** [comment]
+1

**Comment by diguida** [comment]
@emeschi @mommsen ping :-)
In the discussion on #14763 you have no objections with these changes.

**Comment by vanbesien** [comment]
This is running fine on production DQM now.
Would be nice if we could get it merged in the next release to avoid manual patch work for DQM.

**Comment by dmitrijus** [comment]
+1

**Comment by cvuosalo** [comment]
+1

For #14764 96687a443a1318e525a7dd39bc7da0de089efdc4

Second approval, after minor DQM changes. New Jenkins tests are still OK.

#14763 is the 81X version of this PR, and it has already been approved.

**Comment by slava77** [comment]
@diguida @davidlange6 
I'm trying to understand why this comes on the list of possible backports affecting reco/miniAOD.
From the code changes, I see only DQM changes.

**Comment by diguida** [comment]
@slava77 
the reco signature is needed for the changes in `EventFilter/Utilities`, which are code changes depending on the improvements in the class data members dealing with BST values implemented in `EventFilter/FED1024`.
These changes are used in DQM to display the beam status in the online GUI.

**Comment by slava77** [comment]
On 8/30/16 8:21 AM, Salvatore Di Guida wrote:
> @slava77 <https://github.com/slava77>
> the reco signature is needed for the changes in |EventFilter/Utilities|,
> which are code changes depending on the improvements in the class data
> members dealing with BST values implemented in |EventFilter/FED1024|.
> These changes are used in DQM to display the beam status in the online GUI.

Even though the reco signature is needed, based on the jenkins tests and
the PR description,
it looks like the only effect on running code in standard workflows is
in DQM.
There are no new RECO or miniAOD products and the existing ones are
unchanged.
( Someone please correct me if I'm wrong. )

Changes like these are usually not held up to go into the production
release.
But this PR is still pending since a while, as if there are actual
changes to persisted products.

**Comment by diguida** [comment]
@slava77 I was not clear.

> Even though the reco signature is needed, based on the jenkins tests and
> the PR description,
> it looks like the only effect on running code in standard workflows is
> in DQM.

The DQM code involved in the PRis not run in any offline standard workflow, but only by one of online DQM clients to produce the HV and Beam Status information in the online DQM GUI.

> There are no new RECO or miniAOD products and the existing ones are
> unchanged.
> ( Someone please correct me if I'm wrong. )

Correct.

> Changes like these are usually not held up to go into the production
> release.
> But this PR is still pending since a while, as if there are actual
> changes to persisted products.

Not fully correct. This change, better this monitoring information revival, was requested by the online crew to better monitor collision runs. Indeed, this code is happily running in the DQM production cluster since at least two months. So, in the DQM perspective, it should go in soon.

The inclusion has been slowed down by a conflicting requirement by DAQ (having the flexibility to handle their records in the raw data) and offline (using unpackers and data format entity classes to provide event information to consumers). See the long thread on the 81X PR #14763.

Hope this further clarifies.

**Comment by slava77** [comment]
-1
this does not seem to be necessary in 80X anymore.

@diguida please close this PR, if you agree.

**Pull request closed without merging**
