### PR TITLE
Fixed overlaps in M10 Phase2 Scenario (D86, D88, D91)

### PR DESCRIPTION
**Pull request by slomeo**
**PR description:**

Fixed all the overlaps in the Muon Yoke for M10 Phase2 Scenario (D86, D88, D91)

FYI: @srimanob

**PR validation:**

validation by "nohup cmsRun SimG4Core/PrintGeomInfo/test/python/g4OverlapCheck2026_cfg.py >& overlaps.out &" 
I set tolerance equal to 0.00001 to find nm overlaps.

Muon's volumes are not present in the overlaps.out file.

**if this PR is a backport please specify the original PR and why you need to backport that PR:**

nothing special

### CODE REVIEW

**Comment by cvuosalo** [comment]
Comparison differences in the D88 workflows are expected since the geometry has slightly changed.

**Comment by cvuosalo** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

**Comment by perrotta** [comment]
+1

**Pull request merged**
