### PR TITLE
[ALCA] clang-tidy Performance inefficient vector operation suggestion applied

### PR DESCRIPTION
**Pull request by smuzaffar**

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by tvami** [comment]
@cmsbuild, please test for CMSSW_13_2_CLANG_X

**Comment by tvami** [comment]
@cmsbuild , please test
 * prev tests show too many diffs which are not expected

**Comment by tvami** [comment]
+alca
 * both CLANG and std CMSSW compiles
 * diffs are understood, mkFit has again thousands of changes

**Pull request merged**
