### PR TITLE
81X HLT July 29th train

### PR DESCRIPTION
**Pull request by perrotta**
Update the HLT menu up to master table /dev/CMSSW_8_0_0/HLT/V453, i.e. pp menus
- /frozen/2016/25ns15e33/v3.1/HLT/V3
- /online/collisions/2016/25ns15e33/v3.1HLT/V6

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
+1

**Comment by perrotta** [comment]
please test
(DAS error)

**Comment by perrotta** [comment]
@mmusich ; from the errors in the tests it looks like 81X GT does not contain yet the L1 menu L1Menu_Collisions2016_v6 L1 menu needed by the HLT.
It was requested in https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2494.html
Could anybody take care of it? Thx

**Comment by mmusich** [comment]
@perrotta of course it does break the tests. 
I was waiting to see this PR to appear since 18 days (https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2494/1/1.html) to integrate the new L1 menu, as I understand the new L1 menu is incompatible w/ the HLT menu currently in release it could not had been done berore...

**Comment by mmusich** [comment]
@perrotta 
the updated Global Tags are available at #15335.
git commands to include them:

```
git cms-addpkg Configuration/AlCa
git remote add mmusich https://github.com/mmusich/cmssw
git fetch mmusich
git cherry-pick 043465e892d85c290e48a96d38d4d6bd7d9de458
```

**Comment by mmusich** [comment]
please test

**Comment by perrotta** [comment]
@mmusich : please wait, I'm still fighting with git trying to solve conflicts...

**Comment by mmusich** [comment]
OK, sorry. I didnt' realize it.

**Comment by perrotta** [comment]
please test

**Comment by mmusich** [comment]
+1 
for https://github.com/cms-sw/cmssw/pull/15327/commits/ad29f7a5eb32c9a850a3e70451ef4e4005a9b41d

**Comment by perrotta** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
