### PR TITLE
Modernize Multi5x5SuperClusterProducer

### PR DESCRIPTION
**Pull request by Dr15Jones**
-Only call 'consumes' for what is actually consumed
-Only call 'produce' for what is actually produced
-Removed unused functions and variables
-Use edm::EDPutTokens
-Better memory management
-Code cleanups

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test
[try testing without global tag change]

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/25448	ad7b9a1
- code changes are in line with the PR description; the PR is a technical update, as described
- jenkins tests pass and comparisons with the baseline show no differences

**Comment by smuzaffar** [comment]
@Dr15Jones , we did a cleanup of some large data files which were merge in cmssw repo few days ago. Due to this cleanup this PR is now in a bad state (includes all the commits which we rewrite to avoid the large data files), Can you please rebase this PR based on new head?

**Comment by Dr15Jones** [comment]
I was forced to create a new branch from `master` and then cherry-pick the one commit onto that new branch

**Comment by Dr15Jones** [comment]
please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/25448	9e67373
- the changes in the code are the same as in the previously signed version (https://github.com/cms-sw/cmssw/pull/25448	ad7b9a1)

**Pull request merged**
