### PR TITLE
HLT development in May (80X)

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
HLT development in May (80X).
Includes HLT PR #14325 as that is not yet merged.
(Based on CMSSW_8_0_7_patch2 and including Egamma migration PR #13845 as well)
Needs 2016 L1T menu v2!
Rebased to CMSSW_8_0_8

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
@smuzaffar 
This PR is stuck in "Checking for ability to merge automatically…"
Please check....

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by davidlange6** [comment]
any remaining issues for this PR?

**Comment by mmusich** [comment]
+1

**Comment by Martin-Grunewald** [comment]
@davidlange6 
From the HLT side yes, there are remaining developments to be included - we have a TSG deadline of Monday. If you want to integrate now, you can do so (and its 81X twin), but we will have further
items on Monday!
Of course, https://github.com/cms-sw/cmssw/pull/14336 is even more urgent to be integrated in 80X.

**Comment by davidlange6** [comment]
eg, the HLT is not ready for the MC prod yet. Ok good to know. We wait on the release then.

**Comment by Martin-Grunewald** [comment]
@davidlange6 @fwyzard 
Hmm, there is a circular dependency then: we expected an (intermediate) release with current IB content plus #14336, before we need to provide the "final" HLT for MC prod - then to be included in another release. So this is no longer to happen? (We need this "intermediate" release to do more ConfDB parsing and then use that for updating the HLT config for MC prod).

**Comment by davidlange6** [comment]
I think I was never aware of this plan/need, so I can’t comment on any change in plan.

**Comment by Martin-Grunewald** [comment]
@davidlange6 
It was drawn up as you said you'd make a new 80X release "this week".

**Comment by davidlange6** [comment]
good to know the hidden dependency.  will try to manage a release over the weekend

**Comment by Martin-Grunewald** [comment]
....but please include #14336 in it!

**Comment by Martin-Grunewald** [comment]
+1
thsi PR as you included its twin in 81X already.
Subsequent HLT will be put into new PRs...

**Comment by Martin-Grunewald** [comment]
@davidlange6 
Actually, please do include this PR #14445 in this next 80X release as it contains the HLT/Eg technical migration. Thanks!

**Comment by dmitrijus** [comment]
+1

**Pull request merged**
