### PR TITLE
Fix deprecation warnings in PhysicsTools/UtilAlgos

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

- removed unnecessary include of deprecated headers
- switched modules to thread-friendly types.

#### PR validation:

Code compiles without issuing any CMS deprecation warnings.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
Please review. This is part of the last two PRs holding up the removal of the legacy EDFilter class.

**Comment by perrotta** [comment]
+1

**Comment by perrotta** [comment]
merge

**Pull request merged**
