### PR TITLE
Remove PF candidates with nan for energy

### PR DESCRIPTION
**Pull request by mandrenguyen**
Addresses issue #41397 by simply filtering out PF candidates with nan for energy.
This is a short-term fix to stop the crashes in prompt reco.
Should be replaced by finding the source of these nan's in `PFAlgo.cc`

Verified that this removes the segmentation violation using the recipe provided in  #41397

Will need a backport to 13_0_X

### CODE REVIEW

**Comment by mandrenguyen** [comment]
please test

**Comment by mandrenguyen** [comment]
+1
tests pass, will backport.

**Comment by perrotta** [comment]
+1

**Comment by mandrenguyen** [comment]
type pf

**Comment by kdlong** [comment]
Thanks @mandrenguyen! I am taking a look at the cause of this inside PF as well

**Pull request merged**
