### PR TITLE
Add python3 compatibility for RelMon

### PR DESCRIPTION
**Pull request by kskovpen**
#### PR description:

Together with #36119 makes RelMon fully functional in 12_2_X.

#### PR validation:

Tests of ValidationMatrix on the relevant DQMIO files.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Not a backport.

### CODE REVIEW

**Comment by kskovpen** [comment]
assign pdmv

**Comment by kskovpen** [comment]
please test

**Comment by kskovpen** [comment]
+1

**Comment by jfernan2** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
