### PR TITLE
Phase2-356X Fix bugs in the simulation of 2023 HGCal TB setups to provide multiple hits

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Fix bugs in the simulation of 2023 HGCal TB setups to provide multiple hits

#### PR validation:

Use a script in SimG4CMS/HGCalTestBeam/test

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
Type bug-fix

**Comment by civanch** [comment]
+1

**Comment by rappoccio** [comment]
+1

**Pull request merged**
