### PR TITLE
[10_2_X] Add protection for disabled FEDs in the SiStrip packer

### PR DESCRIPTION
**Pull request by pieterdavid**
Backport of https://github.com/cms-sw/cmssw/pull/24577
in case this is needed for followup testing after the HI tests done yesterday.

@icali @mmusich

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by slava77** [comment]
@cmsbuild please test workflow 140.55

**Comment by slava77** [comment]
@fabiocos 
I noticed that some other 10_2_X PRs are being merged, apparently in preparation of a new 10_2_X build.
Please include this one as well, unless you see some issues with it.
Thank you.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
