### PR TITLE
Removed file based destinations from MessageLogger_cfi

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

The destinations were rarely used. Where they were used were updated to explicitly declare the destinations.

#### PR validation:

Each file was loaded into python to guarantee that it parsed correctly. All unit tests for the packages were run and succeeded.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/31930	df352ae 
- technical; affects only a couple of reco files in /test subdirectories

**Comment by kpedro88** [comment]
+upgrade

**Comment by santocch** [comment]
+1

**Comment by makortel** [comment]
+1

**Comment by Dr15Jones** [comment]
@cms-sw/alca-l2 @cms-sw/l1-l2 ping

**Comment by christopheralanwest** [comment]
+alca

**Comment by Dr15Jones** [comment]
@cms-sw/l1-l2 ping

**Comment by silviodonato** [comment]
merge
@cms-sw/l1-l2 please let us know if you have any comments

**Pull request merged**
