### PR TITLE
Removing obsolete FED 1023 handling and fixes for static checks (DAQ) - 81X

### PR DESCRIPTION
**Pull request by smorovic**
As discussed in #15077 here is a PR with fixes for some of static checks in EventFilter/Utilities:
- FED 1023 is leftover from Run1 and no longer used. Removing legacy modules handling it.
- FED 812 is superseded by TCDS FED, so removing a test parser for it.
- Convert legacy modules to edm::one (modules are only used for testing)
- catch(...) in source replaced with catching cms::Exception
- removed dead assignment
- add comments about null pointer assignment exceptions that are intentionally placed in ExceptionGenerator module
- static variable in Raw output module was reported as thread safety issue, but was needed for the signal handler. Now doing the runEnd action when application is interrupted is achieved based on framework signal handling.

### CODE REVIEW

**Comment by smorovic** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by mommsen** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
+1

For #15159 fb19f8acd6715997e1e4cb17605101b04fdd1ce8

Deleting obsolete DAQ files and fixing static analyzer warnings. There should be no change in monitored quantities.

The code changes are satisfactory, and Jenkins tests against baseline CMSSW_8_1_X_2016-07-10-2300 show no significant differences, as expected.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
