### PR TITLE
added esConsumes to modules in RecoEgamma/ElectronIdentification

### PR DESCRIPTION
**Pull request by JamminJones**
#### PR description:

added esConsumes to 1 module

#### PR validation:

the code compiles

### CODE REVIEW

**Comment by JamminJones** [comment]
the module ElectronMVANtupllizer was not modified due to the complexity of the changes required.

**Comment by Dr15Jones** [comment]
This change was made under my supervision.

**Comment by Dr15Jones** [comment]
NOTE: when looking at many of the helpers in this package it was found that the helpers were passed the `edm::EventSetup` but never used it. It could be good if someone went back to this package and removed the access to the `edm::EventSetup` for all those cases.

**Comment by Dr15Jones** [comment]
please test

**Comment by perrotta** [comment]
+1
- Technical
- Jenkins tests pass

**Comment by silviodonato** [comment]
+1

**Pull request merged**
