### PR TITLE
run3-hcx321B Modernize analyzer codes for CalibCalorimetry/CastorCalib

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Modernize analyzer codes for CalibCalorimetry/CastorCalib

#### PR validation:

Use the runTheMatrix test workflows 

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
Just for the record
 * `CalibCalorimetry/CastorCalib/plugins/CastorPedestalsAnalysis.cc` has some commented out code 
 * but since CASTOR is decommissioned I proposed that we don't need remove those

**Comment by tvami** [comment]
+alca

**Comment by qliphy** [comment]
+1

**Pull request merged**
