### PR TITLE
75X: fix pT selection in HLTrigger/special/src/HLTPixlMBFilt.cc

### PR DESCRIPTION
**Pull request by gsafronov**
Add two lines of code for previously lacking pT selection of tracks. Tested with 7_4_13.

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
bloody $&*%&&

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
Since the 7$X and 76X versions of this PR work just fine, the jenkins error is unrelated anyway!

**Comment by Martin-Grunewald** [comment]
+1

**Comment by Martin-Grunewald** [comment]
please test

**Comment by davidlange6** [comment]
+1

**Pull request merged**
