### PR TITLE
Add ParkingBPH skim spec to autoskim.py (back port to 10_2_X)

### PR DESCRIPTION
**Pull request by kfjack**
#### PR description:

Add ParkingBPH skim spec to autoskim.py (back port from PR #26108 to 10_2_X)

### CODE REVIEW

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
@prebello @zhenhu this needs your signature to move forward

**Comment by prebello** [comment]
+1

Thank you @fabiocos

**Comment by fabiocos** [comment]
+1

backport consistent with version in master

**Pull request merged**
