### PR TITLE
Use ofast-flag rather than fast-math for mkFit

### PR DESCRIPTION
**Pull request by mmasciov**
### PR description:

As per title, this PR is meant to switch to `ofast-flag` rather than `fast-math` for mkFit building, as this was proven to allow for improved stability across different architectures.
An analogous change is applied to the standalone mkFit `Makefile.config`.

**Additional notes on the mkFit `Makefile.config`:**
`ofast-flag` in CMSSW consists of `-Ofast -fno-reciprocal-math -mrecip=none` (see https://github.com/cms-sw/cmsdist/pull/8280).
This is reflected in the mkFit `Makefile.config`, with intentional redundancy:
`-Ofast` turns on `-ffast-math`, which in turn activates `-fno-math-errno` (see [reference](https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html)); the redundant flags are not removed intentionally, so that in the case one is willing to remove the effects of `ofast-flag` in the standalone mkFit application, it will be sufficient to comment out the line added in `Makefile.config` with this PR, without changing vectorization due to other pre-existing flags.

### PR validation:

This PR is not meant to affect physics performance, except for compilation-driven effects. Technical performance is not affected either.
This is validated in: http://uaf-10.t2.ucsd.edu/~mmasciov/MIC/testFastMath/MTV_ttbarPU_cgpu-1_fastmath_vs_ofast/ (red/black vs. blue)

FYI, @mmusich, @slava77

### CODE REVIEW

**Comment by clacaputo** [comment]
enable profiling

**Comment by clacaputo** [comment]
please test

**Comment by mmasciov** [comment]
@clacaputo, thanks for enabling and triggering tests with profiling.
However, all `igprofCPU*` entries seem to be empty: is this symptomatic that profiling tests did not complete properly for any reason?
(BTW, just to clarify: we don't expect any significant difference to be found in profiling tests either)

**Comment by gartung** [comment]
I had to resubmit some of the profiling jobs which might have caused the missing `igprofCPU` entries.

**Comment by gartung** [comment]
I noticed the empty `igprofCPU` entries in the IB build profiling jobs as well and I am trying to debug the problem.

**Comment by gartung** [comment]
You can try re-running the PR tests. It might work this time.

**Comment by gartung** [comment]
please test

**Comment by gartung** [comment]
@clacaputo I haven't figured out why the Igprof cpu profiles are empty. For now I would use the Resources Pier Charts. They are the json files linked in the profiling summary for each workflow.
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-b29b55/32086/summary.html

**Comment by clacaputo** [comment]
> @clacaputo I haven't figured out why the Igprof cpu profiles are empty. For now I would use the Resources Pier Charts. They are the json files linked in the profiling summary for each workflow. https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-b29b55/32086/summary.html

Hi @gartung , thanks for checking. Unfortunately, after clicking on the json, the Circles page is empty

**Comment by gartung** [comment]
The link url is malformed. Try 
https://cmssdt.cern.ch/circles/web/piechart.php?local=false&dataset=CMSSW_13_1_X_2023-04-28-1100%2Fel8_amd64_gcc11%2F11834.21%2FPR-b29b55%2F32234%2Fstep3_RAW2DIGI_L1Reco_RECO_RECOSIM_PU.resources&resource=time_thread&colours=default&groups=packages&threshold=0

**Comment by gartung** [comment]
and 
https://cmssdt.cern.ch/circles/web/piechart.php?local=false&dataset=CMSSW_13_1_X_2023-04-28-1100%2Fel8_amd64_gcc11%2F23834.21%2FPR-b29b55%2F32234%2Fstep3_RAW2DIGI_L1Reco_RECO_RECOSIM_PU.resources&resource=time_thread&colours=default&groups=packages&threshold=0

and

https://cmssdt.cern.ch/circles/web/piechart.php?local=false&dataset=CMSSW_13_1_X_2023-04-28-2300%2Fel8_amd64_gcc11%2F136.889%2FPR-7c0862%2F32251%2Fstep3_RAW2DIGI_L1Reco_RECO_SKIM_PAT_ALCA_DQM.resources&resource=time_thread&colours=default&groups=packages&threshold=0

**Comment by clacaputo** [comment]
I've tested the PR on `vocms011` producing 400 events for `11834.21` in `CMSSW_13_1_X_2023-04-30-2300`.

The TimeDiff `CMSSW_13_1_X_2023-04-30-2300` VS `CMSSW_13_1_X_2023-04-30-2300+PR` is this:

```
The same excluding the first 1 events
  delta/mean delta/orJob     original                   new       module name
  ---------- ------------     --------                  ----       ------------
   -1.322640      -0.00%         0.10 ms/ev ->         0.02 ms/ev ootPhotonCore
   +0.069762      +0.01%        23.65 ms/ev ->        25.36 ms/ev detachedQuadStepTracks
   -0.064655      -0.01%        11.89 ms/ev ->        11.14 ms/ev mkFitEventOfHits
   -0.063905      -0.01%        12.03 ms/ev ->        11.28 ms/ev mkFitEventOfHitsPreSplitting
   -0.062740      -0.03%        57.06 ms/ev ->        53.58 ms/ev ecalMultiFitUncalibRecHit@cpu
   +0.059093      +0.00%         6.35 ms/ev ->         6.73 ms/ev tobTecStep
   +0.057614      +0.01%        14.94 ms/ev ->        15.82 ms/ev initialStep
   +0.056911      +0.00%         5.00 ms/ev ->         5.30 ms/ev mixedTripletStep
   +0.055222      +0.01%        18.14 ms/ev ->        19.17 ms/ev detachedTripletStep
   +0.055166      +0.09%       197.39 ms/ev ->       208.59 ms/ev detachedTripletStepTracks
   +0.054596      +0.01%        23.33 ms/ev ->        24.64 ms/ev highPtTripletStepTrackCandidates
   +0.053510      +0.08%       181.53 ms/ev ->       191.51 ms/ev initialStepTracksPreSplitting
   +0.052727      +0.08%       182.90 ms/ev ->       192.81 ms/ev initialStepTracks
   +0.052273      +0.00%         6.77 ms/ev ->         7.13 ms/ev highPtTripletStep
   +0.052233      +0.01%        19.16 ms/ev ->        20.19 ms/ev pixelLessStep
   +0.052184      +0.04%       105.32 ms/ev ->       110.96 ms/ev lowPtTripletStepTracks
   +0.051537      +0.03%        68.10 ms/ev ->        71.71 ms/ev highPtTripletStepTracks
   +0.051366      +0.01%        19.29 ms/ev ->        20.31 ms/ev lowPtTripletStep
   -0.051177      -0.04%       103.15 ms/ev ->        98.00 ms/ev detachedTripletStepSeeds
   +0.051065      +0.01%        16.32 ms/ev ->        17.18 ms/ev lowPtQuadStep
  ---------- ------------     --------                  ----       ------------
Job total:  13.0736 s/ev ==> 13.135 s/ev
``` 

There is slight increase in reco timing that could be a fluctuation.

**Comment by mmasciov** [comment]
@clacaputo, indeed we do not expect any change beyond fluctuations, as also confirmed in our validation (see, e.g., http://uaf-10.t2.ucsd.edu/~mmasciov/MIC/testFastMath/MTV_ttbarPU_cgpu-1_fastmath_vs_ofast/plots_timing/summaryReal.pdf).

**Comment by perrotta** [comment]
+1

**Pull request merged**
