### PR TITLE
Fix bug introduced in the L1T PF code cleanup for release integration

### PR DESCRIPTION
**Pull request by gpetruc**
#### PR description:

Fix bug introduced in the code cleanup for release integration that was resulting garbage clusters in the barrel.
see https://hypernews.cern.ch/HyperNews/CMS/get/L1TriggerUpgrades/384/1.html 

#### PR validation:

Plots of jet response and resolution in the barrel (ttbar, PU 200):
 * [in the old trigger branch before cleanup (good reference)](https://gpetrucc.web.cern.ch/gpetrucc/drop/plots/l1stage2/11_1_X/from110X/110X_v0.4/val/TTbar_PU200/?match=jet_eta_00_13)
 * [in the current 11_1_0_patch2 (broken)](https://gpetrucc.web.cern.ch/gpetrucc/drop/plots/l1stage2/11_1_X/from110X/110X_v1/val/TTbar_PU200/?match=jet_eta_00_13)
 * [in 11_1_0_patch2 + this fix (recovered old behaviour)](https://gpetrucc.web.cern.ch/gpetrucc/drop/plots/l1stage2/11_1_X/from110X/110X_v1.1/val/TTbar_PU200/?match=jet_eta_00_13)

@rekovic

### CODE REVIEW

**Comment by kpedro88** [comment]
@gpetruc the second and third links in the PR description point to the same page

**Comment by kpedro88** [comment]
please test

**Comment by gpetruc** [comment]
> 
> 
> @gpetruc the second and third links in the PR description point to the same page

sorry, copy-paste mistake. Fixed now

**Comment by fwyzard** [comment]
@gpetruc thanks for the fix !

I've made a backport to 11.1.x in #30741 .

**Comment by fwyzard** [comment]
Add to #30741 as well.

**Comment by silviodonato** [comment]
please test

**Comment by silviodonato** [comment]
urgent

**Comment by gpetruc** [comment]
While this is all in terms of bugfixes, performance-wise I have also an update of the calibrations in https://github.com/gpetruc/cmssw/compare/Fix_L1PF-from-CMSSW_11_2_X...gpetruc:UpdateCalib-CMSSW_11_2_X + https://github.com/cms-data/L1Trigger-Phase2L1ParticleFlow/pull/3 

A longer report is in
https://hypernews.cern.ch/HyperNews/CMS/get/L1TriggerUpgrades/384/1/1/1/1/2/3/2.html

**Comment by silviodonato** [comment]
merge

**Comment by rekovic** [comment]
+1

**Pull request merged**
