### PR TITLE
Phase2-gex12 Make use of level() method

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Make use of level() method in calorimeter and muon codes

#### PR validation:

Testing using standard workflows in runTheMatrix.py

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Review by ianna — APPROVED** [review]
Thank you @bsunanda !

**Comment by ianna** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade

**Comment by silviodonato** [comment]
+1

**Pull request merged**
