### PR TITLE
HLTHiggsSubAnalysis: read within bounds

### PR DESCRIPTION
**Pull request by slava77**
add range check in jet flag calculation to avoid reads out of bounds.
This fixes occasional "random" differences in Higgs/VBFHToInv

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cmsbuild please test
output files are truncated. Looks like a glitch on jenkins side.

**Comment by slava77** [comment]
jenkins tests show no differences in comparisons (workflows where I've seen random differences before are not in the comparisons: it usually happens in high pt muon guns)

**Comment by deguio** [comment]
+1

**Pull request merged**
