### PR TITLE
DQM: Added new package MuonMonitor for cosmic muons

### PR DESCRIPTION
**Pull request by calderona**
#### PR description:

Added new package on DQM online for cosmic muon monitoring, under DQM/MuonMonitor and also a new client under DQM/Integration/clients/

#### PR validation

tested locally. All the code compile, runs and histograms appears on DQM GUI.

#### if this PR is a backport please specify the original PR:

https://github.com/cms-sw/cmssw/pull/28244

### CODE REVIEW

**Comment by calderona** [comment]
A  PR for https://github.com/cms-sw/cms-bot/blob/master/categories_map.py to assign category
has been created 
https://github.com/cms-sw/cms-bot/pull/1214

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by fabiocos** [comment]
@boudoul as far as I can see at peesent this impacts only online

**Comment by fabiocos** [comment]
+1

**Pull request merged**
