### PR TITLE
Fix for O2O execution in CC7

### PR DESCRIPTION
**Pull request by ggovi**
In this PR:
- Changed resolution of user information during O2O execution, to adapt to CC7
- Added RunInfo Start O2O integration test
- Added Ecal DAQ O2O integration test

The changes have been merged in 10_1_X already

### CODE REVIEW

**Comment by ggovi** [comment]
please test

**Comment by ggovi** [comment]
please test

**Comment by ggovi** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
