### PR TITLE
Add minN parameter to HLTMuonTrkFilter

### PR DESCRIPTION
**Pull request by dildick**
See also https://github.com/cms-sw/cmssw/pull/7426

### CODE REVIEW

**Comment by perrotta** [comment]
+1

**Comment by dildick** [comment]
Hi!

Can this PR be merged as soon as possible? I would like to implement my HLT path in the ConfDB and I need this parameter.

Thanks!

**Comment by fwyzard** [comment]
Hi Sven,
I expect that Andrea and Martin will request it at today's ORP meeting.

.A

**Comment by davidlange6** [comment]
+1

**Pull request merged**
