### PR TITLE
Import the precise checks done by ROOT to Add histograms.

### PR DESCRIPTION
**Pull request by schneiml**
This is more restrictive than what we used before, but should prevent ROOT from attempting to call Merge() (which mysteriously fails in some cases, causing a FatalRootError on CMSSW side).
The histograms that are now no longer merged seem to be meaningless either ways (0-0 X range).

This PR replaces #26722, which on closer investigation seems too dangerous. It implements the frist alternative listed there, which means we'll need to keep the checks in sync whenever ROOT changes.

It is still not clear why we can't use `TH1::Merge`, but my tests showed that it fails in some cases, even some where `Add` worked. Since semantically we don't really want a `Merge` (the histograms should really have the same "shape" when we merge them), I think it is a good idea to restrict everything to the cases handled by `TH1::Add`.

#### PR validation:

Works on the sample from issue #26727 . No other validation so far.

### CODE REVIEW

**Comment by andrius-k** [comment]
please test

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
@schneiml so what is ultimately the plan here? As we see ROOT 6.14 behaves differently in this respect

**Comment by schneiml** [comment]
@fabiocos I'll close it for now, since it is not really needed. I plan to integrate these changes in the bigger DQMStore restructuring coming (hopefully) soon.

If we decide to not go with the big restructuring, we can come back to this one.

**Pull request closed without merging**
