### PR TITLE
reminiAOD workflows from 80X input (92X)

### PR DESCRIPTION
**Pull request by fabozzi**
backport of #19437 

Added two re-miniAOD workflows from 80X input (data and MC)
following implementation of #19304

The relvals have been tested here:
https://hypernews.cern.ch/HyperNews/CMS/get/relval/7795.html

@slava77 @gpetruc

### CODE REVIEW

**Comment by fabozzi** [comment]
please test

**Comment by fabozzi** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Comment by davidlange6** [comment]
CMSSW_9_2_X developement work is completed. Closing remaining PRs

**Pull request closed without merging**
