### PR TITLE
Remove inappropriate use of provenance in EcalDeadCellTriggerPrimitiveFilter

### PR DESCRIPTION
**Pull request by Dr15Jones**
The code was calling edm::Event::getAllStableProvenance to try to determine if some data products were available in the Event. This did not help performance since the consumes calls would already prefetch all the data. To try to keep the same functionality, I switched to using callWhenNewProductsRegistered.

The logic which changed the movule's behavior for data older than CMSSW_4_2 was also removed.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
@slava77 
>Was your comment to remove the last else because logically this code will never get there assuming there are no more inputs ? Or was your comment to drop the logic of the version detection because it has no effect (assuming all inputs are already after version 4_2)?

I was asking if we can drop the entire version detection because CMSSW_10_3 will never be used to run on reconstruction from before CMSSW_4_2.

**Comment by slava77** [comment]
> I was asking if we can drop the entire version detection because CMSSW_10_3 will never be used to run on reconstruction from before CMSSW_4_2.

I'm fine with removing this detection.
@lihux25 @eioannou I'm assuming it's safe to assume that there are no analysis jobs running this filter on data produced by releases before release CMSSW_4_2

**Comment by Dr15Jones** [comment]
please test

**Comment by perrotta** [comment]
please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/24387	53fbe20
- somewhat technical change in the provenance access, in line with the PR description; drop the logic used with inputs created before CMSSW_4_2
- jenkins tests pass

@Dr15Jones please update the PR description to clarify that the old version detection logic was removed.

**Comment by Dr15Jones** [comment]
@slava77 comment updated

**Comment by kpedro88** [comment]
+1

**Comment by kpedro88** [comment]
merge

**Pull request merged**
