### PR TITLE
[14_0_X] Tunable `PUMax`  in `PrimaryVertexMonitor` and Finer d_xy DQM Tracking Plots

### PR DESCRIPTION
**Pull request by AdrianoDee**
Plain backport of https://github.com/cms-sw/cmssw/pull/44669.

### CODE REVIEW

**Comment by AdrianoDee** [comment]
backport of https://github.com/cms-sw/cmssw/pull/44669

**Comment by AdrianoDee** [comment]
please test

**Comment by tjavaid** [comment]
+1

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
