### PR TITLE
Make header files in FWCore/Framework/interface consistent

### LINKED ISSUE #211: Make header files in FWCore/Framework/interface consistent
The header files in the interface directory should only include header files from other interface directories, not src.

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

The header files in the _interface_ directory should only include header files from other _interface_ directories, not _src_.

#### PR validation:

Framework packages all compile.

fixes makortel/framework#211

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
@smuzaffar I could not get the _poison_ file to work in my area. I did

```bash
scram project CMSSW_12_1_X_2021-08-04-1100
cd CMSSW_12_1_X_2021-08-04-1100/
cmsenv
cd src/
git cms-addpkg FWCore/Framework
git checkout fixHeadersMaker
git cms-addpkg DQM/SiStripMonitorHardware Mixing/Base
scram b -j 24
```

and everything compiled fine (it should have failed). I then did
```bash
touch Mixing/Base/src/PileUp.cc DQM/SiStripMonitorHardware/src/SiStripSpyEventMatcher.cc
scram b -j 24
```
and again, it built fine.

**Comment by smuzaffar** [comment]
you need to run `git cms-checkdeps -a -A` which should create the poison files

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
Please test

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by Dr15Jones** [comment]
+1

**Comment by Dr15Jones** [comment]
Ping @cms-sw/dqm-l2

**Comment by jfernan2** [comment]
+1

**Comment by perrotta** [comment]
@Dr15Jones there is now a conflict with the FWCore/Framework/src/PathsAndConsumesOfModules.cc in the release (since the merge of your own #34735): could you please fix it?

**Comment by Dr15Jones** [comment]
@perrotta rebase done

**Comment by Dr15Jones** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by smuzaffar** [comment]
@cms-sw/dqm-l2 , can you please review this. DQM related change is in DQM/SiStripMonitorHardware/src/SiStripSpyEventMatcher.cc only

**Comment by jfernan2** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
