### PR TITLE
Reverse dependency

### PR DESCRIPTION
**Pull request by lecriste**
#### PR description:

This PR addresses [this comment](https://github.com/cms-sw/cmssw/pull/32785#pullrequestreview-582435930) from a previously merged PR.
It also introduces a file (`AssociatorTools.h`) that will contain methods shared by different associators. 
No changes are expected in the output.

#### PR validation:

`runTheMatrix -l limited`

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

No change is expected, technical PR to make a proper dependency.

**Comment by qliphy** [comment]
+1

**Pull request merged**
