### PR TITLE
SiPM pulse code cleanup

### PR DESCRIPTION
**Pull request by kpedro88**
This PR reduces code and value duplication related to SiPM pulse shapes. Commonly-used functions and constants are relocated to `CalibCalorimetry/HcalAlgos`, and some unused variables in the SiPM code are removed (along with other minor cleanup). The SiPM reco pulse template for HE is now calculated transparently by numerical convolution in `HcalPulseShapes`, instead of being calculated by the same algorithm in a private macro on my computer and then pasted in as a vector of non-reproducible values.

Because of the last change, there will be minor fluctuations in M2 results for 2017 HE, entirely caused by changes in rounding of the values in the reco pulse template. Some distributions from WF 10022.0 (comparing 900pre2 vs 900pre2 + this PR): 
log10(chi2) log10(M2)

attn: @slava77, @mariadalfonso

### CODE REVIEW

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by kpedro88** [comment]
No surprises in the comparisons as far as I can tell

**Comment by civanch** [comment]
+1

**Comment by mmusich** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
