### PR TITLE
Avoid freeing memory owned by TMVA::Reader

### PR DESCRIPTION
**Pull request by dan131riley**
Older versions of TMVA::Reader didn't clean up classification methods, and so leaked memory.  Some CMS code cleaned up the memory itself to avoid leaking.  Starting with ROOT 6.07+, TMVA::Reader now cleans up after itself, so the CMS cleanups are resulting in double frees and potentially corrupted memory.  This (rather ugly) PR patches all the places I could easily find to not assume ownership of the objects.  More details are in issue #17256

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/17266	3ca8416
- implementation is in line with the description
- jenkins tests pass and comparisons with baseline show no differences
    - we started using ROOT 6.08/02 since about 10 days in 90X IBs; so, the new code branches are executed and appear OK

**Comment by slava77** [comment]
@davidlange6 
please clarify if some extra work is needed here or are you just waiting for the missing analysis signature?
Thanks

**Comment by davidlange6** [comment]
its on my todo list (but not at the top)

**Comment by monttj** [comment]
+1

**Comment by davidlange6** [comment]
Hi @dan131riley @Dr15Jones - sorry meant to bring this up yesterday - as we are nominally done with root<6.08, we don't need these ifdefs.I would propose just to support 6.08

That said, why are these not causing crashes? Just because tmva resets the pointers to 0 and it happens to delete things first?

**Comment by dan131riley** [comment]
Ok, I can remove the ifdefs.  wrt why it isn't crashing, valgrind says that our delete is first, followed by the TMVA::Reader destructor, which does:

```
   for (auto it=fMethodMap.begin(); it!=fMethodMap.end(); it++){
      MethodBase * kl = dynamic_cast<TMVA::MethodBase*>(it->second);
      delete kl;
   }
```
Valgrind complains

```
==6469== Invalid read of size 8
==6469==    at 0x64411CD: __dynamic_cast (/mnt/build/davidlt/gcc530_final/b/BUILD/slc6_amd64_gcc530/external/gcc/5.3.0/gcc-tags_gcc_5_3_0_release-231255/obj/x86_64-pc-linux-gnu/libstdc++-v3/libsupc++/../../../../libstdc++-v3/libsupc++/dyncast.cc:50)
==6469==    by 0x165D56F2: TMVA::Reader::~Reader() (in /cvmfs/cms-ib.cern.ch/nweek-02456/slc6_amd64_gcc530/lcg/root/6.08.02/lib/libTMVA.so)
```

and nothing else, so I wonder if it's possible the dynamic_cast is failing, so it deletes a nullptr?

**Comment by Dr15Jones** [comment]
please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/17266	91be322
- sign again after the support for ROOT version earlier than 6.07 was removed
- jenkins tests pass and comparisons show no differences

**Pull request merged**
