### PR TITLE
add loose mva WP for non triggering electrons

### PR DESCRIPTION
**Pull request by fcouderc**
same as PR #13263

Add the HZZ loose WP identification for non triggering electrons.
This new ID has been developed for HZZ analysis and can now be used by a broader audience

@ikrav please follow (74X PR)

### CODE REVIEW

**Comment by fcouderc** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by fcouderc** [comment]
this seems to be due to a file opening error… to be re-tested

On 12 févr. 2016, at 14:51, cmsbuild <notifications@github.com<mailto:notifications@github.com>> wrote:


-1

Tested at: 9ba56a0<https://github.com/cms-sw/cmssw/commit/9ba56a07e69da3885825ae8edf1bcde7afd5b882>
I found errors in the following unit tests:

---> test runtestRecoEgammaElectronIdentification had ERRORS

you can see the results of the tests here:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-13264/11162/summary.html

**Comment by slava77** [comment]
The file is gone from disk, apparently 
The same error shows up in IB as well
https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc6_amd64_gcc491/CMSSW_7_4_X_2016-02-07-0000/unitTestLogs/RecoEgamma/ElectronIdentification

/store/relval/CMSSW_7_4_8_patch1/RelValZEE_13/GEN-SIM-RECO/PU25ns_MCRUN2_74_V11_mulTrh-v1/00000/001C7DBD-583C-E511-9107-0025905A60B2.root
may be better replaced with something more available.
It's an EGM test. So, feel free to update.
74X updates are rare though. So, it may be not so essential.

**Comment by davidlt** [comment]
@slava77 do you think, I should request for this to be transferred to T2_CH_CERN? Looks to be 10GB block.

**Comment by slava77** [comment]
On 2/12/16 6:39 AM, davidlt wrote:
> @slava77 <https://github.com/slava77> do you think, I should request for
> this to be transferred to T2_CH_CERN? Looks to be 10GB block.
> 


Sure, this may be more appropriate than update to the unit test.

BTW, why is showIB not displaying unit test errors like this
https://cmssdt.cern.ch/SDT/html/showIB.html
?

**Comment by davidlt** [comment]
Request has been made, but probably will take 1-2 days. SCRAM seems to do a correct job and report failure `---> test runtestRecoEgammaElectronIdentification had ERRORS`, but I guess it felt through some cracks in the log parsing script. @smuzaffar

**Comment by slava77** [comment]
@fcouderc 
This changes miniAOD output.
This is not allowed in the production release, until a new version/new campaign for miniAOD is defined (none is planned so far).

**Comment by slava77** [comment]
-1
due to changes in miniAOD output
Just addition of a config would be OK, but it should not change stored objects

**Comment by smuzaffar** [comment]
@davidlt, will check the IB script

**Pull request closed without merging**
