### PR TITLE
MF standard sequences cleanup

### PR DESCRIPTION
**Pull request by namapane**
#### PR description:

- Get rid of MagneticField_38T_PostLS1_cff, which has been deprecated ages ago;
- fix ConfigBuilder.py to use the standard MF sequence. As of now, and for data only, it was forcing loading of MagneticField_AutoFromDBCurrent_cff which anyhow points to the standard sequence.

Note that the latter fix removes a meaningless warning message from ConfigBuilder.py as well.

These changes have been recently discussed in https://github.com/cms-sw/cmssw/pull/31651#discussion_r499124784

Note: a significant number of instances of MagneticField_AutoFromDBCurrent_cff is still present in cfg files all around. A good fraction is being handled in #31788; others will be a subject of future PRs, before we can finally remove that cff.

#### PR validation:
Changes are trivial; ie replacing obsolete sequences with others that load exactly the same field map.

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by jfernan2** [comment]
+1

**Comment by silviodonato** [comment]
+operations

**Comment by silviodonato** [comment]
+1

**Pull request merged**
