### PR TITLE
get rid of CMSDEPRECATED_X warnings in `SLHCUpgradeSimulations/Geometry`

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

Part of the migration in https://github.com/cms-sw/cmssw/issues/36404
Went systematically through all of the CMSDEPRECATED_X warnings in the `SLHCUpgradeSimulations/Geometry`  subsystem from `CMSSW_12_3_CMSDEPRECATED_X_2021-12-15-2300` and removed deprecated API calls.
Bonus:
   * merged header files in plugins implementations

#### PR validation:

`cmssw` compiles

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by cvuosalo** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

**Comment by perrotta** [comment]
+1

**Pull request merged**
