### PR TITLE
`BeamSpot` Payload Inspector: introduce payload parameters comparator

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

The goal of this PR is to introduce a new type of class for the BeamSpot Payload Inspector that allows to compare the BeamSpot parameters for two different payloads, either two different IOVs form the same tag, or from two different tags . 
This is done via a novel templated `DisplayParametersDiff` class that will accept both `BeamSpotObjects` and `BeamSpotOnlineObjects` data types.
The unit tests of the package `CondCore/BeamSpotPlugins` are enhanced in order to test the newly added functionality.

#### PR validation:

Tested with the following commands:
```console
getPayloadData.py \
    --plugin pluginBeamSpot_PayloadInspector \
    --plot plot_BeamSpotParametersDiffSingleTag \
    --tag BeamSpotObjects_PCL_byLumi_v0_prompt \
    --time_type Lumi \
    --iovs '{"start_iov": "1406859487477814", "end_iov": "1488257707672138"}' \
    --db Prod \
    --test ;
```
and:

```console
getPayloadData.py \
    --plugin pluginBeamSpot_PayloadInspector \
    --plot plot_BeamSpotParametersDiffTwoTags \
    --tag BeamSpotObjects_Realistic25ns_900GeV_2021PilotBeams_v2_mc \
    --time_type Run \
    --iovs '{"start_iov": "1", "end_iov": "1"}' \
    --tagtwo BeamSpotObjects_Realistic25ns_900GeV_2021PilotBeams_v1_mc \
    --iovstwo '{"start_iov": "1", "end_iov": "1"}' \
    --db Prod \
    --test ;
```

and obtained the following plots:

| BeamSpotParametersDiffSingleTag  | BeamSpotParametersDiffTwoTags |
| ------------- | ------------- |
|  7022e9d6-5ff1-4aed-bcd2-9dd30d352dfd |  35067cfa-0358-4943-b86a-2df1c6ee7f99 |

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by tvami** [comment]
+db

**Comment by perrotta** [comment]
please test

I can hardly believe that the differences in the haloTaggerMVA for patPhotons are originated by this  PR, eg
:
image

Let rerun the tests, to see if it is reproducible, at least.

**Comment by perrotta** [comment]
So, differences are still there, but they now look different than in the previous comparisons. This is the same wf 136.7611 that was reported [above](https://github.com/cms-sw/cmssw/pull/37143#issuecomment-1059798195)

image

While having non identical distributions in consecutive runs of the bot tests probably confirms that there is some non reproducibily issue for those patPhotons' haloTaggerMVA, I don't remember having seen it in other PR tests.
@mmusich @tvami do you have any idea whether these distributions can be touched in any way by the updates implemented with this PR?

**Comment by mmusich** [comment]
> do you have any idea whether these distributions can be touched in any way by the updates implemented with this PR?

There's no way that changes in these classes can affect anything in any relval. 
I think these differences might be caused by some uninitialized variable in #36901.
Also notice that this particular variable starred to be included in the reco comparison also recently (see https://github.com/cms-sw/cms-bot/pull/1717)

**Comment by mmusich** [comment]
since this was being held anyway, I profited to push some other improvement.

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by tvami** [comment]
+1

**Comment by qliphy** [comment]
+1
differences in the haloTaggerMVA for patPhotons is not related to this PR,  and will be fixed later (related to https://github.com/cms-sw/cmssw/pull/36901)

**Pull request merged**
