### PR TITLE
Phase2-hgx325I Remove reference to 6 inch HGCal silicon wafers in 3 codes in Validation/HGCalValidation/plugins

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Remove reference to 6 inch HGCal silicon wafers in 3 codes in Validation/HGCalValidation/plugins

#### PR validation:

Use the runTheMatrix test scenarios

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@perrotta @rappoccio @emanueleusai Jobs are failing randomly on different workflows and none is related to this PR

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by emanueleusai** [comment]
Differences in HGCAL DQM plots caused by formerly empty plots now being filled. @bsunanda can you confirm the changed plots look as expected?

**Comment by bsunanda** [comment]
@emanueleusai Yes these are expected

**Comment by emanueleusai** [comment]
+1

**Comment by bsunanda** [comment]
@perrotta @rappoccio please merge this PR

**Comment by perrotta** [comment]
+1

**Pull request merged**
