### PR TITLE
HLT Migration to 10_0_2 template (10_1_X)

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
HLT Migration to 10_0_2 template
Based on CMSSW_10_1_0_pre1

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by Martin-Grunewald** [comment]
eos errors - let's try again!

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
