### PR TITLE
[94X GT update][2017 MC] Hcal MCParams update

### PR DESCRIPTION
**Pull request by lpernie**
CHANGES:
**phase1_2017_design**
Diff with old GT:
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_mc2017_design_IdealBS_v8/94X_mc2017_design_IdealBS_v7
-> Hcal MCParams update

**phase1_2017_realistic** 
Diff with old GT:
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_mc2017_realistic_v11/94X_mc2017_realistic_v10
-> Hcal MCParams update

**phase1_2017_cosmics** 
Diff with old GT:
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_mc2017cosmics_realistic_deco_v7/94X_mc2017cosmics_realistic_deco_v6

**phase1_2017_cosmics_peak** 
Diff with old GT:
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_mc2017cosmics_realistic_peak_v7/94X_mc2017cosmics_realistic_peak_v6
-> Hcal MCParams update

MOTIVATIONS:
Change motivated here [0], [1] to solve [2].
[0] https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3190.html
[1] https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3458.html
[2] https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3456.html

### CODE REVIEW

**Comment by lpernie** [comment]
backport of https://github.com/cms-sw/cmssw/pull/21881

**Comment by lpernie** [comment]
please test

**Comment by lpernie** [comment]
+1

**Comment by fabiocos** [comment]
@lpernie for which production/use is needed this update in 94X?

**Comment by lpernie** [comment]
Hi @fabiocos ,
the only change in the GT is the Hcal MCParams update [1].
Having these new GTs in autocond is not needed immediately (the new GTs can be used even not having autocond updated), but if you would merge this PR it would be good.

[1] https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3458.html

**Comment by arunhep** [comment]
@fabiocos this PR fixes the problem of unavailability of HCAL local reco conditions for ZDC channels.
Some crashes were observed in Fall17 MC workflows and they are reported here : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3456.html
it will be good to have integrated.

**Comment by fabiocos** [comment]
@lpernie @arunhep thanks for the explanations

**Comment by fabiocos** [comment]
+1

**Pull request merged**
