### PR TITLE
Esmaeel merging p rs 16513 15748

### PR DESCRIPTION
**Pull request by EsmaeelEskandari**

### CODE REVIEW

**Comment by thomreis** [comment]
Hi @EsmaeelEskandari #16513 has been merged now and you could rebase this PR on 80X.

**Comment by thomreis** [comment]
@EsmaeelEskandari your last commit https://github.com/cms-sw/cmssw/pull/16518/commits/b7b951220cbd5f9260544bc839a9dd1651104488 contains a change to the EMTF emulator code. Are you absolutely sure that this should be there?

**Comment by EsmaeelEskandari** [comment]
Dear Thomas,

Yes, It is correct.
PR 15748 was working properly alongside of your PR 165378 previously.

Cheers,
Esmaeel.

**Comment by EsmaeelEskandari** [comment]
@thomreis This PR had no conflicts before. Is my understanding correct that when some other related PR to my PR like yours #16513 is merged, it cause some new conflicts?

**Comment by thomreis** [comment]
Hi @EsmaeelEskandari 

The fact that it worked does not necessarily mean that it does what we expect it to do. I believe that this emulator change might accidentally reverse some emulator changes that where made after you have created PR #15748. @abrinke1 and @rekovic might be able to verify this.
Besides this I think that changes to the emulator should not be in a DQM PR.

Cheers,
Thomas

**Comment by thomreis** [comment]
Most likely the merging of #16513 introduced the conflict. I think rebasing to official-cmssw/CMSSW_8_0_X should resolve them.

```
git fetch official-cmssw
git rebase official-cmssw/CMSSW_8_0_X
```
I would test it in a new branch first not to accidentally mess up your dev branch.

**Pull request closed without merging**
