### PR TITLE
Secondary input source chooses first file to open randomly

### PR DESCRIPTION
**Pull request by wmtan**
The secondary input source, used for mixing pileup, needs to open a pileup file at construction time.
Before this PR, it always opened the first file in the list of files, which caused contention.  This PR randomizes the choice of the file to open at construction time.  This PR does not affect which minbias events will be chosen for mixing.
This change can easily be ported back to 7_4_X or prior releases if needed.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Comment by mark-grimes** [comment]
I've been back porting this to 6_2_X_SLHC (#8985) and just want to check something.
If it is a SecondarySource then the

    factory->activateTimeout(fileIter_->fileName());
    factory->stagein(fileIter_->fileName());

commands are not run, whereas they were in the old way.  Is this okay?

**Comment by mark-grimes** [comment]
Sorry, I see in the comment that you intentionally don't stage in.  Nevermind.

**Pull request merged**
