### PR TITLE
[ROOT] Add explicitely missing headers in DQM and Fireworks

### PR DESCRIPTION
**Pull request by mrodozov**
#### PR description:

Adds missing headers for gVirtualX and TObjArray.
In the latest attempt to integrate ROOT master https://github.com/cms-sw/cmsdist/pull/5618
the integration build failed because ROOT trimmed their header usage and whatever was 
indirectly including TVirtualX header doesn't include it anymore. This pr is including it wherever gVirtualX is used within Fireworks.

#### PR validation:

Builds without failure

### CODE REVIEW

**Comment by Dr15Jones** [comment]
+1

**Comment by alja** [comment]
+1

**Comment by jfernan2** [comment]
+1

**Comment by jfernan2** [comment]
There are CMSSW code rule issues: Search for "catch(...)" statements in *.cc, *.cxx files
Is that expected?

**Comment by mrodozov** [comment]
I'm not sure I've violated anyhow the code rules by this PR I might search in the prev PR involving the same packages if the violation was already there

**Comment by makortel** [comment]
> I'm not sure I've violated anyhow the code rules in this PR, I might search in the prev PR involving the same packages if the violation was already there

Clearly this PR does not add any `catch(...)`, so the violations are very likely already there.

**Comment by smuzaffar** [comment]
Please test
Lets test it for normal ibs too

**Comment by silviodonato** [comment]
+1

**Pull request merged**
