### PR TITLE
hltDiff updates

### PR DESCRIPTION
**Pull request by fwyzard**
- use ROOT's TFile to check for the input files; this automatically supports all protocols supported by ROOT
- make the TriggerEvent collection optional

### CODE REVIEW

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
+1

**Comment by fwyzard** [comment]
@davidlange6 , these changes affect only `hltDiff`, which is a stand-alone tool not use in any central workflow.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
