### PR TITLE
[90X] Fix muon alignment converter

### PR DESCRIPTION
**Pull request by ghellwig**
backport of #18097

Fixes bugs in muon alignment code used for providing muon alignment constants.
Adds also a unit test to prevent such a silent introduction of bugs in the future.
Migrated the respective module to an edm::one module.

Attn.: @lpernie

### CODE REVIEW

**Comment by ghellwig** [comment]
please test

**Comment by ghellwig** [comment]
type bugfix

**Comment by ghellwig** [comment]
please test

**Comment by arunhep** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
