### PR TITLE
Remove AutoMagneticFieldESProducer as obsolete

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

Following the discussion in #28144 that AutoMagneticFieldESProducer is, in fact, obsolete and can be removed, this PR removes it.

#### PR validation:

Code compiles, full matrix runs.

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by perrotta** [comment]
@namapane , please just confirm that nothing is missing

**Comment by namapane** [comment]
@perrotta, looks perfect to me. Thank you @makortel for taking care of this!

**Comment by perrotta** [comment]
+1
- Removal of obsolete code from the release, and links updated in the tests
- Jenkins tests pass

**Comment by Martin-Grunewald** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
