### PR TITLE
Revert "decoupling NANO V10 and V11 [WIP]"

### PR DESCRIPTION
**Pull request by perrotta**
Reverts cms-sw/cmssw#39337

See https://github.com/cms-sw/cmssw/pull/39337#issuecomment-1267863677

### CODE REVIEW

**Comment by perrotta** [comment]
please test workflow 11634.15

**Comment by vlimant** [comment]
that workflow in particular is using a customise function for V10 that the original PR is getting rid of.
it is outdated and can be left broken for now. I will add a PR that switches to the right configuration to run V10

**Comment by perrotta** [comment]
> 11634.15

there are now many more workflows that fail beyond 11634.15 , see https://cmssdt.cern.ch/SDT/html/cmssdt-ib/#/relVal/CMSSW_12_6/2022-10-04-2300?selectedArchs=el8_amd64_gcc10&selectedFlavors=X&selectedStatus=failed

I tested that one simply to verify esplicitely that reverting the PR its error does disappear

**Comment by perrotta** [comment]
Closing this PR because it is not needed any more, given that the fix https://github.com/cms-sw/cmssw/pull/39621 worked as intended

**Pull request closed without merging**
