### PR TITLE
HCALDQM: Add plots for monitoring bad TDC values

### PR DESCRIPTION
**Pull request by DryRun**
Adds 4 plots for monitoring bad TDC values from the HF QIE10s and HEP17 QIE11s (values 50-61 are never supposed to happen, but have been observed in the 2017 data):

- TH1 of bad TDC values, SubdetPM (12*3=36 bins)
- TH1 of bad TDC count vs. BX, SubdetPM (3600*3=10,800 bins)
- TH1 of bad TDC count vs. LS, SubdetPM (4000*3=12,000 bins)
- TH2 of bad TDC count vs ieta vs iphi, depth (84\*64\*7=37,632 bins)

### CODE REVIEW

**Comment by davidlange6** [comment]
hi @DryRun - any plans to fix this pr?

**Comment by DryRun** [comment]
Hi @davidlange6 -- sorry for the delay. I just applied the patch as suggested.

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
