### PR TITLE
Added monitoring for HLT_BTagMu_AK8Jet170_DoubleMu5_v path

### PR DESCRIPTION
**Pull request by marinakolosova**
Hi, 
We would like to add the monitoring of the HLT_BTagMu_AK8Jet170_DoubleMu5_v path. 

@defranchis @tiwariPC

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by defranchis** [comment]
@dmitrijus could you please review?

**Comment by jfernan2** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
