### PR TITLE
Simplify L1TPhase2MuonOffline and fix L1TRate_Offline and L1TStage2CaloLayer2Offline [CMSSW_12_5_X]

### PR DESCRIPTION
**Pull request by perrotta**
#### PR description:

This PR comprehensively backports #39283 and #39297 by cherry picking the very same commits from them.

At the end, this PR does not apply any bug fix (the one originally included in #39283 was lately removed with #3929 because it was not correct) but clean up and simplify largely the structure of the class.

Since Phase2 L1T production is expected to come with 12_5_X, and there are still quite several issues to fix in that code overall, I think it can be better to keep the versions of the code synchronized between the two release cycles, and therefore also merge this PR. Moreover, it allows some performance improvement for that code.

=== Later comment:

I realized that not even #39261 was backported to 12_5_X, and that was a real bug fix for the L1T Phase2 DQM. I cherry picked also that PR here, then.
#### PR validation:

It builds, and it was already tested in master

backport of #39283, #39297 and #39261

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
I realized that not even #39261 was backported to 12_5_X, and that was a real bug fix for the L1T Phase2 DQM. I cherry picked also that PR here, then.

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
type bugfix

**Comment by perrotta** [comment]
backport of #39297

**Comment by emanueleusai** [comment]
+1

**Comment by cecilecaillol** [comment]
+l1

**Comment by perrotta** [comment]
+1

**Pull request merged**
