### PR TITLE
global chi2/ndf cut removed from isLooseTriggerMuon

### PR DESCRIPTION
**Pull request by schhibra**
Back-port of PR #23898.

### CODE REVIEW

**Comment by drkovalskyi** [comment]
This is needed for 10_2 that will going online after the machine development, i.e. it's urgent.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
assign hlt

based on the discussion in the ORP today

**Comment by Martin-Grunewald** [comment]
Depending on timeline for adopting 10_2 on the HLT farm, we may need a 10_1 backport and new release?

**Comment by drkovalskyi** [comment]
I hope that 10_2 will go online soon even if it's delays. So for the immediate fix of the muon trigger we can use the string parse based implementation in 10_1. So I don't think we need to push it back to 10_1.

**Comment by slava77** [comment]
backport of #23898

**Comment by slava77** [comment]
type bugfix

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/23973	90f2cc0
- the "backport" from 10_3_X is correct (the same topic branch is used)
- jenkins tests pass and comparisons with the baseline show differences only in the reco::Muon::selectors variable corresponding to the change in the isLooseTriggerMuon selector.

This is primarily required for the appropriate implementation in HLT in 10_2_X.

**Comment by Martin-Grunewald** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Pull request merged**
