### PR TITLE
Apply a "boundary condition" at the outermost pseudorapidity edges

### PR DESCRIPTION
**Pull request by yslai**
Same bugfix as #12463 for 7_5_X. This bugfix fixes very large (but not infinite) areas that stretches outside the HF by surrounding the event with "mirror events". This is to prevent rare instances, where FastJet would cluster negative pT particles over large distances, and a large, negative particle become a jet in the opposite direction.

Also, the printf() have been converted to EDM log messages.

No performance difference is expected, except for jets either at |eta| ~ 5, or rare events that previously would have contained unreasonably large jet pTs (e.g. 10 TeV).

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@yslai @mandrenguyen 
 is this PR essential for HI data taking?

**Comment by mandrenguyen** [comment]
@slava77 
From what I understand it is necessary
@yslai 
should comment

**Comment by slava77** [comment]
merge

**Pull request merged**
