### PR TITLE
Cleanup Utilities/General

### PR DESCRIPTION
**Pull request by Dr15Jones**
The only use of own_ptr can easily be replaced with unique_ptr.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by Dr15Jones** [comment]
Made a few more cleanups in Utilities/General including removing Tokenizer.

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
