### PR TITLE
Run3-sim152 Take care of difference between DDD and DD4hep in SteppingAction classes 

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Take care of difference between DDD and DD4hep in SteppingAction classes 

#### PR validation:

Use the runTheMatrix test workflows

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
@bsunanda , I think your PR is correct and should be taken but just now there is pending #43493, which also modify the same files. Can we do updates continuously?

**Comment by civanch** [comment]
@bsunanda , what seems to be not optimal is the introduction of run time dependence on DD4hep. From my point of view DD4hep should work for build of geometry and after should not be used. Here for a simple string parsing we include DD4hep header into user actions. I would propose instead add static namespace into SimG4Core/Geometry

static bool SimGeomUtil::isVolume(std::string&, std::string&);
static bool SimGeomUtil::isG4Volume(std::string&, G4String&);

in the code it will be something like


if (isG4Volume("CMSE", physVol->GetName())) { do something }

this may be also used in other places:

if (isG4Volume("CMSE", logVol->GetName())) { do something }

Implementing these (and may other) utility methods basing only on std we may simplify our code avoiding addition of complicate construction in many places, headers of DD4hep, and we do not need extend g4SimHits list of parameters.

**Comment by bsunanda** [comment]
Close this PR. Actions are taken to take care of this

**Pull request closed without merging**
