### PR TITLE
Fix Material Budget Errors

### PR DESCRIPTION
**Pull request by ianna**
* Declare correct type TProfile2D

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by civanch** [comment]
@ianna , it is also fixed in #19939

**Comment by ianna** [comment]
+1

**Comment by dmitrijus** [comment]
+1

**Comment by civanch** [comment]
@davidlange6 , I may be wrong but likely due this bug comparison job never finished if SIM is involved. As a result, some PRs are stack, so please, merge this - it is correct and trivial.

**Comment by davidlange6** [comment]
merge

**Pull request merged**
