### PR TITLE
Implement simple memory tracking on each PR

### PR DESCRIPTION
**Pull request by dmitrijus**
This is work-in-progress, mostly to test how PR scripts work and to start a discussion.

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by dmitrijus** [comment]
This is how it looks like:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-13109/10810/DQMTestsResults/DQMTestsResults/150/memory_25202.0/mbGraph.html

**Comment by deguio** [comment]
+1
can go in as it is. this is the first step towards a more complete testing suite for DQM. more PRs along this line will come.

**Comment by davidlange6** [comment]
@dmitrijus @deguio - if its really ready to be merged, could you update the comment accordingly. Thanks!

**Comment by dmitrijus** [comment]
+1
This can go in, it is stable enough. Further improvements will have their own PRs.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
