### PR TITLE
Fix gcc9 warnings in FastSimDataFormats/L1GlobalMuonTrigger

### PR DESCRIPTION
**Pull request by mrodozov**
#### PR description:

Fix warning in FastSimDataFormats

#### PR validation:

Builds without the warning

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by fabiocos** [comment]
@ssekmen @sbein could you please check? This looks a simple technical fix

**Comment by fabiocos** [comment]
@ssekmen @sbein could you please check? This looks a simple technical fix

**Comment by ssekmen** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
