### PR TITLE
updating from deprecated to supported geometry scenario in test directories

### PR DESCRIPTION
**Pull request by boudoul**
Title says it all

### CODE REVIEW

**Comment by boudoul** [comment]
@ianna , @kpedro88 FYI

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by civanch** [comment]
+1

**Comment by cvuosalo** [comment]
+1

For #15583 ed999af6effd992519f2c9691df1ae60b4235ed4

Updating Phase 2 tests from deprecated to supported geometry scenario. There should be no change in monitored quantities.

The code changes are satisfactory. The Phase 2 unit tests are successful with the new geometry. Jenkins tests against baseline CMSSW_8_1_X_2016-08-24-1100 show no significant differences, as expected.

**Pull request merged**
