### PR TITLE
Fix to PYTHIA 8 photon flux.

### PR DESCRIPTION
**Pull request by hjbossi**
#### PR description:

Fix to PYTHIA 8 photon flux [PR #43840](https://github.com/cms-sw/cmssw/pull/43840) that was discovered when creating the backport. Fix is included both here and in the subsequent backports (see for example [PR #44259](https://github.com/cms-sw/cmssw/pull/44259)). 

#### PR validation:

The modifications in this PR were tested both by myself and @stahlleiton.

### CODE REVIEW

**Comment by hjbossi** [comment]
Could an authorized user please issue the test command?

**Comment by menglu21** [comment]
please test

**Comment by menglu21** [comment]
+1

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
