### PR TITLE
First version of PowhegResHook

### PR DESCRIPTION
**Pull request by mseidel42**
This Pythia8 hook is a C++ port of the alternative hook-based algorithm by Jezo et. al. (arXiv:1607.04538, Appendix B.2) for showering Powheg ttb_NLO_dec and b_bbar_4l processes.

Caveats:
- While the authors found quite good agreement with the reference algorithm, some modifications will be necessary in the future to get complete agreement
- The hook might not be compatible yet with the emission veto hook that we normally use for Powheg+Pythia8.

### CODE REVIEW

**Comment by bendavid** [comment]
It's preferred in general that Pythia8 userhooks are switched on with pythia8 settings flags.  (Take a look at how it's done for the resonance decay filter and similar).

Physics question, is this intended to be used together with the emission veto?  It seems that this only affects the shower scale for FSR in resonance decays, so they shouldn't conflict given that the standard emission veto ignores the resonance decays.

CMSSW already has machinery for running multiple user hooks together, so it should also be ok technically.  What is the concern there?

**Comment by intrepid42** [comment]
@bendavid Thanks for the comments, I implemented a settings flag.

For the emission veto: I tried both hooks together, it technically works. I am just not sure if the emission veto gets confused by the extra gluons (from the resonances) in the LHE or not.

**Comment by bendavid** [comment]
Oh, I see what you mean.

Are the mother-daughter relationships consistent at least?  (In the sense that the radiation from the decay side always has as it's mother either the b from the top decay, or one of the quarks from the hadronic W decay?)

**Comment by intrepid42** [comment]
As far as I see:
- The gluons from the decays have the resonance as mother.
- Additional radiation has the initial-state partons as mothers.

**Comment by perrozzi** [comment]
please test

**Comment by perrozzi** [comment]
+1

**Comment by intrepid42** [comment]
Hi, I just noticed that I accidentally pushed the modifications to the RivetAnalyzer by @jhgoh

**Comment by perrozzi** [comment]
what to do then?

**Comment by intrepid42** [comment]
I think most of those Rivet commits are already merged in CMSSW.

The remaining changes are:

1. Parameter readout duplicated (probably some merge problem, can be fixed easily)
2. RIVET_{REF/INFO}_PATH are only set when empty. This allows us to use Rivet data files from places other than GeneratorInterface/RivetInterface/data.

I actually needed the latter change for testing the new generator with our [TOP Rivet plugins](https://gitlab.cern.ch/CMS-TOP-Rivet/RivetTop), that's why I pulled the change from John's branch. So I would propose to include it in CMSSW.

Note that 6e87d99dc9215d0040fc46bd6a470f5e756ba0af is a physics fix to set the shower scale in hadronic W decays.

**Comment by perrozzi** [comment]
@intrepid42 this PR now even contains a full LHE event. May I suggest to close and prepare separated PRs?

**Comment by intrepid42** [comment]
Hi Luca, the LHE are just 100 events, like for other generators in the test directory of Pythia8Interface.

**Comment by perrozzi** [comment]
@davidlange6 comments?

**Comment by davidlange6** [comment]
all looks ok to me @perrozzi

**Comment by davidlange6** [comment]
please test

**Comment by perrozzi** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
