### PR TITLE
Herwig7 fix seg fault93 x

### PR DESCRIPTION
**Pull request by Andrej-CMS**
Backport of #26905

### CODE REVIEW

**Comment by efeyazgan** [comment]
please test

**Comment by qliphy** [comment]
+1

**Comment by Andrej-CMS** [comment]
@efeyazgan  @qliphy 
could you also please test here

**Comment by qliphy** [comment]
please test

**Comment by qliphy** [comment]
+1

**Comment by prebello** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade

**Comment by kpedro88** [comment]
+1

**Pull request merged**
