### PR TITLE
Improvements for upgrade matrix

### PR DESCRIPTION
**Pull request by kpedro88**
Changes:
1) Moved all 2023 PR/IB tests to 14 TeV processes
2) Added standard set of test WFs for D6 (and some for D5)
3) Added 14 TeV tracker validation WFs for ttbar
4) Centralized the calculation of upgrade WF numbers, and added ability to skip over conflicts with standard matrix WF numbers

I tested 4) by adding a bunch of fake upgrade keys and observed the intended numbering:
```
24853.0 QCD_Pt_600_800_14TeV_TuneCUETP8M1_2023D6PU6_GenSimHLBeamSpotFull14+DigiFull_2023D6PU6+RecoFullGlobal_2023D6PU6+HARVESTFullGlobal_2023D6PU6 
26000.0 FourMuPt_1_200_pythia8_2023D6PU7_GenSimHLBeamSpotFull+DigiFull_2023D6PU7+RecoFullGlobal_2023D6PU7+HARVESTFullGlobal_2023D6PU7 
```

attn: @slava77, @boudoul, @makortel 
This may cause some "missing matrix maps" when merged...
will be backported to 81X

### CODE REVIEW

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by hengne** [comment]
+1

**Comment by slava77** [comment]
I think that there is a problem in this PR
in CMSSW_9_0_X_2016-11-17-1100

```
#runTheMatrix.py -n -e -l 20034 | grep ^2 ==>
20034.0 TTbar_14TeV_TuneCUETP8M1_2023D1_GenSimHLBeamSpotFull+DigiFull_2023D1+RecoFullGlobal_2023D1+HARVESTFullGlobal_2023D1 [1]: cmsDriver.py TTbar_14TeV_TuneCUETP8M1_cfi  --conditions auto:phase2_realistic -n 10 --era Phase2C1 --eventcontent FEVTDEBUG --relval 9000,100 -s GEN,SIM --datatier GEN-SIM --beamspot HLLHC --geometry Extended2023D1 
```
vs
```
#runTheMatrix.py -n -e -l 20034 -w upgrade | grep ^2
20034.0 TTbar_14TeV_TuneCUETP8M1_2023D1_GenSimHLBeamSpotFull14+DigiFull_2023D1+RecoFullGlobal_2023D1+HARVESTFullGlobal_2023D1 [1]: cmsDriver.py TTbar_14TeV_TuneCUETP8M1_cfi  --conditions auto:phase2_realistic -n 10 --era Phase2C1 --eventcontent FEVTDEBUG --relval 9000,100 -s GEN,SIM --datatier GEN-SIM --beamspot HLLHC14TeV --geometry Extended2023D1 
```

note that the two come out with different beam spots.

I think the rule should be in place that the same number should give the same workflow.
It is not the case now.

Please fix.

**Comment by kpedro88** [comment]
@lgray I think we need to port the beamspot-related lines from relval_upgrade to relval_2023

**Comment by slava77** [comment]
which is the right BS for the 14TeV samples?
... and why do we need two kinds? (is it due to dependence of beam size in xy on beam energy?)

**Comment by lgray** [comment]
Hi, I am digging myself out from CMS week and timing..

Yes, use the "VtxSmearedHLLHC14TeV" beamspot. There is a change in the lorentz boost of the bunches, as @slava77 is talking about.

**Comment by lgray** [comment]
I would prefer that we convert of *all* 13 TeV samples in the upgrade workflows. There should only be 14 TeV, they should also all be pythia8 now.

@kpedro88 is this correct?

**Comment by kpedro88** [comment]
@lgray we can't remove 13TeV workflows from the upgrade fragment list, because it's also used for 2017 etc. Everything should be pythia8 now. If there's some specific workflow that's missing a 14TeV version, it can be added (I did some recently, but maybe not all.)

**Comment by lgray** [comment]
Ok, there are definitely a few we'll add then.

**Comment by smuzaffar** [comment]
@kpedro88 , could this PR be the reason of these errors in new 2361* workflows?
https://cms-sw.github.io/relvalLogDetail.html#slc6_amd64_gcc530;CMSSW_9_0_X_2016-11-17-1100

**Comment by kpedro88** [comment]
#16682 fixes that

**Pull request merged**
