### PR TITLE
Run3-alca176 Introduce muon veto for isotrack analysis

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Introduce muon veto for isotrack analysis

#### PR validation:

Used in analyzing data reconstructed with 2 different algorithms 

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by christopheralanwest** [comment]
please test

**Comment by bsunanda** [comment]
@christopheralanwest Could you approve this PR?

**Comment by christopheralanwest** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
