### PR TITLE
update of "baseDataSetRelease" inputs with 930pre4 strings

### PR DESCRIPTION
**Pull request by prebello**
@fabozzi @franzoni 
- GEN-SIM of all MC relvals regenerated due changes in the magnetic field maps (according  #20067)
- FastSim strings updated

### CODE REVIEW

**Comment by fabozzi** [comment]
please test

**Comment by fabozzi** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Comment by smuzaffar** [comment]
@prebello and @davidlange6 , few relvals tests in IBs are failing to find updated datasets 

https://cms-sw.github.io/relvalLogDetail.html#slc6_amd64_gcc630;CMSSW_9_3_X_2017-08-23-2300
https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc6_amd64_gcc630/CMSSW_9_3_X_2017-08-23-2300/pyRelValMatrixLogs/run/250200.1_ProdZEE_13_pmx25ns+ProdZEE_13+DIGIPRMXUP15_PROD_PU25+RECOPRMXUP15PROD_PU25/step2_ProdZEE_13_pmx25ns+ProdZEE_13+DIGIPRMXUP15_PROD_PU25+RECOPRMXUP15PROD_PU25.log

```
the query is file dataset = /RelValPREMIXUP15_PU25/CMSSW_9_3_0_pre4-93X_mc2017_realistic_v1-v1/GEN-SIM-DIGI-RAW
DAS succeeded after 1 attempts 0
found files:  []
```
I guess these new dataset is not available yet ... right?

**Comment by fabozzi** [comment]
Thank you @smuzaffar 
We have not yet regenerated that dataset, so that string has been accidentally changed.
I have restored back in PR #20255

**Pull request merged**
