### PR TITLE
Fix missing headers in Geometry/HcalCommonData to test boost 1.67

### PR DESCRIPTION
**Pull request by mrodozov**
Fixes missing headers needed for this test https://github.com/cms-sw/cmsdist/pull/4004

### CODE REVIEW

**Comment by mrodozov** [comment]
please test with https://github.com/cms-sw/cmsdist/pull/4004

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
This PR does not need new boost. The missing cmath header is from std and should have been included in any case.

**Comment by ianna** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
