### PR TITLE
Update propagate_const and add propagate_const_array

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Update `edm::propagate_const<...>` and its unit test:
  - make most methods of edm::propagate_const<T> constexpr;
  - add a unit test for edm::propagate_const<incomplete_type *>.

Add `edm::propagate_const_array<...>` to support T[], unique_ptr<T[]>, etc.

Implement `edm::propagate_const_array` template with similar functionality to `edm::propagate_const`, but with a subscript operator and support for types like `T[]`, `std::unique_ptr<T[]>` and similar array-like types.

Add support for `get_underlying_safe<propagate_const_array<T>>`.

Add unit tests for `edm::propagate_const_array`:
  - `propagate_const_array<T[]>`
  - `propagate_const_array<unique_ptr<T[]>>`
  - `propagate_const_array<shared_ptr<T[]>>`
  - `propagate_const_array<incomplete_type[]>`

#### PR validation

Unit test `testFWCoreUtilities` builds and runs.

### CODE REVIEW

**Comment by fwyzard** [comment]
These proposal stems from the discussion at https://github.com/cms-sw/cmssw/pull/32039 and https://github.com/cms-patatrack/cmssw/pull/574 .

It turns out that `edm::propagate_const` (as well as `std::experimental::propagate_const`) do not support types with a subscript operator `[]` but without an indirection operator `*` - for example, `std::unique_ptr<T[]>`.

The latter can be useful to guarantee that the conditions data are not modified by accident, by propagating the constness of their container to the actual data.

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
@Dr15Jones Could you review this one?

**Comment by Dr15Jones** [comment]
Although I think this change is pretty neat and definitely does something very useful, my concern is `edm::propagate_const` was meant to be replaced with `std::propagate_const` once (if?) it enters the standard from the `std::experimental` namespace. As such the `std::propagate_const` does not support arrays, see: 
http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2020/n4853.html#propagate_const

Though introduced in C++17, the `std::propagate_const` was not included in C++20 (although it is in `std::experimental` for C++20). I'm not sure what this means for the future of that implementation.

As a possible way to still allow `edm::propagate_const` to be replaced with `std::propagate_const` (if that future happens) how about creating a separate `edm::propagate_const_array` class?

**Comment by fwyzard** [comment]
Them... we make a PR for the standard ?

**Comment by fwyzard** [comment]
@makortel @Dr15Jones here is a possible reimplemenation of `edm::propagate_const_array<T>`:
```c++
namespace edm {

  template <typename T>
  class propagate_const_array;

  template <typename T>
  std::decay_t<T>& get_underlying(propagate_const_array<T>&);
  template <typename T>
  std::decay_t<T> const& get_underlying(propagate_const_array<T> const&);

  template <typename T>
  class propagate_const_array {
  public:
    friend std::decay_t<T>& get_underlying<T>(propagate_const_array<T>&);
    friend std::decay_t<T> const& get_underlying<T>(propagate_const_array<T> const&);
    
    template <typename U>
    friend class propagate_const_array;

    using element_type = typename std::remove_reference<decltype(std::declval<T&>()[0])>::type;

    propagate_const_array() = default;

    propagate_const_array(propagate_const_array<T>&&) = default;
    propagate_const_array(propagate_const_array<T> const&) = delete;
    template <typename U>
    propagate_const_array(U&& iValue) : m_value(std::forward<U>(iValue)) {}

    propagate_const_array<T>& operator=(propagate_const_array&&) = default;
    propagate_const_array<T>& operator=(propagate_const_array<T> const&) = delete;

    template <typename U>
    propagate_const_array& operator=(propagate_const_array<U>& other) {
      static_assert(std::is_convertible_v<std::decay_t<U>, std::decay_t<T>>, "Cannot assign propagate_const_array<> of incompatible types");
      m_value = other.m_value;
      return *this;
    }

    template <typename U>
    propagate_const_array& operator=(U&& iValue) {
      m_value = std::forward<U>(iValue);
      return *this;
    }

    // ---------- const member functions ---------------------
    element_type const& at(size_t pos) const { return m_value[pos]; }
    element_type const& operator[](size_t pos) const { return this->at(pos); }

    // ---------- member functions ---------------------------
    element_type& at(size_t pos) { return m_value[pos]; }
    element_type& operator[](size_t pos) { return this->at(pos); }

  private:
    // ---------- member data --------------------------------
    std::decay_t<T> m_value;
  };

  template <typename T>
  std::decay_t<T>& get_underlying(propagate_const_array<T>& iP) {
    return iP.m_value;
  }

  template <typename T>
  std::decay_t<T> const& get_underlying(propagate_const_array<T> const& iP) {
    return iP.m_value;
  }

}  // namespace edm
```

One limitation of this implementation is that it does not support `edm::propagate_const_array<T[]>` if `T` is an incomplete type.
It might be possible to support it (I'm still not sure) but it'd probably some more work.

**Comment by fwyzard** [comment]
> One limitation of this implementation is that it does not support `edm::propagate_const_array<T[]>` if `T` is an incomplete type.
> It might be possible to support it (I'm still not sure) but it'd probably some more work.

Here is a version that seems to work also for arrays on incomplete types.
Of course the array cannot be instantiated until the type has been defined:
```c++
namespace edm {

  namespace impl {

    // check if a type T has a subscript operator T[N]
    template<typename, typename = void>
    struct has_subscript_operator : std::false_type {};

    template<typename T>
    struct has_subscript_operator<T, std::void_t<decltype(std::declval<T&>()[0])>> : std::true_type {};

    template<typename T>
    constexpr auto has_subscript_operator_v = has_subscript_operator<T>::value;

    // for a type T, return the type of the return value of the subscript operator T[N]
    template <typename T, typename = void, typename = void>
    struct subscript_type {};

    // the specialisations for arrays allow supporting incomplete types
    template <typename T>
    struct subscript_type<T[]> {
      using type = T;
    };

    template <typename T, int N>
    struct subscript_type<T[N]> {
      using type = T;
    };

    template<typename T>
    struct subscript_type<T, std::enable_if_t<not std::is_array_v<T>>, std::enable_if_t<has_subscript_operator_v<T>>> {
      using type = typename std::remove_reference<decltype(std::declval<T&>()[0])>::type;
    };

    template<typename T>
    using subscript_type_t = typename subscript_type<T>::type;

  }

  template <typename T>
  class propagate_const_array;

  template <typename T>
  std::decay_t<T>& get_underlying(propagate_const_array<T>&);
  template <typename T>
  std::decay_t<T> const& get_underlying(propagate_const_array<T> const&);

  template <typename T>
  class propagate_const_array {
  public:
    friend std::decay_t<T>& get_underlying<T>(propagate_const_array<T>&);
    friend std::decay_t<T> const& get_underlying<T>(propagate_const_array<T> const&);
    
    template <typename U>
    friend class propagate_const_array;

    //using element_type = typename std::remove_reference<decltype(std::declval<T&>()[0])>::type;
    using element_type = typename impl::subscript_type_t<T>;

    propagate_const_array() = default;

    propagate_const_array(propagate_const_array<T>&&) = default;
    propagate_const_array(propagate_const_array<T> const&) = delete;
    template <typename U>
    propagate_const_array(U&& iValue) : m_value(std::forward<U>(iValue)) {}

    propagate_const_array<T>& operator=(propagate_const_array&&) = default;
    propagate_const_array<T>& operator=(propagate_const_array<T> const&) = delete;

    template <typename U>
    propagate_const_array& operator=(propagate_const_array<U>& other) {
      static_assert(std::is_convertible_v<std::decay_t<U>, std::decay_t<T>>, "Cannot assign propagate_const_array<> of incompatible types");
      m_value = other.m_value;
      return *this;
    }

    template <typename U>
    propagate_const_array& operator=(U&& iValue) {
      m_value = std::forward<U>(iValue);
      return *this;
    }

    // ---------- const member functions ---------------------
    element_type const& at(size_t pos) const { return m_value[pos]; }
    element_type const& operator[](size_t pos) const { return this->at(pos); }

    // ---------- member functions ---------------------------
    element_type& at(size_t pos) { return m_value[pos]; }
    element_type& operator[](size_t pos) { return this->at(pos); }

  private:
    // ---------- member data --------------------------------
    std::decay_t<T> m_value;
  };

  template <typename T>
  std::decay_t<T>& get_underlying(propagate_const_array<T>& iP) {
    return iP.m_value;
  }

  template <typename T>
  std::decay_t<T> const& get_underlying(propagate_const_array<T> const& iP) {
    return iP.m_value;
  }

}  // namespace edm
```

**Comment by fwyzard** [comment]
See https://github.com/cms-patatrack/cmssw/pull/574 for the actual implementation and use case.
Could you leave there any comments ?  I'll propagate here the final version.

**Comment by fwyzard** [comment]
@Dr15Jones @makortel I've update this PR to reflect the latest version of the changes in https://github.com/cms-patatrack/cmssw/pull/574 .

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
`g++ -fsyntax-only` complains about
```
src/FWCore/Utilities/interface/propagate_const_array.h:103:46: error: declaration of 'operator[]' as non-function
     constexpr element_type const& operator[](size_t pos) const { return m_value[pos]; }
                                              ^~~~~~
src/FWCore/Utilities/interface/propagate_const_array.h:103:44: error: expected ';' at end of member declaration
     constexpr element_type const& operator[](size_t pos) const { return m_value[pos]; }
                                            ^
                                             ;
src/FWCore/Utilities/interface/propagate_const_array.h:103:52: error: expected ')' before 'pos'
     constexpr element_type const& operator[](size_t pos) const { return m_value[pos]; }
                                             ~      ^~~~
                                                    )
src/FWCore/Utilities/interface/propagate_const_array.h:109:40: error: declaration of 'operator[]' as non-function
     constexpr element_type& operator[](size_t pos) { return m_value[pos]; }
                                        ^~~~~~
src/FWCore/Utilities/interface/propagate_const_array.h:109:38: error: expected ';' at end of member declaration
     constexpr element_type& operator[](size_t pos) { return m_value[pos]; }
                                      ^
                                       ;
src/FWCore/Utilities/interface/propagate_const_array.h:109:46: error: expected ')' before 'pos'
     constexpr element_type& operator[](size_t pos) { return m_value[pos]; }
                                       ~      ^~~~
                                              )
```

**Comment by fwyzard** [comment]
Ah... the problem is that - by itself - `propagate_const_array.h` does not include any of the headers that define `size_t`.

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
> ---> test TestRunnerFWCoreTFWLiteSelector had ERRORS

Mhm, is this actually related to this PR ?

**Comment by makortel** [comment]
> > ---> test TestRunnerFWCoreTFWLiteSelector had ERRORS
> 
> Mhm, is this actually related to this PR ?

Unlikely, we've seen that unit test  to fail in ROOT6 master IBs (https://github.com/cms-sw/cmssw/issues/31233, https://github.com/cms-sw/cmssw/issues/32162) and apparently sporadically for years (https://github.com/cms-sw/cmssw/issues/31233#issuecomment-680023714).

**Comment by makortel** [comment]
+1

**Comment by fwyzard** [comment]
@silviodonato @qliphy can we have this in pre10 ?
It would simplify the various Patatrack PRs currently under review.

**Comment by silviodonato** [comment]
urgent

**Comment by mrodozov** [comment]
> > > ---> test TestRunnerFWCoreTFWLiteSelector had ERRORS
> > 
> > 
> > Mhm, is this actually related to this PR ?
> 
> Unlikely, we've seen that unit test to fail in ROOT6 master IBs (#31233, #32162) and apparently sporadically for years ([#31233 (comment)](https://github.com/cms-sw/cmssw/issues/31233#issuecomment-680023714)).

well in default IBs it will be a ... unpleasant to brake PRs

**Comment by fwyzard** [comment]
> well in default IBs it will be a ... unpleasant to brake PRs

@mrodozov uhm... what ?

**Comment by mrodozov** [comment]
> > well in default IBs it will be a ... unpleasant to brake PRs
> 
> @mrodozov uhm... what ?

if this failing test start breaking more often in the default IBs (which it didn't do so far, it was failing in ROOT6 IB only)
it will start bothering people. with their PR working but the test failing. like in this pr

**Comment by qliphy** [comment]
+1

**Pull request merged**
