### PR TITLE
Check valid pads and clusters in GEM trigger primitive producers

### PR DESCRIPTION
**Pull request by dildick**
#### PR description:

I added a few statements to ignore invalid pads and clusters in the GEM-CSC trigger. I also added checks (LogWarnings, not selections) in the GEM trigger primitive producers.

#### PR validation:

Tested with 23234.0 in 11_2_X.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

### CODE REVIEW

**Comment by silviodonato** [comment]
@rekovic do you have any comments?

**Comment by silviodonato** [comment]
please test

**Comment by dildick** [comment]
@rekovic If you could wait with signing this. I'll amend this pull requests with log warnings in the pad and cluster producer is invalid primitives are produced.

**Comment by kpedro88** [comment]
code-checks

**Comment by kpedro88** [comment]
please test

**Comment by kpedro88** [comment]
+upgrade

**Comment by civanch** [comment]
+1

**Comment by rekovic** [comment]
@dildick 
To understand if LogWarnings are a proper level of Message, what causes some GEM pads and clusters to be invalid ?

Otherwise, fine.

**Comment by dildick** [comment]
In principle, pads and clusters should be valid in the simulation. If they are not, the underlying GEM digis have invalid strip numbers, e.g. >=384 for GE1/1, or >=768 for GE2/1, which may be pointing to geometry issues. So that should not be happening. 

Now in the data, I don't know the CTP7 firmware or the GEM unpacker well enough to understand in which cases invalid GEM tracking data might read out incorrectly or unpacked incorrectly. I can imagine that a broken GEM strip mapping in the configuration database might cause problems.

**Comment by dildick** [comment]
@rekovic I'm having difficulties with #30998. This PR should go in first.

**Comment by dildick** [comment]
Just tested with WF 23234.0 in 11_2_X

**Comment by kpedro88** [comment]
please test

**Comment by kpedro88** [comment]
+upgrade

**Comment by cvuosalo** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by dildick** [comment]
@rekovic Could you sign, please?

**Comment by silviodonato** [comment]
kind reminder @cms-sw/l1-l2

**Comment by rekovic** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
