### PR TITLE
Additional FED IDs for new pixel detector

### PR DESCRIPTION
**Pull request by mommsen**
Add new range of FED IDs for the upgraded Pixel detector.

### CODE REVIEW

**Comment by mommsen** [comment]
please test

**Comment by mommsen** [comment]
+1

**Comment by mommsen** [comment]
Could you please merge this pull request for the next pre-release? It's important to get this into 8_1_0.
Thanks, Remi.

**Comment by davidlange6** [comment]
Hi @mommsen - sorry to be slow - i wanted to see what code the changes could possibly affect and that took too long..

anyway, how should we think of MIN/MAXSiPixeluTCAFEDID vs MIN/MAXSiPixel2nduTCAFEDID?

**Comment by mommsen** [comment]
The first range has been defined before and is used for the readout of the upgraded pixel detector. However, pixel might need a dual readout, i.e. each uTCA FED will (potentially) get a second DAQ link. As the original range is too short, we allocated a 2nd range. I hope this makes the naming clearer.

**Comment by davidlange6** [comment]
https://github.com/cms-sw/cmssw/blob/86088d61d757bad0e55addda14859c5ea6108d84/DataFormats/FEDRawData/src/FEDNumbering.cc

https://github.com/cms-sw/cmssw/blob/712fddfa423da1d72f436bca6074b3cb85da455b/EventFilter/SiPixelRawToDigi/src/PixelUnpackingRegions.cc#L103

https://github.com/cms-sw/cmssw/blob/86088d61d757bad0e55addda14859c5ea6108d84/CalibTracker/SiPixelConnectivity/src/SiPixelFedCablingMapBuilder.cc#L72

Hopefully @dkotlins  can clarify/assist on the last two

**Comment by dkotlins** [comment]
Sorry, I do not understand. What is wrong with the code?
Danek

**Comment by davidlange6** [comment]
Hi @dkotlins - @mommsen is adding additional potential fed ids for phase 1 pixels.

**Comment by dkotlins** [comment]
Yes, I know but these are “potential” ids. They are not used anywhere and will not be included in 
any pixel cabling maps.
This is something that might never be used, certainly not before LS2.
D.

**Comment by davidlange6** [comment]
seems there is a difference of urgency mentioned in this PR then - as to reduce surprise bugs, we should either not have these fedids defined here or have them supported so that we don't have to remember to change this code later when the fedids are used and suddenly part of an urgent data taking campaign

**Comment by mommsen** [comment]
Fact is that the DAQ group reserved those FED ids on request of Pixel (Andreas Kornmeyer et al.) In case that pixel does not want to have this range reserved after all, please contact the DAQ group (Frans Meijers or Samim Erhan). I'm merely the secretary trying to keep things in sync.

**Comment by davidlange6** [comment]
I just look for consistency - I presume @dkotlins and Andreas can discuss and decide

**Comment by dkotlins** [comment]
The additional links have been reserved “just-in-case”. 
There is no intention to use them anytime soon, certainly not in 2017.
Remi was simply nice enough to modify the *.h file in CMSSW for bookkeeping 
reasons.
D.

**Comment by davidlange6** [comment]
hi @mommsen - as it seems the pixel side would rather wait for later to deal with these new fed possibilities, could you just comment them out for the purpose of this PR. then its clear that cmssw won't support them. Thanks

**Comment by mommsen** [comment]
@davidlange6 no. I re-iterate that the DAQ group would like to keep this list in sync with the reserved FED ids. What is the reason not to reserve them in CMSSW now, too?

**Comment by davidlange6** [comment]
consistency. don’t want a bug waiting to happen that we all forget about in 4 years (which is I understand the timescale on which we need to remember this topic:( )

**Comment by mommsen** [comment]
Consistency is exactly the point. These FED ids are reserved for the 2nd pixel readout (and the pixel test crate which is being commissioned, btw.) Why should this not be reflected in CMSSW? In order that somebody comes along and picks this range for something else in the next year? What bug are you afraid of?

**Comment by dkotlins** [comment]
Hello,
I did not expect this to explode so much.
FED-IDs in the file from Remi are just constants. 
Is it really illegal to have constants which are unused for now?
 
In most (all?) pixel code which uses FEDs we have some structure like this:

 for(int id = FEDmin; id<=FEDmax; id++) { do someyhing }

So it is very easy to adopt it for any single range e.g. used by phase0 or phase1 pixels.

If there are 2 ranges one would have to modify each such code sequence into two “for” loops,
or something like similar.
This is of course possible but requires some time.
I am not against it but I really have not time myself.
I can ask Viktor/Janos, maybe they can find somebody to work on this.
However having in mind that e.g. the pixel geometry/material is not yet finished it would 
be an unwise redirection of manpower.
  
D.

**Comment by davidlange6** [comment]
Hi
I'm afraid of having half the pixel code written with a different set of assumptions then the other half..

Cheers,
David


On 14 Nov 2016, at 21:12, dkotlins <notifications@github.com<mailto:notifications@github.com>> wrote:

Hello,
I did not expect this to explode so much.
FED-IDs in the file from Remi are just constants.
Is it really illegal to have constants which are unused for now?

In most (all?) pixel code which uses FEDs we have some structure like this:

for(int id = FEDmin; id<=FEDmax; id++) { do someyhing }

So it is very easy to adopt it for any single range e.g. used by phase0 or phase1 pixels.

If there are 2 ranges one would have to modify each such code sequence into two “for” loops,
or something like similar.
This is of course possible but requires some time.
I am not against it but I really have not time myself.
I can ask Viktor/Janos, maybe they can find somebody to work on this.
However having in mind that e.g. the pixel geometry/material is not yet finished it would
be an unwise redirection of manpower.

D.

**Comment by emeschi** [comment]
I am not at all sure how this item deserved such an amount of words.
It is clear that the proposed approach, which is the one we have always followed in the past, makes perfect sense and takes into account that the daq group is the custodian of fed ids.
On the other hand, given the fuss this has given rise to, I could also propose that we remove FEDNumbering.h/cc and let every subsystem make up their own constants instead.
...or not...

Emilio

Sent from my iPhone

On Nov 14, 2016, at 9:26 PM, David Lange <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi
I'm afraid of having half the pixel code written with a different set of assumptions then the other half..

Cheers,
David


On 14 Nov 2016, at 21:12, dkotlins <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com>> wrote:

Hello,
I did not expect this to explode so much.
FED-IDs in the file from Remi are just constants.
Is it really illegal to have constants which are unused for now?

In most (all?) pixel code which uses FEDs we have some structure like this:

for(int id = FEDmin; id<=FEDmax; id++) { do someyhing }

So it is very easy to adopt it for any single range e.g. used by phase0 or phase1 pixels.

If there are 2 ranges one would have to modify each such code sequence into two “for” loops,
or something like similar.
This is of course possible but requires some time.
I am not against it but I really have not time myself.
I can ask Viktor/Janos, maybe they can find somebody to work on this.
However having in mind that e.g. the pixel geometry/material is not yet finished it would
be an unwise redirection of manpower.

D.

**Comment by davidlange6** [comment]
Hi @emeschi - I fully support the current system from the daq group. and I guess you'll agree that the release team should try to ensure that code in the release is self consistent. (I believe what I've asked for (not even as part of this PR) is just a matter of a few characters change, or at most a second set of for loops in two or three places as suggested above)

**Comment by jkarancs** [comment]
Hello everyone.

I suggest to go ahead with this PR with the promise we immediately start to prepare another PR where we ensure full support is given to the FEDNumbering class. This might require some extensive tests Danek mentioned to ensure that we use the right (non-hardcoded) FED numbering everywhere in our codes. This might require some time, nevertheless should not halt us from implementing this current fix. 

Do you agree?

**Comment by davidlange6** [comment]
+1

**Pull request merged**
