### PR TITLE
HLT Migration to 910pre3 template and development (91X)

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
HLT Migration to 910pre3 template and development (91X)
Based on CMSSW_9_1_X_2017-05-12-1100.

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
backport of #18725

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
