### PR TITLE
TrackerHitAssociator clear maps each new event

### PR DESCRIPTION
**Pull request by wmtford**
Just implement the minimal fix suggested by Dmitrijus to prevent the memory leak from the TrackerHitAssociator in CMSSW_7_5_0_pre2.  I'll need to invest some effort to understand the consumes changes made by David Lange and Bill Tanenbaum, before attempting any more ambitious cure.  I also haven't tested anything beyond compilation.  So I leave to reviewers to decide whether to go with this PR as a quick fix or look for something better.

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by civanch** [comment]
@wmtford , test fails for the issue not connected with this PR but this help to update this PR, because it seems that the same two lines as inserted after line 112 are needed after line 168.

**Comment by civanch** [comment]
please test

**Comment by wmtford** [comment]
@civanch  You're right; that was sloppy on my part.  I've updated the PR with this addition.

**Comment by civanch** [comment]
+1

**Comment by Dr15Jones** [comment]
The failure was due to DAS

**Pull request merged**
