### PR TITLE
Run4-hgx286 Start with the cell definitions of V16

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Start with the cell definitions of V16 and add new partial wafer types

#### PR validation:

Tested positioning the cells using cmsShow

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

**Comment by qliphy** [comment]
+1

**Pull request merged**
