### PR TITLE
Fix the GE2/1 pad producer for 16-partition geometries

### PR DESCRIPTION
**Pull request by dildick**
#### PR description:

The GE2/1 pad producer for 16-partition geometries was not correctly working. 

#### PR validation:

Tested with D80 geometry on file ```/store/relval/CMSSW_12_1_0_pre4/RelValTenMuExtendedE_0_200/GEN-SIM-DIGI-RAW/121X_mcRun4_realistic_v5_2026D80noPU-v1/2580000/0021ccff-2964-4ee4-9ad3-c0c81bb0fb83.root```

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

### CODE REVIEW

**Comment by dildick** [comment]
@jfernan2 Can you restart the tests, please?

**Comment by jfernan2** [comment]
please test with #35921

**Comment by dildick** [comment]
A few validation plots for the D77 muon geometry with 16-partition GE2/1 detector from WF 35234.999. Before (blue): no trigger pad or clusters. After (red): trigger pad and clusters now present.

* Trigger Pads

GEM__Pad_total_pads_per_event_GE21-M-L1
GEM__Pad_total_pads_per_event_GE21-M-L2
GEM__Pad_total_pads_per_event_GE21-P-L1
GEM__Pad_total_pads_per_event_GE21-P-L2

* Clusters of Trigger Pad Clusters
 
GEM__PadCluster_total_pad_cluster_GE21-M-L1
GEM__PadCluster_total_pad_cluster_GE21-M-L2
GEM__PadCluster_total_pad_cluster_GE21-P-L1
GEM__PadCluster_total_pad_cluster_GE21-P-L2

**Comment by dildick** [comment]
fyi @rathjd

**Comment by jfernan2** [comment]
@dildick a lot of changes in CSC have appeared in the last test, are they expected?
https://tinyurl.com/yemfgswb
https://tinyurl.com/yjkpdz29

**Comment by dildick** [comment]
Not sure if I understand all the changes. 

This plot probably makes sense for WF38634.0. The GEM-CSC trigger is active in ME1/1 and ME2/1. It allows for LCTs being produced with ALCT and 2 GEM clusters (with a missing CLCT).
CSC__Summary_CSC_wo_CLCT

But I'm not sure how to interpret plots like ```FEDTotalTMBs```, ```All_DDUs_Average_Event_Size``` or ```All_DDUs_Event_Size```.

**Comment by dildick** [comment]
WF 35234.999 has more changes. But now there are non-empty bins in the CSC_wo_CLCT 2D plot that are not ME1/1 or ME2/1. Not sure how to interpret that.

**Comment by dildick** [comment]
@jfernan2 Can you rerun the tests, please?

**Comment by jfernan2** [comment]
Is there any additonal commit between last run of tests and now?

**Comment by dildick** [comment]
Sorry, I misread the 2D plots. It looks like the only changes are in ME2/1 chambers. So those make sense.

The changes are only for ME+2/1 or ME-2/1

Screen Shot 2021-11-08 at 9 26 27 AM
Screen Shot 2021-11-08 at 9 26 44 AM
Screen Shot 2021-11-08 at 9 26 50 AM

**Comment by jfernan2** [comment]
+1

**Comment by dildick** [comment]
FYI @giovanni-mocellin

**Comment by dildick** [comment]
Can this PR be merged? Thanks!

**Comment by rekovic** [comment]
+1

**Comment by perrotta** [comment]
please test
(16 days old tests need to be refreshed...)

**Comment by perrotta** [comment]
Me being not so fond with the CSC electronics, could someone please confirm that the differences reported in the "CSC Summay" DQM plots, as for example in 35034.0

image

or in 35234.999

image

are indeed those expected?

Sven @dildick asked himself the same in https://github.com/cms-sw/cmssw/pull/35779#issuecomment-961223842, but he didn't answer himself (at least not in this thread)...

**Comment by dildick** [comment]
@perrotta I'll take a look.

@rathjd @sifuluo please check if the last commit now properly matches GE2/1 pads and clusters to muons.

**Comment by perrotta** [comment]
@dildick code format fixes must be applied before we can start the tests

**Comment by dildick** [comment]
@perrotta Yes, will do. There is apparently a duplication of matching pads in GE2/1 (in the validation code). It's because GE1/1 and GE2/1 pads should be treated differently for muon >=M8 geometries. @rathjd and @sifuluo fixed that issue. I'll include in this PR.

**Comment by dildick** [comment]
still need to do the code format

**Comment by dildick** [comment]
A few validation plots by @sifuluo:

If there is at least 1 GEMSimHit in a detector, a GEMDigi/GEMPadDigi/GEMPadDigiCluster is expected to be reconstructed and matched to the SimHit, this contributes to N_{Exp}. 

The successfully reconstructed goes to N_{Reco}, and then the matched is N_{Matched}. 

So the Reconstruction Efficiencies are N_{Reco}/N_{Exp} and Matching Efficiencies are N_{Matched} / N_{Reco}. 

GEMDIgi, GEMPadDigi and GEMPadDigiCluster matching efficiencies are plot w.r.t. eta, phi and z of the SimHits.

In the plots below, D1 means GE1/1, and D2 means GE2/1.

* Matching efficiency of sim muons to GEM digis

GEMMatchEff_D1
GEMMatchEff_D2

* Matching efficiency of sim muons to GEM pads (OR of two digis)

PadMatchEff_D1
PadMatchEff_D2

* Matching efficiency of sim muons to GEM pad clusters (several neighboring pads in a partition)

ClusterMatchEff_D1
ClusterMatchEff_D2

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
@dildick as usual, I don't have the expertise to judge if the changes introduced are expected so, if you could give green light to them it is apreciated:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_2_X_2021-11-21-2300+813a0b/46968/dqm-histo-comparison-summary.html

Specially because there differences in CSC beyond the changes introduced in GEM code

**Comment by dildick** [comment]
The plots look good. There are differences only for WFs which have a muon geometry >= M8 (https://github.com/cms-sw/cmssw/blob/master/Configuration/Geometry/README.md). The Phase-2 WFs with the older M4 geometry do not change. That makes sense, because the pad producer was not broken for M4. For >=M8 the pad producer and pad cluster producer are now working. In the CSC L1T producer, GEM-CSC integrated local triggers are being produced in ME2/1 OTMBs. The CSC DQM is responding to the OTMBs with GEM-CSC LCTs.

**Comment by jfernan2** [comment]
+1
Thanks @dildick

**Comment by dildick** [comment]
Thanks

**Comment by dildick** [comment]
@rekovic Can you sign off, please?

**Comment by dildick** [comment]
@rekovic Can you sign, please?

**Comment by rekovic** [comment]
+1

**Comment by perrotta** [comment]
+1
- Observed differences in the DQM outputs being blessed by the detector experts

**Pull request merged**
