### PR TITLE
Run3-hcx377D Provide a scenario for post-Run2 geometry for which the cfi file existed in Geometry/CMSCommonData/python

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Provide a scenario for post-Run2 geometry for which the CFI file existed in Geometry/CMSCommonData/python

#### PR validation:

Use g4 overlap tool to test the new files

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by srimanob** [comment]
Hi @bsunanda 

Could you provide more context on why we need these 2019 configurations now? If there's an Indico link to the discussion or any related slides, that would be very helpful. Thx.

**Comment by bsunanda** [comment]
At the end of 2018 HB was having 4 depths while in Run3 there were many other detectors also got changed. It may be worthwhile to see the impact of HB changes only. That is why 2019 was created long ago as a cfi file. I just supplemented the cff file to ease the studies.
________________________________

**Comment by bsunanda** [comment]
+geometry

**Comment by bsunanda** [comment]
@subirsarkar Please approve this

**Comment by subirsarkar** [comment]
+Upgrade

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
