### PR TITLE
Backport of T1tttt config to 7_4_X

### PR DESCRIPTION
**Pull request by duanders**
Backport of the new SUSY RelVal config as discussed here: https://github.com/cms-sw/cmssw/pull/8620

@franzoni

### CODE REVIEW

**Comment by franzoni** [comment]
hello @duanders 
thanks for making this PR.

@degano @davidlange6 ,
this PR has no labels. How can we get it to be sign-able by GEN ?

@bendavid @covarell ,
can you please keen an eye on this and sign asap ?

@hengne is following this (he has actually made the point to me, a moment ago)

**Comment by franzoni** [comment]
please test

**Comment by bendavid** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
