### PR TITLE
Produce and use custom HGCal towers for baseline GCT calo jets and taus.

### PR DESCRIPTION
**Pull request by EmyrClement**
#### PR description:

Modify Phase-2 GCT jet and tau objects so that they use non-default HGCal towers as input.  I made a new task that produces these new inputs towers and produces the GCT objects with these towers. The additional towers are added to the event content.

#### PR validation:

Tested in [#1226 in cms-l1t-offline](https://github.com/cms-l1t-offline/cmssw/pull/1226). New objects are produced and consumed by GCT producer, and physics performance of GCT jets and taus are as expected. 

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

### CODE REVIEW

**Comment by epalencia** [comment]
Please test

**Comment by epalencia** [comment]
Please test

**Comment by aloeliger** [comment]
+l1

**Comment by epalencia** [comment]
ping @cms-sw/upgrade-l2

**Comment by srimanob** [comment]
+Upgrade

**Comment by srimanob** [comment]
@cmsbuild please test

Refresh the test after a month.

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
