### PR TITLE
MTV protection for samples without jets info

### PR DESCRIPTION
**Pull request by vberta**
#### PR description:

Added protection to run the Validation on a sample without the jets information. Without this protection the user should add cores = cms.InputTag("") in the configuration file if the jet information is missing.

#### PR validation:

- specific validation on a sample without jet information
- runTheMatrix

### CODE REVIEW

**Comment by jfernan2** [comment]
Hi @vberta, I can't seem to find you in [DQM contacts list](https://twiki.cern.ch/twiki/bin/viewauth/CMS/DQMContacts). Could you please briefly introduce yourself?

**Comment by fioriNTU** [comment]
@vberta , please check https://github.com/cms-sw/cmssw/pull/27611#issuecomment-515139392 and briefly introduce yourself, please

**Comment by vberta** [comment]
I'm sorry for the late reply but I am away for the holidays and I don't have the PC with me.
I am a PhD from Pisa group. I am not part of DQM group, but I am working with the tracking group to develop a neural network based seeding for high pt jet tracking (with Andrea Rizzi) . For this purpose last year I developed some extra validation plots i.e. the tracking performances vs deltaR(track, jet), which are currently included in standard validation. 
This PR solve an issue generated from my validation plots.
If you want I will be happy to give to you more detail about me or about this validation task.

**Comment by fioriNTU** [comment]
@vberta , Hi Valerio, ok this is enough, please subscribe to this e-group cms-dqm-offline-developers-tracking so we will not forget about you

**Comment by fioriNTU** [comment]
please test

**Comment by fioriNTU** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Pull request merged**
