### PR TITLE
Fix for missing flagging of gain switch

### PR DESCRIPTION
**Pull request by argiro**
Same as #17212 for 80x

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@argiro 
Is the modified EcalUncalibRecHitWorkerWeights.cc used in any of existing standard workflows (pp, HI, cosmics; HLT)?
I think it is now, but wanted to double-check.

**Comment by argiro** [comment]
@slava77
no, it's not used in production at the moment, but it will be used for the slew rate fix patch.

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/17218	1f69ea9
- code changes are visually correct and is the same as in 90X https://github.com/cms-sw/cmssw/pull/17212 260e6fa  ; the EcalUncalibRecHitWorkerWeights is not used in tested workflows
- jenkins tests pass

**Comment by davidlange6** [comment]
+1

**Pull request merged**
