### PR TITLE
backport extended exception for geant4/vecgeom tracking

### PR DESCRIPTION
**Pull request by civanch**
#### PR description:
Backport extended handling of Geant4/VecGeom exceptions from the master in order to address #37373. Here only files are backported from #36717 and #37216 with modifications of code for exceptions. Geant4 trace of exceptions expected with the new Geant4 11.0 is not considered.

#### PR validation:
private

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by perrotta** [comment]
This PR backports a subset of #36717, and its fixes in #37216
@civanch could you please explain in the description what you are backporting here from #36717, and why you are not proposing to backport it all?

A comment about the previous decision of not backporting those two PRs in 12_2_X was written  in https://github.com/cms-sw/cmssw/pull/36780#issuecomment-1028348446

**Comment by mmusich** [comment]
@civanch is this supposed to fix https://github.com/cms-sw/cmssw/issues/37373 ?

**Comment by civanch** [comment]
I have tried to extend the description.

**Comment by civanch** [comment]
+1

**Comment by civanch** [comment]
urgent

**Comment by qliphy** [comment]
@civanch  In the description, the issue mentioned should be https://github.com/cms-sw/cmssw/issues/37373 instead of #37343

**Comment by qliphy** [comment]
+1

**Pull request merged**
