### PR TITLE
Fix clang compiler warning and replace boost::mpl::if_c with std::conditional

### PR DESCRIPTION
**Pull request by knoepfel**
Fixed some clang compiler warnings.
Also replaced several uses of `boost::mpl::if_c` with `std::conditional`.

### CODE REVIEW

**Comment by knoepfel** [comment]
Sorry, looks like a lot of white-space-only changes in this request.

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by knoepfel** [comment]
What's going on here?  The `std::conditional_t` typedef was introduced in C++14.  To use it `#include <type_traits>` must be included.  To my knowledge, the code was being compiled with the c++14 flag, and I have included the type-traits header.

**Comment by Dr15Jones** [comment]
Looking at the full build log, I believe this is a rootcling problem. Clearing out the overlapping output caused by multiple processes used in the compilation leaves
```
>> Building LCG reflex dict from header file src/DPGAnalysis/SiStripTools/src/classes.h
In file included from input_line_9:51:
In file included from /build/cmsbld/jenkins-workarea/workspace/ib-any-integration/CMSSW_9_0_X_2016-11-30-1100/src/DPGAnalysis/SiStripTools/interface/Multiplicities.h:6:
/build/cmsbld/jenkins-workarea/workspace/ib-any-integration/CMSSW_9_0_X_2016-11-30-1100/src/FWCore/Framework/interface/Event.h:373:10: error: no member named 'conditional_t' in namespace 'std'
    std::conditional_t<detail::has_postinsert<PROD>::value,
    ~~~~~^
/build/cmsbld/jenkins-workarea/workspace/ib-any-integration/CMSSW_9_0_X_2016-11-30-1100/src/FWCore/Framework/interface/Event.h:384:10: error: no member named 'conditional_t' in namespace 'std'
    std::conditional_t<detail::has_donotrecordparents<PROD>::value,
    ~~~~~^
/build/cmsbld/jenkins-workarea/workspace/ib-any-integration/CMSSW_9_0_X_2016-11-30-1100/src/FWCore/Framework/interface/Event.h:387:5: error: use of undeclared identifier 'parentage_recorder'
    parentage_recorder.do_it(putProducts(),
    ^
Error: rootcling: compilation failure (tmp/slc6_amd64_gcc530/src/DPGAnalysis/SiStripTools/src/DPGAnalysisSiStripTools/a/DPGAnalysisSiStripTools_xr73ad0eea2a_dictUmbrella.h)
gmake: *** [tmp/slc6_amd64_gcc530/src/DPGAnalysis/SiStripTools/src/DPGAnalysisSiStripTools/a/DPGAnalysisSiStripTools_xr.cc] Error 1
```
@smuzaffar do we have all the proper flags passed to cling?
@pcanal is this a known problem with ROOT 6.06?

**Comment by Dr15Jones** [comment]
The head in question
http://cmslxr.fnal.gov/source/DPGAnalysis/SiStripTools/interface/Multiplicities.h

violates CMS policy that DataFormats should be seperate from the algorithm which produces them. Instead, the classes in this header attempt to create themselves (and therefore are trying to access `edm::Event` which no data product should do).

**Comment by Dr15Jones** [comment]
The only file that actually uses `Multiplicities.h` is 
http://cmslxr.fnal.gov/source/DPGAnalysis/SiStripTools/plugins/ByMultiplicityEventFilter.cc

and the classes in question are used as helpers and NOT as data formats. Therefore the Wrapper declarations are unnecessary.

However, that class does want dictionaries generated since it uses those classes with the `StringCutObjectSelector` so they can do simple comparisons from the configuration!

**Comment by smuzaffar** [comment]
@Dr15Jones , only flags passed to genreflex (which internally uses cling) are various
-m .pcm
-I/path
-Dmacro 
there is no other flag which we pass to it.

**Comment by Dr15Jones** [comment]
@pcanal how do we tell rootcling to use C++14?

**Comment by pcanal** [comment]
rootcling *should* already automatically pick this up when its
    source code is compiled with C++14 ....
    
    On 12/1/16 7:46 AM, Chris Jones wrote:
    
    
      
      @pcanal how do we tell rootcling to
        use C++14?
      —
        You are receiving this because you were mentioned.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
          
          
        
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/cms-sw/cmssw","title":"cms-sw/cmssw","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/cms-sw/cmssw"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Dr15Jones in #16821: @pcanal how do we tell rootcling to use C++14?"}],"action":{"name":"View Pull Request","url":"https://github.com/cms-sw/cmssw/pull/16821#issuecomment-264176622"}}}

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
@smuzaffar are we sure we are passing the correct options to the compiler when we are building the file generated by genreflex?

**Comment by knoepfel** [comment]
The simplest fix was to replace the `#ifndef __GCCXML__` guards with `#ifndef __ROOTCLING__`.  This does not solve the design issue, but it does move things forward.

As an aside: I have run into a few cases (the `Multiplicities.h` header has some of these) where an attempt has been made to take advantage of move semantics in a c'tor.  For example, a set of c'tors for a class `A` may be defined like:

~~~~{cpp}
class A {
public:
  A(SomeType const& st) : st_{st} {}
  A(SomeType&& st) : st_{st} {}
private:
  SomeType st_;
};
~~~~

Since `A(SomeType&& st)` does not do an `std::move` on the r-value reference `st`, the copy c'tor of `SomeType` will be called.  In other words, no efficiency has been gained.  I will try to add the missing `std::move`s in future pull requests--or I will remove one of the c'tors if the class is used infrequently so as to avoid multiple points of maintenance.

**Comment by smuzaffar** [comment]
@Dr15Jones , yes we are passing the correct options. See the below which is taken from the IB build logs for this file
```
/build/cmsbuild/jenkins-workarea/workspace/build-any-ib/w/slc6_amd64_gcc530/external/gcc/5.3.0/bin/c++
-MMD
-MF
DPGAnalysisSiStripTools/a/DPGAnalysisSiStripTools_xr.d
-c
-I/build/cmsbuild/jenkins-workarea/workspace/build-any-ib/w/tmp/BUILDROOT/2a0843181a328cda7b8822d1ba72547e/opt/cmssw/slc6_amd64_gcc530/cms/cmssw/CMSSW_9_0_X_2016-12-01-1100
-DGNU_GCC
-D_GNU_SOURCE
-DCMSSW_GIT_HASH=CMSSW_9_0_X_2016-12-01-1100
-DPROJECT_NAME=CMSSW
-DPROJECT_VERSION=CMSSW_9_0_X_2016-12-01-1100
-DTBB_USE_GLIBCXX_VERSION=50300
-DBOOST_SPIRIT_THREADSAFE
-DPHOENIX_THREADSAFE
-I/build/cmsbuild/jenkins-workarea/workspace/build-any-ib/w/tmp/BUILDROOT/2a0843181a328cda7b8822d1ba72547e/opt/cmssw/slc6_amd64_gcc530/cms/cmssw/CMSSW_9_0_X_2016-12-01-1100/src
-I/build/cmsbuild/jenkins-workarea/workspace/build-any-ib/w/slc6_amd64_gcc530/lcg/root/6.06.08-oenich/include
-I/build/cmsbuild/jenkins-workarea/workspace/build-any-ib/w/slc6_amd64_gcc530/external/boost/1.57.0-ghmdbj/include
-I/build/cmsbuild/jenkins-workarea/workspace/build-any-ib/w/slc6_amd64_gcc530/external/pcre/8.37/include
-I/build/cmsbuild/jenkins-workarea/workspace/build-any-ib/w/slc6_amd64_gcc530/external/bz2lib/1.0.6/include
-I/build/cmsbuild/jenkins-workarea/workspace/build-any-ib/w/slc6_amd64_gcc530/external/clhep/2.3.1.1-ghmdbj/include
-I/build/cmsbuild/jenkins-workarea/workspace/build-any-ib/w/slc6_amd64_gcc530/external/gsl/2.2.1/include
-I/build/cmsbuild/jenkins-workarea/workspace/build-any-ib/w/slc6_amd64_gcc530/external/hepmc/2.06.07/include
-I/build/cmsbuild/jenkins-workarea/workspace/build-any-ib/w/slc6_amd64_gcc530/external/libuuid/2.22.2/include
-I/build/cmsbuild/jenkins-workarea/workspace/build-any-ib/w/slc6_amd64_gcc530/external/python/2.7.11-ghmdbj/include/python2.7
-I/build/cmsbuild/jenkins-workarea/workspace/build-any-ib/w/slc6_amd64_gcc530/external/sigcpp/2.6.2/include/sigc++-2.0
-I/build/cmsbuild/jenkins-workarea/workspace/build-any-ib/w/slc6_amd64_gcc530/external/tbb/2017_20161004oss/include
-I/build/cmsbuild/jenkins-workarea/workspace/build-any-ib/w/slc6_amd64_gcc530/cms/vdt/v0.3.2-ghmdbj/include
-I/build/cmsbuild/jenkins-workarea/workspace/build-any-ib/w/slc6_amd64_gcc530/external/xerces-c/3.1.3/include
-I/build/cmsbuild/jenkins-workarea/workspace/build-any-ib/w/slc6_amd64_gcc530/external/xz/5.2.1/include
-I/build/cmsbuild/jenkins-workarea/workspace/build-any-ib/w/slc6_amd64_gcc530/external/zlib/1.2.8/include
-I/build/cmsbuild/jenkins-workarea/workspace/build-any-ib/w/slc6_amd64_gcc530/external/md5/1.0.0/include
-I/build/cmsbuild/jenkins-workarea/workspace/build-any-ib/w/slc6_amd64_gcc530/external/tinyxml/2.5.3-ghmdbj/include
-DCMSSW_REFLEX_DICT
-pthread
-pipe
-Werror=main
-Werror=pointer-arith
-Werror=overlength-strings
-Wno-vla
-Werror=overflow
-std=c++14
-ftree-vectorize
-Wstrict-overflow
-Werror=array-bounds
-Werror=format-contains-nul
-Werror=type-limits
-fvisibility-inlines-hidden
-fno-math-errno
--param
vect-max-version-for-alias-checks=50
-Wa,--compress-debug-sections
-msse3
-felide-constructors
-fmessage-length=0
-Wall
-Wno-non-template-friend
-Wno-long-long
-Wreturn-type
-Wunused
-Wparentheses
-Wno-deprecated
-Werror=return-type
-Werror=missing-braces
-Werror=unused-value
-Werror=address
-Werror=format
-Werror=sign-compare
-Werror=write-strings
-Werror=delete-non-virtual-dtor
-Werror=maybe-uninitialized
-Werror=strict-aliasing
-Werror=narrowing
-Werror=uninitialized
-Werror=unused-but-set-variable
-Werror=reorder
-Werror=unused-variable
-Werror=conversion-null
-Werror=return-local-addr
-Werror=switch
-fdiagnostics-show-option
-Wno-unused-local-typedefs
-Wno-attributes
-Wno-psabi
-DBOOST_DISABLE_ASSERTS
-Wno-error=unused-variable
-Wno-error=unused-variable
-Wno-error=unused-variable
-fdebug-prefix-map=/build/cmsbuild/jenkins-workarea/workspace/build-any-ib/w=/opt/cmssw
-fdebug-prefix-map=/build/cmsbuild/jenkins-workarea/workspace/build-any-ib/w/tmp/BUILDROOT/2a0843181a328cda7b8822d1ba72547e/opt/cmssw=/opt/cmssw
-g
-Os
-Wno-unused-variable
-fPIC
DPGAnalysisSiStripTools/a/DPGAnalysisSiStripTools_xr.cc
-o
DPGAnalysisSiStripTools/a/DPGAnalysisSiStripTools_xr.o
```

**Comment by Dr15Jones** [comment]
With Philippe's help I found the problem. We are compiling root with `c++11` flag and not `c++14` flag
```
[chrjones@lxplus032 ~/CMSSW_9_0_X_2016-12-01-1100]$  root-config --cflags
-pthread -std=c++11 -Wno-deprecated-declarations -m64 -I/cvmfs/cms-ib.cern.ch/week1/slc6_amd64_gcc530/cms/cmssw/CMSSW_9_0_X_2016-12-01-1100/external/slc6_amd64_gcc530/bin/../../../../../../../slc6_amd64_gcc530/lcg/root/6.06.08-oenich/include
```
Therefore `rootcling` is applying `-std=c++11` and not `-std=c++14`. Since Kyle used a C++ 14 construct that uncovered the discrepency.

**Comment by Dr15Jones** [comment]
@smuzaffar @davidlange6 we need to rebuild ROOT using the `-std=c++14` compiler switch so that `rootcling` will parse the headers the same way we have `g++` parse them.

**Comment by smuzaffar** [comment]
@Dr15Jones , there is PR for this https://github.com/cms-sw/cmsdist/pull/2703 . I will integrate it for next IB if tests pass

**Comment by smuzaffar** [comment]
please test
IB should have root build with c++14

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
ROOT was rebuilt in the most recent IB to use C++14. This will be used in the next test.

**Comment by Dr15Jones** [comment]
@smuzaffar looks like the ROOT change broke stuff but we missed it in the IB since we didn't do a full rebuild of CMSSW after the change.

**Comment by Dr15Jones** [comment]
I took a look at the failing file, but can't see any reason for the missing class error since the file does include the header file which declares that class. In addition, no ROOT specific defines are in any of those headers. 
Maybe it was a transient file reading glitch?

**Comment by smuzaffar** [comment]
@Dr15Jones , CMSSW_9_0_X_2016-12-02-2300 was a full build with root updates.

**Comment by Dr15Jones** [comment]
+1

**Comment by Dr15Jones** [comment]
The unit test failure has nothing to do with this pull request. (The test failed because the file generated for the test could not be found, which probably means a race condition in the testing infrastructure.)

**Comment by davidlange6** [comment]
hi @knoepfel - could you edit the pull request title to be more reflective of changes made for the release notes. Thanks.

**Comment by knoepfel** [comment]
@davidlange6 done.

**Pull request merged**
