### PR TITLE
Reduce PCL disk space 81X

### PR DESCRIPTION
**Pull request by ghellwig**
Reduces size of binaries written to disk in the harvesting step of the SiPixelAli to 30% of it's original size.
Addresses issue reported in [Tier-0 Operations HN](https://hypernews.cern.ch/HyperNews/CMS/get/tier0-Ops/1435/1/1.html).

### CODE REVIEW

**Comment by ghellwig** [comment]
please test

**Comment by mmusich** [comment]
@ghellwig the error in `50202.0 step2` and in `25202.0 step3`

are not related to this PR:

```
----- Begin Fatal Exception 23-Jun-2016 19:42:51 CEST-----------------------
An exception of category 'Configuration' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing module: class=MixingModule label='mix'
Exception Message:
RootEmbeddedFileSequence no input files specified for secondary input source.
----- End Fatal Exception -------------------------------------------------
```

**Comment by ghellwig** [comment]
please test

**Comment by mmusich** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
