### PR TITLE
[124X backport] Add DY option to Embedding HepMC filter

### PR DESCRIPTION
**Pull request by IzaakWN**
### PR description
Backport of PR https://github.com/cms-sw/cmssw/pull/38829

### PR validation
See PR https://github.com/cms-sw/cmssw/pull/38829 and https://indico.cern.ch/event/1170879/#2-validation-of-exclusive-dy-t

### PR backporting
Backporting to `CMSSW_12_4_X`, for producing the Run-3 `DYJetsToTauTauToMuTauh_M-50` sample for TauPOG studies, and allow the H → WW analysis to use this updated filter.

### CODE REVIEW

**Comment by SiewYan** [comment]
please test

**Comment by Saptaparna** [comment]
Hi, do we expect some of the tests to fail?

**Comment by perrotta** [comment]
code-checks

**Comment by perrotta** [comment]
> Hi, do we expect some of the tests to fail?

The code checks failed when this PR was submitted to the wrong branch. It is not a showstopper here.

**Comment by perrotta** [comment]
backport of https://github.com/cms-sw/cmssw/pull/38829

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
(It also backports https://github.com/cms-sw/cmssw/pull/39090, which must be succesfully tested and merged in the master before this one)

**Comment by Saptaparna** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by perrotta** [comment]
+1
- Both https://github.com/cms-sw/cmssw/pull/38829 and https://github.com/cms-sw/cmssw/pull/39090 are now succesfully tested in master IBs

**Pull request merged**
