### PR TITLE
Migrate Egamma-Electools to use esConsumes

### PR DESCRIPTION
**Pull request by sroychow**
#### PR description:
Part of #31061. Migrates modules of ```EgammaAnalysis/ElectronTools``` to use esConsumes. 

#### PR validation:
Compiles and passes ```runTheMatrix.py -l limited -i all --ibeos```

#### if this PR is a backport please specify the original PR and why you need to backport that PR:
NA

### CODE REVIEW

**Comment by sroychow** [comment]
@cmsbuild please test

**Comment by qliphy** [comment]
please test

**Comment by qliphy** [comment]
+1

**Comment by qliphy** [comment]
merge

**Pull request merged**
