### PR TITLE
Reduce boost dependency in PhysicsTools/NanoAOD

### PR DESCRIPTION
**Pull request by camolezi**
#### PR description:
Changed boost::ptr_vector for std::vector<std::unique_ptr<>>
The code should have the same behavior.

#### PR validation:
Passed on basic runTheMatrix test.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

@vgvassilev @davidlange6

### CODE REVIEW

**Comment by gpetruc** [comment]
isn't this worse performance-wise?
here all pointers are owned by the owner of the vector, so there's no need of reference counting or carrying around a custom deleter. 
A plain `vector<Variable *>` could have been sufficient for all purposes except that it would have needed extra code in the destructor and the copy & move operators (and require a few more derefercing in the access), so I had used boost.
If boost is disfavoured, shouldn't be `vector<unique_ptr>`  the right thing instead, to avoid the added overheads?

**Comment by camolezi** [comment]
> isn't this worse performance-wise?
> here all pointers are owned by the owner of the vector, so there's no need of reference counting or carrying around a custom deleter.
> A plain `vector<Variable *>` could have been sufficient for all purposes except that it would have needed extra code in the destructor and the copy & move operators (and require a few more derefercing in the access), so I had used boost.
> If boost is disfavoured, shouldn't be `vector<unique_ptr>` the right thing instead, to avoid the added overheads?

Yeah, you're right. Probably a unique_ptr is better in this situation.

**Comment by silviodonato** [comment]
Any objections @peruzzim @santocch ?

**Comment by silviodonato** [comment]
merge
 @santocch @peruzzim

**Comment by santocch** [comment]
+1

**Pull request merged**
