### PR TITLE
HGCal Geometry layer clipping tool

### PR DESCRIPTION
**Pull request by Mourtz**
Depends on #25282

### CODE REVIEW

**Comment by alja** [comment]
+1

**Comment by fabiocos** [comment]
@Mourtz this PR is claimed to depend on #25282 that has been closed. Could you please clarify?

**Comment by Mourtz** [comment]
@fabiocos Sorry I used the wrong word there, it was including that PR not depending on it.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
