### PR TITLE
Fix infrequent deadlock in edm::ThreadHandoff

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

- Need to hold the lock until call to `wait` to avoid the possiblility of a deadlock.
- The deadlock has been showing up in the IBs.

#### PR validation:

Ran workflow 159.1 with 4 threads and everything ran fine.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
type bug

**Comment by Dr15Jones** [comment]
This fixes IB timeouts with the following tracebacks
```
Thread 5 (Thread 0x2af7dce00700 (LWP 28901) "cmsRun"):
#0  0x00002af7968b12fc in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x00002af7963f864c in __gthread_cond_wait (__mutex=<optimized out>, __cond=<optimized out>) at /build/muz/g9/boot/BUILD/cc8_amd64_gcc9/external/gcc/9.3.0/gcc-9.3.0/obj/x86_64-redhat-linux-gnu/libstdc++-v3/include/x86_64-redhat-linux-gnu/bits/gthr-default.h:865
#2  std::condition_variable::wait (this=<optimized out>, __lock=...) at ../../../../../libstdc++-v3/src/c++11/condition_variable.cc:53
#3  0x00002af7c795a69b in omt::ThreadHandoff::threadLoop(void*) () from /cvmfs/cms-ib.cern.ch/week1/cc8_amd64_gcc9/cms/cmssw/CMSSW_12_1_X_2021-08-22-2300/biglib/cc8_amd64_gcc9/pluginSimulation.so
#4  0x00002af7968ab14a in start_thread () from /lib64/libpthread.so.0
#5  0x00002af796bbff23 in clone () from /lib64/libc.so.6
[cut]
Thread 1 (Thread 0x2af79790ff00 (LWP 28639) "cmsRun"):
[cut]
#4  <signal handler called>
#5  0x00002af7968b12fa in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#6  0x00002af7963f864c in __gthread_cond_wait (__mutex=<optimized out>, __cond=<optimized out>) at /build/muz/g9/boot/BUILD/cc8_amd64_gcc9/external/gcc/9.3.0/gcc-9.3.0/obj/x86_64-redhat-linux-gnu/libstdc++-v3/include/x86_64-redhat-linux-gnu/bits/gthr-default.h:865
#7  std::condition_variable::wait (this=<optimized out>, __lock=...) at ../../../../../libstdc++-v3/src/c++11/condition_variable.cc:53
#8  0x00002af7c796444b in OscarMTProducer::OscarMTProducer(edm::ParameterSet const&, OscarMTMasterThread const*) () from /cvmfs/cms-ib.cern.ch/week1/cc8_amd64_gcc9/cms/cmssw/CMSSW_12_1_X_2021-08-22-2300/biglib/cc8_amd64_gcc9/pluginSimulation.so

```

**Comment by civanch** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
