### PR TITLE
Fixed compilation in Geant4 IBs

### PR DESCRIPTION
**Pull request by civanch**
#### PR description:
Fixed compilation problem in Geant4 IBs. Should not affect mainstream.

#### PR validation:
private

### CODE REVIEW

**Comment by civanch** [comment]
bug-fix

**Comment by iarspider** [comment]
test parameters:
- release CMSSW_12_6_G4VECGEOM_X/el8_amd64_gcc10

**Comment by iarspider** [comment]
please test

**Comment by smuzaffar** [comment]
please test for CMSSW_12_6_G4VECGEOM_X/el8_amd64_gcc10

**Comment by civanch** [comment]
please test for CMSSW_12_6_G4VECGEOM_X/el8_amd64_gcc10

**Comment by smuzaffar** [comment]
please test

lets start tests for normal IBs too

**Comment by smuzaffar** [comment]
please test for CMSSW_12_6_G4VECGEOM_X/el8_amd64_gcc10

**Comment by civanch** [comment]
These problems were in previous versions of G4VECGEOM.

**Comment by civanch** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
