### PR TITLE
Added protection for invalid GhostTrackStates (94X)

### PR DESCRIPTION
**Pull request by ferencek**
Backport of #21120

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
+1
- Bug fix identical to the one in #21120 , just merged in the master

**Comment by ferencek** [comment]
Would it make sense to also backport to 92X?

**Comment by perrotta** [comment]
Given that the original report of this issue  
(https://hypernews.cern.ch/HyperNews/CMS/get/physTools/3574.html) was  
referring to 92X, I would say yes...


Dinko Ferencek <notifications@github.com> ha scritto:

**Comment by davidlange6** [comment]
merge

**Pull request merged**
