### PR TITLE
PPS renaming alca reco producers - backport of PR#36702 to 12_2_X

### PR DESCRIPTION
**Pull request by grzanka**
#### PR description:

This is a backport of #36702 to 12_2_X

It is related to cms-AlCaDB/AlCaTools#53 

The changes are necessary for T0 replay with PPS. The suggestions for renaming appeared in the discussion of #36273
It is following https://github.com/cms-sw/cmssw/pull/36698

#### PR validation:

Tested with:
```
runTheMatrix.py -l 1041 --ibeos
runTheMatrix.py -l 1042 --ibeos
```

### CODE REVIEW

**Comment by srimanob** [comment]
test parameters:
- workflows = 1041,1042

**Comment by srimanob** [comment]
@cmsbuild please test

**Comment by tvami** [comment]
backport of #36702

**Comment by srimanob** [comment]
+Upgrade

Backport PR. PR test runs fine, the additional workflows with the change run fine.

**Comment by tvami** [comment]
+alca

**Comment by tvami** [comment]
Hi @kskovpen you signed the original PR for this, please consider signing the backport as well, thanks!

**Comment by kskovpen** [comment]
+1

**Comment by tvami** [comment]
Hi @perrotta @qliphy this is essentially fully signed. I guess we should wait a day to see how the IB goes with the master PR and merge this. We'll also request to cut a 12_2_0 so these PPS workflows can be tested. We can discuss the details on Tuesday's ORP

**Comment by qliphy** [comment]
> Hi @perrotta @qliphy this is essentially fully signed. I guess we should wait a day to see how the IB goes with the master PR and merge this. We'll also request to cut a 12_2_0 so these PPS workflows can be tested. We can discuss the details on Tuesday's ORP

@tvami This week's ORP will be cancelled due to ongoing CMSWeek.  However, we can merge this PR and build next 12_2_X this week if it is really urgently needed.

**Comment by qliphy** [comment]
merge
Master PR IB test looks good

**Comment by tvami** [comment]
>  build next 12_2_X this week if it is really urgently needed.

Yes that would be great! But we can wait for the geometry backports before cutting a new 12_2_X release.

**Pull request merged**
