### PR TITLE
Add PU id working points to MiniAOD 8_1_X

### PR DESCRIPTION
**Pull request by ahinzmann**
Add one user int containing 3 bits for loose, medium and tight working points of the PU jet ID to MiniAOD slimmedJets.

Could conflict with #13606. Code would be cleaner if this one is updated after #13606 is merged.

Made sure that
PhysicsTools/PatAlgos/test/patMiniAOD_standard_cfg.py 
adds the desired userInt and is accessible.

8_0_X version is #13641

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

@ahinzmann is the comment about interference with the 80X PRs valid here?
Please check and update the PR description.

**Comment by slava77** [comment]
@smuzaffar @degano 
please explain the comments in 
https://github.com/cms-sw/cmssw/pull/13642#issuecomment-193810291
``` Comparison not run due to Fireworks only changes  ```

**Comment by smuzaffar** [comment]
looks like a bug to me, I am checking

**Comment by smuzaffar** [comment]
For thisPR, Relvals and comparison were not run due to build errors. cms-bot is updated to post the correct message. Following are the reasons due to which cms-bot will skip running comparisons
- There are build errors
- short runTheMatrix was not requested
- PR only contains Fireworks related changes i.e. all the changes in PR belong to Fireworks directory.

**Comment by slava77** [comment]
@cmsbuild please test
new IB is out by now

**Comment by cvuosalo** [comment]
+1

For #13642 ac7411f6d482af4b45160d766c934526f7885bba

Adding an integer to patJets to hold jet PU ID working points. There should be no change in monitored quantities. #13641 is the 80X version of this PR, and it has already been approved by Reco.

Merging of this PR should be coordinated with the merging of #13606 because their modifications might collide.

The code change is satisfactory, and Jenkins tests against baseline CMSSW_8_1_X_2016-03-08-1100 show no significant differences, as expected. An exanded config was checked for correctness for #13641.

**Pull request merged**
