### PR TITLE
remove 2022 HLT menu from `CMSSW_13_X_Y` [`13_1_X`]

### PR DESCRIPTION
**Pull request by missirol**
backport of #41471

#### PR description:

From the description of #41471:
>This PR removes the 2022 HLT menu (frozen pp menu "V1.5" of 2022) from the `master` branch of CMSSW. This change will be backported down to the `13_0_X` release cycle.
>
>The alias `HLT:@relval2022` is updated to point to the `Fake2` HLT menu, i.e. the "fake" menu used in any wfs for conditions between 2016 and the year prior to current data-taking (in this case, 2022).
>
>This change has knock-on effects which, while not directly under HLT's responsability, are addressed in this PR.
>
> - Just moving to the "fake" HLT menu would break wf `11634.7`, because the MkFit customisation for HLT proved to be, once again, too fragile against HLT changes (see https://github.com/cms-sw/cmssw/pull/38816#issuecomment-1192289392 for context). The customisation is updated to avoid such issues now and in the future, and wf `12434.7` (which uses the 2023 HLT menu) is added to the RelVals tested in PRs and IBs. `12434.7` replaces `11634.7` in PR tests, and `11634.7` continues to run in IBs.
>
> - The DQM and Validation sequences of 2022 MC wfs are changed to cope with the "fake" HLT menu introduced in those wfs ("FakeHLT" DQM/Validation sequences). While implementing these changes, I _think_ I accidentally fixed several wfs that were missing some of their intended customisations, e.g. wfs `10824.8`, `10024.24`, `10034.19` and `10080.81`. This can be checked looking at the output of [1] and [2] with and without this PR.
>
>[1] `runTheMatrix.py -nel all -w standard,highstats,pileup,generator,extendedgen,production,ged,2017,2016,machine,premix,nano,2026`
>[2] `runTheMatrix.py -nel all -w upgrade`

This PR is a prerequisite for https://github.com/cms-sw/cmssw/pull/41530.

#### PR validation:

None beyond the tests done for #41471.

#### If this PR is a backport, please specify the original PR and why you need to backport that PR. If this PR will be backported, please specify to which release cycle the backport is meant for:

#41471

Removal of 2022 HLT menu from release cycles meant for 2023 data-taking, or beyond.

### CODE REVIEW

**Comment by missirol** [comment]
test parameters:
 - workflows = 11634.7,11634.601,10824.6,10824.8,10024.24,10034.19,10080.81
 - relvals_opt = -w upgrade

**Comment by missirol** [comment]
please test

**Comment by missirol** [comment]
+hlt

 - verbatim backport of #41471
 - differences in DQM outputs as expected, see https://github.com/cms-sw/cmssw/pull/41471#issuecomment-1529151224

**Comment by missirol** [comment]
@cms-sw/upgrade-l2 @cms-sw/reconstruction-l2 @cms-sw/pdmv-l2 

Could you please have review this backport ?

**Comment by kskovpen** [comment]
+pdmv

**Comment by srimanob** [comment]
+Upgrade

**Comment by missirol** [comment]
@cms-sw/reconstruction-l2

Could you please review this backport ?

**Comment by mandrenguyen** [comment]
+1

**Comment by rappoccio** [comment]
+1

**Pull request merged**
