### PR TITLE
PPS XML files fixes

### PR DESCRIPTION
**Pull request by wpcarvalho**
#### PR description:

This PR is intended to fix syntax errors found in PPS XML files.

#### PR validation:

Simple validation by building geometry with the fixed files and dumping pot and sensor positions. All as expected.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by cvuosalo** [comment]
@wpcarvalho These XML files need to be checked by processing them with DD4hep. Did you do that?

**Comment by civanch** [comment]
please test

let us test this PR indeed

**Comment by wpcarvalho** [comment]
> @wpcarvalho These XML files need to be checked by processing them with DD4hep. Did you do that?

I apologize for my late reply. I was cross checking before. 

There are several syntax errors. Some of files were processed with DD4hep and agree with DD:

Geometry/ForwardCommonData/data/totemt1.xml
Geometry/VeryForwardData/data/CTPPS_Pixel_2018/CTPPS_Pixel_Assembly_Box_Real_023.xml
Geometry/VeryForwardData/data/CTPPS_Pixel_2018/RP_147_Left_Station.xml
Geometry/VeryForwardData/data/CTPPS_Pixel_2018/RP_147_Right_Station.xml
Geometry/VeryForwardData/data/CTPPS_Timing_Horizontal_Pot.xml

Others were fixed by @ghugo83 due to repeated *mm unit:

Geometry/ForwardCommonData/data/Run2/totemt1.xml
Geometry/ForwardCommonData/data/dev/totemt1.xml
Geometry/VeryForwardData/data/CTPPS_2016/CTPPS_210_Left_Station.xml
Geometry/VeryForwardData/data/CTPPS_2016/CTPPS_210_Right_Station.xml
Geometry/VeryForwardData/data/CTPPS_2017/CTPPS_210_Left_Station.xml
Geometry/VeryForwardData/data/CTPPS_2017/CTPPS_210_Right_Station.xml
Geometry/VeryForwardData/data/CTPPS_2018/CTPPS_210_Left_Station.xml
Geometry/VeryForwardData/data/CTPPS_2018/CTPPS_210_Right_Station.xml
Geometry/VeryForwardData/data/RP_147_Left_Station.xml
Geometry/VeryForwardData/data/RP_147_Right_Station.xml

**Comment by wpcarvalho** [comment]
> > @wpcarvalho These XML files need to be checked by processing them with DD4hep. Did you do that?
> 
> I apologize for my late reply. I was cross checking before.
> 
> There are several syntax errors. Some of files were processed with DD4hep and agree with DD:
> 
> Geometry/ForwardCommonData/data/totemt1.xml
> Geometry/VeryForwardData/data/CTPPS_Pixel_2018/CTPPS_Pixel_Assembly_Box_Real_023.xml
> Geometry/VeryForwardData/data/CTPPS_Pixel_2018/RP_147_Left_Station.xml
> Geometry/VeryForwardData/data/CTPPS_Pixel_2018/RP_147_Right_Station.xml
> Geometry/VeryForwardData/data/CTPPS_Timing_Horizontal_Pot.xml
> 
> Others were fixed by @ghugo83 due to repeated *mm unit:
> 
> Geometry/ForwardCommonData/data/Run2/totemt1.xml
> Geometry/ForwardCommonData/data/dev/totemt1.xml
> Geometry/VeryForwardData/data/CTPPS_2016/CTPPS_210_Left_Station.xml
> Geometry/VeryForwardData/data/CTPPS_2016/CTPPS_210_Right_Station.xml
> Geometry/VeryForwardData/data/CTPPS_2017/CTPPS_210_Left_Station.xml
> Geometry/VeryForwardData/data/CTPPS_2017/CTPPS_210_Right_Station.xml
> Geometry/VeryForwardData/data/CTPPS_2018/CTPPS_210_Left_Station.xml
> Geometry/VeryForwardData/data/CTPPS_2018/CTPPS_210_Right_Station.xml
> Geometry/VeryForwardData/data/RP_147_Left_Station.xml
> Geometry/VeryForwardData/data/RP_147_Right_Station.xml

And still these ones to remove not allowed attribute 'eval="true"' from <RotationSection> block:

Geometry/VeryForwardData/data/CTPPS_2016/CTPPS_220_Left_Station.xml
Geometry/VeryForwardData/data/CTPPS_2016/CTPPS_220_Right_Station.xml
Geometry/VeryForwardData/data/CTPPS_2017/CTPPS_220_Left_Station.xml
Geometry/VeryForwardData/data/CTPPS_2017/CTPPS_220_Right_Station.xml
Geometry/VeryForwardData/data/CTPPS_2018/CTPPS_220_Left_Station.xml
Geometry/VeryForwardData/data/CTPPS_2018/CTPPS_220_Right_Station.xml

**Comment by wpcarvalho** [comment]
> > > @wpcarvalho These XML files need to be checked by processing them with DD4hep. Did you do that?
> > 
> > 
> > I apologize for my late reply. I was cross checking before.
> > There are several syntax errors. Some of files were processed with DD4hep and agree with DD:
> > Geometry/ForwardCommonData/data/totemt1.xml
> > Geometry/VeryForwardData/data/CTPPS_Pixel_2018/CTPPS_Pixel_Assembly_Box_Real_023.xml
> > Geometry/VeryForwardData/data/CTPPS_Pixel_2018/RP_147_Left_Station.xml
> > Geometry/VeryForwardData/data/CTPPS_Pixel_2018/RP_147_Right_Station.xml
> > Geometry/VeryForwardData/data/CTPPS_Timing_Horizontal_Pot.xml
> > Others were fixed by @ghugo83 due to repeated *mm unit:
> > Geometry/ForwardCommonData/data/Run2/totemt1.xml
> > Geometry/ForwardCommonData/data/dev/totemt1.xml
> > Geometry/VeryForwardData/data/CTPPS_2016/CTPPS_210_Left_Station.xml
> > Geometry/VeryForwardData/data/CTPPS_2016/CTPPS_210_Right_Station.xml
> > Geometry/VeryForwardData/data/CTPPS_2017/CTPPS_210_Left_Station.xml
> > Geometry/VeryForwardData/data/CTPPS_2017/CTPPS_210_Right_Station.xml
> > Geometry/VeryForwardData/data/CTPPS_2018/CTPPS_210_Left_Station.xml
> > Geometry/VeryForwardData/data/CTPPS_2018/CTPPS_210_Right_Station.xml
> > Geometry/VeryForwardData/data/RP_147_Left_Station.xml
> > Geometry/VeryForwardData/data/RP_147_Right_Station.xml
> 
> And still these ones to remove not allowed attribute 'eval="true"' from block:
> 
> Geometry/VeryForwardData/data/CTPPS_2016/CTPPS_220_Left_Station.xml
> Geometry/VeryForwardData/data/CTPPS_2016/CTPPS_220_Right_Station.xml
> Geometry/VeryForwardData/data/CTPPS_2017/CTPPS_220_Left_Station.xml
> Geometry/VeryForwardData/data/CTPPS_2017/CTPPS_220_Right_Station.xml
> Geometry/VeryForwardData/data/CTPPS_2018/CTPPS_220_Left_Station.xml
> Geometry/VeryForwardData/data/CTPPS_2018/CTPPS_220_Right_Station.xml

... from block `<RotationSection>`

**Comment by cvuosalo** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
