### PR TITLE
[13_0_X] Fixing the missing Tau plots within the L1T offline DQM 

### PR DESCRIPTION
**Pull request by vukasinmilosevic**
#### PR description:
Updating the L1T Tau offline DQM modules to take into account changes in inputs that were causing the plots to be empty:

* This setup was facing the same issue as previously reported for the L1T Muon offline DQM - some HLT modules are listed behind hltBoolEnd, breaking the currently implemented logic for matching to HLT objects (more details in PR #39691)
* Offline Tau experts have removed the anti-electron discriminators that are used as input to the Tau DQM code. Implemented a quick fix so that they are simply removed from the offline tau requirements if they do not exist.
Added more details to warning messages regarding the non-existence of tau discriminators.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport for #41170. Needed for deployment to P5 and to be used for the upcoming data taking period.

### CODE REVIEW

**Comment by aloeliger** [comment]
Backport of #41170

**Comment by aloeliger** [comment]
please test

**Comment by aloeliger** [comment]
+l1

**Comment by vukasinmilosevic** [comment]
ping @emanueleusai @rvenditti

**Comment by emanueleusai** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
