### PR TITLE
Remove hardcoded InputTag in PATPhotonProducer

### PR DESCRIPTION
**Pull request by matteosan1**
Same as PR 7946 but for 75X.
The hardcoded inputtag were preventing the electronVeto in miniAOD to work properly. Different superClusterRefs for (slimmedPhotons and gedGsfElectrons) were indeed compared returning identically false.
Changed accordingly the configuration to produce miniAOD.

### CODE REVIEW

**Comment by matteosan1** [comment]
Hi all,
I ran runTheMatrix and I found no issues. Can you tell me how can I run 
the failing test below ?

On 25.02.2015 17:36, cmsbuild wrote:
>
> -1
>
> Tested at: 50f0783 
> <https://github.com/cms-sw/cmssw/commit/50f078310dfa58bf5cb6ff24a52205f583287ffd>
> I ran the usual tests and I found errors in the following unit tests:
>
> ---> test runtestPhysicsToolsPatAlgos had ERRORS
>
> you can see the results of the tests here:
> https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-7947/2917/summary.html 
>
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/cms-sw/cmssw/pull/7947#issuecomment-75994528>.
>

-- 
Matteo Sani
University of California, San Diego
+41227671577

**Comment by nclopezo** [comment]
Hi Mateo,

you can do: 
<pre>
 scram b  runtests
</pre>

**Comment by civanch** [comment]
+1
@matteosan1 , you somehow picked up already merged PR #7936; because of that this PR become simulation dependent. It seems that there is no SIM but always better to rebase.

**Comment by deguio** [comment]
+1

**Comment by Dr15Jones** [comment]
-1
This looks like it needs to be rebased since it picked up static analyzer changes

**Comment by ktf** [comment]
Any news on this?

**Comment by matteosan1** [comment]
Hi,
I have rebased and updated this area this morning...

On 3/9/15 16:54, Giulio Eulisse wrote:
>
> Any news on this?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/cms-sw/cmssw/pull/7947#issuecomment-77880922>.
>

+++++++++++
Matteo Sani
University of California, San Diego, US.
Tel: +41227671577
CERN Office: 40-3-A02

**Comment by lveldere** [comment]
I guess the rebase failed...
e.g. there are many unrelated FastSim changes.

**Comment by matteosan1** [comment]
Hi,
I haven't noticed any message after having done it, but I can do it again.

On 3/10/15 10:40, lveldere wrote:
>
> I guess the rebase failed...
> e.g. there are many unrelated FastSim changes.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/cms-sw/cmssw/pull/7947#issuecomment-78021784>.
>

+++++++++++
Matteo Sani
University of California, San Diego, US.
Tel: +41227671577
CERN Office: 40-3-A02

**Comment by matteosan1** [comment]
I have tried again and this is the output of git cms-merge-topic with 
latest nightly of 75X:

You are on branch from-CMSSW_7_5_X_2015-03-10-0200
 From .
  * [new ref]                    -> merge-attempt
 From https://github.com/cms-sw/cmssw
  * [new ref]         refs/pull/7947/head -> cms-sw/refs/pull/7947/head
Switched to branch 'merge-attempt'
Merge made by the 'recursive' strategy.
  PhysicsTools/PatAlgos/plugins/PATPhotonProducer.cc | 5 +++--
  PhysicsTools/PatAlgos/python/producersLayer1/photonProducer_cfi.py | 2 +-
  PhysicsTools/PatAlgos/python/slimming/miniAOD_tools.py | 1 +
  3 files changed, 5 insertions(+), 3 deletions(-)
Switched to branch 'from-CMSSW_7_5_X_2015-03-10-0200'
 >> Checking PhysicsTools/PatAlgos CMSSW_7_5_X_2015-03-10-0200
    x PhysicsTools/PatAlgos/plugins/PATPhotonProducer.cc
    x PhysicsTools/PatAlgos/python/producersLayer1/photonProducer_cfi.py
    x PhysicsTools/PatAlgos/python/slimming/miniAOD_tools.py
Checking out these packages: 0

It seems ok to me.
If you think so I can push it to my area again, if not I am open to any 
suggestion.


On 10.03.2015 10:40, lveldere wrote:
>
> I guess the rebase failed...
> e.g. there are many unrelated FastSim changes.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/cms-sw/cmssw/pull/7947#issuecomment-78021784>.
>

-- 
Matteo Sani
University of California, San Diego
+41227671577

**Comment by ferencek** [comment]
@ktf It is my impression that encouraging the use of `git cms-merge-topic` at http://cms-sw.github.io/tutorial-forward-port.html leads to a lot of PRs like this one where completely unrelated commits start showing up.  `git cms-merge-topic` is simply not a proper way to rebase and I would strongly discourage its use when forward and back porting any code change. The best and cleanest way is to use `git rebase`, `git rebase --onto`, and `git cherry-pick`, depending on a specific situation.

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/7947	e105c8c
merged manually in CMSSW_7_5_X_2015-03-11-0200 /test area test7947/

```
 PhysicsTools/PatAlgos/plugins/PATPhotonProducer.cc                 | 5 +++--
 PhysicsTools/PatAlgos/python/producersLayer1/photonProducer_cfi.py | 2 +-
 PhysicsTools/PatAlgos/python/slimming/miniAOD_tools.py             | 1 +
 3 files changed, 5 insertions(+), 3 deletions(-)
```

these do not affect objects produced in the reconstruction step.
according to jenkins, the miniAOD steps run OK.

**Comment by Dr15Jones** [comment]
please rebase to avoid having all of us have to sign the pull request.

**Comment by deguio** [comment]
+1

**Comment by monttj** [comment]
+1

**Comment by davidlange6** [comment]
please rebase this PR @matteosan1

**Comment by matteosan1** [comment]
I have managed to remove extra things. Should be ok now.

**Comment by monttj** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
