### PR TITLE
Add missing newlines in HLTrigger modules

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Add missing newlines at the end of the files under
```
HLTrigger/Configuration
HLTrigger/HLTanalyzers
HLTriggerOffline/SUSYBSM
```
.

#### PR validation:

None.

### CODE REVIEW

**Comment by fwyzard** [comment]
please test

**Comment by mmusich** [comment]
+hlt 
   * technical, no changes expected.

**Comment by tjavaid** [comment]
+1

**Comment by rappoccio** [comment]
+1

**Pull request merged**
