### PR TITLE
Revert "[80X] Temporary fix for multi-IOV input in MillePede"

### PR DESCRIPTION
**Pull request by davidlange6**
Reverts cms-sw/cmssw#16136 as it is causing compilation problems for gcc493.

### CODE REVIEW

**Comment by mmusich** [comment]
@davidlange6 for my own education, where do I find the compilation logs pointing to issues with this PR? 
I've tried here: https://cmssdt.cern.ch/SDT/cgi-bin/showBuildLogs.py/slc6_amd64_gcc493/www/mon/8.0-mon-23/CMSSW_8_0_X_2016-10-24-2300 but I cannot find it

**Comment by ghellwig** [comment]
@mmusich You can find it in the first row of the table which points to this log:
https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc6_amd64_gcc493/CMSSW_8_0_X_2016-10-24-2300/Alignment/MillePedeAlignmentAlgorithm

@davidlange6 why has this not been spotted earlier? I would expect something like this to be covered by the integration tests, but this might be too naive...

**Comment by smuzaffar** [comment]
@ghellwig , integration tests are only run for production arch which is slc6_amd64_gcc530 for 80X release cycle. 
These errors only exist for gcc493 arch.

**Comment by ghellwig** [comment]
btw. why is a non-production architecture a reason to revert a critical fix?

**Comment by ghellwig** [comment]
@smuzaffar thanks for the clarification

**Comment by davidlange6** [comment]
not sure what you see at
https://cmssdt.cern.ch/SDT/cgi-bin/showBuildLogs.py/slc6_amd64_gcc493/www/mon/8.0-mon-23/CMSSW_8_0_X_2016-10-24-2300

but I see

[cid:1BCCF531-C4DB-4976-B0C6-5649B3387890@cern.ch]

On Oct 25, 2016, at 1:15 PM, Marco Musich <notifications@github.com> wrote:

@davidlange6 for my own education, where do I find the compilation logs pointing to issues with this PR?
I've tried here: https://cmssdt.cern.ch/SDT/cgi-bin/showBuildLogs.py/slc6_amd64_gcc493/www/mon/8.0-mon-23/CMSSW_8_0_X_2016-10-24-2300 but I cannot find it

**Comment by mmusich** [comment]
> not sure what you see at https://cmssdt.cern.ch/SDT/cgi-bin/showBuildLogs.py/slc6_amd64_gcc493/www/mon/8.0-mon-23/CMSSW_8_0_X_2016-10-24-2300 but I see [cid:1BCCF531-C4DB-4976-B0C6-5649B3387890@cern.ch]

@davidlange6 

not sure in turn to understand what you mean here, but @ghellwig already answered here: https://github.com/cms-sw/cmssw/pull/16340#issuecomment-256013321, thanks!

**Pull request merged**
