### PR TITLE
update of `hltIntegrationTests` and path of Run-3 Data file for TSG tests [`12_3_X`]

### PR DESCRIPTION
**Pull request by missirol**
backport of #37283

#### PR description:

Exact backport of #37283. See the original PR for a complete description. This PR includes

 - an update of the `hltIntegrationTests` script, mainly to support Dataset Paths in the HLT menus;

 - a fix to the path of the EDM file used for TSG tests on Run-3 Data; this fixes the current issue with the "HLT-Validation" tests in IBs.

#### PR validation:

Relies on the tests done for the original PR.

#### If this PR is a backport, please specify the original PR and why you need to backport that PR:

#37283

The backport is needed to support new features (e.g. Dataset Paths) in the upcoming HLT menu for 12_3_X, plus fixing a problem with file access in the "HLT-Validation" tests of the IBs.

### CODE REVIEW

**Comment by missirol** [comment]
type bugfix

Because of the EDM-file fix for the "HLT-Validation" tests running in IBs.

**Comment by missirol** [comment]
please test

**Comment by missirol** [comment]
please test

Propagated the update of the EDM file-path to the `addOnTests`.

**Comment by missirol** [comment]
+hlt

**Comment by perrotta** [comment]
+1

**Comment by perrotta** [comment]
@missirol HLT tests are failing in the IB also after the merging of this PR, see CMSSW_12_3_X_2022-03-23-2300
I did not look at the details of such a failure: is it something that should have been fixed by this PR?

**Comment by Martin-Grunewald** [comment]
This is unexpected - only the PRef MC integration test fails, all other integration tests are ok - weird!

**Comment by Martin-Grunewald** [comment]
A secon run also does not give any error, so for now I just wait for the next IB to see whether it was a glitch.

**Comment by missirol** [comment]
Sorry for the late reply.

It does look like a glitch. The same HLT tests in the next IB (`12_3_X_2022-03-24-1100`) came back clean, see [here](https://cmssdt.cern.ch/SDT/jenkins-artifacts/HLT-Validation/CMSSW_12_3_X_2022-03-24-1100/slc7_amd64_gcc10/runIB.log).

Maybe related (maybe not), the 12_4_X IB from last night (`12_4_X_2022-03-23-2300`) also had a very strange failure in the HLT tests, but a completely different one, see [here](https://cmssdt.cern.ch/SDT/jenkins-artifacts/HLT-Validation/CMSSW_12_4_X_2022-03-23-2300/slc7_amd64_gcc10/HLT_Integration_GRun_MC_HLT_Photon75_R9Id90_HE10_IsoM_EBOnly_CaloMJJ300_PFJetsMJJ400DEta3_v5.log).

---

Copying the error messages here for reference, as the links will eventually vanish.

[1]

https://cmssdt.cern.ch/SDT/jenkins-artifacts/HLT-Validation/CMSSW_12_3_X_2022-03-23-2300/slc7_amd64_gcc10/HLT_Integration_PRef_MC_hlt.log
```
----- Begin Fatal Exception 24-Mar-2022 05:58:27 UTC-----------------------
An exception of category 'ConfigFileReadError' occurred while
   [0] Processing the python configuration file named hlt.py
Exception Message:
 unknown python problem occurred.
NameError: name 'cms' is not defined

At:
  hlt.py(10): <module>

----- End Fatal Exception -------------------------------------------------
```

https://cmssdt.cern.ch/SDT/jenkins-artifacts/HLT-Validation/CMSSW_12_3_X_2022-03-23-2300/slc7_amd64_gcc10/HLT_Integration_PRef_MC.log
```
stty: standard input: Inappropriate ioctl for device
Will run 35 HLT paths over 100 events, with 4 jobs in parallel
Extracting full menu dump
HLT menu: hltGetConfiguration /dev/CMSSW_12_3_0/PRef/V52 --full --offline --mc --input file:../RelVal_Raw_PRef_MC.root --unprescale --process TEST20220324055823 --max-events 100 --globaltag=auto:run3_mc_PRef --type=PRef
Traceback (most recent call last):
  File "/pool/condor/dir_18518/jenkins/workspace/ib-run-HLT/CMSSW_12_3_X_2022-03-23-2300/bin/slc7_amd64_gcc10/hltCheckPrescaleModules", line 25, in <module>
    exec(open(name).read(), globals(), menu.__dict__)
  File "<string>", line 10, in <module>
NameError: name 'cms' is not defined
Traceback (most recent call last):
  File "/cvmfs/cms-ib.cern.ch/nweek-02725/slc7_amd64_gcc10/cms/cmssw/CMSSW_12_3_X_2022-03-20-0000/bin/slc7_amd64_gcc10/edmConfigDump", line 25, in <module>
    loader.exec_module(mod)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "hlt.py", line 10, in <module>
    process.source = cms.Source( "PoolSource",
NameError: name 'cms' is not defined
```

[2]

https://cmssdt.cern.ch/SDT/jenkins-artifacts/HLT-Validation/CMSSW_12_4_X_2022-03-23-2300/slc7_amd64_gcc10/HLT_Integration_GRun_MC_HLT_Photon75_R9Id90_HE10_IsoM_EBOnly_CaloMJJ300_PFJetsMJJ400DEta3_v5.log
```
%MSG-i ThreadStreamSetup:  (NoModuleName) 24-Mar-2022 11:49:31 UTC pre-events
setting # threads 4
setting # streams 4
%MSG
In file included from input_line_2:1:
/cvmfs/cms-ib.cern.ch/nweek-02725/slc7_amd64_gcc10/lcg/root/6.24.07-1af4b6b72252977b8fe2fde94ca5d475/etc/cling/Interpreter/RuntimeUniverse.h:53:11: error: redefinition of 'InterpreterGeneratedCodeDiagnosticsMaybeIncorrect'
      int InterpreterGeneratedCodeDiagnosticsMaybeIncorrect;
          ^
/cvmfs/cms-ib.cern.ch/nweek-02725/slc7_amd64_gcc10/lcg/root/6.24.07-1af4b6b72252977b8fe2fde94ca5d475/etc//cling/Interpreter/RuntimeUniverse.h:53:11: note: previous definition is here
      int InterpreterGeneratedCodeDiagnosticsMaybeIncorrect;
          ^
Replaced symbol atexit cannot be found in JIT!
Replaced symbol at_quick_exit cannot be found in JIT!
IncrementalExecutor::executeFunction: symbol '_ZN5cling7runtime6gClingE' unresolved while linking [cling interface function]!
You are probably missing the definition of cling::runtime::gCling
Maybe you need to load the corresponding shared library?

[..]

24-Mar-2022 11:58:44 UTC  Closed file file:../RelVal_Raw_GRun_MC.root
----- Begin Fatal Exception 24-Mar-2022 11:58:44 UTC-----------------------
An exception of category 'FatalRootError' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing module: class=EgammaHLTClusterShapeProducer label='hltEgammaClusterShape'
   [2] While initializing meta data for branch: recoRecoEcalCandidatesToValuefloatAssociation_hltEgammaClusterShape__TEST20220324073045.
   Additional Info:
      [a] Fatal Root Error: @SUB=TInterpreter::AutoParse
Error parsing payload code for class reco::RecoEcalCandidate with content:
```

**Pull request merged**
