### PR TITLE
bsunanda:Run2-hcx53 Utilize a test numbering scheme for HGCal in SIM step

### PR DESCRIPTION
**Pull request by bsunanda**
This is step 1 to introduce simulation of hexagonal HGCal cells

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
This unit test failure is not due to this PR - it is there in the IB. There is a PR when integrated will cure this unit test failure

**Comment by civanch** [comment]
@bsunanda , in SimG4CMS/Calo/src/HGCNumberingScheme.cc
 std::cout is left at run time.

**Comment by bsunanda** [comment]
@civanch It was for verbosity protected. Now it is within ifdef. I just pushed a new version

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
please test

**Comment by bsunanda** [comment]
One unit test will fail till PR 12438 is integrated
________________________________

**Comment by bsunanda** [comment]
@lgray Please try to follow this up. The unit test failure is not due to this PR and it needs #12438 to be integrated

**Comment by smuzaffar** [comment]
ignore comment: testing cms-bot

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@davidlange6 The unit test failure is not due to this. It was there in the IB and there is a fix in PR 12438. Please merge the PR12438. All developments for HGCAL are now stuck

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
@bsunanda looks like this PR has merge conflicts. Could you update it? Thanks

**Comment by bsunanda** [comment]
@davidlange6 I cross checked with the last available IB which is December 6 11:00 hr and there is no conflict. I am waiting for the 23:00 hr IB which is not available yet.

**Comment by bsunanda** [comment]
@davidlange6 I also checked against CMSSW_8_0_X_2015-12-06-2300. It integrates without any merge conflict. I am puzzled where this issue can come from.

**Comment by bsunanda** [comment]
I don't see any conflict with the 2 latest IB's
________________________________

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@davidlange6 Please try to accept this. I do not know how to avoid all the history from git

**Comment by civanch** [comment]
@bsunanda , I afraid it is not possible to merge. I personally do not understand this but what you need is to go to area with your PR and call rebase. After that your PR should return to normal.  If you fail than create the same new PR with the same code modification.

**Comment by slava77** [comment]
-1
I agree with @civanch 
It looks like the updates here are done by going to a new IB and then merge-topic, which makes all this mess in the history/commits on the web.

**Comment by bsunanda** [comment]
Yes it was done with a new IB and merge-topic. I am not sure how else I 
can resolve the merge conflicts. The ol IB where it was built was gone.

**Comment by bsunanda** [comment]
This PR is closed a new PR i(12703) s created which doesthe same job

**Pull request closed without merging**
