### PR TITLE
update on L2 muon seeding

### PR DESCRIPTION
**Pull request by khaosmos93**
Backport of #22330
TSG developments for the 2018 data taking are done in 100X

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by perrotta** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by perrotta** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by Martin-Grunewald** [comment]
@perrotta 
please also sign the backport

**Comment by perrotta** [comment]
+1
- Identical to #22330 in the master

**Comment by fabiocos** [comment]
+1

**Pull request merged**
