### PR TITLE
TICLv5: do not use trajectories to compute the track path length

### PR DESCRIPTION
**Pull request by AuroraPerego**
#### PR description:

This removes from the `TICLCandidateProducer` the trajectories used to compute the path length of the tracks.
Since the trajectories are not saved in the event, using them would prevent us from doing rereco from step3.

#### PR validation:

Tested on wf `29688.203`, any `.203` wf is fine.

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by AuroraPerego** [comment]
To test these changes wfs `.203`, like `29688.203` and `29888.203`, should be used. They need the `workflow_opts= -w upgrade` option.

**Comment by jfernan2** [comment]
workflow_opts= -w upgrade

**Comment by jfernan2** [comment]
please test 29688.203, 29888.203

**Comment by AuroraPerego** [comment]
@waredjeb FYI

**Comment by felicepantaleo** [comment]
test parameters:
- workflow_opts= -w upgrade
- workflow = 29888.203,29688.203

**Comment by felicepantaleo** [comment]
@cmsbuild please test

**Comment by mandrenguyen** [comment]
+1 
Changes look to be consistent with the statement:  

> Since the method used to compute the path length is slightly different and the average between MTD and HGCAL times has been set to `true` by default, I think small changes in the candidates time are ok.

Duplicate dictionary warning is not related to this PR.

**Comment by felicepantaleo** [comment]
@cmsbuild please test

**Comment by AuroraPerego** [comment]
The differences in DD4hep wfs do not seem related to this PR.

**Comment by mandrenguyen** [comment]
+1 
resign

**Comment by srimanob** [comment]
+Upgrade

**Comment by waredjeb** [comment]
Hi! @antoniovilela it would be nice if this would be merged before pre5 is built!
Thank you!

**Comment by rappoccio** [comment]
+1

**Pull request merged**
