### PR TITLE
Replace Geometry_cff with GeometryDB_cff in RecoBTag/RecoBTau

### PR DESCRIPTION
**Pull request by jeongeun**
**PR description:**
Review on the Reco part of https://github.com/cms-sw/cmssw/issues/31113

`process.load("Configuration.StandardSequences.Geometry_cff")`
 was outdated https://github.com/cms-sw/cmssw/pull/8810 
It should be replaced with
`process.load("Configuration.StandardSequences.GeometryDB_cff")`

In this PR, RecoBTag (RecoBTau) configuration files 1 file (2 files) are fixed.
```
modified:   RecoBTag/SoftLepton/test/testMuonAssociator.py
```
```
modified:   RecoBTau/JetTagComputer/test/testGenericMVAJetTagComputer_cfg.py
modified:   RecoBTau/JetTagComputer/test/testJetTagProducer_cfg.py
```

#### PR validation:
Tested in CMSSW_12_5_X, the basic test all passed in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by clacaputo** [comment]
@cmsbuild please test

**Comment by clacaputo** [comment]
Dear @cms-sw/tau-pog-l2 , it seems to me the config files fixed by this PR aren't updated since a long time (some of them form 2013).
Do you know if we still need it, maybe used in some unit-test, or we can remove them? Thanks

**Comment by alebihan** [comment]
Hi, this package is not used by the tau-POG (anymore ?), contains "tau" for historical reasons. BTV should probably confirm what should be done.

**Comment by clacaputo** [comment]
> Hi, this package is not used by the tau-POG (anymore ?), contains "tau" for historical reasons. BTV should probably confirm what should be done.

@cms-sw/btv-pog-l2 could you please confirm whether these test files are still needed?

**Comment by clacaputo** [comment]
> @cms-sw/btv-pog-l2 could you please confirm whether these test files are still needed?

a kind ping to @cms-sw/btv-pog-l2

**Comment by johnalison** [comment]
@emilbols, @demuller, @andrzejnovak, @AlexDeMoor can you comment on the tests from the BTV side ?

**Comment by jpata** [comment]
kind ping BTV folks @emilbols, @demuller, @andrzejnovak, @AlexDeMoor  @cms-sw/btv-pog-l2

**Comment by AlexDeMoor** [comment]
After reviewing this code, it appears to be old code unrelated to what we do or use now. We no longer use them and agree with their removal.

**Comment by clacaputo** [comment]
> After reviewing this code, it appears to be old code unrelated to what we do or use now. We no longer use them and agree with their removal.

Hi @AlexDeMoor , thanks for the update. @jeongeun , could you please remove the files?

**Comment by clacaputo** [comment]
A kindly ping to @jeongeun

**Comment by clacaputo** [comment]
@cmsbuild please test

**Comment by clacaputo** [comment]
+reconstruction

- removing outdated files

**Pull request merged**
