### PR TITLE
Fix for AlCaSiStripCalMinBias as discussed on PR #23498

### PR DESCRIPTION
**Pull request by jfernan2**

### CODE REVIEW

**Comment by jfernan2** [comment]
Tries to fix: #23498 
Tk-DQM crew please check:
@boudoul @fioriNTU @dimattia 
FYI:
@lpernie @arunhep @fabiocos @franzoni @mmusich

**Comment by jfernan2** [comment]
please test

**Comment by mmusich** [comment]
hi @jfernan2, thanks for this, it would be interesting to get this tested together with #23498. 
Woudl it be possible to abort the test and test them together?
Thanks!

**Comment by jfernan2** [comment]
please abort

**Comment by jfernan2** [comment]
please test with #23498

**Comment by jfernan2** [comment]
please test with #23498
it seems unrelated...

**Comment by lpernie** [comment]
@jfernan2 could you sign also this?

**Comment by jfernan2** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
