### PR TITLE
Fix our tests for the new frozen menus, and move to the 50ns table with correct prescales

### PR DESCRIPTION
**Pull request by perrotta**
Fix cmsDriver.csh for the new frozen menus, and move to the 50ns table with correct prescales

This Pull Request does nothing, in fact: it simply adds a missing internat TSG test for the new frozen tables, and has the correct version number for the 50ns tables (HLT prescales were actually modified in those tables, but those values are not dumped in CMSSW: therefore the corresponding files in the release only differ for the version number of the HLT table)

### CODE REVIEW

**Comment by perrotta** [comment]
+1

**Comment by perrotta** [comment]
please test

**Comment by Martin-Grunewald** [comment]
Hi @perrotta 
Please also add the new frozen dumps in https://github.com/cms-sw/cmssw/blob/CMSSW_7_5_X/Configuration/HLT/python/autoCondHLT.py

**Comment by perrotta** [comment]
hold

**Comment by Martin-Grunewald** [comment]
ie, the corresponding symbolic GT definitions...

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by perrotta** [comment]
+1

**Comment by perrotta** [comment]
Rebased, to get rid of unneeded signatures

**Comment by perrotta** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
