### PR TITLE
[13_1_X] Revert BeamSpot fallback logic

### PR DESCRIPTION
**Pull request by francescobrivio**
#### PR description:
Verbatim backport of #42284
This PR reverts the online BeamSpot fallback logic to actually fall back to the DB, ie. to consume the last BeamSpot produced by PCL.

#### PR validation:
See master PR for validation

#### Backport:
Backport of #42284

### CODE REVIEW

**Comment by francescobrivio** [comment]
backport of #42284

**Comment by francescobrivio** [comment]
test parameters:
-  addpkg = DQM/Integration

**Comment by francescobrivio** [comment]
@cmsbuild please test

**Comment by emanueleusai** [comment]
testing 13_0 backport at p5

**Comment by emanueleusai** [comment]
+1

- p5 tests completed successfully and results are as expected

**Comment by francescobrivio** [comment]
+db

 - diffs in `12434.7` are known from https://github.com/cms-sw/cmssw/issues/39803

**Comment by saumyaphor4252** [comment]
+alca

**Comment by mandrenguyen** [comment]
+1

**Comment by rappoccio** [comment]
+1

**Pull request merged**
