### PR TITLE
FirstVersionsofDiTauHLTPaths_forPhase2 [13_1_X]

### PR DESCRIPTION
**Pull request by hsert**
First versions of ditau HLT paths for Phase2 with charged isolation and DeepTau Isolation (using Run2 training) are added.

Detailed description of PR is given in the original PR:  https://github.com/cms-sw/cmssw/pull/42562 

We would like that PR will be backported to CMSSW_13_1_X release, since the studies for Phase 2 HLT is ongoing in that release.

I used CMSSW_13_1_X_2023-08-18-1100 release for testing. After initialization, the merged branch is rebased with
```git cms-rebase-topic --old-base CMSSW_13_3_X_2023-08-15-1100 hsert:tauHLTPhase2_dev```
and run the following runMatrix test, and there was no failed run.
```runTheMatrix.py -l limited -i all --ibeos```

### CODE REVIEW

**Comment by missirol** [comment]
backport of https://github.com/cms-sw/cmssw/pull/42562

**Comment by missirol** [comment]
please test

**Comment by missirol** [comment]
@hsert , while not strictly needed for HLT Phase-2 studies, I would prefer to also have a backport to 13_2_X as done for other recent HLT Phase-2 PRs. Can you please open a backport to 13_2 ? Thanks.

**Comment by missirol** [comment]
+hlt

**Comment by rappoccio** [comment]
+1

**Pull request merged**
