### PR TITLE
Sped up principal 'put'

### PR DESCRIPTION
**Pull request by Dr15Jones**
Sped up the time it takes to 'put' data into the Event, LuminosityBlock and Run. 

Using a configuration with the same topology as the HLT but with trivial modules, the code makes that configuration run 20% faster.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
please abort test

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by arunhep** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by perrotta** [comment]
+1
- RecoLuminosity/LumiProducer/plugins/ExpressLumiProducer.cc its the only reco file touched. It chages from
   produces<std::string, edm::InLumi>("...")
to
   produces<std::string, edm::Transition::BeginLuminosityBlock>("...")
(which is the same as currently in LumiProducer.cc, by the way)
- No differences in jenkins tests (none expected)

**Comment by davidlange6** [comment]
merge

**Pull request merged**
