### PR TITLE
Improvements to memory handling of LHE ascii blobs (add lzma compression)

### PR DESCRIPTION
**Pull request by bendavid**
Solves in a minimal way (ie without changing the basic workflow) the large memory usage issue discussed in
https://hypernews.cern.ch/HyperNews/CMS/get/edmFramework/3458/1/1/1/1/1/1/1/1/1/2/1/1/1/1/1/1/1/1/1/3/1/1/1.html

Basically the uncompressed ascii blobs from the lhe's were loaded into memory all at once and killing both LHE merge and GEN-SIM jobs in production.  (The straw that broke the camel's back being the increase in the number of alternate pdf weights used for LO madgraph in Run 2 production)

### CODE REVIEW

**Comment by bendavid** [comment]
This has been tested to give identical results both for pythia downstream as well as ascii dumps of the lhe files.

**Comment by bendavid** [comment]
+1

**Comment by davidlange6** [comment]
@cmsbuild, please test

**Comment by davidlange6** [comment]
+1

**Pull request merged**
