### PR TITLE
L1T Phase-2 Correlator Layer 1 updates for Multiboard tests

### PR DESCRIPTION
**Pull request by gpetruc**
#### PR description:

This PR updates the Level-1 Trigger Phase-2 Correlator Layer 1 code:
 * the hgcal cluster word unpacker emulator can now be configured to unpack also the extra shower shape variables or not, to match what the firmware does inside vs outside the tracker coverage
    *  In cms-l1t-offline, this in https://github.com/cms-l1t-offline/cmssw/pull/1096/commits/382fffe70ad22be28379a4c1de611c2e2d2a3982 from https://github.com/cms-l1t-offline/cmssw/pull/1096 but that commit was lost when porting to cmssw-master with #41290
 * the forward hgcal region is now emulated accurately (physics performance should be unchanged since occupancies are well below the threshold at which truncations happen)
 * emulation of the correlator at tmux18 is now possible in CMSSW
 * the correlator pattern file writers are updated to run on the newer samples, to use a cabling map that reflects the current firmware, and to support also the tmux18 option

Corresponds to cms-l1t-offline https://github.com/cms-l1t-offline/cmssw/pull/1157

I'll soon update both PRs with the fillDescriptions for the Level-1 Trigger Phase-2 Correlator Layer 1 code which I'm currently validating, but I would like to have jenkins run first a set of tests without those changes, and give a chance to the reviewers to see the code before those changes if they want (the fillDescriptions part will be a lot of code changes that shouldn't make any difference at all in the results, so I'd rather factor them out)

#### PR validation:

Tested in `CMSSW_13_3_X_2023-08-21-2300` on `el8`, with:
 * the usual `scram b code-format && scram b code-checks && scram b check-headers && scram b runtests`
 * matrix workflow `23234.0_TTbar_14TeV+2026D94`
 * running `make_l1ct_binaryFiles_cfg.py` under `L1Trigger/Phase2L1ParticleFlow/test`

@cerminar

### CODE REVIEW

**Comment by gpetruc** [comment]
@cmsbuild, please test

**Comment by aloeliger** [comment]
@gpetruc Am I waiting for `fillDescriptions` updates on this? Otherwise this all looks good to me.

**Comment by gpetruc** [comment]
I added now the fillDescriptions part. If you want to see the separate diffs,
 * [without fillDescriptions](https://github.com/cms-sw/cmssw/compare/master...gpetruc:multiboard_correlator_master_noFillDescr)
 * [just fillDescriptions](https://github.com/gpetruc/cmssw/compare/multiboard_correlator_master_noFillDescr...gpetruc:cmssw:multiboard_correlator_master)

Correlator Layer 1 outputs are bitwise identical before vs after the fillDescriptions, as expected

**Comment by gpetruc** [comment]
@cmsbuild , please test

**Comment by aloeliger** [comment]
+l1

**Comment by gpetruc** [comment]
Hello @AdrianoDee @srimanob can you review this PR as well?

L1 has already signed it off last week.

Thanks,

Giovanni

**Comment by srimanob** [comment]
@cmsbuild please test

Retrigger the test after 2 weeks

**Pull request merged**
