### PR TITLE
90x TTrackAssociator in L1TrackTrigger Sequence and in FEVT Eventcontent.

### PR DESCRIPTION
**Pull request by rekovic**
This is useful for L1T MC production....don't want to calculated TriggerTrack Stubs, Clusters, and Associator.

Details of the PR:
 * Add TrackTriggerAssociatorClustersStubs to the L1TrackTrigger sequence, and configure Associator and StubAlgorithm as per experts recipe 
* Add keep Associator digis in FEVT* event content. 
* Turn cout to LogInfo for TrackerParametersESModule.

### CODE REVIEW

**Comment by rekovic** [comment]
please test

**Comment by Dr15Jones** [comment]
assign upgrade

**Comment by kpedro88** [comment]
It's hard for me to tell if the error is caused by this PR (but the comparison baseline logs for `CMSSW_9_0_X_2017-02-28-2300` look clean):
```
#5  0x00007f9e17f71320 in AddFourMomenta::set(reco::Candidate&) const () from /cvmfs/cms-ib.cern.ch/nweek-02461/slc6_amd64_gcc530/cms/cmssw/CMSSW_9_0_X_2017-02-28-2300/lib/slc6_amd64_gcc530/libPhysicsToolsCandUtils.so
#6  0x00007f9e0a01fb4f in reco::tau::RecoTauPiZeroStripPlugin3::operator()(reco::PFJet const&) const () from /cvmfs/cms-ib.cern.ch/nweek-02461/slc6_amd64_gcc530/cms/cmssw/CMSSW_9_0_X_2017-02-28-2300/lib/slc6_amd64_gcc530/pluginRecoTauTagRecoTauPlugins.so
#7  0x00007f9e0a02b786 in RecoTauPiZeroProducer::produce(edm::Event&, edm::EventSetup const&) () from /cvmfs/cms-ib.cern.ch/nweek-02461/slc6_amd64_gcc530/cms/cmssw/CMSSW_9_0_X_2017-02-28-2300/lib/slc6_amd64_gcc530/pluginRecoTauTagRecoTauPlugins.so
```

**Comment by rekovic** [comment]
@kpedro88 Indeed. I will recheck locally repeating the the failing tests.
In all three failed tests,  the error messages come from the step3
step3_RAW2DIGI_L1Reco_RECO_PAT_VALIDATION_DQM.

**Comment by rekovic** [comment]
Vanilla `CMSSW_9_0_X_2017-02-26-2300` does not crash. The PR included crashes the step3 of the above jobs.  The link is not obvious, so needs further investigation.

**Comment by davidlange6** [comment]
Hi @rekovic- I would suggest using valgrind. Looks like memory corruption for such unrelated code to have problems.

**Comment by ianna** [comment]
please, rebase

**Comment by kpedro88** [comment]
@rekovic this either needs to be rebased or closed

**Pull request closed without merging**
