### PR TITLE
Update to HLT menu version 2.1 (101X) 

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
Update to HLT menu version 2.1 (101X)
Based on CMSSW_10_1_X_2018-05-22-2300
Adding also frozen menu dump for @relval2018
Superseeds #23079

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
backport of #23292

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by Martin-Grunewald** [comment]
@arunhep please sign this PR as it superseedes the old #23079

**Comment by Martin-Grunewald** [comment]
@Dr15Jones can you please also sign the backport for addOntests.py ?
Thanks!

**Comment by Dr15Jones** [comment]
+1

**Comment by fabiocos** [comment]
@Martin-Grunewald sorry, I see that the GRun menu is changed, and this is the menu used in the ongoing 101X MC production. So I assume that the same argument to keep on hold the previous PR is valid also for this one, am I correct?

**Comment by Martin-Grunewald** [comment]
@fabiocos 
Adding @gennai 
Indeed this is the case, but please note that TSG would like this update even for (the next batch of) 101X MC production, as what is currently used is of no interest, not even to POG studies.

**Comment by gennai** [comment]
Hi, I confirm what @Martin-Grunewald wrote. We also discussed it in the past TSG meeting and added a comment in the Physics Coordination report. Especially EGamma POG strongly support the interest for this new menu

**Comment by fabiocos** [comment]
@Martin-Grunewald @gennai thanks for the comment

@klute @franzoni FYI

**Comment by Martin-Grunewald** [comment]
@fabiocos 
...ping...

**Comment by fabiocos** [comment]
+1

after agreement with PPD conveners

**Pull request merged**
