### PR TITLE
Phase2-hgx359W Modify the testing code in some packages in RecLocalCalo, SimG4CMS and Validation because of changes made in the Configuration/Geometry area for Phase2 scenarios

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Modify the testing code in some packages in RecLocalCalo, SimG4CMS and Validation because of changes made in the Configuration/Geometry area for Phase2 scenarios. These are backports of #45790 #45791 and #45793

#### PR validation:

Checked some of the modified scripts in present context

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

 Backports of #45790 #45791 and #45793

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by jfernan2** [comment]
+1

**Comment by civanch** [comment]
+1

I would include these updates in 14_1_X to have geometry tests consistent with 2024 geometry

**Comment by bsunanda** [comment]
@srimanob Please approve this PR

**Comment by bsunanda** [comment]
@antoniovagnerini, @nothingface0, @rvenditti, @syuvivida, @tjavaid Please approve this PR

**Comment by tjavaid** [comment]
+1

**Comment by bsunanda** [comment]
@srimanob Please approve this PR

**Comment by srimanob** [comment]
+Upgrade

**Comment by mandrenguyen** [comment]
backport of https://github.com/cms-sw/cmssw/pull/45790
https://github.com/cms-sw/cmssw/pull/45791 and https://github.com/cms-sw/cmssw/pull/45793

**Comment by mandrenguyen** [comment]
+1

**Comment by mandrenguyen** [comment]
type hgcal

**Pull request merged**
