### PR TITLE
Change PI using literals in DataFormats/Math

### PR DESCRIPTION
**Pull request by mrodozov**
#### PR description:

Change literals such that they compile on PPC
see 
https://github.com/cms-sw/cmssw/issues/33743#issuecomment-848572197

#### PR validation:

Compiles on PPC, precision for double is the same as using the "" _pi operator

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test for slc7_ppc64le_gcc9

**Comment by mrodozov** [comment]
please test slc7_aarch64_gcc9

**Comment by slava77** [comment]
+reconstruction

for https://github.com/cms-sw/cmssw/pull/33892	32bf4b9
- technical
- tests pass and comparisons show no (relevant) differences

**Comment by qliphy** [comment]
merge

**Pull request merged**
