### PR TITLE
HGCAL: Change ToA to local time

### PR DESCRIPTION
**Pull request by stahlleiton**
#### PR description:

This PR changes the definition of the time of arrival to represent the local time at which the signal is detected in the HGCAL hit (instead of been back-propagated to 0,0,0). To ensure the time distribution is sampled within 25 ns window, a delay on the local time is added depending on the sub-detector equal to: EE=-9 ns, HEfront=-11 ns, HEback=-14 ns and HFNose=-33 ns.

These time delays are checked in the following plot:
image

This is part of the set of updates already announced in the HGCAL DPG meeting (see https://indico.cern.ch/event/1158758/contributions/4880969/attachments/2451390/4201020/Timining%2020220525%20v2-2.pdf).

#### PR validation:

PR was validated using the following cmsDriver command:
cmsDriver.py TTbar_14TeV_TuneCP5_cfi  --conditions auto:phase2_realistic_T21 -n 10 --era Phase2C18I13M9 --eventcontent FEVTDEBUG -s GEN,SIM,DIGI --datatier GEN-SIM-DIGI  --beamspot HLLHC14TeV --geometry Extended2026D94 --fileout file:step12_HF.root --customise SLHCUpgradeSimulations/Configuration/aging.customise_aging_3000

HGCAL-related changes were mainly observed on the ToA distribution as expected (bias towards lower ToA due to time delay) while changes in the ADC are due to different number of calls of the random number generator, which causes some smearing visible at lower ADC values.

Plots of local time test:

image

### CODE REVIEW

**Comment by rovere** [comment]
@cmsbuild please test

**Comment by pfs** [comment]
@mariadalfonso - this impacts HFNose as well

**Comment by srimanob** [comment]
assign hgcal-dpg

The code change is minimal, but better if hgcal signs the PR too on result/change.

**Comment by felicepantaleo** [comment]
hi @stahlleiton , 
thanks for the PR. Moving to a local time definition is very welcome!
As I commented during your presentation there are three points that should be considered, in order of priority:

1. Do we really need an offset at all? A single precision floating point number can very well represent tens of ns with a precision of few femtoseconds. Shall we get rid of it altogether? 
2. I suggested asking the other DPGs like @cms-sw/mtd-dpg-l2 to uniform the treatment of timing across the CMS detector. What was the result of this discussion?
3. In the reconstruction we are matching calorimetric clusters with tracks and rejecting connections also based on timing compatibility. In fact, this is visible in a drop in the number of electrons with an increase in the number of reconstructed photons. Parts of code where the time from different detectors are compared should be tracked down and adjusted to this new definition.

**Comment by pfs** [comment]
Hi, i think we need an offset. The intrinsic precision is 25ns/1023 =
24 ps in the ROC, but what's more important is that we are limited in
the 0-25ns range. If we leave the simulated ToA without offset it'll
be probably OK for em showers, but we may start loosing a bit more on
the hadronic calorimeter where showers arrive later and take longer to
develop. This is the first plot of the PR.
As at this moment it's not totally clear how long we need to integrate
the charge in the hadronic section, and as we know for sure there is a
configurable offset in the ROCs, I would propose to keep an offset for
the moment. This would leave the simulations the "most ideal" case
where most of the charge that can be possibly be integrated in the
25ns range will be so.


2022-09-20 16:48 GMT+02:00, Felice Pantaleo ***@***.***>:
> hi @stahlleiton ,
> thanks for the PR. Moving to a local time definition is very welcome!
> As I commented during your presentation there are three points that should
> be considered, in order of priority:
>
> 1. Do we really need an offset at all? A single precision floating point
> number can very well represent tens of ns with a precision of few
> femtoseconds. Shall we get rid of it altogether?
> 2. I suggested asking the other DPGs like @cms-sw/mtd-dpg-l2 to uniform the
> treatment of timing across the CMS detector. What was the result of this
> discussion?
> 3. In the reconstruction we are matching calorimetric clusters with tracks
> and rejecting connections also based on timing compatibility. In fact, this
> is visible in a drop in the number of electrons with an increase in the
> number of reconstructed photons. Parts of code where the time from different
> detectors are compared should be tracked down and adjusted to this new
> definition.
>
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/cms-sw/cmssw/pull/39447#issuecomment-1252469501
> You are receiving this because you were mentioned.
>
> Message ID: ***@***.***>


-- 
Pedro

gmail: ***@***.***
cern:   ***@***.***
skype: pedrosilvaspace

**Comment by pfs** [comment]
Hi again, regarding point 2. raised by @felicepantaleo, this change is in line with MTD which digitizes directly the Geant4 time. In that case without offset as it's not so relevant because it's not a calorimeter.

**Comment by stahlleiton** [comment]
> hi @stahlleiton , thanks for the PR. Moving to a local time definition is very welcome! As I commented during your presentation there are three points that should be considered, in order of priority:
> 
>     1. Do we really need an offset at all? A single precision floating point number can very well represent tens of ns with a precision of few femtoseconds. Shall we get rid of it altogether?
> 
>     2. I suggested asking the other DPGs like @cms-sw/mtd-dpg-l2 to uniform the treatment of timing across the CMS detector. What was the result of this discussion?
> 
>     3. In the reconstruction we are matching calorimetric clusters with tracks and rejecting connections also based on timing compatibility. In fact, this is visible in a drop in the number of electrons with an increase in the number of reconstructed photons. Parts of code where the time from different detectors are compared should be tracked down and adjusted to this new definition.

I updated the PR considering @felicepantaleo 3rd point. The correction of the tof delay (changing from local time to global time) is now done in the uncalibrated rechits instead of upstream and the comparison between the MTD and HGCAL times is done at the front of the HGCAL (both propagated to the 1st layer).

**Comment by pfs** [comment]
please test

**Comment by pfs** [comment]
I'm not sure if this PR is now properly rebased becasue there was a "force push" and there are several new signatures pending

**Comment by pfs** [comment]
please test

**Comment by pfs** [comment]
@cmsbuild  please test

**Comment by mandrenguyen** [comment]
Browsing the code changes I would expect changes to be limited to HGCAL and PF.  However, I see changes to the local reco of other detectors, e.g.,
[all_OldVSNew_TTbar14TeV2026D88wf39434p0c_log10HFRecHitsSorted_hfreco__RECO_obj_obj_energy](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_6_X_2022-10-02-2300+c3161c/53102/validateJR/all_OldVSNew_TTbar14TeV2026D88wf39434p0/all_OldVSNew_TTbar14TeV2026D88wf39434p0c_log10HFRecHitsSorted_hfreco__RECO_obj_obj_energy.png)
Is that expected?

**Comment by stahlleiton** [comment]
We will split this PR into two: one dedicated to the digi changes to local time while keeping the time backpropagated to 0 at reco level (as currently done)  and a future one dedicated to changing the reconstruction algorithm also to local time. The changes at the digi level are unavoidable due to the random number generator.

**Pull request closed without merging**
