### PR TITLE
Faster mahi pulse shape initialization

### PR DESCRIPTION
**Pull request by igv4321**
#### PR description:

MAHI now memoizes PulseShapeFunctor objects instead of recreating them every time a different pulse shape is encountered. Only a few different pulse shapes exist (corresponding to different SiPM/HPD types), so std::vector is used to hold the collection instead of std::map.

No changes in the relval results expected.

#### PR validation:

The usual runTheMatrix tests were run

### CODE REVIEW

**Comment by kpedro88** [comment]
please test

**Comment by perrotta** [comment]
@igv4321 : do you have any measurement of the speedup expected because of this PR?
I'm comparing step3 of wf 136.888 and I can't see any relevant improvement in timing...

**Comment by igv4321** [comment]
Yeah, the difference for wf 136.888 would be that the old MahiFit would call PulseShapeFunctor constructor 200 times while the new one calls it just two times. At the same time, hcal local reco processes about half a million HB/HE rechits. While the time difference should be there, it would not be easy to see it.

I did not try to measure the speed improvement. I simply do not have access to a machine with a sufficiently low load to make precise measurements.

**Comment by perrotta** [comment]
+1
- Reduction in number of calls of the PulseShapeFunctor is expected to speed up the Mahi initialization time: such an effect wasn't clearly observed in the limited sample workflow run possibly with some concurrent job in the machine, but it is expected to be there
- IgProf shows that the increased memory consumption (in  MahiFit::setPulseShapeTemplate) is quite acceptable: from 4.2 kb to 8.6 kb
- Jenkins tests pass and show no differences in outputs

**Comment by silviodonato** [comment]
+1

**Pull request merged**
