### PR TITLE
Replace Geometry_cff with GeometryDB_cff in DPGAnalysis

### PR DESCRIPTION
**Pull request by jeongeun**
**PR description:**
Review on the Reco part of https://github.com/cms-sw/cmssw/issues/31113

`process.load("Configuration.StandardSequences.Geometry_cff")`
 was outdated https://github.com/cms-sw/cmssw/pull/8810 
It should be replaced with
`process.load("Configuration.StandardSequences.GeometryDB_cff")`

In this PR, DPGAnalysis configuration files (11 files) are fixed.

```
        modified:   DPGAnalysis/Skims/python/CSCSkim_BFieldStudies_MC_ToscaMap090322_cfg.py
        modified:   DPGAnalysis/Skims/python/CSCSkim_BFieldStudies_ToscaMap090322_cfg.py
        modified:   DPGAnalysis/Skims/python/DoubleMuon_cfg.py
        modified:   DPGAnalysis/Skims/python/PointingDoubleMultiSkim_cfg.py
        modified:   DPGAnalysis/Skims/python/RPCNoise_example.py
        modified:   DPGAnalysis/Skims/python/SuperPointing_MC_ToscaMap090322_cfg.py
        modified:   DPGAnalysis/Skims/python/SuperPointing_ToscaMap090322_cfg.py
        modified:   DPGAnalysis/Skims/python/SuperPointing_and_pixcluster_cfg.py
        modified:   DPGAnalysis/Skims/python/TrackerPointing_MC_ToscaMap090322_cfg.py
        modified:   DPGAnalysis/Skims/python/TrackerPointing_ToscaMap090322_cfg.py
        modified:   DPGAnalysis/Skims/python/filterRecHits_cfg.py
```

Please inform us if there is any obsolete configurations in this PR. Then I will remove.

#### PR validation:
Tested in CMSSW_12_5_X, the basic test all passed in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by mandrenguyen** [comment]
@cms-sw/pdmv-l2 
Perhaps you can sign?

**Comment by kskovpen** [comment]
+pdmv

**Comment by mandrenguyen** [comment]
> +1
> 
>     * Quite likely unused configs, but ok...

Surely not used, but we're trying to get rid of all mentions of Geometry_cff that were raised in the issue in the PR description.  This is the last one in the reco packages.

**Pull request merged**
