### PR TITLE
HBHE M3 = fix M3 (90)

### PR DESCRIPTION
**Pull request by mariadalfonso**
backport of the #17983

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by mariadalfonso** [comment]
@slava77 @fwyzard @deguio 
it's important to have this PR in the 90X so that the siPM can be properly calibrated

**Comment by fwyzard** [comment]
sigh, this might be late for 9.0.0 ?

@mariadalfonso , does the change affect DIGI or HLT/RECO ?
In other words, if we run with a release that contains this PR (e.g. 9.1.x) over MC samples made with a release without this PR (e.g. 8.3.0) do we get the old or new results ?

**Comment by mariadalfonso** [comment]
@fwyzard 
This PR doesn't change the DIGI and you need to check with @kpedro88  if that is ok for the HCAL-DIGI point of view.

Regarding the RECO/HLT
https://github.com/cms-sw/cmssw/releases/tag/CMSSW_8_3_0
the 8.3.0 should not be use neither for the offline PF calibration neither for the online one
as it miss the M2 changes (#17533 #17311) and M3 changes (#17984 #17871)
of course is ok if you use the 9.1.x to re-HLT/re-RECO

**Comment by franzoni** [comment]
attn: @slava77 

There's something inaccurate in the fact that this PR has alca signature - stemming from the fact that CalibCalorimetry/HcalAlgos holds both calibration related code and local reco / shape modelling classes.
@deguio @hatakeyamak would it be possible to factor our into reco or sim packages code which pertains there?

**Comment by slava77** [comment]
On 3/21/17 8:04 AM, Giovanni Franzoni wrote:
> attn: @slava77 <https://github.com/slava77>
> 
> There's something inaccurate in the fact that this PR has alca signature
> - stemming from the fact that CalibCalorimetry/HcalAlgos holds both
> calibration related code and local reco / shape modelling classes.
> @deguio <https://github.com/deguio> @hatakeyamak
> <https://github.com/hatakeyamak> would it be possible to factor our into
> reco or sim packages code which pertains there?

Thank you for noting a stronger connection to reco.
For these cases now you can issue "assign reconstruction"

**Comment by kpedro88** [comment]
@franzoni the problem is that many of these classes need to be used by both SIM and RECO. The guidelines for what packages should host such classes are not very clear.

**Comment by fwyzard** [comment]
+1

**Comment by fwyzard** [comment]
(signature for psychological support)

**Comment by mariadalfonso** [comment]
fixed array based to the discussion in #17983

**Comment by davidlange6** [comment]
please test

**Comment by slava77** [comment]
backport of #17983

**Pull request merged**
