### PR TITLE
Implement the fillDescriptions method for RawStreamFileWriterForBU (11.2.x)

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Implement the `fillDescriptions()` method for the `RawStreamFileWriterForBU` module.
Clean up the module's parameters and directly use an `InputTag` in the python configuration.

#### PR validation:

None.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Backport of #32284

### CODE REVIEW

**Comment by fwyzard** [comment]
backport #32284

**Comment by fwyzard** [comment]
please test

**Comment by smorovic** [comment]
+1

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/32323	2e2b420 
- trivial backport of #32284 (the same topic branch is used)

**Comment by qliphy** [comment]
+1

**Pull request merged**
