### PR TITLE
Add public interface for constructing and freeing caching allocators

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

Addresses #34718 by adding two public functions to construct caching allocators and free cached memory from `CUDAService`.

#### PR validation:

Code compiles.

### CODE REVIEW

**Comment by makortel** [comment]
enable gpu

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
