### PR TITLE
CTPPS pixel mapping for 2018

### PR DESCRIPTION
**Pull request by fabferro**
CTPPS pixel mapping for 2018 to be added to the DB

### CODE REVIEW

**Comment by arunhep** [comment]
@fabferro why do you we need this xml file in release?
isn't this mapping is already in DB with this request? https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3480.html

**Comment by fabferro** [comment]
I'm putting it in the release mainly for reference, but it's not actually needed.
The requests you are mentioning contained only 2017 mapping. The mapping corresponding to this file will be queued in the next days (@clemencia @malbouis ).

**Comment by lpernie** [comment]
please test

**Comment by fabiocos** [comment]
@lpernie @arunhep @ggovi could you please review and sign or comment?

**Comment by arunhep** [comment]
+1

**Comment by ggovi** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
