### PR TITLE
[CMSSW_14_0_X] Update 2024 MC GTs with the L1 menu L1Menu_Collisions2024_v1_0_1_xml

### PR DESCRIPTION
**Pull request by perrotta**
#### PR description:

Update the 2024  MC GTs with the new L1 menu as in cmsTalk https://cms-talk.web.cern.ch/t/update-of-the-2024-l1-menu-tag-l1menu-collisions2024-v1-0-1/36759

The updated tag for L1TUtmTriggerMenuRcd is
From:   **L1Menu_Collisions2024_v1_0_0_xml**
To:   	**L1Menu_Collisions2024_v1_0_1_xml**

**GT differences**

- phase1_2024_design: https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/140X_mcRun3_2024_design_v4/140X_mcRun3_2024_design_v3

- phase1_2024_realistic: https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/140X_mcRun3_2024_realistic_v5/140X_mcRun3_2024_realistic_v4

- phase1_2024_cosmics:https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/140X_mcRun3_2024cosmics_realistic_deco_v5/140X_mcRun3_2024cosmics_realistic_deco_v4

- phase1_2024_cosmics_design: https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/140X_mcRun3_2024cosmics_design_deco_v3/140X_mcRun3_2024cosmics_design_deco_v2

#### PR validation:

Tested in master

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

backport of #44389

### CODE REVIEW

**Comment by perrotta** [comment]
please test with #44397

**Comment by perrotta** [comment]
backport of https://github.com/cms-sw/cmssw/pull/44389

**Comment by mmusich** [comment]
hold
   * unclear if https://github.com/cms-sw/cmssw/pull/44397 is causing trigger results irreproducibility .

**Comment by perrotta** [comment]
As agreed during the joint operations [meeting of 18th March](https://docs.google.com/document/d/1qNrrmaGCMTFdytBK-jw2zqMs29CHIY5v25fD-MrBVeM/edit#heading=h.94pe6ztmuo2l) this PR and https://github.com/cms-sw/cmssw/pull/44397 can get closed, and the corresponding PRs already merged in master should be reverted

**Pull request closed without merging**
