### PR TITLE
 Moved code to new FWCore/Reflection package 

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

Moved code dealing with run-time understanding of a class to its
own package.
This also removes the ROOT dependency from FWCore/Utilities.

#### PR validation:
Used `git grep ` for all the file names to find which ones to change. The changes compile and link.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
The requested code formats are not for any lines modified by this pull request. The changes in PhysicsTools/CondLiteIO are part of #27278. The one change to DataFormats/PatCandidates/src/UserData.cc does not appear to be in any presently created pull request.

**Comment by Dr15Jones** [comment]
@fabiocos how do you want to proceed with the code-formatting?

**Comment by fabiocos** [comment]
@Dr15Jones #27278 overlaps with both this PR and #26592 by @wddgit :
```
Testing PR #  27278  for branch  master
File  CondCore/ESSources/plugins/CondDBESSource.cc  modified in PRs #  ['26592', '27278']
File  CondCore/ESSources/plugins/CondDBESSource.h  modified in PRs #  ['26592', '27278']
File  PhysicsTools/CondLiteIO/plugins/FWLiteESRecordWriterAnalyzer.cc  modified in PRs #  ['26592', '27287', '27278']
File  PhysicsTools/CondLiteIO/plugins/FWLiteESSource.cc  modified in PRs #  ['26592', '27278']
File  PhysicsTools/CondLiteIO/src/RecordWriter.cc  modified in PRs #  ['27287', '27278']
```
I am ready to integrate it into next IB, if this is ok for you, so as the rest can be done on a clean basis. Technically this PR can be merged on top of that (verified), you will just need to rerun code-checks.

**Comment by Dr15Jones** [comment]
>I am ready to integrate it into next IB, if this is ok for you, so as the rest can be done on a clean basis. Technically this PR can be merged on top of that (verified), you will just need to rerun code-checks.

@fabiocos I'm not sure which pull request you mean. If it is one of the code-format pull requests, then I'm all fine with first merging those.

**Comment by Dr15Jones** [comment]
@fabiocos what about code-format for DataFormats/PatCandidates?

**Comment by fabiocos** [comment]
@Dr15Jones yes, I mean merging #27278 tonight. For PatCandidate we do not have anything open yet as far as I can see: @smuzaffar is this in the pipe? In any case this PR has just these overlaps at present:
```
Testing PR #  27287  for branch  master
File  IOPool/Streamer/BuildFile.xml  modified in PRs #  ['27288', '27287']
File  IOPool/Streamer/src/StreamerInputSource.cc  modified in PRs #  ['27288', '27287']
File  PhysicsTools/CondLiteIO/plugins/FWLiteESRecordWriterAnalyzer.cc  modified in PRs #  ['26592', '27287', '27278']
File  PhysicsTools/CondLiteIO/src/RecordWriter.cc  modified in PRs #  ['27287', '27278']
File  Utilities/ReleaseScripts/scripts/git-publish  modified in PRs #  ['27287', '27230']
```

**Comment by smuzaffar** [comment]
@Dr15Jones , go ahead and apply the code-format changes. I can redo the https://github.com/cms-sw/cmssw/pull/27278 once this PR is merged.

**Comment by fabiocos** [comment]
@Dr15Jones @smuzaffar #27278 has been merged without any conflict, I restart the code-checks

**Comment by fabiocos** [comment]
code-checks

**Comment by smuzaffar** [comment]
please test

**Comment by Dr15Jones** [comment]
@smuzaffar this build failure shows a problem with our build system. DataFormats/LuminosityBlock has no code that uses ROOT. It had previously gotten a ROOT dependency `<use name="rootcore"/>` from linking with FWCore/Utilities. In this pull request FWCore/Utilities lost that ROOT dependency. However, now the dictionary generation for DataFormats/LuminosityBlock is failing because it can't find the ROOT header 'RConfig.h'. 

Therefore the problem with the build system is it was implicitly relying on packages which do not depend on ROOT to add a ROOT link in order for the dictionary generation to work.

To fix the problem with this pull request, I can add a direct link to ROOT in DataFormats/LuminosityBlock or we could revise how scram builds the _xr.cc autogenerated dictionary files. Which would you prefer?

**Comment by Dr15Jones** [comment]
@smuzaffar for a bit more context. The probably reason the other DataFormats package work is they depend on DataFormats/Common which depends on DataFormats/Provenance which depends on FWCore/Reflection which finally depends on rootcore. However, I was going to look at removing the FWCore/Reflection dependency from DataFormats/Provenance. If I do that, most DataFormats package will probably fail to build unless we change how the build system handles the dictionary compilation/linking.

**Comment by smuzaffar** [comment]
@Dr15Jones , I would suggest to teach scram to add rootrflx dependency for packages with dict. I will provide a cmsdist PR to go with this.

**Comment by smuzaffar** [comment]
please test with cms-sw/cmsdist#5052

**Comment by Dr15Jones** [comment]
+1

**Comment by perrotta** [comment]
+1
- Technical
- Jenkins tests pass (since the merge of https://github.com/cms-sw/cmsdist/pull/5052)

**Comment by fabiocos** [comment]
@ggovi @efeyazgan @qliphy @santocch please check this PR

**Comment by fabiocos** [comment]
@ggovi @efeyazgan @qliphy the additions to your areas look technical and straightforward, I would like to move forward this PR

**Comment by efeyazgan** [comment]
+1

**Comment by santocch** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Comment by fabiocos** [comment]
@smuzaffar as expected this has broken again the FWLite build, the package list needs to be updated again with the new package added here

**Comment by smuzaffar** [comment]
@fabiocos , this has been already fixed https://github.com/cms-sw/cmsdist/pull/5056

**Pull request merged**
