### PR TITLE
SiStrip Commissioning Updates

### PR DESCRIPTION
**Pull request by rgerosa**
This pull request includes several updates for:

1) New workflow (DaqScopeMode task) developed to use SiStrip spy-data to measure pedestal, noise and tick-mark height.
2) Updates for calibration-scan and calibration-run source steps due to the migration to a new SiStrip local-DAQ infrastructure.
3) Bug fix in the condition upload for the SiStrip online bad-strip analysis, plus fix in the analysis summary plot generation.

None of the proposed changes should affect the production workflow.

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/23228	c954c26
- changes are tangential to reco. The only file in reco category DataFormats/SiStripCommon/interface/ConstantsForDqm.h has an addition of a const used/shared for DQM purposes.
- jenkins tests pass and comparisons with the baseline show no differences

**Comment by dmitrijus** [comment]
+1

**Comment by rgerosa** [comment]
Are there updates/news concerning this  PR?

**Comment by ggovi** [comment]
+1
There are changes in CondFormats but they don't involve persistent classes.

**Comment by lpernie** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
