### PR TITLE
Added new and cleaned up existing Geant4 Physics Lists

### PR DESCRIPTION
**Pull request by civanch**
Clean up physics options for Genat4 simulation:
1) Added extra Physics Lists FTFP_BERT_EMN and QGSP_FTFP_BERT_EMN where of top of CMS production configuration for Run-2 more accurate e+- transport provided for HGCal. This should be faster than EMY and EMZ options from Geant4 distribution.
2) cleaned up EML and EMN electromagnetic model configurations 
3) dump of dEdx, range and cross section tables in the ASCII format instead of the binary format

Should not affect production and recommended to try for HGCal (@bsunanda )

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by fabiocos** [comment]
@civanch could you please clarify the implications of the update of the standard EM physics model? What is the expected physics impact (although no change is seen in the tests)? IS this just a technical code refactoring?

**Comment by civanch** [comment]
@fabiocos , in the production EM physics I change only  1 comment, so nothing should be different in regression tests. All modifications affect upgrade PhysicsList for R&D and PhysicsList for neutron background studies.

**Comment by fabiocos** [comment]
@civanch ok, in FTFP_BERT_EMM we use CMSEmStandardPhysicsLPM

https://cmssdt.cern.ch/lxr/source/SimG4Core/PhysicsLists/plugins/FTFPCMS_BERT_EMM.cc#0002

**Comment by fabiocos** [comment]
+1

**Pull request merged**
