### PR TITLE
Fix memory leak in ConversionLikelihoodCalculator

### PR DESCRIPTION
**Pull request by Dr15Jones**
Make sure the reader_ is deleted

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by slava77** [comment]
On 5/28/17 3:45 PM, Chris Jones wrote:
> Make sure the reader_ is deleted
> 

this leaks once per job, right?

**Comment by Dr15Jones** [comment]
It does leak once per job. But we have so many that leak just once that it is very hard to find ones that leak per event or ones that leak at the beginning and could be deleted at the beginning.

**Comment by slava77** [comment]
On 5/29/17 5:09 AM, Chris Jones wrote:
> It does leak once per job. But we have so many that leak just once that
> it is very hard to find ones that leak per event or ones that leak at
> the beginning and could be deleted at the beginning.
> 

thanks for the clarification.
I'm trying to capture if the mem leak fixes in this and other PRs
contribute to the memory issues in data processing.

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/18990	6e9c9cd
- implemented as described; technical
- jenkins tests pass and comparisons show no differences

**Comment by davidlange6** [comment]
+1

**Pull request merged**
