### PR TITLE
Efficiency flag correction

### PR DESCRIPTION
**Pull request by archiron**
Set the EfficiencyFlag to True into Validation/RecoEgamma/python files. No others changes.
@beaudett

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1
@archiron please let us know if this fixes the issue with the relative normalization of the histos in the DQM GUI. if confirmed I suggest you to have this backported to 74 as well.
thanks,
F.

**Comment by beaudett** [comment]
Hello Federico,
the problem shows up in RelMon only, to my knowledge DQM doesn't try to rescale the plots. Is there any easy way to have a RelMon preview or do we have to wait for an official Release validation campaign ?
Florian

**Comment by deguio** [comment]
ciao @beaudett 
relmon only provides links to the DQM GUI. whatever you see in relmon is taken from the GUI using one of the GUI APIs.

take for example:
https://cmsweb.cern.ch/dqm/relval/plotfairy/overlay?obj=archive%2F1%2FRelValTTbar_13%2FCMSSW_7_4_0-PU25ns_MCRUN2_74_V7_GENSIM_7_1_15-v1%2FDQMIO%2FEgammaV%2FElectronMcSignalValidator%2Fh_ele_absetaEff;obj=archive%2F1%2FRelValTTbar_13%2FCMSSW_7_4_0-PU25ns_MCRUN2_74_V7C_pxWorst_gs7115-v1%2FDQMIO%2FEgammaV%2FElectronMcSignalValidator%2Fh_ele_absetaEff;w=600;h=600;ref=ratiooverlay

you see from the link that this is a query to the DQM GUI directly. there is no manipulation done in relmon.
ciao,
F.

**Comment by deguio** [comment]
to answer your question: the easiest way is to wait for the next pre-release. it should come relatively soon for pre5. an alternative is to run manually the sequence and test on a private gui following the instructions at:
https://twiki.cern.ch/twiki/bin/viewauth/CMS/DQMTest#Installing_the_GUI_Server
I hope it helps,
F.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
