### PR TITLE
Implement eras for Run3 2025 PbPb UPC and oxygen runs

### PR DESCRIPTION
**Pull request by stahlleiton**
#### PR description:

This PR creates two new eras: Run3_2025_UPC and Run3_2025_OXY, meant for the reconstruction of PbPb UPC data and oxygen runs (both p-O and O-O) expected to be taken in 2025.

The plan is to use the UPC reco in the 2025 oxygen runs, so for the time being the Run3_2025_OXY is derived on top of Run3_2025_UPC, with the addition of a process modifier run3_oxygen for possible future changes on top.

A set of new relval workflows are also added, including:
- 182 and 182.1: tests 2025 UPC reco on simulations.
- 143.901 and 143.902: tests reco of 2025 UPC and pp eras on HIForward data.
- 143.911: tests reco of 2025 oxygen era on HIForward data.

And updated the 2024 UPC relval data workflows to use 2024 PbPb UPC data.

@mandrenguyen 

#### PR validation:

runTheMatrix.py -l 181,181.1,182,182.1,142.901,142.902,143.901,143.902,143.911

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

No backport is expected

### CODE REVIEW

**Comment by mandrenguyen** [comment]
please test workflow 181,181.1,182,182.1,142.901,142.902,143.901,143.902,143.911

**Comment by stahlleiton** [comment]
Seems the errors in the relval tests are not related to this PR.

**Comment by mandrenguyen** [comment]
please test

**Comment by stahlleiton** [comment]
@cms-sw/upgrade-l2 , @cms-sw/pdmv-l2 : please review/sign this PR , thanks

**Comment by Moanwar** [comment]
+Upgrade

**Comment by AdrianoDee** [comment]
+pdmv

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
