### PR TITLE
Update & optimize GEN-only Relval workflows

### PR DESCRIPTION
**Pull request by SanghyunKo**
#### PR description:

Updating & optimizing GEN-only Relval workflows as proposed in the recent Relval survey & relevant discussions. Commits contain:
1. Migration of GEN-only Relval fragments to CP5, and gridpacks to NNPDF3.1.
2. Update of MadGraph5 gridpacks to 5_2.6.5 & Sherpacks to 2.2.8.
3. Optimizing GEN-only (regular) Relval workflows up to 2 additional jets.

#### PR validation:

Tested locally using `runTheMatrix.py --what generator -l 503,504,505,506,512,541,545` and `runTheMatrix.py --what extendedgen -l 507,508,509,510,513,521,522,534,536,551,555,560,561`.

### CODE REVIEW

**Comment by chayanit** [comment]
please test

**Comment by kpedro88** [comment]
+upgrade

**Comment by qliphy** [comment]
+1

**Comment by chayanit** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
