### PR TITLE
Disabled PCA inputs for deepTau v2

### PR DESCRIPTION
**Pull request by swozniewski**
#### PR description:

Problems have been detected with dxy_PCA input variables to DeepTauID which are inconsistent between data and MC. This PR sets input values to 0 and disables the variables this way.
Issue and fix were discussed in https://indico.cern.ch/event/842796/contributions/3541592/attachments/1897386/3130770/2019-08-26_DeepTau_ID_2017v2_DY_MC_vs_Embedded_and_bug_in_definition_of_PCA_variables.pdf (see slide 7 in particular)

Backport to 10_2_X for legacy analyses intended.

#### PR validation:

compiles

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by swozniewski** [comment]
sorry, I added another commit. We decided to add a bit more information in the comment.

**Comment by perrotta** [comment]
abort test

**Comment by perrotta** [comment]
please abort test

**Comment by perrotta** [comment]
please test

**Comment by mbluj** [comment]
FYI, this PR and its backports are going to be updated to increment version of deepTauID on request of PC and XPOG from the coordination meeting today. It will involve changes in MiniAOD and NanoAOD.

**Comment by mbluj** [comment]
A set of recent commits is to run fixed deepTauID2017v2, i.e. with disabled usage of the dxy_PCA coordinates, with version number incremented (v2=>v2p1) on the common request.
I think it is ready to test.

**Comment by perrotta** [comment]
please test

**Comment by mbluj** [comment]
> -1
> 
> Tested at: [1d12008](https://github.com/cms-sw/cmssw/commit/1d1200898bb2e1d9110b77fccb956dc3a9ff5473)
> 
> You can see the results of the tests here:
> https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-87bf54/2258/summary.html
> 
> I found follow errors while testing this PR
> 
> **Failed tests: UnitTests**
> 
>     * **Unit Tests**:
> 
> 
> I found errors in the following unit tests:
> 
> ---> test runtestPhysicsToolsNanoAOD had ERRORS

The issue looks to be not related with this PR (inputs from older era than expected by test configuration), but I will followup tomorrow.

**Comment by mbluj** [comment]
Actually it the issue was introduced by this PR, now it should be fixed.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
> ---> test runtestPhysicsToolsNanoAOD had ERRORS

```
KeyError: 'Unknown parameter name idDeepTau2017v2p1VSjet specified while calling Modifier'
```
seems related

**Comment by mbluj** [comment]
Indeed, 1st fix of tau configuration for nanoAOD was prepared to quickly, now it should be fine.

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
Looking at where the 'deepTau2017v2' string is present in CMSSW, I think you should also update the nanoAOD DQM in PhysicsTools/NanoAOD/python/nanoDQM_cfi.py

@swozniewski @mbluj could you please verify?

**Comment by mbluj** [comment]
> Looking at where the 'deepTau2017v2' string is present in CMSSW, I think you should also update the nanoAOD DQM in PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
> 
> @swozniewski @mbluj could you please verify?

Yes, you are right. I'm going to fix is soon.

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
@swozniewski @mbluj, in view of the possible discussion at the ORP, could you please let us know which are the plans for this PR and its backports? I.e. are they planned for a given re-miniAOD campaign, or which is the urgency for having them ready for analyses?

Moreover, do you have updated plots as in page 2 of https://indico.cern.ch/event/842796/contributions/3541592/attachments/1897386/3130770/2019-08-26_DeepTau_ID_2017v2_DY_MC_vs_Embedded_and_bug_in_definition_of_PCA_variables.pdf made with the updated id as in this PR?

**Comment by peruzzim** [comment]
Let me comment here, yes, we will want this backported to 10_2 and 10_6 because it's the version that should replace v2 for Run2 data analysis. And yes, it will be included in a future MINIAOD run. We can discuss at the ORP how to handle this (I guess with the usual run2_miniAOD_devel), probably we will want to switch it on before UL18 starts.

**Comment by mbluj** [comment]
> @swozniewski @mbluj, in view of the possible discussion at the ORP, could you please let us know which are the plans for this PR and its backports? I.e. are they planned for a given re-miniAOD campaign, or which is the urgency for having them ready for analyses?

Backports of this PR are already prepared:  
* #27882 for 106X for UL reMiniAODv2 (under `run2_miniAOD_devel` era as mentioned in #27889), 
* #27879 for 102X for legacy analyses (not added to official workflows) with corresponding PR to nanoAOD repository  cms-nanoAOD#396. The latter development is base of private recipe of Tau POG.
> 
> Moreover, do you have updated plots as in page 2 of https://indico.cern.ch/event/842796/contributions/3541592/attachments/1897386/3130770/2019-08-26_DeepTau_ID_2017v2_DY_MC_vs_Embedded_and_bug_in_definition_of_PCA_variables.pdf made with the updated id as in this PR?

To redo those plots a number of samples has to be processed. Such processing with 102X is well advanced, plots can be expected at the end of this week or beginning of next one.

**Comment by perrotta** [comment]
+1
- From the point of view of the code this PR implements what announced in the PR description: the new deep tau id version v2p1 disables (i.e. sets to 0) the PCA inputs.
- v2p1 replaces the previous v2 everywhere, and the change is propagated wherever needed for mini and nano AOD productions and DQM in cmssw
- Jenkins tests show differences in the tau id in miniAOD, as expected
- Some global comparison data/MC is [announced](https://github.com/cms-sw/cmssw/pull/27878#issuecomment-527173557) to arrive in short, but the results shown in the presentation linked from the PR description suggest that by disabling the PCA inputs the ids move in the right direction

**Comment by peruzzim** [comment]
+1

**Comment by santocch** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Comment by mbluj** [comment]
For records: a set of control plots obtained with the fixed DeepTau 2017v2p1, i.e. with PCA inputs disabled, can be found in https://indico.cern.ch/event/847915/contributions/3565600/attachments/1908653/3153065/TauPOG_DeepTauIDv2p1.pdf (for instance see sl. 4-5 and 12-14). The fix improves data/MC agreement as expected for whole Run-2, in particular ~30% disagreement for 2017 is solved.

**Pull request merged**
