### PR TITLE
Implementation of 2017 MVA Electron ID : 94X MiniAOD

### PR DESCRIPTION
**Pull request by lsoffi**
Already reviewed and merged in the master (PR #21838) 
Link to PR #21838: https://github.com/cms-sw/cmssw/pull/21838

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by Sam-Harper** [comment]
bump to do a test: "please test with cms-sw/cmsdist#3763", thanks

**Comment by perrotta** [comment]
please test with cms-sw/cmsdist#3763

**Comment by perrotta** [comment]
please test with cms-sw/cmsdist#3774

**Comment by smuzaffar** [comment]
please test with cms-sw/cmsdist#3774
no idea why addon test failed, lets re-try

**Comment by slava77** [comment]
@smuzaffar 
it looks like the bot is again comparing to 9_4_X instead of 9_4_MAOD_X.
Perhaps "please test with cms-sw/cmsdist#xyz" triggers a different logic.
Please check and post a message when the fix is available.
Thank you.

**Comment by Sam-Harper** [comment]
Just realised I hadnt synced this branch with the master changes, pushing the update now

**Comment by smuzaffar** [comment]
@slava77 , cms-bot is updated to use correct 9.4.MAOD release for comparison.

**Comment by perrotta** [comment]
please test with cms-sw/cmsdist#3774
(to get rid of possible spurios differences due to the release used for comparisons)

**Comment by perrotta** [comment]
This PR is identical to #21838 already merged in the master, and ready to be accepted also in CMSSW_9_4_MAOD_X as soon as the needed external update will also get merged.

However, I see that still what was requested in https://github.com/cms-sw/cmssw/pull/21838#issuecomment-364865341 is not done yet, not even in the master.

(@guitargeek, @lsoffi @Sam-Harper ) Please report about the plans of the group about:
- Adding the new mvaElectronID_Fall17_* ids to the miniAOD_tools.py, so that the output can be retrieved in miniAOD
- Remove the unused ids from ElectronMVAValueMapProducer_cfi.py (if any), so that they do not get included in the reco sequence and do not uselessly waste computing resources

This has still to be done in the master (I guess: otherwise just point out the PR submitted with it), but it is even more important in a miniAOD production release

**Comment by Sam-Harper** [comment]
@perrotta:
This is done in PRs
https://github.com/cms-sw/cmssw/pull/22308 : 101X
https://github.com/cms-sw/cmssw/pull/22309:  94X for miniAOD

**Comment by perrotta** [comment]
Thank you @Sam-Harper : I should have found it myself, but it is good to have here a reference.

I can't find the (possible) cleaning of the reco sequence: could you please point me to where it is done instead, or alternatively comment about why it is not needed? I mean: do we need to process "Fall17" ids also for older data/MC, or alternatively do we still need to run the old ids in the new data?

**Comment by Sam-Harper** [comment]
@perrotta, oh no problem, its tricky with everything flying about, we will try to document better.

So right now, I'm just talking about re-miniAOD V2 which I now realise you might not be.  In the re-miniAOD V2, they are removed. In reconstruction proper that hasnt happened yet but will soon for CMSSW_10_1_X deadline (some triage is on going right now). 

The old ids are removed and new ones added here:
https://github.com/cms-sw/cmssw/pull/22308/files#diff-76dede28e7751d7bb6c5c9542de4155c

and then this file removes the values from going into the pat::Electrons/Photons:
https://github.com/Sam-Harper/cmssw/blob/0907db7305731609efea7d17440f91aabe15c623/RecoEgamma/EgammaTools/python/egammaObjectModificationsInMiniAOD_cff.py

E/gamma would like both 2016 and 2017 IDs run for both 2016 + 2017 MC. Its useful for studies and debugging.

**Comment by perrotta** [comment]
Looking at a config dump, the following ElectronMVAEstimator's are run in the reco step of the standard productions:
```
        mvaName = cms.string('ElectronMVAEstimatorRun2Phys14NonTrig'),
        mvaName = cms.string('ElectronMVAEstimatorRun2Spring15NonTrig'),
        mvaName = cms.string('ElectronMVAEstimatorRun2Spring15Trig'),
        mvaName = cms.string('ElectronMVAEstimatorRun2Spring15Trig'),
        mvaName = cms.string('ElectronMVAEstimatorRun2Spring16HZZ'),
        mvaName = cms.string('ElectronMVAEstimatorRun2Spring16GeneralPurpose'),
        mvaName = cms.string('ElectronMVAEstimatorRun2Fall17NoIso'),
        mvaName = cms.string('ElectronMVAEstimatorRun2Fall17Iso'),
```
which is exactly what coded in ```RecoEgamma/ElectronIdentification/python/ElectronMVAValueMapProducer_cfi.py```

I wonder if they are all needed: probably "2014" and "2015" ones are not, according to what you say. If so, removing them from the list could avoid running them uselessly (if I understand correctly how things work here...)

**Comment by Sam-Harper** [comment]
Ah thanks, I had missed that those were still being run. Its like playing wack a mole trying to kill them, thanks! Will update the main PR

**Comment by perrotta** [comment]
Thank you Sam!

Sam-Harper <notifications@github.com> ha scritto:

**Comment by perrotta** [comment]
+1
- Identical to #21838 in the master
- It backports the 2017 MVA electron ids to 94X for re-miniAOD
  - The needed external #3774 has just been merged
- It has to be complement (before closing the release= by the enabling of those IDs in the miniAOD output and the removal of the outdated ones from the reco sequence as implemented in #22309 (or in a possible evolution of the same...)

**Comment by fabiocos** [comment]
+1

**Pull request merged**
