### PR TITLE
Removed use of auto_ptr in CalibrationHistograms

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

Switched to std::make_unique.
This is part of a campaign to remove std::auto_ptr.

#### PR validation:

Code compiles.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
@makortel FYI

**Comment by Dr15Jones** [comment]
please test

**Comment by tjavaid** [comment]
+1

**Comment by rappoccio** [comment]
+1

**Pull request merged**
