### PR TITLE
Updated Phase 1 BPIX Geometry

### PR DESCRIPTION
**Pull request by leaca**
Changes to BPIX Phase 1 geometery to match latest design.

### CODE REVIEW

**Comment by friccita** [comment]
I would like to point out that the geometry modifications in this PR (which involve some old BPIX material definitions) should not overwrite the modifications to the BPIX module cable materials submitted in PR #14700. Maybe this is a redundant comment and the two pull requests will not clash with each other, but please let me know in case there is any conflict.

**Comment by makortel** [comment]
For my education, do the changes in this PR impact also reco geometry and/or alignment (for consistency with sim geometry)? (essentially repeating my question in https://github.com/cms-sw/cmssw/pull/14700#issuecomment-222951118)

**Comment by friccita** [comment]
@makortel The positions of the BPIX modules have been slightly shifted due to the increase in the thickness of the CFK facets; also, the thickness of the ROCs has been corrected.

**Comment by makortel** [comment]
Thanks @friccita, so IIUC there would be small inconsistency in pixel cluster positions if alignment/reco geometry are not updated consistently. Then the impact on (runTheMatrix) 2017 workflows depends on the outcome of the discussion in #14545 if we get soon a solution for moving the 2017 workflows to read the geometry from DB.

@mmusich @ghellwig @boudoul @veszpv

**Comment by mmusich** [comment]
@makortel I think the discussion in #14545 is conveerging in getting the Hcal geometry factored out (i.e. consistent with the current value of the calibrations). At that point we could drop the explicit dependence on the xml.
At any rate, when this is update is going to be available in DB as a new geometry tag, updating the alignment can follow rather trivially (always keeping it to the ideal reco geometry, for the time being).

**Comment by ianna** [comment]
please test

**Comment by makortel** [comment]
@mmusich Sounds good to me.

**Comment by ianna** [comment]
+1

**Comment by ianna** [comment]
@leaca - are these final changes for Pixel Phase 1 geometry? If not, what's the timescale for updates?

**Comment by friccita** [comment]
@ianna These changes are not final; they are part of the first round of modifications to make the Phase I Pixel description more accurate and have a working description by this month that may contain some inaccuracies but is still usable for simulation. The timescale for final updates is still under discussion.

**Comment by makortel** [comment]
Interestingly the limited-stats PR comparison shows increase in number of pixel hits/layers in barrel

https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_8_1_X_2016-05-31-2300+14726/14283/10024.0_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2017_GenSimFull+DigiFull_2017+RecoFull_2017+HARVESTFull_2017/Tracking__Track_general_trackingParticleRecoAsssociation_PXLlayersWithMeas_vs_eta.png

https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_8_1_X_2016-05-31-2300+14726/14283/10024.0_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2017_GenSimFull+DigiFull_2017+RecoFull_2017+HARVESTFull_2017/Tracking__Track_general_trackingParticleRecoAsssociation_PXBhits_vs_eta.png

To repeat myself, given that the last phase1 tracking PR #14643 got merged after 810pre6, I think it would make the pre7 (assuming this PR gets merged there) validation a lot easier if these geometry changes could be decoupled from code changes. I.e. I hope the solution discussed in #14545 would be in place by then.

**Comment by davidlange6** [comment]
@leaca - could you change the PR title to be more descriptive of the changes? Thanks
(just click edit at the top right of the page)

**Comment by ianna** [comment]
@makortel - to get appropriate tags from DB, please, use the following customization:
```
    toGet = cms.VPSet(cms.PSet(record = cms.string('GeometryFileRcd'),
                               tag = cms.string('XMLFILE_Geometry_81YV5_Extended2017_mc'),
                               connect = cms.string("frontier://FrontierProd/CMS_CONDITIONS")),
                      cms.PSet(record = cms.string('IdealGeometryRecord'),
                               tag = cms.string('TKRECO_Geometry_81YV5'),
                               connect = cms.string("frontier://FrontierProd/CMS_CONDITIONS")),
                      cms.PSet(record = cms.string('PGeometricDetExtraRcd'),
                               tag = cms.string('TKExtra_Geometry_81YV5'),
                               connect = cms.string("frontier://FrontierProd/CMS_CONDITIONS")),
                      cms.PSet(record = cms.string('PTrackerParametersRcd'),
                               tag = cms.string('TKParameters_Geometry_81YV5'),
                               connect = cms.string("frontier://FrontierProd/CMS_CONDITIONS"))
                      )

```
81YV5 version includes:
 * Extended 2017 scenario with Hcal geometry changes for 2016a 
 * New BPIX module cable materials, new FPIX portcard material and dimensions
 * Changes to BPIX Phase 1 geometry to match latest design

81YV4 version includes:
 * Extended 2017 scenario with Hcal geometry changes for 2016a 
 * New BPIX module cable materials, new FPIX portcard material and dimensions

81YV3 version is already in 81X_upgrade2017_*_v1 GTs and includes:
 * Extended 2017 scenario with Hcal geometry changes for 2016a

**Comment by mmusich** [comment]
thanks @ianna for preparing all the intermediate payloads. 
The next step IMHO (once https://github.com/cms-sw/cmssw/pull/14748 gets approved) is to propagate these in Global Tag (and in the pixel alignment as well).
@makortel should we do it in steps or shall I aim directly to V5 version?

**Comment by mmusich** [comment]
@ianna, in the light of https://github.com/cms-sw/cmssw/pull/14700#issuecomment-223333300, does this mean `81YV4` and `81YV5` need to be discarded? Thanks for the clarification.

**Comment by makortel** [comment]
@mmusich I'm running some tests with #14748 and #14749 (essentially to see how well my understanding of the situation corresponds to reality). I'll comment further after I'm finished, but tentatively, as far as tracking is concerned, it would probably be enough to have GlobalTags with V3 and V5 (i.e. skip V4). 

I let DPG (@boudoul @veszpv) to comment if they would like to have it more fine-grained ("it" referring mostly to validation, I guess).

**Comment by ianna** [comment]
@mmusich - no, as it does not affect 2017 GT. The problem shows for 2023 geometry, these workflows do not use geometry from GTs yet. BTW, what is the plan/timescale for creating a 2023 GT queue?

**Comment by mmusich** [comment]
@ianna it's definitely on our radar, but it has not yet hit the top of the list :) 
By the way most of the hcal conditions are hardcoded in 2023 workflows at this point. What would be the immediate benefit of having the 2023 queue?

**Comment by ianna** [comment]
@mmusich - an immediate benefit would be a significant performance improvement for HGCal geometry. However, new schemas for HGCal parameters and geometry need to be added. The code exists in CMSSW.

**Comment by mmusich** [comment]
@ianna please clarify "performance improvement for HGCal geometry". If the geometry is available in the DB, RelVals configuration can be customized to consume it.

**Comment by ianna** [comment]
@mmusich - yes, you are right, but it would be nice to avoid customisations. Besides they would have to be updated as the tags would be hardcoded (as a GT queue). I guess, it's the question who does the work load. In any case, I'll update the 2023 payloads for 810 release.

**Comment by mmusich** [comment]
@ianna, all right. I'll keep that in mind and try to provide the queue by the end of the cycle.

**Comment by makortel** [comment]
@mmusich I have tested workflow 10024 in CMSSW_8_1_X_2016-06-01-1100 (i.e. before the first pixel geometry change #14700). Let me refer below #14748 as "GT" and #14749 as "Geom"

I compared the produced DQM files from the following cases
1. IB + Geom
2. IB + Geom step2 with IB+Geom+GT step3
3. IB + Geom + GT

Cases 1 and 2 show perfect agreement, while 3 is different (tracking plots look statistically compatible but with only 10 events it is difficult to judge). Should the geometry from GT be "binary-equivalent" to geometry from XML? I.e. if everything is correct, should geometries from GT and XML be interchangeable to the level that Geant would yield same random number sequence?


I also compared (actually first)
4. IB
5. IB step2 with IB+GT step3
6. IB + GT

Cases 4 and 5 provide almost equal results, only change in tracking (in 10 events) coming from jetCore iteration, possibly related to the difference in HCAL geometry between IB (XML) and GT (that should be fixed in #14749 IIUC). Obviously case 6 was, again, much more different.

**Comment by ianna** [comment]
@makortel - geometry from xml and GT should be identical, e.g. the second is a dump of the first.

**Comment by makortel** [comment]
@ianna Is there an easy way for me to compare ("diff") the geometries from XML and GT? (to double-check my test 3 in https://github.com/cms-sw/cmssw/pull/14726#issuecomment-223585443)

**Comment by mmusich** [comment]
@ianna can you check that what we had in the IB (i.e. via xml) is the same we have in the GT?
i.e.:
```
GeometryFileRcd:  (label Extended) XMLFILE_Geometry_81YV3_Extended2017_mc                
IdealGeometryRecord: TKRECO_Geometry_2017_75YV1                                                                                     
PGeometricDetExtraRcd:   TKExtra_Geometry_2017_75YV1  
TrackerParametersRcd: TKParameters_Geometry_2017_75YV1                                                              
```

**Comment by ianna** [comment]
@mmusich - I'll re-check.

@makortel - There are instructions here https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideXMLToDatabaseRTValidation?redirectedfrom=CMS.SWGuideXMLToDatabaseRTValidation

**Comment by ianna** [comment]
@mmusich - Identical as expected. I run comparison between Extended2017 geometry:
  
 1. xml definition as in CMSSW_8_1_X_2016-06-01-1100 with #14749 
 2. Extended geometry XMLFILE_Geometry_81YV3_Extended2017_mc from GT using the same IB and asking for it explicitly:
```
process.GlobalTag = GlobalTag(process.GlobalTag, '81X_upgrade2017_realistic_v1', '')
```
You can see the results here:

cmsdev03:/build/yana/PIXELPII/CMSSW_8_1_X_2016-06-01-1100/src/GeometryReaders/XMLIdealGeometryESSource/test

I used the following configuration files:
```
cmsRun extract2017XMLFile.py
cmsRun read2017BigXMLAndDump.py
cmsRun readExtended2017AndDump.py
cmsRun testCompareDumpFiles.py
```

**Comment by mmusich** [comment]
thanks @ianna for the check and for the recipe! That's very welcome.

**Comment by ianna** [comment]
@makortel - Just an idea - it could be that cmsDriver has different configurations when it runs on geometry from xml vs GT. You can check it comparing expanded configurations with edmConfigDump.

**Comment by makortel** [comment]
@ianna Diffing `edmConfigDump`s didn't reveal anything striking (I put the diff here https://mkortela.web.cern.ch/mkortela/tracking/diff_xml_gt.txt in case somebody else wants to take a look).

I can confirm that @ianna's recipe in https://github.com/cms-sw/cmssw/pull/14726#issuecomment-223606237 does not report any differences between XML and GT geometries. I also tried to diff the textual dumps (`dumpSTD` and `dumpBDB`), but diff reports differences at least because of `0.0` vs `-0.0` and because of the grouping diff does I have not been able to compare line-by-line (and I haven't yet tried to compare individual lines with a custom script).

But already this observation makes me wonder if the test machinery has some tolerance in the comparisons (and in `testCompareDumpFiles.py` I can see `process.comparedddump.tolerance`? In my experience with Geant4 to have full reproducibility one needs everything to be bitwise identical, otherwise the random number sequences may start to diverge after some comparison somewhere being different.  Differences of `0.0` vs. `-0.0` in the text dumps indicate that at least for zero there are bit-level differences.

If the test machinery has tolerances, is there an easy way to reduce them in order to make a(n almost) bitwise comparison?

**Comment by ianna** [comment]
@makortel - The default tolerance is set to 0.000001
You can try to play with it.

**Comment by makortel** [comment]
@ianna I set the `process.comparedddump.tolerance` in your `testCompareDumpFiles.py` to `1e-18` (to cover even smallest numerical difference of double, assuming the tolerance is compared to relative difference). 

I put the result here
https://mkortela.web.cern.ch/mkortela/tracking/diff_testCompareDumpFiles_xml_gt.txt 
There are differences like
```
 - /cms:OCMS[0]/cms:CMSE[1]/tracker:Tracker[1]/tec:TEC[1]/tec:TECWheels[1]/tecwheela:TECWheelA[0]/tecpetal0f:TECPetalCont0F[1]/tecring6f:TECRing6F[1]/tecmodule6:TECModule6[3]/tecmodule6:TECModule6RphiWafer[1]/tecmodule6:TECModule6RphiActive[1]/tecmodule6:TECModule6RphiInactive[1] coordinate x  is different by:     0.0001000 mm
...
 - /cms:OCMS[0]/cms:CMSE[1]/caloBase:CALO[1]/eregalgo:ECAL[1]/eregalgo:EREG[1]/eehier:ENCA[1]/eehier:EEDee[1]/eehier:EEFrontDee[1]/eehier:EEFrontQuad[1]/eregalgo:EESCEnv1[103] coordinate y  is different by:     0.0001000 mm
...
 - /cms:OCMS[0]/cms:CMSE[1]/forward:CastorB[2]/castor:CASTFar[1]/castor:CAST[3]/castor:CEDC[1]/castor:CEDS[1]/castor:CEDR[1]/castor:CEAL[2] coordinate x  is different by:     0.0001000 mm 
...
 - /cms:OCMS[0]/cms:CMSE[1]/zdc:ZDC[1]/zdc:ZDC_HadLayer[1]/zdc:ZDC_HadFiber[1] coordinate x  is different by:     0.0001000 mm 
...
 - /cms:OCMS[0]/cms:CMSE[1]/zdc:ZDC[1]/zdc:ZDC_EMLayer[1]/zdc:ZDC_EMFiber[1] coordinate x  is different by:     0.0001000 mm 
```
I guess these would explain the differences in Geant4 output (https://github.com/cms-sw/cmssw/pull/14726#issuecomment-223585443). Could you take a look again?

**Comment by ianna** [comment]
@makortel - it looks very much like a numeric error. The difference is always the same for all coordinates. I'll have a look. BTW, we compare ASCII file produced from a file BLOB, so it could be just formatting in a geometry dump class (which is used in tests only):
http://cmslxr.fnal.gov/source/DetectorDescription/OfflineDBLoader/src/GeometryInfoDump.cc?v=CMSSW_8_1_X_2016-06-08-2300#0048

Also, it is the same FileBlob class which writes the file BLOB out and reads it in. I'd be surprised if it would produce different results as it also used in alignment and calibration.

To use diff on SpecPar dumps you need to sort them first.

**Comment by makortel** [comment]
Thanks @ianna. Sorting the dumps didn't really help, because I have e.g. in dumpSTD
```
 - /cms:OCMS[0]/cavern:OSFL[1],      0.0000,  -9300.0000,      0.0000,      1.0000,     -0.0000,     -0.0000,     -0.0000,      1.0000,     -0.0000,     -0.0000,     -0.0000,      1.0000
```
and in dumpBDB
```
 - /cms:OCMS[0]/cavern:OSFL[1],      0.0000,  -9300.0000,      0.0000,      1.0000,      0.0000,      0.0000,      0.0000,      1.0000,      0.0000,      0.0000,      0.0000,      1.0000
```
and diff considers `0.0000` to be different from `-0.0000` and therefore marks the two files almost completely different.

**Comment by ianna** [comment]
@makortel - According to the IEEE standard -0/+0 differ only in the sign bit (the rest are 0). I would not think saving the sign for x==0, y==0, and z==0 in position and/or rotation is important. 

@VinInn aand @civanch - Please, confirm. Do we care about preserving a sign for x, y, or z equal -0.0? Would it make any affect on G4? It looks like -0.0 is converted to 0.0 by  
http://cmslxr.fnal.gov/source/CondFormats/Common/src/FileBlob.cc?v=CMSSW_8_1_X_2016-06-08-2300#0068

**Comment by makortel** [comment]
@ianna My impression too is that the sign bit of 0 should make no difference for the floating point calculations. My point was that it does make a different for `diff` that uses the text representation, and because of that `diff` thinks the two dumps are almost completely different. And because of that I did not bother to look from `diff` output if there were any real difference between the dumps (because `diff` didn't make the comparison any easier).

**Comment by friccita** [comment]
Hello all, what is the status of the comparisons/checks? Are there any remaining issues to investigate before this PR can be merged?

**Comment by makortel** [comment]
@ianna Any news?

@friccita Actually I think our discussion and checks are related more to already-merged #14748 (switching 2017 workflows to use geometry from DB than from XML) than this PR. I guess it's a bit of an accident that we do it here.

**Comment by boudoul** [comment]
There was at least the request (see comments above) to change the title to a more explicit one

**Comment by davidlange6** [comment]
regardless of the checks, the title of the PR needs to be updated to be descriptive of the changes. (as commented earlier, but likely lost in the other discussion of the thread)

**Comment by leaca** [comment]
I now changed the title of the PR. (Sorry I missed this comment...)

**Comment by davidlange6** [comment]
@makortel @ianna - just to clarify - is there some remaining issue with this pr (e.g., GT?)?

**Comment by makortel** [comment]
@davidlange6 I'm fine with this PR.

As I mentioned in https://github.com/cms-sw/cmssw/pull/14726#issuecomment-226118420, my concerns were in XML vs. DB geometry, i.e. more related to #14748 (already merged).

**Comment by mmusich** [comment]
@makortel, still at the moment the geometry is steered via DB (Global Tag) and if this gets merged the XML will go out-of-synch with the DB (in this case I think also the alignment). 
Since you are going to have two sets of RelVals (also with the updated conditions from #14925, even if they are not merged yet... ), shall we target to have this merged in pre8 together with the updated Geometry (and Tracker Alignment) in Gobal Tag (containing the V5 payloads from @ianna cfr https://github.com/cms-sw/cmssw/pull/14726#issuecomment-223331136 )?

**Comment by makortel** [comment]
> shall we target to have this merged in pre8 together with the updated Geometry (and Tracker Alignment) in Gobal Tag (containing the V5 payloads from @ianna cfr #14726 (comment) )?

@mmusich I think that would be a good plan. Then in pre8 I'd like to get again two sets for RelVals, but I don't have preference between

* "pre8+default GT" for previous geometry
* "pre8+updated GT" for updated geometry

(as happened with pre7), or 
* "pre8+old GT" for previous geometry
* "pre8+default GT" for updated geometry

(which way I interpret your "pre8 together with updated geometry+alignment in GT").

**Comment by davidlange6** [comment]
@mmusich - is this plan ok for you?

**Comment by mmusich** [comment]
@davidlange6 either plan is fine with me, as long as Matti is happy (i.e. can have separate relvals to test step by step). 
Please just let me know if I need to provide the updated phase-I Global Tags with the "V5" geometry for pre8.

**Comment by davidlange6** [comment]
@mmusich  - so I'll merge this into pre8 - then we can make a new GT for testing the new geometry (to be merged before pre9)

**Comment by mmusich** [comment]
@davidlange6 sounds good. We'll prepare updated GTs with geometry/alignment with the latest geometry for pre9.

**Comment by makortel** [comment]
@ianna

> @ianna for my education, do we expect that going from the 81YV4 version of the geometry to the 81YV5 an effect on the position of the center of the Pixel modules sensors (which is what we store in the alignment record)?

Now that I have the validation plots for this update at hand, I'd like to get an answer to @mmusich's question (thanks for reminding). The plots show large changes (tracking efficiency decreases), and the possible shift in pixel module positions could be one source.

**Comment by makortel** [comment]
While waiting for @ianna to comment, an earlier comment by @friccita https://github.com/cms-sw/cmssw/pull/14726#issuecomment-223050405 says that there were movements in BPix module positions. @mmusich, I'm wonderding if alignment group has any hint/evidence for the opposite?

**Comment by mmusich** [comment]
@makortel,I'll let @ghellwig comment, since he's performed the chek, but comment https://github.com/cms-sw/cmssw/pull/14726#issuecomment-223050405 doesn't imply that the center of the module sensitive areas are moved, just that module thicknesses have been changed.

**Comment by ghellwig** [comment]
@mmusich, @makortel if you are referring to the check I did some time ago, the outcome was that both alignment payloads were exactly identical. I obtained the positions and rotations with [this code](https://github.com/cms-sw/cmssw/blob/CMSSW_8_1_X/Alignment/TrackerAlignment/plugins/CreateTrackerAlignmentRcds.cc#L236-L276), so you might check if the method is wrong on my side.

**Comment by makortel** [comment]
Thanks @ghellwig! I think we need then an explicit comment from @ianna, @friccita, or some other geometry expert if "the center of the module sensitive areas" are changed or not.

It is just that the large efficiency decrease http://cmsdoc.cern.ch/cms/Physics/tracking/validation/MC/CMSSW_8_1_0_pre8_phase1_newGT/81X_upgrade2017_realistic_v4_UPG17PU35newGT_PU_ootb_25ns/RelValTTbar/effandfake1.pdf would be much easier to explain with a mismatch between SIM geometry and alignment than from mismatch between SIM and reco material. I guess we need to update the reco material with the changes of this PR too and see what happens (@rovere's help would be much appreciated).

**Comment by ianna** [comment]
@makortel - how do efficiency plots compare with the GT ones if you run from xml files?

**Comment by ianna** [comment]
Here is what I see when comparing an aligned Tracker geometry from a default upgrade2017 GT with an ideal Tracker geometry (without alignment) built from XML:
screen shot 2016-07-19 at 15 55 14
screen shot 2016-07-19 at 15 55 30

**Comment by ianna** [comment]
Here is a comparison between an ideal Tracker geometry from a default upgrade2017 GT (without alignment) with an ideal Tracker geometry (without alignment) built from XML:
screen shot 2016-07-19 at 16 07 37
screen shot 2016-07-19 at 16 07 49

**Comment by mmusich** [comment]
@ianna, just to clarify:
when you mention default 2017 upgrade GT you mean one of those two:
```
'phase1_2017_design' :  '81X_upgrade2017_design_v4',
'phase1_2017_realistic': '81X_upgrade2017_realistic_v4',
```
?
and the XML is the updated one after this PR?

**Comment by makortel** [comment]
@ianna Many thanks for the checks. Could you clarify which pre-release(/IB) you used? (mainly, XML of which release vs. which exact GT)

> how do efficiency plots compare with the GT ones if you run from xml files?

Based on your second plots (https://github.com/cms-sw/cmssw/pull/14726#issuecomment-233645037), I'll first test re-reco with geometry without alignment (much faster than re-SIM thus allowing me to run more events in a sensible time)

**Comment by ianna** [comment]
Access to DB geometry in CMSSW_8_1_X_2016-07-19-0900:
```
 process.load("Configuration.StandardSequences.FrontierConditions_GlobalTag_cff")
 from Configuration.AlCa.autoCond import autoCond
 process.GlobalTag.globaltag = autoCond['upgrade2017']
 process.load("Configuration.StandardSequences.GeometryDB_cff")
 process.trackerGeometryDB.applyAlignment = cms.bool(False)
```
Access to XML geometry:
```
process.load('Configuration.Geometry.GeometryExtended2017_cff')
process.load('Configuration.Geometry.GeometryExtended2017Reco_cff')
process.load('Geometry.TrackerGeometryBuilder.trackerParameters_cfi')
process.trackerGeometry.applyAlignment = cms.bool(False)
```

**Comment by mmusich** [comment]
@ianna, thanks for providing the recipe. 
The 
```
process.load("Configuration.StandardSequences.GeometryDB_cff")
process.trackerGeometryDB.applyAlignment = cms.bool(False)
```
applies only on the second set of plots, right?

**Comment by ianna** [comment]
@mmusich - yes, it's for the second set of plots

**Comment by mmusich** [comment]
@ghellwig I think we can draw the following conclusions: 

   * comment https://github.com/cms-sw/cmssw/pull/14726#issuecomment-233642611 demonstrates there is some inconsistency between the pixel alignment object in GT and the pixel geometry in XML.
   * comment https://github.com/cms-sw/cmssw/pull/14726#issuecomment-233645037 demonstrates that the pixel geometry from DB is consistent with the one in XML.

This would point to a flaw in the code used to replicate the alignment payload from the geometry in DB that you mentioned in  https://github.com/cms-sw/cmssw/pull/14726#issuecomment-233616935. Would you agree with that?

**Comment by ghellwig** [comment]
@mmusich yes I draw the same conclusions... I will once again run the tool with `81X_upgrade2017_design_v4` and `81X_upgrade2017_realistic_v4` to make sure, that I did not use the wrong input geometry.
@ianna do you see an obvious mistake in the code in https://github.com/cms-sw/cmssw/pull/14726#issuecomment-233616935 ?

**Comment by makortel** [comment]
@ghellwig Sorry for naive question, but are you planning to compare `81X_upgrade2017_design_v4` to `81X_upgrade2017_realistic_v4`, or `81X_upgrade2017_*_v4` to `81X_upgrade2017_*_v3`?

**Comment by ghellwig** [comment]
@makortel as I understood v3 and v4 are identical in terms of alignment payloads, but different in terms of geometry payloads. If the tool works as expected, I would expect different alignment payloads obtained with the tool using the different GTs. Is this correct or did I miss something here?

**Comment by ghellwig** [comment]
@makortel sorry, just realized that I did not explicitely answer the actual question: I plan a comparison of v3 vs. v4

**Comment by ianna** [comment]
@ghellwig - I used the following analyser with minor modifications to validate only tracker geometry: http://cmslxr.fnal.gov/source/Fireworks/Geometry/plugins/ValidateGeometry.cc?v=CMSSW_8_1_X_2016-07-18-2300

Step 0: Take the version where only Tracker can be analysed:
git cms-merge-topic ianna:fw-validate-geometry-by-subdet

Step 1: Dump geometry to root file with Fireworks/Geometry/python/dumpRecoGeometry_cfg.py. Please, modify it to make sure it is the right one:
```
49,52c49
<        process.load("Configuration.StandardSequences.GeometryDB_cff")
<        process.trackerGeometryDB.applyAlignment = cms.bool(False)
< 
< ##       process.load('Configuration.Geometry.GeometryExtended2017Reco_cff')
---
>        process.load('Configuration.Geometry.GeometryExtended2017Reco_cff')
```
```
cmsRun Fireworks/Geometry/python/dumpRecoGeometry_cfg.py tag=2017 tracker=true muon=false calo=false
```

Step 2: Run validation analyser with the following configuration:
```
import FWCore.ParameterSet.Config as cms

process = cms.Process('VALID')

##process.load('Configuration.StandardSequences.GeometryDB_cff')
##process.load('Configuration.StandardSequences.FrontierConditions_GlobalTag_cff')
##from Configuration.AlCa.autoCond import autoCond
##process.GlobalTag.globaltag = autoCond['mc']
process.load('Configuration.Geometry.GeometryExtended2017_cff')
process.load('Configuration.Geometry.GeometryExtended2017Reco_cff')
process.load('Geometry.TrackerGeometryBuilder.trackerParameters_cfi')
process.trackerGeometry.applyAlignment = cms.bool(False)
process.TrackerGeometricDetExtraESModule = cms.ESProducer( "TrackerGeometricDetExtraESModule",
                                                           fromDDD = cms.bool( True )
                                                           )
process.source = cms.Source('EmptySource')

process.maxEvents = cms.untracked.PSet(
    input = cms.untracked.int32(1)
    )
#
# Note: Please, download the geometry file from a location
#       specified by Fireworks/Geometry/data/download.url
#
# For example: wget http://cmsdoc.cern.ch/cms/data/CMSSW/Fireworks/Geometry/data/v4/cmsGeom10.root
#
process.valid = cms.EDAnalyzer("ValidateGeometry",
                               infileName = cms.untracked.string('cmsRecoGeom-2017.root'),
                               outfileName = cms.untracked.string('validate2017Geometry.root'),
                               Tracker = cms.untracked.bool(True),
                               Muon = cms.untracked.bool(False),
                               Calo = cms.untracked.bool(False)
                               )

process.p = cms.Path(process.valid)

```

Note, there will be some misleading histograms on topology comparison because the analyser uses hardcoded numbers for local to global conversion based on run 1 pixel detector - these were defined for a standalone event display. Just ignore these for now.

**Comment by ghellwig** [comment]
@ianna thanks!

**Comment by ghellwig** [comment]
@makortel, @ianna I found the problem.
The reason was a configuration problem for the tool mentioned above. When aligning to the strip part of the alignment payload, I need to exclude the pixel part.
Previously it was done by `PixelBarrel` and `PixelEndcap` and now it is `P1PXB` and `P1PXEC`. With the wrong configuration I ended up with everything from the previous alignment payloads in the new payloads.
@mmusich is already preparing a new GT containing the corrected payloads.
@makortel can you please wait with your tests until the updated GT arrives?

**Comment by mmusich** [comment]
Thanks @ghellwig @makortel @ianna for quick follow-up. 
PR https://github.com/cms-sw/cmssw/pull/15235 introduces the new corrected payloads.

**Comment by makortel** [comment]
Thanks @ghellwig for finding the cause, @ianna for the help, and @mmusich for the new GT.

@ghellwig At this point I'll probably stop my tests and ask directly for new RelVal.

**Comment by ghellwig** [comment]
@makortel thanks for insisting on additional checks!

**Pull request merged**
