### PR TITLE
Move EDProducers in HLT tracking validation sequences to Tasks

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

It appears I was too aggressive in https://github.com/cms-sw/cmssw/pull/29630 when moving all EDProducers and DQM modules from Sequences to Tasks in tracking validation configuration (https://github.com/cms-sw/cmssw/pull/29630/commits/d054368b008751c6fd5dff134e0259ae27d9a1ae). Moving also DQM modules (that are EDProducers using the Accumulator extension) to Tasks caused these modules to be run on each event even though the intention is to run them only if some EDFilter(s) keep the event. Therefore these DQM modules need to be kept in a Sequence (or in general, if a Sequence with Accumulators is (potentially) used also in conjunction with EDFilters that may reject events, the Accumulators should be kept in the Sequence).

The first commit in this PR reverts https://github.com/cms-sw/cmssw/pull/29630/commits/d054368b008751c6fd5dff134e0259ae27d9a1ae. The second commit is a more proper fix to the "unrunnable schedule" error I tried to fix with https://github.com/cms-sw/cmssw/pull/29630/commits/d054368b008751c6fd5dff134e0259ae27d9a1ae. The proposed fix is to move all non-Accumulator EDProducers from HLT tracking validation Sequences to Task (in offline tracking validation they pretty much all are already in Tasks).

Part of https://github.com/cms-sw/cmssw/issues/30074. Should fix all the workflows that failed with `SIBABRT` in https://github.com/cms-sw/cmssw/issues/30074 (the `abort()` itself is changed to an exception in #30082).

#### PR validation:

Limited matrix and workflows `135.9,2017.9,2018.9,25406.0,25406.17,25406.0,25406.17,25406.18` run.

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
type bug-fix

**Comment by makortel** [comment]
urgent

**Comment by jfernan2** [comment]
+1

**Comment by silviodonato** [comment]
+operations

**Comment by silviodonato** [comment]
@civanch @mdhildreth
I'm going to merge this fix in the next IB, if you have no objections.

**Comment by silviodonato** [comment]
merge

**Pull request merged**
