### PR TITLE
Step 1: Simulation Clang tidy code-checks-all

### PR DESCRIPTION
**Pull request by ianna**
* Split https://github.com/cms-sw/cmssw/pull/20511 as suggested by @civanch here https://github.com/cms-sw/cmssw/pull/20511#issuecomment-329464116:

Step 1. SimG4Core/SensitiveDetector + SimG4CMS + SimRomanPot

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by civanch** [comment]
@kpedro88 , please, have a look into this PR, for me it is clean

**Comment by davidlange6** [comment]
lets use the amended version

**Pull request closed without merging**
