### PR TITLE
Run3-gex70 Backport 2 PR's #33423 and #33424 to update 2021, 2026 scenarios

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Backport 2 PR's #33423 and #33424 to correct the 2021 scenario and , 2026 scenarios

#### PR validation:

Tested using the runTheMatrix test workflow 37434.0 and use scripts in SimG4Core/PrintGeomInfo/test/python

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Backport 2 PR's #33423 and #33424

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by srimanob** [comment]
test parameters:
- workflow = 37434.0

**Comment by srimanob** [comment]
Please test

**Comment by silviodonato** [comment]
+operations

**Comment by chayanit** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

**Comment by qliphy** [comment]
+1

**Pull request merged**
