### PR TITLE
Backport to CMSSW_13_0_X of new extended ParticleNet networks for jet classification, regression, and taus

### PR DESCRIPTION
**Pull request by scooperstein**
This pull request would backport the recently merged PR [here](https://github.com/cms-sw/cmssw/pull/40745) into CMSSW_13_0_X. This PR would add a variety of new performance improvements in jet flavor classification, jet energy regression, and tau ID and reconstruction that are important additions to include for Run-3 analyses. For many more details, please refer to the original PR. The code changes from the PR itself should be identical to those just merged in the master branch.

### CODE REVIEW

**Comment by simonepigazzini** [comment]
enable nano

**Comment by swertz** [comment]
please test with https://github.com/cms-data/RecoBTag-Combined/pull/50

**Comment by mandrenguyen** [comment]
backport of #40745

**Comment by swertz** [comment]
please test

**Comment by swertz** [comment]
test parameters:
pull_request = https://github.com/cms-data/RecoBTag-Combined/pull/50

(I'm confused because the above was merged... this should be usable by all CMSSW versions, no?)

**Comment by swertz** [comment]
test parameters:
pull_request = https://github.com/cms-data/RecoBTag-Combined/pull/50

**Comment by swertz** [comment]
please test

**Comment by perrotta** [comment]
tests seem stuck: try to restart them

**Comment by perrotta** [comment]
test parameters:
- pull_request = https://github.com/cms-sw/cmsdist/pull/8436

**Comment by perrotta** [comment]
https://github.com/cms-sw/cmsdist/pull/8436 backports https://github.com/cms-sw/cmsdist/pull/8422 to 13_0_X

**Comment by perrotta** [comment]
please test

**Comment by simonepigazzini** [comment]
I'm not sure of what is causing the failures. The changes in the PR should not affect those workflows.

**Comment by perrotta** [comment]
@simonepigazzini timeouts in RelValInputs workflows are quite common
Let retest, to see if we can get rid of them

**Comment by perrotta** [comment]
please test

**Comment by simonepigazzini** [comment]
+1

The changes are in line with the original PR. Signing this off from xpog

**Comment by mandrenguyen** [comment]
+1

**Comment by perrotta** [comment]
+1
- Only mini and nano involved with the addition of ParticleNet, ok to backport

**Pull request merged**
