### PR TITLE
Add scouting electron, photon, and muon classes and producers

### PR DESCRIPTION
**Pull request by davidsheffield**
The ScoutingMuon members `nMatchedStations_` and `type_` are needed for when we add tracker muons.

I created new `plugin` directories in `HLTrigger/Egamma` and `HLTrigger/Muon` to match the scouting jet producers in `HLTrigger/JetMET`. Let me know if the producers should be placed in the existing `src` directory.

### CODE REVIEW

**Comment by fwyzard** [comment]
-1

**Comment by fwyzard** [comment]
The plugins should be in the /src subdirectories.

**Comment by fwyzard** [comment]
> I created new plugin directories in HLTrigger/Egamma and HLTrigger/Muon to match the scouting jet producers in HLTrigger/JetMET. Let me know if the producers should be placed in the existing src directory.

If HLTrigger/JetMET also defines multipel plugins (under under /src and one under /plugins) they should be moved to a single directory.

**Comment by fwyzard** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Pull request merged**
