### PR TITLE
Change from numberOfMatches() to segment number in DisplacedMuonFilterProducer

### PR DESCRIPTION
**Pull request by vlimant**
#### PR description:

plain backport of #41496 to 13.0.X

### CODE REVIEW

**Comment by vlimant** [comment]
enable nano

**Comment by vlimant** [comment]
FYI @24LopezR

**Comment by vlimant** [comment]
please test

**Comment by 24LopezR** [comment]
Yes, changes are consistent with what is expected.
I had a quick look at the failed comparisons. First, I noticed an increase in DSA Muons (type=8), which is expected. See WF 25202.0:

c_patMuons_slimmedDisplacedMuons__RECO_obj_type

Also, from numberOfMatches() histogram we observe an increase of muons in the region <2, which is also expected since now the filter is not acting in that region anymore for DSAs. Together with this comes a decrease in the region >=2, because there are DSAs that passed the old filter and now they fail. See comparison from WF 136.793:

c_patMuons_slimmedDisplacedMuons__reRECO_obj_numberOfMatches

These are the same effects seen in #41496

**Comment by vlimant** [comment]
+1

**Comment by mandrenguyen** [comment]
backport of https://github.com/cms-sw/cmssw/pull/41496

Same comment as elsewhere, @cms-sw/orp-l2 do we backport to intermediate releases?

**Comment by mandrenguyen** [comment]
type muon

**Comment by mandrenguyen** [comment]
+1

**Comment by antoniovilela** [comment]
+1

**Comment by antoniovilela** [comment]
> backport of #41496
> 
> Same comment as elsewhere, @cms-sw/orp-l2 do we backport to intermediate releases?

Yes, please backport to the intermediate release cycles.

**Pull request merged**
