### PR TITLE
Add calibration fit plot to the PPS HPTDC PCL

### PR DESCRIPTION
**Pull request by ChrisMisan**
#### PR description:

New per-channel plot was added to the harvester, it allows to investigate produced calibration fit. Plot is saved together with all of the worker plots after the harvesting stage.

image

#### PR validation:
wfs 1041, 1044

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

backport to 12_5 and 12_4 will follow.

### CODE REVIEW

**Comment by ChrisMisan** [comment]
type ctpps, new-feature

**Comment by ChrisMisan** [comment]
test parameters:

- workflows=1041,1044

**Comment by ChrisMisan** [comment]
please test

**Comment by tvami** [comment]
+alca
 * 1041, 1044 wf-s pass

**Comment by perrotta** [comment]
+1

**Pull request merged**
