### PR TITLE
JETMET LumiFlag

### PR DESCRIPTION
**Pull request by iatakisi**
#### PR description:
we set lumiflag for only one plot which is MetSig

#### PR validation:
it shouldn't affect any normal DQM

### CODE REVIEW

**Comment by andrius-k** [comment]
please test

**Comment by schneiml** [comment]
@smuzaffar Question regarding the bot output for this PR ( https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_10_6_X_2019-05-06-1100+26655/31517/ ):

It seems that for some workflows, the workflow ran (there are log files) but there is no output directory. In this case I was looking for 136.8311 (JetHT data), but it also affects a few others. Is that expected behaviour?

**Comment by schneiml** [comment]
@fabiocos We'd like to have this small change in 10_6 to get per-lumisection saved plots for JETMET. They requested lumisection information for some quantities, and if we can't get it for all of DQM, we should have at least these plots.

**Comment by andrius-k** [comment]
+1

**Comment by fabiocos** [comment]
@schneiml I would say that the output directory should be there, @smuzaffar could confirm.
The PR in itself looks ok to be merged, I will just launch another test to see whether the comparison in the bot is triggered

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
+1

**Pull request merged**
