### PR TITLE
[RFC] First attempt at a "global" DQM analyzer 

### PR DESCRIPTION
**Pull request by fwyzard**
Use a wrapper around `MonitorElement` to handle concurrent filling via the `fill(...) const` and `shiftFillLast(...) const` methods.

All configuration of the underlying ROOT objects should to be done before booking the `MonitorElement` (e.g. via `book1D (const std::string &name, TH1F *h);`.
Or, we can add the non-`const` methods that are already avalable in the `MonitorElement` interface, though they are only a subset of the `TH1` methods.
In any case, no access to the underlying ROOT object pointer is provided.

Add a `ConcurrentBooker` class that inherits from `IBooker` and replace its `book...` methods to return `ConcurrentMonitorElements`; and a `DQMStore::bookConcurrentTransaction(...)` method that uses the `ConcurrentBooker` in place of the `IBooker`.

Add a new `DQMGlobalEDAnalyzer` inheriting from `edm::global::EDAnalyzer` instead of `edm::stream::EDAnalyzer`, and books "global" `MonitorElement`s (with stream id = 0 and module id = 0).
The user will need to provide a `class` or `struct` that can book and fill the histograms. Filling must be a `const` method, so one should make use of the `ConcurrentMonitorElement` just introduced.

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by fwyzard** [comment]
> c++: error: external/slc6_amd64_gcc630/objs-full/SimG4CoreCustomPhysics.obj: No such file or directory

seems rather unrelated to this PR.

**Comment by fwyzard** [comment]
@cmsbuild , please test

**Comment by fwyzard** [comment]
Let's see if there ia new IB which fixes the unrelated problem.

**Comment by fwyzard** [comment]
@cmsbuild , please abort

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by fwyzard** [comment]
Superseded by #21652.

**Pull request closed without merging**
