### PR TITLE
Fix signed muon tagger

### PR DESCRIPTION
**Pull request by ghost**
Fix in the muon tagger signed discriminators, which were filled always and not only when the signed lepton selection was actually fulfilled.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cmsbuild please test
looks like the results from the last round failed to be copied and comparisons appear incomplete

**Comment by cvuosalo** [comment]
+1

For #12937 5a75061cb3aa85f730de9ca699b3d0e7b73d82e2

Small bug fix to stop the signed muon tagger from being filled unless a signed lepton was actually selected. There should be no change in monitored quantities.

The code fix is satisfactory, and Jenkins [tests](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-12937/10512/summary.html) against baseline CMSSW_8_0_X_2016-01-13-2300 show no significant differences, as expected.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
