### PR TITLE
Pr81x fix duplicate tracks EMTF on top l1t-tsg-v9.2-post-O2O-pr

### PR DESCRIPTION
**Pull request by rekovic**
This is the 81x version of the 80x PR #15980.

Except that here in 81x, the l1t-tsg-9.2 has been fully merged, so what remains is only the fix in EMTF emulator to rid of duplicate tracks. Additional change from auto_ptr to unique_ptr is to sync with these changes made in 81x.
- STATUS: Pending blessing from L1T DPG.

### CODE REVIEW

**Comment by rekovic** [comment]
please test

**Comment by rekovic** [comment]
Blessed.  
With this fix applied, rates of multi-muon triggers agree in data/emul, plots shown at L1T DPG meeting today.

**Comment by rekovic** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
