### PR TITLE
add import FWCore.ParameterSet.Config as cms to top to fix unit tests

### PR DESCRIPTION
**Pull request by davidlange6**
#### PR description:

add import FWCore.ParameterSet.Config as cms to top to fix unit tests

#### PR validation:

Fixes 2 failing unit tests in the DEVEL IB

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by fabiocos** [comment]
please test

**Comment by davidlange6** [comment]
hi @ggovi - could this PR move forward? its trivial. Thanks

**Comment by fabiocos** [comment]
+1

trivial technical fix

**Comment by fabiocos** [comment]
merge 

@ggovi please sign it for reference or comment in case you see an issue with that

**Comment by ggovi** [comment]
+1

**Pull request merged**
