### PR TITLE
Migrate 4D vertexing and downstream reco to full simulation/reconstruction track timestamps and add TOF PID (10_4_X)

### PR DESCRIPTION
**Pull request by bendavid**
Backport of https://github.com/cms-sw/cmssw/pull/25628

### CODE REVIEW

**Comment by bendavid** [comment]
Master version is here
https://github.com/cms-sw/cmssw/pull/25628

**Comment by kpedro88** [comment]
backport of #25628

**Comment by bendavid** [comment]
Keeping in sync with master PR

**Comment by andrius-k** [comment]
please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/25627	75d66ac
- code changes are the same as in  the master version (https://github.com/cms-sw/cmssw/pull/25628	bbff806 )
- jenkins tests pass and comparisons with the baseline show differences only in the affected MTD workflow 27434

**Comment by fabiocos** [comment]
@andrius-k @kpedro88 as for master

**Comment by andrius-k** [comment]
+1

**Comment by fabiocos** [comment]
@kpedro88 I move forward with integration in order to speed up the release, as this looks the correct backport of what already approved in master. Please sign it in case for reference

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Comment by kpedro88** [comment]
@fabiocos usually I wait to sign backports until they have survived in a master IB, in case of surprises...

**Comment by fabiocos** [comment]
@kpedro88 I agree that this is the normal meaningful procedure, as here we are quite late I tried to get prepared in case of success, given that 10_4_X is dedicated only to this particular purpose and nothing else. Anyway as you may see in master this is not the end of the story...

**Pull request merged**
