### PR TITLE
improving dynamic inefficiency monitoring (Rebase of #23061)

### PR DESCRIPTION
**Pull request by fioriNTU**
This PR include plots to monitor the distribution of on track pixels in space (with ROC maps) and in time (with Lumisection trends). It improve the monitoring of dynamic inefficiency in the Pixel detector.

Also few ranges have been adapted to 2018 running

(Rebase of #23061 which is now closed)

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by boudoul** [comment]
hi @fioriNTU , please recall the purpose in the title (not only Rebase of #23061 )

The new package required is likely due to the fact that the last IB is not yet updated with @schneiml 's package ( I guess)

**Comment by dmitrijus** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Pull request merged**
