### PR TITLE
Totem timing DQM

### PR DESCRIPTION
**Pull request by forthommel**
This PR introduces the DQM for Totem vertical timing detectors, using `TotemTimingDigi`.
It was discussed on last Friday's [reco & analysis tools meeting](https://indico.cern.ch/event/718747/contributions/2954139/attachments/1628529/2594591/totempr-cmsoffmg.pdf).

To be included in DQM at P5 during the alignment run (occuring this Saturday morning) to commission the detectors.

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by forthommel** [comment]
It looks like we reached a timeout with `20434.0`...

**Comment by dmitrijus** [comment]
please test

**Comment by perrotta** [comment]
@forthommel : now that  #22796 had been merged and it is available in IB since CMSSW_10_2_X_2018-04-11-2300, do you plan to rebase this PR thus getting rod of the un-needed signaturs (e.g. reco)?

**Comment by forthommel** [comment]
@perrotta Indeed! Thanks for the notice, I was (too) patiently waiting for the next IB!

**Comment by forthommel** [comment]
Hello @perrotta, @civanch, @dmitrijus ! Would it please be possible for one of you to trigger the tests? Many thanks!

**Comment by jfernan2** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by nminafra** [comment]
@fabiocos We don't have an answer to your (very appropriate) remarks: these detectors never saw the beam before. In few hours we'll have a way better understanding and, more importantly, data that can be used to test the code.
Therefore, I promise an optimization of the plots at the next iteration. In my opinion it is possible to reduce the size at the level of the Timing Diamond at least.

**Comment by nminafra** [comment]
@fabiocos @perrotta We collected a fair amount of data during the alignment run and we did a successful commissioning of the detectors. In the following weeks I'll prepare the PRs for optimization of the code and bugfixing. Of course, also including the discussed PRs about geometry and reco. If you prefer, we can close this PR and I'll submit the optimized version of the DQM within the next two weeks.

**Comment by fabiocos** [comment]
@nminafra no need to close this, if you want to elaborate it further

**Comment by fabiocos** [comment]
please test

**Comment by forthommel** [comment]
Hello @fabiocos ! Is there any input needed from our side? Thanks!

**Comment by fabiocos** [comment]
hold

pending a revision of the real needs

**Comment by fabiocos** [comment]
@nminafra what is the status here? I have merged #23025, but it looks that these 2 PRs are to some extent addressing different checks, am I correct?

**Comment by nminafra** [comment]
@fabiocos you are correct. This is dedicated to the timing detectors in the vertical roman pots. The code is ready and tested. I'm waiting for #23101 to be reviewed so i can push the updated DQM which is also using TotemTimingRecHits, similarly to the backport of this pr (#22931). I suppose that the best strategy is that, when #23101 is advanced enough, i update this pr and consequently the backport.

**Comment by nminafra** [comment]
As discussed at the [meeting ](https://indico.cern.ch/event/727481/) today, I've updated the branch to include the new version of the DQM that also uses rechits.
**This PR requires #23101 for all the tests.**

Thanks!

**Comment by nminafra** [comment]
Please, hold on this PR, trying to remove all the files not concerning DQM.

Thanks

**Comment by nminafra** [comment]
Now it should be fine, sorry for the spam.
To avoid losing it in the flow of messages: this PR requires #23101 for all the tests.

**Comment by perrotta** [comment]
please test with #23101

**Comment by perrotta** [comment]
please test with #23101

**Comment by nminafra** [comment]
@fabiocos could you remove the hold, if it is fine with you?

**Comment by dmitrijus** [comment]
+1
(still needs to be unheld)

**Pull request merged**
