### PR TITLE
remove a bunch of useless `SiPixelTemplateStoreESProducer` includes 

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

Clean-up after https://github.com/cms-sw/cmssw/pull/42514.
Addresses https://github.com/cms-sw/cmssw/pull/42644#issuecomment-1692019347

#### PR validation:

```
runTheMatrix.py -l 1001,1001.2,1001.3,1005 -t 4 -j 8 --ibeos
```

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

N/A, but to be backported together with https://github.com/cms-sw/cmssw/pull/42644 (and corresponding backports)

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
test parameters:
   * workflows = 1001.2, 1001.3, 1005

**Comment by mmusich** [comment]
please test

**Comment by perrotta** [comment]
Thank you @mmusich you were faster than me!

Shouldn't we remove them also from:
- DQM/SiPixelPhase1Config/python/SiPixelPhase1OfflineDQM_source_cff.py
- DQM/SiPixelPhase1Config/python/SiPixelPhase1OnlineDQM_Timing_cff.py
- DQM/SiPixelPhase1Config/python/SiPixelPhase1OnlineDQM_cff.py
- DQMOffline/Trigger/python/SiStrip_OfflineMonitoring_cff.py
- FastSimulation/Configuration/python/Reconstruction_BefMix_cff.py
- RecoTracker/FinalTrackSelectors/python/MergeTrackCollections_cff.py
- RecoTracker/TransientTrackingRecHit/python/TTRHBuilders_cff.py
?

**Comment by mmusich** [comment]
@perrotta 

well, at least this one:

> * RecoTracker/TransientTrackingRecHit/python/TTRHBuilders_cff.py

I don't think so, otherwise who's going to provide the producer in all clients that do the refit? As for the others probably the DQM ones (the reconstruction ones I am not sure).

**Comment by perrotta** [comment]
@mmusich yes, you are quite likely right about RecoTracker/TransientTrackingRecHit/python/TTRHBuilders_cff.py, even though the include was added only by #42514 and it was not present before merging that PR

However, in the following configs #42514 both added the include and inserted the module `SiPixelTemplateStoreESProducer` in the paths, while subsequent #42597 removed the module from the paths but not the include from the config:
- DQM/SiPixelPhase1Config/python/SiPixelPhase1OfflineDQM_source_cff.py
- DQM/SiPixelPhase1Config/python/SiPixelPhase1OnlineDQM_Timing_cff.py
- DQM/SiPixelPhase1Config/python/SiPixelPhase1OnlineDQM_cff.py
- FastSimulation/Configuration/python/Reconstruction_BefMix_cff.py
- RecoTracker/FinalTrackSelectors/python/MergeTrackCollections_cff.py

For the following config, instead, only the include was added by #42514 (as it was for TTRHBuilders_cff.py), but the module therein was never used. I have the impression that it was slipped there by mistake: but I may be wrong...
- DQMOffline/Trigger/python/SiStrip_OfflineMonitoring_cff.py -> added by #42514, but why?

**Comment by mmusich** [comment]
These guys I confirm can go:

   * DQM/SiPixelPhase1Config/python/SiPixelPhase1OfflineDQM_source_cff.py
   * DQM/SiPixelPhase1Config/python/SiPixelPhase1OnlineDQM_Timing_cff.py
   * DQM/SiPixelPhase1Config/python/SiPixelPhase1OnlineDQM_cff.py

The rest needs testing.

**Comment by mmusich** [comment]
test parameters:
   * full_cmssw=true

**Comment by perrotta** [comment]
please test

**Comment by emanueleusai** [comment]
+1

**Comment by perrotta** [comment]
+alca

**Comment by perrotta** [comment]
+1

**Pull request merged**
