### PR TITLE
Add to phase-I queues updated version of SiPixelFedCablingMap for 48-channel feds, and update HCal QIEdata to version 2017_v2.0

### PR DESCRIPTION
**Pull request by mmusich**
This PR is meant as a bridge towards wrapping up the phase-I workflows (in PR #15994) to let people finish development work.
# Summary of changes in Global Tags
## Upgrade
- **PhaseI realistic scenario** : [81X_upgrade2017_realistic_Candidate_2016_10_05_11_41_20](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_upgrade2017_realistic_Candidate_2016_10_05_11_41_20) as [81X_upgrade2017_realistic_v14](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_upgrade2017_realistic_v14) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_upgrade2017_realistic_Candidate_2016_10_05_11_41_20/81X_upgrade2017_realistic_v14): 
  - updated version of SiPixelFedCablingMap for 48-channel feds
- **PhaseI design scenario** : [81X_upgrade2017_design_Candidate_2016_10_05_11_42_10](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_upgrade2017_design_Candidate_2016_10_05_11_42_10) as [81X_upgrade2017_design_v12](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_upgrade2017_design_v12) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_upgrade2017_design_Candidate_2016_10_05_11_42_10/81X_upgrade2017_design_v12): 
  - updated version of SiPixelFedCablingMap for 48-channel feds
- **PhaseI HcalDev scenario** : [81X_upgrade2017_HCALdev_Candidate_2016_10_05_11_20_17](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_upgrade2017_HCALdev_Candidate_2016_10_05_11_20_17) as [81X_upgrade2017_HCALdev_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_upgrade2017_HCALdev_v3) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_upgrade2017_HCALdev_Candidate_2016_10_05_11_20_17/81X_upgrade2017_HCALdev_v3): 
  - updated version of SiPixelFedCablingMap for 48-channel feds
  - update HCal QIEdata to version 2017_v2.0

@dkotlins @abdoulline

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
+1

**Comment by davidlange6** [comment]
Hi @mmusich - just to confirm - changes are expected with this PR?

**Comment by mmusich** [comment]
Hi @davidlange6, from the description in the requests only in Hcal in the dev2017 scenario

**Comment by abdoulline** [comment]
Yes, it removes HE saturation in dev2017 scenario.

**Comment by davidlange6** [comment]
+1
thanks

**Pull request merged**
