### PR TITLE
BMTF-KMTF DQM Algo Selector for the DQM/L1TMonitor Subsystem + SEGFAULT fix

### PR DESCRIPTION
**Pull request by panoskatsoulis**
This is the introduction of a new DQM plugin that selects the correct output muons of the BMTF depending on the algorithm that is triggering (Kalman BMTF/ Legacy BMTF).
Also, the PR includes the last BMTF Unpacker which is required by the DQM workflow and by the L1TBMTFAlgoSelector to operate correctly

Also: 
1) Here is fixed the SEGFAULT that occurred at some workflows.
2) A minor change to the Unpacker for a problem that illustrated by the last weekend's tests.

### CODE REVIEW

**Comment by rekovic** [comment]
please test

**Comment by andrius-k** [comment]
Hi @panoskatsoulis, is this a backport of two previous PRs? If so could you please mark it as so?

**Comment by thomreis** [comment]
Hi @panoskatsoulis 
is this a backport of PRs to the master branch? If not please make a PR of this to the master and flag this as a backport PR of if.

**Comment by panoskatsoulis** [comment]
backport of #24652 
This PR includes code of #24237 and #24555

**Comment by panoskatsoulis** [comment]
A new PR that is compatible with tag 10.2.5 has been created
#24793 
This will be closed

**Pull request closed without merging**
