### PR TITLE
backport in 75X : fix SingleTrackVertexConstraint class for the B=0T case 

### PR DESCRIPTION
**Pull request by HuguesBrun**
backport of the PR #9971 in 75X

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by HuguesBrun** [comment]
updated as the 76X PR

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
+1

For #9972 343585d8aa2a5ecbe9f4f2b62249ba4cb2466a55

Bug fix to correctly handle SingleTrackVertexConstraint when magnet is off. The 76X version of this PR, #9972, has already been approved by Reco.

The code change is satisfactory, and Jenkins [tests](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-9972/29/summary.html) against baseline CMSSW_7_5_X_2015-06-30-2300 show no significant differences.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
