### PR TITLE
Combine DeepTauBase with DeepTauId class

### PR DESCRIPTION
**Pull request by mbluj**
#### PR description:

Technical PR which combines the `DeepTauBase` base class into the `DeepTauId` class which previously inherited from the base class. This refactoring is to simplify structure of deep-tau code after keeping only one type of deep-tau discriminators. This should be regarded as first step for changes to enable running of deepTauID with SONIC service.

Changes in the code are minor: they consist moving and combining methods of the removed base and `DeepTauId` classes.

Changes in outputs are not expected.

#### PR validation:

Custom tests with deepTauID production as well as matrix tests (`runTheMatrix.py -l limited -i all --ibeos`) passed successfully.

### CODE REVIEW

**Comment by clacaputo** [comment]
type tau

**Comment by clacaputo** [comment]
please test

**Comment by mbluj** [comment]
> There are some reco changes in `12434.7` https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_13_2_X_2023-06-01-1100+a52f55/57311/validateJR/12434.7_TTbar_14TeV+2023_trackingMkFit/all_RECO_step3/ @mbluj , from you PR's description, it shouldn't be the case

This code can only affect output of deepTauId which is produced in miniAOD and/or nanoAOD workflows (+some tau HLT paths), while differences referred here have (most probably) to do with tracking (small differences in pt of pf-charged candidates, in flavours tagges output, etc.). Could it be that results of MkFit are not 100% reproducible (e.g. with different CPU architecture or so)?

**Comment by perrotta** [comment]
> There are some reco changes in `12434.7` https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_13_2_X_2023-06-01-1100+a52f55/57311/validateJR/12434.7_TTbar_14TeV+2023_trackingMkFit/all_RECO_step3/ @mbluj , from you PR's description, it shouldn't be the case

@cmsbuild non reproducible outputs in that mkfit workflow are showing up from time to time. Here they are clearly unrelated from this PR

**Comment by mandrenguyen** [comment]
+reconstruction
Code refactoring, no change to reco (diffs are spurious)

**Comment by perrotta** [comment]
@mbluj for a possible further cleanup (in a separate PR):
- reorder alphabetically the included headers, as usual with the ones from cmssw first, and system/external ones after
- make `const` the static variable `varsToDrop` at [L216](https://github.com/cms-sw/cmssw/blob/93d4ff273c920108742e972faa6689c5254f7a3a/RecoTauTag/RecoTau/plugins/DeepTauId.cc#LL216C24-L216C35), as also suggested by the static analyzer

**Comment by perrotta** [comment]
+1

**Comment by perrotta** [comment]
> @perrotta thank you for suggestions. Do you suggest a technical PR with only small changes addressing those issues (which can be done quickly) or can the fixes wait for other changes in the deepTauID class?

It's up to you... Well, if you have another PR ready that touches these classes, you can add them there. Otherwise, it could be more convenient submit a simple PR with the fixes, so that they don't get forgotten.
In any case, there is nothing really urgent to fix there.

**Pull request merged**
