### PR TITLE
Initialize GEMDQMBase::MEStationInfo:nMinIdxChamber_ and GEMDQMBase::MEStationInfo:nMaxIdxChamber_ in constructor

### PR DESCRIPTION
**Pull request by iarspider**
#### PR description:

Fixes warnings produced by gcc 11 (#38516)

#### PR validation:

Local build does not produce warnings

### CODE REVIEW

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
please test for el9_amd64_gcc11

**Comment by emanueleusai** [comment]
type gem

**Comment by emanueleusai** [comment]
type bug

**Comment by emanueleusai** [comment]
are the failures for el9_amd64_gcc11 understood? it seem unlikely they are caused by this PR

**Comment by iarspider** [comment]
please test for el9_amd64_gcc11

let's try again, maybe the failures will go away

**Comment by emanueleusai** [comment]
hmmm they're still there. Perhaps some unit tests are not configured to work correctly with this architecture?

**Comment by emanueleusai** [comment]
ah that makes sense!

**Comment by emanueleusai** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
