### PR TITLE
Fix ConfDb connection parameters [110X]

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
#### PR description:

Fix ConfDb connection parameters [110X]

#### PR validation:

TSG tests

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Bug fix in ConfDb connection parameters after recent Oracle update (also fixes HLT Validation tests).

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
backport of #33981

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
