### PR TITLE
get rid of `CMSDEPRECATED_X` warnings from `DQM/Track*`

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

Trivial PR, title says it all.
Part of the migration in #36404.
Went systematically through all of the `CMSDEPRECATED_`X warnings in the subsystems  `DQM/Track*` from `CMSSW_12_3_CMSDEPRECATED_X_2022-01-17-2300` and removed deprecated API calls.

#### PR validation:

`cmssw` compiles

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by perrotta** [comment]
+1

**Comment by perrotta** [comment]
merge

**Pull request merged**
