### PR TITLE
Forward-port three simple tracking PRs from 620_SLHC

### PR DESCRIPTION
**Pull request by makortel**
This PR is a forward-port of the following PRs in 620_SLHC branch that are not yet in 74X
- #4372: Fix PixelTrackCleanerWrapper for quadruplet SeedingHitSet
- #3921: Fpix navigation allfixed newdetid
  - Everything else of it is already included except small enhancement in LogError message that looks possibly useful
- #4180: Remove vector reserve in SeedGeneratorFromRegionHits

No regression expected, no regression observed (tested with RelValTTbar_13 in 740pre6).

@rovere @VinInn @boudoul @venturia @davidlange6, please review

### CODE REVIEW

**Comment by cvuosalo** [comment]
please test

**Comment by cvuosalo** [comment]
@makortel: I ran basic matrix tests and found an error in workflow 140.53_RunHI2011+RunHI2011+RECOHID11+HARVESTDHI (step 2):

cmsRun: /build/cvuosalo/reco/pr7627/CMSSW_7_4_0_pre6-testPR7627/src/RecoTracker/TkSeedGenerator/plugins/SeedGeneratorFromProtoTracksEDProducer.cc:126: virtual void SeedGeneratorFromProtoTracksEDProducer::produce(edm::Event&, const edm::EventSetup&): Assertion `hits.size()<4' failed.

Could a necessary file have been left out of this PR? Does SeedGeneratorFromProtoTracksEDProducer.cc have any relationship to this PR?

The Jenkins tests haven't completed yet, but when they do, I'll check if they show the same error.

**Comment by makortel** [comment]
@cvuosalo Jenkins seems to agree with you, but for me `runTheMatrix.py -l 140.53` succeeds, i.e. I'm unable to reproduce it. The problem can be related to this PR, as d9602cf allows to have 4-hit pixel tracks. Investigating...

**Comment by makortel** [comment]
Ok, it was a matter of `git cms-addpkg RecoTracker/TkSeedGenerator && scram b`, now I can reproduce the issue.

**Comment by makortel** [comment]
I have a bit more information. The "bug" (how we get 4-hit pixel track from 3-layer pixel detector) occurs in `TrackCleaner` (used by `PixelTrackProducer` labelled as "hiPixel3PrimTracks"). What happens is that it gets two 3-hit tracks as an input that share the hits on layers 2 and 3. The code then merges these two tracks such that the resulting track has 4 hits: 2 from layer 1, and 1 from both layers 2 and 3.

I have no idea if this is the intended behaviour of `TrackCleaner` (I'll dig in the code next), but what happens currently (i.e. before d9602cf) is that this 4-hit track gets truncated to 3-hit track with 2 hits from layer 1 and 1 from layer 2 (which, to me, sounds like a bug).

**Comment by makortel** [comment]
Based on the code in `TrackCleaner::cleanTracks()` it looks to me that it behaves as intended. I'm not sure how to proceed.

I would actually ask next why the assert in `SeedGeneratorFromProtoTracksEDProducer` is needed (not obvious from the code)?

**Comment by slava77** [comment]
Would the problem happen in pp tracking if the same kind of hit pattern is
present?

**Comment by makortel** [comment]
@slava77 AFAICT neither `SeedGeneratorFromProtoTracksEDProducer` or ` TrackCleaner` are used in pp tracking. The (not-anymore-run-in-offline) pixelTracks uses `PixelTrackCleanerBySharedHits` as a cleaner, and it doesn't merge tracks (but rejects track with smaller pT from pair that shared >= 2 hits). In seeding of iterative tracking there is no "cleaning" step, i.e. the constructed 3-hit seeds are passed "as they are" to track finding.

**Comment by VinInn** [comment]
SeedGeneratorFromProtoTracksEDProducer is used at HLT, isn't it @mtosi ?

**Comment by makortel** [comment]
Right, I missed that one. But it seems to use the tracks from  PixelTrackProducer+PixelTrackCleanerBySharedHits as an input, so there should be no 4-hit tracks and the assert should not fire.

**Comment by mtosi** [comment]
yes, SeedGeneratorFromProtoTracksEDProducer modules use pixelTracks

**Comment by slava77** [comment]
I'm trying to understand if HI is using the tracking configuration
correctly and intentionally
or it just happens to be some copy-paste of features working in 53X
which have changed since then
and which shouldn't really be used anymore?
If it's the latter, we should propagate updates to the HI reco.



On 2/10/15 5:33 AM, Matti Kortelainen wrote:
> Right, I missed that one. But it seems to use the tracks from
> PixelTrackProducer+PixelTrackCleanerBySharedHits as an input, so there
> should be no 4-hit tracks and the assert should not fire.
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cms-sw/cmssw/pull/7627#issuecomment-73685331>.
> 

-- 
***********************************************************************
 Vyacheslav (Slava) Krutelyov
 TAMU: Physics Dept Texas A&M MS4242, College Station, TX 77843-4242
 CERN: 42-R-027
 AIM/Skype: siava16              googleTalk: slava77@gmail.com
 (630) 291-5128  Cell (US)       +41 76 275 7116 Cell (CERN)

-----------------------------------------------------------------------

**Comment by slava77** [comment]
@yetkinyilmaz @makortel @VinInn @rovere 
Could you please comment on https://github.com/cms-sw/cmssw/pull/7627#issuecomment-73705929

**Comment by yetkinyilmaz** [comment]
Thanks for the attention, I think I need to check with
@istaslis @mandrenguyen

**Comment by mandrenguyen** [comment]
@slava77 
Pixel track merging is known feature in the HI tracking, which is presumably there to reduce the combinatorics.  We haven't tested the actual benefit of this in quite some time though.  Pixel tracks can (rarely) have up to 8 hits, I believe.

**Comment by makortel** [comment]
@mandrenguyen @yetkinyilmaz Given that the merging of pixel tracks is indeed a feature in the HI tracking, is the current behaviour of keeping only first 3 (with d9602cf 4) hits in a pixel track desirable?

**Comment by mandrenguyen** [comment]
@makortel 
I'm not sure.  We'll need a bit more time to understand what's going on here.

@dgulhan @appeltel   Can you take a look?

**Comment by slava77** [comment]
Matt, 
Please clarify if there was progress understanding the impact on HI.
Thank you.

**Comment by davidlange6** [comment]
closing in 74x - there is the same PR open in 75x (now the development release)

**Comment by mandrenguyen** [comment]
Hi Slava,
This is under study, but will take another ~week to sort out.


On 2/18/15 4:02 AM, Slava Krutelyov wrote:
>
> Matt,
> Please clarify if there was progress understanding the impact on HI.
> Thank you.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/cms-sw/cmssw/pull/7627#issuecomment-74803002>.
>


-- 
-----------------------
Matthew Nguyen
Chargé de Recherche
LLR-Ecole Polytechnique
91128 Palaiseau FRANCE
+33 1 69 33 55 65
-----------------------

**Comment by appeltel** [comment]
After some preliminary study of 100 jet-embedded PbPb events in 740pre6, I see no substantial difference on reconstructed or matched tracks between the current cleaning and https://github.com/cms-sw/cmssw/commit/d9602cf6ae0cd7ff220be7925ffeb015fe5b035a . You can see the attached pT distribution, and other quality distributions look nearly identical.

I am concerned that the behavior of the cleaner as @makortel describes is clearly not what we want and I would like to look further into the effect of this on pixel tracking in PbPb in general. I would suppose that for the use case of offline PbPb track reconstruction, the trajectory of the pixel track truncated to hits from the first two layers is still reasonable, so after it gets converted to a seed the CKF probably just picks back up the hit on layer 3. 

For the purpose of the PR, I don't see any problem, so long as we also remove the assert statement: RecoTracker/TkSeedGenerator/plugins/SeedGeneratorFromProtoTracksEDProducer.cc:126

I am not sure why the assert statement was just a sanity check or why it was ever there.

ptr_pr7267_jetembedded_hydjet_100ev

**Comment by makortel** [comment]
Thanks @appeltel.

Are there any objections to removing the assert in SeedGeneratorFromProtoTracksEDProducer.cc? @slava77 @cvuosalo @VinInn

**Comment by VinInn** [comment]
no clue what the assert is doing there.
maybe to protect against quadruplets?

**Comment by makortel** [comment]
I can only tell that it was added in commit 39173218 (CVS times).

**Comment by VinInn** [comment]
Ok, was a safety check.
remove it, given requirements changed.

**Comment by makortel** [comment]
Removed the assert, continuing the discussion in #7798

**Pull request closed without merging**
