### PR TITLE
Validation/RecoEgamma/plugins recOfflineVertices histogram parameters modification V2

### PR DESCRIPTION
**Pull request by archiron**
#### PR description:

in the electron validation (Validation/RecoEgamma/plugins) we made a small modification in the recOfflineVertices histogram (nb of bins and nb of vertices shown) to adapt the nvertices plot range to the Run 3 PU conditions.
we can show the new conformation on linked picture.
recOfflineVertices-4

#### PR validation:

compilation is OK, basics tests (scram b runtests or local tests) are OK to.
runTheMatrix.py -l limited -i all --ibeos tests are fine.

#### if this PR is a backport please specify the original PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch -> OK.
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html) -> OK. 
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html) -> OK.

@beaudett

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by fabiocos** [comment]
@archiron trivial question: you say that the new histogram definition is adapted to Run3; is it also still functional to validate older setups as well?

**Comment by fabiocos** [comment]
silly question, you have increased the possible PU range without moving the lower value, the answer is obviously yes

**Comment by fabiocos** [comment]
+1

**Comment by archiron** [comment]
Yes. I made also tests with 11_0_0_pre2 and 10_6_0_pre4, as with 10_6_1 without any failure.Arnaud Envoyé depuis mon appareil mobile Samsung.
-------- Message d'origine --------De : Fabio Cossutti <notifications@github.com> Date : 20/07/2019  20:33  (GMT+01:00) À : cms-sw/cmssw <cmssw@noreply.github.com> Cc : Chiron <arnaud.chiron@cern.ch>, Mention <mention@noreply.github.com> Objet : Re: [cms-sw/cmssw] Validation/RecoEgamma/plugins recOfflineVertices histogram parameters modification V2 (#27561) @archiron trivial question: you say that the new histogram definition is adapted to Run3; is it also still functional to validate older setups as well?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/cms-sw/cmssw/pull/27561?email_source=notifications\u0026email_token=ABKT7HZVVCBGM53QJYHHQN3QANK5NA5CNFSM4IFDTQA2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD2NTVJI#issuecomment-513489573",
"url": "https://github.com/cms-sw/cmssw/pull/27561?email_source=notifications\u0026email_token=ABKT7HZVVCBGM53QJYHHQN3QANK5NA5CNFSM4IFDTQA2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD2NTVJI#issuecomment-513489573",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by beaudett** [comment]
Hello,
here is the test that Arnaud has done. We have reduced the binning and extended the range, but the distribution is still well readable. 
recOfflineVertices-4
Florian

**Pull request merged**
