### PR TITLE
[HGCal] New fragments for special HGCal RelVal requests

### PR DESCRIPTION
**Pull request by apsallid**
#### PR description:

The HGCal DPG wants to regularly inspect the performance of CLUE clustering in 120/200/300/Scint regions, while at the same time study the 3D score and the behavior of the multicluster validation. For these reasons, we add new gen fragments and will later create a JIRA ticket with the relevant RelVal requests to the PdmV group. Two things to notice, as PdmV told us (@siddhesh86 ) : 
- Since separate workflows with unique numbers would be preferred as all the relvals can be submitted in one go, we have added the GEN fragments we wish to use. 
- In all cases we tried to stay with a name of low string length, since high string length names  are not getting submitted lately. 

Specifically, we are shooting in front of: 
- The scintillator part of CE-H Coarse.
- The silicon part of CE-H Coarse.
- CE-H Fine in the 3 different thicknesses of Silicon cells.
- CE-E in the 3 different thicknesses of Silicon cells.  

#### PR validation:

We have used in the past the CloseByParticleGun with a pair of unconverted photons for calibration studies [1]. 

#### if this PR is a backport please specify the original PR:

This is not a backport. 

@rovere @felicepantaleo @amartelli @gouskos @siddhesh86

[1] https://indico.cern.ch/event/813555/contributions/3400815/attachments/1831509/2999508/Psallidas-Checks.pdf

### CODE REVIEW

**Comment by kpedro88** [comment]
@apsallid you also need to modify the lists at the end of https://github.com/cms-sw/cmssw/blob/master/Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py so the workflow numbers will be assigned for these new fragments

**Comment by apsallid** [comment]
@kpedro88 Thanks a lot. Sorry for this late reply, I was traveling today. These are difficult days.

**Comment by kpedro88** [comment]
please test

**Comment by kpedro88** [comment]
+upgrade

**Comment by qliphy** [comment]
+1

**Comment by fabiocos** [comment]
@prebello @zhenhu the update to PyRelVal looks ok, I've managed to list the new test workflows and run ```20494.0_CloseByParticleGun_CE_E_Front_300um+CE_E_Front_300um_2026D41_GenSimHLBeamSpotFull+DigiFullTrigger_2026D41+RecoFullGlobal_2026D41+HARVESTFullGlobal_2026D41/``` .

Could you please comment or sign it? I would like to move it forward

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

@prebello @zhenhu in case please comment

**Pull request merged**
