### PR TITLE
Updated Photon regressions, added e/gamma regressions for online, updated JECs with L2L3 residuals and other fixes

### PR DESCRIPTION
**Pull request by mmusich**
# Summary of changes in Global Tags
## RunII simulation
- **RunII Ideal scenario** : [80X_mcRun2_design_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_mcRun2_design_v5) as [80X_mcRun2_design_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_mcRun2_design_v4) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/80X_mcRun2_design_v5/80X_mcRun2_design_v4): 
  - updated photon energy regressions for 2016
  - introduced e/gamma energy regressions for HLT 
  - changed Hcal LUT metadata to include 1x1 HF TPs topology
  - updated JEC and PF calibrations for HLT (to allow integration of residuals corrections in 2016 menu)
- **RunII CRAFT scenario** : [80X_mcRun2cosmics_startup_peak_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_mcRun2cosmics_startup_peak_v3) as [80X_mcRun2cosmics_startup_peak_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_mcRun2cosmics_startup_peak_v2) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/80X_mcRun2cosmics_startup_peak_v3/80X_mcRun2cosmics_startup_peak_v2): 
  - updated photon energy regressions for 2016
  - introduced e/gamma energy regressions for HLT 
  - changed Hcal LUT metadata to include 1x1 HF TPs topology
- **RunII Asymptotic scenario** : [80X_mcRun2_asymptotic_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_mcRun2_asymptotic_v5) as [80X_mcRun2_asymptotic_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_mcRun2_asymptotic_v4) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/80X_mcRun2_asymptotic_v5/80X_mcRun2_asymptotic_v4): 
  - updated photon energy regressions for 2016
  - introduced e/gamma energy regressions for HLT 
  - changed Hcal LUT metadata to include 1x1 HF TPs topology
  - updated JEC and PF calibrations for HLT (to allow integration of residuals corrections in 2016 menu)
- **RunII Startup scenario** : [80X_mcRun2_startup_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_mcRun2_startup_v5) as [80X_mcRun2_startup_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_mcRun2_startup_v4) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/80X_mcRun2_startup_v5/80X_mcRun2_startup_v4): 
  - updated photon energy regressions for 2016
  - introduced e/gamma energy regressions for HLT 
  - changed Hcal LUT metadata to include 1x1 HF TPs topology
- **RunII Heavy Ions scenario** : [80X_mcRun2_HeavyIon_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_mcRun2_HeavyIon_v4) as [80X_mcRun2_HeavyIon_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_mcRun2_HeavyIon_v3) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/80X_mcRun2_HeavyIon_v4/80X_mcRun2_HeavyIon_v3): 
  - updated photon energy regressions for 2016
  - introduced e/gamma energy regressions for HLT 
  - changed Hcal LUT metadata to include 1x1 HF TPs topology
  - updated JEC and PF calibrations for HLT (to allow integration of residuals corrections in 2016 menu)
## RunII data
- **RunII Offline processing** : [80X_dataRun2_v6](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_dataRun2_v6) as [80X_dataRun2_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_dataRun2_v5) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/80X_dataRun2_v6/80X_dataRun2_v5): 
  - updated JEC and PF calibrations for HLT (to allow integration of residuals corrections in 2016 menu) .
  - updated photon energy regressions for 2016
  - updated Tracker alignment for 2015 0T IOVs 
  - updated Ecal Intercalibrations for 2015 0T IOVs
  - updated Ecal ADC to GeV scale constants for 2015 0T IOVs
  - updated Ecal Barrel and Endcaps alignment for 2015 0T IOvs
  - updated LS based beamspot for 2015 0T IOvs
  - updated Strip particle gains for 2015 0T IOVs
  - updated Strip bad channels for 2015 0T IOVs
- **RunII HLTHI processing** : [80X_dataRun2_HLTHI_frozen_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_dataRun2_HLTHI_frozen_v3) as [80X_dataRun2_HLTHI_frozen_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_dataRun2_HLTHI_frozen_v2) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/80X_dataRun2_HLTHI_frozen_v3/80X_dataRun2_HLTHI_frozen_v2): 
  - introduced e/gamma energy regressions for HLT 
  - corrected 2015 IOVs in ESEE and ES Intercalibrations records to take into account changes from PR #13074
- **RunII HLT relval processing** : [80X_dataRun2_HLT_relval_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_dataRun2_HLT_relval_v1) as [80X_dataRun2_HLT_relval_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_dataRun2_HLT_relval_v0) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/80X_dataRun2_HLT_relval_v1/80X_dataRun2_HLT_relval_v0): 
  - updated JEC and PF calibrations for HLT (to allow integration of residuals corrections in 2016 menu) 
  - introduced e/gamma energy regressions for HLT 
  - corrected 2015 IOVs in ESEE and ES Intercalibrations records to take into account changes from PR #13074
- **RunII HLT processing** : [80X_dataRun2_HLT_frozen_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_dataRun2_HLT_frozen_v3) as [80X_dataRun2_HLT_frozen_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_dataRun2_HLT_frozen_v2) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/80X_dataRun2_HLT_frozen_v3/80X_dataRun2_HLT_frozen_v2): 
  - updated JEC and PF calibrations for HLT (to allow integration of residuals corrections in 2016 menu) 
  - introduced e/gamma energy regressions for HLT 
  - corrected 2015 IOVs in ESEE and ES Intercalibrations records to take into account changes from PR #13074
- **RunII Offline relval processing** : [80X_dataRun2_relval_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_dataRun2_relval_v1) as [80X_dataRun2_relval_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_dataRun2_relval_v0) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/80X_dataRun2_relval_v1/80X_dataRun2_relval_v0): 
  - updated JEC and PF calibrations for HLT (to allow integration of residuals corrections in 2016 menu) .
  - updated photon energy regressions for 2016
  - updated Tracker alignment for 2015 0T IOVs 
  - updated Ecal Intercalibrations for 2015 0T IOVs
  - updated Ecal ADC to GeV scale constants for 2015 0T IOVs
  - updated Ecal Barrel a
    # Summary of changes in Global Tags 
## RunII simulation
- **RunII Ideal scenario** : [80X_mcRun2_design_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_mcRun2_design_v5) as [80X_mcRun2_design_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_mcRun2_design_v4) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/80X_mcRun2_design_v5/80X_mcRun2_design_v4): 
  - updated photon energy regressions for 2016
  - introduced e/gamma energy regressions for HLT 
  - changed Hcal LUT metadata to include 1x1 HF TPs topology
  - updated JEC and PF calibrations for HLT (to allow integration of residuals corrections in 2016 menu)
- **RunII CRAFT scenario** : [80X_mcRun2cosmics_startup_peak_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_mcRun2cosmics_startup_peak_v3) as [80X_mcRun2cosmics_startup_peak_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_mcRun2cosmics_startup_peak_v2) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/80X_mcRun2cosmics_startup_peak_v3/80X_mcRun2cosmics_startup_peak_v2): 
  - updated photon energy regressions for 2016
  - introduced e/gamma energy regressions for HLT 
  - changed Hcal LUT metadata to include 1x1 HF TPs topology
- **RunII Asymptotic scenario** : [80X_mcRun2_asymptotic_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_mcRun2_asymptotic_v5) as [80X_mcRun2_asymptotic_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_mcRun2_asymptotic_v4) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/80X_mcRun2_asymptotic_v5/80X_mcRun2_asymptotic_v4): 
  - updated photon energy regressions for 2016
  - introduced e/gamma energy regressions for HLT 
  - changed Hcal LUT metadata to include 1x1 HF TPs topology
  - updated JEC and PF calibrations for HLT (to allow integration of residuals corrections in 2016 menu)
- **RunII Startup scenario** : [80X_mcRun2_startup_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_mcRun2_startup_v5) as [80X_mcRun2_startup_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_mcRun2_startup_v4) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/80X_mcRun2_startup_v5/80X_mcRun2_startup_v4): 
  - updated photon energy regressions for 2016
  - introduced e/gamma energy regressions for HLT 
  - changed Hcal LUT metadata to include 1x1 HF TPs topology
- **RunII Heavy Ions scenario** : [80X_mcRun2_HeavyIon_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_mcRun2_HeavyIon_v4) as [80X_mcRun2_HeavyIon_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_mcRun2_HeavyIon_v3) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/80X_mcRun2_HeavyIon_v4/80X_mcRun2_HeavyIon_v3): 
  - updated photon energy regressions for 2016
  - introduced e/gamma energy regressions for HLT 
  - changed Hcal LUT metadata to include 1x1 HF TPs topology
  - updated JEC and PF calibrations for HLT (to allow integration of residuals corrections in 2016 menu)
## RunII data
- **RunII Offline processing** : [80X_dataRun2_v6](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_dataRun2_v6) as [80X_dataRun2_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_dataRun2_v5) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/80X_dataRun2_v6/80X_dataRun2_v5): 
  - updated JEC and PF calibrations for HLT (to allow integration of residuals corrections in 2016 menu) .
  - updated photon energy regressions for 2016
  - updated Tracker alignment for 2015 0T IOVs 
  - updated Ecal Intercalibrations for 2015 0T IOVs
  - updated Ecal ADC to GeV scale constants for 2015 0T IOVs
  - updated Ecal Barrel and Endcaps alignment for 2015 0T IOvs
  - updated LS based beamspot for 2015 0T IOvs
  - updated Strip particle gains for 2015 0T IOVs
  - updated Strip bad channels for 2015 0T IOVs
- **RunII HLTHI processing** : [80X_dataRun2_HLTHI_frozen_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_dataRun2_HLTHI_frozen_v3) as [80X_dataRun2_HLTHI_frozen_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_dataRun2_HLTHI_frozen_v2) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/80X_dataRun2_HLTHI_frozen_v3/80X_dataRun2_HLTHI_frozen_v2): 
  - introduced e/gamma energy regressions for HLT 
  - corrected 2015 IOVs in ESEE and ES Intercalibrations records to take into account changes from PR #13074
- **RunII HLT relval processing** : [80X_dataRun2_HLT_relval_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_dataRun2_HLT_relval_v1) as [80X_dataRun2_HLT_relval_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_dataRun2_HLT_relval_v0) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/80X_dataRun2_HLT_relval_v1/80X_dataRun2_HLT_relval_v0): 
  - updated JEC and PF calibrations for HLT (to allow integration of residuals corrections in 2016 menu) 
  - introduced e/gamma energy regressions for HLT 
  - corrected 2015 IOVs in ESEE and ES Intercalibrations records to take into account changes from PR #13074
- **RunII HLT processing** : [80X_dataRun2_HLT_frozen_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_dataRun2_HLT_frozen_v3) as [80X_dataRun2_HLT_frozen_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_dataRun2_HLT_frozen_v2) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/80X_dataRun2_HLT_frozen_v3/80X_dataRun2_HLT_frozen_v2): 
  - updated JEC and PF calibrations for HLT (to allow integration of residuals corrections in 2016 menu) 
  - introduced e/gamma energy regressions for HLT 
  - corrected 2015 IOVs in ESEE and ES Intercalibrations records to take into account changes from PR #13074
- **RunII Offline relval processing** : [80X_dataRun2_relval_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_dataRun2_relval_v1) as [80X_dataRun2_relval_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_dataRun2_relval_v0) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/80X_dataRun2_relval_v1/80X_dataRun2_relval_v0): 
  - updated JEC and PF calibrations for HLT (to allow integration of residuals corrections in 2016 menu) .
  - updated photon energy regressions for 2016
  - updated Tracker alignment for 2015 0T IOVs 
  - updated Ecal Intercalibrations for 2015 0T IOVs
  - updated Ecal ADC to GeV scale constants for 2015 0T IOVs
  - updated Ecal Barrel and Endcaps alignment for 2015 0T IOvs
  - updated LS based beamspot for 2015 0T IOvs
  - updated Strip particle gains for 2015 0T IOVs
  - updated Strip bad channels for 2015 0T IOVs

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
+1

**Comment by davidlange6** [comment]
please test 
(we miss some tests for some reason)

**Comment by mmusich** [comment]
@davidlange6 can this be merged now? Thanks

**Comment by davidlange6** [comment]
+1

**Pull request merged**
