### PR TITLE
SLHA files received from Andrew H

### PR DESCRIPTION
**Pull request by dnash86**

### CODE REVIEW

**Comment by davidlange6** [comment]
Hi all - did we get the data files for this pull request into cmsdata?

**Comment by bendavid** [comment]
The files are already in cms-data in fact (from when they were originally moved there)

Requestors need to check that what is there is up to date.

**Comment by davidlange6** [comment]
ah - I had understood that was the case for the other PR of this sort. Then I will close this one too

**Comment by bendavid** [comment]
In fact for pythia8 slha files we have a python based solution now not requiring these to be in the release.

**Comment by bendavid** [comment]
(You're otherwise correct that I was referring to the other pull request with a larger number of file types)

**Pull request closed without merging**
