### PR TITLE
Removed beginRun use in EgammaPhotonProducers modules

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

- moved EventSetup get to produce
- changed member data names to match CMS conventions

This is part of framework change that will require stream modules to explicitly register to use Run/LuminosityBlock transitions.

#### PR validation:

Code compiles.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
@makortel FYI

**Comment by Dr15Jones** [comment]
please test

**Comment by mandrenguyen** [comment]
+1

**Comment by rappoccio** [comment]
+1

**Pull request merged**
