### PR TITLE
mix fissing comma

### PR DESCRIPTION
**Pull request by covarell**

### CODE REVIEW

**Comment by covarell** [comment]
+1

**Comment by davidlange6** [comment]
@covarell - please give this PR a meaningful title and description for the release notes. Thanks

**Comment by covarell** [comment]
Sorry it was a typo in making the commit and it was then transferred to the PR name, it was of course "fix missing comma" in the parameter sets of the affected files

**Comment by davidlange6** [comment]
@covarell - could you update the pull request title with this information and possibly a hint about what area the code change is made in (eg generator fragments)

**Pull request closed without merging**
