### PR TITLE
switch HI MC from a 2018 to a 2021 workflow  (158.0 -> 312.0) in the short matrix

### PR DESCRIPTION
**Pull request by slava77**
after discussing with @mandrenguyen , a  sample using signal mixing is more appropriate and using Zeemm sample should cover more parts of reco.
Among a few available Run3 HI MC workflows, 159.0, 311.0, and 312.0 I found that the total time is about the same as 158.0 to within a couple of minutes (for a total of about 30 m on my somewhat slow machine).

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test with cms-sw/cms-bot#1409

**Comment by kpedro88** [comment]
+upgrade

**Comment by chayanit** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
