### PR TITLE
MiniAOD reprocessing (74X, BTV): GBRForest in TMVAEvaluator + SoftLepton taggers using GBRForest

### PR DESCRIPTION
**Pull request by ferencek**
Backport of #10543. Note that this backport had to be applied on top of #10363.

This PR is part of preparations for possible MiniAOD reprocessing of the Spring15 MC and 50ns Run2012B Data in 74X. More info at the following links:
- https://hypernews.cern.ch/HyperNews/CMS/get/physics-validation/2445.html
- https://twiki.cern.ch/twiki/bin/view/CMS/MiniAODSpring15pass2#BTV

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test
(at least compilation and such will be tested; low hopes for DAS cooperation)

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cmsbuild please test
redo the tests since the results for the previous ones expired

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/10760	4d2cda8
- code changes are as described and represent a backport on top of #10363 + (	https://github.com/cms-sw/cmssw/pull/10543	 0d350a8)
- jenkins tests pass and comparisons with baseline show differences in SET and (downstream) combined btaggers all due to the change in #10363. The additions from #10543 are technical.
- checked locally in CMSSW_7_4_10_patch1 /test area sign576/ to confirm memory reduction from using GBR: there is a net decrease of about 8MB clearly connected to use of GBR instead of TMVA during runtime MVA evaluations.

**Comment by slava77** [comment]
@gpetruc since this one is dependent on #10363, a part of #10649, please merge this one (probably after AT signs off as well)

@monttj please check from your side

**Comment by gpetruc** [comment]
ok will merge in #10649 when this will be fully signed

**Comment by monttj** [comment]
+1

**Comment by ferencek** [comment]
Closing. Included in #10649.

**Pull request closed without merging**
