### PR TITLE
Adjustments for using MixingModule for Heavy Ion simulations

### PR DESCRIPTION
**Pull request by yetkinyilmaz**
This is the minimum updates in order to be able to run MixingModule for Heavy-Ion embedding studies.
Presented in https://indico.cern.ch/event/344150/

The main difference from pp pile-up simulations is that it runs mixing in gen-level, and the sim-level mixing in next process happens in playback mode. Event contents are updated accordingly. ConfigBuilder is adjusted so that the commands here define the workflows successfully:
https://github.com/CmsHI/cmssw/blob/mix_74X_08/HeavyIonsAnalysis/Mixing/test/runChainTemp.sh

Tested on 
slc6_amd64_gcc491 
by
runTheMatrix.py -s --useInput all
runTheMatrix.py -l 140.53

To be followed up in later pull-requests:
- Clean up ConfigBuilder.py, StandardSequences other configs for left-overs form the old heavy-ion embedding workflow
- Define the RelVal workflows
- Update PyquenInterface also for the ability to read background event information (special embedding features of Pyquen are temporarily disabled)
- Update in PlaybackInfo dataformat to keep file info - independent development

### CODE REVIEW

**Comment by yetkinyilmaz** [comment]
Dear all, this pull-request seems to be stuck, can somebody comment on what is wrong?
This is quite an important pull-request for the HI studies in 74X.
Thanks.

**Comment by bendavid** [comment]
@ktf this looks like another case where the tests for a 74x pull request ran in a 73x build

**Comment by civanch** [comment]
please test

**Comment by mdhildreth** [comment]
+1

**Comment by monttj** [comment]
+1
But this is more related with reco for genParticles. @slava77 ?
PhysicsTools/HepMCCandAlgos/plugins/GenParticleProducer.cc

**Comment by davidlange6** [comment]
last call for comments on this PR. will be merged soon based on previous green lights and the lack of complaints from pending signatures.

**Comment by bendavid** [comment]
Are we sure this doesn't affect the genparticles for standard workflows?

**Comment by yetkinyilmaz** [comment]
Yes, but I guess you're asking for someone else to confirm, since I am 
the one making the PR?

I can also explain the changes,

this change:
https://github.com/cms-sw/cmssw/pull/6982/files#diff-94009cb95755c284dadfbe394912ba5eL100
is only effective in the doSubEvent_ and/or useCF_ cases, which are 0 in 
standard workflows.

The other lines are just LogDebugs.

**Comment by bendavid** [comment]
+1

**Comment by yetkinyilmaz** [comment]
merging?

**Comment by davidlange6** [comment]
@yetkinyilmaz - looks like this PR broke a number of HI workflows. Please have a look - e.g. - 

https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc6_amd64_gcc481/CMSSW_7_4_X_2015-01-16-1400/pyRelValMatrixLogs/run/300.0_Pyquen_GammaJet_pt20_2760GeV+HydjetQ_MinBias_2760GeVINPUT+Pyquen_GammaJet_pt20_2760GeV+DIGIHISt3+RECOHISt4+HARVESTHI/step2_Pyquen_GammaJet_pt20_2760GeV+HydjetQ_MinBias_2760GeVINPUT+Pyquen_GammaJet_pt20_2760GeV+DIGIHISt3+RECOHISt4+HARVESTHI.log

**Comment by yetkinyilmaz** [comment]
This is totally expected, but I should have temporarily disabled these workflows in the PR. The new methods are completely different, so these workflows will have to be almost completely written from scratch - cleaning the old style HiMixingModule related stuff (see the PR description). 
Can we exclude these workflows from the RelVal temporarily, reserving the numbers associated to them to be used for the updated versions?

**Comment by Martin-Grunewald** [comment]
Hi,

This PR seems to break our addON HLT/HIon test, see here:

https://cmssdt.cern.ch/SDT/cgi-bin//showAddOnLogs.py/slc6_amd64_gcc491/www/sun/7.4-sun-02/CMSSW_7_4_X_2015-01-18-0200/addOnTests/

specifically the test:

https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc6_amd64_gcc481/CMSSW_7_4_X_2015-01-16-1400/addOnTests/logs/cmsDriver-hlt_mc_HIon_cmsDriver.py_TTbar_Tauola_13TeV_cfi_-s_GEN,SIM,DIGI,L1,DIGI2RAW_--mc_--scenario=HeavyIons_-n_10_--conditions_auto:run2_mc_HIon_--relval_9000,50_--data.log

Can you please have a look and suggest a fix?
Thanks!

**Comment by yetkinyilmaz** [comment]
Just answered in the sw thread, yes, we will PR a fix soon.

**Comment by franzoni** [comment]
Hello @yetkinyilmaz ,
in this big PR, the file: in Configuration/StandardSequences/python/VtxSmeared.py
the line: 'RealisticHI2011Collision':      

'IOMC.EventVertexGenerators.VtxSmearedRealisticHI2011Collision_cfi',

has been removed which holds the default SIM beam-spot for heavy ion (as verbally agreed at the orp wtih @mandrenguyen, see also the discussion in #6751).

Removing that line breaks the consistency of VtxSmeared.py . The breaking was not detected by tests which recycle the GEN-SIM for HI. 7_4_0_pre5 still had the line => re-doing the GEN-SIM relval was ok. The first release w/o the line is 7_4_0_pre5_ROOT6, and the subsequent IB's.

Why was the line removed ? Any change in LHC BS expectations for HI run2?
Please let's clarify and make sure we get things right in relation also to #7288.

**Comment by yetkinyilmaz** [comment]
Hi Giovanni,
this was a mistake.
we will commit the fix along with some other fixes in the currently open PR:
https://github.com/cms-sw/cmssw/pull/7287

**Comment by franzoni** [comment]
Thanks, @yetkinyilmaz.
If you're sure #7287 can be in pre6 => good as you say.
Otherwise, we can put it back as a standalone. I would not want to have a matrix in pre6 uncapable of re-doing gen-sim for HI.
@ktf @davidlange6 can you please take note, in relation to the pre6 schedule ?

**Pull request merged**
