### PR TITLE
MTD validation: ETL digi per LGAD multiplicity monitoring

### PR DESCRIPTION
**Pull request by fabiocos**
#### PR description:

Addition of four plots to the MTD validation, to monitor the DIGI multiplicity per LGAD sensor in the ETL. An LGAD could potentially fire one digi per pad, exceeding the histogram range. This range has been adjusted on the observed multiplicty in PU200 events, with a safety margin, to save space.

#### PR validation:

Code compiles, runs, and produces the desired output.

### CODE REVIEW

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
@parbol @ctarricone FYI

**Comment by emanueleusai** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
