### PR TITLE
Phase2-gex169 Modify the phas2 scenarios to accommodate the right set of hits for the HF

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Modify the phas2 scenarios to accommodate the right set of hits for the HF

#### PR validation:

Use the runTheMatrix test workflows

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
+geometry

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@srimanob Please approve this PR

**Comment by srimanob** [comment]
+Upgrade

**Comment by rappoccio** [comment]
+1

**Pull request merged**
