### PR TITLE
[12_5_X] Release dependent modules only after the worker has finished for scheduled modules

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

Backport of https://github.com/cms-sw/cmssw/pull/39245. Fixes a rare scheduling bug that was observed at the HLT in https://github.com/cms-sw/cmssw/issues/39064 (that was first mitigated in https://github.com/cms-sw/cmssw/pull/39201).

#### PR validation:

Tests in #39245 and #39484.

### CODE REVIEW

**Comment by makortel** [comment]
enable threading

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
The `EcalTPG_updateWeightIdMap_test` fails already in the IBs. (is a backport of some fix missing?)

The `TestIOPoolInputNoParentDictionary` seems to have the problems that were fixed later in 12_6_X. @smuzaffar, should we backport the fixes to 12_5_X?

**Comment by smuzaffar** [comment]
> The TestIOPoolInputNoParentDictionary seems to have the problems that were fixed later in 12_6_X. @smuzaffar, should we backport the fixes to 12_5_X?

@makortel , sure. I just opened the PR for 12.5.X

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
Apparently #39235 that fixed the `EcalTPG_updateWeightGroup_test` and `EcalTPG_updateWeightIdMap_test` has not been backported to 12_5_X.

**Comment by perrotta** [comment]
backport of https://github.com/cms-sw/cmssw/pull/39245.

**Comment by perrotta** [comment]
> Apparently #39235 that fixed the `EcalTPG_updateWeightGroup_test` and `EcalTPG_updateWeightIdMap_test` has not been backported to 12_5_X.

Thank you for pointing it out @makortel 
Now it is backported, see #39502

**Comment by perrotta** [comment]
please test with #39503

**Comment by perrotta** [comment]
+1

**Pull request merged**
