### PR TITLE
[100X] Packing and Unpacking for GEM

### PR DESCRIPTION
**Pull request by jshlee**
backport of #21681
request by commissioning team for CRUZET

@slava77 @kpedro88 @hyunyong

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
+1
- This PR makes the GEM packer/unpacker related files in 10_0 identical to those merged in the master with #21934 and #21681
- Backport to 10_0 is justified by the expected application for the commissioning data taking

**Comment by mommsen** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by fabiocos** [comment]
+operations

**Comment by fabiocos** [comment]
@lpernie @arunhep @ghellwig @ggovi @kpedro88 this PR is urgently needed for operations at P5 in 10_0_X, could you please check and sign or comment?

**Comment by perrotta** [comment]
hold

I am noticing now that this PR misses https://github.com/dildick/cmssw/blob/12c69c1b3882a9dcd3ca01981e2ac1e2c255ffd2/CondCore/GEMPlugins/BuildFile.xml , which was originally in PR  #21934 (not backported separately

Please @jshlee comment about it

**Comment by jshlee** [comment]
i didn't include it because it wasn't needed...

**Comment by perrotta** [comment]
unhold
(thank you @jshlee )

**Comment by arunhep** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Comment by ggovi** [comment]
+1

**Comment by fabiocos** [comment]
The code has been integrated already in the master branch, and it regularly runs in the run3/Phase2 MC workflows. It has been initially tested on cosmics data and checked with the DQM code #22500 , merged in the master branch as well.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
