### PR TITLE
Phase2-hgx353C Update the configuration fies in Validation/HGCalValidation for V18 geometry

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Update the configuration fies in Validation/HGCalValidation for V18 geometry

#### PR validation:

Use the runTheMatrix test workflows

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
+geometry

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by tjavaid** [comment]
+1

- spurious differences seen from unstable WF `12434.7` (open issue #39803 )

**Comment by rappoccio** [comment]
+1

**Pull request merged**
