### PR TITLE
python test updates for new sklearn version - 

### PR DESCRIPTION
**Pull request by davidlange6**
import change for sklearn cross_validation module (backwards compatible with our current skikit-learn version)
dropping deepdish as it appears to be no longer developed

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
please test

**Comment by fabiocos** [comment]
@santocch this is analysis specific, could you please have a look?

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Comment by santocch** [comment]
+1

**Pull request merged**
