### PR TITLE
Store DeepTauID in NanoAOD

### PR DESCRIPTION
**Pull request by mbluj**
#### PR description:

This PR it to store novel DeepTauIDs computed at MiniAOD step to NanoAOD tables. 
It can be seen as an follow up action to  #26796

Expected changes: six new variables are added to tau table in NanoAOD - three raw values (float numbers) of tau discriminants against jets, electrons and muons misidentified as taus, and three integer numbers encoding corresponding WPs. 
NanoAOD for old eras should not be modified and should work on top of corresponding MiniAOD inputs not containing DeepTauID variables.

Backport to 10_6_X for UL will follow shortly.

#### PR validation:

NanoAOD workflows were tested.

#### if this PR is a backport please specify the original PR:

N/A

### CODE REVIEW

**Comment by peruzzim** [comment]
please test workflow 1325.6,1325.7,1325.8,1329.1,136.7722,136.7952,136.8521

**Comment by fabiocos** [comment]
@mbluj @peruzzim @fgolf is the output as expected?

**Comment by peruzzim** [comment]
@fabiocos I'm checking that right now

**Comment by peruzzim** [comment]
+xpog

Code looks ok and changes are minimal. Tested in nanoAOD integration workflow in 10_6_X on all previous supported releases: no changes observed.
We will re-test it on 10_6_1_patch(N+1) relval MINIAODs, when available, including this.

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Comment by santocch** [comment]
+1

**Pull request merged**
