### PR TITLE
Removed HTMHTAnalyzer

### PR DESCRIPTION
**Pull request by Dr15Jones**
This module HTMHTAnalyzer has never worked since the CMSSW_7_0 when it was converted to a DQMEDAnalyzer from a helper class of the now defunct JetMETAnalyzer. Then analyze method did not match the DQMEDAnalyzer base class and therefore would never be called.

This works around the clang warning about the analyze method.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by fabiocos** [comment]
please test

failures look clearly unrelated to this PR

**Comment by Dr15Jones** [comment]
please test

**Comment by andrius-k** [comment]
+1

**Comment by fabiocos** [comment]
+1

as this module was not operational during Run2 and nobody has complained, it looks safe to just remove it

**Pull request merged**
