### PR TITLE
ME3/1 ME4/1 Phase-2 upgrade TMB

### PR DESCRIPTION
**Pull request by dildick**
In the past we had ME3/1 and ME4/1 OTMBs with RPC digis. I scrapped those a while ago, since RPC digis will not be sent to the local trigger. An OTMB class for ME3/1 and ME4/1 without RPCs was constructed. Those OTMBs are based on the ME1/1 OTMB for high-pileup running, but they are a lot simpler because (1) the wiregroups are not slanted and (2) the chambers are not divided into two readout sectors for halfstrips.

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by dildick** [comment]
@rekovic can you inspect and sign please?

**Comment by rekovic** [comment]
please test

**Comment by rekovic** [comment]
+1

**Comment by dildick** [comment]
Could this PR be integrated, please?

**Comment by dildick** [comment]
@fabiocos Could you please merge this PR?

**Comment by dildick** [comment]
@davidlange6  Could you please merge this PR?

**Comment by fabiocos** [comment]
+1

**Pull request merged**
