### PR TITLE
HCAL Fb DQM monitoring at layer1 - online DQM test 12_6_3

### PR DESCRIPTION
**Pull request by hftsoi**
#### PR description:
This PR includes additional calolayer1 DQM monitoring elements for HCAL LLP trigger feature bits. Added elements are the 6 fine grain bits occupancy readout at uHTR/layer1 and their comparison, and the single LLP feature bit output expected vs emulated. This is intended to be used for short test in online DQM production for MWGR, therefore PR is closed immediately after opened.

#### PR validation:
Validated by running offline DQM on past commissioning runs, expected plots are produced.

### CODE REVIEW

**Comment by emanueleusai** [comment]
please test

**Comment by syuvivida** [comment]
+1
We tested this PR at P5 with 12_6_3 and the streamers of run and @hftsoi confirmed the output root files contain the correct information (with added histograms).

**Comment by hftsoi** [comment]
Reopen this PR as the online DQM test went fine during MWGR on 9 Feb, and a new PR to master (https://github.com/cms-sw/cmssw/pull/40751) has been opened to make it permanent.

**Comment by emanueleusai** [comment]
type hcal

**Comment by emanueleusai** [comment]
backport of https://github.com/cms-sw/cmssw/pull/40751

**Comment by emanueleusai** [comment]
please test

**Comment by emanueleusai** [comment]
+1

**Comment by emanueleusai** [comment]
Differences in L1T CaloLayer DQM plot as expected

**Comment by perrotta** [comment]
@hftsoi please prepare a backport also for 13_0_X, if you want to use it during this year data taking, and not only during MWGRs

**Comment by hftsoi** [comment]
> 

Thanks @perrotta for reminding, backport to 13_0_X is opened at https://github.com/cms-sw/cmssw/pull/40768

**Comment by perrotta** [comment]
+1
- Master PR succesfully integrated in CMSSW_13_1_X_2023-02-14-2300

**Pull request merged**
