### PR TITLE
bsunanda:Run2-hcx35 Testing HGCal Geometry and Topology

### PR DESCRIPTION
**Pull request by bsunanda**
Adding the functionality of closed PR 11556

### CODE REVIEW

**Comment by ianna** [comment]
@cmsbuild please test

**Comment by ianna** [comment]
+1

**Comment by lgray** [comment]
@davidlange6 FYI it would be pretty useful for us (HGCal software community) to get as much as possible in with 7_6_0. This way we have a solid (and at least mechanically validated) base for the 7_7_0_preX releases.

**Comment by ianna** [comment]
@davidlange6 I agree with @lgray, besides this PR is unrelated to anything else except for HGCal in 76x.

**Comment by davidlange6** [comment]
why all the special mails?This PR has been signed for 0 working days…

**Comment by lgray** [comment]
@davidlange6 Just stating my concerns/interests and it's a rather big project. 
I can make a script to ping you after one day instead?

I guess @ianna agrees? Anyway, indeed it is Saturday.

**Comment by davidlange6** [comment]
+1
typically no special attention is needed for integration in development releases...

**Pull request merged**
