### PR TITLE
Soureek updating topHLTDQMOffline package under DQMOffline/Trigger

### PR DESCRIPTION
**Pull request by soureek**
Updating topHLTDQMOffline package under DQMOffline/Trigger so that it is able to read from "hltTriggerSummaryAOD" collection (present in both Data and MC) in addition to "hltTriggerSummaryRaw" collection (present in MC only and not in Data). Tested code to be ok by running the matrix for TTbar events.

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
-1
rejecting for now in 80x. see comments to be addressed in #13363

**Comment by davidlange6** [comment]
closing this while 81x comments are considered.

**Pull request closed without merging**
