### PR TITLE
L1T DQM Developments for CMSSW_8_0_9

### PR DESCRIPTION
**Pull request by swang373**
This PR combines all L1T DQM developments up to 8_0_9, making cms-sw/cmssw#14463 obsolete and merging cms-sw/cmssw#14634. A corresponding PR for 8_1_X is in the works (timescale unknown).

@vanbesien, this should be safe to patch onto an 8_0_10 release online. It was a little slow to test from overseas, but the code compiles and runs in a fresh 8_0_9 release.

@mzarucki @EsmaeelEskandari @nhaubrich @nsmith-, Is it okay to consider this the final PR based on the 8_0_9 DQM development branch? If so, I'll create an 8_0_10 DQM development branch for us to work on.

### CODE REVIEW

**Comment by mzarucki** [comment]
Thank you for this.

What about the changes in https://github.com/cms-l1t-offline/cmssw/pull/334 ?

The algo bit vs global BX fix is important (and has already been independently integrated online).

Furthermore, in this PR I added an extra set of plots for monitoring, additionally to this fix.

**Comment by vanbesien** [comment]
@mzarucki  @swang373 #14634 was merged in 8_0_10 (assuming this is what you mean with cms-l1t-offline#334 ), so will be included automatically.
Note that we will go to 8_0_10 in online DQM now. (8_0_10_patch2 to be precise, but that does not matter a lot in this case)

**Comment by mzarucki** [comment]
Yes, this fix is correct. However, the https://github.com/cms-l1t-offline/cmssw/pull/334 PR additionally has a set of extra plots. I could make a separate PR with only the plots, if this is desired.

**Comment by swang373** [comment]
Hi @mzarucki ,

I can merge cms-l1t-offline/cmssw#334 into this PR right now.

**Comment by mzarucki** [comment]
Hello, I will make a separate PR, so that the changes with the extra plots are on top the fix (to avoid any unnecessary conflicts or confusion).

Cheers,
Mateusz

**Comment by swang373** [comment]
@mzarucki , sounds good!

**Pull request merged**
