### PR TITLE
Run3-gex108x Modify all Run3 geometry scenarios by including demonstration chambers of GE21 & RPC, and detectors in the forrward region (BHM, PLT, BCMF) plus removing BSC

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Modify all Run3 geometry scenarios by including demonstration chambers of GE21 & RPC, and detectors in the forrward region (BHM, PLT, BCMF) plus removing BSC. To make it to work, need to merge several PR's: #36652, #36653 and the relevant PR's from the GEM group fixing creation of RECO geometry and DQM for GE21 demonstration chamber

#### PR validation:

To be tested when all those PR's are merged to the master. Tested in some standalone way

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by srimanob** [comment]
Hi @bsunanda 
Could you please provide more detail on why we modify the existing Run-3 geometry without creating the new one? I assume the one in GT is still be the one we use for production, but should XML reflect the same geometry? I would avoid merging piece-by-piece PR without a full picture. Thanks.

**Comment by civanch** [comment]
@srimanob , we discussed the situation at the last SIM meeting: https://indico.cern.ch/event/1105846/contributions/4652380/attachments/2367389/4042705/Sim-Talk137.pdf 

There are several minor modifications, which should not affect particle flow calibration but require fixes.

**Comment by qliphy** [comment]
urgent
as discussed at yesterday's ORP,  pre4 will include this PR together with #36715 to make a comparison with pre3.

**Comment by qliphy** [comment]
please test

**Comment by qliphy** [comment]
please test

**Comment by qliphy** [comment]
@bsunanda   Would you please have a check with the RelVals error on 11634.911?
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-ffc1c0/21800/runTheMatrix-results/11634.911_TTbar_14TeV+2021_DD4hep+TTbar_14TeV_TuneCP5_GenSim+Digi+RecoNano+HARVESTNano+ALCA/step3_TTbar_14TeV+2021_DD4hep+TTbar_14TeV_TuneCP5_GenSim+Digi+RecoNano+HARVESTNano+ALCA.log

**Comment by bsunanda** [comment]
@perrotta @qliphy I just sent an email to you two with CC's to a few others - we need to test 4 PR's together - 3 of them are already there (36645, 36679, 36745) and the fourth will come from Carl. With the first 3 PR's and the latest IB, the test goes through without any error or warning

**Comment by qliphy** [comment]
please test with #36679, #36745

**Comment by qliphy** [comment]
please abort
waiting for the PR from Carl with the right GT to be used for Run3 geometry in DB

**Comment by perrotta** [comment]
please test with #36755,#36679,#36750,#36765,#36766 
(test the whole set together)

**Comment by srimanob** [comment]
If the test is OK and geometry signs, please feel free to merge if you need it by today.

**Comment by cvuosalo** [comment]
Geometry will sign after the test results come in OK.

**Comment by cvuosalo** [comment]
+1

**Comment by cvuosalo** [comment]
Test results are as expected for the change in the Run 3 geometry.

**Comment by perrotta** [comment]
+1
- Merging together #36679 #36654 #36750 #36765 #36766 for pre4

**Comment by perrotta** [comment]
merge

**Comment by srimanob** [comment]
+Upgrade

This PR changes the dict2021 geometry configuration. Changes are expected on all Run-3 workflows in the short matrix. PR test runs fine and gets expected results.

**Pull request merged**
