### PR TITLE
L1T muon online DQM CMSSW_8_0_16

### PR DESCRIPTION
**Pull request by thomreis**
Contains bug fixes for the L1T muon data vs. emulator DQM module

Adds a DQM module to compare RegionalMuonCandBXCollections and configurations to use it for data vs. emulator comparisons for EMTF, OMTF, and BMTF, as well as BMTF/EMTF output vs. uGMT input comparisons.

### CODE REVIEW

**Comment by thomreis** [comment]
I have added the zero suppression DQM module.
This is related to PR https://github.com/cms-sw/cmssw/pull/15388

**Comment by thomreis** [comment]
Can someone launch the tests for this please?

**Comment by dmitrijus** [comment]
+1

**Comment by dmitrijus** [comment]
+1

**Comment by dmitrijus** [comment]
this merged upstream - please rebase!

**Comment by thomreis** [comment]
@dmitrijus I think PR #15388 should be merged first. Then I can rebase if the conflict still exists.

**Comment by thomreis** [comment]
This is covered by PR #16513 for 8_0_23. Closing.

**Pull request closed without merging**
