### PR TITLE
NanoAOD developments: 190520 version [102X]

### PR DESCRIPTION
**Pull request by peruzzim**
backport of #26844 

Updated set of NANOAOD developments for 10_2_X, includes and extends #26769.
Depends on #26794, cms-sw/cmsdist#4967, cms-sw/cmsdist#4970.

Includes backport of #26672

### CODE REVIEW

**Comment by peruzzim** [comment]
please test workflow 1325.6,1325.7,1325.8,1329.1,136.7722,136.7952,136.8521 with #26794, cms-data/PhysicsTools-NanoAOD#6

**Comment by mrodozov** [comment]
I have to see if we can test with 10_2 without merging the data external first.

**Comment by fabiocos** [comment]
@mrodozov @peruzzim the external is just an addition of a new file asa far as I can see, I think it could be merged to make things easier

**Comment by mrodozov** [comment]
@fabiocos 
https://github.com/cms-sw/cmsdist/pull/4967 is exactly the same case - for 10_2 I think we have to merge the data external (logic for 10_6 and 11 is assuming the structure on these branches which is not the same as on 10_2)

**Comment by peruzzim** [comment]
please test workflow 1325.6,1325.7,1325.8,1329.1,136.7722,136.7952,136.8521 with #26794, cms-sw/cmsdist#4967

**Comment by peruzzim** [comment]
please abort test

**Comment by peruzzim** [comment]
please test workflow 1325.6,1325.7,1325.8,1329.1,136.7722,136.7952,136.8521 with #26794, cms-sw/cmsdist#4967,cms-sw/cmsdist#4970

we also need the 2018 scales and smearings in 102X as additional externals

**Comment by peruzzim** [comment]
NANOAOD code now needs the `run2_nanoAOD_102Xv1` to be passed when running in 102X.
The tests fail because #26672 was not backported, this would fix 136.8521 but not 10824.0, that is created in a more complicated way via `Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py`, that does not seem to support a specific modifier to be passed only for the NANOAOD step.
Suggestions?

**Comment by peruzzim** [comment]
Another option would be to change NANOAOD code to run without modifiers in 102X (i.e. "assuming" to a certain extent that modifier set, when running).
This would complicate our code maintenance because the code in 102X and 106X would become more different, and the NANOAOD output would still not be fully correct (see explanation [1] below), but possible in principle.

[1]: the modifier is used to tune parameters of modules that also run during MINIAOD production, whose default configuration cannot be changed (see `RecoMET/METFilters/python/ecalBadCalibFilter_cfi.py`), so we would need the possibility to pass a modifier only to the NANOAOD step in sequence 10824.0, if we don't want to modify the MINIAOD output of that sequence.

**Comment by peruzzim** [comment]
please test workflow 1325.6,1325.7,1325.8,1329.1,136.7722,136.7952,136.8521 with #26794, cms-sw/cmsdist#4967,cms-sw/cmsdist#4970

I should have fixed the situation by backporting #26672 and properly handling the modifiers in the backport (discussed with @fabiocos, thanks)

**Comment by mrodozov** [comment]
I see 4967 is merged and not necessary, don't stop the test as it doesn't matter but you may omit it next time

**Comment by peruzzim** [comment]
+xpog

changes only in NANOAOD, all workflows running, also successfully re-tested in the integration repo after the minor fixes

**Comment by perrotta** [comment]
+1
- Changes wrt 10_2_X baseline do not affect reco packages, only nanoAOD and Configuration/PyReleaseValidation

**Comment by kpedro88** [comment]
+upgrade

**Comment by santocch** [comment]
+1

**Comment by fabiocos** [comment]
@prebello @zhenhu do you have any issue with this PR, or could you please otherwise sign? I understand that the update of the nano step is needed to properly use the fix for the ECAL MET (@peruzzim please confirm), it is entering nowhere else.

**Comment by peruzzim** [comment]
@fabiocos do you mean the change in relval configuration in commit 9cbf96d995453e2e65ce490e01ffb826e997626a?
That modifier is needed to redo few things on top of 102X miniAOD (not the fixed MET, but rather filter bits and scales&smearings), it's what we have been using already in NanoAODv4 production - updating relval configuration was forgotten and fixed in #26672, that is now backported.
New steps are added and the configuration of only one workflow is altered, so it cannot enter anywhere outside of workflow 136.8521. I would expect such a minor thing not to delay integration significantly.

**Comment by prebello** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
