### PR TITLE
Phase2-hgx354C Make the XML files required for the V19 version of HGCal with a new longitudinal structure

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Make the XML files required for the V19 version of HGCal with a new longitudinal structure

#### PR validation:

Put together by using the content of the flat file used in the V19 definition. The codes need to be modified and then a scenario can be built to make a full test

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
+geometry

**Comment by bsunanda** [comment]
@srimanob Please approve this

**Comment by srimanob** [comment]
+Upgrade

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
