### PR TITLE
Phase2-hgx360U Update the code for guard ring and mouse bite usage in full and partial wafers in HGCal geometry definition

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Update the code for guard ring and mouse bite usage in full and partial wafers in HGCal geometry definition

#### PR validation:

Use the runTheMatrix test workflows

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
