### PR TITLE
Run3-gex142C Use tokens rather than labels in accessing collections within Alignments/MuonAlignmentAlgorithms

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Use tokens rather than labels in accessing collections within Alignments/MuonAlignmentAlgorithms

#### PR validation:

Use runTheMatrix workflows

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Review by ChrisMisan — COMMENTED** [review]
fillDescription method should be added to the plugins

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by ChrisMisan** [comment]
+alca

- no differences aside from msgLogger

**Comment by rappoccio** [comment]
+1

* Technical migration.

**Pull request merged**
