### PR TITLE
Added removeSchedulingTokensFromModuleLabel function

### LINKED ISSUE #458: function to get module name from PSet without "decorations"
See https://github.com/cms-sw/cmssw/issues/40007

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

Function removes tokens added by the framework to denote how to schedule a module.

#### PR validation:

Code compiles and new test passes.

fixes makortel/framework#458

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
please test

the test failure can't possibly come from this change as the new function isn't used anywhere but the new test.

**Comment by makortel** [comment]
It seems that the failed job ends up asking the data from Vanderbilt after attempt to access it from the IB cache fails
```
04-Jan-2023 00:39:14 CET  Initiating request to open file root://eoscms.cern.ch//eos/cms/store/user/cmsbuild/store/hidata/HIRun2022A/HITestRawPrime0/RAW/v1/000/362/321/00000/fe35c38e-bcff-42e0-bf65-9f0f50d83382.root
%MSG-w XrdAdaptorInternal:  file_open 04-Jan-2023 00:39:15 CET pre-events
Failed to open file at URL root://eoscms.cern.ch:1094//eos/cms/store/user/cmsbuild/store/hidata/HIRun2022A/HITestRawPrime0/RAW/v1/000/362/321/00000/fe35c38e-bcff-42e0-bf65-9f0f50d83382.root?xrdcl.requuid=62e7d4d3-abbb-40d2-b69f-24c5a43a9206.
%MSG
%MSG-w XrdAdaptorInternal:  file_open 04-Jan-2023 00:39:15 CET pre-events
Failed to open file at URL root://eoscms.cern.ch:1094//eos/cms/store/user/cmsbuild/store/hidata/HIRun2022A/HITestRawPrime0/RAW/v1/000/362/321/00000/fe35c38e-bcff-42e0-bf65-9f0f50d83382.root?tried=&xrdcl.requuid=a12e51e9-4839-418a-b89b-1123957b6d58.
%MSG
04-Jan-2023 00:39:15 CET  Initiating request to open file root://eoscms.cern.ch//eos/cms/store/hidata/HIRun2022A/HITestRawPrime0/RAW/v1/000/362/321/00000/fe35c38e-bcff-42e0-bf65-9f0f50d83382.root
%MSG-w XrdAdaptorInternal:  file_open 04-Jan-2023 00:39:16 CET pre-events
Failed to open file at URL root://eoscms.cern.ch:1094//eos/cms/store/hidata/HIRun2022A/HITestRawPrime0/RAW/v1/000/362/321/00000/fe35c38e-bcff-42e0-bf65-9f0f50d83382.root?xrdcl.requuid=c9036a9b-1bce-416c-b30c-803404fd26f0.
%MSG
%MSG-w XrdAdaptorInternal:  file_open 04-Jan-2023 00:39:16 CET pre-events
Failed to open file at URL root://eoscms.cern.ch:1094//eos/cms/store/hidata/HIRun2022A/HITestRawPrime0/RAW/v1/000/362/321/00000/fe35c38e-bcff-42e0-bf65-9f0f50d83382.root?tried=&xrdcl.requuid=fe85f630-ac7a-4230-9313-48db105bc1b7.
%MSG
04-Jan-2023 00:39:16 CET  Initiating request to open file root://xrootd-cms.infn.it//store/hidata/HIRun2022A/HITestRawPrime0/RAW/v1/000/362/321/00000/fe35c38e-bcff-42e0-bf65-9f0f50d83382.root
04-Jan-2023 00:39:33 CET  Successfully opened file root://xrootd-cms.infn.it//store/hidata/HIRun2022A/HITestRawPrime0/RAW/v1/000/362/321/00000/fe35c38e-bcff-42e0-bf65-9f0f50d83382.root
%MSG-w XrdAdaptorLvl3:  AfterFile 04-Jan-2023 00:39:44 CET pre-events
Deactivating xrootd-se3-vanderbilt.sites.opensciencegrid.org from active sources because its quality (1420) is higher than 260 and 4 times larger than the other active server xrootd-se6-vanderbilt.sites.opensciencegrid.org (260) 
%MSG
%MSG-w XrdAdaptorLvl3:  AfterFile 04-Jan-2023 00:39:46 CET pre-events
Deactivating xrootd-se6-vanderbilt.sites.opensciencegrid.org from active sources because its quality (1076) is higher than 260 and 4 times larger than the other active server xrootd-se1-vanderbilt.sites.opensciencegrid.org (260) 
%MSG
[2023-01-04 00:43:23.981195 +0100][Error  ][AsyncSock         ] [xrootd-se1-vanderbilt.sites.opensciencegrid.org:1094.0] Socket error encountered: [ERROR] Socket error
```
I see the same happens also in IBs. I see the directory exists in the cache, but the file is indeed not there. @smuzaffar (or @cms-sw/externals-l2) could you check why this file does not end up being cached?

**Comment by makortel** [comment]
Comparison differences are in 11364.7 (#39803 )

**Comment by makortel** [comment]
+1

**Comment by perrotta** [comment]
+1

**Comment by smuzaffar** [comment]
@Dr15Jones , GCC 12 is not happy with this change
https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/el8_amd64_gcc12/CMSSW_13_0_X_2023-01-07-1100/FWCore/Utilities
```
FWCore/Utilities/src/path_configuration.cc:39:35: error: variable 'constexpr const std::array<char, 4> s_tokens' has initializer but incomplete type
```

**Comment by perrotta** [comment]
> @Dr15Jones , GCC 12 is not happy with this change https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/el8_amd64_gcc12/CMSSW_13_0_X_2023-01-07-1100/FWCore/Utilities
> 
> ```
> FWCore/Utilities/src/path_configuration.cc:39:35: error: variable 'constexpr const std::array<char, 4> s_tokens' has initializer but incomplete type
> ```

@missirol [suggests](https://github.com/cms-sw/cmssw/pull/40428#issuecomment-1375322277) that it is enough adding the missing `#include <array>` in FWCore/Utilities/src/path_configuration.cc
It is missing, in fact: a possible fix in that sense is in #40452

**Pull request merged**
