### PR TITLE
SkipEvent is removed [issue#43793]

### PR DESCRIPTION
**Pull request by denizsun**
#### PR description:
  - Issue was: SkipEvent not available in process.options from 13_3_X? #43793
  - The solution is to remove SkipEvent option. 
  -  SkipEvent is removed hcalcalib_dqm_sourceclient-live_cfg.py

### CODE REVIEW

**Comment by nothingface0** [comment]
> #### PR description:
> 
>     * Issue was: SkipEvent not available in process.options from 13_3_X? #437793
> 
>     * The solution is to remove SkipEvent option.
> 
>     * SkipEvent is removed hcalcalib_dqm_sourceclient-live_cfg.py

Tested at P5 without issues. Thanks!

Minor fix: change the title of the PR and description to the correct issue maybe: #43793

**Comment by tjavaid** [comment]
please test

**Comment by tjavaid** [comment]
+1

- spurious differences observed from unstable WF `12434.7` (open issue #39803 )

**Comment by rappoccio** [comment]
+1

**Pull request merged**
