### PR TITLE
SiStrip Gains Calibration: add unit test for Multi-Run Harvesting

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

This PR is meant to add the configuration and unit test to run the SiStrip Gains in multi-run harvesting mode. This is intended to avoid to have the algorithm unintentionally broken as it happened recently with PR #28622.
A new `MonitorElement`, `EventStats` is added to the module `SiStripGainsPCLWorker` to collect the number of events, tracks and clusters used by the calibration.
The content of this newly added ME is subsequently used to check in the new unit test `checkMultiRunHarvestingOutput` that the number of events effectively used coincides with the expectations. An hint is offered to the user in case it appears only the first run has been processed.
This PR is meant as a companion of the fix for the to the `EDMtoMEConverter` in #28934.

#### PR validation:

I tested this branch to fail (as expected) in `CMSSW_11_1_X_2020-02-18-2300` while it works correctly when merging commit 2972d1d0c46fc73dd65466834b1f5f0b4441775e locally. 
It also passes `runTheMatrix.py -l 1001.0 -t 4 -j 8 --ibeos`.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

This PR is not a backport and no backport is meant to be submitted.

**N.B.:  This PR shall be tested together with #28934 to succeed integration tests.**

cc:
@schneiml @pieterdavid @robervalwalsh

### CODE REVIEW

**Comment by christopheralanwest** [comment]
please test

**Comment by mmusich** [comment]
@christopheralanwest 

> please test

as I wrote in the PR description this is expected to fail. To succeed it needs to be tested together with 
#28934.

**Comment by christopheralanwest** [comment]
please test with #28934

Thanks, @mmusich

**Comment by mmusich** [comment]
@christopheralanwest 

> please test with #28934

based on the logs output, the bot did not pick up your command. I think one needs to abort first and then re-send the test command.
As for the xrootd issue, not sure why it complains, it seems to me the file is on eos:
```
$ eos ls -lart store/data/Run2016B/ZeroBias/ALCARECO/SiStripCalMinBias-18Apr2017_ver2-v1/120000/F4508A99-B534-E711-9ABC-842B2B42B584.root
-rw-r--r--   2 phedex   zh         2238185497 Jul  7  2017 F4508A99-B534-E711-9ABC-842B2B42B584.root
```
a glitch?

**Comment by christopheralanwest** [comment]
please abort

I'm not sure if the second set of tests is still ongoing

**Comment by christopheralanwest** [comment]
please test with #28934

**Comment by silviodonato** [comment]
Do you have any comments?  @franzoni @pohsun  @tlampen @tocheng @christopheralanwest

**Comment by pohsun** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
