### PR TITLE
ECAL - Switch off online ECAL RecHit GPU vs. CPU monitoring - 12_4_X

### PR DESCRIPTION
**Pull request by thomreis**
#### PR description:

Switches off the online ECAL RecHit GPU vs. CPU comparisons since the RecHit module is identical in both options.
~~Until PR #39373 is merged the collections are still consumed so the same existing RecHit collection is used for CPU and GPU inputs.~~
Requires PR #39373 to be merged since the RecHit collection tags have been removed from the configuration.

#### PR validation:

Configured and ran cmsRun with the configuration but no events were processed since the source is a stream that was not available. Should be tested on the playback system as well.

Backport of #39393

### CODE REVIEW

**Comment by thomreis** [comment]
Backport of https://github.com/cms-sw/cmssw/pull/39393

**Comment by thomreis** [comment]
enable gpu

**Comment by thomreis** [comment]
please test

**Comment by syuvivida** [comment]
Tested this PR at the playback of P5 using collision runs 357900, 357815, and cosmic run 356932. The ecalgpu client ran at fu-c2f11-15-01.cms without errors. Plots in the DQMGUI also look fine.

**Comment by rovere** [comment]
@thomreis do you need this for the next data-taking?
Do I understand correctly that #39373 is needed before this PR?

Thanks for clarifying!

**Comment by thomreis** [comment]
Hi @rovere, yes we would need this for data taking when we unpack the ECAL auxiliary collections with the CPU unpacker (see https://its.cern.ch/jira/browse/CMSHLT-2454).

No, PR #39373 is not needed before this PR. However, once #39373 is merged lines 91-95 of this PR could be removed as well  (https://github.com/cms-sw/cmssw/pull/39395/files#diff-7e9b17ce9f9a19ae82d8a705a90d5fab2e021a4f0e18f0a84d7a9875621c4224R91-R95).

**Comment by perrotta** [comment]
> Hi @rovere, yes we would need this for data taking when we unpack the ECAL auxiliary collections with the CPU unpacker (see https://its.cern.ch/jira/browse/CMSHLT-2454).
> 
> No, PR #39373 is not needed before this PR. However, once #39373 is merged lines [91-95](https://github.com/cms-sw/cmssw/pull/39395/files#diff-7e9b17ce9f9a19ae82d8a705a90d5fab2e021a4f0e18f0a84d7a9875621c4224R91-R95) of this PR could be removed as well.

@thomreis , while I don't know whether those lines need to be removed, or it is just a "nice to have", if we want to speed up the merging, could you please give for granted that #39373 gets merged in the next few hours and remove those lines since now if needed, in particular starting from the master version of this PR?

**Comment by thomreis** [comment]
@perrotta removing the lines is a nice to have to clean up the configuration if the RecHit monitoring is switched off. This is done now in all three PRs with the latest commit.
Please note that this means that the configuration will most likely crash on the playback system if #39373 is not there. I am not sure for the matrix tests though.

**Comment by thomreis** [comment]
please test with #39373

**Comment by thomreis** [comment]
please test with #39373

**Comment by thomreis** [comment]
please test with #39373

**Comment by syuvivida** [comment]
Just a note, the test at playback of this PR was done with also PR 39373. Results were OK. (no errors from DQM^2 and DQM Histograms of ECAL are normal.)

**Comment by emanueleusai** [comment]
+1

- P5 tests OK
- GPU comparison differences known

**Comment by perrotta** [comment]
+1

**Pull request merged**
