### PR TITLE
Run3-sim45 Remove reference to G4DataQuestionaire

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

This reference is not needed in current Geant4 version used and the sequence G4DataQuestionaire.hh will be dropped in future Geant4 versions

#### PR validation:

Tested with the standard matrix

#### if this PR is a backport please specify the original PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by civanch** [comment]
@fabiocos, this PR is simple but necessary step for new Geant4. Removed code is obsolete and useless.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
