### PR TITLE
ctpps pixel dqm update

### PR DESCRIPTION
**Pull request by popovvp**
2 files modified (to include new station):
plugins/CTPPSPixelDQMSource.cc
python/ctppsPixelDQMSource_cfi.py

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by popovvp** [comment]
We urgently need to have these changes operational in point 5. If I'm not mistaken
there is a way to have changes implemented in the dqm even before they are in
cmssw.
Could you please try to take any action needed to have the changes operational
in dqm? We are going to have data ready very soon.
The same code backported to PR 22551
thanks

**Comment by fabiocos** [comment]
@popovvp this PR doubles the size of the CTPPS/TrackingPixel DQM folder, increasing its size by 6 MB. How is this justified?

**Comment by popovvp** [comment]
yes, doubled due to including the second station, that increase the number of histograms in ~2 times. Sorry.

**Comment by fabiocos** [comment]
@popovvp this becomes one of the largest single folders of the whole DQM output. Do you see any possible way to slim down the size of the histograms?

**Comment by fabiocos** [comment]
@popovvp @fabferro in order to speed up the integration in view of the data taking, could you please address my question?

**Comment by fabiocos** [comment]
@popovvp thanks, when do you plan to have the new code available for test and integration?

**Comment by popovvp** [comment]
doing now, guess have it today-tomorrow

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
@dmitrijus @jfernan2 could you please check? I assume this is ok to move forward...

**Comment by fabiocos** [comment]
@popovvp in order to deploy it in operations we will need a backport to 10_1_X, the sooner the PR is available the faster it will be (I understand from @fabferro and V. Avati that this is definitely needed for the RP alignment run in about 10 days from now)

**Comment by popovvp** [comment]
does it mean I have to open new PR to 10_1_X

**Comment by fabiocos** [comment]
@popovvp yes

**Comment by fabiocos** [comment]
DQM had already approved this PR, and the latest update is transparent (replace an array of 2D histograms with a corresponding array of 1D histograms). As this PR is needed for 10_1_1 I merge it, @dmitrijus @jfernan2 can comment further in case

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Pull request merged**
