### PR TITLE
add `ClusterShapeHitFilterESProducer_cfi` to `dedxEstimators_Cosmics_cff` as it's now requested by `DeDxHitInfoProducer`

### LINKED ISSUE #46553: DQM `visualization-live` and `visualization-live-secondInstance` crash during HI cosmics
We noticed that the DQM visualization clients,  [`visualization-live`](https://github.com/cms-sw/cmssw/blob/master/DQM/Integration/python/clients/visualization-live_cfg.py) and [`visualization-live-secondInstance`](https://github.com/cms-sw/cmssw/blob/master/DQM/Integration/python/clients/visualization-live-secondInstance_cfg.py) crash during some of the latest cosmic runs, namely: 387579,387557,387556,387555,387552,387548,387546,387544,387541,387539,387531,387338,387240,387235,387212,387209,387207

The exception is:

```
----- Begin Fatal Exception 29-Oct-2024 15:06:19 CET-----------------------
An exception of category 'NoProductResolverException' occurred while
   [0] Processing  Event run: 387552 lumi: 9 event: 19781392 stream: 3
   [1] Running path 'FEVToutput_step'
   [2] Prefetching for module JsonWritingTimeoutPoolOutputModule/'FEVToutput'
   [3] Calling method for module DeDxHitInfoProducer/'dedxHitInfoCosmicTF'
Exception Message:
No data of type "ClusterShapeHitFilter" with label "ClusterShapeHitFilter" in record "CkfComponentsRecord"
 Please add an ESSource or ESProducer to your job which can deliver this data.
----- End Fatal Exception -------------------------------------------------
```

More logs [here](https://cmsweb.cern.ch/dqm/dqm-square/api?what=get_logs&id=dqm-source-state-run387557-hostdqmfu-c2b04-45-01-pid2536056&db=production).

First instance was during run 387207 (24/10/2024). Not all cosmic runs lead to this behavior, however. There was no such crash during 387559, for example. 

We were using `CMSSW_14_1_1` and `CMSSW_14_1_4_patch1` at the time of the crashes, with Global Tag `141X_dataRun3_Express_v3`. We have not tested yet if this is reproducible with `14_0_X`.

Any input is appreciated.

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

Simple fix for https://github.com/cms-sw/cmssw/issues/46553
resolves https://github.com/cms-sw/cmssw/issues/46553

#### PR validation:

```
cmsRun DQM/Integration/python/clients/visualization-live-secondInstance_cfg.py runInputDir=/eos/user/d/dpapagia/data outputBaseDir=./output runNumber=387552 runkey=cosmic_run
```

runs fine (streamers courtesy of @nothingface0)

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Not a backport, but will need to be backported to CMSSW_14_1_X for operations during 2024 `HIon` run.

### CODE REVIEW

**Comment by mmusich** [comment]
type bug-fix

**Comment by mmusich** [comment]
urgent

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
resolves https://github.com/cms-sw/cmssw/pull/46563

**Comment by mandrenguyen** [comment]
ignore tests-rejected with ib-failure

**Comment by jfernan2** [comment]
+1

**Comment by mandrenguyen** [comment]
ignore tests-rejected with ib-failure

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
