### PR TITLE
Pr 11 x calo particles

### PR DESCRIPTION
**Pull request by bmarzocc**
PR description:

This PR is needed for the ECAL Run3 clustering studies. In this PR I change the dataformat of the simClusters, which are used for producing the caloParticle collection. Once this is merged, a central production of samples will be asked. For the moment I ask the PR into 11_0_X  CMSSW, but please let me know if you want this PR on the master or some other branches.

Badder

### CODE REVIEW

**Comment by fabiocos** [comment]
@bmarzocc this PR needs to be updated, there is a conflict to be resolved, and the title should become a bit more meaningful. Do you expect to resume work on it? Otherwise please close it and reopen when you can.

**Comment by bmarzocc** [comment]
@fabiocos Ok let me fix it within tomorrow. Sorry I was busy with other things and it remained pending. "title should become a bit more meaningful", what do you mean exactly? What should I write?

**Comment by fabiocos** [comment]
@bmarzocc as the title is used for the release notes https://cmssdt.cern.ch/SDT/ReleaseNotes/CMSSW_11/CMSSW_11_0_0_pre13.html it should briefly explain what is done, the present title looks a commit name quickly set

**Comment by bmarzocc** [comment]
@fabiocos: as in CMSSW master this PR gives many conflicts due to some other changes in CMSSW, I decided to start from scratch and open a new PR: https://github.com/cms-sw/cmssw/pull/28579
This can be close.

**Pull request closed without merging**
