### PR TITLE
Disable JME Nano workflows due to Nano-prompt dev

### PR DESCRIPTION
**Pull request by srimanob**
#### PR description:
This PR is to disable JME nano workflows for now, to avoid crash in IB. The crash is due to the ongoing dev of Nano-prompt where JME should fix their sequence.

#### PR validation:
-

#### if this PR is a backport please specify the original PR and why you need to backport that PR:
Not a backport, and no need of backport.

### CODE REVIEW

**Comment by srimanob** [comment]
@cmsbuild please test

**Comment by srimanob** [comment]
+Upgrade

**Comment by qliphy** [comment]
@cms-sw/pdmv-l2  Do you have any comment?

**Comment by kskovpen** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
