### PR TITLE
Remove dead assignments from L1Trigger/CSCTrackFinder

### PR DESCRIPTION
**Pull request by perrotta**
A big chunk of dead assignments is reported by the static analyzer in L1Trigger/CSCTrackFinder
This PR tries to get rid of them (perhaps some further iteration will be needed)

The code builds succesfully
No changes expected in outputs

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
There is one more dead assignment in L1Trigger/CSCTrackFinder/src/CSCTFPtLUT.cc, namely the `absPhi12` assignment at https://github.com/cms-sw/cmssw/blob/8ede5a2cb7e88f8a2343a3ebf69d001b92c0a114/L1Trigger/CSCTrackFinder/src/CSCTFPtLUT.cc#L413

I'd prefer to let it unattended for the moment, and refer to the experts to evaluate whether it is a real dead branch, or if it rather witnesses something to be fixed/adjusted, because the original intention of the developer was different.

@dildick @ptcox @barvic FYI

**Comment by dildick** [comment]
@perrotta I have no idea. I don't know much about the old track-finder. Probably best to leave it unchanged?

**Comment by perrotta** [comment]
please test

**Comment by cecilecaillol** [comment]
+l1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
