### PR TITLE
adding sum of PS weights

### PR DESCRIPTION
**Pull request by defranchis**
#### PR description:

Seems like the sum of the PS weights was missing from the nanoAODs. This PR adds two branches to the "Run" tree, containing the missing information. The format is identical to that of other weights (e.g. scale, PDFs)

#### PR validation:

Run on MiniAOD sample TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8 using CMSSW_10_6_27 (one version after the one used to produce NanoAODv9)

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Not a backport

### CODE REVIEW

**Comment by mariadalfonso** [comment]
please test

**Comment by mariadalfonso** [comment]
Screen Shot 2022-05-22 at 19 05 20

**Comment by mariadalfonso** [comment]
+xpog
new set of weights added in the Run2 tree (see snapshot https://github.com/cms-sw/cmssw/pull/38002#issuecomment-1133938986)

**Comment by qliphy** [comment]
+1

**Comment by defranchis** [comment]
Thanks a lot! Is a backport necessary?

**Comment by mariadalfonso** [comment]
> Thanks a lot! Is a backport necessary?

indeed, better to have in 12_4 as well.

**Pull request merged**
