### PR TITLE
[Backport] uGT fix for muon showers full emulation and for HMT mismatches in the DQM workflow

### PR DESCRIPTION
**Pull request by elfontan**
#### PR description:
Backport of https://github.com/cms-sw/cmssw/pull/40773 to CMSSW_13_0_X targeting the first release created for the 2023 data-taking.

The purpose of this PR is to address multiple issues at the GT level related to the muon shower emulation. Here two main items are discussed:
1) **uGT emulation of HMT**
2) **DQM mismatches** 

All details can be found in the conversation of the main PR.
Thanks @eyigitba and @aloeliger for the work and the discussion. 

#### PR validation:
Basic tests performed successfully starting from CMSSW_13_0_X_2023-02-21-1100
> cmsrel CMSSW_13_0_X_2023-02-21-1100
> cd CMSSW_13_0_X_2023-02-21-1100/src
> cmsenv
> git cms-addpkg L1Trigger/L1TGlobal 
> git cms-addpkg DQM/L1TMonitor 
> scram b distclean 
> git cms-checkdeps -a -A
> scram b -j 8
> scram b runtests 
> scram build code-checks
> scram build code-format

### CODE REVIEW

**Comment by aloeliger** [comment]
backport of #40773

**Comment by emanueleusai** [comment]
please test

**Comment by emanueleusai** [comment]
type l1t

**Comment by emanueleusai** [comment]
backport of https://github.com/cms-sw/cmssw/pull/40773

**Comment by aloeliger** [comment]
+l1

**Comment by emanueleusai** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
