### PR TITLE
[L1T] fix negative shift

### PR DESCRIPTION
**Pull request by cecilecaillol**
#### PR description:

Addressing part of issue https://github.com/cms-sw/cmssw/issues/35010, following comment https://github.com/cms-sw/cmssw/issues/35010#issuecomment-1112081142

### CODE REVIEW

**Comment by cecilecaillol** [comment]
please test for CMSSW_12_5_UBSAN_X

**Comment by smuzaffar** [comment]
please test for CMSSW_12_5_UBSAN_X

**Comment by cecilecaillol** [comment]
+l1

**Comment by perrotta** [comment]
+1

**Comment by skinnari** [comment]
@cecilecaillol @smuzaffar this PR was put in without an "OK" from any L1 tracking expert and it is unfortunately not correct to change just this line as done. it kills the tracking efficiency for the negative endcap (see attached plot, thanks to @ryanm124 for checking this and making the plot). and apologies from my end for not responding to the PR sooner, i am on leave. 

either way, please revert this PR ASAP.

D76_TTbarPrompt_PU200_iMath_eff_eta

**Comment by cecilecaillol** [comment]
> @cms-sw/l1-l2 Please have a look at above comment.

@qliphy How can I revert this PR? Is it possible to do it from here? Or should I make a new PR?

@skinnari Sorry about this, I didnt expect it would affect the tracking efficiency. Can you have a look at the issue https://github.com/cms-sw/cmssw/issues/35010 and suggest a way to gix the UBSAN warning in this file?

**Comment by perrotta** [comment]
@skinnari @cecilecaillol I see that the revert PR is ready to get merged. At  the same time, could you please check the logic and provide the actual fix, or alternatively explain why the current logic that applies bitwise operations on negative integers has to be considered instead?

**Comment by skinnari** [comment]
@ryanm124 has a possible fix (see below), can someone please have a look? 

https://github.com/cms-sw/cmssw/issues/35010#issuecomment-1155315448

**Pull request merged**
