### PR TITLE
L1T phase-2 Update old PF emulators with E/gamma integration, and add new emulators (12_0_X version)

### PR DESCRIPTION
**Pull request by cecilecaillol**
#### PR description:
This PR: 
integrates the E/gamma emulation into the existing PF setup. No changes are expected on PF side, and the performance of the new e/gamma should be broadly compatible with the old one

adds the PF & E/gamma emulators based on HLS datafomats. These are provided in a separate file, L1Trigger/Phase2L1ParticleFlow/python/l1ctLayer1_cff.py producing a collections of PF & Puppi candidates called l1ctLayer1:PF and l1ctLayer1:Puppi and of e/gamma candidates l1ctLayer1EG.

#### PR validation:

Rebase from https://github.com/cms-l1t-offline/cmssw/pull/893

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Rebase from https://github.com/cms-l1t-offline/cmssw/pull/893

### CODE REVIEW

**Comment by cecilecaillol** [comment]
please test

**Comment by cecilecaillol** [comment]
@cerminar @gpetruc I am porting your PR to central CMSSW. Any idea how to solve the error above? PFRegionEmu seems to be defined only in https://github.com/cms-l1t-offline/cmssw/blob/phase2-l1t-integration-CMSSW_11_1_7/L1Trigger/Phase2L1ParticleFlow/plugins/L1TCorrelatorLayer1Producer.cc#L438. But I can compile locally and the porting to 11_3 works...

**Comment by gpetruc** [comment]
Hi,

It should be defined also in src/newfirmware/dataformats/layer1_emulator.h

We're going to have a new PR anyway shortly, so perhaps you could even wait
for that before doing the rebase to 11_3?

Giovanni

**Comment by srimanob** [comment]
@cecilecaillol 
Do you want to keep this PR open?

**Pull request closed without merging**
