### PR TITLE
MuonSegmentMatcher: add RPC hits, remove MuonServiceProxy dependence

### PR DESCRIPTION
**Pull request by ptraczyk**
Added a method to MuonSegmentMatcher that performs matching of RPC hits. This is currently not used in standard RECO so no difference in reco output. Also removed the dependence on MuonServiceProxy. This resulted in a bunch of configuration files needing an update, which is also a part of this PR.

### CODE REVIEW

**Comment by perrotta** [comment]
-1

HLT configurations must be modified in ConfDB, and only after that dumped in the release.
Please add your new parameter in your modified modules using the ParameterSetDescription or, at worst, add it with an existAs() check, so that it does not comply if it is not included in the steering python configs. Then, once your pull request will be merged, the new configurations can be parsed in the HLT menu.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/10482	1240bf7
- code changes look ok (static analyzer is ok as well)
- jenkins tests pass and comparisons with the baseline show no differences as expected

**Comment by slava77** [comment]
DQM signature is needed here
@deguio could you please check.

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
