### PR TITLE
HLT menu development for `13_0_X` (3/N) [`13_1_X`]

### PR DESCRIPTION
**Pull request by missirol**
#### PR description:

Development of HLT menus for `CMSSW_13_0_X`.

This is the PR for the `master` branch, which will then be backported to `13_0_X` (the latter is the release cycle currently used for Run-3 HLT-menu development).

This PR includes the integration of the following JIRA tickets.

  - [CMSHLT-2531](https://its.cern.ch/jira/browse/CMSHLT-2531): [HIG] use tighter DeepJet b-tag wp in MSSM-Hbb triggers
  - [CMSHLT-2606](https://its.cern.ch/jira/browse/CMSHLT-2606): [PPS] add `ExpressPPSRandom` stream and PD
  - [CMSHLT-2631](https://its.cern.ch/jira/browse/CMSHLT-2631): [EXO] add 2 diphoton backup triggers to GRun
  - [CMSHLT-2641](https://its.cern.ch/jira/browse/CMSHLT-2641): [TSG] removed unused global PSets (post Run2022)
  - [CMSHLT-2642](https://its.cern.ch/jira/browse/CMSHLT-2642): [TSG] set PS=0 for all MC Paths in all PS columns
  - [CMSHLT-2643](https://its.cern.ch/jira/browse/CMSHLT-2643): [EXO] add eta restriction to delayed-DiPhoton10 triggers
  - [CMSHLT-2647](https://its.cern.ch/jira/browse/CMSHLT-2647): [TSG] removed CUDAService module
  - [CMSHLT-2648](https://its.cern.ch/jira/browse/CMSHLT-2648): [HCAL] remove `HLTHcalCalibTypeFilter` module from `HLT_HcalCalibration_v` trigger

It also includes the migration of the HLT menus ("Fake*", frozen, and development ones) to the `ConfDB` template for `CMSSW_13_0_0`.

#### PR validation:

TSG tests.

#### If this PR is a backport, please specify the original PR and why you need to backport that PR. If this PR will be backported, please specify to which release cycle the backport is meant for:

`CMSSW_13_0_X`

### CODE REVIEW

**Comment by missirol** [comment]
enable gpu

**Comment by missirol** [comment]
please test

**Comment by missirol** [comment]
+hlt

Changes in the outputs of PR tests are in line with updates to the HLT GRun menu, and the change in name of the frozen/fake HLT menus.

**Comment by perrotta** [comment]
+1

**Pull request merged**
