### PR TITLE
Bph reco update 200422

### PR DESCRIPTION
**Pull request by ronchese**
#### PR description:

Fixes/improvements following PR "Bph reco update #29253"
https://github.com/cms-sw/cmssw/pull/29253
(already merged since CMSSW_11_1_0_pre6)
No dependence on other PRs ; no change in output.

#### PR validation:

Full test directory with runTheMatrix.py output here:
https://cernbox.cern.ch/index.php/s/CEZgwME2zdgNDMQ

Other tests performed processing a few events in datasets:
/Charmonium/Run2018A-PromptReco-v2/MINIAOD (with CMSSW_10_1_5)
/Charmonium/CMSSW_11_0_0_pre6-110X_dataRun2_v5_RelVal_2018A-v1/MINIAOD (with CMSSW_11_0_0_pre12)
and looking at the output.

### CODE REVIEW

**Comment by santocch** [comment]
please test

**Comment by silviodonato** [comment]
Do you have any comments @santocch ?

**Comment by santocch** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
