### PR TITLE
C++11 modernization for FWLite

### PR DESCRIPTION
**Pull request by wmtan**
This PR upgrades the FWLite code to C++11/C++14 standards.
This includes:
1) replacing auto_ptr with unique_ptr
2) using make_shared and make_unique where appropriate
3) Replacing 0 with nullptr where applicable
4) changing iterator loops to range based for loops where appropriate.
5) using the auto keyword in for loops.
Also, the const qualifier was added to some for loops where it was missing.
Some of these changes are prerequisites for implementing propagate_const in FWLite code,
which will be done in subsequent PR's.

### CODE REVIEW

**Comment by davidlange6** [comment]
@wmtan - this does not merge

**Comment by wmtan** [comment]
@davidlange6 OK, I will rebase it.

**Comment by wmtan** [comment]
@davidlange6 Rebased. Should merge now.

**Comment by davidlange6** [comment]
please test

**Comment by wmtan** [comment]
@cmsbuild please test

**Comment by Dr15Jones** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
