### PR TITLE
Explicitly define all types allowed for 'precision' NANO parameter

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

Declare precision as optional.allowed to explicitly allow type checking in python.

#### PR validation:

Tested generating of configuration for workflow 546.0, which had previously failed.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
@cms-sw/xpog-l2 this is necessary to fix a unit test failure in the IBs.

**Comment by perrotta** [comment]
urgent
(it fixes IB errors in wfs 546.0, 547.0, 548.0)

**Comment by simonepigazzini** [comment]
+xpog

**Comment by perrotta** [comment]
+1

**Pull request merged**
