### PR TITLE
HLT v2.1 update (80X)

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
HLT v2.1 update (80X)
Based on CMSSW_8_0_10.
Backport of #14811

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by Martin-Grunewald** [comment]
@Dr15Jones 
Could you please sign - the change in Utilities/ReleaseScripts updates the addOn tests.

**Comment by Dr15Jones** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
