### PR TITLE
Fixes for the neutron background simulation with GEANT

### PR DESCRIPTION
**Pull request by calabria**
Same as https://github.com/cms-sw/cmssw/pull/18596, it is needed for the Muon TDR production.
@kpedro88 @pietverwilligen @jshlee @bapavlov

### CODE REVIEW

**Comment by kpedro88** [comment]
please test

**Comment by kpedro88** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by civanch** [comment]
please test

**Comment by kpedro88** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
