### PR TITLE
HBHE: bugfix for MAHI on issue of missing SOI+4 subtraction

### PR DESCRIPTION
**Pull request by hmiaozh**
#### PR description:

This subtraction should goes from 0 to 9 for 10TS, and 1 to 8 for 8TS because of the presence of this "delta". While for the current code, without "delta" present in the index, it's actually going from 0 to 7, missing the last TS, which results in some weird behavior in the fitting for the +4BX. After this fix, this behavior's gone. 
Details can be viewed in slides: [https://indico.cern.ch/event/839463/contributions/3521507/attachments/1892056/3120549/Wired_Behavior_of_Mahi_at_4BX.pdf](https://indico.cern.ch/event/839463/contributions/3521507/attachments/1892056/3120549/Wired_Behavior_of_Mahi_at_4BX.pdf)
And the check of the impact on jets and MET are:  [https://indico.cern.ch/event/839463/contributions/3521507/attachments/1892056/3125214/20190812_Jae_NoMtg_4BXImpact.pdf](https://indico.cern.ch/event/839463/contributions/3521507/attachments/1892056/3125214/20190812_Jae_NoMtg_4BXImpact.pdf)

#### PR validation:

Basic tests are performed and all succeed.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@hmiaozh 
please edit the PR title to be a bit more descriptive of a nature of the change (e.g. "bugfix for MAHI with large TS offset" or smth)

**Comment by fabiocos** [comment]
@hmiaozh could you please remind me whether this is impacting the UL processing?

**Comment by mariadalfonso** [comment]
@fabiocos 

yes this fix apply to the UL both data and MC and for all three years.
We discussed within the DPG and decided not to put at this late stage in the MC/data reprocessing.

1. the effect on the IT energy is negligible
2. has been there since the 2018 prompt and re-reco of the first part and there was no report on the impact on the physics from the offline analyses
3. the rec-hit calibration of the legacy is now self consistent with the legacy local reco

@arapyan @jaehyeok

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/27950	92a64ae 
- code changes are in line with the PR description
- jenkins tests pass and comparisons with the baseline show differences starting from ```hbhereco``` hits and further downstream. The changes are fairly small.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
