### PR TITLE
Changed throw() to noexcept

### PR DESCRIPTION
**Pull request by Dr15Jones**
The throw keyword has been deprecated in C++11 and replaced with the noexcept specification.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by Dr15Jones** [comment]
The test failure is unrelated to this pull request.
[It looks like a temporary output file was deleted before a test that depended upon it was run.]

**Comment by Dr15Jones** [comment]
please test

**Comment by davidlange6** [comment]
+1

**Pull request merged**
