### PR TITLE
add file ECALAndHCALCaloJetLinker.cc

### PR DESCRIPTION
**Pull request by yongjiexin3**
add a new file for ECal and HCal Linking named :  ECALAndHCALCaloJetLinker.cc
which delete the |Ecal.Eta| > 2.5 cut.

### CODE REVIEW

**Comment by bachtis** [comment]
Hi ,Just to add: This is needed for an alternative Calo only reconstruction 
at HLT showing big improvements at L2. This file is not used in offline reco 
so no changes are expected to anything by its addition. Please merge this when possible since 
we need it very soon in 74X

**Comment by slava77** [comment]
please provide a configuration to test this feature.

**Comment by davidlange6** [comment]
please test

**Comment by degano** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/7399	14ec806
checked in CMSSW_7_4_0_pre6 /test area sign506 /

I used the supplied config and ran it in the reconstruction step after supplying regular reco inputs instead of hlt inputs. The code runs ok and takes about the same time as the regular particleFlowBlock and makes output of a similar size.
This is a good enough test at this point (the feature is not enabled currently).

**Pull request merged**
