### PR TITLE
relval scripts update, 2015c data workflows, a couple of fixes.

### PR DESCRIPTION
**Pull request by hengne**
List of updates:
1.) GT / HLT menu updates from Martin @Martin-Grunewald and Marco @mmusich 
2.) Remove test dqm gui url which will stop service in Oct. 12..
3.) Fix bug in "LumiList" selection 
4.) Add new 2015c 25ns data workflows.
5.) Add back mis-removed workflow 1337 "SMS-T1tttt_mGl-1500_mLSP-100_13"
6.) Fix ALCATT step for 13TeV for workflow 1325 "TTbar_13"
7.) Fix ALCAMIN step for 13TeV for workflow 1311 "MinBias_13"
8.) Update deprecated input datasets for workflows "ZElSkim2012B", "ZElSkim2012C", and "ZElSkim2012D".
9.) Regular updates of Relval mixing/premixing inputs. 
10.) New feature to use "global sybolic tag" in relval scripts to automatically choose the right L1 menu that matches with the chosen HLT menu.
11.) Apply New HCAL customise function in 13TeV fullSim and 2015 data workflows. 
12.) Update golden json according to announcement 25 sept. 2015 on HN: https://hypernews.cern.ch/HyperNews/CMS/get/physics-validation/2496.html
13.) Fix an issue in New_HCAL customisation function for PU premixing workflows.

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by hengne** [comment]
sorry, this is because of a typo in my last minute update of the golden
json file:
DPGAnalysis/Skims/data/Cert_246908-XXXXXX_13TeV_PromptReco_Collisions15_JSON.txt

fixed now.

Hengne

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
-1 
for bc47c2265791673542539c567f834220c9baf102. This GTs are not meant for autoCond

**Comment by hengne** [comment]
@mmusich OK, i can change back to the default version, but then i fail to remember why we were changing them to the customized version (e.g. with per crystal pulse shapes for multifit)?  Would changing it back to default one work with e.g. the new ecal local reco?

**Comment by mmusich** [comment]
@hengne of course it will work (in the sense that it won't crash) you will just get different conditions.
The purpose of my providing the "customized" GTs is due to the fact that we still don't have fully consistent re-reco GlobalTags and therefore to speed up the validation procedure I created a special set based on the Prompt and the online ones by adding the calorimeter scale changes. This will be of course included in the next set of GTs, hopefully together with another consistent set of updates

**Comment by mmusich** [comment]
please test

**Comment by hengne** [comment]
@mmusich  ok, thanks!  clear.

**Comment by hengne** [comment]
ping   -- @perrotta, @cmsbuild, @civanch, @diguida, @danduggan, @boudoul, @franzoni, @cerminar, @fabozzi, @Martin-Grunewald, @srimanob, @mdhildreth, @fwyzard, @mmusich

**Comment by fabozzi** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by mmusich** [comment]
+1
same changes as in #11391 (not yet merged)

**Comment by Martin-Grunewald** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
