### PR TITLE
Modernize HcalDbProducer

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

This PR modernizes HcalDbProducer (as part of #26748) by
- moving the contents of the header to the source file
- using ESGetToken
- replacing repeated patterns with generic functions that take advantage of the ESGetToken declarations

I took the liberty of modifying a bit the format of the optional printouts for some products in order to keep the overall structure generic (and thus deducing information from types as much as possible).

#### PR validation:

Limited matrix runs, no changes expected.

### CODE REVIEW

**Comment by makortel** [comment]
@Dr15Jones in case you're interested to take a look

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by kpedro88** [comment]
@abdoulline FYI

**Comment by pohsun** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
