### PR TITLE
Add displacedJet skim / add relval steps / add RAW+miniAOD event content (new IB)

### PR DESCRIPTION
**Pull request by kfjack**
Integrate all of the modifications from PR #21260 with new IB

Add displacedJet skim
Add the corresponding relval steps
Add RAW+AOD event content

Note: now the new workflow(s) to be tested are 136.840, 136.841, 136.842, 136.843.

### CODE REVIEW

**Comment by fabozzi** [comment]
please test workflow 136.840,136.841,136.842,136.843

**Comment by kfjack** [comment]
Could we test the workflow again? Previous tests were rejected simply due to I/O error.

**Comment by fabozzi** [comment]
please test workflow 136.840,136.841,136.842,136.843

**Comment by fabozzi** [comment]
lease test workflow 136.840,136.843

**Comment by fabozzi** [comment]
please test workflow 136.840,136.843

**Comment by fabozzi** [comment]
(let's test with the relvals for which the input RAW seems to be available)

**Comment by fabozzi** [comment]
@jingyuluo  
Can you have a look at the skim output of relval 136.840 and 136.843 in this test?
Thank you!

**Comment by jingyuluo** [comment]
Dear @fabozzi ,

Sorry I missed the message... The event content of the skim output looks good for me!

Many thanks!
Jingyu

**Comment by kpedro88** [comment]
+1

**Comment by fabiocos** [comment]
+operations

**Comment by fabiocos** [comment]
+1

**Pull request merged**
