### PR TITLE
Remove use of legacy module classes from framework tests

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

- replaced use of legacy module types with thread friendly types
- any remaining ones were left intentionally until we remove those APIs

#### PR validation:

Built using `USER_CXXFLAGS='-DUSE_CMS_DEPRECATED' scram b -j ...`

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by makortel** [comment]
Given the errors (I didn't look), how about we go with the #35326 version of `TestParentage`?

**Comment by wddgit** [comment]
If you want me to look at this I will. I think I wrote the merge testing code years ago. The last failure is an assert. It might take a while to understand that one. The other two look like reference files that need updating, which is simple assuming the changes are expected.

**Comment by Dr15Jones** [comment]
please test

**Comment by makortel** [comment]
Following the merge of https://github.com/cms-sw/cmssw/pull/35326 there is now a conflict in `TestParentage.cc`.

**Comment by Dr15Jones** [comment]
please test

**Comment by makortel** [comment]
@cmsbuild, please test

For cleaner comparisons

**Comment by makortel** [comment]
@cmsbuild, please test

(for cleaner comparisons now that the new IB is actually there)

**Comment by makortel** [comment]
+1

**Pull request merged**
