### PR TITLE
Pixel Phase 1 Cosmic Quality Tests [91X]

### PR DESCRIPTION
**Pull request by lunik1**
This PR introduces a separate set of quality tests for the cosmic workflow for the Phase 1 Pixel. Currently these are a copy of the existing quality tests with mean_adc and mean_num_clusters excluded, but will diverge later.

### CODE REVIEW

**Comment by dmitrijus** [comment]
@fioriNTU Another developer? :)

**Comment by fioriNTU** [comment]
yes, actually he is working for some time on Summary plots, but never submitted a PR himself

**Comment by dmitrijus** [comment]
+1

**Comment by vanbesien** [comment]
So, @lunik1, can you set your name in Github? Or at least let us know who you are?

**Comment by davidlange6** [comment]
+1

**Pull request merged**
