### PR TITLE
Fix CachingAllocator debug for non-async operations [14.0.x]

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

@VinInn pointed out that filling memory asynchronously may be incorrect if the memory is later being set synchronously, without using a queue.
This is often the case with pinned host memory buffers, where the allocation and memset may be asynchronous, but the content is accessed directly using host-only operations.

This change makes the allocator wait for the memset to complete before returning the memory buffer to the user code.

It also adds a customisation function to activate memory filling, and uses it in the non-profling Alpaka workflows.

#### PR validation:

None, yet.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backported of #45368 to 14.0.x.

### CODE REVIEW

**Comment by fwyzard** [comment]
type bugfix

**Comment by fwyzard** [comment]
backport #45368

**Comment by fwyzard** [comment]
enable gpu

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
enable gpu

**Comment by fwyzard** [comment]
please abort

**Comment by fwyzard** [comment]
test parameters:
  - enable = gpu
  - workflows_gpu = 12634.402,12634.403,12634.404,12634.412,12661.402

**Comment by fwyzard** [comment]
+heterogeneous

Assuming the tests will pass.

**Comment by fwyzard** [comment]
+heterogeneous

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
+heterogeneous

**Comment by fwyzard** [comment]
please test

**Comment by srimanob** [comment]
+Upgrade

**Comment by AdrianoDee** [comment]
+pdmv

**Comment by rappoccio** [comment]
+1

**Pull request merged**
