### PR TITLE
[HGCAL trigger] Update ECON-T BestChoice NData

### PR DESCRIPTION
**Pull request by jbsauvan**
#### PR description:
- Update configuration of the number of trigger cells sent from the ECON-T with the BestChoice algorithm, as a function of the number of connected elinks
- Following [ECON-T specifications document](https://edms.cern.ch/file/2206779/1/ECON-T_specification_working_doc_v9_2mar2022.pdf)
- To be noted that the BestChoice algorithm is not used in default sequences; therefore no changes are expected.

Associated internal PRs and reviews:
- hgc-tpg#45

#### PR validation:
Tested D86, D92, D94 workflows
```
runTheMatrix.py -w upgrade -l 20034.0 --maxSteps=2 & # D86
runTheMatrix.py -w upgrade -l 22434.0 --maxSteps=2 & # D92
runTheMatrix.py -w upgrade -l 23234.0 --maxSteps=2 & # D94
```

### CODE REVIEW

**Comment by aloeliger** [comment]
please test

**Comment by jbsauvan** [comment]
The failures in the tests seem unrelated to this PR

**Comment by epalencia** [comment]
Please test

**Comment by aloeliger** [comment]
I'm not seeing any other PRs with this kind of error, I guess we'll see if it is temporary.

**Comment by aloeliger** [comment]
+l1

- Trivial changes, no visible results expected

**Comment by srimanob** [comment]
+Upgrade

**Comment by srimanob** [comment]
Note to @jbsauvan @aloeliger 

You may follow up to fix the warning later. Not relate to this PR.

```
/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_14_0_X_2023-11-30-2300/src/L1Trigger/L1THGCal/src/backend/HGCalClusteringImpl.cc:87:26: warning: Branch condition evaluates to a garbage value [core.uninitialized.Branch]
   87 |     if (targetClu < 0 && isSeed[itc])
      |                          ^~~~~~~~~~~
/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_14_0_X_2023-11-30-2300/src/L1Trigger/L1THGCal/src/backend/HGCalClusteringImpl.cc:301:9: warning: Branch condition evaluates to a garbage value [core.uninitialized.Branch]
  301 |     if (isSeed[itc])
      |         ^~~~~~~~~~~
2 warnings generated.
```

**Comment by jbsauvan** [comment]
> Note to @jbsauvan @aloeliger
> 
> You may follow up to fix the warning later. Not relate to this PR.
> 
> ```
> /data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_14_0_X_2023-11-30-2300/src/L1Trigger/L1THGCal/src/backend/HGCalClusteringImpl.cc:87:26: warning: Branch condition evaluates to a garbage value [core.uninitialized.Branch]
>    87 |     if (targetClu < 0 && isSeed[itc])
>       |                          ^~~~~~~~~~~
> /data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_14_0_X_2023-11-30-2300/src/L1Trigger/L1THGCal/src/backend/HGCalClusteringImpl.cc:301:9: warning: Branch condition evaluates to a garbage value [core.uninitialized.Branch]
>   301 |     if (isSeed[itc])
>       |         ^~~~~~~~~~~
> 2 warnings generated.
> ```

Hi @srimanob 
Thanks for the notice!
Indeed this is something I noted that should be fixed.

**Pull request merged**
