### PR TITLE
Lepton time-life info for NanoAOD and Nano branches from ValueMap of elaborated types (14_0_X)

### PR DESCRIPTION
**Pull request by mbluj**
#### PR description:

This PR adds a customization to add lepton time-life related information to NanoAOD. The information contains:
* (refitted) secondary vertex for 3-prong taus (with covariance matrix),
* impact parameter vector (with significance) of the electron, muon and tau tracks wrt PV fitted with beam-spot constraint,
* parameters of electron, muon and tau tracks (with covariance matrix),
* primary vertex with beam-spot constraint (position and covariance matrix).

All those variables are used in the measurement of CP structure of the Higgs-tau Yukawa coupling and related analyses, e.g. measurement of polarization of Z in decays to taus.

In addition, this PR introduces producer of NanoAOD branches from ValueMap of elaborated types in order to enable table extensions using elaborated types other than numeric types (int, float, ...). The new producer is used to store lepton time-life related information in NanoAOD.

This PR backports #43525 and #43916 to 14_0_X.

#### PR validation:

Validated in original PRs.
In addition customized NanoAOD workflow (with the following cmsDriver command) run successfully:
```
cmsDriver.py --python_filename NanoAOD_lifeTimeCustom_cfg.py --eventcontent NANOAODSIM --customise_commands="process.add_(cms.Service('InitRootHandlers',EnableIMT = cms.untracked.bool(False)));process.MessageLogger.cerr.FwkReport.reportEvery=1000" --datatier NANOAODSIM --fileout file:NanoAOD_lifeTimeCustom.root --conditions auto:phase1_2018_realistic --step NANO:@LepTimeLife,DQM:@nanoAODDQM--filein file:some_ttbar2018file.root --era Run2_2018,run2_nanoAOD_106Xv2 --no_exec --mc -n -1
```

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport of #43525 and #43916 to 14_0_X which is production release series for 2024.

### CODE REVIEW

**Comment by vlimant** [comment]
enable nano

**Comment by vlimant** [comment]
please test

**Comment by vlimant** [comment]
+1

**Comment by mandrenguyen** [comment]
backport of https://github.com/cms-sw/cmssw/pull/43525 and https://github.com/cms-sw/cmssw/pull/43916

**Comment by mandrenguyen** [comment]
+1

**Comment by rappoccio** [comment]
+1

**Pull request merged**
