### PR TITLE
Run4-hgx287Y Geometry definition for the mixed layers of HGCal V16

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Geometry definition for the mixed layers of HGCal V16

#### PR validation:

Use runTheMatrix test workflows and also tested for overlaps

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cvuosalo @srimanob Please approve this PR

**Comment by srimanob** [comment]
+Upgrade

**Comment by srimanob** [comment]
Please test

**Comment by srimanob** [comment]
> @cvuosalo @srimanob Please approve this PR

Seem test is pending somehow. I just trigger it, and will re-approve from my side.

**Comment by srimanob** [comment]
+Upgrade

**Comment by cvuosalo** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
