### PR TITLE
squashed #23799 (New pixel RecHit infrastructure for FastSim (for Phases 0, 1, 2, and beyond))) -- backport to 10_2_X

### PR DESCRIPTION
**Pull request by ssekmen**
New pixel RecHit infrastructure for FastSim (for Phases 0, 1, 2, and beyond) 
backport of squashed #23799 to 10_2_X.

### CODE REVIEW

**Comment by fabiocos** [comment]
@ssekmen it looks like a file is missing in the backport:

----- Begin Fatal Exception 21-Nov-2018 00:01:06 CET-----------------------
An exception of category 'FileInPathError' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing module: class=TrackingRecHitProducer label='fastTrackerRecHits'
Exception Message:
edm::FileInPath unable to find file FastSimulation/TrackingRecHitProducer/data/BarrelBig2017.root anywhere in the search path.

Could you please fix it?

**Comment by ssekmen** [comment]
@fabiocos , this should hopefully be fixed by
https://github.com/cms-sw/cmsdist/pull/4527

**Comment by fabiocos** [comment]
please test with cms-sw/cmsdist#4527

**Comment by ssekmen** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
