### PR TITLE
Run3-174D Backport the fix in #43418 on ZDC geometry to update the 2023 Run3 geometry to be used for te Heavy Ion MC

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Backport the fix in #43418 on ZDC geometry to update the 2023 Run3 geometry to be used for te Heavy Ion MC

#### PR validation:

Use the runTheMatrix test workflows

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Bakport the changes done in the master (14_0_X) in #43418

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@antoniovilela, @sextonkennedy, @rappoccio Please see the error message: unknown/release - please see what it should have for the tests

**Comment by bsunanda** [comment]
@malbouis Please resolve the issue of testing

**Comment by bsunanda** [comment]
+geometry

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
We cannot start testing for the special branch but this modifications are tested in #43479, which is identical, so this one may be merged without standard testing.

**Comment by srimanob** [comment]
+Upgrade

**Comment by antoniovilela** [comment]
please abort
   - need to wait a few hours

**Comment by antoniovilela** [comment]
please test
   - IB is now available.

**Comment by antoniovilela** [comment]
hold
   - While discussing which release will be used.

**Comment by rappoccio** [comment]
unhold

**Comment by perrotta** [comment]
@cms-sw/orp-l2 what's the status of the CMSSW_13_0_HeavyIon_X special release?
Can this be merged, so that @bsunanda can derive zdc geometry payloads out of the branch? Or is there anything else missing?

**Comment by antoniovilela** [comment]
> @cms-sw/orp-l2 what's the status of the CMSSW_13_0_HeavyIon_X special release? Can this be merged, so that @bsunanda can derive zdc geometry payloads out of the branch? Or is there anything else missing?

Yes, apologies for the delay.

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
