### PR TITLE
bsunanda:Run2-hcx125 Resolve depth assignment for Hcal backport PR 18194

### PR DESCRIPTION
**Pull request by bsunanda**
The results from this PR is validated by Salavat within CMSSW version 9_1_X.

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by ianna** [comment]
+1

**Comment by ianna** [comment]
Note: it is a back port of PR #18194

**Comment by civanch** [comment]
+1

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@ianna @civanch Added the changes suggested by David for PR 18194 - please approve this

**Comment by ianna** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
