### PR TITLE
interface compatible with evtgen 1.6

### PR DESCRIPTION
**Pull request by alberto-sanchez**
In evtgen 1.6 decay file, pythia codes are from pythia8, so we do not need to convert them anymore. Removing also few duplicates in the extra particles config.

### CODE REVIEW

**Comment by perrozzi** [comment]
+1

**Comment by davidlange6** [comment]
does this break evtgen 1.5 (currently in 81x)?
@alberto-sanchez

**Comment by alberto-sanchez** [comment]
No because, they should use DECAY_2010.DEC. The fix is for DECAY_2014.DEC, which is the default in evtgen 1.6

**Comment by perrozzi** [comment]
@alberto-sanchez this still needs to be incorporated, right?

**Comment by alberto-sanchez** [comment]
@perrozzi  yes

**Comment by mkirsano** [comment]
Pending from August.

**Comment by Dr15Jones** [comment]
@davidlange6 
This change appears to be causing Pythia to crash in the nightly IB for both 8_1 and 9_0. See 
https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc6_amd64_gcc530/CMSSW_8_1_X_2016-11-28-1100/pyRelValMatrixLogs/run/541.0_BuToKstarJPsiToMuMu_forSTEAM_13TeV_TuneCUETP8M1+BuToKstarJPsiToMuMu_forSTEAM_13TeV_TuneCUETP8M1+HARVESTGEN/step1_BuToKstarJPsiToMuMu_forSTEAM_13TeV_TuneCUETP8M1+BuToKstarJPsiToMuMu_forSTEAM_13TeV_TuneCUETP8M1+HARVESTGEN.log
As an example.

**Comment by alberto-sanchez** [comment]
The problem is with the configuration file, which is calling the old decay table from evtgen 1.3 instead the one from evtgen 1.6. My guess is that is not the only configuration which is calling that old decay file. Anyway reverting is the safest thing for now.

**Comment by davidlange6** [comment]
so basically my fear from August. It seems we are back to having things working, so just make a new pull request when you have things fixed up.

**Comment by dan131riley** [comment]
This is incidental to the actual bug, but it is weird enough that I spent a little time investigating, so might as well document.

An oddity about these crashes is that in many of them the thread catching the SIGSEGV is idle, for example

```
Thread 1 (Thread 0x7f530dddfbc0 (LWP 31581)):
#0  0x00000037736df283 in poll () from /lib64/libc.so.6
#1  0x00007f5309ffef24 in full_read.constprop () from /cvmfs/cms-ib.cern.ch/2016-49/slc6_amd64_gcc600/cms/cmssw/CMSSW_9_0_X_2016-11-29-1100/lib/slc6_amd64_gcc600/pluginFWCoreServicesPlugins.so
#2  0x00007f5309fff72a in edm::service::InitRootHandlers::stacktraceFromThread() () from /cvmfs/cms-ib.cern.ch/2016-49/slc6_amd64_gcc600/cms/cmssw/CMSSW_9_0_X_2016-11-29-1100/lib/slc6_amd64_gcc600/pluginFWCoreServicesPlugins.so
#3  0x00007f530a000d15 in sig_dostack_then_abort () from /cvmfs/cms-ib.cern.ch/2016-49/slc6_amd64_gcc600/cms/cmssw/CMSSW_9_0_X_2016-11-29-1100/lib/slc6_amd64_gcc600/pluginFWCoreServicesPlugins.so
#4  <signal handler called>
#5  0x00000037736cf437 in sched_yield () from /lib64/libc.so.6
#6  0x00007f530e82fa3f in tbb::internal::custom_scheduler<tbb::internal::IntelSchedulerTraits>::receive_or_steal_task (this=0x7f530d856400, completion_ref_count=@0x7f530d84b128: 2) at ../../src/tbb/custom_scheduler.h:299
#7  0x00007f530e831590 in tbb::internal::custom_scheduler<tbb::internal::IntelSchedulerTraits>::local_wait_for_all (this=0x7f530d856400, parent=..., child=<optimized out>) at ../../src/tbb/custom_scheduler.h:611
#8  0x00007f530faf9613 in edm::StreamSchedule::processOneEvent(edm::EventPrincipal&, edm::EventSetup const&, bool) () from /cvmfs/cms-ib.cern.ch/2016-49/slc6_amd64_gcc600/cms/cmssw/CMSSW_9_0_X_2016-11-29-1100/lib/slc6_amd64_gcc600/libFWCoreFramework.so
```

A test job I ran didn't fault at all, but also didn't complete even after 12 hours running on a fast system.

One consistent pattern is that it is always thread 1, the "main()" thread, that handles the signal, which is consistent with an externally delivered signal to the primary PID.  The simplest explanation would be some external agent sending a SIGSEGV to the PID, but there's no external agent that would do that.  A crazy theory is that the process is running out of time, gets some other signal to exit and seg faults while invoking the signal handler for that signal, but there's a bunch of problems with that explanation.  So I can't replicate the seg fault, I see what looks like an infinite loop instead (possibly corrupting memory), and I can't account for the seg fault always appearing on thread 1.

**Comment by Dr15Jones** [comment]
@dan131riley thanks for looking further into this one. Definitely seems weird.
@bbockelm this one might interest you since

**Comment by dan131riley** [comment]
There IS a simple explanation, in the 81x relvals the abort is external termination, meaning the timeout expired:

```
A fatal system signal has occurred: external termination request
The following is the call stack containing the origin of the signal.
```

The explanation is here:

https://github.com/cms-sw/cms-bot/blob/master/RelValArgs.py

There's a special case that uses '--signal SIGTERM 7200' ONLY for 8xx releases, so 9xx has reverted to the old behavior of '--signal SIGSEGV 7200'.

@smuzaffar the SIGTERM is definitely preferable, can RelValArgs.py get updated?

**Comment by dan131riley** [comment]
Seems likely the four other mysterious segfaults during exit in CMSSW_9_0_X_2016-11-29-1100 step3s were really timeouts too...

**Comment by smuzaffar** [comment]
thanks @dan131riley  , I will update it

**Pull request merged**
