### PR TITLE
move migration to HBHEPhase1Reconstructor to the common run2_HCAL_2017 era

### PR DESCRIPTION
**Pull request by fwyzard**
follow up to #17235

### CODE REVIEW

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
+1

**Comment by fwyzard** [comment]
@davidlange6 , can you merge this one as well, once the tests are successful ?

**Comment by davidlange6** [comment]
that is what usually happens, yes..

**Comment by davidlange6** [comment]
+1

**Comment by fwyzard** [comment]
> that is what usually happens, yes..
I meant "in time for pre3" :-)

Thanks,
.A

**Pull request merged**
