### PR TITLE
Run3-sim73 Add cfi's to help HB/HE calibration using MC

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Add cfi's to help HB/HE calibration using MC

#### PR validation:

Tried to generate samples using these snippets

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by agrohsje** [comment]
Hi @bsunanda . Can you further comment on the need for this PR? Is this only to produce specific MC samples? If so, I think it is better/sufficient to store the info with the request in  mccm.

**Comment by bsunanda** [comment]
@agrohsje you are right - we recently had 2 mc productions dumped because of wrong choice of fragments and specifications in McM. That inspired me to make these fragments. I can close this if you think that is better.

**Comment by agrohsje** [comment]
That's interesting feedback. Thanks so much! In which sense was it wrong? Something we could have spot when approving tickets? The problem I see is that wrong setup could still be used independent of your PR because MC contacts just add a fragment they find in mccm. 
Is there a safe way to avoid this? We can also extend our checking script.

**Comment by bsunanda** [comment]
@agrohsje I am closing this PR. We do not know where it went wrong - we wanted something as in the fragment SinglePiE50HBHE_pythia8_cfi.py - but we got dataset created using most likely flatptgun. There were 5 M dataset with and without PU. It was wastage of CPU power and time.

**Pull request closed without merging**
