### PR TITLE
[12_5_X] Add new HI Beamspot to the Run-3 HI MC and change vertex smearing to use the estimated HI version

### PR DESCRIPTION
**Pull request by tvami**
#### PR description:

Please see https://github.com/cms-sw/cmssw/pull/39758/

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

backport of https://github.com/cms-sw/cmssw/pull/39758/

### CODE REVIEW

**Comment by tvami** [comment]
backport of https://github.com/cms-sw/cmssw/pull/39758/

**Comment by tvami** [comment]
test parameters:
  - workflows = 159, 159.02, 159.03

**Comment by tvami** [comment]
Backport of https://github.com/cms-sw/cmssw/pull/39758/

**Comment by tvami** [comment]
> Backport of #39758

this doesnt seem to be registered as a label :/

**Comment by francescobrivio** [comment]
backport of #39758

**Comment by francescobrivio** [comment]
> > Backport of #39758
> 
> this doesnt seem to be registered as a label :/

it's the capital "B" the issue :D

**Comment by tvami** [comment]
Hmm but look at this try: https://github.com/cms-sw/cmssw/pull/39951#issuecomment-1298818320

**Comment by francescobrivio** [comment]
+alca

 - difference expected in the HI workflows
 - DQM bin-by-bin comparison (https://tinyurl.com/27tznfkm) similar to master PR

**Comment by srimanob** [comment]
+Upgrade

**Comment by bbilin** [comment]
+pdmv

**Pull request merged**
