### PR TITLE
Provide forward compatibility to HepMC::GenEvent reading

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

Provide a iorule to allow reading data stored in CMSSW_10_6.

#### PR validation:

Tested with job that read a CMSSW_10_6 GENSIM+RAW data file.

### CODE REVIEW

**Comment by fabiocos** [comment]
backport #26210

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
@smuzaffar @mrodozov CMSSW_9_4_MAOD_X_2019-03-24-0000 exists, but apparently the bot does not recognizes it as a valid reference...

**Comment by smuzaffar** [comment]
please test
should be fix now

**Comment by fabiocos** [comment]
@alberto-sanchez @efeyazgan @qliphy this backport is needed to fix the issue observed in the UL processing chain

**Comment by alberto-sanchez** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
