### PR TITLE
DD4hep: SimTracker/TrackerMaterialAnalysis tests

### PR DESCRIPTION
**Pull request by vargasa**
#### PR description:
 
Unify tests in single script, cleanup

#### PR validation:

```
cd SimTracker/TrackerMaterialAnalysis/test
$cmsRun MaterialProducer10GeVNeutrino.py
$cmsRun TrackingMaterialAnalyser_dd4hep.py PhaseI
$cmsRun TrackingMaterialAnalyser_dd4hep.py PhaseII
```
(edit) Migration script has been renamed in order to avoid any confusion with legacy scripts

### CODE REVIEW

**Comment by mtosi** [comment]
thanks for this update
did you update the relevant twiki ?
how could we manage the group list ?

**Comment by vargasa** [comment]
@mtosi No, I guess that won't be done until the migration is completed and old scripts removed working with `DDCMS/Core`. But it would be helpful if you point me to the relevant twiki

**Comment by mtosi** [comment]
https://twiki.cern.ch/twiki/bin/viewauth/CMS/TrackingPOGRecoMaterialFromGeometry
thanks

**Comment by mtosi** [comment]
https://twiki.cern.ch/twiki/bin/viewauth/CMS/TrackingPOGRecoMaterialFromGeometry
thanks

the point is that this package is currently used, in particular, one of the file you are updating
https://github.com/cms-sw/cmssw/blob/a78b4c2407b9c71a19bfcb4cb2d7833a9ae889de/SimTracker/TrackerMaterialAnalysis/test/TrackingMaterialAnalyser.py
therefore, please, provide the relevant information in the twiki

in addition, how could we make the list
https://github.com/cms-sw/cmssw/blob/a78b4c2407b9c71a19bfcb4cb2d7833a9ae889de/SimTracker/TrackerMaterialAnalysis/test/TrackingMaterialAnalyser.py#L85 
?
if I would need to adjust the parametrization, is there a way to automatically group material volumes in slightly a different way ?

thanks !

**Comment by vargasa** [comment]
> the point is that this package is currently used

Please double check, the file you're mentioning `TrackingMaterialAnalyser.py` was introduced as part of the migration, please reefer to https://github.com/cms-sw/cmssw/pull/30125. You probably are referring to the lowercase filename which is a different file that's not being modified by this or previous migration PRs. 

>  how could we make the list

The list shown is filtered from the xml, please see: https://cmssdt.cern.ch/lxr/source/SimTracker/TrackerMaterialAnalysis/python/trackingMaterialAnalyser_ForPhaseII_cfi.py#0015 

```
cat ../data/dd4hep_trackingMaterialGroups_ForPhaseII.xml | grep TrackingMaterialGroup | sed -e 's/\s*//' | cut -d ' ' -f 3 | tr '=' ' ' | cut -d ' ' -f 2 | tr -d '"' | sed -e 's/\(.*\)/"\1",/'
```
> if I would need to adjust the parametrization, is there a way to automatically group material volumes in slightly a different way?

You probably need to edit the xml files located in `SimTracker/TrackerMaterialAnalysis/data/` or use the `dumpFullXML*.py` scripts

**Comment by mtosi** [comment]
> Please double check, the file you're mentioning `TrackingMaterialAnalyser.py` was introduced as part of the migration, please reefer to #30125. You probably are referring to the lowercase filename which is a different file that's not being modified by this or previous migration PRs.

opsi, thanks !

**Comment by silviodonato** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
