### PR TITLE
Revive beam information, physics declared bit, and HLT event selection for online DQM

### PR DESCRIPTION
**Pull request by dmitrijus**
This has been open for over a year, DQM needs this and we have been running it forever.
It should go to the release.

The PR allows the DQM module DQMProvInfo (run by central online DQM) to retrieve the beam information from TCDS FED raw data, by reading the corresponding address for the Beam Synchronous Timing (BST) record. This is currently done using an utility in EventFilter/Utilities, which has been enhanced for this scope.
From this information, the Physics Declared bit is computed, and added into the report summary profile.
NOTA BENE: this is a temporary solution, until a well implemented unpacker for TCDS is made available in CMSSW.

The PR also resurrects a MonitorElement in DQMEventInfo showing the HLT path selection in the DQM input source DQMStreamerReader.

### CODE REVIEW

**Comment by dmitrijus** [comment]
+1

**Comment by dmitrijus** [comment]
+1

**Comment by vanbesien** [comment]
Let me clarify the importance:
This PR is very relevant since it tries to fix the fact that since 2015 the injection of the beam information in the events is broken.
As a result in the DQM all the plots that show the beam status are broken.
To give an example: the main HV plot on the summary page that shows from which LS the stable beams were declared shows a big red line stating that there are no stable beams ever. We've been running this PR manually on top of DQM to fix at least that.
We (DQM) really want this, but we also need a daq signature.

**Comment by davidlange6** [comment]
hi guys

until the event unpacking moves into the tcds unpacker, this won't go in. Its pretty much a trivial request that you've lost a year on:(

**Comment by diguida** [comment]
@davidlange6 the request was not lost, there was a disagreement between your proposal and how DAQ handles raw data coming from FED 1024, and we were stuck.
I proposed a possible solution in the original PR in 80X, but no feedback...

**Comment by dmitrijus** [comment]
Discussion link: https://github.com/cms-sw/cmssw/pull/14763#issuecomment-226155091
Let's continue here.

**Comment by davidlange6** [comment]
having reread that (I think its 81x you mean), its 20 lines of stuff that has nothing to do with the request that I understand

just put 

https://github.com/dmitrijus/cmssw/blob/d60b244f9f2b9546b7c0c92aea5c523e0f61b9cf/DQMServices/Components/src/DQMProvInfo.cc#L259

into a struct made by

https://github.com/cms-sw/cmssw/blob/master/EventFilter/Utilities/plugins/TcdsRawToDigi.cc

**Comment by diguida** [comment]
@davidlange6 concerning https://github.com/cms-sw/cmssw/pull/18045#issuecomment-288693586
As I wrote in the previous PR (see https://github.com/cms-sw/cmssw/pull/17737#issuecomment-283653429), I had a prototype doing exactly what you are describing. There were few things still messed up, but I could start from there. I will coordinate with @dmitrijus

**Comment by diguida** [comment]
@davidlange6 @dmitrijus @vanbesien have a look at #18108

**Comment by slava77** [comment]
either this PR or #18108 will have to be closed

**Comment by diguida** [comment]
@slava77 this is superseded: #18108 contains all commits here (but the merge one) and the new on for the data format.

**Comment by slava77** [comment]
-1

superseded by #18108

**Pull request closed without merging**
