### PR TITLE
[101X][change Metadata] Adding PCC + TrackAlign PCL not consumed by Prompt

### PR DESCRIPTION
**Pull request by lpernie**
This PR has no effect on any workflow.
This PR keeps track on the script that produce the latest IOV of the metadata TAG:
https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/tags/DropBoxMetadata_v5.1_express
(not yet appened to the offical tag)
The test single IOV is in:
https://cms-conddb.cern.ch/cmsDbBrowser/list/Prep/tags/DropBoxMetadata_PCC_TrackAlnoPCC_v1

### CODE REVIEW

**Comment by lpernie** [comment]
backport of #22918

**Comment by lpernie** [comment]
please test

**Comment by lpernie** [comment]
+1

**Comment by fabiocos** [comment]
@ggovi could you please comment in case or sign? It would be useful to have it in 10_1_2.

**Comment by ggovi** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
