### PR TITLE
[12_4_X] Add DQM module using HeavyFlavorAnalysis for BPH common decays 

### PR DESCRIPTION
**Pull request by elusian**
#### PR description:

This PR adds a DQM module based on the HeavyFlavorAnalysis package to create plots for several decays relevant for BPH.
The new plots are available under Physics/HeavyFlavor in the DQM
A more detailed explanation of what plots are available can be found at https://indico.cern.ch/event/1119491/#1-tracking-monitor-in-bph-fina
This PR depends on PR #38535

#### PR validation:

The tests with runTheMatrix return ok, privately tested on a few relvals.
Added processing time is 0.11 s/ev, added size to a DQM file is 0.15%, increase in peak memory consumption is ~10MB

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport of #38540

### CODE REVIEW

**Comment by perrotta** [comment]
test parameters:
- pull_request = #38535

**Comment by perrotta** [comment]
backport of https://github.com/cms-sw/cmssw/pull/38540

**Comment by kskovpen** [comment]
please test

**Comment by mmusich** [comment]
test parameters:
   * pull_request = https://github.com/cms-sw/cmssw/pull/38535
   * workflows = 1347, 1349, 1350, 1364, 1365, 1366, 136.884, 136.896, 136.860, 136.898
   * relvals_opt= -w standard,highstats,pileup,generator,extendedgen,production,cleanedupgrade,ged

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by kskovpen** [comment]
+pdmv

**Comment by emanueleusai** [comment]
+1

**Comment by qliphy** [comment]
please test
to refresh results.  Moreover,  @cms-sw/upgrade-l2  do you have any comment?

**Comment by AdrianoDee** [comment]
+upgrade
From upgrade side, wf updates are fine.

**Comment by mmusich** [comment]
urgent
   * please merge this in 12_4_ 3

**Pull request merged**
