### PR TITLE
Dire integration (for internal partons)

### PR DESCRIPTION
**Pull request by mseidel42**
Needs https://github.com/cms-sw/cmsdist/pull/3711

### CODE REVIEW

**Comment by perrozzi** [comment]
please test

**Comment by perrozzi** [comment]
please test with cms-sw/cmsdist#3711

**Comment by perrozzi** [comment]
@intrepid42 can you crosscheck?

**Comment by intrepid42** [comment]
I forgot to put dire in the cmssw-tool-conf.spec, fixed now!

**Comment by perrozzi** [comment]
please test with cms-sw/cmsdist#3711

**Comment by perrozzi** [comment]
+1

**Comment by fabiocos** [comment]
@perrozzi do you have some validation material? Is Dire supposed to be part of a pythia8 standard workflow?

**Comment by perrozzi** [comment]
@intrepid42 should comment

**Comment by intrepid42** [comment]
I verified that the Dire shower runs and test events (e+e-) are produced, including shower weights

--> I have a small output file with validation events but no high-stats comparison against other generators.

**Comment by fabiocos** [comment]
@intrepid42 sorry, is the example in this PR, where I see that Dire is used, running and producing events for processing correctly out of the box? I mean a technical test, physics checks will come later...

**Comment by intrepid42** [comment]
Yes, I added the test config file `GeneratorInterface/Pythia8Interface/test/pythia8ex14_cfg.py`

**Comment by intrepid42** [comment]
Hi, I hope somebody can help with this: I want to generate pp>ttbar events but the code hangs in pythia::next().

* It works when I turn off initial-state shower
* It works when I set '-s 4000000' and turn off additional analysis modules that I would like to run
* It works without problems and 10x faster with a standalone Pythia+Dire installation on my desktop PC

I am not an expert on shared libraries and thread safety etc... 
Do you have any idea on that?

**Pull request merged**
