### PR TITLE
Initialize variable in ComparatorCodeLUT

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

This was reported by valgrind.

#### PR validation:

Code compiles. I have not yet rerun valgrind with this change.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
The valgrind report is
```
==3764354== Conditional jump or move depends on uninitialised value(s)
==3764354==    at 0x8E190360: ComparatorCodeLUT::run(CSCCLCTDigi&, unsigned int, CSCL1TPLookupTableCCLUT const*) const (in /cvmfs/cms.cern.ch/el8_amd64_gcc12/cms/cmssw/CMSSW_14_1_0_pre5/lib/el8_amd64_gcc12/libL1TriggerCSCTriggerPrimitives.so)
==3764354==    by 0x8E1797C8: CSCCathodeLCTProcessor::constructCLCT(int, unsigned int, std::vector<std::vector<unsigned short, std::allocator<unsigned short> >, std::allocator<std::vector<unsigned short, std::allocator<unsigned short> > > > const&, CSCL1TPLookupTableCCLUT const*) (in /cvmfs/cms.cern.ch/el8_amd64_gcc12/cms/cmssw/CMSSW_14_1_0_pre5/lib/el8_amd64_gcc12/libL1TriggerCSCTriggerPrimitives.so)
==3764354==    by 0x8E190D9D: CSCUpgradeCathodeLCTProcessor::findLCTs(std::vector<int, std::allocator<int> > const (*) [225], CSCL1TPLookupTableCCLUT const*) (in /cvmfs/cms.cern.ch/el8_amd64_gcc12/cms/cmssw/CMSSW_14_1_0_pre5/lib/el8_amd64_gcc12/libL1TriggerCSCTriggerPrimitives.so)
==3764354==    by 0x8E1735BF: CSCCathodeLCTProcessor::run(std::vector<int, std::allocator<int> > const (*) [225], CSCL1TPLookupTableCCLUT const*) (in /cvmfs/cms.cern.ch/el8_amd64_gcc12/cms/cmssw/CMSSW_14_1_0_pre5/lib/el8_amd64_gcc12/libL1TriggerCSCTriggerPrimitives.so)
==3764354==    by 0x8E173D08: CSCCathodeLCTProcessor::run(MuonDigiCollection<CSCDetId, CSCComparatorDigi> const*, CSCChamber const*, CSCL1TPLookupTableCCLUT const*) (in /cvmfs/cms.cern.ch/el8_amd64_gcc12/cms/cmssw/CMSSW_14_1_0_pre5/lib/el8_amd64_gcc12/libL1TriggerCSCTriggerPrimitives.so)
==3764354==    by 0x8E18896F: CSCMotherboard::runCommon(MuonDigiCollection<CSCDetId, CSCWireDigi> const*, MuonDigiCollection<CSCDetId, CSCComparatorDigi> const*, CSCMotherboard::RunContext const&) (in /cvmfs/cms.cern.ch/el8_amd64_gcc12/cms/cmssw/CMSSW_14_1_0_pre5/lib/el8_amd64_gcc12/libL1TriggerCSCTriggerPrimitives.so)
==3764354==    by 0x8E1804B0: CSCGEMMotherboard::run(MuonDigiCollection<CSCDetId, CSCWireDigi> const*, MuonDigiCollection<CSCDetId, CSCComparatorDigi> const*, MuonDigiCollection<GEMDetId, GEMPadDigiCluster> const*, CSCGEMMotherboard::RunContext const&) (in /cvmfs/cms.cern.ch/el8_amd64_gcc12/cms/cmssw/CMSSW_14_1_0_pre5/lib/el8_amd64_gcc12/libL1TriggerCSCTriggerPrimitives.so)
==3764354==    by 0x8E192D3D: CSCTriggerPrimitivesBuilder::build(CSCBadChambers const*, MuonDigiCollection<CSCDetId, CSCWireDigi> const*, MuonDigiCollection<CSCDetId, CSCComparatorDigi> const*, MuonDigiCollection<GEMDetId, GEMPadDigiCluster> const*, CSCTriggerPrimitivesBuilder::BuildContext const&, MuonDigiCollection<CSCDetId, CSCALCTDigi>&, MuonDigiCollection<CSCDetId, CSCCLCTDigi>&, MuonDigiCollection<CSCDetId, CSCALCTPreTriggerDigi>&, MuonDigiCollection<CSCDetId, CSCCLCTPreTriggerDigi>&, MuonDigiCollection<CSCDetId, int>&, MuonDigiCollection<CSCDetId, CSCCorrelatedLCTDigi>&, MuonDigiCollection<CSCDetId, CSCCorrelatedLCTDigi>&, MuonDigiCollection<CSCDetId, CSCShowerDigi>&, MuonDigiCollection<CSCDetId, CSCShowerDigi>&, MuonDigiCollection<CSCDetId, CSCShowerDigi>&, MuonDigiCollection<GEMDetId, GEMCoPadDigi>&) (in /cvmfs/cms.cern.ch/el8_amd64_gcc12/cms/cmssw/CMSSW_14_1_0_pre5/lib/el8_amd64_gcc12/libL1TriggerCSCTriggerPrimitives.so)
==3764354==    by 0xC5A4BC86: CSCTriggerPrimitivesProducer::produce(edm::Event&, edm::EventSetup const&) (in /cvmfs/cms.cern.ch/el8_amd64_gcc12/cms/cmssw/CMSSW_14_1_0_pre5/lib/el8_amd64_gcc12/pluginCSCTriggerPrimitivesPlugins.so)

==3764354==  Uninitialised value was created by a heap allocation
==3764354==    at 0x403BEE1: operator new(unsigned long) (in /cvmfs/cms.cern.ch/el8_amd64_gcc12/external/valgrind/3.23.0-143b83b3001a13f5bb2e0a4b5445fed5/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==3764354==    by 0x8E1732FC: CSCCathodeLCTProcessor::CSCCathodeLCTProcessor(unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, CSCBaseboard::Parameters&) (in /cvmfs/cms.cern.ch/el8_amd64_gcc12/cms/cmssw/CMSSW_14_1_0_pre5/lib/el8_amd64_gcc12/libL1TriggerCSCTriggerPrimitives.so)
==3764354==    by 0x8E190055: CSCUpgradeCathodeLCTProcessor::CSCUpgradeCathodeLCTProcessor(unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, CSCBaseboard::Parameters&) (in /cvmfs/cms.cern.ch/el8_amd64_gcc12/cms/cmssw/CMSSW_14_1_0_pre5/lib/el8_amd64_gcc12/libL1TriggerCSCTriggerPrimitives.so)
==3764354==    by 0x8E1887F1: CSCMotherboard::CSCMotherboard(unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, CSCBaseboard::Parameters&) (in /cvmfs/cms.cern.ch/el8_amd64_gcc12/cms/cmssw/CMSSW_14_1_0_pre5/lib/el8_amd64_gcc12/libL1TriggerCSCTriggerPrimitives.so)
==3764354==    by 0x8E17E2A3: CSCGEMMotherboard::CSCGEMMotherboard(unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, CSCBaseboard::Parameters&) (in /cvmfs/cms.cern.ch/el8_amd64_gcc12/cms/cmssw/CMSSW_14_1_0_pre5/lib/el8_amd64_gcc12/libL1TriggerCSCTriggerPrimitives.so)
==3764354==    by 0x8E18A538: CSCTriggerPrimitivesBuilder::CSCTriggerPrimitivesBuilder(edm::ParameterSet const&) (in /cvmfs/cms.cern.ch/el8_amd64_gcc12/cms/cmssw/CMSSW_14_1_0_pre5/lib/el8_amd64_gcc12/libL1TriggerCSCTriggerPrimitives.so)
==3764354==    by 0xC5A476D1: CSCTriggerPrimitivesProducer::CSCTriggerPrimitivesProducer(edm::ParameterSet const&) (in /cvmfs/cms.cern.ch/el8_amd64_gcc12/cms/cmssw/CMSSW_14_1_0_pre5/lib/el8_amd64_gcc12/pluginCSCTriggerPrimitivesPlugins.so)
```

**Comment by Dr15Jones** [comment]
With this change in, valgrind no longer reports the issue.

**Comment by aloeliger** [comment]
+l1
- technical PR

**Comment by rappoccio** [comment]
+1

**Pull request merged**
