### PR TITLE
Further modification to new Scouting path in HLT (11_2_X)

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
#### PR description:

Further modification to new Scouting path in HLT (11_2_X)
Based on CMSSW_11_2_1_patch2

#### PR validation:

TSG tests

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Backport of #32870 

Fix needed for Scouting MC production using 11_2.

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
type bug-fix

**Comment by Martin-Grunewald** [comment]
backport of #32870

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
