### PR TITLE
Phase2-hgx341F Update the scripts in Geometry/HGCalCommonData/test/python to investigate the discrepancey between DDD and DD4hep descriptions

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Update the scripts in Geometry/HGCalCommonData/test/python to investigate the discrepancies between DDD and DD4hep descriptions

#### PR validation:

Use the modified scripts to investigate the differences

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
+geometry

**Comment by srimanob** [comment]
+Upgrade 

Adding tests for DDD - DD4hep comparisons. No change is expected from this PR.

**Comment by rappoccio** [comment]
+1

**Pull request merged**
