### PR TITLE
Displaced SUSY Trigger Offline Monitoring for 2017

### PR DESCRIPTION
**Pull request by lantone**
This PR updates the path names in the offline exotica validation for the displaced lepton triggers, to be included in the 2017 pp collision menu.

TSG approval slides: https://indico.cern.ch/event/646747/contributions/2626978/attachments/1476569/2287752/bfrancis_OSU_TSG.pdf

### CODE REVIEW

**Comment by mtosi** [comment]
please, rebase
then from what i saw, i think you are updating the config for the validation step (used only in mc relval production)

**Comment by mtosi** [comment]
@cmsbuild, please test

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
