### PR TITLE
Run3-gex22 Update the 2 Reco configuration files for dd4hep

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Update the 2 Reco configuration files for dd4hep run3 scenarios

#### PR validation:

Tried with dd4hep workflows

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cvuosalo Here is the modified cff files

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by ianna** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade

**Comment by silviodonato** [comment]
+1

**Pull request merged**
