### PR TITLE
SiPixel Payload Inspector: introduce utility to display probability-weighted `SiPixelFEDChannelContainer` contents

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

The main goal of this PR is to add the class `SiPixelFEDChannelContainerMapWeigthed` to `SiPixelFEDChannelContainer` Payload Inspector plugin (this is done in commit  b03913c32ada263af5d113c8d2dd7c4babb2b6b1).
This class displays an aggregate map of the masked components for all scenarios included in the examined payload, weighted on the probability per PU unit from a `SiPixelQualityProbabilities` payload (assuming a flat PU profile in the range encoded in  `SiPixelQualityProbabilities`).
The `SiPixelQualityProbabilities` tag comes from user input and is retrieved via a local `cond::persistency::Session` opened in the production database.
This is useful, because without combining the information from both `SiPixelStatusScenariosRcd` and `SiPixelStatusScenarioProbabilityRcd` it is not possible *a priori* to determine the fraction of events in which a given ROC will be masked when the [bad FED channel simulation](https://indico.cern.ch/event/823473/contributions/3444523/attachments/1851561/3039790/trackerDPG_27052019.pdf) is used (as it will be in the 2022 and 2023 physics MC).
Additionally I add a standalone testing script (in commit db7d86ed502b1a2189ee66819b3381eabd646944) and add this class to the pre-existing unit test script of this package (in commit f06968ca5a81f4f6c43075a8fc0e17a3dd1751a9).
A possible extension to supply provision for a user-input list of PU weights (to make it even more adherent to actual full simulation process) is envisaged, but let for a follow-up PR.

#### PR validation:

This PR passes unit tests of the involved package: `scram b runtests`
Additionally I tested the code with this command:

```bash
getPayloadData.py \
    --plugin pluginSiPixelFEDChannelContainer_PayloadInspector \
    --plot plot_SiPixelBPixFEDChannelContainerWeightedMap \
    --tag SiPixelStatusScenarios_StuckTBMandOther_2023_v2_mc \
    --input_params '{"SiPixelQualityProbabilitiesTag": "SiPixelQualityProbabilities_2023_v2_mc"}' \
    --time_type Run \
    --iovs '{"start_iov": "1", "end_iov": "1"}' \
    --db Prod \
    --test ;
```

and obtained the following plot:

image

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

N/A

Cc: @tsusa

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by perrotta** [comment]
In the [log output](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-8bc635/35193/unitTests/src/CondCore/SiPixelPlugins/test/testPixelPayloadInspector/testing.log) of the newly inserted test "testPixelPayloadInspector" there are quite several LogError messages as this:
```
%MSG-e PixelRegionContainers: 
303042564 :=> 1000 is not a recongnized PixelId enumerator! 
PixelBarrel Layer 0 Ladder 1 Module for phase0 1 Module for phase2 1 module (303042564)
%MSG
```

They come from PixelRegionContainers. Do yo have any hint about them?

**Comment by mmusich** [comment]
> They come from PixelRegionContainers. Do yo have any hint about them?

Not from this PR

**Comment by mmusich** [comment]
Ping?

**Comment by perrotta** [comment]
> > They come from PixelRegionContainers. Do yo have any hint about them?
> 
> Not from this PR

I understand that this quite likely does not affect the relevant functionalities introduced by tis PR. However, it is a matter of fact that the new unit test gives some weird output, and layer 0 of the barrel pixel is searched for. Is it a problem of the input data used? Are there used some wrong conditions?
I think that, if possible, it should be fixed. If, on the contrary, you think that we should not care about it because the purposes of the unit test are fulfilled nonetheless, please add a line in the PR description about it, so that if anyone will wonder in the future why those errors are there, a reference can still be found about it.
Thank you!

**Comment by mmusich** [comment]
> I understand that this quite likely does not affect the relevant functionalities introduced by tis PR. However, it is a matter of fact that the new unit test gives some weird output, and layer 0 of the barrel pixel is searched for. Is it a problem of the input data used? Are there used some wrong conditions?
I think that, if possible, it should be fixed. If, on the contrary, you think that we should not care about it because the purposes of the unit test are fulfilled nonetheless, please add a line in the PR description about it, so that if anyone will wonder in the future why those errors are there, a reference can still be found about it.
Thank you!

this is completely irrelevant for this PR. If that bothers you open an issue.

**Comment by mmusich** [comment]
> However, it is a matter of fact that the new unit test gives some weird output, 

This is not even wrong, see [current IB logs](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc11/CMSSW_13_3_X_2023-10-17-1100/unitTestLogs/CondCore/SiPixelPlugins#/14). 
   * the test is not new;
   * the "weird" output is already present in IBs

**Comment by perrotta** [comment]
+1
- Being the error message from the PixelRegionContainers in the unit tests irrelevant for this PR, no reason to not to sign it; Tracker TPG will possibly take care of it, if they consider it of any relevance to debug that code

**Comment by mmusich** [comment]
> Tracker TPG will possibly take care of it, if they consider it of any relevance to debug that code

for the record the tests that triggers the verbose log is this:

https://github.com/cms-sw/cmssw/blob/eb6caadb0fadad053b08cd563264cd7e2370f177/CondCore/SiPixelPlugins/test/testSiPixelPayloadInspector.cpp#L65

I would guess that somehow here 

https://github.com/cms-sw/cmssw/blob/eb6caadb0fadad053b08cd563264cd7e2370f177/CondCore/SiPixelPlugins/plugins/SiPixelLorentzAngle_PayloadInspector.cc#L290-L291

the phase-1 topology is loaded as opposed to the phase-2. Not clear why this happens at this point, but I won't be able to debug further with limited connection I have at the moment.

**Comment by antoniovilela** [comment]
+1
   - Error messages not related to this PR, to be followed up.

**Comment by mmusich** [comment]
>  Error messages not related to this PR, to be followed up.

so... it took me a while to understand what's going, but the issue lies in this commit:

https://github.com/cms-sw/cmssw/commit/5af9d665f48ccbfff7c49a4b6243c9124b37a189#diff-ce714e8f8d1e17f5c572dea87e1c0370ce098a7cad82c4326d4611db2d805b90L8

this screwed the meaning of the bit masks in `StandaloneTrackerTopology`.
Will fix and also create unit tests, such that when the `TrackerTopology` from DB is changed we don't miss to update the class constructed from XML.

**Comment by mmusich** [comment]
>  Will fix and also create unit tests, such that when the TrackerTopology from DB is changed we don't miss to update the class constructed from XML.

done at https://github.com/cms-sw/cmssw/pull/43059

**Pull request merged**
