### PR TITLE
ECal Geometry: Version XML Files According to CMS Convention

### PR DESCRIPTION
**Pull request by ianna**
#### PR description:

* Move the files without internal modification
* Remove legacy files
* Update configurations accordingly

#### PR validation:

usual RelVal

#### if this PR is a backport please specify the original PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by kpedro88** [comment]
@ianna after updating dict2023Geometry.py, you need to rerun generate2023Geometry.py for all affected scenarios to ensure consistency in the xml files.

**Comment by ianna** [comment]
@kpedro88 - where does this come from?
```
$ python Configuration/Geometry/scripts/generate2023Geometry.py -D 17
The Era for this detector should contain:
run2_common, run3_common, phase2_common, phase2_tracker, trackingPhase2PU140, run2_HE_2017, run2_HF_2017, run2_HCAL_2017, run3_HB, phase2_hcal, phase2_hgcal, hcalHardcodeConditions, hcalSkipPacker, phase2_muon, run3_GEM
```

**Comment by kpedro88** [comment]
@ianna the Eras are already set up correctly, so you don't have to change those.
(The script prints this info because I haven't set it up to generate Era files automatically.)

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade

**Comment by ianna** [comment]
@fabiocos - please review

**Comment by fabiocos** [comment]
@ianna I browsed all the modified configurations, they seem visually of, comparing some files whose name was renamed. Where in some way the new definitions of the geometry compared with the previous ones?

**Comment by ianna** [comment]
@fabiocos - github gives this information, if you look at the file list:
```
0 Geometry/EcalCommonData/data/PhaseII/v2/ectkcable.xml → Geometry/EcalCommonData/data/ectkcable/2023/v1/ectkcable.xml
File renamed without changes.
0 Geometry/EcalCommonData/data/PhaseII/v2/ectkcablemat.xml → Geometry/EcalCommonData/data/ectkcablemat/2023/v1/ectkcablemat.xml
File renamed without changes.
0 Geometry/EcalCommonData/data/Run2/eregalgo.xml → Geometry/EcalCommonData/data/eregalgo/2017/v1/eregalgo.xml
File renamed without changes.
0 Geometry/EcalCommonData/data/PhaseII/eregalgo.xml → Geometry/EcalCommonData/data/eregalgo/2023/v1/eregalgo.xml
File renamed without changes.
0 Geometry/EcalCommonData/data/PhaseII/v2/eregalgo.xml → Geometry/EcalCommonData/data/eregalgo/2023/v2/eregalgo.xml
File renamed without changes.
0 Geometry/EcalCommonData/data/PhaseII/esalgo.xml → Geometry/EcalCommonData/data/esalgo/2023/v1/esalgo.xml
File renamed without changes.
0 Geometry/EcalCommonData/data/PhaseII/escon.xml → Geometry/EcalCommonData/data/escon/2023/v1/escon.xml
File renamed without changes.
```

**Comment by fabiocos** [comment]
@ianna yes, I was looking at the update of the global configurations. Was this done manually? It looks ok to me, just to understand

**Comment by fabiocos** [comment]
+1

**Pull request merged**
