### PR TITLE
Implementation of new HF Fine Grain bit definition

### PR DESCRIPTION
**Pull request by mnorthup6690**
This is the same PR as #12130 and #12129.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please rebase this pull request to get rid of all the unnecessary merges

**Comment by Dr15Jones** [comment]
Also, please change the title of the pull request to describe the change. These titles are used when we make release notes so need to be meaningful to our collaborators.

**Comment by mnorthup6690** [comment]
Ok. Can you remind me how to rebase a PR? Thanks a lot.

**Comment by mulhearn** [comment]
I'll do it, but I'll have to make a new PR.

**Comment by mnorthup6690** [comment]
Ok. Thanks a lot Mike.

**Comment by mulhearn** [comment]
I rebased this at #12287 @mnorthup6690, you can close this now.

**Pull request closed without merging**
