### PR TITLE
Add GenPlusSimParticles_cfi.py.

### PR DESCRIPTION
**Pull request by wulsin**
Add customize configuration file to produce/keep a collection of particles simulated by GEANT combined with generated particles.

### CODE REVIEW

**Comment by wulsin** [comment]
The motivation for this pull request is to be able to produce signal MC samples with central production, for the Run 2 Exotica search for disappearing tracks.  Please let me know if I should additionally make a pull request to 7_6_X.  I did the PR for 7_1_X because that is the release used for the Run II Winter 15 GEN-SIM campaign.  Thanks!

**Comment by civanch** [comment]
@wulsin , please, clone this PR to 7_6_X

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by wulsin** [comment]
The motivation for using the GenPlusSimParticleProducer module for the simulation of exotic long-lived particles has been described in two presentations to the Simulation group:  
4 Apr 2014:  https://indico.cern.ch/event/310815/session/1/contribution/12/attachments/594838/818730/20140404_SimulationMtg.pdf
6 Mar 2015:  https://indico.cern.ch/event/377207/session/0/contribution/6/attachments/752124/1031818/20150306_SIMExotica.pdf

**Comment by wulsin** [comment]
Vladimir suggested that I specify the type of the collection produced by GenPlusSimParticleProducer, which is vector<reco::GenParticle>.  

Also, the same PR for 7.6.X:  https://github.com/cms-sw/cmssw/pull/11083 has been merged.  

Please let me know if any more information is needed.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
