### PR TITLE
Add ESInputTag to VPSet default added to cfi file [14_0]

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR validation:

Code compiles. 

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport of #44344 and #44362

### CODE REVIEW

**Comment by Dr15Jones** [comment]
Please test

**Comment by makortel** [comment]
test parameters:
  - full_cmssw = true

**Comment by makortel** [comment]
@cmsbuild, please test

Just to double check...

**Comment by Dr15Jones** [comment]
The unit test failure is not caused by this PR. The problem is a `curl` request of a .py file failed and then resultant file contains an html error message (not python code).

**Comment by makortel** [comment]
@cmsbuild, ignore tests rejected with external-failure

**Comment by makortel** [comment]
bacport of #44344 and #44362

**Comment by antoniovilela** [comment]
ignore testes-rejected with external-failure

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
