### PR TITLE
[14_1_X] Fix DQM Certification JSON Parsing From Web in `das-up-to-nevents.py`

### PR DESCRIPTION
**Pull request by AdrianoDee**
#### PR description:

Plain backport of #46559

### CODE REVIEW

**Comment by AdrianoDee** [comment]
backport of #46559

**Comment by AdrianoDee** [comment]
please test

**Comment by AdrianoDee** [comment]
urgent

**Comment by AdrianoDee** [comment]
+pdmv

**Comment by Moanwar** [comment]
+Upgrade

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
