### PR TITLE
Bug-fix for rapidity filtering in pA collisions

### PR DESCRIPTION
**Pull request by yetkinyilmaz**
Two bugfixes:
- Added missing boost direction in the asymmetric pA system, clarified names of corresponding VtxSmeared scenarios.
- In gen-filtering, the filter should apply after the boost, therefore a customization function is needed to swap the order of VtxSmeared and filter.
  by @MiheeJo @mandrenguyen

### CODE REVIEW

**Comment by bendavid** [comment]
Are these changes already in 74x?  If not, please open a pull request there as well.

**Comment by yetkinyilmaz** [comment]
In 74X, the mixing is implemented differently, there is a major 
pull-request:

https://github.com/cms-sw/cmssw/pull/6982

**Comment by bendavid** [comment]
+1

**Comment by smuzaffar** [comment]
@yetkinyilmaz, workflow 80.0 is failing in 53X IBs, could it be due to this pull request?
https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc6_amd64_gcc472/CMSSW_5_3_X_2015-01-14-1700/pyRelValMatrixLogs/run/80.0_AMPT_PPb_5020GeV_MinimumBias+AMPT_PPb_5020GeV_MinimumBias+DIGI+RECO/step1_AMPT_PPb_5020GeV_MinimumBias+AMPT_PPb_5020GeV_MinimumBias+DIGI+RECO.log

**Comment by yetkinyilmaz** [comment]
Hi Shahzad;
yes, unfortunately this is because we didn't update the workflow for the 
corresponding name change in the vtxsmearing.
This commit was supposed to be added:

https://github.com/CmsHI/cmssw/commit/9decfc673f5add8efd14cc77e513967f0664f27e

I think this PR will fix this:

https://github.com/cms-sw/cmssw/pull/7178

**Pull request merged**
