### PR TITLE
Implement the fillDescriptions method for RawStreamFileWriterForBU

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Implement the `fillDescriptions()` method for the `RawStreamFileWriterForBU` module.
Clean up the module's parameters and directly use an `InputTag` in the python configuration.

#### PR validation:

None.

### CODE REVIEW

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
@smorovic do you think this would be useful ?

**Comment by fwyzard** [comment]
please test

**Comment by smorovic** [comment]
@fwyzard thanks for cleaning up the code. So far it's only used in testing on my side and the Unit test, but it's good to be up to date and more consistent with other modules.

**Comment by smorovic** [comment]
+1

**Comment by smorovic** [comment]
@fwyzard I just saw that in this script we still use `ProductLabel`:
https://github.com/cms-sw/cmssw/blob/master/EventFilter/Utilities/test/startBU.py#L131
`ProductLabel = cms.untracked.string("s"),`

and that script is part of the Unit Test, so I think the test will fail. I suppose that source is the new parameter name?

**Comment by fwyzard** [comment]
Yes.

Sorry, I grepped for `RawStreamFileWriterForBU` but I must have missed that. I'll update it accordingly.

**Comment by fwyzard** [comment]
@cmsbuild, abort

**Comment by fwyzard** [comment]
please test

**Comment by smorovic** [comment]
+1
Seems good, except relvals that are unrelated.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/32284	2e2b420
- changed files are in the daq part of the package EventFilter/Utilities/ which has shared signatures, not affecting the code relevant to reco; the changes look good anyways

**Comment by silviodonato** [comment]
+1

**Pull request merged**
