### PR TITLE
Create a prefire veto bit using trigger rules

### PR DESCRIPTION
**Pull request by apana**
Add trigger bit to emulated GlobalExtBlk to indicate event could not have been caused by prefiring of the trigger. GlobalExtBlk contains the technical trigger bit information. Since these bits are not properly emulated anyway it is save to add the bit here.

### CODE REVIEW

**Comment by rekovic** [comment]
please test

**Comment by rekovic** [comment]
+1

**Comment by fabiocos** [comment]
+operations

the update of the StandardSequences looks coherent with the purpose of the PR

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
@apana @rekovic this PR looks to introduce a circular dependency in the schedule, that causes two unit tests to fail, see https://cmssdt.cern.ch/SDT/cgi-bin/showBuildLogs.py/slc7_amd64_gcc700/www/fri/10.6-fri-23/CMSSW_10_6_X_2019-02-22-2300?utests 

----- Begin Fatal Exception 23-Feb-2019 12:42:16 CET-----------------------
An exception of category 'ScheduleExecutionFailure' occurred while
   [0] Calling beginJob
Exception Message:
Unrunnable schedule
Module run order problem found: 
simGtExtFakeStage2Digis consumes tcdsDigis, tcdsDigis consumes rawDataCollector, rawDataCollector after castorRawData [p
ath digi2raw_step], castorRawData after rpcpacker [path digi2raw_step], rpcpacker after dtpacker [path digi2raw_step], d
tpacker after cscpacker [path digi2raw_step], cscpacker after hcalRawDataVME [path digi2raw_step], hcalRawDataVME after 
esDigiToRaw [path digi2raw_step], esDigiToRaw after ecalPacker [path digi2raw_step], ecalPacker after SiStripDigiToRaw [
path digi2raw_step], SiStripDigiToRaw after siPixelRawData [path digi2raw_step], siPixelRawData after gtStage2Raw [path 
digi2raw_step], gtStage2Raw consumes simGtExtFakeStage2Digis
 Running in the threaded framework would lead to indeterminate results.
 Please change order of modules in mentioned Path(s) to avoid inconsistent module ordering.
----- End Fatal Exception -------------------------------------------------


----- Begin Fatal Exception 23-Feb-2019 12:43:32 CET-----------------------
An exception of category 'ScheduleExecutionFailure' occurred while
   [0] Calling beginJob
Exception Message:
Unrunnable schedule
Module run order problem found: 
rawDataCollector consumes gtStage2Raw, gtStage2Raw consumes simGtExtFakeStage2Digis, simGtExtFakeStage2Digis consumes tc
dsDigis, tcdsDigis consumes rawDataCollector
 Running in the threaded framework would lead to indeterminate results.
 Please change order of modules in mentioned Path(s) to avoid inconsistent module ordering.
----- End Fatal Exception -------------------------------------------------

**Pull request merged**
