### PR TITLE
Add 2018C 2018D relvals

### PR DESCRIPTION
**Pull request by zhenhu**
Add 2018C 2018D relvals

### CODE REVIEW

**Comment by zhenhu** [comment]
please test

**Comment by zhenhu** [comment]
+1

**Comment by prebello** [comment]
hi @fabiocos  if possible please merge it in pre3. we have tested them in pre2 campaign already. thank you.

**Comment by kpedro88** [comment]
+upgrade

**Comment by kpedro88** [comment]
+1

**Comment by kpedro88** [comment]
A bunch of these workflows are crashing in the IB:
https://cms-sw.github.io/relvalLogDetail.html#slc6_amd64_gcc700;CMSSW_10_3_X_2018-08-27-2300

**Comment by prebello** [comment]
@kpedro88  indeed confirming these relvals ended successfully in pre2. 
https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?campaign=CMSSW_10_3_0_pre2__data2018D-1535052722
https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?campaign=CMSSW_10_3_0_pre2__data2018C-1535051353

**Comment by zhenhu** [comment]
Hi @kpedro88 , I think the crash is due to the GT. https://github.com/cms-sw/cmssw/blob/CMSSW_10_3_X_2018-08-27-2300//Configuration/AlCa/python/autoCond.py#L33 . This GT doesn't not cover 2018 C and D. We need to switch to a newer version 103X_dataRun2_PromptLike_v2

**Comment by kpedro88** [comment]
Ah, I didn't realize we still had such an old tag there. This should be fixed with #24381

**Comment by prebello** [comment]
@kpedro88 please test with new GT 103X_dataRun2_PromptLike_v3

**Comment by zhenhu** [comment]
@kpedro88 , yes #24381 updated the prompt-like GT  https://github.com/cms-sw/cmssw/pull/24381/files#diff-8cbfe6480e6018966eac475523946acdR39

**Pull request merged**
