### PR TITLE
reduce CCC by 6%

### PR DESCRIPTION
**Pull request by VinInn**
see presentation at TRK-POG on Monday 23/3/2015

### CODE REVIEW

**Comment by venturia** [comment]
Are we applying the cluster charge cut at the clusterizer level? I think we have already discussed about that but I am scared if this is the case because we loose handles to monitor the detector, especially at the beginning of run2.

**Comment by VinInn** [comment]
@venturia,
no we do not by default

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
Vincenzo, is it 4% or 6%?
the commit message and the subject of the PR don't match

**Comment by slava77** [comment]
... numerically, it's 6%; so, it's the commit message that's off.

**Comment by slava77** [comment]
I'm going to run higher stat tests

**Comment by slava77** [comment]
@Martin-Grunewald 
what are the plans for HLT?
Are you also going to change the cuts or are you going to stay with the current values
```
HLTSiStripClusterChargeCutLoose = cms.PSet(  value = cms.double( 1724.0 ) )
HLTSiStripClusterChargeCutTight = cms.PSet(  value = cms.double( 2069.0 ) )
```
?

**Comment by Martin-Grunewald** [comment]
@slava77 @mtosi 
Depends on what tracker wants at HLT - Mia, should we also change and if so when?
But then we need a JIRA ticket requesting the change at HLT level!

**Comment by VinInn** [comment]
HLT should align itself to offline

**Comment by mtosi** [comment]
I've just read this thread (sorry)
yes, please, we (HLT) have to be in synch w/ offline values

SiStripClusterChargeCutNone = cms.PSet(
value = cms.double(-1.0)
)
SiStripClusterChargeCutLoose = cms.PSet(
value = cms.double(1620.0)
)
SiStripClusterChargeCutTight = cms.PSet(
value = cms.double(1945.0)
)

JIRA ticket:
https://its.cern.ch/jira/browse/CMSHLT-308

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/8397	 68c9286

changes are as expected: more tracks, more charge on track, more time spent to reconstruct; fake rates are essentially unchanged, the efficiency goes up a bit.

Technical performance changes in 25202 (TTbar PU35 run2 setup):
- CPU in RECO sequence goes up by about 2.0%; (parts of) pixelLess and tobTec steps; and convTrack tracking are up by ~10% among the most significant ones
- sizes: 
    - the number of track increases by about 1%, 
    - allConversions are up by ~6% (somewhat similar increase is visible in other "jetty" workflows) 
    - which, with increases downstream, increases the  AOD size by 0.6% (RECO size is up by 0.4%)

Here are a few plots indicating the effect of the cut change in DQM (wflow 25202)

wf25202_tecm_charge_ontrack_percm
wf25202_gen_techits
wf25202_gen_tibhits

3TeV dijet
wf1313_gen_eff_vs_r



wf25202_tidm_charge_ontrack_percm

**Comment by davidlange6** [comment]
+1

**Pull request merged**
