### PR TITLE
Run4-hgx263 Take care of Static Analyzer Issues

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Take care of Static Analyzer Issues

#### PR validation:

These were compilation issues and tested

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by kpedro88** [comment]
please test

**Comment by cvuosalo** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade

**Comment by qliphy** [comment]
+1

**Pull request merged**
