### PR TITLE
backporting default decayer behavior from HEAD

### PR DESCRIPTION
**Pull request by sbein**
#### PR description:
This is to backport the default setting that GEN decays be taken in place of FastSim decayer decays (https://github.com/cms-sw/cmssw/pull/38813). This should be standard for Run 3 MC.

### CODE REVIEW

**Comment by sbein** [comment]
please test

**Comment by perrotta** [comment]
backport of #38813

**Comment by sbein** [comment]
+1

**Comment by rappoccio** [comment]
+1

**Pull request merged**
