### PR TITLE
Need unqiue cfi file names in fillDescription to avoid overwriting in HLT (80X)

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
Need unqiue cfi file names in fillDescriptions to avoid overwriting in HLT (80X)
For ConfDB parsing
Added missing cfi file for new plugin

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by mmusich** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
