### PR TITLE
Migrate `CondTools/RunInfo` to esConsumes

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

Part of #31061. Migrates modules of `CondTools/RunInfo` to use esConsumes.
Profited of the PR to modernize the code and address several static analyzer warnings.

#### PR validation:

It compiles. Also passed locally `EcalIntercalibConstants_O2O_test` which makes use of ` CondTools/RunInfo/interface/BTransitionAnalyzer.h`

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

### CODE REVIEW

**Comment by mmusich** [comment]
test parameters:
  * addpkg CondTools/Ecal

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
please test

**Comment by ggovi** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
