### PR TITLE
(DAQ) jsoncpp moved to a namespace (14_1_X)

### PR DESCRIPTION
**Pull request by smorovic**
#### PR description:
Moved to jsoncollector namespace to avoid conflict with tensorflow import of this lib (newer version).
#### PR validation:

Tested in DAQ test system and produces valid json files.

### CODE REVIEW

**Comment by smorovic** [comment]
@cmsbuild please test

**Comment by smorovic** [comment]
+daq

**Comment by mmusich** [comment]
+hlt
   * see https://github.com/cms-sw/cmssw/pull/44990#issuecomment-2116677099

**Comment by mmusich** [comment]
type bug-fix

**Comment by rappoccio** [comment]
+1

**Pull request merged**
