### PR TITLE
Run3-TB59 Correct TB setups for Oct 2018 runs

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Correct HGCal Test Beam setups for two Oct 2018 runs

#### PR validation:

Tested using specific TB cfg's

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
Are the comparison differences unrelated to this PR?

**Comment by kpedro88** [comment]
@cvuosalo yes, they should be fixed by #30919

**Comment by kpedro88** [comment]
+upgrade

**Comment by cvuosalo** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
