### PR TITLE
Ctpps pixel clusrizer backport 92x

### PR DESCRIPTION
**Pull request by fabferro**
Backport of PR #19470 for ctpps pixel clusterizer

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by perrotta** [comment]
+1
The only difference with #19470 is in the Configuration/AlCa/python/autoCond.py, but by now in 92X there are already even more recent GTs that that supersede those that were merged with the original PR in the master.
For the rest, only one extra empty line is added here wrt the original PR in the master

**Comment by arunhep** [comment]
+1

**Comment by perrotta** [comment]
@ggovi, @civanch, @lveldere could you please review and sign, if you think so?
This PR is needed to backport further CTPPS developments to 92X

**Comment by ggovi** [comment]
+1

**Comment by perrotta** [comment]
@davidlange6 : only fastsim signature is missing in this backport PR, already merged in the master since two weeks. Other CTPPS backports (e.g. #19831) would benefit of having this merged in 92X IBs, before being merged themselves.  Would you agree merging this, if  @civanch, @lveldere are not available in these days for evaluating it? 

(The fastsim related update included in this PR is the addition of the ctppsPixelLocalReconstruction in FastSimulation/Configuration/python/Reconstruction_AftMix_cff.py)

**Comment by davidlange6** [comment]
merge

**Pull request merged**
