### PR TITLE
Add energy correlation functions to jet tools 74 

### PR DESCRIPTION
**Pull request by smuzaffar**

### CODE REVIEW

**Comment by smuzaffar** [comment]
@slava77 and @ahinzmann , this is same as @11075

**Comment by davidlange6** [comment]
@cmsbuild, please test

**Comment by cvuosalo** [comment]
+1

For #11117 ef1fc36223728cba675877035c57d1368f6b05f6

Adding energy correlation functions to jet tools. This new tool doesn't run in standard workflows, so there should be no changes in run-time behavior. #11074 and #11028 are the 75X and 76X versions of this PR, the former has already been approved by Reco and the latter has already been merged.

The new code is satisfactory. Jenkins tests against baseline CMSSW_7_4_X_2015-09-02-2300 show no significant differences, as expected.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
