### PR TITLE
New scenario without  Pixel Extension (phase2, HGCAL version of the calorimeter)

### PR DESCRIPTION
**Pull request by boudoul**
As requested by upgrade managers, I created a new scenario which corresponds to the usual HGCAL (V5 with Pandora reconstruction) in which I removed the tracker pixel extension. I'm still testing it to be sure to validate locally my config. A set of relvals will be requested once fully integrate in a release.
It can be tested with the workflow 162XX.
(a similar one with Shashlik is already available for some time, 134XX)

### CODE REVIEW

**Comment by mark-grimes** [comment]
please test

**Comment by mark-grimes** [comment]
Also test 16200 and 16261 privately, all seems fine.  As far as I can see this is ready to go.
@boudoul,

> I'm still testing it to be sure to validate locally my config

Do you want to wait before merging?  I can merge and ask for a patch release as soon as you're ready.

**Comment by fratnikov** [comment]
@boudoul: this PR waits for your sign off

**Comment by boudoul** [comment]
Hi @fratnikov and @mark-grimes , sorry I am at CHEP, hence the delay in my answer, you can proceed with merging, thanks

**Comment by fratnikov** [comment]
merge

**Pull request merged**
