### PR TITLE
Egamma additions to HCAL and ES reduced rec hit collections

### PR DESCRIPTION
**Pull request by Sam-Harper**
@lgray @matteosan1 

This pull request adds in more HCAL and ES rec-hits to the reduced rec-hit collections for AOD. With the loss of CaloTowers in the event, there is no unbiased HCAL information in the AOD for electrons. This information is extremely useful for studies and understanding electrons and in some minimal form needs to be there.

For ged electrons/photons/superclusters with Et>20 GeV, all HCAL HBHE rec-hits with E>0.8 GeV within 5 towers of the seed crystal of the supercluster are added to the existing reducedRecHit collection. 

For all ged electrons/photons Et>20 GeV && superclusters Et>500 GeV, all ES RecHits of ES PFClusters associated to EE PF Clusters within dR<0.4 of the supercluster are saved. 

This was tested on the dataset:
/RelValTTbar_13/CMSSW_7_4_0_pre2-PU25ns_MCRUN2_73_V7-v1/GEN-SIM-RECO
specifically:
/store/relval/CMSSW_7_4_0_pre2/RelValTTbar_13/GEN-SIM-RECO/PU25ns_MCRUN2_73_V7-v1/00000/12EFC87E-C29A-E411-ABAA-003048FFD79C.root

The increase in the ES and HCAL rec-hit collections are as follows:

HBHERecHitsSorted_reducedHcalRecHitsNew_hbhereco_AODTest. 13856.8 6531.14
HBHERecHitsSorted_reducedHcalRecHits_hbhereco_RECO. 12646.5 5840.52
increase of 691 bytes

EcalRecHitsSorted_reducedEcalRecHitsESNew__AODTest. 5780.54 2697.32
EcalRecHitsSorted_reducedEcalRecHitsES__RECO. 5326.68 2492.3
increase of 205 byes

total increase of 0.88KB

Note on technical details: 
The ES DetId producer had hard code quality cuts on the ES Rec-Hits. It is not clear to me that this is intended and to me it little sense because we are trying to save all the rec-hits used in the clustering but th clustering doesnt have these requirements. So for my addition, I added a way to specify collections that were not to be cleaned.

Given I can now recreate ECAL & HCAL PF clusters in my region of interest around my electrons with the extra information in the reducedRecHit collections, I withdraw my proposal for storing the ECAL & HCAL PF clusters in packed form. It is not perfect but close enough.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@nclopezo @ktf 
did jenkins get stuck somewhere?
I don't see results comping out for hours

**Comment by slava77** [comment]
.. I'm checking it

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/7496	3f62408

- almost all diffs are in the reduced HcalRecHits. Here the size increase varies depending on the sample: ttbar PU35@25 ns has ~10% increase in the reducedHcalRecHits collection size, the 3 TeV dijet sample has ~130% increase in reducedHcalRecHits size
- changes in reducedEcalRecHitsES are tiny

Hcal DQM plots from global rechit validation show changes:
e.g. in dijet 3 TeV
wf1313_he_rechit_resolution
this change is expected because the module plotting it reads all rechits in the event, not checking if it shows up twice ( ``` iEvent.getManyByType(hbhe); ``` )
It's a feature (bug?) of this validation module.

**Comment by nclopezo** [comment]
@slava77, there was a glitch in Jenkins, I restarted the tests manually.

**Pull request merged**
