### PR TITLE
Run2-sim10 Fix the issue of reflected volume in getting distance of hit point from front of xtal in EB/EE

### PR DESCRIPTION
**Pull request by bsunanda**
Computation of hit point position along crystal had a bug for reflected solids in EB/EE

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
-1
@bsunanda , sorry, sensitive detector cannot depend of 
TH2F.h

If we need some checks with histograms it should be outside production code

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
@bsunanda , sorry, that do not raised this question before. You added a second map to the class. In the 1st map crystal length is stored, in the 2nd - the sign. It is enough to have only 1st map where double may be positive or negative. The position will be computed as std::abs(depth*0.5 + z), the code will be simpler and no extra map check in the run time.

**Comment by bsunanda** [comment]
@civanch I made the changes. Please check it once more

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by slava77** [comment]
https://github.com/cms-sw/cmssw/pull/19478#issuecomment-312316779
> Reco comparison results: 9425 differences found in the comparisons

there are changes in all MC workflows.

since this is not a technical PR, some description of expected physics change would be nice for future references.

**Comment by civanch** [comment]
@bsunanda, do I understand correctly, that this depth is used for corrections of sim hits or digi? If this is true, this fix  will require changings downstream and may be not in one place. I have no other explanation of observed differences.

**Comment by bsunanda** [comment]
@civanch I don't think this will cause genuine change. There was a bug in the calculation of distance along the path for reflected volumes which would have caused transmission loss calculation wrong for reflected volumes. This may be the reason for differences. In that case this is a real bug fix.

**Comment by bsunanda** [comment]
@civanch It was meant for special studies where the old way of computing path length was found to give a strange behavior - some crystals show standard longitudinal shower profile while others inverted profile. This is now corrected here. If so we have to back port this to all previous ones which are used for MC production

**Comment by civanch** [comment]
@bsunanda , I agree and this means that downstream corrections are biased. Let me test a bit today and I will sign it.

**Comment by civanch** [comment]
Is it used only for validation or longitudinal non-uniformity corrections are applied for hits?

**Comment by civanch** [comment]
+1
@bsunanda , sorry for late sign, I agree with it now. Likely the description of this PR needs to be extended. This fix really affect Ecal, so it should be known.

Independently of that I would re-discuss how reflection is done. From my point of view, if it would be done correctly this problem would not happen.

**Comment by davidlange6** [comment]
hi @bsunanda @civanch - is there a summary of which releases/geometries/configurations are affected?

**Comment by civanch** [comment]
@davidlange6, as far as I understand, it effects all geometries but a big effect for time detection.

**Comment by bsunanda** [comment]
@davidlange6 @civanch I agree with Vladimir

**Comment by davidlange6** [comment]
no sure i understand. So all geometries. Fine. (worst possible answer, but ok)

the impact on a naive user of CMS MC is 0 or non-0?

**Comment by civanch** [comment]
@bsunanda , @davidlange6 , sorry, only now understand what happens. In the class ECalSD there are two methods curve_LY(..) - used in run1 and run2, allowing take into account ageing and light collection non-uniformity. This method uses crystalLength() method and both where correct (double checked with tracking verbosity) and no change required . 

There is also a new method for upgrade simulation getLayerIDForTimeSim(..) for computation of time signal, where there was a bug. It seems to me now, that the map should not be changed and crystalLength(..) should always return positive value. In the getLayerIDForTimeSim(..) and simple formula (0.5*crlength - localPoint.z()) should be used in all cases as a distance between hit and APD. 

So, in this PR the initialisation of the map should be revert to previous situation, and only getLayerIDForTimeSim(..) should be fixed. In that case all differences except those for upgrade should disappear.

**Comment by bsunanda** [comment]
@civanch I am now confused with your comment. Please let me know what is wrong with this PR - which method is not working correctly

**Comment by civanch** [comment]
@bsunanda , I have checked that for run-2 the code is working fine. The method to comput depth is working in a correct way, so no need to change anything related to the old code (the map of LV versus depth should be unchanged). All problems are only in method where time is computed getLayerIDForTimeSim(..)

**Comment by bsunanda** [comment]
@civanch So in this PR is shall check getLayerIDForTimeSim(..) method? Am I right? The refl volume was causing problem in getRadiationLength(..) which is corrected. I think the earlier version of curve_LY was not correct - my debug plots for depth vs r_B or z_E showed that depth computation is now done correctly.

**Comment by bsunanda** [comment]
@civanch I would like to put those debug plots back again if you want.

**Comment by bsunanda** [comment]
eb1
eb2
ee1
ee2

**Comment by bsunanda** [comment]
I think this PR gives the right values for getLayerIDForTimeSim(..), getRadiationLength(..) and curve_LY(..). I shall restore the debug plots - it resolves many questions which could be asked later.

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
@bsunanda, you have added TF2 into EcalSD, this cannot be in production code.

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@civanch I protect the use of TH2 in .h and .cc with plotDebug

**Comment by bsunanda** [comment]
@civanch Is there anything missing for this? The inclusion of histogram is protected

**Comment by civanch** [comment]
+1
The issue has been discussed at Simulation meeting : https://indico.cern.ch/event/652343/contributions/2655467/attachments/1489938/2315496/Sim-Talk27.pdf 
@davidlange6, it turned out that we have Ecal geometry problem cince CMS beginning. Rotation matrix from global to local coordinate system rotate half of crystals for 180 degrees. The fix, proposed by Sunanda in this PR, restores correct computation of distance between APD and hit. Possible another fix may be done on level geometry or DD classes, I tried to debug but not yet find out the source of the problem and it is not clear if an easy fix is exist. If in future we will find out better fix, it should not change simulation history. This PR change the history, because Ecal hit energy may be changed up to 2%.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
