### PR TITLE
stack trace on SIGABRT to catch assertion failures

### PR DESCRIPTION
**Pull request by dan131riley**
This PR adds SIGABRT to the list of signals for which we initiate a stack trace.  This is motivated by recent assertion failures in ROOT 6.12 builds that may be due to thread-safety issues.  Since the InitRootHandlers module itself calls abort() to handle some failure modes, the modifications are careful to reset the SIGABRT handler to SIG_DFL at the appropriate places.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by Dr15Jones** [comment]
@fabiocos it would be very helpful to get this is as soon as possible in order to track down several failures that are occurring.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
