### PR TITLE
Use std::bind in place of boost:bind

### PR DESCRIPTION
**Pull request by Purva-Chaudhari**
#### PR description:

In this case we can use std::bind instead of boost::bind

#### PR validation:

Passed on basic runTheMatrix test.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

@davidlange6 @vgvassilev

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by alja** [comment]
+1

**Comment by perrotta** [comment]
+reconstruction
- Trivial for reco: just one unneeded include removed from RecoLocalTracker/SiPixelRecHits/src/VVIObj.cc

**Comment by agrohsje** [comment]
@Purva-Chaudhari  I see in some files a change of the include but no corresponding change from boost::bind to std:bind. I assume that means the include isn't needed at all, no?

**Comment by Purva-Chaudhari** [comment]
> @Purva-Chaudhari I see in some files a change of the include but no corresponding change from boost::bind to std:bind. I assume that means the include isn't needed at all, no?

Yes! There were some unnecessary #include for boost bind. I cleaned those finding that it wasn't.

**Comment by agrohsje** [comment]
+generators

**Comment by makortel** [comment]
+core

**Comment by civanch** [comment]
+1

**Comment by qliphy** [comment]
@cms-sw/db-l2  Do you have any comments?

**Comment by qliphy** [comment]
+1

@cms-sw/db-l2 let us know if you have comment.

**Comment by qliphy** [comment]
merge

**Pull request merged**
