### PR TITLE
MTD Validation: addition of plots for the impact of MTD on Pt resolution 

### PR DESCRIPTION
**Pull request by rdelliga**
#### PR description:
Added to MTD Tracks Validation some plots to monitor the impact of MTD hits on the tracks Pt resolution. For details see the presentation at https://indico.cern.ch/event/1368740/contributions/5756499/attachments/2782834/4850767/MTD_January_DelliGatti.pdf
A macro to provide plots was also added.

#### PR validation:
Code compilation and production of plots.

### CODE REVIEW

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
@cms-sw/dqm-l2 any comment?

**Comment by tjavaid** [comment]
+1

- spurious differences observed from unstable WF `12434.7` (open issue #39803 )

**Comment by rappoccio** [comment]
+1

**Pull request merged**
