### PR TITLE
HBHEGPU: Channel quality gpu [master]

### PR DESCRIPTION
**Pull request by mariadalfonso**
forward port of https://github.com/cms-sw/cmssw/pull/35355

### CODE REVIEW

**Comment by fwyzard** [comment]
enable gpu

**Comment by fwyzard** [comment]
please test

**Comment by tvami** [comment]
> enable gpu

@fwyzard I think you missed this
https://github.com/cms-sw/cmssw/pull/35355#issuecomment-924811817
(i.e. adding 11634.522 -- unless it's in there in default)

**Comment by tvami** [comment]
test parameters:
 - workflows_gpu = 11634.522
 - enable_test = gpu

**Comment by tvami** [comment]
@cmsbuild , ping

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by fwyzard** [comment]
@mariadalfonso could you add this change via a new commit, to avoid breaking the HLT customisation ?
```diff
Author: Andrea Bocci <andrea.bocci@cern.ch>
Date:   Thu Sep 23 11:37:31 2021 +0200

    Add HcalChannelQualityGPU to the HLT customisation

diff --git a/HLTrigger/Configuration/python/customizeHLTforPatatrack.py b/HLTrigger/Configuration/python/customizeHLTforPatatrack.py
index 89987dd8320f..6cf64955ee1d 100644
--- a/HLTrigger/Configuration/python/customizeHLTforPatatrack.py
+++ b/HLTrigger/Configuration/python/customizeHLTforPatatrack.py
@@ -543,6 +543,7 @@ def customiseHcalLocalReconstruction(process):
 
     process.load("EventFilter.HcalRawToDigi.hcalElectronicsMappingGPUESProducer_cfi")
 
+    process.load("RecoLocalCalo.HcalRecProducers.hcalChannelQualityGPUESProducer_cfi")
     process.load("RecoLocalCalo.HcalRecProducers.hcalGainsGPUESProducer_cfi")
     process.load("RecoLocalCalo.HcalRecProducers.hcalGainWidthsGPUESProducer_cfi")
     process.load("RecoLocalCalo.HcalRecProducers.hcalLUTCorrsGPUESProducer_cfi")
```

**Comment by fwyzard** [comment]
I've tested this PR as described in https://github.com/cms-sw/cmssw/issues/35376, and while it significantly reduces the HCAL-related discrepancies, it does not eliminate them completely.

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by mariadalfonso** [comment]
> I've tested this PR as described in #35376, and while it significantly reduces the HCAL-related discrepancies, it does not eliminate them completely.

I suggest to finalise the review of this and merge it.
I will look after the residual discrepancies.

**Comment by fwyzard** [comment]
Sounds like a good idea to me.

**Comment by jpata** [comment]
+reconstruction
- sync Mahi on GPU with what is done on CPU, to solve (but not completely eliminate) differences in the Run3 HLT menu
- minor differences in GPU workflows for HBHERecHitsSorted are observed, this is expected

**Comment by Martin-Grunewald** [comment]
+1

**Comment by tvami** [comment]
> I suggest to finalise the review of this and merge it.

I've not seen my comments addressed: https://github.com/cms-sw/cmssw/pull/35355#issuecomment-925050394

**Comment by mariadalfonso** [comment]
> > I suggest to finalise the review of this and merge it.
> 
> I've not seen my comments addressed: [#35355 (comment)](https://github.com/cms-sw/cmssw/pull/35355#issuecomment-925050394)

well, no way this PR affects the Pixel aligment.
Are you sure the test didn't pick up some other changes ?

**Comment by tvami** [comment]
> > > I suggest to finalise the review of this and merge it.
> > 
> > 
> > I've not seen my comments addressed: [#35355 (comment)](https://github.com/cms-sw/cmssw/pull/35355#issuecomment-925050394)
> 
> well, no way this PR affects the Pixel aligment.
> Are you sure the test didn't pick up some other changes ?

@mariadalfonso yes, I've resubmitted the tests several times and got the same results, and then the same thing is there in the master and the backport.

**Comment by tvami** [comment]
> > > > > I suggest to finalise the review of this and merge it.
> > > > 
> > > > 
> > > > I've not seen my comments addressed: [#35355 (comment)](https://github.com/cms-sw/cmssw/pull/35355#issuecomment-925050394)
> > > 
> > > 
> > > well, no way this PR affects the Pixel aligment.
> > > Are you sure the test didn't pick up some other changes ?
> > 
> > 
> > @mariadalfonso yes, I've resubmitted the tests several times and got the same results, and then the same thing is there in the master and the backport.
> 
> Do these spurious GPU-"Pixel alignment" plots appears also in previous PR's test ? 

Not that I know of, i.e. nothing that touches AlCa. Maybe @cms-sw/reconstruction-l2 sees them in other PRs?

**Comment by slava77** [comment]
> > Do these spurious GPU-"Pixel alignment" plots appears also in previous PR's test ?
> 
> Not that I know of, i.e. nothing that touches AlCa. Maybe @cms-sw/reconstruction-l2 sees them in other PRs?

some of the pixel GPU reco is not repeatable

**Comment by tvami** [comment]
+db

**Comment by tvami** [comment]
+alca
 * differences are understood
 * differences in Pixel wfs on GPUs are due to the fact that "some of the pixel GPU reco is not repeatable" see above

**Comment by qliphy** [comment]
+1

**Pull request merged**
