### PR TITLE
Phase2 Outer Tracker : Incorporating recent changes from TEDD Design + cleaning

### PR DESCRIPTION
**Pull request by boudoul**
Greetings, this PR aims to introduce in the dev Phase2 Tracker (=T6,T7,T8) the changes from Mechanical design studies in the TEDD - The changes were presented here https://indico.cern.ch/event/709594/contributions/2931560/attachments/1615255/2566756/upgSim180312_GB.pdf  - Those are so small that basically no regression  should be observed.
The changes in the geometry were done by @ghugo83 .

I also took the opportunity clean previous detids files which were either not used, or not well named , so that now they are associated to the corresponding Tracker (T5 , T6 , T7, T8, ..) appropriately instead of previous cryptic names ; and therefore will be much help some future developments in progress related to cabling map . 
@emiglior FYI

### CODE REVIEW

**Comment by boudoul** [comment]
this PR should be tested with the files from the externals that I just created : https://github.com/cms-data/SLHCUpgradeSimulations-Geometry/pull/10

**Comment by boudoul** [comment]
thank you @mrodozov for the super prompt reaction !

**Comment by kpedro88** [comment]
Changes are isolated to 21234.0 (D21 detector w/ T6), appears to be caused by statistical fluctuations from differences in the simulation history (expected for any geometry change)

**Comment by kpedro88** [comment]
+1

**Comment by ianna** [comment]
+1

**Comment by fabiocos** [comment]
@boudoul @ghugo83 @kpedro88 I see that this PR, that for the rest looks ok to enter into the release, is changing the tracker scenario V404, about which we were discussing for the MTD addition. From the initial comment of Gaelle I understand that the expected changes are so small to be negligible, but they are non zero. So up to which point do we consider this scenario as frozen?

**Comment by emiglior** [comment]
@boudoul @ghugo83 @fabiocos @kpedro88 
My understanding is that there are no short term changes foreseen for the OuterTracker with respect those in this PR (OT v.6.1.4) but we expect changes for the InnerTracker compared to IT v4.0.4

**Comment by fabiocos** [comment]
@emiglior thank you Ernesto, that is ok, but I assume it will be a new version. here we are discussing about changes, although minor, in the very same version, and a similar discussion is ongoign about the possibility to refactor the geometry structure in these existing scenarios to accomodate the new BTL volume and have a separate OTST volume. For me, provided that the geometry and material distributions are unchanged it is not a big issue if there is a valid reason (and we validate that there is no change)

**Comment by fabiocos** [comment]
In any case, I understand that this D21 scenario has been used so far in tests and not in massive productions, am I correct? If this is the case, I will integrate the package this evening

**Comment by emiglior** [comment]
> In any case, I understand that this D21 scenario has been used so far in tests and not in massive productions, am I correct?

I would say so. 2023D17 is the TDR geometry used for large productions; 2023D21 is the devel geometry used so far only for RelVal (SingleMu, TTbar, MinBias) in 10_0_0_pre1 (@boudoul may confirm)

**Comment by boudoul** [comment]
@fabiocos  I confirm, the 'frozen'  scenario is D17 , it does contain the TDR version and has been (is) the subject of MC production - the tracker within D21 is considered as a development one and is not for MC prod (at this point)

**Comment by fabiocos** [comment]
cms-sw/cmsdist/#3901 merged, merge also this package

**Comment by fabiocos** [comment]
+1

**Pull request merged**
