### PR TITLE
Use bin center for HGCal UncalibHits + Speedup in Digitizer

### PR DESCRIPTION
**Pull request by lgray**
Speed up in digitizer (was spending lots of time converting float to double or other silly things).
Try to remove branching or streamline it where possible.
Likely some significant improvement is still possible, but requires redesign.

Also change RecHits to use the bin center for TDC energy readout rather than the bin low edge.

### CODE REVIEW

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by civanch** [comment]
@lgray , in  SimCalorimetry/HGCalSimProducers/src/HGCDigitizerBase.cc  line 39 is not needed because in line 38 a comparison with zero already done.

If we speak on code optimisation then I am not sure if having very long method inlined is an optimal solution in HGCalUncalibRecHitRecWeightsAlgo.h, I would, at least, move makeRecHit to the source.

**Comment by lgray** [comment]
The RecHit producers are not a noticeable user of time (yet). You may
safely disregard them.

(Sent from my Nexus 6)
On Apr 13, 2016 11:57 AM, "Vladimir Ivantchenko" <notifications@github.com>
wrote:

@lgray <https://github.com/lgray> , in
SimCalorimetry/HGCalSimProducers/src/HGCDigitizerBase.cc line 39 is not
needed because in line 38 a comparison with zero already done.

If we speak on code optimisation then I am not sure if having very long
method inlined is an optimal solution in
HGCalUncalibRecHitRecWeightsAlgo.h, I would, at least, move makeRecHit to
the source.

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/cms-sw/cmssw/pull/14033#issuecomment-209347522>

**Comment by civanch** [comment]
+1

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/14033	9b38254
- changes in reco in DataFormats/HGCDigi and RecoLocalCalo/HGCalRecAlgos are rather minimal and are in line with the description
- jenkins test pass (compilation and unit tests; matrix relval workflows for phase 2 are not included)

**Pull request merged**
