### PR TITLE
Test AdaBoost conversion to GBRForest (75X)

### PR DESCRIPTION
**Pull request by lgray**
Backport of #10327

### CODE REVIEW

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
@degano Did you ever get https://github.com/cms-data/RecoEgamma-ElectronIdentification/pull/3 into 75X/74X IBs?

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
+1

For #10446 716c7ef7ae208f2dc5f0fe8a3c9f6654ad0898c3

Converting GsfElectronAlgo / Producers to use edm::GlobalCache object + GBRForest. There should be no significant change in monitored quantities, though there may be some jitter. This PR is the 75X backport of #10327, which has already been merged into 76X.

The code changes are satisfactory, and Jenkins [tests](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-10446/6858/summary.html) against baseline CMSSW_7_5_X_2015-07-30-1100 show no significant differences, as expected.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
