### PR TITLE
[12.4.X] Pixel Heterogenous DQM: fix bug in TProfile definitions 

### PR DESCRIPTION
**Pull request by sroychow**
#### PR description:
Backport of #38203

### CODE REVIEW

**Comment by sroychow** [comment]
enable gpu

**Comment by sroychow** [comment]
@cmsbuild  please test

**Comment by mmusich** [comment]
type tracking, bug-fix

**Comment by mmusich** [comment]
backport of https://github.com/cms-sw/cmssw/pull/38203

**Comment by emanueleusai** [comment]
please test

**Comment by emanueleusai** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
