### PR TITLE
Minor improvement for DQM/PhysicsHWW.

### PR DESCRIPTION
**Pull request by dmitrijus**
Vectors are no longer used as maps.
EventMonitor now directly responsible for filling monitor elements.
Adding a new counter to EventMonitor (after booking) will trigger an error.

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Comment by davidlange6** [comment]
looks like this is crashing relvals. making a revert-ed PR to test it.

**Pull request merged**
