### PR TITLE
GEM Slice Test Geometry + related Validation Package Changes

### PR DESCRIPTION
**Pull request by pietverwilligen**
This PR fixes the GEMGeometryBuilder to be constructed from the CondDB.
This way the GEM Slice Test geometry (5 chambers) in the negative endcap
gets constructed correctly from the database.
Furthermore it adds several fixes to the Validation Package such that it works
with the GEM Slice geometry.

This is a follow up on PR  #18257 with as modification another GEM_2017_MCTest 
identifier for the GEM Simulation that is not included in the standard Run_2 Era.

### CODE REVIEW

**Comment by kpedro88** [comment]
please test

**Comment by perrotta** [comment]
Please submit to the master release (92X, by now) first.
When merged over there, it can then be backported to 91X

**Comment by pietverwilligen** [comment]
i created a 92X PR just before cmsbuild said that there were runTheMatrix errors.
92X PR: #18655

**Comment by ianna** [comment]
Here is the error:
```
----- Begin Fatal Exception 10-May-2017 00:23:02 CEST-----------------------
An exception of category 'ProductNotFound' occurred while
   [0] Processing  Event run: 1 lumi: 1 event: 1 stream: 0
   [1] Running path 'prevalidation_step'
   [2] Prefetching for module MultiTrackValidator/'trackValidator'
   [3] Prefetching for module DuplicateListMerger/'generalTracks'
   [4] Prefetching for module TrackProducer/'mergedDuplicateTracks'
   [5] Prefetching for module DuplicateTrackMerger/'duplicateTrackCandidates'
   [6] Prefetching for module TrackCollectionMerger/'preDuplicateMergingGeneralTracks'
   [7] Prefetching for module TrackProducer/'muonSeededTracksInOut'
   [8] Prefetching for module CkfTrackCandidateMaker/'muonSeededTrackCandidatesInOut'
   [9] Prefetching for module MuonReSeeder/'muonSeededSeedsInOut'
   [10] Prefetching for module MuonIdProducer/'earlyMuons'
   [11] Prefetching for module StandAloneMuonProducer/'standAloneMuons'
   [12] Calling method for module GEMRecHitProducer/'gemRecHits'
Exception Message:
Principal::getByToken: Found zero products matching all criteria
Looking for type: MuonDigiCollection<GEMDetId,GEMDigi>
Looking for module label: simMuonGEMDigis
Looking for productInstanceName: 

   Additional Info:
      [a] If you wish to continue processing events after a ProductNotFound exception,
add "SkipEvent = cms.untracked.vstring('ProductNotFound')" to the "options" PSet in the configuration.

----- End Fatal Exception -------------------------------------------------
```

**Comment by pietverwilligen** [comment]
i have updated the PR. @slava77 @calabria I have moved all GEM Slice Test code to the GEM_2017_MCTest identifier. Is that what you wanted? Now it is not tested anywhere. This is ok because reconstructing 2016 data with the 2017 tag is nonsense for GEM. On the other hand it is a pity because the full-blown 2017 MC worked with GEM included (GEM in --> GEM out, without any problems). How would you  test the GEMSlice test now?

**Comment by davidlange6** [comment]
so how does one get the right gen-sim for 2017 GEM? (since apparently the wrong one is being used)

**Comment by slava77** [comment]
On 5/10/17 1:35 AM, Piet Verwilligen wrote:
> i have updated the PR. @slava77 <https://github.com/slava77> @calabria
> <https://github.com/calabria> I have moved all GEM Slice Test code to
> the GEM_2017_MCTest identifier. Is that what you wanted? Now it is not
> tested anywhere. This is ok because reconstructing 2016 data with the
> 2017 tag is nonsense for GEM. On the other hand it is a pity because the
> full-blown 2017 MC worked with GEM included (GEM in --> GEM out, without
> any problems). How would you test the GEMSlice test now?

MC-specific tests can be run with the GEM_2017_MCTest modifier

If a full workflow is needed in the relval matrix, a workflow can be
created,
but you will need to create a new era for that, something based on
Run2_2017 .. e.g
Run2_2017_gemMCTest or similar in the name
(IIRC cmsDriver does not accept multiple eras).

**Comment by ianna** [comment]
@slava77 - what is wrong with run2_GEM_2017 modifier? Isn't it for GEM in 2017?

**Comment by slava77** [comment]
On 5/10/17 6:34 AM, Ianna Osborne wrote:
> @slava77 <https://github.com/slava77> - what is wrong with run2_GEM_2017
> modifier? Isn't it for GEM in 2017?

All reco features can not be enabled with it due to absence of the raw
data unpacker.
So, as long as it acts on just MC-specific parts of the workflows (e.g.
GEN-SIM), it's a fine modifier.

The complete modifier that serves reco but works only for MC will have
to be named differently
and can not be a part of Run2_2017 era.

**Comment by pietverwilligen** [comment]
Please test

**Comment by kpedro88** [comment]
@slava77 I think `cmsDriver.py` does accept multiple Eras as comma-separated input...

**Comment by kpedro88** [comment]
please test

**Comment by slava77** [comment]
On 5/10/17 7:28 AM, Kevin Pedro wrote:
> @slava77 <https://github.com/slava77> I think |cmsDriver.py| does accept
> multiple Eras as comma-separated input...
> 

indeed
https://github.com/cms-sw/cmssw/blob/master/Configuration/Applications/python/ConfigBuilder.py#L2067

**Comment by ianna** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Comment by davidlange6** [comment]
Closing PR. CMSSW_9_1_X is for muon TDR upgrade changes only (CMSSW_9_2_X for data taking)

**Pull request closed without merging**
