### PR TITLE
Use rapidity instead of pseudo-rapidity in the packing of PackedGenParticles

### PR DESCRIPTION
**Pull request by arizzi**
It was noted that in existing miniAOD some GenJets have invalid refs to PackedGenParticles that extend in eta beyond 6. These particles cannot be saved because the range for eta in the packing is restricted to [-6,6]. 
On the other hand while eta of a GenJet constituent can extend beyond 6, the "rapidity" (used in jet clustering) cannot extend beyond GenJetEta + JetDRparameter. Considering relevant jets up to eta 5, the constituents should never exceed 6 (even for AK8 GenJets we should get up to 5.8).

The PackedGenCandidates are then fixed by storing persistently the "rapidity" in range [-6,6] rather than the pseudorapidity.
An ioread function is provided to keep compatibility (i.e. be able to read 72X MINIAOD)

Speed at read-time should be checked to see if this introduces any regression.

@gpetruc

### CODE REVIEW

**Comment by arizzi** [comment]
IB broken?

**Comment by slava77** [comment]
yes
https://hypernews.cern.ch/HyperNews/CMS/get/swReleases/4172/5.html


On 2/6/15 2:47 PM, arizzi wrote:
> IB broken?
> 
> On Fri, Feb 6, 2015 at 9:13 PM, cmsbuild <notifications@github.com> wrote:
> 
>> -1
>>
>> Tested at: c293253
>> <https://github.com/cms-sw/cmssw/commit/c293253551767128fffc1ea23132918d60fb4b9d>
>> I ran the usual tests and I found errors in the following unit tests:
>>
>> ---> test runtestPhysicsToolsPatAlgos had ERRORS
>>
>> you can see the results of the tests here:
>>
>> https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-7584/2425/summary.html
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/cms-sw/cmssw/pull/7584#issuecomment-73304501>.
>>
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cms-sw/cmssw/pull/7584#issuecomment-73309443>.
> 

-- 
***********************************************************************
 Vyacheslav (Slava) Krutelyov
 TAMU: Physics Dept Texas A&M MS4242, College Station, TX 77843-4242
 CERN: 42-R-027
 AIM/Skype: siava16              googleTalk: slava77@gmail.com
 (630) 291-5128  Cell (US)       +41 76 275 7116 Cell (CERN)

-----------------------------------------------------------------------

**Comment by davidlange6** [comment]
@cmsbuild, please test

**Comment by monttj** [comment]
+1
This has been already discussed in physics-analysis-tool hyper-news thread. 
https://hypernews.cern.ch/HyperNews/CMS/get/physTools/3301/2/5/1/1/1/2/1/1/2/1/1/1.html

**Comment by bendavid** [comment]
Discussed with @arizzi and I will instead rebase this one and add it on top of https://github.com/cms-sw/cmssw/pull/7662 since they otherwise will conflict.

**Pull request closed without merging**
