### PR TITLE
Fix GCC8 compiler warnings, catch exceptions by reference not value

### PR DESCRIPTION
**Pull request by wddgit**
Where possible catch by const reference. There are also a couple
changes the 'scram b code-checks' added in. I expect nothing is
here that would change results of anything.

### CODE REVIEW

**Comment by wddgit** [comment]
please test

**Comment by thomreis** [comment]
+1

**Comment by mommsen** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by perrotta** [comment]
+1
- Technical, it implements what declared in the title
- Jenkins tests pass: no changes expected in output, no one observed

**Comment by andrius-k** [comment]
+1

**Comment by fabozzi** [comment]
+1

**Comment by andrius-k** [comment]
+1

**Comment by fabiocos** [comment]
+1

pure technical code cleaning, changes look everywhere consistent with the PR declared purpose

**Comment by fabiocos** [comment]
merge

**Pull request merged**
