### PR TITLE
O20 for 8_0_15

### PR DESCRIPTION
**Pull request by depasse**
O2O from 8_0_1 to 8_0_15

### CODE REVIEW

**Comment by depasse** [comment]
Please BACKPORT to 8_0_15

**Comment by mmusich** [comment]
-1
@depasse, either a rebase is needed or the wrong base fork has been chosen.

**Comment by depasse** [comment]
My base fork is cms-sw/cmssw

How do you rebase ?
Thanks.

Pierre
________________________________

**Comment by mmusich** [comment]
@depasse it looks to me you made your PR against the wrong branch:
   * 81X: https://github.com/cms-sw/cmssw/compare/CMSSW_8_1_X...depasse:O2O_August2016?expand=1 (*does not merge*)
   * 80X: https://github.com/cms-sw/cmssw/compare/CMSSW_8_0_X...depasse:O2O_August2016?expand=1 (merges)

I suggest to use your current branch to make a pull request against 80x and make a new branch for 81x in which you apply your commit https://github.com/cms-sw/cmssw/commit/76f3d21c2fae498402cd068f31116963a29fcf53 on top the last 81X IB.
Hope this helps

M.

**Pull request closed without merging**
