### PR TITLE
Use explicit type for lambda in CaloSD

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

This works around a compiler crash in gcc 9.

#### PR validation:

This compiles fine using gcc 9.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
@Dr15Jones for my education, is there a specific reason why the "auto" statement should not work? Obviously this seems related to a modified behaviour of the compiler, I was just wondering whether there is anything strictly wrong...

**Comment by Dr15Jones** [comment]
My best guess is it is a compiler bug.

**Comment by fabiocos** [comment]
@Dr15Jones ok, thanks

**Pull request merged**
