### PR TITLE
Add missing newlines under CalibCalorimetry/EcalTPGTools

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Add missing newlines at the end of file under CalibCalorimetry/EcalTPGTools.

#### PR validation:

None.

### CODE REVIEW

**Comment by fwyzard** [comment]
please test

**Comment by aloeliger** [comment]
+l1

- technical changes

**Comment by saumyaphor4252** [comment]
+alca

**Comment by fwyzard** [comment]
please abort

**Pull request closed without merging**
