### PR TITLE
Fix DetectorDescription Parser unit test -- backport of #29947

### PR DESCRIPTION
**Pull request by cvuosalo**
See #29947. With the fix, the unit test runs successfully in 11_1.

### CODE REVIEW

**Comment by cvuosalo** [comment]
type bug-fix

**Comment by cvuosalo** [comment]
backport of #29947

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
