### PR TITLE
[13.0.X] Disentangle `TrackerTrackHitFilter` from phase-0 Strip conditions and activate common alignment track refitter sequence for phase-2

### PR DESCRIPTION
**Pull request by mmusich**
backport of https://github.com/cms-sw/cmssw/pull/40835

#### PR description:

The [common alignment track selection and refitting sequence](https://github.com/cms-sw/cmssw/blob/master/Alignment/CommonAlignment/python/tools/trackselectionRefitting.py) currently cannot run in Phase-2 setups because of missing Phase-0 SiStrip conditions. The module `TrackerTrackHitFilter` indeed requires at construction time the following conditions:

```
----- Begin Fatal Exception 21-Feb-2023 12:46:22 CET-----------------------
An exception of category 'NoRecord' occurred while
   [0] Processing  Event run: 1 lumi: 67 event: 6602 stream: 0
   [1] Running path 'p2'
   [2] Prefetching for module TrackerTrackHitFilter/'TrackerTrackHitFilter'
   [3] Prefetching for EventSetup module SiStripQualityESProducer/'siStripQualityESProducer'
   [4] Calling method for EventSetup module SiStripConnectivity/'sistripconn'
   [5] While getting dependent Record from Record SiStripDetCablingRcd
Exception Message:
No "SiStripFedCablingRcd" record found in the EventSetup.

 Please add an ESSource or ESProducer that delivers such a record.
----- End Fatal Exception -------------------------------------------------
```
As it seems that adding Phase-0 SiStrip conditions (either in GT or by dedicated `ESSource`) would be a wrong design choice, the goal of this PR is allow `TrackerTrackHitFilter` to run without Phase-0 SiStrip conditions, by means of adding a new parameter `isPhase2` that governs if the `SiStripClusterInfo` object used in `TrackerTrackHitFilter` should be constructed or not with an `esConsumes` call.  
This is achieved by using `std::optional` to declare the `SiStripClusterInfo` data member and construct it only if the workflow is not meant for Phase-2.

#### PR validation:

Run the dedicated test: `cmsRun $CMSSW_BASE/src/Alignment/OfflineValidation/test/test_all_Phase2_cfg.py `

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:
Verbatim backport of https://github.com/cms-sw/cmssw/pull/40835 to be able to be used in the phase-2 alignment studies happening in that cycle (see [PdmV JIRA ticket](https://its.cern.ch/jira/browse/PDMVMCPROD-70?focusedCommentId=4748857&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-4748857))

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by tvami** [comment]
+alca

**Comment by mandrenguyen** [comment]
+reconstruction
No changes to reco comparisons, changes only affect alignment workflows

**Comment by perrotta** [comment]
+1

**Pull request merged**
