### PR TITLE
DD4hep: Migrate Muon Algorithms to Geometry/MuonCommonData Package

### PR DESCRIPTION
**Pull request by ianna**
#### PR description:

* Move Muon algorithms to Geometry/MuonCommonData package under **dd4hep** directory
* Merge declaration and definition of the DD algorithms
* The code is unchanged

#### if this PR is a backport please specify the original PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by kpedro88** [comment]
please test
(to get clean comparisons)

**Comment by ianna** [comment]
@kpedro88 - well, it's clean :-)

**Comment by kpedro88** [comment]
+1

**Pull request merged**
