### PR TITLE
Drop tests for py3-hyperas, nose, rep and hyperopt

### PR DESCRIPTION
**Pull request by iarspider**
#### PR description:

These packages are not used and will be dropped. See here: https://github.com/cms-sw/cmsdist/pull/7400#issuecomment-952766556

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@qliphy @perrotta can we get this in ? This PR drops unit tests for few python packages which are not used in cmssw and not very actively maintained

**Comment by perrotta** [comment]
+1

**Comment by perrotta** [comment]
merge

**Comment by santocch** [comment]
+1

**Pull request merged**
