### PR TITLE
Revert "Full reco-material tuninig after PR 18651"

### PR DESCRIPTION
**Pull request by ianna**
Reverts cms-sw/cmssw#18824

### CODE REVIEW

**Comment by ianna** [comment]
@rovere - FYI

**Comment by ianna** [comment]
please test

**Comment by slava77** [comment]
@ianna 
is this a cleanup after integration in the DB or did we find problems?
Please clarify.
Thank you.

**Comment by rovere** [comment]
Close this PR, please. Those updates are meant to enter release and GT.
I'm investigating if **further** tuning is needed, but this one for sure is.

**Comment by ianna** [comment]
@slava77 - these changes has never made it in a GT. 

As I understood from @rovere, he tested SingleMu pt10 with the special GT prepared by @arunhep and @franzoni (92X_upgrade2017_realistic_ForRECOGeometry which did not include this reco material xml file) and did not noticed any significant improvements. Given that we need to move forward with a new 2017 scenario with GEM slice bug fixes, I'm reluctant to introduce this one to a GT without thorough testing.

**Comment by ianna** [comment]
@rovere - please, clarify if you have run other tests including this file? The tag TKRECO_Geometry_92YV1 included in 92X_upgrade2017_realistic_ForRECOGeometry does not have these changes.

**Comment by slava77** [comment]
On 6/20/17 1:40 PM, Ianna Osborne wrote:
> @slava77 <https://github.com/slava77> - these changes has never made it
> in a GT.
> 
> As I understood from @rovere <https://github.com/rovere>, he tested
> SingleMu pt10 with the special GT prepared by @arunhep
> <https://github.com/arunhep> and @franzoni <https://github.com/franzoni>
> (92X_upgrade2017_realistic_ForRECOGeometry which did not include this
> reco material xml file) and did not noticed any significant
> improvements. Given that we need to move forward with a new 2017
> scenario with GEM slice bug fixes, I'm reluctant to introduce this one
> to a GT without thorough testing.

Hi Yana,

Is there a hypernews thread with a related discussion?
Please let me know.
Thank you.

Earlier comments from Marco in this thread here were suggestive that the
RECO geometry update is needed.

**Comment by ianna** [comment]
@rovere - please, test against 92X_upgrade2017_realistic_Candidate_2017_06_21_08_28_33 GT and confirm if there is any improvement in reco with respect to the default 92x GT.

**Comment by ianna** [comment]
@rovere - I will close this one, if the following PR is fully signed: https://github.com/cms-sw/cmssw/pull/19390

**Comment by ianna** [comment]
hold

**Comment by ianna** [comment]
Validation with #19390 is approved by @rovere. The tags will go into the next GT cycle.

**Pull request closed without merging**
