### PR TITLE
Test for Simulation Packages Clang checks-all

### PR DESCRIPTION
**Pull request by ianna**
* Running scram b code-checks-all on a few core packages
* Correct by hand erroneous auto-correction
* Updating dependencies
* Second pass of code-checks-all

There are a few warnings left which have to be modified by hand, please see https://github.com/cms-sw/cmssw/issues/20510

Also there are a few unused variables reported - I did not correct these.

@civanch - FYI, the code and its dependencies compile fine. The purpose of this PR is to run full comparison.

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by civanch** [comment]
-1

**Comment by civanch** [comment]
@ianna , possible groups may be:
  1) SimG4Core/SensitiveDetector + SimG4CMS + SimRomanPot
  2) SimG4Core 
  3) SimGeneral
  4) SimMuon
  5) SimTracker
I would create PR for the next group after previous is merged.

**Comment by ianna** [comment]
@civanch - ok, I can split it.

**Comment by ianna** [comment]
hold

**Comment by ianna** [comment]
@civanch - there are a few packages left after the PR split:

 SimDataFormats/Associations
 SimDataFormats/CaloHit
 SimDataFormats/GeneratorProducts
 SimDataFormats/ValidationFormats
 SimFastTiming/FastTimingCommon

I can rebase this PR after all 5 steps are in an IB, or add these as a step 6

**Comment by davidlange6** [comment]
hi @ianna- @civanch convinced me to go in a few (not 8!) steps due to other pending PRs. We'll merge step 1 once the RHstop PR goes in (so later today).

**Pull request closed without merging**
