### PR TITLE
prevent empty histo in Offline DQM GUI

### PR DESCRIPTION
**Pull request by fioriNTU**

### CODE REVIEW

**Comment by deguio** [comment]
ciao @fioriNTU 
I see that this PR differs from the one submitted to 74. is this wanted?
I am referring in particular to the SiPixDigiSource

**Comment by fioriNTU** [comment]
I guess that could be some white space difference, the actual code should be exactly the same. Let me check.

**Comment by fioriNTU** [comment]
To me it looks exactly the same update, if you think it isn't please be more detailed

**Comment by danduggan** [comment]
@deguio The difference is just due to whitespace and removing empty lines. Otherwise it's the same.

**Comment by fioriNTU** [comment]
cool, I am going to submit it also in 7_6_X

**Comment by deguio** [comment]
ok.

**Comment by deguio** [comment]
+1

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
-1
updates needed. @danduggan

**Comment by davidlange6** [comment]
reopen when updated. Thanks

**Pull request closed without merging**
