### PR TITLE
Re-organize python configurations for the online DQM applications

### PR DESCRIPTION
**Pull request by dmitrijus**
Re-organizes the python configuration files for the online DQM:
- no longer in DQM/Integration/python/test, but in DQM/Integration/python/clients/
- configuration (includes) is separated and now exists in DQM/Integration/python/config/
- playback/production are no longer configured via patches, but rather via /etc/dqm_run_config:

```
[host]
type = playback
```

This is necessary and this PR also enables the DQM File Saver. The new file saver directly wires 
metadata files (used by the DQM GUI) and maintains a backup file (in case the application crashes).

### CODE REVIEW

**Comment by deguio** [comment]
hello David
this is the PR I was referring to yesterday at the ORP meeting.
it doesn't affect the offline world, but since moves files around and touch many of them, we would like to merge this asap.
the code has been tested at p5.

thanks in advance,
F.

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1

**Comment by deguio** [comment]
+1

**Comment by deguio** [comment]
please test

**Comment by davidlange6** [comment]
@dmitrijus - please make a 75x version of this PR

**Comment by dmitrijus** [comment]
Hi David,

I've made PR to both 75 and 76x.

Turns out I forgot to forward port a very old PR (https://github.com/cms-sw/cmssw/pull/9332/),
so these PR's include those changes as well.

Dmitrijus

**Comment by deguio** [comment]
ciao David,
can we have this one merged?
thanks,
F.

**Pull request merged**
