### PR TITLE
Remove StripCPEfromTemplate

### PR DESCRIPTION
**Pull request by pieterdavid**
As discussed in https://github.com/cms-sw/cmssw/pull/22533#pullrequestreview-102575420 .
This removes the (unused) StripCPEfromTemplate option from the RecoLocalTracker/SiStripRecHitConverter package, and the related TrackClusterSplitter plugin from RecoLocalTracker/SubCollectionProducers.
I will add a link to this PR on the associated twiki pages to make sure people can find this back if it needs to be revived at some point.

CC: @mmusich @echabert @OlivierBondu @boudoul

### CODE REVIEW

**Comment by mmusich** [comment]
@pieterdavid thank you!

**Comment by boudoul** [comment]
speed of light ... ! Thanks!

**Comment by perrotta** [comment]
please test
(thank you Pieter)

**Comment by mmusich** [comment]
Dear all, 
on second thought it might have been a little too "drastic" to remove entirely the Strip templates code-base, as I see that there have in fact been active developments in this domain as late as fall 2014 [see this talk](https://indico.cern.ch/event/337178/contributions/785649/attachments/659962/907139/stripTemplate_dpg.pdf) which seemed at the time to be promising (not clear to me at this point why it was not further developed). 
@perrotta can this put on hold for the time being? I'd like first to get some feedback from JHU group which is the main author of these developments.

**Comment by perrotta** [comment]
@mmusich @pieterdavid : let remain this PR quiet  while waiting that you guys and the Tracker group reach a consensus about it. Please close it if you decide that it is not needed/wanted, or alternatively tell here that the review can proceed

**Comment by davidlange6** [comment]
Your PR is unmergeable. Please have a look and possibly rebase it.

**Comment by pieterdavid** [comment]
Thanks @davidlange6 , that was because https://github.com/cms-sw/cmssw/pull/22533 has been merged in the mean time. I rebased on CMSSW_10_1_X.

**Comment by perrotta** [comment]
@mmusich @pieterdavid : did you reach any agreement about whether to go ahead with this PR or just close it?

**Comment by perrotta** [comment]
@pieterdavid @mmusich @echabert @OlivierBondu @boudoul : any news?

**Comment by mmusich** [comment]
@perrotta apologies for the delay. I haven't had time yet to investigate the consequences of this removal.
In the meanwhile it would be interesting to see what happens if you trigger the tests. 
If having it in the RECO pending items disturbs you, you can -1 it for the time being, we'll come back to you later.
Thanks

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
Thank you @mmusich : not really a big trouble having it pending in the reco queue. But consider that we will keep pinging you from time to time to check if there are developments

**Comment by perrotta** [comment]
@mmusich @pieterdavid : any news? (Periodic check, just to make sure that you don't forget it...)

**Comment by mmusich** [comment]
Dear @perrotta 
I am quoting here M. Swartz (main contributor on this item): 

>  The benefits of the strip template reconstruction were found to be fairly small [~10% in resolution] and it would require some effort to keep all of the many planes/sensor types calibrated, so we did not pursue the CPE as an alternative to the production reconstruction algorithm.  The code can certainly be removed from the present/future releases.

therefore I think it is safe to proceed with the code review.

Please @pieterdavid, once this is done, please update the documentation at: 
https://twiki.cern.ch/twiki/bin/view/CMS/SiStripLocalReconstructionPage#StripCPEfromTemplate
Thanks for the patience.

**Comment by perrotta** [comment]
please test
(thank you @mmusich ; relaunching the tests, whose results disappeared since we ran them last)

**Comment by perrotta** [comment]
+1
- Removal of unused  SiStripCPE Template code and references to it
- Jenkins tests pass and show no effect on reco outputs

**Comment by fabiocos** [comment]
+1

I understand that the final decision to remove the code has been confirmed and taken, and therefore it is safe to integrate this PR, and no effect has to be expected

**Pull request merged**
