### PR TITLE
Make the beam spot configuration of the Phase-2 HLT menu more consistent

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Make the beam spot configuration of the Phase-2 HLT menu more consistent.

Currently, part of the modules use the `offlineBeamSpotProducer`, and part use the `hltOnlineBeamSpotProducer`.
Moreover it is not clear if the `hltOnlineBeamSpotProducer` is working correctly in the Phase-2 configuration.

These changes:
  - remove the `hltScalersRawToDigi` and `hltOnlineBeamSpotProducer` modules;
  - rename the `offlineBeamSpotProducer` module to `hltOnlineBeamSpotProducer`;
  - replace explicit instances of the `hltOnlineBeamSpotProducer` with the `HLTBeamSpotTask`;
  - update all modules to use the `hltOnlineBeamSpotProducer` as input.

#### PR validation:

`runTheMAtrix.py -l 20834.76` runs.

Note that this PR builds on top, and so includes, https://github.com/cms-sw/cmssw/pull/40912 .

### CODE REVIEW

**Comment by fwyzard** [comment]
please test

**Comment by beaucero** [comment]
It has been discussed at the HLT Upgrade meeting and it is agreed to get in

**Comment by missirol** [comment]
(The first 3 of the 4 commits are already in `master` due to https://github.com/cms-sw/cmssw/pull/40912. GitHub still shows 4 commits in this PR, but I guess this only a feature of the webpage. A possible workaround is discussed [here](https://github.com/orgs/community/discussions/39031), but I think this PR can be merged regardless.)

**Comment by fwyzard** [comment]
I forced github to re-evaluate the merge, now it shows a single commit.

**Comment by rappoccio** [comment]
+1

**Pull request merged**
