### PR TITLE
Lock access to lumi::service::DBService

### PR DESCRIPTION
**Pull request by Dr15Jones**
Use a guard class to serialize access to the underlying coral
implementation of lumi::service::DBService

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by davidlange6** [comment]
Hi @Dr15Jones @slava77 - this code is obsolete, no?

**Comment by Dr15Jones** [comment]
@davidlange6 since it was in the repository and modules call it, I made the necessary changes.

**Comment by slava77** [comment]
On 4/13/17 8:14 AM, David Lange wrote:
> Hi @Dr15Jones <https://github.com/Dr15Jones> @slava77
> <https://github.com/slava77> - this code is obsolete, no?

it still runs

it may be worth to remove it all from standard processing sequences.

**Comment by slava77** [comment]
@cmsbuild please test

to get cleaner comparisons

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/18342	04203e5
- technical changes, as described
- jenkins tests pass and comparisons with baseline show no relevant differences

**Comment by davidlange6** [comment]
+1
but yes it seems like this is not a functionality likely to be restored...

**Pull request merged**
