### PR TITLE
fakeEmtfParams name update

### PR DESCRIPTION
**Pull request by gekobs**
#### PR description:

Updating the import of fake Emtf params as [PR#29767](https://github.com/cms-sw/cmssw/pull/29767) updates the module `fakeEmtfParams_cff.py` to `fakeEmtfParams_empty_cff.py` .
This can be considered as a follow up of [PR#29767](https://github.com/cms-sw/cmssw/pull/29767).

### CODE REVIEW

**Comment by silviodonato** [comment]
please test

**Comment by silviodonato** [comment]
urgent

**Comment by jiafulow** [comment]
@gekobs  Thanks for identifying the bug and fixing it. I'm sorry I didn't realize that the `fakeEmtfParams_cff.py` file was used in the L1 O2O. It was renamed to `fakeEmtfParams_empty_cff.py`, which caused this bug. The reason I renamed it was to distinguish it from the rest of the `fakeEmtfParams_*_cff.py` files that were added/modified in the particular PR.

The proposed fix looks good to me. If somehow there are more issues due to this file, it can also be simply reverted back to `fakeEmtfParams_cff.py`.

**Comment by gekobs** [comment]
> @gekobs Thanks for identifying the bug and fixing it. I'm sorry I didn't realize that the `fakeEmtfParams_cff.py` file was used in the L1 O2O. It was renamed to `fakeEmtfParams_empty_cff.py`, which caused this bug. The reason I renamed it was to distinguish it from the rest of the `fakeEmtfParams_*_cff.py` files that were added/modified in the particular PR.
> 
> The proposed fix looks good to me. If somehow there are more issues due to this file, it can also be simply reverted back to `fakeEmtfParams_cff.py`.

Thanks for reviewing this. It was actually @hjkwon260 spotting this therefore shout to her

**Comment by silviodonato** [comment]
merge

**Pull request merged**
