### PR TITLE
Geometry xm lparser

### PR DESCRIPTION
**Pull request by lpernie**
Updating the treatment of APEs in:
Alignment/MuonAlignment/python/geometryXMLparser.py

### CODE REVIEW

**Comment by ghellwig** [comment]
please test

**Comment by ghellwig** [comment]
+1

**Comment by lpernie** [comment]
Hi @ghellwig , 
this PR will be active in 91X right? Should I do a PR also in 901 for back porting?
Thanks.

**Comment by ghellwig** [comment]
@lpernie you can make a PR in 90X, of course
Since, it's rather trivial we might get it in for the next release. Not sure, if there will be another 90X release beyond 901, though.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
