### PR TITLE
FastSim : muon validation : use fastsim era to define fastsim customs

### PR DESCRIPTION
**Pull request by lveldere**
This migration was discussed and agreed upon in this meeting:
See https://indico.cern.ch/event/442060/
(FastSim Validation Update)

E.g. migration for tracking validation has been done earlier #10922

For now this pr serves as a discussion forum.
I will contact muon validators for feedback, and help with tests.

### CODE REVIEW

**Comment by lveldere** [comment]
please test

**Comment by lveldere** [comment]
closing until discussion with muon people is done

**Comment by lveldere** [comment]
please test

**Comment by lveldere** [comment]
+1

comparisons ok,
muon validators have made a comparison with large statistics (1000 events), before vs after for fastsim ttbar, and found no discrepancies.

**Comment by civanch** [comment]
+1

**Comment by deguio** [comment]
+1

**Pull request merged**
