### PR TITLE
bsunanda:Run2-TB14  Add extra material for FNAL test beam setup

### PR DESCRIPTION
**Pull request by bsunanda**
Needed to understand energy resolution discrepancy

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@ianna @civanch Kindly review and approve this

**Comment by ianna** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
