### PR TITLE
Remove hardcoded number (255) about the L1 prefiring

### LINKED ISSUE #26494: Improve access to GlobalExtBlk information
This issue is meant to keep track of the residual comments made by @peruzzim and myself to @apana about #26461 . I did not want to hold the test of this code, but it should be possibly improved for next future.

### PR DESCRIPTION
**Pull request by silviodonato**
#### PR description:

Resolves: #26494 (@apana @rekovic @peruzzim )
@fabiocos whenever we will change constant in `GlobalExtBlk::maxExternalConditions` in the future, we should be able to recover the old constant by the class versioning of the data format. Is it correct?

FYI. `GlobalExtBlk::maxExternalConditions` is defined here https://github.com/cms-sw/cmssw/blob/master/DataFormats/L1TGlobal/interface/GlobalExtBlk.h

#### PR validation:

`runTheMatrix.py -l 136.8523,136.874 -i all --ibeos`

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

No backport needed

### CODE REVIEW

**Comment by mariadalfonso** [comment]
please test

**Comment by fabiocos** [comment]
@silviodonato in my understanding the data versioning of schema evolution takes care of changes of interfaces (see https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideCreatingNewProducts#Class_versioning ), not of the change of the value of defined constants, @makortel may correct me in case. 

In any case any change in the DataFormat constant should be accompanied by all the possible updates where relevant. The key point of the comment was to avoid redefining constant values in multiple places in an uncorrelated way.

**Comment by silviodonato** [comment]
> @silviodonato in my understanding the data versioning of schema evolution takes care of changes of interfaces (see https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideCreatingNewProducts#Class_versioning ), not of the change of the value of defined constants, @makortel may correct me in case.
> 
> In any case any change in the DataFormat constant should be accompanied by all the possible updates where relevant. The key point of the comment was to avoid redefining constant values in multiple places in an uncorrelated way.

Right `GlobalExtBlk::maxExternalConditions` is a public data member, so this piece of information is included directly in the objects of the class `GlobalExtBlk`

**Comment by fabiocos** [comment]
@silviodonato I read  _incrementing the version number if and when a persistent non-static data member of the class is added, removed, renamed, or has its type changed._ Changing a value to ```GlobalExtBlk::maxExternalConditions``` does not seem to fall in any of these conditions.

**Comment by cecilecaillol** [comment]
+l1

**Comment by makortel** [comment]
> > @silviodonato in my understanding the data versioning of schema evolution takes care of changes of interfaces (see https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideCreatingNewProducts#Class_versioning ), not of the change of the value of defined constants, @makortel may correct me in case.
> > In any case any change in the DataFormat constant should be accompanied by all the possible updates where relevant. The key point of the comment was to avoid redefining constant values in multiple places in an uncorrelated way.
> 
> Right `GlobalExtBlk::maxExternalConditions` is a public data member, so this piece of information is included directly in the objects of the class `GlobalExtBlk`

I'm a bit confused (because of not using much time to understand) of the issue, but `GlobalExtBlk::maxExternalConditions` is a class-static variable that can have exactly one global value in a program. There is no way schema evolution could provide values for "old objects" because the variable is not stored within the objects.

**Comment by silviodonato** [comment]
Thanks @fabiocos @makortel for the clarification. My previous comment was wrong.

So far we has always had  `maxExternalConditions = 256;`. If in the future (eg. Phase2) this parameter will need to change, we can replace everywhere in CMSSW `maxExternalConditions` with a non-static variable that is equal to `256` for data produced with old releases and to new value for the future.

**Comment by mariadalfonso** [comment]
+xpog

removed hardcoded conditions with a global variable; no changes to the performances.

**Comment by silviodonato** [comment]
+1

> The workflows 140.53 have different files in step1_dasquery.log than the ones found in the baseline. You may want to check and retrigger the tests if necessary. You can check it in the "files" directory in the results of the comparisons

**Pull request merged**
