### PR TITLE
Hlt tau validation update75x

### PR DESCRIPTION
**Pull request by slehti**
Same as PR #9928 +bugfix, now for 75X

### CODE REVIEW

**Comment by deguio** [comment]
ciao @slehti 
please re-submit this PR including the fix to 76 first. once we test there we can merge to 75 and 74 as well (the last one still has to be submitted from what I see)

thanks,
F.

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
please fix 76 first: #10263
then this one can be considered again.

if you want this one in 74 as well please consider submitting there.
ciao,
F.

**Comment by deguio** [comment]
+1
this is now including the fix to avoid crashes with WF 1311
let's try again (just approved for 76. let's see how it goes there first).

**Comment by davidlange6** [comment]
+1

**Comment by perrotta** [comment]
Hi @slehti 
I can't find copy of this PR submitted in 74X: could you please link it in this comment field, for reference? (Or alternatively: please prepare it, as @deguio already asked you since one month).
Thank you,
Andrea

@mbluj

**Comment by slehti** [comment]
PR submitted for 74X: PR #10191

**Pull request merged**
