### PR TITLE
[12.2.X] Introduce alignment campaign-like unit test for `pede`

### PR DESCRIPTION
**Pull request by mmusich**
backport of https://github.com/cms-sw/cmssw/pull/37211

#### PR description:

As discussed here https://github.com/cms-sw/cmsdist/pull/7660#issuecomment-1059375497 introduce a pede execution based off a real (small-scale) MC alignment campaign (cosmics-only). The needed input files to steer the execution are at: `/store/group/alca_global/tkal_millepede_tests/`

#### PR validation:

run `scram b runtests_testPedeCampaign`.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

backport of https://github.com/cms-sw/cmssw/pull/37211

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by tvami** [comment]
Wouldnt we need the backport of https://github.com/cms-sw/cmsdist/pull/7685 in 12_2_X as well?

**Comment by mmusich** [comment]
> Wouldnt we need the backport of https://github.com/cms-sw/cmsdist/pull/7685 in 12_2_X as well?

No, the unit test runs, meaning that the `pede` version used in 12_2_X is fine.

**Comment by qliphy** [comment]
+1

**Comment by perrotta** [comment]
@mmusich , since the merging of this PR in 12_2 we are getting in the IB and PR tests the following error in the testCalibrationTkAlCaRecoProducers unit test
```
----- Begin Fatal Exception 25-Mar-2022 05:18:35 CET-----------------------
An exception of category 'LogicError' occurred while
   [0] Processing end ProcessBlock
   [1] Calling method for module AlignmentProducerAsAnalyzer/'SiPixelAliPedeAlignmentProducer'
Exception Message:
@SUB=MillePedeFileReader::getStringFromHLS
Found an alignable structure not possible to map in the default AlignPCLThresholds partitions
----- End Fatal Exception -------------------------------------------------
```

I can't understand how it could be related, But the fact that MillePede is involved, and the time sequence with the merging of this PR makes me suspect it can have some correlation with it.

**Comment by mmusich** [comment]
@perrotta it is not related. I think a possible fix is at: https://github.com/cms-sw/cmsdist/pull/7718.

**Pull request merged**
