### PR TITLE
Add warning to add DD4hep in GeometryConf

### PR DESCRIPTION
**Pull request by srimanob**
#### PR description:
Update warning to add DD4hep in `Configuration/StandardSequences/python/GeometryConf.py`

#### PR validation:
Fake D92, then try the new script.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:
Not a backport and no need of backport.

### CODE REVIEW

**Comment by srimanob** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

Technical PR to update a warning when new geometries are created. No changes in any workflow are expected.

**Comment by qliphy** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
