### PR TITLE
Extend StallMonitor to trace Run and Lumis

### PR DESCRIPTION
**Pull request by Dr15Jones**
Extended the StallMonitor Service to record module running during Run and LuminosityBlocks.
The global transitions are assigned a stream id equal to the number of streams.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by Dr15Jones** [comment]
-1
The stall measurement is messed up.

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by fabiocos** [comment]
@Dr15Jones yes, I have seen it in the IB

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
please test

**Pull request merged**
