### PR TITLE
Explicitly copy scripts which should end up in cmssw/bin directory

### PR DESCRIPTION
**Pull request by smuzaffar**
As new Build rules only copy scripts with execution permission , so explicitly copy some extrra scripts (perl Module, python lib and config files) which are needed by unit tests

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by fabiocos** [comment]
@smuzaffar ```XML2Python.py``` looks duplicated between ```Utilities/ReleaseScripts``` and ```FWCore/PythonUtilities```, although the two files are not strictly the same

**Comment by smuzaffar** [comment]
@fabiocos , XML2Python.py is in three places 
- PhysicsTools/PythonAnalysis/python/XML2Python.py
- FWCore/PythonUtilities/python/XML2Python.py
- Utilities/ReleaseScripts/scripts/XML2Python.py
only the one from Utilities/ReleaseScripts ends up in cmssw/bin directory. Other two are in PYTHONPATH (i.e. cmssw/python directory).

**Comment by smuzaffar** [comment]
+core
@fabiocos , can we get this in next IB. This is needed sot that we can get new build rules ( cms-sw/cmsdist#5367 ) in DEVEL IBs

**Comment by fabiocos** [comment]
@smuzaffar concerning https://github.com/cms-sw/cmssw/pull/28434#issuecomment-556949099 I wonder whether it makes sense to have multiple variants of the same utility in different places (as I happened to look at FWCore/PythonUtilities for #28439 )

**Comment by fabiocos** [comment]
+1

@christopheralanwest @tlampen this looks technical, please check anyway

**Comment by fabiocos** [comment]
merge

**Comment by christopheralanwest** [comment]
+1

**Pull request merged**
