### PR TITLE
Add bit wise unity initialization for default LUT arrays

### PR DESCRIPTION
**Pull request by aloeliger**
### PR description:

(Potentially) fixes the other maybe-uninitialized warning present in https://github.com/cms-sw/cmssw/issues/41794. This update initializes the default LUT arrays to a null value, then fills each with a bit-wise unity. I need to double check that this solution is acceptable to the calorimeter trigger experts, so it may get changed later.

@iarspider this should hopefully fix the remaining warnings in `L1TCaloLayer1`.

### PR validation:

All code compiles, passes the code checks, and has had code formatting applied. Because this is slightly more than a trivial technical fix, I have also tested that `runTheMatrix` workflows run without obvious complaint

### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

This PR is not a backport

### CODE REVIEW

**Comment by aloeliger** [comment]
I thought I did the format anyways...

**Comment by iarspider** [comment]
please test for CMSSW_13_3_CPP20_X
let's see if the warnings are gone

**Comment by iarspider** [comment]
Warnings [are gone](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-67a332/33932/build-logs/L1Trigger/L1TCaloLayer1/log.html), and test/relval failures are expected.

**Comment by aloeliger** [comment]
CaloL1 experts are reviewing whether they want an exception here instead of a default value in the case of no LUT loaded.

**Comment by aloeliger** [comment]
+l1

- Calo experts have signed off on this solution as okay for now.

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
please test

I don't know what the following string, that appears in the logs of the bot tests, actually means
```
2023-08-04 18:35:27.719891: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
```

Let try testing once again, and see if the quite several differences in outputs (that shouldn't be expected, in my opinion) somehow disappear

**Comment by perrotta** [comment]
+1

**Pull request merged**
