### PR TITLE
Miscellaneous fixes for TRK POG Data/MC validation tool

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

Few miscellaneous fixes for the TRK POG data/MC validation tool:
   * 6ca6c2605f222246f45ae425622a24c221a8dedf: fix MC KShort analysis sequence
   * 5e9ff21cc6ab88c52ef3d37bd3f8cf95c65035c1: fix sign of 3D pointing angle variable, make code slightly more readable 
   * e5a0fb2ecf740ec3635f13e1991930914640d5a1: fix axis limits for the `trackPhiH` ME to avoid using dynamic range which causes histogram merging issues

These were spotted by operating the data/MC validation tool on 2024 data.

#### PR validation:

`cmssw` compiles

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Not a backport, will be backported to CMSSW_14_0_X for 2024 data-taking purposes.

Cc: @dbruschi

### CODE REVIEW

**Comment by mmusich** [comment]
type bug-fix

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by tjavaid** [comment]
+1

**Comment by rappoccio** [comment]
+1

**Pull request merged**
