### PR TITLE
[JME NanoAOD] Backport of #32722 (Changes for event size reduction) to 11_2_X

### PR DESCRIPTION
**Pull request by nurfikri89**
Backport from #32722

#### PR description:

This PR is to reduce the size of custom JME NanoAODs. The following changes are made:
- Check that `npuProd[ibx].getPU_pT_hats()` size is more than 0 in `PhysicsTools/NanoAOD/plugins/NPUTablesProducer.cc`.
- Switch on storing Parton Shower (PS) weights.
- b-tagging algorithm outputs are saved for AK4 jets with pT > 15 GeV.
- Low-level input variables for PileUp jet ID and Quark-Gluon Likelihood are saved for AK4 jets with pT > 10 GeV.
- Remove AK4 PF and AK8 PF jet collections.
- Add separate AK8 GEN and AK8 Puppi jet collections for JEC studies. Minimal information are saved.
- For reclustered GEN jet collections, the minimum pT at the jet clustering level uses the default value (3 GeV) in `RecoJets/JetProducers/python/ak4GenJets_cfi.py`.
- For reclustered reco-level jet collections, the minimum pT at the jet clustering level is set to be 0. Then, only jets with (JEC-corrected) pT > 8 GeV are saved. Additionally for MC samples, jets with pT < 8 GeV are saved if they are matched to GEN jets.

With this PR, the event size is now reduced to **6.42 kb/event** from **9.32 kb/event**. The comparison was made using 10K events from a TTJets RunIISummer19UL17MiniAOD sample. The changes in this PR was discussed in the 13/01/2021 XPOG meeting [1]. 

[1] https://indico.cern.ch/event/978436/

#### if this PR is a backport please specify the original PR:

Original PR is #32722

### CODE REVIEW

**Comment by slava77** [comment]
please test workflow 25202.15,10224.15,11024.15

**Comment by slava77** [comment]
backport of #32722

**Comment by slava77** [comment]
please test workflow 25202.15,10224.15,11024.15

it looks like the last set of tests got stuck.
@smuzaffar @mrodozov please check what happened in case there is a problem in the test status detection
` cms/32760/slc7_amd64_gcc900/relvals Pending — Waiting for tests to start ` was in the status for at least the last 12 hours while tests in other PRs were running. And the "Details" link https://cmssdt.cern.ch/jenkins/job/ib-run-pr-tests/12583/ was showing completed results since a while before.

**Comment by smuzaffar** [comment]
@slava77 , I see that relval/input test was run here https://cmssdt.cern.ch/jenkins/job/ib-run-pr-relvals/701/  . The normal relval test should have been https://cmssdt.cern.ch/jenkins/job/ib-run-pr-relvals/702 but I do not see it in jenkins ( I guess it was accidentally killed/deleted).

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/32760	3d31ee2 
- the backport has the same diff in the code as #32722
- the modifications do not affect regular production setup, except for the special JME nanoAOD; so, this should be OK for a backport to 11_2_X
- jenkins tests pass without differences in the (monitored) results

**Comment by silviodonato** [comment]
@cms-sw/xpog-l2 any objections?

**Comment by gouskos** [comment]
+xpog

**Comment by silviodonato** [comment]
+1

**Pull request merged**
