### PR TITLE
Update L1TNuples to l1t-tsg-v5, and address memory management problems.

### PR DESCRIPTION
**Pull request by mulhearn**
This brings L1TNtuples up-to-date with l1t-tsg-v5.  It adds additional updates for memory management as requested by David.

This supersedes #14028.

The same branch can now be used for both 80x and 81x PRs.  Past experience has taught me that force pushing such a branch to the original PR 14028 will not work nicely as one would expect, and lots of people will get unnecessary e-mail.  So just making a new 81x PR.

### CODE REVIEW

**Comment by mulhearn** [comment]
please test

**Comment by mulhearn** [comment]
This passes our internal tests and does not change algorithm.

**Comment by mulhearn** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
