### PR TITLE
Add era mechanism for a new APV pulse shape for deco mode for Run 2

### PR DESCRIPTION
**Pull request by bourgatte**
Add a new APV pulse shape for deco mode for Run 2.
From last week, a talk on APV pulse shape and an other on Data/MC comparison:

[First talk](https://indico.cern.ch/event/787556/contributions/3278531/attachments/1779993/2895365/APVShape2.pdf)
[Second talk](https://indico.cern.ch/event/787556/contributions/3278532/attachments/1780024/2895436/Presentation_APVShape_160119.pdf)

The conclusion was that with the APV shape using the best simulation for a 320 micron sensor we had a better Data/MC comparison in low cluster charge and high cluster width compared to the default one.

So some changes are expected in the cluster charge, size and shape distributions, and also small 
differences in tracking distributions.

A check was made with 2016 data but the comparison is worse in 2016 than in 2018 by default. The disagreement is by far larger than the differences introduced by changing the APV shape. Also 2018 has the largest data set. That's why we can apply the new APV pulse shape for the whole Run 2.

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by pieterdavid** [comment]
From a first look, most differences are as expected: only the run2 MC workflows have differences, in the SiStrip digis (see [GlobalDigisV](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_10_5_X_2019-01-21-1100+25726/30136/10824.0_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2018_GenSimFull+DigiFull_2018+RecoFull_2018+HARVESTFull_2018+ALCAFull_2018+NanoFull_2018/GlobalDigisV.html)), and consequently there are differences in the [ADCs and cluster charges](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_10_5_X_2019-01-21-1100+25726/30136/10824.0_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2018_GenSimFull+DigiFull_2018+RecoFull_2018+HARVESTFull_2018+ALCAFull_2018+NanoFull_2018/SiStrip_MechanicalView_TOB_layer_1.html), and there are statistical differences in the strip hit resolution plots.
Some of the tracking differences (e.g. the fake rates [here](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_10_5_X_2019-01-21-1100+25726/30136/10824.0_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2018_GenSimFull+DigiFull_2018+RecoFull_2018+HARVESTFull_2018+ALCAFull_2018+NanoFull_2018/Tracking_Track_cutsRecoHp_trackingParticleRecoAsssociation.html)) look quite large, however... I do not know how much that should worry us (and whether we can tell from these tests). @mtosi @JanFSchulte could you provide some guidance? Thanks in advance!

**Comment by JanFSchulte** [comment]
@pieterdavid These changes seem only to affect the fake rate as a function of the dzpvcut, no other comparisons are flagged as failing. I am a bit puzzled as to which might happen, but I also don't think it's that big of an issue as otherwise everything else seems to be fine. Maybe @VinInn or @makortel have a bit more insight here.

**Comment by civanch** [comment]
+1

**Comment by pieterdavid** [comment]
Thanks @JanFSchulte and @makortel !

**Comment by fabiocos** [comment]
+1

**Pull request merged**
