### PR TITLE
[14_1] Remove unused L1TCaloSummary DQM sequences causing issues with HCAL.

### PR DESCRIPTION
**Pull request by aloeliger**
Backport of https://github.com/cms-sw/cmssw/pull/46482

### PR description:

Taken from original:

> This PR removes two unused sequences in the CICADA DQM that were potentially causing duplicate TPs seen in HCAL tests. No DQM changes are expected as a result of this change.
> 
> Also changes Calo Summary DQM configuration to use GT digis instead of test crate digis, which is more correct.

### PR validation:

Sequence has been confirmed to work in failing workflows without crashing. HCAL reports this fixes the issue.

### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

This backport is required for eventual backport to 14_0 for MC production with corrected DQM.

### CODE REVIEW

**Comment by aloeliger** [comment]
please test

**Comment by antoniovagnerini** [comment]
+dqm

**Comment by aloeliger** [comment]
+l1

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
