### PR TITLE
Phase1 for 84X

### PR DESCRIPTION
**Pull request by leggat**
PR https://github.com/cms-sw/cmssw/pull/17880 pack-ported to 84X

### CODE REVIEW

**Comment by leggat** [comment]
Hi @dmitrijus , can we please start the tests?

**Comment by boudoul** [comment]
hi @leggat , the 84X queue is closed - so this PR won't be considered -  Instead can you put it in 90X ? thanks

**Comment by leggat** [comment]
Ah okay sorry, I was told this was the place to put it - I will put it there instead.

**Comment by boudoul** [comment]
as the same time, it's highly recommended to make the same PR title as the one for the master , therefore for the 90X PR, please  put the tilte 'Pixel Phase 1 summary maps'  (you can also add [90x] in the tiltle if you want)  - Thanks.

**Comment by leggat** [comment]
Updated to 90X in https://github.com/cms-sw/cmssw/pull/18035

**Pull request closed without merging**
