### PR TITLE
[BuildFile] Added explicit dependencies

### PR DESCRIPTION
**Pull request by smuzaffar**
#### PR description:

- FWCore/MessageLogger: Added dependency on DataFormats/Provenance due to
```
  FWCore/MessageLogger/interface/JobReport.h:#include "DataFormats/Provenance/interface/RunLumiEventNumber.h"
```

- DataFormats/TrajectoryState: Added dependency on DataFormats/GeometryVector
```
  DataFormats/TrajectoryState/interface/LocalTrajectoryParameters.h:#include "DataFormats/GeometryVector/interface/LocalPoint.h"
  DataFormats/TrajectoryState/interface/LocalTrajectoryParameters.h:#include "DataFormats/GeometryVector/interface/LocalVector.h"
```

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/26775	668a2f7
- technical
- compilation is enough to signoff

**Comment by fabiocos** [comment]
+1

**Pull request merged**
