### PR TITLE
[Do not merge] Tesing bot squashed commits changes cms-sw/cms-bot#2144

### PR DESCRIPTION
**Pull request by smuzaffar**
Please ignore any comments from this PR. This is to test bot change https://github.com/cms-sw/cms-bot/pull/2144 for squashing PRs

### CODE REVIEW

**Comment by smuzaffar** [comment]
+core

just for testing

**Comment by smuzaffar** [comment]
ping

**Comment by smuzaffar** [comment]
please test for el8_aarch64_gcc12

**Comment by smuzaffar** [comment]
ping

**Comment by antoniovilela** [comment]
test

**Comment by antoniovilela** [comment]
please abort

**Pull request closed without merging**
