### PR TITLE
Handle ZDC in L1TriggerObjectsTxtWriter

### PR DESCRIPTION
**Pull request by JHiltbrand**
#### PR description:

Allow the `L1TriggerObjectsTxtWriter` to handle ZDC channels in addition to the usual HCAL channels.

ATTN: @abdoulline @hjbossi 

#### PR validation:

Performed a typical `./genLUT.sh` `dumpAll`-and-`generate` routine with GT `141X_dataRun3_HLT_v1` and obtained an `L1TriggerObjects.txt` file with ZDC channels and associated gains/pedestals included as expected.

I don't believe any validation workflows should be affected.

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by abdoulline** [comment]
> Seems like four tests failed to run in their entirety. Not sure about the return code...
> 
> ```
> 15:27:13 processing: ERROR executing  cd 2024.000001_RunJetMET02024D_10k; das-up-to-nevents.py -d /JetMET0/Run2024D-v1/RAW -e 10000 -pc > step1_dasquery.log  2>&1;  ret= 256
> 15:27:13 processing: ERROR executing  cd 2024.001001_RunZeroBias2024D_10k; das-up-to-nevents.py -d /ZeroBias/Run2024D-v1/RAW -e 10000 -pc > step1_dasquery.log  2>&1;  ret= 256
> 15:27:13 processing: ERROR executing  cd 2024.100001_RunJetMET02024C_10k; das-up-to-nevents.py -d /JetMET0/Run2024C-v1/RAW -e 10000 -pc > step1_dasquery.log  2>&1;  ret= 256
> 15:27:13 processing: ERROR executing  cd 2024.101001_RunZeroBias2024C_10k; das-up-to-nevents.py -d /ZeroBias/Run2024C-v1/RAW -e 10000 -pc > step1_dasquery.log  2>&1;  ret= 256
> ```

These must be DAS (samples files access) error...

**Comment by mandrenguyen** [comment]
ignore tests-rejected with ib-failure
Failures are clearly not related to PR

**Comment by perrotta** [comment]
+db

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
