### PR TITLE
[DD4hep] DDNamespace::name Issue #28949

### PR DESCRIPTION
**Pull request by ianna**
#### PR description:

  * Use ```DDNamespace::prepend(name)``` instead of ```DDNamespace::name()``` in all ```std::string``` operations. 
  * Remove unused ```std::string```s

Addresses issue #28949 and replaces PR #28933

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by mrodozov** [comment]
please test
oh well the cmssw pr can go in without the external anyway

**Comment by cvuosalo** [comment]
+1

**Comment by smuzaffar** [comment]
@kpedro88 and objection here? we need this one in so that we can go ahead with root updates (which are failing due to this change).

**Comment by kpedro88** [comment]
+upgrade

**Comment by silviodonato** [comment]
+1

**Comment by ianna** [comment]
There must have been some other recent PRs merged which require similar update.

**Comment by ianna** [comment]
Please, use #28985 which fixes the issue

**Pull request merged**
