### PR TITLE
Fireworks 10_0: disable tree cache prefetching by default

### PR DESCRIPTION
**Pull request by alja**
* added prefetching control / commandline option
* disable tree cache prefetching by default, waiting to resolve bug https://sft.its.cern.ch/jira/browse/ROOT-9282

### CODE REVIEW

**Comment by alja** [comment]
with the tree cache bug, firewoks can unpredictably crash. 
reported invalid read with valgrind

==121006== Thread 2:
==121006== Invalid read of size 8
==121006==    at 0x7B5C6AD: TFile::ReadBuffers(char*, long long*, int*, int) (in /cmssw/slc6_amd64_gcc630/lcg/root/6.10.09-mmelna2/lib/libRIO.so)
==121006==    by 0x7B78E8D: TFilePrefetch::ReadAsync(TFPBlock*, bool&) (in /cmssw/slc6_amd64_gcc630/lcg/root/6.10.09-mmelna2/lib/libRIO.so)
==121006==    by 0x7B7940D: TFilePrefetch::ReadListOfBlocks() (in /cmssw/slc6_amd64_gcc630/lcg/root/6.10.09-mmelna2/lib/libRIO.so)
==121006==    by 0x7B7946F: TFilePrefetch::ThreadProc(void*) (in /cmssw/slc6_amd64_gcc630/lcg/root/6.10.09-mmelna2/lib/libRIO.so)
==121006==    by 0x78402D0: TThread::Function(void*) (in /cmssw/slc6_amd64_gcc630/lcg/root/6.10.09-mmelna2/lib/libThread.so)
==121006==    by 0x3DBC407AA0: start_thread (in /lib64/libpthread-2.12.so)
==121006==    by 0x3DBBCE8BCC: clone (in /lib64/libc-2.12.so)
==121006==  Address 0x12cf67a8 is 0 bytes after a block of size 40 alloc'd
==121006==    at 0x4808929: operator new[](unsigned long) (in /cmssw/slc6_amd64_gcc630/external/valgrind/3.13.0/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==121006==    by 0x7B5B7E9: TFPBlock::TFPBlock(long long*, int*, int) (in /cmssw/slc6_amd64_gcc630/lcg/root/6.10.09-mmelna2/lib/libRIO.so)
==121006==    by 0x7B77C0F: TFilePrefetch::CreateBlockObj(long long*, int*, int) (in /cmssw/slc6_amd64_gcc630/lcg/root/6.10.09-mmelna2/lib/libRIO.so)
==121006==    by 0x7B77C48: TFilePrefetch::ReadBlock(long long*, int*, int) (in /cmssw/slc6_amd64_gcc630/lcg/root/6.10.09-mmelna2/lib/libRIO.so)
==121006==    by 0x7B714E7: TFileCacheRead::ReadBufferExtPrefetch(char*, long long, int, int&) (in /cmssw/slc6_amd64_gcc630/lcg/root/6.10.09-mmelna2/lib/libRIO.so)
==121006==    by 0x7B70688: TFileCacheRead::ReadBuffer(char*, long long, int) (in /cmssw/slc6_amd64_gcc630/lcg/root/6.10.09-mmelna2/lib/libRIO.so)
==121006==    by 0x76FDC34: TTreeCache::ReadBufferPrefetch(char*, long long, int) (in /cmssw/slc6_amd64_gcc630/lcg/root/6.10.09-mmelna2/lib/libTree.so)
==121006==    by 0x769110F: TBasket::ReadBasketBuffers(long long, int, TFile*) (in /cmssw/slc6_amd64_gcc630/lcg/root/6.10.09-mmelna2/lib/libTree.so)
==121006==    by 0x769502F: TBranch::GetBasket(int) (in /cmssw/slc6_amd64_gcc630/lcg/root/6.10.09-mmelna2/lib/libTree.so)
==121006==    by 0x76955F2: TBranch::GetEntry(long long, int) (in /cmssw/slc6_amd64_gcc630/lcg/root/6.10.09-mmelna2/lib/libTree.so)
==121006==    by 0x76AD3E0: TBranchElement::GetEntry(long long, int) (in /cmssw/slc6_amd64_gcc630/lcg/root/6.10.09-mmelna2/lib/libTree.so)
==121006==    by 0x5B5A60B: fwlite::Event::updateAux(long) const (in /cmssw/slc6_amd64_gcc630/cms/cmssw/CMSSW_10_0_2/lib/slc6_amd64_gcc630/libDataFormatsFWLite.so)
==121006==    by 0x5B5B56A: fwlite::Event::history() const (in /cmssw/slc6_amd64_gcc630/cms/cmssw/CMSSW_10_0_2/lib/slc6_amd64_gcc630/libDataFormatsFWLite.so)
==121006==    by 0x5B5D247: fwlite::Event::getProcessHistory() const (in /cmssw/slc6_amd64_gcc630/cms/cmssw/CMSSW_10_0_2/lib/slc6_amd64_gcc630/libDataFormatsFWLite.so)
==121006==    by 0x4D2C92A: FWLiteJobMetadataManager::doUpdate(FWJobMetadataUpdateRequest*) (in /cmssw/slc6_amd64_gcc630/cms/cmssw/CMSSW_10_0_2/lib/slc6_amd64_gcc630/libFireworksCore.so)
==121006==    by 0x4D0FC59: FWJobMetadataManager::update(FWJobMetadataUpdateRequest*) (in /cmssw/slc6_amd64_gcc630/cms/cmssw/CMSSW_10_0_2/lib/slc6_amd64_gcc630/libFireworksCore.so)
==121006==    by 0x4D76CAC: CmsShowNavigator::setCurrentFile(CmsShowNavigator::FileQueue_t::iterator) (in /cmssw/slc6_amd64_gcc630/cms/cmssw/CMSSW_10_0_2/lib/slc6_amd64_gcc630/libFireworksCore.so)
==121006==    by 0x4D79B60: CmsShowNavigator::appendFile(std::string const&, bool, bool) (in /cmssw/slc6_amd64_gcc630/cms/cmssw/CMSSW_10_0_2/lib/slc6_amd64_gcc630/libFireworksCore.so)
==121006==    by 0x4CC5DEA: CmsShowMain::setupDataHandling() (in /cmssw/slc6_amd64_gcc630/cms/cmssw/CMSSW_10_0_2/lib/slc6_amd64_gcc630/libFireworksCore.so)
==121006==    by 0x4DA564E: CmsShowTaskExecutor::doNextTaskImp() (in /cmssw/slc6_amd64_gcc630/cms/cmssw/CMSSW_10_0_2/lib/slc6_amd64_gcc630/libFireworksCore.so)
==121006==    by 0x4CA2B94: CmsShowTaskExecutorBase::doNextTask() (in /cmssw/slc6_amd64_gcc630/cms/cmssw/CMSSW_10_0_2/lib/slc6_amd64_gcc630/libFireworksCore.so)
==121006==    by 0x4DB325C: CmsShowTaskTimer::Notify() (in /cmssw/slc6_amd64_gcc630/cms/cmssw/CMSSW_10_0_2/lib/slc6_amd64_gcc630/libFireworksCore.so)
==121006==    by 0x7FE80D0: TTimer::CheckTimer(TTime const&) (in /cmssw/slc6_amd64_gcc630/lcg/root/6.10.09-mmelna2/lib/libCore.so)
==121006==    by 0x808FF28: TUnixSystem::DispatchTimers(bool) (in /cmssw/slc6_amd64_gcc630/lcg/root/6.10.09-mmelna2/lib/libCore.so)
==121006==    by 0x80909A2: TUnixSystem::DispatchOneEvent(bool) (in /cmssw/slc6_amd64_gcc630/lcg/root/6.10.09-mmelna2/lib/libCore.so)
==121006==    by 0x7FD7D73: TSystem::InnerLoop() (in /cmssw/slc6_amd64_gcc630/lcg/root/6.10.09-mmelna2/lib/libCore.so)
==121006==    by 0x7FD698E: TSystem::Run() (in /cmssw/slc6_amd64_gcc630/lcg/root/6.10.09-mmelna2/lib/libCore.so)
==121006==    by 0x7F7149E: TApplication::Run(bool) (in /cmssw/slc6_amd64_gcc630/lcg/root/6.10.09-mmelna2/lib/libCore.so)
==121006==    by 0x4030D5: run_app(TApplication&, int, char**) (in /cmssw/slc6_amd64_gcc630/cms/cmssw/CMSSW_10_0_2/bin/slc6_amd64_gcc630/cmsShow.exe)
==121006==    by 0x402B49: main (in /cmssw/slc6_amd64_gcc630/cms/cmssw/CMSSW_10_0_2/bin/slc6_amd64_gcc630/cmsShow.exe)

**Comment by Dr15Jones** [comment]
@pcanal FYI

**Comment by Dr15Jones** [comment]
@bbockelm any ideas?

**Comment by pcanal** [comment]
Can you rerun valgrind with --track-origins=yes ?  thanks.

**Comment by osschar** [comment]
Note, the title is wrong, this doesn't disable TTreeCache, just prefetching. And a command-line option is added to allow a user to enable it.

**Comment by alja** [comment]
@pcanal 
Here is the valgrind log: http://xrd-cache-1.t2.ucsd.edu/alja/valgrind.log.pcanal2
@osschar made the change in Fireworks source.

**Comment by alja** [comment]
+1

**Comment by pcanal** [comment]
@alja Would it be possible to rerun valgrind with a debug build of ROOT and with the supression file (--suppresions=$ROOTSYS/etc/valgrind-root.supp) ?

thanks.

**Comment by alja** [comment]
@pcanal I have to build root debug for cmssw. Will do that within a day or two.

**Comment by fabiocos** [comment]
@pcanal @alja I assume that the request to rerun valgrind is for further debugging, which might be better discussed in a separate issue, and this PR should be integrated anyway as a temporary workaround, right?

**Comment by alja** [comment]
@pcanal Yes, this is a temporary workaround.

**Comment by alja** [comment]
@fabiocos @pcanal 
I made new issue  #22516
There I put there a  new valgrind report with root debug.

**Comment by fabiocos** [comment]
@alja ok thanks

**Comment by fabiocos** [comment]
+1

**Pull request merged**
