### PR TITLE
Remove trackingPhase1PU70 customizations as obsolete

### PR DESCRIPTION
**Pull request by makortel**
This PR (finally!) cleans up the long-obsolete trackingPhase1PU70 era customizations. In addition I did further cleanup in the iterative tracking configurations, most notably made the `trackingPhase1` parameters the defaults in `LowPtQuadStep`, `DetachedQuadStep`, and `HighPtTripletStep`.

Tested in 9_1_0_pre2, no changes expected.

@rovere @VinInn @ebrondol

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
Found a problem in sequence definitions, will push a fix after local tests finish.

(didn't catch earlier because of matrix tests being unscheduled, and apparently the addOnTests reco jobs are run in scheduled mode)

**Comment by makortel** [comment]
@cmsbuild, please test

That should fix the sequences.

**Comment by VinInn** [comment]
ping, essentially no work on tracker related config is possible till this PR is merged

**Comment by perrotta** [comment]
+1
- trackingPhase1PU70 customizations removed; trackingPhase1 parameters set as defaults in LowPtQuadStep, DetachedQuadStep, and HighPtTripletStep
- No changes expected in std workflows: no changes observed in jenkins outputs, nor in some larger stat test run in order to check that there no issues sorted out when setting different defaults (there are so many places in which it was done that I did not want to trust only my attentiveness during the visual inspection...)

**Pull request merged**
