### PR TITLE
added esConsumes to modules in EventFilter/CTPPSRawToDigi

### PR DESCRIPTION
**Pull request by JamminJones**
#### PR description:

added esConsumes to 4 modules 
#### PR validation:

the code compiles

### CODE REVIEW

**Comment by Dr15Jones** [comment]
This change was done under my supervision.

**Comment by Dr15Jones** [comment]
please test

**Review by jpata — COMMENTED** [review]
The changes are minimal, technical and in line with the description. I see no issues from the reco point of view.

**Comment by jpata** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
