### PR TITLE
Remove pixel tracking from phase2

### PR DESCRIPTION
**Pull request by makortel**
This PR removes pixel tracking from phase2, adds firstStepPrimaryVertices, and replaces all uses of pixelVertices with firstStepPrimaryVertices as is done in phase0/phase1 tracking.

Here are MTV plots in 100 events of ttbar+200PU in 910pre3 D11
https://cms-tracking-validation.web.cern.ch/cms-tracking-validation/PR/CMSSW_9_1_0_pre3_PR19165/
Efficiency stays essentially the same (tiny variations), fake rate decreases by 2 % (1 % in highPurity)

Timing should improve. In my test in 910pre3
- in the release
  * iterative tracking takes ~56 s/event
  * pixel tracking + vertexing takes ~6 s/event (not included in above)
- with this PR
  * `firstStepPrimaryVertices` (part of initialStep) takes ~2 s/event

I have not tested the timing of the sorting of `firstStepPrimaryVertices` from #19051 in the context of phase2 PU200, but I'd expect it to be small compared to the rest of the tracking.

Tested in 9_1_0_pre3 and 9_2_2. Expecting changes in phase2 as described above, and no changes in phase0/1.

@rovere @VinInn @ebrondol

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by slava77** [comment]
20434 step3:
```
   [15] Calling method for module TrackClusterRemoverPhase2/'highPtTripletStepClusters'
Exception Message:
Principal::getByToken: Found zero products matching all criteria
Looking for type: edm::ValueMap<int>
Looking for module label: initialStepSelector
Looking for productInstanceName: initialStep
```

@makortel 
perhaps you  have missed some commits?

**Comment by makortel** [comment]
@cmsbuild, please test

Should be fixed now. My testing setup was apparently a bit flawed because at first (before submitting the PR) I didn't see the problem (but eventually I was able to reproduce).

**Comment by dmitrijus** [comment]
+1

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/19165	fc87228
- implemented as described; changes affect only 2023 workflows
- jenkins tests pass and comparisons with baseline show differences only in 2023 workflows and the only significant changes are the expected disappearance of the pixelTracks and pixelVertices
- local tests with higher stats muon guns and PU200 show expected behavior, to supplement the MTV plots provided in the PR description: changes on quantities downstream from early tracking steps are negligibly small. 
    - CPU is reduced by about 3% total (for full reco+miniAOD): essentially all change is in tracking modules where the pixel tracking removal (-10 s) is absorbed by some increase in iterative tracking (+2 s; mostly from pixelPairStep)
    - event content is reduced by the size of the pixelTracks and pixelVertices  (about 0.2 MB/event in the RECO file, which is a 0.6% reduction in this case).

**Comment by davidlange6** [comment]
merge

**Comment by kpedro88** [comment]
@slava77 please assign upgrade to future PRs like this one

**Comment by slava77** [comment]
@kpedro88 
sorry.
I'll try to remember (until the next time, I guess).

Maybe some rule can be written for the bot to do it automatically.
E.g. wget the diff and grep for various patterns of Phase2, Phase-2 or similar appearing there.
You can then unassign if it's unrelated.

**Comment by kpedro88** [comment]
I'll think about it, but it seems likely prone to false positives (and also would "secretly" break the default category-based assignment that's relatively easy for developers to follow).

**Comment by slava77** [comment]
On 6/21/17 2:30 PM, Kevin Pedro wrote:
> I'll think about it, but it seems likely prone to false positives (and
> also would "secretly" break the default category-based assignment that's
> relatively easy for developers to follow).

this PR had 3 reviewers before it was merged.
Nobody remembered to assign upgrade.
It's a sampling with not a very good yield, if you expect to get an
average close to 100%.

**Pull request merged**
