### PR TITLE
[HGCAL trigger] Update in geometry tester class

### PR DESCRIPTION
**Pull request by jbsauvan**
#### PR description:
Add wafer type (orientation and partial) information in the geometry ntuple produced by the geometry tester class.

Associated internal PRs and reviews:
- hgc-tpg#54

### CODE REVIEW

**Comment by aloeliger** [comment]
please test

**Comment by jbsauvan** [comment]
The failed tests seem unrelated to this PR

**Comment by aloeliger** [comment]
please test

**Comment by aloeliger** [comment]
+l1

**Comment by srimanob** [comment]
+Upgrade

Note that we still need a fix mentioned in https://github.com/cms-sw/cmssw/pull/43431#issuecomment-1838888613 (it is just show up also in the static check of this PR). Mention here to note.

**Comment by rappoccio** [comment]
+1

**Pull request merged**
