### PR TITLE
Remove unnecessary inclusions from  DataFormats/L1Trigger that would cause a recursive referencing of the BuildFiles

### PR DESCRIPTION
**Pull request by perrotta**
#### PR description:

Possibile fix for the issue reported in https://github.com/cms-sw/cmssw/pull/37287#issuecomment-1079647682

#### PR validation:

It builds

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
The correct fix was implemented by @smuzaffar in https://github.com/cms-sw/cmsdist/pull/7725

**Comment by perrotta** [comment]
reopen

**Comment by cecilecaillol** [comment]
+l1

**Pull request closed without merging**
