### PR TITLE
[10_6_X] Add ntracks associated to each SV

### PR DESCRIPTION
**Pull request by gouskos**
Backport of PR #31696

**Validation:**
produced a test sample in mc and data
increase in size/evt and time/evt: negligible [<0.01%]

### CODE REVIEW

**Comment by silviodonato** [comment]
@gouskos This PR have been updated with the last commit of #31696, is it correct?

**Comment by silviodonato** [comment]
please test

**Comment by gouskos** [comment]
> @gouskos This PR have been updated with the last commit of #31696, is it correct?

@silviodonato Yes!

**Comment by mariadalfonso** [comment]
+xpog

**Comment by santocch** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
