### PR TITLE
Revert "PUPPI MET in RECO"

### PR DESCRIPTION
**Pull request by silviodonato**
See https://github.com/cms-sw/cmssw/issues/29744
We are getting errors related to #29254 in many workflows.
In addition, the errors seems hardly reproducible, and then we risk to crash the relval production.
So I'm going to revert temporarly #29254 before the night IB in order to build CMSSW_11_1_0_pre7
https://cmssdt.cern.ch/SDT/html/cmssdt-ib/#/ib/CMSSW_11_1_X

### CODE REVIEW

**Comment by silviodonato** [comment]
please test

**Comment by silviodonato** [comment]
merge

**Comment by jfernan2** [comment]
+1 
For the records

**Comment by jfernan2** [comment]
+1
For the records

**Comment by vlimant** [comment]
what is going on @jfernan2 ?

**Pull request merged**
