### PR TITLE
avoiding Pixel templates usage in trackingRecoMaterialAnalyzer [91x] 

### PR DESCRIPTION
**Pull request by boudoul**
This PR intends to fix the crash oberved at Tier0 described in : 
https://hypernews.cern.ch/HyperNews/CMS/get/tier0-Ops/1577.html
90X PR is here : #18417

### CODE REVIEW

**Comment by boudoul** [comment]
@rovere FYI

**Comment by makortel** [comment]
@boudoul Is this really needed in 91X now that the pixel templates are used in tracking (#18271)? (so with similar GT already reco would fail)

**Comment by boudoul** [comment]
I was wondering the same , most likely it's not needed indeed for 91X , I created this PR as default policy  (PR in master and then in 90X)  , but I agree that this one is presumably not needed- I believe the urgency is first to fix 90X to release Tier0 prompt reco- Let's see how it goes with 90X and unless somebody has a different opninion I can close this one (for 91X)

**Comment by rovere** [comment]
Ciao, 
indeed I'd close the 91X PR.

**Comment by davidlange6** [comment]
so what happens the next time pixel templates are not used in tracking?

**Comment by rovere** [comment]
Ciao David,
I'd judge the usage of pixel templates in tracking a stable enough procedure since it has been in place for the past N years w/o any interruption.
Having said that, if you feel more relaxed we can get rid of pixel templates forever in this analyser that is only meant to monitor the material distribution inside the Tracker region. I'd prefer to have it enabled but would not object to having it disabled.

**Comment by davidlange6** [comment]
maybe we can at least protect against them not being there?

**Comment by makortel** [comment]
> so what happens the next time pixel templates are not used in tracking?

Maybe next time we need to disable the templates we should consider disabling them in `WithAngleAndTemplate` TransientTrackingRecHitBuilder instead of replacing all of those with `WithTrackAngle` (that we did in #18271 and its predecessors)? Minus side is that when interpreting `edmConfigDump` one needs one hop more to understand if templates are used or not.

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
i understand better now that this is just an inconsistency between the config of this module and the rest of CMSSW. indeed centralizing this parameter so that everyone is in sync could be beneficial...

but I think there is no need for this PR in 91x as templates are enabled

**Comment by boudoul** [comment]
ok thanks all , closing this one

**Pull request closed without merging**
