### PR TITLE
Remove inheritance in L1MuonPixelTrackFitter and L1MuonRegionProducer

### PR DESCRIPTION
**Pull request by makortel**
While refactoring `PixelTrackProducer`, it occurred to me that for regions and fitter `TSGFromL1Muon` uses only `L1MuonRegionProducer` and `L1MuonPixelTrackFitter` (with an explicit `dynamic_cast` in the code and without failure check). Furthermore, these two classes are used only by `TSGFromL1Muon`. Therefore, for current use cases, there is no need for `L1MuonRegionProducer` to inherit from `TrackingRegionProducer`, and `L1MuonPixelTrackFitter` from `PixelFitter`. This PR suggests to remove those inheritances to ease a bit further refactoring elsewhere.

Tested in CMSSW_8_1_0_pre16, no changes expected in results.

@rovere @VinInn

### CODE REVIEW

**Comment by VinInn** [comment]
@cmsbuild ,please test

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
+1

For #16492 4e912065a6961d5ca1e975d2cddb4164d3572c71

Code clean-up of unneeded inheritance in L1MuonPixelTrackFitter and L1MuonRegionProducer. There should be no change in monitored quantities.

The code changes are satisfactory, and Jenkins tests against baseline CMSSW_8_1_X_2016-11-08-1100 show no significant differences, as expected.

**Comment by slava77** [comment]
did the bot fall asleep?

**Comment by davidlange6** [comment]
+1

**Pull request merged**
