### PR TITLE
Update Run3 data, Run3 2024 MC, Run3 2024 ppRef5TeV GTs in autoCond - 14_1_X

### PR DESCRIPTION
**Pull request by perrotta**
#### PR description:

The following GTs are updated in autoCond:

- `run3_data` -> [140X_dataRun3_v14](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/140X_dataRun3_v14) (see the [diff wrt _v13](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/140X_dataRun3_v13/140X_dataRun3_v14))
  - Allow the 2024 payloads (IOV range 378983 to 383705) appended to the CTPPSRPAlignment tag, see https://cms-talk.web.cern.ch/t/call-for-conditions-re-reco-of-2024-eras-c-d-e/42331/14 
 
- `phase1_2024_realistic `-> [140X_mcRun3_2024_realistic_v25](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/140X_mcRun3_2024_realistic_v25) (see the [diff wrt _v24](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/140X_mcRun3_2024_realistic_v24/140X_mcRun3_2024_realistic_v25))
  - Include the DT and CSC alignments plus a set of GEM tags, see https://cms-talk.web.cern.ch/t/final-call-for-run3summer24-mc-conditions-in-140x/41226/15

- `phase1_2024_realistic_ppRef5TeV` ->[141X_mcRun3_2024_realistic_ppRef5TeV_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/141X_mcRun3_2024_realistic_ppRef5TeV_v4) (see the [diff wrt _v3](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/141X_mcRun3_2024_realistic_ppRef5TeV_v3/141X_mcRun3_2024_realistic_ppRef5TeV_v4))
  - Include the DT and CSC alignments plus a set of GEM tags, see https://cms-talk.web.cern.ch/t/final-call-for-run3summer24-mc-conditions-in-140x/41226/15 (i.e. synchronize with 140X_mcRun3_2024_realistic_v25, see [diff wrt 140X_mcRun3_2024_realistic_v25](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/141X_mcRun3_2024_realistic_ppRef5TeV_v4/140X_mcRun3_2024_realistic_v25))

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport of #46184

### CODE REVIEW

**Comment by perrotta** [comment]
backport of #46184

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
+alca

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
