### PR TITLE
CTPPS: strips update for 2017 data-taking

### PR DESCRIPTION
**Pull request by jan-kaspar**
This PR contains changes in the CT-PPS Si strip SW needed for the 2017 data-taking:
 * Updated list of FED ids: including both horizontal and vertical Roman Pots (RPs).
 * Updated cabling mapping.
 * Updated DQM for strips: plots are booked only for RPs containing strip sensors.

`runTheMatrix.py -l limited` was executed in `CMSSW_9_1_X_2017-04-07-1100` yielding
```
	16 16 15 13 7 1 1 1 tests passed, 1 0 0 0 0 0 0 0 failed
```
The failing test was 4.22 with Step0-DAS_ERROR, thus unrelated to this PR.

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by mommsen** [comment]
+1
The scattering of Totem FED ranges is not nice. But I guess there's nothing we can do about it now.

**Comment by ggovi** [comment]
+1

**Comment by dmitrijus** [comment]
+1

**Comment by perrotta** [comment]
Running your test RecoCTPPS/Configuration/test/raw_data_test.py as such, I get a large amount of errors like (e.g.):

Error in RawDataUnpacker::ProcessVFATDataParallel > Error flags not zero (1) at 578:3:11. Channel errors will be suppressed.
Error in RawDataUnpacker::ProcessVFATDataParallel > Error flags not zero (14) at 581:5:7. Channel errors will be suppressed.
Error in RawDataUnpacker::ProcessVFATDataParallel > Trailer size (208) does not match with words processed (2) at 581:5:7. This frame will be skipped.
Error in RawDataUnpacker::ProcessVFATDataParallel > Unknown header flag 1. Skipping this word.
Error in RawDataUnpacker::ProcessVFATDataParallel > Unknown header flag 1. Skipping this word.

(they are all kind of LogProblems in the code)

Could you please check/confirm that they are safe, and do not point to some potential issue with your code?

**Comment by slava77** [comment]
On 4/13/17 8:07 AM, perrotta wrote:
> Running your test RecoCTPPS/Configuration/test/raw_data_test.py as such,
> I get a large amount of errors like (e.g.):
> 
> Error in RawDataUnpacker::ProcessVFATDataParallel > Error flags not zero
> (1) at 578:3:11. Channel errors will be suppressed.
> Error in RawDataUnpacker::ProcessVFATDataParallel > Error flags not zero
> (14) at 581:5:7. Channel errors will be suppressed.
> Error in RawDataUnpacker::ProcessVFATDataParallel > Trailer size (208)
> does not match with words processed (2) at 581:5:7. This frame will be
> skipped.
> Error in RawDataUnpacker::ProcessVFATDataParallel > Unknown header flag
> 1. Skipping this word.
> Error in RawDataUnpacker::ProcessVFATDataParallel > Unknown header flag
> 1. Skipping this word.
> 
> (they are all kind of LogProblems in the code)

If it's printed in the default configuration
please change to LogError so that the full header appears assigned by
the framework to see which module complains and when

**Comment by jan-kaspar** [comment]
@perrotta, @slava77 This is a known effect and only occurs for data after TS2 in 2016 - that is only the second file in the test config. The reason were 3 faulty read-out chips (VFATs) sending non-sense data. There are new detectors in the RPs now, thus the problem should not be present in 2017 (unless some more chips go bananas). Since we ran with this code anyway throughout the end of 2016, do you think we can keep it like this? In case we need to touch the code, I'd consider what Andrea Rizzi wrote in October 2016:
> in general if you have error or broken hardware parts that could be
> there as part of normal operations, those should not be LogError or
> LogWarning. You may consider some dataformat to store error
> information instead. LogError is reserved for stuff that should not happen and if it
> happens (or happens above some rate) it may require immediate action.

A solution could be to modify the RawDataUnpacker
 * to have a verbosity flag, turned off by default, thus suppressing all the LogXXX output
 * to have a keep-only-correct-frames flag, by default on (this behaviour is almost there)

Then, RawDataUnpacker problems could be spotted in DQM:
  https://github.com/cms-sw/cmssw/blob/master/DQM/CTPPS/plugins/TotemRPDQMSource.cc#L271
since the RawToDigi module wouldn't find the corresponding data frame.

Obviously this solution requires some additional work... What do you think?

**Comment by slava77** [comment]
On 4/13/17 9:45 AM, jan-kaspar wrote:
> @perrotta <https://github.com/perrotta>, @slava77
> <https://github.com/slava77> This is a known effect and only occurs for
> data after TS2 in 2016 - that is only the second file in the test
> config. The reason were 3 faulty read-out chips (VFATs) sending
> non-sense data. There are new detectors in the RPs now, thus the problem
> should not be present in 2017 (unless some more chips go bananas). Since
> we ran with this code anyway throughout the end of 2016, do you think we
> can keep it like this? In case we need to touch the code, I'd consider
> what Andrea Rizzi wrote in October 2016:
> 
>     in general if you have error or broken hardware parts that could be
>     there as part of normal operations, those should not be LogError or
>     LogWarning. You may consider some dataformat to store error
>     information instead. LogError is reserved for stuff that should not
>     happen and if it
>     happens (or happens above some rate) it may require immediate action.

LogError and LogPrint are the same with respect to the text above
(both are the same ELwarning underneath; the difference is in formatting)
So, my comment stands.

**Comment by jan-kaspar** [comment]
@slava77 OK, so is replacement `LogPrint` to `LogError` sufficient for you?

**Comment by slava77** [comment]
On 4/13/17 1:21 PM, jan-kaspar wrote:
> @slava77 <https://github.com/slava77> OK, so is replacement |LogPrint|
> to |LogError| sufficient for you?

Yes.
Maybe LogWarning is more appropriate, especially for cases that you know
already are not real errors that invalidate all results of this algorith.

The problematic channel counter should still be developed
to replace the log messages.

**Comment by jan-kaspar** [comment]
> Maybe LogWarning is more appropriate, especially for cases that you know
> already are not real errors that invalidate all results of this algorith.

OK, I can switch to `LogWarning` - assuming that - as always in the history - the number of faulty chips is compensated by the redundancy in the detector and thus not harmful for proton reconstruction.

> The problematic channel counter should still be developed
> to replace the log messages.

I am not sure I understand what you mean by "problematic channel counter" - can you explain it a bit more?

**Comment by slava77** [comment]
On 4/13/17 1:42 PM, jan-kaspar wrote:
> I am not sure I understand what you mean by "problematic channel
> counter" - can you explain it a bit more?
> 


this is about "You may consider some dataformat to store error ... "
in https://github.com/cms-sw/cmssw/pull/18283#issuecomment-293956846

**Comment by jan-kaspar** [comment]
Summary of the last update
 * code in EventFilter/CTPPSRawToDigi uses formatted LogXXX methods, with default configuration no logging messages produced
 * RawDataUnpacker: frame is dropped if any consistency check fails; consequently corrupted frames appear as ''missing'' in DQM
 * resolved conflict with "master" branch

Test performed with https://github.com/CTPPS/cmssw/blob/0539d6c3060e0af5914184bfd61cd499a2d3ce58/DQM/CTPPS/test/strip_dqm_test_cfg.py running on 2016, post-TS2 data where the data corruption appeared. In particular in channels 578:3:11 and 581:5:7. According to the mapping 
https://github.com/CTPPS/cmssw/blob/0539d6c3060e0af5914184bfd61cd499a2d3ce58/CondFormats/CTPPSReadoutObjects/xml/mapping_tracking_strip_2016_from_fill_5330.xml, these channels correspond to VFATs located at 45-210-fr-hr, plane 2, vfat 3 and 45-210-nr-hr, plane 9, vfat 3. cmsRun produces no log messages and the DQM correctly reports two problematic channels:
45-210-fr-hr
45-210-nr-hr

@nminafra , @forthommel : these are the changes I told about earlier today. Please check this is OK for diamonds. Thanks!

**Comment by perrotta** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by perrotta** [comment]
+1
jenkins comparisons show no differences (as expected, since this is meant to the 2017 data taking)
Tests with their own config show things are not broken
With the latest commits also printouts got fixed

**Comment by perrotta** [comment]
hold
(while @nminafra , @forthommel answer the comment in https://github.com/cms-sw/cmssw/pull/18283#issuecomment-294911547 confirming that this is ok for diamonds)

**Comment by nminafra** [comment]
@perrotta Fine with us, however it require an additional configuration line that will be pushed by @jan-kaspar  in a moment.

**Comment by jan-kaspar** [comment]
> ... however it require an additional configuration line that will be pushed by @jan-kaspar in a moment.

Done.

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
unhold

**Comment by perrotta** [comment]
Please check L110 of EventFilter/CTPPSRawToDigi/src/RawToDigiConverter.cc

The line

if (verbosity > 0)

is not terminated. Therefore, the following instructions

if (testCRC == tfErr)
      {
        record.status.setCRCError();
        stopProcessing = true;
      }

are only executed if verbosity is larger than 0, which I don't think it is the wanted behavior.

Please check, and fix if needed

**Comment by perrotta** [comment]
@jan-kaspar : any news on the check I asked for in https://github.com/cms-sw/cmssw/pull/18283#issuecomment-296129695?

**Comment by jan-kaspar** [comment]
> @jan-kaspar : any news on the check I asked for in #18283 (comment)?

I'm just back from short vacations, I will check it in the hours to come.

**Comment by jan-kaspar** [comment]
@perrotta You are perfectly right. A line printing an error message was accidentally removed in an old commit:
https://github.com/CTPPS/cmssw/commit/0c38042ee3e4fcc11dee46153c6dc5f53f4f9859#diff-e01e0047604a3839bb019fa87ee6be52L109
It is now fixed in 6d46b3c. Many thanks for pointing this out.

Also to @slava77 - the same bug is in 8_0_X:
  https://github.com/cms-sw/cmssw/blob/CMSSW_8_0_X/EventFilter/CTPPSRawToDigi/src/RawToDigiConverter.cc#L111
and of course it would be better to fix it before the re-reco. Could we bundle this small change with the one we are discussing over the email?

**Comment by perrotta** [comment]
please test

**Comment by slava77** [comment]
On 4/25/17 4:58 AM, jan-kaspar wrote:
> @perrotta <https://github.com/perrotta> You are perfectly right. A line
> printing an error message was accidentally removed in an old commit:
> CTPPS@0c38042#diff-e01e0047604a3839bb019fa87ee6be52L109
> <https://github.com/CTPPS/cmssw/commit/0c38042ee3e4fcc11dee46153c6dc5f53f4f9859#diff-e01e0047604a3839bb019fa87ee6be52L109>
> It is now fixed in 6d46b3c
> <https://github.com/cms-sw/cmssw/commit/6d46b3c534880ce758fd8d6560d0d6495852539f>.
> Many thanks for pointing this out.


> 
> Also to @slava77 <https://github.com/slava77> - the same bug is in 8_0_X:
> https://github.com/cms-sw/cmssw/blob/CMSSW_8_0_X/EventFilter/CTPPSRawToDigi/src/RawToDigiConverter.cc#L111
> and of course it would be better to fix it before the re-reco. Could we
> bundle this small change with the one we are discussing over the email?

Yes, please go ahead with an update in 80X as well.

**Comment by dmitrijus** [comment]
+1

**Comment by perrotta** [comment]
+1
jenkins comparisons show no differences (which is good, as this PR is  meant to 2017 data taking)
code looks correct, and requested adjustments were applied

**Comment by mommsen** [comment]
+1

**Comment by jan-kaspar** [comment]
> Yes, please go ahead with an update in 80X as well.

Thanks to @forthommel , a back-port of this bug fix has been included in #18461 by 3cceaaa7e398ad2e81521a1fb3fdefb518ffc379 .

**Comment by arunhep** [comment]
+1

**Pull request merged**
