### PR TITLE
Update autoSkim for 2023 data taking [13_0_X]

### PR DESCRIPTION
**Pull request by youyingli**
#### PR description:

Update new PDs to support the skim for 2023 data taking. The update follows the following:

- [CMSHLT-2596](https://its.cern.ch/jira/browse/CMSHLT-2596) : Split ```JetMET```, ```EGamma``` and ```Muon``` into 2 stream
- [CMSHLT-2707](https://its.cern.ch/jira/browse/CMSHLT-2707) : Move ```HLT_CscCluster``` and ```HLT_L1CSCShower_*``` triggers from ```DisplacedJet``` PD to ```Muon``` PD
- Disappearing Muon skim is added : https://github.com/cms-sw/cmssw/pull/40666
- **Still waiting for LLP Jet skim added and its backport** 

Update the skim workflow to fit the 2023 skim config

#### PR validation:

N/A

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

backport of https://github.com/cms-sw/cmssw/pull/41145

### CODE REVIEW

**Comment by youyingli** [comment]
backport of https://github.com/cms-sw/cmssw/pull/41145

**Comment by perrotta** [comment]
backport of https://github.com/cms-sw/cmssw/pull/41145

**Comment by francescobrivio** [comment]
@youyingli just to be clear, if these changes need to go in Tier0 (i.e. affect prompt reconstruction), you should actually change the Tier0 configuration. e.g. see this line for example for `JetMET`:
https://github.com/dmwm/T0/blob/ca4ab8e66f971294d77b209b96de65b5f3ba6794/etc/ProdOfflineConfiguration.py#L654-L667

You can scroll through the rest of the file and look for `physics_skims` to double check that all the PDs are correctly covered.

Cheers,
Francesco as ORM

**Comment by francescobrivio** [comment]
> @youyingli just to be clear, if these changes need to go in Tier0 (i.e. affect prompt reconstruction), you should actually change the Tier0 configuration. e.g. see this line for example for `JetMET`: https://github.com/dmwm/T0/blob/ca4ab8e66f971294d77b209b96de65b5f3ba6794/etc/ProdOfflineConfiguration.py#L654-L667
> 
> You can scroll through the rest of the file and look for `physics_skims` to double check that all the PDs are correctly covered.
> 
> Cheers, Francesco as ORM

FYI @cms-sw/pdmv-l2 in case something needs to be changed in the Tier0 config, you can request it at the JointOps meeting...there is a dedicated `PdmV` section for cases like this 😄

**Comment by youyingli** [comment]
@francescobrivio , thanks for the reminder. Yes, this should be updated to T0 config. I will submit a ticket to T0 JIRA for a request.

**Comment by youyingli** [comment]
> @francescobrivio , thanks for the reminder. Yes, this should be updated to T0 config. I will submit a ticket to T0 JIRA for a request.

The ticket has been created in [CMSTZ-1031](https://its.cern.ch/jira/browse/CMSTZ-1031).

**Comment by francescobrivio** [comment]
The error from [this log](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-17b18a/31802/runTheMatrix-results/matrixTests.log) shows:
```
ERROR reading file: relval_standard 'SKIMJETMETRUN3_reHLT'
Traceback (most recent call last):
  File "/cvmfs/cms-ci.cern.ch/week1/cms-sw/cmssw/41146/31802/CMSSW_13_0_X_2023-04-03-2300/bin/el8_amd64_gcc11/runTheMatrix.py", line 633, in <module>
    ret = runSelected(opt)
  File "/cvmfs/cms-ci.cern.ch/week1/cms-sw/cmssw/41146/31802/CMSSW_13_0_X_2023-04-03-2300/bin/el8_amd64_gcc11/runTheMatrix.py", line 23, in runSelected
    mrd.prepare(opt.useInput, opt.refRel, opt.fromScratch)
  File "/cvmfs/cms-ci.cern.ch/week1/cms-sw/cmssw/41146/31802/CMSSW_13_0_X_2023-04-03-2300/src/Configuration/PyReleaseValidation/python/MatrixReader.py", line 509, in prepare
    self.readMatrix(matrixFile, useInput, refRel, fromScratch)
  File "/cvmfs/cms-ci.cern.ch/week1/cms-sw/cmssw/41146/31802/CMSSW_13_0_X_2023-04-03-2300/src/Configuration/PyReleaseValidation/python/MatrixReader.py", line 255, in readMatrix
    if self.relvalModule.steps[stepName] is None:
KeyError: 'SKIMJETMETRUN3_reHLT'
```
@cms-sw/pdmv-l2 you might know where this comes from.

**Comment by youyingli** [comment]
Hi @francescobrivio , thanks for the clarification. Indeed, the wf should be updated to fit the correct skim config here, not T0. I will update them.

**Comment by kskovpen** [comment]
please test

**Comment by youyingli** [comment]
@kskovpen , @srimanob, @perrotta , could you please sign it as the test was passed?

**Comment by kskovpen** [comment]
+pdmv

**Comment by srimanob** [comment]
+Upgrade

**Comment by perrotta** [comment]
+1

**Pull request merged**
