### PR TITLE
Fix for the Streams' names to be monitored and protection for paths w…

### PR DESCRIPTION
**Pull request by arcidiac**
…ith zero filters

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by deguio** [comment]
ciao @arcidiac 
this includes additional changes wrt the corresponding PR in 76: #11496 
is this intentional?
thanks,
F.

**Comment by arcidiac** [comment]
Yes it is. It was realized that some fixes added by Darren to the GeneralHLTOffline in 76 and 75 were not propagated here. So here they are!

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
