### PR TITLE
Removed unused variables and functions in RecoLocalCalo/HGCalRecAlgos

### PR DESCRIPTION
**Pull request by Dr15Jones**
These were causing clang warnings.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/25404	e53b8ef
- technical
- jenkins tests pass

**Comment by kpedro88** [comment]
+upgrade

**Comment by fabiocos** [comment]
+1

**Pull request merged**
