### PR TITLE
Make FastTimerService easier to use

### PR DESCRIPTION
**Pull request by kpedro88**
#### PR description:

The [FastTimerService](https://twiki.cern.ch/twiki/bin/viewauth/CMS/FastTimerService) is used as the basis for [circles](https://github.com/fwyzard/circles) (among other things).

The twiki page (linked above) describes how to use it, but requires manually editing configs generated by cmsDriver.

To make this easier to use, I put the code from the twiki into some functions that can be given to cmsDriver using `--customise`:
* `customise_timer_service`
* `customise_timer_service_singlejob`
* `customise_timer_service_multirun`
* `customise_timer_service_print`

I also added a simple harvesting config (which has to run standalone, so a customise function is not appropriate), which includes a `multirun` command-line argument.

@fwyzard if you agree with this approach, we can update the twiki to point out the availability of these convenience functions.

#### PR validation:

Tested the various customise functions and observed that they ran successfully and provided the expected input.

### CODE REVIEW

**Comment by kpedro88** [comment]
please test

**Comment by fwyzard** [comment]
@kpedro88
thanks, looks good.

I cannot actually test it this week, and I'm thinking it could be useful to have the default behaviour in a cff file as well - but I can add that next week.

**Comment by fwyzard** [comment]
+1

**Comment by kpedro88** [comment]
ping @cmsbuild

**Comment by silviodonato** [comment]
+1

**Pull request merged**
