### PR TITLE
Phase2-hgx272 Make sure that change of units in dd4hep will not affect HGCal geometry

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Make sure that change of units in dd4hep will not affect HGCal geometry

#### PR validation:

Use runTheMatrix test workflows

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade

**Comment by qliphy** [comment]
+1

**Pull request merged**
