### PR TITLE
Update to HLT menu 3p2 with muon fix (103X)

### PR DESCRIPTION
**Pull request by silviodonato**
Update to HLT menu 3p2 with muon fix (https://its.cern.ch/jira/browse/CMSHLT-1942).
The version without muon fix is #23942

### CODE REVIEW

**Comment by silviodonato** [comment]
hold

**Comment by silviodonato** [comment]
please test

**Comment by davidlange6** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by silviodonato** [comment]
unhold

**Comment by Martin-Grunewald** [comment]
+1

**Comment by Martin-Grunewald** [comment]
@Dr15Jones 
please sign for core.
Thanks!

**Comment by Dr15Jones** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Pull request merged**
