### PR TITLE
Add a generator filter based on properties of mother and long-lived sister of a gen particle

### PR DESCRIPTION
**Pull request by mgratti**
#### PR description:

This PR introduces a new generator filter that was designed to efficiently select events with heavy long-lived neutrinos (N) from a B semi-leptonic decay: B -> l X N (-> l pi).
Events are filtered based on:
* the kinematic properties of the lepton l,
* the pdgId of the possible mother (multiple) 
* the pdgId and 3d displacement of one among the lepton's sisters. 

This is meant to be used for an MC production using the b-parking conditions, so a backport to 10_2_X will be submitted too, once this PR is merged.

It was checked that the code correctly filters B -> l X N (-> l pi) decay chains with the desired properties.

#### PR validation:

Followed the instructions here:
http://cms-sw.github.io/PRWorkflow.html

The report of `runTheMatrix.py -l limited -i all --ibeos` is attached:
[runall-report-step123-.log](https://github.com/cms-sw/cmssw/files/6234879/runall-report-step123-.log)

Code style checks have been performed and included as a separate commit.

### CODE REVIEW

**Comment by SiewYan** [comment]
please test

**Comment by SiewYan** [comment]
Hi, I do not see any unexpected changes. However, one error flagged, "Static analyzer EventSetupRecord::get warnings" [1], is this expected from computing? @qliphy , @silviodonato 

[1] https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-961a64/13969/llvm-analysis/esrget-sa.txt

**Comment by qliphy** [comment]
@SiewYan  
there are deprecated edm::eventsetup::EventSetupRecord::get<edm::ESHandle<HepPDT::ParticleDataTable> > function calls in FWCore/Framework/interface/EventSetup.h, they are not part of this PR. 

https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideHowToGetDataFromES#Getting_data_from_EventSetup_wit

**Comment by SiewYan** [comment]
Thanks @qliphy

**Comment by SiewYan** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
