### PR TITLE
Ecalmultifit use DB inputs and retuning of spike flagging

### PR DESCRIPTION
**Pull request by emanueledimarco**
This pull request contains:

1) use of the DB inputs in the multifit local reconstruction. For the time being, the GT uses the MC conditions for both data and MC, so no change is expected wrt the previous one (python configuration with MC conditions)

2) re-introduction of the spike killing flags, kOutOfTime and kWeird. The cuts for the topological variables have been reoptimised. If those flags are used in the PF rechits, there could be some minimal change wrt previous version.

3) autocond files contain the GTs with the payloads (there should be the same commit by Salvatore @diguida on the AlCa DB side).

Adding @bendavid @argiro @cerminar @diguida to check this.

IMPORTANT: for @bachtis : this version has the kOutOfTime flag re-enabled (for spikes flagging). Please, if you want, disable it in the PF clustering filtering

### CODE REVIEW

**Comment by diguida** [comment]
please test

**Comment by diguida** [comment]
+1
The Global Tags here contain the minimal changes for pre7 @davidlange6

**Comment by slava77** [comment]
there are small but quite visible changes in jenkins comparisons.
I suppose these are a part of 2)
ecal rechits themselves show only chi2 and reco flag changes.

https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_7_4_X_2015-02-03-0200+7548/5888/validateJR/all_OldVSNew_RunPhoton2012Bwf4p53/all_OldVSNew_RunPhoton2012Bwf4p53c_log10recoPFClusters_particleFlowClusterECAL__reRECO_obj_energy.png

higher stat plots would be useful to characterize the diffs.
If there is a presentation covering the changes, please link it in the description of the PR (at the top of the thread)

**Comment by bendavid** [comment]
In my opinion this should be taken only together with corresponding change to PF to ignore the kOutOfTime flag (that could be implemented in parallel since it will have no effect on the current release where the flag is never set)

**Comment by slava77** [comment]
this change in PF can also be included in one PR superseding this one or just with updating this one.

**Comment by bendavid** [comment]
Ok,
I THINK it only needs to be changed here:
https://github.com/cms-sw/cmssw/blob/CMSSW_7_4_X/RecoParticleFlow/PFClusterProducer/python/particleFlowRecHitECAL_cfi.py

@bachtis can you confirm?

**Comment by emanueledimarco** [comment]
if @bachtis confirms that this is the only place it occurs, I will do the change and update the pull-request. In this way we have the flagging ready to be used in case we need it, but it is turned off by default in PF.

**Comment by bachtis** [comment]
Hi guys. Sorry . Too much code to be integrated at the same time . Yes Josh is right, timingCleaning is used in the PFRecHitQTest ECAL here:
https://github.com/cms-sw/cmssw/blob/CMSSW_7_4_X/RecoParticleFlow/PFClusterProducer/interface/PFRecHitQTests.h

So to disable it set timingCleaning into false for barrel and endcap in 

https://github.com/cms-sw/cmssw/blob/CMSSW_7_4_X/RecoParticleFlow/PFClusterProducer/python/particleFlowRecHitECAL_cfi.py

**Comment by slava77** [comment]
nice,
so, we'll wait for the update and then check

**Comment by emanueledimarco** [comment]
done

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
testing-testing-testing

**Comment by slava77** [comment]
+1

for  https://github.com/cms-sw/cmssw/pull/7548	 4b8bba3
tested in CMSSW_7_4_X_2015-02-02-0200 /test area test7548; with cherry pick/

Minor changes are observed, mostly related to flagging, but there also appear to be (much smaller) either numerical precision variation or an indirect feed-back through the calo-based quantities (dependent on flags) in the PF reco.

A summary of observations
- the technical performance shows 
    - about 50 MB increase in RSS in TTbar PU35@25ns sample (on 100 events); 
    - timing changes are mainly the expected place in 291.80 ms/ev ->       324.09 ms/ev ecalMultiFitUncalibRecHit (this appears to be real, not a DB latency)
- Minor changes in ecal clusters (non-PF ) hybrid SCs  have large variations (no clear shape, a few % reduction in the total count); multi5x5 just tiny changes
data Photon2012B
all_test7548vsorig_runphoton2012bwf4p53c_log10recosuperclusters_correctedhybridsuperclusters__rereco_obj_energy
- relatively small changes in PF
all_test7548vsorig_runphoton2012bwf4p53c_log10recopfjets_ak4pfjets__rereco_obj_et

- the changes in flagging are picked up by calo-based quantities (towers, jets), in some cases this can trigger jet core iteration in tracking and then tracks change ever so slightly as well

- there is some numerical feature in a few plots of S25/E: the bin at 1 apparently changes to 1+epsilon and goes to the overflow
this one is in 3 TeV dijet
wf1313_s25oe_ee
this one is in ttbar no-PU ( ``` runTheMatrix.py -l 25.0 --useInput all ``` to reproduce) 
wf25_s25oe_ee

**Comment by diguida** [comment]
+1
Concerning the timing changes in 291.80 ms/ev -> 324.09 ms/ev `ecalMultiFitUncalibRecHit`, the possible DB contribution in the increase of the processing time is the fetching and deserialization of the payload. While the IOV is loaded at the job start, the query for the payload is run on demand, i.e. only when needed, then it is cached. In order to see the DB latency, we should check the first event passing through the module w.r.t. the other ones.
@ggovi can further comment on this.

**Pull request merged**
