### PR TITLE
Updates on TrackerMaps scripts

### PR DESCRIPTION
**Pull request by arossi83**
This changes affects only scripts used by Tracker shifters. No changes on production code!

### CODE REVIEW

**Comment by andrius-k** [comment]
please test

**Comment by arossi83** [comment]
> @arossi83 Why were the python 3 print function removed in [this case](https://github.com/cms-sw/cmssw/pull/25600/files#diff-ce9c4d45bbdf17211b742e627f6794afR41) (and some other cases in this PR)?

@adrius-k it was an error from my side, I restored it. Thanks!

**Comment by andrius-k** [comment]
@arossi83 Yep, I see the updates but there are some newly introduced code that would use python 2 syntax for printing. Is this desired? Previously there were quite a few (auto generated) PRs that were migrating things to python 3 syntax, so I'm asking because I'm not sure what is the policy on this.

**Comment by arossi83** [comment]
@adrius-k Ok, I see. I think it's better to have everything consistent so I will update also the other codes (sorry I completely miss them before). So please wait for another commit (probably tomorrow).

**Comment by andrius-k** [comment]
+1

**Comment by fabiocos** [comment]
@davidlange6 this scrip cleans the "/usr/bin/python" statement moving it to "/use/bin/env python". As far as I can see there are several places where the first approach is used. Should we consider to clean systematically everything?

**Comment by fabiocos** [comment]
+1

**Pull request merged**
