### PR TITLE
DD4hep: Cleanup HCal Barrel Algorithm

### PR DESCRIPTION
**Pull request by ianna**
#### PR description:

* Remove unneeded caching of shapes and volumes in the namespace containers
* Name the shapes in their constructor

@bsunanda - FYI, perhaps, introduced changes are applicable to other algorithms.

#### if this PR is a backport please specify the original PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by bsunanda** [comment]
@ianna I shall take a look and apply to other cases as well

**Comment by ianna** [comment]
+1

**Comment by ianna** [comment]
@civanch - please, review.

**Comment by civanch** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
