### PR TITLE
Use tbb:task_group in TestTBBTasksAnalyzer

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

- Changed to use tbb::task_group instead of the deprecated tbb::task API.
- Also changed to be a ::one module

#### PR validation:

Code compiles and unit test succeeds.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by makortel** [comment]
@cmsbuild, please test

(for cleaner comparisons)

**Comment by makortel** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
