### PR TITLE
Cleanup definition of exotic particles

### PR DESCRIPTION
**Pull request by civanch**
Exotic particles are not part of Geant4 particle table. For Geant4 tracking of such particles they should be defined and corresponding physics processes (decay, ionisation...) should be assigned. This is done inside CustomPhysics sub-library, which is cleaned up in this PR:
 1) fixed reading of decay channels from slha data file (end of list of channels was not treated correctly
 2) added protection against double instantiation of G4Decay for an exotic particle
 3) Exclude decays with zero branching ratios
 4) improved LogDebug and LogInfo printouts

Should not affect mainstream MC production.

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by fabiocos** [comment]
@civanch this change affects the CustomPhysics list, not the standard production one, so it should affect only simulations of exotic final states, am I correct? All the protections look reasonable, was any test done with a generator of some exotic state?

**Comment by civanch** [comment]
@fabiocos , these fixes where done when I was debugging problem with Chagino and Neutralino run provided by exotica group, there were corresponding shla files and their receipt.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
