### PR TITLE
L1Trigger DQM combo PR

### PR DESCRIPTION
**Pull request by nsmith-**
This combines #13725, #13733, #13513, as well as a few changes on top by @swang373

### CODE REVIEW

**Comment by swang373** [comment]
Hi @vanbesien,

There are still commits to be made to this pull request's branch, but do expect that I will strive to have everything in around the afternoon tomorrow (say, 3 PM?). The remaining changes deal with:

- New plots requested by the EMTF subsystem (I am meeting with Nick and Vivan who are implementing these plots to finalize this tomorrow morning).
- New plots and fixes to old plots requested by the uGMT subsystem (I am meeting with @thomreis tomorrow at 10 AM to finalize this)
- There is a fix for the BMTF unpacker that needs to be incorporated. If they can do this ASAP, BMTF module will be included in the DQM path. If the do not make it in time, would it be possible to patch them in before MWGR4 ends?

I will let you know as soon as everything is ready to test in playback. Thanks!

**Comment by swang373** [comment]
@vanbesien 

I am now merging in the EMTF DQM modules (some conflicts and such). There will have to be a few fixes to the uGMT code, and BMTF's unpacker may soon be incorporated.

**Comment by swang373** [comment]
BMTF has compiled and is running. Will cross-check with @eparadas once the plots are created. All that remains is cleaning up a wrongly used variable in the uGMT module and adding any last plots.

**Comment by swang373** [comment]
@vanbesien 
The BMTF DQM module has been included and what known bugs were fixed. This will suffice for a first pass, as plots can always be added along the way. This branch is ready to be tested on the playback.

@nsmith- 
Merging in the fixed BMTF unpacker from @eparadas brought in many other commits as well. They didn't interfere with running the DQM modules, but I'm wary that I did something wrong.

**Comment by vanbesien** [comment]
Hi @swang373 , can you put it in the dropbox in the tagcollector?: https://twiki.cern.ch/twiki/bin/view/CMS/DQMP5TagCollector
And confirm that this means we can drop #13513 and #13733, just to be sure.

**Comment by swang373** [comment]
Hi @vanbesien , I can confirm for sure that #13513 can be dropped, and I suppose #13733 can be dropped as well as it too is rolled into this pull request. I'll put it in the tagcollector right now,

**Comment by nsmith-** [comment]
@swang373 I think the unpacker merge pulled in a whole bunch of cms-l1t-offline development.
For MWGR#4 DQM, we might as well let this PR baloon, but I think that we may have to make a new PR after more of the trigger stuff is integrated, for merging into a release.

**Comment by vanbesien** [comment]
-1
Please rebase. PR should only change the relevant files.

**Comment by deguio** [comment]
guys. this is becoming ~a mess. please:
- close the PRs which are not relevant anymore (the original PRs #13725, #13733, #13513)
- fix this combo PR so that it doesn't bring in anything more than: #13725, #13733, #13513
- do the same for the 81x branch as well
- cross check that what you need for GR#4 is up to date at: https://twiki.cern.ch/twiki/bin/view/CMS/DQMP5TagCollector

if you want the applications up and running on Monday morning please complete the above steps by tonight.
thanks for understanding,
F.

**Comment by nsmith-** [comment]
@deguio, @vanbesien,
We force pushed a cleaned up history.
It compiles and tests ok from fresh 8_0_1

**Comment by swang373** [comment]
@deguio, @vanbesien,
I can attest to that. I was able to merge it within a fresh CMSSW_8_0_1 release, compile, and run. Here are the plots demonstrating that all subsystems are able to run and produce plots.

**Comment by mzarucki** [comment]
I closed the PRs https://github.com/cms-sw/cmssw/pull/13725 and https://github.com/cms-sw/cmssw/pull/13697 (for 80X and 81X, respectively), as the L1TStage2uGT DQM module will be incorporated in this combined PR.

**Comment by deguio** [comment]
thanks,
I see that a number of changes affecting packages:
DataFormats/L1TMuon
EventFilter/L1TRawToDigi
have been included wrt the sum of the three original PRs.

could you give more details about that?

we will review this PR and test it on the playback over the weekend.

for offline DQM (i.e. the one that runs at the T0) as mentioned already, the inclusion of the relevant sequences in central RECO and DQM will be needed. at the moment this PR concerns online online DQM.
thanks,
F.

**Comment by swang373** [comment]
@deguio 
My apologies for the late reply. I can account for all the changes in DataFormats and EventFilter.

The changes in DataFormats are authorized by @abrinke1 , either minor changes I did (like in #13513), or full blown new developments he has made, such as new member variables to plot and establishing a conversion convention from hardware to physical values. These affect EMTFOutputCollection only, and so their related commits are a part of this branch in order to make plots from some of the member variables.

As for EventFilter, the majority of the changes are from merging in BMTF's unpacker, provided by @eparadas . I do not know the full story, but the BMTF unpacker required a bug fix, and now with this fix implemented, we may make plots from them. There are minor changes to EMTF's unpacker by @bmichlin , who kindly adds more features (such as decoding our MEX_ID's) for the DQM module to either make use in it's processing logic or plot directly.

Thanks!

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1

**Comment by deguio** [comment]
please provide the equivalent PR of this one in 81x and close the ones that are superseded.
thanks,
F.

**Comment by nsmith-** [comment]
*sigh* I guess only llvm is smart enough to find unused anonymous namespace consts?

**Comment by swang373** [comment]
I'll update this branch soon, as the EMTF DQM module requires reorganization and checking to ensure that the changes from @nhaubrich , @vivannguyen , and myself did not introduce bugs.

**Comment by deguio** [comment]
please test

**Comment by nsmith-** [comment]
@deguio, DAS error, not our fault.  Can you tell cmsbot to re-test?

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1

**Comment by swang373** [comment]
@deguio @mzarucki 
The urgent uGT updates have been merged in (66c034125032720b624ec495ee3a2f102ff9c863). The CMSSW_8_1_X version pull request (cms-sw/cmssw#13891) has been updated as well.

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1

**Comment by nsmith-** [comment]
FYI @rekovic, This branch will have merge conflicts with #13767 
We can easily resolve this in the same way that #13891 was done, once #13767 is in an IB.

**Comment by rekovic** [comment]
@nsmith- Thanks.

**Comment by mulhearn** [comment]
This PR is superseded by #14021.

**Comment by vanbesien** [comment]
Don't forget to update the tagcollector if needed.
And maybe close this PR if it's not needed anymore.

**Comment by nsmith-** [comment]
@vanbesien with regards to functionality the new PR is equivalent, so tag change is optional.
The main purpose is to help guide the code changes into a new CMSSW release.

**Pull request merged**
