### PR TITLE
Simplifying LL1TkMuonFilter, CMSSW_12_5_X

### PR DESCRIPTION
**Pull request by trtomei**
#### PR description:

Addressing items 2 and 3 of https://github.com/cms-sw/cmssw/issues/39194
 - Simplified the whole applyQualities infrastructure of the module
 - Default is now `applyQualities = false` and `qualities = {}` (an empty vector). This is fine; if `applyQualities` is set to `true`, then some qualities must be furnished!

#### PR validation:

Test done:
```
cmsDriver.py Phase2 -s HLT:75e33 --processName=HLTX \
--conditions auto:phase2_realistic_T21 \
--geometry Extended2026D88 \
--era Phase2C17I13M9 \
--eventcontent FEVTDEBUGHLT \
--filein=/store/relval/CMSSW_12_5_0_pre5/RelValTTbar_14TeV/GEN-SIM-RECO/125X_mcRun4_realistic_v2_2026D88noPU-v1/10000/8abbb6aa-60d0-4d16-8a9a-7b9c95e5aee7.root \
-n 100 --nThreads 1 --no_exec
```
runs fine, and the new module interface is exercised.

This PR is a backport of https://github.com/cms-sw/cmssw/pull/39280 . It is needed in CMSSW_12_5_X for the upcoming MC production for L1T.

### CODE REVIEW

**Comment by missirol** [comment]
backport of #39280

**Comment by missirol** [comment]
please test

**Comment by missirol** [comment]
please abort

Tests seems stuck.

**Comment by missirol** [comment]
please test

**Comment by missirol** [comment]
+hlt

**Comment by perrotta** [comment]
+1
- Verbatim backport of #39280
- RelVal Input test errors are unrelated

**Comment by perrotta** [comment]
merge

**Pull request merged**
