### PR TITLE
Deprecation of T**DetID and PX*DetID in Alignment/TrackerAlignment/plugins/CosmicRateAnalyzer.cc

### PR DESCRIPTION
**Pull request by alesaggio**
Changed to use TrackerTopology

cc @vidalm @OlivierBondu @pieterdavid

### CODE REVIEW

**Comment by arunhep** [comment]
please test

**Comment by mmusich** [comment]
@arunhep, this PR is part of a series involving deprecation of specialized Strip and Pixel DetIds in favor of accessing the same information via TrackerTopology. 
The change is purely technical and will not affect any production workflow. Any difference in the reco products comparison as shown in the bot report likely comes from the additional commits that were brought via cms-merge-topic.
Thanks

**Comment by arunhep** [comment]
+1
@mmusich thanks for explaining the context

**Comment by davidlange6** [comment]
+1

**Comment by mmusich** [comment]
tracked at #19398

**Pull request merged**
