### PR TITLE
Clean redundant member functions from ElectronSeed

### PR DESCRIPTION
**Pull request by guitargeek**
#### PR description:

When I checked out the pixel matching code for my previous PR I noticed there were some redundant member functions in the `ElectronSeed` class that were flagged for a cleanup. These member functions were originally kept for backwards compatibility with the old `ElectronSeed` class so the new `ElectronSeed` could be quickly integrated without adapting function calls in all of CMSSW. in Probably it's now a good time for removing them.

#### PR validation:

CMSSW compiles.

#### if this PR is a backport please specify the original PR:

No backport intended.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by jfernan2** [comment]
+1

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/28198	81c2059 
- technical 
- jenkins tests pass

**Comment by Martin-Grunewald** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
