### PR TITLE
Fix gazillions of ICC warnings.

### PR DESCRIPTION
**Pull request by ktf**
- const type qualifier on basic return type is meaningless.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
Actually, ```const``` on some return values is useful. It keeps one from doing
```
foo().bar = 3;
```
and stops
```
auto & f = foo();
f.bar =3;
```
Which may help with the semantics of the code to avoid cases where you think you are changing the internals of ```foo``` but in reality you are not.

**Comment by ktf** [comment]
I think icc complains only about basic scalar types (and my pr only fixes
those). In that case what you say does not apply (since there are no
internals) . Do you want me to amend the commit message or you still think
my pr (and icc) is wrong?

**Comment by civanch** [comment]
+1
I believe these method signatures are historical...

**Comment by ktf** [comment]
please test

**Pull request merged**
