### PR TITLE
implement "plan 1" and sum SiPM rechits over all depths

### PR DESCRIPTION
**Pull request by fwyzard**
Introduce a new name `hltHbhePhase1Reco` for the collection of rechits with QIE8/QIE11 and depth segmentation while keeping the original name `hltHbhereco` for the collection of rechits summed over all depths.

### CODE REVIEW

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
+1

**Comment by fwyzard** [comment]
I guess in principle these changes should come from the `run2_HEPlan1_2017` era, but that would be a bit more complicated to support.
Do let me know if having them in the common `run2_HCAL_2017` era breaks anything.

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
+1

**Comment by fwyzard** [comment]
sorry, pushed to the wrong branch

**Comment by fwyzard** [comment]
+1

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
(not sure if the tests are needed again or not)

**Comment by Martin-Grunewald** [comment]
@fwyzard 
Does this way avoid expansion of sequences when adding/inserting?

**Comment by fwyzard** [comment]
Yes, it should avoid it.

**Comment by Martin-Grunewald** [comment]
Great!

**Comment by davidlange6** [comment]
+1
(but depending on names of plugins is dangerous at best)

**Comment by fwyzard** [comment]
Thanks.

What do you mean by

> depending on names of plugins

?

**Comment by kpedro88** [comment]
@fwyzard just saw this - you can get away with keeping these changes in Era `run2_HCAL_2017` as long as we keep Plan1; if it gets removed, you should revert

**Comment by kpedro88** [comment]
does this also need to be ported to 84X?

**Comment by fwyzard** [comment]
Thanks, let's keep it like that then.

No need to backport to 8.4.x if it is used only for data taking. We should backport it if it is used for MC production.

**Pull request merged**
