### PR TITLE
Fixup crash observed in 0-event 1307.0 due to L1TGlobalSummary|Util

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
Fixup crash observed in 0-event 1307.0 due to L1TGlobalSummary|Util

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test
@mulhearn @rekovic

**Comment by Martin-Grunewald** [comment]
@mulhearn @rekovic
Please sign this for 81X

**Comment by Martin-Grunewald** [comment]
@mulhearn @rekovic
Please sign. Thanks!

**Comment by mulhearn** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
