### PR TITLE
CMSHLT-508 74X PR to update DQM modules

### PR DESCRIPTION
**Pull request by mrcarver**

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1

**Comment by parbol** [comment]
Hi I would like to understand whether we need to change something here. Having a look at the log files I didn't see anything that was particularly pointing to our code. I only see the PFMET invalid collection in the HotlineDQM for the first workflow and the Trigger Summary not being available in the second one.

**Comment by Martin-Grunewald** [comment]
The problem seems to be
```
%MSG
attempting to stop a stopped timer
05-Aug-2015 11:58:16 CEST  Closed file root://eoscms//eos/cms/store/relval/CMSSW_7_4_0_pre7/RelValMinBias_13/GEN-SIM/MCRUN2_74_V7-v1/00000/802A09CA-EEB6-E411-A76A-0025905B85B2.root?svcClass=default
```

**Comment by Martin-Grunewald** [comment]
please test

**Comment by parbol** [comment]
Dear experts,

We are a bit lost about the evolution of this PR. Can you please explain whether and action is required from us? We're not 100% sure about the reason why this is failing, if it is failing. It's important that we finish this PR since this is blocking the introduction of a SUSY signal trigger in the menu. You can count with all our resources to fix it, but we need some help to understand what's going on. Thanks

**Comment by davidlange6** [comment]
+1

**Pull request merged**
