### PR TITLE
fixed static analiser warnings3

### PR DESCRIPTION
**Pull request by civanch**
Fixed static analyser warnings in SimG4Core and SimG4CMS. Removed unnecessary comments and empty lines. Substitute auto_ptr. Should not affect production.

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by civanch** [comment]
@davidlange6 , please, do not sign it - I see a minor typo...

**Comment by civanch** [comment]
@davidlange6 , I take back my worries - the PR may be merged.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
