### PR TITLE
restrict NHF-cut to eta<2.4 to prevent it from being applied in the HF

### PR DESCRIPTION
**Pull request by kirschen**
JetID-fix for 2016 datataking

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by davidlange6** [comment]
Hi @kirschen - I don't really follow this change. What is the difference with respect to just disabling the nhf cut completely?

**Comment by kirschen** [comment]
Hi @davidlange6 , this change was discussed in 
https://its.cern.ch/jira/browse/CMSHLT-742
and a separate mail thread involving involved parties/trigger contacts. 

The NHF-cut is still to be applied in the tracker-covered region. However, if applied in HF it is doing harm after PF-reconstruction changes, because the "usual" PF-HF jet has close to 100% neutral hadron fraction. That is why it was dropped from offline JetId-recommendations https://twiki.cern.ch/twiki/bin/viewauth/CMS/JetID#Recommendations_for_13_TeV_data and this just propagates this change to the HLT.

**Comment by davidlange6** [comment]
+1

ah - NHF does not stand for what I thought it did.. Thx.

**Pull request merged**
