### PR TITLE
Remove duplicate ECF variables

### LINKED ISSUE #31052: repeated AK8PuppiSoftDrop ecfN data in slimmedJetsAK8
in regular miniAOD (both in 106X and 112X) we have duplicate values of userFloats in slimmedJetsAK8 appearing with different names, eg. :
- ak8PFJetsPuppiSoftDropValueMap:nb1AK8PuppiSoftDropN2
    - this comes via ak8PFJetsPuppiSoftDropValueMap , inserted in patJetsAK8Puppi 
- nb1AK8PuppiSoftDrop:ecfN2
    - this comes via patJetsAK8PFPuppiSoftDrop, inserted in packedPatJetsAK8

Notably, the former is always present in the jets, while the latter is added only in some jets (where a matching SoftDrop is available?).

one of these should be removed 
@ahinzmann  @camclean @alefisico
please check and comment if this can be addressed soon.
Thank you.

### PR DESCRIPTION
**Pull request by ahinzmann**
#### PR description:

Resolve #31052.
Remove duplicate N2 and N3 variables from MiniAOD.

The duplicate was kept before for backward compatibility with the TWiki (https://twiki.cern.ch/twiki/bin/view/CMSPublic/WorkBookMiniAOD2017#Jets).
The TWiki needs to be updated with this change.

Before this PR, for all AK8 jets with pT<250 GeV 4 values -99999.0 were stored in MiniAOD and NanoAOD. After this PR, those dummy values are not stored anymore MiniAOD, and only kept in NanoAOD for 170<pT<250.

@rappoccio Please check that the code diff makes sense, since you wrote this.

#### PR validation:

scram b runtests

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

No backport planned.

### CODE REVIEW

**Review by rappoccio — APPROVED** [review]

**Comment by rappoccio** [comment]
Looks good, I approved them.

**Comment by perrotta** [comment]
please test

**Comment by mariadalfonso** [comment]
the master should be able to read also the old mini where you still need the value map
you likely need to use the nano-modifiers 
https://github.com/cms-nanoAOD/cmssw/issues/533#issuecomment-672971478

**Comment by ahinzmann** [comment]
While working on a fix for the errors from the tests... a comment for the next round of testing of this PR. The standard workflows with NanoAOD (based on TTbar) typically do not contain any jets with pT>170. Most substructure variables are only calculated above this threshold. Thus the full effect of this PR can only be seen in JetHT workflows (like 136.7722, 136.7952, 136.8521, 136.8522).

**Comment by slava77** [comment]
@cmsbuild please test workflow 10826.0

10826.0 is 2018+QCD_Pt_600_800_13TeV_TuneCUETP8M1_GenSim+Digi+Reco+HARVEST+ALCA+Nano

**Comment by jpata** [comment]
thanks for having started the test @slava77, I'm going to check the differences in the produced NANO root files as suggested.

**Comment by jpata** [comment]
+reco

- verified in workflow `10826.0`
- the only RECO changes in `step3_inMINIAODSIM.root` output are the removal of the following duplicated userFloats for `slimmedJetsAK8`:
```
'ak8PFJetsPuppiSoftDropValueMap:nb1AK8PuppiSoftDropN2',
'ak8PFJetsPuppiSoftDropValueMap:nb1AK8PuppiSoftDropN3',
'ak8PFJetsPuppiSoftDropValueMap:nb2AK8PuppiSoftDropN2',
'ak8PFJetsPuppiSoftDropValueMap:nb2AK8PuppiSoftDropN3'
```
- I also checked that nanoAOD output is not changed

**Comment by slava77** [comment]
> +reco

this abbreviated spelling of the category apparently does not work

**Comment by mariadalfonso** [comment]
+xpog
code cleanup

**Comment by santocch** [comment]
+1

**Comment by qliphy** [comment]
+1

**Comment by Dr15Jones** [comment]
This appears to have broken workflows 136.7722 and 1329.1 in the IBs.

**Comment by Dr15Jones** [comment]
please test workflow 136.7722, 1329.1

**Comment by mariadalfonso** [comment]
@ahinzmann 

the 136.722 and 1329.1 are mini of a type 'run2_miniAOD_80XLegacy'

we should add 'run2_nanoAOD_92X' 'run2_miniAOD_80XLegacy' in the list here 
https://github.com/cms-sw/cmssw/pull/31213/files#diff-8255cc2b641b6438258bddebcd7425efR473

**Pull request merged**
