### PR TITLE
PPS DQM plots for new RPOTs 45-220-NR-HR and 56-220-NR-HR (backport of 41389)

### PR DESCRIPTION
**Pull request by grzanka**
#### PR description:

This PR adds new plots to the DQM for two Roman Pots (previously not included in DQM).
Is it needed in the Online DQM GUI

#### PR validation:

Standard runTheMatrix and manual tests on new data by @smorovic

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport of https://github.com/cms-sw/cmssw/pull/41389

### CODE REVIEW

**Comment by grzanka** [comment]
> @grzanka since the master moved today to CMSSW_13_2_X, please don't forget to prepare also a backport to 13_1_X if you want this backport in 13_0_X get merged

Thanks for notice, I will prepare it soon.

**Comment by mandrenguyen** [comment]
backport of #41389

**Comment by mandrenguyen** [comment]
type ctpps

**Comment by mandrenguyen** [comment]
+reconstruction

**Comment by emanueleusai** [comment]
@grzanka can you confirm you need this in online DQM?

**Comment by emanueleusai** [comment]
please test

**Comment by smorovic** [comment]
+daq

Note, @emanueleusai, @grzanka, that we should deploy this (in DQM) only with the DAQ event-builder update that is coming next week: May 15th or later is the tentative date because our expert is at the conference (CHEP).

Therefore, merging this patch should be well timed, i.e. we should probably hold in case a new 13_0_X release or patch release is planned between today and Friday.

**Comment by grzanka** [comment]
> +daq
> 
> Note, @emanueleusai, @grzanka, that we should deploy this (in DQM) only with the DAQ event-builder update that is coming next week: May 15th or later is the tentative date because our expert is at the conference (CHEP).
> 
> Therefore, merging this patch should be well timed, i.e. we should probably hold in case a new 13_0_X release or patch release is planned between today and Friday.

I confirm that we need that patch in the online DQM. As for the schedule, please propose something that is well timed and leads to shortest deployment time.

**Comment by mandrenguyen** [comment]
+reconstruction
resign

**Comment by smorovic** [comment]
> > +daq
> > Note, @emanueleusai, @grzanka, that we should deploy this (in DQM) only with the DAQ event-builder update that is coming next week: May 15th or later is the tentative date because our expert is at the conference (CHEP).
> > Therefore, merging this patch should be well timed, i.e. we should probably hold in case a new 13_0_X release or patch release is planned between today and Friday.
> 
> I confirm that we need that patch in the online DQM. As for the schedule, please propose something that is well timed and leads to shortest deployment time.

Today is the ORP meeting, we can bring it up. If a release is tagged on Friday (or later), I think that could work.
Early next week (Monday, possibly Tuesday) we can then bring up at the daily run meeting and see when everyone (DAQ, DQM, HLT) can move to the new version. HLT also unpacks CTPPS product (even if it doesn't use it), so it should stay in sync.
Maybe it's good to add a note also to the google doc of the weekly run meeting of today.

**Comment by smorovic** [comment]
> > > > +daq
> > > > Note, @emanueleusai, @grzanka, that we should deploy this (in DQM) only with the DAQ event-builder update that is coming next week: May 15th or later is the tentative date because our expert is at the conference (CHEP).
> > > > Therefore, merging this patch should be well timed, i.e. we should probably hold in case a new 13_0_X release or patch release is planned between today and Friday.
> > > 
> > > 
> > > I confirm that we need that patch in the online DQM. As for the schedule, please propose something that is well timed and leads to shortest deployment time.
> > 
> > 
> > Today is the ORP meeting, we can bring it up. If a release is tagged on Friday (or later), I think that could work.
> > Early next week (Monday, possibly Tuesday) we can then bring up at the daily run meeting and see when everyone (DAQ, DQM, HLT) can move to the new version. HLT also unpacks CTPPS product (even if it doesn't use it), so it should stay in sync.
> > Maybe it's good to add a note also to the google doc of the weekly run meeting of today.
> 
> Will you be connected to the ORP meeting today ? I won't be able to connect unfortunately...

Yes, it's now now and we just discussed i. Release should be ready for ~ early next week (DQM will also test this patch in the meantime).

**Comment by emanueleusai** [comment]
> +daq
> 
> Note, @emanueleusai, @grzanka, that we should deploy this (in DQM) only with the DAQ event-builder update that is coming next week: May 15th or later is the tentative date because our expert is at the conference (CHEP).
> 
> Therefore, merging this patch should be well timed, i.e. we should probably hold in case a new 13_0_X release or patch release is planned between today and Friday.

@smorovic thank you for the clarification, so does it make sense to test this online without the DAQ event-builder update?

**Comment by smorovic** [comment]
@emanueleusai 
I would expect it to have mismatches in plotting since input is different, but should at least run without crash or exception (as the bitmask..). Maybe just running in playback and checking that the job completes cleanly?

**Comment by syuvivida** [comment]
Hi @smorovic 
 our software expert Michel Succar @micsucmed is testing this PR at playback and post the results here later.

Eiko

**Comment by smorovic** [comment]
Thanks @micsucmed, then if from DQM side there is no other issue, please sign off all three PRs (13_2, 13_1 and 13_0).

**Comment by emanueleusai** [comment]
+1

**Comment by rappoccio** [comment]
+1

**Pull request merged**
