### PR TITLE
Add HI mixing wfs for 2023 MC

### PR DESCRIPTION
**Pull request by mandrenguyen**
#### PR description:

Back in #41095 I introduced MC RelVal workflows for heavy ions with 2023 conditions (previously we had 2022).  However, I only add noPU workflows as I was waiting for GEN-SIM input for the mixing workflows. 
Now that exists, so this PR adds the mixing ones. 
Turns out there was a typo in a parameter in the gen fragments which I fixed as well. 

#### PR validation:

Tested with new wfs 320, 321, 322

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

No backport needed.
Would be cool to squeeze this in 13_2_0_pre2 though, if still possible.

### CODE REVIEW

**Comment by mandrenguyen** [comment]
please test workflow 320, 321, 322

**Comment by menglu21** [comment]
+1

**Comment by srimanob** [comment]
Hi @mandrenguyen @menglu21 
Just to confirm as the config of GEN is also changed. Does this need to port back to 13_0 as the plan is to use that series for the GEN-SIM. Thx.

**Comment by srimanob** [comment]
+Upgrade

**Comment by mandrenguyen** [comment]
@srimanob Good point, I'll backport after this is merged.

**Comment by sunilUIET** [comment]
+pdmv

**Comment by rappoccio** [comment]
+1

**Pull request merged**
