### PR TITLE
Updates to the SiPM-on-tile and Si sensor digitization (end-of-life/realistic startup)

### PR DESCRIPTION
**Pull request by pfs**
#### PR description:

This PR contains changes in the emulation of realistic conditions for startup and end-of-life scenarios in HGCAL.

* The bulk of the changes affect the emulation of the SiPM-on-tile sensors. The code used to provide the expected signal, noise, etc. conditions has been refurbished so that it's configured in a way similar to the one used for the Si sensors. Different effects/scalings can be turned on/off by enabling bits in the so called doseMapAlgo in the configuration file. In addition the usage of different SiPM areas is now put in practice when generating events (before it was disabled). These changes enable the generation full realistic scenarios but also scenarios at fixed S/N

* For Si sensors, the pool of conditions is enlarged to encompass the latest measurements of leakage current and charge collection efficiency performed at CERN. In order to avoid cluttering the baseline configuration file used for digitization with still another set of arrays of numbers, we have introduced an additional auxiliary file with two methods to provide the numbers for leakage current and CCE corresponding to different scenarios. The parameterization of the CCE has also been updated to avoid kinks in the function and extrapolate smoothly to lower fluences: 1-2% differences are expected in the signal yield. This also leads to some changes in the gain choice, in regions where the MIP peak was expected to be falling outside the "ideal range" (8-16 ADC counts)

Most of these changes affect the SimProducers/HGCalSimAlgos (as provider of the expected signal, noise and operation parameters, i.e. gain) and SimProducers/HGCalSimProducers (as consumer of these values).
The RecoLocalCalo/HGCalRecProducers is also affected due to the introduction of two new parameters used to model the SiPM-on-tile noise. This latter change has been done by @felicepantaleo 

#### PR validation:

The impact on standard workflows is expected to be null as these effects are disabled by default in the vanilla productions.
As such we have validated this PR with:
* standalone production of single muon samples: results presented in
   * https://indico.cern.ch/event/1068378/#7-sipms-in-simulation : slides 8-13 
   * https://indico.cern.ch/event/1079462/#6-sipm-on-tile-calibration-upd  : slides 8,9
* the hgcal dose map validation analyzers under SimProducers/HGCalSimAlgos
* DIGIS produced by runTheMatrix.py -w upgrade -l 23234.103

A summary of the validation studies for the last two is made in the following slides: [hgcal_prsipmontile_dev_2021Oct21.pdf](https://github.com/cms-sw/cmssw/files/7388256/hgcal_prsipmontile_dev_2021Oct21.pdf)

### CODE REVIEW

**Comment by rovere** [comment]
@bsunanda it is my understanding that the reference version is dynamically computed every time.
@srimanob could you please confirm that?

**Comment by bsunanda** [comment]
I thought it should be like that. If changes in SimAlgos, SimProducer and RecAlgo can change SimHit I doubt that very much

**Comment by pfs** [comment]
@rovere @bsunanda running locally i don't see any difference in SimHits but I realized there is indeed a difference introduced by this PR at digi-level (final thresold-related)  for wf  23234.0 i'm working on it. More news soon.

**Comment by pfs** [comment]
@cmsbuild please test

**Comment by pfs** [comment]
I managed to reproduce the changes observed in the validation locally
starting from CMSSW_12_1_0_pre4 and running the 23234.0 workflow given as example by @rovere.

The changes were in fact were intentional, but I forgot to document and was caught by suprise. 
The changes result from changing a parameter in the hgcalDigitizer_cfi.py.  I had increased the vanilla noise in the SiPM-on-tile section to MIP/7 (before was MIP/100). 

As this change is not needed for the moment in workflows using the vanilla digitization I reverted back to MIP/100 - [link](https://github.com/cms-sw/cmssw/pull/35763/files#diff-fe4c20f743a4224d4789f02bf0581e070e0e85852969f2aec97fd0a92ea4eb9aR42)

Locally I have good agreement between SimHits, Digis and RecHits, hopefully cmsbuild will show the same.

| SimHit   |     Digi      |  RecHit  |
|----------|:-------------:|------:|
|hebEnSim|hebEnDigi|hebEnRec|

**Comment by pfs** [comment]
Hello @srimanob @rovere @bsunanda I think the latest round of comparisons shows that the baseline is re-established. How do you want to proceed? Do i need to rebase this PR? thanks

**Comment by civanch** [comment]
+1

I do not think that rebase is needed.

**Comment by slava77** [comment]
+reconstruction

for https://github.com/cms-sw/cmssw/pull/35763	aeed3f6 
- code changes in reco are somewhat trivial at this point: new parameters are added in HGCalCLUEAlgo.h, apparently to keep the values available in sync with the emulation/sim side (the parameters are not used directly in reco now)
- jenkins tests pass and comparisons with the baseline show no (relevant) differences

**Comment by rovere** [comment]
@pfs can you try to +1 this PR yourself? just to check you "have the powers" :D

**Comment by pfs** [comment]
In the following I'll abuse my powers by the request of @rovere :)

**Comment by pfs** [comment]
+1

**Comment by pfs** [comment]
It seems to work, although maybe the mechanism should be "exclude from the list of approvers in case the submitter of the PR is in it"

**Comment by pfs** [comment]
Hello, can the remaining approvals (upgrade and orp) be given so that this PR is merged. Thanks!

**Comment by srimanob** [comment]
+Upgrade

**Comment by qliphy** [comment]
+1

**Comment by pfs** [comment]
thank you for all the help!

**Pull request merged**
