### PR TITLE
Introduce variant of `pp_on_PbPb` era for 2023

### PR DESCRIPTION
**Pull request by mandrenguyen**
#### PR description:

In #41368 the `Run3` era was split into `Run3` and `Run3_2023`.
We extend this split to the heavy ion era:  Run_pp_on_PbPb and Run_pp_on_PbPb_approxSiStripClusters by introducing 2023 variants. 

#### PR validation:

Tested with 160.  Other affected workflows are 160.02, 160.03, 160.1, 160.2, 160.3, 160.4

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

No backport will be needed.

>

### CODE REVIEW

**Comment by mandrenguyen** [comment]
please test workflow  160, 160.02, 160.03, 160.1

**Comment by mandrenguyen** [comment]
please test
let's try again

**Comment by mandrenguyen** [comment]
please test

**Comment by mandrenguyen** [comment]
@cms-sw/pdmv-l2 Does this look ok for you?

**Comment by srimanob** [comment]
+Upgrade

**Comment by perrotta** [comment]
+1

**Pull request merged**
