### PR TITLE
Drop wrong enum.

### PR DESCRIPTION
**Pull request by ktf**
As suggested in:

https://hypernews.cern.ch/HyperNews/CMS/get/recoDevelopment/1327/1/2.html

### CODE REVIEW

**Comment by ktf** [comment]
@fwyzard

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by mommsen** [comment]
+1

**Comment by cvuosalo** [comment]
+1

For #7731 5b9bd55790feadd21f2398f4b011fb5d773d5503

An obsolete, unused enum definition is deleted by this PR. Jenkins cleanly compiles the code, showing that the enum is indeed unused. No differences from the baseline can be caused by this change. The Jenkins results in validateJR do show some differences, but they are due to some flaw in the Jenkins testing process that has included some other PRs in the test.

**Pull request merged**
