### PR TITLE
[130X] use qScale in charge reweighting

### PR DESCRIPTION
**Pull request by tvami**
#### PR description:

See https://github.com/cms-sw/cmssw/pull/41623

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport of https://github.com/cms-sw/cmssw/pull/41623

### CODE REVIEW

**Comment by tvami** [comment]
backport of https://github.com/cms-sw/cmssw/pull/41623

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by perrotta** [comment]
hold
- I don't think this low level simulation change, even if correct, can be applied to a release from which the production of simulation samples was already started

**Comment by perrotta** [comment]
Thank you Marco. If the Run3 MC production haven't started yet with 13_0_X this can be merged, indeed.
Still waiting for a signature from @cms-sw/simulation-l2 though (also needed for #41719, #41720, #41721 by the way...)

**Comment by jordan-martins** [comment]
Hi all,
Just to confirm: 130X MC prod is for PAG. The prediction is to start in June. So this PR should get in. As said in our PPD Coord. gDoc, we would like to have validation for this, though it would be hard to isolate it.
Best,
PPD

**Comment by perrotta** [comment]
unhold
- Thank you @jordan-martins for confirmation

**Comment by civanch** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
