### PR TITLE
Moving HLT:PRef to 2017 pp Ref menu (94X)

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
Moving HLT:PRef to 2017 pp Ref menu (94X)
Based on CMSSW_9_4_7
Needed for MC production

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by fabiocos** [comment]
@Martin-Grunewald @franzoni @klute do I understand correctly that this change is effectively modifying the HLT in simulation compared to the existing production? Would not this mean breaking backward compatibility of physics content?

**Comment by Martin-Grunewald** [comment]
@fabiocos 
The new HLT:PRef menu is the menu used in 2017 for the 5 TeV pp reference run. It is separate from any other standard data taking (pp, HI, ...); as far as I know the old one has not been used in any MC production for a long time (it dates back to 2015), so there is no breakage. In fact the update in this PR is requested for a planned MC production with the 2017 5 TeV pp ref menu which this PR updates to.

**Comment by fabiocos** [comment]
+1

**Comment by gsfs** [comment]
Confirming that no official MC was run with the previous version of the HLT:PRef menu in 94X and that we are eagerly awaiting a new CMSSW_9_4_X release with this PR included so that official MC can begin for the 2017G pp run at 5 TeV.

**Pull request merged**
