### PR TITLE
L1 t dqm offline stage2 cmssw 9 0 x

### PR DESCRIPTION
**Pull request by z4027163**
This supersedes #16639.

### CODE REVIEW

**Comment by vanbesien** [comment]
Hi @z4027163, who are you?
Understand that we are not triggered to review PRs by anonymous people.

Also, please follow the guidelines from Dmitrijus https://twiki.cern.ch/twiki/bin/view/CMS/DQMGithubGuide
Most specifically: https://twiki.cern.ch/twiki/bin/view/CMS/DQMGithubGuide#2_Fill_in_the_proper_description

Thanks

**Comment by z4027163** [comment]
Hi @vanbesien 
I am Zhangqier Wang. Sorry I didn't put my information in my github account, now it's updated.
I am currently working with Chris in l1t DQMOffline group, and this pull request resolves the conflicts in #16639 .

**Comment by vanbesien** [comment]
Hey. No problem, I noted it in our address book. You are already known to us as one of thte L1T validation code developers. There are many Chris' working at CMS, but I assume the Chris you're working with it Chris Brainerd.
We have multiple PRs for L1T going on at the moment, so for your part of the work, make sure you communicate well with Pierluigi (L1T) and Dmitrijus (DQM) about when your code is stable and you want us to start reviewing. Also follow the guidelines from Dmitrijus: https://twiki.cern.ch/twiki/bin/view/CMS/DQMGithubGuide so that we have some context.

For the release schedule, see the documentation from release management:
https://twiki.cern.ch/twiki/bin/view/CMS/ReleaseSchedule
I see that this PR is for 9_0 and cannot find any reference to 9_1. Keep in mind that for the moment all development should happen against 9_1 and should then be backported to 9_0 if needed.

**Comment by davidlange6** [comment]
Closing PR. CMSSW_9_0_X development has completed (CMSSW_9_2_X is for data taking)

**Pull request closed without merging**
