### PR TITLE
Gen-related Fix addressing rel-Val failure: Updated gridpack that fixes errors encountered in WF 555.0

### PR DESCRIPTION
**Pull request by Saptaparna**
Updated gridpack that fixes errors encountered in WF 555.0

### CODE REVIEW

**Comment by Saptaparna** [comment]
It is sufficient to test only WF 555.

**Comment by Saptaparna** [comment]
@alberto-sanchez This PR looks fine, right?

**Comment by alberto-sanchez** [comment]
@Saptaparna Yes, that looks fine.

**Comment by alberto-sanchez** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Pull request merged**
