### PR TITLE
MTD geometry: update tests for DD4hep

### PR DESCRIPTION
**Pull request by fabiocos**
#### PR description:

This PR contains a collection of updates to support the validation of DD4hep in standard workflows, beyond the pure dump of geometry objects:

- update and add mtd-devoted DD4hep ideal configurations based now on the complete ones, commenting all subdetectors but MTD and using an ad-hoc empty tracker mother volume;

- update the DDD ideal geometry dump, to get back namespaces in the path dump (for easier comparison with DD4hep);

- add a customization fragment to ```SimG4Core/PrintGeomInfo``` to easily use in any configuration the ```PrintGeomInfo``` class (the existing code is more an ad-hoc standalone configuration).

#### PR validation:

By manually adapting the existing DD4hep test workflows to use the MTD-only geometry, the step1 may run, cross MTD (as verified with ```SteppingVerbosity```) and produce SimHits within MTD in MtdSD, as visualized with ```runSimHitCaloHitDumper_cfg.py```. 

The issues causing crashes within step1 for Phase2 test workflows are not due to MTD according to this check, they come from the geometry building in ```DD4hep_DDG4Builder``` when the whole configuration is used.

### CODE REVIEW

**Comment by fabiocos** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by fabiocos** [comment]
@kpedro88 @silviodonato @qliphy do you see a problem with this PR?

**Comment by kpedro88** [comment]
@fabiocos is it necessary to retain non-MTD subdetectors as commented-out lines in the xml, rather than removing them completely?

**Comment by fabiocos** [comment]
@kpedro88 this is for simplicity to compare in a straightforward way with the original from which this is derived. It is not strictly speaking necessary, it makes the comparison a bit simpler, and as it is a test configuration that will go as soon as dd4hep migration is completed I do not think it should create problems

**Comment by kpedro88** [comment]
+upgrade

**Comment by silviodonato** [comment]
+1

**Pull request merged**
