### PR TITLE
Move DeepCore workflow to TTbar (existing GEN-SIM files)

### PR DESCRIPTION
**Pull request by silviodonato**
This PR is a temporary patch of the workflow introduced with #32222 , fixing issue #32543.
The `/RelValQCD_Pt_1800_2400_14/CMSSW_11_2_0_pre6-112X_mcRun3_2021_realistic_v7-v1/GEN-SIM` dataset does not exist. This PR move the workflow to a `TTbar` sample that is already used in other 2021 worflows.

```
[sdonato@lxplus705 src]$ runTheMatrix.py --showMatrix| grep seed
11634.17 2021_seedingDeepCore+TTbar_14TeV_TuneCP5_GenSim+Digi+Reco+HARVEST
```

### CODE REVIEW

**Comment by silviodonato** [comment]
please test

**Comment by silviodonato** [comment]
cc @vberta @mtosi

**Comment by kpedro88** [comment]
+upgrade

**Comment by silviodonato** [comment]
merge

**Pull request merged**
