### PR TITLE
Phase2 Tracker: fixed geometries T33/T35

### PR DESCRIPTION
**Pull request by bartosik-hep**
#### PR description:

Several bugs in Phase2 Tracker geometries `T33` and `T35` have been fixed:
 - 2 versions of the overlap fix introduced manually in #42951 replaced by the correct one from `tkLayout`
 - fixed wrong material budget in the dead area of split-sensor PXB modules

Consistency between the `CMSSW` and `tkLayout` implementations is now restored.

Relocated the overlap-checking script to the right location for being used in future geometry validations

#### PR validation:

 - Relevant packages compile
 - Four-muon workflows with geometry `D102`  run without issues

### CODE REVIEW

**Comment by emiglior** [comment]
@emiglior adding myself as observer

**Comment by srimanob** [comment]
test parameters:
- workflows = 26434.0
- relvals_opt = --what cleanedupgrade,standard,highstats,pileup,generator,extendedgen,production,identity,ged,machine,premix,nano,gpu,2017,2026

**Comment by srimanob** [comment]
@cmsbuild please test

**Comment by srimanob** [comment]
Hi @civanch @bsunanda 
Do you expect the presentation at SIM meeting before merging? Thx.

**Comment by bartosik-hep** [comment]
I've also noticed that the functionality checking overlaps already exists in [`SimG4Core/PrintGeomInfo/test/python
/g4OverlapCheck2026DDD_cfg.py`](https://github.com/cms-sw/cmssw/blob/master/SimG4Core/PrintGeomInfo/test/python/g4OverlapCheck2026DDD_cfg.py)
So it might better worthwhile to remove it from this package, as it was initially introduced here for demonstration purposes.

**Comment by bsunanda** [comment]
The purpose of the final overlap check is done in SimG4Core/PrintGeomzInfo with the chi files in Geometrtry/CMSCommonData. If you want to test overlaps in chi files in subdettector geometry you can jeep the python file there. It is up to the user

**Comment by bsunanda** [comment]
+geometry

**Comment by bartosik-hep** [comment]
Ok, then let's keep it as is and merge the PR

**Comment by bsunanda** [comment]
I checked both the requirements from earlier versions: overlap and Tracker boundary. Both are satisfied. Please approve this PR and let this be merged

**Comment by srimanob** [comment]
+Upgrade

**Comment by rappoccio** [comment]
+1

**Pull request merged**
