### PR TITLE
Protect L1T producers against ME0 hits

### PR DESCRIPTION
**Pull request by dildick**
#### PR description:

Coincidence pads nor pad clusters will be built for ME0. This PR prevents two L1T producers from using ME0 digis. This is done in preparation of the merger of GEM and ME0.

#### PR validation:

I ran WF 22034.0 successfully. 

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

@watson-ij @jshlee

### CODE REVIEW

**Comment by silviodonato** [comment]
Kind reminder @rekovic (this change is rather small)

**Comment by rekovic** [comment]
+1

**Comment by jshlee** [comment]
@dildick protecting for the 16 eta partitions would be handy too

**Comment by dildick** [comment]
@jshlee Idd. But I would put that in a different PR.

**Comment by silviodonato** [comment]
+1

**Pull request merged**
