### PR TITLE
Run3-gem62F Use of alternative ESGetToken initialization for DDD/DD4Hep in Muon/HGCal

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Use of alternative ESGetToken initialization for DDD/DD4Hep in Muon/HGCal

#### PR validation:

Use runTheMatrix test workflows

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cvuosalo Please see this PR

**Comment by civanch** [comment]
@bsunanda, @cvuosalo  - this PR implements what we need.

**Comment by srimanob** [comment]
@civanch @bsunanda @ianna 

Why not include Tracker also,
https://github.com/cms-sw/cmssw/blob/master/Geometry/TrackerGeometryBuilder/plugins/TrackerParametersESModule.cc#L43-L45 ?

Should this if be applied for all subsystems?

**Comment by civanch** [comment]
@srimanob , you are right, we should do that.

**Comment by bsunanda** [comment]
Done that - please see #34249. But this does not cause the issue Carl is investigating. It is access statement or use of ESGetToken which cause this
________________________________

**Comment by srimanob** [comment]
Thanks @bsunanda , should this PR be signed as it, I assume.

Looking around, this is what I can see from master:
- https://github.com/cms-sw/cmssw/blob/master/Geometry/HcalTestBeamData/plugins/HcalTB06BeamParametersESModule.cc#L30-L36
- https://github.com/cms-sw/cmssw/blob/master/Geometry/HcalTestBeamData/plugins/HcalTB02ParametersESModule.cc#L30-L35
- https://github.com/cms-sw/cmssw/blob/master/Geometry/HcalCommonData/plugins/HcalSimParametersESModule.cc#L33-L37
- https://github.com/cms-sw/cmssw/blob/master/Geometry/HcalCommonData/plugins/HcalParametersESModule.cc#L33-L37

**Comment by civanch** [comment]
+1

**Comment by srimanob** [comment]
Hi @bsunanda @civanch @cvuosalo 
I see that part of the code is implemented in https://github.com/cms-sw/cmssw/pull/34219.
Do you want to merge them together in https://github.com/cms-sw/cmssw/pull/34219, or you prefer to merge this first? I am happy to sign, just to confirm for the plan to avoid confusion. Thanks.

**Comment by civanch** [comment]
@srimanob , both are needed. I guess Sunanda introduce correct handling of access to the CompactView one by one. Hope, that most of places are identified, if not next PR(s) will follow.

**Comment by srimanob** [comment]
@civanch 
I mean I see the same change in `Geometry/MuonNumbering/plugins/MuonGeometryConstantsESModule.cc` on both PRs. If we merge this first, @cvuosalo needs to wait until it goes to the next IB, then remove it from his PR, https://github.com/cms-sw/cmssw/pull/34219

**Comment by civanch** [comment]
@srimanob , @cvuosalo , sorry, I see the problem now. In this PR we have HGCal + muons, in #34219 - muons + several other things. Likely this one as more simple should be merged first.

**Comment by srimanob** [comment]
+Upgrade

As agreed with @civanch, this is the PR to merge for adapting on how to call DDD/DD4Hep. This is together with https://github.com/cms-sw/cmssw/pull/34249 which is merged already. Then https://github.com/cms-sw/cmssw/pull/34219 can adapt to them.

**Comment by qliphy** [comment]
+1

**Pull request merged**
