### PR TITLE
GEM Online DQM client fix

### PR DESCRIPTION
**Pull request by hyunyong**
GEM online DQM client fix and index bug fix in DQM module.
@jshlee @threus

### CODE REVIEW

**Comment by jfernan2** [comment]
+1

**Comment by smuzaffar** [comment]
please test
there were issues with eos earlier

**Comment by fabiocos** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by fabiocos** [comment]
+1

fix for online DQM

**Pull request merged**
