### PR TITLE
Run3-sim149 Modify the cfg files in SimG4Core/PrintGeomInfo to get material information from Run3 and Phase2 scenarios

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Modify the cfg files in SimG4Core/PrintGeomInfo to get material information from Run3 and Phase2 scenarios

#### PR validation:

Use the configuration scripts to obtain information from Run3 and Phase2 scenarios

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Pull request merged**
