### PR TITLE
HIN High-pT trigger DQM for 80X (CMSHLT-1078)

### PR DESCRIPTION
**Pull request by FHead**
This PR is the 80X backport of #16284.  The DQM setup for the monitoring of the trigger paths requested in https://its.cern.ch/jira/browse/CMSHLT-1078 is asked for integration. No C++ code change is proposed, we require only python level changes.

### CODE REVIEW

**Comment by dmitrijus** [comment]
+1

**Comment by dmitrijus** [comment]
hold
I signed it too quickly, why is it this change so much bigger than the one in 81x? (337 additions vs 153)
My suspicion is that there was a PR in 80x which was missed, I am not sure how to proceed.

If you say that you want this merged, I will un-hold it.

**Comment by FHead** [comment]
Hello, yes, there was a missed PR still open (https://github.com/cms-sw/cmssw/pull/15968).  This one supersedes the old PR.  I would propose to merge this one and discard the old PR.

**Comment by FHead** [comment]
Can we rerun the tests?  The DAS error is probably temporary.

**Comment by FHead** [comment]
Hi @dmitrijus, could you advice on what additional information you need to proceed?  Thank you.

**Comment by dmitrijus** [comment]
unhold

Ah, I see.

**Comment by dmitrijus** [comment]
This is a backport of two PRs from 81x: https://github.com/cms-sw/cmssw/pull/15967  https://github.com/cms-sw/cmssw/pull/16284

**Comment by dmitrijus** [comment]
please test

**Comment by dmitrijus** [comment]
I have added this PR to https://twiki.cern.ch/twiki/bin/view/CMS/DQMHeavyIon2016 to make our (DQM) life easier. Please check - if you there are any PRs which are missing and needed for HI, please add them to the list.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
