### PR TITLE
Track cuts redone backport

### PR DESCRIPTION
**Pull request by fioriNTU**
Backporting #19428 as requested by @threus

### CODE REVIEW

**Comment by dmitrijus** [comment]
+1

**Comment by dmitrijus** [comment]
thanks!

**Comment by davidlange6** [comment]
hi @fioriNTU - could you rebase this? Thanks.

**Comment by fioriNTU** [comment]
@davidlange6 sorry for the late reply, I overlooked this before. To what release should I rebase?

**Comment by boudoul** [comment]
hi @fioriNTU , rebase with the last 92X IB thanks

**Comment by dmitrijus** [comment]
+1

**Comment by fioriNTU** [comment]
@davidlange6 can this be merged?

**Comment by davidlange6** [comment]
+1

**Pull request merged**
