### PR TITLE
Phase-2 L1T: updated correlator layer 1 e/gamma sorter [master]

### PR DESCRIPTION
**Pull request by gpetruc**
#### PR description:

This PR implements a new sorter of e/gamma objects based on iterative merge-sort, to be used in the barrel part of the correlator layer 1. 
Currently in CMSSW both the barrel and the endcaps were configured to use the sorter based on iterative insertion sort, but in the barrel that sorter can't be implemented in firmware as there aren't enough clock cycles to sort all objects.

From a CMSSW point of view the only change this PR may make in the output is that objects with the same p<sub>T</sub> may end up in different order in the output collection.

The corresponding PR to cms-l1t-offline is https://github.com/cms-l1t-offline/cmssw/pull/1129 for @aloeliger and @epalencia 

#### PR validation:

In this branch, beyond the obvious `scram b code-format && scram b code-checks && scram b runtests` it was tested with matrix workflow 23234.0

In CMSSW_12_5_X, this was validated comparing against the previous sorter and against firmware implementation of this sorting.

### CODE REVIEW

**Comment by gpetruc** [comment]
please test

**Comment by gpetruc** [comment]
Rebased after the merging of #41290 and https://github.com/cms-data/L1Trigger-Phase2L1ParticleFlow/pull/6, tested on [CMSSW_13_2_X_2023-05-20-1100](https://github.com/cms-sw/cmssw/releases/tag/CMSSW_13_2_X_2023-05-20-1100)

**Comment by gpetruc** [comment]
please test

**Comment by gpetruc** [comment]
Hi,

Anybody willing to review this?
(I'm trying to avoid sending you large PRs for the correlator but that can work only if they get integrated frequently enough)

**Comment by aloeliger** [comment]
@gpetruc My apologies, I will try to make time to take a look at this today.

**Comment by AdrianoDee** [comment]
+upgrade

**Comment by AdrianoDee** [comment]
please test

**Comment by aloeliger** [comment]
@gpetruc Good from my end, you write better c++ than I do. I'll wait to see the test results then I'll sign.

**Comment by aloeliger** [comment]
+l1

**Pull request merged**
