### PR TITLE
HCAL: TDC simulation fix

### PR DESCRIPTION
**Pull request by lwang046**
#### PR description:

This PR is a fix to the Hcal DQM issue in https://github.com/cms-sw/cmssw/issues/29076 which was revealed by https://github.com/cms-sw/cmssw/pull/29035 after change Hcal frame size from 8 to 10. The previous code was hardcoded for 8 TS case in run2. The change adjust the sample size automatically.

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by slava77** [comment]
it would be nice to have this merged soon, assuming this actually fixes the random differences in DQM comparisons

**Comment by abdoulline** [comment]
@civanch @silviodonato   may we get it merged, please?

**Comment by silviodonato** [comment]
@civanch @mdhildreth could you have a look to this PR?

**Comment by silviodonato** [comment]
merge
@civanch @mdhildreth please let me know if you have any comment

**Pull request merged**
