### PR TITLE
fix FlatPU prob.

### PR DESCRIPTION
**Pull request by srimanob**

### CODE REVIEW

**Comment by srimanob** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by slava77** [comment]
this is already in place in 80X by forward-port (or other means)
https://github.com/cms-sw/cmssw/blob/CMSSW_8_0_X/SimGeneral/MixingModule/python/mix_Flat_10_50_25ns_cfi.py
@srimanob  please close the PR

**Comment by davidlange6** [comment]
changes are already in 80x. no need for this one (that I forgot about..)

**Pull request closed without merging**
