### PR TITLE
FastTimerService: add measurement of framework overhead (94x)

### PR DESCRIPTION
**Pull request by fwyzard**
- measure the time spent in the event loop, but outside any module
  - keep track of the threads joining and leaving the TBB global arena

### CODE REVIEW

**Comment by fwyzard** [comment]
backport #21446 21446

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
