### PR TITLE
add TrackerMaps for SiStripDetVOff Payload Inspector

### PR DESCRIPTION
**Pull request by mmusich**
Title says it all - add tracker maps of HV,LV and (HV OR LV) off modules in the `SiStripDetVOff` Payload Inspector. 
@hqucms @dimattia

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by slava77** [comment]
On 8/10/17 7:31 AM, cmsbuild wrote:
> -code-checks
> 
> CMSSW Code checks details:
> 
>   * Logs:
>     https://cmssdt.cern.ch/SDT/jenkins-artifacts/pr-code-checks/PR-20109/9
>   * Jenkins log:
>     https://cmssdt.cern.ch/jenkins/job/run-pr-code-ckecks/9/console
>   * How to reproduce:
> 
> |scram -a slc6_amd64_gcc630 project CMSSW_9_3_X_2017-08-10-1100 cd
> CMSSW_9_3_X_2017-08-10-1100 cmsenv git cms-merge-topic -u 20109 scram
> build code-checks |

The message could be more suggestive.
E.g.
"code check has found code style and quality issues which could be
resolved by applying a patch in
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pr-code-checks/PR-20109/9/git-diff.patch
"
perhaps also add a link to some document that describes our choice of
checks.

**Comment by mmusich** [comment]
pretty fancy tool! patch applied btw

**Comment by davidlange6** [comment]
please test

**Comment by ggovi** [comment]
+1

**Comment by davidlange6** [comment]
merge

**Pull request merged**
