### PR TITLE
Clang sa get param dumper and skip MakerHolder::add

### PR DESCRIPTION
**Pull request by gartung**
skip edm::serviceregistry::ServicesManager::MakerHolder::add

### CODE REVIEW

**Comment by Dr15Jones** [comment]
+1

**Comment by Dr15Jones** [comment]
Please test

**Comment by davidlt** [comment]
This again broke a package on Clang.
```
Utilities/StaticAnalyzers/src/getParamDumper.cpp:38:1: error: control may reach end of non-void function [-Werror,-Wreturn-type]
```
`std::string getArgumentValueString` might hit the end of function without hitting return statement.

Could this get fixed ASAP?

**Comment by ktf** [comment]
@nclopezo @davidlt can you check if there is a way to get clang to do syntax check only and do it for every PR?

**Comment by davidlt** [comment]
There is "-fsyntax-only". It only checks for correctness.
I was to propose testing PRs with Clang as mandatory. Otherwise I need to fix it almost every day probably :/

**Comment by ktf** [comment]
If -fsyntax-only takes a reasonable amount of time to run, I've no 
objections. We cannot afford a full rebuild with clang right now, 
though, so it needs to add, say, 10% max to the current test runtime 
average. Sit with @nclopezo to get it working in jenkins.


> There is "-fsyntax-only". It only checks for correctness.
> I was to propose testing PRs with Clang as mandatory. Otherwise I need 
> to fix it almost every day probably :/

**Comment by gartung** [comment]
https://github.com/cms-sw/cmssw/pull/7694

**Comment by gartung** [comment]
This is a clang compilation warning only. I don't see how this "breaks" all pull requests.

**Comment by davidlt** [comment]
It's an error, not a warnings: `error: control may reach end of non-void function [-Werror,-Wreturn-type]`

**Comment by gartung** [comment]
OK. But how does this "break" all pull requests? It builds with g++ just fine. I submitted a pull request to back out the getParamDumper files.

**Comment by davidlt** [comment]
It breaks compiling CMSSW with Clang. We are finally in a state where full CMSSW compiles with Clang compiler, but it seems that it's being broken quite frequently. I intend to look after Clang builds, because Clang is now used for Conditions serialization and ROOT6. Plus I would prefer to use some tools (sanitizers) and don't wait for backports to GCC.

You call always test your code with Clang:
```
scram b vclean && scram b -v -k -j 12 COMPILER=llvm
```
This would allow you check if code compiles with Clang and potentially find issues the code.

**Comment by gartung** [comment]
Actually is it a warning. You made it an error with -Werror which turns warnings into errors.

**Comment by ktf** [comment]
The warning highlights a real issue with your code. If StTrue is false, the method will return garbage. I'm surprised gcc did not complain.

**Comment by gartung** [comment]
I should have submitted the python script change as a seperate pull request. The getParamDumper is a work in progress. Please use pull https://github.com/cms-sw/cmssw/pull/7694 to back out the addition of getParamDumper .

**Comment by gartung** [comment]
Submitted fix for clang warnings/errors in pull request 
https://github.com/cms-sw/cmssw/pull/7699

**Pull request merged**
