### PR TITLE
Replace a Subtraction Solid with a Union Solid

### PR DESCRIPTION
**Pull request by ianna**
- Replace a problematic shape with an identical one

A new shape is in red, the old one is in blue (note, subtracted wings are not clearly shown due to a precision error):
screenshot 2016-08-31 10 50 22

### CODE REVIEW

**Comment by ianna** [comment]
@ptcox and @civanch - FYI, CMSSW_8_1_pre9_Geant4102 and a transient geometry should be used for validation.

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by davidlange6** [comment]
@ianna - perhaps we should focus first on making these changes for 2017 geometry?

**Comment by ianna** [comment]
@davidlange6 - sure, we can discuss it at sim meeting later today

**Comment by davidlange6** [comment]
@ianna - coming back to this - I think we agreed to just change this in forward looking geometries (2017++). Can you have a look to update the PR?

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by ianna** [comment]
@davidlange6 - done

**Pull request merged**
