### PR TITLE
Fix resolution validation plots after moving ME1a CLCT from ring 4 to ring 1

### PR DESCRIPTION
**Pull request by sifuluo**
#### PR description:

This PR fixes the issue brought about by https://github.com/cms-sw/cmssw/issues/37268
Due to the last PR, the CLCTs in ME1a are having detector information of ring == 1 instead of ring == 4.
The CLCT validation will then misinterpret ME1a CLCTs as ME1b ones.

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by perrotta** [comment]
+1
- Thank you @sifuluo

**Comment by perrotta** [comment]
@sifuluo could you please prepare backport PRs for 12_3_X and 12_2_X, as the original bugged PR was also merged in those two release cycles?

**Pull request merged**
