### PR TITLE
[Backport 140X] DQM: restore Muon POG sequence (and CSC Monitor), revert #46298

### PR DESCRIPTION
**Pull request by fabiocos**
#### PR description:

Effective backport of #46293 to 140X

#### PR validation:

Simple revert of previous to previously running code.

### CODE REVIEW

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
urgent

**Comment by fabiocos** [comment]
big-fix

**Comment by fabiocos** [comment]
bug-fix

**Comment by fabiocos** [comment]
type bugfix

**Comment by antoniovagnerini** [comment]
+1

**Comment by antoniovagnerini** [comment]
backport of https://github.com/cms-sw/cmssw/pull/46293

**Comment by antoniovilela** [comment]
backport of https://github.com/cms-sw/cmssw/pull/46364

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
