### PR TITLE
[14_0_X] backport of 44335 (slimmedMETsNoHF and possible cleanup)

### PR DESCRIPTION
**Pull request by hqucms**
#### PR description:

 - backport of https://github.com/cms-sw/cmssw/pull/44335 by @wajidalikhan 

> * slimmedMETsNoHF collection in MiniAOD  is just MET without considering PF candidates in the HF region
> * Its impact on the MiniAOD size is negligible
> * it clusters a new CHS jet collection (ak4PFJetsCHSNoHF) which is used for its Type-1 correction consuming a non-negligible CPU time
> * No use cases at the moment therefore it can be removed from MiniAOD production workflow

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by hqucms** [comment]
please test

**Comment by jfernan2** [comment]
backport of https://github.com/cms-sw/cmssw/pull/44335

**Comment by hqucms** [comment]
+1

**Comment by mandrenguyen** [comment]
+reconstruction
This is simply removing part of the slimmedMET collection (miniAOD) that is not used. 
This is should therefore be safe for reco for a closed release.

**Comment by rappoccio** [comment]
+1

**Pull request merged**
