### PR TITLE
Clean hcal dqm

### PR DESCRIPTION
**Pull request by deguio**
remove the old HCAL DQM

### CODE REVIEW

**Comment by deguio** [comment]
@vkhristenko

**Comment by vanbesien** [comment]
please test

**Comment by kpedro88** [comment]
@deguio once this PR is merged, you can make a followup PR to https://github.com/cms-sw/cms-bot to remove these packages from categories.py (just to avoid clutter)

**Comment by deguio** [comment]
@kpedro88 
yes I can.

**Comment by kpedro88** [comment]
@dmitrijus, @vanbesien can this also get signed before the ORP?

**Comment by dmitrijus** [comment]
+1

does this merge cleanly with https://github.com/cms-sw/cmssw/pull/15380 ?
Either way, I will push https://github.com/cms-sw/cmssw/pull/15380 at the orp first, before this one.

**Comment by kpedro88** [comment]
@dmitrijus I think this is orthogonal with #15380, but @deguio or @vkhristenko can confirm.

**Comment by kpedro88** [comment]
@dmitrijus please at least mention this one in the ORP, even if you want to point out that the other one should be merged first in case of conflicts

**Comment by dmitrijus** [comment]
hold

@davidlange6 told me to hold it until the big HCAL is merged.

**Comment by deguio** [comment]
@dmitrijus 
fine with me. anyway the two PRs should be orthogonal.
F.

**Comment by kpedro88** [comment]
@dmitrijus #15380 is merged now, can you remove the hold?

**Comment by dmitrijus** [comment]
unhold

**Comment by davidlange6** [comment]
+1

**Comment by deguio** [comment]
@kpedro88 
here we go:
https://github.com/cms-sw/cms-bot/pull/733

F.

**Pull request merged**
