### PR TITLE
DT cosmic reco switch to meantimer

### PR DESCRIPTION
**Pull request by ptraczyk**
This is a fix for #7044, this one commit was missing there. The validation plots attached in that PR reflect the situation WITH this commit.
This completes the migration of offline DT reconstruction to the Meantimer pattern recognition algorithm, the Reconstruction and ReconstructionCosmics seqences now use the same DT algorithm for cosmics.

### CODE REVIEW

**Comment by ptraczyk** [comment]
but thats not me, the same error is present without my commit

**Comment by slava77** [comment]
Piotr, please update the subject of the PR to indicate it's for DT cosmic segment reco
(cfg file fix) is not clear enough for self-documentation

**Comment by ptraczyk** [comment]
ok, I made it more explicit

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/7177	a7990f5
tested in CMSSW_7_4_0_pre3 (test area sign487)

As expected, changes affect only the cosmic scenario.
Changes in monitored quantities start from dtSegments: nDOF 
Only a few barrel muon distributions are visibly changing, (other monitored quantities are not changing shapes in a noticeable way): STA chi2, time uncertainties

CPU consumed by dt4DSegments   goes up from   4.46094 ms/ev to  49.2779 ms/ev, based on wf 4.22 RunCosmics2011A, from 160960 (10K events run). This is a 10% increase in reco step. Shouldn't be a big deal here (the algorithm is more complex).

(thank you for changing the subject to the more descriptive).

below are some plots from 7.0 (cosmic MC)
dt4DSegments chi2

all_sign488vsorighistat_cosmicswf7p0c_mindtchamberiddtrecsegment4dsownedrangemap_dt4dsegments__reco_obj_collection__data__chi2 99_99

all_sign488vsorighistat_cosmicswf7p0c_recomuons_muons__reco_obj_time_timeatipinouterr

all_sign488vsorighistat_cosmicswf7p0c_recomuons_muons__reco_obj_time_timeatipinouterr


some from data (wf 4.22)
about 3% of muons get "reassigned" to be in the barrel instead of endcap
wf4p22_sta_chi2
wf4p22_sta_chi2_ecap
wf4p22_meseed_theta

**Pull request merged**
