### PR TITLE
Ignore EDFilters in the reconstruction_step path

### PR DESCRIPTION
**Pull request by perrotta**
This is meant to solve the github issue #23377 ( @Dr15Jones )

The following filters were identified in the sequences that end up in the reconstruction_step path
- electronsWithPresel
- mvaElectrons
- electronsCiCLoose
- pfNoPileUpCandidates
- pfPileUpAllChargedParticles

In order to allow the ```convertToUnscheduled``` function to remove those EDFilters from the Path and put them on the appropriate Task, those modules must be marked with cms.ignore()

When looking at those modules, it turns out that ```electronsWithPresel```, ```electronsCiCLoose```, ```pfNoPileUpCandidates``` and ```pfPileUpAllChargedParticles``` are "true" filters, which are however configured in the reco sequence in order to always pass (result of the filter() function could also be "false" in principle, but it is always "true" with the chosen configurations) -> they can be cms.ignore'd.

On the other hand, ```mvaElectrons``` is a "ElectronIdMVABased" EDFilter which always returns true by construction [1], and produces mvaElectrons -> This can therefore just be moved to become an EDProducer, instead of an EDFIlter.

This PR implements what above. It has been tested running with the short matrix (not all tests have finished yet, but there is no issue in sight so far). No differences at all are expected in the jenkins outputs

[1] https://cmssdt.cern.ch/lxr/source/RecoEgamma/ElectronIdentification/plugins/ElectronIdMVABased.cc#0156

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by Dr15Jones** [comment]
please test

**Comment by perrotta** [comment]
please test
(It times out in step1 of 250202.181, hard to believe that it can be due to this PR: let try once more, and if it happens again I will investigate more deeply)

**Comment by fabiocos** [comment]
@perrotta is the difference in DQM output size entirely due to MessageLogger?

**Comment by perrotta** [comment]
Uhm, good point Fabio.

Looking at the DQM content, I notice that in both the ```MessageLogger/Run summary/Errors/modules_errors``` and ```MessageLogger/Run summary/Warnings/modules_warnings``` plots there are now less bins (i.e. the previous first four bins in the histogram are now missing)

I've no idea how this PR can originate it...

@dmitrijus , could you please give us your advice? The only thing this PR is doing is:
- cms.ignore() a few filters (which do not actually filter) in the reco sequence
- Modify one EDFilter into and EDProducer (that filter was not used for HLT, anyhow)

**Comment by perrotta** [comment]
hold
(in the meanwhile...)

**Comment by Dr15Jones** [comment]
Entries in the ErrorLogHarvester histograms are extremely dependent on the order that the threads decide to run modules. In generally, I strongly suggest ignoring that histogram when looking at differences caused by a pull request.

**Comment by perrotta** [comment]
Thank you @Dr15Jones , that makes sense to me, and I can't envisage any other possible explanation.
I'm going to unhold this PR, but @fabiocos feel free of asking further checks if you think so.

**Comment by perrotta** [comment]
unhold

**Pull request merged**
