### PR TITLE
HLT V4.0 Mercury (92X)

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
HLT V4.0 Mercury (92X).
Based on CMSSW_9_2_13.

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
backport of #20872

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please abort

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by lpernie** [comment]
Please cherrypick this comment to include latest version of autocond with the new GT with new L1T menu (L1Menu_Collisions2017_v4):
https://github.com/lpernie/cmssw/commit/fdbd9e32445b09342813857581568ff3990f06e4

**Comment by Martin-Grunewald** [comment]
We need to delay the L1T v4 GTs and @relval2017 switchover to a later PR.

**Comment by Martin-Grunewald** [comment]
@Dr15Jones 
Could you please sign this backport PR for 92X?
Thanks.

**Comment by Dr15Jones** [comment]
+1

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by Dr15Jones** [comment]
+1
for addOnTests

**Comment by davidlange6** [comment]
+1

**Pull request merged**
