### PR TITLE
python modernize 2to3 tool fix_input

### PR DESCRIPTION
**Pull request by davidlange6**
apply fixes.fix_input tool from python futurize tool

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by fabiocos** [comment]
-1

14:55 cmsdev15 3697> ./calculate_beamwidth.py
beam energy in GeV: 6
Traceback (most recent call last):
  File "./calculate_beamwidth.py", line 19, in <module>
    beam = eval(input("beam energy in GeV: "))
TypeError: eval() arg 1 must be a string or code object

What am I doing wrong here?

**Comment by davidlange6** [comment]
ah - cool.. so the tool creates an interface change. I'll try to understand a better fix.

**Comment by fabiocos** [comment]
@davidlange6 are you planning to update this PR, or should we close it an propose something different later?

**Comment by davidlange6** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Pull request merged**
