### PR TITLE
Use a precision limit for the  formula evaluator test

### LINKED ISSUE #40728: Unit test testCommonToolsUtil failing in CLANG IBs
Hello,

Test `testCommonToolsUtil` is failing at least since `CMSSW_13_0_CLANG_X_2023-02-01-2300`. It asserts with the following error message:
```
checking lazy expression: "overlaps('test')[0].pt" = 2.23607 (reference), 2.23607 (bare), 2.23607 (full)
..F..

testFormulaEvaluator.cc:817:Assertion
Test name: testFormulaEvaluator::checkFormulaEvaluator
assertion failed
- Expression: f.evaluate(emptyV, emptyV) == -(-2.36997 + 0.413917 * std::log(20
8.)) / 208.

Failures !!!
Run: 11   Failure total: 1   Failures: 1   Errors: 0
```

I can reproduce the failure in `cmsdev` machines.
Thanks,
Andrea.

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

This fixes the unit test failure when using clang.

#### PR validation:

The unit test passes now.

fixes #40728

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by clacaputo** [comment]
please test

**Comment by clacaputo** [comment]
+reconstruction

**Comment by perrotta** [comment]
+1

**Pull request merged**
