### PR TITLE
Run3-gem40 Simplify the usage of the cfi files for CSCGeometryBuilder

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Simplify the usage of the cfi and cff files for CSCGeometryBuilder

#### PR validation:

Tested using runTheMatrix.py

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please Test

**Comment by bsunanda** [comment]
@slomeo @watson-ij Please see the changes I made which simplifies adaptation to dd4hep

**Comment by slomeo** [comment]
@bsunanda : please take a look to #30122 now merged

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@slomeo Yes I am making changes on the top of yours

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@smuzaffar Can you please check what could be wrong. All failures claim opening of files failed. Please let me know what I need to do on my side?

**Comment by bsunanda** [comment]
@silviodonato @smuzaffar Can you please check what could be wrong? All failures claim failure in opening of files. Please let me know what I need to do on my side.

**Comment by silviodonato** [comment]
please test
let's try again

**Comment by cvuosalo** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
