### PR TITLE
LLP GenFilter based on transverse displacement and pdgId - backport #37669

### PR DESCRIPTION
**Pull request by Raffaella07**
PR description:
The filter  selects particles based on transverse displacement (by means of a lower and/or upper cut) and pdgIds.
The filter is developed for searches of long lived HNLs in B meson decays (@rmanzoni @pandolf @amlyon)

The filter is included in the /plugins subdirectory of GeneratorInterface/GenFilters .

PR validation:
Filter behavior can be tested in the test subdirectory of GeneratorInterface/GenFilters through the module test_MCLongLivedFilter_cfg.py

Backporting https://github.com/cms-sw/cmssw/pull/37669

### CODE REVIEW

**Comment by amlyon** [comment]
Dear @perrotta, @Saptaparna, 

Here is the backport to 10_2_X of [#37669](https://github.com/cms-sw/cmssw/pull/37669). 

Would it be possible that you review it, and then run the checks? 

The aim would be to merge this PR before the ORP meeting of tomorrow, such that the release can be created in the best delays [1].

Thank you very much for your help!

[1] https://indico.cern.ch/event/1156305/

**Comment by perrotta** [comment]
@Raffaella07 please also remove the update to GeneratorInterface/GenFilters/src/SealModule.cc, which is not needed

When you have done it, could you please prepare the backport for the intermediate releases 10_6_X? 10_6 is the UL release, I imagine that whatever is backported in 10_2 would be eventually needed also in 10_6. Let have it merged in the 10_6_X queue: then even if there is no need for a new release right now, it could enter "for free" at the first occasion

**Comment by Raffaella07** [comment]
Dear @perrotta, 
without the line added in  GeneratorInterface/GenFilters/src/SealModule.cc we end up with this error:
Screenshot 2022-05-09 at 17 14 25
should we include the file in /plugin in some other way? 

After solving this issue, I will prepare the backport for 10_6_X

**Comment by perrotta** [comment]
Indeed, we are missing a BuildFile for the newly created `\plugins` directory

A simpler BuildFile than the one which is in the master (that contaons many more plugins) can be enough. Please try with adding the following BuildFile.xml file in GeneratorInterface/GenFilters/plugins:
```XML
<library name="GeneratorInterfaceGenFiltersPlugins" file="*.cc">
  <use name="FWCore/Framework"/>
  <use name="FWCore/ParameterSet"/>
  <use name="FWCore/Utilities"/>
  <use name="SimDataFormats/GeneratorProducts"/>
  <flags EDM_PLUGIN="1"/>
</library>
```

**Comment by Raffaella07** [comment]
Thanks a lot for the suggestion! I had tried to implement a /plugins/BuildFile.xml but I maybe did not insert all the needed modules. This version works perfectly.

**Comment by perrotta** [comment]
please test

**Comment by Saptaparna** [comment]
+1

**Comment by perrotta** [comment]
All commits have been squashed into a single one, and merged in 12_2_X
@Raffaella07 please prepare also a backport for 10_6 now

**Comment by amlyon** [comment]
Dear @perrotta, thank you for taking care of the merge! 

I also would like to ask if there is anything for us to prepare for the ORP meeting this afternoon, or if it's all in your hands?

**Comment by perrotta** [comment]
> Dear @perrotta, thank you for taking care of the merge!
> 
> I also would like to ask if there is anything for us to prepare for the ORP meeting this afternoon, or if it's all in your hands?

We have already started building 10_2_28_patch1 with this fix. It will be quite likely already completed by the time of the ORP meeting. I expect that someone (either you or the generator contact) will be able to explain to PPD and the other stakholders that will be connected to the meeting what do you intend to do with it, and which are the production plans

**Comment by amlyon** [comment]
> 

Thank you for the info!

**Pull request merged**
