### PR TITLE
[12_3_X] Add new scenario for ECAL ALCANANO and update the unit test

### PR DESCRIPTION
**Pull request by tvami**
#### PR description:

See description at https://github.com/cms-sw/cmssw/pull/37627

#### PR validation:

`scram b runtests` runs

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Backport of https://github.com/cms-sw/cmssw/pull/37627 and https://github.com/cms-sw/cmssw/pull/37668

### CODE REVIEW

**Comment by tvami** [comment]
backport of https://github.com/cms-sw/cmssw/pull/37627

**Comment by tvami** [comment]
assign alca

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
+alca

**Comment by tvami** [comment]
urgent
 * we should not forget to have this in the upcoming 12_3_X

**Comment by perrotta** [comment]
+1

**Pull request merged**
