### PR TITLE
Updated cms::Exception using modern C++

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

- Added format option
- Use concepts to constrain operator<<

#### PR validation:

Code compiles. New unit tests passes.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
@smuzaffar would it be feasible to update our builds to use clang 18?

**Comment by antoniovilela** [comment]
ping (to make bot change milestone)

**Comment by makortel** [comment]
@cmsbuild, please test

We have now clang 18 in the default IB.

**Comment by makortel** [comment]
Comparison differences are related to https://github.com/cms-sw/cmssw/issues/39803, and unit test failure to https://github.com/cms-sw/cmssw/issues/45952

**Comment by makortel** [comment]
ignore tests-rejected with ib-failure

**Comment by makortel** [comment]
+core

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
