### PR TITLE
Hlt tau ref producer update

### PR DESCRIPTION
**Pull request by slehti**
This is the same PR as #13426, but now for cmssw80x

### CODE REVIEW

**Comment by mbluj** [comment]
Hi, just to complete info on this PR. It is meant to fix DQM issue which was a side effect of #13272 which removes obsolete tau discriminants. The effect was understood to be result of a bad logic of tau trigger DQM module which accepted all probes in case of missing discriminant used to select the probes. Code was updated to reject all probes in case of call for a missing discrimiant which should be easy to detect, and a list of discriminants was updated to supported ones. This should revert to behavior very close to the one known before merging  #13272.

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1

**Comment by mbluj** [comment]
Dear All, 
is there anything preventing to merge it to 80X? This is a fix of a dqm issue being a side effect of already merged #13272. 
For reference, a sibling PR for 81X (#13426) is already merged.

**Pull request merged**
