### PR TITLE
Added exception to HepMCValidationHelper

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

Converted a LogError then abort() to be an exception which includes information about the failure.

Related to issue #37169.

#### PR validation:

Code compiles.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
Please test

**Comment by SiewYan** [comment]
+1

**Comment by Saptaparna** [comment]
+1 from me too!

**Comment by jfernan2** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
