### PR TITLE
Add new TimeMemory configuration for minimal report in JobReport

### PR DESCRIPTION
**Pull request by fabiocos**
#### PR description:

A variant of the TimeMemorySummary customisation is provided, to avoid Memory report in the stdout and prevent the long Trigger and Time summary to be reported. Meant to solve the issue with tests within cms-bot, see https://github.com/cms-sw/cms-bot/pull/1122 

The code cleaning by ```scram b code-format-all``` is also provided.

#### PR validation:

Test wf 503 has been run with this customisation, providing the desired result:
```
runTheMatrix.py -l 503.0 --command "--customise Validation/Performance/TimeMemoryJobReport.customiseWithTimeMemoryJobReport -n 100"
```

cmsScimark2 (affected by the code cleaning) also runs and provide output.

### CODE REVIEW

**Comment by fabiocos** [comment]
hold

**Comment by fabiocos** [comment]
waiting for the result of the test of cms-bot...

**Comment by fabiocos** [comment]
please test

**Comment by smuzaffar** [comment]
@fabiocos , do you want to test it stand alone or with cms-bot PR?

**Comment by fabiocos** [comment]
@smuzaffar this test was just to have a clean test passed  here, the real test I would like to have with this PR is in https://github.com/cms-sw/cms-bot/pull/1122#issuecomment-493134274

**Comment by fabiocos** [comment]
unhold

@smuzaffar @Dr15Jones I would like to see the output of the test in the bot, but this should provide what I wanted to have in PR tests (it can be used for other purposes of course). Plus there is the code format cleaning of the Validation/Performance package

**Comment by fabiocos** [comment]
scimark2 is still functional:

```
15:25 cmsdev25 1338> cmsScimark2 
**                                                              **
** SciMark2 Numeric Benchmark, see http://math.nist.gov/scimark **
** for details. (Results can be submitted to pozo@nist.gov)     **
**                                                              **
Using       2.00 seconds min time per kenel.
Composite Score:         1160.69
FFT             Mflops:  1158.96    (N=1024)
SOR             Mflops:   830.58    (100 x 100)
MonteCarlo:     Mflops:   438.26
Sparse matmult  Mflops:  1472.72    (N=1000, nz=5000)
LU              Mflops:  1902.90    (M=100, N=100)
```

**Comment by fabiocos** [comment]
@smuzaffar @davidlange6 looking at Validation/Performance I think there is a lot of very old file put there when I was following simulation (the "performance suite" was written by G. Benelli at that time) but  no more used since ages, apart for a few customization fragments. Could you please confirm that this is not used under the hood in some procedure? Otherwise I might propose some spring cleaning to avoid maintaining useless obsolete stuff that nobody will run...

**Comment by fabiocos** [comment]
@civanch @mdhildreth @bsunanda also from the SIM point of view I doubt there is any recent regular use of most of the scripts in Validation/Performance, am I correct?

**Comment by fabiocos** [comment]
and we are not really using Oval...

**Comment by smuzaffar** [comment]
please test with cms-sw/cms-bot#1122

**Comment by fabiocos** [comment]
@Dr15Jones any objection to have integrated and activated in PR checks by the bot?

**Comment by Dr15Jones** [comment]
No objection

**Comment by fabiocos** [comment]
@Dr15Jones @smuzaffar so could core sign this PR :-) ?

**Comment by smuzaffar** [comment]
+core

**Comment by fabiocos** [comment]
+1

**Pull request merged**
