### PR TITLE
Update 2023 MC GT, VtxSmearing and PU library

### PR DESCRIPTION
**Pull request by francescobrivio**
#### PR description:
This PR updates:
 - The 2023 MC realistic GTs
   - See this [CMSTalk post](https://cms-talk.web.cern.ch/t/mc-call-for-conditions-for-2023-mc/24376/21) for a full list of updates
 - New VtxSmearing for 2023 (`Realistic25ns13p6TeVEarly2023Collision`) included in #41719
 - The 2023 GEN-SIM PU library compatible with the 2023 BeamSpot
   - The samples have been produced by PdmV in [PDMVRELVALS-203](https://its.cern.ch/jira/browse/PDMVRELVALS-203)

GT differences:
 - **phase1_2023_realistic**: https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/131X_mcRun3_2023_realistic_v7/131X_mcRun3_2023_realistic_v8
 - **phase1_2023_cosmics**: https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/131X_mcRun3_2023cosmics_realistic_deco_v7/131X_mcRun3_2023cosmics_realistic_deco_v8

#### PR validation:
Tested with:
`runTheMatrix.py -l 12434.0,12634.99 -j 8`
I will let the bot tests all the other workflows.

#### Backport:
Not a backport, but 13_1_X and 13_0_X will be provided soon

### CODE REVIEW

**Comment by francescobrivio** [comment]
@cmsbuild please test

**Comment by tvami** [comment]
+alca
 * test pass, thousands of diffs, as expected, since we changed several conditions
 * GT diff is consistent with the reqested tags in https://cms-talk.web.cern.ch/t/mc-call-for-conditions-for-2023-mc/24376/21
 * update to HI GT will come in a next PR

**Comment by srimanob** [comment]
Thanks @francescobrivio for the PR.

Note to @cms-sw/pdmv-l2 @cms-sw/alca-l2 
We should also update 2023FS 
+ Update BS in https://github.com/cms-sw/cmssw/blob/master/Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py#L2622

+ Add 2023FS to
https://github.com/cms-sw/cmssw/blob/master/Configuration/PyReleaseValidation/python/relval_steps.py#L3994-L4009

If @cms-sw/pdmv-l2 can generate MinBias and TTbar with new BS, I can make a PR later to final this update on FastSim. Thx.

**Comment by srimanob** [comment]
+Upgrade

Update for FullSim 2023. FastSim to be followed up.

**Comment by sunilUIET** [comment]
+pdmv

**Comment by perrotta** [comment]
+1

**Comment by sunilUIET** [comment]
> Thanks @francescobrivio for the PR.
> 
> Note to @cms-sw/pdmv-l2 @cms-sw/alca-l2 We should also update 2023FS
> 
> * Update BS in https://github.com/cms-sw/cmssw/blob/master/Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py#L2622
> * Add 2023FS to
>   https://github.com/cms-sw/cmssw/blob/master/Configuration/PyReleaseValidation/python/relval_steps.py#L3994-L4009
> 
> If @cms-sw/pdmv-l2 can generate MinBias and TTbar with new BS, I can make a PR later to final this update on FastSim. Thx.

Hi @srimanob , To be sure :). FastSim WFs are required in 12_4_14 with only a change of beamspot to Realistic25ns13p6TeVEarly2023Collision. Right?

**Comment by srimanob** [comment]
Why 12_4? 
I propose to have in master, then backport to 13_0. So we can organize the FastSim-FullSim 2023 in the same release.

**Comment by sunilUIET** [comment]
> Why 12_4? I propose to have in master, then backport to 13_0. So we can organize the FastSim-FullSim 2023 in the same release.

@srimanob Ok thanks! We will produce MinBias and TTbar with Realistic25ns13p6TeVEarly2023Collision in 13_2_0_pre3

**Pull request merged**
