### PR TITLE
Phase1 customs

### PR DESCRIPTION
**Pull request by dkotlins**
Update pixel phase 1 condition in the customization file.
Delete the gain calibration fake conditions, the real gains should be used.
Move the pull request #13228 made from CMSSW_800_pre4 to pre6.

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by ggovi** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
cleaning up the 80x queue a bit - this is already in 81x and that is where its needed.

**Pull request closed without merging**
