### PR TITLE
TTI (Track Trigger Integration) descope scenarios

### PR DESCRIPTION
**Pull request by boudoul**
Propagating the Tracker Descope scenarios (defined in the PR #8008) into the TTI scenario.
I didn't define anything in runthematrix, as this is not intended (for the moment) to be used in any central production but  for track trigger studies - It should not interfere with anything.

### CODE REVIEW

**Comment by degano** [comment]
please test

**Comment by mark-grimes** [comment]
There are reports of database read problems, so I wouldn't worry too much about the "timed out after 2 hours", particular since this doesn't touch the standard tests.
I'm in the process of privately testing 12800 (normal TTI with muons) but with TTI replaced with TTILHCC in the relevant places.  I'll report when done.

**Comment by mark-grimes** [comment]
merge

Tried the aforementioned tests and everything went fine.  No idea about physics results though.
Get a few printouts of

    Warning did not find digi

but that happens in the bare 12800 test.  It's been a while since I've looked through the logs for that one.

**Comment by boudoul** [comment]
thanks Mark! If I remember correctly, I asked in the past to remove the message ' did not find digi ' as it is supposed to be harmless - But seems to be still there - Maybe we need a confirmation that it is really harmless and then eventually remove it : @EmanuelPerez ? @aryd?  - This message is coming from this code [1] ; can you comment on this? Thanks.

[1] https://github.com/cms-sw/cmssw/blob/CMSSW_6_2_X_SLHC/L1Trigger/TrackFindingTracklet/interface/slhcevent.hh#L1670

**Pull request merged**
