### PR TITLE
Add particle list files and update decay files for BPH (Bmm)

### PR DESCRIPTION
**Pull request by heppye**
Add particle list files and update decay files for BPH (Bmm)

### CODE REVIEW

**Comment by covarell** [comment]
Hi Ye,

...V4.dec implies that we need V1, V2, V3 AND V4 in the same release. Is it really the case?
If so, maybe a better naming would help future users to understand the differences between the four versions.

**Comment by heppye** [comment]
@covarell , it is for the usage of documentation as V3 has already been used for runIIWinter15GS official generation.  V4 have pdg2015 bs mixing parameters updates comparing to V3 (made by Andrey) and it should be the recent recommended one.V2 is for pythia6 and have a angular distribution update comparing to V1. V1V2 might could be dropped. Do you have a better suggestion for the naming?

**Comment by covarell** [comment]
Ok, could you just drop V1 and V2 in this commit?

**Comment by covarell** [comment]
+1

**Comment by covarell** [comment]
The same must be done for 80X commit

**Comment by heppye** [comment]
@covarell , many thanks for the prompt response. Same commits also done to https://github.com/cms-sw/cmssw/pull/12683/files.

**Comment by davidlange6** [comment]
sounds like there is no need for V3 to change to V4 - just change V3. The release version will then tell you which version of the file has been used (as is true for the rest of CMSSW)

**Comment by heppye** [comment]
@davidlange6 , for future studies, it might not be easy to notice those changes in the decay file. However, I might commit the changes if it is ok to you.

**Comment by heppye** [comment]
@davidlange6 , done. @covarell , could you please check again? thanks.

**Comment by heppye** [comment]
@cmsbuild , the local tests of those patches are fine.  Could it be possible that 1001.0 step2 is not relevant  to this PR?

**Comment by covarell** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
