### PR TITLE
L1 nano: 13_0_X backport

### PR DESCRIPTION
**Pull request by Sam-Harper**
#### PR description:

This PR is a backport of https://github.com/cms-sw/cmssw/pull/40663 which  adds L1 information to NanoAOD. 

It is necessary to backport to be able to run as prompt nano this year. 

#### PR validation:

Validation is covered in the original PR
https://github.com/cms-sw/cmssw/pull/40663  (its the exact same branch, merges in both 13_0_X and 13_1_X)

### CODE REVIEW

**Comment by swertz** [comment]
enable nano

**Comment by swertz** [comment]
please test

**Comment by swertz** [comment]
+xpog

Vertbatim backport; needed for prompt data NanoV12

**Comment by srimanob** [comment]
+Upgrade

**Comment by kskovpen** [comment]
+pdmv

**Comment by perrotta** [comment]
+1

**Pull request merged**
