### PR TITLE
update PFJetID for RunII, add ak8 MiniAOD monitoring, adopt ak4CHS JEC for type1 MET

### PR DESCRIPTION
**Pull request by webermat**
monitor substructure variables in JetMET DQM for ak8 jets. update PFJetID Selector to new recommended RunII JetID, move type1 corrections to ak4CHS JetEnergyCorrector.

### CODE REVIEW

**Comment by deguio** [comment]
more updates will come. waiting for now.

**Comment by webermat** [comment]
added puppi jets and MET monitoring into JetMET Validation and DQM packages. Reduce number of bins in 2D plots and remove trigger stream folders.

**Comment by webermat** [comment]
please test

**Comment by davidlange6** [comment]
cmsbuild, please test

**Comment by webermat** [comment]
included MET filter monitoring for each of the recommended filters/or filters in testing face. Both PASS histograms and for each filter the efficiency. In order to free up memory all monitoring of OOT PU histograms for the 50ns beam spacing period is removed.

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
@webermat is this one final?
thanks,
F

**Comment by webermat** [comment]
@deguio this is the final version.

**Comment by deguio** [comment]
pleasae test

**Comment by deguio** [comment]
please test

**Comment by webermat** [comment]
the error doesn't seem to be related to the update, but it affects workflow 4.22, which failed previously (cosmics).
The second workflow 8.0 (BeamHalo) which failed previously, runs without any problems. Since both of those run the (fixed) cosmic sequence, workflow 4.22 should finish successfully too.

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
would like to wait and see how it goes the validation in 80x first

**Comment by deguio** [comment]
+1

**Comment by webermat** [comment]
concerning the comparisons, it seems when running the matrix that HBHENoiseFilterFlag is always false in MINAOD, but when running on all available MINIAOD RelVals (both 76X and 80X) the flag is correctly filled and the plots appear to be fine.

**Pull request closed without merging**
