### PR TITLE
Update QGL tag for 2016 and 2018 MC and Run 2 data + Introduce scenario for 2016 cosmics with realistic conditions [10_6_X]

### PR DESCRIPTION
**Pull request by christopheralanwest**
#### PR description:

This PR is a combined backport of PRs #32224 and #31846. It updates the quark-gluon likelihood tag for 2016 and 2018 MC and Run 2 data; 2017 MC already has the correct tag. The update has already been included in the 102X series for the nanoAOD campaign but the change was never propagated to 10_6_X and master.

See the [HN thread](https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/4357.html) for details.

Also, the 2016 Run 2 cosmics scenario is changed from representing conditions at Run 2 startup (which is no longer of interest) to realistic 2016 cosmics conditions (which remains of interest).

The GT diffs are as follows:

**2016 realistic pre-VFP era**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_mcRun2_asymptotic_preVFP_v8/106X_mcRun2_asymptotic_preVFP_v9

**2016 realistic post-VFP era**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_mcRun2_asymptotic_v13/106X_mcRun2_asymptotic_v15

**2016 cosmics (realistic conditions)**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_mcRun2cosmics_startup_deco_v7/106X_mcRun2cosmics_asymptotic_deco_v2

**Offline data**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_dataRun2_v31/106X_dataRun2_v32

**Offline data relval**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_dataRun2_relval_v29/106X_dataRun2_relval_v30

**2018 realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_upgrade2018_realistic_v13/106X_upgrade2018_realistic_v15

**2018 realistic (HEM15/16 failure)**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_upgrade2018_realistic_HEfail_v14/106X_upgrade2018_realistic_HEfail_v15

**2018 cosmics (tracker deco mode)**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_upgrade2018cosmics_realistic_deco_v11/106X_upgrade2018cosmics_realistic_deco_v12

**2018 cosmics (tracker peak mode)**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_upgrade2018cosmics_realistic_peak_v11/106X_upgrade2018cosmics_realistic_peak_v12

The `106X_mcRun2_asymptotic_v15` GT in addition removes several obsolete records.

#### PR validation:

These tags have already been validated and are in use in the 10_2_X series.

In addition, a technical test was performed: `runTheMatrix.py -l limited,1325.516,7.22,136.8642,11024.2,7.4 --ibeos`

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

This PR is backport of PRs #32224 and #31846.

### CODE REVIEW

**Comment by christopheralanwest** [comment]
backport #32224

**Comment by christopheralanwest** [comment]
test parameters
- workflow = 1325.516,7.22,136.8642,11024.2,7.4

**Comment by christopheralanwest** [comment]
please test

**Comment by christopheralanwest** [comment]
please test

**Comment by christopheralanwest** [comment]
+1

- changes seen in PR comparison tests only seen in QG likelihood distributions and in expected workflows (offline data, 2016 MC and 2018 MC)
- consistent backport of PRs #32224 and #31846

**Comment by silviodonato** [comment]
+1

**Pull request merged**
