### PR TITLE
L1T online DQM HLT path for Heavy Ion

### PR DESCRIPTION
**Pull request by BetterWang**
Back port of #25052

### CODE REVIEW

**Comment by andrius-k** [comment]
please test

**Comment by andrius-k** [comment]
@BetterWang @threus will this PR be tested in playback? Otherwise I will review it now.

**Comment by BetterWang** [comment]
Hi @andrius-k , I think no test is needed for this RP. It is trivial.

**Comment by andrius-k** [comment]
+1

**Comment by threus** [comment]
@BetterWang @andrius-k a general comment: every PR, be it trivial or not, that is deployed on top of the production release, will be first tested in playback and only after the validation is complete, will be deployed to production. If the PR is merged before validation and causes crash of the subsystem client in the next prod release, developers will be asked to provide a fix asap.
Both approaches are fine, but the latter may be very risky for the subsystem.
It's of course ok to merge this particular PR, but for the future please notify DQM and update tagCollector twiki accordingly, so we are aware and can test everything that goes to online DQM.

**Comment by fabiocos** [comment]
+1

ok according to ORP discussion

**Pull request merged**
