### PR TITLE
Fix HitPattern::stripHitFilter() (10_4_X)

### PR DESCRIPTION
**Pull request by makortel**
Backport of #25692. Original description:

> The `HitPattern::stripHitFilter()` was counting the MTD hits as well. This PR limits the function to only the strip detectors.
> 
> The problem was found with clang (essentially) complaining the unit test using incorrect overload for `HitPattern::appendHit()`, and adding asserts in addition to the printouts (that would have indicated the problem of wrong overload already in #9959, and the need for an update in #24419).

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by perrotta** [comment]
backport of #25692

**Comment by pmeridian** [comment]
Not an issue as we can always check the actual pattern

**Comment by fabiocos** [comment]
it is not a show-stopper for the production, but for any use of these tracks implying stripHitPattern it might impact. And indeed may packages are recompiled, so it is not practical for a private use...

**Comment by pmeridian** [comment]
Simply you can start build patch1 which can be used for the analysis, but we do not have to delay the start of the production

P.

**Comment by fabiocos** [comment]
sure, I will merge it and then we see when to make a build (in case more fixes arrive)

**Comment by fabiocos** [comment]
+1

**Pull request merged**
