### PR TITLE
Updating HBHEPulseShapeFlag and HBHEStatusBitSetter for Phase 1

### PR DESCRIPTION
**Pull request by igv4321**
Updating HBHEPulseShapeFlag and HBHEStatusBitSetter classes so that they can be used with Phase 1 reco code.
Removing unnecessary default constructors.
Minor bug fix for HBHEStatusBitSetter: update internal HcalLogicalMap every run instead of just once.
This PR should not affect any workflow results in any way.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
HBHEPulseShapeFlag.cc has an error on lines 516-520:
```
   double RMS8Max = RMS / TempCharge[DigiSize-1];
   if(RMS8Max < 1e-5)   // protection against zero
      RMS8Max = 1e-5;

   return RMS / TempCharge[DigiSize-1];
```
I think the last line should actually be:
`return (RMS8Max);`

**Comment by igv4321** [comment]
Agreed and fixed. I guess, this problem has been around since the very beginning.

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
+1

For #15406 f6c2c37b66e3687a7b610b6f058b4bcb6891181d

Updating HBHE classes for Phase 1 HCAL reco. There should be no change in monitored quantities.

The code changes are satisfactory, and Jenkins tests against baseline CMSSW_8_1_X_2016-08-10-1100 show no significant differences, as expected. Extended tests of workflows 136.722_RunDoubleEG2016B and 10024.0_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2017 with 100 and 70 events, respectively, against baseline CMSSW_8_1_X_2016-08-09-1100 also show no significant differences. Similarly, CPU timing measurements show no significant changes.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
