### PR TITLE
Fixed precedence order problem with FormulaEvaluator

### PR DESCRIPTION
**Pull request by Dr15Jones**
Under certain conditions one of the evaluation nodes could be dropped because of a faulty precedence handling.
Unit tests were also extended to test this case.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by slava77** [comment]
@blinkseb 
please confirm that this PR solves the problem

@Dr15Jones we will need 80X and 81X versions of this

**Comment by blinkseb** [comment]
@slava77 Applying 3b2658f on top of CMSSW 8.0.24 fix the issue, I now have exactly the same output from CMSSW than from ROOT!

Thanks a lot!

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/16733 3b2658f
- fix to formula in JEC not yet released for standard workflows. Resolution is confirmed by @blinkseb 
- jenkins tests pass and comparisons show no differences

**Pull request merged**
