### PR TITLE
Run2-alca132 Update the macro codes for IsoTrack and Muon analysis

### PR DESCRIPTION
**Pull request by bsunanda**
Used to compare measurements using Method0/Method3/Mahi reconstruction algorithms

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by lpernie** [comment]
+1

**Comment by fabiocos** [comment]
@bsunanda I assume this has been tested standalone, as this code does not look to run in any regular test workflow

**Comment by fabiocos** [comment]
+1

**Pull request merged**
