### PR TITLE
Implemented BoostedDoubleSVTagInfos (80X)

### PR DESCRIPTION
**Pull request by ferencek**
80X backport of #16124

### CODE REVIEW

**Comment by slava77** [comment]
@ferencek 
just to be clear,  are there any changes to any of the saved products in AOD, RECO, or miniAOD from this PR?
Please clarify.

**Comment by ferencek** [comment]
There are no changes to stored products. However, note that the `pat::Jet` interface has a new accessor function for newly added TagInfos but there are no changes to the class data members.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
backport #16124

**Comment by cvuosalo** [comment]
+1

For #16224 ed961603e069ac6716f5249cce34df48fea14eec

Adding a new, more flexible TagInfo format for the BoostedDoubleSV tagger. There should be no change in monitored quantities.

#16124 is the 81X version of this PR, and it has already been merged.

The code changes are satisfactory and match those in #16124. Jenkins tests against baseline CMSSW_8_0_X_2016-10-16-0000 show no significant differences, as expected.

**Comment by monttj** [comment]
+1
backport  #16124

**Comment by davidlange6** [comment]
+1

**Pull request merged**
