### PR TITLE
Run2-sim30 Try to remove dependency of Reco geometry for CaloSteppingAction

### PR DESCRIPTION
**Pull request by bsunanda**
Step toward to have a code which can do scoring for Geant4 as well as GeantV

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by fabiocos** [comment]
@bsunanda @civanch for my understanding could you please clarify the purpose of this PR, apart for the cleaning of couts? Is the CaloSteppingAction not used in the default workflow, as I would say from configurations?

**Comment by bsunanda** [comment]
@fabiocos @civanch These codes are developed to allow a common platform of comparing Geant4 and GeantV. Certainly this is not in standard workflow and will be used by experts making the comparisons (both physics and performance). CaloSteppingAction without reference to Hcal geometry is the source of the scoring code

**Comment by fabiocos** [comment]
+1

**Pull request merged**
