### PR TITLE
Have InputProductResolver use DelayedReader

### PR DESCRIPTION
**Pull request by Dr15Jones**
Moved communicating with the DelayedReader from the Principal into the InputProductResolver. This   allows a more maintainable system as well as better application of the shared resource handling.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
