### PR TITLE
Rename herwigpp tool to herwig7

### PR DESCRIPTION
**Pull request by Dominic-Stafford**
#### PR description:

Rename external library herwigpp to herwig7 for consistency with pull request cms-sw/cmsdist#6709.

#### PR validation:

Tested with workflow 535 and matchbox test command command from Herwig twiki.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Backport of #32468 for use in UL production

### CODE REVIEW

**Comment by mrodozov** [comment]
please test with https://github.com/cms-sw/cmsdist/pull/6709

**Comment by agrohsje** [comment]
+generators

**Comment by mrodozov** [comment]
@silviodonato @qliphy the external cms-sw/cmsdist#6709 is also fine

**Comment by qliphy** [comment]
+1

**Pull request merged**
