### PR TITLE
Run3-gex181 Getting ready for preparing payload of 2025 Geometry

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Getting ready for preparing payload of 2025 Geometry

#### PR validation:

Use some of the scripts privately

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by perrotta** [comment]
+db
- Add scripts needed to prepare the 2025 geometry

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
