### PR TITLE
HCAL: package with widely-used tools for additional data monitoring

### PR DESCRIPTION
**Pull request by zhokin2**
#### PR description:
This branch includes 3 tasks:
CMT - supporting tool helping for certification of Hcal data;
RMT - supporting tool for monitoring of Hcal data including 
monitoring tasks for Calibration group;
AMT - macros based on use of root files produced by RMT for 
analyses like Raddam with Laser local runs, Gain stability 
with LEDs , phi-symmetry monitoring with use of local 
and global runs;  

#### PR validation:
Compilation is OK, tests run.
NB: no regular workflows are affected

### CODE REVIEW

**Comment by abdoulline** [comment]
Please, change (edit) the title to something like:
"HCAL: adding widely-used tools for additional data monitoring"
And fill  the two descriptive fields: 
PR description:
PR validation:

**Comment by abdoulline** [comment]
@fabiocos   Fabio, what should be done (happen) next - 
I mean who's supposed to create  the new package in CMSSW? 
cmsbot suggests above:
<...> 
Please create a PR for https://github.com/cms-sw/cms-bot/blob/master/categories_map.py to assign category
<...>

**Comment by smuzaffar** [comment]
@abdoulline , who should be responsible for this new packages? Curently `analysis` is responsible for every thing under `DPGAnalysis`

**Comment by abdoulline** [comment]
> @abdoulline , who should be responsible for this new packages? Curently `analysis` is responsible for every thing under `DPGAnalysis`

@smuzaffar 
I suppose the new package in question should stay under 'analysis' category (with HCAL DPG  responsibility in general).

**Comment by boudoul** [comment]
Dear @zhokin2 and @abdoulline : Happy New Year ! 
Should we consider testing this package in one of the next MWGR ? 
Thanks

**Comment by abdoulline** [comment]
> Dear @zhokin2 and @abdoulline : Happy New Year !
> Should we consider testing this package in one of the next MWGR ?
> Thanks

@boudoul 
Happy New year,  Gaelle!
Just to avoid (any) misunderstanding - 
this package contains what's actually used in HCAL data analysis _all the time_ from private git branch.  This PR is more about making it officially evolving with HCAL within CMSSW.

**Comment by fabiocos** [comment]
@abdoulline @boudoul @zhokin2 a few comments for @silviodonato for the follow up: this is the request to import into CMSSW a standalone package of the HCAL community, to keep it synchronous with the rest of CMSSW. I see only one analyzer (and I wonder whether all the dependencies in the BuildFile are really needed, it should be likely cleaned), and a lot of scripts and macros. I would suggest a more conventional structure of the package ("scripts", "macros"), may be having the 3 directories  amt, cmt and rmt as subpackages of them. 

Its content looks a mixture of ALCA and DQM tools, more than a DPGAnalysis in the senso of the other two packages existing so far.

**Comment by abdoulline** [comment]
@silviodonato, @fabiocos 

     Fabio and Silvio,

Alexandr Zhokin (@zhokin2 ) is on winter-break vacation till the end of this week, I believe.

In the meantime: the content is multi-purpose indeed.
Including (among other components) some data quality monitoring, but not for DQM shifters, more experts-oriented with some data-certification "helpers".
NB: there is no usage of regular DQMServices, only ROOT.

**Comment by zhokin2** [comment]
Dear All,

these RMT/CMT were developed by Olga Kodolova, Pavel Bunin, Danila Tlisov and me. Today, Olga and I only,  support and develop these tools.
We provide running of scripts to produce plots for corresponding sites. And over the past 6 years, we are accustomed to not separate scripts and macros within any one(!) analysis. The modification of the directory tree that Fabio offers may look more familiar, but it will require fixing many scripts to provide access to a specific macro. Therefore,  I'd prefer current directory tree without additional  "scripts" and "macros" packages. Once namely Olga will have to redo a lot of scripts for Fabio's suggestion it's important to know her opinion as well.
If you still insist on introducing of the "scripts" and  "macros" packages, should updates to be done, either within current CMTNEW_11_0_X_2 branch, or a new one to be created with the following PR.
Concerning dependencies in the BuildFile. As I said, 6 years we've developed the code adding various new elements and analyzes. Therefore, I do not exclude that something can be cleaned.

Cheers, Alexander.
________________________________

**Comment by zhokin2** [comment]
I got reply from Olga:
" ...I have nothing against either of names....It is not a large deal to change paths in scripts and cc",
- she is not against the changes proposed by Fabio, so I will make the appropriate changes and let you know as soon as everything is ready. The changes will be done within the CMTNEW_11_0_X_2 branch.

AZ
________________________________
From: Alexandr Zhokin
Sent: 09 January 2020 08:03
To: cms-sw/cmssw; cms-sw/cmssw
Cc: Mention; Olga Kodolova
Subject: RE: [cms-sw/cmssw] HCAL: package with widely-used tools for additional data monitoring (#28477)

Dear All,

these RMT/CMT were developed by Olga Kodolova, Pavel Bunin, Danila Tlisov and me. Today, Olga and I only,  support and develop these tools.
We provide running of scripts to produce plots for corresponding sites. And over the past 6 years, we are accustomed to not separate scripts and macros within any one(!) analysis. The modification of the directory tree that Fabio offers may look more familiar, but it will require fixing many scripts to provide access to a specific macro. Therefore,  I'd prefer current directory tree without additional  "scripts" and "macros" packages. Once namely Olga will have to redo a lot of scripts for Fabio's suggestion it's important to know her opinion as well.
If you still insist on introducing of the "scripts" and  "macros" packages, should updates to be done, either within current CMTNEW_11_0_X_2 branch, or a new one to be created with the following PR.
Concerning dependencies in the BuildFile. As I said, 6 years we've developed the code adding various new elements and analyzes. Therefore, I do not exclude that something can be cleaned.

Cheers, Alexander.
________________________________

**Comment by zhokin2** [comment]
Directory tree concerning scripts and macros was re-done according Fabio assumption.
AZ
________________________________

**Comment by zhokin2** [comment]
OK, 32 lines were removed, and now there are 12 lines only. Compilation is fine, test job running fine, output root file is OK.

________________________________

**Comment by silviodonato** [comment]
After the ORP meeting it seems like this package is somewhere between dqm (@jfernan2  @andrius-k  @schneiml  @fioriNTU  @kmaeshima ) and alca (@christopheralanwest  @franzoni  @tlampen  @pohsun  @tocheng )

@zhokin2  @abdoulline which category do you think is more correct?
The list of all categories is https://github.com/cms-sw/cms-bot/blob/master/categories_map.py

**Comment by zhokin2** [comment]
looking on available categories , more correct in general sense is
DQM/HcalTasks , but more precisely would be new name DQM/HcalRemoteTools

**Comment by silviodonato** [comment]
Sorry for the misunderstanding. The categories are the index of the map in https://github.com/cms-sw/cms-bot/blob/master/categories_map.py
(ie. tsim core upgrade xpog visualization geometry docs hlt db externals analysis simulation pdmv generators daq reconstruction l1 heterogeneous dqm alca operations)

DQM/HcalTasks is an already existing package. We can create a new package (DPGAnalysis/HcalTools or using another name). The point is that we need to assign your new package to a category that will monitor / take care of this package in the future (eg. dqm, alca, ...)

**Comment by zhokin2** [comment]
The main purpose of these tools is to improve the quality of the data by making an additional remote analysis of hcal data. Therefore, in the sense, a new package DPGAnalysis/HcalTools can be assigned either to category "dqm" or "analysis". Since these tools are not related to operational tools of data taking and I'd prefer category "analysis" .

**Comment by abdoulline** [comment]
I've replied 16 days ago in this thread to the same question of Shahzad , 
suggesting to keep it under "analysis" category...

**Comment by fabiocos** [comment]
@abdoulline my 2 cents: ```analysis``` has been used so far for physics oriented analysis code, more than for detector monitoring, and furthermore the coverage of that category is at present unclear.

**Comment by abdoulline** [comment]
@fabiocos  indeed, this package is more on "dqm" side (in a broad sense, even if it doesn't use DQMServices)  as mostly used for detector monitoring. 
I've suggested (not well defined) "analysis" as (1) this package isn't used in central workflows (2) it's a mixture of several applications for various purposes (including AlCa).

**Comment by silviodonato** [comment]
Ok, I propose to have this package under "dqm", even if it does not use DQMServices. I prefer to assign to "analysis" only the packages that are actually used in data analysis.
If there are no other comment, we can move on and merge this PR tomorrow.

cc: @santocch

**Comment by jfernan2** [comment]
May I ask why this is not being asigned to AlCa since one of the known and defined purpouses of the code is doing AlCa? This looks to me the same as "DPGAnalysis/SiStripTools", which belongs to analysis. The other one in DPGAnalysis, Skims belongs to AlCa too.
Nothing about DQM is being used in this package, so it gets difficult to distangle; we (dqm) have little to say when it comes to standard CMSSW analyzers in terms of reviewing. Besides, as @zhokin2  mentions, these tools are not related to operational tools of data taking.
Thanks

**Comment by zhokin2** [comment]
These tools are not related to alca (alignment and calibration). Main aim is precise identification of suspecion lumi-sections based on analysis of adc-shape distribution of each hcal channel. It's important especially for long global runs where CMT provides as detailed dedicated sophisticated plots, and corresponding tables(!). It's a valuable auxiliary tool for certification of hcal data. Besides, these tools provide auxiliary plots to identify channels with irregular signal shape, wrong pedestals, firmwares failure and so on, and thus, allow to clarify the source of hcal problems for lumi-sections marked as bad.

**Comment by silviodonato** [comment]
please test

**Comment by silviodonato** [comment]
code-checks

**Comment by zhokin2** [comment]
- correct python file is now in dir. /python

- python file to be used for 2021 is placed in test dir. for further tests

**Comment by silviodonato** [comment]
please test

**Comment by silviodonato** [comment]
+1
@smuzaffar please assign this package to dqm

**Comment by smuzaffar** [comment]
assign dqm
dqm, please sign it if agree. I can then merge https://github.com/cms-sw/cms-bot/pull/1254

**Comment by jfernan2** [comment]
+1

**Pull request merged**
