### PR TITLE
Simplify pat jet constituent access in 94X

### PR DESCRIPTION
**Pull request by ahinzmann**
Backport of #22914

This does not change persistent objects, but it does change the interface to MiniAOD slimmedAK8jets, allowing for computation of jet ID and substructure on top of MiniAOD.

Thus it may be worth cutting an analysis release 95X for this if parties agree.

@arizzi @gpetruc @rappoccio

### CODE REVIEW

**Comment by rappoccio** [comment]
From my side it's necessary to cut a 95x. Putting an interface change into 94x minor releases will create too much confusion. OTOH a 95x will make it clear that this is a schema shift.

**Comment by slava77** [comment]
> From my side it's necessary to cut a 95x.

I don't feel particularly strongly, but perhaps it's a view desensitized by no impact on the production workflows and presumption that the release numbering is to indicate what we produce.

@fabiocos @gpetruc @arizzi

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
> From my side it's necessary to cut a 95x.

BTW, the standard rules will trigger a full build for this (the next number is 9_4_7).
If a new major version is to be made, this feature is a good candidate to enter it, but the rest of reminiAOD production is going to stay in 94X (including the 2016 "legacy" re-mini).

**Comment by rappoccio** [comment]
OK, this will just create a bit of confusion but we can live with it.

**Comment by slava77** [comment]
I guess this will need to wait for tests in https://github.com/cms-nanoAOD/cmssw/pull/161  to complete.

@ahinzmann 
do you expect to introduce [enable or backport] some new algorithms relying on this feature of AK8 jets in the production workflows (like a future nano or the upcoming 80X/2016 re-miniAOD)?

If this remains necessary only for analysis and the output of nanoAOD is confirmed as unchanged, I think that this PR can stay in 9_4_X branch and can be merged soon.

**Comment by slava77** [comment]
@smuzaffar @mrodozov 
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-23007/27572/summary.html
shows up empty (I tried with two browsers)
it seems like the problem is generic, not just for this PR.

**Comment by rappoccio** [comment]
Nothing is planned for 94x AFAIK.

**Comment by smuzaffar** [comment]
@slava77 , it works for me under chrome and IE, which browser/OS you have tried?

**Comment by slava77** [comment]
> @slava77 , it works for me under chrome and IE, which browser/OS you have tried?

it works now.
I guess there was some interruption of service

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/23007	2acf495
- this changes pat::Jet accessor implementation for use cases which are apparently restricted to analysis use cases. No changes are expected in persisted quantities in miniAOD or nanoAOD.
- the backport from https://github.com/cms-sw/cmssw/pull/22914	9b04b8b is correct.
- jenkins tests pass and comparisons with the baseline show differences only in DQM plots of slimmedJetsAK8 jets which count the jet constituents. These differences are expected.
    - higher stat tests in the nanoAOD CI https://github.com/cms-nanoAOD/cmssw/issues/90#issuecomment-383494128 show no differences in the nanoAOD variables

**Comment by ahinzmann** [comment]
We should make sure that the TWiki (https://twiki.cern.ch/twiki/bin/view/CMSPublic/WorkBookMiniAOD2017) will correctly describe this change. What exact release will this PR enter?

**Comment by slava77** [comment]
On 4/23/18 8:43 AM, ahinzmann wrote:
> We should make sure that the TWiki
> (https://twiki.cern.ch/twiki/bin/view/CMSPublic/WorkBookMiniAOD2017)
> will correctly describe this change. What exact release will this PR enter?
> 

it will be 9_4_7 or greater, depending on the integration process

**Comment by fabiocos** [comment]
@slava77 @rappoccio @ahinzmann as DataFormats are touched this will need to enter into a 9_4_7 as Slava says. I do not like the idea of changing the interface to access data in the middle of a production release, but after agreeing to keep the whole reprocessing in 94X and using ancillary branches for that, the creation of a new release cycle just to change the method to access an object in this PR seems to me an overshooting, TBD

**Comment by fabiocos** [comment]
merge

**Comment by ahinzmann** [comment]
I've adapted the documentation accordingly:
https://twiki.cern.ch/twiki/bin/view/CMSPublic/WorkBookMiniAOD2017

**Pull request merged**
