### PR TITLE
ECAL esConsumes migration various packages

### PR DESCRIPTION
**Pull request by thomreis**
#### PR description:

This PR migrates ECAL related code in the various reco and db packages to esConsumes (#31061). In addition `getByLabel()` calls were replaced by `getByToken()`and legacy module types were migrated to multithreaded module types.

#### PR validation:

Code compiles.

### CODE REVIEW

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by ggovi** [comment]
+1

**Comment by jpata** [comment]
+reconstruction
- for 9a7dbd1 
- technical, no reco differences observed/expected
- the switch from legacy modules to `edm::one/stream` seems correct to me

**Comment by qliphy** [comment]
+1

**Pull request merged**
