### PR TITLE
Fix L1T bugs and add workflows

### LINKED ISSUE #30539: ProductNotFound (simEcalEBTriggerPrimitiveDigis) in wf 20634.99
After having turned on the new Phase-2 L1T package (`CMSSW_11_2 2020-07-02-2300`, #30498, #30479) we are getting an exception in 20634.99:
```
----- Begin Fatal Exception 04-Jul-2020 03:42:40 CEST-----------------------
An exception of category 'ProductNotFound' occurred while
   [0] Processing  Event run: 1 lumi: 2 event: 104 stream: 2
   [1] Running path 'FEVTDEBUGHLToutput_step'
   [2] Prefetching for module PoolOutputModule/'FEVTDEBUGHLToutput'
   [3] Calling method for module L1EGCrystalClusterEmulatorProducer/'L1EGammaClusterEmuProducer'
Exception Message:
Principal::getByToken: Found zero products matching all criteria
Looking for type: edm::SortedCollection&lt;EcalEBTriggerPrimitiveDigi,edm::StrictWeakOrdering&lt;EcalEBTriggerPrimitiveDigi&gt; &gt;
Looking for module label: simEcalEBTriggerPrimitiveDigis
Looking for productInstanceName: 
Looking for process: HLT
   Additional Info:
      [a] If you wish to continue processing events after a ProductNotFound exception,
add "SkipEvent = cms.untracked.vstring('ProductNotFound')" to the "options" PSet in the configuration.

----- End Fatal Exception -------------------------------------------------
```

### PR DESCRIPTION
**Pull request by kpedro88**
#### PR description:

* resolves #30539
* resolves issue reported by @srimanob w/ missing ESProducers, and adds TestOldDigiProdLike workflow (which corresponds to the commands that produced the issue)
* puts D49 ProdLike workflow in IB tests
* several minor fixes for L1T issues observed while running workflows

Will backport to 11_1_X.

#### PR validation:

Ran relevant workflows: 20634.99, 23234.0, 23234.1001, 23234.1002, 23234.21

### CODE REVIEW

**Comment by kpedro88** [comment]
please test

**Comment by kpedro88** [comment]
please test workflow 20634.99,23234.0,23234.1001,23234.1002,23234.21

**Comment by kpedro88** [comment]
please abort

**Comment by kpedro88** [comment]
please test workflow 20634.99,23234.0,23234.1001,23234.1002,23234.21

**Comment by silviodonato** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade

**Comment by srimanob** [comment]
@rekovic @chayanit
Could you please check and sign if OK? Thanks.

**Comment by chayanit** [comment]
+1

**Comment by silviodonato** [comment]
@kpedro88  could you prepare a backport to 11_1_X? Thanks

**Comment by kpedro88** [comment]
@silviodonato see #30569

**Comment by silviodonato** [comment]
merge

**Pull request merged**
