### PR TITLE
L1T uGT - Parsing of LUTS, Remove unnecessary Warning messages

### PR DESCRIPTION
**Pull request by rekovic**
- Add parsing of LUTS for ETM, ETMHF, and HTM mass and two body pT algorithms.
- Needed to get rid of unnecessary Warning messages when
running uGT emulator in HLT with L1T Menu contiaing M_T algorithms,
trying to deploy online. 

Please merge soon.

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by rekovic** [comment]
please test

**Comment by rekovic** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
