### PR TITLE
MTD geometry: remove obsolete unused xml configuration files

### PR DESCRIPTION
**Pull request by fabiocos**
#### PR description:

In this PR a number of xml configuration files for old MTD scenarios no more considered for the supported workflows are removed, to make the data area cleaner and lighter.

#### PR validation:

No file for used scenarios has been touched, the test workflow for scenario D49 runs smoothly, as well as the unit test of ```Geometry/MTDCommonData```.

### CODE REVIEW

**Comment by fabiocos** [comment]
please test

**Comment by cvuosalo** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade

**Comment by qliphy** [comment]
+1

**Pull request merged**
