### PR TITLE
TTHFGenFilter 71X

### PR DESCRIPTION
**Pull request by Andrej-CMS**
Filter that can be used to produce a tt+bb sample, that is filtered from an inclusive tt+jets sample on Gen-Sim-Level.
The tool is based on the GenHFHadronMatcher.
Has been discussed, e.g. at:
https://indico.cern.ch/event/535804/contributions/2248021/attachments/1311031/1961746/TTbbFIlterProposal_180716_AndrejSaibel.pdf

https://indico.cern.ch/event/524148/contributions/2154898/attachments/1266760/1875475/CombinationOfTTbarandTTbb_AndrejSaibel.pdf

Backport of #15301

### CODE REVIEW

**Comment by Andrej-CMS** [comment]
@monttj

Now the new flag is also in 71X (See 81X pull request)

**Comment by Andrej-CMS** [comment]
@cmsbuild  @davidlange6 This is the backport of #15301 which was already merged into the 81X branch.

Since we would like to start immediately a test sample production using this filter in the CMS tranche3 global production, we would kindly ask you to accept and merge this PR as soon as possible.

Furthermore, can you please tell us when a new CMSSW release including this PR would then be released?
Thanks in advance

**Comment by mharrend** [comment]
urgent

**Comment by Andrej-CMS** [comment]
urgent

**Comment by Andrej-CMS** [comment]
Dear CMSSW management,

Could you please check out this PR and tell me whether it's okay or what I need to do to get it approved. The 81X version of this code is already merged into CMSSW

Kind regards,

Andrej

**Comment by Andrej-CMS** [comment]
please test

**Pull request closed without merging**
