### PR TITLE
HLTTauDQMOffline_cfi: commented out obsolete discriminators

### PR DESCRIPTION
**Pull request by slehti**
#### PR description:
HLTTauDQM offline reference object selection contained obsolete discriminators not available in RAW-RECO any more. Commented them out.

Expected change: DQM plots made with fake taus, instead of just being empty.

### CODE REVIEW

**Comment by emanueleusai** [comment]
please test

**Comment by emanueleusai** [comment]
+1

- dqm differences in HLT tau where expected

**Comment by perrotta** [comment]
> HLTTauDQM offline reference object selection contained obsolete discriminators not available in RAW-RECO any more. Commented them out.

If they are obsolete, and there is no plan to reinstantiate them, then maybe they can be just removed rather than being simply commented out

> 
> Expected change: DQM plots made with fake taus, instead of just being empty.

Shouldn't one aim at also cleaning them, then? I mean, if there are plots made with fake taus I imagine they have no usage: it isn't then worth trying to remove them completely, rather than having them filled with fakes, wasting resources and keeping confusing the DQM shifters?

**Comment by slehti** [comment]
Removed the commented lines.

The DQM plots should remain, even if made with fake taus, the plots have their use.

**Comment by perrotta** [comment]
please test

**Comment by emanueleusai** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
