### PR TITLE
HCALDQM: Fix ngHO crate-FED mapping (master)

### PR DESCRIPTION
**Pull request by DryRun**
#### PR description:
This PR fixes the ngHO crate-FED mapping implemented in https://github.com/cms-sw/cmssw/pull/28484. The mapping changed a bit since that PR, so HCAL is crashing the DQM playback again. There was some further work done, and crate 38 ended up being used, instead of 33. See that thread for more info on the expected changes.

This probably has cropped up a few times now, and might happen again in the future. We plan to move away from the hard-coded crate-FED map. A couple ideas:

1. Change from FED to something like RBX. HCAL ops doesn't like FED anyways, since it doesn't correspond to anything physical and is subject to change in the future (depending on the zero-suppression strategy at higher radiation damage, HCAL may move to 3 FEDs / crate). 
2. Make FED available through conditions. Seems like a lot of work just to have FED on a plot axis.

#### PR validation:
Fixes the crash in playback. Passed `runTheMatrix.py -l limited -i all --ibeos` without error.

### CODE REVIEW

**Comment by srimanob** [comment]
Does crash in playback (without this PR) can be seen with any relval workflows? Or we just need to test in DQM environment only?

**Comment by jfernan2** [comment]
@srimanob I am afraid the crash can only be seen in Online DQM, otherwise master would be already afected

**Comment by jfernan2** [comment]
please test
Even if backport #28955 has already been tested in Online DQM playback

**Comment by jfernan2** [comment]
+1
Changes expected due to new crate numbering

**Comment by silviodonato** [comment]
+1

**Comment by jfernan2** [comment]
+1
Tested in Online DQM playback

**Pull request merged**
