### PR TITLE
Remove L1Tk paths defined in L1TkObjectProducers_cff.py 

### PR DESCRIPTION
**Pull request by silviodonato**
#### PR description:

As commented in https://github.com/cms-sw/cmssw/issues/31054, the L1Tk paths defined in `L1TkObjectProducers_cff.py` are not necessary and make confusion. This PR deletes `L1TkObjectProducers_cff` including those L1Tk paths, and add the minimal configuration needed into `SimL1Emulator_cff.py `

#### PR validation:

`runTheMatrix.py -l 23234.0`

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

no backport, so far

### CODE REVIEW

**Comment by silviodonato** [comment]
please test

**Review by srimanob — COMMENTED** [review]
I think you delete L1TkObjectProducers_cff.py but why it is still mentioned in SimL1Emulator.
https://github.com/cms-sw/cmssw/blob/9ac87c20c22f7f791998d1e857a32819cd3ae6ce/L1Trigger/Configuration/python/SimL1Emulator_cff.py#L99

**Comment by silviodonato** [comment]
abort

**Comment by silviodonato** [comment]
please test

**Comment by silviodonato** [comment]
please test

**Comment by kpedro88** [comment]
+upgrade

**Comment by silviodonato** [comment]
merge

**Pull request merged**
