### PR TITLE
Fix of HLT names in DQM after JIRA-717 (backport of #13966 in 80X)

### PR DESCRIPTION
**Pull request by silviodonato**
## Fix of HLT names in DQM after JIRA-717 (backport of #13966 in 80X)

Hi all,
with JIRA-717 [1] we are changing the name of a few trigger paths.
This PR fix the DQM code accordingly.
Silvio.
[1] https://its.cern.ch/jira/browse/CMSHLT-717

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
this doesn't merge anymore. could you please fix the conflicts?
I will approve after that.
thanks,
F.

**Comment by silviodonato** [comment]
conflict solved

**Comment by silviodonato** [comment]
hold on. I've made a mess....

**Comment by silviodonato** [comment]
Reopened with https://github.com/cms-sw/cmssw/pull/14008

**Pull request closed without merging**
