### PR TITLE
HLT updates on top of what is in CMSSW742

### PR DESCRIPTION
**Pull request by perrotta**
This PR includes #8916, and further updates the development HLT menus and local tests for them.
It may be considered a backport in 74X of #9148 + #9161 

The _v1 frozen menus (used in RelVals and in the MC production) are not touched
_v2 of those frozen menus are added

### CODE REVIEW

**Comment by slava77** [comment]
<aside>
Will we ever get to a point where HLT updates don't come with 400K source code line-changes
</aside>

**Comment by perrotta** [comment]
@slava77 : unlikely, al least until we need to add new paths in the menu and modify the existing ones
 :-)

**Comment by Martin-Grunewald** [comment]
Rebased to solve merge conflicts.

**Comment by Martin-Grunewald** [comment]
please test

**Comment by lveldere** [comment]
+1

nothing new in the FastSim area with respect to #8953

**Comment by Martin-Grunewald** [comment]
+1

**Comment by Martin-Grunewald** [comment]
Rebased and ading backport of #9217 .

**Comment by Martin-Grunewald** [comment]
please test

**Comment by davidlange6** [comment]
why do we need menus that are the same but with different names? Given there size this is more than a bit suboptimal.

**Comment by Martin-Grunewald** [comment]
What menus are identical? We added new V2 frozen menus which are only currently
identical to the development menus, but will soon be different as the frozen menus stay
unchanged while the development menus change.

**Comment by davidlange6** [comment]
I guess you answered your question. 

How many versions of frozen menus are being proposed to be maintained in the release? (as apparently its increasing still)

**Comment by Martin-Grunewald** [comment]
In terms of numbers that is unclear: In the long term it is envisaged to keep:
* menus used for (large scale) MC productions (currently the V1 menus)
* most recent menus used for the most recent TSG checkpoint studies (currently the V2 menus),
* menus used for real data taking where a non-negligible amount luminosity was acquired.

For comparison, 53X contains 6 frozen menus plus the development menus.

**Comment by fwyzard** [comment]
Hi David,
I think we should maintain all the menus used for significant productions
(like Spring'15) and data taking (like the 50ns menu, and a bunch of 25ns
menus), as they will likely be used for the future MC productions.

Ciao,
.Andrea

**Comment by davidlange6** [comment]
> On May 22, 2015, at 12:45 PM, Martin Grunewald <notifications@github.com> wrote:
> 
> In terms of numbers that is unclear: In the long term it is envisaged to keep:
> 
> 	• menus used for (large scale) MC productions (currently the V1 menus)
> 	• most recent menus used for the most recent TSG checkpoint studies (currently the V2 menus),
> 	• menus used for real data taking where a non-negligible amount luminosity was acquired.
> For comparison, 53X contains 6 frozen menus plus the development menus.

Right-  and now even a month before data taking we have 4 frozen menus. thus the worry.  It sounds like I should not expect v2 to be maintained in the release for very long.

**Comment by Martin-Grunewald** [comment]
Right - V2 (ie, the chckpoint menus for TSG checkpoint tests) would be replaced and eventually faded out/removed once data taking moves to 75X.

**Comment by Martin-Grunewald** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
