### PR TITLE
Adding d0 cut to TrackletCalculatorDisplaced.cc

### PR DESCRIPTION
**Pull request by Jingyan95**
#### PR description:

This PR is opened to address Issue #41357. A cut on d0 exact is added to TrackletCalculatorDisplaced.cc. This fixes the problem that was reported in #41357.

#### PR validation:

I tested this PR with [instruction](https://github.com/cms-sw/cmssw/issues/41357#issuecomment-1731175261) specified in #41357 by @srimanob.

### CODE REVIEW

**Comment by srimanob** [comment]
@cmsbuild please test

**Comment by aloeliger** [comment]
+l1

**Comment by rappoccio** [comment]
+1

**Comment by srimanob** [comment]
@Jingyan95 @aloeliger Please prepare the backport to 13_1 if you would like to request samples to study the effect of the bug. Thx.

**Pull request merged**
