### PR TITLE
Phase2-gex171 Add a few more options to generate the single neutrino file

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Add a few more options to generate the single neutrino file

#### PR validation:

Use this script to validate HGCal geometry

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by tjavaid** [comment]
please test

**Comment by tjavaid** [comment]
type hgcal

**Comment by civanch** [comment]
+1

**Comment by tjavaid** [comment]
+1

**Comment by rappoccio** [comment]
+1

**Pull request merged**
