### PR TITLE
Skim on NoBPTX primary dataset for EXO

### PR DESCRIPTION
**Pull request by jalimena**
This PR creates a skim on the the NoBPTX dataset for EXO-16-004, EXO-17-004, and HCal DPG noise studies. No event selection criteria are applied, but the event content is greatly reduced from RECO. Furthermore, this skim need only be applied to the NoBPTX dataset, which is already quite small.
The approval talk in the PPD meeting is here: https://indico.cern.ch/event/651440/contributions/2651033/attachments/1489030/2313761/NoBPTXExoSkim_PPDMeeting_6July2017.pdf

### CODE REVIEW

**Comment by fabozzi** [comment]
please test

**Comment by fabozzi** [comment]
+1

**Comment by davidlange6** [comment]
hi @jalimena - for testing please add your skim to one of the workflows defined in Configuration/PyReleaseValidation/python/relval_steps.py. @fabozzi may need to help as i'm not sure there is a fully appropriate data set [however, nothing in the skim definition depends on the data set, so he may suggest just using one at random]

**Comment by jalimena** [comment]
Hi @davidlange6 and @fabozzi  - yes, I can do this, but I am indeed having trouble identifying where to add this skim in relval_steps.py. Are there any other 2017 skims defined yet? Please advise.

**Comment by fabozzi** [comment]
Hi @jalimena:
we have a NoBPTX relval defined here:
https://github.com/cms-sw/cmssw/blob/master/Configuration/PyReleaseValidation/python/relval_standard.py#L166

You have to add your skim in RECODR2reHLTAlCaTkCosmics sequence here:
https://github.com/cms-sw/cmssw/blob/master/Configuration/PyReleaseValidation/python/relval_steps.py#L1345

this is similar to what done for other sequences with skim as in:
https://github.com/cms-sw/cmssw/blob/master/Configuration/PyReleaseValidation/python/relval_steps.py#L1348-L1354

@jalimena: you need to add the skim also in autoSkim matrix:
https://github.com/cms-sw/cmssw/blob/master/Configuration/Skimming/python/autoSkim.py#L18

@kfjack: please help @jalimena if she has doubts

**Comment by kfjack** [comment]
@fabozzi, @jalimena 
As I explained to @jalimena yesterday, I'll take over the work from here (relval and skim matrix). But surely if Juliette want to try I can work on another skim first.

**Comment by jalimena** [comment]
Hi all, thanks, I think I did what you asked, but please check. @kfjack, it's no problem :)

**Comment by kfjack** [comment]
@jalimena, @fabozzi 
I think the new commit from Juliette is okay.

**Comment by kpedro88** [comment]
please test workflow 136.735

**Comment by fabozzi** [comment]
+1

**Comment by davidlange6** [comment]
merge

**Pull request merged**
