### PR TITLE
Phase2-trk10 Possible overlap removal in the T33 version of tracker geometry

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Possible overlap removal in the T33 version of tracker geometry. Two possible ways of removing the overlap - (1) by reducing the length of ModuleDeadAreaFront|Back or by repositioning ModuleDeadAreaRight|Left. The final choice will be taken after consulting with Tracker DPG

#### PR validation:

Tested using the Geant4 Overlap testing tool

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
@bsunanda , I would propose instead of given 2 choices propose MR with V1 variant, where "V1" is not included in the file name. This would be possible to merge. With time phase2 tracker experts may propose better solution on top.

**Comment by bsunanda** [comment]
@civanch Once this PR is merged I can make V1 as the default till Tracker DPG thinks otherwise

**Comment by bsunanda** [comment]
+geometry

**Comment by civanch** [comment]
OK, agreed.

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
