### PR TITLE
80x Fireworks: new version of ECAL detail view

### PR DESCRIPTION
**Pull request by alja**
- draw un-uniform shapes with boxes to represent ecal EB and EE energy deposit in detail views for:
  - Electron
  - Photon
  - Candidate
  - Muon
  - CaloTower
  - TrackBase

screen shot 2016-08-16 at 4 34 13 pm

screen shot 2016-08-16 at 4 34 29 pm
- remove the new color palette announcement in the main frame
- remove color manager printout

### CODE REVIEW

**Comment by alja** [comment]
## issues
   * found tiny overlaps of boxes
   * miniaod have empty reduced his in non-photon or electron elements

**Comment by alja** [comment]
+1

**Comment by davidlange6** [comment]
@alja - what is the 81x PR for this change?

**Comment by alja** [comment]
@davidlange6 

I thought the changes go automatically to 81X as well.

Did automatic port to 81X stopped?

**Comment by davidlange6** [comment]
Hi
Yes, it has stopped

David


On 10 Aug 2016, at 16:08, Alja Mrak-Tadel <notifications@github.com<mailto:notifications@github.com>> wrote:


@davidlange6<https://github.com/davidlange6>

I thought the changes go automatically to 81X as well.

Did automatic port to 81X stopped?

**Comment by alja** [comment]
I will review other changes before sending a PR for 81X.

When was automatic port to 81X stopped? Was this announced on HN?

**Comment by alja** [comment]
@davidlange6 
I thought that the rule is that porting to succeeding sub version is automatic as long the succeeding version has pre releases. The CMSSW_8_1_0 is not yet out. Why there is no automatic port? Is this disucssed only on ORP meetings?

**Comment by Dr15Jones** [comment]
In the past we only automatically port from a 'production' release to a 'development' release until 'pre1' happens in the development release. Usually by then the two releases have diverged sufficiently and/or the changes being made are substantial enough to 'freeze' the 'production' release except for backports of bug fixes from the 'development' release to the 'production' release.

**Pull request merged**
