### PR TITLE
bsunanda:Run2-hcx105 Bug fix to HcalGeometry so that ALCARECOHcalCalHBHEMuonFilter can work

### PR DESCRIPTION
**Pull request by bsunanda**

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@franzoni Corrected the issue of HBHEMuonFilter, Please approve this
@civanch Could you sign this for small bug fix for geometry
@kpedro88 Could you approve this - it is a bug fix for Phase 1 geometry

**Comment by kpedro88** [comment]
+1

**Comment by davidlange6** [comment]
assign alca

**Comment by civanch** [comment]
+1

**Comment by fabozzi** [comment]
+1

**Comment by bsunanda** [comment]
@franzoni Please sign this PR

**Comment by franzoni** [comment]
Thanks @bsunanda 
for the record, this fixes the issue which developed here https://github.com/cms-sw/cmssw/pull/16386

**Comment by franzoni** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
