### PR TITLE
Fix condTestRegression unittest for py3

### PR DESCRIPTION
**Pull request by mrodozov**
#### PR description:
Fixes 
https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc820/CMSSW_11_0_PY3_X_2019-10-10-2300/unitTestLogs/CondCore/CondDB#/
#### PR validation:
Builds and runs on both py2 and 3

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by ggovi** [comment]
+1

**Comment by mrodozov** [comment]
Hm I see in https://github.com/cms-sw/cmssw/pull/28157/files 
David already fixed this so I think I'd close this one :/

**Comment by mrodozov** [comment]
@davidlange6 I see you fixed that in your PR for conddb but I noticed that to late and by accident. I also noticed you didn't change this 
https://github.com/cms-sw/cmssw/pull/28161/files#diff-44fb5ff277a0e30437f3b786451c29c7R157
so what should we do ? 
If you 'untouch' the file in your PR this can go in I guess with the same result and without rebase :/

**Comment by davidlange6** [comment]
ah - I didn't lookout that test directory. as this is fully signed, lets make that a different PR. (it fixes a different problem)

**Comment by fabiocos** [comment]
@davidlange6 @mrodozov here is the difference between your fixes, that are in conflict (from the git perspective):

```
diff --git a/CondCore/CondDB/test/condTestRegression.py b/CondCore/CondDB/test/condTestRegression.py
index 9a3492920f7..5f68dbd48a6 100755
--- a/CondCore/CondDB/test/condTestRegression.py
+++ b/CondCore/CondDB/test/condTestRegression.py
@@ -139,7 +139,7 @@ class CondRegressionTester(object):
             self.dbList['%s [%s]'%(rel,arch)] = dbName
 
         cmd ="scram -a %s list -c %s | grep '\\b%s\\b' | head -1 | sed 's|.* ||'" %(arch,rel,rel)
-        out =check_output(cmd, shell=True, universal_newlines=True, stdin=subprocess.PIPE, stdout=subprocess.PIPE)
+        out =check_output(cmd, shell=True, stdin=subprocess.PIPE, stdout=subprocess.PIPE)
         ind = out.find( arch )
         if ind == -1:
             raise Exception('Could not locate the reference release %s with "%s" [ got %s ]' %(rel,cmd,out))
@@ -154,7 +154,7 @@ class CondRegressionTester(object):
 
         try:
             #opening a process with a clean environment ( to avoid to inherit scram variables )
-            res = check_output(cmd, shell=True, universal_newlines=True, env={}, stdin=subprocess.PIPE, stdout=subprocess.PIPE)
+            res = check_output(cmd, shell=True, env={}, stdin=subprocess.PIPE, stdout=subprocess.PIPE)
         except Exception as e:
             self.log( rel, arch, readOrWrite, str(e) )
             raise e
@@ -190,7 +190,7 @@ class CondRegressionTester(object):
         cmd += '%s %s sqlite_file:///%s/%s ' % (executable, readOrWrite, self.dbDir, dbName)
 
         try:
-            res = check_output(cmd, shell=True, universal_newlines=True, stdin=subprocess.PIPE, stdout=subprocess.PIPE)
+            res = check_output(cmd, shell=True, stdin=subprocess.PIPE, stdout=subprocess.PIPE)
         except Exception as e:
             self.log( self.rel, self.arch, readOrWrite, str(e) )
             raise e
```

Is ```universal_newlines=True``` relevant in this context?

**Comment by fabiocos** [comment]
from https://docs.python.org/3/library/subprocess.html#subprocess.check_output I see 

> By default, this function will return the data as encoded bytes. The actual encoding of the output data may depend on the command being invoked, so the decoding to text will often need to be handled at the application level.

This behaviour may be overridden by setting text, encoding, errors, or universal_newlines to True

>

**Comment by mrodozov** [comment]
@fabiocos the aim was to fix the unit test in the py3 IB, this is what's fixes it and it also work in py2

**Comment by fabiocos** [comment]
@mrodozov I am going to fix the conflict directly

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
merge

@ggovi you had already signed this PR, there is no real change since that

**Pull request merged**
