### PR TITLE
HLT menu development for `14_1_X` (2/N) [`14_2_X`]

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

Development of HLT menus for `CMSSW_14_1_X` (branch `CMSSW_14_2_X`): 
   * This is the PR for the master branch, which will then be backported down to 14_1_X (the latter is the release cycle currently used for Run-3 HLT-menu development).

These updates correspond to the changes accumulated in the 14_1_X release cycle for the "**PRef V1.0**" menu: first menu for the 2024 pp reference data-taking period.

This update includes the integration of the following changes:
- migration of the combined HLT table and related subtables to `CMSSW_14_1_1`

In addition we include the integration of the following JIRA tickets:

- [CMSHLT-3325](https://its.cern.ch/jira/browse/CMSHLT-3325) [HIN] Forward/UPC Triggers request for pp Reference Run 2024
- [CMSHLT-3338](https://its.cern.ch/jira/browse/CMSHLT-3338) [HIN] Muon Triggers for PbPb Run 2024
- [CMSHLT-3340](https://its.cern.ch/jira/browse/CMSHLT-3340) [HIN] Jet Triggers for pp Reference Run 2024
- [CMSHLT-3343](https://its.cern.ch/jira/browse/CMSHLT-3343) [HIN] E/gamma Triggers for pp Reference Run 2024
- [CMSHLT-3345](https://its.cern.ch/jira/browse/CMSHLT-3345) [HIN] Remove `PPRefExotica` PD/stream and re-assign paths to `PPRefSingleMuon`
- [CMSHLT-3346](https://its.cern.ch/jira/browse/CMSHLT-3346) [HIN] Justify `Commissioning{ZDC,RawPrime}` PDs in the `PRef` menu
- [CMSHLT-3348](https://its.cern.ch/jira/browse/CMSHLT-3348) [HIN] Add two seeds to `hltL1sUPCHFafterglowCombined`
- [CMSHLT-3350](https://its.cern.ch/jira/browse/CMSHLT-3350) [HIN] Forward/UPC Triggers request for PbPb Run 2024
- [CMSHLT-3356](https://its.cern.ch/jira/browse/CMSHLT-3356) [HIN] E/gamma Triggers for PbPb Run 2024
- [CMSHLT-3357](https://its.cern.ch/jira/browse/CMSHLT-3357) [TSG] Release of special menus V1.6 (for `PRef`, `HIon` runs)
- [CMSHLT-3363](https://its.cern.ch/jira/browse/CMSHLT-3363) [HIN,TSG] Sync offline menu with the 2023 `PRef` online menu

In this PR we also have the following commits:
   * 3da490438fd845e42a04622bca718bdccbd8ceb2 update of L1T HIon menu in TSG GTs to `L1Menu_CollisionsHeavyIons2024_v1_0_5_xml` 
   * 0a490e2cf7f1c7ede75cf0c90a9800f7f1597568 Finalize integration of the following tickets
        * [CMSHLT-3310](https://its.cern.ch/jira/browse/CMSHLT-3310) [TSG] update input files for TSG tests to more modern datasets (2024)
   * 0880f314a1ebe27203d82131471ffe30e1bbc484 Update `hltPathOwners.json` including paths for menus `PRef` 2024 V1.0 and `HIon` 2024 V1.0
   * d07ff7967fd91337163b6ca6a836ed4e11c6e092 Bumped version of Paths for HLT PRef-2024 V1.0

#### PR validation:

TSG Integration tests.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Not a backport, but it will be backported to `CMSSW_14_1_X`.

### CODE REVIEW

**Comment by mmusich** [comment]
type hlt-integration

**Comment by mmusich** [comment]
enable gpu

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
+hlt
   * [changes](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_14_2_X_2024-10-14-1100+ed9f34/65102/dqm-histo-comparison-summary.html) in the `HLTFilters` DQM folders are due the path versioning (https://github.com/cms-sw/cmssw/pull/46375/commits/d07ff7967fd91337163b6ca6a836ed4e11c6e092).

**Comment by mandrenguyen** [comment]
+1

**Comment by smuzaffar** [comment]
@mmusich , some workflows in the IBs are failing with error [a] . Could it be due to this Pr changes?

[a] https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_amd64_gcc12/CMSSW_14_2_X_2024-10-15-1100/pyRelValMatrixLogs/run/160.0_HydjetQ_B12_5362GeV_2023_ppReco/step2_HydjetQ_B12_5362GeV_2023_ppReco.log#/625-625
```
----- Begin Fatal Exception 15-Oct-2024 13:47:04 CEST-----------------------
An exception of category 'FailModule' occurred while
   [0] Processing  Event run: 1 lumi: 1 event: 1 stream: 0
   [1] Running path 'HLT_HIL2SingleMu0_Centrality40to100_v1'
   [2] Calling method for module HLTL1TSeed/'hltL1sSingleMu0Centrality40to100BptxAND'
Exception Message:

Algorithm L1_SingleMu0_Centrality_40_100_BptxAND, requested as seed by a HLT path, cannot be matched to a L1 algo name in any GlobalObjectMap
Please check if algorithm L1_SingleMu0_Centrality_40_100_BptxAND is present in the L1 menu

----- End Fatal Exception -------------------------------------------------
```

**Comment by mmusich** [comment]
> Could it be due to this Pr changes?

yes, but it's already solved by https://github.com/cms-sw/cmssw/pull/46379

**Comment by mmusich** [comment]
> yes, but it's already solved by https://github.com/cms-sw/cmssw/pull/46379

that PR solves part of the issues, but not everything, https://github.com/cms-sw/cmssw/pull/46398 addresses the rest

**Pull request merged**
