### PR TITLE
[RECONSTRUCTION-UPGRADE] [CLANG] Fix warnings reported by llvm16 in CLANG IBs

### PR DESCRIPTION
**Pull request by aandvalenzuela**
Fixes set but unused warnings from clang-16 in CLANG IBs

### CODE REVIEW

**Comment by aandvalenzuela** [comment]
please test

**Comment by mandrenguyen** [comment]
+reconstruction
Changes to comparisons are spurious

**Comment by AdrianoDee** [comment]
+upgrade
(`used` not used)

**Comment by rappoccio** [comment]
+1

**Pull request merged**
