### PR TITLE
Reduce memory churn at Geant4 initialisation of geometry

### PR DESCRIPTION
**Pull request by civanch**
#### PR description:
Reduced number of copies of geometry objects during initialisation of Geant4 geometry.
Correctness of this PR should be confirmed by identical results.

#### PR validation:
private runs

#### if this PR is a backport please specify the original PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by fabiocos** [comment]
In the total RSS seen in wf 11624. there is a small reduction from ```<Metric Name="PeakValueRss" Value="523.309"/>``` to ```<Metric Name="PeakValueRss" Value="513.125"/>``` . Is this the expected effect?

**Comment by civanch** [comment]
@fabiocos , yes, such type small effect is expected. Another improvement - simplification of the code.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
