### PR TITLE
make `edmModuleAllocMonitorAnalyze.py` executable, so that it's avaialble for users in the path

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

Title says it all.

#### PR validation:

After compiling and `rehash`-ing the script is available from command line.  

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

N/A

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
+core

**Comment by makortel** [comment]
Thanks @mmusich!

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
