### PR TITLE
Use phase1 customisation and era simultaneously, and add stripped DQM,VALIDATION and HARVESTING back to phase1 workflow

### PR DESCRIPTION
**Pull request by makortel**
This PR makes the following two suggestions for the phase1 workflows:
1. Modify the phase1 customisation such that it can be used together with `Run2_2017` era, and add the `--era Run2_2017` to phase1 workflows in RelVal matrix
2. Strip the DQM, VALIDATION, and HARVESTING sequences to (almost) their minimum, and add them to phase1 workflows in RelVal matrix
   - actually current implementation adds them back to all upgrade workflows (AFAICT)

The motivation for the first change is that we can start using the `phase1Pixel` era in the tracking code (first in validation, as is done in this PR). With the second change, we get the tracking validation to be run by default in the phase1 workflows (i.e. we don't need to run them ourselves for release validation, and the results end up in DQM GUI).

In addition, fix phase1TkCustoms for tracking-only reco.

~~Note that this PR conflicts with #12747, please integrate it before this one. I wanted to post this PR for discussion nevertheless now.~~

Tested in 8_0_0_pre3 (rebased on top of ~~CMSSW_8_0_X_2015-12-19-1100~~ CMSSW_8_0_X_2016-01-20-2300); for phase1 with ~~`-w upgrade -l 10000.0,15639.0`~~ `-w upgrade -l 10000.0,10239.0`. No changes expected in Run2 workflows.

FYI @rovere @VinInn @boudoul @atricomi @mark-grimes

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by cvuosalo** [comment]
Matrix test in progress...

**Comment by cvuosalo** [comment]
+1

For #12806 d0c48ff6b4543d17919c5c27a75adca2daeae394

Updating Phase 1 workflows to include DQM, Validation, and Harvesting. There should be no change in monitored Reco quantities.

The code changes are satisfactory, and Jenkins [tests](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-12806/10325/summary.html) against baseline CMSSW_8_0_X_2015-12-15-2300 show no significant differences, as expected. An upgrade matrix test of workflow 15639.0_TTbar_14TeV against baseline CMSSW_8_0_0_pre3 shows the production by the new DQM/Validation/Harvesting step of the DQM ROOT file that is missing in the baseline.

**Comment by makortel** [comment]
Rebased on top of CMSSW_8_0_X_2015-12-19-1100 (to solve the conflicts caused by the merge of #12747), and fixed phase1TkCustoms for tracking-only reco (I hadn't actually tested tracking-only reco for phase1 before).

**Comment by civanch** [comment]
please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/12806	 6b64c8a
- changes are as described
- jenkins tests pass and comparisons with baseline show no differences (phase1 workflows not included)
- local tests in CMSSW_8_0_X_2015-12-20-1100 show that ```  -w upgrade -l 10000.0,15639.0  ``` workflows run without crashes

**Comment by civanch** [comment]
+1

**Comment by deguio** [comment]
ciao @makortel 
I am not sure I like the DQM and Visualization customization implemented directly in the central cff files.
isn't it more clear to customize the sequences in the configs under SLHCUpgradeSimulations/Configuration/python ?
as it is done for example in:
https://github.com/makortel/cmssw/blob/phase1CustomsEra/SLHCUpgradeSimulations/Configuration/python/phase1TkCustoms.py#L99

or
https://github.com/makortel/cmssw/blob/phase1CustomsEra/SLHCUpgradeSimulations/Configuration/python/postLS1Customs.py#L186

maybe I am missing something?
thanks,
F.

**Comment by makortel** [comment]
@deguio Isn't the very idea of eras to decentralize the customizations to files where the entities to be customized are defined?

Said that, given that the goal of the phase1-customizations to DQM and validation central sequences is to disable modules until they're tested to be working with phase1, I agree the customizations could be done in `phase1TkCustoms.py` for the moment. But I have two followup questions to be thought about

1. If everything else in `phase1TkCustoms.py` gets migrated to era before all DQM+validation is fully phase1 compatible, is this good-enogh reason to keep including `phase1TkCustoms.py` in the workflows?
2. (trying to think proactively) What about a case where some DQM/validation sequence is needed only for one era? Would a customization of central DQM/validation sequences be allowed then, or should the variability be addressed in the sub-sequences of the central sequences?

I don't have strong opinions here, I would just like to be able to use phase1 era and turn on tracking validation in phase1 RelVals as soon as possible :) (to avoid running tracking validation manually for each pre-release just for release validation). So if you want, I can move the customizations of `DQMOfflinePrePOG`, `DQMOffline`, `DQMOfflineTracking`, `DQMOffline_SecondStep`, `DQMHarvest_Tracking`, `globalPrevalidation`, `globalValidation`, `postValidation`, `hltassociation` `hltvalidation`, and `hltpostvalidation` sequences to `phase1TkCustoms.py`.  I would however keep the customization `globalPrevalidationLiteTracking` in `globalValidation_cff.py`
https://github.com/cms-sw/cmssw/pull/12806/files#diff-280a22a34e1b642031a67e76fefd1e28R176
because that is genuine difference between run2 and phase1.

**Comment by makortel** [comment]
Since there were no further comments, I moved the customization of DQM and validation central sequences to `phase1TkCustoms.py`. @deguio, would this be satisfactory?

I tested the update in CMSSW_8_0_X_2016-01-11-1100 (but did not rebase) with `-w upgrade -l 10000.0,15639.0` and there should be no changes wrt. 6b64c8a.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/12806	7aeef6e
- last changes https://github.com/makortel/cmssw/compare/6b64c8a...7aeef6e do not affect reco and include a move from calls made under ``` if eras.phase1Pixel.isChosen ``` to central cusomization functions
- jenkins tests (non-upgrade workflows) pass and comparisons with baseline show no differences

**Comment by boudoul** [comment]
@slava77 , thanks to this PR we can introduced PR tests for 2017  (thanks @markotel!) with DQM outputs- so far only IB tests were performed for 2017. I shall prepare this in runthematrix now (also with the ongoing modifications in runthematrix due to phase2 scenarios..as well)

**Comment by boudoul** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by makortel** [comment]
Could DQM (@deguio, @vanbesien) please review and sign? Thanks.

**Comment by deguio** [comment]
+1
thanks @makortel. the last implementation is in my opinion more readable.
ciao,
F.

**Comment by makortel** [comment]
Aha, so we have a conflict now (with #12913 I guess). Rebasing...

**Comment by makortel** [comment]
Rebased on top of CMSSW_8_0_X_2016-01-20-2300, tested with `runTheMatrix.py -w upgrade -l 10000.0,10239.0` (I see the workflow numbering has changed since CMSSW_8_0_X_2015-12-19-1100, due to #12913 I guess).

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/12806	 c92afa9
- this is functionally the same change as in the previously approved 	7aeef6e
    - https://github.com/cms-sw/cmssw/compare/cms-sw: a9ff245...makortel:7aeef6e before the rebase vs https://github.com/cms-sw/cmssw/compare/cms-sw:b1c07e6...makortel:c92afa9 after the rebase
- jenkins tests pass and comparisons with baseline show no differences (this is for run1/run2 tests)

**Comment by civanch** [comment]
+1

**Comment by makortel** [comment]
Could PdmV please sign again? Thanks.

**Comment by boudoul** [comment]
whooopsie I missed the rebase , yes I do

**Comment by boudoul** [comment]
+1

**Comment by makortel** [comment]
Could this PR be merged soon? Subsequent developments are starting to pile up.

**Comment by makortel** [comment]
@davidlange6 @slava77 I would greatly appreciate if this PR could be merged to one of the next IBs.

**Comment by davidlange6** [comment]
apologies - is waiting on me to review - trying now.

**Comment by davidlange6** [comment]
@makortel - we have recently realized the downfalls of isChosen().. so we need to use a different solution. (@dr15jones)

Most of what you have can be done with this sort of function

def _modifyTest(o):
    o.remove(simHitTPAssocProducer)

eras.run2_common.toModify(globalPrevalidation,func=_modifyTest)

(changing the names to be appropriate for your case)

this leaves the especially ugly customize functions with era if statements inside.. Am I right to presume that you are protecting against repeating commands that are already executed via the eras?

**Comment by makortel** [comment]
@davidlange6 Yes, the `if eras.phase1Pixel.isChosen()` statements inside the customize functions are indeed to protect against repeating customizations that have already been done via eras.

About the two other cases I added, for `globalValidation_cff.py`
https://github.com/cms-sw/cmssw/pull/12806/files#diff-280a22a34e1b642031a67e76fefd1e28R134
I have already a better fix getting rid of the need of customization by defining it only in terms of what is needed (instead of what is not) in `TrackValidation_cff.py` (https://github.com/makortel/cmssw/commit/f27468456a7c084eab240162d151fc950b6bc23c). I was planning to include it in a subsequent PR, but if you want I can include it here (I would prefer the subsequent PR to avoid additional delay caused by another cycle of signatures).

The one in `TrackValidation_cff.py`
https://github.com/cms-sw/cmssw/pull/12806/files#diff-aadf335934a95c465835668d66744a38R75
on the other hand, is something I would prefer to keep (at least until the HN thread arrives to some conclusion). Sure, the same effect can be achieved with ProcessModifier, but that would require modifications of several sequences and configurations of MultiTrackValidator instances (and here modifications mean replacing some, not all, modules of the sequences, and also replacing some elements of a VInputTag parameter of MTV). I think it is clearer to switch these internal lists upfront before the sequences and MTV VInputTags are generated from the lists.

**Comment by makortel** [comment]
@davidlange6 @Dr15Jones Regarding the `isChosen()` in `TrackValidation_cff.py`
https://github.com/cms-sw/cmssw/pull/12806/files#diff-aadf335934a95c465835668d66744a38R75, it seems that I can (technically) replace the `isChosen()` with `toModify()` operating on the lists achieving the result I want. I would be fine with that. Do you want the changes included in this PR, or would a subsequent PR be enough?

**Comment by davidlange6** [comment]
+1
@makortel - a subsequent PR is ok for me - I'll go ahead and merge this if we can iterate in the near future.

**Comment by makortel** [comment]
@davidlange6 Thanks! I'll file a PR after we get an IB including this PR.

**Pull request merged**
