### PR TITLE
MET EE noise mitigation in 2017 data [remove unnecessary lines]

### PR DESCRIPTION
**Pull request by eioannou**
A new PR is related to the PR #24876 in which unnecessary lines have already removed from MET tool.

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
@eioannou @kpedro88 
A lot of differences in workflow 10224 (only that one): any explanation?

**Comment by kpedro88** [comment]
@perrotta 10224 is a PU workflow, and the differences occur upstream of the changes in this PR. Maybe the pileup input changed or there was some other random number shift?

**Comment by perrotta** [comment]
The minbias input file used in the baseline and in this PR test is the same.

Also logs are identical (warnings, etc.), till step3 at event 10 where  
in the baseline:
```
%MSG-e SiStripMonitorTrack:   
SiStripMonitorTrack:HLTSiStripMonitorTrack  05-Nov-2018 14:12:18 CET  
Run: 1 Event: 10
ClusterCollection is not valid!!
%MSG
0(4.7)
1(4.7)
2(4.7)
4(4.7)
5(4.7)
6(4.7)
05-Nov-2018 14:12:35 CET  Closed file file:step2.root
05-Nov-2018 14:12:38 CET  Closed file  
root://eoscms.cern.ch//eos/cms/store/user/cmsbuild/store/relval/CMSSW_10_0_0_pre2/RelValMinBias_13/GEN-SIM/100X_mc2017_realistic_v1-v1/20000/7206FE6B-89DC-E711-8556-0CC47A4C8F06.root
```
and in this PR test
```
%MSG-e SiStripMonitorTrack:   
SiStripMonitorTrack:HLTSiStripMonitorTrack  06-Nov-2018 00:25:31 CET  
Run: 1 Event: 10
ClusterCollection is not valid!!
%MSG
0(5.75)
1(5.75)
2(5.75)
4(5.75)
5(5.75)
6(5.75)
06-Nov-2018 00:25:58 CET  Closed file file:step2.root
06-Nov-2018 00:26:01 CET  Closed file  
root://eoscms.cern.ch//eos/cms/store/user/cmsbuild/store/relval/CMSSW_10_0_0_pre2/RelValMinBias_13/GEN-SIM/100X_mc2017_realistic_v1-v1/20000/7206FE6B-89DC-E711-8556-0CC47A4C8F06.root
```


Maybe this PR is not related, but I would just be curious to  
understand where the difference come from, and from where those  
outputs are originated.


Kevin Pedro <notifications@github.com> ha scritto:

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
+1
- There are no differences any more in the comparisons: as expected, they did not originate from this PR
- Lines defining an un-necessary default are removed: tests pass with no changes
- (This complements #24876, where this commit got simply lost during a rebase)

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Pull request merged**
