### PR TITLE
[12_5_X] Add check of Tracker HV in BeamSpot DQM clients

### PR DESCRIPTION
**Pull request by francescobrivio**
#### PR description:
Verbatim backport of  #39347
A check on the Tracker HV (both pixels and strips) is added in order not to run on events which are by construction not useful for the BeamSpot determination.
Plus some minor improvements to the DQM BeamSpot clients.

#### PR validation:
See master PR for validation

#### Backport:
Backport of #39347

### CODE REVIEW

**Comment by francescobrivio** [comment]
backport of #39347

**Comment by francescobrivio** [comment]
type performance-improvement

**Comment by francescobrivio** [comment]
@cmsbuild please test

**Comment by mandrenguyen** [comment]
+1

**Comment by saumyaphor4252** [comment]
+alca

**Comment by syuvivida** [comment]
+1

**Comment by rappoccio** [comment]
+1

**Pull request merged**
