### PR TITLE
Run3-hcx201 Modify Hcal geometry in view of no HE (backporting PR #26749)

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Modify Hcal reconstruction geometry in view of absence of HE 

#### PR validation:

Tested with runTheMattrix.py -l limited

#### if this PR is a backport please specify the original PR:

This is a backport of the PR #26749 to 10_6_X and it is a bug fix for all Phase2 geometry scenarios

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by pohsun** [comment]
+1

**Comment by cvuosalo** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
