### PR TITLE
Update HLT subtables after the migration to EOS

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Update the ConfDB subtables creation script following the migration of the repository from AFS to EOS:
  - fix a bug that prevented using the JAR files in-place;
  - update the curl command to follow redirects when downloading the JAR files over the web.

#### PR validation:

Creation of ConfDB subtables works again.

### CODE REVIEW

**Comment by fwyzard** [comment]
type bug-fix

**Comment by fwyzard** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
