### PR TITLE
Monitoring JSON changes in DAQ

### PR DESCRIPTION
**Pull request by smorovic**
Changes:
- migrating to JSON based format for module legend used by f3mon
- adding HLTErrorEvents field which will used to distinguish between losses caused by crashes in CMSSW and other reasons, for example hardware failures.

### CODE REVIEW

**Comment by mommsen** [comment]
+1

**Comment by fwyzard** [comment]
+1

**Comment by fwyzard** [comment]
HLT change looks reasonable

**Comment by deguio** [comment]
+1

**Comment by cvuosalo** [comment]
+1

For #12136 b9ccbe939e89560e2a47ef8328e00327d510f2c4

Changes in the monitoring JSON for the DAQ. #12137 and #12138 are the 76X and 80X versions of this PR.

The code changes are OK for 75X. The 80X version of this PR will require some small code changes for maintainability. Jenkins [tests](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-12136/9257/summary.html) against baseline CMSSW_7_5_X_2015-10-27-2300 show no significant differences.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
