### PR TITLE
Add L1T fractional prescale record [11_2_X]

### PR DESCRIPTION
**Pull request by christopheralanwest**
#### PR description:

This PR is a backport of PR #32758 and PR #32774. It also contains a fix to the data GTs to use the tag `L1TGlobalPrescalesVetosFract_Stage2v1_hlt` rather than `L1TGlobalPrescalesVetosFract_Stage2_v2_hlt` instead, as discussed at https://github.com/cms-sw/cmssw/pull/32741#issuecomment-769878721.

This PR adds a fractional prescale record `L1TGlobalPrescalesVetosFract_Stage2v1_hlt` for data GTs and `L1TGlobalPrescalesVetosFract_passThrough_mc` for MC to accommodate the new fractional L1 prescale functionality.

The additional removal of `SiPixelCPEGenericErrorParmRcd` from `112X_dataRun2_HLT_relval_v3` and `112X_dataRun2_HLT_relval_HI_v2` is a technical change only, removing an obsolete record.

The GT diffs are as follows:

**Run 2 (L1 trigger stage 1)**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_mcRun2_asymptotic_l1stage1_v1/112X_mcRun2_asymptotic_l1stage1_v2

**2016 design**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_mcRun2_design_v1/112X_mcRun2_design_v2

**2016 realistic pre-VFP era**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_mcRun2_asymptotic_preVFP_v2/112X_mcRun2_asymptotic_preVFP_v3

**2016 realistic post-VFP era**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_mcRun2_asymptotic_v2/112X_mcRun2_asymptotic_v3

**2016 cosmics (asymptotic conditions)**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_mcRun2cosmics_asymptotic_deco_v2/112X_mcRun2cosmics_asymptotic_deco_v3

**Run 2 heavy ion**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_mcRun2_HeavyIon_v1/112X_mcRun2_HeavyIon_v2

**Run 2 proton-lead**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_mcRun2_pA_v1/112X_mcRun2_pA_v2

**Offline data**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_dataRun2_v7/112X_dataRun2_v8

**Offline data (HEM failure)**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_dataRun2_HEfail_v7/112X_dataRun2_HEfail_v8

**Offline data relval**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_dataRun2_relval_v7/112X_dataRun2_relval_v8

**Prompt-like HI data**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_dataRun2_PromptLike_HI_v5/112X_dataRun2_PromptLike_HI_v6

**Run 2 HLT RelVals**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/103X_dataRun2_HLT_relval_v9/112X_dataRun2_HLT_relval_v3

**Run 2 HLT RelVals**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/103X_dataRun2_HLT_relval_HI_v5/112X_dataRun2_HLT_relval_HI_v2

**Run 3 data (express)**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/111X_dataRun3_Express_v4/112X_dataRun3_Express_v2

**Run 3 data (prompt)**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/111X_dataRun3_Prompt_v5/112X_dataRun3_Prompt_v2

**2017 design**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_mc2017_design_v2/112X_mc2017_design_v3

**2017 realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_mc2017_realistic_v4/112X_mc2017_realistic_v5

**2017 realistic cosmics (tracker deco mode)**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_mc2017cosmics_realistic_deco_v4/112X_mc2017cosmics_realistic_deco_v5

**2017 realistic cosmics (tracker peak mode)**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_mc2017cosmics_realistic_peak_v4/112X_mc2017cosmics_realistic_peak_v5

**2018 design**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_upgrade2018_design_v4/112X_upgrade2018_design_v5

**2018 realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_upgrade2018_realistic_v7/112X_upgrade2018_realistic_v8

**2018 heavy ion**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_upgrade2018_realistic_HI_v7/112X_upgrade2018_realistic_HI_v8

**2018 realistic (HEM15/16 failure)**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_upgrade2018_realistic_HEfail_v7/112X_upgrade2018_realistic_HEfail_v8

**2018 cosmics (tracker deco mode)**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_upgrade2018cosmics_realistic_deco_v7/112X_upgrade2018cosmics_realistic_deco_v8

**2018 cosmics (tracker peak mode)**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_upgrade2018cosmics_realistic_peak_v7/112X_upgrade2018cosmics_realistic_peak_v8

**2021 design**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_mcRun3_2021_design_v12/112X_mcRun3_2021_design_v13

**2021 realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_mcRun3_2021_realistic_v15/112X_mcRun3_2021_realistic_v16

**2021 cosmics**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_mcRun3_2021cosmics_realistic_deco_v15/112X_mcRun3_2021cosmics_realistic_deco_v16

**2021 heavy ion**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_mcRun3_2021_realistic_HI_v15/112X_mcRun3_2021_realistic_HI_v16

**2023 realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_mcRun3_2023_realistic_v15/112X_mcRun3_2023_realistic_v16

**2024 realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_mcRun3_2024_realistic_v15/112X_mcRun3_2024_realistic_v16

**Phase 2 realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_mcRun4_realistic_v5/112X_mcRun4_realistic_v6

#### PR validation:

The tag for data was prepared by ensuring that the fractional prescale payload is consistent with that used for the old, legacy, integral prescales. See the following presentation for details: https://indico.cern.ch/event/974057/#35-integration-of-l1t-new-frac

In addition, technical tests were performed:

`addOnTests -j 8` and `runTheMatrix.py -l limited,1325.516,7.22,136.8642,10424.0,7.21,11224.0,11024.2,7.4,12024.0,7.23,159.0,12834.0 --ibeos`

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

This PR is a backport of #32758 (with an additional bug fix) to 112X for use in the upcoming MWGR.

### CODE REVIEW

**Comment by christopheralanwest** [comment]
backport #32758

**Comment by christopheralanwest** [comment]
test parameters
- workflow = 1325.516,7.22,136.8642,10424.0,7.21,11224.0,11024.2,7.4,12024.0,7.23,159.0,12834.0
- pull_request = #32744

**Comment by christopheralanwest** [comment]
please test

**Comment by christopheralanwest** [comment]
@rekovic @hjkwon260 Please let me know if the differences in the comparison tests are as expected. Alternatively, I could test this PR with the now-closed PR #32377 to try to eliminate the differences arising from the uGT emulation of displaced muons.

**Comment by silviodonato** [comment]
test parameters
- workflow = 1325.516,7.22,136.8642,10424.0,7.21,11224.0,11024.2,7.4,12024.0,7.23,159.0,12834.0
- pull_request = #32377

**Comment by silviodonato** [comment]
please test

**Comment by silviodonato** [comment]
> @rekovic @hjkwon260 Please let me know if the differences in the comparison tests are as expected. Alternatively, I could test this PR with the now-closed PR #32377 to try to eliminate the differences arising from the uGT emulation of displaced muons.

The differences were related to the L1 muons, so it should be ok

**Comment by christopheralanwest** [comment]
+1

- Backport has same GT differences as PR to master (aside from two removals of obsolete tags)
- No differences observed in PR comparison tests aside from known reproducibility issues
- Failure in last round of tests not seen in previous round and unrelated to this PR

**Comment by silviodonato** [comment]
+1
the error in ` dasgoclient --limit 0 --query 'file dataset=/RelValPhotonJets_Pt_10_13/CMSSW_10_6_0-106X_mcRun2_asymptotic_v3-v1/GEN-SIM site=T2_CH_CERN' | ibeos-lfn-sort -u > step1_dasquery.log  2>&1` is definitely not related to this PR

**Comment by silviodonato** [comment]
merge

**Pull request merged**
