### PR TITLE
Run3-sim118I  Make use of tokens to access collection rather than just labels in SimMuon/RPCDigitizer

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Make use of tokens to access collection rather than just labels in SimMuon/RPCDigitizer

#### PR validation:

Use the runTheMatrix test workflows 

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
