### PR TITLE
Spy Software update

### PR DESCRIPTION
**Pull request by Jangbae**
Wrong product labels for spy data fixed. And a script printing out input list added.

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by dmitrijus** [comment]
This is a followup for https://hypernews.cern.ch/HyperNews/CMS/get/swDevelopment/3425.html

@Jangbae Please introduce yourself to the DQM team (by sending us an email).

**Comment by mmusich** [comment]
Dear @dmitrijus, 
@Jangbae is working within the Strip DAQ Online / Online group to revamp the analysis framework for the SpyChanel data. This stream of data is *not* processed by any regular production CMS workflow as it contains special non-zero suppressed SiStrip data frames (basically is an alternative source of Virgin Raw), and it is uniquely meant for debugging and monitoring purposes of low-level Strip reconstruction. While it is not completely clear to me why the package `SiStripMonitorHardware` lives in `DQM` in the first place, this update is meant as una tantum to recover the ability to process SpyChannel data. 
While I certainly encourage @Jangbae to introduce himself to the DQM core team, this should not be a showstopper to get the PR signed, as this is a blocker for further development and documentation. Thanks for your understanding.
Attn: @boudoul @echabert

**Comment by dmitrijus** [comment]
+1

**Comment by mmusich** [comment]
@fabiocos, is there any outstanding issue with this PR, preventing it from being merged?
Thank you

**Comment by fabiocos** [comment]
@mmusich The change in itself looks ok and I will merge it. Nevertheless the purpose of this package seems different wrt the regular DQM code, and probably its location is not optimal

**Comment by fabiocos** [comment]
+1

**Comment by mmusich** [comment]
> @mmusich The change in itself looks ok and I will merge it. Nevertheless the purpose of this package seems different wrt the regular DQM code, and probably its location is not optimal.

@fabiocos in relation to your comment https://github.com/cms-sw/cmssw/pull/21432/#issuecomment-358412125 we do acknowledge the location is not optimal. Would you care to suggest a more suitable location? Given the nature of the codes, we were thinking about somewhere under the `daq` or `reco` signature area. Thanks in advance.

**Pull request merged**
