### PR TITLE
fix the output name repetition issue and adjust the job splitting

### PR DESCRIPTION
**Pull request by zhenhu**
To fix the dataset name issue in the new HI workflow 144.55 introduced in PR #24484

### CODE REVIEW

**Comment by zhenhu** [comment]
please test 144.55

**Comment by zhenhu** [comment]
please test workflow 140.55

**Comment by zhenhu** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade

**Comment by fabiocos** [comment]
+1

**Pull request merged**
