### PR TITLE
fix "improveWithTrack" for OT hit

### PR DESCRIPTION
**Pull request by VinInn**
it was forgotten...
It surely affects refit, will affect standard tracking as well.

urgent bugfix

### CODE REVIEW

**Comment by VinInn** [comment]
type bugfix

**Comment by VinInn** [comment]
@cmsbuild, please test

**Comment by VinInn** [comment]
@ebrondol

**Comment by VinInn** [comment]
@rovere

**Comment by VinInn** [comment]
@cmsbuild , please test

**Comment by VinInn** [comment]
do not expect regression as Phase OT CPE does not yet make use of track angle...
At least is ready for the time when this will eventually happen

**Comment by dmitrijus** [comment]
+1

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/17571	3fe84b7
- implementation is in line with the description; as noted in https://github.com/cms-sw/cmssw/pull/17571#issuecomment-281155514 the current tracking setup for phase-2 is not using the affected feature and no changes are expected in standard workflows.
- jenkins tests pass and comparisons with baseline show no differences

this apparently fixes the problem reported in 
https://hypernews.cern.ch/HyperNews/CMS/get/recoTracking/1672/1/1/2/1/1/1/1/1.html

**Comment by davidlange6** [comment]
+1

**Pull request merged**
