### PR TITLE
Revert "Disable Xrootd's read recovery mechanism."

### PR DESCRIPTION
**Pull request by davidlange6**
Reverts cms-sw/cmssw#18128

### CODE REVIEW

**Comment by Dr15Jones** [comment]
@davidlange6 what motivated this?

**Comment by davidlange6** [comment]
https://hypernews.cern.ch/HyperNews/CMS/get/comp-ops/3578.html

**Comment by Dr15Jones** [comment]
@davidlange6 thanks. It looks like the specific request is from @bbockelm 
https://hypernews.cern.ch/HyperNews/CMS/get/comp-ops/3578/1/1/1/2/1/2/1/1/1.html

**Comment by davidlange6** [comment]
Right - also discussed in person

**Comment by Dr15Jones** [comment]
+1

**Pull request merged**
