### PR TITLE
pr90x Update 2023 RelVal workflows with HLT@fake2

### PR DESCRIPTION
**Pull request by rekovic**
Switch from HLT@fake to fake2 in 2023 RelVal workflows, by changing the 
configuration of upgradeWorkflowComponents. 

This is needed since we are switching from L1TLegacy to L1TStage2 for Phase2, 
and HLT PR #17795 is introducing an appropriate HLT@fake2 menu. 

To test, needs both #17795 and #17629 merged.

### CODE REVIEW

**Comment by rekovic** [comment]
backport of #17811.

**Comment by kpedro88** [comment]
is there a reason this is needed in both 90X and 91X?

**Comment by rekovic** [comment]
Maybe not...I was maybe mislead by the automatically ported non-merged 90x PRs to 91x.

By the way, what is 91x intended for?

**Comment by kpedro88** [comment]
I think 91X is intended to be used for 2017 prompt reconstruction (and maybe central MC production also).

But for Phase2, we just keep developing in the current development branch (whatever it is), and make an offshoot production release when needed.

**Comment by rekovic** [comment]
Thanks.  Can probably then close  #17811.

**Comment by kpedro88** [comment]
I think you mean you can close this one...

**Comment by rekovic** [comment]
Yes, that is what I meant, but will wait for @davidlange6 to comment.

**Comment by rekovic** [comment]
this is now part of #17629.  can close.

**Pull request closed without merging**
