### PR TITLE
JME python configuration cleanup for 92x 

### PR DESCRIPTION
**Pull request by rappoccio**
The JME python configurations had many vestiges left of previous migrations, as well as considerable "top-level" customization that is no longer relevant. I have consolidated the RecoPFJets_cff customizations into separate cfi python files in RecoJets/JetProducers. 

- Removed iterative cone, SIScone, and AK5 PF and Calo jets in all configurations. 
- Consolidated the various grooming schemes into a single file per jet radius (so, AK4 puppi is now in ak4PFJets_cfi, for instance).
- Left AK4, AK8, KT4, KT6, and only AK5/7 Castor collections since those are the only ones used anywhere in the repository. 
- Added an example AK8 GenJet configuration with grooming applied, since this is a common question. It is not presently run anywhere, though. 

EDIT: No changes should occur to any output, this is a reorganization.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
To quote the last summary of results of jenkins tests:
```
ROOTFileChecks: Some differences in event products or their sizes found
Reco comparison results: 565 differences found in the comparisons
```

this contradicts the PR description:
``` No changes should occur to any output, this is a reorganization.```

Sorry, I should have noticed this a week ago.

Lookins at wf 25.0 reco:
- cmsTopTagPFJetsCHS are gone
- there are ~3 times more ak8PFJetsCHS (from 31 to 111)

Additionally, in 2023 workflows (23234.0)
- there are small changes in ak8PFJetsCHSPruned

miniAOD slimmed jets look completely different:
all_mini_oldvsnew_runsingleph2016bwf136p731c_log10patjets_slimmedjets__rereco_obj_et
all_mini_oldvsnew_runsingleph2016bwf136p731c_patjets_slimmedjets__rereco_obj_eta

**Comment by rappoccio** [comment]
I am looking now, sorry about that. I think my check was not taking into account "checkdeps".

**Comment by rappoccio** [comment]
Grrr. something went wrong with git. I will rebase.

**Comment by rappoccio** [comment]
I can't seem to fix the git problems, I will close this PR and reopen a new one.

**Comment by kpedro88** [comment]
@rappoccio in the future please follow http://cms-sw.github.io/tutorial-resolve-conflicts.html

**Comment by rappoccio** [comment]
Thanks, this is helpful.

**Pull request closed without merging**
