### PR TITLE
Use openloops path variable instead of hardcoded path

### PR DESCRIPTION
**Pull request by thuer**
Replace hard coded path to openloops with environment variable
Works only after https://github.com/cms-sw/cmsdist/pull/1805 for cmsdist is merged

### CODE REVIEW

**Comment by bendavid** [comment]
if the path is available as an environment variable, can't it just be read from the environment directly from inside the C++ code rather than passing it indirectly through the python?  Do we ever need to be able to change it to a different path from the environment variable?

**Comment by thuer** [comment]
The advantage of having it in the python fragment is that you always know with which arguments Sherpa is called exactly, if we start to add certain things in the C++ interface it will be hard to debug once something does not work (e.g. you also need to specify the path if you want to use the Sherpa in CMSSW standalone)

**Comment by davidlt** [comment]
ping^1

**Comment by bendavid** [comment]
+1

**Comment by davidlange6** [comment]
@cmsbuild, please test

**Comment by davidlange6** [comment]
+1

**Pull request merged**
