### PR TITLE
setup to run miniAOD on legacy 80X AOD inputs

### PR DESCRIPTION
**Pull request by slava77**
- run2_miniAOD_80XLegacy modifier (to be added to the list of eras with Run2_2016 or related)
- updates from #18828 for deep flavor 
- disable chargedHadronIsolation reading in packedPFCandidates (it is not available in 80X)

Tested in CMSSW_9_2_3_patch1 with the following:

for MC:
```
cmsDriver.py step3  --conditions auto:run2_mc --mc --scenario pp --process PAT --era Run2_2016,run2_miniAOD_80XLegacy --eventcontent MINIAODSIM,DQM --runUnscheduled  -s PAT,VALIDATION:@miniAODValidation,DQM:@miniAODDQM --datatier MINIAODSIM,DQMIO  -n 3000 --filein /store/mc/RunIISummer16DR80Premix/TT_TuneCUETP8M2T4_13TeV-powheg-pythia8/AODSIM/PUMoriond17_backup_80X_mcRun2_asymptotic_2016_TrancheIV_v6-v1/00000/004973E8-26BA-E611-93E0-A0000420FE80.root  --fileout file:step3.root > step3.log  2>&1 

cmsDriver.py step4  --filetype DQM --conditions auto:run2_mc --mc  --scenario pp -s HARVESTING:@miniAODValidation+@miniAODDQM --era Run2_2016,run2_miniAOD_80XLegacy -n -1 --filein file:step3_inDQM.root --fileout file:step4.root  > step4.log  2>&1 

```

for data:
```
cmsDriver.py step3  --conditions auto:run2_data --data --scenario pp --process PAT --era Run2_2016,run2_miniAOD_80XLegacy --eventcontent MINIAOD,DQM --runUnscheduled  -s PAT,DQM:@miniAODDQM --datatier MINIAOD,DQMIO  -n 3000 --filein /store/data/Run2016E/MET/AOD/18Apr2017-v1/120001/A21C3008-A548-E711-A90D-FA163E26AC84.root  --fileout file:step3.root > step3.log  2>&1 

cmsDriver.py step4  --filetype DQM --conditions auto:run2_data --data --scenario pp  -s HARVESTING:@miniAODDQM --era Run2_2016,run2_miniAOD_80XLegacy -n -1 --filein file:step3_inDQM.root --fileout file:step4.root  > step4.log  2>&1 
```

Here are a couple of plots from the MET PD (instructions above):
- some things are essentially the same (with recognizeable changes [simple , e.g. p4 kinematics pf packedCandidates is the same)]:
all_8_0_28_patch1-orig-patvs9_2_3_patch1-sign917-pat_met18apr2017c_patpackedcandidates_packedpfcandidates__pat_obj_packeddxy_

- Some things differ more (and I don't obviously recognize the difference
E.g. in slimmedJets (maybe cleaning is not the same? it's the same ak4PFJetsCHS on input from AOD directly)
all_8_0_28_patch1-orig-patvs9_2_3_patch1-sign917-pat_met18apr2017c_log10patjets_slimmedjets__pat_obj_et
)
all_8_0_28_patch1-orig-patvs9_2_3_patch1-sign917-pat_met18apr2017c_log10patjets_slimmedjets__pat_obj_energy
Note that ak4PFJets 

@mverzett @kmcdermo @arizzi @gpetruc 

@fabozzi please take a look to possibly set up a matrix workflow to have this regularly tested.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cmsbuild please test
the last attempt failed, but was not recognized by the bot

@smuzaffar please take a look at what happened in connection to
https://cmssdt.cern.ch/jenkins/job/ib-any-integration/20656/console
Thank you

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/19304	bb794a7
- setup for special workflows using run2_miniAOD_80XLegacy modifier ; current standard workflows are not affected
- jenkins tests pass and comparisons show no differences

**Comment by davidlange6** [comment]
hi @slava77 - could we not just use the 2016 era instead of defining a new era? This is presumably now the desired miniaod code for 2016 data, right?

**Comment by gpetruc** [comment]
I think a new era is better, since this switch is for processig in 9XY the
2016 data reconstructed in 80X (for 2016 data reconstructed in 9XY, the
standard 9XY miniAOD configuration is to be used, not this one)

**Comment by slava77** [comment]
On 6/20/17 2:18 AM, David Lange wrote:
> hi @slava77 <https://github.com/slava77> - could we not just use the
> 2016 era instead of defining a new era? This is presumably now the
> desired miniaod code for 2016 data, right?
> 

As Giovanni clarified: this is a support to read 80X AOD inputs
and to modify parts that are different.
The 2016 era (the Run2_2016) is used in 9X to also create RECO&AOD
consistent with 9X.
Both 9X AOD inputs and 80X AOD inputs can not be supported by the same
era alone.
It's possible to get the same functionality with customization.

Perhaps I'm missing some details.
Please clarify.

**Comment by davidlange6** [comment]
ok now I understand, kind of an abuse of the mechanism - but customize is worse. I'll have a look.

**Comment by davidlange6** [comment]
so lets move forward - however, we lack a mechanism parallel to what we have in other workflow components (eg, -s RECO:trackingOnly) as the configs are unscheduled.

Should we not control via a config variable longer term? 

Eg, one could do -s PAT:redoJets

which sets process.miniAODControl.redoJets=1 that propagates down - (I guess this is not so different from eras, but keeps the distinct concepts as distinct.

**Comment by davidlange6** [comment]
merge

**Comment by slava77** [comment]
On 6/20/17 7:17 AM, David Lange wrote:
> so lets move forward - however, we lack a mechanism parallel to what we
> have in other workflow components (eg, -s RECO:trackingOnly) as the
> configs are unscheduled.
> 
> Should we not control via a config variable longer term?
> 
> Eg, one could do -s PAT:redoJets
> 
> which sets process.miniAODControl.redoJets=1 that propagates down - (I
> guess this is not so different from eras, but keeps the distinct
> concepts as distinct.

These flags will need to apply uniformly to PAT, DQM, and VALIDATION
steps to be somewhat more general.
It's not just about redoing something that can recover the inputs to the
state identical in the current release.
In some cases it's about descoping/abandoning some inputs/outputs which
can not be redone.

I think that this support should be available at process load level,
something that's not possible to override by loading PSet fragments,
similar to Era.
On a quick thought, this all sounds like a proposal for a different
mechanism provided by the era mechanism,
which is fine if so desired.

Once framework can support this, we can make necessary updates.

**Pull request merged**
