### PR TITLE
Skimming code for B parking with lepton and 2 tracks

### PR DESCRIPTION
**Pull request by gkaratha**
Dear experts,

This is the first version of the skimming code for B Parking. We want to to save events with 1 lepton and two tracks in order to be used with the new low pT electron reconstruction. Thanks.

Best regards,
George

### CODE REVIEW

**Comment by kfjack** [comment]
@franzoni Yes, I have discussed with George on Tuesday for how to have this setup. But I think we need a corresponding PR to master branch first. 
@gkaratha I think we need a PR for master (10_4_X) first (and "backport" to this version). Do you want me to do it or you want to do it by yourself?

**Comment by gkaratha** [comment]
@kfjack Yes I tried that yesterday. Unfortunately i get this error for CMSSW_10_4_0[*]. Is there another way? thanks


[*]
ERROR: Unable to find release area for "CMSSW" version "CMSSW_10_4_0" for arch slc6_amd64_gcc472.
       Please make sure you have used the correct name/version.
       You can run "scram list CMSSW" to get the list of available versions.

**Comment by gkaratha** [comment]
@mverzett PR for skim

**Comment by kfjack** [comment]
@gkaratha Could you try to pick up the newest IB build to integrate your code?
http://cms-sw.github.io/showIB.html
(If still not working, I can work with you directly today, let me know when/where to meet in this case.)

**Comment by davidlange6** [comment]
while making the PR for the master branch some things to consider

1) avoid TMath and TString
2) clean up the dependencies (presumably this skim can not actually depend on simulation information
3) use the part of root needed include of <use name=root> in the buildfile
4) use existing implementations of dphi and dr
5) avoid std::pair<std::vector<float>,std::vector<std::vector<std::vector<float>>>> [it looks like the code depends on an exact size of all of these data structures, so just create them as std::array and pass by value]
6) if you know how many values to push back in a vector, then reserve its size first
7) at is close than [i] when you know you are not overflowing arrays
8) consider range based loops to avoid copying objects unnecessarily 
9) avoid checking trigResults->accept(i_Trig)) multiple times

**Comment by gkaratha** [comment]
Dear all,

@kfjack ok I found it . Thanks
@davidlange6 Thanks for the comments. Ok will take care of them first then make PR to master.

Best regards,
George

**Comment by fabiocos** [comment]
@gkaratha as the development happens now in 10_5_X and the production backport will be in 10_2_X, can we just close this PR?

**Comment by gkaratha** [comment]
Dear @fabiocos ,

Yes you are right ! I am closing it now. Thanks.

Best regards,
George

**Pull request closed without merging**
