### PR TITLE
Remove boost and root deps from SimDataFormats/EncodedEventId

### PR DESCRIPTION
**Pull request by guitargeek**
Some dependency cleaning. No backport intended.

### CODE REVIEW

**Comment by silviodonato** [comment]
please test

**Comment by agrohsje** [comment]
please test

**Comment by civanch** [comment]
please test

**Comment by cecilecaillol** [comment]
+l1

**Comment by civanch** [comment]
@guitargeek , it seems FastSim is affected by this clean-up. @sbein , can you, please, have a look?

**Comment by guitargeek** [comment]
Hi @sbein, are these changes OK for you?

**Comment by civanch** [comment]
+1

observed difference likely connected with small differences in computation of cosine.
I would suggest to merge this PR.

**Comment by guitargeek** [comment]
Thanks! What about @l2-generators and @l2-upgrade?

**Comment by guitargeek** [comment]
Thanks! What about generators and upgrade? @agrohsje, @alberto-sanchez, @kpedro88, @srimanob.

**Comment by agrohsje** [comment]
+generators

**Comment by srimanob** [comment]
+Upgrade

Technical PR to remove boost and root dependency. Small changes have been observed due to the calculation of trigonometry function.

**Comment by silviodonato** [comment]
+1

**Pull request merged**
