### PR TITLE
Fix L1 fat event filters (80x bis)

### PR DESCRIPTION
**Pull request by rekovic**
80x version of 81x #16782, and of 90x #16799.

This is a replacement for 80x #16765
as it contains the addendum (cherry-picked 0537ca83ee2cb50fcc235de050243250a52b3107 from  #16782)

For completion, here is the original header:
>Fixes for two filters used to select L1T "fat events", to use of the 64-bit event number from TCDS FED word 11 (https://twiki.cern.ch/twiki/bin/viewauth/CMS/TcdsEventRecord#TCDS_Data_Block_Definition_curre) instead of the 24-bit event number from common DAQ header.
>In the case of HLTL1NumberFilter, use of the common DAQ header (ie. existing functionality) is maintained as default.

### CODE REVIEW

**Comment by rekovic** [comment]
please test

**Comment by rekovic** [comment]
+1

**Comment by fwyzard** [comment]
+1

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
Hi @rekovic - for the 90x PR, didn't we move the fed 1024 readout into the already existing tcds unpacker? That should be back ported here.

**Comment by davidlange6** [comment]
Ping @rekovic

**Comment by rekovic** [comment]
Two above commits ( 8fb42dc and 8574895) cherry-picked from the merged 90x https://github.com/cms-sw/cmssw/pull/17082.  
These commits address comment of David https://github.com/cms-sw/cmssw/pull/16806#issuecomment-275487178 .

**Comment by rekovic** [comment]
please test

**Comment by rekovic** [comment]
+1

**Pull request merged**
