### PR TITLE
Fireworks-master:  Fix position of phase2 clusters in 3D and projected views

### PR DESCRIPTION
**Pull request by alja**
## Description
This PR fixes positioning of Phase -2 clusters in the Fireworks event display.
In the screenshot below clusters are rendered as blue point and a marker.

strip-len

### CODE REVIEW

**Comment by alja** [comment]
+1

**Comment by alja** [comment]
@slava77 This is the correction for phase2 clusters. Let me know if you want to backport this change.

**Comment by qliphy** [comment]
@alja  Would you please add some more meaningful detailed description?

**Comment by alja** [comment]
@qliphy I edited title and the comment so it is more clear the PR is about event display.

**Comment by qliphy** [comment]
+1

**Pull request merged**
