### PR TITLE
[80X backport] Allow a boost on particles in PythiaMomDauFilter, PythiaFilter and PythiaFilterMultiMother

### PR DESCRIPTION
**Pull request by zc11**
80X backport of #20140

### CODE REVIEW

**Comment by perrozzi** [comment]
please test

**Comment by perrozzi** [comment]
please test

**Comment by perrozzi** [comment]
+1

**Comment by perrozzi** [comment]
please test

**Comment by perrozzi** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
