### PR TITLE
Removed direct use of tbb::task from SerialTaskQueue

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

- removed pushAndGetNextTaskToRun as it was never used
- applied new code-format

#### PR validation:

Code compiles. No functional changes are expected as this was a minor interface change to use a related class type.

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
@cmsbuild, please test

(for cleaner comparisons)

**Comment by makortel** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
