### PR TITLE
Prepare HcalTPGCoderULUT for concurrent IOVs

### PR DESCRIPTION
**Pull request by wddgit**
Currently the Framework only allows one EventSetup IOV (Interval of Validity) to be processed at a time, but we are preparing to change this in the future and allow multiple concurrent IOVs. This PR modifies the ESProducer of type HcalTPGCoderULUT in preparation for this change.

Prior to this, the ESProducer held a pointer to a single HcaluLUTTPGCoder object. After this PR it will use the ReusableObjectHolder class to manage multiple objects of this type, one for each concurrent IOV. The objects needs to hold different content for different IOVs and the ESProducer needs to modify them during its produce call in a thread safe manner.

The dependsOn feature of the EventSetup has difficulty communicating with these different objects in the callbacks and produce function calls. The usage of the dependsOn feature is replaced by usage of the new ESProductHost class. It has a similar purpose, but works better when there are multiple IOVs because its interface allows direct communication via arguments between the produce methods and the lambda function that gets called when the dependent record changes.

Note that the one very minor change in DataFormats/HcalRecHit is a bug fix. It was failing to compile with debug flags because a static member variable which needed to be defined was not defined.

### CODE REVIEW

**Comment by wddgit** [comment]
please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/24496	8379dbf
- changes in reco-related code are only in DataFormats/HcalRecHit/src/HFQIE10Info.cc. The change is technical.
- jenkins tests pass and comparisons with the baseline show no differences

**Comment by fabiocos** [comment]
@rekovic @thomreis could you please check and sign it?

**Comment by fabiocos** [comment]
@rekovic @thomreis could you please check and sign it?

**Comment by thomreis** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
