### PR TITLE
Run3-gem68 Add the modified xml file for GE21 demonstration chamber used in the 2022 and 2023 scenarios

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Add the modified XML files for the GE21 demonstration chamber used in the 2022 and 2023 scenarios

#### PR validation:

Tested with Geant4 overlap tool

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

May need back porting if new Geometry scenarios to be created for Run3

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by bsunanda** [comment]
@rappoccio, @sextonkennedy, @antoniovilela Please merge this

**Comment by bsunanda** [comment]
@rappoccio, @sextonkennedy, @antoniovilela Please merge this

**Comment by rappoccio** [comment]
+1

**Pull request merged**
