### PR TITLE
The cut parser is now const-thread-safe

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

- isolated the components of the cut parser to their own subdirectory within the interface directory.
- mutable which were being used as temporary storage were either removed or changed to thread safe containers. Using to container allows each thread to get its own temporary instance of the storage and returns it for later use when it is no longer needed.
- extended the thread based unit test to also test that an object shared across threads operates properly.

#### PR validation:

Code compiles. All unit tests pass.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
please test

**Comment by emanueleusai** [comment]
+1

- dqm differences in 11634.911 do not seem to be related to this PR

**Comment by VinInn** [comment]
Does it require changes in the user code?

**Comment by Dr15Jones** [comment]
> Does it require changes in the user code?

Only that one can now call it re-entrantly rather than having to run an independent copy on each thread. The API remains the same.

**Comment by VinInn** [comment]
So It does require changes in the EDProducer to use only one. Any example?

**Comment by Dr15Jones** [comment]
> So It does require changes in the EDProducer to use only one. Any example?

If a module were a `stream::` module only because it was using the cut parser, the module could now become a `global::`.

**Comment by VinInn** [comment]
ok.
we should try with this one
https://cmssdt.cern.ch/dxr/CMSSW/source/DPGAnalysis/SiStripTools/plugins/ByMultiplicityEventFilter.cc#47
that in your report was second (even if it has just two different instances with pretty trivial cuts (as old as 5_3)

**Comment by Dr15Jones** [comment]
On a very cursory look at ROOT's TMethod code, it seems to me like the cling generated wrappers that enable calling class methods should be a one time creation (i.e. the generated code should be shared across the entire program). If that is the case, the large memory use by the StringCutObjectSelector should be shared across all threads trying to parse values from the same C++ class. In that way, sharing the same StringCutObjectSelector across threads (or having a separate one per thread) may not give us much memory savings. To prove if that is true or not, one could use igprof to on a 1 thread vs an 8 thread job and then compare memory usage.

**Comment by mandrenguyen** [comment]
+reconstruction
Technical.  Changes to wf 11634 must be unrelated.

**Comment by perrotta** [comment]
+1

**Pull request merged**
