### PR TITLE
Migrate `assert` to to `ALPAKA_ASSERT_ACC` [14.0.x]

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Migrate `assert()` to `ALPAKA_ASSERT_ACC()`.

#### PR validation:

None.

Backport of #44802 to 14.0.x for data taking.

### CODE REVIEW

**Comment by fwyzard** [comment]
backport #44802

**Comment by fwyzard** [comment]
+heterogeneous

**Comment by fwyzard** [comment]
enable gpu

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
urgent

@cms-sw/orp-l2 please include this PR in the next CMSSW 14.0.x full release.
It is needed to support centrally enabling/disabling assertions in Alpaka GPU code, to evaluate the trade-off between improved error messages and faster HLT throughput.

**Comment by mandrenguyen** [comment]
+1
errors are clearly unrelated to this PR

**Comment by fwyzard** [comment]
please test

The CMSSW_14_0_X_2024-04-22-2300 is hopefully in a better state.

**Comment by perrotta** [comment]
+1
- Identical to the PR in the master branch
- This being technical, even if the master is not yet tested in IB, I can sign for alca/db: then the release managers will decide when to merge

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
