### PR TITLE
Fixing issue of PS cluster matched to  >1 EE cluster in DBG_X IBs

### PR DESCRIPTION
**Pull request by swagata87**
#### PR description:

Currently several workflows of debug IBs fail with the error message `Found a PS cluster matched to more than one EE cluster!`. This was reported in https://github.com/cms-sw/cmssw/issues/34097 and https://github.com/cms-sw/cmssw/pull/35524 . This PR is aimed at fixing this. 

It looks like the problem was here:
https://github.com/cms-sw/cmssw/blob/b4bb14f6573e803ecbe516d306d651d9774d48b7/RecoEcal/EgammaClusterAlgos/src/PFECALSuperClusterAlgo.cc#L420-L422

In particular, `i.key()` seems to give a garbage value. To bypass the issue, `std::find_if` is replaced by `std::find` in a way that we do not need to access `.key()` of `CaloCluster` anymore. This is similar to what was done here: https://github.com/cms-sw/cmssw/blob/cc5a950c6e11d1b3a4dd39b8dff8a9161ecd1037/RecoParticleFlow/PFProducer/src/PFEGammaAlgo.cc#L1869-L1870

This small change seems to solve the problem.

#### PR validation:

Tested from `CMSSW_12_3_DBG_X_2022-01-06-2300` using workflows `117.0` and `11630.0`.

This PR is not a backport.
Backport not needed.

_PS: After the first round of tests, another crash was found in DBG build (only in WF `25202.0`):_ 
```
%MSG-e BasicSingleTrajectoryState:  GsfTrackProducer:lowPtGsfEleGsfTracks  09-Jan-2022 17:26:01 UTC Run: 1 Event: 1
asking for componenets to a SingleTrajectoryState
%MSG
cmsRun: /data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/4cd3ceaede4e18eb9ab43f14fe009004/opt/cmssw/slc7_amd64_gcc10/cms/cmssw/CMSSW_12_3_DBG_X_2022-01-06-2300/src/TrackingTools/TrajectoryState/src/BasicTrajectoryState.cc:248: virtual const Components& BasicSingleTrajectoryState::components() const: Assertion `false' failed.
```
_I took the opportunity to fix that as well._

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test for CMSSW_12_3_DBG_X

**Comment by smuzaffar** [comment]
please test

**Comment by jpata** [comment]
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-867ebb/21578/runTheMatrix-results/25202.0_TTbar_13+TTbar_13+DIGIUP15_PU25+RECOUP15_PU25+HARVESTUP15_PU25+NANOUP15_PU25/step3_TTbar_13+TTbar_13+DIGIUP15_PU25+RECOUP15_PU25+HARVESTUP15_PU25+NANOUP15_PU25.log

```
%MSG-e BasicSingleTrajectoryState:  GsfTrackProducer:lowPtGsfEleGsfTracks  09-Jan-2022 17:26:01 UTC Run: 1 Event: 1
asking for componenets to a SingleTrajectoryState
%MSG
cmsRun: /data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/4cd3ceaede4e18eb9ab43f14fe009004/opt/cmssw/slc7_amd64_gcc10/cms/cmssw/CMSSW_12_3_DBG_X_2022-01-06-2300/src/TrackingTools/TrajectoryState/src/BasicTrajectoryState.cc:248: virtual const Components& BasicSingleTrajectoryState::components() const: Assertion `false' failed.


A fatal system signal has occurred: abort signal
The following is the call stack containing the origin of the signal.

...
#9  0x00002b07b4be2818 in BasicSingleTrajectoryState::components (this=<optimized out>) at /data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/4cd3ceaede4e18eb9ab43f14fe009004/opt/cmssw/slc7_amd64_gcc10/cms/cmssw/CMSSW_12_3_DBG_X_2022-01-06-2300/src/TrackingTools/TrajectoryState/src/BasicTrajectoryState.cc:248
#10 0x00002b081c908ac2 in TrajectoryStateOnSurface::components (this=<synthetic pointer>) at /data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/4cd3ceaede4e18eb9ab43f14fe009004/opt/cmssw/slc7_amd64_gcc10/cms/cmssw/CMSSW_12_3_DBG_X_2022-01-06-2300/src/TrackingTools/TrajectoryState/interface/TrajectoryStateOnSurface.h:85
#11 operator() (tsos=<synthetic pointer>..., __closure=<synthetic pointer>) at /data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/4cd3ceaede4e18eb9ab43f14fe009004/opt/cmssw/slc7_amd64_gcc10/cms/cmssw/CMSSW_12_3_DBG_X_2022-01-06-2300/src/RecoTracker/TrackProducer/src/TrackProducerAlgorithm.cc:288
#12 TrackProducerAlgorithm<reco::GsfTrack>::buildTrack (this=this@entry=0x2b086fd43098, theFitter=<optimized out>, thePropagator=thePropagator@entry=0x2b086f695d80, algoResults=..., hits=..., theTSOS=..., seed=..., ndof=ndof@entry=0, bs=..., seedRef=..., qualityMask=<optimized out>, nLoops=<optimized out>) at /data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/4cd3ceaede4e18eb9ab43f14fe009004/opt/cmssw/slc7_amd64_gcc10/cms/cmssw/CMSSW_12_3_DBG_X_2022-01-06-2300/src/RecoTracker/TrackProducer/src/TrackProducerAlgorithm.cc:302
#13 0x00002b081c795ce8 in TrackProducerAlgorithm<reco::GsfTrack>::runWithCandidate (this=this@entry=0x2b086fd43098, theG=0x2b089e83b200, theMF=0x2b08969d5f30, theTCCollection=..., theFitter=theFitter@entry=0x2b08bd4e6590, thePropagator=thePropagator@entry=0x2b086f695d80, builder=0x2b08f00a6dc0, bs=..., algoResults=...) at /data/cmsbld/jenkins/workspace/build-any-ib/w/slc7_amd64_gcc10/external/gcc/10.3.0-84898dea653199466402e67d73657f10/include/c++/10.3.0/bits/unique_ptr.h:173
#14 0x00002b081c78d638 in GsfTrackProducer::produce (this=0x2b086fd42c00, theEvent=..., setup=...) at /data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/4cd3ceaede4e18eb9ab43f14fe009004/opt/cmssw/slc7_amd64_gcc10/cms/cmssw/CMSSW_12_3_DBG_X_2022-01-06-2300/src/FWCore/Framework/interface/ESHandle.h:65
#15 0x00002b07a6b56468 in edm::stream::EDProducerAdaptorBase::doEvent (this=0x2b08733ef2c0, info=..., act=0x2b07acfe5010, mcc=mcc@entry=0x2b086fd55968) at /data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/4cd3ceaede4e18eb9ab43f14fe009004/opt/cmssw/slc7_amd64_gcc10/cms/cmssw/CMSSW_12_3_DBG_X_2022-01-06-2300/src/FWCore/Framework/src/stream/EDProducerAdaptorBase.cc:61
...
Module: GsfTrackProducer:lowPtGsfEleGsfTracks (crashed)
```

As far as I can tell the crash is related to this PR. @swagata87 please check.

**Comment by swagata87** [comment]
> To clarify, the debug build segfaulted in 25202.0. Is this supposed to happen?

Hi Joosep, 

from a quick look, it seems to me that this crash is due to a different problem. Will look into it more..

**Comment by jpata** [comment]
test parameters:
  - release = CMSSW_12_3_DBG_X

**Comment by jpata** [comment]
@cmsbuild please test

**Comment by jpata** [comment]
@cmsbuild please test

**Comment by jpata** [comment]
@cmsbuild please test

**Comment by smuzaffar** [comment]
please test for CMSSW_12_3_DBG_X
run explicitly for DBg IBs, I have updated the jenkins job to increase the timeout for DBG IBs

**Comment by smuzaffar** [comment]
by the way , Step1 for few workflows [a] are taking too long for DBG IBs [a]. Although I have increased the timeout for DBG PR tests to be 9 hours butwith this rate they might fail again. Can someone check what takes stoo long for DBG relvals?

```
> grep 'Run: 1 Event:' 23234.0_*/step1*.log
%MSG-e ExcessiveTime:  OscarMTProducer:g4SimHits 14-Jan-2022 14:20:37 CET  Run: 1 Event: 1
%MSG-e ExcessiveTime:  OscarMTProducer:g4SimHits 14-Jan-2022 15:09:49 CET  Run: 1 Event: 2
%MSG-e ExcessiveTime:  OscarMTProducer:g4SimHits 14-Jan-2022 15:30:29 CET  Run: 1 Event: 3
%MSG-e ExcessiveTime:  OscarMTProducer:g4SimHits 14-Jan-2022 16:14:13 CET  Run: 1 Event: 4
%MSG-e ExcessiveTime:  OscarMTProducer:g4SimHits 14-Jan-2022 17:14:34 CET  Run: 1 Event: 5
> grep 'Run: 1 Event:' 28234.0_*/step1*.log
%MSG-e ExcessiveTime:  OscarMTProducer:g4SimHits 14-Jan-2022 14:33:27 CET  Run: 1 Event: 1
%MSG-e ExcessiveTime:  OscarMTProducer:g4SimHits 14-Jan-2022 15:26:33 CET  Run: 1 Event: 2
%MSG-e ExcessiveTime:  OscarMTProducer:g4SimHits 14-Jan-2022 15:47:18 CET  Run: 1 Event: 3
%MSG-e ExcessiveTime:  OscarMTProducer:g4SimHits 14-Jan-2022 16:36:06 CET  Run: 1 Event: 4
> grep 'Run: 1 Event:' 35034.0_*/step1*.log
%MSG-e ExcessiveTime:  OscarMTProducer:g4SimHits 14-Jan-2022 14:33:46 CET  Run: 1 Event: 1
%MSG-e ExcessiveTime:  OscarMTProducer:g4SimHits 14-Jan-2022 15:24:48 CET  Run: 1 Event: 2
%MSG-e ExcessiveTime:  OscarMTProducer:g4SimHits 14-Jan-2022 15:46:34 CET  Run: 1 Event: 3
%MSG-e ExcessiveTime:  OscarMTProducer:g4SimHits 14-Jan-2022 16:35:06 CET  Run: 1 Event: 4
```

**Comment by clacaputo** [comment]
> by the way , Step1 for few workflows [a] are taking too long for DBG IBs [a]. Although I have increased the timeout for DBG PR tests to be 9 hours butwith this rate they might fail again. Can someone check what takes stoo long for DBG relvals?
> 
> ```
> > grep 'Run: 1 Event:' 23234.0_*/step1*.log
> %MSG-e ExcessiveTime:  OscarMTProducer:g4SimHits 14-Jan-2022 14:20:37 CET  Run: 1 Event: 1
> %MSG-e ExcessiveTime:  OscarMTProducer:g4SimHits 14-Jan-2022 15:09:49 CET  Run: 1 Event: 2
> %MSG-e ExcessiveTime:  OscarMTProducer:g4SimHits 14-Jan-2022 15:30:29 CET  Run: 1 Event: 3
> %MSG-e ExcessiveTime:  OscarMTProducer:g4SimHits 14-Jan-2022 16:14:13 CET  Run: 1 Event: 4
> %MSG-e ExcessiveTime:  OscarMTProducer:g4SimHits 14-Jan-2022 17:14:34 CET  Run: 1 Event: 5
> > grep 'Run: 1 Event:' 28234.0_*/step1*.log
> %MSG-e ExcessiveTime:  OscarMTProducer:g4SimHits 14-Jan-2022 14:33:27 CET  Run: 1 Event: 1
> %MSG-e ExcessiveTime:  OscarMTProducer:g4SimHits 14-Jan-2022 15:26:33 CET  Run: 1 Event: 2
> %MSG-e ExcessiveTime:  OscarMTProducer:g4SimHits 14-Jan-2022 15:47:18 CET  Run: 1 Event: 3
> %MSG-e ExcessiveTime:  OscarMTProducer:g4SimHits 14-Jan-2022 16:36:06 CET  Run: 1 Event: 4
> > grep 'Run: 1 Event:' 35034.0_*/step1*.log
> %MSG-e ExcessiveTime:  OscarMTProducer:g4SimHits 14-Jan-2022 14:33:46 CET  Run: 1 Event: 1
> %MSG-e ExcessiveTime:  OscarMTProducer:g4SimHits 14-Jan-2022 15:24:48 CET  Run: 1 Event: 2
> %MSG-e ExcessiveTime:  OscarMTProducer:g4SimHits 14-Jan-2022 15:46:34 CET  Run: 1 Event: 3
> %MSG-e ExcessiveTime:  OscarMTProducer:g4SimHits 14-Jan-2022 16:35:06 CET  Run: 1 Event: 4
> ```

@smuzaffar I've checked running locally

`runTheMatrix.py -j 16 -s -l 101.0,10224.0,1306.0,250202.181,25202.0,9.0 --command ' --customise Validation/Performance/TimeMemoryJobReport.customiseWithTimeMemoryJobReport' --job-reports`

and inspecting the `step1*.log`. All the `ExcessiveTime` warnings are related to the `OscarMTProducer`

**Comment by smuzaffar** [comment]
@jpata, @clacaputo, @slava77 can you please review and sign it? It should fix DBG relvals

**Comment by clacaputo** [comment]
Due to timeout issue, I've run the test locally in `CMSSW_12_3_DBG_X_2022-01-06-2300` using the command

```
runTheMatrix.py -j 16 -s -l 101.0,10224.0,1306.0,250202.181,25202.0,9.0 --command ' --customise Validation/Performance/TimeMemoryJobReport.customiseWithTimeMemoryJobReport' --job-reports
```

both without and with the PR applied.

With the PR applied, there aren't any more WF failing with the message `Found a PS cluster matched to more than one EE cluster!`. So it seems to me that the PR fixes that issue.

About `virtual const Components& BasicSingleTrajectoryState::components() const: Assertion 'false' failed`[1], I can't reproduce it.

[1]
```
%MSG-e BasicSingleTrajectoryState:  GsfTrackProducer:lowPtGsfEleGsfTracks  09-Jan-2022 17:26:01 UTC Run: 1 Event: 1
asking for componenets to a SingleTrajectoryState
%MSG
cmsRun: /data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/4cd3ceaede4e18eb9ab43f14fe009004/opt/cmssw/slc7_amd64_gcc10/cms/cmssw/CMSSW_12_3_DBG_X_2022-01-06-2300/src/TrackingTools/TrajectoryState/src/BasicTrajectoryState.cc:248: virtual const Components& BasicSingleTrajectoryState::components() const: Assertion `false' failed.
```

**Comment by clacaputo** [comment]
test parameters:

- enable_test = none

**Comment by clacaputo** [comment]
@cmsbuild please test

**Comment by clacaputo** [comment]
Hi @smuzaffar , despite the test successfully passing https://github.com/cms-sw/cmssw/pull/36655#issuecomment-1014879284 I can still see, in the summary of the checks, one that failed. The one that failed it's related to the test performed on `DBG` IB, for some reason, it's still in the summary.

Is there a way to reset it?

**Comment by clacaputo** [comment]
+reconstruction

- the PR fix an issue in the `DBG` IB
- the proposed changes have been tested locally on a `DBG` IB, as stated in https://github.com/cms-sw/cmssw/pull/36655#issuecomment-1014590730

**Comment by perrotta** [comment]
+1

**Pull request merged**
