### PR TITLE
Integration of the first version of muon DPG nanoAOD ntuples

### PR DESCRIPTION
**Pull request by battibass**
#### PR description:

This pull request is a follow-up of the plans about the migration of muon DPG ntuple code to nanoAOD, and its consequent integration in CMSSW.
The project was discussed in [previous cross-POG meetings](https://indico.cern.ch/event/1146609/#7-alcanano-muon).

As there is no existing place in CMSSW where muon DPG offline analysis code is stored, we propose to add a new package. This was briefly discussed with @perrotta.
The package contains only muon DPG-related nanoAOD stuff, hence it was suggested to add @cms-sw/xpog-l2  as reviewers.

#### PR validation:

The PR integrates the code, but it does not include modules in workflows for now.
It was tested that code compiles and passes `code-format` and `code-checks`.

A test recipe  was used to validate the ntuple production:

```bash
cmsenv

cd DPGAnalysis/MuonTools/test

voms-proxy-init -voms cms -valid 192:0

cmsRun muDpgNtuples_cfg.py

$CMSSW_RELEASE_BASE/src/PhysicsTools/NanoAOD/test/inspectNanoFile.py MuDPGNtuple_nanoAOD_ZMMPU.root --docmd=doc.md --sizemd=size.md
```

At the moment of the PR, the recipe runs fine in the latest IB, and produces an [ntuple whose type, number and size of branches](https://gist.github.com/battibass/5181500429538c365973ff34efd09838), match well what shown at cross-POG (total size of event branches, in Run3 ZMM MC including pile-up, is around 3.3 kB / ev)

### CODE REVIEW

**Comment by mariadalfonso** [comment]
assign xpog

**Comment by mariadalfonso** [comment]
@battibass

how we do test this centrally ?

**Comment by battibass** [comment]
As discussed during the cross-POG meeting [on Feb 8th](https://indico.cern.ch/event/1246376/#8-muon-nano), here follow a few updates related to the __muon DPG NANO__.

In a nutshell:

1. a [generic template table producer](https://github.com/battibass/cmssw/blob/nanoAOD_muonDPGNtuples/DPGAnalysis/MuonTools/src/MuDigiBaseProducer.h) was added and used to write all DT/CSC/RPC/GEM digi tables;
1. a [generic template table producer](https://github.com/battibass/cmssw/blob/nanoAOD_muonDPGNtuples/DPGAnalysis/MuonTools/src/MuLocalRecoBaseProducer.h) was added and used to write all DT/RPC/GEM local-reco tables;
1. a `simpleFlatTableProducer` was used to populate the "basic" table for reco muon objects;
1. (when needed) dedicated producers were slimmed to produce only information that can't be generated by the above table producers;
1. configuration in python modules, was also adapted to allow for central testing with `cmsDriver.py`.

Example commands are:

```bash
$ cmsDriver.py nano_mu_zmuskim --conditions auto:run3_data_relval -s RAW2DIGI,NANO:DPGAnalysis/MuonTools/muNtupleProducer_cff.muNtupleProducer --datatier NANOAOD --eventcontent NANOAOD --data --process muNANO --scenario pp --era Run3 -n 100 --filein file:/eos/cms/store/data/Run2022E/Muon/RAW-RECO/ZMu-10Dec2022-v2/330000/159d8e9d-7887-4543-a637-203f4c874c48.root 
```

and:

```bash
$ cmsDriver.py nano_mu_bkg --conditions auto:run3_data_relval -s RAW2DIGI,NANO:DPGAnalysis/MuonTools/muNtupleProducerBkg_cff.muNtupleProducerBkg --datatier NANOAOD --eventcontent NANOAOD --data --process muNANO --scenario pp --era Run3 -n 100 --filein file:/eos/cms/store/data/Run2022E/Muon/RAW-RECO/ZMu-10Dec2022-v2/330000/159d8e9d-7887-4543-a637-203f4c874c48.root
```

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
Ciao @battibass . After a quick glance:
- Please move the headers now in DPGAnalysis/MuonTools/src into the correct `interface` folder of that package. You can avoid doing so only for the headers included only from within `src` itself, if any: including from `src` (as for example in https://github.com/cms-sw/cmssw/pull/38226/files#diff-20610f56b2af291462e16c7a6e8a51abe777e2d0be031fa6a7cd6d341f27cb33R13) must be avoided
- Since you are on it, you could merge .h and .cc files for all plugins

**Comment by perrotta** [comment]
please test

**Comment by vlimant** [comment]
please test

**Comment by simonepigazzini** [comment]
We plan to merge this PR as it is, with xpog getting signatures rights over the new package. A second PR should follow introducing a new RelVal workflow to test the package.

**Comment by simonepigazzini** [comment]
please test

**Comment by battibass** [comment]
please test

**Comment by battibass** [comment]
please test

**Comment by perrotta** [comment]
+1

**Pull request merged**
