### PR TITLE
Run2-hcx137 Fix bug in the AlCaReco sequence for Pedestal

### PR DESCRIPTION
**Pull request by bsunanda**
The name of the input collection was wrong in one of the paths which is now corrected

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by franzoni** [comment]
what are we addressing, trying to do?
We look forward to a description in the PR.
Thanks, AlCa/Db

**Comment by bsunanda** [comment]
@franzoni We would like to correct this bug also for 9_2_X. Can we do that?

**Comment by franzoni** [comment]
+1

**Comment by franzoni** [comment]
> We would like to correct this bug also for 9_2_X. Can we do that?

Hello @bsunanda , sure thing.
Please place this same commit in a PR to the CMSSW_9_2_X branch, as a backport.
It'll be signed / merged after this one enters an IB.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
