### PR TITLE
Disable multi-thread for ALCAHARVEST

### PR DESCRIPTION
**Pull request by dmitrijus**

### CODE REVIEW

**Comment by dmitrijus** [comment]
please test workflow 1001.0,1004.0

**Comment by fabiocos** [comment]
@kpedro88 could you please have a look? This follows the discussion in https://github.com/cms-sw/cmssw/issues/22281

@cerminar this is what you were suggesting

**Comment by dmitrijus** [comment]
Hi, this can be merged, but this does not fix the crash.
There will be another pull request to fix the bug.

**Comment by fabiocos** [comment]
@dmitrijus yes, the real problem is elsewhere, but I understand that in any case this PR restore the intended behaviour of the ALCAHARVEST wf

**Comment by kpedro88** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
