### PR TITLE
Prepare for concurrent IOVs, Fireworks & FastSimulation

### PR DESCRIPTION
**Pull request by wddgit**
Change return type of produce functions from shared_ptr
to unique_ptr. Note that for the TGeo related classes
this moves them in the right direction, but because of
their dependence on TGeo they still will not work
with concurrent IOVs. More work would need to be done.

### CODE REVIEW

**Comment by wddgit** [comment]
please test

**Comment by alja** [comment]
+1

**Comment by ssekmen** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
