### PR TITLE
[12.4.X] `SiPixelLorentzAnglePCLHarvester`: fetch precise B-field value from map via `inverseBzAtOriginInGeV`

### PR DESCRIPTION
**Pull request by mmusich**
backport of https://github.com/cms-sw/cmssw/pull/38700

#### PR description:

The primary goal of this PR is to address the second point of issue https://github.com/cms-sw/cmssw/issues/38669:

> Unrelated to the crash, but pixel people beware: using magField->nominalValue() as a physical value as in https://github.com/cms-sw/cmssw/pull/38653/files#diff-cd4b91b1150cb8ea3ac6cdb24d49a6bd99f77a8320a5d4a60eeab3000ff42eb1R141 is not a good idea. `nominalValue()` is intended to be used as a label, and is truncated to int, with the corresponding loss of accuracy.
The method `inverseBzAtOriginInGeV()` was added to the interface for the benefit of pixel code (https://github.com/cms-sw/cmssw/pull/35081), for example.

This is done by taking the value of the magnetic field from `inverseBzAtOriginInGeV()` (after having converted it from [GeV<sup>-1</sup>]  to [T]) instead of `nominalValue()`.
I profit of this PR to rename all the other member variable to follow the code rule pattern (rule 2.9: https://cms-sw.github.io/cms_coding_rules.html)

#### PR validation:

Tested successfully the multi-run harvesting mode recipe at https://github.com/cms-sw/cmssw/pull/38641#issuecomment-1178053372;

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

verbatim backport of https://github.com/cms-sw/cmssw/pull/38700

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
type trk, bugfix

**Comment by tvami** [comment]
+alca
 * test pass
 * PR is according to the description

**Comment by tvami** [comment]
urgent
 * well, semi-urgent rather, given that it's done it would be nice to have it in 12_4_3

**Pull request merged**
