### PR TITLE
Stage2CaloLayer2 basic monitor module

### PR DESCRIPTION
**Pull request by jingyucms**
Basic module for Stage2 Calo Trigger Layer2

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by deguio** [comment]
@jingyucms 
there is a number of couts to be removed.
thanks,
F.

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1
not included in any central sequence for now

**Comment by jingyucms** [comment]
80X version of this is #11922

**Comment by jingyucms** [comment]
@deguio @davidlange6 new one made in #12743

**Comment by jingyucms** [comment]
Sorry I mean #12734

**Comment by davidlange6** [comment]
I am cleaning up the 76x queue aside from things for analysis workflows. I'm closing this pull request, please make sure the PR is in 80x. Thanks!

**Pull request closed without merging**
