### PR TITLE
Removing Muon POG DQM sequence from Express pipeline

### PR DESCRIPTION
**Pull request by rseidita**
#### PR description:

Removing Muon POG DQM sequence from Express pipeline to reduce memory load at T0.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Will backport to 14_1_X and 14_0_X

### CODE REVIEW

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
@rseidita could you please prepare the backports for 14_1_X and 14_0_X? We would like to go quick with a patch for Tier0, if possible.

**Comment by rseidita** [comment]
@fabiocos backports opened (#46297 #46298)

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
