### PR TITLE
Dqm files code for vbf susy mu hlt path

### PR DESCRIPTION
**Pull request by amkalsi**
Adding DQM codes for a new SUSY trigger path for Run2 in HLTriggerOffline/SUSYBSM package

### CODE REVIEW

**Comment by deguio** [comment]
-1
to be rebased

**Comment by amkalsi** [comment]
Updated the conflicting files
	HLTriggerOffline/SUSYBSM/python/SUSYBSM_postProcessor_cff.py
	HLTriggerOffline/SUSYBSM/python/SusyExoValidation_cff.py

**Comment by deguio** [comment]
ciao @amkalsi 
shouldn't the SUSY_HLT_Mu_VBF_FASTSIM be included as well in
https://github.com/amkalsi/cmssw/blob/DQM-Files-Code-forVBF-SUSY-MuHLTPath/HLTriggerOffline/SUSYBSM/python/SusyExoValidation_cff.py#L112
?

ciao,
F.

**Comment by amkalsi** [comment]
Thanks, updated HLTriggerOffline/SUSYBSM/python/SusyExoValidation_cff.py file

**Comment by deguio** [comment]
+1

**Comment by deguio** [comment]
please test

**Comment by davidlange6** [comment]
+1

**Pull request merged**
