### PR TITLE
92x For Online DQM Use only - new EMTF emulator plus  L1T config from GlobalTag modulo EMTF

### PR DESCRIPTION
**Pull request by rekovic**
92X - This PR is for Online DQM use in the TagCollector

This is 92x 2017 EMTF emulator (PR #20768) plus NoHackConditions (PR #20689)
with a caviat of allowing static config for new EMTF which also uses DB, but via Frontier and not via GT.  This is needed till the EMTF Forests are in the GT, which will happen once the big EMTF PR #20286 is merged into CMSSW.

### CODE REVIEW

**Comment by rekovic** [comment]
please test with cms-sw/cmsdist#3487

**Comment by rekovic** [comment]
please test with cms-sw/cmsdist#3487

**Comment by Martin-Grunewald** [comment]
@rekovic 
There is now a merge conflict in this PR which must be fixed!

**Comment by rekovic** [comment]
please test with cms-sw/cmsdist#3487

**Comment by Martin-Grunewald** [comment]
@rekovic 
What is the status of this PR? There are jenkins code issues now three weeks ago...

**Comment by rekovic** [comment]
@Martin-Grunewald 

This PR was intended for the DQM Use only.
For the time-being the L1T DQM will go with separate 92x PRs
- EMTF #20768 
- NoHackConditions #20689

So, will close this PR now.

**Pull request closed without merging**
