### PR TITLE
Bump TObject versions for ROOT 6.14.

### PR DESCRIPTION
**Pull request by schneiml**
#### PR description:

This is in response to the test failures in https://github.com/cms-sw/cmsdist/pull/4852 . Tests *will fail* with current ROOT; needs to go in in sync with https://github.com/cms-sw/cmsdist/pull/4852 .

I hope I got all the versions correct, there might have been more in other commits, but I don't know how to manually test things with cmsdist changes.

Based on the numbers in commit 94610d9fbca67feb8 in the root repo.

See also https://github.com/cms-sw/cmsdist/pull/4882 for the matching DQMGUI change. Also, now we'll finally need to update `fastHadd`, once we use a > 10_6 release in online/MWGR.

On a side note: commit https://github.com/root-project/root/commit/94610d9fbca67feb898b67d97d8092eaaa960db7 indicates that our patched ROOT (we had the equivalent of https://github.com/root-project/root/commit/8c9c1a3fbe3a1c5704635f8941abeb9596104c77 since beginning of last year) had sort-of incorrect schema evolution on TH1-derived classes for quite a while. Not sure what the implications  on DQMGUI are (@rovere ?).

FYI @mrodozov .

#### PR validation:

None. 

This only affects the schema migration test, which is mostly a reminder for us to update DQMGUI if needed. If the tests pass, it is good and has no impact on other parts of CMSSW.

### CODE REVIEW

**Comment by mrodozov** [comment]
please test with https://github.com/cms-sw/cmsdist/pull/4852

**Comment by mrodozov** [comment]
please test with cms-sw/cmsdist#4852
lets see if this DB auth fail is persistent

**Comment by schneiml** [comment]
hold

Until we know how to get a working version of https://github.com/cms-sw/cmsdist/pull/4882 , it is not safe for us to have releases using this version of ROOT.

**Comment by mrodozov** [comment]
@schneiml please leaborate "working version" of cms-sw/cmsdist#4882

**Comment by schneiml** [comment]
@mrodozov For clarification -- we need a version of ROOT in CMSWEB (for DQMGUI) with the same streamer versions as the one used in CMSSW. While we might be able to survive for a while with a mismatch, this poses some risks for offline and will cause trouble in online eventually.

**Comment by mrodozov** [comment]
I understand now. If we move CMSSW ROOT version to 6.14 CMSWEB should have the same version. That's fine.

**Comment by smuzaffar** [comment]
@fabiocos , as discussed, I have opened CMSSW_10_6_ROOT614_X branch so that we can test this PR along with https://github.com/cms-sw/cmsdist/pull/4852 . I have changed the branch of this PR to CMSSW_10_6_ROOT614_X. Please merge it so that we can test it ROOT614 IBs.

**Comment by fabiocos** [comment]
+1

@schneiml we are running this against the desired ROOT 6.14 update in a dedicated IB to test it in parallel wrt the regular one, where I will merge the ROOPT 6.14 version validated by PPD. If this is ok, we may consider to promote it directly into the main trunk for 10_6_0

**Comment by fabiocos** [comment]
merge

**Comment by schneiml** [comment]
unhold

(for completeness)

Thanks everyone!

**Comment by andrius-k** [comment]
+1
For future reference

**Pull request merged**
