### PR TITLE
Adding new class GEMDigiSimLink in 81X

### PR DESCRIPTION
**Pull request by mileva**
The new class GEMDigiSimLink is added. The class makes a relation between the produced GEM digis (strip and bx) and the properties of the simhits (tof, particle type, process type, ..). 
An example analyzer is added also in the SimMuon/GEMDigitizer/test/ directory.

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
@mileva , please make few updates in this PR, first of all, please, edit the title which is completely misleading. More important: is it really needed to use boost? in many other places it is removed. 

In GEMDigiSimLinkReader.h better to use inheritance from edm::one::EDAnalyzer, because only in that case the test will be thread safe.

In runGEMDigiSimLinkReader_cfg.py you need to change file name - it is not possible to refer to private area.

**Comment by mileva** [comment]
Thank you for the comments!
The PR is updated following the comments of @civanch. I removed boost/cstdint.hpp from SimDataFormats/GEMDigiSimLink and the code is running well, but I see that boost/cstdint.hpp is included in all the DigiSimLinks in the SimDataFormats package.

> first of all, please, edit the title which is completely misleading.

Sorry, but I am not quite sure which title to change. Is this the branch name? If yes, is it possible to change it now after the pull is requested?

**Comment by civanch** [comment]
@mileva , you can edit description of a PR at any moment - click on pencil in upper right corner.

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
@mileva , it may be better in line 39 of GEMDigiSimLinkReader.cc to use:
class GEMDigiSimLinkReader: public edm::one::EDAnalyze

this will mean that the analyzer will work even in MT mode.

Also in  SimMuon/GEMDigitizer/test/runGEMDigiSimLinkReader_cfg.py  in line 34 there is

 '/store/user/mileva/testFiles/out_local_reco.root'

Is there a way to produce this file in any other area at the previous step?

**Comment by mileva** [comment]
Thank @civanch for the comments! I hope now the analyzer inherits the correct EDAnalyzer. The input file in the configuration might be produced following the instructions GEM simulation instructions. Should I include a link to the GEM simulation page?

**Comment by civanch** [comment]
@mileva , yes, please

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by dildick** [comment]
Can we collect the RPCDigiSimLink, GEMDigiSimLink and DTDigiSimLink (which appears to be defined in SimDataFormats/DigiSimLinks) in a subpackage "SimDataFormats/MuonDigiSimLink"?

**Comment by mileva** [comment]
@dildick I don't think so. Even it is possible, such change will give many dependencies in the other packages. Why do you need such change?

**Comment by mdhildreth** [comment]
yes, let's not shuffle around DigiSimLink definitions at this point.  Why would you want/need to do this?

**Comment by dildick** [comment]
It was rather a suggestion; I take it back

**Comment by calabria** [comment]
any news on this PR?

**Comment by calabria** [comment]
@civanch, @mdhildreth, @davidlange6 is the review complete for this PR?

**Comment by mdhildreth** [comment]
+1

**Pull request merged**
