### PR TITLE
[Backport 12_3_X] Update to DNN-based strategy for outside-in seed generation in Muon HLT

### PR DESCRIPTION
**Pull request by kondratyevd**
This is a backport for https://github.com/cms-sw/cmssw/pull/37437. 
The backport is needed to integrate the OI seeding upgrade into the V2 HLT menu.
There are no changes to the code w.r.t. original PR.

@missirol

### CODE REVIEW

**Comment by missirol** [comment]
please test

The PR tests are not sensitive to this PR, see https://github.com/cms-sw/cmssw/pull/37437#issuecomment-1086729972.

**Comment by JanFSchulte** [comment]
Just a reminder that we also need https://github.com/cms-data/RecoMuon-TrackerSeedGenerator/pull/4 for this update. So once it is merged we need a PR to update the version number of the relevant package in this file: https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_12_3_X/master/data/cmsswdata.txt 

For that we first need to know if the memory consumption reported in these profiles is acceptable: https://github.com/cms-sw/cmssw/pull/37437#issuecomment-1088795387

**Comment by missirol** [comment]
I can't really judge this myself right away. This might be worth discussing in a TSG meeting to get better feedback (cc: @silviodonato). Or what is it already discussed in TSG?

If I look at the % values, this looks like a non-negligible increase, although it is a few percent of the total (<5%). At the same time, this looks like a very large increase compared to the previous model (x10 - x20 ?), if I understood correctly:
 - Link for old model: https://github.com/cms-sw/cmssw/pull/35237#issuecomment-925391137
 - Link for new model: https://github.com/cms-sw/cmssw/pull/37437#issuecomment-1089908196

Was this increase expected? By the way, should the model be reviewed by a ML contact, to see if there are ways to improve it?

I don't think this necessarily stops this PR from proceeding, but these questions should be addressed before this is actually integrated in the HLT menu.

**Comment by smuzaffar** [comment]
test parameters:
- pull_requests = cms-sw/cmsdist#7755

**Comment by smuzaffar** [comment]
please test

**Comment by kondratyevd** [comment]
@missirol yes, the size increase is understood, it is simply due to the increased number of weights in the network.
We did not limit the network size during optimization, as we are not aware of what the memory limitation would be.

I suppose, we can re-optimize the network for a given limitation on the size of the model, if needed.

**Comment by perrotta** [comment]
@cms-sw/reconstruction-l2 would you agree signing this PR, verbatim backport of https://github.com/cms-sw/cmssw/pull/37437 ?
By mistake the cmsdist PR which updates the cms-data inputs needed for it was already merged, see https://github.com/cms-sw/cmsdist/pull/7755. Of course, if there are objections to this backport we'll have to revert it before final 12_3_0.

**Comment by jpata** [comment]
+reconstruction

**Pull request merged**
