### PR TITLE
Trivial bug fixes to record  EcalSampleMask

### PR DESCRIPTION
**Pull request by argiro**
Trivial fix of typo-style bugs. Those bugs did not affect the few runs in which this code was actually used. Just nice to have it fixed for the posterity.
While at it, I turned a few couts into LogError

### CODE REVIEW

**Comment by tocheng** [comment]
@cmsbuild please test

**Comment by ggovi** [comment]
+1

**Comment by fabiocos** [comment]
@argiro how frequent is the error condition triggering the LogError? Is this level of verbosity appropriate, as you are doing a cleaning?

**Comment by argiro** [comment]
> On 23 Oct 2018, at 22:32, Fabio Cossutti <notifications@github.com> wrote:
> 
> @argiro how frequent is the error condition triggering the LogError? Is this level of verbosity appropriate, as you are doing a cleaning?

well it will never happen unless the object in the DB has the wrong length. So never in production. And the masking itself is something that we haven't used in ages.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
