### PR TITLE
Run3-sim101B Remove some compilation warnings in SimGeneral/TrackingAnalysis

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Remove some compilation warnings in SimGeneral/TrackingAnalysis using ESGetToken
 
#### PR validation:

Use the runTheMatrix test workflows

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

pure technical

**Comment by perrotta** [comment]
+1

**Pull request merged**
