### PR TITLE
Moving premixing PU relvals to 2017, moving 2016 as UP15 legacy relvals

### PR DESCRIPTION
**Pull request by fabozzi**
- Premixing PU relvals moved to 2017 scenario (2016 premixing PU still available for legacy)
- All 2016 relvals are re-named as "UP15" legacy relvals (in order to distinguish from default 2017 )

### CODE REVIEW

**Comment by fabozzi** [comment]
please test

**Comment by fabozzi** [comment]
+1

**Comment by kpedro88** [comment]
@fabozzi do we need to do anything with the 2017 MC workflows in the upgrade matrix (some of which are forwarded to the regular matrix in `relval_2017.py`)?

**Comment by fabozzi** [comment]
Hi Kevin, I did not make any migration of fullsim (noPU and classical PU) 2017 MC relvals from upgrade to standard part, to avoid breaking the current numbering scheme of upgrade relvals. So I only introduced premixing PU 2017 while the standard 13 TeV MC relvals are still pointing to 2016. We can foresee a migration of standard MC relvals to 2017 but this is something we have to handshake in order to have under control the upgrade part

**Comment by kpedro88** [comment]
@fabozzi okay, I agree with this approach. We should have a longer chat at some point.

**Comment by kpedro88** [comment]
+1

**Comment by fabozzi** [comment]
hold

**Comment by fabozzi** [comment]
superceded by #19197

**Pull request closed without merging**
