### PR TITLE
fix preexisting tracker alignment validation

### PR DESCRIPTION
**Pull request by hroskes**
Fixing a stupid mistake.  The default behavior is setting this parameter to "true" which doesn't work with int.  I missed this one place in 297cb18bf0610f3184fb2ce9b4466b6ebddc6c05.

### CODE REVIEW

**Comment by arunhep** [comment]
please test

**Comment by lpernie** [comment]
+1

**Comment by boudoul** [comment]
hello @hroskes , could you please make the title a bit more explicit , by mentioning that this is for tracker alignment for example ? [hard otherwise from the release notes to get that it's not for the validation of ecal, pflow,  tau or whatever CMS validation components, and the release notes are, among many other purposes,  a key ingredients for the validators ] Thank you.

**Comment by hroskes** [comment]
hi @boudoul, I fixed the title

**Comment by boudoul** [comment]
Thanks @hroskes !

**Comment by fabiocos** [comment]
+1

**Pull request merged**
