### PR TITLE
[DD4hep] Filtered View Performance - Step 2

### PR DESCRIPTION
**Pull request by ianna**
#### PR description:

Allow caching of a `SpecPar` selected by an attribute for the current `Node`. The assumption is that multiple parameters are associated with the same `SpecPar`. The first `get<double>` call would do an expensive search and the subsequent `getNextValue` will piggyback on it, fetching a value selected by another attribute from the same `SpecPar`.

This works as follows (see the unit test):
```c++ 
double radLength = fview.get<double>("TrackerRadLength");
double xi = fview.getNextValue("TrackerXi");
```

The assumption is that both TrackerRadLength and TrackerXi should be part of one SpecPar:
```xml
   <SpecPar eval="true" name="TrackerRecMaterialTOBLayer1_Z0">
      <PartSelector path="//Tracker/TOB/TOBLayer1/TOBRod1/TOBRod1L/TOBRodCentral1L/TOBModule0[6]/TOBWaferRphi0/TOBActiveRphi0" />
      <PartSelector path="//Tracker/TOB/TOBLayer1/TOBRod1/TOBRod1L/TOBRodCentral1L/TOBModule0[6]/TOBWaferSter0/TOBActiveSter0" />
      <PartSelector path="//Tracker/TOB/TOBLayer1/TOBRod1/TOBRod1H/TOBRodCentral1H/TOBModule0[1]/TOBWaferRphi0/TOBActiveRphi0" />
      <PartSelector path="//Tracker/TOB/TOBLayer1/TOBRod1/TOBRod1H/TOBRodCentral1H/TOBModule0[1]/TOBWaferSter0/TOBActiveSter0" />
      <Parameter name="TrackerRadLength" value="0.023298" />
      <Parameter name="TrackerXi" value="4.98908e-05" />
    </SpecPar>
```

The assumption seems to be reasonable, but of cause, there are exceptions:
https://cmssdt.cern.ch/lxr/source/Geometry/TrackerCommonData/data/PhaseI/trackerStructureTopology.xml#0321

```xml
   <SpecPar name="PixelROCRowsPar_D1">
      <PartSelector path="//.*:PixelForwardSensor" />
      <Parameter name="PixelROCRows" value="80"/>
  </SpecPar>
  <SpecPar name="PixelROCRowsPar_D2">
      <PartSelector path="//.*:PixelForwardSensor" />
      <Parameter name="PixelROCRows" value="80"/>
  </SpecPar>
  <SpecPar name="PixelROCRowsPar_D3">
      <PartSelector path="//.*:PixelForwardSensor" />
      <Parameter name="PixelROCRows" value="80"/>
  </SpecPar>
```

@ghugo83 and @vargasa - any idea what should happen here? Is it assumed that  **PixelROCRows** is a vector?

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by ghugo83** [comment]
```
   <SpecPar name="PixelROCRowsPar_D1">
      <PartSelector path="//.*:PixelForwardSensor" />
      <Parameter name="PixelROCRows" value="80"/>
  </SpecPar>
  <SpecPar name="PixelROCRowsPar_D2">
      <PartSelector path="//.*:PixelForwardSensor" />
      <Parameter name="PixelROCRows" value="80"/>
  </SpecPar>
  <SpecPar name="PixelROCRowsPar_D3">
      <PartSelector path="//.*:PixelForwardSensor" />
      <Parameter name="PixelROCRows" value="80"/>
  </SpecPar>
```

I dont think a vector is needed, just an int.
If you go on looping inside the FilteredView, you will just get a vector full of 80.

This represents the number of rows PER ROC, for pixel sensors.
In this file, one group is all sensors belonging to D1, another group is all sensors belonging to D2, etc.

Here in the XML, there is no point having several blocks, because they are the same path.
This is just done forclarity for the reader, I would say.
The SpecPar name does not change anything.

This is exactly equivalent to:
```
   <SpecPar name="PixelROCRowsPar_AllDisks">
      <PartSelector path="//.*:PixelForwardSensor" />
      <Parameter name="PixelROCRows" value="80"/>
  </SpecPar>
```

**So the behavior of the FilteredView should be: if even the node path is matching //.*:PixelForwardSensor, I take 
`<Parameter name="PixelROCRows" value="80"/>`
and I can safely stop.**


When different values are assigned per layer / disk, the paths are different:
```
<SpecPar name="PixelROCRowsPar_L0">
      <PartSelector path="//PixelBarrelActiveFull0" />
      <Parameter name="PixelROCRows" value="80"/>
</SpecPar>
   <SpecPar name="PixelROCRowsPar_L1">
       <PartSelector path="//PixelBarrelActiveFull1" />
       <Parameter name="PixelROCRows" value="80"/>
</SpecPar>
```
And in that case, the FilteredView will not stop until she finds a node matching the path anyway, to get the value specific to that path.

**Comment by ianna** [comment]
@ghugo83 - Thanks! I did not find anywhere a reference to the `SpecPar` name: for example, `PixelROCRowsPar_D1` Is it used somewhere? If not, perhaps the `SpecPars` could be merged eventually? ;-)

**Comment by ianna** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
