### PR TITLE
Run3-trk08X Provides namespace to all created solids/volumes (backport #35065)

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Provides namespace to all created solids/volumes (backport #35065)

#### PR validation:

Tested using to the runTheMatrix test workflows in #35065

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Backporting #35065

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
Note that this PR affects only DD4hep, not DDD.

**Comment by cvuosalo** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
