### PR TITLE
Fix logical error in HGCal module rotation class

### PR DESCRIPTION
**Pull request by snwebb**
#### PR description:

Logical error found in `if` clause (see #33190 from @perrotta for report) in the module rotation class`HGCalGeomRotation`. This is fixed and additionally a logging message has been made clearer.

#### PR validation:

Code-checks and format applied successfully (this is a very small change).

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by cvuosalo** [comment]
+1

**Comment by perrotta** [comment]
type bug-fix

**Comment by perrotta** [comment]
@cms-sw/upgrade-l2 this is a simple bug fix: could you please check, and either sign or comment?

**Comment by srimanob** [comment]
+Upgrade

**Comment by qliphy** [comment]
+1

**Pull request merged**
