### PR TITLE
Adapt DQMGenericClient to be able to run every LS

### PR DESCRIPTION
**Pull request by thomreis**
In order to use the DQMGenericClient in the online DQM the ratios must be calculated in the dqmEndLuminositySection function as well to have updates in the live DQM GUI.
To rebook existing histograms for every LS the booking is done after eventually existing histograms with the same name have been removed from the DQMStore.

In addition, an opt-out parameter was introduced for the generation of the global efficiency plot.

### CODE REVIEW

**Comment by thomreis** [comment]
please test

**Comment by thomreis** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
