### PR TITLE
Run3-gex83D Update SD classes in SimG4CMS/HcalTestBeam to conform with the new standard

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Update SD classes in SimG4CMS/HcalTestBeam to conform with the new standard

#### PR validation:

Use the scripts in SimG4CMS/HcalTestBeam/test/python

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
