### PR TITLE
Update track analysers used for Alignment input data inspection 

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

Title says it all, update a couple of analyzers that are used to check the input data for the global tracker alignment procedure.
I profit of this to make an addition to the unit tests of this package to have them tested, together with a stub of catch2 tests.
I also employ the filter that was introduced in https://github.com/cms-sw/cmssw/pull/37500 to isolate low pT tracks. 
This is exercised in the unit tests.

#### PR validation:

Private, relies also on the augmented unit tests.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by tvami** [comment]
+alca
 * newly introduced unit test ran fine: https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-5b9188/24012/unitTests/src/Alignment/OfflineValidation/test/testAlignmentOfflineValidation/testing.log

**Comment by mmusich** [comment]
type trk

**Comment by perrotta** [comment]
+1

**Pull request merged**
