### PR TITLE
Herwig7 workflow 535

### PR DESCRIPTION
**Pull request by Andrej-CMS**
Dear all,
I changed the Herwig7 validation workflow to gen-sim and changed the gridpack for ttbar production in this workflow.
please see the discussion in https://github.com/cms-sw/cmssw/pull/23732

Kind regards,
Andrej

### CODE REVIEW

**Comment by kpedro88** [comment]
please test

**Comment by kpedro88** [comment]
please test 535

**Comment by alberto-sanchez** [comment]
+1

**Comment by kpedro88** [comment]
please test workflow 535
(comparison never appeared...)

**Comment by fabozzi** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade

**Comment by fabiocos** [comment]
@Andrej-CMS thank you, can we have a backport to 10_2_X?

**Comment by fabiocos** [comment]
+1

**Pull request merged**
