### PR TITLE
Nano: fix array size branch type, support 16 bit ints, use more 8 or 16 bit integers

### PR DESCRIPTION
**Pull request by swertz**
#### PR description:

- It was brought to our attention by the ROOT team that the branch type used for the size (counter) of native arrays should always be a signed integer (see [here](https://root.cern.ch/doc/master/classTBranch.html#ac0412c423e6c8388b42247e0410cf822)), while it was stored as an unsigned int in NanoAOD. In practice there may be few consequences, but this implements the fix to avoid any potential unwanted effects down the line.
- Add support for 16-bit integers in NanoAOD and fix some inconsistencies for other types (uint, double) in the flat table producer
- Use 8 and 16 bit integers instead of full-size ints where relevant (charges, indices, IDs, counters...). While compression did help in hiding the zeroed unused bits, I still noticed a few percent-level reduction in the size then using native types instead.
    - Note that I avoided using `int8` for signed integers and always relied on `int16` instead. This is because ROOT interprets `int8` as a `char`, which messes up things like `TTree::Draw` and `TTree:Scan` (filling the histogram with characters instead of numbers). 

#### PR validation:

Ran a nano matrix workflow.

### CODE REVIEW

**Comment by swertz** [comment]
enable nano

**Comment by swertz** [comment]
please test

**Comment by swertz** [comment]
please test

**Comment by swertz** [comment]
please test

**Comment by swertz** [comment]
please test

**Comment by swertz** [comment]
+1

(Finally) no changes in the NanoAOD content, as should be. The size gain is smaller than I expected though.

**Comment by perrotta** [comment]
> (Finally) no changes in the NanoAOD content, as should be. The size gain is smaller than I expected though.

Just to understand, what are the changes to nanoAOD reported in the "standard comparisons" for wf 1330 and 25202 , see https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_13_0_X_2023-01-12-1100+64cd62/54976/validateJR.html ?

**Comment by perrotta** [comment]
Not really related to this PR, but triggered by the Static Analizer report of these tests: what is the purpose of [this line](https://github.com/cms-sw/cmssw/blob/cc491f1a5d986cfe6f18bf6a20cdc36a6ab5ef50/DataFormats/NanoAOD/src/classes.h#L8)  in DataFormats/NanoAOD/src/classes.h?

Maybe @lgray knows, since he coded it in https://github.com/cms-sw/cmssw/pull/36037

**Comment by swertz** [comment]
> Just to understand, what are the changes to nanoAOD reported in the "standard comparisons" for wf 1330 and 25202 , see https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_13_0_X_2023-01-12-1100+64cd62/54976/validateJR.html ?

I think it's just because I changed the type of the columns, while the content doesn't change. Perhaps @vlimant can help interpret the output of the comparison script?

> Not really related to this PR, but triggered by the Static Analizer report of these tests: what is the purpose of [this line](https://github.com/cms-sw/cmssw/blob/cc491f1a5d986cfe6f18bf6a20cdc36a6ab5ef50/DataFormats/NanoAOD/src/classes.h#L8) in DataFormats/NanoAOD/src/classes.h?

I was actually wondering the same thing, curious to hear from @lgray .

**Comment by perrotta** [comment]
+1

**Comment by aandvalenzuela** [comment]
Hello @swertz, @vlimant 
This PR caused some compiler errors in the latest ROOT6 IB. Find a proposed solution in https://github.com/cms-sw/cmssw/pull/40545. Could you please have a look?
Thanks!

**Pull request merged**
