### PR TITLE
Phase2-hgx360E Use the new way of defining passive materials for the HGCal v19 geometry

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Use the new way of defining passive materials for the HGCal v19 geometry

#### PR validation:

Use scripts in Geometry/HGCalCommonData to test the new algorithm

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
+geometry

**Comment by bsunanda** [comment]
@Moanwar, @srimanob, @subirsarkar Please approve this PR

**Comment by Moanwar** [comment]
+Upgrade

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
