### PR TITLE
Run3-gex21 Correct ECAL numbering schemes to work for dd4hep

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Correct ECAL numbering schemes to work for dd4hep

#### PR validation:

Tested using the runTheMatrix workflows 11634.0

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
@bsunanda Please change the PR title and description to specify ECAL numbering. I read this PR hoping it would fix the muon numbering problems, but I see it is only for ECAL.
Thanks.

**Comment by ianna** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Comment by cvuosalo** [comment]
@bsunanda Does this PR partially address issues #31466 and #31798?

**Comment by bsunanda** [comment]
@cvuosalo This together with #31810 tries to address the missing hits issue in EB

**Pull request merged**
