### PR TITLE
xrange migration for python3

### PR DESCRIPTION
**Pull request by davidlange6**
at least one unit test in my python3 fwk test fails due to the use of xrange (now range in python3). Migrate using

futurize -f libfuturize.fixes.fix_xrange_with_import -w --no-diffs -n .

(the physics/reco packages )

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/26411	af7a3a7
- technical
- jenkins tests pass

**Comment by pohsun** [comment]
+1

**Comment by fabiocos** [comment]
@santocch @ggovi @fgolf @peruzzim could you please check?

**Comment by peruzzim** [comment]
+xpog

for the changes in PhysicsTools/NanoAOD

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

@santocch @ggovi please have a look anyway and sign it in case for future reference or comment

**Comment by santocch** [comment]
+1

**Pull request merged**
