### PR TITLE
[13_0_X] Fix typos in jetsAK4 CHS and Puppi tables

### PR DESCRIPTION
**Pull request by hqucms**
#### PR description:

Backport of https://github.com/cms-sw/cmssw/pull/42670

> This pull request fixes a few typos in the jetsAK4 CHS and Puppi tables:
> 
> (1) Fix to the `btagRobustParTAK4CvB` definition: the previous definition was using the `pfDeepFlavourJetTags` instead of pfParticleTransformerAK4JetTags` for the `probbb` and `problepb` scores in the denominator. This affects both the CHS and Puppi AK4 jet tables, and **probably(?) affects the official production.**
> 
> (2) Fix to the `nanoAOD_addDeepInfoAK4()` fucntion in the `jetsAK4_Puppi_cff.py`: *this should only affects private/custom productions.*
> 

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by simonepigazzini** [comment]
enable nano

**Comment by simonepigazzini** [comment]
please test

**Comment by simonepigazzini** [comment]
+1

same changes observed in DQM to the c vs b node. This is good to go for the NANO (re)production of prompt 2023

**Comment by simonepigazzini** [comment]
Thanks again @hqucms

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
