### PR TITLE
Backport bug fix for dumpPython function with empty sequences

### PR DESCRIPTION
**Pull request by wddgit**

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

@wddgit how many packages did the checkdeps pull in?

**Comment by slava77** [comment]
ok, I see in jenkins console already that there are many packages on the dep list (most of what we have, apparently)

**Comment by wddgit** [comment]
I only tested with Core packages. I did not try checkups. All the changes are in python and none in the interface and it only effects dumpPython. Will running the RelVals even exercise this? It cannot cause build problems.

**Comment by wddgit** [comment]
OK I meant "I did not try checkdeps". GitHub thought it was a spelling error and changed it to checkups ...

**Comment by slava77** [comment]
On 9/8/16 4:03 PM, W. David Dagenhart wrote:
> I only tested with Core packages. I did not try checkups. All the
> changes are in python and none in the interface and it only effects
> dumpPython. Will running the RelVals even exercise this? It cannot cause
> build problems.

I wanted to test this on the data processing config.
I prefer consistent builds, which means checkdeps (it will take too long)
or an alternative to wait for an IB (it will take too long)
or an alternative to not do checkdeps (it's uncomfortable).
I guess I'll try with the latter.

**Comment by slava77** [comment]
interesting
we didn't have a full build since CMSSW_8_0_19_patch1. I wonder if a failure here actually means a broken full build IB

**Comment by slava77** [comment]
@cmsbuild please test
.. maybe it works with another attempt

**Comment by slava77** [comment]
bakcport of  #15790

**Comment by davidlange6** [comment]
this PR checks out on 650 packages...

**Comment by Dr15Jones** [comment]
The test failures are unrelated to this pull request. They are both complaining about bad indices used in the mixing module
```
%MSG-e SiStripLorentzAngle:  MixingModule:mix 09-Sep-2016 15:17:39 CEST  Run: 1 Event: 1
SiStripLorentzAngle for DetID 442032132 is not stored
%MSG
----- Begin Fatal Exception 09-Sep-2016 15:17:53 CEST-----------------------
An exception of category 'CorruptedData' occurred while
   [0] Processing run: 1 lumi: 1 event: 1
   [1] Running path 'digitisation_step'
   [2] Calling event method for module MixingModule/'mix'
Exception Message:
[SiStripThreshold::getData] asking for data for a strip 128 lower then the first stored strip 112
----- End Fatal Exception -------------------------------------------------
```

**Pull request merged**
