### PR TITLE
adding special hgcal relval workflows in upgradeWorkflowComponents

### PR DESCRIPTION
**Pull request by jnsandhya**
Special relval workflows have been added as part of upgradeWorkflowComponents.py needed for hgcal.

### CODE REVIEW

**Comment by fabozzi** [comment]
@prebello : FYI

**Comment by fabozzi** [comment]
please test

**Comment by fabozzi** [comment]
+1

**Comment by kpedro88** [comment]
+1
@jnsandhya you may want to make a backport PR for 93X

**Comment by davidlange6** [comment]
+1

**Comment by kpedro88** [comment]
@jnsandhya reminder about making a 93X backport if you want to use these workflows in the next set of relvals

**Pull request merged**
