### PR TITLE
improve errors when pileup scenario requires inputs that are not specified

### PR DESCRIPTION
**Pull request by davidlange6**
two changes
 - remove long since deleted default pileup inputs 
 - add exception to cmsDriver if pileup scenario is specified without a pileup_input.

(motivated by recent Mattermost discussion with production errors due to missing --pileup_input causing all jobs to fail)

### CODE REVIEW

**Comment by civanch** [comment]
Likely removed links to files for Run1 are needed.

**Comment by davidlange6** [comment]
those files don't exist, so hard to imagine they are needed. Seems something is wrong with the check I added in the case that there is no pileup scenario specified..

**Comment by davidlange6** [comment]
please test

**Comment by civanch** [comment]
+1

**Pull request merged**
