### PR TITLE
[12_6_X] RPCDqmClient crash fix for 0 LS runs

### PR DESCRIPTION
**Pull request by pmandrik**
#### PR description:

see https://github.com/cms-sw/cmssw/pull/39630

### CODE REVIEW

**Comment by rappoccio** [comment]
please test

**Comment by rappoccio** [comment]
please abort

**Comment by rappoccio** [comment]
Need resources for higher priority PRs

**Comment by emanueleusai** [comment]
@pmandrik can you please remove "[12_6_X]" from the PR title

**Comment by emanueleusai** [comment]
@rappoccio can you please let us know when it is appropriate to restart the tests for this and the other DQM PRs?

**Comment by perrotta** [comment]
please test
(@emanueleusai thank you for asking: we can do it even now: the outage was yesterday)

**Comment by emanueleusai** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
