### PR TITLE
HLT menu development for `14_0_X` (7/N)

### PR DESCRIPTION
**Pull request by mmusich**
backport of https://github.com/cms-sw/cmssw/pull/44948

#### PR description:

Development of HLT menus for CMSSW_14_0_X.
   * This is the PR for the 14.0.X branch (thi is the release cycle currently used for Run-3 HLT-menu development).
   * This version of the GRun HLT menu corresponds to the list of updates to the **"V1.2"** menu for the 2024 pp data-taking period.

This update includes the integration of the following JIRA tickets:
- [CMSHLT-3079](https://its.cern.ch/jira/browse/CMSHLT-3079) : [MUO] Removal pixel hits requirement in Outside-In
- [CMSHLT-3162](https://its.cern.ch/jira/browse/CMSHLT-3162) : [L1T] uGT Test crate data in the NanoDST stream
- [CMSHLT-3169](https://its.cern.ch/jira/browse/CMSHLT-3169) : [HIG] MVA-Based Diphoton HLT Path
- [CMSHLT-3171](https://its.cern.ch/jira/browse/CMSHLT-3171) : [BTV] Migration of emu+1btag to ParticleNet
- [CMSHLT-3172](https://its.cern.ch/jira/browse/CMSHLT-3172) : [L1T] NanoDST stream: store RAW data (`hltFEDSelectorL1`) instead of digis (`hltGtStage2Digis`)
- [CMSHLT-3173](https://its.cern.ch/jira/browse/CMSHLT-3173) : [EXO,Scouting] `AXOL1TL` Paths with `VTight`, `Loose` and `VLoose` Thresholds
- [CMSHLT-3175](https://its.cern.ch/jira/browse/CMSHLT-3175) : [BPH,Scouting,EXO] Scouting ZeroBias (`DST_PFScouting_ZeroBias`)
- [CMSHLT-3176](https://its.cern.ch/jira/browse/CMSHLT-3176) : [BPH,Scouting] update list of L1 bits for scouting muon path
- [CMSHLT-3178](https://its.cern.ch/jira/browse/CMSHLT-3178) : [EXO] Set PS=0 for `HLT_HT360_DisplacedDijet40_Inclusive1PtrkShortSig5_v`
- [CMSHLT-3179](https://its.cern.ch/jira/browse/CMSHLT-3179) : [MUO,Scouting] Update of the NoVtx reconstruction to include extended ROIs (but no pixel doublet recovery)
- [CMSHLT-3180](https://its.cern.ch/jira/browse/CMSHLT-3180) : [BPH] Paths for new low pT BMTF bits
- [CMSHLT-3182](https://its.cern.ch/jira/browse/CMSHLT-3182) : [EGM,EXO,HIG] Reducing the threshold of the high rate single photon path
- [CMSHLT-3183](https://its.cern.ch/jira/browse/CMSHLT-3183) : [EXO] Enabling of AXOL1TL L1 Seeds
- [CMSHLT-3184](https://its.cern.ch/jira/browse/CMSHLT-3184) : [TSG] Backport of online updates in EventDisplay dataset for Cosmics and Circulating menus
- [CMSHLT-3185](https://its.cern.ch/jira/browse/CMSHLT-3185) : [TSG] Prescales of random-based HLTs of GRun in Emergency column (2024 rampup)
- [CMSHLT-3186](https://its.cern.ch/jira/browse/CMSHLT-3186) : [TSG] Add Status_On{CPU,GPU} Paths to all online special menus
- [CMSHLT-3191](https://its.cern.ch/jira/browse/CMSHLT-3191) : [BTV] Adding PNet Info to HLTMonitor
- [CMSHLT-3193](https://its.cern.ch/jira/browse/CMSHLT-3193) : [TSG] Add ZeroBias/HLTPhysics PS columns (Run2024D)
- [CMSHLT-3194](https://its.cern.ch/jira/browse/CMSHLT-3194) : [BTV] Set PS=0 for `HLT_Mu8_*_Ele23_*_CaloDiJet30`

In addition, the following changes are included:
   * 90d704b08288bd0ba975c20a5f6d9facd55ad84e : update of L1T FULL,GRun,2024v11,Special menus in TSG GTs to `L1Menu_Collisions2024_v1_2_0_xml`
   * 09b47ae344b043bc4236c9744dc4ff90580ee902 : update the list of HLT path owners: menu 2024 V1.2
   * bbe2e433e202b86fa348a25f1b4c0110e61f878b : Introduce 2024v1.2 frozen menu and remove 2024v1.1

#### PR validation:

TSG Integration tests

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

backport of https://github.com/cms-sw/cmssw/pull/44948 to the 2024 production cycle (`CMSSW_14_0_X`)

### CODE REVIEW

**Comment by mmusich** [comment]
type hlt-integration

**Comment by mmusich** [comment]
enable gpu

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
+hlt
   * changes in the outputs of PR tests are in line with updates to the HLT GRun menu, and the change in name of the frozen HLT menus

**Comment by antoniovilela** [comment]
+1
   - HLT V1.2 menu dump.

**Pull request merged**
