### PR TITLE
Replace LinkDef file witl XML selection file in Calibration/HcalCalibAlgos

### PR DESCRIPTION
**Pull request by wmtan**
It has been decided to replace LinkDef files with XML selection files.
This PR does this for the LinkDef file that was in Calibration/HcalCalibAlgos.
A reorganization of existing files was needed because XML selection files are not allowed in plugins.
LinkDef files should not be in plugins, either, but that was never enforced.

### CODE REVIEW

**Comment by wmtan** [comment]
@cmsbuild please test

**Comment by wmtan** [comment]
@cmsbuild please test
 updated this PR to fix build issues.

**Comment by wmtan** [comment]
@cmsbuild 
please test

**Comment by smuzaffar** [comment]
@wmtan, it should be in one line (first line) :-)

**Comment by smuzaffar** [comment]
@cmsbuild, please test

**Comment by wmtan** [comment]
@diguida, @franzoni, @cerminar
Please sign or provide a reason for not signing

**Comment by wmtan** [comment]
This PR has been rebased to fix a merge conflict.

**Comment by wmtan** [comment]
@cmsbuid please test

**Comment by diguida** [comment]
please test

**Comment by wmtan** [comment]
This change has been merged in 8_0_X. Not needed here.

**Pull request closed without merging**
