### PR TITLE
Remove stage2 modules from Legacy L1Trigger DQMOffline Sequence

### PR DESCRIPTION
**Pull request by z4027163**

### CODE REVIEW

**Comment by rekovic** [comment]
please test

**Comment by z4027163** [comment]
@rekovic It looks like the integration build is failing. Those fails are not caused by this PR. Those tests passed on the previous CMSSW integration.

**Comment by smuzaffar** [comment]
please test

**Comment by rekovic** [comment]
+1

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
