### PR TITLE
Run3-hcx273 Utilize ESGetToken in HCAL RecHit validation code

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Utilize ESGetToken in HCAL RecHit validation code

#### PR validation:

Tested using runTheMatrix test workflows

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by jfernan2** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
