### PR TITLE
Run3-sim59 Define the reconstruction geometry of ECAL

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Defines EcalXXXGeometryEP for dd4hep application

#### PR validation:

Tested with runTheMatrix.py

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
+1

**Comment by cvuosalo** [comment]
@bsunanda What part of the ECAL Reco geometry migration does this PR cover? How much more work is needed to complete he ECAL Reco geometry migration?

**Comment by bsunanda** [comment]
@cvuosalo Here it defines the connection between EventSetup and producers for ECAL geometry. Earlier we completed the producer for Ecal barrel and for Endcap and Preshower, one need to see if the producer is completed. Rajdeep is looking into this.

**Comment by silviodonato** [comment]
please test workflow 23234.1001, 23434.1001

**Comment by bsunanda** [comment]
Hi,

All the changes refer to dd4hep application. I wonder why the additional tests are required. Nothing is changed for DDD applications. Anyway extra tests are always good. Regards

Sunanda
________________________________

**Comment by silviodonato** [comment]
+1

**Pull request merged**
