### PR TITLE
Manage PluginFactory plugins with unique_ptr in RecoEgamma

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

In addition use `unique_ptr` constructor where needed to prepare for PluginFactory returning `std::unique_ptr`.

#### PR validation:

Code compiles.

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/26858	d0db662
- code changes are in line with the PR description; the changes are technical.
- jenkins tests pass and comparisons with the baseline show  no differences

**Comment by makortel** [comment]
I found an additional case to be generalized (since my initial "search" round in January) within `RecoEgamma`, so I decided to just add it in this PR.

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/26858	ba8515a
- changes since the last reco signoff are somewhat trivial

**Comment by fabiocos** [comment]
+1

**Pull request merged**
