### PR TITLE
Loading the Magnetic Field by default from DB

### PR DESCRIPTION
**Pull request by boudoul**
Access by defaults the Magnetic Field model and parameters through the Global Tag in ConfigBuilder and Relval Tools (as a consequence of  #8814 )

### CODE REVIEW

**Comment by boudoul** [comment]
@cmsbuild please test

**Comment by VinInn** [comment]
not the same...

**Comment by davidlange6** [comment]
indeed.. I asked experts to investigate why (as Slava had done such a check already that was ok)

**Comment by slava77** [comment]
The last time, to sign off on a similar change I reran locally with recycled gen-sim.

**Comment by slava77** [comment]
I think this PR is fine and behavior is as expected.

I used CMSSW_7_5_0_pre5 /my test area test9377/ to run the short matrix with a few extras from reco (full list is: 4.17,4.22,4.29,4.37,4.38,4.39,4.53,5.1,8.0,25.0,101.0,135.4,140.51,140.53,200.0,1000.0,1001.0,1102.0,1330.0,11325.0,50202.0 ).
The tests were run with the gen-sim recycled (jenkins tests do resim).

- I find no significant differences in comparisons with the baseline.
    - There are very small differences in standAloneSETMuons (reco method relying on multiple propagations)

As in the previous case with xml->DB change in the magnetic field, the changes (more specifically the ones with re-SIM) are interpreted as a coming from numerical differences in the field volume boundaries (outside the tracker).
- SIM is strongly affected due to the heavy use of random numbers: a tiny change in one step would trigger different paths and simhits generated for all subsequent events
- reuse of the same sim inputs localizes the discrepancies to be just in one event and only in execution paths dependent on that area with discrepancies.

**Comment by davidlange6** [comment]
@slava77 - thanks for the checks. I didn't realize that the GEN-SIM was being rerun in this test. That amplifies small differences between the file-based and db fields.

**Comment by boudoul** [comment]
Thank you very much for the deep checks
+1

**Pull request merged**
