### PR TITLE
[DO NOT MERGE] Add duplicate pixels

### PR DESCRIPTION
**Pull request by ferencek**
#### PR description:

In this PR duplicate pixels in the clusterizer code are added together instead of taking the last occurence. The goal of the PR is to bring the CPU legacy code in sync with the GPU code as a follow up to the discussions in https://github.com/cms-sw/cmssw/issues/35376 and https://github.com/cms-sw/cmssw/pull/37359

No changes are expected in MC samples. In the data there could be some tiny differences in case some duplicate pixels appear.

#### PR validation:

Code compiles :)

### CODE REVIEW

**Comment by silviodonato** [comment]
PS. This should reduce the differences of ~90% so I'm in favor of this PR, just wanted to say that it should not be the last one...

**Comment by ferencek** [comment]
There are pixel-level and cluster-level thresholds so it is possible that individual pixels would not pass the cluster-level threshold but their sum would. However, I am actually not sure what the final goal here is? To ensure that the legacy CPU and new GPU code give identical results? Does it really make sense to modify the legacy CPU code until it reproduces the GPU code (assuming this is even possible without significant re-engineering)? Note that already this addition of duplicate pixels does not make much sense from the detector point of view. Not that what was done so far in the legacy code was a much better solution. So if we really wanted to touch the legacy code, it would make sense to do something that makes sense from the detector point of view and that would be to completely kill duplicate pixels. I'm not familiar enough with the GPU code but I am a priori against re-engineering the legacy code just so it could reproduce what is done in the GPU code.

In the legacy code the `SiPixelArrayBuffer` class is used to store pixel charges. Internally it allocates a vector of pixel charges for all pixels in a pixel module where the linearized index for a pixel with `row` and `col` coordinates is defined as `col * nrows + row`. It can therefore be quickly checked without expensive lookups if pixel `(row, col)` already has some charge set. Since duplicate pixels can appear more than twice, it would be best to introduce a linearized occupany map from which it would be easy to check how many times a given pixel appeared and any pixels appearing more than once would have their charge set to 0. So killing duplicates in the legacy CPU code is possible without much change in the code.

**Comment by ferencek** [comment]
And based on what I wrote above about the `SiPixelArrayBuffer`, there is currently no place to hold multiple instances of the same pixel (and I am pretty sure sure that the clustering algorithm that comes downstream and takes the `SiPixelArrayBuffer` as input was not designed to handle multiple instances of the same pixel). The only three options are the following ones: to sum them all up, ignore them all or keep only one of them (currently the last one that appears is kept). So I am afraid that reproducing what the GPU code does would require re-engineering the legacy code (making it not so legacy anymore). And all this to do something which is not well motivated from the detector point of view.

**Comment by VinInn** [comment]
I can only second @ferencek words.  The code shall perform what best from a detector & physics point of view.
The GPU code was written to reproduce Legacy clusters and was successfully tested on MC. Then duplicate pixels were observed in data and the advice was to ignore them.

If this is not the case anymore somebody shall decide what action shall be taken to produce correct results compatible to computational costs.
(btw duplicate pixels in Run2 data for BPIX1 seem correlated to large noise where a large part of a DCOL lights up: the affected clusters do not seem to come from tracks, it would even make sense to mark those clusters as noise...)

**Comment by jpata** [comment]
@cmsbuild please test

**Comment by ferencek** [comment]
Hi @silviodonato, yes, I think it is possible to have the CPU code ready before the start of data taking. I assume we are talking about CMSSW_12_4_0 as the target release.

**Comment by silviodonato** [comment]
@ferencek please have a look at the solution proposed in https://github.com/cms-sw/cmssw/pull/37359#issuecomment-1095031647, that would be ideal for the TSG as the plan is to move to Alpaka at some point.

**Comment by silviodonato** [comment]
Once we migrate the GPU code to Alpaka, we will be able to run the same code on both CPU and GPU.
Clearly, if you have in mind a minimal change that can solve the problem, it is welcome as well.

**Comment by jpata** [comment]
@ferencek @OzAmram can you clarify (from the pixel DPG point of view) if this PR is intended as something we should consider ready for merging, or if it's a RFC/discussion topic in the pixel DPG (akin to #37359)?

**Comment by ferencek** [comment]
@jpata, given the discussion above, it turned into more of a discussion topic than something that should be considered for merging. Should I add [DO NOT MERGE] or something else to that effect in the title of the PR to avoid confusion?

**Comment by ferencek** [comment]
@silviodonato, here is a PR that removes duplicate pixels in the legacy CPU code https://github.com/cms-sw/cmssw/pull/37559

**Comment by jpata** [comment]
-reconstruction
- removing from the reco queues until the discussion in the DPG is concluded

**Comment by qliphy** [comment]
@ferencek @fwyzard  This can be closed now by #37559, right?

**Comment by fwyzard** [comment]
Yes, this PR should be closed.

**Pull request closed without merging**
