### PR TITLE
Simhits Validation update

### PR DESCRIPTION
**Pull request by kencall**
Updates are made to HcalSimHitStudy, HcalSimHitsValidation, and SimHitsValidation. These changes extend the updates made in PR #15714. 

Histogram ranges are given in terms of defined constants. 

Additional changes include extending dynamic depths to all 3 modules, adding the testNumber parameter, and adding histograms to sum simhit energy over all depths in a ieta-iphi tower.

attn: @hatakeyamak, @lihux25, @kpedro88, @bsunanda

### CODE REVIEW

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by kencall** [comment]
I see that runTheMatrix failed. I'm working on it now.

**Comment by kpedro88** [comment]
@kencall:
```
----- Begin Fatal Exception 27-Sep-2016 17:09:38 CEST-----------------------
An exception of category 'Configuration' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing module: class=HcalSimHitStudy label='hcalSimHitStudy'
Exception Message:
StatusMismatch: Parameter 'TestNumber' is designated as untracked in the code,
but is not designated as untracked in the configuration file.
Please change the configuration file to 'untracked <type> TestNumber'.
----- End Fatal Exception -------------------------------------------------
```

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by abdoulline** [comment]
Just a small comment: I think the PR title is a bit misleading, as it's not about SImHits per se, but their validation. And usual suggestion:  
runTheMatrix -s --useInput all 
before PR submission.

**Comment by kpedro88** [comment]
@dmitrijus please review/sign

**Comment by dmitrijus** [comment]
+1

**Comment by kpedro88** [comment]
@davidlange6 I think it would be even better if both validation and DQM got those values from the topology. It would improve the flexibility for Phase1 and Phase2. @bsunanda, everything in the "detector constants" section there should be retrievable from the topology, right? @vkhristenko @deguio

**Comment by davidlange6** [comment]
Yes I agree, I have previously complained about the DQM constants but was told there was no way to get them in CMSSW. Would be great if there is a more central way

**Comment by deguio** [comment]
Hi,
this is something we could plan in the future, but it would be helpful to have an example if possible..
In any case those constants are used only for the histogram axis and not for the booking.

**Comment by kpedro88** [comment]
@davidlange6 ping for pre13

**Comment by hatakeyamak** [comment]
KenC is traveling until this afternoon with his kids (including a very recent newborn), so I think that's why he hasn't responded yet. Can we try to merge this branch in for now, and try to do better in the next round. We certainly plan a follow-up PR.

**Comment by davidlange6** [comment]
can we agree on a time scale (as I identified this issue for hcal months ago already…)

**Comment by hatakeyamak** [comment]
The ones that came up during the previous PR (#15714): I am sure they will be done this week (being developed under https://github.com/kencall/cmssw/tree/UpdatedRelVal5). I think it was mostly ready before KenC took off last week. The one that came up here, I feel that we still need to investigate exactly what we need to do (particularly if we want to use topology), so I am a little hesitant to give a clear time scale, but we will start working on it either today or tomorrow.

**Comment by davidlange6** [comment]
Hi @hatakeyamak - let us know what the timescale is as a result of our initial investigation. It would not be nice to have this duplication around for very long.

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by hatakeyamak** [comment]
This last commit/update by KenC is to address the review comments here and he got rid of HcalSimHitsConstants.h.

**Comment by dmitrijus** [comment]
+1

**Comment by kpedro88** [comment]
@davidlange6 can this be merged now?

**Comment by lihux25** [comment]
@davidlang6 I'm pinging you to ask if this PR can be merged now? Thanks you very much!

**Comment by davidlange6** [comment]
+1

**Pull request merged**
