### PR TITLE
Update displaced track jet cuts in GTT

### PR DESCRIPTION
**Pull request by cgsavard**
This is a copy of a PR approved by the L1T group [here](https://github.com/cms-l1t-offline/cmssw/pull/1192)

#### PR description:

This PR updates the displaced track cuts to only use variables available in the track word. The main swap is to use chi2rz/dof and chi2rphi/dof instead of chi2/dof. More on the swapping of the cuts can be seen in the GTT presentation [here](https://indico.cern.ch/event/1356822/contributions/5718823/attachments/2772928/4831803/GTT_disptrkjet_15_12_23.pdf)

#### PR validation:

Checks were made to test the jet efficiency before and after swapping the displaced jet cuts and see no significant change, as can be seen below:
image

All code checks were performed.

### CODE REVIEW

**Comment by epalencia** [comment]
Please test

**Comment by aloeliger** [comment]
+l1
- Already reviewed by L1 in: https://github.com/cms-l1t-offline/cmssw/pull/1192

**Comment by epalencia** [comment]
@cgsavard , there seems to be conflicts with https://github.com/cms-sw/cmssw/pull/43610, could you please check?

**Comment by epalencia** [comment]
Please test

**Comment by aloeliger** [comment]
ping @cms-sw/upgrade-l2

**Comment by subirsarkar** [comment]
+Upgrade

**Comment by rappoccio** [comment]
+1

**Pull request merged**
