### PR TITLE
RazorHbb HLT DQM for 74X

### PR DESCRIPTION
**Pull request by jmduarte**
Changes for Razor Hbb HLT DQM for 74X. Backport of #11644.

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
unfortunately this needs a rebase.
already approved in 76 and 75. please update this PR.
thanks,
F.

**Comment by deguio** [comment]
this brings in 146 commits. please fix.
thanks in advance,
F.

**Comment by Martin-Grunewald** [comment]
-1
Rebase!

**Comment by jmduarte** [comment]
rebased!

thanks!

**Comment by perrotta** [comment]
please test

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
