### PR TITLE
[12.4.X] address undef output of dnn - for issue #37970

### LINKED ISSUE #37970: DQM instability in 12434.0, pixelLessStep_quickAssociatorByHits
In recent PRs it seems the workflow 12434.0 has DQM changes in Tracking/TrackParameters/generalTracks/SeedMon/pixelLessStep/TrackBuilding, pixelLessStep_quickAssociatorByHits

https://github.com/cms-sw/cmsdist/pull/7862
https://github.com/cms-sw/cmssw/pull/37918
https://github.com/cms-sw/cmssw/pull/37952

The change is not always in the same direction:
image
image

@cms-sw/tracking-pog-l2

### PR DESCRIPTION
**Pull request by mmusich**
resolves #37970

#### PR description:

This PR addresses issue https://github.com/cms-sw/cmssw/issues/37970.

In the cand level DNN run after MkFit the output is undetermined if the propagation to the beamline is invalid. This happens in 0.1% of cases at most.

This behaviour is flagged and the output set to -1 (i.e. failing the selection).

I also added a check on ndof > 0 (used to divide chi2), which didn't create problems so far.

#### PR validation:

Example of difference in workflow 12434

no PR https://github.com/cms-sw/cmssw/pull/37918 ------ | with PR https://github.com/cms-sw/cmssw/pull/37918 ----- | fixed

0.951501 the output | 0.951501 the output | 0.951501 the output
0.931231 the output | 0.931231 the output | 0.931231 the output
0.877139 the output | 0.877139 the output | 0.877139 the output
0.557774 the output | 0.557774 the output | 0.557774 the output
0.97176 the output | 0.97176 the output | 0.97176 the output
0.761749 the output | -nan the output | -1 the output
0.485212 the output | 0.485212 the output | 0.485212 the output
-0.888864 the output | -0.888864 the output | -0.888864 the output
0.990027 the output | 0.990027 the output | 0.990027 the output
0.769534 the output | 0.769534 the output | 0.769534 the output
0.962413 the output | 0.962413 the output | 0.962413 the output

The physics changes in MTV validation are almost zero, as expected.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

verbatim backport of https://github.com/cms-sw/cmssw/pull/38004

### CODE REVIEW

**Comment by mmusich** [comment]
backport of https://github.com/cms-sw/cmssw/pull/38004

**Comment by mmusich** [comment]
type bug-fix

**Comment by jpata** [comment]
@cmsbuild please test

**Comment by jpata** [comment]
+reconstruction
- backport of #38004, fixes #37970
- minimal physics changes are expected, but given this is a bugfix, we expect it to be OK for 12_4_0

**Comment by qliphy** [comment]
+1
bugfix

**Pull request merged**
