### PR TITLE
ngrenz: small optimization of Monitor Track inside the DQM

### PR DESCRIPTION
**Pull request by ngrenz**
Work intended to optimize the performance of tracker validation code and code cleanup.

Changes:
- Combination of functions fillModMEs() and fillMEs() with clusterInfos() --> reduce code repetition
- use strstr() instead of find()
- prefer prefix
- inline of some book functions
- put unused code inside a comment

Outputs are supposed to be unchanged.
Any comments and suggestions are welcome.

### CODE REVIEW

**Comment by ngrenz** [comment]
@boudoul FYI

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1
no regression observed.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
