### PR TITLE
addition of BadPFMuonDzFilter plot in nanoDQM_cfi

### PR DESCRIPTION
**Pull request by amkalsi**
This PR includes addition of BadPFMuonDzFilter plot in nanoDQM_cfi in master branch. We missed to add it in PR #30015 #30974.  

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by mariadalfonso** [comment]
+xpog

**Comment by santocch** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
