### PR TITLE
ClusterRepair template initialization bugfix

### PR DESCRIPTION
**Pull request by OzAmram**
#### PR description:
This is a bugfix for the ClusterRepair CPE. Previously, one of the objects used to check whether to run 2D reco or not was not fully initialized. This lead to inconsistent behavior due to dependence on un-initialized variables. The ClusterRepair module is still turned off on during standard reconstruction so we expect no change in all of the tests. With ClusterRepair turned on the difference will be more consistent/better hit position estimates. 

#### PR validation:
Standard runTheMatrix tests have been done.
Also hit position residuals with ClusterRepair on have been checked, and the frequency of the usage of the 2d reco matches our expectations and the expected behavior improvement in residuals is seen.

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
+1
- The initialization was indeed missing, and this PR restores it.
- ClusterRepair is turned off in standard workflows with default configs, and therefore no effect of the bug fix is expected in output
- Jenkins tests pass

**Comment by perrotta** [comment]
type bugfix

**Comment by fabiocos** [comment]
+1

**Pull request merged**
