### PR TITLE
NanoAODv7 code updates [106X]

### PR DESCRIPTION
**Pull request by peruzzim**
#### PR description:

Backport NanoAODv7 feature set (#29212) to 10_6_X, already backported to 10_2_X (#29294).

#### PR validation:

The PR was validated using the standard NanoAOD checks in XPOG.

### CODE REVIEW

**Comment by peruzzim** [comment]
backport #29212

**Comment by peruzzim** [comment]
please test workflow 1325.6,1325.7,1325.8,1329.1,136.7722,136.7952,136.8521

**Comment by peruzzim** [comment]
tests failed because of missing update to cms-data, backport requested there

**Comment by silviodonato** [comment]
test parameters:
- pull_request = https://github.com/cms-data/PhysicsTools-NanoAOD/pull/12
- workflow = 1325.7,1325.6,136.8521,1325.8,136.7722,1329.1,136.7952

**Comment by silviodonato** [comment]
please test

**Comment by mariadalfonso** [comment]
+xpog

- this PR updates nano version V6-->V7
- runTheMatrics shows changes only in the nano

**Comment by perrotta** [comment]
@mariadalfonso @peruzzim : as for the version of this PR in the master, I think it needs #29290
Please confirm. In the meanwhile I'm testing them all together

**Comment by mariadalfonso** [comment]
> @mariadalfonso @peruzzim : as for the version of this PR in the master, I think it needs #29290
> Please confirm. In the meanwhile I'm testing them all together

PR 31063 is simply the V7 nano used for central production of the EOY.

PR 29290 + back port of 30674(not yet available) are related to the JMEnano ( wf10224.15) and should not modify the central nano.

They all need to go in the 10_6 shortly.

**Comment by perrotta** [comment]
+1
- Identical backport of #29212 (excluding a few code format checks which were not yet implemented in 10_6)
- It needs cms-data/PhysicsTools-NanoAOD#12
- As for the backported PR, changes in reco code refer to
  - PhysicsTools/PatAlgos/plugins/LeptonUpdater.cc, where two configuration parameters needed to fix the sign of the impact parameter were added: their default settings do not affect reco outputs
  - Modifications in RecoJets/JetProducers/plugins/BetaStarVarProducer.cc only affect nanoAOD, which is the only user of the "BetaStarPackedCandidateVarProducer" by now
- Jenkins tests show no differences in reco outputs, only in the nanoAOD outputs
- Deprecated "jerc" variables will be replaced by the new ones defined here with the (not yet merged) PR #29290. This apparently affects only JMEnano workflows, which are not run with the standard sequences in 10_6: while in the master this PR merged alone would have broken wfs 25202.01 and 10224.15, in 10_6 this could also be probably merged without #29290

**Comment by slava77** [comment]
@silviodonato @qliphy 
this is missing just the analysis signature.
May I suggest to bypass it here.
Thank you.

**Comment by qliphy** [comment]
+1

**Comment by santocch** [comment]
+1

**Pull request merged**
