### PR TITLE
Fix circular dependencies between Geometry packages

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

Broke the circular dependency between GeometryCommonDetAlgo and GeometrySurface.

#### PR validation:

The code compiles and using `git grep` finds no other includes of the old places for the header files.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by cvuosalo** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
