### PR TITLE
Tracker sub-DetId deprecation for TrackFitters DebugHelpers.h

### PR DESCRIPTION
**Pull request by pieterdavid**
Technical change, no differences expected.

- moved DebugHelpers header from GsfTracking/src to TrackFitters/interface
- made MessageLogger category a parameter
- stopped printing layer number to remove dependency on specific DetIds and TrackerTopology

as discussed with @VinInn and @mmusich  in #19398 

cc: @OlivierBondu @alesaggio @vidalm 

tracked at  #19398

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by slava77** [comment]
```
edm::FileInPath unable to find file L1Trigger/L1TCalorimeter/data/Tau_TrimmingShapeVeto_LUT_v1.0.0.txt anywhere in the search path.
```

the tests were done in CMSSW_9_2_X_2017-06-23-1100
do we need to wait for the next IB due to some external changes and this PR being ahead of CMSSW_9_2_X_2017-06-23-1100
or is there a broken IB?
@davidlange6 @smuzaffar

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by perrotta** [comment]
+1
Technical (mostly removal of duplicated code), no effect on jenkins tests

**Comment by davidlange6** [comment]
+1

**Pull request merged**
