### PR TITLE
Apply ld fix for AllocMonitor to sl7 as well

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

The sl7 dynamic loader also does allocations so needs the work around.

#### PR validation:

Code compiles and now runs under sl7 builds.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
type bugfix

**Comment by makortel** [comment]
Comparison differences look like https://github.com/cms-sw/cmssw/issues/39803

**Comment by makortel** [comment]
Umm, the slc7 test ran only unit tests of `Configuration/PyReleaseValidation`?

**Comment by smuzaffar** [comment]
test parameters:
- addpkg = PerfTools/AllocMonitor

**Comment by smuzaffar** [comment]
please test for slc7_amd64_gcc11

make sure to checkout `PerfTools/AllocMonitor ` to run/test the unit tests

**Comment by smuzaffar** [comment]
I think it is better to move the unit tests https://github.com/cms-sw/cmssw/blob/master/PerfTools/AllocMonitor/test/BuildFile.xml#L6-L23 to `PerfTools/AllocMonitorPreload` package. Currently there is kind of cyclic dependency as `PerfTools/AllocMonitorPreload` depends on `PerfTools/AllocMonitor` while the unit tests of `PerfTools/AllocMonitor` depend on `PerfTools/AllocMonitorPreload`

**Comment by makortel** [comment]
@Dr15Jones What would you think about @smuzaffar's suggestion

> I think it is better to move the unit tests https://github.com/cms-sw/cmssw/blob/master/PerfTools/AllocMonitor/test/BuildFile.xml#L6-L23 to `PerfTools/AllocMonitorPreload` package. Currently there is kind of cyclic dependency as `PerfTools/AllocMonitorPreload` depends on `PerfTools/AllocMonitor` while the unit tests of `PerfTools/AllocMonitor` depend on `PerfTools/AllocMonitorPreload`

**Pull request merged**
