### PR TITLE
 L1TPF: Update single particle resolution in HGCal (11_1 backport)

### PR DESCRIPTION
**Pull request by rekovic**
#### PR description:
Update single particle resolution in HGCal. 
The only missing update by Giovanni (more details in https://hypernews.cern.ch/HyperNews/CMS/get/L1TriggerUpgrades/384/1/1/1/1/2/3/2.html)
Needed for HLT TDR reprocessing. 

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by rekovic** [comment]
please test

**Comment by rekovic** [comment]
urgent

**Comment by silviodonato** [comment]
abort

**Comment by silviodonato** [comment]
clone of https://github.com/cms-sw/cmssw/pull/30770

**Pull request closed without merging**
