### PR TITLE
Fix nano aod customize v10

### PR DESCRIPTION
**Pull request by vlimant**
#### PR description:

this mitigate the migration of V10 Nano configuration from an unmaintainable customise to the `-s NANO:PhysicsTools/NanoAOD/V10/nano_cff` syntax in cmsDriver (migration done in #39337  

#### PR validation:

the workflow in the matrix that were calling for V10 customise now configure properly

### CODE REVIEW

**Comment by vlimant** [comment]
would be better this PR instead of #39620

**Comment by vlimant** [comment]
140.001 succeeded

**Comment by vlimant** [comment]
please test

**Comment by perrotta** [comment]
Thank you @vlimant !
Let test with some additional random workflow among those now failing in the IB, instead...

**Comment by perrotta** [comment]
please abort

**Comment by perrotta** [comment]
please test workflow 140.002, 149.134, 140.116, 10224.15, 11634.15, 25202.15

**Comment by perrotta** [comment]
urgent
(otherwise we will be forced to revert https://github.com/cms-sw/cmssw/pull/39337 before building CMSSW_12_6_0_pre3)

**Comment by vlimant** [comment]
I cannot find `149.134` in the matrix @perrotta ; what workflow was it supposed to be ?

**Comment by perrotta** [comment]
> I cannot find `149.134` in the matrix @perrotta ; what workflow was it supposed to be ?

Uhm, me too...
Quite likely I mistyped it. Sorry for that, let me retry

**Comment by perrotta** [comment]
please test workflow 140.002, 140.034, 140.116, 10224.15, 11634.15, 25202.15

**Comment by vlimant** [comment]
+1

**Comment by perrotta** [comment]
@cms-sw/pdmv-l2 (in particular!) @cms-sw/reconstruction-l2 @cms-sw/upgrade-l2 this PR looks like being able to fix the multitude of relval crashes we had in the last two IBs. Could you please evaluate and sign, if you think so, at your earliest?

**Comment by mandrenguyen** [comment]
+reconstruction

**Comment by srimanob** [comment]
Hi @vlimant 
Could you please clarify NANO versions of 11634.0 (Run-3 MC) ? Is it v10, or else? Here is the config from the PR test,
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-9cb298/28018/runTheMatrix-results/11634.0_TTbar_14TeV+2021+TTbar_14TeV_TuneCP5_GenSim+Digi+RecoNano+HARVESTNano+ALCA/step3_RAW2DIGI_L1Reco_RECO_RECOSIM_PAT_NANO_VALIDATION_DQM.py

I would like to avoid the situation that we run different version of Nano between Data (it seems to me that PR sets it to V10 explicitly) and MC.

Thanks.

**Comment by vlimant** [comment]
@srimanob : it seems to be the master NANO (i.e. not V10 explicitly), as it should be.

**Comment by srimanob** [comment]
+Upgrade

**Comment by perrotta** [comment]
+1

**Pull request merged**
