### PR TITLE
do not throw in PerigeeConversions::ftsToPerigeeParameters

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

- The function now returns an std::optional
- code formatting

The exception was being seen very frequently in a prompt reconstruction job. This made running the job under the debugger looking for an exception which caused the job to fail very difficult.

#### PR validation:

Code compiles.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
This was prompted by #45162

**Comment by tvami** [comment]
+1
 * tests pass

**Comment by mandrenguyen** [comment]
+1

**Comment by rappoccio** [comment]
+1

**Pull request merged**
