### PR TITLE
backporting 31553 to 75X

### PR DESCRIPTION
**Pull request by gkrintir**
backport of #31553

Needed for HINPbPbWinter16pLHE

### CODE REVIEW

**Comment by SiewYan** [comment]
please test

**Comment by agrohsje** [comment]
test parameters:
- workflows = 1370.0,1370.17,1370.18,25215.0,25215.17,25215.18

**Comment by agrohsje** [comment]
please test

**Comment by silviodonato** [comment]
Do you really need a backport to `7_5_X`? Could you specify the reason and the production name?
The last release of `7_5_X` was built almost 3 years ago https://github.com/cms-sw/cmssw/releases/CMSSW_7_5_9

**Comment by gkrintir** [comment]
Hi @silviodonato the heavy ion dataset in 2015 relies on that release, we also have open campaings, e.g,

https://cms-pdmv.cern.ch/mcm/requests?member_of_campaign=HINPbPbWinter16pLHE&page=0&shown=127

Regards

**Comment by silviodonato** [comment]
@gkrintir (and @cms-sw/pdmv-l2)  I cannot write on https://its.cern.ch/jira/browse/PDMVRERECO-37 so I'm writing here.
During the last ORP meeting @smuzaffar proposed to create a script `xrd` which "emulate" the behaviour of the current `xrd` but using `xrootd`. This update will be done at level of SCRAM, and so we don't need to make a patch of all releases. I will let you know when the fix will be ready.

**Comment by smuzaffar** [comment]
Fix is ready and available on cvmfs now

**Comment by gkrintir** [comment]
Many thanks @silviodonato @smuzaffar!

**Pull request closed without merging**
