### PR TITLE
Fix the duplicated HF channels

### PR DESCRIPTION
**Pull request by lihux25**
Throw a LogError if this is found and an empty HF digi collection is put into event.

See discussion thread https://hypernews.cern.ch/HyperNews/CMS/get/recoDevelopment/1390.html for more information.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@lihux25 
please make 75X and 76X PRs with the same change

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/11702	18c6691
- changes in the code are in line with the intended fix for the crash reported in https://hypernews.cern.ch/HyperNews/CMS/get/recoDevelopment/1390.html
- jenkins tests pass and comparisons with baseline show no differences (as expected on good data inputs)
- tested locally in CMSSW_7_4_14
    -  with several run2 PromptReco workflows (2 in 2015B, 1 in 2015C and 2 in 2015D, 200 events each) observe no differences as expected
    - the crash is now gone: the same (previously crashing) input file processing has quite a few more events with bad HF data: they all appear with the error message now, e.g. (some have more than 20 times)
```
%MSG-e HcalRawToDigi:  HcalRawToDigi:hcalDigis 09-Oct-2015 18:45:28 CEST  Run: 258177 Event: 2673815518
Duplicated HF digis found for 20 times
```

**Comment by davidlange6** [comment]
+1

**Pull request merged**
