### PR TITLE
Remove HLT-like customisations from RelVal step for HI Run2 MC

### PR DESCRIPTION
**Pull request by diguida**
The `run2_mc_HIon` key is added to the list of available GlobalTags for testing purposes, originally in `autoCond`, by `autoCondHLT`, so it is specific for TSG tests, like `addOn`.
This key is now removed in RelVal steps and local tests. It is in fact kept for HLT tests.

### CODE REVIEW

**Comment by diguida** [comment]
@mmusich this is something to want to watch as well.

**Comment by diguida** [comment]
please test

**Comment by diguida** [comment]
assign alca

**Comment by diguida** [comment]
test failure unrelated to this PR

**Comment by diguida** [comment]
please test
Let's try again

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/12648	393d02a
- code changes are as described; reco is minimally affected: only in (unused?) test files in RecoHI/HiCentralityAlgos
- jenkins tests pass and comparisons with baseline show no differences as expected

**Comment by fabozzi** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
