### PR TITLE
Hcal Geometry Packages Dependency Cleanup

### PR DESCRIPTION
**Pull request by ianna**
- Moving files to reduce dependencies for Reco part
- Remove unused code

```
Geometry/HcalAlgo:
    DetectorDescription/Algorithm
    DetectorDescription/Base
    DetectorDescription/Core
    FWCore/MessageLogger
    FWCore/PluginManager
    tools/Clhepheader

Geometry/HcalCommonData:
    CondFormats/GeometryObjects
    DataFormats/HcalDetId
    DetectorDescription/Base
    DetectorDescription/Core
    FWCore/Framework
    FWCore/MessageLogger
    FWCore/ParameterSet
    Geometry/CaloTopology
    Geometry/Records
    tools/Boost
    tools/Clhepheader

Geometry/HcalEventSetup:
    CondFormats/Alignment
    CondFormats/AlignmentRecord
    DataFormats/HcalDetId
    FWCore/Framework
    FWCore/MessageLogger
    FWCore/ParameterSet
    FWCore/Utilities
    Geometry/CaloEventSetup
    Geometry/CaloGeometry
    Geometry/CaloTopology
    Geometry/HcalTowerAlgo
    Geometry/Records
    tools/Boost

Geometry/HcalSimData:

Geometry/HcalTestBeamData:
    DetectorDescription/Algorithm
    DetectorDescription/Base
    DetectorDescription/Core
    FWCore/MessageLogger
    FWCore/PluginManager
    tools/Clhepheader

Geometry/HcalTowerAlgo:
    CondFormats/AlignmentRecord
    DataFormats/CaloTowers
    DataFormats/Common
    DataFormats/DetId
    DataFormats/GeometryVector
    DataFormats/HcalDetId
    FWCore/Framework
    FWCore/MessageLogger
    FWCore/ParameterSet
    FWCore/PythonParameterSet
    FWCore/Utilities
    Geometry/CaloGeometry
    Geometry/CaloTopology
    Geometry/Records
    tools/Boost
    tools/Roofitcore
```

### CODE REVIEW

**Comment by ianna** [comment]
@bsunanda - please, comment.

**Comment by bsunanda** [comment]
Yana

I am not sure how I integrate my changes with this. Shall I try to make a fresh commit on top of this and make a PR? But I want the new geometry files in DB (only the CompactView's - please wait a while for the parameters).

Sunanda
________________________________

**Comment by ianna** [comment]
@bsunanda - I think, this PR can be merged with IBs independently as it does not change functionality. If you make your changes on top of it, your PR will not conflict even if this one goes in the IB before yours.

**Comment by ianna** [comment]
+1

**Comment by ianna** [comment]
+1

**Comment by ianna** [comment]
@ggovi - Please, have a look. It's just moving files around to reduce dependencies for RECO step. Thanks.

**Comment by ianna** [comment]
@ggovi  - Please, check. Thanks.

**Comment by ggovi** [comment]
+1

**Comment by davidlange6** [comment]
@ianna - is there a 76x version of this?

**Comment by bsunanda** [comment]
Hi David

I am working on it. I plan to make a few more changes which we discussed in the last simulation meeting. DO I close this PR?

Sunanda
________________________________

**Comment by ianna** [comment]
@davidlange6 - this one should go in 75x.

**Comment by davidlange6** [comment]
saved for 76x.

**Pull request closed without merging**
