### PR TITLE
Pixel vertex counting alca reco v1

### PR DESCRIPTION
**Pull request by capalmer85**
The files added/altered introduce a new ALCAReco for zerobias/random triggers.  Pixels clusters and offline reconstructed vertices are saved in the event content for the dual purpose of offline validation of online luminosity and low luminosity luminometer normalization (with vertex counting).

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild please test

**Comment by mmusich** [comment]
@capalmer85 can you put for reference a brief summary of the expected changes in the description fiedl? Thanks

**Comment by diguida** [comment]
+1

**Comment by diguida** [comment]
@capalmer85 
Next steps are:
1. backport to 74X
2. think of the RelVal workflows where you need to add this AlCaReco.
We will follow up with PdmV.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
