### PR TITLE
Define new CLCT digi format for Run-3

### PR DESCRIPTION
**Pull request by dildick**
#### PR description:

During Run-3 the CSC DPG group is planning to run the CSC trigger with new CLCT patterns based on a 12-bit comparator code. These new CLCTs will be of type `CSCCLCTRun3Digi` to differentiate with the legacy `CSCCLCTDigi` used in Run-1 and Run-2. An introduction to the new CLCT patterns can be found here: https://indico.cern.ch/event/778315/contributions/3238278/subcontributions/268636/attachments/1770627/2876988/181213-CCStatus_WNASH.pdf. A related PR is #28600.

#### PR validation:

The code compiles. `CSCCLCTRun3Digis` are not yet produced in CMSSW. This will be done in a future PR. There should be no change in any standard sequence.

#### if this PR is a backport please specify the original PR:

N/A

@ptcox @tahuang1991

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by dildick** [comment]
@civanch Could you wait with signing off for now?

**Comment by fabiocos** [comment]
@dildick are you expect further development or validation?

**Comment by fabiocos** [comment]
hold

pending a possible alternative proposal by @dildick

**Comment by silviodonato** [comment]
@dildick shall we continue to wait for an update of this PR?

**Comment by dildick** [comment]
Hi Silvio, I'm working on an alternative proposal where I expand the CLCT data format for Run-3. I plan to present it soon in a CSC DPG meeting. So I suppose we can close this for now.

**Comment by silviodonato** [comment]
Ok, let's close this PR. Let me know in case you want to open it again.

**Pull request closed without merging**
