### PR TITLE
Run3-alca251 Modify the HCAL calibration macros in view of current and 2025 IsoTrack calibrations

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Modify the HCAL calibration macros in view of current and 2025 IsoTrack calibrations

#### PR validation:

Tested for isotrack calibration

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by perrotta** [comment]
please test
(DAS error in obviously unrelated, and given that only macros are modified here there is not even need to look at the differences in the test outputs; but let retry once nonetheless)

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by perrotta** [comment]
+alca

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
