### PR TITLE
Updating L1TO2O with extra HI CaloParams

### PR DESCRIPTION
**Pull request by kkotov**
This is a patch including additional 9 CaloLayer2 parameters required for running the emulator (e.g. in DQM) with real configuration at p5.

### CODE REVIEW

**Comment by rekovic** [comment]
@kkotov 
You introduce new file caloStage2Params_2016_v3_3_HI_towEta27_cfi.py, but it is not used anywhere.
Instead, caloStage2Params_2016_v3_3_HI_cfi.py which in PR #16678 is already adjusted for the firmware bug and towEta 28 --> 27, is used. 

Is this PR meant to be used together with https://github.com/cms-sw/cmssw/pull/16678 ?  If so, can you please comment in the header.

**Comment by rekovic** [comment]
please test

**Comment by kkotov** [comment]
@rekovic , it looks indeed like the two PRs, although independent, are addressing the DQM issues with CaloLayer2 in HI run. My guess is that both should go into the same patch release. Let's see if @bundocka wants to comment on that. As of the caloStage2Params_2016_v3_3_HI_towEta27_cfi.py, I should have included this to be a prototype in the L1T O2O config producer. I'll do that now ...

**Comment by kkotov** [comment]
@rekovic hmm, if you say that #16678 already has the default caloStage2Params_2016_v3_3_HI_cfi.py with equivalent to caloStage2Params_2016_v3_3_HI_towEta27_cfi.py fix, maybe I don't even need to change anything, then

**Comment by rekovic** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
