### PR TITLE
Add era modifier for Run3 and HcalPFCuts withTopo to event record

### PR DESCRIPTION
**Pull request by RSalvatico**
#### PR description:

This PR addresses the technical baseline changes needed by #43025 and #43164: the addition of an Era Modifier, its implementation into Era_Run3, and mostly the addition of HcalPFCuts to the event record.

#### PR validation:

runTheMatrix.py -l 10824.0
runTheMatrix.py -l 10024.0

### CODE REVIEW

**Comment by RSalvatico** [comment]
type egamma

**Comment by RSalvatico** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by mmusich** [comment]
hold
   * once https://github.com/cms-sw/cmssw/pull/43025 is merged, this PR becomes unnecessary

**Comment by mmusich** [comment]
as far as I can tell, this PR can be close now. @RSalvatico

**Comment by RSalvatico** [comment]
> as far as I can tell, this PR can be closed now. @RSalvatico

Closing

**Pull request closed without merging**
