### PR TITLE
Fix saveTags() and abs() use in HLTEgammaL1TMatchFilterRegional (92X)

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
Fix saveTags() and abs() use in HLTEgammaL1TMatchFilterRegional (92X)

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
backport of #19750

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
@smuzaffar 
Jenkins claims an AddOnTest failed but does not say which one.
Could you please have a look?

**Comment by smuzaffar** [comment]
please test
I am asking to re-do the tests as there was some issues with jenkins over the weekend.

**Comment by Martin-Grunewald** [comment]
+1
Can't reproduce jenkins error!

**Comment by Martin-Grunewald** [comment]
type bugfix

**Comment by davidlange6** [comment]
+1

**Pull request merged**
