### PR TITLE
Add missing pair dictionaries in DataFormats/GEMDigi

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

DQM/Integration unit tests fail without these dictionaries.

#### PR validation:

The minimum failing configuration now is able to start processing where before it failed during startup.

### CODE REVIEW

**Comment by silviodonato** [comment]
please test

**Comment by Dr15Jones** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by Dr15Jones** [comment]
ping @kpedro88

**Comment by kpedro88** [comment]
+upgrade

**Comment by silviodonato** [comment]
+1

**Pull request merged**
