### PR TITLE
Modernized PropagatorWithMaterialESProducer

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

- pull out parameters in the constructor
- switch to ESGetToken
- added fillDescriptions

#### PR validation:

Code compiles. This is purely a refactoring and is not intended to cause any changes.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by perrotta** [comment]
please test
(offending PR has been reverted in the last IB CMSSW_11_0_X_2019-07-10-2300)

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/27482	5232ef1
- code changes are in line with the PR description; mostly technical
- jenkins tests pass and comparisons with the baseline show no differences

**Comment by fabiocos** [comment]
+1

**Comment by makortel** [comment]
part of #26748

**Pull request merged**
