### PR TITLE
(PhysicsTools/SelectorUtils) move needed dependencies out of export section

### PR DESCRIPTION
**Pull request by davidlange6**
changes are to dependencies used in interface.. (probably mistakenly added by a script of mine to the wrong part of the buildfile..)

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

On Feb 27, 2021 7:09 PM, cmsbuild <notifications@github.com> wrote:

A new Pull Request was created by @davidlange6<https://github.com/davidlange6> (David Lange) for master.

It involves the following packages:

PhysicsTools/SelectorUtils

@perrotta<https://github.com/perrotta>, @jpata<https://github.com/jpata>, @cmsbuild<https://github.com/cmsbuild>, @slava77<https://github.com/slava77> can you please review it and eventually sign? Thanks.
@silviodonato<https://github.com/silviodonato>, @dpiparo<https://github.com/dpiparo>, @qliphy<https://github.com/qliphy> you are the release manager for this.

cms-bot commands are listed here<http://cms-sw.github.io/cms-bot-cmssw-cmds.html>

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/33014	0ad9fc8
- technical; implemented in line with the PR description
- jenkins tests pass (ignoring unrelated failures in what looks like repeating in a few other PR tests)

**Comment by qliphy** [comment]
+1

**Comment by qliphy** [comment]
merge

**Pull request merged**
