### PR TITLE
add tracking hit effiicency vs BX on relval (data workflows only)

### PR DESCRIPTION
**Pull request by mtosi**
this update adds the hit efficiency vs BX on data relval workflows (and all PDs)
@rovere @vininn

### CODE REVIEW

**Comment by slava77** [comment]
@mtosi 
what's the memory increase from this?
3564 bins x the number of different types of histograms can become large.

**Comment by mtosi** [comment]
citing @rovere  (thanks)
1 histo w/ 3600 bins --> 3600 x 8bytes ~ 4k x 8 = 32 kB 
there are 1 histo per partitions x (type of hit + eff)
there are 27 partitions => 135 histos + 27 histos = 162 histos
=> ~5MB

**Comment by slava77** [comment]
Sumw2 is never called, right?
it will add 16 bytes per bin.

**Comment by mtosi** [comment]
=> 15MB ?

**Comment by rovere** [comment]
Not locally, not sure globally (i.e. via static member functions, e.g. https://root.cern.ch/doc/master/TH1_8cxx_source.html#l06247)

**Comment by slava77** [comment]
On 6/17/16 8:17 AM, mia tosi wrote:
> => 15MB ?

sounds small.
I suppose there is only one instance of the monitoring module doing it.
Please confirm.

**Comment by rovere** [comment]
One instance per stream, you mean, right?
I let Mia comment for how many selected-track-collection we do have the monitoring enabled, since those counts separately as instances, if that's what you are asking for.

**Comment by mtosi** [comment]
generalTracks and HP tracks w/ pT > 1 GeV
if tracking POG agrees, I can limit these plots to HP w/ pT > 1

**Comment by rovere** [comment]
Ok, for vs BX enable only HP, pt >1

**Comment by mtosi** [comment]
I'm going to update the PRs, thus

**Comment by VinInn** [comment]
@cmsbuild , please test

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
