### PR TITLE
fillDescriptions migration and parameter cleanup in DAQ modules (80X)

### PR DESCRIPTION
**Pull request by smorovic**
Changes:
- Migrating production DAQ modules EvFDaqDirector, EvFOutputModule, FedRawDataInputSource and FastMonitoringService to using fillDescriptions. Removing cfi python files for those cases.
- Removing obsolete parameters from those modules
- Allow FastMonitoringService to find definition file in both CMSSW_BASE and CMSSW_RELEASE_BASE (those differ when running from project area).

Port of #12146 (75X) and #12147 (76X)

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
@smorovic:
Please try to fix the problems found by the static analyzer in EvFDaqDirector.cc, FastMonitoringService.cc, and FedRawDataInputSource.cc. We are trying to fix as many static analyzer issues as we can.
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-12148/9399/llvm-analysis/

**Comment by smorovic** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by smorovic** [comment]
I applied updates based on some of the changes. Here is a summary of those that still remain:

Dereference of null pointer in ExceptionGenerator.cc
    * module intentionally dereferences null pointer (twice) to crash as part of the test. we could probably fool the checker here by "calculating" 0.

non-const global static variables in crc32c.cc:
• these are all initialized with pthread_once (thread safe)

non-const (global) static variable in json_value.cpp
• json library intializes some references during initialization of static global data, before main(). As far as I understand, this is safe.
• more modern version of the library doesn't seem to do this: https://github.com/open-source-parsers/jsoncpp/blob/master/src/lib_json/json_value.cpp
       so eventually we could migrate to it.

"inherits from edm::EDProducer,edm::EDFilter,edm::EDAnalyzer, or edm::OutputModule"
• some modules are not yet ported to the new interfaces (not used in production, but for testing or debugging raw data). They could probably easily be converted to "one" interfaces, but I didn't do it at this time.

non-const static variable in    EventFilter/Utilities/plugins/RawEventFileWriterForBU.cc
• this module used only for testing purpose. static member pointer provides member data access to the custom signal handler

const_cast used on a pointer to a data class     EventFilter /Utilities/src /json_value.cpp
• same variable is used to store const and non-const variant (a boolean flag set differently for two cases). Non-trivial to fix in the json library
          - to just silence the test, probably it can be achieved with putting char * and const char* in union and use either one where appropriate....


Also I modifies this one, but static checker still complains:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-12148/9436/llvm-analysis/report-5a0da4.html#EndPath

**Comment by mommsen** [comment]
+1

**Comment by cvuosalo** [comment]
@smorovic: It looks like you may have missed a simple const problem in FastMonitoring.cc, line 116:
```
legendaVector.append(Json::Value(*((std::string *)(encPath_[0].decode(i)))));
```
Won't `const std:string *` fix this one?

https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-12148/9436/llvm-analysis/report-2ae9d4.html#EndPath

**Comment by smorovic** [comment]
@cvuosalo,
that one was changed in other PR (using C++ style casts).
Here is the change:
https://github.com/cms-sw/cmssw/pull/12245/files#diff-6868dae040be2082e8a0d79168e37c1bR91
Merge of that PR is still pending.

**Comment by cvuosalo** [comment]
@smorovic: Yes, I see it now. I got confused because there are three 80X PRs that all include FastMonitoringService.cc. Please make sure there is no mix-up during merging that could cause the older version of the file to overwrite the correct version in #12245.

**Comment by cvuosalo** [comment]
+1

For #12148 36f1757b4895d7c8918ebb610d946a112532e89a

fillDescriptions migration in DAQ modules. #12146 and #12147 are the 75X and 76X versions of this PR, and they have already been approved by Reco.

#12245 has a fixed version of FastMonitoringService.cc that should take precedence over the version of this file in this PR.

The code changes are satisfactory, and Jenkins tests against baseline CMSSW_8_0_X_2015-11-02-2300 show no significant differences.

**Comment by smorovic** [comment]
I was taking into account that these changes merge together (also git is smart to take into account "git mv" when it's merged with other commits). Usually also git doesn't silently revert changes, but produces conflicts. In my tests all three merges fine. If any conflict pops up, I will rebase as necessary.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
