### PR TITLE
 [13_0_X SIM] Backport of ZDC transport modifier for heavy ion simulation modifier

### PR DESCRIPTION
**Pull request by civanch**
#### PR description:
Backport of #43493, which extend modifier for heavy ion FullSim for Run3. SHould not affect any pp workflow.

#### PR validation:
private

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for: 
backport from 14_0_X

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

The regression is broken only in one MkFit WF, which is known. So, pp Run-3 is not affected as expected.

**Comment by rappoccio** [comment]
+1

**Pull request merged**
