### PR TITLE
Make VLumiRange be only strings

### PR DESCRIPTION
**Pull request by ericvaandering**
since it lost the ability to deal with unicode

### CODE REVIEW

**Comment by ericvaandering** [comment]
This "fixes" #23774 I still think the original patch that caused this is quite dangerous, but if the LumiLists are really the only problem this should fix it

**Comment by Dr15Jones** [comment]
please also make a pull request for the master branch

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
backport #24169

**Comment by Dr15Jones** [comment]
bugfix

**Comment by Dr15Jones** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
