### PR TITLE
Cleaning Cosmic and HI event content structures

### PR DESCRIPTION
**Pull request by jeongeun**
#### PR description:  
Cleaning up the cosmic and heavy-ion event content structures.
- For improving clarity, moving extend commands to the right after the corresponding output commands (PSet). 
- Clean up unused parts and Remove duplicated import lines. 
- Unify the Modifier styles. 
2 central event content file (`Configuration/EventContent/python/EventContentCosmics_cff.py` and `Configuration/EventContent/python/EventContentHeavyIons_cff.py` ) +
2 additional cosmic files also changed (`RecoLocalMuon/Configuration/python/RecoLocalMuonCosmics_EventContent_cff.py` and `RecoLocalTracker/Configuration/python/RecoLocalTracker_Cosmics_EventContent_cff.py`).

(the previous PR was [#PR29920](https://github.com/cms-sw/cmssw/pull/29920))
#### PR validation:
Event Content comparison check was also done and there is no change with these updates.
Tested in CMSSW_11_1_X, the basic test all passed in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html).

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
Both failing workflows are Cosmics, therefore quite likely affected by the Event Content changes in this PR

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
After the latest adjustments the cleaned up event contents behave correctly, and a visual line-by-line inspection confirms the same.

At this point. I'd only suggest a few minor aesthetical updates.

- In EventContentCosmics_cff.py:
  - FEVTEventContent = RAWEventContent + RECOEventContent
  - FEVTSIMEventContent = RAWSIMEventContent + RECOSIMEventContent

- In EventContentHeavyIons_cff.py:
  - FEVTSIMEventContent, RAWDEBUGEventContent, RECODEBUGEventContent, RAWSIMEventContent: move the extention with "HiMix*" after the extention with the "parent" event content (or, aternatively, do the opposite in RECOSIMEventContent and AODSIMEventContent, just to maintain the same order il all similar structures)

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
Sorry @jeongeun , my comment on EventContentCosmics_cff.py was not as innocuous as it looked to me, 
In fact, you cannot do
- FEVTEventContent = RAWEventContent + RECOEventContent
- FEVTSIMEventContent = RAWSIMEventContent + RECOSIMEventContent

because both RECOEventContent and RECOSIMEventContent start with a "drop *" which cancel whatever was listed before.

One could perhaps define some RecoOutput and RecoSimOutput, analogously to what was originally in the HI event content, and apply the same here, in order to simplify...

But I think that the easiest thing would be to just revert the change I asked you to apply on EventContentCosmics_cff.py to your previous implementation, which worked just fine.

The aesthetical update in EventContentHeavyIons_cff.py can remain, instead.

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
+1
- Some reordering and cleaning of the Cosmic and HI event contents, with no change in the actually saved products
- Jenkins tests pass

**Comment by silviodonato** [comment]
+operations

**Comment by silviodonato** [comment]
+1

**Comment by makortel** [comment]
Could this PR be causing the following failures 140.0 and 150.0?
```
An exception of category 'ProductNotFound' occurred while
   [0] Calling EventProcessor::runToCompletion (which does almost everything after beginJob and before endJob)
Exception Message:
The RandomNumberGeneratorService is trying to restore
the state of the random engines by reading a product from
the LuminosityBlock with input tag "InputTag:  label = randomEngineStateProducer, instance = beginLumi, process = @skipCurrentProcess".
It could not find the product.
Either the product in the LuminosityBlock was dropped or
not produced or the configured input tag is incorrect or there is a bug somewhere
```
By quick look I did not see any changes related to `IOMCRAW` in the `EventContentHeavyIons_cff.py` though.

Let's follow up in #30095

**Pull request merged**
