### PR TITLE
Removed unused EDAnalyzer.h from METTester

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

The header is deprecated.

#### PR validation:

Code compiles.

### CODE REVIEW

**Comment by perrotta** [comment]
@Dr15Jones could you also please remove [L48](https://github.com/cms-sw/cmssw/blob/fb0f1a65c708310f2d490694696fbc1e3035bfd3/Validation/RecoMET/plugins/METTester.h#L48)
Then this PR can even be removed without tests, to save resources

**Comment by Dr15Jones** [comment]
@perrotta 
> could you also please remove [L48](https://github.com/cms-sw/cmssw/blob/fb0f1a65c708310f2d490694696fbc1e3035bfd3/Validation/RecoMET/plugins/METTester.h#L48)

Done

**Comment by perrotta** [comment]
merge
(no need to wast resources in running tests for this trivial PR)

**Comment by emanueleusai** [comment]
+1

**Pull request merged**
