### PR TITLE
Fix logic error in `FinalPath` checks [13.3.x]

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

If an `EDProducer` or `EDFilter` is inserted in a `FinalPath`, the job fails with a cryptic error:
```
----- Begin Fatal Exception 03-Oct-2023 15:42:41 CEST-----------------------
An exception of category 'ConfigFileReadError' occurred while
   [0] Processing the python configuration file named dump.py
Exception Message:
 unknown python problem occurred.
AttributeError: 'str' object has no attribute 'label_'

At:
  /data/user/fwyzard/CMSSW_13_3_X_2023-10-02-2300/src/FWCore/ParameterSet/python/Config.py(1292): <listcomp>
  /data/user/fwyzard/CMSSW_13_3_X_2023-10-02-2300/src/FWCore/ParameterSet/python/Config.py(1292): _insertPaths
  /data/user/fwyzard/CMSSW_13_3_X_2023-10-02-2300/src/FWCore/ParameterSet/python/Config.py(1490): fillProcessDesc
  <string>(2): <module>

----- End Fatal Exception -------------------------------------------------
```

With these changes, the error is more meaningful:
```
----- Begin Fatal Exception 03-Oct-2023 15:46:00 CEST-----------------------
An exception of category 'ConfigFileReadError' occurred while
   [0] Processing the python configuration file named dump.py
Exception Message:
 unknown python problem occurred.
RuntimeError: FinalPath HLTriggerFinalPath has non OutputModules HLTBool,TriggerSummaryProducerRAW

At:
  /data/user/fwyzard/CMSSW_13_3_X_2023-10-02-2300/src/FWCore/ParameterSet/python/Config.py(1290): _insertPaths
  /data/user/fwyzard/CMSSW_13_3_X_2023-10-02-2300/src/FWCore/ParameterSet/python/Config.py(1487): fillProcessDesc
  <string>(2): <module>

----- End Fatal Exception -------------------------------------------------
```

Implement the python checks to notify that also `EDAnalyzer`s are not supported on `FinalPath`s.

The unit tests are extended to catch the error.

#### PR validation:

The extended unit tests pass.

#### PR backport:

Backport of #42936

### CODE REVIEW

**Comment by fwyzard** [comment]
type bugfix

**Comment by fwyzard** [comment]
backport #42936

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
please test

**Comment by makortel** [comment]
Comparisons show https://github.com/cms-sw/cmssw/issues/39803
Logs show https://github.com/cms-sw/cmssw/issues/43293

**Comment by makortel** [comment]
+core

**Pull request merged**
