### PR TITLE
74X 25ns HLT - round four

### PR DESCRIPTION
**Pull request by perrotta**
Developed on top of #11041, which is still pending in the 74X queue.

Based on CMSSW_7_4_12_patch1

It includes (by now...) updates to the HLT menu up to /dev/CMSSW_7_4_0/HLT/V480

It also includes a fix that prevents FastSim crashing if the new menus in #11041 are run (those menus are not used in the standard workflows, though).

### CODE REVIEW

**Comment by perrotta** [comment]
+1

**Comment by perrotta** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
+1

**Pull request merged**
