### PR TITLE
Hlt tau validation conditional plotting3

### PR DESCRIPTION
**Pull request by slehti**
Same as HLTTauDQM: conditional plotting #30243 and #30701.

Did not manage to rebase #30701. Cherry-picked, refused to be added in branch HLTTauValidation_ConditionalPlotting2.
Closing, and continuing in branch HLTTauValidation_ConditionalPlotting3.

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
Thanks @slehti  for this cleaning.
At least two workflows (11634.0 and 12434.0) do not get some (82) HLT/TAU plots removed but instead get 0 stats:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_11_2_X_2020-07-20-2300+948c55/37860/dqm-histo-comparison-summary.html
It would be nice to remove them to not store empty MEs which may confuse TAU POG

**Comment by silviodonato** [comment]
Kind reminder @slehti

**Comment by silviodonato** [comment]
Kind reminder @slehti

**Pull request closed without merging**
