### PR TITLE
Fix the TriggerResultsFilter default configuration to skip the current process

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

The default configuration of `TriggerResultsFilter` tries to read the `TriggerResults` without specifying any process label, which is understood as wanting to read from the current process.
This leads to test for the `TriggerResultsFilter` failing because of a conflict in the schedule.

This PR updates the default configuration to ignore the current process.

#### PR validation:

`HLTrigger/HLTfilters/test/triggerResultsFilter.py` now works:

```bash
cmsRun HLTrigger/HLTfilters/test/triggerResultsFilter_producer.py
...
cmsRun HLTrigger/HLTfilters/test/triggerResultsFilter.py
...
TrigReport ---------- Path   Summary ------------
TrigReport  Trig Bit#   Executed     Passed     Failed      Error Name
TrigReport     1    0       1000        500        500          0 path_1
TrigReport     1    1       1000        333        667          0 path_2
TrigReport     1    2       1000        200        800          0 path_3
TrigReport     1    3       1000         33        967          0 path_all_explicit
TrigReport     1    4       1000        733        267          0 path_any_or
TrigReport     1    5       1000       1000          0          0 path_any_star
TrigReport     1    6       1000         33        967          0 path_1_pre
TrigReport     1    7       1000         33        967          0 path_2_pre
TrigReport     1    8       1000         99        901          0 path_any_pre
TrigReport     1    9       1000       1000          0          0 path_any_doublestar
TrigReport     1   10       1000        733        267          0 path_any_question
TrigReport     1   11       1000          0       1000          0 path_wrong_name
TrigReport     1   12       1000          0       1000          0 path_wrong_pattern
TrigReport     1   13       1000       1000          0          0 path_not_wrong_pattern
TrigReport     1   14       1000          0       1000          0 path_empty_pattern
TrigReport     1   15       1000          0       1000          0 path_l1path_pattern
TrigReport     1   16       1000          0       1000          0 path_l1singlemuopen_pattern
TrigReport     1   17       1000       1000          0          0 path_true_pattern
TrigReport     1   18       1000          0       1000          0 path_false_pattern
```

### CODE REVIEW

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
type bugfix

**Comment by Martin-Grunewald** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
