### PR TITLE
Update for L1 tracking algorithm (bug fixes)

### PR DESCRIPTION
**Pull request by skinnari**
This PR contains fixes for the L1 tracking for the HLT TDR:

(1) The update restores the expected pt resolution for high-pt particles (a bug had been introduced during the CMSSW integration). 
(2) It allows to run the displaced ("extended") version of the L1 tracking w/o having to be in a particular directory (using edm::fileInPath), to make sure it could run in central production.

### CODE REVIEW

**Comment by fwyzard** [comment]
@skinnari could you make a PR for CMSSW_11_2_X as well ?

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by skinnari** [comment]
> @skinnari could you make a PR for CMSSW_11_2_X as well ?

hi @fwyzard apologies, I missed the request to make a separate PR also to CMSSW_11_2_X. this is now available through PR #30245.

**Comment by fwyzard** [comment]
type bugfix

**Comment by fwyzard** [comment]
backport #30245

**Comment by silviodonato** [comment]
assign upgrade

**Comment by silviodonato** [comment]
urgent

**Comment by silviodonato** [comment]
@kpedro88 @rekovic I think can we merge this backport, can't we?

**Comment by kpedro88** [comment]
+upgrade

**Comment by silviodonato** [comment]
merge

**Pull request merged**
