### PR TITLE
Pixel Cluster Counting ALCARECO: separate content for random and zerobias

### PR DESCRIPTION
**Pull request by franzoni**
There are two trigger flavor of Pixel Cluster Counting ALCARECO:
+ on ZeroBias events
+ on Random events
Each ALCARECO flavor ought to store pixel counts only from the event type it cares about.
This PR specializes the output module of the PCC alcareco to do that
(to this point, the output configuration was inclusive and kept both ZB and Ran cunts for both ALCARECO)

original finding by @capalmer85 using replay data https://hypernews.cern.ch/HyperNews/CMS/get/tier0-Ops/1626/1/1/1/1/1/1/1.html
 
Local test carried out using the relval:
`runTheMatrix.py -l 1020 --command='-n 100000'`
with outcome (-Base stants for vanilla 9_2_1 ):
screen shot 2017-06-08 at 00 23 16

### CODE REVIEW

**Comment by franzoni** [comment]
please test

**Comment by franzoni** [comment]
@davidlange6 
based on the "Back porting.." thread, I would PR this change also to CMSSW_9_2_1_patchX, if it existed... What we have in production now is not buggy and is already useful to lumi. Yet, I'd deploy this PR, once vetted, asap to avoid standing data duplication.

**Comment by capalmer85** [comment]
@franzoni This is fine for me.

**Comment by franzoni** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
