### PR TITLE
Modify HG PCL Alignment movement histograms for use in the DQM GUI (Backport of #38815 ) 

### PR DESCRIPTION
**Pull request by mteroerd**
#### PR description:

This PR is in preparation of style changes for the movement histograms displayed in the DQM GUI. This includes the following changes:
- Fixing the order of labels in the status histogram to correctly match the variables
- Adding 5 Additional bins to each movement histogram. The first additional bin is empty, the other ones include cut values on movement threshold, significance, maximum error, and maximum movement. These can be read out in the DQM GUI.

#### PR validation:

Mille & Pede steps were execute to produce ROOT files usable by the DQM GUI. It was confirmed that the changes to the histograms are as intended.

Backport of #38815

### CODE REVIEW

**Comment by tvami** [comment]
backport of https://github.com/cms-sw/cmssw/pull/38815

**Comment by tvami** [comment]
type trk,bugfix

**Comment by tvami** [comment]
test parameters:

workflows = 1001.2, 1001.3

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
+alca
 * 1001.2, 1001.3 passed

**Comment by tvami** [comment]
urgent
 * should be part of next 12_4_X

**Comment by qliphy** [comment]
+1

**Pull request merged**
