### PR TITLE
Keeping the z ordering in the NavigationSchool sorting and fix analyzer

### PR DESCRIPTION
**Pull request by ebrondol**
- The sorting process need to keep the order in z otherwise the `if` condition afterwards can also not be satisfied as it should. The `stable_sort` has been also propagated to the other sorting processes.
- The bug in the analyzer was is caused by the PR #16993. Thanks to @makortel to spot the issue!

### CODE REVIEW

**Comment by VinInn** [comment]
@cmsbuild, please test

**Comment by slava77** [comment]
On 2/17/17 5:25 AM, ebrondol wrote:
>   * The sorting process need to keep the order in z otherwise the |if|
>     condition afterwards can also not be satisfied as it should. The
>     |stable_sort| has been also propagated to the other sorting processes.
>   * The bug in the analyzer was is caused by the PR #16993
>     <https://github.com/cms-sw/cmssw/pull/16993>. Thanks to @makortel
>     <https://github.com/makortel> to spot the issue!

is #16993 a correct PR for the reference?


Do we expect any changes in performance?
If so, please post MTV plots

**Comment by makortel** [comment]
@slava77 
> is #16993 a correct PR for the reference?

Yes. The signature of `beginRun()` was changed such that the function gets actually executed, and there `tTopo` was not initialized before use.

**Comment by ebrondol** [comment]
@slava77 no changes are expected.

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/17547	73f49c2
- technical change as described
- jenkins tests pass and comparisons with baseline show no difference

**Comment by davidlange6** [comment]
+1

**Pull request merged**
