### PR TITLE
Add 2D plots for the comparison between data and emulator for L1TObjects - L1T&Online DQM - cmssw101X

### PR DESCRIPTION
**Pull request by pgianneios**
This PR applies the changes that have been discussed in https://its.cern.ch/jira/browse/CMSLITDPG-166

It introduces a new boolean parameter enable2DComp in:
DQM/L1TMonitor/python/L1TStage2uGMT_cff.py
and
DQM/L1TMonitor/python/L1TdeStage2CaloLayer2_cfi.py

which can be set to True for drawing 2D eta-phi mismatch plots for the comparison of two collections of L1TOblects.

When enable2DComp=True in DQM/L1TMonitor/python/L1TStage2uGMT_cff.py then 2D plots will be produced for Muon Collections and when enable2DComp=True in DQM/L1TMonitor/python/L1TdeStage2CaloLayer2_cfi.py then 2D plots will be produced for Jet, EGs and Tau collections.

### CODE REVIEW

**Comment by pgianneios** [comment]
backport of #23434

**Comment by thomreis** [comment]
please test

**Comment by thomreis** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by jfernan2** [comment]
Successfully tested and integrated in the Online DQM at P5. https://twiki.cern.ch/twiki/bin/viewauth/CMS/DQMP5TagCollector
Merged in master

**Comment by fabiocos** [comment]
+1

validated in CMSSW_10_2_0_pre5

**Pull request merged**
