### PR TITLE
[12_4] Preserve electron mass after FastSim Bremsstrahlung emmision

### PR DESCRIPTION
**Pull request by srimanob**
#### PR description:
Carbon copy of https://github.com/cms-sw/cmssw/pull/42250

### CODE REVIEW

**Comment by srimanob** [comment]
@cmsbuild please test

**Comment by perrotta** [comment]
@cms-sw/pdmv-l2 can you please confirm that no FastSim production was ever started with 12_4_X?
In that case it is fine to integrate this without a modifier

**Comment by srimanob** [comment]
From
https://cms-pdmv.cern.ch/mcm/requests?member_of_campaign=Run3Summer22FSGenPremix&page=0&shown=551903297663
only 2 pilots and mixing. If need, we can restart the mixing again with the new release.

**Comment by sbein** [comment]
+1 thanks Phat

**Comment by perrotta** [comment]
backport of https://github.com/cms-sw/cmssw/pull/42250

**Comment by rappoccio** [comment]
please test

**Comment by perrotta** [comment]
please abort

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
@cms-sw/pdmv-l2 while tests are running, if you confirm that it is not an issue to redo the two pilots and the fastsim MinBias made for mixing in 12_4_X, and that there are no other already produced fastsim samples in 12_4_X involved, then this PR can get merged.

**Comment by sunilUIET** [comment]
@perrotta Currently we produced MinBias only and premix is running. There is no other sample produced with 12_4_X fastsim. It is fine for us to retrigger the PU production with fixes.

**Comment by perrotta** [comment]
+1
- FastSim output after Bremsstrahlung is (tinyly) modified. However FastSim was only produced in 12_4 for a few MinBias samples, that could even be remade if deemed necessary, see https://github.com/cms-sw/cmssw/pull/42451#issuecomment-1681936267

**Pull request merged**
