### PR TITLE
Added test for PSet description wildcard with plugin

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

- Changed the ParameterSetDescription unit test to use catch2.
- Added test for the combination of a wildcard node using a plugin node.

#### PR validation:

New tests passes.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
Please test

**Comment by makortel** [comment]
Comparisons show the usual
* https://github.com/cms-sw/cmssw/issues/39803
* https://github.com/cms-sw/cmssw/issues/43790

**Comment by makortel** [comment]
+core

**Comment by Dr15Jones** [comment]
@cms-sw/orp-l2 could we have this one merged as I have another PR to make which builds on this change.

**Comment by Dr15Jones** [comment]
@cms-sw/orp-l2 Please merge as this is holding up other development.

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
