### PR TITLE
Eras for TSG tests

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
Switch to Eras for TSG tests

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Comment by davidlt** [comment]
Shouldn't we do that for RelVals also?

I see the following in IB RelVal logs:
```

    #
    # -- Warning! You are using a deprecated customisation function. --
    #
    # It will probably run fine, but the customisations you are getting may be out of date.
    # You should update your configuration file by
    #   If using cmsDriver:
    #       1) remove the "--customise SLHCUpgradeSimulations/Configuration/postLS1Customs.customisePostLS1_50ns" option
    #       2) add the option "--era Run2_50ns"
    #   If using a pre-made configuration file:
    #       1) remove or comment out the "process = customisePostLS1_50ns(process)" line.
    #       2) add "from Configuration.StandardSequences.Eras import eras" to the TOP of the config file (above
    #          the process declaration).
    #       3) add "eras.Run2_50ns" as a parameter to the process object, e.g. "process = cms.Process('HLT',eras.Run2_50ns)"
    #
    # There is more information at https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideCmsDriverEras
    #
   
```

**Comment by Martin-Grunewald** [comment]
Yes -  I'd thought this was already done and I was just being late...

**Comment by davidlange6** [comment]
hum - we it was working for a moment (as few workflows aside)

**Comment by davidlt** [comment]
git gripping shows that deprecated stuff is used in various tests, documentations, etc.

What I see in RelVals comes from:
```
Configuration/PyReleaseValidation/python/relval_steps.py:861:                                    {'--customise': 'SLHCUpgradeSimulations/Configuration/postLS1CustomsPreMixing.customisePostLS1_50ns'},
```

I guess.

**Comment by davidlange6** [comment]
yes - that is one piece that is left..

**Pull request merged**
