### PR TITLE
Remove usedFallback argument from (pre|post)(Open|Close)File

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

After https://github.com/cms-sw/cmssw/pull/35505 the "useFallback" information is not available yet for `preOpenFile` signal, and delivering it via `postOpenFile` signal would be a bit cumbersome. Currently this boolean is used only by `Tracer` Service in `(pre|post)OpenFile`. The `Tracer` Service is the only user of the same boolean in `(pre|post)CloseFile`. We concluded that these printouts are not that useful (they don't affect framework's scheduling). This PR removes those printouts, and the boolean argument for the `(pre|post)(Open|Close)File` signals.

#### PR validation:

Code compiles.

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by fwyzard** [comment]
+heterogeneous

**Comment by makortel** [comment]
+core

**Comment by perrotta** [comment]
+1

**Pull request merged**
