### PR TITLE
 TopHLTMonitor: electronID WP changed to tight - Corrected btagalgo name 

### PR DESCRIPTION
**Pull request by skonstantinou**
The electronID WP changed from medium to tight. I also corrected the name of deepCSV b-tagging algorithm which is used in fully hadronic paths.

### CODE REVIEW

**Comment by andrius-k** [comment]
+1

**Comment by kpedro88** [comment]
please test

**Comment by fabiocos** [comment]
verified to pass Express test in Configuration/DataProcessing 

python RunExpressProcessing.py --scenario ppEra_Run2_2018 --fevt --dqmio --global-tag 102X_dataRun2_Express_v2 --lfn /store/t0streamer/Data/Express//000/321/879/run321879_ls0315_streamExpress_StorageManager.dat

on 1000 events

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
please test

the problem looks unrelated to this PR

**Comment by fabiocos** [comment]
@kpedro88  to me the question is why differences are seen in wf 9 and not in wf 25. @andrius-k @skonstantinou do you have an explanation for this?

**Comment by skonstantinou** [comment]
The changes in wf 9 affect HLT/SUSY plots and i think they come from https://github.com/cms-sw/cmssw/blob/master/DQMOffline/Trigger/python/SusyMonitor_cfi.py#L5
and https://github.com/cms-sw/cmssw/blob/master/DQMOffline/Trigger/python/susyHLTEleCaloJets_cff.py#L3

**Comment by fabiocos** [comment]
@skonstantinou sure, that we understand, but is this expected that this wf is affected, although not specific to 2018? And mostly why wf 25 is not, as it looks quite similar (apart for ALCARECO)?

**Comment by fabiocos** [comment]
+1

**Pull request merged**
