### PR TITLE
HLT V3.6 for development menus (101X)

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
HLT V3.5 for development menus (101X)
Does NOT touch production ("frozen") menus
Based on CMSSW_10_1_10.
Updated to V3.6

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
backport of #24512

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
eos access problems
let's try again!

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
