### PR TITLE
Avoid uninitialized data in DD4Hep HGCal geometry parameters

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

- initialized all data members in HGCalParameters as valgrind was complaining about an uninitialized value coming from the construction of the class.
- added sanity checks on values which we believe were probably associated with the uninitialized value.

This is an attempt to work on the occasional non-reproducibility seen in the phase 2 geometry when using dd4hep.

#### PR validation:

Code compiles.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by srimanob** [comment]
Thanks very much @Dr15Jones

**Comment by civanch** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

**Comment by srimanob** [comment]
Testing with 200 jobs (200 events each), all jobs run fine. No issue of https://github.com/cms-sw/cmssw/issues/41927 and https://github.com/cms-sw/cmssw/issues/41451 have been observed.

**Comment by bsunanda** [comment]
@Dr15Jones Thanks Chris. I should have looked into this

**Comment by bsunanda** [comment]
@antoniovilela, @rappoccio Please integrate it urgently

**Comment by bsunanda** [comment]
type Urgent

**Comment by rappoccio** [comment]
+1

**Pull request merged**
