### PR TITLE
Modernize GoodVetexFilter

### PR DESCRIPTION
**Pull request by Dr15Jones**
Added necessary consumes call, switched to getByToken and converted
to be a 'global' module.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
@slava77 This should fix the problem with GoodVertexFilter

**Comment by Dr15Jones** [comment]
please test

**Comment by slava77** [comment]
@davidlange6 in case you could merge that before -2300 build starts, it would be nice
.. a more likely case is -1100 though

**Comment by davidlange6** [comment]
+1

**Pull request merged**
