### PR TITLE
Alignment/TrackerAlignment change return type and remove unneeded class member.

### PR DESCRIPTION
**Pull request by gartung**
Change theTracker from a class member to a function temporary.
Change theTracker from a shared_ptr to a unique_ptr.
All instances of MisalignedTrackerESProducer in the config files
do not show them being changed after instantiation.

### CODE REVIEW

**Comment by gartung** [comment]
@Dr15Jones please review.

**Comment by Dr15Jones** [comment]
Looks good to me

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
Those workflows are failing in the IB.

**Comment by ghellwig** [comment]
please test

**Comment by ghellwig** [comment]
+1
provided jenkins agrees

**Comment by fabiocos** [comment]
+1

**Pull request merged**
