### PR TITLE
Run4-hgx282X Introduce ESGetToken in all classes in Validation/HGCalValidation/test

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Introduce ESGetToken in all classes in Validation/HGCalValidation/test

#### PR validation:

Tested using the workflows in the area Validation/HGCalValidation/test

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by jfernan2** [comment]
+1

**Comment by qliphy** [comment]
Comparison failures from DD4Hep as reported in https://github.com/cms-sw/cmssw/issues/33552

**Comment by qliphy** [comment]
+1

**Pull request merged**
