### PR TITLE
Update the Global tags for latest L1 uGT menu

### PR DESCRIPTION
**Pull request by mmusich**
# Summary of changes in Global Tags
## RunII simulation
- **RunII Ideal scenario** : [80X_mcRun2_design_v14](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_mcRun2_design_v14) as [80X_mcRun2_design_v13](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_mcRun2_design_v13) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/80X_mcRun2_design_v14/80X_mcRun2_design_v13): 
  - updated L1 uGT menu to v4 collisions 
  - updated JEC to Spring15_v1
- **RunII CRAFT scenario** : [80X_mcRun2cosmics_startup_peak_v13](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_mcRun2cosmics_startup_peak_v13) as [80X_mcRun2cosmics_startup_peak_v12](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_mcRun2cosmics_startup_peak_v12) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/80X_mcRun2cosmics_startup_peak_v13/80X_mcRun2cosmics_startup_peak_v12): 
  - updated L1 uGT menu to v4 collisions
- **RunII Asymptotic scenario** : [80X_mcRun2_asymptotic_v14](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_mcRun2_asymptotic_v14) as [80X_mcRun2_asymptotic_v13](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_mcRun2_asymptotic_v13) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/80X_mcRun2_asymptotic_v14/80X_mcRun2_asymptotic_v13): 
  - updated L1 uGT menu to v4 collisions
  - updated JEC to Spring15_v1
- **RunII Startup scenario** : [80X_mcRun2_startup_v14](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_mcRun2_startup_v14) as [80X_mcRun2_startup_v13](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_mcRun2_startup_v13) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/80X_mcRun2_startup_v14/80X_mcRun2_startup_v13): 
  -  updated L1 uGT menu to v4 collisions
## RunII data
- **RunII HLT relval processing** : [80X_dataRun2_HLT_relval_v11](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_dataRun2_HLT_relval_v11) as [80X_dataRun2_HLT_relval_v10](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_dataRun2_HLT_relval_v10) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/80X_dataRun2_HLT_relval_v11/80X_dataRun2_HLT_relval_v10): 
  - updated L1 uGT menu to v4 collisions
- **RunII Offline relval processing** : [80X_dataRun2_relval_v12](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_dataRun2_relval_v12) as [80X_dataRun2_relval_v11](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_dataRun2_relval_v11) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/80X_dataRun2_relval_v12/80X_dataRun2_relval_v11): 
  - updated L1 uGT menu to v4 collisions
  - fixed ES intercalibrations tag to account for refactoring of data/mc scale factor
## Upgrade
- **PhaseI realistic scenario** : [80X_upgrade2017_design_v6](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_upgrade2017_design_v6) as [80X_upgrade2017_design_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_upgrade2017_design_v4) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/80X_upgrade2017_design_v6/80X_upgrade2017_design_v4): 
  - updated L1 uGT menu to v4 collisions
- **PhaseI design scenario** : [80X_upgrade2017_design_v14](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_upgrade2017_design_v14) as [80X_upgrade2017_design_v12](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_upgrade2017_design_v12) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/80X_upgrade2017_design_v14/80X_upgrade2017_design_v12): 
  - updated L1 uGT menu to v4 collisions

### CODE REVIEW

**Comment by mmusich** [comment]
@Martin-Grunewald I am not running tests here since I believe this calls for an update of the HLT menu.
If you want to merge it in your tests please do:
```
git cms-addpkg Configuration/AlCa
git remote add mmusich https://github.com/mmusich/cmssw
git fetch mmusich
git cherry-pick 8a0d3a57133125f52f376edee0fd926d02d719f0
```

**Comment by Martin-Grunewald** [comment]
@mmusich
Thanks for making the GTs and this PR.
Added to our #14445

**Comment by davidlange6** [comment]
will merge with the HLT menu

**Comment by davidlange6** [comment]
@mmusich - but now I notice the JEC changes - these are already in the miniAOD production ongoing?

**Comment by mmusich** [comment]
@davidlange6 yes they are.

**Comment by davidlange6** [comment]
ok, so too bad the release doesn’t have what we are testing/using - but good to catch up

**Comment by mmusich** [comment]
@davidlange6 we had a special set of relvals with this set of JECs included to be tested.

**Comment by davidlange6** [comment]
sure - but lets also keep the release updated so that people can get the right answer for MC out of the box.

**Pull request closed without merging**
