### PR TITLE
10X HLTvalidation:moving HLTJETMET into JME/HLTJETMET

### PR DESCRIPTION
**Pull request by bobaekim**

### CODE REVIEW

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
hi @bobaekim - it looks like this change will break some related macros - please have a look and fix (or remove if obsolete)
https://cmssdt.cern.ch/lxr/search?%21v=CMSSW_10_0_X_2017-11-16-2300&_filestring=&_string=HLT%2FHLTJETMET

**Comment by davidlange6** [comment]
-1
pending requested changed

**Comment by fabiocos** [comment]
@bobaekim are the changes in this PR still needed? If yes pelase take and action concerning the required fix, otherwise please close it.

**Pull request closed without merging**
