### PR TITLE
Plot module residuals

### PR DESCRIPTION
**Pull request by tagay**
Added a function which plots x and y residuals for a specified module. This option is useful when one has to check a particular module which, for instance, moves very far during alignment. (In our case it moved more than by 1 mm)

Post on Hypernews:
https://hypernews.cern.ch/HyperNews/CMS/get/tif-alignment/702.html

### CODE REVIEW

**Comment by arunhep** [comment]
please test

**Comment by lpernie** [comment]
+1

**Comment by pohsun** [comment]
please test

**Comment by fabiocos** [comment]
@pohsun @tagay sorry, but in which test workflow is this code really probed? Apart for testing that it does not break anything else, I have the impression that these are standalone tools, am I correct?

**Comment by hroskes** [comment]
@fabiocos Yes, that's correct.  This is an addition to the tracker alignment validation package, which for the most part isn't really covered by the tests.  Is there a push now to make everything part of a test workflow?  Not that that's a bad idea, but it would be a ton of work.

**Comment by fabiocos** [comment]
please test

**Comment by lpernie** [comment]
+1

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
+1

**Pull request merged**
