### PR TITLE
Optional python parameters

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

Added the ability to declare parameters in PSets, EDProducers, etc without giving actual values to those parameters. The three types are
- `required`: if not set will throw a python exception during serialization to C++
- `optional` : if not set the parameter will not be serialized to C++
- `obsolete` : parameter is never serialzed to C++

This allows the following code
```python
p = cms.PSet( foo = cms.required.int32, bar = cms.optional.untracked.string)

p.foo = 12
p.bar = "stuff"
```

This facility is now used to define the standard top level PSets of `cms.Process` : options, maxEvents and maxLuminosityBlocks.

If more than one type is allowed for a given PSet label, one can use the `allowed` mechanism to specify the types:
```python
   p = cms.PSet( foo = cms.required.allowed(cms.int32, cms.string) )
```

To make it easier to modify multiple parameters within a PSet, one can now use a `dict` to modify a given set of parameters within a PSet:

```python
p.options = dict(numberOfThreads = 4, numberOfStreams = 2)
```

On the C++ side, the `fillDescriptions` system was updated to generate `cms.required` and `cms.optional` entries in the `_cfi.py` files.
#### PR validation:

All framework related tests pass.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by fwyzard** [comment]
> On the C++ side, the `fillDescriptions` system was updated to generate `cms.required` and `cms.optional` entries in the `_cfi.py` files.

What do the generated files look like ?
Do they use the new declarations only when the default values are not specified in the `fillDescriptions` ?

**Comment by Dr15Jones** [comment]
> Do they use the new declarations only when the default values are not specified in the fillDescriptions ?

Only used if no default given. Else they do exactly what we've done in the past.

>What do the generated files look like ?

```python
eventIDFilter = cms.EDFilter('ModuloEventIDFilter',
  modulo = cms.required.uint32,
  offset = cms.required.uint32,
  mightGet = cms.optional.untracked.vstring
)
```

where previously it was
```python
eventIDFilter = cms.EDFilter('ModuloEventIDFilter'
)
```
and the `PoolOutputModule` is now
```python
edmOutput = cms.OutputModule('PoolOutputModule',
  fileName = cms.required.untracked.string,
  logicalFileName = cms.untracked.string(''),
  catalog = cms.untracked.string(''),
  maxSize = cms.untracked.int32(2130706432),
  compressionLevel = cms.untracked.int32(9),
  compressionAlgorithm = cms.untracked.string('ZLIB'),
  basketSize = cms.untracked.int32(16384),
  eventAutoFlushCompressedSize = cms.untracked.int32(20971520),
  splitLevel = cms.untracked.int32(99),
  sortBaskets = cms.untracked.string('sortbasketsbyoffset'),
  treeMaxVirtualSize = cms.untracked.int32(-1),
  fastCloning = cms.untracked.bool(True),
  overrideInputFileSplitLevels = cms.untracked.bool(False),
  writeStatusFile = cms.untracked.bool(False),
  dropMetaData = cms.untracked.string(''),
  dataset = cms.untracked.PSet(),
  overrideBranchesSplitLevel = cms.untracked.VPSet(
  ),
  outputCommands = cms.untracked.vstring('keep *'),
  SelectEvents = cms.untracked.PSet(
    SelectEvents = cms.optional.vstring
  )
)
```

where `fileName` and `SelectEvents.SelectEvents` were added.

**Comment by makortel** [comment]
I wonder why cmsDriver now generates
```python
process.maxEvents = cms.untracked.PSet(
    input = cms.optional.untracked.int32,
    output = cms.optional.untracked..allowed(cms.int32,cms.PSet)
)
```
(`output` having extra dot leading to the failures)

and
```python
process.options = cms.untracked.PSet(
    FailPath = cms.untracked.vstring(),
    IgnoreCompletely = cms.untracked.vstring(),
    Rethrow = cms.untracked.vstring(),
    SkipEvent = cms.untracked.vstring(),
    allowUnscheduled = cms.obsolete.untracked.bool,
    canDeleteEarly = cms.untracked.vstring(),
    emptyRunLumiMode = cms.obsolete.untracked.string,
    fileMode = cms.untracked.string('FULLMERGE'),
    forceEventSetupCacheClearOnNewRun = cms.untracked.bool(False),
    makeTriggerResults = cms.obsolete.untracked.bool,
    numberOfConcurrentLuminosityBlocks = cms.untracked.uint32(1),
    numberOfConcurrentRuns = cms.untracked.uint32(1),
    numberOfStreams = cms.untracked.uint32(0),
    numberOfThreads = cms.untracked.uint32(1),
    printDependencies = cms.untracked.bool(False),
    sizeOfStackForThreadsInKB = cms.optional.untracked.uint32,
    throwIfIllegalParameter = cms.untracked.bool(True),
    wantSummary = cms.untracked.bool(False)
)
```

Maybe related to ConfigBuilder building both string and python object presentations of the config and somehow using pieces of the latter?

**Comment by Dr15Jones** [comment]
@makortel I've now extended the tests in FWCore.ParameterSet.Types to also test untracked.allowed. It now sees the problem. Working on a fix.

**Comment by Dr15Jones** [comment]
@makortel The dumpPython bug is now fixed.Thanks.

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
please abort test

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
The test failure is not from this pull request

**Comment by Dr15Jones** [comment]
+1

**Comment by fwyzard** [comment]
Hi @Dr15Jones,
thanks for the examples, I admit I like the new features a lot.

.A

**Comment by Dr15Jones** [comment]
please test

**Comment by makortel** [comment]
Just thinking out lout and ahead, I wonder what would be the impact for HLT ConfDB `cfi` file parsing?

**Comment by fwyzard** [comment]
I guess it will choke on the new cfi syntax, but it should be reasonably easy to fix once it happens.

**Comment by fwyzard** [comment]
@Martin-Grunewald FYI.

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/27191	2dda43d
- technical (for reco)
- jenkins tests pass

**Comment by Dr15Jones** [comment]
@fabiocos whom do I ping for the analysis signature?

**Comment by fabiocos** [comment]
@santocch please have a look

**Comment by fabiocos** [comment]
@Dr15Jones I have compared the expanded configurations for test workflows 136.85 (data) and 29034.0 (phase2 simulation) with and without this PR. The first obvious difference is in the ```process.options``` , as expected:

```
process.options = cms.untracked.PSet(                                           process.options = cms.untracked.PSet(
    FailPath = cms.untracked.vstring(),                                       |     canDeleteEarly = cms.untracked.vstring()
    IgnoreCompletely = cms.untracked.vstring(),                               <
    Rethrow = cms.untracked.vstring(),                                        <
    SkipEvent = cms.untracked.vstring(),                                      <
    allowUnscheduled = cms.obsolete.untracked.bool,                           <
    canDeleteEarly = cms.untracked.vstring(),                                 <
    emptyRunLumiMode = cms.obsolete.untracked.string,                         <
    fileMode = cms.untracked.string('FULLMERGE'),                             <
    forceEventSetupCacheClearOnNewRun = cms.untracked.bool(False),            <
    makeTriggerResults = cms.obsolete.untracked.bool,                         <
    numberOfConcurrentLuminosityBlocks = cms.untracked.uint32(1),             <
    numberOfConcurrentRuns = cms.untracked.uint32(1),                         <
    numberOfStreams = cms.untracked.uint32(0),                                <
    numberOfThreads = cms.untracked.uint32(1),                                <
    printDependencies = cms.untracked.bool(False),                            <
    sizeOfStackForThreadsInKB = cms.optional.untracked.uint32,                <
    throwIfIllegalParameter = cms.untracked.bool(True),                       <
    wantSummary = cms.untracked.bool(False)                                   <
)                                                                               )
```

and on max events, lumi blocks:

```
process.maxEvents = cms.untracked.PSet(                                         process.maxEvents = cms.untracked.PSet(
    input = cms.untracked.int32(10),                                          |     input = cms.untracked.int32(10)
    output = cms.optional.untracked.allowed(cms.int32,cms.PSet)               <
)                                                                             <
                                                                              <
process.maxLuminosityBlocks = cms.untracked.PSet(                             <
    input = cms.untracked.int32(-1)                                           <
)                                                                               )
```

For the rest, now many
```
    mightGet = cms.optional.untracked.vstring,
```

appears in the configuration, which I understand is a consequence of the ```optional ``` functionality and the update in https://cmssdt.cern.ch/lxr/source/Configuration/StandardSequences/python/earlyDeleteSettings_cff.py#0085

**Comment by Dr15Jones** [comment]
The mightGet are a consequence of the fillDescriptions injecting optionals. That parameter has always been  added automatically by the framework and is viewable using edmPluginHelp in all releases.

**Comment by fabiocos** [comment]
+operations

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

@santocch the PhysicsTools part looks ok to me, it basically update the definition of an assertEqual. Please check and comment in case for further updates

**Comment by santocch** [comment]
+1

**Comment by slava77** [comment]
@Dr15Jones 
is this feature documented in the twikis (someplace navigable from https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideFrameWork#Configuring_jobs ) ?
Please share a link.
Thank you.

**Comment by Dr15Jones** [comment]
@slava77 https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideAboutPythonConfigFile needs to be updated with the changes.

**Comment by Dr15Jones** [comment]
@slava77 I've updated the documentation on that page

**Comment by davidlange6** [comment]
hi @Dr15Jones - looks like this creates problems w/ python3

An exception of category 'ConfigFileReadError' occurred while
   [0] Processing the python configuration file named SingleElectronE120EHCAL_pythia8_cfi_GEN_SIM_DIGI_DIGI2RAW_RAW2DIGI_L1Reco_RECO_EI.py
Exception Message:
 unknown python problem occurred.
AttributeError: '_OptionalParameter' object has no attribute 'extend'

At:
  /cvmfs/cms-ib.cern.ch/nweek-02582/slc7_amd64_gcc700/cms/cmssw-patch/CMSSW_11_0_DEVEL_X_2019-06-27-2300/python/FWCore/ParameterSet/Types.py(56): __getattr__
  /cvmfs/cms-ib.cern.ch/nweek-02582/slc7_amd64_gcc700/cms/cmssw-patch/CMSSW_11_0_DEVEL_X_2019-06-27-2300/python/Configuration/StandardSequences/earlyDeleteSettings_cff.py(87): customiseEarlyDelete
  SingleElectronE120EHCAL_pythia8_cfi_GEN_SIM_DIGI_DIGI2RAW_RAW2DIGI_L1Reco_RECO_EI.py(163): <module>

[i'm not sure I understand the actual cause yet]

@smuzaffar

**Comment by Dr15Jones** [comment]
@davidlange6 I believe this is the underlying cause

https://stackoverflow.com/questions/1087135/boolean-value-of-objects-in-python/1087166#1087166

_OptionalParameter defines __nonzero__ which is used by python 2, but python 3 renamed the function to __bool__.

**Comment by Dr15Jones** [comment]
@davidlange6 fixed in #27399

**Comment by Martin-Grunewald** [comment]
@Dr15Jones @fabiocos 

Sorry but I need to come back to this as it seems the added functionality is incompatible with ConfDB.
In ConfDB, we store one fixed set of top-level plugin parameters for each plugin class. Each parameter needs an example value (even if it is a fake value) in cfi files used to parse this during ConfDB parsing of a new release.

I assume OBSOLETE parameters could simply be ignored and not recorded with the module during parsing, 

REQUIRED parameters should always have an accompanied default value emitted into the cfi file. As we know, parameters without a value do not get emitted (via fillDescriptions into cfi files) and hence ConfDB will not know about them (as it uses cfi files to discover them) and hence they are simply not available for module configs in HLT menus in ConfDB.

OPTIONAL parameters also seem completely unhandlebar in ConfDB parsing in case the C++ code 
checks the existence and then does different things depending on the existance of the parameter
(and what else would be the use case??)
This is because for ConfDB the number/type/list of parameters is fixed, so we can not allow
for varying number of parameters (at least for top-level parameters, varying sets of parameters are
allowed inside PSet parameters).

I am unclear how to proceed and what concrete problem is actually solved by this PR, thus whether it could be done differently and compatible with ConfDB parsing.

**Comment by fwyzard** [comment]
On Wed, 17 Jul 2019, 23:15 Martin Grunewald, <notifications@github.com>
wrote:

> @Dr15Jones <https://github.com/Dr15Jones> @fabiocos
> <https://github.com/fabiocos>
>
> Sorry but I need to come back to this as it seems the added functionality
> is incompatible with ConfDB.
> In ConfDB, we store one fixed set of top-level plugin parameters for each
> plugin class. Each parameter needs an example value (even if it is a fake
> value) in cfi files used to parse this during ConfDB parsing of a new
> release.
>
> I assume OBSOLETE parameters could simply be ignored and not recorded with
> the module during parsing,
>
> REQUIRED parameters should always have an accompanied default value
> emitted into the cfi file. As we know, parameters without a value do not
> get emitted (via fillDescriptions into cfi files) and hence ConfDB will not
> know about them (as it uses cfi files to discover them) and hence they are
> simply not available for module configs in HLT menus in ConfDB.
>
> OPTIONAL parameters also seem completely unhandlebar in ConfDB parsing in
> case the C++ code
> checks the existence and then does different things depending on the
> existance of the parameter
> (and what else would be the use case??)
> This is because for ConfDB the number/type/list of parameters is fixed, so
> we can not allow
> for varying number of parameters (at least for top-level parameters,
> varying sets of parameters are
> allowed inside PSet parameters).
>
> I am unclear how to proceed and what concrete problem is actually solved
> by this PR, thus whether it could be done differently and compatible with
> ConfDB parsing.
>

I guess it's finally time for ConfDB parsing to stop being based on the
generated python files, and move to something more robust.

For example, the parameter set validation code could outout a
machine-readable (e.g json ?) representation of the allowed rules and
values; a parser could read those a populate the database accordingly.

Of course this requires support in the parser, database, gui, and
extraction tool.

So, good news that we may have a dedicated developer again... bad news that
it will be only towards the end of the year.

.A

>

**Comment by Dr15Jones** [comment]
> Sorry but I need to come back to this as it seems the added functionality is incompatible with ConfDB. In ConfDB, we store one fixed set of top-level plugin parameters for each plugin class. Each parameter needs an example value (even if it is a fake value) in cfi files used to parse this during ConfDB parsing of a new release.

If all the parameters for all HLT used modules already have default values, then you will see no difference with this change. Also, hand written cfi files shouldn't contain any of these new types, just ones autogenerated by `fillDescriptions`.

> I assume OBSOLETE parameters could simply be ignored and not recorded with the module during parsing,

Yes. There is no facility to add_ obsolete_ parameters using fillDescriptions so they can only be used in handwritten configurations. Therefore no module descriptions are making use of this. It was only added to accomodate top level PSets used by the framework where we want to validate at python time but some parameters (like `options.runUnscheduled` ) no longer do anything but are still being used by the workflow management system.

> REQUIRED parameters should always have an accompanied default value emitted into the cfi file. As we know, parameters without a value do not get emitted (via fillDescriptions into cfi files) and hence ConfDB will not know about them (as it uses cfi files to discover them) and hence they are simply not available for module configs in HLT menus in ConfDB.

Now you have a way to discover if defaults were never given since a _required_ will appear in the python. You now have a way of checking which you didn't before.

> OPTIONAL parameters also seem completely unhandlebar in ConfDB parsing in case the C++ code
checks the existence and then does different things depending on the existance of the parameter
(and what else would be the use case??)
This is because for ConfDB the number/type/list of parameters is fixed, so we can not allow
for varying number of parameters (at least for top-level parameters, varying sets of parameters are
allowed inside PSet parameters).

Again, you can now discover cases where this is being done and report the problem to the developers. If ConfDB had not previously known about these parameter values it can just skip them since they were always optional and that is what ConfDB was doing before.

> I am unclear how to proceed and what concrete problem is actually solved by this PR, thus whether it could be done differently and compatible with ConfDB parsing.

If module writes already followed the HLT policy of having default values in the _fillDescriptions_, nothing changes. If they had not, now you can catch the problems.

This pull request did not change how developers make use of the ParameterSet system nor gave any new abilities in the C++. Developers have always been able to do _required_ and _optional_ parameters on the C++ side. What this pull request does is expose those on the python side in order to allow 
- more validation in python as well as 
- to function as documentation and 
- to make modifying parameters in the python easier since one doesn't have to specify the type

**Comment by Martin-Grunewald** [comment]
But I assume there is nothing to prevent someone from handwriting a cfi file with these new variants?
So ConfDB needs to deal with this when it encounters such.

Yes, we discover it, but how? How does a REQUIRED without value look in the cfi file? And if it is there it needs to be fixed, so why allow it in the first place if it creates problems later?

Also for OPTIONAL: we spend a long time educating HLT authors not to change physics on the presence or not of parameters, and now you put back an explicit accommodation for this, so 
people witll use it and then it needs to be fixed. Just do not allow it from the onset.

**Pull request merged**
