### PR TITLE
Run3-124D Try to remove compilation warnings in L1Trigger/L1THGCalUtilities

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Try to remove compilation warnings in L1Trigger/L1THGCalUtilities

#### PR validation:

Use the runTheMatrix test workflows

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cecilecaillol** [comment]
+l1

**Comment by srimanob** [comment]
+Upgrade

Technical PR, no change is expected.

**Comment by qliphy** [comment]
+1

**Pull request merged**
