### PR TITLE
RecoTracker test classes: fix clang warnings

### PR DESCRIPTION
**Pull request by gartung**
by changing function parameters to match base class functions.

### CODE REVIEW

**Comment by cvuosalo** [comment]
@gartung: Shouldn't all these overloaded functions get the `override` specifier?

**Comment by gartung** [comment]
@Dr15Jones test please

**Comment by Dr15Jones** [comment]
please test

**Comment by gartung** [comment]
Unrelated failure

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by gartung** [comment]
This is the failure which is unrelated to the test classes being change here as far as I can tell.

----- Begin Fatal Exception 13-Dec-2016 20:47:54 CET-----------------------
An exception of category 'PluginNotFound' occurred while
   [0] Constructing the EventProcessor
Exception Message:
Unable to find plugin 'Phase2TrackerClusterizer' in category 'CMS EDM Framework Module'. Please check spelling of name.
----- End Fatal Exception -------------------------------------------------

**Comment by Dr15Jones** [comment]
please test

**Comment by cvuosalo** [comment]
@gartung: Why aren't all the changed declarations given the `override` specifier?

**Comment by gartung** [comment]
uncommitted change

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
+1

For #16993 de64e952c3316bd0928ce5dfc3e59edfad20b7f7

For RecoTracker test files, fixing Clang warnings about overloading. There should be no change in standard workflows.

The code changes are satisfactory, and Jenkins tests against baseline CMSSW_9_0_X_2016-12-15-1100 show no significant differences, as expected.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
