### PR TITLE
Create Bs_JpsiPhi_V3.dec

### PR DESCRIPTION
**Pull request by heppye**
update BPH decay file.

### CODE REVIEW

**Comment by covarell** [comment]
An update of the file should not be added as "V3" but substitute the existing file (unless there is a reason to keep V1, V2, V3 alive at the same time...)

**Comment by heppye** [comment]
yes, the previous version should be kept. V3 is just for pythia8+evtGenInterface. v2 is for pythia6+evtGen, and V1 has a different angular distribution setting.

**Comment by covarell** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
