### PR TITLE
L1t hlt wseeds presc mask 80x

### PR DESCRIPTION
**Pull request by rekovic**
L1-HLT interface with seeding VETO  if algorithm bit is prescaled or masked.

This version uses the py example configuration work-around for upstream problems with Calo packer/unpacker sequence, pending fix.  Once the fix provided, the change is only in the example
configuration py files.

### CODE REVIEW

**Comment by mulhearn** [comment]
A masterpiece!

**Comment by mulhearn** [comment]
Just edit PR name to something like a newspaper article... since CMS uses these PR headlines in records.

**Comment by mulhearn** [comment]
+1

**Comment by mulhearn** [comment]
please test

**Comment by mulhearn** [comment]
The fix for upstream problems is #13339.  But we can leave this PR as is.

**Comment by fwyzard** [comment]
@davidlange6 is this still in time for 800 ?
in principle I would prefer to have this in for the MWGR, if possible.

**Comment by Martin-Grunewald** [comment]
+1

**Pull request merged**
