### PR TITLE
Rename candidate GTs to use official names and update alcareco trigger bits

### PR DESCRIPTION
**Pull request by christopheralanwest**
#### PR description:

PR #28762 was accidentally approved and merged prior to renaming the GTs to follow the usual convention for official GTs. The string "Candidate" indicates a test GT, which could cause confusion, so this PR simply renames the global tags. The GT diffs below demonstrate that there is no change to the tag content to any of the GTs.

https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/110X_mcRun2_asymptotic_preVFP_Candidate_2020_01_21_10_53_15/110X_mcRun2_asymptotic_preVFP_v4 
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/110X_mcRun2_asymptotic_Candidate_2020_01_21_10_51_32/110X_mcRun2_asymptotic_v7 
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/110X_mcRun2cosmics_startup_deco_Candidate_2020_01_21_10_58_30/110X_mcRun2cosmics_startup_deco_v6 
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/110X_dataRun2_2017_2018_Candidate_2020_01_17_14_50_24/110X_dataRun2_v10 
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/110X_dataRun2_relval_Candidate_2020_01_17_14_52_17/110X_dataRun2_relval_v10 
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_dataRun3_Prompt_Candidate_2020_01_19_15_27_07/106X_dataRun3_Prompt_v5 
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/110X_mc2017_design_Candidate_2020_01_17_14_56_45/110X_mc2017_design_v3 
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/110X_mc2017_realistic_Candidate_2020_01_17_14_54_08/110X_mc2017_realistic_v4 
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/110X_mc2017cosmics_realistic_deco_Candidate_2020_01_17_14_54_57/110X_mc2017cosmics_realistic_deco_v3 
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/110X_mc2017cosmics_realistic_peak_Candidate_2020_01_17_14_55_41/110X_mc2017cosmics_realistic_peak_v3 
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/110X_upgrade2018_design_Candidate_2020_01_17_14_58_40/110X_upgrade2018_design_v4 
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/110X_upgrade2018_realistic_Candidate_2020_01_17_14_59_48/110X_upgrade2018_realistic_v9 
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/110X_upgrade2018cosmics_realistic_deco_Candidate_2020_01_17_15_00_52/110X_upgrade2018cosmics_realistic_deco_v6 
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/110X_upgrade2018cosmics_realistic_peak_Candidate_2020_01_17_15_01_24/110X_upgrade2018cosmics_realistic_peak_v7 
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/110X_mcRun3_2021_design_Candidate_2020_01_17_15_02_07/110X_mcRun3_2021_design_v6 
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/110X_mcRun3_2021_realistic_Candidate_2020_01_17_15_02_54/110X_mcRun3_2021_realistic_v8 
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/110X_mcRun3_2021cosmics_realistic_deco_Candidate_2020_01_17_15_04_04/110X_mcRun3_2021cosmics_realistic_deco_v5  
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/110X_mcRun3_2023_realistic_Candidate_2020_01_17_15_05_07/110X_mcRun3_2023_realistic_v8  
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/110X_mcRun3_2024_realistic_Candidate_2020_01_17_15_06_09/110X_mcRun3_2024_realistic_v8  

#### PR validation:

A technical test was performed: `runTheMatrix.py -l limited,7.2,7.22 --ibeos`

#### if this PR is a backport please specify the original PR:

This PR is not a backport and should not be backported.

### CODE REVIEW

**Comment by christopheralanwest** [comment]
please test workflow 7.2,7.22

**Comment by mmusich** [comment]
@christopheralanwest thanks for this PR.
On a related topic, after #28762 was merged I noticed that wf 136.891 is starting to fail with message:
```
----- Begin Fatal Exception 28-Jan-2020 08:38:22 CET-----------------------
An exception of category 'Configuration' occurred while
   [0] Processing  Event run: 320822 lumi: 75 event: 126696592 stream: 1
   [1] Running path 'pathALCARECOSiPixelCalSingleMuon'
   [2] Calling method for module HLTHighLevel/'ALCARECOSiPixelCalSingleMuonHLTFilter'
Exception Message:
 HLTHighLevel [instance: ALCARECOSiPixelCalSingleMuonHLTFilter - path: pathALCARECOSiPixelCalSingleMuon]: No triggerList with key SiPixelCalSingleMuon in AlCaRecoTriggerBitsRcd
----- End Fatal Exception -------------------------------------------------
```
(see e.g. log [here](https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc7_amd64_gcc820/CMSSW_11_1_X_2020-01-27-2300/pyRelValMatrixLogs/run/136.891_RunSingleMu2018D+RunSingleMu2018D+HLTDR2_2018+RECODR2_2018reHLT_skimSingleMu_Prompt_Lumi+HARVEST2018_L1TMuDQM_Prompt/step3_RunSingleMu2018D+RunSingleMu2018D+HLTDR2_2018+RECODR2_2018reHLT_skimSingleMu_Prompt_Lumi+HARVEST2018_L1TMuDQM_Prompt.log)).
This means that the autoCond key `run2_data_promptlike` which is employed in that wf needs to be updated.  As you are touching autoCond here, would it be possible to include a fix for that?
Now as far as I can see the current Global Tag for that key uses the tag `AlCaRecoHLTpaths_2017_v5` which is different from the one used by the `run3_data_promptlike` key (i.e. `AlCaRecoHLTpaths8e29_5e33_v7_prompt`) which is also contained in the current Prompt Reco GT. I am wondering if this difference is intentional. If it is I can provide a new tag `AlCaRecoHLTpaths_2017_v6` with the new trigger keys, otherwise I would think it is advisable to align the two Global Tags to use the same tag.
Please let me know.
cc:
@silviodonato

**Comment by silviodonato** [comment]
please test workflow 136.891

**Comment by silviodonato** [comment]
please have a look at https://github.com/cms-sw/cmssw/pull/28762#issuecomment-579134600

**Comment by christopheralanwest** [comment]
please test workflow 136.891

**Comment by christopheralanwest** [comment]
+1

**Comment by silviodonato** [comment]
+1
thanks for the fix

**Comment by mmusich** [comment]
@christopheralanwest @silviodonato 
as far as I can this PR destroys more workflow than the previous situation: https://cms-sw.github.io/relvalLogDetail.html#slc7_amd64_gcc820;CMSSW_11_1_X_2020-01-29-1100
I think I understand why the prompt-like workflows had employed a different trigger bit selection. Certain alcas are run on demand and do not subsist on all the IOVs in Prompt Reco, while they are run over across the board in the IB tests.
I'll provide shortly a new tag `AlCaRecoHLTpaths_2017_v6` to be used instead.

**Comment by mmusich** [comment]
the new tag is available: https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/tags/AlCaRecoHLTpaths_2017_v6
Here is the diff w.r.t the previous tag:
image

**Pull request merged**
