### PR TITLE
[GCC 8][Alingment] Fix build error

### PR DESCRIPTION
**Pull request by mrodozov**
Fixes build errors listed here: https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc7_amd64_gcc810/CMSSW_10_2_X_2018-05-22-2300/Alignment/CommonAlignmentMonitor

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by smuzaffar** [comment]
@franzoni, @arunhep, @cerminar and @lpernie , can you please review this?

**Comment by lpernie** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
