### PR TITLE
Jets for 81x MiniAOD

### PR DESCRIPTION
**Pull request by rappoccio**
Here are the changes for Jets for 81x MiniAOD. The changes are: 
- We are "switching" from CHS to PUPPI in AK8 jets. Previously we stored CHS jets and matched PUPPI to those objects, storing values in user floats. Now we store PUPPI jets and store CHS values in user floats instead. 
- We dropped the CHS subjets, saving about 0.5% of the event size. 
- We added a single b-tagging discriminator to the subjets. 

Tests ran: runTheMatrix.py -l limited -i all -j 10, scram b runtests

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
Here are some plots to go with the changes, based on T1tttt with mglu= 1.5TeV mLSP=100 GeV; from RECO of RelVal 810pre9

jet raw PT is slightly lower

wft1tttt_ak8_ptrecogen_100to500
but response after correction is essentially the same 
wft1tttt_ak8_corrogen_b

Jet mass response is lower ... I didn't find a "corrected" mass plot
wft1tttt_ak8_ptrecogen_100to500

PLots with prunedMass, softdrop and tau\* are empty.
Unclear if DQM needs an update or the plots just migrated to different category
wft1tttt_ak8_prunedmass

wft1tttt_ak8_softdropmass
wft1tttt_ak8_tau2otau1


On the technical side:
- AK8CHS and upstream and downstream modules in PAT are gone (36 of them);
- AK8Puppi jets and related modules were added (27 total)
- event content doesn't have ``` patJets_slimmedJetsAK8PFCHSSoftDropPacked_SubJets ``` anymore (as expected), which is about 0.5%


Please check and confirm that the DQM plots behavior is OK. (I suspect something is missing)

**Comment by slava77** [comment]
@rappoccio @schoef @jdolen @ahinzmann 
Do you intend to make the same change for 2016 data rereco?
If so, a PR for 80X is needed.

**Comment by slava77** [comment]
I'm waiting for feedback on https://github.com/cms-sw/cmssw/pull/15437#issuecomment-240617750
before I can sign.

**Comment by ahinzmann** [comment]
we are not planning to backport to 80 (since 80 contains both CHS and PUPPI anyways already).
For the DQM plots @rappoccio will comment.

**Comment by rappoccio** [comment]
Hi, Folks,

Sorry for the delay, I was on holiday. 

We will indeed probably not backport to 80x unless there is a strong desire. About the DQM, indeed I did not change those, I will need to do that. Give me a few hours.

Cheers,
Sal

**Comment by slava77** [comment]
Hi Sal,

a few hours later there is no update yet.
Please clarify on the timeline.
It would be better to make the change in time for pre11 (a PR update today-ish with a chance to check/fix left)

**Comment by rappoccio** [comment]
Yes, sorry, I will try my best to get this done today.

**Comment by rappoccio** [comment]
OK, this should be good to go.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by dmitrijus** [comment]
+1

**Comment by slava77** [comment]
@rappoccio 
you mentioned yesterday that some fixes were still in line.
Please clarify if/when they are coming.

**Comment by slava77** [comment]
@rappoccio 
please leave a note to clarify that all changes from you are included
Thanks.

**Comment by rappoccio** [comment]
Right now! Found the problem. The plots are as follows:

[tau21.pdf](https://github.com/cms-sw/cmssw/files/439953/tau21.pdf)
[softdropmass.pdf](https://github.com/cms-sw/cmssw/files/439954/softdropmass.pdf)
[ptuncorr.pdf](https://github.com/cms-sw/cmssw/files/439955/ptuncorr.pdf)
[prunedmass.pdf](https://github.com/cms-sw/cmssw/files/439956/prunedmass.pdf)

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/15437 dc8a0bb
- changes since 2667ff2 are as expected, based on the SMS relval test:
    - reco quantities are unchanged
    - DQM plots are recovered: SoftDrop, Pruned, and tauX.over.tauY are now filled and appear to be in reasonable agreement
- jenkins tests pass

**Pull request merged**
