### PR TITLE
add two CSCTF plots for debugging MPC/TMB errors from CSC

### PR DESCRIPTION
**Pull request by rjwang**
add two CSCTF plots for debugging MPC/TMB errors from CSC

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1
provided it passes the tests

**Comment by deguio** [comment]
unfortunately this PR doesn't merge on top of #12505
please rebase on top of that branch

**Comment by rjwang** [comment]
Does that mean we have to remake a PR with the latest release?

**Comment by slava77** [comment]
#12505 isn't merged yet. It's not a matter of using the latest release. Two PRs (this and #12505 ) conflict with each other.

**Comment by rjwang** [comment]
Then, what should I do from my side? can I see where is the conflict, and we do need this PR to be merged asap in order to help CSC debug any problems in the trigger path.

**Comment by slava77** [comment]
@deguio is this PR ready to go to 75X?
it sounds like you may have a higher priority for #12505 (else the issue of merging conflicts in https://github.com/cms-sw/cmssw/pull/12470#issuecomment-158780684 doesn't seem clear).
Please clarify.
Thanks.

**Comment by deguio** [comment]
ciao @slava77 
I believe that this one can be merged and #12505 can be rebased on top on the head.

this is a warning for @jingyucms

**Comment by slava77** [comment]
merge

it's unclear when we make a new release though

**Comment by rjwang** [comment]
Thanks.

**Pull request merged**
