### PR TITLE
Run4-hgx279 Next step for V15 Geometry for HGCal

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Next step for V15 Geometry for HGCal - tested geometry access (fro Reco) using DDD/DD4Hep

#### PR validation:

Use the runTheMatrix test workflows 

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

**Comment by qliphy** [comment]
+1

**Pull request merged**
