### PR TITLE
Fix sigmaIetaIphi for photon regression (74X not patches)

### PR DESCRIPTION
**Pull request by lgray**
Sideport of #11403.

### CODE REVIEW

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/11405	93f9992
- bugfix to regression input variable for photon energy correction in miniAOD
- the effect is visible only in miniAOD (analysis level; no DQM available) and it is fairly small (see plots posted in #11403) 
- jenkins tests pass and comparisons with baseline show no differences

This should be merged in time for re-miniAOD.

**Comment by lgray** [comment]
@davidlange6 This also did not make it into 7_4_13 despite being in 7_4_12_patchX...

@gpetruc

**Comment by lgray** [comment]
Hmm, checking something...

**Comment by lgray** [comment]
@davidlange6 sorry, false alarm.

**Comment by lgray** [comment]
@davidlange6 @slava77 indeed, this one was simply not merged before. The only missing one is the fix to the electron classifier BDT calculation...

**Comment by lgray** [comment]
@gpetruc @davidlange6 Ready to go here, too.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
