### PR TITLE
Pr92x L1T development upto l1t integration v95.2 

### PR DESCRIPTION
**Pull request by rekovic**
92x PR of L1T development 

 - Contains developments between tag v94.0 and v95.2 from l1t-integration-CMSSW_9_2_0 integration branch.  Documented in detail in [twiki](https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideL1TOfflineDev#Status_of_Integration), most notably:
   - BMTF: improved eta assignment leading to 50% better resolution w.r.t. GEN
   - New uGMT extrapolation LUTs 20170505. These take the BMTF eta scale fix into account. This needs the external Muons data. (https://github.com/cms-data/L1Trigger-L1TMuon/pull/10)
   - EG - new extended H/E, plus 2nd isolation WP (aka 2016)
   - MET Emulator bug fix when getting address using ieta for MET PUS LUT. Emulator was counting from 0, firmware was counting from 1. 
   - Introduce a new caloParams2017_v1_7 to reflect current online conditions.
(https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideL1TOfflineDev#Status_of_Integration)
 - Number of files changed 58
    - 37 source code files 
    - 21 configuration python files, most not used by default, useful to developers 

Note:  there will be additional fixes in BMTF not provided yet, but that will come in a separate small PR.
Should review this one first.

### CODE REVIEW

**Comment by rekovic** [comment]
please test with cms-sw/cmsdist#3086

**Comment by rekovic** [comment]
@smuzaffar
I see cms-sw/cmsdist#3086 available.   
Not sure what is wrong with the above "please test" command.

**Comment by smuzaffar** [comment]
please test with cms-sw/cmsdist#3087

**Comment by smuzaffar** [comment]
please test with cms-sw/cmsdist#3087

**Comment by rekovic** [comment]
Separate this PR into:
- Muon-Only-PR (#19102)
- Calo-Only-PR (TBD)

**Comment by rekovic** [comment]
please test with cms-sw/cmsdist#3087

**Comment by davidlange6** [comment]
looks like this PR is obsolete

**Pull request closed without merging**
