### PR TITLE
added esConsumes to modules in SimMuon/DTDigitizer

### PR DESCRIPTION
**Pull request by JamminJones**
#### PR description:

added esConsumes to 2 modules

#### PR validation:

the code compiles

### CODE REVIEW

**Comment by Dr15Jones** [comment]
This change was done under my supervision.

**Comment by Dr15Jones** [comment]
please test

**Comment by civanch** [comment]
+1

in muons there are comparisons which are count as a difference but I see the total agreement bin to bin.

**Comment by silviodonato** [comment]
+1

**Pull request merged**
