### PR TITLE
fixing missing particle in filter - 93x

### PR DESCRIPTION
**Pull request by alberto-sanchez**
backport of  #22065

### CODE REVIEW

**Comment by perrozzi** [comment]
please test

**Comment by perrozzi** [comment]
+1

**Comment by fabiocos** [comment]
@perrozzi do we have a real validation of this filter somewhere?

PS: I see you definitely like TMath::Abs....

**Comment by perrozzi** [comment]
@alberto-sanchez should comment

**Comment by alberto-sanchez** [comment]
@perrozzi, @fabiocos : Yes that  was way we found the problem, after the filter we has having events where it has failing, digging that we found the cause. attach is a list of channels tested.

[genOnly_summary_number.pdf](https://github.com/cms-sw/cmssw/files/1685922/genOnly_summary_number.pdf)

 the problems in the BdToJpsiKstar sample are not related to this filter. The hard work has been made by Stephan Wiederkehr

**Comment by perrozzi** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
