### PR TITLE
 MET Filter update (port of #10604)

### PR DESCRIPTION
**Pull request by schoef**
Please see #10604

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/10608	c93b975
- code changes are as expected
- same code as in 74X  and in 76X version (74X was tested additionally with run2 prompt reco setup)
- jenkins tests passed and comparisons with the baseline show no relevant differences
    - jenkins comparisons there  show diffs in logErrors which are expected to change due to  changes in the running modules

**Comment by slava77** [comment]
@monntj, @mmusich @diguida 
Please check, your signatures are needed
Thank you

**Comment by mmusich** [comment]
+1
clean up of `ALCARECODtCalibHI` and `ALCARECODtCalib` configurations.
Already signed the 76X equivalent #10604

**Comment by slava77** [comment]
@monttj
please check if this PR is OK
Thanks

**Comment by monttj** [comment]
+1
same for AT

**Comment by davidlange6** [comment]
+1

**Pull request merged**
