### PR TITLE
Port of 2022 and 2023 L1T CaloParams testing files

### PR DESCRIPTION
**Pull request by aloeliger**
#### PR description:

In the ongoing L1T Offline Software effort to move away from maintaining a parallel fork of CMSSW for Phase 1 development we have been requested to migrate caloParams files used for testing of the L1T system to a central location for their broader usage by L1T developers. This should represent all 2022 and 2023 caloParams.

@bundocka let me know if this works for you. I am trying to port the minimum necessary calo params files. If additional are needed, let me know and I'll pull them over.

#### PR validation:

Simple port of existing test files from l1t offline fork. Is not involved in extant workflows.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

This PR is not a backport and is not expected to be backported for any reason.

### CODE REVIEW

**Comment by aloeliger** [comment]
@bundocka would you like me to port anything else?

**Comment by bundocka** [comment]
@aloeliger I think this is fine for now, thanks

**Comment by aloeliger** [comment]
Please test

**Comment by aloeliger** [comment]
+l1

**Comment by rappoccio** [comment]
+1

**Comment by aloeliger** [comment]
@bundocka Could you please check whether this is enough to unblock your PR for the HI stuff?

**Pull request merged**
