### PR TITLE
Fix HGCal aging

### PR DESCRIPTION
**Pull request by kpedro88**
I noticed several python problems when trying to run an aging configuration that included HGCal. (It seems that this has never been run in production.)

This PR will be backported to 93X.

### CODE REVIEW

**Comment by kpedro88** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Comment by rovere** [comment]
@kpedro88 @malgeri
Ciao Kevin,
thanks for taking a look at this. I know Malgeri has deeply investigated the same issue in the past days and he will likely have a more comprehensive PR covering more than this PR.
Do you agree to close this PR and its sibling one #21157 waiting for Luca's one middle next week??

**Comment by kpedro88** [comment]
@rovere these issues were preventing me from completing tests for HCAL. Since this PR is fairly simple, I think @malgeri shouldn't have too much trouble rebasing on top of it.

**Comment by davidlange6** [comment]
+1

**Comment by rovere** [comment]
@kpedro88 I guess it's simple enough to rebase on top of it, but I fear it's still treating the whole ageing for HGCAL the wrong way.
Anyway, let's go on and make the full, final PR on top of this.

**Comment by kpedro88** [comment]
@rovere this PR is just trying to get the existing code to run without python exceptions - the approach is a different matter

**Pull request merged**
