### PR TITLE
Pixel Geometry Fixes

### PR DESCRIPTION
**Pull request by schneiml**
These two commits should fix the Phase1 Pixel geometry issues reported in the Offline week diskussion.

The pixbar volumes touched here were not modified for a long time, and it is not clear why the subtraction was used there in the first place. It seems safe to remove it, but this should be checked again.

We attempted to compensate the material budget changes by adjusting the material densities accordingly, even though the change is probably within the tolerance of these numbers.

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by ianna** [comment]
@civanch and @davidlange6 - comparing with previous display the overlaps in Pixel are fixed.
with this PR:
screen shot 2016-11-09 at 16 45 02
screen shot 2016-11-09 at 16 40 59
before:
screenshot 2016-11-07 12 02 14
screenshot 2016-11-07 12 21 30

**Comment by davidlange6** [comment]
+1

**Pull request merged**
