### PR TITLE
Update smp validation paths (backport 9_2_X)

### PR DESCRIPTION
**Pull request by npostiau**
This PR is backport of PR #20344 .

@gpasztor (SMP trigger convener, for information)

Updated paths and histograms used by the HLT SMP validation (I am validator for HLT SMP):

- Monitoring of Single Electron triggers.
- Update of the paths monitored for Single Photon.

Changes have been tested by producing DQM files.

### CODE REVIEW

**Comment by mtosi** [comment]
@cmsbuild, please test

**Comment by mtosi** [comment]
@cmsbuild, please test

**Comment by mtosi** [comment]
if this PR is fine (which I think so)
could we proceed w/ the integration, please ?
it should affect only the VALIDATION sequence

**Comment by mtosi** [comment]
@davidlange6 @dmitrijus

**Comment by mtosi** [comment]
back-port #20344

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
please test
(to see that the differences in the test are not real)

**Comment by davidlange6** [comment]
merge

**Pull request merged**
