### PR TITLE
Cmssw mstr brn

### PR DESCRIPTION
**Pull request by gkaratha**
Dear @mtosi, 

I am doing the PR as you requested in the master branch instead of 9_3_X. The PR can not able to merge but this is not due to my code. In the 9_3_X can be merged and compile/run without problems. I did not change any line in the code and addressed the comments of @davidlange6 . I suppose that master branch is something else than 9_3_X because i see many changed files, while i only used 5.

### CODE REVIEW

**Comment by slava77** [comment]
-1

bad PR submission

**Comment by Martin-Grunewald** [comment]
-1

**Comment by kpedro88** [comment]
-1

**Comment by arunhep** [comment]
-1

**Comment by davidlange6** [comment]
Your PR is unmergeable. Please have a look and possibly rebase it.

**Pull request closed without merging**
