### PR TITLE
Remove unused code from HeterogeneousCore/AlpakaCore

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Remove unused code from `HeterogeneousCore/AlpakaCore`.

#### PR validation:

All packages build and unit tests pass.

### CODE REVIEW

**Comment by fwyzard** [comment]
+1

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
@makortel any objections to removing this ?

**Comment by fwyzard** [comment]
enable gpu

**Comment by makortel** [comment]
> @makortel any objections to removing this ?

I'm all for removing this unused piece that only creates confusion. Just for the record, the actually used logic for device selection is in
https://github.com/cms-sw/cmssw/blob/cea249650467c0724ea7dadb238cef942570c708/HeterogeneousCore/AlpakaCore/src/alpaka/chooseDevice.cc#L8-L9

**Comment by fwyzard** [comment]
+heterogeneous

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
