### PR TITLE
Dedicated timing plots for L1T objects - Online DQM & L1T

### PR DESCRIPTION
**Pull request by ghost**
My task in JIRA is : ([https://its.cern.ch/jira/browse/CMSLITDPG-165](https://its.cern.ch/jira/browse/CMSLITDPG-165))

First of all, I needed to make some changes in the code DQM/L1TMonitor/src/L1TStage2uGT.cc . (Of course, in the path : DQM/L1TMonitor/interface/L1TStage2uGT.h, we simply add the new histograms) These changes are mentioned to add some extra plots according to specific L1 Trigger bits (L1_FirstCollisionInTrain and L1_LastCollisionInTrain). So, after I initialize three plots, I used the last two trigger bits, as I mentioned, to fill them. The first plot which called first_bunch, selecting only the L1_FirstCollisionInTrain, is filled with all the algorithm trigger bits (y-axis) and BX (x-axis), the second plot which called last_bunch, selecting only the L1_LastCollisionInTrain, is filled with all the algorithm trigger bits (y-axis) and BX (x-axis), and the last plot called isolated_bunch is filled selecting simultaneously L1_FirstCollisionInTrain and L1_LastCollisionInTrain, is filled with all the algorithm trigger bits (y-axis) and BX (x-axis).

### CODE REVIEW

**Comment by dtsitson** [comment]
Backport of #20969

**Comment by thomreis** [comment]
@dmitrijus  can you launch the tests for this one too please?

**Comment by dmitrijus** [comment]
+1

**Comment by dmitrijus** [comment]
+1

**Comment by thomreis** [comment]
Hi @dtsitson 
Data taking with 92x has finished. This can be closed.

**Pull request closed without merging**
