### PR TITLE
Adding patch to check all particles that are to be decayed by EvtGen and...

### PR DESCRIPTION
**Pull request by inugent**
... decay them - redo the pythia8 decays that are request by pdgid to be decayed by EvtGen

### CODE REVIEW

**Comment by bendavid** [comment]
This should go in 75x at this point.

**Comment by bendavid** [comment]
In addition, rather than redoing the pythia8 decays (this sounds error prone!).  Shouldn't we be configuring pythia8 to not decay those particles requested to be decayed by evtgen?
(Rather than redoing the decays we could even have the evtgen interface crash in case this was not done correctly)

**Comment by inugent** [comment]
Hi Josh,
  I looked into this once before, the problem is how to get the pythia8 object used by EvtGen.... I can investigate this option.
Best regards,
Ian

**Comment by inugent** [comment]
Hmm..  going through my emails, I see the issue of pythia8 not handing the particles back to EvtGen was mentioned by the experts from Warwick. My solution is consistent with their recommendation. However, I am not sure if there is the question of running oscillations 2x.

**Comment by davidlange6** [comment]
gen developments needed in 75x (and eventually 71x), not 74x.

**Pull request closed without merging**
