### PR TITLE
MiniAOD reprocessing (74X, BTV): Removing CSV+SL and adding SL taggers to the default PAT jet configuration

### PR DESCRIPTION
**Pull request by ferencek**
Backport of #10157

This PR is part of preparations for possible MiniAOD reprocessing of the Spring15 MC and 50ns Run2012B Data in 74X. More info at the following links:
- https://hypernews.cern.ch/HyperNews/CMS/get/physics-validation/2445.html
- https://twiki.cern.ch/twiki/bin/view/CMS/MiniAODSpring15pass2#BTV

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by ferencek** [comment]
@monttj, can you please restart the tests

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by monttj** [comment]
+1

**Comment by davidlange6** [comment]
closing PRs included in #10649

**Pull request closed without merging**
