### PR TITLE
Simplify pixel typedefs

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Simplify typedefs and clean up comments in legacy modules.

Make type aliases more consistent in SoA modules: use consistently `OnHost` and `OnDevice` instead of `OnCPU` and `OnGPU`.

#### PR validation:

None.

### CODE REVIEW

**Comment by fwyzard** [comment]
@nothingface0 @AdrianoDee @borzari FYI

**Comment by mmusich** [comment]
before I trigger unwanted tests, is there any particular reason to hold on here?

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
no, it was just too early and before a coffee...

**Comment by mandrenguyen** [comment]
+reconstruction
No changes to comparisons.  Code cleanup.

**Comment by perrotta** [comment]
+1

**Pull request merged**
