### PR TITLE
bsunanda:Run2-hcx121 Backport bug fix for TestNumbering Scheme of HCAL

### PR DESCRIPTION
**Pull request by bsunanda**

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by ianna** [comment]
+1

**Comment by davidlange6** [comment]
hi @bsunanda - please clarify for me - does this change invalid also GEN-SIM produced in 900 or does it just affect later processing steps?

**Comment by davidlange6** [comment]
+1

**Pull request merged**
