### PR TITLE
Run3-176B Update the documentation in Configuration/Geometry/README.md for Run3 scenarios

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Update the documentation in Configuration/Geometry/README.md for Run3 scenarios

#### PR validation:

This is only correct the documentation of Run3 geometries

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
+geometry

**Comment by srimanob** [comment]
+Upgrade

Only readme file is updated.

**Comment by rappoccio** [comment]
+1

**Pull request merged**
