### PR TITLE
HCALDQM: Add quality test for LED misfires (10_3_X)

### PR DESCRIPTION
**Pull request by DryRun**
Adds a quality test for Hcal/DigiTask/LED/LEDEventCount (>=1 events in the histogram indicates that an LED misfired in physics data).

### CODE REVIEW

**Comment by andrius-k** [comment]
please test

**Comment by DryRun** [comment]
Looks like these are file read errors.

Failed to open file at URL root://p06636710k01172.cern.ch:1095//eos/cms/store/user/cmsbuild/store/data/Run2011A/Cosmics/RAW/v1/000/160/960/049F6443-8E53-E011-A943-003048F117EA.root?

**Comment by mrodozov** [comment]
please test

**Comment by andrius-k** [comment]
+1

**Comment by kpedro88** [comment]
please test
(to get a clean result)

**Comment by kpedro88** [comment]
+1

**Comment by abdoulline** [comment]
@DryRun 
David, is it needed for current Online 10_2_X release?

**Comment by DryRun** [comment]
Hi @abdoulline - yes, indeed! The PR for 10_2_X is https://github.com/cms-sw/cmssw/pull/24359.

**Comment by abdoulline** [comment]
ah... thanks you and sorry for overlooking it :(

**Pull request merged**
