### PR TITLE
Run3-sim139 Replace cout with G4cout in SimG4CMS/Muon

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Replace cout with G4cout in SimG4CMS/Muon

#### PR validation:

Use the runTheMatrix test workflows

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

it is timeout not related to this PR

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by perrotta** [comment]
+1

**Pull request merged**
