### PR TITLE
2018 HIon HLT menu (104X)

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
2018 HIon HLT menu (104X)
Based on CMSSW_10_3_0_pre6

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
abort test

**Comment by Martin-Grunewald** [comment]
please abort test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by Martin-Grunewald** [comment]
@Dr15Jones 
Please sign for core. Thanks!

**Comment by Dr15Jones** [comment]
+1

**Comment by fabiocos** [comment]
please test workflow 140.0,145.0

@Martin-Grunewald to address you doubts about the GT used in older relvals

**Comment by fabiocos** [comment]
@Martin-Grunewald looking at the 145 configuration, its runs but with plenty of L1-related error messages inside, so as we have discussed directly it does not crash but it gives meaningless results.
I will move the corresponding workflow to HLT:@fake in a forthcoming PR.

@lpernie @tocheng could you please add the L1Menu_CollisionsHeavyIons2018_v4_0_0-d1_xml to the relevant GTs ?

**Pull request merged**
