### PR TITLE
L1T online DQM - set efficiency flags - 92x

### PR DESCRIPTION
**Pull request by thomreis**
Set efficiency flag for L1T online DQM ratio plots to avoid them being normalized in the GUI.
Also fixes some copy and paste errors in the CaloLayer2DEClient.

This is a backport of #20935 but also includes the PRs #20206 and #20583, which are not in 9_2_x yet. The two additional PRs were merged to avoid conflicts when cherry-picking my three commits.

### CODE REVIEW

**Comment by thomreis** [comment]
backport of #20935

**Comment by rekovic** [comment]
please test

**Comment by rekovic** [comment]
+1

**Comment by dmitrijus** [comment]
+1

**Comment by thomreis** [comment]
Data taking with 92 releases is over.

**Pull request closed without merging**
