### PR TITLE
Clean up of HLTrigger/HLTanalyzers

### PR DESCRIPTION
**Pull request by silviodonato**
This PR removes a lot of obsolete code from HLTrigger/HLTanalyzers .
The remaining code has been synchronized with https://github.com/cms-steam .

cc: @ndaci @mtosi @georgia14

### CODE REVIEW

**Comment by silviodonato** [comment]
please test

**Comment by silviodonato** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
