### PR TITLE
Run3-gex60 Try to resolve overlap in preshower detector for dd4hep

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Try to resolve overlap in preshower detector for dd4hep 

#### PR validation:

Tested using overlap testing tool in SimG4Core/PrintGeomInfo/test/python

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
The results from the DD4hep workflow do change, but are the differences merely statistical fluctuations?

**Comment by cvuosalo** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
