### PR TITLE
Position calc fix

### PR DESCRIPTION
**Pull request by argiro**
Fix sporadic crash in clustering

### CODE REVIEW

**Comment by lgray** [comment]
@argiro can you do the following (to get rid of things from the patchX branch of 74):
```
git checkout PositionCalcFix
git fetch official-cmssw CMSSW_7_4_X:CMSSW_7_4_X
git rebase -i --onto CMSSW_7_4_X PositionCalcFix~1 PositionCalcFix
git push my-cmssw PositionCalcFix -f
```
Thanks!

**Comment by argiro** [comment]
I submitted (mistake) PRs for both CMSSW_7_4_12_patchX #11414 and CMSSW_7_4_X, should I just cancel the former ?

**Comment by davidlange6** [comment]
I think we need both - if one becomes irrelevant we will close it.

**Comment by argiro** [comment]
done (followed instructions below)

Stefano

**Comment by lgray** [comment]
@cmsbuild please test

@argiro Thanks!

**Comment by cvuosalo** [comment]
+1

For #11415 a0d2b3189997dd61ed89f54b11a3c03a278accbb

Fixing buggy code related to the ECAL 2D position that was causing sporadic crashes. There should be no change in monitored quantities.

The code change fixes incorrect code. Jenkins [tests](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-11415/8263/summary.html) against baseline CMSSW_7_4_X_2015-09-21-2300 show no significant differences, as expected.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
