### PR TITLE
Update on Top single lepton + jets paths

### PR DESCRIPTION
**Pull request by ebouvier**
This is the PR going with JIRA ticket CMSHLT-193 (https://its.cern.ch/jira/loginCern.jsp?permissionViolation=true&os_destination=%2Fbrowse%2FCMSHLT-193). Single lepton + jets paths are modified in the DQM and validation codes for the Top PAG.

### CODE REVIEW

**Comment by ebouvier** [comment]
Dear all,
This is the same crash of the Jenkins test as #7195. Besides, this PR is affecting only python config files.
Cheers,

Elvire

**Comment by ebouvier** [comment]
@cmsbuild 
Could you please re-launch the tests ? Thanks !

**Comment by nclopezo** [comment]
please test

**Comment by ebouvier** [comment]
Thanks a lot !

**Comment by deguio** [comment]
+1

**Pull request merged**
