### PR TITLE
[Phase2 3D Digitizer] Fix several bugs related with charge migration

### PR DESCRIPTION
**Pull request by duartej**
Some bug fixes related with the charge migration in the 3D digitizer. 

#### PR description:

Charge was not properly migrated between cells due to the combined effect of the bugs fixed at this commit:
- Maximum migrated charge could be large than the 1/2 of the initial charge.
- Collection points created with the recursive call of the drift function were not added to the final collection points.
- Some checks of the energy deposit position relative to the  pixel cell were erroneously calculated.

This PR **affects only the Phase-2 upgrade** related packages, and only the 2026D65 geometry (T23). It is expected in that geometry, a slightly increase of digis due to the recovery of the migrated charges. 

watchers: @claralasa, @emiglior , @skinnari 

#### PR validation:
 * Passed the `runTheMatrix.py -l limited -i all --ibeos` tests, not sure if they are relevant because I'm not sure if they were tested against 2026D65 geometry. 
 * Checked successfully with the 30210.0

#### if this PR is a backport please specify the original PR and why you need to backport that PR:
It is not (although we will like to backport to 11.2.X ... I suppose that I should open a new PR when this is merged?)

### CODE REVIEW

**Comment by kpedro88** [comment]
please apply code-format

**Comment by kpedro88** [comment]
test parameters
workflow = 30234.0

**Comment by kpedro88** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by srimanob** [comment]
@duartej 
Would you mind to post the histogram which the change is expected? So we have a complete ref for this PR. Thanks.

**Comment by duartej** [comment]
> @duartej
> Would you mind to post the histogram which the change is expected? So we have a complete ref for this PR. Thanks.

Sure, sorry not doing at the beginning. The attached plot is the digi occupancy of the Layer1 (red with the patch/black without it), and as expected you can check there are more digis per event (due to the fact that now the charge is actually migrating when near the pixel edges, so creating an extra digi apart from the one contain most of the charge): 

digi_ocupancy_1D_L1

**Comment by srimanob** [comment]
+Upgrade

Thanks.

**Pull request merged**
