### PR TITLE
mpiCudaGeneric is a program transfer data from a machine to another with GPU using MPI and CUDA.

### PR DESCRIPTION
**Pull request by AliinCern**
#### Program description:
In this program, we transfer data from one machine to GPU remotely in different approaches using MPI and CUDA.

#### Program Validation:
We have successfully compiled it with scram b runtests

#### Program Mechanism:
There are three approaches of transferring data, we call them parts:
Part 1: Transfer data from Root pageable memory to Host pageable memory using MPI, then allocate memory in GPU using 
            cudaMalloc. Finally, transfer data from Host pageable memory to GPU using cudaMemcpy.
Part 2: Transfer data from Root pageable memory to Host Pinned memory using MPI and cudaMallocHost, then allocate 
            memory in GPU using cudaMalloc. Finally, transfer data from Host Pinned memory to GPU using cudaMemcpy.
Part 3: Allocate memory in GPU using cudaMalloc, then transfer data from Root pageable memory to GPU memory 
            using MPI.

#### Program Measurements:
There are seven sections that we have measure time elapse:
1) Time preparation from Root To Host.
2) Time preparation from Host to GPU.
3) Time operation on GPU, measured by Root.
4) Time operation on GPU, measured by Host.
5) Time operation on GPU, measured by Device.
6) Time preparation from Host to Root.

#### Program command line options are:
[-np] number of processes or processors that you would like to run.
[-s] size of vectors that you would like to send, the type is float and there are two vectors.
[-t] number of repeating task on the Device(GPU) side.
[-a] number of repeating the part.
[-p] choice of what part to run in the program.
[-q] print Stander Deviation.
[-f] save the results into a file for each part.
[-h] for help.

### CODE REVIEW

**Comment by fwyzard** [comment]
@cmsbot, please test

**Comment by fwyzard** [comment]
@cmsbot, please test

**Comment by fwyzard** [comment]
+heterogeneous

**Comment by qliphy** [comment]
+1

**Pull request merged**
