### PR TITLE
Phase2-hgx359V Modify the testing code in HGCalCommonData & GeometryHGCal in view of changes made in the Configuration/Geometry area for Phase2 scenarios

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Modify the testing code in HGCalCommonData & GeometryHGCal because of changes made in the Configuration/Geometry area for Phase 2 scenarios. Backport of PRs #45787, #45788, #45789

#### PR validation:

Tested the scripts for V16, V17, V18 versions 

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport #45787 #45788 #45789

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

I would include this clean-up into 14_1_X - these tests may be used in this release in future for Phase-2 for a long time and they does not affect Run3

**Comment by bsunanda** [comment]
@srimanob Please approve this PR

**Comment by srimanob** [comment]
+Upgrade

**Comment by mandrenguyen** [comment]
backport of https://github.com/cms-sw/cmssw/pull/45787 https://github.com/cms-sw/cmssw/pull/45788 https://github.com/cms-sw/cmssw/pull/45789

**Comment by mandrenguyen** [comment]
+1

**Comment by mandrenguyen** [comment]
type hgcal

**Pull request merged**
