### PR TITLE
Cleanup: Remove Geometry/MTCCTrackerCommonData

### PR DESCRIPTION
**Pull request by vargasa**
#### PR description:

Remove `Geometry/MTCCTrackerCommonData` 

Announcement: https://hypernews.cern.ch/HyperNews/CMS/get/tracker-performance/2367.html

**Edit**:

Package was used long time ago (see below) and no longer used

Quoting @boudoul 
> MTCC... Magnet Test and Cosmic Challenge - 2006 - It reminds me the good old time :
> http://cds.cern.ch/record/1000413/files/CR2006_091.pdf
> http://cds.cern.ch/record/987868

### CODE REVIEW

**Comment by cvuosalo** [comment]
@vargasa In the PR description, please give the full name of MTCC and note that it was last used a long time ago, and it is obsolete and no longer used.

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by boudoul** [comment]
MTCC... Magnet Test  and Cosmic Challenge - 2006 - It reminds me the good old time : 
http://cds.cern.ch/record/1000413/files/CR2006_091.pdf
http://cds.cern.ch/record/987868
....
Thanks for the cleaning ! (and indeed a few words in the description would be good, thank you )

**Comment by cvuosalo** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
