### PR TITLE
[Backport] Switching HGCal electrons and photons to TICL-based reconstruction

### PR DESCRIPTION
**Pull request by SohamBhattacharya**
#### PR description:

This is a backport of PR https://github.com/cms-sw/cmssw/pull/31527.
The backport is required for the HLT-TDR studies.

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by slava77** [comment]
based on pre7, it looks like the master version of this PR was responsible for doubling of the miniAOD size and 15% increase in the AOD size in PU200.

**Comment by jpata** [comment]
yes, I confirm this size increase from this PR with my direct test, which took a bit longer to converge.

**Comment by SohamBhattacharya** [comment]
@slava77 @jpata Thank you for the size tests.
From our checks we have found that this has to do with the fact that the input collection ("particleFlowClusterHGCalFromMultiCl") to the superclustering module is not filtered, thereby creating a very large number of reco-electrons/photons.
The filter is switched off in this PR (and in its master) as TICL has to be tuned for 200 PU, w/o which the filter performs sub-optimally
Marco and Felice have already improved the tuning considerably, and this issue should be resolved with the next update to TICL (followed by another update to switch on the filter here).

**Comment by jpata** [comment]
assign upgrade

**Comment by jpata** [comment]
TSG-Upgrade: @fwyzard @trtomei 
Upgrade: @kpedro88 

- is the MINIAOD size increase fine for upgrade studies?
- what's your stance on the "no-change policy" here, the default behaviour does change, but perhaps that's desirable for the TDR studies

Thanks!

**Comment by trtomei** [comment]
As far as I know,

- The increase in miniAOD size is acceptable since, as far as I remember, the bulk of the size is really RAW and RECO.
- The default changing is indeed what we want for the TDR.

**Comment by kpedro88** [comment]
> From our checks we have found that this has to do with the fact that the input collection ("particleFlowClusterHGCalFromMultiCl") to the superclustering module is not filtered, thereby creating a very large number of reco-electrons and reco-photons.
> The filter is switched off in this PR (and in its master) as TICL has to be tuned for 200 PU, w/o which the filter performs sub-optimally
> Marco and Felice have already improved the tuning considerably, and this issue should be resolved with the next update to TICL (followed by another update to switch on the filter here).

Personally, I would propose to integrate the next TICL update (along with all the other TICL backports) all together, so the miniAOD file size stays reasonable.

**Comment by rovere** [comment]
> > From our checks we have found that this has to do with the fact that the input collection ("particleFlowClusterHGCalFromMultiCl") to the superclustering module is not filtered, thereby creating a very large number of reco-electrons and reco-photons.
> > The filter is switched off in this PR (and in its master) as TICL has to be tuned for 200 PU, w/o which the filter performs sub-optimally
> > Marco and Felice have already improved the tuning considerably, and this issue should be resolved with the next update to TICL (followed by another update to switch on the filter here).
> 
> Personally, I would propose to integrate the next TICL update (along with all the other TICL backports) altogether, so the miniAOD file size stays reasonable.

Ciao @kpedro88 I agree it would make sense to integrate everything and check, after that, if the possible increase in miniAOD file size is still there and manageable.
I would advise having the PR integrated separately since they logically pertain to completely different developments.
As soon as this PR is merged, I can keep on working on the candidate TICLv2 we already have and make the mandatory changes accordingly.
We will not cut any release and start production until all those ingredients are in and everyone is "reasonably" happy. I do not think an increase in miniAOD size at this point should stop this integration.

**Comment by jpata** [comment]
So the options are, as I see:
- make one big TICL update, including backports, fixes etc, that does not "break" 11_1_X file sizes
- proceed by iteratively fixing 11_1_X towards TDR goals, while not making any release/production until reco outputs and file sizes are under control

**Comment by rovere** [comment]
Thanks @jpata for the nice summary. I was somehow suggesting to follow your second approach.

**Comment by SohamBhattacharya** [comment]
@jpata Thank you for the summary.
I am partial towards the 2nd option -- it'll be easier to check the reconstruction and file sizes with the iterative fixes.

**Comment by jpata** [comment]
Right, I just wanted to list the options here to be clear. The first option seemed to be preferred by Kevin, while the second by Marco & Soham. I will update this thread after a chat with Slava.

**Comment by kpedro88** [comment]
I was under the impression from @rovere's email that he wanted to make one large PR to backport all of the TICL developments, which is why I suggested also including a file size fix. If there will already be several different PRs, the second option is fine with me.

**Comment by rovere** [comment]
Ciao @kpedro88 
the large PR will only take care of TICL-related developments, while miniAOD size will come from a proper filter applied when creating `pfclusters` from TICL-objects.
I'm all in favour of solution number 2.

**Comment by jpata** [comment]
OK, given the discussion, there is no problem from reco with this iterative approach.

Concerning the MINIAOD size issue @rovere et al, could you please update https://github.com/cms-sw/cmssw/issues/31817 with a time-line on when you can address this in master? Thanks!

**Comment by kpedro88** [comment]
backport of #31527

**Comment by kpedro88** [comment]
+upgrade

**Comment by jpata** [comment]
+reconstruction

- exact backport of #31527 (apart from missing test script dbs_discovery.py here which does not seem relevant) to 11_1_X
- will introduce AOD and MINIAOD size issue documented in https://github.com/cms-sw/cmssw/issues/31817 also in 11_1_X, but this will be followed up shortly by the HGCAL team:
  - [ ] @rovere @SohamBhattacharya please state the timeline of this fix in the issue above
- correspondingly and following the discussion at the ORP, no release or production of 11_1_X is expected until these issues are solved
- standard reco is not affected as expected, MWGR should not be affected

**Comment by qliphy** [comment]
+1

**Pull request merged**
