### PR TITLE
Use thread safe modules in DPGAnalysis/SiStripTools

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

Migrated all modules to thread-safe versions.

#### PR validation:

Code compiles and no more CMS_DEPRECATED warnings appear.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
@makortel FYI

**Comment by Dr15Jones** [comment]
ping @cms-sw/analysis-l2

**Comment by qliphy** [comment]
+1

**Comment by qliphy** [comment]
merge

**Pull request merged**
