### PR TITLE
Fixed indexing error in  EcalPulseSymmCovariance

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

The gcc build with `-O3 -g` gave in error on EcalPulseSymmCovariancesHandler saying it was writing off the end of the array held by EcalPulseSymmCovariance. The problem is the code which translated the matrix coordinates into the compacted array index was incorrect. This change provides a correct mapping.

#### PR validation:

The code compiles and the newly added unit test passes.

No attempt was made to see how the changed lookup might affect physics.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by ggovi** [comment]
+1

**Comment by yuanchao** [comment]
+1

* fixing EcalPulseSymmCovariance matrix mapping
* WF matrix tests and unit tests passed
* build warnings are not of the PR

**Comment by qliphy** [comment]
+1

**Pull request merged**
