### PR TITLE
HLT menu development for `14_0_X` (4/N) [`14_1_X`]

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

Development of HLT menus for CMSSW_14_0_X (branch CMSSW_14_1_X).
  * This is the PR for the master branch, which will then be backported down to 14_0_X (the latter is the release cycle currently used for Run-3 HLT-menu development).
  
This version of the GRun HLT menu corresponds to final list of updates to the "V1.0" menu for the 2024 pp data-taking period.

This update includes the integration of the following JIRA tickets:
- [CMSHLT-3092](https://its.cern.ch/jira/browse/CMSHLT-3092) [TSG] Completion of the offline "Special" table and lists of paths for individual special menus [14_0_X]
- [CMSHLT-3099](https://its.cern.ch/jira/browse/CMSHLT-3099) [BPH] Include L1 seed to Dimuon low pt Jpsi trigger
- [CMSHLT-3101](https://its.cern.ch/jira/browse/CMSHLT-3101) [Scouting] Storage of raw `AK4PFJets` in Scouting
- [CMSHLT-3103](https://its.cern.ch/jira/browse/CMSHLT-3103) [TSG] Undo GRun changes due to CMSHLT-2860 (`MinimumBias` PD, smart-PS of `HLT_ZeroBias` in `EventDisplay`)
- [CMSHLT-3104](https://its.cern.ch/jira/browse/CMSHLT-3104) [BTV] Migration of `MC_PFBTag` to `ParticleNet`
- [CMSHLT-3109](https://its.cern.ch/jira/browse/CMSHLT-3109) [ECAL/PF] Integrate `Alpaka` version of ECAL local reco and `PFRecHit`+`PFCluster` reco of `HBHE RecHits`

In addition, the following changes are included:
   * [5e266bd](https://github.com/cms-sw/cmssw/commit/5e266bd1202b7a612659ee81accab98cd103e03d) robustify `test_OnlineVsDevTablesConsistency`
   * [8e75dc3](https://github.com/cms-sw/cmssw/commit/8e75dc33175ba1c653971e2db4ab6654fbab7147) add `Special` subtable to `DEV` / `dev` `cmsDriver` tests
   * [5f19fd1](https://github.com/cms-sw/cmssw/commit/5f19fd13babd46829ba2f10731c21469688ee931) Introduce `2024v1.0` frozen menu and remove `2023v1.2` and related test machinery.
   * [ce8e531](https://github.com/cms-sw/cmssw/commit/ce8e5312d93a7386abed36f09ea0e5ed6ec71357) update `readme` in `HLTrigger/Configuration/scripts/utils` to CMSSW_14_0_0
   
#### PR validation:

TSG Integration tests

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Not a backport, but it will be backported to CMSSW_14_0_X.

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by antoniovilela** [comment]
+1
   - HLT dump.

**Comment by mmusich** [comment]
+hlt
   * changes in [TriggerResults](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_14_1_X_2024-03-14-2300+1c1724/61686/triggerResults) (found differences in 7 / 46 workflows) look compatible with the path versioning bump (due to the creation of the new online menu) and the updates in the GRun table from https://its.cern.ch/jira/browse/CMSHLT-3103.

**Comment by mmusich** [comment]
type hlt-integration

**Pull request merged**
