### PR TITLE
Forward port 75X

### PR DESCRIPTION
**Pull request by emiglior**
Clean-up of the MuScleFit code (studies on the muon momentum scale) for run2.
This is the forward port to CMSSW_7_5_X of the PR #8700 which entered in CMSSW_7_2_5.
RECO is not affected.
@maralxplus, @mabarrio This can be of interest for you as well

### CODE REVIEW

**Comment by emiglior** [comment]
@vadler @degano @monttj could you start the tests?

**Comment by monttj** [comment]
please test

**Comment by monttj** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
