### PR TITLE
TrackQuality configuration fix

### PR DESCRIPTION
**Pull request by ferencek**
Added missing 's' in the imported module path

### CODE REVIEW

**Comment by civanch** [comment]
+1

**Comment by civanch** [comment]
@ferencek , would you make the same PR  for 7_5_X also?

**Comment by ferencek** [comment]
@civanch Yes, I can. I wasn't sure if PRs will be forward ported automatically.

**Comment by ferencek** [comment]
@civanch I see that 7_4_X was merged into 7_5_X just a few hours ago and I assume this will continue happening so once this PR is merged, it should be automatically forward ported. However, if that does not happen for any reason, I will create a PR for the 7_5_X branch.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
