### PR TITLE
HCAL GPU-CPU Comparison for the Online DQM

### PR DESCRIPTION
**Pull request by lwang046**
#### PR description:

Adding a new DQM client to produce GPU-CPU comparison plots for online DQM, together with a small fix of 2D plot to show profiling instead of accumulating rechits.

#### PR validation:

Tested with dedicated input stream file, client test runs good, `energyDiffGPUCPU_depth_` shows desired mean value instead of summation value.

### CODE REVIEW

**Comment by pmandrik** [comment]
please test

**Comment by pmandrik** [comment]
Hi, we need a backport of this to CMSSW_12_3_X to test and add client at P5

**Comment by emanueleusai** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
