### PR TITLE
Update for keeping gen-level nuclear info in AOD

### PR DESCRIPTION
**Pull request by yetkinyilmaz**
This pull-request contains a fix in order to keep all nuclear information (npart, ncoll, reaction plane) when the HepMCProduct is dropped.

This should be considered as a bug-fix in 75X, the production of the "heavyIon" object has to be in the digi step in order to be usable for some large GEN-SIM samples already produced.

The implementation for CMSSW_8_0_X will be different, it will be added to the gen step, in a more elegant way.

### CODE REVIEW

**Comment by bendavid** [comment]
Are these changes already in 80x?

**Comment by yetkinyilmaz** [comment]
No, in 80X, there will be a different implementation.
For now, we had to implement this one alone urgently.

**Comment by fabozzi** [comment]
please test

**Comment by fabozzi** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by wmtan** [comment]
@yetkinyilmaz @davidlange6 @bendavid @fabozzi @civanch @Dr15Jones  It is easy to prove that this PR broke step2 of relvals 140.1 and 140.4 in CMSSW_7_5_X. So, what should be done about this?
A) Ignore the test failures and hope for the best
B) Revert this PR and redo it.
C) Debug and fix this without reverting this PR.
If the choice is B or C, it should be up to the HI developers to fix this.

**Comment by yetkinyilmaz** [comment]
Thanks for the warning Bill, and sorry for the trouble.
I vote for C, I know where the problem happens and I will try a fix now.

**Pull request merged**
