### PR TITLE
MTD Geometry: update DDD filtering for better memory performance

### PR DESCRIPTION
**Pull request by fabiocos**
#### PR description:

This PR addresses https://github.com/cms-sw/cmssw/issues/46512 , by:

- remove vetoing no more present volumes (since v2);
- separate namespace and name filtering, as suggested by @makortel, eliminating the double string creation if only namespace filtering is needed;
- use locally ```string_view``` for comparisons to reduce memory usage.

#### PR validation:

```Geometry/MTD*``` unit tests successfully run, producing geometry dumps consistent with the reference.

### CODE REVIEW

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
please test

**Comment by makortel** [comment]
From the logs of workflow 29634.0 step 3, the number of memory allocations goes down from [244090020](https://cmssdt.cern.ch/SDT/jenkins-artifacts/ib-baseline-tests/CMSSW_14_2_X_2024-10-28-1100/el8_amd64_gcc12/-GenuineIntel/matrix-results/29634.0_TTbar_14TeV+2026D110/step3_TTbar_14TeV+2026D110.log) to [232478470](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-c26682/42427/runTheMatrix-results/29634.0_TTbar_14TeV+2026D110/step3_TTbar_14TeV+2026D110.log), i.e. a reduction of 11.6 millions.

**Comment by fabiocos** [comment]
as far as I can see in my standalone unit test on cmsdev45, there is no obvious significant impact on the speed of execution, in any case the caching of the strings is preserved to prevent the previous performance problems, that were fixed one year ago.

**Comment by bsunanda** [comment]
+geometry

**Comment by fabiocos** [comment]
@smuzaffar are two days normal for a profiling request? As pointed out by @makortel the memory benefit seems anyway visible by the simple memory report in log files, so in case I could abort the test

**Comment by smuzaffar** [comment]
No @fabiocos , it is not normal. We had only one node to run IB and PR profiling jobs and there were many such jobs waiting for there turn. I now have add couple of more nodes to run profiling jobs

**Comment by smuzaffar** [comment]
please tests

I can not find any trace of previous profiling jobs in jenkins so lets retry the tests

**Comment by fabiocos** [comment]
input errors appear to be unrelated to this PR, the profiling seems to me inconclusive for the problem addressed by this PR.
@cms-sw/upgrade-l2 please check and comment or sign it

**Comment by fabiocos** [comment]
type performance-improvements

**Comment by civanch** [comment]
please test

**Comment by fabiocos** [comment]
please test with #46608

**Comment by Moanwar** [comment]
+Upgrade

**Comment by mandrenguyen** [comment]
ignore tests-rejected with ib-failure

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
