### PR TITLE
Backport: add HTXS Filter for Run2 UL 

### PR DESCRIPTION
**Pull request by harrypuuter**
#### PR description:

This PR is a backport of the HTXS filter to be able to reproduce STXS-filtered UL samples used in SM H->tautau analyses with Run 2 UL. The samples for the non-UL analysis were produced using CMSSW 10_2_X but this filter was not added to the 10_6_X release used for the UL production.

#### PR validation:

Basic tests have been run.

Backport of https://github.com/cms-sw/cmssw/pull/26891

### CODE REVIEW

**Comment by menglu21** [comment]
@cmsbuild please test

**Comment by menglu21** [comment]
+1

**Comment by perrotta** [comment]
@harrypuuter this is not a verbatim backport of https://github.com/cms-sw/cmssw/pull/26891, but rather of the same files as they are now in master. That's perfectly fine. But then, why not to put them in thr `plugin` folder, as they are in master?

**Comment by harrypuuter** [comment]
I did the implementation the same way as it is done in the backport for CMSSW 10_2_X, where the code was still located in interface / src (https://github.com/cms-sw/cmssw/pull/27036). Should it be changed to the master implementation or kept this way ?

**Comment by perrotta** [comment]
> I did the implementation the same way as it is done in the backport for CMSSW 10_2_X, where the code was still located in interface / src (#27036). Should it be changed to the master implementation or kept this way ?

You are already backporting the code as it is now in master, please put everything in the plugin area then

**Comment by rappoccio** [comment]
hold

* Placing explicit hold until the files are migrated to the plugin area.

**Comment by harrypuuter** [comment]
I moved the code to the plugins folder, as it is done on master

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
unhold

**Comment by perrotta** [comment]
@cms-sw/generators-l2 also based on your request, we plan to build a new release in the 10_6_X cycle soon: could you please review this PR, then, so that we can proceed with it?

**Comment by menglu21** [comment]
@cmsbuild please test

**Comment by menglu21** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
