### PR TITLE
L1T Seeded Cone jets update

### PR DESCRIPTION
**Pull request by thesps**
In the context of phase 2 L1T emulation, this PR:

- introduces the R=0.8 configuration for Seeded Cone jets (SC8)
- renames existing Seeded Cone jet collections to 'SC4' for consistency
- fixes some issues with bit-exact matching of the emulator wrt the firmware particularly for MHT
- makes the jets/sums pattern file writer more flexible for testing against the firmware with different configurations (configurable input collections of jets and sums)

For testing, this CMSSW emulator now matches the firmware tested on an L1T board at the level of 99.9% for jets and 95% for sums (100% on the scalar sum and 95% on the vector sum due a difference in libraries for the trigonometry [`std` math vs `hls` math]).

### CODE REVIEW

**Comment by epalencia** [comment]
Please test

**Comment by aloeliger** [comment]
@thesps the error on the build is complaining about an uninitialized variable:

```
L1Trigger/Phase2L1ParticleFlow/plugins/L1CTJetFileWriter.cc
/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_14_0_X_2023-11-14-1100/src/L1Trigger/Phase2L1ParticleFlow/plugins/L1CTJetFileWriter.cc:60:63: warning: field 'gapLengthOutput_' is uninitialized when used here [-Wuninitialized]
```

**Comment by epalencia** [comment]
Please test

**Comment by epalencia** [comment]
Please test

**Comment by aloeliger** [comment]
@epalencia I think I'm satisfied with this, we reviewed it in the L1 fork. Anything from your side?

**Comment by epalencia** [comment]
+l1

**Comment by epalencia** [comment]
ping @cms-sw/upgrade-l2

**Comment by srimanob** [comment]
@cmsbuild please test

Just to trigger the test after a month.

**Comment by subirsarkar** [comment]
+Upgrade

**Comment by rappoccio** [comment]
+1

**Pull request merged**
