### PR TITLE
HCAL DQM Updates

### PR DESCRIPTION
**Pull request by vkhristenko**
These are HCAL DQM Updates requested by Hcal Phase1, Hcal Operations, Hcal DPG

this PR is a copy of  #14742  +
1. Laser Monitoring and proper treatment of Laser/Event Types with uMNio
2. Make compliant with Phase 1 processing.
- Doesn't crash
- In general treatment of Detector/Electronics/TrigTower ids should not crash any of the offline applications, but however if such are found, the summary for the run will bad.
- Other small requests to add certain histograms
- Remove the RECO w/o time constraints for Online hcal2 Application \* Note, this is for Online!!! *

VK

### CODE REVIEW

**Comment by dmitrijus** [comment]
+1

**Comment by dmitrijus** [comment]
+1

**Comment by deguio** [comment]
Hi @davidlange6 
could we please have this one merged?
thanks,
F.

@dmitrijus

**Comment by davidlange6** [comment]
+1

**Comment by deguio** [comment]
thanks :)

**Pull request merged**
