### PR TITLE
HLT menu development for `13_0_X` (13/N) [`13_3_X`]

### PR DESCRIPTION
**Pull request by missirol**
#### PR description:

Development of HLT menus for `CMSSW_13_0_X`.

This is the PR for the `master` branch, which will then be backported down to `13_0_X` (the latter is the release cycle currently used for Run-3 HLT-menu development).

This update includes the integration of the following JIRA ticket.

 - [CMSHLT-2889](https://its.cern.ch/jira/browse/CMSHLT-2889): [TRK] add doublet-recovery tracks to EventContent of `HLTMonitor` stream

#### PR validation:

TSG tests.

#### If this PR is a backport, please specify the original PR and why you need to backport that PR. If this PR will be backported, please specify to which release cycle the backport is meant for:

`CMSSW_13_2_X`
`CMSSW_13_1_X`
`CMSSW_13_0_X`

### CODE REVIEW

**Comment by missirol** [comment]
enable gpu

**Comment by missirol** [comment]
test parameters:
  - enable = gpu
  - workflows = 141.041, 141.042, 141.046

**Comment by missirol** [comment]
please test

**Comment by missirol** [comment]
+hlt

DQM differences are in line with the EventContent update described in [CMSHLT-2889](https://its.cern.ch/jira/browse/CMSHLT-2889).

**Comment by perrotta** [comment]
+1

**Comment by perrotta** [comment]
ping bot

**Comment by slava77** [comment]
type tracking

**Pull request merged**
