### PR TITLE
Add built tracks back to trackingOnly MultiTrackValidator

### PR DESCRIPTION
**Pull request by makortel**
This PR adds back the built tracks MTV instance that was accidentally removed from trackingOnly sequence in #19582.

Tested in 9_3_0_pre2, no changes expected in standard workflows.

@rovere @VinInn @ebrondol

### CODE REVIEW

**Comment by makortel** [comment]
type bug-fix

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
