### PR TITLE
[Phase-2 L1T 14_0_X] small fixes for RCT cluster emulation

### PR DESCRIPTION
**Pull request by pallabidas**
#### PR description:

Small changes to correctly use ECAL LSB = 0.5 in firmware based code. A fix in RCT cluster stitching function and shower shape flag is implemented.

#### PR validation:

Passes local validation checks with efficiency and rate plots, to be presented in a DP note.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Original PR: https://github.com/cms-sw/cmssw/pull/43950
We need the backport for 14_0_X

### CODE REVIEW

**Comment by epalencia** [comment]
Please test

**Comment by srimanob** [comment]
+Upgrade

**Comment by srimanob** [comment]
type backport

**Comment by aloeliger** [comment]
Backport of https://github.com/cms-sw/cmssw/pull/43950

**Comment by aloeliger** [comment]
+l1

**Comment by rappoccio** [comment]
+1

**Pull request merged**
