### PR TITLE
DAQ file broker client (10_2_X)

### PR DESCRIPTION
**Pull request by smorovic**
Backport of #23944 (10_3_X)
Client implementation for new DAQ File Broker protocol

### CODE REVIEW

**Comment by mommsen** [comment]
+1

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/23947	09f835c
- the backport is correct (comparing to https://github.com/cms-sw/cmssw/pull/23944	4c7f2cd : only some of the removed code in EventFilter/Utilities/src/FedRawDataInputSource.cc differs by ```const&``` in two catch arguments). The code changes are not really related to reco and do not affect the standard workflows tested offline.
- jenkins tests pass

**Comment by slava77** [comment]
backport of #23944

**Comment by smorovic** [comment]
Hi @slava77,
code which got rmoved from FedRawDataInputSource.cc ended in EvFDaqDirector.cc with modifications. There I converted all exceptions to const&.

**Comment by kpedro88** [comment]
+1

**Pull request merged**
