### PR TITLE
Fix `PixelCountFilter` and introduce `PixelOccupancyFilter`

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

In [CMSHLT-2928](https://its.cern.ch/jira/browse/CMSHLT-2928), it became clear that the module `PixelCountFilter`  used in the first online 2023 HIon menu (a.k.a `v1.0`), in which there are 4 filters of this type, is "bugged" (it technically works, but it does not produce the intended results), see for more details this [post](https://its.cern.ch/jira/browse/CMSHLT-2928?focusedId=4944093&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-4944093). 
The issue is that the `PixelCountFilter` plugin effectively cuts on the number of `DetSet`s (or, detector modules) with pixel clusters, while the intention was to apply a cut on the total number of pixel clusters. One solution (proposed by HIN PAG in [CMSHLT-2922](https://its.cern.ch/jira/browse/CMSHLT-2922)) is to use a different type of plugin ([HLTPixelActivityFilter](https://github.com/cms-sw/cmssw/blob/CMSSW_13_2_4/HLTrigger/special/plugins/HLTPixelActivityFilter.cc)), which is what is going to be implemented for the data-taking.
This PR proposes to fix the module `PixelCountFilter` by introducing the machinery in `CommonTools/Utils{Algos}` in order to count (and cut) on the total number of entries in a `DetSetVector`. This is implemented in c8b39085aad17dcb18d56d51ca29514253be245b.
In parallel a new filter `PixelOccupancyFilter` is introduced, which allows to filter events if at least N pixel modules have M clusters, where A <=  M <= B (N, A and B are configuration parameters). This is implemented in c8b39085aad17dcb18d56d51ca29514253be245b.

#### PR validation:

`cmssw` compiles. Private tests were carried out with this commit https://github.com/mmusich/cmssw/commit/9d74d21abec5d7d4535273345f84ade1fd02ba3b at to test that the newly introduced filters work as expected

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Not a backport, but it might be backported to 13.2.X

### CODE REVIEW

**Comment by mandrenguyen** [comment]
please test

**Comment by mandrenguyen** [comment]
+1
No change to reco comparisons, as expected.
Can be validated as part of the HLT menu, as intended only for online use.

**Comment by mmusich** [comment]
@cms-sw/pdmv-l2 please take a look.

**Comment by rappoccio** [comment]
+1

**Pull request merged**
