### PR TITLE
Revive of reverted #37852 with a fix on the issue #38044

### PR DESCRIPTION
**Pull request by quark2**
#### PR description:
This PR revives PR #37852 which is reverted because of issue #38044. The issue has been fixed, replacing part of calculations with a massive loop by lighter codes.

Also, this PR contains a backport of #37995 which fixes issue #37906.

Since the issue happened on CMSSW_12_3_X, a PR to this branch is provided first.

#### PR validation:
Test are done and one can check again by `runTheMatrix` workflows

@jshlee @watson-ij

### CODE REVIEW

**Comment by perrotta** [comment]
please @quark2 submit the fix to the master first.
Once merged there, and fully tested, we can backport the fix alone to 12_4_X, and the whole PR to 12_3_X

**Comment by quark2** [comment]
Hi @perrotta, 

Okay, I had no idea about the correct order to make PRs. I'll make the PR soon.

**Comment by emanueleusai** [comment]
please test

**Comment by emanueleusai** [comment]
+1

**Comment by emanueleusai** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by qliphy** [comment]
@quark2  Please update in this backport PR similarly as done in https://github.com/cms-sw/cmssw/pull/38101/commits/dad56f5a17ca3199aaa3df0a5e646348e88d2cc1

**Comment by civanch** [comment]
+1

**Comment by emanueleusai** [comment]
testing at P5

**Comment by qliphy** [comment]
> testing at P5

@emanueleusai  Any news on the P5 test?  Thanks.

**Comment by emanueleusai** [comment]
tests completed successfully. Processing time is similar to what we observed before.

**Comment by emanueleusai** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
