### PR TITLE
Extend GenParticlePruner

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

- added sumGluonsWithSameChildren option to better compact gluons
- added fillDescriptions
- minor code improvements

#### PR validation:

Code compiles. Ran on workflow 1302.181 (Pythia 8 TTbar) substituting the storage of the full GenParticles container with one using 
```
process.genParticles = cms.EDProducer("GenParticlePruner",
                                      src = cms.InputTag("fullGenParticles"),
                                      sumGluonsWithSameChildren = cms.bool(True),
                                      select = cms.vstring("keep *",
                                                           "drop  status > 30 && status < 70"
                                      ))
```

This ran fine and generated a GenParticle list which was 58% the size of the full list to store on the file which resulted in an over all AOD file being 10% smaller.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
The addition of `sumGluonsWithSameChildren` allows the following string of gluons

```
  390 |    15 -       tau- |  2 |  369  369  796  798 |  1  3 | 163.747      0.572 -1.459 |     18.289   -162.723     98.832    1.777 |
  391 |   -16 -  nu_taubar |  1 |  369  369   -1   -1 |  1  0 |  28.546     -0.386 -0.856 |     18.705    -21.564    -11.292    0.000 |
  392 |    21 -          g | 73 |  281  293  421  421 |  2  1 |   0.956     -0.832  0.242 |      0.928      0.229     -0.891    0.306 |
  393 |    21 -          g | 73 |  330  338  603  603 |  2  1 |   1.520     -2.767  2.600 |     -1.302      0.783    -12.048    0.041 |
  394 |    21 -          g | 73 |  334  340  606  606 |  2  1 |   0.824      0.502  2.713 |     -0.750      0.342      0.431    0.210 |
  395 |    21 -          g | 73 |  332  339  602  602 |  2  1 |   2.194     -4.600 -2.749 |     -2.027     -0.839   -109.184    0.487 |
  396 |    21 -          g | 73 |  323  326  592  592 |  2  1 |   3.534      1.884  2.244 |     -2.203      2.763     11.357    0.563 |
  397 |    21 -          g | 73 |  322  336  537  537 |  2  1 |   3.974      2.717 -1.483 |      0.347     -3.959     29.960    0.483 |
  398 |     2 -          u | 73 |  278  297  444  444 |  2  1 |   3.631      3.328 -1.206 |      1.294     -3.393     50.576    0.410 |
  399 |    21 -          g | 73 |  381  385  471  471 |  2  1 |   1.654      0.331  1.060 |      0.808      1.443      0.558    0.559 |
  400 |     2 -          u | 71 |  350  350  402  403 |  1  2 |   1.037     -7.471 -2.787 |     -0.972     -0.360   -910.278    0.330 |
  401 |  2103 -       ud_1 | 71 |  361  361  402  403 |  1  2 |   0.546     -9.178  1.936 |     -0.195      0.510  -2643.611    0.771 |
```

to be reduced to the following
```
   11 |    15 -       tau- |  2 |    7    7  351  353 |  1  3 | 163.747      0.572 -1.459 |     18.289   -162.723     98.832    1.777 |
   12 |   -16 -  nu_taubar |  1 |    7    7   -1   -1 |  1  0 |  28.546     -0.386 -0.856 |     18.705    -21.564    -11.292    0.000 |
   13 |    21 -          g | 73 |    1    1   -1   -1 |  1  0 |   0.956     -0.832  0.242 |      0.928      0.229     -0.891    0.306 |
   14 |     2 -          u | 73 |    0    0   51   51 |  1  1 |   3.631      3.328 -1.206 |      1.294     -3.393     50.576    0.410 |
   15 |     2 -          u | 71 |    0    1   17   18 |  2  2 |   1.037     -7.471 -2.787 |     -0.972     -0.360   -910.278    0.330 |
   16 |  2103 -       ud_1 | 71 |    1    1   17   18 |  1  2 |   0.546     -9.178  1.936 |     -0.195      0.510  -2643.611    0.771 |
```

(this is actually a very small string of gluons, most are much larger groupings than this).

**Comment by Dr15Jones** [comment]
assign generators

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
@smrenna FYI

**Comment by mseidel42** [comment]
Hi Chris,

* In your example https://github.com/cms-sw/cmssw/pull/39133#issuecomment-1222394814 it looks like you would sum gluons from very different eta/phi regions. I am not sure this can be right, hopefully Steve can comment on that.
* But then it looks like just the first one is kept and the others are thrown away?

Best,
Markus

**Comment by SiewYan** [comment]
ping @smrenna

**Comment by perrotta** [comment]
@Dr15Jones @smrenna @cms-sw/generators-l2 : is there any intention to proceed with this PR, stuck since more than five months already. or should we close it, instead?

**Comment by Saptaparna** [comment]
We need to perform validation for this PR. We should discuss this with xpog and find out if analysts can test and tell us if anything crucial would be missing if this PR is merged.

**Comment by Saptaparna** [comment]
@mseidel42 : do you have any further comments on this? Are there other people who might be interested in this pruning?

**Comment by mseidel42** [comment]
Hi all, I think it's important to understand what we are actually doing here, so let me repeat my questions from above:

* In your example https://github.com/cms-sw/cmssw/pull/39133#issuecomment-1222394814 it looks like you would sum gluons from very different eta/phi regions. I am not sure this can be right, hopefully Steve can comment on that.
* But then it looks like just the first one is kept and the others are thrown away?

According to the [Pythia manual](https://pythia.org/latest-manual/Welcome.html) these gluons should be
> 71 - 79 : partons in preparation of hadronization process
    71 : copied partons to collect into contiguous colour singlet

So it looks like they are unrelated gluons collected by color combination before the string fragmentation does its job (and creates 26 hadrons in the example above?).
Merging them does not make physical sense to me, and it might be better to delete them altogether once we make sure that they are not needed.

--> I suggest that partonFlavour should be checked on a large enough sample, to make sure none of these gluons were important in jet flavor association.

**Comment by mseidel42** [comment]
Let me tag @bendavid to comment as well

**Comment by bendavid** [comment]
I commented elsewhere that I think this is a terrible idea to do in CMSSW.  If we want more compact event representations from the generators then this is a feature we should request from the generators where it can be done properly and with full awareness of the internal details.

**Comment by smrenna** [comment]
My last comment about this, from 8/18/22, ends on a note of skepticism.
It was unclear to me who requested this, and what was the physic case.

I see there are two sides to this issue:
I am told that the event history is the largest contributor to the AOD format. I wonder how much
of this is used regularly?    Much of that history is the parton shower and multiparton interactions
(those are identified by the status values in the 30s, 40s, and 50s).
All of that information is saved because we might want to use it to repurpose an event (by making probability changes based on the parton level information).   However, it is only used rarely, if at all.
In principle, all of that information depends upon a single random number seed.   If you trust the reproducibility of all of your software, then you can construct the information you need on the fly, but
that might be grossly inefficient for analyzers.  

On the other hand, _some_ of that information is used regularly, and I do not KNOW how much.
So, if the physics groups agree we need this much and no more all of the time, and they do have
a mechanism (maybe cumbersome) for getting all of the information when they need it, then there could be an acceptable algorithm for pruning the event record down.

But, to my knowledge, no such communication between physics groups has taken place.

**Comment by tvami** [comment]
hi @Dr15Jones (I started to sign for `analysis`), it seems to me that there was a big pushback on this PR, was this ever resolved / should the PR be closed?

**Comment by smuzaffar** [comment]
Milestone for this pull request has been moved to CMSSW_14_0_X.Please open a backport if it should also go in to CMSSW_13_3_X.

**Comment by makortel** [comment]
@cms-sw/generators-l2 Is there any hope for this approach, or should we just close the PR?

**Comment by tvami** [comment]
Given the inactivity I think we should close this PR

**Comment by tvami** [comment]
@cmsbuild , please close

**Pull request closed without merging**
