### PR TITLE
impose TMPDIR=/tmp/$USER

### PR DESCRIPTION
**Pull request by perrozzi**
further evolution of https://github.com/cms-sw/cmssw/pull/21419
according to
https://www.open-mpi.org/faq/?category=osx#startup-errors-with-open-mpi-2.0.x
The workaround for the Open MPI 2.0.x and v2.1.x release series is to set the TMPDIR environment variable to /tmp or other short directory name.
As far as I see from the example, the directory created in the TMPDIR path should be unique and related to the MPI session.
Most important, the written data seems to be cleaned up by MPI after use (i.e. if I point TMPDIR to any directory, it is empty after the job has either succeeded or failed)
@Dr15Jones @bbockelm

### CODE REVIEW

**Comment by perrozzi** [comment]
please test

**Comment by efeyazgan** [comment]
+1

**Comment by davidlange6** [comment]
@Dr15Jones @bbockelm - please comment that this looks ok for you

**Comment by Dr15Jones** [comment]
@davidlange6 I don't have enough expertise with Linux or batch systems to give a reasonable opinion.

**Comment by bbockelm** [comment]
There's no guarantee that the `$USER` environment variable is set in the runtime, nor is there a guarantee that there's a stable UID mapping.  Further, MPI will "most of the time" take care of the directory it creates (it won't in the case of a `SIGSEGV`, because that's how Unix works) but this PR will still leave the `/tmp/$USER` directory in places.

(Note: any use of the `system` syscall is invariably a potential security issue, as it is here.  It is nearly impossible to use in a safe manner.)

Let's just aim for a simple solution: if the site provides a `$TMPDIR` we cannot use, utilize `/tmp` instead.

I think something like this would work (untested):
```
const char *tmpdir = getenv("TMPDIR");
if (tmpdir && (strlen(tmpdir) > 50)) {
    setenv("TMPDIR", "/tmp", true);
}
```
given that OpenMPI will cleanup the created directory in the majority of cases.

If sites provides a `$TMPDIR` we cannot use and don't like us utilizing `/tmp`, we can always have constructive conversation when the time comes...

**Comment by perrozzi** [comment]
please test

**Comment by perrozzi** [comment]
implemented and tested suggestion from @bbockelm, it does what it supposed to do.
the problem might not be fully solved (i.e. is not for sure, but error rate should be much lower, in fact as discussed elsewhere and reminded by Liz at the ORP, we might need a "global strategy" for temporary directories, there as also issues of other kind, cfr https://hypernews.cern.ch/HyperNews/CMS/get/generators/3745)

**Comment by bbockelm** [comment]
Yeah - it's best-practice to follow `$TMPDIR` when possible.  However, this illustrates a case when `$TMPDIR` isn't usable.

On the site side, it's best to make `/tmp` unique per-job as not all software is adapted for `$TMPDIR`.  In the case of Florida, there are available plugins for their batch system to do precisely this, but they choose not to run them.  So, they've effectively nominated themselves as the sentinel for large files in `/tmp`; we update software we control on a best-effort basis and otherwise file bugs.

**Comment by davidlange6** [comment]
merge

**Pull request merged**
