### PR TITLE
move header in private directory

### PR DESCRIPTION
**Pull request by smuzaffar**
#### PR description:

Although these are public headers but are not suppose to be included directly e.g
- `*TkRotation.h`: These are included via `ThRotation.h`
- `*Basic*DVector`: These headers are exposed via `Basic*DVector.h`
- `AVXVec.h`: This is included via `SSEVec.h` 

 This PRs move these headers in interface/private directory. This will help building CXXModules for all headers of package/interface directory. 

#### PR validation:

cms-checkdeps and local build works

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by VinInn** [comment]
Is this a new practice to eventually become pervasive?
Can it be added to the CMS software rules?

**Comment by smuzaffar** [comment]
@fabiocos  @VinInn , I would recommend this practice. If no objections then yes we should update CMS software packaging rules.

**Comment by perrotta** [comment]
+1
- technical 
- jenkins tests pass

**Comment by civanch** [comment]
+1

**Comment by fabiocos** [comment]
@smuzaffar @VinInn I understand the purpose in this specific case. Which are the other possible uses cases you have in mind?

**Comment by VinInn** [comment]
> On 15 May, 2019, at 2:45 PM, Fabio Cossutti <notifications@github.com> wrote:
> 
> @smuzaffar @VinInn I understand the purpose in this specific case. Which are the other possible uses cases you have in mind?
> 
> 
There are many cases (in particular with templates) where the user interface is made up of many other "implementation" classes that shall not be used directly.
Where inlining is not required typically the implementation classes reside in an anonimous namespace in the "src" .cc file itself, but in case of inlining the implementation (even if in a different namespace)
remains exposed to users.

v.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
