### PR TITLE
[92X] Improvements to L1 Offline DQM - part 1 - backport

### PR DESCRIPTION
**Pull request by kreczko**
Backport of PR #19795 (issue #19590)

### CODE REVIEW

**Comment by rekovic** [comment]
please test

**Comment by rekovic** [comment]
backport

**Comment by rekovic** [comment]
+1

**Comment by dmitrijus** [comment]
+1

**Comment by rekovic** [comment]
@kreczko 
Please change titles to describe better each of these PRs
#20231 
#20230
#20228

**Comment by rekovic** [comment]
backport of #19795

**Comment by davidlange6** [comment]
+1

**Pull request merged**
