### PR TITLE
Code format

### PR DESCRIPTION
**Pull request by civanch**
#### PR description:
Only code format 

#### PR validation:
runTheMatrix tests, results should be identical

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by civanch** [comment]
hold
there is an important PR #26578, which should be evaluated and merge first

**Comment by fabiocos** [comment]
@civanch #26578 has been now merged, and this PR should be rebased

**Comment by civanch** [comment]
not needed - other PRs applying code format

**Pull request closed without merging**
