### PR TITLE
Allow edmodule.clone(pset) for PSet to override parameters

### LINKED ISSUE #124: EDModule.clone(pset) raises exception on duplicate parameters
See discussion in https://github.com/cms-sw/cmssw/pull/33354#issuecomment-820580988

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

This PR allows `edmodule.clone(pset)` to work in the python configuration (previously it could lead to "duplicate parameter" errors if `pset` had parameters already defined in `edmodule`). Motivation to allow it is that `clone()` is (similar to) a constructor call with defaults taken from the cloned-from module. Semantics is that the parameters in `pset` override those in `edmodule`. Passing multiple PSets along `edmodule.clone(pset1, pset2)` is allowed as long as `pset1` and `pset2` have distinct parameters, similar to `EDModule` constructors.

Original discussion was in https://github.com/cms-sw/cmssw/pull/33354#issuecomment-820580988.

Resolves https://github.com/makortel/framework/issues/124

#### PR validation:

Framework unit tests pass.

### CODE REVIEW

**Comment by makortel** [comment]
@perrotta Here is what we discussed in https://github.com/cms-sw/cmssw/pull/33354#issuecomment-820580988 (sorry it took a bit more than "few days in wall clock time")

**Comment by Dr15Jones** [comment]
As a side note, do you think we should support unnamed `dict` as inputs as well?

**Comment by makortel** [comment]
> As a side note, do you think we should support unnamed `dict` as inputs as well?

We kind of do already with `edmodule.clone(**dict)`, although that has a limit of one `dict`. At this point I would not proceed for direct `edmodule.clone(dict)`, but this is not a strong feeling.

**Comment by perrotta** [comment]
> @perrotta Here is what we discussed in [#33354 (comment)](https://github.com/cms-sw/cmssw/pull/33354#issuecomment-820580988) (sorry it took a bit more than "few days in wall clock time")

Thank you @makortel

**Comment by qliphy** [comment]
+1

**Pull request merged**
