### PR TITLE
Correct url of the GEN fragment in a Pythia8Interface test and of the RelMon main page, after SSO migration

### PR DESCRIPTION
**Pull request by perrotta**
#### PR description:

Unit test "TestGeneratorInterfacePythia8ConcurrentGeneratorFilter" was failing in the IBs because of a modified address in the pdmv repository of the GEN fragment needed for the test:
From: cms-pdmv.cern.ch
To: cms-pdmv-prod.web.cern.ch

The change in the url of pdmv scripts, to access McM, get in with recent SSO migration

Since I found another such case in Utilities/RelMon/python/definitions.py, I decided to fix also the url listed there in this PR (title and description modified from the original PR)

#### PR validation:

`scram b runtests` works without errors

#### Backports

The unit test is currently failing in all releases: if we want to fix it, this simple fix should be backported in all them

### CODE REVIEW

**Comment by perrotta** [comment]
assign pdmv

@cms-sw/pdmv-l2 this error showed up first in CMSSW_13_3_X_2023-10-22-2300, while it was not present in the previous days IBs: did you move your staffs sometimes on Sunday?

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
type bug fix

**Comment by iarspider** [comment]
@perrotta I made a PR with slightly different fix for the same issue - https://github.com/cms-sw/cmssw/pull/43089, should I close it in favor of this?

**Comment by perrotta** [comment]
> @perrotta I made a PR with slightly different fix for the same issue - #43089, should I close it in favor of this?

Ah, sorry @iarspider I did not notice it, while I should have checked...
Let @cms-sw/pdmv-l2 decide which is the most suitable fix. Probably one could mix them: if the move is supposed to be permanent, I think that the correct address should be used. On the other hand, one could also allow following redirections, to prevent further moves of the same url

**Comment by sunilUIET** [comment]
Hi @perrotta 

   This change, to access McM, get in with recent SSO migration 

https://cms-talk.web.cern.ch/t/pdmv-mcm-migration-to-the-new-sso/30378

So, we will need to update the pdmv url in scripts.

**Comment by perrotta** [comment]
Thank you @sunilUIET 
I will rebase this PR on tomorrow's IB, then

**Comment by perrotta** [comment]
@sunilUIET I rebased the PR on top of the HEAD of the master.
I found another such case in Utilities/RelMon/python/definitions.py, and I decided to fix also that one in this PR: please comment in case you don't agree with the fix (otherways just give your "+1" so that other parties know that PDMV agree with the change)

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
@cms-sw/generators-l2 @cms-sw/dqm-l2 : this is rather trivial, and already approved by pdmv. Could you please have a look?

**Comment by tjavaid** [comment]
+1

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
