### PR TITLE
CSC/GEM validation fix for HLT tests

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
#### PR description:

CSC/GEM validation fix for HLT tests
See discussion in #33085 

#### PR validation:

TSG tests

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by Martin-Grunewald** [comment]
type bug-fix

**Comment by silviodonato** [comment]
+1

**Pull request merged**
