### PR TITLE
First version of nanoDQMIO content

### PR DESCRIPTION
**Pull request by jfernan2**
#### PR description:
First version of nanoDQMIO data-Tier with a preliminary content based on requests from subsystems interested in doing ML4DC/DQM with the upcoming ReReco of Pilot Test Runs taken in Autumn 2021

Tested with: runTheMatrix.py -l limited -i all --ibeos   --command '--procModifiers=dqmPerLSsaving --customise_commands="process.DQMStore.saveByLumi =  cms.untracked.bool(True)"' 

up to Harvesting step (excluded) since Harvesting is not defined with perLS saving

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by perrotta** [comment]
@jfernan2 since, as far as I understand, this PR is ready to get merged, could you please remove "[RFC]" from the title, then?

**Comment by jfernan2** [comment]
Sorry, I had forgotten. Done. Thanks

**Comment by perrotta** [comment]
+1

**Pull request merged**
