### PR TITLE
 Code Issues 333 Pull requests 129 Projects 0 Wiki Insights Remove check for empty sum collection in CALOL2-uGT comparison 10_0_X

### PR DESCRIPTION
**Pull request by ashtipliyski**
PR addresses a false alarm that the DQM comparison plot located under

L1T / L1TStage2uGT / calol2ouput_vs_uGTinput / errorSummaryNum

10_0_x backport of #22878

### CODE REVIEW

**Comment by dmitrijus** [comment]
Is this really necessary for 10_0_X? 
We are switching online DQM to 10_1 this week.

**Comment by thomreis** [comment]
Hi @dmitrijus 
No this one is not needed anymore now that P5 moves to 10_1.

**Comment by fabiocos** [comment]
@ashtipliyski please just close it, as 10_0_X has been replaced by 10_1_X

**Comment by ashtipliyski** [comment]
Closing due to phasing out of 10_0_X out of production.

**Pull request closed without merging**
