### PR TITLE
Minimal Change: reading tags from CondDBv2

### PR DESCRIPTION
**Pull request by mmusich**
That's the minimal change. In the end all tags need to go in GT.

### CODE REVIEW

**Comment by mmusich** [comment]
@slava77 this passes at least the `runTheMatrix.py -l limited` tests. In the end we need the Tau people to identifiy which tags out of the 133 they have in DB they need in GT. @diguida @andrewj314

**Comment by mmusich** [comment]
please test

**Comment by slava77** [comment]
@mmusich This will work for 76X/later where everything is v2, right?
I suppose, we will not update anything in 74X.
Please confirm.

**Comment by mmusich** [comment]
@slava77 should work everywhere past 74X included.

**Comment by cvuosalo** [comment]
+1

For #12094 1109169e4ff67fde2bfc8f87ba1c78b988ef25b7

Small change for reading tau tags from CondDBv2.

Jenkins [tests](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-12094/9192/summary.html) against baseline CMSSW_8_0_X_2015-10-25-2300 show no significant differences.

**Comment by davidlange6** [comment]
+1
thanks! lets get this into 76x..

**Comment by mmusich** [comment]
@davidlange6 sorry for the late reply (I was offline in the last 4 days). Shall I provide the PR for 76X or being 760 already built I am too late?

**Comment by davidlange6** [comment]
@mmusich - no problem - a 76x PR will still be useful. Thanks!

**Pull request merged**
