### PR TITLE
Remove Legacy Scenario Test

### PR DESCRIPTION
**Pull request by ianna**
#### PR description:

* Unused scenario has been deleted and so its test

#### if this PR is a backport please specify the original PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by fabiocos** [comment]
@ianna this is a duplicate of #27390 , not relevant which of them is integrated.

**Comment by ianna** [comment]
Close as a duplicate

**Pull request closed without merging**
