### PR TITLE
Fix use of duplicate bin names in DQM/L1TMonitor

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

ROOT appears to be enforcing that user defined bin names for histograms must be unique.
This fixes the failures in the integration builds of workflow 4.6.

#### PR validation:

Now when running workflow 4.6 step3 the jobs succeed.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test with workflow 4.6

**Comment by perrotta** [comment]
please test workflow 4.6

**Comment by perrotta** [comment]
urgent

**Comment by perrotta** [comment]
@cms-sw/dqm-l2 could you please review this PR, and also sign if you agree with it?

**Comment by perrotta** [comment]
+1
- Bypassing the dqm signature, in order to have this fix into 12_6_0_pre4 that we plan to build by tomorrow
- @cms-sw/dqm-l2 please complain if there is anything you don't like here: this can still get reverted after pre4

**Comment by perrotta** [comment]
merge

**Comment by emanueleusai** [comment]
+1

**Pull request merged**
