### PR TITLE
[12.4.X] add support for `ALCARECOTkAlJetHT` to `trackselectionRefitting`

### PR DESCRIPTION
**Pull request by mmusich**
backport of https://github.com/cms-sw/cmssw/pull/39013

#### PR description:

Title says it all. Needed to make use of the new ALCARECO samples created via PR https://github.com/cms-sw/cmssw/pull/38254 in the alignment workflow.

#### PR validation:

Run the unit tests of `Alignment/OfflineValidation` without problems

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

verbatim backport of https://github.com/cms-sw/cmssw/pull/39013

### CODE REVIEW

**Comment by mmusich** [comment]
test parameters:
   * addpkg = Alignment/OfflineValidation, Alignment/TrackerAlignment, Alignment/MillePedeAlignmentAlgorithm

**Comment by mmusich** [comment]
type bugfix, trk

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
+alca

**Comment by qliphy** [comment]
+1

**Pull request merged**
