### PR TITLE
[102X][L1T][DQMOffline] Tau DQM updates (CMSLITDPG-590)

### PR DESCRIPTION
**Pull request by kreczko**
Backport of #23673

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by thomreis** [comment]
+1

**Comment by andrius-k** [comment]
+1

**Comment by thomreis** [comment]
Hi @fabiocos 
can this PR be merged please so that it can run at the T0 as soon as possible?

**Comment by fabiocos** [comment]
+1

**Pull request merged**
