### PR TITLE
Payload Inspector: add more two-tags comparisons

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

This PR adds few more comparison plots for the`Alignment` and `AlCaRecoTriggerBits` `CondFormats` to be able to compare conditions across tags. In particular few new plots for checking the Tracker and Pixel center of gravity positions are added.

#### PR validation:

Relies on the unit tests implemented in this PR.

#### if this PR is a backport please specify the original PR:

This PR is not a backport, and a backport is not needed.

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by ggovi** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
