### PR TITLE
[10.2.X][DQM] Remove unused variables to avoid compilation warnings

### PR DESCRIPTION
**Pull request by smuzaffar**

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by jfernan2** [comment]
please test

**Comment by thomreis** [comment]
Hi @smuzaffar 
For my curiosity: The changes that caused the compiler warnings to appear were introduced by applying a patch that was suggested by the code checks. Why the code checks suggest it if it causes a warning? And why was there no warning before the patch? The variables were unused also before the patch.

**Comment by smuzaffar** [comment]
@thomreis , no idea why compiler did not complain about this before the code checks. I saw that it was
```
const std::string hName = qHist->getName();
```
and code checks suggested to have const reference i.e.
```
const std::string& hName = qHist->getName();
```
The unused variable was alwasy there but compiler only start complaining when it was made reference.

**Comment by thomreis** [comment]
@smuzaffar thanks. In any case good to remove the unused variable.

**Comment by fabiocos** [comment]
+1

trivial removal of unused variable (thank you @smuzaffar). With the new bot warning label it should be easier to catch these problems before merging the PRs

**Comment by fabiocos** [comment]
merge

**Comment by andrius-k** [comment]
+1

Signing for the sake of completeness.

**Pull request merged**
