### PR TITLE
HGCAL: Fix HGCHEB isSiFE configuration

### PR DESCRIPTION
**Pull request by stahlleiton**
#### PR description:

This PR fixes a bug introduced in https://github.com/cms-sw/cmssw/pull/39720 .
The parameter isSiFE was set to False by mistake which caused the energy scale in HGCAL scintillator (HEB) rechits to be shifted. Setting the isSiFE parameter back to True fixes the issue.

#### PR validation:

The PR was tested with: runTheMatrix.py -w upgrade -l 25300.0

### CODE REVIEW

**Comment by youyingli** [comment]
The energy scale shift in HGCAL scintillator part was observed from ```CloseByPGun_CE_H_Coarse_Scint``` sample in 12_6_0_pre4 and we found the issue comes from https://github.com/cms-sw/cmssw/pull/39720

By using
```
runTheMatrix.py -w "upgrade" -b "UPSG_Std_2026D88noPU" --label "2026D88noPU" -t 8 -m 1500 -l 39497.0 --command="--customise SLHCUpgradeSimulations/Configuration/aging.customise_aging_1000" --noCaf --wm force
```
the result below shows this https://github.com/cms-sw/cmssw/pull/39720 shifts the energy scale to lower one w.r.t. 12_6_0_pre3 and is fixed by this PR.

Screen Shot 2023-05-05 at 12 18 42

**Comment by perrotta** [comment]
please test

**Comment by missirol** [comment]
FYI: @beaucero @SohamBhattacharya , since this affects the HLT Phase-2 menu.

**Comment by srimanob** [comment]
This PR should be backport to CMSSW_13_1, for the HLT production.

**Comment by srimanob** [comment]
type bug-fix

**Comment by stahlleiton** [comment]
> This PR should be backport to CMSSW_13_1, for the HLT production.

I will prepare a backport asap but 
I thought the master branch already pointed to CMSSW 13_1_X

**Comment by youyingli** [comment]
> > This PR should be backport to CMSSW_13_1, for the HLT production.
> 
> I will prepare a backport asap but I thought the master branch already pointed to CMSSW 13_1_X

Now the master branch points to CMSSW_13_2_X milestone.

**Comment by missirol** [comment]
+hlt

Bugfix for HGCal by HGCal DPG. I assume @beaucero and @SohamBhattacharya are okay with having it in the HLT Phase-2 menu.

**Comment by mandrenguyen** [comment]
type hgcal

**Comment by rappoccio** [comment]
+1

**Pull request merged**
