### PR TITLE
Fastsim pixel res histo update

### PR DESCRIPTION
**Pull request by lveldere**
edits #9803 
takes into account that the new pixel resolution files are in cmsdist
https://github.com/cms-sw/cmsdist/pull/1695

### CODE REVIEW

**Comment by lveldere** [comment]
please test

**Comment by davidlange6** [comment]
@lveldere - is this ready to be merged (I assume so, but you have not signed it)

**Comment by lveldere** [comment]
+1

comparisons produced in private, and found to be good.

**Comment by lveldere** [comment]
@davidlange6 
thanks

**Pull request merged**
