### PR TITLE
HLT customisation for Patatrack pixel tracks and GPU offload [12.0.x]

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Add a customisation script for the HLT:
  - enable the Patatrack pixel track reconstruction, with quadruplets or triplets, running on CPU or GPU
  - optionally, add the possibility to offload the ECAL unpacking and local reconstruction to run on GPU
  - optionally, add the possibility to offload the HCAL local reconstruction to run on GPU

The new customisation is not used by any workflows.

#### PR validation:

Validated in CMSSW_12_0_0_pre6 with
```bash
cmsDriver.py reHLT \
    --processName reHLT \
    -s HLT:@relval2021 \
    --conditions 120X_mcRun3_2021_realistic_v4 \
    --datatier GEN-SIM-DIGI-RAW \
    -n 10 \
    --eventcontent FEVTDEBUGHLT \
    --geometry DB:Extended \
    --era Run3 \
    --customise=HLTrigger/Configuration/customizeHLTforPatatrack.customizeHLTforPatatrackTriplets \
    --filein /store/relval/CMSSW_12_0_0_pre6/RelValTTbar_14TeV/GEN-SIM-DIGI-RAW/PU_120X_mcRun3_2021_realistic_v4_JIRA_129-v1/00000/79c06ed5-929b-4a57-a4f2-1ae90e6b38c5.root
```
resulting in
```
19-Aug-2021 17:42:08 CEST  Initiating request to open file file:///gpu_data/store/relval/CMSSW_12_0_0_pre6/RelValTTbar_14TeV/GEN-SIM-DIGI-RAW/PU_120X_mcRun3_2021_realistic_v4_JIRA_129-v1/00000/79c06ed5-929b-4a57-a4f2-1ae90e6b38c5.root
19-Aug-2021 17:42:10 CEST  Successfully opened file file:///gpu_data/store/relval/CMSSW_12_0_0_pre6/RelValTTbar_14TeV/GEN-SIM-DIGI-RAW/PU_120X_mcRun3_2021_realistic_v4_JIRA_129-v1/00000/79c06ed5-929b-4a57-a4f2-1ae90e6b38c5.root
%MSG-e TkDetLayers:   TSGFromL2Muon:hltL3NoFiltersNoVtxTrajSeedOIHit@streamBeginRun  19-Aug-2021 17:42:51 CEST Run: 1 Stream: 0
 ForwardDiskSectorBuilderFromDet: Trying to build Petal Wedge from Dets at different z positions !! Delta_z = -0.951241
%MSG
Begin processing the 1st record. Run 1, Event 2, LumiSection 1 on stream 0 at 19-Aug-2021 17:42:51.956 CEST
#--------------------------------------------------------------------------
#                         FastJet release 3.4.0
#                 M. Cacciari, G.P. Salam and G. Soyez                  
#     A software package for jet finding and analysis at colliders      
#                           http://fastjet.fr                           
#	                                                                      
# Please cite EPJC72(2012)1896 [arXiv:1111.6097] if you use this package
# for scientific work and optionally PLB641(2006)57 [hep-ph/0512210].   
#                                                                       
# FastJet is provided without warranty under the GNU GPL v2 or higher.  
# It uses T. Chan's closest pair algorithm, S. Fortune's Voronoi code
# and 3rd party plugin jet algorithms. See COPYING file for details.
#--------------------------------------------------------------------------
Begin processing the 2nd record. Run 1, Event 1, LumiSection 1 on stream 0 at 19-Aug-2021 17:43:01.240 CEST
Begin processing the 3rd record. Run 1, Event 3, LumiSection 1 on stream 0 at 19-Aug-2021 17:43:08.832 CEST
Begin processing the 4th record. Run 1, Event 4, LumiSection 1 on stream 0 at 19-Aug-2021 17:43:11.405 CEST
Begin processing the 5th record. Run 1, Event 5, LumiSection 1 on stream 0 at 19-Aug-2021 17:43:15.623 CEST
Begin processing the 6th record. Run 1, Event 7, LumiSection 1 on stream 0 at 19-Aug-2021 17:43:19.599 CEST
Begin processing the 7th record. Run 1, Event 8, LumiSection 1 on stream 0 at 19-Aug-2021 17:43:26.721 CEST
Begin processing the 8th record. Run 1, Event 6, LumiSection 1 on stream 0 at 19-Aug-2021 17:43:28.204 CEST
Begin processing the 9th record. Run 1, Event 9, LumiSection 1 on stream 0 at 19-Aug-2021 17:43:37.284 CEST
Begin processing the 10th record. Run 1, Event 10, LumiSection 1 on stream 0 at 19-Aug-2021 17:43:42.508 CEST
19-Aug-2021 17:43:51 CEST  Closed file file:///gpu_data/store/relval/CMSSW_12_0_0_pre6/RelValTTbar_14TeV/GEN-SIM-DIGI-RAW/PU_120X_mcRun3_2021_realistic_v4_JIRA_129-v1/00000/79c06ed5-929b-4a57-a4f2-1ae90e6b38c5.root

=============================================

MessageLogger Summary

 type     category        sev    module        subroutine        count    total
 ---- -------------------- -- ---------------- ----------------  -----    -----
    1 TkDetLayers          -e TSGFromL2Muon:hl                       1        1
    2 fileAction           -s file_close                             1        1
    3 fileAction           -s file_open                              2        2

 type    category    Examples: run/evt        run/evt          run/evt
 ---- -------------------- ---------------- ---------------- ----------------
    1 TkDetLayers          Run: 1 Stream: 0                  
    2 fileAction           PostGlobalEndRun                  
    3 fileAction           pre-events       pre-events       

Severity    # Occurrences   Total Occurrences
--------    -------------   -----------------
Error                   1                   1
System                  3                   3

dropped waiting message count 0
```

Tested successfully both with and without a GPU.
The physics validation and the GPU vs CPU comparison will follow after the customisation has been merged.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Backport of #34956 .

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by fwyzard** [comment]
backport #34956

**Comment by fwyzard** [comment]
@cmsbuild, please test

To make the bot happy, even if the new customisation is not used anywhere.

**Comment by Martin-Grunewald** [comment]
+1

**Comment by perrotta** [comment]
+1
- Backport of a customization not yet used in any standard workflow, but useful to be run in 12_0_X

**Pull request merged**
