### PR TITLE
[104X]Change GT. Fix Pedestal Tag in Relval Offline GT

### PR DESCRIPTION
**Pull request by lpernie**
Change 103X_dataRun2_relval GT reverting ECAL pedestal to EcalPedestals_express.

### CODE REVIEW

**Comment by lpernie** [comment]
test workflow 1010.0

**Comment by fabiocos** [comment]
@lpernie @tocheng the crash itself is fixed. Do you understand why touching ECAL pedestals affecting 2017 modifies the b-tagging output in 2016 tests (136.731)? As far as I can see in 

https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/103X_dataRun2_relval_v7/103X_dataRun2_relval_v8

this change does not affect only ECAL pedestals, is this explicitly intended?

If this is ok and desired, please sign this PR so as we can fix the issue and move forward with 10_4_0_pre2 build

**Comment by lpernie** [comment]
Hi @fabiocos ,
The change only affect the ECAL pedestal Tag. The rest of the differences are due to the different Snapshot Time.
Still we are discussing with ECAL if the change in pedestal in this queue is something desired. We hope to converge soon.

**Comment by lpernie** [comment]
test workflow 1010.0

**Comment by lpernie** [comment]
@fabiocos this is the changes agreed with ECAL people.
Basically we use Prompt Tag for the Pedestal.

**Comment by lpernie** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
