### PR TITLE
Add WFs for 2023D

### PR DESCRIPTION
**Pull request by sunilUIET**
This PR adds WFs (141.041-141.049) for 2023D as mentioned in https://github.com/cms-sw/cmssw/issues/42340
Additional WF (141.039) for 2023C PartkingDoubleMuonLowMass

Changes will be backported to 13_0_X and 13_1_X

### CODE REVIEW

**Comment by sunilUIET** [comment]
test parameters:
relvals_opt= -w standard
workflows = 141.039,141.041,141.041,141.043,141.044,141.045,141.046,141.047,141.048,141.049

**Comment by sunilUIET** [comment]
please test

**Comment by sunilUIET** [comment]
+pdmv

**Comment by srimanob** [comment]
This PR test result is not healthy. It is too noisy with
```
%MSG-w NoModule:   ByClusterSummaryMultiplicityPairEventFilter:toomanystripclus53X  29-Jul-2023 09:27:44 CEST Run: 369978 Event: 570173543
No information for requested module 0 (STRIP). Please check in the Provenance Infomation for proper modules.
%MSG
%MSG-w NoModule:  ByClusterSummaryMultiplicityPairEventFilter:manystripclus53X  29-Jul-2023 09:27:44 CEST Run: 369978 Event: 570173543
No information for requested module 0 (STRIP). Please check in the Provenance Infomation for proper modules.
%MSG
```
@sunilUIET, do you check GT with @cms-sw/alca-l2 ?

**Comment by tvami** [comment]
The GT was frozen at  2023-06-14 12:00:00 my understanding is that run used in these tests is 369978 and is from 2023-07-02 16:10:10 ... so this is expected not to work. I thought we agreed that evenever new data wfs will be added, we will touch base since AlCa needs to re-snapshot the GT

**Comment by tvami** [comment]
test parameters:
 * relvals_opt= -w standard
 * workflows = 141.039,141.041,141.041,141.043,141.044,141.045,141.046,141.047,141.048,141.049
 * pull_request = https://github.com/cms-sw/cmssw/pull/42358

**Comment by srimanob** [comment]
@cmsbuild please abort

Sorry, I would like to fix typo in workflow id to trigger the test.

**Comment by srimanob** [comment]
test parameters:

**Comment by srimanob** [comment]
test parameters:
- relvals_opt= -w standard
- workflows = 141.039,141.041,141.042,141.043,141.044,141.045,141.046,141.047,141.048,141.049
- pull_request = https://github.com/cms-sw/cmssw/pull/42358

**Comment by srimanob** [comment]
@cmsbuild please test

**Comment by srimanob** [comment]
+Upgrade

All new workflows run fine.

**Comment by perrotta** [comment]
+1

**Pull request merged**
