### PR TITLE
L1muon offline dqm harvesting config fix

### PR DESCRIPTION
**Pull request by thomreis**
This fixes the issue that the L1 muon offline DQM harvesting module was not run in the common DQM workflow.

The L1TEgamma harvesting was moved into the Stage2l1TriggerDqmOfflineClient sequence since it does not need to run for legacy workflows.

cms.EDAnalyzer harvesting modules that were merged after the change to DQMEDHarvester have been migrated.

Replacement of couts with LogInfo.

### CODE REVIEW

**Comment by rekovic** [comment]
please test

**Comment by rekovic** [comment]
@thomreis 
Do we now have successfully created muon efficiency plots offline,  that were otherwise failing to be made in production?

**Comment by thomreis** [comment]
@rekovic yes, at least in my tests it works. The sequence with the module was not executed before.

Do you know which workflow of the matrix tests runs the DQM that is also running at the T0? I could not find one that suited me and had to adjust the cmsDriver command to test.

**Comment by dmitrijus** [comment]
+1

**Comment by rekovic** [comment]
+1

**Comment by rekovic** [comment]
@thomreis 
It looks like workflow 136.731 runs on 2016 data and runs the DQM.

**Comment by thomreis** [comment]
@rekovic 136.731 runs the DQM, yes, but not the harvesting that is done at the T0 (called @common). I noticed that the efficiency histograms for L1TEgamma are produced at the T0 but not when running 136.731.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
