### PR TITLE
[NanoAOD] Adding correct Iso filter name (without cut values) for Run3

### PR DESCRIPTION
**Pull request by wonpoint4**
#### PR description:
Adding correct Iso filter name (without cut values) for Run3
Relevant JIRA ticket : https://its.cern.ch/jira/browse/CMSHLT-2312

And I was wondering that I have to make backport PRs to the both of 124X and 125X.

### CODE REVIEW

**Comment by vlimant** [comment]
integration test running https://gitlab.cern.ch/cms-nanoAOD/nanoAOD-integration/-/pipelines/4459659

**Comment by vlimant** [comment]
please test

**Comment by wonpoint4** [comment]
Dear experts,
I couldn't understand the origin of error (The relvals timed out after 4 hours.)
Could you give me an advice or suggestion here?

**Comment by perrotta** [comment]
please test

**Comment by swertz** [comment]
+xpog

> And I was wondering that I have to make backport PRs to the both of 124X and 125X.

That won't be necessary, 124X is closed for Nano and there will be no re-nano in 125X.

**Comment by rappoccio** [comment]
+1

**Comment by silviodonato** [comment]
Related to https://its.cern.ch/jira/browse/CMSHLT-2312

> > And I was wondering that I have to make backport PRs to the both of 124X and 125X.

> That won't be necessary, 124X is closed for Nano and there will be no re-nano in 125X.

This creates problem about the maintenance of the PromptNano AOD when the HLT menu changes during the datataking. We need a larger discussion about this.

In any case, @wonpoint4  is your PR compatible with the HLT menu both before and after CMSHLT-2312, or only after CMSHLT-2312 (ie. it should be compatible with both HLT v1.2 and HLT v1.3)

**Comment by silviodonato** [comment]
cc @jmartinb

**Comment by silviodonato** [comment]
cc: @jordan-martins

**Comment by wonpoint4** [comment]
> In any case, @wonpoint4 is your PR compatible with the HLT menu both before and after CMSHLT-2312, or only after CMSHLT-2312 (ie. it should be compatible with both HLT v1.2 and HLT v1.3)

Yes, this PR is supposed to be compatible with HLT menu before/after CMSHLT-2312, like compatible with menu during the whole Run3, and even the Run2.

**Comment by swertz** [comment]
> And I was wondering that I have to make backport PRs to the both of 124X and 125X.

We have now decided that we would backport changes to the trigger object filter names to 124X to allow prompt nano to pick up those changes, even if it breaks compatibility with Run2 or existing V10 samples. Can you please make a backport to 124X @wonpoint4 ?

In principle the same changes should then also be applied to the frozen V10 config in master: https://github.com/cms-sw/cmssw/blob/master/PhysicsTools/NanoAOD/python/V10/triggerObjects_cff.py

**Comment by swertz** [comment]
@wonpoint4 with the backport merged we now have an inconsistency between the nanoV10 in 124X and the frozen V10 config in master. Can I ask you to make another PR to master to apply the same changes to https://github.com/cms-sw/cmssw/blob/master/PhysicsTools/NanoAOD/python/V10/triggerObjects_cff.py ?

**Pull request merged**
