### PR TITLE
MTD geometry: fix RecoMTD/DetLayers unit test 

### PR DESCRIPTION
**Pull request by fabiocos**
#### PR description:

As a consequence of the move of all MTD geometry unit tests to scenario D110 in https://github.com/cms-sw/cmssw/pull/45211 , the unit test for the tracking geometry navigation in ```RecoMTD/DetLayers``` starts to fail on aarch64 architecture https://github.com/cms-sw/cmssw/pull/45211#issuecomment-2182787318 , due to some numerical differences in the output of operations displayed in the reference file. 

The underlying geometry calculations are made using ```float``` for performance reasons, and on operations involving space measurements of a size O(100 cm) does not always guarantee to display identical results at the micron level on both amd64 and aarch64. For this reason:

- a better formatting and rounding is adopted in this test, with a configurable precision;
- a 4 decimal digits precision is kept for direct inspection, but a safer 2 digits precision is used in the unit test (and corresponding reference, that needs to be updated in parallel to this PR)

#### PR validation:

The unit test comparison succeed on both amd64 and aarch64 (lxplus-arm.cern.ch).

### CODE REVIEW

**Comment by fabiocos** [comment]
please test with https://github.com/cms-data/Geometry-TestReference/pull/15

**Comment by fabiocos** [comment]
please test with https://github.com/cms-data/Geometry-TestReference/pull/15 for el8_aarch64_gcc12

**Comment by mandrenguyen** [comment]
type mtd

**Comment by mandrenguyen** [comment]
+1

**Comment by fabiocos** [comment]
@cms-sw/upgrade-l2 @cms-sw/orp this PR (and the corresponding https://github.com/cms-data/Geometry-TestReference/pull/15 ) will prevent the unit test crash in IB observed for aarch64 architecture, reported by @aandvalenzuela

**Comment by srimanob** [comment]
+Upgrade

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
