### PR TITLE
Remove obsolete HardEventHypothesis class

### PR DESCRIPTION
**Pull request by perrotta**
As pointed out in github issue #29834, and confirmed by the original author of the code therein (@rappoccio), the class HardEventHypothesis "has no purpose anymore and can be removed".

This is what this PR does. No effect expected anywhere

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
+1
- Trivial removal of useless and obsolete code

**Comment by silviodonato** [comment]
merge
@santocch

**Comment by santocch** [comment]
+1

**Pull request merged**
