### PR TITLE
add ignoreVertices parameter

### PR DESCRIPTION
**Pull request by mtosi**
as PR https://github.com/cms-sw/cmssw/pull/18041

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
+1
New parameter added for use at HLT. Default value reproduces the previous behavior: no difference expected, and no difference observed.

**Comment by mtosi** [comment]
could we integrate this PR ?
I think it is needed by MUO POG for HLT developments

**Comment by davidlange6** [comment]
+1

**Pull request merged**
