### PR TITLE
HCAL DQM small fixes of problems experienced during MWGR2

### PR DESCRIPTION
**Pull request by vkhristenko**
resubmitting on top of the updated 80X since it wouldn't merge.
I closed previous PR because I didn't really know based from where to rebase. Just merging CMSSW80X branch showed a large number of commits... may be there was a better way...

VK

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
@vkhristenko - please give this PR a meaningful name for the release notes. Thanks

**Comment by vkhristenko** [comment]
@davidlange6  - done

**Comment by Martin-Grunewald** [comment]
Hi,

This PR in 81X (was auto ported to 81X) seems to create a problem in 81X,
with this error message:
```
----- Begin Fatal Exception 03-Mar-2016 07:38:05 CET-----------------------
An exception of category 'Configuration' occurred while
   [0] Processing run: 1 lumi: 2 event: 301
   [1] Running path 'validation_step'
   [2] Calling event method for module MultiTrackValidator/'hiTrackValidator'
Exception Message:
Efficiency and fake TrackingParticle (refs) point to different collections (eff 3:256 fake 3:254). This is not supported. Efficiency TP set must be the same or a subset of the fake TP set.
----- End Fatal Exception -------------------------------------------------
```

It is a cmsDriver generated workflow:

```
# Auto generated configuration file
# using: 
# Revision: 1.19 
# Source: /local/reps/CMSSW/CMSSW/Configuration/Applications/python/ConfigBuilder.py,v 
# with command line options: RelVal --step=RAW2DIGI,L1Reco,RECO,VALIDATION,DQM --conditions=auto:run2_mc_HIon --filein=file:RelVal_DigiL1RawHLT_HIon_MC.root --custom_conditions= --fileout=RelVal_RECO_HIon_MC.root --number=25 --mc --no_exec --datatier SIM-RAW-HLT-RECO --eventcontent=RAW --customise=HLTrigger/Configuration/CustomConfigs.Base --era=Run2_HI --customise= --scenario=HeavyIons --python_filename=RelVal_RECO_HIon_MC.py --processName=RECO
```

**Pull request merged**
