### PR TITLE
Add Reco and HARVEST FakeHLT steps

### PR DESCRIPTION
**Pull request by jfernan2**
#### PR description:

In order to remove empty unused plots, FakeHLT DQM and NoHLT validation is added to reco and HARVEST steps of 2017 and 2018 data.
Only Run3 wfs should run HLT DQM and Validation and present.

#### PR validation:

Tested with: runTheMatrix.py --nThreads=10 --list=250202.181,28234.0,25202.0,23434.999,12434.0,11634.0,10824.0,10224.0,10042.0,10024.0

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

No

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by mtosi** [comment]
thanks !!!! (really really appreciated)

**Comment by jfernan2** [comment]
I believe the same can be applied to RecoPU and HARVESTPU, i.e. create a RecoPUFakeHLT and HARVESTPUFakeHLT like in wf10224.0
Nevertheless, I don't really understand why plots are not dropped with this change, I will research deeper..

**Comment by chayanit** [comment]
@jfernan2 , you also need to add them in PU part I think
https://github.com/cms-sw/cmssw/blob/9436ad2128acb579eefb009441ae298a989511bf/Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py#L165-L174

**Comment by jfernan2** [comment]
Thanks @chayanit indeed that is the place, I included it in a new commit and I have checked externally that HLT (empty) plots are being removed: DQMBinByBin tool do not show them due to the change of Reco/HARVEST step names, which makes the outputp filename different

**Comment by jfernan2** [comment]
please test

**Comment by kpedro88** [comment]
+upgrade

**Comment by chayanit** [comment]
+1

**Comment by silviodonato** [comment]
+1
empty DQM plots are removed in HLT folder

**Comment by silviodonato** [comment]
@jfernan2  see https://github.com/cms-sw/cmssw/issues/31502

**Pull request merged**
