### PR TITLE
Adding Sistrip DQM Cluster Maps

### PR DESCRIPTION
**Pull request by jandrea**
#### PR description:

Addition of TH2F plots showing the z-phi (r-phi) position of on track hits for the SiStrip barrel (endcaps). The plots are made per layer (per disk).

#### PR validation:

Compiles with CMSSW_11_0_X_2019-05-20-2300, tested with "runTheMatrix.py -l 10024 " and for 100 events.

### CODE REVIEW

**Comment by jfernan2** [comment]
Hi @jandrea, could you please make sure that subsystem name appears in the title of the PR?

**Comment by jfernan2** [comment]
please test

**Comment by jandrea** [comment]
subsystem name added to the PR title.

**Comment by jfernan2** [comment]
Same issue as in #26898 I am afraid. @jandrea can you please have a look?

**Comment by jandrea** [comment]
The problem has been spotted and a fix is implemented. I am currently testing it. In short, the crash came from HLTSiStripTrackMonitor:
For some on track RecHits, the local positions extracted from the function  localPositions() is (0,0,0), and in that case calling globalPosition() causes a segmentation violation.

To my understanding, for some SiStripRecHits on track, there might be sometime missing cluster information. I understood from @mmusich could be related to the way the HLT unpacks the strips information. 
The workaround is not use the globalPosition() function of RecHit but to recalculate it :
auto GP = tkgeom_->idToDet(tkrecHit->geographicalId())->surface().toGlobal(tkrecHit->localPosition());

This seems to work. I am currently testing this with the WF 136.85, 10824.0 and 250202.181

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Pull request merged**
