### PR TITLE
[10_6_X] Updated list of Geant4 process codes

### PR DESCRIPTION
**Pull request by civanch**
#### PR description:
It is a backport of https://github.com/cms-sw/cmssw/pull/38659. This PR is not urgent but needed for MC production release. It should not affect most of productions and is needed only for dark matter particle bremsstrahlung.

#### PR validation:
private

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
backport of https://github.com/cms-sw/cmssw/pull/38659

**Comment by civanch** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
