### PR TITLE
Fix `SiStripG2GainsValidator`

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

This PR is a simple follow-up to https://github.com/cms-sw/cmssw/pull/46382.
I noticed that the test started failing in `CMSSW_14_2_X_2024-10-16-1100` [log](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_amd64_gcc12/CMSSW_14_2_X_2024-10-16-1100/unitTestLogs/CondCore/SiStripPlugins#/), following up to a recent upload to the production SiStrip G2 tag ([cmsTalk](https://cms-talk.web.cern.ch/t/new-sistrip-g2-gain/53441/4)). 
The reasons lies in the fact that after that upload, we're currently in a situation in which the most recent IoV since (386968) in the production tag is more recent that the FCSR at the time of the test (386912). This leads calling the script `testCompareSiStripG2Gains.sh` with time-inverted arguments, which then causes crashes in the calls to the `getPayloadData.py` script.   
I fix this possible pitfall by changing the PCL FCSR to the HLT FCSR which is guaranteed to be >= to any possible upload to the production tag (barring upload mistakes). 
I profit of this PR to remove a few unneeded import statements. 

#### PR validation:

`scram b runtests_test_SiStripG2GainsValidator` run as of Oct 16, 2024 22:30 runs fine.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

N/A

### CODE REVIEW

**Comment by mmusich** [comment]
type bug-fix

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by perrotta** [comment]
+db
- There are differences in Phase2 tests for HGCal DQM: they are clearly not originated by this PR, quite likely some non-reproducibility introduced with some of the latest merged PR (also seen when testing in CMSSW_14_2_X_2024-10-15-1100/el8_amd64_gcc12, e.g. #46386: just guessing from the titles of the PR: [#45865](https://github.com/cms-sw/cmssw/pull/45865), [#45992](https://github.com/cms-sw/cmssw/pull/45992), ... @felicepantaleo)

**Comment by mmusich** [comment]
> There are differences in Phase2 tests for HGCal DQM: they are clearly not originated by this PR, quite likely some non-reproducibility introduced with some of the latest merged PR

Thanks @perrotta. Do you mind opening an issue about it for future reference ?

**Comment by perrotta** [comment]
> > There are differences in Phase2 tests for HGCal DQM: they are clearly not originated by this PR, quite likely some non-reproducibility introduced with some of the latest merged PR
> 
> Thanks @perrotta. Do you mind opening an issue about it for future reference ?

I already planned to do so, but I had to reach my office for it.
Here it is: https://github.com/cms-sw/cmssw/issues/46416

**Pull request merged**
