### PR TITLE
flag to allow the possibility to activate the ZS offline applied to all crystals

### PR DESCRIPTION
**Pull request by amassiro**
Allow ECAL pfrechit thresholds eta dependent in all regions, disregarding if they have been read in Zero Suppression (ZS) of Full Readout (FR).

In the previous version we could activate these thresholds only in ZS regions, or de-activate the application of the thresholds everywhere.

With this PR we can activate the thresholds everywhere, by means of the boolean: "applySelectionsToAllCrystals"

### CODE REVIEW

**Comment by amassiro** [comment]
@argiro @crovelli @emanueledimarco

**Comment by slava77** [comment]
the same functionality can already be achieved and is already used by using ``` srFlags = cms.InputTag("") ```
What is new functionally in this PR?

Please note that the feature has to be integrated in the master branch first.
Also, please justify the need to update 10_0_X

**Comment by amassiro** [comment]
Unfortunately, that is not the case. 

If we set: 
    cms.InputTag("")
the thresholds are never applied.
This is due to the fact that just setting "" the test:
      return fullReadOut or pass(hit);
https://github.com/amassiro/cmssw/blob/ce2ffce36b59010e8fbc2b7c52a0f8098440dc63/RecoParticleFlow/PFClusterProducer/interface/PFRecHitQTests.h#L29

will be always true, since "fullReadout" is true, being set by:
https://github.com/amassiro/cmssw/blob/ce2ffce36b59010e8fbc2b7c52a0f8098440dc63/RecoParticleFlow/PFClusterProducer/interface/PFEcalBarrelRecHitCreator.h#L67
      bool hi = (useSrF ? isHighInterest(detid) : true);

(and similarly in EE rechit producer).

This has been observed "experimentally". I generated with high thresholds, and they were not applied.
With this fix, and setting the flag to "true" the thresholds are applied.

**Comment by slava77** [comment]
> Unfortunately, that is not the case.

Isn't the problem then in this line

``` bool hi = (useSrF ? isHighInterest(detid) : true); ```

that useSrF false should lead to "false" so that normal cuts are applied?

"useSrF" is a property of a full job, not something changing hit by hit.
In case useSrF is false, falling to "hi = true" is meaningless because it disables any selections completely.
So,  this is apparently a bug.
We should fix this instead of introducing a workaround.

**Comment by amassiro** [comment]
We want to intorduce a new feature.

The current version has:
1) apply threshold only in ZS thresholds -> if I define "useSrF" with some input tag
2) do not apply thresholds -> if I define "useSrF" as ""
3) apply threshold to all rechits -> by setting the newly introduced flag [this possibility was not available in the past]

I tested before what you are proposing 
bool hi = (useSrF ? isHighInterest(detid) : false);
and it definitely has the same effect of the current implementation, but it will remove the option (2).
I tried to maintain back-compatibility of the code.
I let @emanueledimarco comment on the details of why the code was written in such a way.

**Comment by slava77** [comment]
On 2/16/18 9:05 AM, Andrea Massironi wrote:
> We want to intorduce a new feature.
> 
> The current version has:
> 
>  1. apply threshold only in ZS thresholds -> if I define "useSrF" with
>     some input tag
>  2. do not apply thresholds -> if I define "useSrF" as ""

this can be achieved by setting empty thresholds or not using a QTest at
all.
I don't see a clear need to have a QTest that's known at configuration
level to do nothing.

>  3. apply threshold to all rechits -> by setting the newly introduced
>     flag [this possibility was not available in the past]
> 
> I tested before what you are proposing
> bool hi = (useSrF ? isHighInterest(detid) : false);
> and it definitely has the same effect of the current implementation, but
> it will remove the option (2).
> I tried to maintain back-compatibility of the code.
> I let @emanueledimarco <https://github.com/emanueledimarco> comment on
> the details of why the code was written in such a way.
> 
> —

**Comment by slava77** [comment]
The other aspect of this PR is that there is a bug in 10_0_X in PF selections.
Because the current thresholds of 0.08 EB and 0.3 EE do nothing due to this srFlags = "" not doing what we (at least me) mistakenly thought it should.
Did the ECAL RelVal validation sign off on this as OK for the latest 10_0_X?

**Comment by amassiro** [comment]
The gathering and seeding thresholds are >= than the ones defined here, done on purpose since the study of the different thresholds and effects on high level objects is still ongoing. But without this fix, or the one you propose, it cannot be performed.

The only effect here is the threshold applied to the pf-rechits that are not clustered.
Though I let object experts comments on their specific use of unclustered components (maybe in the isolation cone definition? Unclustered met?)

**Comment by slava77** [comment]
So, my preference now is to change the true to false in the absence of SR info.
Also, we need a master PR first.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@amassiro 

I'll run locally with "false" to see what the impact is.
If it's small, perhaps we fix it in the master and leave 10_0_X with your solution here which does not change the selection logic in PFEcalBarrelRecHitCreator

**Comment by slava77** [comment]
the failure in the test is due to hltParticleFlowRecHitECALUnseeded
This new parameter will need a customization.

After some thought, I'm convinced now that your solution is more appropriate in a bigger picture:
- it is more appropriate to make the choice of ignoring the SR flags in a specific PFRecHitQTests
- the PFEcalBarrelRecHitCreator should not decide for every possible QTest what to do with the SR flags

Eventually, the full solution will be to 
- restore reading of SRFlags in PFEcalBarrelRecHitCreator
- set the PFRecHitQTestECALMultiThreshold's applySelectionsToAllCrystals to true

This will actually restore the selections to what we had in 2016 as originally intended for 10_0_X; and it will also allow to still have extra flexibility if needed to apply other quality tests using SRFlags.

**Comment by slava77** [comment]
To follow up on https://github.com/cms-sw/cmssw/pull/22254#issuecomment-366301806
and https://github.com/cms-sw/cmssw/pull/22254#issuecomment-366317085

I see that the bug is latent in the current default configuration of PF: the extra PFRecHits are never used or are discarded by downstream code because the thresholds downstream are at least as high as the intended selections that had to be applied in particleFlowRecHitECAL.

So, there is nothing to fix in 10_0_X at this point.

@amassiro once you have a fix for the HLT parameters, please also make a PR to the master branch.

**Comment by amassiro** [comment]
HLT fix added, with also the possibility to perform threshold studies.

--customise HLTrigger/Configuration/customizeHLTforCMSSW.customiseForEcalTestPR22254Default

to trigger the HLT fix.

**Comment by silviodonato** [comment]
please test

**Comment by Martin-Grunewald** [comment]
Likely one should actually call ```customiseForEcalTestPR22254Default``` to modify the process object
(at the end of the customizeHLTforCMSSW file)

**Comment by Martin-Grunewald** [comment]
Would need a 10_1_X PR first....

**Comment by Martin-Grunewald** [comment]
Please fix this 10_0_X PR!

**Comment by Martin-Grunewald** [comment]
please test

**Comment by slava77** [comment]
@amassiro 

please update this PR to be in sync with the master version.

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by slava77** [comment]
backport of #22265

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/22254	afd050a
- fixes a latent bug in PF{EB,EE}RecHitCreator that didn't allow changing thresholds in PFRecHitQTestECALMultiThreshold; also introduces new alternative test scenarios for ECAL thresholds to be used first within TSG
- the changes are the same as in #22265 (ignoring some empty lines changes)
- jenkins tests pass and comparisons with the baseline show no differences

**Comment by Martin-Grunewald** [comment]
@fabiocos could you please merge?
Thanks!

**Comment by fabiocos** [comment]
+1

**Comment by Martin-Grunewald** [comment]
Hi @amassiro 

Just to check: the HLT customisation is NOT applied to ```hltParticleFlowRecHitECALForMuonsMFNoVtx```
Is this correct? You only apply it to:
``` ['hltParticleFlowRecHitECALUnseeded', 'hltParticleFlowRecHitECALL1Seeded', 'hltParticleFlowRecHitECALForMuonsMF', 'hltParticleFlowRecHitECALForTkMuonsMF']```

**Comment by amassiro** [comment]
"hltParticleFlowRecHitECALForMuonsMFNoVtx" is using a different QTest:

          name = cms.string( "PFRecHitQTestThreshold" )

We have not changed it, since it was as this also in 2017.

We have changed all the producers whose QTest in 2017 was "PFRecHitQTestECALMultiThreshold"

**Comment by Martin-Grunewald** [comment]
What does this comment mean in the HLT customisation? Something forgotten or to be done later in another PR?

```# particleFlowRechitECAL new default value "false" flag to be added                                              ```

**Comment by amassiro** [comment]
Something forgotten, sorry about it.

**Comment by Martin-Grunewald** [comment]
Depending on what it is and for both 10_0 and 10_1 we can do it directly in ConfDB rather than via PRs and customisation functions. It depends what the change is!

**Comment by amassiro** [comment]
In this PR we have both introduced the possibility to apply selections at pf-rechit level eta dependent, and we have defined a set of reasonable thresholds that will be studied by POGs for performance of different objects.

The change in the code requires an additional input tag to be handled by the producer (a simple bool) that was not there in the HLT part and that would make the relval matrix crash without the customization. That is why we added the customization function.
If this can be fixed once and for all via ConfDB as well, this is very good.

**Comment by Martin-Grunewald** [comment]
Additional parameters are trivially to handle with a fillDescriptions method (for all parameters).
Then you could just add it in the code, with a defaults value, and be done with it.

**Pull request merged**
