### PR TITLE
(fwd-port) HTXS to master

### PR DESCRIPTION
**Pull request by perrozzi**
https://twiki.cern.ch/twiki/bin/viewauth/CMS/HiggsTemplateCrossSection
needed to put the HTXS categorization into nanoAOD
@arizzi @gpetruc @dsperka

### CODE REVIEW

**Comment by perrozzi** [comment]
please test

**Comment by perrozzi** [comment]
+1

**Comment by perrozzi** [comment]
backport of https://github.com/cms-sw/cmssw/pull/20683

**Comment by arizzi** [comment]
this is useful for NanoAOD, please consider merging before next 94X

**Comment by perrozzi** [comment]
please test

**Comment by perrozzi** [comment]
+1

**Comment by davidlange6** [comment]
merge

**Pull request merged**
