### PR TITLE
Make units dd4hep-dependent in Cocoa

### PR DESCRIPTION
**Pull request by ghugo83**
Make units dd4hep-dependent.
This is in preparation of DD4hep unit change.

@cvuosalo @civanch @ianna 

Tested against regressions.

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by cvuosalo** [comment]
Looks good.

**Comment by yuanchao** [comment]
+1
* migrate from cmsunits to dd4hep units.
* static build warnings not part of the PR

**Comment by qliphy** [comment]
+1

**Pull request merged**
