### PR TITLE
delete unused headers

### PR DESCRIPTION
**Pull request by davidlange6**
As raised in #31505 

none of these files are used in any way (well some are used by others that themselves are unused) - unused means not used in any compilation unit or test.

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by slava77** [comment]
@davidlange6 
for the reco files, I think that in some cases some triage is needed, to OK the removal or not, rather than blindly having all removed.
Please break this PR in pieces so that non-reco subsystems are done separately.
Thank you.

**Comment by agrohsje** [comment]
+1

**Comment by slava77** [comment]
> @davidlange6
> for the reco files, I think that in some cases some triage is needed, to OK the removal or not, rather than blindly having all removed.
> Please break this PR in pieces so that non-reco subsystems are done separately.
> Thank you.

**Comment by slava77** [comment]
> > @davidlange6
> > for the reco files, I think that in some cases some triage is needed, to OK the removal or not, rather than blindly having all removed.
> > Please break this PR in pieces so that non-reco subsystems are done separately.
> > Thank you.

**Comment by slava77** [comment]
> > > @davidlange6
> > > for the reco files, I think that in some cases some triage is needed, to OK the removal or not, rather than blindly having all removed.
> > > Please break this PR in pieces so that non-reco subsystems are done separately.
> > > Thank you.

**Comment by slava77** [comment]
> > > > @davidlange6
> > > > for the reco files, I think that in some cases some triage is needed, to OK the removal or not, rather than blindly having all removed.
> > > > Please break this PR in pieces so that non-reco subsystems are done separately.
> > > > Thank you.

IIRC, from the ORP last week we can expect a split here.
what is the status of this?
@davidlange6 please clarify.
Thank you.

**Comment by slava77** [comment]
> > > > > @davidlange6
> > > > > for the reco files, I think that in some cases some triage is needed, to OK the removal or not, rather than blindly having all removed.
> > > > > Please break this PR in pieces so that non-reco subsystems are done separately.
> > > > > Thank you.
> 
> IIRC, from the ORP last week we can expect a split here.
> what is the status of this?
> @davidlange6 please clarify.
> Thank you.

**Comment by slava77** [comment]
> IIRC, from the ORP a few weeks ago we can expect a split here.
> what is the status of this?
> @davidlange6 please clarify.
> Thank you.

**Comment by slava77** [comment]
@davidlange6 
please clarify on the status of this PR.
Thank you.

**Comment by slava77** [comment]
-1

an update is necessary anyways to pass the tests

**Comment by silviodonato** [comment]
Feel free to use "Ready to review" as soon as there are news

**Pull request closed without merging**
