### PR TITLE
[14.1.X] Update `test_MC_*_setup` unit tests

### PR DESCRIPTION
**Pull request by mmusich**
backport of https://github.com/cms-sw/cmssw/pull/46438

#### PR description:

As discussed in https://github.com/cms-sw/cmssw/issues/45888#issuecomment-2332194431 these unit tests failed to catch an issue when running the reconstruction of data coming out the HLT produced in an earlier release. 
I am updating the tests to use the latest and greatest ingredients as of Oct 18, 2024 (both in terms of releases and GlobalTags) as well as activating catching failures in the HLT step when it's failing in the target release.
Additionally for the RECO step for the 2022 use the customization function `fixReading_12_4_X_Files` as suggested at https://github.com/cms-sw/cmssw/issues/45888#issuecomment-2331984194. 

#### PR validation:

`scram b runtests` runs fine in this package

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

verbatim backport of https://github.com/cms-sw/cmssw/pull/46438 to 14.1.X

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by AdrianoDee** [comment]
+pdmv
[All the test succeeded](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-2ffdd9/42293/unitTests/success.html)

**Comment by Moanwar** [comment]
+Upgrade

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
@cmsbuild, please test
   * let's see if it was a glitch

**Comment by AdrianoDee** [comment]
+pdmv

**Comment by Moanwar** [comment]
+Upgrade

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
