### PR TITLE
Protecting E/gamma Scale and Smearing from "nan" energies : 94XMAOD

### PR DESCRIPTION
**Pull request by Sam-Harper**
94XMAOD backport of  https://github.com/cms-sw/cmssw/pull/24093 need to fix a very rare crash in the reminiAOD

### CODE REVIEW

**Comment by slava77** [comment]
@fabiocos 
once you change the target to 9_4_X, please start the tests
Thank you.

**Comment by fabiocos** [comment]
@Sam-Harper @slava77 changing the base picked lots of older commits, although the change is unmodified, probably the branch can be simply rebased on top of 9_4_X

**Comment by fabiocos** [comment]
please test

**Comment by Sam-Harper** [comment]
ah this was meant for the MAOD branch, let me make a 94X PR, 10mins

**Comment by Sam-Harper** [comment]
done, I'm closing this PR as its now replaced with https://github.com/cms-sw/cmssw/pull/24151

**Comment by fabiocos** [comment]
please abort

**Pull request closed without merging**
