### PR TITLE
fix clang errors and warnings in RecoTracker/TkDetLayers

### PR DESCRIPTION
**Pull request by VinInn**
No clue how it was compiling under gcc

### CODE REVIEW

**Comment by Dr15Jones** [comment]
I had thought a fix was already in the standard CMSSW_7_4_X branch. I think the real problem is the clang builds are not using the code from the development branch.

**Comment by davidlt** [comment]
Works as-is in `CMSSW_7_4_DEVEL_X_2015-01-16-0200` with Clang pre-3.6
```
$ git cms-addpkg RecoTracker/TkDetLayers
$ scram b vclean && scram b -v -k -j 32 2>&1 COMPILER=llvm 2>&1 USER_CXXFLAGS='-Wno-unused-local-typedef' | tee b.log
$ grep 'error:' b.log
clang: error: linker command failed with exit code 1 (use -v to see invocation)
$ git diff origin/CMSSW_7_4_X..origin/CMSSW_7_4_DEVEL_X | wc -l
0
```
There are some link issues only, will look into it a bit later. Other than that, builds fine as-is in plain CMSSW.

So these changes need some good reviews before merging.

**Comment by slava77** [comment]
so, is this PR  actually a fix to an issue or is it not necessary anymore and can be closed?

**Comment by degano** [comment]
@cmsbuild please test

**Comment by degano** [comment]
@cmsbuild please test

**Comment by VinInn** [comment]
I think we close this, as CLANG will now be a clone of TRUNK

**Pull request closed without merging**
