### PR TITLE
DD4hep: TrackerMaterialAnalysis Addresses #29610

### PR DESCRIPTION
**Pull request by vargasa**
#### PR description:

Addresses #29610

### CODE REVIEW

**Comment by vargasa** [comment]
FYI: @silviodonato, @boudoul , @cvuosalo

**Comment by silviodonato** [comment]
please test

**Comment by cvuosalo** [comment]
@vargasa  Looks good. Thanks for taking care of this issue.

**Comment by civanch** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
