### PR TITLE
add MET receipe

### PR DESCRIPTION
**Pull request by TaiSakuma**
The MET group is planning to close the MET recipe by integrating it into either the CMSSW releases or the PAT recipes [https://github.com/cms-met/cmssw/issues/1].

This PR contains the commits in the current MET recipe. With this PR in the CMSSW, we can close the MET recipe for 5_3_X.

The commit https://github.com/TaiSakuma/cmssw/commit/ac3814e10a7b1af43e271b687eeee3c394147242?diff=split edits a file under DataFormats/METReco but doesn't change the data format. It only adds friend operators and won't require to update the checksum.  I am not sure if that is ok.

### CODE REVIEW

**Comment by monttj** [comment]
Looking at the file changes, I would ask the same question regarding these files:
JetMETCorrections/Type1MET/plugins/CorrectedCaloMETProducer2.cc and JetMETCorrections/Type1MET/plugins/CorrectedPFMETProducer2.cc:

But it compiles ok with the lasted IB, CMSSW_5_3_X_2015-01-11-0200 and  the pull request does not affect PAT workflow.

**Comment by monttj** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Comment by TaiSakuma** [comment]
This PR has been merged. But I will write the answer to question about these two files for the record.

    JetMETCorrections/Type1MET/plugins/CorrectedCaloMETProducer2.cc
    JetMETCorrections/Type1MET/plugins/CorrectedPFMETProducer2.cc

These two files were originally merged to CMSSW_6_2_0_pre5. The addition of these two files were [published in CmsTC](https://hypernews.cern.ch/HyperNews/CMS/get/pkgAnnounce/138337.html) and [approved](https://hypernews.cern.ch/HyperNews/CMS/get/pkgAnnounce/138451.html) in March 2013. This was the task *generalize MET correction  (1st step)* described on [CMS.METDevelopmentPlan] (https://twiki.cern.ch/twiki/bin/viewauth/CMS/METDevelopmentPlan).

Later in [CMSSW_7_0_0_pre11](https://github.com/cms-sw/cmssw/releases/tag/CMSSW_7_0_0_pre11), these two files were renamed respectively

    JetMETCorrections/Type1MET/plugins/AddCorrectionsToCaloMET
    JetMETCorrections/Type1MET/plugins/AddCorrectionsToPFMET

with the PR https://github.com/cms-sw/cmssw/pull/1823.

This PR used the original names because this branch has been being used by many users and renaming them would break many configuration files already being used.

**Pull request merged**
