### PR TITLE
Global tag updates for legacy reprocessing 2016

### PR DESCRIPTION
**Pull request by arunhep**
# Summary of changes in Global Tags

Changes are same in both RunI data and RunII data
## RunII data & RunI data

   * **RunI & RunII Offline processing** : [80X_dataRun2_2016LegacyRepro_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_dataRun2_2016LegacyRepro_v3) as [80X_dataRun2_v19](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_dataRun2_v19) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/80X_dataRun2_2016LegacyRepro_v3/80X_dataRun2_v19):
      * Change in SiPixel Templates, GenError and Lorentz Angle. [Sign-off talk](https://indico.cern.ch/event/586735/contributions/2364051/attachments/1374680/2087542/20161121_AlCaDB_EOYRECO.pdf).

      * Change in SiStrip Gain2 calibration, mostly adjustment of IOVs and a new IOV added. [Announced here](https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2825.html) [signed-off talk](https://indico.cern.ch/event/586738/contributions/2397203/) 

      * Tracker alignment, APEs and surface deformations updated. [signed-off talk](https://indico.cern.ch/event/586738/contributions/2387635)

      * Update of BeamSpot corresponding to the changes in tracker alignment package. [signed-off talk](https://indico.cern.ch/event/592611/contributions/2435744)

      * Update of muon alignment and APEs. [announcement](https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2884/1/1/1.html)

      * Update of DtTrig. [Announced here](https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2731/1.html)

      * Update of whole ECAL package. [signed-off talk](https://indico.cern.ch/event/626460/contributions/2529699/). Changes includes update of ECAL pedestals, ADCtoGeV, ECAL alpha values, pulse shapes, time calibrations, channel status of both ECAL and ES, ECAL Laser corrections, ECAL and ES Channel quality, ECAL intercalibration and ES intercalibration.

      * Update of HCAL gains and response corrections. [announced here](https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2836.html)

     * Update of global alignment

     * Update of L1 caloParam tag and addition of L1 muon param tags. [announced here](https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2878/1/1/3/1/1/1/1/1/1.html)

* **RunII Offline relval processing** : [80X_dataRun2_relval_v19](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_dataRun2_relval_v19) as [80X_dataRun2_relval_v18](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_dataRun2_relval_v18) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/80X_dataRun2_relval_v19/80X_dataRun2_relval_v18):
      * all the legacy conditions mentioned above has been updated here as well.

### CODE REVIEW

**Comment by arunhep** [comment]
please test

**Comment by arunhep** [comment]
please test

**Comment by davidlange6** [comment]
+1

**Comment by franzoni** [comment]
thanks , @davidlange6 
( we were about to email warning about being done)

**Pull request merged**
