### PR TITLE
Cast legacy CLCT trigger patterns in Run-3 pattern format (CCLUT-2)

### PR DESCRIPTION
**Pull request by dildick**
#### PR description:

This PR casts the legacy CSC trigger patterns in the Run-3 CSC pattern format.  The old patterns are defined as 1D arrays with length 42. This will change to 2D vector with width 11 and depth 6. More details can be found here [1], page 3-8. The Run-3 patterns have previously been defined in #28600. Because this PR merely replace the 1D array with a 2D vector, there should be no changes in the output. 

I also remove very outdated code (pre-2007) in the CSCCommonTrigger and CSCTrackFinder packages (`NUM_CLCT_PATTERNS_PRE_TMB07`)

[1]
https://indico.cern.ch/event/882849/contributions/3722003/attachments/1977056/3296463/CSCTriggerPlans2020_SvenDildick_L1TDPG.pdf

#### PR validation:

Tested with wf 22034.0.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

FYI @tahuang1991

### CODE REVIEW

**Comment by dildick** [comment]
Hi, can someone initiate the tests?

**Comment by smuzaffar** [comment]
please test

**Comment by rekovic** [comment]
These are really old patterns recast in the new format.
We are pending check on the Run2 data (2018D) by re-emulating and ensure the stubs are unchanged.

**Comment by silviodonato** [comment]
Do you have any news on this PR?

**Comment by dildick** [comment]
Hi Silvio, sorry I'm still working on this. I plan to have an update by next week.

**Comment by dildick** [comment]
@silviodonato I looked at re-emulated 2018 data last week. I noticed significant differences for CLCTs. It was pointed out to me that there is a bug in the pid=2 pattern. I'm looking into it now.

**Comment by dildick** [comment]
```    
// pid=2: right-bending (large)
    {
        {0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1},
        {0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0},
        {0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0},
        {0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0},
        {0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0},
        {1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 11},
    },
``` 

should be
```
    // pid=2: right-bending (large)
    {
        {0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1},
        {0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0},
        {0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0},
        {0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0},
        {0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0},
        {1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 11},
    },
```

**Comment by dildick** [comment]
I made a few validation plots by re-emulating the ALCT/CLCT and LCT on 25000 events in the file block ``/ZeroBias/Run2018D-v1/RAW#5dd68d0d-5a62-4bfe-9065-cc0cd92e3f3e``. Black are the unpacked ALCT/CLCT and LCT. Red are the re-emulated ALCT/CLCT and LCT from RAW digis.

**Comment by dildick** [comment]
comparison_clct_cfeb_mAll
comparison_clct_cfeb_pAll
comparison_clct_keyStrip_mAll
comparison_clct_keyStrip_pAll
comparison_clct_pattern_mAll
comparison_clct_pattern_pAll
comparison_clct_quality_mAll
comparison_clct_quality_pAll
comparison_clct_strip_mAll
comparison_clct_strip_pAll

**Comment by dildick** [comment]
comparison_alct_keywire_mAll
comparison_alct_keywire_pAll
comparison_alct_quality_mAll
comparison_alct_quality_pAll

**Comment by dildick** [comment]
The disagreement for ALCTs is between 1-3 in 10,000.

**Comment by dildick** [comment]
comparison_lct_bend_mAll
comparison_lct_bend_pAll
comparison_lct_cscID_mAll
comparison_lct_cscID_pAll
comparison_lct_keywire_mAll
comparison_lct_keywire_pAll
comparison_lct_pattern_mAll
comparison_lct_pattern_pAll
comparison_lct_quality_mAll
comparison_lct_quality_pAll
comparison_lct_strip_mAll
comparison_lct_strip_pAll

**Comment by dildick** [comment]
@rekovic These plots look fine. 

As you can see, there are small disagreements in the ALCT/CLCT and LCT plots. We're working on resolving differences between the emulator and the firmware.

**Comment by dildick** [comment]
@rekovic Could you rerun the tests, please? Thanks.

**Comment by silviodonato** [comment]
please test

**Comment by dildick** [comment]
@silviodonato It seems the tests were not initiated.

**Comment by silviodonato** [comment]
@cmsbuild ping

**Comment by silviodonato** [comment]
@cmsbuild  please test

**Comment by dildick** [comment]
Plots looks good. The differences between emulator and firmware are in >90% coming from ME1/1. That is something we plan to improve during LS2.

**Comment by dildick** [comment]
@rekovic Could you sign, please?

**Comment by silviodonato** [comment]
Kind reminder to @benkrikler @rekovic

**Comment by rekovic** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Comment by dildick** [comment]
Thank you Vladimir!

**Pull request merged**
