### PR TITLE
Backport to 12_3_X for CSC unpacking update PR#37279

### PR DESCRIPTION
**Pull request by barvic**
#### PR description:
Backport to 12_3_X for CSC unpacking update PR #37279

#### if this PR is a backport please specify the original PR and why you need to backport that PR:
Would need to have those unpacking updates deployed at P5 soon as possible for proper unpacking of CSC ALCT/(O)TMB data with new versions of firmware with enabled Run3 features

### CODE REVIEW

**Comment by perrotta** [comment]
backport of #37279

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
+1
- Master version of this PR already merged since CMSSW_12_4_X_2022-04-06-1100

**Comment by clacaputo** [comment]
+reconstruction

- https://github.com/cms-sw/cmssw/pull/37279 backport
- no reco changes

**Comment by perrotta** [comment]
+1

**Pull request merged**
