### PR TITLE
[14.0.X] remove unused `DoubleSensGeomDet` for ph-2 InnerTracker

### PR DESCRIPTION
**Pull request by mmusich**
backport of #45993

#### PR description:

This PR fixes the CMSSW issues https://github.com/cms-sw/cmssw/issues/43097 and https://github.com/cms-sw/cmssw/issues/45792 removing the `DoubleSensGeomDet` introduced for phase-2 Inner Tracker modules (T33 tracker geometry and following T35, T36, T37, T38 and T39) but actually not used in the code (and unlikely to be used in future).

No changes expected for the output.

#### PR validation:

Tested on:
   * issue:  https://github.com/cms-sw/cmssw/issues/43097
     `cmsRun Fireworks/Geometry/python/dumpRecoGeometry_cfg.py tag=2026 version=D110`
   * issue: https://github.com/cms-sw/cmssw/issues/45792
     `cmsRun Alignment/TrackerAlignment/test/Misalignments/createRandomlyMisalignedGeometry_Phase2_cfg.py`
   * D110: `runTheMatrix.py --what upgrade -l 29607.0`

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

This PR is a backport in 14_0_X of the bug-fix https://github.com/cms-sw/cmssw/pull/45993
Needed to test TkAlignment on MC samples produced in 14_1_X with 2026D110/T35 geometry

### CODE REVIEW

**Comment by mmusich** [comment]
type bug-fix

**Comment by mmusich** [comment]
test parameters:
   * workflow_opts = -w upgrade
   * workflows = 29607.0

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by alja** [comment]
+1

**Comment by perrotta** [comment]
+alca

**Comment by civanch** [comment]
+1

**Comment by jfernan2** [comment]
+1

**Pull request merged**
