### PR TITLE
[DD4hep] Allow full regular expression in evaluation

### PR DESCRIPTION
**Pull request by ianna**
#### PR description:

* Allow selection such as ```//..HE.*```

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by ianna** [comment]
@bsunanda - FYI

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by ianna** [comment]
@bsunanda - I've added a ```printFilter``` member that allows to inspect the content of the selections. BTW, you are using two instances of ```DDFilteredView```. This could pose a problem for a ```TGeoIterator```. I'd suggest to restructure the code so that the ```Detector``` is walked once.

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by ianna** [comment]
> #### PR description:
> * Allow selection such as `//..HE.*`
> 

@cvuosalo, @civanch and @bsunanda - FYI, disabling this type of selection was intentional to speedup iteration. It's **not** a bug, it's a feature.

The underling structure on which we iterate is different. It's a **fully expanded** geometry tree. I'd recommend to tighten selections in the xml files. This kind of modification would not alter geometry and is backward compatible. It will speed up DD selections as well.

Please, look at the DT geometry specs as an example.

**Pull request closed without merging**
