### PR TITLE
Porting modifications from 74

### PR DESCRIPTION
**Pull request by dinardo**
Porting modifications from 74

### CODE REVIEW

**Comment by deguio** [comment]
+1
ciao mauro,
the PR can be merged. keep in mind that we rely on the fact that the code is forced to run ST in the online i.e. this module shouldn't never go to any offline sequence as it is (it would give unpredictable results).

if you want the code to be tested in the playback system, please edit the twiki at:
https://twiki.cern.ch/twiki/bin/viewauth/CMS/DQMP5TagCollector
ciao,
F.

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
-1
ciao mauro,
since this is not merged yet, you can update this PR according to the comments at #10918 
thanks,
F.

**Comment by dinardo** [comment]
OK done.
I've rolled back as you suggested.
Sorry about that,

- Mauro.

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1

**Pull request closed without merging**
