### PR TITLE
Run3-gex108XD Modify muon numbering, adding scenarios for the corretced Run3 geometry in CMSSW version 12_2_X

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Modify muon numbering, adding scenarios for the corretced Run3 geometry. Backport the 2 PR's #36654, #36679. Need a fresh PR for GT to make it work

#### PR validation:

To be tested with the PR's #36740, #36780, #36781 and #36785

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Backporting the PR's already in the master to make the correct Run3 geometry scenario

### CODE REVIEW

**Comment by francescobrivio** [comment]
-1

@bsunanda I don't think copy-pasting 12_3_X GTs in 12_2_X is the correct way to go.
If the new geometry tags for 12_2_X are available, please @cms-sw/geometry-l2 let us know and we will create the 12_2_X  Run3 MC GTs that contain the updated geometry.

**Comment by tvami** [comment]
Hi @bsunanda please include [12_2_X] in the PR title, thanks!

**Comment by tvami** [comment]
backport of https://github.com/cms-sw/cmssw/pull/36554

**Comment by tvami** [comment]
backport of https://github.com/cms-sw/cmssw/pull/36679

**Comment by francescobrivio** [comment]
@cmsbuild please test with #36740,#36780,#36781,#36785

**Comment by bsunanda** [comment]
@tvami I have made the changes as suggested by you

**Comment by perrotta** [comment]
Backport of #36654, #36679
(please check, and update the PR description with it)

**Comment by civanch** [comment]
@bsunanda , are differences expected?

**Comment by bsunanda** [comment]
@civanch The geometry is changed  here. So we expect changes in all run3 scenarios

**Comment by slomeo** [comment]
> @civanch The geometry is changed here. So we expect changes in all run3 scenarios

@bsunanda I'm checking Run3 Geometry in CMSSW_12_3__X_2022-01-23-2300, do I have to 
add this PR to continue my job?

**Comment by bsunanda** [comment]
@slomeo This is a PR for CMSSW_12_2_X. For 12_3_X all relevant PR's are merged to the latest IB and also to 12_3_0_pre4

**Comment by cvuosalo** [comment]
@bsunanda Please correct PR description: backport of #36654, not #36554.

**Comment by bsunanda** [comment]
@cvuosalo Done that

**Comment by cvuosalo** [comment]
+1

**Comment by srimanob** [comment]
+Upgrde

Backport of Run-3 geometry.

**Comment by tvami** [comment]
Hi @perrotta @qliphy @bsunanda 
I see that CMSSW_12_0_0_patch1 was started to be built, but wasnt this PR supposed to be included there?

**Comment by perrotta** [comment]
> Hi @perrotta @qliphy @bsunanda I see that CMSSW_12_0_0_patch1 was started to be built, but wasnt this PR supposed to be included there? I guess even if the answer is yes, we should not stop the build of CMSSW_12_0_0_patch1, it is still good for the AlCa purposes of testing the new PCL workflows

Hi @tvami 
The backport of the PRs to implement the fixed Run3 geometry must wait for some green light from the validation of pr4 s pre3. Moreover, there is also the github issue #36786 to be considered, and if a fix is needed it has to be implemented in the master first, and then backported.
Therefore, we built CMSSW_12_2_0_patch1 as an intermediate step that integrates all fixes requested for the T0 replay of 12_2, and make as such that release hopefully suitable for being deployed at P5.
Another 12_2_1 will follow with the geometry updates as soon as possible

**Comment by tvami** [comment]
Thanks @perrotta sounds good!

**Comment by perrotta** [comment]
@bsunanda, please include Configuration/Eras/python/Modifier_run3_geomOld_cff.py in this backport PR (now mistakenly included in #36780, but `run3_geomOld` is needed here, instead)

**Comment by civanch** [comment]
@cvuosalo , @srimanob, is this PR OK?

**Comment by qliphy** [comment]
please test with #36740,#36780,#36781,#36785

**Comment by srimanob** [comment]
+Upgrade

For the upgrade side, checking on dict2021 shows identical with master. The backport looks OK and changes are as expected as in the master https://github.com/cms-sw/cmssw/pull/36679 for Run-3.

**Comment by cvuosalo** [comment]
+1

**Comment by perrotta** [comment]
+operations

**Comment by perrotta** [comment]
+1

**Pull request merged**
