### PR TITLE
[12.1.X] Oracle test: Use fake/random DB name

### PR DESCRIPTION
**Pull request by smuzaffar**
backport of https://github.com/cms-sw/cmssw/pull/41630

Fix oracle unit test. We know why test is failing, so it is really not required to get this change in this release cycle. Feel free to reject/close it.

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by tvami** [comment]
+1

**Comment by perrotta** [comment]
+1

**Comment by perrotta** [comment]
merge

**Pull request merged**
