### PR TITLE
Introduce TrackingEffFromHitPatternClientConfigZeroBias and use it for the trackingZeroBias DQM Harvesting sequence

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

The title says it all.
We've been requested from central DQM to investigate the messages related to:
```
%MSG-e DQMGenericClient:  DQMGenericClient:trackingEffFromHitPattern@endRun  07-Oct-2020 09:19:57 CEST End Run: 194533
 DQMGenericClient::findAllSubdirectories ==> Missing folder Tracking/TrackParameters/highPurityTracks/pt_1/HIP_OOT_noINpu !!!
%MSG
```
in the relval workflows (see e.g. this  [log](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-3e7a51/9765/runTheMatrix-results/4.53_RunPhoton2012B+RunPhoton2012B+HLTD+RECODR1reHLT+HARVESTDR1reHLT/step4_RunPhoton2012B+RunPhoton2012B+HLTD+RECODR1reHLT+HARVESTDR1reHLT.log) ).
It turns out this is related to the fact that the triggers populating the `ME`s in the special folders (i.e. `FirstCollisionInTrain` `FirstCollisionAfterAbortGap`, `FirstBXAfterTrain`) are not present in any other dataset than `ZeroBias`. 
So the `TrackingEffFromHitPatternClientConfig` (configured in order to look for the special folders) has been cloned and used for the `trackingZeroBias ` DQM Harvesting sequence .

#### PR validation:

Tested in `CMSSW_11_2_X_2020-10-08-1100`:
* `runTheMatrix.py -l 4.53 -t 4 -j 8` : warning messages in step4 are gone.
* `runTheMatrix.py -l 136.892 -t 4 -j 8`: using the `DQMHarvestTrackingZeroBias` sequence, runs smoothly.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Not a backport, no backport needed.

cc:
@mtosi, @sroychow, @arossi83, @tsusa

### CODE REVIEW

**Comment by mmusich** [comment]
tes parameters:
workflows = 4.53, 136.892

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by jfernan2** [comment]
Thank you very much for this PR @mmusich 
Could it be possible/easy to remove also this one:
MSG-e DQMGenericClient:  DQMGenericClient:postProcessorTrack@endRun  08-Oct-2020 18:59:48 CEST End Run: 1
 DQMGenericClient::findAllSubdirectories ==> Missing folder Tracking/TrackBHadron !!!

**Comment by mmusich** [comment]
@jfernan2 
yes I noticed that message as well. That requires a different fix in different files. I would suggest to proceed with this one for the time being if you agree. I'll follow up to the other one later.

**Comment by jfernan2** [comment]
+1

**Comment by qliphy** [comment]
+1

**Comment by mmusich** [comment]
@jfernan2 

> Could it be possible/easy to remove also this one:
MSG-e DQMGenericClient: DQMGenericClient:postProcessorTrack@endRun 08-Oct-2020 18:59:48 CEST End Run: 1
DQMGenericClient::findAllSubdirectories ==> Missing folder Tracking/TrackBHadron !!!

for the record that's addressed at: https://github.com/cms-sw/cmssw/pull/31785

**Comment by jfernan2** [comment]
Thanks a lot!

**Pull request merged**
