### PR TITLE
Run3-alca230 Enable to submit the HCAL calibration macros in a batch mode

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Enable to submit the HCAL calibration macros in a batch mode

#### PR validation:

Test the executable in batch mode

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by ChrisMisan** [comment]
type hcal

**Comment by ChrisMisan** [comment]
please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by tvami** [comment]
+alca

**Pull request merged**
