### PR TITLE
switch RAW repack compression to LZMA-4

### PR DESCRIPTION
**Pull request by slava77**
Based on tests by @mandrenguyen this saves 15% in output size.

@mandrenguyen please provide more detail if available.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
backport of #25067

**Comment by mandrenguyen** [comment]
Some details on the test.
I ran 100 minimum bias PbPb MC events with the following driver options:

--conditions auto:phase1_2018_realistic_hi -s DIGI:pdigi_hi,L1,DIGI2RAW --datatier RAW --pileup HiMixNoPU -n 100 --era Run2_2018_pp_on_AA --eventcontent RAW --nThreads 8 --filein /store/himc/HINPbPbSpring18GS/Hydjet_Quenched_Drum5Ev8_PbPbMinBias_5020GeV_2018/GEN-SIM/100X_upgrade2018_realistic_v10_ext1-v1/40001/FED5A0AA-8EA8-E811-812C-D8D385FF18C4.root 

The size of the raw data from edmEventSize -v may be found below, for zlib-9 (default) and lzma-4
FEDRawDataCollection_rawDataCollector__DIGI2RAW. 1.55188e+06 995289
FEDRawDataCollection_rawDataCollector__DIGI2RAW. 1.553e+06 857158
First number is uncompressed, 2nd number is compressed

One can  see that the compressed size is 15% smaller in the second compression scheme.

**Comment by fabiocos** [comment]
hold

based on https://hypernews.cern.ch/HyperNews/CMS/get/tier0-Ops/2055/1/3/1/1/1/1/1/1/1/1/1/2/1/1/1/1.html

**Comment by slava77** [comment]
Here is an updated using HI data using CMSSW_10_3_1_patch1

- 326622 [taken with /cdaq/physics/Run2018HI/v1.4.0/HLT/V2 on Nov 12]  LS 22+23 stream HIPhysicsMinimumBias0 writes one output HIMinimumBias0 RAW (8530 events total)
    - zlib-9 [default]: 0.41 s/ev; 989.7 kiB/ev ; 7.9 GB file size
    - lzma-4: 0.86 s/ev (2.07 of the baseline) 769.5 kiB/ev  (0.78 of the baseline); 6.2 GB file size
- 326722 [taken with /cdaq/physics/Run2018HI/v1.4.0/HLT/V9 on Nov 15]  LS 42 stream HIPhysicsMinimumBias0 writes one output HIMinimumBias0 RAW (7468 events total)
    - zlib-9 [default]: 0.41 s/ev 946.2 kiB/ev; 6.6 GB file size
    - lzma-4: 0.81 s/ev (1.96 of the baseline) 734.6 kiB/ev (0.78 of the baseline); 5.2 GB file size

It looks like the CPU cost increase is smaller compared to the test of repacking high-pileup data (\~2.0 here and \~3.0 there) and the compression ratio is a bit better (0.78 here and 0.83 there).

@mandrenguyen @icali

**Comment by fabiocos** [comment]
@slava77 I imagine we might close this PR at this point

**Comment by icali** [comment]
Hi, fine with me to close this PR. Potentially we can review again the situation in a couple of year.

**Comment by slava77** [comment]
ok, closing

**Pull request closed without merging**
