### PR TITLE
Ecal laser hdf5 support

### PR DESCRIPTION
**Pull request by grasph**
#### PR description:

Adds support for HDF5 input format to the ECAL laser transparency correction import tool.

#### PR validation:

Code validated with a test input file and the CalibCalorimetry/EcalTrivialCondModules/test/ecalLaserCondTools_cfg.py CMSSW steering file.

### CODE REVIEW

**Comment by grasph** [comment]
Adding @fcouderc to the thread.

**Comment by christopheralanwest** [comment]
please test

**Comment by yuanchao** [comment]
+1

* added HDF5 and MessageLogger
* WF matrix tests and unit tests are all passed
* python modules compile successfully
* static build warnings are not part of the modification

**Comment by qliphy** [comment]
+1

**Comment by grasph** [comment]
Hello,

Sorry for my ignorance, in which release that will go if no backporting PR are done ? The document says "the latest development release".  Does it mean ? next CMSSW_11_3_X , CMSSW_11_4_0, or CMSSW_12_0_0? 

Philippe.

**Comment by qliphy** [comment]
This will be included in 11_3_0_pre3 https://twiki.cern.ch/twiki/bin/view/CMS/CMSSW_11_3_0

**Comment by grasph** [comment]
Perfect. Thanks @qliphy for your quick answer and the link to the twiki.

**Pull request merged**
