### PR TITLE
Cleaning TkMaps code and adding Strip Merged Bad Channels

### PR DESCRIPTION
**Pull request by fioriNTU**
Modify the code to have merged SiStrip bad channels from PCL, FED errors and RunInfo. Modified and cleaned TlMap creation script. These tools are used Offline by the Tracker shifters, nothing is modified in standard Strip DQM workflow

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
@fioriNTU this doesn't merge anymore. Since you need to re-base what about taking the occasion to implement the suggestions in https://github.com/cms-sw/cmssw/pull/13664?
Thanks,
M.

**Comment by fioriNTU** [comment]
Well, ok, will do it as soon as the others developments are ready. thanks.

Il 21/03/2016 10.29, Marco Musich ha scritto:
>
> @fioriNTU <https://github.com/fioriNTU> this doesn't merge anymore. 
> Since you need to re-base what about taking the occasion to implement 
> the suggestions in #13664 <https://github.com/cms-sw/cmssw/pull/13664>?
> Thanks,
> M.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub 
> <https://github.com/cms-sw/cmssw/pull/13655#issuecomment-199191300>
>



---
Questa e-mail è stata controllata per individuare virus con Avast antivirus.
https://www.avast.com/antivirus

**Comment by deguio** [comment]
-1

**Comment by mmusich** [comment]
-1

**Pull request closed without merging**
