### PR TITLE
Tracker DetId Shifts from XML Parameters

### PR DESCRIPTION
**Pull request by ianna**
- Replace configuration fragments with xml description

### CODE REVIEW

**Comment by ianna** [comment]
@venturia - as discussed earlier, this is a first step in DB-ization of configurable parameters for Tracker. So far I've replaced DetId shifts only. I can see that you've used them only for geometries built from DDD. Should PGeometricDet builder be adjusted to use the shifts as well? If needed, the PTrackerParameters record (with DetId shifts) will be available in a GT. 

The next step is to clean up other configurable constants which are already described in xml. I'd appreciate your feedback. Thanks.

**Comment by venturia** [comment]
@ianna,
the DetId shifts have to be applied to any geometry, regardless if they are build from DDD (which for me means XML. Is it a correct understanding?) or from the DB (I assume this is what you mean by PGeometricDet). I must admit that I know I have to learn what is the real difference between a geometry built from DDD and a Geometry built from the database but I was under the assumption that this, for the moment, does not affect my changes because the DetId shifts enter when the GeometricDet tree is used to create the TrackerGeometry and I thought that the DDD/DB business affects only the creation of the GeometricDet tree. Can you tell me if what I am saying is wrong and where do you see I should have used the DetId shifts as well? Strictly speaking the DetId shifts are used in TrackerGeometricDetESModule and, as you can see here:
https://github.com/cms-sw/cmssw/blob/CMSSW_7_4_X/Geometry/TrackerNumberingBuilder/plugins/TrackerGeometricDetESModule.cc#L136
I use them also for the configurations with "fromDDD=false".

Once all the above is settle, namely if I have introduced a bug or not, I may agree with you that it would be better to pass these parameters either using the XML files (DDD method) or, I guess, in NEW DB objects in addition to the ones used to build the GeometricDet tree. Did I got it right?

               Andrea


On Jan 22, 2015, at 14:49 , Ianna Osborne <notifications@github.com<mailto:notifications@github.com>>
 wrote:


@venturia<https://github.com/venturia> - as discussed earlier, this is a first step in DB-ization of configurable parameters for Tracker. So far I've replaced DetId shifts only. I can see that you've used them only for geometries built from DDD. Should PGeometricDet builder be adjusted to use the shifts as well? If needed, the PTrackerParameters record (with DetId shifts) will be available in a GT.

The next step is to clean up other configurable constants which are already described in xml. I'd appreciate your feedback. Thanks.

**Comment by ianna** [comment]
@venturia  In DB case: GeometricDet tree is built by PGeometricDetBuilder http://cmslxr.fnal.gov/source/CondTools/Geometry/plugins/PGeometricDetBuilder.cc?v=CMSSW_7_4_X_2015-01-21-0200 from DDD and stored in a DB (as PGeometricDet). Here is a configuration used: http://cmslxr.fnal.gov/source/CondTools/Geometry/test/trackergeometrywriter.py?v=CMSSW_7_4_X_2015-01-21-0200

This is a separate step and this is what accessible from a GT. Indeed, the detidShifts are declared in TrackerGeometricDetESModule when "fromDDD=false", but never used nor needed, I think. The shifts should be taken into account earlier.

**Comment by venturia** [comment]
@ianna, you are right: once stored in the database the GeometricDet tree has already the detid properly assigned. I agree there is no need to configure the DetId shifts for the case when DB and not DDD is used. If you want to remove them from the fillDescription in that case I have no problem.
At the same time I assume that the piece of code used to create the database object used the same code that is used to create the GeometricDet tree from DDD and, therefore, will use the Detid shifts, whatever way they are configured.

                            Andrea

On Jan 23, 2015, at 10:02 , Ianna Osborne <notifications@github.com<mailto:notifications@github.com>>
 wrote:


@venturia<https://github.com/venturia> In DB case: GeometricDet tree is built by PGeometricDetBuilder http://cmslxr.fnal.gov/source/CondTools/Geometry/plugins/PGeometricDetBuilder.cc?v=CMSSW_7_4_X_2015-01-21-0200 from DDD and stored in a DB (as PGeometricDet). Here is a configuration used: http://cmslxr.fnal.gov/source/CondTools/Geometry/test/trackergeometrywriter.py?v=CMSSW_7_4_X_2015-01-21-0200

This is a separate step and this is what accessible from a GT. Indeed, the detidShifts are declared in TrackerGeometricDetESModule when "fromDDD=false", but never used nor needed, I think. The shifts should be taken into account earlier.

**Comment by ianna** [comment]
@venturia - yes, agree. I'll need to update payloads in DB then.

**Comment by degano** [comment]
@cmsbuild please test

**Comment by venturia** [comment]
@ianna, yes, please check that you can get sensible DB payload. For the moment, since 74x supports only the present geometry and since I have not changed the detid schema for the present geometry (and I am not planning to do so ever!), the new payloads you will get should be identical to the present ones.

                                                                                 Andrea

On Jan 23, 2015, at 10:16 , Ianna Osborne <notifications@github.com<mailto:notifications@github.com>> wrote:


@venturia<https://github.com/venturia> - yes, agree. I'll need to update payloads in DB then.

**Comment by ianna** [comment]
@venturia, thanks, I'll let you know about the results.

**Comment by ianna** [comment]
+1

**Comment by ianna** [comment]
@venturia - I confirm it does not change current tracker geometry.

**Comment by davidlange6** [comment]
@ianna - this PR no longer merges in 74x.

**Comment by ianna** [comment]
@davidlange6 - just submitted a new one.

**Pull request closed without merging**
