### PR TITLE
Updated cfg file for beampixel application for 2018 run

### PR DESCRIPTION
**Pull request by dinardo**
I changed from eras.Run2_2017 to eras.Run2_2018 and from PixelTracks_2017_cff to PixelTracks_cff
- Mauro.

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by dmitrijus** [comment]
Is this a backport? If so, please **link it**

**Comment by dinardo** [comment]
Yeap,
from here: https://github.com/cms-sw/cmssw/pull/22803

**Comment by dmitrijus** [comment]
This is not a backport, number of changes is different.... :(

**Comment by dinardo** [comment]
Hi dmitrijus,
that's quite right.
This is a backporting of PR #22803 and PR #23261.
I've actually made also the PR #23264 which is included in this one (PR #23282).

Cheers,
- Mauro.

**Comment by jfernan2** [comment]
Successfully tested and integrated in the Online DQM at P5. https://twiki.cern.ch/twiki/bin/viewauth/CMS/DQMP5TagCollector
Merged in master

**Comment by fabiocos** [comment]
@dinardo @jfernan2 one part of this PR is the backport of #23261 (why not mentioning it?). The update of the cfg is consistent with 10_2_X . It would be good to mark the backports explictly to avoid confusion.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
