### PR TITLE
Modifications to include HLT_DoubleMu3_Trk_Tau3mu path in the HeavyFlavor DQM package

### PR DESCRIPTION
**Pull request by surnairit**
Dear Experts,

Please incorporate the following modifications to include HLT_DoubleMu3_Trk_Tau3mu path in the HeavyFlavor DQM package :

https://github.com/cms-sw/cmssw/commit/ca912ffb64518b0ca84bac133e8ec0f79693b84b
https://github.com/cms-sw/cmssw/commit/83717008fc3dd7b3c945b8db5ca18f14ac3b4cb2

We have not made any changes in the c++ code.

Regards,
Nairit

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
Need a 81X PR as well!

**Comment by dmitrijus** [comment]
+1

**Comment by dmitrijus** [comment]
please test

**Comment by davidlange6** [comment]
+1

**Pull request merged**
