### PR TITLE
[13_2_X] Add storing of invalid ROC number error (errorType=36) in pixel GPU code

### PR DESCRIPTION
**Pull request by ferencek**
#### PR description:

Backport of https://github.com/cms-sw/cmssw/pull/43052

### CODE REVIEW

**Comment by mmusich** [comment]
enable gpu

**Comment by mmusich** [comment]
please test

**Comment by mandrenguyen** [comment]
backport of https://github.com/cms-sw/cmssw/pull/43052

**Comment by mandrenguyen** [comment]
+1

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
