### PR TITLE
DD: Current Namespace is a Singleton, so make it one

### PR DESCRIPTION
**Pull request by ianna**
* DD current namespace is set by the DD Parser at the end of an element: https://github.com/cms-sw/cmssw/compare/master...ianna:dd-current-namespace-singleton?expand=1#diff-51ff922ad1d158611046bba4ee32b399R86

@cvuosalo - Could you, please, check during the DD Algorithms code review if they do need to use a current namespace or they would be ok with using their parent's namespace? If the latter works, we can remove this class entirely. Thanks.

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade

**Comment by ianna** [comment]
@kpedro88 - any chance it could make in to the next IB?

**Comment by kpedro88** [comment]
+1

**Pull request merged**
