### PR TITLE
[90X] Geometry-independent MillePede validation

### PR DESCRIPTION
**Pull request by ghellwig**
backport of #18550

- make the MillePede-internal validation (MPS validation) properly work for phase-1
- MPS validation works now also without checking out the MP package
- added weight information to the MPS validation
- minor bug fixes for exotic use cases

### CODE REVIEW

**Comment by ghellwig** [comment]
please test

**Comment by franzoni** [comment]
hello @ghellwig
how critical is for PR to end up in 90x ?
it's 92 version is merged and 91 version is fully approved.

**Comment by ghellwig** [comment]
@franzoni It would be great if it could be integrated in the next release, but it is not crucial to create a new release just for this update.
We currently use a private 90X installation where this update is deployed, therefore we only need it if we have to use a more recent 90X release. Looks like an unlikely scenario to me, though.

What about just approving it and let @davidlange6 decide about it when he has to cut a new 90X release?

**Comment by franzoni** [comment]
> What about just approving it and let @davidlange6 decide about it when he has to cut a new 
> 90X release?

David was telling me this morning 
we might not even have more 91x , since all what's needed for data taking will be in 92x

**Comment by franzoni** [comment]
+1

**Comment by davidlange6** [comment]
Closing PR. CMSSW_9_0_X development has completed (CMSSW_9_2_X is for data taking)

**Pull request closed without merging**
