### PR TITLE
Run3-gex138C Try to avoid getByLabel and instead use getByToken in a few modules of Calibration

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Try to avoid getByLabel and instead use getByToken in a few modules of Calibration

#### PR validation:

Use the runTheMatrix test workflows

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by ChrisMisan** [comment]
@bsunanda please squash the code-check

**Comment by ChrisMisan** [comment]
please test

**Review by ChrisMisan — COMMENTED** [review]
- In the Calibration/HcalCalibAlgos/plugins/ValidIsoTrkCalib.cc, there is some commented code which can be cleared.
- why is this necessery?
https://github.com/cms-sw/cmssw/blob/e69ce71aad2028c7b82085e0b0d5b8c4225bc9ed/Calibration/IsolatedParticles/plugins/IsolatedTracksNxN.cc#L323

- Calibration/IsolatedParticles/plugins/IsolatedTracksNxN.cc should make use of the smart pointers instead of manually managing the memory

- In Calibration/TkAlCaRecoProducers/src/CalibrationTrackSelector.cc there is some commented code which can be cleared.

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by ChrisMisan** [comment]
+alca

- differences in MTD and L1T which are failing for all the PRs

- [0b5875f](https://github.com/cms-sw/cmssw/commit/0b5875ffcbe6d77002aa2453a08bbcaef7d78598) changed the vector header allocation to stack but this is sufficient for me as free-space is still on the heap.

**Comment by perrotta** [comment]
+1

**Pull request merged**
