### PR TITLE
transferSystem PSet support and other DAQ updates (73X)

### PR DESCRIPTION
**Pull request by smorovic**
changes:
- beginning of lumisection files written locally by FUs to indicate opening new LS from the input source to other DAQ components (introduced to create backpressure in case of delay in LS processing)
- Each Ini file checksum is verified after writing to disk and before renaming into location where it is taken by hltd
- transfer system PSet and selected destination support. Selected destination is passed as VarArgs parameter. A parameter is added to control whether exception is thrown when PSet is incomplete or parameter missing. New output json field is added to output module as well as JSON and DQMHistograms modules
- fixed min. number of run digits in filenames used by TriggerJSONMonitoring (only relevant for test run numbers smaller than 100000).
- Fake BU and Raw writer improvements:
  - FED 1024 is handled in Raw writer
  - closing last LS written when interrupted from shell
  - updated schema of EoLS and Eor jsd/json
  - ability to copy menu directory when starting a run by script
  - fffParameters.jsn file handling

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by emeschi** [comment]
+1
On 28 Feb 2015, at 11:46, cmsbuild <notifications@github.com<mailto:notifications@github.com>> wrote:


The tests are being triggered in jenkins.

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
