### PR TITLE
Heppy 7 4 4 patch4

### PR DESCRIPTION
**Pull request by cbernet**
Hello, 

Here is a new version of heppy for CMSSW_7_4_X. This version contains important bug fixes, and is compatible with ipython 3.1. I am going to request ipython 3.1 for 74X in cmsdist now and link the two pull requests together. 

It would be great if these two requests could enter CMSSW at the same time. 

@arizzi @gpetruc : we do a PR later with new changes from you guys anytime you want after the migration to ipython 3.1. Here, I'm only fixing critical problems. 

@degano : same stuff as what we discussed for 75X.

Colin

### CODE REVIEW

**Comment by davidlange6** [comment]
@cbernet @degano - lets start this process in 75x and then see how to backport

**Comment by cbernet** [comment]
Hi, 

It’s done in 75X. 
We would really need it in 74X as this is the releases people are using to analyse simulated run2 samples. 

Cheers, 

Colin

**Comment by davidlange6** [comment]
Hi Colin

I understand, but we need to test then back port code (e.g., ipython)

What is the 75x PR?

**Comment by cbernet** [comment]
I think it may be this one, but @degano can confirm:
https://github.com/degano/cmsdist/commit/0b04ae9641bda3016371bc62e43bfd8656cffd14
I had tested that heppy and ipython are working in 75X before the integration. 

What I see is that ipython 3.1.0 is in the 75X IB.

**Comment by davidlange6** [comment]
Perfect - thanks

**Comment by cbernet** [comment]
As said in the cmsdist PR, Alessandro provided a testing recipe, and I could test that in the most recent IB: 
- ipython 3.1 is set 
- the version of heppy in this branch works with ipython 3.1

**Comment by degano** [comment]
+1
I compiled this manually against https://github.com/cms-sw/cmsdist/pull/1617 external.
Ran the usual tests: 1306.0,101.0,1003.0,50202.0,9.0,25202.0.

**Comment by degano** [comment]
@cmsbuild hold.
This is to prevent automatic merge once all the signatures will be in place, since this PR needs to go in along the cmsdist one.

**Comment by degano** [comment]
@cmsbuild hold.
This is to prevent automatic merge once all the signatures will be in place, since this PR needs to go in along the cmsdist one.

**Pull request merged**
