### PR TITLE
[PRO] adding new PPS conditions for 2023

### PR DESCRIPTION
**Pull request by diemort**
This PR is meant to introduce the latest PPS conditions for 2023 for the PPS fast simulation (Direct Simulation).

PPS direct simulation with 2023 conditions show the expected agreement in proton reconstruction based on the gen v recpo comparison.

Gen_vs_Reco_2023

Not a back-port; a new PR is going to be submitted meant for 14.1 since that was the release for 2023 data-taking.

PR passed unittests and runTheMatrix 44 43 41 36 19 1 1 1 1 1 1 tests passed, 0 0 0 0 0 0 0 0 0 0 0 failed

FYI @fabferro @AndreaBellora @forthommel

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by makortel** [comment]
Is there a plan to get these data into the CondDB? (just curious)

**Comment by smuzaffar** [comment]
please test

**Comment by diemort** [comment]
> Is there a plan to get these data into the CondDB? (just curious)

@makortel indeed, we had this discussion in cms-data. Therre are a few conditions that need to be moved to DB, however the old version of direct simulation is based on local conditions especially Run2. We're working on a validation procedure and can investigate about moving all conditions to DB.

**Comment by diemort** [comment]
the fails seem to be in the wf

**Comment by smuzaffar** [comment]
please test

there was bug in cms-bot which is fix now

**Comment by diemort** [comment]
Regarding the error in the RelVal above, it may be related to the missing era in case the fix in the wf was related to a modification in Era_Run3_2023.

**Comment by AndreaBellora** [comment]
> > Is there a plan to get these data into the CondDB? (just curious)
> 
> @makortel indeed, we had this discussion in cms-data. Therre are a few conditions that need to be moved to DB, however the old version of direct simulation is based on local conditions especially Run2. We're working on a validation procedure and can investigate about moving all conditions to DB.

Adding a comment on this point: having these conditions in the DB is not straightforward as it sounds. Since our detector and reconstruction changes conditions very often, we came up some years ago with the implementation of the so-called profiles, which are sets of conditions (not supplied from the DB) between which the direct simulation switches when changing lumisections. 
A good example is the beam crossing angle: LHC doesn't keep a constant crossing angle, thus we need to simulate events that vary it accordingly. In RECO, we rely on a per-LS payload that replicates the real LHC conditions, and in the simulation this is achieved by extracting the values from the xangle distributions observed in data. If we had to put that into condDB, we would then need a way to simulate different runs and LS so that in the end we reproduce the same xangle distributions. 
This, AFAIK, is not obvious and very error-prone, so either we keep using locally supplied files, or we would need to implement records dedicated to the simulation, which somehow contain the profiles, and modify our RECO to treat them properly.
This doesn't only apply to the xangle, but also to a few other conditions that would require a similar treatment.

**Comment by diemort** [comment]
After discussion, PPS offline sw decided to stick with a single Era modifier (already in use) to update conditions from config file. I'm closing this PR and a new one will be prepared to avoid confusion.

@perrotta No need to implement change/addition in Eras.

FYI @fabferro @grzanka @AndreaBellora @forthommel

**Pull request closed without merging**
