### PR TITLE
WIP: New DQM GUI based on files

### PR DESCRIPTION
**Pull request by ErnestaP**
### PR description:
This PR brings the new DQM GUI to CMSSW. The code is already at a working state but a lot of work still needs to be done.

The main purpose of this PR right now is to test it in P5.

### PR validation:
PR was validated locally.

### CODE REVIEW

**Comment by davidlange6** [comment]
Perhaps this pr can instead be made to a fork?

**Comment by silviodonato** [comment]
assign dqm

**Comment by silviodonato** [comment]
@ErnestaP what is the status of this PR?

**Comment by silviodonato** [comment]
please test
@cms-sw/dqm-l2

**Comment by qliphy** [comment]
please test

**Comment by slava77** [comment]
>     * This PR adds an extra 72352KB to repository

the commit history should be cleaned up so that we do not carry information in the repository for accidental/removed files

**Comment by davidlange6** [comment]
In any case its not planned to be in cmssw.

**Comment by silviodonato** [comment]
@ErnestaP do you still need this PR for testing at P5?  As you can see in the comments above there are a lot of files deleted AND added again. I would suggest you to squash the commits in fewer commits to avoid this. All these files remain in the history of github. As a result the size of this PR is 88.316MB, that is definitely too large for a PR (it should be few tens of KBs)

**Comment by ErnestaP** [comment]
Hi @silviodonato, yes I still need it. And thank you, sure I will squash it, but first I would like to finish one task and update it with the latest changes, if is it fine?

**Comment by davidlange6** [comment]
Out of curiosity, why does it a)need to be open, and b) be a pr against this repository (where there is no plan to integrate it)?

**Comment by ErnestaP** [comment]
@davidlange6 sorry for the late reply, I'm on holidays since the last week. It is open because we want to have online GUI accessible for users, and in this way test it during MWGR with actual data. It is really helps with noticing bugs and get feedback. 

However, the plan is to have it separated from CMSSW suit. In order to make it happen, we need to found a way to get the code that is in the master brach of the  following repository https://github.com/cms-DQM/dqmgui over to our P5 machines, including required the Python dependencies, which you can see here: https://github.com/cms-DQM/dqmgui/blob/master/python/requirements.txt

I will start to look at it more closely, after holidays.

**Pull request closed without merging**
