### PR TITLE
Preparation for migration to Geant4 10.6

### PR DESCRIPTION
**Pull request by civanch**
#### PR description:
This PR includes modifications which are needed to be integrated together with the migration of CMSSW to the new Geant4 version 10.6p01. So, only code checks are applided, no testing should be started.
 
#### PR validation:
private

### CODE REVIEW

**Comment by civanch** [comment]
@bsunanda , please, try to use it.

**Comment by civanch** [comment]
hold

**Comment by civanch** [comment]
This PR is on hold only to avoid start test - the PR is fine but should be merged only with the GEANT4 branch.

**Comment by silviodonato** [comment]
I try the trick suggested by Fabio

**Comment by silviodonato** [comment]
merge

**Comment by silviodonato** [comment]
I merged this PR and I reverted it.
The result is no changes in master:
https://github.com/cms-sw/cmssw/compare/c69790b4d5af491df94204d4579c1dd4f166a029...master

The difference is that now we can use the tag 1b50317bc1d3af2df292c48ecc61ffd12ba33d8c as pre4+#29077

**Comment by silviodonato** [comment]
Integrated again with #29104

**Pull request merged**
