### PR TITLE
EcalHaloDataProducer: setting input photon collection to empty string

### PR DESCRIPTION
**Pull request by lathomas**
Fix of the issue raised here: 
https://github.com/cms-sw/cmssw/issues/15781#issuecomment-245909412

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

@lathomas thank you

**Comment by cvuosalo** [comment]
+1

For #15799 5823a2920e230010c5bded0e644d8ac43e9ffd71

Prevent fetching of an unused photon collection to avoid a circular dependency in the RECO path. There should be no change in monitored quantities.

#15800 is the 80X version of this PR.

The code change is satisfactory, and Jenkins tests against baseline CMSSW_8_1_X_2016-09-08-2300 show no significant differences, as expected.

**Comment by slava77** [comment]
hold

@cvuosalo did you check that the execution order and also saved products remained unchanged?
Specifically, do the "photons" run before or after "EcalHaloData" and do the products from EcalHaloData stay the same?
I guess the check is needed in the regular unscheduled workflow like 136.731 as well as in the affected workflow 8.0 that started the issue.

**Comment by slava77** [comment]
test message

**Comment by slava77** [comment]
unhold

**Comment by cvuosalo** [comment]
An extended test of workflows 8.0_BeamHalo and 136.731_RunSinglePh2016B with 20 events each against baseline CMSSW_8_1_X_2016-09-09-2300 shows no significant differences, no significant change in CPU time, and no change in RECO or Mini-AOD event content. For 8.0, `photons` appears in the RECO log after `EcalHaloData`, while for 136.731 the order is reversed.

**Comment by slava77** [comment]
On 9/13/16 1:11 PM, Carl Vuosalo wrote:
> An extended test of workflows 8.0_BeamHalo and 136.731_RunSinglePh2016B
> with 20 events each against baseline CMSSW_8_1_X_2016-09-09-2300 shows
> no significant differences, no significant change in CPU time, and no
> change in RECO or Mini-AOD event content. For 8.0, |photons| appears in
> the RECO log after |EcalHaloData|, while for 136.731 the order is reversed.

Based on the code of EcalHaloAlgo, the photon collection determines
content of
EcalHaloData.TheSuperClusterRefs.
Looking at one of the available 136.731 outputs I see that this vector
is filled sometimes.
This PR should change the result.

What was the evidence to conclude that there is no change in RECO?

**Comment by lathomas** [comment]
There can be a change in RECO indeed. (cf discussion here: https://github.com/cms-sw/cmssw/pull/15800) 
"If the photon collection is anyway produced after this producer is run then it should not change anything. 
If "photons" exist, then it can affect the superclusters stored in the class EcalHaloData: https://github.com/cms-sw/cmssw/blob/CMSSW_8_1_X/RecoMET/METAlgorithms/src/EcalHaloAlgo.cc#L172
These SC are currently not used anywhere though. "

Is this an issue?

**Comment by cvuosalo** [comment]
@slava77: Concerning changes in RECO caused by this PR, the tests I mention above show no changes in DQM or validation plots, and RECO event content size shows no appreciable change. `edmEventSize` reports the same size for the recoEcalHaloData for both baseline and PR for wf 136.731:
```
recoEcalHaloData_EcalHaloData__reRECO. 602.85 297.15
```
Looking into the RECO ROOT file, plots for recoEcalHaloData ShowerShapes_Angle and thehaloclustercands_eb.getClusterEt, for example, are identical between baseline and PR. What other checks are necessary to prove that recoEcalHaloData has not changed?

**Comment by slava77** [comment]
On 9/13/16 3:50 PM, Carl Vuosalo wrote:
> @slava77 <https://github.com/slava77>: Concerning changes in RECO caused
> by this PR, the tests I mention above show no changes in DQM or
> validation plots, and RECO event content size shows no appreciable
> change. |edmEventSize| reports the same size for the recoEcalHaloData
> for both baseline and PR for wf 136.731:
> 
> |recoEcalHaloData_EcalHaloData__reRECO. 602.85 297.15 |
> 
> Looking into the RECO ROOT file, plots for recoEcalHaloData
> ShowerShapes_Angle and thehaloclustercands_eb.getClusterEt, for example,
> are identical between baseline and PR. What other checks are necessary
> to prove that recoEcalHaloData has not changed?

I have provided the variable name that is changing and Laurent has
confirmed (repeated, actually, the earlier note about expected changes).

As we discussed earlier, this change is not an issue for 81X, but should
nominally be rejected from 80X.

**Comment by cvuosalo** [comment]
A test of workflow 136.731_RunSinglePh2016B with 1000 events against baseline CMSSW_8_1_X_2016-09-09-2300 shows no difference in the size of RECO or Mini-AOD event content but does show a tiny difference in the ECAL Halo IDs, shown below. This change could be due to a slight change in the EcalHaloData that this PR might cause. Otherwise, there are no differences shown by this test.

all_testpr15799vsorig_runsingleph2016bwf136p731c_recobeamhalosummary_beamhalosummary__rereco_obj_ecalloosehaloid
all_testpr15799vsorig_runsingleph2016bwf136p731c_recobeamhalosummary_beamhalosummary__rereco_obj_ecaltighthaloid

**Comment by slava77** [comment]
On 9/15/16 12:49 PM, Carl Vuosalo wrote:
> A test of workflow 136.731_RunSinglePh2016B with 1000 events against
> baseline CMSSW_8_1_X_2016-09-09-2300 shows no difference in the size of
> RECO or Mini-AOD event content but does show a tiny difference in the
> ECAL Halo IDs, shown below. This change could be due to a slight change
> in the EcalHaloData that this PR might cause. Otherwise, there are no
> differences shown by this test.

Good to know.
Based on the code there is direct relationship between the clusters
saved for photons and the
beamhalosummary ecal{loose,tight}id.

even though you mention "tiny" difference,
I suppose,
it actually is changing *all* earlier available 1 (true) to 0 (false)
which is nominally a large difference.

**Comment by cvuosalo** [comment]
+1

For #15799 5823a2920e230010c5bded0e644d8ac43e9ffd71

Prevent fetching of a photon collection to avoid a circular dependency in the RECO path.

#15800 is the 80X version of this PR, but it will be rejected, as discussed below.

The code change is satisfactory, and Jenkins tests against baseline CMSSW_8_1_X_2016-09-08-2300 show no significant differences. Tests described above show that EcalHaloData can change for both RECO and Mini-AOD and thereby change ECAL Halo IDs. These event content changes are acceptable in pre-release 81X but not in 80X production, so #15800 will be rejected.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
