### PR TITLE
Update residual decays and verbosity

### PR DESCRIPTION
**Pull request by mkirsano**

### CODE REVIEW

**Comment by bendavid** [comment]
Is this needed to have working residual decays after the previous fix?

**Comment by mkirsano** [comment]
There is residualDecay also in Pythia8 Guns, it was not fixed in the previous fix.
There is a small improvement of HepMCA2.h (needed to ask for inclusion in pythia8). For CMSSW it will work as before.
And additional verbosity of Pythia8Interface

**Comment by bendavid** [comment]
OK thanks.  What is the improvement in hepmca2?

**Comment by mkirsano** [comment]
In the first variant the barcodes of added particles did not continue the previous barcode sequence. Now by default they continue it. And I put back some features that existed in the standard HepMC2.h.

**Comment by bendavid** [comment]
+1

**Pull request merged**
