### PR TITLE
metadata JSON files produced for empty lumisections in DAQ (76X)

### PR DESCRIPTION
**Pull request by smorovic**
Implementation of JSON metadata output for each lumisection in Filter Units and several other smaller changes and bugfixes:
- file distribution scheme in ramdisk previously allowed skipping lumisections with no data. This is now modified so that each process must transition through each lumisection starting from one first seen in lock file in BU ramdisk.
- correponding changes in DAQ (streamer) output module, and DQMHistogram, L1/HLT rates stream producers to output metadata json for empty lumisections
- avoid casting -1 to uint32 in Trigger JSON module, which converts it in the valid range of the checksum (-1 is intended as true negative in JSON to signal that checksumming is disabled in particular cases)
- added "maxBufferedFiles" parameter which limits the number of currently open files (useful in case of more than two input buffers used)
- exception thrown when "_" (underscore) is used as stream name because this breaks file naming convention in DAQ (and breaks output merging by hltd)
- updated fake BU code with latest json format used by DAQ BU application
  removed old unused test mode code in input source and DaqDirector
#10796 is 74X equivalent of this PR
#10807 is 75X equivalent of this PR

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by mommsen** [comment]
+1

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/10808	 a40208b
- the same changes as in 75X (#10807), no effect on RECO, touching only DAQ-relatad processing
- jenkins tests passed, but a large fraction of comparison tests failed, apparently due to transfer failures. Relying on results in 75X PR

**Comment by Martin-Grunewald** [comment]
+1

**Comment by smorovic** [comment]
please test

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/10808	2213e3d
- the change made since the last reco signoff is specific to online fff/hlt processing, not affecting reco
- signing off provided jenkins agrees

**Comment by mommsen** [comment]
+1

**Comment by Martin-Grunewald** [comment]
please test

**Comment by danduggan** [comment]
+1

**Comment by Martin-Grunewald** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
