### PR TITLE
Follow up to the Alpaka integration in CMSSW [14.0.x]

### PR DESCRIPTION
**Pull request by fwyzard**
##### `HeterogeneousCore/AlpakaInterface`
Rewrite the work division utilities:
  - rewrite the uniform element kernel loops.
  - rewrite the independent element kernel loops.
  - remove the obsolete `alpakatools` utilities.

Rewrite the `zeroAndInit` kernel using the `alpakatools` utilities.
Rename `elements_with_stride` to `uniform_elements` in user code.

##### `RecoLocalTracker/SiPixelClusterizer`
Implement fixes that were lost during the CUDA-to-Alpaka migration.

Collect the updates from #39711, #42618, #42977 and #43052, that were missing from the Alpaka implementation:
  - skip invalid or corrupted ROCs: make the Alpaka implementation of the pixel unpacker skip spurious ROCs, similar to the legacy and CUDA versions of the unpacker, and store the
invalid ROC number error (`errorType=36`);
  - fix the decoding of channels with timeout errors (`errorType=27`);
  - synchronise the treatment of pixel `errorType=26`, `27`, `30` with the legacy code;
  - disable `printf` statements at compile time.

##### `RecoTracker/PixelSeeding`
Do not call the fishbone for events with pixel hits only in BPIX1 (reimplement #35638).

##### `RecoTracker/MeasurementDet`
Add a check on the pixel ROC range, to avoid overflows in the (unsigned) range differences.

##### `DataFormats/TrackingRecHitSoA`
Extend `TrackingRecHits` collections for testing and their unit tests.

##### `CondFormats/SiPixelObjects`
Clean up includes and dependencies, and avoid including framework headers in the device compilation.

##### `Geometry/CommonTopologies`
Update comments to pixel topologies.

##### Other changes
Fix include guards after files were moved to different packages.
Clean up include files.
Simplify nested namespace declarations.

#### PR validation:

Unit tests pass.

Validated running a recent HLT menu over 20k events without issues, both on GPU and on CPU, on data and MC: the alpaka implementation running on CPU or GPU gives the same results as the CUDA implementation, within the same non-reproducibility margins (1 event or up to 1% for high-rate triggers).

#### Backport status:

Backport of #43853 to 14.0.x (same branch) for 2024 data taking.

### CODE REVIEW

**Comment by fwyzard** [comment]
backport #43853

**Comment by fwyzard** [comment]
type bugfix

**Comment by fwyzard** [comment]
+heterogeneous

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
OK, assuming all tests pass, I think we have collected all the bug fixes required for `CMSSW_14_1_0_pre1` and `CMSSW_14_0_0`.

**Comment by fwyzard** [comment]
urgent

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
+heterogeneous

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
+heterogeneous

**Comment by mandrenguyen** [comment]
+1

**Comment by perrotta** [comment]
+1
- Verbatim backport of https://github.com/cms-sw/cmssw/pull/43853, which was successully merged since CMSSW_14_1_X_2024-02-12-2300
- Current errors in the master IBs were already present even before the merge of  https://github.com/cms-sw/cmssw/pull/43853  (and should be hopefuly fixed at some point...)

**Comment by civanch** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

**Comment by AdrianoDee** [comment]
+pdmv

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
