### PR TITLE
Sim: Use Production Cut on Proton from XML Definition

### PR DESCRIPTION
**Pull request by ianna**
#### PR description:

* Use production cut on proton set in XML files
* Use LogVerbatim instead of LogDebug
* Add a DD4hep geometry workflow test in a release validation test run automatically
 
Note: It needs https://github.com/cms-sw/cmssw/pull/27299 to go in and updated payloads in DB.

#### if this PR is a backport please specify the original PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by ianna** [comment]
please test

I'd assume the results should differ.

**Comment by civanch** [comment]
@ianna , I do not check why you get crash but would advice not changing python fragments, only modify the code. After this PR let me make minor iteration

**Comment by fabiocos** [comment]
@ianna @civanch if this PR is supposed to use the update of #27299 you need to add that PR to the test. Anyway for geometries taken from the DB this will not be enough, without an update of the tags

**Comment by fabiocos** [comment]
please test with cms-sw/cmssw#27299

**Comment by ianna** [comment]
All workflows which use the geometry from DB fail:
```
terminate called after throwing an instance of 'cms::Exception'
  what():  An exception of category 'SimG4CorePhysics' occurred.
Exception Message:
 DDG4ProductionCuts::setProdCuts: Problem with Region tags - no/more than one ProdCutsForProtons. 
```

**Comment by fabiocos** [comment]
@ianna @civanch as expected...

**Comment by ianna** [comment]
@civanch - FYI, this implementation should allow gradual introduction of the **ProdCutsForProtons** parameter in the XML files.

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by ianna** [comment]
@civanch - please review

**Comment by civanch** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
@ianna I have manually fixed a conflict with #27299, it was a trivial xml indentation issue

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
@ianna @cvuosalo @civanch I have just adjusted the indentation of the new line, which was in this PR in disagreement with #27299. As soon as the test is ok I will merge it in next IB (I do not expect any surprise, differences might just come from other PRs).

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

taking previous signatures as valid, @ianna @civanch please anyway check and sign or comment

**Comment by cvuosalo** [comment]
+1

**Pull request merged**
