### PR TITLE
Fix muon alignment producers 75X

### PR DESCRIPTION
**Pull request by mmusich**
Originally in #9482.
Includes several changes to the ALCARECO producers used by MuonAlignment:
- changed thresholds pT and eta for muons and general tracks;
- added several new collections to the output files (tracks, vertexes, etc.);
- changed some of the detector DCS status flags;
- fixed a bug that existed in the Overlaps stream during Run-1.
- changed the relval steps matrix to test the new features.

### CODE REVIEW

**Comment by mmusich** [comment]
@pakhotin you might want to follow this one.

**Comment by mmusich** [comment]
@cmsbuild please test

**Comment by mmusich** [comment]
@cmsbuild please acknowledge changes

**Comment by mmusich** [comment]
please test

**Comment by davidlange6** [comment]
Hi - I'm cleaning up the 75x CMSSW release queue, so closing issues not directly related to analysis or finalizing the HI MC production. Please make sure these requests are included in the 80x release already. Thanks!

**Pull request closed without merging**
