### PR TITLE
Removal of git-publish

### PR DESCRIPTION
**Pull request by silviodonato**
#### PR description:

Follow-up of https://github.com/cms-sw/cmssw/pull/32917#issuecomment-781390708 by @smuzaffar :

> I think Utilities/ReleaseScripts/scripts/git-publish is not used and can be dropped. It has the old categories name (CVS era). Most of this is now part of git-cms-tools.

cc @cms-sw/core-l2 

#### PR validation:

`scram b runtests`

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

No backport expected

### CODE REVIEW

**Comment by silviodonato** [comment]
please test

**Comment by silviodonato** [comment]
kind reminder @cms-sw/core-l2 . If you prefer we can mention this PR at the ORP meeting, just to be sure nobody needs it.

**Comment by makortel** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
