### PR TITLE
Phase2-hgx314A Next Step toward V17 version of HGCal Geometry

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Next Step toward V17 version of HGCal Geometry. Take care of the newer mode in geometry definition

#### PR validation:

Use runTheMatrix workflows

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@srimanob Please approve this urgently!

**Comment by srimanob** [comment]
+Upgrade

**Comment by qliphy** [comment]
+1

**Pull request merged**
