### PR TITLE
Modification of customisation to include centrality reconstruction in…

### PR DESCRIPTION
**Pull request by jmartinb**
Modification of customisation to include centrality reconstruction in pp reco

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

@jmartinb please provide a link to a presentation in HI or related group with details of your update

Also, please provide some technical level information:
- increase in storage needed in pA workflow

**Comment by jmartinb** [comment]
Here there is a ling to a presentation in the centrality meeting: https://twiki.cern.ch/twiki/pub/CMS/HiCentrality2016/RunPrep_ST_Aug05v1.pdf

I'll let you know about the storage

**Comment by jmartinb** [comment]
The pull request has been updated. AOD event content has been further extended: ZDC will be read through castorDigis (added to pull request) and RPD through hcalDigis

Related slides inluding estimated increase of event size here: https://twiki.cern.ch/twiki/pub/CMS/HiCentrality2016/CentralityInppReco.pdf

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
CentralityBinProducer.cc is not thread-safe because it inherits from the legacy EDProducer on line 47. Should it be fixed now?

**Comment by cvuosalo** [comment]
@jmartinb: Could you provide a complete cmsDriver command for testing this PR? I know the basic part is:

cmsDriver.py step2 --mc --eventcontent AODSIM --customise RecoHI/
Configuration/customise_PPwithHI.customisePPrecoforPPb --datatier AODSIM --conditions 81X_mcRun2_pA_v2 --step
RAW2DIGI,L1Reco,RECO --era Run2_2016

**Comment by jmartinb** [comment]
Hi,
Sorry for the delay in the answer.
I used that command plus: --filein=/store/himc/pPb816Summer16DR/ReggeGribovPartonMC_EposLHC_pPb_4080_4080/GEN-SIM-RAW/80X_mcRun2_asymptotic_v15-v1/100000/002ABE5C-6379-E611-84F8-0025B3E01F20.root --number=100

**Comment by cvuosalo** [comment]
+1

For #16054 acb9cc8c73a63bca96f59a0691a5b98497dd872c

Modifying Heavy Ions customization to add centrality reconstruction. There should be no change in monitored quantities for pp workflows.

The code changes are satisfactory, and Jenkins tests against baseline CMSSW_8_1_X_2016-10-06-1100 show no significant differences, as expected. The Heavy Ion customization was tested as described above. It ran successfully to completion, and the expected collections were added to event content:
```
-----------------------------------------------------------------
   or, B         new, B      delta, B   delta, %   deltaJ, %    branch 
-----------------------------------------------------------------
      0.0 ->       316.0        316     NEWO   0.04     doubles_hiFJGridEmptyAreaCalculator_mapToRhoCorr_RECO.
      0.0 ->       249.0        249     NEWO   0.03     doubles_hiFJRhoProducer_mapEtaEdges_RECO.
      0.0 ->       266.0        266     NEWO   0.04     ZDCDataFramesSorted_castorDigis__RECO.
      0.0 ->       267.8        268     NEWO   0.04     doubles_hiFJGridEmptyAreaCalculator_mapEmptyCorrFac_RECO.
      0.0 ->       319.0        319     NEWO   0.04     doubles_hiFJGridEmptyAreaCalculator_mapToRhoMCorr_RECO.
      0.0 ->       278.8        279     NEWO   0.04     doubles_hiFJRhoProducer_mapToRho_RECO.
      0.0 ->       352.9        353     NEWO   0.05     ZDCDataFramesSorted_hcalDigis__RECO.
      0.0 ->      4085.6       4086     NEWO   0.56     recoCentrality_pACentrality__RECO.
      0.0 ->       328.8        329     NEWO   0.04     doubles_hiFJGridEmptyAreaCalculator_mapToRhoCorr1Bin_RECO.
      0.0 ->       392.8        393     NEWO   0.05     doubles_hiFJRhoProducer_areaJets_RECO.
      0.0 ->     13863.4      13863     NEWO   1.89     CaloTowersSorted_towerMaker__RECO.
      0.0 ->       509.6        510     NEWO   0.07     doubles_hiFJRhoProducer_ptJets_RECO.
      0.0 ->      4895.5       4896     NEWO   0.67     recoHIPhotonIsolationedmValueMap_photonIsolationHIProducerppGED__RECO.
      0.0 ->      4818.6       4819     NEWO   0.66     recoHIPhotonIsolationedmValueMap_photonIsolationHIProducerpp__RECO.
      0.0 ->       329.8        330     NEWO   0.04     doubles_hiFJGridEmptyAreaCalculator_mapToRhoMCorr1Bin_RECO.
      0.0 ->       278.2        278     NEWO   0.04     ZDCRecHitsSorted_zdcreco__RECO.
      0.0 ->       297.4        297     NEWO   0.04     doubles_hiFJRhoProducer_mapToRhoM_RECO.
      0.0 ->       553.4        553     NEWO   0.08     doubles_hiFJRhoProducer_etaJets_RECO.
-------------------------------------------------------------
   735192 ->      767594      32402             4.4     ALL BRANCHES
```

**Comment by davidlange6** [comment]
+1

**Pull request merged**
