### PR TITLE
Let tests fail gracefully if no devices are found

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Let alpaka-based tests that require a device fail gracefully if there are no available devices on the given platform, instead of crashing or succeeding silently.

If more than one device is available, run the tests on each device.

#### PR validation:

Unit tests pass.

If there are no devices, the tests pass with an informational message instead of failing with a segmentation violation.

### CODE REVIEW

**Comment by fwyzard** [comment]
enable gpu

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
enable gpu

**Comment by fwyzard** [comment]
type bugfix

**Comment by fwyzard** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by makortel** [comment]
+heterogeneous

**Comment by rappoccio** [comment]
+1

**Pull request merged**
