### PR TITLE
Phase2-hgx353A Update various cfg files to do the tests for V18 versions of HGCal

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Update various cfg files to do the tests for V18 versions of HGCal

#### PR validation:

Tested this configurations for different versions of HGCal configuration

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@srimanob Please approve this

**Comment by srimanob** [comment]
+Upgrade

**Comment by rappoccio** [comment]
+1

**Pull request merged**
