### PR TITLE
Switch MuTau skim to USER data-tier + RAW-miniAOD event content

### PR DESCRIPTION
**Pull request by kfjack**
Change the MuTau skim output tier to USER, event content to RAW-miniAOD.

### CODE REVIEW

**Comment by fabozzi** [comment]
please test

**Comment by fabozzi** [comment]
+1

**Comment by fabozzi** [comment]
Relval test with MuTau skim was OK
https://hypernews.cern.ch/HyperNews/CMS/get/relval/6345.html

**Comment by davidlange6** [comment]
+1

**Pull request merged**
