### PR TITLE
Update UPC relval workflows

### PR DESCRIPTION
**Pull request by stahlleiton**
#### PR description:

This PR updates the Starlight gridpack to fix the issue seen in https://github.com/cms-sw/cmssw/issues/44536 . In addition it updates the 2024 UPC relval workflows by switching to the HI 2024 GT and the 2023 HI workflows by changing the beamspot to Realistic2023PbPbCollision and the HLT key to HIon (as used in central HIN 2023 MC production).

#### PR validation:

Tested the relval workflows 180, 180.1, 181, 181.1 locally.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

@mandrenguyen

### CODE REVIEW

**Comment by mandrenguyen** [comment]
please test workflow 180, 180.1, 181, 181.1

**Comment by stahlleiton** [comment]
Are there any comments on this PR?

**Comment by stahlleiton** [comment]
@cms-sw/pdmv-l2 , @cms-sw/generators-l2 , @cms-sw/upgrade-l2 : please review/sign this PR

**Comment by menglu21** [comment]
+1

**Comment by AdrianoDee** [comment]
+pdmv

**Comment by srimanob** [comment]
+Upgrade

**Comment by antoniovilela** [comment]
+1

**Comment by makortel** [comment]
The workflows 180.1 and 181.1 added in this PR frequently (but not always) fail with
```
---- Begin Fatal Exception 26-Apr-2024 10:58:14 CEST-----------------------
An exception of category 'Conditions not found' occurred while
   [0] Processing  Event run: 1 lumi: 1 event: 8 stream: 1
   [1] Running path 'HLTAnalyzerEndpath'
   [2] Prefetching for module L1TRawToDigi/'hltGtStage2Digis'
   [3] Prefetching for module RawDataCollectorByLabel/'rawDataCollector'
   [4] Prefetching for module SiStripDigiToRawModule/'SiStripDigiToRaw'
   [5] Calling method for module MixingModule/'mix'
Exception Message:
Unavailable Conditions of type HcalMCParams for cell (0x54000140) (Det 5:5 subdet 2:2 ZDC+ UNKNOWN 0,0)
----- End Fatal Exception -------------------------------------------------
```
There is already an older issue https://github.com/cms-sw/cmssw/issues/43582 about this failure mode, so I'd suggest to follow up there.

**Pull request merged**
