### PR TITLE
Add more module transitions to MessageLogger

### LINKED ISSUE #36522: TestIntegrationFinalPath failure
TestIntegrationFinalPath failed in CMSSW_12_3_X_2021-12-15-2300 slc7_amd64_gcc900 with
```
/data/cmsbld/jenkins/workspace/ib-run-qa/CMSSW_12_3_X_2021-12-15-2300/tmp/slc7_amd64_gcc900 /data/cmsbld/jenkins/workspace/ib-run-qa/CMSSW_12_3_X_2021-12-15-2300
1,7c1
< found thing '' TEST
< found thing '' TEST
< found thing '' TEST
< found thing 'beginLumi' TEST
< found thing 'endLumi' TEST
< found thing 'beginRun' TEST
< found thing 'endRun' TEST
---
> Binary file finalpath.log matches
differences for test_finalpath_cfg.py --path --task --schedule: status 1
=== Log file ===
=== End log file ===

---> test TestIntegrationFinalPath had ERRORS
```
https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc900/CMSSW_12_3_X_2021-12-15-2300/unitTestLogs/FWCore/Integration#/

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

Added write run, write lumi and calling ES modules.

This should fix some unit test failures.

#### PR validation:

Code compiles. Framework unit tests all pass.

fixes #36522

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by makortel** [comment]
Fixes also https://github.com/cms-sw/cmssw/issues/33224

**Comment by Dr15Jones** [comment]
The trace log for the crash is identical to the one in the IB for a different workflow:

https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc10/CMSSW_12_3_X_2022-01-25-1700/pyRelValMatrixLogs/run/1030.0_RunHLTPhy2017B+RunHLTPhy2017B+TIER0EXPHPBS+ALCASPLITHPBS+ALCAHARVDHPBS+ALCAHARVDHPBSLOWPU/step2_RunHLTPhy2017B+RunHLTPhy2017B+TIER0EXPHPBS+ALCASPLITHPBS+ALCAHARVDHPBS+ALCAHARVDHPBSLOWPU.log#/

**Comment by makortel** [comment]
+1

**Comment by perrotta** [comment]
+1
- The error for wf 1030, similar to the one reported here for wf 1004, was also present in the CMSSW_12_3_X_2022-01-25-1700 IB, the one used as baseline for the tests, as also pointed out [above](https://github.com/cms-sw/cmssw/pull/36801#issuecomment-1021753773)
- The following IB CMSSW_12_3_X_2022-01-25-2300 shows the same error as well: possible culprit is #36184, merged for CMSSW_12_3_X_2022-01-25-1700

**Comment by perrotta** [comment]
merge

**Pull request merged**
