### PR TITLE
Change to global module in L1Trigger/L1TGEM

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

- changed to global modules
- removed need to call Run transition
- reworked member functions to use 'return value optimization'

#### PR validation:

Code compiles.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
@makortel FYI

**Comment by Dr15Jones** [comment]
please test

**Comment by aloeliger** [comment]
Not to slow everything down, but this seems a bit more in depth than the usual technical changes. If only for my edification could I get a quick explanation on what happened here?

**Comment by Dr15Jones** [comment]
>  If only for my edification could I get a quick explanation on what happened here?

Sometimes while doing these technical changes I come across some code that could use some 'more lovin' :). I had started by removing the member data that was just caching a EventSetup data product and moved the call to `produce`. This allowed `beginRun` to be removed. After that, I noticed that all the remaining member data were immutable so I could easily change the module to be a `edm::global`. (`edm::global` are preferred over `edm::stream` modules as only one instance of a `edm::global` is needed in a job while we must make a copy of each `edm::stream` per Stream in the job). After the `edm::global` change, I figured I could also use the new `edm::Event::emplace` syntax which avoids creating a temporary on the heap for the `edm::Event::put` call and instead use a stack temporary (less heap churn that way). I did that by changing the member function from having its results value be passed via mutable function argument (which is no longer considered a good solution by the C++ community at large) to have it be the return value of the function. (Modern C++ requires that the compiler now handle returning objects from function using an optimized mechanism).

**Comment by aloeliger** [comment]
> > If only for my edification could I get a quick explanation on what happened here?
> 
> Sometimes while doing these technical changes I come across some code that could use some 'more lovin' :). I had started by removing the member data that was just caching a EventSetup data product and moved the call to `produce`. This allowed `beginRun` to be removed. After that, I noticed that all the remaining member data were immutable so I could easily change the module to be a `edm::global`. (`edm::global` are preferred over `edm::stream` modules as only one instance of a `edm::global` is needed in a job while we must make a copy of each `edm::stream` per Stream in the job). After the `edm::global` change, I figured I could also use the new `edm::Event::emplace` syntax which avoids creating a temporary on the heap for the `edm::Event::put` call and instead use a stack temporary (less heap churn that way). I did that by changing the member function from having its results value be passed via mutable function argument (which is no longer considered a good solution by the C++ community at large) to have it be the return value of the function. (Modern C++ requires that the compiler now handle returning objects from function using an optimized mechanism).

Okay, thanks for the explanation, especially for what was happening to `buildClusters` and `selectClusters` which caught my eye in the first place.

**Comment by aloeliger** [comment]
+l1

**Comment by rappoccio** [comment]
+1

**Pull request merged**
