### PR TITLE
use `--hltProcess reHLT` in Run-3 Data RelVals

### LINKED ISSUE #39714: Missing --hltprocess in reHLT workflows
Dear @cms-sw/pdmv-l2,
I've just realized that the reHLT workflows (eg. `140.003 RunJetHT2022B+HLTRUN3+RECONANORUN3+HARVESTRUN3`), the RECO...DQM step does not include the `--hltprocess reHLT` option, to run the HLT DQM from the reHLT instead of the original HLT.
(@cms-sw/dqm-l2 do you confirm this?).

This seems a problem similar to what we had with the ALCA relvals some weeks ago ([link](https://its.cern.ch/jira/browse/CMSALCA-182?focusedCommentId=4533092&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-4533092) ) 

It seems that we should add a `RECONANORUN3_reHLT` version in `Configuration/PyReleaseValidation/python/relval_steps.py` and use them in the matrix.

This problem was spotted in the contest of https://its.cern.ch/jira/browse/CMSHLT-2503 (@kjpena )
cc @cms-sw/hlt-l2 
```
140.003 RunJetHT2022B+HLTRUN3+RECONANORUN3+HARVESTRUN3 [1]: input from: /JetHT/Run2022B-v1/RAW with run [] 
                                           [2]: cmsDriver.py step2  --process reHLT -s L1REPACK:Full,HLT:@relval2022 --conditions auto:run3_hlt_relval --data  --eventcontent FEVTDEBUGHLT --datatier FEVTDEBUGHLT --era Run3 -n 100 
                                           [3]: cmsDriver.py step3  --conditions auto:run3_data_relval -s RAW2DIGI,L1Reco,RECO,PAT,NANO:PhysicsTools/NanoAOD/V10/nano_cff,DQM:@miniAODDQM+@nanoAODDQM --datatier RECO,MINIAOD,DQMIO --eventcontent RECO,MINIAOD,DQM --data  --process reRECO --scenario pp --era Run3 --customise Configuration/DataProcessing/RecoTLR.customisePostEra_Run3 -n 100 
                                           [4]: cmsDriver.py step4  -s HARVESTING:@miniAODDQM+@nanoAODDQM --conditions auto:run3_data --data  --filetype DQM --scenario pp -n 100 
```

### PR DESCRIPTION
**Pull request by missirol**
resolves #39714

#### PR description:

This PR is an attempt to solve #39714 by updating the Run-3 Data RelVal wfs to use the HLT results from the (re)HLT step of a given wf (process name = `reHLT`), rather than from the collections in wf's input files (process name = `HLT`). Minor renaming/refactoring of transient variables in `relval_steps` and `relval_standard` was done in the process.

Changes can be expected in the outputs of the affected workflows, as this changes which HLT results are used by their post-HLT steps (e.g. PAT and DQM).

This PR will likely need to be rebased after #39755 is integrated.

To add `--hltProcess reHLT` to the post-HLT step of the Run-3 data RelVals, the following is done:
 - rename `HLTDR3_2021` to `HLTDR3_2022`;
 - replace `HLTRUN3` with `HLTDR3_2022` (they are identical, making the first redundant);
 - create `RECODR3_reHLT` (= `"RECODR3 + --hltProcess=reHLT"`);
 - replace `RECODR3_2021` with `RECODR3_reHLT`;
 - rename `RECONANORUN3` to `RECONANORUN3_reHLT`, and base it off of `RECODR3_reHLT`;
 - rename `RECOCOSMRUN3` to `RECOCOSMRUN3_reHLT`.

#### PR validation:

`runTheMatrix.py -l 139.001,140.001,140.104` passed.

#### If this PR is a backport, please specify the original PR and why you need to backport that PR. If this PR will be backported, please specify to which release cycle the backport is meant for:

Not a backport. Backports TBD by PdmV.

### CODE REVIEW

**Comment by missirol** [comment]
test parameters:
 - workflows = 139.001,139.002,139.003,139.004,140.001,140.002,140.003,140.004,140.005,140.015,140.016,140.017,140.018,140.019,140.020,140.031,140.032,140.033,140.034,140.035,140.036,140.104,140.105,140.106,140.107,140.109,140.110,140.111,140.112,140.113,140.114,140.115,140.116,140.117

**Comment by missirol** [comment]
please test

**Comment by srimanob** [comment]
+Upgrade

**Comment by missirol** [comment]
hold

To be rebased onto the next IB, assuming https://github.com/cms-sw/cmssw/pull/39755 is merged by then.

**Comment by srimanob** [comment]
Hi @missirol 
Do you need this one for the coming 12_6_0_pre4, i.e. good for data relvals to go with reHLT? Or this can wait.

**Comment by missirol** [comment]
I didn't think this was urgent, but PdmV should state their preference.

In any case, I will rebase as soon as I have a viable IB.

**Comment by kskovpen** [comment]
Thanks a lot @missirol . I think it should be fine to rebase after an IB.

**Comment by missirol** [comment]
unhold

Rebased, now ready to be tested and reviewed.

**Comment by missirol** [comment]
test parameters:
 - workflows = 139.001,139.002,139.003,139.004,140.001,140.002,140.003,140.004,140.005,140.006,140.007,140.008,140.009,140.010,140.011,140.021,140.022,140.023,140.024,140.025,140.026,140.027,140.028,140.029,140.030,140.031,140.042,140.043,140.044,140.045,140.046,140.047,140.048,140.049,140.050,140.051,140.062,140.063,140.064,140.065,140.066,140.067,140.068,140.069,140.104,140.105,140.106,140.107,140.109,140.110,140.111,140.112,140.113,140.114,140.115,140.116,140.117

**Comment by missirol** [comment]
please test

**Comment by missirol** [comment]
@cms-sw/pdmv-l2 , could you have a look at this PR, please? I'd like to avoid a 2nd rebase.

**Comment by kskovpen** [comment]
+pdmv

**Comment by kskovpen** [comment]
Thanks @missirol

**Comment by perrotta** [comment]
+1

**Pull request merged**
