### PR TITLE
Puppi isolation electrons mini aod rebased v2

### PR DESCRIPTION
**Pull request by ishvetso**
this is a rebase of #15628

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by monttj** [comment]
Shouldn't it be the same as the input for PAT Photon?

process.egmPhotonPUPPIIsolation.srcToIsolate = cms.InputTag("reducedEgamma","reducedGedPhotons") 

The input for PAT photons is "gedPhotons" collection while the input for the value map is "reducedEgamma:reducedGedPhotons". 

Same for electrons. 

Regards,
Taejeong

**Comment by ishvetso** [comment]
I also thought that it should be gedPhotons, but I have checked the dump of the miniAOD configuration and there reducedEgamma collection is the actual input source collection.

**Comment by ishvetso** [comment]
@slava77 I'm trying to rebase -i as you requested to remove some irrelevant commits. I have started a new area and did 
git rebase -i CMSSW_8_1_X_2016-09-04-0000

and I'm getting some conflicts for some reason ...: 
error: could not apply 8cd34d6... few fixes

When you have resolved this problem, run "git rebase --continue".
If you prefer to skip this patch, run "git rebase --skip" instead.
To check out the original branch and stop rebasing, run "git rebase --abort".
Could not apply 8cd34d6... few fixes

should I fix that? I'm a bit surprised to see that.

**Comment by slava77** [comment]
On 9/5/16 8:29 AM, Ivan Shvetsov wrote:
> @slava77 <https://github.com/slava77> I'm trying to rebase -i as you
> requested to remove some irrelevant commits. I have started a new area
> and did
> git rebase -i CMSSW_8_1_X_2016-09-04-0000
> 
> and I'm getting some conflicts for some reason ...:
> error: could not apply 8cd34d6
> <https://github.com/cms-sw/cmssw/commit/8cd34d6148d9a16c0319e8fda7fe90e603d46578>...
> few fixes
> 
> When you have resolved this problem, run "git rebase --continue".
> If you prefer to skip this patch, run "git rebase --skip" instead.
> To check out the original branch and stop rebasing, run "git rebase
> --abort".
> Could not apply 8cd34d6
> <https://github.com/cms-sw/cmssw/commit/8cd34d6148d9a16c0319e8fda7fe90e603d46578>...
> few fixes
> 
> should I fix that? I'm a bit surprised to see that.

try to follow the instructions, in case it's just for one or two commits.

Given the long history of minor commits, which doesn't really describe
that well the feature development,
I  suggest to redo this with just a few descriptive commits.
(start a new test area, copy files there and apply new commits).

**Comment by ishvetso** [comment]
superseded by #15741

**Pull request closed without merging**
