### PR TITLE
Run3-gex66 Remove 2 unused solids, logical & physical volumes of PPS

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Remove 2 unused solids, logical & physical volumes of PPS

#### PR validation:

Tested with some private version. It will be incorporated later in the scenario definition

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@silviodonato @qliphy @cvuosalo @srimanob Can this be included in the pre6?

**Comment by srimanob** [comment]
Urgent

**Comment by civanch** [comment]
+1

**Comment by cvuosalo** [comment]
@bsunanda Thanks for fixing this.

**Comment by cvuosalo** [comment]
@wpcarvalho @jan-kaspar FYI

**Comment by cvuosalo** [comment]
@bsunanda Are you planning to change the 2021 scenario with this change in pre6?

**Comment by silviodonato** [comment]
+1

**Pull request merged**
