### PR TITLE
Further updates to the FastTimerService for 10.0.x

### PR DESCRIPTION
**Pull request by fwyzard**
Follow up on #21738 .

### CODE REVIEW

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by fwyzard** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
@fwyzard @Martin-Grunewald a minor remark: during the compilation you get

>> Subsystem Calibration built
gmake[1]: Entering directory '/build/cmsbld/jenkins/workspace/ib-any-integration/CMSSW_10_0_X_2018-01-15-2300'
tmp/slc6_amd64_gcc630/MakeData/DirCache.mk:30: No such file exists: src/HLTrigger/Timer/test/chrono/test/chrono.cc. Please fix src/HLTrigger/Timer/test/BuildFile.
tmp/slc6_amd64_gcc630/MakeData/DirCache.mk:30: No such file exists: src/HLTrigger/Timer/test/chrono/src/*.cc. Please fix src/HLTrigger/Timer/test/BuildFile.
tmp/slc6_amd64_gcc630/MakeData/DirCache.mk:30: No such file exists: src/HLTrigger/Timer/test/chrono/src/native/*.cc. Please fix src/HLTrigger/Timer/test/BuildFile.

as those files are no more there

**Comment by Martin-Grunewald** [comment]
Fixed in #21869

**Pull request merged**
