### PR TITLE
Switch to pfCandidates for b tagging for Puppi jets

### PR DESCRIPTION
**Pull request by ghost**
Solution to the issue discussed here: https://github.com/cms-sw/cmssw/pull/22608

Switch back to standard pfCandidates for b tagging also for Puppi jets, reverting the change introduced in: https://github.com/cms-sw/cmssw/pull/18666

This change was introduced as it was giving some b tagging performance improvement for Phase2, which is not there anymore with the new Puppi cuts for Phase 2.

Going back to pfCandidates for b tagging recovers in a satisfactory way the performance as shown in the red curves below. It's also a safer choice as it does not expose b tagging to changes in the Puppi algorithm and its parameters.

image

image

The performance of the red curves (standard b tagging with pfCandidates and Phase 2 Puppi cuts) is close now to the black curves, using special custom Phase 2 cuts, which was essentially the attempted solution in https://github.com/cms-sw/cmssw/pull/22608.

The PR can be backported to 93X and included in: https://github.com/cms-sw/cmssw/issues/22554

### CODE REVIEW

**Comment by imarches** [comment]
@kpedro88

**Comment by kpedro88** [comment]
assign upgrade

**Comment by kpedro88** [comment]
@imarches since this change only targets phase2, it should not modify the settings for other eras. Please restrict this change to be activated by a phase2 era.

**Comment by imarches** [comment]
This is on purpose targeting all eras.

The change in https://github.com/cms-sw/cmssw/pull/18666 was introduced as, with the Puppi cuts we had at the time, there were some performance gains for Phase 2. No meaningful performance improvement was seen elsewhere and it was extended to all eras just for consistency, as explained in https://github.com/cms-sw/cmssw/issues/18426

With the motivation gone for Phase 2 to keep things as in https://github.com/cms-sw/cmssw/pull/18666 , there is then no reason to keep that configuration in other eras.

**Comment by kpedro88** [comment]
please test

**Comment by kpedro88** [comment]
+1
changes limited to `slimmedJetsPuppi` collections in miniAOD

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/22696	d6822ae
- changes are as described
- jenkins tests pass and comparisons with the baseline show differences only in slimmedJetsPuppi pairDiscriVector data members. The changes have a somewhat common feature with a reduction in the default values of the discriminants. This is expected because we should now be getting more inputs.

Here is one plot for 136.7611 (JetHT Run2016E remini )
all_oldvsnew_runjetht2016ereminiaodwf136p7611c_min2 max-2 patjets_slimmedjetspuppi__pat_obj___pairdiscrivector__11__second

It appears that we still do not have any plots for the puppi jets btagging in the standard DQM.

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Pull request merged**
