### PR TITLE
Add missing newlines in Reconstruction modules

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Add missing newlines at the end of the files under
```
RecoBTag/Combined
RecoBTag/ImpactParameter
RecoBTag/PerformanceDB
RecoEgamma/EgammaIsolationAlgos
RecoEgamma/EgammaPhotonProducers
RecoLocalCalo/Configuration
RecoLocalCalo/EcalRecProducers
RecoLocalCalo/HGCalRecProducers
RecoLocalTracker/Configuration
RecoLocalTracker/SiPixelRecHits
RecoLocalTracker/SiStripClusterizer
RecoLocalTracker/SiStripZeroSuppression
RecoLuminosity/LumiDB
RecoLuminosity/LumiProducer
RecoMTD/TrackExtender
RecoMuon/TrackerSeedGenerator
RecoMuon/TrackingTools
```
.

#### PR validation:

None.

### CODE REVIEW

**Comment by francescobrivio** [comment]
+db

**Comment by jfernan2** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
