### PR TITLE
reduce cases of LogWarnings with InvalidHelix category in Pixel/Strip ClusterShape compatibility checks

### PR DESCRIPTION
**Pull request by slava77**
backport of #23209

another PR in the LogWarning reduction campaign

InvalidHelix is one of the leading LogWarnings in current pp processing.
It turns out that a large fraction (all?) of the warnings corresponds to the reference helix considered "invalid" because it was reduced to a straight line. This is actually a valid input.

FastCircle::isLine method is added to make the simple test.

There is no change to the physics results of the algorithms. A LogWarning is simply not issued anymore in the case that appears to already have a correct behavior.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/23242	dbab452
- jenkins tests pass and comparisons/logs show a reduction/removal of messages in InvalidHelix category

**Comment by slava77** [comment]
@fabiocos 
I see that several PRs were already merged after the last 10_1_X release (CMSSW_10_1_5).
Is there a reason to delay this PR?

**Comment by fabiocos** [comment]
+1

**Pull request merged**
