### PR TITLE
`BeamSpotOnlineProducer`: add more printouts in case of invalid errors

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

Yet another follow-up to https://github.com/cms-sw/cmssw/issues/45555. As discussed with @gennai, this PR adds an additional level of printout when the algorithm fails to find a valid beamspot from the `BeamSpotTransientObjectsRcd` and falls back to the DB-stored PCL value, in the case that the input errors are not valid (should never be the case, but since it got logged (see https://github.com/cms-sw/cmssw/issues/45555) it would be good to explicitly verify when it happens.
I profit of the PR to remove a couple of magic numbers for the beamspot covariance matrix size. 

#### PR validation:

`cmssw` compiles

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

To be backported to CMSSW_14_0_X for data-taking operations.

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mandrenguyen** [comment]
+reconstruction

**Comment by perrotta** [comment]
+alca

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
