### PR TITLE
Added 2d DQM plot for Heavy Ions UCC

### PR DESCRIPTION
**Pull request by istaslis**
Added 2d plot to monitor Heavy Ions UCC in DQM.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by deguio** [comment]
please submit to 76 and 80 as well.
thanks,
F.

**Comment by slava77** [comment]
@istaslis we'll need a PR in 80X
and then this will need to be signed off before this can be merged

**Comment by deguio** [comment]
+1

**Comment by slava77** [comment]
merge

**Comment by deguio** [comment]
@istaslis 
please submit to 76/80 as well.
thanks,
F.

**Comment by istaslis** [comment]
@BetterWang You asked me to make this PR and promised to look after 7/6 and 8/0 versions. Can you take care of that?
Thanks

**Comment by BetterWang** [comment]
@istaslis Done. Cheers.

**Pull request merged**
