### PR TITLE
Remove unit tests for HGCalRecProducers (covered by matrix now)

### PR DESCRIPTION
**Pull request by lgray**
As in title.

### CODE REVIEW

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/17010 32434e4
- as described
- jenkins tests pass

**Comment by davidlange6** [comment]
+1

**Pull request merged**
