### PR TITLE
 DataFormats/ParticleFlowReco - remove unused data formats

### PR DESCRIPTION
**Pull request by guitargeek**
#### PR description:

Follow up on https://github.com/cms-sw/cmssw/pull/26184, where a lot of the `PFClusterTools` code was removed. Actually, the removed code relied on several DataFormats with are now obsolete and should be removed as well.

By the way, are there any CMSSW policies on how we treat the DataFormats? Is their removal allowed, or should they stick in the release forever to ensure backwards compatibility of ROOT files?

#### PR validation:

Code compiles and local matrix tests pass.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
> By the way, are there any CMSSW policies on how we treat the DataFormats? Is their removal allowed, or should they stick in the release forever to ensure backwards compatibility of ROOT files?

We can remove DF classes including dictionaries for transient DFs (something that was never saved in production jobs).
It's worth to go back in history and check if the data was produced in the past.
@guitargeek do you happen to know which ones were used in the standard PF sequences?

For the  DFs that were saved in the past, but are no longer expected to be consumed, we can make a dummy dictionary to allow reading the old files. For this:  add a ```struct RemovedXYZClassName {} ;``` to classes.h.

Only if the old data is still needed for analysis it is worth to keep the DF implementation.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by guitargeek** [comment]
Hi @slava77, sorry I don't happen to know anything about how the classes were used, as they are from the "Snapshot of CMSSW_6_2_0_pre8" commit so it's hard to find some information in an associated PR or something. Maybe @hatakeyamak, @jpata or @bendavid are familiar with it?

The dummy dictionary sounds like a good option to me anyhow, as it probably does not add any compile time whatsoever, no? Then I would not see any drawback.

**Comment by slava77** [comment]
On 5/16/19 3:17 PM, Jonas Rembser wrote:
> The dummy dictionary sounds like a good option to me anyhow, as it
> probably does not add any compile time whatsoever, no? Then I would not
> see any drawback.
> 

I think that it will be OK to add them only after we see problems in I/O.
IIUC, none of the regular production samples have these classes persisted.

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/26670	e140507
- this is essentially a technical update to remove unused classes
- jenkins tests pass

**Comment by fabiocos** [comment]
+1

**Pull request merged**
