### PR TITLE
HLT customisation for 2016 detector

### PR DESCRIPTION
**Pull request by fwyzard**
Era-based customisation to adapt the 2017 HLT menu to the 2016 detector configuration

This adds a new `HLT_2016` era modifier to collect all HLT changes that should be applied for 2016 era, but should *not* be inherited by the 2017 and later eras.

The HF local reconstruction is reverted to the 2016 configuration.
The HBHE local reconstruction is kept as in 2017, given that the new modules should be able to handle both the "Phase 0" and "Phase 1" geometry.

The Pixel configuration needs to be added.

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
The GRun2016 cff file is STILL using /dev/CMSSW_9_0_0/GRun/V11
but should be /dev/CMSSW_9_0_1/...

**Comment by fwyzard** [comment]
I just deleted `HLTrigger/Configuration/python/HLT_GRun2016_cff.py` assuming we can make use of the GRun menu and pick the Era-based customisation centrally.
I don't know if this needs to be propagated anywhere else ?

**Comment by Martin-Grunewald** [comment]
Could the OnLine GRun2016 cfg file python-import somehow the OnLine GRun cfg file and apply the 2016 era, rather than containing a verbatim copy?

**Comment by Martin-Grunewald** [comment]
cmsDriver.csh would need an update to use GRun instead of GRun2016 in the corresponding commands.

**Comment by fwyzard** [comment]
> Could the OnLine GRun2016 cfg file python-import somehow the OnLine GRun cfg file and apply the 2016 era, rather than containing a verbatim copy?

I don't know how to do that :-(

**Comment by Martin-Grunewald** [comment]
me neither :( so let's leave the verbatim copy which is fine when the 2017 menu evolves so much that the reverse era is no longer feasible...

**Comment by davidlange6** [comment]
Closing PR. CMSSW_9_0_X development has completed (CMSSW_9_2_X is for data taking)

**Pull request closed without merging**
