### PR TITLE
Revert "[12_3_X] Use RAWEventContent parameter set for Repack output module"

### PR DESCRIPTION
**Pull request by perrotta**
Reverts cms-sw/cmssw#38017
See https://github.com/cms-sw/cmssw/pull/38017#issuecomment-1133130912

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by tvami** [comment]
Will this revert conflict now with German's fix?

**Comment by perrotta** [comment]
> Will this revert conflict now with German's fix, ie #38025 ?

https://github.com/cms-sw/cmssw/pull/38025 includes this revert: if we merge it, this revert PR can be closed
Just you guys (@tvami @germanfgv @drkovalskyi) decide what is needed to avoid issues at T0, and then it can be merged, and a patch release prepared in a few hours even during the week end. Just make sure that you all agree on it, and that the chosen solution has got a decent amount of testing.

**Comment by germanfgv** [comment]
@perrotta we need the change in compression algorithm, so I'd push for https://github.com/cms-sw/cmssw/pull/38025

**Comment by tvami** [comment]
I tested the output produced with https://github.com/cms-sw/cmssw/pull/38025, it works fine, see https://github.com/dmwm/T0/pull/4664#issuecomment-1133606803

**Comment by perrotta** [comment]
Closing: replaced by https://github.com/cms-sw/cmssw/pull/38025

**Pull request closed without merging**
