### PR TITLE
Fix TPTask occupancy plots (10_1_X)

### PR DESCRIPTION
**Pull request by DryRun**
The TPTask occupancy plots only get filled if both HBHE and HF TP digis have been found. This PR splits them apart. 

10_1_X version of #22553

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
-1

**Comment by fabiocos** [comment]
@DryRun there is a conflict to be solved before this PR can be merged, I assume this comes from the merge of #22435 , please fix it

**Comment by davidlange6** [comment]
Your PR is unmergeable. Please have a look and possibly rebase it.

**Comment by DryRun** [comment]
Hi, I rebased this PR off of CMSSW_10_1_0_pre2 + PR#22435, but there's still this box above that says there is a conflict... I don't understand why, so perhaps I can close this PR and start fresh from PR#22435? Sorry.

**Comment by jfernan2** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
