### PR TITLE
Steering scripts for O2Os

### PR DESCRIPTION
**Pull request by ggovi**
Added scripts for o2o steering in offline and online environments.
Includes the version  currently deployed.

### CODE REVIEW

**Comment by ggovi** [comment]
please test

**Comment by ggovi** [comment]
+1

**Comment by fabiocos** [comment]
@ggovi just a question, would not be better to have this tree under the scripts subdirectory?

**Comment by fabiocos** [comment]
@ggovi this could be considered afterwards, please let me know what you think anyway

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
@ggovi late comment (as in 10_1_X review): in your scripts 10_0_5 is mentioned, is this intended? These are standalone new scripts so I do not see how they could break existing workflows, but I would like to be sure that they are what is really needed...

**Pull request merged**
