### PR TITLE
produce dqm plots also in case of low stat

### PR DESCRIPTION
**Pull request by argiro**
remove an unwanted feature by which dqm plots are not generated for low stat runs

### CODE REVIEW

**Comment by arunhep** [comment]
please test

**Comment by lpernie** [comment]
+1

**Comment by fabiocos** [comment]
@argiro for my understanding, there is no condition in the code so as it could fail if there is not enough statistics?

**Comment by argiro** [comment]
if there is not enough statistics the code does not generate a new payload. However, we would still like to see the DQM plots

**Comment by fabiocos** [comment]
+1

**Pull request merged**
