### PR TITLE
MTD simulation and local reconstruction: code cleaning

### PR DESCRIPTION
**Pull request by casarsa**
#### PR description:

The obsolete and unused code has been removed from the SimFastTiming and RecoLocalFastTime packages, i.e. the code relative to the BTL design with scintillator tiles and the simple FTL device.

#### PR validation:

The purged code has been tested with the WF 23207.0 in CMSSW_11_1_X_2020-02-09-2300. The results of MTD simulation and local reconstruction are unaffected.

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by fabiocos** [comment]
@casarsa there is no change in name of persistent collections as far as I can see, am I correct?

**Comment by casarsa** [comment]
@fabiocos correct, the persistent collections remain the same

**Comment by casarsa** [comment]
This addresses fully #27450

**Comment by kpedro88** [comment]
resolves #27450

**Comment by kpedro88** [comment]
+upgrade

**Comment by fabiocos** [comment]
@kpedro88 @casarsa there is a corresponding cleaning in the SimG4CMS and geometry area that it is on my todo list

**Comment by perrotta** [comment]
+1
- Obsolete and unused code is removed from reco and sim packages, as well as the links to it in other part of the MTD code
- Jenkins tests pass

**Comment by silviodonato** [comment]
Any comment from simulation  @civanch  @mdhildreth ?

**Comment by civanch** [comment]
+1

**Comment by silviodonato** [comment]
please test workflow 23434.1001

**Comment by silviodonato** [comment]
+1

**Pull request merged**
