### PR TITLE
HLT menu migration to 12_3_0_pre6 template

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
#### PR description:

HLT menu migration to 12_3_0_pre6 template

#### PR validation:

TSG tests

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Backport of #37203 to 12_3_X for TSG/HLT/online use

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
backport of #37203

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by perrotta** [comment]
+1
- Succefully merged in master since CMSSW_12_4_X_2022-03-11-2300

**Pull request merged**
