### PR TITLE
Fastsim tracking add dedx collection - backport to 10_2_X

### PR DESCRIPTION
**Pull request by ssekmen**
backport of #25512 

"Modified code in FastSimulation/SimplifiedParticlePropagator/ package to make de/dx collections. This involved adding the plugin FastTrackDeDxProducer.cc and modifying FastTrackerRecHits.[.h, .cc], as well as adding a data member to the class DataFormats/TrackerRecHit2D/interface/FastTrackerRecHit.h called energyLoss."

### CODE REVIEW

**Comment by ssekmen** [comment]
please test

**Comment by ssekmen** [comment]
+1

**Comment by perrotta** [comment]
+1
- Backport identical to #25512, already merged in master
- For reco, this PR just adds dedx to the FastTrackerRecHit data format; that class (as well as its derived ones) only enters in FastSim related stuffs
- Jenkins tests pass and show no differences

**Comment by srimanob** [comment]
@ssekmen Is this PR needed for 2018 fastsim production?

**Comment by ssekmen** [comment]
It is not needed for all production, but only for a few special samples.

**Comment by fabiocos** [comment]
hold

from @franzoni @srimanob : this is not needed by SUSY production so far in 10_2_X

**Comment by slava77** [comment]
@ssekmen  @fabiocos 
should we close this PR?
Please comment otherwise if it should stay open.
Thank you.

**Comment by fabiocos** [comment]
@ssekmen @sbein as agreed I close this PR

**Pull request closed without merging**
