### PR TITLE
add bunch crossing as index to pixel counters

### PR DESCRIPTION
**Pull request by capalmer85**

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/8944	b5ace6a
changes in the code look reasonable for an ntupler code.
jenkins compiled the 7fdd24f  commit  OK; the updates in b5ace6a look trivial.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
