### PR TITLE
Minor improvements to Alpaka tests [13.0.x]

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

This PR makes some minor improvements to the Alpaka stand-alone and framework-based tests, that came up during the Alpaka tutorials on the 16-17 February:
  - remove one leftover import from `writer.py`
  - simplify getting the `Device` type from the `Queue` in `AlpakaESTestData.h`
  - migrate the test modules from `stream` to `global`
  - allocate host buffers in pinned memory accessible by the `Platform` devices in `testKernel.dev.cc`

#### PR validation:

All unit tests pass.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport of https://github.com/cms-sw/cmssw/pull/40808 to 13.0.x for consistency.

### CODE REVIEW

**Comment by fwyzard** [comment]
backport #40808

**Comment by fwyzard** [comment]
type bugfix

**Comment by fwyzard** [comment]
enable gpu

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
Note: currently this PR includes https://github.com/cms-sw/cmssw/pull/40796.

**Comment by fwyzard** [comment]
I changed the base branch and back again to force GitHub to re-evaluate the list of commits included in the PR.

**Comment by perrotta** [comment]
+1

**Pull request merged**
