### PR TITLE
Adding scal monitoring to online DQM (74x)

### PR DESCRIPTION
**Pull request by dmitrijus**
A backport from https://github.com/cms-sw/cmssw/pull/10298

This PR replaces https://github.com/cms-sw/cmssw/pull/10282,
which should be closed as it misses a few changes.

Dmitrijus

### CODE REVIEW

**Comment by danduggan** [comment]
@dmitrijus, thanks for the rebase - can you also move the scal config file from python/test to python/clients?

**Comment by dmitrijus** [comment]
Hi @danduggan,

the whole reason for the rebase is that I want all branches aligned
before I am changing this config.

I will wait for this PR to be included and only afterwards
make another PR to change it (together for all 3 branches).

**Comment by danduggan** [comment]
@dmitrijus, sure np, we can work around this in online for the moment.

**Comment by danduggan** [comment]
please test

**Comment by deguio** [comment]
please submit to 76 as well.
thanks,
F.

**Comment by deguio** [comment]
please test

**Comment by danduggan** [comment]
@deguio, this has already been merged in 76x, only needed in 74x and 75x to make everything consistent

**Comment by deguio** [comment]
+1

**Comment by deguio** [comment]
with this PR in all the three branches are now in synch. another PR will move the online config application to DQM/Integration/python/configs

**Comment by davidlange6** [comment]
+1

**Pull request merged**
