### PR TITLE
Using CP5 tune generator fragments for Phase2/Run3 RelVal samples

### PR DESCRIPTION
**Pull request by siddhesh86**
PR includes
1) Added a few generator fragments (e.g. TTbar, MinBias at 14TeV) with CP5 tune, intended to use for phase2 RelVal production in CMSSW release validation
2) Added new generator fragments needed for phase2 RelVal production in CMSSW release validation
3) Added corresponding entries for 1) and 2) in the RelVa submission macros (upgradeWorkflowComponents.py, relval_steps.py)
4) MatrixInjector.py: wmsplit set to 1 for high PU RelVal submission for recent detector configurations (D35, D49 etc). It is needed to run highPU phase2 workflows smoothly in the computing system.

### CODE REVIEW

**Comment by smuzaffar** [comment]
@siddhesh86 , can you please resolve the conflit?

**Comment by siddhesh86** [comment]
@smuzaffar, the conflict has been resolved. Thanks.

**Comment by kpedro88** [comment]
@efeyazgan, @agrohsje, @alberto-sanchez, @qliphy do we no longer put the tune name in the fragment? This seems potentially confusing to me.

**Comment by efeyazgan** [comment]
@kpedro88 yes, we should definitely have the tune names in the fragments. @siddhesh86 please update the fragments.

**Comment by chayanit** [comment]
@silviodonato I would like to have this PR in 11_1_0_pre3 if possible. I was traveling so didn't join release meeting today, when will you create pre3? @siddhesh86 could you make change soon?

**Comment by silviodonato** [comment]
urgent

**Comment by silviodonato** [comment]
@chayanit I will try to include it. It depends on how much time will take the update and review of this PR.

**Comment by siddhesh86** [comment]
@chayanit, @silviodonato, @kpedro88, @efeyazgan:    
The suggested corrections in the generator fragments including tune name are implemented and another PR (https://github.com/cms-sw/cmssw/pull/28932) is created including these corrections. Please continue/move to the PR28932.
Thank you.

**Comment by kpedro88** [comment]
please close

**Pull request closed without merging**
