### PR TITLE
Migration to ConfDb 14_0_0_pre3 template and addOnTests bug fix [14_1_X]

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
#### PR description:

Migration to ConfDb 14_0_0_pre3 template and addOnTests bug fix [14_1_X]

#### PR validation:

TSG tests

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

To be backported to 14_0 (data taking release)

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by mmusich** [comment]
> DQMHistoSizes: changed ( 141.042,... ): -0.001 KiB HLT/Filters

there is a bunch of changes in the DQM plots of EGamma HLT http://tinyurl.com/25daobvz that I don't necessarily understand.
@Sam-Harper FYI.

**Comment by Martin-Grunewald** [comment]
Seems to be a problem with Dphi.

**Comment by mmusich** [comment]
hold

indeed:

```
hltGetConfiguration /dev/CMSSW_14_0_0/GRun --globaltag auto:phase1_2024_realistic --mc --unprescale --output minimal --max-events 100 --input /store/mc/Run3Winter24Digi/TT_TuneCP5_13p6TeV_powheg-pythia8/GEN-SIM-RAW/133X_mcRun3_2024_realistic_v8-v2/80000/dc984f7f-2e54-48c4-8950-5daa848b6db9.root --eras Run3 --l1-emulator uGT --l1 L1Menu_Collisions2023_v1_3_0_xml > hlt_14_0_0.py
```

followed by:

```
edmConfigDump hlt_14_0_0.py > hlt_14_0_0_dump_Custom.py
# edit HLTrigger/Configuration/python/customizeHLTforCMSSW.py to remove customizations
edmConfigDump hlt_14_0_0.py > hlt_14_0_0_dump_noCustom.py
diff --color -u hlt_14_0_0_dump_Custom.py hlt_14_0_0_dump_noCustom.py
```

yields

```diff
--- hlt_14_0_0_dump_Custom.py	2024-02-08 18:32:10.172905624 +0100
+++ hlt_14_0_0_dump_noCustom.py	2024-02-08 18:23:54.259174303 +0100
@@ -46898,7 +46898,7 @@
     thrOverEEE = cms.vdouble(-1.0),
     thrRegularEB = cms.vdouble(0.1),
     thrRegularEE = cms.vdouble(0.1),
-    useAbs = cms.bool(True),
+    useAbs = cms.bool(False),
     useEt = cms.bool(True),
     varTag = cms.InputTag("hltEgammaGsfTrackVars","Dphi")
 )
@@ -47115,7 +47115,7 @@
     thrOverEEE = cms.vdouble(-1.0),
     thrRegularEB = cms.vdouble(0.07),
     thrRegularEE = cms.vdouble(0.1),
-    useAbs = cms.bool(True),
+    useAbs = cms.bool(False),
     useEt = cms.bool(True),
     varTag = cms.InputTag("hltEgammaGsfTrackVars","Dphi")
 )
@@ -47332,7 +47332,7 @@
     thrOverEEE = cms.vdouble(-1.0),
     thrRegularEB = cms.vdouble(0.1),
     thrRegularEE = cms.vdouble(0.1),
-    useAbs = cms.bool(True),
+    useAbs = cms.bool(False),
     useEt = cms.bool(True),
     varTag = cms.InputTag("hltEgammaGsfTrackVars","Dphi")
 )
@@ -47549,7 +47549,7 @@
     thrOverEEE = cms.vdouble(-1.0),
     thrRegularEB = cms.vdouble(0.07),
     thrRegularEE = cms.vdouble(0.1),
-    useAbs = cms.bool(True),
+    useAbs = cms.bool(False),
     useEt = cms.bool(True),
     varTag = cms.InputTag("hltEgammaGsfTrackVars","Dphi")
 )
@@ -50641,7 +50641,7 @@
     thrOverEEE = cms.vdouble(-1.0),
     thrRegularEB = cms.vdouble(0.2),
     thrRegularEE = cms.vdouble(0.2),
-    useAbs = cms.bool(True),
+    useAbs = cms.bool(False),
     useEt = cms.bool(False),
     varTag = cms.InputTag("hltEgammaGsfTrackVars","Dphi")
 )
@@ -50925,7 +50925,7 @@
     thrOverEEE = cms.vdouble(-1.0),
     thrRegularEB = cms.vdouble(0.02),
     thrRegularEE = cms.vdouble(0.023),
-    useAbs = cms.bool(True),
+    useAbs = cms.bool(False),
     useEt = cms.bool(False),
     varTag = cms.InputTag("hltEgammaGsfTrackVars","Dphi")
 )
@@ -51216,7 +51216,7 @@
     thrOverEEE = cms.vdouble(-1.0),
     thrRegularEB = cms.vdouble(0.2),
     thrRegularEE = cms.vdouble(0.2),
-    useAbs = cms.bool(True),
+    useAbs = cms.bool(False),
     useEt = cms.bool(False),
     varTag = cms.InputTag("hltEgammaGsfTrackVars","Dphi")
 )
@@ -51484,7 +51484,7 @@
     thrOverEEE = cms.vdouble(-1.0),
     thrRegularEB = cms.vdouble(0.2),
     thrRegularEE = cms.vdouble(0.2),
-    useAbs = cms.bool(True),
+    useAbs = cms.bool(False),
     useEt = cms.bool(False),
     varTag = cms.InputTag("hltEgammaGsfTrackVars","Dphi")
 )
@@ -51752,7 +51752,7 @@
     thrOverEEE = cms.vdouble(-1.0),
     thrRegularEB = cms.vdouble(0.2),
     thrRegularEE = cms.vdouble(0.2),
-    useAbs = cms.bool(True),
+    useAbs = cms.bool(False),
     useEt = cms.bool(False),
     varTag = cms.InputTag("hltEgammaGsfTrackVars","Dphi")
 )
@@ -52020,7 +52020,7 @@
     thrOverEEE = cms.vdouble(-1.0),
     thrRegularEB = cms.vdouble(0.2),
     thrRegularEE = cms.vdouble(0.2),
-    useAbs = cms.bool(True),
+    useAbs = cms.bool(False),
     useEt = cms.bool(False),
     varTag = cms.InputTag("hltEgammaGsfTrackVars","Dphi")
 )
@@ -52288,7 +52288,7 @@
     thrOverEEE = cms.vdouble(-1.0),
     thrRegularEB = cms.vdouble(0.2),
     thrRegularEE = cms.vdouble(0.2),
-    useAbs = cms.bool(True),
+    useAbs = cms.bool(False),
     useEt = cms.bool(False),
     varTag = cms.InputTag("hltEgammaGsfTrackVars","Dphi")
 )
@@ -52556,7 +52556,7 @@
     thrOverEEE = cms.vdouble(-1.0),
     thrRegularEB = cms.vdouble(0.2),
     thrRegularEE = cms.vdouble(0.2),
-    useAbs = cms.bool(True),
+    useAbs = cms.bool(False),
     useEt = cms.bool(False),
     varTag = cms.InputTag("hltEgammaGsfTrackVars","Dphi")
 )
@@ -52824,7 +52824,7 @@
     thrOverEEE = cms.vdouble(-1.0),
     thrRegularEB = cms.vdouble(0.2),
     thrRegularEE = cms.vdouble(0.2),
-    useAbs = cms.bool(True),
+    useAbs = cms.bool(False),
     useEt = cms.bool(False),
     varTag = cms.InputTag("hltEgammaGsfTrackVars","Dphi")
 )
@@ -53092,7 +53092,7 @@
     thrOverEEE = cms.vdouble(-1.0),
     thrRegularEB = cms.vdouble(0.2),
     thrRegularEE = cms.vdouble(0.2),
-    useAbs = cms.bool(True),
+    useAbs = cms.bool(False),
     useEt = cms.bool(False),
     varTag = cms.InputTag("hltEgammaGsfTrackVars","Dphi")
 )
@@ -53318,7 +53318,7 @@
     thrOverEEE = cms.vdouble(-1.0),
     thrRegularEB = cms.vdouble(0.1),
     thrRegularEE = cms.vdouble(0.05),
-    useAbs = cms.bool(True),
+    useAbs = cms.bool(False),
     useEt = cms.bool(True),
     varTag = cms.InputTag("hltEgammaGsfTrackVars","Dphi")
 )
@@ -53485,7 +53485,7 @@
     thrOverEEE = cms.vdouble(-1.0),
     thrRegularEB = cms.vdouble(0.2),
     thrRegularEE = cms.vdouble(0.2),
-    useAbs = cms.bool(True),
+    useAbs = cms.bool(False),
     useEt = cms.bool(False),
     varTag = cms.InputTag("hltEgammaGsfTrackVars","Dphi")
 )
@@ -53753,7 +53753,7 @@
     thrOverEEE = cms.vdouble(-1.0),
     thrRegularEB = cms.vdouble(0.2),
     thrRegularEE = cms.vdouble(0.2),
-    useAbs = cms.bool(True),
+    useAbs = cms.bool(False),
     useEt = cms.bool(False),
     varTag = cms.InputTag("hltEgammaGsfTrackVars","Dphi")
 )
@@ -54021,7 +54021,7 @@
     thrOverEEE = cms.vdouble(-1.0),
     thrRegularEB = cms.vdouble(0.2),
     thrRegularEE = cms.vdouble(0.2),
-    useAbs = cms.bool(True),
+    useAbs = cms.bool(False),
     useEt = cms.bool(False),
     varTag = cms.InputTag("hltEgammaGsfTrackVars","Dphi")
 )
@@ -54289,7 +54289,7 @@
     thrOverEEE = cms.vdouble(-1.0),
     thrRegularEB = cms.vdouble(0.2),
     thrRegularEE = cms.vdouble(0.2),
-    useAbs = cms.bool(True),
+    useAbs = cms.bool(False),
     useEt = cms.bool(False),
     varTag = cms.InputTag("hltEgammaGsfTrackVars","Dphi")
 )
@@ -62915,7 +62915,7 @@
     thrOverEEE = cms.vdouble(-1.0),
     thrRegularEB = cms.vdouble(0.07),
     thrRegularEE = cms.vdouble(0.07),
-    useAbs = cms.bool(True),
+    useAbs = cms.bool(False),
     useEt = cms.bool(True),
     varTag = cms.InputTag("hltEgammaGsfTrackVars","Dphi")
 )
@@ -63015,7 +63015,7 @@
     thrOverEEE = cms.vdouble(-1.0),
     thrRegularEB = cms.vdouble(0.07),
     thrRegularEE = cms.vdouble(0.1),
-    useAbs = cms.bool(True),
+    useAbs = cms.bool(False),
     useEt = cms.bool(True),
     varTag = cms.InputTag("hltEgammaGsfTrackVars","Dphi")
 )
@@ -63332,7 +63332,7 @@
     thrOverEEE = cms.vdouble(-1.0),
     thrRegularEB = cms.vdouble(0.02),
     thrRegularEE = cms.vdouble(0.023),
-    useAbs = cms.bool(True),
+    useAbs = cms.bool(False),
     useEt = cms.bool(False),
     varTag = cms.InputTag("hltEgammaGsfTrackVars","Dphi")
 )
@@ -63548,7 +63548,7 @@
     thrOverEEE = cms.vdouble(-1.0),
     thrRegularEB = cms.vdouble(0.07),
     thrRegularEE = cms.vdouble(0.07),
-    useAbs = cms.bool(True),
+    useAbs = cms.bool(False),
     useEt = cms.bool(True),
     varTag = cms.InputTag("hltEgammaGsfTrackVars","Dphi")
 )
@@ -63715,7 +63715,7 @@
     thrOverEEE = cms.vdouble(-1.0),
     thrRegularEB = cms.vdouble(0.07),
     thrRegularEE = cms.vdouble(0.1),
-    useAbs = cms.bool(True),
+    useAbs = cms.bool(False),
     useEt = cms.bool(True),
     varTag = cms.InputTag("hltEgammaGsfTrackVars","Dphi")
 )
@@ -63740,7 +63740,7 @@
     thrOverEEE = cms.vdouble(-1.0),
     thrRegularEB = cms.vdouble(0.07),
     thrRegularEE = cms.vdouble(0.1),
-    useAbs = cms.bool(True),
+    useAbs = cms.bool(False),
     useEt = cms.bool(True),
     varTag = cms.InputTag("hltEgammaGsfTrackVars","Dphi")
 )
@@ -64189,7 +64189,7 @@
     thrOverEEE = cms.vdouble(-1.0),
     thrRegularEB = cms.vdouble(0.025),
     thrRegularEE = cms.vdouble(0.025),
-    useAbs = cms.bool(True),
+    useAbs = cms.bool(False),
     useEt = cms.bool(True),
     varTag = cms.InputTag("hltEgammaGsfTrackVars","Dphi")
 )
@@ -64514,7 +64514,7 @@
     thrOverEEE = cms.vdouble(-1.0),
     thrRegularEB = cms.vdouble(0.07),
     thrRegularEE = cms.vdouble(0.1),
-    useAbs = cms.bool(True),
+    useAbs = cms.bool(False),
     useEt = cms.bool(True),
     varTag = cms.InputTag("hltEgammaGsfTrackVars","Dphi")
 )
@@ -64539,7 +64539,7 @@
     thrOverEEE = cms.vdouble(-1.0),
     thrRegularEB = cms.vdouble(0.07),
     thrRegularEE = cms.vdouble(0.1),
-    useAbs = cms.bool(True),
+    useAbs = cms.bool(False),
     useEt = cms.bool(True),
     varTag = cms.InputTag("hltEgammaGsfTrackVars","Dphi")
 )
@@ -64564,7 +64564,7 @@
     thrOverEEE = cms.vdouble(-1.0),
     thrRegularEB = cms.vdouble(0.07),
     thrRegularEE = cms.vdouble(0.1),
-    useAbs = cms.bool(True),
+    useAbs = cms.bool(False),
     useEt = cms.bool(True),
     varTag = cms.InputTag("hltEgammaGsfTrackVars","Dphi")
 )
@@ -64919,7 +64919,7 @@
     thrOverEEE = cms.vdouble(-1.0),
     thrRegularEB = cms.vdouble(0.1),
     thrRegularEE = cms.vdouble(0.05),
-    useAbs = cms.bool(True),
+    useAbs = cms.bool(False),
     useEt = cms.bool(True),
     varTag = cms.InputTag("hltEgammaGsfTrackVars","Dphi")
 )
@@ -65125,7 +65125,7 @@
     thrOverEEE = cms.vdouble(-1.0),
     thrRegularEB = cms.vdouble(0.02),
     thrRegularEE = cms.vdouble(0.023),
-    useAbs = cms.bool(True),
+    useAbs = cms.bool(False),
     useEt = cms.bool(False),
     varTag = cms.InputTag("hltEgammaGsfTrackVars","Dphi")
 )
@@ -65399,7 +65399,7 @@
     thrOverEEE = cms.vdouble(-1.0),
     thrRegularEB = cms.vdouble(0.02),
     thrRegularEE = cms.vdouble(0.023),
-    useAbs = cms.bool(True),
+    useAbs = cms.bool(False),
     useEt = cms.bool(False),
     varTag = cms.InputTag("hltEgammaGsfTrackVars","Dphi")
 )
@@ -65640,7 +65640,7 @@
     thrOverEEE = cms.vdouble(-1.0),
     thrRegularEB = cms.vdouble(0.07),
     thrRegularEE = cms.vdouble(0.1),
-    useAbs = cms.bool(True),
+    useAbs = cms.bool(False),
     useEt = cms.bool(True),
     varTag = cms.InputTag("hltEgammaGsfTrackVars","Dphi")
 )
@@ -65896,7 +65896,7 @@
     thrOverEEE = cms.vdouble(-1.0),
     thrRegularEB = cms.vdouble(0.1),
     thrRegularEE = cms.vdouble(0.05),
-    useAbs = cms.bool(True),
+    useAbs = cms.bool(False),
     useEt = cms.bool(True),
     varTag = cms.InputTag("hltEgammaGsfTrackVars","Dphi")
 )
@@ -66088,7 +66088,7 @@
     thrOverEEE = cms.vdouble(-1.0),
     thrRegularEB = cms.vdouble(0.07),
     thrRegularEE = cms.vdouble(0.1),
-    useAbs = cms.bool(True),
+    useAbs = cms.bool(False),
     useEt = cms.bool(True),
     varTag = cms.InputTag("hltEgammaGsfTrackVars","Dphi")
 )
@@ -66113,7 +66113,7 @@
     thrOverEEE = cms.vdouble(-1.0),
     thrRegularEB = cms.vdouble(0.07),
     thrRegularEE = cms.vdouble(0.1),
-    useAbs = cms.bool(True),
+    useAbs = cms.bool(False),
     useEt = cms.bool(True),
     varTag = cms.InputTag("hltEgammaGsfTrackVars","Dphi")
 )
@@ -66604,7 +66604,7 @@
     thrOverEEE = cms.vdouble(-1.0),
     thrRegularEB = cms.vdouble(0.02),
     thrRegularEE = cms.vdouble(0.023),
-    useAbs = cms.bool(True),
+    useAbs = cms.bool(False),
     useEt = cms.bool(False),
     varTag = cms.InputTag("hltEgammaGsfTrackVars","Dphi")
 )
@@ -67177,7 +67177,7 @@
     thrOverEEE = cms.vdouble(-1.0),
     thrRegularEB = cms.vdouble(0.1),
     thrRegularEE = cms.vdouble(0.1),
-    useAbs = cms.bool(True),
+    useAbs = cms.bool(False),
     useEt = cms.bool(True),
     varTag = cms.InputTag("hltEgammaGsfTrackVars","Dphi")
 )
@@ -67536,7 +67536,7 @@
     thrOverEEE = cms.vdouble(-1.0),
     thrRegularEB = cms.vdouble(0.02),
     thrRegularEE = cms.vdouble(0.023),
-    useAbs = cms.bool(True),
+    useAbs = cms.bool(False),
     useEt = cms.bool(False),
     varTag = cms.InputTag("hltEgammaGsfTrackVars","Dphi")
 )
@@ -67854,7 +67854,7 @@
     thrOverEEE = cms.vdouble(-1.0),
     thrRegularEB = cms.vdouble(0.02),
     thrRegularEE = cms.vdouble(0.023),
-    useAbs = cms.bool(True),
+    useAbs = cms.bool(False),
     useEt = cms.bool(False),
     varTag = cms.InputTag("hltEgammaGsfTrackVars","Dphi")
 )
@@ -68161,7 +68161,7 @@
     thrOverEEE = cms.vdouble(-1.0),
     thrRegularEB = cms.vdouble(0.02),
     thrRegularEE = cms.vdouble(0.023),
-    useAbs = cms.bool(True),
+    useAbs = cms.bool(False),
     useEt = cms.bool(False),
     varTag = cms.InputTag("hltEgammaGsfTrackVars","Dphi")
 )
@@ -68468,7 +68468,7 @@
     thrOverEEE = cms.vdouble(-1.0),
     thrRegularEB = cms.vdouble(0.02),
     thrRegularEE = cms.vdouble(0.023),
-    useAbs = cms.bool(True),
+    useAbs = cms.bool(False),
     useEt = cms.bool(False),
     varTag = cms.InputTag("hltEgammaGsfTrackVars","Dphi")
 )
@@ -68775,7 +68775,7 @@
     thrOverEEE = cms.vdouble(-1.0),
     thrRegularEB = cms.vdouble(0.02),
     thrRegularEE = cms.vdouble(0.023),
-    useAbs = cms.bool(True),
+    useAbs = cms.bool(False),
     useEt = cms.bool(False),
     varTag = cms.InputTag("hltEgammaGsfTrackVars","Dphi")
 )
@@ -69132,7 +69132,7 @@
     thrOverEEE = cms.vdouble(-1.0),
     thrRegularEB = cms.vdouble(0.02),
     thrRegularEE = cms.vdouble(0.023),
-    useAbs = cms.bool(True),
+    useAbs = cms.bool(False),
     useEt = cms.bool(False),
     varTag = cms.InputTag("hltEgammaGsfTrackVars","Dphi")
 )
@@ -69489,7 +69489,7 @@
     thrOverEEE = cms.vdouble(-1.0),
     thrRegularEB = cms.vdouble(0.02),
     thrRegularEE = cms.vdouble(0.023),
-    useAbs = cms.bool(True),
+    useAbs = cms.bool(False),
     useEt = cms.bool(False),
     varTag = cms.InputTag("hltEgammaGsfTrackVars","Dphi")
 )
@@ -69796,7 +69796,7 @@
     thrOverEEE = cms.vdouble(-1.0),
     thrRegularEB = cms.vdouble(0.02),
     thrRegularEE = cms.vdouble(0.023),
-    useAbs = cms.bool(True),
+    useAbs = cms.bool(False),
     useEt = cms.bool(False),
     varTag = cms.InputTag("hltEgammaGsfTrackVars","Dphi")
 )
@@ -70081,7 +70081,7 @@
     thrOverEEE = cms.vdouble(-1.0),
     thrRegularEB = cms.vdouble(0.06),
     thrRegularEE = cms.vdouble(0.06),
-    useAbs = cms.bool(True),
+    useAbs = cms.bool(False),
     useEt = cms.bool(True),
     varTag = cms.InputTag("hltEgammaGsfTrackVars","Dphi")
 )
@@ -70268,7 +70268,7 @@
     thrOverEEE = cms.vdouble(-1.0),
     thrRegularEB = cms.vdouble(0.025),
     thrRegularEE = cms.vdouble(0.025),
-    useAbs = cms.bool(True),
+    useAbs = cms.bool(False),
     useEt = cms.bool(True),
     varTag = cms.InputTag("hltEgammaGsfTrackVars","Dphi")
 )
@@ -70576,7 +70576,7 @@
     thrOverEEE = cms.vdouble(-1.0),
     thrRegularEB = cms.vdouble(0.02),
     thrRegularEE = cms.vdouble(0.023),
-    useAbs = cms.bool(True),
+    useAbs = cms.bool(False),
     useEt = cms.bool(False),
     varTag = cms.InputTag("hltEgammaGsfTrackVars","Dphi")
 )
@@ -70850,7 +70850,7 @@
     thrOverEEE = cms.vdouble(-1.0),
     thrRegularEB = cms.vdouble(0.07),
     thrRegularEE = cms.vdouble(0.1),
-    useAbs = cms.bool(True),
+    useAbs = cms.bool(False),
     useEt = cms.bool(True),
     varTag = cms.InputTag("hltEgammaGsfTrackVars","Dphi")
 )
@@ -71106,7 +71106,7 @@
     thrOverEEE = cms.vdouble(-1.0),
     thrRegularEB = cms.vdouble(0.1),
     thrRegularEE = cms.vdouble(0.05),
-    useAbs = cms.bool(True),
+    useAbs = cms.bool(False),
     useEt = cms.bool(True),
     varTag = cms.InputTag("hltEgammaGsfTrackVars","Dphi")
 )
@@ -86376,7 +86376,7 @@
     thrOverEEE = cms.vdouble(-1.0),
     thrRegularEB = cms.vdouble(0.07),
     thrRegularEE = cms.vdouble(0.1),
-    useAbs = cms.bool(True),
+    useAbs = cms.bool(False),
     useEt = cms.bool(True),
     varTag = cms.InputTag("hltEgammaGsfTrackVars","Dphi")
 )
@@ -87090,7 +87090,7 @@
     thrOverEEE = cms.vdouble(-1.0),
     thrRegularEB = cms.vdouble(0.07),
     thrRegularEE = cms.vdouble(0.1),
-    useAbs = cms.bool(True),
+    useAbs = cms.bool(False),
     useEt = cms.bool(True),
     varTag = cms.InputTag("hltEgammaGsfTrackVars","Dphi")
 )
@@ -87654,7 +87654,7 @@
     thrOverEEE = cms.vdouble(-1.0),
     thrRegularEB = cms.vdouble(0.07),
     thrRegularEE = cms.vdouble(0.1),
-    useAbs = cms.bool(True),
+    useAbs = cms.bool(False),
     useEt = cms.bool(True),
     varTag = cms.InputTag("hltEgammaGsfTrackVars","Dphi")
 )
@@ -87888,7 +87888,7 @@
     thrOverEEE = cms.vdouble(-1.0),
     thrRegularEB = cms.vdouble(0.1),
     thrRegularEE = cms.vdouble(0.05),
-    useAbs = cms.bool(True),
+    useAbs = cms.bool(False),
     useEt = cms.bool(True),
     varTag = cms.InputTag("hltEgammaGsfTrackVars","Dphi")
 )
@@ -88084,7 +88084,7 @@
     thrOverEEE = cms.vdouble(-1.0),
     thrRegularEB = cms.vdouble(0.07),
     thrRegularEE = cms.vdouble(0.1),
-    useAbs = cms.bool(True),
+    useAbs = cms.bool(False),
     useEt = cms.bool(True),
     varTag = cms.InputTag("hltEgammaGsfTrackVars","Dphi")
 )
@@ -97049,7 +97049,7 @@
     thrOverEEE = cms.vdouble(-1.0),
     thrRegularEB = cms.vdouble(0.2),
     thrRegularEE = cms.vdouble(0.2),
-    useAbs = cms.bool(True),
+    useAbs = cms.bool(False),
     useEt = cms.bool(False),
     varTag = cms.InputTag("hltEgammaGsfTrackVars","Dphi")
 )
@@ -97236,7 +97236,7 @@
     thrOverEEE = cms.vdouble(-1.0),
     thrRegularEB = cms.vdouble(0.2),
     thrRegularEE = cms.vdouble(0.2),
-    useAbs = cms.bool(True),
+    useAbs = cms.bool(False),
     useEt = cms.bool(False),
     varTag = cms.InputTag("hltEgammaGsfTrackVars","Dphi")
 )
```

**Comment by Martin-Grunewald** [comment]
unhold

**Comment by mmusich** [comment]
unhold

**Comment by mmusich** [comment]
+hlt

**Comment by Martin-Grunewald** [comment]
+1

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
