### PR TITLE
Add missing newlines in EventFilter modules

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Add missing newlines at the end of the files under
```
EventFilter/CTPPSRawToDigi
EventFilter/L1ScoutingRawToDigi
EventFilter/Utilities
```
.

#### PR validation:

None.

### CODE REVIEW

**Comment by fwyzard** [comment]
please test

**Comment by smorovic** [comment]
+daq

**Comment by jfernan2** [comment]
+1

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
