### PR TITLE
extend Modifier boolean expressions to include "not" and "or" [94X]

### PR DESCRIPTION
**Pull request by kpedro88**
This is a *partial* backport of #22210. Only the changes in `FWCore/ParameterSet/python/Config.py` were backported. The additional `Modifier` functionality is needed in 94X for the ongoing fastsim backport.

attn: @makortel @ssekmen

### CODE REVIEW

**Comment by kpedro88** [comment]
please test

**Comment by Dr15Jones** [comment]
+1
The unit test failure is unrelated to this pull request.

**Comment by fabiocos** [comment]
please test

**Comment by kpedro88** [comment]
@fabiocos please merge, the unit test failure is the usual one due to wrong file path, unrelated to this PR

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Pull request merged**
