### PR TITLE
Fixes in HLTriggerOffline/SUSYBSM

### PR DESCRIPTION
**Pull request by jruizvar**
Fix some of the problems in the HLT SUSY Validation package reported here:
https://indico.cern.ch/event/371137/contribution/1/material/slides/0.pdf

The corrections of names are made according to trigger menu /dev/CMSSW_7_4_0/GRun/V6

### CODE REVIEW

**Comment by deguio** [comment]
@jruizvar could you please submit to 75 first? I would like to see this PR merged there first.
thanks,
F.

**Comment by jruizvar** [comment]
Hi Federico,
The PR for 75 (#8177) is done.

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request closed without merging**
