### PR TITLE
increasing lumi range for 2016E relvals

### PR DESCRIPTION
**Pull request by fabozzi**
I have increased the lumi range for 2016E relvals, following the discussion here:
https://github.com/cms-sw/cmssw/commit/e2f9d1516b182e94fe182184e8069b7793641e49#commitcomment-19659749

### CODE REVIEW

**Comment by fabozzi** [comment]
please test

**Comment by davidlange6** [comment]
hum, I had assumed we were decreasing the set of lumis to remove lumis with no data..

**Comment by davidlange6** [comment]
I realize the real issue is that cmsDriver run by a user does not use the lumi section window that you are setting.

das_client --limit 0 --query 'file dataset=/MuOnia/Run2016E-v2/RAW run=277069'

which is due to a deficiency in way the 2016E ls definition is made or with the InputInfo class implementation. I can't tell which.

**Comment by fabozzi** [comment]
I have downloaded and tested locally the cmsDriver of the wf:

step2 --datatier FEVTDEBUGHLT --conditions auto:run2_hlt_relval -s L1REPACK:Full,HLT:@relval2016 --process reHLT --data --era Run2_2016 --eventcontent FEVTDEBUGHLT --io HLTDR2_2016.io --python HLTDR2_2016.py -n 100 --no_exec --filein filelist:step1_dasquery.log --lumiToProcess step1_lumiRanges.log --fileout file:step2.root

Where:
step1_dasquery.log has the file list as provided by the das query:
das_client --limit 0 --query 'file dataset=/MuOnia/Run2016E-v2/RAW run=277069'

and:
step1_lumiRanges.log is a file with the expected lumisection window:
{
"277069" : [[81, 120]]
}

The output cfg from the cmsDriver has:

fileNames = cms.untracked.vstring('/store/data/Run2016E/MuOnia/RAW/v2/000/277/069/00000/00605A9C-D74D-E611-80FB-FA163E83034A.root', 
...
'/store/data/Run2016E/MuOnia/RAW/v2/000/277/069/00000/E28FA9AF-034E-E611-8288-FA163E8B5C54.root'),
    lumisToProcess = cms.untracked.VLuminosityBlockRange("277069:81-277069:120"),

When running the cfg, I can see it opens/closes the files in sequence until it reaches file:
/store/data/Run2016E/MuOnia/RAW/v2/000/277/069/00000/66E757A8-034E-E611-BBC5-02163E0140D5.root

where it starts to process events:
Begin processing the 1st record. Run 277069, Event 92655766, LumiSection 110 at 02-Nov-2016 16:02:16.199 CET

**Comment by fabozzi** [comment]
I can see in das that many files are 1.1MB files and have no events

https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fglobal&input=file+dataset%3D%2FMuOnia%2FRun2016E-v2%2FRAW+run%3D277069

**Comment by davidlange6** [comment]
Right, but as you suggest, the lumi filtering should prevent us from getting those files

**Comment by davidlange6** [comment]
ah - but no

step1_lumiRanges.log is just input to cmsDriver - so you still open and close the first N files until you get one in the lumi section range specified in step1_lumiRanges.log (and then sometimes none of files returned from das are in that range because it returns only the first N of them). 

yuck… 

the better implementation in cmsdriver would be to parse the output of
file,lumi dataset=/MuOnia/Run2016E-v2/RAW

to find relevant files in the das query step…

**Pull request closed without merging**
