### PR TITLE
added esConsumes to modules in RecoTracker/DeDx

### PR DESCRIPTION
**Pull request by JamminJones**
#### PR description:

added esConsumes to 1 module

#### PR validation:

the code compiles

### CODE REVIEW

**Comment by JamminJones** [comment]
DeDxEstimatorProducer and DeDxTools modules were not modified due to the complexity of changes required to modify them.

**Comment by Dr15Jones** [comment]
This change was made under my supervision.

**Comment by Dr15Jones** [comment]
please test

**Comment by perrotta** [comment]
+1
- Technical
- Jenkins tests pass

**Comment by silviodonato** [comment]
+1

**Pull request merged**
