### PR TITLE
BixPixEff

### PR DESCRIPTION
**Pull request by fioriNTU**
Fix the BPix efficiency plot, cuts for Phase I upgrade were applied to actual detector

### CODE REVIEW

**Comment by deguio** [comment]
please test
is there a correspondent PR in 76 and 75?
thanks,
F.

**Comment by fioriNTU** [comment]
I will submit them asap

Il 24/09/2015 20.12, Federico De Guio ha scritto:
>
> please test
> is there a correspondent PR in 76 and 75?
> thanks,
> F.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/cms-sw/cmssw/pull/11468#issuecomment-143008271>.
>



---
Questa e-mail è stata controllata per individuare virus con Avast antivirus.
https://www.avast.com/antivirus

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
please test

**Comment by fioriNTU** [comment]
Could someone point me to the problem with this test?
I don't really understand the log, anyway I ran the white rabbit and everything was fine.

**Comment by deguio** [comment]
+1

**Comment by fioriNTU** [comment]
Hi everybody, is there any problem with this PR? We are missing BPix efficiency plots

**Comment by danduggan** [comment]
@davidlange6 could we have this one merged when you have a chance? I think it should be solid from a DQM standpoint. Thanks!

**Comment by davidlange6** [comment]
+1

**Pull request merged**
