### PR TITLE
add datatier for intermediate EDM NANOAOD stuff

### PR DESCRIPTION
**Pull request by arizzi**
This should solve the problem observed in production of nanoaod with intermediate edm step

### CODE REVIEW

**Comment by kpedro88** [comment]
please test

**Comment by fabozzi** [comment]
+1

**Comment by arizzi** [comment]
@fabozzi did the workflow with this change run successfully?

**Comment by fabozzi** [comment]
no, in pending status actually

**Comment by davidlange6** [comment]
Hi @arizzi @fabozzi from your comments- are there pending issues for this pr?

**Comment by fabozzi** [comment]
I think we should integrate with a fix to set up properly the process string of NANOMERGE step, as we learned from the injection test

**Comment by arizzi** [comment]
@fabozzi what do you mean with fix the process string?
The GT cannot be "fixed" because NANOMERGE is common and any GT is fine (in
fact we would not even need one)

**Comment by fabozzi** [comment]
@arizzi 
The ProcessingString is the parameter of the workflow that is used in the output dataset name. The GT of the step is copied in the ProcessingString: we need to avoid this for the NANOMERGE step and copy instead the GT of the NANOEDM step

https://github.com/cms-sw/cmssw/compare/master...fabozzi:from-CMSSW_9_4_0_pre3_nanoedmtest

I can also make a separate PR for this change in MatrixInjector

**Comment by fabozzi** [comment]
OK, I have inserted the change to MatrixInjector in the "Relval updates for 94X" (PR #21091).
This PR can go ahead as it is for me.

**Comment by arizzi** [comment]
thanks, I was trying to add it here but we had twice the same commits and from phone it was impossible

**Comment by davidlange6** [comment]
+1

**Comment by davidlange6** [comment]
merge

**Pull request merged**
