### PR TITLE
EGM-certified electron IDs for 2016 data: cut-based and MVA 

### PR DESCRIPTION
**Pull request by ikrav**
This PR contains EGM certified cut-based and MVA electron IDs tuned on 80X samples. They are intended to be used on 2016 data. The electron MVA contains the HZZ MVA used for ICHEP16 and the presently recommended general purpose MVA tuned for better performance given features of a more complete 2016 dataset.

This code is being submitted to 80X, 81X, and 90X. The 90X and 80X PRs are already merged, the changes that came up during those merges are also introduced into this one.

### CODE REVIEW

**Comment by rafaellopesdesa** [comment]
att @fcouderc

**Comment by slava77** [comment]
@ikrav 
what are the plans for your developments in 81X?
This is sort of a dead release.

**Comment by ikrav** [comment]
Well, I do not have specific plans, this is just for completeness. However, maybe I should
check with EGM conveners whether I am overlooking something.

Ilya

**Comment by rafaellopesdesa** [comment]
@slava77 Hi Slava ....  EGM has no further plans with 81X. For electrons IDs, the PRs were already merged in 80X and 90X. For photons ID, nothing was merged yet. For photon ID, we need it in 80X (for rereco usage) and 91X (current development release). Are you enforcing backporting from 91X to 90X? Should we do the photon ID in 80X, 90X, and 91X... or only 80X and 91X?

**Comment by slava77** [comment]
On 3/2/17 10:07 AM, Rafael Lopes de Sa wrote:
> @slava77 <https://github.com/slava77> Hi Slava .... EGM has no further
> plans with 81X. For electrons IDs, the PRs were already merged in 80X
> and 90X. For photons ID, nothing was merged yet. For photon ID, we need
> it in 80X (for rereco usage) and 91X (current development release). Are
> you enforcing backporting from 91X to 90X? Should we do the photon ID in
> 80X, 90X, and 91X... or only 80X and 91X?

Hi Rafael,

Backports are driven by your needs.
Presence of a PR in the latest development release first is a
requirement by development policy.

Hope this clarifies.

**Comment by rafaellopesdesa** [comment]
It does. OK, thanks.

We will do the other PRs mentioned above soon.

**Comment by slava77** [comment]
-1

based on email discussion, there is no need for 81X EGM PRs.

**Comment by ikrav** [comment]
Closing the pull request as unnecessary.

**Pull request closed without merging**
