### PR TITLE
EgHLT Phase-II showershape fix : 11_3_X

### PR DESCRIPTION
**Pull request by Sam-Harper**
#### PR description:

This PR disables the calculation of ECAL showershape variables for superclusters which are not in the ECAL. It sets the showershapes to zero so that by default they pass, this makes things easier to build a trigger as it avoids having to OR the ECAL and HGCAL showershape filters (which likely eventually will be made into a single  filter but that is not for today). 

No physics changes are expected, the change in behaviour is a crash is prevented for PhaseII

Backports will follow to 11_1 and 11_2

#### PR validation:

PhaseII E/gamma HLT workflows do not crash.

### CODE REVIEW

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by silviodonato** [comment]
please test

**Comment by Martin-Grunewald** [comment]
I think the bot gets confused as there are 3 PRs all off the same branch. @smuzaffar

**Comment by smuzaffar** [comment]
yes, this is now an issue with new bot which uses the git commits to keep track of test statuses. github commits statuses do not belong to PR but them are attached to the git commit. We had senn similar issues with #32356 and #32367 ( see https://github.com/cms-sw/cmssw/pull/32365#issuecomment-743038662 ) . 
I would suggest to create a separate branch for each PR

**Comment by fwyzard** [comment]
>  I would suggest to create a separate branch for each PR

I rather disagree - thar adds extra work for all developments that needs to be backported and could otherwise just be based on a common ancestor.

**Comment by Sam-Harper** [comment]
Yes I much prefer a common ancestor approach as it saves significant time while ensuring exactly the same thing gets backported

**Comment by smuzaffar** [comment]
I am afraid this is how github commit statuses work :-( Is PRs share the commit then they will share the test results too. 
The only thing I can do is to use cms/PR#/arch/testname to distinguish between results

**Comment by smuzaffar** [comment]
@Sam-Harper , I have update bot to use cms/PR#/arch/test to keep track of PR test status. The new statuses will only be used by new commmits/PRs. In order to enable the new statuses for #32469, #32470 and #32471 , can you please push a new commit (e.g. a comment state in code) to `EgHLTPhaseIIFixes_1100pre9` branch? This will allow to bot to reset the old statuses and start using new one for these PRs

**Comment by Sam-Harper** [comment]
no problem will do so no, thank you so much for updating the bot, its very much appreciated that we can keep this functionality as I do think it will save us time in the future.  Much appreciated

**Comment by smuzaffar** [comment]
please test
thanks @Sam-Harper

**Comment by Martin-Grunewald** [comment]
+1

**Pull request merged**
