### PR TITLE
B2G DQM for dilepton paths

### PR DESCRIPTION
**Pull request by rappoccio**
These are the (hopefully) final B2G paths that needed monitoring to be included in the menus. These are dilepton paths monitored primarily by B2G for the X5/3 analysis. They are designed to monitor:

HLT_Mu37_Ele27_CaloIdL_MW_v
HLT_Mu27_Ele37_CaloIdL_MW_v
HLT_Mu37_TkMu27_v

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by mtosi** [comment]
thanks !
can you please quantify the #bins added by this PR ?

**Comment by mtosi** [comment]
tracked by https://github.com/cms-sw/cmssw/issues/19142

**Comment by rappoccio** [comment]
Hi, Mia,

I'm not sure. Perhaps David knows?

Cheers,
Sal

**Comment by davidlange6** [comment]
presumably dqm has the needed tool by now? @dmitrijus ?

**Comment by davidlange6** [comment]
ping @dmitrijus

**Comment by rappoccio** [comment]
Any word on this? I don't want to miss the deadline.

**Comment by dmitrijus** [comment]
I wrote the instructions in a private email to Mia. I have forwarded it to you. 
The tool is not yet clean enough to be merged, but eventually, it will be :)

**Comment by rappoccio** [comment]
Thanks. I will follow up with the dilepton analysts.

**Comment by davidlange6** [comment]
please test
(now we can answer this impossible question in cmsbot)

**Comment by davidlange6** [comment]
merge

**Pull request merged**
