### PR TITLE
deprecate caloparams by local config for all but HI work flows

### PR DESCRIPTION
**Pull request by mulhearn**
Removing caloparams from local config feels like a game of whack-a-mole now.  This should whack those moles for all cases except HI.

### CODE REVIEW

**Comment by mulhearn** [comment]
please test

**Comment by mulhearn** [comment]
please test

**Comment by mulhearn** [comment]
+1

**Comment by danduggan** [comment]
+1
touches online DQM only, and this touches DQM ~trivially

**Comment by davidlange6** [comment]
+1

**Comment by mulhearn** [comment]
Take that moles!

**Pull request merged**
