### PR TITLE
rechitR45 filter is added to HcalnoiseCleaner module and turn of RBXR…

### PR DESCRIPTION
**Pull request by safarzad**
Two files HLTrigger/JetMET/interface/HLTHcalTowerNoiseCleaner.h
 " HLTrigger/JetMET/src/HLTHcalTowerNoiseCleaner.C
" and ""rechitR45 filter is added to HcalnoiseCleaner module and turn of RBXR45 filter.

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
-1

Not this way, as the physics is changed, and we can not allow that for the frozen menus.
Please configure the (default) action as to reproduce the old behaviour of the filter.
(File a JIRA request to move to some new behaviour for the next round of development menus.)

**Comment by safarzad** [comment]
Hi Martin,

The previous filter will be back if we uncomment  line 212 and comment out line 213.

**Comment by Martin-Grunewald** [comment]
Uncomment 212 to bring back the old filter, but do not comment 213 as that would disable the
new test. Instead, configure a module parameter to tell the code such that the new test is not used,
and only used if asked for explicitly. This way the default behavour is unchnaged and one can still,
with a change in py config of the module, switch on the new filter.

**Comment by safarzad** [comment]
I will give a try but RBXR45 filter is not used for 25ns and we already turn off all HBHE filters online due to the inconsistency between offline and online filter.

**Pull request closed without merging**
