### PR TITLE
Run3-TB45 Correct the xml files for October TB simulation

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Update the geometry description of 2018 October test beam setups

#### PR validation:

Tested using cfg files in SImG4CMS/HGCalTestBeam/test directory

#### if this PR is a backport please specify the original PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by fabiocos** [comment]
@cvuosalo @kpedro88 this does not touch standard workflow, and I understand it has been validated with the provided cfg, any comment? Otherwise I would integrate it

**Comment by kpedro88** [comment]
+upgrade

**Comment by cvuosalo** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
