### PR TITLE
 [HGCAL trigger] Update of the general code architecture - 2 

### PR DESCRIPTION
**Pull request by jbsauvan**
Copy of #24544 + removing deprecated cfi + fixing MVA conflict

## Original PR note
This PR includes important changes of the architecture of the HGCAL TPG code

An overview of this new software architecture had been presented here. It provides a more flexible data flow and also reflects better the current electronics architecture design.
This new infrastructure will facilitate the development of frontend and backend algorithms and also give the possibility to easily run in parallel several trigger workflows.

### CODE REVIEW

**Comment by thomreis** [comment]
please test

**Comment by jbsauvan** [comment]
All comments in the original PR have been implemented, all checks pass and there is no conflicts. If there is no more comments, could this PR be approved?

**Comment by kpedro88** [comment]
+upgrade

**Comment by rekovic** [comment]
+1

**Comment by kpedro88** [comment]
@fabiocos this is ready to go

**Comment by fabiocos** [comment]
+operations

changes in StandardSequences are coherent with the purpose of the PR

**Pull request merged**
