### PR TITLE
Move to D76 in HGCal geometry unit test

### PR DESCRIPTION
**Pull request by srimanob**
#### PR description:
As reported in https://github.com/cms-sw/cmssw/issues/33325, we move to D76.

#### PR validation:
-

#### if this PR is a backport please specify the original PR and why you need to backport that PR:
Not a backport, and no need for backporting.

### CODE REVIEW

**Comment by srimanob** [comment]
Please test

**Comment by silviodonato** [comment]
merge
trivial bugfix

**Comment by jfernan2** [comment]
+1

**Comment by cvuosalo** [comment]
+1

**Pull request merged**
