### PR TITLE
Cleanup of outdated paths from HLT Exotica Validation

### PR DESCRIPTION
**Pull request by borzari**
This is a cleanup of outdated paths from the HLT Exotica Validation code. The list of these paths can be found in https://twiki.cern.ch/twiki/bin/view/CMS/IssuesExoticaHLTValidation#HLT_paths_not_up_to_date ; addition of hltExoticaPostSingleMuon inside the hltExoticaPostProcessors Sequence (at the bottom of the file; the efficiency plots for this category were not being produced).

The code was tested using local files and showed no issues (as expected); the single muon category paths efficiency plots are now being created; The command `runTheMatrix.py -l limited -i all --ibeos` was run with success.

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
@borzari despite the cleanup and commenting of HLT paths, no real reduction or modification of plots is produced, is this expected? 
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_11_3_X_2021-03-25-1100+039f41/41896/dqm-histo-comparison-summary.html

**Comment by borzari** [comment]
@jfernan2 yes, it is expected since the paths that were commented are outdated and no longer exist in the current HLT menus.

**Comment by jfernan2** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
