### PR TITLE
Global tags for Run 2 UL reprocessing [11_0_X]

### PR DESCRIPTION
**Pull request by christopheralanwest**
#### PR description:

This is a backport of PR #28524. The backport is desired so as to have the complete set of conditions for the UL available by default for 11_0_X release validation.

#### PR validation:

See PR #28524 for a description of the validation. In addition, a technical test was performed: `runTheMatrix.py -l limited,7.2,7.4,7.21,7.22 --ibeos`

#### if this PR is a backport please specify the original PR:

This is a backport of PR #28524.

### CODE REVIEW

**Comment by christopheralanwest** [comment]
please test workflow 7.2,7.4,7.21,7.22

**Comment by christopheralanwest** [comment]
backport #28524

**Comment by christopheralanwest** [comment]
+1

- Trivial backport of corresponding PR to master, also confirmed by the identical set of changes in PR comparison tests between the two PRs

**Comment by kpedro88** [comment]
+upgrade

**Comment by fabiocos** [comment]
@srimanob this PR will not affect HLT TDR in my understanding, but will make 11_0_0 usable to further UL tests

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

@chaynit it is a faithful backport of what already approved in 11_1_X

**Comment by chayanit** [comment]
+1
sorry for my missing

**Pull request merged**
