### PR TITLE
allow edmCheckClassTransients to accept multiple rootfile files on command-line

### PR DESCRIPTION
**Pull request by smuzaffar**

### CODE REVIEW

**Comment by smuzaffar** [comment]
this script edmCheckClassTransients is not is use ye to no need to run any ib tests

**Comment by smuzaffar** [comment]
+1

**Comment by smuzaffar** [comment]
@gartung , any objection on the purposed change? It saves few seconds for the package with multiple classes.h files

**Comment by smuzaffar** [comment]
I have updated build rules to call this script and it generated this error
```/var/build/muz/del/CMSSW_7_6_X_2015-09-27-2300/src/FWCore/Utilities/scripts/edmCheckClassTransients -l libDataFormatsJetReco.so -x lib/slc6_amd64_gcc493/DataFormatsJetReco_xr.rootmap -x lib/slc6_amd64_gcc493/DataFormatsJetReco_x1r.rootmap -x lib/slc6_amd64_gcc493/DataFormatsJetReco_x2r.rootmap -x lib/slc6_amd64_gcc493/DataFormatsJetReco_x3r.rootmap
Checking class edm::AssociationVector<edm::RefToBaseProd<reco::Jet>,vector<edm::RefVector<vector<reco::Track>,reco::Track,edm::refhelper::FindUsingAdvance<vector<reco::Track>,reco::Track> > >,edm::RefToBase<reco::Jet>,unsigned int,edm::helper::AssociationIdenticalKeyReference>
Checking class edm::AssociationVector<edm::RefToBaseProd<reco::Jet>,vector<float>,edm::RefToBase<reco::Jet>,unsigned int,edm::helper::AssociationIdenticalKeyReference>
Checking class edm::AssociationVector<edm::RefToBaseProd<reco::Jet>,vector<reco::JetExtendedAssociation::JetExtendedData>,edm::RefToBase<reco::Jet>,unsigned int,edm::helper::AssociationIdenticalKeyReference>
Traceback (most recent call last):
  File "/var/build/muz/del/CMSSW_7_6_X_2015-09-27-2300/src/FWCore/Utilities/scripts/edmCheckClassTransients", line 72, in <module>
    checkTrans(key,value)
  File "/var/build/muz/del/CMSSW_7_6_X_2015-09-27-2300/src/FWCore/Utilities/scripts/edmCheckClassTransients", line 39, in checkTrans
    raise RuntimeError("failed to load dictionary for class '"+name+"'. Check for typedefs in the name.")
RuntimeError: failed to load dictionary for class 'class edm::AssociationMap<edm::OneToMany<reco::CaloJetCollection,std::vector<reco::Track>,unsigned int> >'. Check for typedefs in the name.```

**Comment by Dr15Jones** [comment]
```CaloJetCollection``` is a typedef. I guess I don't understand how rootmap files work then. Patrick, best to talk with Philippe about how to do this.

**Comment by gartung** [comment]
This string shouldn't have appeared in the rootmap file

class edm::AssociationMap<edm::OneToMany<reco::CaloJetCollection,std::vector<reco::Track>,unsigned int> >

The rootmap file is supposed to contain the name as the compiler sees it. 
@smuzaffar Can you check to see if this string appears in the rootmap file.

**Comment by gartung** [comment]
@smuzaffar Nevermind. I see that the string is there. I don't understand why:

grep edm::AssociationMap DataFormatsJetReco*.rootmap
DataFormatsJetReco_x2r.rootmap:class edm::AssociationMap<edm::OneToMany<reco::CaloJetCollection,std::vector<reco::Track>,unsigned int> >
DataFormatsJetReco_x2r.rootmap:class edm::AssociationMap<edm::OneToMany<reco::JPTJetCollection,std::vector<reco::Track>,unsigned int> >

**Comment by gartung** [comment]
The class name appears twice -- once with the typedef-ed name and once with the real names.

# List of selected classes
class edm::AssociationMap<edm::OneToMany<reco::CaloJetCollection,std::vector<reco::Track>,unsigned int> >
class edm::AssociationMap<edm::OneToMany<reco::JPTJetCollection,std::vector<reco::Track>,unsigned int> >
class edm::AssociationMap<edm::OneToMany<vector<reco::CaloJet>,vector<reco::Track>,unsigned int> >
class edm::AssociationMap<edm::OneToMany<vector<reco::JPTJet>,vector<reco::Track>,unsigned int> >

**Comment by gartung** [comment]
@smuzaffar  Please merge this. I will need to change the script to make the error non-fatal. Since the real class name is in the rootmap file it will be loaded and then the transient member can be check.

**Comment by Dr15Jones** [comment]
@gartung You should be able to get the branch from Shahzad's repository, make the change and then do a pull to Shahzad's repo. Then he can integrate it and this pull request will get the change.

**Comment by smuzaffar** [comment]
+1

**Comment by smuzaffar** [comment]
merging this as this script is not used by any thing yet

**Pull request merged**
