### PR TITLE
Run2-hcx146 Correct collection names used in IsoTrack HLTs (Backport PR #19776)

### PR DESCRIPTION
**Pull request by bsunanda**
Pixel IsoTrack Producer is using 2 collections which have been renamed and need correction for 9_2 version for HLT application

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@lpernie Can you accept this PR - it is used in HLT for IsoTrack

**Comment by lpernie** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
