### PR TITLE
Run3-gex98F Use ESGetToken in some of the test scripts of SimCalorimetry

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Use ESGetToken in some of the test scripts of SimCalorimetry (EcalSimProducers and HGCalSimAlgos)

#### PR validation:

Use runTheMatrix test workflows 

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by srimanob** [comment]
+Upgrade

Technical migration of esConsumes, no changes are expected.

**Comment by civanch** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
