### PR TITLE
Run3-gex133A Try to avoid compilation issues in 2 test codes of GeneratorInterface

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Try to avoid compilation issues in 2 test codes of GeneratorInterface

#### PR validation:

Use the runTheMatrix test workflows

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by SiewYan** [comment]
please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by SiewYan** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
