### PR TITLE
Phase2-hgx189 Add specifics for HGCal V10 geometry

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Introduce HGCal V10 geometry specific Era which will introduce things specific to C8 calorimeter design

#### PR validation:

Not yet tested - with this the V10 specific layer weights will be added and then tested with changed D41 scenario

#### if this PR is a backport please specify the original PR:

It is a new set of Era's and not a back porting

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by fabiocos** [comment]
+operations

the update to Eras is coherent with the purpose of the PR, and parallel to what already done.
A possible reorganization of phase2 eras go beyond the scope of this PR (@kpedro88 FYI)

**Comment by kpedro88** [comment]
assign upgrade

**Comment by kpedro88** [comment]
@bsunanda I think it would be better to change the eras used by D41 in this PR

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by kpedro88** [comment]
+upgrade

**Comment by fabiocos** [comment]
+operations

**Comment by cvuosalo** [comment]
+1

**Comment by fabiocos** [comment]
@prebello @zhenhu objections? Or can we move forward?

**Comment by prebello** [comment]
+1

no objections

**Comment by fabiocos** [comment]
+1

**Pull request merged**
