### PR TITLE
[14_1_X] Backport of #45820: Change ScoutingNano event content

### PR DESCRIPTION
**Pull request by patinkaew**
#### PR description:

Backport of https://github.com/cms-sw/cmssw/pull/45820 from 14_2_X to allow tests for ScoutingNano central production at T0 with 14_1_X release. This backport is also intended to keep release consistent because backport of https://github.com/cms-sw/cmssw/pull/44970/, https://github.com/cms-sw/cmssw/pull/45820 to 14_0_X will follow for actual data-taking release, so we eventually have https://github.com/cms-sw/cmssw/pull/44970/, https://github.com/cms-sw/cmssw/pull/45820 in subsequent releases from 14_0_X.

Note: https://github.com/cms-sw/cmssw/pull/44970/ was originally merged to 14_1_X, so we don't need backport for that PR for 14_1_X.

The original PR changes ScoutingNano event content by dropping PF candidates, dropping tracks, adding PFJet clustered at HLT, removing tasks related to TrigObj table, and additional minor changes. The final event size is <2 kB/event for default ScoutingNano configuration, containing only scouting objects without offline objects and without gen info (MC).

#### PR validation:

Standard tests ```scram b runtests``` and ```runTheMatrix.py -l limited -i all --ibeos``` passed when validating https://github.com/cms-sw/cmssw/pull/45820.  ScoutingNano event size report comparison was done in [1]. Original PR tests confirm that these size reports and also observe event size reduced by ~85%.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

This is a backport of https://github.com/cms-sw/cmssw/pull/45820 to CMSSW 14_1_X release.

[1] https://indico.cern.ch/event/1441452/#preview:5119073

### CODE REVIEW

**Comment by patinkaew** [comment]
Tagging HLT Scouting convenors: @silviodonato @elfontan.

**Comment by hqucms** [comment]
enable nano

**Comment by hqucms** [comment]
please test

**Comment by hqucms** [comment]
+1

**Comment by hqucms** [comment]
backport of https://github.com/cms-sw/cmssw/pull/45820

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
