### PR TITLE
Run3-gex109C Avoid compilation warnings in some of the Validation classes

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Avoid compilation warnings in some of the Validation classes (CSCDigis, GEMDigis, Identification, Isolation, ME0Validation, RPCGeometry)

#### PR validation:

Use the runTheMatrix test workflows

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by jfernan2** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
