### PR TITLE
adding phi meson

### PR DESCRIPTION
**Pull request by alberto-sanchez**
for "quarkonium" studies

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
@gpetruc: Is the addition to Mini-AOD made by this PR acceptable?

**Comment by cvuosalo** [comment]
+1

For #14116 80c22d963a280dcfb20abb2912ce7580d4f8563f

Adding phi mesons to the pruned GenParticles in Mini-AOD. There should be no change in monitored quantities.

This approval is contingent upon the approval from the Mini-AOD experts.

The code change is satisfactory, and Jenkins tests against baseline CMSSW_8_1_X_2016-04-18-1100 show no significant differences, except for differences unrelated to this PR from the additional commit Jenkins included. An extended test of workflow 25202.0_TTbar_13 also shows no significant differences. Mini-AOD event content increases in size very slightly by 0.04% with the additional phi mesons:
```
-----------------------------------------------------------------
   or, B         new, B      delta, B   delta, %   deltaJ, %    branch 
-----------------------------------------------------------------
   2245.3 ->      2281.8         36      1.6   0.04     recoGenParticles_prunedGenParticles__RECO.
   5165.1 ->      5166.0          1      0.0   0.00     patElectrons_slimmedElectrons__RECO.
   4186.9 ->      4190.3          3      0.1   0.00     patPackedGenParticles_packedGenParticles__RECO.
-------------------------------------------------------------
    85167 ->       85208         41             0.0     ALL BRANCHES
```
The changes for patElectrons and packedGenParticles are probably just unrelated fluctuations.

**Comment by cvuosalo** [comment]
hold
Wait for @gpetruc to approve of Mini-AOD addition.

**Comment by gpetruc** [comment]
The addition is fine for me,

Giovanni
Il 20-apr-2016 10:39 PM, "cmsbuild" <notifications@github.com> ha scritto:

**Comment by cvuosalo** [comment]
unhold

**Pull request merged**
