### PR TITLE
Run3-gex33 Also add cfg's for step4 and step5 to test dd4hep for Zmumu

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Also add cfg's for step4 and step5 to test dd4hep for Zmumu

#### PR validation:

test by running the workflows

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@slomeo Here are the cfg's for step4 and step5 - they run without issues

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by fabiocos** [comment]
@bsunanda out of curiosity, what is this PR adding on top of #30003 and #31975 ?

**Comment by civanch** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Comment by slomeo** [comment]
@bsunanda thank you very much!

**Pull request merged**
