### PR TITLE
Fix the histogram: RPC_HV_Status

### PR DESCRIPTION
**Pull request by slezki**
Fixed the LS limitation for the histogram: RPC_HV_Status,
@jhgoh @mileva @andresib

### CODE REVIEW

**Comment by jhgoh** [comment]
The "RPC_HV_Status" in the RPC DQM is to show the number of LS with RPC, but it is limited not to exceed 900. This can cause confusion to shifters because of mismatch between the actual nLS of good RPC status and what is shown in the DQM.

We asked the reason of this limitation to the previous developer. It is to limit memory usage when the development was made. Size of memory can be increased for very long runs which can be nLS~2000 and the member variable "DCS" can be increased (type is std::vector<int>). The memory usage for this vector<int> should not be a major factor of the cmssw.

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Comment by jhgoh** [comment]
Thanks @davidlange6

**Pull request merged**
