### PR TITLE
Major updates to L3 Muon OI SeedGenerator for high efficiency ( Backport  PR for  #24267 )

### PR DESCRIPTION
**Pull request by bmahakud**
Backport for  PR #24267
Major updates to HLT OI reconstruction. No changes made to customizeHLTforCMSSW.py. Only .cc file changes

### CODE REVIEW

**Comment by bmahakud** [comment]
@Martin-Grunewald Backport PR

**Comment by perrotta** [comment]
@bmahakud : please update the title to match the one of the backported pull request (so that one can understand from it what this PR deals with)

**Comment by perrotta** [comment]
@cmsbuild please test

**Comment by perrotta** [comment]
backport of #24267

**Comment by Martin-Grunewald** [comment]
Needs fix #24342 to be included here as well!

**Comment by Martin-Grunewald** [comment]
Fix not needed here as we only add the new plugin.

**Comment by Martin-Grunewald** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Pull request merged**
