### PR TITLE
Hcallogicalmap

### PR DESCRIPTION
**Pull request by weihuacern**
Hcal Logical map update, including 
CondFormats/HcalObjects/interface/HcalLogicalMap.h
CondFormats/HcalObjects/src/HcalLogicalMap.cc
CondFormats/HcalObjects/interface/HcalMappingEntry.h
CondFormats/HcalObjects/src/HcalMappingEntry.cc
CalibCalorimetry/HcalAlgos/src/HcalLogicalMapGenerator.cc
CalibCalorimetry/HcalAlgos/interface/HcalLogicalMapGenerator.h
CalibCalorimetry/HcalAlgos/test/MapTester.cc
CalibCalorimetry/HcalAlgos/test/maptester_cfg.py

And also
CalibCalorimetry/HcalAlgos/data/
DB_HBHEHOHF_Calib.txt  
HOremap_Feb2015_crate13.txt  
HOremap_Feb2015_crate6.txt  
QIE_FNAL_normal.txt  
DB_HBHEHOHF_Normal.txt  
HOremap_Feb2015_crate3.txt  
HOremap_Feb2015_crate7.txt  
RBX_RM_QIE.txt

### CODE REVIEW

**Comment by diguida** [comment]
-1
Please add the `txt` files in `CalibCalorimetry/HcalAlgos/data/` folder into the cms-data repo.
@nclopezo can you please check if the folder is already existing?

**Comment by davidlange6** [comment]
@diguida - what is the expected usage of these data files?

**Comment by weihua19900704** [comment]
Hi All: 
Sorry for late reply
I add a new directory CalibCalorimetry/HcalAlgos/data/ in my PR and it should be included in the PR branch. Do I need to send the PR again?
Thanks!
Hua

**Comment by abdoulline** [comment]
Hua, your branch is not changed.  Otherwise GIT would immediately spot it and issue the message here...
Did you "push" the most recent changes (directory) to your "hcallogicalmap" branch on GIT?

**Comment by weihua19900704** [comment]
Ok, will do it soon
________________________________

**Comment by abdoulline** [comment]
... sorry, I might have been too quick...
Apparently you meant the directory was there from the beginning (of PR 
submission) ?

**Comment by davidlange6** [comment]
Hi @abdoulline , @weihua19900704 - maybe you can also answer my question above - what is the expected usage of these two big files? (CMSSW Is not a repo for conditions objects in general).

**Comment by weihua19900704** [comment]
I just try to get QIE card calibration information from these two files(~ 50MB for each). This function was called in the HcalLogicalMapGenerator.cc.
________________________________

**Comment by ggovi** [comment]
-1

**Comment by abdoulline** [comment]
I suggest this PR to be closed. 
A new one with appropriate modifications (and reduced service files) to be (re-) open in 76X.

**Pull request closed without merging**
