### PR TITLE
Phase2-hcx256 Update D58 scenario for hfnose

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Update the D58 scenario with modification of the base-plate material and a small change in the handling of mask operation

#### PR validation:

Tested using runTheMatrix.py

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by kpedro88** [comment]
test parameters
workflows = 27434.0

**Comment by kpedro88** [comment]
please test

**Comment by cvuosalo** [comment]
+1

**Comment by bsunanda** [comment]
@kpedro88 Could you sign this please?

**Comment by kpedro88** [comment]
+upgrade

**Comment by silviodonato** [comment]
+1

**Pull request merged**
