### PR TITLE
Removing forking ability from cmsRun

### PR DESCRIPTION
**Pull request by Dr15Jones**
The ability to fork the process is no longer a feature being used
and the code to make it possible is interfering with the code changes
needed to allow concurrent Run and LuminosityBlock transitions.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
please test

**Comment by perrotta** [comment]
+1
Reco affected through EventFilter/Utilities/FedRawDataInputSource
Technical: removed methods that allow forking the process
No effect on jenkins outputs

**Comment by davidlange6** [comment]
merge

**Pull request merged**
