### PR TITLE
Speedup MET significance calculation

### PR DESCRIPTION
**Pull request by kpedro88**
Using `unordered_set` instead of `set` is about 40% faster on the sample I tested (Fall17 GJets).

@Dr15Jones if you would prefer to define a hash for `edm::Ptr` more globally, let me know.

I intend to backport this to 94X and 102X for analysis use.

### CODE REVIEW

**Comment by kpedro88** [comment]
please test

**Comment by slava77** [comment]
> Using unordered_set instead of set is about 40% faster on the sample I tested (Fall17 GJets).

what are the absolute values for the time saved [and/or, compare this to the full miniAOD processing]?

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/24135	da85f01
- technical updates for speedup
- jenkins tests pass and comparisons show no differences

**Comment by fabiocos** [comment]
+1

**Pull request merged**
