### PR TITLE
Made FebConnectorSpec const thread-safe

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

As this is used in an EventSetup data product, it must be const thread-safe.

This was found by the static analyzer.

#### PR validation:

Code compiles.

### CODE REVIEW

**Comment by tvami** [comment]
type performance-improvement,rpc

**Comment by tvami** [comment]
test parameters:
  - enable_tests = threading

**Comment by tvami** [comment]
@cmsbuild , please test
 * let's do a test with threading too

**Comment by Dr15Jones** [comment]
please test

**Comment by perrotta** [comment]
+1

**Pull request merged**
