### PR TITLE
Internal das client python module to call das_client wrapper

### PR DESCRIPTION
**Pull request by smuzaffar**

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by cvuosalo** [comment]
+1

For #15549 5e1f8f2aa5a0a8d529d21f092fa2b986f5e6f247

Putting das_client call into Python script wrapper. There should be no change in monitored quantities.

The code changes are satisfactory, and Jenkins tests against baseline CMSSW_8_1_X_2016-08-22-1100 show no significant differences, as expected.

**Comment by smuzaffar** [comment]
+1

**Comment by ghellwig** [comment]
@smuzaffar can you tell me, if this will be backported to other release cycles (and which ones)?
If would be great to have this at least in 80X.

attn.: @vbotta

**Comment by davidlange6** [comment]
+1

**Comment by smuzaffar** [comment]
@ghellwig , we can backport it to all active release cycles (53X and above).

**Comment by ghellwig** [comment]
@smuzaffar great! This makes the needed changes really minimal.

**Pull request merged**
