### PR TITLE
Remove old duplicate vfatstatusdigi

### PR DESCRIPTION
**Pull request by watson-ij**
#### PR description:

Remove VFatStatusDigi from DataFormats/GEMDigi (this is an old duplicate of the current EventFilter/GEMRawToDigi and shouldn't have been used anyway for quite some time).

@jshlee 

#### PR validation:

Check it compiled and ran a test 2021 10mu workflow.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by kpedro88** [comment]
please test

**Comment by kpedro88** [comment]
+upgrade

**Comment by civanch** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
