### PR TITLE
fixed default HF file name

### PR DESCRIPTION
**Pull request by civanch**
Fixed default name of HF shower library

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Comment by franzoni** [comment]
@bendavid @srimanob

hello @civanch,
what is the effect of these changes on the standard SIM sequence of 5_3 x ?

We need to deploy this release in production to acquire some GEN new features.
Can we be sure we're not affecting the physics performance of SIM?

Cheers,
Giovanni

**Comment by davidlange6** [comment]
Hi @franzoni

There is no effect. the HF shower library is not used in 53x.

**Comment by franzoni** [comment]
Thanks, David @davidlange6

**Comment by civanch** [comment]
Hi Giovanni,

New HF SL included in 5_3_X is not used by default, it may be enabled via 
customisation. So, by default nothing should be changed in SIM.

Cheers,
Vladimir

**Comment by franzoni** [comment]
Thanks, Vladimir. g.

**Pull request merged**
