### PR TITLE
Backport to 94X: add fast sim2017 PU and pmx wfs

### PR DESCRIPTION
**Pull request by zhenhu**
backport of #24829 

This is an updated cleaner version of PR #24834 , which has been closed. 
Most of the code in this PR are identical as the original PR #24829 , although I have to change some part to make it compatible with 94X.
The recycling strings have also been updated to 9_4_11_cand1, so that there will be no dataset failures in this IB.

### CODE REVIEW

**Comment by zhenhu** [comment]
+code-checks

**Comment by zhenhu** [comment]
please test

**Comment by zhenhu** [comment]
please test workflow 25400.17, 250399.17, 250400.17, 250402.171

**Comment by zhenhu** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
@kpedro88 the backport looks ok, please check and sign it in case
We should add this for CMSSW_9_4_11_cand2 build

**Comment by kpedro88** [comment]
+upgrade

**Pull request merged**
