### PR TITLE
Asynchronous Prefetch

### PR DESCRIPTION
**Pull request by Dr15Jones**
This is 'phase 1.5' of the threaded framework redesign. This change allows all prefetching of data to be done asynchronously within an event. This allows unscheduled modules to run in parallel. The code still processes scheduled modules and paths in sequentially.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
@davidlange6 as agreed upon, this will first go into _DEVEL

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by Dr15Jones** [comment]
@smuzaffar looks like the test system can't figure out how to map the branch name to the release.

**Comment by davidlange6** [comment]
I think we don’t have tests set up for alternative branches. I’ll just push it in.

On Aug 4, 2016, at 8:06 PM, Chris Jones <notifications@github.com<mailto:notifications@github.com>> wrote:


@smuzaffar<https://github.com/smuzaffar> looks like the test system can't figure out how to map the branch name to the release.

**Comment by Dr15Jones** [comment]
hold
@davidlange6 I think I may have found a bug. Please hold off from merging just yet.

**Comment by Dr15Jones** [comment]
The build failures are not from this pull request.

**Comment by Dr15Jones** [comment]
I was running workflow 250202.0 and step 3.

**Comment by Dr15Jones** [comment]
I checked the unit test failures. They are either from problems in the IB or from an inability of that node to reach the oracle server.

**Comment by Dr15Jones** [comment]
The RelVal failures 1306.0, 10021.0, 1330.0, 136.731, 10024.0 and 25202.0 step3 crashed during initialization, well before the code I changed. I'm guessing it was an incomplete build so the job tried to load something that was binarily incompatible?

The other one was a DAS error.

**Comment by Dr15Jones** [comment]
unhold
@davidlange6 I've found and fixed the bug I discovered. Please restart the tests.

**Comment by davidlange6** [comment]
please test
(not sure how the tests ran in the end - but lets see if this works)

On Aug 5, 2016, at 5:23 PM, Chris Jones <notifications@github.com<mailto:notifications@github.com>> wrote:


unhold
@davidlange6<https://github.com/davidlange6> I've found and fixed the bug I discovered. Please restart the tests.

**Comment by Dr15Jones** [comment]
@davidlange6 While doing performance testing I discovered that ROOT was failing under the cases where there were more threads than streams. The problem was one must run a special function on each thread before calling any ROOT routines. I've now got a working solution and the performance tests now run properly.

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
@davidlange6 @smuzaffar The one Jenkins task that refers to this pull request seems to say it is done but hasn't actually completed. It looks like having the git branch name be different than the IB name is seriously confusing our Jenkins scripts.

**Comment by Dr15Jones** [comment]
+1

**Comment by smuzaffar** [comment]
@Dr15Jones , for now I have started the jenkins jobs by hand and will look in tot he job configuration next week to fix it (jenkins should be able to correctly find the base release e.g. CMSSW_8_1_DEVEL_X_...  for this)

**Comment by Dr15Jones** [comment]
The unit test failures are not caused by this pull request.
- runtestRecoEgammaElectronIdentification failed becuase it could not find its data file via xrootd
- all the others ones fail becuase the tests could not make a direct connection to the oracle database

**Comment by Dr15Jones** [comment]
@davidlange6 as far as I can tell, this is good to go.

**Comment by smuzaffar** [comment]
please test

testing cms-bot changes to correctly find the release for devel IBs

**Pull request merged**
