### PR TITLE
clang check misc-string-compare

### PR DESCRIPTION
**Pull request by davidlange6**
for comment about what clang-tidy does to CMSSW (and likely big and not mergeable - this is what clang-tidy check misc-string-compare does on the tip of CMSSW_9_3_X as of a few days ago

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by slava77** [comment]
+1
similar to #19553
good that this time it compiles

**Comment by ianna** [comment]
+1

**Comment by dmitrijus** [comment]
+1
Makes the code look more tidy!

**Comment by davidlange6** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
hi all
contrary to the initial comment - this could be merged as its relatively limited in scope. Please review. Thanks

**Comment by Dr15Jones** [comment]
+1

**Comment by davidlange6** [comment]
merge

**Pull request merged**
