### PR TITLE
BTag DQM with shallowTagInfos

### PR DESCRIPTION
**Pull request by HeinerTholen**
Using shallowTagInfos, as these are provided with DeepCSV btagging at HLT. This follow the pull request #22686

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by HeinerTholen** [comment]
Dear all, sorry for pushing and thereby resetting the signatures, but the config needs to be updated as well (DQMOffline/Trigger/python/BTVHLTOfflineSource_cfi.py).

**Comment by HeinerTholen** [comment]
Dear all, more additions are necessary. Please wait for me to add another set of commits.

**Comment by jfernan2** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by fabiocos** [comment]
@HeinerTholen @dmitrijus @jfernan2 I am a bit surprised that basically no difference is reported by the dqm comparison, neither in histogram content nor in occupancy. As far as I can see, the input paths have changed, and also the histograms do not seem all identically the same, am I correct?

**Comment by HeinerTholen** [comment]
Hi @fabiocos , indeed most new histograms had been added in #22686 . Here, we adapt the code to fully operate with DeepCSV. Also, we tried to keep the number of added histograms small.

**Comment by HeinerTholen** [comment]
Hi @fabiocos , indeed I added histograms in the latest set of commits, so there should be some change. However, I don't under what you compare the numbers to. The number you quoted changed with respect to the one from 12 days ago (2502041). 

Could you maybe explain in more detail via skype? I will send you a mail with my contact.

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
+1

the net addition looks 50 kB

**Pull request merged**
