### PR TITLE
Phase 2 GTT MET cosLUT overflow fix

### PR DESCRIPTION
**Pull request by NJManganelli**
#### PR description:

This PR addresses a very rare bug, in which a lookuptable (vector) is addressed with out-of-bounds values. The solution is to extend the lookup table by 1 (it's generated in a loop based on the size of the updated constant). Firmware HLS does not currently match this, but HLS behavior with out-of-bounds access is not the same as C++

Parasitically, a review comment is addressed, cleaning up the code somewhat (unnecessary explicit setting of values to 0, which were already initialized as such). See https://github.com/cms-sw/cmssw/pull/42347

#### PR validation:

This PR passes 
scram b
scram b code-checks
scram b code-format

Additionally it's used to generate test vectors for L1T workflows, and all outputs are identical in cases not affected by the bug, and results are as expected in the region that is.

This will need to be backported to cms-l1t-offline Phase 2 integration branch

### CODE REVIEW

**Comment by aloeliger** [comment]
please test

**Comment by NJManganelli** [comment]
Folks may be on holiday, but if there are any extant concerns before sign-off, please let me know.

**Comment by aloeliger** [comment]
@NJManganelli Sorry, I'm on holiday. Would you object if I read and signed off tomorrow? Currently on west coast US time.

**Comment by aloeliger** [comment]
Ehh, check that this is pretty simple.

**Comment by aloeliger** [comment]
+l1

**Comment by NJManganelli** [comment]
> Ehh, check that this is pretty simple.

Thanks Andrew, enjoy your holiday, cheers!

**Comment by NJManganelli** [comment]
Are any upgrade folks back from vacation to review/comment?

Cheers,
Nick

**Comment by aloeliger** [comment]
@cms-sw/upgrade-l2 Any review for @NJManganelli on this? The PR changes are relatively small.

**Comment by srimanob** [comment]
type bug-fix

**Comment by srimanob** [comment]
@cmsbuild please test

Retrigger the test after 2 weeks. When success, I will sign. Sorry for very delay.

**Comment by srimanob** [comment]
+Upgrade

**Pull request merged**
