### PR TITLE
Fix `cudaMemcpyAsync` for `localCoordToHostAsync`

### PR DESCRIPTION
**Pull request by AdrianoDee**
#### PR description:

In `TrackingRecHitSoADevice::localCoordToHostAsync` used in `SiPixelRecHitFromCUDA` to fill the legacy hits, `cudaMemcpyAsync` is not taking into account the SoA layout buffer padding. So it's copying some wrong portions of memory. This was noted in https://github.com/cms-sw/cmssw/issues/40604 and this solves it.

This fix is quick and dirty, given also this CUDA to legacy copy will be dropped soon.

#### PR validation:

Run `11634.59x`.

### CODE REVIEW

**Comment by AdrianoDee** [comment]
type bugfix

**Comment by AdrianoDee** [comment]
test parameters:

- workflows = 11634.596, 11634.592
- enable = gpu
- relvals_opt_gpu = --what cleanedupgrade,standard,highstats,pileup,generator,extendedgen,production,ged,machine,premix,nano

**Comment by AdrianoDee** [comment]
please test

**Comment by AdrianoDee** [comment]
test parameters:

- workflows_gpu = 11634.596, 11634.592
- enable = gpu
- relvals_opt_gpu = --what cleanedupgrade,standard,highstats,pileup,generator,extendedgen,production,ged,machine,premix,nano

**Comment by AdrianoDee** [comment]
please test
(a `*_gpu` was missing)

**Comment by srimanob** [comment]
test parameters:

**Comment by srimanob** [comment]
test parameters:
- workflows_gpu = 11634.596,11634.592
- enable = gpu
- relvals_opt_gpu = --what cleanedupgrade,standard,highstats,pileup,generator,extendedgen,production,ged,machine,premix,nano

**Comment by srimanob** [comment]
> test parameters:
> 
> * workflows_gpu = 11634.596, 11634.592
I think the failure comes from the space after `,`

**Comment by srimanob** [comment]
@cmsbuild please test

**Comment by missirol** [comment]
test parameters:
  - enable = gpu
  - workflows_gpu = 10824.592,10824.593,10824.596,10824.597,11634.593,11634.596
  - relvals_opt_gpu = --what upgrade,standard,highstats,pileup,generator,extendedgen,production,ged,machine,premix,nano

**Comment by missirol** [comment]
please test

**Comment by AdrianoDee** [comment]
test parameters:

- enable = gpu
- workflows_gpu = 10824.592,10824.593,10824.596,10824.597,11634.592,11634.593,11634.596,11634.597
- relvals_opt_gpu = --what upgrade,standard,highstats,pileup,generator,extendedgen,production,ged,machine,premix,nano

**Comment by AdrianoDee** [comment]
please test

**Comment by perrotta** [comment]
urgent
- the [backport](https://github.com/cms-sw/cmssw/pull/40870) is wanted in 13_0_0
- @cms-sw/heterogeneous-l2 @cms-sw/reconstruction-l2 please have a look

**Comment by fwyzard** [comment]
+heterogeneous

**Comment by clacaputo** [comment]
please test

**Comment by perrotta** [comment]
@clacaputo please don't restart the tests uselessly, if you did so because of the relval-input errors, see https://github.com/cms-sw/cmssw/issues/40889. If that was the reason, just review the PR as it is.

**Comment by clacaputo** [comment]
+reconstructio

**Comment by missirol** [comment]
please abort

Based on https://github.com/cms-sw/cmssw/pull/40869#issuecomment-1447973109.

(Signing a PR with the label 'tests-pending' starts the tests automatically.)

**Comment by perrotta** [comment]
merge

**Pull request merged**
