### PR TITLE
Updated WaitingTaskList to handle exception

### PR DESCRIPTION
**Pull request by Dr15Jones**
If the task waited upon throws an exception, that exception is communicated to the waiting tasks. This requires a new base class for tasks, WaitingTask.
The unit test was update to reflect the new API and to test the exception case.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by davidlange6** [comment]
@Dr15Jones - I think this error is for you to address

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
