### PR TITLE
Updated to new RNTuple version

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

- std container used by IsoDeposit can now be split by RNTuple
- xml attribute name was changed to rntupleStreamerMode

#### PR validation:

Code compiles.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
NOTE: This change affects nothing we presently do. It is only needed once we want to read/write the ROOT RNTuple format.

**Comment by Dr15Jones** [comment]
As a test, I used a private branch I have with an RNTuple based Source and OutputModule with this change and was able to read/write AOD and miniAOD files.

**Comment by makortel** [comment]
type -changes-dataformats

The changes here do not impact present production system.

**Comment by jfernan2** [comment]
+1

**Comment by antoniovagnerini** [comment]
+1
- spurious differences from HGCal DQM test (open issue  #46416)

**Comment by hqucms** [comment]
+1

**Comment by Dr15Jones** [comment]
ping @cms-sw/core-l2 @cms-sw/generators-l2

**Comment by makortel** [comment]
+core

**Comment by makortel** [comment]
ping @cms-sw/generators-l2

**Comment by makortel** [comment]
ping @cms-sw/generators-l2

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
