### PR TITLE
Backport of puppi changes from 80X to 76X

### PR DESCRIPTION
**Pull request by violatingcp**
These are changes to the puppi code in 80X. This includes : 
1. Addition of PuppiPhoton (with all fixes from 80X)
2. Addition of Puppi Jet corrector flags
3. Code to build puppi MET collections for MiniAOD Puppi MET

This does not include : 
1. 80X tune of puppi (with loosened forward particle cuts)
2. Updaed MiniAOD MET reconstruction code for Puppi

The 2 updates below will come with a bigger pull request that also includes the addition of the MET Uncertainties code.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test
IIUC, this changes miniAOD
I'm not aware of a solid plan so far to allow updates that change miniAOD in 76X.

**Comment by mariadalfonso** [comment]
@slava77 .
These files here are only partial backport of the 80X. These alone would not change the miniAOD since are not inserted in any sequence (miniOAD production, miniAOD-->miniAOD). But better to have in the release than flying around.

For now the 76X backport (met side) include all these in a separate PR
https://github.com/cms-sw/cmssw/compare/CMSSW_7_6_X...cms-met:metTool76X
that I'm trying to slim.

**Comment by slava77** [comment]
@cmsbuild please test
something happened to the original comparisons (none show up in https://github.com/cms-sw/cmssw/pull/13975#issuecomment-207023419)

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/13975	5106c33
- changes are in line with the description: backported only parts of what is in 80X -- mostly added with #13115 -- that do not modify miniAOD)
- jenkins tests pass and comparisons with baseline show no differences

**Pull request merged**
