### PR TITLE
Run3-alca248Z Modify the calibration code of HCAL to ignore the zside index and also change the name of some variables

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Modify the calibration code of HCAL to ignore the zside index and also change the name of some variables

#### PR validation:

Use the modified macros to obtain new sets of correction factors

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@perrotta Taken care of it. Thanks for pointing this

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by perrotta** [comment]
+alca

**Pull request merged**
