### PR TITLE
Add L1 hitless seeding for tracking @ HLT (11_1_X)

### PR DESCRIPTION
**Pull request by cmantill**
#### PR description:

Adding hitless seeds from L1 tracks to be used in the Phase2 HLT tracking sequence.

#### PR validation:

runTheMatrix.py -l limited -i all --ibeos

Should not affect any current workflows.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Backport of [30342](https://github.com/cms-sw/cmssw/pull/30342). 

Needed for HLT MC samples production.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
backport of #30342

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/30574	0130cff
- the backport is correct; the only difference in the PR diffs compared to the master version is in SeedGeneratorFromL1TTracksEDProducer.cc due to the change of name of ```TrajectorySeed::RecHitContainer ``` typedef (introduced recently in the 11_2_X). This code is to be used for HLT developments; it is currently not a part of the standard workflows.
- jenkins tests pass and comparisons show no relevant differences

**Comment by silviodonato** [comment]
+1

**Pull request merged**
