### PR TITLE
Migration of HLT menus to 11_1_0_pre1 Template (11_1_X)

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
#### PR description:

Migration of HLT menus to 11_1_0_pre1 Template (11_1_X)
Plus integration of CMSHLT-2100
Based on CMSSW_11_1_0_pre1

#### PR validation:

TSG tests

#### if this PR is a backport please specify the original PR:

N/A

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by fabiocos** [comment]
@Martin-Grunewald I understand that the changes for the 2021 and 2023 scenarios are expected, am I correct?

**Comment by fabiocos** [comment]
+1

**Comment by Martin-Grunewald** [comment]
@fabiocos 
Yes, they are expected!

**Pull request merged**
