### PR TITLE
matrix update new GENSIM and change 2018 PU to AVE_50

### PR DESCRIPTION
**Pull request by prebello**
This PR aims to:
1) update relval matrix with newest GENSIM strings (from 10_0_0_pre2)
2) update sample SinglePiE50HCAL with high statistics (default configuration)
3) change 2018PU samples to average 50

All changes already tested OK in the 10_0_0_pre2 release.

@fabozzi

### CODE REVIEW

**Comment by prebello** [comment]
please test workflows 11025.0,10225.0,10822.0

**Comment by prebello** [comment]
please test workflow 11025.0,10225.0,10822.0

**Comment by prebello** [comment]
please abort

**Comment by prebello** [comment]
please test workflow 10822.0

**Comment by prebello** [comment]
please abort

**Comment by prebello** [comment]
tests ok for wfs 11025.0 and 10225.0, reflecting the right average PU

**Comment by prebello** [comment]
+1

**Comment by fabozzi** [comment]
How did you handle the GENSIM inputs with v2? This part seems missing

https://cmsweb.cern.ch/das/request?view=list&limit=100&instance=prod%2Fglobal&input=dataset%3D%2FRelVal*%2FCMSSW_10_0_0_pre2-100X_mc2017_realistic_v1-v2%2FGEN-SIM

**Comment by fabozzi** [comment]
Please refer to this previous example for upgrade relvals:

https://github.com/cms-sw/cmssw/blob/CMSSW_9_1_0/Configuration/PyReleaseValidation/python/relval_steps.py#L1737-L1739

**Comment by prebello** [comment]
Thank you Francesco for the hint. 
Nevertheless, it doesn't change the GENSIM version. 
I guess I have followed exactly the proposed dictionary key syntax, as well as your example.
Would you have any idea about what is missing? 

# sometimes v1 won't be used - override it here - the dictionary key is gen fragment + '_' + geometry                  

versionOverrides={'BuMixing_BMuonFilter_forSTEAM_13TeV_TuneCUETP8M1_cfi_2017':'2',
                               'SingleElectronPt10_pythia8_2017':'2',
                               'HSCPstop_M_200_TuneCUETP8M1_13TeV_pythia8_2017':'2',
                     'RSGravitonToGammaGamma_kMpl01_M_3000_TuneCUETP8M1_13TeV_pythia8_2017':'2',
                          'WprimeToENu_M-2000_TuneCUETP8M1_13TeV-pythia8_2017':'2',
'DisplacedSUSY_stopToBottom_M_300_1000mm_TuneCUETP8M1_13TeV_pythia8_2017':'2',
                         'TenE_E_0_200_pythia8_2017':'2'
                             }

**Comment by fabozzi** [comment]
Hi, 
you have to pick up the name of the first step up to "2017" (and "2017PU" for PU relvals). 
For instance:
> runTheMatrix.py --what upgrade --showMatrix | grep 2017 | grep BuMixing
10080.0 BuMixing_BMuonFilter_forSTEAM_13TeV_TuneCUETP8M1_2017_GenSimFull+DigiFull_2017+RecoFull_2017+ALCAFull_2017+HARVESTFull_2017 
10280.0 BuMixing_BMuonFilter_forSTEAM_13TeV_TuneCUETP8M1_2017PU_GenSimFull+DigiFullPU_2017PU+RecoFullPU_2017PU+HARVESTFullPU_2017PU 
etc.

Therefore you must use the following in versionOverrides dictionaries:
'BuMixing_BMuonFilter_forSTEAM_13TeV_TuneCUETP8M1_2017':'2',
'BuMixing_BMuonFilter_forSTEAM_13TeV_TuneCUETP8M1_2017PU':'2'

**Comment by prebello** [comment]
ok. Now looks like that "dasgoclient" is not confortable with it. 
See for instance the msg below. It happens with all wfs. 

In DAS web the command "file dataset=/RelValTenE_0_200/CMSSW_10_0_0_pre2-100X_mc2017_realistic_v1-v2/GEN-SIM site=T2_CH_CERN" works fine though.

 May I kindly ask your help @vkuznet @davidlange6 ?

%%%%
panic: failed to parse X509 proxy: crypto/tls: failed to parse key: asn1: syntax error: sequence truncated

goroutine 1 [running]:
panic(0x796b20, 0xc4200158e0)
        /usr/lib/golang/src/runtime/panic.go:500 +0x1a1
github.com/dmwm/das2go/utils.HttpClient(0x23)
        /afs/cern.ch/work/v/valya/builds/w630/BUILD/slc6_amd64_gcc630/cms/dasgoclient-binary/v01.01.02/dasgoclient/gopath/src/github.com/dmwm/das2go/utils/fetch.go:85 +0x480
github.com/dmwm/das2go/utils.init()
        /afs/cern.ch/work/v/valya/builds/w630/BUILD/slc6_amd64_gcc630/cms/dasgoclient-binary/v01.01.02/dasgoclient/gopath/src/github.com/dmwm/das2go/utils/fetch.go:34 +0x9e
github.com/dmwm/das2go/dasql.init()
        /afs/cern.ch/work/v/valya/builds/w630/BUILD/slc6_amd64_gcc630/cms/dasgoclient-binary/v01.01.02/dasgoclient/gopath/src/github.com/dmwm/das2go/dasql/dasql.go:440 +0x51
github.com/dmwm/das2go/dasmaps.init()
        /afs/cern.ch/work/v/valya/builds/w630/BUILD/slc6_amd64_gcc630/cms/dasgoclient-binary/v01.01.02/dasgoclient/gopath/src/github.com/dmwm/das2go/dasmaps/dasmaps.go:514 +0x56
github.com/dmwm/das2go/das.init()
        /afs/cern.ch/work/v/valya/builds/w630/BUILD/slc6_amd64_gcc630/cms/dasgoclient-binary/v01.01.02/dasgoclient/gopath/src/github.com/dmwm/das2go/das/das.go:782 +0x51
main.init()

# in: /afs/cern.ch/work/p/prebello/private/PAGValidation/CMSSW_10_0_X_2017-12-22-2300/src going to execute cd 10085.0_TenE_0_200+TenE_E_0_200_pythia8_2017_GenSimFullINPUT+DigiFull_2017+RecoFull_2017+ALCAFull_2017+HARVESTFull_2017
 dasgoclient --limit 0 --query 'file dataset=/RelValTenE_0_200/CMSSW_10_0_0_pre2-100X_mc2017_realistic_v1-v2/GEN-SIM site=T2_CH_CERN' | sort -u > step1_dasquery.log  2>&1
 
---
10085.0_TenE_0_200+TenE_E_0_200_pythia8_2017_GenSimFullINPUT+DigiFull_2017+RecoFull_2017+ALCAFull_2017+HARVESTFull_2017 Step0-DAS_ERROR Step1-NOTRUN Step2-NOTRUN Step3-NOTRUN Step4-NOTRUN  - time date Sun Dec 24 18:59:49 2017-date Sun Dec 24 18:59:49 2017; exit: 1 0 0 0 0
0 0 0 0 0 tests passed, 1 0 0 0 0 failed

**Comment by vkuznet** [comment]
Patricia,
I think error message is clear, something wrong with your X509 proxy file.
Please do:
voms-proxy-init -voms cms -rfc
before you run dasgoclient and setup your X509_USER_PROXY environment to
your proxy file (obtained from voms-proxy-init command above).

You may try to use your own X509 CA's. For example,
setup X509_USER_KEY and X509_USER_CERT to your CA's, e.g.
export X509_USER_KEY=~/.globus/userkey.pem
export X509_USER_CERT=~/.globus/usercert.pem
and try again with this settings.

Best,
Valentin.

**Comment by prebello** [comment]
thank you 
in fact we source /afs/cern.ch/cms/PPD/PdmV/tools/subSetupAuto.sh to produce relvals
it is quite different from your instruction but I will try.

**Comment by prebello** [comment]
please test workflow 10085.0,10285.0

**Comment by prebello** [comment]
please test workflow 10085.0,10285.0

**Comment by prebello** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
