### PR TITLE
added dxr unit test

### PR DESCRIPTION
**Pull request by smuzaffar**
Fixed DXR and run `dxr-build.py --help`

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test with cms-sw/cmsdist#6988

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@silviodonato , @qliphy can we merge this? This should properly test DXR script. It will use the correct python required by the DXR itself

**Comment by qliphy** [comment]
+1

**Comment by qliphy** [comment]
merge

**Comment by santocch** [comment]
+1

**Pull request merged**
