### PR TITLE
Include <algorithm> in CSCDBL1TPParametersExtended.cc for std::find

### PR DESCRIPTION
**Pull request by guitargeek**
#### PR description:

Adding a missing include to build the CondFormats on my laptop with gcc 10.2.0.

#### PR validation:

CMSSW compiles.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

No backport intended.

### CODE REVIEW

**Comment by ggovi** [comment]
please test

**Comment by guitargeek** [comment]
Hi @ggovi, @sliviodonato, the bot test didn't get triggered :(

**Comment by qliphy** [comment]
please abort

**Comment by qliphy** [comment]
please test

**Comment by qliphy** [comment]
> Hi @ggovi, @sliviodonato, the bot test didn't get triggered :(

let's try again

**Comment by christopheralanwest** [comment]
+alca

**Comment by ggovi** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
