### PR TITLE
SiStripApvGainFromFileBuilder for 7_5_X

### PR DESCRIPTION
**Pull request by dimattia**
This is the implementation of SiStripApvGainFromFileBuilder for 7_5_X development branch

### CODE REVIEW

**Comment by ggovi** [comment]
+1

**Comment by davidlange6** [comment]
@dimattia , @ggovi - what is the invisioned role of this plugin and large data file? Its not clear from the description.

**Comment by dimattia** [comment]
Greetings,

sorry for the late reply. This package is supposed to be run just on 1 event. The purpose of this analyser is to produce a DB payload (with a given tag) for the SiStrip gain taken with a tick mark scan. The gain values are read from an external ascii file, while the event is used to gather the correct SiStrip cabling description for the tick mark gain scan.

Therefore I guess that the role of this package with respect to large data file is negligible.

Cheers,
Alessandro.


On 14 Apr 2015, at 02:46, David Lange <notifications@github.com<mailto:notifications@github.com>> wrote:


@dimattia<https://github.com/dimattia> , @ggovi<https://github.com/ggovi> - what is the invisioned role of this plugin and large data file? Its not clear from the description.

**Comment by davidlange6** [comment]
Hi @dimattia - I'm not sure I follow (rather, I'm sure I don't) the last line. This PR has a large data file. As presumably the production version of this plugin is instead the one from the database. If the same information is in the DB and in this file, we do not need to carry around the data in the release.

**Comment by davidlange6** [comment]
ping @dimattia?

**Comment by dimattia** [comment]
Hi David,

sorry I lost your e-mail of the 21h April. I apologise with you.

Are you concerned about the size of the “data" directory that I added? Well, this directory contains a file which constitutes the input of the analyser and is there just for convenience because it is pointed by the configuration option I put in the test directory. Of course the infos of this files are delivered into the DB as well, so, if you think is not worth to have it in the release too, you can remove this directory. The analyser will work anyway, providing to set the path to the proper input.

Thanks.

Best,
Alessandro.


On 02 May 2015, at 17:51, David Lange <notifications@github.com<mailto:notifications@github.com>> wrote:

ping

**Pull request closed without merging**
