### PR TITLE
74 x pixel dynamic eff in pre mixing

### PR DESCRIPTION
**Pull request by mdhildreth**
Adds capability to run Pixel Dynamic Inefficiency code on merged digi collections in PreMixing step.  This is necessary for two reasons: (1) the Digi step of the PreMixing merge has no pileup, so there is no inefficiency, which gives too many hits from the hard-scatter MC event; (2) Killing hits separately for the premixed pileup and hard-scatter, even if this was possible, could lead to cases where pileup hits were killed for different modules than hard-scatter hits due to the randomness of the process.
Also fixed here is the "circular" dependency for pileup information, whose "consumes" was removed for things coming from the Secondary Input Stream.

Note to selves: forthcoming "Era" definitions in cfg files (Pixels especially) will need to be modified to work with premixing.

### CODE REVIEW

**Comment by mdhildreth** [comment]
+1

**Comment by mdhildreth** [comment]
please test

**Comment by mdhildreth** [comment]
Sorry, left out the SiPixelSimBlock file...  tests worked great in my release area...

**Comment by mdhildreth** [comment]
+1

**Comment by davidlange6** [comment]
@cmsbuild, please test

**Comment by davidlange6** [comment]
+1

**Comment by VinInn** [comment]
@franzoni 
please note

**Pull request merged**
