### PR TITLE
Fix race condition in DAQ modules when exception is thrown in event processing (only affecting multithreading) - 80X

### PR DESCRIPTION
**Pull request by smorovic**
Port of #12200 (75X) and #12201 (76X)

A rare race condition occurs when exception is thrown during processing of last few events in a file and LS. In this case, another thread can already request next event from the source. If next event belongs to the next LS, input source reports to the FastMonitoringService a total number of events in previous LS.

Normally in case of exception, we skip writing JSON stream output (catching exception action callback in the FastMonitoringService), and subsequently hltd assigns missing events as error events to close micro-merge of that LS. However, suppression was not happening after input source already reported the total number of events to the FastMonitoringService. This lead to incomplete micromerge for some streams. The problem is present only in multithreading, as in the single-threaded mode source can get a request for next event before exception on currently processed event is thrown (i.e. event requests are aborted and run/LS get closed).

In this update, JSON output is suppressed if exception has been thrown, regardless of input source report.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test
@smorovic is this fix still needed in 74X (for online)?

**Comment by Dr15Jones** [comment]
I'm confused. In the present implementation of cmsRun the framework will not ask for the next 'event' of another lumi section until all the events from the previous lumi section have been processed. Does this mean your specific source only notices a new lumi by seeing the next event in the file is from a different lumi? If so, then maybe the source could accumulate its information about events only when the framework asks the source for the next event as apposed to when the framework ask the source what is the next record type.

**Comment by smorovic** [comment]
@Dr15Jones, yes, this is when source discovers new lumisection (discovering it based on files found in ramdisk), before framework gets it.
Event count from the source is used for a cross-check with event counting in FastMonitoringService. Actually I have never seen this check failing. It can also be done by accumulating in the source and being asked for it by the service. I'll look into doing it in that way next week.

**Comment by cvuosalo** [comment]
@smorovic:
Please fix the problem flagged by the static analyzer on line 90 of FastMonitoringService.cc:
```
ost<<i<<"="<<*((std::string *)(encPath_[0].decode(i)))<<" ";
```
I think a `dynamic_cast<const std::string *>` would be appropriate here.

**Comment by smorovic** [comment]
@cvuosalo, thanks for pointing it out, I'll go through problems flagged by the static analyzer next week and try to fix them.

**Comment by smorovic** [comment]
About 74X: it is planned is to switch to 75X for heavy ion, and MD + TS period is starting in 2 days. So I didn't push it (switching to another 74X release in HLT is unlikely).

**Comment by smorovic** [comment]
@cmsbuild please test

I moved the structure which keeps lumisection records accumulated in source, to the source class. However to be able to call into source from FastMonitoringService, I had to migrate source to from Utilities/plugins to Utilities.

**Comment by mommsen** [comment]
+1

**Comment by smorovic** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
@cmsbuild please test
Try to start the tests again

**Comment by cvuosalo** [comment]
@smorovic: Since #12148 and #12245 have been merged, this PR now has merge conflicts. Please fix the conflicts. This PR is otherwise ready for approval, and the Jenkins tests are OK.

**Comment by smorovic** [comment]
Not sure what went wrong in rebase. Closing this one and will make a new PR.

**Pull request closed without merging**
