### PR TITLE
DQM : migrate modules for esConumes part 2

### PR DESCRIPTION
**Pull request by sroychow**
#### PR description:
Part of #31061. Following up from #34208 to migrate more DQM packages for esConsumes.

#### PR validation:
Code compiles and static analyzer checks do no show the Eventsetup get warnings.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:
NA

### CODE REVIEW

**Comment by sroychow** [comment]
@cmsbuild please test.

**Comment by sroychow** [comment]
@cmsbuild please test

**Comment by sroychow** [comment]
> **Failed Tests**: RelVals-INPUT
From the log, I can see this 
```
21:08:13 603 603 600 561 118 41 3 1 1 tests passed, 0 0 0 0 0 0 0 0 0 failed
```
@smuzaffar can you suggest what is the issue? This is probably similar to [this](https://github.com/cms-sw/cmssw/pull/34179#issuecomment-864188811).

**Comment by smuzaffar** [comment]
@sroychow , please ignore this error. This is due to dasgoclient message 
```
2021/06/27 16:30:09 ERROR DAS QL ERROR, query=file block = /MinimumBias/Run2011A-ValSkim-08Nov2011-v1/RAW-RECO#239c497e-0fae-11e1-a8b1-00221959e72f run = 165121 site = T2_CH_CERN, idx=0, msg=unable to parse DAS query
```
I will fix the bot to ignore such errors.

**Comment by jfernan2** [comment]
Thanks @sroychow for this PR. I understand you are not fixing more packages in this PR so I am signing it

**Comment by jfernan2** [comment]
+1

**Comment by sroychow** [comment]
> Thanks @sroychow for this PR. I understand you are not fixing more packages in this PR so I am signing it

Hi @jfernan2 Thanks. That's right. After this PR, only Ecal DQM packages remain to be migrated. Since last Friday they said that they are working on them, I am not touching them.

**Comment by qliphy** [comment]
+1

**Comment by qliphy** [comment]
merge

**Pull request merged**
