### PR TITLE
Migrate module configurations in RecoTracker{ConversionSeedGenerators,DeDx} to use default cfipython v2

### PR DESCRIPTION
**Pull request by jeongeun**
#### PR description: 
Optimization of the python configurations: Improve maintainability by cleaning up the duplicated and cloning from the default/reference configurations.
(I re-make this PR. the original one PR #33901 was spoilt by my mistake..)
 
In this PR, 3 files changed.  
- RecoTracker/ConversionSeedGenerators/python/ConversionStep2_cff.py
- RecoTracker/ConversionSeedGenerators/python/ConversionStep_cff.py
- RecoTracker/DeDx/python/dedxEstimators_cff.py

(The previous PRs were  [PR#33207](https://github.com/cms-sw/cmssw/pull/33207), [PR#33307](https://github.com/cms-sw/cmssw/pull/33307), [PR#33352](https://github.com/cms-sw/cmssw/pull/33352), [PR#33543](https://github.com/cms-sw/cmssw/pull/33543),  [PR#33563](https://github.com/cms-sw/cmssw/pull/33563),  [PR#33671](https://github.com/cms-sw/cmssw/pull/33671),[PR#34007](https://github.com/cms-sw/cmssw/pull/34007),[PR#34009](https://github.com/cms-sw/cmssw/pull/34009) )

Updates: 
Replace explicit configuration with a reference from cfipython/. (migrating EDProducer("type", .. -> typeDefault.clone()) 
Remove the type specifications already presented in cfipython/fillDescriptions reference for improved syntax safety.
Remove the duplicated parameters that are exactly the same value in cfipython reference.

#### PR validation:
Event Content comparison check was also done and there is no change with these updates.
Tested in CMSSW_12_0_X, the basic test all passed in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html).

### CODE REVIEW

**Comment by smuzaffar** [comment]
code-checks

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
+1
- Technical migration, as planned
- Jenkins tests pass and show no differences in outputs

**Comment by qliphy** [comment]
+1

**Pull request merged**
