### PR TITLE
New Global Tags with cleanup and fixes for all scenarios; Reco changes for centralityBin in DQM; Heavy ion common alignment producer

### PR DESCRIPTION
**Pull request by diguida**
Adding Heavy-Ion specific Tracker Alignment AlCaReco producers for 75X, originally in #12030 by @jrcastle

To include centralityBin distribution in the DQM monitoring. For this, changes are requested in the HI reco sequence

```
Reconstruction_HI_cff.py
RecoHiCentrality_EventContent_cff.py
```

and in the Centrality DQM module

```
CentralityDQM_cfi.py
```

Originally in #12002 by @smdogra 

New Global Tags for all supported scenario.
Run1 ideal simulation: 75X_mcRun1_design_v7: As 75X_mcRun1_design_v5 with the following changes:
- taxonomy changes for DT reconstruction uncertainties, ECAL inter calibration errors, ECAL electronics map
- updated PF hadron calibration based on latest 75X analysis.

Run1 realistic simulation: 75X_mcRun1_realistic_v7: As 75X_mcRun1_realistic_v5 with the following changes:
- taxonomy changes for DT reconstruction uncertainties, ECAL inter calibration errors, ECAL electronics map
- updated PF hadron calibration based on latest 75X analysis.

Run1 HeavyIon simulation: 75X_mcRun1_HeavyIon_v7: As 75X_mcRun1_HeavyIon_v5 with the following changes:
- taxonomy changes for DT reconstruction uncertainties, ECAL inter calibration errors, ECAL electronics map
- added HFtowers label for centrality
- updated PF hadron calibration based on latest 75X analysis.

Run1 proton-lead simulation: 75X_mcRun1_pA_v7: As 75X_mcRun1_pA_v5 with the following changes:
- taxonomy changes for DT reconstruction uncertainties, ECAL inter calibration errors, ECAL electronics map
- updated PF hadron calibration based on latest 75X analysis.

Run2 design simulation: 75X_mcRun2_design_v10: As 75X_mcRun2_design_v7 with the following changes:
- added L1T Calorimeter parameters
- taxonomy changes for DT reconstruction uncertainties, ECAL inter calibration errors, ECAL electronics map
- updated Jet Probability calibration with the results produced on top of Spring15 DIGI-RECO campaign
- updated Preshower pedestals as per pedestal run in low gain taken in Run2015D
- updated Preshower Zero suppression thresholds with 6 ADC
- updated HCAL dead channel map as in Run2015D
- updated HCAL pedestals
- updated HCAL pedestal widths
- updated set of Jet Energy Corrections from Summer15 campaign, in 25 ns bunch spacing
- updated L1T RPC configuration accounting for the changes that were done in July 2015 at p5
- updated PF hadron calibration based on latest 75X analysis
- updated Pixel dynamic inefficiency for 50 ns bunch spacing by using 0.999 values in all modules
- updated Strip Gain from MIP cluster charge counting, fixing a 10% deficiency.

Run2 startup simulation: 75X_mcRun2_startup_v9: As 75X_mcRun2_startup_v6 with the following changes:
- added L1T Calorimeter parameters
- taxonomy changes for DT reconstruction uncertainties, ECAL inter calibration errors, ECAL electronics map
- updated Jet Probability calibration with the results produced on top of Spring15 DIGI-RECO campaign
- updated Preshower bad channels as per Run2015D
- updated Preshower pedestals as per pedestal run in low gain taken in Run2015D
- updated Preshower Zero suppression thresholds with 6 ADC
- updated HCAL dead channel map as in Run2015D
- updated HCAL pedestals
- updated HCAL pedestal widths
- updated set of Jet Energy Corrections from Summer15 campaign, in 25 ns bunch spacing
- updated L1T RPC configuration accounting for the changes that were done in July 2015 at p5
- updated PF hadron calibration based on latest 75X analysis
- updated Pixel dynamic inefficiency for 50 ns bunch spacing by using 0.999 values in all modules
- updated Strip Gain from MIP cluster charge counting, fixing a 10% deficiency.

Run2 asymptotic simulation: 75X_mcRun2_asymptotic_v10: As 75X_mcRun2_asymptotic_v9 with the following changes:
- added L1T Calorimeter parameters
- taxonomy changes for DT reconstruction uncertainties, ECAL inter calibration errors, ECAL electronics map
- updated Jet Probability calibration with the results produced on top of Spring15 DIGI-RECO campaign
- updated Preshower bad channels as per Run2015D
- updated Preshower pedestals as per pedestal run in low gain taken in Run2015D
- updated Preshower Zero suppression thresholds with 6 ADC
- updated HCAL dead channel map as in Run2015D
- updated HCAL pedestals
- updated HCAL pedestal widths
- updated set of Jet Energy Corrections from Summer15 campaign, in 25 ns bunch spacing
- updated L1T RPC configuration accounting for the changes that were done in July 2015 at p5
- updated PF hadron calibration based on latest 75X analysis
- updated Pixel dynamic inefficiency for 50 ns bunch spacing by using 0.999 values in all modules
- updated Strip Gain from MIP cluster charge counting, fixing a 10% deficiency.

Run2 HeavyIon simulation: 75X_mcRun2_HeavyIon_v7: As 75X_mcRun2_HeavyIon_v5 with the following changes:
- added L1T Calorimeter parameters
- added new label for HFtowers centrality
- taxonomy changes for DT reconstruction uncertainties, ECAL inter calibration errors, ECAL electronics map
- updated Jet Probability calibration with the results produced on top of Spring15 DIGI-RECO campaign.
- updated PF hadron calibration based on latest 75X analysis
- updated Pixel dynamic inefficiency for 50 ns bunch spacing by using 0.999 values in all modules

Run1 data: 75X_dataRun1_v8: As 75X_dataRun1_v6 with:
- updated AlcaReco Trigger bits to allow TkAl HI producers to run
- technical taxonomy change to get rid of fully qualified v1 account names in the tag names for several records
- updated DT,CSC and Global muon alignment for 2015
- updated CSC bad strips and bad wires
- updated EB,EE and ES alignments
- updated Ecal timing
- updated ECAL pulse shapes with an offline tag with 2 IOVs: the former for Run1, the latter for Run2
- updated Hcal gains, LongReco params, MCparams and Response corrections
- updated JEC to Summer V2 version
- added tag for L1TCaloParamsRcd
- updated PF hadron calibration with the latest version from dedicated MC studies.
- updated SiPixel Lorentz angle,templates and generic errors for 2015
- updated SiStrip noise
- move SiStrip FedCabling,Latency, Pedestals and Thresholds to Prompt tags
- updated Tracker alignment and surface deformations.

Run2 data: 75X_dataRun2_v8 As 75X_dataRun2_v6 with:
- updated AlcaReco Trigger bits to allow TkAl HI producers to run
- technical taxonomy change to get rid of fully qualified v1 account names in the tag names for several records
- updated DT,CSC and Global muon alignment for 2015
- updated CSC bad strips and bad wires
- updated EB,EE and ES alignments
- updated Ecal timing
- updated ECAL pulse shapes with an offline tag with 2 IOVs: the former for Run1, the latter for Run2
- updated Hcal gains, LongReco params, MCparams and Response corrections
- updated JEC to Summer V2 version
- added tag for L1TCaloParamsRcd
- updated PF hadron calibration with the latest version from dedicated MC studies.
- updated SiPixel Lorentz angle,templates and generic errors for 2015
- updated SiStrip noise
- move SiStrip FedCabling,Latency, Pedestals and Thresholds to Prompt tags
- updated Tracker alignment and surface deformations.

Run1 HLT: 75X_dataRun1_HLT_frozen_v4
As 75X_dataRun1_HLT_frozen_v3 (snapshot 2015-10-30 10:23:00 UTC) with the following changes:
- added tag for L1TCaloParamsRcd
- technical taxonomy change to get rid of fully qualified v1 account names in the tag names for several records
- updated PF hadron calibration with the latest version from dedicated MC studies.

Run2 HLT: 75X_dataRun2_HLT_frozen_v4: As 75X_dataRun2_HLT_frozen_v3 (snapshot 2015-10-30 10:23:00 UTC) with the following changes:
- added tag for L1TCaloParamsRcd
- technical taxonomy change to get rid of fully qualified v1 account names in the tag names for several records
- updated PF hadron calibration with the latest version from dedicated MC studies.

### CODE REVIEW

**Comment by diguida** [comment]
please test

**Comment by slava77** [comment]
I suppose, hopes for factorization of features are dead.
I've seen the same centrality bin changes in probably 3 different PRs already.

**Comment by diguida** [comment]
@slava77 the centrality bin changes were missing the backport in 75X as the new label was not yet backported in GT.
I took the opportunity to merge here all PR dealing with GT requests.

**Comment by diguida** [comment]
@slava77 I think the factorisation is operationally achieved:
* Run1 pp comparison will show only the effect of the new PF hadron calibration
* Run1 HI comparison will show the effect of the new centrality table, as well as the usage of the updated DQM module
* Run2 pp comparison will show the effect of the new conditions proposed for MC DR production
* Run2 HI comparison will show the effect of the new centrality table, as well as the usage of the updated DQM module. There we have not propagated any changes of the new conditions for DR campaign, as this set was already validated for the 75X HI campaign (and so the physics performance is untouched)
* Run1 data comparison will show some effects on the "legacy" conditions, especially for 2011 alignment.
* Run2 data comparison will show the effects of the brand new Run2 conditions used for 74X 2015B-C re-reco.

HTH

**Comment by diguida** [comment]
@slava77 just a reminder: this PR also adds some custom HI AlCaReco, and fixes the already existing `TkAlMinBiasHI` one by adding a track quality selection `ALCARECOTkAlMinBiasHI.trackQualities = cms.vstring("highPurity")`.

**Comment by diguida** [comment]
@Dr15Jones @slava77 from the [llvm report](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-12213/9391/llvm-analysis/report-d67e89.html#EndPath) `CentralityBinProducer` is still a legacy `EDProducer`.
For my education, what could prevent this to be moved to `stream::EDProducer` is the fact that the run number is cached at `beginRun`

````
CentralityBinProducer::CentralityBinProducer(const edm::ParameterSet& iConfig):
    prevRun_(0)
    //...
//...
void CentralityBinProducer::beginRun(edm::Run const& iRun, const edm::EventSetup& iSetup) {
    //...
    prevRun_ = iRun.run();
   //...
}
````

Is this correct?

**Comment by Dr15Jones** [comment]
stream modules are allowed to change their member data. Remember, we make multiple copies of stream modules where each copy is only run on one thread at a time. It is global modules which are not allowed to change their member data.

**Comment by slava77** [comment]
@diguida @mmusich 
What's the status of this PR?
It's not even signed by alca ... and we have #12214 depending on this PR.

**Comment by mmusich** [comment]
+1
@slava77 let us know if you need some re-factorization of the conditions to assess the changes. @diguida detailed in https://github.com/cms-sw/cmssw/pull/12213#issuecomment-152666005 what we should expect.

**Comment by slava77** [comment]
@mmusich 
my comment about factorization was really just about the centralityBin modifications not to be in the same PR as autoCond.py changes (if I understand correctly, it's not needed to stream the updated payloads, but maybe I misunderstood).
I was not concerned by factorization of multiple changes in the payloads in the new GT.

As a result of this coupling, we now have a snow-ball rolling: #12214 now includes this PR just because it needed the centrality changes.
Should we "-1" this PR and go to #12214 or should we instead force #12214 to wait until this PR is merged?

**Comment by slava77** [comment]
In local tests I get the following problem in step3 of 140.51 (2010 HI run)
```
----- Begin Fatal Exception 04-Nov-2015 14:58:01 CET-----------------------
An exception of category 'Configuration' occurred while
   [0] Processing run: 152698 lumi: 17 event: 49592
   [1] Running path 'pathALCARECOTkAlUpsilonMuMuHI'
   [2] Calling event method for module HLTHighLevel/'ALCARECOTkAlUpsilonMuMuHIHLT'
Exception Message:
 HLTHighLevel [instance: ALCARECOTkAlUpsilonMuMuHIHLT - path: pathALCARECOTkAlUpsilonMuMuHI]: No triggerList with key TkAlUpsilonMuMuHI in AlCaRecoTriggerBitsRcd
----- End Fatal Exception -------------------------------------------------

```

**Comment by mmusich** [comment]
@slava77 we didn't update the AlCaReco trigger bits for all the IOVs but just the one probed for the 2011 HI data (which is used for the bot tests). Since there are other workflows using runs bound to other IOVs we'll need to updated also these ones. Thanks for spotting the issue.

**Comment by mmusich** [comment]
@slava77 may I propose the following. I'll make a new PR 
   * cherry-picking https://github.com/diguida/cmssw/commit/5ed05b8332aebb3156c2e9c0f29b1603755c2caf and https://github.com/diguida/cmssw/commit/78dfffb098014f593a48860d6ef9a00a0d34644c 
   * fixing the AlCaReco triggerbits also in 2010 IOV
   * the centrality bin change goes decoupled.

**Comment by slava77** [comment]
On 11/4/15 7:03 AM, Marco Musich wrote:
> @slava77 <https://github.com/slava77> may I propose the following. I'll
> make a new PR
> 
>   * cherry-picking diguida@5ed05b8
>     <https://github.com/diguida/cmssw/commit/5ed05b8332aebb3156c2e9c0f29b1603755c2caf>
>     and diguida@78dfffb
>     <https://github.com/diguida/cmssw/commit/78dfffb098014f593a48860d6ef9a00a0d34644c>
> 
>   * fixing the AlCaReco triggerbits also in 2010 IOV
>   * the centrality bin change goes decoupled.


Good for me.

Thank you.

**Comment by rkunnawa** [comment]
@mmusich does this mean that to add the centrality bins, we would need a separate PR (which would be a backport of #12002)? in that way, once we have that, i can add the #12214 to that then? please confirm so we can submit that  
Raghav

**Comment by mmusich** [comment]
@rkunnawa as far as I can understand we first need to get the MC Global Tags with the `HFtower` label into release to get your PR technically passing the tests.

**Comment by rkunnawa** [comment]
@mmusich hmm yeah, we definitely need that. So the plan is to first push your PR with the necessary updated GT in and then we come with the combined PR which adds the centrality bin and the jet DQM which depends on that to 75X. @smdogra is this an acceptable plan of action?

**Comment by mmusich** [comment]
@slava77  #12259 should implement what detailed in https://github.com/cms-sw/cmssw/pull/12213#issuecomment-153754865

**Comment by slava77** [comment]
@mmusich 
thanks for the separation/factorization.
Can we close this one then?

**Comment by mmusich** [comment]
@slava77 I think so, I let @diguida  close this one, after the GTs are merged I guess you can proceed with https://github.com/cms-sw/cmssw/pull/12214

**Comment by diguida** [comment]
-1
superseded by #12259

**Comment by slava77** [comment]
@mmusich @diguida 
are the comments for "Run1 data: 75X_dataRun1_v8: As 75X_dataRun1_v6 with:" all correct?
(e.g. muon alignment update)

**Comment by slava77** [comment]
since I did the tests using this PR, I'm going to post some Qs here:

based on CMSSW_7_5_4 as a baseline + this PR as "new"

data run2 (134.802 DoubleEG 2015C)
HO energy changed by 2 orders of magnitude 
all_sign625vsorig_rundoubleeg2015cwf134p802c_log10horechitssorted_horeco__rereco_obj_obj_energy
Same thing, now in PF clusters:
all_sign625vsorig_rundoubleeg2015cwf134p802c_log10recopfclusters_particleflowclusterho__rereco_obj_energy
this makes more sense though, since there shouldn't be any noticeable energy in HO to the first order

more energy above threshold in HF:
all_sign625vsorig_rundoubleeg2015cwf134p802c_recocalojets_ak4calojets__rereco_obj_eta


The BS fit is apparently much more constraining now (or more precise)
all_sign625vsorig_rundoubleeg2015cwf134p802c_log10recovertexs_offlineprimaryverticeswithbs__rereco_obj_xerror
all_sign625vsorig_rundoubleeg2015cwf134p802c_recovertexs_offlineprimaryverticeswithbs__rereco_obj_x
all_sign625vsorig_rundoubleeg2015cwf134p802c_recovertexs_offlineprimaryverticeswithbs__rereco_obj_y

run1 2011 HI (140.53) has a pretty large change in zdc hit energy
all_sign625vsorig_runhi2011wf140p53c_zdcrechitssorted_zdcreco__rereco_obj_obj_energy

run2 MC and run1 data/MC have qualitatively small differences.


are all of these expected?

**Comment by slava77** [comment]
(some plots were added in the previous [edited] post at https://github.com/cms-sw/cmssw/pull/12213#issuecomment-154158926

**Comment by mmusich** [comment]
Dear @slava77 thanks for the very detailed check and remarks!
Let me adress the comments one by one. First let's provide the browser diffs (unfortunately missing from the PR description):
   * [New Run1 vs Old Run1](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/75X_dataRun1_v6/75X_dataRun1_v8)
   * [New Run2 vs Old Run 2](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/75X_dataRun2_v6/75X_dataRun2_v8)

As you can see the list of changes is quite extensive.
For what concerns Run1 regarding your comment https://github.com/cms-sw/cmssw/pull/12213#issuecomment-154143845, yes the description should be correct. In most places we tried to have the same tag for Run1 and Run2 data Global Tags, serving different conditions based on the IOV. With this mechanism, even when we update the Run2 IOVs only, moving the Run2 GT to pick up a newer tag (say for example `CSCAlignment_v9_offline` instead of `CSCAlignment_v8_offline`) for consistency we change also the tag in the Run1 GT, but since the payloads associated to the Run1 IOV didn't change, we shouldn't expect changes. 
Now coming to HO differences seen in the comparison, I believe this comes from the consistent update of all this set of Hcal conditions (that was required by Hcal DPG) + Update of the PF calibrations:

| Record  | 75X_dataRun2_v6  | 75X_dataRun2_v8 |
|:------------ |:---------------:|:-----:|
| HcalGainsRcd    | HcalGains_v5.07_offline  | HcalGains_v5.09_offline |
| HcalLongRecoParamsRcd  |  HcalLongRecoParams_v1.1_offline   | HcalLongRecoParams_v1.3_offline  |
| HcalMCParamsRcd  | HcalMCParams_v3.0_offline  | HcalMCParams_v5.0_offline  |
| HcalRespCorrsRcd | HcalRespCorrs_v4.7_offline | HcalRespCorrs_v5.0_offline |
| PFCalibrationRcd | PFCalibration_v3_mc | PFCalibration_v5_hlt |

with a consistent change in the JEC from the `Summer15_V1_DATA` version to the `Summer15_V2_DATA`. Please notice that we implemented the same series of changes also for 76X (in PR https://github.com/cms-sw/cmssw/pull/12079: [diff](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/76X_dataRun2_v9/76X_dataRun2_v7) N.B.: `HcalRespCorrs_v5.0_offline` and `PFCalibration_v5_hlt` where already included in the 76X Global Tag)
For what concerns the improvement in the beamspot this is due to the introduction of the the correct Tracker Alignment + APE + Tracker surface deformations for the Run-II IOVs between [TrackerAlignment_v10_offline and TrackerAlignment_v13_offline](https://cms-conddb.cern.ch/browser/#diff/Prod/tags/TrackerAlignment_v10_offline/TrackerAlignment_v13_offline). The beasmpot for Run2 IOVs were already appended in the offline tag when fixing the Global Tags for 74X re-reco but the alignment change was not yet propagated. Now it is. 
For what concerns the "more energy above threshold in HF" and "pretty large change in zdc hit energy" I am actually uncertain. I invite @abdoulline to cross check if possible my list of condition changes for the [Run-I data GT](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/75X_dataRun1_v6/75X_dataRun1_v8)

**Comment by abdoulline** [comment]
Concerning HCAL list of changes:

(1) The _major_ change is HcalGains_v5.07_offline -> HcalGains_v5.09_offline
The former _shouln't be used_ for Run 2 at all, as it has only Run 1 payloads (for old HO and old HF photodetectors).
The latter (v5.09) exists since the beginning of 2015 and contains both Run 1 and appropriate Run 2 (for updated HO and HF subdetectors) gains. 
(2) HcalLongRecoParams_v1.3_offline 
(finally, better late than never) replaces very old (incorrect) ZDC conditions. 
(3) HcalMCParams_v3.0_offline -> v5.0_offline 
is irrelevant for data reco, kept in sync with MC due to some historical reasons.
(4) HcalRespCorrs_v4.7_offline -> v5.0_offline  
reflects "back-propagation" of the most recent validated corrections (0T and 3.8T) to 2015A/B/C(&D)  data periods
(5) PFCalibrationRcd - cannot tell anything from HCAL side.
HCAL has HcalPFCorrsRcd, but it's dummy (=1.0).

**Comment by mmusich** [comment]
thanks @abdoulline therefore my take is that we can mark all the above as changes expected.

**Comment by abdoulline** [comment]
Yes.

BTW, in 760 data RelVals wrt 760_pre7 is the same issue of gains in 
76X_dataRun2_v4 -> 76X_dataRun2_v10 
HcalGains_v5.07_offline -> HcalGains_v5.09_offline

Salavat

**Comment by slava77** [comment]
On 11/6/15 3:32 AM, Salavat Abdullin wrote:
> Concerning HCAL list of changes:
> 
> (1) The /major/ change is HcalGains_v5.07_offline -> HcalGains_v5.09_offline
> The former /shouln't be used/ for Run 2 at all, as it has only Run 1
> payloads (for old HO and old HF photodetectors).
> The latter (v5.09) exists since the beginning of 2015 and contains both
> Run 1 and appropriate Run 2 (for updated HO and HF subdetectors) gains.

Is this a problem of the rereco GT?
(was the prompt GT correct?)


In fact, the same question about the prompt GT correctness applies to all
(prompt GT is not a part of the autoCond)

**Comment by mmusich** [comment]
@slava77 it's only a problem of the re-reco GT. In Prompt GT we have new IOVs for Run2 since months.

**Comment by mmusich** [comment]
@slava77 putting some substance to my previous statement please have a look here: [diff between Prompt and ReReco GT gains](https://cms-conddb.cern.ch/browser/#diff/Prod/tags/HcalGains_v2.08_express/HcalGains_v5.09_offline):
The same two payloads are recurrent in both the tags:
   * c529f437df2fb09fcf6e6f6f64a832389372f848 (0T version)
   * 3e6bded5a30d31acf6735b37f8834364d396e636  (3.8T version)

Just the IOV boundaries differ (removing the latency in prompt).

**Comment by abdoulline** [comment]
Indeed, this is issue of old (pre-2015) _offline conditions tag usage 
for re-reco. HLT/Prompt/Express were/are all OK.

**Comment by abdoulline** [comment]
Right, for Offline we're using more precise "a posteriori" 0T<->3.8 
IOVs boundaries, while for propmt/express/hlt IOVs might be delayed in some 
cases...

**Pull request closed without merging**
