### PR TITLE
Correct prescales

### PR DESCRIPTION
**Pull request by defranchis**
Adding functionality to retrieve and apply pre-scale weights to TopMonitor in order to get meaningful efficiency plots for pre-scaled HLT paths. Unfortunately the prescaleWeightProvider seems not to be working at the moment due to a problem with l1GtTriggerMenuLite, so the change will only have effect once the problem is fixed. For the moment, all weights are equal to 1 and no change will be visible in the efficiency plots

### CODE REVIEW

**Comment by defranchis** [comment]
@mtosi can we please test?

**Comment by mtosi** [comment]
@cmsbuild, please test

**Comment by mtosi** [comment]
@defranchis, there are other config files which need to be updated, aren't there ?

**Comment by dmitrijus** [comment]
+1

**Comment by defranchis** [comment]
Dear all, 
please wait before merging this PR, it's not clear if the prescaleWeightProvider tool can actually be fixed. I'm working on another PR to try to implement another method

**Comment by dmitrijus** [comment]
hold

**Comment by davidlange6** [comment]
hi @defranchis  all - any plans to update this PR?

**Comment by defranchis** [comment]
Hi @davidlange6 yes but probably not very soon. Shall I close and open again when I have updates?

**Pull request closed without merging**
