### PR TITLE
 Small fix in HLT b-tag validation code (76X)

### PR DESCRIPTION
**Pull request by silviodonato**
This PR fixes:
- setEfficiencyFlag() option for mistag vs efficiency plots
- trigger name HLT_PFMET120_NoiseCleaned_BTagCSV07_v -> HLT_PFMET120_NoiseCleaned_BTagCSV0p72_v
- trigger name HLT_CaloMHTNoPU90_PFMET90_PFMHT90_IDLoose_ -> HLT_CaloMHTNoPU90_PFMET90_PFMHT90_IDTight_

PR in 75X:  #10052

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Comment by perrotta** [comment]
Since data taking (and corresponding validation) is actually done with 74X, does it exist (or do you foresee) a 74X counterpart of this pull request?

**Comment by silviodonato** [comment]
I've prepared a branch for it here: https://github.com/cms-sw/cmssw/compare/CMSSW_7_4_X...silviodonato:HLT-val-btag-fix-74X
Please notice that I'm still using the old HLT path names, as they are used in 74X: http://cmslxr.fnal.gov/source/HLTrigger/Configuration/python/HLT_25ns14e33_v1_cff.py?v=CMSSW_7_4_6
Eg. HLT_CaloMHTNoPU90_PFMET90_PFMHT90_IDLoose instead of HLT_CaloMHTNoPU90_PFMET90_PFMHT90_IDTight.

If you are ok with it I will proceed with the PR.

**Comment by silviodonato** [comment]
The issue has been solved with https://github.com/cms-sw/cmssw/pull/10493

**Pull request merged**
