### PR TITLE
Removing not used muon MVAs from miniAOD (backport)

### PR DESCRIPTION
**Pull request by andrea21z**
#### PR description:

- This PR is created to solved an [issue](https://gitlab.cern.ch/cms-nanoAOD/xpog-coordination/-/issues/46) involving two Muon MVAs (ttH lepton MVAs).  This removal is a follow up on the discussion taken in [PR40100](https://github.com/cms-sw/cmssw/pull/40100#issuecomment-1322129298).
- We want to remove the 'mvaValue' and 'lowptMvaValue' from miniAOD because those MVAs are not updated and they are not used by anyone. The analyses using these MVAs use nanoAOD, and there the MVAs are correct.
- When I was doing it, I found that inside the loop where the MVAs values were computed, it was also filled the selector 'MultiIsoMedium' and the variables 'jetPtRel' and 'jetPtRatio'. I talked to SUSY group to see if they were variables that were currently in use and, after checking with analyzers, they told me to leave them in the code. In short, I deleted the MVAs and everything related to them and renamed the module 'MuonMvaEstimator' to 'CalculatePtRatioRel'.

#### PR validation:
- We check the output running runTheMatrix and everything looks fine.
- We execute the basic tests  suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html).

#### This PR is a backport of [PR#40876](https://github.com/cms-sw/cmssw/pull/40876).

### CODE REVIEW

**Comment by swertz** [comment]
enable nano

**Comment by swertz** [comment]
please test

**Comment by swertz** [comment]
+1

Backport in line with master.

**Comment by clacaputo** [comment]
+reconstruction 

- backport of https://github.com/cms-sw/cmssw/pull/40876
- in line with master

**Comment by perrotta** [comment]
backport of https://github.com/cms-sw/cmssw/pull/40876.

**Comment by clacaputo** [comment]
+reconstruction

- resign
- backport of https://github.com/cms-sw/cmssw/pull/40876
- in line with master

**Comment by swertz** [comment]
+1

**Comment by perrotta** [comment]
+1
- Verbatim backport of https://github.com/cms-sw/cmssw/pull/40876

**Pull request merged**
