### PR TITLE
PR #11216 in 7_4_X propagated to 7_6_X, Exotica DQM Updated histograms

### PR DESCRIPTION
**Pull request by aescalante**

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
@aescalante - please give this PR a descriptive title for the release notes. Thanks!

**Comment by aescalante** [comment]
@davidlange6  PR title updated.
Best
Alberto.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
