### PR TITLE
Run3-ft23 Correct run3 scenario for dd4hep and add the other Phase2 scenarios

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Correct run3 scenario for dd4hep and add the other Phase2 scenarios

#### PR validation:

Use standard runTheMatrix test workflows 

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by kpedro88** [comment]
@bsunanda eventually we should duplicate/extend/modify the phase 2 geometry scripts so this can be maintained more automatically

**Comment by cvuosalo** [comment]
The Run 3 change, at least, should be backported into 11_1.

**Comment by cvuosalo** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
