### PR TITLE
Migrate part of PPS modules to use esConsumes

### PR DESCRIPTION
**Pull request by fabferro**
#### PR description:
As requested in issue #31061, this PR migrates to esConsumes the following packages:
CalibPPS and Dqm/CTPPS 

#### PR validation:
Private checks have been done showing no changes in reconstruction, simulation and DQM plots of PPS.

No backport needed.

@jan-kaspar

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by yuanchao** [comment]
+1

* further migration to esConsumes
* wf matrix tests and unit tests passed
* build warning is from ROOT macro

**Comment by qliphy** [comment]
+1

**Pull request merged**
