### PR TITLE
PFMet and PuppiMET Branches: Backport to CMSSW_141X

### PR DESCRIPTION
**Pull request by wajidalikhan**
#### PR description:
- This is a back-port to CMSSW_141X for the PR [https://github.com/cms-sw/cmssw/pull/44038](https://github.com/cms-sw/cmssw/pull/44038) which incorporates 
- PFMet and PuppiMET do not have the same  variables stored in NanoAOD, consistent variables to be stored in both the PFMET and PuppiMET at the NanoAOD for next data taking
- Remove / Rename some of the other relevant branches 

- Had to do the cherry picking of the [https://github.com/cms-sw/cmssw/pull/44038/commits](https://github.com/cms-sw/cmssw/pull/44038/commits) because unknown issues

### CODE REVIEW

**Comment by wajidalikhan** [comment]
Hi @hqucms, there are two separate PR going on. One [MiniAOD Clean up, BTW this is still pending, hasn't been merged yet](https://github.com/cms-sw/cmssw/pull/44335) is dealing with MiniAOD clean up and other one is dealing with renaming or updating MET branches [NanoAOD](https://github.com/cms-sw/cmssw/pull/44038)

**Comment by mandrenguyen** [comment]
> Hi @hqucms, there are two separate PR going on. this one One [MiniAOD Clean up](https://github.com/cms-sw/cmssw/pull/44335) , BTW this is still pending, hasn't been merged yet. The other one is dealing with MiniAOD clean up and other one is dealing with renaming or updating MET branches in [NanoAOD](https://github.com/cms-sw/cmssw/pull/44038)

Can you please update the PR description though?  Please keep the list of PRs explicit rather than hiding the PR#s in hyper-lnks.

**Comment by mandrenguyen** [comment]
The milestone seems to be set to 14_1_X rather than 14_0_X

**Comment by vlimant** [comment]
please overhaul this backport (cherry pick the proper commit and make it against 14_0_X) asap @wajidalikhan

**Comment by hqucms** [comment]
The 14_0_X backport is done in https://github.com/cms-sw/cmssw/pull/44495.
@wajidalikhan Can you close this one?

**Comment by vlimant** [comment]
please close

**Pull request closed without merging**
