### PR TITLE
Removed ShiftFillLast because it generates confusion in shifters

### PR DESCRIPTION
**Pull request by dinardo**
A DQM shifter pointer me to a feature of the layout that might be misunderstood,
therefore I decided to simplify the histograms: I removed the ShiftFillLast and I
made all plots with a fixed X axis range that span over 20h of uninterrupted running
- Mauro.

### CODE REVIEW

**Comment by dinardo** [comment]
Hi,
I'm not sure what the conflicts. I tested it in CMSSW_7_6_0_pre2.
Many thanks for letting me know if there is something I need to do
to solve the conflicts.
Kind regards,
- Mauro.

**Comment by deguio** [comment]
please rebase against a recent snapshot of 76x

**Comment by dinardo** [comment]
Hi Fede,
sure no problem.
I have these instructions to perform a rebase:
git fetch official-cmssw CMSSW_7_6_X:CMSSW_7_6_X
git rebase -i --onto CMSSW_7_6_X my-branch~2 my-branch
git push my-cmssw my-branch -f
But at the second instruction I get the errors message:
fatal: Needed a single revision
invalid upstream my-branch~2
Can you please give me the recipe to perform a rebase ?
Many thanks,
- Mauro.

**Comment by deguio** [comment]
normally I check the help.
git rebase --help
it is very clear and covers all the main use cases
I am not a git expert.. sorry.
F.

**Comment by deguio** [comment]
-1
superseded

**Comment by dinardo** [comment]
Done. Please have a look at  : #11436
- Mauro.

**Pull request closed without merging**
