### PR TITLE
Run3-hcx295 Correct validation code for MB of HCAL

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Correct validation code for MB of HCAL

#### PR validation:

Tested using cfg's in Validation/Geometry/test

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
+1

**Comment by jfernan2** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
