### PR TITLE
Instrument cmssw for nvidia nvprof/nvvm (10.1.x)

### PR DESCRIPTION
**Pull request by fwyzard**
Instrument cmssw for nvprof/nvvm
  - implement a Service to provide CMSSW-aware annotations to nvprof/nvvm
  - highlight selected modules and delayed modules
  - update for CMSSW 10.1.x

### CODE REVIEW

**Comment by fwyzard** [comment]
Update #21946 for compatibility with #21872 .

**Comment by fwyzard** [comment]
@cmsbuild, please test.

**Comment by fwyzard** [comment]
type new-feature

**Comment by davidlange6** [comment]
please test

**Comment by fabiocos** [comment]
@fwyzard could you please point to the new packaged needed? At present this PR adds capabilities without affecting any production workflow as far as I can see, right?

**Comment by fwyzard** [comment]
Indeed, this adds a new service that allows to see the cmsRun transitions (runs, lumis, events, modules, etc.) in the NVIDIA profiler.
While useful on its own, it is even more so once we start offloading some of the computations to the GPUs.

Since it adds a brand new service, no existing workflows should be affected.

The new package was agreed with @makortel , to keep the dependency on CUDA dependency out of the FWCore/Services package.

**Comment by makortel** [comment]
The package is something we came up to suggest for "core heterogeneous computing" components (for some "thinking out loud" see https://github.com/cms-sw/cmssw/pull/21946#issuecomment-360396787).

**Comment by fabiocos** [comment]
@Dr15Jones @smuzaffar before integrating this code (which is ok for me) we need to decide:

1) is it ok to open a completely new package? For the time being it is just one class, for which a new package seems an overkill. Probably this is parallel to FWCore, and I understand this will be expanded in time (see the above comment by @makortel).

2) if it is reasonable, we need to assign it to a category and have a responsible to sign it. It could just be Core Software, as we already do for several Utilities, or we could have a new category and a dedicated responsible for it. What is your preference?

**Comment by Dr15Jones** [comment]
@fabiocos I'd be OK with Utilities/CUDAServices. So we would have not have to create a new top level Subsystem. This does belong in its own package since this has a unique external dependency.

**Comment by fwyzard** [comment]
I don't mind the package, but I'd rather people agree before I move it again.

Does this mean the next accelerator service will go under Utilities instead of HeterogenousCore ?

**Comment by Dr15Jones** [comment]
It does not matter to me if we reuse Utilities or have a new HeterogenousCore. Do we anticipate many more items in HeterogenousCore? Utilities already contains various storage system adaptors which customize cmsRun for different sites. One could see accelerators as something similar.

**Comment by makortel** [comment]
The current prototype (which I'd like to go through at least one round of testing before integration to master) foresees in addition to this PR
* `CUDAService` for general checks of CUDA device availability and possibly resource (e.g. CUDA stream, memory) management, in the same package as the `NVProfilerService` of this PR
   * For additional device types we foresee a service per device type
* `AcceleratorService` for CPU+heterogeneous algorithm scheduling, should go to separate package than the per-device-type services (but uses them)
   * It could be that the result of prototyping is something different than a service, nevertheless the component should live somewhere
* `HeterogeneousProduct`, a transient event data format to keep record which devices have a copy of the data and to automatically transfer the data to CPU when needed. Better be in a package separate from any of above.
   * Could also go under `DataFormats`. If there, should it go to `DataFormats/Common` or to a separate package? At least for now the it does not bring in any special dependencies.

(I don't have strong opinions where to place things as long as there is some consistency)

**Comment by fwyzard** [comment]
By the way, we will likely need also a place for CUDA helper headers / libraries.

**Comment by fwyzard** [comment]
@fabiocos , what do I need to do to get the same preferential treatment as the framework changes, and have my PRs merged within 12 hours instead of 12 days ?

**Comment by fabiocos** [comment]
@Dr15Jones @smuzaffar given the explanations, I think we can move forward with the present proposal, and put it for the time being under the Core category. Please make an alternative category suggestion if you disagree.

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Pull request merged**
