### PR TITLE
Run3-hcx260 Update the material budget study code for HCAL

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Update the code to study material budget for HCAL

#### PR validation:

Tested using the cfg file in Validation/Geometry/test

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by jfernan2** [comment]
+1

**Comment by cvuosalo** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
