### PR TITLE
bsunanda:Phase2-hgx69 Complete HGCal Geometry with no big holes

### PR DESCRIPTION
**Pull request by bsunanda**
Update reco geometry

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by ianna** [comment]
+1

**Comment by bsunanda** [comment]
@civanch @mulhearn @rekovic Please approve

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
@kpedro88 - you are happy with this PR? 
(the L1 change is trivial..)

**Comment by kpedro88** [comment]
@davidlange6 for now, it's fine. We had a private discussion in which we concluded that some of the L1 maps need to be updated, but this can happen in parallel.

@bsunanda did you test this PR with at least 100 ttbar events? (Just in case there are any other infrequently-occurring issues...)

**Comment by bsunanda** [comment]
Yes I did. In any case L1 is turned off.

**Comment by davidlange6** [comment]
merge

**Pull request merged**
