### PR TITLE
l1 track trigger rebased

### PR DESCRIPTION
**Pull request by davidlange6**
#15691 rebased

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
please test

**Comment by slava77** [comment]
it looks like changes in this PR SimTracker/TrackTriggerAssociation/src/classes_def.xml
are the reason for many issues with dictionary locations from the dictionary checker (``` duplicateReflexLibrarySearch.py --dir ./ --lostDefs ``` )
At a first glance it also looks like a number of dictionaries are duplicates in addition to be misplaced
(like Ref for TrackingParticle or a dict for map<int>

**Comment by sviret** [comment]
@slava77 I guess that I can indeed remove the TrackingParticle related dict from there (they were already there before). For the rest it's more complicated, as these are the dictionaries for the L1Tracking associator class. I don't think that they are defined anywhere else.

**Comment by smuzaffar** [comment]
@sviret 
```
edm::Ptr< TrackingParticle >
vector< edm::Ptr< TrackingParticle > >
```
should move to SimDataFormats/TrackingAnalysis. For the rest, I can update the duplicate dict checker script to match 
```
TTClusterAssociationMap
TTStubAssociationMap
(TTStub|TTCluster).*edm::refhelper::FindForDetSetVector.*Phase2TrackerDigi.*
```
for SimTracker/TrackTriggerAssociation.

**Comment by sviret** [comment]
@smuzaffar , OK thanks for the reply, I will move the TrackingParticle stuff in my next L1Tracking PR, which is planned for this week

**Comment by smuzaffar** [comment]
@sviret , this is still not fixed. Dictionary checking tests are still reporting these
https://cmssdt.cern.ch/SDT/cgi-bin/showDupDict.py//slc6_amd64_gcc530/www/sun/8.1-sun-23/CMSSW_8_1_X_2016-11-13-2300/testLogs/dupDict-lostDefs.log

**Comment by sviret** [comment]
@smuzaffar sorry about the delay, definitely no time available to work on that currently. Will look back at this in December

**Pull request merged**
