### PR TITLE
Run3-gex77 Remove reference to duplicated vaccum

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Remove reference to duplicated vaccum and a new scenario is under preparation for this

#### PR validation:

Tested using a cfg in Geometry/VeryForwardData/test

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
@cvuosalo , do you have any comment?

**Comment by cvuosalo** [comment]
+1

**Comment by bsunanda** [comment]
@srimanob Can you approve this PR?

**Comment by civanch** [comment]
we discussed it Monday

**Comment by srimanob** [comment]
+Upgrade

**Comment by srimanob** [comment]
Urgent

**Comment by qliphy** [comment]
+1

**Pull request merged**
