### PR TITLE
Changed modules in HLTrigger/Muon to be thread-friendly

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

This removes the CMS deprecation warnings.

#### PR validation:

Code compiles without issuing warnings.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Martin-Grunewald** [comment]
Hmm, can you remind me of the difference between ```global``` and ```one```?

**Comment by Martin-Grunewald** [comment]
Thanks!

**Comment by missirol** [comment]
+hlt

**Comment by perrotta** [comment]
+1

**Pull request merged**
