### PR TITLE
Run3-alca190 Modify the AlCaRecoProducer for HBHEMuon

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Modify the AlCaRecoProducer for HBHEMuon

#### PR validation:

Use the runTheMatrix test workflows

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

May need back porting to 12_0

### CODE REVIEW

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by yuanchao** [comment]
+1

* matrix tests and unit tests passed
* static build warnings are not part of the PR

**Comment by perrotta** [comment]
@bsunanda , since you added the default configuration via `fillDescriptions` (good!), please now remove the file with the explicit config with the same name Calibration/HcalAlCaRecoProducers/python/alcaHBHEMuonFilter_cfi.py

And then, in Calibration/HcalAlCaRecoProducers/python/ALCARECOHcalCalHBHEMuonFilter_cff.py the line
```
from Calibration.HcalAlCaRecoProducers.alcaHBHEMuonFilter_cfi import *
```
should be changed as
```
from Calibration.HcalAlCaRecoProducers.AlcaHBHEMuonFilter_cfi import *
```

**Comment by bsunanda** [comment]
@perrotta There is no file named Calibration/HcalAlCaRecoProducers/python/alcaHBHEMuonFilter_cfi.py
in the PR - it was removed. Also the file created is named AlcaHBHEMuonFilter_cfi.py and that is why the cff file was modified.

**Comment by perrotta** [comment]
> @perrotta There is no file named Calibration/HcalAlCaRecoProducers/python/alcaHBHEMuonFilter_cfi.py
> in the PR - it was removed. Also the file created is named AlcaHBHEMuonFilter_cfi.py and that is why the cff file was modified.

Ok, great: you already did it, and I did not notice at first...
Everything is fine, then. Thank you Sunanda

**Comment by perrotta** [comment]
+1

**Pull request merged**
