### PR TITLE
Run3-hcx380X Add the 2025 scenario after correcting for the DT Shield (backport of #46705 and #46784)

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Add the 2025 scenario after correcting for the DT Shield (backport of #46705 and #46784)

#### PR validation:

Use the runTheMatrix test workflows

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport of #46705 and #46784

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
+geometry

**Comment by bsunanda** [comment]
@subirsarkar Please approve this PR

**Comment by subirsarkar** [comment]
+Upgrade

**Comment by bsunanda** [comment]
@antoniovilela, @mandrenguyen, Please merge this PR

**Comment by bsunanda** [comment]
type backport

**Comment by smuzaffar** [comment]
ping bot: bot should auto signe d`operations` here on `tests-approved` as the PR touches non-operations code too

**Comment by smuzaffar** [comment]
backport of https://github.com/cms-sw/cmssw/pull/46705

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
