### PR TITLE
[14_0_X] HCAL DQM Online Histogram for Bad Quality Events

### PR DESCRIPTION
**Pull request by denizsun**
Bad Quality Events histogram and BadCapID rotation histogram
#### PR description: 
  - This is a backport PR from #45571.

### CODE REVIEW

**Comment by nothingface0** [comment]
@denizsun Maybe a more appropriate title for the PR would be `[14_0_X] HCAL DQM Online Histogram for Bad Quality Events`, for consistency with the main PR.

**Comment by tjavaid** [comment]
please test

**Comment by denizsun** [comment]
> @denizsun Maybe a more appropriate title for the PR would be `[14_0_X] HCAL DQM Online Histogram for Bad Quality Events`, for consistency with the main PR.

@nothingface0 thanks for the suggestion title! done.

**Comment by tjavaid** [comment]
+1

- spurious differences seen from unstable WF `12834.7` (open issue #39803 )

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
