### PR TITLE
Run2-sim06 Add an example to produce geometry summary for a given configuration

### PR DESCRIPTION
**Pull request by bsunanda**

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
@bsunanda , sorry, I postpone this PR to time when will be in the office and want to run the test with different use-cases. I would guess it is not urgent to integrate it in pre3.

**Comment by bsunanda** [comment]
@cmsbuild  Please test

**Comment by civanch** [comment]
+1
@bsunanda, this PR is working fine, may be you should not change g4Overlap script, instead we should duplicate  for several sub-detectors but we will do this in new PRs

**Pull request merged**
