### PR TITLE
New package FWCore/ROOTTests for testing functionality in ROOT

### PR DESCRIPTION
**Pull request by Dr15Jones**
Added unit tests to test basic behaviors of ROOT CMS depends upon.
The initial tests all stress test various parts of ROOT using
multiple threads.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
The code contains ROOT6 specific calls

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
Did the tests get stuck?

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
@davidlange6 @ktf ping

**Comment by ktf** [comment]
@degano can you please add the package and merge this?

**Pull request merged**
