### PR TITLE
HGC EM + Hadronic Merged Clustering

### PR DESCRIPTION
**Pull request by lgray**
HGC EM + Hadronic merged clustering using the calibrations derived for old (factorized) EM and Hadronic clusterings. Corresponding updates within PFAlgo, some improvements still to be made, small poorly calibrated cluster fragments are produced too often and correspond to overproduction of PFPhotons. There are also still some issues of linking HGC clusters to tracks that cause double counting in PF.

Working on these issues presently. This PR can be used in production to generate reasonable baselines.

@pfs @vandreev11

### CODE REVIEW

**Comment by pfs** [comment]
@lgray wrt to what we discussed Friday's meeting is there any extra feature you would like tested until tomorrow?

**Comment by lgray** [comment]
@pfs There is some minor improvement (reduction) in fragment production that came from the track-based super-clustering. 

I am working on the issues of fragment production in the EM-like clusters. It'll probably come tomorrow.

It would be useful to take another look at the calo-only charged pion response in the mean time.

**Comment by lgray** [comment]
@mark-grimes @fratnikov sorry for the noise, removing couts... this is a bit of a work in progress!

**Comment by lgray** [comment]
@mark-grimes @fratnikov found a timing problem in the code, I've fixed it and commit is coming in a moment.

**Comment by mark-grimes** [comment]
Okay.  There's still a lot of discussion about the HCal local reconstruction so the release requested over the weekend is unlikely to happen before the cross-POG meeting tomorrow.  Still, better to get it in and out of the way.

**Comment by mark-grimes** [comment]
@fratnikov, another update to this is coming if @lgray accepts a pull request onto his branch, which fixes the HGCal V6 customisation duplication discussed over email.

**Comment by fratnikov** [comment]
merge

**Pull request merged**
