### PR TITLE
Update RelVal scripts

### PR DESCRIPTION
**Pull request by hengne**
1.) update fullSim premixing samples
2.) update fastSim miniBias sample.
3.) back port PR #9046 : new feature to specify fastSim miniBias sample using one parameter for all fastSim PU workflows.
4.) change "Memory" parameter from 2400 to 3000

### CODE REVIEW

**Comment by franzoni** [comment]
please test

**Comment by boudoul** [comment]
+1

**Comment by boudoul** [comment]
looks like @cmsbuild ignored my +1  but it's early in the morning, so it should be sleeping :)

**Comment by hengne** [comment]
@boudoul LOL Thanks Gaelle ! ;-)

**Comment by davidlange6** [comment]
+1

**Pull request merged**
