### PR TITLE
Add enforceGUIDInFileName option to PoolSource and EmbeddedRootSource (10_2_X)

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

Quoting original PR

> This PR adds an option to `PoolSource` and `EmbeddedRootSource` to enforce that the file name (without extension) corresponds the GUID of the file. The added configuration parameter is `enforceGUIDInFileName = cms.untracked.bool`, and is set to `false` by default to preserve the current behavior. In case of a mismatch a new error code 8034 (`FileNameInconsistentWithGUID`) is returned.
> 
> The motivation for such an option comes from https://github.com/dmwm/WMCore/issues/9432.

#### PR validation:

Unit tests run.

#### if this PR is a backport please specify the original PR:

Backport of #28561.

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
The unit test fails already in the IB.

**Comment by Dr15Jones** [comment]
+1

**Comment by fabiocos** [comment]
The unit test is failing in the IB for independent reasons, not an issue

**Comment by Dr15Jones** [comment]
backport  #28561

**Comment by Dr15Jones** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Pull request merged**
