### PR TITLE
Make average Fed Occupancy a TProfile

### PR DESCRIPTION
**Pull request by fioriNTU**
Having the FED ocuupancy as TProfile is the easist way to merge histos in harvesting phase, plus I removed commented code

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
is there a correspondent PR for 75?
thanks,
F.

**Comment by fioriNTU** [comment]
Yep, the same changes are in #11488 , it was still Open so I didn't 
submit a new PR, I updated the existing one.

Ciao,
FF

Il 07/10/2015 13.43, Federico De Guio ha scritto:
>
> is there a correspondent PR for 75?
> thanks,
> F.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/cms-sw/cmssw/pull/11597#issuecomment-146165807>.
>



---
Questa e-mail è stata controllata per individuare virus con Avast antivirus.
https://www.avast.com/antivirus

**Comment by deguio** [comment]
I don't see them..
thanks,
F.

**Comment by fioriNTU** [comment]
Sorry Federico, my fault, the right PR is #11186.

Ciao,
FF

Il 07/10/2015 16.09, Federico De Guio ha scritto:
>
> I don't see them..
> thanks,
> F.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/cms-sw/cmssw/pull/11597#issuecomment-146205930>.
>



---
Questa e-mail è stata controllata per individuare virus con Avast antivirus.
https://www.avast.com/antivirus

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
