### PR TITLE
New json dump

### PR DESCRIPTION
**Pull request by PonIlya**
#### PR description:
The purpose of this PR is to improve the dump method.
Records and their consumption will be output to a JSON file rather than a log file or console due to the fact that they are usually too long for visual analysis.
This is more convenient for further use, for example, generating [сonsumption tables](https://twiki.cern.ch/twiki/bin/view/CMS/AlCaDBHLT2023) a log parsing script was previously used to fill it out

Previously, this issue was raised in the following [PR ](https://github.com/cms-sw/cmssw/pull/39901) but was not approved
#### PR validation:
The generated .json file should have the same contents as the previous version of dumpstat after running.

`cmsDriver.py TTbar_13TeV_TuneCUETP8M1_cfi  --conditions auto:phase1_2023_realistic_postBPix -n 5 --era Run3_2023 --geometry DB:Extended -s GEN --fileout output_step1_GEN.root --beamspot Realistic25ns13p6TeVEarly2023Collision  --customise_commands='process.GlobalTag.DumpStat =cms.untracked.bool(True)'|& tee output_step1_GEN.log`

Not a backport

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
-1
wrong release or rebase needed.

**Comment by iarspider** [comment]
This PR contains too many commits (347 > 200). Make sure you chose the right target branch.
@smuzaffar, @rappoccio, @makortel, @sextonkennedy, @Dr15Jones, @antoniovilela, you can override this check with `+commit-count`.

**Comment by iarspider** [comment]
This PR contains too many commits (347 > 200). Make sure you chose the right target branch.
@makortel, @rappoccio, @Dr15Jones, @sextonkennedy, @smuzaffar, @antoniovilela, you can override this check with `+commit-count`.

**Comment by makortel** [comment]
-core

**Comment by jfernan2** [comment]
-1
To clean the queue

**Pull request closed without merging**
