### PR TITLE
changing to esConsumes after fix in  #32217

### PR DESCRIPTION
**Pull request by jsalfeld**
#### PR description:

in #31962 it was pointed out to move to the esConsumes style. A problem was encountered, but fixed in #32217, now merged into 11.2.0_pre10.

This PR changes to esConsumes.

#### PR validation:

I checked the suggested implementation to produce the expected output.

### CODE REVIEW

**Comment by fwyzard** [comment]
please test

**Comment by Martin-Grunewald** [comment]
Workflow fails in IB as well, so likely unrelated to this PR.

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
