### PR TITLE
A few HLT integrations and bug fixes on top of CMSSW_7_4_0

### PR DESCRIPTION
**Pull request by perrotta**
Additional integrations and bug fixes on top of the HLT menus included in CMSSW_7_4_0. they include:
- (Bug fix) fix endpath to not reuse an HLTPrescaler instance already used elsewhere
- (Bug fix) fix bug in b-tagging PFlow sequence, CMSHLT-323
- (Bug fix) two small fixes to muon configuration, CMSHLT-319
- DisplacedMuJet + control paths, CMSHLT-310 (not dumped in the GRun menus yet)
- VBF+Mu SUSY path, CMSHLT-317
- VBF+Displaced paths for 1.4E34, CMSHLT-318 (not dumped in the GRun menus yet)

If, for any reason, we will need a patch release on top of "final" CMSSW-7_4_0, it wouldn't be bad to include also the fixes in this pull request within that patch. Otherwise, the commit in this PR can be merged anyhow in 75X for further developments.

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
Can not reproduce this error (the test is using the HLT fake menu which is unchanged)
Must be a glitch.

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
