### PR TITLE
Revert "Add possibility to cut on timing to IVF"

### PR DESCRIPTION
**Pull request by slava77**
Reverts cms-sw/cmssw#20640

until issues with application of the cut in a consistent way can be resolved.
Current situation is that e.g. D17Timing workflows are affected in the standard B-tag reco because the timing cut is applied there on track selection, while it should not be.

### CODE REVIEW

**Comment by slava77** [comment]
assign upgrade

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by kpedro88** [comment]
To me it doesn't seem necessary to revert this in 10_0_X unless a complete solution is not forthcoming in the next couple of weeks.

**Comment by slava77** [comment]
> To me it doesn't seem necessary to revert this in 10_0_X unless a complete solution is not forthcoming in the next couple of weeks.

The reasons for me:
- it is easier to confirm that the feature/fix works in master without having to go back to 93X
- it took 3 weeks to have the first update, which is apparently still incomplete; making a revert may be more encouraging to have a complete solution
- now I think that we need somewhat significantly different solution based on configuration instead of heuristics based on event content which apparently lead to the current problematic situation

**Comment by Martin-Grunewald** [comment]
-1
#20640 did not touch anything under HLTrigger. So why does this "revert" PR?

**Comment by kpedro88** [comment]
somehow it changes the permissions on some HLT files... weird.

**Comment by slava77** [comment]
>  #20640 did not touch anything under HLTrigger. So why does this "revert" PR?

strange indeed

**Comment by slava77** [comment]
@smuzaffar @davidlange6 
do you know
what could have caused the difference in this revert? Did the cmssw tree change somehow in a way that revert can not be applied anymore?

**Comment by fwyzard** [comment]
I think the changes to the files permissions are from #21325 - and I have no idea why the revert should affect them.

**Comment by fwyzard** [comment]
-1

**Comment by davidlange6** [comment]
I don't see why this is happening - though it is reproducible if I try to make the same revert request. 

We should probably establish one file permission for all cmssw files and enforce it centrally - seems that this is possible..

**Comment by slava77** [comment]
I will close this
- it looks like inconsistent behavior of workflows with timing doesn't bother upgrade
- the extra HLT change seems inappropriate

**Pull request closed without merging**
