### PR TITLE
HCALDQM: bad capid/LED misfire sound alarms only for last 60 LSes (master/10_4_X)

### PR DESCRIPTION
**Pull request by DryRun**
Adds "LSmod60" versions of the bad capid and LED misfire vs LS plots, which only record the last 60 LSes. This is so that the error condition goes away after ~25 minutes, so the sound alarms don't keep triggering.

### CODE REVIEW

**Comment by andrius-k** [comment]
please test

**Comment by andrius-k** [comment]
+1

**Comment by fabiocos** [comment]
@DryRun why the modification of the blocks with ptype == fOnline is not active? Isn't FOnline the default setting?

https://cmssdt.cern.ch/lxr/source/DQM/HcalCommon/interface/DQModule.h#0035
https://cmssdt.cern.ch/lxr/source/DQM/HcalTasks/python/DigiTask.py#0016

**Comment by fabiocos** [comment]
@DryRun ping

**Comment by DryRun** [comment]
Hi @fabiocos  - I might be misunderstanding the question, but these plots are intended only for online DQM. The DQM type (online/offline/local) is set in the corresponding configuration file.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
