### PR TITLE
migrate Alignment/LaserAlignment to esConsumes

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

Title says it all.
Part of #31061.

#### PR validation:

It compiles.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Not a backport, no backport needed.

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
> DQMHistoTests: Total failures: 64469

All failures are concentrated in a single wf: [11634.911](https://tinyurl.com/y9agmku9), clearly nothing to do with the PR.

**Comment by yuanchao** [comment]
+1
* regardless the comparison failure on WF 11634.911, all matrix tests and unit tests passed
* static build warnings are not part of the PR

**Comment by qliphy** [comment]
+1

**Pull request merged**
