### PR TITLE
bsunanda:Run2-alca59 Backport pull request from 8_1_X for AlCaReco stream with muons in HB/HE

### PR DESCRIPTION
**Pull request by bsunanda**
Useful to test calibration using MIPs in HB/HE. Back-ported from CMSSW_8_1_X

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@mmusich @franzoni  Please approve this PR

**Comment by bsunanda** [comment]
@mmusich @franzoni Could you approve the back porting PR?

**Comment by mmusich** [comment]
@bsunanda there are some changes that might be missing in the backport.
In your PR #15226 you have the following changes:
`Calibration/HcalAlCaRecoProducerscers/python/alcastreamHcalHBHEMuon_cff.py`
-->
`Calibration/HcalAlCaRecoProducersers/python/ALCARECOHcalCalHBHEMuon_cff.py` 

and then you rename:
`ALCARECOHcalHBHEMuon_Output_cff.py` 
to:
`ALCARECOHcalCalHBHEMuon_Output_cff.py` 
 
applying as well changes, but I don't see any of these changes in 80x backport. 
Is this on purpose?
Thanks,

M.

**Comment by bsunanda** [comment]
@mmusich I am taking care of these 2 files now. Shall commit them shortly

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by mmusich** [comment]
@bsunanda 

https://github.com/bsunanda/cmssw/blob/f341031bf0a364b07bddaabaf911445aa96f6b56/Calibration/HcalAlCaRecoProducers/python/ALCARECOHcalCalHBHEMuon_Output_cff.py

still looks different from:

https://github.com/cms-sw/cmssw/blob/CMSSW_8_1_X/Calibration/HcalAlCaRecoProducers/python/ALCARECOHcalCalHBHEMuon_Output_cff.py

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by mmusich** [comment]
please test

**Pull request merged**
