### PR TITLE
Replace patterns with explicit class names in `TrackingTools/PatternTools/src/classes_def.xml`, and move the dictionaries of `GlobalErrorBase` to a proper package

### LINKED ISSUE #980: Replace patterns with explicit class names in `TrackingTools/PatternTools/src/classes_def.xml`, and move the dictionaries of `GlobalErrorBase` to a proper package

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

This PR is part of series to replace the last remaining uses class pattern elements in `classes_def.xml` with explicit class names. In addition, it removes (now-)unnecessary code from `classes.h`, adds `persistent="false"` to all `edm::Wrapper<T>` instantiations and removes it from other classes, and finally moves `GlobalErrorBase` (and `Point3DBase`) related dictionaries to `DataFormats/GeometryCommonDetAlgo` that seemed like the right place (it seems to me these dictionaries were defined in `TrackingTools/PatternTools` because of `typedef std::pair<GlobalPoint, GlobalError> VertexConstraint` type alias used there; I also hope the "ROOT6 problem" mentioned in the comment has been solved already).

Resolves https://github.com/cms-sw/framework-team/issues/980

#### PR validation:

Code compiles. The pattern-to-name change kept all existing definitions in the `.rootmap` file, and added a few more with that use the type aliases I used in the `name` attribute.

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
type -changes-dataformats

**Comment by makortel** [comment]
The failure in 4.78 is a file open error. Comparison differences are related to https://github.com/cms-sw/cmssw/issues/39803

**Comment by civanch** [comment]
please test

there are PRs today, which pass tests.

**Comment by civanch** [comment]
+1

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
