### PR TITLE
Clean up CondTools/DQM configurations and add unit tests

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

There is renewed interest in using the `DQMXMLFileRcd` in Database to store Pixel / Strip / Tracking DQM QTests configurations. I therefore refresh the configuration files in that package and also provide unit tests to allow reading / writing of  `DQMXMLFileRcd` to be exercised in IB tests.

#### PR validation:

Relies on the unit tests introduced in this PR which run to completion.
 
#### if this PR is a backport please specify the original PR and why you need to backport that PR:

This PR is not a backport and no backport is needed.

cc:
@sroychow @arossi83 @gbenelli

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by jfernan2** [comment]
+1

**Comment by ggovi** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
