### PR TITLE
Strip payload inspector: add class to retrieve list of dead modules from JSON

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

The main goal of this PR is to add a new class to the Strip Payload inspector, to retrieve the list of dead modules in JSON format from the `SiStripDetVOff` DB record.
In order to achieve that, as double precision is needed in order to store the module `DetIds` as `float`s, a new  class `Histogram1` inheriting from `Plot2D` has been added. The existing class `Histogram1D` is now made to derive from `Histogram1` along with `Histogram1DD` which addressed the issue above, via class templates.
I profit of this PR to add protections to `Histogram1` and `Histogram2D` in order to yield framework warnings in case the provided binning does not make sense, and also few miscellaneous graphical adjustments to some of the existing plots. 

#### PR validation:

Relies on existing unit tests.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Not a backport, no backport needed.

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by silviodonato** [comment]
kind reminder @ggovi

**Comment by ggovi** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
