### PR TITLE
Replace mark-and-delete at next merge algorithm in DQMStore (74x)

### PR DESCRIPTION
**Pull request by dmitrijus**
Additionally, the DQMStore will now acquire locks for writing files.

This PR also add a new file saver for HLT->PB (DQMFileSaverPB).
Which should replace DQMFileSaver in the near future.

(discussion: https://github.com/cms-sw/cmssw/pull/11086)

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by fwyzard** [comment]
as a minimal fix for CMSSW 7.4.x, wouldn't it have been simpler to just make sure that the histograms marked for deletion are actually deleted, in the `postGlobalEndLumi` callback ?

**Comment by dmitrijus** [comment]
This PR was actually introduced a  few weeks ago
with an idea to make this deletion simpler and to solve performance
issues reported by Srecko.

The *memleak* was causes by:
https://github.com/cms-sw/cmssw/blob/CMSSW_7_6_X/DQMServices/Core/src/DQMStore.cc#L486
'temp' should be checked, not 'i_lumi'.
This PR is removes that bit of the code and unintentionally fixes the memleak.

Dmitrijus

**Comment by deguio** [comment]
I discussed with andrea. let's wait to see the outcome of the test on the hilton then we can decide to merge it.
all the use cases should be supported (HLT, Online at p5). offline should be untouched.
let's keep open for now

**Comment by Sam-Harper** [comment]
So I ran the hilton tests on it and I still see what appears to be the same memory increase. I'm now going to double check I ran what I thought I ran. But just wanted to give you an update

**Comment by deguio** [comment]
thanks @Sam-Harper,
this is too bad. please let us know if this is confirmed.
thanks,
F.

**Comment by deguio** [comment]
+1
this one can go in at this point. it would be nice to have it included in the next 74x build.

**Comment by fwyzard** [comment]
ciao @deguio, after the comments from @Sam-Harper do we have any indications that this actually fixes the memory problem ?

**Comment by deguio** [comment]
ciao andrea,
this fixes one problem (inside DQM). the memory leak seen by sam is a root problem fixed by lorenzo already. see:
https://hypernews.cern.ch/HyperNews/CMS/get/edmFramework/3569/1.html

going to reply now asking to have the root we use patched with the fix.

**Pull request merged**
