### PR TITLE
[10.2.X] Cleanup CondCore/SiStripPlugins  y moving the plugin in plugins directory

### PR DESCRIPTION
**Pull request by smuzaffar**
CondCore/SiStripPlugins only generates edm plugins and its src & interface directories only contain one file. This PR moves the plugin.cc file in plugins sub directory.

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by fabiocos** [comment]
@ggovi ping

**Comment by ggovi** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
