### PR TITLE
Phase2-gex100 Make D86 version with the new muonYoke file and to make a new scenario 2026D88 with the new MTD version

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Make D86 version with the new muonYoke file and to make a new scenario 2026D88 with the new MTD version

#### PR validation:

Use the runTheMatrix test workflows 38634.0 and 39434.0

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@fabiocos @slomeo The new PR is made using the new MuonYoke and MTD components

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by srimanob** [comment]
Change is expected, only D86 shows the difference. Note that I will retrigger the test, as D88 is not in the short matrix. We should test if new workflow runs smoothly.

**Comment by srimanob** [comment]
test parameter:
- workflow = 39434.0

**Comment by srimanob** [comment]
@cmsbuild please test

**Comment by bbilin** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

The new geometry runs fine.

**Comment by fabiocos** [comment]
@bsunanda thanks

**Comment by cvuosalo** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
