### PR TITLE
Manage PluginFactory plugins with unique_ptr in RecoMuon

### PR DESCRIPTION
**Pull request by makortel**
This PR is preparatory work to change the PluginFactory to return a `std::unique_ptr`.

In addition I removed an unnecessary `ParameterSet` member from `MuIsoDepositProducer`, and did more thorough migration from raw pointers to `unique_ptr` and cleanup in `RecoMuon/TrackerSeedGenerator`.

Tested in CMSSW_10_5_X_2019-02-05-1100 , no changes expected.

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by perrotta** [comment]
+1
- The update is technical, and corresponds to what declared in the PR description
- Jenkins tests pass

**Comment by fabiocos** [comment]
+1

**Pull request merged**
