### PR TITLE
Additional Photos options (7_1_X)

### PR DESCRIPTION
**Pull request by mseidel42**
#### PR description:

Backport of #26853

Needs https://github.com/cms-sw/cmsdist/pull/4997

### CODE REVIEW

**Comment by efeyazgan** [comment]
please test

**Comment by alberto-sanchez** [comment]
you shuld use:

please test with cms-sw/cmsdist#4997

**Comment by alberto-sanchez** [comment]
please test with cms-sw/cmsdist#4997

**Comment by intrepid42** [comment]
Backported Photospp and EvtGen interface updates

**Comment by alberto-sanchez** [comment]
please test with cms-sw/cmsdist#4997

**Comment by alberto-sanchez** [comment]
please abort

**Comment by alberto-sanchez** [comment]
please test with cms-sw/cmsdist#4997

**Comment by mrodozov** [comment]
please test with cms-sw/cmsdist#4997

**Comment by mrodozov** [comment]
something went wrong let me retry it

**Comment by mrodozov** [comment]
please test cms-sw/cmsdist#4997
lets try one last time and then I'll have a look

**Comment by intrepid42** [comment]
It looked like a github issue?

https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-2879bb/456/git-merge-result:
```
+ git cms-merge-topic -u cms-sw:26886
Attention: git is unable to access GitHub over https, switching to ssh.
Cloning into '/build/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_7_1_X_2019-05-21-1100/src'...
Switched to a new branch 'from-CMSSW_7_1_X_2019-05-21-1100'
From .
 * [new ref]                    -> merge-attempt
fatal: unable to access 'https://github.com/cms-sw/cmssw.git/': error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
fatal: unable to access 'https://github.com/cms-sw/cmssw.git/': error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
```

**Comment by mrodozov** [comment]
please test with cms-sw/cmsdist#4997

**Comment by efeyazgan** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
