### PR TITLE
bsunanda:Phase2-hgx51 Validation of Geometry of HGCal by comparing SIM and Digi/RECO level information

### PR DESCRIPTION
**Pull request by bsunanda**
These codes can be used with private production because it simultaneously looks in PCaloHit, Digi, RecHits

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@deguio Could you check this and do the needful?

**Comment by kpedro88** [comment]
@deguio ping

**Comment by deguio** [comment]
ciao @bsunanda 
are this classes expected to be run in prod eventually? if yes they should be moved to be DQMEDAnalyzers so that they make use of the DQMStore as the others.

cheers,
F.

@dmitrijus

**Comment by bsunanda** [comment]
@deguo @dmitrijus I do not think they will be run for standard relvals. They are needed for special validation jobs
________________________________

**Comment by dmitrijus** [comment]
If there aren't intended to run  in standard sequences - please put them to 'test' or 'test/plugins' folder. It is very hard to track what is running as it is.

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@dmitrijus @vanbesien @deguio Moved the relevant files to test directory. Please sign them now

**Comment by dmitrijus** [comment]
Python config include files should go to the same directory (just test or test/python).

**Comment by bsunanda** [comment]
If I move the cfi files in test area - I cannot reuse them in a cfg. Do you want this to happen?
________________________________

**Comment by bsunanda** [comment]
@deguio @dmitrijus @davidlange6 Please let me know what is to be done to the cfi files. They cannot be used as cfi files if kept in test area

**Comment by dmitrijus** [comment]
Hi, you can reuse them - as long as they are under python/test directory.
such as: process.load("DQM.Integration.test.xxx_cfi").

So, they should go into "python/test", not "test/python" as I previously suggested.

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@deguio @dmitrijus @davidlange6 Moved the cfi files as well

**Comment by bsunanda** [comment]
@deguio @dmitrijus Please approve this now

**Comment by bsunanda** [comment]
@deguio @dmitrijus @davidlange6 Could you approve this

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
