### PR TITLE
 add track hit eff monitoring vs inst. lumi

### PR DESCRIPTION
**Pull request by mtosi**
this PR is meant to add the missing monitoring of the hit efficiency vs inst luminosity
the inst luminosity used is an estimate from the pixel cluster

### CODE REVIEW

**Comment by dmitrijus** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by dmitrijus** [comment]
+1

**Comment by mtosi** [comment]
lumiScalers.isValid() was not enough to avoid missing / not valid input collection
I've just added the check on the size of the lumiScalers collection
I ran runTheMatrix and it seems to be fine, now

**Comment by dmitrijus** [comment]
please test

**Comment by mtosi** [comment]
did it work the rebase ?
I did 
git rebase -i CMSSW_8_1_X
(edited the git file)
git push my-cmssw +HEAD:addHitEffVsLUMI

**Comment by mtosi** [comment]
ok, please "carpe diem"

**Comment by mtosi** [comment]
could we merge this PR, please ?
@cmsbuild @rovere @VinInn @dmitrijus @vanbesien

**Comment by VinInn** [comment]
@cmsbuild , please test

**Comment by mtosi** [comment]
@cmsbuild 
I do not think this error is related to the PR

**Comment by dmitrijus** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
