### PR TITLE
Adding option to disable resetting L1 PS counters on ls change [`12_3_X`]

### PR DESCRIPTION
**Pull request by missirol**
backport of #37395

#### PR description:

Backport of #37395. This PR is needed by TSG for HLT-rate studies in `12_3_X`. It simply adds an option to a producer without changing its defaults.

Description of the original PR by @Sam-Harper (cc: @silviodonato @Martin-Grunewald):
>This PR adds an option to disable resetting the prescale counters of the L1 trigger on lumi section change. This is needed for offline L1 reemulations where we only have ~23000 events per lumisection available (often much much less due to multithreading/job splitting) and this reset comes too soon and causes triggers to have a much higher effective prescale or not fire at all. This is based on the excellent debugging and investigations by @sanuvarghese
>
>Also could experts just confirm why the L1 resets counters every lumisection? I'm just curious to why.
>
>Finally as spotted by both Sanu and myself, we note that this code can not work with fractional prescales. What is the plan here?

#### PR validation:

Relies on the validation done for the original PR.

#### If this PR is a backport, please specify the original PR and why you need to backport that PR:

#37395

Purpose: HLT development in `12_3_X`.

### CODE REVIEW

**Comment by missirol** [comment]
urgent

Targeting `12_3_0`, to support HLT studies.

**Comment by missirol** [comment]
please test

**Comment by epalencia** [comment]
+l1

**Comment by perrotta** [comment]
+1
- Verbatim backport of #37395

**Pull request merged**
