### PR TITLE
fix obsolete raise usage

### PR DESCRIPTION
**Pull request by davidlange6**
Syntax like
```
raise 'hi there', variable
```

has been incorrect since we changed to python 2.6 (many years ago). This error is now flagged by compiling with python3. Fixing the errors we have in cmssw.

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by alberto-sanchez** [comment]
+1

**Comment by ggovi** [comment]
+1

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/24124	f6a01f7
- technical
- jenkins tests pass

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Pull request merged**
