### PR TITLE
DD4Hep: DT Geometry Builder with Correct Numbering

### PR DESCRIPTION
**Pull request by ianna**
* Implement correct Muon numbering based on SpecPars
* This PR has addressed some of the issues mentioned here https://github.com/cms-sw/cmssw/issues/25868

dt chamber 1
dt chamber 2
dt chamber 3
dt chamber 4
dt chamber 5
dt layer 1
dt layer 2
dt layer 3
dt layer 4
dt layer 5

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Pull request merged**
