### PR TITLE
Run3-gex87 Modify material budget code relevant to study XML vs DB

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Modify material budget code relevant to study XML vs DB

#### PR validation:

Tested using cfg's in the test area of Validation/Geometry

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by jfernan2** [comment]
+1

**Comment by cvuosalo** [comment]
+1

**Comment by perrotta** [comment]
+1
- It modifies macros and test scripts not run in workflows but relevant for the comparison of the geometry stored in XML files and in the DB

**Pull request merged**
