### PR TITLE
Add python3 compatible print management in Validation/HGCalValidation

### PR DESCRIPTION
**Pull request by fabiocos**
#### PR description:

Minor fix on top of #26099 for a problem in python3 compatibility (print statement syntax).

#### PR validation:

```CMD_python=$(which python3) scram b -r -v -k -j 8 CompilePython``` does not show any more errors

### CODE REVIEW

**Comment by andrius-k** [comment]
please test

**Comment by fabiocos** [comment]
@andrius-k I would like to have this fixed by this evening

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Comment by andrius-k** [comment]
+1
Signing for future reference.

**Pull request merged**
