### PR TITLE
HipPy alignment algorithm improvements

### PR DESCRIPTION
**Pull request by hroskes**
Backport of #23301

Collected improvements from @usarica over the last year:

- Resurrecting some old code (`getByLabel` --> `getByToken`, etc.) in RecoTracker/TrackProducer to fit track with vertex constraints
- Add the option to use these constraints in HipPy alignment
- More monitoring variables saved by HipPy
- interface stuff, like proxy forwarding

(Note the branch name is pretty old, but we've been `merge-topic`ing this for a while and using it for alignment without any problems.)

### CODE REVIEW

**Comment by arunhep** [comment]
comments from master version of this PR will be applicable here as well : https://github.com/cms-sw/cmssw/pull/23301#pullrequestreview-124294136

**Comment by arunhep** [comment]
please test

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
+1
- Identical commit-wise and code-wise to #23301 in the master
- This is the code which is currently running for the HipPy alignment
- Bug fixes integrated here do not affect regular CMSSW workflows: no effect on jenkins outputs, as expected

**Comment by lpernie** [comment]
+1

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
+1

**Pull request merged**
