### PR TITLE
make a fresh PR for bsunanda:Run2-hcx41 (11767 for 7_6_X) HcalTopology depends only on HcalDDDRecContants

### PR DESCRIPTION
**Pull request by smuzaffar**

### CODE REVIEW

**Comment by smuzaffar** [comment]
@bsunanda, if this looks good then we can close #12143

**Comment by diguida** [comment]
please test
@smuzaffar this looks ok to me.

**Comment by diguida** [comment]
https://github.com/cms-sw/cmssw/compare/cms-sw:CMSSW_8_0_X...bsunanda:Run2-hcx46 and https://github.com/cms-sw/cmssw/compare/cms-sw:CMSSW_8_0_X...smuzaffar:bsunanda-Run2-hcx46 show the same diffs:
````
27 changed files with 37 additions and 298 deletions.
````
https://github.com/cms-sw/cmssw/compare/bsunanda:Run2-hcx46...smuzaffar:bsunanda-Run2-hcx46 is not the same because of different starting parent commits.

**Comment by civanch** [comment]
+1

**Comment by bsunanda** [comment]
@davidlange6 Please try to accept this PR
________________________________

**Comment by mulhearn** [comment]
+1

**Comment by mmusich** [comment]
+1

**Comment by Martin-Grunewald** [comment]
+1

So this replaces #11920 ?

**Comment by bsunanda** [comment]
@Martin-Grunewald  Yes it does

**Comment by Martin-Grunewald** [comment]
@bsunanda 
Can you then please close the (two...) old PRs now obsolete?

**Comment by Martin-Grunewald** [comment]
ie,  #12143  #11920

**Comment by davidlange6** [comment]
+1

**Pull request merged**
