### PR TITLE
Clean up hippy

### LINKED ISSUE #20380: Avoid generic executable names in cmssw e.g. configure
Installing pycrypto using pip in PYTHONUSERBASE failed if cmssw env is set [b]. It turned out of one has ```configure``` executable in PATH then setup.py runs our configure instead of one from pycrypto [a]

We have Alignment/HIPAlignmentAlgorithm/scripts/configure which is copied to cmssw/bin/arch directory. Is this script needed (and should it be in PATH)? Is yes then can we rename it?

[a]
https://groups.google.com/forum/#!msg/sage-devel/pcBPs9aRH6w/JNeQYd8Z7RkJ

[b]
```
    configure: error: cannot find sources (src/pycrypto_compat.h) in /build/muz/y/CMSSW_9_3_0_pre4/bin/slc6_amd64_gcc630 or ..
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-7JlViJ-build/setup.py", line 456, in <module>
        core.setup(**kw)
      File "/cvmfs/cms.cern.ch/slc6_amd64_gcc630/external/python/2.7.11-mlhled2/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/cvmfs/cms.cern.ch/slc6_amd64_gcc630/external/python/2.7.11-mlhled2/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/cvmfs/cms.cern.ch/slc6_amd64_gcc630/external/python/2.7.11-mlhled2/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/cvmfs/cms.cern.ch/slc6_amd64_gcc630/external/py2-pippkgs/5.0-ghjeda4/lib/python2.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/cvmfs/cms.cern.ch/slc6_amd64_gcc630/external/python/2.7.11-mlhled2/lib/python2.7/distutils/command/install.py", line 563, in run
        self.run_command('build')
      File "/cvmfs/cms.cern.ch/slc6_amd64_gcc630/external/python/2.7.11-mlhled2/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/cvmfs/cms.cern.ch/slc6_amd64_gcc630/external/python/2.7.11-mlhled2/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/cvmfs/cms.cern.ch/slc6_amd64_gcc630/external/python/2.7.11-mlhled2/lib/python2.7/distutils/command/build.py", line 127, in run
        self.run_command(cmd_name)
      File "/cvmfs/cms.cern.ch/slc6_amd64_gcc630/external/python/2.7.11-mlhled2/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/cvmfs/cms.cern.ch/slc6_amd64_gcc630/external/python/2.7.11-mlhled2/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/tmp/pip-7JlViJ-build/setup.py", line 251, in run
        self.run_command(cmd_name)
      File "/cvmfs/cms.cern.ch/slc6_amd64_gcc630/external/python/2.7.11-mlhled2/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/cvmfs/cms.cern.ch/slc6_amd64_gcc630/external/python/2.7.11-mlhled2/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/tmp/pip-7JlViJ-build/setup.py", line 278, in run
        raise RuntimeError("autoconf error")
    RuntimeError: autoconf error
error
Cleaning up...
  Removing source in /tmp/pip-7JlViJ-build
Command "/cvmfs/cms.cern.ch/slc6_amd64_gcc630/cms/cmssw/CMSSW_9_3_0_pre4/external/slc6_amd64_gcc630/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-7JlViJ-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-5QfwqG-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-7JlViJ-build/
Exception information:
Traceback (most recent call last):
```

### PR DESCRIPTION
**Pull request by hroskes**
@usarica, @ghellwig, @smuzaffar 

delete some old scripts, to fix #20380.  They were moved to a newer version, using `iterator_py` and friends, a long long time ago.

The remaining files in Alignment/HIPAlignmentAlgorithm/scripts that haven't been modified since "Snapshot of CMSSW_6_2_0_pre8" are:

- `checkError.sh`: still works
- `compareGeomSerial_tpl.C`, `serialGeomCompare.pl` - I doubt these work anymore, but if fixed they would be potentially useful.  Since they're not hurting anyone I didn't delete them.
- `runControl.csh`: still needed

### CODE REVIEW

**Comment by hroskes** [comment]
@smuzaffar do we need any backports?

**Comment by smuzaffar** [comment]
please test
thanks @hroskes for quick fix. Changes in master/93x is enough for now.

**Comment by ghellwig** [comment]
@hroskes as already pointed out to @usarica some time ago, I would in general recommend to rename hippy specific scripts that are in PATH like this: SCRIPT_NAME -> hippy_SCRIPT_NAME

**Comment by usarica** [comment]
@ghellwig We will do this in another PR, not this one. This will potentially create mrege conflicts with a parallel development. All scripts are pretty unique in their name anyway (e.g. submitJobs_py), so the names are unlikely to cause harm, as they haven't done until now.
@hroskes Please refrain from changing files that are already modified as part of alignment campaigns.

**Comment by smuzaffar** [comment]
@davidlange6 , can we get this in 93X? This is just the removal of unused scripts with generic names e.g. `configure`

**Comment by davidlange6** [comment]
merge

**Pull request merged**
