### PR TITLE
HBHE isolated noise reflagger retuning for Run2 - 74X

### PR DESCRIPTION
**Pull request by dertexaner**
This a PR to 74X as per Maria D'alfonso's request for special JetMET validation.
The changes are the same as in https://github.com/cms-sw/cmssw/pull/11726

### CODE REVIEW

**Comment by slava77** [comment]
@dertexaner 
There is no plan so far to change the physics performance in 74X.
If you need to deliver changes to the configuration parameters for tests or some (re)processing requests, please make a customization function which can be called to implement needed changes at the level of the cmsDriver.py call.

**Comment by mariadalfonso** [comment]
@slava77
The idea was to include this modification is some large stat re-reco (1 fb of a couple of datasets)  for validation purposes together with the other PR mentioned as mentioned in
https://indico.cern.ch/event/452395/contribution/2/attachments/1166408/1681999/dalfonso_PPD_7Oct.pdf

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for 
- changes are in line with the description of the PR; the (config) code changes are the same as in #11726  (76X version)
- jenkins tests pass and comparisons with the baseline show differences only in isolated noise variables (used for tagging); no other monitored physics objects are changed
this is a plot from wflow 1003.0 
wf1003_isonoise

@davidlange6 
I suppose, similar to a set of other HCAL/noise-related PRs, this one also goes in limbo until a limited reprocessing release is to be made.

**Comment by slava77** [comment]
@davidlange6 
I think that this PR can be closed
Even if we do something with 2015, it will be 76X.

**Pull request closed without merging**
