### PR TITLE
Add TenTau workflow (92X)

### PR DESCRIPTION
**Pull request by fabozzi**
Adding new TenTau workflow in the upgrade set.
This relval is needed for HLT main validation campaigns (last ones performed in 9_2_8 and 9_2_9)

### CODE REVIEW

**Comment by fabozzi** [comment]
Backport of #20290

**Comment by fabozzi** [comment]
please test workflow 10087

**Comment by fabozzi** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
