### PR TITLE
CPPF DQM modules backport to 12_4_X

### PR DESCRIPTION
**Pull request by zhangcg123**
#### PR description:

Add CPPF online DQM modules L1TdeStage2CPPF and L1TStage2CPPF. 
By comparing the CPPF emulator and unpacker outputs and putting some comparison histograms on the CMS online DQM GUI, shifters can monitor the status of the CPPF hardware.

#### PR validation:

cmsRun DQM/Integration/python/clients/l1tstage2emulator_dqm_sourceclient-live_cfg.py unitTest=True

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport of #38564 and #39307. For CPPF online DQM

### CODE REVIEW

**Comment by clacaputo** [comment]
Please test

**Comment by mmusich** [comment]
For my own education what use case is this PR actually targeting? As far as I am aware data-taking in 12.4.X is over and the release for 2022 re-reco is already frozen, so there seems to be no practical use case for this backport.

**Comment by zhangcg123** [comment]
Hi @mmusich , 
Thanks for your information. 
If the p5 dqm sw will switch to 12.5.X soon, this pr does not make sence. 
I don't know about this thing. So, If an expert can confirm this, we can close this PR.
Sorry for that if I introduce some noise.

**Comment by perrotta** [comment]
As discussed and agreed with DQM and all other groups present at the ORP meeting on Dec 13, we can now close this PR (which will never be merged in the offline release anyhow) and clean up a bit our queues

**Pull request closed without merging**
