### PR TITLE
Fix HLTL1TSeed accounting for prescale handling (80X)

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
Do not consider HLTL1TSeed modules using the emulator (which ignores prescales) for L1T prescales determination.

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
