### PR TITLE
Preferred syntax of except changed in python 2.6

### PR DESCRIPTION
**Pull request by ericvaandering**
See https://www.python.org/dev/peps/pep-3110/#compatibility

```
except as foo:
```

is preferred since python 2.6

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by Dr15Jones** [comment]
@ericvaandering Just to clarify for others, this was done using an automated tool

**Comment by ericvaandering** [comment]
Yes! with "futurize" which is part of the python future package. http://python-future.org

**Comment by ericvaandering** [comment]
So can someone help me understand your testing setup? If I read this correctly, there are something like 20 commits that were tested in a block so the errors could arise from any of them? This commit should be completely safe, of course. And in the summary link given I could not easily locate what cmsbuild thought the error was.

**Comment by davidlt** [comment]
IIRC, it checkout everything else approved for the next IB together with your changes. Simply put, it should be testing on tip of release branch not directly on plain IB.

**Comment by davidlt** [comment]
These failures are not related to your changes, the same ones are in IBs. Might be gone once duplicate dictionaries are resolved.

**Comment by ericvaandering** [comment]
Or presumably if I test against a new IB, it won't be flagged? In other words I assume the test is against the latest IB and if errors are present in both it is not "attributed" to my PR?

**Comment by davidlt** [comment]
(1) Depends if new IB is healthy or not, currently tests are breaking in the IBs and people are working on the fix. No ETA (waiting for approval from package maintainer).
(2) Correct. Those errors are visible on CMSSDT showIB page. Your changes do no introduce any new failures as far as I can see.

**Comment by slava77** [comment]
@cmsbuild please test
to get a clean comparison (CMSSW_8_0_X_2015-10-19-2300 has the parent of this PR already)

**Comment by davidlange6** [comment]
@ericvaandering - these unit tests indeed all fail in a recent IB
(and we should make it easier to dig out the part of the log with the actual failures - I matched up the IB with the errors mentioned above from this: https://cmssdt.cern.ch/SDT/cgi-bin/showBuildLogs.py/slc6_amd64_gcc493/www/tue/8.0-tue-23/CMSSW_8_0_X_2015-10-20-2300)

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/11964	05ffbc4
- technical change, applied as described
- jenkins tests pass (ignoring the unit tests failing in IBs) and comparisons with the baseline show no differences

**Comment by ericvaandering** [comment]
This and #12019 conflict with an earlier patch. I will prepare a new PR with both of these together. I should have made a PR with all three related exception patches.

**Pull request closed without merging**
