### PR TITLE
Pr muon calo dev recipe feb2 80x

### PR DESCRIPTION
**Pull request by mulhearn**
Brings the calo and muon emulators fully up-to-date with the "dev-recipe" branch used for TSG studies, as of Feb 5 2016 (commit 46dadea7ae07332cc43af928bd207338e29f776e).

This PR should get smaller when PR #13068 is merged.

### CODE REVIEW

**Comment by mulhearn** [comment]
please test

**Comment by mulhearn** [comment]
please test

**Comment by mulhearn** [comment]
please test

**Comment by mulhearn** [comment]
Passes the limited relVals in my local test.  This might be an earlier night than I thought!

**Comment by mulhearn** [comment]
+1

**Comment by davidlange6** [comment]
not clear on the changes to EventFilter/L1TRawToDigi/python/caloStage1Raw_cfi.py - but lets fix them elsewhere (there is no effect on the relval tests)

**Pull request merged**
