### PR TITLE
Add the possibility to run multiple matrices in runTheMatrix.py

### PR DESCRIPTION
**Pull request by silviodonato**
#### PR description:

This PR makes possible to use multiple matrices in runTheMatrix.py using `--what`

#### PR validation:

Tested with
```
runTheMatrix.py --showMatrix -l 101.0,10224.0,10824.506,10842.506,11634.506,11650.506,1306.0,250202.181,25202.0,9.0 --what=standard,premix,gpu,pileup,highstat,2017
```

### CODE REVIEW

**Comment by silviodonato** [comment]
please test

**Comment by srimanob** [comment]
@silviodonato 
Is this mean we need to make sure that number is unique across runTheMatrix? I think it is currently, but we have no rule (and check) for number across "what" AFAIK.

**Comment by kpedro88** [comment]
@silviodonato can you update the help message for runTheMatrix.py to describe this new feature?
https://github.com/cms-sw/cmssw/blob/bb3c40442c81076c647f4118fd73c7727668a137/Configuration/PyReleaseValidation/scripts/runTheMatrix.py#L177

**Comment by silviodonato** [comment]
> @silviodonato
> Is this mean we need to make sure that number is unique across runTheMatrix? I think it is currently, but we have no rule (and check) for number across "what" AFAIK.

Currently it gives a warning like
```
==> duplicate name found for  36234.0_TTbar_14TeV+2026D80+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14+DigiTrigger+RecoGlobal+HARVESTGlobal
    keeping  :  (36234.0, 'TTbar_14TeV+2026D80+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14+DigiTrigger+RecoGlobal+HARVESTGlobal', ['cmsDriver.py TTbar_14TeV_TuneCP5_cfi  --conditions auto:phase2_realistic_T25 -n 10 --era Phase2C11I13T25M9 --eventcontent FEVTDEBUG --relval 9000,100 -s GEN,SIM --datatier GEN-SIM --beamspot HLLHC14TeV --geometry Extended2026D80', 'cmsDriver.py step2  --conditions auto:phase2_realistic_T25 -s DIGI:pdigi_valid,L1TrackTrigger,L1,DIGI2RAW,HLT:@fake2 --datatier GEN-SIM-DIGI-RAW -n 10 --geometry Extended2026D80 --era Phase2C11I13T25M9 --eventcontent FEVTDEBUGHLT', 'cmsDriver.py step3  --conditions auto:phase2_realistic_T25 -s RAW2DIGI,L1Reco,RECO,RECOSIM,PAT,VALIDATION:@phase2Validation+@miniAODValidation,DQM:@phase2+@miniAODDQM --datatier GEN-SIM-RECO,MINIAODSIM,DQMIO -n 10 --geometry Extended2026D80 --era Phase2C11I13T25M9 --eventcontent FEVTDEBUGHLT,MINIAODSIM,DQM', 'cmsDriver.py step4  --conditions auto:phase2_realistic_T25 -s HARVESTING:@phase2Validation+@phase2+@miniAODValidation+@miniAODDQM --scenario pp --filetype DQM --geometry Extended2026D80 --era Phase2C11I13T25M9 --mc '], ['TTbar_14TeV_TuneCP5_2026D80_GenSimHLBeamSpot14', 'DigiTrigger_2026D80', 'RecoGlobal_2026D80', 'HARVESTGlobal_2026D80'])
    ignoring :  (36234.0, 'TTbar_14TeV+2026D80+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14+DigiTrigger+RecoGlobal+HARVESTGlobal', ['cmsDriver.py TTbar_14TeV_TuneCP5_cfi  --conditions auto:phase2_realistic_T25 -n 10 --era Phase2C11I13T25M9 --eventcontent FEVTDEBUG --relval 9000,100 -s GEN,SIM --datatier GEN-SIM --beamspot HLLHC14TeV --geometry Extended2026D80', 'cmsDriver.py step2  --conditions auto:phase2_realistic_T25 -s DIGI:pdigi_valid,L1TrackTrigger,L1,DIGI2RAW,HLT:@fake2 --datatier GEN-SIM-DIGI-RAW -n 10 --geometry Extended2026D80 --era Phase2C11I13T25M9 --eventcontent FEVTDEBUGHLT', 'cmsDriver.py step3  --conditions auto:phase2_realistic_T25 -s RAW2DIGI,L1Reco,RECO,RECOSIM,PAT,VALIDATION:@phase2Validation+@miniAODValidation,DQM:@phase2+@miniAODDQM --datatier GEN-SIM-RECO,MINIAODSIM,DQMIO -n 10 --geometry Extended2026D80 --era Phase2C11I13T25M9 --eventcontent FEVTDEBUGHLT,MINIAODSIM,DQM', 'cmsDriver.py step4  --conditions auto:phase2_realistic_T25 -s HARVESTING:@phase2Validation+@phase2+@miniAODValidation+@miniAODDQM --scenario pp --filetype DQM --geometry Extended2026D80 --era Phase2C11I13T25M9 --mc '], ['TTbar_14TeV_TuneCP5_2026D80_GenSimHLBeamSpot14', 'DigiTrigger_2026D80', 'RecoGlobal_2026D80', 'HARVESTGlobal_2026D80'])
```

perhaps we can transform it in an error to avoid that people take the wrong workflow by mistake. Multiple matrices are already used with `--what all`. The default behavior does not change.

**Comment by silviodonato** [comment]
please test

**Comment by silviodonato** [comment]
@cms-sw/upgrade-l2 @cms-sw/pdmv-l2 do you have further comments?

**Comment by chayanit** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

**Comment by qliphy** [comment]
+1

**Pull request merged**
