### PR TITLE
Offline DQM for Displaced Jet Paths in 2017

### PR DESCRIPTION
**Pull request by jingyuluo**
Create offline DQM for Displaced Jet Paths for 2017

### CODE REVIEW

**Comment by jingyuluo** [comment]
JIRA ticket: https://its.cern.ch/jira/browse/CMSHLT-1259

**Comment by dmitrijus** [comment]
@jingyuluo Please introduce yourself, you are the first time contributor.
@mtosi should I review/sign this PR?

**Comment by jingyuluo** [comment]
Hi @dmitrijus and all, nice to meet you! I'm a graduate student from Princeton University, working on displaced jet analysis and luminosity project.   Thanks, Jingyu

**Comment by mtosi** [comment]
I'm really really puzzled by this PR !
I would suggest to contact the DQM developer team in your PAG
and in case have a chat w/ me as well

**Comment by smuzaffar** [comment]
please ignore: testing comment

**Comment by davidlange6** [comment]
Your PR is unmergeable. Please have a look and possibly rebase it.

**Comment by jingyuluo** [comment]
After the discussion with Mia, I opened a new PR #19487 for the DisplacedJet DQM, I'm going to close this one...

**Pull request closed without merging**
