### PR TITLE
HLT menu development for `13_0_X` (6/N): GRun menu V1.0 of 2023

### PR DESCRIPTION
**Pull request by missirol**
backport of #41231

#### PR description:

Development of HLT menus for `CMSSW_13_0_X`.

This version of the GRun HLT menu corresponds to the "V1.0" menu for 2023 pp data-taking, and the corresponding frozen menu is added to the release.

_Note_ : this PR has one additional change that is specific to the `13_0_X` release cycle; the `@relval2023` alias is redirected to the 2023-V1.0 frozen menu (as usual for closed releases, the appropriate frozen HLT menu, when available, is used in RelVals wfs).

This update includes the integration of the following JIRA tickets.

 - [CMSHLT-2637](https://its.cern.ch/jira/browse/CMSHLT-2637): [BPH] updated PSs of `HLT_SingleEle8_SingleEGL1` trigger
 - [CMSHLT-2644](https://its.cern.ch/jira/browse/CMSHLT-2644): [SUS,EXO,TAU] set PS=0 for `Mu3er*MET*70` and `MediumChargedIsoPFTau180HighPtRelaxedIso_Trk50_eta2p1` triggers, and remove them from GRun 
 - [CMSHLT-2645](https://its.cern.ch/jira/browse/CMSHLT-2645): [ECAL] renamed `HLT_Ele35_WPTight_Gsf_L1EGMT_v` trigger, and disabled it (PS=0)
 - [CMSHLT-2700](https://its.cern.ch/jira/browse/CMSHLT-2700): [HIG] replaced instances of `HLTPFDiJetCorrCheckerWithDiTau` with `HLTDiPFJetPlusTausCandidatePFJetProducer`
 - [CMSHLT-2704](https://its.cern.ch/jira/browse/CMSHLT-2704): [HIG] added PNet-based 4J2B backup trigger with PF-HT cut
 - [CMSHLT-2710](https://its.cern.ch/jira/browse/CMSHLT-2710): [TSG] added PS columns for "HLTPhysics+ZeroBias" and "2p3E34"
 - [CMSHLT-2723](https://its.cern.ch/jira/browse/CMSHLT-2723): [SMP] moved `HLT_Photon35_TwoProngs35` trigger to EGamma PD(s)
 - [CMSHLT-2724](https://its.cern.ch/jira/browse/CMSHLT-2724): [EXO] added `Mu6HT240*DisplacedDijet` backup triggers
 - [CMSHLT-2727](https://its.cern.ch/jira/browse/CMSHLT-2727): [SMP] added Photon+Tau and DiTau triggers for W-rare-decay searches
 - [CMSHLT-2728](https://its.cern.ch/jira/browse/CMSHLT-2728): [PPS] renamed `ExpressPPSRandom` to `DQMPPSRandom` stream/PD
 - [CMSHLT-2729](https://its.cern.ch/jira/browse/CMSHLT-2729): [BPH] single PD and stream for `ParkingDoubleElectronLowMass`
 - [CMSHLT-2730](https://its.cern.ch/jira/browse/CMSHLT-2730): [EXO] control trigger and 2 backups for L1SingleLLP-seeded triggers
 - [CMSHLT-2739](https://its.cern.ch/jira/browse/CMSHLT-2739): [MUO,EXO] set PS=4 for `HLT_Mu8_v` and `HLT_Mu8_TrkIsoVVL_v`

#### PR validation:

TSG tests.

#### If this PR is a backport, please specify the original PR and why you need to backport that PR. If this PR will be backported, please specify to which release cycle the backport is meant for:

#41231

Development of HLT menus for 2023 data-taking and Run-3 MC.

### CODE REVIEW

**Comment by missirol** [comment]
test parameters:
  - workflows = 139.004,140.003,140.023,140.043,140.063,12634.0,12634.99,12834.0,13034.0,13034.99

**Comment by missirol** [comment]
+hlt

 - changes in the outputs of PR tests are in line with updates to the HLT GRun menu, the update of the `@relval2023` alias (from "GRun" ot "2023 V1.0"), and the change in name of the fake and frozen HLT menus

**Comment by missirol** [comment]
@cms-sw/orp-l2 , kind ping to review this backport. The parent PR tested okay in the latest 13_1_X IBs.

**Comment by perrotta** [comment]
+1

**Pull request merged**
