### PR TITLE
[GEOMETRY-UPGRADE] Various fixes/improvements for unit test

### PR DESCRIPTION
**Pull request by smuzaffar**
- Convert unit tests to use `<test ...command="cmd"/>` instead of using `FW unit tests driver`
- Make sure that test can run from its dedicated test directory.

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by smuzaffar** [comment]
@cms-sw/upgrade-l2 can you please review this? This is just a technical update

**Comment by AdrianoDee** [comment]
+1
technical

**Comment by perrotta** [comment]
+1

**Pull request merged**
