### PR TITLE
including the 76X pileup Jet Id training 

### PR DESCRIPTION
**Pull request by jbrands**
This PR comes together with https://github.com/cms-data/RecoJets-JetProducers/pull/7
@kkousour and @ahinzmann 
Validation plots can be found here: http://www.hephy.at/user/jbrandstetter/PUId_validation76X/

### CODE REVIEW

**Comment by davidlange6** [comment]
@cmsbuild, please test

**Comment by ahinzmann** [comment]
@slava77, @degano: Is an integration build for this one in the works?

**Comment by slava77** [comment]
@cmsbuild please test
it should be in by now

**Comment by slava77** [comment]
@degano @smuzaffar 
Any idea why jenkins is still using CMSSW_8_0_X_2016-02-28-1100 ?
Is there some installation problem?

**Comment by smuzaffar** [comment]
@slava77 , looks like the validation job failed for 03-01-2300 IB (https://github.com/cms-sw/cmssw/pull/13474#issuecomment-191812119) , so the Base line was not generated for that IB. Due to this ib-any-integration job did not use it. Validation is now running for both 03-01-2300 and 03-02-2300, once baseline is available then pr tests should start using latest release.

**Comment by slava77** [comment]
On 3/3/16 7:31 AM, Malik Shahzad Muzaffar wrote:
> @slava77 <https://github.com/slava77> , looks like the validation job
> failed for 03-01-2300 IB (#13474 (comment)
> <https://github.com/cms-sw/cmssw/pull/13474#issuecomment-191812119>) ,
> so the Base line was not generated for that IB. Due to this
> ib-any-integration job did not use it. Validation is now running for
> both 03-01-2300 and 03-02-2300, once baseline is available then pr tests
> should start using latest release.

Thanks.

I should have checked the baseline artefacts before starting tests.
It's good to know that the more recent IB may be coming soon.

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
+1

For #13474 7c23237a87181e9320874c6f1f913a43fe849499

Updating to the new pile-up jet ID MVA training.

#13472 and #13473 are the 81X and 76X versions of this PR, and the former has been already approved.

The code changes are satisfactory, and Jenkins tests against baseline CMSSW_8_0_X_2016-03-02-2300 show no significant differences, except for those expected from the new training, as discussed and shown in #13472.

**Pull request merged**
