### PR TITLE
Fix MultiTrackValidator MVA monitoring (81X)

### PR DESCRIPTION
**Pull request by makortel**
Backport of #16660 (submitting to 81X to fix workflows being run in IB):

This PR fixes a bug introduced in #16559. The logic inferring the track MVA selector names missed a check that the MVA selector is part of the iteration sequence. This omission lead errors for tracking eras without MVA selection (`trackingLowPU`, `trackingPhase1PU70`, `trackingPhase2PU140`) in trackingOnly workflows. The check is added here.

Tested in CMSSW_8_1_X_2016-11-15-2300, no changes expected in non-trackingOnly workflows, or in trackingOnly workflows with run2 or `trackingPhase1` tracking.

@rovere @VinInn

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
type bugfix

**Comment by makortel** [comment]
backport of #16660

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by dmitrijus** [comment]
+1

**Comment by cvuosalo** [comment]
urgent

**Comment by cvuosalo** [comment]
+1

For #16661 18b2b561a9dabd34028cb38d3cda015894a12851

Fix a bug in MVA selection for tracking-only workflows. There should be no change in monitored quantities for other workflows.

#16660 is the 90X version of this PR, and it has already been approved.

The code changes are satisfactory, and Jenkins tests against baseline CMSSW_8_1_X_2016-11-21-2300 show no significant differences, as expected. Expanded configs were checked for #16660, and they show that only tracking-only workflows are changed as expected.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
