### PR TITLE
New 2017 5TeV pp beamspot parameters from data (minus pixel barycenter)

### PR DESCRIPTION
**Pull request by gsfs**

### CODE REVIEW

**Comment by civanch** [comment]
@gsfs , sorry, I may be miss 10_1_0 PR number? If it is already merged can you put reference in the description?

**Comment by civanch** [comment]
please test

**Comment by gsfs** [comment]
Same change ported to:
CMSSW_9_4_X PR#22717
CMSSW_10_1_X PR#22722

This beamspot will only be used for MC GEN-SIM in 9_3_X

**Comment by civanch** [comment]
+1

**Comment by kpedro88** [comment]
merge

**Pull request merged**
