### PR TITLE
Move division by 2 to match ngHE uhtr firmware

### PR DESCRIPTION
**Pull request by christopheralanwest**
This PR changes the order of the operations in the HCAL trigger primitive emulation to match what is done in firmware for the readout of the upgraded HEP17. In the ieta range 21-28, the segmentation of the HCAL is 10 degrees, but the energy is split evenly into two 5-degree trigger towers in order to maintain the same granularity for the trigger. In the current emulation code, the energy in each channel contributing to the sum is divided by two before performing the sum. With this PR, energies would be divided by two only after calculating the sum.

This PR fixes the differences between firmware and emulation due to rounding, as shown in the attachments.

Only MC that includes the upgraded HEP17 should be affected by this change.

[run293300_HEP17_doublephi.pdf](https://github.com/cms-sw/cmssw/files/986935/run293300_HEP17_doublephi.pdf)
[run293300_HEP17_doublephi_fixed.pdf](https://github.com/cms-sw/cmssw/files/986937/run293300_HEP17_doublephi_fixed.pdf)

### CODE REVIEW

**Comment by fwyzard** [comment]
@christopheralanwest could you make a backport to 9.1.x ?
Not necessarily to enter the 910 release, but at least to have available for people using 91x for trigger studies.
Thanks, .A

**Comment by christopheralanwest** [comment]
@fwyzard The 91X version of this PR is #18741

**Comment by fwyzard** [comment]
thanks

**Comment by fwyzard** [comment]
@cmsbuild please test

**Pull request merged**
