### PR TITLE
SimG4CMS/Tracker: Revert "Additional logs for Validation purposes"

### PR DESCRIPTION
**Pull request by vargasa**
This reverts commit 10db664e05720166306691d1d156fb4d26f60953. See https://github.com/cms-sw/cmssw/issues/31757#issuecomment-709412003

FYI: @ghugo83, @civanch

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
