### PR TITLE
Clean-up of BeamSpot PCL configs

### PR DESCRIPTION
**Pull request by dzuolo**
#### PR description:

This PR is intended to make the config files for the BeamSpot PCL workflows more homogenous, namely:
- the default parameters of the BS Fit common to the two workflows are now set to the same values
   - parameters `PVFitter.minVertexNTracks`, `PVFitter.useOnlyFirstPV` and `PVFitter.minSumPt` are now the only ones with different values between the two workflows, as it should be
- removed modification of these defaults (+ some old comments) in the Legacy workflow config
- errorScale set to 1.0 for both workflows (always recomputed offline for ReReco)

#### PR validation:

Code compiles.
`scramv1 b runtests` successful.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

This is not a backport. No backport needed.

FYI @gennai @lguzzi

### CODE REVIEW

**Comment by francescobrivio** [comment]
@cmsbuild please test

**Comment by mmusich** [comment]
@francescobrivio wouldn't it be better to test also 1004.0 and 1030.0 which exercise the BeamSpot PCL wf in other conditions outside of the short matrix?

**Comment by francescobrivio** [comment]
@cmsbuild please abort

**Comment by mmusich** [comment]
test parameters:
   * workflows = 1004.0, 1030.0

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by francescobrivio** [comment]
> test parameters:
> 
>     * workflows = 1004.0, 1030.0

thanks Marco! as usual, you are faster than anyone else! 😄

**Review by francescobrivio — APPROVED** [review]

**Comment by francescobrivio** [comment]
@mmusich the only real change here is setting the `errorScale` parameter to 1, which seems reasonable to me since we don't know _a priori_ what the pulls in the PVs will be in Run3. Can be edited in the future when we have data.
Would you agree?

**Comment by mmusich** [comment]
@francescobrivio 

> the only real change here is setting the errorScale parameter to 1, which seems reasonable to me since we don't know a priori what the pulls in the PVs will be in Run3. Can be edited in the future when we have data.
Would you agree?

don't we know a priori that the HP wf has a different errorScale compared to the legacy?

**Comment by dzuolo** [comment]
> @francescobrivio
> 
> > the only real change here is setting the errorScale parameter to 1, which seems reasonable to me since we don't know a priori what the pulls in the PVs will be in Run3. Can be edited in the future when we have data.
> > Would you agree?
> 
> don't we know a priori that the HP wf has a different errorScale compared to the legacy?

Hi Marco! I do not know if this comparison was made in the past. If not, I would propose to set the value to 1 (as measured for the re-reco of the pilot beam data with the legacy wf) and check the values again with the first collision data.

**Comment by francescobrivio** [comment]
> > @francescobrivio
> > > the only real change here is setting the errorScale parameter to 1, which seems reasonable to me since we don't know a priori what the pulls in the PVs will be in Run3. Can be edited in the future when we have data.
> > > Would you agree?
> > 
> > 
> > don't we know a priori that the HP wf has a different errorScale compared to the legacy?
> 
> Hi Marco! I do not know if this comparison was made in the past. If not, I would propose to set the value to 1 (as measured for the re-reco of the pilot beam data with the legacy wf) and check the values again with the first collision data.

@mmusich I also don't remember making this explicit comparison of the errorScale obtained with the two wfs. 
In general we do make this measurement prior to every **offline** re-reco, no matter what wf is used.
So I would agree with @dzuolo on setting it to 1 by default and in the meanwhile (i.e. before data-taking next year) we can make some study on 2018 data to check if there is a systematic difference in the errorScale between HP and Legacy wfs.

**Comment by mmusich** [comment]
> I also don't remember making this explicit comparison of the errorScale obtained with the two wfs.

@francescobrivio I am pretty sure it was done by your colleagues back in Run2. Please check again.

**Comment by mmusich** [comment]
> So I would agree with @dzuolo on setting it to 1 by default and in the meanwhile (i.e. before data-taking next year) we can make some study on 2018 data to check if there is a systematic difference in the errorScale between HP and Legacy wfs.

I'd rather study it in realistic 202~1~(2) MC.

**Comment by francescobrivio** [comment]
> > I also don't remember making this explicit comparison of the errorScale obtained with the two wfs.
> 
> @francescobrivio I am pretty sure it was done by your colleagues back in Run2. Please check again.

Ok indeed it was changed by Sara in #23361, following an explicit measurement on 2018 data.
Some checks with MC or real data will need to be re-done next year in any case, so the point now is: is it ok to change them  both to 1 or do we want to still keep the old values?

**Comment by mmusich** [comment]
>  Some checks with MC or real data will need to be re-done next year in any case, so the point now is: is it ok to change them both to 1 or do we want to still keep the old values?

with the promise to revisit them next year, I guess it's OK for now. Perhaps a comment can be left in configuration about the its significance and how to check it.

**Comment by francescobrivio** [comment]
+alca

 - mainly technical, tests are fine
 - errorScale is changed to 1 for both wfs, with the agreement to check again it before next year data taking (see https://github.com/cms-sw/cmssw/pull/36345#issuecomment-985611417) @dzuolo please add it to our to do list

**Comment by perrotta** [comment]
+1

**Pull request merged**
