### PR TITLE
mkFit: overlap area candidate re-check and start using the new hit selection V2 in pixelLess iteration

### PR DESCRIPTION
**Pull request by slava77**
requires cms-data/RecoTracker-MkFit#13
This PR is technical for the default mkFIt setup (running as in production excluding pixelLess).
The goal is to have this in 14_0 pre2 so that a special relval can be requested with pixelLess enabled.

New feature:
- (on demand/configurable) instead of independently adding hits from an overlapping module as a second hit, check the second hit after KF update with the first hit and use this post-update chi2 and the overlap hit chi2; keep the overlap if the score improves
    - enable this for the pixelLess iteration where the addition of pixel hits was quite ineffective

Updates in selecHitIndicesV2 (recently added in #43145 ):
- add propagation uncertainty when hits are selected (most important for pixels)
- sqr/sqrt mixup bugfix 
- make choice of selecHitIndicesV2 configurable
    - enable this for the pixelLess iteration where the old hit selector was overflowing and missing the right hits

Some observations with pixelLess re-enabled
- about 10% reduction in [tracking time](http://uaf-10.t2.ucsd.edu/~legianni/PR118/plots_time_v2_Dec15/plots_timing/summaryCPU.pdf): 6.6 s -> 6.0 s 
- image
- 
    - blue: mkfit5/production before this PR
    - red: mkfit5/production with this PR (to show it's technical)
    - black: mkfit5+pixelLess before this PR
    - orange: mkfit5+pixelLess with this PR
- In [Standard ttbar  MTV](http://uaf-10.t2.ucsd.edu/~legianni/PR118/plots_TT_v2_Dec15) (or in the modified [MTV with pt sim < 0.9 GeV](http://uaf-10.t2.ucsd.edu/~legianni/PR118/plots_TTlowpt_v2_Dec15/)):
    -  image recover small inefficiency below 1 GeV
    - image roughly full recovery of true tracks with large impact parameter (the plot is dominated by the low-pt PU tracks here) 
    - image signal tracks (selected here with pt< 0.9 GeV) efficiency is recovered as expected at higher production radius 
- In XiMinus sample without PU  [standard MTV](http://uaf-10.t2.ucsd.edu/~legianni/PR118/plots_XiMinus_v2_Dec15/) (and [MTV with pt sim < 0.9 GeV](http://uaf-10.t2.ucsd.edu/~legianni/PR118/plots_XiMinuslowpt_v2_Dec15/)) : 
    - image the overall efficiency is as good as CKF 
    - imageimage slight improvement for pt < 0.9 GeV (left) and still slightly worse for pt > 0.9 GeV (right)

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
test parameters:
- pull_request = cms-data/RecoTracker-MkFit#13

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
> [Reco comparison results: 1121 differences found in the comparisons](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_14_0_X_2023-12-15-1100+019829/60312/validateJR.html)

all changes are apparently in the .7 (mkFIt) workflow where the pixelLess iteration is enabled; as expected.

**Comment by jfernan2** [comment]
+1

**Comment by rappoccio** [comment]
+1

**Pull request merged**
