### PR TITLE
TkAlignment: Multi-IOV Zmumu mode, fixes to DMR averaged, PV trends

### PR DESCRIPTION
**Pull request by TomasKello**
This PR introduces following updates to the TkAl All-in-one validation tool:
- multi-IOV mode for the Zmumu validation tool
- small fixes to the PV trend and DMR luminosity-weighted validation tools

PR validation: code-checks, code-format and successful unit tests
FYI: @henriettepetersen

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by perrotta** [comment]
+alca

**Comment by TomasKello** [comment]
I would also like to create backport to CMSSW_14_0_X such as we can benefit from it in ongoing ReReco and data-taking alignment campaigns. Is that feasible? Thx

**Comment by perrotta** [comment]
> I would also like to create backport to CMSSW_14_0_X such as we can benefit from it in ongoing ReReco and data-taking alignment campaigns. Is that feasible? Thx

Please go ahead @TomasKello : as usual, I will sign it for AlCa as soon as this master version of the PR is merged, and IB tests show no issues with it

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
