### PR TITLE
NANO: rework for Prompt (part1)

### PR DESCRIPTION
**Pull request by mariadalfonso**
part1 of the https://github.com/cms-sw/cmssw/pull/34329
migrate all the object from Sequence to Task, except the ele,lowPtEle,photon,met,jet
no changes expected in any of the modifiers

### CODE REVIEW

**Comment by mariadalfonso** [comment]
please test

**Comment by mariadalfonso** [comment]
> * No significant changes to the logs found
> * Reco comparison results: 1306 differences found in the comparisons

1299/1306 due to 140.53 

https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_0_X_2021-07-27-1100+3dddd4/44411/validateJR.html
changes in the deepMetResolution and deepMetResponse not clear why this happen.
I had to add this add 5f0fe1f otherwise crash (despite the changes in ba1a837 is not supposed to change anything in the MET)

I think we merge, open an issue and then JME follow up together with the other multitude of problems of the MET :(

**Comment by mariadalfonso** [comment]
please test 546,547,548

(test nanoGen)

**Comment by mariadalfonso** [comment]
urgent

(ideally should go in the 12_0_pre5)

**Review by ramonbrugman — APPROVED** [review]

**Comment by mariadalfonso** [comment]
+xpog

* technical changes
* to follow up on separate issue https://github.com/cms-sw/cmssw/pull/34661#issuecomment-888100587

**Comment by qliphy** [comment]
+1

**Pull request merged**
