### PR TITLE
TICLv5 - Fix TracksterLinkingbySkeletons Logic

### PR DESCRIPTION
**Pull request by waredjeb**
This PR introduces a fix in the logic of the Skeletons algorithm for the Linking step in TICLv5. 
It also introduces a small fix for comparing two floating points in the SimTrackster Producer.

This PR should be tested enabling some TICLv5 workflows: 
 - `29688.203 SinglePiPt25Eta1p7_2p7_2026D110_GenSimHLBeamSpot+DigiTrigger_2026D110+RecoGlobal_ticl_v5_2026D110+HARVESTGlobal_ticl_v5_2026D110+ALCAPhase2_2026D110 `
 - `29888.203 SinglePiPt25Eta1p7_2p7_2026D110PU_GenSimHLBeamSpot+DigiTriggerPU_2026D110PU+RecoGlobalPU_ticl_v5_2026D110PU+HARVESTGlobalPU_ticl_v5_2026D110PU `

### CODE REVIEW

**Comment by felicepantaleo** [comment]
test parameters:

- workflow =  25288.203,25488.203

**Comment by felicepantaleo** [comment]
@cmsbuild please test

**Comment by felicepantaleo** [comment]
test parameters:

- workflow_opts= -w upgrade
- workflow =  25288.203,25488.203

**Comment by felicepantaleo** [comment]
@cmsbuild please test

**Comment by felicepantaleo** [comment]
test parameters:

- workflow_opts= -w upgrade
- workflow =  29888.203,29688.203

**Comment by felicepantaleo** [comment]
@cmsbuild please test

**Comment by jfernan2** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

**Comment by rappoccio** [comment]
+1

**Pull request merged**
