### PR TITLE
ctpps pixel dqm code update

### PR DESCRIPTION
**Pull request by popovvp**
2 files modified to include new station:
plugins/CTPPSPixelDQMSource.cc
python/ctppsPixelDQMSource_cfi.py

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by dmitrijus** [comment]
Please provide a 10_1_X version of this PR.
(or put a link to it if it is already done)

**Comment by popovvp** [comment]
link to the 10_1_0_pre2 version of this PR is
https://github.com/popovvp/cmssw/tree/dqmctppspix101p2

**Comment by popovvp** [comment]
Could somebody proceed the PR.
Thanks

**Comment by dmitrijus** [comment]
backport of #22678

**Comment by popovvp** [comment]
We urgently need to have these changes operational in point 5. If I'm not mistaken
there is a way to have changes implemented in the dqm even before they are in
cmssw.
Could you please try to take any action needed to have the changes operational
in dqm? We are going to have data ready very soon.

**Comment by dmitrijus** [comment]
@popovvp As with anything urgent, please send an email to core dqm mailing list.

We do have a way to get such PRs into online DQM as soon as possible.
Yes, it involves sending an email to core DQM with a PR number ;)

**Comment by dmitrijus** [comment]
+1

**Comment by fabiocos** [comment]
@popovvp after the move to 10_1_X this PR can be closed

**Pull request closed without merging**
