### PR TITLE
bsunanda:Run2-alca15 Backport the changes for AlCaReco and Trigger codes for Hcal calibrations in PRs 8943, 8950 and 9062

### PR DESCRIPTION
**Pull request by bsunanda**
Modify the AlCa codes, Calibration tree makers and the test scripts. Also changes the offline DQM for the isotrack trigger monitor. Tested in 7_5_X, seen to give clean test on top of 7_4_2.

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild please test

**Comment by deguio** [comment]
+1

**Comment by diguida** [comment]
looking at the differences (comparing with 75X PRs is not easy...)

**Comment by bsunanda** [comment]
They are supposed to be identical from the last PR in 7_5.
________________________________

**Comment by diguida** [comment]
+1
Backport od #8943 , #8950 and #9062

**Comment by abdoulline** [comment]
@davidlange6 
May we have it merged? It stays idle since quite a while... Thank you

**Comment by davidlange6** [comment]
+1

**Pull request merged**
