### PR TITLE
[92X] Fix pixel barycentre tool

### PR DESCRIPTION
**Pull request by ghellwig**
- fix use case of alignment producer that is needed for the bary-centre tool
- make the tool geometry independent
- streamline tool script
- added a unit test for the tool

### CODE REVIEW

**Comment by ghellwig** [comment]
please test

**Comment by ghellwig** [comment]
type bugfix

**Comment by ghellwig** [comment]
please test

**Comment by franzoni** [comment]
no unexpected changes observed in the tests available for 10024.0_TTbar , 136.731_RunSinglePh2016B and 10042.0_ZMM 
(the commit added after won't change any of the official sequences)

**Comment by franzoni** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
