### PR TITLE
Phase2-hgx335N Test the TB topology for HGCal

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Test the TB topology for HGCal

#### PR validation:

Use the script in test area

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by perrotta** [comment]
@civanch latest updates were pretty technical, I think you can re-sign, as you already did in https://github.com/cms-sw/cmssw/pull/40639#issuecomment-1409850477

**Comment by bsunanda** [comment]
+geometry

**Comment by perrotta** [comment]
+1

**Pull request merged**
