### PR TITLE
DAQ file broker client (10_3_X)

### PR DESCRIPTION
**Pull request by smorovic**
Support for obtaining files from DAQ File Broker in the HLT filter farm.
NFS locking mechanism is supported with a configuration parameter.

This will subsequently be pushed to 10_2_X and 10_1_X (patches are identical).

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by mommsen** [comment]
+1

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by davidlange6** [comment]
Your PR is unmergeable. Please have a look and possibly rebase it.

**Comment by smorovic** [comment]
closing, will open another PR.

**Pull request closed without merging**
