### PR TITLE
Ecal DB PayloadInspector with two different tags

### PR DESCRIPTION
**Pull request by depasse**
#### PR description:

Test of new features in DB PayloadInspector to compare 2 different tags

#### PR validation:

Tests done in command line with getPayloadData.py, png correctly produced

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by ggovi** [comment]
please test

**Comment by depasse** [comment]
I had verified this PR with :

$ scram build
$ scram build code-checks
$ scram build -k -j 16 USER_CXXFLAGS='-fsyntax-only' COMPILER='llvm compile'
$ scram build code-format

but it seems to be not enough..

Pb was that the EcalPedestals_PayloadInspector.cc  version came from 11_0_3.  Now the 11_2_0_pre9 version is used.

Cheers.
________________________________

**Comment by silviodonato** [comment]
please test
@cms-sw/db-l2

**Comment by silviodonato** [comment]
kind reminder @ggovi

**Comment by ggovi** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
