### PR TITLE
Adding a Phase2 Tracker (T11) and corresponding workflow (D29) for testing and relvals purpose 

### PR DESCRIPTION
**Pull request by boudoul**
Greetings
This PR aims to add a new version of the phase2 tracker for testing purpose as mentioned at the last simulation meeting with @kpedro88 

This new Tracker (T11) is the same as T6 but 50x50  modules.
This Tracker would benefit to get relvals for physics performance in order to guide R&Ds choice and complete the picture (together with T6,T7,T8)

The corresponding Workflows for T11 is  D29 (244xx) 

I didn't add it in IB test, I don't think it's needed , but it can be added if prefered. 
The PR test should therefore be launched with a 244xx WF

@emiglior FYI

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by kpedro88** [comment]
@boudoul we can't launch the tests with the new workflow unless it's added to relval_2023 (it's fine with me to skip testing it explicitly here, we didn't test all the other tracker variations)

**Comment by kpedro88** [comment]
+1

**Comment by ianna** [comment]
+1

**Comment by kpedro88** [comment]
@prebello @fabozzi please sign

**Comment by prebello** [comment]
+1

**Comment by prebello** [comment]
sorry approved by mistake.. I am checking it

**Comment by prebello** [comment]
@kpedro88  not clear to me: are you going to skip phaseII workflow test as pointed above?

**Comment by kpedro88** [comment]
yes, we'll skip it for now

**Comment by prebello** [comment]
+1

**Comment by kpedro88** [comment]
@fabiocos can this go in?

**Comment by fabiocos** [comment]
+operations

addition of a new upgrade geometry scenario

**Comment by fabiocos** [comment]
+1

workflow 24407.0 runs smoothly

**Pull request merged**
