### PR TITLE
Reconfiguring negative energy filter for 50 ns running. To be ported to 7_4_X.

### PR DESCRIPTION
**Pull request by igv4321**
Changed config per request from the Noise WG

### CODE REVIEW

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
+1

For #8019 01a5ad449e6d45e88d03c3033bdab707933afd92

Minor change in configuration parameters for the negative energy filter to be used for 50 ns running.

Jenkins [tests](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-8019/3054/summary.html) against baseline CMSSW_7_5_X_2015-03-03-0200 show no significant differences.

**Comment by davidlange6** [comment]
@slava77 , @cvuosalo , @igv4321 - please confirm this is desired also for any reprocessing of Run 1 data

**Comment by igv4321** [comment]
I have forwarded the question to the relevant experts. There could be a few days before it gets answered.

**Comment by davidlange6** [comment]
@igv4321 - any news?

**Comment by igv4321** [comment]
Sorry, still under discussion

**Comment by slava77** [comment]
hold

From the discussion today, it sounded like the answer is coming hopefully tomorrow.

**Comment by davidlange6** [comment]
closing this for now - i can reopen once your discussions have concluded.

**Pull request closed without merging**
