### PR TITLE
Modernize dictionary generation in FastSimDataFormats

### PR DESCRIPTION
**Pull request by Dr15Jones**
-removed use of the struct dictionary

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by ssekmen** [comment]
+1

**Comment by fabiocos** [comment]
@Dr15Jones this update follows that of #25830 and #25831. While I understand it is safe in itself for this CMSSW version, I would like to ensure that it does not pose any issue in the case it is further extended to classes that will be used in the UL production as input for an HLT processing to be performed in older CMSSW versions, as discussed in the past

**Comment by Dr15Jones** [comment]
> While I understand it is safe in itself for this CMSSW version, I would like to ensure that it does not pose any issue in the case it is further extended to classes that will be used in the UL production as input for an HLT processing to be performed in older CMSSW versions, as discussed in the past

This change actually has nothing to do with CMSSW changes. We could have done this same change when we switched from ROOT 5 to ROOT 6.0 but we just didn't realize it at the time. It now appears that this "fossil" is exciting a bug in the CXXMODULES build so it is a good time to get rid of item. With or without the `dictionary` dummy class, ROOT is supposed to generate the exact same class dictionary code. As far as I can tell, that appears to be true.

**Comment by fabiocos** [comment]
@Dr15Jones by CMSSW version I was meaning the whole environment including externals versions. 
CMSSW_8_0_X is already using ROOT6, so it should be ok.

**Comment by fabiocos** [comment]
the FastSimDataFormats/CTPPSFastSim was missing in cms-bot, I am adding a PR to fix this

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Pull request merged**
