### PR TITLE
Include ECAL Timing CC labelled tags in Run3 data and MC GTs

### PR DESCRIPTION
**Pull request by saumyaphor4252**
#### PR description:
This PR is mostly a follow-up to https://github.com/cms-sw/cmssw/pull/42928 and adds the Ecal Timing `CC` labelled tags to
- Run3 Express, Prompt, offline data GTs
- Run3 MC GTs, and
- Phase2 MC GT

as follows: 

**For MC**

|Rcd | Label | Tag |
| -- | -- | -- | 
| EcalTimeOffsetConstantRcd	| -	| EcalTimeOffsetConstant_v01_mc | 
| EcalTimeCalibConstantsRcd	| -	| EcalTimeCalibConstants_mc |  
| EcalTimeOffsetConstantRcd	| CC | EcalTimeOffsetConstant_cctiming_v01_mc |
| EcalTimeCalibConstantsRcd | CC | EcalTimeCalibConstants_mc |  

**For Data**: 

|Rcd | Label | HLT | Express | Prompt |
| -- | -- | -- | -- | -- | 
| EcalTimeOffsetConstantRcd	| -	| EcalTimeOffsetConstant_v01_hlt | EcalTimeOffsetConstant_v01_hlt | EcalTimeOffsetConstant_v01_hlt | 
| EcalTimeCalibConstantsRcd	| -	| EcalTimeCalibConstants_v3_hlt | EcalTimeCalibConstants_v3_hlt | EcalTimeCalibConstants_v3_hlt | 
| EcalTimeOffsetConstantRcd	| CC | - | EcalTimeOffsetConstant_v01_express | EcalTimeOffsetConstant_v01_express | 
| EcalTimeCalibConstantsRcd | CC | - | EcalTimeCalibConstants_v1_Express | EcalTimeCalibConstants_v01_prompt | 

| Rcd | Label | PromptAnalysis | Offline | 
| -- | -- | -- | -- | 
| EcalTimeOffsetConstantRcd	| -	| EcalTimeOffsetConstant_v01_express | EcalTimeOffsetConstant_v01_offline |
| EcalTimeCalibConstantsRcd	| -	| EcalTimeCalibConstants_v01_prompt | EcalTimeCalibConstants_Run1_Run2_Run3_v03_offline | 
| EcalTimeOffsetConstantRcd	| CC | EcalTimeOffsetConstant_v01_express | EcalTimeOffsetConstant_cctiming_v01_offline |
| EcalTimeCalibConstantsRcd | CC | EcalTimeCalibConstants_v01_prompt | EcalTimeCalibConstants_Run1_Run2_Run3_v03_offline |

The relevant CMS Talk posts and links for the mentioned changes are [1][2][3]

[1] https://indico.cern.ch/event/1329876/
[2] https://cms-talk.web.cern.ch/t/queues-133x-mc-and-data-queues-opened/29683
[3] https://cms-talk.web.cern.ch/t/full-track-validation-ecal-time-calibration-conditions-for-cc-timing-algorithm/28247 

In addition, it also introduces a new key `run3_data_PromptAnalysis` to the `autoCond`. The corresponding GT is for the offline reprocessing happening with Prompt GTs. So far, the GT has conditions used for the 2022FG reprocessing and was last done in 130X cycle [4] with `130X_dataRun3_PromptAnalysis_v1`. The difference between the 133X GT with the 130X GT used for nanov12 [4] is only the addition of the ECAL Timing `CC` labelled tags. (See in the diffs below). No workflow is testing this GT for now. We leave that to PdMV to include the relevant workflows at some point. 

[4] https://cms-talk.web.cern.ch/t/mc-offline-rereco-gts-for-2022-remini-nano-v12-in-130x/29645

Apart from that it also does some minor changes: 
 - Updates the Run-3 data offline GT to fix the ES channel status tag 
 - Resnapshots the Run3 HLT GT
 - Syncs the Express and Prompt GTs with current data-taking GTs
 - Formats text
 
**GT Differences with the last ones are here**:

- **Run3 data HLT** : No change, just updated snapshot time
  - Diff with last GT: https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/132X_dataRun3_HLT_frozen_v1/133X_dataRun3_HLT_frozen_v1
  - Diff from Current HLT GT: https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/132X_dataRun3_HLT_v2/133X_dataRun3_HLT_frozen_v1
	
- **Run3 data Express** : Includes Ecal Timing CC labelled tags, and updates as per the current Express GT with new snapshot time 
  - Diff with last GT: https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/133X_dataRun3_Express_frozen_v1/132X_dataRun3_Express_frozen_v1
  - Diff from Current Express GT: https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/133X_dataRun3_Express_frozen_v1/132X_dataRun3_Express_v4

- **Run3 data Prompt** : Includes Ecal Timing CC labelled tags, and updates as per the current Prompt GT with new snapshot time 
  - Diff with last GT: https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/133X_dataRun3_Prompt_frozen_v1/132X_dataRun3_Prompt_frozen_v1
  - Diff from Current Prompt GT: https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/133X_dataRun3_Prompt_frozen_v1/132X_dataRun3_Prompt_v4

- **Run3 data Offline** : Includes Ecal Timing CC labelled tags and updates the ES Channel status tag to fix the wrong IOV upload 375472 instead of 374572
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/133X_dataRun3_v3/132X_dataRun3_v1

- **Run3 data PromptAnalysis** : New key for offline reprocessing with Prompt GTs; Includes Ecal Timing CC labelled tags from the last GT used for NANOv12 `130X_dataRun3_PromptAnalysis_v1`
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/133X_dataRun3_PromptAnalysis_v1/130X_dataRun3_PromptAnalysis_v1

- **Phase1 2022 design** : Includes Ecal Timing CC labelled tags
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/133X_mcRun3_2022_design_v1/132X_mcRun3_2022_design_v1

- **Phase1 2022 realistic** : Includes Ecal Timing CC labelled tags
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/133X_mcRun3_2022_realistic_v1/132X_mcRun3_2022_realistic_v2

- **Phase1 2022 realistic postEE** : Includes Ecal Timing CC labelled tags
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/133X_mcRun3_2022_realistic_postEE_v1/132X_mcRun3_2022_realistic_postEE_v2

- **Phase1 2022 cosmics** : Includes Ecal Timing CC labelled tags
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/133X_mcRun3_2022cosmics_realistic_deco_v1/132X_mcRun3_2022cosmics_realistic_deco_v2

- **Phase1 2022 cosmics design** : Includes Ecal Timing CC labelled tags
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/133X_mcRun3_2022cosmics_design_deco_v1/132X_mcRun3_2022cosmics_design_deco_v1

- **Phase1 2022 realistic hi** : Includes Ecal Timing CC labelled tags
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/133X_mcRun3_2022_realistic_HI_v1/132X_mcRun3_2022_realistic_HI_v1

- **Phase1 2023 design** : Includes Ecal Timing CC labelled tags
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/133X_mcRun3_2023_design_v1/132X_mcRun3_2023_design_v1

- **Phase1 2023 realistic** : Includes Ecal Timing CC labelled tags
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/133X_mcRun3_2023_realistic_v1/132X_mcRun3_2023_realistic_v4
	
- **Phase1 2023 realistic postBPix** : Includes Ecal Timing CC labelled tags
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/133X_mcRun3_2023_realistic_postBPix_v1/132X_mcRun3_2023_realistic_postBPix_v3

- **Phase1 2023 cosmics reaslistic** : Includes Ecal Timing CC labelled tags
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/133X_mcRun3_2023cosmics_realistic_deco_v1/132X_mcRun3_2023cosmics_realistic_deco_v3

- **Phase1 2023 cosmics design** : Includes Ecal Timing CC labelled tags
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/133X_mcRun3_2023cosmics_design_deco_v1/132X_mcRun3_2023cosmics_design_deco_v1

- **Phase1 2023 realistic hi** : Includes Ecal Timing CC labelled tags
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/133X_mcRun3_2023_realistic_HI_v1/132X_mcRun3_2023_realistic_HI_v2

- **Phase1 2024 realistic** : Includes Ecal Timing CC labelled tags
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/133X_mcRun3_2024_realistic_v1/132X_mcRun3_2024_realistic_v2

- **Phase2** : Includes Ecal Timing CC labelled tags
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/133X_mcRun4_realistic_v1/132X_mcRun4_realistic_v2

#### PR validation:
Tested successfully with the PR https://github.com/cms-sw/cmssw/pull/42928 using
- `runTheMatrix.py -l 138.2,138.4,138.5,139.001,141.002,141.003,159.1,160.1,312.0,12034.0,12434.0,12834.0,11601.0,23234.0 -j10 --ibeos` 
- `runTheMatrix.py -l 12430.0,12440.0 --what upgrade -j 8 --ibeos`

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:
Not a backport. Backport will be followed up for 132X and 131X to go with:
- https://github.com/cms-sw/cmssw/pull/42946
- https://github.com/cms-sw/cmssw/pull/42947

### CODE REVIEW

**Comment by saumyaphor4252** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
> Run3 data Offline : Updates the ES Channel status tag to fix the wrong IOV upload 375472 instead of 374572
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/133X_dataRun3_v1/132X_dataRun3_v1

based on [these test results](https://github.com/cms-sw/cmssw/pull/42928#issuecomment-1749917304) looks like this GT has to be updated to add the `CC`-labeled ecal tags as well.

**Comment by saumyaphor4252** [comment]
@cmsbuild, please test

**Comment by saumyaphor4252** [comment]
@cmsbuild, please test

**Comment by saumyaphor4252** [comment]
@cmsbuild please test

**Comment by mmusich** [comment]
type bug-fix:
  * I think with this PR (alone) we expect to fix the ECAL @ HLT reconstruction in Run3 MC, as - before this PR - these workflows were using the CC timing calibration while using the ratio method in reconstruction. This PR restores the *status quo ante*.

**Comment by saumyaphor4252** [comment]
+alca
- Differences in Ecal (plus related objects) expected from the change in the Ecal Timing calibrations
- Differences in HLT trigger rates clarified by the above comment
- Bug fix for the following:
   - https://github.com/cms-sw/cmssw/pull/42761
   - https://github.com/cms-sw/cmssw/pull/42701  (See https://github.com/cms-sw/cmssw/pull/42701#issuecomment-1735105200)

**Pull request merged**
