### PR TITLE
Remove magnetic field-dependent Pixel Templates records

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:
This PR is technical, it removes 6 unused ES records (`SiPixelTemplateDBObjectXXTRcd` and `SiPixel2DTemplateDBObjectXXTRcd`). 
These seem to be separate concrete implementations of the main records to be consumed in case of non-standard magnetic field, a mechanism pre-dating the current "label" paradigm that we've been using the whole Run1 and Run2.
As far as I can see these objects are not consumed by anything downstream and there is no tag associated with them in any Global Tag used in production. On the other hand they are still associated to the `SiPixel(2D)TemplateDBObject` in the menu that is used in the GT management tool, making the life of the DB operator complicated and error prone.

#### PR validation:

Technical validation with the limited matrix:
```
runTheMatrix.py -l limited -t 4 -j 8 --ibeos
```
run without issues.

#### if this PR is a backport please specify the original PR:
This PR is not a backport.
cc:
@tsusa @tvami

### CODE REVIEW

**Comment by tocheng** [comment]
@cmsbuild please test

**Comment by tocheng** [comment]
@cmsbuild please test workflow 7.2,7.4

**Comment by tlampen** [comment]
+1
Thanks for removing unused records, which only create confusion.

**Comment by ggovi** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
