### PR TITLE
Changed FailPath/SkipEvent to TryToContinue [DPG]

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

The former options were replaced with the latter some time ago.

#### PR validation:

The configurations are not used anywhere.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by makortel** [comment]
@cms-sw/pdmv-l2 Gentle ping

**Comment by sunilUIET** [comment]
+pdmv

**Comment by rappoccio** [comment]
+1

**Pull request merged**
