### PR TITLE
memory leak fixes for Hydjets

### PR DESCRIPTION
**Pull request by wouf**
#### PR description:

This is bugfix for https://github.com/cms-sw/cmssw/pull/36316 . It fixes some bugs from [here](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-cae5ac/22136/llvm-analysis/), including memory leak issues. Also in this PR, ED modules from the test/ folder were replaced.

#### PR validation:

Hydjet2 - wf 160
Hydjet - wf 150
Pyquen - wf 300

### CODE REVIEW

**Comment by SiewYan** [comment]
please test

**Comment by SiewYan** [comment]
Thank you very much @wouf , I do not see the legacy module warning from the generator side. However, there are warning shown for other, exp: DQM:
```
%MSG-s LegacyModules:  AfterModConstruction 26-Feb-2022 07:47:42 CET pre-events
The following legacy modules are configured. Support for legacy modules
is going to end soon. These modules need to be converted to have type
edm::global, edm::stream, edm::one, or in rare cases edm::limited.
  DQMHistNormalizer normalizePlotsZTT
  DQMFEDIntegrityClient dqmFEDIntegrity
  AlcaBeamMonitorClient AlcaBeamMonitorClient
  DQMMessageLoggerClient DQMMessageLoggerClient
  SiStripDaqInfo siStripDaqInfo
  ESDaqInfoTask ecalPreshowerDaqInfoTask
  SiStripDcsInfo siStripDcsInfo
  ESDcsInfoTask ecalPreshowerDcsInfoTask
  SiStripCertificationInfo siStripCertificationInfo
  ESDataCertificationTask ecalPreshowerDataCertificationTask
  EgHLTOfflineSummaryClient egHLTOffDQMSummaryClient
  DQMOfflineHLTEventInfoClient HLTOverallSummary
```
They will be taken care of by other group.

**Comment by SiewYan** [comment]
+1

**Comment by qliphy** [comment]
this PR is a followup of #36918 :   https://github.com/cms-sw/cmssw/pull/36918#issuecomment-1039905269

**Comment by qliphy** [comment]
+1

**Pull request merged**
