### PR TITLE
Update final L1T menu tag for Run 3 start up

### PR DESCRIPTION
**Pull request by francescobrivio**
#### PR description:
This PR updates the final L1T menu tag for Run 3 start up, as requested in [this CMSTalk post](https://cms-talk.web.cern.ch/t/run-3-gt-update-of-the-l1-menu-tag-v1-0-0-in-run-3-mc-gts-and-run-3-data-relvals-gts/8895), for Run3 MC GTs and the Run3 relval GTs used for TSG tests.
The new L1T tag is `L1Menu_Collisions2022_v1_0_0_xml`.

GT differences:

**Run 3 HLT RelVals**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_dataRun3_HLT_relval_v2/123X_dataRun3_HLT_relval_v3

**Run 3 data RelVals**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_dataRun3_relval_v2/123X_dataRun3_relval_v3

**2021 design**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_mcRun3_2021_design_v12/123X_mcRun3_2021_design_v13

**2021 realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_mcRun3_2021_realistic_v12/123X_mcRun3_2021_realistic_v13

**2021 cosmics**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_mcRun3_2021cosmics_realistic_deco_v12/123X_mcRun3_2021cosmics_realistic_deco_v13

**2021 heavy ion**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_mcRun3_2021_realistic_HI_v12/123X_mcRun3_2021_realistic_HI_v13

**2023 realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_mcRun3_2023_realistic_v12/123X_mcRun3_2023_realistic_v13

**2024 realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_mcRun3_2024_realistic_v12/123X_mcRun3_2024_realistic_v13

**Phase 2 realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_mcRun4_realistic_v9/123X_mcRun4_realistic_v10

#### PR validation:
Tested with:
`runTheMatrix.py -l 12034.0,11634.0,7.23,159.0,12434.0,12834.0 --ibeos -j16`

#### Backport:
Not a backport, but a backport to 12_3_X will be provided soon.

FYI @elfontan @Martin-Grunewald

### CODE REVIEW

**Comment by francescobrivio** [comment]
test parameters:

 - workflows=12034.0,7.23,159.0,12834.0

**Comment by francescobrivio** [comment]
@cmsbuild please test

**Comment by tvami** [comment]
Hmm the results seem interesting, in data where the new GT is used, there are differences in the tracking, see https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_4_X_2022-04-01-2300+688758/49366/139.001_RunMinimumBias2021+RunMinimumBias2021+HLTDR3_2021+RECODR3_MinBiasOffline+HARVESTD2021MB/

but the MCs that used the same new tag have no difference. Can @elfontan @silviodonato comment on this? Thanks

**Comment by francescobrivio** [comment]
> Hmm the results seem interesting, in data where the new GT is used, there are differences in the tracking, see https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_4_X_2022-04-01-2300+688758/49366/139.001_RunMinimumBias2021+RunMinimumBias2021+HLTDR3_2021+RECODR3_MinBiasOffline+HARVESTD2021MB/
> 
> but the MCs that used the same new tag have no difference. Can @elfontan @silviodonato comment on this? Thanks

Pinging also @Martin-Grunewald and @missirol who I know are involved in this development as well.

**Comment by silviodonato** [comment]
> Hmm the results seem interesting, in data where the new GT is used, there are differences in the tracking, see https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_4_X_2022-04-01-2300+688758/49366/139.001_RunMinimumBias2021+RunMinimumBias2021+HLTDR3_2021+RECODR3_MinBiasOffline+HARVESTD2021MB/
> 
> but the MCs that used the same new tag have no difference. Can @elfontan @silviodonato comment on this? Thanks

Do you know what are these IOV differences?
image

The difference is in the workflow based on the 2021 minbias data (pilot beam test)

**Comment by francescobrivio** [comment]
> > Hmm the results seem interesting, in data where the new GT is used, there are differences in the tracking, see https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_4_X_2022-04-01-2300+688758/49366/139.001_RunMinimumBias2021+RunMinimumBias2021+HLTDR3_2021+RECODR3_MinBiasOffline+HARVESTD2021MB/
> > but the MCs that used the same new tag have no difference. Can @elfontan @silviodonato comment on this? Thanks
> 
> Do you know what are these IOV differences? image
> 
> The difference is in the workflow based on the 2021 minbias data (pilot beam test)

Hi Silvio! The differences are due to "live" tags that got updated in the meanwhile, but 139.001 is running on run 346512, so all these differences should be irrelevant.

**Comment by silviodonato** [comment]
no idea... I'd suggest to run the tests one more time to confirm that the differences are real

**Comment by francescobrivio** [comment]
> no idea... I'd suggest to run the tests one more time to confirm that the differences are real

Before restarting the tests I'd like to see if there are other suggestion, because the backport PR (#37443) tests are showing very similar results...

**Comment by mmusich** [comment]
@francescobrivio,

> Hi Silvio! The differences are due to "live" tags that got updated in the meanwhile (by O2Os or manually by users), but 139.001 is running on run 346512, so all these differences should be irrelevant.

They are very relevant instead. By updating the snapshot of the data GT you have unlocked this new IOV:

Screenshot from 2022-04-02 17-08-49

which was announced here: https://cms-talk.web.cern.ch/t/offline-gt-updating-corrected-fixed-pixel-cpe-2d-template/8734/1
This is expected to make small, but visible changes in tracking.

**Comment by francescobrivio** [comment]
> 

Hi @mmusich, indeed you are right, I had missed that IOV difference. Thanks a lot!

**Comment by tvami** [comment]
+alca
 * diffs in tracking are coming from the change of snapshot time
 * otherwise no other diffs are seen

**Comment by qliphy** [comment]
+1

**Pull request merged**
