### PR TITLE
CTPPS: DAQ mapping update

### PR DESCRIPTION
**Pull request by jan-kaspar**
- `CondFormats/TotemReadoutObjects/xml/ctpps_210_mapping.xml`: final 2016 configuration.
- Removed example TOTEM-standalone mapping files.

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by slava77** [comment]
running this in 274199 on top of #14605 
I see an increase in hits and then eventually tracks

AOD file size:
```
-----------------------------------------------------------------
   or, B         new, B      delta, B   delta, %   deltaJ, %    branch 
-----------------------------------------------------------------
     93.8 ->       135.2         41     36.1   0.02     TotemRPRecHitedmDetSetVector_totemRPRecHitProducer__RECO.
     67.2 ->        92.1         25     31.3   0.01     TotemRPClusteredmDetSetVector_totemRPClusterProducer__RECO.
     91.0 ->       147.6         57     47.4   0.02     TotemRPUVPatternedmDetSetVector_totemRPUVPatternFinder__RECO.
    169.7 ->       319.8        150     61.3   0.06     TotemRPLocalTrackedmDetSetVector_totemRPLocalTrackFitter__RECO.
```
these are compressed sizes (on disk)
This looks like expected and the event size is still reasonable for AOD.

Looking at the actual distributions:
about x2 more hits
all_sign718bvssign718_jetht274199c_totemrprechitedmdetsetvector_totemrprechitproducer__reco_obj__sets_data_getposition

about x2 more clusters
all_sign718bvssign718_jetht274199c_totemrpclusteredmdetsetvector_totemrpclusterproducer__reco_obj__sets_data_getnumberofstrips

slightly more than double the number of UV patterns
all_sign718bvssign718_jetht274199c_totemrpuvpatternedmdetsetvector_totemrpuvpatternfinder__reco_obj__sets_data_getprojection

just about twice the number of tracks, but almost all additions are with negative chi2 (???)
all_sign718bvssign718_jetht274199c_totemrplocaltrackedmdetsetvector_totemrplocaltrackfitter__reco_obj__sets_data_getchisquared

**Comment by mmusich** [comment]
+1
ping @ggovi

**Comment by mmusich** [comment]
@jan-kaspar do you have also a 80x version?

**Comment by jan-kaspar** [comment]
@mmusich The XML file itself is CMSSW version independent. We tend to make the 8_0_X back-ports only after the PR has been merged to 8_1_X. But we can "accelerate" the process should it matter to you.

**Comment by mmusich** [comment]
>  But we can "accelerate" the process should it matter to you.
Since we'll do the re-reco in 80x it's needed in any case.

**Comment by ggovi** [comment]
+1

**Pull request merged**
