### PR TITLE
[81X] update HcalZSThresholds 2017 condition

### PR DESCRIPTION
**Pull request by mmusich**
backport of #16705

# Summary of changes in Global Tags 
 
## Upgrade 
 
   * **PhaseI realistic scenario** : [81X_upgrade2017_realistic_v25](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_upgrade2017_realistic_v25) as [81X_upgrade2017_realistic_v24](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_upgrade2017_realistic_v24) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_upgrade2017_realistic_v25/81X_upgrade2017_realistic_v24): 
      * update on the ZSThreshold for the ADC counts (addressing [request](https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2743.html) )
 
   * **PhaseI design scenario** : [81X_upgrade2017_design_IdealBS_v9](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_upgrade2017_design_IdealBS_v9) as [81X_upgrade2017_design_IdealBS_v8](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_upgrade2017_design_IdealBS_v8) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_upgrade2017_design_IdealBS_v9/81X_upgrade2017_design_IdealBS_v8): 
      * update on the ZSThreshold for the ADC counts (addressing [request](https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2743.html) )
 
attn: @abdoulline @walterjr

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
+1

**Comment by slava77** [comment]
looking at 10024
all_oldvsnew_ttbar13tev2017wf10024p0c_log10hbherechitssorted_hbhereco__reco_obj_obj_energy

makes me wonder why we need updates that increase contributions from mostly useless hits (E<100 MeV).

**Comment by mmusich** [comment]
quoting the original reques

```
The Hcal team request a GT update on the ZSThreshold for the ADC counts.
The HCAL OPS colleagues set an upper limit (80%) for the occupancy on HE during 2017.
The HE ZS threshold level was set to 3 to keep it under 80% even at PU100, while the actual plan for 2017 is <PU>=56 [1].

Please, we request a GT update on the 2017 development MC GTs [2] for the following condition:
* HcalZSThresholds_2017_v2.0_mc
```

**Comment by abdoulline** [comment]
Slava, on HCAL side we're setting ZS threshold as low as possible to 
cope with max. FE bandwidth (occupancy). In principle, we'd prefer to 
fully remove it (as in HF...). But downstream cuts/thresholds (e/gamma, 
JetMET) would need to be adjusted.

**Comment by slava77** [comment]
On 11/21/16 9:54 AM, Salavat Abdullin wrote:
> 
> Slava, on HCAL side we're setting ZS threshold as low as possible to
> cope with max. FE bandwidth (occupancy). In principle, we'd prefer to
> fully remove it (as in HF...). But downstream cuts/thresholds (e/gamma,
> JetMET) would need to be adjusted.

Hi Salavat

Does this mean a threshold on hbhereco as well?
It would be nice then to have a threshold here so that we do not spend
CPU time in M2 and disk for RECO tier for these ~0 energy hits.

**Comment by abdoulline** [comment]
I'm not sure what you mean about hbhereco ?
For HB 2017 we (kind of naturally) keep what we have now in Run 2...
For current Run 2 HE we have acceptable, even though quite high (>50% at 
high PU) occupancy.

In general I hope that a decrease of 2017 HE ZS (in this PR), causing some 
increase of readouts to process, will be evenetually mitigated by overall 
M2 performance "breakthrough"...

**Comment by slava77** [comment]
On 11/21/16 10:09 AM, Salavat Abdullin wrote:
> 
> I'm not sure what you mean about hbhereco ?
> For HB 2017 we (kind of naturally) keep what we have now in Run 2...
> For current Run 2 HE we have acceptable, even though quite high (>50% at
> high PU) occupancy.

I see, OK, you didn't mean any changes in selections in HCAL hit
reconstruction.
Hits that have no physics value are still reconstructed and will fill up
CPU and disk.
The motivation is that FE bandwidth allows to write them out.

> 
> In general I hope that a decrease of 2017 HE ZS (in this PR), causing some
> increase of readouts to process, will be evenetually mitigated by overall
> M2 performance "breakthrough"...

For the timing, probably, but size on disk will remain the same.

**Comment by abdoulline** [comment]
Salava, we'll get back to revise ZS for 2017 _after_ e/gamma and 
JetMET (and possibly also HCAL AlCa) will assess their cuts, before 
mass-production 2017.
I agree it doesn't make sense to fill the disk with what's not needed by 
(downstream) consumers...

**Comment by slava77** [comment]
On 11/21/16 1:19 PM, Salavat Abdullin wrote:
> 
> Salava, we'll get back to revise ZS for 2017 _after_ e/gamma and
> JetMET (and possibly also HCAL AlCa) will assess their cuts, before
> mass-production 2017.

Great.
Thanks for keeping this on the todo list.


> I agree it doesn't make sense to fill the disk with what's not needed by
> (downstream) consumers...
> 
>

**Comment by abdoulline** [comment]
Slava, sorry for the typo in your name ... I tend to add extra "a" all the time :-)

**Comment by davidlange6** [comment]
hi @mmusich - not surprisingly this needs a rebase...

**Comment by mmusich** [comment]
@davidlange6 fixed. though https://github.com/cms-sw/cmssw/pull/16534 might be competing with this one

**Comment by mmusich** [comment]
please test

**Comment by davidlange6** [comment]
Right - maybe getting all the gt commits into one pr is the path of least work?

**Comment by mmusich** [comment]
It certainly is, when dependencies allow it.

**Comment by kpedro88** [comment]
@mmusich is this waiting on something?

**Comment by mmusich** [comment]
+1

**Comment by mmusich** [comment]
@kpedro88 

> is this waiting on something?

just me signing (wanted to have this #16534 first in)

**Comment by mmusich** [comment]
-1 
superseded by #16831

**Pull request closed without merging**
