### PR TITLE
Run3-sim109 Temporary fix to switch off GeneralProcess for Run3

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Temporary fix to switch off GeneralProcess for Run3 

#### PR validation:

Tested using workflows of Run3 and Phase2

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
@bsunanda , what is the reason to switch off this in modifier for Run3? It may be switched off in body of g4SimHits.

**Comment by civanch** [comment]
+1

I understand the reason.

**Comment by civanch** [comment]
@bsunanda , this PR is not yet merged, I would propose simply put False inside the body of g4SimHits and not in modifier.

**Comment by bsunanda** [comment]
@civanch I have taken your suggestion. But I thought it could be worthwhile to use this for Phase2

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by perrotta** [comment]
+1
- Switch off confirmed at the ORP meeting on Sep 7

**Pull request merged**
