### PR TITLE
DQM: Optimize DQMIO memory use

### PR DESCRIPTION
**Pull request by schneiml**
#### PR description:

As suggested by @dpiparo around ROOT-10927, the way we use TTrees in DQMIO reading is not very optimal from memory utilization point of view.

I suggested that we could create/destroy the trees as needed (since in the end, we only do a fairly small number of sequential reads), but that lead to segfaults everywhere (at least in my stand-alone test). But, a tactically placed `TTree::Reset` call might give us the same benefit, for very little effort, so that is what I try here.

#### PR validation:

So far I only tried Phat's merge job sample (with the huge HGCAL MEs in it). Results look like this: https://mschneid.web.cern.ch/mschneid/merge/mbGraph.html#?profile=withreset.json&reference=base.json&pid=_sum

There is a slight reduction in memory usage. It might be more on a job where the TTree baskets are more significant compared to the total job; we expect maybe saving 10MB in each of 10 trees? Not sure.

Also, needs more tests to see if the slowdown is systematic or just a random variation.

### CODE REVIEW

**Comment by andrius-k** [comment]
please test

**Comment by schneiml** [comment]
Wow, this `Reset` seems to have a lot more effects than I expected. From the docs it sounded more like it wouldn't have any visible impact on what we are doing...

It also looks like this causes a new memory leak in harvesting jobs: https://mschneid.web.cern.ch/mschneid/merge/mbGraph.html#?profile=harvestwithreset.json&reference=harvestwithout.json&pid=_sum . Not sure if that ultimately causes the crashes or if it is unrelated.

@dpiparo @pcanal any hints what I might be getting wrong?

**Comment by schneiml** [comment]
Ok, I suspect the `Reset` screws up the tree (resets number of entries?), but a quick skim over the docs got me to the `Refresh` call, which promises to re-initialize the tree from the file.

So I added one of those, let's see if that fixes the issues. A test on some per-lumi saved data from 2018 UL looks promising: https://mschneid.web.cern.ch/mschneid/merge/mbGraph.html#?profile=2018withreset.json&reference=2018base.json&pid=_sum

Not huge savings, but still a fairly clear signal. In this test, two files were read and there were a bunch of alternating reads (lumis from one file, then the other, then the first again).

**Comment by schneiml** [comment]
please test

**Comment by schneiml** [comment]
I did another test with some 2016 UL Rereco data: https://mschneid.web.cern.ch/mschneid/merge/mbGraph.html#?profile=2016eithreset.json&reference=2016base.json&pid=_sum

There is a consistent saving in memory, not much, but better than nothing. This also seems to come at a cost in speed (maybe 10%? not really measurable in these tests but it does seem real).

So, overall, I think this is save to go in.

**Comment by schneiml** [comment]
+1

**Comment by silviodonato** [comment]
+1
cc: @srimanob @cms-sw/pdmv-l2

**Pull request merged**
