### PR TITLE
adding photon and muon leg trigger filters of HLT_Mu17_Photon30_IsoCaloId_v

### PR DESCRIPTION
**Pull request by mrcthiel**
Backporting changes as requested in https://github.com/cms-sw/cmssw/pull/39929#issuecomment-1305273670

### CODE REVIEW

**Comment by swertz** [comment]
please test

**Comment by perrotta** [comment]
backport of #39929

**Comment by perrotta** [comment]
Please prepare also a corresponding 12_5_X backport (even though probably not needed any more after the short HI run of nov 2022)

**Comment by perrotta** [comment]
+1

**Pull request merged**
