### PR TITLE
ECAL - Add integrity checks for strip and xtal ids to GPU unpacker

### PR DESCRIPTION
**Pull request by thomreis**
#### PR description:

This PR adds integrity checks for strip ID and xtal ID to the GPU unpacker similar to the ones that exist in the CPU unpacker. This avoids crashes like the ones reported in https://github.com/cms-sw/cmssw/issues/39568 

For events with data corruption in a tower a difference in the number of unpacked digis can occur between the CPU unpacker and the GPU one because the former stops unpacking the tower if an inconsistency is detected in one channel, whereas the later unpacks the channels in parallel and an inconsistency in one channel does not affect the unpacking in other threads.
In many cases, however, an integrity problem in the raw data affects most of the channels in the tower. From the three instances reported in #39568 this year only one resulted in a difference of one digi being produced after the fix.

#### PR validation:

* Does not crash anymore on runs 367771, 368547, 368724 set up with the recipe provided in [#39568](https://github.com/cms-sw/cmssw/issues/39568#issuecomment-1557565628) .
* Passes matrix tests 12434.512, 12434.513, and 12434.514
* No differences seen between CPU and GPU digis on 7750 events from `/store/relval/CMSSW_13_0_0/RelValTTbarToDilepton_14TeV/GEN-SIM-DIGI-RAW/130X_mcRun3_2022_realistic_v2-v3/00000/`

### CODE REVIEW

**Comment by thomreis** [comment]
type ecal

**Comment by thomreis** [comment]
enable gpu

**Comment by fwyzard** [comment]
Should it be `continue` rather than `break`, to process the following entries ?

**Comment by thomreis** [comment]
The CPU unpacker drops all following channels in the tower from the moment in invalid strip ir crystal id is found. So `break` should be OK.

**Comment by thomreis** [comment]
please test

**Comment by fwyzard** [comment]
Mhm... then, the whole block should stop processing, not just the thread
that encountered the error ?

**Comment by thomreis** [comment]
Yes, that would probably mimic the CPU behaviour best but it would make things more complicated. It also does not guarantee that the CPU and GPU digis match because the already unpacked crystals are kept in the CPU unpacker and only all crystals after the invalid one are dropped.
What would be the best way to achieve breaking the loop for all?

**Comment by fwyzard** [comment]
Naively (I am not familiar with the code) a simple way would be to use a `__shared__` variable to signal all threads within a block if the should stop or continue after each crystal.

If we want to reproduce the cpu approach, where all crystals after the first failure are discarded, there could be a second pass that does that in case of failure.

**Comment by thomreis** [comment]
Given that the number of threads is 32 and a tower has 25 channels, of which some may even be zero suppressed, there should be only one pass of the loop in the current configuration.

However, if the shared variable contains the offset in the data array for which the invalid channel was found all threads working on higher offsets could be stopped before writing the digis to the output memory block. If I am not wrong this would require a `__syncthreads()` though.

**Comment by fwyzard** [comment]
> If I am not wrong this would require a `__syncthreads()` though.

Yes.

**Comment by clacaputo** [comment]
Hi @thomreis , I see some minor reco differences in `12434.587`, for example in  `pixelTracks__RECO_obj_p`

c_log10recoTracks_pixelTracks__RECO_obj_p

Is it something expected?

More differences here: [link](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisonsGPU/CMSSW_13_2_X_2023-06-15-2300+3cd2c7/57525/validateJR/12434.587_TTbar_14TeV+2023_Patatrack_AllTripletsGPU_Validation/all_RECO_step3/)

**Comment by thomreis** [comment]
I do not think this PR has an effect on pixelTracks.
Moreover, I do not think that for an MC WF the `if` statements that  cause breaks of the loop will ever be true because MC should not contain corrupted raw data.

**Comment by clacaputo** [comment]
Hi @thomreis , thanks for you reply.

About this:
> However, if the shared variable contains the offset in the data array for which the invalid channel was found all threads working on higher offsets could be stopped before writing the digis to the output memory block. If I am not wrong this would require a `__syncthreads()` though.

Do you expect to implement this?

**Comment by thomreis** [comment]
Yes but I will not be able to get to it in the next 2 weeks, unfortunately. So if we want to avoid the crashes as soon as possible I would suggest to merge this PR as it is and make an issue for me as a reminder that there is some work left to do.

**Comment by missirol** [comment]
This fix is already an improvement, and a potential solution to #39568. I checked with @fwyzard, and I think he agrees with integrating this now, and improving it in a follow-up PR. I can open the issue to keep track of this follow-up.

@cms-sw/reconstruction-l2 , do you agree ?

**Comment by missirol** [comment]
@cms-sw/reconstruction-l2 , kind ping about https://github.com/cms-sw/cmssw/pull/41977#issuecomment-1604322199.

**Comment by clacaputo** [comment]
+reconstruction

**Comment by perrotta** [comment]
+1
- @thomreis @missirol will you take care of opening the issue to keep track of https://github.com/cms-sw/cmssw/pull/41977#issuecomment-1594662179 ?

**Comment by missirol** [comment]
>  will you take care of opening the issue to keep track of [ECAL - Add integrity checks for strip and xtal ids to GPU unpacker #41977 (comment)](https://github.com/cms-sw/cmssw/pull/41977#issuecomment-1594662179) ?

Sure, I opened https://github.com/cms-sw/cmssw/issues/42090.

**Pull request merged**
