### PR TITLE
Pr81x l1t-tsg-v9 (part 2) for Sept 2016 MC production

### PR DESCRIPTION
**Pull request by rekovic**
For easier review, the full l1t-tsg-v9 PR #15732 can be considered in parts: Part 1, Part 2, and Part 3.

Part 3 (#15732) is the original full PR.
Part 2 is this PR.
Part 1 (#15745).

Part 3 is inclusive of code of Part 2.
Part 2 is inclusive of code of Part 1.

This is Part 2. 
It contains updates up to l1t-integration-v79.2.
- plus commit (simBmtf does not use input identifiers in ReEmul and L1REPACK)
  needed for successful testing.
- plus commit for declaring const vars not intended to change (this was one of review comments)

### CODE REVIEW

**Comment by rekovic** [comment]
please test

**Comment by rekovic** [comment]
please test

**Comment by davidlange6** [comment]
HI @rekovic - please rebase this on CMSSW_8_1_X now that part 1 is merged in.

**Comment by rekovic** [comment]
This PR is superseded by the rebased version in #15757.

**Pull request closed without merging**
