### PR TITLE
xrange migration to L1 and egammaanalysis

### PR DESCRIPTION
**Pull request by davidlange6**
at least one unit test in my python3 fwk test fails due to the use of xrange (now range in python3). Migrate using

futurize -f libfuturize.fixes.fix_xrange_with_import -w --no-diffs -n .

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by kpedro88** [comment]
+upgrade

**Comment by fabiocos** [comment]
+1

@santocch @rekovic the change is technical and looks straightforward, please have a look

**Comment by fabiocos** [comment]
merge

**Comment by rekovic** [comment]
+1

**Comment by santocch** [comment]
+1

**Pull request merged**
