### PR TITLE
Online DQM fed client: use rawDataRepacker for HCAL FEDIntegrity Task in HI runs

### PR DESCRIPTION
**Pull request by syuvivida**
#### PR description:
 As suggested by @mmusich, in the current heavy ion HLT menu, `Dataset_HIOnlineMonitor` still keeps the event product `FEDRawDataCollection_rawDataCollector_*_*`. This product includes  non-zero suppressed Tracker FEDs and may be the cause why in some HI runs, DQM streamer files are way over the 2GB limit. Therefore, we tested the DQM client codes with a test streamer that does not contain `FEDRawDataCollection_rawDataCollector_*_*` and see if any DQM client crashes. We found the crash of this client `fed_dqm_sourceclient-live` could be easily fixed with the change of inputTag for `hcalFEDIntegrityTask.tagFEDs`. 

With this update, the client `fed_dqm_sourceclient-live` could run on streamers that either include rawDataCollector or not. The PR does not rely on other PRs.

#### PR validation:
This PR was tested at DQM playback machines at p5 using the following streamers and run_key=hi_run, pp_run or cosmic_run. The DQM clients ran without crashing and we could see output FED histograms. For run 375252, we also ran at lxplus and compare the histograms in the output root files with this PR change (taking rawDataRepacker as input) and the default fed_dqm_sourceclient-live_cfg.py (taking rawDataCollector as input). The output histograms are identical to each other.

362321 --> hi_run, test streamer without `FEDRawDataCollection_rawDataCollector_*_*`
373710 --> pp_run 
375252 --> hi_run
375668 --> cosmic_run

The standalone job at lxplus was run via
`cmsRun DQM/Integration/python/clients/fed_dqm_sourceclient-live_cfg.py runInputDir=/eos/cms/store/group/comm_dqm/Collisions23_tempStreamers runNumber=375252 runkey=hi_run scanOnce=True`

The test streamer without rawDataCollector (run 362321, LS=231) is at
`/eos/cms/store/group/comm_dqm/HI_testStreamers/13_2_4_noDataRepacker/run362321/`

### CODE REVIEW

**Comment by mmusich** [comment]
@cms-sw/hcal-dpg-l2 FYI

**Comment by tjavaid** [comment]
please test

**Comment by abdoulline** [comment]
FYI @lwang046 
I don't know how to draw attention of Selim and Deniz (?)

**Comment by abdoulline** [comment]
Not sure why 12434.7_TTbar_14TeV+2023_trackingMkFit  (only) is affected 
https://cmsweb.cern.ch/dqm/dev/session/eKPooi

**Comment by mmusich** [comment]
> Not sure why 12434.7_TTbar_14TeV+2023_trackingMkFit (only) is affected

unrelated, see https://github.com/cms-sw/cmssw/issues/39803 (btw, the link posted cannot be opened as the DQM session is private, the tinyurl obtainable from the anchor symbol needs to be shared instead)

**Comment by tjavaid** [comment]
+1

**Comment by rappoccio** [comment]
+1

**Pull request merged**
