### PR TITLE
Moved DeepCoreSeedGenerator TF session to global cache

### PR DESCRIPTION
**Pull request by valsdav**
### PR description

This PR moves the tensorflow sessions for model evaluation in RecoTracker/DeepCoreSeedGenerator to the global cache, following the pattern of with https://github.com/cms-sw/cmssw/pull/40161 recently integrated. The resulting, planned changes are documented in https://github.com/cms-sw/cmssw/issues/40248.

### PR validation

The changes to the plugin are minor, and tests of the general, new functionality were already part of the PR mentioned above.

@clacaputo @yongbinfeng @riga

### CODE REVIEW

**Comment by mmusich** [comment]
test parameters:
   * workflow = 11723.17

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mandrenguyen** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
