### PR TITLE
PPS pixel improvement of error debugging

### PR DESCRIPTION
**Pull request by fabferro**
#### PR description:

This PR is intended to improve the information used for error debugging of PPS pixel detector.
Two DQM plots are added to show the error reported during the data unpacking process.
A slight change in the data unpacker is implemented as well to send out more information in case of errors. 

#### PR validation:

Private validation on Run3 data

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

No backport foreseen.

@grzanka

### CODE REVIEW

**Comment by mandrenguyen** [comment]
please test

**Comment by fabferro** [comment]
It seems the RelVal-INPUT tests failed due to TIMEOUT.
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-6376dd/28399/runTheMatrixINPUT-results/matrixTestsINPUT.log
Maybe they should be rerun.

**Comment by mandrenguyen** [comment]
please test
Let's retry

**Comment by mandrenguyen** [comment]
+1

**Comment by emanueleusai** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
