### PR TITLE
[Do not merge] Add -cxxmodules to dataformats genreflex flag

### PR DESCRIPTION
**Pull request by yamaguchi1024**
This is a testing PR for runtime cxxmodules.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by smuzaffar** [comment]
hold
this should not be merged. It was created to test the root cxxmodules cms-sw/cmsdist#4507. Looks like we can not test as cmsdist PR fails due to root issues.

**Comment by smuzaffar** [comment]
please test with  cms-sw/cmsdist#4507

**Comment by smuzaffar** [comment]
please test with cms-sw/cmsdist#4594

**Comment by smuzaffar** [comment]
not needed any more for test.

**Pull request closed without merging**
