### PR TITLE
Moved DetectorDescription/Core to use oneapi/tbb headers

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

The old headers are deprecated in TBB.

#### PR validation:

Code compiles.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by civanch** [comment]
The problem of the unit test seems to be strange: majority of unit tests are sequential not MT.

**Comment by Dr15Jones** [comment]
The unit test failure says it failed because it couldn’t find the python configuration file. Clearly, it is not a consequence of this PR.

**Comment by Dr15Jones** [comment]
Please test

**Comment by perrotta** [comment]
please test with #36696
(The fix for the unit test failure is already merged, but not yet available in the current IB)

**Comment by civanch** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
