### PR TITLE
Clean up Run-Dependent workflows, MultiRun harvesting for Run-Dependent MC, and update/bug fix for runTheMatrix

### PR DESCRIPTION
**Pull request by srimanob**
#### PR description:

1. Clean up steps for Run-Dependent workflows (250200.182,250202.182,250206.182) and make MultiRun harvesting possible for Run-Dependent MC,
2. Bugfix on EventsPerLumi setting when both `process.source.numberEventsInLuminosityBlock` and `--numberEventsInLuminosityBlock` are used together,
3. Workflow will be created properly when `runTheMatrix.py --command "--relval 200000,100"` is used. Before, this argument is ignored as `ns=map(int,arg...)` returns the first index of `--relval`,
4. Change `map` to `list(map)` to support both python2 and python3.

#### PR validation:
With following runTheMatrix(s), workflows return properly. 

`runTheMatrix.py --what premix -l 250200.182,250202.182,250206.182 -t 4 -b 'RD_Harvesting_6' --label 'RD_Harvesting_6' --wm init`
https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?campaign=CMSSW_11_1_0_pre5__RD_Harvesting_6-1586551410
(try new code with 11_1_0_pre5)

`runTheMatrix.py --what premix -l 250200.182,250202.182,250206.182 -t 4 --command "--relval 200000,100" --numberEventsInLuminosityBlock 100 -b 'RD_Harvesting_6HS' --label 'RD_Harvesting_6HS' --wm init`
https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?campaign=CMSSW_11_1_0_pre5__RD_Harvesting_6HS-1586551827 
(try new code with 11_1_0_pre5)

With new harvesting, auto uploading of Run-Dependent MC DQMIO to DQM GUI is successful (at the end of RelVal job).
https://tinyurl.com/vcjr6jc

#### if this PR is a backport please specify the original PR and why you need to backport that PR:
-

### CODE REVIEW

**Comment by chayanit** [comment]
please test

**Comment by kpedro88** [comment]
+upgrade

**Comment by chayanit** [comment]
+1

**Comment by silviodonato** [comment]
please test workflow 250200.182, 250202.182, 250206.182

**Comment by silviodonato** [comment]
+1

**Pull request merged**
