### PR TITLE
Move conddb to python3

### PR DESCRIPTION
**Pull request by davidlange6**
I suspect this does not work however the unit tests are more reliable in the PR testing system..

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
this passed tests - I will restart with a full cmssw build

**Comment by davidlange6** [comment]
test parameters:
  - full_cmssw = true

**Comment by davidlange6** [comment]
please abort

**Comment by davidlange6** [comment]
please test

**Comment by smuzaffar** [comment]
please test
use a newer IB

**Comment by smuzaffar** [comment]
by the way, `conddb` script shoudl work with `python3` as in `PY3` Ibs `python` is `python3`

**Comment by davidlange6** [comment]
I was worried of conflicts with boost python. It's great I'd there are none!

On Jun 16, 2021 8:17 PM, Malik Shahzad Muzaffar ***@***.***> wrote:

by the way, conddb script shoudl work with python3 as in PY3 Ibs python is python3

**Comment by davidlange6** [comment]
I removed "draft" - please consider this PR for integration.

**Comment by qliphy** [comment]
kindly ping @cms-sw/db-l2

**Comment by ggovi** [comment]
This PR does not ensure the full functionality:

[govi@cmsdev23 src]$ conddb -a /build/gg --db oradev list runinfo_31X_mc
[2021-06-24 08:28:05,212] INFO: Connecting to oradev [oracle://cms_cond_general_r@cms_orcoff_prep]
[2021-06-24 08:28:05,330] ERROR: dynamic module does not define module export function (PyInit_libCondDBPyBind11Interface)

I'm preparing the changes for the CondDBPyBind11Interface, which is used also by the o2o tool suite.

**Comment by ggovi** [comment]
I think this PR can be replaced by https://github.com/cms-sw/cmssw/pull/34233
Thanks @davidlange6

**Comment by smuzaffar** [comment]
thanks @ggovi .
Closing it in favor of #34233

**Pull request closed without merging**
