### PR TITLE
More HLT integrations before moving to the L1 seeds for 50ns

### PR DESCRIPTION
**Pull request by perrotta**
Integrate a few more jira tickets for the HLT run2 menus.
They include paths mostly in common between the menus for 25ns and 50ns.
The splitting of the master tables for the two cases will follow

### CODE REVIEW

**Comment by perrotta** [comment]
+1

**Comment by perrotta** [comment]
please test

**Comment by Martin-Grunewald** [comment]
@perrotta 

Why did you not use the same branch as / update PR #8198?
Why did you not update the 74X branch from #8071?
OK, I'll do it later...

**Comment by Martin-Grunewald** [comment]
Adding in #8198

**Comment by Martin-Grunewald** [comment]
please test

**Comment by perrotta** [comment]
Hi Martin,

1) Why did you not use the same branch as / update PR #8198?
Thank you for merging this one with #8198. The reason why I did not  
use the same branch is because it was not clear to me whther that PR  
was already fully discussed and agreed amongst the parties intervened  
in it. And we would like to have our HLT menus merged as quickly as  
possible in 75X and 74X, thus I wanted to avoid possible delays  
because of it (and, moreover, it would have been straightforward to  
rebase either one of the two PR's which wouldn't have been merged as  
first).

2) Why did you not update the 74X branch from #8071?
Because other updates are coming (L1 seeds for 50 ns). I see that  
David in not urged at all in having the menu ready for 74X (as our  
#8071 was fully signed and tested since a while but never merged in  
74X, which is something that makes the life hard to trigger  
developers). Now that #8071 is rebased to a still later IB it will  
become even more problematic for our developers to merge and build all  
needed stuffs for it. At this point, I strongly hope that it can get  
merged in 74X (@davidlange6: any hope?), that we will have a 740pre9  
or a 740 release as soon as possible (@davidlange6: any hope?) where  
TSG developers can continue working on.

Needless to say, since 74X will be the data taking release, I give for  
granted that we can continue update HLT trigger in it, possibly faster  
and with less struggle with respect to what we had to do in these last  
weeks.




Martin Grunewald <notifications@github.com> ha scritto:

**Comment by Martin-Grunewald** [comment]
Indeed, I think in Monday's TSG meeting we need to discuss again
whether we should have a separate 74X_TSG branch with releases.

**Comment by perrotta** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
