### PR TITLE
[10.2.X] MC conditions for 2018

### PR DESCRIPTION
**Pull request by lpernie**
# Summary of changes in Global Tags

## RunI simulation

   * **RunI Heavy Ions scenario** : [101X_mcRun1_HeavyIon_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_mcRun1_HeavyIon_v4) as [102X_mcRun1_HeavyIon_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/102X_mcRun1_HeavyIon_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/101X_mcRun1_HeavyIon_v4/102X_mcRun1_HeavyIon_v1):
      * AlCaRecoHLTpaths

   * **RunI Ideal scenario** : [101X_mcRun1_design_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_mcRun1_design_v4) as [102X_mcRun1_design_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/102X_mcRun1_design_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/101X_mcRun1_design_v4/102X_mcRun1_design_v1):
      * AlCaRecoHLTpaths

   * **RunI Proton-Lead scenario** : [101X_mcRun1_pA_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_mcRun1_pA_v4) as [102X_mcRun1_pA_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/102X_mcRun1_pA_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/101X_mcRun1_pA_v4/102X_mcRun1_pA_v1):
      * AlCaRecoHLTpaths

   * **RunI Realistic scenario** : [101X_mcRun1_realistic_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_mcRun1_realistic_v4) as [102X_mcRun1_realistic_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/102X_mcRun1_realistic_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/101X_mcRun1_realistic_v4/102X_mcRun1_realistic_v1):
      * AlCaRecoHLTpaths

## RunII simulation

   * **RunII Asymptotic scenario** : [102X_mcRun2_asymptotic_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/102X_mcRun2_asymptotic_v2) as [102X_mcRun2_asymptotic_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/102X_mcRun2_asymptotic_v3) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/102X_mcRun2_asymptotic_v2/102X_mcRun2_asymptotic_v3):
      * AlCaRecoHLTpaths

   * **RunII CRAFT scenario** : [102X_mcRun2cosmics_startup_deco_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/102X_mcRun2cosmics_startup_deco_v1) as [102X_mcRun2cosmics_startup_deco_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/102X_mcRun2cosmics_startup_deco_v2) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/102X_mcRun2cosmics_startup_deco_v1/102X_mcRun2cosmics_startup_deco_v2):
      * AlCaRecoHLTpaths

   * **RunII Heavy Ions scenario** : [102X_mcRun2_HeavyIon_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/102X_mcRun2_HeavyIon_v1) as [102X_mcRun2_HeavyIon_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/102X_mcRun2_HeavyIon_v2) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/102X_mcRun2_HeavyIon_v1/102X_mcRun2_HeavyIon_v2):
      * AlCaRecoHLTpaths

   * **RunII Ideal scenario** : [102X_mcRun2_design_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/102X_mcRun2_design_v1) as [102X_mcRun2_design_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/102X_mcRun2_design_v2) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/102X_mcRun2_design_v1/102X_mcRun2_design_v2):
      * AlCaRecoHLTpaths

   * **RunII Proton-Lead scenario** : [102X_mcRun2_pA_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/102X_mcRun2_pA_v1) as [102X_mcRun2_pA_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/102X_mcRun2_pA_v2) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/102X_mcRun2_pA_v1/102X_mcRun2_pA_v2):
      * AlCaRecoHLTpaths

   * **RunII Startup scenario** : [102X_mcRun2_startup_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/102X_mcRun2_startup_v1) as [102X_mcRun2_startup_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/102X_mcRun2_startup_v2) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/102X_mcRun2_startup_v1/102X_mcRun2_startup_v2):
      * AlCaRecoHLTpaths

## Upgrade

   * **PhaseII realistic scenario** : [102X_upgrade2023_realistic_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/102X_upgrade2023_realistic_v1) as [102X_upgrade2023_realistic_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/102X_upgrade2023_realistic_v2) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/102X_upgrade2023_realistic_v1/102X_upgrade2023_realistic_v2):
      * EcalChannelStatus CTPPS_Geometry AlCaRecoHLTpaths

   * **PhaseI 2018 cosmics scenario** : [102X_upgrade2018cosmics_realistic_deco_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/102X_upgrade2018cosmics_realistic_deco_v1) as [102X_upgrade2018cosmics_realistic_deco_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/102X_upgrade2018cosmics_realistic_deco_v2) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/102X_upgrade2018cosmics_realistic_deco_v1/102X_upgrade2018cosmics_realistic_deco_v2):
      * EcalChannelStatus CTPPS_Geometry_2018 AlCaRecoHLTpaths HcalChannelQuality HcalGainsHcalPedestals HcalPedestalWidthsHcalSiPMParameters

   * **PhaseI 2018 design scenario** : [102X_upgrade2018_design_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/102X_upgrade2018_design_v1) as [102X_upgrade2018_design_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/102X_upgrade2018_design_v2) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/102X_upgrade2018_design_v1/102X_upgrade2018_design_v2):
      * EcalChannelStatus CTPPS_Geometry_2018 AlCaRecoHLTpaths HcalChannelQuality HcalGainsHcalPedestals HcalPedestalWidthsHcalSiPMParameters

   * **PhaseI 2018 realistic scenario** : [102X_upgrade2018_realistic_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/102X_upgrade2018_realistic_v1) as [102X_upgrade2018_realistic_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/102X_upgrade2018_realistic_v3) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/102X_upgrade2018_realistic_v1/102X_upgrade2018_realistic_v3):
      * EcalChannelStatus CTPPS_Geometry_2018 AlCaRecoHLTpaths HcalChannelQuality HcalGainsHcalPedestals HcalPedestalWidthsHcalSiPMParameters

## 2017_MC

   * **PhaseI 2017 cosmics peak scenario** : [102X_mc2017cosmics_realistic_deco_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/102X_mc2017cosmics_realistic_deco_v1) as [102X_mc2017cosmics_realistic_deco_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/102X_mc2017cosmics_realistic_deco_v2) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/102X_mc2017cosmics_realistic_deco_v1/102X_mc2017cosmics_realistic_deco_v2):
      * AlCaRecoHLTpaths ExtendedDetailedCavern2017Plan1

   * **PhaseI 2017 cosmics scenario** : [102X_mc2017cosmics_realistic_peak_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/102X_mc2017cosmics_realistic_peak_v1) as [102X_mc2017cosmics_realistic_peak_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/102X_mc2017cosmics_realistic_peak_v2) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/102X_mc2017cosmics_realistic_peak_v1/102X_mc2017cosmics_realistic_peak_v2):
      * AlCaRecoHLTpaths ExtendedDetailedCavern2017Plan1

   * **PhaseI 2017 design scenario** : [102X_mc2017_design_IdealBS_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/102X_mc2017_design_IdealBS_v1) as [102X_mc2017_design_IdealBS_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/102X_mc2017_design_IdealBS_v2) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/102X_mc2017_design_IdealBS_v1/102X_mc2017_design_IdealBS_v2):
      * AlCaRecoHLTpaths ExtendedDetailedCavern2017Plan1

   * **PhaseI 2017 realistic scenario** : [102X_mc2017_realistic_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/102X_mc2017_realistic_v1) as [102X_mc2017_realistic_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/102X_mc2017_realistic_v2) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/102X_mc2017_realistic_v1/102X_mc2017_realistic_v2):
      * AlCaRecoHLTpaths ExtendedDetailedCavern2017Plan1

# Notes
. Due to a broken paths in the DQM code this PR will fail if not tested with #23523

### CODE REVIEW

**Comment by lpernie** [comment]
please test with #23523

**Comment by lpernie** [comment]
please test

**Comment by fabiocos** [comment]
@lpernie what is the plan for this PR?

**Comment by arunhep** [comment]
@fabiocos we will check the differences today and sign. sorry for the delay.
we aim to have it merged by pre6

**Comment by arunhep** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
