### PR TITLE
Run3-alca165 Update all scripts for IsoTrack calibration

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Update all scripts for IsoTrack calibration

#### PR validation:

Tested them and used for calibration studies

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by pohsun** [comment]
please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by pohsun** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
