### PR TITLE
TagProbeFitter: replace call to deprecated overload of RooPdf::paramOn

### PR DESCRIPTION
**Pull request by iarspider**
#### PR description:
It was marked as deprecated for a long time, and was completely removed in https://github.com/root-project/root/pull/12608

### CODE REVIEW

**Comment by iarspider** [comment]
test parameters:

-   pull_request = https://github.com/cms-sw/cmsdist/pull/8433

**Comment by iarspider** [comment]
please test

**Comment by smuzaffar** [comment]
@perrotta @rappoccio can we get this in. This is needed for ROOT6 update (it removes the use of deprecated `RooPdf::paramOn` methoed)

**Comment by perrotta** [comment]
+1

**Comment by perrotta** [comment]
merge

**Pull request merged**
