### PR TITLE
EcalPayloadInspector for Pedestals and ChannelStatus

### PR DESCRIPTION
**Pull request by depasse**
Ecal PayloadInspector for Pedestals and ChannelStatus with magic numbers replaced by constant expressions

### CODE REVIEW

**Comment by kpedro88** [comment]
-1
still the wrong base
please use the GitHub comparison view to see what you are doing before making further PRs

**Comment by slava77** [comment]
-1

**Comment by depasse** [comment]
I don't understand !
I have :
base fork : cms-sw/cmssw
base : master
head fork : depasse/cmssw
compare :EcalPayloadInspector_Pedestals_ChannelStatus

What is wrong ?
Has stgh been changed recently ?
Thanks.
________________________________

**Comment by kpedro88** [comment]
https://github.com/cms-sw/cmssw/compare/master...depasse:EcalPayloadInspector_Pedestals_ChannelStatus clearly shows several recent 91X merge commits in your branch.

92X is the development branch, not 91X. So you need to make sure the base of your branch is the latest 92X IB.

**Pull request closed without merging**
