### PR TITLE
DD4hep: TrackerGeometryBuilder Track FilteredView info

### PR DESCRIPTION
**Pull request by vargasa**
#### PR description:

Progress on https://github.com/cms-sw/cmssw/issues/31143, please see: https://github.com/cms-sw/cmssw/issues/31143#issuecomment-675687549

#### PR validation:

```
$ cmsRun SimG4Core/Configuration/test/ddd_ZMM_Run3_Step1_cfg.py
$ cmsRun SimG4Core/Configuration/test/ddd_ZMM_Run3_Step2_cfg.py
$ cmsRun SimG4Core/Configuration/test/dd4hep_ZMM_Run3_Step3_cfg.py # Still breaking but producing better logs
```

@ianna `dd4hep::FilteredView::nextSibling()` and `dd::FilteredView::nextSibling()` are taking us to different nodes. Is that the expected behavior?

### CODE REVIEW

**Comment by cvuosalo** [comment]
@vargasa This PR looks like a draft or test PR. What are your plans for it? Do you want the PR tests run?

**Comment by vargasa** [comment]
Hi @cvuosalo, yes please. The plan is to have it merged

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by ianna** [comment]
> @ianna `dd4hep::FilteredView::nextSibling()` and `dd::FilteredView::nextSibling()` are taking us to different nodes. Is that the expected behavior?

yes

**Comment by silviodonato** [comment]
+1

**Pull request merged**
