### PR TITLE
Clang Check modernize-use-override

### PR DESCRIPTION
**Pull request by ianna**
Geometry part from @davidlange6 https://github.com/cms-sw/cmssw/pull/19529

Note, I agree with clang that _override_ would be superfluous in declarations where _final_, but not virtual, occurs. Still, the latter declaration expresses the intent a lot clearer and should definitely be preferred.

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
@smuzaffar - I've tried to run failing tests locally and they pass.

**Comment by ianna** [comment]
please test

**Comment by smuzaffar** [comment]
yes, looks like in this case tests were timed out and killed by timeout command.
```
^^^^ End Test testTauEmbeddingProducers ^^^^
>> Tests for package TauAnalysis/MCEmbeddingTools ran.
config/SCRAM/GMake/Makefile.rules:2042: recipe for target 'unittests_runTheWhiteRabbit' failed
gmake: *** [unittests_runTheWhiteRabbit] Terminated
```
if every thing else look good then we should ignore the unittest error here

**Comment by ianna** [comment]
+1

**Comment by ianna** [comment]
@kpedro88 - ping

**Comment by kpedro88** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
