### PR TITLE
Vs self subtraction ver2

### PR DESCRIPTION
**Pull request by yslai**
This is a change to implement a "fall-back" mode, when no calibration information is available, that estimates the UE from the same event using a close approximation of the ATLAS algorithm [Physics Letters B 719, 220–241 (2013)]. This mode is not turned on by default.

### CODE REVIEW

**Comment by slava77** [comment]
@yslai please break up the headers and implementation of GenericVoronoiAlgorithm, VoronoiAlgorithm, and SelfSubtractVoronoiAlgorithm into separate cc/h files.
I think that the source code file VoronoiAlgorithm.cc is already too large.

**Comment by slava77** [comment]
Hi Yue Shi,
are we expecting more commits here soon?

**Comment by yetkinyilmaz** [comment]
Hi. I think cmsbuild's notification was a bit late, and we didn't respond to @slava77.
Let me answer on behalf of @yslai - we discussed the organization of the code and decided to re-implement it in a different arrangement. Therefore, I think this PR should be closed and a new one should be submitted when ready.

**Comment by slava77** [comment]
-1
this can be closed for now (and reopened or made into another PR once ready, as described in https://github.com/cms-sw/cmssw/pull/10991#issuecomment-136742892

**Pull request closed without merging**
