### PR TITLE
[Do not merge] Update classversion CLHEP::Hep3Vector

### PR DESCRIPTION
**Pull request by mrodozov**
#### PR description:

This is needed for testing geant4 changes, since clhep is updated
We cannot have this in master, not until we use the updated version of clhep for our master on https://github.com/cms-sw/cmsdist

#### PR validation:

DataFormats/CLHEP is building

### CODE REVIEW

**Comment by mrodozov** [comment]
please test with https://github.com/cms-sw/cmsdist/pull/6486

**Comment by mrodozov** [comment]
please test with https://github.com/cms-sw/cmsdist/pull/6492

**Comment by mrodozov** [comment]
should it be one additional record like:
```
  <class name="CLHEP::Hep3Vector" ClassVersion="11">
   <version ClassVersion="11" checksum="newchecksum"/>
  </class>
  <class name="CLHEP::Hep3Vector" ClassVersion="10">
   <version ClassVersion="10" checksum="3040806103"/>
  </class>
```

**Comment by mrodozov** [comment]
abort

**Comment by mrodozov** [comment]
I see there are other records like this in the same file

**Comment by davidlange6** [comment]
No, like this:

<class name="CLHEP::Hep3Vector" ClassVersion="11">
   <version ClassVersion="11" checksum="newchecksum"/>
    <version ClassVersion="10" checksum="3040806103"/>
  </class>

**Comment by mrodozov** [comment]
please test with cms-sw/cmsdist#6492

**Comment by civanch** [comment]
@mrodozov , likely warnings are connected with gcc930 and not this PR, error in unit test likely also does not connected with this PR, but failing regression is an issue. This means, that CLHEP constants upgrade affects results. In this case, I would conclude, that we cannot merge new CLHEP to 11_3_X alone. A possible solution would be to merge it only to GEANT4 branches. So, Geant4 10.7 should be validated together with CLHEP 2.4.4.0.

**Comment by mrodozov** [comment]
@civanch yes this needs validation etc, errors are present
The thing with cmssw is that we don't have special cmssw branch for geant4 releases, we use master,
see the RELEASE_BRANCH here:
https://github.com/cms-sw/cms-bot/blob/master/config.map#L7-L8
I think we'll have to make one for G4 that is clone of master and we merge it once we catch up with externals for 'default' G4
If we had such branches than trying clhep 2440 integration against cmssw master would've not been needed.

**Comment by civanch** [comment]
@mrodozov , if I understand correctly, today we cannot simply include new CLHEP in 11_3_GEANT4_X, because it is another external? In 11_3_GEANT4_X we take master and can add only Geant4 modification, not other external libraries?

**Comment by davidlange6** [comment]
Which of reported errors do you believe are connected to CLHEP?

**Comment by mrodozov** [comment]
the unit test failing looks unrelated, but in case we wanted to get this I would've tried to figure it out where this python failure comes from. 
@civanch almost, yes, we can add new externals to GEANT4 as we changed VecGeom last week - as long as the externals does not require changes like this one in CMSSW. Now, CLHEP requires changes also in cmssw

we can have only one version of 
`<class name="CLHEP::Hep3Vector" ClassVersion="11">`
in CMSSW master
but 
geant4 cmsdist branch with clhep 2440 will require version 11
master cmsdist branch with clnep 2413 will require version 10
and because we have only one branch on cmssw that we use for both, we must have another one for geant4
@smuzaffar should we branch master with another name to use for geant4 ?

**Comment by davidlange6** [comment]
Hum, 

is this the right set of diffs ?

https://github.com/cms-externals/clhep/compare/cms/v2.4.1.3...cms/v2.4.4.0

Quite odd that something here triggered a Hep3Vector version change

**Comment by mrodozov** [comment]
there is no commit history because I took clhep 2.4.4.0 from a tar file following:
https://github.com/cms-externals/geant4/issues/51
I see they have the tag also on gitlab now
https://gitlab.cern.ch/CLHEP/CLHEP
but they didn't few days ago.

**Comment by civanch** [comment]
I may be do not understand something, but in the diff between new branch v2.4.4.0 and the master I do not see any difference in numerical constants, while in the CLHEP documentation there is an entry:

2020-07-20 Gabriele Cosmo <Gabriele.Cosmo@cern.ch>

* Units: Updated values in SystemOfUnits.h and PhysicalConstants.h for:
           e_SI, electron charge
           h_Planck, Planck constant
           Avogadro, Avogadro constant
           k_Boltzmann, Boltzmann constant
         based on May 2019 redefinition of SI units. References:
           https://en.wikipedia.org/wiki/2019_redefinition_of_the_SI_base_units
           https://www.britannica.com/science/electron-charge.

This is a claim, that they peaked up from Britannica and Wikipedia new values for number of constants. Values are changed on level of 5th or 6th digits, which should change slightly cross sections and secondary distributions on such level, likely changing simulation histories.

By the way, I cannot see this in our repository, only in CLHEP original.

**Comment by davidlange6** [comment]
Strange. From what I see

git clone -b cms/v2.4.4.0 git@github.com:cms-externals/clhep.git
git clone -b CLHEP_2_4_4_0 https://gitlab.cern.ch/CLHEP/CLHEP.git gitlab
diff -r clhep/ gitlab/

Seems correct.

**Comment by davidlange6** [comment]
It seems something is wrong with the diffs link (not sure what.. anyone see why?)

https://gitlab.cern.ch/CLHEP/CLHEP/-/compare/CLHEP_2_4_1_3...CLHEP_2_4_4_0

**Comment by davidlange6** [comment]
and the Hep3Vector change
https://gitlab.cern.ch/CLHEP/CLHEP/-/commit/5f20daf0cae911793d9aa5fc62987d6dc83647ab

**Comment by davidlange6** [comment]
@civanch 

-  static constexpr double e_SI  = 1.602176487e-19;// positron charge in coulomb
+  static constexpr double e_SI  = 1.602176634e-19;// positron charge in coulomb

-static constexpr double h_Planck      = 6.62606896e-34 * joule*s;
+static constexpr double h_Planck      = 6.62607015e-34 * joule*s;

-static constexpr double k_Boltzmann = 8.617343e-11 * MeV/kelvin;
+static constexpr double k_Boltzmann = 8.617333e-11 * MeV/kelvin;

-static constexpr double Avogadro = 6.02214179e+23/mole;
+static constexpr double Avogadro = 6.02214076e+23/mole;

**Comment by davidlange6** [comment]
> On Dec 10, 2020, at 3:12 PM, Mircho Rodozov <notifications@github.com> wrote:
> 
> 
> the unit test failing looks unrelated, but in case we wanted to get this I would've tried to figure it out where this python failure comes from.
> @civanch almost, yes, we can add new externals to GEANT4 as we changed VecGeom last week - as long as the externals does not require changes like this one in CMSSW. Now, CLHEP requires changes also in cmssw
> 
> we can have only one version of
> <class name="CLHEP::Hep3Vector" ClassVersion="11">
> in CMSSW master
> but
> geant4 cmsdist branch with clhep 2440 will require version 11
> master cmsdist branch with clnep 2413 will require version 10
> and because we have only one branch on cmssw that we use for both, we must have another one for geant4
> @smuzaffar should we branch master with another name to use for geant4 ?
> 

One option you have is to pick up a simple patch via cmssw-queue-override.file

**Comment by smuzaffar** [comment]
one problem with  cmssw-queue-override.file is that it is not used by PR testing setup or for local development (e.g. cms-addpkg is not going to apply these patches)

**Comment by civanch** [comment]
Again, I may be not understand something but He3Vector change is the optimization of the code itself: https://gitlab.cern.ch/CLHEP/CLHEP/-/commit/5f20daf0cae911793d9aa5fc62987d6dc83647ab
but not change any functionality of the class.

**Comment by civanch** [comment]
We may request PPD validation of new CLHEP+VecGeom on top of existing master together with 11_3_0_pre1 or 11_2_0.
This will take significant time but we follow the CMS procedure.

**Comment by civanch** [comment]
@mrodozov , @smuzaffar , how we can resolve this problem? I see two possibilities: 1) ask PPD validation of the new CLHEP separate, later we will ask for validation of GEANT4 10.7; 2) asking validation of CLHEP+Geant4 10.7 together?

**Comment by mrodozov** [comment]
@civanch CLHEP validation only will be more simple because you have to test Geant 10.7 for some time and ask for validation later on

**Comment by davidlange6** [comment]
> On Dec 10, 2020, at 5:32 PM, Vladimir Ivantchenko <notifications@github.com> wrote:
> 
> 
> Again, I may be not understand something but He3Vector change is the optimization of the code itself: https://gitlab.cern.ch/CLHEP/CLHEP/-/commit/5f20daf0cae911793d9aa5fc62987d6dc83647ab
> but not change any functionality of the class.

The data members of the Hep3Vector class changed…  So as usual, to store it persistently the checksum needs to be updated accordingly..

**Comment by smuzaffar** [comment]
@civanch , @davidlange6 I have created CMSSW_11_3_GEANT4_X branch. As discussed during ORP, we can include new clhep and geant4 (along with this change here) for geant4 IBs and ask for a validation.

**Comment by smuzaffar** [comment]
please test with cms-sw/cmsdist#6486

**Comment by smuzaffar** [comment]
looks good for geant4 IB. lets get this merged for geant4 IBs so that we can build g4 release for validation

**Comment by mrodozov** [comment]
please test with https://github.com/cms-sw/cmsdist/pull/6512

**Pull request merged**
