### PR TITLE
PPS: fix two validation plots

### PR DESCRIPTION
**Pull request by jan-kaspar**
#### PR description:

This PR contains 2 trivial fixes (ranges and variable order) of 2 PPS validation plots.

### CODE REVIEW

**Comment by silviodonato** [comment]
test parameters
relvals_opt = --what standard,highstats,pileup,generator,production,ged,2017,2026,machine,premix,gpu; pwd; ls -lh

**Comment by silviodonato** [comment]
please test

**Comment by silviodonato** [comment]
@jan-kaspar please ignore the weird options (they are related to https://github.com/cms-sw/cms-bot/issues/1539). The outcome should be identical to the standard "please test"

**Comment by smuzaffar** [comment]
> test parameters
> relvals_opt = --what standard,highstats,pileup,generator,production,ged,2017,2026,machine,premix,gpu; pwd; ls -lh

@silviodonato , this known and we only allow valid cms users to set these options. pleas esee my comment on  cms-sw/cms-bot#1539

**Comment by jfernan2** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
