### PR TITLE
75x Fireworks: Adjust camera position when open 3D region

### PR DESCRIPTION
**Pull request by alja**
Forward port of #11215

### CODE REVIEW

**Comment by alja** [comment]
+1

**Comment by davidlange6** [comment]
@cmsbuild, please test

**Comment by alja** [comment]
-1 found errror in merge

**Comment by alja** [comment]
+1
fix clang error came back from failed merge

**Comment by davidlange6** [comment]
@cmsbuild, please test

**Comment by davidlange6** [comment]
+1




On Sep 11, 2015, at 9:28 AM, cmsbuild <notifications@github.com<mailto:notifications@github.com>> wrote:


+1
Tested at: 25eef25<https://github.com/cms-sw/cmssw/commit/25eef259b09823d7a59668f4fc0a18bb0c8a8327>
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-11217/8011/summary.html

**Pull request merged**
