### PR TITLE
[12_4_X] Correct the sampic record name

### PR DESCRIPTION
**Pull request by ChrisMisan**
#### PR description:

This PR resolves PCL harvester crash by correcting the sampic record name. 

#### PR validation:
PR was validated with the tarball /afs/cern.ch/user/c/cmst0/public/PausedJobs/ALCAPPS/job_27. The PR will be followed by the new relval test for sampic PCL.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport of #38843

### CODE REVIEW

**Comment by ChrisMisan** [comment]
type ctpps, bug-fix

**Comment by ChrisMisan** [comment]
urgent

- this backport is needed for the next release

**Comment by ChrisMisan** [comment]
please test

**Comment by tvami** [comment]
@cms-sw/orp-l2 so as we agreed, this should be merged and go into 12_4_4 thanks

**Comment by qliphy** [comment]
+1

**Pull request merged**
