### PR TITLE
adding new per-lumi flags to Jetmet DQM

### PR DESCRIPTION
**Pull request by iatakisi**
#### PR description:  
Here I'm adding new  flags to check met, met 2,  sumet and MEtphi  for Jetmet DQMOffline DC   
#### PR validation: 
I ran "runTheMatrix.py -l limited -i all --ibeos" and did not get any error

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by iatakisi** [comment]
Hi,
Should I do something about this PR so that we can have it?

**Comment by emanueleusai** [comment]
let's retest

**Comment by emanueleusai** [comment]
please test

**Comment by emanueleusai** [comment]
@iatakisi I believe there is a problem with your code. You changed MET to per-lumi, but it gets accessed in the endrun to create the ratios: https://github.com/cms-sw/cmssw/blob/c5c79d3a2e208f72621ff37cbf71c6350d084721/DQMOffline/JetMET/src/METAnalyzer.cc#L1389

Can you also explain where are the new flags created? It looks like you are just moving some MEs from being filled per-run to being filled per-lumi.

**Comment by iatakisi** [comment]
> @iatakisi I believe there is a problem with your code. You changed MET to per-lumi, but it gets accessed in the endrun to create the ratios:
> 
> https://github.com/cms-sw/cmssw/blob/c5c79d3a2e208f72621ff37cbf71c6350d084721/DQMOffline/JetMET/src/METAnalyzer.cc#L1389
> 
> Can you also explain where are the new flags created? It looks like you are just moving some MEs from being filled per-run to being filled per-lumi.

     hMETSig->setLumiFlag();

**Pull request closed without merging**
