### PR TITLE
Fix plugin library name AlpakaCore/plugins/BuildFile.xml

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

Should fix the unit test failures reported in https://github.com/cms-sw/cmssw/pull/44387#issuecomment-2002959350

#### PR validation:

None

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Need to be included in https://github.com/cms-sw/cmssw/pull/44388

### CODE REVIEW

**Comment by makortel** [comment]
test parameters
  - addpkg = HeterogeneousCore/AlpakaTest

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by fwyzard** [comment]
+1

**Comment by fwyzard** [comment]
Thanks for the fix.

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
