### PR TITLE
Include HcalPFCuts Rcd and update SiPixel Dynamic Inefficiency tags in MC GTs

### PR DESCRIPTION
**Pull request by saumyaphor4252**
#### PR description:
This PR:
- Integrates the `HcalPFCuts` record in all the MC GTs introduced in https://github.com/cms-sw/cmssw/pull/41128 by updating the 
  - Run1 and Run2 GTs with tag `HcalPFCuts_2016_v1.0_mc`
  - 2017 GTs with tag `HcalPFCuts_2017_v1.0_mc`
  - 2018 GTs with tag `HcalPFCuts_2018_v1.0_mc`
  - 2022 GTs with tag `HcalPFCuts_2022_v1.0_mc`
  - 2023, 2024 and Phase2 GTs with tag `HcalPFCuts_2023_V1.0_mc`
  as requested in this [CMS Talk post](https://cms-talk.web.cern.ch/t/mc-newly-created-hcalpfcuts-mc-tags-submitted-to-13-1-x-mc-queues/22585)[1]. 
- In addition, it also updates the latest SiPixel dynamic Inefficincy tag `SiPixelDynamicInefficiency_phase1_2023_v2_fix2` in the Phase1 2022, 2023 and 2024 GTs requested in this [CMS Talk post](https://cms-talk.web.cern.ch/t/request-creation-of-a-gt-with-preliminary-pixel-dynamic-inefficiency-settings/20385/15) [2].

[1] https://cms-talk.web.cern.ch/t/mc-newly-created-hcalpfcuts-mc-tags-submitted-to-13-1-x-mc-queues/22585
[2] https://cms-talk.web.cern.ch/t/request-creation-of-a-gt-with-preliminary-pixel-dynamic-inefficiency-settings/20385/15

**GT Differences with the last ones are here**:
- **Run1 Design**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/131X_mcRun1_design_v1/131X_mcRun1_design_v2

- **Run1 Realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/131X_mcRun1_realistic_v1/131X_mcRun1_realistic_v2

- **Run1 HI**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/131X_mcRun1_HeavyIon_v1/131X_mcRun1_HeavyIon_v2

- **Run2 Startup**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/131X_mcRun2_startup_v1/131X_mcRun2_startup_v2

- **Run2 l1stage1**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/131X_mcRun2_asymptotic_l1stage1_v1/131X_mcRun2_asymptotic_l1stage1_v2

- **Run2 design**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/131X_mcRun2_design_v1/131X_mcRun2_design_v2

- **Run2 pre VFP**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/131X_mcRun2_asymptotic_preVFP_v1/131X_mcRun2_asymptotic_preVFP_v2

- **Run2 Asymptotic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/131X_mcRun2_asymptotic_v1/131X_mcRun2_asymptotic_v2

- **Run2 MC cosmics**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/131X_mcRun2cosmics_asymptotic_deco_v1/131X_mcRun2cosmics_asymptotic_deco_v2

- **Run2 MC HI**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/131X_mcRun2_HeavyIon_v1/131X_mcRun2_HeavyIon_v2

- **Run2 MC pA**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/131X_mcRun2_pA_v1/131X_mcRun2_pA_v2

- **Phase1 2017 design**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/131X_mc2017_design_v1/131X_mc2017_design_v2

- **Phase1 2017 realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/131X_mc2017_realistic_v1/131X_mc2017_realistic_v2

- **Phase1 2017 cosmics**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/131X_mc2017cosmics_realistic_deco_v1/131X_mc2017cosmics_realistic_deco_v2

- **Phase1 2017 cosmics peak**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/131X_mc2017cosmics_realistic_peak_v1/131X_mc2017cosmics_realistic_peak_v2

- **Phase1 2018 design**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/131X_upgrade2018_design_v1/131X_upgrade2018_design_v2

- **Phase1 2018 realistic**   
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/131X_upgrade2018_realistic_v1/131X_upgrade2018_realistic_v2

- **Phase1 2018 realistic RD**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/131X_upgrade2018_realistic_RD_v1/131X_upgrade2018_realistic_RD_v2

- **Phase1 2018 realistic HI**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/131X_upgrade2018_realistic_HI_v1/131X_upgrade2018_realistic_HI_v2

- **Phase1 2018 realistic HEfail**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/131X_upgrade2018_realistic_HEfail_v2/131X_upgrade2018_realistic_HEfail_v3

- **Phase1 2018 cosmics**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/131X_upgrade2018cosmics_realistic_deco_v1/131X_upgrade2018cosmics_realistic_deco_v2

- **Phase1 2018 cosmics peak**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/131X_upgrade2018cosmics_realistic_peak_v2/131X_upgrade2018cosmics_realistic_peak_v3

- **Phase1 2022 design**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/131X_mcRun3_2022_design_v1/131X_mcRun3_2022_design_v2

- **Phase1 2022 realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/131X_mcRun3_2022_realistic_v2/131X_mcRun3_2022_realistic_v3

- **Phase1 2022 realistic postEE**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/131X_mcRun3_2022_realistic_postEE_v2/131X_mcRun3_2022_realistic_postEE_v3

- **Phase1 2022 cosmics**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/131X_mcRun3_2022cosmics_realistic_deco_v2/131X_mcRun3_2022cosmics_realistic_deco_v3

- **Phase1 2022 cosmics design**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/131X_mcRun3_2022cosmics_design_deco_v1/131X_mcRun3_2022cosmics_design_deco_v2

- **Phase1 2022 realistic hi**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/131X_mcRun3_2022_realistic_HI_v4/131X_mcRun3_2022_realistic_HI_v5

- **Phase1 2023 design**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/131X_mcRun3_2023_design_v3/131X_mcRun3_2023_design_v4

- **Phase1 2023 realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/131X_mcRun3_2023_realistic_v3/131X_mcRun3_2023_realistic_v4

- **Phase1 2023 cosmics**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/131X_mcRun3_2023cosmics_realistic_deco_v3/131X_mcRun3_2023cosmics_realistic_deco_v4

- **Phase1 2023 cosmics design**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/131X_mcRun3_2023cosmics_design_deco_v3/131X_mcRun3_2023cosmics_design_deco_v4

- **Phase1 2023 realistic hi**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/131X_mcRun3_2023_realistic_HI_v6/131X_mcRun3_2023_realistic_HI_v7

- **Phase1 2024 realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/131X_mcRun3_2024_realistic_v1/131X_mcRun3_2024_realistic_v2

- **Phase2 realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/131X_mcRun4_realistic_v2/131X_mcRun4_realistic_v3

#### PR validation:
GTs tested locally with `runTheMatrix.py -l 5.1,8.0,9.0,25.0,101.0,140.0,50200.0,7.22,145.0,281.0,1325.516,11634.0,7.23,159.0,12434.0,12834.0,7.24,160.1 -j 8 --ibeos -j 8 --ibeos`

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:
Not a backport, but a partial backport with the SiPixel Dynamic Inefficiency GT updates will be followed up.

### CODE REVIEW

**Comment by saumyaphor4252** [comment]
@cmsbuild, please test

**Comment by francescobrivio** [comment]
FYI @abdoulline

**Comment by tvami** [comment]
+alca
 * widespread changes, as expected from the redigitization using new DynEff payload

**Comment by perrotta** [comment]
@saumyaphor4252 @tvami 
In wf 11834 there are changes also in tracking quantities that should not depend on HCAL, eg:

image

Is it expected, or due to some known instability in that workflow?

**Comment by mmusich** [comment]
> Is it expected, or due to some known instability in that workflow?

Aren't we changing the pixel dynamic inefficiency here as well???

**Comment by perrotta** [comment]
> > Is it expected, or due to some known instability in that workflow?
> 
> Aren't we changing the pixel dynamic inefficiency here as well???

Correct, thank you @mmusich
(I just woke up...)

**Comment by perrotta** [comment]
!

**Comment by perrotta** [comment]
+1

**Comment by makortel** [comment]
Seems that this PR caused `HcalPFCuts_unittest` unit test to fail in the IBs, see https://github.com/cms-sw/cmssw/issues/41338

**Pull request merged**
