### PR TITLE
Replace mirrored finders in RecoMuon from TrackingTools/DetLayer with the original ones

### PR DESCRIPTION
**Pull request by perrotta**
#### PR description:

Following the resolution of the MTD related part of issue #24452 by PR #32026 (from @fabiocos), I address here the part of the [comment](https://github.com/cms-sw/cmssw/pull/24285#issuecomment-418102225) which referred to RecoMuon's instead, so that it is resolved as well.

The issue claimed that there was no reason to maintain all files like (e.g.) `RecoMuon/DetLayers/src/RBorderFinder.h` which just mirror (e.g.) `TrackingTools/DetLayers/interface/RBorderFinder.h`.

With this PR I'm going to replace their inclusion in `RecoMuon/DetLayers` with the one of the original headers from `TrackingTools/DetLayers`

#### PR validation:

It builds, that's enough
No changes expected

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
please abort

**Comment by perrotta** [comment]
+1
- Simple cleanup
- Jenkins tests pass

**Comment by silviodonato** [comment]
+1

**Pull request merged**
