### PR TITLE
Update MPI tools and tests [12.4.x]

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Update `cmsenv_mpirun` to look for `cmsenv_orted` also under the base releases.

Move the test for CUDA availability from `mpiCudaGeneric` binary to the BuildFile.xml.

#### PR validation:

Tested using a CMSSW area with `cmsenv_orted` under `$CMSSW_RELEASE_BASE/bin/` and not under `$CMSSW_BASE/bin`.

#### If this PR is a backport please specify the original PR and why you need to backport that PR.

Backport of #39036 to CMSSW 12.4.x for ongoing DAQ tests (not used for data taking).

### CODE REVIEW

**Comment by fwyzard** [comment]
backport #39036

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
+heterogeneous

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
+heterogeneous

**Comment by qliphy** [comment]
+1

**Pull request merged**
