### PR TITLE
fix era to be compliant with underlying D91 geometry

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

Addresses comment at https://github.com/cms-sw/cmssw/pull/36660#discussion_r803730616, in order to comply with the description of the geometry at:

https://github.com/cms-sw/cmssw/blob/09bb0b76d6c22947de05c50a46c8ae254c504b97/Configuration/Geometry/python/dict2026Geometry.py#L1750

#### PR validation:

none

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

### CODE REVIEW

**Comment by mmusich** [comment]
test parameters:
   * workflow = 40634.0

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by perrotta** [comment]
type bug-fix

**Comment by srimanob** [comment]
+Upgrade

PR to fix the era of D91, and add missing doc.

**Comment by kskovpen** [comment]
+pdmv

**Comment by perrotta** [comment]
@cms-sw/geometry-l2 is there anything that prevents you signing this bug fix?

**Comment by cvuosalo** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
