### PR TITLE
Add Run-3 FastSim wf to runTheMatrix

### PR DESCRIPTION
**Pull request by srimanob**
#### PR description:
This is to add Run-3 FastSim wf to runTheMatrix.

#### PR validation:
Test with wf `11634.301`

#### if this PR is a backport please specify the original PR and why you need to backport that PR:
No need of backport.

### CODE REVIEW

**Comment by srimanob** [comment]
@cmsbuild please test

**Comment by srimanob** [comment]
@smuzaffar 
Could you please advise on relval-input. As the FastSim workflow runs in one step. Changing the first step (GENSIM) to be relval-input will not make it works. Thanks.

**Comment by perrotta** [comment]
please test

**Comment by srimanob** [comment]
@smuzaffar @makortel @perrotta @qliphy 
Could you please advise on relval-input in IB. As the FastSim workflow runs in one step, changing the first step to be relval-input will not make it works. Thanks for suggestion.

**Comment by perrotta** [comment]
@cms-sw/fastsim-l2 and @cms-sw/pdmv-l2 may give some suggestion on how to adapt the test for relval-input

**Comment by makortel** [comment]
As far as I can tell, the existing FastSim workflows are not run as part of RelVal-INPUT test. Could there be some difference in the setup (via `upgradeWorkflowComponents.py` here vs. `relval_standard.py` for the existing ones) that causes the workflow added here to be run in RelVal-INPUT?

**Comment by makortel** [comment]
The log https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-d509e8/24298/runTheMatrixINPUT-results/matrixTestsINPUT.log looks like the list of workflows is passed to `runTheMatrix` explicitly. Maybe the script calling `runTheMatrix` needs to be told to ignore X.301 or something? @smuzaffar

**Comment by smuzaffar** [comment]
RelVal-INPUT tests runs step1 of all the default workflow for `runTheMatrix.py`. If step1 for this workflow does not require input data then it should be properly configured. I am not an expert of runTheMatrix configuration but I think https://github.com/cms-sw/cmssw/blob/master/Configuration/PyReleaseValidation/python/relval_steps.py needs to be updated to to avoid running step1 for this workflow

**Comment by kpedro88** [comment]
I think the conditions in https://github.com/cms-sw/cmssw/blob/303dd5e62ec35fbfd47d2185d78505ec09b6e77f/Configuration/PyReleaseValidation/python/relval_steps.py#L3766-L3768 need to be updated to handle this new workflow correctly.

**Comment by srimanob** [comment]
Thanks @kpedro88 @smuzaffar @makortel for following up. 
I will update the workflow and condition for fastsim to make it runs properly without INPUT.

**Comment by srimanob** [comment]
@cmsbuild please test

**Comment by kskovpen** [comment]
+pdmv

**Comment by srimanob** [comment]
+Upgrade

This PR includes fastsim workflow to the short matrix.

**Comment by perrotta** [comment]
+1
- The new workflow appears in the Matrix Tests Outputs

**Comment by sbein** [comment]
Thanks @srimanob!

**Pull request merged**
