### PR TITLE
Fixed typo in mixing names

### PR DESCRIPTION
**Pull request by gsfs**
Some of these Poisson options will be used for the 2017 pp reference run at 5 TeV.

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

(looks like this PR got missed)

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
+operations

**Comment by fabiocos** [comment]
merge

**Comment by fabiocos** [comment]
@smuzaffar Is this PR stuck with tests not starting? I checked the fix and it looks simple and ok, and performed a test in a CMSSW area of mine.

**Comment by smuzaffar** [comment]
something is wrong with this PR as it says 
`gsfs wants to merge 1 commit into cms-sw:master from unknown repository `
looks like the source branch for this PR was delete or some. @gsfs, can you open a new PR?

**Comment by gsfs** [comment]
Can anyone tell me how the source branch was deleted? Is this something I could have done by accident?

**Comment by fabiocos** [comment]
@gsfs I am not sure what happened here, but since the problem is real and fix simple, I would suggest either to update this PR or make a new one and close this one, so as we have the fix.

**Comment by gsfs** [comment]
Something went wrong with this pull request since it now says "unknown repository". Will close it and replace it with PR#21853.

**Pull request closed without merging**
