### PR TITLE
[HCAL] Bug fix and default configuration change for Mahi reconstruction

### PR DESCRIPTION
**Pull request by jaylawhorn**
After some internal discussion, this PR makes the following changes to Mahi reconstruction:
- Initialize floating pedestal at 0, not sqrt(pedestal Width)
- Activate chiSquare-based 1 vs 3 pulse switch for Mahi so that:
     (1)Start with 1 pulse + pedestal fit
     (2)If chiSq>chiSqThresh[15], do 3 pulse + pedestal fit
- Offset pulse shape template based on sample of interest (TS3 vs TS4) instead of number of samples (8 vs 10)

In pre3 configuration, observe that the relative energy response between Method 2 and Mahi has energy dependent variation of ~20%
Attached
[mahi_config_change.pdf](https://github.com/cms-sw/cmssw/files/1630071/mahi_config_change.pdf)
 slides show this PR reduces this variation as well as improving overall resolution between Method 2 and Mahi.

~~This is one small bugfix and one config change for Mahi reconstruction:~~

~~(1) The 1 TS offset for the pulse shape arrays in Mahi should be based on the sample of interest, not the number of samples.~~

~~(2) The fit is initialized with pedestal at 0 instead of the average pedestal width.~~

~~These are expected to have very little impact on the overall performance, mostly at low energy. Point (1) should have no impact at all.~~

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by slava77** [comment]
On 1/12/18 6:11 AM, Jay Lawhorn wrote:
> This is one small bugfix and one config change for Mahi reconstruction:
> 
> (1) The 1 TS offset for the pulse shape arrays in Mahi should be based
> on the sample of interest, not the number of samples.
> 
> (2) The fit is initialized with pedestal at 0 instead of the average
> pedestal width.
> 
> ------------------------------------------------------------------------
> 
> 

please provide some plots/slides that describe changes in performance
Thank you.

**Comment by jaylawhorn** [comment]
I reverted the change to the pedestal initialization to decouple the physics performance from a purely software bug. This PR should now have no impact on physics distributions.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@jaylawhorn 
please clarify what will happen to the change that was undone. I have actually interpreted the pedestal bin change as a bugfix because it has aligned the initial values for all bins to be at zero.

Should we expect a separate/additional PR now?

**Comment by jaylawhorn** [comment]
Sorry for the waste of time/resources, the tsSize vs tsOffset was a stupid mistake on my part. I will discuss the strategy for other changes with my HCAL colleagues and get back to you in the next few hours.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@jaylawhorn please update the slides in the PR description with a bit more text.
I wasn't able to follow the upper and lower set of plots with all different colors.

**Comment by jaylawhorn** [comment]
@slava77 I added an extra page of explanation on pg2
[mahi_config_change_v2.pdf](https://github.com/cms-sw/cmssw/files/1630867/mahi_config_change_v2.pdf)

**Comment by slava77** [comment]
@jaylawhorn 
looking at p2 of the slides I see "2017 MC with pileup (10024.0)" and "2018 MC with pileup (10824.0)" . This is inconsistent. The two workflow numbers mentioned do not have pileup (equivalents with pileup are 10224 and 11024).

**Comment by jaylawhorn** [comment]
@slava77 
That was unclear notation, sorry. More accurately: 
"10024.0": run the step3 from 10024.0 on /store/relval/CMSSW_10_0_0_pre3/RelValTTbar_13/GEN-SIM-DIGI-RAW/PU25ns_100X_mc2017_realistic_v1_mahiOFF-v1/20000/105AC931-E6E8-E711-9F4E-003048FFCBB2.root
"10824.0": run the step3 from 10824.0 on /store/relval/CMSSW_10_0_0_pre3/RelValTTbar_13/GEN-SIM-DIGI-RAW/PU25ns_100X_upgrade2018_realistic_v4_mahiOFF-v1/20000/048FD543-85E9-E711-8FC9-0CC47A78A414.root
[mahi_config_change_v3.pdf](https://github.com/cms-sw/cmssw/files/1633800/mahi_config_change_v3.pdf)

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/21840	ffb029f
- updates to MAHI to get its performance more in line with M2
- jenkins tests pass and comparisons with baseline show differences starting from hbheprereco and propagate downstream. The changes go somewhat in the direction closer to the baseline that we had before #21664 (checked based on a local copy from the past tests).
- tests with more events made locally confirm the behavior expected from https://github.com/cms-sw/cmssw/files/1633800/mahi_config_change_v3.pdf provided with this PR.

wf 10071 (flat-pt dijet , no PU)
wf10071_ak4calo_b
wf10071_ak4calo_e
jet response is up by ~5%

similar increase is visible in PF reco
wf10071_ak4pf_b
wf10071_ak4pf_e

**Comment by slava77** [comment]
The changes come from a combination of previously zero energy hits now reconstructed with non-zero (mainly in the low-energy range) and more significantly from an increase of the energy of reconstructed hits which already had non-zero values.
Here are some scatter plots from 10071 (only entries with changes in energies are shown; there is about 50% of entries where values remained unchanged):
hbhereco_mismatch_log10energy_2d_colz

In a comparison with M0 the changed reconstructed hits are now more consistent:
hbhereco_mismatch_log10energyrm0n_2d_colz
vs the baseline
hbhereco_mismatch_log10energyrm0o_2d_colz

the remaining fraction that was not modified by this PR may need some (future) work especially for the range with M0 E>10 GeV where the impact is larger
hbhereco_match_log10energyrm0o_2d_colz
I'm not sure if areas with E_MAHI >E_M0*1.2 are particularly physical.

Similar matching and mismatching comparisons with PU and 2018 setup also show an increase in response, with a more clear bump around 1
hbhereco_mismatch_log10energyrm0n_2d_colz
hbhereco_mismatch_log10energyrm0o_2d_colz

The piece that remained unchanged perhaps also needs some checks
hbhereco_match_log10energyrm0o_2d_colz

**Comment by fabiocos** [comment]
+1

**Pull request merged**
