### PR TITLE
fix: adjust jme_nano cff for changes in #31618

### LINKED ISSUE #31768: 'PSet' object has no attribute 'btagCMVA'
After having merged #31618 (`CMSSW_11_2_X_2020-10-13-1100`) we get this error in wf 10224.15, 11024.15, 25202.15
```
NANO,ENDJOB
We have determined that this is simulation (if not, rerun cmsDriver.py with --data)
with DB:
entry file:step3_inMINIAODSIM.root
Step: NANO Spec: 
Step: ENDJOB Spec: 
customising the process with nanoAOD_customizeMC from PhysicsTools/NanoAOD/nano_cff
Traceback (most recent call last):
  File "/cvmfs/cms-ib.cern.ch/nweek-02650/cc8_amd64_gcc8/cms/cmssw/CMSSW_11_2_X_2020-10-12-2300/bin/cc8_amd64_gcc8/cmsDriver.py", line 56, in <module>
    run()
  File "/cvmfs/cms-ib.cern.ch/nweek-02650/cc8_amd64_gcc8/cms/cmssw/CMSSW_11_2_X_2020-10-12-2300/bin/cc8_amd64_gcc8/cmsDriver.py", line 28, in run
    configBuilder.prepare()
  File "/cvmfs/cms-ib.cern.ch/nweek-02650/cc8_amd64_gcc8/cms/cmssw/CMSSW_11_2_X_2020-10-12-2300/python/Configuration/Applications/ConfigBuilder.py", line 2277, in prepare
    self.pythonCfgCode += self.addCustomise()
  File "/cvmfs/cms-ib.cern.ch/nweek-02650/cc8_amd64_gcc8/cms/cmssw/CMSSW_11_2_X_2020-10-12-2300/python/Configuration/Applications/ConfigBuilder.py", line 865, in addCustomise
    __import__(packageName)
  File "/cvmfs/cms-ib.cern.ch/nweek-02650/cc8_amd64_gcc8/cms/cmssw/CMSSW_11_2_X_2020-10-12-2300/python/PhysicsTools/NanoAOD/custom_jme_cff.py", line 173, in <module>
    btagCMVA  = jetTable.variables.btagCMVA,
AttributeError: 'PSet' object has no attribute 'btagCMVA'
```

### PR DESCRIPTION
**Pull request by andrzejnovak**
Fixes #31768. 
- update custom_jme_cff to sync with default nano changes

@mariadalfonso

### CODE REVIEW

**Comment by mariadalfonso** [comment]
please test workflow 10224.15, 11024.15, 25202.15

**Comment by mariadalfonso** [comment]
type bug-fix

**Comment by mariadalfonso** [comment]
+xpog

fix on the JME to avoid crash
JMEnano updated also for BTV purposed

**Comment by silviodonato** [comment]
merge

**Comment by santocch** [comment]
+1

**Pull request merged**
