### PR TITLE
Calibration update 80 x

### PR DESCRIPTION
**Pull request by dimattia**
Greetings,

this PR contains the fix for the memory issue reported here:
https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2291/2/1/1/1.html

Functional tests are ok. Profile plots will come tomorrow.

Cheers,
Alessandro

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
Hi @dimattia, I get now:
```
------------------------------------------------------------------------------------------
Detailed ressource usage information FOR ALL ME
------------------------------------------------------------------------------------------
subsystem/folder                          histograms       bins        Empty bins     Empty/Total      bins per       MB         kB per
                                           (total)        (total)        (total)                      histogram     (total)    histogram  
------------------------------------------------------------------------------------------
AlCaReco
 -> DtCalibSynch                            2060        566490        303210         0.535           275          2.16          1.07
 -> SiStrip                                14878       9522460       9153064         0.961           640          36.4          2.51
 -> SiStripGains                               9     177290000         92561      0.000522      1.97e+07           676      7.69e+04
 -> SiStripGainsAfterAbortGap                  9     177290000         92561      0.000522      1.97e+07           676      7.69e+04
 -> TkAlMinBias                              268        124031         21397         0.173           463         0.532          2.03
    SUBSYSTEM TOTAL                        17224     364792981       9662793        0.0265      2.12e+04      1.43e+03          82.7
..........................................................................................
```

when it used to be:

```
------------------------------------------------------------------------------------------
Detailed ressource usage information FOR ALL ME
------------------------------------------------------------------------------------------
subsystem/folder             histograms       bins        Empty bins     Empty/Total      bins per       MB         kB per
                                 (total)     (total)        (total)                       histogram     (total)    histogram  
------------------------------------------------------------------------------------------
AlCaReco
 -> DtCalibSynch                   2060        566490        303210         0.535           275          2.16          1.07
 -> SiStrip                       14878       9522460       9153064         0.961           640          36.4          2.51
 -> SiStripGains                     18     354580000        185170      0.000522      1.97e+07      1.35e+03      7.69e+04
 -> SiStripGainsAfterAbortGap        18     354580000        185170      0.000522      1.97e+07      1.35e+03      7.69e+04
 -> TkAlMinBias                     265        123382         21308         0.173           466          0.53          2.05
    SUBSYSTEM TOTAL               17239     719372332       9847922        0.0137      4.17e+04      2.81e+03           163
..........................................................................................

```

**Comment by mmusich** [comment]
@dimattia we need also a backport in 80X once finished with the checks

**Comment by mmusich** [comment]
memory

some crude profiling of RSS vs time in WF 1001.0 shows we should be almost back to 803.

**Comment by mmusich** [comment]
+1

**Comment by davidlange6** [comment]
A ~1.5G increase isn't really "close" to 803... but definitely better than 804. will have a look in the next days

**Comment by davidlange6** [comment]
@dimattia @mmusich 
so I begin to realize that this is memory in a single threaded job...as its all an end-of-job blow up, this is a reminder as to why the dqm does not use something as simple as TFileService in production to store big histograms. We'll need to resolve that. 

However, as a shorter term way to improving things, I have two questions regarding the big histograms:
1) why not TH1S? Are there either 30k entries in a bin?
2) was 2000 bins determined? Eg, Is the rms of the Landau you are fitting something like 3-5 bins?

**Comment by davidlange6** [comment]
and as just discussed in the PPD meeting, it seems that 

process.MEtoEDMConvertSiStripGains.deleteAfterCopy=True

could save 700MB (*2 for two analyzers) if it has no ill effect (my job still has exit code 0)

**Comment by deguio** [comment]
ciao @davidlange6 
indeed what you propose would save more then 1GB. see attachment.
screen shot 2016-04-25 at 19 39 30

based on WF 1001.0 where we added:

`process.MEtoEDMConvertSiStripGains.deleteAfterCopy=cms.untracked.bool(True)`
`process.MEtoEDMConvertSiStripGainsAfterAbortGap.deleteAfterCopy=cms.untracked.bool(True)`


we don't see any drawback in adding this and thinking at the design of the PCL workflows.
ciao,
Gian and F.

**Comment by dimattia** [comment]
@davidlange6

Hi, first let me answering to the questions posed by David

1) why not TH1S? Are there either 30k entries in a bin?

A single 2D histogram is used having in X the APV chip ID (e.g. 77000 APVs in the detector, each one requiring the charge calibration), while in Y there is the full dynamic range for the cluster charge in ADC counts over the path length in the sensor. The Landau is fit on the Y.

In X 1 bin == 1APV chip, this is why it is so huge (almost 80000 APVs). What do we gain if we use 1D histo? I think nothing, please correct me if I am wrong.



2) was 2000 bins determined? Eg, Is the rms of the Landau you are fitting something like 3-5 bins?

This is the full dynamic range used to fit the Landau for every APV chip. This was determined to accomodate the changes on cluster charge shape that we have due to changes in coverage/efficiency, thickness and path-lenght (e.g. incident angle of tracks) over the full detector. In addition it was also determined to have good fit error which scales with statistic. 

This is what we inherited. I believe we can optimize it because we can try to make the binning as a function of r (radius) and eta in the detector. Anyway this requires some study to prove that the new binning is robust. Given the timescale and the manpower this is something that cannot come now.


Then, concerning the proposal of having deleteAfterCopy set to True

I already discussed this with Federico and other guys in the past, as I didn’t understood what actually did this option. In some tests I did see that it only saves 500 MByte. If my eyes didn’t fool myself I see almost 600 Mbytes saved on the plot below (where do you see it is 1 GByte?). Given the memory consumption I believed (and believe) this is a negligible improvement (e.g. it is not the bottleneck). If you think it is worth to have it can easily go into a new update …. if Federico haven;t modified it yet.

By the way: in the workflow of last year we had DeleteAfterCopy set to False for SIStripGain …. which is what I copied for the SiStripAfterAbortGap.

Cheers,
Alessandro.

**Comment by davidlange6** [comment]
it seems I had an important typo in question #1 - I meant a TH2S rather than a TH1S (e.g., to use shorts instead of floats in your data structure)

**Comment by deguio** [comment]
@dimattia 
the DeleteAfterCopy option saves >1GB wrt the red line in marco's plot, which is the memory usage of 80x+this PR on top. this is the configuration I tested.
cheers,
F.

**Comment by davidlange6** [comment]
it should be NHistogramsDeleted*SizeOfHistogram, e.g. 2*700, essentially. It sounds like we should look at all of the Me2edm converters that have this deletion parameter set to false.

**Comment by cerminar** [comment]
@davidlange6 not exactly all. Some of them (running in different steps of the PCL) need it.
Cheers,
G

**Comment by davidlange6** [comment]
I suggested “to look at” - indeed...

**Comment by mmusich** [comment]
please test

**Comment by davidlange6** [comment]
Hi @dimattia - any news on the questions from yesterday's ORP?

**Comment by dimattia** [comment]
Hi,

@davidlange6 I checked the maximum number of entries using histograms that contains the “gold plated” statistics (e.g. 2x10^9 clusters) for a calibration run. Indeed there are no more than 3000 entries per bin for the maximum split of statistics (e.g. split per APV readout chip). We may have troubles if we merge the statistics per readout link or per module (e.g. going coarser than a single APV chip). Anyway this usually happens when the statistics is not enough to calibrate a single APV, hence I believe the statistics per single bin will never exceed 32000.

I will implement the switch TH2F -> TH2S in the next update of this pull request. Likely within the next hour.

Cheers,
Alessandro.

**Comment by mmusich** [comment]
please test

**Comment by dimattia** [comment]
Hi,

@davidlange6  the change TH2F - > TH2F has been implemented in the PR update. Sorry it took a bit more because I need to perform also the test for the gain validation.

Cheers,
Alessandro.

**Comment by mmusich** [comment]
pr_14918

peak RSS measured in wf 1001.0 merging https://github.com/cms-sw/cmssw/pull/14198/commits/9e47c9253dd5f2ae1adc264aae35d697f3133841 is somewhere in 3.5 - 4 GB

**Comment by mmusich** [comment]
+1

**Pull request merged**
