### PR TITLE
Fix TPTask occupancy plots (10_0_X)

### PR DESCRIPTION
**Pull request by DryRun**
The TPTask occupancy plots only get filled if both HBHE and HF TP digis have been found. This PR splits them apart.

10_0_X backport of #22552

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by dmitrijus** [comment]
+1

**Comment by DryRun** [comment]
I just added one more commit to fix the the HF TP TDC cut monitoring, corresponding to https://github.com/cms-sw/cmssw/pull/22667. 

One the tests have be re-run, could this PR be considered for merging into 10_0_X, along with https://github.com/cms-sw/cmssw/pull/22436 and https://github.com/cms-sw/cmssw/pull/22597? We're starting to build up a few outstanding HCALDQM PRs, which last year led to the eternal giant PR that never got merged.

**Comment by dmitrijus** [comment]
+1

**Comment by dmitrijus** [comment]
backport #22552

**Comment by fabiocos** [comment]
+1

**Pull request merged**
