### PR TITLE
L1T muon online DQM 8_1_X - 2nd try

### PR DESCRIPTION
**Pull request by thomreis**
Port to 8_1_X of PR #15378 
2nd try after PR #15423 rebase did not work out as planned.

### CODE REVIEW

**Comment by thomreis** [comment]
Can someone launch the tests for this please to get the process going?

**Comment by dmitrijus** [comment]
please test

**Comment by thomreis** [comment]
Tests look good. @dmitrijus could you check this for DQM please?

**Comment by dmitrijus** [comment]
I will, in the coming few days - there was a BMTF related memory leak I noticed online. I will provide more comments about it :)

**Comment by thomreis** [comment]
The leak in the BMTF unpacker or another one? The former is also tracked here https://github.com/cms-l1t-offline/cmssw/issues/423

**Comment by dmitrijus** [comment]
BMTF unpacker. I have commented on that issue.

**Comment by thomreis** [comment]
@dmitrijus since this has nothing to do with the BMTF leak could we proceed with the steps to merge it?

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
