### PR TITLE
Hcal Parameters Schema Update v2

### PR DESCRIPTION
**Pull request by ianna**
- Merge and rebase remaining changes from Sunanda
- Update Hcal parameters schema ti include recalculated eta table for HF

### CODE REVIEW

**Comment by ianna** [comment]
@bsunanda - to speed integration up I've merged remaining changes from your PR #9994 and #10077 and updated Hcal parameters schema to include recalculated eta table for HF. Please, check that nothing is missing. Thanks.

**Comment by ianna** [comment]
@cmsbuild please test

**Comment by ianna** [comment]
+1

**Comment by ggovi** [comment]
+1

**Comment by ianna** [comment]
@cmsbuild - why labels are not updated yet?

**Comment by ianna** [comment]
@davidlange6 - please, bring this up at ORP - we need it in IBs ASAP.

**Comment by ianna** [comment]
@mmusich - please, have a look and sign. Thanks.

**Comment by mmusich** [comment]
+1

**Comment by ianna** [comment]
@davidlange6 - this PR is needed in pre1 to update DropBox. Thanks.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
