### PR TITLE
Added consumes to RecoLocalFastTime packages

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

Also uses ESGetToken to obtained the data.

#### PR validation:

Ran workflows 20434.0, 21234.0, and 22034.0

### CODE REVIEW

**Comment by Dr15Jones** [comment]
needed for #28223

**Comment by Dr15Jones** [comment]
please test

**Comment by perrotta** [comment]
+1
- Technical
- Jenkins tests pass

**Comment by kpedro88** [comment]
+upgrade

**Comment by Dr15Jones** [comment]
@fabiocos once this gets merged into master, I can restart the test for #28223. As far as my test show, this is the last change needed to make #28223 work cleanly.

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
@Dr15Jones integrated for next IB

**Comment by kpedro88** [comment]
```
----- Begin Fatal Exception 05-Nov-2019 04:35:23 CET-----------------------
An exception of category 'MustUseESGetToken' occurred while
   [0] Processing  Event run: 1 lumi: 1 event: 1 stream: 0
   [1] Running path 'p'
   [2] Calling method for module DDTestCompactView/'test'
   [3] Using EventSetup component DDCompactViewESProducer/'' to make data DDCompactView/'MUON' in record IdealGeometryRecord
Exception Message:
Called EventSetupRecord::get without using a ESGetToken.
 While requesting data type:DDDetector label:'MUON'
----- End Fatal Exception -------------------------------------------------
```

**Comment by Dr15Jones** [comment]
@pedro I'm right now fixing that code :)

**Pull request merged**
