### PR TITLE
Run2-TB38 Describes the 2018 DESY test beam setup for HGCal

### PR DESCRIPTION
**Pull request by bsunanda**
There are 4 cfi files corresponding to 4 setups with different absorber conditions

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by kpedro88** [comment]
+1

**Comment by ianna** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by fabiocos** [comment]
+1

addition of new configurations

**Pull request merged**
