### PR TITLE
75X: realistic BS for PbPb 2015 simulation

### PR DESCRIPTION
**Pull request by mmusich**
Was in #15225:  _Realistic vertex smearing for 2015 PbPb MC (75X)_ 
- Updated the vertex smearing based on final beamspot fits to the data (taking into account the shift of the pixel detector). 
- The corresponding reco beamspot has been placed in the GT key `run2_mc_hi`, following request: [HN](https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2538.html)
- Since the reco beamspot tag is in place, the HI reco relval workflow has been updated to use this vertex smearing.

attn: @mandrenguyen @jrcastle
# Summary of changes in Global Tags
## RunII simulation
- **RunII Heavy Ions scenario** : [75X_mcRun2_HeavyIon_v14](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/75X_mcRun2_HeavyIon_v14) as [75X_mcRun2_HeavIon_v13](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/75X_mcRun2_HeavIon_v13) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/75X_mcRun2_HeavyIon_v14/75X_mcRun2_HeavIon_v13): 
  - updated retune of the RECO BS for 2015 PbPb MC

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
+1

**Pull request merged**
