### PR TITLE
Updated configurations in Reco* to new MessageLogger syntax

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

All configurations in Reco* subsystems which explicitly create a MessageLogger have been converted to the new syntax.
#### PR validation:

All files were passed to `python` and no failures as a result of these change were seen.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by kpedro88** [comment]
+upgrade

**Review by jpata — COMMENTED** [review]
+reconstruction

- updates MessageLogger configs in Reco* packages (all are in /test/ or /validation/ files)
- I've checked by eye and all the changes look reasonable to me
- no changes expected or observed

**Comment by slava77** [comment]
> +reconstruction

I suspect that this was entered not as a regular comment but instead as a review and the bot is not parsing/collecting +1s from reviews

**Comment by jpata** [comment]
ah, good to know, fixing.

**Comment by jpata** [comment]
+reconstruction

    updates MessageLogger configs in Reco* packages (all are in /test/ or /validation/ files)
    I've checked by eye and all the changes look reasonable to me
    no changes expected or observed

**Comment by silviodonato** [comment]
kind reminder @cms-sw/alca-l2

**Comment by yuanchao** [comment]
+1
* modifications only on python configuration
* python build OK
* matrix tests and unit tests all passed
* static check build error/warnings are not part of the modification

**Comment by silviodonato** [comment]
+1

**Pull request merged**
