### PR TITLE
NanoAOD developments: 190520 version, part 2 for UL [106X]

### PR DESCRIPTION
**Pull request by peruzzim**
backport of #26844 

Warning: this PR includes #26786 - a conflict with the HEAD of that PR is fixed here
Depends on #26847, and cms-sw/cmsdist#4996

### CODE REVIEW

**Comment by peruzzim** [comment]
please test workflow 1325.6,1325.7,1325.8,1329.1,136.7722,136.7952,136.8521 with #26847, cms-data/PhysicsTools-NanoAOD#6

**Comment by mrodozov** [comment]
please test workflow 1325.6,1325.7,1325.8,1329.1,136.7722,136.7952,136.8521 with #26847, https://github.com/cms-sw/cmsdist/pull/4996

**Comment by peruzzim** [comment]
please test workflow 1325.6,1325.7,1325.8,1329.1,136.7722,136.7952,136.8521 with #26847, cms-sw/cmsdist#4996

**Comment by peruzzim** [comment]
+xpog

sorry I had forgotten to sign also this backport

**Comment by perrotta** [comment]
+1
- Reconstruction only enters through what is imported from #26786, already signed by reco
- Overall this PR includes completely and update/supersede #26786, which should therefore get closed and replaced by this one

**Comment by santocch** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
