### PR TITLE
Fix needed by classes derived from virtual jet producer

### PR DESCRIPTION
**Pull request by perrotta**
bug-fix of #19098

This should fix the errors in the HI Jet Producers which inherits from VirtualJetProducer by:
- adding the missing parameters in the fillDescription() method of the base class;
- restoring the local src_ variable in VirtualJetProducer, which is needed in the derived classes

@alefisico @Martin-Grunewald @fwyzard @silviodonato

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
type bug-fix

**Comment by perrotta** [comment]
+1
Bug fix tested (also) with HI wfs 301 and 302

**Comment by davidlange6** [comment]
+1

**Pull request merged**
