### PR TITLE
Incremented GenParticle version number for storage

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:
This is needed for the forward porting for ultra legacy processing and is something we should have done anyway says Philippe Canal.

#### PR validation:

Ran simple jobs to create simulation files which were then read in CMSSW_9_4 as a test of the ultra legacy processing.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by fabiocos** [comment]
@efeyazgan @qliphy @alberto-sanchez did you check this PR? Do you see any issue with this?

**Comment by efeyazgan** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
