### PR TITLE
propagation of hcal geometry changes for the csc halo algo

### PR DESCRIPTION
**Pull request by zdemirag**
Related PRs are: 
* https://github.com/cms-sw/cmssw/pull/20289
* https://github.com/cms-sw/cmssw/pull/19910

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by slava77** [comment]
if this changes reco/miniAOD outputs, this PR will likely be rejected for 92X.

**Comment by perrotta** [comment]
This goes together with #20289: they will likely be both rejected in  
92X, but if one really decides to integrate them in 92X then it is  
probably more convenient to merge them into a single PR


Slava Krutelyov <notifications@github.com> ha scritto:

**Comment by kpedro88** [comment]
@slava77 @perrotta - so we are forced to have buggy prompt reco/miniAOD forever this year?

**Comment by kpedro88** [comment]
backport of #20309

**Comment by davidlange6** [comment]
forever is until 940 is done. that is the request as communicated to me. Obviously physics can be convinced to change their mind.

**Comment by slava77** [comment]
Is it just me or did others start missing the github thread by responding in email client?
[the following was sent yesterday]

**Comment by slava77** [comment]
-1
based on comments in #20308, this appears to be non-essential for 92X

**Pull request closed without merging**
