### PR TITLE
Fix ODR violation in BaseKeyed serialization

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

Combined the different implementation of the same tempalte function specialization into one function.
Register the SerializationHelper only once.

#### PR validation:

Code compiles.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by tvami** [comment]
> CondCore/BaseKeyedPlugins (****)

I think @smuzaffar was very much against having small packages in `CondCore` so adding one more might not be the best solution. Couldnt this be under `CondCore/BaseKeyedPlugins` and the DTs would use it from there?

**Comment by Dr15Jones** [comment]
@tvami 
> Couldnt this be under CondCore/BaseKeyedPlugins and the DTs would use it from there?

It is under `BaseKeyedPlugins` so I'm guessing you might have miss typed the name of the package you were suggesting?

**Comment by Dr15Jones** [comment]
@smuzaffar your thoughts? The reason I created `BaseKeyedPlugins` is to avoid unnecessary coupling between the CalibPlugins and DTPlugins packages plus if additional classes ever inherit from `BaseKeyed` then the new package is where one would add the new code needed for the serialization. I.e. this solution gives the best package dependency structure.

**Comment by tvami** [comment]
> It is under `BaseKeyedPlugins` so I'm guessing you might have miss typed the name of the package you were suggesting?

Oh yes I did mistype, sorry, I meant to have it only in `CondCore/CalibPlugins ` and use it from there in the DT case. `CalibPlugins` sounds general enough for me to be usable for any future packages too.

**Comment by Dr15Jones** [comment]
The base class is a special ability of the DB, not something specific to Calo. So a future extension could come from a whole different detector group.

**Comment by smuzaffar** [comment]
@Dr15Jones @tvami , as `CondCore/BaseKeyedPlugins` only generates an edm plugin so there is no real build/link time dependency between this and `Calib` `DT` plugins. Following the existing logic of plugins in `CondCore` , I am fine with adding it in `CondCore/BaseKeyedPlugins`.

At some point we should address https://github.com/cms-sw/cmssw/issues/40212

**Comment by perrotta** [comment]
I have assigned the new package to DB in https://github.com/cms-sw/cms-bot/pull/2041

**Comment by perrotta** [comment]
+db

**Comment by perrotta** [comment]
+1

**Pull request merged**
