### PR TITLE
Fastsim era global validation2

### PR DESCRIPTION
**Pull request by lveldere**
will comment later,
piles up a few earlier pull requests,
needs a rebase once these are approved.

### CODE REVIEW

**Comment by lveldere** [comment]
please test

**Comment by slava77** [comment]
@lveldere #12403 is merged already and can be removed from this PR; the #12320 #12335 should probably be closed

**Comment by lveldere** [comment]
closing, until prior pull request are merged.

**Comment by lveldere** [comment]
No changes observed, except for the Generator directory.
Changes in the generator directory are expected:
FastSim now runs the standard Generator Harvesting,
which takes care of the normalisation of distributions.

**Comment by lveldere** [comment]
rebased, 
fixed a few typos

**Comment by lveldere** [comment]
replaced by #12642

**Pull request closed without merging**
