### PR TITLE
Removed unnecessary xz dependency from GeneratorProducts

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

The dependency is not needed for compiling or linking.

#### PR validation:

Code compiles and links.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
@cms-sw/generators-l2 please review

**Comment by Dr15Jones** [comment]
@cms-sw/orp-l2 could you please bypass the generator signature? This is purely a technical change and the L2s are not responding.

**Comment by Dr15Jones** [comment]
@cms-sw/orp-l2 It has been two weeks, please override the generator signature.

**Comment by antoniovilela** [comment]
merge

**Pull request merged**
