### PR TITLE
Migration of HLT to 1010 template (101X)

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
Migration of HLT to 1010 template (101X)
Based on CMSSW_10_1_0.

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
backport of #22825

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
test missed last update

**Comment by Martin-Grunewald** [comment]
please test

**Comment by fabiocos** [comment]
+1

**Pull request merged**
