### PR TITLE
Update errorScale for BeamSpot Legacy DQM client

### PR DESCRIPTION
**Pull request by francescobrivio**
#### PR description:
Forward-port of #38618 (12_3_X PR)
This PR updates the `errorScale` parameter from 1.22 to 1.0, see the 12_3_X PR for more details

#### PR validation:
The 12_3_X PR (#38618) deployed in production in Fill 7923 shows the beamspot legacy client properly working, see https://github.com/cms-sw/cmssw/pull/38618#issuecomment-1177181758 and https://github.com/cms-sw/cmssw/pull/38618#issuecomment-1177367536

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:
Forward port of #38618 
Backports to 12_4_X and 12_3_X will be provided

### CODE REVIEW

**Comment by francescobrivio** [comment]
@cmsbuild please test

**Comment by francescobrivio** [comment]
+db

 - verbatim forward-port of the 12_3_X PR which is already in production

**Comment by perrotta** [comment]
@cms-sw/dqm-l2 you signed the backport version of this PR, and not this one in the master: should I give the signature here for granted and bypasss it, or is there any reason for not signing this onw?

**Comment by perrotta** [comment]
+1
- Identical to #38618, succesfully tested in 12_3_X at P5 and already signed by @cms-sw/dqm-l2 in that cycle

**Comment by emanueleusai** [comment]
apologies for whatever reason I missed this in our PR tracking tool

**Comment by emanueleusai** [comment]
+1

**Pull request merged**
