### PR TITLE
Hot Strip algorithm updated

### PR DESCRIPTION
**Pull request by suchandradutta**
Updating Hot Strip algorithms in CalibTracker/SiStripQuality putting extra requirement on the strip Digi wrt APV median as developed by Mario Galanti + Message logger ourput made more logical in DQMOffline/CalibTracker/plugins/SiStripQualityHotStripIdentifierRoot.cc

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by deguio** [comment]
+1

**Comment by gbenelli** [comment]
Ping! Can we get the new algorithm merged so that it can be used in PCL@T0? Thanks!

**Comment by mmusich** [comment]
+1
for  https://github.com/suchandradutta/cmssw/commit/a9aad99a7555176e50aa9e993d7aaa36b2e1f77d (backport of #9982)
Visual inspection of the code w.r.t 76X changes OK.

**Comment by mmusich** [comment]
@gbenelli @suchandradutta it might be worth to test the PCL workflow in 76X where the PR is already merged and show that everything looks ok as expected before merging for production. It should be included in the test WF 1001.0 in the matrix.

**Comment by suchandradutta** [comment]
I have used runTheMatrix.py with  WF 1001.0 in 76X IB. The work flow went through without any problem. But the actual algorithm did not trigger due to too few events.

**Comment by mmusich** [comment]
@suchandradutta thanks. This was expected since the test is run automatically in from cms-bot. I was referring to repeating the steps with more statistics (you can customize the cmsDriver command) to see it actually triggers the calibration and compare the payload you obtain with your expectations. Thanks.

**Comment by suchandradutta** [comment]
@mmusich after running the default work flow with 100 events, I did try it  with 10000 events. But I saw that the DQM file produced after step4 was basically empty. I am trying it out again.

Anyway I have tested the algorithm (with and without new addition) in 74X using ALCAPrompt dataset of recent runs and verified that it works.

**Comment by suchandradutta** [comment]
@mmusich my statement was not correct! Using work flow 1001.1 in runTheMatrix in the IB CMSSW_7_6_X_2015-07-08-2300 (out of the box) I do not get any sub-system folders in the DQM file (after step 4 harvesting). So even if I get following message at the end of my test 
> 1 1 1 1 tests passed, 0 0 0 0 failed
the test is not successful!

**Comment by davidlange6** [comment]
+1

**Pull request merged**
