### PR TITLE
HLT menu update to V1.2 (Kerberos) - 93X

### PR DESCRIPTION
**Pull request by silviodonato**
This is an update of the HLT menu to v1.2 (Kerberos).
It is based on master table: /dev/CMSSW_9_2_0/HLT/V83

### CODE REVIEW

**Comment by silviodonato** [comment]
please test

**Comment by Martin-Grunewald** [comment]
Based on CMSSW_9_3_X_2017-06-26-2300.

**Comment by silviodonato** [comment]
I'm confused. This customization function
https://github.com/cms-sw/cmssw/blob/master/HLTrigger/Configuration/python/customizeHLTforCMSSW.py#L176
should set `ClusterThreshold = cms.int32(4000)` in all `SiPixelClusterProducer` modules.
But I'm getting error https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-19444/20938/addOnTests/hlt_data_GRun/cmsRun__build_cmsbld_jenkins-workarea_workspace_ib-any-integration_CMSSW_9_3_X_2017-06-26-2300_src_HLTrigger_Configuration_test_OnLine_HLT_GRun.py_rea.log
`%MSG-i ThreadStreamSetup:  (NoModuleName) 27-Jun-2017 14:10:18 CEST pre-events
setting # threads 4
setting # streams 4
%MSG
DQMStore: MultiThread option is enabled
27-Jun-2017 14:10:30 CEST  Initiating request to open file file:RelVal_Raw_GRun_DATA.root
27-Jun-2017 14:10:31 CEST  Successfully opened file file:RelVal_Raw_GRun_DATA.root
27-Jun-2017 14:10:59 CEST  Closed file file:RelVal_Raw_GRun_DATA.root
----- Begin Fatal Exception 27-Jun-2017 14:10:59 CEST-----------------------
An exception of category 'Configuration' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing module: class=SiPixelClusterProducer label='hltSiPixelClusters'
Exception Message:
ValueError type of ClusterThreshold is expected to be int but declared as double
----- End Fatal Exception -------------------------------------------------`

**Comment by silviodonato** [comment]
Mistake found, sorry for the noise.

**Comment by silviodonato** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by Martin-Grunewald** [comment]
hold

**Comment by Martin-Grunewald** [comment]
unhold

**Comment by davidlange6** [comment]
+1

**Pull request merged**
