### PR TITLE
Adding GEN fragment (GluGluTo2Jets_ExHume) specific for PPS wf testing 

### PR DESCRIPTION
**Pull request by mundim**
#### PR description:

Putting back changes issued in the PR #32765 (in the gen GluGlu gen fragment with updated/corrected SM parameters and insertion of the wf ID in relval_2017.py file) that was accidentally removed. 

#### PR validation:

All validation already done in the PR #32765

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by silviodonato** [comment]
please test

**Comment by silviodonato** [comment]
abort

**Comment by silviodonato** [comment]
please test workflows 11725.0,11925.0

**Comment by silviodonato** [comment]
test parameters:
- workflows = 11725.0,11925.0

**Comment by silviodonato** [comment]
please test
@cms-sw/pdmv-l2 @cms-sw/generators-l2 @cms-sw/upgrade-l2 
Do you have any comment?
The differences should be unrelated to this PR.
The errors are expected, we will need to generate the new GEN-SIM for runTheMatrix once this PR is merged (@cms-sw/pdmv-l2)

**Comment by chayanit** [comment]
+1
OK

**Comment by agrohsje** [comment]
No objections. 
+1

**Comment by agrohsje** [comment]
+generators

**Comment by srimanob** [comment]
+Upgrade

**Comment by qliphy** [comment]
+1

**Comment by qliphy** [comment]
merge

**Comment by chayanit** [comment]
Why the new workflow is not added here in this PR? @mundim https://github.com/CTPPS/cmssw/blob/66dad2191b4ed343b447b14c983e4eb0752b2345/Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py#L1355

**Comment by qliphy** [comment]
> Why the new workflow is not added here in this PR? @mundim https://github.com/CTPPS/cmssw/blob/66dad2191b4ed343b447b14c983e4eb0752b2345/Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py#L1355

This was added by https://github.com/cms-sw/cmssw/pull/32868

**Comment by mundim** [comment]
Hi @chayanit, @silviodonato , others
Sorry for not been too responsive in the last couple of weeks. I was really overloaded and trying to to several things at the same time and made some (maybe lot) of mistakes. I really appreciate the help you all have done.

So, do I need to issue a new PR with the correct (and complete) modifications in all related files? 
Once again, sorry for any trouble...

**Comment by qliphy** [comment]
@mundim   No need to open a new PR for the moment.  We need to wait for PdmV to update the GS string in 11_3_X, which will happen not soon.
https://github.com/cms-sw/cmssw/issues/33010#issuecomment-787475105

**Pull request merged**
