### PR TITLE
Energy correction

### PR DESCRIPTION
**Pull request by archiron**
minor modification into histo name "Total basicclusters corrected energy" instead of "Total basicclusters energy" and computation (with correctedEnergy() instead of energy() )
minor modifications to be OK with the efficiency flag
minor corrections with histos placement into the web page.

@beaudett

### CODE REVIEW

**Comment by deguio** [comment]
ciao @archiron 
this PR doesn't merge anymore. please rebase it on top of a recent IB in 75.
thanks,
F.

**Comment by danduggan** [comment]
@archiron, it looks like you'll need to clean up lines 20-23 in Validation/RecoEgamma/python/ElectronMcSignalValidator_cfi.py

**Comment by deguio** [comment]
-1
rejecting for now

**Comment by archiron** [comment]
lines have been corrected in Validation/RecoEgamma/python/ElectronMcSignalValidator_cfi.py (seems to be due to malformed git update).

**Comment by danduggan** [comment]
please test

**Comment by deguio** [comment]
please test

**Comment by archiron** [comment]
does not seems to be mine. tests seems OK on my side :+1: 4.22_RunCosmics2011A+RunCosmics2011A+RECOCOSD+ALCACOSD+SKIMCOSD+HARVESTDC Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Thu May 28 17:35:06 2015-date Thu May 28 17:29:50 2015; exit: 0 0 0 0 0
1 1 1 1 1 tests passed, 0 0 0 0 0 failed

5.1_TTbar+TTbarFS+HARVESTFS Step0-PASSED Step1-PASSED  - time date Thu May 28 17:38:51 2015-date Thu May 28 17:35:06 2015; exit: 0 0
1 1 tests passed, 0 0 failed

135.4_ZEE_13+ZEEFS_13+HARVESTUP15FS+MINIAODMCUP15FS Step0-PASSED Step1-PASSED Step2-PASSED  - time date Thu May 28 17:46:05 2015-date Thu May 28 17:38:52 2015; exit: 0 0 0
1 1 1 tests passed, 0 0 0 failed

Preparing to run 8.0 BeamHalo+BeamHalo+DIGICOS+RECOCOS+ALCABH+HARVESTCOS
8.0_BeamHalo+BeamHalo+DIGICOS+RECOCOS+ALCABH+HARVESTCOS Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Thu May 28 17:50:07 2015-date Thu May 28 17:46:06 2015; exit: 0 0 0 0 0
1 1 1 1 1 tests passed, 0 0 0 0 0 failed

140.53_RunHI2011+RunHI2011+RECOHID11+HARVESTDHI Step0-PASSED Step1-PASSED Step2-PASSED  - time date Thu May 28 17:58:30 2015-date Thu May 28 17:50:07 2015; exit: 0 0 0
1 1 1 tests passed, 0 0 0 failed

4.53_RunPhoton2012B+RunPhoton2012B+HLTD+RECODreHLT+HARVESTDreHLT+MINIAODDreHLT Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Thu May 28 18:12:08 2015-date Thu May 28 17:58:31 2015; exit: 0 0 0 0 0
1 1 1 1 1 tests passed, 0 0 0 0 0 failed

1306.0_SingleMuPt1_UP15+SingleMuPt1_UP15+DIGIUP15+RECOUP15+HARVESTUP15+MINIAODMCUP15 Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Thu May 28 18:20:35 2015-date Thu May 28 18:12:09 2015; exit: 0 0 0 0 0
1 1 1 1 1 tests passed, 0 0 0 0 0 failed

101.0_SingleElectronE120EHCAL+SingleElectronE120EHCAL Step0-PASSED  - time date Thu May 28 18:22:45 2015-date Thu May 28 18:20:36 2015; exit: 0
1 tests passed, 0 failed

1000.0_RunMinBias2011A+RunMinBias2011A+TIER0+SKIMD+HARVESTDfst2+ALCASPLIT Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Thu May 28 18:30:47 2015-date Thu May 28 18:22:46 2015; exit: 0 0 0 0 0
1 1 1 1 1 tests passed, 0 0 0 0 0 failed

1001.0_RunMinBias2011A+RunMinBias2011A+TIER0EXP+ALCAEXP+ALCAHARVD Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED  - time date Thu May 28 18:35:50 2015-date Thu May 28 18:30:49 2015; exit: 0 0 0 0
1 1 1 1 tests passed, 0 0 0 0 failed

1330.0_ZMM_13+ZMM_13+DIGIUP15+RECOUP15+HARVESTUP15+MINIAODMCUP15 Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Thu May 28 18:47:34 2015-date Thu May 28 18:35:51 2015; exit: 0 0 0 0 0
1 1 1 1 1 tests passed, 0 0 0 0 0 failed

9.0_Higgs200ChargedTaus+Higgs200ChargedTaus+DIGI+RECO+HARVEST Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED  - time date Thu May 28 18:59:38 2015-date Thu May 28 18:47:35 2015; exit: 0 0 0 0
1 1 1 1 tests passed, 0 0 0 0 failed

1003.0_RunMinBias2012A+RunMinBias2012A+RECODDQM+HARVESTDDQM Step0-PASSED Step1-PASSED Step2-PASSED  - time date Thu May 28 19:07:04 2015-date Thu May 28 18:59:38 2015; exit: 0 0 0
1 1 1 tests passed, 0 0 0 failed

25.0_TTbar+TTbar+DIGI+RECO+HARVEST+ALCATT Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Thu May 28 19:20:34 2015-date Thu May 28 19:07:05 2015; exit: 0 0 0 0 0
1 1 1 1 1 tests passed, 0 0 0 0 0 failed

25202.0_TTbar_13+TTbar_13+DIGIUP15_PU25+RECOUP15_PU25+HARVESTUP15_PU25+MINIAODMCUP15 Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Thu May 28 19:45:58 2015-date Thu May 28 19:20:34 2015; exit: 0 0 0 0 0
1 1 1 1 1 tests passed, 0 0 0 0 0 failed

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
