### PR TITLE
Phase2-hgx86 Fix the bug for overwriting (backport from 9_2_X #19198)

### PR DESCRIPTION
**Pull request by bsunanda**
Use correct # for maximum wafers

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by kpedro88** [comment]
+1

**Comment by kpedro88** [comment]
Backport of #19198

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by kpedro88** [comment]
+1

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/19209	9b8b88a
- the same change (ignoring whitespaces) as in 92X version https://github.com/cms-sw/cmssw/pull/19198	84a5122
- jenkins tests pass and comparisons show no differences

**Comment by davidlange6** [comment]
+1

**Pull request merged**
