### PR TITLE
Add L1 offline DQM harvesting step - 92x

### PR DESCRIPTION
**Pull request by thomreis**
Add L1 offline DQM harvesting step to all sequences where the first step is also run.

In particular this should produce efficiency histograms for the express stream reco, where currently only the first step DQM histograms are produced.

### CODE REVIEW

**Comment by thomreis** [comment]
backport of #20313

**Comment by dmitrijus** [comment]
+1

**Comment by dmitrijus** [comment]
+1

**Comment by thomreis** [comment]
@davidlange6 can this be merged please to be ready in the next release at the T0?
it is filly signed and the 94x version is merged for a week already.

**Comment by rekovic** [comment]
@dmitrijus 
please sign.  94x version #20313 has been integrated for a while.

**Comment by rekovic** [comment]
sorry @dmitrijus, the message was for David.

@davidlange6 Can we have this merged please.

**Comment by thomreis** [comment]
Hi @davidlange6 
What keeps this from being merged?

**Comment by thomreis** [comment]
Hi @davidlange6 , what can we do to speed up the integration of this PR?

**Comment by rekovic** [comment]
@thomreis 
As mentioned to you on Thursday, discussed this with @davidlange6, there should be no show-stoppers.  I am sure he will merge it at the earliest convenience.

**Comment by thomreis** [comment]
It is fully signed for almost four weeks. There has been a CMSSW_9_2 release in the meantime that is now running at the T0. This PR could have been in there too and our shifters could have a better tool for data certification already. I do not see why this needs to take so long.

**Comment by davidlange6** [comment]
Apologies - had I remembered, it would be in 9_2_13. I've added a note in the release meeting so that it will be remembered as part of the next release (of course Vladimir and Dmitrijus should do that as well). Otherwise we're more focused on 94x at this point of the run.

**Comment by thomreis** [comment]
Thank you. I understand that 94x is the hot topic at the moment but there are other PRs to releases that some people care about as well.

**Comment by davidlange6** [comment]
yes - thats why we have weekly meetings where groups are asked to write their input (so that one does not have rely on my memory..) - Now I've entered the needed information into the member notes (not that it should be done by me)

**Comment by thomreis** [comment]
I see. I was told that this has been done already for a previous meeting.

**Comment by davidlange6** [comment]
merge

**Pull request merged**
