### PR TITLE
bsunanda:Run2-hcx74 Add scenario to help testing 2016 HCAL setup

### PR DESCRIPTION
**Pull request by bsunanda**
This enables to equip the DB with the right set of constants to test 2016 geometry of HCAL

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by ianna** [comment]
@bsunanda and @davidlange6 - I'd suggest to keep all scenarios in Configuration/Geometry for validation purposes.

**Comment by davidlange6** [comment]
Right - I think we had agreed already on having a scenario for 2017 development for HCAL - can it be used instead?

**Comment by bsunanda** [comment]
I can move to Configuration/Geometry; but David did not want to have two scenarios for 2016. HCAL wants to work with additional channels in 2016 to work with 2016 data and test the code. 2016 (with the additional channels) and 2017 geometries are different for HCAL and each has to be present to serve some purpose. After several discussions within HCAL software group, we came to the following conclusions:
 o preserve the 2016 default geometry which has additional 1x1 HF Trigger Primitives
 o Have 2016 Geometry which has in addition provision for 24 HF channels
 o 2017 Geometry for HCAL which has all HF readout with split multi-anode; HE's with SiPM and additional depth segments and HF trigger primitives dropping the 2x3 and have only 1x1. (which is in 2017Dev)
In light of this we could make 2016Dev for the second item
________________________________

**Comment by civanch** [comment]
@bsunanda , it seems that to put a new scenario to another place is not a good solution - if a new scenario is needed for short or for long time it should be indeed in the same place.

**Comment by bsunanda** [comment]
I understand this. I am resubmitting this by moving it to the usual place with a name GeometryExtend2016Dev. I hope David will allow this.
________________________________

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by ianna** [comment]
+1

**Comment by kpedro88** [comment]
@bsunanda: Could you also define Extended2016dev in https://github.com/cms-sw/cmssw/blob/CMSSW_8_1_X/Configuration/StandardSequences/python/GeometryConf.py ? Otherwise, cmsDriver does not know how to set the geometry.

**Comment by ianna** [comment]
@kpedro88 - you can always give a comma separated file names:
```
--geometry "Configuration.Geometry.GeometrySimHCAL_cff,Configuration.Geometry.GeometryRecoHCAL_cff"
```

**Comment by kpedro88** [comment]
@ianna - Thanks, I did not know that option was available.

**Comment by davidlange6** [comment]
+1

**Comment by abdoulline** [comment]
Is there a chance we could backport it to 80X? 
Than matter is that actual data (with QIE10 reworked PMT box) is being taken and needs to be analysed using 802...

**Comment by bsunanda** [comment]
I shall make a request.
________________________________

**Pull request merged**
