### PR TITLE
Changes to enable new DeepTauId trainig [12_4_X]

### PR DESCRIPTION
**Pull request by mbluj**
#### PR description:
**This PR is a clone of #37892**, i.e. it is created with the same development branch. Full description of the original PR is repeated below for convenience.

This PR adapts DeepTauId producer to a new v2p5 training. The changes are not significant since the architecture and data preprocessing has not changed much structurally compared to previous version. The changes include:
* unification of the interface for scaling (aka standardization) of inputs across subversions and reading of scaling constants from a separate namespace,
* functionality to drop specific global variables from a general list (TauBlockInputs),
* adaptation of runTauIdMVA.py tool,
* new `deepTauId2018v2p5` producer added to the miniAOD workflow and its products (three raw tauIDs) stored in the `slimmedTaus` collection.

Full list of adaptations needed for the v2p5 can be found here: [cms-tau-pog/TauMLTools/issues/99](https://github.com/cms-tau-pog/TauMLTools/issues/99).

In addition this PR consists of changes to DFIsolation producer (1st version of tauID based on DNN) which adapts the producer to changes in base class (previously overlooked).

**Note:** this PR requires new training files being added to cms-data by https://github.com/cms-data/RecoTauTag-TrainingFiles/pull/8.

#### PR validation:

Standard tests, i.e. `runTheMatrix.py -l limited -i all --ibeos`, passed successfully.

Backward-compatibility checks: updated CMSSW code fully reproduces predictions of previous version (v2p1) of deepTauId.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Backport of #37892.

Enables new training of deepTauID which is meant to be dafulat for 2022 data taking.

### CODE REVIEW

**Comment by jpata** [comment]
@cmsbuild please test

**Comment by mbluj** [comment]
Could it be that the test failures are caused by the fact that new  deepTau model files are not propagated to IB yet despite of the fact that the Corresponding PR is already merged (https://github.com/cms-data/RecoTauTag-TrainingFiles/pull/8)?

**Comment by perrotta** [comment]
test parameters:
- pull_request = https://github.com/cms-data/RecoTauTag-TrainingFiles/pull/8

**Comment by perrotta** [comment]
@cmsbuild please test

**Comment by perrotta** [comment]
@smuzaffar could you please remind me how to make a backport of the cmsdist https://github.com/cms-sw/cmsdist/pull/7876 to 12_4? Then I'll take note of it, and I won't ask you any more...

**Comment by smuzaffar** [comment]
@perrotta , you can try running https://cmssdt.cern.ch/jenkins/job/backport-pull-request/lastCompletedBuild/rebuild/parameterized with
```
REPOSITORY=cms-sw/cmsdist
BRANCH=IB/CMSSW_12_4_X/master
PULL_REQUEST=7876
```
which sometimes fails as bot can not automatically merge changes. If this does not work then you can just open a PR to update https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_12_4_X/master/data/cmsswdata.txt#L34 ( i.e. for IB/CMSSW_12_4_X/master branch) with the correct tag.

**Comment by perrotta** [comment]
> @perrotta , you can try running https://cmssdt.cern.ch/jenkins/job/backport-pull-request/lastCompletedBuild/rebuild/parameterized with
> 
> ```
> REPOSITORY=cms-sw/cmsdist
> BRANCH=IB/CMSSW_12_4_X/master
> PULL_REQUEST=7876
> ```
> 
> which sometimes fails as bot can not automatically merge changes. If this does not work then you can just open a PR to update https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_12_4_X/master/data/cmsswdata.txt#L34 ( i.e. for IB/CMSSW_12_4_X/master branch) with the correct tag.

Indeed...
Thank you @smuzaffar 
A new cmsdist is made as https://github.com/cms-sw/cmsdist/pull/7877, which is currently tested together with this PR

**Comment by jpata** [comment]
+reconstruction
- a direct backport of https://github.com/cms-sw/cmssw/pull/37892
- the no-change rule is not applied: agreed at the ORP on Tuesday to accommodate TAU for 12_4_0

**Comment by qliphy** [comment]
+1
tested also in https://github.com/cms-sw/cmsdist/pull/7877

**Pull request merged**
