### PR TITLE
[Phase-2] [14_1_X] Configuration for Phase-2 HLT path validation

### PR DESCRIPTION
**Pull request by SohamBhattacharya**
This PR adds the configuration for Phase-2 HLT path validation (see issue #44761).
Tested locally that it produces an output file with path efficiencies.

No changes are expected from this PR.

### CODE REVIEW

**Comment by mmusich** [comment]
please test
   * albeit there is nothing to test

**Comment by swagata87** [comment]
Does the pt range for egamma ends at 150 GeV in this validation? For following HLT paths, we need to extend that.. 
   ```
        "HLT_Photon108EB_TightID_TightIso_L1Seeded",
        "HLT_Photon108EB_TightID_TightIso_Unseeded",
        "HLT_Photon187_L1Seeded",
        "HLT_Photon187_Unseeded"
   ```
  If you use a Z'->EE sample (few TeV Z' mass), then its very convenient to get egamma objects of all pT range up to TeV scale (due to the off-shell component we also get the low/medium pT egamma)

**Comment by SohamBhattacharya** [comment]
Thanks for the tip on these paths.
Indeed, the configuration will need modification. This PR is just to get the paths into configuration first. We'll have to get the histogram binnings checked by the pogs.
This tool is quite dynamic, for example, it can have path specific bins too.

**Comment by mmusich** [comment]
+hlt
   * adds a standalone utility for the phase-2 HLT path validation
   * @SohamBhattacharya to make this more useful I guess this should be interlaced with the regular release validation configurations. Is there any plans about that?

**Comment by SohamBhattacharya** [comment]
> +hlt
> 
>     * adds a standalone utility for the phase-2 HLT path validation
> 
>     * @SohamBhattacharya to make this more useful I guess this should be interlaced with the regular release validation configurations. Is there any plans about that?

@mmusich yes, that is indeed the plan. I'll move this conversation on how to proceed with that, to #44761.

**Comment by mmusich** [comment]
@SohamBhattacharya please clarify if more updates to this branch are foreseen

**Comment by SohamBhattacharya** [comment]
> @SohamBhattacharya please clarify if more updates to this branch are foreseen

No, that's all for this PR.

**Comment by mmusich** [comment]
+hlt
   * see https://github.com/cms-sw/cmssw/pull/44776#issuecomment-2068776948

**Pull request merged**
