### PR TITLE
Phase2-hgx335P Take care of invalid HGCal scintillator DetIDs

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Take care of invalid HGCal scintillator DetIDs. The bug fix will affect both V16 and V17 geometries. 

#### PR validation:

Use scripts in Validation/HGCalValidation/script

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@srimanob @civanch Please approve this PR. After this I can address the cassette shift issue

**Comment by srimanob** [comment]
Hi @bsunanda 

Do I understand correctly from PR description is that this is a bug-fix PR, its effect should be seen in samples, i.e. relvals, since no change is seen in PR test. So that I can mark this PR as a bug-fix. Thanks.

**Comment by bsunanda** [comment]
@srimanob @civanch This is indeed a bug fix. Some of the borderline hits in scintillators were marked as invalid. This would have created a small change after Digi step.

**Comment by srimanob** [comment]
type bug-fix

**Comment by srimanob** [comment]
+Upgrade

This PR is a bugfix to handle for HGCal DetID. PR test does not show the difference. This should be followed up when relvals are available, together with effects from previous and coming PRs. FYI @cms-sw/pdmv-l2

**Comment by bsunanda** [comment]
+geometry

**Comment by civanch** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
