### PR TITLE
Get rid of hardcoded GEM fedid's

### PR DESCRIPTION
**Pull request by perrotta**
#### PR description:

While reviewing #33000 I noticed some hardcoded FEDID number for GEM's was introduced.
I did not want to delay further the merging of that PR, which contained a fix needed for the D76 Phase2 Geometry. 
Hardcoded ID's may give rise to errors in case of possible future updates/additions to the GEM mapping. 
Therefore, I'm preparing now this simple patch, which names somehow the starting point for the GE0 and GE21 FEDID's.

@jshlee @watson-ij please let me know if you agree with it: if not, I will close this (otherwise trivial) PR

#### PR validation:

It builds

### CODE REVIEW

**Comment by jshlee** [comment]
@perrotta this looks great! thank you

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
please test
(DAS errors do not depend on this PR)

**Comment by perrotta** [comment]
Unaccesible files in eos: annoying, but unrelated to the content of this PR...

**Comment by smorovic** [comment]
+1

**Comment by perrotta** [comment]
please test
(let try once again, hoping that input files are now accessible on eos)

**Comment by silviodonato** [comment]
@ggovi do you have any comments?

**Comment by ggovi** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
