### PR TITLE
Update SumEt, PFMET, PFMETNoMu, PFMHT, PFMHTNoMu. Add newly requested paths.

### PR DESCRIPTION
**Pull request by ndaci**
- Monitoring variables:
  -- SumEt defined as <PFMET>.SumEt()
  -- HT defined as <PFMHT>.SumEt()
  -- Add PFMETNoMu and PFMHTNoMu for Monojet trigger path validation
- Add newly requested trigger paths:

-- HTDisplacedJets
HLT_HT500_DisplacedDijet40_Inclusive_v1 (Signal 7 Hz)
HLT_HT350_DisplacedDijet40_DisplacedTrack_v1 (Signal 3 Hz)
HLT_VBF_DisplacedJet40_DisplacedTrack_v1 (Signal 4 Hz)
HLT_VBF_DisplacedJet40_Hadronic_v1 (Signal 4 Hz)
HLT_HT550_DisplacedDijet40_Inclusive_v1 (Backup 2 Hz)
HLT_HT350_DisplacedDijet80_DisplacedTrack_v1 (Backup 2 Hz)
HLT_VBF_DisplacedJet40_TightID_DisplacedTrack_v1 (Backup 3 Hz)
HLT_VBF_DisplacedJet40_TightID_Hadronic_v1 (Backup 2 Hz)

-- SingleMuon
HLT_Mu45_e2p1_v
HLT_Mu50_v

-- PhotonMET
HLT_Photon135_PFMET100_NoiseCleaned_v

### CODE REVIEW

**Comment by ndaci** [comment]
We just updated this PR with a few last-minute changes.
This includes a fix to the bug reported by @slava77 

Can we please get this PR merged asap ?
Some HLT JIRA tickets rely on it, with close deadlines for trigger paths integration.

Thanks!
The EXO trigger team.

**Comment by deguio** [comment]
+1

**Comment by ndaci** [comment]
Many thanks for the merge !
How can we create a PR for backport into 73X ?

**Comment by deguio** [comment]
ok.. I see that you managed..  :)

**Comment by ndaci** [comment]
Yes indeed :)

**Pull request merged**
