### PR TITLE
rebase PR10612 and PR10354

### PR DESCRIPTION
**Pull request by jingyucms**
Put changes in #10612  and #10354  together and make a new PR

### CODE REVIEW

**Comment by mulhearn** [comment]
please test

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1
provided it passes the tests

online + fix already merged in 74

**Comment by deguio** [comment]
-1
needs fix

**Comment by jingyucms** [comment]
Can you test again?

**Comment by mulhearn** [comment]
please test

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
-1
to be updated after discussion with @jingyucms. feel free to close and reopen when ready.
thanks,
F.

**Comment by jingyucms** [comment]
Temporarily close, waiting for new updates

**Pull request closed without merging**
