### PR TITLE
Validation/RecoMuon: potential bug endRun now called after changing parameters

### PR DESCRIPTION
**Pull request by gartung**
to fix clang warnings --  hides overloaded virtual function [-Woverloaded-virtual]

### CODE REVIEW

**Comment by gartung** [comment]
@Dr15Jones test please

**Comment by Dr15Jones** [comment]
please test

**Comment by gartung** [comment]
Unrelated failure

**Comment by davidlange6** [comment]
please test

**Comment by gartung** [comment]
@davidlange6 The test results do not appear to have been updated. When I click though to the logs they are the logs from 13Dec

**Comment by gartung** [comment]
Nevermind. I see that the tests are running and the link is to the old results.

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
