### PR TITLE
Hi conformal pixel tracks qa

### PR DESCRIPTION
**Pull request by HaoQiu**
Add hiConformalPixelTracks DQM for heavy ion run

### CODE REVIEW

**Comment by andrius-k** [comment]
Hi @HaoQiu, I can't seem t find you in the DQM contact list. Could you please introduce yourself briefly?

**Comment by BetterWang** [comment]
Hi @andrius-k , @HaoQiu is the Heavy Ion tracking POG release validator, as well as developer for the coming 2018 PbPb run. In the email sent in Sept 10th titled "Heavy Ion DQM developers", I included him in the cc but failed to introduce him. Sorry about that.

**Comment by jfernan2** [comment]
@BetterWang @HaoQiu For the future, can you please add @HaoQiu to the corresponding e-group in: 
https://twiki.cern.ch/twiki/bin/viewauth/CMS/DQMContacts#Heavy_Ions

**Comment by andrius-k** [comment]
please test

**Comment by fabiocos** [comment]
+1

late DQM tuning for HI data taking

**Pull request merged**
