### PR TITLE
[12.2.X] Refactoring gen weight storage in EDM + Nano integration

### PR DESCRIPTION
**Pull request by sroychow**
#### PR description:
Backport of #32167 

cc @kdlong

### CODE REVIEW

**Comment by sroychow** [comment]
please test

**Comment by perrotta** [comment]
backport of https://github.com/cms-sw/cmssw/pull/32167

**Comment by sroychow** [comment]
The file in question was introduced via #34169 . Discussing with @kdlong, we think is useful to backport the changes for lumi branch. Is it okay to be backported through this PR or we need to create another backport for 34169?

**Comment by sroychow** [comment]
hi @perrotta I meant the file ```PhysicsTools/NanoAOD/plugins/LumiOutputBranches.h```. 

Okay I shall proceed with backporting the other PR as well.

**Comment by perrotta** [comment]
As anticipated already several times during the ORP meetings, the 12_2_X and 12_3_X queues must be considered as closed. We consequently close this longstanding and apparently unattended PR, in order to clean up the queue. Please feel free to reopen it (with a valid justification) if you really think that it should be still merged, instead.

**Comment by kdlong** [comment]
This was back ported in anticipation of a test campaign for Nano v10, which was cancelled. So it's ok to close it, but we would still really like to have a similar test in another release if possible (@mariadalfonso )

**Pull request closed without merging**
