### PR TITLE
2017 Dev Scenario with Detailed Cavern

### PR DESCRIPTION
**Pull request by amagnani**
This is a first trial to implement a more realistic cavern description in the 2017 CMS geometry. This implementation will be used for the simulation of neutron background in the muon system. 
The cavern geometry was updated with the following elements imported from fluka v3.0.0.0:
- Electronics racks
- HF risers
- YB feet
- realistic implementation of the cavern floor
- elliptical cavern shape
- cavern shaft 
@ianna fixed major overlaps.

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
@civanch - please, compare G4 performance of 2017 vs 2017dev and let us know if the implementation needs optimisation.

**Comment by ianna** [comment]
+1

**Comment by Martin-Grunewald** [comment]
rebase needed!

**Comment by slava77** [comment]
-1

needs a rebase or similar to cleanup the commit history from irrelevant merges

**Pull request closed without merging**
