### PR TITLE
Validation/Geometry apply futurize stage1; use six.iteritems; use python3 for matplotlib

### PR DESCRIPTION
**Pull request by davidlange6**
To  hgcal scripts/unit tests. Likely this fixes one of the unit tests currently failing in the python3 builds.

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by davidlange6** [comment]
sorry, I forgot to commit one file..

**Comment by davidlange6** [comment]
please test

**Comment by jfernan2** [comment]
+1
Technical

**Comment by cvuosalo** [comment]
+1

**Comment by qliphy** [comment]
+1

**Comment by mrodozov** [comment]
please test for CMSSW_12_0_PY3_X

**Pull request merged**
