### PR TITLE
Clean up Unnecessary Direct Dependencies

### PR DESCRIPTION
**Pull request by ianna**
- Clean up unnecessary direct dependencies reported by libCheck

### CODE REVIEW

**Comment by ianna** [comment]
+1

**Comment by ianna** [comment]
@cmsbuild please test

**Comment by ianna** [comment]
@cmsbuild - the compilation error has nothing to do with this PR.

**Comment by ianna** [comment]
@cmsbuild please test

**Comment by ianna** [comment]
@cmsbuild - please, check which PR gives this error. It is not this one. Thanks.

**Comment by ianna** [comment]
@cmsbuild please test

**Comment by ianna** [comment]
+1

**Comment by mmusich** [comment]
+1
trivial changes

**Comment by smuzaffar** [comment]
@ianna , I think you need to add the missing Utilities/General dependency in 
Alignment/TrackerAlignment/BuildFile.xml
Alignment/TrackerAlignment/plugins/BuildFile.xml

instead of Alignment/CommonAlignmentMonitor/plugins/BuildFile.xml

git cms-checkdeps -A -a 
should checkout all the packages needed for rebuild due to BuildFile chanegs.

**Comment by ianna** [comment]
@smuzaffar - Thanks!

**Comment by ianna** [comment]
@cmsbuild please test

**Comment by ianna** [comment]
+1

**Pull request merged**
