### PR TITLE
MTD geometry and reconstruction: update locaPosition in RectangularMTDTopology and adapt cluster accordingly

### PR DESCRIPTION
**Pull request by fabiocos**
#### PR description:

The ```locaPosition```, ```localX``` and ```localY``` methods of ```RectangularMTDTopology``` do not provide, as naively expected, the center of a pixel as its reference position, but its left-bottom corner. This is counterintuitive and forces to some odd coding in the clustering algorithm. It is compensated by a shift by 0.5 pixel in the calculation of the cluster x and y coordinates in the corresponding DataFormat. In order to have a clean situation, the shift is moved from the cluster position calculation to the basic topology code itself.

This should have no net impact, given the limited use of these methods, and the fact that its use inside the BTL clustering is effectively dummy so far. In preparation of a further PR which updates the clustering code, I propose initially this update.

With the occasion, I update the local reconstruction validation code to properly use the cluster parameter estimator code to extract the position, without replicating its methods (which are going to change in next developments).

#### PR validation:

The code was tested with single muon workflow 20903 (scenario D88), showing that the cluster resolution and pull remains consistent with the existing result. The shift in tracking hits position printed from debug statements looks consistent with the  proposed update of reference position.

### CODE REVIEW

**Comment by fabiocos** [comment]
@parbol FYI

**Comment by fabiocos** [comment]
please test

**Comment by emanueleusai** [comment]
DQM histogram differences in ETL Monitoring Elements using hits, just as expected. The only difference in DQM histos I do not understand is this one in Tracks/TrackPathLenghtvsEta:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_6_X_2022-11-11-1100+d480e5/54057/21034.999_TTbar_14TeV+2026D88PU_PMXS1S2PR+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14+PREMIX_PremixHLBeamSpot14PU+DigiTriggerPU+RecoGlobalPU+HARVESTGlobalPU/MTD_Tracks.html

**Comment by fabiocos** [comment]
@emanueleusai this PR affects directly ETL digitization in the determination of the hit radius in https://github.com/cms-sw/cmssw/blob/master/SimFastTiming/FastTimingCommon/src/ETLElectronicsSim.cc#L51 and this should explain the minor fluctuations observed in the ETL plots. This might as well induce some minor fluctuation in the forward clusters, which are mostly single-pixel but not always, and as a consequence occasionally affect the track-cluster match, which define the collection of tracks and the value of the observable which enters into the affected plot. BTW this appears in the sample with PU, where many more hist and tracks are expected, but the PU is a premixed sample not affected by the change in this PR.

**Comment by emanueleusai** [comment]
@fabiocos thank you very much for the explanation!

**Comment by emanueleusai** [comment]
+1

- DQM differences understood

**Comment by bsunanda** [comment]
+geometry

**Comment by fabiocos** [comment]
@cms-sw/reconstruction-l2 @cms-sw/upgrade-l2 questions or comments?

**Comment by clacaputo** [comment]
+reconstruction

**Comment by AdrianoDee** [comment]
+upgrade

**Comment by rappoccio** [comment]
+1

**Pull request merged**
