### PR TITLE
Reset patTrigger.ReadPrescalesFromFile = True in run2_miniAOD_80XLegacy

### PR DESCRIPTION
**Pull request by gpetruc**
Addresses #22207

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by fabiocos** [comment]
@slava77 @perrotta this is the temporary workaround you were suggesting to prevent the crash until the problem is solved in the L1 code. Please sign if you agree

**Comment by slava77** [comment]
@cmsbuild please test workflow 1325.5

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/22239	3cc663b
- (temporary?) fix for a failing miniAOD workflow running on MC inputs from 80X
- jenkins tests pass, including 1325.5 (which is failing in the baseline IB)

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Pull request merged**
