### PR TITLE
Run3-alca186 Update the calibration scripts for HCAL

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Update the calibration scripts for HCAL

#### PR validation:

Tested by using the scripts to obtain the latest calibration of HCAL

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by qliphy** [comment]
please test

**Comment by qliphy** [comment]
kindly ping @cms-sw/alca-l2

**Comment by francescobrivio** [comment]
+alca
 - differences and failures all related to MessageLogger

**Comment by qliphy** [comment]
+1

**Pull request merged**
