### PR TITLE
Updates of the TP reconstruction algorithm to fix the TP energy saturation effect

### PR DESCRIPTION
**Pull request by TaeunKwon**
#### PR description:

This PR updates the Trigger Primitive(TP) reconstruction algorithm to fix the effect that the saturation in the input LUT makes the total TP energy underestimated. To fix the saturation effect, the total energy of TPs is forced to be saturated when the saturation in the input LUT is found before the sum over depths and the peak finder algorithm. This is achieved in the implementation by having the map of saturated towers in `HcalTriggerPrimitiveAlgo` and check the saturation after the peak finder algorithm, to make the TP energy saturated if the saturation is found at the input level. This PR is only applicable for a Run3 condition and can be toggled off by the parameter `applySaturationFix` in `simHcalTriggerPrimitiveDigis`.  The detailed motivation and effect of changes of this PR are presented in [presentation by Taeun Kwon](https://indico.cern.ch/event/1049943/contributions/4416052/attachments/2268682/3852452/CMSWEEK_Commissioning_1TS_Scheme.pdf) from slide 14 to 21

#### PR validation:

A basic technical test was performed: `runTheMatrix.py -l limited -i all --ibeos`

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

This PR is not a backport. It can be backported to 11_3_X after this PR is revised and merged.

### CODE REVIEW

**Comment by qliphy** [comment]
please test

**Comment by abdoulline** [comment]
@TaeunKwon  
It looks like there is no changes in Run3/Phase2 (2021, 2023, 2026 wf's)  results 
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_0_X_2021-06-26-1100+9d18d8/43689/dqm-histo-comparison-summary.html
   (wfs  11634,  12434,  28234, 34834) 

I'm not sure whether it's just because of a small statistics (10ev)?
Could you, please run your favourite wf (RelValQCD_FlatPt_15_3000HS_14 ?) in 12_0_X with reasonable statistics (1k)  **w/wo this PR** to make sure the fix works (makes the expected difference) ?  Or give some other evidence (like debugging printout with this PR) ?

**Comment by cecilecaillol** [comment]
+l1

**Comment by TaeunKwon** [comment]
@abdoulline 
Sorry for the late response. I tested the change with this PR in CMSSW_12_0_X_2021-06-24-1100 release. I guess the reason why there are no changes in Run3/Phase2 (2021, 2023, 2026 wf's) results is that the test is done for the PFA2 scheme. As you can see in the attached file, there is no significant change by fixing the TP energy saturation for the PFA2 scheme. I guess it is because in the PFA2 scheme, we use two time slices for TP energy reconstruction and so, the pulse containment correction factor is small compared to that for PFA1', and it leads to a small number of input LUT saturations. In PFA1', you can see a dramatic change by this PR.
[https://drive.google.com/file/d/1nRXuEa_jepXXJSYA8Av5ZIklX8R-ReRV/view?usp=sharing](https://drive.google.com/file/d/1nRXuEa_jepXXJSYA8Av5ZIklX8R-ReRV/view?usp=sharing)

**Comment by abdoulline** [comment]
@TaeunKwon 
it seems I cannot access the link you've provided...
Anyway, I trust your assessment about substantial (expected) effect on PFA1' and almost imperceptible effect on PFA2 default algo in the PR tests on 10 ev.

**Comment by TaeunKwon** [comment]
I'm sorry I just updated the permission for the attached file. Now I believe you can access the link. Please let me know if you suffer the same problem. Thanks!

**Comment by abdoulline** [comment]
@TaeunKwon OK, thank you. 
Now I can see that the default PFA2 doesn't change much and 
with 10 ev tests it may not be visible in aforementioned DQM/Validation plots...

**Comment by qliphy** [comment]
+1

**Pull request merged**
