### PR TITLE
fix binning in muon->innerTrack DQM [backport #20970]

### PR DESCRIPTION
**Pull request by mtosi**
backport of https://github.com/cms-sw/cmssw/pull/20970

### CODE REVIEW

**Comment by mtosi** [comment]
@cmsbuild, please test

**Comment by mtosi** [comment]
@VinInn 
once tier0 uses this PR
the hit efficiency vs PU plots for the muon->innerTrack 
will have a different binning (`40, 0.5, 120.5`) w.r.t. the current one (`50, 0.5, 50.5`)

**Comment by mtosi** [comment]
@cmsbuild, please test

**Comment by dmitrijus** [comment]
+1

**Comment by mtosi** [comment]
@cmsbuild, please test

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
