### PR TITLE
[10.0.X] [GT Updates] for HCAL Bug fixes and Jet Probability calibration for btagging

### PR DESCRIPTION
**Pull request by arunhep**
backport of #22075 and #22137

# Summary of changes in Global Tags 
 
## 2018_MC
 
   * **PhaseI 2018 cosmics scenario** : [100X_upgrade2018cosmics_realistic_deco_v7](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/100X_upgrade2018cosmics_realistic_deco_v7) as [100X_upgrade2018cosmics_realistic_deco_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/100X_upgrade2018cosmics_realistic_deco_v5) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/100X_upgrade2018cosmics_realistic_deco_v7/100X_upgrade2018cosmics_realistic_deco_v5): 
      * update of jet probability calibrations for b-tagging : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3464.html
      * HCAL bug fixes : https://indico.cern.ch/event/691337/contributions/2866494/attachments/1586921/2509518/ConditionUpdateProposal20180122.pdf
      * update of leftover ECAL TPG threshold tags
      * update of ECAL and CSC bad channel status

   * **PhaseI 2018 design scenario** : [100X_upgrade2018_design_IdealBS_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/100X_upgrade2018_design_IdealBS_v5) as [100X_upgrade2018_design_IdealBS_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/100X_upgrade2018_design_IdealBS_v4) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/100X_upgrade2018_design_IdealBS_v5/100X_upgrade2018_design_IdealBS_v4): 
      * update of jet probability calibrations for b-tagging : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3464.html
      * HCAL bug fixes : https://indico.cern.ch/event/691337/contributions/2866494/attachments/1586921/2509518/ConditionUpdateProposal20180122.pdf

   * **PhaseI 2018 realistic scenario** : [100X_upgrade2018_realistic_v9](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/100X_upgrade2018_realistic_v9) as [100X_upgrade2018_realistic_v7](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/100X_upgrade2018_realistic_v7) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/100X_upgrade2018_realistic_v9/100X_upgrade2018_realistic_v7): 
      * update of jet probability calibrations for b-tagging : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3464.html
      * HCAL bug fixes : https://indico.cern.ch/event/691337/contributions/2866494/attachments/1586921/2509518/ConditionUpdateProposal20180122.pdf
      * update of ECAL and CSC bad channel status

## 2017_MC 
 
   * **PhaseI 2017 cosmics peak scenario** : [100X_mc2017cosmics_realistic_peak_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/100X_mc2017cosmics_realistic_peak_v3) as [100X_mc2017cosmics_realistic_peak_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/100X_mc2017cosmics_realistic_peak_v2) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/100X_mc2017cosmics_realistic_peak_v3/100X_mc2017cosmics_realistic_peak_v2): 
      * update of jet probability calibrations for b-tagging : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3464.html

   * **PhaseI 2017 cosmics scenario** : [100X_mc2017cosmics_realistic_deco_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/100X_mc2017cosmics_realistic_deco_v3) as [100X_mc2017cosmics_realistic_deco_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/100X_mc2017cosmics_realistic_deco_v2) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/100X_mc2017cosmics_realistic_deco_v3/100X_mc2017cosmics_realistic_deco_v2): 
      * update of jet probability calibrations for b-tagging : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3464.html

   * **PhaseI 2017 design scenario** : [100X_mc2017_design_IdealBS_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/100X_mc2017_design_IdealBS_v3) as [100X_mc2017_design_IdealBS_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/100X_mc2017_design_IdealBS_v2) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/100X_mc2017_design_IdealBS_v3/100X_mc2017_design_IdealBS_v2): 
      * update of jet probability calibrations for b-tagging : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3464.html

   * **PhaseI 2017 realistic scenario** : [100X_mc2017_realistic_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/100X_mc2017_realistic_v3) as [100X_mc2017_realistic_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/100X_mc2017_realistic_v2) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/100X_mc2017_realistic_v3/100X_mc2017_realistic_v2): 
      * update of jet probability calibrations for b-tagging : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3464.html

### CODE REVIEW

**Comment by arunhep** [comment]
please test

**Comment by arunhep** [comment]
+1

**Comment by arunhep** [comment]
please test

**Comment by arunhep** [comment]
# Summary of changes in Global Tags from last [commit](https://github.com/cms-sw/cmssw/pull/22078/commits/a04df838369693c74d2043d554433149ac06ca6e)
 
## 2018_MC
 
   * **PhaseI 2018 cosmics scenario** : [100X_upgrade2018cosmics_realistic_deco_v8](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/100X_upgrade2018cosmics_realistic_deco_v8) as [100X_upgrade2018cosmics_realistic_deco_v7](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/100X_upgrade2018cosmics_realistic_deco_v7) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/100X_upgrade2018cosmics_realistic_deco_v8/100X_upgrade2018cosmics_realistic_deco_v7): 

   * **PhaseI 2018 design scenario** : [100X_upgrade2018_design_IdealBS_v6](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/100X_upgrade2018_design_IdealBS_v6) as [100X_upgrade2018_design_IdealBS_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/100X_upgrade2018_design_IdealBS_v5) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/100X_upgrade2018_design_IdealBS_v6/100X_upgrade2018_design_IdealBS_v5): 

   * **PhaseI 2018 realistic scenario** : [100X_upgrade2018_realistic_v10](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/100X_upgrade2018_realistic_v10) as [100X_upgrade2018_realistic_v9](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/100X_upgrade2018_realistic_v9) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/100X_upgrade2018_realistic_v10/100X_upgrade2018_realistic_v9): 

      * HCAL response correction update to take into account the energy scale change for HE. 
https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3483.html
 https://indico.cern.ch/event/701241/contributions/2887035/attachments/1595810/2527619/IsoTrackN59.pdf

**Comment by arunhep** [comment]
@fabiocos please consider this PR for 10_0_2 build. This contains now also the latest change in HE energy scale derived using isoTrack calibration and this is proposed by HCAL DPG.

**Comment by fabiocos** [comment]
@franzoni this is the final fix which we discussed should be included in 10_0_2

**Comment by fabiocos** [comment]
@arunhep are all the differences in the plots understood? Btag and HE I can understand, what about tracking plots?

**Comment by arunhep** [comment]
@fabiocos i see no obvious reason. could it be that the events that we are comparing are not the same? I see differences in distributions which has Sim to Reco quantities.

**Comment by fabiocos** [comment]
please test

**Comment by arunhep** [comment]
@fabiocos @franzoni 
even with higher statistics (50 events), the distributions are not exactly same.

look at the this diagram.

effc_vs_dzpvsigcut_pt

Red : with this PR (new GT)
Blue : old GT

DQM root files can be found here : `/afs/cern.ch/user/a/arun/public/PRTest_22078`

now I am running the workflow with a GT containing only the HCAL changes and rest of the conditions are same as old GT.

**Comment by arunhep** [comment]
@fabiocos @franzoni 
I have checked following cases by running wf 10824 on 50 events : 

1. New GT : all the updates present : GT from this PR
2. Old GT : reference GT from this PR
3. Keeping only HCAL condition updates on the top of old GT --> No change in Tracking
4. Keeping HCAL + ECAL channel status --> No change in tracking
5. Keeping HCAL + ECAL + CSC channel status --> No change in tracking

so once we add new jet probability calibration in GT then we see the change in tracking.
all the files can be found here : `/afs/cern.ch/user/a/arun/public/PRTest_22078`

**Comment by arunhep** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Comment by makortel** [comment]
> so once we add new jet probability calibration in GT then we see the change in tracking.

I can not understand how a(ny) change in btagging would affect tracking. @VinInn 

> all the files can be found here : /afs/cern.ch/user/a/arun/public/PRTest_22078

Thanks for the files, I made the usual TRK validation plots
https://cms-tracking-validation.web.cern.ch/cms-tracking-validation/PR/CMSSW_10_0_X_PR22078/
and according to them it is actually the "HCAL updates" which cause the change. I can see changes already in `initialStepPreSplitting` tracks
https://cms-tracking-validation.web.cern.ch/cms-tracking-validation/PR/CMSSW_10_0_X_PR22078/plots_building_initialStepPreSplitting/effandfakePtEtaPhi.pdf
which actually doesn't make much sense either as the first step in tracking depending on calorimeters comes after those tracks (cluster splitting at the end of that iteration).

Or did I understand the file naming incorrectly?

**Comment by arunhep** [comment]
@makortel 

when I claimed no changes with HCAL updates then I checked only few histograms and not all of them. One of the checked ones is the one posted in above comments.

thanks for the detailed checks. Here are definitions of files names and more details:

1. `DQM_V0001_R000000001__Global__CMSSW_X_Y_Z__RECO_oldGT.root `--> DQM file made with old GT (reference GT in this PR : 100X_upgrade2018_realistic_v7)
2. `DQM_V0001_R000000001__Global__CMSSW_X_Y_Z__RECO_NEWGT.root` --> DQM file made with old GT (target GT in this PR : 100X_upgrade2018_realistic_v10)
3. `DQM_V0001_R000000001__Global__CMSSW_X_Y_Z__RECO_onlyHCAL.root` --> DQM file made with GT only containing HCAL changes from this PR : diff of GT with reference one : https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/100X_upgrade2018_realistic_Candidate_2018_02_08_15_20_01/100X_upgrade2018_realistic_v7
4. `DQM_V0001_R000000001__Global__CMSSW_X_Y_Z__RECO_HCALECAL.root` -->  DQM file made with GT containing HCAL + ECAL changes from this PR : diff of GT with reference one : https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/100X_upgrade2018_realistic_Candidate_2018_02_08_16_17_28/100X_upgrade2018_realistic_v7
5. `DQM_V0001_R000000001__Global__CMSSW_X_Y_Z__RECO_HCALECALCSC.root`  --> DQM file made with GT containing HCAL + ECAL + CSC changes from this PR : diff of GT with reference one : https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/100X_upgrade2018_realistic_Candidate_2018_02_08_18_02_55/100X_upgrade2018_realistic_v7

**Comment by mmusich** [comment]
Hi all,
isn't this the usual case of getting random changes at the digitizer level, due to random number sequences when some new condition affecting the DIGI step enters the Global Tag?
According to https://twiki.cern.ch/twiki/bin/viewauth/CMS/AlCaDBHLT e.g. `HcalGainsRcd` is consumed by the HCAL digitizer.
There is plenty of differences already at the level of strip digis: https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_10_0_X_2018-02-07-1100+22078/24962/10824.0_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2018_GenSimFull+DigiFull_2018+RecoFull_2018+ALCAFull_2018+HARVESTFull_2018/GlobalDigisV_SiStrips.html

**Comment by makortel** [comment]
Thanks @mmusich, I didn't look carefully-enough that DIGI was affected. I fully agree on your diagnosis.

**Pull request merged**
