### PR TITLE
pushing skimming of B Parking to CMSSW_10_5_X

### PR DESCRIPTION
**Pull request by gkaratha**
Dear all, @kfjack , @prebello , @davidlange6 

As I promised I transferred the code to new master (10_5_X). How are we going to proceed? Are there any comments code wise or performance? From our group @mverzett @bainbrid are interested. Thanks

Best regards,
George

### CODE REVIEW

**Comment by prebello** [comment]
@gkaratha please change the title of your PR to show up its proposal.

**Comment by prebello** [comment]
please test

**Comment by gkaratha** [comment]
Dear @prebello ,

Thanks I did it.

Best regards,
 George

**Comment by kfjack** [comment]
@prebello I think the code and tests read fine.

**Comment by prebello** [comment]
+1

**Comment by prebello** [comment]
@gkaratha @kfjack will a backport to 10-2-x be provided soon?

**Comment by fabiocos** [comment]
@gkaratha @prebello @kfjack apart for a minor code optimization suggested by David, the code looks ready. Anyway I have a question: was it tested in some workflow? Do we have a definition of a Relval addition to add here? Otherwise how can we say the code is ok apart for simple visual inspection?

**Comment by prebello** [comment]
hi @fabiocos from my best knowledge, we never injected B parking related relvals. 
PdmV will check what is needed and provide the validation.
FYI @gkaratha @zhenhu @paolo gunnelini

**Comment by fabiocos** [comment]
@gkaratha is there any news about testing this skim?

**Comment by gkaratha** [comment]
Dear all,
I will answer the questions:
@fabiocos  I dont know which tests are needed. I have made the study using AOD. I can send the results for that. Essentially this is also my question. If anything is needed I can provide it. Essentially at this point I will make a small update soon to accommodate the low pT e. Or finalize this with the latest cuts.
@kfjack Yes sure. You can find plenty here (>10TB): /eos/cms/store/data/Run2018B/ParkingBPH5/RAW/v1/000/
Thanks to both.

Best regards,
George Karathanasis

**Comment by fabiocos** [comment]
@kfjack @gkaratha any update on this? I understand that people would like to move forward with the processing quite soon...

**Comment by kfjack** [comment]
@fabiocos sorry for the delay! I should be able to work out the RelVal configuration by today.

**Comment by kfjack** [comment]
Hi all, I created a new PR #25892 containing the updates in this PR plus the corresponding RelVal steps.
Local run was successful. Please help us to test it.

**Comment by fabiocos** [comment]
@gkaratha at this point this PR might be closed

**Comment by fabiocos** [comment]
hold

**Comment by gkaratha** [comment]
Dear all,

I will close this PR since there is no reason to keep it open, unless someone needs it. Thanks for the contributions.

Best,
George

**Pull request closed without merging**
