### PR TITLE
Remove dead assignments for ZToMuMuGammaAnalyzer and HGCalSimHitValidation

### PR DESCRIPTION
**Pull request by perrotta**
#### PR description:

A few dead assignments were spot by the static analyzer in the two plugins. Being simple, they are fixed here.

While doing so:
- Some distance calculation was also speed up in ZToMuMuGammaAnalyzer 
- I profited to merge the .h and .cc files into a single one for ZToMuMuGammaAnalyzer 

#### PR validation:

It builds

No differences are expected whatsoever

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by qliphy** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
