### PR TITLE
[SIM] Fixed ZDC simulation 

### PR DESCRIPTION
**Pull request by civanch**
#### PR description:
CMS simulation use to kill all particles which left central detector in area beyond some distance. The fix means that neutrons, anti-neutrons, and gamma are not killed outside central detector, when travel in the volume "CMStoZDC".

#### PR validation:
private

### CODE REVIEW

**Comment by civanch** [comment]
@bsunanda , FYI

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

regression is not expected, because extra steps of gamma, n, nbar in CMStoZDC volume change simulation histories. Independent check shows that CPU is not increased significantly.

**Comment by rappoccio** [comment]
+1

**Pull request merged**
