### PR TITLE
Updating hadronizers to use CP5 in relvals

### PR DESCRIPTION
**Pull request by efeyazgan**

### CODE REVIEW

**Comment by kpedro88** [comment]
```
ERROR reading file: relval_generator 'Hadronizer_TuneCP5_13TeV_MLM_5f_max4j_LHE_pythia8'
Traceback (most recent call last):
  File "/build/cmsbld/jenkins/workspace/ib-any-integration/CMSSW_10_4_X_2018-10-23-1100/bin/slc6_amd64_gcc700/runTheMatrix.py", line 338, in <module>
    ret = runSelected(opt)
  File "/build/cmsbld/jenkins/workspace/ib-any-integration/CMSSW_10_4_X_2018-10-23-1100/bin/slc6_amd64_gcc700/runTheMatrix.py", line 23, in runSelected
    mrd.prepare(opt.useInput, opt.refRel, opt.fromScratch)
  File "/build/cmsbld/jenkins/workspace/ib-any-integration/CMSSW_10_4_X_2018-10-23-1100/python/Configuration/PyReleaseValidation/MatrixReader.py", line 491, in prepare
    self.readMatrix(matrixFile, useInput, refRel, fromScratch)
  File "/build/cmsbld/jenkins/workspace/ib-any-integration/CMSSW_10_4_X_2018-10-23-1100/python/Configuration/PyReleaseValidation/MatrixReader.py", line 263, in readMatrix
    cfg, input, opts = self.makeCmd(self.makeStep(self.relvalModule.steps[stepName],stepOverrides))
KeyError: 'Hadronizer_TuneCP5_13TeV_MLM_5f_max4j_LHE_pythia8'
```

**Comment by qliphy** [comment]
@efeyazgan   

Need to add the following fine in Configuration/PyReleaseValidation/python/relval_steps.py:

steps['Hadronizer_TuneCP5_13TeV_MLM_5f_max4j_LHE_pythia8']=genvalid('Hadronizer_TuneCP5_13TeV_MLM_5f_max4j_LHE_pythia8_cff',step1HadronizerDefaults)

**Comment by efeyazgan** [comment]
@qliphy I need to change all CUETP8M1 in Configuration/PyReleaseValidation/python/relval_steps.py to CP5, no?

**Comment by qliphy** [comment]
@efeyazgan   Yes,  but it may be safe to  add new PC5 in relval_steps.py, and keep previous CUETP8M1

**Comment by efeyazgan** [comment]
@qliphy yes, but I change (almost) all in relval_generator.py and relval_extendedgen.py to the new tune (as seen in the commits).

**Comment by qliphy** [comment]
@efeyazgan   But there might be other workflows  using CUETP8M1
                   cmssw/Configuration/PyReleaseValidation/python/

**Comment by efeyazgan** [comment]
please test

**Comment by kpedro88** [comment]
@efeyazgan please test locally to ensure the matrix is functional before updating the PR again

**Comment by efeyazgan** [comment]
@kpedro88 all updated workflows tested locally (512, 513, 514, 515, 516, 517, 518,  519,  521,  522, 523, 524, 526,  527, 529, 530, 551, 552, 555, 556, 554,  525, 528)

**Comment by kpedro88** [comment]
@efeyazgan this branch is now broken somehow with a bunch of unrelated commits. Did you merge instead of rebasing?

**Comment by efeyazgan** [comment]
I did not do rebase, I'll fix.

**Comment by perrotta** [comment]
-1
(just to remove from reco queue)

**Comment by efeyazgan** [comment]
Closing this one. The new PR is #25013.

**Pull request closed without merging**
