### PR TITLE
Fixes to DT DQM to use histograms not previously declared

### PR DESCRIPTION
**Pull request by jfernan2**
Last minute plots which were not declared and prevent module from crashing

### CODE REVIEW

**Comment by dmitrijus** [comment]
+1
Please provide a short description.

**Comment by dmitrijus** [comment]
+1
A rather big 'cosmetic' change. Anyway, everything looks fine, this should go in.

**Comment by dmitrijus** [comment]
please test

**Comment by davidlange6** [comment]
Hi @jfernan2  - please change the title of this PR to be descriptive for the release notes

**Comment by davidlange6** [comment]
+1

**Pull request merged**
