### PR TITLE
relval matrix update in 80X

### PR DESCRIPTION
**Pull request by fabozzi**
Matrix updates in 8_0_X (backport of matrix updates from 81X):
- 2016 relvals 
- Run2 cosmics relvals
- skims in reco step

### CODE REVIEW

**Comment by fabozzi** [comment]
please test

**Comment by fabozzi** [comment]
please test

**Comment by fabozzi** [comment]
+1

**Comment by fabozzi** [comment]
please test

**Comment by fabozzi** [comment]
maybe there is an issue with interactive DAS query of MinBias sample for PU...

**Comment by fabozzi** [comment]
please test

**Comment by fabozzi** [comment]
+1

**Comment by fabozzi** [comment]
please test

**Comment by davidlange6** [comment]
+1

**Comment by davidlange6** [comment]
whoops - I meant to wait for the comparisons - lets see if we get them
@smuzaffar

**Comment by smuzaffar** [comment]
it timed out after 6 hours. 
```https://cmssdt.cern.ch/jenkins/job/compare-root-files-short-matrix/14586/console ```
I have restarted it

**Comment by davidlange6** [comment]
thx!

**Pull request merged**
