### PR TITLE
L1T legacy app is turned off and L1T2016 is renamed to L1T

### PR DESCRIPTION
**Pull request by EsmaeelEskandari**

### CODE REVIEW

**Comment by EsmaeelEskandari** [comment]
Regarding this change, L1T2016->L1T, I made another PR for L1T shifter space to be consistent with this one: https://github.com/dmwm/deployment/pull/447

**Comment by thomreis** [comment]
Hi @EsmaeelEskandari,
changing the directory names broke the DQM histogram draw options. All 2D histograms are now displayed in the GUI as scatter plots instead of colz.
Could you please change the directory names also https://github.com/dmwm/deployment. I think the render plugins should be all under dqmgui/style/

**Comment by dmitrijus** [comment]
+1

PR to DQM GUI should happen after this is merged.

**Comment by davidlange6** [comment]
+1

**Comment by threus** [comment]
@EsmaeelEskandari @thomreis is there a 90X back port of this PR?

**Comment by thomreis** [comment]
#18043 includes this changes, yes

**Comment by threus** [comment]
great, thanks @thomreis. That means this PR is included in #18409 as well (which we run in online DQM), since it incorporates #18043

**Pull request merged**
