### PR TITLE
Fix posftix and scheduled mode issue in the runMETUncertainty tool

### PR DESCRIPTION
**Pull request by mmarionncern**
This PR contains a fix for specific uses of the postfix option, and another one for someone running the tool in scheduled mode. 

The PR also contains a small update of the PAT tau cleaning. In case this is forbidden for 80X, as that change affects the miniAOD reprocessing, it will be removed.

Packages touched :
- PhysicsTools/PatUtils
- PhysicsTools/PatAlgos

Changes expected : tau cleaning

Validation plots : http://mmarionn.web.cern.ch/mmarionn/MET/Validation_8_0_X/
(black line is the reference, red line is after the changes)

### CODE REVIEW

**Comment by slava77** [comment]
@mmarionncern 
we need a PR in 81X as well.
This is where the code will be integrated first.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
```  contains a small update of the PAT tau cleaning. In case this is forbidden for 80X ```
yes, changes in miniAOD are not allowed until further notice (miniAOD v3 processing campaign, probably post-ICHEP)

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@mmarionncern please confirm that this is now good to go (tested and working)
Thanks.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cmsbuild please test
the last attempt failed (silently, what concerns notifications in this thread)

**Comment by mmarionncern** [comment]
@slava77 Yes, the PR is in its final state

**Comment by slava77** [comment]
@mmarionncern 
since this PR changes products saved in miniAOD, we can not integrate it in 80X until there is a re-miniAOD campaign.
If this PR is eventually needed in its totality, I can sign and put it on hold.

Please let me know.

**Comment by mmarionncern** [comment]
@slava77 I removed the change that was affecting the miniAOD content. The PR is now transparent for the miniAOD processing.
The tauCleaner change can be integrated later if a re-miniAOD campaign is planned

**Comment by slava77** [comment]
```
@slava77 I removed the change that was affecting the miniAOD content. The PR is now transparent for the miniAOD processing.
The tauCleaner change can be integrated later if a re-miniAOD campaign is planned
```
I suppose this does not apply anymore since this earlier message was apparently edited.

There will be no updates to this PR now, right?
Please clarify.

**Comment by slava77** [comment]
hold

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/14606	c9a634f
- code changes introduce several fixes in MET uncertainty modules configuration (in miniAOD as well).
- jenkins tests pass and comparisons show no differences

This is left on hold and can be integrated when a new re-miniAOD campaign starts

**Comment by mmarionncern** [comment]
I made a rebase to fix the conflicts, appeared since the PR was hold, but it looks like it should not have been done that way.... currently investigating

**Comment by mmarionncern** [comment]
I prefered to remake a new PR on top of the current CMSSW_8_0_X version rather than keeping that PR.
The new PR is here : #15616

**Pull request closed without merging**
