### PR TITLE
Fix clang warnings in LzmaFile

### PR DESCRIPTION
**Pull request by Dr15Jones**
Removed a self-assignment of a variable.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
The runTheMatrix failure is from xrootd not getting the needed file.

**Comment by Dr15Jones** [comment]
please test

**Comment by efeyazgan** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
