### PR TITLE
[10.1.X] Migrate SiStripQualityStatistics configuration to be a DQMEDAnalyzer

### PR DESCRIPTION
**Pull request by mmusich**
As foreseen in https://github.com/cms-sw/cmssw/pull/22134#issuecomment-366654833, since in #22134 `SiStripQualityStatistics` has been migrated to be a `DQMEDAnalyzer` in lieu of a `edm::EDAnalyzer ` the current configuration declaration all over CMSSW won't work anymore (after #22319),  due to a Framework type mismatch: 
```
----- Begin Fatal Exception 08-Mar-2018 12:12:51 CET-----------------------
An exception of category 'Configuration' occurred while
   [0] Constructing the EventProcessor
   [1] Validating configuration of module: class=SiStripQualityStatistics label='stat'
Exception Message:
The base type in the python configuration is EDAnalyzer, but the base type
for the module's C++ class is EDProducer. Please fix the configuration.
It must use the same base type as the C++ class.
----- End Fatal Exception -------------------------------------------------

```
I profit of this PR to add a unit test for the `SiStripQualityStatistics`  that shall help us to catch misbehaviors in time.

### CODE REVIEW

**Comment by mmusich** [comment]
type bug-fix

**Comment by davidlange6** [comment]
please test

**Comment by mmusich** [comment]
```
----- Begin Fatal Exception 08-Mar-2018 17:59:27 CET-----------------------
An exception of category 'fastsim::ParticleManager' occurred while
   [0] Processing  Event run: 1 lumi: 1 event: 32 stream: 0
   [1] Running path 'simulation_step'
   [2] Calling method for module FastSimProducer/'fastSimProducer'
Exception Message:
unknown pdg id: 100441
----- End Fatal Exception -------------------------------------------------
```

I don't see how this can relate to the proposed changes

**Comment by davidlange6** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by arunhep** [comment]
+1

**Comment by fabiocos** [comment]
+1

protection for DQM migration

**Pull request merged**
