### PR TITLE
Back-port of Small Overlap Fixes in GE2/1

### PR DESCRIPTION
**Pull request by ianna**
- Back-port Sunanda's overlap fixes from 74x (Note, most changes reported by git here are in indentation and spaces, but I'll keep them to have identical descriptions in both releases).

### CODE REVIEW

**Comment by ianna** [comment]
After the fix:
screen shot 2015-01-09 at 17 05 02

Before the fix:
screen shot 2015-01-09 at 17 05 50

**Comment by mark-grimes** [comment]
Does this invalidate Gen-Sim?

**Comment by ianna** [comment]
@mark-grimes - I would not think so, the changes are in order of 0.005 cm - comparable with misalignment.

**Comment by davidlange6** [comment]
It invalidates it in the sense that the geometry changes by a tiny amount.

**Comment by davidlange6** [comment]
thinking more - I will close this and save for 74x to avoid having to convince ourselves later that there is no effect on digi-reco - if the TP production plan changes then we can reconsider if a new gen-sim is done for gem.

**Pull request closed without merging**
