### PR TITLE
hgx-TB77A Commit changes made by Ashim for 2023 August/Septemeber Test Beam

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Commit changes made by Ashim for the 2023 August/Septemeber Test Beam

#### PR validation:

This is the first phase of commitment. A complete test will be provided later

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

**Comment by rappoccio** [comment]
+1

**Pull request merged**
