### PR TITLE
Modernized XMLIdealGeometryESProducer

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:
- specify consumes and use ESGetToken
- added fillDescriptions

#### PR validation:

runTheMatrix.py tests work fine.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by ianna** [comment]
@cvuosalo - please, check if the following tests run fine:
https://cmssdt.cern.ch/lxr/search?%21v=CMSSW_11_0_X_2019-10-16-2300&_filestring=py&_string=XMLIdealGeometryESProducer

**Comment by Dr15Jones** [comment]
The test failures are from #28223  not this pull request.

**Comment by Dr15Jones** [comment]
please test

**Comment by cvuosalo** [comment]
Test configs that include the code revised in this PR seem to run the same as they do in the baseline. Two configs were tested:
`GeometryReaders/XMLIdealGeometryESSource/test/testReadXMLFromGTDB.py`
`SimTracker/TrackerMaterialAnalysis/test/listIds_PhaseII.py`

**Comment by ianna** [comment]
@Dr15Jones - proposed changes look good to me.

**Comment by cvuosalo** [comment]
+1

**Pull request merged**
