### PR TITLE
Updated HLTTau validation to include legs X in tau+X triggers

### PR DESCRIPTION
**Pull request by slehti**
Same as PR #9928 (no changes), now for 74X

### CODE REVIEW

**Comment by deguio** [comment]
-1
following the comments at in #9928

**Comment by deguio** [comment]
-1
following the comments at #9928 I prefer to keep this one on hold for now. moreover the backport to 75 is missing.
F.

**Comment by perrotta** [comment]
Hi @slehti : thank you for pointing me to this PR.
However, as you can see, it was closed since more than one month!
Could you please take care of preparing and submitting the correct backport of #10265 / #10821 (which are both already merged in 75X and 76X, respectively)?
Thank you,
Andrea

**Comment by slehti** [comment]
This is the correct backport. I checked with diff all the modified files and they are identical to what is now in CMSSW_7_6_0_pre5. Can this PR be reopened and merged, no need to keep this on hold any longer.

**Comment by perrotta** [comment]
You are the owner of this pull requests, and I think you should be able to reopen it.
Alternatively: @davidlange6 could you please reopen it?

**Pull request closed without merging**
