### PR TITLE
[92x] l1t Muon Unpacker Zero Suppression and DQM. Clang cleaning.

### PR DESCRIPTION
**Pull request by rekovic**
PR 92x - Upgrade the Muon Unpacker and DQM to intelligently  handle Zero Suppression, making it BX aware. Also includes CLANG cleaning

Needed for data taking and available in the release at P5 before hardware change goes online (soon).

This is compatible with past, current, and future data.

### CODE REVIEW

**Comment by rekovic** [comment]
backport of #20634

**Comment by rekovic** [comment]
please test

**Comment by rekovic** [comment]
+1

**Comment by thomreis** [comment]
@dmitrijus @vanbesien could you check this please? The 94x version is merged already and we need it at P5 and the T0 for the new zero suppression.

**Comment by rekovic** [comment]
@dmitrijus please sign. 
After merging, we neet to request a CMSSW release to deploy at P0.

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
merge

**Pull request merged**
