### PR TITLE
bsunanda:Run2-sim05 Add hit capability to the back hadron calorimeter of the HGCal TB

### PR DESCRIPTION
**Pull request by bsunanda**
AHCal comes from CALICE collaboration (DESY) as the back hadron calorimeter of HGCal prototype

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by ianna** [comment]
+1

**Comment by civanch** [comment]
@bsunanda , in this SD class there is no room for Russian roulette?

**Comment by bsunanda** [comment]
@civanch This class inherits from CaloSD. My understanding is that you introduced this through StackingAction and not through SD

**Comment by civanch** [comment]
There are important lines inside each SD:

G4double  wt2 = track->GetWeight();
if(wt2 > 0.0) { edep *= wt2; }

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Comment by davidlange6** [comment]
what is AHCal?
@bsunanda

**Comment by bsunanda** [comment]
This is a piece of CALICE detector brought in the H2 beam line for the next test beam run of HGCal. The geometry is different and also cell size are rectangular with SiPM readout.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
