### PR TITLE
Update RPC geometry fix in 2022 and 2023 MC GTs

### PR DESCRIPTION
**Pull request by saumyaphor4252**
#### PR description:
This PR updates the 2022 and 2023 MC GTs with the RPC geometry fix for the issue in the RPC chambers. More details regarding the tags updated and the original CMS Talk request for the update can be found in [[1]](https://cms-talk.web.cern.ch/t/fix-for-rpc-geometry-for-run3-data-and-mc/25678). 

[1] https://cms-talk.web.cern.ch/t/fix-for-rpc-geometry-for-run3-data-and-mc/25678

**GT Differences with the last ones are here**:

- **Phase1 2022 design**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/131X_mcRun3_2022_design_v2/131X_mcRun3_2022_design_v3

- **Phase1 2022 realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/131X_mcRun3_2022_realistic_v3/131X_mcRun3_2022_realistic_v4

- **Phase1 2022 realistic postEE**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/131X_mcRun3_2022_realistic_postEE_v3/131X_mcRun3_2022_realistic_postEE_v4

- **Phase1 2022 cosmics**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/131X_mcRun3_2022cosmics_realistic_deco_v3/131X_mcRun3_2022cosmics_realistic_deco_v4

- **Phase1 2022 cosmics design**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/131X_mcRun3_2022cosmics_design_deco_v2/131X_mcRun3_2022cosmics_design_deco_v3

- **Phase1 2022 realistic hi**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/131X_mcRun3_2022_realistic_HI_v7/131X_mcRun3_2022_realistic_HI_v8

- **Phase1 2023 design**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/131X_mcRun3_2023_design_v6/131X_mcRun3_2023_design_v7

- **Phase1 2023 realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/131X_mcRun3_2023_realistic_v6/131X_mcRun3_2023_realistic_v7

- **Phase1 2023 cosmics**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/131X_mcRun3_2023cosmics_realistic_deco_v6/131X_mcRun3_2023cosmics_realistic_deco_v7

- **Phase1 2023 cosmics design**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/131X_mcRun3_2023cosmics_design_deco_v6/131X_mcRun3_2023cosmics_design_deco_v7

- **Phase1 2023 realistic hi**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/131X_mcRun3_2023_realistic_HI_v11/131X_mcRun3_2023_realistic_HI_v12

#### PR validation:
GTs tested locally with `runTheMatrix.py -l 12034.0,11634.0,7.23,7.24,159.0,159.1,12434.0,160.1,12834.0  -j 8 --ibeos`

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:
Not a backport but `131X` and `130X` backports coming up right after

### CODE REVIEW

**Comment by saumyaphor4252** [comment]
@cmsbuild, please test

**Comment by saumyaphor4252** [comment]
@cmsbuild, please abort

**Comment by saumyaphor4252** [comment]
test parameters:

- workflows = 12034.0,11634.0,7.23,7.24,159.0,159.1,12434.0,160.1,12834.0

**Comment by francescobrivio** [comment]
There are a lot of differences, mainly in RPC and Muons directories, which is expected given that we are udpating the RPC geometry, FYI @mileva @jhgoh

But in workflow [12834.0](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_13_2_X_2023-06-29-1100+6376da/57738/12834.0_TTbar_14TeV+2024/) I see many changes in all directories, especially Tracking, FYI @cms-sw/tracking-pog-l2
 - Maybe because this is a 2024 workflow and this geometry was intended for 2023 only? @bsunanda could you chime in?

**Comment by mmusich** [comment]
> see many changes in all directories, especially Tracking, FYI

Rather unsurprising, given there are are differences at the level of SiStrip digis [link](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_13_2_X_2023-06-29-1100+6376da/57738/12834.0_TTbar_14TeV+2024/TrackerDigisV_TrackerDigis_Strip.html). The question is, if that is expected... I gather you don't (@cms-sw/trk-dpg-l2).

**Comment by francescobrivio** [comment]
@cmsbuild please test

 - reverted the 2024 MC GT, let's see the new comparison

**Comment by tvami** [comment]
test parameters:
  - workflows = 160, 160.02

**Comment by tvami** [comment]
@cmsbuild , please test
 * I want to see if the 2023 HI wfs have the same issue as the 2022 HI wfs

**Comment by tvami** [comment]
@saumyaphor4252 please modify the PR title so it reflects that 2024 is not updated anymore, thanks

**Comment by tvami** [comment]
@cmsbuild , please abort
 * actually I want to add more 2022 wfs too

**Comment by tvami** [comment]
test parameters:
  - workflows = 160, 160.02,159,159.03

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
I'm not sure what's going on, wf 159 uses the same phase1_2022_realistic_hi GT as the wf 312, one of them shows differences in tracking and the other does not:
Screen Shot 2023-07-10 at 12 11 29

--> i.e. this is not coming from the GT, but given there was 1 week diff from now and last time this was tested, it shouldnt even come from any other PR

**Comment by tvami** [comment]
chatted a bit with @mandrenguyen he pointed out that one diff between these two is that in one case the GENSIM is reused, while in the other it's regenerated. In case it's reused, I could imagine incompatibilities. 
 * Should we merge this and let the HS relvals figure out if there is anything wrong at all?

**Comment by mmusich** [comment]
> In case it's reused, I could imagine incompatibilities.

Should not this hold true for all wfs using recycled GS? Isn't there any other in the matrix? Also what about PU library used for mixing (generated with the old geometry)?

**Comment by bsunanda** [comment]
When the simulation geometry is changed, it is mandatory to regenerate the GEN-SIM step. We changed RPC and ZDC geometries in the past. So all previously generated GEN-SIM samples should be avoided for any comparisons.

Sunanda
________________________________

**Comment by tvami** [comment]
+alca
 * I propose we move this to a relVal campaign with proper stats and regenerated GENSIM

**Comment by mmusich** [comment]
>     I propose we move this to a relVal campaign with proper stats and regenerated GENSIM

shouldn't it be done upfront? we went through some pains to get the gen beamspot correct in the input samples when it was updated.

**Comment by rappoccio** [comment]
+1

as discussed at ORP meeting, will merge this and create relvals for higher-stats checks.

**Comment by mmusich** [comment]
> as discussed at ORP meeting, will merge this and create relvals for higher-stats checks.

So we are happy with broken IBs?

**Pull request merged**
