### PR TITLE
[DD4hep] Remove ".*:" aka "any" Namespace Definition from a Part Selector

### PR DESCRIPTION
**Pull request by ianna**
#### PR description:

* This allows the #31573 integration without splitting 
`Geometry/TrackerCommonData/data/PhaseI/trackerStructureTopology.xml`

This is the only XML file where ` .*: ` namespace is used. The old DD required this definition to attach the `Part Selector` to multiple nodes in various namespaces. Since this removal is fully tested in #31573, it's safe to assume the "any" namespace is not needed for DD4hep processing.

@ghugo83 and @cvuosalo - FYI, this solution is more performant then keeping this namespace and performing a regular expression comparison.

* Piggyback on this PR to improve performance by dropping a check on a top name - `split` takes care of it now.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
urgent

**Comment by ghugo83** [comment]
Hi @ianna 

This is quite useful. 
The `.*: `namespace appears in 
`Geometry/TrackerCommonData/data/PhaseI/trackerStructureTopology.xml`
But also in the following files:
```
Geometry/TrackerSimData/data/PhaseI/trackerProdCuts.xml:   
Geometry/TrackerSimData/data/PhaseI/trackersens.xml:   
Geometry/VeryForwardData/data/CTPPS_Cuts_Per_Region.xml:     
Geometry/VeryForwardData/data/CTPPS_Pixel_Sens.xml:        
Geometry/VeryForwardData/data/RP_Cuts_Per_Region.xml
```

**Comment by ianna** [comment]
> Hi @ianna
> 
> This is quite useful.
> The `.*: `namespace appears in
> `Geometry/TrackerCommonData/data/PhaseI/trackerStructureTopology.xml`
> But also in the following files:
> 
> ```
> Geometry/TrackerSimData/data/PhaseI/trackerProdCuts.xml:   
> Geometry/TrackerSimData/data/PhaseI/trackersens.xml:   
> Geometry/VeryForwardData/data/CTPPS_Cuts_Per_Region.xml:     
> Geometry/VeryForwardData/data/CTPPS_Pixel_Sens.xml:        
> Geometry/VeryForwardData/data/RP_Cuts_Per_Region.xml
> ```

a few birds with one stone :-)

**Comment by ghugo83** [comment]
A question: Does this fix the use of namespace for SpecPar section in general, or only the `.*: `namespace ?

My issue is that when I used the DD4hep filtered view on the Phase 2 Tracker:
`<PartSelector path="//tracker:BModule1Layer1"/>`
This should select only the volumes called `BModule1Layer1` which are defined in the tracker namespace, not those defined in the pixel namespace (IT).
But it was selecting both.

Is this also fixed?

**Comment by ianna** [comment]
> A question: Does this fix the use of namespace for SpecPar section in general, or only the `.*: `namespace ?
> 
> My issue is that when I used the DD4hep filtered view on the Phase 2 Tracker:
> `<PartSelector path="//tracker:BModule1Layer1"/>`
> This should select only the volumes called `BModule1Layer1` which are defined in the tracker namespace, not those defined in the pixel namespace (IT).
> But it was selecting both.
> 
> Is this also fixed?

this fixes only `.*:`. See my comment here https://github.com/cms-sw/cmssw/issues/31579#issuecomment-700570053

**Comment by ianna** [comment]
please test with #31605

**Comment by ianna** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
