### PR TITLE
Timing realistic sim pf

### PR DESCRIPTION
**Pull request by amartelli**
Introduce timing for realistic sim clusters, in HGCAL only.
Use algorithm optimized for TDR studies.
N.B. time is referred to the start of the BX, it is corrected for tof in the hypothesis of neutral and light particle: for longer track length and beta < 1 need offset correction at analysis level

The timing for the hits in HGCAL is enabled in the PR 
https://github.com/cms-sw/cmssw/pull/21957
 

@bendavid @rovere @felicepantaleo

### CODE REVIEW

**Comment by slava77** [comment]
@amartelli 
please justify the request for 10_0_X

In any case, any new feature PR should be submitted to the master branch first.

**Comment by slava77** [comment]
assign upgrade

**Comment by kpedro88** [comment]
There's no reason to put this in 10_0_X. It should go in master.

**Comment by amartelli** [comment]
Yes right. I will reopen a PR in the correct branch

**Pull request closed without merging**
