### PR TITLE
Hotfix to disable num_feddigistrend_per_Lumisection_per_FED plot

### PR DESCRIPTION
**Pull request by yimuchen**
The DQM plot "num_feddigistrend_per_Lumisection_per_FED"  is found to be too large and causing issues for the DQM GUI server. 
Minimum patch to disable this plots for the time being.

### CODE REVIEW

**Comment by dmitrijus** [comment]
please make an upstream port or close this PR (if you don't want to get it centrally merged)
We can still apply closed PRs for online DQM

**Comment by fioriNTU** [comment]
@enochnotsocool  you can close this PR, in 91X we will not have this problem.
@dmitrijus isn't it already included in the Online?

**Comment by enochnotsocool** [comment]
Closing PR, already in online, proper fix in 91X

**Comment by dmitrijus** [comment]
@fioriNTU It is. Point is - if it's not gonna get merged - don't have it open.

**Pull request closed without merging**
