### PR TITLE
Adding an accessor for groomed jet mass in 10.0.x

### PR DESCRIPTION
**Pull request by arizzi**
The JME recommendations for groomed masses changed since we implemented miniaod, so this adds some accessors to take the invariant mass of all groomed subjets, which gives the groomed jet mass.

This is also planned to be implemented in nanoaod. @rappoccio @gpetruc

Same as:
#21901 #21902

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
backport of #21902

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/21944	0e39d13 
- new pat::Jet::groomedMass accessors, needed for analysis
- the same topic branch as the 10_1_X/master version in #21902 
- jenkins tests pass

**Comment by arizzi** [comment]
@fabiocos if we want 10.0.X to become the analysis release (e.g. support NANOAOD)  this version of the additional pat::Jet accessors PR should be merged too.

**Comment by fabiocos** [comment]
merge

**Pull request merged**
