### PR TITLE
Adapt @express sequence for T0 [10_1_X]

### PR DESCRIPTION
**Pull request by schneiml**
backport of #23276

### CODE REVIEW

**Comment by dmitrijus** [comment]
+1

**Comment by boudoul** [comment]
Hello @schneiml , sorry to jump late , but why the changes are different to what you proposed ?
https://indico.cern.ch/event/688864/contributions/3000182/attachments/1646820/2632341/expresssequences.pdf

**Comment by fabiocos** [comment]
hold

**Comment by mmusich** [comment]
I also think that #23276 (equivalent to this in 10_2_X) shall be reverted.
In the description there is written 

> We are still waiting for confirmation from Tracker whether @common is correct for them.

AFAIK no confirmation was given before that PR was merged (@jandrea @arossi83)

**Comment by fabiocos** [comment]
@boudoul @mmusich thank you for raising this issue, and pointing to the discussion. @dmitrijus @jfernan2  was #23276 finally agreed between DQM and DPGs ? I took the signature as a confirmation, but apparently this is not the case: could you please clarify? As I would like to close CMSSW_10_2_0_pre5 on Monday sharp, we should better understand what to do before the week-end

**Comment by schneiml** [comment]
@mmusich be aware that neither of these PRs changes anything in production, except for some Run1 relvals (which does not really qulify as production, I guess). This is a *preparation* for production changes that need to be implemented by Tier0.

Also, confirmation was given orally in the core DQM meeting, IIRC. The final validation will happen with a Tier0 replay, but for that we need the changes in a release (not strictly, but it will be a lot less confusing).

**Comment by schneiml** [comment]
@boudoul the main change is using `@common` rather then `@commonSiStripZeroBias`, done on behalf of Tracker, because currently Express uses `@common` (via the default/null sequence, which is `DQMOffline`. 

Note that `@express` is currently not used for Express, and this PR exist for the sole purpose to change that.

**Comment by mmusich** [comment]
@schneiml, quite clearly we have very different views of what is production. Those run1 relvals (which are the only wf at the moment mimicking Tier-0) are *definitely* used as production by many users.
Anyway, event if this is for preparation, this is quite clearly wrong, because if it ends up being used in real express, several different crucial plots will disappear.

**Comment by schneiml** [comment]
@fabiocos I'd like to see #23276 (or this PR) relval'd, simply because the relvals are the only thing that it affects. Though, as mentioned before, these PRs don't change anything meaningful until T0 starts to use this sequence.

**Comment by mmusich** [comment]
> because currently Express uses @common (via the default/null sequence, which is DQMOffline.

Are you sure of this statement? 
IF I trust what you wrote in https://indico.cern.ch/event/688864/contributions/3000182/attachments/1646820/2632341/expresssequences.pdf (slide n.2) 
the `@common` sequence doesn't contain `pvMonitor` which we do use for alignment validation purposes and it's definitely available in the express DQM: https://goo.gl/g79Tp7
Please clarify.

**Comment by schneiml** [comment]
@mmusich re the run1 relavals, I can agree on that [1]. If there are indeed plots missing, then please point out which, and which sequences to enable.

If that implies refactoring `@commonSiStripZeroBias` into `@common` + `@X` so we can have both at the same time, I'd be very happy, but it is a lot more risky for production (we might have to rename plots etc.)

[1] Actually, I have a CMSSW philosophical question here: are these Relvals supposed to reproduce whatever was seen at the time this data was taken (then changing anything in this sequence would be a mistake), or are they supposed to run the latest-and-greatest code on the old data (then we should update them to the current T0 situation).

**Comment by mmusich** [comment]
> If there are indeed plots missing, then please point out which, and which sequences to enable.

I pointed out one in my message https://github.com/cms-sw/cmssw/pull/23351#issuecomment-393449796. I think it's Trk DQM job to make sure there are not others.

**Comment by schneiml** [comment]
@mmusich `pvMonitor` is part of `DQMOfflineTracking`, IIRC. Cleaning up that would be another step.

Actually, the difference between `@common` and `@commonSiStripZeroBias` is really just a trigger selection in one SiStrip plugin, a few plots turned on in that plugin, and a slightly different config for a Tracking plugin. But seeing that is _way too hard_ at the moment, and  a different issue.

**Comment by mmusich** [comment]
> Actually, the difference between @common and @commonSiStripZeroBias is really just a trigger selection in one SiStrip plugin, a few plots turned on in that plugin, and a slightly different config for a Tracking plugin.

OK. What about dumping the configuration with `print process.dumpPython()` once with one sequence and once with the other and showing the diff between the two to the TK DQM people? As things were presented, the change seemed much larger.
Also I don't see the case for changing the release just to see more clearly what is going to change. 
I think surely someone from dqm core could run those relvals for 100 event privately in the two cases and circulate the harvested files to the groups. 
my 2 cents.

**Comment by schneiml** [comment]
@mmusich I did construct the new sequence in a way that nothing should change, but there will of course be some differences in the long tail of rarely used DQM modules. I can try the config dump diff, I am afraid it will be giant but it is worth trying.

For a proper test, I'd just go for a T0 replay, because we will need that anyways, and it is the only way to be really sure what is happening.

**Comment by boudoul** [comment]
I believe that the conclusion for the PPD coordination yesterday was more to use a std relval validation rather than a T0 replay (@franzoni )

**Comment by schneiml** [comment]
I did the config dump diff: https://mschneid.web.cern.ch/mschneid/expressdifferences
with a bit of cleanup the differences are not very big, though there are some, esp. regarding totem/ctpps. 

@forthommel @nminafra @jan-kaspar do you look at Express DQM and need something included there?

**Comment by mmusich** [comment]
@schneiml thanks for this.

About the modules which would disappear, for tracker I am worried about these two guys:

```
process.MonitorTrackResiduals
process.refittedForPixelDQM
```

For tracking propably also these guys are relevant (@VinInn please confirm):
```
process.KshortMonitoring
process.KshortWlxy16Monitoring
process.LambdaMonitoring
process.LambdaWlxy16Monitoring
```

What about changes in configuration parameters of modules which are common among the two sequences?

**Comment by schneiml** [comment]
@mmusich I'd say there are no config changes. But then, I also fail to see any config changes between the old and new `@express` (that is `@common` vs. `@commonSiStripZeroBias`), so, I might have a problem with my method here.

**Comment by boudoul** [comment]
Thanks all for the checks,  I'm afraid here I should -1 for the Tracker. Changes proposed are not under control (not even requested and was not proposed, not sure I understand even the full motivation). DQM @ express is a crucial tool for checking the performance of the detector , quality of data and immediate feedback in case of issue. Therefore it requires to be functional at any moment.  I personnally find pretty dangerous to blindly inject changes  in the next data taking release without any check but 'the next T0 replay' . Happy to continue further the discussion maybe somewhere else , but at this point I cannot approve the changes in this backport. Sorry.

**Comment by fabiocos** [comment]
Dear all, any back-port will require a validation in master, and an agreement of all the stakeholders. even before this. Besides wf 1001.0 for 2011 data we have wf 1001.2 for 2017 data, and as already said I would like to add one for 2018 data. 

The sequences that we are running in wf 1001 are in general not those used originally that year, although we have eras for year specific customisations. But to me the real issue here is to understand whether there is consensus on the proposed change, and apparently this is not true, so we should consider to keep #23276 on hold until the situation is clarified. Having this sequence in the release will not impact T0 as this sequence is so far not used at Tier0, but of course if it has to be the basis for an update of the T0 configuration it should be agreed with all the potential users.

@schneiml I do not think we need a whole pre-release to test the sequence, it is used in a very limited number of relvals that are anyway not run in the regular RelVal production, as confirmed by PdmV experts. A test check can be done standalone, and I would strongly suggest to use more recent data.

**Comment by schneiml** [comment]
@fabiocos Thanks.

One thing we should keep on the table is that *currently there is no RelVal that represents Express well*. 1001.2 or also a 2018 version of it use `@express`, which, as of today, is very different from what T0 Express uses (`null`). That is not just a sub/superset issue (which would "only" matter for crashes etc.) but actually *different values in the same DQM plots* (due to `@commonSiStripZeroBias`). Removing this discrepancy is what these changes are all about.

This PR reduces the discrepancy a bit by moving the relval closer to production. The next step is then to move production to be identical to the relval. The validation of each of these steps is a bit more complicated, since we are actually *fixing* the workflows that should be used for validation...

**Comment by fabiocos** [comment]
@schneiml do you have a detailed comparison of the present sequence in a T0 PSet and @express? I think that the problems should be factorized into:

1) which is the sequence that people needs, regardless of what is the T0 default today? In my view your @express definition should have this target, especially when probed into a development cycle (and this is why #23276 was merged). @mmusich and @boudoul seem to point to some useful plots that your most recent @express definition would miss because of the move from @commonSiStripZeroBias to @common : are you planning to update it before pre5 is built at the beginning of next week? Or should we temporarily revert #23276 waiting for a further update?

2) ensure that T0 and whatever express-like test in the release are in sync, so as we may test in advance what we deploy in production, without the need to wait for a T0 replay or even worse for crashes in production. This is a separate problem, that should come after we have agreed on 1)

**Comment by schneiml** [comment]
@fabiocos re 1, I did construct this sequence based on feedback we got, including the explicit remark that `@common` should be used (though that was only orally so far, so if Tracker figures out differently in further checks, we have to change it [2]). I am fairly convinced that `@express` as of current master (incl. #23276) would be fine for production.

For a comparison of the completly unfolded configuration, that turned out to be more complicated than expected, since even if the *content* of the sequences is the same, the *structure* is different [3]. I am working on it, but I will not have time next week, so it is fine with me to postpone this PR for a while.

Re 2, currently 1001.2 and T0 Express production are far out of sync, and as far as I see they never were in sync (`@express` never appeard in the T0 config as far as the git history reaches). Also, `@express` of 10_1 releases could not be used for production, according to the feedback I got. We could sync 1001.2 to current production as an intermediate step (defining `'express':       ['DQMOffline',...]` should do it). The changes in this PR would synchronize them to the new definition as a side effect.

[2] However, I think that is unlikely, since `null == DQMOffline` is used in production and does not use the `SiStripZeroBias` versions of sequences.

[3] Fixing this would be another very useful refactoring, which I might work on in parallel. Though that will touch all production WF, so I'd rather not backport it. I think this also causes some confusion, e.g. around `pvMonitor`, which is in both sequences but that is very non-obvious...

**Comment by perrotta** [comment]
+1
- This is the same as #23352, plus a few DQM related commits: the additions here do not deal with reco, and therefore I sign this PR simply as a consequence of signing #23352 
- Both pull requests must be merged, because in #23352 a new commit has been added which is not (yet) included here
- I verified that the two PRs do not conflict each other and they can be merged in any order without rebasing

**Comment by perrotta** [comment]
Sorry, wrong thread: I am going to cancel my previous comment!

**Comment by fabiocos** [comment]
@schneiml thanks, I was about to suggest it

**Comment by schneiml** [comment]
@fabiocos we need to come back to that one we have 10_4 open, but the 10_1 PR is for sure no longer needed...

**Comment by fabiocos** [comment]
@schneiml absolutely

**Pull request closed without merging**
