### PR TITLE
Remove PhysicsTools/RooStatsCms

### PR DESCRIPTION
**Pull request by silviodonato**
As discussed at the ORP meeting and announced in some forums (eg. https://hypernews.cern.ch/HyperNews/CMS/get/higgs-combination/1438.html),
we are removing  PhysicsTools/RooStatsCms from CMSSW.

### CODE REVIEW

**Comment by silviodonato** [comment]
please test

**Comment by silviodonato** [comment]
please test

**Comment by silviodonato** [comment]
please test

**Comment by silviodonato** [comment]
@santocch, I had to remove also
```
 ElectroWeakAnalysis/ZMuMu/bin/hltEffwithCPError.cpp 
 ElectroWeakAnalysis/ZMuMu/bin/hltEffwithCPErrorMCvsDATA.cpp 
```
in general the package `ElectroWeakAnalysis/ZMuMu/` seems to be not used since 2011.

**Comment by santocch** [comment]
+1

**Comment by silviodonato** [comment]
@Dr15Jones @makortel @smuzaffar I simply removed `PhysicsTools/RooStatsCms` from ` Utilities/ReleaseScripts/scripts/git-publish` . Are you ok with it?

**Comment by smuzaffar** [comment]
+core

**Comment by silviodonato** [comment]
+1

**Pull request merged**
