### PR TITLE
Standard Propagator

### PR DESCRIPTION
**Pull request by a-kapoor**
Standard propagator now used in FastSim Tracking

No significant change in timing is observed !!

### CODE REVIEW

**Comment by ANSH0712** [comment]
please test

**Comment by ANSH0712** [comment]
[@cmsbuild,] please test

**Comment by lveldere** [comment]
please test

**Comment by lveldere** [comment]
+1

**Comment by davidlange6** [comment]
@ANSH0712 - could you add a comment about where the "standard propagator" is now used? e.g., "standard propagator now used in fastsim tracking" to the title for our release notes.
Thanks!

**Comment by ANSH0712** [comment]
@davidlange6 - Sure !!

**Comment by davidlange6** [comment]
+1

**Pull request merged**
