### PR TITLE
Fix debug build of L1Trigger/DTTriggerPhase2

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

Converted operator<< for DTPattern to take a const&. Needed when call from LogDebug.

#### PR validation:

Package now builds with -DEDM_ML_DEBUG

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by srimanob** [comment]
+Upgrade

Technical fix, no change is expected.

**Comment by cecilecaillol** [comment]
+l1

**Comment by qliphy** [comment]
+1

**Pull request merged**
