### PR TITLE
Modernize AutoMagneticFieldESProducer

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

This PR is an updated version of #27413 modernizing AutoMagneticFieldESProducer as part of #26748 by
- Merging header to source
- Removing ParameterSet member
- Making members const, set them in constructor initializer list
- Using trailing underscore for member variables
- Reducing copying of strings
- Using ESGetToken

The difference wrt. #27413 is that the recently-introduced mayConsume mechanism is used for the ESGetToken.

#### PR validation:

Code compiles, limited matrix runs.

### CODE REVIEW

**Comment by makortel** [comment]
FYI @Dr15Jones

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by namapane** [comment]
@makortel can we discuss plan a bit here? AutoMagneticFieldESProducer is obsolete, it should be removed, I think it makes no sense to update it.

**Comment by namapane** [comment]
(a bit of history: the producer was a first attempt at making the map adapt to the current read from DB, but was obsoleted after we moved the full MF configuration to DB. The module was not removed but is no longer necessary and at this point is better to remove it, also beacuse we won't make a corresponding DD4hep version.)

**Comment by namapane** [comment]
Of course - it makes no harm if this update is merged. I just want to point out that this module is about to be removed.

**Comment by makortel** [comment]
> can we discuss plan a bit here? AutoMagneticFieldESProducer is obsolete, it should be removed, I think it makes no sense to update it.

It was used in at least one runTheMatrix workflow back in May (I don't know if things have changed since). Here "used" means that it was part of the configuration, not that there was actually anyone consuming its product (because that was much easier to extract from the full matrix).

If it is really obsolete, I'm all in favor for removing it. Do you have a plan when would you remove it? Or should I do it now?

**Comment by namapane** [comment]
Ciao Matti,

If you wish, please go on. If it's used in runTheMatrix or elsewhere it 
should be replaced with the standard config, ie:

Configuration/StandardSequences/python/MagneticField_cff.py

As far as I can tell there is only this snippet in the release that uses it:

https://cmssdt.cern.ch/dxr/CMSSW/source/RecoTracker/TkNavigation/test/msGalore.py#54

which should fixed to use MagneticField_cff.py
(the valueOverride at L55 can be safely commented, as it just forces 
using the 3.8T map which is the default)

Also I see that it's listed here among all possible esmodules:
https://cmssdt.cern.ch/dxr/CMSSW/source/HLTrigger/Configuration/python/Tools/confdb.py#757

but I suppose this is an auto-generated list of modules/configs (?)
In no case is this module supposed to be used by HLT anyhow.

In addition to removing it we would need to remove the corresponding 
cff.py files in Engine/python and the friend declaration in 
MagGeoBuilderFromDDD.h.

If you can take care of this it would be great, otherwise I plan to do 
that togheter with other cleanups/updates in a couple of weeks from now.

**Comment by makortel** [comment]
Superseded by  #28162

**Pull request closed without merging**
