### PR TITLE
Run3-alca224 Make use of MessageLogger wherever possible in Calibration/IsolatedParticles and HcalIsolatedTrackReco packages and also extend the use of the macros

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Make use of MessageLogger wherever possible in Calibration/IsolatedParticles and HcalIsolatedTrackReco packages. Several macros in IsolatedParticles are modified to extend their performances 

#### PR validation:

Use the runTheMatrix test workflows

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by tvami** [comment]
@ChrisMisan I'll let you review this one, ok?

**Comment by ChrisMisan** [comment]
type hcal

**Comment by ChrisMisan** [comment]
please test

**Comment by ChrisMisan** [comment]
type performance-improvements

**Review by ChrisMisan — COMMENTED** [review]
@bsunanda I am seeing a lot of changes under /macros, can you please change the title accordingly and also squash the commits?

**Comment by ChrisMisan** [comment]
@bsunanda Can you also squash the commits to one?

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by ChrisMisan** [comment]
+alca

- no differences aside from msgLogger and MTD
- PR in line with the description

**Comment by ChrisMisan** [comment]
There are several places where iterative loop can be changed to the range based one e.g.
https://github.com/cms-sw/cmssw/pull/38780/files#diff-90ca2a7c21ff99e833a07c9d5f1004a273f7fafd1217286eefb9bf5dbd2b645cL120
Maybe it's worth considering for the future improvements.

**Comment by perrotta** [comment]
+1

**Pull request merged**
