### PR TITLE
RUn3-alca230X Fix some bugs and make the scripts workable for calibrating HCAL with Run3 data and MC

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Fix some bugs and make the scripts workable for calibrating HCAL with Run3 data and MC

#### PR validation:

Tested against Run3 data and MC

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by ChrisMisan** [comment]
type hcal, bugfix

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by tvami** [comment]
+alca
 * tests pass (tho I dont think there are unit tests for these scripts, they are also anyway under macros)

**Comment by perrotta** [comment]
+1

**Pull request merged**
