### PR TITLE
[14.0.X backport] RPCDigis validaiton module update

### PR DESCRIPTION
**Pull request by jhgoh**
#### PR description:

This is backport of #45029, update of RPCDigis validation modules.

#### PR validation:

Passes test with `runTheMatrix.py -l 12834.0`

#### If this PR is a backport please specify the original PR and why you need to backport that PR.

This is backport of #45029, already merged to the main branch.
We want to keep the same set of plots during the RPC validation procedure.

@mileva @mrcthiel

### CODE REVIEW

**Comment by tjavaid** [comment]
backport of #45029

**Comment by tjavaid** [comment]
please test

**Comment by tjavaid** [comment]
+1
- PR #45301 should fix the [missing](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-a08208/40080/dupDict/lostDefs.txt) HcalRecHitSoA dict.

**Comment by rappoccio** [comment]
+1

**Pull request merged**
