### PR TITLE
 [14_0_X] Update unpacker for L1T Calo scouting + DataFormat tests

### PR DESCRIPTION
**Pull request by Mmiglio**
Backport of https://github.com/cms-sw/cmssw/pull/44393 and Data Format tests of https://github.com/cms-sw/cmssw/pull/43984

#### PR description:

This PR updates the unpacker for L1T Calo scouting, following the upgrade of HW/SW upgrade of the scouting DAQ system.
Backported also data format tests for files produced with previous releases. 

#### PR validation:

The PR has been validated using data collected with the scouting system in the past week(s) and comparing results with L1T objects collected during CRAFT with the cdaq.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

backport of https://github.com/cms-sw/cmssw/pull/44393 and https://github.com/cms-sw/cmssw/pull/43984 to CMSSW_14_0_X for data tacking.

### CODE REVIEW

**Comment by smorovic** [comment]
please test

**Comment by rappoccio** [comment]
hold

* We need a justification as to why this new feature is being backported to the stable branch. Only bug fixes should be backported.

**Comment by Mmiglio** [comment]
Hi @rappoccio, 
We need this backport as the L1Scouting system hardware is changed, hence a slightly different unpacker is needed.
Moreover, as far as I understood, we need to be using the same CMSSW version as the HLT because of plans for common repacking.
On the other hand, touching the DataFormat tests is not really needed. I just thought it was a good Idea to align the changes, but of course I can restore the original version.

**Comment by smorovic** [comment]
please test

**Comment by smorovic** [comment]
+daq

**Comment by antoniovilela** [comment]
unhold

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
