### PR TITLE
Adding back thepeginterface -92x

### PR DESCRIPTION
**Pull request by alberto-sanchez**
needed for the jet energy calibration.  since 92x is the branch where the calibration is done.

needs externals:  thepeg and herwigpp

### CODE REVIEW

**Comment by efeyazgan** [comment]
please test

**Comment by alberto-sanchez** [comment]
the errors are expected, it needs thepeg 1.9.2p1 and herwigpp 2.7.1

**Comment by perrozzi** [comment]
please test with cms-sw/cmsdist#20597

**Comment by perrozzi** [comment]
please test with cms-sw/cmsdist#3437

**Comment by alberto-sanchez** [comment]
Look like the wrong version of thepeg has been used. External has not been compiled.

**Comment by efeyazgan** [comment]
Please test

**Comment by efeyazgan** [comment]
please test with cms-sw/cmsdist#3437

**Comment by efeyazgan** [comment]
+1

**Comment by davidlange6** [comment]
merge

**Pull request merged**
