### PR TITLE
Premix option c, with 2 tags, ECAL

### PR DESCRIPTION
**Pull request by amassiro**
First implementation of the ECAL run dependent MC

To be tested it needs this PR: https://github.com/cms-sw/cmssw/pull/27649

Physics details in the presentation at ECAL DPG here: https://indico.cern.ch/event/847097/

This PR will affect only the mixing step, when the premixed library is mixed with the hard scattering. The idea is that the pileup response, that has been simulated with a given transparency for ECAL crystals, will be scaled to match the transparency of the corresponding IOV.
A new object is introduced ( EcalLaserAPDPNRatiosMCRcd ), that has 1 single IOV, thus allowing this to be used as reference for scaling.
Goal: correct simulation of the photostatistics for pileup, when producing run dependent MC with several IOVs (main changes in run dependent MC for ECAL are transparency and noise).

This PR is needed for testing via relval, checking physics performance and possibly imploved data-MC comparison.

### CODE REVIEW

**Comment by amassiro** [comment]
Moved to 11_0_X in https://github.com/cms-sw/cmssw/pull/27974

**Comment by pohsun** [comment]
please test

**Comment by fabiocos** [comment]
@amassiro I guess you submitted to the wrong branch, you were intending this for master, am I correct?

**Comment by amassiro** [comment]
> @amassiro I guess you submitted to the wrong branch, you were intending this for master, am I correct?

Yes, sorry for the confusion.

This is the PR I created next.
https://github.com/cms-sw/cmssw/pull/27974

I suppose I can just close this one here, right?

**Comment by amassiro** [comment]
PR pureseeded by PR #27974

**Pull request closed without merging**
