### PR TITLE
bsunanda:Run2-sim04 Adding a dumping analyzer to diagnose if o/p is created using TestNumbering or not for HCAL

### PR DESCRIPTION
**Pull request by bsunanda**

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
@bsunanda , it is not possible to left even in a test a reference to a private file:
 file:/afs/cern.ch/user/a/amkalsi/public/ForSunandaDa/024A536E-48EE-E611-843A-001E67E71C95.root

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1
@bsunanda , in the same test directory there are many other tests which use as an input a simple name like "testMuon.root", "zee.root".... These test files are generated at previous steps or may be link somehow. Having these two concrete names left in this new test would be a problem in a long term.

**Pull request merged**
