### PR TITLE
Modification on r-phi distribution plots and fix on under/overflow bins in GEM onlineDQM, a backport to 12_0_X

### PR DESCRIPTION
**Pull request by quark2**
#### PR description:
Some requests on r-phi distributions are applied; finer binning on phi direction, more plots for digi.

Also, the under/overflow bins of 1D histograms are not displayed well. It has been fixed.

#### PR validation:
Tests are done and one can check again by `runTheMatrix` workflows

#### if this PR is a backport please specify the original PR and why you need to backport that PR:
This is a backport of #36230 and #36253 to CMSSW_12_0_X to be deployed on the current runs

@jshlee @watson-ij

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by jfernan2** [comment]
@quark2 is this backport in sync with master now?

**Comment by quark2** [comment]
Hi @jfernan2, 
Sorry for my late...

Not exactly... A type of plot was changed in the master branch when GEM validation codes were updated (#34821), which I didn't notice. I missed this point and made this unsync. Here is a commit for the sync.

Best regards, 
Byeonghak Ko

**Comment by jfernan2** [comment]
+1
Tested in Online playback DQM machine at P5

**Comment by qliphy** [comment]
+1

**Pull request merged**
