### PR TITLE
Better handling of timeout in FWCore/SharedMemory

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

The call to timed_wait will still take just as long as it takes the Worker to complete but will then return false if that time was longer than the set wait time.
Now we use transitionID_ to signify if the worker did the work and if it did, we ignore the timeout.
Added new `retry` methods which allow user control of what to do if a timeout does happen.

#### PR validation:

Code compiles and all framwork unit tests (including new ones) pass.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
Please test

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
