### PR TITLE
[BTVNano] add NegTag for UParT

### PR DESCRIPTION
**Pull request by Ming-Yan**
#### PR description:

Add Negative tag of UParT and deduced the output node to btvnano

#### PR validation:

passes the usual `runTheMatrix test: runTheMatrix.py -l limited -i all --ibeos`

### CODE REVIEW

**Comment by ftorrresd** [comment]
enable nano

**Comment by ftorrresd** [comment]
+1

**Comment by jfernan2** [comment]
+1

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
