### PR TITLE
remove CASTOR from CaloGeometryBuilder for 2023

### PR DESCRIPTION
**Pull request by kpedro88**
I realized that there was no need for CASTOR to be in the CaloGeometryBuilder list for the 2023 geometries, as it has been removed from all of them. I don't think this actually has any effect, but is just for cleanliness. (@ianna, please correct me if I'm wrong.) I also made the geometry script a tiny bit smarter.

@boudoul, when I reran the geometry script, I noticed from the diff that the D4 geometry did not have the HGCal volumes in CaloGeometryBuilder... not sure how that happened. @ianna, will this cause problems?

Tested with 20000.0 and 21200.0 (FourMu, 2023D1 and 2023D4).

### CODE REVIEW

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by ianna** [comment]
@kpedro88 - no, it shouldn't, but the relvals will tell us for sure.

**Comment by ianna** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
