### PR TITLE
[81X] PV-Validation for phase I 

### PR DESCRIPTION
**Pull request by mmusich**
backport of #16898 
Few miscellaneous fixes in the PV Validation tool to better deal with phase-I data:
   * allow dynamic selection via all-in-one metadata of the eta range of the probe track
   * allow selection of tracks avoiding either the barrel or the forward pixel partitions
   * allow choice of CPE used in the track refit (avoid templates for phase-I)
   * added aggregated canvases for the resolutions and pulls 
   * add steering of plotting style from ini metadata
   * add x- and y- transverse IP projections

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
@ghellwig @franzoni @arunhep:
is there any comment on this PR? If not please this sign-off, thanks.
M.

**Comment by ghellwig** [comment]
+1

**Pull request closed without merging**
