### PR TITLE
run3-alca240X Addition of one more Isolated bunch AlCaReco - backport of #40970 to version 13_0_X

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Addition of one more Isolated bunch AlCaReco - backport of #40970 to version 13_0_X

#### PR validation:

Use the runTheMatrix test workflows

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backported version

### CODE REVIEW

**Comment by bsunanda** [comment]
@tvami Please unhold this and approve this to go to 13_0_X

**Comment by tvami** [comment]
unhold
 * but there is some mismatch between what Maria told me is needed and the content of this PR, I wrote to her in Mattermost

**Comment by tvami** [comment]
>  I wrote to her in Mattermost

I'll approve after this is clarified

**Comment by mariadalfonso** [comment]
@bsunanda 
can you clarify what's the difference between the

HcalCalIsolatedBunchSelector--> this is already in the ZeroBias, and also in the T0 configuration 
https://github.com/dmwm/T0/blob/master/etc/ProdOfflineConfiguration.py#L1169

HcalCalIsolatedBunchFilter --> you are trying to add in the Commissioning  here (should be followed by a notification to the T0); can this module be replaced by the HcalCalIsolatedBunchSelector ?

**Comment by tvami** [comment]
I can sign this, but as mentioned by Maria

> should be followed by a notification to the T0

it needs to be propagated to the T0 config, it's not read from CMSSW directly

It would be nice if the questions under https://github.com/cms-sw/cmssw/pull/40980#issuecomment-1468040265 would be clarified

**Comment by tvami** [comment]
+alca
  * see https://github.com/cms-sw/cmssw/pull/40980#issuecomment-1475466345

**Comment by bsunanda** [comment]
The main difference is one used zero bias and the other needs jet trigger to ensure enough energy in HCAL

**Comment by tvami** [comment]
> it needs to be propagated to the T0 config, it's not read from CMSSW directly

I requested it to be added here
https://cms-talk.web.cern.ch/t/add-hcalcalisolatedbunchfilter-to-commissioning-pd-for-900-gev-collisions/21685

**Pull request merged**
