### PR TITLE
[DD4hep] Increase precision of Trapezoid definitions to prevent complaints from Native Geant4 10.7

### PR DESCRIPTION
**Pull request by cvuosalo**
Native Geant4 in the Geant4 IB performs strict tests on trapezoid solids, while VecGeom Geant4 used in the master is more lenient. Native Geant4 requires all trapezoid dimensions to be non-zero, and it requires trapezoid faces to be planar down to the nanometer scale.

The DD4hep big XML file in the DB uses precision 5 for solids. At this precision, the trapezoids `tidmodule0:TIDModule0StereoKaptonCut` and `tecmodule1s:TECModule1TopFrame2` get zero values for their `bl2` and `tl2` parameters. In fact, these two solids are not true Trapezoids and should probably be defined as Trd1 or something similar, but historically they were defined as Trapezoids with two vanishingly small but non-zero dimensions. In addition, at precision 5, some trapezoid faces show deviation from being planar at the nanometer scale.

Since the Run 3 geometry has been finalized, this PR attempts to make the smallest revision possible to remove the complaints from Native Geant4. In the revised DD4hep big XML file, the precision of Trapezoids (only) is increased from 5 to 8. In addition, the `bl2` and `tl2` parameters of Trapezoid `tecmodule1s:TECModule1TopFrame2` are increased from 5.e-14 to 5.e-8 millimeters. This new value should still be small enough to have the same effect as the original, but it doesn't require an excessive precision to represent.

After this PR, the revised DD4hep big XML file will be uploaded to the DB, and a PR will be submitted to put this big 
XML file into the DD4hep Global Tag. We can consider at that point whether the revised Global Tag will be suitable for 12_1. With the revision, regression will probably not be preserved since numeric values will change, but no significant changes would be expected.

This PR resolves issue #35655.

#### PR validation:

The revised big XML file from this PR was compared with the previous one to check that the only change was the addition of three digits to each Trapezoid parameter. Simulation was run with Native Geant4, and no complaints were generated.

Backporting to 12_0 is probably not advised at this late stage for 12_0.

### CODE REVIEW

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by civanch** [comment]
Yes, I think so.

**Comment by civanch** [comment]
We observed many times that a change of any dimension even of one volume on a tiny value make simulation history different in the first simulated ttbar event. The second event will start from the different random seed.

**Comment by perrotta** [comment]
> We observed many times that a change of any dimension even of one volume on a tiny value make simulation history different in the first simulated ttbar event. The second event will start from the different random seed.

Ok, it can make sense.
I expect this can be fully validated with the DD4Hep relvals in pre5, which I expect will be fully inspected before definitely switch to DD4Hep in pre6

**Comment by perrotta** [comment]
+1

**Pull request merged**
