### PR TITLE
[12.3.X] Add support of `TH1I` and `TH2I` in DQM 

### PR DESCRIPTION
**Pull request by mmusich**
backport of https://github.com/cms-sw/cmssw/pull/37665
backport of https://github.com/cms-sw/cmssw/pull/37795

#### PR description:

Title says it all, needed for a possible backport of https://github.com/cms-sw/cmssw/pull/37860 and https://github.com/cms-sw/cmssw/pull/37836 to be used for operations.

#### PR validation:

`cmssw` compiles.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

verbatim backport of https://github.com/cms-sw/cmssw/pull/37665  and #37795

### CODE REVIEW

**Comment by mmusich** [comment]
@sroychow FYI

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
+core

**Comment by fwyzard** [comment]
@cms-sw/dqm-l2 sorry for bothering you, could you review and sign this PR so we can include it in the next 12.3.x (patch) release ?

**Comment by emanueleusai** [comment]
+1

**Comment by perrotta** [comment]
+1
- Verbatim backport of the two PRs listed in the description, already merged in master since 12_4_X

**Pull request merged**
