### PR TITLE
Pixel local reco: reduce code duplication in SiPixelRawToDigi related code

### PR DESCRIPTION
**Pull request by czangela**
### PR description:

This PR should resolve some duplication issues, namely:
1. from #32483 reuse existing constants in `SiPixelRawToClusterGPUKernel`
2. #26731 avoid code duplication in `SiPixelRawToDigi` `ErrorChecker's`

Accordingly, the changes made can be categorized this way:
1. Reusing different bit manipulation constants in all the `ErrorCheckers`, as well as `PixelDataFormatter` and `SiPixelRawToClusterGPUKernel`
As part of this effort I introduced a new namespace with some `constexpr` variables and functions named `sipixelconstants` and placed it in `DataFormats/SiPixelDigi`. It should probably have a different name, and I suppose a more appropriate place would be `DataFormats/SiPixelRawToDigi`, but I let that the more experienced contributors decide. I just didn't want to do the fifth rebase yet.
2. Move common functions from `ErrorCheckerPhase0` and `ErrorChecker` (this is phase 1) to `ErrorCheckerBase`
This is really not harmful.

### PR validation:

Since this PR influences parts of the code which don't contribute to `DQM` histograms, there was a custom validation that took place.

Basically, I was just printing the `FED errors` before and after the changes and comparing them.

#### This is the description of this validation:

---
#### Phase 0 - workflow 136.731

1. Run workflow, modify # of events to `4000`
```sh
runTheMatrix.py -e -l 136.731 --ibeos -t 4 -j 0 --maxSteps=3
```

2. Run `step2` and `step3`
 During `step3` log events with `FED errors`.

3. Select events with at least one `FED error`:
    In repository `/afs/cern.ch/work/a/aczirkos/public/errorchecker_validation/phase1`
    the file `runlumievent.txt` contains `378` entries of `run:lumi:event`

4. With `edmPickEventy.py` use this file to filter the events
```sh
edmPickEvents.py "SinglePhoton/Run2016B-v2/RAW" <filename> --crab
```

5. Run with `crab`
```sh
crab submit -c pickevents_crab.py
crab getoutput
```

Example result file in repository `/afs/cern.ch/work/a/aczirkos/public/errorchecker_validation/phase0` the file `step2.root`

6. Run on reduced dataset `step3` before and after the changes.

Use some custom `LogDebug` to track error collection. Make sure that no messages get dropped (indicated at the end of some generated log file).

Example of adding `LogDebug` entry:
```diff
diff --git a/EventFilter/SiPixelRawToDigi/src/PixelDataFormatter.cc b/EventFilter/SiPixelRawToDigi/src/PixelDataFormatter.cc
index 5557f806144..02a177018b5 100644
--- a/EventFilter/SiPixelRawToDigi/src/PixelDataFormatter.cc
+++ b/EventFilter/SiPixelRawToDigi/src/PixelDataFormatter.cc
@@ -417,6 +417,11 @@ void PixelDataFormatter::unpackFEDErrors(PixelDataFormatter::Errors const& error
                                          DetErrors& nodeterrors) {
   const uint32_t dummyDetId = 0xffffffff;
   for (const auto& [errorDetId, rawErrorsVec] : errors) {
+	for (auto const& aPixelError : rawErrorsVec) {
+        LogDebug("FedErrors") << "DETID: " << errorDetId << "; FED: " << aPixelError.getFedId()
+                              << ", TYPE: " << aPixelError.getType() << ", WORD: " << aPixelError.getWord32()
+                              << ", MSG: " << aPixelError.getMessage();
+      }
     if (errorDetId == dummyDetId) {  // errors given dummy detId must be sorted by Fed
       nodeterrors.insert(nodeterrors.end(), rawErrorsVec.begin(), rawErrorsVec.end());
     } else {
```

Example `MessageLogger` entry for `cmsDriver.py` python config file:
```py
# Output info to file detailedInfo.log
process.MessageLogger = cms.Service("MessageLogger",
    destinations = cms.untracked.vstring('detailedInfo'),
    categories         = cms.untracked.vstring('FedErrors'),
    debugModules  = cms.untracked.vstring('*'),
        detailedInfo          = cms.untracked.PSet(
        threshold =  cms.untracked.string('DEBUG'),
        default    =  cms.untracked.PSet(limit = cms.untracked.int32(0)),
        INFO       =  cms.untracked.PSet(limit = cms.untracked.int32(0)),
        DEBUG   = cms.untracked.PSet(limit = cms.untracked.int32(0)),
        FedErrors = cms.untracked.PSet(limit = cms.untracked.int32(10000000))
    )
)
```

8. Compare the two log files

Extract lines with FED errors
```sh
grep DETID detailedInfo.log > errors01.log
```

##### Number # of FED errors by type in the validation data
```
      1 TYPE:30
     15 TYPE:31
    148 TYPE:37
    249 TYPE:40
```

In the repository `/afs/cern.ch/work/a/aczirkos/public/errorchecker_validation/phase0` there are the log files, root file and python config of the validation:
```sh
ls -halt /afs/cern.ch/work/a/aczirkos/public/errorchecker_validation/phase0 
total 238M
drwxr-xr-x. 2 aczirkos zh 2,0K máj  28 15.38 .
-rw-r--r--. 1 aczirkos zh  62K máj  28 15.38 step3.py
drwxr-xr-x. 4 aczirkos zh 2,0K máj  28 15.31 ..
-rw-r--r--. 1 aczirkos zh  36K máj  25 16.01 errors_01.log
-rw-r--r--. 1 aczirkos zh  36K máj  25 16.01 errors_02.log
-rw-r--r--. 1 aczirkos zh 7,1K máj  25 16.01 select_events.txt
-rw-r--r--. 1 aczirkos zh 237M máj  25 14.37 step2.root
```

One can compare the errors (in `bash` shell) such as
```sh
diff <(sort errors_01.log) <(sort errors_02.log)
```
In this example `errors_01.log` is before and `errors_02.log` is after changes.
They should have no differences.

---
#### Phase 1 workflow 136.816

1. Run workflow, only single-threaded
```sh
runTheMatrix.py -e -l 136.816 --ibeos -t 1 -j 0 --maxSteps=3
```

Since FED errors are more common in the phase 1 data, running on *100* events will suffice.

2. Basically do the same as with phase 0 just without steps 2-5. (since almost all events have errors)

##### Number # of FED errors by type in the validation data
```
  21500 TYPE:25
     93 TYPE:30
     55 TYPE:31
   6683 TYPE:37
```
Now from the repository `/afs/cern.ch/work/a/aczirkos/public/errorchecker_validation/phase1`
```sh
ls -halt /afs/cern.ch/work/a/aczirkos/public/errorchecker_validation/phase1/
total 882M
drwxr-xr-x. 2 aczirkos zh 2,0K máj  28 17.26 .
-rw-r--r--. 1 aczirkos zh 2,7M máj  28 17.25 errors_02.log
-rw-r--r--. 1 aczirkos zh 2,7M máj  28 16.49 errors_01.log
-rw-r--r--. 1 aczirkos zh  20K máj  28 15.38 step3.py
-rw-r--r--. 1 aczirkos zh 876M máj  28 15.36 step2.root
drwxr-xr-x. 4 aczirkos zh 2,0K máj  28 15.31 ..
```
And comparing the results (again, `errors_01.log` is before and `errors_02.log` is after changes)
```sh
diff <(sort errors_01.log) <(sort errors_02.log)
```
Again, no differences should appear.

### if this PR is a backport please specify the original PR and why you need to backport that PR:
it is not

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by civanch** [comment]
+1

**Comment by slava77** [comment]
enable gpu

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by jpata** [comment]
+reconstruction
- technical, no reco changes expected or observed neither in standard or GPU workflows

**Comment by qliphy** [comment]
+1

**Pull request merged**
