### PR TITLE
Run2-alca120 Modify the output contents of AlCaReco streams

### PR DESCRIPTION
**Pull request by bsunanda**
Add lumi scalars for iterative phi symmetry which will be used also for Radiation damage studies. Get rid of pre-rechit collection for HBHEMuonFIlter which is no longer needed for 2018 data taking

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@lpernie @arunhep Can you approve this PR?

**Comment by lpernie** [comment]
+1

**Comment by lpernie** [comment]
Assuming change in size is really negligible as told at Alca/DB meeting.
(we would like to see the number anyway)

**Comment by fabiocos** [comment]
+1

**Pull request merged**
