### PR TITLE
[12_3_X] Dump of the beamspot for DIP

### PR DESCRIPTION
**Pull request by francescobrivio**
#### PR description:
Backport of #37858
This PR adds the dump of the beamspot parameters that are the uploaded in DIP.

#### PR validation:
Code compiles and run `Online_BeamMonitor_file.py` in the test directory to check that the printed information is correct.

#### Backport:
Backport of #37858

FYI @gennai @dzuolo @sikler

### CODE REVIEW

**Comment by francescobrivio** [comment]
@cmsbuild please test

**Comment by francescobrivio** [comment]
backport of #37858

**Comment by francescobrivio** [comment]
@cmsbuild please test

 - issues in tests seem related to accessing remote files, let's try again

**Comment by tvami** [comment]
+db

**Comment by francescobrivio** [comment]
urgent

 - to be included in the next 12_3_X release for collisions

**Comment by emanueleusai** [comment]
+1

**Comment by emanueleusai** [comment]
tested successfully at P5

**Comment by perrotta** [comment]
+1

**Pull request merged**
