### PR TITLE
Updated FG bit definition including new fixes

### PR DESCRIPTION
**Pull request by mnorthup6690**
Hey guys. I would like to delete my old pull requests #11687 and #11842. This branch has the fixed fine grain bit definition for the HF. The previous branch had the FG bit implemented incorrectly.

### CODE REVIEW

**Comment by mulhearn** [comment]
I suspect this is too late for 76X...  @davidlange6 can comment further.  How do you know this improves data/MC agreement for the FG bit?

**Comment by mnorthup6690** [comment]
I looked at a recent run and compared the FG bits pulled directly from the data with the FG bits produced by the HcalTrigPrimProducer. They matched almost perfectly. I would also like to pull these changes into 75X if possible. I'm preparing a PR now.

**Comment by abdoulline** [comment]
These "endless" if-else sequences don't look aestetically nice (at all).
This could be realized by some "lookup" std::map<x,y>, where x can be
iphi's, y - GCTeta (in the first of those sequences) and then to use
map.find(x) for getting y...

**Comment by mulhearn** [comment]
please test

**Comment by mulhearn** [comment]
@davidlange6 just cleaning up loose ends.  Should we merge this just to keep 76X consistent with 75X?  Note that the 80X PR which addresses the code style request is already in place.  Or is it better to wait for the 80X PR to pass relvals and then backport?

**Comment by davidlange6** [comment]
I am cleaning up the 76x queue aside from things for analysis workflows. I'm closing this pull request, please make sure the PR is in 80x. Thanks!

**Comment by mulhearn** [comment]
Well, actually, it looks like this *didn't* actually make it into 80X for some reason... we'll track this here:

https://github.com/cms-l1t-offline/cmssw/issues/79

**Pull request closed without merging**
