### PR TITLE
Phase2-sim148 Update some of the scriptss and correct the comments

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Update some of the scriptss and correct the comments

#### PR validation:

Use the scripts to make some studies for all Phase2 scenarios

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by tjavaid** [comment]
please test

**Comment by srimanob** [comment]
> please test

Hi @tjavaid 
Why do we need to re-test here?

**Comment by tjavaid** [comment]
+1

**Pull request merged**
