### PR TITLE
fix header L1Trigger/L1TMuonOverlap

### PR DESCRIPTION
**Pull request by mrodozov**
Fix headers related to #15248
We start enforcing the rule today to fail the PR if it doesn't comply with the header check.
The remaining headers to be fixed are currently - 1, for which we are adding an exception until the issue opened about that header is addressed

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@nsmith-, @rekovic, @thomreis , can you please sign this?

**Comment by fabiocos** [comment]
+1

trivial technical fix

**Comment by fabiocos** [comment]
merge

**Pull request merged**
