### PR TITLE
fix DQM core config and SiPixelPhase1Summary + align master to 90x updates (MeasurementTrackerEventProducer)

### PR DESCRIPTION
**Pull request by mtosi**
as discussed in PR https://github.com/cms-sw/cmssw/pull/18252
this PR is meant to fix the master 
- DQM/Integration/python/clients/hlt_dqm_sourceclient-live_cfg.py
- DQM/Integration/python/config/inputsource_cfi.py
- DQM/SiPixelPhase1Summary/src/SiPixelPhase1Summary.cc
and align some code which will enter in 90x while they were missing in the master
- RecoTracker/MeasurementDet/plugins/MeasurementTrackerEventProducer.cc

### CODE REVIEW

**Comment by slava77** [comment]
@mtosi 
please change to a descriptive title

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
+1
A few protections added to RecoTracker/MeasurementDet/plugins/MeasurementTrackerEventProducer.cc
(Still, I would prefere to have files in 91X and in 90X, as in the proposed #18252, identical line by line, and not only "functionally identical", as it would ease both review and maintainement. I think this can be done in the backport PR, where there are a few more files that could profit of such a synchronization)

**Comment by mtosi** [comment]
ciao
after having checked, I copied-and-pasted RecoTracker/MeasurementDet/plugins/MeasurementTrackerEventProducer.cc from 90x here

hope it is fine, now
thanks (and sorry the confusion)

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
+1
(once again, as in https://github.com/cms-sw/cmssw/pull/18520#issuecomment-298606074)

**Comment by dmitrijus** [comment]
+1
this will conflict with https://github.com/cms-sw/cmssw/pull/18538

I don't care which PR is merged first, but the other one will have to resolve the conflict :)

**Comment by davidlange6** [comment]
hi @mtosi - please rebase. Thanks

**Comment by mtosi** [comment]
rebase done, and resolved conflict as well
.. next time, please, do the other way round, if possible

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
they were merged in the order of being signed and tested. if some other order is desired specific instructions (or better a "hold" from @dmitrijus) are needed.

**Comment by perrotta** [comment]
+1
(again...)

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
