### PR TITLE
Offline validation for 74X collisions and cosmics

### PR DESCRIPTION
**Pull request by hroskes**
CondDBv2 and ROOT6 compilation.  Also in 75X as #9552, without the CondDBv2 part because as I understand it CondDBv2 is the default in 75X.

I explicitly checked that this, #9536, and #9550 are all orthogonal to each other.

### CODE REVIEW

**Comment by diguida** [comment]
@hroskes you should open also a corresponding PR in 75X. We cannot sign this until the corresponding 75X version is included.

**Comment by diguida** [comment]
please test

**Comment by hroskes** [comment]
@diguida done in 75X.  Do I understand correctly that I don't need to explicitly switch to CondDBv2 in 75?

**Comment by diguida** [comment]
@hroskes that's correct. In that release, we changed the default to be V2 on the AlCa side too.

**Comment by mmusich** [comment]
failures in test are unrelated to the PR

**Comment by diguida** [comment]
please test

**Comment by mmusich** [comment]
+1

**Comment by hroskes** [comment]
I'm so sorry... I just noticed I made this PR for 75X instead of 74X.  I have to close it and start over.

**Pull request closed without merging**
