### PR TITLE
Fix jet ordering in MvaMEtUtilities class 75X

### PR DESCRIPTION
**Pull request by mmarionncern**
Same as #9961 for 75X

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
+1

For #9962 b71d572e3b20f672f306bc054458b15cb067a46a

Small change to improve sorting of jets for MET MVA. It should not have an effect on standard sequences. The 74X version of this PR, #9961, has already been approved by Reco.

The code change is satisfactory, and Jenkins [tests](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-9962/684/summary.html) against baseline CMSSW_7_5_X_2015-07-01-2300 show no significant differences, as expected.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
