### PR TITLE
Moving to 2018 Cosmic WFs and Re-adding 2016-2017 Cosmic WFs (10_2_X)

### PR DESCRIPTION
**Pull request by boudoul**
Backport of #25137
Updating runthematrix cosmic WFs with the latest and greatest 2018 Cosmic GTs
The corresponding WFs are 7.2 , 7.3, 7.4

This PR is also backporting #25249 and #25276 to be fully in synch with 10_4 X (adding 2017-2016)
The corresponding WFs are 7.21 , 7.22
Thanks @lpernie for having provided the GTs

@mmusich @tsusa FYI

### CODE REVIEW

**Comment by prebello** [comment]
please test workflow  7.2,7.3,7.4 with #25127

**Comment by kpedro88** [comment]
+upgrade

**Comment by zhenhu** [comment]
+1

**Comment by fabiocos** [comment]
@boudoul could you please update it according to the 10_3_X and 10_4_X implementations, so as we can merge it?

**Comment by boudoul** [comment]
Hi @fabiocos I just updated to be in synch , sorry for the delay

**Comment by prebello** [comment]
@boudoul  thank you for your changes. Nevertheless, there is a typo. You have added 7.22 for both UP17 and UP16. Could you please fix it?

**Comment by boudoul** [comment]
Thanks @prebello for noticing ! 
fixed in my last commit

**Comment by fabiocos** [comment]
@prebello the PR looks ok to me to go, I would like to include it in next 10_2_X version I would like to build soon

**Comment by prebello** [comment]
+1

sure @fabiocos  go ahead

**Comment by fabiocos** [comment]
+1

@kpedro88 although not specific for upgrade, please sign it for reference

**Comment by fabiocos** [comment]
merge

**Comment by kpedro88** [comment]
+upgrade

**Pull request merged**
