### PR TITLE
Switching BoostedDoubleSV tagger to v4 training for AK8 jets

### PR DESCRIPTION
**Pull request by ferencek**
New BoostedDoubleSV tagger training for AK8 jets presented in https://indico.cern.ch/event/596134/contributions/2413751/attachments/1391765/2120352/double-b-v4.pdf

Request to add new training to externals is here https://github.com/cms-sw/cmsdist/issues/2788

@cvernier

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/17294	024c723
- change in the training file version as described; this affects only pfBoostedDoubleSecondaryVertexAK8BJetTagsAK8Puppi (in miniAOD); there is no monitoring of this, apparently 
- jenkins tests pass and comparisons with baseline show no difference

**Comment by davidlange6** [comment]
+1

**Pull request merged**
