### PR TITLE
EMTF: Improve protection against corrupted LCT data (11_1_X)

### PR DESCRIPTION
**Pull request by jiafulow**
#### PR description:

This is a backport of #30830 to the 11_1_X series. The content of this PR is identical to that of #30830 . 

#### PR validation:

Please see #30830 .

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Please see #30830 . This is requested for 11_1_X because it might be needed for the next MWGR.

---
Notifications: @eyigitba

### CODE REVIEW

**Comment by silviodonato** [comment]
please test

**Comment by andrius-k** [comment]
Hi all,
We have tested PR in the DQM playback system replaying the run 336345 and `l1tstage2emulator` is no longer crashing.
Regards,
Andrius (for Core DQM)

**Comment by boudoul** [comment]
Ping @rekovic

**Comment by silviodonato** [comment]
urgent

**Comment by silviodonato** [comment]
@rekovic

**Comment by silviodonato** [comment]
please test

**Comment by jiafulow** [comment]
The failure seems unrelated to this PR:

- WF 136.88811: DQM/TimerService/process PAT allocated. It measures memory allocation (kB) which went from 2.714e+05 to 271444 -- basically no difference.

**Comment by silviodonato** [comment]
To be merged in the next CMSSW_11_1_X release

**Comment by boudoul** [comment]
It would be good to get the signature of @rekovic ......

**Comment by silviodonato** [comment]
merge

**Comment by silviodonato** [comment]
@rekovic this is a backport of to https://github.com/cms-sw/cmssw/pull/30830

**Pull request merged**
