### PR TITLE
silence static-analyzer warnings in `HLTConfig{Data,Provider}`

### PR DESCRIPTION
**Pull request by missirol**
#### PR description:

The use of the methods `edm::ParameterSet::exists` and `edm::ParameterSet::existsAs` leads to warnings issued by the static analyser (SA). In my understanding, this is done to discourage the use of these methods as a way to compensate for missing, or incomplete, implementations of `fillDescriptions` methods in the corresponding plugins.

Many (~40%) of the SA warnings from HLT packages originate from `exists` and `existsAs` calls in the classes `HLTConfigData` and `HLTConfigProvider`. The latter need to inspect the global process PSet to work as intended. In this case, the use of `exists` and `existsAs` calls seems justified and unavoidable (and is not related to the lack of `fillDescriptions` methods).

This PR adds the macro `CMS_SA_ALLOW` to these calls in `HLTConfig{Data,Provider}` in order to silence the corresponding SA warnings.

Unrelated to the purpose of this PR, some minor technical cleanup in `HLTConfigProvider` is also applied (removal of spurious `endl`s from `MessageLogger` calls).

While working on this PR, an issue with `CMS_SA_ALLOW` was found (#43646), and #43678 fixed it. This PR technically does not depend on #43678, but it requires the latter in order to work as intended.

Merely technical. No changes expected.

#### PR validation:

I reproduced the SA warnings with the pseudo-recipe below. Using this PR plus #43678, the warnings due to `HLTConfig{Data,Provider}.cc` disappear.
```bash
[..]
git cms-addpkg HLTrigger/HLTcore
git cms-addpkg Utilities/StaticAnalyzers
scram b
USER_LLVM_CHECKERS="-enable-checker threadsafety -enable-checker optional.ClassChecker -enable-checker cms -enable-checker deprecated -disable-checker cms.FunctionDumper" scram b -k checker  SCRAM_IGNORE_PACKAGES=Fireworks/% SCRAM_IGNORE_SUBDIRS=test > class+function-checker.log 2>&1
```

#### If this PR is a backport, please specify the original PR and why you need to backport that PR. If this PR will be backported, please specify to which release cycle the backport is meant for:

N/A

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by mmusich** [comment]
S/A log looks indeed cleaner now: https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-03196d/36749/llvm-analysis/

**Comment by mmusich** [comment]
+hlt
   * technical, silences some S/A warnings related to  `edm::ParameterSet::exists` and `edm::ParameterSet::existsAs` (see https://github.com/cms-sw/cmssw/pull/43679#issuecomment-1882837992) and supplies some other unrelated minor clean-up in log messages handling.

**Comment by mmusich** [comment]
> -1

das errors are unrelated. Will re-trigger the test, just to have a clean set of signatures.

**Comment by rappoccio** [comment]
+1

**Pull request merged**
