### PR TITLE
L1T DemonstratorTools: support transparent compression of pattern files

### PR DESCRIPTION
**Pull request by gpetruc**
#### PR description:

This PR updates the DemonstratorTools package to support transparent compression of files pattern files if they end up with `.gz` (gzip) or `.xz` (lzma), using boost iostreams. 

This feature is already implemented in other tools outside CMSSW that work with pattern files, in the [emp software framework](https://gitlab.cern.ch/p2-xware/software/emp-toolbox/-/merge_requests/121) and [correlator trigger tools](https://gitlab.cern.ch/cms-cactus/phase2/firmware/correlator-common/-/commits/master-125x/utils/patterns.py) so having the feature in CMSSW is useful.

For the moment lzma is not recommended since the other emp software tools don't support it as they're built on a version of boost iostreams without lzma, but since that may change in the future and adding lzma is only 5 extra lines of code I thought it was easier to just add it already in CMSSW.

The PR also updates the costructor of the BoardDataWriter to make the extension of the file configurable, and updates the pieces of C++ code using that class in CMSSW to add this extra parameter.
 * @tswilliams If you prefer, I can add an additonal constructor that doesn't take the file extension to keep backwards compatibility.
* The behaviour of the GTT dumpers in DemonstratorTools is unchanged, the output remains an uncompressed text file.
* The configuration of the Correlator pattern dumpers in Phase2L1ParticleFlow is updated to use compressed files and also to switch to the new EMP format introduced in #41768 above
* I have also a version of the Phase2L1ParticleFlow which introduces `fillDescriptions()` for the Correlator Layer 2 e/gamma L1TCtL2EgProducer (@cerminar), I can either include it in this PR or leave it for the later bigger PR that adds `fillDescriptions()` also for the Correlator Layer 1 producers. You can see the diff in https://github.com/gpetruc/cmssw/compare/DemonstratorTools_compression_master...L1TCtL2EgProducer_fillDescriptions_master 

Note that pattern file production is not run in any production workflow

The PR was tested with the usual code checks + `runTheMatrix -l 23234.0` (to check nothing got broken elsewhere) and `L1Trigger/Phase2L1ParticleFlow/test/make_l1ct_binaryFiles_cfg.py` (which runs the correlator emulator + pattern file producers)

A PR to cms-l1t-offline is also under way

### CODE REVIEW

**Comment by gpetruc** [comment]
@cmsbuild, please test

**Comment by tswilliams** [comment]
Hi @gpetruc 

> @tswilliams If you prefer, I can add an additonal constructor that doesn't take the file extension to keep backwards compatibility.

I think it's fine without an additional backwards-compatible constructor. But on that point, I'll just mention @EmyrClement here so he's aware that he might have to update the HGC code to add the extra constructor argument in future.

After looking through the code, my only other comment is that it would be good to add a check on `fileExt` in the `BoardDataWriter`, so that it throws an exception if the extension isn't `txt`, `txt.gz` or `txt.xz` - to make it clear to people straight away if they make a mistake there.

**Comment by aloeliger** [comment]
+l1

**Comment by gpetruc** [comment]
Added the check following @tswilliams's suggestion

**Comment by aloeliger** [comment]
+l1

**Comment by srimanob** [comment]
+Upgrade

From upgrade side, the relevant code is on `L1Trigger/Phase2L1ParticleFlow`, where the configuration is updated with extra parameters.

**Comment by perrotta** [comment]
+1

**Pull request merged**
