### PR TITLE
Configure Geant4 physics list to be similar to GeantV

### PR DESCRIPTION
**Pull request by civanch**
For comparison of the default Geant4 and new GeantV tracking an equivalent to GeanV EM physics constructor is proposed, where only gamma, e+, e- interactions are included.

This PR should not affect any production.

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by civanch** [comment]
@kpedro88 , this is one to one GeantV PhysList.

**Comment by kpedro88** [comment]
thanks @civanch

**Comment by fabiocos** [comment]
+1

**Pull request merged**
