### PR TITLE
[12_4_X] add DT and CSC rechits to AOD content

### PR DESCRIPTION
**Pull request by kakwok**
#### PR description:

Backport of #40251 for 2022 data re-processing and signal MC production.

This PR adds CSC/DT rechits to the AOD datatier, which are the essential inputs for multiple searches of LLP decaying in the muon system and evaluating related trigger performances

#### PR validation:

Backport of #40251

### CODE REVIEW

**Comment by clacaputo** [comment]
please test

**Comment by clacaputo** [comment]
Hi @kakwok , what is the reason for this backport?
Consider that for 2022 MC it could be possible to create a new chain in MccM for some samples; instead, for 2022 data it's not possible, the workflows are already in place.

FYI @cms-sw/pdmv-l2

**Comment by sixie** [comment]
@clacaputo : The purpose for the backport is to be able to use it for additional 2022 MC production. Our signal production has not started yet, so this is an opportunity to have the DT and CSC hits available in AOD for the new signal MC.

**Comment by clacaputo** [comment]
Hi @smuzaffar, the bot reports `ROOTFileChecks: Some differences in event products or their sizes found`, is there a list of the differences somewhere in `summary.html`?

**Comment by cmorgoth** [comment]
Since this PR adds CSC/DT rechits to the AOD datatier we expect to be some differences in the event size.
Considering this is urgent for the MC production for early Run3 analysis can we please proceed?

**Comment by clacaputo** [comment]
enable profiling

**Comment by clacaputo** [comment]
please test

**Comment by clacaputo** [comment]
+reconstruction

**Comment by perrotta** [comment]
hold
- As it was suggested at the ORP meeting of Feb 21, this can be implemented as a customization in those few productions that need it in the closed 12_4_X cycle

**Comment by sixie** [comment]
@perrotta : can you explain what the suggestion is? We would like this modification for ALL MC productions for 2022. not just "a few". It should be the default.

**Comment by clacaputo** [comment]
> @clacaputo : The purpose for the backport is to be able to use it for additional 2022 MC production. Our signal production has not started yet, so this is an opportunity to have the DT and CSC hits available in AOD for the new signal MC.

@sixie Here you claim that you need this PR only for the new "signal MC", not for all the MC productions. Based on the info you provided, we decided to propose you to add the new collections through a `cmsDriver` customization

**Comment by tvami** [comment]
Requested PdmV to make new chains in https://its.cern.ch/jira/projects/PDMVMCPROD/issues/PDMVMCPROD-105
After chains are done, there is no need for this PR, we can just make samples specifying the chains that will save the muon hits.

**Comment by tvami** [comment]
@cmsbuild , please close
 * signal samples are being produced with this content, w/o the need of this PR

**Pull request closed without merging**
