### PR TITLE
clang check readability-redundant-string-cstr

### PR DESCRIPTION
**Pull request by davidlange6**
for comment about what clang-tidy does to CMSSW (and likely big and not mergeable - this is what clang-tidy check readability-redundant-string-cstr does on the tip of CMSSW_9_3_X as of a few days ago

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by slava77** [comment]
+1

looks OK and apparently also compiles and introduces no changes

**Comment by davidlange6** [comment]
please test
(also for consideration for merging)

**Comment by Dr15Jones** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Comment by fwyzard** [comment]
-1

**Comment by fwyzard** [comment]
Nothing touching DQMOffline/Trigger should be considered for merging until all the pending PRs have been merged.

**Comment by civanch** [comment]
+1

**Pull request closed without merging**
