### PR TITLE
 SiStrip Bad channel estimation from FED error

### PR DESCRIPTION
**Pull request by suchandradutta**
Bad channel from FED errors

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
+1
base on discussion in https://github.com/cms-sw/cmssw/pull/13888

**Comment by davidlange6** [comment]
@suchandradutta - right, to help us not forget I'll open an issue for this change - what is the tracker goal for having it complete?

**Comment by boudoul** [comment]
thanks @suchandradutta and @davidlange6 - We are assigning now this task within the DPG with the aim of being done by summer- We can keep you posted to follow progress (and difficulties if any..)

**Pull request merged**
