### PR TITLE
Try a second time if pop fails in ReusableObjectHolder

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

Experience has shown that for some builds, tbb::concurrent_queue try_pop appears to falsely fail. Adding a second attempt to try to decrease that frequency.

#### PR validation:

Code compiles and the related unit test passes.

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
@cmsbuild, please test for slc7_aarch64_gcc11

**Comment by Dr15Jones** [comment]
So I looked at the implementation of oneApi::tbb::concurrent_queue::try_pop and they make use of `std::memory_order::relaxed` in a couple of places which could definitely lead to the false positives.

**Comment by makortel** [comment]
On a sample of one test, this didn't seem to fully cure the "issue"
```
===== Test "testFWCoreUtilities" ====
Running ............................... # seen: 3 3
F...

reusableobjectholder_t.cppunit.cpp:241:Assertion
Test name: reusableobjectholder_test::testSimultaneousUse
assertion failed
- Expression: t1ItemsSeen.size() > 0 && t1ItemsSeen.size() < 3

Failures !!!
Run: 34   Failure total: 1   Failures: 1   Errors: 0

---> test testFWCoreUtilities had ERRORS
```
(whether it had an impact on the distribution of elements in the ReusableObjectHolder would require larger scale test)

**Comment by makortel** [comment]
-1

Per our discussion earlier, a different approach would be needed.

**Pull request closed without merging**
