### PR TITLE
GEM Online & Offline Efficiency Update (backport of #37954, 12_3_X)

### PR DESCRIPTION
**Pull request by seungjin-yang**
#### PR description:
This PR is a backport of https://github.com/cms-sw/cmssw/pull/37954. This PR turns on the muon propagation error cuts, which mistakenly were turned off via https://github.com/cms-sw/cmssw/pull/36883. Also, this PR simplifies the directory structure in the DQM output file and reduces redundant plots. In the offline DQM, the way to build the initial state muon propagations and a matching metric is changed. You can find more details [here](https://indico.cern.ch/event/1161504/contributions/4878468/attachments/2444237/4188150/SYang_220515.pdf).
From a technical point of view, this PR adds base classes for online and offline efficiency monitors.

#### PR validation:
Because this PR affects both the online and the offline DQM, this PR was validated with two tests.
- For the online DQM,
```bash
CMSSW_VERSION=CMSSW_12_3_X_2022-06-09-2300
cmsrel ${CMSSW_VERSION}
cd ${CMSSW_VERSION}/src
git-cms-merge-topic GEM-DQM-Eff-Update_from-${CMSSW_VERSION}
git-cms-addpkg DQM/Integration
cmsRun ${CMSSW_BASE}/src/DQM/Integration/python/clients/gem_dqm_sourceclient-live_cfg.py unitTest=True
```

- For the offline DQM,
```bash
CMSSW_VERSION=CMSSW_12_3_X_2022-06-09-2300
cmsrel ${CMSSW_VERSION}
cd ${CMSSW_VERSION}/src
git-cms-merge-topic GEM-DQM-Eff-Update_from-${CMSSW_VERSION}
runTheMatrix.py -w upgrade -l 11611.0
```

#### if this PR is a backport please specify the original PR and why you need to backport that PR:
Backport of #37954. In 12_3_X, the propagation error cuts mistakenly are turned off, resulting in a lower GEM detection efficiency than expected. So, I decided to backport #37954 to 12_3_X.

### CODE REVIEW

**Comment by seungjin-yang** [comment]
@jshlee @quark2

**Comment by emanueleusai** [comment]
please test

**Comment by emanueleusai** [comment]
testing at P5

**Comment by emanueleusai** [comment]
type gem

**Comment by emanueleusai** [comment]
backport of #37954

**Comment by emanueleusai** [comment]
tests at P5 completed successfully

**Comment by emanueleusai** [comment]
+1

**Comment by perrotta** [comment]
> #### PR description:
> This PR is a backport of #37954. This PR turns on the muon propagation error cuts, which mistakenly were turned off via #36883. 

Just to understand: is this large PR needed as a whole in the data-taking release 12_3_X just to turn on the muon propagation error cuts? If that's the only reason, perhaps a simpler fix could have been enough. 

By the way, with respect to the PR in the master here the files that implement the GEMOfflineDQMBase class are not removed: was there any reason for it?

**Comment by seungjin-yang** [comment]
Hi @perrotta, this PR not only turns on propagation error cuts but also provides a more reliable GEM detection efficiency measurement. So, I want to backport this PR to 12_3_X.
Also, I removed `GEMOfflineDQMBase`, which was replaced by `GEMDQMEfficiencySourceBase`. Thank you for pointing this out!

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
+1
- Identical backport of https://github.com/cms-sw/cmssw/pull/37954, already [tested at P5](https://github.com/cms-sw/cmssw/pull/38330#issuecomment-1159372019)
- It fixes and simplifies the DQM plots for GEM

**Pull request merged**
