### PR TITLE
Move ME0 trigger primitive producers from DIGI to L1 step

### PR DESCRIPTION
**Pull request by dildick**
#### PR description:

Similar as PR #28254. To be integrated after #28183.

The ME0 pad producer has been moved to the L1T step. The ME0 pad cluster producer has been switched off, as ME0 pads will not be clustered in contrast to GE1/1 and GE2/1, according to the Phase-2 L1T design. I also enabled the ME0TriggerProducer in the L1T step in preparation for algorithm development in 2020. 

#### PR validation:

I checked that it runs with WF 22034.0 in CMSSW_11_0_X_2019-10-31-1100

#### if this PR is a backport please specify the original PR:

N/A

@tahuang1991

### CODE REVIEW

**Comment by kpedro88** [comment]
please test

**Comment by kpedro88** [comment]
+upgrade

**Comment by fabiocos** [comment]
@rekovic @civanch could you please have a look?

**Comment by civanch** [comment]
+1

**Comment by rekovic** [comment]
+1

**Comment by dildick** [comment]
Thanks!

**Comment by fabiocos** [comment]
+1

**Pull request merged**
