### PR TITLE
[13_0_X] Revert BeamSpot fallback logic

### PR DESCRIPTION
**Pull request by francescobrivio**
#### PR description:
Verbatim backport of #42284
This PR reverts the online BeamSpot fallback logic to actually fall back to the DB, ie. to consume the last BeamSpot produced by PCL.

#### PR validation:
See master PR for validation

#### Backport:
Backport of #42284

### CODE REVIEW

**Comment by francescobrivio** [comment]
backport of #42284

**Comment by francescobrivio** [comment]
test parameters:
-  addpkg = DQM/Integration

**Comment by francescobrivio** [comment]
@cmsbuild please test

**Comment by emanueleusai** [comment]
please test

**Comment by emanueleusai** [comment]
testing at p5

**Comment by syuvivida** [comment]
+1
@nothingface0 and @antoniovagnerini tested this PR at p5 with collision run 370580 and CMSSW_13_0_11. The beam spot clients ran without crashing and @francescobrivio confirmed the test results are ok.

**Comment by mandrenguyen** [comment]
+1

**Comment by francescobrivio** [comment]
+db

**Comment by saumyaphor4252** [comment]
+alca

**Comment by rappoccio** [comment]
+1

**Pull request merged**
