### PR TITLE
Make legacy and uROS DT packer naming consistent for InputTag cfg parameter [10_1_X] 

### PR DESCRIPTION
**Pull request by battibass**
Backport of [PR # 23091](https://github.com/cms-sw/cmssw/pull/23091)

### CODE REVIEW

**Comment by slava77** [comment]
Backport of #23091

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/23092	94c179d
- this fixes the premixing problems in DT in the same way as in the master version (https://github.com/cms-sw/cmssw/pull/23091	e6246b2)
- jenkins tests pass and comparisons show no differences. The 2018 premixing workflow running in jenkins in 102X is not a part of 10_1_X, which explains lack of differences.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
