### PR TITLE
Add UL18 V5 jet energy corrections + V2 jet resolution [10_6_X]

### PR DESCRIPTION
**Pull request by christopheralanwest**
#### PR description:

This PR add UL18 V5 jet energy corrections + V2 jet resolution to 2018 and 2021 realistic MC as well as to the corresponding IOVs of the data GTs. Validation slides can be found at https://github.com/cms-jet/JECDatabase/blob/master/PDF/Summer19UL18_V5/Validation_Summer19UL18_V5_JEC.pdf.

The Run 3 GTs are not updated in the backport in order to minimize unnecessary changes.

The GT diffs are as follows:

**Offline data**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_dataRun2_v30/106X_dataRun2_v31

**Offline data relval**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_dataRun2_relval_v28/106X_dataRun2_relval_v29

**2018 realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_upgrade2018_realistic_v12/106X_upgrade2018_realistic_v13

**2018 realistic (HEM15/16 failure)**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_upgrade2018_realistic_HEfail_v12/106X_upgrade2018_realistic_HEfail_v14

**2018 cosmics (tracker deco mode)**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_upgrade2018cosmics_realistic_deco_v10/106X_upgrade2018cosmics_realistic_deco_v11

**2018 cosmics (tracker peak mode)**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_upgrade2018cosmics_realistic_peak_v10/106X_upgrade2018cosmics_realistic_peak_v11

#### PR validation:

See the validation slides at https://github.com/cms-jet/JECDatabase/blob/master/PDF/Summer19UL18_V5/Validation_Summer19UL18_V5_JEC.pdf.

Also, a technical test was performed: `runTheMatrix.py -l limited,11024.2,7.4 --ibeos`

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

This PR is a backport of PR #32169. The JEC updates in this PR is intended for the re-miniAOD.

### CODE REVIEW

**Comment by christopheralanwest** [comment]
test parameters
- workflow = 11024.2,7.4

**Comment by christopheralanwest** [comment]
backport #32169

**Comment by christopheralanwest** [comment]
please test

**Comment by christopheralanwest** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
