### PR TITLE
fix compilation error with EDM DEBUG in 80X

### PR DESCRIPTION
**Pull request by VinInn**
apparently never compiled with 
``` scram b -v USER_CXXFLAGS="-DEDM_ML_DEBUG"```

### CODE REVIEW

**Comment by VinInn** [comment]
No, I suspect was part of something else. I marked backport because seems fixed in the master
(at least master compiles with ```USER_CXXFLAGS="-DEDM_ML_DEBUG"```)
mark it bug-fix is you wish

**Comment by perrotta** [comment]
This PR is a partial backport of #13386, only merged in 81X (not in 80X)
In fact, the solution adopted in the master for https://github.com/cms-sw/cmssw/pull/24514/files#diff-a9ce9d935ab3668f3d3a9adf77676169R104 is different...

**Comment by slava77** [comment]
On 9/12/18 7:34 AM, Vincenzo Innocente wrote:
> No, I suspect was part of something else. I marked backport because
> seems fixed in the master
> (at least master compiles with |USER_CXXFLAGS="-DEDM_ML_DEBUG"|)
> mark it bug-fix is you wish
> 

I needed the PR number mainly to know if we need the same fix in other
active versions.
What is the use case in 80X that wouldn't apply to e.g. 94X?

**Comment by perrotta** [comment]
As I wrote, the same (or similar) fixes are there since 81X thanks to #13386, see
https://github.com/cms-sw/cmssw/pull/13386/files#diff-d190d912bb92b12ada65a63cc0f3fd13R244
and
https://github.com/cms-sw/cmssw/pull/13386/files#diff-a9ce9d935ab3668f3d3a9adf77676169R156
(where a different fix was preferred)

**Comment by VinInn** [comment]
>What is the use case in 80X that wouldn't apply to e.g. 94X?
2016 (phase0) analysis. If 81X is ok (phase0 as default), close this PR

**Comment by perrotta** [comment]
+1
- If not needed in 80X this will not be merged, but I see no reason to avoid signing this bug fix for the runs with the debug flag enabled and on a LogDebug output
- This is not an identical backport of (a tiny subset of) #13386, because there, and still in the current master, ```int(hit->geographicalId())`` was preferred instad of ```hit->geographicalId().rawId()```, which is the choice for this PR. On the other hand, the choice made here seems to me even more pertinent, and I wouldn't necessarily stick on an identical reproduction of what in the master for a LogDebug 
- Jenkins tests pass

**Comment by slava77** [comment]
I mentioned in the ORP that this PR by itself does not require a new 80X build.
@kpedro88 I guess this means that this can still be merged for IBs, but a patch release may need more reasons (other PRs or more urgency for this one) to be built.
@VinInn  If an actual release is needed sooner, please clarify the needs.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
