### PR TITLE
Pileup scenario for 2018 using an extrapolation of data to date.

### PR DESCRIPTION
**Pull request by plujan**
This uses the 2018 data so far, extrapolated over the rest of the year. For more details see the slides here: https://indico.cern.ch/event/737811/contributions/3045257/attachments/1670000/2678601/pu_projections_2018_june.pdf

### CODE REVIEW

**Comment by plujan** [comment]
Hi all,

I just learned that the distribution here has not yet been smeared as we planned, so I'll get that updated as soon as possible.

Sorry for the incovenience!

**Comment by plujan** [comment]
The file now includes the properly smeared version. Here's the plot of the distributions:

pileupsummer2018

**Comment by franzoni** [comment]
hi @plujan , thanks for this.

"Summer18" is already taken as a name:
it's the ongoing MC campaign based on 10_1 .

Would it be possible to rename this scenario, to avoid mis-understanding pls.
"JuneProjectionFull18", or a better idea ?

Including PdmV convenors who master the naming of 10_2 based MC campaign
@fabozzi @prebello @GurpreetSinghChahal

**Comment by plujan** [comment]
Sure, done! Also, tested with cmsDriver to make sure everything actually works, and it looks fine.

**Comment by fabiocos** [comment]
please test

testing nothing in reality, I do not see a way to do it from the bot until this scenario is not put as default for some test wf

**Comment by plujan** [comment]
@fabiocos Yeah agreed -- I just tested it by picking a random workflow and changing the cmsDriver command to include the new scenario, but there's not really much more that can be done.

**Comment by fabiocos** [comment]
+operations

simple addition of a new PU scenario to StandardSequences

**Comment by fabiocos** [comment]
+1

**Comment by franzoni** [comment]
Tks!!

**Pull request merged**
