### PR TITLE
Make L1T object comparison fillDescriptions compatible with ConfDB parsing - 101x

### PR DESCRIPTION
**Pull request by thomreis**
Backport of #24372 

In order to have the framework modules appear in the ConfDB GUI it is needed to replace object comparison and filter fillDescriptions addDefault with addWithDefaultLabel.

### CODE REVIEW

**Comment by thomreis** [comment]
please test

**Comment by Martin-Grunewald** [comment]
assign hlt

**Comment by Martin-Grunewald** [comment]
-1

**Comment by Martin-Grunewald** [comment]
+1

**Comment by thomreis** [comment]
+1

**Pull request merged**
