### PR TITLE
PackedClusters for 74X to keep PFClusters in AOD

### PR DESCRIPTION
**Pull request by Sam-Harper**
Dear All, 

@lgray  @matteosan1 

I decided the best way to alert folks with via this pull request rather than emailing as it ensures I get the right people. E/gamma is already aware about this. Currently in the AOD, my understanding is that we do not save CaloTowers or HcalRecHits. Nor do we store the PFClusters. Therefore we have no unbiased or minimally biased HCAL collection. There is a need to have this in place for studies. 

Right now, I would like the PFClusters accessable at the AOD level. This is useful for isolation development and debugging. Indications are that PF cluster based isolation is promising (https://indico.cern.ch/event/305124/contribution/3/material/slides/1.pdf). It is also what is used for the HLT. To continue to develop isolation and also to understand the HLT isolation, we need PFClusters in the AOD.  It is also useful for H/E studies.  

I understand that these were dropped due to space. For isolation studies and H/E , we can get away with just having the et/eta/phi and detId of the seed cluster. So I have developed a packed format ala the mini-aod (not this is for AOD not miniAOD) for Clusters. I put it in with the pat::PackedCandidate as it reuses the packer they use which is in that package. 

I then tested the size on ttbar events (/store/relval/CMSSW_7_4_0_pre2/RelValTTbar_13/GEN-SIM-RECO/PU25ns_MCRUN2_73_V7-v1/00000/12EFC87E-C29A-E411-ABAA-003048FFD79C.root) and found following sizes in bytes from edmEventSize:
patPackedClusters_packedPFClustersECAL__AODTest. 6896.77 4042.27
patPackedClusters_packedPFClustersHCAL__AODTest. 3433.81 1911.33

So we can store all PF clusters in 6Kb per event. If this is a problem, we can filter based on gedGsfElectrons and gedPhotons with DR<0.5. This reduces the event size to 
patPackedClusters_packedPFClustersECAL__AODTest. 1092.29 662.26
patPackedClusters_packedPFClustersHCAL__AODTest. 398.37 253.17

which is less than a 1kb compressed.  Note, I think the ECAL ones might even be already in the AOD but its not quite clear to me if they are. Any clarifications from experts would be useful here. Regardless, I'm almost fully certain HCAL are not. 

I would like to have this information in the AOD, what steps should I take to ensure that this happens

Thanks,
Sam

### CODE REVIEW

**Comment by slava77** [comment]
Hi Sam,
what is the meaning of "to understand the HLT isolation" ?
Is this only for MC? to make studies on larger samples (normally made in AODSIM) to improve iso definitions (cones, thresholds etc) to be later propagated to HLT?
(if so, then it sounds similar to the recent feature request for HLT jet threshold/selection related studies).
If for MC, would it be enough to keep the isolation values computed at HLT?

The class will need to be defined outside of pat:: namespace to be considered for RECO sequences.

**Comment by Sam-Harper** [comment]
Hi Slava,

Thank you for your quick response. This would be for data as well but is more important for MC. 

The idea behind this is that I want to do studies to improve isolation definitions which can be both be propagated to HLT and RECO. I also want to do studies for H/E (which is like an isolation). I am also concerned that for commissioning, we will have no quick and easy way know what roughly the HLT isolation was online (its not saved and its based on PF clusters which we dont keep in AOD so we cant even use a RECO proxy). 

My endgame here:
develop a new isolation for high energy electrons using PF clusters, there is indication so far that this is better than using PF candidates. It would also allow syncing RECO and HLT definations
develop a new H/E variable for electrons using PF candidates and ensure we can tune this properly
These definitions would probably be for 2016 but we need these candidates to try and develop the definations in 2015.

Right now these studies require RECO and this is quickly going to become impossible/very difficult. This would simplify my life as well as introducing some minimal HCAL information into the AOD that will be useful for re-commissioning the detector. 


Ah I forgot that it has to be outside the pat namespace, I will remake the class to do that. This makes life a little difficult with figuring what to do about https://github.com/cms-sw/cmssw/blob/CMSSW_7_4_X/DataFormats/PatCandidates/interface/libminifloat.h but I'm sure I'll figure out a solution (I'm guessing I cant make something like Dataformats/EgammaCandidates depend on DataFormats/PathCandidates).

**Comment by slava77** [comment]
btw, github is probably a good venue to discuss specific code implementation
and maybe have a summary of performance, but the rest of the physics
discussion
makes more sense in the hypernews.

Please add a test config for your producer.


On 1/16/15 10:36 AM, Sam-Harper wrote:
> Hi Slava,
> 
> Thank you for your quick response. This would be for data as well but is
> more important for MC.
> 
> The idea behind this is that I want to do studies to improve isolation
> definitions which can be both be propagated to HLT and RECO. I also want
> to do studies for H/E (which is like an isolation).


We have reduced HCAL and ECAL rechits stored in AOD.
If a gedElectron's HCAL hits are not in the list, they should just be
added there.
I'd think this will give you better level of details than packed cluster et


> I am also concerned
> that for commissioning, we will have no quick and easy way know what
> roughly the HLT isolation was online (its not saved and its based on PF
> clusters which we dont keep in AOD so we cant even use a RECO proxy).


It would be much much better to find a solution to save the isolation
from HLT actually computed online.
It's been on the wishlist for a while.

> 
> My endgame here:
> develop a new isolation for high energy electrons using PF clusters,
> there is indication so far that this is better than using PF candidates.
> It would also allow syncing RECO and HLT definations
> develop a new H/E variable for electrons using PF candidates and ensure
> we can tune this properly
> These definitions would probably be for 2016 but we need these
> candidates to try and develop the definations in 2015.

Are the high-energy electrons special or would a similar improvement
be expected for lower momentum electrons as well.
If clusters work better, we should eventually update the detector-based
isolation.


> 
> Right now these studies require RECO and this is quickly going to become
> impossible/very difficult. This would simplify my life as well as
> introducing some minimal HCAL information into the AOD that will be
> useful for re-commissioning the detector.
> 



> Ah I forgot that it has to be outside the pat namespace, I will remake
> the class to do that. This makes life a little difficult with figuring
> what to do about
> https://github.com/cms-sw/cmssw/blob/CMSSW_7_4_X/DataFormats/PatCandidates/interface/libminifloat.h
> but I'm sure I'll figure out a solution (I'm guessing I cant make
> something like Dataformats/EgammaCandidates depend on
> DataFormats/PathCandidates).
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cms-sw/cmssw/pull/7236#issuecomment-70280847>.
> 

-- 
***********************************************************************
 Vyacheslav (Slava) Krutelyov
 TAMU: Physics Dept Texas A&M MS4242, College Station, TX 77843-4242
 CERN: 42-R-027
 AIM/Skype: siava16              googleTalk: slava77@gmail.com
 (630) 291-5128  Cell (US)       +41 76 275 7116 Cell (CERN)

-----------------------------------------------------------------------

**Comment by degano** [comment]
@cmsbuild please test

**Comment by degano** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
Hi Sam,
were you going to resubmit the packed cluster version in the follow up of the RECO meeting discussion?

**Comment by Sam-Harper** [comment]
Hi Slava, I realized that I could actually remake the PF Clusters from AOD information once I got the HCAL rec-hits in which was more useful generally. Its not perfect but fine for my needs. So in the interests of space I now withdraw the plan to have packed clusters in the AOD. Sorry, I should have been clearer about this. If there is a desire for me to add the class with the modifications discussed, I can do so but I wasnt planning on doing anything.

**Comment by slava77** [comment]
Hi Sam,

Thanks for the clarification.
I guess no action is needed at this point.
If the recipe to remake the clusters is somewhat involved,
I'd suggest to put a config or py function in an appropriate python/
directory of PF packages.



On 2/5/15 7:29 AM, Sam-Harper wrote:
> Hi Slava, I realized that I could actually remake the PF Clusters from
> AOD information once I got the HCAL rec-hits in which was more useful
> generally. Its not perfect but fine for my needs. So in the interests of
> space I now withdraw the plan to have packed clusters in the AOD. Sorry,
> I should have been clearer about this. If there is a desire for me to
> add the class with the modifications discussed, I can do so but I wasnt
> planning on doing anything.
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cms-sw/cmssw/pull/7236#issuecomment-73045740>.
> 

-- 
***********************************************************************
 Vyacheslav (Slava) Krutelyov
 TAMU: Physics Dept Texas A&M MS4242, College Station, TX 77843-4242
 CERN: 42-R-027
 AIM/Skype: siava16              googleTalk: slava77@gmail.com
 (630) 291-5128  Cell (US)       +41 76 275 7116 Cell (CERN)

-----------------------------------------------------------------------

**Pull request closed without merging**
