### PR TITLE
hcal strip filter (74X)

### PR DESCRIPTION
**Pull request by aminnj**
Hcal problematic cell length filter added to BeamHaloSummary.

(74X copy of https://github.com/cms-sw/cmssw/pull/10934)

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/11181	55a4c95
- the same changes as in 75X/76X versions
- addition of new data members should be transparent; the change is relevant mainly for data processing (not so much for MC)
- jenkins tests pass and comparisons with the baseline show no differences (there are no downstream objects affected and the modified/added values in the objects are not monitored)

**Comment by mariadalfonso** [comment]
@monttj, please have a look at this PR, we would like to have the Additional Beam Halo for the coming 3.8T runs

**Comment by monttj** [comment]
+1

**Comment by slava77** [comment]
hold
looks like this PR needs a fix: there is a problem running ```runTheMatrix.py -l 1102 -i all```
observed in 76X IBs

**Comment by slava77** [comment]
@cms-bot,  new commit is here

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/11181	 83bf986
- changes since last signoff are as expected https://github.com/aminnj/cmssw/compare/55a4c95...83bf986 and the same as in the fix in 76X in #11447 
- jenkins tests pass including (manually included for the last test) 1102.0 workflow. Comparisons with the baseline show no differences (the adde products/variables are not monitored)

**Comment by slava77** [comment]
@monttj please check this PR
your signature is needed.
Thank you.

**Comment by monttj** [comment]
+1

**Comment by slava77** [comment]
@davidlange6 
I think that this PR can be closed
Even if we do something with 2015, it will be 76X.

**Pull request closed without merging**
