### PR TITLE
[93X] Improvements to L1 Offline DQM - part 2 (issue #19592)

### PR DESCRIPTION
**Pull request by kreczko**
This PR implements the improvements requested in issue #19592 by the L1T team.

@tapperad et all, please have a look

### CODE REVIEW

**Comment by dmitrijus** [comment]
+1

**Comment by kreczko** [comment]
As far as I can see all unit tests succeded (searching for `---> test` in the [unit test log](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-19796/21578/unitTests.log)).
The only error message in the logs is
```
dropped waiting message count 0
stat: cannot stat `dqm_empty.root': No such file or directory
read_missing_file_cfg.py ------------------------------------------------------------
18-Jul-2017 16:36:46 CEST  Initiating request to open file file:dqm_missing.root
18-Jul-2017 16:36:47 CEST  Successfully opened file file:dqm_missing.root
----- Begin Fatal Exception 18-Jul-2017 16:36:47 CEST-----------------------
An exception of category 'FileReadError' occurred while
   [0] Calling InputSource::readFile_
   [1] Opening DQM Root file
Exception Message:
Input file file:dqm_missing.root appears to be corrupted since it does not have the proper internal structure.
 Check to see if the file was closed properly.
----- End Fatal Exception -------------------------------------------------
```

If I understand from the name, this file should not exist (and the test segment is marked as success).

What am I missing?

**Comment by dmitrijus** [comment]
The test failure is unrelated to this PR. I i will look into it.

**Comment by kreczko** [comment]
@dmitrijus Did you have any time to look into this?

**Comment by dmitrijus** [comment]
please test

**Comment by rekovic** [comment]
@kreczko 
Are these failing test going to be addressed?

**Comment by kreczko** [comment]
@rekovic Yes, as @dmitrijus pointed out, the failures are unrelated to this PR.

**Comment by dmitrijus** [comment]
+1

**Comment by kreczko** [comment]
@rekovic @mulhearn 
Tests are now passing, only the L1T signature is missing.

**Comment by rekovic** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
