### PR TITLE
Migration to CMSSW_10_5_0_pre2 code base in ConfDB

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
Migration to CMSSW_10_5_0_pre2 code base in ConfDB
Based on CMSSW_10_5_0_pre2

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
FallbackFileOpenError - let's try again!

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by Martin-Grunewald** [comment]
please test

**Comment by fabiocos** [comment]
+1

**Pull request merged**
