### PR TITLE
Photon MVA-based ID for Run3 from EGamma POG

### PR DESCRIPTION
**Pull request by Prasant1993**
#### PR description:

This PR is to add Photon MVA-based ID for Run3 from EGamma POG:

- This will add photon MVA-based ID decisions for a new optimized ID in Run3. 
- The new optimized ID is trained using G+Jets simulation sample produced in CMSSW_12_2_X Winter22 campaign.
- The ID optimization and the comparison of results can be found in the below presentations made in EGamma POG:

1. https://indico.cern.ch/event/1182858/#2-update-on-run3-photon-mva-id
2. https://indico.cern.ch/event/1188686/#2-update-on-run3-photon-mva-id
3. https://indico.cern.ch/event/1192144/#2-update-on-run3-photon-mva-id
4. https://indico.cern.ch/event/1192146/#2-update-on-run3-photon-mva-id
5. https://indico.cern.ch/event/1192145/#2-update-on-run3-photon-mva-id
6. https://indico.cern.ch/event/1204272/#2-update-on-run3-photon-mva-id

#### PR validation:

runTheMatrix tests have been successfully run for the following workflows :

- runTheMatrix.py -l 12434.0
- runTheMatrix.py -l 11834.0
- runTheMatrix.py -l 10024.0
- runTheMatrix.py -l 136.874

Validation has also been performed to cross-check the Run3 MVA ID efficiencies from the MINIAOD datasets and compared with Run2 ID decisions using G+Jets, Relval H125, Relval ZEE and Relval QCD MC samples as shown in the below plots:

- Comparison of signal photon MVA ID efficiencies at WP80 using 122X G+Jets MC sample : https://egamma-val.web.cern.ch/Run2_vs_Run3_PhotonIDMVA_test_plots/Tests_in_122X_GJet_sample/WP80/
- Comparison of signal photon MVA ID efficiencies at WP90 using 122X G+Jets MC sample : https://egamma-val.web.cern.ch/Run2_vs_Run3_PhotonIDMVA_test_plots/Tests_in_122X_GJet_sample/WP90/
- Comparison of signal photon MVA ID efficiencies at WP80 and WP90  using 124X Relval Higgs125 MC sample : https://egamma-val.web.cern.ch/Run2_vs_Run3_PhotonIDMVA_test_plots/Tests_in_124X_relvalHiggs_M125_sample/
- Comparison of signal photon MVA ID efficiencies at WP80 and WP90 using 124X Relval ZEE MC sample : https://egamma-val.web.cern.ch/Run2_vs_Run3_PhotonIDMVA_test_plots/Tests_in_124X_relvalZEE_sample/
- Comparison of background photon MVA ID efficiencies at WP80 using 124X Relval QCD MC sample : https://egamma-val.web.cern.ch/Run2_vs_Run3_PhotonIDMVA_test_plots/Tests_in_124X_relvalQCD_sample/WP80/
- Comparison of background photon MVA ID efficiencies at WP90 using 124X Relval QCD MC sample : https://egamma-val.web.cern.ch/Run2_vs_Run3_PhotonIDMVA_test_plots/Tests_in_124X_relvalQCD_sample/WP90/        

The photon MVA training weight files for Run3 have been already added here : https://github.com/cms-data/RecoEgamma-PhotonIdentification/tree/master/MVA
A PR is submitted and not merged yet : https://github.com/cms-data/RecoEgamma-PhotonIdentification/pull/13
This current PR for photon MVA ID will take the input weight files from the above PR to work with.

#### Backport:

This PR does not need any backportation.

We would like to keep both RunIIFall17V2 photon MVA ID decision and this new Run3Winter22V1 photon MVA ID decision in the upcoming nano because several early analysis are using Run2 ID for Run3, and it is working quite well, so they might or might not want to switch. The necessary changes for adding the Run3 MVA photon ID in NanoAOD has already been made in this PR.

### CODE REVIEW

**Comment by swagata87** [comment]
type egamma

**Comment by swagata87** [comment]
please test with https://github.com/cms-data/RecoEgamma-PhotonIdentification/pull/13

**Comment by swagata87** [comment]
EGM POG maintains 4 types of IDs (electron cutbased+MVA; photon cutbased+MVA). All of them are being reoptimised for Run3. 
1/4 https://github.com/cms-sw/cmssw/pull/39839 -> Electron cutbased
2/4 this PR -> Photon MVA
And the other 2 PRs are coming shortly.
All of them aims for the last open pre-release of 12_6_0, so that new IDs can be present in reMini and reNano which will be made with 12_6.

Tagging EGM nanoAOD contact @rgoldouz

**Comment by vlimant** [comment]
enable nano

**Comment by swertz** [comment]
Do we want to disable the Run3 IDs (also in #39839) for Run2 samples?

**Comment by swagata87** [comment]
> Do we want to disable the Run3 IDs (also in #39839) for Run2 samples?

Run3 IDs are not specifically needed in Run2 samples. But we are anyway not going to reNano any of the Run2 data or MC, right? So maybe we can leave it out for simplicity for now? We can come back to cleanups later on..?

**Comment by swertz** [comment]
> But we are anyway not going to reNano any of the Run2 data or MC, right? So maybe we can leave it out for simplicity for now? We can come back to cleanups later on..?

The idea is to keep Run2 and Run3 samples as much as possible in sync for combined analyses, there will for sure be a re-nano of Run2 at some point (if not in 126X then in 130X), so we should keep things clean in master.

This is also valid for MINI, btw (not running the Run3 IDs for Run2 MINI).

**Comment by swagata87** [comment]
yes we are just trying to make sure that Run3 IDs get integrated now, as we do not want to miss the deadline of last open pre-release of 12_6_0. The cleanups can be done afterwards too, if that's not a problem.

**Comment by mandrenguyen** [comment]
+1

**Comment by swertz** [comment]
please test

Retriggering tests this time with nano workflows

**Comment by swertz** [comment]
please abort

**Comment by swertz** [comment]
please test with https://github.com/cms-data/RecoEgamma-PhotonIdentification/pull/13

**Comment by swertz** [comment]
please test

Trying again, the error looks spurious. Nano DQM has the new variables and they look OK:

image

**Comment by swertz** [comment]
+xpog

**Comment by perrotta** [comment]
@Prasant1993 @swagata87 are the many differences in the Run3 workflows (tracking, etc.) explained somehow? I doubt they come from this PR, not even from the technical PR tested together with this one, but it would be nice to pinpoint a possible origin of them before merging

**Comment by vlimant** [comment]
@perrotta can you please point out one of the relmon directory that makes you worried ?
I'm looking at some of them and it looks like a glitch in the comparison. The changes in this PR have no way to influence the tracks "etaSim" (whatever this means)

https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_6_X_2022-11-06-2300+aaed28/53928/11634.0_TTbar_14TeV+2021+TTbar_14TeV_TuneCP5_GenSim+Digi+RecoNano+HARVESTNano+ALCA/Tracking_Track_simulation.html

https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_6_X_2022-11-06-2300+aaed28/53928/11634.0_TTbar_14TeV+2021+TTbar_14TeV_TuneCP5_GenSim+Digi+RecoNano+HARVESTNano+ALCA/

**Comment by perrotta** [comment]
> @perrotta can you please point out one of the relmon directory that makes you worried ?
> I'm looking at some of them and it looks like a glitch in the comparison. The changes in this PR have no way to influence the tracks "etaSim" (whatever this means)

@vlimant I see you were able to find them yourself, and you also reached my conclusion that it cannot be originated by this PR.
Let try to see whether the "glitch" disappears if we retest it once more. If not, I would ask the authors to investigate where the possible correlation comes from

**Comment by perrotta** [comment]
please test with https://github.com/cms-data/RecoEgamma-PhotonIdentification/pull/13

**Comment by rappoccio** [comment]
+1

Expected new features into nano.

**Comment by Martin-Grunewald** [comment]
Errors in IBs:

```
----- Begin Fatal Exception 09-Nov-2022 06:07:37 CET-----------------------
An exception of category 'FileInPathError' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing module: class=PhotonMVAValueMapProducer label='photonMVAValueMapProducer'
Exception Message:
edm::FileInPath unable to find file RecoEgamma/PhotonIdentification/data/MVA/RunIII_Winter22/PhoMVA_ID_EB_V1.weights.root anywhere in the search path.
The search path is defined by: CMSSW_SEARCH_PATH
${CMSSW_SEARCH_PATH} is: /data/cmsbld/jenkins/workspace/ib-run-relvals/CMSSW_12_6_X_2022-11-08-2300/poison:/data/cmsbld/jenkins/workspace/ib-run-relvals/CMSSW_12_6_X_2022-11-08-2300/src:/data/cmsbld/jenkins/workspace/ib-run-relvals/CMSSW_12_6_X_2022-11-08-2300/external/slc7_amd64_gcc10/data:/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02758/slc7_amd64_gcc10/cms/cmssw/CMSSW_12_6_X_2022-11-08-2300/src:/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02758/slc7_amd64_gcc10/cms/cmssw/CMSSW_12_6_X_2022-11-08-2300/external/slc7_amd64_gcc10/data
Current directory is: /data/cmsbld/jenkins/workspace/ib-run-relvals/CMSSW_12_6_X_2022-11-08-2300/pyRelval/250402.0_TTbar_13+FS_TTbar_13_PRMXUP15_PU25+HARVESTUP15FS+MINIAODMCUP15FS
----- End Fatal Exception -------------------------------------------------
```

**Comment by Martin-Grunewald** [comment]
Great, thanks!

**Pull request merged**
