### PR TITLE
Phase1 Pixel DQM Bugfixes

### PR DESCRIPTION
**Pull request by schneiml**
This PR fixes some smaller bugs that were found in the first version merged in #14586 (also @fioriNTU ).
- (UPDATE: the explanation here is wrong, it seems this was all caused by the invalid refs fixed by [this](https://github.com/cms-sw/cmssw/pull/14760/commits/5b03e23a33ee37d8c44b8e2b0f710eb78ba7d2f7). I still don't understand why this happens, but it is undefined behaviour and therefore totally fine.) The most critical one was caused by the last-minute changes to TrackerTopology ( @davidlange6 ). The new code stored a `edm::ESHandle` to TT, and that seemed to silently become invalid on rare occasions. The fix is to use a bare pointer, which is a bad solution but works. While I can understand that the Handle or also the pointer gets invalid, what I do NOT understand is why this happens during the DQM booking phase (maybe also elsewhere, but definitely there) and only in one out of 6 plugins, that all run the same code. Maybe there is more to it. (The plugin in question is SiPixelPhase1RecHits, the symptom is that many histograms are not booked, and changing to pointers fixes it).
- the other commits fix a crash on configurations with all MEs turned off and some cosmetic changes
- finally there is a a fix for the issue reported by @slava77 today in #14586 . With this fix the given command does still crash, but it is no longer the Phase1 Pixel DQMs fault (I hope).
- I have no idea how @mtosi 's commit ends up in this PR. It is totally unrelated. (Update: fixed by rebase & force push)

### CODE REVIEW

**Comment by slava77** [comment]
```
finally there is a a fix for the issue reported by @slava77 today in #14586 . With this fix the given command does still crash, but it is no longer the Phase1 Pixel DQMs fault (I hope).
```
what is the reason for a crash now?
The data processing config worked before the #14586  was introduced.

**Comment by schneiml** [comment]
```
Traceback (most recent call last):
  File "RunPromptRecoCfg.py", line 111226, in <module>
    process.patMetUncertaintySequenceNoHF = cms.Sequence(process.ak4PFCHSL1FastL2L3CorrectorChain+process.ak4PFCHSL1FastL2L3ResidualCorrectorChain++process.patPFMetT1NoHFpatMetUncertaintySequenceNoHF+process.patPFMetT1SmearNoHFpatMetUncertaintySequenceNoHF)
TypeError: bad operand type for unary +: 'Sequence'
```

I have honestly no idea what this sequence does, but to me this is a sign that it is not DQM related.

**Comment by slava77** [comment]
On 6/3/16 6:51 AM, Marcel Schneider wrote:
> |Traceback (most recent call last): File "RunPromptRecoCfg.py", line
> 111226, in <module> process.patMetUncertaintySequenceNoHF =
> cms.Sequence(process.ak4PFCHSL1FastL2L3CorrectorChain+process.ak4PFCHSL1FastL2L3ResidualCorrectorChain++process.patPFMetT1NoHFpatMetUncertaintySequenceNoHF+process.patPFMetT1SmearNoHFpatMetUncertaintySequenceNoHF)
> TypeError: bad operand type for unary +: 'Sequence' |
> 
> I have honestly no idea what this sequence does, but to me this is a
> sign that it is not DQM related.

Probably not, but I guess the only way is to check in a  test build with
the phase1 DQM changes reverted

**Comment by schneiml** [comment]
Are there instructions on how to do a clean revert (with cmssw packages etc.)?

**Comment by schneiml** [comment]
@slava77 I am fairly certain the new crash was introduced by this #14608 .

-  In `-pre5`, things work, but the sequences in question are _empty_.
-  The PR added something to the sequences.
-  In `-pre6`, some of the `cms.Sequence`s have a `_seq` of `None`, which is translated to the empty string.
- This leads to syntax errors when a sequence of such sequences is `dumpPython`ed. 

There are two bugs here: one is that the `patMetUncertaintySequence` contains invalid sequences with a `_seq` of `None`. This indicates a functional problem that has to be fixed. the other one is that `dumpPython` creates incorrect output in this cornercase. This is a purely technical cornercase that is usually not needed and does not really need a fix, though it is still a bug. I'd propose representing the invalid sequence as `"cms.Sequence()"` or sth instead of the empty string, but I am not certain what makes most sense there due to the mixin architecture. Maybe an early crash would be even better. (The line in question is https://github.com/cms-sw/cmssw/blob/CMSSW_8_1_X/FWCore/ParameterSet/python/SequenceTypes.py#L238 )

Relevant lines in output:
```
[mschneid][8][9.22][lxplus011][.../tst/CMSSW_8_1_0_pre6]$ ag 'process.patMetUncertaintySequence' RunPromptRecoCfg.py 
111088:process.patMetUncertaintySequenceNoHF = cms.Sequence(process.ak4PFCHSL1FastL2L3CorrectorChain+process.ak4PFCHSL1FastL2L3ResidualCorrectorChain++process.patPFMetT1NoHFpatMetUncertaintySequenceNoHF+process.patPFMetT1SmearNoHFpatMetUncertaintySequenceNoHF)
111124:process.patMetUncertaintySequencePuppi = cms.Sequence(process.ak4PFCHSL1FastL2L3CorrectorChain+process.ak4PFCHSL1FastL2L3ResidualCorrectorChain++process.patPFMetT1PuppipatMetUncertaintySequencePuppi+process.patPFMetT1SmearPuppipatMetUncertaintySequencePuppi)
111130:process.patMetUncertaintySequence = cms.Sequence(process.ak4PFCHSL1FastL2L3CorrectorChain+process.ak4PFCHSL1FastL2L3ResidualCorrectorChain++process.patPFMetT1patMetUncertaintySequence+process.patPFMetT1SmearpatMetUncertaintySequence)
111190:process.fullPatMetSequence = cms.Sequence(process.patMetModuleSequence+process.patMetCorrectionSequence+process.patMetUncertaintySequence+process.patShiftedModuleSequence+process.slimmedMETs)
111226:process.fullPatMetSequencePuppi = cms.Sequence(process.patMetModuleSequencePuppi+process.patMetCorrectionSequencePuppi+process.patMetUncertaintySequencePuppi+process.patShiftedModuleSequencePuppi+process.patCaloMet)
111256:process.fullPatMetSequenceNoHF = cms.Sequence(process.patMetModuleSequenceNoHF+process.patMetCorrectionSequenceNoHF+process.patMetUncertaintySequenceNoHF+process.patShiftedModuleSequenceNoHF+process.patCaloMet)
[mschneid][8][8.44][lxplus011][.../tst/CMSSW_8_1_0_pre6]$ cd ../CMSSW_8_1_0_pre5/
[mschneid][8][7.37][lxplus011][.../tst/CMSSW_8_1_0_pre5]$ ag 'process.patMetUncertaintySequence' RunPromptRecoCfg.py 
104741:process.patMetUncertaintySequenceNoHF = cms.Sequence()
104897:process.patMetUncertaintySequencePuppi = cms.Sequence()
105116:process.patMetUncertaintySequence = cms.Sequence()
105587:process.fullPatMetSequence = cms.Sequence(process.patMetModuleSequence+process.patMetUncertaintySequence+process.patShiftedModuleSequence+process.patMetCorrectionSequence)
105623:process.fullPatMetSequencePuppi = cms.Sequence(process.patMetModuleSequencePuppi+process.patMetUncertaintySequencePuppi+process.patShiftedModuleSequencePuppi+process.patMetCorrectionSequencePuppi)
105653:process.fullPatMetSequenceNoHF = cms.Sequence(process.patMetModuleSequenceNoHF+process.patMetUncertaintySequenceNoHF+process.patShiftedModuleSequenceNoHF+process.patMetCorrectionSequenceNoHF)
[mschneid][8][9.27][lxplus011][.../tst/CMSSW_8_1_0_pre5]$ 
```

notice the `cms.Sequence()` in `-pre5` and the `++` syntax error in `-pre6`.

**Comment by makortel** [comment]
> the other one is that dumpPython creates incorrect output in this cornercase. This is a purely technical cornercase that is usually not needed and does not really need a fix, though it is still a bug. I'd propose representing the invalid sequence as "cms.Sequence()" or sth instead of the empty string, but I am not certain what makes most sense there due to the mixin architecture. Maybe an early crash would be even better

Having debugged these kind of cases (too) many times, I'd much prefer to get an early crash with a clear error message with as much useful information as possible to help fixing the cause. I think mapping this case to empty sequence would add confusion and make debugging more difficult.

**Comment by slava77** [comment]
On 6/7/16 2:16 AM, Marcel Schneider wrote:
> @slava77 <https://github.com/slava77> I am fairly certain the new crash
> was introduced by this #14608 <https://github.com/cms-sw/cmssw/pull/14608> .
> 
>   * In |-pre5|, things work, but the sequences in question are /empty/.
>   * The PR added something to the sequences.
>   * In |-pre6|, some of the |cms.Sequence|s have a |_seq| of |None|,
>     which is translated to the empty string.
>   * This leads to syntax errors when a sequence of such sequences is
>     |dumpPython|ed.


Thanks for checking.
This should help in further investigation.

**Comment by dmitrijus** [comment]
@schneiml can you take a look at https://github.com/cms-sw/cmssw/issues/14800 ?

**Comment by schneiml** [comment]
@dmitrijus My guess is that this PR also fixes this issue, at least for
the moment, but I cannot guarantee it.

**Comment by dmitrijus** [comment]
+1

**Comment by schneiml** [comment]
@dmitrijus I was about to ping you for this one. As far as I see this should fix all known issues with the Phase1 DQM as of now.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
