### PR TITLE
add PU vs LS

### PR DESCRIPTION
**Pull request by mtosi**
backport of https://github.com/cms-sw/cmssw/pull/20694

### CODE REVIEW

**Comment by mtosi** [comment]
@cmbuild, please test

**Comment by fwyzard** [comment]
If the diff on github is correct, there seem to be some unrelated changes
in
https://github.com/mtosi/cmssw/blob/1c41dc4989b4dc4d0b8cfbc54f2229eeacd591ee/DQM/TrackingMonitor/python/MonitorTrackInnerTrackMuons_cff.py
.

Ciao,
.Andrea

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by mtosi** [comment]
I'm adding the bug fix (https://github.com/cms-sw/cmssw/pull/20726) I've just created for the master

**Comment by mtosi** [comment]
@cmsbuild, please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by dmitrijus** [comment]
+1

**Comment by Martin-Grunewald** [comment]
@mtosi 
There is now a merge conflict in this PR which must be fixed!

**Comment by mtosi** [comment]
thanks @Martin-Grunewald (I did not realize)
I think it is fixed, now

but we need the signature --again--
@davidlange6 @dmitrijus @Martin-Grunewald @silviodonato

**Comment by mtosi** [comment]
@cmsbuild, please test

**Comment by dmitrijus** [comment]
+1

**Comment by Martin-Grunewald** [comment]
+1

**Comment by davidlange6** [comment]
merge

**Pull request merged**
