### PR TITLE
fix det search tolerances for Cosmics

### PR DESCRIPTION
**Pull request by VinInn**
the title says all

### CODE REVIEW

**Comment by VinInn** [comment]
@cmsbuild , please test

**Comment by davidlange6** [comment]
@VinInn - just to clarify - I had understood the missing rate issue was limited to B=0 - does this PR also have a significant effect at B=3.8?

**Comment by VinInn** [comment]
We do  not know the effect at 3.8T.
In any case it is consistent with what used elsewhere for instance for Muon seeded, conversion, electron etc
I asked Matti to use it also for LowPU.
Essentially makes it consistent with RunI and 7X

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/14466	750f907
-  configuration change is in line with the needed fix; the change in GroupedCkfTrajectoryBuilderP5_cff.py is the same as in https://github.com/cms-sw/cmssw/pull/14467	0c85e7e; there is also an addition of a few LogDebugs here (OK)
- jenkins tests pass and comparisons with baseline show small differences in the cosmics processing workflow 4.22 and also in cosmics-related variables (only in 25202, probably just a rare value to change)
- see notes on local tests in https://github.com/cms-sw/cmssw/pull/14467#issuecomment-218995564

**Comment by davidlange6** [comment]
+1

**Pull request merged**
