### PR TITLE
HLT update for 25ns (76X)

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
HLT update for 25ns (76X).
Based on 760pre2.

### CODE REVIEW

**Comment by davidlange6** [comment]
@cmsbuild, please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
Need new GTs with L1T menu ```L1Menu_Collisions2015_25nsStage1_v4```

**Comment by Martin-Grunewald** [comment]
by-hand rebase!

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by diguida** [comment]
@Martin-Grunewald here it is: #10752

**Comment by diguida** [comment]
superseded by #10753

**Comment by diguida** [comment]
please test

**Comment by Martin-Grunewald** [comment]
@diguida 
Thanks a lot!! I also added the file here,as I am pretty sure we'll have more updates from the HLT
side to add... HLT development never rests.

**Comment by diguida** [comment]
@Martin-Grunewald I have anyhow sent both PR: up to you to decide after the outcome of the tests.

**Comment by Martin-Grunewald** [comment]
please test

**Comment by diguida** [comment]
superseded by #10753 with the following changes:

1. rebase to latest IB
1. removed https://github.com/cms-tsg-storm/cmssw/commit/698c4573a2a7d07ce896fc66db28a26445b42829
1. cherry-picked https://github.com/diguida/cmssw/commit/eb570c2a716bbe0b845b0d16d0eff01ea4da89c9

**Comment by Martin-Grunewald** [comment]
please test

**Comment by diguida** [comment]
Same errors as in https://github.com/cms-sw/cmssw/pull/10753#issuecomment-131245769

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by ianna** [comment]
@diguida, @davidlange6 - please, integrate this PR ASAP. It is needed for testing of #10353. Thanks.

**Comment by diguida** [comment]
+1

**Comment by Martin-Grunewald** [comment]
@davidlange6 
You did integrate the equivalent 75X PR, so please then also integrate this PR for 76X.
Thanks!

**Comment by davidlange6** [comment]
+1

**Pull request merged**
