### PR TITLE
Backport of #28854 (Updates for Custom JME NanoAODs: Fix JetID, update modifiers and able to run on data)

### PR DESCRIPTION
**Pull request by nurfikri89**
**Backport of additions from #28854**

This PR updates the Custom JME NanoAOD with the following items:

1. Update era modifiers with run2_jme_2016 and run2_jme_2017.
2. Setup the proper JetID versions according to PUPPI vs CHS for each year.
3. Made necessary changes such that it can now run on data. Added wrapper functions to be used when specifying customise_commands when running on MC or data.

**if this PR is a backport please specify the original PR:**

Original PR is #28854

### CODE REVIEW

**Comment by perrotta** [comment]
@nurfikri89 Please fix conflicts

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
please abort

**Comment by perrotta** [comment]
+1
- Identical backport of #28854, now merged in the master
- Specialization is added in nanoAOD for usage with MC or data, and the proper Run2 JetID version is defined based on the year of data taking
- Reco output doesn't change

**Comment by peruzzim** [comment]
+xpog

**Comment by silviodonato** [comment]
+1

**Comment by santocch** [comment]
+1

**Pull request merged**
