### PR TITLE
Fix compiler warning in CalibCalorimetry/HcalAlgos

### PR DESCRIPTION
**Pull request by lgray**
Remove a do-while loop that only ever executed once.
Now we just execute the code.

### CODE REVIEW

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
@cmsbuild please abort

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
Can someone please take a look at this and sign if off?

**Comment by franzoni** [comment]
I've found no changes in a few relvals

however I find it hard to grap the logic: you've turned a loop with two stopping conditions
into a single execution of a piece of code 

Did you intend to reproduce the same behaviour, just by different means ?

**Comment by lgray** [comment]
Hi Giovanni, exactly.

Before there was the do ... while which executed once and had a break
statement in it.
Now that the loop is removed that break statement is in the *outer* loop
and would alter the logic of the loop over the rbxs instead.
So, the equivalent statement without the do...while is a continue, since it
skips the same code without breaking the loop.

On Tue, Jan 17, 2017 at 9:42 AM, Giovanni Franzoni <notifications@github.com

**Comment by ghellwig** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
