### PR TITLE
Update a few GTs in autoCond

### PR DESCRIPTION
**Pull request by perrotta**
The following GTs were updated in autoCond to the latest version available for them in the DB.

- GlobalTag for Run3 offline data reprocessing, 'run3_data':  
  -  [140X_dataRun3_v17](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/140X_dataRun3_v17) ([diff](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/140X_dataRun3_v17/140X_dataRun3_v16) wrt previous version v16)
  - Fix HCal Pedestals and Gains to solve the issue reported in [gitlab](https://gitlab.cern.ch/cms-ppd/event-performance/ep-coordination/-/issues/5#note_8640560), see [cmsTalk](https://cms-talk.web.cern.ch/t/call-for-conditions-re-reco-of-2024-eras-c-d-e/42331/23)
- GlobalTag for MC production with realistic conditions for Phase1 2022, 'phase1_2022_realistic':
  - [140X_mcRun3_2022_realistic_v12](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/140X_mcRun3_2022_realistic_v12) ([diff](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/140X_mcRun3_2022_realistic_v11/140X_mcRun3_2022_realistic_v12) wrt previous version v11)
  - Update the muon alignment as for [cmsTalk](https://cms-talk.web.cern.ch/t/call-for-conditions-full-2022-2023-data-rereco-and-mc-production-in-140x/32887/53) 
- GlobalTag for MC production with realistic conditions for Phase1 2023, 'phase1_2023_realistic':
  - [140X_mcRun3_2023_realistic_v9](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/140X_mcRun3_2023_realistic_v9) ([diff](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/140X_mcRun3_2023_realistic_v7/140X_mcRun3_2023_realistic_v9) wrt previous version v7)
  - Update the muon alignment as for [cmsTalk](https://cms-talk.web.cern.ch/t/call-for-conditions-full-2022-2023-data-rereco-and-mc-production-in-140x/32887/52) 
  - Update the SiPixelStatus tags as for [cmsTalk](https://cms-talk.web.cern.ch/t/call-for-conditions-full-2022-2023-data-rereco-and-mc-production-in-140x/32887/51)

To be backported in 14_1_X and 14_0_X

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
+alca
- The same unit test has errors also in the IB (even though the log is different)
- The [identical PR](https://github.com/cms-sw/cmssw/pull/46672) is running without errors in CMSSW_14_1_X

**Comment by antoniovilela** [comment]
+1

**Comment by antoniovilela** [comment]
merge

**Pull request merged**
