### PR TITLE
[106X backport] Add DY option to Embedding HepMC filter

### PR DESCRIPTION
**Pull request by IzaakWN**
### PR description
Backport of PR https://github.com/cms-sw/cmssw/pull/38829

### PR validation
See PR https://github.com/cms-sw/cmssw/pull/38829 and https://indico.cern.ch/event/1170879/#2-validation-of-exclusive-dy-t

### PR backporting
Backporting to `CMSSW_10_6_X`, beause we would like to reproduce the `DYJetsToTauTauToMuTauh_M-50` sample for Run-2 UL MC for TauPOG studies, and allow the H → WW analysis to use this updated filter.

### CODE REVIEW

**Comment by SiewYan** [comment]
please test

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
please abort

**Comment by perrotta** [comment]
test parameters:
- workflow = 136.9
- addpkg = TauAnalysis/MCEmbeddingTools

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
backport of https://github.com/cms-sw/cmssw/pull/38829

**Comment by civanch** [comment]
+1

**Comment by qliphy** [comment]
@cms-sw/generators-l2 Do you have any further comment?

**Comment by Saptaparna** [comment]
No further comments. +1

**Comment by qliphy** [comment]
+generators
see above

**Comment by qliphy** [comment]
merge

**Pull request merged**
