### PR TITLE
Avoid freeing memory owned by TMVA::Reader

### PR DESCRIPTION
**Pull request by smuzaffar**
This was noticed by valgrid https://github.com/cms-sw/cmssw/issues/19179#issuecomment-307687417 
It is same issue mentioned here https://github.com/cms-sw/cmssw/pull/17266

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by Dr15Jones** [comment]
Leaking memory at the beginning of the job doesn't look like a good solution to me.

**Comment by smuzaffar** [comment]
@Dr15Jones , why you think it is a memory leak? TMVA::Reader destructor  (https://github.com/root-project/root/blob/4fa59f4fb80fd914cb84144e5218e55397810c01/tmva/tmva/src/Reader.cxx#L289) is going to free it  at the end of this function

**Comment by lgray** [comment]
Indeed, looks like they fixed that problem...

**Comment by lgray** [comment]
Yeah fixed here: https://github.com/root-project/root/commit/e22060814e21266d24bd171b22cf45e56a809bc2

**Comment by Dr15Jones** [comment]
I withdraw my objection. The version of `BookMVA` we call does have the memory cleaned up. The other public version which we are not calling in this code does not clean up its memory:
https://github.com/cms-sw/root/blob/cms/v6-08-06/tmva/tmva/src/Reader.cxx#L439

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/19207	6b0e61e
- the same change as was done in the past in e.g. https://github.com/cms-sw/cmssw/pull/17266/files#diff-5ec5d166fbe4a06101a391228700a62bL187
- jenkins tests pass (Reco comparison results: 0 differences found in the comparisons)

**Comment by davidlange6** [comment]
+1

**Pull request merged**
