### PR TITLE
Cleaning Obsolete upgrade files

### PR DESCRIPTION
**Pull request by boudoul**
I'm removing files which are (super) old remnants of upgrade tracker scenarios not anymore used for years. More cleaning / reorganizing of the tracker packages/files to come, but starting with the obvious ones.

### CODE REVIEW

**Comment by boudoul** [comment]
put back recoFromSimDigis actually used in phase1tkcustoms

**Comment by ianna** [comment]
+1

**Comment by boudoul** [comment]
Looks like I need to clean the Buildfile, I will do a bit later

**Comment by boudoul** [comment]
Closing this PR  in order to submit a fixed PR

**Pull request closed without merging**
