### PR TITLE
[101X][L1T][DQMOffline] CaloJets -> PFJets for L1T Offline DQM

### PR DESCRIPTION
**Pull request by kreczko**
Backport of #23458

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by thomreis** [comment]
+1

**Comment by davidlange6** [comment]
Your PR is unmergeable. Please have a look and possibly rebase it.

**Comment by kreczko** [comment]
tried with the github resolve tool, should be OK now.

**Comment by thomreis** [comment]
+1

**Comment by fabiocos** [comment]
+1

validated in CMSSW_10_2_0_pre5

**Pull request merged**
