### PR TITLE
Fix AllStepsToTree option to runP_Tracker.py script

### PR DESCRIPTION
**Pull request by cvuosalo**
Issue #31069 concerned the script `Validation/Geometry/test/runP_Tracker.py` that terminates with an exception if its `AllStepsToTree` is set to True. This PR fixes the problem and allows the script to run to completion and produce its output files.

The problem was that a `TTree` was created before its `TFile` was created. When the `TTree` reached 1 MB in memory, this exception was generated:
```
---- Begin Fatal Exception 28-Feb-2022 21:20:13 CET-----------------------
An exception of category 'FatalRootError' occurred while
   [0] Processing  Event run: 1 lumi: 1 event: 17 stream: 0
   [1] Running path 'p1'
   [2] Calling method for module OscarMTProducer/'g4SimHits'
   Additional Info:
      [a] Fatal Root Error: @SUB=TBranch::WriteBasketImpl
basket's WriteBuffer failed.

----- End Fatal Exception -------------------------------------------------
```
The fix is to create a temporary file for the `TTree` to use. This file can't be used for the actually writing, because the program has another file open that can clash with the temporary file. Thus, when the `TTree` is complete, the final output file is created and the temporary is removed.

#### PR validation:

The script runs successfully to completion and produces complete output files. Here are the commands to test the script:
```
cmsRun test/single_neutrino_cfg.py nEvents=1000
python3 test/runP_Tracker.py geom="Extended2017Plan1" label=Tracker 
```

No backport is needed.

### CODE REVIEW

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by jfernan2** [comment]
+1

**Comment by cvuosalo** [comment]
+1

**Comment by cvuosalo** [comment]
type bug-fix

**Comment by qliphy** [comment]
+1

**Pull request merged**
