### PR TITLE
Central skims for 2018 PbPb run

### PR DESCRIPTION
**Pull request by mandrenguyen**
Replace central skim cffs from 2016 pPb with ones for this year's 2018 PbPb run.
These will only be testable once the HLT menu is integrated, which should be soon.

### CODE REVIEW

**Comment by fabiocos** [comment]
@mandrenguyen do we really need to drop old stuff, would not be an era-based approach possible?

**Comment by mandrenguyen** [comment]
@fabiocos  I don't really see the motivation for keeping the 2016 pA central skims around.  We won't have more pA data until midway through Run 3 at earliest.  Even then we would likely not reuse the same skimming configurations.   I can bring those old cffs back if you prefer.  However, I would not bother with trying to control which prompt skims are run based on an era.   AFAIK central skims are implemented directly in the T0 configuration.

**Comment by fabiocos** [comment]
@prebello @zhenhu @davidlange6 do we have a general policy for maintaining older skims? 
At present there is nothing in the release for PbPb as far as I can see, and the pA skims of 5_3_X had gone since a while

**Comment by davidlange6** [comment]
My 2 cents
a) we should maintain skims that are not obsolete (skims likely needed in run3 are not obsolete)
b) skims should not be controlled by era rather by cmsDriver command.

**Comment by prebello** [comment]
Hi @fabiocos  about Skims, @kfjack has contacted HIN group after PdmV request to get the necessary inputs and can give more details.  Please, @mandrenguyen @kkrajczar could you comment on the thread "status SKIM matrix for HI"?
Thank you‎

**Comment by mandrenguyen** [comment]
@prebello
After this PR is merged, I think we just need to provide the mapping between PD and central skim to the T0 hypernews.  @kfjack can correct me if that's wrong.

 Please note that @kkrajczar is no longer in CMS

Regarding maintaining older skims, the 2016 pA skims will not be reused in Run 3.

**Comment by fabiocos** [comment]
please test workflow 140.56,140.57

**Comment by prebello** [comment]
+1

tests approved

**Comment by fabiocos** [comment]
+operations

the update of the StandardSequences is coherent with the PR purpose

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
@mandrenguyen in my check I missed that 140.54 is using the PA skim, apologies for this. As PA sequences do not harm, I will restore them, although I think that this workflow has mostly a technical use.

**Pull request merged**
