### PR TITLE
[12_4_X] Adding HZZ electron MVA ID 

### PR DESCRIPTION
**Pull request by asculac**
#### PR description:
Backport of https://github.com/cms-sw/cmssw/pull/38355
- adding HZZ training for electron ID, which is an EGgamma-approved ID (latest talk at egamma POG [here](https://indico.cern.ch/event/895972/contributions/4297090/attachments/2219102/3757479/ElectronID_Egamma31032021.pdf) ) used for H->4l, which cannot otherwise be recomputed on top of nanoAODs. 
- It is based on the same electronMVAValueMapProducer used for existing mvaIds, but with an updated and separate training for 2016UL, 2017UL and 2018UL.
- A single variable mvaHZZIso is added to electrons. The appropriate training to be used is selected automatically. The idea is that the variable name will stay the same in the future, selecting a new training when appropriate.
- No need to store working points as bools since these can be easily derived from the MVA value.

- In addition to this PR: renaming mva Egamma IDs to be more generic 

#### PR validation:

- Tested in CMSSW_12_4_0_pre1; verified that the new variable is added correctly.
- Adds 1 float per electron.

This PR is a backport of https://github.com/cms-sw/cmssw/pull/38355

### CODE REVIEW

**Comment by mariadalfonso** [comment]
please test

**Comment by mariadalfonso** [comment]
backport of https://github.com/cms-sw/cmssw/pull/38355

**Comment by asculac** [comment]
I forgot to set mvaHZZIso to None also for run3_nanoAOD_devel, I apologize for this overlook. It should be okay now

**Comment by gouskos** [comment]
please test

**Comment by gouskos** [comment]
+xpog
Thanks @asculac. Modifications in line with PR description

**Comment by clacaputo** [comment]
+reconstruction

- RECO differences are related to the new variable "mvaHZZIso", not present in the reference release. This new var shifts some electronTable columns, introducing some artefact differences. See https://github.com/cms-sw/cmssw/pull/38355
- backport is in line with the original pr

**Comment by qliphy** [comment]
+1

**Pull request merged**
