### PR TITLE
Prepare Pythia8Interface to pythia8 219

### PR DESCRIPTION
**Pull request by mkirsano**

### CODE REVIEW

**Comment by mkirsano** [comment]
This is compatible with the current pythia8

**Comment by govoni** [comment]
+1

**Comment by degano** [comment]
please test with cms-sw/cmsdist#2294

**Comment by covarell** [comment]
please test with cms-sw/cmsdist#2294

**Comment by covarell** [comment]
I retried tests because I could not figure out what the problem is and want to see if it is transient...

**Comment by davidlange6** [comment]
the error was unrelated

**Pull request merged**
