### PR TITLE
Remove obsolete Scouting Data Format unit tests

### PR DESCRIPTION
**Pull request by wddgit**
#### PR description:

Remove obsolete Scouting Data Format unit tests

These tests were replaced by newer tests and there is discussion related to that in the PR comments of the PRs adding the new unit tests. See #41913 and #41834.

#### PR validation:

This only removes obsolete unit tests. There is nothing to test. The newer unit tests that replace them still pass after removal.

### CODE REVIEW

**Comment by wddgit** [comment]
There is one thing related to these old tests that bothers me slightly. I am leaning towards just ignoring this, but if someone thinks it is worth investigating I will or maybe someone else should...

In the IBs in the ROOT6_X area, the tests removed by this PR are failing. It is only in ROOT6_X build, in all the others it passes. Does anyone understand this? Is it worth worrying about? The log file output is gigantic so it is hard to look at and I don't understand it...

```
===== Test "testDataFormatsScoutingRun2" ====
...
/data/cmsbld/jenkins/workspace/ib-run-qa/CMSSW_13_2_ROOT6_X_2023-06-12-2300/src/DataFormats/Scouting/test/testDataFormatsScoutingRun2.sh: line 26: 2815602 Killed                  "${SCRAM_TEST_PATH}"/scoutingCollectionsDumper.py -v 1 -n 1 --skip 81 -i testDataFormatsScoutingRun2_step1.root -k Scouting > testDataFormatsScoutingRun2_step2.log 2> testDataFormatsScoutingRun2_step2_stderr.log

Failure running scoutingCollectionsDumper.py: status 137
=== Log File ==========
malloc_consolidate(): unaligned fastbin chunk detected
 *** Break *** abort
malloc(): unsorted double linked list corrupted
 *** Break *** abort
...
```

**Comment by wddgit** [comment]
please test

**Comment by makortel** [comment]
> In the IBs in the ROOT6_X area, the tests removed by this PR are failing. It is only in ROOT6_X build, in all the others it passes. Does anyone understand this? Is it worth worrying about?

@pcanal is investigating the crash (more details in https://github.com/cms-sw/cmssw/issues/41222).

**Comment by makortel** [comment]
Let's keep @missirol in the loop

**Comment by makortel** [comment]
hold

Until the ROOT problem with the earlier test is understood (https://github.com/cms-sw/cmssw/issues/41222#issuecomment-1595320732)

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
unhold

**Comment by makortel** [comment]
> Until the ROOT problem with the earlier test is understood ([#41222 (comment)](https://github.com/cms-sw/cmssw/issues/41222#issuecomment-1595320732))

The ROOT problem was worked around (see the issue for more details)

**Comment by makortel** [comment]
Comparison differences are related to https://github.com/cms-sw/cmssw/issues/39803

**Comment by makortel** [comment]
+core

**Comment by rappoccio** [comment]
+1

**Pull request merged**
