### PR TITLE
Added FinalPath implementation [12_2]

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:
OutputModules placed on a FinalPath do not cause unscheduled execution. This ability was requested by HLT.

As part of work, consolidated all copied code used in various OutputModuleBase implementations into one class.

Backport of #36398

#### PR validation:

Code compiles. All framework related unit tests (included the newly added ones) pass.

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by Dr15Jones** [comment]
The failure is unrelated to this PR. SQLite is reporting a disk I/O failure.

**Comment by makortel** [comment]
> The failure is unrelated to this PR. SQLite is reporting a disk I/O failure.

For the record, this error (occurring also in IBs) is reported in https://github.com/cms-sw/cmssw/issues/36319.

**Comment by makortel** [comment]
+1

**Comment by qliphy** [comment]
merge

**Pull request merged**
