### PR TITLE
Revert "L1T EMTF O2O 2018"

### PR DESCRIPTION
**Pull request by fabiocos**
Reverts cms-sw/cmssw#23759

Temporary workaround for the problem described in #23873 to allow the integration without massive test failures.

### CODE REVIEW

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
@smuzaffar apparently the test failed, but it is unclear to me why

**Comment by fabiocos** [comment]
please test

**Comment by smuzaffar** [comment]
connection to github is failing frequently, I have connected to github

**Comment by fabiocos** [comment]
tested to remove the failure on top of CMSSW_10_3_X_2018-07-19-2300 for wf 136.871

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Pull request merged**
