### PR TITLE
Prepare for table set 160812; general cleanup

### PR DESCRIPTION
**Pull request by namapane**
**No** change in default behavior.
This PR includes:
-new MF geometry XML files;
-cleanup obsolete download.url files;
-update tools for table conversion and for generation of .db payloads for MF geometry and configuration;
-update validation, field visualization and regression tools;
-allow for the larger boundary of map version 160812.

For information about maps, cf. https://indico.cern.ch/event/642366/contributions/2606389/ .

### CODE REVIEW

**Comment by slava77** [comment]
@namapane 
all new topic pull requests should be made to master branch (it is now corresponding to CMSSW_9_3_X).
Please close this and reopen for master/93X.
Thank you.

**Comment by slava77** [comment]
also, do we have to have the MF geometry XML files in the release?
Isn't the geometry now all setup to just use the payloads from DB?

**Comment by namapane** [comment]
Yes, but we always also kept the input xml files in the release. I 
personally think it is safer to have them in, but if you prefer I can 
remove them all and archive them somewhere else.

Cheers
	Nicola

**Comment by slava77** [comment]
Hi Nicola,
Please take note of https://github.com/cms-sw/cmssw/pull/19454#issuecomment-311433756
This PR should be closed and reopened in master branch for CMSSW_9_3_X.
Thank you.

**Comment by namapane** [comment]
Yes, but I am waiting to an answer to the previous question about removing the XML files, see above.

**Comment by slava77** [comment]
On 6/28/17 10:11 AM, Nicola Amapane wrote:
> Yes, but I am waiting to an answer to the previous question about
> removing the XML files, see above.
> 

I guess if a few of the old ones can be dropped, the net change is
acceptable.

**Comment by namapane** [comment]
No, there're no old ones that can be dropped for the time being. So 
either I keep these new ones in the PR, or I remove all of them.

Cheers
	Nicola

**Comment by slava77** [comment]
On 6/28/17 2:48 PM, Nicola Amapane wrote:
> 
> No, there're no old ones that can be dropped for the time being. So
> either I keep these new ones in the PR, or I remove all of them.
> 

Hi Nicola,

Are these xml files hand-edited (~10K lines each), or are they
auto-generated?
For the latter case, I think it's more appropriate to remove the
auto-generated output and make sure the "auto-generator" is in the release.

		--slava

**Comment by namapane** [comment]
They are automatically generated but starting from a description file 
that is edited by hand by Slava Kl (since the geometry must match the 
FEM model geometry).
I agree on the general idea of committing automatic generators, but in 
this case there's little gain in committing the generator code since we 
would need to commit the hand-edited files, and as the code gets updated 
with time there is no guarantee it will keep generating exactly the same 
xmls for all supported old versions. I generally use the xmls for 
debugging or visualization and I need to be 100% sure they are verbatim 
those that were fed into the DB. So I would never re-generate them when 
I need them; I would rather pick the original ones whether they are in 
the release or archived elsewhere. So in short I'd rather remove the 
xmls (or, keep them) than maintain a backward-compatible version that I 
actually do not need.

Cheers
	Nicola

**Comment by slava77** [comment]
On 6/28/17 3:57 PM, Nicola Amapane wrote:
> 
> They are automatically generated but starting from a description file
> that is edited by hand by Slava Kl (since the geometry must match the
> FEM model geometry).
> I agree on the general idea of committing automatic generators, but in
> this case there's little gain in committing the generator code since we
> would need to commit the hand-edited files, and as the code gets updated
> with time there is no guarantee it will keep generating exactly the same
> xmls for all supported old versions. I generally use the xmls for
> debugging or visualization and I need to be 100% sure they are verbatim
> those that were fed into the DB. So I would never re-generate them when
> I need them; I would rather pick the original ones whether they are in
> the release or archived elsewhere. So in short I'd rather remove the
> xmls (or, keep them) than maintain a backward-compatible version that I
> actually do not need.
> 

Sorry for still picking on the "all or none" option.

If I understand correctly, files created with older releases can not be
reproduced verbatim.
Also, it sounds like there is little utility from older files that were
already fed into the DB and were extensively validated.

It sounds like it's more practical to keep only the new ones
until they make it into a stable release (after being parsed to a DB and
properly validated)
and perhaps until a future new version comes in.
If the older ones are still needed, it only takes to check out an older
release and get the files.

Did I miss something?

**Comment by namapane** [comment]
That is essentially it. I generally compare differences with N-1 
versions when new ones appear but very rarely with earlier ones and yes 
I can always pick them from github, so OK let's go for your proposal.

Cheers
	Nicola

**Pull request closed without merging**
