### PR TITLE
Clean up muon alignment test files

### LINKED ISSUE #49: More MuonAlignment ES get() calls
going to https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc7_amd64_gcc900/CMSSW_12_2_CMSDEPRECATED_X_2021-11-03-2300/Alignment/MuonAlignment
crtl-f `.get(`
gives me 10 occurrences

### PR DESCRIPTION
**Pull request by hyunyong**
#### PR description:

Resolves https://github.com/cms-AlCaDB/AlCaTools/issues/49
Clean up unused test files

### CODE REVIEW

**Comment by mmusich** [comment]
I think the title of this PR is misleading. There's no migration as a matter of fact,  just a deletion of files.

**Comment by hyunyong** [comment]
> I think the title of this PR is misleading. There's no migration as a matter of fact, just a deletion of files.

Yes, I changed the title.
Thank you.

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
+alca
 * simple clean-up

**Comment by perrotta** [comment]
+1

**Pull request merged**
