### PR TITLE
New dqm modules for PFHT paths (rebase of #9027)

### PR DESCRIPTION
**Pull request by jruizvar**
Add dqm modules for the new PFHT triggers.

This pull request supersedes #9027

### CODE REVIEW

**Comment by degano** [comment]
@cmsbot please test

**Comment by deguio** [comment]
please test

**Comment by jruizvar** [comment]
If I understand correctly, the error comes from the DQMHarvestMuon_step:

%MSG-e DQMGenericClient:  DQMGenericClient:hltMuonEfficiencies@endJob  04-Jun-2015 16:03:47 CEST PostEndRun
 DQMGenericClient::findAllSubdirectories ==> Missing folder HLT/Muon !!!
%MSG

However, this request don't touch the HLT/Muon folder.

**Comment by deguio** [comment]
please test
test results not available

**Comment by deguio** [comment]
+1
this PR adds 2340 bins.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
