### PR TITLE
Muon HLT for IterL3: porting to new seeding 

### PR DESCRIPTION
**Pull request by folguera**
Modified MuonTrackingRegionBuilder to be compatible with the new seeding algorithm for the iterative tracking.  

Was #17924 in 91X

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by perrotta** [comment]
+1
- Reorganized ParameterSetDescription in MuonTrackingRegionBuilder to be compatible with the new seeding algorithm for the IT
- No changes expected in the results, no changes observed in jenkins tests

**Comment by davidlange6** [comment]
+1

**Pull request merged**
