### PR TITLE
Backport `ConditionalTask` to CMSSW_12_3_X

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

This PR backports from CMSSW 12.4.x/12.5.x the PRs that implement the `ConditionalTask`:
  - #37305: Added ConditionalTask
  - #37563: Make SwitchProducer work with ConditionalTask
  - #37872: Fix dumpPython() for Task and ConditionalTask when they contain > 255 elements
  - #38006: Fix behavior of SwitchProducer in ConditionalTask with non-chosen EDAlias case(s) that are consumed explicitly

#### PR validation:

Unit tests in `FWCore/Integration` pass.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Backports #37305, #37563, #37872, #38006.

### CODE REVIEW

**Comment by fwyzard** [comment]
This PR is probably _not_ needed in the release; for the time being it is useful for local tests.

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by fwyzard** [comment]
backport #37305, #37563, #37872

**Comment by missirol** [comment]
Was https://github.com/cms-sw/cmssw/pull/37562 also needed? Based on https://github.com/cms-sw/cmssw/pull/37563#issue-1203905234.

**Comment by fwyzard** [comment]
I thought so, but it looks like #37562 is already included in #37933, which has already been merged into CMSSW_12_3_X .

**Comment by fwyzard** [comment]
> ---> test SiStripDAQ_O2O_test had ERRORS

As usual ...

**Comment by missirol** [comment]
backport of https://github.com/cms-sw/cmssw/pull/37305
backport of https://github.com/cms-sw/cmssw/pull/37563
backport of https://github.com/cms-sw/cmssw/pull/37872
backport of https://github.com/cms-sw/cmssw/pull/38006

`backport` label was missing :)

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Pull request closed without merging**
