### PR TITLE
Implement a simple vector add test with alpaka

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Implement a simple vector add test with alpaka and `cms::alpakatools` utilities.

#### PR validation:

The new tests pass.

### CODE REVIEW

**Comment by fwyzard** [comment]
hold

**Comment by fwyzard** [comment]
In addition to adding the test, this PR is going to be used to exemplify two problems in the SCRAM build rules:
  - the `*.dev.cc` files are compiled with `nvcc` even when building the CPU version of the tests
  - SCRAM does not actually run the alpaka tests when invoked as `scram b runtests`

**Comment by fwyzard** [comment]
enable gpu

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
enable gpu

**Comment by fwyzard** [comment]
please test with cmsdist#8255

**Comment by smuzaffar** [comment]
please test with https://github.com/cms-sw/cmsdist/pull/8256

**Comment by fwyzard** [comment]
please test with cms-sw/cmsdist#8256

**Comment by fwyzard** [comment]
please test with cms-sw/cmsdist#8256

**Comment by fwyzard** [comment]
unhold

**Comment by fwyzard** [comment]
OK, the test infrastructure now works, and the simple test works as well.
While I'm looking to add a N-dimensional test, these changes could already go in as they are.

**Comment by fwyzard** [comment]
+heterogeneous

**Comment by perrotta** [comment]
+1

**Pull request merged**
