### PR TITLE
L1T muon DQM upgrades part2

### PR DESCRIPTION
**Pull request by thomreis**
Upgrades for the L1T muon DQM

- Reduce number of bins for uGMT histograms.
- Retune quality tests.
- Move some uGMT quality tests to separate muon quality test configurations for all runs and additional tests fro collisions runs.
- Add OMTF quality tests.
- uGT data vs. emulator quality tests.
- update of L1T client.

### CODE REVIEW

**Comment by thomreis** [comment]
please test

**Comment by thomreis** [comment]
supersedes PR #23373

**Comment by dmitrijus** [comment]
+1

**Comment by fabiocos** [comment]
+1

on wf 10824 there is a reduction of about 850 kB in memory usage

**Comment by thomreis** [comment]
I have reduced the number of bins for some histograms so I would expect a reduction.

**Pull request merged**
