### PR TITLE
Removed the RPCEfficiency folder in RPC DQM

### PR DESCRIPTION
**Pull request by jeongsumin**
#### PR description:

This PR is contained about remove the "RPCEfficiency" folder which seems to be never used in RPC DQM.
 
In the offline DQM, there are several memory problems (this is running in Tier0). 
And DQM offline may have more histograms (~17k). 

So we need to reorganize what is unused or used.

Therefore in the first step, we should remove this folder which is contained 4667 histograms.

#### PR validation:

I tested this changes with runTheMatrix.py 136.867 (RunSingleMu2018B) & 30.0 (ZMM)

#### if this PR is a backport please specify the original PR:
N/A

@jhgoh

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by fabiocos** [comment]
@jeongsumin @jfernan2 this PR looks like a new development, am I correct? Why is it proposed in 10_6_X and not in master first?

**Comment by jhgoh** [comment]
> @jeongsumin @jfernan2 this PR looks like a new development, am I correct? Why is it proposed in 10_6_X and not in master first?

Correct. This should go to the master branch first.

**Comment by jfernan2** [comment]
@jeongsumin   please close it and resubmit to master, sorry I did not notice from the beginning

**Comment by jeongsumin** [comment]
@jfernan2 @jhgoh @fabiocos 
I'm so sorry for the late answer.
Then I am going to close this PR from now on and resubmit to master 11_0_X branch.

**Pull request closed without merging**
