### PR TITLE
DD4hep-based Geometry Description to G4 Geometry Converter

### PR DESCRIPTION
**Pull request by ianna**
#### PR description:

This PR is intended for discussion only. It does not need to be merged in IBs. @mrodozov is working on adding DDG4 static library, so eventually this code will be picked up from an external. These are DD4hep classes needed to convert a DD geometry description to a G4 geometry.

* DD4hep geometry to G4 geometry converter
* Added a test and its configuration

**There is one issue:** the converter does not like our _material:Vacuum_ definition:

```
<ElementaryMaterial name="Vacuum" density="1e-13*mg/cm3" symbol=" " atomicWeight="1*g/mole" atomicNumber="1"/>
```
as it passes it to G4 the latter throws:
```
-------- EEEE ------- G4Exception-START -------- EEEE -------

*** ExceptionHandler is not defined ***
*** G4Exception : mat012
      issued by : G4Element::G4Element()
Fail to create G4Element CMS element with Z= 2  N= 1   N < Z is not allowed

*** Fatal Exception ***
-------- EEEE -------- G4Exception-END --------- EEEE -------
```

Instead, the following Vacuum definition as a thin Air works fine:
```
<CompositeMaterial name="Vacuum" density="1e-10*mg/cm3" symbol=" " method="mixture by weight">
   <MaterialFraction fraction="0.7494">
    <rMaterial name="materials:Nitrogen"/>
   </MaterialFraction>
   <MaterialFraction fraction="0.2369">
    <rMaterial name="materials:Oxygen"/>
   </MaterialFraction>
   <MaterialFraction fraction="0.0129">
    <rMaterial name="materials:Argon"/>
   </MaterialFraction>
   <MaterialFraction fraction="0.0008">
    <rMaterial name="materials:Hydrogen"/>
   </MaterialFraction>
  </CompositeMaterial>
```
which creates:
```
Geant4Converter        ++ Created G4  Material: materials:Vacuum    density:  0.000 mg/cm3  RadL: 5864694.266 km   Nucl.Int.Length: 13694660.844 km 
                       Imean:  85.538 eV   temperature: 273.15 K  pressure:   1.00 atm
```

#### PR validation:

```
cmsRun SimG4Core/DD4hepGeometry/test/python/testG4Geometry.py
```

#### if this PR is a backport please specify the original PR:

no back port is needed

### CODE REVIEW

**Comment by ianna** [comment]
@civanch, @Dr15Jones, @cvuosalo, @ianna, @mdhildreth, @davidlange6, @slava77, @fabiocos, @smuzaffar, @bsunanda, @kpedro88 - FYI

**Comment by ianna** [comment]
assign simulation

**Comment by ianna** [comment]
@smuzaffar - please, check the proposed code fixes :-)
```
-      virtual ~Geant4GeometryInfo();
+      ~Geant4GeometryInfo() override override override override;
```

**Comment by smuzaffar** [comment]
@ianna , indeed this does not look right. Let me check

**Comment by smuzaffar** [comment]
code-checks
This is know feature/bug of `clang-tidy` ( http://lists.llvm.org/pipermail/cfe-dev/2015-December/046566.html ). If more than one source files propose a same fix for a header then `clang-apply-replacements` apply it multiple times. I have fixed the build rules to avoid this duplications.

**Comment by ianna** [comment]
replaced by https://github.com/cms-sw/cmssw/pull/26383 and https://github.com/cms-sw/cmssw/pull/26423

**Pull request closed without merging**
