### PR TITLE
Enable .59521 and .59621 wfs for profiling

### PR DESCRIPTION
**Pull request by srimanob**
#### PR description:
This PR is a follow up from https://indico.cern.ch/event/1297976/#17-update-on-gpu-profiling. 
It enables .59521 and .59621 wfs for profiling.

#### PR validation:
Test with 11634.59521, all steps run.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:
No need of backport.

### CODE REVIEW

**Comment by srimanob** [comment]
test parameters:
- workflows = 11834.59521
- relvals_opt = --what cleanedupgrade,standard,highstats,pileup,generator,extendedgen,production,identity,ged,machine,premix,nano,gpu,2017,2026

**Comment by srimanob** [comment]
@cmsbuild please test

**Comment by srimanob** [comment]
FYI @gartung @fwyzard

**Comment by srimanob** [comment]
+Upgrade

The new `11834.59521` runs fine.

**Comment by fwyzard** [comment]
> FYI @gartung @fwyzard

Thanks for adding these workflows.

**Comment by srimanob** [comment]
Kindly ping @cms-sw/pdmv-l2

**Comment by sunilUIET** [comment]
+pdmv

**Comment by perrotta** [comment]
+1

**Comment by srimanob** [comment]
> @srimanob Should this work with 23834 workflows as well?

Hi @gartung 
We need https://github.com/cms-sw/cmssw/pull/41011 to extend patatrack to  newer geometry. I will push for that.

**Comment by gartung** [comment]
@srimanob No gpu kernels were run in the 59621 workflow. Previously I had added 
```process.options.accelerators = ['gpu-nvidia']```, but I don't see this in the generated config files.
The [nsys log file](https://cmssdt.cern.ch/SDT/jenkins-artifacts/profiling/CMSSW_13_2_X_2023-07-11-1100/el8_amd64_gcc11/11834.59621/step3_gpu_nsys.log) does not show any kernels being run.

**Comment by srimanob** [comment]
@fwyzard @AdrianoDee @makortel 
Do you have some clues?

What I understand is that, `.59621` is a clone of `.596` which should use GPU if available, and `procmodifier` of GPU is enable.
https://github.com/cms-sw/cmssw/blob/master/Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py#L1422-L1462

` '--accelerators': 'gpu-nvidia',` is a must to use, which we don't expect to use it. The example of workflow is `.597` when we run both on CPU and GPU, then make comparison.

Thx.

**Comment by srimanob** [comment]
Just a note, I don't understand the log. It does not mean you don't have a match system to use GPU?

```
An exception of category 'UnavailableAccelerator' occurred while
   [0] Constructing the EventProcessor
Exception Message:
The system has no compute accelerators that match the patterns specified in process.options.accelerators:
 gpu-nvidia

The following compute accelerators are available:
 cpu
```

**Comment by gartung** [comment]
It could be an unrecognized nvidia gpu on cms-oc-gpu-01. It has two RTX 2060's.

```
----- Begin Fatal Exception 11-Jul-2023 23:43:18 CEST-----------------------
An exception of category 'UnavailableAccelerator' occurred while
   [0] Constructing the EventProcessor
Exception Message:
The system has no compute accelerators that match the patterns specified in process.options.accelerators:
 gpu-nvidia

The following compute accelerators are available:
 cpu
 ```

**Comment by gartung** [comment]
Oh. Wait... The logs got over written when I put the explicit modifier back.

**Comment by gartung** [comment]
I will re-run the job that generates the log.

**Comment by fwyzard** [comment]
CMSSW seems to recognize the GPUs without issues:
```
[2023-07-12 00:14:10] fwyzard@cms-oc-gpu-01:/cvmfs/cms-ib.cern.ch/sw/x86_64/week1/slc7_amd64_gcc11/cms/cmssw/CMSSW_13_2_X_2023-07-11-1100$ cudaComputeCapabilities 
   0     7.5    NVIDIA GeForce RTX 2060
   1     7.5    NVIDIA GeForce RTX 2060
```

**Comment by gartung** [comment]
It worked with the current IB
https://cmssdt.cern.ch/SDT/jenkins-artifacts/profiling/CMSSW_13_2_X_2023-07-12-1100/el8_amd64_gcc11/11834.59621/step3_gpu_nsys.txt

**Pull request merged**
