### PR TITLE
Phase2-hgx339X Delete obsolete files from Geometry/HGCalCommonData

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Delete obsolete files from Geometry/HGCalCommonData

#### PR validation:

Use the runTheMatrix test workflows

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by srimanob** [comment]
+Upgrade

Technical PR to remove obsoleted files.

**Comment by perrotta** [comment]
+1

**Pull request merged**
