### PR TITLE
Run3-hcx244 Switch of debug prints

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Switch off debug prints

#### PR validation:

Standard tests performed

#### if this PR is a backport please specify the original PR:

It is strictly not back porting. But the debug prints will be off in the master thread as well

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
+1

**Comment by fabiocos** [comment]
@bsunanda thank you, i consider this as a bug fix. Which is the PR implementing this in master?

**Comment by bsunanda** [comment]
@fabiocos I have removed the debug printing in #28506 - but that PR has many more things

**Comment by fabiocos** [comment]
@bsunanda thanks

**Comment by fabiocos** [comment]
bug-fix

**Comment by fabiocos** [comment]
+1

**Comment by cvuosalo** [comment]
@fabiocos @bsunanda It looks like one of the files in this PR never made it into 11_1, and it was left out of #28506. But the problem is minor. Maybe Sunanda can fix it in his next PR.

**Pull request merged**
