### PR TITLE
Fix SimPFProducer for electrons

### PR DESCRIPTION
**Pull request by rovere**
Please refer to the commit messages for further information.
There are also useful slides in [here](https://indico.cern.ch/event/748252/contributions/3100081/attachments/1698957/2735366/kunori_20180808_hgcsim_testing2.pdf]) and [here](https://indico.cern.ch/event/747942/contributions/3094699/attachments/1696999/2731800/kunori_20180801_hgcsim_ak4_PFcand.pdf)

Also, a new MonitorElement has been added in order to monitor the issue: the previously added Validation MonitorElements were not able to spot this issue.

I do expect some regression, but it fixes the issue.
The fix is geometry independent.

type bug-fix

### CODE REVIEW

**Comment by kpedro88** [comment]
please test workflow 24034.0

**Comment by andrius-k** [comment]
+1

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/24498	c3b1854
- changes in the reco code are rather straightforward (most easily seen with "?w=1" ) and fall in line with the added comment and the issue described in https://indico.cern.ch/event/747942/contributions/3094699/attachments/1696999/2731800/kunori_20180801_hgcsim_ak4_PFcand.pdf 
- jenkins tests pass and comparisons with the baseline show differences only in the phase-2 workflows, as expected, starting from PF candidates
e.g. in 21234
all_oldvsnew_ttbar14tev2023d21wf21234p0c_recopfcandidates_particleflow__reco_obj_eta
this affects only neutral hadrons (down by 14%) and photons (down by 3%)

**Comment by fabiocos** [comment]
+1

**Pull request merged**
