### PR TITLE
Fix dereference of PVOrig (master)

### PR DESCRIPTION
**Pull request by gpetruc**
Addressing https://its.cern.ch/jira/browse/CMSCOMPPR-3271

Master version of 94X PR #24137

@arizzi

### CODE REVIEW

**Comment by gpetruc** [comment]
please test

**Comment by gpetruc** [comment]
type bugfix

**Comment by gpetruc** [comment]
+1

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/24138	5317f93
- this is a rather trivial fix, adding a check for ```PVOrig.isNonnull() ``` before dereferencing it. It should affect only previously crashing events.
- jenkins tests pass
- I'm relying on tests done by @gpetruc in connection with https://its.cern.ch/jira/browse/CMSCOMPPR-3271 to confirm the problem resolution

**Comment by fabiocos** [comment]
+1

**Pull request merged**
