### PR TITLE
Compatibility changes of Pythia8Interface for pythia8 226

### PR DESCRIPTION
**Pull request by mkirsano**

### CODE REVIEW

**Comment by mkirsano** [comment]
This is to be tested together with cmsdist #3004

**Comment by perrozzi** [comment]
please test with cms-sw/cmsdist#3004

**Comment by perrozzi** [comment]
+1

**Comment by smuzaffar** [comment]
please test with cms-sw/cmsdist#3076

**Comment by smuzaffar** [comment]
please test with cms-sw/cmsdist#3076
try again

**Comment by perrozzi** [comment]
can this be merged?

**Comment by alberto-sanchez** [comment]
@davidlange6 ,  I am attaching few comparison plots for 226 and 212. 
[pythia8-226-validation.pdf](https://github.com/cms-sw/cmssw/files/1059167/pythia8-226-validation.pdf)

**Comment by perrozzi** [comment]
from GEN side this is OK

**Comment by davidlange6** [comment]
+1

**Pull request merged**
