### PR TITLE
Phase2-HGX350X Add a new workflow for a version containing V18 definition of HGCal

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Add a new workflow for a version containing V18 definition of HGCal

#### PR validation:

Use runTheMatrix test workflow 27234.0 designed for this scenario 2026D104

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
+geometry

**Comment by bsunanda** [comment]
@sunilUIET Can you approve this?

**Comment by sunilUIET** [comment]
+pdmv

**Comment by bsunanda** [comment]
@srimanob Can you approve this please?

**Comment by srimanob** [comment]
test parameters:
- workflow = 27234.0
- relvals_opt = --what cleanedupgrade,standard,highstats,pileup,generator,extendedgen,production,identity,ged,machine,premix,nano,gpu,2017,2026

**Comment by srimanob** [comment]
@cmsbuild please test

We should test the new workflow in the PR.

**Comment by srimanob** [comment]
FYI @fabiocos @24LopezR 
I propose to merge this PR first. Then ETL (https://github.com/cms-sw/cmssw/pull/43407) on top with new defined D105. Thx.

**Comment by mmusich** [comment]
@srimanob 

> The output of D104 is [very very noisy](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-204a05/36276/runTheMatrix-results/27234.0_TTbar_14TeV+2026D104/step3_TTbar_14TeV+2026D104.log) in RECO step. I think it does not relate to this PR, but tracker T35. I may missed it when we integrated D102 which uses T35 also. If this is confirmed, I will sign the PR, and open the issue to follow up. Thx.

this happens because in https://github.com/cms-sw/cmssw/pull/41880 it was forgotten to update the `label`s `forWidth` and `fromAlignment` in the map at `autoCondPhase2` (hence the relval job reads the ones (not being overridden) in the physical GT `auto:phase2_realistic`. Since this latter is based off geometry `T21` it doesn't have the split sensors in BPix1, thus the error messages. This is followed up at https://github.com/cms-sw/cmssw/pull/43482

**Pull request merged**
