### PR TITLE
allow user to select vtx or beamspot covariance

### PR DESCRIPTION
**Pull request by fojensen**
fixed a bug where the switch to allow the user to use the vertex instead of the beamspot did not correspondingly use the vertex as a reference to calculate the 3D & 2D decay significance

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test
@fojensen Frank, I suppose PRs for 75X and 76X are coming soon

**Comment by fojensen** [comment]
@slava77
once this goes through smoothly I was going submit the other two

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/12097	f054e42
- select correct covariance for V0 reco with "useVertex" (non-default option)
- jenkins tests pass and comparisons with baseline show no differences

@davidlange6 this will be needed for reference pp for HI

@fojensen please prepare 75X/76X/80X PRs

**Comment by fojensen** [comment]
@slava77

I do not see my original 76x PR in the IB list:
https://github.com/cms-sw/cmssw/pull/11699
https://cmssdt.cern.ch/SDT/html/showIB.html
I would like to use the IB to apply the fix
(as you can tell I found the 80X and the 75X)
thank you

**Comment by slava77** [comment]
Frank, the #11699 was merged on Oct 9 (as you can see from the PR itself).
The showIB page displays only recent merges (the past 10 days or so).
You can use 760pre7 for the tests 
https://github.com/cms-sw/cmssw/releases/CMSSW_7_6_0_pre7

**Comment by davidlange6** [comment]
+1

**Pull request merged**
