### PR TITLE
Run2-hcx130 Backport to 9_1_X the update of HB depth segmentation

### PR DESCRIPTION
**Pull request by bsunanda**
This is backporting of PR #19036

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by ianna** [comment]
+1

**Comment by bsunanda** [comment]
Since 9_1_X will not be used for barrel calorimeter TDR production I am closing this PR

**Pull request closed without merging**
