### PR TITLE
Update Higgs Dalitz paths (75X)

### PR DESCRIPTION
**Pull request by jasperlauwers**
backport of #11340

### CODE REVIEW

**Comment by perrotta** [comment]
@jasperlauwers : only the last commit in this ticket is actually the backport of #11340.
Could you please make separate pull requests for separate updates/fixes?
As such you would speed up the merging of this pull request, and as a consequence the integration of the new paths in the HLT menu.
@jasperlauwers : only the last commit in this ticket is actually the backport of #11340.
Could you please make separate pull requests for separate updates/fixes?
As such you would speed up the merging of the part which relates to the additional monitoring of the new Dalitz path(s), and as a consequence the integration of the new paths in the HLT menu.

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1

**Comment by jasperlauwers** [comment]
Adding backport #11636 
Adding it on top of this PR because the new commit also requires a small fix to the code.

**Comment by jasperlauwers** [comment]
The last backport for now #11198

**Comment by jasperlauwers** [comment]
The PR has been updated to contain the commits that have been validated in 7_6_0_pre6.

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
Closing - not needed for HeavyIons (only planned 75x usage)

**Pull request closed without merging**
