### PR TITLE
DQM: restore Muon POG sequence (and CSC Monitor), revert #46293

### PR DESCRIPTION
**Pull request by fabiocos**
#### PR description:

#46293 has involuntarily removed CSC Monitor DQM output while trying to reduce the memory footprint of DQM harvesting by switching off apparently not crucial muon POG output. This PR simply restores the previous situation to prevent the loss of CSC information, while preparing a better alternative solution

#### PR validation:

Trivial revert to the previous situation of the affected sequences.

### CODE REVIEW

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
urgent

**Comment by fabiocos** [comment]
type bugfix

**Comment by fabiocos** [comment]
The failed unit test fails also in the IB since CMSSW_14_2_X_2024-10-09-2300, the problem appears to be independent on this PR

**Comment by iarspider** [comment]
@cmsbuild ignore tests-rejected with ib-failure

**Comment by antoniovagnerini** [comment]
+1

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
