### PR TITLE
Switching on CSV+SL tagger using new GT

### PR DESCRIPTION
**Pull request by pvmulder**
This PR relies on #7692. Now that the new GT are made available, a new b-tagger can be switched on without crashing the reco sequence, this was also discussed in the merged #7542. 
Note that the change in PhysicsTools/PatAlgos/python/producersLayer1/jetProducer_cfi.py will be crashing some of the PAT tests, because the new tagger is not yet included in the RelVals (a similar issue was discussed in #7678).

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
this has the same problem as #7678
the PAT change will have to happen after the products are made and validated in relval

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
for https://github.com/cms-sw/cmssw/pull/7697	1357304

the tagger shows up  and the producer is OK from technical performance point of view (CPU, event size is small (180 bytes after compression on 100 events).

The decision is pending understanding of the PF-related content in #7692 (merged in here)

**Comment by monttj** [comment]
+1
There is no significant impact on the PAT sequence.

**Comment by slava77** [comment]
+1

based mostly on the discussion in #7692 
and the conclusions on just the btagging changes in this PR (above, at https://github.com/cms-sw/cmssw/pull/7697#issuecomment-74201218)

**Comment by diguida** [comment]
@pvmulder I have cherry-picked your commits in #7332 so that now we have a PR with all the features for the new GT in.

**Comment by diguida** [comment]
-1
Superseded by #7732

**Comment by pvmulder** [comment]
merged in 74X in #7732

**Pull request closed without merging**
