### PR TITLE
clang check modernize-redundant-void-arg

### PR DESCRIPTION
**Pull request by davidlange6**
for comment about what clang-tidy does to CMSSW (and likely big and not mergeable - this is what clang-tidy check modernize-redundant-void-arg does on the tip of CMSSW_9_3_X as of a few days ago

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by slava77** [comment]
-1

https://clang.llvm.org/extra/clang-tidy/checks/modernize-redundant-void-arg.html looks good to use, but there are failure modes, apparently

**Comment by ianna** [comment]
+1 

however, it would be nice to keep consistent no space between ()

**Comment by dmitrijus** [comment]
+1

**Pull request closed without merging**
