### PR TITLE
Add a safety check to  L1TGlobalUtil and  L1TGlobalSummary

### PR DESCRIPTION
**Pull request by fwyzard**
This fixes the segmentation fault that happens if an unrelated error prevents the `L1TGlobalSummary` from analysing any events.
When that happens, the `L1TGlobalUtil` never reads the `EventSetup` and is left partly unconfigured, leading to a crash when `L1TGlobalSummary` attempts to print the summary.
The fix is to check the validity of the `L1TGlobalUtil` before reading its contents.

### CODE REVIEW

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by fabiocos** [comment]
@nsmith-, @thomreis, @rekovic could you please have a look? It could be helpful to get it into pre4, if possible

**Comment by thomreis** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
