### PR TITLE
[DQM] Bin by bin normalization off by default

### PR DESCRIPTION
**Pull request by andrius-k**
#### PR description:

Normalization is now off by default in the DQM GUI when exploring bin by bin tool results in an overlay view.

#### PR validation:

PR was validated locally.

### CODE REVIEW

**Comment by andrius-k** [comment]
please test

**Comment by jfernan2** [comment]
This PR is fixing this issue: https://github.com/cms-sw/cmssw/pull/28442#issuecomment-564641967

**Comment by andrius-k** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Comment by smuzaffar** [comment]
@andrius-k , I am testing https://github.com/cms-sw/cmsdist/pull/5537 and noticed that this test does not run under python3 (CMSSW_11_1_PY3_X IBs). Please see the errors here
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_11_1_PY3_X_2020-02-10-2300+1e2753/35036/dqmBinByBinLog.log

Can you please provide a fix for python3?

**Comment by andrius-k** [comment]
@smuzaffar Thanks for spotting this. visDQMUpload is not compatible with python3 - I will fix this.

**Comment by andrius-k** [comment]
Hi @smuzaffar,
I ported visDQMUpload to work also on python3: https://github.com/cms-sw/cmssw/pull/28970
Regards,
Andrius

**Pull request merged**
