### PR TITLE
Replace Geometry_cff with GeometryDB_cff in RecoLocalMuon

### PR DESCRIPTION
**Pull request by jeongeun**
**PR description:**
Review on the Reco part of https://github.com/cms-sw/cmssw/issues/31113

`process.load("Configuration.StandardSequences.Geometry_cff")`
 was outdated https://github.com/cms-sw/cmssw/pull/8810 
It should be replaced with
`process.load("Configuration.StandardSequences.GeometryDB_cff")`

In this PR, RecoLocalMuon configuration files (12 files) are fixed.
```
        modified:   RecoLocalMuon/CSCRecHitD/test/run_on_raw.py
        modified:   RecoLocalMuon/CSCRecHitD/test/run_on_raw_72x.py
        modified:   RecoLocalMuon/CSCRecHitD/test/run_on_simdigi.py
        modified:   RecoLocalMuon/CSCRecHitD/test/test_bad_channels.py
        modified:   RecoLocalMuon/CSCSegment/test/run_on_raw_700.py
        modified:   RecoLocalMuon/CSCSegment/test/run_on_raw_720p3.py
        modified:   RecoLocalMuon/CSCSegment/test/run_on_raw_74x.py
        modified:   RecoLocalMuon/CSCSegment/test/run_on_simdigi.py
        modified:   RecoLocalMuon/CSCSegment/test/run_on_simdigi_74x.py
        modified:   RecoLocalMuon/CSCSegment/test/run_on_simdigi_st.py
        modified:   RecoLocalMuon/CSCValidation/test/CSCVal_example_cfg.py
        modified:   RecoLocalMuon/CSCValidation/test/cscv_RAW.py
```
#### PR validation:
Tested in CMSSW_12_5_X, the basic test all passed in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by clacaputo** [comment]
+reconstruction

- technical PR
- no reco changes

**Comment by perrotta** [comment]
@jeongeun @clacaputo could you please take into account (i.e. either fix further or answer somehow) the [comment](https://github.com/cms-sw/cmssw/pull/38552#issuecomment-1174828099) of @tvami in the sibling PR 38852?

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
assign alca

**Comment by qliphy** [comment]
+1

**Pull request merged**
