### PR TITLE
Switch 75X RelVals to HLT development menus

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
Switch 75X RelVals to HLT development menus (cf #8639)
(In 74X, RelVals stay with the frozen HLT menus).

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
