### PR TITLE
Template PFTowers to run on packedCandidates

### PR DESCRIPTION
**Pull request by mandrenguyen**
#### PR description:

PFTowers is templated to run with input pat::packedCandidate, instead of just reco::PFCandidate.
This allows us to rerun the full heavy-ion jet clustering sequence on miniAOD.
In the re-miniAOD workflows (158.01 and 140.5611 in the RelVal matrix) both the PFCandidates and packedPFCandidates are present. 
This PR switches the input to the packed candidates such that this input is tested.

#### PR validation:

Tested on 158.01

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

No backport is foreseen

### CODE REVIEW

**Review by jpata — COMMENTED** [review]
sorry for the delay in comments.

**Comment by jpata** [comment]
I suppose it must be, although just by the look of the error message, it looks like a more serious crash

https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-0fbd37/20019/runTheMatrixINPUT-results/138.3_RunMinimumBias2021Splash+RunMinimumBias2021Splash+RECODR3Splash+HARVESTDR3/step2_RunMinimumBias2021Splash+RunMinimumBias2021Splash+RECODR3Splash+HARVESTDR3.log

```
A fatal system signal has occurred: external termination request
The following is the call stack containing the origin of the signal.



A fatal system signal has occurred: external termination request
The following is the call stack containing the origin of the signal.



Waiting for stacktrace completion failed: timed out waiting for GDB to complete.

Waiting for stacktrace completion failed: 
timed out waiting for GDB to complete.

Current Modules:

Current Modules:

Module: non-CMSSW (crashed)

A fatal system signal has occurred: external termination request

Module: EcalHaloDataProducer:EcalHaloData (crashed)

A fatal system signal has occurred: external termination request

```

**Comment by jpata** [comment]
@cmsbuild please test

**Comment by jpata** [comment]
+reconstruction
- modifies the HI jets in MiniAOD to run on PackedPFTowers
- changes expected/observed in the HI reminiaod workflows, we think this is due to the reduced precision of the packed candidates
- no other unexpected changes

**Comment by perrotta** [comment]
+1

**Pull request merged**
