### PR TITLE
Run3-gex29 Restore the older dd4hep algo for preshower

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Restore the older dd4hep algo for preshower

#### PR validation:

Tried with all cfg's for in SimG4Core/Configuration/test

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by cvuosalo** [comment]
Do I understand correctly that this PR is a temporary fix until the DD4hep team fixes the bug with assemblies?

**Comment by bsunanda** [comment]
I am not sure if this will stay or not. The new code can help to debug dd4hep. We have to validate that later on. This description may be very similar to ddd part. We have to think more if this has a small or larger life time

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by ianna** [comment]
+1

a general cleanup can be addressed later

**Comment by ianna** [comment]
urgent

**Comment by qliphy** [comment]
+1

**Pull request merged**
