### PR TITLE
Back-port of 3 EMTF PRs to CMSSW_10_1_X

### PR DESCRIPTION
**Pull request by abrinke1**
Back-port of EMTF PRs #22820 , #22839 , and #23109 , in particular for use in data-emulator comparisons in Online DQM.

### CODE REVIEW

**Comment by thomreis** [comment]
please test

**Comment by thomreis** [comment]
backport of #23109

**Comment by thomreis** [comment]
@abrinke1 please add this PR to the DQM tag collector twiki and ask for deployment at p5 as well.

**Comment by rekovic** [comment]
+1

**Comment by fabiocos** [comment]
@abrinke1 @rekovic @thomreis this PR:

1) modifies DataFormats, although as far as I can see they are transient ones 

2) modifies the emulator output compared to what is currently being used in the 101X MC campaign 

Could you please confirm these two points? 1) should not be a problem, if the format is transient. But if 2) is true, this breaks the MC production campaign consistency

**Comment by rekovic** [comment]
@fabiocos 

The only essential DataFormat changes that I see are a in EMTFHit.h class, 
which is caused by the removal of a few private member variables:

from
https://github.com/cms-sw/cmssw/pull/23277/files#diff-4045d9263367367fc4bb0c1688fde5f5L178
to
https://github.com/cms-sw/cmssw/pull/23277/files#diff-4045d9263367367fc4bb0c1688fde5f5L183

The rest of the changes in this DataFormat and others are either added new members, or changes in setters and accessors, which should be OK from the perspective of backwards compatibility. 

So, maybe the easiest thing is to simply put back the removed members in the EMTFHit.h and assign to them a trivial value in constructor, and forget about them. That way the DataFormats are considered to be unchanged. 

Otherwise, the answer to your questions is
- EMTFHit is a transient  DataFormat and was not used in downstream L1T simulation steps.

**Comment by rekovic** [comment]
attn @jiafulow

**Comment by abrinke1** [comment]
@fabiocos , @rekovic ,

1) This DataFormat is transient.  It is only used by the EMTF DQM, and the removed private members (DetId's) are not even used by the DQM.  I would not call this an "essential DataFormat change", and I don't see any reason to leave it in as a  dummy / unused quantity.

2) The changes to the track-building are almost negligible from the efficiency point-of-view.  In any case, does the MC processing campaign pick up every PR as it goes into 10_1_X?  If so, I can just change some values in simEmtfDigis_cfi.py so that the default emulation is with the 2017 algo, which is what the pre-PR emulator used.  Just let me know what you prefer.

Cheers,
Andrew

**Comment by fabiocos** [comment]
@rekovic @abrinke1 thank you for the detailed discussion. Indeed the MC campaign could use the updated version of the release for new samples, so backward compatibility is important both from the technical and from the physics point of view (as for instance discussed for #23118)

**Comment by rekovic** [comment]
@fabiocos 
I think what @abrinke1 is saying is that this DataFormat is not saved in any data tier and therefore can be re-written, arguing for merging this PR as is.

**Comment by abrinke1** [comment]
For concern (1), @rekovic is correct - I would argue it is OK as-is.  For the track-building (2), I have just committed a change to use the 2017 track-building as the default emulation, i.e. identical to the before-PR algorithm.

**Comment by thomreis** [comment]
Now this PR differs from the master PR.

**Comment by abrinke1** [comment]
True.  I understood that this was the request.  It doesn't make any sense to have the default EMTF configuration for 10_2_X MC set to 2017 emulation ...

**Comment by rekovic** [comment]
+1

**Comment by jfernan2** [comment]
Successfully tested and integrated in the Online DQM at P5. https://twiki.cern.ch/twiki/bin/viewauth/CMS/DQMP5TagCollector
Merged in master

**Comment by fabiocos** [comment]
@abrinke1 @thomreis @rekovic at this point I would like to merge this PR into CMSSW_10_1_7, where also the HLT menu will be update, breaking the compatibility. Does it makes sense to keep the last update to keep compatibility with the earlier situation at this point? I understand that the changes are minor anyway.

**Pull request merged**
