### PR TITLE
[GEM] GEMAMC13 DataFormats bugfix

### PR DESCRIPTION
**Pull request by jshlee**
#### PR description:
- in GEMAMC13, orbitNumber() fixed to return uint32_t instead of uint16_t
- in GEMAMCStatus, orbitNumber comparison between amc13 and amc limited to uint16_t
- no changes expected.

#### PR validation:
tested with wf 34611.0, 11611.0

### CODE REVIEW

**Comment by jshlee** [comment]
please test

**Comment by perrotta** [comment]
please test
(5 days to generate a comparison summary seems too much...)

**Comment by srimanob** [comment]
type bug-fix

**Comment by srimanob** [comment]
+Upgrade

Bug fix PR on type of variable. PR test runs fine, and no change is seen (as expected).

**Comment by civanch** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
