### PR TITLE
add decay file for BPH

### PR DESCRIPTION
**Pull request by heppye**
add decay file for BPH

### CODE REVIEW

**Comment by covarell** [comment]
What is the need for the new .pdl file?

**Comment by heppye** [comment]
this pdl is for analysis of new resonance search via Lambdab decay. The requests are  BPH-Summer12-00201/00202/00203. Since the lifetime of lambdab needs to be udpated, changing 'Particle' in evtgen decay file does not work. I have checked the evtgen code and also confirmed with current evtgen interface developer that it might be the way to make the property change. Please let me know if you have any further suggestions. Thanks, Ye

**Comment by covarell** [comment]
+1

**Comment by covarell** [comment]
I hope you realize that when you add these decay files *only* to 53X, they will all be lost in the master development release (which currently is 81X) so you cannot use them anymore at 13 TeV... This happened already a few times, so I am wondering...

**Comment by heppye** [comment]
thanks for the reminder. This PR is prepared in a kind of rush especially for the exceptional BPH RunI HPA. Ok, I will make another PR to 81X later for further usage. Thanks, Ye.

**Comment by covarell** [comment]
Ok! Please in general have a look that the repositories of 53X, 71X and 81X contain the same files. If not, you can make global PRs for back- (forward-)porting all the missing ones (not one by one, please)

**Comment by heppye** [comment]
ok.

**Comment by inugent** [comment]
Please remove me from this thread. I am no longer on cms.

**Comment by davidlange6** [comment]
+1
@smuzaffar - could you remove @inugent from the list of people that opted-in to getting notifications from cmsbot? Thanks!

**Comment by smuzaffar** [comment]
@davidlange6 , done https://github.com/cms-sw/cms-bot/commit/f99c42ca8bae56b2a44a548062d421a876c6c74f

**Pull request merged**
