### PR TITLE
MTD geometry: add final proposed scenario (flat bars along phi) D38, fix the BTLDetId ieta navigation method [10_4_X backport of 25572]

### PR DESCRIPTION
**Pull request by fabiocos**
Final MTD scenario for TDR D38 (flat bars along phi)
Fix the ieta BTLDetId navigation method for negative side

(cherry picked from commit ff45d0e76a599b2b5847faf50eb055af9234c3e8)

Restore constexpr in BTLDetId accidentally removed

(cherry picked from commit 780be3d5e7688177a38575ca438a3cbc84061a48)

update crystal thicknesses according to T. Tabarelli's infos

(cherry picked from commit b0ad448c46efef792af2871acbb442d737f8620f)

Update README.md

(cherry picked from commit 95b688c32169a7c899f827ee79a943d7e8b2514e)

backport #25572

### CODE REVIEW

**Comment by fabiocos** [comment]
code-checks

**Comment by fabiocos** [comment]
backport #25572

**Comment by fabiocos** [comment]
please test workflow 27434.0,27834.0

**Comment by kpedro88** [comment]
+upgrade
@fabiocos will #25639 also be backported?

**Comment by fabiocos** [comment]
+operations

**Comment by fabiocos** [comment]
@kpedro88 after this is merged I will push the other backport

**Comment by fabiocos** [comment]
@cvuosalo @ianna @civanch @prebello @zhenhu this PR is the exact backport of what you have already approved in master, I move forward with the integration in order to prevent crashes by all the other depending PRs. Please sign it anyway for future reference

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Pull request merged**
