### PR TITLE
HLT menu development for `13_0_X` (2/N)

### PR DESCRIPTION
**Pull request by missirol**
backport of #40790

#### PR description:

Development of HLT menus for `CMSSW_13_0_X`.

This PR includes the integration of the following JIRA tickets.

  - [CMSHLT-2592](https://its.cern.ch/jira/browse/CMSHLT-2592): [TSG] removal of deprecated GRun Paths post Run2022 (combined table unchanged)
  - [CMSHLT-2593](https://its.cern.ch/jira/browse/CMSHLT-2593): [TSG] remove unused Paths from HLT combined menu (post Run2022)
  - [CMSHLT-2596](https://its.cern.ch/jira/browse/CMSHLT-2596): [TSG] split EGamma,JetMET,Muon datasets and streams by 2
  - [CMSHLT-2605](https://its.cern.ch/jira/browse/CMSHLT-2605): [GEM] extend RPCMON stream to GEM
  - [CMSHLT-2607](https://its.cern.ch/jira/browse/CMSHLT-2607): [PPS] extend list of CT-PPS FEDs
  - [CMSHLT-2613](https://its.cern.ch/jira/browse/CMSHLT-2613): [EGM] added two MC_Egamma_Open Paths (only to combined table)
  - [CMSHLT-2633](https://its.cern.ch/jira/browse/CMSHLT-2633): [EXO] update of displaced Photon+PFHT trigger and addition of backups

It also includes the migration of the HLT menus ("Fake*", frozen, and development ones) to the `ConfDB` template for `CMSSW_13_0_0_pre4`.

#### PR validation:

TSG tests.

#### If this PR is a backport, please specify the original PR and why you need to backport that PR. If this PR will be backported, please specify to which release cycle the backport is meant for:

#40790

Development of HLT menus for 2023 data-taking and Run-3 MC.

### CODE REVIEW

**Comment by missirol** [comment]
enable gpu

**Comment by missirol** [comment]
please test

**Comment by missirol** [comment]
please test

The RelVals-INPUT error is not a time-out. It's probably transient and unrelated to these HLT changes, but to be extra-safe the tests are restarted.

**Comment by missirol** [comment]
+hlt
 - changes in the outputs of PR tests are in line with updates to the HLT GRun menu, and the change in name of the frozen/fake HLT menus

**Comment by rappoccio** [comment]
+1

**Comment by missirol** [comment]
@rappoccio , maybe this merge was a bit quick, but I don't expect any issues (so no further action needed, imho).

This kind of HLT backport is usually merged after we see no problems in the `master` IB (in this case, `CMSSW_13_1_X_2023-02-17-1100` which includes #40790 and is still running).

**Pull request merged**
