### PR TITLE
Add particle list files and update decay file for BPH(Bmm)

### PR DESCRIPTION
**Pull request by heppye**
Add particle list files and update decay file for BPH(Bmm)

### CODE REVIEW

**Comment by covarell** [comment]
+1

**Comment by covarell** [comment]
+1

**Comment by davidlange6** [comment]
@heppye - how do the two pdl files differ?

**Comment by heppye** [comment]
@davidlange6 , the difference is about bs lifetime (line295 and line439). 'evt_Bsmm.pdl' use the lifetime of heavy Bs state. This setting is implemented by the Bmm analysis team.

**Comment by heppye** [comment]
reference papers provided by the initial requesters.  PRL, 109, 041801; PR, D86, 014027  and
hep-ph/0012129 (PR, D63, 114015).

**Comment by davidlange6** [comment]
I believe there is a way to change the lifetime in the dec file - is that not the case? @heppye

**Comment by heppye** [comment]
@davidlange6 , yes. But not sure whether this feature has been fully validated in the current evtGenInterface. Will contact the current developer and perform local test. May the CMSSW_7_1_X PR https://github.com/cms-sw/cmssw/pull/12686 been merged first if possible.

**Comment by davidlange6** [comment]
@heppye - any news on this? I can't think why this feature would be affected by the CMS interface.

**Comment by heppye** [comment]
@davidlange6 , sorry for my late response. not having a time to test the feature being suggested yet. Will mark it to the working list and discuss with current evtgen interface developer.

**Comment by davidlange6** [comment]
@heppye - then I'll close this PR and you can open a new one when the question is resolved. Thanks!

**Comment by heppye** [comment]
@davidlange6 ok. thanks. Sorry for the delay.

**Pull request closed without merging**
