### PR TITLE
Fix gcc9 warnings Alignment/MillePedeAlignmentAlgorithm

### PR DESCRIPTION
**Pull request by mrodozov**
#### PR description:

Fix gcc9 warnings in Alignment/MillePedeAlignmentAlgorithm

#### PR validation:

Builds and doesn't complain with warnings. Intentionally left the empty cases untouched (didn't remove them) since the author left comments for future filling of that cases

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test

**Comment by pohsun** [comment]
+1

**Pull request merged**
