### PR TITLE
[12_2_X] Modernize `DQM/BeamMonitor/plugins/TKStatus` plugin

### PR DESCRIPTION
**Pull request by francescobrivio**
#### PR description:
Backport of #37214 to 12_2_X
Modernize the `DQM/BeamMonitor/plugins/TKStatus` plugin to use `DCSRecord` token in case the DCS information from SCAL is not available (i.e. from Run3 onwards).

#### PR validation:
Code compiles + see tests in master PR.
@cms-sw/dqm-l2 This backport should be tested online at P5.

#### Backport:
Backport of #37214

### CODE REVIEW

**Comment by francescobrivio** [comment]
backport of #37214

**Comment by francescobrivio** [comment]
@cmsbuild please test

**Comment by jfernan2** [comment]
Since this PR is potentially affecting Online DQM, I'd like to test it at P5 before signing

**Comment by francescobrivio** [comment]
> Since this PR is potentially affecting Online DQM, I'd like to test it at P5 before signing

thanks @jfernan2 I agree!

**Comment by jfernan2** [comment]
+1
Tested successfully in Online DQM at P5 (no crashes).

**Comment by qliphy** [comment]
+1

**Pull request merged**
