### PR TITLE
bug fixes in CSC (ME11) trigger primitives for re-emulation; fix ME11 selective readout

### PR DESCRIPTION
**Pull request by slava77**
This is supposed to address issues with running CSC (ME11 part) emulator on run2 data (currently broken for ME11a) and for re-emulation applications of run2 MC (currently possible from sim digis, but appears to be less convenient than done from RAW).
Additionally, the selective readout for run2 MC was fixed (currently the CSC selective readout emulation is disabled in run2 MC; everything is saved.)
- extend CLCT processor to cover 7 CFEBs (that's how OTMB works now), this is for current data
- pick up correct ranges for smartME11ab case for the (MC only at this point) SLHC algorithm
- updated CLCT processor to also correctly read comparators on MC inputs if configured with unganged ME1a for "current" TMB algorithm (that's what we have in current OTMB firmware now)
- fix CSCTriggerPrimitivesReader (minor, input names got mixed up after getByLabel -> getByToken conversion done last year)
- added a shift of 4 CFEBs or 128 halfstrips for packed CLCTs and LCTs coming from ME1a (see notes below), they show up in SLHC-OTMB MC algorithm only. [this is the only change that affects output of Run2 MC "standard" workflows; note though that the unpacked LCTs and CLCTs are not really used, other than in the limited set of DQM and non-standard validation; if fixes in 74X are no longer possible, we can take this out and live with the ambiguous packing]
- fixed ME1A pretrigger filling in MC by the CSCTriggerPrimitivesBuilder
- made the packer aware of pretriggers and ALCTs showing up in ME1A detid with the SLHC-OTMB algorithm (this should make it possible to correctly emulate selective readout during packing; disabled for run2 MC)

An equivalent of this PR will be made for 74X and 75X.
This is an initial submission to review with corresponding experts.

Changes show up only Run2 MC "standard" DQM plots like this (me1/1a occupancies are present); there are no changes in regular reco or HLT objects.
wf1320_hostripsandwiresandclct

### CODE REVIEW

**Comment by slava77** [comment]
@ptcox @barvic @valuev

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by Martin-Grunewald** [comment]
@slava77 
What is the status here, and for 74X/75X?

**Comment by mulhearn** [comment]
+1

**Comment by slava77** [comment]
Martin, on a technical side, I will submit equivalent PRs in 74X/75X.
I was expecting feedback from CSC experts (some discussion ongoing in a private thread since after the PR submission) before going with PRs in other release branches so that I don't have to follow up with fixes in 2-3 branches.

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/8664	48d7652
tested in CMSSW_7_3_5 /test area csc-me11A-emulator/
the summary is in the subject of the PR.
jenkins tests confirm expected set of changes only in the ME11 trigger primitives plots in run2 MC, now showing up appropriately in A and B parts of the chamber.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
