### PR TITLE
[DQM] Fix to compareDQMOutput since python3

### PR DESCRIPTION
**Pull request by jfernan2**
#### PR description:

Bin By Bin tool broken since python3 change 
As pointed out in https://github.com/cms-sw/cmssw/pull/34374#issuecomment-876617338

### CODE REVIEW

**Comment by jfernan2** [comment]
urgent

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by srimanob** [comment]
@qliphy @perrotta @silviodonato @jfernan2 
I see that 12_0_0_pre4 is built already.

Do you think that this PR is needed when PdmV try to make a comparison using relmon?

**Comment by jfernan2** [comment]
Hi @srimanob 
This PR affects only the DQM Bin By Bin tool, not RelMon

**Comment by silviodonato** [comment]
+1
Thanks @jfernan2 and @srimanob . Indeed I see that this code was added with https://github.com/cms-sw/cmssw/pull/26283 and it seems independent on RelMon

**Comment by silviodonato** [comment]
@jfernan2 I still see 
```
Exception comparing two root files: a bytes-like object is required, not 'str'
```
See `dqmBinByBinLog.log` in https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_0_X_2021-07-08-1100+152b8c/43938/

Do you think we will see this fixed only *after* the merge of the PR?

**Comment by smuzaffar** [comment]
@silviodonato , yes it should be fixed once we have a newer IB with the fix. I already have started 8h00 Ib

**Comment by jfernan2** [comment]
I confirm, thanks @smuzaffar

**Comment by smuzaffar** [comment]
@jfernan2 , looks like we still need more fixes fir dqm bin by bin test. Looks like it managed to upload the result but failed ot generate the html pages , see https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_0_X_2021-07-09-1100+5c6882/43968/dqmBinByBinLog.log 
```
No differences were observed - output will not be written
Baseline file successfully opened
PR file successfully opened
No differences were observed - output will not be written
No differences were observed - output will not be written

Exception comparing two root files: list index out of range
Exception comparing two root files: list index out of range
Exception comparing two root files: list index out of range
```

**Comment by jfernan2** [comment]
I have created https://github.com/cms-sw/cmssw/pull/34442 to fix the issue.
Thanks fro the warning!

**Pull request merged**
