### PR TITLE
Added functionality to TrackHistory.cc(.h) to get matched TrackingParticle to the Track

### PR DESCRIPTION
**Pull request by smoortga**
This change introduces the possibility to access the matched TrackingParticle to the Track whenever the TrackHistory::Evaluate() function is used. This allows the user to investigate the properties of the truth-track (i.e. the TrackingParticle) of which the history is being calculated with this code. 

This functionality is needed in the BTV group to easily monitor possible differences between reco-quantities and truth-level information form tracks of different origins (BWeakDecays, CWeakDecays, ...)

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
Hi @smoortga - please use lower case letters to start both variable names and function names

Second, what is the memory impact of this change?

**Comment by smoortga** [comment]
hi @davidlange6,

I updated the naming conventions.

I think the memory impact is rather modest. Typically when using the TrackHistory code, the user will define 1 instance of a TrackHistory object (or more specifically a TrackClassifier object which has a TrackHistory member), and the TrackHistory::evaluate() will be called on every track the user is iterating over. So after each such an evaluate, the object now has one more member object to save (the TrackingParticle I added in this PR), but it will be overwritten each time the evaluate function is called again.

This change will not add new collections to AOD/miniAOD files, so in that sense it will not increase the data storage needed when producing MC samples.

Hope this helps, but please let me know if you have more concerns on the memory impact.

Cheers,
Seth

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
