### PR TITLE
[12_2_X backport] fix in bc->e filter 

### PR DESCRIPTION
**Pull request by swagata87**
#### PR description:

See details in PR description of https://github.com/cms-sw/cmssw/pull/37869
This is an exact backport of 37869. 
The backport is being made following a discussion in today's PPD meeting, during this talk:
https://indico.cern.ch/event/1158486/#30-retraining-of-pf-electron-i
The plan is that once this backport PR is merged and a new 12_2_X release is made, EGM will request QCD b/c->e samples again, in 12_2_X. With those samples, we will check the performance of DNN-based PF ID.

### CODE REVIEW

**Comment by swagata87** [comment]
backport of https://github.com/cms-sw/cmssw/pull/37869

**Comment by SiewYan** [comment]
please test

**Comment by SiewYan** [comment]
@Saptaparna , @GurpreetSinghChahal

**Comment by swagata87** [comment]
Hi generator experts, 
is there anything else needed from our side about this PR?

**Comment by Saptaparna** [comment]
+1

**Comment by qliphy** [comment]
+1

**Comment by qliphy** [comment]
@swagata87  CMSSW_12_2_4 is now ready: https://github.com/cms-sw/cmssw/releases/CMSSW_12_2_4

**Comment by swagata87** [comment]
> @swagata87 CMSSW_12_2_4 is now ready: https://github.com/cms-sw/cmssw/releases/CMSSW_12_2_4

Many thanks Qiang and Andrea. 
This will be really helpful for our PF ID studies.

**Pull request merged**
