### PR TITLE
Run3-gex176E Update the rpc geometry description for 2024 scenario

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Update the RPC geometry description for the 2024 scenario

#### PR validation:

Use the overlap checking tool

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

To be backported to CMSSW_14_0_X using #44094

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by saumyaphor4252** [comment]
urgent

**Comment by saumyaphor4252** [comment]
FYI @cms-sw/alca-l2

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
+geometry

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
+geometry

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
