### PR TITLE
Fix MonitorElement exception in L1TTau offline DQM. - 92x

### PR DESCRIPTION
**Pull request by thomreis**
backport of #20156

### CODE REVIEW

**Comment by rekovic** [comment]
please test

**Comment by rekovic** [comment]
@thomreis 
Originally merged  Tau DQM Offline PR (#20043) been reverted in 92x, by a recent PR https://github.com/cms-sw/cmssw/pull/20168

@davidlange6 
I imagine that you would like a combo fixed version PR, i.e original PR + this PR, showing that it
passes the previously observed crashes.

**Comment by thomreis** [comment]
@rekovic yes I saw it in 9_2_9_patch1. Now this PR has a conflict. What best to do about this?

**Comment by thomreis** [comment]
Superseded by #20174

**Pull request closed without merging**
