### PR TITLE
Adding 2021 scripts to CondTools/Geometry 

### PR DESCRIPTION
**Pull request by AramayisPetrosyan**
PR description:

adding 2021 scripts (based on 2019 ones) to the test directory
CondTools/Geometry/test/writehelpers
per request of Ianna Osborne @ianna
PR validation:

runTheMatrix.py -s is OK
if this PR is a backport please specify the original PR:

No need for backporting.

It's a resubmission with updates of closed PR
https://github.com/cms-sw/cmssw/pull/27693

### CODE REVIEW

**Comment by abdoulline** [comment]
Please, copy the (meaningful) title from closed PR.

**Comment by ianna** [comment]
please test

**Comment by abdoulline** [comment]
@ggovi   
Giacomo, could you take a look, please?

**Comment by ggovi** [comment]
+1

**Comment by kpedro88** [comment]
assign geometry

**Comment by abdoulline** [comment]
@cvuosalo, @ianna 
May I kindly draw your attention to this PR?

**Comment by ianna** [comment]
+1

**Pull request merged**
