### PR TITLE
Added MinimizeSourceAndOutputTime

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

Replaces PoolSource and PoolOutputModule with dummy version that run faster and do not require as much memory. Useful for fast validating jobs.

#### PR validation:

Tested by importing into a step3 configuration and applying the customize function.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
ping @cms-sw/core-l2

**Comment by makortel** [comment]
Comparison differences are related to https://github.com/cms-sw/cmssw/issues/46416

**Comment by makortel** [comment]
+core

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
