### PR TITLE
Move division by 2 to match ngHE uhtr firmware

### PR DESCRIPTION
**Pull request by christopheralanwest**
Backport #18635

### CODE REVIEW

**Comment by fwyzard** [comment]
@mtosi can you please pick this up, when you prepare the next L1 skims ?

**Comment by fwyzard** [comment]
please test

**Comment by mtosi** [comment]
I'm taking note of this PR, thank @fwyzard  for pointing it !
will it be added to STORM instructions as well ?
@Martin-Grunewald @silviodonato can you comment, please ?

thanks !

**Comment by fwyzard** [comment]
> will it be added to STORM instructions as well ?

I guess we can add it.

**Comment by rekovic** [comment]
+1

**Comment by Martin-Grunewald** [comment]
Added to STORM recipe...

**Comment by davidlange6** [comment]
Closing PR. CMSSW_9_1_X is for muon TDR upgrade changes only (CMSSW_9_2_X for data taking)

**Pull request closed without merging**
