### PR TITLE
[132X] Fix upper bound of the scale in SUEP shower simulation

### PR DESCRIPTION
**Pull request by tvami**
#### PR description:

See https://github.com/cms-sw/cmssw/pull/43165
please note that there is no need for a customization because this only affects the SUEP simulations, and there were no officially done SUEP samples done for UL (nor any other campaigns)

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

backport of https://github.com/cms-sw/cmssw/pull/43165

### CODE REVIEW

**Comment by tvami** [comment]
backport of https://github.com/cms-sw/cmssw/pull/43165

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
@cmsbuild , please test with https://github.com/cms-sw/cmssw/pull/43187

**Comment by tvami** [comment]
@cmsbuild , please abort

**Comment by tvami** [comment]
@cmsbuild , please test with https://github.com/cms-sw/cmssw/pull/43187

**Comment by menglu21** [comment]
+1

**Comment by rappoccio** [comment]
+1

**Pull request merged**
