### PR TITLE
modify electron track seeding regions for pp_on_AA era

### PR DESCRIPTION
**Pull request by bi-ran**
this PR switches the tracking regions for the pixel pair/triplet and strip pair electron track seeding modules to regions centred on vertices. the ptmin threshold in the seeding regions for all three modules are also raised to 8 GeV. this improves the timing of the stripPairElectronSeeds module by a factor of 6-7, while also slightly improving the efficiency and fake rate. a short set of slides comparing the performance before/after this change can be found at [1].

[[1]]: https://twiki.cern.ch/twiki/pub/CMS/HiEgamma2018/electron-strippair-seeding.pdf

@mandrenguyen

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
> Reco comparison results: 0 differences found in the comparisons

the tests include wf 158.0.
However it has only 1 event.
Is the effect expected to be small at general event level?

**Comment by bi-ran** [comment]
@slava77 yes, changes are expected to be small for min bias events where there are few electrons, since supercluster thresholds are now at 15 GeV.

**Comment by slava77** [comment]
Some observations 
- in "filtered 3000" HI minBias sample of 230 events
    - there are no significant change in electrons/photons
    - there is a fairly significant reduction in CPU use in electron seeding: the combined decrease is about 15 s/event, reducing the production-like job total time to 142 s/evt on 230 events
- Z->ee/mm sample with HI minbias mix ("pyquen" based on what's in wf 302.0 with beam energy 5020 as for this year and with reco using pp_on_AA)
    - about a factor of 2 reduction in electron gsf tracks below pt of 10 GeV (expected)
all_sign1037vsorig_pyquenzeemumujetspprecoin2018wf302p18c_log10recogsftracks_electrongsftracks__reco_obj_pt
    - changes in the reconstructed electrons are fairly small due to the pt threshold
pf electrons:
all_sign1037vsorig_pyquenzeemumujetspprecoin2018wf302p18c_log10recopfcandidates_particleflow__reco_obj_p56
ged electrons
all_sign1037vsorig_pyquenzeemumujetspprecoin2018wf302p18c_recogsfelectrons_gedgsfelectrons__reco_obj_classification

the MTV fake rate plot shows a decrease of about 30% in fakes
wf302 18_gsf_mtv_fr_eta

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/24413	66ef5db
- code changes are in line with the PR description
- jenkins tests pass and comparisons with the baseline show no differences (only 1 event is tested in pp_on_AA workflow)
- local tests show roughly expected behavior with a significant reduction of CPU time spent in electron seeding (which was substantially below the threshold of the electron reco in the baseline).

**Comment by kpedro88** [comment]
+1

**Pull request merged**
