### PR TITLE
Utilities/StaticAnalyzers: Report top level functions calling EventSetupRecord::get

### PR DESCRIPTION
**Pull request by gartung**

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by gartung** [comment]
test

**Comment by gartung** [comment]
please test

**Comment by gartung** [comment]
please test

**Comment by gartung** [comment]
please test

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
@smuzaffar Do you have any thoughts on storing `Utilities/StaticAnalyzers/scripts/modules_in_ib.txt.gz` in `cmssw` git? It's only 12 kB, but it is  needed only for a limited time. (the information is from full runTheMatrix so in principle it's even duplicate information packaged conveniently)

**Comment by makortel** [comment]
@gartung 

> `Utilities/StaticAnalyzers/scripts/modules_in_ib.txt.gz` 

The file should be placed in some other directory than `scripts` (`data` ?) to avoid it getting copied into the `bin` directory of the release. But before moving it let's wait for @smuzaffar to comment first if the file is ok to be placed in `cmssw`.

**Comment by gartung** [comment]
bloom.bin is also a binary file of similar size.

**Comment by smuzaffar** [comment]
@gartung are you planing to update this modules_in_ib.txt.gz very frequently ( e.g. weekly bases) to reflects the latest state of modules in IBs? If yes then I would suggest to save it in text form. 
@makortel , scram does not copy non-executable files to bin directory so it does not hurt to keep it in scripts directory but yes do these type of data files they should go in data directory

**Comment by makortel** [comment]
@smuzaffar 

> are you planing to update this modules_in_ib.txt.gz very frequently ( e.g. weekly bases) to reflects the latest state of modules in IBs? If yes then I would suggest to save it in text form.

I'm thinking to not update it at all, and remove the filtering (and that file) once all the EDModules in the filtered list have been migrated (within half a year, hopefully). In principle new code should already call EventSetup consumes. If something would nevertheless slip through, I'd expect only few such cases and and address those then.

**Comment by gartung** [comment]
OK. The file is uncompressed. You can squash merge the pr so the binary does not appear in the commit history.

**Comment by smuzaffar** [comment]
thanks @makortel , in  this case  it is ok to keep it in cmssw.
@gartung , can you please force push changes to remove the gz file from history. "Squash merge" is possible but I am afraid @silviodonato , @qliphy might forget to do it. Also cms-bot does not recognize the squash merge auto generated merge message.

**Comment by smuzaffar** [comment]
please test

**Comment by gartung** [comment]
please test

**Comment by makortel** [comment]
+1

DAS errors are already in the IB

**Comment by qliphy** [comment]
+1

**Comment by qliphy** [comment]
merge

**Pull request merged**
