### PR TITLE
Remove last bits of LargeD0 iterations, and add Phase1 iteration enumerators

### PR DESCRIPTION
**Pull request by makortel**
This PR removes the last remnants of LargeD0 iterations (they were partly removed already in #3446, and were confirmed to be obsolete https://hypernews.cern.ch/HyperNews/CMS/get/recoTracking/1583/1.html). Then, as a preparatory step, the `iterNLargeD0` track algorithm enumerators are reused for upcoming new Phase1 tracking iterations (two of them are not needed now, so they're marked as reserved). They are intentionally not yet used (in Phase1PU70 and PU140 configurations), because I want to keep the current state until we have finalized the validation of Phase1 tracking in 80X against 62X_SLHC.

Tested in 800pre2, no changes expected.

@rovere @VinInn

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by VinInn** [comment]
There are, in principle, two PFlow file to modify...
RecoParticleFlow/PFProducer/src/PFElectronAlgo.cc
and
RecoParticleFlow/PFTracking/src/PFDisplacedVertexFinder.cc


I was doing something similar in
https://github.com/cms-sw/cmssw/compare/CMSSW_8_0_X...VinInn:SeedRedux800
that I will align to this changes...

We may thing also to "create" a place holder for the duplicateMerger (in place of rs ?)
What is the plan for HighPtQuadruplet: to use InitialStep?

**Comment by makortel** [comment]
@VinInn Yes, eventually those PF files need to be modified (and also elsewhere where the algo enumerators are used explicitly, I haven't checked yet). I didn't include those here because the new enumerators are not yet used anywhere. I was planning to do the migrations in the same PR I change the current Phase1PU70/140 iterations to set the proper algo (which will have to wait a bit as I wrote in the PR description).

I was indeed thinking to use initialStep for the first (quadruplet-seeded) Phase1 iteration.

**Comment by VinInn** [comment]
@makortel , ok. let's keep the list of the file involved somewhere....

**Comment by makortel** [comment]
The error seems to be
```
/bin/cp: /bin/cp: cannot create regular file `cfipython/slc6_amd64_gcc493/DQM/BeamMonitor/FedRawDataInputSource_cfi.py'cannot create regular file `cfipython/slc6_amd64_gcc493/DQM/BeamMonitor/FedRawDataInputSource_cfi.py': File exists
: File exists
gmake: *** [lib/slc6_amd64_gcc493/AlcaBeamMonitor.edmplugin] Error 1
gmake: *** [lib/slc6_amd64_gcc493/BeamSpotProblemMonitor.edmplugin] Error 1
```
I can't see how this could be caused by this PR.

**Comment by smuzaffar** [comment]
assign dqm
actual issue is that all the plugins generated from DQM/BeamMonitor [a] are generating the same cfi file. So plugin gmake processes trying to copy this file and fail. Actual problem is in 
`https://github.com/cms-sw/cmssw/blob/8912b6fabc351091aedf219db64948df22a1ff85/EventFilter/Utilities/src/FedRawDataInputSource.cc#L1287`
where this shared library is defining a plugin. Thisplugin definition should move to EventFilter/Utilities/plugins


```
AlcaBeamMonitor/edm_write_config/FedRawDataInputSource_cfi.py        BeamMonitor/edm_write_config/FedRawDataInputSource_cfi.py             PixelVTXMonitor/edm_write_config/FedRawDataInputSource_cfi.py
AlcaBeamMonitorClient/edm_write_config/FedRawDataInputSource_cfi.py  BeamMonitorBx/edm_write_config/FedRawDataInputSource_cfi.py           TKStatus/edm_write_config/FedRawDataInputSource_cfi.py
BeamConditionsMonitor/edm_write_config/FedRawDataInputSource_cfi.py  BeamSpotProblemMonitor/edm_write_config/FedRawDataInputSource_cfi.py  Vx3DHLTAnalyzer/edm_write_config/FedRawDataInputSource_cfi.py
```

**Comment by VinInn** [comment]
@cmsbuild, please test

**Comment by VinInn** [comment]
@slava77 , @davidlange6 this is purely technical.
We need it integrated to continue working on this and other iterations
In particular I have to make duplicateMerged an algo by its own, this will produce (apparent) regression.
So better to do it as early as possible...

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/12458	8e86aba
- technical changes only to replace unused iteration enums with phase1 and phase2 placeholders
- jenkins tests pass and comparisons with baseline show no differences as expected

**Comment by davidlange6** [comment]
+1

**Pull request merged**
