### PR TITLE
Use new library name when running edmWriteConfig test

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

A previous pull request changed which plugin library contains the `ProducerWithPSetDesc` plugin. This updates the call to edmWriteConfig in the test to use the proper library.

#### PR validation:

Modification to the test now succeeds.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by smuzaffar** [comment]
+core
@perrotta , unit tests passed and this time `edmWriteConfig` properly generated the cfi's [a]. Feel free to merge it for next IB
[a] https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-597844/30047/unitTests/src/FWCore/Integration/test/TestIntegrationParameterSet/testing.log
```
edmWriteConfigs ------------------------------------------------------------
testProducerWithPsetDesc
testLabel1
producerWithPSetDesc
test
```

**Comment by perrotta** [comment]
+1

**Comment by perrotta** [comment]
merge
- This only touches a unit test, which looks as having been fixed now: there is no reason to wait for the JR comparisons
- Let have this merged in time for the 2300 IB

**Pull request merged**
