### PR TITLE
New fastsim geometry fix, AddOn faliure fix - backport to 94X

### PR DESCRIPTION
**Pull request by ssekmen**
Backports of 
#22202: New FastSim geometry fix
#23019: fixes for AddOn Test Failures

### CODE REVIEW

**Comment by ssekmen** [comment]
please test

**Comment by ssekmen** [comment]
+1

**Comment by fabiocos** [comment]
@ssekmen was this verified to fix the problems observed in 9_4_11_cand1?

**Comment by fabiocos** [comment]
+1

**Comment by ssekmen** [comment]
@fabiocos , I did a test with 4000 events and all was ok (crash was happening around ~2500th event).

**Pull request merged**
