### PR TITLE
Fix compilation warnings in MESet*

### PR DESCRIPTION
**Pull request by iarspider**
#### PR description:

Fix warnings reported [here](https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/el8_amd64_gcc12/CMSSW_13_2_X_2023-07-04-1100/DQM/EcalCommon), e.g.:

```
/data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/de71853a65d857b5c29aa52c2674d8d1/opt/cmssw/el8_amd64_gcc12/cms/cmssw-patch/CMSSW_13_2_X_2023-07-04-1100/src/DQM/EcalCommon/src/MESetBinningUtils.cc: In function 'formAxis':
  /data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/de71853a65d857b5c29aa52c2674d8d1/opt/cmssw/el8_amd64_gcc12/cms/cmssw-patch/CMSSW_13_2_X_2023-07-04-1100/src/DQM/EcalCommon/src/MESetBinningUtils.cc:855:51: warning: argument 1 value '18446744073709551615' exceeds maximum object size 9223372036854775807 [-Walloc-size-larger-than=]
   855 |           axis.labels = new std::string[axis.nbins];
      |                                                   ^
/data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc12/external/gcc/12.3.1-40d504be6370b5a30e3947a6e575ca28/include/c++/12.3.1/new:128:26: note: in a call to allocation function 'operator new []' declared here
  128 | _GLIBCXX_NODISCARD void* operator new[](std::size_t) _GLIBCXX_THROW (std::bad_alloc)
      |                          ^
```

#### PR validation:

Code compiles without warnings

### CODE REVIEW

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
please test

**Comment by emanueleusai** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
