### PR TITLE
Backport: Adding d0 cut to TrackletCalculatorDisplaced.cc 

### PR DESCRIPTION
**Pull request by Jingyan95**
Back porting PR#43014 to 13_1_X

### CODE REVIEW

**Comment by srimanob** [comment]
@cmsbuild please test

**Comment by srimanob** [comment]
@antoniovilela @rappoccio 
This is a PR I mentioned during ORP. When it is merge, I would like to request new 13_1.
Since this PR effects only Phase-2 L1T, I don't think we need it in 13_2. Thanks.

**Comment by epalencia** [comment]
+l1

**Comment by srimanob** [comment]
Backport of https://github.com/cms-sw/cmssw/pull/43014

**Comment by srimanob** [comment]
Hi @Jingyan95 
Thanks for the backport. Could you please fix the Title of PR, to reflect on the update? You can use the same as https://github.com/cms-sw/cmssw/pull/43014, with Backport

**Comment by Jingyan95** [comment]
> Hi @Jingyan95 Thanks for the backport. Could you please fix the Title of PR, to reflect on the update? You can use the same as #43014, with Backport

Done

**Pull request merged**
