### PR TITLE
Fix crashes in edmConfigBrowser

### PR DESCRIPTION
**Pull request by Dr15Jones**
The edmConfigBrowser modifies member functions of standard configuration
python objects. The modification to the cms.Process __init__ was
not general enough to deal with the change of number of allowed
arguments. In addition, the 'replace' modification could not deal
with something being replaced with None.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by Dr15Jones** [comment]
hold
I have some other fixes coming

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by Dr15Jones** [comment]
unhold

**Comment by davidlange6** [comment]
+1

**Pull request merged**
