### PR TITLE
Run2-hcx180 Fix a bug for HcalDetId which affects DQM of calibration channels

### PR DESCRIPTION
**Pull request by bsunanda**
This fix was integrated to 10_2_X master from branch bsunanda:Run2-hcx173

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
@bsunanda , likely you need also back port this fix to 9_3_X (if any effect on SIM step)

**Comment by bsunanda** [comment]
It affects some data related stuff. Mainly for some of the DQM with monitoring data. It will not affect the SIM step

**Comment by bsunanda** [comment]
It affects some data related stuff. Mainly for some of the DQM with monitoring data. It will not affect the SIM step

**Comment by civanch** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
