### PR TITLE
[Phase-2] [backport] Fixed L1 quality mask requirement in L1TkEmSingle51Filter

### PR DESCRIPTION
**Pull request by SohamBhattacharya**
#### PR description:

Backport of https://github.com/cms-sw/cmssw/pull/42896

### CODE REVIEW

**Comment by mmusich** [comment]
type bugfix, egamma

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
+hlt
   * see https://github.com/cms-sw/cmssw/pull/42896#issuecomment-1746214450

**Comment by rappoccio** [comment]
+1

**Pull request merged**
