### PR TITLE
migrate modules used by the HLT menu to multithreading (various) (75x)

### PR DESCRIPTION
**Pull request by fwyzard**
backport #10958 to 75x

### CODE REVIEW

**Comment by fwyzard** [comment]
@cmsbuild please test

**Comment by fwyzard** [comment]
+1

**Comment by fwyzard** [comment]
tracked at #10965

**Comment by mulhearn** [comment]
+1

**Comment by mulhearn** [comment]
Thanks, Andrea.

**Comment by deguio** [comment]
+1

**Comment by ggovi** [comment]
+1

**Pull request merged**
