### PR TITLE
Always set the thread stack size when configuring TBB, even if the number of threads is not specified (10.2.x)

### PR DESCRIPTION
**Pull request by fwyzard**
Set the thread stack size even if the number of threads is not specified on the command line nor in the `process.options` ParameterSet.

### CODE REVIEW

**Comment by fwyzard** [comment]
backport #24054

**Comment by fwyzard** [comment]
bugfix

**Comment by fwyzard** [comment]
@cmsbuild please test

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by Dr15Jones** [comment]
I'd prefer just a cherry pick of #24054 just to keep any future backports to cmsRun consistent between 10_2 and 10_3

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
+1

**Pull request merged**
