### PR TITLE
Moving the Prescale ES producer to the new parser and deleting old XML parser

### PR DESCRIPTION
**Pull request by kkotov**
New XML parser take over everything now. Old one is removed.

### CODE REVIEW

**Comment by rekovic** [comment]
please test

**Comment by kkotov** [comment]
Although I removed the two lines failing the compilation, for some reason I cannot check how it compiles in my local installation of CMSSW_9_1_0_pre3. I see scram warnings:
****WARNING: Invalid tool FWCore/Framework. Please fix src/L1Trigger/L1TMuonBarrel/src/BuildFile.xml file.
and them multiple linking errors complaining on a missing "edm::Exception::throwThis" symbol. I am giving up as it is beyond my expertise and I only hope it'll compile fine here.

**Comment by kkotov** [comment]
@rekovic , could you trigger the tests again, please?

**Comment by rekovic** [comment]
please test

**Comment by kkotov** [comment]
Of course, I can resolve the conflict above and trigger another round of tests, but I don't see this PR is being a priority for anyone. If this is not going to be merged, why bother?

**Comment by Martin-Grunewald** [comment]
@kkotov 
Please raise it at the next TSG meeting...

**Comment by kkotov** [comment]
@Martin-Grunewald , I'll try to ping Vladimir today-tomorrow again. In the end no one from TSG can sign-off this PR.

**Comment by Martin-Grunewald** [comment]
please test

**Comment by kkotov** [comment]
@Martin-Grunewald , Thanks for triggering the tests!

**Comment by rekovic** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
