### PR TITLE
Improve caching of MF geometry across runs

### PR DESCRIPTION
**Pull request by namapane**
#### PR description:

Added a protection to check that the MF geometry cache introduced in #38640 is still valid.
Addresses item 1) in issue #38669.

Also added a test to siumlate a job spanning over several runs with different magnet currents, triggering the cache in different conditions. It can be run with:

`MagneticField/Engine/test/regression.py producerType=fromDB_DD4hep current=-1`

As expected, the cache works when switching among maps with the same geometry (3, 3.5 and 3.8 T; or 0 and 2 T).
When switching between 3 and 2 T, the geometry needs to be redone, which as expected leads to a crash in dd4hep.
This can only be fixed upstream; however, this is a very exotic use case (ie job spanning different runs taken while the magnet was ramping). In any case, the test can be used to keep track of this potential issue.

### CODE REVIEW

**Comment by clacaputo** [comment]
@cmsbuild please test

**Comment by clacaputo** [comment]
> This can only be fixed upstream; however, this is a very exotic use case

Hi @namapane , just for my education, how exotic are these cases? Do we have any occurrences in the past?
The upstream fix that you are suggesting is something related to DD4HEP or to MF?

**Comment by clacaputo** [comment]
> In any case, the fix would have to be in DD4HEP, to allow rebuilding a geometry in the same process. @civanch may be able to comment better.

Hi @civanch , do you think it would be better to open an issue about it?

**Comment by civanch** [comment]
@namapane , @clacaputo , I think that it is not needed to duplicate issue https://github.com/cms-sw/cmssw/issues/38669. 
This PR is valid and should be merged. Concerning change of geometry between runs in one job I know it is not recommended for Geant4 but in some cases may work by chance, for example, in the case of a single thread.

**Comment by clacaputo** [comment]
+reconstruction

- address item 1 of https://github.com/cms-sw/cmssw/issues/38669
- no reco chages

**Comment by perrotta** [comment]
+1

**Pull request merged**
