### PR TITLE
Run3-gex98E Use ESGetToken in some of the test analyzers in SimMuon/GEMDigitizer

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Use ESGetToken in some of the test analyzers in SimMuon/GEMDigitizer

#### PR validation:

Use runTheMatrix test workflows

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by perrotta** [comment]
+1

**Comment by bsunanda** [comment]
@AdrianoDee, @srimanob Please approve this PR

**Comment by srimanob** [comment]
+Upgrade

Technical PR on esConsumes migration. No change is expected from this PR. PR test runs fine.

**Comment by perrotta** [comment]
+1

**Pull request merged**
