### PR TITLE
Tracker Alignment Maps limit output options + cleanup fix

### PR DESCRIPTION
**Pull request by SenneVanPutte**
#### PR description:

Adding output limitation options.
Fixed cleanup step bug that caused segment violation.

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
I think the RelVal failures are due to some (temporary?) eos glitch.
The problem in the unit test highlighted another problem though:
```
[0B/0B][100%][==================================================][0B/s]  
Run: [ERROR] Server responded with an error: [3014] Unable to open file  /eos/cms/store/caf/user/cschomak/emptyModuleList.txt; Network is unreachable� (source)

cat: emptyModuleList.txt: No such file or directory
Done.

All-In-One Tool: /store/caf/user/cschomak/emptyModuleList.txt does not exist!
```
There should be no usage of private user eos areas in central tools.
@SenneVanPutte perhaps you can take care of that too?

https://github.com/cms-sw/cmssw/blob/18f41ede8ac62f7097030abe8f052451c78e08ad/Alignment/OfflineValidation/python/TkAlAllInOneTool/geometryComparison.py#L19

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by tlampen** [comment]
+alca

**Comment by qliphy** [comment]
+1

**Pull request merged**
