### PR TITLE
Add Heavy Ion AOD Event Content as requested from Heavy Ion PInGs

### PR DESCRIPTION
**Pull request by appeltel**
Change AOD EventContent to reflect the requirements from the Heavy Ion Physics Interest Groups (PInGs) for analysis of 2015 PbPb data.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
+1

For #9042 42153b2c3194b9c273c5a955ce80ea667b680b60

This PR adds to the HI AOD event content. It should merely add data, not change monitored quantities.

The code changes are satisfactory, and Jenkins tests show no significant differences, as expected. Tests of HI workflow 140.53 with 100 events also show no significant differences compared to baseline CMSSW_7_5_X_2015-05-10-2300. Comparison of the AOD content between baseline and PR shows that the additional collections do indeed appear in the new AOD, and AOD file size for this test workflow grows by about 20%.

**Comment by davidlange6** [comment]
+1

**Comment by slava77** [comment]
@cvuosalo  What's the size of the AOD/event now?

**Comment by slava77** [comment]
(responding to self)
the last time I checked (before this PR) the AOD size was 1MB/evt , so, +20% here should mean 1.2 MB.
RECO here was 4.5 MB/evt.
This is still a ~50/50 mix of ~empty vs "normal" PbPb events.

**Comment by cvuosalo** [comment]
@slava77: In my test, the baseline size of AOD was reported as 830 kB per event, and with this PR it became 1010 kB per event.

**Pull request merged**
