### PR TITLE
Replace mark-and-delete at next merge algorithm in DQMStore (75x)

### PR DESCRIPTION
**Pull request by dmitrijus**
Additionally, the DQMStore will now acquire locks for writing files.

This PR also add a new file saver for HLT->PB (DQMFileSaverPB).
Which should replace DQMFileSaver in the near future.

Please do not accept this PR until I say okay.

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by dmitrijus** [comment]
Ready to go in

**Comment by deguio** [comment]
+1
yep. I confirm. content validated.

**Comment by fwyzard** [comment]
I know that this is under DQM responsibility, but since the changes are intended explicitly for the HLT, let me ask...

Why do you think a dedicated DQMFileSaver module for .pb files is a better approach ?
Doesn't it increase code duplication, and make it easier for the online and offline code base to go out of sync ?

**Comment by dmitrijus** [comment]
If you look at the DQMFileSaver, the code is not even related to the file saving,
but rather the glue code needed for each use case.
The *actual* saving is done by calling DQMStore->save{PB}.

As it is now, there is a huge mess of at least 7 parameters (and only a few of them are used for a given workflow). With this approach, we isolate each parameter and functionally  to a specific workflow.

> Doesn't it increase code duplication?

No, since this was essentially a glue code, it is very specific to a workflow.
For example, for .pb output we also write .json files and this is only true for .pb.
No other workflow writes a .json files.

> Make it easier for the online and offline code base to go out of sync?

On contrary, this will make maintaining the code way easier:
we will be able to modify any workflow without affecting the other.

Even though saver for .pb is a separate module, it still has a common base (DQMFileSaverBase).
Our plan is to have 3 modules:

* DQMFileSaverOnline -> for DQM saving at our online cluster, it is already done.
It implements some "weird" features like writing origin files and making periodical backups;
* DQMFileSaverPB -> for DQM output at HLT (ie .pb output);
* DQMFileSaverOffline -> for the offline workflows (not yet done).

Old DQMFileSaver will be deprecated/removed once we migrate each workflow.

By the way, HLT does not have to switch to DQMFileSaverPB yet.
The deletion fix (main reason for this PR) applies to both old and new savers.

**Comment by fwyzard** [comment]
Understood, thanks!

**Comment by deguio** [comment]
+1
ups

**Pull request merged**
