### PR TITLE
HLT menu 2017 v1.1 (backport of #19235)

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
HLT menu 2017 v1.1 (backport of #19235 to 92X)

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
backport of #19235

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by Martin-Grunewald** [comment]
@arunhep @franzoni 
...same for 92X.... (#19235 is integrated in 93X)

**Comment by Martin-Grunewald** [comment]
eos error lead to the above failure

**Comment by Martin-Grunewald** [comment]
please test

**Comment by arunhep** [comment]
@Martin-Grunewald 
I was wondering about the purpose of backport this PR in 92X. 
Because as you know this has been merged in 93X which will eventually be used for MC production.

**Comment by Martin-Grunewald** [comment]
@arunhep @fwyzard 
There isn't even a timeline for a 930final yet - and I thought the MC production will be with 92?
But in any case, 92 is the data taking release and we'd also need to have a recent HLT menu in
the release itself.

**Comment by arunhep** [comment]
@Martin-Grunewald 
it has been established in last orp meeting that release for MC production will be 93X.
keep in mind that the L1 menu is buggy here.

**Comment by Martin-Grunewald** [comment]
OK, thanks!
Concerning the L1T issue, we expect a fix which needs to be backported, as TSG studies will have to continue in 92 as long as that is the data taking release.

**Comment by arunhep** [comment]
+1
L1T menu fix needs to be back-ported to 92X, whenever available as mentioned by @Martin-Grunewald

**Comment by Martin-Grunewald** [comment]
hold

**Comment by arunhep** [comment]
@Martin-Grunewald @davidlange6 
can this be merged ? we will then start back-porting other stuff relevant for V1 MC production? if this is merged then we can recycle the GTs which we have used in 93X integration process. 
@franzoni @lpernie

**Comment by Martin-Grunewald** [comment]
@arunhep @davidlange6 
Yes, we (TSG) would also like to get this merged, though not this specific PR but instead in form of PR #19468 which contains this and further stuff (not changing the AlCa part).

**Comment by Martin-Grunewald** [comment]
Closing this PR as being superseded by #19445

**Pull request closed without merging**
