### PR TITLE
[92X] RelVal tests for new alca workflows

### PR DESCRIPTION
**Pull request by cerminar**
This PR edits the production set of relvals adding workflows to test:
- ECAL pedestal creation in PCL
- new AlCaLumiPixel alcarecos running from ALCARAW
- new AlCaLumiPixel alcarecos running from RAW

### CODE REVIEW

**Comment by franzoni** [comment]
please test

**Comment by franzoni** [comment]
The error on the workflow 4.22 is un-related to this PR:

`   [2017-05-30 16:25:59.314951 +0200][Error  ][AsyncSock         ] [eoscms.cern.ch:1094 #0.0] Socket error while handshaking: [ERROR] Socket timeout`

**Comment by franzoni** [comment]
please test

**Comment by arunhep** [comment]
@arunhep adding myself to watch

**Comment by fabozzi** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Pull request merged**
