### PR TITLE
Run3-hcx379X Creating the possibility to add the additional MB4 shield in Phase2 scenarios

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Creating the possibility to add the additional MB4 shield in Phase2 scenarios

#### PR validation:

Use the runTheMatrix test workflows

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
+geometry

**Comment by bsunanda** [comment]
@subirsarkar Please approve this PR

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
