### PR TITLE
Back port of ALCARECOLumiPixelsMinBias to 74X

### PR DESCRIPTION
**Pull request by capalmer85**
exactly like https://github.com/cms-sw/cmssw/pull/8948, but in 74X

### CODE REVIEW

**Comment by capalmer85** [comment]
I have checked this in the same way described in the AlCa/DB meeting.  The results are identical.

Just to know, if I had done this development in 74X first, would that have been automatically pushed into 75X eventually?  Or will I always need make two PRs?

**Comment by mmusich** [comment]
@cmsbuild please test

**Comment by mmusich** [comment]
@capalmer85 7.5.X is the current development release. Updates should first go there and then backport to 7.4.X

**Comment by mmusich** [comment]
+1
backport of #8948

**Comment by davidlange6** [comment]
@capalmer85 - please change the title of this PR to be descriptive of the change for the release notes

**Comment by davidlange6** [comment]
+1

**Pull request merged**
