### PR TITLE
Update Payload Scripts for 76x

### PR DESCRIPTION
**Pull request by ianna**
- Use new HCAL parameters schema
- Remove obsolete files
- Clean up metadata files

### CODE REVIEW

**Comment by diguida** [comment]
please test

**Comment by ianna** [comment]
@cmsbuild - the error is unrelated to this PR.

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
@cmsbuild please test

**Comment by ianna** [comment]
+1

**Comment by ggovi** [comment]
+1

**Comment by mmusich** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
