### PR TITLE
add hltTracksMerged monitoring (both DQM and Validation)

### PR DESCRIPTION
**Pull request by mtosi**
new tracking @HLT strategy for the pixel bad components mitigation [https://its.cern.ch/jira/browse/CMSHLT-1360]
has updated the name of the final tracks collection
=> this PR adds both the DQM and Validation for the new hltTracksMerged collection

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by mtosi** [comment]
I'm confused (sorry)
are these errors related to this PR ?
thanks

**Comment by mtosi** [comment]
the analogous PR in 92x (https://github.com/cms-sw/cmssw/pull/19594) seems fine
=> I do not totally get why this is not working properly
could we test it again ?

**Comment by dmitrijus** [comment]
+1

**Comment by dmitrijus** [comment]
plase test

**Comment by dmitrijus** [comment]
please test

**Comment by mtosi** [comment]
I still not get how this PR can produce such error, do you ?
thanks

**Comment by Martin-Grunewald** [comment]
please test

**Comment by mtosi** [comment]
can we merge this PR, please ?

**Comment by Martin-Grunewald** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
