### PR TITLE
HLT menu migration to CMSSW 12_0_0_pre5 template [12_0_X]

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
#### PR description:

HLT menu migration to CMSSW 12_0_0_pre5 template [12_0_X]

#### PR validation:

TSG tests

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Backport of #34740  (needed for HLT)

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
backport of #34740

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by Martin-Grunewald** [comment]
please test

**Comment by perrotta** [comment]
+1
Same as the corresponding one merged in master, already signed by HLT
I won't care about failing RelVals-INPUT tests, as the issue is general these days

**Comment by perrotta** [comment]
merge

**Pull request merged**
