### PR TITLE
New HF Shower Library interface  for FastSim 

### PR DESCRIPTION
**Pull request by Vlandr57**
This is version of HF Shower Library interface for FastSim which allows
to use all necessary functions  from FullSim Shower Library.

### CODE REVIEW

**Comment by lveldere** [comment]
please test

**Comment by Vlandr57** [comment]
Strange, I just checked again the compilation with 
scram b vclean && scram build -k -j 12 USER_CXXFLAGS='-fsyntax-only' COMPILER='llvm compile'
it was OK for CMSSW_7_5_X_2015-03-28-2300 with some warning messages

**Comment by lveldere** [comment]
Hi Vladimir

The errors are not related to your pr, don't worry about it.

Cheers

Lukas

**Comment by lveldere** [comment]
+1

no regression expected, no regression observed

**Comment by civanch** [comment]
+1

**Pull request merged**
