### PR TITLE
added esConsumes to modules in RecoTracker/TrackProducer

### PR DESCRIPTION
**Pull request by JamminJones**
#### PR description:

added esConsumes to 1 module

#### PR validation:

the code compiles

### CODE REVIEW

**Comment by JamminJones** [comment]
the following modules were not modified due to the complexity of the changes required: GsfTrackProducer, GSFTrackRefitter,Trackproducer,TrackRefitter,DAFTrackProducer,TwoBodyDecayConstraintProducer, and TwoBodyDecayMomConstraintProducer

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
+1
- Technical
- Jenkins tests pass

**Comment by silviodonato** [comment]
+1

**Pull request merged**
