### PR TITLE
Add new functions to AlCaNano.py needed for the T0 replay

### PR DESCRIPTION
**Pull request by tvami**
#### PR description:

T0 replay revealed some missing functions in the AlCaNano.py: https://github.com/dmwm/T0/pull/4664#issuecomment-1172776748

This PR adds that

#### PR validation:

scram b runtests

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Needed to be backported to 12_4_X

### CODE REVIEW

**Comment by tvami** [comment]
type ecal,bugfix

**Comment by tvami** [comment]
urgent
 * backport should go into 12_4_3

**Comment by tvami** [comment]
assign alca

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by francescobrivio** [comment]
+1

 - in line with PR description
 - will be tested in Tier0 replay

**Comment by perrotta** [comment]
+1

**Pull request merged**
