### PR TITLE
Add HGCAL L1 trigger in SimL1Emulator and event content

### PR DESCRIPTION
**Pull request by jbsauvan**
For the `phase2_hgcal` era:
- Add the HGCAL L1 trigger simulation in the `SimL1Emulator` sequence
- Add the HGCAL trigger cell digis in the `L1TriggerFEVTDEBUG` event content

The processing time increase is a bit more than 1s/event for 200PU events. The output collection size is about 400kB/event for 200PU events.

### CODE REVIEW

**Comment by jbsauvan** [comment]
@lgray This is something you might want to follow

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by jbsauvan** [comment]
@rekovic @mulhearn  you already saw these changes in an email I sent you 2 weeks ago.
Could you take a look again and tell me if you have comments?
Thanks

**Comment by rekovic** [comment]
+1

**Comment by jbsauvan** [comment]
Resolved conflicts introduced by #16001

**Comment by jbsauvan** [comment]
@davidlange6 
Now this pull request looks a bit messy. It should concern only L1 trigger packages. Should I create a clean new PR?

**Comment by slava77** [comment]
-1
rebase is needed

**Comment by jbsauvan** [comment]
Thanks! Rebase done.
@rekovic @mulhearn, could you have a look again after the changes? The direct imports of Eras have been removed.
And could someone trigger the tests?
Thanks

**Comment by jbsauvan** [comment]
@rekovic @mulhearn @davidlange6 
Can this PR be signed / merged, or do you need that I make some changes?
Thanks

**Comment by rekovic** [comment]
+1

**Comment by jbsauvan** [comment]
@davidlange6 
Now that it is fully signed, do you think this PR can be merged? Or do you have comments?
Thanks

**Comment by davidlange6** [comment]
+1

**Pull request merged**
