### PR TITLE
New binning of Run-3 CLCT slope (CCLUT-13)

### PR DESCRIPTION
**Pull request by dildick**
#### PR description:

Previously the CLCT slope binning was fixed to ~0.156 from 0 up to 2.5 half-strips / layer in the Run-3 CLCT algorithm. This PR updates the definition so it is always a multiple of 1/8-strip/layer. First 14 bins are 1/8 wide. Last two are 1/4 and 1/2 wide. See also [DN-19-059](https://gitlab.cern.ch/tdr/notes/DN-19-059/blob/master/temp/DN-19-059_temp.pdf), section 4.8. 

Related PR: https://github.com/cms-data/L1Trigger-CSCTriggerPrimitives/pull/5

#### PR validation:

Code compiles. Tested in CMSSW_11_2_0_pre9 on single muon gun.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A. Run-3 CLCT algorithm not yet deployed at P5.

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

@tahuang1991

### CODE REVIEW

**Comment by dildick** [comment]
A few plots are included in DN-19-059 showing the discretization. Examples for ME1/1, ME1/2, ME2/1 and ME2/2 below

With full slope resolution:
Screen Shot 2021-04-08 at 9 26 40 PM

With 1(sign)+4(value) -bit slope resolution
Screen Shot 2021-04-08 at 9 26 58 PM

**Comment by dildick** [comment]
@jiafulow @abrinke1 @eyigitba PR for the new slope binning.

**Comment by civanch** [comment]
please test

**Comment by cecilecaillol** [comment]
+l1

**Comment by civanch** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
