### PR TITLE
Run3-gem55 Add analyzer to dump content of Muon SimHits

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Add analyzer to dump content of Muon SimHits (useful in establishing hits produced in dd4hep)

#### PR validation:

Used in the testing of SIM step with dd4hep

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Comment by fabiocos** [comment]
@civanch @bsunanda @silviodonato please recall that if you want to quickly inspect the simhits content of an event you may also use https://github.com/cms-sw/cmssw/blob/master/SimG4Core/Application/test/SimHitCaloHitDumper.cc through https://github.com/cms-sw/cmssw/blob/master/SimG4Core/Application/test/runSimHitCaloHitDumper_cfg.py

**Pull request merged**
