### PR TITLE
EGM IDs for MiniAOD Reprocessing (74X)

### PR DESCRIPTION
**Pull request by lgray**
Contains new IDs for Spring15.
- Cutbased variants for 50ns and 25ns
- MVA base variants, 25ns for electrons, 25ns/50ns for photons.
- HEEPV6

Bools are embedded in the pat objects for these IDs.

Please note that the Photon PF isolation variables are now overwritten in MiniAOD to give the values that are used as input to the cutbased photon ID.
Links to all documentation can be found in the corresponding python configuration files.

HEEP5.1 is removed.

Embedding of ID variables (not the cut flow digests) in PAT is enabled through object modifiers.
- All things needed to recalculate MVA values, as well as mva values and categories themselves.

This PR is dependent on #10556.

Weight files are absent from this PR.

Now includes backport of: #10873

@ikrav @cmkuo
@gpetruc @arizzi

### CODE REVIEW

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@lgray is there a PR in the cms-data for the xml files already?
What is the net effect on the memory use? (e.g., using step3 from 4.77, since it's closer in size to T0 workflows and has some egamma objects)

**Comment by lgray** [comment]
@slava77 yes, links: https://github.com/cms-data/RecoEgamma-PhotonIdentification/pull/3 https://github.com/cms-data/RecoEgamma-ElectronIdentification/pull/5

**Comment by lgray** [comment]
@slava77 Net effect on RSS was something like 40-50MB. igprof showed something bigger.

**Comment by lgray** [comment]
@cmsbuild please test

new ib with externals is ready.

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
@cmsbuild please test

previous errors were das errors...

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by monttj** [comment]
+1

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/10598	b4877ad
- changes in the code are consistent with the 75X/76X version (I checked the 75X diffs vs this PR) ==> expected
- jenkins tests pass and show no differences in monitored quantities
- tested locally in CMSSW_7_4_X_2015-08-14-1100 /test area sign579/ including run2 dimuon 251721 run 200 events for memory/technical performance tests:
    - there is a minor increase in slimmedElectrons and slimmedPhotons products size (~<1%); other products [RECO/AOD are unchanged]
    - {photon,electron}MVAValueMapProducer, photonIDValueMapProducer, and egmPhotonIDs new modules now show up in the path (expected)
    - after 10 events there is a 0.3 MB increase in total allocated memory: of these, the move from TMVA to GBR is -3 MB (reduction) and show up clearly in the change in allocation from 9.5 MB in ElectronMVAEstimatorRun2Phys14NonTrig to 6.7 MB in  MVAValueMapProducer for GsfElectron and Photon modules (new modules added) ; I couldn't  track down the increase (could be incidental)

@gpetruc now that #10619 is merged, you can pick this one up

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by gpetruc** [comment]
Ok, later today I will update also #10649 re-merging this

**Comment by lgray** [comment]
@smuzaffar Can you check out what happened here? Looks like Jenkins died in the middle of testing?

**Comment by smuzaffar** [comment]
@lgray , looks like the build machine went offline during the build. You can restart the tests by comments "please test"

**Comment by smuzaffar** [comment]
please test
ok I did it :-)

**Comment by lgray** [comment]
:-)

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/10598	0533d42
- changes are consistent with integration of  commits made in #10873 on top of previously signed off version of this PR in  https://github.com/cms-sw/cmssw/pull/10598	b4877ad  [checked by cherry-picking]
- jenkins tests passed as far as the could with the infrastructure issues.
- tested locally with a short matrix and 200 events from 251721 DoubleMuon and DoubleEG in CMSSW_7_4_10_patch1 /test area sign579/
    - there are no changes in the monitored quantities in DQM or in fwlite reco comparisons
    - compared to 75X/76X, there is a larger (about x2) contribution in CPU from photonIDValueMapProducer: the code is using ptrAt, which comes through a RefToBase in 74X. The PhotonIDValueMapProducer is the largest consumer of edm::View<reco::Candidate>::ptrAt method https://slava77sk.web.cern.ch/slava77sk/reco/cgi-bin/igprof-navigator/CMSSW_7_4_10_patch1-sign579-cvmfs.251721.DoubleEG.pp/985 .  This code, as implemented doesn't seem to need the persisted Ptr/Ref info and could operate with plain c reference. 
    - AOD and RECO outputs are unchanged
    - MINIAOD output shows mild increase in the size of electrons and photons
```
-------------------------------------------------------------
 orig, B       new, B      delta, B   delta, %   deltaJob, %    branch 
-------------------------------------------------------------
     2602 ->        2636         34      1.3   0.10     patElectrons_slimmedElectrons__RECO.
     1947 ->        2046         99      5.0   0.28     patPhotons_slimmedPhotons__RECO.
```

**Comment by lgray** [comment]
@cmsbuild please test

@monttj can you please sign? Thanks!

**Comment by monttj** [comment]
+1

**Comment by slava77** [comment]
@davidlange6  this one is merged in #10649 already

**Pull request closed without merging**
