### PR TITLE
Added protection for invalid GhostTrackStates

### PR DESCRIPTION
**Pull request by ferencek**
This is a fix for the problem reported in https://hypernews.cern.ch/HyperNews/CMS/get/physTools/3574.html

Thanks to @oglez for proposing the fix.

@arizzi @imarches @kskovpen @mverzett @JyothsnaKomaragiri

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
@ferencek : do you have a script to test this fix?

About the possible input file: I think that 
/eos/cms/store/mc/RunIISummer17MiniAOD/DYJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/MINIAODSIM/92X_upgrade2017_realistic_v10_ext1-v1/110000/C8DC18F2-8B85-E711-A66E-E0071B7AE500.root
is not there any more.

**Comment by ferencek** [comment]
I was doing tests in CMSSW_9_2_8 by running https://github.com/cms-sw/cmssw/blob/CMSSW_9_2_8/PhysicsTools/PatAlgos/test/patTuple_updateJets_fromMiniAOD_cfg.py where I added at the bottom of the file
```python
process.source = cms.Source("PoolSource",
    fileNames = cms.untracked.vstring(
        'root://cmsxrootd.fnal.gov//store/mc/RunIISummer17MiniAOD/DYJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/MINIAODSIM/92X_upgrade2017_realistic_v10_ext1-v1/110000/C8DC18F2-8B85-E711-A66E-E0071B7AE500.root'
    ),
    skipEvents = cms.untracked.uint32(21492)
)

process.setName_('TEST')
```
In out-of-the-box CMSSW_9_2_8 this should crash. After adding the fix
```bash
git cms-merge-topic cms-btv-pog:GhostTrackStateProtection_from-CMSSW_9_2_8
```
the crash no longer occurs.

**Comment by perrotta** [comment]
+1
- This fix actually prevents crashing in case of invalid states
- For that particular state now it is the same as non passing the request of distance from the "origin", i.e. it is not further updated, while a LogError is issued

**Comment by davidlange6** [comment]
merge

**Pull request merged**
