### PR TITLE
Add Tracker Alignment di-muon monitoring to other resonances

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

This PR extends on the concept introduced at https://github.com/cms-sw/cmssw/pull/39148 (and then followed up at https://github.com/cms-sw/cmssw/pull/39173 and https://github.com/cms-sw/cmssw/pull/39217) in order to monitor the vertexing and mass biases for other di-muon resonances (J/ψ→µµ  and Υ(1S) →µµ) used in the tracker alignment procedure.

#### PR validation:

Relies on the existing (and augmented) unit tests.
The output of it has been uploaded to a test GUI for convenience of inspection and it's available by connecting to:

```console
 ssh -NL 8060:localhost:8060 <USER>@lxplus724.cern.ch
````
and visiting:
   * for the J/ψ → µµ : https://tinyurl.com/2nlexqqx
   * for the Υ(1S) → µµ : https://tinyurl.com/2f2qkelc  

Morevor the single bin fits for the resonance masses are available [here](http://musich.web.cern.ch/musich/display/2022CMassBiasFits/)

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Not a backport but will be backported to 12.5.x and 12.4.x for data-taking monitoring purposes.

### CODE REVIEW

**Comment by mmusich** [comment]
test parameters:
   * workflow = 1002.4
   * relvals_opt = --what cleanedupgrade,standard,highstats,pileup,generator,extendedgen,production,ged,machine,premix

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by emanueleusai** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
