### PR TITLE
Add `SiPixelRawDataError` monitoring for `gpuValidation` setup

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

Somewhat inspired by the discussion at https://github.com/cms-sw/cmssw/issues/41715#issuecomment-1580541189, the main goal of this PR is to add a `DQMEDAnalyzer` (`SiPixelPhase1RawDataErrorComparator`) designed to monitor the difference in terms of SiPixel Raw data errors in the CPU and GPU branches of the workflows running the `gpuValidation` modifier.
As there is no SoA-like data structure used in the CPU workflow (it reads directly the legacy digis) at variance with other heterogeneous data products used in the pixel workflow (recHits, tracks, vertices) I designed the module in order to read the legacy data format `SiPixelRawDataError` (converted from SoA in the GPU workflow and run directly in the CPU one).
I profit of this PR to fix a couple of bugs left from the portable data migration PR:
   * fix a mistake in one of the input tags in `SiPixelCompareRecHitsSoA` (commit d65a81a8ed53056355948592a845395ca417efc2)
   * use in `SiPixelCompareRecHitsSoA` the convention Host -> CPU and Device -> GPU as used in other plugins of this package 

#### PR validation:

Successfully run the worfklow `runTheMatrix.py -l 10824.507 --command='-n 100'.`

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Not a backport, but it might be backported in order to use in the 2023 HLT menus.

Cc:
@sroychow @AdrianoDee

### CODE REVIEW

**Comment by mmusich** [comment]
test parameters:
   * enable_tests = gpu

**Comment by mmusich** [comment]
test parameters:
   * enable_tests = gpu
   * workflows_gpu = 11634.503, 11634.506, 11634.583, 11634.587, 10824.507

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
test parameters:
   * enable_tests = gpu
   * workflows_gpu = 10824.507
   * relvals_opt= -w upgrade
   * relvals_opt_gpu = -w upgrade

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by emanueleusai** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
