### PR TITLE
More L1T bug fixes [11.1.x]

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Fix several bugs found by @tommasoboccali.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Backport #30606 .

### CODE REVIEW

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by fwyzard** [comment]
backport #30606

**Comment by fwyzard** [comment]
type bugfix

**Comment by fwyzard** [comment]
urgent

**Comment by silviodonato** [comment]
merge

**Comment by kpedro88** [comment]
+upgrade

**Pull request merged**
