### PR TITLE
continuing HLT integrations - 75X

### PR DESCRIPTION
**Pull request by geoff-smith**
CMSHLT-310 - added to GRun, 50nsGRun (already in masters)
CMSHLT-273 - added to masters, 50nsGRun

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
@Dr15Jones 
Hi Chris, 
Do you know what this error
```
'EDAlias' object has no attribute 'resolve'
```
actually means in the above FastSim test?

**Comment by lveldere** [comment]
@Dr15Jones @Martin-Grunewald 
I'm looking into the 

'''
'EDAlias' object has no attribute 'resolve'
'''

I commented out all edaliases, which lead to the error

'''
Exception Message:
python encountered the error: <type 'exceptions.RuntimeError'>
The SequencePlaceholder muonDTDigis cannot be resolved.
'''

So, it seems that SequencePlaceholder cannot work together with EDAliases

**Comment by lveldere** [comment]
@Martin-Grunewald @sekmen

Hi Martin

I get rid of the error by redefining the following sequence as

```
#process.HLTMuonLocalRecoSequence = cms.Sequence(cms.SequencePlaceholder("muonDTDigis")+process.hltDt1DRecHits+process.hltDt4DSegments+cms.SequencePlaceholder("muonCSCDigis")+process.hltCsc2DRecHits+proc\
ess.hltCscSegments+cms.SequencePlaceholder("muonRPCDigis")+process.hltRpcRecHits)
```
as

```
process.HLTMuonLocalRecoSequence = cms.Sequence(process.hltRpcRecHits)
```

That leads to another unrelated crash

```
----- Begin Fatal Exception 16-Apr-2015 19:31:19 CEST-----------------------
An exception of category 'ProductNotFound' occurred while
   [0] Processing run: 1 lumi: 1 event: 1
   [1] Running path 'HLT_ReducedIterativeTracking_v1'
   [2] Calling event method for module EcalUncalibRecHitProducer/'hltEcalUncalibRecHit'
Exception Message:
Principal::getByToken: Found zero products matching all criteria
Looking for type: EBDigiCollection
Looking for module label: hltEcalDigis
Looking for productInstanceName: ebDigis
```

If the label hltEcalDigis is replaced with ecalDigis, this should be gone as well.

**Comment by Dr15Jones** [comment]
Is ```muonDTDigis``` an EDAlias?

**Comment by Martin-Grunewald** [comment]
Yes, 
```
process.muonDTDigis = cms.EDAlias(
    simMuonDTDigis = cms.VPSet(cms.PSet(
        type = cms.string('DTLayerIdDTDigiMuonDigiCollection')
    ))
)
```

**Comment by Martin-Grunewald** [comment]
@lveldere 
Hi Lukas, I have update this PR with your changes and new FastSim HLT dumps.
There are still errors, now like this:
```

Warning: L1GlobalTriggerObjectMapRecord with input tag InputTag:  label = gtDigis, i\
nstance =
requested in configuration, but not found in the event.
%MSG
%MSG-w HLTLevel1GTSeed:  HLTLevel1GTSeed:hltL1sL1ZeroBias  17-Apr-2015 13:33:34 CEST\
 Run: 1 Event: 1

```
and
```
----- Begin Fatal Exception 17-Apr-2015 13:33:35 CEST-----------------------
An exception of category 'ProductNotFound' occurred while
   [0] Processing run: 1 lumi: 1 event: 1
   [1] Running path 'HLT_PFMETForMC_v1'
   [2] Calling event method for module L2MuonSeedGenerator/'hltL2MuonSeeds'
Exception Message:
Principal::getByToken: Found zero products matching all criteria
Looking for type: L1MuGMTReadoutCollection
Looking for module label: gtDigis
Looking for productInstanceName:

   Additional Info:
      [a] If you wish to continue processing events after a ProductNotFound exceptio\
n,
add "SkipEvent = cms.untracked.vstring('ProductNotFound')" to the "options" PSet in \
the configuration.

----- End Fatal Exception -------------------------------------------------
```

**Comment by lveldere** [comment]
@Martin-Grunewald 
That one should be fixed now,
please
git cms-merge-topic lveldere:hlt-fastsim-collection-edits

I can't debug, cause I don't know how confdb.py works...

**Comment by Martin-Grunewald** [comment]
@lveldere 

....and also:
```
--- a/FastSimulation/Configuration/python/DigiAndMixAliasInfo_cff.py
+++ b/FastSimulation/Configuration/python/DigiAndMixAliasInfo_cff.py
@@ -91,7 +91,10 @@ muonCSCDigisAliasInfo = cms.VPSet(
 gtDigisAliasInfo = cms.VPSet (
     cms.PSet(
         key = cms.string("simGtDigis"),
-        value = cms.VPSet(cms.PSet(type = cms.string("L1GlobalTriggerReadoutRecord")))
+        value = cms.VPSet(
+            cms.PSet(type = cms.string("L1GlobalTriggerReadoutRecord")),
+            cms.PSet(type = cms.string("L1GlobalTriggerObjectMapRecord"))
+            )
         )
```

**Comment by Martin-Grunewald** [comment]
@lveldere 
Needed to add the EDAlias for gmtDigis (similar to gtDigis).
Please have a look!

**Comment by lveldere** [comment]
@Martin-Grunewald 

Thanks!
It looks good.

**Comment by Martin-Grunewald** [comment]
@lveldere 

Ah well, now there is a runtime crash in FamosProducer's destructor:
```
%MSG
%MSG-e FatalSystemSignal:  AfterModConstruction 17-Apr-2015 16:51:38 CEST  pre-events
A fatal system signal has occurred: segmentation violation
%MSG


A fatal system signal has occurred: segmentation violation
The following is the call stack containing the origin of the signal.
NOTE:The first few functions on the stack are artifacts of processing the signal and can be ignored

#0  0x0000003a6f2ac61e in waitpid () from /lib64/libc.so.6
#1  0x0000003a6f23e609 in do_system () from /lib64/libc.so.6
#2  0x00007fa9978b7e27 in TUnixSystem::StackTrace() () from /afs/cern.ch/cms/sw/ReleaseCandidates/vol0/slc6_amd64_gcc491/cms/cmssw-patch/CMSSW_7_5_X_2015-04-17-1100/external/slc6_amd64_gcc491/lib/libCore.so
#3  0x00007fa98ce1ab55 in sig_dostack_then_abort () from /afs/cern.ch/cms/sw/ReleaseCandidates/vol0/slc6_amd64_gcc491/cms/cmssw/CMSSW_7_5_X_2015-04-16-2300/lib/slc6_amd64_gcc491/libFWCoreServices.so
#4  <signal handler called>
#5  0x00007fa9785bcb6d in HFShowerLibrary::~HFShowerLibrary() () from /afs/cern.ch/cms/sw/ReleaseCandidates/vol0/slc6_amd64_gcc491/cms/cmssw/CMSSW_7_5_X_2015-04-16-2300/lib/slc6_amd64_gcc491/libSimG4CMSCalo.so
#6  0x00007fa97868d87a in FastHFShowerLibrary::~FastHFShowerLibrary() () from /afs/cern.ch/cms/sw/ReleaseCandidates/vol0/slc6_amd64_gcc491/cms/cmssw/CMSSW_7_5_X_2015-04-16-2300/lib/slc6_amd64_gcc491/libFastSimulationShowerDevelopment.so
#7  0x00007fa978770772 in CalorimetryManager::~CalorimetryManager() () from /afs/cern.ch/cms/sw/ReleaseCandidates/vol0/slc6_amd64_gcc491/cms/cmssw/CMSSW_7_5_X_2015-04-16-2300/lib/slc6_amd64_gcc491/libFastSimulationCalorimetry.so
#8  0x00007fa9787a94ab in FamosManager::~FamosManager() () from /afs/cern.ch/cms/sw/ReleaseCandidates/vol0/slc6_amd64_gcc491/cms/cmssw/CMSSW_7_5_X_2015-04-16-2300/lib/slc6_amd64_gcc491/pluginFastSimulationEventProducer.so
#9  0x00007fa9787aed23 in FamosProducer::~FamosProducer() () from /afs/cern.ch/cms/sw/ReleaseCandidates/vol0/slc6_amd64_gcc491/cms/cmssw/CMSSW_7_5_X_2015-04-16-2300/lib/slc6_amd64_gcc491/pluginFastSimulationEventProducer.so
#10 0x00007fa9787aed89 in FamosProducer::~FamosProducer() () from /afs/cern.ch/cms/sw/ReleaseCandidates/vol0/slc6_amd64_gcc491/cms/cmssw/CMSSW_7_5_X_2015-04-16-2300/lib/slc6_amd64_gcc491/pluginFastSimulationEventProducer.so
#11 0x00007fa998495096 in edm::stream::ProducingModuleAdaptorBase<edm::stream::EDProducerBase>::~ProducingModuleAdaptorBase() () from /afs/cern.ch/cms/sw/ReleaseCandidates/vol0/slc6_amd64_gcc491/cms/cmssw/CMSSW_7_5_X_2015-04-16-2300/lib/slc6_amd64_gcc491/libFWCoreFramework.so
#12 0x00007fa9787b1fa7 in edm::stream::ProducingModuleAdaptor<FamosProducer, edm::stream::EDProducerBase, edm::stream::EDProducerAdaptorBase>::~ProducingModuleAdaptor() () from /afs/cern.ch/cms/sw/ReleaseCandidates/vol0/slc6_amd64_gcc491/cms/cmssw/CMSSW_7_5_X_2015-04-16-2300/lib/slc6_amd64_gcc491/pluginFastSimulationEventProducer.so
#13 0x0000000000410565 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release() ()
#14 0x00007fa99844a96a in std::_Rb_tree<std::string, std::pair<std::string const, std::shared_ptr<edm::maker::ModuleHolder> >, std::_Select1st<std::pair<std::string const, std::shared_ptr<edm::maker::ModuleHolder> > >, std::less<std::string>, std::allocator<std::pair<std::string const, std::shared_ptr<edm::maker::ModuleHolder> > > >::_M_erase(std::_Rb_tree_node<std::pair<std::string const, std::shared_ptr<edm::maker::ModuleHolder> > >*) () from /afs/cern.ch/cms/sw/ReleaseCandidates/vol0/slc6_amd64_gcc491/cms/cmssw/CMSSW_7_5_X_2015-04-16-2300/lib/slc6_amd64_gcc491/libFWCoreFramework.so
#15 0x00007fa99844a996 in std::_Sp_counted_ptr<edm::ModuleRegistry*, (__gnu_cxx::_Lock_policy)2>::_M_dispose() () from /afs/cern.ch/cms/sw/ReleaseCandidates/vol0/slc6_amd64_gcc491/cms/cmssw/CMSSW_7_5_X_2015-04-16-2300/lib/slc6_amd64_gcc491/libFWCoreFramework.so
#16 0x0000000000410565 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release() ()
#17 0x00007fa998446c71 in edm::Schedule::Schedule(edm::ParameterSet&, edm::service::TriggerNamesService&, edm::ProductRegistry&, edm::BranchIDListHelper&, edm::ThinnedAssociationsHelper&, edm::ExceptionToActionTable const&, std::shared_ptr<edm::ActivityRegistry>, std::shared_ptr<edm::ProcessConfiguration>, edm::ParameterSet const*, edm::PreallocationConfiguration const&, edm::ProcessContext const*) () from /afs/cern.ch/cms/sw/ReleaseCandidates/vol0/slc6_amd64_gcc491/cms/cmssw/CMSSW_7_5_X_2015-04-16-2300/lib/slc6_amd64_gcc491/libFWCoreFramework.so
#18 0x00007fa998452918 in edm::ScheduleItems::initSchedule(edm::ParameterSet&, edm::ParameterSet const*, edm::PreallocationConfiguration const&, edm::ProcessContext const*) () from /afs/cern.ch/cms/sw/ReleaseCandidates/vol0/slc6_amd64_gcc491/cms/cmssw/CMSSW_7_5_X_2015-04-16-2300/lib/slc6_amd64_gcc491/libFWCoreFramework.so
#19 0x00007fa9983b761d in edm::EventProcessor::init(std::shared_ptr<edm::ProcessDesc>&, edm::ServiceToken const&, edm::serviceregistry::ServiceLegacy) () from /afs/cern.ch/cms/sw/ReleaseCandidates/vol0/slc6_amd64_gcc491/cms/cmssw/CMSSW_7_5_X_2015-04-16-2300/lib/slc6_amd64_gcc491/libFWCoreFramework.so
#20 0x00007fa9983b91ea in edm::EventProcessor::EventProcessor(std::shared_ptr<edm::ProcessDesc>&, edm::ServiceToken const&, edm::serviceregistry::ServiceLegacy) () from /afs/cern.ch/cms/sw/ReleaseCandidates/vol0/slc6_amd64_gcc491/cms/cmssw/CMSSW_7_5_X_2015-04-16-2300/lib/slc6_amd64_gcc491/libFWCoreFramework.so
#21 0x000000000040d1e9 in main::{lambda()#1}::operator()() const ()
#22 0x000000000040b666 in main ()
```

Can you have a look? The PR is rebased to CMSSW_7_5_X_2015-04-17-1100

**Comment by Martin-Grunewald** [comment]
@lveldere 
BTW, the above crash happens also when the HLT step is removed from the cmsDriver command...

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
Traceback with line numbers - did you add the HF to the FastSim geometry recently?

```
#0  0x0000003a6f2ac61e in waitpid () from /lib64/libc.so.6
#1  0x0000003a6f23e609 in do_system () from /lib64/libc.so.6
#2  0x00007f10f51c8e27 in TUnixSystem::StackTrace() () from /afs/cern.ch/cms/sw/ReleaseCandidates/vol0/slc6_amd64_gcc491/cms/cmssw-patch/CMSSW_7_5_X_2015-04-17-1100/external/slc6_amd64_gcc491/lib/libCore.so
#3  0x00007f10eb09ab55 in sig_dostack_then_abort () from /afs/cern.ch/cms/sw/ReleaseCandidates/vol0/slc6_amd64_gcc491/cms/cmssw/CMSSW_7_5_X_2015-04-16-2300/lib/slc6_amd64_gcc491/libFWCoreServices.so
#4  <signal handler called>
#5  0x00007f10d63412e7 in HFShowerLibrary::~HFShowerLibrary (this=0x6000003e8, __in_chrg=<optimized out>) at /data/CMS0/CMSSW_7_5_X_2015-04-17-1100/src/SimG4CMS/Calo/src/HFShowerLibrary.cc:164
#6  0x00007f10d645b3f7 in FastHFShowerLibrary::~FastHFShowerLibrary (this=0x7f10ee4bb300, __in_chrg=<optimized out>) at /data/CMS0/CMSSW_7_5_X_2015-04-17-1100/src/FastSimulation/ShowerDevelopment/src/FastHFShowerLibrary.cc:42
#7  0x00007f10d656de42 in CalorimetryManager::~CalorimetryManager (this=0x7f10f0ea1e00, __in_chrg=<optimized out>) at /data/CMS0/CMSSW_7_5_X_2015-04-17-1100/src/FastSimulation/Calorimetry/src/CalorimetryManager.cc:165
#8  0x00007f10d662d97a in FamosManager::~FamosManager (this=0x7f10ee9bf040, __in_chrg=<optimized out>) at /data/CMS0/CMSSW_7_5_X_2015-04-17-1100/src/FastSimulation/EventProducer/src/FamosManager.cc:87
#9  0x00007f10d663a3ed in FamosProducer::~FamosProducer (this=0x7f10edaeb580, __in_chrg=<optimized out>) at /data/CMS0/CMSSW_7_5_X_2015-04-17-1100/src/FastSimulation/EventProducer/src/FamosProducer.cc:67
#10 0x00007f10d663a462 in FamosProducer::~FamosProducer (this=0x7f10edaeb580, __in_chrg=<optimized out>) at /data/CMS0/CMSSW_7_5_X_2015-04-17-1100/src/FastSimulation/EventProducer/src/FamosProducer.cc:67
#11 0x00007f10f5da5096 in edm::stream::ProducingModuleAdaptorBase<edm::stream::EDProducerBase>::~ProducingModuleAdaptorBase() () from /afs/cern.ch/cms/sw/ReleaseCandidates/vol0/slc6_amd64_gcc491/cms/cmssw/CMSSW_7_5_X_2015-04-16-2300/lib/slc6_amd64_gcc491/libFWCoreFramework.so
#12 0x00007f10d664e8b6 in edm::stream::EDProducerAdaptorBase::~EDProducerAdaptorBase (this=0x7f10f012d8e0, __in_chrg=<optimized out>) at /afs/cern.ch/cms/sw/ReleaseCandidates/vol0/slc6_amd64_gcc491/cms/cmssw-patch/CMSSW_7_5_X_2015-04-17-1100/src/FWCore/Framework/interface/stream/EDProducerAdaptorBase.h:46
#13 0x00007f10d664f140 in edm::stream::ProducingModuleAdaptor<FamosProducer, edm::stream::EDProducerBase, edm::stream::EDProducerAdaptorBase>::~ProducingModuleAdaptor (this=0x7f10f012d8e0, __in_chrg=<optimized out>) at /afs/cern.ch/cms/sw/ReleaseCandidates/vol0/slc6_amd64_gcc491/cms/cmssw-patch/CMSSW_7_5_X_2015-04-17-1100/src/FWCore/Framework/interface/stream/ProducingModuleAdaptor.h:52
#14 0x00007f10d664f170 in edm::stream::ProducingModuleAdaptor<FamosProducer, edm::stream::EDProducerBase, edm::stream::EDProducerAdaptorBase>::~ProducingModuleAdaptor (this=0x7f10f012d8e0, __in_chrg=<optimized out>) at /afs/cern.ch/cms/sw/ReleaseCandidates/vol0/slc6_amd64_gcc491/cms/cmssw-patch/CMSSW_7_5_X_2015-04-17-1100/src/FWCore/Framework/interface/stream/ProducingModuleAdaptor.h:52
```

**Comment by Martin-Grunewald** [comment]
please test

**Comment by lveldere** [comment]
Hi Martin

I cannot look into it before Monday I'm afraid.

I've had a similar issue in the recent past.
It was initiated by a missing product.
Somehow that was not handled well and
a seg fault occurs while destructing FastSim
before the error message is given...

FastSim is using the standard HF ShowerLibrary since 740pre2.

Cheers

Lukas

**Comment by lveldere** [comment]
@Martin-Grunewald 

Hi Martin

The segfaults in FastSim are fixed.
https://github.com/cms-sw/cmssw/commit/c3104fd437754375f9851ec0b9a2cb4586e1be27

Merge with
git cms-merge-topic lveldere:hlt-fastsim-collection-edits

Tested with 5.1 and 134.5

Cheers

Lukas

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
@lveldere 
Great, thanks a lot. Updated this PR and rerunning tests!

**Comment by Martin-Grunewald** [comment]
@lveldere 
Sorry, but I get a waring and a crash in the 50nsGRun fastsim example (simply use cmsDriver):

```
%MSG-w TrackListMerger:  TrackListMerger:hltPFMuonMerging  20-Apr-2015 15:12:01 CEST Run: 1 Event: 1
TrackCollection InputTag:  label = hltIter2Merged, instance =  not found
%MSG
----- Begin Fatal Exception 20-Apr-2015 15:12:01 CEST-----------------------
An exception of category 'ProductNotFound' occurred while
   [0] Processing run: 1 lumi: 1 event: 1
   [1] Running path 'HLT_FullTrack12_v1'
   [2] Calling event method for module AnalyticalTrackSelector/'hltHighPtGoodFullTracks'
Exception Message:
Principal::getByToken: Found zero products matching all criteria
Looking for type: edm::OwnVector<TrackingRecHit,edm::ClonePolicy<TrackingRecHit> >
Looking for module label: hltIter4HighPtMerged
Looking for productInstanceName:
```

**Comment by lveldere** [comment]
I'll look into it later today.
Lukas

**Comment by lveldere** [comment]
@Martin-Grunewald 

Hi Martin

The 50nsGrun error you reported is fixed in 
https://github.com/cms-sw/cmssw/commit/a90fe0522126ace9c55f064342863deaaeca51a1

Merge this into your area with
git cms-merge-topic lveldere:hlt-fastsim-collection-edits

I tested with

```
 cmsDriver.py ZEE_13TeV_TuneCUETP8M1_cfi  --conditions auto:run2_mc --fast  -n 10 --eventcontent FEVTDEBUGHLT,DQM --relval 100000,2000 -s GEN,SIM,RECOBEFMIX,DIGI:pdigi_valid,L1,L1Reco,RECO,EI,HLT:@frozen25ns,VALIDATION --datatier GEN-SIM-DIGI-RECO,DQMIO --beamspot NominalCollision2015 --customise SLHCUpgradeSimulations/Configuration/postLS1Customs.customisePostLS1 --magField 38T_PostLS1 --no_exec
```

which unfortunately leads to an error I don't understand

```
----- Begin Fatal Exception 20-Apr-2015 17:01:36 CEST-----------------------
An exception of category 'FailModule' occurred while
   [0] Processing run: 1 lumi: 1 event: 1
   [1] Running path 'HLT_DoubleMediumIsoPFTau40_Trk1_eta2p1_Reg_v1'
   [2] Calling event method for module HLTLevel1GTSeed/'hltL1sDoubleTauJet44erORDoubleJetC72'
Exception Message:

Algorithm  L1_DoubleTauJet44er, requested as seed by a HLT path, not found in the L1 trigger menu
   L1Menu_Collisions2015_25ns_v2/L1T_Scales_20141121/Imp0
Incompatible L1 and HLT menus.

----- End Fatal Exception -------------------------------------------------
```

Cheers

Lukas

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
@nclopezo
Tests seem stuck, please give it a kick.
Thanks.

**Comment by Martin-Grunewald** [comment]
+1

**Comment by nclopezo** [comment]
Hi Martin,
I restarted them.

**Comment by lveldere** [comment]
+1

@perrotta @Martin-Grunewald 

The new FastSim cfg structure #8455 will be backported to 74 the next 1 to 2 weeks.
Is this pr going to be backported as well?
At least part of it will be needed in 74 for FastSim.

Thanks for the nice cooperation btw.

**Comment by Martin-Grunewald** [comment]
@lveldere 
Backporting  #8455 to 74X would be fine to keep it in sync with 74X, so we'll then also
backport this #8753 as needed.

This is even better for me as I am working on removing the HLT FAMOS cff dumps
and generate then via python from the data/fullSim cff dumps on the fly - this is in
the long run, but FastSim technical structure then being the same between 74X and
75X  means I only need to solve one problem once!
This feature be require support from you and fastsim experts, but would allow
you and us to test fastsim issues without extracting the dump from the database
runnung the infamous confdb.oy (cf the issues over the last days)

**Comment by lveldere** [comment]
Thanks Martin

On Tue, Apr 21, 2015 at 11:55 AM, Martin Grunewald <notifications@github.com
> wrote:

> @lveldere <https://github.com/lveldere>
> Backporting #8455 <https://github.com/cms-sw/cmssw/pull/8455> to 74X
> would be fine to keep it in sync with 74X, so we'll then also
> backport this #8753 <https://github.com/cms-sw/cmssw/pull/8753> as needed.
>
> This is even better for me as I am working on removing the HLT FAMOS cff
> dumps
> and generate then via python from the data/fullSim cff dumps on the fly -
> this is in
> the long run, but FastSim technical structure then being the same between
> 74X and
> 75X means I only need to solve one problem once!
> This feature be require support from you and fastsim experts, but would
> allow
> you and us to test fastsim issues without extracting the dump from the
> database
> runnung the infamous confdb.oy (cf the issues over the last days)
>

That sounds great. I'd be happy to help with that when the rush for the
run2 simulations is over.

**Comment by Martin-Grunewald** [comment]
@franzoni @civanch 
Ping - could you please sign for operations?

**Pull request merged**
