### PR TITLE
xml file for me0 with 6 eta partitions

### PR DESCRIPTION
**Pull request by pietverwilligen**
follow up of #17770 now submitted for integration in 91X

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
+1

a new file which is not included in relval tests

**Comment by calabria** [comment]
can we have this PR integrated asap? this option will serve as a backup, but it is better if it is available in the release. Thanks.

**Comment by ianna** [comment]
@davidlange6 - please, include it in IBs

**Comment by davidlange6** [comment]
+1

**Pull request merged**
