### PR TITLE
Utilities/StaticAnalyzers: Check for CMS_THREAD_SAFETY or CMS_SA_ALLOW attributes on statments using const_cast and skip warnings.

### PR DESCRIPTION
**Pull request by gartung**
This adds a veto on ConstCastChecker and ConstCastAwayChecker using the CMS_THREAD_SAFETY or CMS_SA_ALLOW attributes at the beginning of statements using const_cast or casting const away.

For example 

```
--- a/FWCore/Framework/src/EventSetupRecordIntervalFinder.cc
+++ b/FWCore/Framework/src/EventSetupRecordIntervalFinder.cc
@@ -12,6 +12,7 @@
 
 #include "FWCore/Framework/interface/EventSetupRecordIntervalFinder.h"
 #include "FWCore/Utilities/interface/Likely.h"
+#include "FWCore/Utilities/interface/thread_safety_macros.h"
 #include <cassert>
 #include <mutex>
 
@@ -67,7 +68,7 @@ namespace edm {
   std::set<EventSetupRecordKey> EventSetupRecordIntervalFinder::findingForRecords() const {
     if (intervals_.empty()) {
       //we are delaying our reading
-      const_cast<EventSetupRecordIntervalFinder*>(this)->delaySettingRecords();
+      CMS_SA_ALLOW const_cast<EventSetupRecordIntervalFinder*>(this)->delaySettingRecords();
     }

```
removes the warning about the use of const_cast.

Tested locally.

### CODE REVIEW

**Comment by gartung** [comment]
@makortel

**Comment by gartung** [comment]
please test

**Comment by makortel** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
