### PR TITLE
[12_5_X] EMTF Primitive Conversion LUT update

### PR DESCRIPTION
**Pull request by eyigitba**
#### PR description:

This is a backport of https://github.com/cms-sw/cmssw/pull/39822

This PR adds options to use the new primitive conversion LUTs in the EMTF emulator. The LUTs were deployed at P5 on October 6th, but they are not used in the emulator yet. 

This PR needs the LUTs in https://github.com/cms-data/L1Trigger-L1TMuon/pull/23 to work.

We see improvement in EMTF performance at P5 with these new LUTs, so changes to muon efficiencies etc are expected when testing the re-emulation workflows from recent runs (after October 6th). Otherwise this PR shouldn't change anything in the emulator.

This PR should be backported to 12_4 if there is an opportunity to run this at P5 to improve data/emulator comparisons in DQM. If data taking with 12_5 is expected we should also backport it there. 

This has no effect on MC production so MC campaigns do not matter for the purpose of this PR.

#### PR validation:

Validated with the workflow from https://github.com/cms-sw/cmssw/pull/39822#issuecomment-1290545788 since the regular test workflows are not useful for this PR. 

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

https://github.com/cms-sw/cmssw/pull/39822

### CODE REVIEW

**Comment by cecilecaillol** [comment]
please test

**Comment by cecilecaillol** [comment]
+l1

**Comment by perrotta** [comment]
backport of https://github.com/cms-sw/cmssw/pull/39822

**Comment by perrotta** [comment]
please test with https://github.com/cms-sw/cmsdist/pull/8142

**Comment by perrotta** [comment]
+1
- It improves data/emulator comparison in DQM

**Pull request merged**
