### PR TITLE
ME0 re-digitizer module

### PR DESCRIPTION
**Pull request by dildick**
This module re-digitizes the ME0 pseudo digis. It smears and discretizes the timing position. It is included only in Phase2 digitization sequences. 

Note: To be integrated after #16185. I will rebase on top of most recent build after #16185 is integrated.

### CODE REVIEW

**Comment by slava77** [comment]
@dildick @pietverwilligen 
should this PR supersede #16185 or should the merge of #16185 be removed from this PR?

**Comment by dildick** [comment]
I merged #16185 to test my code. The merge can be removed. I can also rebase after #16185 is merged.

**Comment by slava77** [comment]
-1
the PR looks premature

**Comment by dildick** [comment]
@slava77 It turns out that my additions do compile without #16185. I removed all #16185 commits.

**Comment by Dr15Jones** [comment]
+1
for Core, only added entry to RandomNumberService

**Comment by dildick** [comment]
ME0ReDigiProducer was not registered. I tested WFs 20024.0 and 22424.0 again. Both were successful.

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by dildick** [comment]
Hi, please let me know if more work is need for this PR. Thanks.

**Comment by Dr15Jones** [comment]
+1
Just adding another random number engine

**Comment by dildick** [comment]
Can this pull request be integrated, please? Thanks!

**Comment by davidlange6** [comment]
+1
though hopefully this module has a very short lifetime.

**Pull request merged**
