### PR TITLE
Memory efficient implementation of timing information for HGCDigitizer module for Premix Workflow.

### PR DESCRIPTION
**Pull request by abhishek-das-mahant**
#### PR description:

<The HGCDigitizer module, in it's current form, store timing information of all the incoming hits from the minbias events  in PreMixStage1 of the Premix Workflow. This PR aims to drop the timing information from redundant hits from the minbias events, once a HGCal cell reaches it's fire-off threshold of accumulated charge. 

I found the PR to improve the performance of the code in terms of CPU performance, reduced memory and disk usage. The quantitative figures are mentioned below -
**CPU Performance -** 
For BaseLine Igprof summary, I got the following

       88.1  ...............  211'531'179'858 / 211'531'179'858    1'008'942'599 / 1'008'942'599      edm::BMixingModule::produce(edm::Event&, edm::EventSetup const&) [16]
        2.3  ...............    5'484'689'754 / 5'484'689'754             13'591 / 13'591             edm::PoolOutputModule::write(edm::EventForOutput const&) [201]

###############################################################################
And for the new Premix method, I got

       80.8  ...............  109'380'472'943 / 109'380'472'943      957'052'716 / 957'052'716        edm::BMixingModule::produce(edm::Event&, edm::EventSetup const&) [16]
        2.2  ...............    2'970'142'735 / 2'970'142'735             11'298 / 11'298             edm::PoolOutputModule::write(edm::EventForOutput const&) [280]

**Disk Usage -**

PHGCSimAccumulator_simHGCalUnsuppressedDigis_EE_DIGI. 2.57756e+08 4.29255e+06
PHGCSimAccumulator_simHGCalUnsuppressedDigis_HEfront_DIGI. 3.5771e+07 621998
PHGCSimAccumulator_simHGCalUnsuppressedDigis_HEback_DIGI. 7.30215e+06 119472

For my new method, disk usage

PHGCSimAccumulator_simHGCalUnsuppressedDigis_EE_DIGI. 6.85587e+07 4.08996e+06
PHGCSimAccumulator_simHGCalUnsuppressedDigis_HEfront_DIGI. 6.34798e+06 333652
PHGCSimAccumulator_simHGCalUnsuppressedDigis_HEback_DIGI. 760055 51035.3

**MemoryInfo-**

FOr the addPileup method, the new proposed procedure uses almost an order of magnitude less memory(as shown in the attached screenshot; Black background screenshot- Baseline method, White background screenshot- My new method
BaseLine
NewPreMix

)

 >

#### PR validation:

<I ran a validation test by comparing results from WorkFlow # 20634.0(standard mix) and # 20634.99(premix) using custom validation package here - https://github.com/amartelli/HGCTimingAnalysis/tree/TimingAnalysis_11_1_X >

### CODE REVIEW

**Comment by kpedro88** [comment]
please test

**Comment by civanch** [comment]
please test

**Comment by adas1994** [comment]
@kpedro88 , In my last PR on the similar topic , you suggested running 2 different phase 2 upgrade test workflows, which are usually not included in the standard test set. I don't remember the workflow numbers. If you do, could you run them also, please?

**Comment by kpedro88** [comment]
@adas1994 one of those workflows is no longer necessary. I just realized the other workflow (premixing) was accidentally omitted during a recent cleanup, so I have to re-add it.

**Comment by adas1994** [comment]
> @adas1994 one of those workflows is no longer necessary. I just realized the other workflow (premixing) was accidentally omitted during a recent cleanup, so I have to re-add it.

Okay, please let me know once you re-introduce the workflow and give it a test run. Appreciate the help, @kpedro88 .

**Comment by kpedro88** [comment]
The re-added workflows are in #30875

**Comment by kpedro88** [comment]
@adas1994 some thoughts and questions as I look over the code:
* what impact does this have on the CPU usage and memory usage of the premix stage 1 step, and on the file size of the premixed output?

The idea is quite nice, and the code comments are useful to follow the steps of the algorithm as implemented. I'm concerned, though, that the implementation contains some linear operations like `insert()` inside a loop over hits.

It might be more CPU-efficient to make each `PhitRefs_bx0[id]` into a map (sorted by time), and then after all the hits are in the map, step through the map just once, in order, accumulating charge and checking the threshold. This would come at the expense of some increased memory usage while the process is running. (I'm not completely sure if this would be faster, but it might be worth checking.) Alternatively, the existing vectors could just be sorted once, after all the hits are added (and then loop through to accumulate and check thresholds).

**Comment by adas1994** [comment]
> @adas1994 some thoughts and questions as I look over the code:
> 
>     * what impact does this have on the CPU usage and memory usage of the premix stage 1 step, and on the file size of the premixed output?
> 
> 
> The idea is quite nice, and the code comments are useful to follow the steps of the algorithm as implemented. I'm concerned, though, that the implementation contains some linear operations like `insert()` inside a loop over hits.
> 
> It might be more CPU-efficient to make each `PhitRefs_bx0[id]` into a map (sorted by time), and then after all the hits are in the map, step through the map just once, in order, accumulating charge and checking the threshold. This would come at the expense of some increased memory usage while the process is running. (I'm not completely sure if this would be faster, but it might be worth checking.) Alternatively, the existing vectors could just be sorted once, after all the hits are added (and then loop through to accumulate and check thresholds).

@kpedro88 I did not quantify the improvement in term of memory, but I am pretty sure that it is theoretically bound to store less data in the intermediate step, as I am discarding the timing info after the accumulated charge reaches threshold. 

Secondly, I have made a number of attempts to get around using `insert()` in the inner loop and try out some other data structure like `std::map`, which are  inherently ordered. But I was unsuccessful. I will see again what I can do about it.

As per other concerns, let me ping back to you tomorrow. I will see if I can address some/all of them.

**Comment by kpedro88** [comment]
please test workflow 23434.99

**Comment by kpedro88** [comment]
please test workflow 23434.99

**Comment by adas1994** [comment]
> > @adas1994 some thoughts and questions as I look over the code:
> > ```
> > * what impact does this have on the CPU usage and memory usage of the premix stage 1 step, and on the file size of the premixed output?
> > ```
> > 
> > 
> > The idea is quite nice, and the code comments are useful to follow the steps of the algorithm as implemented. I'm concerned, though, that the implementation contains some linear operations like `insert()` inside a loop over hits.
> > It might be more CPU-efficient to make each `PhitRefs_bx0[id]` into a map (sorted by time), and then after all the hits are in the map, step through the map just once, in order, accumulating charge and checking the threshold. This would come at the expense of some increased memory usage while the process is running. (I'm not completely sure if this would be faster, but it might be worth checking.) Alternatively, the existing vectors could just be sorted once, after all the hits are added (and then loop through to accumulate and check thresholds).
> 
> @kpedro88 I did not quantify the improvement in term of memory, but I am pretty sure that it is theoretically bound to store less data in the intermediate step, as I am discarding the timing info after the accumulated charge reaches threshold.
> 
> Secondly, I have made a number of attempts to get around using `insert()` in the inner loop and try out some other data structure like `std::map`, which are inherently ordered. But I was unsuccessful. I will see again what I can do about it.
> 
> As per other concerns, let me ping back to you tomorrow. I will see if I can address some/all of them.

@kpedro88 , I looked into your suggestions in detail and thought about it. It is possible to approach this charge-accumulation process the way you have suggested.

Now, it could require quite higher memory usage as you put it; and it will also be "inconsistent" with the way things are done in accumulate member function here : https://github.com/adas1994/cmssw/blob/MemoryEfficient_Implementation_HGCdigitizer_PreMix/SimCalorimetry/HGCalSimProducers/src/HGCDigitizer.cc#L634

In it's current form, my `accumulate_forPremix()` function closely follows the `accumulate()`(which, I think Arabella wrote, most possibly) function. So, here is what I would suggest - I would modify both my `accumulate_forPremix()` and `accumulate()` functions and try to do a quantitative study on memory-CPU time trade off in a different PR effort within a couple months from now? And you let this PR through if the comparisons are alright?

**Comment by kpedro88** [comment]
@adas1994 thanks for the pointer to `accumulate()`: I either didn't realize or had forgotten that algorithm also used `insert()`. Given that, I agree this PR can go forward in its current form, with possible algorithm improvements for both cases coming in a later PR.

However, it would still be good to quantify the CPU, memory, and disk usage of this current PR compared to the baseline.

**Comment by adas1994** [comment]
> @adas1994 thanks for the pointer to `accumulate()`: I either didn't realize or had forgotten that algorithm also used `insert()`. Given that, I agree this PR can go forward in its current form, with possible algorithm improvements for both cases coming in a later PR.
> 
> However, it would still be good to quantify the CPU, memory, and disk usage of this current PR compared to the baseline.

@kpedro88  What would you use to do the CPU performance study, igprof or Arm-map profiler? Sorry, it has been a while and I have forgotten how to use both, but I can look back. Or, can this CPU performance quantification be done using cmsbuild testkit itself?

**Comment by kpedro88** [comment]
I personally use igprof for detailed studies, but to start, you can use [TimeMemoryInfo](https://github.com/cms-sw/cmssw/blob/master/Validation/Performance/python/TimeMemoryInfo.py) to track the CPU and memory usage.

**Comment by civanch** [comment]
+1

**Comment by adas1994** [comment]
@kpedro88 , I ran igprof profiler on my old and new premix method. But the output files are each ~43 MB big. Do you want me to post them here? Or I remember you had a nice summarizer script that would run on these output-files and make a much shorter summary. Do you want me to run that?

**Comment by kpedro88** [comment]
@adas1994 yes, you can run the script as described here: https://github.com/kpedro88/utilities#runigprofsh

the memory and disk usage should be easy to summarize

**Comment by adas1994** [comment]
For BaseLine Igprof summary, I got the following -
           88.1  ...............  211'531'179'858 / 211'531'179'858    1'008'942'599 / 1'008'942'599      edm::BMixingModule::produce(edm::Event&, edm::EventSetup const&) [16]
            2.3  ...............    5'484'689'754 / 5'484'689'754             13'591 / 13'591             edm::PoolOutputModule::write(edm::EventForOutput const&) [201]

###############################################################################
And for the new Premix method, I got 

           80.8  ...............  109'380'472'943 / 109'380'472'943      957'052'716 / 957'052'716        edm::BMixingModule::produce(edm::Event&, edm::EventSetup const&) [16]
            2.2  ...............    2'970'142'735 / 2'970'142'735             11'298 / 11'298             edm::PoolOutputModule::write(edm::EventForOutput const&) [280]

As you suggested @kpedro88

**Comment by kpedro88** [comment]
@adas1994 thanks, this shows a CPU reduction in both the mixing and output. Please provide memory and disk usage results as well.

Looking deeper in the full igprof reports that you sent me, the reduction indeed comes from HGCDigiProducer:
old:
```
[25]       23.3   56'046'625'928                0 / 56'046'625'928               415                    HGCDigiProducer::finalizeEvent(edm::Event&, edm::EventSetup const&)
```
new:
```
[40]       10.2   13'876'059'840                0 / 13'876'059'840        68'734'400                    HGCDigiProducer::finalizeEvent(edm::Event&, edm::EventSetup const&)
```

**Comment by adas1994** [comment]
> @adas1994 thanks, this shows a CPU reduction in both the mixing and output. Please provide memory and disk usage results as well.
> 
> Looking deeper in the full igprof reports that you sent me, the reduction indeed comes from HGCDigiProducer:
> old:
> 
> ```
> [25]       23.3   56'046'625'928                0 / 56'046'625'928               415                    HGCDigiProducer::finalizeEvent(edm::Event&, edm::EventSetup const&)
> ```
> 
> new:
> 
> ```
> [40]       10.2   13'876'059'840                0 / 13'876'059'840        68'734'400                    HGCDigiProducer::finalizeEvent(edm::Event&, edm::EventSetup const&)
> ```

Cool. Glad to see it. Let me know if there is any other issues.

**Comment by kpedro88** [comment]
@adas1994 please provide memory and disk usage results

**Comment by adas1994** [comment]
> @adas1994 please provide memory and disk usage results

Should I use some other argument while running the runIgprof.sh to get memory and disk usage? I am not sure how to get additional information other than what I have already gave you...

**Comment by kpedro88** [comment]
My runIgprof.sh script only handles CPU usage.

For memory usage, you can use [TimeMemoryInfo](https://github.com/cms-sw/cmssw/blob/master/Validation/Performance/python/TimeMemoryInfo.py) in your config, as I mentioned previously.

For disk usage, just look at the output root files with `edmEventSize`.

**Comment by adas1994** [comment]
> My runIgprof.sh script only handles CPU usage.
> 
> For memory usage, you can use [TimeMemoryInfo](https://github.com/cms-sw/cmssw/blob/master/Validation/Performance/python/TimeMemoryInfo.py) in your config, as I mentioned previously.
> 
> For disk usage, just look at the output root files with `edmEventSize`.

For the Baseline Premix method, disk usage - 

PHGCSimAccumulator_simHGCalUnsuppressedDigis_EE_DIGI. 2.57756e+08 4.29255e+06
PHGCSimAccumulator_simHGCalUnsuppressedDigis_HEfront_DIGI. 3.5771e+07 621998
PHGCSimAccumulator_simHGCalUnsuppressedDigis_HEback_DIGI. 7.30215e+06 119472
For my new method, disk usage


PHGCSimAccumulator_simHGCalUnsuppressedDigis_EE_DIGI. 6.85587e+07 4.08996e+06
PHGCSimAccumulator_simHGCalUnsuppressedDigis_HEfront_DIGI. 6.34798e+06 333652
PHGCSimAccumulator_simHGCalUnsuppressedDigis_HEback_DIGI. 760055 51035.3

**Comment by adas1994** [comment]
For TimeMemoryInfo, I am posting 2 screenshots. The black-background screenshot is for the Baseline method. And the White-background screenshot is for my new Premix method.
BaseLine
NewPreMix

**Comment by kpedro88** [comment]
@adas1994 thanks for these numbers, it's good to document the memory and disk space reduction.

Just one more thing: when you ran the validation test, did you see that the plots were identical? Or were there changes in the results?

**Comment by adas1994** [comment]
> @adas1994 thanks for these numbers, it's good to document the memory and disk space reduction.
> 
> Just one more thing: when you ran the validation test, did you see that the plots were identical? Or were there changes in the results?
I found the histograms to be more-or-less identical.

**Comment by kpedro88** [comment]
@adas1994 if they're not 100% identical, it would be good to post them in this PR as part of the documentation.

Can you also update the PR description with the CPU, memory, and disk usage info?

**Comment by adas1994** [comment]
> @adas1994 if they're not 100% identical, it would be good to post them in this PR as part of the documentation.
> 
> Can you also update the PR description with the CPU, memory, and disk usage info?

Will do right now.

**Comment by adas1994** [comment]
> > @adas1994 if they're not 100% identical, it would be good to post them in this PR as part of the documentation.
> > Can you also update the PR description with the CPU, memory, and disk usage info?
> 
> Will do right now.

Done.

**Comment by kpedro88** [comment]
Thanks! Please also post the validation plots (or a link to a PDF) in the PR description.

**Comment by adas1994** [comment]
@kpedro88 , I was kind of hoping that the validation plots from the special Phase 2 workflow that you ran would suffice for validation. If I would have to produce formal plots for validation, it might take days, because I will be fully occupied the rest of the week. Is it absolutely necessary to produce plots from my side? Because they are not generated by standardized validation tests....it was developed by Arabella.

**Comment by kpedro88** [comment]
@adas1994 in the PR description, you stated that you had already run the validation package. Can't you just post those results?

The premixing results currently aren't included in the standard PR comparison tests (maybe this should change).

**Comment by adas1994** [comment]
> @adas1994 in the PR description, you stated that you had already run the validation package. Can't you just post those results?
> 
> The premixing results currently aren't included in the standard PR comparison tests (maybe this should change).

I had tested on ~50 events, each with 200 PU. Give me a few days then, I will run this stuff on a few thousands events on condor and post the plots.

**Comment by adas1994** [comment]
@kpedro, as you suggetsed, I am uploading some illustrative plots(they are from 4760 Single Kaon event with fixed number of 200 Pileups) for stdmix and premix.
[New_HGCalTimingAnalysis.pdf](https://github.com/cms-sw/cmssw/files/4999817/New_HGCalTimingAnalysis.pdf)

**Comment by kpedro88** [comment]
@adas1994 please be careful who you tag on GitHub (I'm @kpedro88)

The plots mostly look reasonable. The h_Vtx_dvx,dvy,dvz plots seem very different between standard mixing and premixing, though.

Since this PR specifically changes premixing, it might be a more direct comparison to make the same plots from the premixing workflow before and after this PR.

**Comment by adas1994** [comment]
> @adas1994 please be careful who you tag on GitHub (I'm @kpedro88)
> 
> The plots mostly look reasonable. The h_Vtx_dvx,dvy,dvz plots seem very different between standard mixing and premixing, though.
> 
> Since this PR specifically changes premixing, it might be a more direct comparison to make the same plots from the premixing workflow before and after this PR.

@kpedro88 The comparison between baseline premix method and my new premix method shouldn't matter, given a comparison between standard mix and new premix, because when I wrote the baseline premix method, ultimately I had to compare the plots to the standardmix then also. I directly went for this comparison because A. this comparison is more robust and B. I have a stupid bug in my condor job submission script that is hard to find and somehow causing the the baseline premix method to fail there.

But the plots attached sort of establishes that this PR should be clean to go forward.

**Comment by kpedro88** [comment]
The comparison between classical mixing and premixing is more robust from a physics standpoint. For a technical PR, though, it can be more useful to have the direct comparison before and after the PR.

Do you understand the behavior of the h_Vtx_dvx,dvy,dvz plots?

**Comment by adas1994** [comment]
> The comparison between classical mixing and premixing is more robust from a physics standpoint. For a technical PR, though, it can be more useful to have the direct comparison before and after the PR.
> 
> Do you understand the behavior of the h_Vtx_dvx,dvy,dvz plots?

Those plots come from the trackingvertices in an event and therefore probably their behavior is mixing procedure specific. I don't think we need to be bothered about them. I am posting it here(but as you'll see more descriptive plots are missing for the baseline premix methods for unknown reason.
[BaseLineVsNewHGCalTimingAnalysis.pdf](https://github.com/cms-sw/cmssw/files/5002814/BaseLineVsNewHGCalTimingAnalysis.pdf)
)

**Comment by kpedro88** [comment]
Okay, at least the few plots that are filled there show reasonable agreement...

**Comment by adas1994** [comment]
> Okay, at least the few plots that are filled there show reasonable agreement...

I am so glad to hear it !! And I hope there is no other issues...

**Comment by kpedro88** [comment]
@adas1994 I'm going to add a premixing workflow to the regular PR tests. This will produce the comparison plots automatically. Hopefully that can all converge in the next ~day, and then I will be able to approve this PR.

**Comment by adas1994** [comment]
> @adas1994 I'm going to add a premixing workflow to the regular PR tests. This will produce the comparison plots automatically. Hopefully that can all converge in the next ~day, and then I will be able to approve this PR.

Okay. But I couldn't understand one thing...didn't you already run this extra workflow after re-introducing it to the CMSSW(as it was erased earlier by mistake)? Or it's a different thing?

**Comment by kpedro88** [comment]
I ran the workflow to make sure it would run successfully, but without adding it to the default PR tests, the baseline plots aren't stored, so the comparison plots can't be generated.

**Comment by adas1994** [comment]
> I ran the workflow to make sure it would run successfully, but without adding it to the default PR tests, the baseline plots aren't stored, so the comparison plots can't be generated.

Okay, so I am guessing that not much left here to do on my part in this PR. Btw, @kpedro88 I have a question not necessarily related to this PR. Is it mainstream that developers look for open issues in CMSSW github and pick up issues to work on by their own, or does one have to go through some-kind-of-approval-process to work on something? For example, if I want to work on Open Issue #30968 , do I need to talk to people or am I allowed to just get started ?

**Comment by kpedro88** [comment]
Anyone is welcome to work on any open issue*. To avoid duplicating effort, if you are starting to work on a certain issue, you may want to add a comment to that effect (so others are aware).

* of course, if the solution has some impact on physics performance, it may require validation and approval by the appropriate DPG or POG, as usual.

**Comment by adas1994** [comment]
> @adas1994 I'm going to add a premixing workflow to the regular PR tests. This will produce the comparison plots automatically. Hopefully that can all converge in the next ~day, and then I will be able to approve this PR.

Any update on this, @kpedro88 ?

**Comment by kpedro88** [comment]
The PR for that is #30988. It became a bit more involved than initially expected, but hopefully it can be merged soon.

**Comment by kpedro88** [comment]
please test

**Comment by kpedro88** [comment]
+upgrade
changes in premix workflow output not detectable at the 10 event level

**Comment by silviodonato** [comment]
+1

**Pull request merged**
