### PR TITLE
Adding parameters needed for PUjetID 94X and 102X v2

### PR DESCRIPTION
**Pull request by alefisico**
#### PR description:

 - Including the files and parameters needed for the latest PUjetID training for 94X and 102X samples.
 - Once merged, we need to backport this PR to the corresponding CMSSW release for the latest nanoAOD.
 - There is also a PR for the new weights for PUJetID cms-data/RecoJets-JetProducers#10 (comment)

This PR superseeds #28827.
Expected changes with this PR: https://indico.cern.ch/event/860457/#17-pujetid-training-and-valida 

FYI: @ahinzmann @lathomas  @camclean

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by alefisico** [comment]
I think this test will fail because this PR https://github.com/cms-data/RecoJets-JetProducers/pull/10 needs to be included.

**Comment by slava77** [comment]
test parameters
- pull_request = cms-data/RecoJets-JetProducers#10

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
the bot is apparently asleep
I received a notice of commit 0e644b8 just about 2 hours ago.

@smuzaffar @mrodozov 
please check

**Comment by smuzaffar** [comment]
currently there is network issue at CERN ( https://hypernews.cern.ch/HyperNews/CMS/get/cernCompAnnounce/1405.html ) so bot is not receiving any updates.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by lathomas** [comment]
Hello,  
For the record the changes in the PU ID output now look as expected. 
 https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_11_1_X_2020-02-19-2300+0ba9ea/35177/validateJR/all_OldVSNew_RunJetHT2017FreMINIAODwf136p8311/all_OldVSNew_RunJetHT2017FreMINIAODwf136p8311c_patJets_slimmedJets__PAT_obj___userFloats__3_.png

**Comment by slava77** [comment]
@alefisico 
please edit the PR description to add a link to some slides showing expected changes in performance.

https://twiki.cern.ch/twiki/bin/viewauth/CMS/PileupJetID  points to https://indico.cern.ch/event/860457/#17-pujetid-training-and-valida . I'm guessing it's the latest on this subject.

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/28984	0e644b8 
- code changes are in line with the PR description and the follow up review [most of the review history was in #28827] 
- jenkins tests pass and comparisons with the baseline show differences only in jet PU ID variables. The changes look roughly as expected from https://indico.cern.ch/event/860457/#17-pujetid-training-and-valida and were confirmed to be as expected earlier in https://github.com/cms-sw/cmssw/pull/28984#issuecomment-589508052

**Comment by silviodonato** [comment]
+1

**Pull request merged**
