### PR TITLE
Delete deprecated scripts accessing geometry with prior-run2 GT in Calibration/Hcal

### PR DESCRIPTION
**Pull request by yuanchao**
#### PR description:

Following up the migration of Geometry_cff to GeometryDB_cff (https://github.com/cms-sw/cmssw/pull/35278), proper GlobalTag needs to be set in advance. We take the chance to clean up AlCa/DB related scripts that accessing with prior-run2 GT in Calibration/HcalAlCaRecoProducers and Calibration/HcalCalibAlgos.

#### PR validation:

Delete deprecated script that can't be tested with modern geometry.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Not a back port and no back port expected.

### CODE REVIEW

**Comment by tvami** [comment]
@yuanchao please squash the commits

**Comment by tvami** [comment]
@bsunanda please have a look at this PR, and if you disagree with the cleaning, please provide new configs that work, and possibly make them into unit tests, thanks!

**Comment by tvami** [comment]
type hcal

**Comment by tvami** [comment]
thanks @bsunanda !

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
+alca
 * agreed by HCAL as well

**Comment by qliphy** [comment]
+1

**Pull request merged**
