### PR TITLE
Remove redundant unique_ptr constructor calls from FastSimulation

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

Cleanup follow-up to #27097.

#### PR validation:

Code compiles.

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by fabiocos** [comment]
This needs to be rebased as well...

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by fabiocos** [comment]
@ssekmen this PR looks ok to me, I will merge it in next IB. Please check and comment in case.

**Comment by ssekmen** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
