### PR TITLE
change default cmsRun to use python3. 

### PR DESCRIPTION
**Pull request by davidlange6**
And Remove now obsolete FWCore/PyDevParameterSet package

### CODE REVIEW

**Comment by davidlange6** [comment]
test parameters:
  - full_cmssw = true

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
test_parameters:

**Comment by davidlange6** [comment]
please test

**Comment by smuzaffar** [comment]
test parameters:

**Comment by smuzaffar** [comment]
please test
re-start the tests as there was a typo in last "test_parameters"

**Comment by davidlange6** [comment]
ok, great - the unit tests passed this time.

**Comment by davidlange6** [comment]
please test

**Comment by makortel** [comment]
@davidlange6 The "Reco comparison" differences seem to be in slimmed jets `pairDiscriVector`. Do you know if these are caused by element order in dictionaries (e.g. `cms.PSet`) changing between py2 and py3?

**Comment by davidlange6** [comment]
iirc, they are caused by the reco comparison scripts assuming that keys come out of a dict in a certain order.

**Comment by makortel** [comment]
I inspected the MiniAOD file from the reference and the PR test for workflow 4.53, and indeed the order of elements in `pairDiscriVector` are different between the two. The full PY3 release has passed validation.

**Comment by makortel** [comment]
+1

**Comment by makortel** [comment]
urgent

@qliphy @perrotta @silviodonato As mentioned in ORP, it would be useful to have this PR in pre4

**Comment by qliphy** [comment]
+1

**Pull request merged**
