### PR TITLE
Register FlatRandomPtAndDxyGunProducer in Sealmodule

### PR DESCRIPTION
**Pull request by dildick**
@calabria @kpedro88

### CODE REVIEW

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by kpedro88** [comment]
bugfix for #17775

**Comment by kpedro88** [comment]
assign upgrade

**Comment by perrozzi** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
