### PR TITLE
Modernized GenTtbarCategorizer

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:
- converted to edm::global::EDProducer
- filled in fillDescriptions

#### PR validation:

Code compiles.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
This fixes the step5 case in #25090

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
@silviodonato 
> for my education, should we also remove the _cfi.py file https://github.com/cms-sw/cmssw/blob/master/TopQuarkAnalysis/TopTools/python/GenTtbarCategorizer_cfi.py ?

I think that would be best, yes.

**Comment by silviodonato** [comment]
Ok, I created #30193

**Pull request merged**
