### PR TITLE
Update 2024 geometry and GEM alignment conditions in 2024 MC GTs

### PR DESCRIPTION
**Pull request by saumyaphor4252**
#### PR description:
The PR updates the 2024 geometry and compatible GEM alignment conditions tags in the relevant MC GTs:
- `140X_mcRun3_2024_design_v6`
- `140X_mcRun3_2024_realistic_v7`
- `140X_mcRun3_2024cosmics_realistic_deco_v7`
- `140X_mcRun3_2024cosmics_design_deco_v5`
- `141X_mcRun3_2024_realistic_HI_v2`

More details with the full list of tag updates and links to relevant presentations can be found in the CMS Talk request in [1]. 

FYI @bsunanda @watson-ij @hyunyong @mrcthiel @jhgoh 

An additional key `phase1_2024_realistic_hi` is added in preparation for the 2024 HI MC GT. The key is not consumed anywhere at this point of time but can be used once new workflows for 2024 HI are included. 

[1] https://cms-talk.web.cern.ch/t/gt-mc-data-update-of-2024-gem-and-rpc-geomtery-conditions-for-data-and-mc/36739

**GT Differences with the last ones are here**:

- **Phase1 2024 design**: 
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/140X_mcRun3_2024_design_v3/140X_mcRun3_2024_design_v6

- **Phase1 2024 realistic**: 
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/140X_mcRun3_2024_realistic_v4/140X_mcRun3_2024_realistic_v7
- **Phase1 2024 cosmics realistic**:
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/140X_mcRun3_2024cosmics_realistic_deco_v4/140X_mcRun3_2024cosmics_realistic_deco_v7

- **Phase1 2024 cosmics design**: 
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/140X_mcRun3_2024cosmics_design_deco_v2/140X_mcRun3_2024cosmics_design_deco_v5

- **Phase1 2024 realistic hi**:
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/141X_mcRun3_2024_realistic_HI_v1/141X_mcRun3_2024_realistic_HI_v2 

#### PR validation:
Since there are limited 2024 workflows for testing all the changed GT keys, one GT each (realistic and design) has been tested using the existing 2024 realistic workflows: 
- `runTheMatrix.py -l 13050.0,13049.0,13046.0,13045.0,13040.0,12933.0,12841.0,12802.0,12824.0,12834.1,13052.0 --what upgrade -j 10 --ibeos`
- `runTheMatrix.py -l 13050.0,13049.0,13046.0,13045.0,13040.0,12933.0,12841.0,12802.0,12824.0,12834.1,13052.0 --what upgrade -j 10 --ibeos --command "--conditions 140X_mcRun3_2024_design_Candidate_2024_03_20_16_03_10"`

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Not a backport. Backport to 140X will be needed

### CODE REVIEW

**Comment by saumyaphor4252** [comment]
test parameters:
- workflows = 13050.0,13049.0,13046.0,13045.0,13040.0,12933.0,12841.0,12802.0,12824.0,12834.1,13052.0
- relvals_opt = --what upgrade,standard

**Comment by saumyaphor4252** [comment]
@cmsbuild please test

**Comment by perrotta** [comment]
The error in wf 13045 is unrelated, and a fix for it (affecting Generators) is now available in https://github.com/cms-sw/cmssw/pull/44499
Let retest this PR without that unrelatedly failing workflow

**Comment by perrotta** [comment]
test parameters:
- workflows = 13050.0,13049.0,13046.0,13040.0,12933.0,12841.0,12802.0,12824.0,12834.1,13052.0
- relvals_opt = --what upgrade,standard

**Comment by perrotta** [comment]
please test

**Comment by mmusich** [comment]
Screenshot from 2024-03-21 21-42-12

isn't the new naming schema a bit unorthodox (there's not even `Geometry` in the tag name) ?

**Comment by saumyaphor4252** [comment]
please test

**Comment by perrotta** [comment]
The unit test fails supposedly because https://github.com/cms-sw/cmssw/pull/44473 was picked on top of CMSSW_14_1_X_2024-03-21-2300 without the necessary accompanying cmsdist update, see https://github.com/cms-sw/cmssw/pull/44497#issuecomment-2015953596
Let relaunch the tests now in a fresher IB which contain both the cmssw and cmsdist PRs merged

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
urgent
(to be included in the pre-release planned for March 26)

**Comment by mmusich** [comment]
> Well that's what was provided to us.

I think it should have been asked to provide better tag names in the cmsTalk, well before cutting Global Tags

> Huge differences as expected from the geometry updates in the concerned 2024 MC workflows

out of curiosity, do we understand why certain 2024 wfs (e.g. [13049.0 overlay GUI](https://cmsweb.cern.ch/dqm/dev/start?runnr=1;dataset%3D/RelVal_wf13049_0_pr/CMSSW_14_1_X-PRcmssw_44497-61894/DQMIO;referenceshow%3Dall;referencenorm=False;referenceobj1%3Dother::/RelVal_wf13049_0_base/CMSSW_14_1_X-PRcmssw_44497-61894/DQMIO::;sampletype%3Doffline_relval;workspace%3DEverything;) or [12933.0 overlay GUI](https://cmsweb.cern.ch/dqm/dev/start?runnr=1;dataset%3D/RelVal_wf12933_0_pr/CMSSW_14_1_X-PRcmssw_44497-61894/DQMIO;referenceshow%3Dall;referencenorm=False;referenceobj1%3Dother::/RelVal_wf12933_0_base/CMSSW_14_1_X-PRcmssw_44497-61894/DQMIO::;sampletype%3Doffline_relval;workspace%3DEverything;) ) instead have only moderate changes (and all in the GEM folder)?

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
