### PR TITLE
Changed binary to logical operation in OptimalHelixPlaneCrossing

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

This got rid of a clang warning.

#### PR validation:

Compiling the code under clang no longer issues the warning.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
@makortel FYI

**Comment by Dr15Jones** [comment]
please test

**Comment by clacaputo** [comment]
+reconstruction

**Comment by perrotta** [comment]
+1

**Pull request merged**
