### PR TITLE
[14_0_X] - Fix for `EndPath`s in `DependecyGraph`

### PR DESCRIPTION
**Pull request by AdrianoDee**
#### PR description:

14_0_X backport of #44742

### CODE REVIEW

**Comment by AdrianoDee** [comment]
please test

**Comment by AdrianoDee** [comment]
backport of https://github.com/cms-sw/cmssw/pull/44742

**Comment by AdrianoDee** [comment]
type bug-fix

**Comment by makortel** [comment]
+core

**Comment by rappoccio** [comment]
+1

**Pull request merged**
