### PR TITLE
Update pileup scenario in RelVals

### PR DESCRIPTION
**Pull request by kskovpen**
#### PR description:

This PR updates the pileup scenario in RelVals from the default Run3_Flat55To75_PoissonOOTPU to a more realistic 2022_LHC_Simulation_10h_2h, which was already validated in 12_0_0_pre6.

#### PR validation:

Tested in standard PU wfs.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Not a backport.

### CODE REVIEW

**Comment by kskovpen** [comment]
please test

**Comment by srimanob** [comment]
Hi @kskovpen 

I am not sure it is a good idea to change to the PU scenario used for production in relvals setting. The reason is that we have very limited no. of events in relvals, getting very broad PU will not help us to focus on PU dependent quantities. In the past, i.e. 2018, we decided to keep PU50 for relvals, just to make sure we get relvals in the worst-case scenario. 

Maybe @cms-sw/reconstruction-l2 and DPG @amassiro should comment on this PR.

**Comment by kskovpen** [comment]
> Hi @kskovpen
> 
> I am not sure it is a good idea to change to the PU scenario used for production in relvals setting. The reason is that we have very limited no. of events in relvals, getting very broad PU will not help us to focus on PU dependent quantities. In the past, i.e. 2018, we decided to keep PU50 for relvals, just to make sure we get relvals in the worst-case scenario.
> 
> Maybe @cms-sw/reconstruction-l2 and DPG @amassiro should comment on this PR for the usefulness for objects and physics performance.

Thanks for your comment, @srimanob. The only goal was to update to the same pileup configuration as used in the MC production, but I get your point. Let's see indeed what others think.

**Comment by mmusich** [comment]
Hi @srimanob reporting here my 2 cents:

>  am not sure it is a good idea to change to the PU scenario used for production in relvals setting. The reason is that we have very limited no. of events in relvals, getting very broad PU will not help us to focus on PU dependent quantities. In the past, i.e. 2018, we decided to keep PU50 for relvals, just to make sure we get relvals in the worst-case scenario.

1) `Run3_Flat55To75_PoissonOOTPU`has no fixed average as in PU50, but varies from 55 to 75 so it already somewhat spread, isn't it?
2) I think the current profile is overly aggressive w.r.t LHC projections and forces upon developers unrealistically pessimistic conditions (e.g. dynamic inefficiencies depend on PU etc.). This has already had some consequences e.g. on the tuning of tracking for HLT.

**Comment by slava77** [comment]
a link to the PU profile plot in this PR description would be nice.

**Comment by mmusich** [comment]
> a link to the PU profile plot in this PR description would be nice.

I think it was discussed here: https://github.com/cms-sw/cmssw/pull/34460#issuecomment-879926496

**Comment by srimanob** [comment]
Kindly ping the discussion on this @qliphy @perrotta

**Comment by srimanob** [comment]
Do you have a plan to discuss this PR, @cms-sw/pdmv-l2 ?

**Comment by kskovpen** [comment]
It was briefly discussed yesterday. I think there is no strong opinion on this. On our side, the idea was just to keep things in sync with respect to what is used in MC production. Since RelVals are mainly used for software validation, probably this update is not very relevant, having both pileup profiles more or less representing similar phase space.

**Comment by kskovpen** [comment]
As was discussed today, let's close it for now.

**Pull request closed without merging**
