### PR TITLE
[14_0_X SIM] Allowed MT mode for RHStopTracer of R-hadron simulation

### PR DESCRIPTION
**Pull request by civanch**
#### PR description:
RHStopTracer is implemented as a SimProducer wrapper allowing identify stop of R-hadrons within CMS.
In this PR this wrapper is enabled for the MT mode.

#### PR validation:
private

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:
when will approved will be backported to Run3 MC production releases.

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by tvami** [comment]
urgent
 * @cms-sw/orp-l2 we need the backport of this for Run-3 signal simulations, please merge asap, thanks!

**Comment by tvami** [comment]
I validated with
```
cmsrel CMSSW_14_0_X_2023-11-15-1100
cd CMSSW_14_0_X_2023-11-15-1100/src
cmsenv
git cms-merge-topic 43273
curl -s -k https://cms-pdmv-prod.web.cern.ch/mcm/public/restapi/requests/get_fragment/PPD-Run3Summer22HSCPGS-00002 --retry 3 --create-dirs -o Configuration/GenProduction/python/PPD-Run3Summer22HSCPGS-00002-fragment.py -s Configuration/GenProduction/python/PPD-Run3Summer22HSCPGS-00002-fragment.py
scram b -j
cmsDriver.py Configuration/GenProduction/python/PPD-Run3Summer22HSCPGS-00002-fragment.py --python_filename PPD-Run3Summer22HSCPGS-00002_1_cfg.py --eventcontent RAWSIM --customise SimG4Core/CustomPhysics/Exotica_HSCP_SIM_cfi.customise,Configuration/DataProcessing/Utils.addMonitoring --datatier GEN-SIM --fileout file:PPD-Run3Summer22HSCPGS-00002.root --conditions 124X_mcRun3_2022_realistic_v12 --beamspot Realistic25ns13p6TeVEarly2022Collision --customise_commands process.source.numberEventsInLuminosityBlock="cms.untracked.uint32(100)" --step GEN,SIM --geometry DB:Extended --era Run3 --mc -n 10  --nThread=2
```

it works fine! (As opposed to w/o the PR we get 
```
RunManagerMTWorker::createWatchers: Unable to use Watcher RHStopTracer if number of threads > 1
----- End Fatal Exception -------------------------------------------------
```

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
