### PR TITLE
Introduce new utilities for writing Alpaka kernels

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Introduce four new utilities for writing Alpaka kernels:
  - `blocks_with_stride(acc, size)`
  - `elements_in_block(acc, block, size)`
  - `once_per_grid(acc)`
  - `once_per_block(acc)`

Simplify the unit tests, and extend them to cover the newly introduced functionality.

---

##### blocks_with_stride

`blocks_with_stride(acc, size)` returns a range than spans the (virtual) block indices required to cover the given problem size.

For example, if size is 1000 and the block size is 16, it will return the range from 0 to 62 (63 blocks of 16 elements covers 1008 elements, enough for a total size of 1000).
If the work division has more than 63 blocks, only the first 63 will perform one iteration of the loop, and the other will exit immediately.
If the work division has less than 63 blocks, some of the blocks will perform more than one iteration, in order to cover then whole problem space.

All threads in a block see the same loop iterations, while threads in different blocks may see a different number of iterations.

##### elements_in_block

`elements_in_block(acc, block, size)` returns a range that spans all the elements within the given block. Iterating over the range yields values of type `ElementIndex`, that contain both `.global` and `.local` indices of the corresponding element.

If the work division has only one element per thread, the loop will perform at most one iteration.
If the work division has more than one elements per thread, the loop will perform that number of iterations, or less if it reaches size.

##### once_per_grid

`once_per_grid(acc)` evaluates to true for a single thread within the kernel execution grid.

Usually the condition is true for block 0 and thread 0, but these indices should not be relied upon.

##### once_per_block

`once_per_block(acc)` evaluates to true for a single thread within the block.

Usually the condition is true for thread 0, but this index should not be relied upon.

#### PR validation:

The updated unit tests compile and pass.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

If the `master` branch is moved to `CMSSW_14_0_X`, this PR will be backported to `CMSSW_13_3_X`.

### CODE REVIEW

**Comment by fwyzard** [comment]
enable gpu

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
> ## GPU Unit Tests
> 
> I found 1 errors in the following unit tests:
> 
> ---> test alpakaTestKernelCudaAsync had ERRORS

The original test fails to run, but exits with a non-error status:
```
$ $CMSSW_FULL_RELEASE_BASE/test/$SCRAM_ARCH/alpakaTestKernelCudaAsync
No devices available on the platform alpaka_cuda_async, the test will be skipped.
No devices available on the platform alpaka_cuda_async, the test will be skipped.
No devices available on the platform alpaka_cuda_async, the test will be skipped.
===============================================================================
test cases: 3 | 3 passed
assertions: - none -
```

I though SCRAM would not run the CUDA tests if `cudaIsEnabled` fails ?

**Comment by makortel** [comment]
> I though SCRAM would not run the CUDA tests if `cudaIsEnabled` fails ?

That is the default behavior, but for GPU_X IBs and the PR GPU tests all tests depending on `cuda` are explicitly run (this is visible e.g. in the PR GPU unit test log
```
+ eval USER_UNIT_TESTS=cuda timeout 7320 scram b -v -k -j 4 unittests
++ USER_UNIT_TESTS=cuda
++ timeout 7320 scram b -v -k -j 4 unittests
```
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-139b5e/35643/gpuUnitTests/log.txt
)

So the node where the GPU tests were run did not have a GPU (setup compatible with CUDA 12.2?) after all?

**Comment by fwyzard** [comment]
CERN GPU nodes will be updated to CUDA 12.2 between tomorrow and Wednesday:
https://cern.service-now.com/service-portal?id=outage&n=OTG0145266 .

**Comment by fwyzard** [comment]
@makortel
1. do you think the way to write the test is OK, or we should have a different behaviour?
2. do the other changes look good?

**Comment by makortel** [comment]
Looks ok to me

**Comment by fwyzard** [comment]
+heterogenous

**Comment by fwyzard** [comment]
+heterogeneous

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
please abort

**Comment by fwyzard** [comment]
enable gpu

**Comment by fwyzard** [comment]
please test

**Comment by rappoccio** [comment]
@fwyzard is the failed unit test expected? Should we hold off on this one?

**Comment by fwyzard** [comment]
I think the failed unit test is due to the update of the GPU nodes that was done at CERN this week.

**Comment by fwyzard** [comment]
let's try again

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
@makortel, what do you think about the names
  - `elements_with_stride`
  - `blocks_with_stride`
  - `elements_in_block`
  - `local_elements_in`block`
?

**Comment by fwyzard** [comment]
please test

**Comment by makortel** [comment]
> what do you think about the names

Let's see if I manage to understand their behavior correctly from just name

> * `elements_with_stride`

Loops over all elements of (all threads of) all blocks with a given stride?

> * `blocks_with_stride`

Loops over all blocks with a given stride?

> * `elements_in_block`

Loops over all elements of (all threads of) a given block?

> * `local_elements_in_block`

I'm unable to quickly figure out how the `local_` prefix would alter the behavior.

**Comment by thomreis** [comment]
I get compilation errors with the last commit.
```
CMSSW_13_3_0_pre5/src/HeterogeneousCore/AlpakaInterface/interface/workdivision.h:567:93: error: type/value mismatch at argument 1 in template parameter list for 'template<class TDim> using Vec = alpaka::Vec<TDim, unsigned int>'
  567 |     return alpaka::getIdx<alpaka::Grid, alpaka::Threads>(acc) = Vec<alpaka::Dim<TAcc>::value>::zeros();
      |                                                                                             ^
/data/user/treis/ecal/run3/dev/alpaka/CMSSW_13_3_0_pre5/src/HeterogeneousCore/AlpakaInterface/interface/workdivision.h:567:93: note:   expected a type, got 'alpaka::Dim<TExtent>::value'
```

**Comment by fwyzard** [comment]
that's the downside of pushing untested code on GitHub...

**Comment by fwyzard** [comment]
> I get compilation errors with the last commit.

Fixed, and added tests for `once_per_grid` and `once_per_block`.

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
+heterogeneous

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
