### PR TITLE
Rename inline c++ files to .icc

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Rename inline c++ files with different extensions (`*.impl`, `*.inl`) to `.icc` that is the most common one used in CMSSW:
```
$ find * -name '*.icc' -or -name '*.impl' -or -name '*.inl' | cut -d. -f2 | sort | uniq -c
     86 icc
      1 impl
      4 inl
```

Move include files used by a single .cc file to the src/ directory.

No changes expected.

### CODE REVIEW

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
please test

**Comment by makortel** [comment]
+core

Thanks!

**Comment by cecilecaillol** [comment]
+l1

**Comment by smorovic** [comment]
+daq

**Comment by perrotta** [comment]
+1

**Pull request merged**
