### PR TITLE
Allow Portable{Collection,Object}<T, TDev> to be used also independently of ALPAKA_ACCELERATOR_NAMESPACE

### LINKED ISSUE #720: Generalize and simplify PortableCollection<T, TDev> alias template definition

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

This PR makes the `PortableCollection<T, TDev>` and `PortableObject<T, TDev>` alias templates usable also independently of `ALPAKA_ACCELERATOR_NAMESPACE`. This ability can be useful e.g. for EventSetup data product classes that themselves are templated over the device type (`TDev`), and want to use the PortableCollection for SoA storage (e.g. having `PortableCollection`(s) as data members).

Furthermore, this PR simplifies the definitions of the `PortableCollection<T, TDev>` and `PortableObject<T, TDev>` alias templates. The trait-based approach is kept, but the traits are fully defined and specialized in `DataFormats/Portable/interface/Portable{Collection,Object}.h`. In addition, the specializations of the `CopyTo{Host,Device}` templates were moved to the headers in `interface/` as well.

Old description from the RFC-stage of this PR:

> The first commit of this PR makes the `PortableCollection<T, TDev>` alias template usable also independently of `ALPAKA_ACCELERATOR_NAMESPACE`. This ability can be useful e.g. for EventSetup data product classes that themselves are templated over the device type (`TDev`), and want to use the PortableCollection for SoA storage (e.g. having PortableCollection(s) as data members). I have an example crafted, but that is waiting for https://github.com/cms-sw/cmssw/pull/43298 to get merged, and therefore I went with a standalone PR just for this ability.
>
> While doing that I felt the way the `PortableCollection<T, TDev>` is defined was a bit cumbersome.
> * The second commit continues to use the trait-based approach, but the trait is fully defined and specialized in `DataFormats/Portable/interface/PortableCollection.h`
>* The third commit uses `std::conditional_t` in the alias template instead of the trait class template
>
> Some further cleanup can be done, depending on the decided approach. (e.g. in case of second or third commit I'd move the specializations of `CopyToHost` and `CopyToDevice` class templates to `DataFormats/Portable/interface/PortableCollection.h`).

Resolves https://github.com/makortel/framework/issues/720

#### PR validation:

Added unit test compiles.

### CODE REVIEW

**Comment by makortel** [comment]
@fwyzard Any thoughts?

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
Comparison differences are related to https://github.com/cms-sw/cmssw/issues/39803

Log differences are related to https://github.com/cms-sw/cmssw/issues/43293

**Comment by makortel** [comment]
@fwyzard Any comments?

**Comment by fwyzard** [comment]
Sorry for the delay, the LUMI hackathon and the CMS Week got me distracted :-/



> The first commit of this PR makes the `PortableCollection<T, TDev>` alias template usable also indepndently of `ALPAKA_ACCELERATOR_NAMESPACE`.

OK.

A couple of questions:
  - is there any reason to change `class` to `struct` ?
  - can defining `traits::PortableCollectionTrait<T, alpaka::DevCpu>` more than once (in `DataFormats/Portable/interface/alpaka/PortableCollection.h` when compiling for the CPU backend, and now in `DataFormats/Portable/interface/PortableHostCollection.h`) cause any problems ? Or is it OK to have the same specialisation twice, if they resolve to the same types ?


> * The second commit continues to use the trait-based approach, but the trait is fully defined and specialized in `DataFormats/Portable/interface/PortableCollection.h`

OK, this cleans it all up anyway :-)


> * The third commit uses `std::conditional_t` in the alias template instead of the trait class template

I like best the style of the second commit, but I don't have any concrete objections to the third one.

It feels like the second may be easier to extend if there are other special cases in the future - but I guess whatever logic that uses, can also be implemented using `std::conditional_t`.

So, I like two bes,t but I'm also OK with three.

**Comment by fwyzard** [comment]
By the way, can you do the same also for `PortableObject` ?

**Comment by makortel** [comment]
> * is there any reason to change `class` to `struct` ?

My personal preference for `struct` when everything is public (which might be somewhat consistent with [Core Guidelines C.2](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#c2-use-class-if-the-class-has-an-invariant-use-struct-if-the-data-members-can-vary-independently). IIRC the earlier `PortableCollectionTrait::CollectionType` being private lead to compilation errros.

> * can defining `traits::PortableCollectionTrait<T, alpaka::DevCpu>` more than once (in `DataFormats/Portable/interface/alpaka/PortableCollection.h` when compiling for the CPU backend, and now in `DataFormats/Portable/interface/PortableHostCollection.h`) cause any problems ? Or is it OK to have the same specialisation twice, if they resolve to the same types ?

I'd think two identical specializations would be technically ok in terms of One Definition Rule. Nevertheless, I think having only one definition would be simplest for future maintenance.

> I like best the style of the second commit, but I don't have any concrete objections to the third one.
> 
> It feels like the second may be easier to extend if there are other special cases in the future - but I guess whatever logic that uses, can also be implemented using `std::conditional_t`.

I agree the second commit would be easier to extend. Or, even if such extensions could be done with `std::conditional_t`, maybe with one additional case the code would still be readable, but I'd imagine with third (and onwards) the pattern matching style with the template specializations to be easier to digest.

On the other hand, with just 2 cases the `std::conditional_t` feels easier to me. 

Can you think of a situation where we'd need (or want to have) another special case? (I'm wondering if there is something foreseeable we might want to account already now)

The pattern for selecting between host and device collections repeats at least in the pixel PRs. I'd like some simple-to-use facility for users to use, and `std::conditional_t` fits the bill. It seems to me if another special case would be needed in the future, the user code for selecting between the host and device collections would have to be addressed anyway. Perhaps at that point we should consider some further abstraction?

> By the way, can you do the same also for `PortableObject` ?

Yes.

**Comment by fwyzard** [comment]
> Can you think of a situation where we'd need (or want to have) another special case? (I'm wondering if there is something foreseeable we might want to account already now)

The two possibilities I had in mind are Unified Memory and oneAPI CPU devices (OpenCL-based).

These might need some special casing of the `PortableCollection`s since they would use memory accessible (or just on) the host -- but I haven't given any concrete thoughts about what that would imply.

**Comment by makortel** [comment]
> > Can you think of a situation where we'd need (or want to have) another special case? (I'm wondering if there is something foreseeable we might want to account already now)
> 
> The two possibilities I had in mind are Unified Memory and oneAPI CPU devices (OpenCL-based).
> 
> These might need some special casing of the `PortableCollection`s since they would use memory accessible (or just on) the host -- but I haven't given any concrete thoughts about what that would imply.

After thinking a bit more, I'm starting to lean towards the second commit, i.e. keeping the trait-based approach here, to have a little bit more flexibility for the future. I'd still advocate the `std::conditional_t` for user code for time being.

**Comment by makortel** [comment]
This update
* rebases on top of CMSSW_14_0_0_pre1
* keeps the trait-based approach
* moves the specializations of `CopyTo{Host,Device}` to the headers in `interface/`, as those specializations do not depend on `ALPAKA_ACCELERATOR_NAMESPACE`

To me this PR is now complete.

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by fwyzard** [comment]
+1

**Comment by rappoccio** [comment]
+1

**Pull request merged**
