### PR TITLE
Save transient BMTF objects to EDM output file

### PR DESCRIPTION
**Pull request by dildick**
Slight modification to BMTF so that it writes `L1MuBMTrack`, `L1MuBMTrackSegEta` and `L1MuBMTrackSegPhi` to EDM output file. This is needed to know exactly which L1 segments were used to build the `RegionalMuonCand` at the analysis stage. At the moment there is a missing link between `RegionalMuonCand` and `L1MuDTChambPhContainer`. A deltaR match between `RegionalMuonCand` and `L1MuBMTrack` would resolve that problem. There are no changes made to the BMTF logic or emulator algorithms. The performance should therefore be the same before and after this update.

I tested it with WF 20434.0 only so far. 

The extra collections are written out into the ROOT file as you can see below. 

<PRE>
-bash-4.1$ edmEventSize -a -v step2.root | grep BM
l1tRegionalMuonCandBXVector_simBmtfDigis_UnsortedBMTF_HLT. 400.2 294.1
l1tRegionalMuonCandBXVector_simBmtfDigis_BMTF_HLT. 363.2 277
l1tMuonBXVector_simGmtStage2Digis_imdMuonsBMTF_HLT. 348.2 276.4
L1MuBMTracks_simBmtfDigis_BMTF_HLT. 339.7 264.5
L1MuBMTrackSegPhis_simBmtfDigis_BMTF_HLT. 313.3 260.9
L1MuBMTrackSegEtas_simBmtfDigis_BMTF_HLT. 279.7 251.9
</PRE>

@tahuang1991, @demarley FYI

### CODE REVIEW

**Comment by davidlange6** [comment]
-1
these classes need to move to a DataFormats package if they are to become data formats

**Comment by dildick** [comment]
@davidlange6 L1MuBMTrack has class members `L1MuBMTrackAssParam`, `L1MuBMAddressArray` and `L1MuBMSecProcId`. `L1MuBMTrackSegPhi` and `L1MuBMTrackSegEta` have class member `L1MuBMTrackSegLoc `. These are all defined in `L1Trigger/L1TMuonBarrel`. If the BMTF track and its segments have to move to `DataFormats/L1TMuon`, then so do the classes mentioned above. Otherwise there will be cyclic inclusions I think. What do you suggest?

**Comment by davidlange6** [comment]
Thats correct, yes.

**Comment by davidlange6** [comment]
eg, anything to be put into the event or into data files and all of its dependencies need to be in DataFormats.

**Comment by davidlange6** [comment]
please test

**Comment by dildick** [comment]
Ok. I will make the modification. Thanks!

**Comment by dildick** [comment]
it seems more changes are needed. I will let you know when I done.

**Comment by dildick** [comment]
seems to compile now with `scram b vclean && scram b -k -j 8`

**Comment by abrinke1** [comment]
Hi @dildick ,

A few comments:

1) Would it be better to pull this into the l1t-offline code first, and test it out there?  Perhaps @rekovic has thoughts.

2) In principle, the unique stub identifiers should be saved here:

https://github.com/cms-l1t-offline/cmssw/blob/l1t-integration-CMSSW_9_2_5_patch2/L1Trigger/L1TMuonBarrel/src/L1MuBMTrackFinder.cc#L226

I think the uGMT (@thomreis) uses these stub identifiers to cancel tracks between wheels.  Perhaps @gkaratha can comment on whether these fields are filled properly and completely in the emulator, and how to interpret them.

3) If you want to avoid the complications of interpreting the RegionalMuonCand track address, why not just save the L1MuBMTrack collection:

https://github.com/cms-l1t-offline/cmssw/blob/l1t-integration-CMSSW_9_2_5_patch2/L1Trigger/L1TMuonBarrel/interface/L1MuBMTrack.h

This appears to have everything you want, including the L1MuBMTrackSegPhi and L1MuBMTrackSegEta vectors associated with the event.  You'd have to add it to the producer, and the track-finder:

https://github.com/cms-l1t-offline/cmssw/blob/l1t-integration-CMSSW_9_2_5_patch2/L1Trigger/L1TMuonBarrel/plugins/L1TMuonBarrelTrackProducer.cc#L41

https://github.com/cms-l1t-offline/cmssw/blob/l1t-integration-CMSSW_9_2_5_patch2/L1Trigger/L1TMuonBarrel/src/L1MuBMTrackFinder.cc#L208

It would probably require moving L1MuBMTrack.h to DataFormats/L1TMuon, though.  I guess I don't see why you need to save out L1MuBMTrackSegEta and L1MuBMTrackSegPhi separately.

Best,
Andrew

**Comment by dildick** [comment]
Hi @abrinke1 

1. Testing it out in cms-l1t-offline would be an idea. 
2. If the track address contains information which stub was used in each station, so that I can access the stub angle and stub direction, then this PR might not be needed. But from my point this is the easiest way to do it. It has worked for me in the past with the DTTF. If trigger people think that these changes go a bit too far, then a functionality should be made available that translate addresses into physical stubs.
3. If I need to move L1MuBMTrack.h then also its dependencies need to be moved. See comment by David Lange above.

Thanks

**Comment by davidlange6** [comment]
please test

**Comment by dildick** [comment]
@rekovic please sign

**Comment by abrinke1** [comment]
Hi @dildick ,

Sorry for the late comment, but to de-clutter things, it might be better if the "lower level" classes (that you don't actually produce) were in a sub-folder, i.e. DataFormats/L1TMuon/interface/BMTF/, rather than DataFormats/L1TMuon/interface/.  Specifically I'm looking at:

L1MuBMAddressArray.h
L1MuBMSecProcId.h
L1MuBMTrackAssParam.h
L1MuBMTrackSegLoc.h

L1MuBMTrack.h, L1MuBMTrackSegEta.h, and L1MuBMTrackSegPhi.h are fine in the main folder, since those are now produced by L1TMuonBarrelTrackProducer.cc.  @thomreis can comment as well, if he has an opinion.

Other than that, I think this PR looks good to go, and will be very useful.

Best,
Andrew

**Comment by dildick** [comment]
@abrinke1 A reasonable request. I move the auxiliary classes to `DataFormats/L1TMuon/{interface,src}/BMTF/`

**Comment by abrinke1** [comment]
Thanks!

**Comment by dildick** [comment]
@cmsbuild IMO the BMTF group is responsible to make sure the code is up to date with CMSSW code style. I am not planning to modify anything else.

**Comment by davidlange6** [comment]
please test

**Comment by abrinke1** [comment]
If it's a "DAS Error", does that just mean that some dataset was temporarily unavailable?  Should the tests just be re-triggered?

**Comment by smuzaffar** [comment]
please test
looks like das server returned empty results which caused this error. Das queries results has been refreshed now, so this should work now.

**Comment by dildick** [comment]
@abrinke1 are there more comments? if not, could @rekovic and @davidlange6 sign?

**Comment by abrinke1** [comment]
No comments from me - sign away!

**Comment by dildick** [comment]
@rekovic please sign, it need this in asap

**Comment by dildick** [comment]
update to comply with code-checks

**Comment by davidlange6** [comment]
please test

**Comment by rekovic** [comment]
+1

**Comment by dildick** [comment]
@smuzaffar can you rerun the tests again please?

**Comment by smuzaffar** [comment]
@dildick , code-checks automatically runs when PR is updated.

**Comment by dildick** [comment]
@smuzaffar this PR, as well as #19786 and #19986 have been waiting too long already for a L1 and/or L2 signature. The code-checks for all these PRs is necessary, but not essential and can be taken care of in a follow-up pull request all together. If I have to do this now, each will have to be retested (tests may fail again), resigned (signatures are already delayed) etc.

**Comment by dildick** [comment]
@smuzaffar can you rerun the tests again please?

**Comment by smuzaffar** [comment]
please test

**Comment by davidlange6** [comment]
+1

**Pull request merged**
