### PR TITLE
[Do Not Merge] New "CUDA" Memory Pool [12.4.X]

### PR DESCRIPTION
**Pull request by VinInn**
This is a new version of #37952 mostly for benchmarking purposes.

It extends the use of the new memory pool to the calorimeters (including the HostAllocator).

A new feature comes from realizing that there is no reason to delay memory free in DataFormats as there is always a stream-sync before any data-format is deleted. 
For those hosted on the host (sic) it's absolutely safe (either are used and better be a sync before that, or does not matter).
For those hosted on the device it can only fail for very (very) peculiar early delete patterns involving intermediate results used only on device.
@makortel : could you please comment on this statement/proposal?

w/r/t public benchmarks such as 

image

I obtain 812Hz for 32 threads (instead of 763 above)

### CODE REVIEW

**Comment by VinInn** [comment]
@cmsbuild , please test

**Comment by VinInn** [comment]
enable gpu

**Comment by VinInn** [comment]
enable hlt

**Comment by VinInn** [comment]
No idea how to fix the clang test failure (it is using CUDADataFormatsTrackingRecHit_xr.rootmap from the IB, why?)

**Comment by VinInn** [comment]
@cmsbuild please test

**Comment by VinInn** [comment]
@cmsbuild please test

**Comment by VinInn** [comment]
enable gpu

**Comment by tvami** [comment]
-alca
 * just to remove from the `alca` queues
 * or well actually, should it be closed, 12_4_X wont be used anymore for data taking

**Comment by perrotta** [comment]
> I'm not planning any further work

Thank you @VinInn : feel free to close the PR, then. Or should we?

**Comment by tvami** [comment]
@cmsbuild , please close
 * see https://github.com/cms-sw/cmssw/pull/39623#issuecomment-1420933658

**Pull request closed without merging**
