### PR TITLE
Add HGCal RecHits to AOD for file sizes tests

### PR DESCRIPTION
**Pull request by lgray**
Adds HGCalRecHits (no digis, or uncalibrated hits) to event record.

### CODE REVIEW

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
Would it make sense to remove some of the HGCAL PF clusters from AOD?
particleFlowClusterHGCal  are almost 1/2 of AODSIM in PU200 now
(PFClusters 2.9 MB + CaloClusters 0.8 MB + SuperClusters 0.6 MB).

**Comment by slava77** [comment]
Is this PR made in order to be able to do developments from AOD in case RECO will be deleted?
Is this going to be solely HGCAL clustering development?
Is it clear that you will not need e.g. caloTruth to do this work on HGCAL?

I'm trying to understand if this addition of ~2MB/event (22% increase in the AOD size) is actually going to be used.

**Comment by lgray** [comment]
This PR is made in case RECO is deleted and we are left only with AOD.
This is so that more-or-less any study with HGCal can proceed, since shower shape variables are not yet calculated and saved for any physics objects (mainly E/gamma, of course).
caloTruth is in the GEN-SIM-DIGI-RAW, so two file solution will work unless the DIGI is being thrown away.

**Comment by lgray** [comment]
After talking to Luca / Pat / Meenakshi, the first round in going with RECO and so makes this PR not necessary.

**Comment by lgray** [comment]
The follow up will be a reduced rechits collection, similar to those for ECAL/HCAL.

**Comment by slava77** [comment]
On 12/6/16 12:22 AM, Lindsey Gray wrote:
> This PR is made in case RECO is deleted and we are left only with AOD.
> This is so that more-or-less any study with HGCal can proceed, since
> shower shape variables are not yet calculated and saved for any physics
> objects (mainly E/gamma, of course).
> caloTruth is in the GEN-SIM-DIGI-RAW, so two file solution will work
> unless the DIGI is being thrown away.


I suppose, 7MB of GEN-SIM-DIGI-RAW may fit the budget still much better,
if RECO is ~40 MB.

It sounds like for your work to be feasible, you need either RECO (~40MB)
or GEN-SIM-DIGI-RAW+ AOD* ~ 7MB + 11 MB ~ 18 MB.
So, just a factor of two saving.

I suspect the muons will want GEN-SIM-DIGI-RAW (for ME0 there is need
for DIGIs, they are not in RECO).

However, it is also quite possible that tracker will need RECO.
So, the net will then bloat to 58 MB/event and your addition to AOD
might become just a copy.

I'll sign off based on discussion on Wed in RECO/AT

**Comment by lgray** [comment]
@slava77 Have closed this PR in the mean time. It seems like we will go with RECO. If that changes I can reopen this.

**Comment by davidlange6** [comment]
I agree with @slava77 - best to understand the suite of data products needed and make a single data output format with that information (not caring about the name of it so much..)

**Comment by slava77** [comment]
@kpedro88 
may I ask  you to poll developers (users of the production samples) to find out their needs and if we can get one file format (possibly smaller than FEVT) that would fit all.

**Pull request closed without merging**
