### PR TITLE
Remove further unused classes from DataFormats/GEMDigi

### PR DESCRIPTION
**Pull request by watson-ij**
#### PR description:

Per #30586 removing further unused classes DataFormats/GEMDigi/GEMAMCStatusDigi and GEMGEBStatusDigi. These classes are older unused versions of replacements in EventFilter/GEMRawToDigi.

@jshlee @quark2  @hyunyong @davidlange6 

#### PR validation:

Checked run the matrix on the 2021 10mu workflow 11621.0 runs without issue after removing the classes.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by watson-ij** [comment]
I don't think this is due to me. I added this onto a branch that was previously merged into master, could that cause an issue?

**Comment by davidlange6** [comment]
@smuzaffar - seems code checks are not working this morning

On Jul 9, 2020, at 8:20 AM, cmsbuild <notifications@github.com<mailto:notifications@github.com>> wrote:



-code-checks

ERROR: Build errors found during clang-tidy run.

gmake: *** [tmp/slc7_amd64_gcc820/Makefile:32: .SCRAM/slc7_amd64_gcc820/timestamps/clhepheader] Error 1

gzip: /build/cmsbld/jenkins/workspace/run-pr-code-checks/CMSSW_11_2_X_2020-07-08-2300/.SCRAM/slc7_amd64_gcc820/ToolCache.db.gz: unexpected end of file
Can't call method "initpathvars" on an undefined value at /cvmfs/cms-ib.cern.ch/nweek-02636/share/lcg/SCRAMV1/V2_2_9_pre07/src/SCRAM/SCRAM.pm<http://cms-ib.cern.ch/nweek-02636/share/lcg/SCRAMV1/V2_2_9_pre07/src/SCRAM/SCRAM.pm> line 392.
--
gmake: *** [tmp/slc7_amd64_gcc820/Makefile:32: .SCRAM/slc7_amd64_gcc820/timestamps/clhep] Error 1

Finding a value for CORAL_BASE:

--
gmake: *** No rule to make target 'code-checks'.
gmake: *** [There are compilation/build errors. Please see the detail log above.] Error 2

**Comment by davidlange6** [comment]
code-checks

**Comment by kpedro88** [comment]
please test

**Comment by kpedro88** [comment]
+upgrade

**Comment by civanch** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
