### PR TITLE
Phase2-hgx312Y Make a complete scenario for HGCal geometry version V17

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Make a complete scenario for HGCal geometry version V17

#### PR validation:

Use the runTheMatrix test workflows

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cvuosalo @srimanob Please approve this PR. Our next step is stuck

**Comment by srimanob** [comment]
+Upgrade

Needed for V17 HGCal.

**Comment by bsunanda** [comment]
@cvuosalo Please approve this

**Comment by cvuosalo** [comment]
+1

**Comment by perrotta** [comment]
+1
- Isn't it time yet to make a V17 workflow in the matrix?

**Pull request merged**
