### PR TITLE
Fix 2022v15 frozen HLT menu for PixelCPEFast changes

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
#### PR description:

Fix 2022v15 frozen HLT menu for PixelCPEFast changes
https://its.cern.ch/jira/browse/CMSHLT-2585

#### PR validation:

TSG tests

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

N/A

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please abort

**Comment by missirol** [comment]
Can't we just remove the frozen menu from the `master` branch, since it is unused? We would add one back next year when 13_0_X closes (e.g. HLT V1.0 of 2023).

**Comment by Martin-Grunewald** [comment]
Indeed, but it is easier to replace/rename, rather than rip-out and add from scratch in all the thus affected files.

**Pull request merged**
