### PR TITLE
L1T online DQM changes

### PR DESCRIPTION
**Pull request by thomreis**
Improvements and fixes for the L1T online DQM

- Add fillDescriptions
- reorganizing config files
- Move uGMT emulator DQM before the fat event filter
- renaming L1T2016 directories that somehow managed to be only changed in 90x releases but not in 91x and 92x.
- fix bug in L1 muon comparison module

### CODE REVIEW

**Comment by thomreis** [comment]
This PR addresses a comment made here: https://github.com/cms-sw/cmssw/pull/18500#pullrequestreview-36213502

**Comment by davidlange6** [comment]
please test

**Comment by rekovic** [comment]
@dmitrijus  please review and sign.  Also the backport #18664.

**Comment by dmitrijus** [comment]
+1

**Pull request merged**
