### PR TITLE
Mod highest values

### PR DESCRIPTION
**Pull request by rrabadan**
The possibility to produce a sorted list of the N modules with the largest digi, cluster, off track cluster occupancy when the corresponding tracker maps are produced is added

### CODE REVIEW

**Comment by venturia** [comment]
@rrabadan, @threus,
I know it is painful and it sounds like a tax to be payed only by honest citizens, but could you profit of this pull request and add in the README.md file of this package the documentation about the instructions on how to use and configure the plugin SiStripOfflineDQM ? It would be _very_ useful.

                                          ciao

                                  Andrea

On May 23, 2015, at 3:21 , cmsbuild <notifications@github.com<mailto:notifications@github.com>>
 wrote:


A new Pull Request was created by @rrabadan<https://github.com/rrabadan> (Raul Rabadan) for CMSSW_7_5_X.

Mod highest values

It involves the following packages:

DQM/SiStripMonitorClient

@cmsbuild<https://github.com/cmsbuild>, @danduggan<https://github.com/danduggan>, @nclopezo<https://github.com/nclopezo>, @deguio<https://github.com/deguio> can you please review it and eventually sign? Thanks.
@threus<https://github.com/threus>, @venturia<https://github.com/venturia> this is something you requested to watch as well.
You can sign-off by replying to this message having '+1' in the first line of your reply.
You can reject by replying to this message having '-1' in the first line of your reply.
If you are a L2 or a release manager you can ask for tests by saying 'please test' in the first line of a comment.
@nclopezo<https://github.com/nclopezo> you are the release manager for this.
You can merge this pull request by typing 'merge' in the first line of your comment.

**Comment by rrabadan** [comment]
Conflicts fixed.


On May 24, 2015, at 10:11, cmsbuild <notifications@github.com<mailto:notifications@github.com>> wrote:


-1
@rrabadan<https://github.com/rrabadan> This pull request cannot be automatically merged, could you please rebase it?
you can see the log for git cms-merge-topic here:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-9242/7823/git-merge-result

**Comment by deguio** [comment]
please test

**Comment by threus** [comment]
pretty ping..

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
