### PR TITLE
functionality to avoid creating (empty) DQM outputs for invalid HLT paths

### PR DESCRIPTION
**Pull request by missirol**
#### PR description:

This PR includes one possible way to avoid creating empty plots in the HLT offline-DQM
when a module is configured with HLT paths that are not present in the menu.

Implementation: added a method to the `GenericTriggerEventFlag` class in `CommonTools/TriggerUtils`,
and added a switch named `requireValidHLTPaths` in the `TopMonitor` plugin, as an example of how this could be used.

No differences expected in the comparisons (the `requireValidHLTPaths` switch added to `TopMonitor` is currently set to `False`).

#### PR validation:

Tested the changes locally and the code behaves as expected (for example: if the switch is turned on and the HLT path is not a valid one, the corresponding DQM outputs are not produced).

`runTheMatrix.py`: workflows 250202.171 and 250202.181 ran successfully.

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by perrotta** [comment]
+1
- Reco related changes are limited to GenericTriggerEventFlag, and just add the functionality needed by DQM
- Jenkins tests pass and show no differences in reco outputs

**Comment by santocch** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Pull request merged**
