### PR TITLE
fix histo scales, add ngood vertex

### PR DESCRIPTION
**Pull request by VinInn**
fix bugs and add flexibility
adapt to current 2015 running

make sense only if in production before end of TS2

### CODE REVIEW

**Comment by VinInn** [comment]
is forward port automatic?

**Comment by smuzaffar** [comment]
@VinInn, forward port is automatic only for 75X to 76X.

**Comment by VinInn** [comment]
will manual port then

**Comment by smuzaffar** [comment]
yes manual in a sense that you have to create a different PR for 75x

**Comment by slava77** [comment]
In any case, check if the 76X version didn't diverge from what's in 75X.
Otherwise, a forward port may not work and this issue detection is not
very clear, AFAIK.

**Comment by VinInn** [comment]
@cmsbuild please test

**Comment by davidlange6** [comment]
@cmsbuild, please test

**Comment by deguio** [comment]
+1

**Comment by rovere** [comment]
Also in this case, I need to have this approved to push another PR on top.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
