### PR TITLE
EGM IDs for CMSSW 74X

### PR DESCRIPTION
**Pull request by lgray**
Contains a backport of #9797, without the ExpressionParser.

Also implements VID cutbased and MVA-based electron and photon IDs for PHYS 14 and Spring15.

This will require some new entries into the appropriate cms-data repositories.
A forward port to CMSSW_7_5_X and CMSSW_7_6_X will come soon.

@ikrav @cmkuo

### CODE REVIEW

**Comment by slava77** [comment]
RecoEgamma/ElectronIdentification/data and  RecoEgamma/PhotonIdentification/data has to go to the external data packages

**Comment by lgray** [comment]
Yup, this will likely come tomorrow. Busy today.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cmsbuild please test

@lgray 
- What's the status of moving the externals?
- is the miniAOD-from-miniAOD part going to show up here as well?

**Comment by lgray** [comment]
Externals delayed because of development on the later, and yes there will
be a backport.
Expect to be done Friday.

-L

**Comment by slava77** [comment]
@lgray please also resolve the event content issue that appears when running reco+miniaod in one application https://github.com/slava77/cmssw/issues/71
The {egmGsfElectronIDs} from the RECO part should be explicitly specified in the RECO*EventContent
http://cmslxr.fnal.gov/lxr/source/RecoEgamma/Configuration/python/RecoEgamma_EventContent_cff.py?v=CMSSW_7_4_6#0016 
Thank you.

**Comment by lgray** [comment]
Sure, that's no problem.

**Pull request closed without merging**
