### PR TITLE
another pass through the clang check cleanup 

### PR DESCRIPTION
**Pull request by davidlange6**
(again avoiding files touched by open PRs as of last night)

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
strange - the clang-tidy checks tell me to undo what my last commit did. Lets see for this time.

**Comment by Dr15Jones** [comment]
+1

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
merge




On 5 Nov 2017, at 18:59, cmsbuild <notifications@github.com<mailto:notifications@github.com>> wrote:


Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-21166/24187/summary.html

Comparison Summary:

  *   No significant changes to the logs found
  *   Reco comparison results: 0 differences found in the comparisons
  *   DQMHistoTests: Total files compared: 26
  *   DQMHistoTests: Total histograms compared: 2900266
  *   DQMHistoTests: Total failures: 1
  *   DQMHistoTests: Total nulls: 0
  *   DQMHistoTests: Total successes: 2900094
  *   DQMHistoTests: Total skipped: 171
  *   DQMHistoTests: Total Missing objects: 0
  *   Checked 107 log files, 10 edm output root files, 26 DQM output files

**Pull request merged**
