### PR TITLE
added esConsumes to modules in L1Trigger /L1ExtraFromDigis

### PR DESCRIPTION
**Pull request by JamminJones**
#### PR description:

added esConsumes to 1 module
#### PR validation:

the code compiles

### CODE REVIEW

**Comment by Dr15Jones** [comment]
This code change was made under my supervision.

**Comment by Dr15Jones** [comment]
hold

the EventSetup gets are done conditionally so we should set the tokens conditionally as well.

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
unhold

**Comment by Dr15Jones** [comment]
NOTE: The new code conditionally calls esConsumes based on the conditional getting of the data from the EventSetup. This was done to avoid prefetching of EventSetup data that will not be needed.

Looking at the existing `consumes` calls, many of them should also be conditional as the configuration parameters set which Event data will actually be requested. Not calling `consumes` conditionally is requiring the framework to prefetch Event data which is not needed.

I suggest that the maintainers of this code modify the `consumes` calls to only be called if needed.

**Comment by Dr15Jones** [comment]
ping

**Comment by Dr15Jones** [comment]
ping (it has been  2 weeks now without a review)

**Comment by rekovic** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
