### PR TITLE
implements UPT invariant mass triggers in uGT emulator

### PR DESCRIPTION
**Pull request by cavana**
#### PR description:

This PR provides a software implementation of the invariant mass correlation condition involving unconstrained pT for displaced muons in the uGT emulator.

No changes in output are expected.

#### PR validation:

This PR has been validated by the following:
(1) all code changes have been confirmed to compile correctly using 
(2) all code changes have been confirmed to execute properly by producing test vectors, which agree with the uGT firmware.
(3) all code changes have been confirmed to execute properly using "runTheMatrix.py -l 11634.0"

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by cecilecaillol** [comment]
please test

**Comment by cecilecaillol** [comment]
+l1

**Comment by silviodonato** [comment]
+1

> The workflows 140.53 have different files in step1_dasquery.log than the ones found in the baseline. You may want to check and retrigger the tests if necessary. You can check it in the "files" directory in the results of the comparisons

**Comment by rekovic** [comment]
@cavana @cecilecaillol 
We need a backport of this in 11_3_X.

**Comment by cavana** [comment]
@rekovic Will attempt today and report tomorrow.

**Pull request merged**
