### PR TITLE
Updated quality bits of KMTF 

### PR DESCRIPTION
**Pull request by bachtis**
#### PR description:

Per request of the L1 DPG based on studies of the BPH group we are sightly modifying the quality bit definition of KMTF

#### PR validation:
Tests of the performance and tests between hardware and emulator have been performed

Note that this is a minor change of the previous code . No propagated changes needed downstream for this change

@eyigitba @drkovalskyi @gmelachr

### CODE REVIEW

**Comment by aloeliger** [comment]
@bachtis Could you really quickly hit the auto-formatting (`scram build code-format`) for this PR? This should be quick after that.

**Comment by bachtis** [comment]
> @bachtis Could you really quickly hit the auto-formatting (`scram build code-format`) for this PR? This should be quick after that.

yep

**Comment by bachtis** [comment]
@aloeliger the code format patch is done

**Comment by epalencia** [comment]
Please test

**Comment by aloeliger** [comment]
+l1

**Comment by antoniovilela** [comment]
+1

**Comment by missirol** [comment]
@cms-sw/l1-l2 @eyigitba , should this PR be backported to 14_0_X ?

**Pull request merged**
