### PR TITLE
Fix the MadGraph bug for multithreading

### PR DESCRIPTION
**Pull request by colizz**
#### PR description:

Fix two scripts related to MadGraph multithread implementation.

- A MadGraph bug was recently observed in the multithread mode that influences the calculated cross-section for the multi-jet process: https://bugs.launchpad.net/mg5amcnlo/+bug/1884085
To fix this, We apply the corresponding patch to the MadGraph code when producing events from earlier gridpacks.
- Simplify the runcmsgrid patch to make it compatible with the current and future [runcmsgrid script](https://github.com/cms-sw/genproductions/blob/c5b912a886c0aadc9d17cd5893f8bd1a00b453a6/bin/MadGraph5_aMCatNLO/runcmsgrid_LO.sh).

#### PR validation:

The fix is on shell scripts, hence does not influence the CMSSW framework.
We tested the scripts on W+01234j and DY+01234j multi-jet processes to validate that the MG bug is solved.

(A quick test for this PR on [`SMP-MultiValidationUL17wmLHEGEN-00001`](https://cms-pdmv.cern.ch/mcm/requests?prepid=SMP-MultiValidationUL17wmLHEGEN-00001&page=0&shown=127))
```shell
cmsrel CMSSW_11_2_X_2020-06-28-0000
cd CMSSW_11_2_X_2020-06-28-0000/src/
cmsenv
git cms-merge-topic colizz:dev-mt-112X
curl -s --insecure https://cms-pdmv.cern.ch/mcm/public/restapi/requests/get_fragment/SMP-MultiValidationUL17wmLHEGEN-00001 --retry 2 --create-dirs -o Configuration/GenProduction/python/SMP-MultiValidationUL17wmLHEGEN-00001-fragment.py 
scram b -j 8
cd ../..
cmsDriver.py Configuration/GenProduction/python/SMP-MultiValidationUL17wmLHEGEN-00001-fragment.py --fileout file:SMP-MultiValidationUL17wmLHEGEN-00001.root --mc --eventcontent RAWSIM,LHE --datatier GEN,LHE --conditions 106X_mc2017_realistic_v6 --beamspot Realistic25ns13TeVEarly2017Collision --step LHE,GEN --geometry DB:Extended --era Run2_2017 --python_filename SMP-MultiValidationUL17wmLHEGEN-00001_1_cfg.py --no_exec --customise Configuration/DataProcessing/Utils.addMonitoring -n 400 --nThreads 4

cmsRun -e -j SMP-MultiValidationUL17wmLHEGEN-00001_rt.xml SMP-MultiValidationUL17wmLHEGEN-00001_1_cfg.py
```

### CODE REVIEW

**Comment by qliphy** [comment]
please test

**Comment by qliphy** [comment]
thanks @colizz
Do you think the patch should also be included in https://github.com/cms-sw/genproductions ?

**Comment by colizz** [comment]
> thanks @colizz
> Do you think the patch should also be included in https://github.com/cms-sw/genproductions ?

Thanks @qliphy.
I would suggest doing so when we officially move on to MG>=2.7.3.
The reason is that: for the current MG version in use (which is <=2.6.5), this patch must be used together with MG bug fix patches as implemented in `run_generic_tarball_cvmfs_madgraphLO_multithread.sh`, the wrapper of `runcmsgrid.sh`. Those fixes are gridpack version-dependent and a bit complicated to handle.
Therefore it is safer to keep all those stuff in CMSSW, and let CMSSW trigger the multithread feature.

With MG>=2.7.3, we can include this patch in `genproductions` (or directly apply this patch to runcmsgrid in `genproductions`), since all bugs are fixed.

**Comment by qliphy** [comment]
+1

**Comment by silviodonato** [comment]
please test workflow 551.0

**Comment by silviodonato** [comment]
+1

**Pull request merged**
