### PR TITLE
[BugFix]  DDG4ProductionCuts Debug Printout

### PR DESCRIPTION
**Pull request by ianna**
#### PR description:

* Instead of printing 
     *  a G4RegionStore pointer, print the G4RegionStore size 
     *  a G4Region pointer, print its name

```
  num  1 regionName: ZDCRegion, the store of size 2
DDG4ProductionCuts : regionName ZDCRegion, the store of size 2
DDG4ProductionCuts : region ZDCRegion
DDG4ProductionCuts : new G4Region ZDC
  num  1 regionName: TrackerDeadRegion, the store of size 3
DDG4ProductionCuts : regionName TrackerDeadRegion, the store of size 3
DDG4ProductionCuts : region TrackerDeadRegion
DDG4ProductionCuts : new G4Region Tracker
  num  1 regionName: TrackerSensRegion, the store of size 4
DDG4ProductionCuts : regionName TrackerSensRegion, the store of size 4
DDG4ProductionCuts : region TrackerSensRegion
DDG4ProductionCuts : new G4Region TOBWaferRphi4
  num  1 regionName: TrackerSensRegion, the store of size 5
  num  1 regionName: TrackerSensRegion, the store of size 5
```
here is how it was before:
```
  num  1 regionName: ZDCRegion 0x7fcdd78a12e0
DDG4ProductionCuts : regionName ZDCRegion 0x7fcdd78a12e0
DDG4ProductionCuts : region 0x7fcdcd3e9cc0
DDG4ProductionCuts : new G4Region ZDC
  num  1 regionName: TrackerDeadRegion 0x7fcdd78a12e0
DDG4ProductionCuts : regionName TrackerDeadRegion 0x7fcdd78a12e0
DDG4ProductionCuts : region 0x7fcdcd3e9d80
DDG4ProductionCuts : new G4Region Tracker
  num  1 regionName: TrackerSensRegion 0x7fcdd78a12e0
DDG4ProductionCuts : regionName TrackerSensRegion 0x7fcdd78a12e0
DDG4ProductionCuts : region 0x7fcdcd3e9e40
DDG4ProductionCuts : new G4Region TOBWaferRphi4
  num  1 regionName: TrackerSensRegion 0x7fcdd78a12e0
  num  1 regionName: TrackerSensRegion 0x7fcdd78a12e0
```
#### if this PR is a backport please specify the original PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by fabiocos** [comment]
@ianna @civanch a trivial conflict with #27588 has been fixed, I will take your signatures as good

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
+1

**Comment by ianna** [comment]
please test

**Comment by civanch** [comment]
+1
there is 880 failures in DQM but this cannot be due to this PR.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
