### PR TITLE
testEmptyHist.sh store RECO output in FEVTDEBUGHLT format

### PR DESCRIPTION
**Pull request by lveldere**

### CODE REVIEW

**Comment by lveldere** [comment]
please test

**Comment by lveldere** [comment]
+1

**Comment by davidlange6** [comment]
@lveldere - this PR does not merge -could you rebase?

**Comment by lveldere** [comment]
please test

**Comment by lveldere** [comment]
+1

**Comment by lveldere** [comment]
@davidlange6 

errors are not at all related to the pr

**Pull request merged**
