### PR TITLE
Introduce SiStripCalCosmics ALCARECO

### PR DESCRIPTION
**Pull request by mmusich**
Greetings,
the aim of this PR is to introduce a new SiStrip AlCaReco workflow meant as intermediate step for the production of SiStrip calibration trees to be used for monitoring and calibration purposes. 
An archetypal example of monitorable quantity with cosmic rays is the Strip Lorentz Angle, see e.g. details in this [presentation](https://indico.cern.ch/event/787656/contributions/3334666/attachments/1803298/2941971/20190227_SiStripCalib_LorentzAngle.pdf).
The new AlCaReco is in essence the cosmics version of `SiStripCalMinBias` adapted to work with a different input track collection and adjusting the acceptance cuts.
The new workflow has been fully interlaced with RelVals and AlCaReco matrix via `autoAlCa`.
Typical output file sizes are ~ 2kB/evt (for comparison the output of the whole 2018 Commissioning dataset is <0.5TB).
Tested locally via: `runTheMatrix.py -l 7.21,7.22,7.3,7.4`
@robervalwalsh FYI

### CODE REVIEW

**Comment by prebello** [comment]
please test

**Comment by kpedro88** [comment]
+upgrade

**Comment by prebello** [comment]
+1

**Comment by pohsun** [comment]
+1

**Comment by fabiocos** [comment]
please test workflow 7.21,7.22,7.3,7.4

**Comment by fabiocos** [comment]
+operations

the update of StandardSequences looks coherent with the purpose of the PR

**Comment by fabiocos** [comment]
+1

**Pull request merged**
