### PR TITLE
(DAQ) jsoncpp moved to a namespace (14_0_X backport)

### PR DESCRIPTION
**Pull request by smorovic**
#### PR description:

Moved to jsoncollector namespace to avoid conflict with tensorflow import of this lib (newer version).

#### PR validation:

Tested in DAQ test system and produces valid json files.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport of #44989
See also:
https://github.com/cms-sw/cmssw/issues/44975

### CODE REVIEW

**Comment by smorovic** [comment]
@cmsbuild please test

**Comment by smorovic** [comment]
+daq

**Comment by mmusich** [comment]
+hlt
   * verified that this PR on top of `CMSSW_14_0_X_2024-05-16-2300` passes the test with recipe at https://github.com/cms-sw/cmssw/issues/44975#issue-2297728164

**Comment by mmusich** [comment]
type bug-fix

**Comment by mmusich** [comment]
backport of https://github.com/cms-sw/cmssw/pull/44989

**Comment by rappoccio** [comment]
+1

**Pull request merged**
