### PR TITLE
Phase2-sim81 Give an example with no tracker simulation for HGCal

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Give an example with no tracker simulation for HGCal

#### PR validation:

Use the cfg file in Geometry/HGCalCommonData/test/python

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

**Comment by qliphy** [comment]
+1

**Pull request merged**
