### PR TITLE
[DQM] Fix for bug in DT DQM at Online 12_4_X

### PR DESCRIPTION
**Pull request by jfernan2**
PR description:
Fixed bug in folder which had been renamed, the bug was affecting Online DQM only

Tested privately in Online mode

Backport of https://github.com/cms-sw/cmssw/pull/38802

### CODE REVIEW

**Comment by jfernan2** [comment]
backport of #38802

**Comment by jfernan2** [comment]
test parameters:
- addpkg = DQM/Integration

**Comment by jfernan2** [comment]
please test

**Comment by emanueleusai** [comment]
type muon

**Comment by emanueleusai** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
