### PR TITLE
Run3-hcx370 Protection to avoid unphysical ZDC SimHits which caused crashes during digitization (backport #46286)

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Protection to avoid unphysical ZDC SimHits which caused crashes during digitization (backport #46286)

#### PR validation:

Use the runTheMatrix test workflows

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport of #46286

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by bsunanda** [comment]
@mandrenguyen, @rappoccio, @antoniovilela Please merge this for 14_1_X

**Comment by mandrenguyen** [comment]
+1

**Comment by mandrenguyen** [comment]
backport of https://github.com/cms-sw/cmssw/pull/46286

**Pull request merged**
