### PR TITLE
Fixed path names. Removed pt2 and pt3 in unnecessary cases. Added debug print (dump # of HLT passed events). Replace cout to DebugLog. Updated paths (PhotonMET, PureMET, DiPhoton, HighPtPhoton).

### PR DESCRIPTION
**Pull request by ryonamin**
This is a PR replaced instead of #11047 (There was a problem to be merged).
Also this is included a latest request that corresponds to #11453. ==> Decided to remove this change and make this change at #11151 (see below).
==> In summary, Backport from 76X to 75X (#10907,#10974, #11219).

### CODE REVIEW

**Comment by deguio** [comment]
ciao @ryonamin 
sorry but I am confused now. 
the rebase is fine, but the equivalent of #11453 should go on top of #11151 and not here.
otherwise I fear that as soon as the first one is merged, the second won't merge anymore.
F.

**Comment by ryonamin** [comment]
Oh, sorry! You're complete correct. I made a mistake. Do you think I can get the change (#11453) back, and add it to #11151?

**Comment by deguio** [comment]
yep.
go ahead.
thanks,
F.

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
let's see how it goes...
in principle you could have just removed commit 9a5b543 and following.

**Comment by deguio** [comment]
typo to be fixed. see:
https://github.com/cms-sw/cmssw/pull/11456/files#diff-e39cf2b11b6cc26b6dc8db0f427a819dR15

could you just remove those two new files? they will be added anyway with PR #11151 
thanks,
F.

**Comment by ryonamin** [comment]
Sorry again, I messed up. I think I should remove changes (e.g. DST_...) in CaloHT and PFHT because otherwise I guess it will conflict with #11151. So I'm thinking to close this PR and make a new PR that has only the original changes (without Calo and PFHT). Do you think it will work fine? Thank you in advance!

**Comment by ryonamin** [comment]
I have learned again thanks to you. Sorry for my mess.

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1

**Pull request closed without merging**
