### PR TITLE
Update python code to latest standards?

### PR DESCRIPTION
**Pull request by ericvaandering**
Done with `futurize -1 -nw -x print_with_import .`

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by perrotta** [comment]
please test
(to clean up the results of the tests)

**Comment by arunhep** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by perrotta** [comment]
+1
Technical changes: they do make sense, and it seem to work
No changes in jenkins outputs (none expected)

**Comment by davidlange6** [comment]
merge

**Pull request merged**
