### PR TITLE
Deployment of a 2-input (AOD+parent RAW) workflow in the matrix

### PR DESCRIPTION
**Pull request by fabozzi**
runTheMatrix code is extended to allow a workflow which has in input AOD+ parent RAW. 
An example is now exercised in the matrix.

Use case: re-do HLT on the fly and give it in input to DQM:offlineHLTSourceOnAOD for a fast HLT validation turnaround (useful to extend HLT menu validation procedures). 

It has already been tested that WMAgent is able to deal with such a workflow.

### CODE REVIEW

**Comment by fabozzi** [comment]
please test workflow 136.7803

**Comment by fabozzi** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
