### PR TITLE
Fix CMS deprecation warnings in L1TriggerConfig/GctConfigProducers

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

- changed to thread friendly types
- added esConsumes

#### PR validation:

Code compiles without issuing deprecation warnings.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
Please test

**Comment by cecilecaillol** [comment]
+l1

**Comment by perrotta** [comment]
+1

**Pull request merged**
