### PR TITLE
Fixing RecoLocalTracker/SiPixelRecHits/src/SiPixelTemplate.cc and header

### PR DESCRIPTION
**Pull request by mrodozov**
This PR substitutes https://github.com/cms-sw/cmssw/pull/22611 with the changes proposed in https://github.com/cms-sw/cmssw/pull/22458 . Tested on aarch64 and confirmed to fix the issue

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by fabiocos** [comment]
@mrodozov this PR needs to be rebased

**Comment by mrodozov** [comment]
@fabiocos the purpose of this PR was to bring some changes from #22458 which now is merged, so I'm closing this one

**Comment by fabiocos** [comment]
@mrodozov thanks for the clarification

**Pull request closed without merging**
