### PR TITLE
[12_3_X] Safeguard for nHits==0

### PR DESCRIPTION
**Pull request by AdrianoDee**
#### PR description:

Backport to 12_3_X of #38159 

Following discussion in #37933

### CODE REVIEW

**Comment by AdrianoDee** [comment]
type trk

**Comment by AdrianoDee** [comment]
type bugfix

**Comment by AdrianoDee** [comment]
test parameters:

- enable_tests = gpu
- workflows_gpu = 11634.503, 11634.502, 39434.502
- workflows = 11634.501, 39434.501, 11634.502
- relvals_opt= -w standard,highstats,pileup,generator,extendedgen,production,upgrade,cleanedupgrade,ged

**Comment by AdrianoDee** [comment]
please test

**Comment by perrotta** [comment]
@AdrianoDee could you please give a more descriptive title to the PR, for example the same of the backported one?

**Comment by AdrianoDee** [comment]
> @AdrianoDee could you please give a more descriptive title to the PR, for example the same of the backported one?

Sure, moved to the original PR title

**Comment by AdrianoDee** [comment]
please test

**Comment by tvami** [comment]
backport of https://github.com/cms-sw/cmssw/pull/38159

**Comment by jpata** [comment]
Just to confirm: the validation picks up some fluctuations in pixel tracks.

This is not observed in this PR for 12_5 or 12_4. Is this an expected side-effect of this PR, or is it a random thing?

**Comment by missirol** [comment]
In my understanding, wf [`11634.506`](https://cmsweb.cern.ch/dqm/dev/start?runnr=1;dataset%3D/RelVal_wf11634_506_pr/CMSSW_12_3_X-PRcmssw_38160-50653/DQMIO;referenceshow%3Dall;referencenorm=False;referenceobj1%3Dother::/RelVal_wf11634_506_base/CMSSW_12_3_X-PRcmssw_38160-50653/DQMIO::;sampletype%3Doffline_relval;workspace%3DEverything;) is known to produce at times non-reproducible outputs (tiny differences).

**Comment by AdrianoDee** [comment]
> This is not observed in this PR for 12_5 or 12_4. Is this an expected side-effect of this PR, or is it a random thing?

Having inspected the changes I'd say that these are random differences, yes.

**Comment by silviodonato** [comment]
@qliphy @perrotta , please consider to include this PR in the next 12_3_X release which might avoid a crash in the HLT in runs without Pixels

**Comment by jpata** [comment]
+reconstruction
- backport of https://github.com/cms-sw/cmssw/pull/38159
- technical bugfix

**Comment by qliphy** [comment]
+1

**Pull request merged**
