### PR TITLE
PA vtx smearing and auto cond 80X

### PR DESCRIPTION
**Pull request by mandrenguyen**
Update of vertex smearing and corresponding reco BS.
Backport of #16974 
Supersedes #16962 and #16787, which will now be closed

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by perrozzi** [comment]
+1

**Comment by mandrenguyen** [comment]
@fabozzi Can you please sign this 80X version as well, since you signed the 90X version?

**Comment by fabozzi** [comment]
+1

**Comment by mandrenguyen** [comment]
@davidlange6 Would be really great to get this in 80X shortly such that we can run GEN-SIM over the holidays.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
