### PR TITLE
Add default values to LocalTrajectoryParameters

### PR DESCRIPTION
**Pull request by davidlt**
Please, review the default values to see what __really__ makes sense.

Signed-off-by: David Abdurachmanov <David.Abdurachmanov@cern.ch>

### CODE REVIEW

**Comment by davidlt** [comment]
please test

**Comment by VinInn** [comment]
Why? what's the need to zero the memory? it has a cost...

**Comment by davidlt** [comment]
Compiler errors:
```
  /build/cmsbld/jenkins-workarea/workspace/build-any-ib/w/tmp/BUILDROOT/e0eb2f086f77fc0689f9e9b1fd785a9e/opt/cmssw/slc6_amd64_gcc700/cms/cmssw/CMSSW_9_0_X_2017-01-24-1100/src/RecoMuon/StandAloneTrackFinder/src/StandAloneTrajectoryBuilder.cc:282:20: error: 'seedVoid.TrajectorySeed::tsos_.PTrajectoryStateOnDet::theLocalParameters.LocalTrajectoryParameters::theQbp' may be used uninitialized in this function [-Werror=maybe-uninitialized]
      TrajectorySeed seedVoid;
                    ^~~~~~~~
  /build/cmsbld/jenkins-workarea/workspace/build-any-ib/w/tmp/BUILDROOT/e0eb2f086f77fc0689f9e9b1fd785a9e/opt/cmssw/slc6_amd64_gcc700/cms/cmssw/CMSSW_9_0_X_2017-01-24-1100/src/RecoMuon/StandAloneTrackFinder/src/StandAloneTrajectoryBuilder.cc:282:20: error: 'seedVoid.TrajectorySeed::tsos_.PTrajectoryStateOnDet::theLocalParameters.LocalTrajectoryParameters::theDxdz' may be used uninitialized in this function [-Werror=maybe-uninitialized]
   /build/cmsbld/jenkins-workarea/workspace/build-any-ib/w/tmp/BUILDROOT/e0eb2f086f77fc0689f9e9b1fd785a9e/opt/cmssw/slc6_amd64_gcc700/cms/cmssw/CMSSW_9_0_X_2017-01-24-1100/src/RecoMuon/StandAloneTrackFinder/src/StandAloneTrajectoryBuilder.cc:282:20: error: 'seedVoid.TrajectorySeed::tsos_.PTrajectoryStateOnDet::theLocalParameters.LocalTrajectoryParameters::theDydz' may be used uninitialized in this function [-Werror=maybe-uninitialized]
   /build/cmsbld/jenkins-workarea/workspace/build-any-ib/w/tmp/BUILDROOT/e0eb2f086f77fc0689f9e9b1fd785a9e/opt/cmssw/slc6_amd64_gcc700/cms/cmssw/CMSSW_9_0_X_2017-01-24-1100/src/RecoMuon/StandAloneTrackFinder/src/StandAloneTrajectoryBuilder.cc:282:20: error: 'seedVoid.TrajectorySeed::tsos_.PTrajectoryStateOnDet::theLocalParameters.LocalTrajectoryParameters::theX' may be used uninitialized in this function [-Werror=maybe-uninitialized]
```

https://github.com/cms-sw/cmssw/blob/CMSSW_9_0_X/RecoMuon/StandAloneTrackFinder/src/StandAloneTrajectoryBuilder.cc#L279

**Comment by slava77** [comment]
the code around the error is 
```C++
  TrajectorySeed seedForBW;

  if(theBWSeedType == "noSeed") {
    TrajectorySeed seedVoid;
    seedForBW = seedVoid;
  }

```

And line 282 mentioned in the error message is inside the "if " and it is probably referring to ```seedForBW = seedVoid``` (line 283).
The code inside this if has no effect.

@davidlt could you please check if removing these two lines will help instead

**Comment by slava77** [comment]
ping
@davidlt 
were you able to check an alternative fix from https://github.com/cms-sw/cmssw/pull/17276#issuecomment-275789393 
?

**Comment by davidlt** [comment]
@slava77 not this week, but I would still argue that having default values makes code safer (we have already seen how random stuff in memory can affect things).

**Comment by slava77** [comment]
On 2/2/17 10:07 AM, davidlt wrote:
> @slava77 <https://github.com/slava77> not this week, but I would still
> argue that having default values makes code safer (we have already seen
> how random stuff in memory can affect things).
> 

It seems to me that compiler is capable to capture use of uninitialized
values.
Is it not good enough in this case to warrant initialization?

**Comment by davidlt** [comment]
The compiler can capture only some of cases. We had found bugs in the past where compiler wasn't warning us about this.

**Comment by slava77** [comment]
@VinInn @rovere @makortel 
do you have an example of an algorithm/config particularly heavy on LocalTrajectoryParameters use to check the cost.
I'm guessing that initialization will not be really visible in the full reco or even just tracking setup (at least not in igprof due to inlined inits)

**Comment by VinInn** [comment]
I think that the compiler can optimize away if realize that those values are never used.
Is more on a matter of principle: we cannot go through one by one all actual use cases:
initializing with junk (and 0 in this case IS junk) is not much better than not initializing at all.

**Comment by slava77** [comment]
On 2/3/17 9:01 AM, Vincenzo Innocente wrote:
> I think that the compiler can optimize away if realize that those values
> are never used.
> Is more on a matter of principle: we cannot go through one by one all
> actual use cases:
> initializing with junk (and 0 in this case IS junk) is not much better
> than not initializing at all.

Thanks for the inputs.
I guess this means we can as well integrate this PR as is.

**Comment by davidlange6** [comment]
is it perhaps more clear/worrisome if these go into the default constructor (naively there only to keep the classes.h happy?)

**Comment by slava77** [comment]
On 2/3/17 9:27 AM, David Lange wrote:
> is it perhaps more clear/worrisome if these go into the default
> constructor (naively there only to keep the classes.h happy?)
> 

Moving the initialization to the default constructor instead of the defaults
will solve the compiler error as well,
but the result will be the same because all other constructors set data
values for all members.

Clearly ,the default constructor is not only in classes.h
The place that lead to the compiler error is in MuonSeedCreator.cc

So, this doesn't really change the arguments.

**Comment by davidlange6** [comment]
I see.  Thanks for the pointer.

naively simple code changes could avoid the need in MuonSeedCreator - these changes could avoid the rather duplicative construct in place there currently. If the initialization is important enough to discuss, perhaps MuonSeedCreator should be changed (as its currently doing: default constructor, real constructor, == operator). Anyway, just suggestions

**Comment by VinInn** [comment]
> On 3 Feb, 2017, at 10:20 AM, David Lange <notifications@github.com> wrote:
> 
> naively simple code changes could avoid the need in MuonSeedCreator - these changes could avoid the rather duplicative construct in place there currently. If the initialization is important enough to discuss, perhaps MuonSeedCreator should be changed (as its currently doing: default constructor, real constructor, == operator). Anyway, just suggestions 
Indeed, who?
Most probably there are other few 1000s of places with code similar to this.... 
shall we open a Jira ticket?

v.

**Comment by davidlt** [comment]
Here is an update: https://github.com/cms-sw/cmssw/pull/17457

**Pull request closed without merging**
