### PR TITLE
Run3-alca211B Make an application to study isotracks using generated particles

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Make an application in Calibration/HcalCalibAlgos to study isotracks using generated particles

#### PR validation:

Tested using a MC Reco dataset

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by tvami** [comment]
@bsunanda what was the incentive to not include the content of this PR in the https://github.com/cms-sw/cmssw/pull/36181 ?

**Comment by tvami** [comment]
@yuancho can you please take this one? I'll review the other one.

**Comment by bsunanda** [comment]
@tvami  The other came out while trying to work with tuning a new reconstruction algorithm and it was ready for a while. I only forgot to commit them. The second one came out while reviewing isotrack calibration and we need some time to put it in place for use. This PR is made so that we can share the work among a group of people.

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by tvami** [comment]
@yuanchao have you had the chance to review this?

**Comment by bsunanda** [comment]
@tvami @yuanchao Ping for a review and inclusion

**Comment by yuanchao** [comment]
+1
Sorry for the delay
* example analyzer
* tests passed ok

**Comment by qliphy** [comment]
+1

**Pull request merged**
