### PR TITLE
Fixes and modifications on GEM TnP efficiency plots (backport of #42639, 13_0_X)

### PR DESCRIPTION
**Pull request by jo100sun**
#### PR description:

Backport of (#42639)[https://github.com/cms-sw/cmssw/pull/42639]. This PR introduces updates on GEM TnP efficiency plots and bugfix for the GEM edge distance calculation at TrackerMuon propagation. (#40554)[https://github.com/cms-sw/cmssw/pull/40554]

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

This PR is backport of (#42639)[https://github.com/cms-sw/cmssw/pull/42639]. We would like to introduce this changes for upcoming run.

@jshlee @watson-ij

### CODE REVIEW

**Comment by mandrenguyen** [comment]
type muon, bug-fix

**Comment by mandrenguyen** [comment]
please test

**Comment by mandrenguyen** [comment]
+1

**Comment by rappoccio** [comment]
@cms-sw/dqm-l2  is this okay to sign for 13_0?

**Comment by emanueleusai** [comment]
+1

- tests at P5 ok
- DQM differences in Muon plots as expected
- DQM differences in 12434.7 not related to this PR

**Comment by rappoccio** [comment]
+1

**Comment by jo100sun** [comment]
Hello @emanueleusai , can you tell me when this PR will be available to see at cmsweb?

**Comment by syuvivida** [comment]
Hi @jo100sun as you know the HI data will be processed with 13_2_X. Do you need these plots to be fixed/displayed for HI runs? I see https://github.com/cms-sw/cmssw/pull/42687 is merged but not yet included in 13_2_3 ([current version run at Tier-0](https://cms-talk.web.cern.ch/t/t0-production-change-to-run2023f/29318)). If yes, we need to ask to build a new release to include this PR.

**Comment by jo100sun** [comment]
> Do you need these plots to be fixed/displayed for HI runs? 
Yes exactly. I saw my changes are included in [13_2_4](https://github.com/cms-sw/cmssw/releases/tag/CMSSW_13_2_4). Will this change apply to DQM also?

**Pull request merged**
