### PR TITLE
Update of ECAL conditions for Run3 MC production 12_4

### PR DESCRIPTION
**Pull request by tvami**
#### PR description:

Update of ECAL conditions for Run3 MC production 12_4 as requested in 
https://cms-talk.web.cern.ch/t/gt-mc-update-of-ecal-conditions-for-run3-mc-production-12-4/12134

 these GTs
```
124X_mcRun3_2022cosmics_realistic_deco_v8
124X_mcRun3_2022_realistic_HI_v7
124X_mcRun3_2022_realistic_v7
```

The diff wrt to the previous versions are
**phase1_2022_realistic**

https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts//124X_mcRun3_2022_realistic_v6/124X_mcRun3_2022_realistic_v7

**phase1_2022_cosmics**

https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts//124X_mcRun3_2022cosmics_realistic_deco_v7/124X_mcRun3_2022cosmics_realistic_deco_v8

**phase1_2022_realistic_hi**

https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts//124X_mcRun3_2022_realistic_HI_v6/124X_mcRun3_2022_realistic_HI_v7

The diffs are in the requested tags only.

#### PR validation:

```
test parameters:
  - workflows = 12034.0,11634.0,7.23,159.0,12434.0,12834.0
 ```

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Will be backported to 12_4_X

### CODE REVIEW

**Comment by tvami** [comment]
test parameters:
  - workflows = 12034.0,11634.0,7.23,159.0,12434.0,12834.0

**Comment by tvami** [comment]
type ecal

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
urgent
 * should be in the 2300 IB so that the backport had a day before merging

**Comment by tvami** [comment]
> are the new conditions touching the digitization step?

Yes they are!

**Comment by mmusich** [comment]
> Yes they are!

so no wonder there are changes all over the place. The simulation histories are changed as a consequence of the conditions updates.

**Comment by perrotta** [comment]
+1

**Pull request merged**
