### PR TITLE
Back port of Z->ee Skim for Run2 to 74X

### PR DESCRIPTION
**Pull request by emanueledimarco**
This is a 74X back port of #9548

### CODE REVIEW

**Comment by franzoni** [comment]
please test

**Comment by emanueledimarco** [comment]
same change as in #9548 
@shervin86 please also follow this.

**Comment by franzoni** [comment]
please test

**Comment by franzoni** [comment]
+1

re-tested :   

cmsDriver.py skims -s SKIM:ZElectron --data --dasquery=file dataset=/SingleElectron/CMSSW_7_4_0-GR_R_74_V10A_RelVal_electron2012A-v1/RECO -n 100 --conditions auto:com10 --python_filename=ZElectron_SKIM.py --processName=SKIMZElectron --no_exec

which runs ok.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
