### PR TITLE
Minor style modification to avoid unnecessary line splitting

### PR DESCRIPTION
**Pull request by fabiocos**
#### PR description:

Move comments to avoid not needed line splitting after the integration of #26985 and #26987 

#### PR validation:

The code compiles.

### CODE REVIEW

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
@kpedro88 @rekovic this is trivial, and ultimately a matter of taste. I propose this solution, although the original version is not strictly speaking wrong

**Comment by kpedro88** [comment]
+upgrade

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Pull request merged**
