### PR TITLE
ECAL - Add integrity checks for strip and xtal ids to GPU unpacker - 130X

### PR DESCRIPTION
**Pull request by thomreis**
#### PR description:

This PR adds integrity checks for strip ID and xtal ID to the GPU unpacker similar to the ones that exist in the CPU unpacker. This avoids crashes like the ones reported in https://github.com/cms-sw/cmssw/issues/39568

For events with data corruption in a tower a difference in the number of unpacked digis can occur between the CPU unpacker and the GPU one because the former stops unpacking the tower if an inconsistency is detected in one channel, whereas the later unpacks the channels in parallel and an inconsistency in one channel does not affect the unpacking in other threads.
In many cases, however, an integrity problem in the raw data affects most of the channels in the tower. From the three instances reported in https://github.com/cms-sw/cmssw/issues/39568 this year only one resulted in a difference of one digi being produced after the fix.

#### PR validation:

* Does not crash anymore on runs 367771, 368547, 368724 set up with the recipe provided in https://github.com/cms-sw/cmssw/issues/39568#issuecomment-1557565628 .
* Passes matrix tests 12434.512, 12434.513, and 12434.514
* No differences seen between CPU and GPU digis on 7750 events from /store/relval/CMSSW_13_0_0/RelValTTbarToDilepton_14TeV/GEN-SIM-DIGI-RAW/130X_mcRun3_2022_realistic_v2-v3/00000/

Backport of #41977 for HLT to avoid crashes when encountering invalid detector IDs in the raw data.

### CODE REVIEW

**Comment by thomreis** [comment]
type ecal

**Comment by thomreis** [comment]
enable gpu

**Comment by thomreis** [comment]
backport of #41977

**Comment by thomreis** [comment]
please test

**Comment by clacaputo** [comment]
+reconstruction

**Pull request merged**
