### PR TITLE
fix fillDescr config of PFRecoTauChargedHadronProducer

### PR DESCRIPTION
**Pull request by swozniewski**
Adresses issue raised in PR #26254 concerning VPSets in PFRecoTauChargedHadronProducer.
Adds default VPSets to PFRecoTauChargedHadronProducer fillDescription.
Renames old cfi to cff and clones new auto-generated cfi.
@perrotta

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by fabiocos** [comment]
please test

**Comment by perrotta** [comment]
+1
- Configuration of PFRecoTauChargedHadronProducer adjusted in the fillDescription method
- The VPset's reported missing in https://github.com/cms-sw/cmssw/pull/26254#issuecomment-478485336 are now present in the generated cfi file
- Jenkins tests pass with no differences, as expected

**Comment by fabiocos** [comment]
+1

**Pull request merged**
