### PR TITLE
Fixes for code rule violations in Validation/RecoB and HLTriggerOffline/SUSYBSM

### PR DESCRIPTION
**Pull request by fabiocos**
#### PR description:

During the recent code-format migration, that is systematically accessing all the packages, two code rules violations have been spotted in Validation/RecoB and HLTriggerOffline/SUSYBSM. This PR addresses them, ~~with the exception so far of one try - catch block whose purpose is not clear to me~~.

#### PR validation:

Code compiles and passes basic code quality tests.

### CODE REVIEW

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
@slava77 @perrotta @Martin-Grunewald in your experience is it clear what is the purpose of this try - catch protection
https://cmssdt.cern.ch/lxr/source/HLTriggerOffline/SUSYBSM/src/SUSY_HLT_SingleLepton.cc#0068 ?
If at this point both the validity of the GsfElectron track and of the conversion is checked, I am not sure what other kind of protection is possibly needed. Browsing around for similar patters I do no see such kind of test.

**Comment by slava77** [comment]
just git grepping shows that https://cmssdt.cern.ch/lxr/source/HLTriggerOffline/SUSYBSM/src/SUSY_HLT_SingleLepton.cc#0068 is the only place where try/catch is used on this method.
I don't know offhand why it would throw.

**Comment by fabiocos** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
