### PR TITLE
Improve MultiTrackValidator performance

### PR DESCRIPTION
**Pull request by makortel**
This PR reduces the time spent in MultiTrackValidator in RAW2DIGI,RECO,VALIDATION,DQM jobs using TTbar + 35@25ns PU events by a factor of 25. The main sources of improvement are (in descending order, roughly)
- LogInfo/LogVerbatim -> LogDebug/LogTrace (5x improvement ...)
- Precalculate TP momentum+vertex wrt PCA for TPs passing the efficiency selection (instead of repeating them for all input track collections)
- Eliminate (repeated) string comparisons in `analyze()`
- Inline all trivial TrackingParticle accessors
- Tune TrackingParticleSelector, do the efficiency-selection only once (instead of repeating for all input track collections)

A side effect is that now the dEdx-histograms are filled also for the subcollections of generalTracks, and the histograms are not booked for MTV instances other than the one for FullSim pp validation.

Tested in CMSSW_7_5_X_2015-05-03-1100+#8888 and rebased (+tested with limited matrix) on top of CMSSW_7_5_X_2015-05-07-1100 for IB containing #8888. No changes are expected in already-filled histograms. 

@rovere @VinInn

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
this is very nice.. :)
thanks @makortel

**Comment by makortel** [comment]
Fixed the clang compilation error.

**Comment by civanch** [comment]
please test

**Comment by deguio** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
