### PR TITLE
Tracking HLT validation cleanup

### PR DESCRIPTION
**Pull request by makortel**
This PR cleans up the HLT tracking validation configurations, and adds a flag to MultiTrackValidator to control if the min(DeltaR) should be calculated wrt. a single reference collection (old behaviour), or wrt. each track collection to itself (the behaviour needed here). This allows merging the four MTV instances into a single one, which further makes the summary plots meaningful (now they contain all the monitored HLT track collections instead of a single one). Add a DQMGenericClient to produce the efficiency, fake rate etc. for the summary plots as in offline validation.

Tested in CMSSW_7_6_X_2015-07-29-2300, expecting following changes only
- MTV summary and simulation plots contain all monitored HLT track collections separately instead of being merged to a single bin
- summary plots contain now efficiency, fake rate etc.

@rovere @VinInn @mtosi

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
by cloning the postProcessorTrack a number of histograms is added in the harvesting step. is this needed/wanted (apart from the summary ones you mention)?

**Comment by makortel** [comment]
I would say yes, we want to keep the HLT instance in sync with the offline one also for harvesting step (sorry for forgotting to mention these). Their input histograms were anyway already produced. (and if it turns out that something is not needed/wanted, we should remove these input histograms from MTV too from the HLT instance).

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
