### PR TITLE
[HGCAL trigger] Auto-encoder for ECON-T data compression

### PR DESCRIPTION
**Pull request by jbsauvan**
Adding @dnoonan08 

#### PR description:
This PR implements an additional data compression algorithm, an auto-encoder, for the frontend ECON-T.
It is not enabled by default, and the default behaviour of the HGCAL TPG is not affected.

Details on this auto-encoder can be found in this presentation :
https://indico.cern.ch/event/987946/contributions/4174157/
(the slides include links to older presentations as well)

Depends on external cms-data/L1Trigger-L1THGCal#21

#### PR validation:

Tested workflows
```
runTheMatrix.py -w upgrade -l 23234.0 --maxSteps=2                                                                                                                                                                                                                                
runTheMatrix.py -w upgrade -l 28234.0 --maxSteps=2                                                                                                                                                                                                                              
runTheMatrix.py -w upgrade -l 31434.0 --maxSteps=2
```

### CODE REVIEW

**Comment by cecilecaillol** [comment]
please test

**Comment by jbsauvan** [comment]
It needs to be tested with cms-data/L1Trigger-L1THGCal#21, otherwise there are missing data files

**Comment by kpedro88** [comment]
test settings
* pull_request = https://github.com/cms-data/L1Trigger-L1THGCal/pull/21

**Comment by kpedro88** [comment]
please test

**Comment by kpedro88** [comment]
test parameters
pull_request = cms-data/L1Trigger-L1THGCal#21

**Comment by kpedro88** [comment]
please test

**Comment by cecilecaillol** [comment]
+l1

**Comment by srimanob** [comment]
Hi @jbsauvan 
How this PR can be tested exactly? As you mentioned that this new data compression algorithm is not on by default, only the private test can be done? Thanks for clarification.

**Comment by jbsauvan** [comment]
Hi @srimanob 
We have a test config to test various algorithms `L1Trigger/L1THGCalUtilities/test/testHGCalL1T_multialgo_V11_cfg.py`. But it is not up to date in this PR. We have a more recent one in our development branch; I will add a commit to make it available here.

**Comment by jbsauvan** [comment]
Hi @srimanob 
I just added the updated test config

**Comment by srimanob** [comment]
Please test

This is just to trigger for the updated PR, no change is expected. Thanks @jbsauvan

**Comment by srimanob** [comment]
+Upgrade

**Comment by cecilecaillol** [comment]
+l1

**Comment by qliphy** [comment]
+1

**Pull request merged**
