### PR TITLE
Clean unused dependencies from BuildFiles

### PR DESCRIPTION
**Pull request by guitargeek**
#### PR description:

Another quick BuildFile cleaning PR in the style of many before (for example https://github.com/cms-sw/cmssw/pull/36834).

In many cases, the dependencies had to be moved to the appropriate BuildFile, for example from a plugins directory to the library directory or vice versa.

This PR cleans unnecessary includes from CMSSW BuildFiles that were added in the last months.

#### PR validation:

CMSSW compiles.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

No backport intended.

### CODE REVIEW

**Comment by AdrianoDee** [comment]
Please test

**Comment by fwyzard** [comment]
+heterogeneous

**Comment by AdrianoDee** [comment]
+upgrade

**Comment by emanueleusai** [comment]
+1

**Comment by tvami** [comment]
+1
 * technical PR

**Comment by SiewYan** [comment]
+1

**Comment by cecilecaillol** [comment]
+l1

**Comment by jpata** [comment]
+reconstruction
- technical

**Comment by perrotta** [comment]
+1

**Pull request merged**
