### PR TITLE
Re-insert layer 678 in PFX to recover efficiency in D11 wf

### PR DESCRIPTION
**Pull request by ebrondol**
Title say it all.

### CODE REVIEW

**Comment by ebrondol** [comment]
It has been tested on top of the PR #17891 . 
These are the efficiency results for D4(left) and D11 (right) for ttbar sample without PU
screenshot from 2017-03-14 15 46 34
These are the fakerate results for D4(left) and D11 (right) for ttbar sample without PU200
screenshot from 2017-03-14 15 47 02
In all plots blue is the reference and red is +thisPR & #17891 .

**Comment by ebrondol** [comment]
@VinInn can you please check how the timing change with these two PR?

Informing @kpedro88

**Comment by kpedro88** [comment]
assign upgrade

**Comment by kpedro88** [comment]
@ebrondol should official tests be run with #17891?

**Comment by ebrondol** [comment]
@kpedro88 no, the tests can be run just on this PR alone.
For the performance results can also be tested alone. For timing results I would prefer to test it on top of the other one to have an reasonable idea.

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by VinInn** [comment]
Timing 64 events on 6 threads
"tracking only" no dqm

this PR + #17891 
```
TimeReport ---------- Event  Summary ---[sec]----
TimeReport       event loop CPU/event = 106.984537
TimeReport      event loop Real/event = 19.187352
TimeReport     sum Streams Real/event = 110.525152
grep TimeReport recoNew678.log | grep Candi | awk '{s+=$2} END {print s}' 
47.7355
```

#17891 
```
TimeReport ---------- Event  Summary ---[sec]----
TimeReport       event loop CPU/event = 87.795315
TimeReport      event loop Real/event = 16.441992
TimeReport     sum Streams Real/event = 93.341641
grep TimeReport recoNew.log | grep Candi | awk '{s+=$2} END {print s}'
37.6698
```

so 27% increase in pattern recognition...

**Comment by slava77** [comment]
On 3/14/17 8:58 AM, Vincenzo Innocente wrote:
> Timing 64 events on 6 threads
> "tracking only" no dqm
> 
> this PR + #17891 <https://github.com/cms-sw/cmssw/pull/17891>
> 
> |TimeReport ---------- Event Summary ---[sec]---- TimeReport event loop
> CPU/event = 106.984537 TimeReport event loop Real/event = 19.187352
> TimeReport sum Streams Real/event = 110.525152 grep TimeReport
> recoNew678.log | grep Candi | awk '{s+=$2} END {print s}' 47.7355 |
> 
> #17891 <https://github.com/cms-sw/cmssw/pull/17891>
> 
> |TimeReport ---------- Event Summary ---[sec]---- TimeReport event loop
> CPU/event = 87.795315 TimeReport event loop Real/event = 16.441992
> TimeReport sum Streams Real/event = 93.341641 grep TimeReport
> recoNew.log | grep Candi | awk '{s+=$2} END {print s}' 37.6698 |
> 
> so 27% increase in pattern recognition...

Is this for D4 or for D11?

**Comment by VinInn** [comment]
is D4,
but I suspect something changed (I had to change base release) as everything seem to have increased by 20%....  (hgcal, output module...)
```
[innocent@vinavx2 ttbar]$ grep TimeReport recoNew.log | grep Candi
TimeReport   0.001191     0.001191     0.001191  convTrackCandidates
TimeReport   0.284270     0.284270     0.284270  detachedQuadStepTrackCandidates
TimeReport   1.642745     1.642745     1.642745  duplicateTrackCandidates
TimeReport   0.390376     0.390376     0.390376  generalV0Candidates
TimeReport   3.235267     3.235267     3.235267  highPtTripletStepTrackCandidates
TimeReport   9.885673     9.885673     9.885673  initialStepTrackCandidates
TimeReport  10.629926    10.629926    10.629926  lowPtQuadStepTrackCandidates
TimeReport   5.187097     5.187097     5.187097  lowPtTripletStepTrackCandidates
TimeReport   0.208074     0.208074     0.208074  muonSeededTrackCandidatesInOut
TimeReport   6.205138     6.205138     6.205138  pixelPairStepTrackCandidates
[innocent@vinavx2 ttbar]$ grep TimeReport recoNew678.log | grep Candi
TimeReport   0.001480     0.001480     0.001480  convTrackCandidates
TimeReport   0.363169     0.363169     0.363169  detachedQuadStepTrackCandidates
TimeReport   2.172430     2.172430     2.172430  duplicateTrackCandidates
TimeReport   0.530847     0.530847     0.530847  generalV0Candidates
TimeReport   3.725894     3.725894     3.725894  highPtTripletStepTrackCandidates
TimeReport  12.403102    12.403102    12.403102  initialStepTrackCandidates
TimeReport  13.918701    13.918701    13.918701  lowPtQuadStepTrackCandidates
TimeReport   6.397084     6.397084     6.397084  lowPtTripletStepTrackCandidates
TimeReport   0.277177     0.277177     0.277177  muonSeededTrackCandidatesInOut
TimeReport   7.945651     7.945651     7.945651  pixelPairStepTrackCandidates
```
look to pixelPair: why should change? ignore for the time being...

**Comment by VinInn** [comment]
apologies for the confusion of the previous reports about timing (thay I will delete)
so here is
```
[innocent@vinavx2 ttbar]$ grep TimeRep recoNew678.log | head -n 4
TimeReport ---------- Event  Summary ---[sec]----
TimeReport       event loop CPU/event = 106.984537
TimeReport      event loop Real/event = 19.187352
TimeReport     sum Streams Real/event = 110.525152
[innocent@vinavx2 ttbar]$ grep TimeRep recoNew_2.log | head -n 4
TimeReport ---------- Event  Summary ---[sec]----
TimeReport       event loop CPU/event = 104.536232
TimeReport      event loop Real/event = 18.721179
TimeReport     sum Streams Real/event = 107.713895
[innocent@vinavx2 ttbar]$ grep TimeReport recoNew_2.log | grep Candi | awk '{s+=$2} END {print s}'
46.6194
[innocent@vinavx2 ttbar]$ grep TimeReport recoNew678.log | grep Candi | awk '{s+=$2} END {print s}'
47.7355
```

so only 2% slower (and this makes much more sense)

**Comment by kpedro88** [comment]
@VinInn thanks for double checking, I am much happier with that

**Comment by ebrondol** [comment]
@kpedro88 Any news on this? We would like to put them in the new release because of the importance for the efficiency plot for the TDR

**Comment by kpedro88** [comment]
Looking at the comparisons for 20234 (D4):

Changes in higher-level quantities and most tracking quantities are minimal.

Changes in pixel tracks are concentrated at high eta and low pt:
pixeltrack eta
pixeltrack pt

A few places in the comparison have larger changes. @ebrondol, can you confirm these are expected? Examples:

cutsRecoLowPtQuadStep_trackingParticleRecoAsssociation


cutsRecoHighPtTripletStep_trackingParticleRecoAsssociation


@slava77 or @perrotta should also review

**Comment by makortel** [comment]
The `*_dzpvcut*` histograms are cumulative, so tiny changes accumulate to larger changes as the x increases (and `*_dzpvcut_pt` ones can be unstable when DIGI-RAW changes).

**Comment by kpedro88** [comment]
@makortel okay, that makes sense. I guess it also makes sense (given other plots) that we observe an overall increase for low pt steps and a decrease for high pt steps.

**Comment by ebrondol** [comment]
@kpedro88 the changes respect to high eta are of course expected, the low pT region does not surprise me.

**Comment by kpedro88** [comment]
+1

**Comment by ebrondol** [comment]
@davidlange6 @slava77 can we get this PR in 910pre1?

**Comment by slava77** [comment]
On 3/22/17 6:17 AM, ebrondol wrote:
> @davidlange6 <https://github.com/davidlange6> @slava77
> <https://github.com/slava77> can we get this PR in 910pre1?

too late for pre1

**Comment by slava77** [comment]
(plots are in 900pre6+#17891 as a baseline and that with this PR added as "new")

D4 PU200
about 4% more PF CH essentially all are with eta > 3.5
all_sign883vssign880_ttbar14tev2023d4timingpu200localwf23034p0c_recopfcandidates_particleflow__reco_obj_eta43
this matches increase in general track population. About 94% of increase in generalTracks shows up as PF charged hadrons.

more tracks from initialStep
all_sign883vssign880_ttbar14tev2023d4timingpu200localwf23034p0c_recotracks_generaltracks__reco_obj_algo

MTV plots show somewhat reasonable increase in duplicates and fakes in high eta region
wf23034pu200_hp_fake_eta
wf23034pu200_hp_dup_eta
the duplicates increase in eta 3 to 3.5 could probably be mitigated (there is no gain/change in efficiency here, only above 3.5)

wf23034pu200_hp_eff_eta


Technical, with full sequence:
-  the increase in CPU time in reco-related modules is only 1.2%, consistent with https://github.com/cms-sw/cmssw/pull/17919#issuecomment-286488896
- memory increase (full reco+validation) is about 14 MB/core (with a rather large uncertainty; roughly consistent with the product size increase)

**Comment by slava77** [comment]
... somehow all changes in PF CH do not generate any significant increase in PF jets population
all_sign883vssign880_ttbar14tev2023d4timingpu200localwf23034p0c_recopfjets_ak4pfjets__reco_obj_eta

**Comment by kpedro88** [comment]
@slava77 maybe worthwhile to plot eta distribution weighted by pT? If the added CH candidates are all soft, it might not affect jet clustering/multiplicity strongly.

**Comment by slava77** [comment]
On 3/22/17 9:13 AM, Kevin Pedro wrote:
> @slava77 <https://github.com/slava77> maybe worthwhile to plot eta
> distribution weighted by pT? If the added CH candidates are all soft, it
> might not affect jet clustering/multiplicity strongly.

Could be.
In eta 3-4 the sum(Pt) from charged hadrons is up by under 10% (relative),
and it's still a factor of 2 less than the sumPt of HF hadrons.

{topic not particularly relevant to this PR}

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/17919	5bf37e3
- change is as described: added FPIX seeding layer combinations for phase-2 quadruplets and high-pt triplets; affects only 2023 workflows
- jenkins tests pass and comparisons with baseline show diffs only in 2023 workflows
- local test with PU200 and 10-mu D4 show some increase in efficiency and only moderate increase in fakes/dups; D11 10-mu wf shows significant increase in efficiency at high eta as expected 

wf24011_general_eff_eta

**Comment by slava77** [comment]
@davidlange6 
if 910pre1 needs another restart, please consider to include this.
Thank you.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
