### PR TITLE
add LogDebug to CandViewExtractor

### PR DESCRIPTION
**Pull request by jpata**
#### PR description:

Adds some LogDebug messages to check isolation calculations. Needed for debugging PR #31298.

#### PR validation:
compiles, runs and produces output for 136.7611.

### CODE REVIEW

**Comment by jpata** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
should we add this to the reco category?

**Comment by santocch** [comment]
+1

**Comment by silviodonato** [comment]
> should we add this to the reco category?

I agree, see https://github.com/cms-sw/cms-bot/pull/1381

**Comment by silviodonato** [comment]
+1

**Pull request merged**
