### PR TITLE
Loose mva WP for  non triggering electrons

### PR DESCRIPTION
**Pull request by fcouderc**
Add the HZZ loose WP identification for non triggering electrons.
This new ID has been developed for HZZ analysis and can now be used by a broader audience

### CODE REVIEW

**Comment by fcouderc** [comment]
@cmsbuild please test

**Comment by fcouderc** [comment]
@ikrav   76X PR to follow

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
This changes miniAOD output.
This is not allowed in the production release, until a new version/new campaign for miniAOD is defined (none is planned so far).

**Comment by slava77** [comment]
-1
due to changes in miniAOD output
Just addition of a config would be OK, but it should not change stored objects

**Pull request closed without merging**
