### PR TITLE
bsunanda:Run2-alca62 Modify TDC mask in HcalTPParameters from 32 bit to 64 bit uint

### PR DESCRIPTION
**Pull request by bsunanda**

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by mmusich** [comment]
+1 
provisionally approved: as discussed with @ggovi, no persistent condition data created with a version of the code older than the one proposed in this PR should be propagated to production workflows @walterjr @aboulline

**Comment by abdoulline** [comment]
Yes Marco, we didn't make any tags yet and will only do that with the 
new/modified DataFormat when available in IB.

**Comment by ggovi** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
