### PR TITLE
Geant4 user actions and CMS mctruth handling clean-up

### PR DESCRIPTION
**Pull request by civanch**
#### PR description:
This PR include modifications intended to reduce dependencies between objects used at SIM step in run time. Also couple of values saved into persistent MC truth objects are fixed. This PR should be useful for R&D and upgrade developments. No change in mainstream WFs are expected.

#### PR validation:
private

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
please test

there was DAS errors

**Comment by civanch** [comment]
+1

**Comment by perrotta** [comment]
+1

**Comment by iarspider** [comment]
@civanch the DBG_X IBs are failing to build ( [log](https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/el8_amd64_gcc11/CMSSW_13_1_DBG_X_2023-03-27-2300/SimG4CMS/Calo) ) after this PR was merged:

```
/data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc11/external/gcc/11.2.1-f9b9dfdd886f71cd63f5538223d8f161/bin/c++ -c -DGNU_GCC -D_GNU_SOURCE -DEIGEN_DONT_PARALLELIZE -DTBB_USE_GLIBCXX_VERSION=110201 -DTBB_SUPPRESS_DEPRECATED_MESSAGES -DTBB_PREVIEW_RESUMABLE_TASKS=1 -DTBB_PREVIEW_TASK_GROUP_EXTENSIONS=1 -DBOOST_SPIRIT_THREADSAFE -DPHOENIX_THREADSAFE -DBOOST_MATH_DISABLE_STD_FPCLASSIFY -DBOOST_UUID_RANDOM_PROVIDER_FORCE_POSIX -DGNU_GCC -DG4V9 -DGNU_GCC -DG4V9 -DDD4HEP_USE_GEANT4_UNITS=1 -DCMSSW_GIT_HASH='CMSSW_13_1_DBG_X_2023-03-27-2300' -DPROJECT_NAME='CMSSW' -DPROJECT_VERSION='CMSSW_13_1_DBG_X_2023-03-27-2300' -I/data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/9dde49def0b6f642763e19f977feeb75/opt/cmssw/el8_amd64_gcc11/cms/cmssw/CMSSW_13_1_DBG_X_2023-03-27-2300/src -I/data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc11/external/dd4hep/v01-23x-3637f0613a0d3afea6b636bfbb4ace09/include -I/data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc11/external/geant4/10.7.2-0e5231ef1da903b5220f5e39be20c6b6/include/Geant4 -I/data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc11/external/geant4/10.7.2-0e5231ef1da903b5220f5e39be20c6b6/include -I/data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc11/external/pcre/8.43-5dcc901acc02f624b22dd9840b2357e8/include -isystem/data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc11/external/boost/1.80.0-d560885614912b656cea04440e0ae44f/include -I/data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc11/external/bz2lib/1.0.6-2c1f18484cb66c30aba7929f2be5e7d4/include -isystem/data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc11/external/clhep/2.4.5.1-7e9b1c45d7f5b4361ac787761986b8a2/include -I/data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc11/external/cuda/11.5.2-66a9473808e7d5863d5bbec0824e2c4a/include -I/data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc11/external/expat/2.1.0-5f6457b4c04e97afec6079bd7d2db998/include -I/data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc11/external/gsl/2.6-fcf47bcbedd800ca8386c7e2920fa474/include -I/data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc11/external/hepmc/2.06.10-8d052e96205063f65fddfc4cbf40f506/include -I/data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc11/external/libuuid/2.34-0451b31e1b9a58c6aeefab41c18eea34/include -isystem/data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc11/lcg/root/6.26.11-9cfff04c7e738c67c5f012057fa9fe5a/include -isystem/data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc11/external/tbb/v2021.8.0-b05aa240920b2e90a45b2d4a5dc13536/include -I/data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc11/external/vecgeom/v1.1.17-10b2db97d6b1736305b7b352fc807529/include -I/data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc11/external/vecgeom/v1.1.17-10b2db97d6b1736305b7b352fc807529/include/VecGeom -I/data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc11/external/xerces-c/3.1.3-96261f23c7d6fbfb7d59be544bd882f3/include -I/data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc11/external/xz/5.2.5-83d0a00b575efd1701e07bedf7977343/include -I/data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc11/external/zlib/1.2.11-3dfb2715f3608466b74431b80eb9d788/include -I/data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc11/external/eigen/82dd3710dac619448f50331c1d6a35da673f764a-9ac4aed18ac60d0189693c592862694d/include/eigen3 -I/data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc11/external/fmt/8.0.1-43b841663c2a0d6622910a1ad66d228d/include -I/data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc11/external/md5/1.0.0-e68283f2de2e2e709a0db99db3b53205/include -I/data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc11/external/OpenBLAS/0.3.15-26c67b8b638762cfd2e2bcfc936e3ec7/include -I/data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc11/external/tinyxml2/6.2.0-c2bad61e58f94d6db8f640afbd739be2/include -O2 -pthread -pipe -Werror=main -Werror=pointer-arith -Werror=overlength-strings -Wno-vla -Werror=overflow -std=c++17 -ftree-vectorize -Werror=array-bounds -Werror=format-contains-nul -Werror=type-limits -fvisibility-inlines-hidden -fno-math-errno --param vect-max-version-for-alias-checks=50 -Xassembler --compress-debug-sections -fuse-ld=bfd -msse3 -felide-constructors -fmessage-length=0 -Wall -Wno-non-template-friend -Wno-long-long -Wreturn-type -Wextra -Wpessimizing-move -Wclass-memaccess -Wno-cast-function-type -Wno-unused-but-set-parameter -Wno-ignored-qualifiers -Wno-deprecated-copy -Wno-unused-parameter -Wunused -Wparentheses -Wno-deprecated -Werror=return-type -Werror=missing-braces -Werror=unused-value -Werror=unused-label -Werror=address -Werror=format -Werror=sign-compare -Werror=write-strings -Werror=delete-non-virtual-dtor -Werror=strict-aliasing -Werror=narrowing -Werror=unused-but-set-variable -Werror=reorder -Werror=conversion-null -Werror=return-local-addr -Wnon-virtual-dtor -Werror=switch -fdiagnostics-show-option -Wno-unused-local-typedefs -Wno-attributes -Wno-psabi -Wno-error=unused-variable -ftls-model=global-dynamic -pthread -DBOOST_DISABLE_ASSERTS -g -O3 -DEDM_ML_DEBUG -flto -fipa-icf -flto-odr-type-merging -fno-fat-lto-objects -Wodr -Wl,--exclude-libs,ALL  -fPIC   /data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/9dde49def0b6f642763e19f977feeb75/opt/cmssw/el8_amd64_gcc11/cms/cmssw/CMSSW_13_1_DBG_X_2023-03-27-2300/src/SimG4CMS/Calo/src/HFFibre.cc -o tmp/el8_amd64_gcc11/src/SimG4CMS/Calo/src/SimG4CMSCalo/bigobj/HFFibre.cc.o
/data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/9dde49def0b6f642763e19f977feeb75/opt/cmssw/el8_amd64_gcc11/cms/cmssw/CMSSW_13_1_DBG_X_2023-03-27-2300/src/SimG4CMS/Calo/src/CaloSD.cc: In member function 'virtual void CaloSD::update(const EndOfTrack*)':
  /data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/9dde49def0b6f642763e19f977feeb75/opt/cmssw/el8_amd64_gcc11/cms/cmssw/CMSSW_13_1_DBG_X_2023-03-27-2300/src/SimG4CMS/Calo/src/CaloSD.cc:710:64: error: 'it' was not declared in this scope; did you mean 'Hit'?
   710 |         edm::LogVerbatim("CaloSim") << "CaloSD: get track " << it << " from Container of size "
      |                                                                ^~
      |                                                                Hit
```

`it` was defined as index of last element in `trksForThisEvent` ( [here](https://github.com/cms-sw/cmssw/blob/e436297b73c7272dcc9ee8398d1857314be24a57/SimG4CMS/Calo/src/CaloSD.cc#L706) ). Could you please check?

**Comment by bsunanda** [comment]
I am trying to provide  a fix in a PR shortly. It is #41215
________________________________

**Comment by civanch** [comment]
@bsunanda , you fix another problem in #41215

**Pull request merged**
