### PR TITLE
Adding E, R and Z ranges to Close by gun generator

### PR DESCRIPTION
**Pull request by tonydp03**
#### PR description:

This pull request is made because we wanted to introduce a range in Energy, R and Z in the CloseByParticleGunProducer Workflow. Now in the configuration file the energy, R and Z ranges must be specified, while the ParticleGun will select a random Energy, R and Z in those ranges.

#### PR validation:

This pull request adds a couple of features (as described before) on top of the pull request #26065 made by @rovere.

@felicepantaleo 
@clelange

### CODE REVIEW

**Comment by rovere** [comment]
Please add a working snippet in Configuration/Generator/python, so that this can be linked easily with runTheMatrix/cmsDriver. This was suggested in #26065

**Comment by efeyazgan** [comment]
please test

**Comment by rovere** [comment]
Please take a look at one of the many examples in Configuration/Generator/python, e.g., [here](https://github.com/cms-sw/cmssw/blob/master/Configuration/Generator/python/SingleMuPt15Eta1p7_2p7_cfi.py), and modify your snippet accordingly. A snippet is not a full blown configuration.
Thanks!

**Comment by fabiocos** [comment]
@tonydp03 I concur with the comment of @rovere , the proposal for Configuration/Generator does not work as it is now. You should add a generator fragment, then in case you may add a full test configuration in the test area of the package (if deemed useful).

**Comment by tonydp03** [comment]
In the last commit I modified the snippet according to your suggestions @rovere . It should work now @fabiocos .

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
please abort

**Comment by fabiocos** [comment]
@tonydp03 sorry, quickly looking at the generator fragment, it now looks ok, apart for the name (please use _cfi.py as for all other fragments). Anyway it looks you used cms-merge-topic to prepare this PR, which in general should be avoided. I see here 7 new files, but in practice 6 of them are from #26065, am I correct? I suggest that you close this PR and open a new one, where you just add the _cfi.py configuration fragment on top of the latest 10_6_X branch

**Comment by tonydp03** [comment]
@fabiocos Indeed, but I modified the CloseByParticleGunProducer files in #26065 to handle a variable range in energy, R and z (that was the goal of the pull request), that's why I used cms-merge-topic.
In addition, since it had been asked in #26065 as well, I added the snippet according to the new changes.

**Comment by fabiocos** [comment]
@tonydp03 fine, but please propose a clean PR with the snippet and the modification to the gun, without other cms-merge-topic

**Comment by tonydp03** [comment]
Addressed in #26277.

**Pull request closed without merging**
