### PR TITLE
Fix MTV validation of initialStepPreSplitting tracks

### PR DESCRIPTION
**Pull request by makortel**
There is a subtle bug in the current tracking validation setup in "built tracks" MultiTrackValidator variant for initialStepPreSplitting tracks. Because of the cluster splitting done in the initialStepPreSplitting iteration, it uses different pixel clusters (`siPixelClustersPreSplitting`) than the rest of the iterations (`siPixelClusters`). However, for the validation only a single the cluster->TrackingParticle mapping (`tpClusters` product) is created with the `siPixelClusters` as an input. When this mapping is queried in QuickTrackAssociatorByHits, there is no check for the `ProductID` of the (pixel) `OmniClusterRef`. In other words, for an `OmniClusterRef` from `siPixelClustersPreSplitting`, take the index of the `Ref` and check if an `OmniClusterRef` from `siPixelClusters` with the same index is matched to a TrackingParticle.

This PR fixes the problem in the following way
* Store the key `ProductID`s in `ClusterTPAssociation`, and check it when querying for matching TrackingParticles
   * This required adding dictionary for `edm::VecArray<ProductID, 2>`
* Add a second instance of the cluster->TP mapping (`tpClustersPreSplitting`) for the PreSplitting clusters, and add an additional MTV instance only for the initialStepPreSplitting tracks.
   * This means that the `initialStepPreSplitting` gets removed from the summary plots for seeds and built tracks
   * I also moved all the producers to Tasks to make sure that they're always run unscheduled

 Tested in CMSSW_10_4_0_pre2, expecting changes in MTV seeding and built tracks summary and initialStepPreSplitting plots.

@VinInn @mtosi @JanFSchulte @hajohajo

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test workflow 135.13,1325.1,1325.3,2017.13,10024.1,10024.3,10824.1,20034.1,10024.5

**Comment by andrius-k** [comment]
+1

**Comment by Dr15Jones** [comment]
+1
For DataFormats/Provenance

**Comment by fabiocos** [comment]
@makortel the only change observed is in the global efficiency summary, and I would say it is consistent with this PR change, please correct me in case

**Comment by fabiocos** [comment]
+1

**Comment by makortel** [comment]
@fabiocos Yes, that is consistent.

**Pull request merged**
