### PR TITLE
New GTs Hcal digis for fastsim

### PR DESCRIPTION
**Pull request by davidlange6**
This is the final set of GT for next pre-release:

Updated new conditions for Run2 MC DIGI-RECO campaign.
Added Egamma PF Cluster corrections in all scenarios (so removed the ESPrefer in RecoParticleFlow/PFClusterProducer/python/particleFlowClusterECAL_cfi.py);
Updated hadron PF calibrations for Run2 MC, and new IOV appended to the HLT and re-reco GT;
Removed unused records for old 3x3 APE in all the GT;
Removed unsupported SIM geometry scenarios;
Use the correct key for HI Run2 MC (as in #7704).

In addition - current fastim configs miss the run2 setup for digitizers in fastsim. This PR takes care of that (will be more robust once we get eras working)

### CODE REVIEW

**Comment by davidlange6** [comment]
@cmsbuild, please test

**Comment by slava77** [comment]
Hi David,

the fix didn't need to include the GT merged with it.
The issue with fastsim configuration is decoupled from it.

**Comment by davidlange6** [comment]
yes, that is correct

**Comment by slava77** [comment]
uhm, now that Salvatore "-1"d the #7707, David, could you please update the subject of the PR and maybe copy-paste the description from #7707 with a note that this includes a fix to fastsim.
Thanks.

**Comment by davidlange6** [comment]
Fixed

**Comment by diguida** [comment]
@davidlange6 @slava77 The fastsim issue is decoupled from GT, but the latter showed the issue. So I think it is ok make a single PR, and I -1 the previous one.

**Comment by slava77** [comment]
uhm, the PR is made on top of yet another "recompile-the-universe" minor fix from the head.
jenkins will be chugging through this for a while.

**Comment by davidlange6** [comment]
@slava77 - not sure which PR you mean? (how can I see what you are talking about)

**Comment by slava77** [comment]
nevermind, jenkins got through this quickly enough
I was talking about #7583
(it gets dragged in by jenkins tests using "CMSSW_7_4_X_2015-02-13-0200 + 7726")

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/7726	e532afb
tested in CMSSW_7_4_X_2015-02-12-0200 /test area sign518a, with an equivalent fix cherry-picked/
This +1 is still with an expectation that Run1 GTs are going to be updated in the next PR to include the PF hadron  calibrations

Here are a few plots from run2 MC particle guns:

1 TeV electrons
there's quite an increase in higher MET population
all_sign517vssign518_singleelectron13pt1000wf1316p0c_log10recopfmets_pfmet__reco_obj_pt

1TeV muons
all_sign517vssign518_singlemu13pt1000wf1322p0c_recodedxdataedmvaluemap_dedxtruncated40__reco_obj_values__dedx

flat-dijet-spectrum 
the lower energy hit population increases (smaller noise?)
all_sign517vssign518_qcd13tevflatpt15s3000wf38p0c_log10hfrechitssorted_hfreco__reco_obj_obj_energy

clusters are about the same
all_sign517vssign518_qcd13tevflatpt15s3000wf38p0c_log10recosuperclusters_hfemclusters__reco_obj_energy

**Comment by civanch** [comment]
+1

**Comment by diguida** [comment]
@davidlange6 I have a new branch in my repo containing all the changes that need to be merged (this PR + #7697) plus the new Global Tags `diguida:autoCond_740pre7_full_changes`. I can do a new PR or you can cherry pick and add here.

**Comment by diguida** [comment]
@davidlange6 I have made #7732 on top of my branch

**Comment by diguida** [comment]
+1

**Comment by lveldere** [comment]
@davidlange6 

This one did not get the fastsim flag, so I missed it.

Could you explain briefly what used to be wrong for FastSim and how it was fixed?

Thanks

Lukas

@ssekmen

**Comment by davidlange6** [comment]
Hi Lukas

Two problems

a) the run2 customize functions assumed that the digitizers were on a path call digitisation_path, which they are not in fastsim

b) You have a customize function that imports all of the mixing module configurations. This is not very nice as any changes to those configurations are then overridden. I hacked around this by making sure your customize function is first. This problem will be better soon.

**Comment by lveldere** [comment]
Thanks a lot


> a) the run2 customize functions assumed that the digitizers were on a path
> call digitisation_path, which they are not in fastsim
>
>
At some point FastSim cfg will have the same structure as FullSim,
that will make it a bit easier as well.


> b) You have a customize function that imports all of the mixing module
> configurations. This is not very nice as any changes to those
> configurations are then overridden. I hacked around this by making sure
> your customize function is first. This problem will be better soon.
>
>
I realise it is not very nice, but could not think of anything better yet...
When syncing FastSim cfg further with FullSim I will keep this in mind.
Suggestions are welcome of course :-)

**Pull request merged**
