### PR TITLE
bsunanda:Phase2-gem15 ME0 with eta partitions

### PR DESCRIPTION
**Pull request by bsunanda**

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by ianna** [comment]
+1

**Comment by davidlange6** [comment]
@bsunanda - where are we with cleaning up all the old v* versions of this geometry?

**Comment by bsunanda** [comment]
This will be coming soon. Now we understand which files are to be kept. Also all the cfi files need modifications.
________________________________

**Comment by davidlange6** [comment]
could we put a date on “soon”? Its the usual answer for gem geometry cleanup…

**Comment by bsunanda** [comment]
2 weeks - which means by June 1
________________________________

**Comment by davidlange6** [comment]
+1

**Pull request merged**
