### PR TITLE
[mkFit] Tools supporting better layer-related computations -- technical changes to support further development

### PR DESCRIPTION
**Pull request by osschar**
#### PR description:

There are no significant physics changes.

Several changes only affect mkFit in standalone mode.

Main goals:

- Make it easier to express vectorized code.

- Be able to do simple propagations, parameters only, no errors.

- Explore more precise hit preselection in each layer (see MkFinder.selectHitIndicesV2()).

- Make it easier to export low-level algorithm / tracking state for further analysis directly in ROOT format.

- Allow further development of Phase2 mkFit tracking, together with the new propagate-to-plane functionality (in another PR).

#### Detailed changes

Add half_length member to ModuleInfo, fill it in MkFitGeometryESProducer.cc

Extend HitInfo with half-strip-length, add qbar (the other of r/z variables), Store fast-access arrays as std::vector<HitInfo>.

Move propToR/Z() can/maxReachRadius() from Track to TrackBase.

Implement LayerOfHits::reset() to make sure containers are empty before re-filling. Call this from both methods (beginHitRegistration() and suckInHits()).

Miscellaneous changes to better support dump-hit-window case.

* RecoTracker/MkFitCore/interface/Track.h Add function mcHitIDofFirstHit() to simplify dump-hit-window code.

* RecoTracker/MkFitCore/src/MkBuilder.cc Add missing MkFinder setup in dump-hit-window case.

* RecoTracker/MkFitCore/standalone/Makefile.config Clarify usage of Ofast (by Steve).

* RecoTracker/MkFitCMS/standalone/Makefile Use GNU make &: syntax (grouped targets) for dictionary targets.

* RecoTracker/MkFitCore/src/MiniPropagators.h/cc: Implementations of propagators of track parameters only (no errors/covariances), with various levels of approximation and also supporting vectorization.

Use VDT for fast transcendentals in MiniPropagators.

Add scalar and element-wise arithemtic operators and transcendentals to Matriplex. This makes writing vectorized loops using Matriplex variables much clearer.

Prepare infrastructure for deep-dump comparisons in selectHitIndicesV2 (and elsewhere).

* `MkFitCore/interface/Config.h`
 Fix typo.

* `MkFitCore/interface/MkBuilder.h
 MkFitCore/interface/Track.h
 MkFitCore/interface/TrackStructures.h
 MkFitCore/src/TrackStructures.cc
 MkFitCore/src/MkBuilder.cc
 MkFitCore/standalone/Event.cc
 MkFitCore/standalone/Event.h`
Pass seed-index in the current seed-vector along. In Event, provide a means of determining sim-track from hits of each seed track.

* `MkFitCore/src/MkBuilder.cc`
Add handling of WSR_Failed.

* `MkFitCore/src/Matrix.h`
Add short-int Matriplex typedefs

* `MkFitCore/src/MiniPropagators.cc
 MkFitCore/src/MiniPropagators.h`
 Fail-flag consistency, rename State dphi to dalpha.

* `MkFitCore/src/MkBase.h`
Add radius() function.

* `MkFitCore/src/MkFinder.cc
 MkFitCore/src/MkFinder.h` 
Modularization of new/old hit-selection. Reimplemented bin-search for edge positions and determined global scaling of bin-search windows to reproduce current behavior.

* `MkFitCore/standalone/Makefile
MkFitCore/standalone/Makefile.config`
 Add rules for building RntDumper stuff.

* `MkFitCore/standalone/RntDumper/`
New sub-directory: Implementation of classes and structures for dumping ROOT TTrees or RNTuples.

* `MkFitCMS/standalone/Makefile`
Add linking agains libMicRntDump.so

* `MkFitCMS/standalone/MkStandaloneSeqs.cc` 
Make it easier to find out why standalone tracks are not matched to sim tracks.

* `MkFitCMS/standalone/Shell.cc
MkFitCMS/standalone/buildtestMPlex.cc` 
Setup Event current-seed-vector pointers as needed during event processing.

* `MkFitCMS/standalone/mkFit.cc`
Finalize all RntDumpers on exit.

Standalone consolidation plus cleanup of parameters, remove unused ones.

* `MkFitCMS/standalone/buildtestMPlex.cc` 
When validation is on make sure seeds are restored after BH, STD, CE runs.

* `MkFitCMS/standalone/mkFit.cc` 
Rename run-all to run default -- make it run std, and ce.

* `MkFitCore/src/MkBuilder.cc` 
Missing MkFinder setup in backwardFitBH().

* `MkFitCore/standalone/Geoms/CylCowWLids.cc` 
Array of eta extents too short.

* `MkFitCore/standalone/Makefile.config` 
Consolidate CMSSW and other occurences of Ofast, msse2, std=c++17/1z. Cleanup unused -D defines / settings.

* `MkFitCore/standalone/ConfigStandalone.h`
Remove unused simulation multiple scattering parameters.

#### PR validation:

No significant physics changes: [MTV plots](http://uaf-10.t2.ucsd.edu/~legianni/plots_compare_layerProcv2_PRVersion/)

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by osschar** [comment]
There is a minimal conflic between this pr and PR # #43146.
It occurs around `MkFitCore/src/MkFinder.cc:170` -- both changes should be accepted.

**Comment by mandrenguyen** [comment]
I was having a look at the comparisons.  They mostly look fine but I'm scratching my head about this pair:
[141.044_RunJetMET2023D/all_mini_reRECO_step3_inMINIAOD/c_HBHERecHitsSorted_reducedEgamma_reducedHBHEHits_reRECO_obj_obj_eraw.](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_13_3_X_2023-10-29-0000+981bbc/59480/validateJR/141.044_RunJetMET2023D/all_mini_reRECO_step3_inMINIAOD/c_HBHERecHitsSorted_reducedEgamma_reducedHBHEHits_reRECO_obj_obj_eraw.png)

[141.044_RunJetMET2023D/all_mini_reRECO_step3_inMINIAOD/c_HBHERecHitsSorted_reducedEgamma_reducedHBHEHits_reRECO_obj_obj_energy](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_13_3_X_2023-10-29-0000+981bbc/59480/validateJR/141.044_RunJetMET2023D/all_mini_reRECO_step3_inMINIAOD/c_HBHERecHitsSorted_reducedEgamma_reducedHBHEHits_reRECO_obj_obj_energy.png)

Am i just reading too much into some fluctuations?  
While we're at it, since most of these changes seem purely technical, can you please point out the ones that lead to all these minor (and hopefully negligible) differences?   Thanks!

**Comment by osschar** [comment]
All the differences should come from this section:
https://github.com/cms-sw/cmssw/pull/43145/files#diff-98dcf509af7754b02d4fe0a9902ab6d8514b8401880de93d6fd957c09fa0a87cR454-R457

This blocks adding of hits for further processing (for a given candidate, at the current layer) when the desired radius has not been reached. This can happen close to helix apogee and for very low-pt tracks (I think it was < 0.2 GeV but more likely 0.1GeV). The propagation can also fail rather spectacularly resulting in nans and nonsencical values for hit-search windows (which I noticed in the new version of hit pre-processing function).

As there were no significant changes in the low-level MTV I decided to keep it in.

**Comment by mandrenguyen** [comment]
Also, would it make sense to factorize the purely technical changes from the one you refer to?  That might help to be sure that there are no unintended consequences from the former.

**Comment by osschar** [comment]
How sensible this is -- I don't know :) Is the plot from particle-flow? The change could lead to some low-pt tracks missing the last hit (likely a bogus one) and then failing the track-quality hits because of this. But if this is really number of hcal hits, there should be zero effect from a tracking change :)

Other than that, sure, I can take this out ... should I go ahead?

**Comment by osschar** [comment]
I rolled back to less strict propagation failure detection. It was a bit more complicated as this check now done sooner ... and I did not want to reintroduce it back in the old place where it would interfere with the new code -- so I just loosened the criteria of failure to be in line with the old code.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by mandrenguyen** [comment]
The last commit doesn't seem to have changed this hbhe change:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_13_3_X_2023-10-30-1100+981bbc/59500/validateJR/141.044_RunJetMET2023D/all_mini_reRECO_step3_inMINIAOD/c_HBHERecHitsSorted_reducedEgamma_reducedHBHEHits_reRECO_obj_obj_eraw.png

@slava77 @kskovpen Any opinion here?

**Comment by slava77** [comment]
> The last commit doesn't seem to have changed this hbhe change: https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_13_3_X_2023-10-30-1100+981bbc/59500/validateJR/141.044_RunJetMET2023D/all_mini_reRECO_step3_inMINIAOD/c_HBHERecHitsSorted_reducedEgamma_reducedHBHEHits_reRECO_obj_obj_eraw.png
> 
> @slava77 @kskovpen Any opinion here?

it looks like there are around 2e-4 [tracks with a change](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_13_3_X_2023-10-30-1100+981bbc/59500/validateJR/141.044_RunJetMET2023D/all_reRECO_step3/c_recoTracks_generalTracks__reRECO_obj_eta.png) in this workflow.
The [Gsf tracks](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_13_3_X_2023-10-30-1100+981bbc/59500/validateJR/141.044_RunJetMET2023D/all_reRECO_step3/c_log10recoGsfTracks_electronGsfTracks__reRECO_obj_pt.png) differ at around just below 1/100.
Apparently one gsfElectron drops out (out of 113) and one more changes [classification](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_13_3_X_2023-10-30-1100+981bbc/59500/validateJR/141.044_RunJetMET2023D/all_reRECO_step3/c_recoGsfElectrons_gedGsfElectrons__reRECO_obj_classification.png).
The changes in reducedEgamma in your message come likely from the disappeared gsfElectron (more likely than from the reclassified one).

Tracks start similarly in [136.874_RunEGamma2018C wf](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_13_3_X_2023-10-30-1100+981bbc/59500/validateJR/136.874_RunEGamma2018C/all_reRECO_step3/) and somewhat similar in gsf tracks, but it doesn't propagate to the electrons.

So, it all looks like a butterfly effect from small changes in tracks.
I was hoping that @osschar expectations for the change in the code actually reduce the impact, but reco diffs changed only from 4895 to 4813.

**Comment by slava77** [comment]
@smuzaffar @VinInn 
is the dependence on vdt explicit, or do we actually use preload variant where all std math gets replaced?
[vdt.specs](https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_13_3_X/master/vdt.spec#L17)
looks like this is a preload variant.

Is there a way to use just explicit calls?
I don't think we want to just jump to using vdt sincos in the existing mkFit methods.

**Comment by slava77** [comment]
> @smuzaffar @VinInn is the dependence on vdt explicit, or do we actually use preload variant where all std math gets replaced? [vdt.specs](https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_13_3_X/master/vdt.spec#L17) looks like this is a preload variant.
> 
> Is there a way to use just explicit calls? I don't think we want to just jump to using vdt sincos in the existing mkFit methods.

apparently `vdt_headers` 

I have a related question, how is the full vdt controlled with preload, is it somehow fenced with a specific cmssw library, or does everything get the vdt math symbols once `<use name="vdt"/>` shows up anywhere? we have `[L1Trigger/DTTriggerPhase2/BuildFile.xml](https://github.com/cms-sw/cmssw/blob/f0bc2a83e73a4b25225c84d1b5937b3d57602924/L1Trigger/DTTriggerPhase2/BuildFile.xml#L12)` using vdt

**Comment by smuzaffar** [comment]
@slava77 , `vdt` dependency is explicit. You can use `vdt::fast_*` to explicitly use these.
I do not think the default `sin/cos/tan` functions provided by vdt are ever called (even either explicitly linking libvdt or doing a preload).

**Comment by slava77** [comment]
> @slava77 , `vdt` dependency is explicit. You can use `vdt::fast_*` to explicitly use these. I do not think the default `sin/cos/tan` functions provided by vdt are ever called (even either explicitly linking libvdt or doing a preload).


The release notes in vdt are a bit more suggestive that libm symbols are replaced
> -DPRELOAD=1. If set, symbols identical to the Libm ones but containing 
> a vdt call will be generated in the lib. If preloaded, vdt calls will be 
> performed instead of libm ones.

**Comment by slava77** [comment]
@cmsbuild please test

let's see if vdt_headers gives fewer differences

**Comment by smuzaffar** [comment]
OK @slava77, I tried building vdt with some debug print outs and yes 
- `LD_PRELOAD=path/libvdt.so test-my-vdt` calls the vdt math functions
-  Linking `vdt` library to cmssw shared lib/plugin is not calling vdt math functions
- Linking `vdt` library to the executable calls the vdt math

So one either needs to explicitly link `vdt` to the main executable (e.g `cmsRun`) or use LD_PRELOAD.

**Comment by makortel** [comment]
@smuzaffar This is very tangential to this PR, but should we drop the `vdt` dependence from [L1Trigger/DTTriggerPhase2/BuildFile.xml](https://github.com/cms-sw/cmssw/blob/f0bc2a83e73a4b25225c84d1b5937b3d57602924/L1Trigger/DTTriggerPhase2/BuildFile.xml#L12)? From your tests it seems the dependence there is mostly confusing.

**Comment by slava77** [comment]
> Reco comparison results: 4868 differences found in the comparisons

this looks essentially the same as in the previous iteration. So, the `vdt` vs `vdt_headers` had no impact.

So, having taken off a remote possibility of long range library use effects, I think what remains is just the small changes in tracks propagating to less numerically stable gsfTracks and further on.

**Comment by mandrenguyen** [comment]
+1
Small changes compatible with expectation based on discussion above

**Comment by rappoccio** [comment]
+1

**Pull request merged**
