### PR TITLE
Run3-gex109B Avoid compilation warnings in some Validation code

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Avoid compilation warnings in some Validation codes (EcalRecHits, EcalTriggerPrimitives)

#### PR validation:

Use runTheMatrix test workflows

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by cecilecaillol** [comment]
+l1

**Comment by qliphy** [comment]
please test

**Comment by perrotta** [comment]
+1

**Pull request merged**
