### PR TITLE
fix WF 1311

### PR DESCRIPTION
**Pull request by deguio**
no PAT sequence is run in RECOMINUP15
removing the miniAOD harvesting to keep consistency and avoid crashes.

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1

**Comment by fabozzi** [comment]
+1

**Comment by davidlange6** [comment]
not clear to me why there is not a mini-aod for this workflow. but ok..

**Comment by davidlange6** [comment]
+1

**Pull request merged**
