### PR TITLE
[DB][BuildFile] Use ifarch instead of ifarchitecture to match system arch only.

### PR DESCRIPTION
**Pull request by smuzaffar**
BuildFile cleanup: Use ifarch to match the exact arch

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
+db
 * unit test failure is known and it's not connected to this PR
 * otherwise tests pass

**Comment by perrotta** [comment]
+1

**Comment by perrotta** [comment]
merge

**Pull request merged**
