### PR TITLE
add 10 electrons gun gen fragment

### PR DESCRIPTION
**Pull request by mtosi**
backport PR https://github.com/cms-sw/cmssw/pull/17394

### CODE REVIEW

**Comment by govoni** [comment]
+1

**Comment by mtosi** [comment]
ciao
are there issue w/ this PR ?
thanks

**Comment by boudoul** [comment]
ciao @mtosi , naively, reading your comments in the 90X PR , it seems that this is targeting 2017 development studies , therefore there is no need to backport in 80X, 81X (which won't be used for that purpose) 
My two cents

**Comment by mtosi** [comment]
thanks
I tend to agree, I let you decide if integrated or close this PR

**Comment by perrozzi** [comment]
-1

**Pull request closed without merging**
