### PR TITLE
Protect against missing track info in MiniAOD

### PR DESCRIPTION
**Pull request by ahinzmann**
When pileup jet ID is reran on top of an existing MiniAOD, it crashes due to missing tracking information.
The fix sets the corresponding variables to default values if no information is available.
The affected variables are not used in the default MVA training of pileup jet ID, thus have no effect on the observable used in analyses.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

@ahinzmann there should probably be a workflow to capture issues like this.

**Comment by perrotta** [comment]
please test

**Comment by ahinzmann** [comment]
@slava77 does a MiniAOD from MiniAOD workflow exist? It could cover this case and is actually quite a common workflow.

**Comment by slava77** [comment]
On 10/10/17 2:17 AM, ahinzmann wrote:
> @slava77 <https://github.com/slava77> does a MiniAOD from MiniAOD
> workflow exist? It could cover this case and is actually quite a common
> workflow.
> 

It's somewhat hidden in the cmsDriver:
-s EI:MiniAODfromMiniAOD
should trigger loading of
PhysicsTools/PatAlgos/python/slimming/MiniAODfromMiniAOD_cff.py
Check if the work done there is good for tests here as well
If so, perhaps it could be added to the unit tests in
PhysicsTools/PatAlgos/test/runtests.sh

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by perrotta** [comment]
+1
- Same as #27041 in the master, except that in 93X it was not possible to take profit of the fixed PackedCandidate::dz() method, not yet available in the release
- Protection added for cases in which the tracks are not available
- It only matters for pileup jet ID rerun on top of an existing MiniAOD: no changes expected for standard workflows
- No effect on jenkins outputs, as expected

**Comment by davidlange6** [comment]
merge

**Comment by ahinzmann** [comment]
I have added an example of rerunning pileup jet ID on top of MiniAOD to the PAT unit tests, such that this kind of issue will be caught by the tests in the future: #21018

**Pull request merged**
