### PR TITLE
Update quality test limits

### PR DESCRIPTION
**Pull request by lunik1**
Backport of PR #20729 to CMSSW_9_2_X

### CODE REVIEW

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
hi- @lunik1 @dmitrijus - why is this so different from the 94x version?

**Comment by lunik1** [comment]
Hi, the initial commit is the same. The second commit is to adjust the limits again to fix some errors seen in the playback.

**Comment by fioriNTU** [comment]
@lunik1 of course any change you did in 9_2_X should be ported in 9_4_X too.

**Comment by davidlange6** [comment]
so its not a back port then... (and it needs to be)

**Comment by lunik1** [comment]
I should make a new PR targeting 9_4_X containing c564659b8919ebdfa5657032ddbda6ee6bcad11b ?

**Comment by fioriNTU** [comment]
@lunik1, just modify the current PR to add your latest changes. If you think it takes too long, you can even close this PR and open a new one consistent with the 9_2_X

**Comment by lunik1** [comment]
I don't think the 9_2_X PR can be modified, as it has been merged.

**Comment by fioriNTU** [comment]
@lunik1 , ah ok, I dodn't relize we were commenting on the 9_2_X version.
@davidlange6 should we place a new PR with these modifications? In the case I would wait a bit, since we probably still need to make some tuning using more statistics of real runs.

**Comment by davidlange6** [comment]
yes - changes all need to go the master branch before propagating elsewhere.

**Comment by davidlange6** [comment]
-1
not a backport

**Comment by fioriNTU** [comment]
@lunik1, please close this PR, at the end is running online, we do not need to pollute CMSSW releases

**Pull request closed without merging**
