### PR TITLE
[10X][DQM][L1T] Reduce memory consumption of L1T DQM plots

### PR DESCRIPTION
**Pull request by kreczko**
Fixing issues
 - https://its.cern.ch/jira/browse/CMSLITDPG-443
 - https://its.cern.ch/jira/browse/CMSLITDPG-444
 - https://its.cern.ch/jira/browse/CMSLITDPG-445

Reducing the memory consumption by reducing the number of bins for 2D histograms (&phi; vs &phi; and E<sub>T</sub> vs E<sub>T</sub>), e .g.
image

### CODE REVIEW

**Comment by thomreis** [comment]
please test

**Comment by thomreis** [comment]
+1

**Comment by dmitrijus** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
