### PR TITLE
Reduce CPU time in MuonAssociatorByHitsHelper

### PR DESCRIPTION
**Pull request by kpedro88**
There was some work done to improve efficiency in `MuonAssociatorByHitsHelper` previously in #16669, but it did not fully solve the problem. After a number of attempts, I determined that calls to `std::vector<>::begin()/end()` can actually become rather costly when repeated ad infinitum in 200PU workflows. Using range-based loops turned out to be the easiest solution. (Unfortunately, the outermost loop in `getShared()` can't be optimized this way because `boost::ptr_vector` doesn't appear to support it.)

igprof results for step3 using 5 events w/ 200PU in WF 21434.0 (ttbar 2023D4PU):

baseline:
```
[32]       11.7     889.68     301.64 / 588.03     MuonAssociatorByHitsHelper::getShared(boost::ptr_vector<std::pair<unsigned int, std::vector<std::pair<unsigned int, EncodedEventId>, std::allocator<std::pair<unsigned int, EncodedEventId> > > >, boost::heap_clone_allocator, std::allocator<void*> >&, __gnu_cxx::__normal_iterator<TrackingParticle const*, std::vector<TrackingParticle, std::allocator<TrackingParticle> > >) const
            6.4  .........     487.96 / 487.96       TrackingParticle::g4Track_begin() const [43]
            1.1  .........      80.48 / 80.52        TrackingParticle::g4Track_end() const [188]
            0.3  .........      19.59 / 155.88       _init [127]
```

PR:
```
[39]        6.8     495.26     495.26 / 0.00       MuonAssociatorByHitsHelper::getShared(boost::ptr_vector<std::pair<unsigned int, std::vector<std::pair<unsigned int, EncodedEventId>, std::allocator<std::pair<unsigned int, EncodedEventId> > > >, boost::heap_clone_allocator, std::allocator<void*> >&, __gnu_cxx::__normal_iterator<TrackingParticle const*, std::vector<TrackingParticle, std::allocator<TrackingParticle> > >) const
```

This module only runs in Validation, so this won't have an impact on CPU time, but will help with relvals. Further improvements should come from more dedicated reorganization of the code by muon experts.

### CODE REVIEW

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by civanch** [comment]
+1

**Comment by slava77** [comment]
@smuzaffar 
regarding 
```
The workflows 1003.0, 1001.0, 1000.0, 140.53, 136.731, 4.22 have different files in step1_dasquery.log than the ones found in the baseline. You may want to check and retrigger the tests if necessary. You can check it in the "files" directory in the results of the comparisons
```
this time apparently the first file was different.
DAS hasn't gotten any more reliable.
I thought that by now we have switched to using cache in the jenkins jobs.
What is the status of using it?

**Comment by smuzaffar** [comment]
@slava77 , this is fixed for PR tests based on CMSSW_9_0_X_2016-12-08-2300 and above. There was an issue in cache usage (for 90X IB only) which is now fixed. You can try re-running the test

**Comment by davidlange6** [comment]
+1

**Pull request merged**
