### PR TITLE
Fix deprecation warnings in DQMOffline/CalibMuon

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

Converted modules to edm::one::EDAnalyzer

#### PR validation:

Package compiles without issuing a CMS deprecation warning.

### CODE REVIEW

**Comment by emanueleusai** [comment]
please test

**Comment by Dr15Jones** [comment]
please test

**Comment by emanueleusai** [comment]
please test

**Comment by emanueleusai** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
