### PR TITLE
update HGCal unit test for new geometry

### PR DESCRIPTION
**Pull request by kpedro88**
#### PR description:

The D62 geometry was removed in #31673. The unit test is updated to use the corresponding new D71 geometry (both have C14).

#### PR validation:

Ran unit test.

### CODE REVIEW

**Comment by kpedro88** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by silviodonato** [comment]
merge
this PR fixes the unit test
@cms-sw/geometry-l2 please let us know if you have any comments

**Comment by cvuosalo** [comment]
+1

**Pull request merged**
