### PR TITLE
GEM Reco Geometry from DB in 2017 Era

### PR DESCRIPTION
**Pull request by ianna**
* GEM reco geometry builder is added to RecoDB producers based on era
* Added run2_GEM_2017 modifier

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
@slava77 - FYI. This is another way of configuring GEM geometry. Note, the producer will fail if GEM reco geometry record is not available in a GT queue. Both upgrade2017 and upgrade2018 GT queues will have the record in #17319

**Comment by slava77** [comment]
@ianna 
thanks

@calabria please take a note

**Comment by ianna** [comment]
@davidlange6 - relvals fail as expected due to missing GEMRECO geometry:
```
----- Begin Fatal Exception 30-Jan-2017 20:26:38 CET-----------------------
An exception of category 'NoRecord' occurred while
   [0] Processing run: 1
   [1] Running path 'HLT_AK8PFJet360_TrimMass30_v7'
   [2] Calling beginRun for module TSGFromL2Muon/'hltL3TrajSeedOIState'
   [3] Using EventSetup component GlobalTrackingGeometryESProducer/'' to make data GlobalTrackingGeometry/'' in record GlobalTrackingGeometryRecord
   [4] Using EventSetup component GEMGeometryESModule/'' to make data GEMGeometry/'' in record MuonGeometryRecord
   [5] While getting dependent Record from Record MuonGeometryRecord
Exception Message:
No "GEMRecoGeometryRcd" record found in the EventSetup for synchronization value
Run: 1 LuminosityBlock: 0 Event: 0 Time: 1
 Please add an ESSource or ESProducer that delivers such a record.
----- End Fatal Exception -------------------------------------------------

```

**Comment by ianna** [comment]
please test with #17319

**Comment by davidlange6** [comment]
tests ok with #17319 and #17332

**Pull request merged**
