### PR TITLE
update working point for new DNN

### PR DESCRIPTION
**Pull request by minxiyang**
Update working point of the MkFit DNN for the newest update of the MkFit reconstruction: cms-sw/cmssw#36246.

The performance of the updated DNN: https://jschulte.web.cern.ch/jschulte/DNN_Nov29th/run3finalv4_TTbar/

The test is ran on the dataset /RelValTTbar_14TeV/CMSSW_12_1_0_pre5-PU_121X_mcRun3_2021_realistic_v15-v2/GEN-SIM-DIGI-RAW with the CMSSW _12_2_X. The performance of the MkFit DNN on the MkFit tracks is compared to the CKF DNN on the CKF dataset.

### CODE REVIEW

**Comment by slava77** [comment]
test parameters:
- pull_request = cms-data/RecoTracker-FinalTrackSelectors#11

**Comment by slava77** [comment]
enable profiling

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by mmasciov** [comment]
@minxiyang, @mmusich, @slava77: please consider suggestion in https://github.com/cms-data/RecoTracker-FinalTrackSelectors/pull/11#issuecomment-982085728

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+reconstruction

for https://github.com/cms-sw/cmssw/pull/36285	83c6517 
- code changes are in line with the PR description
- jenkins tests pass and comparisons with the baseline show differences in tracks entering the generalTracks collection and downstream quantities.
    - technical performance as seen in the profiler reports are roughly unchanged (the memory use and the time per event are similar/same)
    - track validation plots seem rather similar in these tests, but there are just 10 events in each case
    - somewhat higher stat wf with data EGamma2018C 136.874 shows roughly expected behavior (to have slightly lower fakes):
        - the number of generalTracks is down by about 1.7% (expected to be mainly from fakes reduction)
        - the number of charged hadrons is down by about 0.6%

- CKF to mkFit comparisons are provided in the PR description for the standard relval ttbar with PU (IIUC, prior to the update in 83c6517)
- incremental comparisons corresponding to the latest/83c6517 version of the PR are available including #36246 in https://indico.cern.ch/event/1098365/#6-mkfit-status-report  e.g. in 
image

**Comment by slava77** [comment]
@perrotta @qliphy 
this together with  cms-data/RecoTracker-FinalTrackSelectors#11 are expected in 12_2_0_pre3

**Comment by perrotta** [comment]
+1
- Updated working points with slightly improved physics performance

**Pull request merged**
