### PR TITLE
era to store ZDC digis for pp reco [13_2_X]

### PR DESCRIPTION
**Pull request by mandrenguyen**
backport of #42942

### CODE REVIEW

**Comment by mandrenguyen** [comment]
please test

**Comment by mandrenguyen** [comment]
urgent
likely to be needed for data taking pending decision at daily ops meeting tomorrow

**Comment by mandrenguyen** [comment]
+1

**Comment by simonepigazzini** [comment]
+1

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
