### PR TITLE
PPS: fix z sign in diamond geometry

### PR DESCRIPTION
**Pull request by jan-kaspar**
#### PR description:

Up to now, the z sign of diamond-RP geometry has been wrong (i.e. inconsistent with other PPS RPs).

This PR brings a fix:
  * for Run3 geometry, the fix is applied directly in the geometry XML file
  * for Run2 geometry, the fix is applied in the geometry builder code - in order to avoid the need to re-upload the geometry to DB, revalidate, ...

Thanks to the fix, the mitigation code is removed from:
  * proton-reco module
  * direct-simulation module

This is a technical PR, no change in results is expected.

#### PR validation:

Below few snippets from PPS geometry print out (module ``CTPPSGeometryInfo``). ``ce`` stands for the detector centre, the z component is the last number.

  * 2018, before PR:
```
2054160384 (diamd RP  16) | ce=(+73.050, -0.000, +215700.000)
2070937600 (diamd RP 116) | ce=(+73.050, -0.000, -215700.000)

2054160384 (diamd RP  16, plane 0, channel  0) | ce=(+3.325, +0.000, +215679.449)
2054164480 (diamd RP  16, plane 0, channel  1) | ce=(+4.825, +0.000, +215679.449)

2070937600 (diamd RP 116, plane 0, channel  0) | ce=(+3.325, +0.000, -215720.551)
2070941696 (diamd RP 116, plane 0, channel  1) | ce=(+4.825, +0.000, -215720.551)
```

  * 2018, after PR:
```
2054160384 (diamd RP  16) | ce=(+73.050, -0.000, -215700.000)
2070937600 (diamd RP 116) | ce=(+73.050, -0.000, +215700.000)

2054160384 (diamd RP  16, plane 0, channel  0) | ce=(+3.325, +0.000, -215679.449)
2054164480 (diamd RP  16, plane 0, channel  1) | ce=(+4.825, +0.000, -215679.449)

2070937600 (diamd RP 116, plane 0, channel  0) | ce=(+3.325, +0.000, +215720.551)
2070941696 (diamd RP 116, plane 0, channel  1) | ce=(+4.825, +0.000, +215720.551)
```

  * 2021, after PR:
```
2054160384 (diamd RP  16) | ce=(+72.050, -0.000, -215700.000)
2056257536 (diamd RP  22) | ce=(+72.050, -0.000, -215078.000)
2070937600 (diamd RP 116) | ce=(+72.050, -0.000, +215700.000)
2073034752 (diamd RP 122) | ce=(+72.050, -0.000, +215078.000)

2054160384 (diamd RP  16, plane 0, channel  0) | ce=(+2.325, +0.000, -215720.551)
2054164480 (diamd RP  16, plane 0, channel  1) | ce=(+3.825, +0.000, -215720.551)

2070937600 (diamd RP 116, plane 0, channel  0) | ce=(+2.325, +0.000, +215679.449)
2070941696 (diamd RP 116, plane 0, channel  1) | ce=(+3.825, +0.000, +215679.449)
```

Interpretation of the snippets:
  * 2018, comparison of before and after this PR: only the z component changed sign, as expected
  * comparison 2018 and 2021, both after the PR: the z signs are identical and correct (negative for LHC sector 45, positive for LHC sector 56)

Addition comparison plots (before and after the PR):
  * [dirsim_cmp.pdf](https://github.com/cms-sw/cmssw/files/5771116/dirsim_cmp.pdf): direct simulation of PPS
  * [reco_cmp.pdf](https://github.com/cms-sw/cmssw/files/5771118/reco_cmp.pdf): PPS reco of Run2 data
  * no difference observed - as expected

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
+1

**Comment by jfernan2** [comment]
+1

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/32603	ca280c2
- technical, relocating the z-sign flip from use cases to upstream, the geometry.
- jenkins tests pass without differences

**Comment by qliphy** [comment]
+1

**Pull request merged**
