### PR TITLE
DQMStore cleanup in preparation for concurrent booking

### PR DESCRIPTION
**Pull request by knoepfel**
This pull request does not include any functional or interface changes.  Rather, this pull request includes cleanups of `DQMStore` before embarking on implementing concurrent booking in earnest:

- Quite a bit of tidying using modern C++
- Removing the global `IBooker`/`IGetter` global members of `DQMStore` in favor of creating local ones on the fly whenever transaction booking takes place
- Improving the RAII usage

There was an uninitialized data member for one of the `DQMStore` constructors.  That has been fixed by relying on default-value (i.e. in-class) initialization, and by using a forwarding constructor.

### CODE REVIEW

**Comment by knoepfel** [comment]
@Dr15Jones  FYI

**Comment by dmitrijus** [comment]
@schneiml FYI

**Comment by dmitrijus** [comment]
+1

great work!

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
The test failures are not from this pull request since they also happened in the IB. 
[It appears there was a problem today with CERN's xrootd servers.]

**Comment by knoepfel** [comment]
Thanks for the heads-up @Dr15Jones.

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
Maybe the problem is from this pull request. Looking at one of the failing jobs I see this crash
```
Thread 7 (Thread 0x7f059d0f1700 (LWP 16242)):
#0  0x0000003be46e5419 in syscall () from /lib64/libc.so.6
#1  0x00007f05b638b86f in XrdSys::LinuxSemaphore::Wait (this=0x7f05a49fd1f8) at /build/cmsbld/jenkins/workspace/build-any-ib/w/BUILD/slc6_amd64_gcc630/external/xrootd/4.6.1-omkpbe3/xrootd-4.6.1/src/./XrdSys/XrdSysLinuxSemaphore.hh:161
#2  XrdCl::SyncQueue<XrdCl::JobManager::JobHelper>::Get (this=0x7f05a49e1b98) at /build/cmsbld/jenkins/workspace/build-any-ib/w/BUILD/slc6_amd64_gcc630/external/xrootd/4.6.1-omkpbe3/xrootd-4.6.1/src/./XrdCl/XrdClSyncQueue.hh:67
#3  XrdCl::JobManager::RunJobs (this=0x7f05a49e1b80) at /build/cmsbld/jenkins/workspace/build-any-ib/w/BUILD/slc6_amd64_gcc630/external/xrootd/4.6.1-omkpbe3/xrootd-4.6.1/src/XrdCl/XrdClJobManager.cc:146
#4  0x00007f05b638ba29 in RunRunnerThread (arg=<optimized out>) at /build/cmsbld/jenkins/workspace/build-any-ib/w/BUILD/slc6_amd64_gcc630/external/xrootd/4.6.1-omkpbe3/xrootd-4.6.1/src/XrdCl/XrdClJobManager.cc:33
#5  0x0000003be4a07aa1 in start_thread () from /lib64/libpthread.so.0
#6  0x0000003be46e8bcd in clone () from /lib64/libc.so.6
Thread 6 (Thread 0x7f059daf2700 (LWP 16241)):
#0  0x0000003be46e5419 in syscall () from /lib64/libc.so.6
#1  0x00007f05b638b86f in XrdSys::LinuxSemaphore::Wait (this=0x7f05a49fd1f8) at /build/cmsbld/jenkins/workspace/build-any-ib/w/BUILD/slc6_amd64_gcc630/external/xrootd/4.6.1-omkpbe3/xrootd-4.6.1/src/./XrdSys/XrdSysLinuxSemaphore.hh:161
#2  XrdCl::SyncQueue<XrdCl::JobManager::JobHelper>::Get (this=0x7f05a49e1b98) at /build/cmsbld/jenkins/workspace/build-any-ib/w/BUILD/slc6_amd64_gcc630/external/xrootd/4.6.1-omkpbe3/xrootd-4.6.1/src/./XrdCl/XrdClSyncQueue.hh:67
#3  XrdCl::JobManager::RunJobs (this=0x7f05a49e1b80) at /build/cmsbld/jenkins/workspace/build-any-ib/w/BUILD/slc6_amd64_gcc630/external/xrootd/4.6.1-omkpbe3/xrootd-4.6.1/src/XrdCl/XrdClJobManager.cc:146
#4  0x00007f05b638ba29 in RunRunnerThread (arg=<optimized out>) at /build/cmsbld/jenkins/workspace/build-any-ib/w/BUILD/slc6_amd64_gcc630/external/xrootd/4.6.1-omkpbe3/xrootd-4.6.1/src/XrdCl/XrdClJobManager.cc:33
#5  0x0000003be4a07aa1 in start_thread () from /lib64/libpthread.so.0
#6  0x0000003be46e8bcd in clone () from /lib64/libc.so.6
Thread 5 (Thread 0x7f059e4f3700 (LWP 16240)):
#0  0x0000003be46e5419 in syscall () from /lib64/libc.so.6
#1  0x00007f05b638b86f in XrdSys::LinuxSemaphore::Wait (this=0x7f05a49fd1f8) at /build/cmsbld/jenkins/workspace/build-any-ib/w/BUILD/slc6_amd64_gcc630/external/xrootd/4.6.1-omkpbe3/xrootd-4.6.1/src/./XrdSys/XrdSysLinuxSemaphore.hh:161
#2  XrdCl::SyncQueue<XrdCl::JobManager::JobHelper>::Get (this=0x7f05a49e1b98) at /build/cmsbld/jenkins/workspace/build-any-ib/w/BUILD/slc6_amd64_gcc630/external/xrootd/4.6.1-omkpbe3/xrootd-4.6.1/src/./XrdCl/XrdClSyncQueue.hh:67
#3  XrdCl::JobManager::RunJobs (this=0x7f05a49e1b80) at /build/cmsbld/jenkins/workspace/build-any-ib/w/BUILD/slc6_amd64_gcc630/external/xrootd/4.6.1-omkpbe3/xrootd-4.6.1/src/XrdCl/XrdClJobManager.cc:146
#4  0x00007f05b638ba29 in RunRunnerThread (arg=<optimized out>) at /build/cmsbld/jenkins/workspace/build-any-ib/w/BUILD/slc6_amd64_gcc630/external/xrootd/4.6.1-omkpbe3/xrootd-4.6.1/src/XrdCl/XrdClJobManager.cc:33
#5  0x0000003be4a07aa1 in start_thread () from /lib64/libpthread.so.0
#6  0x0000003be46e8bcd in clone () from /lib64/libc.so.6
Thread 4 (Thread 0x7f059eef4700 (LWP 16239)):
#0  0x0000003be4a0f00d in nanosleep () from /lib64/libpthread.so.0
#1  0x00007f05b6227753 in XrdSysTimer::Wait (mills=<optimized out>) at /build/cmsbld/jenkins/workspace/build-any-ib/w/BUILD/slc6_amd64_gcc630/external/xrootd/4.6.1-omkpbe3/xrootd-4.6.1/src/XrdSys/XrdSysTimer.cc:239
#2  0x00007f05b63305f7 in XrdCl::TaskManager::RunTasks (this=0x7f05a49d5680) at /build/cmsbld/jenkins/workspace/build-any-ib/w/BUILD/slc6_amd64_gcc630/external/xrootd/4.6.1-omkpbe3/xrootd-4.6.1/src/XrdCl/XrdClTaskManager.cc:244
#3  0x00007f05b6330749 in RunRunnerThread (arg=<optimized out>) at /build/cmsbld/jenkins/workspace/build-any-ib/w/BUILD/slc6_amd64_gcc630/external/xrootd/4.6.1-omkpbe3/xrootd-4.6.1/src/XrdCl/XrdClTaskManager.cc:37
#4  0x0000003be4a07aa1 in start_thread () from /lib64/libpthread.so.0
#5  0x0000003be46e8bcd in clone () from /lib64/libc.so.6
Thread 3 (Thread 0x7f059f8f5700 (LWP 16238)):
#0  0x0000003be46e91c3 in epoll_wait () from /lib64/libc.so.6
#1  0x00007f05b622c804 in XrdSys::IOEvents::PollE::Begin (this=0x7f05a49e1c60, syncsem=<optimized out>, retcode=<optimized out>, eTxt=<optimized out>) at /build/cmsbld/jenkins/workspace/build-any-ib/w/BUILD/slc6_amd64_gcc630/external/xrootd/4.6.1-omkpbe3/xrootd-4.6.1/src/./XrdSys/XrdSysIOEventsPollE.icc:213
#2  0x00007f05b6228e75 in XrdSys::IOEvents::BootStrap::Start (parg=0x7ffc922e4980) at /build/cmsbld/jenkins/workspace/build-any-ib/w/BUILD/slc6_amd64_gcc630/external/xrootd/4.6.1-omkpbe3/xrootd-4.6.1/src/XrdSys/XrdSysIOEvents.cc:131
#3  0x00007f05b6226f78 in XrdSysThread_Xeq (myargs=0x7f059fd47940) at /build/cmsbld/jenkins/workspace/build-any-ib/w/BUILD/slc6_amd64_gcc630/external/xrootd/4.6.1-omkpbe3/xrootd-4.6.1/src/XrdSys/XrdSysPthread.cc:86
#4  0x0000003be4a07aa1 in start_thread () from /lib64/libpthread.so.0
#5  0x0000003be46e8bcd in clone () from /lib64/libc.so.6
Thread 2 (Thread 0x7f05a633f700 (LWP 16205)):
#0  0x0000003be4a0f37d in waitpid () from /lib64/libpthread.so.0
#1  0x00007f05b5f588c7 in edm::service::cmssw_stacktrace_fork() () from /cvmfs/cms-ib.cern.ch/nweek-02515/slc6_amd64_gcc630/cms/cmssw-patch/CMSSW_10_1_X_2018-03-14-2300/lib/slc6_amd64_gcc630/pluginFWCoreServicesPlugins.so
#2  0x00007f05b5f59525 in edm::service::InitRootHandlers::stacktraceHelperThread() () from /cvmfs/cms-ib.cern.ch/nweek-02515/slc6_amd64_gcc630/cms/cmssw-patch/CMSSW_10_1_X_2018-03-14-2300/lib/slc6_amd64_gcc630/pluginFWCoreServicesPlugins.so
#3  0x00007f05bd21cc2f in std::execute_native_thread_routine (__p=0x7f05b6e76a00) at ../../../../../libstdc++-v3/src/c++11/thread.cc:83
#4  0x0000003be4a07aa1 in start_thread () from /lib64/libpthread.so.0
#5  0x0000003be46e8bcd in clone () from /lib64/libc.so.6
Thread 1 (Thread 0x7f05bcecfc20 (LWP 16076)):
#0  0x0000003be46df383 in poll () from /lib64/libc.so.6
#1  0x00007f05b5f58d04 in full_read.constprop () from /cvmfs/cms-ib.cern.ch/nweek-02515/slc6_amd64_gcc630/cms/cmssw-patch/CMSSW_10_1_X_2018-03-14-2300/lib/slc6_amd64_gcc630/pluginFWCoreServicesPlugins.so
#2  0x00007f05b5f595fa in edm::service::InitRootHandlers::stacktraceFromThread() () from /cvmfs/cms-ib.cern.ch/nweek-02515/slc6_amd64_gcc630/cms/cmssw-patch/CMSSW_10_1_X_2018-03-14-2300/lib/slc6_amd64_gcc630/pluginFWCoreServicesPlugins.so
#3  0x00007f05b5f5a6f6 in sig_dostack_then_abort () from /cvmfs/cms-ib.cern.ch/nweek-02515/slc6_amd64_gcc630/cms/cmssw-patch/CMSSW_10_1_X_2018-03-14-2300/lib/slc6_amd64_gcc630/pluginFWCoreServicesPlugins.so
#4  <signal handler called>
#5  0x00007f05bb921142 in std::_Rb_tree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::_Identity<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::find(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const () from /cvmfs/cms-ib.cern.ch/nweek-02515/slc6_amd64_gcc630/cms/cmssw/CMSSW_10_1_X_2018-03-12-2300/lib/slc6_amd64_gcc630/libFWCoreMessageService.so
#6  0x00007f05b48b8bdd in DQMStore::makeDirectory(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) () from /build/cmsbld/jenkins/workspace/ib-any-integration/CMSSW_10_1_X_2018-03-14-2300/lib/slc6_amd64_gcc630/libDQMServicesCore.so
#7  0x00007f05b48b8feb in DQMStore::setCurrentFolder(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) () from /build/cmsbld/jenkins/workspace/ib-any-integration/CMSSW_10_1_X_2018-03-14-2300/lib/slc6_amd64_gcc630/libDQMServicesCore.so
#8  0x00007f0594e7b595 in TkHistoMap::folderDefinition(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) () from /build/cmsbld/jenkins/workspace/ib-any-integration/CMSSW_10_1_X_2018-03-14-2300/lib/slc6_amd64_gcc630/libDQMSiStripCommon.so
#9  0x00007f0594e7be77 in TkHistoMap::createTkHistoMap(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, float, bool) () from /build/cmsbld/jenkins/workspace/ib-any-integration/CMSSW_10_1_X_2018-03-14-2300/lib/slc6_amd64_gcc630/libDQMSiStripCommon.so
#10 0x00007f0594e7c69c in TkHistoMap::TkHistoMap(TkDetMap const*, DQMStore::IBooker&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, float, bool) () from /build/cmsbld/jenkins/workspace/ib-any-integration/CMSSW_10_1_X_2018-03-14-2300/lib/slc6_amd64_gcc630/libDQMSiStripCommon.so
#11 0x00007f0589569020 in MonitorTrackResidualsBase<(TrackerType)0>::bookHistograms(DQMStore::IBooker&, edm::Run const&, edm::EventSetup const&) () from /build/cmsbld/jenkins/workspace/ib-any-integration/CMSSW_10_1_X_2018-03-14-2300/lib/slc6_amd64_gcc630/pluginDQMTrackerMonitorTrack.so
#12 0x00007f05b48b3845 in DQMEDAnalyzer::beginRun(edm::Run const&, edm::EventSetup const&) () from /build/cmsbld/jenkins/workspace/ib-any-integration/CMSSW_10_1_X_2018-03-14-2300/lib/slc6_amd64_gcc630/libDQMServicesCore.so
#13 0x00007f05bee2f69b in edm::one::EDProducerBase::doBeginRun(edm::RunPrincipal const&, edm::EventSetup const&, edm::ModuleCallingContext const*) () from /cvmfs/cms-ib.cern.ch/nweek-02515/slc6_amd64_gcc630/cms/cmssw-patch/CMSSW_10_1_X_2018-03-14-2300/lib/slc6_amd64_gcc630/libFWCoreFramework.so
#14 0x00007f05bed77b30 in edm::WorkerT<edm::one::EDProducerBase>::implDoBegin(edm::RunPrincipal const&, edm::EventSetup const&, edm::ModuleCallingContext const*) () from /cvmfs/cms-ib.cern.ch/nweek-02515/slc6_amd64_gcc630/cms/cmssw-patch/CMSSW_10_1_X_2018-03-14-2300/lib/slc6_amd64_gcc630/libFWCoreFramework.so
#15 0x00007f05bed46636 in decltype ({parm#1}()) edm::convertException::wrap<bool edm::Worker::runModule<edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)0> >(edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)0>::MyPrincipal const&, edm::EventSetup const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)0>::Context const*)::{lambda()#1}>(bool edm::Worker::runModule<edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)0> >(edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)0>::MyPrincipal const&, edm::EventSetup const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)0>::Context const*)::{lambda()#1}) () from /cvmfs/cms-ib.cern.ch/nweek-02515/slc6_amd64_gcc630/cms/cmssw-patch/CMSSW_10_1_X_2018-03-14-2300/lib/slc6_amd64_gcc630/libFWCoreFramework.so
#16 0x00007f05bed4687c in bool edm::Worker::runModule<edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)0> >(edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)0>::MyPrincipal const&, edm::EventSetup const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)0>::Context const*) () from /cvmfs/cms-ib.cern.ch/nweek-02515/slc6_amd64_gcc630/cms/cmssw-patch/CMSSW_10_1_X_2018-03-14-2300/lib/slc6_amd64_gcc630/libFWCoreFramework.so
#17 0x00007f05bed46b4b in std::__exception_ptr::exception_ptr edm::Worker::runModuleAfterAsyncPrefetch<edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)0> >(std::__exception_ptr::exception_ptr const*, edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)0>::MyPrincipal const&, edm::EventSetup const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)0>::Context const*) () from /cvmfs/cms-ib.cern.ch/nweek-02515/slc6_amd64_gcc630/cms/cmssw-patch/CMSSW_10_1_X_2018-03-14-2300/lib/slc6_amd64_gcc630/libFWCoreFramework.so
#18 0x00007f05bed47008 in void edm::SerialTaskQueueChain::actionToRun<edm::Worker::RunModuleTask<edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)0> >::execute()::{lambda()#1}&>(edm::Worker::RunModuleTask<edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)0> >::execute()::{lambda()#1}&) () from /cvmfs/cms-ib.cern.ch/nweek-02515/slc6_amd64_gcc630/cms/cmssw-patch/CMSSW_10_1_X_2018-03-14-2300/lib/slc6_amd64_gcc630/libFWCoreFramework.so
#19 0x00007f05bed47091 in edm::SerialTaskQueue::QueuedTask<void edm::SerialTaskQueueChain::push<edm::Worker::RunModuleTask<edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)0> >::execute()::{lambda()#1}&>(edm::Worker::RunModuleTask<edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)0> >::execute()::{lambda()#1}&)::{lambda()#1}>::execute() () from /cvmfs/cms-ib.cern.ch/nweek-02515/slc6_amd64_gcc630/cms/cmssw-patch/CMSSW_10_1_X_2018-03-14-2300/lib/slc6_amd64_gcc630/libFWCoreFramework.so
#20 0x00007f05bd93642c in tbb::internal::custom_scheduler<tbb::internal::IntelSchedulerTraits>::local_wait_for_all (this=0x7f05bc907200, parent=..., child=<optimized out>) at ../../src/tbb/custom_scheduler.h:509
#21 0x00007f05bedd6b61 in edm::EventProcessor::beginRun(edm::Hash<2> const&, unsigned int, bool&) () from /cvmfs/cms-ib.cern.ch/nweek-02515/slc6_amd64_gcc630/cms/cmssw-patch/CMSSW_10_1_X_2018-03-14-2300/lib/slc6_amd64_gcc630/libFWCoreFramework.so
#22 0x00007f05bedd7531 in edm::EventProcessor::runToCompletion() () from /cvmfs/cms-ib.cern.ch/nweek-02515/slc6_amd64_gcc630/cms/cmssw-patch/CMSSW_10_1_X_2018-03-14-2300/lib/slc6_amd64_gcc630/libFWCoreFramework.so
#23 0x000000000040e782 in main::{lambda()#1}::operator()() const ()
#24 0x000000000040d17a in main ()
```

This should be reproduced doing `runTheMatrix.py -l 4.22`

**Comment by Dr15Jones** [comment]
Kyle and I found the problem, it is this piece of code that assumes IBooker and IGetter have long lifetimes
https://github.com/cms-sw/cmssw/blob/30329beb2ae0c5788e5dab332c6f39aef0bfef30/DQM/SiStripCommon/src/TkHistoMap.cc#L56

**Comment by dmitrijus** [comment]
> Kyle and I found the problem, it is this piece of code that assumes IBooker and IGetter have long lifetimes

We shall see it reworked and fixed. It is a misuse of the DQMStore.
Previously, we thought TKHistoMap is not run centrally, we were wrong.

**Comment by knoepfel** [comment]
@dmitrijus we think we can make some minor adjustments to `TkHistoMap` so that this pull request could go in.  Such changes, however, would not collide with any re-workings you'd like to do.  Sound okay?

**Comment by schneiml** [comment]
Be aware there may be more places where things like that are done, typically not covered by PR/IB tests (also, TkHistoMap was not supposed to be in there, normally it is used in a private workflow). We should eliminate all of these instances, but it will require some interaction with the subsystems.

**Comment by boudoul** [comment]
Hi @schneiml , I don't think this statement 'TkHistoMap was not supposed to be in there, normally it is used in a private workflow)'  is true ....

**Comment by schneiml** [comment]
@boudoul I was afraid it might not be true. I usually assumed what is going on there is fine because it does not run in normal offline sequences... So either way, we need to fix TkHistoMap and maybe more, since you probably want the functionality that it provides.

**Comment by schneiml** [comment]
@knoepfel I just tried disallowing what that module does (taking pointers of the IBooker), and got a list of modules that do that sort of things: http://mschneid.web.cern.ch/mschneid/pointers-to-ibooker

Not too many, and maybe some false positives, but we should check each of them.

**Comment by knoepfel** [comment]
@schneiml thanks.  I've just committed some changes for the `TkHistoMap`, so the tests should come back a little better.  But I'll work through the others you pointed me to.

**Comment by Dr15Jones** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
