### PR TITLE
Enhancements to GBRForest/Tree for converting TMVA classifiers (74X)

### PR DESCRIPTION
**Pull request by lgray**
Backport of #10275 

@bendavid

### CODE REVIEW

**Comment by diguida** [comment]
please test

**Comment by lgray** [comment]
@diguida @ggovi Could we get your +1s here? Thanks!

**Comment by ggovi** [comment]
+1

**Comment by diguida** [comment]
+1
Interface changes in `CondFormats/EgammaObjects/interface/GBRForest.h` and `CondFormats/EgammaObjects/interface/GBRTree.h` do not modify the serializable data members.
Backport of #10275

**Comment by diguida** [comment]
@lgray sorry for late signing, and thanks for the reminder.
@davidlange6 what is the proposed strategy here? I think that `CMSSW_7_6_0_pre2` RelVal should confirm that no changes are seen. In this case, you can merge, but this will trigger a full build (interface changes).
Unfortunately I missed this at the ORP meeting: do you want me to add it to the TWiki for reference?

**Comment by slava77** [comment]
@davidlange6 please check
this is blocking further backports now (10475)

**Comment by davidlange6** [comment]
+1

**Pull request merged**
