### PR TITLE
Use `Run4` for Phase2 PU inputs

### PR DESCRIPTION
**Pull request by AdrianoDee**
#### PR description:

Trivial fix for the PU input to be used in Phase2 wfs. Spotted by @Parsifal-2045 (thanks!) in https://github.com/cms-sw/cmssw/issues/46839.

#### PR validation:

None

### CODE REVIEW

**Comment by AdrianoDee** [comment]
type bug-fix

**Comment by AdrianoDee** [comment]
please test

**Comment by Moanwar** [comment]
+Upgrade

**Comment by AdrianoDee** [comment]
please test

**Comment by AdrianoDee** [comment]
+pdmv

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
