### PR TITLE
Added a tool to do a bin by bin DQM root file comparison

### PR DESCRIPTION
**Pull request by andrius-k**
#### PR description:

This PR adds a tool to perform a thorough bin by bin comparison of DQM root files. The main intention is to use this tool during the comparison stage of DQM pull request tests.

#### PR validation:

The tool does not run as part of CMSSW but rather as a standalone tool, so only local testing of the logic of the tool was made.

### CODE REVIEW

**Comment by andrius-k** [comment]
please test

**Comment by andrius-k** [comment]
+1

**Comment by andrius-k** [comment]
@fabiocos This PR has no implications and the tool is needed for DQM development as soon as possible. As soon as it will be integrated into master we will be able to use it in PR tests.

**Comment by fabiocos** [comment]
hold

pending a clarification

**Comment by schneiml** [comment]
@fabiocos a short list of reasons why I like this tool much better than the RelMon output:
- The output is short and clear.
- Differences are uploaded to DQMGUI, which is the standard tool to visualize DQM data. Static PNGs don't get anywhere close in functionality.
- DQMGUI/the tool also provides access to the ROOT files for manual inspection.
- It does not assume anything about the file structure, and can catch fundamental changes (like the references in #26258).

Overall, the working assumption of RelMon is that DQM is working correctly and we want to validate changes in reconstruction etc., while what we need for the coming DQM infrastructure work (starting with #26232 ) is reliable information on whether DQM is still behaving correctly.

**Comment by schneiml** [comment]
see also: https://github.com/cms-sw/cms-bot/issues/1110
I'd be happy if I could run this tool myself, but other technical difficulties make that harder than expected...

**Comment by andrius-k** [comment]
@fabiocos You are correct, this tool does not have any external dependencies.

The tool that I'm introducing is different than `compare_using_files.py`. I did local testing of the said tool and it reports 100% success (I assume that means that histograms are the same) even if the number of fill calls on TH1Fs is different. I crafted root files with a test histogram for this test myself. Existing tool clearly doesn't do the bin by bin comparison but rather something else, with some allowed margin of error. This is not suitable for us at all. The tool also makes assumptions about the structure of a DQM root file while my tool does not. This allowed us to spot the issue where [legacy references were being written into DQM root files](https://github.com/cms-sw/cmssw/pull/26258).

Another issue is that browsing through generated html pages is a bit cumbersome especially if there are quite a few plots. We provide a familiar and the only official way to explore DQM plots - the DQM GUI.

And lastly, another important factor for us is speed. Our tool does not have to generate `.png` files for every overlay comparison and therefore is significantly faster.

We have already started cleaning up and changing the internals of DQM code and we need a tool that will reassure as that we did not break thousands of subsystems histograms. No current tool can do that and our development, therefore, is slowed down until the tool is merged.

**Comment by andrius-k** [comment]
please test

**Comment by davidlange6** [comment]
> On Apr 3, 2019, at 12:59 PM, Andrius <notifications@github.com> wrote:
> 
> @fabiocos You are correct, this tool does not have any external dependencies.
> 
> The tool that I'm introducing is different than compare_using_files.py. I did local testing of the said tool and it reports 100% success (I assume that means that histograms are the same) even if the number of fill calls on TH1Fs is different. I crafted root files with a test histogram for this test myself. Existing tool clearly doesn't do the bin by bin comparison but rather something else, with some allowed margin of error. This is not suitable for us at all. The tool also makes assumptions about the structure of a DQM root file while my tool does not. This allowed us to spot the issue where legacy references were being written into DQM root files.

did you actually try to learn the tool or just blindly run it? I guess you are blindly running it based on all of these issues...

**Comment by andrius-k** [comment]
@davidlange6 
> did you actually try to learn the tool or just blindly run it? I guess you are blindly running it based on all of these issues...

It doesn't matter how configurable the tool is because we can't change what the bot is running anyway. And yes, I'm aware of its functionality and it doesn't work for us! If you have concrete suggestions on how we can achieve what we want with an existing toolset I'd very much like to hear them. Otherwise I'd like to be spending my time preparing for UL ReReco using my tool instead of trying to convince you that it's necessary. 

@fabiocos 
UL ReReco deadline is approaching really quickly and we want to prepare a per lumisection saving functionality (#26232) for it. This tool is necessary for that.
If you have other questions or concerns please express them as soon as possible because time is running out quickly for us.

**Comment by andrius-k** [comment]
@fabiocos @davidlange6 Do you have any other questions or concerns regarding this tool?

**Comment by fabiocos** [comment]
unhold

following the discussion at the Core Software meeting https://indico.cern.ch/event/817694/contributions/3413621/attachments/1836773/3009721/go
it was agreed to test this code, allowing the DQM team to use it for its developments scheduled for beginning of summer, and re-discuss at that time possible ways of converging with RelMon after some experience has been gained

**Comment by fabiocos** [comment]
please test

**Comment by andrius-k** [comment]
+1

**Comment by fabiocos** [comment]
@andrius-k @schneiml @fioriNTU a first observation: the differences in the DQM TimerService are not filtered out (as it is done for instance in the RelMon report by the cms-bot). Even on a null comparison as this one this is going to create artificial differences...

**Comment by fabiocos** [comment]
+1

**Pull request merged**
