### PR TITLE
Change FEStatus flag labels in ECAL DQM

### PR DESCRIPTION
**Pull request by kyungminparkdrums**
#### PR description:

This PR changes the flag labels of the FE Status plots in the ECAL DQM plot

*   FIFOFULL -> FORCEDFULLSUPP
*   FULLL1ADESYNC -> FIFOFULL

#### PR validation:

PR is validated by running the ECAL online DQM configuration and verifying the plots on a test DQM GUI.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

This is the Master PR. Backports are made to `14_0_X` in the PR #44404

### CODE REVIEW

**Comment by tjavaid** [comment]
please test

**Comment by kyungminparkdrums** [comment]
Hi, the error is unrelated to the changes I've made in the scripts inside the `DQM` for the PR.

**Comment by antoniovilela** [comment]
please test

**Comment by tjavaid** [comment]
+1

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
