### PR TITLE
[PPS] Diamond DQM patch for 2017

### PR DESCRIPTION
**Pull request by forthommel**
#### PR description:

This PR allows rechits with negative OOT index to be discarded in the population of the per-BX activity and pixel tomography monitoring plots for the PPS diamond detector. This allows to fix a `std::out_of_range` exception raised in e.g. 2017C relvals workflows (see e.g. [here](https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?campaign=CMSSW_10_6_1__dataUL2017C_stdDQM-1562786386)), as the time acquisition window was significantly larger (thus increasing the multiplicity of OOT hits).

@fabferro, @prebello, @vavati, @jfernan2

#### PR validation:

Successfully tested on the "faulty" workflow on a `10_6_1`, and forward-ported on this `11_0_X` master branch.

```sh
$ cmsDriver.py step3 --conditions 106X_dataRun2_v15 \
  -s RAW2DIGI,L1Reco,RECO,SKIM:ZElectron,EI,PAT,ALCA:EcalCalZElectron+EcalUncalZElectron+HcalCalIterativePhiSym+HcalCalIsoTrkFilter,DQM:@standardDQM+@ExtraHLT+@miniAODDQM 
  --runUnscheduled --process reRECO --data --era Run2_2017 \
  --eventcontent RECO,MINIAOD,DQM --hltProcess reHLT --scenario pp \
  --datatier RECO,MINIAOD,DQMIO \
  --customise Configuration/DataProcessing/RecoTLR.customisePostEra_Run2_2017 \
  --filein=/store/relval/CMSSW_10_6_1/DoubleEG/FEVTDEBUGHLT/103X_dataRun2_HLT_relval_v8_stdDQM_RelVal_2017C-v1/20000/9894C3EA-791C-4E47-B4F4-537828FFEF62.root
```

#### if this PR is a backport please specify the original PR: N/A

Before submitting your pull requests, make sure you followed this checklist:
- [x] verify that the PR is really intended for the chosen branch
- [x] verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- [x] verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
@forthommel  please note that this PR needs a backport to 9_6_1 and extra commits taking care of the configuration part, namely replacing the removed code on:
https://github.com/cms-sw/cmssw/pull/27571
https://github.com/cms-sw/cmssw/pull/27570  (backport)
The config code could be added on top of the above commits if you provide the corresponding modules

**Comment by forthommel** [comment]
> @forthommel please note that this PR needs a backport to 9_6_1 and extra commits taking care of the configuration part, namely replacing the removed code on:
> #27571
> #27570 (backport)
> The config code could be added on top of the above commits if you provide the corresponding modules

Many thanks, @jfernan2 ! However, since neither #27571 nor #27570 are merged in the two branches, would not it be simpler to simply discard these latter two open PRs and concentrate on this one (and the backport PR I am about to launch)?

**Comment by jfernan2** [comment]
@forthommel  fine with me, but I want to insist that you are not touching python configuration to include CT-PPS properly in the Validation in THIS PR (either in the backport), hence my insistence.

The lines touched by  #27571 nor #27570 should be replaced by other as the email thread in which you are included reads.

**Comment by forthommel** [comment]
@jfernan2 Also perfectly fine for me.

**Comment by jfernan2** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
