### PR TITLE
Tools for creating and writing HBHENegativeEFilter objects to CMS db

### PR DESCRIPTION
**Pull request by igv4321**
Executables and instructions for making and writing HBHENegativeEFilter (a.k.a. HCAL negative energy filter) objects into the CMS database.

Detailed description and instructions can be found in the file CondTools/Hcal/test/readme_HBHENegativeEFilter.txt.

This PR will not modify any existing results.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by igv4321** [comment]
@ggovi Please take a look and sign if you see no problems

**Comment by ggovi** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
