### PR TITLE
Backport offline PU ID fix from #12053 to 74

### PR DESCRIPTION
**Pull request by ahinzmann**
It requires cms-data/RecoJets-JetProducers#6 to be merged into 74X FIRST.
Backport of offline PU ID (but not HLT PU ID) fixes in #12053 to make it usable for analyses.
Tested with RecoJets/JetProducers/test/testJetTools_cfg.py

This PR uses the new weight names from cms-data/RecoJets-JetProducers#6 to fix the bug for cut based pu ID. The names of offline and online pu ID are now the same. Nevertheless,this PR targets mainly the offline pu ID. The fix includes that cut-based variables have the same name as MVA variables as well as including the pull variable in the offline pu ID. The code was tested and gives reasonable values for all variables (online and offline) before running the MVA.

### CODE REVIEW

**Comment by slava77** [comment]
@ahinzmann 
this PR will also change the results for objects produced in the standard workflows, right?
The goal for changes in the production releases is to not change the defaults, new behavior better be available with a change in configuration.
It is not the case for this PR.
I suppose, the PR can stay as a reference as a part of recipes (but will not go to 74X until this release reopens for backports/ "new features")

**Comment by ahinzmann** [comment]
The main purpose is to be able to have a recipe for analyzers in 74 indeed.
For this at least the cms-data/RecoJets-JetProducers#6 is needed in the release. Is this possible?
The default 74X behavior is a broken PU jet ID, not sure if we need to keep this in the release, that's up to you.

**Comment by slava77** [comment]
I think that the external data update can be made.
@degano is there a way to jenkins test a cmsdist PR adding an external without a cmssw PR?

**Comment by slava77** [comment]
-1
to take it off the list of PRs in need of the reco signature for the purpose of integration to 74X.
We do not plan to integrate in 74X PRs that change products produced in the standard RECO+MINIAOD sequence.
this PR  stays as a reference for analysis level recipes.

**Pull request closed without merging**
