### PR TITLE
Correcting index in getAntiDecayTable

### PR DESCRIPTION
**Pull request by mmasciov**
Same as PR #21673

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
hi @mmasciov @civanch - can you say more about this fix and its impact?

**Comment by civanch** [comment]
Hi @davidlange6 , the bug was introduced in CMSSW_7_5_X, this bug means incorrect list of decay products for the case when anti-particle of an exotic particle is created. Concrete cases @mmasciov may explain. May be link to some talk may be added to the description of this PR?

**Comment by mmasciov** [comment]
Hi @davidlange6 @civanch, what @civanch says is correct: this bug was preventing the (correct) decay of anti-particles, in particular of exotic/susy particles. The ith daughter was being overwritten with the jth daughter, as the index of the array name was mistaken.
I'm not aware of talks describing such problem. 
I got into this issue while simulating a signal with a decaying SUSY particle (1000024), and I have checked that this line was the source of the issue. After correcting this line, the signal looks as expected. 
I believe no central signal was produced yet making use of this module (last signal of this kind was generated using 7_1_X). The problem would have been there for 2017 signal MC (that will be generated using 9_3_X).

**Comment by davidlange6** [comment]
+1

Thanks for the full explanation - glad it doesn't affect any production. Seems we need better tests for @civanch to use if he wants to continue changing this part of the sim code in the future...

**Pull request merged**
