### PR TITLE
Database object for the HCAL negative energy filter

### PR DESCRIPTION
**Pull request by igv4321**
Database object for the HCAL negative energy filter. Current filter relies on "Method 1" OOT pileup subtraction which is no longer being used. This object will allow us to remove dependence on "Method 1".

Once this code gets in and the relevant tag gets into the relval GT, the HCAL reco code will be modified to use it.

### CODE REVIEW

**Comment by degano** [comment]
please test

**Comment by igv4321** [comment]
please test

**Comment by abdoulline** [comment]
May we have it approved to move further with Noise filters preparations for data taking?
Thank you.

**Comment by mmusich** [comment]
+1 
@ggovi please also have a look

**Comment by slava77** [comment]
This PR is holding developments for the negative energy filter.

Igor and Salavat, will this code change (negative energy filter) be needed for 74X or can we really keep it just in 75X developments (for the next reprocessing)?

**Comment by ggovi** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
