### PR TITLE
Updating Global Tags with latest requests by L1, Pixel, Geometry

### PR DESCRIPTION
**Pull request by mmusich**
# List of Changes
- Run1 Ideal Simulation `75X_mcRun1_design_v3`: as `75X_mcRun1_design_v1` with
  - updated HCAL spec pars, adding extra constants and regexps for selection (no changes in geometry). 
- Run1 Realistic Simulation `75X_mcRun1_realistic_v3` as: `75X_mcRun1_realistic_v1` with
  - updated HCAL spec pars, adding extra constants and regexps for selection (no changes in geometry). 
- Run1 Heavy Simulation `75X_mcRun1_HeavyIon_v3` as: `75X_mcRun1_HeavyIon_v1` with
  - updated HCAL spec pars, adding extra constants and regexps for selection (no changes in geometry). 
- Run1 proton-Lead Simulation `75X_mcRun1_pA_v3`: as `75X_mcRun1_pA_v1` with
  - updated HCAL spec pars, adding extra constants and regexps for selection (no changes in geometry). 
- Run2 startup Simulation `75X_mcRun2_startup_v3`: as  `75X_mcRun1_startup_v1` with:
  - updated HCAL spec pars, adding extra constants and regexps for selection (no changes in geometry) in all supported scenario (including dev) 
  - updated L1 Global Trigger Menu (v4) 
  - updated Global Muon Trigger parameter 
  - updated Pixel dead channels map from 3.8T 2015B collisions.  
- Run2 Ideal Simulation `75X_mcRun2_design_v3`: as  `75X_mcRun2_design_v1` with:
  - updated HCAL spec pars, adding extra constants and regexps for selection (no changes in geometry) in all supported scenario (including dev) 
  - updated Global Muon Trigger parameter 
- Run2 asymptotic Simulation `75X_mcRun2_asymptotic_v3`: as `75X_mcRun1_asymptotic_v1` with
  - updated HCAL spec pars, adding extra constants and regexps for selection (no changes in geometry) in all supported scenario (including dev) 
  - updated Global Muon Trigger parameter 
  - updated Pixel dead channels map from 3.8T 2015B collisions.  
- Run2 Heavy Ion Simulation `75X_mcRun2_HeavyIon_v3`: as `75X_mcRun1_HeavyIon_v1` with 
  - updated HCAL spec pars, adding extra constants and regexps for selection (no changes in geometry) in all supported scenario (including dev)  
  - updated Global Muon Trigger parameter 
  - updated Pixel dead channels map from 3.8T 2015B collisions 
  - updated L1 Global Trigger Menu (`CollisionsHeavyIons2011_v0_nobsc_notau_centrality_q2_singletrack.v1`)  
  - fixed SiPixelDynamic inefficiency to use flat .999 efficiency payload.  

---

No changes in offline/HLT run1 and run2 data processing

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by diguida** [comment]
+1

**Comment by mmusich** [comment]
@davidlange6, so shall we just remove the b-tag training waiting for 760_pre2 release validation?
There rest is either a fix, or transparent or needed.

**Comment by davidlange6** [comment]
yes please - (maybe we should do a validation in 75x too, but not together with the other changes that should be just fixes)

**Comment by diguida** [comment]
@cmsbuild please notice changes

**Comment by diguida** [comment]
please test

**Comment by mmusich** [comment]
@davidlange6 we removed the BTV training, but this will result in the ugly feature that v2 version GT (with the most updated conditions) will supersede the ones proposed here v3

**Comment by mmusich** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
