### PR TITLE
phaseI  geometry updates, alignment ideal pixel and realistic strip, ideal phaseI BS away from 000

### PR DESCRIPTION
**Pull request by franzoni**
# Summary of changes in Global Tags

## RunII simulation

   * **PhaseI 2017 cosmics scenario** : [90X_upgrade2017cosmics_realistic_peak_v7](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_upgrade2017cosmics_realistic_peak_v7) as [90X_upgrade2017cosmics_realistic_peak_v6](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_upgrade2017cosmics_realistic_peak_v6) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/90X_upgrade2017cosmics_realistic_peak_v7/90X_upgrade2017cosmics_realistic_peak_v6):
      * geometry updates to fit large-size pixel reactivated, see Tracker Overlap Bugfixes #17383 and Replace Polycone in Pixel Fwd #17387 https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2803/1.html
      * alignment payload with ideal pixel and strip as in the current realistic phase-0 scenario (en par with phase0 as far as pixel are concerned)

   * **PhaseI 2017 design scenario** : [90X_upgrade2017_design_IdealBS_v7](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_upgrade2017_design_IdealBS_v7) as [90X_upgrade2017_design_IdealBS_v6](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_upgrade2017_design_IdealBS_v6) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/90X_upgrade2017_design_IdealBS_v7/90X_upgrade2017_design_IdealBS_v6):
      * Ideal_Centered_SLHC_v3 is physics-wise the same as Ideal_Centered_SLHC_v2, except small 1E-5 displacement in Z to stay away from 000
      * geometry updates to fit large-size pixel reactivated, Tracker Overlap Bugfixes #17383 and Replace Polycone in Pixel Fwd #17387 , see : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2803/1.html

   * **PhaseI 2017 realistic scenario** : [90X_upgrade2017_realistic_v7](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_upgrade2017_realistic_v7) as [90X_upgrade2017_realistic_v6](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_upgrade2017_realistic_v6) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/90X_upgrade2017_realistic_v7/90X_upgrade2017_realistic_v6):
      * geometry updates to fit large-size pixel reactivated, see Tracker Overlap Bugfixes #17383 and Replace Polycone in Pixel Fwd #17387 https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2803/1.html
      * alignment payload with ideal pixel and strip as in the current realistic phase-0 scenario (en par with phase0 as far as pixel are concerned)

   * **PhaseI 2018 cosmics scenario** : [90X_upgrade2018cosmics_realistic_peak_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_upgrade2018cosmics_realistic_peak_v5) as [90X_upgrade2018cosmics_realistic_peak_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_upgrade2018cosmics_realistic_peak_v4) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/90X_upgrade2018cosmics_realistic_peak_v5/90X_upgrade2018cosmics_realistic_peak_v4):
      * geometry updates to fit large-size pixel reactivated, see Tracker Overlap Bugfixes #17383 and Replace Polycone in Pixel Fwd #17387 https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2803/1.html
      * alignment payload with ideal pixel and strip as in the current realistic phase-0 scenario (en par with phase0 as far as pixel are concerned)

   * **PhaseI 2018 design scenario** : [90X_upgrade2018_design_IdealBS_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_upgrade2018_design_IdealBS_v5) as [90X_upgrade2018_design_IdealBS_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_upgrade2018_design_IdealBS_v4) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/90X_upgrade2018_design_IdealBS_v5/90X_upgrade2018_design_IdealBS_v4):
      * Ideal_Centered_SLHC_v3 is physics-wise the same as Ideal_Centered_SLHC_v2, except small 1E-5 displacement in Z to stay away from 000
      * geometry updates to fit large-size pixel reactivated, see Tracker Overlap Bugfixes #17383 and Replace Polycone in Pixel Fwd #17387 https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2803/1.html

   * **PhaseI 2018 realistic scenario** : [90X_upgrade2018_realistic_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_upgrade2018_realistic_v5) as [90X_upgrade2018_realistic_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_upgrade2018_realistic_v4) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/90X_upgrade2018_realistic_v5/90X_upgrade2018_realistic_v4):
      * geometry updates to fit large-size pixel reactivated, see Tracker Overlap Bugfixes #17383 and Replace Polycone in Pixel Fwd #17387 https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2803/1.html
      * alignment payload with ideal pixel and strip as in the current realistic phase-0 scenario (en par with phase0 as far as pixel are concerned)

### CODE REVIEW

**Comment by franzoni** [comment]
please test

**Comment by franzoni** [comment]
+1

. observed differences in MC 2017 workflows -> ok.
. *oddly*, observed differences also in the 2016B data (un-justified since this PR only modifies GT's for MC workflows), concentrated in AlCaReco/SiStrip 

. thanks to @mmusich for the records,
I gather such fluctuation in might relate to https://its.cern.ch/jira/browse/CMSTRACK-151 
( needs follow up )

**Comment by franzoni** [comment]
hello @davidlange6 

Due to the PPD workshop ongoing -> I won't be able to attend ORP tonight - apologies.

It would be great if this PR ( @slava77 : do you want to inspect it? )
could be merged at earliest convenience
there's more conditions expected (not yet in AlCa db hands) due to come in by pre4
( HCAL detector type, pixel local conditions)

**Comment by davidlange6** [comment]
+1

**Pull request merged**
