### PR TITLE
[14_0_X] New plugin for gen-part isolation.

### PR DESCRIPTION
**Pull request by namapane**
#### PR description:
Backport of #44623.

### CODE REVIEW

**Comment by vlimant** [comment]
enable nano

**Comment by vlimant** [comment]
please test

**Comment by vlimant** [comment]
+1

**Comment by vlimant** [comment]
N.B : #44664 will popup unless we modify this PR

**Comment by vlimant** [comment]
-xpog

**Comment by hqucms** [comment]
please test workflow 546.0,547.0,548.0

**Comment by hqucms** [comment]
+1

Failures for workflows 546.0,547.0,548.0 fixed by https://github.com/cms-sw/cmssw/pull/44654/commits/4ee621cb4975121157cbfc0a13145ab0843d6cc9.

**Comment by hqucms** [comment]
Backport of https://github.com/cms-sw/cmssw/pull/44623

**Comment by rappoccio** [comment]
+1

**Pull request merged**
