### PR TITLE
Disabled looper reconstruction in HI Eras for Run3_pp_on_PbPb and Run2…

### PR DESCRIPTION
**Pull request by sayanchatterjee38**
PR description:

Title: Disabled looper reconstruction in HI Eras for Run 3_pp_on_PbPb and Run2_2018_pp_on_AA

Description: This PR has disabled looper reconstruction from HI Eras after checking timing and CPU usage, tracking efficiency, fake, multiple, non-primary reconstructions fractions for peripheral and central events. Also, the same checks were performed in the MinimumBias dataset produced for 1000 events. Please, see slides 1-9 from here [1].

No significant changes were observed in event and track variables while removing the No-Looper condition except for the Hit count distribution.

An issue had been raised already regarding disabling looper reconstruction for HeavyIons. Please look here [2] for detail.

Link for the HI Trackin POG:
[1] https://indico.cern.ch/event/1153062/contributions/4841907/attachments/2429416/4159748/NoLooper_HITracking.pdf

Link for the issue:
[2] https://github.com/cms-sw/cmssw/issues/35758

PR validation:

Run time observations and a detailed study of each track variable have been performed with enabling and disabling trackingNoLoopers. We have also performed a detailed comparison of tracking efficiency, fake, multiple, and nonprimary reconstruction fractions for central, peripheral, and minimum bias events with enabling and disabling trackingNoLoopers.

If this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

cc: @mandrenguyen, @abaty, @CesarBernardes

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by jpata** [comment]
If I recall correctly, the discussion in the previous PR was if this should also be disabled for the other years in Run2.
Reco preference is to have the configurations as similar as possible across different eras (unless there are good physics reasons).
On the other hand, in the end it's only the HI group who will be consuming these data, and if there's no capacity or reason to recheck the older periods, I wouldn't push on it too hard. So if you and the tracking POG confirm that doing only 2018+Run3 is fine, I have no objection and will sign it.

**Comment by mmusich** [comment]
>  So if you and the tracking POG confirm that doing only 2018+Run3 is fine, I have no objection and will sign it.

I think the PR as is can go, but it would still be nice to check on the other periods and adjust accordingly if possible.

**Comment by abaty** [comment]
Hi Marco, Joosep,

From my side, I think it is best if we could focus our efforts in the HI tracking group on getting everything ready for Run 3 at the moment.  Checking the earlier eras will take a little time, so I would suggest we proceed forward with this PR for now and then revisit the other earlier, lower priority, eras at a later date.  Perhaps we could create an issue on github so that we do not forget in the future?

**Comment by jpata** [comment]
+reconstruction
- looper reco disabled for Run2_2018 and Run3
- reco differences expected and observed in HI workflows for tracks and everything downstream of tracks

**Comment by qliphy** [comment]
+1
to follow up with https://github.com/cms-sw/cmssw/issues/35758.

**Pull request merged**
