### PR TITLE
Hotline skim AlCaReco workflows

### PR DESCRIPTION
**Pull request by duanders**
-Adding new package Calibration/Hotline containing hotline skim code
-Adding two new AlCaRecos implementing the hotline skims
-Including the hotline skims in the AlCaRecoMatrix under StreamExpress
-Including the hotline skims in the RelVal RECOD step

See presentation here: https://indico.cern.ch/event/368342/contribution/5/material/slides/0.pdf

### CODE REVIEW

**Comment by davidlange6** [comment]
@duanders -did you mean to commit a plugin? (if not, why the BuildFile.xml?)

**Comment by duanders** [comment]
@davidlange6  Sorry, the BuildFile was included by mistake.  (a previous version of the skim code contained a new plugin.)  Fixed this.

**Comment by franzoni** [comment]
please test

**Comment by duanders** [comment]
The ALCARECOEventContent contained a 'drop *' command, which caused AlCa collections to be wrongly dropped.  I removed the 'drop *' from the hotline event content, which fixes it.  @davidlange6 @franzoni  can we re-test?

**Comment by diguida** [comment]
@cmsbuild please test

**Comment by diguida** [comment]
+1
* new package `Calibration/Hotline` containing hotline skim code
* new AlCaReco implementing the hotline skim: sequences are in the client code, and paths are  implemented in `Configuration/StandardSequences/python/AlCaRecoStreams_cff.py`;
* hotline skim is included in the AlCaRecoMatrix under `StreamExpress`;
* hotline skim is included in `dataReco` definition for data RelVals;
* re-shaping of the definition of AlCaReco EventContent, in order to avoid python circular dependencies.

**Comment by diguida** [comment]
to be implemented: AlCa prompt implementation for AlCa harvesting step.

**Comment by mmusich** [comment]
@diguida we will take care when merging the other changes (e.g. muon alignment producers)

**Comment by mmusich** [comment]
Reporting here analysis from Salvatore:
```
1. Test setup:
a. job run on Run1 HighMet2011A sample in RelVal (wf 4.28)
b. Input data tier: RAW-RECO
2. Output events and collections:
a. Output events: 10 [1]
b. Output collections: see [2] for the full list; they are in agreement with the FEVT event content definition as in [3]
3. Event size: see [4]. Biggest ones:
Branch Name | Average Uncompressed Size (Bytes/Event) | Average Compressed Size (Bytes/Event)
FEDRawDataCollection_rawDataCollector__reHLT. 401125 158183
SiStripClusteredmNewDetSetVector_siStripClusters__reRECO. 118813 65220.1
recoTrackExtras_generalTracks__reRECO. 44114.8 26372.6
CaloTowersSorted_towerMaker__reRECO. 65780 24862.2
recoHcalNoiseRBXs_hcalnoise__reRECO. 57250.4 24046.1
EcalRecHitsSorted_ecalRecHit_EcalRecHitsEB_reRECO. 31920.9 20155
recoPFClusters_particleFlowClusterPS__reRECO. 64398.3 19341.7
recoPFCandidates_particleFlow__reRECO. 91831.5 18728.4
SiPixelClusteredmNewDetSetVector_siPixelClusters__reRECO. 31339 16795.3
TrackingRecHitsOwned_generalTracks__reRECO. 98426.1 16293.2
recoTracks_generalTracks__reRECO. 35294.3 15940.6
recoGsfElectrons_uncleanedOnlyGsfElectrons__reRECO. 15930.3 15617.6
recoGsfElectrons_gedGsfElectrons__reRECO. 15255.5 14939.7
HBHERecHitsSorted_hbheprereco__reRECO. 29119.7 14430.7
HBHERecHitsSorted_hbhereco__reRECO. 29086.7 14398
4. Event rate. Looking at WBM, I see that these two runs correspond to about 10 hours of data taking:
https://cmswbm.web.cern.ch/cmswbm/cmsdb/servlet/RunSummary?RUN=165121&SUBMIT=Submit
https://cmswbm.web.cern.ch/cmswbm/cmsdb/servlet/RunSummary?RUN=172802&SUBMIT=Submit

[1] edmFileUtil 4.28_HighMet2011A+HighMet2011A+HLTDSKIM+RECODreHLT+HARVESTDreHLT+MINIAODDreHLT/Hotline.root -e
[2] edmDumpEventContent 4.28_HighMet2011A+HighMet2011A+HLTDSKIM+RECODreHLT+HARVESTDreHLT+MINIAODDreHLT/Hotline.root --forceColumns
[3] https://github.com/cms-sw/cmssw/blob/CMSSW_7_6_X/Calibration/Hotline/python/hotlineSkims_Output_cff.py
[4] edmEventSize 4.28_HighMet2011A+HighMet2011A+HLTDSKIM+RECODreHLT+HARVESTDreHLT+MINIAODDreHLT/Hotline.root -v
```
Findings on 75X IB relvals are in line with expectations.

**Pull request merged**
