### PR TITLE
 Remove option to run on single GEM pads; Simplify CSC trigger configuration

### PR DESCRIPTION
**Pull request by dildick**
#### PR description:

* First major part: The GEM-CSC trigger will use clusters in Run-3 (not single GEM pads) which will be sent to the ME1/1 optical trigger motherboards over 9.6 Gb/s optical fibers as explained in [DN-20-016](https://gitlab.cern.ch/tdr/notes/DN-20-016/-/blob/master/nodraft/DN-20-016_temp.pdf). This PR finally removes the option to run on single pads (which was the normal way since CMSSW_6_2_X_SLHC).
* Second major part of the pull request is a working version of https://github.com/cms-sw/cmssw/pull/31401, with the intent of making the CSC trigger configuration easier to understand. All psets for ALCT, CLCT, TMB, MPC and CCLUT are put in `python/params` rather than directly in `cscTriggerPrimitiveDigis_cfi`, reducing the main configuration to less than 100 lines. Thus `params/` contains
```
python/params/
* alctParams_cfi
* clctParams_cfi
* tmbParams_cfi
* auxiliaryParams_cfi
* cclutParams_cfi
* __init__.py
```
* `SLHC` was renamed to `Phase2` everwhere
* `alctClctOffset_` was made a constant, defined in CSCConstants.h
* `use_run3_patterns_` and `use_comparator_codes_` were merged into `runCCLUT_` (because we will not run the Run-3 patterns without CCLUT)

#### PR validation:

Code compiles. Rebase from #31460 which was stuck in failing `code-checks`.  Performance plots can be found in the #31460 conversation.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

FYI @tahuang1991

### CODE REVIEW

**Comment by dildick** [comment]
All commits squashed into a single commit.

@silviodonato Can you run the tests, please?

**Comment by silviodonato** [comment]
please test

**Comment by silviodonato** [comment]
abort

**Comment by silviodonato** [comment]
code-checks

**Comment by silviodonato** [comment]
please test

**Comment by dildick** [comment]
There was a merge conflict I had to resolve.

**Comment by dildick** [comment]
There are a few CSC related failures in  ```23434.999```, which is Phase-2 with pileup.

12 differences coming from type9, type7 and type5. I don't quite know what those mean.

Screen Shot 2020-09-30 at 3 50 06 PM

Screen Shot 2020-09-30 at 3 49 21 PM

Screen Shot 2020-09-30 at 3 49 24 PM

Screen Shot 2020-09-30 at 3 49 29 PM

**Comment by dildick** [comment]
If I understand correctly, the mapping is:
```
ME1/1 -> 1
ME1/2 -> 2
ME1/3 -> 3
ME1/a -> 4
ME2/1 -> 5
ME2/2 -> 6
ME3/1 -> 7
ME3/2 -> 8
ME4/1 -> 9
ME4/2 -> 10
```
So these plots concern the ALCTs in ME2/1, ME3/1 and ME4/1

**Comment by dildick** [comment]
Ah! I see that I changed the ALCT settings for those chambers to use Phase-2. In the past there were some problems in ME3/1 and ME4/1 as I recall, that were resolved in #30914. We do want to use the Phase-2 algorithms in those chambers (especially ghost cancellation and 0 pre-trigger deadtime, narrow mask maybe not as it might negatively affect displaced muon triggering), but I need to check if the efficiency and possibly the trigger rate. In the mean time, I'll revert the ALCT settings for those chambers so that the tests pass without changes. I was not expecting any changes in the tests.

**Comment by dildick** [comment]
On a side note, it would probably be a good idea to change type1 -> ME1/1,..., type9 -> ME4/2 in the CSC validation code.

**Comment by dildick** [comment]
@silviodonato Could you rerun the tests?

**Comment by qliphy** [comment]
please test

**Comment by dildick** [comment]
@qliphy Thanks. My last commits seemed to have correctly reverted the ALCT processors. In `23434.999` I do a difference in the GEM copad plots. 

Screen Shot 2020-10-08 at 9 21 11 AM
Screen Shot 2020-10-08 at 9 21 53 AM

**Comment by dildick** [comment]
@silviodonato There are no differences in the PU0 tests. I understand that the DIGI+PU50 simulation is done twice (once for the CMSSW_11_2_X and once for CMSSW_11_2_X+31631) and that the digitized hit collections may be different due to randomness in the pileup simulation. Is this correct?

**Comment by silviodonato** [comment]
> @silviodonato There are no differences in the PU0 tests. I understand that the DIGI+PU50 simulation is done twice (once for the CMSSW_11_2_X and once for CMSSW_11_2_X+31631) and that the digitized hit collections may be different due to randomness in the pileup simulation. Is this correct?

Yes, that is correct. However it sound a bit weird that we pass from 6 entries in the plot to 0 entry. Could you try to run the test locally on more events?

**Comment by silviodonato** [comment]
@rekovic could you have a look?

**Comment by dildick** [comment]
@silviodonato Indeed, it is weird. There are no reported changes in the digis or pads, so it's related to the copad processor.

**Comment by dildick** [comment]
Still looking into it. The last commit is to ensure that only clusters for a particular chamber are declusterized before making the coincidences. Don't think this actually solves the issue seen above.

**Comment by dildick** [comment]
I see 3 coincidence pads in the original branch that I do not see in the modified one in `Run 1, Event 4, LumiSection 1`, namely these. 
```
layer1: GEMPadDigi Pad = 84 bx = 0, layer2: GEMPadDigi Pad = 82 bx = 0
layer1: GEMPadDigi Pad = 84 bx = 0, layer2: GEMPadDigi Pad = 83 bx = 0
layer1: GEMPadDigi Pad = 85 bx = 0, layer2: GEMPadDigi Pad = 83 bx = 0
```

What I don't understand is that originally there were 20 coincidence pads, which was reduced to 17. However, only the difference shows up in the plot, namely the three coincides shown above.

**Comment by dildick** [comment]
There are more differences that pertain to out-of-time coincidences pads, in bx != 0

**Comment by silviodonato** [comment]
please test

**Comment by dildick** [comment]
@silviodonato In the CSCGEMMotherboards I run the GEM coincidence pad processing. I had moved it past a check on whether the ALCTs and CLCTs are empty. If both were empty, it would not process the clusters. I moved the call to the declusterizer up, so that always all clusters are processed.

A second commit loosens the deltapad from 2 to 4. We have seen that for low-pT muons and displaced muons this helps to maintain efficiency.

**Comment by dildick** [comment]
More troubling perhaps is the few number of entries in the histogram. For station 1 I count 11 coincidence pads with BX = 0
```
Re -1 Ri 1 St 1 La 1 Ch 26 Ro 8 Roll: 8 layer1: GEMPadDigi Pad = 141 bx = 0, layer2: GEMPadDigi Pad = 141 bx = 0
Re -1 Ri 1 St 1 La 1 Ch 26 Ro 8 Roll: 8 layer1: GEMPadDigi Pad = 141 bx = 0, layer2: GEMPadDigi Pad = 142 bx = 0
Re -1 Ri 1 St 1 La 1 Ch 26 Ro 8 Roll: 8 layer1: GEMPadDigi Pad = 141 bx = 0, layer2: GEMPadDigi Pad = 143 bx = 0
Re -1 Ri 1 St 1 La 1 Ch 26 Ro 8 Roll: 8 layer1: GEMPadDigi Pad = 142 bx = 0, layer2: GEMPadDigi Pad = 141 bx = 0
Re -1 Ri 1 St 1 La 1 Ch 26 Ro 8 Roll: 8 layer1: GEMPadDigi Pad = 142 bx = 0, layer2: GEMPadDigi Pad = 142 bx = 0
Re -1 Ri 1 St 1 La 1 Ch 26 Ro 8 Roll: 8 layer1: GEMPadDigi Pad = 142 bx = 0, layer2: GEMPadDigi Pad = 143 bx = 0
Re -1 Ri 1 St 1 La 1 Ch 29 Ro 1 Roll: 1 layer1: GEMPadDigi Pad = 125 bx = 0, layer2: GEMPadDigi Pad = 125 bx = 0
Re -1 Ri 1 St 1 La 1 Ch 29 Ro 1 Roll: 1 layer1: GEMPadDigi Pad = 125 bx = 0, layer2: GEMPadDigi Pad = 126 bx = 0
Re 1 Ri 1 St 1 La 1 Ch 33 Ro 4 Roll: 4 layer1: GEMPadDigi Pad = 84 bx = 0, layer2: GEMPadDigi Pad = 82 bx = 0
Re 1 Ri 1 St 1 La 1 Ch 33 Ro 4 Roll: 4 layer1: GEMPadDigi Pad = 84 bx = 0, layer2: GEMPadDigi Pad = 83 bx = 0
Re 1 Ri 1 St 1 La 1 Ch 33 Ro 4 Roll: 4 layer1: GEMPadDigi Pad = 85 bx = 0, layer2: GEMPadDigi Pad = 83 bx = 0
```
Why do only the last 3 show up in the plot? Something that needs to be addressed in different PR...

**Comment by silviodonato** [comment]
@dildick see #31863. Can it be related to your problem?
 
> GEM digi bx is wrong, it should be the relative difference between AMC and BFAT bx.

**Comment by dildick** [comment]
No, the unpacker does not affect validation plots with coincidence pad digis.

**Comment by silviodonato** [comment]
please test

**Comment by dildick** [comment]
@silviodonato This looks good to me now. There are a bit more coincidence pads now, but this is due to the fact that I loosened a window. I did this to increase acceptance for low pT muons and displaced muons.

**Comment by silviodonato** [comment]
@cms-sw/l1-l2 please review/sign

**Comment by silviodonato** [comment]
@cms-sw/l1-l2 please review/sign

**Comment by rekovic** [comment]
Hi @dildick 
The change is CSC configuration might lead to changes in the EMTF and EMTF++ performance.  Has this been checked?  How is EMTF affected, if affected at all. 

True that this PR is for 11_2_X, but we should remain consistent with 11_1_X where we are using EMTF for HLT TDR in 11_1_X. 

Attn: @jiafulow

**Comment by silviodonato** [comment]
ping @dildick

**Comment by dildick** [comment]
@silviodonato Yes, I need to check the effects on the EMTF.

**Comment by qliphy** [comment]
ping @dildick   Do you have any update on EMTF check?

**Comment by dildick** [comment]
@qliphy I don't see any difference in 0 pileup single muon relval sample (/RelValSingleMuFlatPt2To100/CMSSW_11_0_0-110X_mcRun4_realistic_v2_2026D49noPU-v1/GEN-SIM-DIGI-RAW).

**Comment by dildick** [comment]
@rekovic @qliphy @silviodonato 

A few performance plots (not for publication) on 1000 PU200 ecents from dataset /RelValSingleMuFlatPt2To100/CMSSW_11_0_0-PU25ns_110X_mcRun4_realistic_v3_2026D49PU200-v1/GEN-SIM-DIGI-RAW. 

First set of plots made with CMSSW_11_2_X_2020-11-23-1100

Eff_EMTF_pt_Pt20_
Eff_EMTF_eta_Pt20_
Eff_EMTF2_eta_Pt20_
Eff_EMTF_phi_Pt20_

Second set of plots made with CMSSW_11_2_X_2020-11-23-1100+PR31631

Eff_EMTF_pt_Pt20_
Eff_EMTF_eta_Pt20_
Eff_EMTF2_eta_Pt20_
Eff_EMTF_phi_Pt20_

**Comment by dildick** [comment]
I don't see a noticeable difference in the plots. The EMTF pT efficiency has the same shape (turn-on, plateau).

**Comment by qliphy** [comment]
ping @cms-sw/l1-l2

**Comment by rekovic** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
