### PR TITLE
Added new muon-tau-jet OvRm filter

### PR DESCRIPTION
**Pull request by jaimeleonh**
#### PR description:

Adding new muon-tau-jet overlap removal filter following the existing HLTDoubletSinglet filter template needed for a new monitoring HLT path.

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by missirol** [comment]
@jaimeleonh 

Is there an expected timeline for proposing this monitoring trigger for integration in the HLT menus (via JIRA)? If this is expected to happen within the next few weeks, a backport of this PR to 12_3_X might be needed.

**Comment by missirol** [comment]
In the current plan, V2 will be in 12_4_X, so then the backport does not seem strictly needed. On the other hand, this PR is very simple, and backporting it poses no problems, imho. I leave the decision to open a backport to you. If you decide to backport, this should be done well ahead of the deadline for 12_3_0 (which is April 8).

**Comment by missirol** [comment]
+hlt

 - addition of an HLT filter, not presently used in any wfs nor HLT menus
 - the "RelVals-INPUT" error must be unrelated to this PR (aside from compiling the source code, which works, the PR tests are not sensitive to this PR)
 - the tests could be restarted, of course, if that's considered useful

**Comment by perrotta** [comment]
+1

**Comment by perrotta** [comment]
merge

**Pull request merged**
