### PR TITLE
Made AlignmentMuonSelectorModule a stream module

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

This change is part of #25090

#### PR validation:

The code compiles.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
please test

**Comment by perrotta** [comment]
+1
- Technical
- Jenkins tests pass

**Comment by pohsun** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
