### PR TITLE
Adding Sherpa ttbar+2j GEN Relval workflow 536

### PR DESCRIPTION
**Pull request by SanghyunKo**
Adding Sherpa ttbar@NLO + 2 LO jets (MENLOPS) GEN Relval workflow as discussed in GEN meeting.

(Currently, only ZtoEE process is available for Sherpa Relval (workflow 534).)

### CODE REVIEW

**Comment by efeyazgan** [comment]
I thought we asked for a simpler process for the relval.

**Comment by efeyazgan** [comment]
Adding @GurpreetSinghChahal

**Comment by SanghyunKo** [comment]
Hi @efeyazgan, I reduced number of jets and the order of jets. Now event generation only takes ~0.7s/event, so I assumed that the process is simple enough for the relval. However, I can replace python fragment & sherpack for simpler and more generic one if you want.

**Comment by smuzaffar** [comment]
@SanghyunKo , we did a cleanup of some large data files which were merge in cmssw repo few days ago. Due to this cleanup this PR is now in a bad state (includes all the commits which we rewrite to avoid the large data files), Can you please rebase this PR based on new head?

**Comment by perrotta** [comment]
-1
(Not for reco, rebase needed)

**Comment by kpedro88** [comment]
FYI, how to rebase: http://cms-sw.github.io/tutorial-resolve-conflicts.html

**Comment by SanghyunKo** [comment]
Updated PR

(cherry-picked the commit & pushed to remote based on the new master head `4ba3075`)

**Comment by fabiocos** [comment]
please test workflow 536

**Comment by kpedro88** [comment]
+upgrade

**Comment by qliphy** [comment]
@SanghyunKo   You mentioned above that " Now event generation only takes ~0.7s/event".  How about this simpler Sherpack?    To me, it is fine to update with the simpler one.

**Comment by SanghyunKo** [comment]
@qliphy Thanks for the comment. The runtime per event is almost similar to the previous one since the order is same (ttbar 0j@NLO + 1&2j@LO). Then I'll push the commit when new Sherpack is ready at cvmfs.

**Comment by SanghyunKo** [comment]
Replaced the Sherpack with the simpler Run card.

(only generator fragment is changed from the view of this PR)

**Comment by qliphy** [comment]
please test workflow 536

**Comment by qliphy** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade

**Comment by SanghyunKo** [comment]
Hi @zhenhu, @prebello, could you please check this and sign?

**Comment by prebello** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
