### PR TITLE
inequality operators for cms types

### PR DESCRIPTION
**Pull request by hroskes**
Is there any reason not to implement <, <=, >, >= for int32 and similar?

I was very confused when I tried to do something like this:

```
myanalyzer = cms.EDAnalyzer("MyAnalyzer",
    myanalyzer.informationlevel = cms.int32(0),
)

#...

myanalyzer.informationlevel = max(myanalyzer.informationlevel, 3)

print myanalyzer.informationlevel  #prints cms.int32(0)
```

Because `__gt__` is not implemented, `max(cms.int32(0), 3)` returns `cms.int32(0)` because the class name comes later in the alphabet.

I don't see any way this could break anything, but please let me know if there's a particular reason it was left unimplemented.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
Please extend the unit tests at the bottom of this file to test the comparisons. This should also test strange things such as
```
cms.uint32(3) < cms.string("foo")
cms.uint32(6) < 7
7 < cms.unint32(6)
```

**Comment by hroskes** [comment]
@Dr15Jones I added some tests (is this what you had in mind?  I've never done this before).

Some of them fail.  The problem is that `x = cms.double("5")` is valid but `x.value() == "5"` rather than `5`.  Is that a mistake.

Actually this problem is unrelated to inequalities, `cms.double("5") == cms.double(5)` would also return false which is wrong.

**Comment by Dr15Jones** [comment]
please test

**Comment by hroskes** [comment]
@Dr15Jones it's going to fail because of the double("5") issue, see the last message

**Comment by Dr15Jones** [comment]
I'd say that the real problem is `cms.double("5")` should either raise an exception or convert itself to be identical to `cms.double(5)`. This is the first time I've seen that the code had a problem.

**Comment by Dr15Jones** [comment]
I hadn't originally appreciated that python allows comparison of any type to any other type
```
>>> 5 < "5"
True
>>> "5" < 5
False
```
So therefore comparing `cms.double` to `cms.string` is a legitimate thing in python.

**Comment by hroskes** [comment]
I think the easiest fix is to change [this line](https://github.com/cms-sw/cmssw/blob/defd715e6155c0df2b826764e96af29f310953f3/FWCore/ParameterSet/python/Types.py#L106) to:
```return tmp == value```
This would allow double(5) (even though 5 is an int) but not double("5")

Does this sound ok to you?

**Comment by Dr15Jones** [comment]
One concern I have with the implementation is 
```
   cms.double(5) <= 6
```
returns true, but 
```
6 > cms.double(5)
```
may return false (and in my test does) because python is comparing type int to type cms.double and is comparing type names.

I believe we'd get consistent behavior if when comparing unrelated types the code switched to the standard python method using `self` instead of comparing `self.value()`.

**Comment by hroskes** [comment]
Wait, really?  I get correct behavior in both cases.
```
Python 2.7.11 (default, Dec  2 2016, 17:22:14)
[GCC 5.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import FWCore.ParameterSet.Config as cms
>>> 4 < cms.double(5)
True
>>> cms.double(5) <= 6
True
>>> 6 > cms.double(5)
True
```

**Comment by Dr15Jones** [comment]
I did the comparison `6 > cms.double(5)` in a work area which did not have your changes. I assumed (quite possible incorrectly) that python would do type comparison when the first item was an `int` and call `cms.double.__<comparison name>__` when the first item was a `cms.double`.

**Comment by Dr15Jones** [comment]
Looking at `cms.int64` and `cms.uint64` (and the other integer versions) I see they enforce that the original python value was an integer. I suppose double should check to see if it was given a `int`, `long` or `float` value.

**Comment by hroskes** [comment]
I think it's the 4th paragraph [here](https://docs.python.org/2/reference/datamodel.html#object.__lt__), it flips the comparison if `int` doesn't directly support comparing to `cms.double`

> There are no swapped-argument versions of these methods (to be used when the left argument does not support the operation but the right argument does); rather, `__lt__()` and `__gt__()` are each other’s reflection, `__le__()` and `__ge__()` are each other’s reflection, and `__eq__()` and `__ne__()` are their own reflection.

**Comment by Dr15Jones** [comment]
please test

**Comment by hroskes** [comment]
Looks like there are some places that actually do use cms.double('0.5')...  What do you suggest?  Change them all or just edit `__init__` and `setValue` to convert the value to a float?

```
[hroskes@lxplus087 src]$ find . -type f -exec grep "cms.double *( *['"'"][^)]* *)' {} +
./Calibration/EcalAlCaRecoProducers/python/WZElectronSkims_cff.py:#                              max = cms.double("0.5")
./Calibration/EcalAlCaRecoProducers/python/WZElectronSkims53X_cff.py:                             max = cms.double("0.5")
./ElectroWeakAnalysis/Skimming/python/zMuMuMuonUserData.py:    alpha = cms.double("0.75"),
./ElectroWeakAnalysis/Skimming/python/zMuMuMuonUserData.py:    beta = cms.double("-0.75"),
./ElectroWeakAnalysis/Skimming/python/zMuMuMuonUserData.py:    ptThreshold = cms.double("1.5"),
./ElectroWeakAnalysis/Skimming/python/zMuMuMuonUserData.py:    etEcalThreshold = cms.double("0.2"),
./ElectroWeakAnalysis/Skimming/python/zMuMuMuonUserData.py:    etHcalThreshold = cms.double("0.5"),
./ElectroWeakAnalysis/Skimming/python/zMuMuMuonUserData.py:    dRVetoTrk = cms.double("0.015"),
./ElectroWeakAnalysis/Skimming/python/zMuMuMuonUserData.py:    dRTrk = cms.double("0.3"),
./ElectroWeakAnalysis/Skimming/python/zMuMuMuonUserData.py:    dREcal = cms.double("0.25"),
./ElectroWeakAnalysis/Skimming/python/zMuMuMuonUserData.py:    dRHcal = cms.double("0.25"),
./ElectroWeakAnalysis/Skimming/python/zMuMuMuonUserData.py:    alpha = cms.double("0.75"),
./ElectroWeakAnalysis/Skimming/python/zMuMuMuonUserData.py:    beta = cms.double("-0.75"),
./ElectroWeakAnalysis/Skimming/python/zMuMuMuonUserData.py:    ptThreshold = cms.double("1.5"),
./ElectroWeakAnalysis/Skimming/python/zMuMuMuonUserData.py:    etEcalThreshold = cms.double("0.2"),
./ElectroWeakAnalysis/Skimming/python/zMuMuMuonUserData.py:    etHcalThreshold = cms.double("0.5"),
./ElectroWeakAnalysis/Skimming/python/zMuMuMuonUserData.py:    dRVetoTrk = cms.double("0.015"),
./ElectroWeakAnalysis/Skimming/python/zMuMuMuonUserData.py:    dRTrk = cms.double("0.3"),
./ElectroWeakAnalysis/Skimming/python/zMuMuMuonUserData.py:    dREcal = cms.double("0.25"),
./ElectroWeakAnalysis/Skimming/python/zMuMuMuonUserData.py:    dRHcal = cms.double("0.25"),
./ElectroWeakAnalysis/Skimming/python/zMuMuMuonUserData.py:    alpha = cms.double("0.75"),
./ElectroWeakAnalysis/Skimming/python/zMuMuMuonUserData.py:    beta = cms.double("-0.75"),
./ElectroWeakAnalysis/Skimming/python/zMuMuMuonUserData.py:    alpha = cms.double("0.75"),
./ElectroWeakAnalysis/Skimming/python/zMuMuMuonUserData.py:    beta = cms.double("-0.75"),
./ElectroWeakAnalysis/ZMuMu/python/ZMuMuCategoriesNtuples_cff.py:        ptThreshold = cms.double("1.5"),
./ElectroWeakAnalysis/ZMuMu/python/ZMuMuCategoriesNtuples_cff.py:        etEcalThreshold = cms.double("0.2"),
./ElectroWeakAnalysis/ZMuMu/python/ZMuMuCategoriesNtuples_cff.py:        etHcalThreshold = cms.double("0.5"),
./ElectroWeakAnalysis/ZMuMu/python/ZMuMuCategoriesNtuples_cff.py:        deltaRVetoTrk = cms.double("0.015"),
./ElectroWeakAnalysis/ZMuMu/python/ZMuMuCategoriesNtuples_cff.py:        deltaRTrk = cms.double("0.3"),
./ElectroWeakAnalysis/ZMuMu/python/ZMuMuCategoriesNtuples_cff.py:        deltaREcal = cms.double("0.25"),
./ElectroWeakAnalysis/ZMuMu/python/ZMuMuCategoriesNtuples_cff.py:        deltaRHcal = cms.double("0.25"),
./ElectroWeakAnalysis/ZMuMu/python/ZMuMuCategoriesNtuples_cff.py:        alpha = cms.double("0."),
./ElectroWeakAnalysis/ZMuMu/python/ZMuMuCategoriesNtuples_cff.py:        beta = cms.double("-0.75"),
./ElectroWeakAnalysis/ZMuMu/python/ZMuMuCategoriesNtuples_cff.py:##         ptThreshold = cms.double("1.5"),
./ElectroWeakAnalysis/ZMuMu/python/ZMuMuCategoriesNtuples_cff.py:##         etEcalThreshold = cms.double("0.2"),
./ElectroWeakAnalysis/ZMuMu/python/ZMuMuCategoriesNtuples_cff.py:##         etHcalThreshold = cms.double("0.5"),
./ElectroWeakAnalysis/ZMuMu/python/ZMuMuCategoriesNtuples_cff.py:##         deltaRVetoTrk = cms.double("0.015"),
./ElectroWeakAnalysis/ZMuMu/python/ZMuMuCategoriesNtuples_cff.py:##         deltaRTrk = cms.double("0.3"),
./ElectroWeakAnalysis/ZMuMu/python/ZMuMuCategoriesNtuples_cff.py:##         deltaREcal = cms.double("0.25"),
./ElectroWeakAnalysis/ZMuMu/python/ZMuMuCategoriesNtuples_cff.py:##         deltaRHcal = cms.double("0.25"),
./ElectroWeakAnalysis/ZMuMu/python/ZMuMuCategoriesNtuples_cff.py:##         alpha = cms.double("0."),
./ElectroWeakAnalysis/ZMuMu/python/ZMuMuCategoriesNtuples_cff.py:##         beta = cms.double("-0.75"),
./ElectroWeakAnalysis/ZMuMu/test/zToMuMuAnalysis_ntuple.py:        ptThreshold = cms.double("1.5"),
./ElectroWeakAnalysis/ZMuMu/test/zToMuMuAnalysis_ntuple.py:        etEcalThreshold = cms.double("0.2"),
./ElectroWeakAnalysis/ZMuMu/test/zToMuMuAnalysis_ntuple.py:        etHcalThreshold = cms.double("0.5"),
./ElectroWeakAnalysis/ZMuMu/test/zToMuMuAnalysis_ntuple.py:        deltaRVetoTrk = cms.double("0.015"),
./ElectroWeakAnalysis/ZMuMu/test/zToMuMuAnalysis_ntuple.py:        deltaRTrk = cms.double("0.3"),
./ElectroWeakAnalysis/ZMuMu/test/zToMuMuAnalysis_ntuple.py:        deltaREcal = cms.double("0.25"),
./ElectroWeakAnalysis/ZMuMu/test/zToMuMuAnalysis_ntuple.py:        deltaRHcal = cms.double("0.25"),
./ElectroWeakAnalysis/ZMuMu/test/zToMuMuAnalysis_ntuple.py:        alpha = cms.double("0."),
./ElectroWeakAnalysis/ZMuMu/test/zToMuMuAnalysis_ntuple.py:        beta = cms.double("-0.75"),
./CondTools/SiPixel/test/SiPixelGenErrorDBObjectUploader_cfg.py:                                  Version = cms.double("3.0"),
./CondTools/SiPixel/test/SiPixelTemplateDBObjectUploader_cfg.py:                                  Version = cms.double("3.0"),
./CondTools/SiPixel/test/SiPixel2DTemplateDBObjectUploader_cfg.py:                                  Version = cms.double("17.0"),
./CondTools/SiPixel/test/SiPixelInclusiveBuilder_cfg.py:                                          Version = cms.double("3.0"),
./RecoEgamma/EgammaPhotonProducers/python/trajectoryCleanerBySharedHitsForConversions_cfi.py:TrajectoryCleanerBySharedHitsForConversions.fractionShared = cms.double('0.5')
```

(plus some more matches which are false positives)

```
./SimG4CMS/HcalTestBeam/test/python/run_tb06_all_cfg.py:  pfile.write('process.common_beam_parameters.MinE = cms.double('+listE[i]+') \n')
./SimG4CMS/HcalTestBeam/test/python/run_tb06_all_cfg.py:  pfile.write('process.common_beam_parameters.MaxE = cms.double('+listE[i]+') \n')
./SimG4CMS/HcalTestBeam/test/python/run_tb06_all_cfg.py:  pfile.write('process.testbeam.TestBeamAnalysis.EcalFactor = cms.double(' + ecal + ') \n')
./SimG4CMS/HcalTestBeam/test/python/run_tb06_all_cfg.py:  pfile.write('process.testbeam.TestBeamAnalysis.HcalFactor = cms.double(' + hcal + ') \n\n')
./Geometry/EcalTestBeam/test/ee/CaloGeometryLoaderTest.icc:                    <<"\n    MinEta = cms.double("<< strTetaZ <<"),"
./Geometry/EcalTestBeam/test/ee/CaloGeometryLoaderTest.icc:                    <<"\n    MaxEta = cms.double("<< strTetaZ <<"),"
./Geometry/EcalTestBeam/test/ee/CaloGeometryLoaderTest.icc:                    <<"\n    MinPhi = cms.double("<< strTphiZr <<"),"
./Geometry/EcalTestBeam/test/ee/CaloGeometryLoaderTest.icc:                    <<"\n    MaxPhi = cms.double("<< strTphiZr <<"),"
./Geometry/EcalTestBeam/test/ee/CaloGeometryLoaderTest.icc:                    <<"\n    Psi    = cms.double("<< strTpsir <<"),"
./Geometry/EcalTestBeam/test/ee/CaloGeometryLoaderTest.icc:                    <<"\n    BeamMeanX = cms.double("<< strTxpos <<"),"
./Geometry/EcalTestBeam/test/ee/CaloGeometryLoaderTest.icc:                    <<"\n    BeamMeanY = cms.double("<< strTypos <<"),"
./Geometry/EcalTestBeam/test/ee/CaloGeometryLoaderTest.icc:                    <<"\n    BeamPosition = cms.double("<< strTzpos <<")\n    )"
./Geometry/EcalTestBeam/test/write_crystal_cfg.pl:        print OUTFILE "    MinEta = cms.double(".$eta,"),\n";
./Geometry/EcalTestBeam/test/write_crystal_cfg.pl:        print OUTFILE "    MaxEta = cms.double(".$eta,"),\n";
./Geometry/EcalTestBeam/test/write_crystal_cfg.pl:        print OUTFILE "    MinPhi = cms.double(".$phi,"),\n";
./Geometry/EcalTestBeam/test/write_crystal_cfg.pl:        print OUTFILE "    MaxPhi = cms.double(".$phi,"),\n";
```

**Comment by Dr15Jones** [comment]
Given that the `cms.*int*` types do not support string values I am inclined to disallow them for `cms.double` as well.  Therefore I'm for changing them all. The difficult is finding them 'all' since it is also possible someone did the equivalent of
```
v = "5"
d = cms.double(v)
```

So how about you change the ones you found and then I'll use your pull request and do a full 'release validation' run to see if it catches anything else.

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
So far my test has found an additional file
```
File "/cvmfs/cms-ib.cern.ch/week1/slc6_amd64_gcc530/cms/cmssw-patch/CMSSW_9_0_X_2017-01-06-1100/python/DQM/Physics/ewkMuLumiMonitorDQM_cfi.py", line 13, in <module>
  ptThreshold = cms.untracked.double("0.0"), 
```
I'm guessing your search was on `cms.double` and not `cms.untracked.double`. If I search for `untracked.double(` I get the following files
```
DQM/Physics/python/ewkMuLumiMonitorDQM_cfi.py
ElectroWeakAnalysis/ZMuMu/python/ZMuMuCategoriesSequences_cff.py
ElectroWeakAnalysis/ZMuMu/python/zSelection_cfi.py
ElectroWeakAnalysis/ZMuMu/test/BTagAnalysis.py
ElectroWeakAnalysis/ZMuMu/test/ZMuMu_MCanalysis.py
ElectroWeakAnalysis/ZMuMu/test/ZMuMu_radiative_analysis.py
ElectroWeakAnalysis/ZMuMu/test/dimuonStatistics.py
ElectroWeakAnalysis/ZMuMu/test/old/zToMuMuAnalysis_IsoDeposit.py
ElectroWeakAnalysis/ZMuMu/test/zMuMuIsolationAnalysis.py
ElectroWeakAnalysis/ZMuMu/test/zToMuMuAnalysis.py
ElectroWeakAnalysis/ZMuMu/test/zToMuMuAnalysis_EtaRegions.py
ElectroWeakAnalysis/ZMuMu/test/zToMuMuAnalysis_ntuple.py
ElectroWeakAnalysis/ZMuMu/test/zToMuMuAnalysis_vtx.py
ElectroWeakAnalysis/ZMuMu/test/zToMuMuAnalysis_withGlbMuQualityCuts.py
```
Looks like those need to be changed as well.

FYI, the test I ran was 
```
nohup runTheMatrix.py -j 12 --command='--no_exec' > & matrix.log &
```
which creates a bunch of configuration files via importing configuration fragments. I was going to run `python` on each of the created configurations, but sometimes the creation of the configuration failed first with a python problem.

**Comment by Dr15Jones** [comment]
Here's another reason we do not want to keep the use of string as we do now,
```
>>> import FWCore.ParameterSet.Config as cms
>>> print cms.double("5").value()+cms.double("5").value()
55
>>> print cms.double(5).value()+cms.double(5).value()
10
```

**Comment by Dr15Jones** [comment]
The unit test and RelVal failures are both caused by `DQM/Physics/ewkMuLumiMonitorDQM_cfi.py`.

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
I tested all RelVal configurations generated by `runTheMatrix.py` and they all work now.

**Comment by Dr15Jones** [comment]
+1

**Comment by hroskes** [comment]
Thanks!

**Comment by Dr15Jones** [comment]
Thank you for making the change (and putting up with all the requested changes).

**Comment by dmitrijus** [comment]
+1

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/17117	885f5a4
- the only change in RECO category is in RecoEgamma/EgammaPhotonProducers/python/trajectoryCleanerBySharedHitsForConversions_cfi.py . Based on git grep, the TrajectoryCleanerBySharedHitsForConversions is not used
- jenkins tests pass and comparisons with baseline show no differences.

**Pull request merged**
