### PR TITLE
PPS: address comments

### PR DESCRIPTION
**Pull request by jan-kaspar**
#### PR description:

This mostly-technical PR aims to address two suggestions by @fabiocos.

  * https://github.com/cms-sw/cmssw/pull/28492#issuecomment-563180098: use random numbers from CLHEP and provide elementary reproducibility
  * https://github.com/cms-sw/cmssw/pull/25495#pullrequestreview-219923984: move
Validation/CTPPS/python/randomXiThetaGunProducer_cfi.py to Configuration/Generator

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by fabiocos** [comment]
@jan-kaspar thank you, did you verify this update with the validation configuration?

**Comment by jan-kaspar** [comment]
@fabiocos Yes. A test based on [this config](https://github.com/jan-kaspar/proton_simulation_validation/blob/master/templates/test_acceptance_cfg.py) (including the files from Validation/CTPPS/python/simu_config), made for the 2018 configuration, yields the following simulated x distributions in the 4 Roman Pots (columns):

x_dist_cmp

Blue: before this PR, red-dashed: with this PR. No change observed, as expected.

**Comment by fabiocos** [comment]
@christopheralanwest @tocheng @tlampen the update is mostly technical, could you please have a look?
@qliphy @agrohsje the update in your area is marginal

**Comment by pohsun** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Pull request merged**
