### PR TITLE
migrate Validation/RecoTrack to esConsumes

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

Part of #31061.
Migrated to esConsumes the following pakages
   * `Validation/RecoTrack `

#### PR validation:

It builds and passes `runTheMatrix.py -s` with:

```
37 33 28 23 14 4 1 1 1 tests passed, 0 0 0 0 0 0 0 0 0 failed
```

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Not a backport, no backport needed.

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by jfernan2** [comment]
+1

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by jfernan2** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
