### PR TITLE
HLT menu development for `12_4_X` (2/N)

### PR DESCRIPTION
**Pull request by missirol**
backport of #38241

#### PR description:

Development of HLT menus for `CMSSW_12_4_X`.

Includes the integration of the following JIRA tickets.

  - [CMSHLT-2273](https://its.cern.ch/jira/browse/CMSHLT-2273): [BPH] Double-electron triggers for R(X)-type analyses _(partly integrated)_
  - [CMSHLT-2281](https://its.cern.ch/jira/browse/CMSHLT-2281): [HIG] Update of DijetVBF+2Tau trigger
  - [CMSHLT-2282](https://its.cern.ch/jira/browse/CMSHLT-2282): [EXO] PFMETNoMu trigger with HF cleaning + low-pT double-photon triggers _(partly integrated)_
  - [CMSHLT-2284](https://its.cern.ch/jira/browse/CMSHLT-2284): [HIG] Backup and control triggers for 2Tau+Jet trigger
  - [CMSHLT-2285](https://its.cern.ch/jira/browse/CMSHLT-2285): [HIG] Control triggers for VBF+2Tau trigger
  - [CMSHLT-2289](https://its.cern.ch/jira/browse/CMSHLT-2289): [TAU] Update of VBF+2Tau triggers
  - [CMSHLT-2291](https://its.cern.ch/jira/browse/CMSHLT-2291): [B2G] SingleJet and DiJet Triggers on AK8 jets with softdrop-mass cut
  - [CMSHLT-2306](https://its.cern.ch/jira/browse/CMSHLT-2306): [TOP] Update of DeepJet WP for HT+6Jet+1BTag trigger
  - [CMSHLT-2308](https://its.cern.ch/jira/browse/CMSHLT-2308): [BPH] Update of triggers for Tau->3Mu search _(amended with respect to [#38108](https://github.com/cms-sw/cmssw/pull/38108))_
  - [CMSHLT-2314](https://its.cern.ch/jira/browse/CMSHLT-2314): [JME] Low-pT single-photon trigger for jet-energy corrections
  - [CMSHLT-2316](https://its.cern.ch/jira/browse/CMSHLT-2316): [TSG] run Pixel DQM (CPU-vs-GPU) inside the HLT
  - [CMSHLT-2321](https://its.cern.ch/jira/browse/CMSHLT-2321): [EXO] Backup and monitoring triggers for displaced-dimuon searches
  - [CMSHLT-2324](https://its.cern.ch/jira/browse/CMSHLT-2324): [TSG] Naming: changed `AlCaLumiPixelCounts` to `AlCaLumiPixelsCounts`
  - [CMSHLT-2325](https://its.cern.ch/jira/browse/CMSHLT-2325): [TRK,AlCa,TSG] Update of `DQMOnlineBeamspot` EventContent and FEDSelector for TCDS
  - [CMSHLT-2330](https://its.cern.ch/jira/browse/CMSHLT-2330): [TAU,HIG] Naming: changed "`DeepTauIso`" label to "`DeepTau`"
  - [CMSHLT-2333](https://its.cern.ch/jira/browse/CMSHLT-2333): [EGM,HIG] Naming: removed "`NoPixelVeto`" label from Diphoton Paths _(partly integrated)_

#### PR validation:

TSG tests.

#### If this PR is a backport, please specify the original PR and why you need to backport that PR:

#38241

Development of HLT menus for 2022 pp data-taking.

### CODE REVIEW

**Comment by missirol** [comment]
enable gpu

To better test the update of the DQM path, which only runs on GPU.

**Comment by missirol** [comment]
please test

**Comment by missirol** [comment]
please abort

**Comment by missirol** [comment]
hold

See https://github.com/cms-sw/cmssw/pull/38241#issuecomment-1146572241.

**Comment by tvami** [comment]
@cmsbuild , please test with https://github.com/cms-sw/cmssw/pull/38293

**Comment by missirol** [comment]
unhold

**Comment by missirol** [comment]
It seems that some of the tests are having trouble finishing.

@smuzaffar , what you would suggest to do in this case? Does one need to restart the tests from scratch?

**Comment by smuzaffar** [comment]
The pending test requires a HTCondor based GPU node. 4 hours ago, cmsbot has requested the allocation of such node but sometimes it can take more few hours to get this type of resource. I would suggest to wait few more hours

**Comment by missirol** [comment]
+hlt

 - differences in PR-tests outputs are in line with the updates to the GRun HLT menu
 - some differences are not fully understood (by me), namely diffs in `HLT/SiStrip` ; the same as written for the original PR in applies (suggesting that the effect is reproducible), see https://github.com/cms-sw/cmssw/pull/38241#issuecomment-1150473390;
 - this PR should be merged only after #38293 (but for the same IB, possibly)

**Pull request merged**
