### PR TITLE
DeepTau v2p5 in nanoAOD [12_4_X]

### PR DESCRIPTION
**Pull request by mbluj**
#### PR description:
This PR adds working point definitions for a newly integrated DeepTau v2p5. 
A corresponding study with details about WP threshold derivation and tau efficiency/mis-ID rate plots for both Run2 UL and Run 3 samples can be found [here](https://indico.cern.ch/event/1173018/contributions/4926652/attachments/2466518/4237200/wp_eff_final.pdf).

**This PR is a backport of #38726 to 12_4_X.**

In particular, the changes in this PR are (as in #38726):
* For nanoAOD: add a dedicated set of variables `_deepTauVars2018v2p5` to `taus_cff.py`,
* Unify WP masking interface to a single function `_tauIdWPMask()`;
* Option to compute WP flags from raw scores (`from_raw` argument in `_tauIdWPMask()`) given the threshold values, instead of reading them directly from MINIAOD;
* Change the format of storing WPs from bitmask to integer values for user-friendliness [see note in #38726]. 

Differences wrt #38726:
* WP thresholds values for DeepTau v2p5 are **not** used within runTauIdMVA.py and thus not added to miniAOD preserving its content (to fulfill no-changing policy for production releases);
* deepTau v2p5 WP flags stored in nanoAOD are computed from raw scores.

#### PR validation:

Original PR successfully tested with the "limited" set of matrix tests and a custom nanoAOD production. Matrix tests of this PR ongoing - we do not expect failures and will update this description when tests are finished.

#### If this PR is a backport please specify the original PR and why you need to backport that PR.

This PR is a backport of #38726 to 12_4_X, introduces deepTauID v2p5 to nanoAOD v10.

### CODE REVIEW

**Comment by mariadalfonso** [comment]
RUN3: 

V2.5 are correctly added
Screen Shot 2022-07-18 at 15 00 58

but the V2.1 get substantial changes
Screen Shot 2022-07-18 at 14 59 52

RUN2:
 
We should append the v2.5 also to the Run2 mini  with the modifier run2_nanoAOD_106Xv2
Screen Shot 2022-07-18 at 15 04 00

**Comment by mariadalfonso** [comment]
boosted taus: 
current ID variables changes as follow
Screen Shot 2022-07-18 at 15 10 10
Is this expected ?

**Comment by kandrosov** [comment]
@mariadalfonso Yes, it is expected because the way IDs are stored is changed from bitmask to WP numbering, as described in the PR description.
However, to avoid confusions, I propose that we move further discussion to the original PR thread https://github.com/cms-sw/cmssw/pull/38726 and once it is merged, will address this backport. Would you agree?

**Comment by mariadalfonso** [comment]
> @mariadalfonso Yes, it is expected because the way IDs are stored is changed from bitmask to WP numbering, as described in the PR description.
> However, to avoid confusions, I propose that we move further discussion to the original PR thread #38726 

You mean both the tau and boosted tau v2.1 quantities are expected to change ?
Then it's not anymore the same ID as in the past, so we cannot call anymore v2.1 (for tau) and  2017v2 (for boosted tau).

> and once it is merged, will address this backport. Would you agree?

technically are doing different things, one re-run the ID and one read from MINI, 
These comments apply to both (at the moment I do not have the Run3 plots with the master branch reading the mini).

**Comment by mariadalfonso** [comment]
> v2p1 (and other old ids) and their WPs are the same, but the way WPs are stored has changed.

yes I can see, but means that for run3: if someone do analysis from mini or nano  we get two different thing
 "3" can be medium or tight and this can only create confusion.

Can we push the change in bit-map for the Run3 mini as well  in a separate PRs ?
or post-pone this change for the very futures ?

**Comment by kandrosov** [comment]
> ok, good to know that there is a 3rd way to get the ID.

`tau.tauID("ID_NAME")`, e.g. `tau.tauID("byMediumDeepTau2017v2p1VSjet")`, is the only way to access tau IDs and their WPs at the MiniAOD level that is recommended and supported by the Tau POG. So, I don't expect any mini vs nano problems that could be triggered by the the proposed change.

> can we disantangle the two features in master: 1) one PR for bitmap of all the IDs and 2) add the new V2.5 ?
> Would be much easier to review

yes, it can be done. I'll prepare a PR with bitmap->numbering modification shortly.

**Comment by mbluj** [comment]
@mariadalfonso, @kandrosov, my two cents on differences in tauIDs other than newly added deepTau v2p5: It is indeed true that the main change is caused by a modified way of storing of WPs (bitset->numbers), but one should also expect some change caused by the different selection of taus stored in nanoAOD. The selection bases on the "big OR" of loosest WPs of all discriminants against jet->tau fakes and now it contains also deepTau v2p5 VVVL: https://github.com/cms-sw/cmssw/pull/38751/files#diff-d54676262d2e5326ee3455e57747fd476b12be16993a8eb0f4794e8771f6526fR18

**Comment by mbluj** [comment]
@mariadalfonso,  https://github.com/cms-sw/cmssw/pull/38751/commits/ece4723bcbfee47ac03d0b0de2bd4689f7da32b2 adds a customization function to add items missing in Run-2 UL samples needed by nano v10 (now only deepTau v2p5); it is a counterpart of https://github.com/cms-sw/cmssw/commit/dd403613f92ee9125087af6ca19ac47f30a71bdc described in https://github.com/cms-sw/cmssw/pull/38726#issuecomment-1193884405.

**Comment by mariadalfonso** [comment]
please test

**Comment by clacaputo** [comment]
type tau

**Comment by mbluj** [comment]
Commit https://github.com/cms-sw/cmssw/pull/38751/commits/969573d0a7ca70f0da312b2c16a268983a94ef45 adds DeepTauID v2p5 to nanoAOD when the `run2_nanoAOD_106Xv2` or `run3_nanoAOD_122` modifier is used (with an already existing function to add tauIDs),  and removes the `nanoAOD_customizeV10` customization function (as it is not needed longer). It is copy of a commit to master (https://github.com/cms-sw/cmssw/pull/38726#issuecomment-1201155745)

PR rebased on top of a newer 12_4_X IB.

**Comment by mariadalfonso** [comment]
please test

**Comment by mariadalfonso** [comment]
Seems that the mini+nano in one step fails 136.72412

Our test with persistent nano are ok
https://gitlab.cern.ch/cms-nanoAOD/nanoAOD-integration/-/issues/173

@mbluj can you have a look ?
Thanks

**Comment by mbluj** [comment]
> Seems that the mini+nano in one step fails 136.72412
> 
> Our test with persistent MINI are ok https://gitlab.cern.ch/cms-nanoAOD/nanoAOD-integration/-/issues/173
> 
> @mbluj can you have a look ? Thanks

Yes, I am on it. The problem is indeed due to the common (re)mini+nano workflow as at both steps deepTauID is added to taus. At mini it is default with 125X/124X, while at nano it is triggered by an era modifier. There are two problems with this setup: one is technical as modules with same names are crated, but different inputs are expected (modules are in different place in "production chain"), while other is "philosophical" as deepTauID is tried to be run twice. The first one can be solved with some effort by adding a suffix to module names, while the other is more difficult to avoid without an prior knowledge on combination of workflows, i.e. production levels (here mini & nano) and eras used.

**Comment by mariadalfonso** [comment]
please test

**Comment by mariadalfonso** [comment]
+xpog

the only difference with master is that also for Run3 we re-run all the times the new ID due to the no change policy of the mini already in production

**Comment by qliphy** [comment]
+1

**Pull request merged**
