### PR TITLE
Hcal DB Parameters Schema

### PR DESCRIPTION
**Pull request by ianna**
- Hcal parameters in DB implementation

### CODE REVIEW

**Comment by ianna** [comment]
@bsunanda - please, have a look. 

This schema stores both Sim and Reco parameters in one tag. One suggestion from my side is to store HcalTopologyMode as int and not as a string.

To produce the tag:
```
cmsRun CondTools/Geometry/test/calogeometrywriter.py
```

To use it, please, customise you cfg:
```
process.GlobalTag.toGet = cms.VPSet(cms.PSet(record = cms.string('PHcalParametersRcd'),
                                             tag = cms.string('HCAL_Parameters_Test01'),
                                             connect = cms.untracked.string("sqlite_file:./myfile.db")
                                             )
                                    )
```
and get the record from ES:
```
edm::ESHandle<PHcalParameters> php;
setup.get<PHcalParametersRcd>().get( php );
```
I'll write a few more tests shortly.

**Comment by ianna** [comment]
@mark-grimes - FYI.

**Comment by ianna** [comment]
@abdoulline - Please, have a look at the PR. It should be discussed with Hcal DPG. Along these lines - is there anything else to be configured for Hcal which can be stored in a DB tag?

**Comment by ianna** [comment]
+1

**Comment by davidlange6** [comment]
closing in 74x - there is the same PR open in 75x (now the development release)

**Pull request closed without merging**
