### PR TITLE
Better dependency checking on Paths

### LINKED ISSUE #43519: Case of circular dependence not caught by the checker
Here is a reproducer for a configuration that has a circular dependence cycle that leads the job to get stuck, but is missed by the circular dependence checker (for more history see https://github.com/cms-sw/cmssw/issues/43517)
```py
import FWCore.ParameterSet.Config as cms

process = cms.Process("TEST")
process.source = cms.Source("EmptySource")
process.maxEvents.input = 1

process.a = cms.EDProducer("IntProducer", ivalue = cms.int32(10))
process.b = cms.EDProducer("AddIntsProducer", labels = cms.VInputTag("c"))
process.c = process.b.clone(labels=["a"])
process.dependingFilter = cms.EDFilter("IntProductFilter", label=cms.InputTag("b"), threshold=cms.int32(1000))
process.rejectingFilter = cms.EDFilter("TestFilterModule", acceptValue = cms.untracked.int32(-1))

process.p1 = cms.Path(process.c)
process.p2 = cms.Path(process.b + process.dependingFilter + process.a)
process.p3 = cms.Path(process.rejectingFilter + process.a)
```
If the `p3` is commented out, the checker properly identifies the circular dependence and throws an exception
```
----- Begin Fatal Exception 07-Dec-2023 17:41:00 CET-----------------------
An exception of category 'ScheduleExecutionFailure' occurred while
   [0] Calling beginJob
Exception Message:
Unrunnable schedule
The Path/EndPath configuration could cause the job to deadlock
  module 'c' is on path 'p1' and depends on module 'a'
  module 'a' is on path 'p2' and follows module 'b' on the path
  module 'b' is on path 'p2' and depends on module 'c'
----- End Fatal Exception -------------------------------------------------
```

An attempt of the dependence graph
```mermaid
flowchart LR;
  subgraph p1
    c["c"];
  end
  subgraph p2
    direction LR
    b["b"];
    df{"dependingFilter"};
    p2a["a"];
    b ~~~ df ~~~ p2a;
    df --> b;
  end
  subgraph p3
    direction LR
    rf{"rejectingFilter"};
    p3a["a"];
    rf ~~~ p3a;
  end
  p1 ~~~ p2 ~~~ p3;
  b --> c;
  c --> p2a & p3a;

```

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

Now checks for direct and indirect dependent modules being later on a Path.

#### PR validation:

Code compiles and all framework unit tests (including the new one) pass.

fixes #43519

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
please test

**Comment by makortel** [comment]
+core

**Comment by rappoccio** [comment]
+1

**Pull request merged**
