### PR TITLE
Phase2-TB63 Rearrange the header file and make first example for dd4hep

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Rearrange the header file and make first example for dd4hep

#### PR validation:

Tested using examples in SimG4CMS/HGCalTestBeam/test

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@civanch @srimanob @perrotta @qliphy The conflict does not make sense. I tried to merge the PR with a new IB and it merges without any problem.

**Comment by civanch** [comment]
@bsunanda , git usually is right. Please, wait a bit and try to rebase.

**Comment by civanch** [comment]
@bsunanda , check with the today IB SimG4CMS/HGCalTestBeam/plugins/HGCPassive.h

**Comment by bsunanda** [comment]
Close this PR in favor of #34791

**Pull request closed without merging**
