### PR TITLE
Concurrent LuminosityBlock processing

### PR DESCRIPTION
**Pull request by Dr15Jones**
Can now specify how many LuminosityBlocks can be processed simultaneously by cmsRun.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by Dr15Jones** [comment]
I am in the process of running the full runTheMatrix.py suite using 4 threads per job. So far there have been no errors.

**Comment by Dr15Jones** [comment]
I do not necessarily believe that all standard modules will work properly if we use more than 1 LuminosityBlocks at the moment. The default is to run with only 1 LuminosityBlock so all present workflows should run just fine.
Once this pull request is in, I plan to do extensive testing of workflows with mulitple LuminosityBlocks to shake out any problems.

**Comment by fwyzard** [comment]
Hi Chris,
one thing that will likely break processing multiple lumisections, and is not post of the matrix tests yet, is the streaming of the DQM plots from the HLT nodes to online DQM.
I cannot say without trying how bad the breakage is going to be: it is possible that things will Just Work most of the time, with somewhat off results; or it may lead to memory corruptions.
Unfortunately I cannot think of any solutions yet.

I do not know whether the standard lumi-based DQM plots will also be affected.

**Comment by Dr15Jones** [comment]
@slava77 in the comparison check results, how can I find exactly what 'failed'?

**Comment by mommsen** [comment]
+1
Changes in  EventFilter::Utilities::FRDStreamSource are trivial.

**Comment by slava77** [comment]
On 1/25/18 6:45 AM, Chris Jones wrote:
> @slava77 <https://github.com/slava77> in the comparison check results,
> how can I find exactly what 'failed'?
> 



"""
Reco comparison results: 4 differences found in the comparisons
"""
is made for what shows up in validateJR in comparisons

details of the QA are available in that directory in 	logRootQA.log

In this case for validateJR search for "JR results" in that file:
JR results differ 4 all_OldVSNew_TTbar13TeVPU2017wf10224p0
the last word in the line above is the name of the directory.
Go there and look for png files.

In this case you will find logErrorHrvester has differences.
Most likely this is transient: xrootd issues a different set of messages
when loading the files and this difference is picked up in comparisons.

**Comment by Dr15Jones** [comment]
@fwyzard thanks for the heads up.

**Comment by Dr15Jones** [comment]
@fwyzard is it specifically the DQMMonitoringService you are concerned about?
https://github.com/cms-sw/cmssw/blob/master/DQMServices/StreamerIO/plugins/DQMMonitoringService.cc

**Comment by fwyzard** [comment]
@Dr15Jones , what I have in mind is the mode of operation of the `DQMFileSaver` used by the HLT, where the histograms are saved and reset after each lumisection.

My guess is that the present approach will not work as originally intended once multiple lumisections can be open at the same time.
Of course, I will have to actually try it and see what happens.

**Comment by fwyzard** [comment]
More in general, some DQM modules create a new copy of their histograms every (or every N) lumisection(s); again, I don't know if they will work as intended once we have multiple concurrent lumisections.

**Comment by perrotta** [comment]
+1
- Reco is touched with some cleaning of  ```EventFilter/Utilities/test/analyzerGNs_cfg.py```
- Test in ```EventFilter/Utilities/test```  runs without crashing

**Comment by Dr15Jones** [comment]
@civanch @mdhildreth please sign for simulation

**Comment by civanch** [comment]
+1

**Comment by fwyzard** [comment]
Can I ask that downstream code (HLT DQM and possibly FastTimerService) be
fixed *before* this is integrated ?

**Comment by Dr15Jones** [comment]
@fwyzard The default is to run with 1 and only 1 LuminosityBlock. It must be explicitly turned on to be used and that will not be done in a production system until we've fully tested all our workflows, including HLT DQM with it.

I would really like to get this integrated since it is a huge pain to do rebasing on as other things evolve.

**Comment by Dr15Jones** [comment]
@fwyzard Can you post a way I can test the HLT DQM with this pull request enabled but with the default of 1 LuminosityBlock?

**Comment by fwyzard** [comment]
I'm fine leaving the decision to Fabio.

**Comment by Dr15Jones** [comment]
@fwyzard a quick look at FastTimerService seems to indicate it is fully concurrent LuminosityBlock ready. 

The class does have a per concurrent LuminosityBlock slot for each of the lumi resources it uses. It also uses ConcurrentMonitorElements to fill the histograms which are filled for each LuminosityBlock. The histograms themselves are booked in begin Run and this pull request does not add the ability to have more than 1 Run. Therefore booking is unaffected.

**Comment by fwyzard** [comment]
Hi Chris,
thanks for checking - glad I future-proofed the FTS enough for concurrent
lumis.

I will try to provide an online-like HLT configuration once I'm back in
track of a laptop.

.A

**Comment by fwyzard** [comment]
Hi @Dr15Jones,
the latest online-like HLT configuration I have at hand is for 10.0.0-pre3, running over Run2017F data: https://fwyzard.web.cern.ch/fwyzard/20180127/hlt_1000pre3.py .

@Martin-Grunewald , @silviodonato , if it doesn't work with 10.0.0 final, can you provide a more up-to-date one ?

**Comment by Dr15Jones** [comment]
@fwyzard @Martin-Grunewald @silviodonato I tried running the configuration from Andrea in CMSSW_10_0_0 and it fails with
```
----- Begin Fatal Exception 27-Jan-2018 11:30:38 CST-----------------------
An exception of category 'Configuration' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing module: class=PFRecHitProducer label='hltParticleFlowRecHitHF'
Exception Message:
ValueError type of depth is expected to be vector<int> but declared as int32
----- End Fatal Exception -------------------------------------------------
```

**Comment by Dr15Jones** [comment]
After hacking the configuration so it would actually initialize all the modules, I get the error
```
----- Begin Fatal Exception 27-Jan-2018 13:11:17 CST-----------------------
An exception of category 'NoRecord' occurred while
   [0] Processing  stream begin Run run: 306121 stream: 3
   [1] Calling method for module HBHEPhase1Reconstructor/'hltHbhePhase1RecoM2RegForMuonsNoVtx'
Exception Message:
No "HcalTimeSlewRecord" record found in the EventSetup.n
 Please add an ESSource or ESProducer that delivers such a record.
----- End Fatal Exception -------------------------------------------------
```

**Comment by Martin-Grunewald** [comment]
Please add:
```
process.load('CalibCalorimetry.HcalPlugins.HcalTimeSlew_cff')
```

**Comment by Dr15Jones** [comment]
@Martin-Grunewald thanks

**Comment by Dr15Jones** [comment]
I ran the hacked configuration on both regular CMSSW_10_0_0 and a CMSSW_10_0_0 with this pull request (using the default 1 concurrent LuminosityBlock). They both ran just fine.

**Comment by Dr15Jones** [comment]
@fwyzard I ran the hacked configuraition setting the system to allow 2 concurrent LuminosityBlocks. After making a trivial fix to PoolSource (which I plan on making in a follow up pull request rather than in this one) the job ran just fine. I watched the job using `top` and during the LuminosityBlock transitions, the job was able to keep the CPU utilization at greater than 80%.

**Comment by fwyzard** [comment]
Hi @Dr15Jones, thanks for checking.
I'm actually more worried that the monitoring information coming form the HLT DQM may be wrong.
I will try to validate that in the coming days.

**Comment by Dr15Jones** [comment]
@fabiocos how do you want to handle integrating this?

**Comment by fwyzard** [comment]
hi @Dr15Jones, @fabiocos, 
I've tested an online-like HLT configuration with vanilla CMSSW_10_1_X_2018-01-27-1100, and with #21949 (this PR) and #22007 (Only used index 0 for Run and Lumi) on top: as far as I can see the HLT results, monitoring information, and DQM plots are unchanged.

The next step would be to test what happens with actual concurrent lumisections.
Can it be enabled already with these PRs, or are there further changes needed ?

**Comment by fwyzard** [comment]
By thw way, an online-like HLT configuration compatible with CMSSW_10_1_X_2018-01-27-1100 is at https://fwyzard.web.cern.ch/fwyzard/20180127/hlt_101x_v8.py , and one compatible with the latest IB at https://fwyzard.web.cern.ch/fwyzard/20180127/hlt_101x_v9.py .

**Comment by Dr15Jones** [comment]
@fwyzard you also need #22007

**Comment by Dr15Jones** [comment]
@fabiocos please consider this for merging.

   - @fwzard has demonstrated (more conclusively than my earlier test) that the HLT works fine when using the default of 1 concurrent luminosity block. Even if he sees a problem using multiple concurrent luminosity blocks, any futher changes can be done in a later pull request (or the HLT could just run with the default settings.)
   - all tests for this pull request have passed
   - I personally ran then entire runTheMatrix suite which worked fine 
   - this pull request is fully signed

I am concerned that the longer we wait to merge the more likely a conflict may occur. Having rebased this code twice, I can say that it was an absolutely miserable experience and I do not wish to have to do it a third time.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
