### PR TITLE
fix needed for psu TkMap

### PR DESCRIPTION
**Pull request by fioriNTU**
fix needed for psu TkMap

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by deguio** [comment]
+1
not sure why the DQM signature is needed. anyway +1 for me.

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/10257	 3ae6d7d
- changes in the code do not affect  reco use cases (TrackerMap is used in calibration and DQM). Code changes are OK.
- jenkins tests pass and comparisons with the baseline show no difference

**Comment by davidlange6** [comment]
+1

**Pull request merged**
