### PR TITLE
Use python3 to generate geometry

### PR DESCRIPTION
**Pull request by iarspider**
#### PR description:

Possible fix for #34552. Similar to #34474.

### CODE REVIEW

**Comment by srimanob** [comment]
Please test

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by iarspider** [comment]
test parameters:
pull_request = cms-sw/cmsdist#7142

**Comment by iarspider** [comment]
@cmsbuild please test

**Comment by iarspider** [comment]
Closing in favor of #34554

**Pull request closed without merging**
