### PR TITLE
Include the updated header from Geometry/Records instead of the obsolete one

### PR DESCRIPTION
**Pull request by perrotta**
#### PR description:

The header file Geometry/CaloEventSetup/interface/CaloTopologyRecord.h was since ages simply pointing to the correct Geometry/Records/interface/CaloTopologyRecord.h, as it reads

```C++
#ifndef Geometry_CaloEventSetyp_CaloTopologyRecord
#define Geometry_CaloEventSetyp_CaloTopologyRecord

//moved so just forward the new one under the old name

#include "Geometry/Records/interface/CaloTopologyRecord.h"

#endif
```

This PR replaces all remaining occurrencies of "Geometry/CaloEventSetup/interface/CaloTopologyRecord.h" with "Geometry/Records/interface/CaloTopologyRecord.h" in CMSSW, and remove the obsolete header.

As such it is purely technical, and does nothing but simplifying the dependencies and cleaning the release from obsolete material: if  @cms-sw/geometry-l2 agrees with the move, I think this can be safely merged. 

**PS**: I hoped I could have avoided applyng the code-format to the code RecoJets/JetAnalyzers/test/myJetAna.cc in the test area, but unfortunately it was not the case... With the [second commit](https://github.com/cms-sw/cmssw/pull/33784/commits/41a3eda06ace4fba92e9cafa6fcc5c3db3260fba) of this PR we add thousands of useless code format related updates to that test code. At least, they do not look harmful.

#### PR validation:

It builds, and the short matrix runs

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by Martin-Grunewald** [comment]
+1

**Comment by chayanit** [comment]
+1

**Comment by perrotta** [comment]
+1
- Technical
- Jenkins tests pass

**Comment by perrotta** [comment]
@cms-sw/alca-l2 @cms-sw/analysis-l2 @cms-sw/fastsim-l2 : could you please have a look and sign, if you agree with it?

**Comment by civanch** [comment]
+1

**Comment by yuanchao** [comment]
+1

* replace and remove the obsolete header (technical)
* matrix tests and unit tests passed

**Comment by qliphy** [comment]
+1

**Comment by qliphy** [comment]
merge

**Comment by santocch** [comment]
+1

**Pull request merged**
