### PR TITLE
Fix issue with BTV HLT OfflineDQM

### PR DESCRIPTION
**Pull request by marco-link**
#### PR description:
resolve issue (#38626) with BTV HLT OfflineDQM on Run3 data

#### PR validation:

`runTheMatrix.py -l limited -i all`

### CODE REVIEW

**Comment by perrotta** [comment]
@marco-link please prepare the backports for 12_3_X and 12_4_X: the fix (patch...) being conceptually simple, it could be even merged simultaneously in master and in the production and data-taking releases

**Comment by tvami** [comment]
type bugfix,btv

**Comment by tvami** [comment]
urgent

**Comment by emanueleusai** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
