### PR TITLE
Add AlCaReco producers in phase-2 workflows

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

The goal of this PR is to start exercising Tracker alcareco producers in the phase-2 workflows, as there is interest in trying a preliminary alignment with the phase-2 geometry.
A minimal set of changes if proposed in order to achieve that goal, including the necessary update of the `phase2_realistic` autoCond key in order to get most updated trigger bits from the run-3 global tag (see also [cmsTalk](https://cms-talk.web.cern.ch/t/outdated-alcarecotriggerbitsrcd-payload-in-the-phase-2-simulation-global-tag/16749)):
   * Global Tag difference: https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/125X_mcRun4_realistic_v2/125X_mcRun4_realistic_v3

In addition the pseudo-rapidity range of the alignment alcarecos is modified in the case of the phase-2 tracker to allow full coverage (up to |η|<4).

#### PR validation:

Run successfully `runTheMatrix.py -l 20834.0 -t 4 -j 8`

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

N/A

cc:
@consuegs

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by malbouis** [comment]
+alca

- I already leave the alca signature but I have no problem signing again in case the tests are re-triggered due to changes :-) 
- Changes are inline with the description 
- the tests results came back fine, only message logger failures

**Comment by mmusich** [comment]
@malbouis 

> Would you please replace the Candidate Gt with this versioned one?

done in the last push.

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by francescobrivio** [comment]
+alca

 - re-signing
 - @mmusich would you mind adding to the PR description the GT diff:
 https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/125X_mcRun4_realistic_v2/125X_mcRun4_realistic_v3
 Thank you!

**Comment by mandrenguyen** [comment]
+1

**Comment by srimanob** [comment]
To clarify, the PR proposes to run ALCA step by default in all Phase-2 workflows. What is the cost, i.e. in terms of RelVals disk when we run full set of relvals, both NoPU and PU200?

I see we currently do the same for Run-3 also.

**Comment by mmusich** [comment]
>  PU200?

is not run.

**Comment by srimanob** [comment]
Ah, OK. The Alca step is not in 
https://github.com/cms-sw/cmssw/blob/638de995737feb5fb11fbfcc486290853b0aa363/Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py#L2162

**Comment by mmusich** [comment]
@cms-sw/pdmv-l2 please have a look and if you agree sign.
Thank you.

**Comment by kskovpen** [comment]
+pdmv

**Comment by perrotta** [comment]
+1

**Pull request merged**
