### PR TITLE
CTPPS pixel clusters with db

### PR DESCRIPTION
**Pull request by fabferro**
CTPPS pixel clusterizer (input digis, output clusters)
New subpackage: RecoCTPPS/CTPPSPixelLocal.
Pixel ADC calibration called within the clusterization. CTPPSPixelGainCalibration record and tools added.
Mapping and dead/noisy channel mask to be loaded in the DB to have the raw2digi running properly.
Also contributors: @malbouis @clemencia @nogima

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by perrotta** [comment]
It needs a proper DB (GT) from which to read...

**Comment by Martin-Grunewald** [comment]
please test

**Comment by perrotta** [comment]
It still needs a proper DB (GT) from which to read...
Tests will keep failing until this is not provided

**Comment by slava77** [comment]
@fabferro 
please clarify on the status of the GT update.
I expect that this PR should eventually include the autoCond.py update commit or that update will need to be in the IB first.

@franzoni @arunhep

**Comment by franzoni** [comment]
hello @slava77 
just spoke to @fabferro

one of the three condformats needed for the consumption by the CPPS pixel reco
is part of this PR itself.
In order to update the autocond GT's to cater for the consumption of the three records,
we need the third condformats to be in a release.

Proposal agreed with @fabferro:
+ split this PR into one which only adds the necessary condformat
+ once a release (note: alas for this an IB is not sufficient) will be available to register also the third condformat => load to offline db the 3 condition payloads
+ AlCa/Db will make updated global tags and release update of autocond
+ the other "half" of this PR which consumes the 3  calibrations will be placed

**Comment by fabferro** [comment]
OK, we'll split it in 2 PR's starting with CondFormats, CondCore and CondTools packages.
The Clusterizer will come just after.

**Pull request closed without merging**
