### PR TITLE
MTD reconstruction: set fixed precision for floating point printed in unit test

### PR DESCRIPTION
**Pull request by fabiocos**
#### PR description:

Fix rounding in printout used in unit test of ```RecoMTD/DetLayers```, as the precision is creating issues with alternative architectures (PPC and arm).

#### PR validation:

Code runs, rounding at 4 decimal digits allows check of positions at micron level.  To be verified on alternative architectures.

### CODE REVIEW

**Comment by fabiocos** [comment]
please test with https://github.com/cms-data/Geometry-TestReference/pull/9

initial test with default architecture

**Comment by fabiocos** [comment]
the tests in https://github.com/cms-data/Geometry-TestReference/pull/9 show this rounding protects the unit test on other architectures, namely ```slc7_ppc64le_gcc9``` and ```slc7_aarch64_gcc9```

**Comment by mrodozov** [comment]
+externals

**Comment by perrotta** [comment]
+1
- It fixes a failure of the RecoMTDDetLayersTestDriver test, which started failing for both PPC and Arm after it was added in #33598
- Tested also in cms-data/Geometry-TestReference#9 in several architectures, see https://github.com/cms-sw/cmssw/pull/33762#issuecomment-843817843
- Jenkins tests pass, with no differences in the standard workflows, as expected because only some different rounding in the printouts was added

**Comment by srimanob** [comment]
+Upgrade

**Comment by silviodonato** [comment]
+1

**Pull request merged**
