### PR TITLE
[14_0_X] Introduce Unified Particle Transformer AK4 jet tagger (Backport) 

### PR DESCRIPTION
**Pull request by AlexDeMoor**
#### PR description:

This PR introduce UnifiedParticleTransformerAK4 a novel inclusive tagger for jet. This network will perform an inclusive tagging combining b/c/tau/lep tagging with jet energy regression (both the regression and the resolution estimation via quantile regression). The model is trained with a specific robust training combining improved adversarial training and domain adaptation for reducing the impact of the data/MC disagreement on the final performance. The output nodes of the domains are also kept for exploring the possibility of efficiency mapping and their impact later.

An overview of the method can be seen at: https://indico.cern.ch/event/1368069/contributions/5793148/
A focus on the novel adversarial training is described here: https://indico.cern.ch/event/1372038/#3-adversarial-training-for-par
The preliminary results of the model were shown in the following meeting: https://indico.cern.ch/event/1397392/#17-preliminary-results-of-part
The final results will be shared this Monday: https://indico.cern.ch/event/1403350/#3-part-2024-final-results-and

This PR requires the associated ONNX model which has been submitted in the adequate RecoBTag-Combined repo: https://github.com/cms-data/RecoBTag-Combined/pull/57

For your information: a last training is ongoing trying to improve the current performance via an enriched dataset. A modification of the final model could occur. This will only affect the RecoBTag-Combined PR, not this one.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Yes this is the backport of https://github.com/cms-sw/cmssw/pull/44641

### CODE REVIEW

**Comment by hqucms** [comment]
enable nano

**Comment by hqucms** [comment]
test parameters:
- pull_requests = https://github.com/cms-data/RecoBTag-Combined/pull/57

**Comment by jfernan2** [comment]
backport of https://github.com/cms-sw/cmssw/pull/44641

**Comment by hqucms** [comment]
please abort

**Comment by hqucms** [comment]
please test with https://github.com/cms-sw/cmssw/pull/44627

**Comment by hqucms** [comment]
please test

**Comment by hqucms** [comment]
+1

**Comment by hqucms** [comment]
please test

**Comment by mandrenguyen** [comment]
type btv, jetmet, tau

**Comment by mandrenguyen** [comment]
+reconstruction

**Comment by hqucms** [comment]
@cms-sw/orp-l2 I opened the cms-dist PR https://github.com/cms-sw/cmsdist/pull/9148, which should be merged together.

**Comment by rappoccio** [comment]
+1

**Pull request merged**
