### PR TITLE
[14_0_X] Hack `EgammaHLTR9IDProducer` to be able to run it in Phase2 HLT

### PR DESCRIPTION
**Pull request by swagata87**
Backport of https://github.com/cms-sw/cmssw/pull/44358

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by rappoccio** [comment]
+1

**Pull request merged**
