### PR TITLE
Phase2-hgx337 The first entry of the V18 version of HGCal geometry

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

The first entry of the V18 version of HGCal geometry

#### PR validation:

Use the script in Validation/HGCalValidation/scripts 

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by bsunanda** [comment]
@srimanob Please approve this PR

**Comment by emanueleusai** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

No change is expected from this PR. It introduces the new coming V18 HGCal.

**Comment by rappoccio** [comment]
+1

**Pull request merged**
