### PR TITLE
Cleanup of CTPPS sequences

### PR DESCRIPTION
**Pull request by fioriNTU**
#### PR description:

This PR is part of the DQM sequence cleanup effort. It move an Harvesting module to step 2, originally it was included in a step 1,  

#### PR validation:

Used runTheMatrix with 10024 workflow, and validated the Online client manually on top of the latest available 11_0_X IB.

### CODE REVIEW

**Comment by fioriNTU** [comment]
@fabferro @forthommel FYI

**Comment by fioriNTU** [comment]
please test

**Comment by jan-kaspar** [comment]
Thanks @fioriNTU , it looks good to me!

**Comment by fioriNTU** [comment]
+1
comparison looks as expected, no plots added or deleted

**Comment by fabiocos** [comment]
+1

**Pull request merged**
