### PR TITLE
Removed obsolete code from SIM

### PR DESCRIPTION
**Pull request by civanch**
#### PR description:
In this PR obsolete or unused code is removed. These lines were kept for a long time in order do not break simulations histories, because in these lines random numbers are used. As a result, simulation histories will be changed and some differences will be seen in regression.

#### PR validation:
private

#### if this PR is a backport please specify the original PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
@bsunanda , this PR interferes with your #27743 but the overlap is small and you indeed need to updated #27743.

**Comment by civanch** [comment]
+1

**Comment by kpedro88** [comment]
+1
real change in muon hits can be seen in 2026 workflow
statistical fluctuations from changes in random number usage show up in Run1/Run2 simulation workflows (not Phase2 because Castor is not present in Phase2)

**Pull request merged**
