### PR TITLE
Run3-hcx342 Try to fix the issue of HCAL hit relabeller

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Try to fix the issue of HCAL hit relabeler. This is a bug fix

#### PR validation:

Use the new test code in Geometry/HcalCommonData/test and its test script in .../test/python directories

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Need the bug fix to be back ported to CMSSW_13_1_X and CMSSW_13_0_X

### CODE REVIEW

**Comment by abdoulline** [comment]
@bsunanda  Thanks!

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
Type Bug Fix

**Comment by malbouis** [comment]
type bug-fix

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
+geometry

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
+geometry

**Comment by rappoccio** [comment]
+1

**Pull request merged**
