### PR TITLE
Quick fix - o2o bmtf

### PR DESCRIPTION
**Pull request by panoskatsoulis**
This is a Quick Fix for the BMTF o2o issue,
the data/emulator mismatches.

### CODE REVIEW

**Comment by thomreis** [comment]
please test

**Comment by thomreis** [comment]
@panoskatsoulis please make also a PR to the master branch for this.

**Comment by panoskatsoulis** [comment]
Just did the PR to the master.

**Comment by thomreis** [comment]
backport of #22670

**Comment by thomreis** [comment]
Hi @rekovic 
can you try with this PR if the record is produced as it should be?

**Comment by thomreis** [comment]
Hi @panoskatsoulis @rekovic 
is this PR still needed? I think the code is also included in PR #22709 .

**Comment by panoskatsoulis** [comment]
Hello,
Closed

**Pull request closed without merging**
