### PR TITLE
[DD4hep] Automated Comparison of TrackerParameters DD vs DD4hep

### PR DESCRIPTION
**Pull request by ianna**
#### PR description:

* Automated comparison for `TrackerParameters` produced with `DD4hep` vs `DD`
* Faster retrieval of the parameters from a map

When a namespace is not required:
```c++
auto const& vec = cpv->getVector<int>("detIdShifts");
```
It gives an identical result as the following, but using a namespace:
```c++
auto const& v = cpv->detector()->vectors().at("trackerParameters:detIdShifts");
std::vector<int> subdetPars;
std::transform(v.begin(), v.end(), std::back_inserter(subdetPars), [](int i) -> int { return std::round(i); });
```

TrackerParameters producer DD4hep vs DD:
```
TimeModule> 1 1 test TrackerParametersAnalyzer 1.94412
TimeModule> 1 1 p1 PathStatusInserter 5.19753e-05
TimeModule> 1 1 TriggerResults TriggerResultInserter 1.97887e-05
TimeEvent> 1 1 1.94451
MemoryReport> Peak virtual size 806.32 Mbytes
 Key events increasing vsize: 
[0] run: 0 lumi: 0 event: 0  vsize = 0 deltaVsize = 0 rss = 0 delta = 0
[0] run: 0 lumi: 0 event: 0  vsize = 0 deltaVsize = 0 rss = 0 delta = 0
[1] run: 1 lumi: 1 event: 1  vsize = 806.32 deltaVsize = 0 rss = 285.715 delta = 0
[0] run: 0 lumi: 0 event: 0  vsize = 0 deltaVsize = 0 rss = 0 delta = 0
[0] run: 0 lumi: 0 event: 0  vsize = 0 deltaVsize = 0 rss = 0 delta = 0
[0] run: 0 lumi: 0 event: 0  vsize = 0 deltaVsize = 0 rss = 0 delta = 0
[0] run: 0 lumi: 0 event: 0  vsize = 0 deltaVsize = 0 rss = 0 delta = 0
[1] run: 1 lumi: 1 event: 1  vsize = 806.32 deltaVsize = 0 rss = 285.715 delta = 0
TimeReport> Time report complete in 6.36567 seconds
 Time Summary: 
 - Min event:   1.94451
 - Max event:   1.94451
 - Avg event:   1.94451
 - Total loop:  1.94565
 - Total init:  4.41856
 - Total job:   6.36567
 - EventSetup Lock:   0
 - EventSetup Get:   0
 Event Throughput: 0.513968 ev/s
 CPU Summary: 
 - Total loop:  1.81109
 - Total init:  2.43381
 - Total extra: 0
 - Total job:   4.24624
 Processing Summary: 
 - Number of Events:  1
 - Number of Global Begin Lumi Calls:  1
 - Number of Global Begin Run Calls: 1

```
```
TimeModule> 1 1 test TrackerParametersAnalyzer 1.27393
TimeModule> 1 1 p1 PathStatusInserter 4.79221e-05
TimeModule> 1 1 TriggerResults TriggerResultInserter 2.09808e-05
TimeEvent> 1 1 1.27431
MemoryReport> Peak virtual size 714.941 Mbytes
 Key events increasing vsize: 
[0] run: 0 lumi: 0 event: 0  vsize = 0 deltaVsize = 0 rss = 0 delta = 0
[0] run: 0 lumi: 0 event: 0  vsize = 0 deltaVsize = 0 rss = 0 delta = 0
[1] run: 1 lumi: 1 event: 1  vsize = 714.941 deltaVsize = 0 rss = 231.512 delta = 0
[0] run: 0 lumi: 0 event: 0  vsize = 0 deltaVsize = 0 rss = 0 delta = 0
[0] run: 0 lumi: 0 event: 0  vsize = 0 deltaVsize = 0 rss = 0 delta = 0
[0] run: 0 lumi: 0 event: 0  vsize = 0 deltaVsize = 0 rss = 0 delta = 0
[0] run: 0 lumi: 0 event: 0  vsize = 0 deltaVsize = 0 rss = 0 delta = 0
[1] run: 1 lumi: 1 event: 1  vsize = 714.941 deltaVsize = 0 rss = 231.512 delta = 0
TimeReport> Time report complete in 4.63043 seconds
 Time Summary: 
 - Min event:   1.27431
 - Max event:   1.27431
 - Avg event:   1.27431
 - Total loop:  1.27532
 - Total init:  3.35362
 - Total job:   4.63043
 - EventSetup Lock:   0
 - EventSetup Get:   0
 Event Throughput: 0.784119 ev/s
 CPU Summary: 
 - Total loop:  1.19313
 - Total init:  2.11341
 - Total extra: 0
 - Total job:   3.30792
 Processing Summary: 
 - Number of Events:  1
 - Number of Global Begin Lumi Calls:  1
 - Number of Global Begin Run Calls: 1
```

@ghugo83 - This PR does not solve the problem with a TOB DetId, just one more automated check for an IB integration.
```
%MSG-w TkAccumulatingSensitiveDetector::createHit:  OscarMTProducer:g4SimHits  26-Oct-2020 16:47:56 CET Run: 1 Event: 1
 theDetUnitId is not valid for TrackerHitsTOB
%MSG
----- Begin Fatal Exception 26-Oct-2020 16:47:56 CET-----------------------
An exception of category 'TkAccumulatingSensitiveDetector::createHit' occurred while
   [0] Processing  Event run: 1 lumi: 1 event: 1 stream: 0
   [1] Running path 'FEVTDEBUGoutput_step'
   [2] Prefetching for module PoolOutputModule/'FEVTDEBUGoutput'
   [3] Calling method for module OscarMTProducer/'g4SimHits'
Exception Message:
cannot get theDetUnitId for G4Track 5834
----- End Fatal Exception -------------------------------------------------

```

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
