### PR TITLE
move EcalPedestalHistory in to plugins directory to avoid duplicate definitions

### PR DESCRIPTION
**Pull request by smuzaffar**
#### PR description:

Currectly `EcalPedestalHistory` edmplugin is defined in src directory which means it becomes part of the `CondToolsEcal` shared library. Any plugin which depneds on  `CondTools/Ecal`  then register  `EcalPedestalHistory` which can result in duplicate plugin definition e.g.

https://cmssdt.cern.ch/SDT/cgi-bin/showDupDict.py//slc7_amd64_gcc700/www/sat/11.0-sat-11/CMSSW_11_0_X_2019-08-31-1100/testLogs/dupDict-edmPD.log

- EcalPedestalHistory
  - pluginCalibCalorimetryEcalTrivialCondModules.so
  - pluginCalibrationEcalCalibAlgosAuto.so

#### PR validation:

local build shows not errors.

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by fabiocos** [comment]
@ggovi could you please have a look? It is a simple technical fix

**Comment by ggovi** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
