### PR TITLE
Read SLHA from TTree

### PR DESCRIPTION
**Pull request by kpedro88**
#### PR description:

The upcoming pMSSM scan covers O(500K) different signal models, each with their own SLHA parameters. It is prohibitive to have a separate text file for each model, or to put all the SLHA tables directly into the generator fragment.

Instead, we have deployed a new method, using a ROOT `TTree` to compress the information and then efficiently read just the SLHA table for a specific model. This uses a `TTreeIndex` to search the tree, with the index information derived from the `configDescription` used for the randomized parameter signal scan.

In case others want to use this method in the future, it is implemented using a factory pattern, where the base class handles getting the ROOT file and tree, and the derived class handles parsing the `configDescription` and extracting the information from the tree. The expected PSet looks like this:
```python
SLHATreeForPythia8 = cms.PSet(
    name = cms.string("SLHAReaderpMSSM"),
    file = cms.string(os.path.expandvars('$CMSSW_BASE/src/GeneratorInterface/Pythia8Interface/data/pMSSM_selected.root')),
    tree = cms.string('mcmc'),
),
```

#### PR validation:

The full pMSSM generator fragment is still being finalized, and the associated ROOT file (1.7GB) is expected to be uploaded somewhere in cvmfs. For now, the PR can be tested following these instructions: https://gist.github.com/kpedro88/ab8a1350dd6c4f7f52275bbb993cf741.

Backports are planned to 10_6_X, 10_2_X, and 9_4_X. I will wait to submit the backports until this PR is reviewed and approved.

### CODE REVIEW

**Comment by kpedro88** [comment]
please test

**Comment by SiewYan** [comment]
@mkirsano , new plugin added to Pythia8Interface. I do not see any significant changes toward the On-going work on pythia8 upgrade. I do not see any issue with the reader, do you have any comment?

**Comment by mkirsano** [comment]
To test it with the version 303, we will have to use this one and 3 
more PR, total of 4. A bit complicated?

20/10/20 12:25, SiewYan пишет:

**Comment by kpedro88** [comment]
I don't think this PR should be dependent on any particular Pythia8 version.

**Comment by agrohsje** [comment]
Hi @kpedro88 . Just one question. With this new logic we cannot review when approving requests.  How will we make sure there is no mistake?

**Comment by kpedro88** [comment]
@agrohsje I'm not sure what you're asking. In the PR description, I provided test instructions in a gist.

**Comment by agrohsje** [comment]
What I mean. When we are asked to approve mc requests, we cannot easily check the tree, resp. the settings that are used to fill it. What is the procedure to make sure there is no mistake in the tree? Not saying I can spot all mistakes in the table but I usually check them carefully.

**Comment by kpedro88** [comment]
I think this would have to be assessed by the results of the test run for the MC request. When the test runs, Pythia prints the contents of the SLHA table temporary files (each time a new table is loaded). In the particular case of the pMSSM scan, it doesn't seem like there's a viable approach to check 500K SLHA tables manually.

**Comment by agrohsje** [comment]
The scan is not my worry, it is the "template" that would be nice to check.  We could add additional info to gen checking script, but the output will become messy. Will think about this and approve. Thanks @kpedro88

**Comment by agrohsje** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
