### PR TITLE
Clean unused dependencies from BuildFiles

### PR DESCRIPTION
**Pull request by guitargeek**
#### PR description:

Another quick BuildFile cleaning PR in the style of many before (for example https://github.com/cms-sw/cmssw/pull/39160).

In many cases, the dependencies had to be moved to the appropriate BuildFile, for example from a plugins directory to the library directory or vice versa.

This PR cleans unnecessary includes from CMSSW BuildFiles that were added in the last months.

#### PR validation:

CMSSW compiles.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

No backport intended.

### CODE REVIEW

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by missirol** [comment]
+hlt

**Comment by AdrianoDee** [comment]
+upgrade

**Comment by swertz** [comment]
+xpog

**Comment by mandrenguyen** [comment]
+reconstruction

**Comment by ChrisMisan** [comment]
+alca

- no differences spotted
- technical PR

**Comment by tvami** [comment]
+db
 * technical PR

**Comment by emanueleusai** [comment]
+1

- technical PR

**Comment by tvami** [comment]
> and @cecilecaillol, could you please take a look? 

also @epalencia

**Comment by cecilecaillol** [comment]
+l1

**Comment by guitargeek** [comment]
Hi @rappoccio! Since only the signature of `analysis` is missing, can this PR be merged now? It would probably good to merge this soon, so that there are no conflicts appearing in one of the many files

**Comment by perrotta** [comment]
+1

**Comment by perrotta** [comment]
merge

**Pull request merged**
