### PR TITLE
[GCC9] fix implicit-fallthrough warning for Validation/EcalDigis

### PR DESCRIPTION
**Pull request by smuzaffar**
This should fix the GCC9 compilation warning

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by fabiocos** [comment]
@jfernan2 @andrius-k this looks straightforward and ok to me, could you please check and sign it in case?

**Comment by jfernan2** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
