### PR TITLE
Update of HLT frozen menu to 2022-V1.3

### PR DESCRIPTION
**Pull request by missirol**
#### PR description:

This PR updates the frozen HLT menu in `12_5_X` to the "V1.3" menu for 2022 pp data-taking.

#### PR validation:

TSG tests.

#### If this PR is a backport, please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

N/A

### CODE REVIEW

**Comment by missirol** [comment]
please test

**Comment by missirol** [comment]
+hlt

**Comment by missirol** [comment]
@cms-sw/orp-l2 , a kind ping for the review of this PR.

**Comment by perrotta** [comment]
+1

**Pull request merged**
