### PR TITLE
Run2-hcx171 Add 3 new Det names for HGCal

### PR DESCRIPTION
**Pull request by bsunanda**
The HGCal will make use of the sub-detector part to expand the channel description

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by fabiocos** [comment]
@bsunanda @civanch @lgray one question: do we really need 3 top level detectors for HGCal? Or would not be better to have one HGCal detector, and manage the different sub-systems as subdetectors? BTW, I think I will add one top level detector for the FastTiming, as this would allow me a bit more freedom in the numbering scheme I have designed for the MTD).

**Comment by lgray** [comment]
Isn't the HGCalEEDetId not needed any more?  I though that everything was addressable with the HGCalDetId alone now?

**Comment by bsunanda** [comment]
Hi Lindsey

We have to use 3 DetId class-es for HGCal. The final design will be put in place soon - but we need 3 Det level assignment for this to accommodate some of the requirements discussed in a few recent HGCal meetings. I shall define them when I start putting in the new detector definitions. I have not deleted  HGCalDetId class as yet - but this will be done soon.

Sunanda
________________________________

**Comment by bsunanda** [comment]
Hi Fabio

This is indeed required. There were big discussions about this for the past 6-8 months. We have come to some compromise with 3 new Det names. Regards

Sunanda
________________________________

**Comment by fabiocos** [comment]
@bsunanda sorry, but we have different subsystems in all the other top level detectors, and they have their own detids (e.g. EBDetID, EEDetId, ESDetId), still the top level detector is just one (Ecal). So why here do you need to split already at top detector level in 3 instead of redefining

https://github.com/cms-sw/cmssw/blob/master/DataFormats/ForwardDetId/interface/ForwardSubdetector.h#L4

as done for instance in

https://github.com/cms-sw/cmssw/blob/master/DataFormats/ForwardDetId/interface/ForwardSubdetector.h#L4

or

https://github.com/cms-sw/cmssw/blob/master/DataFormats/ForwardDetId/interface/ForwardSubdetector.h#L4  ?

I am not particularly keen on pushing a specific solution, but I would like to understand the underlying logic

**Comment by bsunanda** [comment]
Hi Fabio

We discussed in great detail about this in the HGCal meetings. Each detector has its own problems and this is reflected in this choice.The main difficulty is the huge CPU requirement in pattern recognition in HGCal and so for simple pattern recognition it is better to have light navigation tools which can make use of some hierarchical definition with sufficient information of providing idea of neighbours. IN the previous version we tried to pack this in a way which needs lengthier unpacking and row/column or translation from cell to trigger cell was very heavy. It will be nice if you could attend ome of the HGCal meeting to understand the issues involved. ECAL is a detector with lot less channels than HGCal and also it has near pointing geometry so that navigation tool can be written in a simpler way.

Sunanda
________________________________

**Comment by fabiocos** [comment]
@bsunanda ok, I see the discussion in https://indico.cern.ch/event/700830/ and I understand better the reason for this choice.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
