### PR TITLE
Fix G4 logical volumes assignments to production cuts regions with DD4hep

### PR DESCRIPTION
**Pull request by ghugo83**
Fix the remaining discrepancies in G4 logical volumes assignments to production cuts regions with DD4hep.
These discrepancies were stemming from reflected volumes.
Reflected volumes need to benefit from a special treatment in DD4hep.

This is now addressed, and together with https://github.com/cms-sw/cmssw/pull/33101:
**The production cuts assignments are not absolutely identical between DDD and DD4hep: 839 roots are assigned to production cuts regions.**

NB: I also had a branch where a container already containing the G4 reflected volumes is passed to the production cuts constructor. This complicates the interface though, and has absolutely no impact on perf (less than ~0.01 s in initialization loop), hence did not go for that option.

@civanch @cvuosalo @ianna

### CODE REVIEW

**Comment by ghugo83** [comment]
NB: Production cut regions are also identical between DDD and DD4hep.

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
