### PR TITLE
PPS alignment renaming AlCa Prompt producers

### PR DESCRIPTION
**Pull request by grzanka**
#### PR description:

This PR is a refactoring (renaming) of the AlCa Prompt producers responsible for PPS Alignment.
The changes are necessary for T0 replay with PPS. The suggestions for renaming appeared in the discussion of https://github.com/cms-sw/cmssw/pull/36273

#### PR validation:

Tested with:
```
runTheMatrix.py -l 1042 --ibeos
```

### CODE REVIEW

**Comment by grzanka** [comment]
@malbouis @tvami FYI

**Comment by yuanchao** [comment]
@cmsbuild please test

**Comment by malbouis** [comment]
test parameters:

- workflows=1042

**Comment by malbouis** [comment]
@cms-sw/pdmv-l2 , @cms-sw/upgrade-l2 , this is a technical PR. It is part of a renaming to run the PPS PCL workflows at  a Tier0 replay. Would you please consider signing it?

**Comment by kskovpen** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

**Comment by tvami** [comment]
Hi @cms-sw/orp-l2 this PR is essentially fully signed, please sign at your earliest convenience.

**Comment by grzanka** [comment]
Closing in favour of https://github.com/cms-sw/cmssw/pull/36702 as suggested in https://github.com/cms-sw/cmssw/pull/36702#issuecomment-1018693912

**Pull request closed without merging**
