### PR TITLE
Run3-gex93A Modify the run3 scenarios with the modified material xml files

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Modify the run3 scenarios with the modified material xml files. D86 scenario of phase2 is also affected because of changes in the material file used for the tracker cable going through the gap between EB/HB and HGCal

#### PR validation:

Use the runTheMatrix test workflows

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
@bsunanda Do you think it is expected that these small material changes would be enough to create comparison differences in the DD4hep workflow 11634.911?

**Comment by cvuosalo** [comment]
@bsunanda Will the reduced material scenarios also require these changes?

**Comment by cvuosalo** [comment]
+1

**Comment by bsunanda** [comment]
@cvuosalo Yes in view of the changes in dd4hep case it may be worthwhile to modify the changed scenarios. We need to relook at the legacy scenario as well. But the priority is Run3 default geometry

**Comment by civanch** [comment]
urgent

**Comment by srimanob** [comment]
If I read the PR correctly, the change of 2021 is only on tracker. Why do we see a lot of effects in most of subsystems? 
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_1_X_2021-09-14-1100+f7b975/45481/11634.911_TTbar_14TeV+2021_DD4hep+TTbar_14TeV_TuneCP5_GenSim+Digi+Reco+HARVEST+ALCA/

Is it because of many PRs are merged on top of IB?

**Comment by civanch** [comment]
@srimanob , if a tiny modification is introduced to tracker geometry or material, then tracking history for all CMS should be changed.

**Comment by srimanob** [comment]
+Upgrade

This PR introduces a change in tracker material as what PR title says. However, I would prefer that the title and PR description are updated to reflect what include in this PR because there is a change also in Phase-2 ECAL XML.

**Comment by qliphy** [comment]
@bsunanda  Would you follow suggestions above from @srimanob ?

**Comment by qliphy** [comment]
> +Upgrade
> 
> This PR introduces a change in tracker material as what PR title says. However, I would prefer that the title and PR description are updated to reflect what include in this PR because there is a change also in Phase-2 ECAL XML.

@bsunanda Please see above.

**Comment by bsunanda** [comment]
Yes, I know that. It only affects D86 scenario for phase2 which is currently under investigation. So this will not affect any of the validated phase2 scenarios

**Comment by bsunanda** [comment]
@qliphy @perrotta @cvuosalo @civanch @srimanob Please merge this PR

**Comment by qliphy** [comment]
+1

**Comment by qliphy** [comment]
merge

**Pull request merged**
