### PR TITLE
[DD] Move public headers in to interface directory

### PR DESCRIPTION
**Pull request by smuzaffar**
As reported in #34718 , this PR moves headers in interface directory for `DetectorDescription`
```
      2 src/DetectorDescription/Core/src/Box.h
      2 src/DetectorDescription/Core/src/Cons.h
      2 src/DetectorDescription/Core/src/CutTubs.h
      2 src/DetectorDescription/Core/src/EllipticalTube.h
      2 src/DetectorDescription/Core/src/ExtrudedPolygon.h
      5 src/DetectorDescription/Core/src/LogicalPart.h
      6 src/DetectorDescription/Core/src/Material.h
      2 src/DetectorDescription/Core/src/Polycone.h
      2 src/DetectorDescription/Core/src/Polyhedra.h
      1 src/DetectorDescription/Core/src/PseudoTrap.h
     18 src/DetectorDescription/Core/src/Solid.h
      4 src/DetectorDescription/Core/src/Specific.h
      2 src/DetectorDescription/Core/src/Sphere.h
      2 src/DetectorDescription/Core/src/Torus.h
      2 src/DetectorDescription/Core/src/Trap.h
      1 src/DetectorDescription/Core/src/TruncTubs.h
      2 src/DetectorDescription/Core/src/Tubs.h
```

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by ianna** [comment]
@smuzaffar - I think these are private headers, e.g. they should not be exposed beyond `DD/Core`

**Comment by smuzaffar** [comment]
@ianna , there are unit tests in `SimG4Core/Geometry` which use these headers. Feel free to move the unit tests from `SimG4Core/Geometry` in to `DD/Core`

**Comment by ianna** [comment]
> @ianna , there are unit tests in `SimG4Core/Geometry` which use these headers. Feel free to move the unit tests from `SimG4Core/Geometry` in to `DD/Core`

@smuzaffar - thanks, the unit tests depend on Geant4. Shall we delete them?

**Comment by smuzaffar** [comment]
instead of deleteding move unit tests to DD/Core/test , adding geant4 dependency only for  DD/Core/test should be fine

**Comment by ianna** [comment]
> instead of deleteding move unit tests to DD/Core/test , adding geant4 dependency only for DD/Core/test should be fine

No, moving them would not work - some of the tests that implement non-G4 shapes depend on `SimG4Core/Geometry`. I guess, this PR is a better solution. Thanks!

**Comment by ianna** [comment]
@smuzaffar - I've no idea why the removal test fail. This change should not have had any affect on them...

**Comment by smuzaffar** [comment]
Relval-INPUT test failing is not related to this PR. This is due to https://github.com/cms-sw/cmssw/issues/34633 issue.

**Comment by civanch** [comment]
+1

**Comment by perrotta** [comment]
+1

**Comment by perrotta** [comment]
@cms-sw/geometry-l2 please notice the "logic error" pointed out by the static analyzer
I think it could be solved by simply moving **L105** of SimG4Core/Geometry/src/DDG4ProductionCuts.cc inside the preceeding if block: that starts at **L92**:
```C++
   if (regionName != curName) {
```

**Comment by perrotta** [comment]
merge

**Pull request merged**
