### PR TITLE
added missing pixel features from CVS-head

### PR DESCRIPTION
**Pull request by clelange**
This pull request is similar to the one for CMSSW_5_3_X here: https://github.com/cms-sw/cmssw/pull/7167

During the switch from CVS to git a large part of the pixel code additions which are needed for the pixel online software and also calibration of the pixel detector were forgotten to be added to a release and only ended up in the CVS head. These changes should be in CMSSW_7_3_X and later (pull requests will follow for CMSSW_7_4_Y once this one is accepted).

### CODE REVIEW

**Comment by davidlange6** [comment]
please submit first for 74x.

**Comment by mmusich** [comment]
@clelange #7220 is merged in 74X, what about this one?

**Comment by clelange** [comment]
If nobody objects, it would also be good to have it merged in 7_3_X to make sure it's propagated everywhere in the future.

**Comment by davidlange6** [comment]
74x is the 2015 release - having this there should be sufficient

**Pull request closed without merging**
