### PR TITLE
[10.2.X] HP BS

### PR DESCRIPTION
**Pull request by lpernie**
Book keeping for AlcaDB

### CODE REVIEW

**Comment by lpernie** [comment]
please test

**Comment by lpernie** [comment]
backport of #23818

**Comment by lpernie** [comment]
please test

**Comment by lpernie** [comment]
Please test

**Comment by lpernie** [comment]
+1

**Comment by ggovi** [comment]
+1

**Comment by lpernie** [comment]
Hello @fabiocos , there are no changes in the workflow.
This change only remind how the metadata has been produced. It is a book keeping for AlCa about the metadata tag,

**Comment by fabiocos** [comment]
+1

**Pull request merged**
