### PR TITLE
Move ecal_dqm_sourceclient and hlt_dqm_sourceclient to Run-3 era

### LINKED ISSUE #36944: Code still consumes CASTOR tags in Run-3
In https://github.com/cms-sw/cmssw/pull/36940
we discovered that the there is still some code that consumes CASTOR tags in Run-3.

https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-0f9c0d/22366/unitTests/src/DQM/Integration/test/TestDQMOnlineClient-ecal_dqm_sourceclient/testing.log
and
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-0f9c0d/22366/unitTests/src/DQM/Integration/test/TestDQMOnlineClient-hlt_dqm_sourceclient/testing.log

```
----- Begin Fatal Exception 11-Feb-2022 22:50:25 CET-----------------------
An exception of category 'NoRecord' occurred while
   [0] Processing global begin Run run: 344518
   [1] Prefetching for module EcalDQMonitorClient/'ecalMonitorClient'
   [2] Prefetching for EventSetup module CaloGeometryBuilder/''
   [3] Calling method for EventSetup module CastorGeometryFromDBEP/''
   [4] While getting dependent Record from Record CastorGeometryRecord
Exception Message:
No "PCastorRcd" record found in the EventSetup.

 Please add an ESSource or ESProducer that delivers such a record.
```

and
```
----- Begin Fatal Exception 11-Feb-2022 22:50:59 CET-----------------------
An exception of category 'NoRecord' occurred while
   [0] Processing global begin Run run: 344518
   [1] Prefetching for module HcalRecHitsAnalyzer/'hltHCALRecHitsAnalyzer'
   [2] Prefetching for EventSetup module CaloGeometryBuilder/''
   [3] Calling method for EventSetup module CastorGeometryFromDBEP/''
   [4] While getting dependent Record from Record CastorGeometryRecord
Exception Message:
No "PCastorRcd" record found in the EventSetup.

 Please add an ESSource or ESProducer that delivers such a record.
----- End Fatal Exception -------------------------------------------------
```

### PR DESCRIPTION
**Pull request by tvami**
#### PR description:

To resolve the issue in https://github.com/cms-sw/cmssw/pull/36940#issuecomment-1036986080

Shamelessly copied from Marco here:
https://github.com/cms-sw/cmssw/issues/36944#issuecomment-1037059001

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Should be backported to 12_2_X

Resolves https://github.com/cms-sw/cmssw/issues/36944

### CODE REVIEW

**Comment by tvami** [comment]
type bug-fix

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by rappoccio** [comment]
We discussed this internally and for the moment we will have to go with this solution for the MWGR and fix it for CRAFT.

**Comment by perrotta** [comment]
@jfernan2 is there any reason why you signed the 12_2_X backport and not this one in the master?

**Comment by tvami** [comment]
> @jfernan2 is there any reason why you signed the 12_2_X backport and not this one in the master?

I think it's just that the Jenkins tests came back earlier for that PR (which is weird as the tests were started later)

**Comment by jfernan2** [comment]
That's it, when I signed tests were not available in this one

**Comment by jfernan2** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
