### PR TITLE
Hcalmap

### PR DESCRIPTION
**Pull request by weihuacern**
version G hcal electronic map and logical map producer:
cmsRun CalibCalorimetry/HcalAlgos/test/maptester_cfg.py 

New features: 
HO remap
HBHEHF uTCA channels
QIE map
Possible DB dump file from original FNAL QIE calibration constant once we have source file in CalibCalorimetry/HcalAlgos/data diretory(the source file is about 50MB so not included in the PR)

### CODE REVIEW

**Comment by lihux25** [comment]
Can anyone take a look at this PR and proceed? It's now important for other code development based on it. And these are to enable 1x1 HF trigger primitive. Thanks!

**Comment by mmusich** [comment]
please test

**Comment by diguida** [comment]
-1
* data files should go in the data repo.
* change of shape of condition objects is not allowed: please create a new class containing the new members.

**Comment by ggovi** [comment]
-1

**Pull request closed without merging**
