### PR TITLE
Add include for TrackFwd.h to MuonSelector.h

### PR DESCRIPTION
**Pull request by Teemperor**
We use TrackCollection in this header, so we also need to include
TrackFwd.h to make this file compile on its own.

### CODE REVIEW

**Comment by Teemperor** [comment]
Part of the work going on regarding the C++ modules migration of CMSSW (tracked as issue https://github.com/cms-sw/cmssw/issues/15248). This PR is not meant to refactor things, but just to make these headers compile.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/19280	cbbb2b0
- technical 
- jenkins tests pass

**Comment by davidlange6** [comment]
merge

**Pull request merged**
