### PR TITLE
Phase2-hgx311B Add creation of some missing v17 modules for the HE section of HGCal

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Add creation of some missing v17 modules for the HE section of HGCal

#### PR validation:

Tested with some of the cfg's in the test area of Geometry/HĢCalCommonData

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cvuosalo @civanch @srimanob Please sign this PR. It is needed for the next step of V17 geometry description

**Comment by cvuosalo** [comment]
+1

**Comment by bsunanda** [comment]
@srimanob Please approve this PR. It is needed for subsequent modifications.

**Comment by srimanob** [comment]
+Upgrade

Add missing piece of V17 HGCal.

**Comment by qliphy** [comment]
+1

**Pull request merged**
