### PR TITLE
fixing names in fragments for 13p6 CPx tunes

### PR DESCRIPTION
**Pull request by agrohsje**
#### PR description:
Modified setting names for CPx tunes adjusted to 13.6 TeV. Reason is simpler handling for common background production. Discussed in the original PR:
https://github.com/cms-sw/cmssw/pull/38358#issuecomment-1165540772

#### PR validation:
Checked that nothing was touched and only file names changed in the PR. Compared on top settings to MCTunes2017 to see difference discussed on p6:
https://indico.cern.ch/event/1169048/contributions/4909711/attachments/2456268/4210106/2022_June6_GEN_CPXnormForRun3_SercanSen.pdf

### CODE REVIEW

**Comment by agrohsje** [comment]
add generators

**Comment by agrohsje** [comment]
Hi @SanghyunKo , all, I just made the PR to help out as I proposed the change. Hope that's fine. Can also adjust something if preferred. Let me know. Once we agreed I will make a backport to 12_4 and 12_2. However for the early cross section we decided to keep 13 TeV settings to be consistent with already available samples.

**Comment by agrohsje** [comment]
please test

**Comment by agrohsje** [comment]
Not enough carma points. Maybe someone else can ask the bot to test?

**Comment by Saptaparna** [comment]
Please test

**Comment by Saptaparna** [comment]
I hope I have the power.

**Comment by agrohsje** [comment]
Looks good. Thanks so much @Saptaparna !

**Comment by Saptaparna** [comment]
+1

**Comment by qliphy** [comment]
+1
Thanks @agrohsje   Please backport this to 12_4_X and 12_3_X/12_2_X (if needed).

**Pull request merged**
