### PR TITLE
[90X] update 2023 upgrade simulation Global Tag with SIM and RECO geometries tags

### PR DESCRIPTION
**Pull request by mmusich**
# Summary of changes in Global Tags 
 
## Upgrade 
 
   * **PhaseII realistic scenario** : [90X_upgrade2023_realistic_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_upgrade2023_realistic_v3) as [90X_upgrade2023_realistic_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_upgrade2023_realistic_v2) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/90X_upgrade2023_realistic_v3/90X_upgrade2023_realistic_v2): 
      * added conditions for`GEMRecoGeometryRcd`,`ME0RecoGeometryRcd` 
      * updated RECO geometries for `HcalParametersRcd`, `IdealGeometryRecord`, `PGeometricDetExtraRcd`, `PHcalRcd`, `PTrackerParametersRcd`, `RPCRecoGeometryRcd` to version `81YV023` 
      * added 6 flavours of SIM geometry `GeometryFileRcd` with labels Extended2023D*, *=1,..,6
      * removed several unused labels of SIM geometry `GeometryFileRcd`:
```
   Record           Label                        Tag                                                      
   ---------------  ---------------------------  -------------------------------------------------------  
-  GeometryFileRcd  Extended2015CastorMeasured   XMLFILE_Geometry_80YV1_Extended2015CastorMeasured_mc     
-  GeometryFileRcd  Extended2015CastorSystMinus  XMLFILE_Geometry_80YV1_Extended2015CastorSystMinus_mc    
-  GeometryFileRcd  Extended2015CastorSystPlus   XMLFILE_Geometry_80YV1_Extended2015CastorSystPlus_mc     
-  GeometryFileRcd  Ideal                        XMLFILE_Geometry_Run2_76YV2_Ideal2015_mc                 
-  GeometryFileRcd  Extended2015ZeroMaterial     XMLFILE_Geometry_Run2_76YV2_Extended2015ZeroMaterial_mc  
-  GeometryFileRcd  Extended2015dev              XMLFILE_Geometry_Run2_76YV2_Extended2015dev_mc           
-  GeometryFileRcd  Ideal2015dev                 XMLFILE_Geometry_Run2_76YV2_Ideal2015dev_mc 
```
      

attn: @ianna this addresses [this](https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2779.html) and this [request](https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2780.html)

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
+1
as geometry is consumed via XML, no changes are foreseen in production workflows

**Comment by mmusich** [comment]
@davidlange6 if there are no objections, would you kindly approve also this one? 
There is more long term conditions' consolidation work needed in view of 900pre3.
Thanks,
M.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
