### PR TITLE
new T0 scenario ppEra_Run2_2016_pA; migration of customise_PPwithHI to eras

### PR DESCRIPTION
**Pull request by slava77**
- no changes to the currently available workflows
- customisePPrecoForPeripheralPbPb should be replaced by Run2_25ns_peripheralPbPb
- customisePPrecoforPPb  is replaced by Run2_2016_pA
- added T0 scenario ppEra_Run2_2016_pA to be used for the upcoming pA processing

Primary reason that forced the move to eras was the event content edits, which are not compatible with the DataProcessing workflow setup (fully python process preparation). In 75X for pp reference run we ended up making edits in the actual release.
Given that special settings are applicable to both data and MC, it is more appropriate to have them set up using eras.

Before deleting customise_PPwithHI, I checked that the resulting config is the same with the customise and with the era on top of the corresponding parent era (Run2_25ns + customisePPrecoForPeripheralPbPb vs Run2_25ns_peripheralPbPb; and Run2_2016+customisePPrecoforPPb vs Run2_2016_pA).

Current status of DataProcessing setup in 81X prevented debugging there:
- https://github.com/cms-sw/cmssw/issues/15792 is still not resolved 
- and a possible alternative pkl solution was not implemented or tested

@makortel @rovere @VinInn note the edits in the seeding setup PSets instead of specific iterative tk module instances. It seemed that to me that this is more straightforward for maintenance reasons (in addition to plain simplicity reason of having less spots to add the modifications).

I'll wait for inputs for ~day  before porting this to 81X.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cmsbuild please test

... now updated PPb relval steps, contributing to wf 281.

**Comment by fabozzi** [comment]
+1

**Comment by makortel** [comment]
@slava77 

> note the edits in the seeding setup PSets instead of specific iterative tk module instances. It seemed that to me that this is more straightforward for maintenance reasons (in addition to plain simplicity reason of having less spots to add the modifications).

I'd say that this way is also more correct (if there is no need to adjust the maxElement per iteration). So +1 from me.

**Comment by slava77** [comment]
@cmsbuild please test

... after matching up the "keep" statements with #16308 to include QIE10 ZDC

**Comment by slava77** [comment]
@cmsbuild please test
after rebase

**Comment by slava77** [comment]
@cmsbuild please test
to pickup the latest IB

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/16394 6d84747
- jenkins tests pass and comparisons show no differences

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/16394 d4bc922
- jenkins tests pass and comparisons show no differences
- local tests comparing pPb and PbPb customizations to the era results were done prior to the PR submission and show consistent behavior and consistent expanded configs

**Comment by slava77** [comment]
backport of #16439 
is included here

**Comment by fabozzi** [comment]
+1

**Comment by slava77** [comment]
@davidlange6 
please clarify when this is going to be merged
DQM and probably L1 PRs are blocked by availability of eras introduced by this PR.

**Comment by davidlange6** [comment]
the 81x 1100 is testing parts of this PR (given the changes of yesterday) - so presumably this can get merged later today

**Comment by mandrenguyen** [comment]
@slava77 @davidlange6 
@icali informs me there is some urgency to test the L1-related items slated for 8023 tomorrow.  I would propose that the release be built as soon as this PR is merged.  That would mean patching in the DQM related PRs (16408, 16406, 16289, some of which depend on this PR) somewhat later.  Does that sound reasonable/doable?

**Comment by davidlange6** [comment]
sounds like the plan already established by the ORP...

**Comment by mandrenguyen** [comment]
@davidlange6 ok, perfect (sorry, i had to miss the ORP)

**Pull request merged**
