### PR TITLE
remove HcalCholeskyMatrix object entirely

### PR DESCRIPTION
**Pull request by kpedro88**
This PR finishes the removal of the unused HcalCholeskyMatrix object (see issue #14954).

attn: @abdoulline

### CODE REVIEW

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by mmusich** [comment]
+1

**Comment by kpedro88** [comment]
@ggovi @davidlange6 it would be nice to merge this quickly - while preparing this, I noticed another unused HCAL CondFormat that can be removed (HcalCovarianceMatrix). However, because that object has neighboring lines of code with HcalCholeskyMatrix in some places, I have to wait until this PR is merged so I can rebase. Otherwise, Git thinks there is a conflict.

**Comment by kpedro88** [comment]
@ggovi ping

**Comment by mmusich** [comment]
@kpedro88
@ggovi is away for a few days, and I am not sure he's reading us. 
I think this PR is harmful enough to be merged by-passing the db signature. Let's discuss it at today's ORP.

**Comment by kpedro88** [comment]
@mmusich I hope you mean harmless...

**Comment by mmusich** [comment]
@kpedro88 freudian slip :) corrected now

**Comment by kpedro88** [comment]
@davidlange6 reminder

**Pull request merged**
