### PR TITLE
Remove Legacy Configurations

### PR DESCRIPTION
**Pull request by ianna**
#### PR description:

Remove Iguana configurations

#### if this PR is a backport please specify the original PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by fabiocos** [comment]
Wow, pieces of history...

**Comment by ianna** [comment]
+1

**Comment by ianna** [comment]
@fabiocos - I think you can bypass other signatures. I guarantee the configurations are not useful.

**Comment by perrotta** [comment]
+1
- For reco it just removes obsolete test scripts
- Jenkins tests pass

**Comment by fabiocos** [comment]
@civanch these test cfgs look all quite old, I agree with @ianna, please have a look

**Comment by civanch** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
