### PR TITLE
Bump of CLHEP::Hep3Vector ClassVersion needed for (GEANT4 10.7.1)

### PR DESCRIPTION
**Pull request by silviodonato**
#### PR description:

Bump of CLHEP::Hep3Vector ClassVersion in `DataFormats/CLHEP/src/classes_def.xml`
needed for the update of GEANT4 ( https://github.com/cms-sw/cmsdist/pull/6742 )

#### PR validation:

`CMSSW_11_3_0_pre3_G4VECGEOM` fully validated by PdmV

### CODE REVIEW

**Comment by silviodonato** [comment]
urgent
(to merge  cms-sw/cmsdist#6742 for pre5).
@silviodonato @qliphy let's remind us to use "Squash and merge" to avoid  315 merge commits!

**Comment by makortel** [comment]
+1

assuming the tests in https://github.com/cms-sw/cmsdist/pull/6742#issuecomment-803109330 pass

**Comment by makortel** [comment]
```
error: class 'CLHEP::Hep3Vector' has a different checksum for ClassVersion 11. Increment ClassVersion to 12 and assign it to checksum 3040806103
```
Something didn't work? The current version 10 has the same checksum `3040806103`.

**Comment by silviodonato** [comment]
moved to https://github.com/cms-sw/cmssw/pull/33234

**Comment by silviodonato** [comment]
I closed this PR to avoid the "noise" of the commits "Merge CMSSW_11_3_X into CMSSW_11_3_GEANT4_X. "

**Pull request closed without merging**
