### PR TITLE
HcalDQM: Add protection to collection non-exist case for GPUTask, backport of PR #40117

### PR DESCRIPTION
**Pull request by lwang046**
Backport of PR #40117 to 12_6_X, as requested in #40119

### CODE REVIEW

**Comment by emanueleusai** [comment]
type hcal

**Comment by emanueleusai** [comment]
backport of https://github.com/cms-sw/cmssw/pull/40117

**Comment by emanueleusai** [comment]
please test

**Comment by perrotta** [comment]
+1

**Pull request merged**
