### PR TITLE
Adding new paths to the monitoring - Backport of #20536

### PR DESCRIPTION
**Pull request by sscruz**
Monitoring for Muon POG paths. 
+ Output of the modules: /afs/cern.ch/work/s/sesanche/public/DQM/sep14/DQM_V0001_R000000001__Global__CMSSW_X_Y_Z__RECO.root

+ This PR will add 178540 bins

### CODE REVIEW

**Comment by heppye** [comment]
@dmitrijus,@mia PR is to support higgs trigger proposal targeting for v4. May DQM and STEAM please provide a quick look. Please push the integration if possible. Thanks, Ye (for HIGGS)

**Comment by mtosi** [comment]
@cmsbuild, please test

**Comment by mtosi** [comment]
@sscruz 
can you please quantify the increase in the # bins ?

**Comment by dmitrijus** [comment]
Please change the name of the pull request.

"Backport of #20536" tells us nothing. And we know it's a backport, because there is no other way to get a PR into this branch.

**Comment by dmitrijus** [comment]
@sscruz The pull request needs to go into the master branch first. If you have a pull request for it, please link it.

**Comment by dmitrijus** [comment]
ah, wait, it is in the title...
backport of https://github.com/cms-sw/cmssw/pull/20536

**Comment by sscruz** [comment]
hi @dmitrijus , yes indeed. Sorry about that!

**Comment by davidlange6** [comment]
Closing PR as it is not needed for this release cycle. CMSSW_9_3_X is planned for use only for 2017 GEN-SIM production and HGCal TDR production.

**Pull request closed without merging**
