### PR TITLE
Phase2-hgx150 Add a new validation code for Digi's to be used in standalone way

### PR DESCRIPTION
**Pull request by bsunanda**

### CODE REVIEW

**Comment by andrius-k** [comment]
please test

**Comment by davidlange6** [comment]
please test

**Comment by andrius-k** [comment]
+1

**Comment by fabiocos** [comment]
@bsunanda this code looks so far standalone, please correct me in case. Where was it really tested, and where it should be used?

**Comment by bsunanda** [comment]
@fabiocos This is done in a private test with simulated DIGI collection. The person (Koushik) who does HGCal validation for SIM/DIGI/RECHit uses standalone tools outside normal RelVal runs. The normal RelVal uses DQM tools and for private tests it is easy to produce a ROOT file which can be seen by a bare ROOT browser.

**Comment by fabiocos** [comment]
@bsunanda my question is: is this code exercised in any regular workflow? I would say no...

**Comment by bsunanda** [comment]
@fabiocos No I did not use in in regular workflow. But I used outputs from WF 24034.0 to test it

**Comment by fabiocos** [comment]
+1

**Pull request merged**
