### PR TITLE
Make the online DQM fileinputsource more intelligent

### PR DESCRIPTION
**Pull request by schneiml**
This allows reprocessing StreamExpress runs, as it was needed to analyse some Pilot Blade timing scan data after the online shutdown. It could also be useful in the future and for general Phase1 online DQM development. 

One dataset (as returned from DAS) can have many runs, so we allow selecting a specific run. The
dataset always has all events and will be fully processed, which can be too much for the online DQM, therefore we allow selecting a subset of LS (like in the lookarea).

Remaining problem: The input files as reported from DAS appear in random order, so it can happen that many files have to be opened to find a small LS range, and the data will appear randomly in the DQM live view.

This configuration includes the dataset with the last 2016 pPb runs (again, as they were interesting for the Pilot Blade team and culd not be analysed using the online system). It is by default enabled in the `pixel` and `pixel_up` online clients after #16875 .

### CODE REVIEW

**Comment by dmitrijus** [comment]
+1

**Comment by dmitrijus** [comment]
Regardless dataset_cfi.py, would it not make sense to query these from DAS directly?

**Comment by schneiml** [comment]
Yes it would, but I'd have to figure out how to do this. Any hints where to steal the relevant code?

**Comment by dmitrijus** [comment]
Try https://twiki.cern.ch/twiki/bin/view/CMSPublic/WorkBookLocatingDataSamples

**Comment by schneiml** [comment]
Progress note here: I found the snippet that queries DAS for the runTheMatrix sequences and it looks like that can be used here. Now I just have to come up with a working DAS query that terminates in finite time and test it once I have time and DAS is responding.

**Comment by dmitrijus** [comment]
hold
Nice!

**Comment by schneiml** [comment]
@dmitrijus I added the DAS query support. Main issue is that it can take a while to get results, but that is pretty much expected. Therefore I allowed having the `dataset_cfi.py` file instead, but I removed it from the PR and by default DAS is queried.

Works with the default options, might need some tuning for older runs...

**Comment by dmitrijus** [comment]
super!

**Comment by dmitrijus** [comment]
+1

**Comment by dmitrijus** [comment]
unhold

**Comment by davidlange6** [comment]
+1

**Pull request merged**
