### PR TITLE
Muon HLT - fix in TSGForOI

### PR DESCRIPTION
**Pull request by folguera**
Rescale the TSOS error before finding the compatible detector. This is the same as #17750 but in 91X.
A PR (#17862) was created in 91X and got a request to create the PR in the master.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by perrotta** [comment]
please test
(Errors are unrelated to this PR, and present also in the baseline CMSSW_9_1_X_2017-03-13-2300: let try with a new IB, were those errors are fixed)

**Comment by perrotta** [comment]
@folguera were you able to find the plot mentioned in https://github.com/cms-sw/cmssw/pull/17750#issuecomment-285342038 ?
I think this PR and the one in 90X can be signed off as soon as we can have a look at it
Thank you

**Comment by folguera** [comment]
@perrotta  as you can see the only visible effect is in the overlap region, otherwise it makes no difference. Just for your info this is the L3/L2 efficiency (with no filters at L3 applied), in both cases (L3 and L2) the HLT object has to match a RECO global muon. 

effl3l2eta_oi

**Comment by perrotta** [comment]
+1
No changes visible in jenkin tests, but the effect of the fix on a larger stat sample shown in https://github.com/cms-sw/cmssw/pull/17917#issuecomment-287344452 goes in the wanted direction

**Comment by davidlange6** [comment]
+1

**Pull request merged**
