### PR TITLE
[91X] Fix muon alignment converter

### PR DESCRIPTION
**Pull request by ghellwig**
Fixes bugs in muon alignment code used for providing muon alignment constants.
Adds also a unit test to prevent such a silent introduction of bugs in the future.
Migrated the respective module to an edm::one module.

Attn.: @lpernie

### CODE REVIEW

**Comment by ghellwig** [comment]
please test

**Comment by ghellwig** [comment]
type bugfix

**Comment by ghellwig** [comment]
@davidlange6 
I realize that there is still the CMSSW code rule issue regarding `catch(...)` in a file I touched in this PR
Naively I would expect that any uncaught exception is finally handled by the framework.
Said that, I would just remove this catch-all. Is it safe to proceed like this?

**Comment by davidlange6** [comment]
catch(...) is more a problem from its performance characteristics than anything else.. is best to remove

**Comment by ghellwig** [comment]
please test

**Comment by ghellwig** [comment]
thanks @davidlange6 for your advice!

**Comment by arunhep** [comment]
+1

**Comment by davidlange6** [comment]
+1

the GeometryIdeal_cff is almost always the wrong thing to use - but looks to be correct here

**Pull request merged**
