### PR TITLE
Increasing eta range for tau reconstruction for phase 2 geometries

### PR DESCRIPTION
**Pull request by roger-wolf**
Dear colleagues, 

this is a minimal change to increase the eta range for tau reconstruction for phase2 geometries. We have thoroughly checked and came to the conclusion that this modification is the only one needed to achieve the extension of the eta range for tau reconstruction. A cross check on a phase2 workflow has demonstrated that the eta range of reconstructed tau leptons is indeed increased as expected. 

Tests of runtime and physics performance and small private validation samples did not reveal any problems as anticipated since the modifications a minimal and not even active for non phase2 GT's

As advised by phase2 experts (e.g. Kevin Pedro) we a setting this PR out into the normal 90X development queue. 

Cheers,
Roger

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
Thanks!

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/17163	1655467
- changes are as described [also include an update to local test input files]
- jenkins tests pass and comparisons with baseline show changes only in 2023 workflows in tau variables as expected
- local tests with ttbar PU200 show reasonable changes:
    - tau modules CPU times are up by about 50%, the total increase is 4s/event (40 HS06s) or just under 1% of the total reco time
    - output products related to taus increase in size by 20-40%
    - some plots follow

several discriminator variables look a bit too optimistic about the added yields to be signal-like
all_sign824vsorig_ttbar14tev2023d4timingpu200localwf23034p0c_recopftaudiscriminator_hpspftaudiscriminationbyisolationmvarun2v1pwnewdmwltraw__reco_obj_data_

eta range is extended as expected with relatively flat distribution
all_sign824vsorig_ttbar14tev2023d4timingpu200localwf23034p0c_recopftaus_hpspftauproducer__reco_obj_eta

all_sign824vsorig_ttbar14tev2023d4timingpu200localwf23034p0c_recorecotaupizeros_hpspftauproducer_pizeros_reco_obj_eta
[pi0 reco is apparently restricted by the HGCAL coverage]


all_mini_sign824vsorig_ttbar14tev2023d4timingpu200localwf23034p0c_pattaus_slimmedtausboosted__reco_obj_eta
all_mini_sign824vsorig_ttbar14tev2023d4timingpu200localwf23034p0c_pattaus_slimmedtaus__reco_obj_eta

**Comment by davidlange6** [comment]
+1

**Pull request merged**
