### PR TITLE
Migration of HLT to 900pre2 template & cleanup

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
Migration of HLT to 900pre2 template & cleanup

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by Martin-Grunewald** [comment]
(PR based on CMSSW_9_0_X_2016-12-15-2300)

**Comment by davidlange6** [comment]
Hi @Martin-Grunewald - this needs to be rebased. Thanks

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
Rebased to CMSSW_9_0_X_2017-01-04-1100.
Hopefully nothing got lost...

**Comment by Martin-Grunewald** [comment]
+1

**Comment by Martin-Grunewald** [comment]
@davidlange6 
Done - merges now. Please integrate before the next conflict arises...

**Comment by davidlange6** [comment]
+1
but, err- well, it was a conflict with an hlt pr.. so there was no way to win.

**Pull request merged**
