### PR TITLE
[L1T] Fix issue in loop going beyond array bounds

### PR DESCRIPTION
**Pull request by cecilecaillol**
#### PR description:

Fix issue https://github.com/cms-sw/cmssw/issues/37694, restraining loop over number of clusters allowed in L1 card

### CODE REVIEW

**Comment by cecilecaillol** [comment]
please test

**Comment by cecilecaillol** [comment]
+l1

**Comment by AdrianoDee** [comment]
test parameters:
- workflow=39434.103

**Comment by AdrianoDee** [comment]
please test

**Comment by cecilecaillol** [comment]
@AdrianoDee, @srimanob Kind reminder, can you please review this PR?

**Comment by perrotta** [comment]
+1

**Pull request merged**
