### PR TITLE
Add needed changes to L1 digi to raw for premixing

### PR DESCRIPTION
**Pull request by davidlange6**
fixes failing step2 workflows  (maybe other problems later in the chain)

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by Dr15Jones** [comment]
This appears to have broken the IBs. Shouldn’t the toModify calls be moved to
https://github.com/cms-sw/cmssw/blob/eb8d8e46378a9a48661ec4708c6e176af3e6e627/EventFilter/L1TRawToDigi/python/caloLayer1Raw_cfi.py
?

**Comment by davidlange6** [comment]
where (which workflows) do you see things getting worse?

**Comment by davidlange6** [comment]
ok, 50ns premixing... i fixed all the 25 ns premixing ones so its an improvement.

**Pull request merged**
