### PR TITLE
Material budget update for Phase 2 Flat and Tilted Trackers plugged on Phase 1 Pixel

### PR DESCRIPTION
**Pull request by ghugo83**
This is the twin sister PR of #15946 for SLHCDEV.
@boudoul @ianna @alkemyst

Reminder : 
Updated Flat and Tilted Tracker material budget. This should (hopefully) be a step towards solving the issues in Phase 2 Reco spotted by @ebrondol .

In this PR : 
- updated paths in trackerRecoMaterial.xml and trackerProdCuts.xml to be in concordance with the Pixel / Outer Tracker volumes split.
- TrackerXi values in TrackerRecoMaterial.xml have been manually hacked by Stefano (thanks @VinInn @rovere @venturia ).
- fixed elementary materials description.

### CODE REVIEW

**Comment by ghugo83** [comment]
Dear all,
Can anyone accept/refuse this PR ?

Thanks a lot,
Cheers

**Comment by VinInn** [comment]
@cmsbuild , please test

**Comment by VinInn** [comment]
type urgent

**Comment by ianna** [comment]
+1

**Pull request closed without merging**
