### PR TITLE
Tunings to improve efficiency. Retain only best matching hit in a layer [10_4_X backport of 25636]

### PR DESCRIPTION
**Pull request by fabiocos**
Tunings to improve efficiency. Retain only best matching hit in a layer

(cherry picked from commit 59459aa0c8e07151563f2f9cbfff782ea20b5ce7)

code-checks

(cherry picked from commit 1f6dec12908780648d5515dcfa63b5d9d28d6559)

backport #25636

### CODE REVIEW

**Comment by fabiocos** [comment]
code-checks

**Comment by fabiocos** [comment]
please test workflow 27434.0

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/25715	5ea0e32 
- code changes are the same as in the master version PR (https://github.com/cms-sw/cmssw/pull/25636	1f6dec1)
- jenkins tests pass and comparisons with the baseline show differences only in the workflow with MTD 27434 as expected.

**Comment by kpedro88** [comment]
+upgrade

**Comment by fabiocos** [comment]
+1

**Pull request merged**
