### PR TITLE
add sigmaietaiphi for photon regression inputs

### PR DESCRIPTION
**Pull request by fcouderc**
adding the sigmaietaiphi variable which was missing to compute the photon regression
which affects the photon energy scale computation

### CODE REVIEW

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
@slava77 I'll cherry pick this commit into the ongoing PRs for 75X/74X. It seems to merge fine, so could be separate PR. Your preference.

**Comment by slava77** [comment]
@cmsbuild please test
the last round went to 13-1100 IB, which is older than this PR.
Current tests are being done with CMSSW_7_6_X_2015-09-16-1200 already

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/11276	 7ea1ba5
- this is a clear bugfix; the fix affects correctedEnergy of pat photons if modifiers are running (there are no DQM miniAOD validation plots for photons, as far as I can see)
- jenkins tests pass and comparisons with baseline show no differences (as expected)

**Comment by davidlange6** [comment]
+1

**Pull request merged**
