### PR TITLE
Prepare for concurrent IOVs, MisalignedMuonESProducer

### PR DESCRIPTION
**Pull request by wddgit**
Change produced type from shared_ptr to unique_ptr.

Note this required changing the arguments to the
GeometryBuilders build functions to just be simple
references which is better anyway because the old
interface restricted the caller to using shared_ptr
for no reason.

### CODE REVIEW

**Comment by wddgit** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by pohsun** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
