### PR TITLE
Remove duplicated code used to decode FED header and trailer

### PR DESCRIPTION
**Pull request by mommsen**
For historical reasons, there are two implementations to decode the FED header and trailer. This pull requests removes this duplication and tries to unify how informations found in the FED header and trailer is accessed.

This pull request addressed issues #14353 and #21312. It is also a required for the pull request #21436.

### CODE REVIEW

**Comment by mommsen** [comment]
please test

**Comment by mommsen** [comment]
please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/21690	26cf0d9
- somewhat technical cleanup: reco packages are affected via changes in dependencies or a small interface change (e.g. ```fedTrailer.lenght -> fedTrailer.fragmentLength```
- jenkins tests pass and comparisons with the baseline show no relevant differences
    - ignoring random differences in 2018 workflows introduced by #21651 and affecting HCAL energies used in HLT

**Comment by mommsen** [comment]
+1

**Comment by ghellwig** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
merge

**Pull request merged**
