### PR TITLE
Update EDM inputs to HLT-Validation tests [`8_0_X` only]

### PR DESCRIPTION
**Pull request by missirol**
#### PR description:

This PR is specific to the `CMSSW_8_0_X` release cycle.

Some of the HLT-Validation tests running in IBs started to fail due to the unavailability of EDM files used as input to these tests (see [IB dashboard](https://cmssdt.cern.ch/SDT/html/cmssdt-ib/#/ib/CMSSW_8_0_X), and https://github.com/cms-sw/cmssw/issues/40013).

This PR updates the path to these files, ~~to use copies kept in the TSG area on EOS.~~ which will now rely on the cms-bot cache (see discussion in https://github.com/cms-sw/cmssw/issues/40013 and #40020, where the corresponding updates to `cms-bot` are also mentioned).

In addition, it disables the HLT-integration-tests part of the HLT-Validation tests for scram-archs in SLC6, which are incompatible with the most recent version of ConfDB-v2 (see https://github.com/cms-sw/cmssw/issues/40013#issuecomment-1326250032).

#### PR validation:

None.

#### If this PR is a backport, please specify the original PR and why you need to backport that PR. If this PR will be backported, please specify to which release cycle the backport is meant for:

N/A

### CODE REVIEW

**Comment by missirol** [comment]
please test

**Comment by missirol** [comment]
please test

This will not fully fix the HLT-Validation tests in `8_0_X`, because there seems to be an unrelated issue in accessing the menus from ConfDB (not sure why that is, locally it works):
https://cmssdt.cern.ch/SDT/jenkins-artifacts/HLT-Validation/CMSSW_8_0_X_2022-11-20-2300/slc6_amd64_gcc530/runIB.log

**Comment by missirol** [comment]
please test

From https://github.com/cms-sw/cmssw/issues/40013#issuecomment-1323246563 ..

> to use the bot cache (this 2nd option will not require signatures by Core-Sw)

.. sadly I have to retract this, as I would also change the input of one addon test (from RAW-RECO to RAW, which is the preferred tier for HLT). The file in question is not in the bot cache, but it will be once the PR is merged (it is currently at a T3).

**Comment by missirol** [comment]
please test

See https://github.com/cms-sw/cmssw/issues/40013#issuecomment-1326250032.

**Comment by missirol** [comment]
+hlt

This PR fixes the HLT-Val tests currently failing in `8_0_X` IBs (access EDM files from cms-bot cache + disable HLT-integration tests in SLC6).

The update of 1 input file of the `addOnTests` requires the signature of @cms-sw/core-l2 .

**Comment by perrotta** [comment]
+1

**Comment by perrotta** [comment]
Ah, ok: the @cms-sw/core-l2 is still missing.
I'll let the ORP signature anyhow: as soon as core will sign, this can get merged: if core has any remark, the orp signature alone will not be enough for merging

**Comment by missirol** [comment]
@smuzaffar , could you please check this PR, #40029 and #40028, and sign them for Core-Sw if you agree?

It would be good to test them in IBs over this weekend.

**Comment by smuzaffar** [comment]
+core
For Utilities/ReleaseScripts change, new input data is already available via ibeos cache.

**Pull request merged**
