### PR TITLE
New Calibration for D11 Geometry

### PR DESCRIPTION
**Pull request by atricomi**
New ClusterShape calibration files have been created to take into account the new pixel barrel orientation in T5 Tracker Upgrade Geometry
Default WP is 99.9% efficiency/layer
Also Calibration for 99.5% is available for test purposes

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by kpedro88** [comment]
assign upgrade

**Comment by VinInn** [comment]
this is D11 with this PR vs D13 w/o  (ttbar PU200)
http://innocent.home.cern.ch/innocent/RelVal/pu200D11_ori/plots_highPurity/effandfake1.pdf

**Comment by VinInn** [comment]
as a side effect in #18728 you can see singlemuons as well for this PR  (blue squares)

**Comment by slava77** [comment]
@VinInn 
please add a comparison of D11 without and with this PR.
Comparison of D13(without) with D11(with) is not easy to interpret as being useful for D11.

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/18663	7dafeac
- change in pixel cluster shape for phase 2; the same as in 91X
- jenkins tests pass and comparisons with baseline show differences only in phase-2 workflows
- relying on supporting material provided with the pull request and additional tests done in 91X as a part of the signoff

**Comment by kpedro88** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
