### PR TITLE
Run2-hgx185 Add 2 algorithms for HGCal to DD4Hep format

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Convert 2 HGCal detector description algorithms to dd4hep world

#### PR validation:

Some test script is added and tested in a different scenario

#### if this PR is a backport please specify the original PR:

It is tried to keep the new coding standard  and not a backport

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
The failure in unit test is not due to this PR. Most likely #26267 address this issue

**Comment by ianna** [comment]
please test with cms-sw/cmsdist#4835

**Comment by ianna** [comment]
@bsunanda - Could you please include the cmsRun test in relval script?
```
https://github.com/cms-sw/cmssw/blob/master/DetectorDescription/DDCMS/test/runTest.sh
```
Here is a result of the test:
```
cmsRun DetectorDescription/DDCMS/test/python/testDDHGCalCellAlgorithm.py
cmsShow -c geo.fwc --tgeo-name=TestDDHGCalCell --sim-geom-file cmsDD4HepGeom.root
```
Screen Shot 2019-04-03 at 11 47 05

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
@ianna: I'm satisfied with this PR. I will leave it to you to approve if your issues have been addressed.

**Comment by ianna** [comment]
+1

@bsunanda - I hope, you'll provide a test for the second algorithm as a next PR

**Comment by fabiocos** [comment]
+1

the added test runs smoothly

**Pull request merged**
