### PR TITLE
Removed use of '#define private public' for testing

### PR DESCRIPTION
**Pull request by Dr15Jones**
Tests had converted all private to public in order to test internals. This no longer works with newer versions of gcc since it messes up linking. Switched to using friend instead.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by davidlt** [comment]
Not sure why test is failing, because first thing `RecoMET/METProducers/test/runtests.sh` does it to run _cmsDriver_ command to generate the input file.

https://github.com/cms-sw/cmssw/blob/CMSSW_7_6_X/RecoMET/METProducers/test/runtests.sh

**Comment by davidlange6** [comment]
how do we clean up files after a command finishes? It seems the file is found by one subsequent job but not the next

**Comment by davidlt** [comment]
Tried it locally and got different experience. One thing, PR tests does show cmsDriver being executed. Test:
```
Running script: /tmp/cmsbuild/workspace/ib-any-integration/CMSSW_7_6_X_2015-10-01-2300/src/RecoMET/METProducers/test/runtests.sh
# Conditions read from  CMS_CONDITIONS  via FrontierProd 
%MSG-w CondDBESSource:  (NoModuleName) 02-Oct-2015 09:39:50 CEST pre-events
```
Locally:
```
Running script: /mnt/build/davidlt/CMSSW_7_6_X_2015-10-01-2300/src/RecoMET/METProducers/test/runtests.sh
GEN,SIM,RECOBEFMIX,DIGI:pdigi_valid,L1,L1Reco,RECO,ENDJOB
We have determined that this is simulation (if not, rerun cmsDriver.py with --data)
```
Which failed for me:
```
ImportError: No module named PFRecoTauDiscriminationAgainstElectron_cfi
```

I don't see cmsDriver being invoked in IBs logs also:
https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc6_amd64_gcc493/CMSSW_7_6_X_2015-10-01-2300/unitTestLogs/RecoMET/METProducers

Ah, it's a patch IB so it doesn't show the actual issues.

It's failing in the normal IB also (you just need to find a full IB to see the logs with errors): https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc6_amd64_gcc493/CMSSW_7_6_X_2015-10-01-1100/unitTestLogs/RecoMET/METProducers

**Comment by davidlt** [comment]
Recompiled again and _testRecoMETMETProducers_ worked fine locally.

**Comment by davidlange6** [comment]
@davidlt - i'll merge and we can see what happens...

**Pull request merged**
