### PR TITLE
Run3-gex41 Complementing the geometry scenarios of special cases with the Reco cff's

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Complementing the geometry scenarios of special cases with the Reco cff's

#### PR validation:

Tested using special workflows

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cvuosalo @kpedro88 Could you approve this PR

**Comment by kpedro88** [comment]
+upgrade

**Comment by cvuosalo** [comment]
Please correct the PR title: "cases", not "ases".

**Comment by cvuosalo** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
