### PR TITLE
Hlt object monitor squashedv2

### PR DESCRIPTION
**Pull request by muell149**
new changes for HLT online DQM

### CODE REVIEW

**Comment by danduggan** [comment]
please test

**Comment by muell149** [comment]
Looking at the merge conflict, it should contain the lines present:

<<<<<<< HEAD
=======
#process.load("DQM.HLTEvF.HLTMonitor_cff")
process.load("DQM.HLTEvF.HLTObjectMonitor_cff")

#process.load("DQM.HLTEvF.HLTMonitorClient_cff")
>>>>>>> cms-sw/refs/pull/9668/head


I don't understand what a rebase would accomplish here or how I would
modify the code to avoid this since it needs to load
process.load("DQM.HLTEvF.HLTObjectMonitor_cff"). How should I proceed?


Cheers,
Charlie

**Comment by danduggan** [comment]
@muell149 <https://github.com/muell149> let's sit down this afternoon and
do it together.

**Comment by danduggan** [comment]
actually i'm not sure why this is causing a conflict, after looking at this in more detail I'd naively think it should be mergeable...

**Comment by deguio** [comment]
-1

**Comment by deguio** [comment]
this PR should be closed
thanks,
F.

**Pull request closed without merging**
