### PR TITLE
CMSSW_7_4_X HCALDQM Updates

### PR DESCRIPTION
**Pull request by vkhristenko**
Tested/Ran runTheMatrix - all tests seem to be fine

Several Updates included:

1) Fix of the crash reported here: https://hypernews.cern.ch/HyperNews/CMS/get/swDevelopment/3234/1.html
Those are sitting inside the HcalDigiMonitor.h/.cc files

2) Addition of new modules:
There is an attempt currently to completely rewrite the HCALDQM CMSSW Plugins. Here, we include:
--- DQM/HcalCommon - Contains Base Classes for new HCALDQM Packages and some utilities
--- DQM/HcalTasks - To separate new(HcalTasks) HCALDQM Packages from the old(HcalMonitorTasks), all the new HCALDQM Tasks now reside in that folder. Provides analogous functionality as HcalMonitorTasks, however adds a lot of new features on top:
HF Phase Scan and HBHE Timing Monitoring wrt TCDS Shifts, etc...
---DQM/Integration/python/test: hcal_dqm python config is comletely new, however old modules are included in the Online DQM Running for now.

3) Addition to the management of the HCAL Status. Based on the plots generated in DQM/HcalTasks/pluging/HcalTimingTask, if there is a significant shift for HBHEabc partitions, the status of HBHE will be set to 0.1 respectively...

4) Addition of the HCALDQM Calibration Application: hcalcalib.... Should be running during the Abort Gap events.

### CODE REVIEW

**Comment by vkhristenko** [comment]
@abdoulline

**Comment by deguio** [comment]
please test

**Comment by vkhristenko** [comment]
A rather stupid question may be - am I supposed now to delete the branch, rebase again and then redo this PR submission??? Cause this branch is now also outdated because of the cmsdqm updates.......?????

**Comment by deguio** [comment]
you can use the same branch and rebase it. this same PR will be updated

**Comment by vkhristenko** [comment]
Going to delete and resubmit. My branches are garbage

**Pull request closed without merging**
