### PR TITLE
fix InnerDeltaPhi for icc

### PR DESCRIPTION
**Pull request by VinInn**
the title says all

### CODE REVIEW

**Comment by VinInn** [comment]
@cmsbuild, please test

**Comment by VinInn** [comment]
@davidlt, could you please verify that icc compiles?

**Comment by davidlt** [comment]
Fixes the issue (tested on `CMSSW_8_0_ICC_X_2016-01-10-2300`).

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/12904	abc0cf8
- technical change (repeats functional implementation of the cropped_asin inside VI_DEBUG)
- jenkins tests pass and ICC cross check is also OK

**Comment by davidlange6** [comment]
+1

**Pull request merged**
