### PR TITLE
Adding BPH skim module (backport from #14775)

### PR DESCRIPTION
**Pull request by kfjack**
Add the newly proposed skim module for BPH PAG into the CMSSW, back port from PR #14775.

### CODE REVIEW

**Comment by fabozzi** [comment]
please test

**Comment by fabozzi** [comment]
+1

**Comment by fabozzi** [comment]
please test

**Comment by fabozzi** [comment]
+1

**Comment by davidlange6** [comment]
@kfjack @fabozzi - could you add the Configuration/PyReleaseValidation changes to this PR? Then we can do the proposed checks

**Comment by fabozzi** [comment]
@davidlange6 @kfjack PR #14912 has all the backports to 80x of matrix updates, including the BPH skim enabled in relval. Is there anything missing there?

**Comment by davidlange6** [comment]
Great - but I’d like to get both PRs combined into one. Can you take care?

**Comment by fabozzi** [comment]
OK, will do

**Comment by fabozzi** [comment]
@davidlange6 @kfjack PR #14912 now includes this PR

**Comment by davidlange6** [comment]
merged in #14912

**Pull request closed without merging**
