### PR TITLE
GEM TnP efficiency plots with bad VFAT masking and Etapartition-wise measurements (backport of #45676, 14_1_X)

### PR DESCRIPTION
**Pull request by jo100sun**
#### PR description:

Backport of (https://github.com/cms-sw/cmssw/pull/45676)[https://github.com/https://github.com/cms-sw/cmssw/pull/45676]. This PR introduces etapartition-wise measurement and VFAT masking of GEM TnP efficiency

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

This PR is backport of (https://github.com/cms-sw/cmssw/pull/45676)[https://github.com/https://github.com/cms-sw/cmssw/pull/45676]. We would like to introduce this changes for upcoming run.

@jshlee @watson-ij

### CODE REVIEW

**Comment by antoniovagnerini** [comment]
backport of #45676

**Comment by antoniovagnerini** [comment]
please test

**Comment by antoniovagnerini** [comment]
+1

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
