### PR TITLE
b-tag GBRForest payloads from GT

### PR DESCRIPTION
**Pull request by ferencek**
This PR enables fetching the b-tag GBRForest payloads from the global tag. In addition, the pfCombinedMVAv2 tagger is now added to PAT jets by default.

@jpata, it appears that the AdaBoost flag for the CombinedMVAv2 taggers was not set correctly. Please check that everything is configured correctly in the PR.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test
[unclear if it makes it to pre7]

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/11685	d4c0c35
- code changes are mostly in line with the descripsion
    - @ferencek it's worth to add that the pfCombinedMVAV2BJetTags is now added to the taggers saved with pat jets
- jenkins test pass and show differences only in plots related to pfCombinedMVAV2BJetTags

Comparing to baseline (CMSSW_7_6_X_2015-10-08-1100) in local tests:
- there is a noticeable change in pfCombinedMVAV2BJetTags (e.g. 251721 DoubleMuon)

all_sign610vsorig_doublemuon251721c_recojetedmreftobaseprodtofloatsassociationvector_pfcombinedmvav2bjettags__reco_obj_data_

and the same just with value>=0: the tagger values now run only up to 1.0
all_sign610vsorig_doublemuon251721c_recojetedmreftobaseprodtofloatsassociationvector_pfcombinedmvav2bjettags__reco_obj_data_169

On the technical side:
- there is apparently 485 kB of additional allocations through DB reads of GBRForest, but this is probably from the change of the origin, which is not easy to get to
- pfCombinedMVAV2BJetTagsAK8 and pfCombinedMVAV2BJetTagsPuppi are now running in the default calls with pat/miniaod steps (a result of the change in  PhysicsTools/PatAlgos/python/producersLayer1/jetProducer_cfi.py) ; there is also a small increase in size of slimmedJets and slimmedJetsPuppi
- there is no significant change in size on disk or CPU time (the new modules take up under 2 ms /evt)

**Comment by ferencek** [comment]
@slava77, I updated the PR description and mentioned the addition of pfCombinedMVAV2BJetTags.

@jpata, can you please comment on the discriminator changes. What was in the release before this PR was not producing values between -1 and 1. However, if I switched back to just using TMVA (no GBRForest), I would get values between -1 and 1. So it appeared that the GBRForest AdaBoost flag was not set correctly resulting in discriminator values that went beyond -1 and 1. Now the GBRForest output matches with that from TMVA.

**Comment by ferencek** [comment]
@monttj, can you please sign this PR. Thanks

**Comment by jpata** [comment]
> @jpata, it appears that the AdaBoost flag for the CombinedMVAv2 taggers was not set correctly. Please check that everything is configured correctly in the PR.
@ferencek you are completely correct, the AdaBoost flag should be changed to `False` as you did. I didn't manage propagate this. Sorry for the delay in answering, I had not seen the original mail(s).

**Comment by ferencek** [comment]
@jpata, thanks for the reply. At this point there are no outstanding issues and the test errors appear unrelated to this PR.

**Comment by smuzaffar** [comment]
please test

**Pull request merged**
