### PR TITLE
Cleanup: remove unused ME0MuonTrackCollProducer

### PR DESCRIPTION
**Pull request by watson-ij**
#### PR description:

This class is unused and relates to ME0 which we plan to eventually
remove from CMSSW in favor of "GE0".

@jshlee 

#### PR validation:

Checked runTheMatrix.py still runs with workflow -w upgrade -l 24821.0 ; 2026D54+TenMuE

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by perrotta** [comment]
`me0Associator` is also imported by RecoMuon/MuonIdentification/test/testME0MuonAnalyzer_Example.py

**Comment by dildick** [comment]
@watson-ij Could you also clean-up the test files
* `RecoMuon/MuonIdentification/test/testME0MuonAnalyzer_Example.py`
* `RecoMuon/MuonIdentification/test/testME0MuonAnalyzer_fullreco.py`

Thanks.

**Comment by jshlee** [comment]
@watson-ij I think all of #11398 can be removed.

**Comment by watson-ij** [comment]
Okay, I will go through the PR from @jshlee  and see if I can figure out how much can be pulled out without affecting the current setup.

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
+1
- Unused ME0 related code and test scripts removed from CMSSW
- Jenkins tests pass: the removals did not cause any effect on the outputs, confirming as such that it is not in use any more

**Comment by kpedro88** [comment]
+upgrade

**Comment by silviodonato** [comment]
+1

**Pull request merged**
