### PR TITLE
Backport StoredMergeableRunProductMetadata

### PR DESCRIPTION
**Pull request by srimanob**
To replace https://github.com/cms-sw/cmssw/pull/25213

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by fabiocos** [comment]
@srimanob as 10_2_X is not expected to be part of the ultra-legacy reprocessing, could you please clarify the usefulness of this PR?

**Comment by srimanob** [comment]
@fabiocos This PR is for 9_4_X branch.

**Comment by fabiocos** [comment]
@srimanob you are correct, the question remains the same though

**Comment by srimanob** [comment]
@fabiocos 
As confirm by TSG, the 2018 menu will be able to run on 10_4, 10_5, so we should not need this PR for 10_2_X for 2018 UL. However, since it's effort-less to make, maybe we can add this to 10_2. What do you think?

**Comment by fabiocos** [comment]
@srimanob as you say it looks (almost) effortless, but what is the purpose? I do not want to make a big noise about this, but there are many backports we could do with a little effort (for each of them separately), but is it really needed? In case we may do it when the use case pops up I would say

**Comment by srimanob** [comment]
@fabiocos 
Sure, no need for 10_2 this time. Only 8_0_X and 9_4_X are needed.

**Comment by davidlange6** [comment]
9_4 or 9_2?

**Comment by srimanob** [comment]
@davidlange6 
9_2 was used for data, but we always use 9_4 for MC since the beginning (Fall17 campaign). Should we run UL with trigger in 9_2 instead?

**Comment by fabiocos** [comment]
+1

**Pull request merged**
