### PR TITLE
pp RECO with HI photon isolation using "customise" option

### PR DESCRIPTION
**Pull request by ttrk**
This PR adds the HI-style isolation to the pp photon sequences. Heavy Ions needs this information during the pp reference run in order to do proper comparisons to PbPb results, where this information will be used for photon ID.

It will add two instances of the HIPhotonIsolation ValueMap, one for "std" photons and another for GED photons to the RECO and AOD event content for pp events.
This is urgent, as the pp reference run is approaching soon.

As pointed by @slava77  in the RECO meeting on 29.10.2015, this PR is planned to go into 75X.

Upon feedback on the previous PR, this PR implements "customisation" approach.

@richard-cms 
@yenjie

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

@davidlange6 I see the last auto-merge 75X->76X on Oct 18. Did we stop since then?
(I think yes, but I'm not sure)

**Comment by richard-cms** [comment]
I think Jenkins had a hiccup here, https://cmssdt.cern.ch/jenkins/job/ib-any-integration/9393/console is inaccessible.

**Comment by richard-cms** [comment]
Is there any more information or changes you'd like to see from me or @ttrk? 

Should we include our customization in postLS1Customs in this PR, or in a future one?

**Comment by slava77** [comment]
@richard-cms I think this function can be included in customise_Reco:
https://github.com/cms-sw/cmssw/blob/CMSSW_7_5_4/SLHCUpgradeSimulations/Configuration/python/postLS1Customs.py#L761

If you propagate this PR to 76X, this modification of customise_Reco should not be propagated.

**Comment by ttrk** [comment]
@slava77 I inserted the relevant function into the pointed position in SLHCUpgradeSimulations/Configuration/python/postLS1Customs.py .

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by civanch** [comment]
+1

**Comment by slava77** [comment]
... testing ...

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/12185	 cef7230
- code looks ok
- jenkins tests pass and comparisons with baseline show no differences
- new modules appear in run2 data and MC processing and take under 40ms/event based on 134.802 (2015C DoubleEG)
```
       added      +0.16%         0.00 ms/ev ->        17.81 ms/ev photonIsolationHIProducerppGED
       added      +0.11%         0.00 ms/ev ->        12.08 ms/ev photonIsolationHIProducerpp
       added      +0.05%         0.00 ms/ev ->         5.18 ms/ev islandBasicClusters
```
- new products appear in pp run2 RECO: increasing the size by ~0.5%
    - recoHIPhotonIsolationedmValueMap_photonIsolationHIProducerpp
    - recoHIPhotonIsolationedmValueMap_photonIsolationHIProducerppGED
    - recoCaloClusters_islandBasicClusters_islandBarrelBasicClusters
    - recoCaloClusters_islandBasicClusters_islandEndcapBasicClusters
- new products appear in pp run2 AOD: increasing the size by ~0.2%
    - recoHIPhotonIsolationedmValueMap_photonIsolationHIProducerpp
    - recoHIPhotonIsolationedmValueMap_photonIsolationHIProducerppGED

**Comment by slava77** [comment]
@ttrk 
please make a 76X PR with *only* 
- RecoHI/Configuration/python/customise_PPwithHI.py 
- RecoHI/HiEgammaAlgos/python/photonIsolationHIProducer_cfi.py 
(no modifications to SLHCUpgradeSimulations/Configuration/python/postLS1Customs.py )

**Comment by davidlange6** [comment]
+1

**Pull request merged**
