### PR TITLE
[HGCal] Shrinking Layer Clustering internal data structures - backport to 11_1_X 

### PR DESCRIPTION
**Pull request by felicepantaleo**
#### PR description:
backport to 11_1_X of #30753

### CODE REVIEW

**Comment by felicepantaleo** [comment]
@cmsbuild please test

**Comment by felicepantaleo** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
backport of #30753

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/30757	0295d4f 
- changes in the code are the same as in #30753 
- jenkins tests pass and comparisons with the baseline show no (relevant) differences

This is a technical update, just cleaning up some memory hoarding (or/and for-peak allocation)

**Comment by srimanob** [comment]
@silviodonato @slava77 
I've done the test on full prod-like reco sequence, seems we are at 14 GB now which is a good sign.

**Comment by srimanob** [comment]
@silviodonato 
As mentioned in email "Converging on HLT TDR Production", please feel free to build the release. We will then can set the pilot from the new release. Thanks.

**Comment by silviodonato** [comment]
+1

**Pull request merged**
