### PR TITLE
Fix in TSGForOI muons - 92X

### PR DESCRIPTION
**Pull request by silviodonato**
93X version: #19948
-----------------------------
Running ` hltIntegrationTests /dev/CMSSW_9_2_0/GRun/V94 -i root://cms-xrd-global.cern.ch//store/data/Run2017B/MuonEG/RAW/v1/000/297/469/00000/C0653517-2D59-E711-91CD-02163E0118F3.root -x "--globaltag 92X_dataRun2_HLT_v4" -x "--l1-emulator uGT --l1 L1Menu_Collisions2017_v2_m6_full_xml" -j16 -n100 -d hltintegrationTestV94 &>logIntegrationDataV94 &`
we found inconsistencies between running full HLT menu and single HLT path.

This is due to some non-const members of TSGForOI that are not initialized at each event.

This PR is very important for the upcoming V2.1 menu.

### CODE REVIEW

**Comment by silviodonato** [comment]
please test

**Comment by Martin-Grunewald** [comment]
type bug-fix

**Comment by Martin-Grunewald** [comment]
urgent

**Comment by slava77** [comment]
@cmsbuild please test

it looks like for this PR as well jenkins lost the build job request

**Comment by silviodonato** [comment]
please test

**Comment by silviodonato** [comment]
please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/19947	74e5166
- TSGForOI is now global and has the same starting state event by event, which was not the case before. Changes are the same as in the 93X version.
- jenkins tests pass [there are no 2017 data workflows in jenkins in 2017 where changes would become noticeable]
- relying on pre-submission tests by @silviodonato and also test results made in 93X, which included 2017 workflows

**Comment by davidlange6** [comment]
+1

**Pull request merged**
