### PR TITLE
Update validation for RPC hit reconstruction

### PR DESCRIPTION
**Pull request by slowmoyang**
#### PR description:
This PR drops plots that are no longer used in the release validation procedure for RPC hit reconstruction. The PR also simplifies the directory path where plots related to RPC hit reconstruction are stored.

@jhgoh @mileva @mrcthiel

#### PR validation:
The changes have been reviewed in [the last RPC DPG meeting](https://indico.cern.ch/event/1443185/#1-updates-on-validation-sw-for). The PR has been tested with `runTheMatrix.py -w upgrade -l 12811.0`.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:
We intend to backport this PR to active release cycles.

### CODE REVIEW

**Comment by tjavaid** [comment]
please test

**Comment by tjavaid** [comment]
+1

- spurious differences seen from unstable WF `12834.7` (open issue #39803 )
- @slowmoyang , would you like to make backport PR if needed?

**Comment by mandrenguyen** [comment]
+1

**Comment by slowmoyang** [comment]
@tjavaid Yes, I'd like to make a backport PR to 14_0_X. I plan to do it within a day.

**Pull request merged**
