### PR TITLE
Validation/Geometry: CleanUp

### PR DESCRIPTION
**Pull request by vargasa**
Removing old _cfg files. Functionality has been integrated into runP_Tracker_cfg.py:

```
	for t in {'BeamPipe','Tracker','PixBar','PixFwdMinus','PixFwdPlus', \
	'TIB','TOB','TIDB','TIDF','TEC','TkStrct','InnerServices'}; \
	do cmsRun runP_Tracker_cfg.py geom=XYZ label=$t; done
```

Read: https://github.com/cms-sw/cmssw/pull/17210

### CODE REVIEW

**Comment by andrius-k** [comment]
please test

**Comment by cvuosalo** [comment]
+1

**Comment by andrius-k** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
