### PR TITLE
DNN-based Tau-Id discrimians (102X)

### PR DESCRIPTION
**Pull request by mbluj**
This pull request provides two new DNN-based Tau-Ids, DeepTau and DPFTau, to be produced for pat::Taus with MiniAOD.
It is a backport of #25016 to 102X for analyses based on 2018 data and detailed description can be found therein.

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
backport of #25016

**Comment by mbluj** [comment]
@MRD2F could you please sync this with master/104X and 102X where possible? Thanks!

**Comment by MRD2F** [comment]
@mbluj Yes, I'll start with that

**Comment by perrotta** [comment]
please test

**Comment by mbluj** [comment]
Recent updates are to sync this backport with #25016 + other small fixes as GlobalTag for 102X.

**Comment by perrotta** [comment]
+1
- New DNN-based Tau-Id discriminants are made available for analyses:
   - they don't run in official central workflows
   - additional training files also need to be included as externals
- (Same comment as in #25016) Memory footprint is still rather large (O(100MB/evt)) , but nonetheless deemed acceptable for the usage this code is intended to: if and when it will be requested to be included in some central sequence meant to production some further assessment and study should be performed, as well as some deeper investigation of the timing performance (which from the first results does not seem to be a concern, anyhow)
- Since central sequences used in production are not touched by this PR, its possible backport has no counterindications
- Jenkins tests pass and show no differences

**Comment by smuzaffar** [comment]
hold
this PR history contains large data files.

**Comment by perrotta** [comment]
@smuzaffar , if I understand it correctly, your request in practice is to rebase these pull requests: correct?

**Comment by kandrosov** [comment]
@smuzaffar The PR #25016 has already been merged. It should include the same big files in history as in this PR. Therefore, merging this PR should not consume more space, since the big files are already part of the history in the central repository.
To solve the problem, one can merge this PR (and similar backport PR in 94X) and then manually remove the big files from the history in the central repository.

**Comment by smuzaffar** [comment]
@kandrosov, It was mistake on our part that #25016 was merged with those big files in the history and now we get warnings like these [a]. We are going to rebase master branch to clean the history and remove ref to these big files.

For this back ports PR I would suggest to rebase ( and re-write the history , see detaile here https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History and edit the commits which add these files)

[a]
```
remote: warning: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
remote: warning: See http://git.io/iEPt8g for more information.
remote: warning: File RecoTauTag/RecoTau/data/DPFIsolation_2017v0.pb is 50.10 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB
remote: warning: File RecoTauTag/RecoTau/data/deepTau_2017v1_20L1024N.pb is 80.98 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB
```

**Comment by smuzaffar** [comment]
I would suggest to clean the history and remove ref to these files [a]. These were added and later deleted in the PR. 

ERROR:  RecoTauTag/RecoTau/data/DPFIsolation_2017v1.pb ['Added', 'Deleted']
ERROR:  RecoTauTag/RecoTau/test/runTauIdMVA.py ['Added', 'Deleted']
ERROR:  RecoTauTag/RecoTau/data/deepTau_2017v1_20L1024N.pb ['Added', 'Deleted']
ERROR:  RecoTauTag/RecoTau/python/DPFIsolation_cfi.py ['Added', 'Deleted']
ERROR:  RecoTauTag/RecoTau/python/DeepTauId_cfi.py ['Added', 'Deleted']
ERROR:  RecoTauTag/RecoTau/data/DPFIsolation_2017v0.pb ['Added', 'Deleted']
ERROR:  RecoTauTag/RecoTau/python/runTauIdMVA.py ['Added', 'Modified', 'Deleted']

**Comment by mbluj** [comment]
Hello,
as I never tried to rewrite git history (which sounds danger) I would like ask for confirmation if I got correctly what should be done. What I understand is following
1.  I checkout the PR'ed branch from the repository from which I PR'ed to official CMSSW, e.g. like this
```
git cms-init -X repo-name
git checkout branch-name
```
2. Then, I clean history of the branch as follows
```
git filter-branch --tree-filter 'rm -f file1-to-remove, file2-to-remove ... ' branch-name
```
3. Finally, I should push the branch with modified history to remote (will it be possible?). 

Is it what you mean?
This should be repeated also for 94X backport.

**Comment by fabiocos** [comment]
@mbluj as this and the 9_4_X are backports with no special review in the middle of the history, unless keeping the long list of commits has a value for you I think it might be simpler to follow the advice https://cms-sw.github.io/faq.html#how-do-i-collapse-multiple-commits-into-one 

@smuzaffar this is what we were discussing as a possibility to trim commit histories, right?

**Comment by mbluj** [comment]
@fabiocos @smuzaffar I have no problem with rewriting a full history - it takes quite some time, but I can do it in background. However, I would like to understand if procedure I described is correct one (to not mess things).

**Comment by smuzaffar** [comment]
unhold
I am happy with the squash

**Comment by fabiocos** [comment]
@mbluj I can just squash myself the history at merge time, if that is ok for you

**Comment by mbluj** [comment]
> 
> 
> @mbluj I can just squash myself the history at merge time, if that is ok for you

Yes, great! Thank you.

**Comment by fabiocos** [comment]
@smuzaffar if I add "+1" will this confuse the bot, or trigger any further action on his side? Just to update the label status for the record..

**Comment by smuzaffar** [comment]
it should be fine to do +1 now. Bot should only update the labels.

**Pull request merged**
