### PR TITLE
Push_back 0th weight manually, prevent duplication of PS weights in P8.30x

### LINKED ISSUE #36705: 134 PS weights instead of 46 in Pythia 8.3
Dear all,
producing GEN events in e.g. CMSSW_12_1_0 or CMSSW_11_3_4 (P8.3) I see that the weight vector per event, i.e. 
Events->Scan("GenEventInfoProduct_generator__GEN.obj.weights_")
has 134 entries, while the header contains the correct info. I.e. 
LuminosityBlocks->Scan("GenLumiInfoHeader_generator__GEN.obj.weightNames_","","colsize=60")
gives me 46 PS weights as expected. 
@SiewYan @mkirsano is one of you available to check what goes wrong?  I didn't run P8 standalone yet.  
I used this fragment for testing: 
https://www.desy.de/~agrohsje/hidden/PPD-Run3Autumn21wmLHEGS-00001-fragment.py
Cheers, Alexander.

### PR DESCRIPTION
**Pull request by SanghyunKo**
#### PR description:

The weight storage logic in Pythia8 had been changed since 8.30x version, causing the duplication of PS weights in CMS. This PR prevents weight duplication by setting `Pythia8ToHepMC::set_store_weights(false)` and keeps the old weight structure the same as in UL by push_back 0th weight manually. Fixes #36705

#### PR validation:

Tested with the workflow `555`,  `556`

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

This PR is intended for 12_4_X (otherwise the Pythia8 MC will contain duplicated PS weights in the weight containers)

### CODE REVIEW

**Comment by SiewYan** [comment]
please test

**Comment by qliphy** [comment]
please test

**Comment by SiewYan** [comment]
please test workflow 555, 556

**Comment by SiewYan** [comment]
@SanghyunKo thank you very much for the PR!

I detect a fail comparison for wf 556, on the number of gen weights [*]: ```wgtVal``` [**], seemingly the number of event weights reduced. Is this the expected observation from your private test on wf 556?

[*] https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_5_X_2022-05-22-2300+7f0994/50439/556.0_TTbar_NLO_Pow_13TeV_py8+TTbar_Pow_LHE_13TeV+Hadronizer_TuneCP5_13TeV_powhegEmissionVeto2p_pythia8+HARVESTGEN2/Generator__GenWeight_wgtVal.png
[**] https://github.com/cms-sw/cmssw/blob/291fef21c554f7a21930b966c36449e837e76fd7/Validation/EventGenerator/plugins/GenWeightValidation.cc#L133-L134

**Comment by SanghyunKo** [comment]
@SiewYan yes, in fact this is exactly what this PR intended for - before we have 1340 entries (= 134 weights x 10 events) while after 460 entries (46 weights x 10 events) where 134 is duplication (= 44 x 3 + 2) which should be 46 (= 44 + 2) instead

**Comment by SiewYan** [comment]
+1

Thanks for the clarification! the PR looks fine for me then.

**Comment by perrotta** [comment]
+1

**Pull request merged**
