### PR TITLE
Minor enhancements to special geometry comparison test

### PR DESCRIPTION
**Pull request by cvuosalo**
`runDDDvsDBGeometryValidation.sh` is a special test to be run by experts to compare the geometry in a local database and the Conditions database. One test in the script is to compare the concatenated geometry XML files in each database. These files may actually differ, or they may only appear to differ because of different ordering of some of the content of the files.

I added a two more tests to the script to try to help the expert determine whether there are real differences in the two geometry XML files or whether the apparent differences are due to minor re-ordering. The overall problem of definitively determining whether two big XML files are functionally identical even if their parts are in different orders is still not solved, though the enhancements in this PR are a step in that direction. Maybe this issue can be fully resolved in a later PR.

One file in this PR is unrelated to the others. `splitExtended2021Database.sh` is used for creating payloads. The DB group requested that I update the command used in the script from 
`conddb_import`, which is intended to be decommissioned, to `conddb`.

#### PR validation:

The scripts run and produce informative output. They have no effect on production workflows or unit tests.

`splitExtended2021Database.sh` continues to work and create payloads. With the change in command, I noticed that the comment field in the payload changed. For example, the old `conddb_import` created the following payload. Note the Description field.
```
Name                    TimeType  ObjectType     Synchronisation  EndOfValidity  Insertion_time              Description                                                             
----------------------  --------  -------------  ---------------  -------------  --------------------------  ---------------------------------------------------------------------   
TKRECO_Geometry_111YV1  Run       PGeometricDet  any              -1             2020-03-02 17:49:31.613191  Created copying tag TKRECO_Geometry_111YV1 from sqlite_file:myfile.db   
```
The new `conddb` created almost the same payload:
```
Name                    TimeType  ObjectType     Synchronisation  EndOfValidity  Insertion_time              Description   
----------------------  --------  -------------  ---------------  -------------  --------------------------  -----------   
TKRECO_Geometry_111YV1  Run       PGeometricDet  any              -1             2020-03-21 02:58:08.136170  New Tag       
```
Note that Description field is different. I assume this difference is harmless.

No backport is needed for this PR.

### CODE REVIEW

**Comment by cvuosalo** [comment]
@ggovi Please check `splitExtended2021Database.sh` and let me know if I have used the correct arguments for the new command. They seem to work correctly as far as I could tell.

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by jfernan2** [comment]
+1

**Comment by ggovi** [comment]
+1

**Comment by cvuosalo** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
