### PR TITLE
[9_4_X] DeepDoubleCvL and DeepDoubleCvB tagger integration

### PR DESCRIPTION
**Pull request by andrzejnovak**
Backport of #24918

Dependent on cms-data/RecoBTag-Combined#19

### CODE REVIEW

**Comment by andrzejnovak** [comment]
Updated with changes to requested in #25370

**Comment by andrzejnovak** [comment]
@slava77 can we run test on this now?

**Comment by perrotta** [comment]
@cmsbuild please test with cms-sw/cmsdist#4549

**Comment by slava77** [comment]
@cmsbuild please test with cms-sw/cmsdist#4549

try again, assuming the last failure was transient
```
13:01:14 error: RPC failed; curl 18 transfer closed with outstanding read data remaining
13:01:14 fatal: The remote end hung up unexpectedly
```

**Comment by slava77** [comment]
the build error is repeatable.

@smuzaffar @mrodozov 
please check what is happening.
Thank you.

**Comment by smuzaffar** [comment]
@cmsbuild please test with cms-sw/cmsdist#4549

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/25371	8a281a6 
- code changes are in line with the PR description and the follow up review; the backport is consistent with the master version (except for the part that the taggers are not enabled in the default/production version of the workflows).
- jenkins tests pass and comparisons with the baseline show no differences

@fabiocos this needs cms-sw/cmsdist#4549

**Comment by andrzejnovak** [comment]
@fabiocos Is there anything else holding this up?

**Comment by fabiocos** [comment]
please test

**Comment by smuzaffar** [comment]
code checks

**Comment by andrzejnovak** [comment]
@slava77 @perrotta @fabiocos @ferencek  When can we expect this to be included in a release? The taggers are supported by BTV and we'd like to have a stable rel to build commissioning and SF measurement against. The no change policy should be satisfied.

**Comment by slava77** [comment]
@andrzejnovak 
this PR was merged on Jan 9.
There was a general push to move the analysis to 10_2_X.
This is the reason for no 9_4_X release so far (since 9_4_12 released on Nov 21).

**Comment by slava77** [comment]
BTW, there will likely be a new 94X for other purposes soon (fastsim fixes).
So, this should fit your needs, I guess.

**Pull request merged**
