### PR TITLE
Add k892 and bc 2s

### PR DESCRIPTION
**Pull request by alberto-sanchez**
Adding particles to prune list, to allow simulation studies.

### CODE REVIEW

**Comment by perrotta** [comment]
Out of curiosity: where are taken from the codes for Bc(2S) and Bc(2S)*?
Apparently not from the list in  https://cdcvs.fnal.gov/redmine/projects/heppdt/wiki/2006_List_of_mesons, or other lists that can be linked from the pdg pages...

**Comment by alberto-sanchez** [comment]
From Monte Carlo particle numbering scheme, and in consultation with Steve Mrenna, both conclude
that 100541  is  for Bc(2^1S_0)+  and 100543   for Bc(2^3S_1)+

**Comment by perrotta** [comment]
+1
- Added particle generator codes to the pruned Gen particle list in PatAlgos: kind of technical and not really relevant for reco
- Jenkins tests pass

**Comment by fabiocos** [comment]
@alberto-sanchez could you please clarify the reason for this update, who asked for it, and how was it checked?

**Comment by alberto-sanchez** [comment]
@fabicos, we dump the content of the gen part and  checked the correct mom and daugthers. For bc2s is straightforward. For 323 the analysis code was run in a test file, making sure we are able to trace the signal and background process. We are planning a report on the xPOG meeting. See https://docs.google.com/presentation/d/1u-xH4qKH_r5LEw4HEXaB7wbR5FL7mXUyWnLubGsiBHU/edit?usp=drivesdk
The current users are Juan P. Fernandez and my analysis team.

**Comment by alberto-sanchez** [comment]
@fabiocos we  are in the process, the xPOG meeting is next week. 
About the tests, yet we have done the relevant tests.

**Comment by alberto-sanchez** [comment]
After discussion in xPOG chat, we will try to optimize the inclusion of K*+(892). In order to reduce the size. Do not merge yet.

**Comment by fabiocos** [comment]
hold

@alberto-sanchez please let me know when this is ready again to go

**Comment by alberto-sanchez** [comment]
@peruzzim @fgolf we have tested that just keep the K*+/- in acceptable and dropping daugthers from prune (they are available in packed list) will reduce the size in 1 order of magnitude. e.g. now the miniaod just increase by 0.1%

**Comment by alberto-sanchez** [comment]
please test

**Comment by alberto-sanchez** [comment]
@fabiocos , this should be ready to go, once signed

**Comment by fabiocos** [comment]
@peruzzim @fgolf I understand this is ok for you, comment otherwise

**Comment by peruzzim** [comment]
Based on the reported size increase, that is now much smaller than in the first version, XPOG is ok with this addition.

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Pull request merged**
