### PR TITLE
NominalCollision2015 beamspot: migration of SIM and RECO BS

### PR DESCRIPTION
**Pull request by franzoni**
- SIM beamspot updated for postLs1: pp => NominalCollision2015 ; HI => RealisticHI2011Collision
- GT's changed to provide RECO postLs1 beamspot; this ensures that the matrix for postLs1 is consistent when re-doing GEN-SIM
- GEN-SIM recycle updated to point to  postLs1 beamspot; this ensures that the matrix for postLs1 is consistent when re-cycling existing GEN-SIM
- various updates to names of GEN-SIM samples, following the py6 => py8 migration

### CODE REVIEW

**Comment by franzoni** [comment]
+1
summary of full-matrix tests: https://hypernews.cern.ch/HyperNews/CMS/get/swReleases/4153/1/2/1/1.html

**Comment by franzoni** [comment]
we need to keep an eye on the questions asked in #6982
That problem won't generate crashes in the matrix when operated recycling gen-sim. Once the questions will be answered, it may be easy to address.

**Comment by ktf** [comment]
please test

**Comment by diguida** [comment]
+1

**Pull request merged**
