### PR TITLE
Updating MC GT for HeavyIon production, Data GT for 2015 Run2 EOY Re-Reco, HLT GT for HeavyIon data taking.

### PR DESCRIPTION
**Pull request by diguida**
# Summary of Global Tag changes
## RunII Simulation
- Heavy Ion scenario: 75X_mcRun2_HeavyIon_v10: As 75X_mcRun2_HeavyIon_v9 with the following changes:
  - updated centrality table for HFtowers in 200 bins
  - updated underlying event table with latest estimations from PbPb first collisions
  - updated JEC with HI tracking
  - updated L1T menu with the version used in PbPb collisions
  - updated strip bad channels with the payload with TOB L3 FED 434 and 439 IN, computed using 25 ns Run 254790.
## RunI Data
- HLT processing: 75X_dataRun1_HLT_frozen_v5: As 75X_dataRun1_HLT_frozen_v4 (snapshot time set to 2015-12-02 11:30:00 UTC) with the following changes:
  - added HCAL negative energy filter record
  - revert BTag MVA to the values of 74X in order to keep HLT performance on data
  - revert PF hadron calibration to the values of 74X in order to keep HLT performance on data.
- Offline processing: 75X_dataRun1_v11: As 75X_dataRun1_v10 with the following changes:
  - updates for 2015 EOY data re-reco (backported from 76X)
    - lumi based beamspot
    - Tracker alignment, APE and surface deformations
    - DT, CSC, and muon GPR alignment
    - DT Vdrift and Ttrig
    - CSC electronics calibrations
    - SiStrip bad channel and particle gain
    - Hcal gains and response corrections
    - Castor local reco calibration for 0T re-reco
    - Ecal IC, AdcToGeV, time calibrations, alignment
    - ES intercalibration
  - merge Run1 and Run2 tags for Centrality tables in HF Towers.
## RunII Data
- HLT processing: 75X_dataRun2_HLT_frozen_v7: As 75X_dataRun2_HLT_frozen_v5 (snapshot time set to 2015-11-20 17:40:00 UTC) with the following changes:
  - added HCAL negative energy filter record.
- HLT HeavyIon processing: 75X_dataRun2_HLTHI_frozen_v4: As 75X_dataRun2_HLTHI_v2 (snapshot time set 2015-11-19 22:15:00 UTC) to with the following changes:
  - updated tag for AK4Calo HLT JEC for pp reference run at 5 TeV and HI run. The first IOV contains the payload computed with ECAL multifit on top of RECO.
- Offline processing: 75X_dataRun2_v11: As 75X_dataRun2_v10 with the following changes:
  - updates for 2015 EOY data re-reco (backported from 76X)
    - lumi based beamspot
    - Tracker alignment, APE and surface deformations
    - DT, CSC, and muon GPR alignment
    - DT Vdrift and Ttrig
    - CSC electronics calibrations
    - SiStrip bad channel and particle gain
    - Hcal gains and response corrections
    - Castor local reco calibration for 0T re-reco
    - Ecal IC, AdcToGeV, time calibrations, alignment
    - ES intercalibration
  - merge Run1 and Run2 tags for Centrality tables in HF Towers.

### CODE REVIEW

**Comment by diguida** [comment]
@Martin-Grunewald I assume the HeavyIon RelVal MC tests will fail with incompatible HLT/L1T menus.
Please let me know it you have a working version of the trigger tables compatible with the PbPb L1T menu.

**Comment by mmusich** [comment]
@diguida @Martin-Grunewald, if this is the case, the same holds true for #12636

**Comment by Martin-Grunewald** [comment]
@diguida @mmusich 
Yes we need to wait until the PbPb menu for the release and to be used for MC is ready.

**Comment by diguida** [comment]
@Martin-Grunewald @mmusich indeed, HI MC RelVals fail:

````
git: (from-CMSSW_7_5_X_2015-11-30-2300 %) $ runTheMatrix.py -n -i all | grep HI
140.0  HydjetQ_MinBias_2760GeVINPUT+DIGIHI2011+RECOHI2011+HARVESTHI2011
140.1  QCD_Pt_80_120_13_HIINPUT+DIGIHI+RECOHI+HARVESTHI
140.2  PhotonJets_Pt_10_13_HIINPUT+DIGIHI+RECOHI+HARVESTHI
140.3  ZMM_13_HIINPUT+DIGIHI+RECOHI+HARVESTHI
140.4  ZEEMM_13_HIINPUT+DIGIHI+RECOHI+HARVESTHI
140.51 RunHI2010+REPACKHID+RECOHID11St3+HARVESTDHI
140.52 RunHI2010+RECOHID10+RECOHIR10D11+HARVESTDHI
140.53 RunHI2011+RECOHID11+HARVESTDHI
145.0  HydjetQ_MinBias_5020GeVINPUT+DIGIHI+RECOHI+HARVESTHI
300.0  Pyquen_GammaJet_pt20_2760GeV+DIGIHIMIX+RECOHIMIX+HARVESTHI
301.0  Pyquen_DiJet_pt80to120_2760GeV+DIGIHIMIX+RECOHIMIX+HARVESTHI
302.0  Pyquen_ZeemumuJets_pt10_2760GeV+DIGIHIMIX+RECOHIMIX+HARVESTHI
1004.0 RunHI2011+TIER0EXPHI+ALCAEXPHI+ALCAHARVD1HI+ALCAHARVD2HI+ALCAHARVD3HI
git: (from-CMSSW_7_5_X_2015-11-30-2300 %) $ runTheMatrix.py -l 140.1,140.2,140.3,140.4,145.0 -i all
...
140.1_QCD_Pt_80_120_13_HI+QCD_Pt_80_120_13_HIINPUT+DIGIHI+RECOHI+HARVESTHI Step0-PASSED Step1-FAILED Step2-NOTRUN Step3-NOTRUN  - time date Wed Dec  2 14:33:24 2015-date Wed Dec  2 14:32:23 2015; exit: 0 16640 0 0
140.2_PhotonJets_Pt_10_13_HI+PhotonJets_Pt_10_13_HIINPUT+DIGIHI+RECOHI+HARVESTHI Step0-DAS_ERROR Step1-NOTRUN Step2-NOTRUN Step3-NOTRUN  - time date Wed Dec  2 14:32:32 2015-date Wed Dec  2 14:32:24 2015; exit: 1 0 0 0
140.3_ZMM_13_HI+ZMM_13_HIINPUT+DIGIHI+RECOHI+HARVESTHI Step0-DAS_ERROR Step1-NOTRUN Step2-NOTRUN Step3-NOTRUN  - time date Wed Dec  2 14:32:37 2015-date Wed Dec  2 14:32:28 2015; exit: 1 0 0 0
140.4_ZEEMM_13_HI+ZEEMM_13_HIINPUT+DIGIHI+RECOHI+HARVESTHI Step0-PASSED Step1-FAILED Step2-NOTRUN Step3-NOTRUN  - time date Wed Dec  2 14:33:32 2015-date Wed Dec  2 14:32:33 2015; exit: 0 16640 0 0
145.0_HydjetQ_MinBias_5020GeV+HydjetQ_MinBias_5020GeVINPUT+DIGIHI+RECOHI+HARVESTHI Step0-PASSED Step1-FAILED Step2-NOTRUN Step3-NOTRUN  - time date Wed Dec  2 14:34:22 2015-date Wed Dec  2 14:32:37 2015; exit: 0 16640 0 0
3 0 0 0 tests passed, 2 3 0 0 failed
````
But, the error is not related to conditions or menu, but to missing products in the DIGI step:
````
----- Begin Fatal Exception 02-Dec-2015 14:33:20 CET-----------------------
An exception of category 'ProductNotFound' occurred while
   [0] Processing run: 1 lumi: 1 event: 1
   [1] Running path 'digitisation_step'
   [2] Calling event method for module GenHIEventProducer/'heavyIon'
Exception Message:
Principal::getByToken: Found zero products matching all criteria
Looking for type: CrossingFrame<edm::HepMCProduct>
Looking for module label: mix
Looking for productInstanceName: generator

   Additional Info:
      [a] If you wish to continue processing events after a ProductNotFound exception,
add "SkipEvent = cms.untracked.vstring('ProductNotFound')" to the "options" PSet in the configuration.

----- End Fatal Exception -------------------------------------------------
````

**Comment by diguida** [comment]
@Martin-Grunewald now running `addOn` tests to see other nice features there.

**Comment by diguida** [comment]
As discussed in #12636 we proceed here with the HI MC GT, in order to understand the issues and fix them. We assume therefore that the menu and the fixes here will be forward-ported to latest cycles.

**Comment by Martin-Grunewald** [comment]
HIon HLT menu: https://github.com/cms-sw/cmssw/pull/12644

**Comment by diguida** [comment]
@Martin-Grunewald @perrotta I wrote a comment with the git commands needed for cherry-picking this commit: https://github.com/cms-sw/cmssw/pull/12644#issuecomment-161356516 and https://github.com/cms-sw/cmssw/pull/12644#issuecomment-161357534

**Comment by diguida** [comment]
As explained in the meeting, I am making sure we do not use the special keys in `autoCondHLT.py` for `runTheMatrix`

**Comment by diguida** [comment]
Here it is the PR removing specific TSG customisations for HI MC: #12648 RelVal steps should use the keys provided by AlCa in MC.

**Comment by diguida** [comment]
-1
superseded by #12644

**Comment by hengne** [comment]
@diguida i meet the same crash in mixing module, which for sure not related to this PR.

**Comment by diguida** [comment]
@hengne @mmusich the crash refers to the following wf `140.{1-4}, 145.0`. This also happens in standard IB RelVal, as explained in https://github.com/cms-sw/cmssw/pull/12644#issuecomment-161406179

**Pull request closed without merging**
