### PR TITLE
Fix typo in the RelMon category 

### PR DESCRIPTION
**Pull request by tvami**
#### PR description:

Extremely simple, cosmetic PR to fix a typo in the Jenkins tests: "skiped" --> "skipped"

#### PR validation:

Code compiles

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

This is not a backport, and no backport is needed.

### CODE REVIEW

**Comment by tvami** [comment]
type bug-fix

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by jfernan2** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
