### PR TITLE
Cleaning of TrajectoryCleanerESProducer in HLT directory

### PR DESCRIPTION
**Pull request by silviodonato**
Cleaning of TrajectoryCleanerESProducer in the whole HLT directory.
This does not have any effects on the HLT trigger results.

See #21434

### CODE REVIEW

**Comment by silviodonato** [comment]
please test

**Comment by Martin-Grunewald** [comment]
@silviodonato 
This should be done in ConfDB (master and affected subtables!) as well, otherwise we'll have it back next time.

**Comment by silviodonato** [comment]
Yes, I forgot to do it yesterday. Thanks to spot this. I've done it with https://its.cern.ch/jira/browse/CMSHLT-1702

**Comment by Martin-Grunewald** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
