### PR TITLE
Fix non-linearity from C++ in HGCDigitizer

### PR DESCRIPTION
**Pull request by lgray**
This PR fixes a non-linearity found in the HGCDigitizer coming from initialization of the HGC Data frames.

Before there was a "square wave" imprint on the energies coming from the TDC, this is fixed now as seen below:
charge_vs_simenergy

### CODE REVIEW

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by civanch** [comment]
+1

**Comment by civanch** [comment]
@lgray , have you an evidence that "explicit" make a problem?

**Comment by lgray** [comment]
It's not the explicit that was making the problem, was the bit packing. ```explicit``` wasn't really needed anyway.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
