### PR TITLE
clean includes in PhotonMIPHaloTagger.h

### PR DESCRIPTION
**Pull request by davidlange6**
noticed as they lead to errors in the modules IB (not really sure why..)

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
"598 598 595 556 117 41 3 1 1 tests passed, 0 0 0 0 0 0 0 0 0 failed" - I'm not sure I see the problem reported?

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
@davidlange6 since you are cleaning the includes in this class, you can maybe also consider the following:
- "DataFormats/EcalRecHit/interface/EcalRecHitCollections.h" can now be removed from PhotonMIPHaloTagger.cc
- I would say also  "DataFormats/HcalRecHit/interface/HcalRecHitCollections.h"
- Also EcalChannelStatusRcd.h and EcalSeverityLevelAlgoRcd.h can be removed from being include'd in PhotonMIPHaloTagger.cc
- Probably several other include's can be removed from PhotonMIPHaloTagger.cc, e.g.
  - "DataFormats/BeamSpot/interface/BeamSpot.h"
  - All EgammaIsolationAlgos
  - "DataFormats/EgammaReco/interface/BasicCluster.h"
  - "DataFormats/EgammaReco/interface/BasicClusterFwd.h"
  - "DataFormats/EgammaReco/interface/SuperCluster.h"
  - "DataFormats/TrackReco/interface/Track.h"
  - "DataFormats/TrackReco/interface/TrackFwd.h"
  - "DataFormats/EgammaCandidates/interface/GsfElectron.h"
  - "DataFormats/EgammaCandidates/interface/GsfElectronFwd.h"
  - "CommonTools/Utils/interface/StringToEnumValue.h"
  - "DataFormats/EcalDetId/interface/EEDetId.h"
  - All "Geometry" ones (two of them are also repeated twice)
- `<string>` can be removed both from .h and from .cc
- I would add an `#include <vector>` in the header, instead

**Comment by davidlange6** [comment]
Hi @perrotta - I’ll have to leave a general cleanup of this class to the experts...

**Comment by perrotta** [comment]
+1
- Technical
- Jenkins tests pass
- (Further cleaning in the same package could be the target for a future PR)

**Comment by qliphy** [comment]
+1

**Pull request merged**
