### PR TITLE
implement concurrent ExternalLHEProducer technique

### PR DESCRIPTION
**Pull request by SiewYan**
#### PR description:

The concurrent version of ExternalLHEProducer is implemented for GEN workflows, LHE production + Hadronization mode.

  - No changed in output; expects improved CPU time.
  - None
  - https://twiki.cern.ch/twiki/bin/view/CMSPublic/WorkBookGenMultithread#Concurrent_ExternalLHEProducer
  - https://indico.cern.ch/event/894534/contributions/3827060/attachments/2030893/3398914/ExternalGeneratorFilter_for_Generators_Meeting.pdf
  - https://github.com/cms-sw/cmssw/issues/25090#issuecomment-818987732

#### PR validation:

Ran on several workflow from relval_generator, relval_extendedgen with `--nThreads 4`, and it is a success.

### CODE REVIEW

**Comment by SiewYan** [comment]
please test workflow 512,547,548,555,513,551,556,514,552,554,515,516,517,518,519,520

**Comment by SiewYan** [comment]
please test workflow 512,547,548,555,513,551,556,514,552,554,515,516,517,518,519,520

**Comment by qliphy** [comment]
adding @colizz @Dr15Jones who may want to have a look.

**Comment by colizz** [comment]
@SiewYan @qliphy Thanks, it looks good to me.🙂

**Comment by SiewYan** [comment]
@qliphy , does `comparisons for the following workflows were not done due to missing matrix map` indicate the test is not done?

**Comment by qliphy** [comment]
> @qliphy , does `comparisons for the following workflows were not done due to missing matrix map` indicate the test is not done?

The test runs for those workflows have been done without problem, but no comparisons done due to missing map (as those are for only limited worklows https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_0_X_2021-04-23-1100+106d73/42385/)

**Comment by SiewYan** [comment]
Thanks for clarification!

**Comment by SiewYan** [comment]
+1

**Comment by qliphy** [comment]
+1

**Comment by silviodonato** [comment]
This PR creates an error with Herwig7 (see https://github.com/cms-sw/cmssw/issues/33544)

**Pull request merged**
