### PR TITLE
[14_0_X] [Phase-2] Enable support for P2GTCandidates in HLT

### PR DESCRIPTION
**Pull request by SohamBhattacharya**
#### PR description:

First step towards migrating Phase-2 to HLT to use P2 GT emulator.
No changes are expected from this PR.
This just enables the usage of P2GTCandidate objects in HLT.

@rovere FYI

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
> No changes are expected from this PR.
This just enables the usage of P2GTCandidate objects in HLT.

@SohamBhattacharya visually the PR looks ok. Before signing can you clarify how you tested the changes?

**Comment by SohamBhattacharya** [comment]
> > No changes are expected from this PR.
> > This just enables the usage of P2GTCandidate objects in HLT.
> 
> @SohamBhattacharya visually the PR looks ok. Before signing can you clarify how you tested the changes?

Sure, I ran HLT on a `14_0_0_pre2` RelVal [1], there were no changes in the HLT summary (before: [2], after: [3]).

[1] /store/relval/CMSSW_14_0_0_pre2/RelValTTbar_14TeV/GEN-SIM-DIGI-RAW/133X_mcRun4_realistic_v1_STD_2026D98_noPU-v2/2590000/0545395f-3e24-41f9-9d0e-ad6c6941bdc2.root


[2]
```
HLT-Report ---------- Event  Summary ------------
HLT-Report Summary for Job
HLT-Report Events total = 20 wasrun = 20 passed = 20 errors = 0

HLT-Report ---------- HLTrig Summary ------------
HLT-Report   HLT #  WasRun     L1S     Pre     HLT   %L1sPre    Rate  RateHi  Errors Name
HLT-Report	 0	20	20	20	 3  15.00000     0.0     0.0	   0 L1T_SinglePFPuppiJet230off
HLT-Report	 1	20	20	20	 4  20.00000     0.0     0.0	   0 L1T_PFPuppiHT450off
HLT-Report	 2	20	20	20	 4  20.00000     0.0     0.0	   0 L1T_PFPuppiMET220off
HLT-Report	 3	20	20	20	 0   0.00000     0.0     0.0	   0 HLT_AK4PFPuppiJet520
HLT-Report	 4	20	20	20	 0   0.00000     0.0     0.0	   0 HLT_PFPuppiHT1070
HLT-Report	 5	20	20	20	 2  10.00000     0.0     0.0	   0 HLT_PFPuppiMETTypeOne140_PFPuppiMHT140
HLT-Report	 6	20	20	20	 4  20.00000     0.0     0.0	   0 L1T_PFHT400PT30_QuadPFPuppiJet_70_55_40_40_2p4
HLT-Report	 7	20	20	20	 9  45.00000     0.0     0.0	   0 L1T_DoublePFPuppiJets112_2p4_DEta1p6
HLT-Report	 8	20	20	20	 1   5.00000     0.0     0.0	   0 HLT_PFHT330PT30_QuadPFPuppiJet_75_60_45_40_TriplePFPuppiBTagDeepCSV_2p4
HLT-Report	 9	20	20	20	 1   5.00000     0.0     0.0	   0 HLT_PFHT200PT30_QuadPFPuppiJet_70_40_30_30_TriplePFPuppiBTagDeepCSV_2p4
HLT-Report	10	20	20	20	 1   5.00000     0.0     0.0	   0 HLT_DoublePFPuppiJets128_DoublePFPuppiBTagDeepCSV_2p4
HLT-Report	11	20	20	20	 0   0.00000     0.0     0.0	   0 HLT_PFHT330PT30_QuadPFPuppiJet_75_60_45_40_TriplePFPuppiBTagDeepFlavour_2p4
HLT-Report	12	20	20	20	 0   0.00000     0.0     0.0	   0 HLT_PFHT200PT30_QuadPFPuppiJet_70_40_30_30_TriplePFPuppiBTagDeepFlavour_2p4
HLT-Report	13	20	20	20	 0   0.00000     0.0     0.0	   0 HLT_DoublePFPuppiJets128_DoublePFPuppiBTagDeepFlavour_2p4
HLT-Report	14	20	20	20	 5  25.00000     0.0     0.0	   0 L1T_SingleTkMuon_22
HLT-Report	15	20	20	20	 1   5.00000     0.0     0.0	   0 L1T_DoubleTkMuon_15_7
HLT-Report	16	20	20	20	 1   5.00000     0.0     0.0	   0 L1T_TripleTkMuon_5_3_3
HLT-Report	17	20	20	20	 1   5.00000     0.0     0.0	   0 HLT_Mu50_FromL1TkMuon
HLT-Report	18	20	20	20	 4  20.00000     0.0     0.0	   0 HLT_IsoMu24_FromL1TkMuon
HLT-Report	19	20	20	20	 0   0.00000     0.0     0.0	   0 HLT_Mu37_Mu27_FromL1TkMuon
HLT-Report	20	20	20	20	 0   0.00000     0.0     0.0	   0 HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_DZ_FromL1TkMuon
HLT-Report	21	20	20	20	 0   0.00000     0.0     0.0	   0 HLT_TriMu_10_5_5_DZ_FromL1TkMuon
HLT-Report	22	20	20	20	 4  20.00000     0.0     0.0	   0 L1T_TkEm51
HLT-Report	23	20	20	20	 5  25.00000     0.0     0.0	   0 L1T_TkEle36
HLT-Report	24	20	20	20	 6  30.00000     0.0     0.0	   0 L1T_TkIsoEm36
HLT-Report	25	20	20	20	 3  15.00000     0.0     0.0	   0 L1T_TkIsoEle28
HLT-Report	26	20	20	20	 2  10.00000     0.0     0.0	   0 L1T_TkEm37TkEm24
HLT-Report	27	20	20	20	 3  15.00000     0.0     0.0	   0 L1T_TkEle25TkEle12
HLT-Report	28	20	20	20	 2  10.00000     0.0     0.0	   0 L1T_TkIsoEm22TkIsoEm12
HLT-Report	29	20	20	20	 3  15.00000     0.0     0.0	   0 L1T_TkIsoEle22TkEm12
HLT-Report	30	20	20	20	 2  10.00000     0.0     0.0	   0 HLT_Ele32_WPTight_Unseeded
HLT-Report	31	20	20	20	 2  10.00000     0.0     0.0	   0 HLT_Ele26_WP70_Unseeded
HLT-Report	32	20	20	20	 0   0.00000     0.0     0.0	   0 HLT_Photon108EB_TightID_TightIso_Unseeded
HLT-Report	33	20	20	20	 0   0.00000     0.0     0.0	   0 HLT_Photon187_Unseeded
HLT-Report	34	20	20	20	 0   0.00000     0.0     0.0	   0 HLT_DoubleEle25_CaloIdL_PMS2_Unseeded
HLT-Report	35	20	20	20	 1   5.00000     0.0     0.0	   0 HLT_Diphoton30_23_IsoCaloId_Unseeded
HLT-Report	36	20	20	20	 2  10.00000     0.0     0.0	   0 HLT_Ele32_WPTight_L1Seeded
HLT-Report	37	20	20	20	 0   0.00000     0.0     0.0	   0 HLT_Ele115_NonIso_L1Seeded
HLT-Report	38	20	20	20	 2  10.00000     0.0     0.0	   0 HLT_Ele26_WP70_L1Seeded
HLT-Report	39	20	20	20	 0   0.00000     0.0     0.0	   0 HLT_Photon108EB_TightID_TightIso_L1Seeded
HLT-Report	40	20	20	20	 0   0.00000     0.0     0.0	   0 HLT_Photon187_L1Seeded
HLT-Report	41	20	20	20	 0   0.00000     0.0     0.0	   0 HLT_DoubleEle25_CaloIdL_PMS2_L1Seeded
HLT-Report	42	20	20	20	 0   0.00000     0.0     0.0	   0 HLT_DoubleEle23_12_Iso_L1Seeded
HLT-Report	43	20	20	20	 1   5.00000     0.0     0.0	   0 HLT_Diphoton30_23_IsoCaloId_L1Seeded
HLT-Report	44	20	20	20	 2  10.00000     0.0     0.0	   0 HLT_DoubleMediumChargedIsoPFTauHPS40_eta2p1
HLT-Report	45	20	20	20	20 100.00000     0.0     0.0	   0 MC_JME
HLT-Report	46	20	20	20	20 100.00000     0.0     0.0	   0 MC_BTV
HLT-Report	47	20	20	20	10  50.00000     0.0     0.0	   0 MC_Ele5_Open_Unseeded
HLT-Report	48	20	20	20	 6  30.00000     0.0     0.0	   0 MC_Ele5_Open_L1Seeded
HLT-Report	49	20	20	20	 0   0.00000     0.0     0.0	   0 HLTriggerFinalPath

HLT-Report end!

```

[3]
```
HLT-Report ---------- Event  Summary ------------
HLT-Report Summary for Job
HLT-Report Events total = 20 wasrun = 20 passed = 20 errors = 0

HLT-Report ---------- HLTrig Summary ------------
HLT-Report   HLT #  WasRun     L1S     Pre     HLT   %L1sPre    Rate  RateHi  Errors Name
HLT-Report	 0	20	20	20	 3  15.00000     0.0     0.0	   0 L1T_SinglePFPuppiJet230off
HLT-Report	 1	20	20	20	 4  20.00000     0.0     0.0	   0 L1T_PFPuppiHT450off
HLT-Report	 2	20	20	20	 4  20.00000     0.0     0.0	   0 L1T_PFPuppiMET220off
HLT-Report	 3	20	20	20	 0   0.00000     0.0     0.0	   0 HLT_AK4PFPuppiJet520
HLT-Report	 4	20	20	20	 0   0.00000     0.0     0.0	   0 HLT_PFPuppiHT1070
HLT-Report	 5	20	20	20	 2  10.00000     0.0     0.0	   0 HLT_PFPuppiMETTypeOne140_PFPuppiMHT140
HLT-Report	 6	20	20	20	 4  20.00000     0.0     0.0	   0 L1T_PFHT400PT30_QuadPFPuppiJet_70_55_40_40_2p4
HLT-Report	 7	20	20	20	 9  45.00000     0.0     0.0	   0 L1T_DoublePFPuppiJets112_2p4_DEta1p6
HLT-Report	 8	20	20	20	 1   5.00000     0.0     0.0	   0 HLT_PFHT330PT30_QuadPFPuppiJet_75_60_45_40_TriplePFPuppiBTagDeepCSV_2p4
HLT-Report	 9	20	20	20	 1   5.00000     0.0     0.0	   0 HLT_PFHT200PT30_QuadPFPuppiJet_70_40_30_30_TriplePFPuppiBTagDeepCSV_2p4
HLT-Report	10	20	20	20	 1   5.00000     0.0     0.0	   0 HLT_DoublePFPuppiJets128_DoublePFPuppiBTagDeepCSV_2p4
HLT-Report	11	20	20	20	 0   0.00000     0.0     0.0	   0 HLT_PFHT330PT30_QuadPFPuppiJet_75_60_45_40_TriplePFPuppiBTagDeepFlavour_2p4
HLT-Report	12	20	20	20	 0   0.00000     0.0     0.0	   0 HLT_PFHT200PT30_QuadPFPuppiJet_70_40_30_30_TriplePFPuppiBTagDeepFlavour_2p4
HLT-Report	13	20	20	20	 0   0.00000     0.0     0.0	   0 HLT_DoublePFPuppiJets128_DoublePFPuppiBTagDeepFlavour_2p4
HLT-Report	14	20	20	20	 5  25.00000     0.0     0.0	   0 L1T_SingleTkMuon_22
HLT-Report	15	20	20	20	 1   5.00000     0.0     0.0	   0 L1T_DoubleTkMuon_15_7
HLT-Report	16	20	20	20	 1   5.00000     0.0     0.0	   0 L1T_TripleTkMuon_5_3_3
HLT-Report	17	20	20	20	 1   5.00000     0.0     0.0	   0 HLT_Mu50_FromL1TkMuon
HLT-Report	18	20	20	20	 4  20.00000     0.0     0.0	   0 HLT_IsoMu24_FromL1TkMuon
HLT-Report	19	20	20	20	 0   0.00000     0.0     0.0	   0 HLT_Mu37_Mu27_FromL1TkMuon
HLT-Report	20	20	20	20	 0   0.00000     0.0     0.0	   0 HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_DZ_FromL1TkMuon
HLT-Report	21	20	20	20	 0   0.00000     0.0     0.0	   0 HLT_TriMu_10_5_5_DZ_FromL1TkMuon
HLT-Report	22	20	20	20	 4  20.00000     0.0     0.0	   0 L1T_TkEm51
HLT-Report	23	20	20	20	 5  25.00000     0.0     0.0	   0 L1T_TkEle36
HLT-Report	24	20	20	20	 6  30.00000     0.0     0.0	   0 L1T_TkIsoEm36
HLT-Report	25	20	20	20	 3  15.00000     0.0     0.0	   0 L1T_TkIsoEle28
HLT-Report	26	20	20	20	 2  10.00000     0.0     0.0	   0 L1T_TkEm37TkEm24
HLT-Report	27	20	20	20	 3  15.00000     0.0     0.0	   0 L1T_TkEle25TkEle12
HLT-Report	28	20	20	20	 2  10.00000     0.0     0.0	   0 L1T_TkIsoEm22TkIsoEm12
HLT-Report	29	20	20	20	 3  15.00000     0.0     0.0	   0 L1T_TkIsoEle22TkEm12
HLT-Report	30	20	20	20	 2  10.00000     0.0     0.0	   0 HLT_Ele32_WPTight_Unseeded
HLT-Report	31	20	20	20	 2  10.00000     0.0     0.0	   0 HLT_Ele26_WP70_Unseeded
HLT-Report	32	20	20	20	 0   0.00000     0.0     0.0	   0 HLT_Photon108EB_TightID_TightIso_Unseeded
HLT-Report	33	20	20	20	 0   0.00000     0.0     0.0	   0 HLT_Photon187_Unseeded
HLT-Report	34	20	20	20	 0   0.00000     0.0     0.0	   0 HLT_DoubleEle25_CaloIdL_PMS2_Unseeded
HLT-Report	35	20	20	20	 1   5.00000     0.0     0.0	   0 HLT_Diphoton30_23_IsoCaloId_Unseeded
HLT-Report	36	20	20	20	 2  10.00000     0.0     0.0	   0 HLT_Ele32_WPTight_L1Seeded
HLT-Report	37	20	20	20	 0   0.00000     0.0     0.0	   0 HLT_Ele115_NonIso_L1Seeded
HLT-Report	38	20	20	20	 2  10.00000     0.0     0.0	   0 HLT_Ele26_WP70_L1Seeded
HLT-Report	39	20	20	20	 0   0.00000     0.0     0.0	   0 HLT_Photon108EB_TightID_TightIso_L1Seeded
HLT-Report	40	20	20	20	 0   0.00000     0.0     0.0	   0 HLT_Photon187_L1Seeded
HLT-Report	41	20	20	20	 0   0.00000     0.0     0.0	   0 HLT_DoubleEle25_CaloIdL_PMS2_L1Seeded
HLT-Report	42	20	20	20	 0   0.00000     0.0     0.0	   0 HLT_DoubleEle23_12_Iso_L1Seeded
HLT-Report	43	20	20	20	 1   5.00000     0.0     0.0	   0 HLT_Diphoton30_23_IsoCaloId_L1Seeded
HLT-Report	44	20	20	20	 2  10.00000     0.0     0.0	   0 HLT_DoubleMediumChargedIsoPFTauHPS40_eta2p1
HLT-Report	45	20	20	20	20 100.00000     0.0     0.0	   0 MC_JME
HLT-Report	46	20	20	20	20 100.00000     0.0     0.0	   0 MC_BTV
HLT-Report	47	20	20	20	10  50.00000     0.0     0.0	   0 MC_Ele5_Open_Unseeded
HLT-Report	48	20	20	20	 6  30.00000     0.0     0.0	   0 MC_Ele5_Open_L1Seeded
HLT-Report	49	20	20	20	 0   0.00000     0.0     0.0	   0 HLTriggerFinalPath

HLT-Report end!
```

**Comment by mmusich** [comment]
> Sure, I ran HLT on a 14_0_0_pre2 RelVal [1], there were no changes in the HLT summary (before: [2], after: [3]

Thanks for the reply, but I meant how you tested the changes work as expected.

**Comment by SohamBhattacharya** [comment]
> > No changes are expected from this PR.
> > This just enables the usage of P2GTCandidate objects in HLT.
> 
> @SohamBhattacharya visually the PR looks ok. Before signing can you clarify how you tested the changes?

A few HLT paths were tested [1, 2] a while back in a private branch in `12_5_2_patch1` [3], using a recipe provided by L1 to run the GT emulator and produce the P2GTCandidates. 
Now that the GT emulator is fully integrated, we are resuming the attempt to switch the HLT filters to use the GT emulator.
Note that the switch cannot be tested out-of-the-box, as (to the best of my knowledge) the P2GTCandidates are not being produced+stored by default. I am in communication with L1 about enabling that.

I wanted to split the migration to P2GT emulator into different PRs: first the support for using P2GTCandidates, and then changing the HLT filters to use them.

[1] https://indico.cern.ch/event/1300760/contributions/5470629/attachments/2674255/4638873/2023-06-27_HLT-upgrade-meeting.pdf

[2]
`path`: default
`pathP2GT`: path using P2 GT emulator
```
HLT-Report ---------- HLTrig Summary ------------
HLT-Report   HLT #  WasRun     L1S     Pre     HLT   %L1sPre    Rate  RateHi  Errors Name
HLT-Report       0      50      50      50      22  44.00000     0.0     0.0       0 HLT_Mu50_FromL1TkMuon
HLT-Report       1      50      50      50      22  44.00000     0.0     0.0       0 HLT_Mu50_FromL1TkMuonP2GT
HLT-Report       2      50      50      50      32  64.00000     0.0     0.0       0 HLT_IsoMu24_FromL1TkMuon
HLT-Report       3      50      50      50      32  64.00000     0.0     0.0       0 HLT_IsoMu24_FromL1TkMuonP2GT
HLT-Report       4      50      50      50      28  56.00000     0.0     0.0       0 HLT_Mu37_Mu27_FromL1TkMuon
HLT-Report       5      50      50      50      28  56.00000     0.0     0.0       0 HLT_Mu37_Mu27_FromL1TkMuonP2GT
```
[3] https://github.com/SohamBhattacharya/cmssw/tree/test_P2-L1-GT-emulator_12_5_2_patch1

**Comment by mmusich** [comment]
+hlt
   * interlocutory step towards migrating the Phase-2 HLT to use Phase2 GlobalTrigger emulator.
   * no changes reported by the bot in the [test results](https://github.com/cms-sw/cmssw/pull/43707#issuecomment-1889736648), both in terms of Trigger Results and in terms of the DQM histogram comparisons
   * relying on the private validation done by the proponent, see https://github.com/cms-sw/cmssw/pull/43707#issuecomment-1891994089 and https://github.com/cms-sw/cmssw/pull/43707#issuecomment-1892087238

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
