### PR TITLE
Electron hlt filter bits mod

### PR DESCRIPTION
**Pull request by DebabrataBhowmik**
#### PR description:

This PR is being made to correctly assign the filterbit "HLT30WPTightGSfTrackIso" to the electron trigger objects.
In current versio, we have a filter bit "WPTight" including "WPTight" & "TrackIsoFilter" in the similar line, however this is more generic and have contribution from cross-triggers along with the single electron triger of interest. 
Thus it is very important for EGM to have this additional filterbits(being included via this PR) to have the proper filterbit corresponding to the lowest pT, unprescaled, single electron trigger.  

#### PR validation:
- This PR just adds one filterbit to the electron trigger objects 
- Checked with : runTheMatrix.py -l 12846.0
- The test passed and the results are as expected

Backportation is not needed for this PR.

### CODE REVIEW

**Comment by RSalvatico** [comment]
type egamma

**Comment by RSalvatico** [comment]
enable nano

**Comment by RSalvatico** [comment]
please test

**Comment by hqucms** [comment]
+1

**Comment by hqucms** [comment]
ignore tests-rejected with ib-failure

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
