### PR TITLE
TriggerResultsFilter: migrate to L1 Stage2 (80x)

### PR DESCRIPTION
**Pull request by fwyzard**

### CODE REVIEW

**Comment by fwyzard** [comment]
@cmsbuild please test

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
+1

**Comment by fwyzard** [comment]
the results look correct from a simple test running over recent data

**Comment by dmitrijus** [comment]
+1

**Comment by slava77** [comment]
+1

for 
- reco is minimally affected, only in  RecoLocalTracker/SiPixelClusterizer/test/testClusters.py with what what appears to make not change at run time
- jenkins tests pass and comparisons with baseline show no differences in reco  products; there are changes in HLT plots
    - similar to 81X version, there are empty HLT Btag plots in wf 25202 https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_8_0_X_2016-06-12-2300+14878/14459/25202.0_TTbar_13+TTbar_13+DIGIUP15_PU25+RECOUP15_PU25+HARVESTUP15_PU25/HLT_BTag.html
    - there is a small change in HLT ele plot
wf134 911_singleele

chances are that this PR gets updated.

**Comment by fwyzard** [comment]
chances are it will not be.

**Comment by mulhearn** [comment]
+1

**Comment by Martin-Grunewald** [comment]
@mmusich 
Please sign!

**Comment by mmusich** [comment]
+1

**Comment by davidlange6** [comment]
so I missed in 81x (or maybe its not there) - but this PR appears to add endless printouts - 

Begin processing the 5th record. Run 1, Event 5, LumiSection 1 at 14-Jun-2016 22:40:32.693 CEST
%MSG-w ProductNotFound:  TriggerResultsFilter:hltBtagTriggerSelection  14-Jun-2016 22:40:33 CEST Run: 1 Event: 5
An exception of category 'ProductNotFound' occurred.
Exception Message:
Principal::getByToken: Found zero products matching all criteria
Looking for type: BXVector<GlobalAlgBlk>
Looking for module label: gtDigis
Looking for productInstanceName:

**Comment by fwyzard** [comment]
what workflow is this running in ?
looks like Run I ?

**Comment by Martin-Grunewald** [comment]
@davidlange6 
This printout would have been there even without this PR, as the label "gtDigis" tells you
the config of the TriggerResultsFilter:hltBtagTriggerSelection instance had never been
updated to conform to stage-2.
If it is really a Run-I Stage-1/legacy workflow, then the instance should be removed as
we do not support the old L1T, for which hlt validation is anyway no longer needed.

**Comment by fwyzard** [comment]
Actually, without this PR the message is not there, because the filter still looks for the old legacy GT products.
The fact that the legacy GT payload *is* present in a 2016 workflow is a bug, though.

**Comment by fwyzard** [comment]
the messages should be removed by #14987

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
+1

**Pull request merged**
