### PR TITLE
Add script for tracking public MC plots

### PR DESCRIPTION
**Pull request by makortel**
This PR adds the script used to make the 2017 performance plots from MC.

Tested in 10_2_0_pre5, no changes expected.

@VinInn @mtosi @hajohajo @JanFSchulte

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by makortel** [comment]
I found a small issue with the code (an interface change of `plotting` after this script was ran the last time), so I took the opportunity to include it in this PR (sorry @dmitrijus )

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by fabiocos** [comment]
@makortel this is not affecting any production workflow, so it is ok to me to merge in 10_2_X now.
I assume it has been tested in a standalone mode. I notice that we have here the n-th version of tdrstyle.C in CMSSW, different from a couple of others I have randomly compared with...

**Comment by fabiocos** [comment]
+1

**Pull request merged**
