### PR TITLE
DependencyGraph: change default file name

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Change the default file name created by the `DependencyGraph` to use the `.dot` extension.

### CODE REVIEW

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by fwyzard** [comment]
that seems... unrelated ?
@smuzaffar ?

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by fwyzard** [comment]
code-checks

**Comment by makortel** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
