### PR TITLE
[124X] Fix for nan in loc angle backport

### PR DESCRIPTION
**Pull request by tvami**
#### PR description:

See https://github.com/cms-sw/cmssw/pull/38881/

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport of https://github.com/cms-sw/cmssw/pull/38881/

### CODE REVIEW

**Comment by tvami** [comment]
type bugfix,trk

**Comment by tvami** [comment]
backport of https://github.com/cms-sw/cmssw/pull/38881

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
+db

**Comment by clacaputo** [comment]
+reconstruction

- backport of #38881 , code in line with the original PR

**Comment by qliphy** [comment]
+1

**Comment by fabiocos** [comment]
@qliphy @perrotta this PR seems to solve new crashes that we are observing at Tier0. It would be useful to clarify the path for its insertion into a (patch)-release which can be deployed.  I did not see issues triggered by it in the IBs after its merge.

**Comment by qliphy** [comment]
> @qliphy @perrotta this PR seems to solve new crashes that we are observing at Tier0. It would be useful to clarify the path for its insertion into a (patch)-release which can be deployed. I did not see issues triggered by it in the IBs after its merge.

@fabiocos  Yes, there are several PRs requested for next 12_4_X,  let's discuss the plan at today's ORP.

**Pull request merged**
