### PR TITLE
Fix CMS deprecatation warnings in  RecoLocalMuon

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

- converted modules to edm::one::EDAnalyzer
- added esConsumes calls

#### PR validation:

Packages compiles without issuing CMS deprecation warnings.

### CODE REVIEW

**Comment by clacaputo** [comment]
+reconstruction

**Comment by srimanob** [comment]
Note to @watson-ij @smuzaffar 

Not relate to this PR. I see the static check output tells a warning on `/RecoLocalMuon/GEMRecHit/plugins/GEMRecHitProducer.cc` and `DataFormats/DTRecHit/interface/DTDriftTimeParameters.icc`, maybe you can have a look later. Thx.

https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-33b9b2/28375/llvm-analysis/

**Comment by srimanob** [comment]
+Upgrade

Technical PR, no change is expected.

**Comment by perrotta** [comment]
+1

**Pull request merged**
