### PR TITLE
Update online bs with pv information master

### PR DESCRIPTION
**Pull request by rovere**
This will bring master inline with the 920patchX branch for everything related to the online BS. Namely:

* it introduces a proper pixel tracking and vertexing based on 2017 tracking and detector
* it updates the output file of the beampixel application to be compatible with DIP usage
* it rewrites the logic with which the online BS output files are written to disk.
* it tunes the global tracking region for pixel tracking in order to be able to compute the BS position using the canonical d0-phi fit.

It includes #19012 so I'd suggest integrating this one that goes beyond that one.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/19050	3025a0e
- parts related to RECO (RecoPixelVertexing/PixelTrackFitting/python/PixelTracks_2017_cff.py ) are the same as in https://github.com/cms-sw/cmssw/pull/18918	 	01951a9. There was some discussion to merge PixelTracks_2017_cff with PixelTracks_cff, but that will contain other feature changes and will happen later.
- jenkins tests pass and comparisons show no differences (the modified parts are not tested in the jenkins jobs)

**Comment by davidlange6** [comment]
@dmitrijus - this is apparently urgently needed.. any plans to review it?

**Comment by vanbesien** [comment]
doing 9-sum to make sure the end result of all this matches 100% with current online production

**Comment by vanbesien** [comment]
+1

**Pull request merged**
