### PR TITLE
DD4Hep Algorithms and Shapes

### PR DESCRIPTION
**Pull request by ianna**
* Includes https://github.com/cms-sw/cmssw/pull/22643
* Add more CMS-specific shapes

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by Dr15Jones** [comment]
I'm surprised that some of these file have AIDA copyright. Are such files unique to CMS or are they copied from DD4Hep? If so, should we make those an external?

**Comment by civanch** [comment]
@ianna , may be having detailed discussion on design of DD4Hep is needed? We may suffer from tails of old thread unsafe frameworks.

**Comment by ianna** [comment]
@Dr15Jones - these files are unique to CMS and should be under our control for at least some time allow smooth integration with CMS framework. Markus and I are working on the code together. As you may have noticed, there is a lot of copying back and forth. The CMS Tracker Pixel from run 1 is an example in DD4Hep repository. 
I agree, the long term ownership and the code distribution should be discussed, so should be the copyright.

**Comment by ianna** [comment]
@civanch - I'm confident, we can help with threadsafety of DD4Hep when it is an issue.

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by fabiocos** [comment]
@ianna @civanch I understand that this code is not currently affecting any production workflow, so entering it into the release for further test, also about thread saftery, si ok, am I correct?

@Dr15Jones @davidlange6 @sextonkennedy @tommasoboccali
technically this code seems ready to be integrated, but I am not sure about the conclusion concerning the copyright statements in some of the files. Ianna says that this stuff is unique to CMS, but f we integrate it as it is we will be distributing software with the AIDA copyright inside. Do you see issues with that?

**Comment by civanch** [comment]
Dear all, to avoid confusions there are two AIDA packages: first old analysis package, which is dead now, second - geometry project for unification of Geant4 and ROOT, it should be also dead but I am not sure. This geometry tool evolution is a slow process. After several years of AIDA developments VecGeom appears and at some moment in time it become independent on AIDA.  

For me, having AIDA or Gaudi headers inside DD4HEP means that the package itself is not clean. What I see in this PR as geometry description seems to be convenient and I fully agree with the basic idea to have a modern geometry description, which is written on base of  the best knowledge of geometry and modern architectures. Ideally, it should be free from tails of old frameworks. I am sure, that this PR is harmless but, independently on that, I would have design discussion/analysis and formulate CMS requirements to this tool.

**Comment by sextonkennedy** [comment]
Hi All,

I did investigate this through Benedikt.  He said that the authors do intend to move to LGPL and have the copyright owned by CERN.  We should push on SFT to clean up the package as Vladimir suggests.

Cheers, Liz

On Apr 17, 2018, at 10:58 AM, Vladimir Ivantchenko <notifications@github.com<mailto:notifications@github.com>> wrote:


Dear all, to avoid confusions there are two AIDA packages: first old analysis package, which is dead now, second - geometry project for unification of Geant4 and ROOT, it should be also dead but I am not sure. This geometry tool evolution is a slow process. After several years of AIDA developments VecGeom appears and at some moment in time it become independent on AIDA.

For me, having AIDA or Gaudi headers inside DD4HEP means that the package itself is not clean. What I see in this PR as geometry description seems to be convenient and I fully agree with the basic idea to have a modern geometry description, which is written on base of the best knowledge of geometry and modern architectures. Ideally, it should be free from tails of old frameworks. I am sure, that this PR is harmless but, independently on that, I would have design discussion/analysis and formulate CMS requirements to this tool.

**Comment by fabiocos** [comment]
@ianna @civanch @sextonkennedy AIDA appears everywhere in the header files of DD4hep, but this is at least an external package, although distributed with CMSSW. I am speaking here of the files of this PR that will become directly part of CMSSW code. When Liz says "We should push on SFT to clean up the package as Vladimir suggests." I assume she is referring to DD4hep, what about the code in this PR?

**Comment by sextonkennedy** [comment]
Hi Yana,

If this is code you wrote and it is an experiment example, then we should not be required to have the AIDA copyright on the files.  What do you mean by “re-write” the classes?  Sorry I didn’t have time to look at the PRs themselves.

Cheers, Liz
Sent from my iPad

On Apr 17, 2018, at 14:39, Ianna Osborne <notifications@github.com<mailto:notifications@github.com>> wrote:


@fabiocos<https://github.com/fabiocos> - if this copyright is an issue, I can completely diverge from the DD4Hep/DDCMS example, e.g. re-write the classes and use our own namespace. I've modified and added quite a bit of the code anyway.

**Comment by ianna** [comment]
Hi Liz,

This PR code is a joint work between Markus and me. It originated from a copy of a DD4hep/DDCMS example, which in its turn contained a copy of the CMS code. 

As far as I understand, DD4hep has CERN copyright, more exactly it's "CERN copyright for the benefit of the AIDA(2020) Consortium". We can discuss the re-licensing issue at the next DD4hep developers meeting on the 9th of May.

Kind regards,
Yana

**Comment by fabiocos** [comment]
@ianna @sextonkennedy @tommasoboccali as agreed, we put this PR on hold pending the clarification about the copyright issue

**Comment by fabiocos** [comment]
hold

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
Replaced by https://github.com/cms-sw/cmssw/pull/23037

**Pull request closed without merging**
