### PR TITLE
DD4hep: Add DDDetector Producer from DB and Cleanup ES Records

### PR DESCRIPTION
**Pull request by ianna**
#### PR description:

* Add DDDetector Producer from DB that is now an IdealGeometryRecord
* Cleanup and streamline Geometry Records
* Revert changes to IdealMagneticFieldRecord - no need to depend on GeometryFileRcd

@namapane - Please, take the ```DetectorDescription/DDCMS/plugins/DDDetectorESProducer.cc``` as an example for a MF producer from DB. I didn't want to introduce yet another set of configurable parameters here.

@cvuosalo - there is a problem (under investigation) with reading the geometry payloads from DB. The job to run is:
```
cmsRun DetectorDescription/DDCMS/test/python/testGeometry2021FromDB.py
```
This PR does not intend to solve it.

#### if this PR is a backport please specify the original PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by cvuosalo** [comment]
@ianna: Did you check that `MagneticField/GeomBuilder/test/python/testMagGeometry.py` runs successfully after this change? That test is not part of the unit tests.

**Comment by ianna** [comment]
@smuzaffar - I think, you've had a suggestion how to make this comparison better:
```
=============================================

MessageLogger Summary

Severity    # Occurrences   Total Occurrences
--------    -------------   -----------------

dropped waiting message count 0
The output diff is 1228 (it's ok if it's relatively small, e.g. less then a 1050):
1c1
< %MSG-i Geometry:  (NoModuleName) DTGeometryESProducer() 12-Sep-2019 14:58:07 CEST pre-events
---
> %MSG-i Geometry:  (NoModuleName) DTGeometryESProducer() 14-Oct-2019 18:47:21 CEST pre-events
5c5,6
< Benchmark 'DTGeometryESProducer Filter Registry' took 0.066751 millis
---
> DDDetectorESProducer::Produce MUON
> Benchmark 'DTGeometryESProducer Filter Registry' took 0.051119 millis
7c8
< Benchmark 'DTGeometryESProducer' took 7550.89 millis
---
> Benchmark 'DTGeometryESProducer' took 8962.74 millis
9c10
<  Geometry node for DTGeom is  0x7f870b897e40
---
>  Geometry node for DTGeom is  0x7f5c71deabc0
3683c3684
<     2 EventSetupDependency -i AfterModConstruc                       2*       2
---
>     2 EventSetupDependency -i AfterModConstruc                       3*       3
3686c3687
<     5 Geometry             -i DTGeometryTest:t                      19       19
---
>     5 Geometry             -i DTGeometryTest:t                      20       20
3700c3701
<     2 EventSetupDependency pre-events       pre-events       
---
>     2 EventSetupDependency pre-events       pre-events       pre-events
3714c3715
< Info                   35                  35
---
> Info                   37                  37
Failure using cmsRun /build/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_0_X_2019-10-14-1100/src/Geometry/DTGeometryBuilder/test/python/testDTGeometry.py: status 255
status = 65280

---> test GeometryDTGeometryBuilderTestDriver had ERRORS
 
^^^^ End Test GeometryDTGeometryBuilderTestDriver ^^^^
Package DetectorDescription/DDCMS: Running test testDD4hepFilteredView

```

**Comment by ianna** [comment]
> @ianna: Did you check that `MagneticField/GeomBuilder/test/python/testMagGeometry.py` runs successfully after this change? That test is not part of the unit tests.

Nope, and it does not run since we need to add a ```produce(const IdealMagneticFieldRecord&)``` to the ```ESSource```.
BTW, we should include all relevant tests in the automated validation scripts.

**Comment by ianna** [comment]
hold

**Comment by ianna** [comment]
unhold

**Comment by ianna** [comment]
please test

**Comment by namapane** [comment]
> 
> 
> > @ianna: Did you check that `MagneticField/GeomBuilder/test/python/testMagGeometry.py` runs successfully after this change? That test is not part of the unit tests.
> 
> Nope, and it does not run since we need to add a `produce(const IdealMagneticFieldRecord&)` to the `ESSource`.
> BTW, we should include all relevant tests in the automated validation scripts.

Hi Ianna, it's in the plans together with the producer from DB, but I wanted to finish some cleanup of all tests beforehand.

**Comment by ianna** [comment]
please test

**Comment by cvuosalo** [comment]
+1

**Comment by ianna** [comment]
@perrotta, @slava77 - please, review

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/28167	368cd16 
- somewhat technical; in line with the PR description
- jenkins tests pass

**Comment by fabiocos** [comment]
+1

**Pull request merged**
