### PR TITLE
remove plugin template `HLTJetTagWithMatching`

### PR DESCRIPTION
**Pull request by missirol**
#### PR description:

This PR removes the plugin template `HLTJetTagWithMatching`, which is now superseded by the improved version of `HLTJetTag` added in #41351. The use of `HLTJetTagWithMatching` was removed from the latest Run-3 HLT menus in #42610. For further information, see also https://github.com/cms-sw/cmssw/issues/41045, [CMSHLT-2750](https://its.cern.ch/jira/browse/CMSHLT-2750), and [CMSHLT-2863](https://its.cern.ch/jira/browse/CMSHLT-2863).

Merely technical. No changes expected.

#### PR validation:

`addOnTests.py` passed.

#### If this PR is a backport, please specify the original PR and why you need to backport that PR. If this PR will be backported, please specify to which release cycle the backport is meant for:

N/A

### CODE REVIEW

**Comment by missirol** [comment]
please test

**Comment by missirol** [comment]
please test

**Comment by missirol** [comment]
+hlt

**Comment by perrotta** [comment]
+1

**Pull request merged**
