### PR TITLE
enable dnn tracking for heavy ions for Run 3 eras

### PR DESCRIPTION
**Pull request by mandrenguyen**
#### PR description:

The heavy-ion reconstruction (eras based on `pp_on_AA`) use track selection calibrations based on a BDT that was trained on Run 2 PbPb MC for six of the tracking iterations.
In the meantime, pp has migrated to a DNN-based track selection.  
There is an ongoing effort to perform a DNN training for heavy ions, but this is not 100% sure to converge for 13_2_X, which is the intended release for 2023 PbPb. 
As a back-up solution we have tested the default pp calibrations, but tightening the working points to give a similar efficiency to the old BDT calibrations.   
It was found that the efficiency and fake rate are very similar, except at high pT where the fake rate is dramatically lower with the DNN track selection. 
The performance is shown here:
https://indico.cern.ch/event/1278968/contributions/5372961/attachments/2646731/4581824/Performance_of_DNN_with_pp_training_in_heavy_ions.pdf
This PR switches to the DNN as the default for heavy ions.
We also remove an additional difference between pp and HI tracking, which was the use of the `tight` quality bit in the hit cleaning between steps. 

#### PR validation:

Tested with wf 160

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

No backport will be needed.

@CesarBernardes @abaty @sayanchatterjee38 @icali

### CODE REVIEW

**Comment by mandrenguyen** [comment]
please test workflow 160

**Comment by tvami** [comment]
hi Matt, we have the Run-3 MC and data GTs separate from the Run-2 ones. So although I'm all for cleaning, if you just want the Run-3 part, we can just do the removal in the Run-3 GTs only for now.

**Comment by tvami** [comment]
Although, looking at this PR, when you change `pp_on_AA` that does automatically change Run-2 stuff too, no?

**Comment by mandrenguyen** [comment]
@tmavi
Ok, sounds good to clean from the Run 3 queues once this is merged.
trackdnn is only enabled for the Run 3 era.
This PR should not change the behavior of the Run 2 HI workflows, unless I screwed something up (which we would see when the tests are done)

**Comment by mandrenguyen** [comment]
Ok, now it looks like tracking is only modified in the PbPb Run 3 workflow, e.g.,
[312.0_Pyquen_ZeemumuJets_pt10_2760GeV_2022/all_RECO_step3/c_recoTracks_generalTracks__RECO_obj_originalAlgo.png](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_13_2_X_2023-05-16-2300+dfa2ea/57108/validateJR/312.0_Pyquen_ZeemumuJets_pt10_2760GeV_2022/all_RECO_step3/c_recoTracks_generalTracks__RECO_obj_originalAlgo.png)

@slava77 or @mmusich do you have any feedback on this PR eventually?

**Comment by slava77** [comment]
> @slava77 or @mmusich do you have any feedback on this PR eventually?

I didn't have much to comment on the implementation in the PR.

The only question is if the validation based on private tests is enough. 
For pp we'd probably go with a special validation, not to impact adversely the downstream observables unexpectedly.
Perhaps for HI it's OK though.

**Comment by mmusich** [comment]
> I didn't have much to comment on the implementation in the PR.

for starters, this could have been shown at a POG meeting. As far as I can tell, it didn't.

**Comment by mandrenguyen** [comment]
> for starters, this could have been shown at a POG meeting. As far as I can tell, it didn't.

Thanks for the invitation?  
Please let me know when the next opportunity is after Monday the 22nd.
I have a conflict on that day, and it looks like the agenda is already pretty full anyway.

**Comment by mmusich** [comment]
> Please let me know when the next opportunity is after Monday the 22nd.

The next opportunity would be the joint DPG/POG meeting on [Wed 24th](https://indico.cern.ch/event/1271487/?showDate=all&showSession=8#b-506191-joint-tracker-dpg-tra) though being TkWeek we should see if it fits. 
In any case the code review can happen independently from a formal presentation, that I guess would be focused on the validation.

**Comment by mmusich** [comment]
> The next opportunity would be the joint DPG/POG meeting on [Wed 24th](https://indico.cern.ch/event/1271487/?showDate=all&showSession=8#b-506191-joint-tracker-dpg-tra) though being TkWeek we should see if it fits.

@mandrenguyen please clarify if that slot suits you. Thank you.

**Comment by mandrenguyen** [comment]
+reconstruction
Changes in comparisons are as expected.
Since the changes to tracking are well localized to the heavy ion era, I think it makes sense to simply merge this for pre1 and then request a high-statistics validation.  I brought it up at the XEB and there was no objection from PPD.

**Comment by perrotta** [comment]
> +reconstruction Changes in comparisons are as expected. Since the changes to tracking are well localized to the heavy ion era, I think it makes sense to simply merge this for pre1 and then request a high-statistics validation. I brought it up at the XEB and there was no objection from PPD.

@mmusich would you have any objection from the Tracking POG side?

**Comment by mmusich** [comment]
> would you have any objection from the Tracking POG side?

No, as long as there is a clear path forward for physics validation, as it seems there is. +1 from me

**Comment by perrotta** [comment]
+1

**Pull request merged**
