### PR TITLE
EventFilter/EcalRawToDigi: change return type of ESProducer to uniue_ptr

### PR DESCRIPTION
**Pull request by gartung**

### CODE REVIEW

**Comment by gartung** [comment]
@Dr15Jones

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@Dr15Jones 
please confirm that the changes in this PR are OK

**Comment by Dr15Jones** [comment]
This PR is OK. From the frameworks perspective, it is better for ESProducers to return `std::unique_ptr` in the cases where the ESProducers have no need to hold onto the data products themselves. Making these changes now should make it easier in the future to migrate to a more thread-friendly EventSetup system.

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/22056	bc09764
- technical
- jenkins tests pass

**Comment by fabiocos** [comment]
+1

**Pull request merged**
