### PR TITLE
`DiMuonMassBiasClient`: add protection for empty input histogram in the fitting function

### LINKED ISSUE #39180: DiMuonMassBiasClient does not support concurrent lumis
Many workflows in CMSSW_12_5_X_2022-08-24-1100 fail with
```
----- Begin Fatal Exception 24-Aug-2022 15:57:39 CEST-----------------------
An exception of category 'ModulesSynchingOnLumis' occurred while
   [0] Calling beginJob
Exception Message:
The framework is configured to use at least two streams, but the following modules
require synchronizing on LuminosityBlock boundaries:
  DiMuonMassBiasClient ALCARECOTkAlDiMuonMassBiasClient

The situation can be fixed by either
 * modifying the modules to support concurrent LuminosityBlocks (preferred), or
 * setting 'process.options.numberOfConcurrentLuminosityBlocks = 1' in the configuration file
----- End Fatal Exception -------------------------------------------------
```

### PR DESCRIPTION
**Pull request by mmusich**
resolves https://github.com/cms-sw/cmssw/issues/39180

#### PR description:

Title says it all, forward-port of commit e03333cdd9bf894c4eca9b348e2538d6c195c89d from PR https://github.com/cms-sw/cmssw/pull/39166, needed to avoid getting stuck with the Voigtian fit on empty input histograms.
Also it removes from the path being run `DiMuonMassBiasClient` as it doesn't support (yet) concurrent lumis, see https://github.com/cms-sw/cmssw/issues/39180#issuecomment-1225931956

#### PR validation:

The unit test in the backport PR https://github.com/cms-sw/cmssw/pull/39166 with this commit now runs fine.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Forward-port from https://github.com/cms-sw/cmssw/pull/39166

### CODE REVIEW

**Comment by mmusich** [comment]
type bug-fix, trk

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
enable threading

**Comment by mmusich** [comment]
please test

**Comment by qliphy** [comment]
urgent

**Comment by emanueleusai** [comment]
+1

**Comment by perrotta** [comment]
+1
- @mmusich as you removed ALCARECOTkAlDiMuonMassBiasClient from the paths being run, how did you check that the fix is actually doing what intended? Is there a unit function somewhere that still test it, as you are suggesting in the PR description?

**Comment by mmusich** [comment]
@perrotta 
> as you removed ALCARECOTkAlDiMuonMassBiasClient from the paths being run, how did you check that the fix is actually doing what intended? Is there a unit function somewhere that still test it, as you are suggesting in the PR description

Yes, there is:

https://github.com/cms-sw/cmssw/blob/562ab3970c327bb8f19020b3c2e3eab1c49e5fbb/DQMOffline/Alignment/test/testDiMuonVertexMonitor.sh#L11

which calls:

https://github.com/cms-sw/cmssw/blob/562ab3970c327bb8f19020b3c2e3eab1c49e5fbb/DQMOffline/Alignment/test/DiMuonVertex_HARVESTING.py#L118-L123

Without the fix in commit https://github.com/cms-sw/cmssw/commit/e94b2f131d96d27eefa675eb02538c512278eac7 the unit test in the 12.4.x backport was failing, see [log](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-a5b591/27044/unitTests/src/DQMOffline/Alignment/test/testDiMuonVertexMonitor/testing.log), but after the fix (and *before* removing `ALCARECOTkAlDiMuonMassBiasClient` from the path being run) the tests did succed (see https://github.com/cms-sw/cmssw/pull/39166#issuecomment-1225920091).
This is how I noticed that a protection was needed,  because the input files of the unit test are different in 12.4.x than in master and generated the error state not previously seen in the master IBs.
I hope this explains

**Comment by perrotta** [comment]
Perfect, thank you @mmusich !

**Pull request merged**
