### PR TITLE
fix mistake in the last commit and remove pf cluster timing cut module

### PR DESCRIPTION
**Pull request by hengne**
fix a mistake in the last commit: 
https://github.com/cms-sw/cmssw/pull/7117

### CODE REVIEW

**Comment by hengne** [comment]
remove pf cluster timing cut module, refer to the discussion with Michalis on pull request #7117

**Comment by hengne** [comment]
comment out the importing line of the PF time selector

**Comment by bachtis** [comment]
Thanks Hengne!
M

**Comment by mark-grimes** [comment]
merge

Tested privately.

**Pull request merged**
