### PR TITLE
Update tracking MC validation scripts

### PR DESCRIPTION
**Pull request by makortel**
This PR updates the tracking MC validation scripts with the main changes being
- Include V0 validation plots
- Update PackedCandidate plots (followup to #12405)
- Support plots by originalAlgo and algoMask
  - When the histograms are available, e.g. MTV in standalone and trackingOnly modes
- Support plots for seeds and built tracks
  - When the histograms are available, e.g. MTV in trackingOnly mode
- Support comparing DQM files with different MTV subfolder naming conventions using a predefined fallback mechanism
  - E.g. to compare 80X and 62X_SLHC DQM files
- Include timing plots (from FastTimerService)
- Include tables in the summary report pages
- Tuning/additions of plots
- Decrease (stdout) verbosity

Based on 800pre4, standard workflows are not touched so no changes expected.

@rovere @VinInn

### CODE REVIEW

**Comment by VinInn** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
Could DQM (@deguio, @vanbesien) please review and sign? Thanks.

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
