### PR TITLE
EMTF emulate directly from unpacked CPPF digis

### PR DESCRIPTION
**Pull request by abrinke1**
To this point, the EMTF emulator has been taking in raw RPC hits and performing an emulation of the CPPF logic: clustering, sorting, and computing theta and phi coordinates for the hits.  With this PR, the new sequence for re-emulating data is:

1) EMTF unpacks the received CPPF digis into a CPPFDigiCollection
2) EMTF emulator uses this CPPFDigiCollection in the track-building

This brings the fraction of tracks with perfect data-emulator agreement up from ~92% to > 98%.  The emulator logic in MC is unaffected, as there is no CPPFDigi producer in MC at the moment.  The main practical benefit is better data-emulator agreement for DQM monitoring, and for offline performance studies.

Of potential interest to @jiafulow , @rekovic , @thomreis , @maseguracern , @camilocarrillo , @jhgoh , @mileva, @brieucf

Best regards,
Andrew

### CODE REVIEW

**Comment by rekovic** [comment]
please test

**Comment by abrinke1** [comment]
Hi @rekovic , @thomreis ,
Could you take a look and sign off on this?
Thanks, Andrew

**Comment by rekovic** [comment]
+1

**Comment by abrinke1** [comment]
Hi @fabiocos ,
It's not clear to me how to see the changed histograms.  Clicking through these folders, I don't see any plot comparison:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-23747/29061/DQMTestsResults/DQMTestsResults/
We do expect to see changes in the EMTF DQM, in particular improved data-emulator agreement - but the plan was to test this in the Online DQM Playback.  If the other checks are complete, I could make the request to deploy this PR in the DQM, before you make the final commit into CMSSW master.
Best,
Andrew

**Comment by fabiocos** [comment]
@abrinke1 https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_10_2_X_2018-07-09-2300+23747/27382/136.788_RunSinglePh2017B+RunSinglePh2017B+HLTDR2_2017+RECODR2_2017reHLT_skimSinglePh_Prompt+HARVEST2017/

from the summary.html got in "Comparison with the baseline" and pick the directory for 136.788...
If you click on the pie-charts with failure associated you will see the histograms.

I ask because these differences do not appear in 2018 workflow fior instance. May be the number of events is limited, or this code is not really running in 136.85, as that workflow is for a photon dataset?

**Comment by abrinke1** [comment]
Hi @fabiocos ,
These are exactly the sorts of plots that we do expect to change: EMTF data vs. emulator plots in DQM.  I'm not sure exactly what is run in each workflow, so I couldn't say if the 2018 workflow runs the full set of Online DQM plots.  Also, I don't know if the validation test will "fail" if there is any difference at all in the histograms, or if there is some % difference threshold it has to pass.  In most cases the differences will be small, and if the run did not have RPC and/or CPPF enabled, then there will be no difference at all.  For us, the full test of this will come when we deploy in the Online DQM -- though of course, we've already validated offline on 2018 data.
Cheers,
Andrew

**Comment by thomreis** [comment]
Hi @abrinke1 
please make also a backport PR to the 10_2_X branch.

**Comment by abrinke1** [comment]
10_2_X (https://github.com/cms-sw/cmssw/pull/24106) and 10_1_X (https://github.com/cms-sw/cmssw/pull/23919) back-ports created

**Pull request merged**
