### PR TITLE
Fix an incorrect (D)CFEB number assignment in the CSC CLCT producer for Run-3 L1T (CCLUT-12)

### PR DESCRIPTION
**Pull request by dildick**
#### PR description:

* It was reported that the Run-3 CCLUT trigger primitive algorithm shows weird behavior for CSC CLCTs when the key half-strip is on the edge of a (D)CFEB (key half-strip is 0 or 31). This PR fixes that. If a CLCT is on the edge, the (D)CFEB number is changed when the CCLUT-corrected half-strip crosses the (D)CFEB boundary.
* In addition, 3 class members are added to store the number of strips, half-strips and (D)CFEBs for a chamber.
* I also changed `bool noDigis` (which is used as a double-negative)  to `bool hasDigis`. 

#### PR validation:

Tested on a 10 GeV prompt muon sample produced with 11_0_X.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

@tahuang1991 @msd14

### CODE REVIEW

**Comment by silviodonato** [comment]
please test

**Comment by silviodonato** [comment]
@dildick @cms-sw/l1-l2 have you planned to use this fix in the next MWGR?

**Comment by dildick** [comment]
@silviodonato No, the CCLUT algorithm is still in testing at B904. It has not yet been deployed at P5. No backport required.

**Comment by dildick** [comment]
A few validation plots (not for publication). 

Eff_CSCCLCT_comparison_ME11
Eff_CSCCLCT_comparison_ME12
Eff_CSCCLCT_comparison_ME13
Eff_CSCCLCT_comparison_ME21
Eff_CSCCLCT_comparison_ME22
Eff_CSCCLCT_comparison_ME31
Eff_CSCCLCT_comparison_ME32
Eff_CSCCLCT_comparison_ME41
Eff_CSCCLCT_comparison_ME42
 
Res_CSCCLCT_poscomparison_ME11
Res_CSCCLCT_poscomparison_ME12
Res_CSCCLCT_poscomparison_ME13
Res_CSCCLCT_poscomparison_ME21
Res_CSCCLCT_poscomparison_ME22
Res_CSCCLCT_poscomparison_ME31
Res_CSCCLCT_poscomparison_ME32
Res_CSCCLCT_poscomparison_ME41
Res_CSCCLCT_poscomparison_ME42

**Comment by silviodonato** [comment]
@dildick I'm not sure the average CMS user is able to understand which detector are affected from "Fix incorrect CFEB assignment (CCLUT-12)". Please add some words about CSC and L1T. It happens often that people look at the release notes (eg. https://github.com/cms-sw/cmssw/releases/CMSSW_11_3_0_pre5) to find the origin of some changes observed in RelVals.

**Comment by dildick** [comment]
@silviodonato Done!

**Comment by dildick** [comment]
@silviodonato @rekovic Can this PR be merged?

**Comment by silviodonato** [comment]
is there any comment from @cms-sw/l1-l2

**Comment by cecilecaillol** [comment]
+l1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
