### PR TITLE
fix HLT track collection

### PR DESCRIPTION
**Pull request by mtosi**
bug fix of the DQM configuration for the track monitoring @HLT 
@JanFSchulte @Martin-Grunewald @silviodonato @rovere @VinInn @makortel

### CODE REVIEW

**Comment by mtosi** [comment]
@cmsbuild, please test

**Comment by Martin-Grunewald** [comment]
Need a 93X PR as well!

**Comment by mtosi** [comment]
yes, I know (I'm cherry picking the commit) thanks @Martin-Grunewald

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
