### PR TITLE
[92X] Improvements to L1 Offline DQM - part 3 - backport

### PR DESCRIPTION
**Pull request by kreczko**
Backport of PR #19797 (issue #19593)

### CODE REVIEW

**Comment by rekovic** [comment]
please test

**Comment by rekovic** [comment]
backport

**Comment by rekovic** [comment]
+1

**Comment by dmitrijus** [comment]
+1

**Comment by rekovic** [comment]
backport of  #19797

**Comment by davidlange6** [comment]
+1

**Comment by davidlange6** [comment]
@kreczko - i guess this needs a rebase thanks to the merging of parts 1 and 2

**Comment by kreczko** [comment]
@davidlange6 Indeed. I have now rebased the PR.

@rekovic @dmitrijus could you please re-sign.

The rebase had a conflict due to the input tag change:
```
-    caloMETCollection=cms.InputTag("caloMet"),
+    caloMETCollection=cms.InputTag("caloMetBE"),
+    # MET collection including HF
+    caloETMHFCollection=cms.InputTag("caloMet"),
```

**Comment by rekovic** [comment]
please test

**Comment by rekovic** [comment]
+1

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
