### PR TITLE
added esConsumes to modules in L1Trigger/CSCTrackFinder

### PR DESCRIPTION
**Pull request by JamminJones**
#### PR description:

added esConsumes to 2 modules

#### PR validation:

The code compiles

### CODE REVIEW

**Comment by Dr15Jones** [comment]
This change was made under my supervision.

**Comment by Dr15Jones** [comment]
please test

**Comment by silviodonato** [comment]
kind reminder @rekovic

**Comment by silviodonato** [comment]
merge

**Pull request merged**
