### PR TITLE
diphoton_hlt_filters_added

### PR DESCRIPTION
**Pull request by Soumyatifr**
Dear experts,
I have added the hlt_diphoton_filters which are essentially needed for the next iteraton of the NANOAOD production.
It is very urgent, can you kindly check and merged to the master branch.
Keeping Higgs to gamma/gamma convenor @lfinco here to keep track of it. 
Thanks and let me know if you need anything else for this.

### CODE REVIEW

**Comment by swertz** [comment]
Thanks @Soumyatifr , quick question: do you really need separate bits for all the added filters, or could they regrouped using a logical OR, according to the threshold? ie:
- `hltEG30LIso60CaloId15b35eHE12R9Id50b80eEcalIsoLastFilter OR hltEG30Iso60CaloId15b35eR9Id50b90eHE12b10eR9Id50b80eEcalIsoFilter`
- `hltEG22Iso60CaloId15b35eHE12R9Id50b80eTrackIsoUnseededLastFilter OR hltEG22R9Id85b90eHE12R9Id50b80eR9UnseededLastFilter`

(perhaps using globbing, such as `hltEG30*Filter` or however restrictive it needs to be, see other examples in the file)

**Comment by Soumyatifr** [comment]
@swertz Thanks for your comments, actually we need the seperate information for the individual filters. I have consulted this with @lfinco also. So kindly keep them in seperate bits. 
Thanks in advance.

**Comment by swertz** [comment]
enable nano

**Comment by swertz** [comment]
please test

**Comment by swertz** [comment]
please test

Retrying for timeouts

**Comment by swertz** [comment]
type egamma

**Comment by swertz** [comment]
please test

**Comment by swertz** [comment]
+1

Many more photon trigger objects selected, with the new filters (varying depending on the era):
image

**Comment by rappoccio** [comment]
+1

Expected changes are observed in the DQM plots.

**Pull request merged**
