### PR TITLE
add quality selections in MkFitOutputConverter

### PR DESCRIPTION
**Pull request by slava77**
This PR intends to address #35798, to reduce warnings about bad track states downstream of mkFit track building.

In addition to already present check for positive-definiteness of the covariance based on the diagonal elements, more selections were added to MkFitOutputConverter in order to send only trackable candidates:
- the covariance matrix is checked using the Sylvester's criterion to have a full check of positive-definiteness
- "sanity" checks for the track candidate parameters:
    - pt > 10 MeV
    - θ ∈ [0.01, π–0.01]
    - state position inside the tracker: r < 120 cm and |z| < 280 cm; position uncertainty below 100 cm

The CPU cost in the converter goes up by about 0.02% of the reco time based on wf 136.874: [before](https://slava77sk.web.cern.ch/slava77sk/reco/cgi-bin/igprof-navigator/sw-123X/CMSSW_12_3_0_pre1-sign1131.pass-e731805.136.874.step3.100.pp/1873) vs [after](https://slava77sk.web.cern.ch/slava77sk/reco/cgi-bin/igprof-navigator/sw-123X/CMSSW_12_3_0_pre1-sign1131.pass-bce63d6.136.874.step3.100.pp/1716)

The number of logWarnings went down, focusing on the ones with ` not pos` in the warning message (using `CMSSW_12_3_0_pre1` as a reference):
- in 136.874 on 100 events: baseline 112, noMkFit baseline 3, this PR 12.
    - the warnings are in modules not directly reading mkFit track candidates
- in wf 11834.21 on 400 events: baseline 2636, noMkFit 31, this PR 19
    - the warnings are in modules not directly reading mkFit track candidates
- in a trackingOnly test similar to 11834.21 with PU50 on 1000 events: baseline 2209, noMkFit 19, this PR 17
    - here 14 warnings are in modules reading mkFit track candidates

On average, it seems that the number of warnings is roughly back to the rate seen with the  old setup using just the CKF builder.

Small changes are expected due to rejection of mainly bad tracks.
@leonardogiannini checked in a sample with pileup 50 on 1000 evens, there are negligible or [no differences in the MTV plots](http://uaf-10.t2.ucsd.edu/~legianni/plotsMTV-FebTRKPOG/checkDeterminant/checkWarnings-final/plots_ootb.html):
looking at all tracks
image
The effect is a bit more visible in the pixelLess iteration, the most affected iteration
image

@osschar @makortel @mmasciov 
@cms-sw/tracking-pog-l2

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
> The effect is a bit more visible in the pixelLess iteration, the most affected iteration
> image

I've added the above observation to the PR description, since most of the logWarnings were in the pixelLess iteration.

**Comment by slava77** [comment]
@cms-sw/reconstruction-l2 
it would be nice to get this in pre6

**Comment by jpata** [comment]
assign @cms-sw/tracking-pog-l2

**Comment by mmusich** [comment]
> assign https://github.com/orgs/cms-sw/teams/tracking-pog-l2

not sure if you really wanted to assign this to `trk-pog`.
In any case @slava77 will you be able to summarize all the activity done towards the mitigation of https://github.com/cms-sw/cmssw/issues/35798 at the next TRK POG meeting on March 14th?

**Comment by slava77** [comment]
> In any case @slava77 will you be able to summarize all the activity done towards the mitigation of #35798 at the next TRK POG meeting on March 14th?

sure; towards the end of the agenda, if possible.
Also, this may become a part of a larger mkFit update, but I'm not sure yet if that part converges by March 14.

**Comment by perrotta** [comment]
+1
- Thank you @mmusich

**Pull request merged**
