### PR TITLE
DQM for HLT_Ele27_WPLoose_Gsf_WHbbBoost_v1 - 74X

### PR DESCRIPTION
**Pull request by silviodonato**
This PR add the validation cod for the trigger HLT_Ele27_WPLoose_Gsf_WHbbBoost_v1 (https://its.cern.ch/jira/browse/CMSHLT-343)

PR in 75X: https://github.com/cms-sw/cmssw/pull/9438

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
@silviodonato this does not merge now. Could you rebate. Thanks!

**Comment by davidlange6** [comment]
@cmsbuild, please test

**Comment by slava77** [comment]
-1
this needs a rebase

**Comment by deguio** [comment]
-1
rebased needed?

**Comment by silviodonato** [comment]
@deguio @slava77 
If I make the comparison from my branch I found only "3 files changed": https://github.com/cms-sw/cmssw/compare/CMSSW_7_4_X...silviodonato:DQMWHbb_74X
Here in the PR I have "Files changed 49". 
Do you know why?
Should I close and reopen the PR?

Thanks, Silvio.

**Comment by silviodonato** [comment]
I'm trying to close and re-open the PR

**Pull request closed without merging**
