### PR TITLE
Add support for untracked PSets and SwitchProducer to MassReplace tools

### LINKED ISSUE #28852: SwitchProducer does not meet the expectations of the mass replacement tools
`SwitchProducer` does not meet the expectations of the mass replacement tools in `FWCore.ParameterSet.MassReplace`. Noticed in https://github.com/cms-sw/cmssw/issues/28850#issuecomment-581149286
```
  File "/data/cmsbld/jenkins/workspace/auto-builds/CMSSW_11_1_0_pre2_Patatrack-slc7_amd64_gcc820/build/CMSSW_11_1_0_pre2_Patatrack-build/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_1_0_pre2_Patatrack/python/FWCore/ParameterSet/MassReplace.py", line 69, in enter
    self.doIt(visitee, label)
  File "/data/cmsbld/jenkins/workspace/auto-builds/CMSSW_11_1_0_pre2_Patatrack-slc7_amd64_gcc820/build/CMSSW_11_1_0_pre2_Patatrack-build/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_1_0_pre2_Patatrack/python/FWCore/ParameterSet/MassReplace.py", line 20, in doIt
    type = value.pythonTypeName()
AttributeError: 'EDProducer' object has no attribute 'pythonTypeName'
```

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

This PR fixes #28852. Before doing it, I took a round of traversing also untracked `PSet` and `VPSet` because I wanted to replace `pythonTypeName()` with `isinstance` for the type inspection.

For normal modules the `MassSearchReplaceParamVisitor` checks only the given parameter name, i.e. it does not descend into nested PSets. For `SwitchProducer` I **believe** the expected behavior would be to do the replacement for each contained `EDProducer`/`EDAlias`.

#### PR validation:

Unit tests run.

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
@Dr15Jones or @wddgit, could you please review?

**Comment by makortel** [comment]
I had understood wrongly the deepcopy logic

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by wddgit** [comment]
@makortel I reviewed it and did not notice any problems as I read through the new code. +1 from me.

**Comment by makortel** [comment]
+1

Thanks @wddgit

**Comment by silviodonato** [comment]
+1

**Pull request merged**
