### PR TITLE
DAQ: fix file descriptor close in DAQSource (13_1_X)

### PR DESCRIPTION
**Pull request by smorovic**
#### PR description:
Fixes fd close when end of file is reached. Assert is added in case this is not caught (should not happen) to avert leaving open files (fd leak).

#### PR validation:

Tested by running with this patch in daq3val cluster.

### CODE REVIEW

**Comment by smorovic** [comment]
@cmsbuild please test

**Comment by smorovic** [comment]
please test

**Comment by smorovic** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
