### PR TITLE
Run3-alca184 Add a new analyzer for studies of HCAL using isotrack and muons

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Add a new analyzer for studies of HCAL using isotrack and muons

#### PR validation:

Tested using MC and data files

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by qliphy** [comment]
please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by yuanchao** [comment]
+1

* new HCAL analyzer using isotrack and muons
* matrix tests and unit tests passed
* build warnings are not due to this PR

**Comment by qliphy** [comment]
+1

**Pull request merged**
