### PR TITLE
fix hep17 and hf compression luts

### PR DESCRIPTION
**Pull request by akhukhun**
Backport of #18173 .

### CODE REVIEW

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by abdoulline** [comment]
@akhukhun 
I suppose it's indispensable for 901 MC production(s)?

**Comment by akhukhun** [comment]
@abdoulline it should not have dramatic effect but I guess it's better to have it fixed this way.

**Comment by abdoulline** [comment]
OK, let's aim for getting it into 901

**Comment by franzoni** [comment]
same comments as:
https://github.com/cms-sw/cmssw/pull/18173#issuecomment-292529047

**Comment by franzoni** [comment]
+1

**Comment by rekovic** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
