### PR TITLE
Initialize members in initializer list in HGCalTriggerValidator

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

This PR is a preparatory step to change PluginFactory to return `std::unique_ptr`.

#### PR validation:

Code compiles.

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by jfernan2** [comment]
Hi @makortel
We don't have you identifed as DQM developer in: 
https://twiki.cern.ch/twiki/bin/viewauth/CMS/DQMContacts#HGCAL 
Could you please add yourself in the corresponding e-group for future references? 
Thanks

**Comment by makortel** [comment]
@jfernan2 I'm core software developer.

**Comment by jfernan2** [comment]
Sorry @makortel I got confused by the PR title

**Comment by jfernan2** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
