### PR TITLE
Modifier to apply energy corrections to photons and electrons (miniAOD) for 75X

### PR DESCRIPTION
**Pull request by lgray**
This PR implements the latest energy corrections for GED electrons and photons and applies them during MiniAOD processing.

ECAL regressions are done using GBRLikelihood and a good boost in resolution is expected compared to the previous BDTs. 
The track + ECAL combination is done with a standard BDT, but the inputs are updated to use the semi-parametric BDT output.

The ES Prefers will removed once the weights will be integrated into the GT.
Working on comparison plots for the resolution.

Supersedes #10611

### CODE REVIEW

**Comment by slava77** [comment]
@lgray the description is outdated by now (ref files are never more; the payloads are in the DB now; the GT is still not available though)

**Comment by lgray** [comment]
@slava77 done.

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
@diguida any idea why this failed?

(Sent from my Nexus 6)

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
@slava77 looks like this set of jenkins tests will fail again due to tags not being in the GT.
@diguida any idea why? I see the tags in the conditions DB web browser for 75X.

**Comment by lgray** [comment]
@diguida Correction: I see now that the payloads in 75X are GBRForest and not GBRForestD. Any idea what the ETA there is? I guess we are waiting on a 76X pre-release?

**Comment by slava77** [comment]
@mmusich @diguida 
Please comment on expected availability of a GT with the GBRForestD.
A new  75X build is imminent, based on the ORP meeting.
It would be better to have this PR there, if we can't get a GT, we can stick to esprefer, put that's not really preferable.

**Comment by mmusich** [comment]
@slava77 we can build the GT tomorrow.
@lgray please include both conveners next time in the discussion

**Comment by lgray** [comment]
@mmusich noted

**Comment by mmusich** [comment]
@lgray working on the GT I noticed there are requests for tags `GBRForestD_gedelectron_p4combination_50ns_v0` with label `gedelectron_p4correction_50ns` and `GBRForestD_gedelectron_p4combination_25ns_v0` with label `gedelectron_p4correction_25ns` that seem to be unnecessary (looking to the PR code). Shall I just discard them?

**Comment by lgray** [comment]
@mmusich keep the "combination" version of the tags. Correction was an error from a previous attempt.

**Comment by lgray** [comment]
rebasing...

**Comment by lgray** [comment]
@mmusich OK - rebased. Let me know when the GT goes into 75X.
@slava77

**Comment by mmusich** [comment]
@lgray please cherry-pick from #10872 

```
git cms-addpkg Configuration/AlCa
git remote add mmusich https://github.com/mmusich/cmssw.git
git fetch mmusich
git cherry-pick 1e0e17905bf20a391212b47483b173993d17fd32
```

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by mmusich** [comment]
+1 
for https://github.com/lgray/cmssw/commit/4cc7bf1a01e122e050bce75a32734efc8a2cecbf

**Comment by mmusich** [comment]
@slava77 I have other requests for 75X in the pipeline. I didn't merge all of them to allow you to test the new regressions separately. Let me know when you're done with this, so that I can move on with the rest

**Comment by lgray** [comment]
@mmusich since it is +1'd by slava in #10689 and matrix tests now run here without using ESPrefers  you may proceed.

**Comment by lgray** [comment]
@mmusich Just let me know if I need to remove 4cc7bf1 from my history at some point.

**Comment by mmusich** [comment]
@lgray just to make sure: are there any ESPrefers, toGet or any other customization of conditions around yet?

**Comment by lgray** [comment]
@mmusich No, they have been removed from this PR.

**Comment by mmusich** [comment]
@lgray no need too. I'll make a new PR with a superseding version of some of the GTs.

**Comment by lgray** [comment]
@mmusich OK, great. Please ping me again once you have something similar for 74X and I can start the tests there too.

**Comment by slava77** [comment]
Marco,

if your requests can be merged today, I can catch up later with a test
of this PR
on top of those.

**Comment by mmusich** [comment]
@lgray the 74X equivalent is ready #10883 please cherry-pick where needed (#10598 I suppose).

**Comment by lgray** [comment]
@mmusich Thanks a lot!

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/10690	 4cc7bf1
- backport from the 76X version is done correctly (changes are the same as in https://github.com/cms-sw/cmssw/pull/10689	e9ad0ce)
- the code runs both in this setup (GT PR wasn't merged in CMSSW_7_5_X_2015-08-19-2300 used in jenkins) as well as on top of CMSSW_7_5_X_2015-08-20-2300
- changes in jenkins show up only in the electon miniAOD DQM. The following is from wf 4.53 in jenkins
wf4 53_slimmedele_det_vs_et

**Comment by monttj** [comment]
+1

**Comment by lgray** [comment]
Sorry for clearing the signatures ... again ...
I had to correct a bug in the photon regressions value maps.

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
@cmsbuild please test

@slava77 I am done double checking for residual use of full5x5. Done messing with this PR.

**Comment by lgray** [comment]
@mmusich @diguida could you please resign? Thanks!

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/10690	4b5cd3b

- changes in the code since the last signoff (https://github.com/lgray/cmssw/compare/4cc7bf1a0...4b5cd3b)  are the same as  https://github.com/cms-sw/cmssw/pull/10921	 0c57abf
- jenkins tests passed 
    - ... not many comparisons made it to the comparisons results
    - the ones that made it show differences only in miniAOD DQM, showing an effect of now applied corrections (similar to what was posted here earlier)
- tested locally in CMSSW_7_5_X_2015-08-20-2300 /test area sign580/, comparing specifically with respect to the last iteration in https://github.com/cms-sw/cmssw/pull/10690	 4cc7bf1
    - there are minor changes in the electron miniAOD DQM observables (photons should be changing as well, but they are not monitored). E.g.  in 251721 DoubleEG over 200 events (left/black is 4cc7bf1, right/red is 4b5cd3b)
wf251721doubleeg_slimmedele_det
wf251721doubleeg_slimmedele_pt

**Comment by slava77** [comment]
@monttj 
please re-sign if there are no issues
Thanks

**Comment by monttj** [comment]
+1

**Comment by mmusich** [comment]
+1 
for https://github.com/lgray/cmssw/commit/4cc7bf1a01e122e050bce75a32734efc8a2cecbf

**Comment by mmusich** [comment]
@lgray the bot doesn't seem to react to any of my actions....

**Comment by lgray** [comment]
Sometimes the bot is asleep.

FYI I am in Japan on vacation, my personal response will also be very
limited from now on.

(Sent from my Nexus 6)

**Comment by smuzaffar** [comment]
GitHub was under DDos attack yesterday and that is why cms-bot was not able to process your comments

**Comment by davidlange6** [comment]
+1

**Pull request merged**
