### PR TITLE
Run3-alca236 Make small changes to a few scripts in Calibration/HcalCalibAlgos

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Make small changes to a few scripts in Calibration/HcalCalibAlgos which are used in the latest calibration studies

#### PR validation:

Use them to analyse 2022 calibration data

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by tvami** [comment]
@bsunanda please include `HcalCalibAlgos` in the PR title, as of now, it's a very general text and could mean anything :) Thanks

**Review by ChrisMisan — COMMENTED** [review]
couts should be removed, maps in some cases could've been replaced by the unordered implementation but given this is in "macros" and is not related directly to the changes I see no reason to hold up this pr.

**Comment by ChrisMisan** [comment]
+alca

- no significant changes detected

**Comment by rappoccio** [comment]
+1

**Pull request merged**
