### PR TITLE
Change tau trigger bits stored in NanoAOD

### PR DESCRIPTION
**Pull request by mbluj**
#### PR description:

The tau trigger bits in NanoAOD never provided a match in 2018 triggers because the 'Hps' part in the name was forgotten. This PR is meant to fix this issue as well as to prepare to accommodate Run-3 tau triggers. We have decided to go with a unified strategy that will work for both Run-2 and Run-3 triggers which have similar structure and naming conventions, hence the addition of extra bits containing DeepTau. It now also contains trigger bits for taus in the PAG VBF and displaced tau triggers. A full overview of all trigger filters in Run-2 and Run-3 was made and is contained in google sheets [here](https://docs.google.com/spreadsheets/d/1L8P4HeiUSaisewuSFBEJOM5t5xXcDjNbfBtD9hEE5F8/edit#gid=0)

**Changes**:
* Addition of wildcards to original trigger bits to work for both HPS and non-HPS paths;
* Addition of DeepTau trigger bits;
* Addition of bits 4096 to 32768 to include PAG paths;
* Addition of bits 65536 for completeness, they allow to go a bit more specific in the triggers to select;
* Addition of boosted tau block. Right now the bits are redundant, but we expect more to be added in the future;
* Added bits to non-tau blocks from cross triggers.

#### PR validation:
Reran NanoAOD for all three Run-2 years and in a Run-3 sample, everything seemed to act as expected

### CODE REVIEW

**Comment by mariadalfonso** [comment]
@mbluj
as expected there are differences in the [NanoAODDQM]/[TrigObj]
You can have a look here and report on if is all expected
https://gitlab.cern.ch/cms-nanoAOD/nanoAOD-integration/-/issues/155

**Comment by mbluj** [comment]
> @mbluj as expected there are differences in the [NanoAODDQM]/[TrigObj] You can have a look here and report on if is all expected https://gitlab.cern.ch/cms-nanoAOD/nanoAOD-integration/-/issues/155

@mariadalfonso, could you remind me please how to access DQM plots from outside CERN?

**Comment by mariadalfonso** [comment]
@mbluj  here  the plots
Screen Shot 2022-06-24 at 11 17 29
Screen Shot 2022-06-24 at 11 17 04
Screen Shot 2022-06-24 at 11 16 42

**Comment by mbluj** [comment]
For me changes in fired trigger bits seem sensible; distributions describing trigger objects seem to agree between updated and reference, but I am not sure how to interpret the fact that numbers of entries are different - if it is an issue of DQM that different number of input events is compared or it is because of different filtering of trigger with modified trigger bits. Anyway, local tests were successful.
@lwezenbe @kandrosov could you cross check it and comment, please?

**Comment by kandrosov** [comment]
For tau trigger objects pre-selection is changed, so changes in size are expected. Why size has changed for jets - I don't know... @mariadalfonso - is there some requirement that one trigger object can belong to only one TrigObj nanoAOD type? E.g. if one miniAOD trigger objects pass pre-selection for two nanoAOD trig object types, would it be stored as two nanoAOD TrigObj?

We have introduced a new object type `BoostedTau`. If exclusivity is enforced, it might reduce the amount of `Jet` objects.

**Comment by mariadalfonso** [comment]
> For tau trigger objects pre-selection is changed, so changes in size are expected. 

indeed this done in 
https://github.com/cms-sw/cmssw/pull/38472/files#diff-9b898944f08810913ea5c1605c47bd9a6c99eb91fc20f491ba2767702f4a0184R85

> Why size has changed for jets - I don't know... @mariadalfonso - is there some requirement that one trigger object can belong to only one TrigObj nanoAOD type? E.g. if one miniAOD trigger objects pass pre-selection for two nanoAOD trig object types, would it be stored as two nanoAOD TrigObj?
>

The plot of size of jets seems unchanged, but the plots of the properties changes because we have have more match due to the  4 more bits added
https://github.com/cms-sw/cmssw/pull/38472/files#diff-9b898944f08810913ea5c1605c47bd9a6c99eb91fc20f491ba2767702f4a0184R149

> 
> We have introduced a new object type `BoostedTau`. If exclusivity is enforced, it might reduce the amount of `Jet` objects.

Let me know what you think.
is good from my side, 

@mbluj can you prepare the 12_4 backport ?

**Comment by mbluj** [comment]
I think it is fine also from Tau side. @kandrosov please comment if it is not true.

Yes, I will prepare a backport to 12_4 soon (hopefully later today).

**Comment by kandrosov** [comment]
@mariadalfonso in the [plot](https://user-images.githubusercontent.com/5656714/175505084-b92e9ee8-3ebb-4605-bb4f-1d1527a9a857.png) you've posted above, there are differences in `_size` distribution for `TrigObj/Jet`, or I'm misreading the plot?
Except that, all the rest looks fine to me.

**Comment by mariadalfonso** [comment]
+xpog

updates to the trigger bit for both Run2 and Run3 nano.

**Pull request merged**
