### PR TITLE
[RECONSTRUCTION-XPOG] [LLVM14] Apply code checks

### PR DESCRIPTION
**Pull request by smuzaffar**
Applying code checks changes suggested by LLVM 14 ( which we want to integrate in cmssw once fully testing in CLANG IBs).
[performance-unnecessary-copy-initialization](https://releases.llvm.org/14.0.0/tools/clang/tools/extra/docs/clang-tidy/checks/performance-unnecessary-copy-initialization.html) check suggested these modifications.

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@cms-sw/reconstruction-l2  can you please review/sign this?

**Comment by mandrenguyen** [comment]
+reconstruction

**Comment by perrotta** [comment]
+1
- @cms-sw/xpog-l2 this is trivial: let bypass your signature

**Comment by perrotta** [comment]
merge

**Pull request merged**
