### PR TITLE
Fix SiPM pulses

### PR DESCRIPTION
**Pull request by kpedro88**
This PR is a major step toward resolving the problem of strange output pulses from the SiPM simulation.

Slides detailing my reasoning: http://kjplanet.com/pr/sipm_pulse_study_3.pdf

Slides validating the fix (from @mariadalfonso): http://dalfonso.web.cern.ch/dalfonso/HCAL/oct11/Phase1Jul21_ValidationDIGIFIX.pdf

@slava77 this could have some impact on the performance observed in #15959.

This PR may be updated shortly with an additional change to the RECO pulse shape (still being tested).

### CODE REVIEW

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
tests got stuck apparently.
In my local tests I see changes in HO.

I suppose, this is intended.
Kevin, please clarify.
There are no HO MC plots in the .pdf you have linked, although the change appears to be generic for all SiPMs.

**Comment by kpedro88** [comment]
Yes, this problem affected anything using the SiPM simulation (apparently for many years), so the fix will alter results for both HO and HE.

**Comment by slava77** [comment]
+1 (informal) from me: this clearly improves things on the reco side. See notes in https://github.com/cms-sw/cmssw/pull/15959#issuecomment-253260387

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
