### PR TITLE
Btag paths modification

### PR DESCRIPTION
**Pull request by natalia-korneeva**
btag@hlt re-enabling
btag paths modification
removing noisy warnings

### CODE REVIEW

**Comment by mtosi** [comment]
@cmsbuild, please test

**Comment by mtosi** [comment]
@natalia-korneeva thanks for this PR

in order to avoid such noise next time we will have the config file not in synch w/ the HLT menu,
could you please try to improve the c++ code ?

thanks

**Comment by natalia-korneeva** [comment]
@mtosi I already switched off the module which produce warnings, so there will be no noise (I tested it with the meaningless HLT menu)

**Comment by heppye** [comment]
@dmitrijus , could DQM please check and sign off the PR? (urgent updates for BTV@HLT RelVal). Thanks.

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
"in order to avoid such noise next time we will have the config file not in synch w/ the HLT menu," is basically impossible. probably a different approach is needed from hlt. @mtosi

**Comment by mtosi** [comment]
well,
a part having specific sequences to be used by runTheMatrix
I was thinking to the code matti and I added to some of our code in order
to stress/point the issue, but only once ....

**Comment by davidlange6** [comment]
@mtosi - i don't really understand your comment...

**Comment by davidlange6** [comment]
+1

**Comment by mtosi** [comment]
@davidlange6 
I was referring to what matti and I used as trick
in order to limit the number of print out
for instance
https://github.com/cms-sw/cmssw/pull/17996/files#diff-e017c390d8c85647725a77df4134c891R258

**Pull request merged**
