### PR TITLE
Migrate `assert` to to `ALPAKA_ASSERT_ACC`

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Migrate `assert()` to `ALPAKA_ASSERT_ACC()`.

#### PR validation:

None.

To be backported to 14.0.x for data taking.

### CODE REVIEW

**Comment by fwyzard** [comment]
Fixes #44792.

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
urgent

Backport needed for data taking.

**Comment by fwyzard** [comment]
enable gpu

**Comment by fwyzard** [comment]
+heterogeneous

**Comment by mandrenguyen** [comment]
+1

**Comment by perrotta** [comment]
+1

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
