### PR TITLE
Try converting RecoParticleFlow/PFTracking to GBRForest + GlobalCache (75X)

### PR DESCRIPTION
**Pull request by lgray**
Backport of #10143

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
tests stuck here please resubmit.

**Comment by Dr15Jones** [comment]
@smuzaffar the tests appear stuck

**Comment by davidlange6** [comment]
Please test
(Chris you can ask too)



On Jul 28, 2015, at 1:59 PM, Chris Jones <notifications@github.com<mailto:notifications@github.com>> wrote:


@smuzaffar<https://github.com/smuzaffar> the tests appear stuck

**Comment by Dr15Jones** [comment]
I had assumed that since the bot was stuck in testing, a manual intervention would be needed to start testing again. Seems I was wrong.

**Comment by cvuosalo** [comment]
+1

For #10367 17de6f265afa03931d958bdaa5559dce0c36b21e

Putting GBRForest objects into edm::GlobalCaches to reduce memory usage for multi-threaded jobs. There should be no significant changes in monitored quantities. Reduction in memory use has been verified in the already merged 76X version of this PR, #10143.

The code changes are satisfactory, and Jenkins [tests](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-10367/2726/summary.html) against baseline CMSSW_7_5_X_2015-07-28-1100 show no significant differences, as expected.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
