### PR TITLE
FixLumisPerJobSplittingFor2018

### PR DESCRIPTION
**Pull request by srimanob**
#### PR description:
Fix LumisPerJobSplitting For 2018 which changed from Prompt to Offline in
https://github.com/cms-sw/cmssw/pull/26417/files

#### PR validation:
https://cmsweb.cern.ch/reqmgr2/fetch?rid=request-srimanob_RVCMSSW_11_0_0_pre5RunEGamma2018C__PHATTEST_RelVal_2018C_190831_214637_5994

#### if this PR is a backport please specify the original PR:
-

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by chayanit** [comment]
please test

**Comment by srimanob** [comment]
Test job is done, and no. of events is as expected:
https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=CMSSW_11_0_0_pre5__data2018C_PHATTEST-1567280726-RunEGamma2018C

Ref: 10_6_0_pre2
https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=CMSSW_10_6_0_pre2__data2018C-1552977809-RunEGamma2018C

**Comment by chayanit** [comment]
+1

**Comment by fabiocos** [comment]
@kpedro88 this is not upgrade specific, please have a look at your earliest convenience, it is a fix that would be good to get soon

**Comment by kpedro88** [comment]
+upgrade

**Comment by fabiocos** [comment]
+1

**Pull request merged**
