### PR TITLE
Add Gen vertex time and position to NanoAOD

### PR DESCRIPTION
**Pull request by kdlong**
#### PR description:

Adds the Gen vertex x,y,z position and time (t0) as a new table in the NanoAOD. 

This is needed for an ongoing study in the W mass analysis to determine the rate at which the primary vertex is not correctly assigned with the sum pt^2 algorithm. t0 could be useful for exotics searches. According to @bendavid adding such info to the nano has been discussed briefly in the physics tools workshop planning.

#### PR validation:

I checked that the info gets added properly to a test MC sample. I just took the precision position from the reco vertex. For t0, I don't know what the needed precision would be.

### CODE REVIEW

**Comment by mariadalfonso** [comment]
please test

**Comment by santocch** [comment]
+1

**Comment by mariadalfonso** [comment]
@kdlong 

I see some problem when running on the EOY16.
you can reproduce the problem running on 
/store/relval/CMSSW_9_4_9_cand2/RelValTTbar_13/MINIAODSIM/94X_mcRun2_asymptotic_v3_PU_RelVal_rmaod-v1/10000/C8DD1D3F-AD83-E811-97F6-0025905B85EC.root


----- Begin Fatal Exception 05-Nov-2020 12:17:37 CET-----------------------
448An exception of category 'ProductNotFound' occurred while
449   [0] Processing  Event run: 1 lumi: 1 event: 2 stream: 2
450   [1] Running path 'nanoAOD_step'
451   [2] Calling method for module SimpleXYZPointFlatTableProducer/'genVertexTable'
452Exception Message:
453Principal::getByToken: Found zero products matching all criteria
454Looking for type: ROOT::Math::PositionVector3D<ROOT::Math::Cartesian3D<float>,ROOT::Math::DefaultCoordinateSystemTag>
455Looking for module label: genParticles
456Looking for productInstanceName: xyz0
457   Additional Info:
458      [a] If you wish to continue processing events after a ProductNotFound exception,
459add "SkipEvent = cms.untracked.vstring('ProductNotFound')" to the "options" PSet in the configuration.

**Comment by kdlong** [comment]
Thanks @mariadalfonso. Maybe someone else knows if the format of this product changed at some point, or could vary by workflow?

**Comment by kdlong** [comment]
It doesn't make a ton of sense to me since this code was last changed 4 years ago: https://github.com/cms-sw/cmssw/blame/a04f0be710b1a3f725547078ed117a61caeafebe/PhysicsTools/HepMCCandAlgos/plugins/GenParticleProducer.cc#L155

Is there any reason this module wouldn't be produced or would have a different name in this relval workflow?

**Comment by kdlong** [comment]
Ok, according to @bendavid this wasn't added in MiniAOD until recently.  I'll add some checks based on the era

**Comment by mariadalfonso** [comment]
> Ok, according to @bendavid this wasn't added in MiniAOD until recently. I'll add some checks based on the era

we might want to have only for the UL , so something like this might work
```
for modifier in run2_nanoAOD_92X, run2_miniAOD_80XLegacy, run2_nanoAOD_94X2016, run2_nanoAOD_94X2016, run2_nanoAOD_94XMiniAODv1, run2_nanoAOD_94XMiniAODv2, run2_nanoAOD_102Xv1:
  modifier.toModify( nanoSequenceFS.remove(genVertexTables) )
```

please add also someDQM plot

**Comment by mariadalfonso** [comment]
please test workflow 546,547,548

**Comment by mariadalfonso** [comment]
integration tests of central still shows the same problem 


----- Begin Fatal Exception 09-Nov-2020 20:43:54 CET-----------------------
451An exception of category 'ProductNotFound' occurred while
452   [0] Processing  Event run: 1 lumi: 1 event: 1 stream: 0
453   [1] Running path 'nanoAOD_step'
454   [2] Calling method for module SimpleXYZPointFlatTableProducer/'genVertexTable'
455Exception Message:
456Principal::getByToken: Found zero products matching all criteria
457Looking for type: ROOT::Math::PositionVector3D<ROOT::Math::Cartesian3D<float>,ROOT::Math::DefaultCoordinateSystemTag>
458Looking for module label: genParticles
459Looking for productInstanceName: xyz0
460   Additional Info:
461      [a] If you wish to continue processing events after a ProductNotFound exception,
462add "SkipEvent = cms.untracked.vstring('ProductNotFound')" to the "options" PSet in the configuration.

**Comment by mariadalfonso** [comment]
please test workflow 546,547,548

**Comment by mariadalfonso** [comment]
on the positive side  confirm that the central nano runs this time.
here some plots from 
http://nanoaod.cern.ch:8060/dqm/dev/start?runnr=1;dataset=/RelVal_MC106Xul17_TTH/CMSSW_11_2_X_2020-11-11-1100-32008-2085938-diff/DQM;sampletype=offline_relval;filter=all;referencepos=ratiooverlay;referenceshow=all;referencenorm=False;referenceobj1=other%3A%3A/RelVal_MC106Xul17_TTH/CMSSW_11_2_X_2020-11-11-1100-32008-2085938-diff-ref/DQM%3A;referenceobj2=none;referenceobj3=none;referenceobj4=none;search=;striptype=object;stripruns=;stripaxis=run;stripomit=none;workspace=Everything;size=M;root=Physics/NanoAODDQM/GenVtx;focus=;zoom=no;

t0 is not filled, for x,y we can probably improve the binning of the dam hosts, the z vertex looks good

**Comment by mariadalfonso** [comment]
please test workflow 546,547,548

**Comment by mariadalfonso** [comment]
please test workflow 546,547,548

**Comment by kdlong** [comment]
@gpetruc @peruzzim Since the Vertex XYZ is in a 3Vector class, but the t0 is just a float in the event, I couldn't add them together with a single producer (At least I saw no way to do it with the simpleflattable producer). Instead I tried a trick, just naming the separate t0 table GenVtx_t0. This works and looks fine in the file. However, when I try to add a DQM plots with 

GenVtx_t0 = ... plots('', ...) it isn't filled in the DQM file.

Is this expected? Is there possibly an easy way around it? I can always just name the t0 differently, without an underscore, if this is expected cause problems.

**Comment by peruzzim** [comment]
@klong you should include the `t0` via an extension table (additional column to existing table, ignore the comment in the quoted lines) as done in:
https://github.com/cms-sw/cmssw/blob/5a9032753050e752ce6ae087a3edb5a28f8aaf3e/PhysicsTools/NanoAOD/python/particlelevel_cff.py#L139
https://github.com/cms-sw/cmssw/blob/5a9032753050e752ce6ae087a3edb5a28f8aaf3e/PhysicsTools/NanoAOD/python/vertices_cff.py#L27
and plot it as the other variables in the GenVtx collection in DQM.

**Comment by kdlong** [comment]
Thanks @peruzzim. Is this supported in the GlobalVariablesTableProducer though? I don't see an "extension" option there.

**Comment by kdlong** [comment]
@peruzzim and I discussed this a bit more offline. It would nice if the XYZ and t0 were in the same object, but it seems like their is no 4D class corresponding to the ROOT Point3D class used to store the XYZ. We could make one, but this seems not worth it to me.

Instead, I added the option for the GlobalVariablesTables to be an extension. It is false by default, and should be transparent to all the current workflows. I tested that this works and that it appears in the DQM (and is filled now).

If there is a strong opposition to this, I would just 1) Rename the GenVtx_t0 so it is in it's own table that doesn't clash with the GenVtx table 2) drop t0 for now

**Comment by mariadalfonso** [comment]
please test workflow 546,547,548

**Comment by peruzzim** [comment]
> @peruzzim and I discussed this a bit more offline. It would nice if the XYZ and t0 were in the same object, but it seems like their is no 4D class corresponding to the ROOT Point3D class used to store the XYZ. We could make one, but this seems not worth it to me.
> 
> Instead, I added the option for the GlobalVariablesTables to be an extension. It is false by default, and should be transparent to all the current workflows. I tested that this works and that it appears in the DQM (and is filled now).
> 
> If there is a strong opposition to this, I would just 1) Rename the GenVtx_t0 so it is in it's own table that doesn't clash with the GenVtx table 2) drop t0 for now

@kdlong why don't you use `reco::Vertex`? It has a simple constructor that takes position, error matrix (you can set it to null) and time.

**Comment by bendavid** [comment]
@peruzzim the discussion we're having here is exactly the reason xyz and t0 are stored in separate branches in the AOD and MINIAOD in the first place.

We can perhaps change that for future releases, but presumably we can just deal with this fact at the nanoaod level for the moment...

**Comment by kdlong** [comment]
@peruzzim I really don't think the current solution is less elegant than putting a gen object in a reco class, and given that it's working and I understood the deadline was today, I'd rather not revisit it.

**Comment by mariadalfonso** [comment]
With the last implementation the DQM is finally fixed.
The current solution extend the GlobalVariablesTableProducer along what was suggested here 
https://github.com/cms-sw/cmssw/pull/32008#issuecomment-726610444
Eventually things can be improved for nanoV9 following the discussion in the pr

**Comment by mariadalfonso** [comment]
+xpog

**Comment by silviodonato** [comment]
merge

**Comment by santocch** [comment]
+1

**Pull request merged**
