### PR TITLE
remove one HLT-related histogram from E/Gamma offline DQM

### PR DESCRIPTION
**Pull request by missirol**
#### PR description:

This PR removes an histogram related to HLT from the outputs of the E/Gamma offline DQM. This histogram is sensitive to the list of triggers in the HLT menu, and it has led to confusion in #40700. In my opinion, this histogram is not helpful in this part of the DQM (the HLT outputs are already monitored by other dedicated DQM plugins).

Merely technical. No changes expected, except for the removal of the histogram in question.

#### PR validation:

None.

#### If this PR is a backport, please specify the original PR and why you need to backport that PR. If this PR will be backported, please specify to which release cycle the backport is meant for:

N/A

### CODE REVIEW

**Comment by missirol** [comment]
please test

**Comment by emanueleusai** [comment]
please test

**Comment by missirol** [comment]
@cms-sw/dqm-l2 , can you please review/sign this PR ?

**Comment by emanueleusai** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
