### PR TITLE
Sim G4 Geometry Converter for Extruded Polygon Shape

### PR DESCRIPTION
**Pull request by ianna**
* Integrate new Extruded Polygon solid in Simulation
* Add access to its parameters
* Add unit tests

@bsunanda and @civanch - FYI

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by civanch** [comment]
@ianna , in DDSolid there are many "auto" where "auto" is defined by expression and final type is not obvious. In this case, I would use real types to avoid confusions.

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by ianna** [comment]
@civanch - please, let me know if the changes are satisfactory. I need this PR in order to implement the shape visualization which is the next PR.

**Comment by civanch** [comment]
+1

**Pull request merged**
