### PR TITLE
(Backport) Hcal: Fix the TDC Simulation Algorithm

### PR DESCRIPTION
**Pull request by lwang046**
back port of #32729. 

This fix doesn't affect DIGI/RECO output in any workflow as TDC info it not used by any consumer at the moment. It's used (with explicit customization) only in special HCAL samples produced on demand for LLP physics studies

### CODE REVIEW

**Comment by abdoulline** [comment]
@civanch  Vladimir, could you do "please test"?

**Comment by civanch** [comment]
please test

**Comment by abdoulline** [comment]
(1) wf 4.76 fails as it couldn't get an access to data (as in other PRs)
(2) quick look at the DQM bin-by-bin shows difference solely in QIE11 (2018 HE,  >=2021 HB/HE)  TDC plots, as expected. 

@lwang046    Long, please, take a look at (2)  
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_11_2_X_2021-01-25-2300+42f3cb/40982/dqm-histo-comparison-summary.html
to make sure the change in TDC distributions look as expected.

**Comment by lwang046** [comment]
From the available distributions in DQM they look reasonable and resemble what was saw about TDC info in 2018 isolation data.

**Comment by abdoulline** [comment]
OK, thanks!

**Comment by civanch** [comment]
+1

changes expected; failed WF is due to files absence not this PR.

**Comment by qliphy** [comment]
+1

**Comment by qliphy** [comment]
merge

**Pull request merged**
