### PR TITLE
Phase2-hgx360T Make a test code to find the area of HGCal cells through the method "cellArea" of HGCalDDConst

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Make a test code to find the area of HGCal cells through the method "cellArea" of HGCalDDConst

#### PR validation:

Use this code to test the cell area evaluation

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by Moanwar** [comment]
+Upgrade

**Comment by bsunanda** [comment]
+geometry

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
