### PR TITLE
new MC pPb wf based on EposLHC_4080_4080GeV (80X)

### PR DESCRIPTION
**Pull request by fabozzi**
new pPb MC wf for HI
- gen fragment EposLHC_4080_4080GeV
- GT: auto:run2_mc_pa
- beamspot Run2PPbBoost
- customise RecoHI/Configuration/customise_PPwithHI.customisePPrecoforPPb
- AODSIM as output

backport of #16119

### CODE REVIEW

**Comment by fabozzi** [comment]
@mandrenguyen @mmusich 
this is the 80X backport
You are iterested to it because of #16110

**Comment by fabozzi** [comment]
backport of #16119

**Comment by fabozzi** [comment]
please test

**Comment by mmusich** [comment]
@fabozzi, thank you!

**Comment by fabozzi** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
