### PR TITLE
Hcal dump calibrations

### PR DESCRIPTION
**Pull request by kpedro88**
HcalCalibrationsSet and HcalCalibrationWidthsSet are derived calibration objects which can contain some non-trivial information: pedestals and pedestal widths converted from adc to fC (using QIE coder), and "respcorrgain" (production of RespCorrs and Gains). This PR adds the ability to dump the relevant non-trivial information from these derived objects to text files, using the existing HCAL database tools.

### CODE REVIEW

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by kpedro88** [comment]
Build error was apparently due to an unnecessary include in `CastorRawToDigi/plugins/CastorRawToDigi.cc` which caused a BuildFile inconsistency when combined with the changes in this PR.

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by mmusich** [comment]
+1

**Comment by kpedro88** [comment]
@ggovi @slava77 @cvuosalo please sign, has no effect on anything (only for HCAL development)

**Comment by cvuosalo** [comment]
+1

For #16499 10869fb05b53df72cac332201b33659fead9039b

Enhancing HCAL development tools. The change in Reco code is extremely tiny. There should be no change in monitored quantities.

The code changes are satisfactory, and Jenkins tests against baseline CMSSW_8_1_X_2016-11-07-1100 show no significant differences, as expected.

**Pull request merged**
