### PR TITLE
Fix one more CondCore unit test

### LINKED ISSUE #29983: CondCore unit tests failing for PY3 IBs due to use of boost_python
@ggovi , many CodeCore unit tests are failing in PY3 IBs with error like [a]. Problem is that in PY3 IBs , the default python is python3 which these unit tests are linked to boost_python which was build against python2. In past we have avoided such issues by replacing boost_python with pybind11.  Can you please look in to these tests and use PyBind11 instead of boost_python?

[a]
```
===== Test "testAlCaRecoTriggerBitsPayloadInspector" ====
Could not find platform independent libraries &lt;prefix&gt;
Could not find platform dependent libraries &lt;exec_prefix&gt;
Consider setting $PYTHONHOME to &lt;prefix&gt;[:&lt;exec_prefix&gt;]
ImportError: No module named site

---&gt; test testAlCaRecoTriggerBitsPayloadInspector had ERRORS
 
^^^^ End Test testAlCaRecoTriggerBitsPayloadInspector ^^^^
```

### PR DESCRIPTION
**Pull request by mmusich**
Resolves https://github.com/cms-sw/cmssw/issues/29983

#### PR description:

Addresses issue raised at https://github.com/cms-sw/cmssw/issues/29983#issuecomment-635192667.
I profit of this PR (in commit 8612e67) also to fix the test `CondCore/Utilities/test/testPngHistograms.cpp` which was actually not doing anything useful. 

#### PR validation:

Relies on the existing unit tests, both in `CMSSW_11_2_X_2020-05-27-2300` and `CMSSW_11_2_PY3_X_2020-05-27-2300`

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Not a backport, and no backport are needed.

### CODE REVIEW

**Comment by mmusich** [comment]
type bug-fix

**Comment by mmusich** [comment]
@cmsbuild, please test for CMSSW_11_2_PY3_X

**Comment by silviodonato** [comment]
Do you have any comments? @ggovi

**Comment by ggovi** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
