### PR TITLE
HLT menu development for `12_3_X`

### PR DESCRIPTION
**Pull request by missirol**
#### PR description:

Development of HLT menus for `CMSSW_12_3_X`. Includes the integration of the following JIRA tickets:

  - [CMSHLT-2184](https://its.cern.ch/jira/browse/CMSHLT-2184): [BTV] addition of paths with DeepJet b-tagger
  - [CMSHLT-2218](https://its.cern.ch/jira/browse/CMSHLT-2218): [BTV] fix to `MC_CaloBTagDeepCSV` path

A customisation function is added to make these latest menus, built in `12_3_0_pre4`, work in the latest IBs. This customisation is needed after the integration of https://github.com/cms-sw/cmssw/pull/36639, which updated, wrt `12_3_0_pre4`, the `cfi` template of a producer now used in the latest `GRun` menu.

#### PR validation:

TSG tests.

#### If this PR is a backport, please specify the original PR and why you need to backport that PR:

N/A

### CODE REVIEW

**Comment by missirol** [comment]
> A customisation function is added to make these latest menus, built in `12_3_0_pre4`, work in the latest IBs. This customisation is needed after the integration of https://github.com/cms-sw/cmssw/pull/36639, which updated, wrt `12_3_0_pre4`, the `cfi` template of a producer now used in the latest `GRun` menu.

@ahinzmann , could you please confirm that

`(PFCandidatePrimaryVertexSorter).assignment.NumOfPUVtxsForCharged = cms.int32(-1)` in `12_3_0_pre4`

is equivalent to

`(PFCandidatePrimaryVertexSorter).assignment.NumOfPUVtxsForCharged = cms.uint32(0)` after https://github.com/cms-sw/cmssw/pull/36639?

Thanks!

**Comment by missirol** [comment]
please test

**Comment by missirol** [comment]
+hlt

 - HLT-development PR needed to introduce a customisation function which makes the latest HLT menus in `ConfDB` functional not only for `12_3_0_pre4`, but also for the `12_3_X` branch (`master`)
 - changes in outputs of Run-3 wfs are in line with expectations for these HLT updates
 - [#36807 (comment)](https://github.com/cms-sw/cmssw/pull/36807#issuecomment-1022168096) is taken as a 'yes', based on my understanding of the changes in [#36639](https://github.com/cms-sw/cmssw/pull/36639)

**Comment by qliphy** [comment]
+1

**Pull request merged**
