### PR TITLE
Update two variables of electron MVA to match the training definition (76X)

### PR DESCRIPTION
**Pull request by lgray**
Update BDT evaluation code to match the training definitions exactly.

Affects VID / MiniAOD.

### CODE REVIEW

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
``` edm::service::InitRootHandlers::stacktraceFromThread() ``` in a few workflows that I looked at .
I guess the CMSSW_7_6_X_2015-09-15-1100  is broken

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/11260	983f5ad
- code changes look OK
- jenkins jobs failed due to issues in IB
- signed off based on observations in 75X for #11261

**Comment by smuzaffar** [comment]
#11270 should fix this
I am going to merge #11270  and start an IB as soon as 23h00 IB is done

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by davidlange6** [comment]
+1

**Pull request merged**
