### PR TITLE
Make Timing Service work with SubProcess

### PR DESCRIPTION
**Pull request by wddgit**

### CODE REVIEW

**Comment by wddgit** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by Dr15Jones** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Comment by smuzaffar** [comment]
@wddgit , @fabiocos , looks like this PR has caused the massive "Timeout" errors in recent IBs.
If I revert this locally then I can run wf 4.28. I have made a "Revert" PR for this to tests few of failing tests. If that PR tests works fine then either we revert it or Wait for @wddgit  to provide a fix

**Comment by fabiocos** [comment]
@smuzaffar @wddgit @Dr15Jones  when trying standalone runs of several workflows yesterdays I did manage to complete them without apparent anomalies. Shazhad, did you manage to reproduce the issue?

**Comment by smuzaffar** [comment]
were you running in multi threaded mode?

**Pull request merged**
