### PR TITLE
Cmssw 9 1 x

### PR DESCRIPTION
**Pull request by antoniovagnerini**

### CODE REVIEW

**Comment by antoniovagnerini** [comment]
1)Adding 2017 HLT menu paths for MSSMHbb & MSSMHbbmu in hltHiggsValidator_cfi.py 
2)Adding MSSMHbbmu in hltHIggsPostProcessor_cff.py
3)Adding RelVal_TTBar samples  in hltHIggsValidator_cfg.py

**Comment by mtosi** [comment]
@antoniovagnerini please do your PR in 92x
then, can you confirm me this code is meant for the validation of the new paths
in the standard release validation based mainly on MC samples ?

what about the code in the DQM, which is meant to be used on data ?
thanks !

**Comment by antoniovagnerini** [comment]
Hi Mia, 

unfortunately, the 92x branch is closed for updates. Could you redirect the changes of this PR from the 91X branch to the master branch? 

Yes, I developed this new code for the validation of the new HLT paths necessary for the MSSMHbb and MSSMHbbmu analyses and their integration in the standard release. 

I based this test on MC TTBar_rel_val samples. I have emailed Arun to ask him about the Higgs architecture of the DQM code and I am waiting for a reply. 

Alternatively, could you elaborate on the steps necessary for the DQM update? 

Cheers, 

Antonio

**Comment by mtosi** [comment]
ciao
use master (it maps 92x, now)

for the rest, I'm going to send a private email, the answer and comments take long

**Pull request closed without merging**
