### PR TITLE
Checksum parameter cfi export (74X)

### PR DESCRIPTION
**Pull request by smorovic**
CRC32 is checked by default, however parameter to control this is not exported.

We need a way to switch this off in heavy ion test setup, so two changes are provided:
- export of the parameter (for the new template)
- reuse adler32 setting as default (as we replaced adler32 with crc32, for existing templates).

Also, two other not previously exported parameters were added to cfi files, and input source parameter defaults were changed to defaults used in production.

Backport of #11535 and #11536

### CODE REVIEW

**Comment by smorovic** [comment]
please test

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by mommsen** [comment]
+1

**Comment by cvuosalo** [comment]
+1

For #11537 648e28577e8b45ca15d5008a077755e983767037

For Heavy Ions, exporting checksum parameter so it can be toggled as necessary. There should be no change in monitored quantities. #11535 and #11536 are the 76X  and 75X versions of this PR, and they have already been approved by Reco.

The code changes are satisfactory, and Jenkins tests against baseline CMSSW_7_4_X_2015-09-28-1100 show no significant differences, as expected.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
