### PR TITLE
Update of the LumiPCC module veto list and afterglow factors for 2024 [CMSSW_14_0_X]

### PR DESCRIPTION
**Pull request by radla118**
#### PR description:

Update of the LumiPCC module veto list and afterglow parameters implemented in the corresponding configuration files. Backport of PR #44568 

#### PR validation:

Validated by running runTheMatrix.py -l 1020.0 configuration.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

The modified parameters are intended to be used for the 2024 data-taking period (CMSSW_14_0_2).

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
backport of https://github.com/cms-sw/cmssw/pull/44568

**Comment by perrotta** [comment]
+alca
- (Copying here the same comments written while approving the master version of this PR)
- Same procedure to determine the misbehaving modules with past year data as was done for similar previous PRs
- The migration towards the storage of these parameters in the db rather than in python config is still ongoing...

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
