### PR TITLE
Add `SiStripApproximateClusterCollection` as a simple format for RAW (re-vamped)

### PR DESCRIPTION
**Pull request by mmusich**
Originally in https://github.com/cms-sw/cmssw/pull/42022 from @jeongeun.

#### PR description:

Based on the issue "Dataformat compatibility issue for HI SiStrip cluster in RAW" (https://github.com/cms-sw/cmssw/issues/39106)

Aim : changing Data-format (`edmNew::DetSetVector`) in RAW to be simple-enough for infinite backwards compatibility. -> It has to be readable by all future CMSSW releases.
Re-defining the corresponding final data-types directly in the ApproximatedClusters.
Need to be straightforward to convert from `edmNew::DetSetVector`.

The simplified data format has updated (recommended by Matti in 2022 Sep)
(https://github.com/cms-sw/cmssw/compare/master...makortel:cmssw:siStripApproximateClusterCollection_v2)

Target : 13_2_X release for the 2023 HeavyIon data-taking.
#### PR validation:

Tested in `CMSSW_13_3_X_2023-08-02-1100`, the basic test passed in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html):
   *  passes `runTheMatrix.py -l 140.58 -t 4 -j 8 --ibeos`

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Not a backport, but needs to be backported to CMSSW_13_2_X.

### CODE REVIEW

**Comment by mmusich** [comment]
test parameters:
   * workflow = 140.58

**Comment by mmusich** [comment]
As expected, [140.6, step2](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-186115/34140/runTheMatrixINPUT-results/140.6_RunHI2022/step2_RunHI2022.log) fails because the RAW' dataformat in its 2022 layout is different from the one proposed in this PR. I am wondering what are the plans for that (i.e. discard RAW' data from 2022 entirely, or try to support it)

**Comment by mandrenguyen** [comment]
@mmusich As far as I'm concerned the 2022 test data was only for testing.  We have all of that data in the regular RAW format.  So IMO we do not need to support it.

**Comment by mmusich** [comment]
@mandrenguyen 

> As far as I'm concerned the 2022 test data was only for testing. We have all of that data in the regular RAW format. So IMO we do not need to support it.

shall I just remove `140.6` from the matrix?

**Comment by mandrenguyen** [comment]
> @mandrenguyen
> 
> > As far as I'm concerned the 2022 test data was only for testing. We have all of that data in the regular RAW format. So IMO we do not need to support it.
> 
> shall I just remove `140.6` from the matrix?

I propose we temporarily dis-activate it and replace with a 2023 input when available.

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mandrenguyen** [comment]
+1

**Comment by emanueleusai** [comment]
+1

**Comment by mmusich** [comment]
the last push was necessary to remove the conflict that developed in the meantime.

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
@makortel,

I was wondering, PR https://github.com/cms-sw/cmssw/pull/42475 assumes that in the RAW data for the 2023 HI run we'll have a `DetIdCollection` saved

https://github.com/cms-sw/cmssw/blob/ed6d0cc3c115c611d431bcc17dc2115d35647edc/DataFormats/DetId/interface/DetIdCollection.h#L7

is this kind of object simple enough to be forward-compatible? Or would that need the same kind of treatment as `edmNew::DetSetVector` here?

**Comment by makortel** [comment]
Thanks @mmusich for asking!

> I was wondering, PR #42475 assumes that in the RAW data for the 2023 HI run we'll have a `DetIdCollection` saved
> 
> https://github.com/cms-sw/cmssw/blob/ed6d0cc3c115c611d431bcc17dc2115d35647edc/DataFormats/DetId/interface/DetIdCollection.h#L7
> 
> is this kind of object simple enough to be forward-compatible? Or would that need the same kind of treatment as `edmNew::DetSetVector` here?

On a quick look, `DetId` looks ok for backwards-compatibility guarantee. The `EDCollection`, on the other hand, looks like something that could be easily replaced with just `std::vector`. Therefore it may potentially be removed in the future, and I'm hesitant to extend the backwards-compatibility guarantee for that. An `std::vector<DetId>` would be fine (we just need to document its inclusion to "RAW umbrella" and add the necessary reading ability tests).

**Comment by mmusich** [comment]
@cms-sw/reconstruction-l2 @cms-sw/pdmv-l2 @cms-sw/upgrade-l2 @cms-sw/dqm-l2 would you please have a look here?

**Comment by mandrenguyen** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

From the upgrade side, only removing workflow and step.

**Comment by emanueleusai** [comment]
+1

**Comment by sunilUIET** [comment]
+pdmv

**Comment by rappoccio** [comment]
+1

**Comment by mandrenguyen** [comment]
> @mandrenguyen
> 
> > As far as I'm concerned the 2022 test data was only for testing. We have all of that data in the regular RAW format. So IMO we do not need to support it.
> 
> shall I just remove `140.6` from the matrix?

@mmusich Coming back to this issue, I've managed to confuse myself about this incompatibility.
Indeed, as I said, I don't think we'll care about reading rawprime from 2022 in new releases.
However 140.6 is actually reading RAW and running `REPACK:DigiToApproxClusterRaw` to turn it into RAW'.
Since RAW is unchanged, shouldn't we still be able to do this in 13_2_X?
I think we need some kind of offline workflow that will mimic what the HLT will be doing in order to make sure we're ready for the new data. 
We do seem to have that in place for MC (160.02), but not for real data.

**Comment by mandrenguyen** [comment]
I just realized that wf 140.6 did `REPACK:DigiToApproxClusterRaw` in CMSSW_12_5_X, but not in newer releases.
In any case, we have a 140.58 which runs `REPACK:DigiToApproxClusterRaw` on 2018 PbPb data. 
What should have a Run 3 wf that does the same. 
However, if I try to run the Run 3 equivalent of 140.58:
`cmsDriver.py repack --scenario pp --conditions auto:run3_data_prompt -s REPACK:DigiToApproxClusterRaw --datatier GEN-SIM-DIGI-RAW-HLTDEBUG --eventcontent REPACKRAW --era Run3_pp_on_PbPb_approxSiStripClusters -n 10 --procModifiers approxSiStripClusters --repacked --process REHLT --filein /store/hidata/HIRun2022A/HITestRaw6/RAW/v1/000/362/321/00000/76c3e7a8-896e-4671-9563-d6c596da5252.root --customise_commands "process.rawPrimeDataRepacker.src='rawDataRepacker'"`

I'm getting the following errors:
`
%MSG-w SiStripRawToDigi:  SiStripRawToDigiModule:siStripDigisHLT  18-Aug-2023 01:55:35 CEST Run: 362321 Event: 79195409
NULL pointer to FEDRawData for FED: id 135
Note: further warnings of this type will be suppressed (this can be changed by enabling debugging printout)
%MSG
----- Begin Fatal Exception 18-Aug-2023 01:55:35 CEST-----------------------
An exception of category 'NoRecord' occurred while
   [0] Processing  Event run: 362321 lumi: 165 event: 79195409 stream: 0
   [1] Running path 'REPACKRAWoutput_step'
   [2] Prefetching for module PoolOutputModule/'REPACKRAWoutput'
   [3] Prefetching for module SiStripClusters2ApproxClusters/'hltSiStripClusters2ApproxClusters'
   [4] Calling method for module BeamSpotOnlineProducer/'hltBeamSpotProducer'
Exception Message:
No "BeamSpotTransientObjectsRcd" record found in the EventSetup.

 Please add an ESSource or ESProducer that delivers such a record.
`
Any idea how to fix this?

**Comment by mmusich** [comment]
@mandrenguyen 

>  Any idea how to fix this?

yes. The following patch

```diff
diff --git a/Configuration/StandardSequences/python/DigiToRaw_Repack_cff.py b/Configuration/StandardSequences/python/DigiToRaw_Repack_cff.py
index a712ecaf6fc..6adc8c873da 100644
--- a/Configuration/StandardSequences/python/DigiToRaw_Repack_cff.py
+++ b/Configuration/StandardSequences/python/DigiToRaw_Repack_cff.py
@@ -84,5 +84,10 @@ hltScalersRawToDigi =  cms.EDProducer( "ScalersRawToDigi",
    scalersInputTag = cms.InputTag( "rawDataRepacker" )
 )
 
+import RecoVertex.BeamSpotProducer.onlineBeamSpotESProducer_cfi as _mod
+BeamSpotESProducer = _mod.onlineBeamSpotESProducer.clone(
+    timeThreshold = 999999 # for express allow >48h old payloads for replays. DO NOT CHANGE
+)
+
 DigiToApproxClusterRawTask = cms.Task(hltSiStripRawToDigi,siStripZeroSuppressionHLT,hltScalersRawToDigi,hltBeamSpotProducer,siStripClustersHLT,hltSiStripClusters2ApproxClusters,rawPrimeDataRepacker)
 DigiToApproxClusterRaw = cms.Sequence(DigiToApproxClusterRawTask)
```

allows:

```
cmsDriver.py repack --scenario pp --conditions auto:run3_data_prompt -s REPACK:DigiToApproxClusterRaw --datatier GEN-SIM-DIGI-RAW-HLTDEBUG --eventcontent REPACKRAW --era Run3_pp_on_PbPb_approxSiStripClusters -n 10 --procModifiers approxSiStripClusters --repacked --process REHLT --filein /store/hidata/HIRun2022A/HITestRaw6/RAW/v1/000/362/321/00000/76c3e7a8-896e-4671-9563-d6c596da5252.root --customise_commands "process.rawPrimeDataRepacker.src='rawDataRepacker'"
```

to run to completion.

**Comment by mmusich** [comment]
> What should have a Run 3 wf that does the same.

hopefully https://github.com/cms-sw/cmssw/pull/42600 should address this.

**Comment by fwyzard** [comment]
> The `EDCollection`, on the other hand, looks like something that could be easily replaced with just `std::vector`. Therefore it may potentially be removed in the future, and I'm hesitant to extend the backwards-compatibility guarantee for that. An `std::vector<DetId>` would be fine (we just need to document its inclusion to "RAW umbrella" and add the necessary reading ability tests).

Why does the `EDCollection` template even exist ?
Issues with ROOT supporting `std::vector` as a top level data format (17 years ago) ?

**Comment by mmusich** [comment]
> Why does the EDCollection template even exist ?

I am not sure, but (also discussing with @missirol) I think we could just get rid of it entirely and drop-in replace it instead an `std::vector<DetId>` in the Strip unpacker and use that in all clients instead of creating conversions back and forth to persist the data in the RAW' samples.

**Comment by missirol** [comment]
> drop-in replace it instead an `std::vector<DetId>` in the Strip unpacker and use that in all clients

This is attempted in #42662 (thanks to pointers I got from @mmusich).

**Pull request merged**
