### PR TITLE
Fixing missing seeds affecting Electron EcalDriven Efficiency : 92X

### PR DESCRIPTION
**Pull request by Sam-Harper**
Backport of https://github.com/cms-sw/cmssw/pull/20106

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by slava77** [comment]
@Sam-Harper 
This change affects both data and MC, and in a rather significant way, right?
MCv1 [CMSSW_9_2_8] is meant to have the same reco as the 92X prompt.
So, by no-change policy this can not go to 92X.

**Comment by Sam-Harper** [comment]
so the re-reco will be done with 93X? Sorry for not knowing this, its been a bit manic.

**Comment by slava77** [comment]
On 8/14/17 5:49 AM, Sam-Harper wrote:
> so the re-reco will be done with 93X? Sorry for not knowing this, its
> been a bit manic.

there is a rereco with 92X (9_2_8 or it's equivalent)
there will be a rereco with 93X later named release with features
collected by Sept 15.

**Comment by perrotta** [comment]
-1
- The changes are identical to the ones signed off by reco right now in 93X (#20106)
- However, since also MC would be affected by them, no backport is allowed in principle in 92X
- Assign a "-1" to remove this PR from our list: it can be reconsidered in case PPD or PC decide that changes that affect MC productions can still be allowed in 92X

**Comment by Sam-Harper** [comment]
Thanks @perrotta , I was considering closing this today as well. I will follow up with PPD about what to do for data and see how serious this issue vs the timeline for 93X is.

**Pull request closed without merging**
