### PR TITLE
Adding a vertex smearing configution for pp at 5 TeV, based on latest info from the LHC

### PR DESCRIPTION
**Pull request by mandrenguyen**
Expected beam conditions for the pp run at 5 TeV that will take place in about 4 weeks.
The GEN-SIM production will be in the same release used for 13 TeV, so I will also add this into 71X.
I can also add this in CMSSW8, if we're no longer forward porting from 76X.
As usual, we will iterate with ppd/pdmv to get the matching reco BS in the GT.

### CODE REVIEW

**Comment by civanch** [comment]
@mandrenguyen , is "Expected" an optimal name? before "Nominal" was used for 13 TeV.

**Comment by mandrenguyen** [comment]
@civanch Makes sense. Will update in a bit.

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1
@mandrenguyen , likely similar PRs for 7_1 and 8_0 are needed

**Comment by davidlange6** [comment]
@mandrenguyen - do we really need to keep around the last "new" HI beamspot? (ie, can we just change it as its now seemingly obsolete)

**Comment by mandrenguyen** [comment]
@davidlange6 
We had intended to update the HI beamspot to something more realistic after it become clear the centroid wasn't really going to be at the origin, but in the end decided not to restart the GEN-SIM for that, as the real data may turn out to be different from both.  If it's not hurting anyone, I would leave it around (it's not active in relval) for systematic studies.  If nothing else, I can always overwrite this with the real beam parameters after we actually see the data.  If it really bothers you, I can zap it, preferably as a separate PR.

**Comment by civanch** [comment]
please test
@mandrenguyen , do we still  need this PR?

**Comment by mandrenguyen** [comment]
@civanch GEN-SIM will be in 71X.  Not sure we'll ever run this in 76X, but I put it in just in case.

**Pull request merged**
