### PR TITLE
TICLv5 : Superclustering DNN

### PR DESCRIPTION
**Pull request by tcuisset**
#### PR description:
This PR brings a new electron superclustering setup for TICLv5. Superclusters can be built either using a DNN or the Mustache algorithm. 

Changes : 

- PCA cleaning algorithm [(slides)](https://indico.cern.ch/event/1097262/contributions/4620513/attachments/2348364/4005041/TICLmeeting_18112021.pdf)
- Superclustering DNN (TracksterLinkingBySuperClusteringDNN), with EDAnalyzer for producing training samples (SuperclusteringSampleDumper)
- Superclustering with Mustache inside TICL (TracksterLinkingbySuperClusteringMustache)
- Producer to convert superclusters as tracksters to Egamma dataformats and feeding it to electron chain, with energy regression (EGammaSuperclusterProducer)
- refactored TICLDumper to make it better configurable

Adds three process modifiers to choose between old PF-based Mustache superclustering, new TICL-based Mustache, and DNN-based superclustering.

No significant changes are expected to workflows that do not enable ticl_v5 modifier (off by default), though some very small changes are due to a change from double to float in trackster PCA calculation . For ticl_v5 workflows changes in electron reconstruction are expected.

Presentation : [TICL meeting](https://indico.cern.ch/event/1414107/#1-superclustering-in-ticlv5)

This PR depends on cms-data : cms-data/RecoHGCal-TICL#5

#### PR validation:
Tested using runTheMatrix workflows : 

 - 29691.203 SingleElectronPt15Eta1p7_2p7_2026D110 + ticl_v5
 - 29691.204 SingleElectronPt15Eta1p7_2p7_2026D110 + ticl_v5_mustache
 - 29691.205 SingleElectronPt15Eta1p7_2p7_2026D110 + ticl_v5_mustache_pf
 - 29646.204 ZEE_14TeV_TuneCP5_2026D110 + ticl_v5_mustache
 - 29646.205 ZEE_14TeV_TuneCP5_2026D110 + ticl_v5_mustache_pf

and also 29846.204,29846.205,29891.203,29891.204,29891.205

### CODE REVIEW

**Comment by felicepantaleo** [comment]
test parameters:  

- workflow_opts= -w upgrade
- workflow = 29888.203,29688.203

**Comment by felicepantaleo** [comment]
@cmsbuild please test

**Comment by rovere** [comment]
@cmsbuild please test with cms-data/RecoHGCal-TICL#5

**Comment by felicepantaleo** [comment]
test parameters:  

- workflow_opts= -w upgrade
- workflow = 29888.203,29688.203
- pull_request = https://github.com/cms-data/RecoHGCal-TICL/pull/5

**Comment by felicepantaleo** [comment]
@cmsbuild please test

**Comment by felicepantaleo** [comment]
test parameters:  

- workflow_opts= -w upgrade
- workflow = 29888.203,29688.203,29846.204,29846.205,29891.203,29891.204,29891.205,29691.203,29691.204,29691.205,29646.204,29646.205
- pull_request = https://github.com/cms-data/RecoHGCal-TICL/pull/5

**Comment by felicepantaleo** [comment]
@cmsbuild please test

**Comment by mandrenguyen** [comment]
enable profiling
We think it should be working again after https://github.com/cms-sw/cms-bot/pull/2280
Just using this PR to test the profiling

**Comment by mandrenguyen** [comment]
please test
just re-running to test profiling

**Comment by mandrenguyen** [comment]
enable none
it seems we still need to fix some things in cms-bot for Phase-2 profiling

**Comment by jfernan2** [comment]
enable profiling
We think it should be working again after https://github.com/cms-sw/cms-bot/pull/2282

**Comment by jfernan2** [comment]
please test
just re-running to test profiling since the last test is at least 2 week old now

**Comment by jfernan2** [comment]
please test workflow 12634.21,29834.21

**Comment by jfernan2** [comment]
please test  workflow 12634.21,29834.21
Last trial trying to get profiling results

**Comment by felicepantaleo** [comment]
Can this PR be merged, and another PR be used to test profiling? there are two more PRs to be opened on top of this development that should be merged before 14_1_0 is closed.

@tcuisset can you post the results of the timing studies of this pr, so that they can merge it?

**Comment by mandrenguyen** [comment]
> Can this PR be merged, and another PR be used to test profiling? there are two more PRs to be opened on top of this development that should be merged before 14_1_0 is closed.
> 
> @tcuisset can you post the results of the timing studies of this pr, so that they can merge it?

Can you please summarize the upcoming PRs?

**Comment by waredjeb** [comment]
> > Can this PR be merged, and another PR be used to test profiling? there are two more PRs to be opened on top of this development that should be merged before 14_1_0 is closed.
> > @tcuisset can you post the results of the timing studies of this pr, so that they can merge it?
> 
> Can you please summarize the upcoming PRs?

Hi @mandrenguyen 

The first PR will integrate an improvement in the Linking algorithm for TICLv5 (TracksterLinkingbySkeletons). It is expected to slightly change the way we build the TICLGraph and open the searching window, together with new algorithm parameters. I will open it this morning.
- The second PR will introduce a plugin system for the energy regression and PID in TICL, together with replacing the TF model for the energy regression and PID with two ONNX  models, one for energy regression and one for PID. Should come in the following few days and it would be extremely important for TICLv5 since we will deploy the new trained models with the new TICL reconstruction

**Comment by tcuisset** [comment]
Timing studies for the PR (using 100 SingleElectron events, PU=200), showing the the main producers in the electron chain (using TimingModule). (NB: the DNN is only enabled with TICLv5, which is currently off by default. So there would only be change for the *.203/204/205 workflows)

| Producer  | DNN (s) | TICL-mustache (s) | PF Mustache (baseline) (s) |
| ------------- | ------------- | ------------- | ------------- |
| ticlTracksterLinksSuperclustering | 0.16 | 0.0077| -|
| ecalDrivenElectronSeeds | 0.66 | 0.80| 0.11|
| electronCkfTrackCandidates | 0.57 |0.60| 0.05|
| electronGsfTracks | 0.37 |0.36| 0.05|
| Full event (tracker reco+TICL+Gsf electrons)| 29.1924| 29.3598 | 29.215|

The time taken by the electron chain increases with the DNN, but stays negligible compared to overall event reco time. This is expected to be reduced by the new PID (that would reduce the seeding of GsfTracks from pileup / hadronic tracksters)

**Comment by jfernan2** [comment]
Thanks for the info @tcuisset

**Comment by jfernan2** [comment]
+1

**Comment by waredjeb** [comment]
kind ping

I know it is vacation period, but it would be really nice if we could integrate this in pre7

**Comment by civanch** [comment]
+1

**Comment by srimanob** [comment]
@cmsbuild please test

**Comment by AdrianoDee** [comment]
+pdmv

**Comment by srimanob** [comment]
Hi @tcuisset @waredjeb 
Could you please clarify the PR test result, and what you mentioned in the PR description,
"No changes are expected to workflows that do not enable ticl_v5 modifier (off by default). For ticl_v5 workflows changes in electron reconstruction are expected."

I see changes around all Phase-2 default workflow which I think does not enable ticl_v5 modifier. Do I miss a discussion in this PR? Thx.

**Comment by tcuisset** [comment]
> Hi @tcuisset @waredjeb Could you please clarify the PR test result, and what you mentioned in the PR description, "No changes are expected to workflows that do not enable ticl_v5 modifier (off by default). For ticl_v5 workflows changes in electron reconstruction are expected."
> 
> I see changes around all Phase-2 default workflow (e.g. [here](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_14_1_X_2024-08-04-0000+d1a85e/63871/validateJR.html)) which I think does not enable ticl_v5 modifier. Do I miss a discussion in this PR? Thx.

Hi @srimanob ,
The changes seen in Phase-2 non-TICLv5 workflows are due to the change from double to float in the [trackster PCA computation](https://github.com/cms-sw/cmssw/pull/45333/files#diff-c2b0a484f5de9311737b9441259b0e5f49ddb15fe040d8e90e8e03d49fc6b170). This leads to very small changes in trackster eta/phi that then propagates further down the chain.
The differences in these workflows are very small (mostly migration between adjacent bins).

**Comment by srimanob** [comment]
Hi @tcuisset 
Thanks for clarification. Could you please update the PR description, to avoid confusion.

**Comment by srimanob** [comment]
+Upgrade

Change seen in Phase-2 workflows is explaned by the double to float calculation mentioned in https://github.com/cms-sw/cmssw/pull/45333#issuecomment-2268908384

**Comment by tjavaid** [comment]
+1

- spurious differences seen from unstable WF `12834.7` (open issue #39803 )

**Comment by antoniovilela** [comment]
+operations

**Comment by antoniovilela** [comment]
https://github.com/cms-data/RecoHGCal-TICL/pull/5 merged.
cmsdist tag PR: https://github.com/cms-sw/cmsdist/pull/9370

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
