### PR TITLE
HCALDQM: Fix digi size reference for summary plots (10_0_X)

### PR DESCRIPTION
**Pull request by DryRun**
Fixes the digi size reference (HB, HE from 10 to 8) for the summary plots. Also moves the location of the reference from C++ (HcalCommon/interface/Constants.h) to python (DigiTask.py, and copied via import to HcalOnlineHarvesting.py and HcalOfflineHarvesting.py).

10_0_X backport of https://github.com/cms-sw/cmssw/pull/22595.

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by mariadalfonso** [comment]
@DryRun 
I think you still need to cherry pick the commit c02a24b

**Comment by DryRun** [comment]
@mariadalfonso Thanks for spotting that, I forgot to push the commit! Done now.

**Comment by dmitrijus** [comment]
type backport

**Comment by dmitrijus** [comment]
+1

**Comment by dmitrijus** [comment]
type backport

**Comment by deguio** [comment]
@DryRun 
can this one be closed?

**Pull request closed without merging**
