### PR TITLE
bsunanda:Phase2-gem20 Update the current proposal for GE21 as a Dev version

### PR DESCRIPTION
**Pull request by bsunanda**
This is a version as suggested by the engineering group and may become default later

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by ianna** [comment]
@bsunanda - what's the timescale for final version of this description? Perhaps, queueing it for CMSSW 9.0.x would give you more time to fix it?

screen shot 2016-11-09 at 17 16 15

**Comment by bsunanda** [comment]
@ianna Is there a overlap. I dont think so. If it is the description of hybrid or cooling tube, newer measurements wont be available for a while. It is more important to see the effect of the gap between the eta partitions which need to be studied now. So if there is no overlap please approve this

**Comment by ianna** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
