### PR TITLE
Geant4 physics lists without Geant4 particle iterator 

### PR DESCRIPTION
**Pull request by civanch**
Newer versions of Geant4 cannot compile with the current CMSSW due to interface to Geant4 particle. This change removes such limitation. This PR is a clone of #18109.

This is also a first step to make custom physics be MT capable (not the case so far). In other word, make exotics simulation multi-threaded.

For CMS alternative EM physics constructors initialisation is changed according Geant4 recommendations.

It should not affect any result of current simulation even simulation history.

### CODE REVIEW

**Comment by civanch** [comment]
@davidlange6 , is it OK for the particle list now?

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
please test

**Comment by davidlange6** [comment]
please test

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
@smuzaffar , can you, please, advice what may happens with this PR? Locally this PR is OK with many runMatrix tests but in official test fails with 5.1, in 5.1 WF where this code is not used at all. First is failed at exit of the step2, the last test is killed by timeout.

**Comment by smuzaffar** [comment]
please test
no idea, there is a message at the end "Fatal system signal has occurred during exit" . I have restarted the tests to see if error is reproduceable in jenkins

**Comment by civanch** [comment]
This is closed and #18268 is done from scratch

**Pull request closed without merging**
