### PR TITLE
New proton transport clean (following up PR 25355)

### PR DESCRIPTION
**Pull request by mundim**
New attempt for the this PR (following up 25355) with a cleaner history. The data dir inside SimTransport/HectorProducer will still appear in the history, since when addding the package, it was already in git.

### CODE REVIEW

**Comment by civanch** [comment]
+1

**Comment by civanch** [comment]
This is PPS SIM PR in the clean area, long discussion was in 2018 for previous PRs. @efeyazgan , please, sign it once more.

**Comment by efeyazgan** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
