### PR TITLE
Modularized FWCore, DataFormats

### PR DESCRIPTION
**Pull request by Teemperor**
First step to modularize FWCore (and the DataFormats libraries used by FWCore). This patch adds all missing includes and removes cyclic includes that cause FWCore to fail compiling with per-header modules.

### CODE REVIEW

**Comment by Teemperor** [comment]
This PR is work-in-progress. See [this issue](https://github.com/cms-sw/cmssw/issues/15248) for the tracking issue about modularizing CMSSW.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@Teemperor what's the aspect of "work in progress"?
If you plan to add edits to more packages and other files, cms-sw/cmssw is not the best repo for this: make a PR to your own area and mention it in #15248 .

If, OTOH, this is "essentially done", then this PR can stay.

**Comment by slava77** [comment]
-1 

looks incomplete
OK as a work in progress, but clearly not ready to merge

**Comment by davidlange6** [comment]
fyi - more info here https://indico.cern.ch/event/623308/
but indeed, the entire CMSSW needs to compile with any proposed changes before its useful to make a pull request.

**Comment by Teemperor** [comment]
As suggested, I'll split this up in multiply smaller PRs. Closing this.

**Pull request closed without merging**
