### PR TITLE
  Fix statics in DQM/BeamMonitor

### PR DESCRIPTION
**Pull request by dmitrijus**
Fix statics in DQM/BeamMonitor.
Make them members in Vx3DHLTAnalyzer.

(forwardport of https://github.com/cms-sw/cmssw/pull/11988)

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1

**Comment by deguio** [comment]
please test

**Comment by davidlange6** [comment]
I am cleaning up the 76x queue aside from things for analysis workflows. I'm closing this pull request, please make sure the PR is in 80x. Thanks!

**Pull request closed without merging**
