### PR TITLE
Hit counters for Run-3 shower CSC trigger (HadronicShowerTrigger-2)

### PR DESCRIPTION
**Pull request by dildick**
#### PR description:

This PR adds the code to count cathode/anode hits and packs the result in a `CSCShowerDigi` object. Follow-up of https://github.com/cms-sw/cmssw/pull/33389. The hit counters are not enabled yet.

#### PR validation:

Code compiles. The hit counters run parallel with the ordinary ALCT and CLCT finding.  Tested with WF 11634.0. There should be no differences. 

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A. We expect the (local trigger, track-finder, uGMT) firmware to be available by Summer 2021. I'll first develop the entire emulator in 11_3_X, then backport if need be.

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by dildick** [comment]
I tried rebasing to see if this would remove the clang error.

**Comment by dildick** [comment]
Strange, the `CSCShowerDigiCollection` is present in the 11_3_X branch though.

**Comment by dildick** [comment]
@cecilecaillol Could you start the tests, please?

**Comment by cecilecaillol** [comment]
please test

**Comment by dildick** [comment]
Strange, I did not see this in local tests. Maybe something wrong in the readout

**Comment by dildick** [comment]
@cecilecaillol This should fix the memory error. I'm running all matrix tests now to make sure it does.

**Comment by cecilecaillol** [comment]
please test

**Comment by cecilecaillol** [comment]
+l1

**Comment by dildick** [comment]
6 failures, 5 from the message logger, 1 from the pixel system.

Screen Shot 2021-04-15 at 6 39 14 AM

**Comment by dildick** [comment]
Are there any more comments on this PR?

**Comment by dildick** [comment]
@qliphy can this be signed off?

**Comment by qliphy** [comment]
+1

**Pull request merged**
