### PR TITLE
Initialize variables, and a few other trivial adjustments in RecoRomanPot/RecoFP420

### PR DESCRIPTION
**Pull request by perrotta**
#### PR description:

I understand that this code is not currently used in CMSSW. Anyhow, it was rather annoying to see Static Analyzer warnings coming from it: a few missing initializations were added in order to (hopefully) cope with them.

While doing so, I also profited to fix some rather obvious bad coding that I encountered: this cleaning is not supposed, nor meant, to be complete, as I just touched what jumped under my eyes.

Overall, no changes are expected if and when this code will be ever used.

#### PR validation:

It builds

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by jpata** [comment]
Thanks for this! I think we should investigate if this outdated code can be dropped, if there is no way to test it, and nobody really monitoring the outputs.

**Comment by jpata** [comment]
+reconstruction
- signing this as a minimal/technical change, but the code is not running or tested (https://github.com/cms-sw/cmssw/issues/36612)

**Comment by qliphy** [comment]
+1

**Pull request merged**
