### PR TITLE
Fix customisePixelLocalReconstruction() customize function

### LINKED ISSUE #35624: [GPU] 11634.X RelVal failures during processing of Python configuration
[Example log file](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc900/CMSSW_12_1_GPU_X_2021-10-11-2300/pyRelValMatrixLogs/run/11634.502_TTbar_14TeV+2021_Patatrack_PixelOnlyGPU+TTbar_14TeV_TuneCP5_GenSimINPUT+Digi+Reco+HARVEST/step2_TTbar_14TeV+2021_Patatrack_PixelOnlyGPU+TTbar_14TeV_TuneCP5_GenSimINPUT+Digi+Reco+HARVEST.log#/)

```
Starting python3 /pool/condor/dir_10183/jenkins/workspace/ib-run-relvals/cms-bot/monitor_workflow.py timeout --signal SIGTERM 9000  cmsRun -j JobReport2.xml  step2_DIGI_L1_DIGI2RAW_HLT.py
----- Begin Fatal Exception 12-Oct-2021 09:04:49 UTC-----------------------
An exception of category 'ConfigFileReadError' occurred while
   [0] Processing the python configuration file named step2_DIGI_L1_DIGI2RAW_HLT.py
Exception Message:
 unknown python problem occurred.
RuntimeError: Unable to cast Python instance of type <class 'NoneType'> to C++ type 'std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >'

At:
  /cvmfs/cms-ib.cern.ch/nweek-02702/slc7_amd64_gcc900/cms/cmssw/CMSSW_12_1_GPU_X_2021-10-11-2300/python/FWCore/ParameterSet/Config.py(1163): _insertPaths
  /cvmfs/cms-ib.cern.ch/nweek-02702/slc7_amd64_gcc900/cms/cmssw/CMSSW_12_1_GPU_X_2021-10-11-2300/python/FWCore/ParameterSet/Config.py(1323): fillProcessDesc
  <string>(2): <module>

----- End Fatal Exception -------------------------------------------------
```

Only occurs in GPU IBs

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

This PR adds explicit manipulation of `HLTSchedule` when the Paths whose customization was added in https://github.com/cms-sw/cmssw/pull/35566 are replaced in `ProcessFragment`. Fixes https://github.com/cms-sw/cmssw/issues/35624.

#### PR validation:

Tested on CPU-only machine that workflow 11634.502 works.

### CODE REVIEW

**Comment by makortel** [comment]
test parameters:
   - workflows_gpu = 11634.502,11634.506,11634.512,11634.522,11634.592,11634.596,11650.502,11650.506
   - enable_tests = gpu

**Comment by makortel** [comment]
Tests are stuck?

**Comment by makortel** [comment]
@cmsbuild, please abort

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by tvami** [comment]
@cmsbuild ping

**Comment by makortel** [comment]
Just to clarify (to myself) that with this PR all the tested GPU workflows succeeded
```
11634.502_TTbar_14TeV+2021_Patatrack_PixelOnlyGPU+TTbar_14TeV_TuneCP5_GenSim+Digi+Reco+HARVEST Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED  - time date Tue Oct 19 14:42:49 2021-date Tue Oct 19 14:33:30 2021; exit: 0 0 0 0
11634.506_TTbar_14TeV+2021_Patatrack_PixelOnlyTripletsGPU+TTbar_14TeV_TuneCP5_GenSim+Digi+Reco+HARVEST Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED  - time date Tue Oct 19 14:42:50 2021-date Tue Oct 19 14:33:31 2021; exit: 0 0 0 0
11634.512_TTbar_14TeV+2021_Patatrack_ECALOnlyGPU+TTbar_14TeV_TuneCP5_GenSim+Digi+Reco+HARVEST Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED  - time date Tue Oct 19 14:42:35 2021-date Tue Oct 19 14:33:31 2021; exit: 0 0 0 0
11634.522_TTbar_14TeV+2021_Patatrack_HCALOnlyGPU+TTbar_14TeV_TuneCP5_GenSim+Digi+Reco+HARVEST Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED  - time date Tue Oct 19 14:42:35 2021-date Tue Oct 19 14:33:32 2021; exit: 0 0 0 0
11634.592_TTbar_14TeV+2021_Patatrack_GPU+TTbar_14TeV_TuneCP5_GenSim+Digi+Reco+HARVEST Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED  - time date Tue Oct 19 14:54:40 2021-date Tue Oct 19 14:42:36 2021; exit: 0 0 0 0
11634.596_TTbar_14TeV+2021_Patatrack_TripletsGPU+TTbar_14TeV_TuneCP5_GenSim+Digi+Reco+HARVEST Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED  - time date Tue Oct 19 14:54:40 2021-date Tue Oct 19 14:42:36 2021; exit: 0 0 0 0
11650.502_ZMM_14+2021_Patatrack_PixelOnlyGPU+ZMM_14TeV_TuneCP5_GenSim+Digi+Reco+HARVEST Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED  - time date Tue Oct 19 14:50:24 2021-date Tue Oct 19 14:42:50 2021; exit: 0 0 0 0
11650.506_ZMM_14+2021_Patatrack_PixelOnlyTripletsGPU+ZMM_14TeV_TuneCP5_GenSim+Digi+Reco+HARVEST Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED  - time date Tue Oct 19 14:50:24 2021-date Tue Oct 19 14:42:50 2021; exit: 0 0 0 0
8 8 8 8 tests passed, 0 0 0 0 failed
```

**Comment by qliphy** [comment]
+1

**Pull request merged**
