### PR TITLE
Remove unused headers for RECO & SIM packages

### PR DESCRIPTION
**Pull request by yuanchao**
#### PR description:

Remove unused headers in RECO & SIM packages.

Following the issue #31505, the following headers are unused in several package:
 -  RecoEgamma/EgammaTools/interface/ConversionTools.h
 -  RecoEgamma/EgammaTools/interface/EffectiveAreas.h
 -  RecoHI/HiJetAlgos/interface/UECalibration.h
 -  RecoJets/JetAnalyzers/doc/myJetAna.html
 -  RecoJets/JetAnalyzers/interface/CaloTowerBoundries.h
 -  RecoJets/JetAnalyzers/interface/MyCluster.h
 -  RecoJets/JetAnalyzers/interface/myFilter.h
 -  RecoJets/JetAnalyzers/interface/myJetAna.h
 -  RecoJets/JetAnalyzers/test/myFilter.cc
 -  RecoJets/JetAnalyzers/test/myJetAna.cc
 -  RecoLocalCalo/EcalRecAlgos/interface/EcalUncalibRecHitLeadingEdgeAlgo.h
 -  RecoMuon/TrackingTools/interface/MuonSeedDetLayer.h
 -  RecoTracker/SpecialSeedGenerators/interface/EtaPhiMeasurementEstimator.h
 -  RecoTracker/TkMSParametrization/interface/rangesIntersect.h
 -  RecoTracker/TrackProducer/interface/GsfTrackProducerAlgorithm.h
 -  RecoTracker/TransientTrackingRecHit/interface/GSTransientTrackingRecHit.h
 -  RecoVertex/ConfigurableVertexReco/interface/ReconstructorFromLinPtFinder.h
 -  RecoVertex/KinematicFit/interface/CombinedKinematicConstraintT.h
 -  RecoVertex/LinearizationPointFinders/interface/MonteCarloLinearizationPointFinder.h
 -  RecoVertex/LinearizationPointFinders/src/MonteCarloLinearizationPointFinder.cc
 -  SimCalorimetry/CaloSimAlgos/interface/CaloVNoisifier.h
 -  SimDataFormats/RPCDigiSimLink/interface/RPCDigiSimLinkfwd.h
 -  SimDataFormats/TrackerDigiSimLink/interface/PixelDigiSimLinkfwd.h
 -  SimDataFormats/TrackerDigiSimLink/interface/StripCompactDigiSimLinksfwd.h
 -  SimDataFormats/TrackerDigiSimLink/interface/StripDigiSimLinkfwd.h
 -  SimG4CMS/Calo/interface/HcalTestHistoClass.h
 -  SimG4Core/Application/interface/DDDWorldObserver.h
 -  SimG4Core/Notification/interface/ComponentBuilder.h
 -  SimG4Core/Notification/interface/ComponentFactoryByName.h
 -  SimG4Core/Notification/interface/DispatchableG4Step.h
 -  SimG4Core/Notification/interface/OwnIt.h

#### PR validation:

Code compiles. Run local limited runTheMatrix.py tests.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Not a backport and no backport forseen.

### CODE REVIEW

**Comment by civanch** [comment]
+1

**Comment by slava77** [comment]
The following do not follow a pattern of unused header removal and also remove the code using the headers:

- RecoJets/JetAnalyzers/doc/myJetAna.html
- RecoJets/JetAnalyzers/interface/myFilter.h RecoJets/JetAnalyzers/test/myFilter.cc
- RecoJets/JetAnalyzers/interface/myJetAna.h RecoJets/JetAnalyzers/test/myJetAna.cc

@camclean @alefisico 
@cms-sw/hcal-dpg-l2 it seems like this may have been used by HCAL DPG not so long ago (unless I mis-attributed Frank's commit a068b01a3916aaf2142e071e2a75f6622c2bc8b3). Please check/confirm that this is not used anymore

**Comment by slava77** [comment]
RecoLocalCalo/EcalRecAlgos/interface/EcalUncalibRecHitLeadingEdgeAlgo.h
 was used in EcalUncalibRecHitWorkerGlobal until #8717 (2015)
@cms-sw/ecal-dpg-l2  please clarify if EcalUncalibRecHitLeadingEdgeAlgo is still needed and should be kept in the release.
Thank you.

**Comment by slava77** [comment]
RecoVertex/KinematicFit/interface/CombinedKinematicConstraintT.h was used/tested in RecoVertex/KinematicFit/test/test_CombinedConstraint.cpp which was apparently lost during CVS -> git import (I did not find any indications that it was removed intentionally).

So, perhaps it's practical to eventually recover the /test directory as of https://github.com/cms-sw/cmssw/tree/0a6192c876dbfe83249fbaba871c68ac029fcae2/RecoVertex/KinematicFit/test 

@VinInn (primary developer since fbcb3b803286e6c4d93c67f9e4ef7c3d89d8ad4c)
@emilbols @mmusich @vmariani 
please check and comment for BTV/TRK or perhaps other use cases as in BPH.
Thank you.

**Comment by slava77** [comment]
> > @cms-sw/hcal-dpg-l2 it seems like this may have been used by HCAL DPG not so long ago (unless I mis-attributed Frank's commit [a068b01](https://github.com/cms-sw/cmssw/commit/a068b01a3916aaf2142e071e2a75f6622c2bc8b3)). Please check/confirm that this is not used anymore
> 
> That was almost 10 years ago, I don't think it is used anymore!

OK, thanks for checking.

**Comment by slava77** [comment]
So, for reco the following remain candidates to keep
- RecoLocalCalo/EcalRecAlgos/interface/EcalUncalibRecHitLeadingEdgeAlgo.h
    - waiting for feedback in https://github.com/cms-sw/cmssw/pull/35167#issuecomment-917128412 
- RecoVertex/KinematicFit/interface/CombinedKinematicConstraintT.h
    - waiting for feedback in https://github.com/cms-sw/cmssw/pull/35167#issuecomment-917131947

**Comment by emilbols** [comment]
> RecoVertex/KinematicFit/interface/CombinedKinematicConstraintT.h was used/tested in RecoVertex/KinematicFit/test/test_CombinedConstraint.cpp which was apparently lost during CVS -> git import (I did not find any indications that it was removed intentionally).
> 
> So, perhaps it's practical to eventually recover the /test directory as of https://github.com/cms-sw/cmssw/tree/0a6192c876dbfe83249fbaba871c68ac029fcae2/RecoVertex/KinematicFit/test

I dont think this is being used by anyone active in btv. Perhaps in case some extensive study of the vertexing was restarted, this kind of tool could be useful, but i think for the most part this code is forgotten from a btv standpoint.

**Comment by thomreis** [comment]
From ECAL DPG point of view RecoLocalCalo/EcalRecAlgos/interface/EcalUncalibRecHitLeadingEdgeAlgo.h is not needed anymore and can be removed.

**Comment by slava77** [comment]
+reconstruction

for https://github.com/cms-sw/cmssw/pull/35167	276099b 
- code changes are in line with the PR description and the few questionable removals were confirmed to be OK
- jenkins tests pass

**Comment by perrotta** [comment]
+1

**Pull request merged**
