### PR TITLE
Set a maximum number of waiting messages

### PR DESCRIPTION
**Pull request by Dr15Jones**
If the MessageLogger buffer queue exceeds a set size, any following messages will be discarded.
The value can be controlled via the 'waiting_threshold' parameter.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by davidlange6** [comment]
Hi @Dr15Jones - this is 100 messages total or per thread?

**Comment by Dr15Jones** [comment]
100 total messages waiting to be processed for all threads. The hope was collisions were rare so the buffer is almost always empty. That doesn't seem to be true for those rare disastrous cases. 100 is just a guess at a number to keep reasonable jobs still printing all their output and stopping unreasonable jobs from overwhelming the system.

**Comment by davidlange6** [comment]
this should also work well with things like the memory service running threaded. could the message logger report at the end of job also include the number of dropped messages?

**Comment by Dr15Jones** [comment]
The summary now reports how many were dropped because of overtaxing.

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
