### PR TITLE
modify pixel probability cut in final fit to reject hit affected by Dyn-Innefficency

### PR DESCRIPTION
**Pull request by VinInn**
the title says all.
please refers to presentation at reco meeting on May 21st
and to the HN thread 
https://hypernews.cern.ch/HyperNews/CMS/get/pixelOfflineSW/1134/1/1.html

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
... this is on hold for now, based on the discussion in the RECO meeting today.
If we need an alternative set of samples made in relvals for tests, please make a customize function to enable a particular mode.

**Comment by slava77** [comment]
I just wanted to check /register in this thread that this change is still under investigation and is as such the PR is still on hold.
Please comment if it's incorrect.

**Comment by VinInn** [comment]
It is under investigation.
I will surely not be implemented as is (the failing hits shall be marked bad, not missing).

**Comment by slava77** [comment]
-1

superseded by #9756 ; moving to 756X developments

**Pull request closed without merging**
