### PR TITLE
[13_1_X] HGCAL: Fix HGCHEB isSiFE configuration

### PR DESCRIPTION
**Pull request by stahlleiton**
#### PR description:

This PR fixes a bug introduced in #39720 .
The parameter isSiFE was set to False by mistake which caused the energy scale in HGCAL scintillator (HEB) rechits to be shifted. Setting the isSiFE parameter back to True fixes the issue.

#### PR validation:

The PR was tested with: runTheMatrix.py -w upgrade -l 25300.0

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport of: https://github.com/cms-sw/cmssw/pull/41547

### CODE REVIEW

**Comment by missirol** [comment]
please test

**Comment by missirol** [comment]
backport of https://github.com/cms-sw/cmssw/pull/41547

**Comment by missirol** [comment]
+hlt

Bugfix for HGCal by HGCal DPG. I assume @beaucero and @SohamBhattacharya are okay with having it in the HLT Phase-2 menu.

**Comment by mandrenguyen** [comment]
type hgcal

**Comment by missirol** [comment]
@cms-sw/upgrade-l2 , any issue with signing this backport ?

**Comment by srimanob** [comment]
+Upgrade

**Comment by rappoccio** [comment]
+1

**Pull request merged**
