### PR TITLE
Run3-gex168 Modify all Run3 scenarios after fixing the HCAL SD issue

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Modify all Run3 scenarios after fixing the HCAL Sensitive DEtector (SD) issue. The dd4hep was using some additional SDs which need not be in the list producing hits in HCAL. This was corrected in #42463 and these corrections are incorporated in this list. If this causes a serious impact on the simulation, it clearly indicates that this PR needs to be back ported to 13_2_X, 13_1_X, 13_0_X 

#### PR validation:

Use the runTheMatrix test workflows

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport to be decided later

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
+geometry

**Comment by bsunanda** [comment]
@srimanob Please approve this

**Comment by perrotta** [comment]
@bsunanda I imagine you refere to the new geometries xml files integrated with #42463
Please, write in the PR description of this PR:
- what was the issue fixed by those modified geometry files
- what differences are you expecting in output, so that one can judge the large number of differences observed in the tests

**Comment by srimanob** [comment]
Hi @bsunanda @perrotta 

I would propose, for Run-3, after the PR is merged to master, we ask PdmV to look on impact of the bug and decide if we should backport or not. Backporting will create inconsistent in the production release. I think we should do it only we understand the impact, and we would like to restart the production. If the impact is very small, I think the bug-fix should go only 2024, and legacy of Run-3.

By the way, should new geometry be created as payload for GT? @cms-sw/alca-l2 
If yes, maybe we should do it before the 13_3_0_pre2.

Thx.
FYI @cms-sw/pdmv-l2

**Comment by srimanob** [comment]
+Upgrade

**Comment by perrotta** [comment]
The differences are rather large in the test outputs, but they could be even due to the reshuffling of the random seeds, Definitely a validation is necessary to assess the size of the changes, and it could be done in pre2

Unless there are such macroscopic differences that would require to start once again the simulations with 13_0 (Run3) and 13_1 (Phase2), I wouldn't backport into those cycles. I would rather prepare a backport in 13_2 for the HI run and MC.

By the way, @bsunanda : ahem, what is a "SD"? Differences between the xml files after and before the fix are as:
```
 diff v2/hcalRecNumbering.xml v1/hcalRecNumbering.xml
21,23c21
<     <PartSelector path="//HBS.*"/>
<     <PartSelector path="//HTS.*"/>
<     <PartSelector path="//HVQX"/>
---
>     <PartSelector path="//HCal"/
```

**Comment by civanch** [comment]
@perrotta , SD is SensitiveDetector. The problem fixed in this PR does not change geometry itself but change names and list of SD labels assigned to geometry volumes. My personal impression that backports to 3_2 and 3_1 are safe, because no SIM production in these releases. Backport to 3_0 should be done when we understand consequences of this fix. So, @bsunanda , please,  prepare backports. Let us see what happens in 13_3_0_pre2  and after decide on backport.

**Comment by perrotta** [comment]
+1
- Validation with CMSSW_13_3_0_pre2 is expected

**Comment by srimanob** [comment]
> @perrotta , SD is SensitiveDetector. The problem fixed in this PR does not change geometry itself but change names and list of SD labels assigned to geometry volumes. My personal impression that backports to 3_2 and 3_1 are safe, because no SIM production in these releases. Backport to 3_0 should be done when we understand consequences of this fix. So, @bsunanda , please, prepare backports. Let us see what happens in 13_3_0_pre2 and after decide on backport.

Hi Vladimir, 13_1 is used for Phase-2 where production is almost done. I would avoid to backport to 13_1.

**Comment by perrotta** [comment]
Just to be clear: backports to 13_0 and 13_1 will be accepted only in the "worst case scenario", if we realize that the already started simulation is just rubbish,
Obviously, nobody want to do so!

**Comment by bsunanda** [comment]
I certainly agree with this. There are 3 PRs - one is to provide correct lists of SDs without disturbing the scenario definition. Then there is one to define the correct definition of the Run3 scenario and one to define the Phase2 scenario. Certainly, the number 3 does not need any backport whatever the consequence is. Number 2 will depend on the impact on the simulation. But I do not see any harm in backporting the first one. It helps to evaluate in each case the level of impact. Also if the impact is large, we have to make a new set of payloads. Regards

Sunanda
________________________________

**Pull request merged**
