### PR TITLE
remove TestOldDigi

### PR DESCRIPTION
**Pull request by kpedro88**
#### PR description:

We no longer require compatibility with 11_0_X digis in 11_2_X.

#### PR validation:

Compiled and tested runTheMatrix.py.

### CODE REVIEW

**Comment by kpedro88** [comment]
please test

**Comment by kpedro88** [comment]
please test

**Comment by kpedro88** [comment]
+upgrade

**Comment by chayanit** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
