### PR TITLE
Fixes for regression in the persistency of std::string payloads

### PR DESCRIPTION
**Pull request by ggovi**
Fix for std::string type matching. A recent compiler change has changed the output of the 'demangler' for the std::string class.
Regression test adapted for execution in IB environment. This test will now run correctly once the above fix will be in a main release

### CODE REVIEW

**Comment by ggovi** [comment]
please test

**Comment by ggovi** [comment]
please test

**Comment by ggovi** [comment]
please test

**Comment by ggovi** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
