### PR TITLE
Remove unnecessary ROOT5/ROOT6 diffs in CondCore/IOVService

### PR DESCRIPTION
**Pull request by wmtan**
Some changes made to CondCore/IOVService in CMSSW_7_4_ROOT6_X should have also been made in CMSSW_7_4_X/7_5_X for code compatibility. This PR makes these changes in 7_5_X.
The changes are trivial, namely using the correct relative path to an included local header.

### CODE REVIEW

**Comment by davidlange6** [comment]
@cmsbuild, please test

**Comment by diguida** [comment]
+1

**Comment by ggovi** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
