### PR TITLE
Alca for hin 

### PR DESCRIPTION
**Pull request by franzoni**
make HI people happy - use run2_mc_hi where needs be (run2_mc_HIon)

@mandrenguyen @diguida

### CODE REVIEW

**Comment by slava77** [comment]
this is the third PR on top of #7692 (merging it inside already) and from what I understand another one is coming.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by diguida** [comment]
The change of the Run2 MC HI key is now cherry-picked in #7707

**Comment by slava77** [comment]
-1

superseded by #7707

**Comment by diguida** [comment]
-1

**Comment by franzoni** [comment]
Thanks @diguida @slava77 . Given that this one is " is now cherry-picked in #7707" , I close.

**Pull request closed without merging**
