### PR TITLE
HCALDQM: fix RecHitTask crash, adc2fC from DB, fix TPTask, add plots (92X backport of 18841)

### PR DESCRIPTION
**Pull request by DryRun**
Backport https://github.com/cms-sw/cmssw/pull/18841 to 9_2_X.

Edit: at @dmitrijus' request, here is the comment from the PR to master.

A few updates:

- Fix crash in RecHitTask exposed by beam splashes. For the plan-1 collapsed RecHits that do not exist in the actual detector, the HcalElectronicsId must not be used. One such case was hidden by an energy cut, so wasn't noticed earlier.
- Take adc2fC conversion from conditions instead of a hard-coded table.
- Integrated a fix for the number of samples in trigger primitive emulation, needed for TPTask to work.
- Add HF dual anode asymmetry plots. _Enabled by an Eras modifier, to ensure the code doesn't try to access nonexistent HFPreRecHits._
- _Add some timing plots for HEP17 phase scan._
- Smaller fixes: adjustments to axis ranges, ADC vs TDC plot, fix uMNIO crate# in fed2crate map, add HEP17 to local run tasks (LEDTask, PedestalTask, LaserTask), protect QIE11Task against laser and/or CRF digis ending up in QIE11DigiCollection (want only HEP17).

### CODE REVIEW

**Comment by dmitrijus** [comment]
+1

**Comment by DryRun** [comment]
Pinging @dmitrijus, @davidlange6 in case this PR has fallen off the radar (as well as the follow-up, https://github.com/cms-sw/cmssw/pull/19569, which fixes more bugs of similar species).  Please let me know if I can do anything to help these along.

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
CMSSW_9_2_X developement work is completed. Closing remaining PRs

**Pull request closed without merging**
