### PR TITLE
remove phase2_hgcalV9 modifier

### PR DESCRIPTION
**Pull request by kpedro88**
#### PR description:

After #30645, the `phase2_hgcalV9` modifier and various features to support the old HGCal geometry (which used HCAL for the scintillator part) are no longer needed.

This PR removes the modifier and simplifies the associated configuration files. In some cases, the former modifications were set as the default or as part of the base `phase2_hgcal` modifier; in other cases (e.g. tuning/calibrations), the modifications were moved into the `phase2_hgcalV10` modifier.

If HGCal experts (@cseez @rovere @bsunanda @jbsauvan) would prefer different choices in some of these cases, please comment on this PR.

This PR only addresses configuration files (and associated `fillDescriptions()`). Significant parts of the C++ code could be cleaned up further, but this is left to the existing issue #27095.

#### PR validation:

Ran workflow 23234.0 successfully.

### CODE REVIEW

**Comment by kpedro88** [comment]
please test

**Comment by bsunanda** [comment]
@kpedro88 I have a few corrections for dict2026. I shall wait till this PR is integrated. Meanwhile I have corrected the local cfi's for HGCal

**Comment by kpedro88** [comment]
+upgrade

**Comment by jfernan2** [comment]
+1

**Comment by cvuosalo** [comment]
+1

**Comment by jbsauvan** [comment]
Thanks @kpedro88, the L1THGCal changes look fine for me.

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/30702	ec631a6 
- code changes are in line with the PR description
- jenkins tests pass and comparisons with the baseline show no differences (apparently because pre-v9 tests were removed already)

**Comment by civanch** [comment]
+1

**Comment by slava77** [comment]
l1 signature is missing
please check/sign

**Comment by silviodonato** [comment]
+operations

**Comment by silviodonato** [comment]
@rekovic ?

**Comment by silviodonato** [comment]
merge

**Pull request merged**
