### PR TITLE
Soureek updating TOP trigger Pathnames according to CMSHLT-666

### PR DESCRIPTION
**Pull request by soureek**
The following paths have been renamed according to [1] as suggested in [2]
HLT_Ele23_WPLoose_Gsf_CentralPFJet30_BTagCSV07_v2
HLT_Ele27_WPLoose_Gsf_CentralPFJet30_BTagCSV07_v1
HLT_Ele32_eta2p1_WPLoose_Gsf_CentralPFJet30_BTagCSV07_v2
HLT_IsoMu18_CentralPFJet30_BTagCSV07_v2
HLT_IsoMu22_CentralPFJet30_BTagCSV07_v2
HLT_IsoMu24_eta2p1_CentralPFJet30_BTagCSV07_v4

[1] https://docs.google.com/spreadsheets/d/1jQbCdbkrsoirLJ9_UvN-xEvjYbtPnHqRHKDwwB8iHFg/edit#gid=0
[2] https://its.cern.ch/jira/browse/CMSHLT-666

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1

**Comment by Soureek89** [comment]
I have corrected for the errors obtained during tests triggered by jenkins. I tested the code by running the matrix for TTbar events. Test results show the following message.

25.0_TTbar+TTbar+DIGI+RECOAlCaCalo+HARVEST+ALCATT Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Fri Jan 22 15:20:45 2016-date Fri Jan 22 15:04:02 2016; exit: 0 0 0 0 0
1 1 1 1 1 tests passed, 0 0 0 0 0 failed 

Please cross-check again for any possible update.

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
+1
would be easier to maintain these arrays of strings if they were put into an array once and then used instead of being repeated two times

**Pull request merged**
