### PR TITLE
Update Material Budget Analyzer Configuration

### PR DESCRIPTION
**Pull request by ianna**
- Add Hcal parameters and constants required to run it
- Add instructions on how to disable big libraries to avoid assertion

### CODE REVIEW

**Comment by ianna** [comment]
@cmsbuild please test

**Comment by civanch** [comment]
+1
@ianna , a good idea to add a comment to macro file

**Comment by davidlange6** [comment]
@ianna @smuzaffar - what does not work with big libraries?

**Comment by smuzaffar** [comment]
@davidlange6 , Not sure yet. I will check with @ianna

**Comment by smuzaffar** [comment]
SimG4Core/PrintGeomInfo depends on packages
```
SimG4Core/Notification
SimG4Core/Geometry
```
which are part of big-lib. So SimG4Core/PrintGeomInfo should also end up in BigProducts/Simulation/BuildFile.xml

@ianna , can you please add it in BigProducts/Simulation/BuildFile.xml and cleanup the  disable big libraries comment?

**Comment by ianna** [comment]
@davidlange6 and @smuzaffar - these are tests based on SimG4CoreGeometry which is not in Simulation biglib, I think. It brings in G4 shared libraries. I do not think, we need or want to bundle it all together.

**Comment by ianna** [comment]
@davidlange6 - there is nothing to do for this PR - could you, please, merge it? Thanks.

**Comment by civanch** [comment]
@ianna , as Shahzad  commented, it is possible to avoid disable of biglibs by a simple addition to
BigProducts/Simulation/BuildFile.xml :

  <use name="SimG4Core/PrintGeomInfo"/>

After that the test works in both cases when biglib enabled and disabled. It seems that an addition of PrintGeomInfo to biglib should not bring any penalty.

**Comment by ianna** [comment]
@civanch - as we've discussed with @smuzaffar, this solution would require to build biglibs with G4 Geometry libraries and also these tests. It would be loaded for production as a non-used extra. Do we really want it?

**Comment by civanch** [comment]
@ianna , I would agree that this is not the only test which require disable biglib. If I understand your point correctly, we should not add to biglib all sub-directories with unit tests, instead likely should add comments as you did in this PR. This PR is a first example and in this view this PR may be merged.

**Comment by ianna** [comment]
@civanch - yes, it's not like we run the tests for release validation. Even then, a solution can be found.

**Comment by davidlange6** [comment]
@ianna -sorry to be slow to answer - this is a self contained package (that is small), and not a test (the code is in src not in test). There is no downside I see to moving it into the big library which is where it should have been already. 

But, then I don't understand your comment that "would require to build biglibs with G4 Geometry libraries" - what new dependences are there?

**Comment by civanch** [comment]
@davidlange6 , if it would be the only test sub-package which requires disabling biglib it is easy to add Shahzad fix but there are other sub-packages with tests mainly related to geometry. All these sub-directories are not used in SIM production, is there sense to extend our biglib with several extra sub-packages?

**Comment by davidlange6** [comment]
what are some examples?

**Comment by civanch** [comment]
@davidlange6 , for example, Validation/Geometry sub-package.

**Comment by civanch** [comment]
@davidlange6 , we likely will work more on this sub-package, so an addition to biglib can be done in the next PR if needed.

**Comment by ianna** [comment]
@davidlange6 - this one is more like a utility/test even it is in src (historically?). Unfortunately, it requires SimG4Core/Geometry shared library which is not in biglib. We've discussed it with @smuzaffar yesterday - we can provide a python fragment centrally to be able to remove biglibs from the path to run these tests. Then, every test python configuration can include it if relevant.

**Comment by smuzaffar** [comment]
Yes, I was discussing this with Ianna and thought that we might play some tricks (e.g resetting LD_LIBRARY_PATH to not have biglibs) in the python configuration but looks like that is not going to work.

@ianna , SimG4Core/Geometry is part of Biglib. It is mentioned in the https://github.com/cms-sw/cmssw/blob/CMSSW_8_0_X/BigProducts/Simulation/BuildFile.xml .

**Comment by ianna** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by smuzaffar** [comment]
+1

**Comment by davidlange6** [comment]
thanks! @civanch - seems we should do the same thing with Validation/Geometry (maybe the histograming plugins should be moved to plugins directory as to separate them more cleanly.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
