### PR TITLE
fix PU range for highPU (81x)

### PR DESCRIPTION
**Pull request by mtosi**
this PR is meant to fix the binning of histograms as functions of PU
in addition plots w/ pixel and strip cluster multiplicity have been defined  to have axis automatically extended in case the predefined range is too small

this PR can be useful in DQM step on run 283171 (highPU fill)
@dmitrijus @vanbesien @rovere @VinInn @makortel

### CODE REVIEW

**Comment by VinInn** [comment]
@cmsbuild , please test

**Comment by VinInn** [comment]
type backport

**Comment by mtosi** [comment]
sorry
I've just fixed a typo

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
