### PR TITLE
Backport for Totem T2, to be used in the special run at 25.6, consisting of #41472 , #41777 and #41859

### PR DESCRIPTION
**Pull request by oljemark**
#### PR description:

For the TOTEM special foreseen on 25.6.2023, the new T2 telescope will be used (and removed after the run) to measure inelastic rate and veto diffractive p+p collisions, when measuring the elastic p+p cross section.

This is a backport of three PR's: PR #41472 introduced 2-channel unpacking for T2, PR #41777 included T2 DQM plots additions and fixes, and PR #41859 added the T2 to the online DQM calibration path, but was descoped from including T2 RecHit reconstruction and use in DQM since some relVals were failing with "Deleting previous geometry: cmsMagneticField:MAGF/Detector" at the step where the T2 XML geometry was read in; this is possibly similar to issue #33203 (see discussion here: https://github.com/cms-sw/cmssw/pull/41859#issuecomment-1581990537 ). 
After the descoping, T2 Digis are successfully saved in the event and used to produce Digi-based DQM plots in common reconstruction with the rest of the PPS detectors. An additional fourth PR with final DQM plot updates is being prepared for submission to master this weekend, that will also be backported to 13_0_X.

This backport is for a special TOTEM release to be ready for testing start of next week (https://github.com/cms-sw/cmssw/pull/41859#issuecomment-1584370879).

#### PR validation:

T2 & PPS unit tests were run successfully, as were several PPS workflows and a few relVals that had failed with the geometry error noted above, before descoping of PR #41859 .

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

This is a backport to 13_0_X for a special TOTEM release, consisting of three recent Totem T2 PRs: #41472 , #41777 & #41859 .

### CODE REVIEW

**Comment by mandrenguyen** [comment]
backport of #41472 #41777 #41859
Are we also going to backport this to 13_1_X?

**Comment by mandrenguyen** [comment]
type ctpps

**Comment by mandrenguyen** [comment]
please test

**Comment by perrotta** [comment]
> Are we also going to backport this to 13_1_X?

To be decided. We either
- build a dedicated release for the Totem run, in a separate brach off 13_0_X (in this case no backport to 13_1_X will be needed)
- or merge in the main 13_0_X (in which case a backport to 13_1_X will also be needed, to allow continuity through the release cycles)

**Comment by oljemark** [comment]
Hi, @perrotta . I submitted the fourth PR with DQM plot fixes here: PR #41922

**Comment by mandrenguyen** [comment]
+reconstruction

**Comment by rappoccio** [comment]
This PR will need a "backport" to https://github.com/cms-sw/cmssw/tree/CMSSW_13_0_7_TOTEM_X before we create the release.

**Comment by perrotta** [comment]
> This PR will need a "backport" to https://github.com/cms-sw/cmssw/tree/CMSSW_13_0_7_TOTEM_X before we create the release.

I have modified the target to CMSSW_13_0_7_TOTEM_X
Still pretty mergeable in the new base

**Comment by tvami** [comment]
Hmm arent there some unrelated PRs appearing? Stuff from Marco from May, etc? (https://github.com/cms-sw/cmssw/pull/41916/commits/8a7a7a2dfaae8662a2a267c2186d8e37e486c387, etc)

**Comment by perrotta** [comment]
@oljemark please rebase to the new CMSSW_13_0_7_TOTEM_X branch, as it was discussed and agreed at today's joint operation meeting

**Comment by perrotta** [comment]
please test

**Comment by tvami** [comment]
"Unable to find CMSSW IB for CMSSW_13_0_7_TOTEM_X."

**Comment by tvami** [comment]
@cmsbuild , please test for CMSSW_13_0_X

**Comment by perrotta** [comment]
> "Unable to find CMSSW IB for CMSSW_13_0_7_TOTEM_X."

@smuzaffar is it possible to start the IBs for the CMSSW_13_0_7_TOTEM_X (production architecture is enough) so that we can test this and the other Totem PR? Thank you!

**Comment by perrotta** [comment]
> sure I can set up the IB but do we really need it? Can you test this PR based on CMSSW_13_0_7 release itself e.g. using `please test for CMSSW_13_0_7` to test these changes on top of CMSSW_13_0_7?

Ah, cool! Yes, we can do so

**Comment by perrotta** [comment]
please abort

**Comment by tvami** [comment]
given that there is no `CMSSW_13_0_8`, wasnt testing for `CMSSW_13_0_X` the same as testing for `CMSSW_13_0_7`? That's what I had in mind when doing https://github.com/cms-sw/cmssw/pull/41916#issuecomment-1587508956

**Comment by mandrenguyen** [comment]
+1 
resign

**Comment by emanueleusai** [comment]
+1

**Comment by tvami** [comment]
+1

**Comment by rappoccio** [comment]
+1

**Comment by syuvivida** [comment]
@oljemark 
could you check if the output of the playback test is ok? Thanks!! We used run 367104 for the test. 
The output root file is here: /eos/cms/store/group/comm_dqm/temp_DQMGUI_data_repository/totem/

**Comment by mmusich** [comment]
@syuvivida I might have missed where the playback request was done. Please remember to keep ORM in the loop when discussing the preparations for the totem run.

**Comment by oljemark** [comment]
Hi @syuvivida . The recent replay test on the 13_0_7_TOTEM release used run 368805, where TOTEM T2 & TrackingStrips were connected. Also, was this test done with the PPS DQM client in normal mode? The TrackingStrips & TotemT2 are only run in the calibration mode, set here https://github.com/CTPPS/cmssw/blob/0a38b0798473b67bf0e3e09296a128103c9ba8c7/DQM/Integration/python/clients/ctpps_dqm_sourceclient-live_cfg.py#L94

**Comment by vavati** [comment]
> @oljemark could you check if the output of the playback test is ok? Thanks!! We used run 367104 for the test. The output root file is here: /eos/cms/store/group/comm_dqm/temp_DQMGUI_data_repository/totem/

@syuvivida : we cannot judge the output in view of the Totem run as the run you have selected does not have T2 data neither strips data. So i suggest you use the same used for the T0 reply otherwise the test is not conclusive

**Comment by syuvivida** [comment]
@oljemark @vavati indeed this test was done with the normal mode. We will switch to the calibration mode. We will request the streamers of 368805. But I also noticed in run registry that PPS was excluded in this run 368805. Is this ok for the test?

**Comment by mmusich** [comment]
@syuvivida 

Screenshot from 2023-06-16 11-26-59

let me repeat myself, this sort of things need to coordinated at the joint ops level...

**Comment by syuvivida** [comment]
@mmusich sorry I forgot to reply to you earlier. We are discussing about the playback runs in the online DQM machines. In the past, this piece of information was usually passed from the other DQM convener @emanueleusai to the DQM core team (after either reading the code or communication with the authors).

**Comment by mmusich** [comment]
>  We are discussing about the playback runs in the online DQM machines. In the past, this piece of information was usually passed from the other DQM convener 

@syuvivida I let you (as DQM expert) to clear up the internal details of the online DQM. What I mean is that for information such as which run to test, which Global Tags to use, etc., the ORM chat is the best place to ask, to avoid picking up configurations at random.

**Comment by syuvivida** [comment]
@oljemark @vavati we just received streamers of 368805 at our playback machines this morning. The calibration sequence was turned on in this playback run. 
Please take a look of the output root file here and let us know if the plots look ok. Thanks!!
/eos/cms/store/group/comm_dqm/temp_DQMGUI_data_repository/totem/DQM_V0001_CTPPS_R000528350.root

**Comment by vavati** [comment]
> @oljemark @vavati we just received streamers of 368805 at our playback machines this morning. The calibration sequence was turned on in this playback run. Please take a look of the output root file here and let us know if the plots look ok. Thanks!! `/eos/cms/store/group/comm_dqm/temp_DQMGUI_data_repository/totem/DQM_V0001_CTPPS_R000528350.root`

@syuvivida  Thanks. I checked and the plots looks ok (at least they are not empty!) If you didn't get any issue during the playback I would say that these are validated. Next step will be another global run in a couple of days when T2 will be installed.

**Pull request merged**
