### PR TITLE
75X: New GT with L1T v5 and thus new HLT selection

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
75X: New GT with L1T v5 and thus new HLT selection

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
+1

**Comment by Martin-Grunewald** [comment]
+1

**Comment by mmusich** [comment]
@Martin-Grunewald we needed to change the L1 RCT calibrations since they were wrong in Run2 MC GTs. Can you please cherry-pick https://github.com/cms-sw/cmssw/commit/9c185cca4f0517ddb3b65e3281a3fa31e57bfce5?

**Comment by diguida** [comment]
hold
wait for cherry pick

**Comment by Martin-Grunewald** [comment]
@mmusich @diguida 
Done, please un-hold.

**Comment by Martin-Grunewald** [comment]
please test

**Comment by diguida** [comment]
+1

**Comment by Martin-Grunewald** [comment]
+1

**Comment by mmusich** [comment]
@davidlange6 can this be merged? it already has merge conflicts with #11598

**Comment by davidlange6** [comment]
+1

**Pull request merged**
