### PR TITLE
HLTrigger/ cleaned up by clang-tidy modernize checks

### PR DESCRIPTION
**Pull request by fwyzard**
Enabled checks:
    modernize-loop-convert
    modernize-make-unique
    modernize-pass-by-value
    modernize-redundant-void-arg
    modernize-replace-auto-ptr
    modernize-shrink-to-fit
    modernize-use-auto
    modernize-use-default
    modernize-use-nullptr
    modernize-use-override

### CODE REVIEW

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
Almost all changes were done automatically by clang-tidy.
People please comment if they seem meaningful, if the style looks decent, etc.

**Comment by fwyzard** [comment]
@bartonaz , do you think it would be feasible to run `hltDiff` and build your web page to check the results, based on the comparison run as part of the PR integration ?

**Comment by bartosik-hep** [comment]
@fwyzard Yes, I can run `hltDiff` and check the results.
If I understand correctly, I can just rerun one of our recent event-by-event validations with and without this PR merged, and the results should be identical, right?

**Comment by fwyzard** [comment]
What I had in mind is, the integration tests already run the HLT (among others) with and without the changes.
Can you try to access those results and run hltDiff over them ?

If it works we could try to have it done automatically as part of the integration tests.

**Comment by bartosik-hep** [comment]
Sure, this is a better solution. 
I only see root files under the `Matrix Tests Outputs` section, like here: https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-18436/19313/runTheMatrix-results/50202.0_TTbar_13+TTbar_13+DIGIUP15_PU50+RECOUP15_PU50+HARVESTUP15_PU50/
and file `step3_inMINIAODSIM.root` seems to be the one that can be used for a comparison.

But I don't know how to access those files from lxplus. @fwyzard, do you know?

**Comment by fwyzard** [comment]
To start, I guess you can just download them, something like 
```wget https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-18436/19313/runTheMatrix-results/50202.0_TTbar_13+TTbar_13+DIGIUP15_PU50+RECOUP15_PU50+HARVESTUP15_PU50/step2.root```

.A

**Comment by bartosik-hep** [comment]
`wget` didn't work for downloading the files, because only authenticated users can access those files.

Nevertheless, I downloaded them by hand, run `hltDiff` over each pair of files with 5 or 10 events in each file. They all have identical HLT results, with no affected events.

**Comment by fwyzard** [comment]
Good !

Can you put the resulting web pages up somewhere ?
I would like to ask the people that maintain the integration tests if hltDiff could be run automatically and the pages made available under https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-18436/ ...

**Comment by bartosik-hep** [comment]
Here is the summary page generated from JSON output of hltDiff: https://cms-hltdiff-visual.web.cern.ch/cms-hltDiff-visual/?files=/afs/cern.ch/user/n/nbartosi/public/relval/2017_04_21_pr18436/#results_path

There is not much to see, just the total number of processed events, since no changes were found.
But what is suspicious is that the list of skipped trigger paths is not empty, meaning that some paths were present in `TriggerResults` of one file, but not the other. This can be seen better when looking at an [individual file](https://cms-hltdiff-visual.web.cern.ch/cms-hltDiff-visual/?files=/afs/cern.ch/user/n/nbartosi/public/relval/2017_04_21_pr18436/step3_25202.0_TTbar_13_TTbar_13_DIGIUP15_PU25.root.json#results_path).

And I have to mention that these web pages are not statically generated by the server, but they are interactive – generated from JSON input by the browser, using JavaScript. Therefore, making just static HTML pages out of them is not very straightforward. So one has to think carefully what information is needed and in which way it has to be viewed.

**Comment by Martin-Grunewald** [comment]
+1

**Comment by fwyzard** [comment]
@bartonaz 
> There is not much to see, just the total number of processed events, since no changes were found.
But what is suspicious is that the list of skipped trigger paths is not empty, meaning that some paths were present in TriggerResults of one file, but not the other. This can be seen better when looking at an individual file.

Looks like the comparison was done across (or at least included) different "steps": the HLT step, and the RECO/DQM step.
For example, how did you generate `/afs/cern.ch/user/n/nbartosi/public/relval/2017_04_21_pr18436/step3_25202.0_TTbar_13_TTbar_13_DIGIUP15_PU25.root.json` ?

> And I have to mention that these web pages are not statically generated by the server, but they are interactive – generated from JSON input by the browser, using JavaScript. Therefore, making just static HTML pages out of them is not very straightforward. So one has to think carefully what information is needed and in which way it has to be viewed.

Ah, I see. But the it would be enough to make the json file with the differences available, and build a link that would submit it to the dynamic pages, right ?

By the way, I think hltDiff can also produce DQM-like plots ?

**Comment by davidlange6** [comment]
+1

**Comment by bartosik-hep** [comment]
> For example, how did you generate /afs/cern.ch/user/n/nbartosi/public/relval/2017_04_21_pr18436/step3_25202.0_TTbar_13_TTbar_13_DIGIUP15_PU25.root.json

This file was generated with the following command:
`hltDiff -o files/baseline/step3_25202.0_TTbar_13_TTbar_13_DIGIUP15_PU25.root -O HLT -n files/pr/step3_25202.0_TTbar_13_TTbar_13_DIGIUP15_PU25.root -N HLT -jc`

The file paths are given wrt: `/afs/cern.ch/work/n/nbartosi/cms/relval/2017_04_21_pr18436/`
Those files come from `step3.root` in https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-18436/19313/runTheMatrix-results/25202.0_TTbar_13+TTbar_13+DIGIUP15_PU25+RECOUP15_PU25+HARVESTUP15_PU25/, and  have only two `TriggerResults` payloads, with labels `RECO` and `HLT`.

- - -

> Ah, I see. But the it would be enough to make the json file with the differences available, and build a link that would submit it to the dynamic pages, right ?

Yes, it is true. That's the way how I'm using it. The only thing to note is that the JSON files have to be stored in a publicly-accessible AFS folder, otherwise the web-server will not be able to access the files.

- - -

> By the way, I think hltDiff can also produce DQM-like plots ?

Yes, it can. If just summary plots are enough, it can be an easier option.

**Pull request merged**
