### PR TITLE
Phase2-hgx276 Fifth step of making V15 geometry for HGCal

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Fifth step of making V15 geometry for HGCal by enabling mixed player formation

#### PR validation:

Tested by dumping the geometry and checking overlaps

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cvuosalo @srimanob @kpedro88 Could you approve this PR?

**Comment by cvuosalo** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

**Comment by qliphy** [comment]
+1

**Pull request merged**
