### PR TITLE
Run3-TB57 Update the cfi/cfg files for HGCal TB studies

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Update cfi/cfg files for HGCal TB studies

#### PR validation:

Tested with cfg files in SimG4CMS/HGCalTestBeam

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade

**Comment by civanch** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
