### PR TITLE
Run3-gex155X Backport #40865 to CMSSW_13_0_X for additional Run3 files needed as the step1 for making 2023 geometry payload

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Backport #40865 to CMSSW_13_0_X for additional Run3 files needed as the step1 for making 2023 geometry payload

#### PR validation:

Use the runTheMatrix test workflows

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

This is backport of #40865

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by srimanob** [comment]
test parameters:
- workflow = 12434.911
- relvals_opt = --what cleanedupgrade,standard,highstats,pileup,generator,extendedgen,production,ged,machine,premix,nano,gpu
- pull_request = https://github.com/cms-sw/cmssw/pull/40883

**Comment by srimanob** [comment]
@cmsbuild please test

**Comment by srimanob** [comment]
please abort

**Comment by srimanob** [comment]
+Upgrade

Test in https://github.com/cms-sw/cmssw/pull/40883#issuecomment-1445028932 runs fine.

**Comment by perrotta** [comment]
+1
- This PR backports the xml files necessary for making the 2023 geometry payloads.
- I imagine that some validation of the new geometry should be provided before actually implementing them in 13_0_0, i.e. when merging #40883

**Pull request merged**
