### PR TITLE
Backport: Light by light modifier PR 103X

### PR DESCRIPTION
**Pull request by rchudasa**
#### PR description:
@slava77 @echapon 
This PR is a backport of following PRs. 

* https://github.com/cms-sw/cmssw/pull/26763 updating SC reg corrector for UL (May 16)
* https://github.com/cms-sw/cmssw/pull/26892 adding V3 modifier (Jun 13)
* https://github.com/cms-sw/cmssw/pull/27633 Light by light modifier (Aug 22)
* https://github.com/cms-sw/cmssw/pull/27871 tracker cluster cut (Aug 27)
* https://github.com/cms-sw/cmssw/pull/28051 low-pt regression (Oct 15)

This PR is submitted to reconstruct low pT photons down to 2 GeV for light by light scattering.

### CODE REVIEW

**Comment by kpedro88** [comment]
please test

**Comment by slava77** [comment]
one important missing piece for the reprocessing is the egamma regression.
IIUC, this requires code and configuration changes.
What is the status of it?

**Comment by slava77** [comment]
backport of #27633 
backport of #27871 

@smuzaffar 
do we have a way to denote many-to-one PR backports?

**Comment by rchudasa** [comment]
> one important missing piece for the reprocessing is the egamma regression.
> IIUC, this requires code and configuration changes.
> What is the status of it?

I am working on it and we expect to close it next week.

**Comment by slava77** [comment]
> > one important missing piece for the reprocessing is the egamma regression.
> > IIUC, this requires code and configuration changes.
> > What is the status of it?
> 
> I am working on it and we expect to close it next week.

@rchudasa 
please update on the status.
Thank you.

**Comment by slava77** [comment]
@rchudasa
please update on the status by some time Tuesday early afternoon.
This should help to understand the release needs during the release planning meeting tomorrow.
Thank you.

**Comment by rchudasa** [comment]
@slava77 
We (with @Sam-Harper ) could figure out the issue in Backport regression PR of Sam's. It works fine for low pt SuperClusters now. We are checking the regressions for photons and electrons now. Once all three are ready, Sam will upload them to python config. I hope it should be ready in 2 days.

**Comment by slava77** [comment]
@rchudasa
please update on the status by some time Tuesday early afternoon.
This should help to understand the release needs during the release planning meeting tomorrow.
Thank you.

**Comment by rchudasa** [comment]
@slava77 
Low pt SC, photon and electron regressions are ready and it just needs to be uploaded by @Sam-Harper  in python config but he is away at CMS POS and busy, he might be able to do it in 2-3 days

**Comment by slava77** [comment]
> @slava77
> Low pt SC, photon and electron regressions are ready and it just needs to be uploaded by @Sam-Harper in python config but he is away at CMS POS and busy, he might be able to do it in 2-3 days

@rchudasa @Sam-Harper 
please let me know the status of this.
Thank you.

**Comment by Sam-Harper** [comment]
Doing it right now.

**Comment by Sam-Harper** [comment]
Okay done. So unfortunately we merge conflict by editing the same file so it has to be in one PR. 

I've made an example here:
https://github.com/cms-sw/cmssw/compare/CMSSW_10_3_X...Sam-Harper:LightByLightModifierWithReg_1033_patch1?expand=1

Ruchi it is probably best to update this branch with both of them as a result. 

git cms-merge-topic Sam-Harper:LightByLightModifierWithReg_1033_patch1 #just a simple way to checkout the branch, dont actually need to merge
git push my-cmssw Sam-Harper/LightByLightModifierWithReg_1033_patch1:LightByLightModifier_1033_patch1

alternatively I can open a new PR with that branch. 

Note the enabling of the regression is this commit:
https://github.com/cms-sw/cmssw/commit/4d4f51c01afef3fa0ab461c9f895070f093ffe0f

**Comment by rchudasa** [comment]
Thank you @Sam. 

@slava77 
The branch is updated with regression commits from Sam now.

**Comment by slava77** [comment]
@cmsbuild please test

@Sam-Harper 
does everything that was added to this PR already have an equivalent in the master branch?
As usual, all new features enter the master branch first.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by Sam-Harper** [comment]
The last commit technically does not. I'll commit it now.

**Comment by Sam-Harper** [comment]
done: https://github.com/cms-sw/cmssw/pull/28051

**Comment by rchudasa** [comment]
@slava77 
Is there anything remaining from our side for this PR to be merged?

Thanks.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@rchudasa 
please update the PR description to reflect the full list of backports.
Here is what I see, including the merge dates in the master:
- #26763 updating SC reg corrector for UL (May 16)
- #26892 adding V3 modifier (Jun 13)
- #27633 Light by light modifier (Aug 22)
- #27871 tracker cluster cut  (Aug 27)
- #28051 low-pt regression (Oct 15)

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/27898	4d4f51c 
- backports of #26763, #26892, #27633, #27871, #28051 are correct (the combined diff is not the same due to some differences introduced in the context, e.g. in #27477 and #25574)
- code changes are (somewhat) in line with the PR description; more backports were added since the PR was opened https://github.com/cms-sw/cmssw/pull/27898#issuecomment-542392569. This PR introduces changes needed for a special workflow to be enabled with ```--procModifiers egamma_lowPt_exclusive``` and does not affect the standard workflows.
- jenkins tests pass and comparisons with the baseline show no differences 
- local tests with a reference file from HIForward2018A run 326854 using ```103X_dataRun2_Prompt_LowPtPhotonReg_v1``` shows roughly expected behavior
    - CPU time is generally down, mostly by trimming the processing tails in tracking: average time on 10K events is down from 0.43 s/ev to 0.35 s/ev and the max time from 613 to 13 s/ev
    - max RSS on 8-thread job is down from 5.4 GiB to 3.1 GiB (due to trimmings starting from tracking)
    - AOD output size increased by about 50% from 20 to 32 kiB/ev driven by caloTowers and siPixelClusters

perhaps the most striking is the increase in the number of gedPhotons
all_sign1085VSorig_HIForward2018Ac_recoPhotons_gedPhotons__RECO_obj_et
Here in 103X with this PR and ```103X_dataRun2_Prompt_LowPtPhotonReg_v1``` we have about 0.68 photons per event, compared to my last test in 11X/master of #28051 using ```110X_dataRun2_PromptLike_HI_Candidate_2019_09_30_11_30_43``` with 0.53 photons per event (on the same input file). It seems like either some of the egamma calibrations are substantially different or there may be some other differences affecting the yield of photons in the two releases.

Comparing the distributions in the 11X version with 103X, the caloTowers look fairly similar.
It seems like most of the differences are in the endcaps.
Here are a few plots comparing the master version (in black) with this PR (in red)
The EE SC energy shape looks similar
all_CMSSW_10_3_X_2019-10-13-0000-sign1085VSCMSSW_11_0_0_pre10-sign1089-lbl_HIForward2018Ac_log10recoSuperClusters_particleFlowSuperClusterECAL_particleFlowSuperClusterECALEndcapWithPreshower_RECO_obj_energy

EE SC corrected E uncertainty is much larger in 103X
all_CMSSW_10_3_X_2019-10-13-0000-sign1085VSCMSSW_11_0_0_pre10-sign1089-lbl_HIForward2018Ac_log10max1e-5,recoSuperClusters_particleFlowSuperClusterECAL_particleFlowSuperClusterECALEndcapWithPreshower_RECO_obj_correctedEnergyUncertainty

I'm signing off, leaving the differences to possible peculiarities in the GTs used in the tests. The GTs are set outside of the reco PRs.

**Comment by fabiocos** [comment]
+operations

the backport of the ```Configuration/ProcessModifier``` update is coherent with the master version

**Comment by fabiocos** [comment]
+1

**Pull request merged**
