### PR TITLE
add customization function for highPU @HLT

### PR DESCRIPTION
**Pull request by mtosi**
this customization function should be used by STEAM --for the moment-- in order to increase the threshold on strip and pixel clusters multiplicity

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
If it is for STEAM only, why does it have to be in the release?

**Comment by mtosi** [comment]
I think it might be useful for future development as well
  mia

**Comment by silviodonato** [comment]
Hi Mia, can you explain better why this should be in the release?
When it would be applied?

**Comment by mtosi** [comment]
if we need to run on samples (either data or MC) w/ large PU
  mia

**Comment by silviodonato** [comment]
@cmsbuild  please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
