### PR TITLE
Run4-hgx277 Adding a new scenario for October 18 TB setup

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Adding a new scenario for October 18 TB setup

#### PR validation:

Use cfg's in SimG4CMS/HGCalTestBeam/test

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
Comparison tests seem to show many unexpected differences in Phase 2 workflows.

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

**Comment by qliphy** [comment]
+1

**Pull request merged**
