### PR TITLE
DAQ - fixing streamer count of HLT paths with the GlobalEvFOutputModule (12_2_X)

### PR DESCRIPTION
**Pull request by smorovic**
PR description:
Calculating trigger names and module ID in constructor so that it is
available both for for serializeRegistry and serializing event with the
GlobalEvFOutputMOdule

Resolves https://github.com/cms-sw/cmssw/issues/37029

This issue is critical for DQM for running in CRAFT from the Feb 28th.

PR validation:
Tested with a scripted test:
/afs/cern.ch/user/s/smorovic/public/test_outputmodule (see also https://github.com/cms-sw/cmssw/issues/37029)
The test passes with this patch.
The test will also be integrated into the existing unit test (pending work planned for another PR).

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Backport of #37054

### CODE REVIEW

**Comment by smorovic** [comment]
@cmsbuild please test

**Comment by smorovic** [comment]
+1

**Comment by makortel** [comment]
+1

**Comment by francescobrivio** [comment]
backport of #37054

**Comment by francescobrivio** [comment]
urgent

 - possibly needed for CRAFT

**Comment by qliphy** [comment]
+1

**Pull request merged**
