### PR TITLE
Photos createHistoryEntries (94X)

### PR DESCRIPTION
**Pull request by mseidel42**
94X backport of #28785

### CODE REVIEW

**Comment by silviodonato** [comment]
backport of #28785

**Comment by silviodonato** [comment]
@intrepid42  why do you need these backports in 94X and 71X? Our ultra-legacy release for Run-2 is 10_6_X

**Comment by intrepid42** [comment]
Hi Silvio, we need it for W mass in 2016 (71X) and 2017 lowPU (94X) production.
At the moment it does not look like this will happen as UL but I will create a backport to 106 as well!

**Comment by qliphy** [comment]
please test

**Comment by qliphy** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
