### PR TITLE
improve TkMaps 81X

### PR DESCRIPTION
**Pull request by fioriNTU**
Add run number to tracker maps, clean index html removing unrelevant maps and remove cndDBv2 stuff

### CODE REVIEW

**Comment by VinInn** [comment]
@cmsbuild , please test

**Comment by deguio** [comment]
my understanding is that this classes are not used in central workflows. referring for example to the SiStripTrackerMapCreator. could you confirm?
thanks,
F.

**Comment by fioriNTU** [comment]
Exactly, they are used only Offline by the Tracker shifters to produce 
Tracker Maps

ciao,
FF
Il 10/04/2016 15.31, Federico De Guio ha scritto:
>
> my understanding is that this classes are not used in central 
> workflows. referring for example to the SiStripTrackerMapCreator. 
> could you confirm?
> thanks,
> F.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub 
> <https://github.com/cms-sw/cmssw/pull/13973#issuecomment-207985618>
>



---
Questa e-mail è stata controllata per individuare virus con Avast antivirus.
https://www.avast.com/antivirus

**Comment by deguio** [comment]
+1

**Comment by fioriNTU** [comment]
Hi all, is there any reason why this PR is not merged?

**Comment by davidlange6** [comment]
@fioriNTU - apologies for the delay - just a reminder that TkDetMap should really become a ESSource and derive its information from the geometry...

**Comment by davidlange6** [comment]
+1

**Pull request merged**
