### PR TITLE
Speed improvements for TauJetRegionProducer

### PR DESCRIPTION
**Pull request by lgray**
Passing vectors by value is a sin against many deities.

### CODE REVIEW

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
I think I found a reasonable way to get rid of the time spent in the module itself as well. Working on it.

**Comment by lgray** [comment]
@cmsbuild please test

Latest additions bring the module down by factor 1000 or so.

**Comment by lgray** [comment]
@cmsbuild please abort

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
@cmsbuild please test

Found more low hanging fruit in the boosted tau seeds.

**Comment by cvuosalo** [comment]
While you're improving performance, it might be nice to change BoostedTauSeedsProducer.cc to support multi-threading. On line 45, the class just needs to inherit from a thread-safe version of EDProducer:

class BoostedTauSeedsProducer : public edm::EDProducer

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
+1

For #17040 ca0699a8b2c15fc5b08a1ba76e1d619f7ee15822

Speeding up TauJetRegionProducer by caching a jet-to-PF-candidate map  to avoid unnecessary, repetitive searches. There should be no change in monitored quantities.

The code changes are satisfactory, and Jenkins tests against baseline CMSSW_9_0_X_2016-12-16-1100 show no significant differences, as expected. A test was performed against baseline CMSSW_9_0_0_pre2 using 200 events of the following file:
```
/store/relval/CMSSW_9_0_0_pre1/RelValTTbar_14TeV/GEN-SIM-RECO/PU25ns_90X_upgrade2023_realistic_v0_2023D4PU200r2-v1/10000/0099452E-F7BD-E611-99D4-0CC47A4C8E0E.root
```
This test performed only the PAT, DQM, and Validation steps with the command (plus the standard step4 command):
```
 cmsDriver.py step3  --conditions auto:phase2_realistic --era Phase2C2 --eventcontent MINIAODSIM,DQM --runUnscheduled  -s PAT,VALIDATION:@miniAODValidation,DQM:@miniAODDQM --datatier MINIAODSIM,DQMIO --geometry Extended2023D4  -n 200 --customise Validation/Performance/TimeMemoryInfo.py  --filein file:step2.root  --fileout file:step3.root
```

The test results show no significant differences and no change in event content (in collections or total size). CPU time for this PU 200 test shows dramatic improvement:
```
  delta/mean delta/orJob     original                   new       module name
  ---------- ------------     --------                  ----       ------------
   -1.996503     -64.67%     72988.70 ms/ev ->        63.86 ms/ev recoTauAK4PFJets08RegionBoosted
   -1.842428      -2.34%      2757.17 ms/ev ->       113.07 ms/ev boostedTauSeeds
  ---------- ------------     --------                  ----       ------------
Job total:  112.772 s/ev ==> 41.1593 s/ev
```

**Comment by slava77** [comment]
On 12/19/16 12:17 PM, Carl Vuosalo wrote:
> +1
> 
> For #17040 <https://github.com/cms-sw/cmssw/pull/17040> ca0699a
> <https://github.com/cms-sw/cmssw/commit/ca0699a8b2c15fc5b08a1ba76e1d619f7ee15822>
> 
> Speeding up TauJetRegionProducer by caching a jet-to-PF-candidate map to
> avoid unnecessary, repetitive searches. There should be no change in
> monitored quantities.

For the monitored values: were you able to check with
the latest version of cms-reco-tools ?
I have updated it on Dec 16
https://github.com/slava77/cms-reco-tools/pull/107

**Comment by cvuosalo** [comment]
@slava77: I ran the check today with the latest version of validate.C:
```
commit 8b126d038ede35ecaa5540c6f49f6544dfd9501b
Author: Slava Krutelyov <slava77@cern.ch>
Date:   Fri Dec 16 22:31:00 2016 +0100

    fix plotting for ref with a different process name; add boosted taus (miniaod only)
```
My copy of  cms-reco-tools should be up-to-date.

**Comment by lgray** [comment]
@cvuosalo If possible could you post an igprof with the PR?

**Comment by lgray** [comment]
@cvuosalo I found another factor or 8 or so in the BoostedTauSeedsProducer, do you want me to commit that here and we resign or should I open another PR after this one is merged?

**Comment by cvuosalo** [comment]
@lgray: I suggest a new PR. This one is ready for merging. Also, I'm leaving as Reco convener, so a new PR would be simpler for Slava to start on. But please mention the similarity to this PR in the description of the new PR.

**Comment by cvuosalo** [comment]
@lgray: Here are the igprof results for the PU 200 test.

Baseline: http://cvuosalo.web.cern.ch/cvuosalo/cgi-bin/igprof-navigator/pr17040base

PR: http://cvuosalo.web.cern.ch/cvuosalo/cgi-bin/igprof-navigator/pr17040

**Comment by davidlange6** [comment]
+1

**Pull request merged**
