### PR TITLE
[94X]  Few fixes and additions to SiStrip PI plugins  (backport of #20946)

### PR DESCRIPTION
**Pull request by mmusich**
backport of #20946 

Post-merge follow-up to https://github.com/cms-sw/cmssw/pull/20643. 

Fixed:
   * bug in the filling of the `SiBadStrips` comparison plot due to not identical `detIds` list size for first and last IOV.

Added: 
   * 1D plot of payload dump values for `SiStripLorentzAngle` and `SiStripBackplaneCorrection`
   * Bad Strips Quality Statistics analysis breakout plot.

### CODE REVIEW

**Comment by mmusich** [comment]
type bug-fix

**Comment by ggovi** [comment]
please test

**Comment by ggovi** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
