### PR TITLE
Remove obsolete files in the HLT SUSY Validation package

### PR DESCRIPTION
**Pull request by jruizvar**
The HLT SUSY validation code changed back in 2014. The last validation with the old code was 720pre5, and after that the HLT SUSY Validation moved to a new DQM code (#5693).

Deleting the unused files is part of the maintenance of the current package.

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
thanks @jruizvar for the cleaning. could you please submit the same PR to 81x as well?
thanks,
F.

**Comment by jruizvar** [comment]
@deguio the forward port has been requested: #13563

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
