### PR TITLE
SiPixelQuality : fix tagging of the stuckTBM channels

### PR DESCRIPTION
**Pull request by tocheng**
Backport of #23267 to CMSSW_10_1_X

### CODE REVIEW

**Comment by tocheng** [comment]
Hello, @tvami, @tsusa, @veszpv, this is something you want to follow.

**Comment by lpernie** [comment]
please test

**Comment by prebello** [comment]
please test workflow 136.8391, 1040.1, 1001.2, 1040

**Comment by prebello** [comment]
please test workflow 136.8391, 1040.1, 1001.2, 1040

**Comment by lpernie** [comment]
+1

**Comment by fabiocos** [comment]
@tocheng @lpernie as far as I can see this PR is not tested in RelVals, as it refers to PCL run in Express, am I correct? Can you confirm it? 
BTW, it might be useful to update the tests in the test area to 2018, anyway the step3 adapted to 2018 works, while the step4 complains, which GT should be used? How was this practically validated?

**Comment by tocheng** [comment]
@fabiocos 
Yes, it is refers to PCL run in Express.
Step 4 complains because step4 uses 100X Express GT 
https://github.com/cms-sw/cmssw/blob/CMSSW_10_1_X/Configuration/PyReleaseValidation/python/relval_steps.py#L1543
Latest GT 101X_dataRun2_Express_v7 should be fine to remove the complaints.
https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_dataRun2_Express_v7

We currently validate the payloads manually. We compare the bad components in the payloads and compare with the pixel map and FED error plots in the offline DQM GUI to make sure the payloads make sense. 

If the PR leads to changes in harvester (step4), we run the harvester manually using the latest Express GT.
If the PR leads to changes in ALCARECO, we run the production of ALCARECO and harvester manually and compare payloads with the ones before the changes.

**Comment by lpernie** [comment]
@fabiocos something else is needed here?

**Comment by fabiocos** [comment]
+operations

**Comment by fabiocos** [comment]
+1

**Pull request merged**
