### PR TITLE
Run2-alca121 Take care of HLT codes for IsoTrackHB/HE in view of increased noise level in EE

### PR DESCRIPTION
**Pull request by bsunanda**
Thresholds are separately handed for EB and EE (also use eta dependent threshold for EE)

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by Martin-Grunewald** [comment]
It seems ```IsolatedEcalPixelTrackCandidateProducer``` is missing a ```fillDescriptions``` method which would take care of the new parameters not yet present in the HLT configuration (and the old parameters should be set as deprecated in there).

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@Martin-Grunewald I have added the fill description method and changed the HLT..cff(cfg) by hand. Hope this can be accepted. I shall later add fillDescription to the other producers in the package.

**Comment by davidlange6** [comment]
please test

**Comment by Martin-Grunewald** [comment]
-1
no direct modification of the HLT dumps. Instead, use (and call) a customisation function in customizeHLTforCMSSW in HLTrigger/Configuration/python

**Comment by davidlange6** [comment]
please test

**Comment by bsunanda** [comment]
@Martin-Grunewald sorry for my poor knowledge in customization - I replaced the entire block in customization function. I believe it works. But need a better customization from the experts in future. We do need this new version of the code to be used online at the earliest.

**Comment by Martin-Grunewald** [comment]
@bsunanda 
Please remove the changes in the files in  HLTrigger/Configuration/test/ - they are covered by the customisation function as well.
The customisation is just to get the PR in; once we move to 10_1_X with HLT, the changes will be put in the menus directly in ConfDB, and we'll redo the menu dumps as usual from ConfDB and remove the customisation code.

**Comment by bsunanda** [comment]
@Martin-Grunewald I shall do that. Hope this won't make the unit test to fail

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by bsunanda** [comment]
@lpernie @arunhep Please approve this. It is needed for updating HLT - once it is integrated we can go for making the changes in HLT menu

**Comment by Martin-Grunewald** [comment]
@bsunanda 
Please fix a merge conflict (arose due to integration of #22636 also modifying the customize file).

**Comment by bsunanda** [comment]
@Martin-Grunewald I wish that PR was integrated in the previous IB. I do not have an IB yet with that PR as yet

**Comment by davidlange6** [comment]
Your PR is unmergeable. Please have a look and possibly rebase it.

**Comment by Martin-Grunewald** [comment]
@bsunanda 
CMSSW_10_1_X_2018-03-19-2300 could be used.

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@Martin-Grunewald @lpernie @arunhep Can you approve this PR?

**Comment by Martin-Grunewald** [comment]
+1

**Comment by bsunanda** [comment]
@lpernie @arunhep @ghellwig This PR is needed for the HLT menu of 10_1_0. Could you please approve this?

**Comment by bsunanda** [comment]
@lpernie Could you please approve this as well?

**Comment by lpernie** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
