### PR TITLE
cleanup PhysicsTools/PatUtils data files

### PR DESCRIPTION
**Pull request by smuzaffar**
The data files for PhysicsTools/PatUtils are also part of cms-data/PhysicsTools-PatUtils reposiotry. These deleted files are identical as the one available in https://github.com/cms-data/PhysicsTools-PatUtils. 

Once merged we need a full IB to avoid picking up data files from CMSSW/poison directory

### CODE REVIEW

**Comment by smuzaffar** [comment]
test parameters:
- disable_poison = true

**Comment by smuzaffar** [comment]
please test

**Comment by slava77** [comment]
+reconstruction

for https://github.com/cms-sw/cmssw/pull/33310	48074da
- technical; the files should have been removed already in Dec of 2018 when https://github.com/cms-data/PhysicsTools-PatUtils was setup

**Comment by qliphy** [comment]
+1

**Pull request merged**
