### PR TITLE
Phase2-hgx359E Make a few bug fixes before proceeding with V19 version

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Make a few bug fixes before proceeding with V19 version

#### PR validation:

Use the modified code to extract the complete XML file information for the V19 version

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
+geometry

**Comment by srimanob** [comment]
+Upgrade

**Comment by rappoccio** [comment]
+1

**Pull request merged**
