### PR TITLE
Add missing newlines in L1Trigger modules

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Add missing newlines at the end of the files under
```
L1Trigger/CSCTriggerPrimitives
L1Trigger/Configuration
L1Trigger/DemonstratorTools
L1Trigger/GlobalCaloTrigger
L1Trigger/GlobalTriggerAnalyzer
L1Trigger/L1CaloTrigger
L1Trigger/L1TCaloLayer1
L1Trigger/L1TCalorimeter
L1Trigger/L1THGCal
L1Trigger/L1TMuonEndCap
L1Trigger/L1TNtuples
L1Trigger/L1TZDC
L1Trigger/Phase2L1GT
L1Trigger/Phase2L1ParticleFlow
L1Trigger/RegionalCaloTrigger
L1Trigger/TextToDigi
L1Trigger/TrackFindingTracklet
L1Trigger/TrackTrigger
L1Trigger/TrackerDTC
L1Trigger/TrackerTFP
L1TriggerConfig/L1GtConfigProducers
L1TriggerScouting/Utilities
```
.

#### PR validation:

None.

### CODE REVIEW

**Comment by fwyzard** [comment]
please test

**Comment by smorovic** [comment]
+daq

**Comment by subirsarkar** [comment]
+Upgrade

**Comment by aloeliger** [comment]
+l1

- Technical PR

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
