### PR TITLE
bsunanda:Run2-alca71 Correct the IsoTrackkanalyzer and associated macros

### PR DESCRIPTION
**Pull request by bsunanda**
Correct mistakes in the tree maker and associate macros used in the IsoTrack Calibration code

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@mmusich please approve

**Comment by mmusich** [comment]
+1
for https://github.com/bsunanda/cmssw/commit/35b83b63ba92c98a8b557cb5dd2b8e4dcdf46524

**Comment by davidlange6** [comment]
+1

**Pull request merged**
