### PR TITLE
Btag-OfflineDQM-CHS-To_PUPPI

### PR DESCRIPTION
**Pull request by felix-phy**
#### PR description:
With this proposed change the Btag OfflineDQM configs have been changed to run with the PUPPI jet collection as input instead of CHS. 

#### PR validation:
```runTheMatrix.py -l 12834.0 -i all --ibeos``` runs successfully (TTbar dataset is used for validation) with the implemented changes.

### CODE REVIEW

**Comment by tjavaid** [comment]
please test

**Comment by felix-phy** [comment]
In the last commit, era modifiers are introduced such that CHS jets are used for eras (pp on PbPb, FS) for which no PUPPI collection is available. This should fix the failing workflows (tested on 135.4, 5.1, 312.0).

**Comment by mandrenguyen** [comment]
please test

**Comment by tjavaid** [comment]
@felix-phy ,  I believe [various changes](https://tinyurl.com/29rkfudz) observed in `WF 12834.7` are spurious. Could you please confirm whether [changes](https://tinyurl.com/24tf7eeh) e.g. in `WF 4.53` are expected while moving from CHS to PUPPI collection?

**Comment by mandrenguyen** [comment]
+1

**Comment by Dr15Jones** [comment]
This appears to be causing many RelVals to fail with

```
----- Begin Fatal Exception 22-Aug-2024 15:14:07 CEST-----------------------
An exception of category 'ProductNotFound' occurred while
   [0] Processing  Event run: 1 lumi: 1 event: 1 stream: 2
   [1] Running path 'validation_step'
   [2] Calling method for module BTagPerformanceAnalyzerMC/'bTagValidationNoall'
Exception Message:
Principal::getByToken: Found zero products matching all criteria
Looking for type: edm::AssociationVector<edm::RefToBaseProd<reco::Jet>,std::vector<float>,edm::RefToBase<reco::Jet>,unsigned int,edm::helper::AssociationIdenticalKeyReference>
Looking for module label: pfJetProbabilityBJetTagsPuppi
Looking for productInstanceName: 

   Additional Info:
      [a] If you wish to continue processing events after a ProductNotFound exception,
add "TryToContinue = cms.untracked.vstring('ProductNotFound')" to the "options" PSet in the configuration.

----- End Fatal Exception -------------------------------------------------
```

In particular 11.0, 158.1, 158.2, 158.3, 281.0, 301.0 1311.0

**Comment by mandrenguyen** [comment]
@felix-phy @cms-sw/btv-pog-l2 
Can you please acknowledge the message the following comment, and fix this issue ASAP?
https://github.com/cms-sw/cmssw/pull/45577#issuecomment-2304706322
Relvals are crashing.

**Comment by nurfikri89** [comment]
@mandrenguyen I will take a look at this. I think @felix-phy is away.

**Comment by nurfikri89** [comment]
> @felix-phy @cms-sw/btv-pog-l2 Can you please acknowledge the message in the following comment, and fix this issue ASAP? [#45577 (comment)](https://github.com/cms-sw/cmssw/pull/45577#issuecomment-2304706322) Relvals are crashing.

@mandrenguyen @Dr15Jones PR #45794 should fix the failing RelVals.

**Comment by mandrenguyen** [comment]
@nurfikri89 Thank you for treating this urgently on the weekend.  It's really appreciated.

**Pull request merged**
