### PR TITLE
BPH DQM for 92X

### PR DESCRIPTION
**Pull request by anigamova**

### CODE REVIEW

**Comment by mtosi** [comment]
@cmsbuild, please test

**Comment by mtosi** [comment]
tracked by https://github.com/cms-sw/cmssw/issues/19142

**Comment by dmitrijus** [comment]
+1

**Comment by mtosi** [comment]
@cmsbuild, please test

**Comment by dmitrijus** [comment]
+1

**Comment by fwyzard** [comment]
Hi,
given the amount of stuff that needs to be backported, I plan to do it in a single PR as soon as the DQM for the HLT menu v2.1 is fully integrated in 9.3.x.
If the 9.3.x equivalent of this PR has already been merged, or is listed as "Open" at #19412, can you close this PR ?

**Comment by fwyzard** [comment]
hold

**Comment by fwyzard** [comment]
please merge #19961 before merging any other HLT DQM PR on 9.2.x, and then rebase them

**Pull request closed without merging**
