### PR TITLE
Phase2-gex168 Modify all Phase2 scenarios after fixing the HCAL SD issue

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Modify all Phase2 scenarios after fixing the HCAL Sensitive Detector (SD) issue. The dd4hep was using some additional SDs which need not be in the list producing hits in HCAL. This was corrected in https://github.com/cms-sw/cmssw/pull/42463 and these corrections are incorporated in this list. If this causes a serious impact on the simulation, it clearly indicates that this PR needs to be back ported to 13_2_X, 13_1_X, 13_0_X

#### PR validation:

Use the runTheMatrix test workflows

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport will be decided later

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
+geometry

**Comment by bsunanda** [comment]
@srimanob Please approve this

**Comment by srimanob** [comment]
+Upgrade

Change is seen in Phase-2 workflows as expected.

**Comment by perrotta** [comment]
+1
- Validation with CMSSW_13_3_0_pre2 is expected

**Pull request merged**
