### PR TITLE
Added missing esConsumes to DTTrackFinder

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

- Added esConsumes to helpers
- Removed an unnecessary base class (which was actually the same name as a class in another package)
- Simplified memory management in L1MuDTSectorProcessor

#### PR validation:

Code compiles. The changes are not meant to change any behavior.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
Please test

**Comment by Dr15Jones** [comment]
I fixed the merge conflicts

**Comment by Dr15Jones** [comment]
please test

**Comment by qliphy** [comment]
please test
test again with new IB

**Comment by Dr15Jones** [comment]
ping @cms-sw/l1-l2

**Comment by Dr15Jones** [comment]
ping @cms-sw/l1-l2

**Comment by qliphy** [comment]
please test
test again with new IB before merging (bypassing L1 if needed)

**Comment by qliphy** [comment]
merge

**Pull request merged**
