### PR TITLE
[CORE] Cleanup USE_UNITTEST_DIR which is now enabled at project level

### PR DESCRIPTION
**Pull request by smuzaffar**
This flag is not needed any more at package/BuildFile.xml level as it has been enabled at project level

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by makortel** [comment]
Another incarnation of #39803

**Comment by makortel** [comment]
+core

Unit tests succeeded

**Comment by makortel** [comment]
The RelVal-INPUT failures come from (re-)HLT step of 2021 and 2022 data workflows. The node happened(?) to have a GPU (T4), and the jobs ran out of memory (which is not surprising given the number of concurrent jobs).

**Comment by perrotta** [comment]
+1

**Pull request merged**
