### PR TITLE
[NanoAOD] Add ParticleNet-based Muon ID

### PR DESCRIPTION
**Pull request by jlidrych**
#### PR description:

This PR adds ParticleNet-based Muon ID for NanoAODv15.
The feature was discussed during Muon POG meeting [(23/09/2024)](https://indico.cern.ch/event/1457874/) and it will be discussed during XPOG meeting [(2/10/2024)](https://indico.cern.ch/event/1462345/)

#### PR validation:
I've performed a local running test to see that the mva is loaded and nanoAOD is in fact produced.

### CODE REVIEW

**Comment by hqucms** [comment]
@jlidrych Can you link the cms-data PR with the model files?

Regarding the implementation, I think it would be better to run the producer at the `PAT` step and store the scores in MiniAOD already, where NANO just reads the value directly. Could you please do that?

**Comment by jfernan2** [comment]
enable nano

**Comment by jlidrych** [comment]
Here is the link to cms-data PR.
https://github.com/cms-data/PhysicsTools-NanoAOD/pull/17

At this stage of the development, we would strongly prefer a nanoAOD implementation. The nanoAOD implementation offers more flexibility. For example, if a new training is required in the future, re-Mini will not be necessary; only re-Nano will be needed. We can discuss this at the  X-POG meeting.

**Comment by hqucms** [comment]
test parameters:
 - pull_requests = https://github.com/cms-data/PhysicsTools-NanoAOD/pull/17
 - enable = nano

**Comment by hqucms** [comment]
please test

**Comment by hqucms** [comment]
> Here is the link to cms-data PR. [cms-data/PhysicsTools-NanoAOD#17](https://github.com/cms-data/PhysicsTools-NanoAOD/pull/17)
> 
> At this stage of the development, we would strongly prefer a nanoAOD implementation. The nanoAOD implementation offers more flexibility. For example, if a new training is required in the future, re-Mini will not be necessary; only re-Nano will be needed. We can discuss this at the X-POG meeting.

@jlidrych Having the producer implemented in the PAT step does not prevent it to be re-run in the NANO step if needed -- all the ML jet taggers are implemented in that way.

**Comment by hqucms** [comment]
please test

**Comment by hqucms** [comment]
please test

**Comment by hqucms** [comment]
@jlidrych I reworked this PR in https://github.com/cms-sw/cmssw/pull/46273. Let's continue the discussion there.

**Comment by hqucms** [comment]
please close

Superseded by https://github.com/cms-sw/cmssw/pull/46273.

**Pull request closed without merging**
