### PR TITLE
Run3-hcx299 Update HF showering code (from Lev)

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Update HF showering code (from Lev and checked by Salavat )

#### PR validation:

Use the runTheMatrix test workflows 

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
@bsunanda , HFShowerLibrary files are again broken after transmission via e-mail - it is needed to recover this files. Probably it is not a good idea to send files via e-mail, better to use afs.

**Comment by abdoulline** [comment]
@bsunanda  probably it's worth wthdrawing this PR until proper files are available?  
Actually these updates are supposed to be inactive wrt any MC at the moment...

**Comment by bsunanda** [comment]
@abdoulline @civanch Closing this PR in view of future files from Lev. I shall make some changes on top of the files I shall receive which I have also done for this PR

**Comment by bsunanda** [comment]
Closing this PR till we get new files from Lev which will not change the current workflows

**Comment by abdoulline** [comment]
> Closing this PR till we get new files from Lev which will not change the current workflows

@bsunanda  I'm afraid it's beyond what Lev could do... 
Hist attempt to use OnlyLong parameter (which is True by default) for handling an additional option (aligning different signal  propagation time in different fibers)  time was apparently a mistake...

**Pull request closed without merging**
