### PR TITLE
Pixel tracking2017 for online bs master

### PR DESCRIPTION
**Pull request by rovere**
This PR will update pixel Tracking and Vertexing for Online DQM Beamspot applications.
IT INCLUDES ALSO #18816 
See also #18918

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by perrotta** [comment]
please test

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cmsbuild please test

looks like some xrootd problems

**Comment by rovere** [comment]
I'm not what is happening with this PR...?

**Comment by perrotta** [comment]
Conflicts arisen since the merging of #18816 must be solved.
Then tests can be rerun, to get rid of unrelated errors

**Comment by smuzaffar** [comment]
looks like there is some issue with CMS EOS due to which IBs and PR tests are not able to access EOSCMS files. We have opened a ticket to understand the issue

**Comment by slava77** [comment]
it looks like the plan for updates here will include some other feature changes (like migration of phase-2 from pixelTracks). 
So, this may take a while to integrate (I was hoping for a technical update instead).

In case we have to move to a 921 release (for whatever reason unrelated to this PR), I think it's more appropriate to merge this PR in its original form (after the conflict resolution).
Please update this.

**Comment by dmitrijus** [comment]
@rovere Please close this PR (we still will be able to merge it online!)

**Comment by slava77** [comment]
OK to close if it doesn't seem to matter for DQM, I'm not sure then why we needed an urgent 920patch3 with an equivalent of this one.

**Pull request closed without merging**
