### PR TITLE
TagInfo collection name update

### PR DESCRIPTION
**Pull request by ferencek**
PAT jets store TagInfo names by stripping everything starting from 'TagInfos'. Hence, internally it is not possible to distinguish `pfImpactParameterTagInfosAK8` from `pfImpactParameterTagInfos`. So to avoid possible ambiguities, TagInfo collection names need to end with 'TagInfos'.

This PR does not change MiniAOD in 76X and it also does not have any impact on reading older 76X MiniAOD files.

Backport of a single commit from #13685.

### CODE REVIEW

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
+1

For #13700 056c7dbcfa73ed01d7ee36e7837a0275653e71ba

Renaming TagInfos collections to avoid confusion.

The code changes are satisfactory, and Jenkins tests against baseline CMSSW_7_6_X_2016-03-08-2300 show no significant differences. An extended test of workflow 25202.0_TTbar_13 with 70 events against baseline CMSSW_7_6_4 also shows no significant differences, no change in RECO or Mini-AOD event content, and no significant change in CPU time or memory usage. The renaming's only effect is that two modules run with new names but take the same amount of CPU time:

```
  delta/mean delta/orJob     original                   new       module name
  ---------- ------------     --------                  ----       ------------
     removed      -0.00%         0.34 ms/ev ->         0.00 ms/ev pfInclusiveSecondaryVertexFinderTagInfosAK8AK8
       added      +0.00%         0.00 ms/ev ->         0.33 ms/ev pfInclusiveSecondaryVertexFinderAK8TagInfosAK8
     removed      -0.00%         2.10 ms/ev ->         0.00 ms/ev pfImpactParameterTagInfosAK8AK8
       added      +0.00%         0.00 ms/ev ->         2.11 ms/ev pfImpactParameterAK8TagInfosAK8
```

**Comment by slava77** [comment]
```
       added      +0.00%         0.00 ms/ev ->         0.33 ms/ev pfInclusiveSecondaryVertexFinderAK8TagInfosAK8
```
This is strange. I thought the goal was to have "TagInfos" at the end of the name. Did the addJetCollection postfix add it anyways
@ferencek please clarify

**Comment by ferencek** [comment]
@slava77, yes, `addJetCollection` adds a user-defined label (in the above case `AK8`) at the end of the module name. However, what matters for adding TagInfos to PAT jets is the string up to "TagInfos" (see https://github.com/cms-sw/cmssw/blob/CMSSW_7_6_4/DataFormats/PatCandidates/src/Jet.cc#L406-L416). So to be able to distinguish `pfImpactParameterTagInfosAK8` from `pfImpactParameterTagInfos` among the added TagInfos, it is necessary to move `AK8` in front of `TagInfos`. Additional `AK8`, which could be any other string, at the end of the name in the above example is not relevant and will be dropped from the internally stored TagInfo name.

**Pull request merged**
