### PR TITLE
CTPPS: updated DQM for 2018 data taking

### PR DESCRIPTION
**Pull request by dfigueiredo**
This PR updates the DQM:

- Includes new CTPPS Roman Pot (RP) state (with [CTPPSRecord](https://github.com/cms-sw/cmssw/blob/master/DataFormats/OnlineMetaData/interface/CTPPSRecord.h) collection) in function of LS. Each state corresponds to a combination of (HV & LV & position for physics).

- States are 0 (not used), 1 (bad), 2 (warning) and 3 (ok).

A test python is available at [DQM/CTPPS/test/timing_dqm_test_cfg.py](https://github.com/CTPPS/cmssw/blob/368a273e134089c78cf2ef64e6c500bde16f710d/DQM/CTPPS/test/timing_dqm_test_cfg.py)

@nminafra @fabferro @forthommel

### CODE REVIEW

**Comment by jfernan2** [comment]
Hola @dfigueiredo can you please introduce yourself? We don't have you identified as CTPPS DQM developer in:
https://twiki.cern.ch/twiki/bin/viewauth/CMS/DQMContacts#CT_PPS
Thanks

**Comment by forthommel** [comment]
@jfernan2 Interesting collection! let us know where we can introduce ourselves for any later developments :)

**Comment by jfernan2** [comment]
@forthommel just add/remove anybody from the corresponding e-group including your git username so that we cna keep track of who to contact
Thanks

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
@dfigueiredo No robot for the moment, but I wish I could have one replacing me and still get my income...

**Comment by dmitrijus** [comment]
+1

**Comment by fabiocos** [comment]
please test

**Pull request merged**
