### PR TITLE
Added TritonService to exception messages

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

Also LogError output of execSys command in case of failure.

Looking at failures in the IB RelVals it was hard to know the exceptions were coming from the TritonService.

#### PR validation:

Code compiles.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by kpedro88** [comment]
thanks @Dr15Jones - I had written these messages like they were coming from a module (where the module name is output by default), forgetting that's not the case for services

**Comment by makortel** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
