### PR TITLE
 Backport of UL scales and smearings to 106X 

### PR DESCRIPTION
**Pull request by jainshilpi**
This is essentially a backport of https://github.com/cms-sw/cmssw/pull/29526
to 106X. 

Just to mention the changes again:

(1) EnergyScaleCorrection.cc/h
(2) calibratedEgammas_cff.py

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by perrotta** [comment]
backport of #29526

**Comment by slava77** [comment]
@cmsbuild please test

to refresh the tests

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/30199	575f240
- the backport is consistent with the final state of files in #29526 
    - RecoEgamma/EgammaTools/interface/EnergyScaleCorrection.h and EnergyScaleCorrection.cc files are the same as in the master branch and include code-checks in addition with changes from #29526 proper
    - RecoEgamma/EgammaTools/python/calibratedEgammas_cff.py is updated minimally to pick up the new training for ```run2_miniAOD_devel```
- jenkins tests pass and comparisons with the baseline show no (relevant) differences

**Comment by silviodonato** [comment]
+1

**Pull request merged**
