### PR TITLE
Complete run3 muon validation and new setup for phase2 validations

### PR DESCRIPTION
**Pull request by cedricpri**
Going back to the complete muon validation scheme for the run3, and added a new option to consider the energy to be able to perform 13TeV vs 14TeV validations.

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
@cedricpri  this PR is replacing some histograms by others but only in some (5) workflows, can you please check if this behaviour is expected?
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_11_0_X_2019-05-23-2300+4bdab1/31887/dqm-histo-comparison-summary.html

**Comment by cedricpri** [comment]
This is indeed expected, thanks for checking.

**Comment by jfernan2** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
