### PR TITLE
L1T DQM timing plot upgrades part2

### PR DESCRIPTION
**Pull request by thomreis**
Split the uGT DQM module in one that handles the standard DQM plots and another one for the timing plots.
This way the timing plot module can run also in the offline DQM while the other module does not run because of the large 2D histograms.

Also moves the calo L2 output to uGT input comparison configuration to the uGT configuration.

### CODE REVIEW

**Comment by thomreis** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
+1

**Pull request merged**
