### PR TITLE
Fastsim 75X: fix truth matching for recoTracks from PU events

### PR DESCRIPTION
**Pull request by lveldere**
required to validation digi-reco PU mixing

### CODE REVIEW

**Comment by lveldere** [comment]
please test

**Comment by lveldere** [comment]
-1

FullSim test succeed, but the original issue with  FastSim is only partially fixed

**Comment by slava77** [comment]
Lukas, please clarify if the "-1" in https://github.com/cms-sw/cmssw/pull/8654#issuecomment-90584683 is still applicable.
Tests succeeded here somehow (but not in 74X #8653 )

**Comment by lveldere** [comment]
please test

**Comment by lveldere** [comment]
@slava77 

Next time I'll close when I want people to avoid reviewing.
I expect things to work properly now.
I'll fix the 74X pr after lunch.

**Comment by cvuosalo** [comment]
+1

For #8654 baa69f4e8da0d31c5b6309ba5a1c74d926d67124

Fixing truth matching for PU tracks. Correcting MC truth values would not be expected to alter reco quantities.

The code changes are satisfactory, and Jenkins [tests](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-8654/4145/summary.html) against baseline CMSSW_7_5_X_2015-04-08-2300 show no significant differences. The test for workflow 4.53_RunPhoton2012B erroneously shows differences in most  quantities, but these results are due to some problem unrelated to this PR.

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
