### PR TITLE
Add new modules for GEM offline DQM

### PR DESCRIPTION
**Pull request by seungjin-yang**
#### PR description:
GEMOfflineMonitor checks the attributes of GEM-related objects like digi and rechit excluding what online DQM do. Segment part is planned to be updated after GEM/ME0 merging.
GEMEfficiencyAnalyzer and GEMEfficiiencyHarvester measure GEM efficiency and resolution using both tight global muons and standalone muons.

#### PR validation:
This PR was tested with workflow 11611.0 and 27411.0.
Plots can be found in he following two links.
https://indico.cern.ch/event/927191/contributions/3898232/attachments/2053764/3443071/Talk_GEM_DPG_200609_Offline_DQM.pdf
https://indico.cern.ch/event/931844/contributions/3916126/attachments/2062310/3459906/GEM_DPG_200623_Offline_DQM.pdf

@jshlee @watson-ij

### CODE REVIEW

**Comment by seungjin-yang** [comment]
New commits remove a deprecated gemEfficiencyHarvesterLoose from gemEfficiencyHarvesterSeq and unnecessary comments.

**Comment by seungjin-yang** [comment]
@szaleski

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+1
Plots have very low (6 ) or null entries in the tested workflows but seem ok

**Comment by silviodonato** [comment]
+1

**Comment by davidlange6** [comment]
looks like this created problems in the IB - should it be reverted before 1100?

**Pull request merged**
