### PR TITLE
Access to X and Y Offsets

### PR DESCRIPTION
**Pull request by ianna**
* Allow access to x and y offsets calculated in a constructor
* Needed for an event display to minimize amount of data stored in a reco geometry file

### CODE REVIEW

**Comment by ianna** [comment]
@alja - FYI

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by alja** [comment]
@ianna Thanks!

**Comment by davidlange6** [comment]
hi @ianna - please update the title to reflect what class/area is affected for the release notes. Thanks

**Comment by alja** [comment]
The title could be:
Add getter for offsets in RectangularPixelTopology. 

I need that change for visualization of pixel clusters and hits.

**Comment by alja** [comment]
@ianna 
Is it safe to presume FWRecoGeometryProducer will have only RectangularPixelTopology and not ProxyPixelTopology ?

**Comment by ianna** [comment]
@alja - I think, yes.

**Comment by alja** [comment]
@ianna 
I run first test and got a lot of prints like cast to RectangularPixelTopology is not valid:
https://github.com/alja/cmssw/blob/phase2_test/Fireworks/Geometry/src/FWRecoGeometryESProducer.cc#L49

I used tag 2023D4 in CMSSW_9_0_0_pre2.

**Comment by ianna** [comment]
@alja - you are right, Phase 2 blades are defined as Trapezoids.

**Comment by alja** [comment]
@ ianna
how do i get local xy coordinates in this case ?

**Comment by ianna** [comment]
@alja - sensitive volumes are still boxes. http://cmslxr.fnal.gov/source/RecoLocalTracker/Phase2TrackerRecHits/src/Phase2StripCPEGeometric.cc#0022

**Comment by alja** [comment]
@ianna 

I found out I can get offsets like https://github.com/alja/cmssw/blob/a50cbdfd8f0f7df5787a93336f0d1e7d718790cc/Fireworks/Geometry/src/FWRecoGeometryESProducer.cc#L34

Is that OK?
If so, than the PR is no longer needed.

**Comment by ianna** [comment]
@alja - yes, it looks fine to me.

**Pull request closed without merging**
