### PR TITLE
Phase2-hcx229 Modify a few scenarios for location of CaloUtil.xml file

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

There are 2 versions of CaloUtil.xml depending on the version of caloBase.xml file used. These are now correctly put in the phase2 scenario.

#### PR validation:

Use standard tests with runTheMatrix.py

#### if this PR is a backport please specify the original PR:

Nothing special

### CODE REVIEW

**Comment by fabiocos** [comment]
please test

**Comment by kpedro88** [comment]
+upgrade

**Comment by cvuosalo** [comment]
+1

**Comment by fabiocos** [comment]
@bsunanda the two versions of CaloUtil.xml differ:
```
09:28 cmsdev25 7338> diff -b $CMSSW_RELEASE_BASE/src/Geometry/HcalSimData/data/CaloUtil.xml $CMSSW_RELEASE_BASE/src/Geometry/HGCalSimData/data/CaloUtil.xml
74c74
<    <Parameter name="FineLevels" value="8" eval="true"/>
---
>    <Parameter name="FineLevels" value="4" eval="true"/>
```
What is the expected impact of this difference on the update of scenarios already used for production (I mean D35)? No effect is seen in the limited PR test, but is this enough?

**Comment by fabiocos** [comment]
+1

**Pull request merged**
