### PR TITLE
FastSim LL particles backport  from 11_2X to 94X

### PR DESCRIPTION
**Pull request by sbein**
#### PR description:

This is a backport PR for 31285

#### PR validation:

The backport is needed to support the physics needs of an upcoming SUSY pMSSM simulation, since this scan contains LL particles.  
https://github.com/cms-sw/cmssw/pull/31285

### CODE REVIEW

**Comment by kpedro88** [comment]
-1
please carefully follow the instructions in http://cms-sw.github.io/tutorial-resolve-conflicts.html#backporting-a-pr

**Comment by sbein** [comment]
Yes, I will need to retry this. I followed the backporting rebasing procedure, but the git merge conflict files seemed to show information incompatible with the commits it was attempting to merge. For example, there were errors in the "HEAD" code, which, if accepted, would not allow a successful compilation. To try to right this, I copied the files directly from HEAD after doing "git rebase --skip" several times, and added and committed the 3 modified files. However, now I see it seems this PR wants to modify dozens of packages, so something went wrong. Will try again using the commands like in @kpedro88's example.

**Comment by slava77** [comment]
-1
wrong branch, according to the PR title

**Comment by Martin-Grunewald** [comment]
-1

**Pull request closed without merging**
