### PR TITLE
bsunanda:Run2-alca64 Allow to define dummy parameters for non-SiPM cells

### PR DESCRIPTION
**Pull request by bsunanda**
Correct HCAL hardcode loader for SiPM parameters

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by kpedro88** [comment]
@mmusich @davidlange6 please review/sign/merge quickly, this is vital for HCAL 2017 conditions

**Comment by kpedro88** [comment]
@mmusich please review quickly, minor change but necessary before we can submit an HCAL 2017 global tag

**Comment by mmusich** [comment]
+1

**Comment by kpedro88** [comment]
@davidlange6 can this be merged today?

**Pull request merged**
