### PR TITLE
Update beginning and end of life noise values for BH

### PR DESCRIPTION
**Pull request by lgray**
New expectations for BH noises values for TDR.
Add end of life configuration for BH (soon to add a new era for this for easy config).

### CODE REVIEW

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by kpedro88** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
hi @lgray - could you add a small comment in the cfi to document the source of the new numbers. Thanks

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by civanch** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
