### PR TITLE
Path renaming and some updates for TOP and BTV

### PR DESCRIPTION
**Pull request by marinakolosova**
- Renamed fully hadronic paths BTagCSV, DoubleBTagCSV, TripleBTagCSV and DeepCSV as in https://its.cern.ch/jira/browse/CMSHLT-1463.
- Added jetEtaBinning for PFJetFwd paths.
- Some updates on the selection/binning of the fully hadronic paths.
- Fixed a histo label in TopMonitor.cc

### CODE REVIEW

**Comment by heppye** [comment]
Needed for V2 menu, may STEAM, DQM, STORM please provide a quick comment. Thanks, Ye (for BTV@HLT)

**Comment by dmitrijus** [comment]
+1

**Comment by heppye** [comment]
@dqm, could u please start the test again? Thanks.

**Comment by dmitrijus** [comment]
I can't. The conflicts need to be fixed.

**Comment by heppye** [comment]
@DQM, could u please explain in a little details and point out where we should improve? cmsbuild test seems fine. Thanks for your time, Ye (for BTV@HLT)

**Comment by defranchis** [comment]
@mtosi @dmitrijus can we please test?

**Comment by heppye** [comment]
@marinakolosova , could u please confirm again your local branch is up to data?

**Comment by defranchis** [comment]
@mtosi @davidlange6 @fwyzard can we please test?

**Comment by mtosi** [comment]
@cmsbuild, please test

**Comment by defranchis** [comment]
@dmitrijus can you please check and sign?

**Comment by dmitrijus** [comment]
+1

**Comment by defranchis** [comment]
@davidlange6 can you please check (and sign if everything is OK)?

**Comment by fwyzard** [comment]
tracked by #19142

**Comment by fwyzard** [comment]
I have merged this in #19916.
Please DO NOT TOUCH this PR/branch, and leave it open.

**Pull request merged**
