### PR TITLE
[101X][L1T][DQMOffline] Upgrading L1TEGammaOffline (CMSLITDPG-585)

### PR DESCRIPTION
**Pull request by kreczko**
## WARNING
This PR depends on #23494 and should not be merged before it.
After #23494 is merged, this one will probably need a rebase.

## Summary
Backport of #23515

### CODE REVIEW

**Comment by thomreis** [comment]
please test

**Comment by thomreis** [comment]
+1

**Comment by davidlange6** [comment]
Your PR is unmergeable. Please have a look and possibly rebase it.

**Comment by dmitrijus** [comment]
+1

**Comment by thomreis** [comment]
+1

**Pull request closed without merging**
