### PR TITLE
Fix radix sort test (12.0.x)

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Fix the compilation errors in HeterogeneousCore/CUDAUtilities/test/radixSort_t.cu:
  - take into account the actual size of the type being sorted, instead of always assuming a 64-bit type;
  - use an union instead of a cast to keep the compiler happy about the aliasing rules.

#### PR validation:

`gpuRadixSort_t` compiles and runs fine.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Backport of #34929.

### CODE REVIEW

**Comment by fwyzard** [comment]
type bugfix

**Comment by fwyzard** [comment]
backport #34929

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
+heterogeneous

**Comment by qliphy** [comment]
+1

**Pull request merged**
