### PR TITLE
Fix online744

### PR DESCRIPTION
**Pull request by deguio**
bunch of fixes still pending from the 72 --> 74 move
DQM online is affected

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1

**Comment by cvuosalo** [comment]
+1

For #9623 2efcbfdfc17ba5a258b803aacd3e6d87a5f43ea4

Forward port of online DQM fixes from 72X. Reco changes are limited to a changed comment.

Jenkins [tests](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-9623/8182/summary.html) against baseline CMSSW_7_4_X_2015-06-15-1100 show no significant differences, as expected.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
