### PR TITLE
IORawData/CSCCommissioning file reader fixes 

### PR DESCRIPTION
**Pull request by barvic**
#### PR description:
IORawData/CSCCommissioning fixes
- File reader crash fix. Fixed typo for FileReaderDCC, which was causing this tool crashes
- Changes for legacy CSCFileReader FirstReadBug to correct number of events in converted data files

### CODE REVIEW

**Comment by smorovic** [comment]
please test

**Comment by dildick** [comment]
@barvic Can you also update https://github.com/cms-sw/cmssw/blob/master/IORawData/CSCCommissioning/test/readFile.py with for B904 data? For instance, in ```process.rawDataCollector``` we need this line instead ```FED846 = cms.untracked.vstring('RUI01'),```.

**Comment by dildick** [comment]
Thanks! Final question. Could also the input and output file be made configurable? That will help me to set up automated workflows for B904 data re-emulation.

**Comment by barvic** [comment]
@dildick This is general purpose CSC utility package with sample config files. Please feel free to add modified config files with changes for your particular tasks.

**Comment by smorovic** [comment]
please test

**Comment by smorovic** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
