### PR TITLE
fillDescriptions migration and parameter cleanup in DAQ modules (76X) 

### PR DESCRIPTION
**Pull request by smorovic**
Changes:
- Migrating production DAQ modules EvFDaqDirector, EvFOutputModule, FedRawDataInputSource and FastMonitoringService to using fillDescriptions. Removing cfi python files for those cases.
- Removing obsolete parameters from those modules
- Allow FastMonitoringService to find definition file in both CMSSW_BASE and CMSSW_RELEASE_BASE (those differ when running from project area).

Port of #12146 (75X)

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
+1

For #12147 38202045f0a6f7f982c1ab2c3832dc9e51eb18ce

fillDescriptions migration in DAQ modules. #12146 and #12148 are the 75X and 80X versions of this PR, and the former has already been approved by Reco.

The code changes are satisfactory, and Jenkins tests against baseline CMSSW_7_6_X_2015-10-30-1100 show no significant differences.

**Comment by mommsen** [comment]
+1

**Comment by davidlange6** [comment]
I am cleaning up the 76x queue aside from things for analysis workflows. I'm closing this pull request, please make sure the PR is in 80x. Thanks!

**Pull request closed without merging**
