### PR TITLE
give `OnlineLuminosityRecord` info to HLT's `LumiMonitor` plugin [`12_5_X`]

### PR DESCRIPTION
**Pull request by missirol**
backport of #39859

#### PR description:

From the description of #39859:

>This PR address the 2nd item in the description of #39756, plus a related comment in https://github.com/cms-sw/cmssw/issues/39756#issuecomment-1282752666.
>
>The `LumiMonitor` DQM plugin, used inside HLT, is updated to read the values of online instantaneous luminosity and mean PU from the so-called 'online-metadata' digis, when the corresponding info from SCAL is not available (i.e. from Run 3 onwards).
>
>To improve clarity, some of the plot labels, transient variables, and configuration parameters are renamed. I changed "scal lumi/PU" to a more generic "online lumi/PU", but of course feel free to suggest better names.
>
>Minor technical improvements (e.g. `const`-ness of class data members) were done in the process.
>
>(In case this is backported to `12_4_X`, it should not warrant a new `ConfDB` parsing, since the new configuration parameter of `LumiMonitor`, i.e. `onlineMetaDataDigis`, already defaults to the intended collection; at the same time, `hltOnlineMetaDataDigis` should in principle be included in the `DQMHistograms` EndPath in the HLT menus.)

3a1fd65c2497a05c43f401afe3af77bb9e36ddaf fixes a couple of pixel-related harvesting outputs which depend on the outputs of the `LumiMonitor` plugin; please see https://github.com/cms-sw/cmssw/pull/39859#issuecomment-1296284482 for details.

This is not an exact backport because of 3af98ee5f6c: the renaming of the parameter `LumiMonitor.FolderName (-> .folderName)`, done in #39859, is not backported to `12_5_X` in order to avoid extra complications to HLT online operations.

#### PR validation:

None beyond the validation done for #39859.

#### If this PR is a backport, please specify the original PR and why you need to backport that PR. If this PR will be backported, please specify to which release cycle the backport is meant for:

#39859

Fix for HLT online DQM.

### CODE REVIEW

**Comment by missirol** [comment]
please test

**Comment by missirol** [comment]
please test

I figured it's better not to backport the renaming of the `FolderName` parameter even to `12_5_X` (see https://github.com/cms-sw/cmssw/pull/39859#discussion_r1005798625, and https://github.com/cms-sw/cmssw/pull/39897#issuecomment-1295151001), to avoid the need for a ConfDB parsing of a future 12_5_X release in the midst of the Hion test run (the description of this PR has been updated accordingly).

**Comment by missirol** [comment]
please test

See https://github.com/cms-sw/cmssw/pull/39859#issuecomment-1296284482.

**Comment by missirol** [comment]
+hlt

**Comment by emanueleusai** [comment]
testing 12_4 backport at p5

**Comment by syuvivida** [comment]
+1

**Comment by perrotta** [comment]
+1
- "Almost" verbatim backport of the corresponding PR in the master, see https://github.com/cms-sw/cmssw/pull/39859#discussion_r1005798625: this was evaluated by HLT the safest way to propagate the changed parameters, and DQM approved

**Pull request merged**
