### PR TITLE
Migration of modules used in PbPb HLT to do ZeroSuppression to stream modules in 75X

### PR DESCRIPTION
**Pull request by kkrajczar**
Dear all,

We have realized that two modules used in the PbPb HLT ZeroSuppression sequence are still legacy ones:  RawDataCollectorByLabel and SiStripDigiToRawModule. I don't know how important the migration of these modules to streamer ones is. For any case, I have migrated the modules and verified that HLT runs and gives the same rates before and after the migration. Similar PRs will be made for 76X and 80X.

I am cc'ing TSG experts for comments.

@mandrenguyen @fwyzard @Martin-Grunewald 

Cheers,
Krisztian

### CODE REVIEW

**Comment by slava77** [comment]
@kkrajczar please suggest a realistic HLT setup to test the timing.
[This probably goes beyond just this PR]

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
We'd also need a PR for 76X and then hopefully the 76X PR will be autoported to 80X.

**Comment by kkrajczar** [comment]
Hi Slava,

A realistic way of testing this PR would be to re-run an HLT with ZeroSuppression on 2010 VirginRAW PbPb data. I have prepared a very-very basic HLT menu that performs ZS for this purpose. I tested it in 753p1 with the config given by the following re-L1+HLT command:

hltGetConfiguration /users/krajczar/ttbar/Testing/V1 --full --offline --data --unprescale --process TEST --globaltag auto:run1_data --l1-emulator 'stage1,gt' --l1Xml L1Menu_CollisionsHeavyIons2011_v0_nobsc_notau_centrality_q2_singletrack.v1.xml --output none --max-events 10 --input file:root://xrootd.unl.edu//store/user/abaty/2010VirginRaw_v2/HICorePhysics/VirginRAW_2010_HICorePhysics_SKIM_v2_Cent_0_5/150721_125934/0000/VirginRAW_2010_HICorePhysics_SKIM_v2_Cent_0_5_82.root > hlt_RUN_VR.py

You would need to edit hlt_RUN_VR.py by appending the 
process.load('L1Trigger.L1TCalorimeter.caloConfigStage1HI_cfi')
process.caloStage1Params.regionPUSType = cms.string("zeroWall")
lines.

The resulting config ran successfully, so the timing of the ZS with this PR and without it can be tested.

Of course, once the HIon menu for this year is available, that can be used (together with the matching L1 menu) instead of my pure ZS-test menu mentioned above.

Cheers,
Krisztian

**Comment by kkrajczar** [comment]
I realized that 753p1 might too old a release for testing, so I also provide below the instructions for 755p1:

Same hltGetConfiguration command as above, but with the V2 of the HLT menu:

hltGetConfiguration /users/krajczar/ttbar/Testing/V2 --full --offline --data --unprescale --process TEST --globaltag auto:run1_data --l1-emulator 'stage1,gt' --l1Xml L1Menu_CollisionsHeavyIons2011_v0_nobsc_notau_centrality_q2_singletrack.v1.xml --output none --max-events 10 --input file:root://xrootd.unl.edu//store/user/abaty/2010VirginRaw_v2/HICorePhysics/VirginRAW_2010_HICorePhysics_SKIM_v2_Cent_0_5/150721_125934/0000/VirginRAW_2010_HICorePhysics_SKIM_v2_Cent_0_5_82.root > hlt_RUN_VR.py

Add the following lines to the end of hlt_RUN_VR.py:
process.load('L1Trigger.L1TCalorimeter.caloConfigStage1HI_cfi')
process.load('L1Trigger.L1TCalorimeter.caloStage1Params_HI_cfi')

Cheers,
Krisztian

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/12415	 0232d99
- code changes are in line with the PR description; visual inspection of the producers suggests that it is safe to apply this change
- jenkins tests pass and comparisons with baseline show no differences

**Pull request merged**
