### PR TITLE
 lower pt cut on dedxhitinfo to 10 GeV and add dedx harmonic2 for pixel hits

### PR DESCRIPTION
**Pull request by slava77**
Lowering of pt from 15 GeV to 10 GeV increases signal yields by 10% for short (pixel-only) heavy high pt tracks.

Addition of the pixel-only harmonic2 enables calibration from AOD (it has to be done on low pt tracks; hence full addition).

the cost to AOD is about 1% (1 kB/event from the dedxHitInfo lower threshold and 3kB/evt from the pixel-only harmonic2) based on checks in ttbar and Run2016H JetHT  data. This estimate was made in 80X.

The addition of dedx  estimator for pixel to AOD is directly related to https://indico.cern.ch/event/638437/contributions/2595782/attachments/1460494/2255768/stoppedtracks_xpog_170516.pdf (see minutes for it in https://indico.cern.ch/event/638437/contributions/2595782/note/)

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by gpetruc** [comment]
Don't you also need to add a `keep *_dedxPixelHarmonic2_*_*` in https://github.com/cms-sw/cmssw/blob/master/RecoTracker/Configuration/python/RecoTracker_EventContent_cff.py#L63 ?

**Comment by slava77** [comment]
@cmsbuild please test

@gpetruc thanks for spotting the missing event content change, I had the change in local but not committed/pushed .. surprisingly I repeated the same in 80X as well

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/18773	f190f90
- jenkins tests pass and comparisons show differences only in DQM plots of /dedxHitInfo, corresponding to more tracks added to the plots as a result of lowering the threshold on selected tracks data to be saved
- local tests were done as a pre-submission step and impact is provided in the PR description

wf136 731_dedx_nhits

**Comment by davidlange6** [comment]
+1

**Pull request merged**
