### PR TITLE
Add DMQ FakeBeamMonitor plugin and clients

### PR DESCRIPTION
**Pull request by francescobrivio**
#### PR description:
- Added one new plugin under DQM/BeamMonitor: `DQM/BeamMonitor/plugins/FakeBeamMonitor.cc`
  - It's almost a copy of the BeamMonitor.cc plugin, except that the BeamSpot is not fitted from tracks and PVs, but is randomly generated using a TRandom3.
  - No change in the undelying logic with respect to the BeamMonitor is added
  - This plugin should be used when tracks/PVs are not available in the event, but a random BeamSpot is still needed (_e.g._ during MWGR)

- Added two clients (basically a copy of the already existing beamspot clients) that run the new FakeBeamMonitor plugin:
  - `DQM/Integration/python/clients/beamfake_dqm_sourceclient-live_cfg.py`
  - `DQM/Integration/python/clients/beamhltfake_dqm_sourceclient-live_cfg.py`

#### PR validation:
The new plugin and clients have been tested "offline" by me, @gennai and @ggovi using and "EmpySource" and thanks to @smorovic who was running a DAQ with fake runs. 
Two customizations are needed in the clients: 
- the parameter `authenticationPath` (lines [358 of `beamfake_dqm_sourceclient-live_cfg.py`](https://github.com/cms-sw/cmssw/compare/master...MilanoBicocca-pix:BSforOnlineHLT_FakeBS_11_2?expand=1#diff-7ef0ceb19db32176634c9c20f1f734e3R358) and [160 of `beamhltfake_dqm_sourceclient-live_cfg.py`](https://github.com/cms-sw/cmssw/compare/master...MilanoBicocca-pix:BSforOnlineHLT_FakeBS_11_2?expand=1#diff-bb2d600bca17d8ba649a5ea73d0631a8R160) ) should contain the path to the `db.key` file, needed for the upload to CondDB. A copy of this key can be found at P5 under `~govi/bs_key/.cms_cond` (@ggovi can confirm). 
- the parameter `lastLumiUrl` (lines [367 of `beamfake_dqm_sourceclient-live_cfg.py`](https://github.com/cms-sw/cmssw/compare/master...MilanoBicocca-pix:BSforOnlineHLT_FakeBS_11_2?expand=1#diff-7ef0ceb19db32176634c9c20f1f734e3R367) and [169 of `beamhltfake_dqm_sourceclient-live_cfg.py`](https://github.com/cms-sw/cmssw/compare/master...MilanoBicocca-pix:BSforOnlineHLT_FakeBS_11_2?expand=1#diff-bb2d600bca17d8ba649a5ea73d0631a8R169) ) was working fine at the moment of the test, but should be double checked.

#### Backporting
A backport to CMSSW_11_1_X might be needed.

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by andrius-k** [comment]
Hello,
Could you please provide a backport of this PR to 11_1_X for us (DQM) to test it in the playback system?
Regards,
Andrius

**Comment by francescobrivio** [comment]
> Hello,
> Could you please provide a backport of this PR to 11_1_X for us (DQM) to test it in the playback system?
> Regards,
> Andrius

**Comment by francescobrivio** [comment]
Sorry this was not supposed to be closed.

**Comment by francescobrivio** [comment]
> Hello,
> Could you please provide a backport of this PR to 11_1_X for us (DQM) to test it in the playback system?
> Regards,
> Andrius

I will open the backport.

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
@francescobrivio @gennai there were changes to this PR made by @andrius-k yesterday in the test done at the MWGR, as you suggested. We should include them in this PR, right? If we are expecting to make similar test in the future or actually use the code in online you should push these changes to the PR. Andrius can provide the diff if needed. Thanks

**Comment by francescobrivio** [comment]
> @francescobrivio @gennai there were changes to this PR made by @andrius-k yesterday in the test done at the MWGR, as you suggested. We should include them in this PR, right? If we are expecting to make similar test in the future or actually use the code in online you should push these changes to the PR. Andrius can provide the diff if needed. Thanks

I don't think this code is meant to be used in online (@gennai please correct me if I'm wrong), but we might want to use it again in similar tests. So if you can provide the diff I will push those changes as well.

**Comment by andrius-k** [comment]
Hi @francescobrivio,
I can see that you pushed another commit yesterday after we deployed the PR to P5. The diff between this PR (from the second commit) and what's currently running in P5 is the following:

``` diff
diff --git a/CondCore/DBOutputService/src/OnlineDBOutputService.cc b/CondCore/DBOutputService/src/OnlineDBOutputService.cc
index 9f8065c5f44..c1ec99522e9 100644
--- a/CondCore/DBOutputService/src/OnlineDBOutputService.cc
+++ b/CondCore/DBOutputService/src/OnlineDBOutputService.cc
@@ -11,8 +11,9 @@ cond::service::OnlineDBOutputService::OnlineDBOutputService(const edm::Parameter
       m_preLoadConnectionString(iConfig.getUntrackedParameter<std::string>("preLoadConnectionString", "")),
       m_debug(iConfig.getUntrackedParameter<bool>("debugLogging", false)) {
   if (!m_lastLumiUrl.empty()) {
-    startTransaction();
-    m_runNumber = PoolDBOutputService::session().getCurrentRun().run;
+    //startTransaction();
+    //m_runNumber = PoolDBOutputService::session().getCurrentRun().run;
+    m_runNumber = iConfig.getUntrackedParameter<unsigned long long>("runNumber",100000);
   } else {
     m_lastLumiFile = iConfig.getUntrackedParameter<std::string>("lastLumiFile", "");
     //if( m_lastLumiFile.size() == 0 ){
diff --git a/DQM/Integration/python/clients/beamfake_dqm_sourceclient-live_cfg.py b/DQM/Integration/python/clients/beamfake_dqm_sourceclient-live_cfg.py
index 5cc6468f4a2..704ddcad8f6 100644
--- a/DQM/Integration/python/clients/beamfake_dqm_sourceclient-live_cfg.py
+++ b/DQM/Integration/python/clients/beamfake_dqm_sourceclient-live_cfg.py
@@ -34,6 +34,8 @@ noDB = True
 if 'noDB=False' in sys.argv:
     noDB=False

+noDB = False
+
 #---------------
 # Input sources
 if unitTest:
@@ -363,8 +365,8 @@ process.OnlineDBOutputService = cms.Service("OnlineDBOutputService",
     preLoadConnectionString = cms.untracked.string('frontier://FrontierProd/CMS_CONDITIONS'),

     runNumber = cms.untracked.uint64(options.runNumber),
-    lastLumiFile = cms.untracked.string('last_lumi.txt'),
-    #lastLumiUrl = cms.untracked.string('http://ru-c2e14-11-01.cms:11100/urn:xdaq-application:lid=52/getLatestLumiSection'),
+    #lastLumiFile = cms.untracked.string('last_lumi.txt'),
+    lastLumiUrl = cms.untracked.string('http://ru-c2e14-11-01.cms:11100/urn:xdaq-application:lid=52/getLatestLumiSection'),
     writeTransactionDelay = cms.untracked.uint32(options.transDelay),
     latency = cms.untracked.uint32(2),
     autoCommit = cms.untracked.bool(True),
```

**Comment by francescobrivio** [comment]
> Hi @francescobrivio,
> I can see that you pushed another commit yesterday after we deployed the PR to P5. The diff between this PR (from the second commit) and what's currently running in P5 is the following:
> 
> ```diff
> diff --git a/CondCore/DBOutputService/src/OnlineDBOutputService.cc b/CondCore/DBOutputService/src/OnlineDBOutputService.cc
> index 9f8065c5f44..c1ec99522e9 100644
> --- a/CondCore/DBOutputService/src/OnlineDBOutputService.cc
> +++ b/CondCore/DBOutputService/src/OnlineDBOutputService.cc
> @@ -11,8 +11,9 @@ cond::service::OnlineDBOutputService::OnlineDBOutputService(const edm::Parameter
>        m_preLoadConnectionString(iConfig.getUntrackedParameter<std::string>("preLoadConnectionString", "")),
>        m_debug(iConfig.getUntrackedParameter<bool>("debugLogging", false)) {
>    if (!m_lastLumiUrl.empty()) {
> -    startTransaction();
> -    m_runNumber = PoolDBOutputService::session().getCurrentRun().run;
> +    //startTransaction();
> +    //m_runNumber = PoolDBOutputService::session().getCurrentRun().run;
> +    m_runNumber = iConfig.getUntrackedParameter<unsigned long long>("runNumber",100000);
>    } else {
>      m_lastLumiFile = iConfig.getUntrackedParameter<std::string>("lastLumiFile", "");
>      //if( m_lastLumiFile.size() == 0 ){
> diff --git a/DQM/Integration/python/clients/beamfake_dqm_sourceclient-live_cfg.py b/DQM/Integration/python/clients/beamfake_dqm_sourceclient-live_cfg.py
> index 5cc6468f4a2..704ddcad8f6 100644
> --- a/DQM/Integration/python/clients/beamfake_dqm_sourceclient-live_cfg.py
> +++ b/DQM/Integration/python/clients/beamfake_dqm_sourceclient-live_cfg.py
> @@ -34,6 +34,8 @@ noDB = True
>  if 'noDB=False' in sys.argv:
>      noDB=False
> 
> +noDB = False
> +
>  #---------------
>  # Input sources
>  if unitTest:
> @@ -363,8 +365,8 @@ process.OnlineDBOutputService = cms.Service("OnlineDBOutputService",
>      preLoadConnectionString = cms.untracked.string('frontier://FrontierProd/CMS_CONDITIONS'),
> 
>      runNumber = cms.untracked.uint64(options.runNumber),
> -    lastLumiFile = cms.untracked.string('last_lumi.txt'),
> -    #lastLumiUrl = cms.untracked.string('http://ru-c2e14-11-01.cms:11100/urn:xdaq-application:lid=52/getLatestLumiSection'),
> +    #lastLumiFile = cms.untracked.string('last_lumi.txt'),
> +    lastLumiUrl = cms.untracked.string('http://ru-c2e14-11-01.cms:11100/urn:xdaq-application:lid=52/getLatestLumiSection'),
>      writeTransactionDelay = cms.untracked.uint32(options.transDelay),
>      latency = cms.untracked.uint32(2),
>      autoCommit = cms.untracked.bool(True),
> ```

thanks @andrius-k !
I prefer not to touch the CondCore package, since @ggovi wrote that particular module and he might want to work more on that.
About the fake beamspot clients:
- the lastLumiFile/Url change has alrady been implemented in: https://github.com/cms-sw/cmssw/pull/30690/commits/1992d5bbad6c19e13dd96d70217e42a779585dda
- the parameter `noDB = False` instead should be read from command line, was there a problem with that?

**Comment by andrius-k** [comment]
Hi @francescobrivio 
No problem!
Regarding the `noDB` argument, unfortunately we can't selectively pass in different arguments to different Online clients. Is it possible for you to set the default value to whatever you would like it to be when running in Online production?

**Comment by jfernan2** [comment]
@francescobrivio @ggovi could you clarify a but about the noDB parameter, in particular:
- we cannot run selectively as @andrius-k said, except for limited tests for which we understand the FakeBeamMonitor is intended for, at least in some circustances
- for MWGRs, we understand that noDB should be then equal to False, i.e. the DB will be accesible, a run and a LS are available from DAQ, is this correct?
- noDB = True should be used for "offline" tests with no live mode or UnitTest mode, or any other playback mode to not overwrite the DB?
Thanks

**Comment by silviodonato** [comment]
kind reminder @francescobrivio

**Comment by gennai** [comment]
Hi, I can answer on the above points. noDB means that a sql file is created instead of uploading the new payload to the Prod condition DB. You are basically right.
noDB= True should be used for unit test and other local tests (including playback). For MWGR  noDB must be = False as we do want to upload the payload to the database.

**Comment by francescobrivio** [comment]
Sorry for the delay. Please see the inline answers.

> @francescobrivio @ggovi could you clarify a but about the noDB parameter, in particular:
> 
>     * we cannot run selectively as @andrius-k said, except for limited tests for which we understand the FakeBeamMonitor is intended for, at least in some circustances
Not sure I understand the `run selectively` part. Can't this option be bassed from command line?
> 
>     * for MWGRs, we understand that noDB should be then equal to False, i.e. the DB will be accesible, a run and a LS are available from DAQ, is this correct?
This is correct
> 
>     * noDB = True should be used for "offline" tests with no live mode or UnitTest mode, or any other playback mode to not overwrite the DB?
Correct. 

The `noDB = False` option (access the DB and upload conditions) should only be used for specific tests (e.g. during MWGR) or in normal data taking periods, as you can see in the "normal" BeamSpot client [here](https://github.com/cms-sw/cmssw/blob/master/DQM/Integration/python/clients/beam_dqm_sourceclient-live_cfg.py#L31)

**Comment by jfernan2** [comment]
Thanks @francescobrivio @gennai   
So, the default config we want is noDB = True to avoid real uploading (as it is the PR right now).

noDB = False will only be used on very dedicated ocasions, since DQM core will have to pass it manually by command line on a very limited number of runs. We have to manually switch it off on the client running at P5, which is error prone and not desired, that's why I meant by run selectively

Correct?

**Comment by gennai** [comment]
> Thanks @francescobrivio @gennai
> So, the default config we want is noDB = True to avoid real uploading (as it is the PR right now).
> 
> noDB = False will only be used on very dedicated ocasions, since DQM core will have to pass it manually by command line on a very limited number of runs. We have to manually switch it off on the client running at P5, which is error prone and not desired, that's what I meant by run selectively
> 
> Correct?

yes.

**Comment by jfernan2** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Comment by jfernan2** [comment]
@francescobrivio  we need a new PR in Master with
lastLumiFile = cms.untracked.string('last_lumi.txt'),
to make this PR working out of the box as commented in
https://github.com/cms-sw/cmssw/pull/30696#issuecomment-664966571
Thanks

**Pull request merged**
