### PR TITLE
drop type specs in RecoMET

### PR DESCRIPTION
**Pull request by jeongeun**
#### PR description: 
Update the safer syntax for existing parameter :
- drop type specifications where the original parameter exists.
- move all parameter inside the clone

Instead of modifying parameters with full type specs, which can be interpreted as an insertion of a new parameter, it is a safer way to protect from parameter name mistakes and will also help in possible parameter migrations.
(The previous PR were [PR#31162](https://github.com/cms-sw/cmssw/pull/31162),[PR#31243](https://github.com/cms-sw/cmssw/pull/31243),[PR#31332](https://github.com/cms-sw/cmssw/pull/31332), [PR#31389](https://github.com/cms-sw/cmssw/pull/31389))

In this PR, total 7 files updated. 
- RecoMET/{METPUSubtraction} 5 files 
- RecoMET/{METProducers} 2 files 

#### PR validation:
Event Content comparison check was also done and there is no change with these updates.
Tested in CMSSW_11_2_X, the basic test all passed in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html).

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
Errors seem unrelated (file open errors)
Let retry the tests later on

**Comment by perrotta** [comment]
please test
(retry...)

**Comment by perrotta** [comment]
+1
- Configurations cleaning implemented as anticipated in the PR descriptions
- Jenkins tests pass and show no differences, as expected

**Comment by silviodonato** [comment]
+1

**Pull request merged**
