### PR TITLE
Updated paths (DiPhoton, HighPtPhoton).

### PR DESCRIPTION
**Pull request by ryonamin**
For 76X.

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1
provided it passes the tests

**Comment by davidlange6** [comment]
+1

**Comment by davidlange6** [comment]
@ryonamin - hum, seems this does not merge...

**Comment by ryonamin** [comment]
I guess it is because I had to add "," to same line(s) in different PRs to add new paths at the end of the path list.
But this is the case, the conflict can be easily seen by eyes and can be solved easily, I think.
Anyway please let me know what I should do for this issue.
Thank you in advance!

**Comment by ryonamin** [comment]
Should I make another PR from the latest IB instead of this PR? or should I just wait?
Thank you for your suggestion in advance.

**Comment by davidlange6** [comment]
@ryonamin - lets start from a new PR - assuming it merges ok, I will merge into 76x right away. Thanks

**Comment by ryonamin** [comment]
Thank you for your suggention. I have made another PR (#11219).

**Pull request closed without merging**
