### PR TITLE
fixes tinyxml dependencies and uses tinyxml as external

### PR DESCRIPTION
**Pull request by iahmad-khan**

### CODE REVIEW

**Comment by smuzaffar** [comment]
@cmsbuild, please test with cms-sw/cmsdist#2352

**Comment by iahmad-khan** [comment]
@cmsbuild please test with cms-sw/cmsdist#2353

**Comment by Dr15Jones** [comment]
The tests failed because it was unable to open a temp file.

**Comment by Dr15Jones** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by davidlange6** [comment]
@smuzaffar - @iahmad-khan - this looks ready to go in - or is there something more to do?

**Comment by smuzaffar** [comment]
please test
@davidlange6 , do not understand why unit tests are failing.

**Comment by smuzaffar** [comment]
+1
testRecoMETMETProducers is failing in IB. 
@davidlange6 , this can be merged.

**Pull request merged**
