### PR TITLE
Putting final XeXe beamspot smearing parameters into master for future compatibility

### PR DESCRIPTION
**Pull request by gsfs**

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by fabiocos** [comment]
@gsfs were the old parameters already used for official productions? The PR in itself is simple and looks ready to go

**Comment by gsfs** [comment]
No, the old parameters were never used for official production. That's why we felt it was appropriate to keep the same name and just change the numbers.

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Pull request merged**
