### PR TITLE
MTD geometry: add scenario D39 equal to D38 but for the crystal thickness [10_4_X backport of 25639]

### PR DESCRIPTION
**Pull request by fabiocos**
Add scenario D39 equal to D38 but for the crystal thickness in the innermost and outermost regions, set as in D35

(cherry picked from commit b6f1baf0b36d6efaff972417aed3b09cbcfcc004)

minor comment by K. Pedro on geometry description

(cherry picked from commit 41eae85e4cb816935ff9817d235952a325ff6f5f)

### CODE REVIEW

**Comment by fabiocos** [comment]
code-checks

**Comment by fabiocos** [comment]
please test workflow 27434.0

**Comment by fabiocos** [comment]
the problem in the baseline is due to the fact that #25717 was needed by the RECO additions, repeating the test after it is merged in CMSSW_10_4_X_2019-01-22-1100

**Comment by fabiocos** [comment]
please test workflow 27434.0

**Comment by kpedro88** [comment]
backport of #25639

**Comment by fabiocos** [comment]
@cvuosalo @kpedro88 @prebello @zhenhu this is the exact backport of what you have already signed in master, could you please sign it for reference?

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Comment by kpedro88** [comment]
+upgrade

**Comment by cvuosalo** [comment]
+1

**Pull request merged**
