### PR TITLE
[10_3_X] Regional strip unpacker: support for legacy modes and bugfix for virgin raw

### PR DESCRIPTION
**Pull request by pieterdavid**
Backport of https://github.com/cms-sw/cmssw/pull/24851
As I understood, there is no plan to use virgin raw for the upcoming HI run, but we are submitting this bugfix to have it in place just in case.

CC: @icali @alesaggio

### CODE REVIEW

**Comment by icali** [comment]
Yes, at the moment there is no plan to use VR mode this year. However, if during the HI run the tracker hybrid mode will not behave as expected (extremely unlikely because tested extensively), as a plan B we would need to run the tracker in VR mode.  Being a piece of code that is completely orthogonal to pp data-taking, it could be beneficial to have it included also in 10_3_0.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
assign hlt
similar reasoning to https://github.com/cms-sw/cmssw/pull/24851#issuecomment-430321971

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/24852	91d3de7
- HLT-specific clusterizer from RAW inputs 
- the backport from the master #24851 is trivial: the same topic branch is used
- jenkins tests pass and comparisons with the baseline show no differences (the SiStripClusterizerFromRaw is used in the standard tests and its default behavior related to the standard SiStrip packing is unchanged)

**Comment by Martin-Grunewald** [comment]
+1

**Comment by fabiocos** [comment]
@icali as I understand that the RelVal campaign in 10_4_X will probe little about this PR, was any standalone test done?

**Comment by icali** [comment]
No, as of today we didn't test it further of what was done by Pieter. We simply verified that the changes were in line with what we know being a bug in 2015.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
