### PR TITLE
switch pixelLess iteration to use CKF instead of mkFit

### PR DESCRIPTION
**Pull request by slava77**
Discussion in PPD Aug 4
https://indico.cern.ch/event/1187803/#43-discussion-of-reversion-to
appears to be converging to the decision to switch the pixelLess iteration to use CKF instead of mkFit.

This PR makes the switch and removes Run3_ckfPixelLessStep, which is now identical to Run3
(I checked this using the run3 wf 11834.0 expanded config for step3).

@cms-sw/tracking-pog-l2

### CODE REVIEW

**Comment by slava77** [comment]
backport of #38967

**Comment by qliphy** [comment]
please test

**Comment by bbilin** [comment]
@cmsbuild please test

**Comment by mmusich** [comment]
@cms-sw/pdmv-l2 @cms-sw/upgrade-l2 can you have a look to this?

@cms-sw/orp-l2 the creation of a release with this PR needs to be timed in carefully because it has implications on the structure of the output datasets for prompt reco (era or processing version change). This ping is just to collect signatures in case of need.

**Comment by AdrianoDee** [comment]
+upgrade
- nothing to comment from the upgrade point of view: backport of https://github.com/cms-sw/cmssw/pull/38967

**Comment by bbilin** [comment]
+pdmv

**Comment by perrotta** [comment]
Given the discussion in the [Mattermost ORM channel](https://mattermost.web.cern.ch/cms-exp/channels/orm--t0) I wonder whether we should also merge this PR, and cut a 12_4_7 right after with all tracking changes included all at once...

**Comment by mmusich** [comment]
hi @perrotta 

> Given the discussion in the [Mattermost ORM channel](https://mattermost.web.cern.ch/cms-exp/channels/orm--t0) I wonder whether we should also merge this PR, and cut a 12_4_7 right after with all tracking changes included all at once...

given the blessing of O&C and the agreement of the ORM, we think we can go ahead with the merge of this PR and the creation of CMSSW_12_4_7. 
Thank you.

**Comment by perrotta** [comment]
+1
- See https://github.com/cms-sw/cmssw/pull/38968#issuecomment-1219259820

**Comment by slava77** [comment]
type tracking

**Pull request merged**
