### PR TITLE
Adding fastjet shape correction for analysis in 74x

### PR DESCRIPTION
**Pull request by rappoccio**
Here is a fastjet "rho-based" shape correction for future analysis releases in 74x. 
Currently this is completely disabled by default. Some advances in fastjet contrib
are forthcoming to make this much faster than it currently is. Until then,
this should remain disabled except for expert usage in analyses.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by rappoccio** [comment]
Please hold off on the tests, many apologies but the line "use_common_bge_for_rho_and_rhom" should be commented with the version of fastjet in the release. This will be in future fastjet versions.

**Comment by rappoccio** [comment]
Apologies again... this is fixed. I accidentally committed my private version with private fastjet.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
+1

For #11285 8a8a9ce07e960b8c190186d90aed0c06730381d6

Adding Fast Jet shape correction, but disabled by default. There should be no change in standard workflows. The shape correction is intended for expert use by analysts.

The code changes are satisfactory, and Jenkins [tests]() against baseline CMSSW_7_4_X_2015-09-16-1100 show no significant differences, as expected.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
