### PR TITLE
GEM Online & Offline Efficiency Update

### PR DESCRIPTION
**Pull request by seungjin-yang**
#### PR description:
This PR mainly simplifies the directory structure in the DQM output file and reduces redundant plots. Also, in the offline DQM, the way to build the initial state muon propagations and a matching metric is changed. You can find more details [here](https://indico.cern.ch/event/1161504/contributions/4878468/attachments/2444237/4188150/SYang_220515.pdf).
From a technical point of view, this PR adds base classes for online and offline efficiency monitors.

#### PR validation:
Because this PR affects both the online and the offline DQM, this PR was validated with two tests.

- For the online DQM,
```bash
cmsrel CMSSW_12_4_0_pre3
cd CMSSW_12_4_0_pre3/src
git-cms-merge-topic GEM-DQM-Eff-Update_from-CMSSW_12_4_0_pre3
git-cms-addpkg DQM/Integration
cmsRun ${CMSSW_BASE}/src/DQM/Integration/python/clients/gem_dqm_sourceclient-live_cfg.py unitTest=True
```
You can find unit test output files [here](https://github.com/seungjin-yang/GEM-Workspace/tree/main/SW-Dev/220426_GEM-Offline-DQM-New-Naming-and-Modes/test/CMSSW_12_4_0_pre3/OnlineDQM-unitTest/upload).

- For the offline DQM,
```bash
cmsrel CMSSW_12_4_0_pre3
cd CMSSW_12_4_0_pre3/src
git-cms-merge-topic GEM-DQM-Eff-Update_from-CMSSW_12_4_0_pre3
runTheMatrix.py -w upgrade -l 11611.0
```
You can find the results [here](https://indico.cern.ch/event/1161504/contributions/4878468/attachments/2444237/4188150/SYang_220515.pdf).

#### if this PR is a backport please specify the original PR and why you need to backport that PR:
This PR is not a backport but is required to be backported for applying changes to upcoming runs.

### CODE REVIEW

**Comment by seungjin-yang** [comment]
@jshlee @quark2

**Comment by jshlee** [comment]
please test

**Comment by emanueleusai** [comment]
+1

**Comment by emanueleusai** [comment]
there is a large number of failures that in not present in the 12_4 backport.
I understand the plots added/ removed are caused by the reorganization, but why are there changed plots in workflow 12434.0? See: https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_4_X_2022-05-15-2300+c7fca7/50302/dqm-histo-comparison-summary.html
Interestingly many of those plots are empty: https://cmsweb.cern.ch/dqm/dev/start?runnr=1;dataset%3D/RelVal_wf12434_0_pr/CMSSW_12_4_X-PRcmssw_37954-50302/DQMIO;referenceshow%3Dall;referencenorm=False;referenceobj1%3Dother::/RelVal_wf12434_0_base/CMSSW_12_4_X-PRcmssw_37954-50302/DQMIO::;sampletype%3Doffline_relval;workspace%3DEverything;

**Comment by perrotta** [comment]
@emanueleusai please see https://github.com/cms-sw/cmssw/issues/37970

**Comment by emanueleusai** [comment]
+1

**Comment by qliphy** [comment]
@seungjin-yang Please squash the commits into one

**Comment by seungjin-yang** [comment]
@qliphy I did squashing using rebase.

**Comment by perrotta** [comment]
please test
(also good opportunity to test whether the non reproducibility of Tracking DQM in wf 12434.0 actually disappears after the merging of #38004 in the IB)

**Comment by perrotta** [comment]
After the merging of https://github.com/cms-sw/cmssw/pull/38004 the non reproducibility of the Tracking DQM in wf 12434.0 looks like having been disappeared: that's great!

Related to this PR, I notice several Log messages of this kind:
```
%MSG-e GEMEfficiencyAnalyzer:  GEMEfficiencyAnalyzer:gemEfficiencyAnalyzerSta  20-May-2022 10:28:07 CEST Run: 1 Event: 2
failed to propagate a muon from (Detector, Subdetector) = (2, 3) to  Re 1 Ri 1 St 1 La 1 Ch 1 Et 0 . The path length is 0
%MSG
%MSG-e GEMEfficiencyAnalyzer:  GEMEfficiencyAnalyzer:gemEfficiencyAnalyzerSta  20-May-2022 10:28:07 CEST Run: 1 Event: 2
failed to propagate a muon from (Detector, Subdetector) = (2, 3) to  Re 1 Ri 1 St 1 La 1 Ch 64 Et 0 . The path length is 0
%MSG
%MSG-e GEMEfficiencyAnalyzer:  GEMEfficiencyAnalyzer:gemEfficiencyAnalyzerSta  20-May-2022 10:28:07 CEST Run: 1 Event: 2
failed to propagate a muon from (Detector, Subdetector) = (2, 3) to  Re 1 Ri 1 St 1 La 2 Ch 1 Et 0 . The path length is 0
%MSG
%MSG-e GEMEfficiencyAnalyzer:  GEMEfficiencyAnalyzer:gemEfficiencyAnalyzerSta  20-May-2022 10:28:07 CEST Run: 1 Event: 2
failed to propagate a muon from (Detector, Subdetector) = (2, 3) to  Re 1 Ri 1 St 1 La 2 Ch 64 Et 0 . The path length is 0
%MSG
```

Coud you please check and take care of them? (I.e. fix the origin, if these messages are relevant, or demote them if they are not)

**Comment by seungjin-yang** [comment]
@perrotta, I intended such messages, but it looks good to lower the log level. I will replace it with LogDebug soon. Thank you for letting me know.

**Comment by perrotta** [comment]
please test

**Comment by emanueleusai** [comment]
please test

**Comment by emanueleusai** [comment]
+1

**Comment by perrotta** [comment]
@quark2, do I understand correctly that merging this PR won't interfere with the fix you are preparing for #37786?

**Comment by quark2** [comment]
Hi @perrotta, 

yep, it is not related to the issue. The efficiency part and other DQM parts are well separated.

**Comment by perrotta** [comment]
+1

**Pull request merged**
