### PR TITLE
Add L1T lowPU v3 menu (75X)

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
Add L1T lowPU v3 menu (75X)
The L1 xml file is provided by Takashi MATSUSHITA takashi.matsushita@cern.ch

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by mulhearn** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
