### PR TITLE
Add ppRef modifier instead of a GT

### PR DESCRIPTION
**Pull request by tvami**
#### PR description:

A technical change so that we don't need to create ppRef GTs anymore. Remove `phase1_2017_realistic_ppref` from autoCond and include it in the autoCondModifier

#### PR validation:

runTheMatrix.py -l 149.0 runs fine

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

### CODE REVIEW

**Comment by malbouis** [comment]
The 'phase1_2017_realistic_ppref' key is based on the 'phase1_2017_realistic' with the addition of the tags included in the difference of 120X_mc2017_realistic_v1/120X_mc2017_realistic_forppRef5TeV_v2.

`conddb diff 120X_mc2017_realistic_v1 120X_mc2017_realistic_forppRef5TeV_v2`

`conddb diff 120X_mc2017_realistic_v1 120X_mc2017_realistic_forppRef5TeV_v2
[2021-10-30 10:46:44,224] INFO: Connecting to pro [frontier://PromptProd/cms_conditions]
Record                        Label  pro::120X_mc2017_realistic_v1 Tag                              pro::120X_mc2017_realistic_forppRef5TeV_v2 Tag   
----------------------------  -----  -------------------------------------------------------------  ----------------------------------------------   
BeamSpotObjectsRcd            -      BeamSpotObjects_Realistic25ns_13TeVCollisions_Early2017_v1_mc  BeamSpotObjects_pp_2017G_MC_2021sample_for_UL    
EcalLaserAPDPNRatiosRcd       -      EcalLaserAPDPNRatios_UL_2017_mc                                EcalLaserAPDPNRatios_mc_Run2017G_306580          
EcalPedestalsRcd              -      EcalPedestals_UL_2017_mc                                       EcalPedestals_Run2017G_306580                    
EcalTPGLinearizationConstRcd  -      EcalTPGLinearizationConst_UL_2017_mc                           EcalTPGLinearizationConst_Run2017G_306580        
EcalTPGPedestalsRcd           -      EcalTPGPedestals_UL_2017_mc                                    EcalTPGPedestals_Run2017G_306580                 
L1TUtmTriggerMenuRcd          -      L1Menu_Collisions2017_v4                                       L1Menu_pp502Collisions2017_v4_m6_xml`

The Modifier autoCond2017ppRef5TeV introduced in this PR takes exactly the same records/tags as above.

the unit test failure from above is not related to this PR.

**Comment by malbouis** [comment]
+alca

**Comment by qliphy** [comment]
merge

**Comment by qliphy** [comment]
@tvami  There is conflict to be resolved after merging #35914

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
@cmsbuild , please test with https://github.com/cms-sw/cmssw/pull/35766

**Comment by malbouis** [comment]
+alca

**Comment by tvami** [comment]
Results are as expected
 * unit test fails due to https://github.com/cms-sw/cmssw/issues/35868
 * Jenkins diffs are zero
 * more importantly 149.0 runs fine (this is he wf that uses the ppRef GT)

**Comment by tvami** [comment]
> @tvami There is conflict to be resolved after merging #35914

Hi @qliphy conflict is resolved and tests have finished nicely (except for the known unit test issue)

**Comment by qliphy** [comment]
merge

**Pull request merged**
