### PR TITLE
Phase2-hgx315A Make changes to make small corrections for v17 geometry

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Make changes to make small corrections for v17 geometry

#### PR validation:

Use test scripts in test/python in Geometry/HGCalCommonData and Geometry/HGCalGeometry

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
+1

**Comment by bsunanda** [comment]
@emanueleusai, @AdrianoDee, @srimanob, @jfernan2, @ahmad3213, @pmandrik, @micsucmed, @rvenditti can you please review it and eventually

**Comment by srimanob** [comment]
+Upgrade

Update on new V17 HGCal which is not yet in workflows.

**Comment by emanueleusai** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
