### PR TITLE
Move commons.h to DataFormats/HGCalReco to break cyclic dep

### PR DESCRIPTION
**Pull request by smuzaffar**
This PR proposes to move `RecoHGCal/TICL/interface/commons.h` to `DataFormats/HGCalReco/interface/commons.h` to break the cyclic dependency. `RecoHGCal/TICL` depends `DataFormats/HGCalReco` via [a]. Moving the `commons.h` in to `DataFormats/HGCalReco` break the cyclic deps and should also fix the FWLite build errors [b] as `RecoHGCal/TICL` is not part of fwlite build

[a]
```RecoHGCal/TICL/plugins/TICLCandidateFromTrackstersProducer.cc:#include "DataFormats/HGCalReco/interface/TICLCandidate.h"
RecoHGCal/TICL/plugins/TICLCandidateFromTrackstersProducer.cc:#include "DataFormats/HGCalReco/interface/Trackster.h"
RecoHGCal/TICL/plugins/PFTICLProducer.cc:#include "DataFormats/HGCalReco/interface/TICLCandidate.h"
RecoHGCal/TICL/plugins/HGCGraph.cc:#include "DataFormats/HGCalReco/interface/Common.h"
RecoHGCal/TICL/plugins/SeedingRegionAlgoBase.h:#include "DataFormats/HGCalReco/interface/Common.h"
RecoHGCal/TICL/plugins/SeedingRegionAlgoBase.h:#include "DataFormats/HGCalReco/interface/TICLSeedingRegion.h"
RecoHGCal/TICL/plugins/TICLDumper.cc:#include "DataFormats/HGCalReco/interface/Trackster.h"
RecoHGCal/TICL/plugins/TICLDumper.cc:#include "DataFormats/HGCalReco/interface/TICLCandidate.h"
RecoHGCal/TICL/plugins/TICLDumper.cc:#include "DataFormats/HGCalReco/interface/Common.h"
RecoHGCal/TICL/plugins/TICLDumper.cc:#include "DataFormats/HGCalReco/interface/commons.h"
RecoHGCal/TICL/plugins/TICLLayerTileProducer.cc:#include "DataFormats/HGCalReco/interface/TICLLayerTile.h"
RecoHGCal/TICL/plugins/LinkingAlgoByDirectionGeometric.h:#include "DataFormats/HGCalReco/interface/commons.h"
RecoHGCal/TICL/plugins/LinkingAlgoByDirectionGeometric.h:#include "DataFormats/HGCalReco/interface/TICLLayerTile.h"
RecoHGCal/TICL/plugins/LinkingAlgoByDirectionGeometric.h:#include "DataFormats/HGCalReco/interface/Trackster.h"
RecoHGCal/TICL/plugins/TrackstersPCA.h:#include "DataFormats/HGCalReco/interface/Trackster.h"
```

[b]
```
In file included from input_line_7:70:
src/DataFormats/HGCalReco/interface/TICLCandidate.h:10:10: fatal error: 'RecoHGCal/TICL/interface/commons.h' file not found
#include "RecoHGCal/TICL/interface/commons.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

### CODE REVIEW

**Comment by smuzaffar** [comment]
@felicepantaleo , your PR https://github.com/cms-sw/cmssw/pull/44785 had introduced this dependency. please feel free to propose a better change ( e.g. move `common.h` to some other common base package)

**Comment by felicepantaleo** [comment]
Thanks @smuzaffar DataFormats/HGCalReco is a good location.

**Comment by felicepantaleo** [comment]
@cmsbuild please test

**Comment by smuzaffar** [comment]
hold

@felicepantaleo , there is already [DataFormats/HGCalReco/interface/Common.h](https://github.com/cms-sw/cmssw/blob/master/DataFormats/HGCalReco/interface/Common.h) , Any objections on merging both DataFormats/HGCalReco/interface/Common.h and DataFormats/HGCalReco/interface/commons.h ?

**Comment by felicepantaleo** [comment]
@smuzaffar Since there is already a PR fixing pending stuff in TICLv5, maybe we can make the fix you propose here  https://github.com/cms-sw/cmssw/pull/45215 and close this PR so that we avoid conflicts, rebase, and retriggering of tests.

**Comment by smuzaffar** [comment]
@felicepantaleo , I have merged `commons.h` in to `Common.h` also remove the unused header e.g. `RecoLocalCalo/HGCalRecAlgos/interface/RecHitTools.h` to avoid the Dataformat dependency on `RecoLocalCalo/HGCalRecAlgos`. Though this PR  and #45215 both touches `[RecoHGCal/TICL/plugins/SimTrackstersProducer.cc](https://github.com/cms-sw/cmssw/pull/45215/files#diff-70a0f36c20d1f73fb9385989ae8b56c04aef863aa9a7dd07c4aad62947f86362)` but  I think this PR can go in parallel with #45215  as changes are well isolated and there will be no need to rebase

**Comment by smuzaffar** [comment]
please test

**Comment by mandrenguyen** [comment]
+1

**Comment by smuzaffar** [comment]
@cms-sw/dqm-l2 @cms-sw/upgrade-l2 can you please review this PR . This should fix the cyclic source level dependency between `RecoHGCal/TICL` and `DataFormats/HGCalReco` and also should fix the FWLite build error

**Comment by smuzaffar** [comment]
unhold

**Comment by tjavaid** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
