### PR TITLE
Add support to multi layout portable collections (up to 5) [14.0.x]

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

The design is recursive, but ROOT seems not to serialize variadic templates, so we have a 5 elements design. This number is arbitrary and can be changed with relatively little work.

The order of the PortableDeviceCollection template parameters is changed from device at the end to device at the beginning to accommodate the pseudo variadic templation.

A test validates the collection with two layouts and three layouts.

The layout and view can be accessed by index or type, on the condition the type is present only once in the collection.

The default index is set to 0 to minimize the need for changes in the single layout case. Empty template parameters square bracket ("<>") are needed in some cases.

Convenience scripts are added to generate the XML need for dictionary generation but has to be edited if there are commonalities between multiple collections.

#### PR validation:

The PR is validated with the pre-existing `HeterogeneousCore/AlpakaTest/test/testHeterogeneousCoreAlpakaTestWriteRead.sh` which has been extended to add a two-layouts example.

#### Backport status

Backport of #40285 to CMSSW 14.0.x, from the same branch.

### CODE REVIEW

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
> ## Unit Tests
> 
> I found 1 errors in the following unit tests:
> 
> ---> test test-das-selected-lumis had ERRORS

The failed test is unrelated to this PR:

> ```
> ===== Test "test-das-selected-lumis" ====
> + export CMS_BOT_USE_DASGOCLIENT=true
> + CMS_BOT_USE_DASGOCLIENT=true
> + QUERY='lumi,file dataset=/HIHardProbes/HIRun2018A-v1/RAW run=326479'
> + dasgoclient --limit 0 --query 'lumi,file dataset=/HIHardProbes/HIRun2018A-v1/RAW run=326479' --format json
> + das-selected-lumis.py 1,23
> + grep '^/store/'
> 2024/02/13 03:25:10 ERROR failed to parse X509 proxy: crypto/tls: failed to parse key: asn1: syntax error: data truncated
> 
> ---> test test-das-selected-lumis had ERRORS
> TestTime:3
> ^^^^ End Test test-das-selected-lumis ^^^^
> ```

**Comment by smuzaffar** [comment]
ignore tests-rejected with external-failure

we have randomly seen such failure but really do not understand why `dasgoclient`  soemtimes can not parse the key

**Comment by fwyzard** [comment]
+heterogeneous

**Comment by fwyzard** [comment]
urgent

for CMSSW_14_0_0, as discussed at the ORP on 2024/02/13

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
