### PR TITLE
Update tau embed wf

### PR DESCRIPTION
**Pull request by kskovpen**
#### PR description:

Update the tau embed wf to include the proper data tier specs and an additional miniaod step.

#### PR validation:

Validated with 136.900 wf.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Not a backport.

### CODE REVIEW

**Comment by kskovpen** [comment]
please test

**Comment by kskovpen** [comment]
test parameters:
- workflow = 136.900

**Comment by kskovpen** [comment]
please test

**Comment by srimanob** [comment]
+Upgrade

The updated workflow 136.9 runs fine.

**Comment by kskovpen** [comment]
+pdmv

**Comment by qliphy** [comment]
please test
just to refresh the old test results

**Pull request merged**
