### PR TITLE
[12_0_X] Backport concurrent GEN utilities

### PR DESCRIPTION
**Pull request by colizz**
#### PR description:

The concurrent GEN utilities are also be backported to 12_0_X, to benefit some samples produced by POG in the Run 3 condition. (similar to the 10_6_X backport https://github.com/cms-sw/cmssw/pull/34527)

It includes two PRs backported from the master branch:

- https://github.com/cms-sw/cmssw/pull/34710
- https://github.com/cms-sw/cmssw/pull/35072

#### PR validation:

No local test done. The PR should be well validated by triggering 'please test' (running on all workflows)

### CODE REVIEW

**Comment by AdrianoDee** [comment]
test parameters:
- workflows = 573

**Comment by qliphy** [comment]
test parameters:
- enable_test = threading
- workflow_threading = 570,571,572,573,574,575,576,577,562.0,537.0,1361.17,1361.0,1310.0,560.0
- workflows = 570,571,572,573,574,575,576,577,562.0,537.0,1361.17,1361.0,1310.0,560.0

**Comment by qliphy** [comment]
please test

**Comment by agrohsje** [comment]
+generators

**Comment by jordan-martins** [comment]
+1

**Comment by qliphy** [comment]
ping @cms-sw/upgrade-l2   Do you have any comment?

**Comment by srimanob** [comment]
+Upgrade

This PR is a backport of GEN concurrent utilities.

**Comment by qliphy** [comment]
+1

**Pull request merged**
