### PR TITLE
add genfragment for Chi_b -> Y(1S)Gamma and Chi_c -> J/psiGamma

### PR DESCRIPTION
**Pull request by mtosi**
following the suggestion and request by BPH PAG,
we are adding the genFragments for the Chi_b --> Y(1S)Gamma and Chi_c --> J/psiGamma production at 14 TeV

these will be used for the special relval samples request we are aiming for the validation of the effect of the loopers disabling (https://its.cern.ch/jira/browse/PDMVRELVALS-128) and the mkFit (https://its.cern.ch/jira/browse/PDMVRELVALS-130)

@kskovpen @slezki

### CODE REVIEW

**Comment by mtosi** [comment]
@cmsbuild, please test

**Comment by qliphy** [comment]
@cms-sw/generators-l2 Any comment?

**Comment by alberto-sanchez** [comment]
No issues for me. I worked in those cfg couple of years ago, and should be ok.

**Comment by agrohsje** [comment]
As @alberto-sanchez used them already, I have no comments on the physics. Maybe two small ones on the names. 
I would change hyphen to underscore. I hope I remember correctly that we decided to use always underscores, different from the dataset name where we mix. This is also not consistent for the 2 files. 
And maybe we should also indicate the MuFilter in the second config name, as done for the first, no?

**Comment by alberto-sanchez** [comment]
I have run again these cfgs. I found an issue with the one for chic. The 

'PhaseSpace:pTHatMin = 2.'

seems low. I would suggest to set it to something like

'PhaseSpace:pTHatMin = 10.'

this is because the cut on the J/psi is higher (16.0 GeV), which is well motivated for the high pT thresholds on the triggers for inclusive J/psi.

**Comment by mtosi** [comment]
as highlighted by @slezki in order to optimize the filter efficiency,
I've just update the parameter 'PhaseSpace:pTHatMin = 10.', this should provide an efficiency around 4.671e-02

**Comment by qliphy** [comment]
please test

**Comment by GurpreetSinghChahal** [comment]
thanks @mtosi would you like to include MuFilter in the name of the first fragment, as suggested by Alex? It'd be better to stay consistent with the names as MuFilter is used in both fragments. Then we can approve it asap.

**Comment by agrohsje** [comment]
@mtosi : if you are modifying the name, you could replace - with _.

**Comment by qliphy** [comment]
@mtosi  Would you please address comments from GEN?

**Comment by qliphy** [comment]
ping @mtosi

**Comment by SiewYan** [comment]
please test

**Comment by qliphy** [comment]
please test

**Comment by SiewYan** [comment]
All comments are addressed.

**Comment by SiewYan** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
