### PR TITLE
Replacing HLT Scouting trigger paths by new Run3 Scouting trigger path

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
#### PR description:

Replacing HLT Scouting trigger paths by new Run3 Scouting trigger path
Based on CMSSW_11_3_X_2021-01-31-2300

Also including PFBlockProducer changes (#32291) and update to CMSSW_11_3_0_pre2 ConfDB template

#### PR validation:

TSG tests

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
Underlying IB (used for PR jenkins tests) is broken: CMSSW_11_3_X_2021-02-02-2300 - need to wait until this is fixed!

**Comment by Martin-Grunewald** [comment]
Re-testing with new IB CMSSW_11_3_X_2021-02-03-0800

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
