### PR TITLE
Replace patterns with explicit class names in `DataFormats/Math/src/classes_def.xml`

### LINKED ISSUE #977: Replace patterns with explicit class names in `DataFormats/Math/src/classes_def.xml`

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

This PR is part of series to replace the last remaining uses `class pattern` elements in `classes_def.xml` with explicit class names. In addition, it cleans up `classes.h` file. ~~, and marks the `MiniFloatConverter::ReduceMantissaToNbitsRounding` as transient (since its persistency was clearly no the intention in https://github.com/cms-sw/cmssw/pull/42323)~~ (this class does not need to marked as transient because it is not an instantiation of `edm::Wrapper<T>` template, and `persistent="false"` would have zero impact)

Resolves https://github.com/cms-sw/framework-team/issues/977

#### PR validation:

Code compiles. The generated `.rootmap` files are nearly identical. This PR adds
```
class vector<std::pair<ROOT::Math::PositionVector3D<ROOT::Math::Cartesian3D<double>,ROOT::Math::DefaultCoordinateSystemTag>,float> >
``` 
there (there already was a  nearly identical `vector<pair<...`).

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
@cmsbuild, please abort

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
Comparison differences are related to https://github.com/cms-sw/cmssw/issues/39803

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
