### PR TITLE
GT updates for 900pre5 with Summer16 JECs, GEM reco geometry and ESEE Intercalib

### PR DESCRIPTION
**Pull request by arunhep**
Description is updated below.

### CODE REVIEW

**Comment by franzoni** [comment]
@davidlange6 
we would like this considered at the ORP today
we're waiting for the tests to finish to sign it

**Comment by franzoni** [comment]
+ **GEM RECO geometry** --> not expected to yield any change, simply added a record to support future eras which will demand the present of GEM reco geometry

+ **ESEE Intercalibration** --> only affects 2016D, not probed by the short matrix; @cmkuo tested locally `[here](https://github.com/cms-sw/cmssw/pull/17219#issuecomment-280834478)` 

+ impact of **JEC's update in** **data 2016B** expected and understood, see [link]( https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_9_0_X_2017-02-27-2300+17649/18507/136.731_RunSinglePh2016B+RunSinglePh2016B+HLTDR2_2016+RECODR2_2016reHLT_skimSinglePh_HIPM+HARVESTDR2/ ) and plot 
jetmet__jet_cleanedak4pfjets_dijet_jetenergycorrvspt

+ impact of **JEC's update in MC** not understood. 
    + The update is **visible in the TTBar with 50ns** pileup ([plots](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_9_0_X_2017-02-27-2300+17649/18507/50202.0_TTbar_13+TTbar_13+DIGIUP15_PU50+RECOUP15_PU50+HARVESTUP15_PU50/JetMET_Jet_Cleanedak4PFJetsCHS.html))
50_ns_jetmet__jet_cleanedak4pfjetschs_dijet_jetenergycorrvseta

    + The update is **NOT visible in the TTBar with 25ns** pileup ([plots](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_9_0_X_2017-02-27-2300+17649/18507/25202.0_TTbar_13+TTbar_13+DIGIUP15_PU25+RECOUP15_PU25+HARVESTUP15_PU25/JetMET_Jet_Cleanedak4PFJetsCHS.html))

We'll update this PR when understood.
@schoef @slava77

**Comment by franzoni** [comment]
We got a larger (x10) statistics for TTBar 2016 with pile up. We confirm the outcome when looking at the profile of the average JEC's applied as a function of eta and pt (red=new GT's, blue=GT's as in the 90x currently - same conventions as the plots of last week):
   * in the 50ns we observe differences


50ns_eta_ttbar_50200_1

   * in the 25ns there's no change


25ns_pt_ttbar_25200_1
25ns_eta_ttbar_25200_1

   * in the 2017 (noPU) there's no change, either

@slava77 @schoef can you give us hints

**Comment by slava77** [comment]
On 3/6/17 2:29 AM, Giovanni Franzoni wrote:
> @slava77 <https://github.com/slava77> @schoef
> <https://github.com/schoef> can you give us hints
> 

I don't have any specific comments based on the posted plots.

**Comment by franzoni** [comment]
Thanks @slava77 
We've gotten feedback form Henning (JetMet) and will update this chat in the next hours with a summary.

**Comment by arunhep** [comment]
please test

**Comment by franzoni** [comment]
* the update being deployed here to JEC's here only involves, for MC, their uncertainties
   * as such, no differences are expected on the profiles vs eta/pt of the consumed JEC corrections, which is now the case for the 25ns and 50ns alike (for 2017 it's already been reported earlier) - verified in the relmon plots
   * the difference previously noted on the 50ns plots stemmed from the fact that the 2016 startup global tag holds JEC's derived for 50ns; the tags we're deploying here are intended for 25 ns instead, hence we reverted the change to leave in 2016 startup. Now now no changes on the profiles vs eta/pt of the consumed JEC's are visible
   * changes in MET, which probers also the JEC errors, proves that there is an effect of deploying the new tags, see:
jetmet__metvalidation_slimmedmets_metunc_jetendown
jetmet__metvalidation_slimmedmets_metunc_jetenup


Many Thanks to @kirshen and @schoef

**Comment by franzoni** [comment]
+1

**Comment by franzoni** [comment]
related to this [80x PR](https://github.com/cms-sw/cmssw/pull/17219#issuecomment-274074304) 
which needs this PR to be merged/tested to trigger a backport 
( Es conditions and code fix among the features needed for the legacy rereco )

**Comment by arunhep** [comment]
# Summary of changes in Global Tags

## RunII simulation

   * **RunII Asymptotic scenario** : [90X_mcRun2_asymptotic_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_mcRun2_asymptotic_v5) as [90X_mcRun2_asymptotic_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_mcRun2_asymptotic_v4) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/90X_mcRun2_asymptotic_v5/90X_mcRun2_asymptotic_v4):
      * Summer16 JECs

   * **RunII Ideal scenario** : [90X_mcRun2_design_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_mcRun2_design_v5) as [90X_mcRun2_design_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_mcRun2_design_v4) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/90X_mcRun2_design_v5/90X_mcRun2_design_v4):
      * Summer16 JECs

   * **RunII Startup scenario** : Not changed. Kept the same GT as previous [90X_mcRun2_startup_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_mcRun2_startup_v4) with JECs corresponding to 50ns.

## RunI data

   * **RunI HLT processing** : [90X_dataRun2_HLT_frozen_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_dataRun2_HLT_frozen_v3) as [90X_dataRun2_HLT_frozen_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_dataRun2_HLT_frozen_v2) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/90X_dataRun2_HLT_frozen_v3/90X_dataRun2_HLT_frozen_v2):
      * GEM RECO geometry
      * HCAL SiPM Parameter tag update

   * **RunI Offline processing** : [90X_dataRun2_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_dataRun2_v5) as [90X_dataRun2_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_dataRun2_v4) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/90X_dataRun2_v5/90X_dataRun2_v4):
      * Summer16 JECs
      * ESEE Intercalibration mentioned here  https://github.com/cms-sw/cmssw/pull/17219
      * GEM RECO geometry

## RunII data

   * **RunII HLTHI processing** : [90X_dataRun2_HLTHI_frozen_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_dataRun2_HLTHI_frozen_v3) as [90X_dataRun2_HLTHI_frozen_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_dataRun2_HLTHI_frozen_v2) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/90X_dataRun2_HLTHI_frozen_v3/90X_dataRun2_HLTHI_frozen_v2):
      * GEM RECO geometry
      * HCAL SiPM Parameter tag update

   * **RunII HLT relval processing** : [90X_dataRun2_HLT_relval_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_dataRun2_HLT_relval_v3) as [90X_dataRun2_HLT_relval_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_dataRun2_HLT_relval_v2) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/90X_dataRun2_HLT_relval_v3/90X_dataRun2_HLT_relval_v2):
      * GEM RECO geometry
      * HCAL SiPM Parameter tag update

   * **RunII Offline processing** : [90X_dataRun2_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_dataRun2_v5) as [90X_dataRun2_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_dataRun2_v4) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/90X_dataRun2_v5/90X_dataRun2_v4):
      * Summer16 JECs
      * ESEE Intercalibration mentioned here  https://github.com/cms-sw/cmssw/pull/17219
      * GEM RECO geometry

   * **RunII Offline relval processing** : [90X_dataRun2_relval_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_dataRun2_relval_v5) as [90X_dataRun2_relval_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_dataRun2_relval_v4) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/90X_dataRun2_relval_v5/90X_dataRun2_relval_v4):
      * Summer16 JECs
      * ESEE Intercalibration mentioned here  https://github.com/cms-sw/cmssw/pull/17219
      * GEM RECO geometry

   * **RunII Prompt processing** : [90X_dataRun2_PromptLike_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_dataRun2_PromptLike_v5) as [90X_dataRun2_PromptLike_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_dataRun2_PromptLike_v4) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/90X_dataRun2_PromptLike_v5/90X_dataRun2_PromptLike_v4):
      * Summer16 JECs
      * GEM RECO geometry
      * HCAL SiPM Parameter tag update

   * **RunI HLT processing** : [90X_dataRun2_HLT_frozen_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_dataRun2_HLT_frozen_v3) as [90X_dataRun2_HLT_frozen_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_dataRun2_HLT_frozen_v2) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/90X_dataRun2_HLT_frozen_v3/90X_dataRun2_HLT_frozen_v2):
      * GEM RECO geometry
      * HCAL SiPM Parameter tag update

## Upgrade

   * **PhaseII realistic scenario** : [90X_upgrade2023_realistic_v6](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_upgrade2023_realistic_v6) as [90X_upgrade2023_realistic_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_upgrade2023_realistic_v4) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/90X_upgrade2023_realistic_v6/90X_upgrade2023_realistic_v4):
      * Summer16 JECs

   * **PhaseI 2017 design scenario** : [90X_upgrade2017_design_IdealBS_v16](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_upgrade2017_design_IdealBS_v16) as [90X_upgrade2017_design_IdealBS_v15](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_upgrade2017_design_IdealBS_v15) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/90X_upgrade2017_design_IdealBS_v16/90X_upgrade2017_design_IdealBS_v15):
      * Summer16 JECs

   * **PhaseI 2017 realistic scenario** : [90X_upgrade2017_realistic_v16](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_upgrade2017_realistic_v16) as [90X_upgrade2017_realistic_v15](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_upgrade2017_realistic_v15) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/90X_upgrade2017_realistic_v16/90X_upgrade2017_realistic_v15):
      * Summer16 JECs

   * **PhaseI 2018 design scenario** : [90X_upgrade2018_design_IdealBS_v13](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_upgrade2018_design_IdealBS_v13) as [90X_upgrade2018_design_IdealBS_v12](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_upgrade2018_design_IdealBS_v12) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/90X_upgrade2018_design_IdealBS_v13/90X_upgrade2018_design_IdealBS_v12):
      * Summer16 JECs

   * **PhaseI 2018 realistic scenario** : [90X_upgrade2018_realistic_v13](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_upgrade2018_realistic_v13) as [90X_upgrade2018_realistic_v12](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_upgrade2018_realistic_v12) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/90X_upgrade2018_realistic_v13/90X_upgrade2018_realistic_v12):
      * Summer16 JECs

**Comment by franzoni** [comment]
hello @davidlange6 
would it be possible to have this PR merged ?
What should be provide for that to happen ?
( the chages are the same already merged in 91x https://github.com/cms-sw/cmssw/pull/17702 )

There are other AlCa changes we want to deploy now. Test would be cleaner and more meaningful if we could have an IB including these changes.

thanks!

**Comment by argiro** [comment]
Ecal also would be interested in knowing if we can move forward ..

**Comment by franzoni** [comment]
hello @davidlange6
would it be possible to have this PR merged ?
What should be provide for that to happen ?
( the chages are the same already merged in 91x #17702 )

**Comment by franzoni** [comment]
hello @davidlange6
would it be possible to have this PR merged ?
What should be provide for that to happen ?
( the changes are the same already merged in 91x #17702 )

**Comment by davidlange6** [comment]
actually I missed in 91x - why gem reco geometry in run1? Did we not manage to fix the code to understand if there are gems or not?
@ianna

**Comment by ianna** [comment]
@davidlange6 - it's in 2017 onwards. What makes you think it is in run 1?

**Comment by davidlange6** [comment]
I read the comments from @arunhep.EG:

	• RunI Offline processing : 90X_dataRun2_v5 as 90X_dataRun2_v4 with the following changes:

		• Summer16 JECs
		• ESEE Intercalibration mentioned here  #17219
		• GEM RECO geometry

**Comment by ianna** [comment]
@arunhep - I think, it is a mistake, GEM reco geometry should not be in Run 1. The tag was not there before:
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/90X_dataRun2_HLT_frozen_v2/90X_dataRun2_HLT_frozen_v3

**Comment by ianna** [comment]
@davidlange6 - It looks like it's the same GT queue for both run 1 and run 2. The tags in data queues have IOVs. @arunhep and @franzoni, please confirm.

**Comment by davidlange6** [comment]
that indeed makes sense - so what is the IOV for the GEM reco geometry addition?  Is it just the comment that is incorrect?

**Comment by arunhep** [comment]
@davidlange6 @ianna yes as you mentioned data GTs contain tags with multiple IOVs, but the GEM geometry tag has one only one IOV (1) covering actually whole history. Will this affect the Run-I workflows? Because if version of code relevant for Run-I is not consuming this record then it should not affect anything. @franzoni can you please confirm?

**Comment by davidlange6** [comment]
lets fix the IOV to match reality in any case...

**Comment by ianna** [comment]
@arunhep - standard run 1 code does not consume this record. GEM producer which needs it is enabled from 2017 era onwards.

**Comment by franzoni** [comment]
hello @ianna @david
the record not being consumed in the run1 standard sequences 
won't pose issues to the content / physics performance 

We concur, however, that an introducing 2 IOV's is the cleaner solution
Thanks for pointing this out!

@ianna can you provide the tag ~now / today ?
@davidlange6 we'll have to add a commit to both https://github.com/cms-sw/cmssw/pull/17886 and https://github.com/cms-sw/cmssw/pull/17905 also for other updates - we'll make sure we'll also replace the tag in the data GT to add the IOV. We'll use the same run number we've used for the HCAL phaseI 287446

Cheers and thanks,
@arunhep and Giovanni

**Comment by franzoni** [comment]
> lets fix the IOV to match reality in any case...

addressed [here](https://github.com/cms-sw/cmssw/pull/17886#issuecomment-286271239), given that https://github.com/cms-sw/cmssw/pull/17886 will supersede this PR

**Pull request closed without merging**
