### PR TITLE
EMTF DQM Module for CMSSW_8_1_X

### PR DESCRIPTION
**Pull request by swang373**
The corresponding CMSSW_8_1_X version of the follow pull request: cms-sw/cmssw#13513.

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1

**Comment by mulhearn** [comment]
+1

**Comment by davidlange6** [comment]
@smuzaffar @degano - could you add DataFormats/L1TMuon to the L1 category. Thanks!

**Comment by smuzaffar** [comment]
done, cms-bot should recognize it after this comment

**Pull request merged**
