### PR TITLE
HIN Jet DQM/Validation in 80X, with removing commented out code

### PR DESCRIPTION
**Pull request by rkunnawa**
Latest HIN Jet DQM/Validation modules for 80X. Useful to test background subtracted jets and its composite structures. 
Cheers
Raghav

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1
provided it passes the tests
as commented in #12194 some improvement to the readibility/maintainability of the code could be implemented.

**Comment by davidlange6** [comment]
+1

**Comment by davidlange6** [comment]
@rkunnawa @deguio - looks like this pr has introduced problems in the 80x IBs. Could you have a look (I'm told the underlying problem is dereferencing null MonitorElements)

https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc6_amd64_gcc493/CMSSW_8_0_X_2015-11-15-1100/pyRelValMatrixLogs/run/140.1_QCD_Pt_80_120_13_HI+QCD_Pt_80_120_13_HIINPUT+DIGIHI+RECOHI+HARVESTHI/step3_QCD_Pt_80_120_13_HI+QCD_Pt_80_120_13_HIINPUT+DIGIHI+RECOHI+HARVESTHI.log

**Comment by rkunnawa** [comment]
Hi @davidlange6 and @deguio, Let me take a look now and get back to you guys. thanks for letting me know.

**Comment by rkunnawa** [comment]
Hi @davidlange6, i found the unused monitoring elements and removed them. I pushed it into this commit, but i dont see it here. Should i submit a new PR containing the bug fix?

**Comment by davidlange6** [comment]
yes, since this PR is merged, you need to make a new PR.
Thanks!

**Comment by rkunnawa** [comment]
@davidlange6 
#12452 contains the necessary fix. 
thanks!

**Pull request merged**
