### PR TITLE
Introduce PCL-like workflows for SiStrip Lorentz Angle Monitoring (and potentially calibration)

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

This PR introduces a PCL-like workflow for SiStrip Lorentz Angle Monitoring (and potentially calibration), by using the `SiStripCalCosmics` dataset in input. The setup closesly resemble the one presented multiple times (see e.g. [this talk](https://indico.cern.ch/event/1271467/contributions/5350054/attachments/2624636/4538685/20230404_RWalsh_StripsCalibLA.pdf)) in which the hall mobility of the strips modules (only TIB and TOB for the time being, grouped in regions sharing same layer / module type) is estimated by fitting the distribution of the Strip cluster multiplicity as a function of the track grazing angle.  
The  `SiStripCalCosmics`  AlCaReco producer is added to the `ExpressCosmics` PD in `autoAlCa` while the new `PromptCalibProdSiStripLA` ALCAPrompt producer is introduced in several configuration files in  `Configuration/StandardSequences`  package. 

#### PR validation:

Run the following command:

```
cmsDriver.py testReAlCa -s ALCA:PromptCalibProdSiStripLA --conditions 130X_dataRun3_Prompt_v2 --scenario cosmics --data --era Run3_2023 --datatier ALCARECO --eventcontent ALCARECO --processName=ReAlCa -n 100000 --dasquery='file dataset=/Cosmics/Commissioning2023-SiStripCalCosmics-PromptReco-v1/ALCARECO run=364141' --nThreads=4 
```
followed by:

```
cmsDriver.py stepHarvest -s ALCAHARVEST:SiStripLA --conditions 130X_dataRun3_Prompt_v2 --scenario pp --data --era Run3_2023 -n -1 --filein file:PromptCalibProdSiStripLA.root
```

and obtained reasonable output DQM and db files.
Also run successfully the augmented relval wf 1005.0 (`runTheMatrix.py -l 1005.0 -t 4 -j 8 --ibeos`.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Not a backport, might be backported to 13.2.X for testing purposes during the 2023 HI data-taking

### CODE REVIEW

**Comment by mmusich** [comment]
test parameters:
   * workflow = 1005.0

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by tvami** [comment]
The new output looks reasonable
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-d1bd0b/34294/runTheMatrix-results/1005.0_RunCosmics2022F/DQM_V0001_R000360336__Express__PCLTest__ALCAPROMPT.root

@mmusich should this be converted to a full PR? I dont really have comments regarding the coding.

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by tvami** [comment]
+alca
 * tests pass, diffs in MsgLogger only
 * code in line with the PR desc

**Comment by mmusich** [comment]
@cms-sw/pdmv-l2 @cms-sw/upgrade-l2 do you have comments?

**Comment by sunilUIET** [comment]
+pdmv

**Comment by srimanob** [comment]
+Upgrade

**Comment by perrotta** [comment]
+1

**Pull request merged**
