### PR TITLE
Update 106X global tags in data and 2021/2023 MC [backport]

### PR DESCRIPTION
**Pull request by christopheralanwest**
#### PR description:

This PR updates offline, prompt-like and 2021 MC global tags in 10_6_X. It is a backport of PR #26773 to 10_6_X. 

#### PR validation:

See the description in PR #26773.

#### if this PR is a backport please specify the original PR:

This is a backport of PR #26773 to 10_6_X.

### CODE REVIEW

**Comment by christopheralanwest** [comment]
please test

**Comment by mmusich** [comment]
@christopheralanwest @tocheng is there any showstopper with this PR? 
Please clarify

**Comment by christopheralanwest** [comment]
please test

**Comment by christopheralanwest** [comment]
+1

Changes are seen and expected in comparison tests for

-- PPS quantities only in 2018 RECO (136.85)
-- 2017 data RECO (136.788)
-- 2021 (11624.0) and 2023 (20034.0, 21234.0, 27434.0, and 29034.0) MC

No changes are seen in other workflows.

**Comment by prebello** [comment]
@christopheralanwest  please what do you mean exactly? did you test all sort of relvals? we have already used 106X_upgrade2021_realistic_v4 in the 2021 relvals in 10-6-0. What sort of changes are expected? Thank you.

**Comment by fabiocos** [comment]
@christopheralanwest @franzoni @srimanob I understand that this is the PR we discussed at the PPD general meeting with the phase2 GT update for ECAL, am I correct? Am I also correct in understanding that it can be merged without any of the other further code addition and provide the correct results?

**Comment by christopheralanwest** [comment]
@fabiocos Yes, that is correct.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
