### PR TITLE
PhysicsTools/KinFitter: fix clang warnings about missing override keyword in ROOT macro

### PR DESCRIPTION
**Pull request by gartung**
Use ClassDefOverride macro instead of ClassDef macro so that override keyword is used where needed.

These warnings are removed after this change:
PhysicsTools/KinFitter/interface/TFitConstraintEp.h:59:3: warning: 'IsA' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
   ClassDef(TFitConstraintEp, 0)
  ^
PhysicsTools/KinFitter/interface/TFitConstraintM.h:56:3: warning: 'IsA' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
   ClassDef(TFitConstraintM, 0)
  ^
PhysicsTools/KinFitter/interface/TFitConstraintMGaus.h:42:3: warning: 'IsA' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
   ClassDef(TFitConstraintMGaus, 0)
  ^
PhysicsTools/KinFitter/interface/TFitParticleCart.h:38:3: warning: 'IsA' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
   ClassDef(TFitParticleCart, 0)
  ^
PhysicsTools/KinFitter/interface/TFitParticleEMomDev.h:40:3: warning: 'IsA' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
   ClassDef(TFitParticleEMomDev, 0)
  ^
PhysicsTools/KinFitter/interface/TFitParticleEScaledMomDev.h:35:3: warning: 'IsA' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
   ClassDef(TFitParticleEScaledMomDev, 0)
  ^
PhysicsTools/KinFitter/interface/TFitParticleESpher.h:38:3: warning: 'IsA' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
   ClassDef(TFitParticleESpher, 0)
  ^
PhysicsTools/KinFitter/interface/TFitParticleEtEtaPhi.h:38:3: warning: 'IsA' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
   ClassDef(TFitParticleEtEtaPhi, 0)
  ^

### CODE REVIEW

**Comment by gartung** [comment]
@Dr15Jones please test

**Comment by Dr15Jones** [comment]
Please test

**Comment by fabiocos** [comment]
@gartung @Dr15Jones @smuzaffar @mrodozov it looks like that this PR overlaps entirely with #22872, am I correct? So just one of them is needed

**Comment by smuzaffar** [comment]
@fabiocos, yes they overlap. Feel free to merge any of these.

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Pull request merged**
