### PR TITLE
Implementation of the option preexistingprimaryvertex

### PR DESCRIPTION
**Pull request by henriettepetersen**
Backport of #24761
I implemented the option preexistingprimaryvertex in the same style as the existing option preexistingoffline in the TkAlAllInOneTool for alignment @hroskes, @connorpa.

### CODE REVIEW

**Comment by tocheng** [comment]
@cmsbuild please test

**Comment by tocheng** [comment]
+1

**Comment by fabiocos** [comment]
@henriettepetersen @tocheng could you please clarify the purpose of this PR, now that the pp data taking is over?

**Comment by hroskes** [comment]
@fabiocos this is primarily for rerunning on data already taken, so that we can run the ultralegacy rereco.  The most important thing is we have to be able to run over all the 2018 data.  That said, if we can run on the data for the whole year using 104X, we don't necessarily need this.

**Comment by mmusich** [comment]
@fabiocos, when the PR was first submitted on Sep 28, pp data-taking was not over.
It's amazing it took almost two month to review such a simple PR...

**Comment by tocheng** [comment]
@hroskes @mmusich Thanks for the feedback. I don't know how it escaped from the eyes of ALCaDB. It is our miss.

**Comment by davidlange6** [comment]
Thats one 1 month:) - but it looks to be a delay from the responsible L2s - you might discuss with them

**Comment by fabiocos** [comment]
The master version was merged 3 weeks ago, for the rest I do not see anybody urged in the ORPs or here for the integration of this code. Having said that, the release to prepare the ultra-legacy is 10_4_X. Anyway, if there are short term activities that need to be done in 10_2_X and cannot be done in 10_4_X we could merge it, although I would like to understand what is the 10_4_X impediment.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
