### PR TITLE
MTD geometry: add BTL topology to MTDTopology, reorganize dependencies

### PR DESCRIPTION
**Pull request by fabiocos**
#### PR description:

This PR updates the ```MTDTopology``` class by adding a BTL part, associating an ```iphi``` and ```ieta``` index to sensor modules ```DetId``` of ```MTDGeometry```, using the same ordering. In order to avoid circular dependencies, ```MTDTopology``` is moved from ```MTDNumberingBuilder```, where it was for historical reasons (cloning the tracker geometry structure in old days) to the more appropriate ```MTDGeometryBuilder```. The ```_cfi.py``` fragment is kept anyway in the original location (through a python import) to prevent disruption of scores of existing configuration files. 

This is the opportunity to:

- add a test of BTL navigation in ```RecoMTD/DetLayers``` that couples both ```MTDTopology``` and ```MTDTrayBarrelLayer``` navigation at the same time (in parallel to the existing test for ETL navigation in tracking).
- clean some records definition and dependencies;
- remove part of codes referring to the obsolete v1 BTL geometry, no more supported and present in CMSSW since this summer;
- reorder the ```MTDGeometry``` entries running their phi from -pi to pi, as the CMS default used in the ```RecoMTD/DetLayers``` construction of BTL, instead of the present order from 0 to 2pi;

In order to keep the unit tests stable at this step, the last point is temporarily undone, and it will be separately proposed together a complete rewriting of the BTL numbering scheme, to be based on top of this PR, where all data references will have anyway to be changed. In this way we reduce the number of space expensive test reference updates.

#### PR validation:

Code compiles, runs, unit tests are at present providing the expected output, and the yet not used ```TestBTLNavigation``` has the expected behaviour:

```

Test of BTL navigation 



BTL layer   18 at z =           0.00 rods =            108 dets =          10368

Tray    1
 MTDDetTray at  (-115.030,-13.011,0.000)  L/W/T   :         496.07 /           5.47 /           0.38 normal phi =           0.17
    1 BTLDetId 1653824400 iphi/ieta =    1 /    1 side =    0 RU =    2 mod =   22 pos =              (-115.03,-13.01,-245.48) 
...............phishift=  iphi/ieta =  108 /    1  -1 side =    0 RU =    2 mod =   24 pos =              (-115.03,13.01,-245.48) 
...............phishift=  iphi/ieta =    2 /    1   1 side =    0 RU =    2 mod =   23 pos =              (-114.03,-19.03,-245.48) 
...............etashift= -1 out of range
...............etashift=  iphi/ieta =    1 /    2   1 side =    0 RU =    2 mod =   19 pos =              (-115.03,-13.01,-240.32) 
    2 BTLDetId 1653821328 iphi/ieta =    1 /    2 side =    0 RU =    2 mod =   19 pos =              (-115.03,-13.01,-240.32) 
...............phishift=  iphi/ieta =  108 /    2  -1 side =    0 RU =    2 mod =   21 pos =              (-115.03,13.01,-240.32) 
...............phishift=  iphi/ieta =    2 /    2   1 side =    0 RU =    2 mod =   20 pos =              (-114.03,-19.03,-240.32) 
...............etashift=  iphi/ieta =    1 /    1  -1 side =    0 RU =    2 mod =   22 pos =              (-115.03,-13.01,-245.48) 
...............etashift=  iphi/ieta =    1 /    3   1 side =    0 RU =    2 mod =   16 pos =              (-115.03,-13.01,-235.16) 
    3 BTLDetId 1653818256 iphi/ieta =    1 /    3 side =    0 RU =    2 mod =   16 pos =              (-115.03,-13.01,-235.16) 
...............phishift=  iphi/ieta =  108 /    3  -1 side =    0 RU =    2 mod =   18 pos =              (-115.03,13.01,-235.16) 
...............phishift=  iphi/ieta =    2 /    3   1 side =    0 RU =    2 mod =   17 pos =              (-114.03,-19.03,-235.16) 
...............etashift=  iphi/ieta =    1 /    2  -1 side =    0 RU =    2 mod =   19 pos =              (-115.03,-13.01,-240.32) 
...............etashift=  iphi/ieta =    1 /    4   1 side =    0 RU =    2 mod =   13 pos =              (-115.03,-13.01,-230.00) 
    4 BTLDetId 1653815184 iphi/ieta =    1 /    4 side =    0 RU =    2 mod =   13 pos =              (-115.03,-13.01,-230.00) 
...............phishift=  iphi/ieta =  108 /    4  -1 side =    0 RU =    2 mod =   15 pos =              (-115.03,13.01,-230.00) 
...............phishift=  iphi/ieta =    2 /    4   1 side =    0 RU =    2 mod =   14 pos =              (-114.03,-19.03,-230.00) 
...............etashift=  iphi/ieta =    1 /    3  -1 side =    0 RU =    2 mod =   16 pos =              (-115.03,-13.01,-235.16) 
...............etashift=  iphi/ieta =    1 /    5   1 side =    0 RU =    2 mod =   10 pos =              (-115.03,-13.01,-224.84) 
(...)
10366 BTLDetId 1657949072 iphi/ieta =  108 /   94 side =    1 RU =    2 mod =   18 pos =              (-115.03,13.01,235.16) 
...............phishift=  iphi/ieta =  107 /   94  -1 side =    1 RU =    2 mod =   17 pos =              (-114.03,19.03,235.16) 
...............phishift=  iphi/ieta =    1 /   94   1 side =    1 RU =    2 mod =   16 pos =              (-115.03,-13.01,235.16) 
...............etashift=  iphi/ieta =  108 /   93  -1 side =    1 RU =    2 mod =   15 pos =              (-115.03,13.01,230.00) 
...............etashift=  iphi/ieta =  108 /   95   1 side =    1 RU =    2 mod =   21 pos =              (-115.03,13.01,240.32) 
10367 BTLDetId 1657952144 iphi/ieta =  108 /   95 side =    1 RU =    2 mod =   21 pos =              (-115.03,13.01,240.32) 
...............phishift=  iphi/ieta =  107 /   95  -1 side =    1 RU =    2 mod =   20 pos =              (-114.03,19.03,240.32) 
...............phishift=  iphi/ieta =    1 /   95   1 side =    1 RU =    2 mod =   19 pos =              (-115.03,-13.01,240.32) 
...............etashift=  iphi/ieta =  108 /   94  -1 side =    1 RU =    2 mod =   18 pos =              (-115.03,13.01,235.16) 
...............etashift=  iphi/ieta =  108 /   96   1 side =    1 RU =    2 mod =   24 pos =              (-115.03,13.01,245.48) 
10368 BTLDetId 1657955216 iphi/ieta =  108 /   96 side =    1 RU =    2 mod =   24 pos =              (-115.03,13.01,245.48) 
...............phishift=  iphi/ieta =  107 /   96  -1 side =    1 RU =    2 mod =   23 pos =              (-114.03,19.03,245.48) 
...............phishift=  iphi/ieta =    1 /   96   1 side =    1 RU =    2 mod =   22 pos =              (-115.03,-13.01,245.48) 
...............etashift=  iphi/ieta =  108 /   95  -1 side =    1 RU =    2 mod =   21 pos =              (-115.03,13.01,240.32) 
...............etashift=  1 out of range
```

### CODE REVIEW

**Comment by fabiocos** [comment]
type mtd

**Comment by fabiocos** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by Moanwar** [comment]
+Upgrade

**Comment by antoniovagnerini** [comment]
+dqm

**Comment by mandrenguyen** [comment]
+1

**Comment by smuzaffar** [comment]
@fabiocos , this PR is breaking debug IBs and also clang static checks ( which were failed during PR tests too )[a]. Can you please  provide a fix as soon as possible

https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-3504b6/43377/llvm-analysis/runStaticChecks.log
```
>> Analyzing  src/Geometry/Records/src/PEcalPreshowerRcd.cc 
src/Geometry/MTDNumberingBuilder/plugins/DDCmsMTDConstruction.cc:211:90: error: use of undeclared identifier 'makempiToppi'
  211 |           << " " << it->type() << " " << it->translation().z() << " " << convertRadToDeg(makempiToppi(it->phi()))
      |                                                                                          ^
src/Geometry/MTDNumberingBuilder/plugins/DDCmsMTDConstruction.cc:365:90: error: use of undeclared identifier 'makempiToppi'
  365 |           << " " << it->type() << " " << it->translation().z() << " " << convertRadToDeg(makempiToppi(it->phi()))
      |                                                                                          ^
2 errors generated.
```

**Pull request merged**
