### PR TITLE
Clean duplicate code in HLTriggerOffline/Muon

### PR DESCRIPTION
**Pull request by JanFSchulte**
This PR adresses issue https://github.com/cms-sw/cmssw/issues/37290 and removes duplicate code from `HLTriggerOffline/Muon`, where the propagation of muon tracks from the IP to the muon system and their matching to L1 muons was re-implemented for use in offline DQM (classes `PropagateToMuon` and `L1MuonMatcherAlgo`). The code providing the same functionality from `MuonAnalysis/MuonAssociators` is used instead. 

Because `HLTMuonValidtor` creates `HLTMuonPlotter` objects, which in turn consume ESTokens, outside it's constructor (see https://github.com/cms-sw/cmssw/blob/master/HLTriggerOffline/Muon/src/HLTMuonValidator.cc#L165), these token have to be fed down the chain of constructors. The machinery for this was added to the implementation of the propagation and matching code in `HLTriggerOffline/Muon` and has now been integrated into the one in  `MuonAnalysis/MuonAssociators` so that all applications of this code can use the same implementation. 

#### PR validation:

No changes in results expected. Code passes all unit tests (even though I think the packages in question might not have any) and all tests run with `runTheMatrix.py -l limited -i all --ibeos` path without failure.

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by missirol** [comment]
I'm a bit uneasy about complicating several HLT producers to comply with the (arguably convoluted) logic of one DQM client.

I tried to implement an alternative solution in #37367, which does not touch HLT packages.

**Comment by missirol** [comment]
@JanFSchulte , the tests from the alternative PR (#37367) came back clean. I would personally prefer that PR to this one (no static functions to move tokens around, no changes to HLT, no changes to `PropagateToMuon*` other than templating). What do you think?

**Comment by JanFSchulte** [comment]
@missirol I agree, your solution is much cleaner. I'll close here.

**Comment by missirol** [comment]
Thanks, @JanFSchulte .

**Pull request closed without merging**
