### PR TITLE
Change devel build to use pybind11 for cmsRun

### PR DESCRIPTION
**Pull request by davidlange6**

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
please abort

**Comment by davidlange6** [comment]
sorry - I realize there is no devel build from which this can be tested yet

**Comment by Dr15Jones** [comment]
Now that we have the argv problem solved, the most recent DEVEL build seems to be showing there is  a conversion problem with strings. The unit tests failures in FWCore/Integration, IOPool/Input and GeneratorInterface/LHEInterface all stem from a conversion error. These errors are

```
----- Begin Fatal Exception 23-Feb-2019 04:32:42 CET-----------------------
An exception of category 'ConfigFileReadError' occurred while
   [0] Processing the python configuration file named /build/cmsbld/jenkins/workspace/ib-run-qa/CMSSW_10_6_DEVEL_X_2019-02-22-2300/src/FWCore/Integration/test/testEDAliasAnalyze_cfg.py
Exception Message:
 unknown python problem occurred.
TypeError: wrong types (<type 'unicode'>,<type 'unicode'>,<type 'unicode'>,<type 'unicode'>,<type 'unicode'>,<type 'unicode'>,<type 'unicode'>,<type 'unicode'>,<type 'unicode'>,<type 'unicode'>,<type 'unicode'>,<type 'unicode'>,<type 'unicode'>,<type 'unicode'>,<type 'unicode'>,<type 'unicode'>,<type 'unicode'>,<type 'unicode'>,<type 'unicode'>,<type 'unicode'>,<type 'unicode'>,<type 'unicode'>,<type 'unicode'>,<type 'unicode'>,<type 'unicode'>) added to <class 'FWCore.ParameterSet.Types.vstring'>

At:
  /cvmfs/cms-ib.cern.ch/nweek-02564/slc7_amd64_gcc700/cms/cmssw-patch/CMSSW_10_6_DEVEL_X_2019-02-22-2300/python/FWCore/ParameterSet/Mixins.py(551): __init__
  /cvmfs/cms-ib.cern.ch/nweek-02564/slc7_amd64_gcc700/cms/cmssw-patch/CMSSW_10_6_DEVEL_X_2019-02-22-2300/python/FWCore/ParameterSet/Mixins.py(601): __init__
  /cvmfs/cms-ib.cern.ch/nweek-02564/slc7_amd64_gcc700/cms/cmssw-patch/CMSSW_10_6_DEVEL_X_2019-02-22-2300/python/FWCore/ParameterSet/Types.py(777): __init__
  /cvmfs/cms-ib.cern.ch/nweek-02564/slc7_amd64_gcc700/cms/cmssw-patch/CMSSW_10_6_DEVEL_X_2019-02-22-2300/python/FWCore/ParameterSet/Types.py(26): __call__
  /build/cmsbld/jenkins/workspace/ib-run-qa/CMSSW_10_6_DEVEL_X_2019-02-22-2300/src/FWCore/Integration/test/testEDAliasAnalyze_cfg.py(7): <module>
  <string>(3): <module>

----- End Fatal Exception -------------------------------------------------
Failure cmsRun testEDAliasAnalyze_cfg.py testEDAliasTask.root: status 90
```
```
----- Begin Fatal Exception 23-Feb-2019 04:32:42 CET-----------------------
An exception of category 'ConfigFileReadError' occurred while
   [0] Processing the python configuration file named /build/cmsbld/jenkins/workspace/ib-run-qa/CMSSW_10_6_DEVEL_X_2019-02-22-2300/src/FWCore/Integration/test/testEDAliasAnalyze_cfg.py
Exception Message:
 unknown python problem occurred.
TypeError: wrong types (<type 'unicode'>,<type 'unicode'>,<type 'unicode'>,<type 'unicode'>,<type 'unicode'>,<type 'unicode'>,<type 'unicode'>,<type 'unicode'>,<type 'unicode'>,<type 'unicode'>,<type 'unicode'>,<type 'unicode'>,<type 'unicode'>,<type 'unicode'>,<type 'unicode'>,<type 'unicode'>,<type 'unicode'>,<type 'unicode'>,<type 'unicode'>,<type 'unicode'>,<type 'unicode'>,<type 'unicode'>,<type 'unicode'>,<type 'unicode'>,<type 'unicode'>) added to <class 'FWCore.ParameterSet.Types.vstring'>

At:
  /cvmfs/cms-ib.cern.ch/nweek-02564/slc7_amd64_gcc700/cms/cmssw-patch/CMSSW_10_6_DEVEL_X_2019-02-22-2300/python/FWCore/ParameterSet/Mixins.py(551): __init__
  /cvmfs/cms-ib.cern.ch/nweek-02564/slc7_amd64_gcc700/cms/cmssw-patch/CMSSW_10_6_DEVEL_X_2019-02-22-2300/python/FWCore/ParameterSet/Mixins.py(601): __init__
  /cvmfs/cms-ib.cern.ch/nweek-02564/slc7_amd64_gcc700/cms/cmssw-patch/CMSSW_10_6_DEVEL_X_2019-02-22-2300/python/FWCore/ParameterSet/Types.py(777): __init__
  /cvmfs/cms-ib.cern.ch/nweek-02564/slc7_amd64_gcc700/cms/cmssw-patch/CMSSW_10_6_DEVEL_X_2019-02-22-2300/python/FWCore/ParameterSet/Types.py(26): __call__
  /build/cmsbld/jenkins/workspace/ib-run-qa/CMSSW_10_6_DEVEL_X_2019-02-22-2300/src/FWCore/Integration/test/testEDAliasAnalyze_cfg.py(7): <module>
  <string>(3): <module>

----- End Fatal Exception -------------------------------------------------
Failure cmsRun testEDAliasAnalyze_cfg.py testEDAliasTask.root: status 90
```

```
----- Begin Fatal Exception 23-Feb-2019 04:33:53 CET-----------------------
An exception of category 'ConfigFileReadError' occurred while
   [0] Processing the python configuration file named /build/cmsbld/jenkins/workspace/ib-run-qa/CMSSW_10_6_DEVEL_X_2019-02-22-2300/src/GeneratorInterface/LHEInterface/test/testMerge_cfg.py
Exception Message:
 unknown python problem occurred.
TypeError: wrong types (<type 'unicode'>,<type 'unicode'>) added to <class 'FWCore.ParameterSet.Types.vstring'>

At:
  /cvmfs/cms-ib.cern.ch/nweek-02564/slc7_amd64_gcc700/cms/cmssw-patch/CMSSW_10_6_DEVEL_X_2019-02-22-2300/python/FWCore/ParameterSet/Mixins.py(551): __init__
  /cvmfs/cms-ib.cern.ch/nweek-02564/slc7_amd64_gcc700/cms/cmssw-patch/CMSSW_10_6_DEVEL_X_2019-02-22-2300/python/FWCore/ParameterSet/Mixins.py(601): __init__
  /cvmfs/cms-ib.cern.ch/nweek-02564/slc7_amd64_gcc700/cms/cmssw-patch/CMSSW_10_6_DEVEL_X_2019-02-22-2300/python/FWCore/ParameterSet/Types.py(777): __init__
  /cvmfs/cms-ib.cern.ch/nweek-02564/slc7_amd64_gcc700/cms/cmssw-patch/CMSSW_10_6_DEVEL_X_2019-02-22-2300/python/FWCore/ParameterSet/Types.py(26): __call__
  /build/cmsbld/jenkins/workspace/ib-run-qa/CMSSW_10_6_DEVEL_X_2019-02-22-2300/src/GeneratorInterface/LHEInterface/test/testMerge_cfg.py(13): <module>
  <string>(3): <module>

----- End Fatal Exception -------------------------------------------------
Failure using /build/cmsbld/jenkins/workspace/ib-run-qa/CMSSW_10_6_DEVEL_X_2019-02-22-2300/src/GeneratorInterface/LHEInterface/test/testMerge_cfg.py: status 90
```

```
----- Begin Fatal Exception 23-Feb-2019 04:42:04 CET-----------------------
An exception of category 'ConfigFileReadError' occurred while
   [0] Processing the python configuration file named /build/cmsbld/jenkins/workspace/ib-run-qa/CMSSW_10_6_DEVEL_X_2019-02-22-2300/src/IOPool/Input/test/PrePoolInputTest_cfg.py
Exception Message:
 unknown python problem occurred.
ValueError: PoolInputTest.root is not a valid <class 'FWCore.ParameterSet.Types.string'>

At:
  /cvmfs/cms-ib.cern.ch/nweek-02564/slc7_amd64_gcc700/cms/cmssw-patch/CMSSW_10_6_DEVEL_X_2019-02-22-2300/python/FWCore/ParameterSet/Mixins.py(91): __init__
  /cvmfs/cms-ib.cern.ch/nweek-02564/slc7_amd64_gcc700/cms/cmssw-patch/CMSSW_10_6_DEVEL_X_2019-02-22-2300/python/FWCore/ParameterSet/Types.py(156): __init__
  /cvmfs/cms-ib.cern.ch/nweek-02564/slc7_amd64_gcc700/cms/cmssw-patch/CMSSW_10_6_DEVEL_X_2019-02-22-2300/python/FWCore/ParameterSet/Types.py(26): __call__
  /build/cmsbld/jenkins/workspace/ib-run-qa/CMSSW_10_6_DEVEL_X_2019-02-22-2300/src/IOPool/Input/test/PrePoolInputTest_cfg.py(19): <module>
  <string>(3): <module>

----- End Fatal Exception -------------------------------------------------
Failure using PrePoolInputTest_cfg.py: status 90
```

**Comment by davidlange6** [comment]
Right- its only puzzling that the errors are so isolated... I'm looking at it (most likely tomorrow/Monday in reality...)

**Comment by davidlange6** [comment]
actually its probably another case of (different..) argc / argv errors.

**Pull request merged**
