### PR TITLE
Hcal DQM remove OneLumiEDAnalyzer

### PR DESCRIPTION
**Pull request by lwang046**
A fix to Hcal related legacy modules raised in issues #25090.

Passed local `runTheMatrix.py -l limited -i all --ibeos` test without fails.

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by abdoulline** [comment]
@DryRun  @lwang046 
Could you, please, remind me/us  whether DigiPhase1Task is now obsolete (and why)? - To possibly just exclude it.

**Comment by lwang046** [comment]
> @DryRun @lwang046
> Could you, please, remind me/us whether DigiPhase1Task is now obsolete (and why)? - To possibly just exclude it.

Just made a new commit to fix the monitoring elements changes from DigiPhase1Task module. For future dev purpose, maybe @DryRun could comment if this module is obsolete or not?

**Comment by DryRun** [comment]
Dear all, 

Indeed, DigiPhase1Task should be obsolete by now. It was intended to compare "legacy" vs. Phase-1 digis in the early days of the Phase-1 upgrade. The plots it contains should be fully represented in DigiTask.

Cheers,
David

**Comment by jfernan2** [comment]
Thanks @DryRun 
So, then I'd suggest removing the module to avoid future misunderstandings.

**Comment by jfernan2** [comment]
@lwang046  I am afraid that just renaming the files won't work. The hcal/hcal2 modules are around in some other central places, e.g.:
https://github.com/cms-sw/cmssw/search?q=hcal2&unscoped_q=hcal2

**Comment by lwang046** [comment]
Hi @jfernan2, from my understanding the hcal/hcal2 clients in the DQM/Integration folder are for online use only. While the first case where hcal/hcal2 appeared in DQMOffline folder were meant for offline steps, they are different from the previous ones and works independently. The second case where the client names appeared in the DQM/Integration/test/BuildFile.xml indeed needs to be changed,  but it seems I don't have access right to modify this BuildFile. And the last case where Hcal2 appeared in the hcal2_* client itself is a name string of a root file or folder where the plots were stored.

**Comment by jfernan2** [comment]
Hi @lwang046 I agree with you, however the folder names defined in both Online clients (hcal/hcal2) are remaining with this PR, so if you rename the files, we should do the same in the folders they create for coherence
On the other hand, I don't understand why you cannot change the BuildFile.xml since it is in the same folder/package.
Concerning Offline, despite they are indepent to this change, the same names stick and call very same file names:

**Comment by lwang046** [comment]
Hi @jfernan2 thanks for the quick reply,
> Hi @lwang046 I agree with you, however the folder names defined in both Online clients (hcal/hcal2) are remaining with this PR, so if you rename the files, we should do the same in the folders they create for coherence
will change the name string too
> On the other hand, I don't understand why you cannot change the BuildFile.xml since it is in the same folder/package.
here when I do git cms-addpkg DQM/Integration, there is no such test/ folder in the DQM/Integration/, so I thought it has something todo with access? I'm working under CMSSW_11_1_X_2020-04-27-1100
> Concerning Offline, despite they are indepent to this change, the same names stick and call very same file names:
> 
> https://github.com/cms-sw/cmssw/blob/17e6869c6ea494367cc3a95af59cef266f20f1b2/DQMOffline/Configuration/python/DQMOffline_cff.py#L40-L42
My apologies I didn't quite understand this one, do you mean the `hcalOfflineSourceSequence` and `HcalDQMOfflineSequence` still call/were called by the DQM/Integration/python/clients/hcal(2)_* clients?

**Comment by jfernan2** [comment]
Thanks a lot @lwang046 

> 
> here when I do `git cms-addpkg DQM/Integration`, there is no such test/ folder in the DQM/Integration/, so I thought it has something todo with access? I'm working under CMSSW_11_1_X_2020-04-27-1100

You need an extra: 
git cms-addpkg DQM/Integration/test

> 
> > Concerning Offline, despite they are indepent to this change, the same names stick and call very same file names:
> > https://github.com/cms-sw/cmssw/blob/17e6869c6ea494367cc3a95af59cef266f20f1b2/DQMOffline/Configuration/python/DQMOffline_cff.py#L40-L42
> 
> My apologies I didn't quite understand this one, do you mean the `hcalOfflineSourceSequence` and `HcalDQMOfflineSequence` still call/were called by the DQM/Integration/python/clients/hcal(2)_* clients?

No, I meant that the same nomenclature is being used in Offline, but this can be for another PR since changes will be clearly visible in the github tests there if we make worng labeling, so let's decouple it.
Thank you

**Comment by lwang046** [comment]
Hi  @andrius-k, @kmaeshima, @schneiml, @cmsbuild, @jfernan2, @fioriNTU, the code checks of the last commit was rejected but when I do `curl https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-29544/14871/code-checks.patch | patch -p1` or `run scram build code-checks` nothing happened. I have never seen this before, may I ask how shall I proceed please?

**Comment by andrius-k** [comment]
Hi @lwang046, so the issue is that you committing 3 files inside `DQM/Integration/test/` directory that already exist in the master branch and you are getting a merge conflict. Github, just above the comment text box is reporting this fact as well. What happens is that code checks merge your PR on top of the master and conflicts are prepared to be solved by git by adding special lines that are of course invalid code.

I think the best solution right now would be do get the lates changes of the 2 conflicting files from the master branch to you local checkout and commit only their changes (if you want to make them). Let me know if you need any help doing so.

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
@lwang046  I understand that DigiTask contains the old/reduced DigiPhase1Task. 
However I see for Phase2 in addition a new DigiRunHarvesting folder created inside Hcal folder. But I don't see to find out where it does come from, I guess it is coming from DigiTask downstream since now it is not a copyAndExclude but toModify. It contains 47 MEs, it would be good to understand them.
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_11_1_X_2020-04-28-1100+6725ce/36042/dqm-histo-comparison-summary.html
Any idea?

**Comment by jfernan2** [comment]
On a totally different subject: the changes affecting to Online DQM are not and cannot be tested here in github. And we (DQM) cannot test them since P5 is down at present. So, I understand you have made some independent validation that the plots including per LS/events are remaining unchanged.
Thanks

**Comment by jfernan2** [comment]
Related to my last comment: the reportSummaryMap which contains info vs LS changes already at Offline
https://tinyurl.com/ycxjwe6a

**Comment by jfernan2** [comment]
Another strange fact is double number of processed events in non-Phase2 workflows, eg.:

https://tinyurl.com/y9r2un8q

**Comment by lwang046** [comment]
> @lwang046 I understand that DigiTask contains the old/reduced DigiPhase1Task.
> However I see for Phase2 in addition a new DigiRunHarvesting folder created inside Hcal folder. But I don't see to find out where it does come from, I guess it is coming from DigiTask downstream since now it is not a copyAndExclude but toModify. It contains 47 MEs, it would be good to understand them.
> https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_11_1_X_2020-04-28-1100+6725ce/36042/dqm-histo-comparison-summary.html
> Any idea?

Hi @jfernan2, the DigiRunHarvesting folder comes from here. Previously with the DigiPhase1Task the std::find(_summaryList.begin(), _summaryList.end(), fDigi) condition was not fulfilled so there was no such folder, but now it's there.

**Comment by lwang046** [comment]
> Another strange fact is double number of processed events in non-Phase2 workflows, eg.:
> 
> https://tinyurl.com/y9r2un8q

Forgiving me for a stupid question, if the same ME was booked twice: https://github.com/cms-sw/cmssw/blob/7bf830bbb5f57be6673227056342a5adf8c88567/DQM/HcalTasks/plugins/DigiTask.cc#L789-L790 & https://github.com/cms-sw/cmssw/blob/7bf830bbb5f57be6673227056342a5adf8c88567/DQM/HcalTasks/plugins/DigiPhase1Task.cc#L297-L298, would the previously filled one be cleared or be added? Also I thought for this workflow there were only 10 events generated in the cmdlog? If these 2 wonderments are correct, that will explain why there were 20 events before but 10 events now?

**Comment by lwang046** [comment]
> On a totally different subject: the changes affecting to Online DQM are not and cannot be tested here in github. And we (DQM) cannot test them since P5 is down at present. So, I understand you have made some independent validation that the plots including per LS/events are remaining unchanged.
> Thanks

>Related to my last comment: the reportSummaryMap which contains info vs LS changes already at Offline https://tinyurl.com/ycxjwe6a

@jfernan2 My apologies I failed to understand your comments here, may I ask which checks you were looking for?

**Comment by jfernan2** [comment]
Thanks a lot @lwang046 
I understand then that, the different plot on:
https://tinyurl.com/ycxjwe6a
which is related to the tests I was proposing for Online DQM, it is fine to have the digi values in red now.
About extra Online DQM tests, let me explain: with this PR, the way the plots which have information vs time/LS are filled changes, so the plots content may be differet too. The link above is the only one which seems to change in Offline, but it is understood since Digis are now checked, assuming red color is expected.

Hence ,in Online DQM you should probably test the changes running standalone the two clients
DQM/Integration/python/clients/hcalreco_dqm_sourceclient-live_cfg.py
DQM/Integration/python/clients/hcal_dqm_sourceclient-live_cfg.py
to avoid surprises once we turn on the DQM Online Clients at P5
Thank you very much

**Comment by jfernan2** [comment]
+1
After private succesful tests for Online DQM output

**Comment by abdoulline** [comment]
@jfernan2  thank you very much for your help!
@lwang046  congrats for your first major contribution to HCAL Online DQM!

**Comment by silviodonato** [comment]
+1

**Comment by makortel** [comment]
It seems that this PR might have caused 3 workflows to segfault in HARVESTING step, see https://github.com/cms-sw/cmssw/issues/29605.

**Comment by schneiml** [comment]
Hi @lwang046, to have this clarified:

> Forgiving me for a stupid question, if the same ME was booked twice:

If you book the same name twice, you get *the same object* in both places. If you then call fill from two modules, you see all the data in one histogram.

That is how the "Number of Events" histograms showed double number of events. This behavior changed recently (in the new DQMStore work, merged in 11_1), and these plots were among the few changes noticed there.

**Comment by jfernan2** [comment]
Resolves #25090
(Partially)

**Pull request merged**
