### PR TITLE
Phase2-hgx309A Add a method to extract orientation indexfrom placement index of HGCal cells/wafers

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Add a method to extract orientation indexfrom placement index of HGCal cells/wafers

#### PR validation:

Use the runTheMatrix test workflows 

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cvuosalo @civanch @srimanob Please review this code and sign it in view of proceeding to the next step

**Comment by civanch** [comment]
+1

**Comment by bsunanda** [comment]
@srimanob Please sign this. Waiting for the next step

**Comment by srimanob** [comment]
+Upgrade

Technical PR to add the method for extracting the orientation of HGCal. No change is expected with the PR test.

**Comment by qliphy** [comment]
+1

**Pull request merged**
