### PR TITLE
protect DAClusterizerInZ_vect.cc from a too small value backport of #16761

### PR DESCRIPTION
**Pull request by VinInn**

### CODE REVIEW

**Comment by VinInn** [comment]
@cmsbuild

**Comment by VinInn** [comment]
bugfix

**Comment by VinInn** [comment]
backport

**Comment by slava77** [comment]
given that this affects both MC and data, this PR will not go in 80X until after legacy rereco campaign.
(late 2017?)

**Comment by VinInn** [comment]
@abaty

**Comment by slava77** [comment]
For 80X I could accept this more easily if the change is configurable.

**Comment by mandrenguyen** [comment]
@slava77 There appears to be a desire to get this in as quickly as possible.  This affects some of the pA triggers that are based on tracking.  @kkrajczar may comment further.

**Comment by slava77** [comment]
On 11/25/16 6:58 AM, mandrenguyen wrote:
> @slava77 <https://github.com/slava77> There appears to be a desire to
> get this in as quickly as possible. This affects some of the pA triggers
> that are based on tracking. @kkrajczar <https://github.com/kkrajczar>
> may comment further.

Is this needed in prompt?
If so, then a new processing version or era is practical.

Do you gain or lose by having the first data with this bug and the
second part after beam reversal with it fixed?
It seems more practical to have a consistent picture and then reprocess
everything relevant with the fix in place.

**Comment by mandrenguyen** [comment]
@slava77 I defer to the heavy ion conveners and run coordination on the issue of when to deploy this, which is currently being discussed.

**Comment by slava77** [comment]
On 11/25/16 7:24 AM, mandrenguyen wrote:
> @slava77 <https://github.com/slava77> I defer to the heavy ion conveners
> and run coordination on the issue of when to deploy this, which is
> currently being discussed.

To deploy this for HI we need a configurable fix.
This can not change pp reco for ongoing MC campaign (I have in mind
whatever extensions may need to happen and use the latest 80X release).

**Comment by slava77** [comment]
ping

we need a configurable solution for HI needs in order to not violate the change policy in 80X.
Looking at the code, the constructor interface allows to do this somewhat easily.

**Comment by abaty** [comment]
HI Slava,

The decision among the conveners and run coordinators is to not apply this online or in the prompt reco,.  We will instead pick it up during the next data reprocessing (whenever that may be).

-Austin

**Comment by slava77** [comment]
On 12/2/16 8:35 AM, abaty wrote:
> HI Slava,
> 
> The decision among the conveners and run coordinators is to not apply
> this online or in the prompt reco,. We will instead pick it up during
> the next data reprocessing (whenever that may be).
> 
> -Austin

Hi Austin,

Your description is in line with what was discussed at the ORP on Tuesday.
My comment is to match these needs.

It's not about prompt reco or current online.

This change affects most of the pp events, even though the change is
effectively small in most of the relevant phase space.
80X physics performance can not change for the standard workflows
with default configurations, until evolution is allowed either by
exception or rescoping the release.



		--slava

**Comment by slava77** [comment]
ping
should we expect an update here?

**Comment by mandrenguyen** [comment]
@slava77 I suggest we close this and come back to it if there ends up being an 80X reprocessing.

**Comment by slava77** [comment]
-1

after https://github.com/cms-sw/cmssw/pull/16764#issuecomment-266693100

**Pull request closed without merging**
