### PR TITLE
Add missing library in CalibTracker/SiStripCommon

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

Need to link with DataFormats/Scalers in order for UBSAN to work.

#### PR validation:

Compiles and links with CMSSW_11_0_UBSAN_X_2019-06-18-1100 IB.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by fabiocos** [comment]
@tocheng @pohsun @christopheralanwest this PR looks trivial to me, I will integrate it in next IB, please have a look at it

**Comment by christopheralanwest** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
