### PR TITLE
Run2-hcx154 Make correct usage of HCAL geometry

### PR DESCRIPTION
**Pull request by bsunanda**

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@perrotta @slava77 Please review and approve

**Comment by ttrk** [comment]
@bsunanda In the new version, the object is initialized with the Barrel SubDetector information. See
https://github.com/cms-sw/cmssw/pull/20443/files#diff-0f5e0006e31e12f2de8eedbabba5f532R38

Will it pick up the correct geometry for HCAL Endcap ? The workflow comparisons look ok, I still wanted to make sure.

**Comment by bsunanda** [comment]
@ttrk For Hcal we have one geometry which covers barrel, endcap, outer and forward. The requirement to find a geometry needs Det and SubDet - so Hcal and HcalBarrel is a good choice

**Comment by perrotta** [comment]
@bsunanda 

To see the effects of this PR I run a small sample (100 evt) of the wf 150 (HydjetQ_B12_5020GeV_2018) with and without merging this PR. Reconstructed objects look identical in the two reconstructions (in particular HCal recHits energy and iEta); the only exception is the following plot obtained with HCalRechitIsolCalculator 

all_testpr20443vsorig_hydjetqb1220118f150p0c_recohiphotonisolationedmvaluemap_photonisolationhiproducer__reco_obj_values__hcalrechitisor2

The (tiny) difference shows up for distances between the photon and the hbheRecHit 0.1<deltaEta<0.2 (i.e. it is not there in hcalRechitIsoR1 and it is there in hcalRechitIsoR2,3,4,5). As I said, I can't see differences in the recHit energy/eta, nor in the photon energy/eta....

Probably it is not worth debugging any further, if there is some possible explanation for it: do you have any? In the HCalRechitIsolCalculator::getBkgSubHcalRechitIso() method the eta of the recHit is accessed via geometry_ , i.e. potentially affected by this PR.

(Of course my point is not whether the differences are relevant, they are not in fact: I would simply would like to check whether everything is under control)

**Comment by perrotta** [comment]
Discussing with @slava77  we concluded that the explanation for that difference in the isolation HCal content and not in the HCal recHits is due exactly to what written in https://github.com/cms-sw/cmssw/pull/20443#issuecomment-330553409, i.e. "the eta of the recHit is accessed via geometry_": therefore the observed difference is the effect of this fix

**Comment by perrotta** [comment]
+1
- It fixes the access to HCal geometry also for HI reco, analogously to what was already done in other sectors
- No major effects on the outputs: the few differences reported in https://github.com/cms-sw/cmssw/pull/20443#issuecomment-330553409 can be explained as an effect of this fix

**Comment by slava77** [comment]
@davidlange6 
are we waiting for some feedback here?
please clarify

**Comment by davidlange6** [comment]
hi @slava77 - its the same "fix" as in #20523 - was hoping for a more proper fix.

**Comment by slava77** [comment]
> hi @slava77 - its the same "fix" as in #20523 - was hoping for a more proper fix.

right, but a few PRs with the same "fix" were already merged.

**Comment by bsunanda** [comment]
@slava77 @davidlange6 I cannot foresee a more proper fix in foreseeable future.

**Comment by bsunanda** [comment]
@slava77 @davidlange6 Please approve this

**Comment by bsunanda** [comment]
@davidlange6 What do you mean by a more proper fix?

**Comment by slava77** [comment]
@davidlange6 
while technical improvements are still blocking this PR, I'd like to note that we are running with a buggy algorithm using incorrect access to geometry.

@bsunanda @mandrenguyen 
please take a look at changes posted here earlier.
I see that photonIsolationHIProducer is also a part of the XeXe PR.
We may need a backport.

**Comment by mandrenguyen** [comment]
@ttrk Can you take a look please?

**Comment by davidlange6** [comment]
Well - it depends. There seems to be a pile of these PRs.. (usual CMS nose of camel approach). So we can fix one/two and ignore the other bugs, or fix the interface so that all can be easily identified and fixed (via compilation errors, which is the robust way to change an interface)

now - of course one can propose to do that in a PR that comes in some definite time period from now, but I've not seen that proposed.

**Comment by slava77** [comment]
On 10/7/17 7:45 AM, David Lange wrote:
> Well - it depends. There seems to be a pile of these PRs.. (usual CMS
> nose of camel approach). So we can fix one/two and ignore the other
> bugs, or fix the interface so that all can be easily identified and
> fixed (via compilation errors, which is the robust way to change an
> interface)
> 
> now - of course one can propose to do that in a PR that comes in some
> definite time period from now, but I've not seen that proposed.

Let's see if this one is essential for XeXe run.

**Comment by ttrk** [comment]
@slava77 
My understanding is that the PR fixes the bug (using correct geometry), but is not coded in the ideal way.

Yes, photonIsolationHIProducer is important for the XeXe run. It is likely that XeXe reco will be done with 92X ( @mandrenguyen can comment on the release), requiring a backport of the PR.

**Comment by mandrenguyen** [comment]
Important for the XeXe run is perhaps overstating it.   We can live without this for the prompt reco, the release for which has to be replayed for Monday.   There's no plan for a photon analysis on a faster scale than the data is likely to be re-reco'd anyway.

**Comment by ttrk** [comment]
@slava77 @mandrenguyen  
Concerning photonIsolationHIProducer, I am fine with a XeXe prompt reco that does not contain this PR, since it can be merged for re-reco. 

@mandrenguyen 
FYI, this PR does not modify photonIsolationHIProducer only, but also ParticleTowerProducer.cc under  RecoHI/HiJetAlgos/

**Comment by slava77** [comment]
> So we can fix one/two and ignore the other bugs, or fix the interface so that all can be easily identified and fixed (via compilation errors, which is the robust way to change an interface)

@bsunanda 
how comprehensive was your coverage so far of possible places with the same issue in the release?

If there is a still unknown set of issues present, this **should become a showstopper for 94X**

**Comment by davidlange6** [comment]
> On Oct 7, 2017, at 6:52 PM, Slava Krutelyov <notifications@github.com> wrote:
> 
> So we can fix one/two and ignore the other bugs, or fix the interface so that all can be easily identified and fixed (via compilation errors, which is the robust way to change an interface)
> 
> @bsunanda
> how comprehensive was your coverage so far of possible places with the same issue in the release?
> 
> If there is a still unknown set of issues present, this should become a showstopper for 94X
> 

I agree

After investigating a little - I realize that the fact that HcalGeometry derives from CaloSubdetectorGeometry is nothing new (even if inside it is a structure begging for a vector of sub detectors as implemented in the CaloGeometry class....) - 

but that means the issue is newer - Eg

GlobalPoint pos =geo_->getGeometry(hid)->getPosition();

is apparently broken for HCAL detids. This seems to me that it is simply due to the lack of appropriate subclasses for IdealObliquePrism and IdealZPrism that correctly deal with the special implementation of getPosition (currently in HcalGeometry). 

Maybe there is a less hacky fix (if I've understood (all of) the problem)

**Comment by davidlange6** [comment]
Hi again

@bsunanda mostly

I realize it can be even simpler. The question is, aside from things internal to the HcalGeometry class itself, for what usage would this proposed change be incorrect: 

--- a/Geometry/HcalTowerAlgo/interface/HcalGeometry.h
+++ b/Geometry/HcalTowerAlgo/interface/HcalGeometry.h
@@ -106,7 +106,11 @@ public:
                        const DetId&       detId     ) override ;
 
   const CaloCellGeometry* getGeometry( const DetId& id ) const override {
+    if (!m_mergePosition) {
       return cellGeomPtr( m_topology.detId2denseId( id ) ) ;
+    } else {
+      return cellGeomPtr( m_topology.detId2denseId( m_topology.idFront(id) ) ) ; 
+    }
   }


The behavior of HcalGeometry itself can be preserved without difficulty via a private function..

**Comment by bsunanda** [comment]
Hi Dave

I shall check this and if this is a solution I shall go for it.

Sunanda
________________________________

**Comment by davidlange6** [comment]
hi @bsunanda - this change is no longer required. Correct?

**Comment by bsunanda** [comment]
After PR# 20868 is merged these changes are no longer necessary

**Pull request closed without merging**
