### PR TITLE
Bug Fix for PR #17589 (Fixed Empty tracker histograms)

### PR DESCRIPTION
**Pull request by yimuchen**
Reverting line causing some histograms to not be filled

### CODE REVIEW

**Comment by boudoul** [comment]
hi @dmitrijus can you please trigger the test ?

**Comment by boudoul** [comment]
FYI the 91X PR is there  : #17865

**Comment by boudoul** [comment]
hi @enochnotsocool , could you please manwhile update the title of this PR to be a bit more explicit ? Thanks

**Comment by boudoul** [comment]
@davidlange6 , This is an important bug fix , it is reverting a line that was mistakenly changed in pre6 (so putting it back as it was in pre5 ) impacting severely DQM plots-  I guess @dmitrijus will put this PR  in the list for 90X bug fix at the ORP

**Comment by dmitrijus** [comment]
+1

**Comment by dmitrijus** [comment]
-1
This isn't a backport, this change is substantially different from the one linked by @boudoul.

So, to ask again, is this in 91x? Or rather, why is this only the one line change - compared to the linked PR, wouldn't it be more sense to backport that entire PR?

**Comment by boudoul** [comment]
of course, we just have in 90X the bug fix part of the PR mentioned

**Comment by boudoul** [comment]
if 900 is built without this bug fix, the tracker will declare the validation of 900 as failure 9s we did as pre6 )

**Pull request merged**
