### PR TITLE
HLT menu development for `13_0_X` (12/N) [`13_3_X`]

### PR DESCRIPTION
**Pull request by missirol**
#### PR description:

Development of HLT menus for `CMSSW_13_0_X`.

This is the PR for the `master` branch, which will then be backported down to `13_0_X` (the latter is the release cycle currently used for Run-3 HLT-menu development).

This update includes the integration of the following JIRA tickets.

 - [CMSHLT-2820](https://its.cern.ch/jira/browse/CMSHLT-2820): [EXO] tighter isolation cut on L2Taus in displaced-tau trigger (and addition of backup trigger)
 - [CMSHLT-2836](https://its.cern.ch/jira/browse/CMSHLT-2836): [TSG] addition of looser L1T seeds to dilepton Scouting triggers
 - [CMSHLT-2862](https://its.cern.ch/jira/browse/CMSHLT-2862): [TRK,ECAL] use only CPU products in CPU branch of `DQMGPUvsCPU` triggers 
 - [CMSHLT-2867](https://its.cern.ch/jira/browse/CMSHLT-2867): [EXO] remove Tracker-HV filters in calo-only LLP triggers
 - [CMSHLT-2872](https://its.cern.ch/jira/browse/CMSHLT-2872): [SMP] looser DiTau trigger for W-3pi search (plus control trigger)
 - [CMSHLT-2873](https://its.cern.ch/jira/browse/CMSHLT-2873): [AlCa] set smartPS=2 for `HLT_Physics_v` in `ExpressPhysics` PD
 - [CMSHLT-2874](https://its.cern.ch/jira/browse/CMSHLT-2874): [EXO,HIG] new VBF-parking triggers without PFJet-CHF cut
 - [CMSHLT-2875](https://its.cern.ch/jira/browse/CMSHLT-2875): [EXO] triggers for displaced mu-tau and e-tau final states
 - [CMSHLT-2877](https://its.cern.ch/jira/browse/CMSHLT-2877): [GEM] save GEM `FEDRawData` in `RPCMON` stream
 - [CMSHLT-2878](https://its.cern.ch/jira/browse/CMSHLT-2878): [TRK] add pixel-doublet-recovery iteration to standard tracking sequence, and disable track-looper reconstruction

In addition, the following updates relevant to HLT-menu development are included.
 - 1438ec3cbfd: fix function `getHltConfiguration`
 - 699cc5dd669: change compression settings of OutputModule in `hltIntegrationTests`
 - 098df6d76c0: use bash arrays in `test/get*HLT.sh` scripts
 - cf289c7ffac: remove module `siPixelQualityESProducer` from HLT `cff` files
 - 5cafe26d3ca: update of L1T pp menu in TSG GTs to [`L1Menu_Collisions2023_v1_3_0`](https://htmlpreview.github.io/?https://github.com/cms-l1-dpg/L1MenuRun3/blob/696c92070a1be0ae6bcb23644f65b1119cedc4ba/development/L1Menu_Collisions2023_v1_3_0/L1Menu_Collisions2023_v1_3_0.html)
 - 9ced6a4d6da: update of Run-3 data EDM input in HLT tests (HLT-Validation and HLT-addOn tests)

#### PR validation:

TSG tests.

#### If this PR is a backport, please specify the original PR and why you need to backport that PR. If this PR will be backported, please specify to which release cycle the backport is meant for:

`CMSSW_13_2_X`
`CMSSW_13_1_X`
`CMSSW_13_0_X`

### CODE REVIEW

**Comment by missirol** [comment]
enable gpu

**Comment by missirol** [comment]
please test

**Comment by missirol** [comment]
+hlt

 - Changes in the outputs of PR tests are in line with the updates to the HLT GRun menu.

**Comment by mmusich** [comment]
test parameters:
   * workflows = 141.041, 141.042, 141.046

**Comment by mmusich** [comment]
@cmsbuild, please test
   * I am just profiting (abusing) of this PR to see the effect of [CMSHLT-2878](https://its.cern.ch/jira/browse/CMSHLT-2878): ([TRK] add pixel-doublet-recovery iteration to standard tracking sequence, and disable track-looper reconstruction) on some of the 2023D data (afflicted by the BPix L3/4 hole, included in https://github.com/cms-sw/cmssw/commit/971b7e90af6cb966f3d677453f3e080358a90536). PR integration shold not bound to the outcome of these tests.

**Comment by perrotta** [comment]
+1
- Let merge this, the ongoing tests with the additional workflows will continue independently (or, better: this will get automatically merged as soon as the tests will succesfully finish)

**Comment by mmusich** [comment]
> I am just profiting (abusing) of this PR to see the effect of [CMSHLT-2878](https://its.cern.ch/jira/browse/CMSHLT-2878): ([TRK] add pixel-doublet-recovery iteration to standard tracking sequence, and disable track-looper reconstruction) on some of the 2023D data (afflicted by the BPix L3/4 hole, included in https://github.com/cms-sw/cmssw/commit/971b7e90af6cb966f3d677453f3e080358a90536). PR integration should not bound to the outcome of these tests.

For the record, I would have expected the new collection `hltDoubletRecoveryPFlowTrackSelectionHighPurity` to appear in the DQM comparisons due the already integrated https://github.com/cms-sw/cmssw/pull/42266. This is currently not the case because the input collection is not yet saved in the `FEVTDEBUGHLT` data-tier. This will be followed up in this ticket: https://its.cern.ch/jira/browse/CMSHLT-2889

**Comment by slava77** [comment]
type tracking

**Pull request merged**
