### PR TITLE
Fix Pixel Clusters for Phase2 HLT Menu

### PR DESCRIPTION
**Pull request by AdrianoDee**
#### PR description:

This PR realigns the `siPixelClusters` module used in Phase2 HLT menu to the one up to date in the release. Without this fix the pixel clustering parameters used in the menu are obsolete and this causes a huge drop in tracking efficiency. 

#### PR validation:

Running the menu the general tracks efficiency is recovered. Tested with `39434.75` wf.

image

### CODE REVIEW

**Comment by AdrianoDee** [comment]
test parameters:

- workflows = 39434.75
- relvals_opt = --what cleanedupgrade,standard,highstats,pileup,generator,extendedgen,production,ged,machine,premix

**Comment by AdrianoDee** [comment]
please test

**Comment by missirol** [comment]
type bugfix

Fix to the HLT Phase-2 menu.

**Comment by missirol** [comment]
This fix reminds that there is no DQM in wf `39434.75` for the HLT Phase-2 menu.

I understood from https://github.com/cms-sw/cmssw/pull/37162#issuecomment-1083414786 that this was being worked on. @trtomei, can you remind me what is the plan for that?

**Comment by missirol** [comment]
+hlt

**Comment by perrotta** [comment]
+1

**Comment by Martin-Grunewald** [comment]
Q: would this PR need to be backported to 12_4 and 12_5 for studies?

**Comment by Martin-Grunewald** [comment]
@AdrianoDee 
Please provide backport PRs for 12_4 and 12_5.
Thank you!

**Comment by missirol** [comment]
> This fix reminds that there is no DQM in wf `39434.75` for the HLT Phase-2 menu.
> 
> I understood from [#37162 (comment)](https://github.com/cms-sw/cmssw/pull/37162#issuecomment-1083414786) that this was being worked on. @trtomei, can you remind me what is the plan for that?

@trtomei , do you know if anybody is working on adding DQM to the wf testing the HLT Phase-2 menu?

**Comment by AdrianoDee** [comment]
> > This fix reminds that there is no DQM in wf `39434.75` for the HLT Phase-2 menu.
> 
> > 
> 
> > I understood from [#37162 (comment)](https://github.com/cms-sw/cmssw/pull/37162#issuecomment-1083414786) that this was being worked on. @trtomei, can you remind me what is the plan for that?
> 
> 
> 
> @trtomei , do you know if anybody is working on adding DQM to the wf testing the HLT Phase-2 menu?

Is there an issue for that or shall we open it?

**Comment by missirol** [comment]
I don't think there is; it's probably good to open one.

**Pull request merged**
