### PR TITLE
Updates to L1TCaloLayer1 and unpacker (80X)

### PR DESCRIPTION
**Pull request by nsmith-**
Contains:
Region validation
minBias unpacker updates
Code cleanup for emulator

80X version of #14284

### CODE REVIEW

**Comment by mulhearn** [comment]
In terms of algorithms, this is confirmed bitwise equivalent to l1t-tsg-v5 in 806.

**Comment by mulhearn** [comment]
+1

**Comment by mulhearn** [comment]
+1

**Comment by mulhearn** [comment]
please test

**Comment by nsmith-** [comment]
This is merged in 81X and passed ok through CMSSW_8_1_0_pre4

**Comment by nsmith-** [comment]
@davidlange6 this is merged for ~1 week in 81X
Happy to get it off my plate ;)

**Comment by davidlange6** [comment]
+1

**Pull request merged**
