### PR TITLE
Rebasing from PR in CMSSW_8_1_X

### PR DESCRIPTION
**Pull request by dinardo**
Please see PR#14926 ... rebase needed to cope with PR#345 for dqmgui ...

### CODE REVIEW

**Comment by dinardo** [comment]
This PR# has to go with PR#345 in dqmgui !

**Comment by vanbesien** [comment]
Corresponding 81X PR #14926

**Comment by dmitrijus** [comment]
please test

**Comment by dinardo** [comment]
I don't understand.
Do you want me to do something ?
Shall I need to make a new pull-request in a different CMSSW_8_0_version ?

**Comment by dmitrijus** [comment]
You need to re-create this PR and close this one.
The target should be 8_0_X, not CMSSW_8_0_10_patchX

**Comment by dmitrijus** [comment]
81x one is fine

**Comment by dmitrijus** [comment]
new pr https://github.com/cms-sw/cmssw/pull/14935

**Pull request closed without merging**
