### PR TITLE
remove host-based override and printout

### PR DESCRIPTION
**Pull request by fwyzard**

### CODE REVIEW

**Comment by ggovi** [comment]
@fwyzard 
is the special Frontier connection string no longer required for the cms domain?

**Comment by fwyzard** [comment]
It is, but it is a bad idea to make the change based on the host name.
For example:
  - some random machine could be called "whatever.cms.university.edu" and pick up the wrong connection string
  - an online machine could not report the ".cms" part of the hostname and miss the customisation

.A

**Comment by mmusich** [comment]
@fwyzard, I appreciate your point. To be sure I understand correctly this one is more an heads up than a real proposal ?

**Comment by ggovi** [comment]
I think we should have _somewhere_ the lines with the Frontier long connection string 'ready' for the cms domain.  Maybe split them to a different file to be deployed and used depending on the context?

**Comment by ggovi** [comment]
@fwyzard 
Assuming your change, how are you going to use this file for the HLT use case?

**Comment by fwyzard** [comment]
HLT does not rely on this, or any othe python file from the release, since the whole configuration is self-contained, and stored in ConfDB.

**Comment by fwyzard** [comment]
Together with DAQ, we think we could deploy a SITECONF on the online machines that would reduce the long connection string to
```
frontier://FrontierOnProd/CMS_CONDITIONS
```

**Comment by mmusich** [comment]
@fwyzard maybe I am too naive, but what about online DQM? @vanbesien @dmitrijus

**Comment by ggovi** [comment]
ah ok, that would be the way to go then!

**Comment by fwyzard** [comment]
Online DQM should set their connection string properly (like I assume they are doing now, since this was not present in 8.0.x).

**Comment by diguida** [comment]
This PR has been included in #15296 featuring also the online DQM configuration

**Comment by mmusich** [comment]
-1

**Pull request closed without merging**
