### PR TITLE
Remove GenTtbarCategorizer_cfi.py (moved to fillDescription)

### PR DESCRIPTION
**Pull request by silviodonato**
#### PR description:

After #30150, the default values of GenTtbarCategorizer are defined using fillDescriptions. 
This PR removes the old GenTtbarCategorizer_cfi.py and uses the automatically generated categorizeGenTtbar_cfi
https://github.com/cms-sw/cmssw/pull/30150#issuecomment-642645454

#### PR validation:

runTheMatrix.py  -l limited  -t 4 --ibeos

### CODE REVIEW

**Comment by silviodonato** [comment]
please test

**Comment by santocch** [comment]
+1

**Comment by silviodonato** [comment]
Any objections @peruzzim ?

**Comment by silviodonato** [comment]
merge

**Pull request merged**
