### PR TITLE
[RFC] Test clang-tidy --checks performance-for-range-copy

### PR DESCRIPTION
**Pull request by fwyzard**
See the description at https://clang.llvm.org/extra/clang-tidy/checks/performance-for-range-copy.html .

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by Dr15Jones** [comment]
This looks good. (Although I prefer 'east const' :).)

**Comment by cvuosalo** [comment]
+1

**Comment by kpedro88** [comment]
@fwyzard is there any interacting between this check and modernize-loop-convert? (Should we apply this one on top of modernize-loop-convert?)

**Comment by kpedro88** [comment]
+upgrade

**Comment by fwyzard** [comment]
> @fwyzard is there any interaction between this check and modernize-loop-convert? (Should we apply this one on top of modernize-loop-convert?)

https://github.com/cms-sw/cmssw/pull/29863 had all the changes applied at once.
Is that enough to check how the flags interact with each other ?

**Comment by kpedro88** [comment]
It's extremely difficult to browse the changes in GitHub. Can you restore the branch for that PR to enable browsing locally?

**Comment by kpedro88** [comment]
never mind, can fetch it with `git fetch official-cmssw refs/pull/29863/head`

**Comment by kpedro88** [comment]
It seems like #29863 is missing some of the changes that appear in this PR (e.g. in `Alignment/OfflineValidation/bin/DMRtrends.cc`)

But if the plan is to apply them all together as described in https://github.com/cms-sw/cmssw/pull/29934#issuecomment-632376546, it should be fine

**Comment by pohsun** [comment]
+1

**Comment by santocch** [comment]
+1

**Comment by qliphy** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by jfernan2** [comment]
+1

**Comment by perrotta** [comment]
+reconstruction

**Comment by mommsen** [comment]
+1

**Comment by mrodozov** [comment]
-note
keep it

**Comment by alja** [comment]
+1

**Comment by Martin-Grunewald** [comment]
+1

**Pull request closed without merging**
