### PR TITLE
Run3-gex164Z Modify all Run3 scenarios after fixing the RPC geometry issue

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Modify all Run3 scenarios after fixing the RPC geometry issue

#### PR validation:

The change in the xml file is being tested by the RPC group, The changes in the scenario is tested by running overlap testing tools with all modified scenarios

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Should be back ported to versions which will be used for production data/MC

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by srimanob** [comment]
The report will be done at ALCA meeting on Mon, 19 Jun
https://indico.cern.ch/event/1292018/

**Comment by bsunanda** [comment]
@srimanob Since the report is good, could you please approve this PR?

**Comment by srimanob** [comment]
+Upgrade

**Comment by rappoccio** [comment]
+1

**Pull request merged**
