### PR TITLE
Run3-gex155A Additional files to make payloads for 2023 Geometry

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Additional files in CondTools/Geometry to make payloads for 2023 Geometry

#### PR validation:

Use them in making the payloads

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by tvami** [comment]
+alca
 * with the comment that some of these scripts should become unit tests

**Comment by bsunanda** [comment]
@tvami Waiting for db clearance. can you sign for db?

**Comment by tvami** [comment]
+db
 * sorry I signed for alca but this was supposed to be `db`

**Comment by rappoccio** [comment]
+1

**Pull request merged**
