### PR TITLE
Customization for merging General and Pixel Track Collections in PbPb Reconstruction

### PR DESCRIPTION
**Pull request by abaty**
This PR adds a customization that merges tracks from the HIGeneralTracks and HIConformalPixelTracks collections into a single merged collection, which will be needed in a future reReco.  This customization drastically improves the tracking efficiency and fake rate at pt's less than 2 GeV, and will significantly enhance physics capabilities in HI events at low pt.

The customization can be checked running a config generated with the command below over RAW data from the 2015 PbPb run.  Note that with this customization the previously used HIGeneralTracks collection is dropped and replaced with a MergedCollection in the final event content.

cmsDriver.py step2 --process RECO --repacked --conditions 75X_dataRun2_PromptHI_v3 --scenario HeavyIons -s RAW2DIGI,L1Reco,RECO --datatier AOD --customise Configuration/DataProcessing/RecoTLR.customiseRun2CommonHI,RecoHI/Configuration/RecoMergedTrackCollection.customiseAddMergedTrackCollection --data --eventcontent AOD --no_exec

More information regarding the changes in performance can be found in the presentation shown in the HI PAG meeting here:
https://indico.cern.ch/event/507212/contributions/2189474/attachments/1284769/1910223/Pixel_Status_HIN_WEST.pdf

@CesarBernardes

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

@abaty please clarify on plans when this is needed (75X are built on demand now, the last one was more than 2 months ago).

**Comment by BetterWang** [comment]
Dear @slava77 , we would like to have a release to re-reco last year's PbPb data including pixel tracks.
This can extend our low pT reach and reduce fake rate significantly.

**Comment by mandrenguyen** [comment]
@abaty Is there any reason not to add this to the frontier release (81X)?  Or is this the first and last time we will ever run pixel tracking?  What is the expected impact on downstream products such as muons and particle flow?

**Comment by abaty** [comment]
@mandrenguyen @CesarBernardes 

In the future I believe we might promote the merged track collection the default track reconstruction for HI, but this needs more discussion in a wider audience I think.  We should prepare a PR for the new release in any case.

The current customization in this PR implementation should not affect anything downstream, as the building of the HIGeneralTracks collection has not changed at all.  The downstream products will still use this collection as input, and then the collection will be dropped at the end of the processing, in favor of keeping the merged collection.  In the future if it is decided we want to move towards using the merged collection for everything, we will need to make sure all the downstream stuff picks up the new collection.

**Comment by mandrenguyen** [comment]
@abaty Making this the default behavior is a separate issue from having this in 81X.  I'm somewhat wary of dropping hiGeneralTracks, since other collections will contain references to this collection.  Given the very limited scope of this reprocessing (two primary datasets, I've been told), is it really worth dropping the standard track collection, which is being used by many downstream modules?  Perhaps @BetterWang can comment for the flow group.

**Comment by abaty** [comment]
@mandrenguyen 

If you are strongly against dropping this collection for now then I think we can keep it; we were trying to limit the amount of disk space used.  As you said since this is a limited reprocessing then the extra space hopefully won't be a huge issue for now.

**Comment by BetterWang** [comment]
Hi @abaty @mandrenguyen @CesarBernardes ,
The first round of reprocessing will be one HIMB PD and one HIFlowCorr PD. After that, we plan to reprocess all MB PD. The disk usage is quite heavy though. I will ask other PinG leaders if they need to reprocess other PDs to do further studies. I would like to keep hiGeneralTracks, but it really depends on the disk space at VU.

**Comment by mandrenguyen** [comment]
@BetterWang  That's not what was proposed to me by the HI conveners.  I would suggest a clear plan that includes an estimate of the resources required be presented at the PAG.  I find it hard to believe that the other sub-group leaders will/have signed off on a reprocessing of the entire dataset without storing the standard track collection, which will almost certainly crash our standard ntuples (hiForest).

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
Testing in progress...

**Comment by cvuosalo** [comment]
@abaty: It appears the instructions for running the test config are wrong. The customise argument is given as:
```
--customise Configuration/DataProcessing/RecoTLR.customiseRun2CommonHI,RecoHI/Configuration/RecoMergedTrackCollection.customiseAddMergedTrackCollection
```
but this causes an error because there is no file called `RecoMergedTrackCollection`. The following customise argument works:
```
 --customise Configuration/DataProcessing/RecoTLR.customiseRun2CommonHI,RecoHI/Configuration/customise_RecoMergedTrackCollection.customiseAddMergedTrackCollection
```
Are the instructions incorrect, or does the file in this PR have the wrong name?

**Comment by BetterWang** [comment]
@cvuosalo  The documentation was out dated.

**Comment by cvuosalo** [comment]
+1

For #14819 4b0b8d97c978881620b004d1abf58a8a6da0512a

Adding customization for merging General and Pixel Track Collections in PbPb reco. There should be no change in standard workflows since this PR adds a new config that is not used by default.

The code changes are satisfactory, and Jenkins tests against baseline CMSSW_7_5_X_2016-06-12-0000 show no significant differences, as expected, though there are a few spurious differences in the validation plots. The following test exercised the new config with 10 events against baseline CMSSW_7_5_8_patch4:
```
cmsDriver.py step2 --process RECO --repacked --conditions 75X_dataRun2_PromptHI_v3 --scenario HeavyIons -s RAW2DIGI,L1Reco,RECO --datatier AOD --customise Configuration/DataProcessing/RecoTLR.customiseRun2CommonHI,RecoHI/Configuration/customise_RecoMergedTrackCollection.customiseAddMergedTrackCollection --data --eventcontent AOD --customise Validation/Performance/TimeMemoryInfo.py --filein /store/hidata/HIRun2015/HIMinimumBias2/RAW/v1/000/262/818/00000/006CDFEB-2598-E511-9D75-02163E014781.root --fileout file:step2.root  -n 10
```
The collections added by this PR increase Reco event content by about 7%:
```
-----------------------------------------------------------------
   or, B         new, B      delta, B   delta, %   deltaJ, %    branch 
-----------------------------------------------------------------
      0.0 ->       343.8        344     NEWO   0.03     floatedmValueMap_hiGeneralAndPixelTracks_MVAVals_RECO.
      0.0 ->     69678.1      69678     NEWO   6.93     recoTracks_hiGeneralAndPixelTracks__RECO.
      0.0 ->       344.2        344     NEWO   0.03     floatedmValueMap_hiPixelOnlyStepSelector_MVAVals_RECO.
      0.0 ->       339.4        339     NEWO   0.03     floatedmValueMap_hiHighPtStepSelector_MVAVals_RECO.
-------------------------------------------------------------
  1005691 ->     1076412      70721             7.0     ALL BRANCHES
```
CPU time increases by about 11%.
```
  delta/mean delta/orJob     original                   new       module name
  ---------- ------------     --------                  ----       ------------
       added      +0.40%         0.00 ms/ev ->        74.28 ms/ev hiGeneralAndPixelTracks
       added      +8.73%         0.00 ms/ev ->      1612.74 ms/ev hiConformalPixelTracks
       added      +0.02%         0.00 ms/ev ->         3.27 ms/ev hiPixelOnlyStepSelector
       added      +0.02%         0.00 ms/ev ->         2.91 ms/ev hiHighPtStepSelector
  ---------- ------------     --------                  ----       ------------
Job total:  18.4635 s/ev ==> 20.4358 s/ev
```

**Comment by davidlange6** [comment]
+1

**Pull request merged**
