### PR TITLE
Modify tau sequences to not pull payloads from outside GT (14_0_X)

### PR DESCRIPTION
**Pull request by mbluj**
#### PR description:

This PR addresses a longstanding issue with tau modules pulling payloads from outside GT (https://github.com/cms-sw/cmssw/issues/43797).
The issue at the AOD and miniAOD steps is solved since CMSSW 12 series, so this PR fixes it at the nanoAOD step and it is believed that it closes the issue with current CMSSW series (14_X_Y).
Changes introduced by this PR are purely technical and do not change produced samples.

It is verbatim backport of #44685.

#### PR validation:

Validated locally with nano configurations for Run3 and Run2,run2_nanoAOD_106Xv2 eras with and without access to frontier (the latter with GTs dumped to sqlite files)
Validation with matrix tests in preformed the context of the original PR.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport of #44685 for 2024 operations.

### CODE REVIEW

**Comment by hqucms** [comment]
enable nano

**Comment by hqucms** [comment]
please test

**Comment by jfernan2** [comment]
backport of https://github.com/cms-sw/cmssw/pull/44685

**Comment by jfernan2** [comment]
type tau

**Comment by hqucms** [comment]
+1

**Comment by jfernan2** [comment]
+1

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
