### PR TITLE
Updated version of the boosted double SV tagger (76X)

### PR DESCRIPTION
**Pull request by ferencek**
Backport of #12442.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
+1

For #12445 40f990ddd7d6da8a0e528966a180efe06e25de80

Updating the boosted double SV tagger. #12442 and #12446 are the 80X and 74X versions of this PR.

The code changes are satisfactory, and Jenkins [tests](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-12445/9785/summary.html) against baseline CMSSW_7_6_X_2015-11-15-1100 show no significant differences,

**Comment by ferencek** [comment]
I have updated the 80X version of this PR (#12442). Once it is merged and validated, we can go ahead with this PR. From what I understood from the discussion in #12288, MiniAOD changes will be possible in which case I need to add one more commit to this PR to make it the full backport of #12442. Let me know if it would be OK to include this commit already now.

**Comment by slava77** [comment]
@cmsbuild please test

@ferencek none of the changes in this PR (or the commits you wanted to add) are in RECO/AOD, is this correct?
If so, I think you can add your commits here to match #12442 

@arizzi @gpetruc

**Comment by ferencek** [comment]
@slava77, correct, none of the changes affect RECO/AOD. I just added the missing commit and updated the PR description to make it clear this is not a partial but the full backport.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
+1

For #12445 78bb2a028b777bc3287ace837aa63633c6a3d328

Second approval after small code changes. #12442 and #12446 are the 80X and 74X versions of this PR.

The code changes are satisfactory, and Jenkins tests still show no significant differences. See #12442 for detail on extended test results, which show no problems.

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
@cmsbuild please test
It appears the Jenkins test failed.

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
+1

For #12445 9fc470c31836f68c5198d090c3b65a71b5f62fd7

Third approval after tiny code change. #12442 and #12446 are the 80X and 74X versions of this PR.

The code change is OK. Jenkins tests are running into systemic problems not related to this PR. Jenkins tests for #12446 were successful, and they show no problems.

**Pull request merged**
