### PR TITLE
HCALDQM: more fixes for crashes due to calib channels, improve TP emulation, and minor plot adjustments (92X backport of 19547)

### PR DESCRIPTION
**Pull request by DryRun**
Backport 19547 to 9_2_X. This is take 2 of https://github.com/cms-sw/cmssw/pull/19548, which pulled in some unwanted commits somehow.

Edit: at @dmitrijus' request, here is the comment from the original PR. 

- Finish protecting against inclusion of calibration channels in QIE10/11DigiCollections. These can cause crashes when FEDs 1134 and 1135 are included in runs. (The previous PRs fixed most of these, but I unfortunately discovered a few more cases.)
- Add zero suppression to emulated TPs, to match what is done in data TPs.
- PedestalTask has a filter to skip the laser/CRF/calibration channels crate. This was moved from crate 36 to 38, so the filter is updated accordingly (note that crate 36 is not in use anymore).
- Small plot adjustments: fN_to4000 changed to fN_to8000 (this is used only to set the y-range for profile plots, so doesn't add bins), and fEtCorr_256 is changed from [-2,256] to [-1, 257] so that saturated bins aren't right on the edge.
This PR does not add any extra bins.

### CODE REVIEW

**Comment by dmitrijus** [comment]
This is way bigger than https://github.com/cms-sw/cmssw/pull/19547
Not a proper backport.

**Comment by DryRun** [comment]
Hi Dmitrijus,

I wasn't sure how to make this PR, since it is effectively a backport of
18841+19547... Perhaps the 18841 backport will merge soon, in which case I
can base the 19547 backport off of that? Unfortunately, the two PRs are not
factorizable.

Cheers,
David

**Comment by dmitrijus** [comment]
Sounds like a plan. So we wait until https://github.com/cms-sw/cmssw/pull/19538 is merged.

**Comment by DryRun** [comment]
I added a commit to fix a bug pointed out by @slava77 -- I mistakenly changed an instance of QIE11DataFrame::samples() to QIE11DataFrame::size(), which led to accessing some values beyond the end of a vector to determine the digi timing, and hence random values being filled in the plot.

**Comment by slava77** [comment]
On 7/10/17 6:27 AM, David Yu wrote:
> I added a commit to fix a bug pointed out by @slava77
> <https://github.com/slava77> -- I mistakenly changed an instance of
> QIE11DataFrame::samples() to QIE11DataFrame::size(), which led to
> accessing some values beyond the end of a vector to determine the digi
> timing, and hence random values being filled in the plot.

It's nice to have a fix.
Thank you.

**Comment by dmitrijus** [comment]
If you add a fix, please provide an upstream version of it too.

**Comment by DryRun** [comment]
Hi @dmitrijus - sorry to be unclear, the upstream version is https://github.com/cms-sw/cmssw/pull/19588.

**Comment by vanbesien** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
CMSSW_9_2_X developement work is completed. Closing remaining PRs

**Pull request closed without merging**
