### PR TITLE
add AlCaReco matrix for 2016 reprocessing

### PR DESCRIPTION
**Pull request by franzoni**
add AlCaReco matrix for 2016September reprocessing,
which is all what is run at T0 and less than it's currently in the matrix.
For documentation and future reference.

### CODE REVIEW

**Comment by mmusich** [comment]
please test 
(actually nothing that can be tested in standard tests)

**Comment by mmusich** [comment]
+1

**Comment by mmusich** [comment]
@cmsbuild, please test
test seem to be stuck. re-trying

**Comment by davidlange6** [comment]
+1

**Pull request merged**
