### PR TITLE
Run3-TB56 Update all the cfg files of HGCal TB

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

In view of getting MB plots for TB setup, several cfg files are updated so that they work with the latest changes in geometry codes for other parts)

#### PR validation:

All changed cfg files in the area SimG4CMS/HGCalTestBeam/test are tested with acceptable results

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by kpedro88** [comment]
+upgrade

**Comment by civanch** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
