### PR TITLE
[12_4] Unique upgrade workflow ID

### PR DESCRIPTION
**Pull request by srimanob**
#### PR description:
This to make a unique upgrade workflow ID between CMSSW_12_4 and beyond after https://github.com/cms-sw/cmssw/pull/41591

#### PR validation:
Using `runTheMatrix.py --what upgrade -n | grep 2022ReReco` to check the workflow ID

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:
This PR is for 12_4 only. Master (and maybe 13_1) will have the same kind of PR but with different `numWFConflict`. Here is the master PR, https://github.com/cms-sw/cmssw/pull/41689

### CODE REVIEW

**Comment by srimanob** [comment]
test parameters:

+ relvals_opt= -w upgrade
+ workflows = 14434.0

**Comment by srimanob** [comment]
@cmsbuild please test

The workflow `14434.0` should equivalent to `14034.0` from https://github.com/cms-sw/cmssw/pull/41591

**Comment by srimanob** [comment]
test parameters:
- relvals_opt= -w upgrade
- workflows = 14434.0

**Comment by srimanob** [comment]
@cmsbuild please abort

**Comment by srimanob** [comment]
test parameters:
- relvals_opt= -w upgrade
- workflows = 14434.0

**Comment by srimanob** [comment]
@cmsbuild please test

**Comment by srimanob** [comment]
@cmsbuild please test

**Comment by sunilUIET** [comment]
+pdmv

**Comment by srimanob** [comment]
+Upgrade

**Comment by rappoccio** [comment]
+1

**Pull request merged**
