### PR TITLE
DQMStore - switch to C++17's std::string_view

### PR DESCRIPTION
**Pull request by knoepfel**
To clean up the implementation, the `char_string` class has been replaced by `std::string_view`.  This should be seamless for the user.

### CODE REVIEW

**Comment by andrius-k** [comment]
+1

**Comment by andrius-k** [comment]
-1

There is a build error.

`getPathname()` now returns `std::string_view` so data type of `path` variable apparently should be adjusted accordingly.

**Comment by knoepfel** [comment]
@andrius-k Sorry about that; thought I had taken care of all the dependent code.  The commit I just pushed takes care of the build error.

**Comment by andrius-k** [comment]
please test

**Comment by knoepfel** [comment]
Investigating.

**Pull request closed without merging**
