### PR TITLE
Update the ADG database host names used by ConfDB (10.2.x)

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

This PR updates the database host names used by the ConfDB offline converter to access the ADG copy of the online database.

There are no changes to any CMSSW-specific code.

#### PR validation:

The sample command
```
hltConfigFromDB --v2 --adg --configName /cdaq/physics/Run2018/2e34/v3.6.1/HLT/V2 > hlt.py
```
fails without this PR, and succeeds with it.

### CODE REVIEW

**Comment by fwyzard** [comment]
@cmsbuild please test

**Comment by fwyzard** [comment]
+1

**Comment by fwyzard** [comment]
backport #27756

**Comment by fwyzard** [comment]
type bugfix

**Comment by fwyzard** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
