### PR TITLE
Phase2-hgx316G Tools used in investigating the overlap issue of HGCal geometry versions beyond V14

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Tools used in investigating the overlap issue of HGCal geometry versions beyond V14

#### PR validation:

Use overlap testing tools and debug prints in the algorithms to cross-check between DDD and DD4hep versions

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by bsunanda** [comment]
@srimanob Please approve this PR

**Comment by srimanob** [comment]
+Upgrade

This PR is to add tools to test overlap of HGCal. No change is expected from this PR as it does not touch geometry / workflow.

**Comment by perrotta** [comment]
+1

**Pull request merged**
