### PR TITLE
Support Comp2RefEqualH DQM quality test also on TProfile

### PR DESCRIPTION
**Pull request by gpetruc**
As the title reads, plus scram code-checks

### CODE REVIEW

**Comment by gpetruc** [comment]
please test

**Comment by gpetruc** [comment]
Uhm, the error in [1000.0](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-20887/23670/runTheMatrix-results/1000.0_RunMinBias2011A+RunMinBias2011A+TIER0+SKIMD+HARVESTDfst2+ALCASPLIT/step3_RunMinBias2011A+RunMinBias2011A+TIER0+SKIMD+HARVESTDfst2+ALCASPLIT.log) is
````
----- Begin Fatal Exception 11-Oct-2017 13:00:49 CEST-----------------------
An exception of category 'Configuration' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing module: class=PATMuonProducer label='tightMuonsCandidateForZMuSkim'
Exception Message:
MissingParameter: Parameter 'recomputeBasicSelectors' not found.
----- End Fatal Exception -------------------------------------------------
````
which IMHO comes from #20612 (merged) breaking [DPGAnalysis/Skims/python/ZMuSkim_cff.py](https://github.com/cms-sw/cmssw/blob/master/DPGAnalysis/Skims/python/ZMuSkim_cff.py) since that cff file makes a `PATMuonProducer` explicitly, and misses the new required parameter `recomputeBasicSelectors`  (the parameter  also seems to be missing in the `PATMuonProducer` [fillDescriptions](https://github.com/cms-sw/cmssw/blob/master/PhysicsTools/PatAlgos/plugins/PATMuonProducer.cc#L638-L745), but apparently parameter set validation is disabled for that class since 2009 by bd44959dc97e23ba97b2e7f50993e68297ca0164 so the ~100 lines of implementation don't do anything)

**Comment by slava77** [comment]
On 10/11/17 6:21 AM, Giovanni Petrucciani wrote:
> |MissingParameter: Parameter 'recomputeBasicSelectors' not found. -----
> End Fatal Exception ------------------------------------------------- |
> 
> which IMHO comes from #20612
> <https://github.com/cms-sw/cmssw/pull/20612> (merged) breaking
> DPGAnalysis/Skims/python/ZMuSkim_cff.py
> <https://github.com/cms-sw/cmssw/blob/master/DPGAnalysis/Skims/python/ZMuSkim_cff.py>
> since that cff file makes a |PATMuonProducer| explicitly, and misses the
> new required parameter |recomputeBasicSelectors| (the parameter also
> seems to be missing in the |PATMuonProducer| fillDescriptions
> <https://github.com/cms-sw/cmssw/blob/master/PhysicsTools/PatAlgos/plugins/PATMuonProducer.cc#L638-L745>,
> but apparently parameter set validation is disabled for that class since
> 2009 by bd44959
> <https://github.com/cms-sw/cmssw/commit/bd44959dc97e23ba97b2e7f50993e68297ca0164>
> so the ~100 lines of implementation don't do anything)
> 

to preserve formal causality:
the DPGAnalysis/Skims/python/ZMuSkim_cff.py was updated in #20693 merged
~26 hrs ago
while the #20612 was merged 3 days ago.

**Comment by gpetruc** [comment]
rerunning the tests as the IB should now be working

**Comment by gpetruc** [comment]
@cmsbuild please test

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
