### PR TITLE
DD4hep: SimTracker/TrackerMaterialAnalysis Migrated plugin Test

### PR DESCRIPTION
**Pull request by vargasa**
#### PR description:

Progress on testing migrated plugin to `dd4hep`

#### PR validation:

```
cmsRun trackingMaterialProducer10GeVNeutrino_ForPhaseII.py
cmsRun TrackingMaterialAnalyser.py
```

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by Dr15Jones** [comment]
@silviodonato 
This pull request added the file ```SimTracker/TrackerMaterialAnalysis/test/TrackingMaterialAnalyser.py```

while the file ```SimTracker/TrackerMaterialAnalysis/test/trackingMaterialAnalyser.py``` already exists in the repository. Files names differing only by capitalization are not allowed as they cause serious problems on file systems which are case-insensitive (like Windows and Macs).

Please fix this problem.

**Comment by makortel** [comment]
Apparently the capitalized one is being renamed in #30282.

@smuzaffar Should we think about how to catch such cases earlier?

**Pull request merged**
