### PR TITLE
Update muon shower (un)packing function with new specification

### PR DESCRIPTION
**Pull request by dinyar**
#### PR description:

Received a new shower bit mapping from proponents and updated the (un)packing function accordingly.

#### PR validation:

Ran `scram b runtests` and  `runTheMatrix.py -l limited -i all --ibeos`.

### CODE REVIEW

**Comment by rekovic** [comment]
please test

**Comment by rekovic** [comment]
@cmsbuild, please test

**Comment by rekovic** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
