### PR TITLE
expand 2017 wf list for IB

### PR DESCRIPTION
**Pull request by slava77**
add 2017
(ele guns 10, 35, 1000; pho guns 10, 35; mu guns 1, 10, 100, 1000, QCD 3TeV, QCD Flat)
This will also help to keep the input files in cmsbuild eos space,
since these are actively used in local MC checkout of pull requests.

### CODE REVIEW

**Comment by davidlange6** [comment]
please propose to remove roughly the same cpu from elsewhere..

**Comment by slava77** [comment]
OK, I'll take a look. 

lack of this slows down tests and signoff of reco PRs (requires manual edits of das queries to drop CERN T2 and then fight with failures in xrootd). Until a few days ago the samples were apparently still at CERN, so it didn't come up.

**Comment by davidlange6** [comment]
just to be clear - I'm all for adding more 2017

**Comment by kpedro88** [comment]
@davidlange6 I did recently remove ~10 IB WFs for 2023 in #18524 (though this was mostly to make room for the ever-expanding menagerie of new geometry variations...)

**Comment by davidlange6** [comment]
ah - but if its IB tests, it matters less - sorry I misread IB for PR somehow

**Comment by slava77** [comment]
On 5/5/17 6:56 AM, David Lange wrote:
> ah - but if its IB tests, it matters less - sorry I misread IB for PR
> somehow

Yes, it's in the PR title :)

**Comment by slava77** [comment]
On 5/5/17 6:56 AM, David Lange wrote:
> ah - but if its IB tests, it matters less - sorry I misread IB for PR
> somehow
>> On May 5, 2017, at 3:53 PM, Kevin Pedro <notifications@github.com> wrote:
>> 
>> @davidlange6 I did recently remove ~10 IB WFs for 2023 in #18524 (though this was mostly to make room for the ever-expanding menagerie of new geometry variations...)

If cleanup is still needed, even after the scope of the list is clear,
I was going to propose to thin out some of the 2015 data  and maybe even
some run-1.

**Comment by davidlange6** [comment]
> On May 5, 2017, at 5:21 PM, Slava Krutelyov <notifications@github.com> wrote:
> 
> On 5/5/17 6:56 AM, David Lange wrote:
> > ah - but if its IB tests, it matters less - sorry I misread IB for PR
> > somehow
> >> On May 5, 2017, at 3:53 PM, Kevin Pedro <notifications@github.com> wrote:
> >> 
> >> @davidlange6 I did recently remove ~10 IB WFs for 2023 in #18524 (though this was mostly to make room for the ever-expanding menagerie of new geometry variations...)
> 
> If cleanup is still needed, even after the scope of the list is clear,
> I was going to propose to thin out some of the 2015 data and maybe even
> some run-1.

anything thought to be useful to test should stay on the list... indeed 2015 data is getting less and less in that category I guess.

**Comment by davidlange6** [comment]
please test

**Comment by kpedro88** [comment]
+1

**Pull request merged**
