### PR TITLE
 Remove duplicate pixels [12.4.x]

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Backport of #37559 by @ferencek .

> This PR completely removes all duplicate pixels from the clustering step. This is an alternative to https://github.com/cms-sw/cmssw/pull/37496 where charges from duplicate pixels are summed up.
>
> No changes are expected in MC samples. In the data there could be some tiny differences in case some duplicate pixels appear.

#### PR validation:

> Code compiles :)

#### If this PR is a backport please specify the original PR and why you need to backport that PR.

Backport of #37559 for data taking.

### CODE REVIEW

**Comment by fwyzard** [comment]
type bugfix

**Comment by fwyzard** [comment]
backport #37559

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
urgent

**Comment by fwyzard** [comment]
Needed for data taking for compatibility with #38947

**Comment by qliphy** [comment]
Should comments brought in the master PR be also included here?
https://github.com/cms-sw/cmssw/pull/37559#discussion_r936381817

**Comment by fwyzard** [comment]
I think we can simply avoid considering and merging this until we converge on #37559 .

**Comment by fwyzard** [comment]
hold

**Comment by fwyzard** [comment]
please test

**Comment by jpata** [comment]
+reconstruction
- a direct backport of https://github.com/cms-sw/cmssw/pull/37559, required for datataking (see inline for the discussion)

**Comment by jpata** [comment]
@fwyzard is it still on hold from your side? if not, would you mind doing "unhold"?

**Comment by fwyzard** [comment]
Apologies - no, this should be fine now.

**Comment by fwyzard** [comment]
unhold

**Pull request merged**
