### PR TITLE
miniAOD fixes from e/gamma merged together for 7412patch2

### PR DESCRIPTION
**Pull request by davidlange6**
#11232, #11262, #11282 combined and put on branch for 7_4_12_patch2

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test
just to have a combined checkpoint

**Comment by davidlange6** [comment]
We don't have an ib to test with



On Sep 18, 2015, at 2:51 PM, Slava Krutelyov <notifications@github.com<mailto:notifications@github.com>> wrote:


@cmsbuild<https://github.com/cmsbuild> please test
just to have a combined checkpoint

**Comment by slava77** [comment]
ah, I missed that it's branching off

**Comment by smuzaffar** [comment]
as requested by @davidlange6 , I am merging it and starting CMSSW_7_4_12_patch2

**Pull request merged**
