### PR TITLE
Add "one loose" showers from EMTF and "two loose showers in different sectors" from uGMT to L1Tntuples

### PR DESCRIPTION
**Pull request by dinyar**
#### PR description:

This PR adds the newly added "one loose" showers that are produced at the EMTF level and the "two loose in different sectors" produced in the uGMT to the L1TNtuples.

(mostly for @elfontan, but this might also be useful for @eyigitba)

#### PR validation:

Ran with command `cmsDriver.py l1Ntuple -s RAW2DIGI --python_filename=data_def.py -n 10000 --no_output --era=Run3 --data --conditions=124X_dataRun3_Prompt_v4  --customise=L1Trigger/Configuration/customiseReEmul.L1TReEmulFromRAW --customise=L1Trigger/L1TNtuples/customiseL1Ntuple.L1NtupleRAWEMU --filein=/store/data/Commissioning2023/Cosmics/RAW/v2/000/365/300/00000/0bee10f0-6e0c-4efd-9ab5-c58993f0b709.root --fileout=HMT_Cosmics_L1Ntuple.root` (provided by @elfontan, thanks for that!). Looking at the resulting NTuple I saw one loose shower from EMTF in every event (this was somewhat surprising to me, but the code is quite straightforward and I'm not sure how loose the thresholds are.. ), I saw two loose showers in different sectors for about 42% of events.

### CODE REVIEW

**Comment by dinyar** [comment]
One more question: should this also be backported to 13_0_X? I had suspected that it doesn't need to be, but let me know if it would be useful.

**Comment by aloeliger** [comment]
please test

**Comment by aloeliger** [comment]
@dinyar This isn't emulation/something that is going to be needed for running at P5/T0 is it? If not I think we can forgo the back port to 13_0?

**Comment by elfontan** [comment]
Hey @dinyar @aloeliger,
thanks for this!
I agree that it is probably not strictly needed, but my personal preference would to have a coherent status of the code and changes between 130X and 131X, if possible, to avoid any confusion or misunderstanding in the future... 

Cheers,
--Elisa

**Comment by aloeliger** [comment]
Okay, understood. We can check with ORP if they would be okay on a back port of these changes, but I would guess that the preference is only those things strictly necessary in data taking operations are back ported.

**Comment by aloeliger** [comment]
+l1

**Comment by perrotta** [comment]
> Okay, understood. We can check with ORP if they would be okay on a back-port of these changes, but I would guess that the preference is only those things strictly necessary in data taking operations are back-ported.

Since this only touches the L1TNtuples, and the update is also not too complicated, I don't think there are counterindications in backporting it in the data taking release. Provided it can really help L1T operations somehow, of course.

**Comment by perrotta** [comment]
+1

**Pull request merged**
