### PR TITLE
Add Lumisection Ouputs for `das-up-to-nevents.py`

### PR DESCRIPTION
**Pull request by AdrianoDee**
#### PR description:

This PR proposes:
- extra `100k` golden data wfs;
- add an option to `das-up-to-nevents.py` to dump the json of runs+lumisections for the selected files.
- to use this option for all the golden workflows (this is needed to properly handle the wfs when submitting with the RelVal machine);
- a fix for the issue renaming them to  RunPark2{Muon|Electron}*. The golden data wfs using `ParkingDouble{Muon|Electron}*` .

#### PR validation:

Golden wfs, e.g. `2024.100005`, run.

### CODE REVIEW

**Comment by AdrianoDee** [comment]
please test

**Comment by AdrianoDee** [comment]
please test

**Comment by AdrianoDee** [comment]
+pdmv

**Comment by Moanwar** [comment]
+Upgrade

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
