### PR TITLE
boost::enable_if and boost::bind replacements

### PR DESCRIPTION
**Pull request by davidlange6**
#### PR description:

replaced a few boost constructs with c++11 replacements

#### PR validation:

code compiles and example workflows run

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by perrotta** [comment]
+1
- Technical
- Jenkins tests pass

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Comment by santocch** [comment]
+1

**Pull request merged**
