### PR TITLE
Fix Puppi MET and smearing MET correction, add central test for the MET tool (81X)

### PR DESCRIPTION
**Pull request by mmarionncern**
Same as #13954 for 81X

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by mmusich** [comment]
this branch has conflicts

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
+1

For #13955 fc8b57c48d53e1148340de163f01e9737845227a

Fixing PUPPI MET in Mini-AOD.

#13954 is the 80X version of this PR, and it has already been approved.

The code changes are satisfactory. Jenkins tests against baseline CMSSW_8_1_X_2016-04-13-1100 show only the expected differences in PUPPI MET. An extended test for #13954 shows similar results.

**Pull request merged**
