### PR TITLE
Removal of `DTRecoUncertaintiesRcd` from all GTs

### LINKED ISSUE #23: Remove DTRecoUncertaintiesRcd tags
Consumption of these tags was removed in
https://github.com/cms-sw/cmssw/pull/35208

HN request to remove the tags here
https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/4461.html

### PR DESCRIPTION
**Pull request by tvami**
Removal of `DTRecoUncertaintiesRcd` from all GTs

#### PR description:

The obsolete record of `DTRecoUncertaintiesRcd` was removed from all 12_1_X GTs. Request can be seen in the HN msg of [1] and the diffs between the previous and new GTs in [2], as expected it's only in this `DTRecoUncertaintiesRcd` record. Please note that there is a +2 in the version numbering, that is because first the wrong record was removed. I kept the commit for historical reasons. 

[1] 
https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/4461.html

[2]
Diff GT - New GT
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mcRun1_design_v2/121X_mcRun1_design_v4
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mcRun1_realistic_v2/121X_mcRun1_realistic_v4
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mcRun1_HeavyIon_v2/121X_mcRun1_HeavyIon_v5
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mcRun2_startup_v2/121X_mcRun2_startup_v4
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mcRun2_asymptotic_l1stage1_v2/121X_mcRun2_asymptotic_l1stage1_v4
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mcRun2_design_v2/121X_mcRun2_design_v4
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mcRun2_asymptotic_preVFP_v2/121X_mcRun2_asymptotic_preVFP_v4
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mcRun2_asymptotic_v2/121X_mcRun2_asymptotic_v4
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mcRun2cosmics_asymptotic_deco_v2/121X_mcRun2cosmics_asymptotic_deco_v4
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mcRun2_HeavyIon_v2/121X_mcRun2_HeavyIon_v4
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mcRun2_pA_v2/121X_mcRun2_pA_v4
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_dataRun2_v2/121X_dataRun2_v4
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_dataRun2_HEfail_v2/121X_dataRun2_HEfail_v4
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_dataRun2_relval_v2/121X_dataRun2_relval_v4
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_dataRun2_PromptLike_HI_v2/121X_dataRun2_PromptLike_HI_v4
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_dataRun3_HLT_v2/121X_dataRun3_HLT_v4
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_dataRun2_HLT_relval_v2/121X_dataRun2_HLT_relval_v4
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_dataRun3_Express_v2/121X_dataRun3_Express_v4
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_dataRun3_Prompt_v2/121X_dataRun3_Prompt_v4
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_dataRun3_v2/121X_dataRun3_v4
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mc2017_design_v2/121X_mc2017_design_v4
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mc2017_realistic_v2/121X_mc2017_realistic_v4
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/120X_mc2017_realistic_forppRef5TeV_v2/120X_mc2017_realistic_forppRef5TeV_v2
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mc2017cosmics_realistic_deco_v2/121X_mc2017cosmics_realistic_deco_v4
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mc2017cosmics_realistic_peak_v2/121X_mc2017cosmics_realistic_peak_v4
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_upgrade2018_design_v2/121X_upgrade2018_design_v4
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_upgrade2018_realistic_v2/121X_upgrade2018_realistic_v4
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_upgrade2018_realistic_RD_v2/121X_upgrade2018_realistic_RD_v4
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_upgrade2018_realistic_HI_v2/121X_upgrade2018_realistic_HI_v4
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_upgrade2018_realistic_HEfail_v2/121X_upgrade2018_realistic_HEfail_v4
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_upgrade2018cosmics_realistic_deco_v4/121X_upgrade2018cosmics_realistic_deco_v6
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_upgrade2018cosmics_realistic_peak_v2/121X_upgrade2018cosmics_realistic_peak_v4
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mcRun3_2021_design_v4/121X_mcRun3_2021_design_v6
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mcRun3_2021_realistic_v5/121X_mcRun3_2021_realistic_v7
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mcRun3_2021cosmics_realistic_deco_v5/121X_mcRun3_2021cosmics_realistic_deco_v7
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mcRun3_2021_realistic_HI_v5/121X_mcRun3_2021_realistic_HI_v7
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mcRun3_2023_realistic_v4/121X_mcRun3_2023_realistic_v6
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mcRun3_2024_realistic_v4/121X_mcRun3_2024_realistic_v6
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mcRun4_realistic_v2/121X_mcRun4_realistic_v4

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Not a backport and no backport is needed.

cc. @namapane 

resolves https://github.com/cms-AlCaDB/AlCaTools/issues/23

### CODE REVIEW

**Comment by tvami** [comment]
test parameters:
  - workflows = 140.0,200.0,202.0,203.0,204.0,205.0,4001.0,4006.0,4007.0,4008.0,11634.0,12434.0,12834.0,1325.516,50200.0,7.22,145.0,281.0,10424.0,7.21,11224.0,250200.182,11024.2,7.4,12034.0,7.23,159.0,12834.0,7.24

**Comment by tvami** [comment]
@cmsbuild , ping

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by francescobrivio** [comment]
> test parameters:
> 
>     * workflows = 140.0,200.0,202.0,203.0,204.0,205.0,4001.0,4006.0,4007.0,4008.0,11634.0,12434.0,12834.0,1325.516,50200.0,7.22,145.0,281.0,10424.0,7.21,11224.0,250200.182,11024.2,7.4,12034.0,7.23,159.0,12834.0,7.24

@tvami we should probably include `136.897` as well (the new RUn3 offline WF with CRUZET data).

**Comment by tvami** [comment]
> > test parameters:
> > ```
> > * workflows = 140.0,200.0,202.0,203.0,204.0,205.0,4001.0,4006.0,4007.0,4008.0,11634.0,12434.0,12834.0,1325.516,50200.0,7.22,145.0,281.0,10424.0,7.21,11224.0,250200.182,11024.2,7.4,12034.0,7.23,159.0,12834.0,7.24
> > ```
> 
> @tvami we should probably include `136.897` as well (the new Run3 offline WF with CRUZET data).

Good point

**Comment by tvami** [comment]
test parameters:
  - workflows = 140.0,200.0,202.0,203.0,204.0,205.0,4001.0,4006.0,4007.0,4008.0,11634.0,12434.0,12834.0,1325.516,50200.0,7.22,145.0,281.0,10424.0,7.21,11224.0,250200.182,11024.2,7.4,12034.0,7.23,159.0,12834.0,7.24,136.897

**Comment by tvami** [comment]
@namapane @cms-sw/dqm-l2 
it seems some DQM clients use this tag!

The following two unit tests failed
```
src/DQM/Integration/test/TestDQMOnlineClient-dt4ml_dqm_sourceclient
src/DQM/Integration/test/TestDQMOnlineClient-dt_dqm_sourceclient
```
with this error
```
----- Begin Fatal Exception 23-Sep-2021 18:29:41 CEST-----------------------
An exception of category 'NoRecord' occurred while
   [0] Processing  Event run: 334393 lumi: 1 event: 16285 stream: 0
   [1] Running path 'dtDQMPathPhys'
   [2] Calling method for module DTRecHitProducer/'dt1DRecHits'
Exception Message:
No "DTRecoConditionsUncertRcd" record found in the EventSetup.n
 Please add an ESSource or ESProducer that delivers such a record.
 ```

**Comment by mmusich** [comment]
there's also plenty of failures in the HLT tests: https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-3298b2/18866/addOnTests/runall-report.log

e.g.

https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-3298b2/18866/addOnTests/hlt_data_Fake/cmsDriver.py_RelVal_-s_HLT:Fake,RAW2DIGI,L1Reco,RECO_--data_--scenario=pp_-n_10_--conditions_auto:run1_data_Fake_--relval_9000,50_--datatier_RAW-HLT-.log

**Comment by tvami** [comment]
Yes it seems like when `DTRecHitProducer/'dt1DRecHits'` is used this tag is consumed

**Comment by tvami** [comment]
Oh I think I see what's happening...
https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/4461.html
I followed the subject title... and the subject title is the opposite from the body of the email...

**Comment by tvami** [comment]
I've updated the GT, the title, the description (and notified the HN)

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by namapane** [comment]
> 
> 
> Oh I think I see what's happening...
> https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/4461.html
> I followed the subject title... and the subject title is the opposite from the body of the email...

Right... the two are named confusingly similarly and indeed I put the wrong one in the subject (while, ironically, I warned about possible confusion in the body...)

**Comment by malbouis** [comment]
+alca

**Comment by perrotta** [comment]
+1

**Pull request merged**
