### PR TITLE
HLT menu development for `12_5_X` (2/N) [`13_0_X`]

### PR DESCRIPTION
**Pull request by missirol**
#### PR description:

Development of HLT menus for `CMSSW_12_5_X`.

This is the PR for the `master` branch, which will then be backported down to `12_5_X` (the latter is the release cycle currently used for HLT-menu development for Run 3).

This PR includes the integration of the following JIRA tickets.

  - [CMSHLT-2581](https://its.cern.ch/jira/browse/CMSHLT-2581): [HIon] Fixes to the HIon V1.0 menu after 2022 HIon test run

It also includes the following updates.

 - The `HLTDebug*` (offline) EventContents, used in data tiers like `FEVTDEBUGHLT`, are updated removing the collections of the `DQMGPUvsCPU` stream, as a result of the discussion in #40110 and #40136.

 - The pp L1T menu used in HLT-AddOn and HLT-Validation tests is updated (for the relevant non-frozen menus) to the last L1T menu to be used for 2022 pp data-taking (see [CMSLITDPG-980](https://its.cern.ch/jira/browse/CMSLITDPG-980?focusedCommentId=4634706&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-4634706)): [`L1Menu_Collisions2022_v1_4_0`](https://htmlpreview.github.io/?https://github.com/cms-l1-dpg/L1MenuRun3/blob/69232a5846364040dddedc084b0350ed4fa3c9c7/development/L1Menu_Collisions2022_v1_4_0/L1Menu_Collisions2022_v1_4_0.html) (tag in `CondDB`: [`L1Menu_Collisions2022_v1_4_0-d1_xml`](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/tags/L1Menu_Collisions2022_v1_4_0-d1_xml)).

#### PR validation:

TSG tests.

#### If this PR is a backport, please specify the original PR and why you need to backport that PR. If this PR will be backported, please specify to which release cycle the backport is meant for:

`CMSSW_12_5_X`
`CMSSW_12_6_X`

### CODE REVIEW

**Comment by missirol** [comment]
enable gpu

To test the EventContent change in GPU workflows.

**Comment by missirol** [comment]
please test

**Comment by missirol** [comment]
please abort

Tests seem partly stuck (I see they are proceeding in other PRs), so I'll try to restart them.

**Comment by missirol** [comment]
please test

**Comment by missirol** [comment]
+hlt

  - differences in the outputs of PR tests are in line with the update of the HLT GRun menu, and the update of the `HLTDebug*` EventContents (see https://github.com/cms-sw/cmssw/pull/40155#issuecomment-1328026871)

PS. An earlier `comparison` test seems stuck on the Jenkins side.

**Comment by perrotta** [comment]
+1

**Pull request merged**
