### PR TITLE
[RFC] Add updated but "off" FastSim pixel resolution histograms infrastructure

### PR DESCRIPTION
**Pull request by lcorcodilos**
#### PR description:

This PR adds the infrastructure to use the FastSim pixel resolution histograms that were recently submitted to cms-data in this PR [1]. These are based on UL pixel simulation but will **not** be used in the UL FastSim production which has already begun. 

This PR is just meant to preserve the work that was done and to make the new resolution histograms easily accessible in the future with the hard-coded boolean `ULresolutionHistograms` which is set to `False`. As result, this PR should produce no change.

[1] - https://github.com/cms-data/FastSimulation-TrackingRecHitProducer/pull/4

#### Known issues/need for feedback

The new resolution histograms have been prepared for each year but the modifiers used to this point have been "per-phase". So in the case of Phase 1, the modifier needs to be different depending on the era. I currently have it coded as 

```python
    from Configuration.Eras.Era_Run2_2017_FastSim_cff import Run2_2017_FastSim
    Run2_2017_FastSim.toModify(fastTrackerRecHits, plugins = pixelPlugins2017UL)

    from Configuration.Eras.Era_Run2_2018_FastSim_cff import Run2_2018_FastSim
    Run2_2018_FastSim.toModify(fastTrackerRecHits, plugins = pixelPlugins2018UL)
```
but this obviously does not work - it just conveys the intention. We could use feedback on the best way to accomplish this implementation.

#### PR validation:

The following have been run successfully:
```
scram build code-checks
scram build code-format
scram b runtests
```

I also ran `runTheMatrix.py -l limited -i all --ibeos` but see failures that appear to be unrelated to these changes.

### CODE REVIEW

**Comment by lcorcodilos** [comment]
@tvami @pmaksim1 @sbein @OzAmram

**Comment by tvami** [comment]
@cmsbuild , please test with cms-data/FastSimulation-TrackingRecHitProducer#4

**Comment by lcorcodilos** [comment]
I'll copy one of these tests and try to debug what's going on. Based on the changes, my suspicion is that something is going on in PixelResolutionHistograms.cc/h

**Comment by lcorcodilos** [comment]
The issue is in the use of TAxis' GetXbins() which is among the changes so that variable bin widths in cotAlpha and cotBeta are accepted. Existing resolution histograms were not all defined using an array of bin edges in which case GetXbins() returns an empty TArrayD. I've added a new version of `getBinEdges` which takes the TAxis as the argument and unpacks that to pass to the existing version which needs the bin width, lower axis edge, and number of bins.

A few other changes for other issues that came up:
- Fix implementation of histCheck which did not correctly account for `ignore_single` and `ignore_qBit`.

**Comment by tvami** [comment]
@cmsbuild , please test with cms-data/FastSimulation-TrackingRecHitProducer#4

**Comment by sbein** [comment]
please test

**Comment by smuzaffar** [comment]
test parameters:
- pull_request = cms-data/FastSimulation-TrackingRecHitProducer#4

**Comment by smuzaffar** [comment]
please test

**Comment by tvami** [comment]
Hi @lcorcodilos can you look into this error "Histogram (cot�lpha=0.0863589, cot�eta=3.7315, nQbin=1) was not found for PixelTemplateSmearer. Check if the smearing resolution histogram exists."

**Comment by lcorcodilos** [comment]
The latest commit fixes RelVal 5.1. I'm now testing 135.4. There were some fixes to basic logic in PixelResolutionHistograms.cc to match the previous version to get things working. That leaves me a bit concerned that the comparisons run with the UL resolution histograms are not accurate. It shouldn't affect this PR but we'd obviously like to know the impact these histograms have if someone does turn them "on".

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by smuzaffar** [comment]
please test

**Comment by civanch** [comment]
@sbein , can you comment?

**Comment by sbein** [comment]
@civanch Yes, @lcorcodilos, @pmaksim1  and I discussed this yesterday and Lucas has so far been too busy to follow up. He says he needs a week to look into issues that were raised in the validation.

**Comment by smuzaffar** [comment]
please test

**Comment by sbein** [comment]
@tvami I aim to discuss this with @pmaksim1 on Friday

**Comment by tvami** [comment]
@sbein @pmaksim1 what was the conclusion after all about this PR?

**Comment by sbein** [comment]
Hi, @tvami. @pmaksim1 said he would try to look in to it soon, but there was little development so far, since Lucas is now a foregone resource.

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
Hmmm the results in https://github.com/cms-sw/cmssw/pull/34812#issuecomment-1179775265 dont match my recollection... my recollection was that in the end we started seeing result in the central wf-s, like 5.1 but now everything upto MsgLogger looks fine. Is that now just the trick with the stats? Or the point is that in the PR the feature now is disabled by default?

**Comment by tvami** [comment]
>  the hard-coded boolean ULresolutionHistograms which is set to False. As result, this PR should produce no change.

ahh yes, ok, so the point indeed is that in the PR the feature now is disabled by default

**Comment by sbein** [comment]
Yes, the ULresolutionHistograms basically suppress all impact until someone can come and figure out what the enabled feature causes significant changes to physics observables, e.g., @pmaksim1 and company.

**Comment by tvami** [comment]
>  t until someone can come and figure out why the enabled feature causes significant changes to physics observables, e.g., pmaksim1 and company.

Yes, we have somebody starting to work on it, @ammitra

**Comment by smuzaffar** [comment]
Milestone for this pull request has been moved to CMSSW_14_0_X.Please open a backport if it should also go in to CMSSW_13_3_X.

**Comment by tvami** [comment]
@cmsbuild , please close
 * Lucas left the field, there are several things to debug, a new PR can be opened when those issues are resolved

**Pull request closed without merging**
