### PR TITLE
[PhysicsTools/FWLite] Solve warning found by gcc 5.3.0

### PR DESCRIPTION
**Pull request by ghost**
https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc6_amd64_gcc530/CMSSW_8_1_X_2016-03-02-1100/PhysicsTools/FWLite
The behavior is unchanged, the parentheses makes clear the order of the logical operation while suppressing the warning.

### CODE REVIEW

**Comment by degano** [comment]
please test

**Comment by davidlt** [comment]
This should be wrong. Logical not should be applied to a full condition.`m_optionsType` seems to hold up to 32 options/flags. Only one is available in general, just `kEventContOpt`. It really wants to check if `kEventContOpt` is not set in `m_optionsType`.

**Comment by degano** [comment]
I don't know if it's wrong. The change I made does not change the behavior. If it was wrong in the first place then the maintainer of the package should tell us.

**Comment by smuzaffar** [comment]
Agree, looks like the intended behaviour is to achieve
```
(! (m_optionsType & kEventContOpt))
```
I would suggest to update the PR and wait for analysis L2 to approve it.

**Comment by davidlange6** [comment]
@Dr15Jones - is this a fwk package? (unchanged since years)

**Comment by davidlange6** [comment]
ping @Dr15Jones

**Comment by Dr15Jones** [comment]
This is not considered a framework package.

**Comment by Dr15Jones** [comment]
I agree with Shahzad that the present change doesn't match the intended behaviour (although it matches what the compiler is doing).

**Pull request closed without merging**
