### PR TITLE
Run3-gex28 Take care of namespace issue for EB numbering in dd4hep

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Take care of namespace issue for EB numbering in dd4hep (also solves the issue of units)

#### PR validation:

Tested along with #31886 and #31919

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by ianna** [comment]
urgent

**Comment by civanch** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
