### PR TITLE
Add relval for b parking skim 102x

### PR DESCRIPTION
**Pull request by kfjack**
Back port of bparking skim to 102X + adding relval tests.
Merging the files/updates from PR #25995, PR #25892, and PR #26035 

Workflow 136.898 to be tested.

@gkaratha and @bainbrid --- this should replace PR #25995.

### CODE REVIEW

**Comment by fabiocos** [comment]
code-checks

**Comment by fabiocos** [comment]
please test workflow 136.898,136.8501,10824.8

**Comment by fabiocos** [comment]
apart for spaces it is fully consistent with my test backport https://github.com/fabiocos/cmssw/tree/fc-bp26035

**Comment by kfjack** [comment]
Hi all, I think the parting skim part looks okay technically. 

Could @gkaratha and @bainbrid double check the contents? 
The files are available at https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-26038/33351/runTheMatrix-results/136.898_RunParkingBPH2018B+RunParkingBPH2018B+HLTDR2_2018+RECODR2_2018reHLT_skimParkingBPH_Prompt+HARVEST2018/
Many thanks.

**Comment by kfjack** [comment]
Hi all, I think the B parking skim part looks okay technically.

Could @gkaratha and @bainbrid double check the contents?
The files are available at https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-26038/33351/runTheMatrix-results/136.898_RunParkingBPH2018B+RunParkingBPH2018B+HLTDR2_2018+RECODR2_2018reHLT_skimParkingBPH_Prompt+HARVEST2018/
Many thanks.

**Comment by gkaratha** [comment]
Dear @kfjack ,

Thanks for your help! I appreciated. I checked the file like last time and it runs fine[*].Thanks again.

Best regards,
George

[*] TrigReport Events total = 8 passed = 4 failed = 4

**Comment by kfjack** [comment]
Hi all, I think this PR is fine and we can merge if it is also okay for everyone. Many thanks.

**Comment by prebello** [comment]
+1

**Comment by fabiocos** [comment]
@kpedro88 this is not strictly upgrade specific, anyway please have a look and sign it in case. I would like to merge it for next IB at this point, if no problem is seen in master for #26035 (as I expect)

**Comment by kpedro88** [comment]
+upgrade

**Comment by fabiocos** [comment]
+1

**Pull request merged**
