### PR TITLE
Run2-hcx174 HcalDetId is meant for HB/HE/HO/HF only

### PR DESCRIPTION
**Pull request by bsunanda**
Avoids the warnings in HcalUnpack

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@fabiocos Sorry Fabio for touching DetId.h again

**Comment by bsunanda** [comment]
@civanch Please approve this PR

**Comment by civanch** [comment]
+1

**Comment by bsunanda** [comment]
@fabiocos Could you please merge this?

**Comment by fabiocos** [comment]
+1

**Pull request merged**
