### PR TITLE
Adding subGenJets to NanoGEN

### PR DESCRIPTION
**Pull request by arizzi**
#### PR description:

This PR adds the SubGenJets to NANOGEN.

#### PR validation:

Tested on 13_X and produces the expected collections

SubGenJetAK8_pt 7.87129 1.35149
SubGenJetAK8_eta 7.89604 1.2970
SubGenJetAK8_phi 7.89604 1.2970
SubGenJetAK8_mass 7.92079 1.242
nSubGenJetAK8 7.33168 0.925743

### CODE REVIEW

**Comment by hqucms** [comment]
enable nano

**Comment by hqucms** [comment]
please test

**Comment by hqucms** [comment]
+1

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
