### PR TITLE
backport of #13594: Gsf cleanup and debug

### PR DESCRIPTION
**Pull request by fwyzard**
backport of #13594 (Gsf cleanup and debug) to CMSSW 8.0.x

### CODE REVIEW

**Comment by fwyzard** [comment]
tracked at #15151

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
from a quick test on 1k events, I see
  - 1 difference in HLT results
  - no improvement in timing

**Comment by slava77** [comment]
@fwyzard 
no timing improvement should mean no backport.
What are the arguments to still apply it to 80X?

**Comment by fwyzard** [comment]
Well, actually I'm just going through the list of PRs that were suggested to be backported.
Of course, if there is no gain we should not backport it - but I'd like to make some higher statistics checks, and/or try a different sample, because I have seen very few HLT accepts in my test, much less than expected.

**Comment by slava77** [comment]
On 7/22/16 5:54 AM, Andrea Bocci wrote:
> Well, actually I'm just going through the list of PRs that were
> suggested to be backported.

OK, we are on the same page for this.

**Comment by fwyzard** [comment]
@slava77 @cvuosalo should I worry about this error ?

**Comment by slava77** [comment]
@fwyzard 
you can ignore
``` ---> test testRecoMETMETProducers had ERRORS ```
it fails in IB as well. We have been slow in fixing it.

**Comment by slava77** [comment]
@fwyzard 
if this PR is included in #15279 , please close this PR.

**Comment by fwyzard** [comment]
yes, this is fully included in #15279

**Pull request closed without merging**
