### PR TITLE
[BeamSpot] fit 1D projections of PV distribution to get initial values for 3D fit parameters

### PR DESCRIPTION
**Pull request by rmanzoni**
back porting https://github.com/cms-sw/cmssw/pull/10780

### CODE REVIEW

**Comment by slava77** [comment]
@rmanzoni please clarify on the importance of the fix for the current data taking.
If it's not very important, it will be integrated after 25ns startup is over.

**Comment by rmanzoni** [comment]
Hi @slava77,

the beam spot fit failures affect the beam spot determination run in the prompt calibration loop. If the failure rate gets large enough, typically when the actual beam spot position is vary far off the a priori position hard coded in the module, the impact on prompt calibration could be substantial.

Two examples:

1. https://hypernews.cern.ch/HyperNews/CMS/get/beamspot/135.html about 20% of the fits failed because of this reason

2. https://hypernews.cern.ch/HyperNews/CMS/get/beamspot/137.html a particularly nasty situation occurred at LS124, where the fit converged to a secondary minimum and the resulting BS Z position was  -8. cm with a tiny error, so tiny that when (weighted) averaged out over the full run set the Z to be around -6. cm, while for the rest of the run it was correctly estimated to be around -1.3 cm

**Comment by slava77** [comment]
Riccardo, thank you for the explanation.
It sounds like the short answer is "we want it included as soon as possible"
@davidlange6

**Comment by sushilchauhan** [comment]
These changes will also be important for online beamspot because we also see similar fit failure issue as mentioned by Ricardo here. I already check in a previous collision run and it worked fine.

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by diguida** [comment]
@slava77 we agree with your executive summary.

**Comment by cvuosalo** [comment]
@cmsbuild please test
Try again, hoping for no more DAS errors

**Comment by diguida** [comment]
+1
for https://github.com/cms-sw/cmssw/commit/49541a69a4cba182620a8a22730339682126d499
￼￼￼￼￼￼￼
25202.0 comparison

The correspondent version in 76X #10780 has already been approved by AlCa.￼

**Comment by diguida** [comment]
￼

**Comment by cvuosalo** [comment]
+1

For #10782 49541a69a4cba182620a8a22730339682126d499

Changing the initial values of the primary vertex fit. The 75X and 76X versions of this PR, #10781 and #10780, have already been approved by Reco.

The code changes are satisfactory. Jenkins tests against baseline CMSSW_7_4_X_2015-08-14-1100 show very small changes in PV fit results, but none of these differences are significant. See above and #10780 for example plots of the small changes in the fit results.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
