### PR TITLE
New ES calibrations tags due to updated PF ES clustering to include calibration in case of dead planes

### PR DESCRIPTION
**Pull request by amartelli**
Changes in the preshower cluster energy recostruction to include ES single plane calibration in case of dead planes and data to mc energy scale factors  #12929

### CODE REVIEW

**Comment by mmusich** [comment]
@amartelli I actually meant that you pull my commit in your PR. Without your changes in the source this PR will produce inconsistent results.

**Comment by mmusich** [comment]
please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/13074	e597082
- code changes are OK. This is a replacement to https://github.com/cms-sw/cmssw/pull/12929	e89d235 with addition of the new GTs.
- jenkins tests pass and comparisons with baseline show small differences in data workflows; the most significant difference is in 2015 ES hit energy (which doesn't propagate to a significant change in downstream quantities)
e.g. 134.911
wf134 911_eshit_energy
- local tests in CMSSW_8_0_0_pre5 with more events and a lager set of samples confirms behavior observed in jenkins. Comparing to results in https://github.com/cms-sw/cmssw/pull/12929	e89d235, there are no differences in run1 and run2 MC and data; there is an update in 2017 MC (10039.0) which no leads to no change with respect to the baseline, as expected the 2017 GT is updated now.
- failures in the addOn tests can be ignored, they are due to a missing input file, unrelated to this PR.

@amartelli please edit the first block of this PR (at the top of the page) and put the details about the code changes from #12929.

**Comment by Martin-Grunewald** [comment]
please test
(HIon problem should be solved)

**Comment by slava77** [comment]
@amartelli 
please keep the PR subject shorter (it should not be much longer than your typical email message subject or a paper title).
The current "Introducing new ES calibrations tags due to updated PF ES clustering. Changes in the preshower cluster energy reconstruction are meant to include the ES single plane calibration in case of dead planes and data-to-mc energy scale factors" is too verbose.
Please edit the PR description to include necessary details (it is the first block under the subject and the "Conversation", "Commits" .. tabs).

**Comment by amartelli** [comment]
ok done (the original from mmusich was already a good description)

**Comment by slava77** [comment]
On 1/27/16 6:18 AM, amartelli wrote:
> ok done (the original from mmusich was already a good description)
> 

Thank you.
The subject was OK.
I was going after the PR description, which was empty.
Sorry for the confusion.

**Comment by emanueledimarco** [comment]
@slava77 last time it happened on this PR, it was a problem of the system. Could be the case again?

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by franzoni** [comment]
+1

@emanueledimarco @amartelli @shervin86 
please follow up to the thread below



Adding the AlCa egroup.

Dear Jean,

what you say is correct, and applies to the global tags which have been actually used at HLT at P5 and in prompt production.

The GT's which we need to deploy in 80x containing the updated conditions for ES, are instead to be part of autocond and used in 80x and future releases to reconstruct and run reHLT tests over 2015 data in workflows like relvals and IB tests. Therefore a change in those GT's of the past is required to avoid a physics inconsistency.

Thanks and greetings,
Giovanni for AlCa

On Fri, 29 Jan 2016 at 13:20 Jean Fay <Jean.Fay@cern.ch> wrote:
On 29/01/2016 07:27, Giovanni Franzoni wrote : 

    Dear ECAL gurus, 

    + update the GT used for HLT to assure the consistency between 
    conditions and the 80x code being updated  when running on 2015 data 
        ->  notably, we note that ESIntercalibConstants_V07_hlt and 
    ESIntercalibConstants_Run1_Run2_V03_offline are the same for the 
    future but differ along 2015 [1] (the same holds for ESEE intercalib). 
   Dear Giovanni, 
  This is normal and will not change ! 
  hlt is used online and there is no reason to change it for the past. Furthermore it is strictly forbidden to change the past. Hence, when an offline payload is validated, it can be also introduce in hlt but only with an IOV which is "current run + 1" 
  Cheers,   Jean & Pierre

**Pull request merged**
