### PR TITLE
[12_2_X] Update CPX tune to 13.6 TeV

### PR DESCRIPTION
**Pull request by SanghyunKo**
#### PR description:

Update CPX tune to 13.6 TeV, see https://indico.cern.ch/event/1169048/#30-sample-normalization-for-cp

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Backport of #38358

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by qliphy** [comment]
please test

**Comment by qliphy** [comment]
@cms-sw/generators-l2 Please considering signing this PR.

**Comment by Saptaparna** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
