### PR TITLE
Update Run-I Global Tags with FEMapRcd and Phase-I reconstruction Geometry

### PR DESCRIPTION
**Pull request by mmusich**
# Summary of changes in Global Tags
## RunI simulation
- **RunI Ideal scenario** : [81X_mcRun1_design_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun1_design_v2) as [81X_mcRun1_design_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun1_design_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_mcRun1_design_v2/81X_mcRun1_design_v1): 
  - Added `HcalFrontEndMapRcd` for Run1 simulation
- **RunI Heavy Ions scenario** : [81X_mcRun1_HeavyIon_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun1_HeavyIon_v2) as [81X_mcRun1_HeavyIon_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun1_HeavyIon_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_mcRun1_HeavyIon_v2/81X_mcRun1_HeavyIon_v1): 
  - Added `HcalFrontEndMapRcd` for Run1 simulation
- **RunI Realistic scenario** : [81X_mcRun1_realistic_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun1_realistic_v2) as [81X_mcRun1_realistic_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun1_realistic_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_mcRun1_realistic_v2/81X_mcRun1_realistic_v1): 
  - Added `HcalFrontEndMapRcd` for Run1 simulation
- **RunI Proton-Lead scenario** : [81X_mcRun1_pA_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun1_pA_v2) as [81X_mcRun1_pA_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun1_pA_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_mcRun1_pA_v2/81X_mcRun1_pA_v1): 
  - Added `HcalFrontEndMapRcd` for Run1 simulation
## Upgrade
- **PhaseI realistic scenario** : [81X_upgrade2017_realistic_v6](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_upgrade2017_realistic_v6) as [81X_upgrade2017_realistic_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_upgrade2017_realistic_v5) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_upgrade2017_realistic_v6/81X_upgrade2017_realistic_v5): 
  - updated Phase-I Tracker Reco geometry (tag "v6" for geometry) as in #15110
- **PhaseI design scenario** : [81X_upgrade2017_design_v6](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_upgrade2017_design_v6) as [81X_upgrade2017_design_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_upgrade2017_design_v5) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_upgrade2017_design_v6/81X_upgrade2017_design_v5): 
  - updated Phase-I Tracker Reco geometry (tag "v6" for geometry) as in #15110

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by makortel** [comment]
@mmusich Thanks! For phase1 the GT diff link in your description is against `80X_upgrade2017_realistic_v5` while your intention was probably `81X_...`. (and yes, I was almost going crazy before I noticed that).

**Comment by mmusich** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
