### PR TITLE
[12.2.X] Fix Tracker Alignment Payload writing

### PR DESCRIPTION
**Pull request by mmusich**
backport of  #37925

#### PR description:

The goal of this PR is to fix a bug inadvertently introduced at https://github.com/cms-sw/cmssw/pull/36076 (aimed to migrate Alignment codes to new `PoolDBOutputService` methods).
Moving to usage of instances instead of pointers led to the `GeometryAligner::removeGlobalTransform` call (to remove global roto-translations after computation of the alignment corrections) to be ineffective. This in turn lead to large spurious rotations and shifts of the alignment output geometry with respect to the input one.
This is fixed here in commit  36d14e9b50d8ae0e960c07247d8ed0e44b47905b.

#### PR validation:

Run a small alignment campaign (copied from `mp3495`) and compared the output payloads with respect to the input one. Results (obtained from the payload inspector) are collected:
   * [here](http://musich.web.cern.ch/musich/display/comparison_PromptVsAlignmentCRAFT22/old/): before the fix
   * [here](http://musich.web.cern.ch/musich/display/comparison_PromptVsAlignmentCRAFT22/fixed/): after the fix
   
Here is a couple of plots selected from the folders above (**notice the scale**).   

| Before the fix | After the fix |
| ------------- | ------------- |
|  image | image |

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

partial backport of #37925

### CODE REVIEW

**Comment by mmusich** [comment]
type bug-fix

**Comment by mmusich** [comment]
type backport

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by francescobrivio** [comment]
urgent

 - @qliphy @perrotta this PR is a **mandatory** to fix the TkAlignment in 12_2 which is currently broken. 
   - Even tho this release cycle won't be used for data taking anymore, I think it's better to have a new 12_2 patch which includes this fix and an thus a proper TkAligment code

**Comment by tvami** [comment]
+alca

**Comment by qliphy** [comment]
+1

**Pull request merged**
