### PR TITLE
CTPPS: DAQ mapping update - backport of #14828

### PR DESCRIPTION
**Pull request by grzanka**
Backport of PR #14828 from CMSSW 81X
- CondFormats/TotemReadoutObjects/xml/ctpps_210_mapping.xml: final 2016 configuration.
- Removed example TOTEM-standalone mapping files.

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
+1

**Comment by ggovi** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
