### PR TITLE
[14.0.X] Miscellaneous fixes for dqm online clients 

### PR DESCRIPTION
**Pull request by mmusich**
backport of https://github.com/cms-sw/cmssw/pull/44384

#### PR description:

The night of 13th March 2024, [run 377827](https://cmsoms.cern.ch/cms/runs/report?cms_run=377827) was mistakenly acquired using the DQM DAQ key `hi_run` (despite having other collision keys).
This uncovered a couple of leftovers from PRs https://github.com/cms-sw/cmssw/pull/43846 and https://github.com/cms-sw/cmssw/pull/43257 that made few DQM online clients crash (see logs at [DQM square](https://cmsweb.cern.ch/dqm/dqm-square/?run=377827&db=production)).
These are fixed here. 
 
#### PR validation:

```
python3 beam_dqm_sourceclient-live_cfg.py runkey=hi_run
python3 beampixel_dqm_sourceclient-live_cfg.py runkey=hi_run
python3 pixellumi_dqm_sourceclient-live_cfg.py runkey=hi_run
```

all compile fine now.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Verbatim backport of https://github.com/cms-sw/cmssw/pull/44384 to CMSSW_14_0_X for 2024 data-taking purposes.

### CODE REVIEW

**Comment by mmusich** [comment]
type bug-fix

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mandrenguyen** [comment]
+reconstruction

**Comment by gabrielmscampos** [comment]
PR successfully tested and validated in DQM Playback machines using test set `run375631_streamHIDQM`.

image

**Comment by tjavaid** [comment]
> PR successfully tested and validated in DQM Playback machines using test set `run375631_streamHIDQM`.
> 
> image

thanks @gabrielmscampos for the additional checks!

**Comment by tjavaid** [comment]
+1

- spurious differences from `WF 12834.7` seen

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
