### PR TITLE
SiStrip Payload Inspector: alternative style Tracker Maps and code clean-up

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

This PR adds the possibility to produce and display Tracker Maps of the SiStrip detector conditions using `TH2Poly` and the `TPolyLine` vertices stored as externals (in the  `cms-data/DQM-SiStripMonitorClient` repository) in this PR: https://github.com/cms-data/DQM-SiStripMonitorClient/pull/1 via the newly introduced class `SiStripTkMaps` .
A couple of examples are implemented as well.
I profit of this PR to introduce a couple of clean-up commits:
   * 5bf310094af0cebd6bf40eda93d1457b8bd392aa migrates wherever possible to the new PayloadInspector class interfaces introduced at PR https://github.com/cms-sw/cmssw/pull/29622 
   * c0ff2c5b01ef8d89a7326ccd60377a1c25538006 makes use of the namespace `cond::payloadInspector` in all `CondCore/SiStripPlugins` in all plugins avoiding heavy repetitions in the code. 

#### PR validation:

Relies on private validation and augmented unit tests.
A couple of example outputs are pasted here:

LAMap
===
BCMap

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

This PR is not a backport and no backport is needed.

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
code-checks

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by ggovi** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
