### PR TITLE
CSJetProducer bug fix for flow modulation

### PR DESCRIPTION
**Pull request by stepobr**
#### PR description:

This is a bug fix for flow modulation in `CSJetProducer`. `minFlowChi2Prob` and `maxFlowChi2Prob` are never set and there are no specified defaults. This leads to `minProb` and `maxProb` to be always False and this way the whole flow modulation part is skipped. I'm setting appropriate default values in `fillDescriptions`, so that it works fine as long as `useModulatedRho = True`

Hopefully this can be added to 11_2_0.

@mandrenguyen @FHead

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@stepobr 
please provide in the PR description (a link to or slides with) some plots to show ak4Cs jets performance before and after the fix for self-documentation.
Thank you.

**Comment by perrotta** [comment]
In the reco [comparisons](https://github.com/cms-sw/cmssw/pull/32158#issuecomment-728478187) there are differences in the linkData of ParticleFlowBlock: they are not due to this PR, as showing up occasionally after the [latest root update](https://github.com/cms-sw/cmsdist/pull/6388#issuecomment-725620932)

On the other hand, there are no other observed differences in the tests, which is expected, because `useModulatedRho` is now set to `false`.

**Comment by stepobr** [comment]
> On the other hand, there are no other observed differences in the tests, which is expected, because `useModulatedRho` is now set to `false`.

Strange, I was expecting `useModulatedRho` to be `true` in HI workfows. Is it overwritten somewhere?

**Comment by perrotta** [comment]
> > On the other hand, there are no other observed differences in the tests, which is expected, because `useModulatedRho` is now set to `false`.
> 
> Strange, I was expecting `useModulatedRho` to be `true` in HI workfows. Is it overwritten somewhere?

@stepobr : yes, you are right, the default value is overwritten in RecoHI/HiJetAlgos/python/HiRecoPFJets_cff.py
Then, the lack of differences in the automatic tests can be due to their low stat: please provide some link to a validation which shows the effect, as also requested by @slava77 [above](https://github.com/cms-sw/cmssw/pull/32158#issuecomment-728349521)

**Comment by mandrenguyen** [comment]
Let me clarify a bit, and propose a change of strategy.
The flow modulation was introduced for an analysis of large radii jets (HIN-18-014).  Once this improvement was made, we decided to port this back into our analysis framework, and now into miniAOD.
We just realized that due to these missing parameters, the feature is not active, hence this bugfix.
However, this is also the case in our current analysis framework, which is what will be used as a baseline to validate the miniAOD.

To answer Slava's question, the most recent study was from a week ago:  
https://twiki.cern.ch/twiki/pub/CMS/HiHighPt2020/20201109_RandomCone_HighPTMeeting_YiChen.pdf

Based on random cones studies, the phi modulation is a quite minor effect for the standard R=0.4 that we run in miniAOD.
Therefore, I propose that we keep the current behavior, which we have been using or some time now, and try to activate the flow modulation for the next iteration (either Run 3 or the next reMiniAOD).
If we would like to make the code less misleading, who could keep the default parameters added by this PR and explicitly set useModulatedRho to False.

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
@mandrenguyen I think the fix is quite logical, and I don't see the reason to maintain a bugged version of the code, or some dummy parameter that reproduces it, with the only purpose of not changing the outputs. This is the master release of CMSSW, not some frozen production one.

Therefore, I'd suggest to keep the PR as it is. Of course, one has to decide whether the symmetric 90% chi2 probability is exactly what you need, but this has to be a decision of the HI group based on physics.

The only thing we are asking for is to provide some validation which shows that the fix actually propagates to the miniAOD outputs, and that they are reasonable. Since the automatic tests do not seem to show it (I imagine because of their low statistics) then please provide some distribution produced with this PR which testify its effectiveness.

**Comment by perrotta** [comment]
@stepobr @mandrenguyen please take a decision about how to proceed with this fix, so that it can be included in the next pre-release (the last open one for 11_2_X). If we decide to integrate it, please also provide an evidence that the "reasonable" parameter setting resulting form this fix propagates to the HI outputs as expected/wanted.

**Comment by mandrenguyen** [comment]
@perrotta I would prefer that we keep the flow modulation off for now.  I suggest that @stepobr set useModulatedRho to False, such that this becomes just a technical change.  We will eventually flip this feature on, but it will require more investigation first (so not for the 1st reMiniAOD campaign)

**Comment by stepobr** [comment]
@perrotta @mandrenguyen sorry for the delay, now I've set `useModulatedRho` to False

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
+1
- It fixes the previous bugged configuration assignments for the chi2 prob boundaries
- Flow modulation is switched off, in order to reproduce the result of the previous settings: this feature will be eventually enabled when further studies will become available
- Jenkins tests pass and show no differences, as expected

**Comment by qliphy** [comment]
+1

**Pull request merged**
