### PR TITLE
Suppress warnings from ONNXRuntime

### PR DESCRIPTION
**Pull request by hqucms**
Change ONNXRuntime logging level to `ORT_LOGGING_LEVEL_ERROR`.
This should fix https://github.com/cms-sw/cmsdist/pull/5857#issuecomment-634030814.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by mrodozov** [comment]
@slava77 I think we broke the IB with the last LLVM update somehow :/

**Comment by slava77** [comment]
> @slava77 I think we broke the IB with the last LLVM update somehow :/

OK, thanks for reminding, 
is the fix expected in CMSSW_11_2_X_2020-05​-26-1700 ?

**Comment by smuzaffar** [comment]
yes 17h IB should be good for tests.

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/29989	1978626
- moving to less verbose (error only) setup
- jenkins tests pass and in combination with cms-sw/cmsdist#5857 there are no additional warnings

this PR can be merged by itself

**Comment by santocch** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
