### PR TITLE
[12_4_X] Add CSCCluster skim config

### PR DESCRIPTION
**Pull request by kakwok**
#### PR description:

This is a backport of #37782
This PR adds the config for a RAW-AOD skim for the CSC clusters events, based on new LLP trigger paths.  
The CSC cluster skim saves the following collections in addition to standard RAW-AOD output:
```
csc2DRecHits
dt1DRecHits
```
The CSC cluster skim selects events passing the following HLT paths, which is already included in the HLT v2 menu:
```
HLT_CscCluster_Loose_v*
HLT_CscCluster_Medium_v*
HLT_CscCluster_Tight_v*
HLT_L1CSCShower_DTCluster50_v2
HLT_L1CSCShower_DTCluster75_v2
```
[HLT Jira ticket](https://its.cern.ch/jira/browse/CMSHLT-2279)

#### PR validation:

same as #37782

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

This is a backport of #37782

### CODE REVIEW

**Comment by tvami** [comment]
urgent
 * should go into 12_4_4

**Comment by tvami** [comment]
backport of https://github.com/cms-sw/cmssw/pull/37782

**Comment by tvami** [comment]
@cmsbuild , please test
 * tho I think nothing tests this...

**Comment by kskovpen** [comment]
+pdmv

**Pull request merged**
