### PR TITLE
BMTF - New Kalman Emulator

### PR DESCRIPTION
**Pull request by panoskatsoulis**
This is the Kalman Emulator corresponding to the Kalman-fw 2.3
This is code written by @bachtis .

Please don't merge yet.

### CODE REVIEW

**Comment by rekovic** [comment]
please test

**Comment by fabiocos** [comment]
@panoskatsoulis @rekovic @thomreis what is the plan for this PR? Is this going to enter 10_3_X within very few days?

**Comment by panoskatsoulis** [comment]
There will be soon a newer version of the emulator, closing the PR .

**Comment by fabiocos** [comment]
@panoskatsoulis @rekovic I understand that the target here is clearly the future, not 10_3_X and/or the present data taking

**Comment by panoskatsoulis** [comment]
@fabiocos the target is the present data taking, I will create a 2 new PRs regarding the emulator today.
The PRs will include even newer emulator for Kalman than what is included in this PR

**Pull request closed without merging**
