### PR TITLE
Added ModuleAllocMonitor Service

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

This uses the AllocMonitor system to monitor the memory usage done by each module as well as the source and memory released at end of event.

#### PR validation:

Code compiles and unit tests pass.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
please test

let's see if this is affected by the OS change as well.

**Comment by Dr15Jones** [comment]
+1

**Comment by rappoccio** [comment]
+1

**Pull request merged**
