### PR TITLE
HBHEGPU: protection when detector is out

### PR DESCRIPTION
**Pull request by mariadalfonso**
fix issue reported in #34197

### CODE REVIEW

**Comment by mariadalfonso** [comment]
type bugfix

**Comment by perrotta** [comment]
please test

**Comment by mariadalfonso** [comment]
please test

**Comment by mariadalfonso** [comment]
> @mariadalfonso the effect of the fix is not testable with the standard jenkins tests with "normal" inputs, of course.
> Could you please confirm that you verified it actually fixes the cases that generated the issue?

I replicated the crash following instructions from here
https://github.com/cms-sw/cmssw/issues/34197#issuecomment-868476197
and the fix provided solve the crash for that particular configuration

**Comment by perrotta** [comment]
+reconstruction
- [Verified](https://github.com/cms-sw/cmssw/pull/34429#issuecomment-8789049) to fix the HCAL and ECAL local reconstruction eon a GPU when any of those detectors is out
- The fix has no effect on the "normal" workflows when all detectors are present
- Since the issue showed up during MWGR, the already provided backport (#34428) is welcome in 11_3

**Comment by perrotta** [comment]
+1

**Pull request merged**
