### PR TITLE
HBHE isolated noise reflagger retuning for Run2

### PR DESCRIPTION
**Pull request by dertexaner**

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test


Halil, 
please provide details about physics impact of this PR.
Some slides from a DPG or POG meeting would be the best.

After 76X was closed for new features, I think that now a presentation in PPD is also necessary to proceed with this code integration.

**Comment by dertexaner** [comment]
Hi Slava,
This PR aims to reduce the mistagging rate of the iso-based noise filters by a factor of ~2.5 (down to <5E-04 levels) in physics events (QCD MC, SingleMuon, SingleElectron PDs). The efficiency seems to be ~constant in MET PD as the change doesnt introduce tails in the HBHE MET distribution. We hope to present this at the Hcal Noise WG meeting tomorrow. A PPD/DPG presentation is also OK if needed.

**Comment by slava77** [comment]
@dertexaner 
Is this relevant for HeavyIons data taking?
If so, please prepare a PR in 75X.

**Comment by dertexaner** [comment]
@slava77 
I am not familiar with the use of this filter in HI data, but I will investigate.
Any comments from outside?  

On a different note, here is the presentation on the performance of this PR from today's meeting at the HCAL Noise WG:
https://indico.cern.ch/event/453554/contribution/7/attachments/1169128/1688472/Talk_Oct13_2015.pdf

**Comment by dertexaner** [comment]
Following the HN thread here: https://hypernews.cern.ch/HyperNews/CMS/get/hi-general/2366.html, it appears we will not need a HI 75X version of this PR.

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/11726	641fb0a
- configuration changes in line with the PR description and a summary of expected impact given above by @dertexaner 
- jenkins tests pass and show minor differences in HcalNoise related variables and in HCAL time of the towers in a small fraction of towers (less than 1E-4); regular mainstream data products are not affected.
- additionally tested on 134.805 (2015C MET) and 134.802 (2015C DoubleEG): the same observations as in jenkins tests

**Comment by davidlange6** [comment]
+1

**Pull request merged**
