### PR TITLE
Fix statics in DQM/BeamMonitor

### PR DESCRIPTION
**Pull request by dmitrijus**
Fix statics in DQM/BeamMonitor.

Make them members in Vx3DHLTAnalyzer.
Please test before accepting.

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
@dmitrijus 
thanks for this. waiting to see the same submitted to 76 before approving.

mentioning @dinardo to inform him about the changes

**Comment by deguio** [comment]
+1

**Comment by deguio** [comment]
shouldn't conflict against #12043

**Comment by davidlange6** [comment]
+1

**Pull request merged**
