### PR TITLE
Phase2-hgx359O First test of the V19 geometry of HGCal (longitudinal structure part to be corrected still)

### PR DESCRIPTION
**Pull request by bsunanda**
### PR description:

First test of the V19 geometry of HGCal (longitudinal structure part to be corrected still)

#### PR validation:

Tested with some some cfg files in Geometry/HGCalCommonData/test/python

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
+geometry

**Comment by bsunanda** [comment]
@srimanob Please approve this

**Comment by mandrenguyen** [comment]
@cms-sw/upgrade-l2 can you have a look please?

**Comment by srimanob** [comment]
+Upgrade

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
