### PR TITLE
G4 sensitive detectors cleanup 4

### PR DESCRIPTION
**Pull request by civanch**
Clean-up of CMS Sensitive detectors classes:
  - const interfaces to G4Step and G4Track where possible;
  - use strings in interfaces by const references;
  - code-checks applied;
  - removed commented lines and some blank lines.

No code improvement done, only clean-up of interfaces in order to be able to clean the code for sub-libraries separately. So, this is an intermediate step needed because in previous PR #20292 simulation history was changed, likely due to code improvement. 

No change in results is expected.

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by civanch** [comment]
@kpedro88 , @davidlange6 , in this PR I for purpose only include interface change and nothing for code improvement. Now results are identical.

**Comment by kpedro88** [comment]
+1

**Comment by davidlange6** [comment]
-1
until issues with the previous parts of this campaign are understood

**Pull request closed without merging**
