### PR TITLE
Phase2-hgx325G Make bug correction in HGCHitValidation and remove all references to 6-inch silicon version

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Make bug correction in HGCHitValidation and remove all references to 6-inch silicon version

#### PR validation:

Use the runTheMatrix test workflows

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by emanueleusai** [comment]
there's many difference in the test in Jet, MET, and JetValidation that I do not quite understand

**Comment by bsunanda** [comment]
@emanueleusai @perrotta These changes are in some examples in test directory which cannot affect any removal chain. Please approve and integrate this. We have some bugs in HGCal geometry and the fixes cannot be transmitted because there will be a conflict in the files  of this PR.

**Comment by srimanob** [comment]
@cmsbuild please test

Re-trigger the test, to remove unexpected disagreement in DQM.

**Comment by srimanob** [comment]
All failures are gone, only MessageLogger is remaining. This is good.

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by emanueleusai** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
