### PR TITLE
Ecal TPG Weights building from a file

### PR DESCRIPTION
**Pull request by depasse**
Ecal TPG Weights building from a simple file and no more from PulseShape 2009 Test Beam data in a complex way

### CODE REVIEW

**Comment by ggovi** [comment]
please test

**Comment by ggovi** [comment]
@depasse 
can you please remove the printouts when not required, and turn them in edm::Log... statements when you need to keep them...
Thanks!

**Comment by fabiocos** [comment]
please test

**Comment by ggovi** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
