### PR TITLE
Better protect EventProcessor::globalEndLumiAsync from exceptions

### PR DESCRIPTION
**Pull request by Dr15Jones**
Guarantee that endRun has to be called before the waiting task is released by controlling the order in which the destructors of the objects controlling those resources are called. This guarantees that even if an unexpected exception occurs, the order will still be maintained.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
@Dr15Jones is this related to #23409?

**Comment by Dr15Jones** [comment]
This is meant to fix #23409

**Comment by fabiocos** [comment]
@Dr15Jones right, thanks

**Pull request merged**
