### PR TITLE
ticl: Optimize calculation of Trackster time

### PR DESCRIPTION
**Pull request by felicepantaleo**
This PR optimizes the calculation of Trackster time in `RecoHGCal/TICL/plugins/TrackstersPCA.cc` by improving both code efficiency and readability.

- Key improvements include:
  - Replaced `std::vector<double>` with `std::array<float, 3>` for spatial coordinates, reducing memory overhead and enhancing computational performance.
  - Simplified the logic of the `project_lc_to_pca` function by directly calculating the squared distance, removing the need for extra square root operations.
  - Optimized the time correction calculation, introducing a more concise variable for the inverse of `z` and adjusting the logic for `deltaT` to improve numerical stability.
  - Removed redundant checks for used layer clusters in the loop, further simplifying the code.
  
Overall, these changes result in cleaner code and potentially faster execution without altering the core functionality.

@AuroraPerego fyi

### CODE REVIEW

**Comment by felicepantaleo** [comment]
test parameters:  

- workflow_opts= -w upgrade
- workflow = 29696.203

**Comment by felicepantaleo** [comment]
enable profiling

**Comment by felicepantaleo** [comment]
type hgcal

**Comment by felicepantaleo** [comment]
please test

**Comment by jfernan2** [comment]
please test
Launching tests once more to get last FastTimer CPU profiling changes from:
https://github.com/cms-sw/cms-bot/pull/2348
https://github.com/cms-sw/cms-bot/pull/2349

**Comment by jfernan2** [comment]
@felicepantaleo I see timing reductions in many places involving Tracksters and HGCAL, thanks!
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-d5463d/41850/profiling/29834.21/diff-step3_cpu.resources.json.html

**Comment by jfernan2** [comment]
+1

**Comment by Moanwar** [comment]
+Upgrade

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
