### PR TITLE
Protect against ill-defined track momenta and reffited tau vertices for tauReco@mini (10_6_X)

### PR DESCRIPTION
**Pull request by mbluj**
#### PR description:

As title says; in miniAOD samples (recent 94X/102X productions) there are rare tracks within pat:PackedCandidates (mainly lostTracks collection) with ill-defined momenta, i.e. pt being inf and/or eta nan. Those tracks used to (re)fit tau vertex result with a vertex with an undefined position (reco::Vertex::Point(nan,nan,nan)), but claiming to be a valid transient vertex. This PR protects against such issues - ill-defined tracks are not used for the fit and vertices with invalid position are not used for further processing.

This PR has not impact on official workflows, while it fixes issue causing failures in the tauReco@mini (unoffical) workflow.

#### PR validation:

* Validated with tauReco@mini (unofficial) workflow that failures observed with original code are fixed.
* Matrix tests (`runTheMatrix.py -l limited -i all --ibeos`) successful (with master).

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Backport of #31582 to 10_6_X for processing existing and UL (re)MiniAOD samples.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Review by slava77 — COMMENTED** [review]
this should be synced up with #31582

**Comment by mbluj** [comment]
> this should be synced up with #31582

Yes sure, it will be done. Should I also port code formatting as in master?

**Comment by perrotta** [comment]
> > this should be synced up with #31582
> 
> Yes sure, it will be done. Should I also port code formatting as in master?

It is normally better to avoid it, unless those formatting changes are strictly interconnected with the actual code changes (or they are just few, and you like including them), in order to reduce the diffs to be evaluated in the review.

**Comment by mbluj** [comment]
Synced with #31582 w/o code reformatting

**Comment by perrotta** [comment]
please test

**Comment by slava77** [comment]
backport of #31582

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/31585	405d79f 
- this PR is now consistent with the master version
- jenkins tests pass (the code changes affect only the code that runs in analysis, not in the matrix tests)

**Comment by qliphy** [comment]
+1

**Pull request merged**
