### PR TITLE
add "ppReco" label in relval output dataset names for batch injection

### PR DESCRIPTION
**Pull request by zhenhu**

### CODE REVIEW

**Comment by kpedro88** [comment]
@smuzaffar the bot missed this one, can you check?

**Comment by zhenhu** [comment]
please test

**Comment by zhenhu** [comment]
+1

**Comment by fabiocos** [comment]
@kpedro88 any objection? This looks ok and trivial to me

**Comment by kpedro88** [comment]
+upgrade

**Pull request merged**
