### PR TITLE
[13_0] 2023 FastSim

### PR DESCRIPTION
**Pull request by srimanob**
#### PR description:
Backport of https://github.com/cms-sw/cmssw/pull/42327 (overwrite https://github.com/cms-sw/cmssw/pull/42295)

### CODE REVIEW

**Comment by srimanob** [comment]
test parameters:
- workflows = 14034.0,14234.0
- relvals_opt = --what cleanedupgrade,standard,highstats,pileup,generator,extendedgen,production,identity,ged,machine,premix,nano,gpu,2017,2026

**Comment by srimanob** [comment]
@cmsbuild please test

**Comment by srimanob** [comment]
+Upgrade

**Comment by sunilUIET** [comment]
+pdmv

**Comment by perrotta** [comment]
+1

**Pull request merged**
