### PR TITLE
first commit of TwinMux unpacker

### PR DESCRIPTION
**Pull request by jpazzini**
first commit of TwinMux unpacker

### CODE REVIEW

**Comment by smuzaffar** [comment]
cms-bot acknowledge new package

**Comment by smuzaffar** [comment]
@mulhearn can you please review it and eventually sign? Thanks.

**Comment by jpazzini** [comment]
@davidlange6 , @mulhearn - I included in this latest fix the changes proposed by @davidlange6. If there is anything else needed before testing and signing this commit, please let me know.

**Comment by jpazzini** [comment]
@davidlange6 what's the status of this PR? I did what you asked but I haven't heard anything more. Moreover, as you pointed out before in the thread, PR #13123 is based on this.

**Comment by davidlange6** [comment]
afaik, its now in #13165

**Comment by jpazzini** [comment]
davidlange6, thank you. I wasn't aware of that. I see some mods were requested but I was directly referred to in the thread. Is #13165 still open or is it already merged? Can I do them now or is it too late?

**Comment by davidlange6** [comment]
#13165 is still open. (though I guess changes need to go via @mulhearn )

**Pull request closed without merging**
