### PR TITLE
Complete gemsta porting

### PR DESCRIPTION
**Pull request by archiesharma**
Adding GEM hits in the standalone reconstruction

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
-1
Changes in HLTrigger/Configuration have to go through ConfDB.
Use a fillDescriptions(.) method (preferred) or existsAs (deprecated)
in the C++ plugin code to take care of the added parameters.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
@cmsbuild please test
Jenkins comparisons never completed. Trying again.

**Comment by Martin-Grunewald** [comment]
-1
HLT issue still not taken care of.

**Comment by archiesharma** [comment]
fillDescription function added in L2MuonProducer to take care of the new added parameters for GEMs and they are removed from the HLTrigger/Configuration as per suggestions.

**Comment by Martin-Grunewald** [comment]
please test

**Comment by slava77** [comment]
-1

moving to 76X: further review will happen in #9806
(since the same archiesharma:completeGEMSTAPorting is used here and in #9806, actual local developments if any are needed can proceed in your original 75X (pre)release area until we are forced to move to a more recent 76X )

**Comment by deguio** [comment]
-1
see slava comment

**Pull request closed without merging**
