### PR TITLE
Put back wf 140.6 in the relval matrix 

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

https://github.com/cms-sw/cmssw/pull/42495 removed `140.60` from the relval  matrix. This PR recreates it, but using instead full 2022 RAW data format, emulate the RAW' and then reconstruct using the approximated clusters workflow (as discussed in https://github.com/cms-sw/cmssw/pull/42495#issuecomment-1683134955)

#### PR validation:

`runTheMatrix.py -l 140.58,140.60 -t 4 -j 8 --ibeos` runs fine

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

To be backported to 13.2.X

Cc: @mandrenguyen

### CODE REVIEW

**Comment by mmusich** [comment]
test parameters:
   * workflows = 140.58, 140.6

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
kindly pinging @cms-sw/pdmv-l2 and @cms-sw/upgrade-l2

**Comment by perrotta** [comment]
+operations

**Comment by srimanob** [comment]
+Upgrade

**Comment by sunilUIET** [comment]
+pdmv

**Comment by rappoccio** [comment]
+1

**Pull request merged**
