### PR TITLE
[Utilities] Cleanup for public headers

### PR DESCRIPTION
**Pull request by smuzaffar**
As reported in #34718 , this PR moves headers in interface directory for `Utilities`
```
      9 Utilities/StorageFactory/test/Test.h  -> src/Utilities/StorageFactory/interface/Test.h
      1 Utilities/XrdAdaptor/src/XrdStatistics.h -> src/Utilities/XrdAdaptor/interface/XrdStatistics.h
```

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by Dr15Jones** [comment]
The XrdStatisticsService should be handled in a different way. The service should have a base class defined (where that base class is public and appears in probably FWCore/Services) and then XrdStatisticsService inherits from the base class and never has its header exposed.

**Comment by smuzaffar** [comment]
sounds good @Dr15Jones.

**Comment by smuzaffar** [comment]
@Dr15Jones can you please take care of XrdStatisticsService?

**Comment by smuzaffar** [comment]
hold

**Comment by smuzaffar** [comment]
closing this
- XrdStatisticsService needs changes as suggested here https://github.com/cms-sw/cmssw/pull/34724#issuecomment-891904951
- Utilities/StorageFactory/test/Test.h is only used in tests , I guess we can allow tests sub-dirs to use files from other packages tests sub-dir

**Pull request closed without merging**
