### PR TITLE
memory reduction most visible in HI processing, done mostly by dropping muon isodeposits in HI (same as #12764)

### PR DESCRIPTION
**Pull request by slava77**
technical PR to reduce memory use, mainly driven by observations in complex events in HI workflows.

see details in 75X PR #12764)

tested in CMSSW_8_0_X_2015-12-11-1100: there are no differences compared to the baseline

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/12766	1cf8480
- jenkins tests confirm there are no changes in the monitored outputs

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
