### PR TITLE
[LLVM 10] Adjust Utilities/StaticAnalyzers for new clang

### PR DESCRIPTION
**Pull request by mrodozov**
#### PR description:

Adjustments for llvm 10 in cmssw 

#### PR validation:

The static analyzer builds with new llvm. tests are not exactly available.

### CODE REVIEW

**Comment by makortel** [comment]
@gartung Could you a look, please? (all looked straightforward to me)

**Review by gartung — APPROVED** [review]

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/29391	12f49ff 
- changes in reco are trivial; the rest is related to  Utilities/StaticAnalyzers, which is outside of the reco scope

**Comment by silviodonato** [comment]
@mrodozov do you have news on this PR?

**Comment by mrodozov** [comment]
The externals (numba) latest version doesn't work with py2 anymore, I'm thinking of changing the tests to work with py3 only and finish it

**Comment by davidlange6** [comment]
So the first python package we have to drop from python2….. sounds like the right solution.

On Apr 20, 2020, at 11:35 AM, Mircho Rodozov <notifications@github.com<mailto:notifications@github.com>> wrote:



The externals (numba) latest version doesn't work with py2 anymore, I'm thinking of changing the tests to work with py3 only and finish it

**Comment by smuzaffar** [comment]
+core
@silviodonato , this PR is for CLANG IBs. I would suggest to merge it along with cms-sw/cmsdist#5708 so that we can fix warnings new llvm warnings.

**Comment by smuzaffar** [comment]
@silviodonato , any objections on merging this for CLANG IBs?

**Comment by silviodonato** [comment]
+1

**Comment by santocch** [comment]
+1

**Comment by smuzaffar** [comment]
code-checks

**Comment by jfernan2** [comment]
+1

**Pull request merged**
