### PR TITLE
Monitor for mrh 920 patch4

### PR DESCRIPTION
**Pull request by dimattia**
Hello,

this is the same as #18531, with all comments addressed,  but based on CMSSW_9_2_0_patch4.

### CODE REVIEW

**Comment by franzoni** [comment]
https://github.com/cms-sw/cmssw/pull/18531#issuecomment-305140532

**Comment by franzoni** [comment]
can this be closed ?
it's been merged in master

**Comment by boudoul** [comment]
yes @dimattia please close it,  thanks

**Comment by dimattia** [comment]
Closed as requested.

**Pull request closed without merging**
