### PR TITLE
[Superseded by #46523] Add GloParT inference facility

### PR DESCRIPTION
**Pull request by colizz**
#### PR description:

This PR adds the GloParT 3 model's inference utility into CMSSW, prepared for NanoAODv15. The topic was discussed in the recent JMAR meeting [[slides]](https://indico.cern.ch/event/1438225/contributions/6053213/attachments/2915795/5117048/24.08.26_JMAR_Status%20of%20GloParT%20for%20AK8%20jets%20(v2024.08).pdf)

Global Particle Transformer (GloParT) 3 is an inclusive tagging model for AK8 jets that covers the entire phase space and enables resonance mass regression for each jet class. It functions as both a global tagger and a mass regression model for AK8 jets and can also be utilized as a pre-trained model. The hidden layer neurons (with dimension 256) are stored in MiniAOD, providing the capability to resume all output scores. Further details can be found in the slides.

In summary, the AK8 jet features added to MiniAOD and NanoAOD are illustrated below.

glopart-integration

Please test this PR with https://github.com/cms-data/RecoBTag-Combined/pull/61.

Note: the current model in https://github.com/cms-data/RecoBTag-Combined/pull/61 is a placeholder for incorporating this PR. During our development history, GloParT 2 has already been validated to function properly within CMSSW (using this branch: https://github.com/colizz/cmssw/tree/dev-130X-glopart ), although it has not been officially integrated. We are now upgrading GloParT from version 2 to version 3 (details in slides), and the final GloParT 3 model will be ready within 2-3 weeks. We are suggested to make this infrastructure PR to cmssw first.

Adding @qliphy @cmantill @rkansal47 @jmduarte 

#### PR validation:

The PR passes the unit test `test_globalpart_cfg.py`. It is also validated under the workflow AODSIM->MINIAOD->NANOAOD.

### CODE REVIEW

**Comment by hqucms** [comment]
enable nano

**Comment by hqucms** [comment]
test parameters:
 - pull_request = https://github.com/cms-data/RecoBTag-Combined/pull/61

**Comment by hqucms** [comment]
please test

**Comment by colizz** [comment]
Hi all, please see below a security check on the inferred tagger scores (using the GloParT 2 model). They are consistent with the score predicted by Weaver.
glopart2-check

**Comment by jfernan2** [comment]
enable profiling

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
please test

Tests are gone since they are 2 week old now, FYI @cms-sw/xpog-l2

**Comment by tvami** [comment]
I thought this PR is waiting for https://github.com/cms-data/RecoBTag-Combined/pull/61 to be not a placeholder anymore so there is not much new to test anyway

**Comment by colizz** [comment]
Hi @jfernan2 @tvami, many thanks! This PR requires us to finalize the upload of the model in https://github.com/cms-data/RecoBTag-Combined/pull/61.

XPOG has suggested that we upload our current "beta1" model (instead of a dummy model) so that performance can be tested. We've now done this and updated both PRs accordingly. Thanks very much for your test!

**Comment by hqucms** [comment]
please abort

**Comment by hqucms** [comment]
please test

**Comment by hqucms** [comment]
enable profiling,nano

**Comment by hqucms** [comment]
please test

**Pull request closed without merging**
