### PR TITLE
Sos monitoring2

### PR DESCRIPTION
**Pull request by gkaratha**
addressing Mia's comments

### CODE REVIEW

**Comment by mtosi** [comment]
did you test before doing the PR ?!?

**Comment by gkaratha** [comment]
Dear Mia, yes we made some basic tests.  We produced the offline efficiency with different but similar code. We know that it compiles without errors or warnings and produces the plots it must. The content of the plot has not been tested thoroughly though due to no statistics and it is what we are doing now

**Comment by dmitrijus** [comment]
please test

**Comment by mtosi** [comment]
tracked by https://github.com/cms-sw/cmssw/issues/19142

**Comment by mtosi** [comment]
I'm really confused by this PR :(
are you in contact w/ your DQM developer ?
do you think it is worth to have a chat ?

**Comment by gkaratha** [comment]
Dear Mia, I wrote it. I would be happy to chat.

**Comment by fwyzard** [comment]
@gkaratha can you please give a more descriptive name and comment to this PR ?

**Comment by gkaratha** [comment]
Dear Andrea, yes of course. But Mia told me to modify the TopMonitoring code to be usuable for my analysis instead of using this, since we cant afford one code per analysis. I have already changed the TopMonitoring code and now  I am checking it. I will do a different PR  with a more appropriate description. Thanks for the comment.

**Comment by dmitrijus** [comment]
+1

**Comment by fwyzard** [comment]
Martin pointed out that this has been made for the wrong branch: CMSSW_9_2_0_patchX instead of CMSSW_9_2_X.
Do we have the PRs for CMSSW 9.3.x and 9.2.x instead ?

**Comment by fwyzard** [comment]
Please close this PR.

**Comment by fwyzard** [comment]
Superseded by #19627

**Pull request closed without merging**
