### PR TITLE
Adding Onia states to pruned gen particles

### PR DESCRIPTION
**Pull request by alberto-sanchez**
Onia states seems missed. I am adding all of them, even when those in the 500 - 600 range are already there. Just to make sure all will be there.

### CODE REVIEW

**Comment by monttj** [comment]
please test

**Comment by davidlange6** [comment]
@cmsbuild, please test

**Comment by monttj** [comment]
@cmsbuild please test

**Comment by davidlange6** [comment]
@gpetruc - is this addition ok for you?

**Comment by gpetruc** [comment]
Alberto, can you check what's the increase in the number of pruned gen particles for a typical MC sample (maybe on TTbar pythia8; you can re-run just the miniAOD production step...)
I would expect the increase to be negligible, but just to be sure that pythia8 doesn't do anything strange.

**Comment by alberto-sanchez** [comment]
@gpetruc , I have used a file from TT_TuneCUETP8M1_13TeV-powheg-pythia8. 
The differences observed are not significant. They are really small.


pruned

**Comment by gpetruc** [comment]
Thanks, then I have no objections on this PR.

**Pull request merged**
