### PR TITLE
Run3-hcx372 Allow only valid ZDC Hits to enter the digitization phase -- backport #46286

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Allow only valid ZDC Hits to enter the digitization phase -- backport #46286

#### PR validation:

Use the runTheMatrix test workflows

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport of #46286 (adapted the usage of ZDCTopology)

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by perrotta** [comment]
backport of https://github.com/cms-sw/cmssw/pull/46286

**Comment by antoniovilela** [comment]
hold

**Comment by bsunanda** [comment]
Most likely not required for CMSSW_14_0_X. Inhibit digitization for ZDC preferred

**Pull request closed without merging**
