### PR TITLE
Era modifiers L1T for Phase2, Run3, and Run2_2018.

### PR DESCRIPTION
**Pull request by rekovic**
#### PR description:

Era trigger modifiers `phase2_trigger`, `stage2L1Trigger_2021`, and `stage2L1Trigger_2018` for 
 - Phase2,
 - Run3
 - Run2_2018.

#### PR validation:
These modifiers are not used yet, and are for future developments.  So this PR should have no effect on current CMSSW.

### CODE REVIEW

**Comment by rekovic** [comment]
please test

**Comment by rekovic** [comment]
assign l1

**Comment by silviodonato** [comment]
+operations

**Comment by rekovic** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
