### PR TITLE
Run3-alca172 Update some of the analyzing scripts

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Update some of the analyzing scripts

#### PR validation:

Tested all the scripts with current data and MC datasets

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by christopheralanwest** [comment]
please test

**Comment by silviodonato** [comment]
Do you have any comments @cms-sw/alca-l2 ?

**Comment by tlampen** [comment]
+alca

**Comment by qliphy** [comment]
+1

**Pull request merged**
