### PR TITLE
Use unique_ptr constructor for PluginFactory plugins in AttachSD

### PR DESCRIPTION
**Pull request by makortel**
This PR is preparatory work to change the PluginFactory to return a `std::unique_ptr`. On the same go I also changed the management of `SensitiveDetector` object from raw pointer to `unique_ptr` (within `AttachSD::create()`, ~~likely the return type could be changed to use `unique_ptr` as well but I'd leave that out from this PR~~).

Tested in CMSSW_10_5_X_2019-01-23-1100, no changes expected.

### CODE REVIEW

**Comment by civanch** [comment]
+1
concerning change the return type I am not sure: SensitiveDetector is a Geant4 object, it should follow G4 interface, deletion is G4 responsibility (good or bad it is).

**Comment by makortel** [comment]
@civanch Is the second commit https://github.com/cms-sw/cmssw/pull/25832/commits/98ad8175094c10542f943cc6f72e9e750ced89c5 actually wrong then?

**Comment by civanch** [comment]
@makortel , may be I am wrong, but it seems to be fine - you release std::unique_ptr and put it into the std::vector of pointers, I understand this as you give this object to G4.

**Comment by fabiocos** [comment]
+1

@civanch @makortel in any case in this PR the return type is untouched

**Pull request merged**
