### PR TITLE
bsunanda:Phase2-hgx70 Complete HGCal Geometry with no big holes

### PR DESCRIPTION
**Pull request by bsunanda**
This is the same as bsunanda:Phase2-hgx69 for CMSSW_9_0_X version

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by ianna** [comment]
+1

this is a back port from 90x (PR pending)

**Comment by bsunanda** [comment]
@civanch @mulhearn @rekovic Please approve this PR

**Comment by civanch** [comment]
+1

**Comment by rekovic** [comment]
+1

**Comment by davidlange6** [comment]
not needed in 81x. (phase2 dev will evolve in 90x)

**Pull request closed without merging**
