### PR TITLE
Fix Phase II Tracker Material scenarios to remove duplicate 20% one

### PR DESCRIPTION
**Pull request by mdhildreth**
Fix duplicate 20% percent material to 50 % scenario.  D27 was supposed to be 50%

### CODE REVIEW

**Comment by mdhildreth** [comment]
please test

**Comment by ianna** [comment]
@mdhildreth - you need to update dict2023Geometry.py:
https://cmssdt.cern.ch/lxr/source/Configuration/Geometry/python/dict2023Geometry.py
and then re-generate the scenario to avoid the error:
```
Running script: /build/cmsbld/jenkins/workspace/ib-any-integration/CMSSW_10_2_X_2018-07-17-1100/src/Configuration/Geometry/test/runtests.sh
cmsExtendedGeometry2023D27XML_cfi.py differs
```
Please, do not forget to update https://cmssdt.cern.ch/lxr/source/Configuration/Geometry/README.md

**Comment by ianna** [comment]
-1

**Comment by mdhildreth** [comment]
please test

**Comment by mdhildreth** [comment]
@ianna Fixed now.  If everything passes, could you please sign?

**Comment by mdhildreth** [comment]
@ianna  p.s.  The README file was correct; the dictionary was wrong.

**Comment by ianna** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade

**Pull request merged**
