### PR TITLE
PPS fixes in using DBOutputService

### PR DESCRIPTION
**Pull request by fabferro**
Fixes in use of DBOutputService: changing writeOne into writeOneIOV.

### CODE REVIEW

**Comment by tvami** [comment]
Hi @fabferro this is not the proposed way to go. This
https://github.com/cms-sw/cmssw/blob/dcc82d4c65de2b4bc99ea14f0542178541514815/CondTools/Geometry/plugins/PPSGeometryBuilder.cc#L81
should be instead instanciated and then the reference should be passed to the `writeOneIOV` . Please revisit https://indico.cern.ch/event/1088598/contributions/4580152/attachments/2333275/3976721/DBOutputService%20changes.pdf 
and/or have a look at a PR https://github.com/cms-sw/cmssw/pull/35999

Furthermore, I believe there is more than a single code for the PPS to change, right?

**Comment by fabferro** [comment]
> should be instead instanciated and then the reference should be passed to the

I already checked the docs you point me to, as well as some PRs that should "cure" the "problem", but I probably did not get the full story. I'll check them again. 
BTW, as far as I could see the other part of codes in which PPS was involved have already been modified. Most of the changes have been done by @ggovi. 
So AFAIU this is the last PPS part to be changed. If not, please let me know.

**Comment by tvami** [comment]
Here is a list that I found
https://github.com/cms-sw/cmssw/blob/master/CondTools/CTPPS/plugins/PPSTimingCalibrationWriter.cc#L46
https://github.com/cms-sw/cmssw/blob/master/CondTools/CTPPS/plugins/WriteCTPPSBeamParameters.cc#L70
https://github.com/cms-sw/cmssw/blob/master/CondTools/CTPPS/src/CTPPSRPAlignmentInfoAnalyzer.cc#L88
https://github.com/cms-sw/cmssw/blob/master/CondTools/CTPPS/src/WriteCTPPSPixGainCalibrations.cc#L239
https://github.com/cms-sw/cmssw/blob/master/CondTools/CTPPS/src/WriteCTPPSPixelAnalysisMask.cc#L76
https://github.com/cms-sw/cmssw/blob/master/CondTools/CTPPS/src/WriteCTPPSPixelDAQMapping.cc#L75

What @ggovi did was the first step that could be done centrally, now you need to take care of not using pointers and then pass the reference

**Comment by tvami** [comment]
> I already checked the docs you point me to, as well as some PRs that should "cure" the "problem", 

Please have a look at https://github.com/cms-sw/cmssw/pull/35999 this is the first PR from a subsystem, i.e. something that you need to do (any other PR you've looked at so far was just done for the first step of the resolution of the problem)

**Comment by fabferro** [comment]
@tvami: now I see the point. 
Before doing all the needed modifications, let me check if what I have in mind does the job.
In https://github.com/cms-sw/cmssw/blob/master/CondTools/CTPPS/plugins/WriteCTPPSBeamParameters.cc#L70
I would write
const CTPPSBeamParameters p = *bp.product();
poolDbService->writeOneIOV(p,........

Would it be ok dereferencing bp.product() pointer?

Otherwise I can only think of using smart pointers.

Your opinion?

Thanks.

**Comment by tvami** [comment]
Hi @fabferro 
I'd do something along these lines

```
  edm::ESHandle<CTPPSBeamParameters> bp = iSetup.getHandle(tokenBeamParameters_);

  // Pointer for the conditions data object
  const CTPPSBeamParameters* p = bp.product();
```
```suggestion
const auto p =  &iSetup.getData(tokenBeamParameters_);
```

and then
```
 poolDbService->writeOneIOV(*p, ilumi, "CTPPSBeamParametersRcd");
```
```suggestion
 poolDbService->writeOneIOV(p, ilumi, "CTPPSBeamParametersRcd");
```

Of course calling it `p` makes no sense anymore, so I'd also suggest to call it beamParam or something like that

**Comment by fabferro** [comment]
@tvami I think I'd better close this PR and open a new one with all the needed modifications.

**Comment by tvami** [comment]
-db
 * the PR is closed in favor of a new more general one

**Comment by tvami** [comment]
Hi @fabferro do you maybe have news on the follow-up PR of this?

**Comment by fabferro** [comment]
> 
> 
> Hi @fabferro do you maybe have news on the follow-up PR of this?

Hi @tvami, I did not forget. I've done the changes but I'm waiting for our DB experts to check that the changes are transparent. They are very overloaded these days and it's taking a bit longer than expected.

**Comment by tvami** [comment]
May I propose that you submit the PR in a draft mode while the further checks are being done?

**Comment by fabferro** [comment]
> May I propose that you submit the PR in a draft mode while the further checks are being done?

Done. PR#36180

**Pull request closed without merging**
