### PR TITLE
Latest updates in DQM/TrackingMonitorSource for data/MC comparisons for the Tracking POG

### PR DESCRIPTION
**Pull request by dbruschi**
This pull request contains the implementation of the latest distributions and plugins which are used by the Tracking POG for their data/MC comparisons. The main changes are to the StandaloneTrackMonitor plugin: a bug regarding the Z invariant mass and pt distribution has been fixed (they didn't have an impact on the results anyway), the histograms about the error on the IP are now in log scale, for dilepton events the cosphi3d distribution described here: https://indico.cern.ch/event/1312617/contributions/5521545/attachments/2694079/4675527/2023.08.01.misAlignmentPPD.pdf is evaluated.

### CODE REVIEW

**Comment by tjavaid** [comment]
please test

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cmsbuild please abort

need to wait for the next IB, actually

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by tjavaid** [comment]
please test

**Comment by tjavaid** [comment]
+1

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
