### PR TITLE
Validation/Geometry: Cleanup

### PR DESCRIPTION
**Pull request by vargasa**
#### PR description:

Cleanup. Removing outdated files.

#### PR validation:

cmsbuild test in place

#### if this PR is a backport please specify the original PR:

No backport

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by fabiocos** [comment]
@vargasa are all the removed scripts definitely unused? I noticed them while working on this package, I think most of the stuff is a remnant of the very beginning of CMSSW...

**Comment by vargasa** [comment]
>  are all the removed scripts definitely unused? I think most of the stuff is a remnant of the very beginning of CMSSW

@fabiocos. I checked some of the scripts were supposed to do what we are doing now with the unit test. There are some other scripts that makes reference to files that do not exist anymore. I checked them carefully but we can always go back if needed.

**Comment by cvuosalo** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
