### PR TITLE
Ignore tensorflow models

### PR DESCRIPTION
**Pull request by jpata**
Avoid committing .pb files (tensorflow weights) to cms-sw/cmssw. This seems to happen every once in a while, especially for first-time contributors: https://github.com/cms-sw/cmssw/pull/32222 and https://github.com/cms-sw/cmssw/pull/32128

No validation was done, no backport is intended.

### CODE REVIEW

**Comment by makortel** [comment]
Sounds reasonable to me. I do see one protobuf file in `PhysicsTools/TensorFlow/test/testAOT_add.pb`, which seems to be intended for tests.

What has been the policy for `.gitignore` changes before?

**Comment by jpata** [comment]
`git add -f` can always be used for adding new test files and existing files are not affected. Merging this will likely save non-negligible amount of time in reco, especially for first-time submitters.

**Comment by makortel** [comment]
@smuzaffar Do you have any concerns?

**Comment by smuzaffar** [comment]
+core
no objections @makortel

**Comment by qliphy** [comment]
+1

**Pull request merged**
