### PR TITLE
Switch to L1Tv4 and HLTv4.0 in @relval2017 (10_0_X)

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
Switch to L1Tv4 and HLTv4.0 in @relval2017 (10_0_X)
Based on CMSSW_9_4_X_2017-10-25-2300.

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by Martin-Grunewald** [comment]
@arunhep @lpernie 
please check and sign.

Thanks!

**Comment by lpernie** [comment]
+1

**Comment by lpernie** [comment]
I see this is going to 10_0_X. We should backport this to 94X.

**Comment by Martin-Grunewald** [comment]
@lpernie 
Done #21029

**Comment by davidlange6** [comment]
please test

(are these hcal differences fake?)

**Comment by arunhep** [comment]
@davidlange6 
>(are these hcal differences fake?)
not really. I asked @lpernie to add the GT description.
There is an update of HCAL pedestals and width tags for MC V2 : https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_mc2017_realistic_v5/94X_mc2017_realistic_v4

**Comment by lpernie** [comment]
# Summary of changes in Global Tags

## RunII data

   * **RunII HLT relval processing** : [94X_dataRun2_HLT_relval_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_dataRun2_HLT_relval_v5) as [94X_dataRun2_HLT_relval_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_dataRun2_HLT_relval_v3) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_dataRun2_HLT_relval_v5/94X_dataRun2_HLT_relval_v3):
      * L1Tmenu

   * **RunII Offline relval processing** : [94X_dataRun2_relval_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_dataRun2_relval_v5) as [94X_dataRun2_relval_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_dataRun2_relval_v2) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_dataRun2_relval_v5/94X_dataRun2_relval_v2):
      * L1Tmenu

   * **RunII Prompt processing** : [94X_dataRun2_PromptLike_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_dataRun2_PromptLike_v5) as [94X_dataRun2_PromptLike_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_dataRun2_PromptLike_v3) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_dataRun2_PromptLike_v5/94X_dataRun2_PromptLike_v3):
      * L1Tmenu

## Upgrade

   * **PhaseII realistic scenario** : [94X_upgrade2023_realistic_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_upgrade2023_realistic_v2) as [94X_upgrade2023_realistic_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_upgrade2023_realistic_v0) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_upgrade2023_realistic_v2/94X_upgrade2023_realistic_v0):
      * L1Tmenu

   * **PhaseI 2018 cosmics scenario** : [94X_upgrade2018cosmics_realistic_deco_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_upgrade2018cosmics_realistic_deco_v4) as [94X_upgrade2018cosmics_realistic_deco_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_upgrade2018cosmics_realistic_deco_v3) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_upgrade2018cosmics_realistic_deco_v4/94X_upgrade2018cosmics_realistic_deco_v3):
      * L1Tmenu

   * **PhaseI 2018 design scenario** : [94X_upgrade2018_design_IdealBS_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_upgrade2018_design_IdealBS_v5) as [94X_upgrade2018_design_IdealBS_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_upgrade2018_design_IdealBS_v4) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_upgrade2018_design_IdealBS_v5/94X_upgrade2018_design_IdealBS_v4):
      * L1Tmenu

   * **PhaseI 2018 realistic scenario** : [94X_upgrade2018_realistic_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_upgrade2018_realistic_v5) as [94X_upgrade2018_realistic_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_upgrade2018_realistic_v4) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_upgrade2018_realistic_v5/94X_upgrade2018_realistic_v4):
      * L1Tmenu

## 2017_MC

   * **PhaseI 2017 cosmics peak scenario** : [94X_mc2017cosmics_realistic_peak_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_mc2017cosmics_realistic_peak_v4) as [94X_mc2017cosmics_realistic_peak_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_mc2017cosmics_realistic_peak_v3) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_mc2017cosmics_realistic_peak_v4/94X_mc2017cosmics_realistic_peak_v3):
      * L1Tmenu +  HCAL pedestals and width tags for MC V2

   * **PhaseI 2017 cosmics scenario** : [94X_mc2017cosmics_realistic_deco_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_mc2017cosmics_realistic_deco_v4) as [94X_mc2017cosmics_realistic_deco_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_mc2017cosmics_realistic_deco_v3) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_mc2017cosmics_realistic_deco_v4/94X_mc2017cosmics_realistic_deco_v3):
      * L1Tmenu +  HCAL pedestals and width tags for MC V2

   * **PhaseI 2017 design scenario** : [94X_mc2017_design_IdealBS_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_mc2017_design_IdealBS_v5) as [94X_mc2017_design_IdealBS_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_mc2017_design_IdealBS_v4) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_mc2017_design_IdealBS_v5/94X_mc2017_design_IdealBS_v4):
      * L1Tmenu +  HCAL pedestals and width tags for MC V2

   * **PhaseI 2017 realistic scenario** : [94X_mc2017_realistic_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_mc2017_realistic_v5) as [94X_mc2017_realistic_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_mc2017_realistic_v4) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_mc2017_realistic_v5/94X_mc2017_realistic_v4):
      * L1Tmenu +  HCAL pedestals and width tags for MC V2

**Comment by arunhep** [comment]
@davidlange6 what is the plan to merge this? we have few other updates lined up.
Thanks.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
