### PR TITLE
Add RelVals for APV Dynamic Gain Simulation + HIP mitigation 

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

Title says it all, this is a follow-up of PR https://github.com/cms-sw/cmssw/pull/28024. 
Add for the various no-PU, PU (std. mixing) and PU (premixing) dynamic APV gains simulation relvals the HIP mitigation customization as it is run for the2016 data.
This will allow to have the complete battery of tests needed to perform the validation requested at https://its.cern.ch/jira/projects/PDMVRELVALS/issues/PDMVRELVALS-59

#### PR validation:

Passes standard runTheMatrix tests:

```
runTheMatrix.py -l 1325.91,25202.2,250202.4,250202.5 -t 4 -j 8 --ibeos
```
Preliminary comparisons of the: 
- default simulation (`25202`)
- Dynamic gain APV simulation ON + HIP mitigation OFF (`25202.1`)
- Dynamic gain APV simulation ON + HIP mitigation ON (`25202.2`)

have been made, here is a preview of some of the salient effects:

image
image

#### if this PR is a backport please specify the original PR:

This PR is not a backport.
cc:
@pieterdavid @EmyrClement @mtosi @JanFSchulte

### CODE REVIEW

**Comment by mmusich** [comment]
@chayanit, @pgunnell, @cmsbuild, @kpedro88, @zhenhu
can test be started here, please?

**Comment by kpedro88** [comment]
please test workflow 1325.91,25202.2,250202.4,250202.5

**Comment by chayanit** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade

**Comment by fabiocos** [comment]
+1

**Pull request merged**
