### PR TITLE
drop `--catalog` option from `edmFileUtil` check in `unittestinputsource` (online DQM unit tests)

### LINKED ISSUE #39262: DQM unit tests massive failures in  CMSSW_12_6_X_2022-08-30-2300
Starting from CMSSW_12_6_X_2022-08-30-2300 we observe massive DQM unit test failures.
See log: https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_amd64_gcc10/CMSSW_12_6_X_2022-08-30-2300/unitTestLogs/DQM/Integration#/

Trying to compile in local checkout:

```console
$ python3 beamhlt_dqm_sourceclient-live_cfg.py unitTest=True
Querying DAS for files...
the query is file run=355380 dataset=/ExpressPhysics/Run2022B-Express-v1/FEVT lumi=19
DAS succeeded after 1 attempts 0
found files:  ['/store/express/Run2022B/ExpressPhysics/FEVT/Express-v1/000/355/380/00000/b8a57fc4-5656-42b4-9b7b-2e647baf65e8.root']
edmFileUtil --catalog file:/cvmfs/cms-ib.cern.ch/SITECONF/local/PhEDEx/storage.xml?protocol=xrootd --events /store/express/Run2022B/ExpressPhysics/FEVT/Express-v1/000/355/380/00000/b8a57fc4-5656-42b4-9b7b-2e647baf65e8.root | tail -n +9 | head -n -5 | awk '{ print $3 }'
Traceback (most recent call last):
  File "/tmp/musich/CMSSW_12_6_X_2022-08-30-2300/src/DQM/Integration/python/clients/beamhlt_dqm_sourceclient-live_cfg.py", line 42, in <module>
    process.load("DQM.Integration.config.unittestinputsource_cfi")
  File "/cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc10/cms/cmssw-patch/CMSSW_12_6_X_2022-08-30-2300/src/FWCore/ParameterSet/python/Config.py", line 744, in load
    module = __import__(moduleName)
  File "/tmp/musich/CMSSW_12_6_X_2022-08-30-2300/src/DQM/Integration/python/config/unittestinputsource_cfi.py", line 113, in <module>
    eventsToProcess.append("%s:%s:%s-%s:%s:%s" % (options.runNumber, ls, events[0], options.runNumber, ls, events[-1]))
IndexError: list index out of range
```

### PR DESCRIPTION
**Pull request by mmusich**
resolves https://github.com/cms-sw/cmssw/issues/39262

#### PR description:

Title says it all, no longer needed after integration of https://github.com/cms-sw/cmssw/pull/37278, as per https://github.com/cms-sw/cmssw/issues/39262#issuecomment-1232848626

#### PR validation:

Will be done in the PR unit tests.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

N/A

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by perrotta** [comment]
urgent
(mostly for us: there are too many errors in the IBs now, and we should really start getting rid of them)

**Comment by smuzaffar** [comment]
looks good, unit tests [passed](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-304308/27226/unitTests/success.html)

**Comment by perrotta** [comment]
+1
- It looks like having fixed the issue: let merge it and try to clean the IBs a bit
- @cms-sw/dqm-l2 please complain if you think there is anything missing

**Comment by perrotta** [comment]
merge

**Comment by emanueleusai** [comment]
+1

**Pull request merged**
