### PR TITLE
[DQM] DT Fixing FEDFatal 12_2_X

### PR DESCRIPTION
**Pull request by jfernan2**
#### PR description:

Backport of https://github.com/cms-sw/cmssw/pull/36448

### CODE REVIEW

**Comment by jfernan2** [comment]
backport

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+1
This backport was created in view of a possible CRAFT data taking in 2022 with 12_2_X

**Comment by qliphy** [comment]
+1

**Pull request merged**
