### PR TITLE
HBHE: energy reco

### PR DESCRIPTION
**Pull request by mariadalfonso**
backport of #21821 

In view of resynching the 10_0_X for HLT studies
https://its.cern.ch/jira/browse/CMSHLT-1726
https://its.cern.ch/jira/browse/CMSHLT-1730

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
+1
- It is identical to #21821, already merged in the master
- For the reco part, this is just code cleaning: no changes are expected in output, none are seen
. Backport to 10_0 is justified if TSG wants to develop trigger paths with the same parameters that are available in the master

**Comment by mariadalfonso** [comment]
@Martin-Grunewald @perrotta 
resolved the conflicts in customizeHLTforCMSSW and rebased

**Comment by perrotta** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by perrotta** [comment]
+1
- Only rebased since it got signed in https://github.com/cms-sw/cmssw/pull/22316#issuecomment-368071800

**Comment by fabiocos** [comment]
+1

**Pull request merged**
