### PR TITLE
Updates to L1TGlobal to use new UTM library (80X)

### PR DESCRIPTION
**Pull request by mulhearn**
Updates to L1TGlobal to make use of the new UTM library for parsing the L1 menu.

The ALCA/DB dependence should clear with PR #13202.

### CODE REVIEW

**Comment by mulhearn** [comment]
please test

**Comment by mulhearn** [comment]
please test

**Comment by mulhearn** [comment]
sorry, accidentally forced pushed the HLT branch here... fixed now.

**Comment by mulhearn** [comment]
please test

**Comment by mulhearn** [comment]
+1

**Comment by mulhearn** [comment]
please test

**Comment by mulhearn** [comment]
...and stay off the sauce this time.

**Comment by slava77** [comment]
@mulhearn 
may I ask you to use some sensible PR subject/titles 
(this refers to a number of PRs in L1 submitted recently).
We use these for release self-documentation.
Instead of the default garbled git branch topic name, it would be nice to type in some human readable text.
There is an "Edit" button to the right at the top of the PR page.
A PR subject should look more like a news headline or a paper title, not as a doi link or alike.

Thank you.

**Comment by mulhearn** [comment]
please test

**Comment by mulhearn** [comment]
+1

**Comment by davidlange6** [comment]
please test (looks like a glitch)

**Comment by mulhearn** [comment]
@cmsbuild, please test

**Comment by mulhearn** [comment]
relVals running... I think Jenkins hits the sauce a little too hard on the weekend.

**Comment by mulhearn** [comment]
@davidlange6 this one is now good to go!

**Comment by davidlange6** [comment]
+1

**Comment by davidlange6** [comment]
@mulhearn - this brings in some warnings- could you have a look and fix
https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc6_amd64_gcc493/CMSSW_8_0_X_2016-02-06-2300/L1Trigger/L1TGlobal

**Comment by mulhearn** [comment]
@davidlange6 - got it, will track the issue here:  https://github.com/cms-l1t-offline/cmssw/issues/145

**Pull request merged**
