### PR TITLE
Using dasgoclient for das queries in runTheMatrix (92X)

### PR DESCRIPTION
**Pull request by fabozzi**
Backport of #21015

### CODE REVIEW

**Comment by fabozzi** [comment]
please test

**Comment by fabozzi** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Comment by fabozzi** [comment]
plase test

**Comment by fabozzi** [comment]
please test

**Comment by fabozzi** [comment]
please test

**Comment by fabozzi** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Comment by davidlange6** [comment]
merge

**Pull request merged**
