### PR TITLE
Print function migration for RecoBTag_TensorFlow

### PR DESCRIPTION
**Pull request by davidlange6**
Using futurize -n -w --no-diffs -j 4 -f libfuturize.fixes.fix_print_with_import

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/24027	dc4fa45 
- technical, changing only a test configuration
- jenkins tests pass

**Comment by kpedro88** [comment]
+1

**Pull request merged**
