### PR TITLE
Switch random number generator to mixmax

### PR DESCRIPTION
**Pull request by civanch**
New random number generator MIXMAX has better properties and is thread safe. It is proposed to be used in the ROOT6 branch both for Full and Fast SIM. The simulation histories will be different, so only statistical comparison of results is possible.

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by fabiocos** [comment]
@civanch which is the validation plan? Compare relVal output? Some longer data sample?

**Comment by civanch** [comment]
@fabiocos , yes we may request long run to be sure that there is no issue and we need RelVal validation. I may produce similar PR for the master which will be pending until proper time to merge.

**Comment by fabiocos** [comment]
please test

**Comment by civanch** [comment]
This PR is not needed anymore, because MixMax is merged to the development branch

**Pull request closed without merging**
