### PR TITLE
Run2-alca101 Make the codes and macros updated with the current versions used for calibration

### PR DESCRIPTION
**Pull request by bsunanda**
Calibration code is modified to select/antiselect a given RBX for calibration/monitoring
Fit/Plot macro is modified to utilize  common code to do packing/unpacking DetId read correction files

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by lpernie** [comment]
Hi @bsunanda , seems you are mostly touching macros. Could you add a description for the PR? 
Thanks.

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@lpernie @arunhep Can you approve this PR?

**Comment by lpernie** [comment]
+1

**Comment by davidlange6** [comment]
merge

**Pull request merged**
