### PR TITLE
save particleFlowRecHitHBHE and particleFlowRecHitHF collections

### PR DESCRIPTION
**Pull request by kpedro88**
particleFlowRecHitHCAL is no longer used*. Instead, the separate particleFlowRecHitHBHE and particleFlowRecHitHF collections should be kept in the PF event content.

Let me know if I should backport this anywhere.

\* https://github.com/cms-sw/cmssw/blob/CMSSW_8_0_X/RecoParticleFlow/PFClusterProducer/python/particleFlowCluster_cff.py

### CODE REVIEW

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@kpedro88 
this appears applicable to all releases.
I suggest adding 75X and 76X PRs.
I'm assuming these don't add substantially to the event size.

@bachtis are these collections really used anywhere?
(Considering that them missing has gone unnoticed for quite some time)

**Comment by bachtis** [comment]
Hi @slava77 
The PR is fine . Indeed we need those in the PF event content . I just had never done it since 
it is trivial to remake them on RECO from the rechits

**Comment by kpedro88** [comment]
@slava77 @bachtis - submitted #12324 and #12325 to backport to 76X and 75X.

**Comment by cvuosalo** [comment]
+1

For #12300 ea8183a1e9cef0b8a6a3f32d716a84dd16f0d16c

Replacing the particleFlowRecHitHCAL collection with the particleFlowRecHitHBHE and particleFlowRecHitHF collections. There should be no change in monitored quantities.

Jenkins [tests](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-12300/9503/summary.html) against baseline CMSSW_8_0_X_2015-11-05-2300 show no significant differences, as expected. Extended tests of workflows 134.705_RunMET2015B and 134.805_RunMET2015C with 70 events each against baseline  CMSSW_8_0_X_2015-11-03-2300 also show no significant differences. Product sizes increase very marginally (less than 0.02%) from the new collections:
```
134.705
-------------------------------------------------------------
 or, B       new, B      delta, B   delta, %   deltaJ, %    branch 
-------------------------------------------------------------
        0 ->          75         75     NEWO   0.01     recoPFRecHits_particleFlowRecHitHBHE_Cleaned_reRECO.
        0 ->         228        228     NEWO   0.02     recoPFRecHits_particleFlowRecHitHF_Cleaned_reRECO.
-------------------------------------------------------------
  1060872 ->     1061174        302             0.0     ALL BRANCHES

134.805
-------------------------------------------------------------
 or, B       new, B      delta, B   delta, %   deltaJ, %    branch 
-------------------------------------------------------------
         0 ->          59         59     NEWO   0.00     recoPFRecHits_particleFlowRecHitHBHE_Cleaned_reRECO.
    53380 ->       53363        -17     -0.0  -0.00     recoTracks_generalTracks__reRECO.
        0 ->          87         87     NEWO   0.01     recoPFRecHits_particleFlowRecHitHF_Cleaned_reRECO.
-------------------------------------------------------------
  1247198 ->     1247323        125             0.0     ALL BRANCHES

```

**Comment by davidlange6** [comment]
+1

**Pull request merged**
