### PR TITLE
Modify trigger filterBits for electrons and photons in custom EGM Nano

### PR DESCRIPTION
**Pull request by RSalvatico**
#### PR description:

This PR modifies the `filterBits` content for the `TrigObj`s with id = 11 and id = 22 (electrons and photons, respectively) in the custom EGM Nano only, to better suit the current needs of the POG.

#### PR validation:

Checked that we get credible results in terms of trigger objects, IDs and pT thresholds when requesting each of the filterBits to be on. One workflow that can be used is 

`runTheMatrix.py -l 2500.315 --sites ''`

### CODE REVIEW

**Comment by RSalvatico** [comment]
type egamma

**Comment by hqucms** [comment]
enable nano

**Comment by hqucms** [comment]
please test

**Comment by hqucms** [comment]
+1

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
