### PR TITLE
Change tau trigger bits stored in NanoAOD [12_4_X]

### PR DESCRIPTION
**Pull request by mbluj**
#### PR description:

This PR is meant to fix an issue with not matching tau triggers bits in 2018 (due to a forgotten 'Hps' part in their names) as well as to prepare to accommodate Run-3 tau triggers.

This PR is a backport of #38472 (full description therein).

**Changes**
* Addition of wildcards to original trigger bits to work for both HPS and non-HPS paths;
* Addition of DeepTau trigger bits;
* Addition of bits 4096 to 32768 to include PAG paths;
* Addition of bits 65536 for completeness, they allow to go a bit more specific in the triggers to select;
* Addition of boosted tau block. Right now the bits are redundant, but we expect more to be added in the future;
* Added bits to non-tau blocks from cross triggers.

#### PR validation:

Reran NanoAOD for all three Run-2 years and in a Run-3 sample, everything seemed to act as expected. In addition tests run during integration to the master.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

It is a backport of #38472; it is meant to become a part of nanoAOD v10.

### CODE REVIEW

**Comment by mariadalfonso** [comment]
please test

**Comment by perrotta** [comment]
backport of https://github.com/cms-sw/cmssw/pull/38472

**Comment by mariadalfonso** [comment]
+xpog

backport inline with master

**Comment by perrotta** [comment]
+1

**Pull request merged**
