### PR TITLE
`CalibTracker/SiStripChannelGain`: fix issue with ODR of `stAPVGain` struct

### LINKED ISSUE #38650: [LTO_X - CalibTracker] Solve -Wodr compiler warnings
Hello,

We have seen some compiler warnings of the type `-Wodr` in LTO_X IBs ([CMSSW_12_5_LTO_X_2022-07-07-1100](https://cmssdt.cern.ch/SDT/cgi-bin/showBuildLogs.py/el8_amd64_gcc10/www/thu/12.5.LTO-thu-11/CMSSW_12_5_LTO_X_2022-07-07-1100) and [CMSSW_12_5_LTO_X_2022-07-06-1100](https://cmssdt.cern.ch/SDT/cgi-bin/showBuildLogs.py/el8_amd64_gcc10/www/wed/12.5.LTO-wed-11/CMSSW_12_5_LTO_X_2022-07-06-1100), for example) in package `CalibTracker/SiStripChannelGain`. See sample stack trace:

```
>> Building edm plugin tmp/el8_amd64_gcc10/src/CalibTracker/SiStripChannelGain/plugins/CalibTrackerSiStripChannelGainAuto/libCalibTrackerSiStripChannelGainAuto.so
/data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc10/external/gcc/10.3.0-84898dea653199466402e67d73657f10/bin/c++ -O2 -pthread -pipe -Werror=main -Werror=pointer-arith -Werror=overlength-strings -Wno-vla -Werror=overflow -std=c++1z -ftree-vectorize -Wstrict-overflow -Werror=array-bounds -Werror=format-contains-nul -Werror=type-limits -fvisibility-inlines-hidden -fno-math-errno --param vect-max-version-for-alias-checks=50 -Xassembler --compress-debug-sections -msse3 -felide-constructors -fmessage-length=0 -Wall -Wno-non-template-friend -Wno-long-long -Wreturn-type -Wextra -Wpessimizing-move -Wclass-memaccess -Wno-cast-function-type -Wno-unused-but-set-parameter -Wno-ignored-qualifiers -Wno-deprecated-copy -Wno-unused-parameter -Wunused -Wparentheses -Wno-deprecated -Werror=return-type -Werror=missing-braces -Werror=unused-value -Werror=unused-label -Werror=address -Werror=format -Werror=sign-compare -Werror=write-strings -Werror=delete-non-virtual-dtor -Werror=strict-aliasing -Werror=narrowing -Werror=unused-but-set-variable -Werror=reorder -Werror=unused-variable -Werror=conversion-null -Werror=return-local-addr -Wnon-virtual-dtor -Werror=switch -fdiagnostics-show-option -Wno-unused-local-typedefs -Wno-attributes -Wno-psabi -Wno-error=unused-variable -DBOOST_DISABLE_ASSERTS -flto -fipa-icf -flto-odr-type-merging -fno-fat-lto-objects -Wodr -shared -Wl,-E -Wl,-z,defs tmp/el8_amd64_gcc10/src/CalibTracker/SiStripChannelGain/plugins/CalibTrackerSiStripChannelGainAuto/DeDxDiscriminatorLearner.cc.o tmp/el8_amd64_gcc10/src/CalibTracker/SiStripChannelGain/plugins/CalibTrackerSiStripChannelGainAuto/SealModules.cc.o tmp/el8_amd64_gcc10/src/CalibTracker/SiStripChannelGain/plugins/CalibTrackerSiStripChannelGainAuto/SiStripGainCosmicCalculator.cc.o tmp/el8_amd64_gcc10/src/CalibTracker/SiStripChannelGain/plugins/CalibTrackerSiStripChannelGainAuto/SiStripGainFromAsciiFile.cc.o tmp/el8_amd64_gcc10/src/CalibTracker/SiStripChannelGain/plugins/CalibTrackerSiStripChannelGainAuto/SiStripGainFromCalibTree.cc.o tmp/el8_amd64_gcc10/src/CalibTracker/SiStripChannelGain/plugins/CalibTrackerSiStripChannelGainAuto/SiStripGainFromData.cc.o tmp/el8_amd64_gcc10/src/CalibTracker/SiStripChannelGain/plugins/CalibTrackerSiStripChannelGainAuto/SiStripGainRandomCalculator.cc.o tmp/el8_amd64_gcc10/src/CalibTracker/SiStripChannelGain/plugins/CalibTrackerSiStripChannelGainAuto/SiStripGainsCalibTreeWorker.cc.o -o tmp/el8_amd64_gcc10/src/CalibTracker/SiStripChannelGain/plugins/CalibTrackerSiStripChannelGainAuto/libCalibTrackerSiStripChannelGainAuto.so -Wl,-E -Wl,--hash-style=gnu -L/data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/ed6117194997de64d40aad03ededc67f/opt/cmssw/el8_amd64_gcc10/cms/cmssw/CMSSW_12_5_LTO_X_2022-07-06-1100/biglib/el8_amd64_gcc10 -L/data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/ed6117194997de64d40aad03ededc67f/opt/cmssw/el8_amd64_gcc10/cms/cmssw/CMSSW_12_5_LTO_X_2022-07-06-1100/lib/el8_amd64_gcc10 -L/data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/ed6117194997de64d40aad03ededc67f/opt/cmssw/el8_amd64_gcc10/cms/cmssw/CMSSW_12_5_LTO_X_2022-07-06-1100/external/el8_amd64_gcc10/lib -lCalibTrackerSiStripChannelGain -lCalibTrackerSiStripCommon -lTrackingToolsPatternTools -lTrackingToolsTransientTrackingRecHit -lTrackingToolsDetLayers -lRecoTrackerDeDx -lTrackingToolsGeomPropagators -lTrackingToolsTrajectoryState -lDataFormatsTrackReco -lDataFormatsTrackCandidate -lDataFormatsTrackerRecHit2D -lDataFormatsFTLRecHit -lDataFormatsTrajectorySeed -lCalibFormatsSiStripObjects -lCalibTrackerRecords -lDataFormatsTrackingRecHit -lGeometryTrackerGeometryBuilder -lCondFormatsSiStripObjects -lDataFormatsL1TrackTrigger -lMagneticFieldRecords -lCondFormatsDataRecord -lDataFormatsTrackerCommon -lGeometryCommonTopologies -lCondCoreDBOutputService -lCondFormatsAlignment -lDataFormatsBeamSpot -lDataFormatsGeometryCommonDetAlgo -lDataFormatsSiStripCluster -lGeometryRecords -lGeometryTrackerNumberingBuilder -lTrackingToolsAnalyticalJacobians -lCommonToolsUtilAlgos -lCondCoreCondDB -lCondFormatsAlignmentRecord -lDQMServicesCore -lDataFormatsCandidate -lDataFormatsGeometrySurface -lDataFormatsSiStripCommon -lDataFormatsTrajectoryState -lDetectorDescriptionCore -lDetectorDescriptionDDCMS -lMagneticFieldEngine -lCommonToolsUtils -lCondFormatsGeometryObjects -lCondFormatsRunInfo -lDataFormatsCLHEP -lDataFormatsCaloRecHit -lDataFormatsEcalDetId -lDataFormatsForwardDetId -lDataFormatsGeometryVector -lDataFormatsL1GlobalTrigger -lDataFormatsMuonDetId -lDataFormatsNanoAOD -lDataFormatsPhase2TrackerCluster -lDataFormatsSiPixelDetId -lDataFormatsSiStripDetId -lFWCoreFramework -lCondFormatsCommon -lDataFormatsDetId -lDataFormatsFEDRawData -lDataFormatsL1GlobalMuonTrigger -lDataFormatsMath -lDataFormatsOnlineMetaData -lDataFormatsPhase2TrackerDigi -lDataFormatsScalers -lDataFormatsScouting -lDataFormatsSiPixelCluster -lDataFormatsSiStripDigi -lFWCoreCommon -lFWCoreServiceRegistry -lCondFormatsPhysicsToolsObjects -lDataFormatsCommon -lFWCoreParameterSet -lFWCoreMessageLogger -lDataFormatsProvenance -lFWCorePluginManager -lFWCoreReflection -lTrackingToolsTrajectoryParametrization -lCondFormatsSerialization -lFWCoreConcurrency -lFWCoreUtilities -lFWCoreVersion -lUtilitiesOpenSSL -llcg_CoralCommon -llcg_RelationalAccess -llcg_CoralKernel -llcg_CoralBase -lDDAlign -lDDCond -lDDCore -lDDParsers -lPhysics -lHist -lMatrix -lGenVector -lMathMore -lTree -lNet -lGeom -lThread -lboost_filesystem -lMathCore -lRIO -lSmatrix -lboost_iostreams -lboost_regex -lboost_serialization -lboost_system -lclasslib -lCore -lboost_thread -lboost_date_time -lCLHEP -lpcre -lbz2 -lcurl -lgsl -luuid -lprotobuf -ltbb -lxerces-c -llzma -lz -lfmt -lcms-md5 -lopenblas -lssl -lcrypto -lcrypt -ldl -lrt -lstdc++fs -ltinyxml2
  /data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/ed6117194997de64d40aad03ededc67f/opt/cmssw/el8_amd64_gcc10/cms/cmssw/CMSSW_12_5_LTO_X_2022-07-06-1100/src/CalibTracker/SiStripChannelGain/interface/APVGainStruct.h:9:8: warning: type 'struct stAPVGain' violates the C++ One Definition Rule [-Wodr]
     9 | struct stAPVGain {
      |        ^
/data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/ed6117194997de64d40aad03ededc67f/opt/cmssw/el8_amd64_gcc10/cms/cmssw/CMSSW_12_5_LTO_X_2022-07-06-1100/src/CalibTracker/SiStripChannelGain/plugins/SiStripGainFromData.cc:71:8: note: a different type is defined in another translation unit
   71 | struct stAPVGain {
      |        ^
/data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/ed6117194997de64d40aad03ededc67f/opt/cmssw/el8_amd64_gcc10/cms/cmssw/CMSSW_12_5_LTO_X_2022-07-06-1100/src/CalibTracker/SiStripChannelGain/interface/APVGainStruct.h:11:7: note: the first difference of corresponding definitions is field 'Bin'
   11 |   int Bin;
      |       ^
/data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/ed6117194997de64d40aad03ededc67f/opt/cmssw/el8_amd64_gcc10/cms/cmssw/CMSSW_12_5_LTO_X_2022-07-06-1100/src/CalibTracker/SiStripChannelGain/plugins/SiStripGainFromData.cc:73:7: note: a field with different name is defined in another translation unit
   73 |   int DetId;
      |       ^
Leaving library rule at src/CalibTracker/SiStripChannelGain/plugins
```

It seems there are some elements defined multiple times within the same namespace leading to violation of the C++ One Definition Rule. Could you please have a look at it?

Many thanks,
Andrea.

### PR DESCRIPTION
**Pull request by mmusich**
resolves https://github.com/cms-sw/cmssw/issues/38650

#### PR description:

Issue https://github.com/cms-sw/cmssw/issues/38650 reported some compiler warnings of the type `-Wodr` in `LTO_X` IBs, as some elements defined multiple times within the same namespace leading to violation of the C++ One Definition Rule.
This is solved by making the class `SiStripGainFromData` use the struct `stAPVGain` defined in the `APVGainStruct` header.

#### PR validation:

`cmssw` compiles.
Run succesfully `scram build use-ibeos runtests`.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

N/A

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by tvami** [comment]
@cmsbuild , please test for CMSSW_12_5_LTO_X

**Comment by tvami** [comment]
type bugfix,trk

**Comment by mmusich** [comment]
>> Subsystem DQM built
>> Entering Package src/BigProducts/Simulation
>> Building  big plugin tmp/el8_amd64_gcc10/src/BigProducts/Simulation/pluginSimulation.so
lto-wrapper: warning: Extra option to -Xassembler: --compress-debug-sections, dropping all -Xassembler and -Wa options.
during IPA pass: icf

I don't think this is related...

**Comment by tvami** [comment]
Yes, let's just wait for the standard `el8_amd64_gcc10 ` tests to finish, and I'll ignore the LTO build failure

**Comment by tvami** [comment]
@mmusich I'm confused on why the other PR's `@cmsbuild , please test for CMSSW_12_5_LTO_X` worked, and why it doesnt work here, should we try that again?

**Comment by tvami** [comment]
+alca
 * diffs in MTD only
 * PR is according to the PR description

**Comment by qliphy** [comment]
+1

**Pull request merged**
