### PR TITLE
Removal of PixelPairStep for Phase 1 HI Tracking

### PR DESCRIPTION
**Pull request by abaty**
After the inclusion of additional quadruplet iterations for Phase 1 tracking in PR #18646, we have decided to remove the pixel pair step from the phase 1 HI tracking workflow (similar to what was done for pp tracking).  Studies [here](https://indico.cern.ch/event/646309/contributions/2625076/attachments/1475706/2285895/PixelPairStudy.pdf) show that this iteration is only recovering 1-2% efficiency, while also contributing ~1% fake rate.  

Timing studies show a decrease in tracking time in 0-10% events from ~109 s to ~99 s, and from 10.3 to 9.7s in inclusive events.

Testing can be done using the HI Phase 1 relval proposed in PR #19089.

@mandrenguyen

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
Regarding

> we have decided to remove the pixel pair step from the phase 1 HI tracking workflow (similar to what was done for pp tracking).

you may want to check the latest developments in the pp reco in #19051 
pixel pair iteration is active in phase-1 pp reco

**Comment by slava77** [comment]
@cmsbuild please test

comparisons never showed up

**Comment by slava77** [comment]
@abaty 
please clarify if there is a follow up to https://github.com/cms-sw/cmssw/pull/19338#issuecomment-309437958

Are you planning to mitigate the inefficiency in a similar way as in pp (using pixelPair step)?

**Comment by abaty** [comment]
@slava77 

We are doing some quick investigations to see if this type of mitigation is worthwhile for us.  We should have an answer by the end of tomorrow.

**Comment by abaty** [comment]
@slava77 
After some review, we believe we would benefit from some similar mitigation strategy.  As this will involve keeping the pair step in some form, I will close this PR and make a new one once we have settled on an effective setup.

**Pull request closed without merging**
