### PR TITLE
[74X] JER integration into conditions database

### PR DESCRIPTION
**Pull request by blinkseb**
This PR is a backport of #10448 for CMSSW 7.4.x

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by ggovi** [comment]
+1

**Comment by mmusich** [comment]
+1

**Comment by ggovi** [comment]
+1

**Comment by blinkseb** [comment]
Hi all, I've found a small bug in the code already merged into 7.6.x and in this PR. How should I proceed? I can update this PR with the fix, but then all the signoff will be needed again, and the JetMET pog is waiting on this to be merged quickly...

In case I update the PR, can the validation process be quick?

Thanks

**Comment by mmusich** [comment]
@blinkseb first correct the bug in 8.0.X and 7.6.X than you will backport it here.

**Comment by blinkseb** [comment]
@mmusich Done as #12723 and #12773

**Comment by diguida** [comment]
@blinkseb @mmusich #12723 is merged now.
Please cherry pick https://github.com/blinkseb/cmssw/commit/067de091c50d0a4b81a0c33747e66afc4e0218df and https://github.com/blinkseb/cmssw/commit/dd1521bb32324b1f474cfff85bb01aebf370b51d here.

**Comment by mmusich** [comment]
please test

**Comment by ggovi** [comment]
+1

**Comment by mmusich** [comment]
+1

**Comment by monttj** [comment]
+1

**Comment by slava77** [comment]
It looks like some recent changes in package categories now added need for reconstruction signature.

Before spending much time on this, please explain why this PR is still needed. Which analyses still use 74X.
Last 74X release was needed 10 months ago.
@blinkseb  if this PR is not needed in 74X, please close it.

**Comment by blinkseb** [comment]
Looks like it's indeed no longer needed since it's in 7.6.x anyway. Closing this one, thanks.

**Pull request closed without merging**
