### PR TITLE
L1T muon online DQM 8_1_X

### PR DESCRIPTION
**Pull request by thomreis**
Port to 8_1_X of PR https://github.com/cms-sw/cmssw/pull/15378

### CODE REVIEW

**Comment by thomreis** [comment]
I have added the zero suppression DQM module.
This is related to PR https://github.com/cms-sw/cmssw/pull/15387

**Comment by thomreis** [comment]
Can someone launch the tests for this please?

**Comment by dmitrijus** [comment]
+1

**Comment by dmitrijus** [comment]
> This is related to PR #15387 

Related how? Which one should be merged first?

**Comment by thomreis** [comment]
The changes in PR #15387 are needed to load the EventFilter/L1TRawToDigi code as a library in other packages.
So PR #15387 should go first.

**Comment by dmitrijus** [comment]
+1

**Comment by slava77** [comment]
-1

needs a rebase (merges dragged in need for reco signature)

**Comment by thomreis** [comment]
Hm. That does not seem to have worked as intended.

**Comment by thomreis** [comment]
OK, I think now it is better.

**Comment by dmitrijus** [comment]
+1

**Comment by thomreis** [comment]
need to rebase this

**Comment by slava77** [comment]
-1
needs a rebase

**Comment by davidlange6** [comment]
@thomreis - should we close this PR?

**Comment by thomreis** [comment]
@davidlange6 - no, I want to wait until PR #15387 is merged and then rebase this one. In case the rebase does not work out well I will close this PR and make a new one.

**Comment by davidlange6** [comment]
ok, thanks for the update

**Comment by mmusich** [comment]
@thomreis #15387 appears to be merged. Would it be then safe to rebase to avoid all the unneeded signatures?

**Comment by ianna** [comment]
@thomreis - please, rebase

**Comment by thomreis** [comment]
This is too messed up. I will close this and make a new PR.

**Pull request closed without merging**
