### PR TITLE
Better era imports 2

### PR DESCRIPTION
**Pull request by kpedro88**
Removing a few lingering imports of `Configuration.StandardSequences.Eras`...

### CODE REVIEW

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by kpedro88** [comment]
I see no changes in the comparisons, as expected.

**Comment by davidlange6** [comment]
thanks @kpedro88 - @rekovic I think the only not-completely trivial changes are in L1 - can you have a look today  so we can merge this in. Thanks

**Comment by kpedro88** [comment]
yes, I found that `stage1L1Trigger` is chained into `run2_25ns`, so there's no need to check for both.

**Comment by dmitrijus** [comment]
+1

**Comment by cvuosalo** [comment]
+1

For #16357 6871eef1ddba7fe51115b2fa0940194431eb3d39

Removing unneeded eras imports. There should be no change in monitored quantities.

The code changes are satisfactory, and Jenkins tests against baseline CMSSW_8_1_X_2016-10-25-1100 show no significant differences, as expected.

**Comment by kpedro88** [comment]
@rekovic @mulhearn please sign off

**Pull request merged**
