### PR TITLE
 [12_3_X] Ecal phisym run3 workflow

### PR DESCRIPTION
**Pull request by simonepigazzini**
#### PR description:

This is a backport to 12_3_X of PR #36988. The backport is needed to perform tests with T0 replays.

### CODE REVIEW

**Comment by francescobrivio** [comment]
backport of #36988

 - @simonepigazzini please change the title to "[12_3_X] Ecal phisym run3 workflow"

**Comment by francescobrivio** [comment]
@cmsbuild please test

**Comment by francescobrivio** [comment]
+1

 - backport of #36988
 - tests clean except the usual MessageLogger and MTD differences

**Comment by francescobrivio** [comment]
@smuzaffar looks like the bot is stuck?

**Comment by smuzaffar** [comment]
looks like again github webhook issue. Now it seems to be ok

**Comment by tvami** [comment]
@cms-sw/orp-l2 this is essentially fully signed

**Comment by francescobrivio** [comment]
> looks like again github webhook issue. Now it seems to be ok

Thanks a lot @smuzaffar!

**Comment by perrotta** [comment]
+1

**Pull request merged**
