### PR TITLE
L1 muon DQM for CMSSW_8_0_23

### PR DESCRIPTION
**Pull request by thomreis**
This PR includes PR #15388 and has the DQM related commits of PR #15378 cherry-picked on top of it.

After testing, commit https://github.com/cms-sw/cmssw/commit/825dbe69b1c3c8c7614de2cce46a227143a4198a was added to fix a ProductNotFound.

This should supersede PRs #16502 and #15378.

### CODE REVIEW

**Comment by thomreis** [comment]
@rekovic please test this PR as it is needed for muon online DQM withthe newly deployed release 8_0_23

**Comment by rekovic** [comment]
please test

**Comment by dmitrijus** [comment]
hold

**Comment by dmitrijus** [comment]
please close this one

**Comment by thomreis** [comment]
Should it not be kept open for the tagCollector? If #16513 is used online instead the emulator workflow will not work.

**Comment by thomreis** [comment]
So I'm closing this to not have too many PRs open. However, online this one instead of #16513 should be used since it contains a fix for the L1 emulator DQM configuration.

**Pull request closed without merging**
