### PR TITLE
HCALDQM: Update DigiTask for 2018 HE (10_1_X backport)

### PR DESCRIPTION
**Pull request by DryRun**
Backport of https://github.com/cms-sw/cmssw/pull/22724 to 10_1_X (the original PR was intended for 10_1_X, but was merged in 10_2_X).

Updates HCALDQM DigiTask for 2018 HE. A number of plots were not filled for HEP17 last year because it would have mixed QIE8 and QIE11 digis; QIE11-specific plots were created in QIE11Task. Now that HE==QIE11, I integrated the plots of interest from QIE11Task to DigiTask.

I also included one small bug fix for LaserTask: with the 2018 HE, the range for the laser signal has to be increased.

#22971 should be merged first.

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
This PR looks needed to fix a problem reported in prompt RECO, see the thread

https://hypernews.cern.ch/HyperNews/CMS/get/tier0-Ops/1870.html

@DryRun thanks for the fast reaction, this PR was not highlighted as crucial for data taking, and since its master version entered into CMSSW_10_2_0_pre2 that is still under validation, I was waiting for the outcome of that check to integrate it into CMSSW_10_1_X. At this point this is becoming more a fix, but I would like to understand what is causing the crash and why this did not appear so far

**Comment by fabiocos** [comment]
@dmitrijus @jfernan2 @schneiml BTW I understand this is running in online DQM already?

**Comment by DryRun** [comment]
Hi @fabio, I was also surprised that it didn't crash earlier. The reason is that the histogram that causes the crash is filled very rarely, only when a QIE10/QIE11 returns a TDC value that is not allowed in the specification. 

Regarding online DQM, this PR is indeed deployed, as part of https://github.com/cms-sw/cmssw/pull/23006.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
