### PR TITLE
ECAL PF thresholds for aging [91X]

### PR DESCRIPTION
**Pull request by kpedro88**
Backport of #19687

Also updates the phase2 auto GT (better late than never).

@davidlange6, we need a new 91X patch release once this is merged.

### CODE REVIEW

**Comment by kpedro88** [comment]
please test

**Comment by kpedro88** [comment]
please test

**Comment by kpedro88** [comment]
please test

**Comment by kpedro88** [comment]
Validation results:
from Sasha Ledovskoy: https://indico.cern.ch/event/652731/contributions/2656797/attachments/1492050/2320341/170712_upsg_ledovskoy_B.pdf
from Nick Smith: https://indico.cern.ch/event/652731/contributions/2656796/attachments/1492036/2320660/nsmith_upsg_egamma_fix_20170713.pdf

@davidlange6 please merge ASAP so we can make patch3

**Comment by kpedro88** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by kpedro88** [comment]
@smuzaffar can this persistent DAS error be addressed?

**Comment by smuzaffar** [comment]
@cmsbuild, please test with #19730
@kpedro88  https://github.com/cms-sw/cmssw/pull/19730 should fix this.

**Comment by kpedro88** [comment]
@smuzaffar thanks

**Comment by kpedro88** [comment]
@davidlange6 we need a release urgently, please provide an ETA

**Comment by davidlange6** [comment]
merge

**Pull request merged**
