### PR TITLE
Updated PR for CorrWithOverlapRemovalCondition.cc

### PR DESCRIPTION
**Pull request by namppl**
#### PR description:
Update of https://github.com/cms-sw/cmssw/pull/36103. Rebased to the latest commit.

#### PR validation:
Unit tests done

### CODE REVIEW

**Comment by cecilecaillol** [comment]
please test

**Comment by rekovic** [comment]
This PR is the change of logic from the one meant by OverlapRemoval. In the logic of this PR there is no OverlapRemoval but rather a condition of three objects with correlation conditions imposed on pairs of two. No L1T object is removed !! 

The logic of this PR is what I implemented in the new class CorrThreeBodyByTwoBodyCondition https://github.com/cms-sw/cmssw/pull/36441 which was resently reverted and which I am now fixing.   Development of the logic of this PR needs to continue on that class and not touch the CorrWithOverlapRemovalCondition which does something very different, removes overlapping objects at L1T, many of them, to reduce the fake rate.

Both emulators need to be made available in the GlobalTrigger emulation and part of the CMSSW release for physics  (May), This PR destroys and hijacks the ongoing developments of OverlapRemoval which tries to improve the GlobalTrigger by ridding the overlaps.   Since the proponents of the new condition did not bother developing the emulator for their proposals, I am making one for them!! The hope is to have the GlobalTrigger emulator fully supporting this logic in the ThreeByTwoBodyCorrelation and the one of true OverlapRemoval next week.

**Comment by cecilecaillol** [comment]
please test

**Comment by cecilecaillol** [comment]
+l1

**Comment by perrotta** [comment]
@cecilecaillol I don't think that @rekovic agrees with the content of this PR, see https://github.com/cms-sw/cmssw/pull/36758#issuecomment-1017495022
Could you please agree among yourself a common @cms-sw/l1-l2 decision for this PR

I'll keep this PR on hold while waiting for such additional information

**Comment by perrotta** [comment]
hold

**Comment by cecilecaillol** [comment]
@perrotta Merging this PR is supported by L1 DPG conveners and L1 project managers

**Comment by lathomas** [comment]
@perrotta I confirm that  the strategy of this PR is blessed by L1 DPG. We would need it to be merged as soon as possible for seed developments that need to make it in 12_3. Thanks !

**Comment by perrotta** [comment]
unhold

**Comment by perrotta** [comment]
+1
- Comment https://github.com/cms-sw/cmssw/pull/36758#issuecomment-1017495022 from @rekovic is superseded by https://github.com/cms-sw/cmssw/pull/36758#issuecomment-1019956207 from @cecilecaillol and https://github.com/cms-sw/cmssw/pull/36758#issuecomment-1021135864 from @lathomas 
- @cecilecaillol @lathomas thank you for the confirmation; next time please answer directly to the comment that suggests to reject this PR, and the review can proceed smoothly

**Comment by perrotta** [comment]
merge

**Pull request merged**
