### PR TITLE
Run3-gex67 Modify Run3 workflows with changed version of RP devices

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Modify Run3 workflows with changed version of RP devices (bug fix)

#### PR validation:

Use scripts from SimG4Core/PrintGeomInfo/test/python to check scenarios defined using DDD and also DD4Hep

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
+1

**Comment by cvuosalo** [comment]
@bsunanda Thanks for cleaning this up.

**Comment by srimanob** [comment]
+Upgrade

**Comment by cvuosalo** [comment]
@silviodonato @qliphy If pre6 hasn't been built yet, it would be good to get this PR in pre6.

**Comment by srimanob** [comment]
> @silviodonato @qliphy If pre6 hasn't been built yet, it would be good to get this PR in pre6.

Hi @cvuosalo pre6 built is done,
https://github.com/cms-sw/cmssw/issues/33426

**Comment by silviodonato** [comment]
Yes, we built pre6, but we are waiting for 12_0_X before merging new PRs

**Comment by qliphy** [comment]
+1

**Pull request merged**
