### PR TITLE
Enable SoA range checking by default

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Enable SoA range checking by default.

#### PR validation:

None.

#### Backport status:

To be backported to 14.0.x for data taking.

### CODE REVIEW

**Comment by fwyzard** [comment]
please test

**Comment by Martin-Grunewald** [comment]
@fwyzard 
What is the status of this and its backport to 14_0?

**Comment by fwyzard** [comment]
I'm testing what is the impact, both in terms of catching errors, and on the HLT performance.

**Comment by fwyzard** [comment]
The impact on the HLT is less than 1%, from
```
Running 4 times over 10300 events with 8 jobs, each with 32 threads, 24 streams and 1 GPUs
   694.4 ±   0.2 ev/s (10000 events, 98.0% overlap)
   692.5 ±   0.3 ev/s (10000 events, 97.9% overlap)
   695.4 ±   0.2 ev/s (10000 events, 98.7% overlap)
   692.8 ±   0.2 ev/s (10000 events, 98.4% overlap)
 --------------------
   693.8 ±   1.4 ev/s
```
to
```
Running 4 times over 10300 events with 8 jobs, each with 32 threads, 24 streams and 1 GPUs
   688.7 ±   0.2 ev/s (10000 events, 99.5% overlap)
   690.7 ±   0.2 ev/s (10000 events, 98.2% overlap)
   690.7 ±   0.2 ev/s (10000 events, 98.8% overlap)
   691.1 ±   0.2 ev/s (10000 events, 98.7% overlap)
 --------------------
   690.3 ±   1.0 ev/s
```

**Comment by fwyzard** [comment]
+heterogeneous

**Comment by fwyzard** [comment]
enable gpu

**Comment by fwyzard** [comment]
please test

(to refresh the test results)

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
