### PR TITLE
Remove some const-away casts from EventFilter

### PR DESCRIPTION
**Pull request by makortel**
To clean up static analyzer reports.

Tested in CMSSW_10_4_X_2018-10-25-2300, no changes expected.

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
@cmsbuild, please abort

**Comment by makortel** [comment]
Missed a few cases in `CSCTFEvent.cc`.

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by thomreis** [comment]
+1

**Pull request merged**
