### PR TITLE
swap the position in the fragment list for FastSim and FullSim

### PR DESCRIPTION
**Pull request by prebello**
this PR aims to adequate the position of new FastSim 2017 and (usual) FullSim 2018 input strings in 10_4_X release, based on the new implementation of FastSim 2017 in 9_4_X #25123 

@fabiocos in the case you think it is useful to maintain the good shape of the code, please consider it.

local tests ok

### CODE REVIEW

**Comment by prebello** [comment]
please test workflow 10824.0,11024.0,250202.18,250399.17,250400.17,25400.17

**Comment by prebello** [comment]
+1

**Comment by fabiocos** [comment]
@prebello this is essentially an internal ordering of tests that is useful for your habit, but does not change any functionality right?
@kpedro88 please sign it in case for reference, although there is nothing specifically referring to upgrade here

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Comment by prebello** [comment]
@fabiocos exactly only a matter of an internal ordering. Thank you

**Comment by kpedro88** [comment]
+upgrade

**Pull request merged**
