### PR TITLE
HLT BTV DQM offline

### PR DESCRIPTION
**Pull request by silviodonato**
This PR add the DQM offline for the online b-tagging. 
It is a follow up of https://github.com/cms-sw/cmssw/pull/10017 .
It includes the suggestions by @deguio .
I also added a file to test it in the test folder.

### CODE REVIEW

**Comment by silviodonato** [comment]
As soon as it will be approved, I will prepare the backport to 75X and 76X

**Comment by deguio** [comment]
please test

**Comment by silviodonato** [comment]
I try it with CMSSW_7_6_X_2015-08-04-2300 and I didn't see any conflict!
What do I have to do? Thanks, Silvio.

**Comment by davidlange6** [comment]
did you forget to commit BTVHLTOfflineAnalyzer_cff.py?

**Comment by silviodonato** [comment]
I removed it, and I fixed "DQMOffline_Trigger_cff".
My comment was referring to "This branch has conflicts that must be resolved", not to the fact that the cmsbuild test failed. 
Thanks, Silvio.

**Comment by deguio** [comment]
ciao silvio,
could you please rebase this one? it is not mergeable anymore..
thanks,
F.

**Comment by silviodonato** [comment]
Ok, the problem was that I did't see any conflict in CMSSW_7_6_X_2015-08-04-2300.
Now I rebased with CMSSW_7_6_X_2015-08-10-1100.
Thanks, Silvio.

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
ciao @silviodonato 
here my comments:

- the following scope should go to the DQMBeginRun
https://github.com/silviodonato/cmssw/blob/BTVHLTDQMOffline/DQMOffline/Trigger/src/BTVHLTOfflineSource.cc#L258-L278
- please remove all the commented lines
- the whole way the MEs are stored in the PathInfo class and then accessed seems not an efficient one to me. maybe making all the private members of the PathInfo class public, would avoid having to maintain all the methods in it:
https://github.com/silviodonato/cmssw/blob/BTVHLTDQMOffline/DQMOffline/Trigger/interface/BTVHLTOfflineSource.h#L141-L179
a struct can probably do the work.

F.

**Comment by silviodonato** [comment]
ciao @deguio,
I modified the code according to the first two points.
About your third point, you are proposing to use a struct public containing the PathInfo, right? What about the MEs ?
Thanks, Silvio.

**Comment by deguio** [comment]
+1

**Comment by deguio** [comment]
I believe that the code can go in but I have one last doubt.
I thought that this module should run on the HLTMon stream which has a special event content and it is reconstructed with an express-like reco. if this is the case, the module should be included in:
OfflineHLTMonitoring
and not in:
offlineHLTSource

please let me know.
thanks,
F.

**Comment by puigh** [comment]
I believe that this module requires extra event content, which is why it received special status. Because of this, it should run on HLTMon stream. Therefore, you are correct, yes, it should be included in OfflineHLTMonitoring and not offlineHLTSource.

Cheers,
Darren

**Comment by silviodonato** [comment]
Where is the python configuration for OfflineHLTMonitoring? Which changes do I need to apply to the code? Do you have an example?
Thanks, Silvio.

**Comment by deguio** [comment]
everything is in:
https://github.com/silviodonato/cmssw/blob/BTVHLTDQMOffline/DQMOffline/Trigger/python/DQMOffline_Trigger_cff.py

it is a matter of moving line 52 after:
https://github.com/silviodonato/cmssw/blob/BTVHLTDQMOffline/DQMOffline/Trigger/python/DQMOffline_Trigger_cff.py#L70

F.

**Comment by silviodonato** [comment]
Thanks!

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1
@silviodonato please backport this PR to previous cycles where needed.
ciao,
F.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
