### PR TITLE
Make statics constexpr in HcalTopology

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

This fixes a problem when compiling using UBSAN as a static const object is still required to have storage assigned while a constexpr does not have storage.

#### PR validation:

This compiles and links using CMSSW_11_0_UBSAN_X_2019-06-18-1100 IB.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
[I pushed a commit to the wrong branch, sorry everyone]

**Comment by Dr15Jones** [comment]
please test

**Comment by cvuosalo** [comment]
+1

**Comment by bsunanda** [comment]
@Dr15Jones Chris I am making changes to HcalTopology and it has all the fixes suggested by you. I am making the PR for some dense indexing. Could this PR be closed as there will be conflicts. Please let me know

**Comment by fabiocos** [comment]
@bsunanda the simplest thing is that I merge this PR now and your rebase (if needed) on top of it

**Comment by fabiocos** [comment]
+1

**Pull request merged**
