### PR TITLE
Clang tidy checks - add new checks to .clang-tidy

### PR DESCRIPTION
**Pull request by mrodozov**
#### PR description:

Adds the new checks to be applied on every PR.
To be merged after https://github.com/cms-sw/cmssw/pull/30632

#### PR validation:

Applied on cmssw, with few exceptions (that are fixed) it builds

### CODE REVIEW

**Comment by makortel** [comment]
Was it this PR https://github.com/cms-sw/cmssw/pull/30505 after which we agreed to enable the new checks?

**Comment by smuzaffar** [comment]
yes @makortel , we will wait for #30505 to be merged and then integrated new checks

**Comment by silviodonato** [comment]
Hi @smuzaffar , @makortel, @mrodozov , https://github.com/cms-sw/cmssw/pull/30505 needs to be updated (there is a conflict to be solved). Can we merge this PR ?

**Comment by mrodozov** [comment]
@silviodonato In short, yes I'm in favor to merge it, tldr:
I checked #30505 last week and it needed rebase. Since it needs rebase and it's only 8 files running the code checks on it when rebasing doesn't look like a big issue to me, but there might be other concerns.

**Comment by silviodonato** [comment]
@smuzaffar , @makortel we agreed to merge this PR, didn't we?

**Comment by smuzaffar** [comment]
+core
yes

**Comment by silviodonato** [comment]
+1

**Pull request merged**
