### PR TITLE
[`12.4_HLT_X`] HLT configurations for 2022 MC: from menu 2022 V1.4 to menu 2022 V1.5

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

Development of HLT menu for `CMSSW_12_4_HLT_X`.
This update is meant *exclusively* for the Summer2024 production of Run 3 MC. 

**This PR is NOT a backport**.

This version of the GRun Frozen HLT menu corresponds to to the **"V1.5"** menu for the 2022 pp data-taking period.  The older version **"V1.4"** is removed. All TSG integration tests are updated accordingly.
This update includes the integration of the following JIRA tickets:
   - [CMSHLT-2474](https://its.cern.ch/jira/browse/CMSHLT-2474): [TSG] fixes to PS values of 5 triggers (e.g. `HLT_ZeroBias_Alignment_v*`)
  -  [CMSHLT-2486](https://its.cern.ch/jira/browse/CMSHLT-2486): [BPH] new triggers with dz requirement for double-electron parking
  -  [CMSHLT-2487](https://its.cern.ch/jira/browse/CMSHLT-2487): [BPH] single-electron control trigger for double-electron parking triggers (currectly disabled, PS=0)
  -  [CMSHLT-2488](https://its.cern.ch/jira/browse/CMSHLT-2488): [BPH] another single-electron control trigger for double-electron parking triggers (currectly disabled, PS=0)
  -  [CMSHLT-2494](https://its.cern.ch/jira/browse/CMSHLT-2494): [EXO] fix to inclusive delayed-jet control trigger
  -  [CMSHLT-2366](https://its.cern.ch/jira/browse/CMSHLT-2366): [BTV] disable `DeepCSV` triggers of `GRun`
  -  [CMSHLT-2476](https://its.cern.ch/jira/browse/CMSHLT-2476): [TSG] seed of `HLT_EphemeralZeroBias` changed to `L1_ZeroBias_copy`
  -  [CMSHLT-2478](https://its.cern.ch/jira/browse/CMSHLT-2478): [MUO] removed some HLT-muon modules from `suppressWarning` list
  -  [CMSHLT-2491](https://its.cern.ch/jira/browse/CMSHLT-2491): [TSG] update PSs of `HLT_HT300_Beamspot` trigger
  -  [CMSHLT-2495](https://its.cern.ch/jira/browse/CMSHLT-2495): [TSG] update PSs of Ephemeral triggers
  -  [CMSHLT-2497](https://its.cern.ch/jira/browse/CMSHLT-2497): [TSG] added L1T seed to `HLT_EphemeralPhysics` (L1A Physics "masking" L1_ZeroBias_copy)
  - [CMSHLT-2499](https://its.cern.ch/jira/browse/CMSHLT-2499): [TSG] added `L1_SingleTau130er2p1` to L1T seeds using `L1_SingleTau120er2p1`
  -  [CMSHLT-2501](https://its.cern.ch/jira/browse/CMSHLT-2501): [EXO] added L1Tau-seeded delayed-jet triggers
  -  [CMSHLT-2514](https://its.cern.ch/jira/browse/CMSHLT-2514): [TSG] disable two displaced-dijet and two PNET triggers
  -  [CMSHLT-2518](https://its.cern.ch/jira/browse/CMSHLT-2518): [HIG] update of 1 L1T seed and 2 PSs of MSSM-Hbb control triggers
  -  [CMSHLT-2519](https://its.cern.ch/jira/browse/CMSHLT-2519): [TSG] disable 4 fatjet softdrop-mass triggers plus other PS changes
  -  [CMSHLT-2520](https://its.cern.ch/jira/browse/CMSHLT-2520): [BTV] updated PSs of BTagMu triggers
  -  [CMSHLT-2527](https://its.cern.ch/jira/browse/CMSHLT-2527): [EXO] updated L1T seed of SingleLLPJet triggers
  - [CMSHLT-2534](https://its.cern.ch/jira/browse/CMSHLT-2534): [JME] doubled PS of `AlCa_*PFJet*` triggers
  -  [CMSHLT-2537](https://its.cern.ch/jira/browse/CMSHLT-2537): [TSG] sync PSs of offline menu with V1.4.5 online menu
  -  [CMSHLT-2539](https://its.cern.ch/jira/browse/CMSHLT-2539): [TSG] use common PF-scouting sequence in `MC_Run3_PFScoutingPixelTracking_v` Path

This corresponds to the updates to the `GRun` subtable as in https://github.com/cms-sw/cmssw/pull/39679 and https://github.com/cms-sw/cmssw/pull/39926

In addition, commit https://github.com/cms-sw/cmssw/pull/45939/commits/8d33e25b52d167b177e62717e85a822fbf474756 removes support for the frozen menu 2022 V1.2, unused for the Summer24 MC production.

#### PR validation:

TSG integration tests 

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Not a backport, not to be forward-ported.

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by vlimant** [comment]
Hi @mmusich , thanks for the PR. Is it possible to keep v1.4 in, or are the changes in the v1.5 menu incompatible ?

**Comment by mmusich** [comment]
>  Is it possible to keep v1.4 

It is possible, I'd rather not, given the amount of confusion that having multiple menus has created in PdmV.

**Comment by vlimant** [comment]
please keep v14 around ; never mind the confusion

**Comment by mmusich** [comment]
> please keep v1.4 around ; never mind the confusion

please provide a justification.

**Comment by vlimant** [comment]
for the Summer24 MC production for 2022, we would like to keep the option of choosing between v1.4 and v1.5, even though the v1.5 option is preferred

**Comment by mmusich** [comment]
> for the Summer24 MC production for 2022, we would like to keep the option of choosing between v1.4 and v1.5, even though the v1.5 option is preferred

I would think this decision is ultimately a TSG one. When I get word from TSG coordination to keep V1.4 I'll comply.

**Comment by vlimant** [comment]
agreed. 
2 cents : "rather not, given the amount of confusion that having multiple menus has created in PdmV." is not a good argument to drop it. while my argument to keep it is more sensible.

**Comment by mmusich** [comment]
> 2 cents : "rather not, given the amount of confusion that having multiple menus has created in PdmV." is not a good argument to drop it.

I beg to disagree, because the any mistakes in the L1T+HLT configuration would need then to be ultimately debugged by TSG experts, thus I would tend to minimize the amount of effort we need to spend on it.

**Comment by antoniovilela** [comment]
What is missing for this PR? Does it impact validation for the production?

**Comment by mmusich** [comment]
> What is missing for this PR? 

I am not sure to understand the question: I guess passing tests and `hlt` signature. 

> Does it impact validation for the production?

probably. PPD should clarify.

**Comment by antoniovilela** [comment]
> > What is missing for this PR?
> 
> I am not sure to understand the question: I guess passing tests and `hlt` signature.
> 
> > Does it impact validation for the production?
> 
> probably. PPD should clarify.

What is the timeline for HLT checks & validation of the updates in this PR

**Comment by mmusich** [comment]
> What is the timeline for HLT checks & validation of the updates in this PR.

This menu (with minor adjustments) took data at P5 in the last part of 2022. Provided it passes tests here I am not expecting it giving (technical) problems in production. As for the physics content I am not qualified to provide an answer. How was the previous version validated?

**Comment by antoniovilela** [comment]
> > What is the timeline for HLT checks & validation of the updates in this PR.
> 
> This menu (with minor adjustments) took data at P5 in the last part of 2022. Provided it passes tests here I am not expecting it giving (technical) problems in production. As for the physics content I am not qualified to provide an answer. How was the previous version validated?

If there is a reason to use the previous version in production, I would say it is PPD's call. If the new version is good for production and does not delay things due to validation, then I would wait for the PR to be merged (maybe still today) ?

**Comment by antoniovilela** [comment]
We have started a patch build without this, we can make a new patch if agreed by all parties (PPD & Trigger coordination).

**Comment by mmusich** [comment]
> We have started a patch build without this, we can make a new patch if agreed by all parties (PPD & Trigger coordination).

OK. Once tests are done here, I'll remove support also for V1.2 (not needed in this cycle).

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
Ok 8d33e25 cannot work on the relvals without more complicated changes involving conditions.

**Comment by mmusich** [comment]
+hlt

**Pull request merged**
