### PR TITLE
update Method3 with new time slew parametrization and response correction for data and MC (75x)

### PR DESCRIPTION
**Pull request by fwyzard**
- update Method3 with new time slew parametrization and response correction for data and MC
- customise the HLT for the updates to HCAL method 3

### CODE REVIEW

**Comment by fwyzard** [comment]
backport #11091 / #11100 to CMSSW 7.5.x

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
+1

**Comment by fwyzard** [comment]
I've checked (in 76x) that the parameters are added to the HLT configuration only for Monte Carlo.
For data, the correct values should be taken from fillDescriptions().

**Comment by davidlange6** [comment]
@fwyzard - neither this nor the 76x version merge now. (not sure why)

**Comment by slava77** [comment]
@abdoulline @davidlange6 @fwyzard 
please clarify what's the status of the 76X integration of the HCAL changes.
- this PR (local reco changes) doesn't merge
- #11071 (digitization updates in time slew [HBHE only?]) and #11070 (HF MC scale down) are fully signed but are not merged yet .. and they are still mergeable

**Comment by fwyzard** [comment]
rebased

**Comment by fwyzard** [comment]
+1

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/11101	d12d65b
- the same changes are applied here as in #11100 
- jenkins tests pass and comparisons with baseline show expected behavior:
    - no changes in monitored RECO products 
    - HLT calorimeter-related plots change noticeably in 25202 (ttbar with 25ns) but without major failures; HLT plots in other workflows are not changed by this PR

**Comment by abdoulline** [comment]
NB: updated part of _MC_ Method 3 (in this PR) s based on new HcalTimeSlewSim. So the two should be used in sync...  
While David's back-compatible  https://github.com/cms-sw/cmssw/pull/11184
keeps new HcalTimeSlewSim as an option.

**Pull request merged**
