### PR TITLE
Run3-alca141X Modify the macros in view of using depth-dependent and phi-dependent correction factors in the estimation of overall correction factors

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Modify the macros in view of using depth-dependent and phi-dependent correction factors in the estimation of overall correction factors

#### PR validation:

Used in producing the final correction factors

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by tvami** [comment]
@bsunanda can you please make these scripts into a unit test? We are really not testing anything meaningful like this

**Comment by bsunanda** [comment]
@tvami I shall rearrange the scripts in a way to make unit tests. I shall do that for the next PR

**Comment by tvami** [comment]
+alca
 * with the promise that these will be made into a unit test, see https://github.com/cms-sw/cmssw/pull/41101#issuecomment-1528656968

**Comment by perrotta** [comment]
+1

**Pull request merged**
