### PR TITLE
bsunanda:Run2-hcx49 First attempt of hexagonal geometry for HGCal

### PR DESCRIPTION
**Pull request by bsunanda**
Tested only for overlaps. Needs lot more work to make it useful for simulation (and then reconstruction)

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by ianna** [comment]
@bsunanda - there are 34 very small overlaps reported by cmsShow. Note, an overlap reported only once per volume copy.

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by ianna** [comment]
+1

**Comment by davidlange6** [comment]
i'm surprised that this is changing an existing geometry - hgcal developers do not rely on what was previously in v7 for anything?

**Comment by bsunanda** [comment]
The earlier v7 was a bit pre-emptive. It was supposed to make ground for this one. The earlier v7 was to define the absorber thickness. The real structure is coming from this.
________________________________

**Comment by davidlange6** [comment]
+1

Thanks for the confirmation.

**Pull request merged**
