### PR TITLE
Load Accelerators_cff unconditionally in customizeHLTforPatatrack.py, and clean up GPU/CPU forcing functions

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

Follow-up to https://github.com/cms-sw/cmssw/pull/36699#discussion_r808641430. Also clean up `forceGpuOffload()` and `resetGpuOffload()` functions in favor of `process.options.accelerators` that was added in #36699.

#### PR validation:

None

### CODE REVIEW

**Comment by makortel** [comment]
I believe with the functionality introduced in https://github.com/cms-sw/cmssw/pull/36699 these functions would be unnecessary
https://github.com/cms-sw/cmssw/blob/4e650d8eb644ac5d19d78151bc61d1a84cd59d39/HLTrigger/Configuration/python/customizeHLTforPatatrack.py#L39-L49

If you want, I can clean them up in this PR (or leave them up to you).

@fwyzard

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
enable gpu

**Comment by missirol** [comment]
@makortel , in https://github.com/cms-sw/cmssw/pull/36699#discussion_r808641430 I see the suggestion was about using `Accelerators_cff`, while this PR still uses `ProcessAcceleratorCUDA_cfi`. Right now the two are equivalent, but could you explain a bit please?

**Comment by fwyzard** [comment]
> I believe with the functionality introduced in #36699 these functions would be unnecessary
> 
> https://github.com/cms-sw/cmssw/blob/4e650d8eb644ac5d19d78151bc61d1a84cd59d39/HLTrigger/Configuration/python/customizeHLTforPatatrack.py#L39-L49

Yes, the should be replaced by the use of the new functionality.

> If you want, I can clean them up in this PR (or leave them up to you).

Sure, please remove them :-)

**Comment by makortel** [comment]
> in [#36699 (comment)](https://github.com/cms-sw/cmssw/pull/36699#discussion_r808641430) I see the suggestion was about using `Accelerators_cff`, while this PR still uses `ProcessAcceleratorCUDA_cfi`. Right now the two are equivalent, but could you explain a bit please?

Thanks @missirol for catching! I was being sloppy, I changed the `load()` now to `Accelerators_cff`.


> > If you want, I can clean them up in this PR (or leave them up to you).
> 
> Sure, please remove them :-)

Done.

**Comment by missirol** [comment]
please test

**Comment by missirol** [comment]
+hlt

(the many tiny differences in the outputs of [wf 11634.506](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisonsGPU/CMSSW_12_3_X_2022-02-25-1100+28b847/48578/dqm-histo-comparison-summary.html) are a known feature, not related to this PR)

**Pull request merged**
