### PR TITLE
Change ElectronID to the latest in python configuration for JetPlusTrack algoritm

### PR DESCRIPTION
**Pull request by kodolova**
#### PR description:

According the request in https://github.com/cms-sw/cmssw/pull/46868
ElectronID was changed in JetPlusTrackCorrections_cfi.py
to egmGsfElectronIDs:cutBasedElectronID-RunIIIWinter22-V1-tight
re-reco of electronid was removed from JetPlusTrackCorrections_cff.py

Changed in pythons configuration for the new ElectronID according the
https://github.com/cms-sw/cmssw/pull/46868 
  
#### PR validation:
runMatrix results are in
/afs/cern.ch/work/k/kodolova/public/HMUMUBB/NEWEGMID/MATRIX/

### CODE REVIEW

**Comment by jfernan2** [comment]
@kodolova please add a minimal description of the PR. Thank you

**Comment by jfernan2** [comment]
Related to https://github.com/cms-sw/cmssw/pull/46868

**Comment by Dr15Jones** [comment]
please test

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
