### PR TITLE
cyclic dependency:  Merge Geometry/CommonDetUnit in to CommonTopologies

### LINKED ISSUE #28415: Cyclic dependency between  Geometry/CommonTopologies and Geometry/CommonDetUnit
UBSAN IBs failed [a] due to `undefined reference to 'typeinfo for GeomDetType'`. `GeomDetType` comes from `Geometry/CommonDetUnit` but `Geometry/CommonTopologies` can not depend on  `Geometry/CommonDetUnit` due to cyclic dependency [b].

[a]
https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc7_amd64_gcc820/CMSSW_11_0_UBSAN_X_2019-11-15-2300/Geometry/CommonTopologies

[b]
```
>grep Geometry/CommonTopologies -R Geometry/CommonDetUnit
Geometry/CommonDetUnit/BuildFile.xml:<use   name="Geometry/CommonTopologies"/>
Geometry/CommonDetUnit/interface/PixelGeomDetUnit.h:#include "Geometry/CommonTopologies/interface/ProxyPixelTopology.h"
Geometry/CommonDetUnit/interface/PixelGeomDetType.h:#include "Geometry/CommonTopologies/interface/PixelTopology.h"
Geometry/CommonDetUnit/src/PixelGeomDetUnit.cc:#include "Geometry/CommonTopologies/interface/SurfaceDeformation.h"
Geometry/CommonDetUnit/src/GeomDet.cc:#include "Geometry/CommonTopologies/interface/Topology.h"

>grep -R  Geometry/CommonDetUnit Geometry/CommonTopologies
Geometry/CommonTopologies/interface/GeometryAligner.h:#include "Geometry/CommonDetUnit/interface/DetPositioner.h"
Geometry/CommonTopologies/interface/GeometryAligner.h:#include "Geometry/CommonDetUnit/interface/GeomDet.h"
Geometry/CommonTopologies/interface/ProxyPixelTopology.h:#include "Geometry/CommonDetUnit/interface/PixelGeomDetType.h"
Geometry/CommonTopologies/src/ProxyPixelTopology.cc:#include "Geometry/CommonDetUnit/interface/PixelGeomDetType.h"
```

### PR DESCRIPTION
**Pull request by smuzaffar**
#### PR description:

As mentioned is https://github.com/cms-sw/cmssw/issues/28415 , there is cyclic dependency between Geometry/CommonDetUnit in to CommonTopologies . Here we propose to merge these two packages.

resolves #28415

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by perrotta** [comment]
+1
- The cyclic dependency is removed by merging the two Geometry packages
- For reco this PR trivially takes note of the move of a few headers from CommonDetUnit to CommonTopologies
- Jenkins tests pass and show no differences

**Comment by jfernan2** [comment]
+1

**Comment by alja** [comment]
+1

**Comment by Martin-Grunewald** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade

**Comment by smuzaffar** [comment]
@fabiocos , can we get this in? Hopefully this should the UBSAN IBs build error ( https://cmssdt.cern.ch/SDT/cgi-bin/showBuildLogs.py/slc7_amd64_gcc820/www/fri/11.0.UBSAN-fri-23/CMSSW_11_0_UBSAN_X_2019-11-29-2300 )

**Comment by santocch** [comment]
+1

**Comment by pohsun** [comment]
+1

**Comment by fabiocos** [comment]
@ggovi @rekovic the updates in your area look straightforward and minimal, please have a look anyway

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Comment by fabiocos** [comment]
@smuzaffar the integration of #28503 in parallel to this PR has broken a couple of new relvals, I'll fix that

**Pull request merged**
