### PR TITLE
SimG4CMS/Calo : gcc 6.0 misleading-indentation warning flags potential bug; with formatting fix

### PR DESCRIPTION
**Pull request by gartung**
/build/cmsbuild/jenkins-workarea/workspace/build-any-ib/w/tmp/BUILDROOT/8258e37281729e179b5af9c3b033d930/opt/cmssw/slc6_amd64_gcc600/cms/cmssw/CMSSW_8_1_X_2016-06-26-2300/src/SimG4CMS/Calo/src/HFShowerLibrary.cc:122:3: warning: this 'if' clause does not guard... [-Wmisleading-indentation]
    if (fibre)  delete   fibre;  fibre  = 0;
   ^~
/build/cmsbuild/jenkins-workarea/workspace/build-any-ib/w/tmp/BUILDROOT/8258e37281729e179b5af9c3b033d930/opt/cmssw/slc6_amd64_gcc600/cms/cmssw/CMSSW_8_1_X_2016-06-26-2300/src/SimG4CMS/Calo/src/HFShowerLibrary.cc:122:32: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the 'if'
   if (fibre)  delete   fibre;  fibre  = 0;
                                ^~~~~

  /build/cmsbuild/jenkins-workarea/workspace/build-any-ib/w/tmp/BUILDROOT/8258e37281729e179b5af9c3b033d930/opt/cmssw/slc6_amd64_gcc600/cms/cmssw/CMSSW_8_1_X_2016-06-26-2300/src/SimG4CMS/Calo/test/HOSimHitStudy.cc:505:3: warning: this 'if' clause does not guard... [-Wmisleading-indentation]
    if (eHO17 > 0) nHO++; if (eHO17T > 0) nHOT++;
   ^~
/build/cmsbuild/jenkins-workarea/workspace/build-any-ib/w/tmp/BUILDROOT/8258e37281729e179b5af9c3b033d930/opt/cmssw/slc6_amd64_gcc600/cms/cmssw/CMSSW_8_1_X_2016-06-26-2300/src/SimG4CMS/Calo/test/HOSimHitStudy.cc:505:25: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the 'if'
   if (eHO17 > 0) nHO++; if (eHO17T > 0) nHOT++;
                         ^~
  /build/cmsbuild/jenkins-workarea/workspace/build-any-ib/w/tmp/BUILDROOT/8258e37281729e179b5af9c3b033d930/opt/cmssw/slc6_amd64_gcc600/cms/cmssw/CMSSW_8_1_X_2016-06-26-2300/src/SimG4CMS/Calo/test/HOSimHitStudy.cc:506:3: warning: this 'if' clause does not guard... [-Wmisleading-indentation]
    if (eHO18 > 0) nHO++; if (eHO18T > 0) nHOT++;
   ^~
/build/cmsbuild/jenkins-workarea/workspace/build-any-ib/w/tmp/BUILDROOT/8258e37281729e179b5af9c3b033d930/opt/cmssw/slc6_amd64_gcc600/cms/cmssw/CMSSW_8_1_X_2016-06-26-2300/src/SimG4CMS/Calo/test/HOSimHitStudy.cc:506:25: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the 'if'
   if (eHO18 > 0) nHO++; if (eHO18T > 0) nHOT++;
                         ^~
  /build/cmsbuild/jenkins-workarea/workspace/build-any-ib/w/tmp/BUILDROOT/8258e37281729e179b5af9c3b033d930/opt/cmssw/slc6_amd64_gcc600/cms/cmssw/CMSSW_8_1_X_2016-06-26-2300/src/SimG4CMS/Calo/test/HOSimHitStudy.cc:532:5: warning: this 'if' clause does not guard... [-Wmisleading-indentation]
      if (eHOE17[ieta] > 0) nHOE++; if (eHOE17T[ieta] > 0) nHOET++;
     ^~
/build/cmsbuild/jenkins-workarea/workspace/build-any-ib/w/tmp/BUILDROOT/8258e37281729e179b5af9c3b033d930/opt/cmssw/slc6_amd64_gcc600/cms/cmssw/CMSSW_8_1_X_2016-06-26-2300/src/SimG4CMS/Calo/test/HOSimHitStudy.cc:532:35: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the 'if'
     if (eHOE17[ieta] > 0) nHOE++; if (eHOE17T[ieta] > 0) nHOET++;
                                   ^~
  /build/cmsbuild/jenkins-workarea/workspace/build-any-ib/w/tmp/BUILDROOT/8258e37281729e179b5af9c3b033d930/opt/cmssw/slc6_amd64_gcc600/cms/cmssw/CMSSW_8_1_X_2016-06-26-2300/src/SimG4CMS/Calo/test/HOSimHitStudy.cc:533:5: warning: this 'if' clause does not guard... [-Wmisleading-indentation]
      if (eHOE18[ieta] > 0) nHOE++; if (eHOE18T[ieta] > 0) nHOET++;
     ^~
/build/cmsbuild/jenkins-workarea/workspace/build-any-ib/w/tmp/BUILDROOT/8258e37281729e179b5af9c3b033d930/opt/cmssw/slc6_amd64_gcc600/cms/cmssw/CMSSW_8_1_X_2016-06-26-2300/src/SimG4CMS/Calo/test/HOSimHitStudy.cc:533:35: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the 'if'
     if (eHOE18[ieta] > 0) nHOE++; if (eHOE18T[ieta] > 0) nHOET++;
                                   ^~

### CODE REVIEW

**Comment by civanch** [comment]
@gartung , in HFSHowerLibrary.cc you need to remove checks completely and left only
delete  fibre;
delete  photo;
here (if) is meaningless.

**Comment by civanch** [comment]
Also if cleanup the class 0 better to substituted by nullptr

**Comment by gartung** [comment]
My task is to remove warnings, not cleanup code.

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
