### PR TITLE
Improve support for HIP/ROCm and Alpaka

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Update CMS code for Alpaka devel as of 2023.02.01, that includes some functions and traits previously defined in CMSSW.

Add or improve support for HIP/ROCm in HeterogeneousCore tools and SoA DataFormats, including a dedicated unit test.

This PR requires
  - https://github.com/cms-sw/cmssw-config/pull/91
  - https://github.com/cms-sw/cmsdist/pull/8284

#### PR validation:

Old and new unit tests pass.

### CODE REVIEW

**Comment by fwyzard** [comment]
please test with cms-sw/cmssw-config#91, cms-sw/cmssw-config#91

**Comment by fwyzard** [comment]
code-checks with cms.week0.PR_ac9e8379/53.0-004e1992113b32c3ea5cd84a3366d985

**Comment by fwyzard** [comment]
please test with cms-sw/cmsdist#8284,cms-sw/cmsdist#8285

**Comment by fwyzard** [comment]
please test with cms-sw/cmsdist#8284,cms-sw/cmsdist#8285

**Comment by fwyzard** [comment]
code-checks with cms.week0.PR_ac9e8379/53.0-004e1992113b32c3ea5cd84a3366d985

**Comment by fwyzard** [comment]
+heterogeneous

**Comment by fwyzard** [comment]
> 49 48 47 37 24 5 1 1 1 1 1 tests passed, 0 0 0 0 0 0 0 0 0 0 0 failed

👍🏻

**Comment by perrotta** [comment]
@fwyzard there are now conflicts to be solved for this PR

**Comment by fwyzard** [comment]
Nooooooo.....

**Comment by fwyzard** [comment]
code-checks with cms.week0.PR_ac9e8379/53.0-004e1992113b32c3ea5cd84a3366d985

**Comment by fwyzard** [comment]
please test with cms-sw/cmsdist#8284,cms-sw/cmsdist#8285

**Comment by fwyzard** [comment]
All tests ran fine locally.

**Comment by fwyzard** [comment]
+1

**Comment by perrotta** [comment]
+1
- Differences in tests comes from https://github.com/cms-sw/cmssw/pull/40622

**Pull request merged**
