### PR TITLE
Refactor scatterer addition in aGblPoint to explicitly specify type for scatPrecision.inverse()

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

To test with https://github.com/cms-sw/cmsdist/pull/9053

#### PR validation:

`cmssw` compiles

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

N/A

### CODE REVIEW

**Comment by mmusich** [comment]
test parameters:
   * pull_request = https://github.com/cms-sw/cmsdist/pull/9053

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by sroychow** [comment]
@cms-sw/externals-l2 @cms-sw/orp-l2 @cms-sw/alca-l2  following the discussion in [comment](https://github.com/cms-sw/cmssw/issues/44188#issuecomment-1985955569), can this be reviewed and merged for the next IB? 
Along with the external PR - https://github.com/cms-sw/cmsdist/pull/9053

**Comment by tvami** [comment]
urgent

**Comment by perrotta** [comment]
+alca
- Add explicit type definition as required by the spec updates in the gbl and millepede externals
- It must be merged together with https://github.com/cms-sw/cmsdist/pull/9053 (well, probably it can also get emrged alone... but the real update in the cmsdist PR)

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
