### PR TITLE
Update the standard RECO_AOD_MINIAOD Event Content definitions

### PR DESCRIPTION
**Pull request by jeongeun**
Replacing only the wildcard in second field with specific Module names
(no rejection in other lines.)

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
-1
... for the HLTrigger change. First, please explain why this change is needed.
Second, the HLT file is autogenerated from ConfDB and will be overwritten with the next HLT change.

**Comment by slava77** [comment]
@jeongeun 
Please restrict the changes to RECO/PAT parts:
changes in the following  should be removed
HLTrigger/Configuration
L1Trigger/Configuration
Thank you.

@Martin-Grunewald 
this is a request from reco in a follow up to issues of running in unscheduled mode: if the event content has wildcards and the configuration loaded is not clean (loaded through other "steps"), we can end up running spurious modules.

**Comment by jeongeun** [comment]
I remove the changes in HLTrigger/Configuration and L1Trigger/Configuration.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
the unit test error is not related to this PR, it's present in the IB

**Comment by cvuosalo** [comment]
@jeongeun: Please merge this pull request with #10768 and #10764 to create one new pull request, since these pull requests are changing the same files.

**Comment by jeongeun** [comment]
I applied some changes after checking 2 workflows (8.0 cosmic, 140.53 HI).

**Comment by jeongeun** [comment]
@cmsbuild please test

**Comment by mmusich** [comment]
@jeongeun your PR has conflicting commits. Please rebase.

**Pull request closed without merging**
