### PR TITLE
MiniAOD: use all genParticles for patJets partonFlavour

### PR DESCRIPTION
**Pull request by arizzi**
This should implement Jet flavour in MiniAOD as agreed in the pat (i.e. use all genparticles for flavour stored by value)

@Andrej-CMS  @gpetruc @ahinzmann @amarini @ferencek

### CODE REVIEW

**Comment by arizzi** [comment]
@azzurip

**Comment by gpetruc** [comment]
please test

**Comment by Andrej-CMS** [comment]
Hello @arizzi ,

Sorry, I was at a conference last week and could not reply. The fix looks fine to me. 

Kind regards,
Andrej

**Comment by arizzi** [comment]
the error seem unrelated to me

**Comment by perrotta** [comment]
That error is also in the IB since the merging of #20286, as far as I can understand.
In any case, nothing to do with this PR

**Comment by ahinzmann** [comment]
@arizzi Yes, this is what we agreed on.
@ferencek This change should not break btagging, right?
@Andrej-CMS Can you confirm that you changed exactly this line, when you performed the tests documented in #19048? So you have already tested the result of this PR?

**Comment by ferencek** [comment]
@ahinzmann, yes, b tagging should not be broken since the primary flavor definition is hadron-based so not affected by any changes to the parton-based flavor.

@arizzi, I think `task.add(process.selectedHadronsAndPartons)` in miniAOD_tools.py can also be removed.

**Comment by arizzi** [comment]
@ferencek this PR is meant to be minimal because 94X is closing, I would
not touch anything just for cleanup before this is merged.

**Comment by ferencek** [comment]
@arizzi, fair enough.

**Comment by Andrej-CMS** [comment]
@ahinzmann 
Yes, I tested exactly this setup. If there is another test required, please let me know!

**Comment by arizzi** [comment]
should we retrigger the test (i.e. was the IB fixed?)

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
Net effect (from low stat jenkins tests, wf 10024): move a few jets away from jetflavour=0, and reshuffle a bit the other flavours (here an electron jet becomes a jet from photon):
jetmet__jetvalidation_slimmedjets_partonflavor

**Comment by arizzi** [comment]
I think what we see is a few more gluon jets  instead of flavour = 0 and
one "d" becoming a gluon.

this is expected I'd say.

**Comment by perrotta** [comment]
Indeed: biased by pdgId :-)

ar1izzi <notifications@github.com> ha scritto:

> I think what we see is a few more gluon jets  instead of flavour = 0 and
> one "d" becoming a gluon.
>
> this is expected I'd say.
>

**Comment by perrotta** [comment]
+1
- Use all genparticles for jet flavour stored in MiniAOD
- This moves a few jets away from jetflavour=0, and reshuffle a bit the other flavours; no other changes in reco quantities observed in jenkins tests
- The same is visible also in some larger stat TTbar PU sample:
jetparton

**Comment by davidlange6** [comment]
merge

**Pull request merged**
