### PR TITLE
Updated neutron background simulation

### PR DESCRIPTION
**Pull request by civanch**
For geant4 simulation of neutron background effects for muon system a special simulation required when time window is extended to 0.1 second and all tracking cuts used in normal CMS simulation are disabled. This part of simulation is revised and improved:
1) removed double instantiation of muon-nuclear interaction
2) update EM physics configuration for Geant4 10.2
3) disabled all tracking cuts 
4) added option enabling thermal neutron scattering (E < 4 eV)
5) updated custom fragments for this simulation

All these modifications should not change mainstream SIM step but should help making Muon TDR

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
Hi @civanch - are there some slides/graphs showing the validation done so far?

**Comment by civanch** [comment]
@davidlange6 , muon peoples are trying to run just now to see effects of these modifications (not obvious how long this will take for them). What I have checked myself: neutron HP and neutron HP thermal models are really enabled and the code is running without crashes. I also run standard ttbar without these neutron and it is fine to me. The mainstream should not be affected.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
