### PR TITLE
MTD geometry: remove obsolete geometry scenario D73, superseded by D75 and D76

### PR DESCRIPTION
**Pull request by fabiocos**
#### PR description:

This PR is a follow-up of #32840 and addresses the issue #32882 . The scenario D73 has been effectively replaced by scenarios D75 and D76 (Identical in terms of MTD content), and it has no more reason to exist, as it was made just for ETL v5 integration. The update of this geometry causes D73 to fail, but there is no benefit in fixing this, as its removal was already scheduled in discussions with the Upgrade software coordinator.

#### PR validation:

All the instances of the D73 string referring to the scenario in LXR look to have been addressed, and

```
10:38 cmsdev25 5309> runTheMatrix.py -n | grep D73 | wc -l
0
10:38 cmsdev25 5310> runTheMatrix.py -n --what upgrade | grep D73 | wc -l
0
```

The list of existing wfs is preserved (with the second commit).

### CODE REVIEW

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
please abort

**Comment by fabiocos** [comment]
please test

**Comment by davidlange6** [comment]
as apparently this PR leaves behind some no longer useful xmls - what is the strategy for cleaning out xmls no longer used by any geometry?

**Comment by fabiocos** [comment]
@davidlange6 which xmls are you referring to? The master configurations of the scenario are removed, what else am I missing?

**Comment by davidlange6** [comment]
Things referenced only by this master configuration - perhaps there are none - but the other thread suggests that there would be

**Comment by ianna** [comment]
> as apparently this PR leaves behind some no longer useful xmls - what is the strategy for cleaning out xmls no longer used by any geometry?

AFAIK if the xml files that are no longer used by any scenario they are deleted. The burden is on a PR submitter and reviewer :-)

**Comment by fabiocos** [comment]
@davidlange6 in the particular case of this PR for MTD there should be none, ```v5/etl.xml``` is used in the newer scenarios D75 and D76, and this was the cause of the issue reported by @makortel . Actually the removal of D73 might have happened at the same time, I did not immediately realise that fixing the geometry for the newer caloBase envelope would cause such a problem. As there was no official use of D73, which was made by me for test/development, it looked appropriate an update of the xml instead of a proliferation of temporary development versions.

**Comment by cvuosalo** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

**Comment by chayanit** [comment]
+1

**Comment by qliphy** [comment]
+operations

**Comment by qliphy** [comment]
+1

**Pull request merged**
