### PR TITLE
Migrate rest of {HBHEPhase1,HcalHit,HcalSimple}Reconstructor to EventSetup consumes

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

This PR is part of #31061. It completes the EventSetup-consumes migration for bunch of HCAL modules that were partly migrated earlier, but were causing failures in #31746.

#### PR validation:

Code compiles, these modules no longer triggers the exception of #31746 in a job using them.

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by perrotta** [comment]
+1
- Technical
- Jenkins tests pass

**Comment by silviodonato** [comment]
kind reminder @cms-sw/alca-l2

**Comment by christopheralanwest** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
