### PR TITLE
[81X] update dataRun2 GT with conditions for Sept2016 re-reco

### PR DESCRIPTION
**Pull request by mmusich**
backport of  #16656

# Summary of changes in Global Tags 
 
## RunII data 
 
   * **RunII Offline processing** : [81X_dataRun2_v11](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_dataRun2_v11) as [81X_dataRun2_v10](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_dataRun2_v10) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_dataRun2_v11/81X_dataRun2_v10): with updates of Sept2016 re-reco:
      * updated Tracker Alignment 
      * updated Tracker Surface deformations
      * update LS based Beamspot because of new alignment
      * updated CSC and DT alignment errors to use offline versions
      * updated ES and Ecal channel status
      * updated Hcal channel status
      * updated Ecal ADC2GeV
      * updated Ecal laser corrections
      * updated Ecal pulse shapes
      * updated Hcal response corrections

   * **RunII Offline relval processing** : [81X_dataRun2_relval_v14](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_dataRun2_relval_v14) as [81X_dataRun2_relval_v13](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_dataRun2_relval_v13) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_dataRun2_relval_v14/81X_dataRun2_relval_v13): 
      * updated Tracker Alignment 
      * updated Tracker Surface deformations
      * update LS based Beamspot because of new alignment
      * updated CSC and DT alignment errors to use offline versions
      * updated ES and Ecal channel status
      * updated Hcal channel status
      * updated Ecal ADC2GeV
      * updated Ecal laser corrections
      * updated Ecal pulse shapes
      * updated Hcal response corrections

### CODE REVIEW

**Comment by mmusich** [comment]
@davidlange6 this should solve the issue reported in https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2748.html

@fabozzi: as usual, deployment of Data relvals on recent data acquisitions era necessitates some coordination between AlCa and PdmV. Thanks for your understanding.

**Comment by davidlange6** [comment]
Thanks!

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
