### PR TITLE
Run3-gex16 Correct numbering scheme for ECAL

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Correct numbering scheme for ECAL for dd4hep application. It only allows the step2 job to proceed before getting segfault by the tracker code

#### PR validation:

Tested with examples in SimG4Core/Configuration

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by cvuosalo** [comment]
Please add to the PR description which problems this PR fixes. Does it fix the step2 assertion failure? Does it fix double-placement of EVFE?
Thanks.

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

This is a simple fix, so should be merge promptly.

**Comment by silviodonato** [comment]
+1

**Pull request merged**
