### PR TITLE
[DT DQM] Fix some minor style bugs

### PR DESCRIPTION
**Pull request by jfernan2**
#### PR description:

This PR fixes some minor DT DQM style bugs spotted during the review of the DT DOC documentation

Changes bring in sync the info in the GUI with that on the DT Twikis

This PR affects both Online and Ofline GUIs

#### PR validation:

Validated on private DQM GUI. 

No backport needed

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
Added an additional commit to fix a weird behaviour spotted during a test in ONline DQM playback, now it should be OK. I am sorry for the inconvenience. Thanks

**Comment by jfernan2** [comment]
please test

**Comment by syuvivida** [comment]
Hi @jfernan2 
   We are running the latest update of this PR now at our playback:
https://cmsweb.cern.ch/dqm/online-playback
Please let us know if it's working as expected.

Thanks!!

**Comment by jfernan2** [comment]
Final version of the PR

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
Online DQM playback looks correct. 
Green light from my side to deploy.
Thanks a lot!

**Comment by antoniovagnerini** [comment]
+1 
Tested in playback machine with collision run 379315 and since no issues observed it was then deployed online http://cmsonline.cern.ch/cms-elog/1213060

**Comment by antoniovilela** [comment]
+1

**Comment by syuvivida** [comment]
@jfernan2 could you make a backport of this PR to 14_0_X so that it could be included in the next 14_0_X release? Thanks!!

**Pull request merged**
