### PR TITLE
FastSim removal of unused package FastSimulation/EventProducer

### PR DESCRIPTION
**Pull request by sbein**
#### PR description:

Removing FastSimulation/EventProducer

which contains the FamosProducer.cc and FamosManager.cc ED scripts. They are not used in sample production, and there are currently no other known uses. This is a resolution to the issue:

https://github.com/cms-sw/cmssw/issues/35243

One spurious reference to the Famos producers is also made in  
FastSimulation/ForwardDetectors/test/CastorTowerProducerTest_cfg.py

This does not seem to be usable anymore and the authors of the code left the experiment long ago, and so was also removed. 

#### PR validation:

only unused code is removed, so no changes are "theoretically" possible. A standard recipe from runTheMatrix, 135.1, was tested locally without any apparent issue.

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by makortel** [comment]
@smuzaffar Since the entire package `FastSimulation/EventProducer` is removed here, should the PR also remove its entry from
https://github.com/cms-sw/cmssw/blob/b4937736ee72171e766aab74f9452b9f7bcb8956/Utilities/ReleaseScripts/scripts/CMSSWReleaseDependency.rules#L32
?

**Comment by sbein** [comment]
+1

**Comment by smuzaffar** [comment]
as no one has sign this PR yet, so go ahead and update CMSSWReleaseDependency.rules ( just drop the `FastSimulation/EventProducer/.*        : geant4.*` line)

**Comment by sbein** [comment]
+1

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
