### PR TITLE
fix on mean s/n calculation

### PR DESCRIPTION
**Pull request by jandrea**
Fix a bug in the mean S/N calculation for the ControlView plots in the SiStrip directory. For 94X release.

### CODE REVIEW

**Comment by jandrea** [comment]
ok. I ran "scram build code-checks", then did git add and git commit.

**Comment by davidlange6** [comment]
Then do git push so that the update goes to github


On 27 Sep 2017, at 07:20, jandrea <notifications@github.com<mailto:notifications@github.com>> wrote:


ok. I ran "scram build code-checks", then did git add and git commit.

**Comment by jandrea** [comment]
@davidlange6 Yes sorry. It should be done now.

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
merge

**Pull request merged**
