### PR TITLE
Converted remaining DQM modules to edm::one::EDAnalyzer

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

This fixes the CMS deprecation warnings in the DQM subsystem.

#### PR validation:

Packages compile without issuing CMS deprecation warnings.

### CODE REVIEW

**Comment by missirol** [comment]
please test

**Comment by missirol** [comment]
+hlt

**Comment by tvami** [comment]
+db
 * quoting Matti, "solution in a suboptimal way though, that does not use DQM base classes and prevents concurrent lumis"
 * but it is a solution, and we can let the beampost team deal with it in a more optimal way later

**Comment by mmusich** [comment]
> quoting Matti, "solution in a suboptimal way though, that does not use DQM base classes and prevents concurrent lumis"

please open an issue about it, otherwise it gets difficult to track it down.

**Comment by emanueleusai** [comment]
+1

**Comment by perrotta** [comment]
+1

**Comment by mmusich** [comment]
> please open an issue about it, otherwise it gets difficult to track it down.

I've done it here: https://github.com/cms-sw/cmssw/issues/39973 (for the record)

**Pull request merged**
