### PR TITLE
HLT menu development for `12_3_X`

### PR DESCRIPTION
**Pull request by missirol**
#### PR description:

Development of HLT menus for `CMSSW_12_3_X`.

Includes the integration of the following JIRA tickets.

  - [CMSHLT-2211](https://its.cern.ch/jira/browse/CMSHLT-2211): Triggers for LLP searches.
  - [CMSHLT-2221](https://its.cern.ch/jira/browse/CMSHLT-2221): New DoubleTau+Jet HLT path for H&#8594;&tau;&tau; and HH&#8594;bb&tau;&tau;.
  - [CMSHLT-2224](https://its.cern.ch/jira/browse/CMSHLT-2224): New VBF+&tau;&tau; HLT path for H&#8594;&tau;&tau;.
  - [CMSHLT-2240](https://its.cern.ch/jira/browse/CMSHLT-2240): Removal of &tau;+MET triggers.
  - [CMSHLT-2241](https://its.cern.ch/jira/browse/CMSHLT-2241): Removal of outdated &gamma;&gamma; HLT path.
  - [CMSHLT-2243](https://its.cern.ch/jira/browse/CMSHLT-2243): Removal of obsolete Run-2 Scouting paths.

#### PR validation:

TSG tests.

#### If this PR is a backport, please specify the original PR and why you need to backport that PR:

N/A

### CODE REVIEW

**Comment by missirol** [comment]
please test

**Comment by missirol** [comment]
Looks like the tests are having trouble starting (from quick a look, it seems to be happening for other PRs as well).

**Comment by missirol** [comment]
+hlt

 - differences in the outputs of Run-3 wfs are consistent with the updates of the HLT `GRun` menu
 - @perrotta @qliphy , unless you have comments on this PR, it would be useful to have it already in the 23:00 IB (to spot any possible issues early, as the `12_3_0_pre6` deadline approaches)

**Comment by perrotta** [comment]
@missirol with this PR this additional warning message shows up in the step3 logs (see the several "workflows with reco comparison differences" in the "Comparison failed" menu, where they all differ for the additional warning message):
```
%MSG-w TriggerObjectStandAlone::packFilterLabels():   PATTriggerObjectStandAloneSlimmer:slimmedPatTrigger 06-Mar-2022 14:09:27 CET  Run: 1 Event: 3
Warning: can't resolve 'hltL3fDimuonL1f0ppL2NV2Chaf10L3NVf0Veto1Prompt' to a label index. idx: 3
%MSG
%MSG-w TriggerObjectStandAlone::packFilterLabels():   PATTriggerObjectStandAloneSlimmer:slimmedPatTrigger 06-Mar-2022 14:09:27 CET  Run: 1 Event: 3
Warning: can't resolve 'hltL3fDimuonL1f0ppL2NV2Chaf10L3NVf0Veto1Prompt' to a label index. idx: 1
%MSG
```
This is probably something you want to cure before merging this.

**Comment by missirol** [comment]
@perrotta , thanks for spotting this. I checked the menu, and I don't think there is anything to change on that side.

What is 'special' about that filter (`hltL3fDimuonL1f0ppL2NV2Chaf10L3NVf0Veto1Prompt`) is that a Path uses it with a negation (the Path uses `~hltL3fDimuonL1f0ppL2NV2Chaf10L3NVf0Veto1Prompt`, prepending with a tilde; can be seen by ctrl+find of [the `GRun` menu in this PR](https://raw.githubusercontent.com/cms-sw/cmssw/6cb4ba7dea7cedb955469404e84e73063f69aa8f/HLTrigger/Configuration/python/HLT_GRun_cff.py)). I can only guess that `PATTriggerObjectStandAloneSlimmer` is complaining about that (the tilde), but I don't know how to fix that (that module is not under HLT, and if a fix is needed it might take me some time).

**Comment by missirol** [comment]
To confirm: I tested wf `11634.0`, reproduced the additional warning, then verified that modifying the GRun menu as follows
```diff
+ [..] + hltL3fDimuonL1f0ppL2NV2Chaf10L3NVf0Veto1Prompt
- [..] + ~hltL3fDimuonL1f0ppL2NV2Chaf10L3NVf0Veto1Prompt
```
makes the warning disappear.
This is consistent with `PATTriggerObjectStandAloneSlimmer` somehow not being able to handle the presence of the tilde operator.

**Comment by Martin-Grunewald** [comment]
Hmm, we used ```~``` filters in HLT menus the past so that type of PAT error message was there already unless filtered out.

**Comment by Martin-Grunewald** [comment]
I can not see the error message in the files you are pointing to. Where are they precisely? Which log file? I looked a at log files:
```
<h3>Default comparison: Workflows with reco comparison differences</h3>


WF # | Differences
-- | --
all_OldVSNew_PyquenZEEMMppRECOin2021wf312p0 | 2
all_OldVSNew_RunJetHT2016EreMINIAODwf136p7611 | 1
all_OldVSNew_RunJetHT2018DreMINIAODULwf136p88811 | 1
all_OldVSNew_TTbar14TeV2021wf11634p0 | 3
all_OldVSNew_TTbar14TeV2021wf11634p7 | 3
all_OldVSNew_TTbar14TeV2021DD4wf11634p911 | 3
all_OldVSNew_TTbar14TeV2021DDDBwf11634p914 | 3
all_OldVSNew_TTbar14TeVPU2021wf11834p0 | 3
all_OldVSNew_TTbar14TeV2023wf12434p0 | 3

Default comparison: Workflows with reco comparison differences
WF #	Differences
[all_OldVSNew_PyquenZEEMMppRECOin2021wf312p0](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_3_X_2022-03-05-1100+a76537/48748/validateJR/all_OldVSNew_PyquenZEEMMppRECOin2021wf312p0)	2
[all_OldVSNew_RunJetHT2016EreMINIAODwf136p7611](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_3_X_2022-03-05-1100+a76537/48748/validateJR/all_OldVSNew_RunJetHT2016EreMINIAODwf136p7611)	1
[all_OldVSNew_RunJetHT2018DreMINIAODULwf136p88811](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_3_X_2022-03-05-1100+a76537/48748/validateJR/all_OldVSNew_RunJetHT2018DreMINIAODULwf136p88811)	1
[all_OldVSNew_TTbar14TeV2021wf11634p0](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_3_X_2022-03-05-1100+a76537/48748/validateJR/all_OldVSNew_TTbar14TeV2021wf11634p0)	3
[all_OldVSNew_TTbar14TeV2021wf11634p7](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_3_X_2022-03-05-1100+a76537/48748/validateJR/all_OldVSNew_TTbar14TeV2021wf11634p7)	3
[all_OldVSNew_TTbar14TeV2021DD4wf11634p911](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_3_X_2022-03-05-1100+a76537/48748/validateJR/all_OldVSNew_TTbar14TeV2021DD4wf11634p911)	3
[all_OldVSNew_TTbar14TeV2021DDDBwf11634p914](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_3_X_2022-03-05-1100+a76537/48748/validateJR/all_OldVSNew_TTbar14TeV2021DDDBwf11634p914)	3
[all_OldVSNew_TTbar14TeVPU2021wf11834p0](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_3_X_2022-03-05-1100+a76537/48748/validateJR/all_OldVSNew_TTbar14TeVPU2021wf11834p0)	3
[all_OldVSNew_TTbar14TeV2023wf12434p0](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_3_X_2022-03-05-1100+a76537/48748/validateJR/all_OldVSNew_TTbar14TeV2023wf12434p0)	3

```
and do not see them
???

**Comment by missirol** [comment]
I also could not see them there. I found one example in "Matrix Test Outputs":
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-a76537/22881/runTheMatrix-results/11634.0_TTbar_14TeV+2021+TTbar_14TeV_TuneCP5_GenSim+Digi+RecoNano+HARVESTNano+ALCA/step3_TTbar_14TeV+2021+TTbar_14TeV_TuneCP5_GenSim+Digi+RecoNano+HARVESTNano+ALCA.log

**Comment by perrotta** [comment]
> I could not see them there either. I found one example in "Matrix Test Outputs": https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-a76537/22881/runTheMatrix-results/11634.0_TTbar_14TeV+2021+TTbar_14TeV_TuneCP5_GenSim+Digi+RecoNano+HARVESTNano+ALCA/step3_TTbar_14TeV+2021+TTbar_14TeV_TuneCP5_GenSim+Digi+RecoNano+HARVESTNano+ALCA.log

Indeed: all workflows listed in https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_3_X_2022-03-05-1100+a76537/48748/validateJR.html for which the report says that there is one extra warning message, the extra warning message is exatly that one, and it can be found in the step3 log.

**Comment by perrotta** [comment]
> Hmm, we used `~` filters in HLT menus the past so that type of PAT error message was there already unless filtered out.

In the current GRun menu there is another negated filter, in `Status_OnCPU`. However that fragment probably enter in a different way (or even not enter at all) in the `PATTriggerObjectStandAloneSlimmer`

**Comment by Martin-Grunewald** [comment]
Thanks! (I mean also in Run2 - 2018 etc.) Anyway, please consider integration despite this.

**Comment by perrotta** [comment]
+1
- Let have this merged in order to ease the further developments of the Run3 HLT menu
- The issue of the wrongly mapped HLT path in PAT must anyhow be fixed: issue #37157 was opened for it

**Comment by missirol** [comment]
Thanks @perrotta .

**Pull request merged**
