### PR TITLE
o2o ECAL(originally from depasse)

### PR DESCRIPTION
**Pull request by franzoni**
fw port of #15483: 

. added handling of passwords via VarParsing
. connection string set to prod db; migration away from CondDBCommon_cfi

### CODE REVIEW

**Comment by franzoni** [comment]
@cmsbuild 
please test

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
@franzoni my understanding of the bot is that the test request needs to appear in the first line of the comment.

**Comment by ggovi** [comment]
+1

**Pull request merged**
