### PR TITLE
Reduce DD exposure to help with furter DD4hep migration

### PR DESCRIPTION
**Pull request by ianna**
#### PR description:

* Replace DDName with string
* Remove DDExpandedView
* Cleanup

@cvuosalo - FYI, let's see if this cleanup can help

#### if this PR is a backport please specify the original PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
@fabiocos - the MTD detector code has a number of hard-coded magic strings and constants. For example, it relies on the XML filenames: mtd.xml and btl.xml. It means that if anyone would decide to rename the files the following code will break: 
https://cmssdt.cern.ch/lxr/source/Geometry/MTDNumberingBuilder/src/CmsMTDStringToEnum.cc#0003

Also, why getting a substring from the filtered view instead of the Geometric det name: https://cmssdt.cern.ch/lxr/source/Geometry/MTDNumberingBuilder/plugins/CmsMTDConstruction.cc#0015

The reason for this PR to fail is here:
https://cmssdt.cern.ch/lxr/source/Geometry/MTDNumberingBuilder/plugins/CmsMTDConstruction.cc#0032

```BModule1Lay``` is an MTD detector, but it looks like the 0 to 10 hard-coded selection causes the comparison to fail 

```
===== Test "testPhase2PixelNtuple" ====
argument 0: testPhase2PixelNtuple
argument 1: /bin/bash
argument 2: SLHCUpgradeSimulations/Geometry/test
argument 3: phase2_digi_reco_pixelntuple.sh
shell is: /bin/bash
Current directory is: /build/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_0_X_2019-08-10-1100
topdir is: /build/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_0_X_2019-08-10-1100
testdir is: /build/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_0_X_2019-08-10-1100/src/SLHCUpgradeSimulations/Geometry/test
tmpdir is: /build/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_0_X_2019-08-10-1100/tmp/slc7_amd64_gcc700
testbin is: /build/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_0_X_2019-08-10-1100/test/slc7_amd64_gcc700
Running script: /build/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_0_X_2019-08-10-1100/src/SLHCUpgradeSimulations/Geometry/test/phase2_digi_reco_pixelntuple.sh
10-Aug-2019 22:54:10 CEST  Initiating request to open file root://eoscms.cern.ch//eos/cms/store/user/cmsbuild/store/relval/CMSSW_10_6_0_patch2/RelValSingleMuPt10/GEN-SIM/106X_upgrade2023_realistic_v3_2023D41noPU-v1/10000/7377ED92-245C-CC4D-9F05-25ABB5522A08.root
10-Aug-2019 22:54:14 CEST  Successfully opened file root://eoscms.cern.ch//eos/cms/store/user/cmsbuild/store/relval/CMSSW_10_6_0_patch2/RelValSingleMuPt10/GEN-SIM/106X_upgrade2023_realistic_v3_2023D41noPU-v1/10000/7377ED92-245C-CC4D-9F05-25ABB5522A08.root
----- Begin Fatal Exception 10-Aug-2019 22:55:46 CEST-----------------------
An exception of category 'MTDConstruction' occurred while
   [0] Processing  stream begin Run run: 1 stream: 0
   [1] Calling method for module PFElecTkProducer/'uncleanedOnlyPfTrackElec'
   [2] Using EventSetup component TransientTrackBuilderESProducer/'' to make data TransientTrackBuilder/'TransientTrackBuilder' in record TransientTrackRecord
   [3] Using EventSetup component GlobalTrackingGeometryESProducer/'' to make data GlobalTrackingGeometry/'' in record GlobalTrackingGeometryRecord
   [4] Using EventSetup component MTDDigiGeometryESModule/'mtdGeometry' to make data MTDGeometry/'' in record MTDDigiGeometryRecord
   [5] Using EventSetup component MTDGeometricTimingDetESModule/'mtdNumberingGeometry' to make data GeometricTimingDet/'' in record IdealGeometryRecord
Exception Message:
woops got: BModule1Lay
----- End Fatal Exception -------------------------------------------------
10-Aug-2019 22:55:46 CEST  Closed file root://eoscms.cern.ch//eos/cms/store/user/cmsbuild/store/relval/CMSSW_10_6_0_patch2/RelValSingleMuPt10/GEN-SIM/106X_upgrade2023_realistic_v3_2023D41noPU-v1/10000/7377ED92-245C-CC4D-9F05-25ABB5522A08.root

=============================================
```
We should discuss how to proceed.

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
+1

@fabiocos - an additional MTD revision and cleanup is needed. I'll leave it to you.

**Comment by cvuosalo** [comment]
I give my +1, too. Thanks, Yana.

**Comment by ianna** [comment]
@kpedro88 - please review

**Comment by fabiocos** [comment]
A quick test running the ideal simulation test code https://github.com/cms-sw/cmssw/blob/master/Geometry/MTDCommonData/test/testMTDinDDD.py shows no difference

**Comment by fabiocos** [comment]
Also https://github.com/cms-sw/cmssw/blob/master/Geometry/MTDGeometryBuilder/test/mtd_cfg.py gives the same results, apart for the lack of printed namespaces (and node address):

```
56,57c56,57
< %MSG-i MTDDigiGeometryAnalyzer:  MTDDigiGeometryAnalyzer:prod  13-Aug-2019 11:51:01 CEST Run: 1 Event: 1
< Geometry node for MTDGeom is  0x7f9e23f49f00
---
> %MSG-i MTDDigiGeometryAnalyzer:  MTDDigiGeometryAnalyzer:prod  13-Aug-2019 11:51:13 CEST Run: 1 Event: 1
> Geometry node for MTDGeom is  0x7f4a80cbaf00
29524c29524
<  Subdetector 18 MTD Det BModule33Layer1NegativeZTimingwafer
---
>  Subdetector 18 MTD Det FieldParameters:BModule33Layer1NegativeZTimingwafer
29527c29527
<  Subdetector 18 MTD Det BModule17Layer1NegativeZTimingwafer
---
>  Subdetector 18 MTD Det FieldParameters:BModule17Layer1NegativeZTimingwafer
29530c29530
<  Subdetector 18 MTD Det BModule1Layer1NegativeZTimingwafer
---
>  Subdetector 18 MTD Det FieldParameters:BModule1Layer1NegativeZTimingwafer
29533c29533
<  Subdetector 18 MTD Det BModule1Layer1PositiveZTimingwafer
---
>  Subdetector 18 MTD Det FieldParameters:BModule1Layer1PositiveZTimingwafer
29536c29536
<  Subdetector 18 MTD Det BModule17Layer1PositiveZTimingwafer
---
>  Subdetector 18 MTD Det FieldParameters:BModule17Layer1PositiveZTimingwafer
29539c29539
<  Subdetector 18 MTD Det BModule33Layer1PositiveZTimingwafer
---
>  Subdetector 18 MTD Det FieldParameters:BModule33Layer1PositiveZTimingwafer
29542c29542
<  Subdetector 19 MTD Det EModule1Disc1Timingwafer
---
>  Subdetector 19 MTD Det FieldParameters:EModule1Disc1Timingwafer
29545c29545
<  Subdetector 19 MTD Det EModule2Disc1Timingwafer
---
>  Subdetector 19 MTD Det FieldParameters:EModule2Disc1Timingwafer
29548c29548
<  Subdetector 19 MTD Det EModule3Disc1Timingwafer
---
>  Subdetector 19 MTD Det FieldParameters:EModule3Disc1Timingwafer
29551c29551
<  Subdetector 19 MTD Det EModule4Disc1Timingwafer
---
>  Subdetector 19 MTD Det FieldParameters:EModule4Disc1Timingwafer
29554c29554
<  Subdetector 19 MTD Det EModule5Disc1Timingwafer
---
>  Subdetector 19 MTD Det FieldParameters:EModule5Disc1Timingwafer
29557c29557
<  Subdetector 19 MTD Det EModule6Disc1Timingwafer
---
>  Subdetector 19 MTD Det FieldParameters:EModule6Disc1Timingwafer
29560c29560
<  Subdetector 19 MTD Det EModule7Disc1Timingwafer
---
>  Subdetector 19 MTD Det FieldParameters:EModule7Disc1Timingwafer
29563c29563
<  Subdetector 19 MTD Det EModule8Disc1Timingwafer
---
>  Subdetector 19 MTD Det FieldParameters:EModule8Disc1Timingwafer
29566c29566
<  Subdetector 19 MTD Det EModule9Disc1Timingwafer
---
>  Subdetector 19 MTD Det FieldParameters:EModule9Disc1Timingwafer
29569c29569
<  Subdetector 19 MTD Det EModule10Disc1Timingwafer
---
>  Subdetector 19 MTD Det FieldParameters:EModule10Disc1Timingwafer
29572c29572
<  Subdetector 19 MTD Det EModule11Disc1Timingwafer
---
>  Subdetector 19 MTD Det FieldParameters:EModule11Disc1Timingwafer
```

**Comment by fabiocos** [comment]
@ianna there is an issue with the MTDTopologyAnalyzer as run in https://github.com/cms-sw/cmssw/blob/master/Geometry/MTDNumberingBuilder/test/mtd_cfg.py , it does not print any more the dump of the DetIds. I am trying to quickly understand it, i see that namespaces are hardcoded, by that is not the only issue.

**Comment by fabiocos** [comment]
@ggovi could you please check? The update in the DB area looks minor and simple to me

**Comment by ianna** [comment]
@fabiocos  - how can I reproduce it?

```
scram b USER_CXXFLAGS="-g\ -D=EDM_ML_DEBUG" 
Trailing \ in regex m/^USER_CXXFLAGS=-g\/ at /cvmfs/cms-ib.cern.ch/week0/share/lcg/SCRAMV1/V2_2_9_pre04-pafccj/src/SCRAM/SCRAM.pm line 159.
```

**Comment by fabiocos** [comment]
@ianna ok, I've understood the issue, another update is needed in order to preserve the analyzer functionality:
```
14:28 cmsdev25 2862> git diff
diff --git a/Geometry/MTDNumberingBuilder/test/MTDTopologyAnalyzer.cc b/Geometry/MTDNumberingBuilder/test/MTDTopologyAnalyzer.cc
index fc7f206df1e..3ab6df84892 100644
--- a/Geometry/MTDNumberingBuilder/test/MTDTopologyAnalyzer.cc
+++ b/Geometry/MTDNumberingBuilder/test/MTDTopologyAnalyzer.cc
@@ -90,14 +90,14 @@ void MTDTopologyAnalyzer::analyze(const edm::Event& iEvent, const edm::EventSetu

     size_t num = fv.geoHistory().size();

-    if (fv.geoHistory()[num - 1].logicalPart().name() == "btl:BarrelTimingLayer") {
+    if (fv.geoHistory()[num - 1].logicalPart().name().name() == "BarrelTimingLayer") {
       isBarrel = true;
       limit = num;
-      ddtop = "btl:BarrelTimingLayer";
-    } else if (fv.geoHistory()[num - 1].logicalPart().name() == "etl:EndcapTimingLayer") {
+      ddtop = "BarrelTimingLayer";
+    } else if (fv.geoHistory()[num - 1].logicalPart().name().name() == "EndcapTimingLayer") {
       isBarrel = false;
       limit = num;
-      ddtop = "etl:EndcapTimingLayer";
+      ddtop = "EndcapTimingLayer";
     }

     if (num <= limit && fv.geoHistory()[num - 1].logicalPart().name().name() != ddtop) {
```

With this update the output of the topology check is preserved. At this point also the analyzers in Geometry/MTDCommonData/test should be better updated, but they are not broken by this PR, so I can take care of this later

**Comment by ianna** [comment]
@fabiocos - thanks, done.

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
@ggovi please comment or sign it

**Comment by fabiocos** [comment]
@ggovi I would like to merge this PR, the DB part looks ok to me, please have a look

**Comment by ianna** [comment]
@ggovi - please, review

**Comment by ggovi** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

@kpedro88 please have a look in case

**Comment by kpedro88** [comment]
+upgrade

**Pull request merged**
