### PR TITLE
Commonality with ROOT6 version for CommonTools/Utils

### PR DESCRIPTION
**Pull request by wmtan**
This pull request is for commonality in the CMSSW code for the package CommonTools/Utils between CMSSW_7_4_ROOT6_X and CMSSW_7_4_X. All the changes in this package in CMSSW_7_4_ROOT6_X that are compatible with ROOT5 are ported back in this PR. The changes may seem extensive, but much of it is white space changes and reformatting.
The CondCore/Utils unit tests and the entire relval matrix pass in 7_4_X with this PR.

### CODE REVIEW

**Comment by wmtan** [comment]
This build error pre-exists in the release and has nothing to do with this PR.

**Comment by wmtan** [comment]
please test

**Comment by ktf** [comment]
@cmsbuild, please test

**Comment by wmtan** [comment]
Those two unit test failures are preexisting in the release, and are not due to this PR.  See:
https://cmssdt.cern.ch/SDT/cgi-bin/showBuildLogs.py/slc6_amd64_gcc491/www/thu/7.5.ROOT5-thu-23/CMSSW_7_5_ROOT5_X_2015-03-26-2300.
Please merge this PR so I can fix the tests.

**Pull request merged**
