### PR TITLE
76x Fireworks: Fix clang error

### PR DESCRIPTION
**Pull request by alja**
This is a cherry pick of a change 8a2f447b7b847bee900fc4886d5d144edf259921 in #10595.

### CODE REVIEW

**Comment by alja** [comment]
+1

**Comment by Dr15Jones** [comment]
please test

**Comment by lgray** [comment]
@davidlange6 can you please merge this one? It is blocking tests in other PRs.

**Comment by davidlange6** [comment]
+1
ok!

**Pull request merged**
