### PR TITLE
fix PU range for highPU

### PR DESCRIPTION
**Pull request by mtosi**
as #16215

### CODE REVIEW

**Comment by VinInn** [comment]
@cmsbuild , please test

**Comment by mtosi** [comment]
sorry, there was a typo (getTH2D instead of getTH2F)
not it is fine and runTheMatrix -l limited worked

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
+1

**Pull request merged**
