### PR TITLE
 Reduced output string on data relvals to avoid exceed length limit

### PR DESCRIPTION
**Pull request by chayanit**
#### PR description:

Due to limit of workflow name (100 characters), we sometimes run into issues of exceed limit and not able to inject some relvals as the workflow name is too long e.g. chayanit_RVCMSSW_10_5_0_pre1_ROOT614RunDisplacedJet2018C__RelVal_**displacedJet**2018C_190207_102532_234. This PR is made in order to reduce labels on data relvals (bold) as they seem redundant. 

#### PR validation:

1. I have tested by injecting a small set of 2018A relvals here https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?campaign=CMSSW_10_6_0_pre3__data2018A_testReducedlabel-1554958645. The relvals are successfully done with the reduced string workflow names and output names.
2. I have also tested with relmon system using "manual" pairing and it works without problem here (https://cms-pdmv.cern.ch/ReleaseMonitoring/Test_Reducedlabel/DataReport/).

### CODE REVIEW

**Comment by kpedro88** [comment]
please test

**Comment by srimanob** [comment]
Could you pleas put PR description, and the way you do the test? Currently you leave it blank.
@chayanit Thanks.

**Comment by prebello** [comment]
@chayanit  thank you. 
I would suggest that you maintain the "nano" in the related wfs (nano_jetHT2018A to nano2018A for instance), the same you did for miniaod case.

**Comment by fabiocos** [comment]
please test

**Comment by prebello** [comment]
+1

**Comment by chayanit** [comment]
> Could you pleas put PR description, and the way you do the test? Currently you leave it blank.
> @chayanit Thanks.

Done.

**Comment by chayanit** [comment]
Can we merge this PR or is there anything still needed to be verified?
Cheers,
Chayanit

**Comment by srimanob** [comment]
@kpedro88 The signature on upgrade is needed, in case you would like to comment. Thx.

**Comment by kpedro88** [comment]
+upgrade

**Comment by kpedro88** [comment]
+1

**Pull request merged**
