### PR TITLE
Geometry Clang Check readability-delete-null-pointer

### PR DESCRIPTION
**Pull request by ianna**
* Geometry part of @davidlange6's https://github.com/cms-sw/cmssw/pull/19662

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
@smuzaffar - it looks like the code checks did not run

**Comment by ianna** [comment]
+1

**Comment by smuzaffar** [comment]
@ianna , it must be around the time when github was down.
Anyway, I have started the tests now

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
@smuzaffar - it looks like the code check runs on all changed files, not just from this PR. For example: RecoTracker/FinalTrackSelectors/plugins/TrackCollectionMerger.cc

**Comment by smuzaffar** [comment]
@Ianna, code-checks build rule uses git diff $CMSSW_VERSION to find out chaged files and in this case as #20207 is merged in master and was picked up for tests that is why it was considered as changed file. Anyway, I have fixed the test to only consider the files changed in PR

**Comment by ianna** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
