### PR TITLE
Validation module about GEM Detector at High Eta region.

### PR DESCRIPTION
**Pull request by geonmo**
#### Features
- Simulation collection : Support simhit occupancy and efficiency plots.
- Digitization collection : Support Strip and pad plots' occupancy and efficiency plots.
- L1 Collection : Support copad's occupancy and efficiency plots
- Reco Collection : Support Reco hits occupancy plots
#### Additional information :
- #8890 is required for this PR to support Copad digi collection. ( #8890 already is included this PR.)
- SLHCUpgradeSimulations/Configuration is fixed to change schedule and configuration to run validation modules.

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by geonmo** [comment]
Hello, 
I removed unused variables without BOOST library's.
Could you test again?

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by geonmo** [comment]
Hello, all.
When this PR will be merged to official?

**Comment by slava77** [comment]
I added https://github.com/cms-sw/cms-bot/pull/463 to resolve the "new-package-pending" issue

**Comment by mulhearn** [comment]
+1

**Comment by geonmo** [comment]
@deguio Hello, Could your check my PR #9070 about GEM Validation modules?

**Comment by deguio** [comment]
ciao @geonmo 
since this is a brand new package I would like to invite you at the next DQM meeting to present:
- the content of the development
- the main monitorables and the structure of the package
- some numbers about nHistograms, nBins, memory...
I will send you an email with the details about the next meeting.
thanks in advance,
F.

**Comment by geonmo** [comment]
@deguio Thanks for your help. However, we need to discuss who will present at DQM meeting. GEM validation meeting will be held on Friday. So, we can prepare a slide after this Friday. Could you invite us after our meeting?

**Comment by deguio** [comment]
ciao,
as discussed yesterday at the DQM meeting [1], there are some improvements to be included in this PR before the merging. they are mostly related to the huge amount of histograms/bins booked.
even if the code is not run in any central sequence for now (to be run on demand), it would be nice to have the 2D maps reduced in number and size.

keeping on hold for now.
thanks in advance,
F.

[1]
https://indico.cern.ch/event/371150/contribution/2/material/slides/0.pdf

**Comment by geonmo** [comment]
Hello, I need to update memory reducing and etc.
I closed PR and re-open after update.

**Pull request closed without merging**
