### PR TITLE
EcalCondObject container iteration fix

### PR DESCRIPTION
**Pull request by bfonta**
Backport from #33573 for the next mid week global run.

#### PR description:

- The ```EcalCondObjectContainer``` class currently contains a ```begin()``` and an ```end()``` functions that return ```const_iterator```s. However, these must not be used to iterate over the container. This is because internally the container is made out of two independent ```std::vectors```, and while the ```begin()``` gives back an iterator to the begin of the first vector, the ```end()``` gives an iterator to the end of the second vector. Up to recently an iteration over the container was only used in ```CalibCalorimetry/EcalTPGTools/plugins/EcalTPGParamBuilder.cc``` to print debug messages and it was protected by counters that only allowed the first 10 iterations, effectively iterating only on the first internal vector. Only recently, with the addition of the ECAL local reconstruction on GPU, iterations over the full container range were attempted (using ```std::copy```) and this resulted in segmentation violations, together with the incorrect usage of ```std::vector::reserve()``` before ```std::copy()```. In order to prevent this issue from happening again we decided that the best way is to remove the ```begin()``` function from the ```EcalCondObjectContainer``` class (a custom iterator approach was considered but deemed too complex for the problem at hand and potentially less efficient). This PR does this and replaces the existing iterations with iterations over the two internal vectors separately.

- The ```EcalTPGParamBuilder``` was modernised to be a one module and use ```esConsumes```.

#### PR validation:

```
cmsRun RecoLocalCalo/EcalRecProducers/test/testEcalRechitProducer_cfg.py
```

### CODE REVIEW

**Comment by b-fontana** [comment]
backport of #33573

**Comment by fwyzard** [comment]
please test

**Comment by cecilecaillol** [comment]
+l1

**Comment by yuanchao** [comment]
+1
* technical; EcalTPGParamBuilder modernised to use esConsumes
* WF matrix tests and unit tests passed
* build warnings are not part of the PR

**Comment by ggovi** [comment]
+1

**Comment by slava77** [comment]
+reconstruction

for https://github.com/cms-sw/cmssw/pull/33574 e20409e 
- code changes related to reco are just in RecoLocalCalo/EcalRecProducers/test/, they look reasonable
- the backport is correct (the same topic branch is used as #33573 )
- jenkins tests pass

**Comment by qliphy** [comment]
+1

**Pull request merged**
