### PR TITLE
Pcc producer phase1 rebase 92 x

### PR DESCRIPTION
**Pull request by capalmer85**
Rebase to CMSSW_9_2_X #18233

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

I'm not really sure why a new PR was necessary if instead #18233 could have been updated.

**Comment by capalmer85** [comment]
@slava77 Sam is not available today to do the rebasing.  It seemed easier for me to do and then be the owner of the PR.

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/18813	84db1c8
- reco parts were not changed since the last signoff by reco on May 8 for the equivalent of this in  https://github.com/cms-sw/cmssw/pull/18233	9d39217
- jenkins tests pass and comparisons show no differences

**Comment by franzoni** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
