### PR TITLE
correctly update boundary box preventing overwriting in case a hit ha…

### PR DESCRIPTION
**Pull request by clelange**
…s x value = 0

This fixes a bug in the HGCal layer clustering: the "box" that was built from the hits that pass the energy thresholds was erroneously reset in case a hit had an x-value of 0. This limited the area used for the clustering, losing whole layer clusters for no reason. It's fixed now using a boolean for each layer. The consequence is that some multiclusters will have more energy than before (and a couple more layer clusters will be built).

This is the back-port of https://github.com/cms-sw/cmssw/pull/20521 to `CMSSW_9_3_X`.

### CODE REVIEW

**Comment by kpedro88** [comment]
@clelange is this needed for the TDR release?

**Comment by clelange** [comment]
@kpedro88 It would be good if this was part of the TDR release, but since the effect does not seem to be too big, it is not a show stopper in case it comes too late.

**Comment by kpedro88** [comment]
it's most likely too late already

**Comment by kpedro88** [comment]
please test

**Comment by kpedro88** [comment]
+1

**Comment by perrotta** [comment]
+1
- Same as #20521 in the master
- Bug fix: small effect on final quantities but it is deserved

**Comment by davidlange6** [comment]
+1

**Pull request merged**
