### PR TITLE
Remove puppi multipliticies from JME nano

### PR DESCRIPTION
**Pull request by ahinzmann**
#### PR description:

Fix issue reported in #28936

#### PR validation:

runTheMatrix -l  25202.01

no backports.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test workflow 25202.01

**Comment by slava77** [comment]
@peruzzim @fgolf 
please check this at somewhat elevated priority 
Thank you.

**Comment by peruzzim** [comment]
only affects the JME custom workflow and JME is ok with it: https://github.com/cms-sw/cmssw/pull/28936#issuecomment-603750679
so I expect that it's ok to merge, will add signature as soon as tests succeed

**Comment by peruzzim** [comment]
+xpog

**Comment by slava77** [comment]
> Reco comparison results: 2 differences found in the comparisons

also, the special JME nano 25202.01 passed OK

**Comment by santocch** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
