### PR TITLE
Backport of UL (2017 and 2018) scale and smearing corrections in nanoAOD photons and electrons (106X)

### PR DESCRIPTION
**Pull request by jainshilpi**
This is just a backport of #31974 - 2017 and 2018 UL scales and smearing in nanoAOD. Updated files are:
(1) nano_cff.py
(2) photon_cff.py
(3) electron_cff.py

@mariadalfonso

### CODE REVIEW

**Comment by mariadalfonso** [comment]
please test

**Comment by mariadalfonso** [comment]
seems that cannot find the 
https://github.com/cms-data/EgammaAnalysis-ElectronTools/pull/9

----- Begin Fatal Exception 02-Nov-2020 16:33:33 CET-----------------------
An exception of category 'FileInPathError' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing module: class=CalibratedPatElectronProducer label='calibratedPatElectronsUL18'
Exception Message:
edm::FileInPath unable to find file EgammaAnalysis/ElectronTools/data/ScalesSmearings/Run2018_29Sep2020_RunFineEtaR9Gain_scales.dat anywhere in the search path.
The search path is defined by: CMSSW_SEARCH_PATH
${CMSSW_SEARCH_PATH} is: /data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_10_6_X_2020-11-02-1100/poison:/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_10_6_X_2020-11-02-1100/src:/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_10_6_X_2020-11-02-1100/external/slc7_amd64_gcc700/data:/cvmfs/cms-ib.cern.ch/week1/slc7_amd64_gcc700/cms/cmssw-patch/CMSSW_10_6_X_2020-11-02-1100/poison:/cvmfs/cms-ib.cern.ch/week1/slc7_amd64_gcc700/cms/cmssw-patch/CMSSW_10_6_X_2020-11-02-1100/src:/cvmfs/cms-ib.cern.ch/week1/slc7_amd64_gcc700/cms/cmssw-patch/CMSSW_10_6_X_2020-11-02-1100/external/slc7_amd64_gcc700/data
Current directory is: /data/cmsbld/jenkins/workspace/ib-run-pr-tests/runTheMatrix-results/10824.0_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2018_GenSimFull+DigiFull_2018+RecoFull_2018+HARVESTFull_2018+ALCAFull_2018+NanoFull_2018

**Comment by silviodonato** [comment]
please test with cms-data/EgammaAnalysis-ElectronTools#9

**Comment by santocch** [comment]
+1

**Comment by mariadalfonso** [comment]
+xpog
changes inline with master

**Comment by qliphy** [comment]
+1

**Pull request merged**
