### PR TITLE
Remove some configuration files using nonexistent standard sequences

### PR DESCRIPTION
**Pull request by wmtan**
I discovered that there are a large number of python config files that cannot possibly be run because they use configuration files in Configurations/StandardSequences that were moved or removed more than three years ago, and in many cases, more than four years ago.  I am working on a generator feature that requires modifying a lot of config files, so it will make life much easier if these obsolete config files that cannot possibly be used are removed from the release.
Note 1:  This PR removes about 5400 lines of unusable code from the release!
Note 2: This PR should not be confused with #10030 (already merged), which removed a different set of obsolete config files.
Note 3: The original version of this PR mistakenly removed 17 additional files, that, while they did use obsolete sequences, the obsolete sequence was removed only three months ago. So this PR no longer deletes those 17 files.  Thanks to Slava for catching this.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by lveldere** [comment]
+1

**Comment by deguio** [comment]
+1

**Comment by slava77** [comment]
I'd like to keep RecoParticleFlow/Configuration/test/RecoToDisplay_*
I have a record of these being used about 2 years ago (I used it myself less than 3 years ago).
The functionality in these files was also brought up several times recently.

**Comment by wmtan** [comment]
I am closing this PR temporarily.  One of the obsolete configuration files that I thought was removed 3 years ago was in fact removed only 3 months ago in 7_5_X, and is, in fact, still present in 7_4_X and prior releases.  Thanks to Slava for catching this. I will reopen this PR when I modify it to remove only those configuration files that really use files made obsolete > 3 years ago.

**Comment by lveldere** [comment]
+1

**Comment by deguio** [comment]
+1

**Comment by wmtan** [comment]
These relval errors are not caused by this PR.  A simple glance at the most recent IB for which there are relval results, CMSSW_7_6_X_2015-07-12-1100, shows that these errors are already present in the base.

**Comment by cvuosalo** [comment]
@cmsbuild please test
Try test again -- maybe we'll get a better IB

**Comment by wmtan** [comment]
@cmsbuild  There were only three relvals that failed (looking in the link provided), and all three failed due to DAS errors.  The other 13 relvals all passed.  The DAS failures are not due to this PR.

**Comment by cvuosalo** [comment]
@cmsbuild please test
Try again to see if DAS errors can be avoided this time.
I have also run matrix tests and will use them for review if the Jenkins test don't work.

**Comment by cvuosalo** [comment]
+1

For #10116 d1db48df4bc9e5762bb5848f5c4487ce5cf75f78

Deletion of obsolete, unused configuration files. There should be no change in run-time behavior.

Jenkins [tests](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-10116/8687/summary.html) against baseline CMSSW_7_6_X_2015-07-14-1100 show no significant differences, as expected. Matrix tests against the same baseline also show no differences.

**Comment by civanch** [comment]
+1

**Pull request merged**
