### PR TITLE
Changed DQM configuration parameters for modified Single lepton cross-triggers

### PR DESCRIPTION
**Pull request by manuelfs**
We are changing the isolation cone to R=0.2 for the SUSY Single lepton cross-triggers, and one module has changed name, so we needed to change the cff file.

Also, the single lepton triggers that we used as a reference have changed thresholds, so we changed those parameters accordingly.

### CODE REVIEW

**Comment by degano** [comment]
please test

**Comment by deguio** [comment]
ciao @manuelfs 
could you submit this PR to 75 first? we want to have things tested there before merging.
thanks,
F.

**Comment by manuelfs** [comment]
Ciao
Should I create a new PR based on CMSSW_7_5_X, or is there a different way?
Thanks.

**Comment by deguio** [comment]
new PR based on 75x as you say.
thanks,
F.

**Comment by manuelfs** [comment]
Thank you @deguio.

I made a new PR at #8560 based on 75X

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
