### PR TITLE
Run4-hgx260 Bug fix to HGCal relevant mode for geometries beyond V12 geometry

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Bug fix to HGCal relevant mode for geometries beyond V12 geometry

#### PR validation:

Tested using runTheMatrix workflows

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by kpedro88** [comment]
@bsunanda there are many changes in phase 2 workflow comparisons. Are these expected? Can you clarify the nature of the bug? Does this impact HLT TDR production?

**Comment by bsunanda** [comment]
There was a bug in the declaration of valid cell which was present for all corner centered wafers - This will affect all scenario's since V11. I do not know how much the production is done. Should we backport the correction?

**Comment by kpedro88** [comment]
@bsunanda can you quantify the impact of the bug? How does it affect physics?

**Comment by cvuosalo** [comment]
+1

**Comment by bsunanda** [comment]
@kpedro88 This will falsely declare some of the hits at the borders to be invalid. So if decisions are taken in the bulk of the detector this has little effect. B

**Comment by bsunanda** [comment]
@kpedro88 Could you approve this PR? Also let me know if any back porting is needed for the bug fix and if so, to which release 11_1 or 11_0?

**Comment by kpedro88** [comment]
@cseez @rovere @fwyzard @trtomei FYI, this is a bug fix to the HGCal geometry used in the HLT TDR, which affects the list of valid cells at the detector boundaries. The impact on physics should be minimal, so I propose we do not backport it to 11_1_X (since the sample production is already in advanced stage, and consistency is desirable). But please let me know if you have a different perspective on this.

**Comment by kpedro88** [comment]
+upgrade

**Comment by kpedro88** [comment]
For future reference, the changes to HGC RecHits are minor:
all_OldVSNew_TTbar14TeV2026D49wf23234p0c_log10HGCRecHitsSorted_HGCalRecHit_HGCEERecHits_RECO_obj_obj_energy
all_OldVSNew_TTbar14TeV2026D49wf23234p0c_log10HGCRecHitsSorted_HGCalRecHit_HGCHEFRecHits_RECO_obj_obj_energy
all_OldVSNew_TTbar14TeV2026D49wf23234p0c_log10HGCRecHitsSorted_HGCalRecHit_HGCHEBRecHits_RECO_obj_obj_energy

One can also check e.g. the layer cluster eta and phi values:
all_OldVSNew_TTbar14TeV2026D49wf23234p0c_recoCaloClusters_hgcalLayerClusters__RECO_obj_eta
all_OldVSNew_TTbar14TeV2026D49wf23234p0c_recoCaloClusters_hgcalLayerClusters__RECO_obj_phi

**Comment by trtomei** [comment]
Does this affect both SIM and RECO geometry? If RECO only, are there mitigations we can apply at HLT level?
Given the level of differences (very small), I suppose it would be okay to do it to not backport it. Still, would be nice to have the aforementioned mitigations.

**Comment by silviodonato** [comment]
+1

**Comment by rovere** [comment]
Dear all, sorry to jump in late. I'm a little confused and maybe someone could help solve my problems.
Aren't the HLT TDR sample using D49 HGCAL geometry that, internally, use the V11 version? This PR mentions explicitly that the bug affects version beyond V12. Could someone clarify and, in case, edit this PR so that we are consistent?

**Comment by kpedro88** [comment]
HGCal v12 is in the C11 geometry, but indeed, I think it should say "including and beyond v12".

**Comment by bsunanda** [comment]
The issue is for all geometries which have corner centering setups which is true for all versions since (including and beyond) C11
________________________________

**Comment by kpedro88** [comment]
Ah, but indeed, D49 uses C9, which has HGCal v11. @bsunanda please clarify

**Comment by bsunanda** [comment]
Sorry V11 already had corner centering - so it had issues as well
________________________________

**Comment by kpedro88** [comment]
@bsunanda can you update the PR title/description for future reference?

**Pull request merged**
