### PR TITLE
backport of 19618

### PR DESCRIPTION
**Pull request by VinInn**
title says all
to be integrated asap. possibly in production on T0 as High Lumi data taking will resume

### CODE REVIEW

**Comment by VinInn** [comment]
@cmsbuild please test

**Comment by VinInn** [comment]
@gpetruc @veszpv @boudoul @venturia FYI

**Comment by dmitrijus** [comment]
backport of #19618

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
