### PR TITLE
Combination of #23120 and #23012 for testing purposes

### PR DESCRIPTION
**Pull request by ahinzmann**
See #23120 and #23012

### CODE REVIEW

**Comment by slava77** [comment]
I think that this PR is not necessary.
There is a way to run tests with multiple PRs included.
However, there is no way to compare to a baseline+somePR.

**Comment by ahinzmann** [comment]
would it be possible to run the comparisons for this PR to see that the issue of missing jets in HF in #23012 is solved by combining both?

**Comment by perrotta** [comment]
please test

**Comment by slava77** [comment]
@ahinzmann 
this PR is now out of sync with #23120

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by perrotta** [comment]
please test

**Pull request closed without merging**
