### PR TITLE
Run3-sim34 Update the codes which make more meaningful comparisons between G4 and GV

### PR DESCRIPTION
**Pull request by bsunanda**
### PR description:

Update the codes which make more meaningful comparisons between G4 and GV

#### PR validation:

Tested in the context where Geant4 results are compared with GeantV results

#### if this PR is a backport please specify the original PR:

No back porting is needed. The code is kept for a futuristic use if we take a GeantV like approach in future.

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by fabiocos** [comment]
@bsunanda besides the macro update, you make a number of adjustment to the use of unit of measurements in CaloSteppingAction, keeping CLHEP but changing their use (from the Birk constants to the input parameters). Although this is essentially a standalone test class, I assume you have verified the result are the same. For my understanding what is the reason for this change?

**Comment by bsunanda** [comment]
@fabiocos Geant4 and GeantV come with totally different set of units. We need to isolate the use of units in the specific code where Geant4 class is used. In case of Birk's law application the basic constants supplied as parameters require step size in cm, density in g/cc -> so I changed them in appropriate place. For Light collection efficiency or other geometry parameters the internal unit is in mm and for energy deposit the unit is in MeV till it is changed at the time of storage. This way I could match the units in Geant4 and GeantV. My latest comparisons are much more positive - most likely I can show that in the next simulation meeting

**Comment by fabiocos** [comment]
@bsunanda thanks for the clarification, this PR will be integrated in next IB

**Comment by fabiocos** [comment]
+1

**Pull request merged**
