### PR TITLE
update the list of path monitored in the muon HLT DQM 

### PR DESCRIPTION
**Pull request by HuguesBrun**
addition of 4 more paths

### CODE REVIEW

**Comment by degano** [comment]
@cmsbuild please test

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
would like to check the tests before approving.
@HuguesBrun how many histograms does this add?
thanks,
F.

**Comment by davidlange6** [comment]
@nclopezo , @degano - seems this PR needs its tests run by hand

**Comment by nclopezo** [comment]
Hi David, I started them manually.

**Comment by HuguesBrun** [comment]
Hello, @deguio, 
I noticed that I need to update a bit the way the muon DQM code is parsing the filters due to the fact we switched recently to the PF isolation.
Would you mind if I update this PR or do you prefer I submit an other one for that ? (I am testing the changes right now but lxplus is superslow this morning...) 
thank you !

**Comment by HuguesBrun** [comment]
Hello again, 
I just updated the PR in order to handle the new HLT filters introduced by the use on PF isolation on isolated muon path. 

I checked the size increase of the HLT/Muons directory, the result is here:

folder HLT/Muons | histograms | bins |Empty bins | Empty/Total  | bins per histogram | MB | kB per histogram 
------------- | -------------  | -------------  | -------------  | -------------  | -------------  | -------------  | -------------
before  | 2728 | 757248 | 124507 | 0.164 | 278 | 2.95 | 1.11
after       |  3600  | 778468 | 142803 | 0.183 | 216 | 3.03 | 0.862

**Comment by deguio** [comment]
+1
@HuguesBrun please make sure that the old/not interesting HLT paths are removed.
thanks,
F.

**Pull request merged**
