### PR TITLE
Prep work for the Run-3 GEM-CSC integrated local trigger

### PR DESCRIPTION
**Pull request by dildick**
#### PR description:

Prep work for the Run-3 GEM-CSC integrated local trigger. This goes together with PR https://github.com/cms-data/L1Trigger-CSCTriggerPrimitives/pull/6.
* The lookup tables were organized into CCLUT, GEMCSC and ME11.
   * CCLUT: comparator code LUT algorithm that provides better position and bending resolution
   * GEMCSC: GEM-CSC integrated trigger
   * ME11: ME11 specific LUTs for ALCTs crossing with CLCTs
* `CSCComparatorCodeLUT` renamed to `CSCLUTReader` so we can reuse it for the GEM-CSC trigger
* Helper classes `CSCALCTCrossCLCT`, `GEMInternalCluster` and `LCTQualityAssignment` were added.
   * `CSCALCTCrossCLCT`: class that checks if an ALCT crosses with a CLCT. Not always the case for ME1/1. A lengthy description was added when this class would be used
   * `GEMInternalCluster`: transient container for `GEMPadDigiCluster` and a coincidence of two `GEMPadDigiCluster`s. We will shortly be doing the GEM-CSC matching based on `GEMPadDigiCluster` instead of `GEMPadDigi` and `GEMCoPadDigi`, like in the firmware. The emulator would no longer decluster into single pads. The `GEMInternalCluster` will eliminate much of the code duplication that exists now, and nearly all of the horrible function templating.
   * `LCTQualityAssignment`: class that holds the definitions for LCT quality in Run-2 and Run-3. Documented in DN-20-016. Idea is to unload this code from the TMB classes.

#### PR validation:

Tested with WF 11634.0. There should be no changes to any of the workflows.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by cecilecaillol** [comment]
please test

**Comment by dildick** [comment]
@cecilecaillol These failures should be go away by restarting the tests. I think a new IB was made that should take care of changes in cms-data.

**Comment by cecilecaillol** [comment]
please test

**Comment by cecilecaillol** [comment]
+l1

**Comment by qliphy** [comment]
test parameters

- pull_requests = cms-data/L1Trigger-CSCTriggerPrimitives#6

**Comment by qliphy** [comment]
please test

**Comment by dildick** [comment]
@qliphy Thanks a lot, in principle the external is not yet needed, as the Run-3 CSC trigger algorithm is not switched on yet. But in a few weeks to months this is certainly the plan.

**Comment by qliphy** [comment]
> @qliphy Thanks a lot, in principle the external is not yet needed, as the Run-3 CSC trigger algorithm is not switched on yet. But in a few weeks to months this is certainly the plan.

Thanks @dildick  for the information!  So we can move forward this PR first.

**Comment by qliphy** [comment]
+1

**Pull request merged**
