### PR TITLE
bsunanda:Run2-gem09    Upload corrected GE21 geometry xml files

### PR DESCRIPTION
**Pull request by bsunanda**
Two alternate geometries for GE21 to be evaluated

### CODE REVIEW

**Comment by ianna** [comment]
@cmsbuild please test

**Comment by ianna** [comment]
+1

**Comment by davidlange6** [comment]
@bsunanda - lets remove at least obsolete version of the gem geometry as a trade for getting yet another new one

**Comment by bsunanda** [comment]
Update the scenario and remove 2 obsolete versions
________________________________

**Comment by ianna** [comment]
@cmsbuild please test

**Comment by ianna** [comment]
@bsunanda - has v7 geometry been agreed to be a default one?

**Comment by ianna** [comment]
+1

**Comment by bsunanda** [comment]
I believe so. This is what I got from Teruki's mail
________________________________

**Comment by calabria** [comment]
@ianna , yes v7 is meant to be the default

**Comment by davidlange6** [comment]
+1

**Pull request merged**
