### PR TITLE
PackedCandidates.. comment out parts of unit test that are not expected to work

### PR DESCRIPTION
**Pull request by davidlange6**
(given how constructor is meant to pack and throw away the original p4 information)

### CODE REVIEW

**Comment by Dr15Jones** [comment]
-1

**Comment by Dr15Jones** [comment]
Looks like this was pushed to the wrong release.

**Comment by davidlange6** [comment]
whoops- yes..

**Comment by slava77** [comment]
-1
this should be closed, apparently.

**Comment by ggovi** [comment]
-1
(close)

**Pull request closed without merging**
