### PR TITLE
Initialize all member data in PropagateToMuon

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

Initialized all member data. UBSAN reported cases where data was being read before it was set.

#### PR validation:

Code compiles.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
@makortel FYI

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
please test

**Comment by tvami** [comment]
@cmsbuild , please test
 * altho the issue is not connected

**Comment by tvami** [comment]
+1
 * technical

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
