### PR TITLE
DD4Hep Migration: Parse CMS XML Files

### PR DESCRIPTION
**Pull request by ianna**
First step towards integrating a proof of principle example:
this test parses CMS XML files for run 1 Tracker.

To run the test:
```
cmsRun DetectorDescription/DDCMS/python/dump.py
```

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by smuzaffar** [comment]
@ianna , you need to wait for first 10.1.X IB to test this.

**Comment by ianna** [comment]
@smuzaffar - ok, thanks.

**Comment by ianna** [comment]
Replaced by https://github.com/cms-sw/cmssw/pull/22194

**Pull request closed without merging**
