### PR TITLE
Remove hard-coded dphi value

### PR DESCRIPTION
**Pull request by hyunyong**
#### PR description:

Remove the hard-coded dPhi value for the GEM strip topology.
When we made this PR, the GTs didn't include the dPhi values, so we put the dPhi value temporarily.
Since the GTs updated,  we can remove the temporary dPhi value from the GEM geometry builder.

It needs to back-port to 11_3_X

#### PR validation:

The GEM geometry analyzer validated this PR.

### CODE REVIEW

**Comment by srimanob** [comment]
Please test

**Comment by srimanob** [comment]
@hyunyong 
Why do you need it for 11_2? Do you have the production or anything special there that need this in the production version of CMSSW?

**Comment by civanch** [comment]
problems cannot be triggered by this PR.

**Comment by hyunyong** [comment]
> @hyunyong
> Why do you need it for 11_2? Do you have the production or anything special there that need this in the production version of CMSSW?

11_2 GTs include the 

> @hyunyong
> Why do you need it for 11_2? Do you have the production or anything special there that need this in the production version of CMSSW?

I intended 11_3. I fixed the PR description.
Sorry for the confusion.

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by srimanob** [comment]
Please test

**Comment by hyunyong** [comment]
> This PR is creating an error:
> cmsRun: /data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/5e4cb43dbbbc358c519406d08818dca4/opt/cmssw/slc7_amd64_gcc900/cms/cmssw/CMSSW_12_0_X_2021-04-29-1100/src/Geometry/CommonTopologies/src/GEMStripTopology.cc:13: GEMStripTopology::GEMStripTopology(int, float, float, float): Assertion `angularWidth_ != 0' failed.
> 
> That is one reason why the PR tests are failing.
> @hyunyong Please investigate and fix this error.

@cvuosalo The problem is "113X_upgrade2018_realistic_v5" GT has "GEMRECO_Geometry_10YV4" GEM geometry tag.
"GEMRECO_Geometry_10YV4" doesn't have the new dPhi value.
GEM has participated in the slice test during Run2, so 2017 and 2018 geometries have GEM.

**Comment by cvuosalo** [comment]
@hyunyong If I understand correctly, the GEM reco geometry has changed from Run 2 to Run 3. In the Run 2 GEM reco geometry, there is no `dPhi` parameter, but it does exist for Run 3.
I think the code has to be written to support both cases. Before this line is executed:
```
 float dphi = *(shapeStart + 6);
```
a check needs to be made to make sure there is actually a value at that location. Otherwise, the default 0.17715 has to be used.

**Comment by hyunyong** [comment]
> @hyunyong If I understand correctly, the GEM reco geometry has changed from Run 2 to Run 3. In the Run 2 GEM reco geometry, there is no `dPhi` parameter, but it does exist for Run 3.
> I think the code has to be written to support both cases. Before this line is executed:
> 
> ```
>  float dphi = *(shapeStart + 6);
> ```
> 
> a check needs to be made to make sure there is actually a value at that location. Otherwise, the default 0.17715 has to be used.

@cvuosalo We didn't change the geometry but we tried to improve the strip topology. 

> @hyunyong If I understand correctly, the GEM reco geometry has changed from Run 2 to Run 3. In the Run 2 GEM reco geometry, there is no `dPhi` parameter, but it does exist for Run 3.
> I think the code has to be written to support both cases. Before this line is executed:
> 
> ```
>  float dphi = *(shapeStart + 6);
> ```
> 
> a check needs to be made to make sure there is actually a value at that location. Otherwise, the default 0.17715 has to be used.

@cvuosalo GEM geometry is not changed during Run2 and Run3, but just we try to improve the strip topology. 
If we can update the 2017 and 2018 Tags, it would be good.
However, if it is not possible, I can add some lines to check the parameter.
```
  std::vector<double>::const_iterator shapeEnd = rgeo.shapeEnd(gid);
  float check = *(shapeEnd);
  if (check == dphi) dphi = 0.177151;
```
Let me know your opinions.

**Comment by cvuosalo** [comment]
@hyunyong Legacy Global Tags for 2017 and 2018 should not be changed. The GEM code needs to be changed to be run correctly whether the `dPhi` parameter exists or not.
It seems to me a check would look like:
```
std::vector<double>::const_iterator shapeEnd = rgeo.shapeEnd(gid);
float dPhi = 0.17715;
if (shapeEnd - shapeStart >= 6)  // I'm not sure whether 6 is the correct type
  dphi = *(shapeStart + 6);
```

**Comment by hyunyong** [comment]
> @hyunyong Legacy Global Tags for 2017 and 2018 should not be changed. The GEM code needs to be changed to be run correctly whether the `dPhi` parameter exists or not.
> It seems to me a check would look like:
> 
> ```
> std::vector<double>::const_iterator shapeEnd = rgeo.shapeEnd(gid);
> float dPhi = 0.17715;
> if (shapeEnd - shapeStart >= 6)  // I'm not sure whether 6 is the correct type
>   dphi = *(shapeStart + 6);
> ```

@cvuosalo Yes, I understood. I changed the dphi like this and tested it.
2017 and 2018 geometries use 0.17715, but 2021 uses the dphi value from DB.
```
float dphi = (shapeStart + 6 < rgeo.shapeEnd(gid)) ? *(shapeStart + 6) : 0.17715;
```

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

**Pull request merged**
