### PR TITLE
Move ParticleFlow to a separate category in RelMon

### PR DESCRIPTION
**Pull request by justinasr**
#### PR description:

Move ParticleFlow from Miscellanea to it's own separate row in category table of RelMon report summary since the PF has joined the release validation.

#### PR validation:

Ran ValidationMatrix.py and compared results to output before changes.

#### If this PR is a backport please specify the original PR and why you need to backport that PR:

Not a backport.

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by chayanit** [comment]
assign PdmV

**Comment by jfernan2** [comment]
+1

**Comment by chayanit** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
