### PR TITLE
HLT menu development for `14_0_X` (8/N)

### PR DESCRIPTION
**Pull request by mmusich**
backport of https://github.com/cms-sw/cmssw/pull/45160

#### PR description:

Development of HLT menus for CMSSW_14_0_X.
   * This is the PR for the 14.0.X branch (this is the release cycle currently used for Run-3 HLT-menu development).
   * This version of the GRun HLT menu corresponds to the list of updates to the **"V1.3"** menu for the 2024 pp data-taking period.

This update includes the integration of the following JIRA tickets:
- [CMSHLT-3189](https://its.cern.ch/jira/browse/CMSHLT-3189) : [AlCa,ECAL,GEM,RPC] Replace L1uGT digis with RAW data in ALCAP0, ALCAPHISYM and RPCMON streams
- [CMSHLT-3195](https://its.cern.ch/jira/browse/CMSHLT-3195) : [CSC,GEM,RPC]Add GEM Trigger Information to RPCMON output
- [CMSHLT-3197](https://its.cern.ch/jira/browse/CMSHLT-3197) : [MUO] New BDT Model in Muon Doublet-Recovery
- [CMSHLT-3210](https://its.cern.ch/jira/browse/CMSHLT-3210) : [TSG] Add HLT_Physics_v to online special menus
- [CMSHLT-3211](https://its.cern.ch/jira/browse/CMSHLT-3211) : [SUS] Control trigger prescale tuning MSSM Hbb
- [CMSHLT-3212](https://its.cern.ch/jira/browse/CMSHLT-3212) : [TSG,Scouting] Adding 2024 upt L1 seeds to the DoubleMuon Scouting path
- [CMSHLT-3213](https://its.cern.ch/jira/browse/CMSHLT-3213) : [EGM,EXO,SMP] Add `DST_PFScouting_SinglePhotonEB_v1` to the HLT menu
- [CMSHLT-3215](https://its.cern.ch/jira/browse/CMSHLT-3215) : [TAU,HIG] Remove HPS sequence from PNet ETau paths
- [CMSHLT-3219](https://its.cern.ch/jira/browse/CMSHLT-3219) : [BPH] single muon low pT paths for lumi-decay
- [CMSHLT-3225](https://its.cern.ch/jira/browse/CMSHLT-3225) : [TSG] Remove PS columns `"1p8E34+X"`
- [CMSHLT-3226](https://its.cern.ch/jira/browse/CMSHLT-3226) : [TSG] Remove PS column `"2p0E34_NoMuShower"`
- [CMSHLT-3227](https://its.cern.ch/jira/browse/CMSHLT-3227) : [PF,HIon] Update `HIDQMGPUvsCPU` EventContent with hltParticleFlowClusterHCAL* products
- [CMSHLT-3228](https://its.cern.ch/jira/browse/CMSHLT-3228) : [TSG] Set PS=1 for HLT-Scouting in `"2p0E34_OnlyMuons"`
- [CMSHLT-3229](https://its.cern.ch/jira/browse/CMSHLT-3229) : [TSG] Remove PS columns `"2p0E34+ZeroBias"` and `"2p0E34+HLTPhysics"` from the offline menu
- [CMSHLT-3233](https://its.cern.ch/jira/browse/CMSHLT-3233) : [TSG] Backport of some online updates from last PPS menus
- [CMSHLT-3234](https://its.cern.ch/jira/browse/CMSHLT-3234) : [TSG,DQM] Set PS=30 for `Dataset_OnlineMonitor`
- [CMSHLT-3235](https://its.cern.ch/jira/browse/CMSHLT-3235) : [TSG] Reassign `hltFEDSelectorTCDS` from `HLTriggerFinalPath` to those paths in streams actually saving its product

In addition, the following changes are included:
   * bc1aeea7be0831cb18cc038893325e30cf4a810e : fix bugs in `hltPathOwners.json`
   * a67fd2dceb61bc4e90dd8b4aa5f099e86127020a : update the list of HLT path owners: menu 2024 V1.3
   * e5c104d2acde03468fbeb8966727a4025e63553c : Introduce 2024v1.3 frozen menu and remove 2024v1.2

#### PR validation:

TSG Integration tests

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

backport of https://github.com/cms-sw/cmssw/pull/45160 to the 2024 production cycle (`CMSSW_14_0_X`)

### CODE REVIEW

**Comment by mmusich** [comment]
enable gpu

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by mmusich** [comment]
hold

**Comment by mmusich** [comment]
unhold

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
+hlt

**Comment by mmusich** [comment]
@cms-sw/orp-l2 can you please merge this?

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
