### PR TITLE
Deal with cases in which file is a nullptr in DQMRootSource.cc

### PR DESCRIPTION
**Pull request by perrotta**
#### PR description:

As hinted by the static analyzer, see also https://github.com/cms-sw/cmssw/pull/39852#issuecomment-1294603711, there is a logic error in the code of DQMRootSource.cc ([this line](https://github.com/cms-sw/cmssw/compare/master...perrotta:dealWithMissingFiles?expand=1#diff-065460daed6dfa882871be4c6dcc28e8c6fc38c622382b3cbdaaf3be78a0d7ebL556)) when `file = nullptr`

If I understand correctly the logic behind, this PR should be the fix for it

I write a PR instead of a github issue because in this case it looks faster to me. But please @Dr15Jones and/or @cms-sw/dqm-l2  comment here if you think that the fix is correct, or if you suggest something else instead

#### PR validation:

It builds.
If the fix is correct, there should be no differences in outputs

### CODE REVIEW

**Comment by perrotta** [comment]
@cmsbuild please test

**Comment by Dr15Jones** [comment]
It seems to me that `file ==nullptr` and `(!isGoodFile && m_skipBadFiles)` being false (without already throwing an exception) can only happen if `fNames` is empty. If that is the case, then one should also change line 488 to
```TFile* file = nullptr;```

**Comment by perrotta** [comment]
please test

**Comment by emanueleusai** [comment]
+1

- new logic is correct

**Comment by perrotta** [comment]
+1

**Pull request merged**
