### PR TITLE
Phase2-hgx311A Small fix to the conversion code and rmoval of unused parameters in v16 geometry definition of HGCal

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Small fix to the conversion code and rmoval of unused parameters in v16 geometry definition of HGCal

#### PR validation:

Use  runTheMatrix test workflows

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by perrotta** [comment]
@bsunanda thank you for having taken care of some of the the post-merge comments that were posted for PR #37734

You considered here https://github.com/cms-sw/cmssw/pull/37734#discussion_r867223429

Please consider including also https://github.com/cms-sw/cmssw/pull/37734#discussion_r867224451 and https://github.com/cms-sw/cmssw/pull/37734#discussion_r867201862

@makortel FYI

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by bsunanda** [comment]
@srimanob Please sign this

**Comment by srimanob** [comment]
+Upgrade

Fixes on V16 HGCal. It would be better if @bsunanda confirms no change is expected from the fix of conversion code.

**Comment by perrotta** [comment]
>
> Fixes on V16 HGCal. It would be better if @bsunanda confirms no change is expected from the fix of conversion code.

The actual fix is in https://github.com/cms-sw/cmssw/pull/37851/files#diff-373efabb0e6542374dd09c69608b24df2188a7beed945f9be373dbf432082e11R642
Waiting for @bsunanda to comment what above before merging

**Comment by bsunanda** [comment]
The changes made to v16 xml file are essentially removing some unused parameters. They will not affect v16 results. The changes made to the conversion code are required for the v17 geoetry description. So it is safe to take the changes as it is

**Comment by perrotta** [comment]
+1
- See https://github.com/cms-sw/cmssw/pull/37851#issuecomment-1120822682

**Pull request merged**
