### PR TITLE
[HLT] [CLANG] Fix warnings reported by llvm16 in CLANG IBs

### PR DESCRIPTION
**Pull request by aandvalenzuela**
Fixes set but unused warnings from clang-16 in CLANG IBs

### CODE REVIEW

**Comment by aandvalenzuela** [comment]
please test

**Comment by missirol** [comment]
@aandvalenzuela , the test results report "Clang Warnings to fix". Could you please have a look ?
```
RecoTauTag/HLTProducers/src/L2TauPixelTrackMatch.cc:82:14: warning: unused variable 'n0' [-Wunused-variable]
```

**Comment by aandvalenzuela** [comment]
please test

**Comment by missirol** [comment]
+hlt

**Comment by perrotta** [comment]
+1

**Pull request merged**
