### PR TITLE
OMTF emulator corresponding to the 2024 OMTF firmware [14_0_X]

### PR DESCRIPTION
**Pull request by mbluj**
#### PR description:

Changes to the OMTF algorithm which were introduced in the firmware for 2024: mainly changes related to the triggering on the displaced muons. With this update, the OMTF data-to-emulator agreement in the online DQM should be at the level of 99.5%. The firmware was deployed in the CMS on 19th March 2024.
This PR is backport of #43687 & #44893 and requires cms-data/L1Trigger-L1TMuon#26

FYI, @kbunkow 

#### PR validation:

The version was checked by running the online DQM on the data from a collision run taken in April 2024 during testing the original PR to 14_1_X.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport of #44893 on top of #43687 for 2024 operations. Requires cms-data/L1Trigger-L1TMuon#26 (added to cms-distr for 14_1, but not for 14_0).

### CODE REVIEW

**Comment by aloeliger** [comment]
Backport of https://github.com/cms-sw/cmssw/pull/44893

**Comment by aloeliger** [comment]
please test

**Comment by mbluj** [comment]
@aloeliger it should be tested with https://github.com/cms-data/L1Trigger-L1TMuon/pull/26. This is already merged to cms-data, but not propagated to cms-distr of 14_0 (to be done).
We are working in parallel to store this information in CondDB and make it available via GT, but it is beyond scope of this PR.

**Comment by aloeliger** [comment]
@mbluj Right, ok. I don't what the procedure is on data-file backports, but I could figure it out if you aren't already working on it. Let me know if you need assistance with that.

**Comment by mbluj** [comment]
> @mbluj Right, ok. I don't what the procedure is on data-file backports, but I could figure it out if you aren't already working on it. Let me know if you need assistance with that.

As far as I remember in my PRs it has been always performed by release managers. Anyway, it requires that in https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_14_0_X/master/data/cmsswdata.txt L1Trigger-L1TMuon is updated to V01-10-00. I will check if I can do PR for it.

**Comment by mbluj** [comment]
Backport of update of OMTF data in cms-dist for 14_0 in https://github.com/cms-sw/cmsdist/pull/9177.

**Comment by smuzaffar** [comment]
test parameters:
- pull_request = cms-sw/cmsdist#9177

**Comment by smuzaffar** [comment]
please test

**Comment by aloeliger** [comment]
+l1

**Pull request merged**
