### PR TITLE
Delete old scripts accessing geometry with prior-run2 GT in CalibMuon/CSCCalibration

### PR DESCRIPTION
**Pull request by yuanchao**
#### PR description:

Following the up the migration of Geometry_cff to GeometryDB_cff (https://github.com/cms-sw/cmssw/pull/35278), proper GlobalTag needs to be set in advance. We take the chance to clean up deprecated AlCa/DB script in CSCCalibration.

#### PR validation:

Remove deprecated scripts: testNewCalibConstants_global_cfg.py and testNewCalibConstants_global_cfg.py

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Not a back port and no back port expected.

### CODE REVIEW

**Comment by tvami** [comment]
type csc,performance-improvement

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
FYI @ptcox 
if you disagree with the cleaning, please provide a working config (and make it a unit test), thanks!

**Comment by tvami** [comment]
assign csc-dpg-l2

**Comment by tvami** [comment]
+alca
 * I'll sign from the AlCa side and let the CSC DPG have the final word

**Comment by tvami** [comment]
hi @ptcox can you pease comment on this PR? thanks!

**Comment by ptcox** [comment]
I already did comment on this: 
"I object very strongly to deletion of old scripts for no reason. In what way is it useful to anybody to remove scripts with superseded content? Even a broken config file is useful to somebody in the future arriving with no knowledge of what was done in the past.
Isn't that one point of a software repository? It is not as if one can arrive years later, when one need to accomplish whatever the old script used to do, and somehow magically retrieve it from deletion: how would one even know it had ever existed?"

They were used for producing CSCValidation output in simulation and in real data. They do not make sense as a 'unit test'. 

However, if you really think it is necessary to delete them I am not going to fight about it. I just don't think it's a good idea. It will likely be somebody else's problem to recreate equivalent configs at some point in the future.

**Comment by tvami** [comment]
Hi Tim,
I didnt (and still dont) see your comment on this earlier.
Many subsystems have scripts that really should be deleted. I understand yours is not that case. So let's fix these configs.

> They were used for producing CSCValidation output in simulation and in real data. 

Is there a version of the script that's still used?

> They do not make sense as a 'unit test'.

I dont understand why not? `CSCValidation.cc` is part of this package, and this config file runs it, i.e. it's testing if `CSCValidation.cc` still works. 

Further questions: can we simply run this on Run-3 data? If yes, do you need a special skim? For MC, what input would make sense?
Thanks

**Comment by perrotta** [comment]
+1
- No need to relaunch the tests: just two outdated test scripts are removed from the release

**Comment by perrotta** [comment]
+1
- No need to relaunch the tests: just two outdated test scripts are removed from the release

**Comment by ptcox** [comment]
Hi Tamas,

I just do not have the time to invest in this now. Sorry.

Tim
________________________________

**Comment by ptcox** [comment]
I object very strongly to deletion of old scripts for no reason. In what 
way is it useful to anybody to remove scripts with superseded content? 
Even a broken config file is useful to somebody in the future arriving 
with no knowledge of what was done in the past.
Isn't that one point of a software repository? It is not as if one can 
arrive years later, when one need to accomplish whatever the old script 
used to do, and somehow magically retrieve it from deletion: how would 
one even know it had ever existed?

And I do not have time to invest in this now.

Tim

**Pull request merged**
