### PR TITLE
Phase2 Tracker Geometries: add 20% and 50% extra material (93X version)

### PR DESCRIPTION
**Pull request by mdhildreth**
Add 20% and 50% increased material to Phase 2 tracker for L1 Track Trigger Stress Test.

### CODE REVIEW

**Comment by kpedro88** [comment]
Will this actually be used in 93X? We are trying to move new productions to 102X.

**Comment by mdhildreth** [comment]
please test

**Comment by mdhildreth** [comment]
please test

**Comment by fabiocos** [comment]
@mdhildreth @kpedro88 there is a conflict here between this PR and #23126 we need to agree how to solve it

**Comment by fabiocos** [comment]
@mdhildreth @kpedro88 obviously referring to the master version #23203

**Comment by ianna** [comment]
+1

**Comment by prebello** [comment]
+1

tests-approved

**Comment by fabiocos** [comment]
@ianna @mdhildreth @kpedro88 is this PR still needed? BTW, I think that the scenarios here are not in sync with the scenarios in master, is this a situation that already happened? I think it could be confusing...

**Comment by fabiocos** [comment]
@mdhildreth if this is not needed better to close it I would say, in case we can resurrect it

**Comment by fabiocos** [comment]
@mdhildreth based on your statement in the ORP spreadsheet, this PR is no more needed. In case we will resurrect it

**Pull request closed without merging**
