### PR TITLE
Remove SiStripDetId from CalibTracker/StripESProducers

### PR DESCRIPTION
**Pull request by nickmccoll**
Removed the SiStripDetId sub detector classes and replaced them with TrackerTopology.

### CODE REVIEW

**Comment by nickmccoll** [comment]
Are these errors expected? I don't know how the could be caused by the changes and see similar errors in other PRs.

**Comment by nickmccoll** [comment]
Not to bug anyone, but is there something I need to do have this PR go through review? Thanks!

**Comment by diguida** [comment]
@nickmccoll looking into it

**Comment by mmusich** [comment]
+1

**Comment by ggovi** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
