### PR TITLE
Use correct beamspot for 2016 MC + update MC tracker alignment scenario for 2016 pre-VFP era [10_6_X]

### PR DESCRIPTION
**Pull request by christopheralanwest**
#### PR description:

This PR is a backport of PR #28624, which changes the default beamspot for 2016 scenarios and updates the tracker APEs for MC of the 2016 pre-VFP era. Commits 5d50378 and 
e514a31 are cherry-picked from the PR to master. The 10_6_X branch requires an additional two changes of the beamspot scenario, in commit 662b68c. Finally, the global tags are updated in commit 5ea966a. The changes to the GTs can be understood by comparing the diffs with respect to the previous 10_6_X autoCond GTs or by comparison with those in master.

_**Comparison with previous 10_6_X GT**_

**2016 design MC**
Updated to use ideal beamspot
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_mcRun2_design_v6/106X_mcRun2_design_v7
**2016 preVFP pp collision MC**
Updated to use 25ns beamspot rather than 50ns beamspot. Update to tracker APEs
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_mcRun2_asymptotic_preVFP_v1/106X_mcRun2_asymptotic_preVFP_v3
**2016 pp collision MC**
Updated to use 25ns beamspot rather than 50ns beamspot. 
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_mcRun2_asymptotic_v8/106X_mcRun2_asymptotic_v9
**2016 cosmic MC**
Updated to use 25ns beamspot rather than 50ns beamspot. Not relevant but change is made to minimize unnecessary differences between cosmic and pp collision GTs
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_mcRun2cosmics_startup_deco_v5/106X_mcRun2cosmics_startup_deco_v6

_**Comparison between 10_6_X and master**_
**2016 design MC**
Only differences are in tau tags added in 11_0_X and obsolete pixel tags
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/110X_mcRun2_design_v5/106X_mcRun2_design_v7
**2016 preVFP pp collision MC**
Only differences are in tau tags added in 11_0_X, addition to AlCaReco bits added in 11_1_X, and obsolete pixel tags
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/110X_mcRun2_asymptotic_preVFP_v4/106X_mcRun2_asymptotic_preVFP_v3
**2016 pp collision MC**
Only differences are in tau tags added in 11_0_X, addition to AlCaReco bits added in 11_1_X, and obsolete pixel tags
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/110X_mcRun2_asymptotic_v7/106X_mcRun2_asymptotic_v9
**2016 cosmic MC**
Only differences is addition to AlCaReco bits added in 11_1_X
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/110X_mcRun2cosmics_startup_deco_v6/106X_mcRun2cosmics_startup_deco_v6

#### PR validation:

Please see description of PR #28624 for details of physics validation. In addition, a technical test was performed: `runTheMatrix.py -l limited,7.22 --ibeos`

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

This is a backport of PR #28624. The backport corresponds to the configuration that is already in use for the ultra-legacy reprocessing.

### CODE REVIEW

**Comment by christopheralanwest** [comment]
backport #28624

**Comment by christopheralanwest** [comment]
please test

**Comment by christopheralanwest** [comment]
+1

- backport consistent with changes in master
- changes in DQM and reco quantities PR integration tests only present in 2016 MC, as expected

**Comment by civanch** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade

**Comment by santocch** [comment]
+1

**Comment by silviodonato** [comment]
Do you have any objection @chayanit @pgunnell @zhenhu ?

**Comment by chayanit** [comment]
+1
sorry I thought I have already signed

**Comment by silviodonato** [comment]
+1

**Pull request merged**
