### PR TITLE
use the correct associator for tracker validation

### PR DESCRIPTION
**Pull request by abbiendi**
Wrong configuration parameter, using an associator created with Validation/RecoMuon/python/associators_cfi.py  instead of the correct one located in SimTracker/TrackAssociatorProducers.
This creates an unnecessary dependence between muon and tracker validation.
The fix makes no change to the actually used parameters in the running workflows, hence no change at all in the results. However it is necessary for a custom workflow of the muon validation, which otherwise gets broken by this.

@davidcarbonis @boudoul

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by abbiendi** [comment]
@dmitrijus, @jfernan2   
please, can you review this PR and hopefully sign it ?
It is urgent, we need it to enter in pre4 for benchmarking the New vs Old Muon validation in pre4. Without this the customization of the muon validation crashes cmsRun.

**Comment by abbiendi** [comment]
@vazzolini, @kmaeshima, @dmitrijus, @jfernan2, @vanbesien 
whoever is in charge: please, can you review this PR and hopefully sign it ?
It is a very simple change, but urgent, we need it to enter in pre4 for benchmarking the New vs Old Muon validation in pre4. Without this the customization of the muon validation crashes cmsRun.

**Comment by jfernan2** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
