### PR TITLE
Re-enable trigger cache.

### PR DESCRIPTION
**Pull request by bbockelm**
This re-enables the trigger cache, which provides a bit more than an order-magnitude speedup for `edmCopyPickEvent` over high-latency.

This additionally remove errant copy/pasted code blocks and guarantees that an assert cannot be hit.

@osschar

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
Any ideas why this may have caused problems when we first switched to multi-threading?

**Comment by bbockelm** [comment]
The only possible case was when the switchover entry would be set to 0 (everything else was excluded by prior `if`-cases); we simply changed things to guarantee that the entry was set to `> 0`.

**Comment by Dr15Jones** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
