### PR TITLE
Enhancements to GBRForest/Tree for converting TMVA classifiers (75X)

### PR DESCRIPTION
**Pull request by lgray**
Backport of #10275 

@bendavid

### CODE REVIEW

**Comment by diguida** [comment]
please test

**Comment by diguida** [comment]
+1
Interface changes in `CondFormats/EgammaObjects/interface/GBRForest.h` and `CondFormats/EgammaObjects/interface/GBRTree.h` do not modify the serializable data members.
These are a back-port of changes proposed as in #10275 for 76X.

**Comment by ggovi** [comment]
+1

**Comment by lgray** [comment]
@ggovi Could you also +1 the back and forward ports of this PR? Thanks!

**Comment by davidlange6** [comment]
+1

**Pull request merged**
