### PR TITLE
Modified vbf filter

### PR DESCRIPTION
**Pull request by gmandorl**
VBFGenJetFilter.cc has been extended.
Possible requirements on the invariant mass of the two pt-leading genJets.
The considered genJets can also be asked to have a minimum DeltaR from the event charged prompt leptons.

### CODE REVIEW

**Comment by gmandorl** [comment]
I make a mistake. The package
AnalyzerMiniAOD/GenJetAnalyzer
wasn't ment to be updated in cmssw.

Do I create a new PR with just 
GeneratorInterface/GenFilters
?

**Comment by perrozzi** [comment]
you can use
`git rm --cached -r AnalyzerMiniAOD/GenJetAnalyzer`
and commit to remove it from git but keep it local

**Comment by gmandorl** [comment]
I removed the package AnalyzerMiniAOD/GenJetAnalyzer

**Comment by perrozzi** [comment]
please test

**Comment by perrozzi** [comment]
+1

**Comment by perrozzi** [comment]
backport of https://github.com/cms-sw/cmssw/pull/20394

**Comment by perrozzi** [comment]
please test

**Comment by perrozzi** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
