### PR TITLE
Replace Candidate GT by named GT in conddb script unit tests and update offline Run-3 data GT

### PR DESCRIPTION
**Pull request by malbouis**
#### PR description:

This PR has two updates:

- Replace a Candidate GT by a named GT in the conddb unit tests in view of AlCaDB policy of deleting Candidates GTs older than 6 months.
- Update the Run-3 data offline GT to be used for the Pilot Beam ReReco with ECAL PF Cluster corrections as request here: https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/4562.html
 
The difference in the run-3 data offline GT wrt the previous version is shown below. the only differences are in the 16 updated multi-IOV tags that contain related to ECAL PC Cluster corrections:
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/122X_dataRun3_v2/122X_dataRun3_v3

#### PR validation:

For the conddb unit tests: `scram b runtests_test_conddb`

For the offline Run-3 data GT: `runTheMatrix.py -l 136.897,136.899,138.3,139.001,139.002,139.003,139.004 -j16`

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

This is not a backport but it will be backported to 122X, 121X and 120X.

### CODE REVIEW

**Comment by malbouis** [comment]
test parameters:

- workflows=136.897,136.899,138.3,139.001,139.002,139.003,139.004

**Comment by malbouis** [comment]
please test

**Comment by tvami** [comment]
+1
 * modified unit tests pass
 * new GT is just rather here for documentation

**Comment by qliphy** [comment]
+1

**Comment by mmusich** [comment]
@malbouis @tvami,
if you really intend to pursue the deletion of candidate GlobalTags older than 6 months, please notice that in addition to PR  #36409 you'll also need backports of commit https://github.com/cms-sw/cmssw/pull/36402/commits/8ac21353617bb8f3efb495dad4d823e730e96735 all the way down to 12.0.X as the unit test `test_conddb` was introduced first there:

https://github.com/cms-sw/cmssw/blob/9326bb057cdceb9e6b4bd9cd289148323cb34d21/CondCore/Utilities/test/test_conddb.sh#L38

https://github.com/cms-sw/cmssw/blob/400ccef06488c90b2555705b2aaa414c2f2f4295/CondCore/Utilities/test/test_conddb.sh#L38

**Comment by malbouis** [comment]
@mmusich Thanks for pointing that out! We will do the backports to 121X and 120X as well.

**Pull request merged**
