### PR TITLE
Update ExoticaDQM_cfi.py

### PR DESCRIPTION
**Pull request by aescalante**
Modified list of valid HLT trigger path names due to a typo in one of the trigger names.

### CODE REVIEW

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Comment by perrotta** [comment]
Since data taking (and corresponding validation) is actually done with 74X, does it exist (or do you foresee) a 74X version of this pull request?

**Comment by aescalante** [comment]
Yes, the same pull request was done also for 74x and 75x 

https://github.com/cms-sw/cmssw/pull/10104 and https://github.com/cms-sw/cmssw/pull/10251

**Comment by perrotta** [comment]
Thank you Alberto: I missed the 74X pull request.
A.


Alberto Escalante del Valle <notifications@github.com> ha scritto:

**Pull request merged**
