### PR TITLE
HLT DQM for 9.3.x - part 3

### PR DESCRIPTION
**Pull request by fwyzard**
Follow up to #19713.

Merge the following HLT DQM pull requests (in this order):
  - #19250 from gomber:Wprime_DQMPromptMonitoring
  - #19290 from parbol:DQM-SingleElectron-Jet

### CODE REVIEW

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by davidlange6** [comment]
+1
(will use the 1100 IB to count histo bins)

**Comment by fwyzard** [comment]
Thanks. For more HLT DQM, do I open a new PR to or keep merging things here ?

**Comment by davidlange6** [comment]
merge

**Comment by davidlange6** [comment]
i meant to merge this.

**Comment by davidlange6** [comment]
hi @fwyzard - it looks like this PR has introduced a bunch of seg faults - could you find a quick fix

eg

https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc7_amd64_gcc630/CMSSW_9_3_X_2017-07-25-1100/pyRelValMatrixLogs/run/136.784_RunMET2017B+RunMET2017B+HLTDR2_2017+RECODR2_2017reHLT_skimMET_Prompt+HARVEST2017/step3_RunMET2017B+RunMET2017B+HLTDR2_2017+RECODR2_2017reHLT_skimMET_Prompt+HARVEST2017.log

----- Begin Fatal Exception 25-Jul-2017 14:24:05 CEST-----------------------
An exception of category 'FatalRootError' occurred while
   [0] Processing  stream end Run run: 297227 stream: 2
   [1] Calling method for module TopMonitor/'susyEle17CaloIdMJet30_ele'
   Additional Info:
      [a] Fatal Root Error: @SUB=Merge
Cannot merge histograms - limits are inconsistent:
 first: elePtEta_1_denominator (9, 0.000000, 400.000000), second: elePtEta_1_denominator (10, 0.000000, 400.000000)

**Comment by fwyzard** [comment]
will look - just to confirm, these are exceptions, not segfaults we are talkinig about, right ?

**Comment by fwyzard** [comment]
I suspect I understand the problem - it looks like multiple modules are booking the same histogram; I've asked @parbol to have a loot in #19290.

**Comment by fwyzard** [comment]
If my guess is correct, #19912 should fix these errors.

**Comment by fwyzard** [comment]
OK, step3 of 136.784 runs fine with the fix.

**Comment by Martin-Grunewald** [comment]
@fwyzard 
TSG test shows this error:
```
%MSG
----- Begin Fatal Exception 26-Jul-2017 08:07:55 CEST-----------------------
An exception of category 'StdException' occurred while
   [0] Processing  Event run: 1 lumi: 3 event: 103 stream: 1
   [1] Running path 'dqmofflineOnPAT_step'
   [2] Calling method for module TopMonitor/'WprimeEle115'
Exception Message:
A std::exception was thrown.
no method or data member named "deltaEtaSuperClusterAtVtx" found for type "reco::GsfElectron"
----- End Fatal Exception -------------------------------------------------
```

**Comment by fwyzard** [comment]
hi @Martin-Grunewald ,
how do I reproduce it ?

And by the way, what does the exception mean ?

**Comment by davidlange6** [comment]
Yes, also seen in IBs - presumably a problem with StringCutParser setup (perhaps a sign that this code had never selected an event in the developers tests...)

**Comment by Martin-Grunewald** [comment]
Eg, this IB relval test
https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc6_amd64_gcc630/CMSSW_9_3_X_2017-07-25-1100/pyRelValMatrixLogs/run/136.79_RunMuOnia2017B+RunMuOnia2017B+HLTDR2_2017+RECODR2_2017reHLT_skimMuOnia_Prompt+HARVEST2017/step3_RunMuOnia2017B+RunMuOnia2017B+HLTDR2_2017+RECODR2_2017reHLT_skimMuOnia_Prompt+HARVEST2017.log

**Comment by davidlange6** [comment]
https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc7_amd64_gcc630/CMSSW_9_3_X_2017-07-25-2300/pyRelValMatrixLogs/run/136.785_RunMuonEG2017B+RunMuonEG2017B+HLTDR2_2017+RECODR2_2017reHLT_skimMuonEG_Prompt+HARVEST2017/step3_RunMuonEG2017B+RunMuonEG2017B+HLTDR2_2017+RECODR2_2017reHLT_skimMuonEG_Prompt+HARVEST2017.log

here is one way ( 136.785 step 3)

**Comment by fwyzard** [comment]
hi @davidlange6 , do you want the fix on top of #19916 or stand-alone ?

**Comment by davidlange6** [comment]
Stand alone please

**Comment by fwyzard** [comment]
#19918

**Comment by Martin-Grunewald** [comment]
Using #19918 I get the next error:
```
Begin processing the 5th record. Run 1, Event 107, LumiSection 3 at 26-Jul-2017 10:09:21.725 CEST
----- Begin Fatal Exception 26-Jul-2017 10:09:21 CEST-----------------------
An exception of category 'StdException' occurred while
   [0] Processing  Event run: 1 lumi: 3 event: 103 stream: 0
   [1] Running path 'dqmofflineOnPAT_step'
   [2] Calling method for module TopMonitor/'WprimeEle115'
Exception Message:
A std::exception was thrown.
no method or data member named "passConversionVeto" found for type "reco::GsfElectron"
----- End Fatal Exception -------------------------------------------------
```

**Comment by fwyzard** [comment]
Sigh... on which workflow?
I didn't get any errors on 136.784 and 136.785 ...

**Comment by Martin-Grunewald** [comment]
Our TSG workflow on the V2.1 menu - within ```HLTrigger/Configuration/test```:
```
./runAll.csh GRun
```

**Comment by fwyzard** [comment]
hi again,
I've run all the 136.* workflows without seeing the issue reported by Martin - and the reason could be that I did not hit an interesting event.

However,  for my tests I've used #19916 (actually #19917) on top of the other changes. Is it possible that the problem has already been fixed by the commits there ?

Martin, can you try with the latest IB + #19917 ?

**Comment by Martin-Grunewald** [comment]
@fwyzard 
Unfortunatly the error persists:
```
CMSSW_9_3_X_2017-07-26-2300/src/HLTrigger/Configuration/test/[129]$ git branch
  CMSSW_9_3_X
  cms-sw/refs/pull/19884/head
  cms-sw/refs/pull/19917/head
* from-CMSSW_9_3_X_2017-07-26-2300
```
to reproduce: make a developer area:
```
cd src
git cms-addpkg HLTrigger/Configuration
scram b
rehash
cd HLTrigger/Configuration/test/

cp /afs/cern.ch/user/g/gruen/public/RelVal_DigiL1RawHLT_GRun_MC.py .
cp cp /afs/cern.ch/user/g/gruen/public/RelVal_RECO_GRun_MC.py .

cmsRun RelVal_DigiL1RawHLT_GRun_MC.py >& RelVal_DigiL1RawHLT_GRun_MC.log
echo $?

cmsRun RelVal_RECO_GRun_MC.py >& RelVal_RECO_GRun_MC.log
echo$?
```
The first cmsRun takes a GEN-SIM file and produces the file needed for the second cmsRun which shows the crash.

**Comment by fwyzard** [comment]
Your test machine is bigger than mine... 

In my second attempt, the job was killed after the first few events by the kernel because the machine ran out of memory.

In the first attempt the whole machine died...

I'm trying again with a singe stream to reduce the memory usage.

**Comment by fwyzard** [comment]
OK, with a single thread/stream I can reproduce the error.

**Pull request merged**
