### PR TITLE
Switching off reconstruction of so called "NullTaus"

### PR DESCRIPTION
**Pull request by mbluj**
Hi All,

it is a copy of #17706 rebased to the main branch (91X). Description of the original RP cited below for reference. The #17706 will be closed in a minute.

Best,
Michał

Hi all,

this is a simple configuration switch to remove the so called "null-taus" from the tau reconstruction. Null taus are jets seeding tau candidates, which actually do not fulfill any good tau reconstruction criterion. In the past these had been kept in the reconstruction for debugging purposes, since it allows a 1:1 correspondence of reconstructed tau candidates with seeding jets. In the meantime this should be switched to False when running in standard reconstruction. For more details refer to @mbluj.

NB:
we have split this change off from #17620 (90X) for clarity reasons. See also discussion in the conversation there.

Cheers,
Roger

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@davidlange6 
why was this merged without a reco signature?

**Comment by davidlange6** [comment]
err- thats a good question. I think I clicked on the wrong PR. Shall i unmerge it?

**Comment by slava77** [comment]
@davidlange6 
I'll check it today and will let you know if it should be reverted.

**Comment by slava77** [comment]
@mbluj @roger-wolf 
in quite a few workflow comparisons there are differences in DQM like this (from wf 136.731, SinglePh2016B data)
wf136 731_pftau_loosemu3_sumpt

Are these plots missing a basic tau quality preselection or did this update remove more than necessary?

**Comment by mbluj** [comment]
Yes, this plot is done without checking if a tau candidate passes basic quality criteria as presence of leading track. Differences are expected: it should be less tau candidates with low values of isolation sum.

**Comment by slava77** [comment]
On 3/14/17 9:38 AM, mbluj wrote:
> Yes, this plot is done without checking if a tau candidate passes basic
> quality criteria as presence of leading track. Differences are expected:
> it should be less tau candidates with low values of isolation sum.

something to put on the list to fix in DQM at some point?

**Comment by mbluj** [comment]
> > Yes, this plot is done without checking if a tau candidate passes basic
> > quality criteria as presence of leading track. Differences are expected:
> > it should be less tau candidates with low values of isolation sum.
>
> something to put on the list to fix in DQM at some point?

Yes, right we should think on fixing DQM to not look on very poor taus.
But, such poor taus will not be produced when this PR is merged, so DQM
will not see them.

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/17767	b09eb1b
- post-merge "+1"
- changes are as described, affecting tau reco configuration
- jenkins tests pass and comparisons with baseline show differences in tau objects
- local test with modified validate.C shows that differences in recoPFTaus_hpsPFTauProducer go away after a requirement that leadPFChargedHadrCandsignedSipt_ is non-NaN, the differences in discriminants go away after requiring the discriminant values (non-binary cases) are non-zero
- either jenkins or local tests show no differences in miniAOD tau objects, confirming that after basic selections there are no changes as expected.

**Pull request merged**
