### PR TITLE
Adjusts SimHits histogram binning and adds Additional Noise plots

### PR DESCRIPTION
**Pull request by kencall**
SimHits histograms filled by Validation/HcalHits/src/HcalSimHitStudy.cc and Validation/HcalHits/src/SimHitsValidationHcal.cc have some binning adjusts.

Additional noise plots have been added.

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by kencall** [comment]
I have checked DQM files generated in testing [1]. The histograms have the desired changes.

[1] https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-11493/8424/runTheMatrix-results/25.0_TTbar+TTbar+DIGI+RECOAlCaCalo+HARVEST+ALCATT/DQM_V0001_R000191226__Global__CMSSW_X_Y_Z__RECO.root

**Comment by hatakeyamak** [comment]
Since we haven't heard much on thread, I just wanted to write this to get people's attention on this PR and I wanted to make sure this will be included in 7_6_X.

**Comment by deguio** [comment]
@vkhristenko

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
