### PR TITLE
Adding dqmHarvestingFakeHLT for HI

### PR DESCRIPTION
**Pull request by jfernan2**
#### PR description:

This PR adds dqmHarvestingFakeHLT  for HI to fix Harvesting in wf140.53
Error in logs recently spotted
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-e133d3/4085/runTheMatrix-results/140.53_RunHI2011+RunHI2011+RECOHID11+HARVESTDHI/step3_RunHI2011+RunHI2011+RECOHID11+HARVESTDHI.log
Only affecting Run1 HI workflows
Run2 HI workflows run pp harvesting

#### PR validation:

Tested with  runTheMatrix.py -l 140.53 -i all --ibeos

#### if this PR is a backport please specify the original PR:

Not needed

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+1
Changes in wf140.53 as expected due to missing DQM harvesting until now

**Comment by fabiocos** [comment]
+operations

the update of StandardSequences is coherent with the purpose of the PR

**Comment by fabiocos** [comment]
+1

**Pull request merged**
