### PR TITLE
HLT development and PRef menu updates (92X)

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
HLT development and PRef menu updates (92X)
Basd on CMSSW_9_2_14_patch1

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
backport pf #21253

**Comment by Martin-Grunewald** [comment]
backport of #21253

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
