### PR TITLE
Use explicit acelerator types in alpaka tests

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Update the `HeterogeneousTest` alpaka tests to use the explicit accelerator types in alpaka device code:
  - move all alpaka device code to the `ALPAKA_ACCELERATOR_NAMESPACE` namespace;
  - use the explicit accelerator types, like `Acc1D` or `Acc2D`, instead of the generic `TAcc` template argument.

#### PR validation:

The `HeterogeneousTest` unit tests pass:
```
Creating test log file logs/el8_amd64_gcc12/testing.log
Pass    3s ... HeterogeneousTest/AlpakaDevice/testAlpakaDeviceAdditionCudaAsync
Skip    0s ... HeterogeneousTest/AlpakaDevice/testAlpakaDeviceAdditionROCmAsync (Failed to run rocmIsEnabled)
Pass    0s ... HeterogeneousTest/AlpakaDevice/testAlpakaDeviceAdditionSerialSync
Pass   10s ... HeterogeneousTest/AlpakaDevice/testAlpakaTestDeviceAdditionModule
Pass    3s ... HeterogeneousTest/AlpakaKernel/testAlpakaDeviceAdditionKernelCudaAsync
Skip    0s ... HeterogeneousTest/AlpakaKernel/testAlpakaDeviceAdditionKernelROCmAsync (Failed to run rocmIsEnabled)
Pass    0s ... HeterogeneousTest/AlpakaKernel/testAlpakaDeviceAdditionKernelSerialSync
Pass    7s ... HeterogeneousTest/AlpakaKernel/testAlpakaTestKernelAdditionModule
Pass    3s ... HeterogeneousTest/AlpakaOpaque/testAlpakaDeviceAdditionOpaqueCudaAsync
Skip    0s ... HeterogeneousTest/AlpakaOpaque/testAlpakaDeviceAdditionOpaqueROCmAsync (Failed to run rocmIsEnabled)
Pass    0s ... HeterogeneousTest/AlpakaOpaque/testAlpakaDeviceAdditionOpaqueSerialSync
Pass    7s ... HeterogeneousTest/AlpakaOpaque/testAlpakaTestAdditionModules
Pass    7s ... HeterogeneousTest/AlpakaOpaque/testAlpakaTestOpaqueAdditionModule
Pass    3s ... HeterogeneousTest/AlpakaWrapper/testAlpakaDeviceAdditionWrapperCudaAsync
Skip    0s ... HeterogeneousTest/AlpakaWrapper/testAlpakaDeviceAdditionWrapperROCmAsync (Failed to run rocmIsEnabled)
Pass    0s ... HeterogeneousTest/AlpakaWrapper/testAlpakaDeviceAdditionWrapperSerialSync
Pass    7s ... HeterogeneousTest/AlpakaWrapper/testAlpakaTestWrapperAdditionModule
>> Test sequence completed for CMSSW CMSSW_14_1_X_2024-04-08-2300
```

### CODE REVIEW

**Comment by fwyzard** [comment]
enable gpu

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
> I found compilation error when building:

Interesting, this
```bash
/cvmfs/cms-ci.cern.ch/week0/cms-sw/cmssw/44676/38717/install.sh
cd CMSSW_14_1_X_2024-04-09-1100/
cmsenv
cd src/
scram b clean
scram b -j
```
works on a machine with a local CUDA installation, but fails on lxplus8.

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
OK, let's try one step at a time... only the change to the namespaces and templates, _not_ the change to the code structure.

**Comment by fwyzard** [comment]
OK then, let's keep it like this for now.

@makortel what do you think ?
do you prefer the original version, or this one ?

**Comment by makortel** [comment]
I have a slight preference for this PR (for the reasons outlined in https://github.com/cms-sw/cmssw/issues/44625).

The functions currently defined in headers should be marked as `inline` (or `ALPAKA_FN_INLINE`?) now that they are not implicitly `inline` anymore.

**Comment by fwyzard** [comment]
> I have a slight preference for this PR (for the reasons outlined in #44625).

OK.
 
> The functions currently defined in headers should be marked as `inline` (or `ALPAKA_FN_INLINE`?) now that they are not implicitly `inline` anymore.

I'll mark them as `inline`.

`ALPAKA_FN_INLINE` is an attempt to be a cross-platform "force inline" for device code, I don't think we should use it much in general.

**Comment by fwyzard** [comment]
please test

**Comment by makortel** [comment]
> I'll mark them as `inline`.
> 
> `ALPAKA_FN_INLINE` is an attempt at a cross-platform "force inline" for device code, I don't think we should use it much in general.

Sounds good.

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
