### PR TITLE
Conversions from low pt gsf tracks mini aod 105x

### PR DESCRIPTION
**Pull request by nancymarinelli**

### CODE REVIEW

**Comment by perrotta** [comment]
Please fix conflicts and remove the extra commits which ended up in this PR

**Comment by nancymarinelli** [comment]
Sorry I need advice.
I had done git cm-addpkg PhysicsTools/PatAlgos on top of the most recent 
IB for 105X. I made the two smalle changes and that is wat I committed. 
I would not know how to go about it. And if I force a new commit, I 
would do the same exact thing.



On 06/03/19 17:44, perrotta wrote:
> Please fix conflicts and remove the extra commits which ended up in this PR
>

-- 
________________________________________
Nancy Marinelli
Research Associate Professor
University of Notre Dame, IN, US
CERN, Bdg 40/3-A01, 1211 Geneva
SWITZERLAND
Phone +41-22-76-70809
fax +41-22-76-78940

**Comment by boudoul** [comment]
ciao @nancymarinelli , we are now in 10_6_X so a most recent IB should be found in 10_6_X not in 10_5_X.
Hope that helps.

**Comment by nancymarinelli** [comment]
Well, thanks. But I do not see it in the list. There must be a new 
architecture. Which is what ?


On 06/03/19 17:57, boudoul wrote:
> ciao @nancymarinelli , we are now in 10_6_X so a most recent IB should be found in 10_6_X not in 10_5_X.
> Hope that helps.
>
>

-- 
________________________________________
Nancy Marinelli
Research Associate Professor
University of Notre Dame, IN, US
CERN, Bdg 40/3-A01, 1211 Geneva
SWITZERLAND
Phone +41-22-76-70809
fax +41-22-76-78940

**Comment by perrotta** [comment]
10_6_X IBs are only built in slc7.
For the architecture you can consider slc7_amd64_gcc700

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
please abort tests

**Comment by perrotta** [comment]
The errors are real, and originate in the normal workflows when the bParking era is not set

**Comment by perrotta** [comment]
please abort test

**Comment by fabiocos** [comment]
please test

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
+1
- ```recoConversions_gsfTracksOpenConversions``` are added to the miniAOD event content only in correspondence of the bParking era
- No change whatsoever for standard, non-bParking workflows: jenkins tests pass and show no differences
- Just for the record, in the 11024 wf (TTBar PU 2018) those conversions add 1.8 kB/evt to the miniAOD output in the bParking era; for comparison, slimmedLowPtElectrons amount to 54.9 kB/evt (while "normal" slimmedElectrons are at 2.0 kB/evt) and lowPtGsfEleGsfTracks stay at 23.9 kB/evt. All these sizes where measured with just 80 events: probably compression is sub-optimal, but it is just to provide an idea.

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Comment by santocch** [comment]
+1

**Pull request merged**
