### PR TITLE
122nano and boosted tau

### PR DESCRIPTION
**Pull request by mariadalfonso**
Add modifier to produce nanoV10 out of the Run3Winter22MiniAOD campaign initiated with the CMSSW_12_2_3_patch1 release.

boosted-tau ID in MINI changed along the way and are not consistent.
Disabled as are not needed for the early analyses.

Production can be called as follow:

For early Run3 MC
--era Run3,run3_nanoAOD_122 --customise="PhysicsTools/NanoAOD/V10/nano_cff.nanoAOD_customizeV10"

Prompt 12_4 data{*}  and real MC Run3 campaign
--era Run3  --customise="PhysicsTools/NanoAOD/V10/nano_cff.nanoAOD_customizeV10"

{*} https://cms-talk.web.cern.ch/t/t0-production-node-configuration-change-to-cmssw-12-4-3-and-era-run2022c/13003

+++++++++ validated with 

`cmsDriver.py mc122Xrun3_v10 -n 10 --mc --eventcontent NANOAODSIM --datatier NANOAODSIM --conditions auto:phase1_2022_realistic --step NANO --nThreads 1 --era Run3,run3_nanoAOD_122 --filein file:/tmp/dalfonso/5e00dedb-ac7b-4762-9d11-09647a813285.root --fileout file:nano_mc122Xrun3_v10.root --customise_commands "process.options.wantSummary = cms.untracked.bool(True)" --customise="PhysicsTools/NanoAOD/V10/nano_cff.nanoAOD_customizeV10"`

with input file 
xrdcp root://cmsxrootd.fnal.gov///store/mc/Run3Winter22MiniAOD/TTTo2J1L1Nu_CP5_13p6TeV_powheg-pythia8/MINIAODSIM/122X_mcRun3_2021_realistic_v9-v2/30000/5e00dedb-ac7b-4762-9d11-09647a813285.root .

### CODE REVIEW

**Comment by mariadalfonso** [comment]
please test

**Comment by mariadalfonso** [comment]
+xpog

**Comment by mariadalfonso** [comment]
any objection on merging this ?

**Comment by perrotta** [comment]
+1

**Pull request merged**
