### PR TITLE
update DependencyGraph service

### PR DESCRIPTION
**Pull request by fwyzard**
- show plugin class in tooltip (SVG only)
  - highlight a list of modules

### CODE REVIEW

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
I would like to add a helper function for this and similar services, to extract the list of modules from a sequence:
```python
def modules_in_sequences(* sequences):
  from FWCore.ParameterSet.SequenceTypes import ModuleNodeVisitor
  modules = []
  for sequence in sequences:
    sequence.visit(ModuleNodeVisitor(modules))
  return [ module.label() for module in modules ]
```

Any suggestions where it should go ?

**Comment by Dr15Jones** [comment]
@fwyzard I guess the helper function could go into FWCore.ParameterSet.Utilities?

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
this seems a cleaner way of disabling the warnings only for the relevant code

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
@Dr15Jones do you think the python is OK ?
it would be nice to have similar functions for Tasks, once they are in

**Comment by wddgit** [comment]
After the Task PR is integrated, the function (modulesInSequences) as written will already would work just fine if you put tasks in the list passed in as an argument. In addition, if there are tasks associated with a sequence the visitor will already visit the modules on those associated tasks if the sequence is passed in as an argument. You might consider renaming the function, but other than that it should just work.

**Comment by wddgit** [comment]
One other comment. After the Task PR is merged, the output list of modulesInSequences could contain ESProducers, ESSources and Services even when it is run on a Sequence because of the potential of tasks associated to the sequence. I have not looked at how that output list is used or whether that might cause problems.

**Comment by Dr15Jones** [comment]
+1

**Comment by fwyzard** [comment]
Hi David, thanks for the comment.
The current use case should still be fine, but I'll update the function to return only ED modules.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
