### PR TITLE
bsunanda:Phase2-hgx47 Update the ganging for BH as discussed in the simulation meeting

### PR DESCRIPTION
**Pull request by bsunanda**

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by ianna** [comment]
@bsunanda - it would be good to add description to future PRs when submitting them.

**Comment by ianna** [comment]
+1

**Pull request merged**
