### PR TITLE
adding configuration files for Matchbox and standalone H7 [backport]

### PR DESCRIPTION
**Pull request by theofil**
this is a back port from master into 106X, to have in sync the two releases

### CODE REVIEW

**Comment by agrohsje** [comment]
Hi @theofil . Do you mind linking above the PR to master? Thanks.

**Comment by theofil** [comment]
@agrohsje
If you mean to provide the link to the PR I previously made on master here
it is:
https://github.com/cms-sw/cmssw/pull/32337

if not, please explain.

**Comment by agrohsje** [comment]
Hi @theofil . Thanks for the link. This looks good to me except maybe the names. Maybe we could follow the dataset name strategy so that it is easy to understand what the fragments are about, like 
PPToEE_LO_TuneCH3_13TeV_herwig7_matchbox as well as DyToLL_TuneCH3_13TeV_herwig7 . I would omit the standalone, as we don't call -pythia8-standalone and matchbox indicates the special case of H7. Of course the same should then be done in master as well as potential flows that include them. Do you think we can easily do?

**Comment by theofil** [comment]
@agrohsje yes, should it be an update of the existing PR or we close this
and make a new one for 106 and master ?

**Comment by agrohsje** [comment]
Yes. We could close, fix in master and then backport everything.

**Comment by theofil** [comment]
closing this PR → opening new for master
https://github.com/cms-sw/cmssw/pull/33599

**Pull request closed without merging**
