### PR TITLE
multithreading fix for 74x:  L1GtTriggerMenu-related modules

### PR DESCRIPTION
**Pull request by fwyzard**

### CODE REVIEW

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
+1

**Comment by fwyzard** [comment]
tracked at #11317

**Comment by deguio** [comment]
+1

**Comment by fwyzard** [comment]
backport #10958 / #10970 to 74x

**Comment by ggovi** [comment]
+1

**Comment by mulhearn** [comment]
+1

**Comment by fwyzard** [comment]
rebased to merge on top of both CMSSW_7_4_X and CMSSW_7_4_12_patch4

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
+1

**Comment by deguio** [comment]
+1

**Comment by mulhearn** [comment]
+1

**Comment by monttj** [comment]
+1

**Comment by ggovi** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
