### PR TITLE
Use Run and Lumi caches in ConditionDumperInEdm

### PR DESCRIPTION
**Pull request by Dr15Jones**
Switched to using Run and LuminosityBlock based caches to allow efficient concurrent processing of those transitions.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
hold
There is a bug in the framework which is causing the crash.

**Comment by Dr15Jones** [comment]
I can confirm that #25237 fixes the crash in this pull request.

**Comment by Dr15Jones** [comment]
please test with  #25237

**Comment by Dr15Jones** [comment]
unhold 
The needed framework fix is now in the IB

**Comment by thomreis** [comment]
+1

**Comment by fabiocos** [comment]
+1

DQM changes look unrelated to this PR

**Pull request merged**
