### PR TITLE
Modernize CastorDbProducer

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

This PR modernizes the CastorDbProducer (as part of #26748) by
- move header to source
- migrate to ES consumes
- generalize the implementation

#### PR validation:

Limited matrix runs.

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
@cmsbuild, please abort

**Comment by makortel** [comment]
Didn't notice first that this package was already clang-formatted, so I squashed the formatting changes on top of my changes to the same commit.

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by pohsun** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
