### PR TITLE
Move PFClusterWidthAlgo into CommonTools/ParticleFlow

### PR DESCRIPTION
**Pull request by guitargeek**
#### PR description:

This PR moves `PFClusterWidthAlgo` from  RecoParticleFlow/PFClusterTools to CommonTools/ParticleFlow. That class is used both in RecoEgamma and RecoEcal as well, justifying the transition to CommonTools. Like this, the dependency of RecoEgamma on RecoParticleFlow is eliminated.

Furthermore, the includes in HGCalShowerShapeHelper are cleaned to make it not appear like RecoEgamma/EgammaTools depends on RecoParticleFlow.

#### PR validation:

CMSSW compiles.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

No backport intended.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+reconstruction

for https://github.com/cms-sw/cmssw/pull/33458	dbaf8b4
- code changes are in line with the PR description, moving PFClusterWidthAlgo
- jenkins tests pass and comparisons with the baseline show no (relevant) differences

**Comment by qliphy** [comment]
+1

**Pull request merged**
