### PR TITLE
A correct description of the HL-LHC beamspot

### PR DESCRIPTION
**Pull request by lgray**
This PR changes the HL-LHC beamspot simulation we are using to be exactly the HL-LHC beamspot simulation from the HL-LHC machine group.

This PR is waiting for one more item: a correct description of the x and y distribution of vertices in the beamspot.  

The online beamspot doesn't need to be updated as the major change here is for the width of the beamspot in time, and the online beamspot only has spatial coordinates. There is a slight change in the beamspot z width but it does not invalidate the beamspot in the database.

Vertex profile in time (axis is ns, arb units):
vertex_t_profile

Vertex profile in z (axis in cm, normalized to ev/mm in 140 PU):
vertex_z_profile

Vertex shape in z and time (arb units):
vertex_zt_profile

@davidlange6 It would be good to get this in for the tracker TDR production, I also found a weird bug in the old HL-LHC beamspot such that x and z were correlated (which should not be the case!).

### CODE REVIEW

**Comment by lgray** [comment]
@cmsbuild please test

Reminder - this PR only has the z and time coordinates cross-validated with the HL-LHC machine group. X and Y should come soon.

@kpedro88

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
Seriously clang? No constexpr sqrt?

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by civanch** [comment]
@lgray , usually a beam spot scerario also registered in Configuration/StandardSequences/python/VtxSmeared.py

In HLLHCEvtVtxGenerator.cc you locally defines static values which exist in CLHEP. But you have CLHEP headers in this class:

  CLHEP::pi, CLHEP::twopi, CLHEP::proton_mass_c2, CLHEP::c_light - all are there.

**Comment by lgray** [comment]
@civanch This beamspot scenario is already in VtxSmeared.py from old (buggy) version of the beamspot description: https://github.com/cms-sw/cmssw/blob/CMSSW_9_0_X/Configuration/StandardSequences/python/VtxSmeared.py#L38-L41

I guess the CLHEP statics will get optimized away too, though I really prefer using constexpr.

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
Attached here are the current x and y profiles. I am awaiting further iteration with the HL-LHC guys to make sure this matches what they expect. 

profile in x:
vertex_x_profile

profile in y
vertex_y_profile

profile in xy:
vertex_xy_profile

**Comment by civanch** [comment]
+1
@lgray , CLHEP number are constexpr, there is no sense redefining these numbers locally.

**Comment by lgray** [comment]
HOLD

This PR is pending validation from contacts in the HL-LHC machine group. We
should make sure *first* that these parameters are correct before merging.

**Comment by kpedro88** [comment]
hold

**Comment by lgray** [comment]
@kpedro88 could you unhold, I have confirmation from Rogelio Garcia (HL-LHC guy) that this looks good. I am doing a few final checks.

**Comment by lgray** [comment]
Here are the beam profiles for the default parameters of this validated HL-LHC beamspot simulation. This is for 200PU.

profile in x (arb units):
vertex_x_profile

profile in y (arb units):
vertex_y_profile

profile in z (ev/mm):
vertex_z_profile

profile in t (arb units): 
vertex_t_profile

2D space vs. time profiles (arb units):
vertex_tx_profile
vertex_ty_profile
vertex_zt_profile

2D spatial profiles (arb units):
vertex_xy_profile
vertex_zx_profile
vertex_zy_profile

**Comment by lgray** [comment]
Hold on, this has some effects in the reconstruction to understand. Not expected.

@slava77

**Comment by lgray** [comment]
OK - talking to @slava77 a bit more since the beamspot is different the comparison with the baseline is different from the SIM level so it's hard to make a good comparison with 10 events.

**Comment by lgray** [comment]
@VinInn @rovere @mmusich 

Just FYI the current reco::BeamSpot parameters for HL-LHC are:
```-----------------------------------------------------
              Beam Spot Data

 Beam type    = 2
       X0     = 1.56059e-05 +/- 1.11113e-05 [cm]
       Y0     = -5.14073e-06 +/- 1.08985e-05 [cm]
       Z0     = 0.0282329 +/- 0.0694134 [cm]
 Sigma Z0     = 4.31313 +/- 0.0490817 [cm]
 dxdz         = 0.000103158 +/- 2.53614e-06 [radians]
 dydz         = -2.13911e-07 +/- 2.48033e-06 [radians]
 Beam Width X = 0.00137129 +/- 2.07524e-05 [cm]
 Beam Width Y = 0.000806147 +/- 2.07524e-05 [cm]
 Emittance X  = 0 [cm]
 Emittance Y  = 0 [cm]
 Beta star    = 0 [cm]
-----------------------------------------------------```

And for this new HL-LHC beam spot the BeamWidthX is 11um (instead of 13um), BeamWidthY is 5um (instead of 8um), SigmaZ is more or less the same.

Should we update the beamspot, or just go as is?

**Comment by lgray** [comment]
However, the bias in the x0 (which should be zero for HL-LHC) is almost one sigma. Not sure if that matters for tracking.

**Comment by mmusich** [comment]
@lgray about:

> Should we update the beamspot, or just go as is?

we can easily update it if you point me to the list of preferred parameters.

**Comment by lgray** [comment]
@mmusich Noted! I will await input from @VinInn and @rovere in that case.

**Comment by kpedro88** [comment]
unhold

**Comment by davidlange6** [comment]
+1

**Comment by davidlange6** [comment]
I realize I merged this one prematurely - however the beam spot bias issue is not due to this PR, so I'm not reverting it (unless discussion to come indicates that is the right thing).

**Comment by lgray** [comment]
Beamspot bias issue? Guessing this is for present running or is this for
Phase 2 studies?

**Comment by lgray** [comment]
@davidlange6 I'm curious about this because there are some offsets we see
in timing distributions that appeared that we haven't been able to trace
down.

**Comment by lgray** [comment]
Even with the "NoSmear" beamspot.

**Pull request merged**
