### PR TITLE
Run3-gex150 Avoid using cout in Geometry/CMSCommonData

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Avoid using cout in Geometry/CMSCommonData

#### PR validation:

Use the runTheMatrix test workflows

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by bsunanda** [comment]
@srimanob Please approve this

**Comment by srimanob** [comment]
+Upgrade

Technical PR.

**Comment by perrotta** [comment]
+1

**Pull request merged**
