### PR TITLE
Adding JECs, PF and L1T menu to Run-3 MC GTs and data relval GTs

### PR DESCRIPTION
**Pull request by tvami**
#### PR description:

Include JEC and PF calibrations as request in https://cms-talk.web.cern.ch/t/gt-new-run3-hlt-jec-tags-for-123x-125x-for-mc/13290 and https://cms-talk.web.cern.ch/t/gt-updated-pf-calibration-hlt-tag-for-run-3/13293 then add new L1T menu as requested in https://cms-talk.web.cern.ch/t/run-3-gt-update-of-the-l1-menu-tag-v1-3-0-in-run-3-mc-gts-and-run-3-data-relvals-gts/13513

The new GTs and their diff wrt to the last GTs in autoCond are here

**phase1_2022_design**

https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts//124X_mcRun3_2022_design_v7/125X_mcRun3_2022_design_v2

**phase1_2022_realistic**

https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts//124X_mcRun3_2022_realistic_v10/125X_mcRun3_2022_realistic_v2

**phase1_2022_cosmics**

https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts//124X_mcRun3_2022cosmics_realistic_deco_v11/125X_mcRun3_2022cosmics_realistic_deco_v2

**phase1_2022_cosmics_design**

https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts//124X_mcRun3_2022cosmics_design_deco_v7/125X_mcRun3_2022cosmics_design_deco_v2

**phase1_2022_realistic_hi**

https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts//124X_mcRun3_2022_realistic_HI_v10/125X_mcRun3_2022_realistic_HI_v2

**phase1_2023_realistic**

https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts//124X_mcRun3_2023_realistic_v11/125X_mcRun3_2023_realistic_v2

**phase1_2024_realistic**

https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts//124X_mcRun3_2024_realistic_v11/125X_mcRun3_2024_realistic_v2

**phase2_realistic**

https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts//124X_mcRun4_realistic_v8/125X_mcRun4_realistic_v2

**run3_hlt_relval**

https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts//124X_dataRun3_HLT_relval_v8/125X_dataRun3_HLT_relval_v1

**run3_data_relval**

https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts//124X_dataRun3_relval_v8/125X_dataRun3_relval_v1

#### PR validation:

```
test parameters:
  - workflows = 12034.0,11634.0,7.23,159.0,12434.0,12834.0
 ```

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Not a backport, backport might be needed, under discussion

### CODE REVIEW

**Comment by tvami** [comment]
test parameters:
  - workflows = 12034.0,11634.0,7.23,159.0,12434.0,12834.0

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
assign hlt
 * all these changes are affecting HLT step

**Comment by missirol** [comment]
@tvami 

I can check the comparisons later today. If there aren't other updates to `autoCond` expected in the next 2/3 days, we could integrate this PR by the end of the week together with the corresponding update of the HLT menus (PR to come). Otherwise, I'll check and possibly sign this PR sooner.

**Comment by tvami** [comment]
hi @missirol thanks! As of now it seems we wont have further updates in the coming days.

**Comment by missirol** [comment]
@tvami 

I noticed that in this PR there are IOV differences between `run3_hlt`-vs-`run3_hlt_relval` and `run3_data`-vs-`run3_data_relval`. Maybe it's not a showstopper for this PR, but it should eventually be fixed, imho. (Basically, every time the 2 `relval` GTs are updated with a new L1T-menu tag, the 2 non-`relval` GTs also need to be updated/snapshot-ed accordingly, afaiu.)

**Comment by missirol** [comment]
please test

Refreshing the comparisons, still with the current HLT menu, to see the expected differences from GT changes.

**Comment by mmusich** [comment]
> but it should eventually be fixed, imho. 

Sorry to chime in,  but since I have seen this request elsewhere, I keep not understanding why this would be a problem. 
Are you testing with these Global Tags any data more recent then the earliest snapshot? If not it should not make any difference.

**Comment by missirol** [comment]
>  Are you testing with these Global Tags any data more recent then the earliest snapshot? If not it should not make any difference.

Not to my knowledge.

No, it won't make a difference, that's why I wrote it is not a showstopper. My understanding of the policy agreed to by AlCa and TSG is that the only difference between `auto:X` and `auto:X_relval` should be the L1TMenu tag; anything on top of that leads to unnecessary confusion. That's just my 2 cents.

I assume there are good reasons to have the `relval` GTs as separate standalone GTs, but I wonder if we could set them up dinamically in CMSSW making `auto:X_relval` from `auto:X` plus a customisation to override the L1T menu tag. This would reduce the maintenance load on AlCa, and I'm not sure what the disadvantage would be.

**Comment by mmusich** [comment]
> This would reduce the maintenance load on AlCa, and I'm not sure what the disadvantage would be.

A long time ago (beginning of Run2) it was deemed better that GlobalTags employed in relvals are "physical" snapshots of the DataBase and not dynamically built constructs, to avoid unpleasant irreproducibility issues when those are built by non-experts.

**Comment by missirol** [comment]
> matter-of-factishly this is required for aesthetical reasons

I simply wrote what my understanding of the approach was. Others can correct me and/or agree that this isn't necessary, re the IOV diffs.

> A long time ago (beginning of Run2) it was deemed better that GlobalTags employed in relvals are "physical" snapshots of the DataBase and not dynamically built constructs, to avoid unpleasant irreproducibility issues when those are built by non-experts.

Thanks, good to know. My thought was that, given a release, one would know what is `auto:X` and what is the L1T menu that goes into `X_relval`, thus would know the latter without ambiguity. In any case, I see the point and it is not for me to decide. I was simply wondering.

**Comment by tvami** [comment]
So my conclusion from the discussion above is that it's fine to keep the GTs as they are for now, in the future we should pay more attention to have the exact same snapshot for that two GTs.

**Comment by tvami** [comment]
@cmsbuild , please abort
 * tests are stuck....

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
hi @missirol we have now another update for the autoCond, so this should be merged, should we do it semi-blind? given that the DQM tool is not working...

**Comment by tvami** [comment]
@cms-sw/alca-l2 
looking at the diffs in
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_5_X_2022-08-06-1100+a50019/52000/11634.7_TTbar_14TeV+2021_trackingMkFit+TTbar_14TeV_TuneCP5_GenSim+Digi+RecoNano+HARVESTNano/HLT.html

I see jets and trigger related changes, which are all expected by the changes in this PR. Can you please sign so I dont sign my own PR?

**Comment by missirol** [comment]
> we have now another update for the autoCond, so this should be merged, should we do it semi-blind? given that the DQM tool is not working...

I would try to wait a bit longer if possible, e.g. until tomorrow, hoping the DQM issue gets fixed. Would that be okay? In the meantime, I will check the available comparisons, like those from the link you shared.

**Comment by francescobrivio** [comment]
+alca

 - given the conclusion in https://github.com/cms-sw/cmssw/pull/38916#issuecomment-1208002268 and the fact that we have more updates for autoCond in the pipeline

**Comment by francescobrivio** [comment]
> > we have now another update for the autoCond, so this should be merged, should we do it semi-blind? given that the DQM tool is not working...
> 
> I would try to wait a bit longer if possible, e.g. until tomorrow, hoping the DQM issue gets fixed. Would that be okay? In the meantime, I will check the available comparisons, like those from the link you shared.

I guess we can hold off the changes in the pipeline untill tomorrow, but I would not delay too much if possible.
@cms-sw/dqm-l2 any update on the DQM tool?

**Comment by missirol** [comment]
+hlt

Did not find evidence of issues. Afaict, differences in PR comparisons are small, and I think that's consistent with expectations (more detailed physics validation of these changes was, or will be, done offline by the JME-POG and TSG).

**Comment by tvami** [comment]
urgent
 * @cms-sw/orp-l2 we have another update in the queue, please merge this asap thanks!

**Comment by qliphy** [comment]
+1

**Pull request merged**
