### PR TITLE
Fix Release Validation Test

### PR DESCRIPTION
**Pull request by ianna**
- Do not test removed scenario
- Add new scenarios to test

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
@cmsbuild - it does not look like the error is related to this PR

**Comment by smuzaffar** [comment]
cmsbuild, please test

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
