### PR TITLE
add ntuplizer for pixel hits

### PR DESCRIPTION
**Pull request by emiglior**
Added a simple EDA for writing user ntuple with the pixel RecHit infos for SLHC studies.
It is essentially a developement of SLHCUpgradeSimulations/Geometry/test/StdHitNtuplizer[.h,.cc] but limited to pixels only.
@ktf, @davidlt 
@boudoul, @mmusich

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild please test

**Comment by emiglior** [comment]
@cmsbuild please notice changes in BuildFile

**Comment by emiglior** [comment]
@boudoul, @ianna, @mmusich
Hi, 
I have two questions:
- who is going to sign the PR?
- should we forward-port this analyzer to CMSSW_75X?

**Comment by emiglior** [comment]
@atricomi this is something that you might want to monitor as well

**Comment by boudoul** [comment]
hi @emiglior , the release managers of the SLHC release  willl take care at their convenance -  It would be good indeed to have this analyzer ready in 75X - We probably cannot test it in 75X at this point, but keeping things synchronized is good , can you prepare a PR for 75X too ? Thanks.

**Comment by mark-grimes** [comment]
merge

**Pull request merged**
