### PR TITLE
Run3-sim91X Backport the xml files needed for a more correct Run3 geometry scenario definition

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Backport the xml files needed for a more correct Run3 geometry scenario definition. This is the split version of #35108 retaining only the xml parts

#### PR validation:

Use the runTheMatrix test workflows in #35108

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Done in many PR's for 12_1_X and these files are from 12_1_X

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
+1

**Comment by bsunanda** [comment]
@srimanob Please approve this

**Comment by srimanob** [comment]
+Upgrade

**Comment by perrotta** [comment]
+1
- Backport of xml files, but nothing has been implemented yet at this point

**Pull request merged**
