### PR TITLE
Run2-TB33 Enable test beam setup to dump geometry for cmsShow

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Dumping for cmsShow needs a logical volume of unique name and copy number for  every positioning 

#### PR validation:

Tested with dumping the geometry as well as running the SIM step with the modified version

#### if this PR is a backport please specify the original PR:

It is needed for the main branch only - no back porting needed

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by kpedro88** [comment]
+upgrade

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade

**Comment by fabiocos** [comment]
+1

**Pull request merged**
