### PR TITLE
use python from env instead of /usr/bin/python

### PR DESCRIPTION
**Pull request by smuzaffar**
Remove the hard coded `/usr/bin/python` and pick up python from PATH. This will make sure that we use the python provided by cmssw.

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by qliphy** [comment]
+1

**Comment by fabiocos** [comment]
+1

@Martin-Grunewald @jfernan2 @andrius-k these are simple technical fixes that I will merge in next IB, please have a look

**Comment by jfernan2** [comment]
+1

**Comment by Martin-Grunewald** [comment]
+1

**Pull request merged**
