### PR TITLE
trends vs LS instead of seconds

### PR DESCRIPTION
**Pull request by threus**
Updated few trend plots to be plotted vs lumisection rather than time in offline DQM. This will help LS-based run certification for SiStrips. Based on the work of @mateoRG

### CODE REVIEW

**Comment by threus** [comment]
apologies, my bad!

**Comment by deguio** [comment]
ciao @threus 
you can push to this same branch in order to update this PR.
ciao,
F.

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1

**Pull request merged**
