### PR TITLE
Add Phase-2 with HLT:75e33 wf

### PR DESCRIPTION
**Pull request by srimanob**
#### PR description:
To add Phase-2 wf with HLT 75e33 menu. This is still a draft, to be used with https://github.com/cms-sw/cmssw/pull/37158 and https://github.com/cms-sw/cmssw/pull/37162.

#### PR validation:
`runTheMatrix.py --what upgrade -l 35034.111 -t 8 --wm init`
give expected workflow.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:
If merge in 12_4_X, then backport is needed for 12_3_X.

### CODE REVIEW

**Comment by trtomei** [comment]
Cross-posting from #37162 : how does this need to be modified to become the workflow discussed there?

**Comment by Martin-Grunewald** [comment]
I understand this PR currently defines part of the required workflow (only), but not the complete one, nor does it add it to the PR, IB and relval tests. @srimanob could you please help us to achieve this?

**Comment by srimanob** [comment]
Hi @Martin-Grunewald @trtomei 
I will update the PR to address the additional step of HLT.

**Comment by srimanob** [comment]
@cmsbuild code-checks

**Comment by srimanob** [comment]
Reopen the PR in 124 branch, https://github.com/cms-sw/cmssw/pull/37324

**Pull request closed without merging**
