### PR TITLE
Updated MessageLogger tests to remove obsolete usages

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

- removed the use of fwkJobReports parameter as that parameter has done nothing for years.
- change FwkJob to FwkTest to better reflect how it has been used for years.

NOTE: neither were removed from the _cfi files used outside of the tests as that could break existing configurations. Such a change will be done at a later date.

#### PR validation:

Relevant framework unit tests pass.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by makortel** [comment]
@Dr15Jones There are merge conflicts (caused by the merge of https://github.com/cms-sw/cmssw/pull/31815)

**Comment by Dr15Jones** [comment]
please test

**Comment by makortel** [comment]
+1

The Reco differences are caused by https://github.com/cms-sw/cmssw/pull/31470 that was included in the test on top of the IB.

**Comment by silviodonato** [comment]
+1

**Pull request merged**
