### PR TITLE
ECAL Bad Calibration Filter for 94X

### PR DESCRIPTION
**Pull request by gouskos**
Backporting #20698 in 94X: Add a filter for the Ecal crystal with bad calibrations

### CODE REVIEW

**Comment by slava77** [comment]
backport of #20698

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/21062	681792e
- addition of a MET filter path to flag events if some ecal channels are over threshold; backport of #20698 is correct
- jenkins tests pass and comparisons show no difference

**Comment by davidlange6** [comment]
merge

**Pull request merged**
