### PR TITLE
Add vertex of problem tau in HepMCValidationHelper

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

It is possible that the tau has gone farther than the generator is willing to decay it.

#### PR validation:

Code compiles.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
@makortel FYI

**Comment by Dr15Jones** [comment]
Another possible issue is the tau comes after the pruning happens to the particle list. Perhaps the pruning removed the daughters?

**Comment by makortel** [comment]
Would the production vertex be useful as well?

**Comment by Dr15Jones** [comment]
@makortel 
> Would the production vertex be useful as well?

The belief is the decay is beyond the beam pipe cutoff limit so the only important value is the decay vertex. Also, since this comes from the generator and the generator is not supposed to decay 'long flying' particles the production vertex should be close to the beam interaction point.

**Comment by Dr15Jones** [comment]
@cms-sw/generators-l2 @cms-sw/dqm-l2 please consider signing as the change is trivial and should help crackdown the ongoing problem.

**Comment by emanueleusai** [comment]
+1

**Comment by Dr15Jones** [comment]
@cms-sw/generators-l2

**Comment by Dr15Jones** [comment]
@cms-sw/generators-l2 ping

**Comment by Dr15Jones** [comment]
@cms-sw/generators-l2 the failure this PR is meant to help diagnosed has happened 4 times this week in the IBs. Having this change in will help trace down the origin of the problem.

**Comment by perrotta** [comment]
+1
- This only updates the Exception message: let bypass the @cms-sw/generators-l2 signature (but please feel free to comment and complain once this is merged)

**Comment by perrotta** [comment]
merge

**Pull request merged**
