### PR TITLE
trackingNtuple updates from mkFit/LST developments

### PR DESCRIPTION
**Pull request by slava77**
these updates accumulated over a couple of years in the mkFit and line-segment tracking (LST) developments.
The default trackingNtuple logic should be the same (aside for a few added branches).

Summary of changes relative to the upstream in TrackingNtuple
- optional for simhits info:
    - can add OOT hits with `includeOOT`
    - can keep (secondary) electron simhits with `keepEleSimHits`
    - can save simhit momentum px,py,pz with `saveSimHitsP3`
    - can enable saving only the closest simhit based on significance sorting with `simHitBySignificance`
- optional for seed details:
    - can save Curvilinear 5x5 covariance with `addSeedCurvCov` in a row-major vector of size 15
- added by default:
    - bitmask of cluster masking used per iteration; configurable via `clusterMasks`
    - cluster charge per CM
    - cluster size 
    - seed state parameters in global coordinates (x,y,z and px,py,pz)
- config tools now have `customiseTrackingNtupleHLT` to be able to run on HLT tracking

Also, add `TrackSimpleMerger` which can concatenate a set of reco::Track collections.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by jfernan2** [comment]
+1

**Comment by slava77** [comment]
@mtosi @vmariani @mmusich 
please check the updates.

I see that DQM have signed already, but since I did not discuss the details in this PR explicitly with TRK POG, I wanted to get an OK for the updates.

(this was reviewed/discussed with former TRK POG conveners (@makortel and @cerati ) as a part of developments/needs for mkFit; just to give more context)

**Comment by mtosi** [comment]
+1, thanks

**Comment by slava77** [comment]
+reconstruction

for https://github.com/cms-sw/cmssw/pull/34256	be2d604 
- code changes are primarily in Validation/RecoTrack; the reco category includes only an addition of a plain track merger CommonTools/RecoAlgos/plugins/TrackSimpleMerger.cc
- jenkins tests pass and comparisons with the baseline show no (relevant) differences

**Comment by qliphy** [comment]
+1

**Pull request merged**
