### PR TITLE
[HGCAL trigger] V11 geometry compatibility

### PR DESCRIPTION
**Pull request by jbsauvan**
#### PR description:
Add compatibility with the V11 geometry.
Depends on external cms-data/L1Trigger-L1THGCal#17

#### PR validation:
Tested V9, V10 and V11 worflows
```
runTheMatrix.py -w upgrade -l 20034.0 --maxSteps=2
runTheMatrix.py -w upgrade -l 20434.0 --maxSteps=2
runTheMatrix.py -w upgrade -l 22034.0 --maxSteps=2
```

### CODE REVIEW

**Comment by rekovic** [comment]
please test

**Comment by rekovic** [comment]
abort test

**Comment by rekovic** [comment]
needs to be tested with external  cms-data/L1Trigger-L1THGCal#17 (attn @mrodozov )

**Comment by kpedro88** [comment]
test parameters
pull requests = https://github.com/cms-data/L1Trigger-L1THGCal/pull/17

**Comment by kpedro88** [comment]
please test

**Comment by mrodozov** [comment]
its like 
```
test paarmeters:
- pull requests = cms-data/L1Trigger-L1THGCal#17
```

**Comment by kpedro88** [comment]
please abort

**Comment by kpedro88** [comment]
test parameters
pull_requests = cms-data/L1Trigger-L1THGCal#17

**Comment by kpedro88** [comment]
please test

**Comment by smuzaffar** [comment]
please test
looks like previous test did not run with the data external. Jenkins job paramters in https://cmssdt.cern.ch/jenkins/job/ib-run-pr-tests/5575/console   show that it was not run for cmssw PR.

**Comment by kpedro88** [comment]
appears to be an error in the IB

**Comment by smuzaffar** [comment]
please test

**Comment by kpedro88** [comment]
+upgrade

**Comment by rekovic** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
