### PR TITLE
Change ECAL DQM Presample and Trigger primitive plots thresholds

### PR DESCRIPTION
**Pull request by abhih1**
#### PR description:
This PR changes the thresholds of 

- Presample Quality plot to remove the ring of red spots observed in the Ecal endcaps
- Trigger Primitive emulator quality plot to remove the red towers at high eta in the endcaps

These are known issues due to ageing and radiation effects and the thresholds will need to be assessed and changed further, if need be.

#### PR validation:

PR is validated by running the ECAL online DQM configuration and verifying the plots on a test DQM GUI.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

This is the Master PR.
Backports are made to 13_0_X  and 13_1_X

### CODE REVIEW

**Comment by thomreis** [comment]
type ecal

**Comment by thomreis** [comment]
please test

**Comment by emanueleusai** [comment]
+1

- differences in ECAL DQM plots as expected

**Comment by perrotta** [comment]
+1

**Pull request merged**
