### PR TITLE
Move Common Graph Classes from DD to Utilities

### PR DESCRIPTION
**Pull request by ianna**
* Move Graph classes as is
* Minimal cleanup
* Add tests
* Remove unneeded dependencies

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
@slava77 and @Dr15Jones - FYI

This is a pretty much straightforward move. I'll update Reco and DD code as a separate step when this PR is merged in an IB. Note, the code does call for more cleanup/modernization. I'm planning to do it after we have comparison plots in place (e.g a step 3).

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
@Dr15Jones - have you had a chance to look at it? Thanks.

**Comment by Dr15Jones** [comment]
I see that @slava77 suggested putting this in `CommonTools/Utils`. What was the motivation for putting it in `Utilities/General` (which is bassically a place holding classes which will probably eventually be removed)?

**Comment by ianna** [comment]
CommonTools/Utils bring in additional dependencies on:
```
<use   name="FWCore/Utilities"/>
<use   name="FWCore/MessageLogger"/>
<use   name="CondFormats/DataRecord"/>
<use   name="CondFormats/EgammaObjects"/>
<use   name="boost"/>
<use   name="roothistmatrix"/>
<use   name="roottmva"/>
```
I've discussed with @smuzaffar and he suggested the latter.

**Comment by Dr15Jones** [comment]
Thanks for the reasoning.

**Comment by Dr15Jones** [comment]
+1

**Comment by Dr15Jones** [comment]
By the way, the 'unit test' is not a unit test since it does not fail if something doesn't work. (I know the test predates your oversight of geometry).

**Comment by davidlange6** [comment]
Utilities/* is not the place for this code.. [just have a look at whats there] Remind me, who are the consumers of this?

**Comment by ianna** [comment]
@davidlange6 - it's DetectorDescription and Reco

**Comment by Dr15Jones** [comment]
hold

**Comment by davidlange6** [comment]
DataFormats/Math has a number of similar constructs..

**Comment by Dr15Jones** [comment]
I suspect what we really need to do is see if we can replace our 'Graph' with the actual boost graph library.

**Comment by davidlange6** [comment]
I believe that was the idea - however i it won't happen tomorrow..

**Comment by Dr15Jones** [comment]
Of we want to replace this code, what is the urgent need to move it now?

**Comment by ianna** [comment]
@davidlange6 - yes, moving to boost is the plan.
@Dr15Jones - Reco vertex code depends on DetectorDescription now. I just wanted to remove the need to additional signature while working on it.

**Comment by ianna** [comment]
@Dr15Jones and @davidlange6 - FYI, if I need to update the graph code and check out dependencies, I get the whole shebang which takes a while to compile:
```
Alignment  CalibTracker  CondTools  DetectorDescription  Fireworks  GeometryReaders      L1Trigger      PhysicsTools  RecoEgamma     RecoLocalFastTime  RecoParticleFlow  RecoTauTag   RecoVertex              SUSYBSMAnalysis  SimG4CMS   SimGeneral   SimTracker        Utilities
CalibMuon  Calibration   DQM        FastSimulation       Geometry   HeavyFlavorAnalysis  MagneticField  RecoCTPPS     RecoLocalCalo  RecoMET            RecoRomanPot      RecoTracker  SLHCUpgradeSimulations  SimCalorimetry   SimG4Core  SimRomanPot  TrackPropagation  Validation
```

**Comment by ianna** [comment]
as discussed with @davidlange6 - I'll move the classes to DataFormats/Math

**Comment by ianna** [comment]
@davidlange6 - DataFormats/Math does not look like a good pace for the classes:
```
Unknow target src/Utilities/General/interface/Graph.h
Unknow target src/Utilities/General/interface/GraphWalker.h
```

**Comment by smuzaffar** [comment]
@ianna, you need to run "scram build clean".
Anyway, DataFormats/Math also have other dependencies 
```
<use   name="DataFormats/Common"/>
<use   name="DataFormats/Provenance"/>
<use   name="FWCore/MessageLogger"/>
<use   name="FWCore/Utilities"/>
<use name="DataFormats/StdDictionaries"/>
```

**Pull request closed without merging**
