### PR TITLE
Preparing Upgrade WFs in RunTheMatrix

### PR DESCRIPTION
**Pull request by boudoul**
This PR is adding the upgrade workflows in RunTheMatrix
While large software developments are still needed to make the upgrade geometries working in 74X, runTheMatrix is now ready for the different configurations as it was defined in 62XSLHC and will also help developers to get recipe when developing the ugrade software
This change is not impacting any of the standard workflows used in IBs or during the injection of the relvals.
The  upgrade workflows can only be called with the --what upgrade option and therefore are not run in IBs. (until we have something really running) 
@mark-grimes :  FYI

### CODE REVIEW

**Comment by degano** [comment]
@cmsbuild please test

**Comment by franzoni** [comment]
+1

HI @boudoul , what you propose is all fine. A few tests revealed no problems.
Two comments, which are for us PdmV ( @srimanob ) and offline more in general

+ handling "epochs" / "eras" in a systematic way which is not only top-level dictionaries is the organic way of managing multiple versions of the CMS experiment co-existing in the same release; besides relval, also production sequences (e.g. : recent need of different L1 emulation sequences for 50ns, 25ns ) could be handled more cleanly that way.
@davidlange6 we spoke about this a year ago or os, you said at the time there was development ongoing, can we try anything out ? 

+ more relval -specific: we could forward-think and figure out if / which commonality do we expect to have between the runII- and upgrade-specific dictionary/tuples . Better merging all options in the same file or splitting ? "relval_upgrade.py "  and upgradeWorkflowComponents.py could merge in one.

**Comment by davidlange6** [comment]
There is a pull request implementing eras in 74x since a while. (Thanks to @mark-grimes ) - it needs some attention from me.

**Comment by franzoni** [comment]
thanks @davidlange6 @mark-grimes good news about eras!
Can you let us PdmV know @boudoul @srimanob know when we can take a look, and understand implications for production and relvals ? Tks.

**Comment by franzoni** [comment]
@davidlange6 @mark-grimes, which one is the PR in question ?
@boudoul @srimanob

**Comment by davidlange6** [comment]
#6784 
which can be found via the github search (or the 74x PR list)
https://github.com/cms-sw/cmssw/search?q=era&type=Issues&utf8=✓

**Pull request merged**
