### PR TITLE
L1Trigger DQM Combo PR 13800 fixed merge conflict

### PR DESCRIPTION
**Pull request by rekovic**
This is basically PR #13800 with merge conflicts fixed in two files:
- DataFormats/L1TMuon/interface/EMTF/SP.h
- EventFilter/L1TRawToDigi/src/implementations_stage2/EMTFBlockSP.cc

### CODE REVIEW

**Comment by rekovic** [comment]
It is built on top of last night built. It merges cleanly.

**Comment by rekovic** [comment]
please test

**Comment by swang373** [comment]
@deguio @mzarucki 
The urgent updates for uGT have been merged (d3bad586a061e90f37bed7e4343e178acc783b4ad3bad58) and the configuration file for the DQM sequence was updated to correctly load the global tag when testing offline (1d70a22389a240c05bc48212503822246bfc19d0).

**Comment by rekovic** [comment]
+1

please test

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
