### PR TITLE
[NanoAOD] Backport of #41687 (Fix typo of imported ParticleNet tagger list for AK4 Puppi jets) to 13_1_X

### PR DESCRIPTION
**Pull request by nurfikri89**
Backport of #41687

#### Original PR description:
This PR fixes a typo bug for the imported ParticleNet tagger list in `nanoAOD_addDeepInfoAK4` function in `jetsAK4_Puppi_cff.py`. Confirmed by @scooperstein that this is a typo. Replace `CHS` with `Puppi`. 

#### PR validation:
passes the usual runTheMatrix test: `runTheMatrix.py -l limited -i all --ibeos`

### CODE REVIEW

**Comment by perrotta** [comment]
type bug-fix

**Comment by perrotta** [comment]
@cms-sw/xpog-l2 , as this in a bug-fix, perhaps you would like to have it merged in the next CMSSW_13_1_0 release...

**Comment by simonepigazzini** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
