### PR TITLE
Migrate module configuration in RecoTauTag to use default cfipython

### PR DESCRIPTION
**Pull request by jeongeun**
#### PR description: 
Optimization of the python configurations: Improve maintainability by cleaning up the duplicated and cloning from the default/reference configurations. (The previous PRs : #33207, #33307, #33352, #33543, #33563, #33671, #34007, #34091, #34009, #34155, #34371, #34480, #34543, #34571, #34817, #34818 )
 
In this PR, 4 files changed.  
        modified:   RecoTauTag/RecoTau/python/PATTauDiscriminationByMVAIsolationRun2_cff.py
        modified:   RecoTauTag/RecoTau/python/PFRecoTauDiscriminationByMVAIsolation2_cff.py
        modified:   RecoTauTag/RecoTau/python/PFRecoTauTagInfoProducer_cfi.py
        modified:   RecoTauTag/RecoTau/python/PFTauPrimaryVertexProducer_cfi.py

Update
- Replace explicit configuration with a reference from cfipython/. (migrating EDProducer("type", .. -> typeDefaylt.clone() ) 
- Remove the type specifications already presented in cfipython/fillDescriptions reference for improved syntax safety.
- Remove the duplicated parameters that are exactly the same value in cfipython reference.

#### PR validation:
Event Content comparison check was also done and there is no change with these updates.
Tested in CMSSW_12_1_X, the basic test all passed in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html).

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by mbluj** [comment]
The changes look fine for tau reco.
+1

**Comment by jpata** [comment]
+reconstruction
- technical, no reco changes expected/observed
- I checked that there is no change in the config dump before and after this change, as expected

**Comment by perrotta** [comment]
+1

**Pull request merged**
