### PR TITLE
New HCalTower cleaner including rechits

### PR DESCRIPTION
**Pull request by safarzad**
New module includes rechit filter to be applied in 2016 menus

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
Hi,

You also need to declare it as a plugin using the Fw macros.

**Comment by safarzad** [comment]
I do not know what is Fw macros

**Comment by safarzad** [comment]
it is only a new module that if it is in cmssw we will be able to go further and create a JIRA ticket for HLT cfg to use this module in 2016.

**Comment by Martin-Grunewald** [comment]
You will not be able to use it with cmsRun if it is not declared as a plugin:
Add it to https://github.com/cms-sw/cmssw/blob/CMSSW_8_0_X/HLTrigger/JetMET/plugins/SealModule.cc - see there how this is done for the other modules.
(and read up on the FwEDM twikis on how to declare new plugins).

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Pull request merged**
