### PR TITLE
 Update the HLT customisation for running over 2018 data (11.2.x)

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Update the HCAL customisation for running the latest GRun HLT menu over 2018 data (and MC), with the Phase-0 HCAL barrel.

#### PR validation:

Check that the GRun menu can be run over 2018 data.
#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Backport of #33133

### CODE REVIEW

**Comment by fwyzard** [comment]
type bug-fix

**Comment by fwyzard** [comment]
backport #33133

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
+hlt

**Comment by qliphy** [comment]
+1

**Pull request merged**
