### PR TITLE
Removed unneeded dependency on rootminuit2

### PR DESCRIPTION
**Pull request by Dr15Jones**

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
The header that was truncated came from cvmfs so it looks like a problem there.

**Comment by Dr15Jones** [comment]
please test

**Comment by slava77** [comment]
@cmsbuild please test
I'm guessing that a part of last attempt failures was due to this PR being far ahead of the IB.

**Comment by Dr15Jones** [comment]
Weird, don't know why when I built it the symbols were found. Given that BSFitter.cc explicitly asks for Minuit2 items, I think we should keep the dependency.

**Pull request closed without merging**
