### PR TITLE
Pythia8 particlegun fix

### PR DESCRIPTION
**Pull request by smrenna**
fix bug in Py8EGun so that antiparticle has opposite direction to the first particle.

### CODE REVIEW

**Comment by lgray** [comment]
@smrenna you need to do: 
```
git fetch CMSSW_7_6_X:CMSSW_7_6_X
git rebase -i --onto CMSSW_7_6_X pythia8-particlegun-fix~3 pythia8-particlegun-fix
``` 
and then submit this PR.

**Comment by lgray** [comment]
@smrenna Actually you need to do something a little more complicated because of the merge commit in the middle. Hold on.

**Comment by smrenna** [comment]
Yah, I didn't know how to remove the middle part of the "3" requests.

**Comment by lgray** [comment]
@smrenna 
You need to do:
```
git fetch CMSSW_7_6_X:CMSSW_7_6_X
git checkout pythia8-particlegun-fix
git checkout -b pythia8-particlegun-fix-bak
git checkout pythia8-particlegun-fix
git reset --hard  a1d17c3
git cherry-pick dd44640
git push my-cmssw pythia8-particlegun-fix -f
```

**Comment by lgray** [comment]
@smrenna please check on the github website for recipe, had to edit something after I sent it.

**Comment by smrenna** [comment]
Konsole output
cmslpc37:src->git fetch CMSSW_7_6_X:CMSSW_7_6_X
ssh: Could not resolve hostname CMSSW_7_6_X: Name or service not known
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

This is my starting point:

Konsole output

cmslpc37:src->git branch
  CMSSW_7_4_X
  from-CMSSW_7_4_1_patch1
* pythia8-particlegun-fix

What if I just checkout a CMSSW_7_6_X release and start over?

--S

**Comment by lgray** [comment]
@smrenna updated recipe sorry for typo

**Comment by slava77** [comment]
considering it's a 3-line change,
I suggest to just re-implement it in 76X.

		--slava

**Comment by slava77** [comment]
-1
replaced by #10670

**Comment by Martin-Grunewald** [comment]
-1
(please close this PR as it seems no longer active)

**Pull request closed without merging**
