### PR TITLE
Run3-gex160Y Backport of #41464 to CMSSW version 13_1_X which contains a bug fix for ZDC simulation geometry

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Backport of #41464 to CMSSW version 13_1_X which contains a bug fix for ZDC simulation geometry

#### PR validation:

Use the runTheMatrix test workflows

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport of #41464

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by perrotta** [comment]
backport of https://github.com/cms-sw/cmssw/pull/41480

**Comment by perrotta** [comment]
@cms-sw/upgrade-l2 CMSSW_13_1_0 will be cut next week, and it is supposed to be used for the production of Phase2 samples: could you please have a look at this PR, and sign it if you agree with it?

**Comment by bsunanda** [comment]
@srimanob Please approve this

**Comment by srimanob** [comment]
+Upgrade

**Comment by srimanob** [comment]
Thanks @perrotta 
Looking on this PR, it is on Run-3 geometry only. However, we can merge it.

**Comment by perrotta** [comment]
> Looking on this PR, it is on Run-3 geometry only. However, we can merge it.

Indeed...
@bsunanda why are you backporting the fix for the Phase2 geometry in 13_0_X and not in 13_1_X? I would have rather exepected the contrary, since the Phase2 MC production is foreseen with 13_1_X

**Comment by srimanob** [comment]
Hi @perrotta 
For Phase-2, the related PR (#41480 ) is merged and appear in 13_1_0_pre4,
https://github.com/cms-sw/cmssw/releases/CMSSW_13_1_0_pre4

**Comment by perrotta** [comment]
+1

**Pull request merged**
