### PR TITLE
Remove old FPIX; make New FPIX default, and update FPIX materials

### PR DESCRIPTION
**Pull request by schneiml**
This PR is #15986 + #16148 .
- #15986 moves the new FPIX into the place of the old one, and removes remainders of the old one. This includes deleting some ancient geometries that used the old FPIX. See discussion there. (Rebased to CMSSW_8_1_X_2016-10-07-2300 to ease testing.)
- #16148 updates the FPIX xml files that were moved around above, leading to conflicts. I cherry-picked the single commit here and fixed the conflicts, this seems to be the easiest way.
#15986 can still be disputed; in that case only #16148 should be merged. But if we want both changes in, this is the PR to use.

(also @tmulholland , @veszpv , @friccita )

### CODE REVIEW

**Comment by makortel** [comment]
Just thinking out loud: if this cleanup is not strictly needed for 81X, how about postponing it to 90X? In case of problems we would have more time to fix.

**Comment by davidlange6** [comment]
Hi @makortel - I don't agree with leaving this mess around for 8_1_0 (or later). Its not good that we've coupled cleanup and real changes. It would be far easier to do things one by one...

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by davidlange6** [comment]
Hi @schneiml - could you rebase. thx

**Comment by schneiml** [comment]
Rebased. The original idea was to merge this *instead* of  #16148 , and I added that commit in here... Anyways, rebased now, all relevant files stay identical.

**Comment by davidlange6** [comment]
please test
(the best way to ensure that superseded PRs are not merged is to close them)

**Pull request merged**
