### PR TITLE
Fix flat vtx generator

### PR DESCRIPTION
**Pull request by amartelli**
Fix the distribution of the time coordinate for FlatEvtVtxGenerator.
This PR makes the T value independent from the Z one, allowing the generation of events with displaced vertex in space and not in time, and also vice versa.

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by amartelli** [comment]
Following suggestion from @civanch added extended comment in the constructor and python config.
Also the default parameters for T variable are set to restore the Z and T correlation, but now the user has the flexibility to change independently Z and T, and deal with the correlation between the two.

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by civanch** [comment]
Differences in WFs 7.3 and 8.0 are expected

**Comment by davidlange6** [comment]
hi @amartelli @civanch - i'm not sure I follow "allowing the generation of events with displaced vertex in space and not in time" - this capability would seem to have already been possible given the TimeOffset parameter of the old implementation. 

The capability added is to allow the user to specify a time range (eg, Tmax-Tmin) that is not physically correct given the z range (and assuming the beams are along z and traveling at the speed of light). I'm not really sure the motivation for this. While it could be an option, I don't think it should be the default for this module.

**Comment by civanch** [comment]
hi @davidlange6 , flat generator is a specific one. For Gaussian sampling of Z and T are not correlated, only RMS are the same (if we speak about T*c_light) and it is a real distribution when two Gaussian beams collide.  If two flat beam collide we will have triangle distribution in space and the time distribution will be correlated with sampled Z.   So, the flat generator is not a distribution for collided beams. It may be beam-gas or may be used for some studies, for example,  to be biased by real space/time distribution. If it is use-case dependent, then  user should compute time limits for the use-case and define time limits as parameters of the class. What we do not add is the Z/T correlation parameter, the reason - not obvious how to introduce it in a general case.

**Comment by amartelli** [comment]
Hi @davidlange6 
the problem was line https://github.com/cms-sw/cmssw/pull/21000/files#diff-2a5a0f7f34087f59655d0c64aeb47db9L52
With this, it was not possible to generate a vertex displaced in Z (as example minZ = +10 and maxZ = +10) keeping the time at zero. One could have set TimeOffset = -10 to correct for this, but no instructions were specified.
I discovered this because I am studying the time of the reconstructed showers in the calorimeters and after setting vtxZ = +10 the time did not correlate at all with the tof from the vertex, because it got also shifted in time by 10ns*c.

I understand your concerns of the needed correlation between Z and T, there is a clear statement in both the constructor and the python configuration to warn about this.  Also, for a proper correlation, minT and maxT should depend on (MinZ - MaxZ)/2 rather than on the absolute value...
And the default parameters in the phyton for T are such to correlate vtxT with vtxZ in the assumption of minZ = -5.3 maxZ = 5.3 (as it was before the PR and with the default parameters)

Anyway my assumption is that FlatVertexGenerator is used for studies and not for physics production, so people changing the parameters are supposed to know what they are doing.

**Comment by davidlange6** [comment]
ok - I see the point now. Thanks

**Comment by davidlange6** [comment]
merge

**Pull request merged**
