### PR TITLE
Update TSG tests and Relval Steps to use new run3_[hlt|data]_relval GTs

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
#### PR description:

Update TSG tests and Relval Steps to use new run3_[hlt|data]_relval GTs

#### PR validation:

TSG tests

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Backport of #37184 needed for TSG/HLT use in 12_3

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
backport of #37184

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by AdrianoDee** [comment]
+upgrade
Backport of https://github.com/cms-sw/cmssw/pull/37184

**Comment by kskovpen** [comment]
+pdmv

**Comment by qliphy** [comment]
+1

**Pull request merged**
