### PR TITLE
XMLConfigReader and XmlConfigReader cleanup in L1T 

### PR DESCRIPTION
**Pull request by davidlange6**
rearrange xerces use in L1T packages to better handle memory management. Fixes errors in workflow 136.7321 currently in the IBs (hopefully doesn't cause others)

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by mulhearn** [comment]
This looks fine to me, but we should have @kkotov run some tests to make sure no problem with O2O is introduced.

**Comment by rekovic** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
