### PR TITLE
IsolatedBunchesTrackingMonitor

### PR DESCRIPTION
**Pull request by fioriNTU**
Adding a clone of SiStripMonitorTrack in order to monitor data from IsolatedBunches trigger.

### CODE REVIEW

**Comment by fioriNTU** [comment]
@dmitrijus could you please start the test on it?

**Comment by dmitrijus** [comment]
+1

**Comment by fioriNTU** [comment]
What "DAS error" means? The relevant log file is empty. Is this related to a Data Aggregation System error? In this case, could you please retrigger the test as soon as possible? (also for #15345)

**Comment by boudoul** [comment]
das error means that the input files used (here the files corresonding to the run 182124 used for the WF 140.53) was not found - sometimes DAS failed to find and therefore the corresponding WFs was not run (and therefore not tested with your code) - Indeed the usual next step after a das error is to retrigger a test

**Comment by boudoul** [comment]
I believe this is the failure which can be temporary ignored ( according to #15370), could we proceed with this request ? the corresponding one in 81X has been merged -  thanks all

**Comment by fioriNTU** [comment]
@dmitrijus can we go ahead with this please?

**Comment by dmitrijus** [comment]
I will push it at the ORP, should be merged today / tomorrow.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
