### PR TITLE
HLT update to L1T menu v5 incl. GT (80X)

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
HLT update to L1T menu v5 incl. GT (80X)
This PR includes the GT changes from #13893 plus the changes as in #14077
It also includes the previous HLT PR #13862 as that is not yet integrated, thus requiring again all signatures.
Rebased to CMSSW_8_0_X at 14:10 April 16th, as  #13862 and #13893  are now integrated, so some fewer signatures!

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by fwyzard** [comment]
@Martin-Grunewald if you rebase the branch on top of the latest CMSSW_8_0_X, it should clean up some history and get rid of the core, pdmv and l1 signatures.

**Comment by Martin-Grunewald** [comment]
Good point - done!

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by Martin-Grunewald** [comment]
@mmusich 
Please also sign this one (80X)
Thanks!

**Comment by mmusich** [comment]
+1

**Comment by mmusich** [comment]
@Martin-Grunewald would you mind updating autoCond in this PR as in https://github.com/cms-sw/cmssw/pull/14152? That's needed to fix the issues reported in https://github.com/cms-sw/cmssw/pull/13954#issuecomment-211980186. Unfortunately the new Global Tags have already the v5 menu in it, therefore won't work without the latest update of the HLT menu

**Comment by davidlange6** [comment]
+1

**Comment by davidlange6** [comment]
@Martin-Grunewald - whoops -seems that there is a merge conflict now - can you have a look?

**Comment by mmusich** [comment]
@davidlange6 I would naively say that the merge conflict stems from https://github.com/cms-sw/cmssw/pull/14152 just merged

**Comment by davidlange6** [comment]
probably

**Comment by Martin-Grunewald** [comment]
Really! Great! Work!

**Comment by Martin-Grunewald** [comment]
rebased to 8_0_X to fix merge conflict

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by Martin-Grunewald** [comment]
@mmusich 
Please sign!
Thanks!

**Comment by mmusich** [comment]
+1

**Comment by Martin-Grunewald** [comment]
@mmusich 

It looks to me that all failures are real-data only and GT related:

```
----- Begin Fatal Exception 19-Apr-2016 23:38:34 CEST-----------------------
An exception of category 'NoRecord' occurred while
   [0] Processing run: 256677 lumi: 380 event: 397024298
   [1] Running path 'HLT_DiPFJet15_FBEta3_NoCaloMatched_v1'
   [2] Calling event method for module L1FastjetCorrectorProducer/'hltAK4PFFastJetCorrector'
Exception Message:
No "JetCorrectionsRecord" record found in the EventSetup for synchronization value
Run: 256677 LuminosityBlock: 380 Event: 0 Time: 6195459379240747776
 Please add an ESSource or ESProducer that delivers such a record.
----- End Fatal Exception -------------------------------------------------
```

What has changed in the real-data GTs? It seems the snapshotTime is wrongly set?

**Comment by Martin-Grunewald** [comment]
I think the new GTs are bad - the IB real-data relvals with return code 16640 all show the
above error: https://cms-sw.github.io/relvalLogDetail.html#slc6_amd64_gcc530;CMSSW_8_1_X_2016-04-19-2300
I am going to revert  #14152...

**Comment by Martin-Grunewald** [comment]
please test

**Comment by mmusich** [comment]
@Martin-Grunewald yes, apologies, it's my fault with the global snapshot time. Fixing it, no need to revert.

**Comment by davidlange6** [comment]
Hi Marco
Thanks- let us know (via a PR I guess) when done

**Comment by Martin-Grunewald** [comment]
@davidlange6 
In the meantime you could integrate #14106

**Comment by davidlange6** [comment]
Ok I did things in the other order, so yet again a rebase is needed

**Comment by Martin-Grunewald** [comment]
You really seem to think this is funny. What the hell!

**Comment by davidlange6** [comment]
I think it's funny? I'm instead annoyed at the way people have strongly coupled unrelated stuff...

**Comment by Martin-Grunewald** [comment]
please test

**Comment by davidlange6** [comment]
i guess its the different commits with the same change that is creating the mess. For next time, git cherry-pick is your friend.

**Comment by Martin-Grunewald** [comment]
OK, thanks for integrating!

**Comment by mmusich** [comment]
+1

**Pull request merged**
