### PR TITLE
Consolidate nuclear interactions files for fastsim 

### PR DESCRIPTION
**Pull request by davidlange6**
Goal - to reduce open files in cmsRun

@smuzaffar - this needs all the data files currently in data-FastSimulation-MaterialEffects to be replaced by this file:
 cmsdev02:/build/dlange/CMSSW_9_2_X_2017-05-11-1100/src/FastSimulation/MaterialEffects/data/NuclearInteractions.root

### CODE REVIEW

**Comment by civanch** [comment]
@davidlange6 , @ssekmen , probably this problem is the next argument to try switch to FTF FastSim nuclear interaction. Here usage of root for storage of intermediate data is, at least, a strange patern.

**Comment by davidlange6** [comment]
if we can rm -r these files that is even better!

**Comment by smuzaffar** [comment]
@iahmad-khan , can you please takecare of data-FastSimulation-MaterialEffects

**Comment by smuzaffar** [comment]
please test with cms-sw/cmsdist#3038

**Pull request merged**
