### PR TITLE
Phase2-hgx334B Extend some of the calling sequences of Geometry to include zside which is needed to treat correctly cassette shifts

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Extend some of the calling sequences of Geometry to include zside which is needed to treat correctly cassette shifts. There were several internal calls which were wrong in earlier versions. This may cause differences in predictions. Now all internal calls are checked and corrected.

#### PR validation:

Use the runTheMatrix test workflows

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
+geometry

**Comment by civanch** [comment]
+1

**Comment by bsunanda** [comment]
@clacaputo, @mandrenguyen, @emanueleusai, @ahmad3213, @AdrianoDee, @srimanob Please approve this PR. Without this PR we cannot complete the full functionality of the V17 geometry of HGCal

**Comment by mandrenguyen** [comment]
+reconstruction
No diffs in comparisons.
Changes to reco modules consist basically of a new flag for zside

**Comment by srimanob** [comment]
+Upgrade

**Comment by emanueleusai** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
