### PR TITLE
Fix crashing hcalcalib

### PR DESCRIPTION
**Pull request by DryRun**
This PR is for fixing a crash in online DQM, not intended to merge (I'll merge the relevant commits into that branch later). The crash is once again due to calibration channels being included in QIE10DigiCollection and QIE11DigiCollection. I've added more "if" statements to protect against these.

### CODE REVIEW

**Comment by dmitrijus** [comment]
@DryRun Please close the PR if it is not intended to be merged.
If you are **just** making a PR for online DQM (not recommended), please press button "close" right after you create a PR. Saves us a lot of work.

**Comment by DryRun** [comment]
@dmitrijus OK, thank you for the information.

**Comment by threus** [comment]
@DryRun, coming back to this later - why not to merge it? Is it fixed somewhere else already? If not, it means we (online DQM) will always have to include this PR on top of CMSSW92X (see p5tagCollector twiki)..

**Comment by DryRun** [comment]
Hi @threus  -- unfortunately, things are held up a bit by #18841, which has been under discussion for several weeks now. The changes in 19058 unfortunately do not factorize with 18841. So, please correct me if I'm wrong, but my understanding is that 18841 has to merge first, and then we can PR and merge the additional changes in 19058.

**Comment by threus** [comment]
@DryRun thanks. In the p5TagCollector it's written that this PR replaces 18841, but if not, then we wait until 18841 is merged before testing it on playback. I added this note to the p5tagCollector, to keep in mind.

**Pull request closed without merging**
