### PR TITLE
[124X] Fix PPS timing detectors record and tag names for PCL, fix further bugs for SAMPIC wf

### PR DESCRIPTION
**Pull request by tvami**
#### PR description:

See https://github.com/cms-sw/cmssw/pull/38981/ and https://github.com/cms-sw/cmssw/pull/38893

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport of https://github.com/cms-sw/cmssw/pull/38981 and https://github.com/cms-sw/cmssw/pull/38893

### CODE REVIEW

**Comment by tvami** [comment]
type ctpps,bugfix

**Comment by tvami** [comment]
urgent 
 * needed for data taking

**Comment by tvami** [comment]
backport of https://github.com/cms-sw/cmssw/pull/38981

**Comment by tvami** [comment]
backport of https://github.com/cms-sw/cmssw/pull/38893

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
@cmsbuild , please abort

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
@cmsbuild , please test
 * the error is unrelated

**Comment by ChrisMisan** [comment]
@tvami can you explain changing the tag to PPSDiamondSampicCalibration_pcl?

**Comment by tvami** [comment]
> @tvami can you explain why the tag was changed to PPSDiamondSampicCalibration_pcl?

To be in line with all the stuff above, both the HPTDC and the alignment have this structure if you look just above a few lines

**Comment by malbouis** [comment]
+1

**Comment by tvami** [comment]
@cms-sw/orp-l2 it seems the IB with the master version of this PR is running fine

**Comment by qliphy** [comment]
+1

**Pull request merged**
