### PR TITLE
Updated SimProducer for ECAL

### PR DESCRIPTION
**Pull request by civanch**
#### PR description:
This PR intended to fix issue #36256. SimProducer used for analysis of hits in ECAL has minor modification. Also InputTag is used instead of string for generatorSmearing label to remove warning in the WF 101.0.

#### PR validation:
WFs: 101.0, 102.0, 1306.0

#### if this PR is a backport please specify the original PR and why you need to backport that PR:
no

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by perrotta** [comment]
test parameters:
- workflows = 101.0, 102.0

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
Uhm, I started the tests with relvals 101.0, 102.0 to test them threaded, but I think that https://github.com/cms-sw/cms-bot/pull/1666/files still prevents it. Let retry with a hack

**Comment by perrotta** [comment]
please abort

**Comment by perrotta** [comment]
test parameters:
- workflows = 101.0, 102.0
- pull_request = https://github.com/cms-sw/cms-bot/pull/1670

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
@smuzaffar , I tried to run the tests together with a "dummy" [cms-bot PR](https://github.com/cms-sw/cms-bot/pull/1670) that reverts https://github.com/cms-sw/cms-bot/pull/1666, with the intention of testing this fix with 101 and 102 run multithread.
I am not sure that it actually succeded: do you know how can I check it?

**Comment by smuzaffar** [comment]
please test
@perrotta , for PR we run tests in non-threading mode that is why these wf didnot fail. I have updated https://github.com/cms-sw/cmssw/pull/36297#issuecomment-982935306 to enable threading tests and added `101,102` to be tested for threaded relvals.

**Comment by perrotta** [comment]
Thank you @smuzaffar , this is nice to know!

**Comment by perrotta** [comment]
+1
- Threading tests succed also for wf 101 and 102 now

**Pull request merged**
