### PR TITLE
[10_6_X] Fixes for XRootD 5.x

### PR DESCRIPTION
**Pull request by iarspider**
#### PR description:

Companion PR for https://github.com/cms-sw/cmsdist/pull/8484 - adopt to XRootD API changes

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport of #34991, #35455, #38309, #30787, #30262, and #26789

### CODE REVIEW

**Comment by iarspider** [comment]
please test with https://github.com/cms-sw/cmsdist/pull/8484

**Comment by smuzaffar** [comment]
test parameters:
- pull_request = cms-sw/root#178, cms-sw/cmsdist#8484

**Comment by smuzaffar** [comment]
please test

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
"test_occi_std_length" is also failing in IBs

**Comment by smuzaffar** [comment]
@makortel @osschar these changes are needed to backport xrootd 5 in to CMSSW 10.6. Can you please review and if looks good then we can integrate 
- https://github.com/cms-sw/root/pull/178 
- https://github.com/cms-sw/cmsdist/pull/8484

**Comment by makortel** [comment]
I would have preferred cherry-picking the commits rather than copying the `XrdSource.cc` directly. Now it also backports https://github.com/cms-sw/cmssw/pull/38309, https://github.com/cms-sw/cmssw/pull/30787, https://github.com/cms-sw/cmssw/pull/30262, and https://github.com/cms-sw/cmssw/pull/26789. They are all ok, but could you @iarspider add those in the PR description?

**Comment by makortel** [comment]
+core

**Comment by makortel** [comment]
@smuzaffar Just to be explicit, I leave the https://github.com/cms-sw/root/pull/178 and https://github.com/cms-sw/cmsdist/pull/8484 for you to sign.

**Comment by iarspider** [comment]
@makortel this was the initial attempt, but the code between 10_6 (target release for this change) and 12_1 (target release for #34991) diverged too much for cherry-picking.

**Comment by smuzaffar** [comment]
@makortel , sure I will take care of cmsdist/root PRs

**Comment by rappoccio** [comment]
+1

Externals are updating, we need this to go through IBs to clear the unsuccessful checks.

**Comment by rappoccio** [comment]
merge

**Pull request merged**
