### PR TITLE
Fix for L1T emulator DQM client crash - PRv2

### PR DESCRIPTION
**Pull request by thomreis**
This fixes an exception due to a missing L1TCaloParamsO2ORcd record in the L1T emulator DQM client.

### CODE REVIEW

**Comment by thomreis** [comment]
please test

**Comment by thomreis** [comment]
type bugfix

**Comment by thomreis** [comment]
please test

**Comment by fabiocos** [comment]
@dmitrijus, @jfernan2 could you please check and sign in case?

**Comment by jfernan2** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
