### PR TITLE
TrackerAlignment PI: Support pixel only comparisons

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

It is sometimes more convenient and faster (especially for the PCL) to compare two Tracker Alignment payloads only in the Pixel components. This PR supports this option by adding a new template to `TrackerAlignmentCompareAll` in order to limit the number of IDs looked at (if `doOnlyPixel` those that have subdetId > 2 are discarded). 
Also added a unit test for the functionality.

#### PR validation:

Privately run the unit test, successfully. 

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

N/A

### CODE REVIEW

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by mmusich** [comment]
> -1
> Failed Tests: RelVals-INPUT

aah, I was starting to miss these

**Comment by tvami** [comment]
+1
 * dedicated unit test passed
 * relval input test failure are not relevant

**Comment by perrotta** [comment]
+1

**Comment by perrotta** [comment]
merge

**Pull request merged**
