### PR TITLE
fix hdr GeneratorInterface/Herwig7Interface

### PR DESCRIPTION
**Pull request by mrodozov**
Fix headers related to #15248. 
This header HepMCTemplate.h had only one include and one template definition, and was included only by 
Herwig7Interface.h . ThePEG/Vectors/HepMCTraits.h itself did not included some types (like map) used by HepMCTemplate and since ThePEG is an external, instead of changing the external headers or requesting changes (or applying a patch) I just moved the entire header content into Herwig7Interface as shortcut. Let me know if that is NOT ok.

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by alberto-sanchez** [comment]
please test workflow 511.0

**Comment by alberto-sanchez** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
