### PR TITLE
Clean up BuildFiles under HeterogeneousCore/

### PR DESCRIPTION
**Pull request by fwyzard**
Clean up BuildFile.xml filea with `xmllint --format`.

### CODE REVIEW

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
+1

**Comment by makortel** [comment]
@smuzaffar I wonder if we could make 

> Clean up BuildFile.xml files with `xmllint --format`.

(or something along it) part of code-checks?

**Comment by silviodonato** [comment]
+1

**Pull request merged**
