### PR TITLE
either remove or make a bunch of configuration fragments compile

### LINKED ISSUE #45106: Few configuration fragments don't compile
The following script shows that few cfi fragments are broken in `CMSSW_14_1_X_2024-05-29-2300`:

```bash
#!/bin/bash

# Array of module paths
modules=(
    "DQM.EcalMonitorDbModule.EcalCondDBWriter_cfi"
    "Geometry.ForwardCommonData.hfnoseV15ParametersInitialization_cfi"
    "Geometry.HcalEventSetup.HcalTrigTowerGeometry_cfi"
    "JetMETCorrections.TauJet.TCRecoTauDiscriminationAlgoComponent_cfi"
    "RecoMET.METPUSubtraction.mvaPFMET_leptons_cfi"
    "RecoTauTag.RecoTau.PFRecoTauProducer_cfi"
    "RecoTracker.MkFit.mkFitHitConverter_cfi"
    "L1Trigger.L1TCalorimeter.caloStage2Params_2016_v0.0_cfi"
    "DQM.SiStripMonitorClient.SiStripDQMRecoConfigOfflineGlobalRunCAF_cfi"
    "RecoParticleFlow.PFProducer.pfGsfElectronCiCSelector_cfi"
    "SimGeneral.MixingModule.mix_2015_25nsLowPU_matchData_PoissonOOTPU_cfi"
)

# Loop over the array and execute the python commands
for module in "${modules[@]}"; do
    echo "****************************************************************"
    python3 -m "$module"
done
echo "****************************************************************"
```

gives:

```console
****************************************************************
Traceback (most recent call last):
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el9_amd64_gcc12/external/python3/3.9.14-b98669a1dd7ad6f9a9402f3cf1f9d11c/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el9_amd64_gcc12/external/python3/3.9.14-b98669a1dd7ad6f9a9402f3cf1f9d11c/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el9_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-05-29-2300/src/DQM/EcalMonitorDbModule/python/EcalCondDBWriter_cfi.py", line 11, in <module>
    from DQM.EcalMonitorTasks.PNDiodeTask_cfi import ecalPnDiodeTask
ImportError: cannot import name 'ecalPnDiodeTask' from 'DQM.EcalMonitorTasks.PNDiodeTask_cfi' (/cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el9_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-05-29-2300/src/DQM/EcalMonitorTasks/python/PNDiodeTask_cfi.py)
****************************************************************
Traceback (most recent call last):
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el9_amd64_gcc12/external/python3/3.9.14-b98669a1dd7ad6f9a9402f3cf1f9d11c/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el9_amd64_gcc12/external/python3/3.9.14-b98669a1dd7ad6f9a9402f3cf1f9d11c/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el9_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-05-29-2300/src/Geometry/ForwardCommonData/python/hfnoseV15ParametersInitialization_cfi.py", line 3, in <module>
    from Geometry.HGCalCommonData.hgcalEEV15ParametersInitialization_cfi import *
ModuleNotFoundError: No module named 'Geometry.HGCalCommonData.hgcalEEV15ParametersInitialization_cfi'
****************************************************************
Traceback (most recent call last):
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el9_amd64_gcc12/external/python3/3.9.14-b98669a1dd7ad6f9a9402f3cf1f9d11c/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el9_amd64_gcc12/external/python3/3.9.14-b98669a1dd7ad6f9a9402f3cf1f9d11c/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el9_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-05-29-2300/src/Geometry/HcalEventSetup/python/HcalTrigTowerGeometry_cfi.py", line 3, in <module>
    import Geometry.HcalEventSetup.hcalTrigTowerGeometry_cfi
ModuleNotFoundError: No module named 'Geometry.HcalEventSetup.hcalTrigTowerGeometry_cfi'
****************************************************************
Traceback (most recent call last):
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el9_amd64_gcc12/external/python3/3.9.14-b98669a1dd7ad6f9a9402f3cf1f9d11c/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el9_amd64_gcc12/external/python3/3.9.14-b98669a1dd7ad6f9a9402f3cf1f9d11c/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el9_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-05-29-2300/src/JetMETCorrections/TauJet/python/TCRecoTauDiscriminationAlgoComponent_cfi.py", line 3, in <module>
    from RecoTauTag.RecoTau.TCTauAlgoParameters_cfi import *
ModuleNotFoundError: No module named 'RecoTauTag.RecoTau.TCTauAlgoParameters_cfi'
****************************************************************
Traceback (most recent call last):
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el9_amd64_gcc12/external/python3/3.9.14-b98669a1dd7ad6f9a9402f3cf1f9d11c/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el9_amd64_gcc12/external/python3/3.9.14-b98669a1dd7ad6f9a9402f3cf1f9d11c/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el9_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-05-29-2300/src/RecoMET/METPUSubtraction/python/mvaPFMET_leptons_cfi.py", line 66, in <module>
    from RecoTauTag.Configuration.HPSPFTaus_cff import hpsPFTauDiscriminationByLooseCombinedIsolationDBSumPtCorr3Hits
ImportError: cannot import name 'hpsPFTauDiscriminationByLooseCombinedIsolationDBSumPtCorr3Hits' from 'RecoTauTag.Configuration.HPSPFTaus_cff' (/cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el9_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-05-29-2300/src/RecoTauTag/Configuration/python/HPSPFTaus_cff.py)
****************************************************************
Traceback (most recent call last):
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el9_amd64_gcc12/external/python3/3.9.14-b98669a1dd7ad6f9a9402f3cf1f9d11c/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el9_amd64_gcc12/external/python3/3.9.14-b98669a1dd7ad6f9a9402f3cf1f9d11c/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el9_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-05-29-2300/src/RecoTauTag/RecoTau/python/PFRecoTauProducer_cfi.py", line 1, in <module>
    from RecoTauTag.RecoTau.pfRecoTauProducerDef_cfi import pfRecoTauProducerDef
ModuleNotFoundError: No module named 'RecoTauTag.RecoTau.pfRecoTauProducerDef_cfi'
****************************************************************
Traceback (most recent call last):
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el9_amd64_gcc12/external/python3/3.9.14-b98669a1dd7ad6f9a9402f3cf1f9d11c/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el9_amd64_gcc12/external/python3/3.9.14-b98669a1dd7ad6f9a9402f3cf1f9d11c/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el9_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-05-29-2300/src/RecoTracker/MkFit/python/mkFitHitConverter_cfi.py", line 3, in <module>
    from RecoTracker.MkFit.mkFitHitConverterDefault_cfi import mkFitHitConverterDefault as _mkFitHitConverterDefault
ModuleNotFoundError: No module named 'RecoTracker.MkFit.mkFitHitConverterDefault_cfi'
****************************************************************
/cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el9_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-05-29-2300/external/el9_amd64_gcc12/bin/python3: Error while finding module specification for 'L1Trigger.L1TCalorimeter.caloStage2Params_2016_v0.0_cfi' (ModuleNotFoundError: No module named 'L1Trigger.L1TCalorimeter.caloStage2Params_2016_v0')
****************************************************************
Traceback (most recent call last):
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el9_amd64_gcc12/external/python3/3.9.14-b98669a1dd7ad6f9a9402f3cf1f9d11c/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el9_amd64_gcc12/external/python3/3.9.14-b98669a1dd7ad6f9a9402f3cf1f9d11c/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el9_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-05-29-2300/src/DQM/SiStripMonitorClient/python/SiStripDQMRecoConfigOfflineGlobalRunCAF_cfi.py", line 5, in <module>
    from DQM.SiStripMonitorClient.RecoForDQM_Cosmic_cff import *
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el9_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-05-29-2300/src/DQM/SiStripMonitorClient/python/RecoForDQM_Cosmic_cff.py", line 11, in <module>
    siPixelDigis.InputLabel = 'source'
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el9_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-05-29-2300/src/FWCore/ParameterSet/python/Modules.py", line 324, in __setattr__
    self.__addParameter(name, value)
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el9_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-05-29-2300/src/FWCore/ParameterSet/python/Modules.py", line 290, in __addParameter
    raise TypeError(name+" does not already exist, so it can only be set to a cms.EDProducer or cms.EDAlias")
TypeError: InputLabel does not already exist, so it can only be set to a cms.EDProducer or cms.EDAlias
****************************************************************
Traceback (most recent call last):
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el9_amd64_gcc12/external/python3/3.9.14-b98669a1dd7ad6f9a9402f3cf1f9d11c/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el9_amd64_gcc12/external/python3/3.9.14-b98669a1dd7ad6f9a9402f3cf1f9d11c/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el9_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-05-29-2300/src/RecoParticleFlow/PFProducer/python/pfGsfElectronCiCSelector_cfi.py", line 57, in <module>
    electronsCiCLoose = cms.EDFilter("EleIdCutBased",
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el9_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-05-29-2300/src/FWCore/ParameterSet/python/Modules.py", line 173, in __init__
    super(EDFilter,self).__init__(type_,*arg,**kargs)
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el9_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-05-29-2300/src/FWCore/ParameterSet/python/Modules.py", line 137, in __init__
    super(_Module,self).__init__(type_,*arg,**kargs)
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el9_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-05-29-2300/src/FWCore/ParameterSet/python/Mixins.py", line 397, in __init__
    super(_TypedParameterizable,self).__init__(*arg,**kargs)
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el9_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-05-29-2300/src/FWCore/ParameterSet/python/Mixins.py", line 186, in __init__
    self.__setParameters(kargs)
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el9_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-05-29-2300/src/FWCore/ParameterSet/python/Mixins.py", line 268, in __setParameters
    self.__addParameter(name, value)
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el9_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-05-29-2300/src/FWCore/ParameterSet/python/Mixins.py", line 252, in __addParameter
    self.__raiseBadSetAttr(name)
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el9_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-05-29-2300/src/FWCore/ParameterSet/python/Mixins.py", line 307, in __raiseBadSetAttr
    raise TypeError(name+" does not already exist, so it can only be set to a CMS python configuration type")
TypeError: electronIDType does not already exist, so it can only be set to a CMS python configuration type
****************************************************************
Traceback (most recent call last):
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el9_amd64_gcc12/external/python3/3.9.14-b98669a1dd7ad6f9a9402f3cf1f9d11c/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el9_amd64_gcc12/external/python3/3.9.14-b98669a1dd7ad6f9a9402f3cf1f9d11c/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el9_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-05-29-2300/src/SimGeneral/MixingModule/python/mix_2015_25nsLowPU_matchData_PoissonOOTPU_cfi.py", line 6, in <module>
    mix.input.nbPileupEvents.probFunctionVariable = cms.vint32(0,1,2,3,4,5,6,7,8,9,10,11,12),
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el9_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-05-29-2300/src/FWCore/ParameterSet/python/Mixins.py", line 291, in __setattr__
    self.__dict__[name].setValue(value)
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el9_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-05-29-2300/src/FWCore/ParameterSet/python/Mixins.py", line 656, in setValue
    self.extend(v)
  File "/cvmfs/cms-ib.cern.ch/sw/x86_64/week1/el9_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-05-29-2300/src/FWCore/ParameterSet/python/Mixins.py", line 624, in extend
    raise TypeError("wrong type being extended to container "+self._labelIfAny())
TypeError: wrong type being extended to container vint32
****************************************************************
```

spotted from confDB parsing logs.

### PR DESCRIPTION
**Pull request by mmusich**
fixes https://github.com/cms-sw/cmssw/issues/45106

#### PR description:

Title says it all, either remove or adapt a bunch of configuration fragments that currently don't compile

#### PR validation:

```bash
#!/bin/bash -ex

# Array of module paths
modules=(
    "DQM.EcalMonitorDbModule.EcalCondDBWriter_cfi"
    #"Geometry.ForwardCommonData.hfnoseV15ParametersInitialization_cfi" (removed, here)
    #"Geometry.HcalEventSetup.HcalTrigTowerGeometry_cfi" (removed, here)
    #"JetMETCorrections.TauJet.TCRecoTauDiscriminationAlgoComponent_cfi" (removed, here)
    "RecoMET.METPUSubtraction.mvaPFMET_leptons_cfi"
    #"RecoTauTag.RecoTau.PFRecoTauProducer_cfi" (removed https://github.com/cms-sw/cmssw/pull/45191)
    #"RecoTracker.MkFit.mkFitHitConverter_cfi" (removed https://github.com/cms-sw/cmssw/pull/45109)
    "L1Trigger.L1TCalorimeter.caloStage2Params_2016_v0p0_cfi"
    "DQM.SiStripMonitorClient.SiStripDQMRecoConfigOfflineGlobalRunCAF_cfi"
    "RecoParticleFlow.PFProducer.pfGsfElectronCiCSelector_cfi"
    "SimGeneral.MixingModule.mix_2015_25nsLowPU_matchData_PoissonOOTPU_cfi"
)

# Loop over the array and execute the python commands
for module in "${modules[@]}"; do
    echo "****************************************************************"
    python3 -m "$module"
done
echo "****************************************************************"
```

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

N/A

### CODE REVIEW

**Comment by Dr15Jones** [comment]
Thanks!

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by tvami** [comment]
+analysis

**Comment by jfernan2** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by bsunanda** [comment]
-1

**Comment by bsunanda** [comment]
Please do not remove the cfi or cf's in Geometry/ForwardCommonData or Geometry/HcalEventSetup. I shall make them working

**Comment by bsunanda** [comment]
+geometry

**Comment by mmusich** [comment]
@cms-sw/l1-l2 @cms-sw/dqm-l2 kind ping

**Comment by aloeliger** [comment]
+l1

**Comment by tjavaid** [comment]
+1

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
