### PR TITLE
Improve TPSAlgorithm

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

- Initialize member data in match_t. This was spotted by UBSAN.
- Add const where applicable
- Improve copying elements to a vector

#### PR validation:

Code compiles.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
please test

**Comment by aloeliger** [comment]
please test

**Comment by Dr15Jones** [comment]
@cms-sw/l1-l2 ping

**Comment by aloeliger** [comment]
+l1

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
