### PR TITLE
TriggerResultFilters: accept arbitrary Path names

### PR DESCRIPTION
**Pull request by fwyzard**
- accept arbitrary Path names
- rename the internal classes for consistency
- update test files for the new functionality
- prevent segfault if an L1 trigger is used in the expression without passing the L1 results collection

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
+1

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
@nclopezo @ktf    
'please test' seems to no longer work... why, can it be brought back?

**Comment by Martin-Grunewald** [comment]
This PR creates/ or exposes/ a crash:
```
%MSG
%MSG-e FatalSystemSignal:  FSQDiJetAve:fsqHLTOfflineSource  13-Jan-2015 16:44:22 CET Run: 1 Event: 501
A fatal system signal has occurred: segmentation violation
%MSG


A fatal system signal has occurred: segmentation violation
The following is the call stack containing the origin of the signal.
NOTE:The first few functions on the stack are artifacts of processing the signal and can be ignored

#0  0x00000032a40ac61e in waitpid () from /lib64/libc.so.6
#1  0x00000032a403e609 in do_system () from /lib64/libc.so.6
#2  0x00007fa5d85ab847 in TUnixSystem::StackTrace() () from /afs/cern.ch/cms/sw/ReleaseCandidates/vol1/slc6_amd64_gcc491/cms/cmssw/CMSSW_7_4_X_2015-01-13-0700/external/slc6_amd64_gcc491/lib/libCore.so
#3  0x00007fa5cf400895 in sig_dostack_then_abort () from /afs/cern.ch/cms/sw/ReleaseCandidates/vol1/slc6_amd64_gcc491/cms/cmssw/CMSSW_7_4_X_2015-01-13-0700/lib/slc6_amd64_gcc491/libFWCoreServices.so
#4  <signal handler called>
#5  0x00007fa59fbe3214 in FSQ::HandlerTemplate<reco::Track, int>::analyze(edm::Event const&, edm::EventSetup const&, HLTConfigProvider const&, trigger::TriggerEvent const&, edm::TriggerResults const&, \
edm::TriggerNames const&, float) () from /data/CMS0/CMSSW_7_4_X_2015-01-13-0700/lib/slc6_amd64_gcc491/pluginDQMOfflineTrigger.so
#6  0x00007fa59fbc4725 in FSQDiJetAve::analyze(edm::Event const&, edm::EventSetup const&) () from /data/CMS0/CMSSW_7_4_X_2015-01-13-0700/lib/slc6_amd64_gcc491/pluginDQMOfflineTrigger.so
#7  0x00007fa5d9aff901 in edm::stream::EDAnalyzerAdaptorBase::doEvent(edm::EventPrincipal&, edm::EventSetup const&, edm::ActivityRegistry*, edm::ModuleCallingContext const*) () from /afs/cern.ch/cms/sw\
/ReleaseCandidates/vol1/slc6_amd64_gcc491/cms/cmssw/CMSSW_7_4_X_2015-01-13-0700/lib/slc6_amd64_gcc491/libFWCoreFramework.so
#8  0x00007fa5d9af5aff in edm::WorkerT<edm::stream::EDAnalyzerAdaptorBase>::implDo(edm::EventPrincipal&, edm::EventSetup const&, edm::ModuleCallingContext const*) () from /afs/cern.ch/cms/sw/ReleaseCan\
didates/vol1/slc6_amd64_gcc491/cms/cmssw/CMSSW_7_4_X_2015-01-13-0700/lib/slc6_amd64_gcc491/libFWCoreFramework.so
#9  0x00007fa5d9a304a3 in decltype ({parm#1}()) edm::convertException::wrap<bool edm::Worker::doWork<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::Ev\
entPrincipal, (edm::BranchActionType)1>::MyPrincipal&, edm::EventSetup const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context co\
nst*)::{lambda()#1}>(bool edm::Worker::doWork<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::MyPrincipal&, \
edm::EventSetup const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*)::{lambda()#1}) () from /afs/cern.ch/cms/sw/Releas\
eCandidates/vol1/slc6_amd64_gcc491/cms/cmssw/CMSSW_7_4_X_2015-01-13-0700/lib/slc6_amd64_gcc491/libFWCoreFramework.so
#10 0x00007fa5d9a306f5 in bool edm::Worker::doWork<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::MyPrincip\
al&, edm::EventSetup const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*) () from /afs/cern.ch/cms/sw/ReleaseCandidate\
s/vol1/slc6_amd64_gcc491/cms/cmssw/CMSSW_7_4_X_2015-01-13-0700/lib/slc6_amd64_gcc491/libFWCoreFramework.so
#11 0x00007fa5d9a3681e in decltype ({parm#1}()) edm::convertException::wrap<void edm::Path::processOneOccurrence<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTr\
aits<edm::EventPrincipal, (edm::BranchActionType)1>::MyPrincipal&, edm::EventSetup const&, edm::StreamID const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*)::{\
lambda()#1}>(void edm::Path::processOneOccurrence<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::MyPrincipa\
l&, edm::EventSetup const&, edm::StreamID const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*)::{lambda()#1}) () from /afs/cern.ch/cms/sw/ReleaseCandidates/vol1\
/slc6_amd64_gcc491/cms/cmssw/CMSSW_7_4_X_2015-01-13-0700/lib/slc6_amd64_gcc491/libFWCoreFramework.so
#12 0x00007fa5d9a36ae2 in void edm::Path::processOneOccurrence<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1\
>::MyPrincipal&, edm::EventSetup const&, edm::StreamID const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*) () from /afs/cern.ch/cms/sw/ReleaseCandidates/vol1/s\
lc6_amd64_gcc491/cms/cmssw/CMSSW_7_4_X_2015-01-13-0700/lib/slc6_amd64_gcc491/libFWCoreFramework.so
#13 0x00007fa5d9a36ed5 in void edm::StreamSchedule::processOneEvent<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionT\
ype)1>::MyPrincipal&, edm::EventSetup const&, bool)::{lambda()#1}::operator()() const () from /afs/cern.ch/cms/sw/ReleaseCandidates/vol1/slc6_amd64_gcc491/cms/cmssw/CMSSW_7_4_X_2015-01-13-0700/lib/slc6\
_amd64_gcc491/libFWCoreFramework.so
#14 0x00007fa5d9a371cb in decltype ({parm#1}()) edm::convertException::wrap<void edm::StreamSchedule::processOneEvent<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::Occurre\
nceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::MyPrincipal&, edm::EventSetup const&, bool)::{lambda()#1}>(void edm::StreamSchedule::processOneEvent<edm::OccurrenceTraits<edm::EventPrincipal,\
 (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::MyPrincipal&, edm::EventSetup const&, bool)::{lambda()#1}) () from /afs/cern.ch/cms/sw/ReleaseCandidat\
es/vol1/slc6_amd64_gcc491/cms/cmssw/CMSSW_7_4_X_2015-01-13-0700/lib/slc6_amd64_gcc491/libFWCoreFramework.so
#15 0x00007fa5d9a37428 in void edm::StreamSchedule::processOneEvent<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionT\
ype)1>::MyPrincipal&, edm::EventSetup const&, bool) () from /afs/cern.ch/cms/sw/ReleaseCandidates/vol1/slc6_amd64_gcc491/cms/cmssw/CMSSW_7_4_X_2015-01-13-0700/lib/slc6_amd64_gcc491/libFWCoreFramework.s\
o
#16 0x00007fa5d9a2bf1c in edm::EventProcessor::processEvent(unsigned int) () from /afs/cern.ch/cms/sw/ReleaseCandidates/vol1/slc6_amd64_gcc491/cms/cmssw/CMSSW_7_4_X_2015-01-13-0700/lib/slc6_amd64_gcc49\
1/libFWCoreFramework.so
#17 0x00007fa5d9a2c742 in edm::EventProcessor::processEventsForStreamAsync(unsigned int, std::atomic<bool>*) () from /afs/cern.ch/cms/sw/ReleaseCandidates/vol1/slc6_amd64_gcc491/cms/cmssw/CMSSW_7_4_X_2\
015-01-13-0700/lib/slc6_amd64_gcc491/libFWCoreFramework.so
#18 0x00007fa5d9a3b9c4 in edm::StreamProcessingTask::execute() () from /afs/cern.ch/cms/sw/ReleaseCandidates/vol1/slc6_amd64_gcc491/cms/cmssw/CMSSW_7_4_X_2015-01-13-0700/lib/slc6_amd64_gcc491/libFWCore\
Framework.so
#19 0x00007fa5d73fecba in tbb::internal::custom_scheduler<tbb::internal::IntelSchedulerTraits>::local_wait_for_all (this=0x7fa5d65e3d00, parent=..., child=<optimized out>) at ../../src/tbb/custom_sched\
uler.h:474
#20 0x00007fa5d9a2c468 in edm::EventProcessor::readAndProcessEvent() () from /afs/cern.ch/cms/sw/ReleaseCandidates/vol1/slc6_amd64_gcc491/cms/cmssw/CMSSW_7_4_X_2015-01-13-0700/lib/slc6_amd64_gcc491/lib\
FWCoreFramework.so
#21 0x00007fa5d9a09abd in statemachine::HandleEvent::readAndProcessEvent() () from /afs/cern.ch/cms/sw/ReleaseCandidates/vol1/slc6_amd64_gcc491/cms/cmssw/CMSSW_7_4_X_2015-01-13-0700/lib/slc6_amd64_gcc4\
91/libFWCoreFramework.so
```

I tested in plain CMSSW_7_4_X_2015-01-13-0700 (no crash)
and plain CMSSW_7_4_X_2015-01-13-0700 plus this PR.

To reproduce:
Make developer area with CMSSW_7_4_X_2015-01-13-0700 and without/with this PR
```
 git cms-addpkg HLTrigger/Configuration
 scam b -j 4
 cd HLTrigger/Configuration/test
 ./cmsCdriver.csh
 cmsRun RelVal_DigiL1RawHLT_FULL_MC.py >& RelVal_DigiL1RawHLT_FULL_MC.log
 cmsRun RelVal_RECO_FULL_MC.py >& RelVal_RECO_FULL_MC.log
```
The fist cmsRun prepares a file with HLT to run, in the second cmsRun,
RAW2DIGI,L1Reco,RECO,VALIDATION,DQM on the (HLT) output.
This second cmsRun crashes with the PR is added in.

**Comment by Martin-Grunewald** [comment]
Traceback with line numbers:
```
%MSG
%MSG-e FatalSystemSignal:  FSQDiJetAve:fsqHLTOfflineSource  13-Jan-2015 17:19:43 CET Run: 1 Event: 501
A fatal system signal has occurred: segmentation violation
%MSG


A fatal system signal has occurred: segmentation violation
The following is the call stack containing the origin of the signal.
NOTE:The first few functions on the stack are artifacts of processing the signal and can be ignored

#0  0x00000032a40ac61e in waitpid () from /lib64/libc.so.6
#1  0x00000032a403e609 in do_system () from /lib64/libc.so.6
#2  0x00007ff2f5c2e847 in TUnixSystem::StackTrace() () from /afs/cern.ch/cms/sw/ReleaseCandidates/vol1/slc6_amd64_gcc491/cms/cmssw/CMSSW_7_4_X_2015-01-13-0700/external/slc6_amd64_gcc491/lib/libCore.so
#3  0x00007ff2eca83895 in sig_dostack_then_abort () from /afs/cern.ch/cms/sw/ReleaseCandidates/vol1/slc6_amd64_gcc491/cms/cmssw/CMSSW_7_4_X_2015-01-13-0700/lib/slc6_amd64_gcc491/libFWCoreServices.so
#4  <signal handler called>
#5  0x00007ff2bd0c19bb in FSQ::HandlerTemplate<reco::Track, int>::analyze (this=0x7ff2c2813980, iEvent=..., iSetup=..., hltConfig=..., trgEvent=..., triggerResults=..., triggerNames=..., weight=1) at /data/CMS0/CMSSW_7_4_X_2015-01-13-0700/src/DQMOffline/Trigger/src/FSQDiJetAve.cc:278
#6  0x00007ff2bd0842c5 in FSQDiJetAve::analyze (this=0x7ff2c6672e00, iEvent=..., iSetup=...) at /data/CMS0/CMSSW_7_4_X_2015-01-13-0700/src/DQMOffline/Trigger/src/FSQDiJetAve.cc:670
#7  0x00007ff2f7182901 in edm::stream::EDAnalyzerAdaptorBase::doEvent(edm::EventPrincipal&, edm::EventSetup const&, edm::ActivityRegistry*, edm::ModuleCallingContext const*) () from /afs/cern.ch/cms/sw/ReleaseCandidates/vol1/slc6_amd64_gcc491/cms/cmssw/CMSSW_7_4_X_2015-01-13-0700/lib/slc6_amd64_gcc491/libFWCoreFramework.so
```

**Comment by fwyzard** [comment]
Hi Martin,
I'm looking into it.

.A

**Comment by fwyzard** [comment]
Hi Martin,
I found the problem: FSQ::BaseHandler does not check if parsing the trigger
expression is successful or not; if the parsing fail the parser returns a
null pointer, and later on calling init() on it leads to the segmentation
fault.

I can think of few solutions:
1. let FSQ::BaseHandler check that the parsing returns a valid pointer
2. make the parser always return a valid point (if the parsing fails, it
can return an object that corresponds to a selection that always returns
"false").

The latter is more robust, as it never returns a null pointer, but the
caller of parse() looses the possibility to check if the parsing failed or
succeeded.

What do you prefer ?

.A

**Comment by fwyzard** [comment]
+1

**Comment by fwyzard** [comment]
Well, to begin with I've fixed FSQDiJetAve - I can still make the parser more fail safe later.

**Comment by fwyzard** [comment]
By the way, looks like the HLT changes have been automatically merged via the 7.3.x branch.

**Comment by Martin-Grunewald** [comment]
I very much prefer the null pointer: it gives more information to the client and it is
the client's job to check this to avoind dereferncing it, adding an appropriate action.

**Comment by Martin-Grunewald** [comment]
Hmm, and I do not like this automatic forward port from 73X this late in the 74X series...

**Comment by ktf** [comment]
@Martin-Grunewald @davidlange6 Should I turn it off? As usual the automatic forward porting is a policy   we decide, not something dictated by the tools we use. If you do not want it, and you are happy to live with the burden disabling it introduces (as opposed to the burden leaving it on introduces), just say so and it will be disabled.

**Comment by Martin-Grunewald** [comment]
For my case, I more often do NOT want automatic forward-port than I want it
(we make PRs for 73X and 74X). But others may be in the opposite position.

My suggestion:
Whatever the "default" is/will be, please provide a way on the PR page of the PR to request
to do the opposite of the default (ie, if default = no port, clickable button or special
comment [similar to 'please test' say 'please port to 74X'] to request port; if default=port, button/comment to signal no-port).

Also, the forward port (if requested/not declined) should be done immediately,
not days later.

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
reverting so that I can revert the FSQ changes giving problems in the IBs (I think this will only revert the FSQ changes in this PR)

**Comment by Martin-Grunewald** [comment]
OK, so only the FSQ stuff of this PR is actually reverted...

**Pull request merged**
