### PR TITLE
Add mu beamspot constrained pT. Increase mu eta and phi precision to 16 bits [13.0.X]

### PR DESCRIPTION
**Pull request by vlimant**
#### PR description:

plain backport of #42646

### CODE REVIEW

**Comment by vlimant** [comment]
enable nano

**Comment by vlimant** [comment]
FYI @namapane

**Comment by vlimant** [comment]
please test

**Comment by namapane** [comment]
Thank you @vlimant ! 
But isn't this missing [RecoMuon/GlobalTrackingTools/plugins/MuonBeamspotConstraintValueMapProducer.cc](https://github.com/cms-sw/cmssw/pull/42646/files#diff-ab135f127c4d87be1156dbe7546b9c938b9f1b86b5c82a8a25449b49c757ee89)?

**Comment by vlimant** [comment]
please test

**Comment by vlimant** [comment]
please test

**Comment by vlimant** [comment]
all changes expected

**Comment by vlimant** [comment]
+1

**Comment by mandrenguyen** [comment]
backport of https://github.com/cms-sw/cmssw/pull/42646

**Comment by mandrenguyen** [comment]
type muon

**Comment by mandrenguyen** [comment]
+1

Are we skipping the intermediate backports?

**Comment by namapane** [comment]
> +1
> 
> Are we skipping the intermediate backports?

I can backport to other branches, just let me know which ones :-)

**Comment by mandrenguyen** [comment]
@cms-sw/orp-l2 Should we also include this feature in 13_1 and 13_2?

**Comment by antoniovilela** [comment]
> @cms-sw/orp-l2 Should we also include this feature in 13_1 and 13_2?

Yes, in general we would like features implemented in an older cycle also in the intermediate ones.

**Comment by namapane** [comment]
> > @cms-sw/orp-l2 Should we also include this feature in 13_1 and 13_2?
> 
> Yes, in general we would like features implemented in an older cycle also in the intermediate ones.

Done (#42786, #42787).

**Pull request merged**
