### PR TITLE
L1Trigger/TrackerDTC fix for SLHCUpgradeSimulations/Geometry unit test failure (#29474)

### PR DESCRIPTION
**Pull request by tschuh**
#### PR description:

CheckHistory was set to True by default by mistake, now corrected.

### CODE REVIEW

**Comment by boudoul** [comment]
Hello @tschuh , thanks for the fix, can you make the title more explicit, to make sure we know which fix you are talking about in the release notes where the title will be displayed ?... thanks

**Comment by kpedro88** [comment]
please test

**Comment by silviodonato** [comment]
urgent

**Comment by silviodonato** [comment]
solves #29474

**Comment by kpedro88** [comment]
I ran the unit test manually, merging this PR in the latest IB, and it now succeeds.

**Comment by kpedro88** [comment]
looks like other PRs were merged with this one and caused comparison failures

**Comment by silviodonato** [comment]
> I ran the unit test manually, merging this PR in the latest IB, and it now succeeds.

Thanks

**Comment by silviodonato** [comment]
merge
The differences are due to the update of GEANT4

**Pull request merged**
