### PR TITLE
Added getByToken to edm::EventBase

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

- Extended fwlite::*Event to have consumes to generate a token
- Updated unit tests

#### PR validation:

Code compiles and new unit tests pass.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by makortel** [comment]
Should the twiki documentation be updated to include the token possibility? On a quick look these two pages looked most relevant
https://twiki.cern.ch/twiki/bin/view/CMSPublic/WorkBookFWLiteEventLoop
https://twiki.cern.ch/twiki/bin/view/CMSPublic/WorkBookFWLiteExamples

**Comment by makortel** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
