### PR TITLE
Reco changes for centralityBin in DQM

### PR DESCRIPTION
**Pull request by smdogra**
To include centralityBin distribution in the DQM monitoring. For this,  changes are requested  in the HI reco sequence 

> Reconstruction_HI_cff.py
> RecoHiCentrality_EventContent_cff.py
> and in the 
> CentralityDQM module.
> CentralityDQM_cfi.py

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test
@smdogra I suppose you will make a PR for 75X as well.

**Comment by slava77** [comment]
```
An exception of category 'NoProxyException' occurred while
   [0] Processing run: 1 lumi: 1 event: 1
   [1] Running path 'reconstruction_step'
   [2] Calling event method for module CentralityBinProducer/'centralityBin'
Exception Message:
No data of type "CentralityTable" with label "HFtowers" in record "HeavyIonRcd"
 Please add an ESSource or ESProducer to your job which can deliver this data.
```
the error seems real
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-12002/9079/addOnTests/hlt_mc_HIon/cmsDriver.py_RelVal_-s_HLT:HIon,RAW2DIGI,L1Reco,RECO_--mc_--scenario=HeavyIons_-n_10_--conditions_auto:run2_mc_HIon_--relval_9000,50_--datatier_RAW-H.log

The same test passes in the reference IB
https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc6_amd64_gcc493/CMSSW_7_6_X_2015-10-20-1100/addOnTests/logs/cmsDriver-hlt_mc_HIon_cmsDriver.py_RelVal_-s_HLT:HIon,RAW2DIGI,L1Reco,RECO_--mc_--scenario=HeavyIons_-n_10_--conditions_auto:run2_mc_HIon_--relval_9000,50_--datatier_RAW-H.log

call
``` addOnTests.py -t hlt_mc_HIon ```
 to reproduce

**Comment by slava77** [comment]
@smdogra 
I suppose the fix to the addOnTest issue is coming soon.
Please confirm.

Thank you.

**Comment by mmusich** [comment]
@slava77 there might be a missing label in the MC Heavy Ion GTs (the inital request was to have 2 separate labels for data/mc but at some point this should have changed). Either this line
`centralitybincollection = cms.InputTag("centralityBin","HFtowers")` 
is changed to consume some of the available MC labels or we need to modify the Global Tags.
@diguida

**Comment by mmusich** [comment]
@smdogra GTs with the label HFTower for MC are available: https://github.com/cms-sw/cmssw/pull/12079

**Comment by smdogra** [comment]
@slava77 Can we test it again or do we need to have new PR ?

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
@smdogra looks like #12079 made CMSSW_7_6_X_2015-10-25-2300. If an IB past that one is used to test you should have your `HFtowers` labels available [Diff among GT](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/76X_mcRun2_HeavyIon_v10/76X_mcRun2_HeavyIon_v8).

**Comment by cvuosalo** [comment]
+1

For #12002 5ebae90a1f121249d913277ae9a8dfb129e60c9b

Adding the centrality bin distribution for Heavy Ions.

The code changes are satisfactory, and Jenkins [tests](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-12002/9203/summary.html) against baseline CMSSW_7_6_X_2015-10-26-1100 show no significant differences except the expected addition of the centrality bin distribution for Heavy Ion workflow 140.53. An example is shown below:
centrality

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Comment by diguida** [comment]
@smdogra the 75X back-port of #12002 is ready, together with GT: #12213

**Pull request merged**
