### PR TITLE
Add histograms for nrec/nsim, and average number of pixel/strip hits to MultiTrackValidator

### PR DESCRIPTION
**Pull request by makortel**
This PR adds the following histograms to MultiTrackValidator
* nrec/sim vs. pT, eta, PU
  * as a prerequisite, `num_reco2_{pT,eta,pu}` histograms are added to have distributions of tracks passing the same selection as TrackingParticles in corresponding `num_simul_{pT,eta,pu}` histograms
* average number of pixel or strip hits vs. eta

and the `nrec_vs_nsim` histogram is modified to show the numbers of selected tracks vs. selected TrackingParticles (selection as for phi etc. histograms).

In addition
* a missing include to `Event.h` is added to `RecoTrackSelectorBase.h`
* A new option "simpleratio" is added to `DQMGenericClient` efficiency calculation
  * also some magic numbers are replaced with `enum class`

Tested in 9_1_0_pre1, in addition to new histograms expecting changes in `tracks`, `fakes`, and `{num,effic,...}_*_pu` histograms because of modified axis limits.

@rovere @VinInn @ebrondol

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by ebrondol** [comment]
@makortel tnks! Can you give us a link to have a look at the new MTV plots?

**Comment by makortel** [comment]
I didn't bother to add these to the plotting scripts, but I can do it and show some example plots.

**Comment by mtosi** [comment]
i think the issue w/ workflow 4.53 spotted by the test (which, looking at the corresponding log, is the same i found yesterday)
it is not related to this PR
the issue comes from step2
and it seems to be related to the input files

**Comment by slava77** [comment]
@cmsbuild please test
I think that by now 4.53 is either fixed or is also bad in the baseline and skipped in that case

**Comment by davidlange6** [comment]
the "issue" is most likely cern's eos..

**Comment by davidlange6** [comment]
please test

**Comment by makortel** [comment]
@cmsbuild, please test

Fixed a bug in TrackingParticle DeltaR calculation, and added nrec/nsim and pixel/strip hits/layers vs. eta to "extended" plots (`makeTrackValidationPlots.py --extended ..`).

**Comment by makortel** [comment]
@ebrondol here are some example plots (10 events ttbar+PU200 D4 in 900pre4, highPurity tracks)
* nrec vs. nsim https://cms-tracking-validation.web.cern.ch/cms-tracking-validation/PR/CMSSW_9_0_0_pre4_PR18073/plots_allTPEffic_highPurity/nrecVsNsim.pdf
* pixel/strip layers/hits vs. eta https://cms-tracking-validation.web.cern.ch/cms-tracking-validation/PR/CMSSW_9_0_0_pre4_PR18073/plots_allTPEffic_highPurity/hitsLayers.pdf

**Comment by ebrondol** [comment]
Great! Thanks!

**Comment by dmitrijus** [comment]
+1

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/18073	5ec4f36
- reco is minimally affected (CommonTools/RecoAlgos/interface/RecoTrackSelectorBase.h added a direct include of FWCore/Framework/interface/Event.h)
- jenkins tests pass and comparisons with baseline show some changes in tracking-related DQM plots (FWLite comparisons show that persisted track objects are not affected)

**Comment by davidlange6** [comment]
+1

**Pull request merged**
