### PR TITLE
Gem sim validation porting 76 x only occupy plots optimize header

### PR DESCRIPTION
**Pull request by geonmo**
### Hit Validation module for GEM Detector after Run2
1. This PR include Validation/MuonGEMHits, MuonGEMDigis, MuonGEMRecHits module to validate GEM hit simulation.
   - MuonGEMHits module is related to SimHit on GEM Detector(Run2019/2023).
   - MuonGEMDigis module is related to Digi step about GEM Strip, pad and Copad.
   - MuonGEMRechits module is related to local reco hit on GEM Detector. 
#### This PR does not affect to running other modules.
- These module are only running with specific customize options.

Remake PR due to wrong push to my branch and too old.
It is same PR #11605 except some fix as follow comments.

### CODE REVIEW

**Comment by geonmo** [comment]
@cmsbuild, @deguio Could you test this PR?

**Comment by deguio** [comment]
please test

**Comment by geonmo** [comment]
@deguio Hello, deguio. Could you approve this PR?

**Comment by deguio** [comment]
+1
was reviewed and accepted already

**Comment by geonmo** [comment]
@davidlange6 Hello, david. Could you review my PR?

**Comment by geonmo** [comment]
@davidlange6 Could you review and approve this PR?

**Comment by geonmo** [comment]
@davidlange6 Hello, david. Could you merge this PR? You merged another(same name) PR about CMSSW_8X. I don't know which version is a main release.

**Pull request closed without merging**
