### PR TITLE
[backport]  MTD geometry and reconstruction: synchronise with master up to PR 33762

### PR DESCRIPTION
**Pull request by fabiocos**
#### PR description:

This PR backports to branch 11_3_X the following recent MTD updates added to 12_0_X:

- revert https://github.com/cms-sw/cmssw/pull/33657
- cherry-pick https://github.com/cms-sw/cmssw/pull/33453
- cherry-pick https://github.com/cms-sw/cmssw/pull/33647
- cherry-pick https://github.com/cms-sw/cmssw/pull/33598
- cherry-pick https://github.com/cms-sw/cmssw/pull/33649
- cherry-pick https://github.com/cms-sw/cmssw/pull/33762

It requires https://github.com/cms-data/Geometry-TestReference/pull/9 (a cmsdist backport is provided in parallel).

#### PR validation:

Code has been verified in master, it compiles in 11_3_X

### CODE REVIEW

**Comment by fabiocos** [comment]
please test with https://github.com/cms-sw/cmsdist/pull/6921

**Comment by fabiocos** [comment]
backport

**Comment by silviodonato** [comment]
merge

**Comment by jfernan2** [comment]
+1
for the records...

**Comment by srimanob** [comment]
+Upgrade

This is needed for 11_3 Phase-2 (small) production.

**Comment by silviodonato** [comment]
I'm sorry I merged the wrong PR... I reverted this PR with #33793. The morning IB should be ok

**Comment by fabiocos** [comment]
I'll propose this PR again to go through the usual review, please recall to revert also the corresponding cmsdist update otherwise I expect some unit test to fail in 11_3_X (not a big drama, but)

**Comment by jfernan2** [comment]
+1

**Pull request merged**
