### PR TITLE
PR 80x v86.1 tsg-9.2 post O2O PR merge

### PR DESCRIPTION
**Pull request by rekovic**
This PR is for L1T Offline software l1t-tsg-v9.2 (v86.1) + correct changes introduced unintentionally by the L1T O2O PR

Details:
When merged L1T O2O PR (#15842), the core L1T emulation of calo and muon trigger objects
was affected due to a changes in L1TCalorimeter and L1TMuon packages. 
Unit tests of L1T emulation did not bit-wise agree before and after the O2O merge.

DONE: Bit-wise agreement for calo objects (jets, sums, taus, eg's was re-obtained) after reverting L1TCaloParamsESProducer

DONE: Bit-wise agreement for muon objects after configuring L1TMuonGlobalParamsESProducer to
not use Xml files.

### CODE REVIEW

**Comment by rekovic** [comment]
This PR contains commits addressing review comments of the three 81X PRs: 
- Part 1 (#15745)
- Part 2 (#15757)
- Part 3 (#15823)

**Comment by rekovic** [comment]
please test

**Comment by rekovic** [comment]
+1

**Comment by rekovic** [comment]
please test

**Comment by rekovic** [comment]
Failing tests repeated in a locally built release CMSSW_8_0_X_2016-09-25-0000 plus merging this PR:
<pre>
git cms-merge-topic -u 15978 
</pre>

The failures are due to missing data files, e.g. 
<pre> 
dm::FileInPath unable to find file L1Trigger/L1TCalorimeter/data/lut_30to40_hfHighPt_experiment2_changeLimits_add_mult.txt anywhere in the search path.
 </pre>

@davidlange6 
The needed data files from https://github.com/cms-l1t-offline/L1Trigger-L1TCalorimeter  have already been merged in cms-data:master but not sure if available in this IB ?

**Comment by davidlange6** [comment]
@rekovic - seems not - I'll get them in for the 1100 IB

**Comment by rekovic** [comment]
please test

**Comment by rekovic** [comment]
please test

**Comment by rekovic** [comment]
please test

**Comment by rekovic** [comment]
+1

**Pull request merged**
