### PR TITLE
[CORE] Various fixes/improvements for unit test

### PR DESCRIPTION
**Pull request by smuzaffar**
Updated unit tests so that they can be run from their own separate directory. Mostly 

- convert `<bin ...>` to `<test....>`
- make use of `SCRAM_TEST_PATH` instead
- cleanup unused unittest driver files

these changes will allow to run unit tests in separate unit test directories.

### CODE REVIEW

**Comment by smuzaffar** [comment]
@Dr15Jones , @makortel many of these `FWCore/MessageService/test/u*.sh` files are similar. I think we can merge most of these in two a single script and run it with different input parameters e.g. `runtest.sh <num>` .

**Comment by smuzaffar** [comment]
please test

**Comment by Dr15Jones** [comment]
> many of these FWCore/MessageService/test/u*.sh files are similar.

Yeah, those tests are ancient and written by a person who really wasn't a CMS developer (he was the original FNAL message logger developer). Consolidating them makes a lot of sense.

**Comment by makortel** [comment]
> > many of these FWCore/MessageService/test/u*.sh files are similar.
> 
> Yeah, those tests are ancient and written by a person who really wasn't a CMS developer (he was the original FNAL message logger developer). Consolidating them makes a lot of sense.

I agree. @smuzaffar Would you like to pursue the consolidation already in this PR?

**Comment by smuzaffar** [comment]
> I agree. @smuzaffar Would you like to pursue the consolidation already in this PR?

@makortel , no not in this PR. I can do it in a new PR (after I am done with unit test changes to allow them to run from separate test directory/per test)

**Comment by makortel** [comment]
A single-histogram difference in 11634.7 is presumably realted to #39803

**Comment by makortel** [comment]
+1

**Comment by perrotta** [comment]
+2

**Comment by perrotta** [comment]
+1

**Pull request merged**
