### PR TITLE
Fix online74

### PR DESCRIPTION
**Pull request by deguio**
this is a bunch of fixes needed to have 74 working at p5.
the GT is updated as well.

### CODE REVIEW

**Comment by deguio** [comment]
@diguida
we discussed already in person the bad behaviour of 
loadRecoTauTagMVAsFromPrepDB_cfi.py

where the code is accessing frontier://FrontierProd/CMS_COND_PAT_000.
this doesn't work from inside p5 and this module is apparently included in some of the reco sequences run by the online applications.

how do you suggest to proceed here?
thanks in advance,
F.

**Comment by deguio** [comment]
commenting out everything is the temporary solution I put in place for 74, but it is not a final one.

**Comment by diguida** [comment]
@deguio 
I have checked the sequences, but not the GT yet.
There are two issues here:

1. (more serious) there is a new `ESSource`, without `ESPrefer`, while the only one reading conditions should be the `PoolDBESSource` instantiated in `FrontierConditions_GlobalTag`.
1. (less serious) the logic of the fragment is not included in the payload loading.

I will give more information shortly.
@mmusich this is something you want to watch as well.

**Comment by jpavel** [comment]
I think that part of the problem is that the payloads that are being loaded via this file are not included in any GT. Also, I think that by commenting this stuff, the tau sequence should fail, as these payloads are necessary for several discriminants. @andrewj314

**Comment by diguida** [comment]
@jpavel IIRC we added these corrections are already in some GT. We discussed this in an AlCaDB meeting, and even in person. Am I missing something?

**Comment by diguida** [comment]
@jpavel Anyhow, all the production sequences *MUST* consume conditions *ONLY* from GT. It is the only guaranteed way not to jeopardise reconstruction with incompatible calibrations.

**Comment by jpavel** [comment]
They are in the production database. And AFAIK the last step is to include them in a queue the tag via GTC. This has not happened so far, as it was not clear to me which queue should be used.

**Comment by diguida** [comment]
@jpavel yes, indeed I have just found your question on private email in January (while I was sick).
From what I can see in the sequence, I assume that they are needed for both MC and data (including HLT), for Run1 and Run2 scenarios.

**Comment by jpavel** [comment]
@diguida Yes - what are the names of the queues? 74Y_data*, 74Y_mc*  and 75Y_data* and 75Y_mc* ? I do not think it is needed for HLT, as the HLT discriminators are not using MVA (at least not at the moment).

**Comment by diguida** [comment]
@jpavel thanks!
The queues are:
74Y_designRun1
74Y_mcRun1
74Y_mcRun1_HeavyIon
74Y_mcRun1_pA
74Y_designRun2
74Y_mcRun2_startup
74Y_mcRun2_asymptotic
74Y_mcRun2_HeavyIon
74Y_dataExpress
74Y_dataPrompt
74Y_dataRun1
74Y_dataRun1RelVal
74Y_dataRun2
74Y_dataRun2RelVal
Same for 75X queues:
75Y_designRun1
75Y_mcRun1
75Y_mcRun1_HeavyIon
75Y_mcRun1_pA
75Y_designRun2
75Y_mcRun2_startup
75Y_mcRun2_asymptotic
75Y_mcRun2_HeavyIon
75Y_dataRun1
75Y_dataRun1RelVal
75Y_dataRun2
75Y_dataRun2RelVal

**Comment by jpavel** [comment]
thanks, I submitted one tag to test the procedure. However, we have ~150 of those - is there a way how to automate the submission? CLI perhaps?

**Comment by slava77** [comment]
Is this PR a work in progress?
From the comments earlier it sounds like it is and it's not worth reviewing/signing it yet.

**Comment by jpavel** [comment]
@diguida Is the submission I made for one tag at the moment correct? Next, I cannot select a "record" for our payloads of type PhysicsTFormulaPayloadRcd and PhysicsTGraphPayloadRcd, so I cannot queue them. Were the new formats propagated to the tag collector?

**Comment by jpavel** [comment]
@slava77 I think that it is work in progress - we need to include tau payloads to GT and I think that the PR at the moment breaks RECO sequence.

**Comment by deguio** [comment]
-1
this won't be tested as it is. this is work ongoing.
F.

**Comment by slava77** [comment]
Is this still in a "work ongoing" status?

**Comment by deguio** [comment]
ciao @slava77 
an update about this is that for the online, where the full reco sequence is run for the EvD and other applications, I managed to get the code working by using a TauID.db as an input locally.
this is a temporary solution. I let @diguida and @jpavel converge on a final fix for this.

closing.
ciao,
F.

**Pull request closed without merging**
