### PR TITLE
[DQM]Removed a nop call of DQMStore::setVerbose()

### PR DESCRIPTION
**Pull request by andrius-k**
#### PR description:

This PR removes a call that nop call to `DQMStore::setVerbose()`. The method will be removed from the `DQMStore` in the future.

#### PR validation:

PR was tested internally.

### CODE REVIEW

**Comment by andrius-k** [comment]
please test

**Comment by perrotta** [comment]
+1
- For reco, only one call of the (empty, by now) ```DQMStore::setVerbose()``` method is removed from some test code
- Jenkins tests pass

**Comment by Martin-Grunewald** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by fabiocos** [comment]
@qliphy @agrohsje the generator part of this PR looks simple, please have a look.
@jfernan2 @andrius-k what is the situation about it, for what concerns your signature?

**Comment by qliphy** [comment]
+1

**Pull request merged**
