### PR TITLE
improve math in broken-line fit

### PR DESCRIPTION
**Pull request by VinInn**
These changes were supposed to happen during the "clean-up" (that apparently just added duplicates).

It should also address the symptom in #34831 :
The NaN stays NaN of course. It will be trapped later and the track marked bad.
There is no gain in trying to robustify math in circle_fit as, in case of aligned hits, the fast_fit is most probably already broken

Expect some negligible differences (present even in the unit test)

Negligible effects on timing.

### CODE REVIEW

**Comment by VinInn** [comment]
@cmsbuild , please test

**Comment by VinInn** [comment]
enable gpu

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+reconstruction

for https://github.com/cms-sw/cmssw/pull/35128	25ca171
- code changes are mostly technical, in line with the PR description
- jenkins tests pass
    - comparisons with the baseline show no (relevant) differences in the CPU tests 
    - comparisons in the GPU tests have negligible differences only in the pixel tracking workflow 10824.502 DQM plots (none made it to the persisted object plain reco comparisons)

**Comment by slava77** [comment]
@VinInn 
please make a backport to 12_0_X.
Thank you.

**Comment by qliphy** [comment]
+1

**Comment by fwyzard** [comment]
> please make a backport to 12_0_X.
> Thank you.

Done via #35313.

**Pull request merged**
