### PR TITLE
New feature in GEM simulation: GEMPadDigiCluster

### PR DESCRIPTION
**Pull request by dildick**
A GEMPadDigiCluster is a set of adjacent GEMPadDigis in a single GEM chamber. Currently we send all trigger pads from the GEM chamber to the CSC chamber. In the hardware each GEM chamber optohybrid will send at most 8 clusters of at most 8 adjacent trigger pads to the nearby CSC optical trigger mother board. The effects are expected to be very small (<1%) on the local GEM-CSC trigger performance. 

Still needs to be done: use GEMPadDigiClusters instead of GEMPadDigis in CSC trigger emulator.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by dildick** [comment]
Comparison looks good. There should not be (and there aren't) any changes with respect to the baseline.

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
