### PR TITLE
Phase2-hgx305 Update the hgcalcell xml files in view of foressen corrections

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Update the hgcalcell xml files in view of foressen corrections. We foresee a new plugin code for creating the cells which will require two additional parameters. The new code will take care of the V17 cells but is not expected to modify cells for earlier version. However the parameters are needed for earlier version as well. 

#### PR validation:

Use the runTheMatrix test workflows

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
+1

**Comment by bsunanda** [comment]
@srimanob Please sign this. We are waiting for this PR to be merged to go to the next step

**Comment by srimanob** [comment]
Hi @bsunanda 
Am I understand correctly that this update to XML files will effect all HGCAL version, but not now?
I seems it touches all versions used for C9-C17 in https://github.com/cms-sw/cmssw/blob/master/Configuration/Geometry/python/dict2026Geometry.py

**Comment by bsunanda** [comment]
Hope it does not. The modified algorithm needs 2 additional parameters which will affect V17 geometry of HGCal and hopefully not the earlier ones. But those parameters need to be defined for all versions of XML file

**Comment by bsunanda** [comment]
We need that version to be checked in next and without this PR it cannot be tested

**Comment by srimanob** [comment]
Thanks. I think this is an information that should be in the PR description. This will us to understand and in case needs to look back if there is an issue.

**Comment by srimanob** [comment]
+Upgrade

**Comment by bsunanda** [comment]
@srimanob done an addiotnal comment

**Comment by perrotta** [comment]
+1

**Pull request merged**
