### PR TITLE
Make a static variable const in L1Trigger/Phase2L1ParticleFlow/interface/taus/TauNNIdHW.h

### PR DESCRIPTION
**Pull request by perrotta**
#### PR description:

Simple fix to make the static analyzer happy

#### PR validation:

It build

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by cecilecaillol** [comment]
+l1

**Comment by srimanob** [comment]
+Upgrade

Technical PR.

**Comment by perrotta** [comment]
+1

**Comment by perrotta** [comment]
merge

**Pull request merged**
