### PR TITLE
New training for anti-e tau-Id

### PR DESCRIPTION
**Pull request by mbluj**
This PR adds configuration for payloads with a new training of anti-e tau-Id. It follows changes introduced by #24800.
In addition, this PR adds a switch to remove/keep tau candidates in the EB-EE crack regions (|eta|~1.5). Those regions are covered by the new training (but not by the old one) to allow recovery of efficiency. By default the switch is set to value recovering previous behavior (removal of candidates in EB-EE cracks) thus this does not breaks backward compatibility.
We intend to backport this PR to 102X and 94X to be used in Run-2 analyses and be included to NanoAOD with 102X (different PR via NanoAOD repo will be prepared).

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by mbluj** [comment]
The recent commit just adds the new anti-e discriminant to tau tools for users convenience. It is backported to 102X (#25487), while backport to 94X will be performed when DNN-tauID (and tau tools) are finally merged to 94X.

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
@mbluj 
I'm running the test provided, which completes successfully.

Out of curiosity: during the test setup the following output is printed on log:
```
patTauDiscriminationByLooseElectronRejectionMVA62018 loadMVA = 1
patTauDiscriminationByLooseElectronRejectionMVA62018 loadMVA = 1
patTauDiscriminationByMediumElectronRejectionMVA62018 loadMVA = 1
patTauDiscriminationByMediumElectronRejectionMVA62018 loadMVA = 1
patTauDiscriminationByTightElectronRejectionMVA62018 loadMVA = 1
patTauDiscriminationByTightElectronRejectionMVA62018 loadMVA = 1
patTauDiscriminationByVLooseElectronRejectionMVA62018 loadMVA = 1
patTauDiscriminationByVLooseElectronRejectionMVA62018 loadMVA = 1
patTauDiscriminationByVTightElectronRejectionMVA62018 loadMVA = 1
patTauDiscriminationByVTightElectronRejectionMVA62018 loadMVA = 1
rerunDiscriminationByIsolationNewDMMVArun2017v2Loose loadMVA = 1
```
i.e. any WP seems to be loaded twice. 

However, I cannot figure out what produces those strings in the log. Could you please verify what actually originates that output, and if the fact that all WPs are repeated twice there does not mean that the loading is uselessly repeated?

**Comment by mbluj** [comment]
> @mbluj
> I'm running the test provided, which completes successfully.
> 
> Out of curiosity: during the test setup the following output is printed on log:
> 
> ```
> patTauDiscriminationByLooseElectronRejectionMVA62018 loadMVA = 1
> patTauDiscriminationByLooseElectronRejectionMVA62018 loadMVA = 1
> patTauDiscriminationByMediumElectronRejectionMVA62018 loadMVA = 1
> patTauDiscriminationByMediumElectronRejectionMVA62018 loadMVA = 1
> patTauDiscriminationByTightElectronRejectionMVA62018 loadMVA = 1
> patTauDiscriminationByTightElectronRejectionMVA62018 loadMVA = 1
> patTauDiscriminationByVLooseElectronRejectionMVA62018 loadMVA = 1
> patTauDiscriminationByVLooseElectronRejectionMVA62018 loadMVA = 1
> patTauDiscriminationByVTightElectronRejectionMVA62018 loadMVA = 1
> patTauDiscriminationByVTightElectronRejectionMVA62018 loadMVA = 1
> rerunDiscriminationByIsolationNewDMMVArun2017v2Loose loadMVA = 1
> ```
> 
> i.e. any WP seems to be loaded twice.
> 
> However, I cannot figure out what produces those strings in the log. Could you please verify what actually originates that output, and if the fact that all WPs are repeated twice there does not mean that the loading is uselessly repeated?

This message comes from constructor of `PATTauDiscriminantCutMultiplexer` class which is the base class for MVA tau-Id WPs: https://github.com/cms-sw/cmssw/blob/master/RecoTauTag/RecoTau/plugins/PATTauDiscriminantCutMultiplexer.cc#L156 and has nothing to do with this PR. As far as I understand the message is repeated as many times as the module is constructed which is equal to number of threads used.

What is sure is that the `if(verbosity_)` statement should not be used in this line as `verbosity_` is not initialized yet in #L156, it happens only in #L182. I'm going to fix it.

What concerns loading payloads from DB: it happens once per event in the `beginEvent` method: https://github.com/cms-sw/cmssw/blob/master/RecoTauTag/RecoTau/plugins/RecoTauDiscriminantCutMultiplexer.cc#L206 and #221 which is correct.

**Comment by mbluj** [comment]
The recent commit fixes issue with too late initialization of `verbosity_` parameter in one plugin and repeated initialization in other. The issues were however not critical.

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
+1
- A new anti-e tau-ID defined is added to tau tools for user convenience, but disabled by default by now
- Jenkins tests pass and show no differences
- Local tests run with that ID enabled run successfully

**Comment by fabiocos** [comment]
+1

**Pull request merged**
