### PR TITLE
HLT migration to 12_3_0_pre4 + HLT development

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
#### PR description:

HLT migration to 12_3_0_pre4 + HLT development
Based on CMSSW_12_3_X_2022-01-23-2300

#### PR validation:

TSG tests

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1
The test error is just the annoying RelVals-INPUT failure of workflow 4.76

**Comment by perrotta** [comment]
+1

**Comment by perrotta** [comment]
merge

**Pull request merged**
