### PR TITLE
[12.3.X] Shorten the names of two ALCARECOStreams in order to fit into DBS database schema limitations

### PR DESCRIPTION
**Pull request by mmusich**
backport of https://github.com/cms-sw/cmssw/pull/38186

#### PR description:

It was pointed out in https://cms-talk.web.cern.ch/t/alcaprompt-datasets-not-loaded-in-dbs/11146/1 that, quoting:

> Since the last update of the alcareco matrix, two new producers were added to ExpressPhysics:
>    * `PromptCalibProdSiPixelLorentzAngle`
>    * `PromptCalibProdSiStripHitEfficiency`
>    while the resulting (harvested) ROOT files are regularly displayed in the DQM, the corresponding ALCAPROMPT datasets in DAS are missing.
>
> The names of the datasets expected are:
>
>    /StreamExpress/Run2022A-PromptCalibProdSiStripHitEfficiency-Express-v1/ALCAPROMPT
>    /StreamExpress/Run2022A-PromptCalibProdSiPixelLorentzAngle-Express-v1/ALCAPROMPT
>
> According to Tier0 experts the problem is related to the name of the dataset, which is too long to be accepted, and the WMAgent software at present is not signalling this but keeps trying the upload. While probably a better handling of this issue should be thought for future, we need to fix the cause of the problem by shortening the names.

This PR performs such shortening:
   * `ALCARECOPromptCalibProdSiPixelLorentzAngle` is renamed `ALCARECOPromptCalibProdSiPixelLA`
   * `ALCARECOStreamPromptCalibProdSiStripHitEfficiency` is renamed `ALCARECOStreamPromptCalibProdSiStripHitEff`

#### PR validation:

Run the following commands:
```console
cmsDriver.py testReAlCa -s ALCA:PromptCalibProdSiPixelLA --conditions 123X_dataRun3_Express_v6 --scenario pp --data --era Run2_2018 --datatier ALCARECO --eventcontent ALCARECO --processName=ReAlCa -n 10000 --dasquery='file dataset=/StreamExpress/Run2022A-SiPixelCalSingleMuon-Express-v1/ALCARECO run=352572' --customise_commands='process.ALCARECOCalSignleMuonFilterForSiPixelLorentzAngle.TriggerResultsTag = cms.InputTag ( "TriggerResults","","HLT" ) ; process.ALCARECOCalSignleMuonFilterForSiPixelLorentzAngle.HLTPaths = ["*"]' --nThreads=4

cmsDriver.py stepHarvest -s ALCAHARVEST:SiPixelLA --conditions 123X_dataRun3_Express_v6  --scenario pp --data --era Run2_2018 --filein file:PromptCalibProdSiPixelLA.root -n -1
```

and

```console
cmsDriver.py testReAlCa -s ALCA:PromptCalibProdSiStripHitEff --conditions 123X_dataRun2_v2 --scenario pp --data --era Run2_2018 --datatier ALCARECO --eventcontent ALCARECO --processName=ReAlCa -n 100000 --dasquery='file dataset=/StreamExpress/Run2018D-SiStripCalMinBias-Express-v1/ALCARECO run=325172' --nThreads=4

msDriver.py stepHarvest -s ALCAHARVEST:SiStripHitEff --conditions 123X_dataRun2_v2 --scenario pp --data --era Run2_2018 --filein file:PromptCalibProdSiStripHitEff.root -n -1 
```

Also exercised successfully the two `runTheMatrix` workflows running the PCL workflows:
   * `runTheMatrix.py -l 1001,1001.2` 

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Verbatim backport of https://github.com/cms-sw/cmssw/pull/38186

### CODE REVIEW

**Comment by mmusich** [comment]
test parameters: 
   * workflow = 1001.2

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
@cmsbuild, please test
   * let's try again

**Comment by tvami** [comment]
+alca
 * tests pass
 * private tests with the problematic run pass, too

**Comment by fabiocos** [comment]
urgent

the absence of this fix is creating a backlog of not properly uploaded files in Tier0, which should be stopped asap

**Comment by srimanob** [comment]
+Upgrade

Backport PR.

**Comment by mmusich** [comment]
sorry to constantly ping you @cms-sw/pdmv-l2  :)

**Comment by kskovpen** [comment]
Sorry for delay

**Comment by mmusich** [comment]
thanks @kskovpen see also the 12.4.X version of this https://github.com/cms-sw/cmssw/pull/38187

**Comment by qliphy** [comment]
+1

**Pull request merged**
