### PR TITLE
Run3-gex74N Bug fix for the material budget code and add a macro for getting the plots

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Bug fix for the material budget code and add a macro for getting the plots

#### PR validation:

Tested using the scripts in Validation/Geometry/test

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by jfernan2** [comment]
+1

**Comment by cvuosalo** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by jfernan2** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
