### PR TITLE
TrackingTools/KalmanUpdators: Remove class member that are not needed.

### PR DESCRIPTION
**Pull request by gartung**
Remove class member that are not needed.
Return shared_ptr from make_shared directly.

### CODE REVIEW

**Comment by gartung** [comment]
@Dr15Jones please review.

**Comment by Dr15Jones** [comment]
looks good to me

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
please test

**Comment by slava77** [comment]
@cmsbuild please test

it looks like the failures are gone based on the recent jenkins tests

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/21983	5c9a305
- technical
- jenkins tests pass

**Comment by fabiocos** [comment]
+1

**Pull request merged**
