### PR TITLE
GEN related PR: Updating configs in Configuration/Generator/python/ with new gridpacks to fix errors (ref. PR 25343)

### PR DESCRIPTION
**Pull request by Saptaparna**
This PR is a response to PR #25343 (https://github.com/cms-sw/cmssw/issues/25343). The gen related configs have been updated with new gridpacks that should solve the issues encountered in sl7 setup.

### CODE REVIEW

**Comment by alberto-sanchez** [comment]
please test

**Comment by Saptaparna** [comment]
@alberto-sanchez is this PR okay? If there are no other issues, can this be merged? thanks!

**Comment by alberto-sanchez** [comment]
please test workflow 523.0, 551.0, 555.0, 1360.0, 25210.0

**Comment by alberto-sanchez** [comment]
@Saptaparna I am relaunching the test with the appropriate workflows. I missed those in the first try.

**Comment by Saptaparna** [comment]
@alberto-sanchez Is this PR fine? Looks like everything works, right?

**Comment by qliphy** [comment]
Thanks @Saptaparna !  local tests with wf 551 and 555 look good to me.

**Comment by qliphy** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Pull request merged**
