### PR TITLE
Clang fixes in CondTools/SiPixel

### PR DESCRIPTION
**Pull request by Dr15Jones**
Fixed various clang compiler warnings seen in CondTools/SiPixel.
In addition, worked on modernizing and correcting problems in SiPixelGainCalibrationReadDQMFile.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
Please test

**Comment by ggovi** [comment]
+1

**Comment by Dr15Jones** [comment]
ping @franzoni @pohsun @tocheng @lpernie

**Comment by pohsun** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
