### PR TITLE
Trk hit assoc log debug

### PR DESCRIPTION
**Pull request by wmtford**
Cleanup of TrackerHitAssociator per request of @kpedro88 for earlier PR#18354:  commented couts removed or replaced by LogDebug; auto iterator and range-based loops.  test/TestAssociator rewritten to replace duplicated code with a templated function, and add phase 2 tracker.

### CODE REVIEW

**Comment by kpedro88** [comment]
@wmtford thanks for following up on this. Two things:
1) The PR needs to be rebased; please follow the tutorial at http://cms-sw.github.io/tutorial-resolve-conflicts.html
2) The code checks need to be applied before the PR can be tested (follow the instructions above, provided by the bot).

**Comment by kpedro88** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
