### PR TITLE
Fix for the access of haloMVATaggerVal in the Run 1+2 files

### PR DESCRIPTION
**Pull request by jainshilpi**
This PR fixes the problem caused by the PR: #36901 ,  first caught here: #37143
PR #36901 was missing the correct treatment to Run 1+2 files (e.g. WF 136.7611) which essentially picks the 2016 AOD files and tries to find the value of haloTaggerMVAVal_. Since this variable does not exist in those AOD files (which was added by PR: #36901 ), this was just taking some junk value and puts in haloTaggerMVAVal(). 
This PR fixes this issue by having the appropriate ioread rules.

### CODE REVIEW

**Comment by perrotta** [comment]
please test
(Thank you @jainshilpi !)

**Comment by perrotta** [comment]
type bugfix

**Comment by swagata87** [comment]
hi Shilpi, 
do I understand correctly that the BDT score returned by `haloTaggerMVAVal()` is such that beam halos peak at a lower value (around 0) and signal photons peak at higher value (around 1). And in analysis level, people will check something like 
`if haloTaggerMVAVal()<say 0.7 then reject the photon as it is beam halo`. 
If this is the case, then +99 might be better than -99, ie, ` <![CDATA[haloTaggerMVAVal_ = 99;]]> `
Although it is unlikely that someone will reminiAOD Run2 data again, but +99 is safer..  just in case..

**Comment by jainshilpi** [comment]
> hi Shilpi, do I understand correctly that the BDT score returned by `haloTaggerMVAVal()` is such that beam halos peak at a lower value (around 0) and signal photons peak at higher value (around 1). And in analysis level, people will check something like `if haloTaggerMVAVal()<say 0.7 then reject the photon as it is beam halo`. If this is the case, then +99 might be better than -99, ie, `<![CDATA[haloTaggerMVAVal_ = 99;]]>` Although it is unlikely that someone will reminiAOD Run2 data again, but +99 is safer.. just in case..

Hi Swagata, I was thinking about it. If that is preferred default value, I can do the update.

**Comment by jainshilpi** [comment]
As @swagata87 mentioned above, I also think its safer to have 99 instead of -99 so that the photons are not rejected just in case this variable is used on the Run1/2 files. The corresponding update is done.

**Comment by jpata** [comment]
@cmsbuild please test

**Comment by jpata** [comment]
Is the read rule the best solution here? Have a look at what was done for https://github.com/cms-sw/cmssw/pull/36179, no read rule was required, and we don't seem to have a proliferation of read rules for any new branch that is introduced.

Perhaps it's better to just initialize `Photon::haloTaggerMVAVal_` with a default in the class definition? In fact, [here](https://github.com/cms-sw/cmssw/blob/24fa880739386620b7828f73bd2b6f456cdf6450/DataFormats/EgammaCandidates/src/Photon.cc#L11) a default is set (with a value that is not ideal perhaps?), but evidently the problematic photon is constructed in a different way, so `Photon::haloTaggerMVAVal_` is not initialized, so perhaps the other constructors need to take into account the default value, too.

**Comment by jainshilpi** [comment]
> @jainshilpi should this value be changed, too?
> 
> https://github.com/cms-sw/cmssw/blob/24fa880739386620b7828f73bd2b6f456cdf6450/DataFormats/EgammaCandidates/src/Photon.cc#L11
> 
> Otherwise, in the future, it might be confusing why some photons have mva=99, some mva=-999, and some have a meaningful value.

ah yes sorry - fixed that now - thanks @jpata for catching.

**Comment by perrotta** [comment]
@cmsbuild please test

**Comment by jpata** [comment]
+reconstruction
- bugfix on top of https://github.com/cms-sw/cmssw/pull/36901, taking care of the uninitialized values of the `haloMVATaggerVal`

**Comment by perrotta** [comment]
+1
- This is expected to clean up the comparisons in the bot tests

**Pull request merged**
