### PR TITLE
Fix modifiers in Phase2 L1T sequences and add Phase2 L1T objects to FEVTDEBUG EventContent

### PR DESCRIPTION
**Pull request by silviodonato**
#### PR description:

Based on #30491
Adding all Phase2 L1T products to FEVTDEBUG Event Content
Also add missing KBmtf in the Muon L1T sequence.
Synch of Modifiers between L1T sequences. We turn on the new Phase-2 L1T package only with `(phase2_trigger & phase2_trackerV14).t`

#### PR validation:

Workflow `23234.0` works (it was failing in #30491)

### CODE REVIEW

**Comment by silviodonato** [comment]
please test

**Comment by silviodonato** [comment]
abort

**Comment by silviodonato** [comment]
please test
I forgot to push the last commit

**Comment by silviodonato** [comment]
The test did not run with
```
+ git clone --branch CMSSW_11_2_X --no-checkout --reference /cvmfs/cms.cern.ch/cmssw.git.daily --origin official-cmssw git@github.com:cms-sw/cmssw.git /data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_2_X_2020-07-01-2300/src
Cloning into '/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_2_X_2020-07-01-2300/src'...
Connection to github.com closed by remote host.
+ grep 'Automatic merge failed' /data/cmsbld/jenkins/workspace/ib-run-pr-tests/git-merge-result
+ grep 'Couldn'\''t find remote ref' /data/cmsbld/jenkins/workspace/ib-run-pr-tests/git-merge-result
+ git diff --name-only CMSSW_11_2_X_2020-07-01-2300
warning: Not a git repository. Use --no-index to compare two paths outside a working tree
```
I tried to squash the commit into one

**Comment by silviodonato** [comment]
please test

**Comment by silviodonato** [comment]
please test

**Comment by smuzaffar** [comment]
this failed to merge
https://cmssdt.cern.ch/jenkins/job/ib-run-pr-tests/7599/console

**Comment by smuzaffar** [comment]
I forced re-run the tests and now it looks that it is running

**Comment by silviodonato** [comment]
merge

**Comment by makortel** [comment]
Did this PR perhaps break 20634.99?
```
----- Begin Fatal Exception 03-Jul-2020 04:03:04 CEST-----------------------
An exception of category 'ProductNotFound' occurred while
   [0] Processing  Event run: 1 lumi: 2 event: 103 stream: 3
   [1] Running path 'FEVTDEBUGHLToutput_step'
   [2] Prefetching for module PoolOutputModule/'FEVTDEBUGHLToutput'
   [3] Calling method for module L1EGCrystalClusterEmulatorProducer/'L1EGammaClusterEmuProducer'
Exception Message:
Principal::getByToken: Found zero products matching all criteria
Looking for type: edm::SortedCollection&lt;EcalEBTriggerPrimitiveDigi,edm::StrictWeakOrdering&lt;EcalEBTriggerPrimitiveDigi&gt; &gt;
Looking for module label: simEcalEBTriggerPrimitiveDigis
Looking for productInstanceName: 
Looking for process: HLT
   Additional Info:
      [a] If you wish to continue processing events after a ProductNotFound exception,
add "SkipEvent = cms.untracked.vstring('ProductNotFound')" to the "options" PSet in the configuration.
----- End Fatal Exception -------------------------------------------------
```
https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc820/CMSSW_11_2_X_2020-07-02-2300/pyRelValMatrixLogs/run/20634.99_TTbar_14TeV+TTbar_14TeV_TuneCP5_2026D41PU_GenSimHLBeamSpotFull14INPUT+PREMIX_2026D41PU_PremixHLBeamSpotFull14PU_Premix+DigiFullTriggerPUPRMXCombined_2026D41PU+RecoFullGlobalPUPRMX_2026D41PU+HARVESTFullGlobalPU_2026D41PU/step3_TTbar_14TeV+TTbar_14TeV_TuneCP5_2026D41PU_GenSimHLBeamSpotFull14INPUT+PREMIX_2026D41PU_PremixHLBeamSpotFull14PU_Premix+DigiFullTriggerPUPRMXCombined_2026D41PU+RecoFullGlobalPUPRMX_2026D41PU+HARVESTFullGlobalPU_2026D41PU.log#/

**Pull request merged**
