### PR TITLE
Run3-ft21 Fix run3 geometry so that SIM step works

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Fix run3 geometry so that SIM step works

#### PR validation:

Use a built in cfg file to test the new geometry scenario

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
+1

**Comment by bsunanda** [comment]
@kpedro88 Could you sign this please? I think this has to go for 11_1_0 to enable Run3 scenario

**Comment by kpedro88** [comment]
+upgrade

**Comment by silviodonato** [comment]
+1

**Pull request merged**
