### PR TITLE
CTPPS: DQM update

### PR DESCRIPTION
**Pull request by jan-kaspar**
This PR collects several improvements of CTPPS DQM plots, including those fundamental for the upcoming 90m run.

Changes in general CTPPS plots
 * removed unused trigger-related plots
 * added correlation plots between pots of different technologies (strips, pixels, diamonds etc.)
 * optimisation of diamond plots
 * strips: kept only plots for pots used in 2018

Plots for 90m run
 * strips: U/V trigger-sector correlation plots

Plots for low-energy run
 * follow up of #21158 (with David's comment implemented)

Note: some of the new plots are only relevant for special runs (CTPPS alignment, low-energy, etc.). These plots are built by a dedicated module ElasticPlotDQMSource which is by default not included in the processing sequence. It is agreed with the DQM team that the module can be included for the special runs upon our demand.

The updated code was tested on the data from the 2018 CTPPS run with this config: DQM/CTPPS/test/all_ctpps_dqm_test_from_aod_cfg.py.

``runTheMatrix.py -l limited`` gave ``23 22 21 17 9 1 1 1 1 tests passed, 1 1 0 0 0 0 0 0 0 failed``. The two failing tests
  * 4.22: Step0-DAS_ERROR
  * 136.7611: Step1-FAILED

don't seem related to this PR.

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by ianna** [comment]
+1

@jan-kaspar - does it mean that the DB payloads will have to be updated?

**Comment by jan-kaspar** [comment]
@ianna Yes, the geometry payloads will need an update. Since in few days @nminafra will push another RP modifying the payloads, you may like to wait and do both at the same time. Thanks!

**Comment by fabiocos** [comment]
please test

**Comment by nminafra** [comment]
@ianna the other PR @jan-kaspar was mentioning (which includes the geometry of the new timing detectors) was just issued: #23101

**Comment by jan-kaspar** [comment]
Could someone restart the test? I don't believe that there is any reason for it to fail. With the same code the test passed on 23 April.

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
+1

**Pull request merged**
