### PR TITLE
Phase2-hgx349 Modify the material budget script to enable obtaining material budget plots for HFNose

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Modify the material budget script to obtain material budget plots for HFNose (scanning till the beginning and the end of the HFNose)

#### PR validation:

Obtained the plots with the 2026D94 scenario before and after HFNose 

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
+geometry

**Comment by jfernan2** [comment]
+1

**Comment by bsunanda** [comment]
@nothingface0, @antoniovagnerini, @syuvivida, @rvenditti, @tjavaid Can you approve this?

**Comment by tjavaid** [comment]
+1

- understanding  the [differences](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_14_0_X_2023-11-12-0000+350dd7/59686/12434.7_TTbar_14TeV+2023_trackingMkFit/) caused by unstable workflow `12434.7` as reported in #39803 
- @bsunanda , please modify a bit the title and description for `scipt` -> `script` (if it is meant for)

**Pull request merged**
