### PR TITLE
Run3-alca235 Update some of the scripts used in calibrating HCAL channels using muons

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Update some of the scripts used in calibrating HCAL channels using muons
 
#### PR validation:

Use the scripts in getting useful set of histograms to do the fitting of the muon signals

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by ChrisMisan** [comment]
type hcal

**Comment by ChrisMisan** [comment]
please test

**Comment by ChrisMisan** [comment]
+alca

- changes only in macros
- differences only in msgLogger

**Comment by perrotta** [comment]
+1

**Pull request merged**
