### PR TITLE
Delete unused headers/test files (DB packages)

### PR DESCRIPTION
**Pull request by ggovi**
#### PR description:

Implementing changes from https://github.com/cms-sw/cmssw/pull/31870/, on DB packages

### CODE REVIEW

**Comment by ggovi** [comment]
please test

**Comment by tvami** [comment]
As part of the cleaning discussed in https://github.com/cms-sw/cmssw/issues/31505

**Comment by tvami** [comment]
+alca

**Comment by ggovi** [comment]
+1

**Comment by rekovic** [comment]
+1

**Comment by perrotta** [comment]
please test
(to refresh the tests before merging)

**Comment by smuzaffar** [comment]
please test

**Comment by perrotta** [comment]
+1

**Pull request merged**
