### PR TITLE
[9.4.X][Change GT] JEC for MC

### PR DESCRIPTION
**Pull request by lpernie**
Added JEC MC Tags to:
## 2018 MC GT
.  [94X_upgrade2018_design_IdealBS_v8](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_upgrade2018_design_IdealBS_v8/94X_upgrade2018_design_IdealBS_v7)
.  [94X_upgrade2018_realistic_v9](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_upgrade2018_realistic_v9/94X_upgrade2018_realistic_v7)
.  [94X_upgrade2018cosmics_realistic_deco_v7](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_upgrade2018cosmics_realistic_deco_v7/94X_upgrade2018cosmics_realistic_deco_v6)

## 2017 MC GT
.  [94X_mc2017_design_IdealBS_v12](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_mc2017_design_IdealBS_v12/94X_mc2017_design_IdealBS_v11)
.  [94X_mc2017_realistic_v16](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_mc2017_design_IdealBS_v12/94X_mc2017_design_IdealBS_v11)
.  [94X_mc2017cosmics_realistic_deco_v13](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_mc2017cosmics_realistic_deco_v13/94X_mc2017cosmics_realistic_deco_v11)
.  [94X_mc2017cosmics_realistic_peak_v12](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_mc2017cosmics_realistic_peak_v12/94X_mc2017cosmics_realistic_peak_v11)

### CODE REVIEW

**Comment by lpernie** [comment]
please test

**Comment by lpernie** [comment]
please test

**Comment by lpernie** [comment]
+1

**Comment by lpernie** [comment]
backport #24381

**Comment by fabiocos** [comment]
@lpernie could you please move this PR on 9_4_X? I may move the target release manually, but I see I get a messy merge history in that case

**Comment by fabiocos** [comment]
@lpernie @franzoni I have raised the question about backward compatibility for physics in case this fix is merged, it would affect new productions. May be this is what we want, but it should be explicitly agreed...

**Comment by lpernie** [comment]
Hello @fabiocos , indeed we just agreed that it would be better to do not merge this PR for the moment.
We are investigating the time needed for the availability of the JEC fix for Data, and check if is worth it to redo the miniAOD campaign at the light of these new fixes. We will represent the PR only if this is the case.

**Comment by fabiocos** [comment]
@lpernie thank you

**Pull request closed without merging**
