### PR TITLE
Phase2-hgx315B Modify some of the test scripts for HGCal Geometry

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Modify some of the test scripts (use the same script for a number of geometry versions) for HGCal Geometry

#### PR validation:

Tested the modified scripts

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
+1

**Comment by bsunanda** [comment]
@srimanob Please sign this

**Comment by srimanob** [comment]
+Upgrade

Updating the test script, no change in any upgrade workflows.

**Comment by perrotta** [comment]
+1

**Pull request merged**
