### PR TITLE
recover original behaviour: do not write .jsndata files for empty lumisections

### PR DESCRIPTION
**Pull request by fwyzard**

### CODE REVIEW

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
+1

**Comment by fwyzard** [comment]
@smorovic does this look ok ?

**Comment by smorovic** [comment]
@fwyzard looks ok, but I will take the changes and run a few tests just to be sure we get the same behavior.

**Comment by smorovic** [comment]
@fwyzard I ran a test with HLTRates stream (L1Rates changes are equivalent) in VM FFF cluster, having one FU with empty lumisection and one with data in the run. In both cases output format is correct in the output side.
I.e. it all looks and works ok.

**Comment by fwyzard** [comment]
@smorovic thank you

**Comment by fwyzard** [comment]
thank you

**Comment by davidlange6** [comment]
Hi @fwyzard - please provide a master branch version - thanks

**Comment by fwyzard** [comment]
done: #19045

**Pull request merged**
