### PR TITLE
run2-alca105 Correct a few macro's and the main analysis routine for studying SPR

### PR DESCRIPTION
**Pull request by bsunanda**
Macro's are used for calibrating energy scale factor using isolated charged hadrons. StudyHLT is the analyzer to study single particle response from low luminosity runs.

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by davidlange6** [comment]
please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by ghellwig** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
