### PR TITLE
[L1-UPGRADE] Applying code checks/format

### PR DESCRIPTION
**Pull request by smuzaffar**
This PR applies clang-format and clang checks to source files which were missed during previous code-format campaigns.

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by aloeliger** [comment]
+l1

**Comment by smuzaffar** [comment]
@cms-sw/upgrade-l2 can you please review this? This only contains trivial code format update

**Comment by smuzaffar** [comment]
@Moanwar, @srimanob, @subirsarkar can youplease sign it for upgrade?

**Comment by subirsarkar** [comment]
+Upgrade

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
