### PR TITLE
Pixel code cleanup 10_3

### PR DESCRIPTION
**Pull request by OzAmram**
Small cleanup for pixel code. Mostly just removing blocks of commented out code that are old and not used. Removed one unused function (isFlipped). Also set the 2D template label is ESProducer to the correct default for current and future GT's. Tested on pixeltrees to produce exactly the same output. 

@pmaksim1  @perrotta @slava77 @fabiocos @makortel @tvami @tsusa @cmantill @schuetzepaul

### CODE REVIEW

**Comment by pmaksim1** [comment]
Just to mention that we are also trying to get rid of all the "magic numbers" for the errors (e.g. when various things fail), but we haven't converged on how exactly to do that, but hopefully we'll figure it out by the deadline for 10.4.

Anyway, we march forward in small steps...

**Comment by tocheng** [comment]
Hello @pmaksim1, may I ask the reason to remove the "isFlipped"?
Is it because you don't need it or you have a better way doing that?
Thanks!

**Comment by OzAmram** [comment]
Hi @tocheng. I removed isFlipped because it was not needed and not used anywhere as far as I could tell.

**Comment by pmaksim1** [comment]
But, @tocheng , if you do use it, then we will of course keep it.

An additional approach is to move it somewhere else.  There is other code (e.g. stuff used by FastSim) which we will move later.  So if you need it, we'll uncomment it and then we can discuss a better place to put it.

**Comment by tocheng** [comment]
@OzAmram @pmaksim1 Thanks for the information. I don't use the function, just want to double check with you the motivation to remove the function.

**Comment by tocheng** [comment]
+1

**Comment by perrotta** [comment]
+1
- Rather trivial cleanup, with no effect on reco outputs, as expected
- Jenkins tests pass

**Comment by fabiocos** [comment]
+1

**Pull request merged**
