### PR TITLE
Prevent disabing of HGCal electron cluster preselection 94x

### PR DESCRIPTION
**Pull request by nsmith-**
Forward port of #20588

### CODE REVIEW

**Comment by perrotta** [comment]
assign upgrade

**Comment by perrotta** [comment]
please test

**Comment by kpedro88** [comment]
Observations from the comparisons:

1. A couple fewer gsf electrons from multiclusters:
gsf ele multicl

2. ~65% decrease in number of electron merged seeds:
ele merged seeds

3. Slight change in EB rechits:
eb rechits

4. ~50% decrease in ECAL driven gsf electrons (not from multiclusters):


Are all of these changes expected?

**Comment by nsmith-** [comment]
These are all no pileup PhaseII tests, right?
1. I might have expected more of a change, but perhaps the RecHits in the multiclusters are sorted in a way that having the first element be from HcalEndcap is rare.
2. This is fully expected.
3. I do not know how the change I made could have any impact on RecHits, they are earlier in the reco, maybe something is not deterministic there?
4. This is fully expected.

**Comment by kpedro88** [comment]
Yes, these are noPU workflows.

I found where the `reducedEcalRecHitsSequence` is [defined](https://github.com/cms-sw/cmssw/blob/master/RecoEcal/EgammaClusterProducers/python/reducedRecHitsSequence_cff.py) and it does use input from clustering, so maybe that explains the slight change.

**Comment by nsmith-** [comment]
Oh so it is downstream.  Still, in principle I think barrel clusters should have been untouched, but maybe if they are on the edge of the barrel they get flagged as interesting.

**Comment by kpedro88** [comment]
The changes in gsf electrons might be close enough to barrel eta values to be of interest:
gsf ele eta

@perrotta what do you think?

**Comment by perrotta** [comment]
@kpedro88 @nsmith- 
The explanation for the slightly reduced number of reducedEcalRecHitsEB does make sense: reduced recHits are kept in a 5x5 eta/phi matrix around the cluster.
My next question is: why we don't see any effect to the reducedEcalRecHitsEE, instead?

**Comment by perrotta** [comment]
Answering my question myself: because reducedEcalRecHitsEE are empty in the phase2 outputs (independently of this PR). I imagine this is a consequence of the replacement of the endcap calorimetry with the HGCal, but maybe someone here can confirm.

**Comment by davidlange6** [comment]
yes... that is correct

**Comment by perrotta** [comment]
Looking at the logs of the reco step, I notice that this PR also prevents the following error message to be printed in approx 1 event out of four in wf 20034:
 "PFBLOCKALGO BUG!!!! Found a SuperCluster in a block by itself!"
(this is also visible in event nr 4 of the 5 events run by jenkins in the automatic tests: while running the same wf on 100 events I get 23 times that message)

The message is issued by RecoParticleFlow/PFProducer/plugins/PFEGammaProducer.cc, and this looks to me as another confirmation that this fix may be deserved.

**Comment by perrotta** [comment]
+1
- This is a bugifx, explained in detail in https://github.com/cms-sw/cmssw/pull/20588#issue-258876324 and https://github.com/cms-sw/cmssw/pull/20588#issuecomment-330596806
- It can clean up electron seeds, especially in high PU events
- Distributions in the phase2 workflows automatically run by jenkins are shown in https://github.com/cms-sw/cmssw/pull/20591#issuecomment-331189688 and discussed in https://github.com/cms-sw/cmssw/pull/20591#issuecomment-331269964 and following entries in the thread, and found in agreement with the expectations
- One should check if the efficiency is affected with some larger stat, but in any case the bug has to be fixed, and I don't see that check as a showstopper

**Comment by kpedro88** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
