### PR TITLE
Added PSetTemplate to allow description of a PSet

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

This is used in conjunction with required or optional functionality to describe the allowed parameters of a PSet.

#### PR validation:

The python unit tests pass.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
The unit test failure is from the IB, not this pull request

**Comment by christopheralanwest** [comment]
The failure will be resolved with the merging of #31729, which was intended to be merged at the same time as #31780.

**Comment by makortel** [comment]
+1

Could you update the documentation https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideAboutPythonConfigFile#Parameters_without_defaults with the `allowAnyLabel_` and `PSetTemplate`?

**Comment by Dr15Jones** [comment]
@makortel documentation has been updated.

**Comment by silviodonato** [comment]
+1

**Comment by silviodonato** [comment]
merge

**Pull request merged**
