### PR TITLE
Run3-gem37 Complete construction of MuonGeometryConstants (also for dd4hep)

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Complete construction of MuonGeometryConstants (also for dd4hep)

#### PR validation:

Use the cfg files in Geometry/MuonNumbering/test

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@silviodonato @smuzaffar Please take a look at the the current IB. 136.88811 fails in all PR's

**Comment by silviodonato** [comment]
@bsunanda thanks, we know about that issue, it should be fixed by #29826

**Comment by ianna** [comment]
please test

**Comment by cvuosalo** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
