### PR TITLE
Fix upper bound of the scale in SUEP shower simulation

### PR DESCRIPTION
**Pull request by tvami**
#### PR description:

SUEP simulations have a bug with the upper bound of the scale to be fixed at 2.0, this PR fixes that (credit to @cericeci).

The change was validated by the analysis team and private samples were shown at
https://indico.cern.ch/event/1157541/#24-suep-signal-details
Now they are requesting official samples so we need it in CMSSW.

#### PR validation:

This PR has no effect on bkg samples, or most of the signal samples, it's only relevant to SUEP showers with Pythia. See the link above for the validation by analysts.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Should be backported to both 12_4_X (for Run-3 samples) and 10_6_X (for UL)

### CODE REVIEW

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
diffs in MsgLogger only

**Comment by menglu21** [comment]
Hi @tvami which slide shows the difference between with and w/o the fix

**Comment by menglu21** [comment]
+1

**Comment by tvami** [comment]
@cms-sw/orp-l2 if you have the chance to merge this today, I'll get started doing the backports and hopefully by done by OPR next week

**Comment by rappoccio** [comment]
+1

**Pull request merged**
