### PR TITLE
remove unused KFFittingSmootherESProducer.h

### PR DESCRIPTION
**Pull request by slava77**
`git grep "KFFittingSmootherESProducer\.h"` returns nothing

apparently this was supposed to be removed in #11931

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
> **Failed Tests**: RelVals-INPUT

@smuzaffar @mrodozov 
do we have some inconsistent error reporting?

I see in https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-994807/16101/runTheMatrixINPUT-results/matrixTestsINPUT.log
```
Preparing to run 4.26 ZMuSkim2011A+ZMuSkim2011A+HLTDSKIM+RECODR1reHLT+HARVESTDR1reHLT
2021/06/18 15:33:06 ERROR failed to parse X509 proxy: crypto/tls: failed to parse key: asn1: syntax error: sequence truncated
```
but then the job 4.26 actually completes OK based on the logs

and also the summary of this runTheMatrix test has
```
603 603 600 561 118 41 3 1 1 tests passed, 0 0 0 0 0 0 0 0 0 failed

+ echo ALL_OK
ALL_OK
```

Is this `X509`-related error the reason for the `Failed Tests: RelVals-INPUT` report?

**Comment by smuzaffar** [comment]
@slava77 , yes currently bot parses the final log file and look for `ERROR` keyword in it. If it is there then it marks the test failed. 
I see that in this case there are 6 workflows with messages like `ERROR failed to parse X509 proxy` but test actually ran fine. I can update bot to ignore `ERROR failed to parse X509 proxy`

**Comment by slava77** [comment]
+reconstruction

for https://github.com/cms-sw/cmssw/pull/34179   c9a3bcc
- technical
- compiles and runs

**Comment by qliphy** [comment]
+1

**Comment by qliphy** [comment]
merge

**Pull request merged**
