### PR TITLE
New GT for all scenarios, including Heavy Ion Run2 simulation changes already deployed in 75X and 80X.

### PR DESCRIPTION
**Pull request by diguida**
The new GT for Heavy Ion Run2 simulation required #12180 to be approved.
# Summary of Changes
## RunI Simulation
- **Ideal scenario**: [`76X_mcRun1_design_v11`](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/76X_mcRun1_design_v11): As [`76X_mcRun1_design_v10`](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/76X_mcRun1_design_v10) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/76X_mcRun1_design_v10/76X_mcRun1_design_v11):
  - updated B tag discriminators for HLT with the following taggers: `CombinedSVIVFV2RecoVertex`, `CombinedSVIVFV2PseudoVertex`, `CombinedSVIVFV2NoVertex`, `CombinedSVRecoVertex`, `CombinedSVPseudoVertex`, `CombinedSVNoVertex` (as used by HLT data collection in 2015).
- **Realistic scenario**: [`76X_mcRun1_realistic_v11`](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/76X_mcRun1_realistic_v11): As [`76X_mcRun1_realistic_v10`](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/76X_mcRun1_realistic_v10) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/76X_mcRun1_realistic_v10/76X_mcRun1_realistic_v11):
  - updated B tag discriminators for HLT with the following taggers: CombinedSVIVFV2RecoVertex, CombinedSVIVFV2PseudoVertex, CombinedSVIVFV2NoVertex, CombinedSVRecoVertex, CombinedSVPseudoVertex, CombinedSVNoVertex (as used by HLT data collection in 2015).
- **Heavy Ion scenario**: [`76X_mcRun1_HeavyIon_v11`](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/76X_mcRun1_HeavyIon_v11): As [`76X_mcRun1_HeavyIon_v10`](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/76X_mcRun1_HeavyIon_v10) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/76X_mcRun1_HeavyIon_v10/76X_mcRun1_HeavyIon_v11):
  - updated B tag discriminators for HLT with the following taggers: CombinedSVIVFV2RecoVertex, CombinedSVIVFV2PseudoVertex, CombinedSVIVFV2NoVertex, CombinedSVRecoVertex, CombinedSVPseudoVertex, CombinedSVNoVertex (as used by HLT data collection in 2015).
- **Proton-Lead scenario**: [`76X_mcRun1_pA_v11`](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/76X_mcRun1_pA_v11): As [`76X_mcRun1_pA_v10`](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/76X_mcRun1_pA_v10) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/76X_mcRun1_pA_v10/76X_mcRun1_pA_v11):
  - updated B tag discriminators for HLT with the following taggers: CombinedSVIVFV2RecoVertex, CombinedSVIVFV2PseudoVertex, CombinedSVIVFV2NoVertex, CombinedSVRecoVertex, CombinedSVPseudoVertex, CombinedSVNoVertex (as used by HLT data collection in 2015).
## RunII Simulation
- **Ideal scenario**: [`76X_mcRun2_design_v14`](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/76X_mcRun2_design_v14): As [`76X_mcRun2_design_v13`](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/76X_mcRun2_design_v13) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/76X_mcRun2_design_v13/76X_mcRun2_design_v14):
  - updated B tag discriminators for HLT with the following taggers: CombinedSVIVFV2RecoVertex, CombinedSVIVFV2PseudoVertex, CombinedSVIVFV2NoVertex, CombinedSVRecoVertex, CombinedSVPseudoVertex, CombinedSVNoVertex (as used by HLT data collection in 2015).
- **Startup scenario**: [`76X_mcRun2_startup_v13`](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/76X_mcRun2_startup_v13): As [`76X_mcRun2_startup_v12`](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/76X_mcRun2_startup_v12) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/76X_mcRun2_startup_v12/76X_mcRun2_startup_v13):
  - updated B tag discriminators for HLT with the following taggers: CombinedSVIVFV2RecoVertex, CombinedSVIVFV2PseudoVertex, CombinedSVIVFV2NoVertex, CombinedSVRecoVertex, CombinedSVPseudoVertex, CombinedSVNoVertex (as used by HLT data collection in 2015).
- **Asymptotic scenario**: [`76X_mcRun2_asymptotic_v14`](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/76X_mcRun2_asymptotic_v14): As [`76X_mcRun2_asymptotic_v13`](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/76X_mcRun2_asymptotic_v13) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/76X_mcRun2_asymptotic_v13/76X_mcRun2_asymptotic_v14):
  - updated B tag discriminators for HLT with the following taggers: CombinedSVIVFV2RecoVertex, CombinedSVIVFV2PseudoVertex, CombinedSVIVFV2NoVertex, CombinedSVRecoVertex, CombinedSVPseudoVertex, CombinedSVNoVertex (as used by HLT data collection in 2015).
- **Heavy Ion scenario**: [`76X_mcRun2_HeavyIon_v14`](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/76X_mcRun2_HeavyIon_v14): As [`76X_mcRun2_HeavyIon_v12`](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/76X_mcRun2_HeavyIon_v12) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/76X_mcRun2_HeavyIon_v12/76X_mcRun2_HeavyIon_v14):
  - added additional labels for castor sim geometry
  - introduced L1T calo params configuration for HI
  - updated L1T menu with the version used in PbPb collisions
  - updated Castor Gains in order to avoid a lot of saturation (on digi level) in PbPb simulations in CASTOR
  - updated centrality table for HFtowers in 200 bins
  - updated underlying event table with latest estimations from PbPb first collisions
  - updated JEC with HI tracking including L1FastJet corrections set to 1, in order to avoid crashes
  - updated B tag discriminators for HLT with the following taggers: CombinedSVIVFV2RecoVertex, CombinedSVIVFV2PseudoVertex, CombinedSVIVFV2NoVertex, CombinedSVRecoVertex, CombinedSVPseudoVertex, Combin\
    edSVNoVertex (as used by HLT data collection in 2015).
## RunI Data
- **HLT processing**: [`76X_dataRun1_HLT_frozen_v11`](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/76X_dataRun1_HLT_frozen_v11): As [`76X_dataRun1_HLT_frozen_v10`](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/76X_dataRun1_HLT_frozen_v10) (snapshot time set to 2015-12-18 17:00:00 UTC) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/76X_dataRun1_HLT_frozen_v10/76X_dataRun1_HLT_frozen_v11):
  - added HLT label for PF hadron calibration in order to replicate 2015 HLT performance
  - updated B tag discriminators for HLT with the following taggers: CombinedSVIVFV2RecoVertex, CombinedSVIVFV2PseudoVertex, CombinedSVIVFV2NoVertex, CombinedSVRecoVertex, CombinedSVPseudoVertex, CombinedSVNoVertex (as used by HLT data collection in 2015).
- **Offline processing**: [`76X_dataRun1_v16`](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/76X_dataRun1_v16): As [`76X_dataRun1_v15`](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/76X_dataRun1_v15) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/76X_dataRun1_v15/76X_dataRun1_v16):
  - updated B tag discriminators for HLT with the following taggers: CombinedSVIVFV2RecoVertex, CombinedSVIVFV2PseudoVertex, CombinedSVIVFV2NoVertex, CombinedSVRecoVertex, CombinedSVPseudoVertex, CombinedSVNoVertex (as used by HLT data collection in 2015).
## RunII Data
- **HLT processing**: [`76X_dataRun2_HLT_frozen_v11`](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/76X_dataRun2_HLT_frozen_v11): As [`76X_dataRun2_HLT_frozen_v10`](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/76X_dataRun2_HLT_frozen_v10) (snapshot time set to 2015-12-18 17:00:00 UTC) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/76X_dataRun2_HLT_frozen_v10/76X_dataRun2_HLT_frozen_v11):
  - updated B tag discriminators for HLT with the following taggers: CombinedSVIVFV2RecoVertex, CombinedSVIVFV2PseudoVertex, CombinedSVIVFV2NoVertex, CombinedSVRecoVertex, CombinedSVPseudoVertex, CombinedSVNoVertex (as used by HLT data collection in 2015).
- **HLT Heavy Ion processing**: [`76X_dataRun2_HLTHI_frozen_v2`](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/76X_dataRun2_HLTHI_v2): As [`76X_dataRun2_HLTHI_v1`](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/76X_dataRun2_HLTHI_v1) (snapshot time set to 2015-12-18 17:00:00 UTC) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/76X_dataRun2_HLTHI_v1/76X_dataRun2_HLTHI_v2):
  - updated B tag discriminators for HLT with the following taggers: CombinedSVIVFV2RecoVertex, CombinedSVIVFV2PseudoVertex, CombinedSVIVFV2NoVertex, CombinedSVRecoVertex, CombinedSVPseudoVertex, CombinedSVNoVertex (as used by HLT data collection in 2015).
- **Offline processing**: [`76X_dataRun2_v16`](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/76X_dataRun2_v16): As [`76X_dataRun2_v15`](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/76X_dataRun2_v15) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/76X_dataRun2_v15/76X_dataRun2_v16):
  - updated B tag discriminators for HLT with the following taggers: CombinedSVIVFV2RecoVertex, CombinedSVIVFV2PseudoVertex, CombinedSVIVFV2NoVertex, CombinedSVRecoVertex, CombinedSVPseudoVertex, CombinedSVNoVertex (as used by HLT data collection in 2015).
## Upgrade 2017 simulation
- **Ideal scenario**: [`76X_upgrade2017_design_v9`](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/76X_upgrade2017_design_v9): As [`76X_upgrade2017_design_v8`](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/76X_upgrade2017_design_v8) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/76X_upgrade2017_design_v8/76X_upgrade2017_design_v9):
  - updated B tag discriminators for HLT with the following taggers: CombinedSVIVFV2RecoVertex, CombinedSVIVFV2PseudoVertex, CombinedSVIVFV2NoVertex, CombinedSVRecoVertex, CombinedSVPseudoVertex, CombinedSVNoVertex (as used by HLT data collection in 2015).

### CODE REVIEW

**Comment by diguida** [comment]
please test

**Comment by diguida** [comment]
+1

**Comment by davidlange6** [comment]
cmsbuild, please test

ok - #12180 is approved now, so I will retest this - I'm not sure the ORP notes are correct that imply that this PR depends on #12180 - seems rather that there is another piece for HI that does. Maybe @mmusich or @franzoni can clarify.

**Comment by mmusich** [comment]
@davidlange6 
Indeed the Run2 Heavy Ion GT was not updated in this PR pending the approval #12180. @diguida should update the PR with the new Global Tag:  

```
'run2_mc_hi'        :   '76X_mcRun2_HeavyIon_v13',
```
Actually there are some other changes that have accumulated in the queue in the meanwhile that probably deserve a further version of the GT:

https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/76X_mcRun2_HeavyIon_v13/76X_mcRun2_HeavyIon_Queue

**Comment by mmusich** [comment]
Acutally  '76X_mcRun2_HeavyIon_v14' with all the desired features already exists. That's the one to be used.

**Comment by diguida** [comment]
@mmusich @davidlange6 The GT queue `76X_mcRun2_HeavyIon_Queue` has been always kept up-to-date with the latest changes for HI MC deployed in 75X and 80X, while waiting for #12180 to be approved. `76X_mcRun2_HeavyIon_v14` was built by me once the HI MC conditions were frozen, i.e. putting the same changes as in `80X_mcRun2_HeavyIon_v0` for the development cycle and `75X_mcRun2_HeavyIon_v12` for the HI MC campaign. Now, it is time to update the branch here.

**Comment by diguida** [comment]
please test
Rebased on top of latest IB and added HI Run2 MC changes.

**Comment by diguida** [comment]
wow! ICE!!

**Comment by diguida** [comment]
very strange: we are not re-compiling any library...

**Comment by diguida** [comment]
please test
let's retry.

**Comment by mmusich** [comment]
+1

**Comment by diguida** [comment]
Run2 HI MC wf in the test matrix are ok:

````
$ runTheMatrix.py -l 140.1,140.2,140.4,145.0 -i all
140.1_QCD_Pt_80_120_13_HI+QCD_Pt_80_120_13_HIINPUT+DIGIHI+RECOHI+HARVESTHI Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED  - time date Thu Jan  7 17:14:27 2016-date Thu Jan  7 17:07:52 2016; exit: 0 0 0 0
140.2_PhotonJets_Pt_10_13_HI+PhotonJets_Pt_10_13_HIINPUT+DIGIHI+RECOHI+HARVESTHI Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED  - time date Thu Jan  7 17:14:28 2016-date Thu Jan  7 17:07:55 2016; exit: 0 0 0 0
140.4_ZEEMM_13_HI+ZEEMM_13_HIINPUT+DIGIHI+RECOHI+HARVESTHI Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED  - time date Thu Jan  7 17:14:29 2016-date Thu Jan  7 17:08:00 2016; exit: 0 0 0 0
145.0_HydjetQ_MinBias_5020GeV+HydjetQ_MinBias_5020GeVINPUT+DIGIHI+RECOHI+HARVESTHI Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED  - time date Thu Jan  7 17:22:22 2016-date Thu Jan  7 17:08:01 2016; exit: 0 0 0 0
4 4 4 4 tests passed, 0 0 0 0 failed
````

**Pull request merged**
