### PR TITLE
fixing PNET DQM module

### PR DESCRIPTION
**Pull request by rgerosa**
Backport of [PR39272](https://github.com/cms-sw/cmssw/pull/39272) in 12-5-X as requested by release managers. It involves small changes in the PNET trigger DQM monitoring.

### CODE REVIEW

**Comment by emanueleusai** [comment]
please test

**Comment by rgerosa** [comment]
it seems (if I am not wrong) that there were timeouts in running over some relval inputs. Hence errors are not related to this PR.

**Comment by perrotta** [comment]
please test
(yes, relval-input errors are unrelated, but let retest anyhow)

**Comment by perrotta** [comment]
backport of https://github.com/cms-sw/cmssw/pull/39272

**Comment by emanueleusai** [comment]
+1

- differences in L1T Phase2 most likely caused by https://github.com/cms-sw/cmssw/pull/39303 not being included in IB yet

**Comment by perrotta** [comment]
+1

**Pull request merged**
