### PR TITLE
Single electron paths from CMSHLT-330 for Top validation code in 75X

### PR DESCRIPTION
**Pull request by ebouvier**
This is PR to update the Top PAG validation and offline DQM codes accordingly to CMSSHLT-330 JIRA ticket. See #8857 for 74X.

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by ebouvier** [comment]
The same error occur in #8865 and  #8807. It does not seem to be related to this PR.

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
