### PR TITLE
Dqm binbybin fix

### PR DESCRIPTION
**Pull request by andrius-k**
#### PR description:

This PR adds more debug information about root files that were produced. It also adds support for recent bot changes where a list of all PRs under test is given. 

#### PR validation:

Code was tested locally.

### CODE REVIEW

**Comment by andrius-k** [comment]
please test

**Comment by andrius-k** [comment]
+1

**Comment by fabiocos** [comment]
@andrius-k looking at the result of this test I am not sure that the listing of PRs is what you were expecting, for sure it is not giving the PR sequential number but the commit id I would say...

**Comment by andrius-k** [comment]
@fabiocos Yes, PULL_REQUEST_NUMBER is now the hash of all PRs being tested. This PR addresses exactly this issue. The PR essentially makes sure that the results are presented in nice and understandable fashion.

**Comment by fabiocos** [comment]
+1

**Comment by smuzaffar** [comment]
@andrius-k , this needs to go in 10.6.X too otherwise comparions tests for Bin-By-Bin will fail once https://github.com/cms-sw/cms-bot/pull/1143 is merged.

**Comment by andrius-k** [comment]
@smuzaffar Just opened a backport to 10_6_X: #26929

**Pull request merged**
