### PR TITLE
fix a bunch of tests broken by cms-sw/cmssw#46582

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

Title says it all, addresses https://github.com/cms-sw/cmssw/pull/46582#issuecomment-2458927028

#### PR validation:

`scram b runtests` runs.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

N/A - not needed.

### CODE REVIEW

**Comment by mmusich** [comment]
test parameters:
   * enable = hlt_p2_integration, hlt_p2_timing

**Comment by srimanob** [comment]
Thx @mmusich 
It seems this does not cover all remainings, but one needed for IB test. We can go ahead with this, and I will do the rest after this PR is merged.

**Comment by srimanob** [comment]
@cmsbuild please test

**Comment by mmusich** [comment]
> It seems this does not cover all remainings, but one needed for IB test

not sure, to understand, what's missing?

**Comment by srimanob** [comment]
If we look on
https://github.com/search?q=repo%3Acms-sw%2Fcmssw+GeometryExtended2026D&type=code&p=1
we will see some missings, i.e. in 
[SimGeneral/Debugging/python/caloParticleDebugger_cfg.py](https://github.com/cms-sw/cmssw/blob/12ead85fa72b713b7a294c3cbf6d80728c1ea71a/SimGeneral/Debugging/python/caloParticleDebugger_cfg.py#L11)
[L1Trigger/TrackerDTC/test/testDAQ_cfg.py](https://github.com/cms-sw/cmssw/blob/12ead85fa72b713b7a294c3cbf6d80728c1ea71a/L1Trigger/TrackerDTC/test/testDAQ_cfg.py#L13)
which my scan missed.

I also want to update the filenames and related calls, e.g.
```
CondTools/Geometry/test/calogeometry2026writer.py
CondTools/Geometry/test/geometry2026test_local.py
CondTools/Geometry/test/writehelpers/geometryExtended2026_writer.py
CondTools/Geometry/test/writehelpers/geometryExtended2026_xmlwriter.py
```

They do not need to get green lights in ib. If you would like to include in your PR, you can go ahead. Or I will do it later.

**Comment by mmusich** [comment]
>  we will see some missings

OK, but these are untested, which means we can assume them by default broken.

**Comment by srimanob** [comment]
> > we will see some missings
> 
> OK, but these are untested, which means we can assume them by default broken.

Right. One which include already, or missing, some of them are broken by default (link to non-existing geometry, ... etc). But I think I will update them all, and also clean up.

**Comment by fabiocos** [comment]
@srimanob why forcing a default here, since the choice of the version is left free elsewhere? I mean unit tests like those in ```RecoMTD/DetLayers``` or ```SimG4CMS/Forward```. This can be practical for standard unit test behaviour, less for development use of the cfgs... Of course it can be bypassed by overwriting the default, but the logic does not seem uniform everywhere.

**Comment by mmusich** [comment]
> why forcing a default here, since the choice of the version is left free elsewhere? 

it should be forced wherever it's tested.

**Comment by mmusich** [comment]
@srimanob 

> One which include already, or missing, some of them are broken by default (link to non-existing geometry, ... etc). But I think I will update them all, and also clean up.

if you're interested I fixed the rest of them in [this commit](https://github.com/cms-sw/cmssw/commit/58f487df2406e539548e0bda30ecb54ba333d27d).

I tested them with this script:

```bash
#!/bin/bash

# Log file to store cmsRun output
log_file="cmsRun_output.log"

# Initialize counters for successful and failed runs
success_count=0
fail_count=0

# Clear the log file at the start of each run
> "$log_file"

# List of modified files to run with cmsRun
files=(
    "CalibCalorimetry/EBPhase2TPGTools/test/runEBPhase2TPParamProducer.py"
    "CondTools/Geometry/test/calogeometry2026writer.py"
    "CondTools/Geometry/test/hgcalgeometrywriter.py"
    "CondTools/Geometry/test/me0geometrywriter.py"
    "CondTools/Geometry/test/writehelpers/geometryExtended2026_writer.py"
    "CondTools/Geometry/test/writehelpers/geometryExtended2026_xmlwriter.py"
    "DQM/Physics/test/topDQM_production_cfg.py"
    "DetectorDescription/OfflineDBLoader/test/dumpGeom_cfg.py"
    "Geometry/CaloTopology/test/testHGCalTopology_cfg.py"
    "Geometry/GEMGeometryBuilder/test/python/validateME0GeometryOldDD_cfg.py"
    "Geometry/GlobalTrackingGeometryBuilder/test/testGlobalTrackingGeometry_cfg.py"
    "Geometry/HGCalCommonData/test/python/testHGCalWaferID_cfg.py"
    "L1Trigger/Phase2L1GT/test/test_GT.py"
    "L1Trigger/Phase2L1Taus/test/produceHPSPFTaus_cfg.py"
    "L1Trigger/TrackerDTC/test/testDAQ_cfg.py"
    "L1Trigger/TrackerDTC/test/test_cfg.py"
    "L1Trigger/VertexFinder/test/vertexNTupler_cfg.py"
    "RecoLocalMuon/GEMCSCSegment/test/runGEMCSCCoincidenceRateAnalyzer_cfg.py"
    "RecoTauTag/RecoTau/test/runDeepTauIDsOnMiniAOD.py"
    "SimCalorimetry/EcalEBTrigPrimProducers/test/testPhase2_13_1_0_pre3.py"
    "SimGeneral/Debugging/python/caloParticleDebugger_cfg.py"
    "SimTracker/SiPhase2Digitizer/test/PixelTestBeamValidator_cfg.py"
    "Validation/Geometry/test/runP_Mtd_cfg.py"
    "Validation/Geometry/test/runP_TrackerPhase2TkBE_cfg.py"
    "Validation/MtdValidation/test/mtdHarvesting_cfg.py"
    "Validation/MtdValidation/test/mtdValidation_cfg.py"
    "Validation/SiTrackerPhase2V/test/ValidateRecHit_TrackerPhase2Standalone_cfg.py"
)

# Loop through each file, run cmsRun, and log output
for file in "${files[@]}"; do
    echo "Running cmsRun for $file..." | tee -a "$log_file"
    
    # Run cmsRun and capture output
    if cmsRun "$file" >> "$log_file" 2>&1; then
        echo "Success: $file" | tee -a "$log_file"
        ((success_count++))
    else
        echo "Failure: $file" | tee -a "$log_file"
        ((fail_count++))
    fi
done

# Final summary
echo "" | tee -a "$log_file"
echo "Summary:" | tee -a "$log_file"
echo "Total tests run: $((success_count + fail_count))" | tee -a "$log_file"
echo "Successful tests: $success_count" | tee -a "$log_file"
echo "Failed tests: $fail_count" | tee -a "$log_file"
```

as expected:

```

Summary:
Total tests run: 27
Successful tests: 3
Failed tests: 24
```

**Comment by srimanob** [comment]
FYI @bsunanda 
As fixes are covering the rest. Let's discuss here.

**Comment by bsunanda** [comment]
@mmusich @srimanob I am working on many in Geometry area. Please avoid them and also in SimG4Core and SimG4CMS
________________________________

**Comment by mmusich** [comment]
> am working on many in Geometry area. Please avoid them and also in SimG4Core and SimG4CMS

i don't understand why I should avoid them.

**Comment by bsunanda** [comment]
If we work on the same files it unnecessarily creates conflicts and I have lost a few days work  that way
________________________________

**Comment by mmusich** [comment]
> If we work on the same files it unnecessarily creates conflicts and I have lost a few days work  that way

I am not pushing any more commits to this PR (anyway the rest of the files is heavily broken besides the geometry, as the simple test [above](https://github.com/cms-sw/cmssw/pull/46608#issuecomment-2459217669).

**Comment by bsunanda** [comment]
Please do all other files except the ones in SimG4Core, SimG4CMS and Geometry
________________________________

**Comment by mmusich** [comment]
> Please do all other files except the ones in SimG4Core, SimG4CMS and Geometry

I did touch some files in `Geometry/MTD*` in this PR (that are currently broken).  If you wish to further work on them you can make it in a follow-up PR.

**Comment by srimanob** [comment]
Hi @mmusich @bsunanda 
Thanks to look into it. For this PR, let's go as it is, to fix the IB test. We then move to Geometry PR from @bsunanda 
Then I will recheck again if we have some remaining which should be updated, i.e. filenames and related calls.

@fabiocos I think the idea was to move all to defaults one. It was the goal when we put the default one as a placeholder.
However, DPG has a free choice to have dedicated tests to specific geometries if need. But having them run in ib is not a good idea to me.

**Comment by mmusich** [comment]
@smuzaffar it looks like test `hlt-p2-integration` has problem starting. I noticed the same earlier in https://github.com/cms-sw/cmssw/pull/46539. Do you have any idea if / where there is a problem?

**Comment by fabiocos** [comment]
@srimanob @mmusich fine for me moving tests to a default, at the end of the day it is enough to change it once to test a new scenario. But then this update needs to be propagated also in those other cases.

**Comment by mmusich** [comment]
>  But then this update needs to be propagated also in those other cases.

it would be good to document all the configurations that need to be update. If you know of other cases, please create such an issue.

**Comment by mmusich** [comment]
+hlt
   * local test pass, unclear why `hlt-p2-integration` doesn't run (it looks a cms-bot infrastructural issue not related to the PR)

**Comment by srimanob** [comment]
> @srimanob @mmusich fine for me moving tests to a default, at the end of the day it is enough to change it once to test a new scenario. But then this update needs to be propagated also in those other cases.

Yes, this is my plan. When this migration is done, I will go back and look on all test files which still be detector-specific and move them to default if agree.

It is part of
https://github.com/cms-sw/cmssw/issues/42945

**Comment by mmusich** [comment]
urgent
   * to fix broken unit tests in IBs

**Comment by smuzaffar** [comment]
> @smuzaffar it looks like test `hlt-p2-integration` has problem starting. I noticed the same earlier in #46539. Do you have any idea if / where there is a problem?

 `hlt-p2-integration` is [running now](https://cmssdt.cern.ch/jenkins/job/ib-run-pr-hlt_p2_integration/9/console)

**Comment by perrotta** [comment]
+1

**Comment by Moanwar** [comment]
+Upgrade

**Comment by civanch** [comment]
+1

my impression is that there is no overlaps with @bsunanda PRs.

**Comment by mmusich** [comment]
@cms-sw/dqm-l2 @cms-sw/reconstruction-l2 please sign, so that we can clean the 23:00 IB.

**Comment by mmusich** [comment]
> Do we understand why we see failure comparisons across all Phase-2?

yes. https://github.com/cms-sw/cmssw/issues/46416

**Comment by jfernan2** [comment]
+1

**Comment by antoniovagnerini** [comment]
+1
- spurious differences from HGCal DQM test (open issue  #46416)

**Comment by mmusich** [comment]
@cms-sw/orp-l2 kind ping to merge this (it restores some functionality broken earlier, and other PRs depend on the availability of these tests).

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
