### PR TITLE
Run3-gex153X Backport #40783 to CMSSW version 13_0_X the 2023 Geometry modified because of shifted positions of GE21 Chambers

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Backport #40783 to CMSSW version 13_0_X the 2023 Geometry modified because of shifted positions of GE21 Chambers

#### PR validation:

Use the runTheMatrix test workflows

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport #40783 to CMSSW_13_0_X

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by civanch** [comment]
Let us sign this PR and merge. The master one https://github.com/cms-sw/cmssw/pull/40783 is already merged. This one does not affect any WF, because by default geometry is taken from DB.  

This PR is needed, because 13_0 is the baseline for 2023 production, so XML version of the geometry should correspond to the DB one.

**Comment by bsunanda** [comment]
@srimanob Please sign this PR so that it can get into 13_0 release

**Comment by srimanob** [comment]
+Upgrade

**Comment by perrotta** [comment]
+1
- As [stated](https://github.com/cms-sw/cmssw/pull/40783#issuecomment-1438267405) when merging the corresponding PR in the master, we currently rely on some private validation made by @bsunanda, but before using for 2023 (i.e. enabling the modified geometry via db) a complete validation by the GEM group is mandatory

**Pull request merged**
