### PR TITLE
Added new attributes to FillInfo and created update script for acron schedule.

### PR DESCRIPTION
**Pull request by coder-amey**
Hello, @franzoni, @arunhep, @lpernie and @ggovi.

@ravindkv and I have made the following modifications to the FillInfo package:

- The following attributes have been added to the package by modifying FillInfo.cc, FillInfo.h and FillInfoPopConSourceHandler.cc files:
  - lumiPerBx as CMS_BEAM_COND.CMS_LHC_LUMIPERBUNCH.INSTLUMI_BUNCH (vector\<float\>)
  - delivLumi as MAX(RUNTIME_LOGGER.LUMI_SECTIONS.DELIVLUMI) (float)
  - recLumi as MAX(RUNTIME_LOGGER.LUMI_SECTIONS.LIVELUMI) (float)
- The FillInfoUpdate.sh script has been designed for acron to schedule jobs.
- FillInfoUpdate.sh script increments the previous fill numbers by a specific interval, runs the FillInfoPopConAnalyzer.py script and logs the details for every run.

Thus, we have added new variables to the package which can now be triggered with acron using the FillInfoUpdate.sh script.
We have also resolved the mergeability issues of our previous [pull request](https://github.com/cms-sw/cmssw/pull/21921) by rebasing to a newer CMSSW release (10_0_0_pre32).

I request you to kindly scrutinize our work and provide us with your valuable suggestions so that we can improve this pull request and get it merged.

Thank you for your time.

Sincerely,
Amey & Ravindra.

### CODE REVIEW

**Comment by ghellwig** [comment]
please test

**Comment by fabiocos** [comment]
@ghellwig @lpernie @arunhep @ggovi is there any issue with this PR keeping it on hold?
@coder-amey is this development still needed?

**Comment by lpernie** [comment]
Hi @fabiocos , yes developments are still needed for this PR.
We hope to have news soon.

**Comment by ggovi** [comment]
@coder-amey 
As discussed, the FillInfo CondFormats class need to be replaced by a new class with a flexible layout, capable to add parameters upon request without to violate the schema evolution contraints.
The new CondFormats is here: #22473 
Please close this PR. The changes need to be integrated with the new Class once it appears in the IB

**Comment by coder-amey** [comment]
The development of a flexible CondFormats class can be viewed [here](https://github.com/cms-sw/cmssw/pull/22527).
This pull request is now closed.

**Pull request closed without merging**
