### PR TITLE
Fixed TotemRPGeometry to be const correct

### PR DESCRIPTION
**Pull request by Dr15Jones**
Changed const functions so they returned pointers to const objects.
Changes functions to return const & or to take const & as arguments to avoid unnecessary copying.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
This showed up as a thread-unsafe EventSetup data product.

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
