### PR TITLE
Hgcal v7geometry xml files

### PR DESCRIPTION
**Pull request by vandreev11**
@bsunanda @pfs @lgray HGCAL V7 geometry (TP) material structure implementation. The sizes will be modified to avoid conflicts (execessive Z-dimention). Useful to commit already now.

### CODE REVIEW

**Comment by lgray** [comment]
@vandreev11 Please make a pull requests for features that are mostly final (that or we modify this PR until you're happy). 76X is a bit of a different beast from 62X_SLHC. Unless no one has a problem to take unfinished features into a pre-release.

**Comment by lgray** [comment]
@kpedro88 @sethzenz

**Comment by vandreev11** [comment]
@lindsey The features mostly final, it is TP geometry structure. The thing is the HGC+BH total length is a bit out of the allowed range. There is no problem to  modify, I am waiting a suggestion from TP-design authors on what can be shrunk. In meantime this is the base to start a development of hexagonal segmentation. V5 should be fine for the clustering optimization at the same time.

**Comment by lgray** [comment]
@vandreev11 OK that makes more sense.

**Comment by lgray** [comment]
@vandreev11 Could you please update the description of the PR to state what you said in your message yesterday? Just so it's clear what's going on looking through the history.

**Comment by lgray** [comment]
@vandreev11 One more small comment, possibly to add to this PR. Is there any way to test the geometry (or is that coming with the v7 developments later)?

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by ianna** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Comment by lindsey** [comment]
Please remove me from this email string.

**Comment by lgray** [comment]
@lindsey You'll have to press the unsubscribe button yourself (up on the top right). Can't remove you myself.

@vandreev11 my github username is @lgray. Please be more careful in the future.

**Comment by vandreev11** [comment]
@lgray yes, sorry for that

**Pull request merged**
