### PR TITLE
Complete migration from physics tools - cmssw93X

### PR DESCRIPTION
**Pull request by perrotta**
93X version of #22584 (where also the code-checks fixes have been included): the fix is needed for the production of Phase2 MC

As pointed out in the issue #22483 , nearly all classes "migrated" by 60bfee7 have still a copy in PhysicsTools/CandUtils

Code in CMSSW accessed either one or the other implementation, with the same name and often also with the definition in the interface protected by an identical include guard

This PR removes all the duplicate implementations that were left in PhysicsTools/CandUtils, and adapts the classes that still relied on them to use the same (identical) implementations that were migrated longtime ago in CommonTools/CandUtils

### CODE REVIEW

**Comment by perrotta** [comment]
backport of of #22584

**Comment by perrotta** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by perrotta** [comment]
+1
- 93X backport of #22584, now merged in the master
- Duplicated classes in PhysicsTools/CandUtils are been removed, and all code in CMSSW that still accessed them gets modified accordingly
- No effect is expected in reco outputs, none is observed in jenkins tests

**Comment by kpedro88** [comment]
merge

**Pull request merged**
