### PR TITLE
bsunanda:Run2_alca36 bacport the changes to PythiaFilterIsolatedTrack to CMSSW version 7_1_X

### PR DESCRIPTION
**Pull request by bsunanda**
The changes to the filter are integrated with 8_1_X version

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@covarell Could you approve this backporting so that we can make a request for production

**Comment by covarell** [comment]
+1

**Comment by bsunanda** [comment]
@davidlange6 Could you integrate this and if there is a pactch version with this we have to request some MC sample with the filter

**Comment by davidlange6** [comment]
+1

**Pull request merged**
