### PR TITLE
[TkTrackingRegions] Move public headers to interface directory

### PR DESCRIPTION
**Pull request by smuzaffar**
As reported in #34718 , this PR moves headers in interface directory for `TkTrackingRegions`
```
     4 src/RecoTracker/TkTrackingRegions/plugins/GlobalTrackingRegionProducerFromBeamSpot.h
```

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+reconstruction

for https://github.com/cms-sw/cmssw/pull/34870	3cbb3a1
- technical; the incorrect cross-package include appeared first in 85f3fda12a129dae0182fe77867e0326fbc80fe2 in 2011

**Comment by qliphy** [comment]
+1

**Pull request merged**
