### PR TITLE
improve math in broken-line fit [12.0.x]

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Backport #35128 to CMSSW 12.0.x.

#### PR validation:

These changes fix the crash observed during CRuZeT run 344679.

#### If this PR is a backport please specify the original PR and why you need to backport that PR:

Backport of #35128

### CODE REVIEW

**Comment by fwyzard** [comment]
backport #35128

**Comment by fwyzard** [comment]
type bugfix

**Comment by fwyzard** [comment]
please test

**Comment by slava77** [comment]
> Reco comparison results: 2805 differences found in the comparisons

these are all in 11634.911 DD4HEP, which has repeatability issues

**Comment by slava77** [comment]
+reconstruction

for https://github.com/cms-sw/cmssw/pull/35313	477e2c8
- code changes are the same as in the master PR #35128 , which was merged for about 2 weeks already ==> the backport is correct
- jenkins tests pass and comparisons with the baseline show no relevant differences

**Comment by perrotta** [comment]
@slava77 the description of the master version of this PR says "Expect some negligible differences (present even in the unit test)".
They are just possible numerical-level differences, as far as I understand: does it comply with the no-change rule that we must apply now for 12_0_X, for which productions have started already?

**Comment by fwyzard** [comment]
@perrotta I don't think the Patatrack pixel tracking is used anywhere in production, yet.

**Comment by perrotta** [comment]
> @perrotta I don't think the Patatrack pixel tracking is used anywhere in production, yet.
> It's enabled only by the `.501`, `.502`, `.505` and `.506` workflows.

Good point :-)

**Comment by perrotta** [comment]
+1

**Pull request merged**
