### PR TITLE
PPS: direct simulation with xangle distributions

### PR DESCRIPTION
**Pull request by jan-kaspar**
#### PR description:

This is a mostly technical change, making it easier to run the PPS "direct" simulation with realistic xangle distributions (extracted from data). For more details, please refer to [this Proton POG presentation](https://indico.cern.ch/event/952808/contributions/4003276/attachments/2098963/3528490/kaspar_systematics.pdf)

#### PR validation:

The direct simulation is not included in any central workflows (neither in matrix tests). Therefore no changes are expected there.

Some validation plots are available in the above-linked POG presentation.

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by tlampen** [comment]
+alca

**Comment by qliphy** [comment]
+1

**Pull request merged**
