### PR TITLE
Use preferred form of not-equal since python 3 eliminates <>

### PR DESCRIPTION
**Pull request by ericvaandering**
@Dr15Jones said 8_0_X would be a decent place to start getting rid of old python that is not compatible with python 3 but works fine in 2.6/2.7.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by Dr15Jones** [comment]
+1

**Comment by davidlt** [comment]
Should we also cook CMSSW + Python 3.5 IB?

**Comment by davidlange6** [comment]
do we know what externals do / do not support it ?

**Comment by ericvaandering** [comment]
No. Will break for sure as the point of these patches is to get the python as compatible as can be with 3.x while not breaking 2.6 compatibility. Actual python3 compatibility is a whole different animal.

**Comment by davidlt** [comment]
@davidlange6 most of Python packages we ship are not required for CMSSW execution, but it's easy to check since Python 3 is default in Fedora 23. Most critical part is to make sure Framework + Python 3 is fine. Most of other changes should be mechanical.

I can experiment with that a bit on personal branch to see what works or not.

**Comment by slava77** [comment]
@cmsbuild please test
to get a clean set of tests

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/11960	931a199
- technical change affects only test python scripts in reco category
- jenkins tests pass and comparisons with the baseline show no differences

**Pull request merged**
