### PR TITLE
Phase2-hgx279x Remove some overlap (HGCal) and modify debug statements for quick comparison

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Remove some overlap in HGCal geometry and modify debug statements for quick comparison

#### PR validation:

Use the runTheMatrix test workflows

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
The comparison differences are just new simulation histories triggered by the small fixes in the geometry.

**Comment by cvuosalo** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

**Comment by qliphy** [comment]
+1

**Pull request merged**
