### PR TITLE
[12_1_X] Set usedFallback properly, silence file closing printouts in StatisticsSenderService

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

This PR is a combined backport of #36379 and #36403. I think these make sense given the observation of #36375.

#### PR validation:

Unit tests run.

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
+1

**Comment by makortel** [comment]
backport

**Comment by perrotta** [comment]
+1
- Fixes worth being backported in 12_1_X (for whenever a new release will be built...)

**Pull request merged**
