### PR TITLE
 (re)introduce hit pair limit in iterative tracking seeding (port of #24818 )

### PR DESCRIPTION
**Pull request by slava77**
backport of #24818

copy-paste of the description in 104X follows:

This PR is somewhat inspired by issues reported in https://hypernews.cern.ch/HyperNews/CMS/get/tier0-Ops/2014.html

The target module(s) in this PR are of HitPairEDProducer kind.
To define a limit I used a somewhat ad-hoc limit of \~0.5 GB of output data per event.
This leads to 
- a limit of 50M pairs for produceIntermediateHitDoublets = True (producing 2 ints per entry)
- a limit of 12M pairs for produceSeedingHitSets = True (producing 4 rechit pointers per entry)

As a specific case test, I used PromptReco_Run323420_EGamma from the HN thread and find that with this PR the job is expected to be processable:
- single thread RSS peak moves down from 22GB to 7GB
    - 8-thread RSS peak with this PR is around 13GB

Note that I made a guess for a bottom-up limit: for 10K real particles in an event (PU200 has about 10K tracking particles with pt>0.5 GeV and |eta|<4), for at worst \~50 layer pairs (as a still sensible large number)
- 12M limit would correspond to \~4% purity in created pairs
- 50M limit would correspond to \~1% purity in created pairs

This sounds safe enough from these "first principles".

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/24941	a55ba60
- this is the same as the now merged 10_4_X version https://github.com/cms-sw/cmssw/pull/24818	a55ba60
- jenkins tests pass

**Comment by fabiocos** [comment]
hold

not strictly needed for 10_3_X data taking

**Comment by slava77** [comment]
this look useless now for operations purposes

**Pull request closed without merging**
