### PR TITLE
Electron Validation Pt1000 histos

### PR DESCRIPTION
**Pull request by archiron**
The configuration files have been modified and/or added to take electronPt1000 histos into account.
A new branch have bee added (EgammaV/ElectronMcSignalValidatorPt1000).

tests with runTheMatrix.py over 4.22 5.1 135.4 8.0 140.53 4.53 1306.0 101.0 1000.0 1001.0 1330.0 9.0 1003.0 25.0 25202.0 are OK and do not show significant size increase on DQM_V0001*.root files.

pt1000-1

@beaudett

### CODE REVIEW

**Comment by deguio** [comment]
ciao @archiron 
it seems to me that the two files 
- ElectronMcSignalValidatorPt1000_gedGsfElectrons_cfi.py
- ElectronMcSignalPt1000Validator_gedGsfElectrons_cfi.py

are identical in terms of content. could you remove one of those?
thanks,
F.

**Comment by deguio** [comment]
for the record. this PR adds 388 histograms. 230251 bins in total.

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
could this module be on the pre-validation path instead of the validation end path?

**Comment by deguio** [comment]
ciao,
actually this PR is a temporary one to have the high pt samples properly checked during the validation.
I have discussed with @franzoni and we will put in place a specific matrix to be used for high pt samples. this would avoid duplicating all the histograms and have half of them meaningless.

I would keep this one on hold for now waiting to have things properly done on our side.
@archiron sorry for being so late.

F.

**Comment by deguio** [comment]
-1

**Pull request closed without merging**
