### PR TITLE
Removed unneeded include of EDAnalyzer.h from DQM

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

The header is deprecated.

#### PR validation:

Code compiles.

### CODE REVIEW

**Comment by missirol** [comment]
please test

**Comment by missirol** [comment]
+hlt

**Comment by perrotta** [comment]
merge
- Succesfully tested together with #39912
- Quite trivial updates, no need to wait for signatures

**Comment by emanueleusai** [comment]
+1

**Pull request merged**
