### PR TITLE
FullSim GENSIM and FastSim strings update

### PR DESCRIPTION
**Pull request by prebello**
This PR updates FullSim GENSIM and FastSim input strings. It is also related to the request at    #22232  

FYI @fabozzi @fabiocos @kpedro88

### CODE REVIEW

**Comment by prebello** [comment]
please test

**Comment by kpedro88** [comment]
NB this will conflict with #22255, but should be easy to resolve either way.

**Comment by davidlange6** [comment]
Your PR is unmergeable. Please have a look and possibly rebase it.

**Comment by prebello** [comment]
@davidlange6 I have just committed the updated GENSIM strings for 2018 and 2018Design inputs. 
Could you please consider it here or should I start from scratch? 
In addition I tried to solved conflicts from the button above but could not mark it as solved.

**Comment by prebello** [comment]
@davidlange6  It seems I could do it.

**Comment by prebello** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
