### PR TITLE
HGCal 2D Layer Clusters

### PR DESCRIPTION
**Pull request by lgray**
Forward port of #16813.

### CODE REVIEW

**Comment by lgray** [comment]
@cvuosalo I will deal with the code comments soon. Starting this PR so you may continue.

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
+1

For #16840 66f5c81421dc2c91dbe40556537fde261ca684a4

Adds a Phase 2 HGCal clustering algorithm, which does not run by default in standard workflows. There should be no change in monitored quantities.

#16813 is the 81X version of this PR, and it has already been approved, though it may never be merged since 90X is now the target for Phase 2 development.

The code changes are satisfactory, and Jenkins tests against baseline CMSSW_9_0_X_2016-12-06-1100 show no significant differences, as expected, except for a glitch for workflow 136.731 that is unrelated to this PR. Tests of the new clustering are described in #16813 and show no problems.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
