### PR TITLE
multithreading migration for HLT muon 

### PR DESCRIPTION
**Pull request by HuguesBrun**
migration of the HLT muon reconstruction to multithreading safe producers

adding in cc @jhgoh

### CODE REVIEW

**Comment by degano** [comment]
@cmsbuild please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by Dr15Jones** [comment]
+1
Non of the modules show up in the 'module to statics' report from the static analyzer

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/7384	28e06d8
code updates look good
jenkins runs and shows no differences

**Pull request merged**
