### PR TITLE
Baseline for Hermetic Timing Demo (SLHC)

### PR DESCRIPTION
**Pull request by lgray**
@mark-grimes I have to revise the plan a little bit from yesterday, I (unfortunately) remembered that the ToT digitization for HGCal never made it in since it was a late development. Therefore, in order to have all the fast timing information needed it is necessary to make a full new release anyway.

While at it, it seemed prudent to bring in the 4D vertex reconstruction as well, as it exists in SLHCDEV. 
I have a person branch that has more developments here, but that can come later.

This PR is therefore a straight side-port of #11770.

I request that this be merged and a new release be cut, pursuant to the plan for fast timing laid out yesterday in the Upgrade Studies meeting.

### CODE REVIEW

**Comment by lgray** [comment]
@mark-grimes @boudoul Note, this will also require an update to the fast timing workflows that have been used. The correct customization function is 
```
RecoParticleFlow.PandoraTranslator.cust_2023HGCalPandoraMuonPerfectFastTime
```

Please use this when submitting min bias and requested signal samples.

**Comment by mark-grimes** [comment]
please test

**Comment by mark-grimes** [comment]
To explain the delay, @davidlange6 is liaising with upgrade hierarchy to find out production needs and hence offline support requirements.

**Comment by mark-grimes** [comment]
This addition was approved in the 12/Nov upgrade performance studies meeting, apologies for the delay.  All unit test failures are from the missing 'startup' key and unrelated to this PR, except runtestUtilAlgos which is a missing file nothing to do with this PR (#11984 would fix the first issue but I need to modify that PR).

@lgray for a full release the name FastTimingKludge is going to have to change.  Also, introducing a new RecoFTL package for a single subpackage is a little unnecessary.  I'll have a look for a suitable place to put it but suggest one if you have a better idea.  I will also rename in SLHCDEV once this is merged for consistency.
Also need to be stricter about the couts, e.g. [TrackTimeValueMapProducer.cc line 249](https://github.com/cms-sw/cmssw/pull/12290/files#diff-0278f86d3818f20ebcbb6393c3519d68R249) and `if( debug ) cout...` should go to `LogDebug`.

**Comment by lgray** [comment]
Hi Mark, OK It is no problem to change the name. If anything I could put
the FastTimingKludge package into RecoParticleFlow/HermeticTiming, I think
it would be fitting. This package will definitely expand in the future.

I'll change the LogDebug.

Thanks,
-L

**Comment by lgray** [comment]
@mark-grimes Does this sound good to you? If so I'll take care of it tomorrow morning.

**Comment by mark-grimes** [comment]
Sounds ideal to me, I can change SLHCDEV to match once this is in.  If this goes into 8_0_X (which I hope it will eventually) I suspect they will want some unit tests on the error matrices, but that's just my speculation.  After this PR is anything else necessary before cutting a release?

Just to reiterate the official Offline position - 6_2_X_SLHC is closed to new developments except for exceptional cases like this.

**Comment by lgray** [comment]
@cmsbuild please test

@mark-grimes  This should satisfy your code review requests.

**Comment by lgray** [comment]
@mark-grimes  To answer all your questions. This is all that is needed to cut a release. Another, release, following the developments from step 1 will be needed but that is not until next year.

**Comment by mark-grimes** [comment]
merge

All test failures are from missing key or test files.

**Pull request merged**
