### PR TITLE
Check bounds.

### PR DESCRIPTION
**Pull request by rekovic**
#### PR description:

Fix the illegal out of bounds write  issue reported in https://github.com/cms-sw/cmssw/issues/32460

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by rekovic** [comment]
please test

**Comment by silviodonato** [comment]
urgent
for the HLT TDR release (11_1_X)

**Comment by rekovic** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade

**Comment by qliphy** [comment]
+1

**Pull request merged**
