### PR TITLE
Remove link to empty library tcmalloc_minimal. 

### PR DESCRIPTION
**Pull request by gartung**
This will allow the removal of google-pertools-toolfile from cmssw-tool-conf.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
@smuzaffar what is your feeling on this change?

**Comment by smuzaffar** [comment]
@Dr15Jones , after this change cmsRunTC will be identical to cmsRun (for amd64 archs) and cmsRunGlibC (for non adm64). So in this case, do we want to keep this? I would suggest to then fully drop cmsRunTC. 
I personally do not use this executable but @davidlt might be using it for debugging.

**Comment by davidlt** [comment]
+1 for removal of `cmsRunTC` if not needed. Yeah, I was using it for debugging. Only jemalloc and tcmalloc are supporting C++14 sized deallocation feature. Thus switching between those 3 implementation was helpful to catch issues. Note, that GCC 7 branch later version of it: https://github.com/cms-sw/cmsdist/commits/IB/CMSSW_9_4_X/gcc700/gperftools.spec

**Comment by smuzaffar** [comment]
for gcc700 , this library is not empty. The tool itself got rename (as david mentioned) i.e. https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_9_4_X/gcc700/gperftools.spec so instead of dropping cmsRunTC (which is useful for debugging) I would suggest that we get gperftools in gcc630

**Comment by Dr15Jones** [comment]
@gartung please close this pull request since the plan is to switch to gperftools.

**Pull request closed without merging**
