### PR TITLE
Utilities/StaticAnalyzers: group callstacks in EventSetupRecord::get report by package directory and producer

### PR DESCRIPTION
**Pull request by gartung**
Callstacks in EventSetupRecord::get report are now grouped by package directory and producer and output as a yaml file

```
PhysicsTools/NanoAOD:
  L1TriggerResultsConverter:
  - 'L1TriggerResultsConverter::beginRun(); '
PhysicsTools/PatAlgos:
  pat::JetCorrFactorsProducer:
  - 'pat::JetCorrFactorsProducer::produce(); '
  pat::PATElectronProducer:
  - 'pat::PATElectronProducer::produce(); '
  pat::PATElectronSlimmer:
  - 'pat::PATElectronSlimmer::produce(); pat::ObjectModifier<pat::Electron>::setEventContent();
    ModifyObjectValueBase::setEventContent() virtual; EGRegressionModifierV3::setEventContent(); '
```

### CODE REVIEW

**Comment by gartung** [comment]
@makortel Can you please sign off on this PR.

**Comment by gartung** [comment]
please test

**Comment by smuzaffar** [comment]
@gartung looks good. By the way, this is not run in PR tests and can only be tested in IBs ... right?

**Comment by gartung** [comment]
Correct. Only for IB's.

**Comment by makortel** [comment]
@smuzaffar This can be merged, right?

**Comment by smuzaffar** [comment]
@gartung , does this depend on your latest changes for llvm?

**Comment by smuzaffar** [comment]
+core
@makortel this looks good to go.

**Comment by qliphy** [comment]
+1

**Pull request merged**
