### PR TITLE
Add link to cub::CachingDeviceAllocator documentation

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Add link to the documentation of `cub::CachingDeviceAllocator` in `HeterogeneousCore/CUDACore/README.md`

#### PR validation:

None, as there are only documentation changes.

### CODE REVIEW

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by fwyzard** [comment]
@makortel OK for you ?

**Comment by makortel** [comment]
+1

Thanks.

**Comment by silviodonato** [comment]
+1

**Pull request merged**
