### PR TITLE
Add uTCA FEDs to check for calibration type

### PR DESCRIPTION
**Pull request by ssekmen**
Enabled checking uTCA FEDs for calibration information in addition to the VME FEDs.
Calibration information to be taken from uTCA FEDs by default.  When this does not exist, VME calibration information is taken.
Possible differences between uTCA and VME calibration information is also checked, and a warning is issued in case of differences.

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
Please submit also in 81X

**Comment by ssekmen** [comment]
HCAL experts asked for a modification.  I'll have to do that first.

**Comment by Martin-Grunewald** [comment]
What is the status of this PR and its 81X incarnation?
If obsolete, please close it!

**Comment by fwyzard** [comment]
@agapitos , could you follow this up with the HCAL experts ? are there other changes needed ?

**Comment by ssekmen** [comment]
Sorry for the late response, I was on vacation.
Some modification was required from the HCAL side, and I have implemented it.    
I will do the final tests and commit very soon.

**Comment by ssekmen** [comment]
HCAL wishes to do some more technical modifications, so we will be working on these.

**Comment by ssekmen** [comment]
Had a thorough discussion with HCAL experts.  We decided to continue this work in a new PR after the modifications, so I'm closing this one for the time being.

**Pull request closed without merging**
