### PR TITLE
[BuildFile] Fixed Buildfile and move templated coded in interface directory

### PR DESCRIPTION
**Pull request by smuzaffar**
https://github.com/cms-sw/cmssw/pull/31981/files added a new plugin without the closing `</library>` tag. This causes SCRAMV3 IBs to fail as scramv3 is more strict on checking Buildfiles. This should fix this issue.

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by mrodozov** [comment]
please test for CMSSW_11_2_CLANG_X_2020-11-22-2300
it should also fix the clang IB (same reason)

**Comment by mrodozov** [comment]
please test for CMSSW_11_2_CLANG_X

**Comment by smuzaffar** [comment]
please test for CMSSW_11_2_CLANG_X

**Comment by smuzaffar** [comment]
please test

**Comment by civanch** [comment]
@smuzaffar , may be better to include icc file in the header file?

**Comment by smuzaffar** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by smuzaffar** [comment]
@silviodonato , @qliphy  can we get this in. It should fix clang and SCRAM3 IBs

**Comment by qliphy** [comment]
+1   
@cms-sw/upgrade-l2  let us know if you have any concern.

**Comment by qliphy** [comment]
merge

**Comment by kpedro88** [comment]
+upgrade

**Pull request merged**
