### PR TITLE
[14_2_X] Use `Run4` for Phase2 PU inputs

### PR DESCRIPTION
**Pull request by AdrianoDee**
#### PR description:

Backport of #46841.

#### PR validation:

None.

### CODE REVIEW

**Comment by AdrianoDee** [comment]
type bug-fix

**Comment by AdrianoDee** [comment]
please test

**Comment by Moanwar** [comment]
+Upgrade

**Comment by AdrianoDee** [comment]
+pdmv

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
