### PR TITLE
Improve vertexing monitoring for Tracker Alignment AlCaReco samples

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

The goal of this PR is to a generic vertex analyzer to be used for the Tracker Alignment alcareco monitoring. 
I profit of this PR to add some more histograms concerning the Beam Spot monitoring to an existing analyzer and to improve the unit test suite.

#### PR validation:

Run successfully the augmented unit tests. 

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

N/A

### CODE REVIEW

**Comment by mmusich** [comment]
@cms-sw/alca-l2 any comment on this PR?

**Comment by tvami** [comment]
+alca

**Comment by tvami** [comment]
would it make sense to backport this?

**Comment by tvami** [comment]
urgent
 * given that this PRs backport is relevant for data taking monitoring, I think it makes sense to have this `urgent`

**Comment by perrotta** [comment]
+1

**Comment by mmusich** [comment]
> given that this PRs backport is relevant for data taking monitoring, I think it makes sense to have this urgent

the backport of this is at https://github.com/cms-sw/cmssw/pull/41408. I lumped there https://github.com/cms-sw/cmssw/pull/41393 since it's affecting the same package to avoid opening too many PRs :)

**Pull request merged**
