### PR TITLE
[DQM] Prompt matrix redefinition 

### PR DESCRIPTION
**Pull request by jfernan2**
#### PR description:

Based on agreements from PPD meetings:
- Created commonReduced which excludes TRK
- Removed CT-PPS, L1TMon and Tau from common

https://docs.google.com/presentation/d/1AF65xzq7T70Yt-0o_OV47YTFBv-kbvHZDlRmUSCZsAw/edit#slide=id.geedc047305_0_0

This PR goes in sync with: https://github.com/dmwm/T0/pull/4617

### CODE REVIEW

**Comment by qliphy** [comment]
@jfernan2  Should we wait for the test results of https://github.com/dmwm/T0/pull/4619 ?

**Comment by jfernan2** [comment]
@qliphy yes, good idea! Thanks

**Comment by qliphy** [comment]
@jfernan2   Ok, but we are not going to build the next pre release soon.  So I assume you want to have a IB release with this PR included for the Replay test, right?

**Comment by germanfgv** [comment]
@jfernan2 @qliphy I'm actually not sure what you mean by IB release. As long as it is available in /cvmfs it should be ok

**Comment by qliphy** [comment]
@jfernan2   This PR creates issue for workflow 1003.0 in most recent IB:
https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc900/CMSSW_12_1_X_2021-10-13-1100/pyRelValMatrixLogs/run/1003.0_RunMinBias2012A+RunMinBias2012A+RECODDQM+HARVESTDDQM/step2_RunMinBias2012A+RunMinBias2012A+RECODDQM+HARVESTDDQM.log#/73-73

----- Begin Fatal Exception 13-Oct-2021 14:22:14 CEST-----------------------
An exception of category 'HCALDQM' occurred while
   [0] Processing  Event run: 191226 lumi: 398 event: 556864314 stream: 0
   [1] Running path 'dqmoffline_1_step'
   [2] Calling method for module TPTask/'tpTask'
Exception Message:
TPTask::Collection HcalTrigPrimDigiCollection isn't available: valHcalTriggerPrimitiveDigis 

Would you please have a look?

**Comment by jfernan2** [comment]
Thanks @qliphy  but I am puzzled since the last commit of this PR should have fixed that...
Any recipe to reproduce this error?

**Comment by qliphy** [comment]
@jfernan2 
You can do as following:

cmsrel CMSSW_12_1_X_2021-10-12-2300
cd CMSSW_12_1_X_2021-10-12-2300/src
git cms-merge-topic 35605
scram b -j9
runTheMatrix.py -l 1003.0 --job-reports -t 4 --ibeos

**Comment by jfernan2** [comment]
I have created https://github.com/cms-sw/cmssw/pull/35658
I am sorry for the inconvenience, it was anasty Run1 sequence definition

**Pull request merged**
