### PR TITLE
Update to HLT menu version 2.1 (102X)

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
Update to HLT menu version 2.1 (102X)
Based on CMSSW_10_2_X_2018-05-22-2300
Adding also frozen menu dump for @relval2018

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by Martin-Grunewald** [comment]
@Dr15Jones can you please sign for addOntests.py ?
Thanks!

**Comment by Dr15Jones** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
