### PR TITLE
fix case of enums to match db

### PR DESCRIPTION
**Pull request by davidlange6**
#### PR description:

Fixes unit test failures introduced in #28157 

#### PR validation:

Affected unit tests now work

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test
@fabiocos , this seems to fix the unit tests, so I would suggest to merge it for 11h00 (even if PR tests do not finish) or we can delay the 11h Ib for an hour.

**Comment by fabiocos** [comment]
@davidlange6 @smuzaffar so I keep my revert commit https://github.com/fabiocos/cmssw/tree/fc-revert28157 on hold, assuming this further fix can take care of all the issues.

**Comment by davidlange6** [comment]
would have been better to have merged this for 1100... it can't really do harm.

**Comment by fabiocos** [comment]
@davidlange6 I agreed with @smuzaffar to hold the IB for a little, he is running a set of tests, then we will merge and have an IB just for this

**Comment by smuzaffar** [comment]
I have tested locally and not all the unit tests passed [a] but it is much better now. I would suggest to merge it before 12h and start IB

[a]
---> test EcalTPGPhysicsConst_O2O_test had ERRORS
---> test EcalTPGFineGrainEBIdMap_O2O_test succeeded
---> test EcalDAQ_O2O_test had ERRORS
---> test EcalTPGWeightIdMap_O2O_test succeeded
---> test EcalTPGLutIdMap_O2O_test succeeded
---> test EcalTPGPedestals_O2O_test succeeded
---> test EcalDCS_O2O_test succeeded
---> test EcalADCToGeV_update_test succeeded
---> test EcalIntercalibConstants_O2O_test had ERRORS
---> test EcalLaser_O2O_test had ERRORS
---> test EcalTPGFineGrainEBGroup_O2O_test succeeded
---> test EcalTPGFineGrainTowerEE_O2O_test succeeded
---> test EcalTPGFineGrainStripEE_O2O_test succeeded
---> test EcalTPGSpike_O2O_test succeeded
---> test EcalTPGLutGroup_O2O_test succeeded
---> test testPngHistograms succeeded
---> test EcalTPGTowerStatus_O2O_test succeeded
---> test testHistograms succeeded
---> test testBasicPayload succeeded
---> test test_CreateFileLists had ERRORS
---> test EcalTPGCrystalStatus_O2O_test succeeded
---> test EcalTPGSlidingWindow_O2O_test succeeded
---> test EcalTPGWeightGroup_O2O_test succeeded
---> test EcalTPGLinearizationConst_O2O_test succeeded
---> test test_PrepareInputDb succeeded
---> test EcalTPGBadStripStatus_O2O_test succeeded
---> test SiStripDCS_O2O_test had ERRORS
---> test RunInfoStart_O2O_test succeeded
---> test test_MpsWorkFlow succeeded
---> test SiStripDAQ_O2O_test succeeded


      6 ERRORS
     24 succeeded

**Comment by fabiocos** [comment]
@smuzaffar I agree, it does not look as the final solution, but it definitely improves the situation

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Comment by smuzaffar** [comment]
@fabiocos you want to merge any thing else or should I start the IB now.

**Pull request merged**
