### PR TITLE
[mkFit] small fix in propToPlane

### PR DESCRIPTION
**Pull request by leonardogiannini**
#### PR description:

The PR is mostly due to abnormal results in the track parameters seen when running mkFit standalone and testing the propagation to plane instead the current propagation to R/Z. 

The check "(std::abs(sl[n]) > std::abs(s[n]))" is removed as it misused the straight line approximation in cases where the path to the module would be shorter. The replacement is kept only to prevent numerical instability.

The rest of the code changes are minor changes.

#### PR validation:

As expected no change is observed in phase1 (as propToR is not used)
http://uaf-10.t2.ucsd.edu/~legianni/plots_validateP2P_sl/plots_phase1/

In phase2 the propToR is used only in the hit search, but not the fit of the parameters (which also refitted using CKF), so the final effect is very small.
http://uaf-10.t2.ucsd.edu/~legianni/plots_validateP2P_sl/plots_tt/

A small increase in n. of hits in the muon sample at high pT (e.g. http://uaf-10.t2.ucsd.edu/~legianni/plots_validateP2P_sl/plots_3_mu_pt1to1000_eta0p0to0p4)

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by jfernan2** [comment]
type bug-fix

**Comment by jfernan2** [comment]
+1

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
