### PR TITLE
run2-trk03 Add the missing cff file for 2018 Zero Material

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Add the missing cff file for 2018 Zero Material

#### PR validation:

use  runTheMatrix test workflows and replace default with zero material

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by kpedro88** [comment]
please test

**Comment by cvuosalo** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade

**Comment by qliphy** [comment]
+1

**Pull request merged**
