### PR TITLE
Add 2023 DD4hep XML wf

### PR DESCRIPTION
**Pull request by srimanob**
#### PR description:
This PR adds 2023 DD4hep XML wf. It needs https://github.com/cms-sw/cmssw/pull/40865.

#### PR validation:
Configuration dump is fine with 
`runTheMatrix.py --what upgrade -l 12434.911 --wm init`

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:
It should be backport to 13_0.

### CODE REVIEW

**Comment by srimanob** [comment]
test parameters:
- workflow = 12434.911
- relvals_opt = --what cleanedupgrade,standard,highstats,pileup,generator,extendedgen,production,ged,machine,premix,nano,gpu
- pull_request = https://github.com/cms-sw/cmssw/pull/40865

**Comment by srimanob** [comment]
@cmsbuild please test

**Comment by srimanob** [comment]
+Upgrade

The workflow 12434.911 (2023 DD4hep XML) runs fine.

**Comment by perrotta** [comment]
+1

**Comment by srimanob** [comment]
Kindly ping @cms-sw/pdmv-l2 
Thanks.

**Comment by perrotta** [comment]
+1

**Pull request merged**
