### PR TITLE
Use Tracker Parameters from DB

### PR DESCRIPTION
**Pull request by ianna**
- Fully migrate to using Tracker parameters from DB:
  - Replace Tracker parameters taken from configuration file fragment with identical parameters retrieved from DB tag
  - Introduce Tracker topology dependency on Tracker parameters
  - Implement Tracker parameters from DD reader
  - Update schema to fully eliminate all Tracker constants amen from configuration

NOTE: a new DB tag is needed to test this PR. Further modifications of HLT configurations are needed to remove explicit definition of Tracker parameters.

To test for run1:

Step 1: Produce the tag:

```
cmsRun CondTools/Geometry/test/trackergeometrywriter.py
```

Step 2: Customise the GT:

```
process.GlobalTag.toGet = cms.VPSet(cms.PSet(record = cms.string('PTrackerParametersRcd'),
                                             tag = cms.string('TK_Parameters_Test02'),
                                             connect = cms.untracked.string("sqlite_file:./myfile.db")
                                             )
                                    )
```

To produce the tag for other scenarios, please, modify CondTools/Geometry/test/trackergeometrywriter.py

***\* This work and PR will be discussed during AlcaDB meeting next Monday. ****

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
-1
Mereg conflicts.
Rebase to most recent IB to get rid of (some of) the HLT changes.

**Comment by ianna** [comment]
@cmsbuild - did you try to merge before or after my fixes? Thanks.

**Comment by perrotta** [comment]
@ianna : if you merge this PR on top of the latest IB (by now CMSSW_7_4_X_2015-02-07-0200) you still have conflicts in 
Alignment/LaserAlignment/plugins/LaserAlignment.cc
Geometry/TrackerGeometryBuilder/python/idealForDigiTrackerGeometryDB_cff.py
Please fix them.

**Comment by ianna** [comment]
@perrotta - thanks!

**Comment by slava77** [comment]
... I'm checking it for reco part

**Comment by slava77** [comment]
Yana, 

the instructions are not very clear on how to get the run2 mc or other files.

I tried step2 (DIGI and HLT) in run1 mc, and it's at least running

**Comment by slava77** [comment]
step3 (reco+dqm/validation) is broken in GlobalDigisAnalyzer
after switching to the topology here, step3 also runs.

**Comment by ianna** [comment]
@slava77 - thanks!

Please, replace the following line for run2:
```
process.load("Configuration.Geometry.GeometryExtended_cff")
```
with
```
process.load("Configuration.Geometry.GeometryExtended2015_cff")
```

**Comment by slava77** [comment]
Hi Yana,

just this change in the trackergeometrywriter.py wasn't enough.
The run2 mc jobs still fail with the same errors as when I tried with the run1 file:

```
An exception of category 'Configuration' occurred while
   [0] Constructing the EventProcessor
   [1] Validating configuration of ESProducer or ESSource of type TrackerTopologyEP with label: 'trackerTopologyConstants'
Exception Message:
Illegal parameters found in configuration.  The parameters are named:
 'pxb_ladderMask'
 'pxb_ladderStartBit'
 'pxb_layerMask'
 'pxb_layerStartBit'

```

**Comment by ianna** [comment]
@slava77 - Sorry, it must be some configuration file fragment or customisation I missed which needs a clean up. I'd guess HLT - they collect and expand all fragments in one file.

**Comment by slava77** [comment]
Yana,

on the run1 side, I came across missing code changes in the following 
- DQMOffline/CalibTracker/plugins/SiStripQualityHotStripIdentifierRoot.cc

There is also one I mentioned earlier
- Validation/GlobalDigis/src/GlobalDigisAnalyzer.cc

**Comment by slava77** [comment]
I checked outputs of the run1 mc and data test jobs and there are no difference as expected
tests were done in CMSSW_7_4_X_2015-02-04-1400 + 7352+7516 as a reference, and reference+40a02c8 (cherry picked) for the "new version".
The "new version" matrix was run with a customize function as suggested in the PR description.

run2 mc failed.

**Comment by ianna** [comment]
@slava77 - thanks! I've updated remaining HLT configurations and run2 should be fine. I'm running the tests now.

**Comment by ianna** [comment]
@venturia and @boudoul, FYI.

**Comment by ianna** [comment]
FYI, AlcaDB meeting agenda and slides for discussion on Tuesday: https://indico.cern.ch/event/368326/

@venturia - Could you, please, comment on Tracker parameters schema? Is there everything defined you need? Thanks.

**Comment by perrotta** [comment]
-1

Please, do not modify HLT configurations in HLTrigger/Configuration yourself: TSG will take care of it if and when needed.
In your case, I don't even think it is (strictly) necessary: you remove several parameters from the configurations like
trackerTopologyConstants = cms.ESProducer( "TrackerTopologyEP",
...
)
but those parameter are not searched for by your modified TrackerTopologyEP plugin, thus they are useless but shouldn't harm if left in the config (am I correct?).

Anyhow, you still get a lot of errors even from the short matrix
runTheMatrix.py -s 
you have to fix at least them before we can be able to evaluate your PR on the HLT (or anywhere else).

**Comment by Martin-Grunewald** [comment]
@perrotta
the plugin uses fillDescriptions, so the extra parameters lead to an
error message as they are removed in fillDescriptions, rather than
declared optional...

**Comment by Martin-Grunewald** [comment]
@perrotta 
I guess for HLT we need to add a CMSSW-release dependent customisation,
replacing the "long" module with the couple-of-lines "config" inside confdb.py.
I can do so later this afternoon unless you have time now...

**Comment by perrotta** [comment]
Ah, yes, Martin, I did not notice the fillDescription(). Thus we will have to parse the new config anyhow at some time (but I agree that Ianna can remove the extra parameter by hand in the meanwhile, only in order to test this PR).
In any case, even the matrix tests fail by now (and the automatic ones as well): the proponents must fix them before anybody can perform any test on this PR.

**Comment by Martin-Grunewald** [comment]
@perrotta 
If we have the same menu for 73 and 74, we always need a release dependent customisation,
either for 73 if we move the menu to 74, or for 74...

**Comment by ianna** [comment]
@perrotta and @Martin-Grunewald - standard tests suppose to fail without extra record in a GT. Please, see PR description on how to produce the record and customise your job locally. If it is any help, I can put sqlite files or tags in Prep DB with run1 and run2 records somewhere publicly.

**Comment by ianna** [comment]
@perrotta - if HLT configurations reference non-existing parameters the following exception occurs:
```
An exception of category 'Configuration' occurred while
   [0] Constructing the EventProcessor
   [1] Validating configuration of ESProducer or ESSource of type TrackerTopologyEP with label: 'trackerTopologyConstants'
Exception Message:
Illegal parameters found in configuration.  The parameters are named:
 'pxb_ladderMask'
 'pxb_ladderStartBit'
 'pxb_layerMask'
 'pxb_layerStartBit'
```

**Comment by ianna** [comment]
@perrotta - I've added some test configurations and customisations to make it easier:

for run2:
```
cmsRun CondTools/Geometry/test/trackergeometrywriterRun2.py
runTheMatrix.py -l 2.0 --command "--conditions auto:run2_mc --customise Geometry/TrackerGeometryBuilder/customTrackerParametersRun2.customise"
```

for run1:
```
cmsRun CondTools/Geometry/test/trackergeometrywriter.py
runTheMatrix.py -l 2.0 --command "--customise Geometry/TrackerGeometryBuilder/customTrackerParametersRun1.customise"
```

**Comment by venturia** [comment]
@ianna, I want be able to look at this pull request before the second half of this week.

On Feb 9, 2015, at 14:00 , cmsbuild <notifications@github.com<mailto:notifications@github.com>>
 wrote:


Pull request #7589<https://github.com/cms-sw/cmssw/pull/7589> was updated. @perrotta<https://github.com/perrotta>, @cmsbuild<https://github.com/cmsbuild>, @civanch<https://github.com/civanch>, @diguida<https://github.com/diguida>, @danduggan<https://github.com/danduggan>, @lveldere<https://github.com/lveldere>, @cvuosalo<https://github.com/cvuosalo>, @fwyzard<https://github.com/fwyzard>, @ianna<https://github.com/ianna>, @mdhildreth<https://github.com/mdhildreth>, @monttj<https://github.com/monttj>, @Martin-Grunewald<https://github.com/Martin-Grunewald>, @Dr15Jones<https://github.com/Dr15Jones>, @cerminar<https://github.com/cerminar>, @deguio<https://github.com/deguio>, @slava77<https://github.com/slava77>, @ggovi<https://github.com/ggovi>, @vadler<https://github.com/vadler>, @mmusich<https://github.com/mmusich>, @ktf<https://github.com/ktf>, @nclopezo<https://github.com/nclopezo> can you please check and sign again.

**Comment by ianna** [comment]
@cmsbuild - PR #7646 should fix the first unit test error. The second will go away as soon as GT is updated.

**Comment by slava77** [comment]
@diguida 
Salvatore, when should we expect a GT for this one? (or is it available already)

**Comment by venturia** [comment]
@ianna I have just made a pull request to _your_ branch , tracker-parameters-fromDB, where I have removed the usage of the parameter "upgradeGeometry". If you accept it, this pull request should be updated automatically. You will have to remove upgradeGeometry from the xml, the DB, whereever else you put it. @atricomi, could you have a look and confirm if it is ok? I have forced upgradeGeometry to be true if the subdetector is an upgraded one and false if it is not. I think we do not use a present pixel subdetector enumerator for the upgraded detector, not even for the barrel.

**Comment by atricomi** [comment]
@aventuri Indeed this “upgradeGeometry” for phase1 should be not removed since a lot of time. It was used for te BigPixel but just for historical reasons since the BigPixel should be exactly the same as in the current geometry. Could you give me the full recipe to check everything. I would like to run a full chain test.Thanks

Il giorno 15/feb/2015, alle ore 16:19, venturia <notifications@github.com> ha scritto:

**Comment by venturia** [comment]
Alessia, there is no workflow running in 74x yet! I am planning to get rid of upgradeGeometry also in my private branch of SLHC but it is not done yet.

On Feb 16, 2015, at 9:21 , Alessia Tricomi <notifications@github.com<mailto:notifications@github.com>>
 wrote:

@aventuri Indeed this “upgradeGeometry” for phase1 should be not removed since a lot of time. It was used for te BigPixel but just for historical reasons since the BigPixel should be exactly the same as in the current geometry. Could you give me the full recipe to check everything. I would like to run a full chain test.Thanks

Il giorno 15/feb/2015, alle ore 16:19, venturia <notifications@github.com<mailto:notifications@github.com>> ha scritto:

**Comment by atricomi** [comment]
@aventuri sorry I mean should be removed ...
Il giorno 16/feb/2015, alle ore 09:25, venturia <notifications@github.com> ha scritto:

**Comment by venturia** [comment]
By the way: I have not removed the use of "upgradeGeometry", I have simply hardcoded its value based on the subdetector type: for phase 1 and phase 2 subdetectors it is true for the present pixel detector it is false. If  it is also useless then we can remove it also from the code that uses it. Maybe in a future PR.

                         Andrea

On Feb 16, 2015, at 9:26 , Alessia Tricomi <notifications@github.com<mailto:notifications@github.com>> wrote:

@aventuri sorry I mean should be removed ...
Il giorno 16/feb/2015, alle ore 09:25, venturia <notifications@github.com<mailto:notifications@github.com>> ha scritto:

**Comment by davidlange6** [comment]
closing in 74x - there is the same PR open in 75x (now the development release)

**Pull request closed without merging**
