### PR TITLE
Add HLT75e33 step to Phase-2 workflows

### PR DESCRIPTION
**Pull request by srimanob**
#### PR description:
This PR is to add Phase2 HLT75e33 to Phase-2 workflow. It needs https://github.com/cms-sw/cmssw/pull/37162.

#### PR validation:
Output from the following runTheMatrix works,
`runTheMatrix.py --what upgrade -l 39434.75 -t 8 --wm init`

#### if this PR is a backport please specify the original PR and why you need to backport that PR:
After agree on the way to implement, we will need to backport to 12_3_X

### CODE REVIEW

**Comment by srimanob** [comment]
code-checks

**Comment by srimanob** [comment]
@smuzaffar Do I miss any change to make the code-check for PR test happen? Thanks.

**Comment by smuzaffar** [comment]
no you did not miss any change. github itself is going through a bad time 9 https://www.githubstatus.com/ ) that is why bot is not reacting to and command

**Comment by srimanob** [comment]
test parameters:
- pull_request = https://github.com/cms-sw/cmssw/pull/37162

**Comment by srimanob** [comment]
@cmsbuild please test

**Comment by srimanob** [comment]
This is a side note to @cms-sw/pdmv-l2 that they will face a space increasing for D88 if run with cmsDriver after this PR is merge. Duplication of FEVTDEBUGHLT after RECO will happen. One can remove the original production of FEVT from RECO step.

I think I should change the datatier, either of RECO or HLT step, so that it will not collapse.

**Comment by kskovpen** [comment]
Thanks @srimanob . Do you have an estimate of how much it will increase in size without manual intervention in the wf configuration?

**Comment by srimanob** [comment]
You will need roughly 20 TB more per standard set of D88 NoPU+PU200. I estimate from TTbar/SUSY which needs ~1TB for GEN-SIM-RECO in both PU scenario. The output from HLT step will completely overlap with RECO with additional information of HLTX step. I assume you have the drop function in RelVals machine.

Note that, I plan to make a little update on datatier. So that we will have the same GEN-SIM-RECO for output from HLTX step, and output from RECO which will be dropped can be something else, i.e. FEVT. So, this will be transparent from user point of view.

**Comment by srimanob** [comment]
@cmsbuild please test

**Comment by kskovpen** [comment]
+pdmv

**Comment by srimanob** [comment]
hold

Let's hold it until we finalize https://github.com/cms-sw/cmssw/pull/37162

**Comment by srimanob** [comment]
unhold

**Comment by srimanob** [comment]
@cmsbuild please test

**Comment by missirol** [comment]
@srimanob 

One small point: #37162 now provides [`HLT:@relval2026`](https://github.com/cms-sw/cmssw/pull/37162/files#diff-49beb1fbdd7ffb0026a95687af6c6f42d77d976186283a9b1851a8203f871061R14) (currently equivalent to `HLT:75e33`), similarly to other HLT menus used in RelVal wfs. Just in case you'd prefer to use that.

**Comment by srimanob** [comment]
@cmsbuild please test

**Comment by srimanob** [comment]
+Upgrade

This PR is to add workflow for HLT Phase-2. The needed PR is fully sign, https://github.com/cms-sw/cmssw/pull/37162

**Comment by srimanob** [comment]
@cms-sw/pdmv-l2 Could you please check and sign again?

**Comment by kskovpen** [comment]
+pdmv

**Comment by qliphy** [comment]
+1

**Pull request merged**
