### PR TITLE
Phase2-gem43 Remove an overlap in the MF shield

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

ShieldingME4 in muonYoke.xml (as in 2021/v3) is overlapping with ShieldongBoronPoly_1_ME in mfshield.xml (as of 2026/v4) over a large region. They are made of same material and one of them is commented out in 2026/v1 version of muonYoke.xml

#### PR validation:

Tested using overlap tool in a phase2 scenario

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@slomeo Please check this

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by slomeo** [comment]
@bsunanda  :  I rebased your PR in CMSSW_11_2_X_2020-07-12-2300 and I put in Geometry/​CMSCommonData/​python/​cmsExtendedGeometry2026D59XML_cfi.py the line 'Geometry/MuonCommonData/data/muonYoke/2026/v1/muonYoke.xml' instead of Geometry/MuonCommonData/data/muonYoke/2021/v3/muonYoke.xml'. Then I checked the overlaps with cmsShow and I found what you can se in the attached picture:
Screenshot 2020-07-13 16 49 52

**Comment by bsunanda** [comment]
@cvuosalo Can you approve this PR. I urgently need this PR to resolve overlaps in many phase2 scenarios

**Comment by cvuosalo** [comment]
+1

**Comment by cvuosalo** [comment]
@bsunanda Is Sergio's comment saying that there are still overlaps in this PR?

**Comment by silviodonato** [comment]
+1

**Comment by bsunanda** [comment]
@cvuosalo @slomeo That overlap is in forward shield. I shall investigate that

**Pull request merged**
