### PR TITLE
Phase2-HGX350A Resolve the scenario for V18 version of HGCal Geometry

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Resolve the scenario for V18 version of HGCal Geometry

#### PR validation:

Use the runTheMatrix test workflows

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by srimanob** [comment]
test parameters:
- workflows = 27234.0
- relvals_opt = --what cleanedupgrade,standard,highstats,pileup,generator,extendedgen,production,identity,ged,machine,premix,nano,gpu,2017,2026

**Comment by srimanob** [comment]
@cmsbuild please test

**Comment by srimanob** [comment]
+Upgrade

Change is seen only in 27234.0 (geometry 2026D104) as expected.

**Comment by bsunanda** [comment]
@sunilUIET Could you approve this?

**Comment by sunilUIET** [comment]
+pdmv

**Comment by bsunanda** [comment]
@rappoccio @antoniovilela Please merge this PR

**Comment by bsunanda** [comment]
@rappoccio @antoniovilela Please merge this PR. we are waiting for the next PR

**Comment by bsunanda** [comment]
@rappoccio @antoniovilela Please merge this PR. We are waiting for this new IB to declare a new workflow

**Comment by bsunanda** [comment]
@rappoccio @antoniovilela Please merge this PR. We are waiting for this new IB to declare a new workflow

**Comment by bsunanda** [comment]
type bug fix

**Comment by bsunanda** [comment]
Please merge - otherwise V18 is meaningless

**Comment by bsunanda** [comment]
Bug fix

**Comment by bsunanda** [comment]
Type Bug-Fix

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
