### PR TITLE
Cleaned up CastorMonitorModule

### PR DESCRIPTION
**Pull request by Dr15Jones**
-Removed unnecessary global variables
-Switch to using unique_ptr to manage memory
-Removed use of begin/endLuminosityBlock which was only for a print statement
-Get the conditions in analyze not in dqmBeginRun
-Removed unused member variables

### CODE REVIEW

**Comment by andrius-k** [comment]
please test

**Comment by Dr15Jones** [comment]
@andrius-k wrote
> Hi @Dr15Jones, are you planning to test this PR in playback?

I have no knowledge of how to do that. I will gladly run any tests in CMSSW or in the IB system which can be used to test this code. Baring that, I'm afraid it falls to the DQM L2s to test correctness. 

On that subject, @fabiocos , @smuzaffar and myself would be happy to assist the DQM L2s in creating a way to test in the IBs the DQM system. This should greatly decrease your workload as changes to the DQM system and its modules are necessary in order to deal with the threading efficiency lost caused by the DQM modules moving from ::stream modules to ::one modules.

> I presume that there will not be a back-port to this PR.
These changes are intended to be 'forward looking' towards Run 3 and are definitely not meant to be back-ported.

**Comment by andrius-k** [comment]
+1

Hi @Dr15Jones, thanks clarifications. We (DQM) would also be interested in integrating online tests into IB system and this is something we might look into during the LS. I would like to point out that there are no concrete plans about this yet as we would first need to figure out the correct way to do this, but this is something we are considering.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
