### PR TITLE
[HGCAL] Simplify makeHGCalValidationPlots

### PR DESCRIPTION
**Pull request by lecriste**
#### PR description:

This PR simplifies the code in `makeHGCalValidationPlots.py` and makes `hgcalPlots.py` more robust.
No changes are expected in the output.

#### PR validation:

`runTheMatrix -l limited`

### CODE REVIEW

**Comment by felicepantaleo** [comment]
@cmsbuild please test

**Review by felicepantaleo — COMMENTED** [review]
if this bug was introduced in 11_3_X and is still present, could you also provide a backport in 11_3?

**Comment by jfernan2** [comment]
@lecriste I don't undertand why the changes in eta and phi for Nun and NumDup (at least) for CaloParticle distributions are being introduced again. From your PR description I read no changes are expected. E.g.:
Base: https://tinyurl.com/yelgu3z6
PR: https://tinyurl.com/yzyakkzl

All changes: https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_0_X_2021-05-04-2300+76a38b/42636/dqm-histo-comparison-summary.html
Thanks

**Comment by lecriste** [comment]
@jfernan2 I don't understand either: the two files modified by this PR are not producing those changes. For some reason the base comparison is run without #33488, and from the checks summary above I see 33545 (previous closed PR with same name from same branch) instead of this PR number in some listed items.
Shall I open another PR from a different branch?

**Comment by jfernan2** [comment]
please test
Let's run the test again to introduce last build into the comparison

**Comment by jfernan2** [comment]
+1

**Comment by lecriste** [comment]
@silviodonato and @qliphy, please wait before merging this. I want to push one more commit.

**Comment by silviodonato** [comment]
-1 

> @silviodonato and @qliphy, please wait before merging this. I want to push one more commit.

ok

**Comment by ebrondol** [comment]
I would like to mention here that I still see duplicates of pdf plots when I run with the `trackstersWithEdges` option: https://ebrondol.web.cern.ch/ebrondol/HGCal/PR33639/plots1_trackstersEdges/plots1_Tracksters.html
This was discussed with @lecriste and decided to fix it in another PR which will come at a later point.

**Comment by lecriste** [comment]
@jfernan2 can you please trigger the tests again?

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
