### PR TITLE
AssoByHits with GEM hits porting 8XY

### PR DESCRIPTION
**Pull request by calabria**
This PR contains the new module needed to associate the GEM tracking recHits (GEMHitAssociator) and the all the changes needed in the AssociatorByHits to make it associate also GEM tracking recHits. The association of GEM hits is disabled by default to avoid problems when the GEM detectors are not present in the geometry scenario. Moreover a new plot representing the averange number of GEM tracking recHits vs eta hs been added in the MuonTrackValidator. It is not filled by default, it has to be switched on when GEM detectors are present in the simulation. I checked the code with the following runTheMatrix command and all tests ended successfully: runTheMatrix.py -l limited -i all (with the use of GEM disabled, but I tested it also with GEM hits present and GEM association enabled without problems).

Same content as https://github.com/cms-sw/cmssw/pull/11962 in 76X.

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by calabria** [comment]
@deguio @degano @davidlange6 can this PR be approved and merged? thanks

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
