### PR TITLE
Important-> EDM IDs update, Fixed typo in effective areas.

### PR DESCRIPTION
**Pull request by lgray**
Further additions to #10619.

This includes an updated 25ns Spring15 photon MVA ID and appropriate updates to MiniAOD steering.
Additionally, we include a first round of 25ns Spring15 cutbased IDs.

A notable thing here is fixing of a typo for effect areas.

Weight files are already in the cms-data area, and do not exist in the history of this PR.

### CODE REVIEW

**Comment by lgray** [comment]
@ikrav @cmkuo

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
.. looking at this one, then going backward to 75 and then 76

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/10873	361837b
- code changes are OK [ cutBasedElectronID_Spring15_25ns_V1 added, and mvaPhotonID_Spring15_25ns_nonTrig_ V0 swapped for V2]
- jenkins tests passed as far as they could 
- tested locally in CMSSW_7_6_X_2015-08-21-1100 /test area sign579b/ with a short matrix and 200 events in DoubleMuon and DoubleEG in 251721
- there are no differences in monitored quantities in DQM or fwlite reco comparisons
- technical performance are essentially unchanged:
    -  egmGsfElectronIDs is slower by ~30%, but that's just 3ms/evt
    - memory allocations don't show significant differences
    - data products on disk change only in MINIAOD: 0.6% increase in slimmedElectrons size

**Comment by lgray** [comment]
@monttj signature please? Thanks!

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@monttj please check, this needs your signature to make it to pre4, hopefully.
Thank you.

**Comment by monttj** [comment]
+1
I am sorry for late response. 
There is CMSDAS going on this week locally.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
