### PR TITLE
egamma HLT Off dqm hep17 2D eff plots backport for 92X

### PR DESCRIPTION
**Pull request by sushilchauhan**
backport of PR#19699. It adds HEP17 folder for egamma HLTOffline DQM and 2D efficiecy plots are added for egamma HLT Validation

### CODE REVIEW

**Comment by mtosi** [comment]
@cmsbuild, please test

**Comment by dmitrijus** [comment]
backport of https://github.com/cms-sw/cmssw/pull/19699

Ping me once the upstream is merged, I will sign this one.

**Comment by sushilchauhan** [comment]
@mtosi just updated this PR , backport of #19699 (in 94X).

**Comment by mtosi** [comment]
@cmsbuild, please test

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
Your PR is unmergeable. Please have a look and possibly rebase it.

**Comment by sushilchauhan** [comment]
@davidlange6 how i could know the prs which give these conflicts. Thanks.

**Comment by davidlange6** [comment]
you can look at the list of files that have a conflict at the bottom of your pull request on GitHub. Then look at the history of those files for recent commits (and corresponding PRs)

**Comment by sushilchauhan** [comment]
@davidlange6 I just look the history of this file and it seems i was the last perosn to make chagnes. https://github.com/cms-sw/cmssw/commits/master/DQMOffline/Trigger/python/EgHLTOfflineSource_cfi.py  then why I see confilict? OR am I looking at wrong link?? Thanks

**Comment by dmitrijus** [comment]
+1

**Comment by sushilchauhan** [comment]
I hope this could be checked and merged without furhter need of rebase.

**Comment by sushilchauhan** [comment]
May I ask if there are plans to merge it? Or if something more need to be done from myside?

**Comment by davidlange6** [comment]
No there are not - data taking is over. We'll use newer software for 2018.

**Comment by davidlange6** [comment]
CMSSW_9_2_X developement work is completed. Closing remaining PRs

**Pull request closed without merging**
