### PR TITLE
Make edmStreamStallGrapher properly handle unscheduled processing

### PR DESCRIPTION
**Pull request by Dr15Jones**
The algorithm for understanding the log files did not properly deal
with logs from jobs which were running unscheduled.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
@VinInn after reviewing the log you created, I determined that my script only worked properly for scheduled jobs. Thanks for trying it out and giving me your logs.

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
