### PR TITLE
Monitoring of tau decay products in NanoDQM

### PR DESCRIPTION
**Pull request by Ksavva1021**
#### PR description:
This PR builds on top of https://github.com/cms-sw/cmssw/pull/42987, such that the tau decay products can be monitored by NanoDQM.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

This PR is a backport of https://github.com/cms-sw/cmssw/pull/43382.

### CODE REVIEW

**Comment by vlimant** [comment]
enable nano

**Comment by vlimant** [comment]
please test

**Comment by vlimant** [comment]
+1

**Comment by rappoccio** [comment]
+1

**Comment by vlimant** [comment]
type tau

**Pull request merged**
