### PR TITLE
reorganise HLTrigger/Timer utilities

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Reorganise the `memory_usage` and `processor_model` utilities:
  - move the code from the plugin to the library
  - add unit tests
  - implement experimental support for monitoring per-thread peak memory usage with jemalloc

#### PR validation:

Unit tests compile, run, and give the expected results.

### CODE REVIEW

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by fwyzard** [comment]
please test with cmsdist#5852

**Comment by fwyzard** [comment]
As a comparison, here are the output of the unit test using
### glibc malloc
```
+allocated / -deallocated / < peak memory for the current thread:
	+0 kB / -0 kB / < 0 kB
	+0 kB / -0 kB / < 0 kB
	+0 kB / -0 kB / < 0 kB
	+0 kB / -0 kB / < 0 kB
	+0 kB / -0 kB / < 0 kB
	+0 kB / -0 kB / < 0 kB
	+0 kB / -0 kB / < 0 kB
	+0 kB / -0 kB / < 0 kB
	+0 kB / -0 kB / < 0 kB
	+0 kB / -0 kB / < 0 kB
	+0 kB / -0 kB / < 0 kB
	+0 kB / -0 kB / < 0 kB
	+0 kB / -0 kB / < 0 kB
	+0 kB / -0 kB / < 0 kB
	+0 kB / -0 kB / < 0 kB
	+0 kB / -0 kB / < 0 kB
	+0 kB / -0 kB / < 0 kB
	+0 kB / -0 kB / < 0 kB
	+0 kB / -0 kB / < 0 kB
	+0 kB / -0 kB / < 0 kB
	+0 kB / -0 kB / < 0 kB

+allocated / -deallocated / < peak memory for the current thread:
	+0 kB / -0 kB / < 0 kB
	+0 kB / -0 kB / < 0 kB
	+0 kB / -0 kB / < 0 kB
	+0 kB / -0 kB / < 0 kB
	+0 kB / -0 kB / < 0 kB
	+0 kB / -0 kB / < 0 kB
	+0 kB / -0 kB / < 0 kB
	+0 kB / -0 kB / < 0 kB
	+0 kB / -0 kB / < 0 kB
	+0 kB / -0 kB / < 0 kB
	+0 kB / -0 kB / < 0 kB
	+0 kB / -0 kB / < 0 kB
	+0 kB / -0 kB / < 0 kB
	+0 kB / -0 kB / < 0 kB
	+0 kB / -0 kB / < 0 kB
	+0 kB / -0 kB / < 0 kB
	+0 kB / -0 kB / < 0 kB
	+0 kB / -0 kB / < 0 kB
	+0 kB / -0 kB / < 0 kB
	+0 kB / -0 kB / < 0 kB
	+0 kB / -0 kB / < 0 kB
```

### jemalloc 5.2.1
```
+allocated / -deallocated / < peak memory for the current thread:
	+1067 kB / -246 kB / < 0 kB
	+1083 kB / -246 kB / < 0 kB
	+1099 kB / -246 kB / < 0 kB
	+1115 kB / -246 kB / < 0 kB
	+1131 kB / -246 kB / < 0 kB
	+1147 kB / -246 kB / < 0 kB
	+1163 kB / -246 kB / < 0 kB
	+1179 kB / -246 kB / < 0 kB
	+1195 kB / -246 kB / < 0 kB
	+1211 kB / -246 kB / < 0 kB
	+1227 kB / -246 kB / < 0 kB
	+1227 kB / -262 kB / < 0 kB
	+1227 kB / -278 kB / < 0 kB
	+1227 kB / -294 kB / < 0 kB
	+1227 kB / -310 kB / < 0 kB
	+1227 kB / -326 kB / < 0 kB
	+1227 kB / -342 kB / < 0 kB
	+1227 kB / -358 kB / < 0 kB
	+1227 kB / -374 kB / < 0 kB
	+1227 kB / -390 kB / < 0 kB
	+1227 kB / -406 kB / < 0 kB

+allocated / -deallocated / < peak memory for the current thread:
	+1227 kB / -406 kB / < 0 kB
	+1243 kB / -406 kB / < 0 kB
	+1243 kB / -422 kB / < 0 kB
	+1259 kB / -422 kB / < 0 kB
	+1259 kB / -438 kB / < 0 kB
	+1275 kB / -438 kB / < 0 kB
	+1275 kB / -454 kB / < 0 kB
	+1291 kB / -454 kB / < 0 kB
	+1291 kB / -470 kB / < 0 kB
	+1307 kB / -470 kB / < 0 kB
	+1307 kB / -486 kB / < 0 kB
	+1323 kB / -486 kB / < 0 kB
	+1323 kB / -502 kB / < 0 kB
	+1339 kB / -502 kB / < 0 kB
	+1339 kB / -518 kB / < 0 kB
	+1355 kB / -518 kB / < 0 kB
	+1355 kB / -534 kB / < 0 kB
	+1371 kB / -534 kB / < 0 kB
	+1371 kB / -550 kB / < 0 kB
	+1387 kB / -550 kB / < 0 kB
	+1387 kB / -566 kB / < 0 kB
```

### jemalloc 5.2.1 with peak memory tracking
from cms-sw/cmsdist#5852
```
+allocated / -deallocated / < peak memory for the current thread:
	+1067 kB / -246 kB / < 0 kB
	+1083 kB / -246 kB / < 16 kB
	+1099 kB / -246 kB / < 32 kB
	+1115 kB / -246 kB / < 48 kB
	+1131 kB / -246 kB / < 64 kB
	+1147 kB / -246 kB / < 80 kB
	+1163 kB / -246 kB / < 96 kB
	+1179 kB / -246 kB / < 112 kB
	+1195 kB / -246 kB / < 128 kB
	+1211 kB / -246 kB / < 144 kB
	+1227 kB / -246 kB / < 160 kB
	+1227 kB / -262 kB / < 160 kB
	+1227 kB / -278 kB / < 160 kB
	+1227 kB / -294 kB / < 160 kB
	+1227 kB / -310 kB / < 160 kB
	+1227 kB / -326 kB / < 160 kB
	+1227 kB / -342 kB / < 160 kB
	+1227 kB / -358 kB / < 160 kB
	+1227 kB / -374 kB / < 160 kB
	+1227 kB / -390 kB / < 160 kB
	+1227 kB / -406 kB / < 160 kB

+allocated / -deallocated / < peak memory for the current thread:
	+1227 kB / -406 kB / < 0 kB
	+1243 kB / -406 kB / < 16 kB
	+1243 kB / -422 kB / < 16 kB
	+1259 kB / -422 kB / < 16 kB
	+1259 kB / -438 kB / < 16 kB
	+1275 kB / -438 kB / < 16 kB
	+1275 kB / -454 kB / < 16 kB
	+1291 kB / -454 kB / < 16 kB
	+1291 kB / -470 kB / < 16 kB
	+1307 kB / -470 kB / < 16 kB
	+1307 kB / -486 kB / < 16 kB
	+1323 kB / -486 kB / < 16 kB
	+1323 kB / -502 kB / < 16 kB
	+1339 kB / -502 kB / < 16 kB
	+1339 kB / -518 kB / < 16 kB
	+1355 kB / -518 kB / < 16 kB
	+1355 kB / -534 kB / < 16 kB
	+1371 kB / -534 kB / < 16 kB
	+1371 kB / -550 kB / < 16 kB
	+1387 kB / -550 kB / < 16 kB
	+1387 kB / -566 kB / < 16 kB
```

**Comment by Martin-Grunewald** [comment]
@fwyzard 
This is good to go?

**Comment by fwyzard** [comment]
I think so, yes.
Since we shoild have the patched jemalloc in the build, let me just rerun the tests to see if it works as intended.

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
Mhm, it doesn't actually show the peak usage:
```
===== Test "memory_usage_je_t" ====
+allocated / -deallocated / < peak memory for the current thread:
	+1132 kB / -280 kB / < 0 kB
	+1148 kB / -280 kB / < 0 kB
	+1164 kB / -280 kB / < 0 kB
	+1180 kB / -280 kB / < 0 kB
	+1196 kB / -280 kB / < 0 kB
	+1212 kB / -280 kB / < 0 kB
...
```

Isn't #5852 integrated in the recent IBs ?

**Comment by smuzaffar** [comment]
yes it is in recent 11.2.X IBs

**Comment by fwyzard** [comment]
@smuzaffar I think **tag** is still forcing the use of the official `5.2.1` release, instead of the tip of the `cms/5.2.1` branch ?
```spec
### RPM external jemalloc 5.2.1

%define tag %{realversion}
%define branch cms/%{realversion}
%define github_user cms-externals
Source: git+https://github.com/%{github_user}/jemalloc.git?obj=%{branch}/%{tag}&export=%{n}-%{realversion}&output=/%{n}-%{realversion}-%{tag}.tgz
```

**Comment by smuzaffar** [comment]
ah good catch ... my bad, will update now for both 11.2 and 11.1

**Comment by smuzaffar** [comment]
11.2.X: https://github.com/cms-sw/cmsdist/pull/5896
11.1.X: https://github.com/cms-sw/cmsdist/pull/5897

**Comment by silviodonato** [comment]
please test with cms-sw/cmsdist#5896

**Comment by fwyzard** [comment]
hold

the PR for the alternative implementation in jemalloc is being reviewed upstream; once its interface settles, I will update this PR accordingly, so we don't need to make an update when we eventually switch to jemalloc 6.x - because by then we may have forgotten what this was all about :-)

**Comment by fwyzard** [comment]
@cmsbuild, please test with cms-sw/cmsdist#5896

**Comment by fwyzard** [comment]
@cmsbuild, please test with cms-sw/cmsdist#5896

**Comment by fwyzard** [comment]
unhold

**Comment by fwyzard** [comment]
+1

**Comment by fwyzard** [comment]
Seems to be fine, it;s passing both the internal jemalloc tests, and the ones under `HLTrigger/Timer/tests`.

**Comment by silviodonato** [comment]
+1

**Pull request merged**
