### PR TITLE
Update trigger filters for jets stored in Nano for Run3 menu

### PR DESCRIPTION
**Pull request by johnalison**
#### PR description:

Updating the Jet Trigger objects stored in Nano with the filters from the Run3 menu
Expect the trigObj content of the Nano to change.

#### PR validation:

Tested producing new NanoAOD in 12_4_8

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Would be good to have this in 12_4_X for Run3 Nano production.

### CODE REVIEW

**Comment by johnalison** [comment]
The changes to PhysicsTools/NanoAOD/python/triggerObjects_cff.py modified in PR(s): [#39796](https://github.com/cms-sw/cmssw/pull/39796), [#39309](https://github.com/cms-sw/cmssw/pull/39309)

can be merged with the changes proposed here.

**Comment by swertz** [comment]
Hi @johnalison , for my information, I suppose this change is not compatible with Run2 samples/triggers?

We are planning to change the way trigger object info is stored in nano, but for now we have decided that we would allow changes to the trigger object filter names necessary for Run3 so that prompt nano can pick those up, even if it breaks compatibility with Run2 or existing V10 samples. 

Can you please apply the same changes to the "frozen" V10 config, so that V10 stay in sync between 124X and 126X? https://github.com/cms-sw/cmssw/blob/master/PhysicsTools/NanoAOD/python/V10/triggerObjects_cff.py

**Comment by johnalison** [comment]
@swertz  correct. I have removed the filters that are not Run 3 and added filters that are not in Run-2. 
yes, I can also update v10.triggerObjects_cff.py

**Comment by johnalison** [comment]
@swertz  changes now in V10 config

**Comment by swertz** [comment]
enable nano
please test

**Comment by vlimant** [comment]
please test

**Comment by swertz** [comment]
+1

Only differences are seen in jet trigger objects.

**Comment by rappoccio** [comment]
+1 

* Changes expected in nano

**Pull request merged**
