### PR TITLE
PixelJetPuId  multi-threading (75X)

### PR DESCRIPTION
**Pull request by silviodonato**
This PR makes the module PixelJetPuId multi-threading friendly.
(backport in 74X: #9138 )

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Comment by Martin-Grunewald** [comment]
@davidlange6 
Despite your +1 this PR is not marked as merged! ??

**Comment by Martin-Grunewald** [comment]
please test

**Comment by davidlange6** [comment]
@Martin-Grunewald - because the tests haven't passed yet.

**Comment by Martin-Grunewald** [comment]
@davidlange6, @nclopezo 
Tests are stuck, please give it a kick.

**Comment by nclopezo** [comment]
I restarted them.

**Pull request merged**
