### PR TITLE
Phase2-hgx360L Change 2026 to Run4 for scenario declarations in various scripts of Validation/HGCalValidation

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Change 2026 to Run4 for scenario declarations in various scripts of Validation/HGCalValidation

#### PR validation:

Tested the scripts

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by antoniovagnerini** [comment]
+1
- spurious differences from HGCal DQM test (open issue  #46416)

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
