### PR TITLE
Implementation of the option preexistingprimaryvertex

### PR DESCRIPTION
**Pull request by henriettepetersen**
I implemented the option preexistingprimaryvertex in the same style as the existing option preexistingoffline in the TkAlAllInOneTool for alignment @hroskes, @connorpa.

### CODE REVIEW

**Comment by tocheng** [comment]
please test

**Comment by hroskes** [comment]
@tocheng could we try this again?  It's just xrd errors.

**Comment by tocheng** [comment]
please test

**Comment by hroskes** [comment]
@cmsbuild are you sleeping?

**Comment by tocheng** [comment]
@cmsbuild please test

**Comment by tocheng** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
