### PR TITLE
Monitoring JSON changes in DAQ (76X)

### PR DESCRIPTION
**Pull request by smorovic**
Changes:
- migrating to JSON based format for module legend used by f3mon
- adding HLTErrorEvents field which will used to distinguish between losses caused by crashes in CMSSW and other reasons, for example hardware failures.

port of #12136 submitted for 75X

### CODE REVIEW

**Comment by mommsen** [comment]
+1

**Comment by fwyzard** [comment]
+1

**Comment by deguio** [comment]
+1

**Comment by cvuosalo** [comment]
+1

For #12137 ccbf41e2bd2f8a15763e1a2f9a671518b14c64c9

Changes in the monitoring JSON for the DAQ. #12136 and #12138 are the 75X and 80X versions of this PR, and the former has already been approved by Reco.

The code changes are OK for 76X. The 80X version of this PR will require some small code changes for maintainability. Jenkins tests against baseline CMSSW_7_6_X_2015-10-27-2300 show no significant differences.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
