### PR TITLE
ROC counting trend plots per layer/ring for phase 1 pixel DQM

### PR DESCRIPTION
**Pull request by leggat**
Implementing per ring/layer ROC counting trend plots in the phase 1 pixel DQM summary code.

Trend plots for FPIX and BPIX were originally added in https://github.com/cms-sw/cmssw/pull/18993, this PR is to turn these into the per-layer/ring versions.

### CODE REVIEW

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Comment by threus** [comment]
@leggat could you please back port this PR to 92X? It is needed for the online DQM, otherwise your changes don't get merged into the current production branch.
Thanks

**Comment by leggat** [comment]
Hi Tomas - I'm confused, I thought this was already in 92X - isn't it 
already running online? It was certainly a 92X release that I pushed it 
from...

**Comment by boudoul** [comment]
hello @leggat , what you did (and was correct because this is the way to proceed) is that you pull request to 'master' which corresponds to the development release . At the time you made it , the development release was 92X, but then he stayed a bit before getting reviewed and the 93X became the devlopemnt release (93X ) instead of 92X.   Actually 2 weeks ago, this is why you see somewhere above " modified the milestone: CMSSW_9_3_X, CMSSW_9_2_X 15 days ago"   , so it has been merged in the development release (93X) and now you should backport to 92X as requested by @threus

**Comment by leggat** [comment]
Ah I see, thanks @boudoul for the clarification. I will do as requested.

**Comment by threus** [comment]
@boudoul exactly :)
@leggat thanks!

**Pull request merged**
