### PR TITLE
EMTF Unpacker Update to Add HMT and Displaced Muon Information [12_3_X]

### PR DESCRIPTION
**Pull request by eyigitba**
#### PR description:

This PR updates the EMTF unpacker to add High Multiplicity Trigger (HMT) and Displaced Muon information. The EMTF firmware at P5 is already updated to add these parameters to EMTF DAQ output. 

The main changes are in `EMTFBlockSP` for unpacking the new information. The `EMTFCollections`, `EMTFSetup` `EMTFTokens` and `SP.h` are changed accordingly to include the new Regional Muon Shower object in the EMTF unpacker workflow. 

No changes are expected in performance. 

#### PR validation:

Validated with `runTheMatrix.py -l limited -i all --ibeos` and no changes are observed.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

This is a backport of PR https://github.com/cms-sw/cmssw/pull/37194, to include this update in upcoming runs at P5.

### CODE REVIEW

**Comment by epalencia** [comment]
Please test

**Comment by cecilecaillol** [comment]
+l1

**Comment by perrotta** [comment]
backport of https://github.com/cms-sw/cmssw/pull/37194

**Comment by perrotta** [comment]
+1
- verbatim backport of #37194

**Pull request merged**
