### PR TITLE
fix some ranges/binning of plots in Phase 1 DQM

### PR DESCRIPTION
**Pull request by fioriNTU**
This PR adjust some ranges to match the present and future running conditions.

Also disable the computation of row and col starting by the rec-hit position, that couse some jittering effect in the bin population

### CODE REVIEW

**Comment by dmitrijus** [comment]
+1

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Comment by davidlange6** [comment]
hi @fioriNTU @dmitrijus - seems this added 20MB of histograms. Is that correct/

**Comment by fioriNTU** [comment]
@davidlange I will check, in principle I think to have been fair in extending/reducing the binning of histograms, no real new histogram is added there

**Comment by davidlange6** [comment]
ok, someone added 20MB of pixel histograms since 921... I suspect its this one.

**Comment by fioriNTU** [comment]
@davidlange if this is only a suspect, I think that the PR that added more Phase1 histograms lately is this one https://github.com/cms-sw/cmssw/pull/19059 , Mia deleted accidentally a large number of TProfiles from the regular Phase 1 DQM when introducing the HLTPixelDQM. This can add 20MB of stuff.
Anyway I am checking by my side.

**Comment by davidlange6** [comment]
can be - i was only guessing..

**Comment by fioriNTU** [comment]
@davidlange6  it looks like this PR doesn't add the 20MB of histos, I ran the 10024 workflow with and without and the filesize is the same 87MB in both cases

**Pull request merged**
