### PR TITLE
Added new categories (DSTJets,DSTMuons) for scouting triggers.

### PR DESCRIPTION
**Pull request by ryonamin**
Alternative PR to 11696.

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
#11620 needs to be merged first.
waiting before approving.

**Comment by deguio** [comment]
-1
rebase needed in case this is still wanted (we will switch soon to 75x)

**Comment by ryonamin** [comment]
I've made a new PR : 12163

**Pull request closed without merging**
