### PR TITLE
[DD4hep] [CMSSW_12_1] use DD4hep consistently in configurations - back port to 12_1

### PR DESCRIPTION
**Pull request by ianna**
#### PR description:

back port to 12_1: address issue #33373

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
please test

**Comment by tvami** [comment]
backport of https://github.com/cms-sw/cmssw/pull/36004

**Comment by tvami** [comment]
Hi @ianna please edit the PR title by including [12_1_X] in it (signaling that this now is a backport)

**Comment by tvami** [comment]
+1
 * tests come back all good
 * PR title should change to reflect that this is a backport to 12_1_X

**Comment by srimanob** [comment]
+Upgrade

Backport of https://github.com/cms-sw/cmssw/pull/36004.
Technical PR to resolve the issue of mix using of DD4hep and else.

**Comment by perrotta** [comment]
@ianna I don't understand the reason to backport these PRs to 12_1_X, which is a short term cycle only intended to produce the digi premix samples.
Could you please either close or explain which is the purpose of the backport?

**Comment by ianna** [comment]
> @ianna I don't understand the reason to backport these PRs to 12_1_X, which is a short term cycle only intended to produce the digi premix samples.
> Could you please either close or explain which is the purpose of the backport?

It's just to make sure we have clean naming conventions and no accidental reference to an old naming. The PR does not change any functionality.

**Comment by civanch** [comment]
+1

PR is correct @perrotta , @qliphy , it is your decision accept or not.

**Comment by perrotta** [comment]
> PR is correct @perrotta , @qliphy , it is your decision accept or not.

Thank you all!
However, such large code changes (with no practical effect on the productions foreseen with the release) cannot be accepted in closed release cycles. Let have it in 12_2_X, and in all subsequent cycles as a consequence.

**Comment by perrotta** [comment]
-1

**Comment by qliphy** [comment]
close by above comments.

**Pull request closed without merging**
