### PR TITLE
Run3-alca205C Modernize several AlCaRecoProducers for HCAL

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Modernize several AlCaRecoProducers for HCAL

#### PR validation:

Tested using standard runTheMatrix workflows

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
+alca
 * no differences due to the change, only due to " workflows 140.53 have different files in step1_dasquery.log "

**Comment by perrotta** [comment]
> * no differences due to the change, only due to " workflows 140.53 have different files in step1_dasquery.log "

Well, not really: there are jet related differences in Run2 wfs 1325.81 and 136.731: are they understood @bsunanda

**Comment by tvami** [comment]
@perrotta I dont really understand how this works, if I go to the DQM bin-by-bin
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_1_X_2021-09-30-1100+854a39/45888/dqm-histo-comparison-summary.html
there is no changes for 1325.81 nor for 136.731
```
Removed, added and changed plots
-0 | +0 | 0
```

**Comment by bsunanda** [comment]
wfs 1325.81 and 136.731 do not use any alba related to HCAL. Only 140.53 does that for hcalcalminbias. I don't think the cause of the difference is due to the changed code. It is due to different input type

**Comment by perrotta** [comment]
please test
(let give it another try...)

**Comment by perrotta** [comment]
+1
- Differences in wfs 1325.81 and 136.731 were transitories

**Pull request merged**
