### PR TITLE
[IOMC]: update vertex smearing parameters for realistic 13 TeV 50ns collisions

### PR DESCRIPTION
**Pull request by sarafiorendi**
back-porting of
https://github.com/cms-sw/cmssw/pull/10384

### CODE REVIEW

**Comment by davidlange6** [comment]
@sarafiorendi - apologies - perhaps I've missed it - is this new (3rd..) change to this beamspot discussed somewhere? We don't want these to change once we start using them.

**Comment by sarafiorendi** [comment]
Hi @davidlange6,

the reconstruction of the story is as follows:

1st change (https://github.com/cms-sw/cmssw/pull/10048 et al.) was the first attempt to provide realistic vtx smearing parameters. These were computed from 0T runs.

2nd change (https://github.com/cms-sw/cmssw/pull/10221) this is just a patch to the numbers in the previous round of PRs, which we found out were faulty
==> a bunch of MC were produced with these conditions

3rd change, the present one, computed on 3.8T runs. This differs from the previous version for the X position of the centroid and for the inclusion of the latest greatest PIX alignment. We observed that, with B = 3.8T, the X moved by ~200 um and this movement is large enough to be accounted for.
==> meant to be the best configuration for the coming MC production

I think @mmusich and @diguida can comment further

**Comment by mmusich** [comment]
@davidlange6 hopefully that should be the last time we change them. They should be used for the production of the new round of MC with the more realistic luminous region description (compared to data). 
If you wish we can arrange to have it discussed at one of the AlCa meetings, but I believe you can find a pretty detailed description in the [beamspot HN](https://hypernews.cern.ch/HyperNews/CMS/get/beamspot/134.html).
Another useful link is this page: [Beasmpot Operations](https://twiki.cern.ch/twiki/bin/viewauth/CMS/BeamSpotOperations#Results_from_2015B)

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
