### PR TITLE
Handle event meta data changes in streamer files [14_0]

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

Moved storage of meta data needed for events into the first EventMessage sent before the subsequent events which need that meta data.
This fixed a problem seen online where different HLT nodes were generating different event meta data for the same luminosity block but online the event data for one node is used.

#### PR validation:

Code compiles and unit tests pass.

backport of #44892 (and #44753 to make the former trivial to backport)

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by nothingface0** [comment]
@Dr15Jones Using 14_0_6, most of the DQM clients semm to have an issue opening existing stream files from run 380531:

```
Can't deserialize registry data (in open file): An exception of category 'FatalRootError' occurred.
   Additional Info:
      [a] Fatal Root Error: @SUB=TBufferFile::ReadClassBuffer
Could not find the StreamerInfo for version 11 of the class edm::SendJobHeader, object skipped at offset 33
```
Is this incompatibility expected?

**Comment by Dr15Jones** [comment]
> Is this incompatibility expected?

Yes. The streamer format had to be changed to accommodate the needed meta data. The streamer format has no backwards compatibility ability (by its original design). 

You'll have to do what was described before, convert the original streamer into a ROOT file then use the ROOT file as input to a new job and have that new job write the new streamer format.

**Comment by smorovic** [comment]
@cmsbuild please test

**Comment by smorovic** [comment]
+daq

**Comment by Dr15Jones** [comment]
hold

our intent is to add an additional change once the master pull request is in the IB

**Comment by mmusich** [comment]
do we really need this PR in 14_0_X (and e.g. break compatibility with the streamer files of all the 2024 past runs already saved at Tier0 for future replays)? 
tagging @francescobrivio as (incoming) ORM.

**Comment by francescobrivio** [comment]
> do we really need this PR in 14_0_X (and e.g. break compatibility with the streamer files of all the 2024 past runs already saved at Tier0 for future replays)?

I strongly support this question 😄 

>  This fixed a problem seen online where different HLT nodes were generating different event meta data for the same luminosity block but online the event data for one node is used.

Also, from the PR description I don't fully get how critical (if at all) this is for data-taking?

**Comment by smorovic** [comment]
> > do we really need this PR in 14_0_X (and e.g. break compatibility with the streamer files of all the 2024 past runs already saved at Tier0 for future replays)?
> 
> I strongly support this question 😄
> 
> > This fixed a problem seen online where different HLT nodes were generating different event meta data for the same luminosity block but online the event data for one node is used.
> 
> Also, from the PR description I don't fully get how critical (if at all) this is for data-taking?

We are fine *now* with a specific workaround that was developed, but it will depend on what gets changed in HLT during data-taking this year.
So the question is actually on HLT if we'll need this during pp (and what about HI, do we move to 14_1_X for that or stay with 14_0?).

**Comment by mmusich** [comment]
>  So the question is actually on HLT if we'll need this during pp 

my gut feeling is no (tagging also @missirol and @mtosi for extra confirmation).

> (and what about HI, do we move to 14_1_X for that or stay with 14_0?).

For HI we move in 14_1_X - there breakage in inevitable.

**Comment by mmusich** [comment]
> my gut feeling is no

on second thought, we still plan to move the HCal local reco to `alpaka` so in principle that would need to be protected by the workaround (https://github.com/cms-sw/cmssw/pull/44699/) as well.

**Comment by makortel** [comment]
This backport is part of the plan outlined in https://github.com/cms-sw/cmssw/issues/44643#issuecomment-2046098157 . It allows us to remove the quick&ugly&hacky workaround placed in https://github.com/cms-sw/cmssw/pull/44698 / https://github.com/cms-sw/cmssw/pull/44699 . Furthermore, with this PR any further Alpaka developments (such as https://github.com/cms-sw/cmssw/pull/44910) do not need be hacked with the workaround. As this PR properly groups the event-specific metadata and events in the same file, it not only solves this problem, but is also able to avoid other potential mismatches.

The streamer file breakage by this PR is no different from any other data format class change, except maybe in that it impacts the RAW that has typically not been touched during the data taking. Because of streamer file compatibility being so brittle, to my understanding, Tier0 always runs repacking using the same release with which the streamer file was produced. Therefore, old streamer files can still be used for replays, with the caveat that any change in streamer files won't get tested by those replays.

When (or if?) this PR gets deployed in 14_0_X, the deployment should be carefully planned, e.g. for a technical stop, so that it can be properly tested also in the production system without risking the data taking.

(Ultimately the risk-benefit decision of the fate of this PR is not the decision of `core`)

**Comment by francescobrivio** [comment]
> The streamer file breakage by this PR is no different from any other data format class change, except maybe in that it impacts the RAW that has typically not been touched during the data taking. Because of streamer file compatibility being so brittle, to my understanding, Tier0 always runs repacking using the same release with which the streamer file was produced. Therefore, old streamer files can still be used for replays, with the caveat that any change in streamer files won't get tested by those replays.

I think the big exception here is actually Express processing, for which there is no "repacking with original release".

> When (or if?) this PR gets deployed in 14_0_X, the deployment should be carefully planned, e.g. for a technical stop, so that it can be properly tested also in the production system without risking the data taking.

Then why not making this break even more clear and wait for 14_1_X?

**Comment by makortel** [comment]
> I think the big exception here is actually Express processing, for which there is no "repacking with original release".

Does express processing read the streamer files directly without repacking then?

> > When (or if?) this PR gets deployed in 14_0_X, the deployment should be carefully planned, e.g. for a technical stop, so that it can be properly tested also in the production system without risking the data taking.
> 
> Then why not making this break even more clear and wait for 14_1_X?

We are fine with that. The main risk seems to be repeating https://github.com/cms-sw/cmssw/issues/44643 (i.e. unreadable streamer files for use cases that use Refs etc).

We'd nevertheless suggest to continue testing of these changes (e.g. with the help of this PR).

**Comment by mmusich** [comment]
> Does express processing read the streamer files directly without repacking then?

Yes.

**Comment by germanfgv** [comment]
> Express processing at Tier0 has the technical capability of running a separate repacking step, e.g. if HLT and T0 releases do not match

I confirm this statement by @mmusich. If streamers from previous releases are not compatible, we can still run Express workflows by repacking with the streamer's original release, while performing reconstructing with the newer release.

We can also perform sigle job tests using  https://github.com/cms-sw/cmssw/blob/master/Configuration/DataProcessing/test/RunExpressProcessing.py

**Comment by Dr15Jones** [comment]
please test

**Comment by smorovic** [comment]
+1

**Comment by syuvivida** [comment]
Just to add that we tested this PR again after reproducing DQM streamers by running HLT built with 14_0_7 and 44978, now we could read the DQM streams fine and the clients ran without crashing even if some streamer files have zero event size.

**Comment by smorovic** [comment]
+1

**Comment by makortel** [comment]
Comparisons show the usual
* https://github.com/cms-sw/cmssw/issues/39803
* https://github.com/cms-sw/cmssw/issues/43790

**Comment by makortel** [comment]
+core

(this is just to have my signature on the record, avoid the future merge to become pending on `core` signature) Merging should still wait for positive outcome from the ongoing test. @cms-sw/orp-l2 Should we put this PR on hold, or is the situation clear enough without?

**Comment by antoniovilela** [comment]
> +core
> 
> (this is just to have my signature on the record, avoid the future merge to become pending on `core` signature) Merging should still wait for positive outcome from the ongoing test. @cms-sw/orp-l2 Should we put this PR on hold, or is the situation clear enough without?

Hi Matti, this PR is on hold. From the e-mail thread, one had the impression the tests were successful, but it would be good to have confirmation.
Thanks.

**Comment by tjavaid** [comment]
backport of #44892 , #44753

**Comment by tjavaid** [comment]
+1

- P5 tests OK.
- spurious differences seen from unstable WF `12834.7` (open issue #39803 )

**Comment by perrotta** [comment]
+alca
- AlCa relevant parts are the exact backport of https://github.com/cms-sw/cmssw/pull/44892
- As it was [confirmed at the Join Ops meeting of June 10](https://docs.google.com/document/d/1VscH-ZO-E_R1NPP541SBoiK9AL-OcyvALSvnSoyg8Mw/edit), tests of the event meta data changes in streamer files went fine with CMSSW_14_0_7_HLTTest

**Comment by rappoccio** [comment]
untold

**Comment by rappoccio** [comment]
unhold

**Comment by rappoccio** [comment]
+1

**Pull request merged**
