### PR TITLE
Phase2-hgx96 Correct DetId types for HGCal

### PR DESCRIPTION
**Pull request by bsunanda**
HGCEEDetId and HGCHEDetid are obsolete and currently only HGCalDetId is valid.

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Comment by fabiocos** [comment]
please test workflow 20434.0

**Comment by fabiocos** [comment]
+1

**Pull request merged**
