### PR TITLE
Add a new Data Format for BST record from TCDS raw, and use it to revive beam information, physics declared bit, and HLT event selection for online DQM

### PR DESCRIPTION
**Pull request by dmitrijus**
Backport of https://github.com/cms-sw/cmssw/pull/18108

### CODE REVIEW

**Comment by dmitrijus** [comment]
+1

**Comment by dmitrijus** [comment]
type backport

**Comment by slava77** [comment]
backport of #18108

looks like this text in the PR description is not enough for the bot to react .. or, maybe it's the capitalization

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/18470	c398400
- changes are the same as in https://github.com/cms-sw/cmssw/pull/18108	68c66f4, which is in 91X since Apr 13
- jenkins tests pass and the report includes differences in the event products, expected to be present (BSTRecord_tcdsDigis_bstRecord)

I guess that in commissioning we do not strictly require dataset version change, else it will need to happen with this change deployed.

**Pull request merged**
