### PR TITLE
Fastsim: fix segfault muon hlt

### PR DESCRIPTION
**Pull request by lveldere**
HLT expects l1ExtraParticles.centralBxOnly = True

to be merged after #8455

### CODE REVIEW

**Comment by lveldere** [comment]
please test

**Comment by lveldere** [comment]
+1

**Comment by davidlange6** [comment]
@cmsbuild, please test

**Comment by lveldere** [comment]
@davidlange6 

Tests seem to hang.
I've tested this in private on top of #8455 on 1000 events and it works properly.
Can this be merged?

**Comment by davidlange6** [comment]
+1

**Pull request merged**
