### PR TITLE
Modification of configuration for boostedTau creation 

### PR DESCRIPTION
**Pull request by roger-wolf**
Dear all, 

this is a PR with a minor modification of the configuration for the creation of boostedTaus. The only file that really has anything to do with the modification as such is 

RecoTauTag/Configuration/python/boostedHPSPFTaus_cfi.py (lines 22 & 23)

The other files are part of a infrastructure that we use for our internal testing and validation (e.g. of this change), which has been extended to be able also to validate boostedTaus now. 

The modification as such loosens the anti-muon discriminator requirement to be more efficient for the identification of boostedTaus. It has been verified that this increases the efficiency of the identification of boostedTaus in the relevant kinematic regimes, where two taus might be very close to each other. For non-boosted taus the expected behaviour is: 

1) no difference on normal taus (obviously);
2) only small to tiny differences on boostedTaus (in the usually tested regimes for release validation);
3) if changes occur they should only be visible in the anti-muon discriminators (loose and tight WP) and lead to an increased probability to pass the discriminator value. 

Usual tests have been made w/o notice of any problems. 

Cheers,
Roger

### CODE REVIEW

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
+1

For #15996 a52d50398add810acf8dbe0a6ab1f175df9843ac

Small configuration change to improve boosted tau ID efficiency.

The code changes are satisfactory, and Jenkins tests against baseline CMSSW_8_1_X_2016-09-28-1100 show no significant differences. A test of workflow 25202.0_TTbar_13 with 100 events against baseline CMSSW_8_1_X_2016-09-27-1100 also shows no significant differences. CPU time (without DQM or Validation) for the affected module appears to improve by almost 10%:
```
  delta/mean delta/orJob     original                   new       module name
  ---------- ------------     --------                  ----       ------------
    -0.080255      -0.05%        78.75 ms/ev ->        72.67 ms/ev recoTauAK4PFJets08RegionBoosted
  ---------- ------------     --------                  ----       ------------
```

**Comment by slava77** [comment]
On 9/29/16 3:14 PM, Carl Vuosalo wrote:
> +1
> 
> For #15996 <https://github.com/cms-sw/cmssw/pull/15996> a52d503
> <https://github.com/cms-sw/cmssw/commit/a52d50398add810acf8dbe0a6ab1f175df9843ac>
> 
> Small configuration change to improve boosted tau ID efficiency.
> 
> The code changes are satisfactory, and Jenkins tests against baseline
> CMSSW_8_1_X_2016-09-28-1100 show no significant differences. A test of
> workflow 25202.0_TTbar_13 with 100 events against baseline
> CMSSW_8_1_X_2016-09-27-1100 also shows no significant differences. 


Looks like the boosted taus are not monitored in miniAOD DQM.
TAU POG better add some standard validation for this rather costly
reconstruction


> CPU
> time (without DQM or Validation) for the affected module appears to
> improve by almost 10%:
> 
> |delta/mean delta/orJob original new module name ---------- ------------
> -------- ---- ------------ -0.080255 -0.05% 78.75 ms/ev -> 72.67 ms/ev
> recoTauAK4PFJets08RegionBoosted ---------- ------------ -------- ----
> ------------ |

this must be random

the modified modules
hpsPFTauDiscriminationBy{Loose,Tight}MuonRejection3Boosted
are running after recoTauAK4PFJets08RegionBoosted

**Comment by davidlange6** [comment]
+1

**Pull request merged**
