### PR TITLE
Add layer counting capability to PixelActivityFilter

### PR DESCRIPTION
**Pull request by JanFSchulte**
Adds the ability to cut on the number of layers with pixel clusters in the PixelActivityFilter at HLT. Needed for 90m beta* running

### CODE REVIEW

**Comment by silviodonato** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by fabiocos** [comment]
@Martin-Grunewald @JanFSchulte late question: the new code as it is does not run because of the parameter setting, but was it tested with values of layers different than 0?

**Comment by JanFSchulte** [comment]
@fabiocos Yes, I tested this and it works as expected. The users of this module have still to do their studies to come up with their actual configuration for the HLT, but in my mock tests the results were consistent with my expectations.

**Pull request merged**
