### PR TITLE
[81X] adding key for phase2 upgrade2023 MC simulation

### PR DESCRIPTION
**Pull request by mmusich**
was in: #15942

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by lgray** [comment]
Superseded by #15936

**Comment by mmusich** [comment]
+1

**Comment by davidlange6** [comment]
@mmusich can we not remove phase2_design - it looks to be unmaintained

**Comment by mmusich** [comment]
@davidlange6, indeed. I'll give your suggestion a try in this PR.

**Comment by lgray** [comment]
Addressed and being tested in the HL-LHC beamspot PR.

**Comment by davidlange6** [comment]
+1
Thanks

**Pull request merged**
