### PR TITLE
Add TotalLoopTime to framework job report

### PR DESCRIPTION
**Pull request by Dr15Jones**

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by Dr15Jones** [comment]
@davidlange6 It would be useful to get this into 9_4 since that release also contains another addition to the framework job report for timing. By putting all changes into the same release we can make it easier for workflow management to get the specific information they want without having to keep track of so many release changes.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
