### PR TITLE
Era support for the BMTF Packer

### PR DESCRIPTION
**Pull request by panoskatsoulis**
backport of #32365

### CODE REVIEW

**Comment by panoskatsoulis** [comment]
This PR stands instead of the previous #32367 that was closed.

**Comment by smuzaffar** [comment]
please test

**Comment by silviodonato** [comment]
urgent

**Comment by silviodonato** [comment]
cc: @BenjaminRS @bundocka @cbotta

**Comment by silviodonato** [comment]
backport of https://github.com/cms-sw/cmssw/pull/32455

**Comment by rekovic** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
