### PR TITLE
[HGCAL trigger] New implementation for the V9 geometry (squashed history of #25949)

### PR DESCRIPTION
**Pull request by fabiocos**
Squashed commit of the following (original version with review history #25949):

commit 3817e56ead3c2f9dbc24f58eccb9fb616a1aec11
Author: Jean-Baptiste Sauvan <jean-baptiste.sauvan@cern.ch>
Date:   Fri Feb 22 15:35:26 2019 +0100

    Remove temporaries

commit df87dd94c29ddd9f492bcce5ce8832280e208ba7
Author: Jean-Baptiste Sauvan <jean-baptiste.sauvan@cern.ch>
Date:   Fri Feb 22 11:40:38 2019 +0100

    Remove multiple if statements in HGCalClusterT

commit f2666d19ceac71ec0580b24b71ecbb61c71462de
Author: Jean-Baptiste Sauvan <jean-baptiste.sauvan@cern.ch>
Date:   Fri Feb 15 10:26:21 2019 +0100

    Remove data geometry file

commit a6ce7dcde8babdbaf66ef75a9b76d40976b3c956
Author: Giovanni <gpetruc@gmail.com>
Date:   Thu Feb 14 16:26:20 2019 +0100

    Accessor should be float, not bool

commit 7c1d3a617294cc315554436d0a3591d7f6f7b1ce
Author: Jean-Baptiste Sauvan <jean-baptiste.sauvan@cern.ch>
Date:   Thu Feb 14 16:10:54 2019 +0100

    Fix triggerTools config in concentrator

commit 890da2274d8fe77a691690587cd164f6d916b484
Author: Jean-Baptiste Sauvan <jean-baptiste.sauvan@cern.ch>
Date:   Thu Feb 14 15:55:54 2019 +0100

    Cleaning V9Imp2 geometry

commit 81fdfa526ba7d52f606d2bf31780184791a39363
Author: Jean-Baptiste Sauvan <jean-baptiste.sauvan@cern.ch>
Date:   Thu Feb 14 15:37:44 2019 +0100

    Update geometry README

commit 1388fd587252cb8b1d42c9ec57f930c6ed6447e6
Author: Jean-Baptiste Sauvan <jean-baptiste.sauvan@cern.ch>
Date:   Thu Feb 14 14:56:31 2019 +0100

    Add isEm/Had in trigger tools

commit 19b6e3103bb42e45093fd9d3a4a0347ad6db6ce1
Author: Jean-Baptiste Sauvan <jean-baptiste.sauvan@cern.ch>
Date:   Thu Feb 14 14:40:19 2019 +0100

    Add V9 relval test config

commit e63a3b5922807bf3151875b849a25c69ea0f84c8
Author: Jean-Baptiste Sauvan <jean-baptiste.sauvan@cern.ch>
Date:   Thu Feb 14 14:38:23 2019 +0100

    Fix layer in geometry V9 Imp2

commit d1fbe90f6139ffe57d46f739519e9567669fa7bf
Author: Jean-Baptiste Sauvan <jean-baptiste.sauvan@cern.ch>
Date:   Thu Feb 14 14:36:45 2019 +0100

    Rename V9 panel mapping

commit 450eb4aea43dd752b43abd761dddf3f397a83e90
Author: Jean-Baptiste Sauvan <jean-baptiste.sauvan@cern.ch>
Date:   Fri Feb 8 15:56:38 2019 +0100

    add scintillator modules in V9 Imp2

commit b077c909b66a336f20d309f7f088dda7fed80fe9
Author: Jean-Baptiste Sauvan <jean-baptiste.sauvan@cern.ch>
Date:   Mon Jan 28 10:15:07 2019 +0100

    Silicon panels implementation in V9 Imp2

commit 6fdc831849eb7df2a90a18c7c366586a12421204
Author: Jean-Baptiste Sauvan <jean-baptiste.sauvan@cern.ch>
Date:   Wed Jan 16 16:51:17 2019 +0100

    Update detid management

commit ae1850f2155a40c90462f3d9359e79cbd11f91bb
Author: Jean-Baptiste Sauvan <jean-baptiste.sauvan@cern.ch>
Date:   Wed Jan 16 16:50:25 2019 +0100

    Add scintillator TCs for V9Imp2

commit 4ce380bd3b67391959844c9f866fda93c9120d7e
Author: Jean-Baptiste Sauvan <jean-baptiste.sauvan@cern.ch>
Date:   Fri Jan 4 16:20:48 2019 +0100

    Temporarily remove module check

commit dcd8ed94aec706c99a13c497cbbaa6c425e56c66
Author: Jean-Baptiste Sauvan <jean-baptiste.sauvan@cern.ch>
Date:   Fri Jan 4 15:24:11 2019 +0100

    Add V9 Imp2 geometry tester

commit 04873f1aec1e965c688f181a4916a472bfd0e78e
Author: Jean-Baptiste Sauvan <jean-baptiste.sauvan@cern.ch>
Date:   Thu Jan 3 13:28:25 2019 +0100

    Add v2 implementation of v9 geometry

commit e604b54b19a40503319dd4d14111624d1e233acf
Author: Jean-Baptiste Sauvan <jean-baptiste.sauvan@cern.ch>
Date:   Wed Feb 13 16:22:39 2019 +0100

    Fix thicknessIndex for trigger cells

commit 69afb47fecb7d4e8ee4df532076ba7cfea445182
Author: Jean-Baptiste Sauvan <jean-baptiste.sauvan@cern.ch>
Date:   Tue Feb 12 15:25:01 2019 +0100

    Modify relval test file

commit c1312c44ba8b812ba1e4873517dee36dda505277
Author: Giovanni <gpetruc@gmail.com>
Date:   Fri Jan 25 15:16:40 2019 +0100

    Save H/E in the Multicluster to avoid expensive recomputation

commit 1d9d31270111e500ad31cccf1a3947c9a7af2344
Author: Jean-Baptiste Sauvan <jean-baptiste.sauvan@cern.ch>
Date:   Wed Dec 19 09:33:42 2018 +0100

    Cleaning

commit 52a1cb31aca4cb5588e0c1a24dfaee6670576195
Author: Jean-Baptiste Sauvan <jean-baptiste.sauvan@cern.ch>
Date:   Tue Dec 18 17:32:28 2018 +0100

    Update compatibility of TC ntuplizer with V9 geometry

commit af70b91159ba2cd2c8a9a627636730ca29f574e9
Author: Jean-Baptiste Sauvan <jean-baptiste.sauvan@cern.ch>
Date:   Fri Dec 14 09:53:11 2018 +0100

    cleaning

commit 5cd838fdd040f47dfd1e295d06b8710d6c892fe0
Author: Jean-Baptiste Sauvan <jean-baptiste.sauvan@cern.ch>
Date:   Thu Dec 13 16:06:17 2018 +0100

    Update compatibility of digi ntuplizer with V9 geometry

commit 811623d6e4c09f6e6b0400a097ae8cb8e4b3c810
Author: Jean-Baptiste Sauvan <jean-baptiste.sauvan@cern.ch>
Date:   Thu Dec 13 16:05:27 2018 +0100

    Add layers() in trigger tools

commit 01ea123c0ed3e63285b9ee6fdd3bc99685fb103a
Author: Jean-Baptiste Sauvan <jean-baptiste.sauvan@cern.ch>
Date:   Thu Dec 13 16:04:38 2018 +0100

    Fix trigger layers

commit 4e71fbc797872fcffc3d43cd09f60670846d53df
Author: Jean-Baptiste Sauvan <jean-baptiste.sauvan@cern.ch>
Date:   Tue Dec 11 17:14:38 2018 +0100

    Add compatibility with V9 geom detid scheme

### CODE REVIEW

**Comment by fabiocos** [comment]
please test

**Comment by kpedro88** [comment]
+upgrade
identical to #25949

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Pull request merged**
