### PR TITLE
[Cond][clang-tidy] make deleted function public 

### PR DESCRIPTION
**Pull request by smuzaffar**
Cleanup for clang-tidy warning `deleted member function should be public [modernize-use-equals-delete]`

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by tvami** [comment]
+alca
* technical PR

**Comment by ggovi** [comment]
+1

**Comment by perrotta** [comment]
+1
(@cms-sw/l1-l2 this PR is technical, and changes are quite trivial: just complain in case you have problems with it, and we'll revert it)

**Comment by perrotta** [comment]
merge

**Pull request merged**
