### PR TITLE
[91X] fix spurious tickmark gain change warnings in SiStripChannelGain calibration

### PR DESCRIPTION
**Pull request by mmusich**
Greetings,
the aim of this Pull Request is to remove the spurious warnings (appearing in all workflows involving the `PromptCalibProdSiStripGains` and `PromptCalibProdSiStripGainsAfterAbortGap` producers, that are run in the Prompt Calibration Loop) of the type:

```
%MSG
%MSG-w SiStripGainFromCalibTree:   SiStripGainFromCalibTree:ALCARECOSiStripCalib@beginRun  03-Mar-2017 04:54:54 CET Run: 165121
WARNING: TickMarkGain in the global tag changed
```
(e.g. [any output of wf 1001.0](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-17753/18124/runTheMatrix-results/1001.0_RunMinBias2011A+RunMinBias2011A+TIER0EXP+ALCAEXP+ALCAHARVD1+ALCAHARVD2+ALCAHARVD3+ALCAHARVD4+ALCAHARVD5/step3_RunMinBias2011A+RunMinBias2011A+TIER0EXP+ALCAEXP+ALCAHARVD1+ALCAHARVD2+ALCAHARVD3+ALCAHARVD4+ALCAHARVD5.log) )

These have been found to originate when checking at `SiStripGainFromCalibTree::algoBeginRun` the tickmark height gain in pixel partitions (where of course it makes no sense at all).
No change in production workflows are expected (barring removal of extra log).

attn: @dimattia

### CODE REVIEW

**Comment by franzoni** [comment]
please test

**Comment by franzoni** [comment]
no changes in plots of 2016 MC 25ns, 2017 TTbar, 2016B

**Comment by franzoni** [comment]
+1

**Comment by mmusich** [comment]
Also as expected the warning are gone from the [log of wf 1001.0, step3](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-17765/18182/runTheMatrix-results/1001.0_RunMinBias2011A+RunMinBias2011A+TIER0EXP+ALCAEXP+ALCAHARVD1+ALCAHARVD2+ALCAHARVD3+ALCAHARVD4+ALCAHARVD5/step3_RunMinBias2011A+RunMinBias2011A+TIER0EXP+ALCAEXP+ALCAHARVD1+ALCAHARVD2+ALCAHARVD3+ALCAHARVD4+ALCAHARVD5.log)

**Comment by davidlange6** [comment]
+1

**Pull request merged**
