### PR TITLE
Update online bs with pv information

### PR DESCRIPTION
**Pull request by rovere**
* Update the global region definition for pixel tracking in online
* Improve the logic to select the destination of the output text files.

### CODE REVIEW

**Comment by dmitrijus** [comment]
Is this backport still needed? It has been merged upstream.

**Comment by rovere** [comment]
@dmitrijus if #19063 is merged it will automatically include this PR.

**Comment by dmitrijus** [comment]
@rovere Please close this PR.

**Comment by jfernan2** [comment]
@rovere please close this PR

**Comment by rovere** [comment]
Closing this dinosaur.

**Pull request closed without merging**
