### PR TITLE
DQM: Remove dqmEndRun in DQMEDAnalyzer

### PR DESCRIPTION
**Pull request by schneiml**
#### PR description:
Another step forward on the way towards `edm::stream` modules, I decided that we cannot support `endRun` operations in `DQMEDAnalyzer`. Same goes for begin/end lumi, but they are less common. I allow `dqmBeginRun`, since it logically makes sense and is also mostly save (It's hard to do anything illegal with DQM objects before `bookHistograms`).

The full API is still available in `DQMOneEDAnalyzer`, and the few modules having non-trivial `endRun` today where migrated to it. However, the majority was just debug printouts, which I simply removed.

This is separate PR (separate form the coming bigger changes, PR #28622 ), to make the changes affecting subsystem code more visible and allow a validation independent from the coming bigger PR.

#### PR validation:

Compiles, and no changes to *file* output are expected.  There will be less log output in some configurations.

Some "summary" printouts where removed; these might be useful, but should not be part of DQM modules.

### CODE REVIEW

**Comment by schneiml** [comment]
Properly rebased  to CMSSW_11_1_X_2019-12-04-2300 and fixed the code-format.

**Comment by schneiml** [comment]
please test

No changes expected.

**Comment by schneiml** [comment]
please test

**Comment by schneiml** [comment]
The change in JetMET is surprising. Maybe `METAnalyzer` needs to be `DQMOneLumiEDAnalyzer` (if it contains per-lumi histograms).

**Comment by civanch** [comment]
+1

**Comment by schneiml** [comment]
please test

hoping that the bin-to-bin tool is fully working again. The additional commit might fix the JetMET difference.

**Comment by schneiml** [comment]
+1

Comparison is all clean now.

**Comment by schneiml** [comment]
@fabiocos What about this one? As far as I see it is uncontroversial, just missing a lot of signatures.

Getting this in should also reduce the number of signatures on  #28622.

**Comment by fabiocos** [comment]
@schneiml the move back to ```DQMOneEDAnalyzer``` forces lack of concurrency for all the migrated classes, please correct me in case. What is the plan to move them to avoid this constraint, if any?

**Comment by schneiml** [comment]
@fabiocos as of today, *all* `DQMEDAnalyzer`s are `edm::one` modules watching lumi transitions and block concurrent lumisections (which is why we can't have them at this time).

The modules which are moved to `DQMOneEDAnalyzer` actually *drop* the lumisection watching and should be ok for concurrent lumis.

The modules moved to `DQMOneLumiEDAnalyzer` now explicitly request the current behavior and *will continue* to block concurrent lumis until manually modified.

The plan is that after  #28622, we can change `DQMEDAnalyzer` to `edm::stream`, and release the "watching lumisections" constraint from ~all DQM modules, allowing concurrent lumisections in general. Of course, that is only as long as the `DQMOneLumiEDAnalyzer`s are either not part of the relevant sequences or manually modified.

**Comment by Martin-Grunewald** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade

**Comment by schneiml** [comment]
@santocch @efeyazgan @rekovic @benkrikler @civanch @peruzzim Could you please have look and sign this PR? The changes should be rather trivial.

**Comment by santocch** [comment]
+1

**Comment by schneiml** [comment]
Still waiting for signatures, no real objections as far as I remember (@fabiocos ?).

**Comment by silviodonato** [comment]
This PR seems ready to be merged but several signatures are still missing:
generators:   @alberto-sanchez  @SiewYan  @qliphy  @efeyazgan  @mkirsano  @agrohsje 
l1:   @benkrikler  @rekovic 
xpog:   @fgolf  @peruzzim 
simulation:   @mdhildreth  @civanch 
could you review and eventually sign this PR, please?

**Comment by silviodonato** [comment]
+1

**Comment by silviodonato** [comment]
please merge

**Comment by silviodonato** [comment]
merge

**Pull request merged**
