### PR TITLE
[DD4hep] Convert Reflections via TGeo Reflection Factory

### PR DESCRIPTION
**Pull request by ianna**
#### PR description:

* While waiting for a proper solution from DD4hep: temporarily use a TGeo reflection factory to convert reflections  before calling the DD4hep G4 converter

@bsunanda - FYI
* As we have discussed, the CSC sim hits in -Z look good now
* All EE sim hits are present

Screenshot 2020-10-28 at 14 09 47

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
@cvuosalo, @civanch, @bsunanda - I think, it's safe to integrate this PR because we can control TGeo reflection factory from a configuration.

**Comment by cvuosalo** [comment]
+1

**Comment by qliphy** [comment]
@ianna   Would you mind to move from cout to edm::LogInfo or something like that (see https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideMessageLogger ) ? std::cout is not thread safe, so we should move away from it (see https://github.com/cms-sw/cms-sw.github.io/issues/94)

**Comment by ianna** [comment]
@qliphy - thanks for pointing it out. Since all unit tests use `std::cout` I'll do it in a separate PR.

**Comment by qliphy** [comment]
+1

**Comment by makortel** [comment]
> Since all unit tests use `std::cout`

`std::cout` is fine in unit tests...

**Comment by ianna** [comment]
> > Since all unit tests use `std::cout`
> 
> `std::cout` is fine in unit tests...

no action needed then :-)

**Comment by mrodozov** [comment]
please test for CMSSW_11_2_X_2020-10-28-2300

**Comment by mrodozov** [comment]
abort 
forgot to add the part that is failing. this PR broke unit test 
MagneticFieldEngineTestDriver

**Comment by ianna** [comment]
> abort
> forgot to add the part that is failing. this PR broke unit test
> MagneticFieldEngineTestDriver

sorry about that. I'll have a look shortly.

**Comment by mrodozov** [comment]
alright, it's in the last IB, I won't start the test here then (it's redundant to "prove" it)

**Comment by silviodonato** [comment]
Yes, I confirm that this PR is the origin of the issue #31987 ( test MagneticFieldEngineTestDriver had ERRORS )

**Pull request merged**
