### PR TITLE
Minor recommended changes to GEMGeometryBuilder

### PR DESCRIPTION
**Pull request by watson-ij**
#### PR description:

Minor changes recommended by @perrotta in #36715

#### PR validation:

Compiled and ran test GEMGeometry builder

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by watson-ij** [comment]
please test

**Comment by perrotta** [comment]
@cms-sw/dqm-l2 @cms-sw/upgrade-l2 @cms-sw/geometry-l2 the error in wf 4.76 is common to all PR and IB tests these days, and due to an unreachable input file.
Please consider the tests for this purely technical PR as passed, and proceed with evaluation and possible approval: this is suitable to be merged in pre4

**Comment by srimanob** [comment]
+Upgrade

Minor fix on GEM GeometryBuilder, pure technical PR.

**Comment by jfernan2** [comment]
+1

**Comment by cvuosalo** [comment]
+1

**Comment by perrotta** [comment]
+1

**Comment by perrotta** [comment]
merge

**Pull request merged**
