### PR TITLE
Fftjet eventsetup fix

### PR DESCRIPTION
**Pull request by igv4321**
#### PR description:

Proper use of ESGetToken objects for FFTJet modules, with appropriate esConsumes calls introduced in the module constructors. This is a purely technical fix, with no changes in the results expected.

#### PR validation:

The usual runTheMatrix tests were run, as well as some private tests.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
Please test

**Comment by jpata** [comment]
+reconstruction
- technical
- private code

**Comment by Dr15Jones** [comment]
The static analyzer says there are still old uses of `EventSetupRecord::get` being used in 
JetMETCorrections/FFTJetModules/plugins/FFTJetLookupTableESProducer.cc

See
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-9b18be/26582/llvm-analysis/report-001203.html#EndPath

**Comment by igv4321** [comment]
Indeed, thank you. Missed that one.

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by Dr15Jones** [comment]
@igv4321 thanks for making the fix.

**Comment by jpata** [comment]
+reconstruction
- technical
- private code

**Comment by qliphy** [comment]
+1

**Comment by qliphy** [comment]
merge

**Pull request merged**
