### PR TITLE
Changed FailPath/SkipEvent to TryToContinue [RECO]

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

The former options were replaced with the latter some time ago.

#### PR validation:

The scripts are not used anywhere.

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
+hlt
   * technical

**Comment by jfernan2** [comment]
+1

**Comment by rappoccio** [comment]
+1

**Pull request merged**
