### PR TITLE
Hlt tau trigger validation update94 x

### PR DESCRIPTION
**Pull request by slehti**
Updated Tau HLT prompt monitoring code.

### CODE REVIEW

**Comment by mtosi** [comment]
@cmsbuild, please test

**Comment by mtosi** [comment]
@slehti , please quantify the increase in #bins 
thanks

**Comment by slehti** [comment]
There were plots with range 0-200, 20 bins which would benefit from a wider range. I changed the range, and to keep the bin width the same, also the number of bins: 0-200, 20 bins -> 0-500, 50 bins.

**Comment by mtosi** [comment]
@slehti thanks, I saw it, indeed
could you please quantify the increase in #bins ?
as you know, we are trying to squeeze as much as possible the memory / size ....
did you consider a variable binning ?

**Comment by slehti** [comment]
About the binning, not all plots were changed, only 7 with higher thresholds.

I have not thought about variable binning, but if you think it is necessary to reduce the number of bins, 
I can move back to the old number of bins, 20 bins/plot. So if I need to extend the range by X, than I'll start the plot from X to keep the bin width and the number of bins constant. Shall I do it that way?

**Comment by mtosi** [comment]
if you could do it so, it would be great, I think
.. next time (it seems the increase is not dramatic, now ) ;)

thanks a lot !
 mia

**Comment by mtosi** [comment]
@cmsbuild, please test

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
