### PR TITLE
add feds

### PR DESCRIPTION
**Pull request by elaird**
This PR (for 74X) contains a cherry-picked commit from the merged 73X PR: #8223

CC: @abdoulline

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test
comparisons never finished
hoping the testing infrastructure issues are resolved by now

**Comment by slava77** [comment]
@elaird please update the subject of the PR (the first line to be more self-descriptive;
e.g. "add uTCA HF FEDs to HCAL unpacker (forward port from 73X)"

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/8689	 755ef99
the same code changes were signed off and tested in 73X in #8223

**Comment by davidlange6** [comment]
+1

**Pull request merged**
