### PR TITLE
fix for `TestDQMServicesDemo` unit test

### PR DESCRIPTION
**Pull request by missirol**
#### PR description:

This PR tries to fix the DQM unit test `TestDQMServicesDemo`.
It looks like some API calls in DQM-related scripts needed to be adjusted after the switch from `uproot-3` to `uproot-4`.
See https://github.com/cms-sw/cmssw/issues/35868 for some more details.

#### PR validation:

The relevant unit test now passes.

#### If this PR is a backport, please specify the original PR and why you need to backport that PR:

N/A

### CODE REVIEW

**Comment by missirol** [comment]
please test with #35766

(abusing my testing rights to test this quickly; the other PR seems to be needed to avoid issues in unrelated wfs)

**Comment by qliphy** [comment]
type bugfix

**Comment by qliphy** [comment]
urgent

**Comment by jfernan2** [comment]
+1
Thank you @missirol

**Comment by qliphy** [comment]
+1

**Pull request merged**
