### PR TITLE
Update Global Tags: new JEC, introducing HcalFrontEndMapRcd, updated Phase-I Pixel Geometry

### PR DESCRIPTION
**Pull request by mmusich**
# Summary of changes in Global Tags
## RunII simulation
- **RunII Ideal scenario** : [81X_mcRun2_design_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun2_design_v2) as [81X_mcRun2_design_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun2_design_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_mcRun2_design_v2/81X_mcRun2_design_v1): 
  - updated Jet Energy corrections and resolutions from `Spring16_v6` package
  - new tag for `HcalFrontEndMapRcd`: Run2 + QIE10 channels configuration 
- **RunII CRAFT scenario** : [81X_mcRun2cosmics_startup_peak_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun2cosmics_startup_peak_v2) as [81X_mcRun2cosmics_startup_peak_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun2cosmics_startup_peak_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_mcRun2cosmics_startup_peak_v2/81X_mcRun2cosmics_startup_peak_v1): 
  - updated Jet Energy corrections and resolutions from `Spring16_v6` package
  - new tag for `HcalFrontEndMapRcd`: Run2 + QIE10 channels configuration 
- **RunII Asymptotic scenario** : [81X_mcRun2_asymptotic_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun2_asymptotic_v2) as [81X_mcRun2_asymptotic_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun2_asymptotic_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_mcRun2_asymptotic_v2/81X_mcRun2_asymptotic_v1): 
  - updated Jet Energy corrections and resolutions from `Spring16_v6` package
  - new tag for `HcalFrontEndMapRcd`: Run2 + QIE10 channels configuration 
- **RunII Startup scenario** : [81X_mcRun2_startup_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun2_startup_v2) as [81X_mcRun2_startup_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun2_startup_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_mcRun2_startup_v2/81X_mcRun2_startup_v1): 
  - new tag for `HcalFrontEndMapRcd`: Run2 + QIE10 channels configuration 
- **RunII Heavy Ions scenario** : [81X_mcRun2_HeavyIon_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun2_HeavyIon_v2) as [81X_mcRun2_HeavyIon_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun2_HeavyIon_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_mcRun2_HeavyIon_v2/81X_mcRun2_HeavyIon_v1): 
  - new tag for `HcalFrontEndMapRcd`: Run2 + QIE10 channels configuration 
## RunII data
- **RunII Offline processing** : [81X_dataRun2_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_dataRun2_v2) as [81X_dataRun2_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_dataRun2_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_dataRun2_v2/81X_dataRun2_v1): 
  - updated Jet Energy corrections and resolutions from `Spring16_v6` package
  - new tag for `HcalFrontEndMapRcd`: four IOVs that have the description of the front end map during different periods of data taking (Run1, Long Shutdown 1 and Run 2)
- **RunII HLTHI processing** : [81X_dataRun2_HLTHI_frozen_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_dataRun2_HLTHI_frozen_v0) as [80X_dataRun2_HLTHI_frozen_v9](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_dataRun2_HLTHI_frozen_v9) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_dataRun2_HLTHI_frozen_v0/80X_dataRun2_HLTHI_frozen_v9): 
  - new tag for `HcalFrontEndMapRcd`: four IOVs that have the description of the front end map during different periods of data taking (Run1, Long Shutdown 1 and Run 2)
- **RunII HLT relval processing** : [81X_dataRun2_HLT_relval_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_dataRun2_HLT_relval_v0) as [80X_dataRun2_HLT_relval_v11](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_dataRun2_HLT_relval_v11) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_dataRun2_HLT_relval_v0/80X_dataRun2_HLT_relval_v11): 
  - new tag for `HcalFrontEndMapRcd`: four IOVs that have the description of the front end map during different periods of data taking (Run1, Long Shutdown 1 and Run 2)
- **RunII HLT processing** : [81X_dataRun2_HLT_frozen_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_dataRun2_HLT_frozen_v0) as [80X_dataRun2_HLT_frozen_v12](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_dataRun2_HLT_frozen_v12) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_dataRun2_HLT_frozen_v0/80X_dataRun2_HLT_frozen_v12): 
  - new tag for `HcalFrontEndMapRcd`: four IOVs that have the description of the front end map during different periods of data taking (Run1, Long Shutdown 1 and Run 2)
- **RunII Offline relval processing** : [81X_dataRun2_relval_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_dataRun2_relval_v2) as [81X_dataRun2_relval_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_dataRun2_relval_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_dataRun2_relval_v2/81X_dataRun2_relval_v1): 
  - updated Jet Energy corrections and resolutions from `Spring16_v6` package
  - new tag for `HcalFrontEndMapRcd`: four IOVs that have the description of the front end map during different periods of data taking (Run1, Long Shutdown 1 and Run 2)
## Upgrade
- **PhaseI realistic scenario** : [81X_upgrade2017_realistic_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_upgrade2017_realistic_v4) as [81X_upgrade2017_realistic_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_upgrade2017_realistic_v3) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_upgrade2017_realistic_v4/81X_upgrade2017_realistic_v3): 
  - updated Jet Energy corrections and resolutions from `Spring16_v6` package
  - new tag for `HcalFrontEndMapRcd`: Run2 + QIE10 channels configuration
  - updated phase-I tracker geometry to `81YV5` (Updated Phase 1 BPIX Geometry #14726)
- **PhaseI design scenario** : [81X_upgrade2017_design_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_upgrade2017_design_v4) as [81X_upgrade2017_design_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_upgrade2017_design_v3) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_upgrade2017_design_v4/81X_upgrade2017_design_v3): 
  - updated Jet Energy corrections and resolutions from `Spring16_v6` package
  - new tag for `HcalFrontEndMapRcd`: Run2 + QIE10 channels configuration
  - updated phase-I tracker geometry to `81YV5` (Updated Phase 1 BPIX Geometry #14726)

---

Since conditions in the `offline` tags for re-reco have been updated with IOVs for 2016, we can remove now the temporary keys `auto:run2_*_WillDisappearInJul16` from the 2016B relval matrix

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
please test

**Comment by fabozzi** [comment]
+1

**Comment by mmusich** [comment]
+1
as expected changes involve:
   * 2016B data workflows: [comparison SinglePhoton2016B](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_8_1_X_2016-07-07-1100+15141/14864/validateJR/all_OldVSNew_RunSinglePh2016Bwf136p731/)
   * 2017 simulation workflows: [comparison 1 (TTbar)](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_8_1_X_2016-07-07-1100+15141/14864/validateJR/all_OldVSNew_TTbar13TeV2017wf10024p0/), [comparison 2 (TenMu gun) ](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_8_1_X_2016-07-07-1100+15141/14864/validateJR/all_OldVSNew_TenMuE2017wf10021p0/)

**Pull request merged**
