### PR TITLE
Update RivetInterface for Rivet 3.x

### PR DESCRIPTION
**Pull request by mseidel42**
#### PR description:

* Updated interface for new major Rivet release 3.x
* Needs https://github.com/cms-sw/cmsdist/pull/5107
* Add multiweight handling for PS (default) and ME/PDF (optional) variations.

#### PR validation:

* Processed Powheg ttbar with PS, ME, and PDF (NNPDF31_nnlo) uncertainties:
image

* Checked that output of `ParticleLevelProducer` remains as expected.

### CODE REVIEW

**Comment by qliphy** [comment]
please test with cms-sw/cmsdist#5107

**Comment by intrepid42** [comment]
Ups, wanted to write the comment here, not in cmsdist: I would suggest to compile ThePEG without Rivet. There should not be any need for calling Rivet analyses directly from the the Herwig7 configuration, it can all be passed to the RivetInterface. cmsdist is updated accordingly.

**Comment by efeyazgan** [comment]
please test with cms-sw/cmsdist#5107

**Comment by intrepid42** [comment]
Removed Rivet-based FxFxAnalysis in Herwig7 (not compatible with Rivet 3) https://github.com/cms-sw/cmsdist/pull/5107/commits/5622f2169d9a28f78972433e898ec3e09a8e9139

**Comment by efeyazgan** [comment]
please test with cms-sw/cmsdist#5107

**Comment by intrepid42** [comment]
I updated https://github.com/cms-sw/cmsdist/pull/5107 again... Successful build of cmssw-tool-conf (including rivet and herwigpp) on cmsdev now.

**Comment by efeyazgan** [comment]
please test with cms-sw/cmsdist#5107

**Comment by efeyazgan** [comment]
please test with cms-sw/cmsdist#5107

**Comment by efeyazgan** [comment]
please test with cms-sw/cmsdist#5107

**Comment by efeyazgan** [comment]
please test with cms-sw/cmsdist#5107

**Comment by fabiocos** [comment]
@intrepid42 @efeyazgan @qliphy @agrohsje how was this Rivet update practically tested? Is there a link to some documentation? Was the possible impact on nanoAOD checked? @peruzzim @fgolf FYI

**Comment by intrepid42** [comment]
Hi Fabio, the nanoAOD DQM looks ok: https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-6f974d/1791/runTheMatrix-results/1325.7_TTbar_13_94Xv2NanoAODINPUT+TTbar_13_94Xv2NanoAODINPUT+NANOEDMMC2017_94XMiniAODv2+HARVESTNANOAODMC2017_94XMiniAODv2/

I am not sure if any differences to previous versions should show up on this page: https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_11_0_X_2019-08-01-2300+6f974d/32907/dqm-histo-comparison-summary.html

**Comment by fabiocos** [comment]
@efeyazgan @qliphy @agroshje @intrepid42 so are you ready to sign this PR?

**Comment by qliphy** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
