### PR TITLE
Run3-hcx326X Make use of a version of EDAnalyzer to meet multithreaded application in some Hcal codes for calibration

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Make use of a version of EDAnalyzer to meet multithreaded application in some Hcal codes for calibration

#### PR validation:

Use the runTheMatrix test workflows

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by tvami** [comment]
+alca

**Comment by rekovic** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
