### PR TITLE
`TrackingMonitor`: extend lumi monitoring for Run-3 to 2.5E34 and remove SCAL in labels

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

Title says it all, current limits are exceeded by Run-3 inst lumi projections.

#### PR validation:

None (but changes are trivial)

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

N/A

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by emanueleusai** [comment]
Looking at the DQM bin-by-bin comparisons, I understand the differences in plots vs Lumi, but I don;t get the differences in other plots such as: residual_x_per_SignedModule_per_SignedLadder, see e.g.:
https://tinyurl.com/2l6kby2p

**Comment by mmusich** [comment]
@emanueleusai 

> Looking at the DQM bin-by-bin comparisons, I understand the differences in plots vs Lumi, but I don;t get the differences in other plots such as: residual_x_per_SignedModule_per_SignedLadder, see e.g.:
https://tinyurl.com/2l6kby2p

the difference you are pointing to refers to wf. 11634.7 that is known to generate spurious differences see https://github.com/cms-sw/cmssw/issues/39803

**Comment by emanueleusai** [comment]
good point, thank you

**Comment by emanueleusai** [comment]
+1

- DQM plot differences expected in vs_lumi plots
- other differences spurious

**Comment by perrotta** [comment]
+1

**Pull request merged**
