### PR TITLE
Fix invalid includes in Alignment/OfflineValidation

### PR DESCRIPTION
**Pull request by iarspider**
#### PR description:

Fix invalid includes reported here: [link](https://cmssdt.cern.ch/SDT/jenkins-artifacts/invalid-includes/CMSSW_14_1_X_2024-07-01-1100/el8_amd64_gcc12/Alignment/OfflineValidation/)

#### PR validation:

Bot tests

### CODE REVIEW

**Comment by iarspider** [comment]
please test

**Comment by mmusich** [comment]
hold

**Comment by smuzaffar** [comment]
@mmusich , I remember few years ago we updated cmssw build rules to not allow including headers from private folders of a package (one should only include headers from `interface` dir of other package). Let me re-check the include header rules

**Comment by smuzaffar** [comment]
So according to cmssw build rules https://github.com/cms-sw/cmssw-config/blob/scramv3/SCRAM/check-product-src.py#L37-L42 , we do allow including non-interface file within a package so `SubsystemA/PackageA/<non-interface>/*` can include any file from `SubsystemA/PackageA`. 

@iarspider , we need to update https://github.com/cms-sw/cms-bot/blob/master/chk-invalid-headers.py to follow this policy

**Comment by iarspider** [comment]
@cmsbuild please abort

**Pull request closed without merging**
