### PR TITLE
drop type specifications in RecoEgamma

### PR DESCRIPTION
**Pull request by jeongeun**
#### PR description: 
Update the safer syntax for existing parameter :
- drop type specifications where the original parameter exists.
- move all parameter inside the clone/modifier

Instead of modifying parameters with full type specs, which can be interpreted as an insertion of a new parameter, it is a safer way to protect from parameter name mistakes and will also help in possible parameter migrations.
(previous PR for RecoEgamma is [PR#31243](https://github.com/cms-sw/cmssw/pull/31243). )

In this PR, a total of 10 files changed. 

RecoEgamma/EgammaElectronProducer 2 file
RecoEgamma/EgammaIsolationAlgos 2 file
RecoEgamma/EgammaPhotonProducers 6 file

#### PR validation:
Event Content comparison check was also done and there is no change with these updates.
Tested in CMSSW_11_2_X, the basic test all passed in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html).

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
The FileInPath error doesn't look being originated by this PR.
However, I am puzzled: the base release for the failing tests was CMSSW_11_3_X_2021-02-02-1100, while the error seems to be brought in CMSSW by #32641, only merged in master since CMSSW_11_3_X_2021-02-02-2300...

**Comment by smuzaffar** [comment]
@perrotta , this is because the packages touched by #32641 were also checkout ( may be due to their deps on the changes made here) during the build of this PR.

**Comment by perrotta** [comment]
> @perrotta , this is because the packages touched by #32641 were also checkout ( may be due to their deps on the changes made here) during the build of this PR.

Thank you @smuzaffar : let wait for the next IB before re-launching the tests, then

**Comment by smuzaffar** [comment]
please test
new IBs is now available

**Comment by perrotta** [comment]
+1
- Technical, following what claimed in the title and PR description
- Jenkins tests pass

**Comment by qliphy** [comment]
+1

**Pull request merged**
