### PR TITLE
FastTimerService: removed explicit calls to MonitorElement::getTH1

### PR DESCRIPTION
**Pull request by missirol**
#### PR description:

This PR is a simple follow-up to #32343 (see [this comment](https://github.com/cms-sw/cmssw/pull/32364#issuecomment-745222635)): now that the `MonitorElement::setStatOverflows` implementation has been updated in #32364, it is possible to remove explicit calls to `getTH1()` in the `FastTimerService`, in compliance with DQM recommendations.

No changes expected (this is only a change in syntax).

FYI: @jfernan2

#### PR validation:

Code compiles.

### CODE REVIEW

**Comment by fwyzard** [comment]
please test

**Comment by jfernan2** [comment]
Thanks @missirol !

**Comment by jfernan2** [comment]
+1

**Comment by Martin-Grunewald** [comment]
(1) seems like a magic number, how about (kTrue) as used in other PRs?

**Comment by missirol** [comment]
Good point, Martin. I thought it might be better to use the same type as required by the function (`unsigned int`)
https://github.com/cms-sw/cmssw/blob/dc7bcc549003ed18eebffabcf36526f3b4653386/DQMServices/Core/src/MonitorElement.cc#L907

It's not clear to me why `MonitorElement::setStatOverflows` internally resorts to `kTRUE`. Naively, I would have expect something like (pseudocode)
```cpp
  void MonitorElement::setStatOverflows(unsigned int value) {
    auto access = this->accessMut();
    if (value == 0)
      access.value.object_->SetStatOverflows(TH1::kIgnore);
    else if (value == 1)
      access.value.object_->SetStatOverflows(TH1::kConsider);
    else if (value == 2)
      access.value.object_->SetStatOverflows(TH1::kNeutral);
    else
      WARNING
  }
```
(see: https://root.cern.ch/doc/v622/classTH1.html#a476f6c171ecaad7e811fd615e8a2468a)

@jfernan2 do you have any suggestions?

Anyways, I can certainly change to `kTRUE`; it will give the same result.

**Comment by jfernan2** [comment]
IMHO, kNeutral option is misleading and we should avoid it since the global flag in CMSSW is unclear: behaviour should be to consider overflows or not.

I sticked to kTrue since it implied the least number of modifications around:
https://github.com/cms-sw/cmssw/search?q=setStatOverflows

but I am open to suggestions and to move everything to numbers. I don't have a strong preference

**Comment by missirol** [comment]
Hi @jfernan2 , thanks for your comment. I don't have a strong opinion either, here are just my 2 cents:

* if the idea is to enforce "overflows or not", as you mentioned, then it might be clearer to change the argument of `MonitorElement::setStatOverflows` to `bool` instead of `unsigned int`

* an alternative would be to just let `MonitorElement::setStatOverflows(unsigned int)` be a direct interface to `TH1::SetStatOverflows` (leaving it up to the user to call it properly), along the lines of the pseudocode written above. In this second case, existing code using `kTRUE` will still work as intended, even though it would become clearer to call `myME.setStatOverflows(1)`.

The only weak spot I see in the current impl is that if someone mistakenly calls `myME.setStatOverflows(10)` (random number), that will silently translate to `kIgnore`.

My 2 cents aside, unless there are other comments on this by you or others, later today I will change this to `kTRUE` in this PR, just to be consistent with how the function is used elsewhere in CMSSW.

**Comment by fwyzard** [comment]
>     * if the idea is to enforce "overflows or not", as you mentioned, then it might be clearer to change the argument of `MonitorElement::setStatOverflows` to `bool` instead of `unsigned int`

This is what seems to make the most sense to me.

**Comment by fwyzard** [comment]
please test

**Comment by jfernan2** [comment]
I have created:
https://github.com/cms-sw/cmssw/pull/32737
To set bool the function parameter as discussed.
Thanks

**Comment by fwyzard** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
