### PR TITLE
[14_1_X] Add HLT pixel thrust filter

### PR DESCRIPTION
**Pull request by stahlleiton**
#### PR description:

Backport of https://github.com/cms-sw/cmssw/pull/46190

### CODE REVIEW

**Comment by mmusich** [comment]
backport of https://github.com/cms-sw/cmssw/pull/46190

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
+hlt
   * verbatim backport of https://github.com/cms-sw/cmssw/pull/46190 into the 2024 HIon data-taking release

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
