### PR TITLE
Add Phase-2 GT to EventContent

### PR DESCRIPTION
**Pull request by HaarigerHarald**
#### PR description:

This adds the `P2GTCandidate`s and `P2GTAlgoBlock`s to the EventContent for Phase-2, requested by @artlbv.

@SohamBhattacharya

### CODE REVIEW

**Comment by artlbv** [comment]
FYI @rovere @VourMa

**Comment by aloeliger** [comment]
please test

**Comment by aloeliger** [comment]
+l1

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
