### PR TITLE
Add modes to ignore the original masks and prescales

### PR DESCRIPTION
**Pull request by fwyzard**
Add two new modes:
  - "ForcePrescaleValues" to apply the given prescale values
  - "ForceColumnValues"   to apply the prescales from the given column
ignoring the prescales and masks already applied.

Useful for example when skimming ZeroBias events, to ignore the masks and prescales used during data taking.

### CODE REVIEW

**Comment by fwyzard** [comment]
backport #21273

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by rekovic** [comment]
+1

**Comment by davidlange6** [comment]
merge

**Pull request merged**
