### PR TITLE
add skim configuration using bunch crossing

### PR DESCRIPTION
**Pull request by Moanwar**
#### PR description:
Add a special skim configuration for high pile up runs we had last year
#### PR validation:
The code successfully compiled and tested through CMSDriver locally test
 
#### if this PR is a backport please specify the original PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

@fwyzard  @trtomei

### CODE REVIEW

**Comment by prebello** [comment]
@kfjack this is the PR related to the thread "Skimming of Data"? Did you agree with @Moanwar? thank you.

**Comment by kfjack** [comment]
Hi @prebello the configuration reads okay to me (although there are hard-coded BX numbers in the code given this is an one-time-use module, hard to avoid I think). The only problem is that I'm not yet very sure how to test  it.

**Comment by prebello** [comment]
@kfjack  thank you. @Moanwar was it tested somehow?

**Comment by kfjack** [comment]
Hi @prebello I believe @Moanwar already tested it offline, and from the code it looks pretty straightforward as well. I guess we still need to add a RelVal or so to test it centrally?

**Comment by prebello** [comment]
> Hi @prebello I believe @Moanwar already tested it offline, and from the code it looks pretty straightforward as well. I guess we still need to add a RelVal or so to test it centrally?

yes please. The datasets were pointed by Andrea. You can take one run, also pointed by him, to make this test. All needed information is in the thread.

**Comment by boudoul** [comment]
Hello @Moanwar .Just a curiosity , why the BX  number (and range) are hardcoded  ?  Thanks

**Comment by Moanwar** [comment]
Hello @boudoul  this is a special skim configuration for high pile up runs we had last year , so we wanted to select a certain bunch crossing ranges to getting sets of raw data with well-defined pileup. We will then be able to study the HLT reconstruction timing versus the pileup ranges. is that answer your question ? thanks

**Comment by boudoul** [comment]
Yes thanks for the very prompt answer !

**Comment by fabiocos** [comment]
@Moanwar could you please fill the PR description and validation section?

**Comment by Moanwar** [comment]
Hello , is there any update on merging approval ? thanks

**Comment by kfjack** [comment]
Hi @Moanwar we need to prepare a RelVal. I'm working on it now. On the other hand, the PR should go to master branching first. In any case I'll prepare both updates together.

**Comment by Moanwar** [comment]
Hello @kfjack  thanks so much

**Comment by boudoul** [comment]
Dear @Moanwar , can you edit  your description  : "...for high pile up runs we had last year .."  --> replace last year by the year in question ... thank you - Since this is really dedicated for a special filling scheme, the indication of the fill number(s) you are talking about would be useful in case you have it

**Comment by Moanwar** [comment]
Dear @boudoul  Okay i will edit by putting the exact year and fill numbers. But i think i need to repeat this pull request to push it to the master as Phat from PPD group told me this skim should be pushed first to master because of CMS policy . Is that okay ?

**Comment by prebello** [comment]
@Moanwar any news? @kfjack

**Comment by fabiocos** [comment]
@Moanwar as agreed at last ORP this PR is no more needed and can be closed

**Comment by Moanwar** [comment]
@fabiocos Alright thanks :)

**Pull request closed without merging**
