### PR TITLE
bsunanda:Phase2-hgx45 Add the histograming part of geometry validation and also add BH validation code

### PR DESCRIPTION
**Pull request by bsunanda**
Correct the Simwatcher code to add detector information as well

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by bsunanda** [comment]
@deguio Could you please review this PR and sign

**Comment by bsunanda** [comment]
@deguio, @vanbesien Please review this PR and approve

**Comment by deguio** [comment]
ciao @bsunanda 
is this supposed to live forever as a private code?
as it is it cannot go co any central sequence.
F.

**Comment by bsunanda** [comment]
We are working out validation sequence for HGCal. We shall include this at that time. Since HGCal codes are under development right now we have not made the validation sequence yet.
________________________________

**Comment by deguio** [comment]
ok. I would keep this outside cmssw then.
the HGCGeometryValidation should migrated to be a DQMEDAnalyzer and the DQMStore should be used for the histo handling.

**Comment by bsunanda** [comment]
I do not fully understand the first comment. Yes we shall soon migrate the code to DQMEDAnalyzer and provide a client code as well.
________________________________

**Comment by deguio** [comment]
ok. good to know.
thanks,
F.

**Comment by bsunanda** [comment]
@deguio Could you approve this PR so that other people can utilize the current version now?

**Comment by deguio** [comment]
mmm. I'm not going to approve for merging a code that is not compatible with the DQM code directives.
other people could use this PR privately. anyway nothing is going to run centrally.

will wait for the updates you promised (DQMEDAnalyzer+client, etc).
thanks for uderstanding,
F.

**Comment by bsunanda** [comment]
Close this PR and added a new PR bsunanda:Phase2-hgx50 to overcome comments from DeGuo

**Pull request closed without merging**
