### PR TITLE
[13_0_X] Pythia8 photon flux

### PR DESCRIPTION
**Pull request by stahlleiton**
#### PR description:

backport of https://github.com/cms-sw/cmssw/pull/43840

### CODE REVIEW

**Comment by stahlleiton** [comment]
@hjbossi

**Comment by mandrenguyen** [comment]
backport of #43840

**Comment by mandrenguyen** [comment]
please test

**Comment by stahlleiton** [comment]
Since this PR is meant for HIN MC production, should I also make a backport to CMSSW_13_0_HeavyIon_X ?

**Comment by mandrenguyen** [comment]
@rappoccio @antoniovilela This one will eventually need to be added to a release to be built on top of  CMSSW_13_0_HeavyIon

**Comment by hjbossi** [comment]
Could an authorized user please merge this request?

**Comment by mandrenguyen** [comment]
> Could an authorized user please merge this request?

We have to wait for @cms-sw/generators-l2 to sign

**Comment by DickyChant** [comment]
@menglu21 and @bbilin any news?

**Comment by menglu21** [comment]
+1

**Comment by rappoccio** [comment]
+1

**Pull request merged**
