### PR TITLE
Ccctf tuning

### PR DESCRIPTION
**Pull request by rovere**
## Executive Summary

This PR is the first tuning of the cluster charge cut (CCC) that tries to recover hits-on-track on real data, while keeping the same performances in terms of efficiency, fake-rate and timing on Monte Carlo.

It is not excluded that some minor fine tuning will be needed in the course of the release, depending also on the outcome of the full release validation with this first set of changes.
### Monte Carlo

The standard set of tracking MTV validation plots for a TTBar sample (35PU@25ns) that compares this PR against a recent IB are available at this [link](https://roverepublic.web.cern.ch/roverepublic/MTV_ProposedTuning2/). The main points to notice are:
- overall the performance in terms of efficiency is quite the same, except for a small loss at very low pt (could be a further fine-tune will come trying to recover also this tiny fraction) [see here](https://roverepublic.web.cern.ch/roverepublic/MTV_ProposedTuning2/plots_summary_highPurity/summary.pdf)
- The fake-rate increase from an ~8% to a ~10%, but this, in a sense, is kind of unavoidable, given the nature of this PR (recovering hits implies also adding some fake ones, unfortunately). Again, [see here](https://roverepublic.web.cern.ch/roverepublic/MTV_ProposedTuning2/plots_summary_highPurity/summary.pdf) for plots. Anyway we believe this level of fake is still ok, especially since it is computed with quite loose requirements. And we do not want to hold this any further.
- in terms of timing, from private measurements, the reco time goes from 7.9 sec/ev to 8 sec/ev, so basically we do not observe any slowdown.
- Unfortunately the MC simulation does not properly simulate the loss of hit-collection-efficiency we see on data: in order to see the real effects, we also privately reconstructed 1K event from 260627.
#### Hits on Track

The results are nicely summarized [here](https://www.dropbox.com/s/07wcxcccy5m1nxh/hits.png?dl=0)
- Legend:
  - black: this PR
  - blue: an intermediate tuning
  - orange: recent IB w/o this PR
  - red: prompt-reco on the full statistics
- Comments
  - this PR recovers ~2 hits on track on the full eta range (black vs orange).
  - the red is above the orange simply because it integrates the full run, including the last part at "low-lumi"
#### Hit Efficiency

The plot is available [here](https://www.dropbox.com/s/hqdfptbbpr12la3/globalEfficiencies.png?dl=0). There are clear improvements in all SiStrip detectors, especially in TIB and TOB. More plots available from within CERN only [here](http://mrovere-dqmgui-slc6.cern.ch:8060/dqm/dev/start?runnr=260627;dataset=/SingleMuon/ReReco260627_ProposedTuning2_80X/DQMIO;sampletype=offline_data;filter=all;referencepos=overlay;referenceshow=all;referenceobj1=other%3A%3A/RelValTTbar/CMSSW_8_0_0_ProposedTuning2/DQMIO%3A;referenceobj2=other%3A%3A/SingleMuon/ReReco260627_ProposedTuning_80X/DQMIO%3A;referenceobj3=other%3A%3A/SingleMuon/ReReco260627_80X/DQMIO%3A;referenceobj4=other%3A%3A/SingleMuon/Run2015D-PromptReco-v4/DQMIO%3A;search=effi;striptype=object;stripruns=;stripaxis=run;stripomit=none;workspace=Everything;size=M;root=Tracking/TrackParameters/highPurityTracks/pt_1/HitEffFromHitPattern;focus=;zoom=no;).
#### SiStrip Cluster Charge Plots

Few plots are available [here for TIB](https://www.dropbox.com/s/uef4x5izi8k5075/TIB_Charge.png?dl=0) and [here for TOB](https://www.dropbox.com/s/hgyhxziw3l84cy1/TOB_Charge.png?dl=0). From these plots it is quite clear the effect of the current PR.
#### Timing

Timing wise, I observed no significant slowdown comparing 80X vanilla reco and 80X+this PR reco.
## New CCC Logic

The cluster charge cut is now applied in 2 different ways:
- as en estimator, while deciding if a hit is compatible or not. This is the CCC that we have been using during 2015@25ns data taking. For the first 4 iterations the threshold of this cut has been lowered to 800 (was 1620/1945), while for all the latter, the thresholds are identical to what was already there.
- as a trajectory filter. The first 4 iterations will accept at most 2 hits (either consecutive or not) whose charge is in the range 800;1620 (the current Loose threshold). The exception is the LowPt iteration, that will only accept one such hit (the reason being that there is not much gain in pushing it up to 2 for this iteration).
- All the logic beyond the first 4 iterations has been unchanged, in order to contain timing and fake-rate.
## Miscellanea

This PR contains also a customise for HLT in order to avoid crashes@HLT due to the fact that a parameter has been changed from a simple double to a refToPset_, in order to keep the symmetry with all other CCC cuts. I leave the "integration" of the customize into the HLT Menu to HLT experts

@mtosi

### CODE REVIEW

**Comment by slava77** [comment]
@rovere any more commits coming?

**Comment by rovere** [comment]
No thanks. I do not know the best way to guess the PR number for the HLT customize, so the additional commit was intended since the beginning.

If there is a better policy I'm interested in learning it.

Ciao,
Marco.

Sent from my HTC

----- Reply message -----

**Comment by slava77** [comment]
@cmsbuild please test
I wasn't sure it was just for the PR number

**Comment by Martin-Grunewald** [comment]
I have a question on the HLT change. How did you identify the PSets in the HLT config needing to be changed? The issue is that the HLT menu has developed since what is currently in 80X (for HIon and ppRef), so how can one figure out which additional PSets (potentially) need a change? Are they tied to some specific producer modules or what?

**Comment by rovere** [comment]
Ciao @Martin-Grunewald, the modules that should be changed are the TrajectoryFilters that now must have a new PSet  configured properly.
What I did was simply running reHLT and fixing the problems as they appeared: not the smartest move, I agree, but in the end it was quite fast.
If you have ways to bulk-edit the HLT menu and modify in one go all the configured TrajectoryFilters (C++-wise, i.e. with all possible python labels), I'd be interested in knowing how, in case I need to go through the same exercise again in the future.

**Comment by Martin-Grunewald** [comment]
The ConfDB GUI (where the HLT menu is being edited) allows to select/find all module instances based on their C++ class type. What C++ types are these, precisely?

**Comment by makortel** [comment]
@rovere In the customize, you could e.g. loop over all PSets of cms.Process (`process.psets_()` gives their labels), and do the change for those whose `ComponentType` is `CkfBaseTrajectoryFilter` (I'm assuming that only these TrajectoryFilters in the HLT menu need to be edited).

**Comment by rovere** [comment]
Ciao @makortel 
indeed that's a possibility, but it sounds a little heavy solutions.
@Martin-Grunewald  the C++ type is indeed ```CkfBaseTrajectoryFilter```

**Comment by Martin-Grunewald** [comment]
Well, there are no plugins of C++ type ```CkfBaseTrajectoryFilter``` in the HLT menu - is that a base class name? ConfDB only knows about the actual class type of a plugin - what are those for this problem? Or is it as @makortel describes, that one looks not for module instances but for PSets
whose component type parameter has value ```CkfBaseTrajectoryFilter```?

**Comment by makortel** [comment]
@Martin-Grunewald Indeed these are not modules (EDProducer/EDFilter), but helper plugins constructed within an EDProducer (and configured via top-level PSets and `refToPSet_`).

**Comment by rovere** [comment]
http://cmslxr.fnal.gov/dxr/CMSSW/source/TrackingTools/TrajectoryFiltering/interface/CkfBaseTrajectoryFilter.h#16
and the plugin is defined here:
http://cmslxr.fnal.gov/dxr/CMSSW/source/TrackingTools/TrajectoryFiltering/plugins/modules.cc

So these are not ED*, but helper plugins.

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/12718	 0a45240
- changes in the code are in line with the PR description
    - there might still be changes in the HLT config customization (the thread is not very clear), probably not yet.  addOn tests passed, which means the HLT menus available are OK with the change. The new behavior doesn't allow a default. So, any place that was not changed would not run.
- jenkins test pass and comparisons show differences in tracks and objects downstream
- tested locally with higher statistics using CMSSW_8_0_X_2015-12-07-1100.
    - on the tracking side I see changes consistent with what's posted in the description of the PR
    - I didn't find substantial changes in other objects downstream of the iterative tracking other than those related directly to the tracks
        - in samples with PU, the pf candidates charged hadrons yields go down pt < 1 GeV (maybe as much as ~5% in the 0.3 to 0.7 GeV range)
        - maybe significant: there is about 25% increase in the particleFlowDisplacedVertex visible in 25202 (ttbar PU35), which is not visible in other (all lower PU) samples.
    - technical performance:
        - on-disk size decreases a bit by ~0.1% in 2015 data and increases by 0.1% in PU35 (fakes overtake?)
        - CPU increases by about 1% in 2015C data and by about 2% in PU35 ttbar. The increase is clearly in the modified iter tracking modules (detachedTriplet, lowPt and pixelPair) which take about 10% CPU time

A part of the hitEff pattern efficiency increase is from plain CCC inefficiency (not from 25 ns PU effects), which is apparently not described that well in MC:
- in MC I don't see significant changes in generalTracks/HitEff globalEfficiency plots
- in data there is an increase even as early as 2011 data
wf 1000
wf1000_hiteffpatt_general
wf 4.53 in 2012B
wf4 53_hiteffpatt_general
wf 134.805 in 2015C
wf134 805_hiteffpatt_highpur

wf 134.911 in 2015D
wf134 911_hiteffpatt_general

**Comment by rovere** [comment]
@Martin-Grunewald  can we try and have this approved in time for pre3?

**Comment by Martin-Grunewald** [comment]
+1

**Comment by rovere** [comment]
@Martin-Grunewald thanks.

**Comment by davidlange6** [comment]
+1

**Comment by VinInn** [comment]
so this did not enter in pre3, did it?
At this point I doubt tracking can be fully validated before pre5....

**Comment by rovere** [comment]
Looking [here](https://github.com/cms-sw/cmssw/releases/tag/CMSSW_8_0_0_pre3) indeed it is confirmed that it did **not** enter pre3, which is basically equivalent to say that we will not validate anything on top of this until end-january. That's 1+ month lost.

**Comment by davidlt** [comment]
This shouldn't be a big issue. If this change is critical @davidlange6 can just tag pre4 and build that today then 1+ month is not lost.

**Comment by fwyzard** [comment]
HF 1x1 TP production along 2x3 TP (#12654)

is also rather urgent.

Ciao,
.Andrea

**Comment by slava77** [comment]
@rovere @VinInn 
Did you have any planned tracking feature changes that depend on validation of this PR?
Also, is the set of relvals adequate? Do we have enough 2015 data to see the phase space that you may be most interested in?

If so, we may want to have a pre4 this week.

**Comment by davidlange6** [comment]
is there a plan for validation reports to happen over the holidays? If not, there is not really a difference between today an Jan 4 that I see..

**Comment by rovere** [comment]
Ciao @davidlange6 ,
I guess RelVal for pre3 will be launched over Xmas (so that we would have handy samples to use). If we wait for pre4, we have to add, at least, another couple of weeks in 2016.
@slava77 I guess the standard set or RelVals, at this level, is fine. I'd like to see the effects on other objects as a first priority.

**Pull request merged**
