### PR TITLE
MINIAOD BUGFIX: pvREF not set for some electrons

### PR DESCRIPTION
**Pull request by arizzi**
Electron pfCandidates with gsfTracks but without a generalTrack are not associated to PVs in MINIAOD.
The fix tests both gsfTracks and regular tracks for all PFCandidates (preferring the gsfTrack when both available)

@gpetruc

### CODE REVIEW

**Comment by davidlange6** [comment]
@cmsbuild, please test

**Comment by arizzi** [comment]
I must have not commited the last fix... apologies.. fixing now!

**Comment by arizzi** [comment]
@davidlange6  can you please trigger cmsbuild again (apologies for the missing commit)

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/8842	2db0a1b
- the code changes look reasonable
- jenkins tests run OK (covers miniAOD step integrity)
- there are no changes in reco step outputs based on fwlite monitoring or DQM/Validation plots, as expected (the changes are touching a different code used only in miniAOD slimming)

**Pull request merged**
