### PR TITLE
MTD validation: update monitoring of reconstructed clusters

### PR DESCRIPTION
**Pull request by fabiocos**
#### PR description:

In order to support the validation of MTD cluster properties, which will be the topic of a next PR, several histograms so far optional and off by default are promoted as regular histograms to be monitored. At the same time, the large memory-consuming 2D occupancy plots are moved under the optional flag, since they are more useful for visual inspection in case of debugging than for quantitative comparisons.

#### PR validation:

The code runs smoothly on test wf. 20903.0 producing the desired output.

### CODE REVIEW

**Comment by fabiocos** [comment]
@gsorrentino18 FYI

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
thanks to @gsorrentino18 for noticing it, of course it does not change any conclusion/result

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
@cms-sw/dqm-l2 any comment or question?

**Comment by emanueleusai** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
