### PR TITLE
Switching off reconstruction of so called "NullTaus"

### PR DESCRIPTION
**Pull request by roger-wolf**
Hi all, 

this is a simple configuration switch to remove the so called "null-taus" from the tau reconstruction. Null taus are jets seeding tau candidates, which actually do not fulfil any good tau reconstruction criterion. In the past these had been kept in the reconstruction for debugging purposes, since it allows a 1:1 correspondence of reconstructed tau candidates with seeding jets. In the meantime this should be switched to False when running in standard reconstruction. For more details refer to @mbluj. 

NB: 
we have split this change off from https://github.com/cms-sw/cmssw/pull/17620 for clarity reasons. See also discussion in the conversation there.

Cheers,
Roger

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by mbluj** [comment]
Hi,
it is added an additional selection at output of tau producer to remove tau candidates without a real leading PFChargedHadronCandidate. In some taus it can substituted by a neutral PFCandidate matched to rather poor general track not used by PFlow which produces a tau candidate with a null or small momentum. Tau candidates removed by this selection do not pass tau-decay mode reconstruction required at analysis level.

**Comment by slava77** [comment]
@cmsbuild please test

the addOn test failure appears to be due to (intermittent?) file IO  issues

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
-1
superseded by #17706
90X is closed for new feautres: this is a new feature, despite of it been somewhat technical

**Pull request closed without merging**
