### PR TITLE
ECAL skip GPU unpacking of the rest of the block if a bad block is detected - 130x

### PR DESCRIPTION
**Pull request by thomreis**
#### PR description:

Skip the GPU unpacking of the rest of the block if a bad block is detected in one thread. This behaviour matches the one of the CPU unpacker.

Backport of https://github.com/cms-sw/cmssw/pull/42301 for HLT.

#### PR validation:

No crashes with integrity errors observed in runs 367771, 368547, and 368724 in https://github.com/cms-sw/cmssw/issues/39568. Passes WF 12434.512

### CODE REVIEW

**Comment by thomreis** [comment]
type ecal

**Comment by thomreis** [comment]
enable gpu

**Comment by thomreis** [comment]
backport of #42301

**Comment by thomreis** [comment]
please test

**Comment by perrotta** [comment]
> I let @rappoccio and @perrotta comment, but normally one would make the 13_1_X backport as well. Doesn't cost much.

I agree. If we backport in an older release cycle it is a good habit to also backport in all open cycles in between, unless there are counterindications in doing so.
Instead, I wonder if a backport to the pp data taking release 13_0_X is still really needed, now that it is clear that there will be no pp data taking with 13_0_X any more in 2023. Some discussion about whether to keep maintaning that release for the data taking will be addressed during the next ORP: stay tuned.

**Comment by thomreis** [comment]
OK I will make the 13_1_X backport as well then.
For this one I let you decide. If you do not want it in the end you can close the PR.

**Comment by thomreis** [comment]
13_1_X backport: https://github.com/cms-sw/cmssw/pull/42406

**Comment by clacaputo** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
