### PR TITLE
Proposal for Fastsim premix wfs (7_5_X)

### PR DESCRIPTION
**Pull request by lveldere**
I propose premix workflows for FastSim to initiate discussion with PdmV about validation of FastSim with premixing. 

I added FastSim equivalents  for each of the 25ns FullSim scenarios.

### CODE REVIEW

**Comment by lveldere** [comment]
@srimanob, @nclopezo, @boudoul, @franzoni

May I kindly remind you of this one?
Cheers Lukas

**Comment by franzoni** [comment]
hello Lukas, @lveldere  further to our conversation, may we suggest that:
1) you comment out all workflow's dependent on the existence of the premix sample
2) you include in relval_premix.py only the workflows which will have a regular fast.vs.full validation comparison (not to load the IB process beyond what we need)
3) can you please remove the print statement at line 823
4) to avoid temporary failures in the IB, we suggest you comment out the lines 813-824
Cheers, Phat and Giovanni

**Comment by lveldere** [comment]
sorry, i will rebase :-)

**Comment by lveldere** [comment]
> 1) you comment out all workflow's dependent on the existence of the premix
> sample
>
done

> 2) you include in relval_premix.py only the workflows which will have a
> regular fast.vs.full validation comparison (not to load the IB process
> beyond what we need)
>
I kept ttbar and the nugun

> 3) can you please remove the print statement at line 823
>
done

> 4) to avoid temporary failures in the IB, we suggest you comment out the
> lines 813-824
> Cheers, Phat and Giovanni
>
I don't understand what I'm supposed to do here.
As far as I understand I have commented out everything that could lead to
failures in IB, see my reply to 2)

**Comment by franzoni** [comment]
Hello Lukas @lveldere , this PR got closed and I fear you committed from a wrong branch, leading to 1k files modified. Concerning your last "I don't understand", I do follow your logic, though to take a look we would need this PR to be re-based.

Further to our conversation on Mobday, Phat @srimanob is following this task - he's out today. Is #8893 intended to replaced this PR ? If so, may you please apply to #8893 the suggestions we gave here ?

**Pull request closed without merging**
