### PR TITLE
updates src files to use md5 as external

### PR DESCRIPTION
**Pull request by iahmad-khan**

### CODE REVIEW

**Comment by iahmad-khan** [comment]
@cmsbuild please test with https://github.com/cms-sw/cmsdist/pull/2370

**Comment by iahmad-khan** [comment]
@cmsbuild, please test with cms-sw/cmsdist#2370

**Comment by iahmad-khan** [comment]
@degano @smuzaffar @davidlange6 should we merge it.

**Comment by mmusich** [comment]
+1

**Comment by iahmad-khan** [comment]
@cmsbuild, please test with cms-sw/cmsdist#2370

**Comment by iahmad-khan** [comment]
@cmsbuild, please test with cms-sw/cmsdist#2370

**Comment by smuzaffar** [comment]
@cmsbuild, please test with cms-sw/cmsdist#2370
one last try to see if unit test failure has any thing to do with this PR

**Comment by smuzaffar** [comment]
addon test error is unrelated to this PR (missing input file).
@davidlange6 , feel free to merge this (md5 external is already part of 81X IBs)

**Comment by smuzaffar** [comment]
cmsbuild, please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
+1
unit tests errors are unrelated to this PR.

**Pull request merged**
