### PR TITLE
Multi thread lhe to increase GEN efficiency

### PR DESCRIPTION
**Pull request by perrozzi**
Still under testing.
Requires modification to the random number seeds (seed*10) in production to avoid duplicates.

### CODE REVIEW

**Comment by perrozzi** [comment]
in principle, with nthread=8 this requires to unpack 8 times the gridpack, which could become a problem for mg5_amc. a switch could (should) be added to activate/deactivate the functionality

**Comment by alberto-sanchez** [comment]
@perrozzi looks your PR comes from different branch.

**Comment by davidlange6** [comment]
Your PR is unmergeable. Please have a look and possibly rebase it.

**Comment by perrozzi** [comment]
rebased

**Comment by alberto-sanchez** [comment]
please test

**Comment by alberto-sanchez** [comment]
@perrozzi do you have this for master branch as well?

**Comment by perrozzi** [comment]
is master the HEAD? I thought it was CMSSW_10_2_X, sorry.
ps the PR should not be merged yet, needs further work

**Comment by davidlange6** [comment]
Yes, master always is always the development branch

**Comment by qliphy** [comment]
@perrozzi   Does this rely on the read-only gridpack feature implemented in official MG only since 2.6.1?

**Comment by fabiocos** [comment]
@perrozzi @qliphy what is the status of this PR? Do we have a master version of it? I do not think so...

**Comment by perrozzi** [comment]
Hi, sorry for the very long delay. It's trivial to port it to master, will do it unless somebody has already done it in the meanwhile. Will also add a few features that are missing

**Comment by perrozzi** [comment]
which cmssw release shall I use to push to master?

**Comment by perrozzi** [comment]
(found)

**Comment by perrozzi** [comment]
since https://github.com/cms-sw/cmssw/pull/24653 doesn't assign people, let's continue the discussion here.
If we want to implement this feature and ensure some kind of back-compatibility, in my opinion we need a discussion.
There are a few possibilities that need to be taken into account... To the ones coming to my mind are:
   - madgraph LO and POWHEG gridpacks which are inefficient with multi-core and need this feature. The gridpacks are not-read-only, and need to be untarred as many times as the number of threads,
   - madgraph LO (future,  >=v2.6.1) gridpacks which are inefficient with multi-core and need this feature, but they are read-only that can be untarred only once or are uploaded to cvmfs already untarred
   - madgraph NLO that in principle are efficient and don't need this feature

Is there any case missing?
To keep back-compatibility and don't touch the order/number of script parameters I propose to make the ncpu parameter
```
ncpu=${4}
echo "%MSG-MG5 thread count requested = $ncpu"
```
customizable in the following way.
A purely numerical parameter (e.g. `8`) will indicate no need for the manual multi-threading feature (i.e. old behavior as of now), while an alphanumeric parameter like `8m` will activate the multi-threading feature with multiple untarring, and `8r` will activate the multi-threading feature with single/no untarring.

Please let me know if this is clear and if you think it makes sense, I will implement an example to clarify what I have in mind

**Comment by qliphy** [comment]
Should we set different random number? And  "1"  will be updated with "$ncpu"?

https://github.com/cms-sw/cmssw/blob/4820571fc98b30307b07ca24dce9b89ebe49d3b5/GeneratorInterface/LHEInterface/data/run_generic_tarball_cvmfs.sh#L75

**Comment by qliphy** [comment]
Adding more people @bendavid @kdlong @AndreasAlbert @agrohsje @covarell @lviliani 

@perrozzi     Current implementation is only for the first one you listed, right? :

"madgraph LO and POWHEG gridpacks which are inefficient with multi-core and need this feature. The gridpacks are not-read-only, and need to be untarred as many times as the number of threads,"

**Comment by AndreasAlbert** [comment]
@perrozzi do you have any (rough) numbers to quantify how much faster this is? Exact improvement obviously depends on the process, size of the gridpack, etc., but it would be good to have an approximate feeling. How many events do we need to produce to break even?

**Comment by perrozzi** [comment]
@AndreasAlbert this PR is not updated yet, please refer to this for further comments https://github.com/cms-sw/cmssw/pull/24653
I didn't do extensive timing tests yet, but for sure in the case of POWHEG this can speed up things sensibly since the gridpack is generally very small.

**Comment by efeyazgan** [comment]
please test

**Comment by fabiocos** [comment]
@perrozzi @efeyazgan @qliphy @alberto-sanchez sorry but I am a bit confused about this PR. It was born in 10_3_X, it stayed inactive for several months, then it was finally approved without much apparent discussion in GitHub. Nevertheless it does not look to be a backport of master, where a new script has been created with the run_generic_tarball_cvmfs_manual_multithread.sh  name, but it is not even corresponding to that script in master, although close. Could you please clarify what is the ultimate target here, and why 10_2_X should depart from master?

**Comment by efeyazgan** [comment]
@perrozzi could you please make the backport from the new master?

**Comment by fabiocos** [comment]
hold

@efeyazgan I understand that what you want is effectively to backport master, so I put this on hold

**Comment by fabiocos** [comment]
As discussed in the review of #25966, this PR is superseded by that and may be closed

**Pull request closed without merging**
