### PR TITLE
Adding Run2 Comsics Global Tag to autoCond and make wf 1307.0 use it

### PR DESCRIPTION
**Pull request by mmusich**
# Changes in GT
- adding the `run2_mc_cosmics` autoCond key: [80X_mcRun2cosmics_startup_peak_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_mcRun2cosmics_startup_peak_v0) as [80X_mcRun2_asymptotic_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_mcRun2_asymptotic_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/80X_mcRun2cosmics_startup_peak_v0/80X_mcRun2_asymptotic_v1):
  - Startup Tracker, DT and CSC alignment
  - L1 configuration for top-bottom cosmics triggering

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
please test

**Comment by hengne** [comment]
+1

**Comment by mmusich** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
