### PR TITLE
FastSim clean FamosProducer

### PR DESCRIPTION
**Pull request by lveldere**
- remove never-used input formats for signal and pu events
- remove never-used configuration files for vertex smearing
- remove imports of vertex smearing configuration from PF: these imports are obsolete, probably since a long while

### CODE REVIEW

**Comment by lveldere** [comment]
please test

**Comment by lveldere** [comment]
closing this for the moment
some old fastsim validation packages depend on the 'never-used' interfaces.
need to verify whether these packages are useful,
and if they are, whether it makes sense to use those 'never-used' interfaces

**Comment by lveldere** [comment]
please test

**Comment by lveldere** [comment]
+1

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/8875	af0a750
- changes are clear and are fastsim-specific
- there are no changes in jenkins tests comparisons (including the FS workflows)

**Comment by davidlange6** [comment]
+1

**Pull request merged**
