### PR TITLE
Fix ROC mapping in `SiPixelFEDChannelContainer_PayloadInspector`

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

During the preparation of the Bad FED channel scenario for the 2023 MC production (documented at this [cmsTalk](https://cms-talk.web.cern.ch/t/new-pixel-status-scenarios-and-probabilities-for-2023-mc/28126)) it was noticed that the `SiPixelFEDChannelContainer`  and `SiPixelQuality` payload inspectors gave different sets of masked ROCs even if they should have been in principle contained the same sets.
This was traced back (thanks to @tsusa) to a erroneous mapping of the ROCs within the module in the `SiPixelFEDChannelContainer_PayloadInspector`.
This is fixed in this PR, together with miscellaneous graphical improvements.

#### PR validation:

Tested by comparing the output of 

```console
getPayloadData.py \
    --plugin pluginSiPixelQuality_PayloadInspector \
    --plot plot_SiPixelBPixQualityMap \
    --tag SiPixelQuality_byPCL_stuckTBM_v1 \
    --time_type Lumi \
    --iovs '{"start_iov": "1589554511348014", "end_iov": "1589554511348014"}' \
    --db Prod \
    --test ;
```
(IOV `1589554511348014` correpsonds in packed cond Time to `run 370097, LS 302`) and compared it with the output of the command

```console
getPayloadData.py \
    --plugin pluginSiPixelFEDChannelContainer_PayloadInspector \
    --plot plot_SiPixelBPixFEDChannelContainerMap \
    --tag SiPixelStatusScenarios_StuckTBM_2023_v1_mc \
    --input_params '{"Scenarios": "370097_302"}' \
    --time_type Run \
    --iovs '{"start_iov": "1", "end_iov": "1"}' \
    --db Prod \
    --test ;
```

before and after the PR.
Here are the results:

|  Reference | Target (before PR) | Target (after PR) |
| ----------- | ----------- | ----------- |
|  image |  image | image | 

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

N/A

### CODE REVIEW

**Comment by mmusich** [comment]
type bug-fix

**Comment by mmusich** [comment]
please test

**Comment by perrotta** [comment]
+db

**Comment by perrotta** [comment]
+1

**Pull request merged**
