### PR TITLE
[backport] Added new filter, thought for a B -> l HNL X analysis

### PR DESCRIPTION
**Pull request by mgratti**
#### PR description:

Backport of #33308 + implements the modifications done in #33806. 

Needed for a possible Ultra-legacy B-parking MC production.

### CODE REVIEW

**Comment by qliphy** [comment]
please test

**Comment by agrohsje** [comment]
@mgratti Please update this backport with the latest version. Same for https://github.com/cms-sw/cmssw/pull/33815 . Thanks so much!

**Comment by mgratti** [comment]
Yes, I will proceed now! Thank you

**Comment by agrohsje** [comment]
please test

**Comment by agrohsje** [comment]
+generators

**Comment by qliphy** [comment]
+1

**Pull request merged**
