### PR TITLE
Dt conditions cleanup

### PR DESCRIPTION
**Pull request by namapane**
Complete the copy ctor and assignment op of DTRecoConditions (cf https://github.com/cms-sw/cmssw/commit/9e6c46eddeed3fb6abd7d305cf8e9d093302a85a#commitcomment-11050618).
Complete tools for writing/dumping this payload. 
Clean-up (remove) unused/dummy/duplicate DT payload tools.

### CODE REVIEW

**Comment by mmusich** [comment]
@namapane to make it clean let's wait for #8976 to be approved

**Comment by namapane** [comment]
Actually this is unrelated to #8976, there's no change in the payoad format. So I would proceed with this independently.

**Comment by diguida** [comment]
@mmusich @namapane 
At this point better to have this in first, so that you can run the final version of your tools producing an SQLite file. In the meantime, the other PR goes in and you can upload to dropbox.

**Comment by diguida** [comment]
+1

**Comment by mmusich** [comment]
@ggovi ping

**Comment by ggovi** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
