### PR TITLE
Update pileupCal.py using numpy

### PR DESCRIPTION
**Pull request by tuthongtran**
#### PR description:

Update pileupCal.py using numpy. Works with python3
More details in https://github.com/cms-sw/cmssw/pull/34092
#### PR validation:

tested in CMSSW_12_0_0_pre6

### CODE REVIEW

**Comment by ggovi** [comment]
please test

**Comment by perrotta** [comment]
@tuthongtran could you please assign a more meaningful title to your PR?

Perhaps, "Update pileupCal.py using numpy" or "Update pileupCal.py for python3"

**Comment by ggovi** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
