### PR TITLE
Migrate rest of CSCTFTrackProducer to EventSetup consumes

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

This PR is part of #31061. It should complete the EventSetup consumes migration for CSCTFTrackProducer (the partial migration caused failures in #31746).

#### PR validation:

Code compiles.

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by silviodonato** [comment]
kind reminder @cms-sw/l1-l2

**Comment by rekovic** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
