### PR TITLE
[EGM] Remove unused sub-package RecoEgamma/Examples

### PR DESCRIPTION
**Pull request by swagata87**
#### PR description:
Removed unused sub-package RecoEgamma/Examples.
Purely technical PR. No physics change is expected.
Addresses this issue: https://github.com/cms-sw/cmssw/issues/36590

#### PR validation:
CMSSW compiles.
Checked that the following worked successfully:
`runTheMatrix.py -l 11834.0`

This PR is not a backport.
Backport not needed.

### CODE REVIEW

**Comment by swagata87** [comment]
@cmsbuild  please test

**Comment by jpata** [comment]
Thanks! Can you clarify the status of this PR, why is it "do not merge"?

**Comment by swagata87** [comment]
this PR is now ready for review, as we did not receive any objection about removing the sub-package

**Comment by jpata** [comment]
type egamma

**Comment by swagata87** [comment]
I will get back to this PR after ~1 week (going on a vacation.. )

**Comment by jpata** [comment]
+reconstruction
- technical cleanup of dead code

**Comment by qliphy** [comment]
+1

**Pull request merged**
