### PR TITLE
PPS Diamond Sampic timing calibration renaming AlCa Prompt producers

### PR DESCRIPTION
**Pull request by ChrisMisan**
#### PR description:
This PR is a refactoring (renaming) of the AlCa Prompt producers responsible for PPS Timing Calibration.
The changes are necessary for T0 replay with PPS. The suggestions for renaming appeared in the discussion of #36273
It is following #36698

### CODE REVIEW

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by yuanchao** [comment]
+1
* renaming of the AlCa Prompt producers for PPS
* matrix WF tests passed

**Comment by tvami** [comment]
urgent

**Comment by grzanka** [comment]
Closing in favour of https://github.com/cms-sw/cmssw/pull/36702 as suggested in https://github.com/cms-sw/cmssw/pull/36702#issuecomment-1018693912

**Comment by ChrisMisan** [comment]
Commits included in #36702

**Pull request closed without merging**
