### PR TITLE
adding 2018 PbPb path

### PR DESCRIPTION
**Pull request by goni-zz**
related to PR: #25059

### CODE REVIEW

**Comment by andrius-k** [comment]
backport of #25059

**Comment by andrius-k** [comment]
please test

**Comment by goni** [comment]
@andrius-k I can see the dqm is pending in this PR. Can we expect when it is going to other test to merge?

**Comment by andrius-k** [comment]
+1

**Comment by mandrenguyen** [comment]
@fabiocos I've just been told this PR was desired for data taking.  Clearly it's a bit late, but can we go ahead and merge this in case the data taking release is updated for other reasons?

**Comment by fabiocos** [comment]
@mandrenguyen at the last ORP meeting we agreed to wait for a patch for the first collisions, in case some fix is needed there. I am anyway planning an update on the short timescale, including this PR

**Comment by fabiocos** [comment]
+1

**Comment by mandrenguyen** [comment]
@fabiocos Thank you.  We also have a request today from the muon POG to add or modify a central skim needed for monitoring the CSCs with RAW-RECO.  That PR will come tomorrow.

**Pull request merged**
