### PR TITLE
Fix bug when an exception happens near lumi end

### PR DESCRIPTION
**Pull request by Dr15Jones**
Fixed a bug where an exception happens during event processing near
a lumi end boundary such that some streams see the exception while
others exited normally.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
This fixes the abort seen in the IB RelVal for workflow 25406

https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc7_amd64_gcc630/CMSSW_10_1_X_2018-02-09-1100/pyRelValMatrixLogs/run/25406.0_ZMM_13+FS_ZMM_13_UP15_PU25+HARVESTUP15FS+MINIAODMCUP15FS/step1_ZMM_13+FS_ZMM_13_UP15_PU25+HARVESTUP15FS+MINIAODMCUP15FS.log

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by Dr15Jones** [comment]
type bug

**Comment by fabiocos** [comment]
+1

**Pull request merged**
