### PR TITLE
Fix compilation warnings in CalibCalorimetry pkg

### PR DESCRIPTION
**Pull request by mrodozov**
This PR fixes the warnings from CalibCalorimetry pkg after clang-tidy checks modifications done here https://github.com/cms-sw/cmssw/pull/20755

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by ghellwig** [comment]
+1
provided jenkins agrees
@smuzaffar is it possible to include this in the code checks?

**Comment by smuzaffar** [comment]
@ghellwig , we are thinking the same.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
