### PR TITLE
ME0SegAlgoRU - fix self-subtraction bug

### PR DESCRIPTION
**Pull request by jshlee**
#### PR description:

follow up to #26913, fix self-subtraction bug in ME0SegAlgoRU

#### PR validation:

tested with runTheMatrix.py -w upgrade -l 20011.0

@watson-ij

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by kpedro88** [comment]
+upgrade

**Comment by perrotta** [comment]
> Comparison Summary:
> 
> * No significant changes to the logs found
> * Reco comparison results: 0 differences found in the comparisons

@jshlee , do you have any comparison available where one can see the effect of this (quite reasonable) bug fix?

**Comment by jshlee** [comment]
@perrotta - no not yet. I've been a bit busy at a conference.

**Comment by perrotta** [comment]
> @perrotta - no not yet. I've been a bit busy at a conference.

Ok @jshlee, the fix makes enough sense, and it doesn't require a dedicated validation (although I would have been curious to see what was the effect of the bug...).

**Comment by perrotta** [comment]
+1
- Quite logical bug fix
- Jenkins tests pass and show no difference: likely some dedicated test sample needed to evaluate its effect on ME0

**Comment by fabiocos** [comment]
+1

**Pull request merged**
