### PR TITLE
Code Fix to read tower geometry correctly in Ecal DQM StatusManager [12_4_X]

### PR DESCRIPTION
**Pull request by abhih1**
#### PR description:

This PR fixes the code to read tower geometry correctly in Ecal DQM StatusManager.
Additionally the `toGet` method of accessing the DB tags is removed from the Ecal DQM config, on the suggestion of AlcaDB.

#### PR validation:
PR is validated by running a local test which creates an sqlite file which is uploaded to the DB and verified with an online DQM run on a test DQM GUI. Everything looks as expected.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:
Backport of https://github.com/cms-sw/cmssw/pull/38357
Backport needed to maintain continuity in production versions

### CODE REVIEW

**Comment by emanueleusai** [comment]
please test

**Comment by emanueleusai** [comment]
type ecal

**Comment by emanueleusai** [comment]
backport of #38357

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
@cmsbuild , please test with https://github.com/cms-sw/cmssw/pull/38455

**Comment by tvami** [comment]
@cmsbuild , please abort

**Comment by tvami** [comment]
@cmsbuild , please test with https://github.com/cms-sw/cmssw/pull/38456

**Comment by tvami** [comment]
+alca

**Comment by emanueleusai** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
