### PR TITLE
Flexible SOI config for HF

### PR DESCRIPTION
**Pull request by igv4321**
Introducing flexible sample of interest configuration for HF (to have the capability to reconstruct pre- and post-samples). The mode of operation is described in the cfi comments.

This PR will not modify any existing relval results.

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by igv4321** [comment]
Sorry, forgot something. This PR should be complete now.

**Comment by igv4321** [comment]
Sorry, not yet...

**Comment by igv4321** [comment]
OK, pushed the right file. This PR is really complete now.

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by bsunanda** [comment]
@perrotta @slava77 Please sign this - it is needed for phisymmetry calibration

**Comment by perrotta** [comment]
+1
New parameters allow for more possibilities of selecting the "Sample Of Interest"
Default values preserve the previous behavior, and therefore no effects on the results is visible

**Comment by davidlange6** [comment]
+1

**Pull request merged**
