### PR TITLE
Run3-ft17 Correct a few python files

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Correct  a few cfg files to enable passing unit tests (see #29814)

#### PR validation:

Tested using the scripts in Validation/Geoemtry

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by kpedro88** [comment]
@bsunanda why does this PR delete cmsExtendedGeometry2026D56XML_cfi.py ?

**Comment by bsunanda** [comment]
It was in the wrong place. Geometry/CMSCommonData/python has the same cfi file.

**Comment by kpedro88** [comment]
Ah, thanks.

**Comment by kpedro88** [comment]
+upgrade

**Comment by cvuosalo** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
