### PR TITLE
fix clang static analyzer warning using namespace in header

### PR DESCRIPTION
**Pull request by gartung**
Missed this one in the last pull request for this package.

### CODE REVIEW

**Comment by gartung** [comment]
@Dr15Jones

**Comment by mmusich** [comment]
please test

**Comment by gartung** [comment]
@Dr15Jones

**Comment by Dr15Jones** [comment]
please test

**Comment by mulhearn** [comment]
please test

**Comment by mulhearn** [comment]
please test

**Comment by mulhearn** [comment]
Maybe deleting the branch and reopening has hosed cmsbuild for this PR?  I'll just make a new one...

**Comment by mulhearn** [comment]
Arghhh, github won't let you resumbit the same PR.  @gartung:  I think it might be easiest if you just close the PR and remake it...

**Comment by gartung** [comment]
resubmitting

**Pull request closed without merging**
