### PR TITLE
Phase2-hgx330 Transfer most of the HGCal TB related geometry file to the new branch Geometry/HGCalTBCommonData

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Transfer most of the HGCal test-beam related geometry files to anew project area Geometry/HGCalTBCommonData. Once this PR is merged and this project area is declared as a part of CMSSW, the corresponding files in Geometry/HGCalCommonData will be deleted

#### PR validation:

A thorough test will be done once the corresponding files in SimG4CMS are updated

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@smuzaffar Could you please add this package in the list

**Comment by smuzaffar** [comment]
@bsunanda , done in https://github.com/cms-sw/cmssw/pull/40122

**Comment by bsunanda** [comment]
+geometry

**Comment by perrotta** [comment]
+1
- @bsunanda please proceed with the deletion of the duplicated files, then (and the needed redirections, I imagine)

**Pull request merged**
