### PR TITLE
MTD validation: update track-MTD matching efficiency monitoring

### PR DESCRIPTION
**Pull request by fabiocos**
#### PR description:

This PR proposes several updates to the MTD validation and reconstruction code, in view of a detailed study of the MTD clustering:

- the ```MtdTracksValidation``` class is updated by adding histograms to monitor track - ```TrackingParticle``` matching, also including TP with a ```SimTrack``` linked to MTD hits, to better disentangle acceptance effects from other inefficiency sources. This monitoring is now running also in case of fake primary vertex, allowing the code to run also on particle guns output, where the usual vertex selection fails;
- the local reconstruction monitoring is optimised by adding a ```break``` statement in the loop to match simulated and reconstructed hits inside a cluster. The time taken should be significantly cut, especially on events with PU;
- several debugging printout is added or polished, also in cluster reconstruction classes.

The memory addition to histogram output has been measured to be about 6 KiB.

#### PR validation:

Test MTD validation configuration runs smoothly and provide the desired histograms. As a side note ```SimTrack``` producing hits in ETL are not saved, as outside the tracker volume. This issue should be addressed in a separate development.

### CODE REVIEW

**Comment by fabiocos** [comment]
please test

**Comment by jpata** [comment]
type mtd

**Comment by emanueleusai** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

This PR is considered to be technical from the upgrade related code. No change is expected on MTD related quantities.

**Comment by perrotta** [comment]
+1

**Comment by fabiocos** [comment]
making further checks, I realized that the absence of matches in ETL for tracks to TP with simulated ETL hits is primarily due to a trivial bug at https://github.com/cms-sw/cmssw/pull/38064/files#diff-035207001dc7d8a415f150209e67549137f2abeee744f4a55af9d9620b691babR406 , tracks outside Tracker acceptance play a secondary role. I have a fix ready, which I will integrate with further updates

**Pull request merged**
