### PR TITLE
MTD geometry/reconstruction: update tests, invert order of forward DetLayers

### PR DESCRIPTION
**Pull request by fabiocos**
#### PR description:

This PR addresses an issue reported by @parbol while validating the rebase of the addition of MTD to tracker navigation. As a default the order of the forward DetLayers looks inverted compared to what expected as default ordering (from negative to positive). This PR simply swaps the order, ~~so far it should be irrelevant for the use of the MTD code inside the reconstruction~~, but matters when adding MTD to the layers navigation.

At present the layers order matters only in the selection of ETL hits and their use for track building inside the ```TrackExtenderWithMTD```, where it was not properly managed, as the code was developed in a single-ETL disc content. 
In order to 1) get the correct behaviour that 2) makes the algorithm independent on the input ordering, a corresponding update of the ETL hits search is made (please note that the track build code still needs an update to properly use the timing information of both disks if present, work to follow and be based on this PR).

At the same time geometry tests are updated, also in order to become independent from ```MTDTopology```, whose real usefulness is under scrutiny and will be likely dropped or seriously revised in next future. 

#### PR validation:

Code compiles and run, the local test shows a change in the ordering of DetLayers:

```
*** allBTLLayers():              1
  0  subdet = Phase2TimingBarrel Barrel = 1 Forward = 0  Cylinder of radius:     117.629585

*** allETLLayers():              4
  0  subdet = Phase2TimingEndcap Barrel = 0 Forward = 1  Disk at:    -303.154999
  1  subdet = Phase2TimingEndcap Barrel = 0 Forward = 1  Disk at:    -300.265015
  2  subdet = Phase2TimingEndcap Barrel = 0 Forward = 1  Disk at:     300.265015
  3  subdet = Phase2TimingEndcap Barrel = 0 Forward = 1  Disk at:     303.154999

*** allForwardLayers():              2
  0  subdet = Phase2TimingEndcap Barrel = 0 Forward = 1  Disk at:     300.265015
  1  subdet = Phase2TimingEndcap Barrel = 0 Forward = 1  Disk at:     303.154999

*** allBackwardLayers():              2
  0  subdet = Phase2TimingEndcap Barrel = 0 Forward = 1  Disk at:    -300.265015
  1  subdet = Phase2TimingEndcap Barrel = 0 Forward = 1  Disk at:    -303.154999

*** allLayers():              5
  0  subdet = Phase2TimingEndcap Barrel = 0 Forward = 1  Disk at:    -303.154999
  1  subdet = Phase2TimingEndcap Barrel = 0 Forward = 1  Disk at:    -300.265015
  2  subdet = Phase2TimingBarrel Barrel = 1 Forward = 0  Cylinder of radius:     117.629585
  3  subdet = Phase2TimingEndcap Barrel = 0 Forward = 1  Disk at:     300.265015
  4  subdet = Phase2TimingEndcap Barrel = 0 Forward = 1  Disk at:     303.154999

```

### CODE REVIEW

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
hold

pending a clarification about the observed differences

**Comment by fabiocos** [comment]
rebased on CMSSW_11_3_X_2021-03-16-2300, benefiting from #33139

**Comment by fabiocos** [comment]
I have updated the PR description, the bug fixed by #33139 was partly hiding the fact that the order of layers effectively matters in the use of multiple ETL hits for track building (never adjusted so far). Using the appropriate ```-t 0.99999``` threshold for statistical comparison in RelMon, as done by the cms-bot, this is visible also in a standalone test.

With the latest commit anyway the ```TrackExtenderWithMTD``` code becomes independent on the order of the endcap layers (verified with printouts and DQM comparison adding the latest commit on both this PR and on top of the original code).

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
unhold

**Comment by cvuosalo** [comment]
+1

**Comment by perrotta** [comment]
@fabiocos from your comments I derive that you verified the outputs, and understood and approved all differences observed there in the relevant phase2 geometry: could you please confirm?

**Comment by fabiocos** [comment]
@perrotta the updated test clearly shows that now forward layers are those at positive z, as usually expected. Furthermore, a look at the behaviour of the updated ```TrackExtenderWithMTD``` running it on top of both the old and new order of DetLayers shows no more difference, since the protection now ensures that the correct order of the hits is used.

Since previously the use of hits in the extender was depending on the order, some difference has to be expected, and in the premixing samples, where the multiplicity is much higher, they are magnified, this is my interpretation of the DQM output.

**Comment by perrotta** [comment]
+1
- Fix verified to act as expected in the MTD reco outputs

**Comment by fabiocos** [comment]
@srimanob comments?

**Comment by srimanob** [comment]
+Upgrade

**Comment by qliphy** [comment]
+1

**Pull request merged**
