### PR TITLE
Fix clang warnings in HeterogeneousCore/CUDAServices

### PR DESCRIPTION
**Pull request by makortel**
Clang complained from two unused variables.

### CODE REVIEW

**Comment by makortel** [comment]
@fwyzard Could you double-check that this is a correct fix?

**Comment by fwyzard** [comment]
@makortel thanks for the heads up.

I'd rather not make changes to `NVProfilerService` in the official cmssw until we merge the changes from the patatrack branch.

**Comment by fwyzard** [comment]
-1

**Comment by smuzaffar** [comment]
@makortel , we did a cleanup of some large data files which were merge in cmssw repo few days ago. Due to this cleanup this PR is now in a bad state (includes all the commits which we rewrite to avoid the large data files), Can you please rebase this PR based on new head?

**Comment by makortel** [comment]
Let's see some other way indeed.

**Pull request closed without merging**
