### PR TITLE
Phase2-hgx315Y Try to fix the error reported in #38276

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Try to fix the error reported in #38276 

#### PR validation:

Tested by scenario 2026D92

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special - it is a Bug Fix

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
Why are there so many comparison differences in the 2026 workflows? Isn't this PR supposed to be a simple bug fix?

**Comment by bsunanda** [comment]
The earlier bug was causing wrong cell assignments for one of the coarse wafers. This fix is expected to change simulation results

**Comment by cvuosalo** [comment]
+1

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cvuosalo @srimanob Please approve this PR

**Comment by smuzaffar** [comment]
please test workflow 36234.0 for CMSSW_12_5_UBSAN_X
just to make sure it has fixes the error reported in https://github.com/cms-sw/cmssw/issues/38276#issue-1263604053

**Comment by cvuosalo** [comment]
+1

**Comment by bsunanda** [comment]
@srimanob When there is a bug, one does not knw what it could cause. As it was taking values outside bound in the buggy version, we were expecting changes in the workflows

**Comment by bsunanda** [comment]
@srimanob Please approve this

**Comment by srimanob** [comment]
+Upgrade

**Comment by qliphy** [comment]
+1

**Pull request merged**
