### PR TITLE
Use PREMIX in the name of the .97 workflow

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

This PR is a follow-up to the discussion in https://github.com/cms-sw/cmssw/pull/27753#issuecomment-557797983 to use PREMIX as the dataset name for the pileup library for the premix workflows coming from the upgrade matrix. The PR is marked as RFC because I'm not sure if the changes here are sufficient.

#### PR validation:

Workflow 20661.97 runs.

### CODE REVIEW

**Comment by makortel** [comment]
@chayanit 

This PR shows how far I got in using PREMIX as the dataset name. Let me repeat my question https://github.com/cms-sw/cmssw/pull/27753#issuecomment-523065187 

> From where exactly is the dataset name picked up? E.g. the directory created by runTheMatrix has the form `<num>_<name>+<step>[+<step2>]`, is it the `<name>` part? Or from one of the `step`s?

With this PR `runTheMatrix -n` shows
```
20661.97 PREMIX_2026D41PU_PremixHLBeamSpotFullPU_Premix
```
and running the workflow produces a directory
```
20661.97_NuGun+PREMIX_2026D41PU_PremixHLBeamSpotFullPU_Premix
```

Are these sufficient for the PREMIX to be picked up as the dataset name? Or is something additional needed?

**Comment by makortel** [comment]
@cmsbuild, please test workflow 20661.97

**Comment by chayanit** [comment]
Hi @makortel, sorry for not being able to reply promptly, too many things in hands. 

To answer your (very long time ago) question, I think the suffix "PREMIX" is picked up from --datatier we setup in upgradeStepDict of each step and the code read it through MatrixInjector.py. 

This is a cmsDriver we would like to have for .97 (premix stage1) for example 11861.97
 cmsDriver.py step1  --conditions auto:phase1_2021_realistic --pileup_input das:/RelValMinBias_14TeV/CMSSW_11_0_0_pre12-110X_mcRun3_2021_realistic_v5-v1/GEN-SIM -n 10 --era Run3 --eventcontent PREMIX --procModifiers premix_stage1 **--relval 100000,100** -s GEN,SIM,DIGI:pdigi_valid --datatier PREMIX --pileup Run3_Flat55To75_PoissonOOTPU **--evt_type SingleNuE10_cfi** --io PREMIXUP21_PU25.io --python PREMIXUP21_PU25.py --no_exec --fileout file:step1.root  --nThreads 4 > step1_PREMIXUP21_PU25+PREMIXUP21_PU25.log

I tried your implementation and this is cmsDriver I got. 
 cmsDriver.py SingleNuE10_cfi.py  --conditions auto:phase1_2021_realistic --pileup_input das:/RelValMinBias_14TeV/CMSSW_11_0_0_pre12-110X_mcRun3_2021_realistic_v5-v1/GEN-SIM -n 10 --era Run3 --eventcontent PREMIX --procModifiers premix_stage1 **--relval 9000,50** -s GEN,SIM,DIGI:pdigi_valid **--beamspot Run3RoundOptics25ns13TeVLowSigmaZ** --datatier PREMIX --pileup Run3_Flat55To75_PoissonOOTPU --geometry DB:Extended --io PREMIX_2021PU_PremixFullPU_Premix.io --python PREMIX_2021PU_PremixFullPU_Premix.py --no_exec --fileout file:step1.root  --nThreads 8 > step1_NuGun+PREMIX_2021PU_PremixFullPU_Premix.log

I don't think premixing stage1 needs beamspot as GS step.

**Comment by makortel** [comment]
@chayanit 

> To answer your (very long time ago) question, I think the suffix "PREMIX" is picked up from --datatier we setup in upgradeStepDict of each step and the code read it through MatrixInjector.py.

Doesn't the data tier to go position 3 in our dataset naming convention `/1/2/3`? I though we're talking about how to replace (in lossyspeak) `SingleNuE10` with `PREMIX` in 1.

Thanks for the target cmsDriver command. The main difference seems to be `SingleNuE10_cfi.py` -> `step1 --evt_type SingleNuE10_cfi`, correct? 

> I don't think premixing stage1 needs beamspot as GS step.

Right, the beamspot might be unnecessary. On the other hand, does it do any harm?

**Comment by chayanit** [comment]
> @chayanit
> 
> > To answer your (very long time ago) question, I think the suffix "PREMIX" is picked up from --datatier we setup in upgradeStepDict of each step and the code read it through MatrixInjector.py.
> 
> Doesn't the data tier to go position 3 in our dataset naming convention `/1/2/3`? I though we're talking about how to replace (in lossyspeak) `SingleNuE10` with `PREMIX` in 1.

Oh, I thought you were asking me about 3. I think your current setup will give 1 => 'PrimaryDataset': 'RelValNuGun' but what we need is RelValPREMIXUP21_PU25.  
> 
> Thanks for the target cmsDriver command. The main difference seems to be `SingleNuE10_cfi.py` -> `step1 --evt_type SingleNuE10_cfi`, correct?
> 
> > I don't think premixing stage1 needs beamspot as GS step.
> 
> Right, the beamspot might be unnecessary. On the other hand, does it do any harm?

I have to think more carefully on this question.

**Comment by makortel** [comment]
> Oh, I thought you were asking me about 3. I think your current setup will give 1 => 'PrimaryDataset': 'RelValNuGun' but what we need is RelValPREMIXUP21_PU25.

So from where is the `NuGun` inferred from for the dataset name?

> > > I don't think premixing stage1 needs beamspot as GS step.
> > 
> > 
> > Right, the beamspot might be unnecessary. On the other hand, does it do any harm?
> 
> I have to think more carefully on this question.

The upgrade matrix seems to set beamspot and geometry for all GEN-SIM steps
https://github.com/cms-sw/cmssw/blob/8f71eb0e649b60496f33a206c635be2a7c2692b7/Configuration/PyReleaseValidation/python/relval_steps.py#L3107-L3115
so I'm reluctant to change that for premixing stage1 (which is customized on top of the "GenSim" steps).

**Comment by makortel** [comment]
> > Oh, I thought you were asking me about 3. I think your current setup will give 1 => 'PrimaryDataset': 'RelValNuGun' but what we need is RelValPREMIXUP21_PU25.
> 
> So from where is the `NuGun` inferred from for the dataset name?

Could it come from the directory name of the workflow? For example, 250199.18 has
```
250199.18_PREMIXUP18_PU25+PREMIXUP18_PU25/
```
while 11861.97 has
```
11861.97_NuGun+SingleNuE10_cf_2021PU_PremixFullPU_Premix/
```
so I'm wondering if the pattern could be something along `<workflow number>_<dataset name>+<steps>`?

**Comment by chayanit** [comment]
Yes, you're somehow right. But directory name is also picked up from "upgradeFragments" in upgradeWorkflowComponents.py

**Comment by chayanit** [comment]
> > I have to think more carefully on this question.
> 
> The upgrade matrix seems to set beamspot and geometry for all GEN-SIM steps
> 
> https://github.com/cms-sw/cmssw/blob/8f71eb0e649b60496f33a206c635be2a7c2692b7/Configuration/PyReleaseValidation/python/relval_steps.py#L3107-L3115
> 
> 
> so I'm reluctant to change that for premixing stage1 (which is customized on top of the "GenSim" steps).

Indeed, I realised too and thinking if we need to specify a new "upgradeStepDict" for Premixing and not use the one from GenSim.

**Comment by makortel** [comment]
Now the 11861.97 workflow produces a directory
```
11861.97_PREMIXUP21_PU25+PREMIX_2021PU_PremixFullPU_Premix/
```
and (phase2) 20661.97
```
20661.97_PREMIXUP26D41_PU25+PREMIX_2026D41PU_PremixHLBeamSpotFullPU_Premix/
```

Does this resolve the dataset name issue?

(I'm not really sure if the `--evt_type` change https://github.com/cms-sw/cmssw/pull/28470/commits/3676170e98139a821baac31bd48ba48db3987282 is actually a useful change)

I'd prefer that further improvements in premixing handling in the upgrade matrix would be left to subsequent PR(s), preferably by someone with longer-term vision of how these pieces should evolve.

**Comment by makortel** [comment]
@cmsbuild, please test workflow 11834.99,12634.99,13034.99,20634.99,20661.97

**Comment by srimanob** [comment]
@fabiocos 
Maybe this is the one to go to pre14, consider as fix for Phase-2 premix relvals.

**Comment by kpedro88** [comment]
please test workflow 11834.99,12634.99,13034.99,20634.99,20661.97

**Comment by fabiocos** [comment]
@makortel @chayanit in my understanding the ```--beamspot``` option should be dummy for pure premixing, as it affects only the GEN-SIM step, loading the appropriate fragment in https://cmssdt.cern.ch/lxr/source/Configuration/StandardSequences/python/VtxSmeared.py

**Comment by kpedro88** [comment]
@makortel what is the status of this PR? Is it ready?

**Comment by makortel** [comment]
> what is the status of this PR? Is it ready?

I suppose it depends whether the `--beamspot` should be removed from premix stage1 job. Technically stage1 job *does* GEN-SIM (even though the gen fragment is just nu-gun). On the other hand the workflows in `relval_premix.py` do not include `--beamspot` for stage1 jobs. Further OTOH, the `--beamspot` was there in the upgrade stage1 jobs already before this PR, so one could argue it could/should be changed in a separate PR.

I'm also not sure if PdmV (@chayanit) already confirmed whether this PR is actually sufficient to set the dataset name to contain PREMIX (I missed if they/she did).

**Comment by chayanit** [comment]
> > what is the status of this PR? Is it ready?
> 
> I suppose it depends whether the `--beamspot` should be removed from premix stage1 job. Technically stage1 job _does_ GEN-SIM (even though the gen fragment is just nu-gun). On the other hand the workflows in `relval_premix.py` do not include `--beamspot` for stage1 jobs. Further OTOH, the `--beamspot` was there in the upgrade stage1 jobs already before this PR, so one could argue it could/should be changed in a separate PR.

I think if it's complicated to remove '--beamspot' for premixing library, we can keep it as it shouldn't do anything to nu-gun sample. 

> 
> I'm also not sure if PdmV (@chayanit) already confirmed whether this PR is actually sufficient to set the dataset name to contain PREMIX (I missed if they/she did).

Somehow, I tried your modification and it doesn't work. However, I have been busy to CMSDAS in Beijing this week and next week as organising committee at CMS week in Bangkok. I can have a look again only during winter break, sorry.

**Comment by fabiocos** [comment]
@makortel @chayanit concerning the issue of ```beamspot```: stage1 jobs are doing GEN-SIM production of a neutrino gun, a trick to produce empty events on top of which to mix pre-produced MinBias GEN-SIM hits for a pure pileup sample (because using Geantinos was unpractical). As no real hit is produced (unless it is your most unlucky day), you could position the beamspot for the neutrino gun on the moon and get the same physical result. In the digitisation part, where the mixing of the empty neutrino hits and MinBias hits is done, the vertex smearing has no effect. What matters to get the correct physics is that the beam spot for the signal GEN-SIM and the original MinBias library GEN-SIM is consistent. So in my view the presence or absence of beamspot for the neutrino gun job is irrelevant (not needed but not harming either)

**Comment by fabiocos** [comment]
it would be useful to converge on this PR before 11_1_0_pre1 is built

**Comment by chayanit** [comment]
please test workflow 11861.97,20661.97

**Comment by chayanit** [comment]
please test workflow 20661.97

**Comment by chayanit** [comment]
@makortel , the only missing piece is to change number of event produced for premixing library to --relval 100000,100 and I think this PR is ready to go. Thank you.

**Comment by makortel** [comment]
@cmsbuild, please test workflow 11834.99,12634.99,13034.99,20634.99,20661.97

**Comment by makortel** [comment]
> the only missing piece is to change number of event produced for premixing library to --relval 100000,100 and I think this PR is ready to go.

Done in *a* way in the last commit. Based on the the preceding discussion my feeling is that the premixing treatment in the "upgrade matrix" could benefit from an overhaul (in a subsequent PR, and I can't commit to that), e.g. the `Kby(100,100)` would be less hidden if listed in `upgradeWorkflowComponents.py` among the others.

**Comment by chayanit** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade

**Comment by silviodonato** [comment]
code-checks

**Comment by silviodonato** [comment]
+1

**Pull request merged**
