### PR TITLE
[DD4hep] DD Filtered View: Add Debug Print, RegExp Speed Up and Clean Up

### PR DESCRIPTION
**Pull request by ianna**
#### PR description:

* Remove the need to an obscure `mergeSpecifics()` method because it does not merge anything, but filters the specifics registry. Note, the method is still accessible, but will be cleaned up in a later PR. 
* Instead of `mergeSpecifics()`, now `DDFilteredView` can be constructed from a `DDCompactView` and a `DDFilter`:
```c++
  const cms::DDFilter filter("OnlyForHcalSimNumbering", "HCAL");
  cms::DDFilteredView fv(cpv, filter);
```
* Use `regexp` as `keys` in a `Filter` to speed it up a bit
* <strike>Add a print filter method to allow easier debugging</strike>
* Remove methods that are not needed any more
* Use Hcal parameters builder as a user story study

@bsunanda - you may want to remove the `BenchmarkGrd` and disable the `MessageLogger` for the `Geometry`.

It's slightly slower to merge the filter registry:
```
< Benchmark 'DTGeometryESProducer Filter Registry' took 0.057576 millis
---
> Benchmark 'DTGeometryESProducer Filter Registry' took 0.052404 millis
```
but, it's ~8% faster to build the DT geometry:
```
< Benchmark 'DTGeometryESProducer' took 8082.02 millis
---
> Benchmark 'DTGeometryESProducer' took 8713.86 millis
``` 

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Review by ianna — COMMENTED** [review]
@bsunanda - time retrieving material names has been reduced from `70996.3 millis` to `49157.4 millis`
```
SpecPar names OnlyForHcalSimNumbering, HCAL:
hcal
Benchmark 'HcalSimParametersFromDD HCal materials OnlyForHcalSimNumbering, HCAL' took 70996.3 mill-is
```
due to the change in the selection from  `//.*HEScintillator.*` to  `//HEScintillator.*`:
```
hcal
   //HBS.*
   //HTS.*
   //HES.*
   //HVQF
   //HCal
   //HBS.*
   //HTS.*
   //.*HEScintillator.*
   //HVQX
   //VcalElecCathode
   //FibreBundle.*
   //VcalFibreBundleL.*
   //VcalFibreBundleR.*
   //CALO
   //MBAT
   //MBBT.*
   //VCAL
```
```
hcal
   //HBS.*
   //HTS.*
   //HES.*
   //HVQF
   //HCal
   //HBS.*
   //HTS.*
   //HEScintillator.*
   //HVQX
   //VcalElecCathode
   //FibreBundle.*
   //VcalFibreBundleL.*
   //VcalFibreBundleR.*
   //CALO
   //MBAT
   //MBBT.*
   //VCAL
Benchmark 'HcalSimParametersFromDD HCal materials OnlyForHcalSimNumbering, HCAL' took 48402.1 millis
```

The paths seem to be fine to use this type of selection:
```
world_volume/OCMS_1/CMSE_1/OQUA_1/VcalElectronics_1/VcalEleBox_1/VcalElecRBX_1/VcalElecPMT_1/VcalElecCathode_1
    world_volume/OCMS_1/CMSE_1/OQUA_1/FibreContainer_1/FibreBoxTrap_1/FibreBoxL_1/FibreBundle12_2
    world_volume/OCMS_1/CMSE_1/OQUA_1/VcalFibreBundleContainer_1/VcalFibreBundleSector_1/VcalFibreBundleHalfSectorL_1/VcalFibreBundleL11_2

    world_volume/OCMS_1/CMSE_1/VCAL_5002/HVQF_1/HVQX_18

```
Here is the summary before the changes:
```
TimeModule> 1 1 hpa HcalParametersAnalyzer 183.178
TimeModule> 1 1 p1 PathStatusInserter 0.00127196
TimeModule> 1 1 TriggerResults TriggerResultInserter 3.60012e-05
TimeEvent> 1 1 183.183
MemoryReport> Peak virtual size 536.102 Mbytes
 Key events increasing vsize: 
[0] run: 0 lumi: 0 event: 0  vsize = 0 deltaVsize = 0 rss = 0 delta = 0
[0] run: 0 lumi: 0 event: 0  vsize = 0 deltaVsize = 0 rss = 0 delta = 0
[1] run: 1 lumi: 1 event: 1  vsize = 536.102 deltaVsize = 0 rss = 96.9062 delta = 0
[0] run: 0 lumi: 0 event: 0  vsize = 0 deltaVsize = 0 rss = 0 delta = 0
[0] run: 0 lumi: 0 event: 0  vsize = 0 deltaVsize = 0 rss = 0 delta = 0
[0] run: 0 lumi: 0 event: 0  vsize = 0 deltaVsize = 0 rss = 0 delta = 0
[0] run: 0 lumi: 0 event: 0  vsize = 0 deltaVsize = 0 rss = 0 delta = 0
[1] run: 1 lumi: 1 event: 1  vsize = 536.102 deltaVsize = 0 rss = 96.9062 delta = 0
TimeReport> Time report complete in 186.166 seconds
 Time Summary: 
 - Min event:   183.183
 - Max event:   183.183
 - Avg event:   183.183
 - Total loop:  183.186
 - Total init:  2.9769
 - Total job:   186.166
 - EventSetup Lock:   6.19888e-06
 - EventSetup Get:   191.965
 Event Throughput: 0.00545894 ev/s
 CPU Summary: 
 - Total loop:  183.018
 - Total init:  1.43986
 - Total extra: 0
 - Total job:   184.461
 Processing Summary: 
 - Number of Events:  1
 - Number of Global Begin Lumi Calls:  1
 - Number of Global Begin Run Calls: 1
```
and after:
```
TimeModule> 1 1 hpa HcalParametersAnalyzer 140.614
TimeModule> 1 1 p1 PathStatusInserter 0.00015378
TimeModule> 1 1 TriggerResults TriggerResultInserter 2.40803e-05
TimeEvent> 1 1 140.614
MemoryReport> Peak virtual size 542.105 Mbytes
 Key events increasing vsize: 
[0] run: 0 lumi: 0 event: 0  vsize = 0 deltaVsize = 0 rss = 0 delta = 0
[0] run: 0 lumi: 0 event: 0  vsize = 0 deltaVsize = 0 rss = 0 delta = 0
[1] run: 1 lumi: 1 event: 1  vsize = 542.105 deltaVsize = 0 rss = 137.961 delta = 0
[0] run: 0 lumi: 0 event: 0  vsize = 0 deltaVsize = 0 rss = 0 delta = 0
[0] run: 0 lumi: 0 event: 0  vsize = 0 deltaVsize = 0 rss = 0 delta = 0
[0] run: 0 lumi: 0 event: 0  vsize = 0 deltaVsize = 0 rss = 0 delta = 0
[0] run: 0 lumi: 0 event: 0  vsize = 0 deltaVsize = 0 rss = 0 delta = 0
[1] run: 1 lumi: 1 event: 1  vsize = 542.105 deltaVsize = 0 rss = 137.961 delta = 0
TimeReport> Time report complete in 143.36 seconds
 Time Summary: 
 - Min event:   140.614
 - Max event:   140.614
 - Avg event:   140.614
 - Total loop:  140.616
 - Total init:  2.74258
 - Total job:   143.36
 - EventSetup Lock:   1.38283e-05
 - EventSetup Get:   149.858
 Event Throughput: 0.00711159 ev/s
 CPU Summary: 
 - Total loop:  140.488
 - Total init:  1.4459
 - Total extra: 0
 - Total job:   141.936
 Processing Summary: 
 - Number of Events:  1
 - Number of Global Begin Lumi Calls:  1
 - Number of Global Begin Run Calls: 1
```

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
This isn't an error, just a difference in diff, but I'll need to fix it anyway:
```diff
The output diff is 676:
0a1,3
> %MSG-i Geometry:  (NoModuleName) DTGeometryESProducer() 16-Mar-2020 18:14:01 CET pre-events
> Label '' IGNORING alignment labels ''.
> %MSG
1a5,9
> DDDetectorESProducer::Produce MUON
> Benchmark 'DTGeometryESProducer Filter Registry' took 0.042465 millis
> 
> Benchmark 'DTGeometryESProducer' took 8169.55 millis
> 
3679,3680c3687,3688
<     5 Geometry             -i (NoModuleName)   DTGeometryESProd      1*       1
<     6 Geometry             -i DTGeometryTest:t                       3*       3
---
>     5 Geometry             -i (NoModuleName)   DTGeometryESProd      1        1
>     6 Geometry             -i DTGeometryTest:t                       3        3
Failure using cmsRun /data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_1_X_2020-03-16-1100/src/Geometry/DTGeometryBuilder/test/python/testDTGeometry.py: status 255
status = 65280

---> test GeometryDTGeometryBuilderTestDriver had ERRORS
 

```

**Comment by ianna** [comment]
please test

**Comment by civanch** [comment]
+1

Carl, I think now PR is fine.

**Comment by silviodonato** [comment]
+1

**Pull request merged**
