### PR TITLE
Run2-hgx100 Change std::vector to std::unordered_set for storing valid detId's

### PR DESCRIPTION
**Pull request by bsunanda**
List of valid DetId's are now stored in a hashed table to improve performance

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by kpedro88** [comment]
@bsunanda can we see performance profiling to demonstrate the extent of the improvement?

**Comment by kpedro88** [comment]
There are comparison differences in many workflows. Is this expected? If so, what is the source?

**Comment by ianna** [comment]
@bsunanda - second @kpedro88's request: std::binary_search in a sorted std::vector can be faster. Please, also check that we can store an unorderd_set in DB.

**Comment by kpedro88** [comment]
with enough entries, hash search should be faster than binary search, but we still want to check that the hashing overhead doesn't exceed that speedup. Storing in DB is also a good question, I'm not sure of the status of hash tables in DB.

**Comment by ianna** [comment]
Here is a result of a [small test](https://github.com/lemire/Code-used-on-Daniel-Lemire-s-blog/blob/master/2016/09/15/stlsizeof.cpp) run in CMSSW_10_1_X_2018-02-22-2300 showing the memory usage by STL containers:
```
./stlsizeof 
Displaying memory usage in bytes.
Filling data structures with 1024 elements and reporting the per element memory usage.
memory usage per element of a vector<uint32_t> : 4
memory usage per element of a list<uint32_t> : 24
memory usage per element of a deque<uint32_t> : 4.64062
memory usage per element of an unordered_set<uint32_t> : 29.6016
memory usage per element of a set<uint32_t> : 40
Comments : 
This is an optimistic estimate: the overhead of the data structure and the allocations is ignored.
Because the per-value overhead might be fixed, the results might be less dramatic with larger elements, such as long strings.
```

**Comment by ianna** [comment]
@kpedro88 - Searching for the same 5000 random elements in the 500000-size containers with identical content, I'd conclude, that the hash search is not faster then the binary search. It can be worse:

```
Vector Binary Search: 0.00272952s
Unordered Set Find: 0.00384313s
```
or better:
```
Vector Binary Search: 0.00282022s
Unordered Set Find: 0.00143542s
```
I'm not convinced we need to move from vector to unordered_set given, that unordered_set has 7 times more memory overhead.

**Comment by perrotta** [comment]
@bsunanda (@ianna @kpedro88 ): did you reach any conclusion about the usefulness, or possible improvements for this PR? Are further checks needed, and if so which is their status of completion?
Furthermore: are the sources of the differences in the jenkins tests understood?

**Comment by drkovalskyi** [comment]
For changes that can affect many core algorithms we'd better have a very good reason to introduce them. Validation will take time and we still can miss some issues.

**Comment by perrotta** [comment]
@bsunanda please update about status and plans for this PR

**Comment by davidlange6** [comment]
Your PR is unmergeable. Please have a look and possibly rebase it.

**Comment by perrotta** [comment]
-1
This PR is unattended since almost three week, already: let remove it from the reco list
If and when some work on it will restart and new commits will be merged the "-1" will automatically get reset: however, if you are not interested in it any more please @bsunanda close it

**Comment by bsunanda** [comment]
@perrotta dont close it right now. i shall try to see how this can be resurrected

**Comment by bsunanda** [comment]
Close this PR in favour of #22673

**Pull request closed without merging**
