### PR TITLE
Update 2018 HI MC to latest GT and HLT menu

### PR DESCRIPTION
**Pull request by mandrenguyen**
- Update HI MC workflows with latest GT / vertex smearing set
- Also switch to HIon menu from placeholder
- Old heavy ions scenario is updated to use 2018 pp vertex smearing (was already using 2018 pp reco BS, but still with 2017 vertex smearing).

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by tocheng** [comment]
@cmsbuild please test

**Comment by fabiocos** [comment]
@mandrenguyen @lpernie @tocheng all the differences are concentrated in the HI workflows. The larger size of HLT histograms is likely motivated by the change in HLT menu, I do not see other explanations, do you agree?

If the outcome of the test is ok for you, could you please sign it?

@prebello @zhenhu FYI

**Comment by tocheng** [comment]
+1

**Comment by fabiocos** [comment]
@prebello @zhenhu do you agree with the proposed changes? If yes please sign, or comment

**Comment by prebello** [comment]
+1
@mandrenguyen will it affect somehow the report of HIN groups from 10-4-0-pre3 (see today's summary in PPD meeting the changes expected)  to 10-4-0-pre4 validation? 
Thank you

**Comment by mandrenguyen** [comment]
@prebello Small changes are expected to tracking/vertexing.  I don't imagine this should be problematic for validation.  I don't understand what happened between 10_4_0_pre3 and pre2 in the slides you point me.  I don't see that the beamspot changed between these releases, as is claimed in the slides.   Perhaps I'm missing something.

**Comment by fabiocos** [comment]
@kpedro88 this is not specific for upgrade, in case please sign it for reference

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Comment by kpedro88** [comment]
+upgrade

**Comment by prebello** [comment]
@mandrenguyen  there are few changes in relvals GENSIM inputs wrt the changes of this PR. 
We aim to recycle GENSIM from 10-4-0-pre3 that for HI uses new auto:phase1_2018_realistic_hi
Then baseDataSetRelease[1] used in noPU samples as PhotonJets, QCD and ZEEMM will adopt CMSSW_10_4_0_pre3-103X_upgrade2018_realistic_HI_v10-v1 
Is it compatible with your changes? That is, from now on the noPU samples mentioned above with be produced with auto:phase1_2018_realistic_hi instead of auto:phase1_2018_realistic ?

**Comment by mandrenguyen** [comment]
@prebello The GENSIM has to be performed with the driver option --beamspot RealisticPbPbCollision2018, i.e., should it should be regenerated after this PR.
In order for RECO to be compatible the phase1_2018_realistic_hi autoconditions should point to 103X_upgrade2018_realistic_HI_v11 (or higher). 
I hope that answers your question.

**Comment by prebello** [comment]
@mandrenguyen  maybe not. 
let me clarify: 

- MiniBias in **10-4-0-pre3**, Hydjet_Quenched_B12_5020GeV_cfi, was produced with auto:phase1_2018_realistic --beamspot Realistic25ns13TeVEarly2017Collision --era Run2_2018

- other noPU in **10-4-0-pre3**, PhotonJets, QCD and ZEEMM and HydjetQ_B12_5020GeV_2018_ppReco, were produced with auto:phase1_2018_realistic_hi --beamspot Realistic25ns13TeVEarly2018Collision --era Run2_2018

knowing, that in **pre3**, auto:phase1_2018_realistic is 103X_upgrade2018_realistic_v8 and auto:phase1_2018_realistic_hi is 103X_upgrade2018_realistic_HI_v10,  my question is:
 may we use these GENSIM files from 10-4-0-pre3 as inputs for the noPU and PU samples in 10-4-0-pre4? 

@nwickram

**Comment by mandrenguyen** [comment]
@prebello 
Both the v8 and v10 GTs are compatible with Realistic25ns13TeVEarly2018Collision
It would appear from your message that the MB needs to be regenerated with the 2018 vertex smearing.
Wfs 300-302 also have to use a GT that is compatible with the vertex smearing in the MB input dataset.

The lingering Realistic25ns13TeVEarly2017Collision is due to the fact that when pp workflows updated to 2018 vertex smearing, this was not done for the HI workflows.  For a while (until 10_3_0_pre5, I think) these workflows had an inconsistent vertex smearing & reco BS, unfortunately.

**Comment by prebello** [comment]
@mandrenguyen  
would the change below be the right one, or do you prefer to use gen2018 instead of gen2017?
steps['HydjetQ_B12_5020GeV_2018']=merge([{'-n':1,'--beamspot':'Realistic25ns13TeVEarly2018Collision'},hiDefaults2018,gen2017('Hydjet_Quenched_B12_5020GeV_cfi',U2000by1)])

**Pull request merged**
