### PR TITLE
Improve L1TMuonBarrelTrackProducer

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

- decreased substantially the number of per event allocations done
- made code changes to allow this module to now be a stream module
- improved memory handling

#### PR validation:

Ran step3 of workflow 12861.0 with improved ModuleAllocMonitor. Previously each event processed by the module needed 85k allocations. Now only the first event of each stream uses that much and all subsequent only use 19 allocations.

This should strictly be a technical change and should have no effect on the results.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
@makortel FYI

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
The reason the allocations dropped is the code now only calls `L1MuBMTFConfig::setDefaultsES` if the dependent record has changed.

**Comment by makortel** [comment]
type performance-improvements

**Comment by Dr15Jones** [comment]
I was able to reproduce the problem locally and then used `git bisect` to determine which commit introduced a problem. It was 

ee269797a7cf60165bab654f4fbaa23a975c7e9d is the first bad commit
```
Author: Christopher Jones <chrisdjones15@gmail.com>
Date:   Fri Nov 8 14:57:31 2024 -0600

    Make L1TMuonBarrelTrackProducer a stream module
    
    No more global variables are being used by code called by the
    producer.
    Switched to using edm::Event::emplace.
```

**Comment by Dr15Jones** [comment]
I found the problem. I had moved `dtbx_.clear()` from the beginning of `produce` to the end. If I move it back to the beginning everything works.

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
The latest commit does away with the 85k allocations needed for the first event of each stream.

**Comment by Dr15Jones** [comment]
please test

**Comment by perrotta** [comment]
> This should strictly be a technical change and should have no effect on the results.

There are quite several changes instead in the comparisons for the L1TEMU DQM plots, which need to be understood

**Comment by Dr15Jones** [comment]
@perrotta in the DQM comparisons plots, do you know which color is the baseline, i.e. red or blue?

**Comment by Dr15Jones** [comment]
@perrotta wrote
> There are quite several changes instead in the comparisons for the L1TEMU DQM plots, which need to be understood

Looking at step3 configuration for workflow 1330.0 I see two instances of L1TMuonBarrelTrackProducer

```python
simBmtfDigis = cms.EDProducer("L1TMuonBarrelTrackProducer",
    DTDigi_Source = cms.InputTag("simTwinMuxDigis"),
    DTDigi_Theta_Source = cms.InputTag("simTwinMuxDigis"),
    Debug = cms.untracked.int32(0)
)

valBmtfDigis = cms.EDProducer("L1TMuonBarrelTrackProducer",
    DTDigi_Source = cms.InputTag("bmtfDigis"),
    DTDigi_Theta_Source = cms.InputTag("bmtfDigis"),
    Debug = cms.untracked.int32(0)
)

```

but in the original code, there is a class `static` which olds the configuration options obtained from python
https://github.com/cms-sw/cmssw/blob/036340d2aebccd64fa1d5e77eae65fdd8bbb8489/L1Trigger/L1TMuonBarrel/src/L1MuBMTrackFinder.cc#L63-L67

so in the original code, one and ONLY ONE of the configuration would set `m_config` and the other configuration would be discarded. This means in the original code, even though `simBmtfDigis` and `valBmtfDigis` were SUPPOSED to be configured differently, they were actually both using the same `m_config` which happened to be the value for the module which HAPPENED to be created first by the framework.

So it looks to me like the original system was doing the wrong thing and the new code is actually doing what the configuration said it should do. That would definitely account for the differences seen.

This illustrates why globals (including class statics) are 'evil'.

**Comment by Dr15Jones** [comment]
Using the Tracer service, I see that `valBmtfDigis` is created before `simBmtfDigis` in the job.

I also ran the Tracer service with and without this PR and had it dump module dependencies.

Old Code:
```
  L1TMuonBarrelTrackProducer/'simBmtfDigis' consumes products from these modules:
    L1TRawToDigi/'bmtfDigis'
  L1TMuonBarrelTrackProducer/'valBmtfDigis' consumes products from these modules:
    L1TRawToDigi/'bmtfDigis'
```

new code
```
  L1TMuonBarrelTrackProducer/'simBmtfDigis' consumes products from these modules:
    L1TTwinMuxProducer/'simTwinMuxDigis'
  L1TMuonBarrelTrackProducer/'valBmtfDigis' consumes products from these modules:
    L1TRawToDigi/'bmtfDigis'
```
so it is clear that using the old code, the job is incorrectly configured (i.e. what was specified in the configuration file IS NOT what the application actually does).

**Comment by Dr15Jones** [comment]
Doing some further checks, I looked at step2 and see the only instance of the module is configured as
```python
simBmtfDigis cms.EDProducer("L1TMuonBarrelTrackProducer",
    DTDigi_Source = cms.InputTag("simTwinMuxDigis"),
    DTDigi_Theta_Source = cms.InputTag("simTwinMuxDigis"),
    Debug = cms.untracked.int32(0)
)
```
so the change I made will now make `simBmtfDigis` in step3 behave like the same named module in step2.

**Comment by Dr15Jones** [comment]
I took a look at how `valBmtfDigis` and `simBmtfDigis` are used in the job. Here are the module dependencies

```
  L1TBMTFAlgoSelector/'valBmtfAlgoSel' consumes products from these modules:
    L1TMuonBarrelKalmanTrackProducer/'valKBmtfDigis'
    L1TMuonBarrelTrackProducer/'valBmtfDigis'

  L1TStage2RegionalMuonCandComp/'l1tdeStage2Bmtf' consumes products from these modules:
    L1TRawToDigi/'bmtfDigis'
    L1TBMTFAlgoSelector/'valBmtfAlgoSel'
  L1TStage2RegionalMuonCandComp/'l1tdeStage2BmtfSecond' consumes products from these modules:
    L1TRawToDigi/'bmtfDigis'
    L1TBMTFAlgoSelector/'valBmtfAlgoSel'

  DQMRootOutputModule/'DQMoutput' consumes:
    DQMToken 'l1tdeStage2Bmtf' 'DQMGenerationRecoLumi' 'RECO', lumi
    DQMToken 'l1tdeStage2Bmtf' 'DQMGenerationRecoRun' 'RECO', run
    DQMToken 'l1tdeStage2BmtfSecond' 'DQMGenerationRecoLumi' 'RECO', lumi
    DQMToken 'l1tdeStage2BmtfSecond' 'DQMGenerationRecoRun' 'RECO', run

--------
  L1TMuonProducer/'simGmtStage2Digis' consumes products from these modules:
    L1TMuonBarrelTrackProducer/'simBmtfDigis'

  L1TMuonDQMOffline/'l1tMuonDQMOfflineEmu' consumes products from these modules:
    MuonProducer/'muons'
    L1TMuonProducer/'simGmtStage2Digis'
    RecoChargedRefCandidatePrimaryVertexSorter/'offlinePrimaryVertices'
    BeamSpotProducer/'offlineBeamSpot'

  DQMRootOutputModule/'DQMoutput' consumes:
    DQMToken 'l1tMuonDQMOfflineEmu' 'DQMGenerationRecoLumi' 'RECO', lumi
    DQMToken 'l1tMuonDQMOfflineEmu' 'DQMGenerationRecoRun' 'RECO', run
```
So it looks like the output of those two modules is ONLY used by modules which are only used to fill DQM histograms. Basically these are not used by modules doing the actual RECO steps.

**Comment by Dr15Jones** [comment]
So cmsDriver.py with the command `-s RAW2DIGI,L1Reco,RECO,RECOSIM,PAT,DQM:@standardDQMFakeHLT+@miniAODDQM` gets both `valBmtfDigis` and `simBmtfDigis` are in the job. If one just does `-s RAW2DIGI,L1Reco,RECO,RECOSIM,PAT` those modules are not in the configuration. 

So the modules are run just to fill DQM histograms, not to process the data being generated in this job.

**Comment by Dr15Jones** [comment]
Adding additional information, looking at the file (step2.root) used as input to step3 of the workflow, I see the following are in the file
```
[cdj@cmslpc247 1330.0_ZMM_13]$ edmDumpEventContent file:step2.root | grep Bmtf
BXVector<L1MuKBMTrack>                "simKBmtfDigis"             ""                "HLT"     
BXVector<l1t::RegionalMuonCand>       "simBmtfDigis"              "BMTF"            "HLT"     
BXVector<l1t::RegionalMuonCand>       "simKBmtfDigis"             "BMTF"            "HLT"     
BXVector<l1t::RegionalMuonCand>       "simBmtfDigis"              "UnsortedBMTF"    "HLT"     
vector<L1MuBMTrack>                   "simBmtfDigis"              "BMTF"            "HLT"     
vector<L1MuBMTrackSegEta>             "simBmtfDigis"              "BMTF"            "HLT"     
vector<L1MuBMTrackSegPhi>             "simBmtfDigis"              "BMTF"            "HLT"     
```
So it means step3 is trying to rerun a module (incorrectly with respect to the old code) which already has data stored in the file.

**Comment by Dr15Jones** [comment]
I switched on Debug output from the module and saw that the `building` stage was not occurring.

**Comment by Dr15Jones** [comment]
please test

**Comment by perrotta** [comment]
+1

**Comment by aloeliger** [comment]
+l1

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
