### PR TITLE
SiPM pulse shape fixes [81X]

### PR DESCRIPTION
**Pull request by kpedro88**
Backport of #16825

### CODE REVIEW

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by kpedro88** [comment]
@davidlange6 are POGs still being directed to 81X for 2017 physics studies? If so, this should go in; otherwise, I will close it.

**Comment by mmusich** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by kpedro88** [comment]
@davidlange6 can this go in?

**Comment by davidlange6** [comment]
not planning changes to 81x at this point..

**Comment by kpedro88** [comment]
if POGs are going to be looking at RECO output in 81X, this is needed.

**Comment by davidlange6** [comment]
then the hcal validation reports should be changed... I don't think we can hear that 810 is ok from validation and then hear that a change is really needed or its not useful.. hard to plan a production system that way. (and we already concluded to leave this for 90x on Dec 1..)

**Comment by kpedro88** [comment]
to me, the presence of arbitrary cutoffs in the pulse shapes is a bug, which should be fixed (and is fixed by this PR). This was not really visible at the level of HCAL validation, but does affect M2 performance. If POGs will be instructed not to expect optimal 2017 performance in 81X, then this isn't needed, but it is not clear to me that such a message has been conveyed.

**Comment by davidlange6** [comment]
I'm not that I disagree. - it sounds like a great topic for a future validation report to me, as we don't typically change digi/reco output physics wise. As we have 820 in a few days, there is a simple solution if pogs are interested in MC with the latest greatest (well, until the next latest greatest comes:) )

**Comment by abdoulline** [comment]
Then we need to convince PPD/POGs to turn to 820...

**Comment by mariadalfonso** [comment]
(my little 2cent)
Since the 8_0_1_pre16 the scale and resolution of the HCAL response are close to the run2 level.
I think the POG can give a pretty good feedback with this 8_1_0 already.

There are many little things here and there that we need to fix on the HCAL side and not all of the ones we know are in this PR. We need fix all of them but we can pile them up in another release (8_2_0 or 9_0_X_preX) so that the POG can do another intermediate large scale validation before the 90X is frozen for the 2017 MC.

**Comment by abdoulline** [comment]
We know that PPD is well informed to take its decision.
810 will be validated this week. 820 - no earlier than mid.January. This may (or may not) make the difference for POGs.

**Pull request closed without merging**
