### PR TITLE
[12.1.X] Update of mkFit as in 12_2_0 (backport of PR #35974)

### PR DESCRIPTION
**Pull request by mmasciov**
#### PR description:

Backport of PR #35974 to 12_1_X, together with cms-sw/cmsdist#7444.
The reason for the backport is to ensure that data reprocessing makes use of the same mkFit developments available in 12_2_X.

It requires cms-sw/cmsdist#7444.

#### PR validation:

Please refer to PR #35974.

### CODE REVIEW

**Comment by tvami** [comment]
@cmsbuild , please test with https://github.com/cms-sw/cmsdist/pull/7444

**Comment by tvami** [comment]
backport of https://github.com/cms-sw/cmssw/pull/35974

**Comment by tvami** [comment]
urgent
 * TkAlignment would like to test mkFit with a rereco (in 12_1_X) so we'd need this in asap

**Comment by jpata** [comment]
Do we need a formal confirmation that changing the reco results in 12_1_X is OK (that no sample submission has been done)?

**Comment by qliphy** [comment]
> Do we need a formal confirmation that changing the reco results in 12_1_X is OK (that no sample submission has been done)?

@rappoccio @cms-sw/pdmv-l2 may confirm on this.
Anyway we don't have sample production with 12_1_X, which was released last week.

**Comment by jpata** [comment]
>  Anyway we don't have sample production with 12_1_X, which was released last week.

Thank you, that's what I thought but I wasn't sure. Approving this just now.

**Comment by jpata** [comment]
+reconstruction
- exact backport of #35974 
- physics changes in tracks and downstream quantities observed and are NOT protected with a modifier (this should be fine, since there is no sample production with 12_1 yet)
- requires cms-sw/cmsdist#7444

**Comment by qliphy** [comment]
+1

**Pull request merged**
