### PR TITLE
HLT menu development for `12_4_X` (2/N) [`12_5_X`]

### PR DESCRIPTION
**Pull request by missirol**
#### PR description:

Development of HLT menus for `CMSSW_12_4_X`.

This is the PR for the `master` branch, which will then be backported to `12_4_X` (the latter is the release cycle currently used for HLT-menu development for Run 3).

Includes the integration of the following JIRA tickets.

  - [CMSHLT-2273](https://its.cern.ch/jira/browse/CMSHLT-2273): [BPH] Double-electron triggers for R(X)-type analyses _(partly integrated)_
  - [CMSHLT-2281](https://its.cern.ch/jira/browse/CMSHLT-2281): [HIG] Update of DijetVBF+2Tau trigger
  - [CMSHLT-2282](https://its.cern.ch/jira/browse/CMSHLT-2282): [EXO] PFMETNoMu trigger with HF cleaning + low-pT double-photon triggers _(partly integrated)_
  - [CMSHLT-2284](https://its.cern.ch/jira/browse/CMSHLT-2284): [HIG] Backup and control triggers for 2Tau+Jet trigger
  - [CMSHLT-2285](https://its.cern.ch/jira/browse/CMSHLT-2285): [HIG] Control triggers for VBF+2Tau trigger
  - [CMSHLT-2289](https://its.cern.ch/jira/browse/CMSHLT-2289): [TAU] Update of VBF+2Tau triggers
  - [CMSHLT-2291](https://its.cern.ch/jira/browse/CMSHLT-2291): [B2G] SingleJet and DiJet Triggers on AK8 jets with softdrop-mass cut
  - [CMSHLT-2306](https://its.cern.ch/jira/browse/CMSHLT-2306): [TOP] Update of DeepJet WP for HT+6Jet+1BTag trigger
  - [CMSHLT-2308](https://its.cern.ch/jira/browse/CMSHLT-2308): [BPH] Update of triggers for Tau->3Mu search _(amended with respect to [#38107](https://github.com/cms-sw/cmssw/pull/38107))_
  - [CMSHLT-2314](https://its.cern.ch/jira/browse/CMSHLT-2314): [JME] Low-pT single-photon trigger for jet-energy corrections
  - [CMSHLT-2316](https://its.cern.ch/jira/browse/CMSHLT-2316): [TSG] run Pixel DQM (CPU-vs-GPU) inside the HLT
  - [CMSHLT-2321](https://its.cern.ch/jira/browse/CMSHLT-2321): [EXO] Backup and monitoring triggers for displaced-dimuon searches
  - [CMSHLT-2324](https://its.cern.ch/jira/browse/CMSHLT-2324): [TSG] Naming: changed `AlCaLumiPixelCounts` to `AlCaLumiPixelsCounts`
  - [CMSHLT-2325](https://its.cern.ch/jira/browse/CMSHLT-2325): [TRK,AlCa,TSG] Update of `DQMOnlineBeamspot` EventContent and FEDSelector for TCDS
  - [CMSHLT-2330](https://its.cern.ch/jira/browse/CMSHLT-2330): [TAU,HIG] Naming: changed "`DeepTauIso`" label to "`DeepTau`"
  - [CMSHLT-2333](https://its.cern.ch/jira/browse/CMSHLT-2333): [EGM,HIG] Naming: removed "`NoPixelVeto`" label from Diphoton Paths _(partly integrated)_

#### PR validation:

TSG tests.

#### If this PR is a backport, please specify the original PR and why you need to backport that PR:

N/A

### CODE REVIEW

**Comment by missirol** [comment]
enable gpu

To better test the update of the DQM path, which only runs on GPU.

**Comment by missirol** [comment]
please test

**Comment by missirol** [comment]
The tests failed because the HLT menu now requires the L1T menu `L1Menu_Collisions2022_v1_0_1` (or higher), but that is not yet included in the MC and `_relval` GTs.

This PR (and its backport) will have to wait until the update of those GTs with the latest L1T menu, i.e. `L1Menu_Collisions2022_v1_1_0` (see [this comment](https://its.cern.ch/jira/browse/CMSLITDPG-980?focusedCommentId=4362104&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-4362104)). Alternatively, HLT needs to partly revert [CMSHLT-2284](https://its.cern.ch/jira/browse/CMSHLT-2284), which I would disfavour since the GTs have to be updated in any case.

@elfontan , what is the ETA to request the update of the GTs?

**Comment by missirol** [comment]
hold

See https://github.com/cms-sw/cmssw/pull/38241#issuecomment-1146572241.

**Comment by missirol** [comment]
Thanks, @elfontan !

**Comment by missirol** [comment]
unhold

L1T-v1_1_0 integrated in GTs in #38283.

**Comment by missirol** [comment]
please test with https://github.com/cms-sw/cmssw/pull/38283

**Comment by missirol** [comment]
+hlt

 - differences in PR-tests outputs are in line with the updates to the GRun HLT menu
 - some differences are not fully understood (by me), namely diffs in `HLT/SiStrip` appearing in wf `11634.911` (DD4hep from xml) and `11634.914` (DDD from DB), but not in `11634.0` (DD4hep from db); the updates in this PR in principle do not modify the outputs of the tracker local reconstruction (double-checked based on diffs in ConfDB); I wonder if part of this difference in SiStrip comes from the fact that part of the reconstruction runs "on demand", and several Paths have changed (but then, one would naively expect differences in wf `11634.0` too)
 - this PR should be merged only after #38283 (but for the same IB, possibly)

**Comment by missirol** [comment]
As I wrote in https://github.com/cms-sw/cmssw/pull/38241#issuecomment-1150473390, the differences in `HLT/SiStrip` for only certain Run-3 wfs leave me a bit puzzled, but I don't think that should stop the integration of these HLT updates.

**Comment by qliphy** [comment]
+1

**Pull request merged**
