### PR TITLE
Remove old FileInPath

### PR DESCRIPTION
**Pull request by Dr15Jones**
The class ::FileInPath in Utilities/General is a left-over from the transition to CMSSW. We are working towards removing it. All known uses of ::FileInPath can be replaced with edm::FileInPath which hides
which exact environment variables CMSSW uses to find data files.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by davidlange6** [comment]
please test

**Comment by perrozzi** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
