### PR TITLE
[HGCal] Scintillator support for RecHits calibration 

### PR DESCRIPTION
**Pull request by apsallid**
#### PR description:

The HGCalHitCalibration package is extensively used each time a new RelVal campaign is 
announced. With the PR #29165 under approval and the addition of a calibration factor for the scintillator region, we extend the code to produce also the relevant calibration plots for scintillator. 

#### PR validation:

We have tested the PR with the usual HGCal validation tools and produce some plots [1].   

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

This is not a backport. 

[1] http://apsallid.web.cern.ch/apsallid/HGCValid_testscint_Plots/

@rovere @bsunanda @cseez @pfs

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
@apsallid is it expected that hgcal_ele_EoP_CPene_scint_calib_fraction  and hgcal_photon_EoP_CPene_scint_calib_fraction   get no entries in the four Phase2 workflows?
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_11_1_X_2020-03-10-1100+49b2ef/35429/dqm-histo-comparison-summary.html

**Comment by apsallid** [comment]
@jfernan2 Yes, we have discussed that and for the time being it is fine. We will consider moving to tracksters in the near future.

**Comment by jfernan2** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
