### PR TITLE
Add stub of `DropBoxMetadata` payload inspector

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

This PR introduces a stub of  payload inspector for the `DropBoxMetadata`class, which is used to store the PCL upload configurations, in order to provide display and comparisons of the various PCL metadata JSON-based files. 
In order to do so, a change in the `CondFormat` is necessary, but as only an accessor is added, there's no schema evolution policy breakage. 
For the time being only the infrastructural changes are introduced, while the actual plotting will be addressed at a later time from @tlampen.
I introduce here also examples and unit tests in the `CondCore/PhysicsToolsPlugins/test` folder.
I profit of this PR to make a minor update to the `AlCaRecoTriggerBits_PayloadInspector` (commit https://github.com/mmusich/cmssw/commit/67617011ef71a64fb4fb7a4bfdeda7d5eb1503e4) and to fix a bug in (commit https://github.com/mmusich/cmssw/commit/0c13523b4a6f154a4b2709a6e0a5accde61f3c84)

#### PR validation:

Passes the introduced unit tests.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by tvami** [comment]
cc @tlampen

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
+1
 * tests pass
 * new unit test looks good https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-ac5825/20204/unitTests/src/CondCore/PhysicsToolsPlugins/test/test_DropBoxMetadata_PayloadInspector/testing.log
 * we can see more in PayloadInspector based on the IB

**Comment by tvami** [comment]
One question tho @mmusich what's your reasoning to put the DropBox metadata PI under  CondCore/PhysicsToolsPlugins ? It's not really a physics tool, right?

**Comment by mmusich** [comment]
> what's your reasoning to put the DropBox metadata PI under CondCore/PhysicsToolsPlugins ? It's not really a physics tool, right?

I agree,  but the record association is defined there: 

https://github.com/cms-sw/cmssw/blob/74e82562e4dc2f9b24ee7a2ebaf2ac6dcf7a3a09/CondCore/PhysicsToolsPlugins/src/plugin.cc#L30

**Comment by missirol** [comment]
To be pedantic, in the PR description

>  I introduce here also examples and unit tests in the `CondCore/HLTPlugins/test` folder.

I guess this should be `CondCore/PhysicsToolsPlugins/test` instead.

**Comment by missirol** [comment]
+hlt

**Comment by qliphy** [comment]
+1

**Pull request merged**
