### PR TITLE
Sort GenVisTau collection by their pT in GenVisTauProducer

### PR DESCRIPTION
**Pull request by ktht**
Discussion: https://github.com/cms-nanoAOD/cmssw/issues/118

### CODE REVIEW

**Comment by gpetruc** [comment]
please test

**Comment by gpetruc** [comment]
+1
this is only used in NanoAOD at the moment.
Also, previous behaviour was to return the objects in the original order they had in the gen particles, which is arbitrary, so nobody could have been relying on the older ordering.

**Comment by arizzi** [comment]
I confirm that the crash cannot be repoduced on IB + this PR

**Comment by fabiocos** [comment]
please test

I have seen once that issue but was not easily reproducible

**Comment by fabiocos** [comment]
+1

pure analysis code

**Pull request merged**
