### PR TITLE
[HGCAL] Move plugins out of SimDataFormats

### PR DESCRIPTION
**Pull request by lecriste**
#### PR description:

This PR moves the plugins recently added into `SimDataFormats/Associations` to `SimCalorimetry/HGCalAssociatorProducers` and uniform the naming of associators files. 
No changes are expected in the output.

#### PR validation:

`runTheMatrix -l limited`

### CODE REVIEW

**Comment by rovere** [comment]
@cmsbuild please test﻿

**Comment by lecriste** [comment]
@civanch can you please review this PR?

**Comment by civanch** [comment]
+1

**Comment by srimanob** [comment]
@lecriste 
I see that we have an error report in Static Check build log. Could you please have a look?
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-b01bf1/14946/summary.html

**Comment by srimanob** [comment]
Please test

**Comment by lecriste** [comment]
@srimanob the error in Static Check build is fixed now.

**Comment by lecriste** [comment]
@civanch can you please review again this PR? The only changes from previous signoff are for LogDebug.

**Comment by srimanob** [comment]
+Upgrade

This is considered to be technical PR, moving plugins from SimDataFormats to SimCalorimetry, and uniform the naming. PR test passed without change (as expected)

**Comment by civanch** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
