### PR TITLE
MC GTs updated with BPix fixes Fed Cabling, Sim geometry, HCALSiPM Fix

### PR DESCRIPTION
**Pull request by arunhep**
# Summary of changes in Global Tags

## Upgrade

   * **PhaseI 2017 cosmics peak scenario** : [92X_upgrade2017cosmics_realistic_peak_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/92X_upgrade2017cosmics_realistic_peak_v1) as [91X_upgrade2017cosmics_realistic_peak_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/91X_upgrade2017cosmics_realistic_peak_v5) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/92X_upgrade2017cosmics_realistic_peak_v1/91X_upgrade2017cosmics_realistic_peak_v5):
      * updated simulation geometry with BPix fixes : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2923.html
      * updated reco geometry with BPix Fixes : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2923.html
      * Fixed SiPixel Fed Cabling map https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2924.html
      * update of tracker alignment and APEs for 92X MC production https://indico.cern.ch/event/637519/contributions/2603391/
      * Fix in HCAL SiPM which only affects high energy rechits : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2960.html
      * update of ECAL spike killing for L1 trigger objects https://indico.cern.ch/event/637516/contributions/2593517/

   * **PhaseI 2017 cosmics scenario** : [92X_upgrade2017cosmics_realistic_deco_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/92X_upgrade2017cosmics_realistic_deco_v1) as [91X_upgrade2017cosmics_realistic_deco_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/91X_upgrade2017cosmics_realistic_deco_v5) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/92X_upgrade2017cosmics_realistic_deco_v1/91X_upgrade2017cosmics_realistic_deco_v5):
      * updated simulation geometry with BPix fixes : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2923.html
      * updated reco geometry with BPix Fixes : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2923.html
      * Fixed SiPixel Fed Cabling map https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2924.html
      * update of tracker alignment and APEs for 92X MC production https://indico.cern.ch/event/637519/contributions/2603391/
      * Fix in HCAL SiPM which only affects high energy rechits : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2960.html
      * update of ECAL spike killing for L1 trigger objects https://indico.cern.ch/event/637516/contributions/2593517/

   * **PhaseI 2017 design scenario** : [92X_upgrade2017_design_IdealBS_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/92X_upgrade2017_design_IdealBS_v1) as [91X_upgrade2017_design_IdealBS_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/91X_upgrade2017_design_IdealBS_v5) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/92X_upgrade2017_design_IdealBS_v1/91X_upgrade2017_design_IdealBS_v5):
      * updated simulation geometry with BPix fixes : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2923.html
      * updated reco geometry with BPix Fixes : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2923.html
      * Fixed SiPixel Fed Cabling map https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2924.html
      * Fix in HCAL SiPM which only affects high energy rechits : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2960.html
      * update of ECAL spike killing for L1 trigger objects https://indico.cern.ch/event/637516/contributions/2593517/

   * **PhaseI 2017 realistic scenario** : [92X_upgrade2017_realistic_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/92X_upgrade2017_realistic_v1) as [91X_upgrade2017_realistic_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/91X_upgrade2017_realistic_v5) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/92X_upgrade2017_realistic_v1/91X_upgrade2017_realistic_v5):
      * updated simulation geometry with BPix fixes : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2923.html
      * updated reco geometry with BPix Fixes : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2923.html
      * Fixed SiPixel Fed Cabling map https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2924.html
      * update of tracker alignment and APEs for 92X MC production https://indico.cern.ch/event/637519/contributions/2603391/
      * Fix in HCAL SiPM which only affects high energy rechits : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2960.html
      * update of ECAL spike killing for L1 trigger objects https://indico.cern.ch/event/637516/contributions/2593517/

   * **PhaseI 2018 cosmics scenario** : [92X_upgrade2018cosmics_realistic_deco_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/92X_upgrade2018cosmics_realistic_deco_v1) as [91X_upgrade2018cosmics_realistic_deco_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/91X_upgrade2018cosmics_realistic_deco_v5) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/92X_upgrade2018cosmics_realistic_deco_v1/91X_upgrade2018cosmics_realistic_deco_v5):
      * updated simulation geometry with BPix fixes : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2925.html
      * updated reco geometry with BPix Fixes : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2925.html
      * Fixed SiPixel Fed Cabling map https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2924.html
      * update of tracker alignment and APEs for 92X MC production https://indico.cern.ch/event/637519/contributions/2603391/
      * Fix in HCAL SiPM which only affects high energy rechits : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2960.html

   * **PhaseI 2018 design scenario** : [92X_upgrade2018_design_IdealBS_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/92X_upgrade2018_design_IdealBS_v1) as [91X_upgrade2018_design_IdealBS_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/91X_upgrade2018_design_IdealBS_v5) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/92X_upgrade2018_design_IdealBS_v1/91X_upgrade2018_design_IdealBS_v5):
      * updated simulation geometry with BPix fixes : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2925.html
      * updated reco geometry with BPix Fixes : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2925.html
      * Fixed SiPixel Fed Cabling map https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2924.html
      * Fix in HCAL SiPM which only affects high energy rechits : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2960.html

   * **PhaseI 2018 realistic scenario** : [92X_upgrade2018_realistic_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/92X_upgrade2018_realistic_v1) as [91X_upgrade2018_realistic_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/91X_upgrade2018_realistic_v5) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/92X_upgrade2018_realistic_v1/91X_upgrade2018_realistic_v5):
      * updated simulation geometry with BPix fixes : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2925.html
      * updated reco geometry with BPix Fixes : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2925.html
      * Fixed SiPixel Fed Cabling map https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2924.html
      * update of tracker alignment and APEs for 92X MC production https://indico.cern.ch/event/637519/contributions/2603391/
      * Fix in HCAL SiPM which only affects high energy rechits : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2960.html

### CODE REVIEW

**Comment by arunhep** [comment]
please test

**Comment by franzoni** [comment]
@fabozzi
this is the PR brining in the geometry changes  we'll need new GEN-SIM for
We've discussed this with Gurpeet this morning (sorry, I don't have his github account)

**Comment by franzoni** [comment]
@gurpreetsinghchahal

**Comment by davidlange6** [comment]
from an integration point of view it would be really really nice that the pixel changes were separated from all the rest..

**Comment by franzoni** [comment]
hello @davidlange6

in PhaseI 2017 realistic scenario  the only changes besides the pixel+TkGeometry+alignment package are:
+  configuration of ECAL L1 trigger primitives (reflecting a change in the spike killing algo as happened at P5 for 2017) and 
+ a fix for HCAL linearity, which ~unperceivable 
(see: https://hypernews.cern.ch/HyperNews/CMS/get/AUX/2017/05/30/10:31:08-62246-Nonlinearity_update_May29_2017_SA.pdf)  which affects only high energy rechits in HEP17.

By being calorimeter-only and only one RECO level,
can't we rely on a de-facto intrinsic factorization ?
It is of course technically possible reverting to pixel+TkGeometry+alignment . It'll take a few hours of work (since the changes are now all approved in queues) and we'll then need an additional PR,
while from yesterday we understood we would limit the steps to what we're doing here and a final one for PFcalibration + Beamstpot + RECO geom.

Please advise.

**Comment by franzoni** [comment]
please test

**Comment by davidlange6** [comment]
my main motivation is that the Ecal and Hcal changes could go in now and part of the routine tests, while the pixel changes will need to wait (~1 week) while the relval process completes

**Comment by franzoni** [comment]
+ the error on 50202.0 step3 is due to an unavailable input GEN-SIM file 

`      [d] XrdCl::File::Open(name='root://cms-xrd-global.cern.ch//store/relval/CMSSW_9_0_0_pre4/RelValMinBias_13/GEN-SIM/90X_mcRun2_asymptotic_v1-v1/10000/80A7D7A4-65EA-E611-9F23-0CC47A4D765E.root', flags=0x10, permissions=0660) => error '[ERROR] Server responded with an error: [3011] No servers are available to read the file.`

At any rate, the minBias used for pileup overlay are recycled from a geometry inconsistent with what we're testing here, hence no content loss. We'll need the GEN-SIM to be available for mixing once PdmV / @fabozzi and @GurpreetSinghChahal will have re-done with these GT's and modified the matrix input accordingly

+ also 1 of the addon checks has failed for missing input file

`            [a] XrdCl::File::Open(name='root://eoscms.cern.ch//eos/cms/store/user/cmsbuild/store/data/Run2016B/JetHT/RAW/v1/000/272/762/00000/C666CDE2-E013-E611-B15A-02163E011DBE.root', flags=0x10, permissions=0660) => error '[FATAL] Socket timeout' (errno=0, code=103)
      [b] Remote server already encountered a fatal error; no redirections were performed.
      [c] Input file root://eoscms.cern.ch//eos/cms/store/user/cmsbuild/store/data/Run2016B/JetHT/RAW/v1/000/272/762/00000/C666CDE2-E013-E611-B15A-02163E011DBE.root could not be opened.
Fallback Input file root://cms-xrd-global.cern.ch//store/data/Run2016B/JetHT/RAW/v1/000/272/762/00000/C666CDE2-E013-E611-B15A-02163E011DBE.root also could not be opened.
`

**Comment by arunhep** [comment]
hold

**Comment by davidlange6** [comment]
superseded by #19127

**Pull request closed without merging**
