### PR TITLE
fix failing unit tests after #38702 merge (Drop of geometry D49)

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

Title says it all.
Attempt to fix problem at https://github.com/cms-sw/cmssw/issues/38594#issuecomment-1261879490.

#### PR validation:

Run unit tests, which are not completely OK yet.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

N/A

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
please test

**Comment by srimanob** [comment]
+Upgrade

Fixes for unit test after phase-2 geometry clean up. No change is expected in comparison.

**Comment by mmusich** [comment]
type bug-fix

**Comment by mmusich** [comment]
@cms-sw/simulation-l2 @cms-sw/geometry-l2 please take a look.

**Comment by civanch** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
