### PR TITLE
CTPPS: new DataFormats related to TOTEM RP raw data and digi - backport of PR #13837

### PR DESCRIPTION
**Pull request by grzanka**
Backport of PR #13837 from CMSSW 81X

1st pull request out of 3 related to TOTEM RP raw-data unpacking and raw-to-digi conversion.
Validation config included in the 3rd pull request (EventFilter).

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
oops, need to have #14578 merged

**Comment by slava77** [comment]
@cmsbuild please test
IB with the DetId change in #14578 is now available and should be known to jenkins

**Comment by civanch** [comment]
+1

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/14579	8e50ef0
- backport of #13837 is done correctly: the same changes already integrated in 81X since a few weeks.
- jenkins tests pass 

@davidlange6 
this is needed for further PR integration

**Comment by davidlange6** [comment]
+1

**Pull request merged**
