### PR TITLE
Make sure variables are preserved in ReggeGribovPartonMCInterface

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

The compiler had warnings about possibly uninitialized values in the FORTRAN. Looking at the algorithm, the code expects the subroutine values to be preserved between calls. The portable way of doing that is to use the `save` keyword.

One of the previous uninitialized fixes incorrectly reset the value of an array each call rather than using `save` which is needed for the algorithm to properly work.

#### PR validation:

The code compiles. As the warning was in the aarch64 build and I do not have access to that machine, it is unclear if the warning will go away.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by makortel** [comment]
@cmsbuild, please test for el8_aarch64_gcc11

**Comment by Dr15Jones** [comment]
@cms-sw/generators-l2 ping

**Comment by Dr15Jones** [comment]
ping @cms-sw/generators-l2

**Comment by Dr15Jones** [comment]
ping @cms-sw/generators-l2

**Comment by Saptaparna** [comment]
+1

**Pull request merged**
