### PR TITLE
Add overloads used for copying conditions data from the host to the gpu

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Add `asyncCopy` overloads used for copying conditions data from the host to CUDA GPUs.

#### PR validation:

Validated as part of cms-patatrack#574

### CODE REVIEW

**Comment by fwyzard** [comment]
+1

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
@silviodonato @qliphy assuming the tasts pass, can we have this in pre10 ?
It would simplify the various Patatrack PRs currently under review.

**Comment by fwyzard** [comment]
please test with #32184

**Comment by silviodonato** [comment]
urgent

**Comment by qliphy** [comment]
+1

**Pull request merged**
