### PR TITLE
MTD simulation: premixing tuning

### PR DESCRIPTION
**Pull request by casarsa**
#### PR description:

The packing of the PU SimHits information in the premixing library has been tuned to fix a bias in the MTD time resolution when running with premixing. Basically, the width of the word, in which the time and energy information is stored, has been increased from 10 to 16 bits.

The figure below shows a comparison of the BTL resolution between the standard PU (WF 22234.0) and the premixed PU (WF 22234.99) for the current code and the proposed changes.

image

#### PR validation:

**PU library size:**

   current:
          PMTDSimAccumulator_mix_FTLBarrel_DIGI. 3.46034e+06 2.89781e+06
          PMTDSimAccumulator_mix_FTLEndcap_DIGI. 1.33435e+06 788234

   new:
          PMTDSimAccumulator_mix_FTLBarrel_DIGI. 4.66987e+06 2.82419e+06
          PMTDSimAccumulator_mix_FTLEndcap_DIGI. 1.57796e+06 902263

**Performance:**

The new code affects the steps 2 and 3, it has been tested with WF 22234.99 in CMSSW_11_1_X_2020-02-24-2300.

step 2

MemoryReport> Peak virtual size 4503.98 Mbytes
 Key events increasing vsize: 
[1] run: 1 lumi: 1 event: 1  vsize = 4119.94 deltaVsize = 0 rss = 2456.23 delta = 0
[2] run: 1 lumi: 1 event: 2  vsize = 4119.95 deltaVsize = 0.015625 rss = 2674.35 delta = 218.117
[4] run: 1 lumi: 1 event: 4  vsize = 4503.96 deltaVsize = 384.008 rss = 2787.09 delta = 112.746
[6] run: 1 lumi: 1 event: 6  vsize = 4503.98 deltaVsize = 0.0195312 rss = 2787.36 delta = 0.265625
[0] run: 0 lumi: 0 event: 0  vsize = 0 deltaVsize = 0 rss = 0 delta = 0
[8] run: 1 lumi: 1 event: 8  vsize = 4503.98 deltaVsize = 0 rss = 2860.68 delta = 73.3164
[7] run: 1 lumi: 1 event: 7  vsize = 4503.98 deltaVsize = 0 rss = 2831.74 delta = 44.3789
[6] run: 1 lumi: 1 event: 6  vsize = 4503.98 deltaVsize = 0.0195312 rss = 2787.36 delta = 0.265625
TimeReport> Time report complete in 844.182 seconds
 Time Summary: 
 - Min event:   61.3985
 - Max event:   116.356
 - Avg event:   74.3752
 - Total loop:  823.047
 - Total init:  21.0407
 - Total job:   844.182
 - EventSetup Lock:   7.72476e-05
 - EventSetup Get:   79.1781
 Event Throughput: 0.01215 ev/s
 CPU Summary: 
 - Total loop:  685.092
 - Total init:  9.92849
 - Total extra: 0
 - Total job:   695.103
 Processing Summary: 
 - Number of Events:  10
 - Number of Global Begin Lumi Calls:  1
 - Number of Global Begin Run Calls: 1

step 3

MemoryReport> Peak virtual size 4815.11 Mbytes
 Key events increasing vsize: 
[0] run: 0 lumi: 0 event: 0  vsize = 0 deltaVsize = 0 rss = 0 delta = 0
[1] run: 1 lumi: 1 event: 1  vsize = 4035.09 deltaVsize = 0 rss = 2976.07 delta = 0
[2] run: 1 lumi: 1 event: 2  vsize = 4431.09 deltaVsize = 396 rss = 3095.2 delta = 119.129
[3] run: 1 lumi: 1 event: 3  vsize = 4815.11 deltaVsize = 384.02 rss = 3062.52 delta = -32.6836
[0] run: 0 lumi: 0 event: 0  vsize = 0 deltaVsize = 0 rss = 0 delta = 0
[5] run: 1 lumi: 1 event: 5  vsize = 4815.11 deltaVsize = 0 rss = 3238.1 delta = 175.582
[4] run: 1 lumi: 1 event: 4  vsize = 4815.11 deltaVsize = 0 rss = 2982.25 delta = -80.2656
[3] run: 1 lumi: 1 event: 3  vsize = 4815.11 deltaVsize = 384.02 rss = 3062.52 delta = -32.6836
TimeReport> Time report complete in 655.984 seconds
 Time Summary: 
 - Min event:   40.0881
 - Max event:   145.567
 - Avg event:   58.967
 - Total loop:  636.154
 - Total init:  19.2085
 - Total job:   655.984
 - EventSetup Lock:   8.89301e-05
 - EventSetup Get:   78.7761
 Event Throughput: 0.0157195 ev/s
 CPU Summary: 
 - Total loop:  582.007
 - Total init:  12.7771
 - Total extra: 0
 - Total job:   594.932
 Processing Summary: 
 - Number of Events:  10
 - Number of Global Begin Lumi Calls:  1
 - Number of Global Begin Run Calls: 1

### CODE REVIEW

**Comment by kpedro88** [comment]
test settings
* workflows = 20661.97,20634.99,23434.1001

**Comment by kpedro88** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade

**Comment by silviodonato** [comment]
please test workflow 23234.1001, 23434.1001

**Comment by silviodonato** [comment]
abort

**Comment by silviodonato** [comment]
please test workflow 20661.97,20634.99,23434.1001,23434.1001
@kpedro88 I cannot find the results of the wf you launched (20661.97,20634.99,23434.1001)
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-de2d39/4873/runTheMatrix-results/

**Comment by silviodonato** [comment]
@casarsa , as you might know, we need to keep a compatibility between 11_0_0 and 11_1_X in order to re-run the reconstruction starting from the GEN-SIM-DIGI-RAW produced in 11_0_0_patch1 for the HLT TDR. 
Do you think this PR can break this compatibility? In other words, if we merge this PR and we read the MTD digi produced in  11_0_0_patch1, should we get meaningful values?

**Comment by silviodonato** [comment]
FYI: @fwyzard @thiago: you might be interested in this issue with MTD and premixing (not only for the possible compatibility issue)

**Comment by casarsa** [comment]
@silviodonato This PR changes the format of the premixing library. The MTD digis are not affected.

**Comment by fwyzard** [comment]
@silviodonato thanks for the heads up; according to @casarsa this should be fine.

Premixing will be good to have in the long run, unfortunately not for the HLT TDR !

**Comment by silviodonato** [comment]
+1

**Pull request merged**
