### PR TITLE
Add 4 Isolation variables for Photon to NanoAOD

### PR DESCRIPTION
**Pull request by Prasant1993**
#### PR description:

 This PR is to add 4 isolation variables for  Photon in NanoAOD . The Egamma photon  MVA-based ID for Run3 uses new isolation variables as input to the BDT training. These 4 isolation variables [**Photon_hcalPFClusterIso, Photon_ecalPFClusterIso, Photon_pfChargedIso, Photon_trkSumPtSolidConeDR04**] are currently not present in the photon table in NanoAOD. As Hgg analysis will be using the Egamma Run3 photon IDMVA, these 4 input variables for photons are required in NanoAoD to do a proper Data/MC validation of all the variables as input to the photon ID BDT training  and also it will help to evaluate a new training weight file in a NanoAOD test sample when it is available at some point later for better performance. 

#### PR validation:

runTheMatrix tests have been successfully run for the following workflows :

- runTheMatrix.py -l 12434.0
- runTheMatrix.py -l 2500.0

The size of these variables in the event in NanoAOD is calculated  according to a check with  the command
python3 PhysicsTools/NanoAOD/test/inspectNanoFile.py <my_file.root> -j test.json -s test_size_report.html -d tes_doc.html

MiniAoD File used to check these additions of floats in NanoAOD: /store/relval/CMSSW_13_2_0_pre2/RelValZEE_14/MINIAODSIM/PU_131X_mcRun3_2022_realistic_v3-v1/2590000/97db4599-13c4-4b15-b8d4-76c01e916784.root

Results of size/variable in event are Here : https://prrout.web.cern.ch/prrout/Eventsize_beforeafteradd_check/After_add_Presision8/test_size_report.html

Photon_trkSumPtSolidConeDR04 - 2.8 b/evt
Photon_pfChargedIso - 2.4 b/evt
Photon_hcalPFClusterIso - 3.1 b/evt
Photon_ecalPFClusterIso - 2.8 b/evt

#### Backport: 
As pointed out by @simonepigazzini in the PR #42247 we want these additions to only go into NANO v13,  i.e. the Fall/Winter production for 2022 and 2023. So no backport needed.

Tagging Hgg and Egm convenors here.
@lfinco @fcouderc as Hgg conveners
@swagata87 @a-kapoor @RSalvatico as EGamma conveners

### CODE REVIEW

**Comment by RSalvatico** [comment]
type egamma

**Comment by RSalvatico** [comment]
enable nano

**Comment by RSalvatico** [comment]
please test

**Comment by Prasant1993** [comment]
> Is there any chance we can prune the list of photon isolation variables from obsolete ones?

Hi @simonepigazzini, most of the isolation variables present are needed for photon IDMVA training and validation. I see some pfRelIso03 variables present for both in  Run2 and Run3. These variables are probably being used by some analyses or POG studies. I can't say with certainty if we have any obsolete ones that we can remove.

**Comment by a-kapoor** [comment]
> Is there any chance we can prune the list of photon isolation variables from obsolete ones?

@simonepigazzini We can possibly remove Run2 bases isolations that are only needed if one uses Run2 IDs in a Run3 analysis. EGM we will not support Run2 IDs for Run3, we have dedicated IDs now. I suppose it is not a problem if run2 Nano has a different set of variables compared to run3 Nano, for the time being?

**Comment by mariadalfonso** [comment]
> > Is there any chance we can prune the list of photon isolation variables from obsolete ones?
> 
> @simonepigazzini We can possibly remove Run2 based isolations that are only needed if one uses Run2 IDs in a Run3 analysis. EGM will not support Run2 IDs for Run3, we have dedicated IDs now. I suppose it is not a problem if run2 Nano has a different set of variables compared to run3 Nano, for the time being.

ideally you want to keep the branch in the same way, then filled optimally for Run2 and Run3; 
in this way will be trasparrent to the users; docs will have a string that explain to non expert for they are defined; 
we have done like this for the H/E that changed also between the Run2 and Run3.

**Comment by simonepigazzini** [comment]
I second @mariadalfonso comment. Whenever possible, we should retain the same name (with different content) for Run2 and Run3.  Otherwise we should implement the minimal set of Run3 variables and place the Run2 ones inside a function activated by the 106X modifier, to allow running on Run2 MINIAODs.

**Comment by a-kapoor** [comment]
@simonepigazzini We agree with your comment here. Indeed, the plan is to have the same name for the same variables, irrespective of Run3 or Run2. We will discuss this PR and the path forward in today's egm meeting and keep you posted.

However, is that a showstopper for this PR? Maybe we can make an additional PR to make the naming scheme common and only have the description in the doc string, but it would be great if this PR, which is for adding these 4 variables, is merged. Let us know what you think.

**Comment by simonepigazzini** [comment]
It would be good to have this ready for 13_3, which is still some weeks away. Is it impossible for you to implement this now?

**Comment by a-kapoor** [comment]
@simonepigazzini OK then. Let me discuss this internally. I will keep you posted.

**Comment by simonepigazzini** [comment]
please test

**Comment by simonepigazzini** [comment]
@Prasant1993  can you please backport this to 13_0?

**Comment by antoniovilela** [comment]
+1

**Comment by ZhenxuanZhang-Jensen** [comment]
Dear experts,

I hope this message finds you well and I am in the correct place to ask questions. For run2 analysis, I am curious to inquire about the most recent advancements in the treatment of boosted photon identification, particularly in cases where two photons are merged. Can this Egamma photon MVA-based ID for Run3 work well in the boosted case? Could you kindly provide information on any official approaches or treatments in this regard?

Thank you for your time and assistance.

Best regards,
Zhenxuan

**Comment by swagata87** [comment]
Hi @ZhenxuanZhang-Jensen 

Unfortunately this is not the correct place to ask such questions. 
You can ask in EGamma CMSTalk: https://cms-talk.web.cern.ch/c/physics/egm/144 ; everyone subscribed to that channel will receive your email.

Or if you want to send your email to a limited number of people (for example convenors only) then you can send emails to:

- Only EGM L2 convenors: cms-phys-conveners-EGM@cern.ch
- EGM L2+L3 convenors: cms-egamma-l3-convenors@cern.ch
- EGM HLT L3 + EGM L2 convenors: cms-trigger-EGM-conveners@cern.ch

**Pull request merged**
