### PR TITLE
2017 relvals: updates for 92X

### PR DESCRIPTION
**Pull request by fabozzi**
- update gensim recycling for 2017 wf to 9_2_1 (these gensim are compatible with pixel geometry fix)
- fixing generated events for JPsiMuMu_Pt-8 2017 wf 

Integration of new gensim recycling is needed to test changes in #19038 

@franzoni @arunhep

### CODE REVIEW

**Comment by fabozzi** [comment]
please test

**Comment by fabozzi** [comment]
+1

**Comment by davidlange6** [comment]
actually given the lack of #19038 i'm surprised that this PR does not break all the workflows... i'll try to make a combined PR to test things together.

**Comment by davidlange6** [comment]
ah - its because the gen-sim is not recycled in the PR tests. ok.

**Comment by davidlange6** [comment]
superseded by #19127

**Pull request closed without merging**
