### PR TITLE
Typo in CSCTightHalo2015Filter

### PR DESCRIPTION
**Pull request by lathomas**
1 character change: a boolean was assigned the wrong value.

### CODE REVIEW

**Comment by slava77** [comment]
@lathomas 
how do you test or validate the code?
The number of updates in the last few weeks was pretty large.
Do we have appropriate plots in DQM?

**Comment by lathomas** [comment]
@slava77  
It took several iterations to come up with a filter working properly because of various reasons. 
The main one is that simulations cannot really be trusted here (both for beam halos and physics events), which means data need to be scrutinized for tuning the filter. 

The performances of the filter were checked by the MET scanning group and finally validated by the MET conveners. 
You can see some plots here:  
https://lathomas.web.cern.ch/lathomas/BeamHalo/METFilterPerformace.pdf
Especially interesting is slide 2 which shows the efficiency of the various MET filters as a function of the MET for events in the Hotline dataset.. 
The idea is that the filter is supposed to kill many events in the high MET tail but should not kill any at low MET, where collisions events are expected to dominate over noise such as beam halos. The last update of the PR (before this one) aimed at decreasing the fake rate observed at low MET, which was found to be due to large activites in the calorimeter. 

To do these plots, the MET scanners use a special tagging mode (taggingMode_=true, i.e. events failing the filter are not discarded but just reported as having failed) which is why they were not sensitive to this typo...

**Comment by davidlange6** [comment]
@cmsbuild, please test

**Comment by cvuosalo** [comment]
+1

For #11967 70b36e15fe703aa8b3476372f7a70a51ee642c24

Bug fix for the CSCTightHalo2015Filter.

The code changes are satisfactory, and Jenkins [tests](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-11967/9235/summary.html) against baseline CMSSW_7_6_X_2015-10-26-2300 show no significant differences. Previous PRs related to this halo filter, like #11136, also showed no significant differences with Jenkins and extended tests.

**Pull request merged**
