### PR TITLE
Addition of WFs for postEE scenario [12_4_X]

### PR DESCRIPTION
**Pull request by sunilUIET**
#### PR description:

This PR is to add WFs (IDs 13600.0 to 13943.0) with GT: phase1_2022_realistic_postEE and HLT: relval2022_postEE for the release validation for the post-EE scenario.  The changes with this PR require merging of [#39019](https://github.com/cms-sw/cmssw/pull/39019) which includes post EE GT: phase1_2022_realistic_postEE. Newly added WFs already use the beam-spot as mentioned in #39019.

#### PR validation:

This PR is being tested with a few of the added WFs such as 13239, 13250, 13275.0

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

This PR is a backport #40151. The difference w.r.t. #40151 is that HLT keys are @relval2022_postEE in place of @relval2022.

@bbilin @kskovpen @francescobrivio @silviodonato

### CODE REVIEW

**Comment by srimanob** [comment]
Hi @sunilUIET 
I don't see the PR in master. We should have the PR in master first.

**Comment by Martin-Grunewald** [comment]
Well, ```'HLTmenu': '@relval2022_postEE',``` exists in 12_4_X only!
For 125X and 126X and 130X, you'd have to use ```'HLTmenu': '@relval2022',```

**Comment by sunilUIET** [comment]
Hi @srimanob 

   This PR is intended to use HLT :@relval2022_postEE for postEE relvals. This HLT key exists only in 12_4_X, therefore, we could not set it in 12_6_X for PR in master.

**Comment by Martin-Grunewald** [comment]
But you can make a postEE wf in master using the postEE GT just with the 'HLTmenu': '@relval2022'!

**Comment by sunilUIET** [comment]
Thanks Martin for the suggestion! A PR [40151](https://github.com/cms-sw/cmssw/pull/40151) is created for the master.

**Comment by srimanob** [comment]
Thanks @sunilUIET 
Could you please update the PR description that this PR is a backport of https://github.com/cms-sw/cmssw/pull/40151, and take note on difference. Thx.

**Comment by srimanob** [comment]
test parameters:

- workflow = 13634.0
- relvals_opt = --what cleanedupgrade,standard,highstats,pileup,generator,extendedgen,production,ged,machine,premix

**Comment by srimanob** [comment]
@cmsbuild please test

**Comment by sunilUIET** [comment]
Hi @srimanob 

We are getting different WF IDs for 12_6_X and 12_4_X. For TTbar process in 12_4_X use WF ID 13234 in place of 13634.

**Comment by srimanob** [comment]
@cmsbuild please abort

**Comment by srimanob** [comment]
> Hi @srimanob
> 
> We are getting different WF IDs for 12_6_X and 12_4_X. For TTbar process in 12_4_X use WF ID 13234 in place of 13634.

Thx. I made a typo. I would like to run 13234.0

**Comment by srimanob** [comment]
test parameters:

- workflow = 13234.0
- relvals_opt = --what cleanedupgrade,standard,highstats,pileup,generator,extendedgen,production,ged,machine,premix

**Comment by kpedro88** [comment]
@sunilUIET 
> We are getting different WF IDs for 12_6_X and 12_4_X. For TTbar process in 12_4_X use WF ID 13234 in place of 13634.

This is because 12_6_X also has the 2021FS workflows (from #38660): https://github.com/cms-sw/cmssw/blob/efd81992f5f8bd88279ddaa907a0e5364f210b0e/Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py#L27-L28

If you want to keep the workflow numbers consistent, you can the range used by 2021FS in 12_6_X to the 12_4_X `numWFConflict`: https://github.com/cms-sw/cmssw/blob/CMSSW_12_4_X/Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py#L79

**Comment by sunilUIET** [comment]
Thanks @kpedro88  for the suggestion! PR is updated with the fix.

**Comment by srimanob** [comment]
test parameters:

- workflow = 13634.0
- relvals_opt = --what cleanedupgrade,standard,highstats,pileup,generator,extendedgen,production,ged,machine,premix

**Comment by srimanob** [comment]
@cmsbuild please test

**Comment by srimanob** [comment]
test parameters:

- workflow = 13634.0
- relvals_opt = --what cleanedupgrade,standard,highstats,pileup,generator,extendedgen,production,ged,machine,premix
- pull_request = https://github.com/cms-sw/cmssw/pull/39019

**Comment by srimanob** [comment]
@cmsbuild please test

**Comment by srimanob** [comment]
@cmsbuild please test

**Comment by sunilUIET** [comment]
+pdmv

**Comment by srimanob** [comment]
+Upgrade

Backport PR. It is not a carbon copy of what is in master due to the change in HLT key and GT.

**Comment by rappoccio** [comment]
hold

* Needs to wait for signatures [here](https://github.com/cms-sw/cmssw/pull/39019), placing the hold so this doesn't accidentally go first.

**Comment by missirol** [comment]
Should this PR also be backported to `12_5_X` and `12_6_X` ?

**Comment by missirol** [comment]
unhold

#39019 was merged.

**Comment by missirol** [comment]
test parameters:
  - workflow = 13634.0
  - relvals_opt = --what cleanedupgrade,standard,highstats,pileup,generator,extendedgen,production,ged,machine,premix

**Comment by srimanob** [comment]
@perrotta @rappoccio 
Could you please consider to unhold and merge? Then I can rebase https://github.com/cms-sw/cmssw/pull/40256

Thanks.

**Comment by missirol** [comment]
@cms-sw/orp-l2 , kind ping about this PR.

https://github.com/cms-sw/cmssw/pull/40138#issuecomment-1336831264 and https://github.com/cms-sw/cmssw/pull/40138#issuecomment-1341383100 are still unanswered (https://github.com/cms-sw/cmssw/pull/40138#issuecomment-1336831264 is maybe a question to @cms-sw/pdmv-l2).

**Comment by sunilUIET** [comment]
> Should this PR also be backported to `12_5_X` and `12_6_X` ?

**Comment by sunilUIET** [comment]
@missirol, For 12_5_X backport will it be appropriate to set it with HLT keys @relval2022 and auto:phase1_2022_realistic_postEE? For 12_6_X backport #40279  is created

**Comment by missirol** [comment]
> For 12_5_X backport will it be appropriate to set it with HLT keys @relval2022 and auto:phase1_2022_realistic_postEE?

Yes.

> For 12_6_X backport https://github.com/cms-sw/cmssw/pull/40279 is created

Okay. If you don't mind, please add "[12_4_X]" (or "[12_5_X]" or "[12_6_X]") somewhere in  the title of each backport, so it's a bit easier to follow things.

**Comment by missirol** [comment]
backport of https://github.com/cms-sw/cmssw/pull/40151

**Comment by sunilUIET** [comment]
> > For 12_5_X backport will it be appropriate to set it with HLT keys @relval2022 and auto:phase1_2022_realistic_postEE?
> 
> Yes.
> 
> > For 12_6_X backport #40279 is created
> 
> Okay. If you don't mind, please add "[12_4_X]" (or "[12_5_X]" or "[12_6_X]") somewhere in the title of each backport, so it's a bit easier to follow things.

Thanks! #40280 is created for backport in 12_5_X

**Comment by perrotta** [comment]
unhold

**Comment by perrotta** [comment]
+1

**Pull request merged**
