### PR TITLE
New O2O for BeamSpot online run start

### PR DESCRIPTION
**Pull request by ggovi**
#### PR description:

Implementation of a new O2O workflow, required to initialise the BeamSpot tags with some adapted values for the HLT consumption at every new run.

This PR also contain a fix to correctly load the tag size in the Tag Info, in the context of the PopCon based workflow. 

#### PR validation:

A dedicated python cfg file has been used to test the new workflow against a local sqlite file.

### CODE REVIEW

**Comment by ggovi** [comment]
please test

**Comment by ggovi** [comment]
+1

**Comment by pohsun** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Comment by silviodonato** [comment]
@ggovi a O2O unit test is failing after having merged this PR (see #30049). I'm not sure if it is related to this PR.

**Pull request merged**
