### PR TITLE
GEM Reco Geometry Payload Writer Added to 2017 Scripts

### PR DESCRIPTION
**Pull request by ianna**
* Add GEM reco geometry payload writer to 2017 scripts

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by ianna** [comment]
@ggovi - please check and sign

**Comment by ianna** [comment]
@ggovi - ping

**Comment by ianna** [comment]
@ggovi - ping

**Comment by ggovi** [comment]
+1

**Comment by ianna** [comment]
@davidlange6 - just re-based without changes

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
please test

**Pull request merged**
