### PR TITLE
Update TSG tests from 2017 real data to 2018 real data

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
#### PR description:

Update TSG tests from 2017 real data to 2018 real data
Based on CMSSW_11_2_X_2020-07-22-2300

#### PR validation:

TSG tests

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
type bug-fix

**Comment by Martin-Grunewald** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
