### PR TITLE
Give more context in case of an ExternalGenerator error

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

- Added extra information to error output when there was a problem with the external application.

We are seeing infrequent errors in the IB and I was hoping to get a bit more context to help diagnose what is happening.

#### PR validation:

Please test.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by SiewYan** [comment]
@Dr15Jones , the test [*] suggested that:

Non-const variable 'std::string s_uniqueID' is static and might be thread-unsafe

not sure will it break during application..

[*] https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-6218d7/24394/llvm-analysis/report-f9d975.html#EndPath

**Comment by SiewYan** [comment]
The fail test is working [*], its looking ok for me. 

[*] https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-6218d7/24394/unitTests/src/GeneratorInterface/Core/test/FailingGeneratorFilterTest/testing.log

**Comment by SiewYan** [comment]
+1

**Comment by perrotta** [comment]
@Dr15Jones indeed I share the same doubt as @SiewYan : is the newly defined `s_uniqueID` thread safe?

**Comment by Dr15Jones** [comment]
@SiewYan @perrotta 
> Non-const variable 'std::string s_uniqueID' is static and might be thread-unsafe

Sorry for not getting back sooner. Within cmsRun, this would definitely be a concern. In this case, this is part of the external application and that application only uses 1 thread (since it is running an instance of a non-thread safe generator).  I've properly annotated the variable so the test should pass now.

**Comment by Dr15Jones** [comment]
please test

**Comment by perrotta** [comment]
+1

**Pull request merged**
