### PR TITLE
Simplify caching of CLHEP::HepRandomEngine in digitizers

### LINKED ISSUE #22712: Use of edm::RandomNumberGenerator in HGCDigiProducer
`HGCDigiProducer` (which is/can be a member variable of `MixingModule`, which itself is a `stream::EDProducer`) has a local "stream cache" for `CLHEP::HepRandomEngine`s.
https://github.com/cms-sw/cmssw/blob/301a35e206b6d2b8fe036ef003e7f00e772f3291/SimCalorimetry/HGCalSimProducers/plugins/HGCDigiProducer.cc#L47-L50
https://github.com/cms-sw/cmssw/blob/301a35e206b6d2b8fe036ef003e7f00e772f3291/SimCalorimetry/HGCalSimProducers/plugins/HGCDigiProducer.cc#L69-L81

A private e-mail thread with @Dr15Jones and @wddgit concludes that this construct should be safe, even if it is a bit weird.

The only benefit of this construct we could think of is being able to obtain the `CLHEP::HepRandomEngine` on O(1) time instead of O(log n) time.

I nevertheless decided to create an issue on this to understand why the cache is needed, and if we are happy with it or not.

### PR DESCRIPTION
**Pull request by makortel**
The explicit stream-based caching was introduced in #2392 at the time the the MixingModule was still a "one" module. Now that the MixingModule is a stream producer, there is no need to do the caching explicitly (=vectors indexed by the stream ID). A simple member variable is enough, and it is safe because framework runs always the same instance of a stream module in a given stream.

The caching is further simplified to always set the cache variable in `initializeEvent()` and set it back to `nullptr` in `finalizeEvent()` (to prevent the use of the engine outside event, e.g. begin/end lumi/run).

Resolves #22712.

Tested in CMSSW_10_1_0 (rebased on top of CMSSW_10_2_X_2018-04-10-2300), no changes expected.

@wddgit @Dr15Jones

### CODE REVIEW

**Comment by civanch** [comment]
@makortel , @Dr15Jones ,as I understand the logic of random numbers, in SIM step both for FullSim and FastSim the RandomNumberService is caled once per event to define random number generator for given event (Inside current thread). In FastSim this generator is distributed a a parameter of all methods to all called sub-classes. In the case of FullSim/Geant4 the random engine is set per event to as a CLHEP engine in the given thread. These both variants are transparent and seems to be  correct from the design point of view : method of definition of the generator is fully disconnected with FullSim and FastSim. The ovehead of access to the service per event is minimal.

At the DIGI/Mixing steps there is a sequence of producers, in each we need to access the service. There may be more overhead, however, to me having engine definded per event is indeed more safe than keeping  one engine stored after the first call. I afread that the method proposed by Matti may provide completely non-reproducible code, because event sequence in a thread is not reproducible.

**Comment by makortel** [comment]
@civanch Technically the current "StreamID-indexed vector" caching, and the caching done in this PR, are safe, and produce exactly the same results. (motivation for this PR being clearer code so that one does not have to wonder why there is a vector)

Would your preference be then to set the cache in each call to `initializeEvent()` (and reset to `nullptr` in finalizeEvent()`? I agree that would be clearer to a reader who would then not have to think/know about the exact details of random number service.

**Comment by kpedro88** [comment]
please test
(seems stuck)

**Comment by civanch** [comment]
@makortel , the rebase required for this PR

**Comment by makortel** [comment]
Rebased on top of CMSSW_10_2_X_2018-04-10-2300 and simplified the caching further along https://github.com/cms-sw/cmssw/pull/22874#issuecomment-379239758.

@civanch I dediced in the end to set the cache variable back to `nullptr` in `finalizeEvent()` to prevent its use outside of `Event` (i.e. in begin/end lumi/run).

**Comment by makortel** [comment]
@cmsbuild, please test with workflow 250202.0,250202.17,250202.18,250402.0

Let's include premixing workflows as well to demonstrate that they continue to work (as some parts of digitizer code is called from premixing)

**Comment by makortel** [comment]
@cmsbuild, please test workflow 250202.0,250202.17,250202.18,250402.0

Maybe some day I'll remember the syntax on the top of my head...

**Comment by civanch** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
