### PR TITLE
Backport of fixes on PPS geometry

### PR DESCRIPTION
**Pull request by diemort**
#### PR description:

This is a backport of #35380 to CMSSW_12_0_1.

This PR addresses a few minor corrections on the PPS geometry in the Pixel sensors and complies the material names in the reco geometry as stated in #34927. The position of the Silicon wafers has been move down to 250um w.r.t. the bottom foil and the envelopes with sensors ad flexible cables has been enlarged to avoid volume overlaps. Besides, the U shape of the Aluminum supports has been changed to a plain squared piece. A detailed list of the file changes and visualization of the new changes in the Pixel sensors is given in this [twiki](https://twiki.cern.ch/twiki/bin/view/CMS/PPSPixelGeometryFix1210pre2).

Includes updated on both DDD and dd4hep files and keeps the default dict2021Geometry.py for 12_0.

#### PR validation:

The new changes in the geometry have been validated with the full CMS geometry dump for visualization and overlap check with tolerance 0.01, plus direct and full simulation to confirm hits in both pixel and timing detectors. The position of the pixel sensors have been checked with direct simulation [here](https://twiki.cern.ch/twiki/bin/view/CMS/PPSPixelGeometryFix1210pre2#Comparisons_on_pixel_distance).

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

PR  #35380, needed to update PPS geometry for Run3.

All changes follow the Naming Rules for new XML files in geometry.
All workflow tests done.

FYI @fabferro @jan-kaspar

### CODE REVIEW

**Comment by diemort** [comment]
Remaining dict2021 files removed.

**Comment by bsunanda** [comment]
@diemort You should not have deleted those files - just substitute the ones from CMSSW_RELEASE_BASE area

**Comment by bsunanda** [comment]
Those files were there in the release base and let them stay as they were like dict2021

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by civanch** [comment]
urgent

**Comment by perrotta** [comment]
backport of #35380

**Comment by perrotta** [comment]
+1
- It adds to 12_0_X the xml files containing the updates for the PPS geometry, without modifying the default dict2021Geometry.py

**Pull request merged**
