### PR TITLE
add packages used by headers in CondFormats

### PR DESCRIPTION
**Pull request by davidlange6**
As noted in the modules IB, some package dependencies are missing from the BuildFile. This PR adds them. Changes are to CondFormats/BeamSpotObjects and CondFormats/RecoMuonObjects.

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
Not related to the changes in this PR .

**Comment by vgvassilev** [comment]
Ping

**Comment by davidlange6** [comment]
@smuzaffar - is this unit test expected to work in pr tests?

**Comment by smuzaffar** [comment]
No, there is no fix forthis unit test yet ( https://github.com/cms-sw/cmssw/issues/30049 )

**Comment by davidlange6** [comment]
Ok - thanks - then no point in redoing the PR tests..

On Jun 2, 2020, at 2:15 PM, Malik Shahzad Muzaffar <notifications@github.com<mailto:notifications@github.com>> wrote:



No, there is no fix forthis unit test yet ( #30049<https://github.com/cms-sw/cmssw/issues/30049> )

**Comment by davidlange6** [comment]
@silviodonato - perhaps this can be merged? There is no feedback from those responsible...

**Comment by silviodonato** [comment]
merge

**Pull request merged**
