### PR TITLE
Run2-sim24 Use a momentum distribution for particle gun

### PR DESCRIPTION
**Pull request by bsunanda**
Useful to validate isolated particle response

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@perrozzi @efeyazgan Can you approve this PR at your earliest? I need this for some G4 validation work

**Comment by perrozzi** [comment]
+1

**Comment by fabiocos** [comment]
@bsunanda @perrozzi @efeyazgan this code obviously does not run anywhere, as it is new. Was it minimally tested?

**Comment by bsunanda** [comment]
@fabiocos Yes I tested it and will use it for my next validation with 2017 low PU data

**Comment by fabiocos** [comment]
+1

**Pull request merged**
