### PR TITLE
GENSIM strings for 10_6_X

### PR DESCRIPTION
**Pull request by chayanit**
#### PR description:

Update GENSIM string for 10_6_X

#### PR validation:

All the validation and IB tests are done, referred to old PR https://github.com/cms-sw/cmssw/pull/26953
This PR is needed for #26875 to be merged on top. 

#### if this PR is a backport please specify the original PR:

Backport to 10_6_X

### CODE REVIEW

**Comment by fabiocos** [comment]
@chayanit thank you for following the request of a dedicated PR for the updated input samples. As I have discussed with @zhenhu at this point this PR is likely obsolete, as the 11_0_0_pre1 samples have been/are being produced. These new samples will be the starting point for the 11_0_0_pre2 validation, so having this PR in the release before the build is of little help. So I suggest to update this PR with the 11_0_0_pre1 GEN-SIM strings, ensure that all the needed samples are available, merge this into the IB, rebase on this #26875 and finalize the addition.

**Comment by chayanit** [comment]
@fabiocos I was not trying to argue anything and prepared new PR according to your request but it seems this will never ever end. Let me clarify something:
1.If i understood correctly, this will be a backport of 10-6-x GENSIM string. I know it will be obsoleted as soon as we produce new GENSIM for 11-0-0. But shouldn’t we have one GS string version kept for 10-6-x?
2. Given this GS string will be obsoleted, so why didn’t you guys allow my pLHE relvals #26875 to be merged. Now it seems not reasonable to hold my another PR with the reason of GS strings.
3. If you want to wait for update GS string in 11-0-0, there are plenty of missing relvals to be injected as same as we experienced DAS error in 10-6-0. This will take another week or so which means my pLHE relvals PR can’t be merged in time of 11-0-0-pre2.
4. I have been working on adding pLHE relvals PR for more than 4 months due to many errors (there was the first PR opened since 10-6-0-pre2). Things got very delayed already. I hope you can understand.

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
Summarizing the discussion with @zhenhu @chayanit : this PR is not needed for 11_0_0_pre2, where in any case the GEN-SIM input samples from pre1 will be used. Still, as those will take still a while to be fully completed, its integration may help to speed-up the integration of the long waiting #26875 without too large further delays.
We therefore agree to move forward on the short term with this PR, and have another update soon with pre1 samples as soon as available.

**Comment by kpedro88** [comment]
Indeed, it is unfortunate that it has taken so long for all the necessary samples to be produced in the 10_6_0 campaign. I think the agreement to include this interim update is the right approach at this point.

**Comment by kpedro88** [comment]
+upgrade

**Comment by fabiocos** [comment]
@zhenhu @prebello I believe that this PR is ok for you, if yes please sign it, I will merge it after announcing pre2

**Comment by zhenhu** [comment]
+1

**Comment by zhenhu** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
