### PR TITLE
Phase I Pixel Barrel Geometry and Material Budget changes for pre12

### PR DESCRIPTION
**Pull request by zucchett**
This pull request includes several updates for the Phase I Pixel Barrel geometry and material budget. The main changes are:
- added offset to the pixel barrel ladder positions (in r and phi) to match the pixel barrel blueprints
- updated geometry and material for cooling tubes
- signal and power cable material for BPix including Supply Tubes is updated according form the latest information
- adjusted material density for conn3 and conn4, pixel barrel service, and SupTubesCables solids

@veszpv and @schneiml may want to be informed or comment about this pull request.

### CODE REVIEW

**Comment by davidlange6** [comment]
please test




On 16 Sep 2016, at 18:23, cmsbuild <notifications@github.com<mailto:notifications@github.com>> wrote:


A new Pull Request was created by @zucchett<https://github.com/zucchett> (Alberto Zucchetta) for CMSSW_8_1_X.

It involves the following packages:

Geometry/TrackerCommonData

@civanch<https://github.com/civanch>, @Dr15Jones<https://github.com/Dr15Jones>, @ianna<https://github.com/ianna>, @mdhildreth<https://github.com/mdhildreth>, @cmsbuild<https://github.com/cmsbuild>, @davidlange6<https://github.com/davidlange6> can you please review it and eventually sign? Thanks.
@makortel<https://github.com/makortel>, @ghellwig<https://github.com/ghellwig>, @venturia<https://github.com/venturia>, @VinInn<https://github.com/VinInn>, @ghugo83<https://github.com/ghugo83> this is something you requested to watch as well.
@slava77<https://github.com/slava77>, @smuzaffar<https://github.com/smuzaffar> you are the release manager for this.

cms-bot commands are list here cms-sw/cmssw#13028<https://github.com/cms-sw/cmssw/issues/13028>

**Comment by schneiml** [comment]
Note that this PR, unlike #15805 ,  *does* change the standard 2017 geometry, so if pre12 has both of these PRs, we expect changes in the 100xx WFs. However, these changes are small and incremental, like the material budget updates we had in the past (additionally there are also small changes in the sensor geometry here), and unlike the complete rebuild of the FPIX.

Regarding the sensor positions, due to the fact that Alignment is turned on in the normal 2017 WFs, and that the DB geometry was most likely not updated,  the reco geometry will be slightly off which might degrade tracking. This might need fixing (maybe @mmusich ?).

This is mostly @cvuosalo ,  regarding the question in the other PR.

**Comment by ianna** [comment]
+1

**Comment by makortel** [comment]
> Note that this PR, unlike #15805 , does change the standard 2017 geometry, so if pre12 has both of these PRs, we expect changes in the 100xx WFs

Actually there should be no effect on 10[02]xx WFs, because those pick the geometry from DB instead of XML (the XML needs first to be converted/uploaded to DB, and then we'd need a new GT). The only piece I'm not sure is `Geometry/TrackerCommonData/plugins/DDPixBarLayerUpgradeAlgo.cc` (I don't know if it gets run only for XML geometry or also for DB geometry, and if the latter, what happens if the new "PitchFineTune" etc. do not exist).

But your comment answered to my question before I asked, that is, this PR affects both the "current phase1 geometry" (XMLs) and the "new FPix" of #15805.

**Comment by mmusich** [comment]
> Regarding the sensor positions, due to the fact that Alignment is turned on in the normal 2017 WFs, and that the DB geometry was most likely not updated, the reco geometry will be slightly off which might degrade tracking. This might need fixing (maybe @mmusich ?).


@schneiml the DB is _definitely_ not updated but since in the current setup everything (sim+reco geometry + alignment) is taken from DB the changes proposed here have no effect. 
No effect expected and no effect seen:
   * [TTBar 2017](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_8_1_X_2016-09-16-1100+15883/15919/10024.0_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2017_GenSimFull+DigiFull_2017+RecoFull_2017+HARVESTFull_2017/)
   * [TenMu 2017](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_8_1_X_2016-09-16-1100+15883/15919/10021.0_TenMuE_0_200+TenMuE_0_200_pythia8_2017_GenSimFull+DigiFull_2017+RecoFull_2017+HARVESTFull_2017/) 

@ianna when do we expect the updated version of the geometry as tags in DB?

**Comment by schneiml** [comment]
@mmusich Ah right, in the normal WFs *all* the geometries come from DB. I confused this with the new FPIX WFs, where the Geometry should be loaded from XML but Reco was still using the DB due to alignment (which is why we turned of alignment there).

So everything should be fine in the tests, but the tests are not actually useful... This might be a problem since we would like to have relvals of the geometry with only the barrel changes from this PR, before we merge the new FPIX into the main 2017 geometry for the release. 

Regarding DB changes, I guess this should happen with pre13 where we plan to assemble the final 2017 geometry from this barrel, the new FPIX and the material budget improvements not ready for pre12.

**Comment by mmusich** [comment]
> So everything should be fine in the tests, but the tests are not actually useful... This might be a problem since we would like to have relvals of the geometry with only the barrel changes from this PR, before we merge the new FPIX into the main 2017 geometry for the release. 

if you want to achieve that, then you should undo:
   * this: https://github.com/cms-sw/cmssw/pull/14748/commits/844c563f5daba9451c9ebc8afef77536e7b3351d 
   * this: https://github.com/cms-sw/cmssw/pull/14545/commits/16c3b2c35c9654ec888259b37b456d7cfabdccb3 

the second guarantees we don't screw up the alignment / geometry synchronization.
Remember that once the alignment is removed everything in the Tracker (including Strips!) is brought back to design positions (so, no misalignment scenario)

> Regarding DB changes, I guess this should happen with pre13 where we plan to assemble the final 2017 geometry from this barrel, the new FPIX and the material budget improvements not ready for pre12.

what prevents to have staggered approach and have the changes proposed in this PR first in DB to get XML and GT in synch, and then get all the rest (including the removal of special FPix stuff) in pre13?

**Comment by schneiml** [comment]
@mmusich thanks for the hints, I think we will not change anything for the release now, but this information is useful for us to produce the data ourselves.

Regarding DB, I have no idea what the usual conventions are and I see no problem with your proposal. It is just that I don't think it is necessary. Pre12 and pre13 will probably be fairly close.

**Comment by makortel** [comment]
In my opinion we should do the following (following the so-far-successful phase1 geometry validation strategy, and probably repeating what @mmusich was already after)

In pre12 have 2 (or 3) sets of 2017 RelVals:

1. With the geometry+alignment currently in GT (to validate all other changes from pre11->pre12).
2. With the geometry from this PR + the corresponding alignment, both in GT (as we have done earlier, personally I don't have strong feelings to validate this PR separately from #15805, but I don't mind if @schneiml+tracker prefers so). The GT does not need to be ready at the time pre12 is made, the time of RelVal submission is enough (although we want the RelVals soon after :)
3. With the geometry of #15805 (+this PR) from XML, alignment disabled (using the "NewFPix" workflows of #15805).

In pre13, the geometry of this PR + #15805 becomes the default, and we put it + the corresponding alignment to default autoCond GT of pre13. (This is important because there is the cluster shape calibration depends on the geometry, but the data is currently in a text file in a `data` directory and needs to be explicitly specified/customized in the configuration. I guess everybody agrees that the data should really be in the GT instead, but I fear that is unlikely to happen within the given schedule.)

**Comment by ianna** [comment]
@davidlange6 - are you going to merge this one as well?

**Comment by davidlange6** [comment]
+1

**Comment by schneiml** [comment]
@ianna , @davidlange6 : We have one more small change in https://github.com/cms-sw/cmssw/commit/18e06b7b38d5cca9e1a99fd7f0f62bb73c8882e9 . Should we update this PR/open a new one once this is merged/open a new one?

**Comment by ianna** [comment]
@schneiml - when a PR for this small change is expected?

**Comment by davidlange6** [comment]
@schneiml - make a new one....

**Comment by schneiml** [comment]
Once @zucchett pushes the button. I hope soon. If it is really urgentt, I guess anyone can do: https://github.com/cms-sw/cmssw/compare/CMSSW_8_1_X...zucchett:PixelGeomCoolTubes

The change is just adding the matter lost by shrinking the tubes by increasing their density.

**Comment by veszpv** [comment]
+1 for the proposal. Clearly, the number of scenarios are limited, but 
at least the factorization of BPix (smaller) changes from FPix (major) 
changes is advisable in order to assess the sensitivity of various 
POGs/PAGs to these changes to help estimating if further iterations are 
required. Who will officially request these validation scenarios?

**Comment by makortel** [comment]
@veszpv 
> Who will officially request these validation scenarios?

I can take care of that (as before for most of the 81X pre-releases). Obviously the plan needs some coordination with @ianna (for geometry tags that include this PR + https://github.com/cms-sw/cmssw/compare/CMSSW_8_1_X...zucchett:PixelGeomCoolTubes) and @mmusich (for GTs for PdmV to use).

**Comment by zucchett** [comment]
@schneiml @davidlange6 
The branch for the new PR is ready, and it can be done anytime if @veszpv agrees.

**Comment by veszpv** [comment]
Assuming that @schneiml has internally validated it from the Tracker point of view, it would be important for the new PR to be requested asap and merged still in pre12, as it would correct the material description of a volume that has been defined in this presently merged PR.

**Comment by zucchett** [comment]
The new PR #15930 has been opened.

**Comment by ianna** [comment]
@veszpv and @makortel - I'll prepare one set of new payloads with BPix for 2017 "realistic" and "design" GT queues and another set with BPix + FPix for 2017 "realistic" and "design" GT queues. Then Pixel nose will be added. If validation finds no problems, a default version can be updated.

Timescale for tags - Friday morning (as long as there is no other modifications planned).

@davidlange6 - earlier the Friday?

**Comment by ianna** [comment]
FYI, @veszpv and @makortel the tags of a current Extended2017 scenario + (all) BPix changes are in Prod DB:
```
XMLFILE_Geometry_81YV9_Extended2017_mc
TKRECO_Geometry_81YV9
TKExtra_Geometry_81YV9
TKParameters_Geometry_81YV9
```

**Comment by ianna** [comment]
@veszpv and @makortel the tags of a current Extended2017 scenario + (all) BPix changes + FPix changes are in Prod DB:
```
XMLFILE_Geometry_81YV10_Extended2017NewFPix_mc
TKRECO_Geometry_81YV10
TKExtra_Geometry_81YV10
TKParameters_Geometry_81YV10
```

@mmusich - FYI

**Comment by mmusich** [comment]
@ianna, thanks we'll to tune in the alignment accordingly before approving the tags in GT.

**Pull request merged**
