### PR TITLE
Phase2TrackerDigitizer: Activating Bias Rail Inefficiency

### PR DESCRIPTION
**Pull request by suchandradutta**
#### PR description:
Activating the  bias rails inefficiency for PS-p modules by default as it is the intrinsic to the sensor itself. SimHits are discarded (not considered for Digitization) when the trajectory is entirely inside the bias rail region. At the moment we consider also those SimHits for which the trajectory is partly outside (optimistic scenario with 'AND' condition for Entry/Exit points of SimHits) the bias rail region. 

**Note :** the code was already integrated before we are now switching it on through a configuration parameter. 

We expect to find  less digis in PSP modules due to this inefficiency
  
At the moment we are estimating the effect of this inefficiency in L1 tracking and it is not fully optimized. We might move to a more pessimistic scenario when we shall not consider the SimHits where the the trajectory is event partly inside the bias rail region ( 'OR' condition for Entry/Exit points of SimHits)

#### PR validation and some performance updates

- [Bi-weekly modelling, simulation and performance Meeting 11/11/2022](https://indico.cern.ch/event/1201190/contributions/5140217/attachments/2547129/4386516/Phase2Digitizer_BiasRailInEff_NoiseOccu_11112022.pdf)

- [Bi-weekly modelling, simulation and performance Meeting 11/11/2022](https://indico.cern.ch/event/1201190/contributions/5135986/attachments/2546226/4384765/LST_BiasRailBadStrips_TKPhase2Simulation_221111.pdf)

- [Bi-weekly modelling, simulation and performance Meeting 27/05/2022](https://indico.cern.ch/event/1160374/contributions/4894251/attachments/2452078/4201920/L1T_DQM_Update_5_27_22.pdf)
  
**Note :** all the above validation plots are presented with the pessimistic 'OR' option

@emiglior

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
please test
   * spurious failure

**Comment by civanch** [comment]
@suchandradutta , I agree with proposed implementation but am not sure if it is a correct approach to add any filter if the geometry the new tracker is not fully finalized. Usually such type of filter or mask are added to very final variant of simulation.

**Comment by emiglior** [comment]
Hi @civanch, as mentioned in the PR description, this inefficiency is kind of unavoidable. 
For the moment, we would prefer to keep the activation of the mask as an option to make the comparison with past results easier and to allow the development of mitigation strategies.

**Comment by civanch** [comment]
+1

**Comment by suchandradutta** [comment]
> > +Upgrade
> > Maybe `OR` and `AND` should be control via configuration in case of the need of comparison in future.
> > Changes are seen in all Phase-2 workflows as expected since the PR effects only Phase-2. Note to @cms-sw/pdmv-l2 on the validation when the release with this PR comes out.

Updated the code to be able to select between ### AND and ### OR options through configuration

**Comment by srimanob** [comment]
@suchandradutta 

No need to do at this point, if this PR is good. You can make it later, that is why I signed the PR with comment.

**Comment by mmusich** [comment]
Why was this PR closed?

**Comment by slava77** [comment]
> Why was this PR closed?

perhaps a wrong button pushed?

**Comment by mmusich** [comment]
@suchandradutta can you open it again?

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
please test
   * failure is spurious

**Comment by civanch** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

Re-sign

**Comment by rappoccio** [comment]
+1

**Pull request merged**
