### PR TITLE
clang check modernize-make-shared

### PR DESCRIPTION
**Pull request by davidlange6**
for comment about what clang-tidy does to CMSSW (and likely big and not mergeable - this is what clang-tidy check modernize-make-shared does on the tip of CMSSW_9_3_X as of a few days ago

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by slava77** [comment]
+1

even though the comparisons got stuck this looks OK [better than #19550 in the way that it compiles now]

**Comment by davidlange6** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
merge

**Pull request merged**
