### PR TITLE
[10_1_X] SiStrip Gains conditions DB manipulation tools

### PR DESCRIPTION
**Pull request by mmusich**
Greetings,
the aim of this PR is to introduce two plugins to manipulate SiStrip gain condition objects.
   * `SiStripApvGainRescaler` is designed to be used to rescale the values of the SiStrip G2 (a.k.a. particle) gains whenever there is an update of the SiStrip G1 (a.k.a. tickmark height) gains, before the cluster statistics for achieving a G2 measurement in-situ is available, according to the simple formula G2_new = (G1_old*G2_old)/G1_new. 
   * `SiStripChannelGainFromDBMiscalibrator` is designed to create mis-calibrations on top of an existing payload by smearing or setting an off scale, hierarchically, for the gain values up to the layer (wheel) level

I profit of this PR to fix a small inconsistency in the axis labeling of one of the payload inspector plots found when commissioning the tools.

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
please test

**Comment by ggovi** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
