### PR TITLE
Susy HLT DQM updates in 80x

### PR DESCRIPTION
**Pull request by olivito**
Adding DQM monitoring for SUSY lepton fake rate paths, including new C++ code.

Updating python configurations for HT, HT+MET, MET paths to consolidate python code and add newly proposed trigger paths.

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by olivito** [comment]
I've added to this PR to update also some python configuration names for HT paths as they've changed in the latest HLT menu. Could you please check again and trigger the automatic tests?

Thanks,
Dominick

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
