### PR TITLE
bug fix in clone constructor of GsfElectron

### PR DESCRIPTION
**Pull request by shervin86**
…sion correction without modifying the object

Conflicts:
	RecoEgamma/EgammaTools/src/SCEnergyCorrectorSemiParm.cc

Backport of #16752

### CODE REVIEW

**Comment by slava77** [comment]
@shervin86 please edit the title to keep it more descriptive of the content

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/16790 0a757c1
- backport of #16752 with changes serving analysis needs (no effect on centrally running workflows)
    - code changes are essentially the same as in #16752, apart for the added protection against HGCAL  (DetId::Forward), which is harmless in 80X.
- jenkins tests pass and show no relevant differences in monitored quantities

**Comment by davidlange6** [comment]
+1

**Pull request merged**
