### PR TITLE
Update HLT menu  (V4)

### PR DESCRIPTION
**Pull request by silviodonato**
This PR updates the HLT menus to the most updated version (V4).
HLT master table: /dev/CMSSW_8_0_0/HLT/V536
GRun table: /dev/CMSSW_8_0_0/GRun/V184

All working paths that were removed from GRun have been re-inserted, in order to have them available in the next MC production as requested by XEB.

81X version: #15875

### CODE REVIEW

**Comment by silviodonato** [comment]
please test

**Comment by fwyzard** [comment]
@silviodonato , we also need to "freeze" the new HLT menu to make it available for relvals and MC production.

Can you
  - update /frozen/2016/25ns15e33/v4.0/HLT to the latest GRun menu
  - include it in the python dumps, as  HLTrigger/Configuration/python/HLT_25ns15e33_v4_cff.py
?

**Comment by Martin-Grunewald** [comment]
please test

**Comment by silviodonato** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please do not interfere....

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
I have reverted the autoHLT.py changes, to get this PR passing tests and integrated.
Once the 80X GT updates are ready, we need another PR to switch to v4.

**Comment by mmusich** [comment]
>I have reverted the autoHLT.py changes, to get this PR passing tests and integrated.
Once the 80X GT updates are ready, we need another PR to switch to v4.

@Martin-Grunewald, in case you want to skip 1 PR and get everything merged together, the GTs with updated L1 menu are available, please cherry-pick from here: https://github.com/cms-sw/cmssw/pull/15899

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
Rebased to CMSSW_8_0_X_2016-09-18-0000

**Comment by Martin-Grunewald** [comment]
+1
@mmusich @cerminar 
please sign this one for AlCa as well.

**Comment by mmusich** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
