### PR TITLE
Run3-gex69 Move the macros to a separate directory and adopt for dd4hep

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Move the macros to a separate directory and adopt for dd4hep

#### PR validation:

Tested by running the codes using test script

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@smuzaffar Please suggest what is to be done

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by cvuosalo** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
