### PR TITLE
small fixes to JetMET trigger DQM plots

### PR DESCRIPTION
**Pull request by kirschen**
add HLT_CaloMET to search patterns, change eta/phi resolution plots to show the absolute difference instead of the (for spatial quantities ill-defined) 'relative resolution'

### CODE REVIEW

**Comment by kirschen** [comment]
74X-backport: #9885

**Comment by deguio** [comment]
hello @kirschen 
please submit to 76x as well. the same branch will merge.
thanks,
F.

**Comment by kirschen** [comment]
76 PR in #9892
@deguio: should future PRs first be filed for 76X and the backported to 74X/75X?

**Comment by deguio** [comment]
this is a minor fix from what I see. could go in parallel in all the release cycles.
ciao,
F.

**Comment by deguio** [comment]
+1

**Comment by deguio** [comment]
please test

**Comment by davidlange6** [comment]
+1

**Pull request merged**
