### PR TITLE
Split L1TMuonPhase2/Constants.h header and move Phase2L1GMT private headers in to plugins

### PR DESCRIPTION
**Pull request by smuzaffar**
`UBSAN` IBs are broken after the merge of https://github.com/cms-sw/cmssw/pull/37358 . The header https://github.com/cms-sw/cmssw/blob/master/DataFormats/L1TMuonPhase2/interface/Constants.h and compilation flags `-fsanitize=undefined`  (used for UBSAN Ibs) do not go well. Compiler takes hours to compile all compilation units where this header is included.

This PR breaks `DataFormats/L1TMuonPhase2/interface/Constants.h` header move the part of it's contents to `L1Trigger/Phase2L1GMT/plugins/Constants.h`. Also it disabled the `-fsanitize=undefined` flag for `Phase2L1TGMTProducer.cc` which actually include this header. 

This change should have no effects and it will fix the UBSAN builds

[a]
```
8730 00:00:02                                          \_ /cvmfs/cms-ib.cern.ch/nweek-02750/el8_amd64_gcc10/external/gmake/4.3-c4a96629837dd30c3fcd8f20831359f1/bin/gmake -r -f tmp/el8_amd64_gcc10/Makefile -j 10
 9486 00:00:00                                              \_ /bin/sh -c [ -d tmp/el8_amd64_gcc10/src/L1Trigger/Phase2L1GMT/plugins/Phase2L1GMTPlugins ] ||  /usr/bin/mkdir -p tmp/el8_amd64_gcc10/src/L1Trigger/Phase2L1GMT/plugins/Phase2L1GMTPlugins & ----  gcc10/src/L1Trigger/Phase2L1GMT/plugins/Phase2L1GMTPlugins/Phase2L1TGMTProducer.cc.d && exit 1))  
 9492 00:00:00                                                  \_ /bin/sh -c [ -d tmp/el8_amd64_gcc10/src/L1Trigger/Phase2L1GMT/plugins/Phase2L1GMTPlugins ] ||  /usr/bin/mkdir -p tmp/el8_amd64_gcc10/src/L1Trigger/Phase2L1GMT/plugins/Phase2L1GMTPlugi ----  gcc10/src/L1Trigger/Phase2L1GMT/plugins/Phase2L1GMTPlugins/Phase2L1TGMTProducer.cc.d && exit 1))  
 9494 00:00:00                                                      \_ /cvmfs/cms-ib.cern.ch/nweek-02750/el8_amd64_gcc10/external/gcc/10.3.0-84898dea653199466402e67d73657f10/bin/c++ -c -DGNU_GCC -D_GNU_SOURCE -DEIGEN_DONT_PARALLELIZE -DTBB_USE_GLIBCX ----  tmp/el8_amd64_gcc10/src/L1Trigger/Phase2L1GMT/plugins/Phase2L1GMTPlugins/Phase2L1TGMTProducer.cc.o
 9498 00:08:22                                                          \_ /cvmfs/cms-ib.cern.ch/nweek-02750/el8_amd64_gcc10/external/gcc/10.3.0-84898dea653199466402e67d73657f10/bin/../libexec/gcc/x86_64-redhat-linux-gnu/10.3.0/cc1plus -quiet -I /bui ----  fsanitize=pointer-overflow -fPIC --param=vect-max-version-for-alias-checks=50 -fabi-version=0 -o -
 9502 00:00:00                                                          \_ /cvmfs/cms-ib.cern.ch/nweek-02750/el8_amd64_gcc10/external/gcc/10.3.0-84898dea653199466402e67d73657f10/bin/../lib/gcc/x86_64-redhat-linux-gnu/10.3.0/../../../../x86_64-redhat- ----  tmp/el8_amd64_gcc10/src/L1Trigger/Phase2L1GMT/plugins/Phase2L1GMTPlugins/Phase2L1TGMTProducer.cc.o
```

### CODE REVIEW

**Comment by smuzaffar** [comment]
urgent

@cms-sw/l1-l2 , can you please review this ? This should allow us to start building `UBSAN` IBs again

**Comment by cecilecaillol** [comment]
+l1

**Comment by perrotta** [comment]
+1

**Comment by smuzaffar** [comment]
> Thank you @smuzaffar #37358 was merged already in 12_4: I think this needs to be backported also to 12_4 and 12_5, then: could you please also take care of it?

sure, I will open PRs for 12.4 and 12.5 too

**Pull request merged**
