### PR TITLE
Add HGCAL Hit calibration to Phase2 HLT.

### PR DESCRIPTION
**Pull request by rovere**
#### PR description:

Add the HGCAL hit calibration validation module to Phase 2 HLT validation. This will be able to catch, in future, issues similar to those reported in #44552 

#### PR validation:

Tested on a Phase2 workflow: plots are created and properly filled.

### CODE REVIEW

**Comment by rovere** [comment]
@cmsbuild please test

**Comment by rovere** [comment]
ping dqm

**Comment by rovere** [comment]
@srimanob we would need this PR merged and an equivalent backport to 14_0 to be sure HGCAL is correctly calibrated w/ the geometry to be used for 2024 Spring Phase2 production.

**Comment by mmusich** [comment]
@cms-sw/dqm-l2 please take a look.

**Comment by srimanob** [comment]
> @srimanob we would need this PR merged and an equivalent backport to 14_0 to be sure HGCAL is correctly calibrated w/ the geometry to be used for 2024 Spring Phase2 production.

Thanks @rovere 
So, if I understand correctly, this PR is not for production mode. But it is good for relvals we are going to produce in 14_0. Right?

**Comment by rovere** [comment]
Ciao @srimanob 
this PR is meant to monitor the HGCAL calibration in the Phase2 HLT Menu constantly. It is useful while testing PR and doing release validation with RelVals.

**Comment by tjavaid** [comment]
+1

- @rovere , do you want to make its backport PR for 14_0_X ?

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
