### PR TITLE
New fits and custom labels

### PR DESCRIPTION
**Pull request by dinardo**
I've changed fit function for certain plots and I've added custom labels to Y-axis of application status plot.

N.B. please let me know if I have to make a pull request also for other CMSSW versions !

### CODE REVIEW

**Comment by dmitrijus** [comment]
please test

**Comment by vanbesien** [comment]
Is there a corresponding 80X PR?

**Comment by vanbesien** [comment]
Corresponding 80X PR #14933

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
