### PR TITLE
Run3-gex30 Update the preshowering numbering scheme and a test code

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Update the preshowering numbering scheme and a test code

#### PR validation:

Tested using the cfg's in the test area

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
