### PR TITLE
TOB Connectors Overlap Bugfix

### PR DESCRIPTION
**Pull request by ianna**
* Remove TOBConnect56 (copy 1, 2, 5, and 6) intersection with TOBCFTube4
* Move TOBConnect56 (copy 3 and 4) out of TOBCFTube3

TOBConnect56 copies were moved along Z by +/- 2 mm. See attached screenshots (before and after the bugfix).
Sensitive volumes are not affected, nor new overlaps were introduced.

screenshot 2017-01-18 10 16 24
screenshot 2017-01-18 10 18 26

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by ianna** [comment]
@civanch and @veszpv - FYI

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by civanch** [comment]
@davidlange6 , do we need extra test of these xml fixes?

**Comment by davidlange6** [comment]
+1

**Pull request merged**
