### PR TITLE
move a few unit tests to python3

### PR DESCRIPTION
**Pull request by davidlange6**
identified by cmsdist pull request tests to still be using python2

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
please test


On Jul 13, 2021 7:16 PM, cmsbuild ***@***.***> wrote:

+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-34470/23921

  *   This PR adds an extra 20KB to repository

**Comment by srimanob** [comment]
+Upgrade

**Comment by perrotta** [comment]
+reconstruction
- move tests to python3 and replace a deprecated alias
- jenkins tests pass

**Comment by cvuosalo** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
