### PR TITLE
Add pythia8 config for T1tttt SMS

### PR DESCRIPTION
**Pull request by duanders**
Adding a Pythia8 config for the SUSY simplified model T1tttt.  The sample is pythia-only, with the needed SLHA file embedded in the config.  

This PR is part of a request to add T1tttt to the RelVal sequence, replacing the LM1 sample.  The request was presented here: https://indico.cern.ch/event/371138/contribution/8/material/slides/0.pdf

### CODE REVIEW

**Comment by bendavid** [comment]
Gen fragment is missing the UE tune piece (should use TuneCUETP8M1 as in the other fragments)

**Comment by duanders** [comment]
Added the CUEP8M1 settings.

**Comment by bendavid** [comment]
+1

**Comment by ktf** [comment]
Please test

**Comment by davidlange6** [comment]
+1

**Comment by franzoni** [comment]
hello @duanders
in light of what was discussed last week at the PPD, can you please back-port this gen fragment also to 74x ? While working on the matrix implications, I've realised it's not there.
@bendavid / roberto, I trust you were at the discussion during Dustin's talk, and know the rational.
Cheers. g

**Pull request merged**
