### PR TITLE
[Core] Fix unit tests for DBG IBs

### PR DESCRIPTION
**Pull request by smuzaffar**
- added new ref logs for DBG IB and updated u1, u19 and u33 scripts to use ref from DBG directory
- Removed unused tests cpp files

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test for CMSSW_13_1_DBG_X

**Comment by makortel** [comment]
+core

**Pull request merged**
