### PR TITLE
Topic fill description uncalib rechit

### PR DESCRIPTION
**Pull request by matteosan1**
Add fillDescriptions method to UncalibRechitProducer to allow easier HLT configuration handling.
In order to allow to keep the possibility to switch between "Weights" and Multifit in confDb I have also modified the structure of the PSet so that all the parameters not common to different algorithms are now inside the algoPSet PSet.

### CODE REVIEW

**Comment by cvuosalo** [comment]
please test

**Comment by cvuosalo** [comment]
Matrix tests underway for this PR.

**Comment by Martin-Grunewald** [comment]
HLT changes required here are in #7915 which also includes this PR.

**Comment by slava77** [comment]
-1

superseded by #7915

**Pull request closed without merging**
