### PR TITLE
[DD4hep] Fix last of preshower overlaps

### PR DESCRIPTION
**Pull request by cvuosalo**
The ECal preshower showed overlaps of about 1 mm between volumes `SFAbsNPbLOutAl` and `SFAbsNPbLinPb`. These volumes are created by the preshower algorithm. The algorithm was also creating a few unneeded solids and volumes.

It turns out that the `SFAbsNPbLOutAl` volume was being built incorrectly. With old DD, this volume is heavily nested, while with DD4hep it was missing some components. This PR  changes the code so that this volume gets the same structure in DD4hep as in the old DD. To add to the confusion, there were two different components both named `SFAbsNPbLOutAl`, and this PR changes the name of the volume to `SFAbsNPbLOutAlVol` to distinguish it from the like-named Tube.

The fix in this PR is complicated because the old DD code was using the capability of the old DD to create objects before they are fully defined. Old DD places the `SFAbsNPbLOutAl` volume before fully defining it and filling it with solids. That is not possible with DD4hep. To get around this problem, this PR adds a new loop where in the first iteration the necessary components are built and in the second iteration they are placed. The resulting code is even more complex than the original. It would be good to rewrite all this code to more clearly adapt it to the DD4hep paradigm where all components have to be defined before use, but we are trying to merge this PR for 12_0_0_pre2, and there is not time for such an extensive rewrite.

This PR removes uneeded solids and volumes and re-names a few components in cases where two different components had identical names.

#### PR validation:

The overlap checker, `SimG4Core/PrintGeomInfo/test/python/g4OverlapCheck_dd4hep_cfg.py`, was run before and after this change to show that the overlaps were fixed. Also, all solids were compared between old DD and DD4hep and found to be the same for the preshower (ignoring the new assemblies).

A backport is probably not necessary.

### CODE REVIEW

**Comment by cvuosalo** [comment]
urgent

**Comment by cvuosalo** [comment]
@qliphy We would like to get this PR into 12_0_0_pre2.

**Comment by cvuosalo** [comment]
@cmsbuild please test workflow 11634.911

**Comment by qliphy** [comment]
@cvuosalo thanks.  You mentioned "A backport is probably not necessary.",  but we may need 11_3_X for high statistics production, so why not back-porting to 11_3_X?

**Comment by cvuosalo** [comment]
@cmsbuild please test workflow 11634.911

**Comment by civanch** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
