### PR TITLE
Fix packed gen particle copy and move ctors

### PR DESCRIPTION
**Pull request by wmtan**
Pr #11706 created explicit copy and move constructors for pat::PackedGenParticle.
Unfortunately, the packed quantities were left out, so they were neither moved nor copied.
This PR fixes that, and also enhances the unit test so that this would have been caught.
This fixes the discrepancy recently seen in PackedGenParticle.

### CODE REVIEW

**Comment by wmtan** [comment]
@cmsbuild please test

**Comment by Dr15Jones** [comment]
What about the operator=?

**Comment by wmtan** [comment]
@Dr15Jones I suppose that both PackedGenParticle and PackedCandidate need copy and move assignment operators. I'll add them if they do not already exist. I can use the canonical form, using the copy and move constructors, I think.

**Comment by wmtan** [comment]
@Dr15Jones @davidlange6 I updated this PR both to fix the assignment operators and to use the
CMS_THREAD_SAFE macro to avoid the build warnings.

**Comment by wmtan** [comment]
@cmsbuild please test

**Comment by Dr15Jones** [comment]
@vadler, @monttj @davidlange6 this is critical for fixing a bug already in the release

**Pull request merged**
