### PR TITLE
Invert ALCAHARVDSIPIXELCALRUN1 so that an actually full DQM output file is produced

### PR DESCRIPTION
**Pull request by mmusich**
For some reason, if the `SiPixelQuality` AlCaHarvester is run for last in wf. 1001.0, the output DQM file is empty in PR tests. 
This in turn makes the comparison with baseline useless, as when the relmon command is run, a division by zero occurs, crashing the processs.
I am not sure why this happens, so I am cc'ing here @tocheng and @cerminar, just to make sure there is not something fishy lurking there.
At any rate, as we'd like to keep the relmon meaningful, to check the content of the `SiStripGains...`  Harvesters plots, I propose to invert the order, so that we actually get a full harvested DQM output to test.

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by kpedro88** [comment]
+1

**Comment by lpernie** [comment]
+1

**Comment by fabiocos** [comment]
please test

**Comment by mmusich** [comment]
@GurpreetSinghChahal, @prebello, @fabozzi any objection against this change?

**Comment by fabozzi** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
