### PR TITLE
Add contains function for Sequence, Path, EndPath, Task, and Schedule

### PR DESCRIPTION
**Pull request by wddgit**

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by slava77** [comment]
@davidlange6 
please check and perhaps merge this PR.
This is needed before we can integrate #20879

**Comment by Dr15Jones** [comment]
The unit test failures were not caused by this pull request. The PythonParameterSet error is a known existing problem with the test. The other failures are happening in the IBs.

**Comment by davidlange6** [comment]
merge

**Pull request merged**
