### PR TITLE
Phase2-gex118 Correct the scenarios for using the correct Producer for GEM Reconstruction Geometry

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Correct the scenarios for using the correct ESProducer for GEM Geometry

#### PR validation:

Use the runTheMatrix test workflows

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
+1

**Comment by srimanob** [comment]
Will this PR solve the issue of "GEM doesn’t pick up the DD4hep setup in GEMGeometryESModule ?" reported in
https://docs.google.com/document/d/1es0C2gH8KVt87iDoPRpdq8VVDjuEKtdd4kPjTsfW_RU/edit#heading=h.tr36dih79f57
on Phase-2 DD4hep test.

**Comment by bsunanda** [comment]
Yes

**Comment by srimanob** [comment]
+Upgrade

This PR is to fix the issue of Phase-2 DD4hep workflow that can't config DD4hep correctly for `GEMGeometryESModule` as reported in https://docs.google.com/document/d/1es0C2gH8KVt87iDoPRpdq8VVDjuEKtdd4kPjTsfW_RU/edit#heading=h.tr36dih79f57

PR test can't be used to test the fix as we have several issues for Phase-2 DD4hep workflow. The local test with this PR, i.e. using 
`cmsDriver.py step3 -s RAW2DIGI,L1Reco,RECO,RECOSIM --conditions auto:phase2_realistic_T21 --datatier GEN-SIM-RECO -n 10 --eventcontent FEVTDEBUGHLT --geometry DD4hepExtended2026D88 --era Phase2C17I13M9 --procModifiers dd4hep --python Reco_DD4hep_2026D88_dump.py --no_exec --filein file:step2.root --fileout file:step3.root --customise_command "process.DTGeometryESModule.applyAlignment = cms.bool(False) \n process.gemGeometry.fromDD4hep = cms.bool(True) \n process.gemGeometry.fromDDD = cms.bool(False)" --dump_python`
, the output workflow is correct for GEM,
```
process.gemGeometry = cms.ESProducer("GEMGeometryESModule",
    alignmentsLabel = cms.string(''),
    appendToDataLabel = cms.string(''),
    applyAlignment = cms.bool(False),
    fromDD4hep = cms.bool(True),
    fromDDD = cms.bool(False)
)
```
Thanks @bsunanda for the fix.
The doc is updated on this fix,
https://docs.google.com/document/d/1es0C2gH8KVt87iDoPRpdq8VVDjuEKtdd4kPjTsfW_RU/edit?usp=sharing

**Comment by srimanob** [comment]
type bug-fix

**Comment by perrotta** [comment]
+1

**Pull request merged**
