### PR TITLE
Fix warnings in EcnaAnalyzer

### PR DESCRIPTION
**Pull request by iarspider**
#### PR description:

Fix warnings in gcc12 builds ([log](https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/el8_aarch64_gcc12/CMSSW_13_2_X_2023-06-29-2300/CalibCalorimetry/EcalCorrelatedNoiseAnalysisModules)):

```
.../src/CalibCalorimetry/EcalCorrelatedNoiseAnalysisModules/src/EcnaAnalyzer.cc: In member function '__ct_base ':
  .../src/CalibCalorimetry/EcalCorrelatedNoiseAnalysisModules/src/EcnaAnalyzer.cc:218:52: warning: argument 1 value '18446744073709551615' exceeds maximum object size 9223372036854775807 [-Walloc-size-larger-than=]
   218 |   fDeeNumberString = new TString[fMaxFedUnitCounter];
      |                                                    ^
/data/cmsbld/jenkins_b/workspace/build-any-ib/w/el8_aarch64_gcc12/external/gcc/12.3.1-40d504be6370b5a30e3947a6e575ca28/include/c++/12.3.1/new:128:26: note: in a call to allocation function 'operator new []' declared here
  128 | _GLIBCXX_NODISCARD void* operator new[](std::size_t) _GLIBCXX_THROW (std::bad_alloc)
      |                          ^
  .../src/CalibCalorimetry/EcalCorrelatedNoiseAnalysisModules/src/EcnaAnalyzer.cc:326:50: warning: argument 1 value '18446744073709551615' exceeds maximum object size 9223372036854775807 [-Walloc-size-larger-than=]
   326 |   fDateFirst = new TString[fMaxTreatedStexCounter];
      |                                                  ^
/data/cmsbld/jenkins_b/workspace/build-any-ib/w/el8_aarch64_gcc12/external/gcc/12.3.1-40d504be6370b5a30e3947a6e575ca28/include/c++/12.3.1/new:128:26: note: in a call to allocation function 'operator new []' declared here
  128 | _GLIBCXX_NODISCARD void* operator new[](std::size_t) _GLIBCXX_THROW (std::bad_alloc)
      |                          ^
  .../src/CalibCalorimetry/EcalCorrelatedNoiseAnalysisModules/src/EcnaAnalyzer.cc:333:49: warning: argument 1 value '18446744073709551615' exceeds maximum object size 9223372036854775807 [-Walloc-size-larger-than=]
   333 |   fDateLast = new TString[fMaxTreatedStexCounter];
      |                                                 ^
/data/cmsbld/jenkins_b/workspace/build-any-ib/w/el8_aarch64_gcc12/external/gcc/12.3.1-40d504be6370b5a30e3947a6e575ca28/include/c++/12.3.1/new:128:26: note: in a call to allocation function 'operator new []' declared here
  128 | _GLIBCXX_NODISCARD void* operator new[](std::size_t) _GLIBCXX_THROW (std::bad_alloc)
      |                          ^
.../src/CalibCalorimetry/EcalCorrelatedNoiseAnalysisModules/src/EcnaAnalyzer.cc: In member function '__ct_comp ':
  .../src/CalibCalorimetry/EcalCorrelatedNoiseAnalysisModules/src/EcnaAnalyzer.cc:218:52: warning: argument 1 value '18446744073709551615' exceeds maximum object size 9223372036854775807 [-Walloc-size-larger-than=]
   218 |   fDeeNumberString = new TString[fMaxFedUnitCounter];
      |                                                    ^
/data/cmsbld/jenkins_b/workspace/build-any-ib/w/el8_aarch64_gcc12/external/gcc/12.3.1-40d504be6370b5a30e3947a6e575ca28/include/c++/12.3.1/new:128:26: note: in a call to allocation function 'operator new []' declared here
  128 | _GLIBCXX_NODISCARD void* operator new[](std::size_t) _GLIBCXX_THROW (std::bad_alloc)
      |                          ^
  .../src/CalibCalorimetry/EcalCorrelatedNoiseAnalysisModules/src/EcnaAnalyzer.cc:326:50: warning: argument 1 value '18446744073709551615' exceeds maximum object size 9223372036854775807 [-Walloc-size-larger-than=]
   326 |   fDateFirst = new TString[fMaxTreatedStexCounter];
      |                                                  ^
/data/cmsbld/jenkins_b/workspace/build-any-ib/w/el8_aarch64_gcc12/external/gcc/12.3.1-40d504be6370b5a30e3947a6e575ca28/include/c++/12.3.1/new:128:26: note: in a call to allocation function 'operator new []' declared here
  128 | _GLIBCXX_NODISCARD void* operator new[](std::size_t) _GLIBCXX_THROW (std::bad_alloc)
      |                          ^
  .../src/CalibCalorimetry/EcalCorrelatedNoiseAnalysisModules/src/EcnaAnalyzer.cc:333:49: warning: argument 1 value '18446744073709551615' exceeds maximum object size 9223372036854775807 [-Walloc-size-larger-than=]
   333 |   fDateLast = new TString[fMaxTreatedStexCounter];
      |                                                 ^
/data/cmsbld/jenkins_b/workspace/build-any-ib/w/el8_aarch64_gcc12/external/gcc/12.3.1-40d504be6370b5a30e3947a6e575ca28/include/c++/12.3.1/new:128:26: note: in a call to allocation function 'operator new []' declared here
  128 | _GLIBCXX_NODISCARD void* operator new[](std::size_t) _GLIBCXX_THROW (std::bad_alloc)
      |                          ^
```

#### PR validation:

Code compiles

### CODE REVIEW

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
Notice: as far as I can tell, `fDeeFromFedTcc` is not used anywhere in the code and can be freely removed.

**Comment by francescobrivio** [comment]
maybe we can get an opinion from @cms-sw/ecal-dpg-l2 ?

**Comment by francescobrivio** [comment]
+1

 - PR according to description
 - tests are clean
 - blessed by ECAL DPG (see https://github.com/cms-sw/cmssw/pull/42170#issuecomment-1621986331)

**Comment by perrotta** [comment]
@iarspider @francescobrivio since it was blessed by ECAL DPG, I would remove all references to `fDeeFromFedTcc` , rather than letting them commented out

**Comment by iarspider** [comment]
please test

**Comment by francescobrivio** [comment]
+1

 - signing already since the last commit is simple removal of commented lines

**Comment by perrotta** [comment]
+1

**Pull request merged**
