### PR TITLE
[11_1_X] adding MultiplicityValueProducer* plugins (HLT Phase-2 TDR)

### PR DESCRIPTION
**Pull request by missirol**
#### PR description:

Backport of https://github.com/cms-sw/cmssw/pull/33204 (description of the latter copied below):

-------

During tests on the HLT Phase-2 menu (which is being integrated in https://github.com/cms-sw/cmssw/pull/32903), @SWuchterl (BTV) noticed that one plugin was still coming from a user-pkg (so, not from CMSSW directly). This PR aims to integrate this in the release.

The plugin itself is rather simple: it's a (templated) producer that adds to the event the multiplicity value of a given EDM collection.

It is used in the current Phase-2 HLT to get the multiplicity of pixel clusters; that value, in turn, is used as PU-proxy input to the PUPPI producer in Phase-2 HLT studies (see https://github.com/cms-sw/cmssw/pull/32341 for the relevant update to PUPPI).

At the moment, the only application of this is the HLT Phase-2 menu in the context of Jets/MET reconstruction, so I'm tentatively adding this plugin to `HLTrigger/JetMET`.

Attn: @fwyzard @trtomei

-------

#### PR validation:

Tested with user workflows for Phase-2 HLT TDR studies.

#### If this PR is a backport, please specify the original PR and why you need to backport that PR:

Backport of https://github.com/cms-sw/cmssw/pull/33204

### CODE REVIEW

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
+1

**Comment by Martin-Grunewald** [comment]
-1

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Pull request merged**
