### PR TITLE
[13_0_X] APE measurement tool: Resolved python3 compatibility issues, added unit test functionality, removed dependency on other package: Backport of #42012

### PR DESCRIPTION
**Pull request by mteroerd**
#### PR description:

autoSubmitter.py did not run on recent CMSSW releases since ROOT does not work with python2, while python3 execution would throw an error from using the output of "check_output" without decode().

Some additional small changes to remove redundancies were applied, as well as a change to the disk space requested by condor jobs (the target input file size is 350MB, but files can be larger than 400MB anyway) and some formatting changes. Also, the method names now adhere to the CMS naming rules. 

Additionally, added unit test functionality and removed the need to add the package Alignment/TrackerAlignment whenever a measurement is to be performed.

#### PR validation:

I executed the program with an example configuration and made sure it ran as expected. All changes should be transparent.
Also, a unit test can now be run to validate the PR.

#### Backport

Backport of #42012
Slight change since unit tests use a different working folder in this CMSSW release.

### CODE REVIEW

**Comment by mmusich** [comment]
type bug-fix

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
backport of https://github.com/cms-sw/cmssw/pull/42085

**Comment by mmusich** [comment]
just a kind ping to @cms-sw/alca-l2 concerning this and the other [backport](https://github.com/cms-sw/cmssw/pull/42086)

**Comment by francescobrivio** [comment]
Thanks for the ping!
The master PR also contains the deletion of:
 - Alignment/APEEstimation/test/testApeestimatorSummary_cfg.py
 - Alignment/APEEstimation/test/testApeestimator_cfg.py
 
Should that be backported here (and in the 13_1_X backport) as well?

**Comment by mteroerd** [comment]
Hi Francesco, 
I forgot to include their removal in the backports. However,  this will not create any problems related to any functionality. In fact,  I removed them because they are unused code. So from my side, I do not think they have to be removed here.

**Comment by francescobrivio** [comment]
+1

 - tests ok and new unitTest is successful
 - left for a possible followup PR (i.e. not critical): https://github.com/cms-sw/cmssw/pull/42085#issuecomment-1610906226

**Comment by perrotta** [comment]
+1

**Pull request merged**
