### PR TITLE
Store association maps

### PR DESCRIPTION
**Pull request by lecriste**
#### PR description:

This PR introduces two products which can be consumed by several analyzers, removing code duplication. The first replacement is made for the `HGVHistoProducerAlgo::fill_generic_cluster_histos` method, no changes are expected in the output.

#### PR validation:

`runTheMatrix -l limited`

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by lecriste** [comment]
@jfernan2 can you please trigger the tests again?

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by lecriste** [comment]
@civanch can you please review this PR (assuming you are the `simulation` signer)?

**Comment by civanch** [comment]
+1

**Comment by civanch** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
