### PR TITLE
NanoAOD update (94X version, same as #21095)

### PR DESCRIPTION
**Pull request by arizzi**
Add several variables in NanoAOD.
Read from miniaod some of the new variables computed in pre3 (e.g. for jet substructures)
Move cmsDriver input files to pre3
Includes DQM for NanoAOD

Same as  #21095 (just merged)
@gpetruc @peruzzim

### CODE REVIEW

**Comment by kpedro88** [comment]
backport of #21095

**Comment by kpedro88** [comment]
please test

**Comment by perrotta** [comment]
+1
- Identical to #21095, now merged in the master

**Comment by kpedro88** [comment]
+1

**Comment by fabozzi** [comment]
+1

**Comment by slava77** [comment]
@davidlange6 @dmitrijus 
are we just waiting for a DQM signature or was it not included in 940patch1 for some other reason?

**Comment by davidlange6** [comment]
the data format changes would have triggered a 9_4_1 instead. That was more than I wanted to worry about over the weekend.

**Comment by arizzi** [comment]
@davidlange6 anything holding this?

**Comment by arizzi** [comment]
well, would this delay the inclusion of the features contained here?

**Comment by perrotta** [comment]
@arizzi : I think that as soon as we will have another full build we can plan to merge  #21399 in it, which fully includes this one.
Or is there any reason why you only/first want to merge the updates included in this PR and not the additional ones in #21399?

**Comment by arizzi** [comment]
I'd like to have both!

**Comment by davidlange6** [comment]
Your PR is unmergeable. Please have a look and possibly rebase it.

**Comment by arizzi** [comment]
this is very unfortunate because we already keep two versions for 94x and master and there was no reason to hold this so long that it became unmergeable... I'll also be travelling today so I hope @gpetruc can have a look

**Comment by arizzi** [comment]
btw you merged 21399 that contains this... we ahould probably close thia after we verified thay we did not miss any commit

**Comment by perrotta** [comment]
This PR is FULLY contained in #21399, which got already mearged (and which is the reason of the conflicts).

As I wrote in https://github.com/cms-sw/cmssw/pull/21399#issuecomment-346345365, I already explicitely verified that the content of this PR is actually fully contained (git diff wrt what merged in the master only showed the few different comment lines I noted in the report)

Please @arizzi close this one (reco already gave "-1" to avoid the duplication)

**Comment by arizzi** [comment]
we lost dec17df and 8af4051.
-one is just adding the comments requested for the magic numbers in gen prod interpretation
-the other is enabling DQM in relval (but we figured it was not really enabled due to missing harvesting, so it doesn't really matter)

I'd close this and add those commits in the next 94X PR

**Pull request closed without merging**
