### PR TITLE
adding special hgcal relval workflows in upgradeWorkflowComponents

### PR DESCRIPTION
**Pull request by jnsandhya**
Special relval workflows have been added as part of upgradeWorkflowComponents.py needed for hgcal. Backporting PR #20411

### CODE REVIEW

**Comment by fabozzi** [comment]
@jnsandhya 
This PR is still for master i.e. 94X

**Comment by fabozzi** [comment]
Please select correct CMSSW branch to compare with when making the PR

**Comment by kpedro88** [comment]
please test

**Comment by kpedro88** [comment]
@smuzaffar looks like the bot does not update the milestone when the base branch for the PR is updated?

**Comment by kpedro88** [comment]
backport of #20411

**Comment by jnsandhya** [comment]
Just changed the base release to 93X
On Sep 11, 2017, at 10:13 PM, fabozzi <notifications@github.com<mailto:notifications@github.com>> wrote:


Please select correct CMSSW branch to compare with when making the PR

**Comment by smuzaffar** [comment]
@kpedro88 , cms-bot is fixed now to properly update the milestone.

**Comment by fabozzi** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
