### PR TITLE
Fastsim tracking add dedx collection - backport to 94X

### PR DESCRIPTION
**Pull request by ssekmen**
backport of #25512

"Modified code in FastSimulation/SimplifiedParticlePropagator/ package to make de/dx collections. This involved adding the plugin FastTrackDeDxProducer.cc and modifying FastTrackerRecHits.[.h, .cc], as well as adding a data member to the class DataFormats/TrackerRecHit2D/interface/FastTrackerRecHit.h called energyLoss."

### CODE REVIEW

**Comment by ssekmen** [comment]
please test

**Comment by perrotta** [comment]
+1
- Backport identical to #25512, already merged in master
- For reco, this PR just adds dedx to the FastTrackerRecHit data format; that class (as well as its derived ones) only enters in FastSim related stuffs
- Jenkins tests pass and show no differences

**Comment by ssekmen** [comment]
+1

**Comment by fabiocos** [comment]
hold

as agreed with @ssekmen and PPD conveners

**Comment by sbein** [comment]
Slides with before/after ratios for various observables are attached.  Study is based on 20,000 ttbar events generated with the same random seed before and after this PR. No change is seen in any bin of any observable, so it should be "safe" for production.
[FastSimPR25606Validation.pdf](https://github.com/cms-sw/cmssw/files/2880659/FastSimPR25606Validation.pdf)

**Comment by fabiocos** [comment]
@perrotta as far as I can see the modified DataFormat is not persistent, do you confirm?
@ssekmen this PR provides the code to add a new collection, but this is not activated, am I correct?

**Comment by perrotta** [comment]
@fabiocos : neither FastTrackerRecHit or its derived classes are saved in any eventContent

**Comment by sbein** [comment]
@fabiocos right, event content will not change unless a process like process.dedxHarmonic2 = cms.EDProducer("FastTrackDeDxProducer",... is added to the sequence

**Comment by slava77** [comment]
@ssekmen  @fabiocos 
should we close this PR?
Please comment otherwise if it should stay open.
Thank you.

**Comment by sbein** [comment]
I wanted to finish a study checking the MET distribution in FastSim for LL scenarios. I found a bit of funny behavior with a previous iteration. That should be available within a day or 2

**Comment by slava77** [comment]
> I wanted to finish a study checking the MET distribution in FastSim for LL scenarios. I found a bit of funny behavior with a previous iteration. That should be available within a day or 2

@sbein 
Please clarify on the status.
Thank you.

**Comment by sbein** [comment]
@slava77 summary was given in last simulations meeting. need to check the MET differences b/t fastsim/fullsim for LL models.

**Comment by fabiocos** [comment]
@ssekmen @sbein as agreed I close this PR

**Pull request closed without merging**
