### PR TITLE
HLT V4.0 Mercury (94X)

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
HLT V4.0 Mercury (94X).
Based on CMSSW_9_4_0_pre2.

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please abort

**Comment by davidlange6** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please abort

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Dr15Jones** [comment]
+1
for Utilities/ReleaseScripts

**Comment by Martin-Grunewald** [comment]
+1

**Comment by lpernie** [comment]
Please cherrypick this comment to include latest version of autocond with the new GT with new L1T menu (L1Menu_Collisions2017_v4):
https://github.com/lpernie/cmssw/commit/4c849d17ac8387228269a9c098de2d8357d544ea

**Comment by Martin-Grunewald** [comment]
We need to delay the L1T v4 GTs and @relval2017 switchover to a later PR.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
