### PR TITLE
Updates the Run2 era to match recent changes in the customisations

### PR DESCRIPTION
**Pull request by mark-grimes**
Copies the L1 trigger era updates from FullSim to FastSim.  Has no effect whatsoever unless one of the Run 2 eras is active.

EDIT since opening - since the L1 FullSim changes were requires for this PR, I included them here and closed the other separate PR.

### CODE REVIEW

**Comment by lveldere** [comment]
please test

**Comment by mark-grimes** [comment]
Argh! It's dependant on #10171.  I'll add those to commits to this too and resubmit.

**Comment by mark-grimes** [comment]
Added the commit from #10171 that this relies on.  Will require a signature from L1 trigger as well now.

**Comment by lveldere** [comment]
please test

**Comment by mulhearn** [comment]
@mark-grimes:  we are trying to remove the L1 menu selection from configuration and instead use the versions in the GT.  Will these changes conflict with those changes (See: PR #10184).  (Also: thank you by the way for jumping in and helping out with this mess of L1T configs...)  Can you also point me to a talk or something to help me get up to speed with the intended use of the Eras... this came up when I was mostly offline so I don't yet understand what should go in the GT versus the customizations.

**Comment by mark-grimes** [comment]
@mulhearn, yes I saw #10184 after submitting this batch of PRs.  That doesn't conflict in the git sense, but it diverges the era and customisation functions.  Eras are intended as a replacement for customisation functions, mainly so that changes are in the same file as the original.  Hence changes are devolved to the relevant experts rather than a monolithic central area.  There is a [twiki page](https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideCmsDriverEras), let me know if any of it isn't clear.
Until the switch is made I'm making sure both methods give the same results, so I will update the era when #10184 is merged.  At some point (don't know when) we will switch to using eras and deprecate customisation functions, then any further configuration changes will go in eras only.  Until then carry on as you are and I will try to keep the era in synch.

**Comment by mulhearn** [comment]
Thanks!

**Comment by mark-grimes** [comment]
About push some changes that bring the latest updates.  With this and #10172 the eras and customisation functions are in line.  There is a summary of the differences (verbatim differences are expected) for CMSSW_7_6_X_2015-07-28-1100 at http://grimes.web.cern.ch/grimes/eraProcessDiffs/processDiffs-7_6_X_2015-07-28-1100-PR10172-PR10187.html.
That shows differences with the `outputCommands`, but they're difficult to check programmatically.  I'm about to check that they're just the same thing reordered by hand.

**Comment by mark-grimes** [comment]
Found some extra collections in the era configurations:

http://grimes.web.cern.ch/grimes/eraProcessDiffs/fileDumpDiffs-7_6_X_2015-07-28-1100-PR10172-PR10187.txt

So, there will need to be another PR to fix that.

**Comment by mark-grimes** [comment]
Actually, ignore that last comment.  I was accidentally using the wrong branch, output collections are exactly the same.  The report in the link above has been updated.

**Pull request merged**
