### PR TITLE
Remove nonfunctional and unmaintained FP420 code

### PR DESCRIPTION
**Pull request by jpata**
#### PR description:
FP420 is no longer developed, the code is not maintained, and not runnable.
We got a confirmation neither CTPPS nor Proton want to pick up the maintenance.

Addresses https://github.com/cms-sw/cmssw/issues/36612.

#### PR validation:

Compiles.

### CODE REVIEW

**Comment by jpata** [comment]
@cmsbuild please test

**Comment by jpata** [comment]
@cmsbuild please test

**Comment by jpata** [comment]
+reconstruction
- addresses https://github.com/cms-sw/cmssw/issues/36612
- technical, no changes

**Comment by civanch** [comment]
+1

**Comment by makortel** [comment]
+core

Happy to, the need just missed my attention

**Comment by perrotta** [comment]
+1

**Pull request merged**
