### PR TITLE
Phase2-hgx157 Update the standalone digi study of HGCal (upgrade) to give reasonable o/p

### PR DESCRIPTION
**Pull request by bsunanda**
Also split it up for each sub detector

### CODE REVIEW

**Comment by andrius-k** [comment]
Hi @bsunanda, could you please make sure that the there is a name of a subsystem in the title of the PR?

**Comment by rovere** [comment]
@bsunanda ,
while I have nothing in abstract terms against test code that could be run standalone, I do feel the need to discuss this kind of tools in a more general way with a bigger audience, so that relevant people are aware of their existence.

Also, I'm strongly in favour of adding as much DQM/Validation as needed/possible for the HGCal detector, having an accompanying Twiki page that explains what it does (and also how would be a wonderful plus).

**Comment by bsunanda** [comment]
@rovere I fully agree with this. This is done on request by Kaushik who is doing some validation work and I shall ask him to prepare the twiki page with all validation tools and also discuss about all validation tool within DPG

**Comment by bsunanda** [comment]
@andrius-k Sorry I missed out the name which I have now added

**Comment by bsunanda** [comment]
@andrius-k Could you sign this please?

**Comment by andrius-k** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
