### PR TITLE
Update the autoSkim.py for new HLT menu v1.3

### PR DESCRIPTION
**Pull request by sam7k9621**
#### PR description:
To be synced with PD changes in the new HLT menu (v1.3)

1. Merged **SingleMuon** and **DoubleMuon** into **Muon** dataset
2. Merged **JetHT** and **MET** into **JetMET** dataset
3. Removed unused PD **ParkingBPH**

#### PR validation:

None

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport of #38933

### CODE REVIEW

**Comment by bbilin** [comment]
@cmsbuild, please test

**Comment by qliphy** [comment]
@sam7k9621  Is this a backport from master?

**Comment by sam7k9621** [comment]
> @sam7k9621 Is there a corresponding PR in master?

@qliphy I just created a PR in master and updated the backport info.

**Comment by kskovpen** [comment]
please test

**Comment by kskovpen** [comment]
+pdmv

**Comment by qliphy** [comment]
+1

**Comment by qliphy** [comment]
@sam7k9621  It seems this backport PR brought some unit test issue in 12_4_X IB which doesn't appear in the master IB:
https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_amd64_gcc10/CMSSW_12_4_X_2022-08-09-1100/unitTestLogs/Configuration/DataProcessing#/902-902

Exception: Impossible to map SingleMuon from {'BTagMu': 'LogError+LogErrorMonitor', 'DisplacedJet': 'EXODisplacedJet+EXODelayedJet+EXODTCluster+EXOCSCCluster+LogError+LogErrorMonitor', 'JetMET': 'JetHTJetPlusHOFilter+EXOHighMET+EXODelayedJetMET+LogError+LogErrorMonitor', 'EGamma': 'ZElectron+WElectron+EXOMONOPOLE+LogError+LogErrorMonitor', 'Tau': 'LogError+LogErrorMonitor', 'Muon': 'ZMu+LogError+LogErrorMonitor', 'MuonEG': 'TopMuEG+LogError+LogErrorMonitor', 'NoBPTX': 'EXONoBPTXSkim+LogError+LogErrorMonitor', 'HcalNZS': 'LogError+LogErrorMonitor', 'HLTPhysics': 'LogError+LogErrorMonitor', 'ZeroBias': 'LogError+LogErrorMonitor', 'Commissioning': 'EcalActivity+LogError+LogErrorMonitor', 'Cosmics': 'CosmicSP+CosmicTP+LogError+LogErrorMonitor', 'MonteCarlo': 'EXODisappTrk+LogError+LogErrorMonitor'}

Failure for configuration: /data/cmsbld/jenkins/workspace/ib-run-qa/CMSSW_12_4_X_2022-08-09-1100/src/Configuration/DataProcessing/test/RunPromptReco.py --scenario ppEra_Run2_2018 --reco --aod --dqmio --global-tag GLOBALTAG --lfn=/store/whatever --alcareco TkAlMinBias+SiStripCalMinBias --PhysicsSkim=@SingleMuon: status 1
status = 256

---> test TestConfigDP had ERRORS
TestTime:1210
^^^^ End Test TestConfigDP ^^^^
>> Tests for package Configuration/DataProcessing ran.

**Comment by qliphy** [comment]
@sam7k9621  Is there anything missing to backport?

**Comment by sam7k9621** [comment]
@qliphy thank you for the reminder, I have applied a new PR to fix this issue #39009

**Comment by qliphy** [comment]
Thanks @sam7k9621

**Pull request merged**
