### PR TITLE
Vectorized 2D simulated annealing vertexing and Updates to precision timing integration in reconstruction and miniaod [93X]

### PR DESCRIPTION
**Pull request by bendavid**
Combined backport of https://github.com/cms-sw/cmssw/pull/19935 and https://github.com/cms-sw/cmssw/pull/20338

### CODE REVIEW

**Comment by kpedro88** [comment]
assign upgrade

**Comment by kpedro88** [comment]
please test

**Comment by slava77** [comment]
I don't see 163dda9 in the list of commits to expect a transparent merge of #20338.
if we keep this PR in now, I'd have to "-1" the #20338

IMHO, this PR wack-a-mole is not making things advance faster.

@kpedro88 
please confirm that this combined [but possibly not making it] is better than one by one.

**Comment by bendavid** [comment]
The intention was to merge either https://github.com/cms-sw/cmssw/pull/20338 OR this one.

If https://github.com/cms-sw/cmssw/pull/20338 is merged I can rebase this one.

**Comment by kpedro88** [comment]
@slava77 theoretically there's less dead time (waiting for tests, IBs, etc.) if we can test/merge two related backports at once

@bendavid not sure what you did to make this branch... @lgray's branch is already compatible with 93X, so I think you can just use `git cms-checkout-topic` with his branch and then rebase yours on top of it.

**Comment by bendavid** [comment]
Yes ok, I just cherry-picked the commits on top of the latest 93x IB.

**Comment by bendavid** [comment]
Btw, it's not possible to simply base these changes on top of https://github.com/cms-sw/cmssw/commit/163dda924ab37b565c2b2ff011882cbf7b93c968 as originally suggested, since this would create a merge conflict with https://github.com/cms-sw/cmssw/commit/f0e2d9f2613fbbe4d3da336f83a1e5cfe9eac2f4#diff-aeb8de2821a36977d6947e28e5a972ef and https://github.com/cms-sw/cmssw/commit/f49968a31031f7519508f44bc1113f5182b95b7f#diff-aeb8de2821a36977d6947e28e5a972ef which had been added more recently than where https://github.com/cms-sw/cmssw/pull/19935 started from.

I'll leave this as is for now and rebase as needed once https://github.com/cms-sw/cmssw/pull/20483 is merged in CMSSW_9_3_X

**Comment by bendavid** [comment]
Since https://github.com/cms-sw/cmssw/pull/19935 was already backported separately in https://github.com/cms-sw/cmssw/pull/20483, I'm closing this in favour of https://github.com/cms-sw/cmssw/pull/20535

**Pull request closed without merging**
