### PR TITLE
[IOMC] Move public headers to interface directory

### PR DESCRIPTION
**Pull request by smuzaffar**
Removed unnecessary include statements
As reported in #34718 , this PR moves headers in interface directory for `IOMC/RandomEngine`
```
      3 src/IOMC/RandomEngine/src/TRandomAdaptor.h
      2 src/IORawData/DTCommissioning/plugins/RawFile.h
```

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by makortel** [comment]
+1

**Comment by qliphy** [comment]
kindly ping @cms-sw/daq-l2

**Comment by smorovic** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
