### PR TITLE
Add missing include to  TrackingRecHit.h

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

The header now includes all symbols it references. This was spotted by the CXXMODULE IB.

#### PR validation:

The code compiles.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
FYI @smuzaffar

**Comment by Dr15Jones** [comment]
please test

**Comment by makortel** [comment]
Already done in https://github.com/cms-sw/cmssw/pull/29606

**Comment by Dr15Jones** [comment]
I only looked in open pull request which is why I missed it. Darn.

**Pull request closed without merging**
