### PR TITLE
additional features for alignment validation dmr plotting tool

### PR DESCRIPTION
**Pull request by ssthr**
Two additional features to the All-In-One Alignment Validation tool are provided in separate commits.

-`parallel merging of DMR histos`: An option is given to merge the root dmr histograms in parallel to save runtime. Call tool with `--mergeOfflineParallel`-flag to activate the feature.

-`statistical measures`: Several statistical measures of potential interest are printed out for each DMR validation. Includes several p-Values to judge the significance of differences between the distributions and an estimate for the alignment uncertainty.

Further details can be found at:
https://indico.cern.ch/event/649310/contributions/2673094/attachments/1502539/2340536/presentation.pdf

### CODE REVIEW

**Comment by arunhep** [comment]
@cmsbuild please test

**Comment by lpernie** [comment]
+1

**Comment by smuzaffar** [comment]
code-checks

**Comment by davidlange6** [comment]
+1

**Pull request merged**
