### PR TITLE
Pixel Cluster Counting Automation Integration - LumiPOG on 10_1_X

### PR DESCRIPTION
**Pull request by samhiggie**
Hello, 

This pull request represents continued work from our PCC Automation from 2017 an extension from Calibration/LumiAlCaRecoProducers/

The LumiPOG wants to incorporate these changes into the live release 10_1_X if possible, and would need to integrate a combined process involving RawPCCProducer and CorrPCCProducer into PCL to derive corrections for the luminosity using the Random Triggers that the LumiPOG uses. 
We have yet to merge into PCL and might need extra tips to do this. 

Looking forward to these changes!

Cheers,
Sam H. and the LumiPOG

### CODE REVIEW

**Comment by arunhep** [comment]
please test

**Comment by capalmer85** [comment]
@arunhep Is this where we should be putting the PR?  Does "please test" not work if in state "code-checks-rejected"?  It looks like that is a problem for all 10_1_X PRs.

**Comment by capalmer85** [comment]
Update how?

**Comment by boudoul** [comment]
hi @capalmer85 , the needed changes are proposed by the link provided by the code-check, I recall the link here  : https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-22439/3700/git-diff.patch

**Comment by capalmer85** [comment]
@boudoul Thanks for the link.  That was easy.  :-)

**Comment by arunhep** [comment]
please test

**Comment by cerminar** [comment]
@samhiggie 
Do I understand correctly that:
[Calibration/LumiAlCaRecoProducers/test/raw_corr_Random_cfg.py](https://github.com/samhiggie/cmssw/blob/0488a5ab8d4f30e86b35bce164c1f451437a4a67/Calibration/LumiAlCaRecoProducers/test/raw_corr_Random_cfg.py)
would be the configuration for PCL while
[Calibration/LumiAlCaRecoProducers/test/raw_ZeroBias_cfg.py](https://github.com/samhiggie/cmssw/blob/0488a5ab8d4f30e86b35bce164c1f451437a4a67/Calibration/LumiAlCaRecoProducers/test/raw_ZeroBias_cfg.py)

Is the configuration that you would like to run in an alcareco in prompt?

I guess this would need to be put in the standard format for having an ALCARECO and the PCL workflow called by ConfigBuilder...unless you have already done the cooking of the confuguration.
is that right?

**Comment by capalmer85** [comment]
These are the configurations we used with crab for offline analysis of 2017
data.  We wanted to keep them somewhere for reference.  We assumed that we
would work out how to implement the online configuration with you in a
separate PR.

Does that work for you or would you like us to work out the prompt reco
configuration here as well?

**Comment by cerminar** [comment]
@capalmer85 sounds good I just wanted to make sure I got the point. I can start working at the configurations looking at these files as reference. As you said this will go in a separate PR.
BTW, as requested by @arunhep  in out mail thread, we will need a payload for testing the prompt-reco alcareco in relvals on real data. (it just needs to ensure functionality not physics quality results).

**Comment by arunhep** [comment]
+1

**Comment by fabiocos** [comment]
@arunhep this PR does not add this extra code to the ALCARECO workflows for the time being, only standalone test configurations are provided. Were they used to test and validate the code? Was this presented somewhere?

**Comment by capalmer85** [comment]
These producers were used to produce luminosity results on the 2017 data.
The configuration files were used to test these exact version of the
producers, but no presentation was made regarding the validation.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
