### PR TITLE
L1T: KBMTF update to coarse eta

### PR DESCRIPTION
**Pull request by cecilecaillol**
#### PR description:

Updated KBMTF coarse eta assignments in the bmtf/omtf regions. New LUTs can be found in L1Trigger/L1TMuon/data/bmtf_luts/kalmanLUTs_v302.root, the config file has been modified accordingly.

Needed for next MWGR. Will be backported to 11_3_X

#### PR validation:

Rebase of https://github.com/cms-l1t-offline/cmssw/pull/919

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Rebase of https://github.com/cms-l1t-offline/cmssw/pull/919

### CODE REVIEW

**Comment by cecilecaillol** [comment]
+l1

**Comment by rekovic** [comment]
this will be tested with the Externals PR https://github.com/cms-data/L1Trigger-L1TMuon/pull/21

**Comment by rekovic** [comment]
attn @mrodozov

**Comment by rekovic** [comment]
we need to abort the test, since the LUT that is pointed to in 5bfbc09 is not available in the Externals yet.

**Comment by rekovic** [comment]
please abort test

**Comment by mrodozov** [comment]
please test with cms-data/L1Trigger-L1TMuon#21

**Comment by mrodozov** [comment]
testing with L1Trigger-L1TMuon#21 will bring the _v302.root file

**Comment by qliphy** [comment]
+1

**Comment by rekovic** [comment]
@cecilecaillol  We need a backport of this to 11_3_X

**Comment by rekovic** [comment]
Also, I see now that the root file is merged as well.  We need to delete it from main CMSSW_12_X.

**Pull request merged**
