### PR TITLE
bsunanda:Run2-alca12 Allow some debugging to the IsoTrack trigger filter code

### PR DESCRIPTION
**Pull request by bsunanda**
Provide debugging to IsoTrack trigger filters

### CODE REVIEW

**Comment by fwyzard** [comment]
-1

**Comment by fwyzard** [comment]
@bsunanda , please use `LogDebug` instead of `#ifdef` and `edm::LogInfo` .

**Comment by fwyzard** [comment]
@cmsbuild please test

**Comment by bsunanda** [comment]
Please recheck these tests. Failure happens in DAS query which has nothing to do with the changed code. It must be some transient hickup due to network.  I cannot reproduce the error.
________________________________

**Comment by bsunanda** [comment]
I ran the matrix a few times. Sometimes it has 0 error - sometimes 1, sometimes 2 errors - but when there are error(s) it is always for DAS enquiry.
________________________________
From: Sunanda Banerjee
Sent: 04 May 2015 19:13
To: cms-sw/cmssw; cms-sw/cmssw
Subject: RE: [cmssw] bsunanda:Run2-alca12 Allow some debugging to the IsoTrack trigger filter code (#8950)

Please recheck these tests. Failure happens in DAS query which has nothing to do with the changed code. It must be some transient hickup due to network.  I cannot reproduce the error.
________________________________

**Comment by fwyzard** [comment]
@cmsbuild please test

**Comment by fwyzard** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
