### PR TITLE
MTD reconstruction: save correct outermost hit position also for tracks w/o last hit in mtd

### PR DESCRIPTION
**Pull request by martinamalberti**
#### PR description:
This PR implement a fix of the outermost hit position value, saved by the TrackExtenterWithMTD class, for tracks w/o last hit in MTD.

#### PR validation:
The code compiles, runs and produces expected results. 
Tested on workflow 29607.0.

### CODE REVIEW

**Comment by jfernan2** [comment]
enable profiling

**Comment by jfernan2** [comment]
please test

**Comment by fabiocos** [comment]
please test

all failures in previous test look unrelated to this PR

**Comment by jfernan2** [comment]
+1

**Comment by fabiocos** [comment]
@martinamalberti @jfernan2 this is effectively a bug fix, although not a critical one, probably it might make sense to backport it to 14_2_X, now that we have moved forward

**Comment by fabiocos** [comment]
@cms-sw/upgrade-l2 any comment?

**Comment by fabiocos** [comment]
type bugfix

**Comment by Moanwar** [comment]
> @cms-sw/upgrade-l2 any comment?

Hi @fabiocos , I wrote a comment above about double-checking the trackMaxBtlEta_. In the first commit, it was set to 1.48, but then it was changed to 1.5. I just wanted to confirm which value is correct. Unfortunately, I haven't received a response yet so I can approve the PR from the upgrade side. Thanks for confirming!

**Comment by fabiocos** [comment]
@Moanwar eta=1.5 is consistent with the BTL/ETL separation used in ```Validation/MtdValidation```, we agreed with @martinamalberti to use the same value as there

**Comment by Moanwar** [comment]
> @Moanwar eta=1.5 is consistent with the BTL/ETL separation used in `Validation/MtdValidation`, we agreed with @martinamalberti to use the same value as there

Thanks a lot @fabiocos for confirmation :)

**Comment by Moanwar** [comment]
+Upgrade

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
