### PR TITLE
remove deprecated heavyIon scenario workflows

### PR DESCRIPTION
**Pull request by mandrenguyen**
#### PR description:

There are some knock-off effects from the removal of workflows based on the old `heavyIons` scenario, done in:
https://github.com/cms-sw/cmssw/pull/43824

The removal of these in the master is causing issues in CMSSW_14_0_X, as described here:
https://github.com/cms-sw/cmssw/pull/44612#issuecomment-2044421667

This PR simply removes these workflows in 14_0_X as well. 

#### PR validation:

compiles

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

This is a manual cherry-pick of 
https://github.com/cms-sw/cmssw/commit/01c75db2cbdf096b31f28ea26956afa37ef5baf2

### CODE REVIEW

**Comment by mandrenguyen** [comment]
please test

**Comment by mandrenguyen** [comment]
please test

**Comment by mandrenguyen** [comment]
please test

**Comment by antoniovilela** [comment]
@cms-sw/pdmv-l2 @cms-sw/upgrade-l2 
Let's get this in 14_0_5 to avoid failing workflows.
Thanks.

**Comment by AdrianoDee** [comment]
+pdmv

**Comment by AdrianoDee** [comment]
I was wondering if it would make sense to back port all https://github.com/cms-sw/cmssw/pull/43824 ? Or is it too much?

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
