### PR TITLE
migrate modules used by the HLT menu to multithreading (L1)

### PR DESCRIPTION
**Pull request by fwyzard**
This is the L1-only part of #10909 .

### CODE REVIEW

**Comment by fwyzard** [comment]
@cmsbuild please test

**Comment by fwyzard** [comment]
tracked at #10964

**Comment by mulhearn** [comment]
+1

**Comment by davidlange6** [comment]
@fwyzard  - this does not merge now

**Comment by fwyzard** [comment]
The history of these files is a mess :-(

Anyway, my commit already takes care of the namespace cleanup.
Can you do the merge with

  git merge -Xtheirs my-cmssw/migrate_to_multithreading_75x_L1

?

Otherwise you can pick #11072, where I just did that.

.A

**Pull request closed without merging**
