### PR TITLE
CTPPS: pixel DQM

### PR DESCRIPTION
**Pull request by popovvp**
initial ctpps_pixel_dqm code

### CODE REVIEW

**Comment by slava77** [comment]
assign dqm

**Comment by slava77** [comment]
[following up after a private email]
I notice that the submitted code is in a wrong directory
instead of cmssw/DQM/CTPPS they should be all in DQM/CTPPS

**Comment by popovvp** [comment]
Hi Slava
  How to do that ?
  Thanks,
    Vladimir

**Comment by slava77** [comment]
On 4/13/17 3:25 PM, popovvp wrote:
> 
> Hi Slava
> How to do that ?
> Thanks,
> Vladimir
> 

given there is just one commit here, just remake a PR.

**Comment by popovvp** [comment]
Leave a comment

**Pull request closed without merging**
