### PR TITLE
fix conversion to XML for objects with template names

### PR DESCRIPTION
**Pull request by apfeiffer1**
- fix conversion to XML for objects with template names
- add an example for conversion of EcalCondObjectContainer<EcalTPGCrystalStatusCode> objects to XML in C++ to speed up conversion (1 sec instead of 20 sec when compiled-on-the-fly)

### CODE REVIEW

**Comment by ggovi** [comment]
+1

**Comment by davidlange6** [comment]
@apfeiffer1 - this does not merge - could you rebase it. Thanks

**Comment by apfeiffer1** [comment]
@cmsbuild please test again
@davidlange6 - resolved.

**Comment by ggovi** [comment]
+1

**Comment by apfeiffer1** [comment]
@davidlange6 - ping ... is there a reason this is not in yet ?

**Comment by davidlange6** [comment]
its not tested yet - I'll start those

**Comment by davidlange6** [comment]
@cmsbuild, please test

**Comment by apfeiffer1** [comment]
Could some expert please "translate" to me the error message ? Sorry, but I do not understand either the text in the comments here nor the one at the link :( My present understanding is that the line (from the link):

/bin/sh: -c: line 0: syntax error near unexpected token `('

indicates a problem in the infrastructure, not really a problem of the unit-test itself (which should not be affected by the changes in the PR at all) ??? 

Thanks, 
   cheers, andreas

**Comment by davidlange6** [comment]
+1

**Comment by davidlt** [comment]
How did this pass? This is breaking unit test compilation.
```
git diff c7b8f3e62d0e1a78de336ddc77f84e6012e3369a..612d4ac43289aa0e51ce67f546df343f91086491 -- CondCore/CondDB/test/BuildFile.xml
```
You removed _testCondDBDict_ library, but did not remove statements in 3 unit test linking to it.

**Comment by davidlt** [comment]
Apparently _testRootStreaming_ test requires you to have a dictionary built in test.

**Pull request merged**
