### PR TITLE
Improve DQM beamspot clients

### PR DESCRIPTION
**Pull request by francescobrivio**
#### PR description:
Forward port of #35918

Updates to the Legacy and HLT BeamSpot DQM clients:
- Fixed the names of the output DQM folder so that the DQM is more clear:
   - 1 folder for BeamMonitorLegacy
   - 1 folder for BeamMonitorLHT
   - previous BeamMonitor folder is removed
- Added the offline <-> online beamspot swap same as in express and HLT
- In the BeamSpot Legacy clients I also fixed the pixelTracksTrackingRegions parameters to remove the 2018 HI customization that was left there (thanks @mmusich!). Overall this should increase the number of tracks reconstructed by the Legacy client so that it can fit PVs and eventually the Beamspot.
- Fixed a typo in the name of the Legacy BeamSpotOnline tag

**[Important Note]** 
This PR contains an additional commit to remove the following customization in the BeamSpot Legacy DQM client:
```
process.pixelTracksTrackingRegions.RegionPSet.ptMin = 0.1
```
This customization was used in 12_0_X during PilotBeam 2021 data taking due to the special collision conditions, but should not be applied for standard collision.

#### PR validation:
Validated with DQM playback system and also during data-taking, see https://github.com/cms-sw/cmssw/pull/35918#issuecomment-956087758 and https://github.com/cms-sw/cmssw/pull/35918#issuecomment-956119341 for the outcome of the data-taking.

#### Backport
A backport to 12_0_X is provided in #35918
A backport to 12_1_X is provided in #35935

### CODE REVIEW

**Comment by emanueleusai** [comment]
please test

**Comment by jfernan2** [comment]
please test with #35921

**Comment by perrotta** [comment]
please abort
(no need to rerun all tests only to get rid of a unit test error, already fixed in the IB)

**Comment by perrotta** [comment]
... unless you @jfernan2 really wanted to test that unit test!
Please let me know if I misunderstood your intentions (and apologize if so)

**Comment by jfernan2** [comment]
Thanks @perrotta 
Since this PR is affecting DQM/Integration where UnitTests are, this was a way to check if this PR was consistent with its backports (beyond an eye inspection from my side), but it is fine, no problem.

**Comment by perrotta** [comment]
+1
- Identical to #35918, which was already merged in 12_0_X to be used in the latest data taking with beams

**Comment by jfernan2** [comment]
+1
Tested in Online DQM at P5

**Comment by perrotta** [comment]
merge

**Pull request merged**
