### PR TITLE
TopHLT: Updated electron ID

### PR DESCRIPTION
**Pull request by skonstantinou**
Updated electron ID and removed electron isolation cut ( iso cut is included in electron ID) 
Other updates: changed the HT definition in fully hadronic paths (pt>30 & abs(eta)<2.4) and default b-tagging algorithm

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by andrius-k** [comment]
+1

**Comment by andrius-k** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Pull request merged**
