### PR TITLE
missing * in keep statement for gedGsfElectronCores

### PR DESCRIPTION
**Pull request by shervin86**
This bug is not present in 75X where the \* is present

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild please test

**Comment by mmusich** [comment]
+1
trivial change, but allows to keep correct event content

**Comment by davidlange6** [comment]
@shervin86 - this * is dangerous. Could you the explicit set of modules that you want instead. Thanks

**Comment by shervin86** [comment]
The * didn't seem to me dangerous, but I fixed putting the full label

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
+1

**Comment by davidlange6** [comment]
Thanks! @shervin86  - could you also propagate this change to 75x.

**Pull request merged**
