### PR TITLE
Cleanup of BTV OfflineDQM

### PR DESCRIPTION
**Pull request by marco-link**
#### PR description:

- remove of old taggers from OfflineDQM:
  - combMVAv2
  - CSVTag
  - CSVv2
  - Ctagger
  - CtaggerTag
  - JBP
  - SET
  - SISVHE
  - SMT
  - SSVHE
  - TCHE

- extend jet eta range in histograms from 2.4 to 2.5
- remove now deprecated module `MVAJetTagPlotter` (affected by #31061)

#### PR validation:
`runTheMatrix.py -l 136.891` and `runTheMatrix.py -l 12034.0` to verify DQMOffline histograms are filled correctly

`runTheMatrix.py -l limited -i all --ibeos` with some unrelated failures:

```
----- Begin Fatal Exception 16-Jun-2021 11:33:13 CEST-----------------------
An exception of category 'StdException' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing ESSource: class=PoolDBESSource label='GlobalTag'
Exception Message:
A std::exception was thrown.
Connection on "frontier://(preferipfamily=0)(proxyconfigurl=http://grid-wpad/wpad.dat)(backupproxyurl=http://cmst0frontier.cern.ch:3128)(backupproxyurl=http://cmst0frontier1.cern.ch:3128)(backupproxyurl=http://cmst0frontier2.cern.ch:3128)(backupproxyurl=http://cmsbpfrontier.cern.ch:3128)(backupproxyurl=http://cmsbpfrontier1.cern.ch:3128)(backupproxyurl=http://cmsbpfrontier2.cern.ch:3128)(backupproxyurl=http://cmsbproxy.fnal.gov:3128)(serverurl=http://cmsfrontier.cern.ch:8000/FrontierProd)(serverurl=http://cmsfrontier1.cern.ch:8000/FrontierProd)(serverurl=http://cmsfrontier2.cern.ch:8000/FrontierProd)(serverurl=http://cmsfrontier3.cern.ch:8000/FrontierProd)(serverurl=http://cmsfrontier4.cern.ch:8000/FrontierProd)/CMS_CONDITIONS" cannot be established ( CORAL : "ConnectionPool::getSessionFromNewConnection" from "CORAL/Services/ConnectionService" )
----- End Fatal Exception -------------------------------------------------
```

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
Thanks @marco-link !!

**Comment by jfernan2** [comment]
Thank you very much for this cleaning @marco-link !!

**Comment by jfernan2** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
