### PR TITLE
bsunanda:Run2 alca65 Activate accessing DB for new Hcal objects

### PR DESCRIPTION
**Pull request by bsunanda**

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by kpedro88** [comment]
@mmusich please review ASAP, needed for other development PRs

**Comment by mmusich** [comment]
-1
why you need to change autoCond?
Let's wait for next IB. Shoul contain the needed changes

**Comment by kpedro88** [comment]
I think this PR merges @mmusich's earlier PR updating autocond and needs to be rebased.

**Comment by bsunanda** [comment]
@mmusich I did not change autocond - just built it on top of your PR. That is why you see the change there. I tried to rebase with the latest IB and there is no conflict.

**Comment by mmusich** [comment]
@bsunanda then please remove any change in `Configuration/AlCa/python/autoCond.py`. The upgrade GTs need further work before pre13 and this will soon conflict. 
Ps: the current 81x HEAD already has the needed Global Tags.

**Comment by bsunanda** [comment]
@mmusich I did not make any change to autocond.. May be I close this PR and make a fresh one. At that time I needed your PR to test validity

**Pull request closed without merging**
