### PR TITLE
 New_samples (TTbarLepton_14 and QQH1352T_14) added with some changes

### PR DESCRIPTION
**Pull request by sharmaaash**
#### PR description:

Following changes are made -
mass of Higgs - 125 GeV
mass of top - 172.5
Tuning is updated to 'TuneCP5'

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by chayanit** [comment]
@sharmaaash should we also update the file name QQH1252T_14?

**Comment by sharmaaash** [comment]
> @sharmaaash should we also update the file name QQH1252T_14?

Yes, I updated the file name QQH1252T_14

**Comment by agrohsje** [comment]
@sharmaaash why was this closed? will you open again or is it obsolete?

**Comment by sharmaaash** [comment]
> @sharmaaash why was this closed? will you open again or is it obsolete?

No, it is no longer to be useful. So there is another PR created without any changes in upgradeWorkflowComponents file.

**Pull request closed without merging**
