### PR TITLE
Fixes for conddb tools

### PR DESCRIPTION
**Pull request by ggovi**
Various fixes for tag metadata management:
- conddb: in copy tag, fixed tag metadata  handling
- conddb_version_mgr: boost version validation in GTs set as optional

### CODE REVIEW

**Comment by ggovi** [comment]
please test

**Comment by ggovi** [comment]
please test

**Comment by ggovi** [comment]
+1

**Comment by fabiocos** [comment]
@ggovi is this still needed for 94X?

**Pull request closed without merging**
