### PR TITLE
Run4-hgx287X Extend the work for V16 Geometry of HGCal

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Extend the work for V16 Geometry of HGCal: Do the all silicon layers for the hadronic part

#### PR validation:

Use the runTheMatrix test workflows

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

**Comment by qliphy** [comment]
+1

**Pull request merged**
