### PR TITLE
Complete EventSetup migration for bunch of L1 modules

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

This PR is part of #31061. It completes the EventSetup-consumes migration for bunch of L1 modules that were partly migrated earlier, but were causing failures in #31746.

#### PR validation:

Code compiles, these modules no longer triggers the exception of #31746 in a job using them.

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by jfernan2** [comment]
+1

**Comment by silviodonato** [comment]
kind reminder @cms-sw/l1-l2

**Comment by rekovic** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
