### PR TITLE
Backport: make PFJetId-calculation configurable with maxEta parameter, set defa…

### PR DESCRIPTION
**Pull request by kirschen**
…ult to eta 5.2

76X PR: #10570

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
-1
The code must reproduce the old behaviour; thus set maxEta to 1e99.

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
