### PR TITLE
Elestream 75 x

### PR DESCRIPTION
**Pull request by amassiro**
Electron stream for ECAL.

Multi-threading friendly type implemented.
edm::EDProducer ---> edm::stream::EDProducer< >
Plus further refinements in the code.

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by diguida** [comment]
@cmsbuild is stuck in tests since 2 days here

**Comment by diguida** [comment]
@cmsbuild please test

**Comment by diguida** [comment]
let's try again!

**Comment by diguida** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
I started tests manually, just in case

**Comment by diguida** [comment]
@slava77 thanks

**Comment by mmusich** [comment]
+1
for https://github.com/amassiro/cmssw/commit/7807c6ec85d5f8f1f13b89521ce38bec0af62837
- fwdport of #9720. 
- Changed the producer to multi-thread safe
- minor changes in the names of variables (improved readability)

**Comment by davidlange6** [comment]
+1

**Pull request merged**
