### PR TITLE
[muon] updated mva weights and tuned the default values

### PR DESCRIPTION
**Pull request by drkovalskyi**
Updated MVA weights and tuned the default values in accordance with the recent practice in SUSY and HIG PAGs. It fits current reco better than the old MVA training. In future we may need to introduce an era dependent code.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
```
<FATAL>                          : The expression declared to the Reader needs to be checked (name or order are wrong)
***> abort program execution
22-Jun-2018 06:41:47 CEST  Closed file file:step2.root
----- Begin Fatal Exception 22-Jun-2018 06:41:47 CEST-----------------------
An exception of category 'StdException' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing module: class=PATMuonProducer label='patMuons'
Exception Message:
A std::exception was thrown.
FATAL error
----- End Fatal Exception -------------------------------------------------

```
this doesn't look related to a missing training file (which should be in the IB).
Does the error mean that the file or is it the code that is bad?

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/23637	1e883cf
- changes in the code are in line with the PR description: new muon MVA training is now used in PAT/miniAOD
- jenkins tests pass and comparisons with the baseline show differences only in the slimmedMuons variables related to ID/MVA

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Pull request merged**
