### PR TITLE
Update unit tests for LLVM 11

### PR DESCRIPTION
**Pull request by mrodozov**
#### PR description:

This is adjusting existing tests to LLVM 11. llvmlite support for py2 is removed so testLLVMlite is run with python3 only.
The clang tidy test is adding two new lines in the generated yaml, one is 'BuildDirectory' which is better not assumed what it should be.

 #### PR validation:

The tests are running

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test with cms-sw/cmsdist#6691

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
+core

**Comment by silviodonato** [comment]
merge

**Comment by santocch** [comment]
+1

**Pull request merged**
