### PR TITLE
DD4hep: Define Vacuum as thin Air

### PR DESCRIPTION
**Pull request by ianna**
#### PR description:

When DD4hep geometry to G4 geometry converter is used the Vacuum as currently defined:
```
<ElementaryMaterial name="Vacuum" density="1e-13*mg/cm3" symbol=" " atomicWeight="1*g/mole" atomicNumber="1"/>
```
causes G4 to throw:
```
-------- EEEE ------- G4Exception-START -------- EEEE -------

*** ExceptionHandler is not defined ***
*** G4Exception : mat012
      issued by : G4Element::G4Element()
Fail to create G4Element CMS element with Z= 2  N= 1   N < Z is not allowed

*** Fatal Exception ***
-------- EEEE -------- G4Exception-END --------- EEEE -------
```
Instead, the following Vacuum definition as a thin Air works fine:
```
<CompositeMaterial name="Vacuum" density="1e-10*mg/cm3" symbol=" " method="mixture by weight">
   <MaterialFraction fraction="0.7494">
    <rMaterial name="materials:Nitrogen"/>
   </MaterialFraction>
   <MaterialFraction fraction="0.2369">
    <rMaterial name="materials:Oxygen"/>
   </MaterialFraction>
   <MaterialFraction fraction="0.0129">
    <rMaterial name="materials:Argon"/>
   </MaterialFraction>
   <MaterialFraction fraction="0.0008">
    <rMaterial name="materials:Hydrogen"/>
   </MaterialFraction>
  </CompositeMaterial>
```
which creates:
```
Geant4Converter        ++ Created G4  Material: materials:Vacuum    density:  0.000 mg/cm3  RadL: 5864694.266 km   Nucl.Int.Length: 13694660.844 km 
                       Imean:  85.538 eV   temperature: 273.15 K  pressure:   1.00 atm
```
#### PR validation:

when https://github.com/cms-sw/cmssw/pull/26383 is merged:
```
cmsRun SimG4Core/DD4hepGeometry/test/python/testG4Geometry.py
```

#### if this PR is a backport please specify the original PR:

no back port is needed

### CODE REVIEW

**Comment by ianna** [comment]
assign simulation

**Comment by ianna** [comment]
please test

**Comment by civanch** [comment]
@ianna , vacuum in a vacuum chamber is not equal to air. You need a consultation from machine experts, they know this. Moreover, you may ask if the vacuum is the same in different parts of CMS.

**Comment by ianna** [comment]
@civanch which vacuum is used in CMS simulation?

**Comment by civanch** [comment]
@ianna , it is:

<material name="Vacuum0x7f2d9f51e000" state="gas"><T unit="K" value="293.15"/><MEE unit="eV" value="19.2"/><D unit="g/cm3" value="9.99999473841014e-17"/><fraction n="1" ref="H0x7f2d9f6ada40"/>

where H is hydrogen - physically it is more adequate than air. Concerning density - better to ask, if the value is correct. Machine peoples know current situation better than we have in this old definition.

**Comment by civanch** [comment]
@ianna , I suspect DD4hep bug, the line you show potentially correct.

**Comment by ianna** [comment]
Thanks I’ll follow up

**Comment by civanch** [comment]
@ianna, I do not see MEE parameter in your line, I suspect it is DD4Hep defect. They must implement material properly.

**Comment by fabiocos** [comment]
@ianna @civanch any news on this subject? I fully agree with Vladimir that the standard air is not suitable as vacuum proxy, the density is incompatible with we may expect from the beam pipe ambient

**Comment by ianna** [comment]
@fabiocos - yes, it's fixed it in the #26740

**Pull request closed without merging**
