### PR TITLE
Phase2-hgx225 Correct wafer positioning code

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Correct the codes for waferPosition and distFromEdgeHex which are now dependent on layer #. Correction for wafer size will be done in a future PR for V11 version.

#### PR validation:

Use standard runTheMatrix.py to test the code

#### if this PR is a backport please specify the original PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
Why so many comparison differences?

**Comment by kpedro88** [comment]
@cvuosalo a change in a geometry volume will entirely alter the simulation history for any workflow using that geometry. the changes are isolated to the phase 2 D46 workflow, which is expected based on which geometry was modified.

**Comment by cvuosalo** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by kpedro88** [comment]
@bsunanda please update the PR description to say that only V11 was changed, and also to describe the expected comparison changes.

**Comment by bsunanda** [comment]
@kpedro88 Changed. Reverting the sizes for V9/V10 also affected V11. I am testing that separately and shall put a new PR once I am ready

**Comment by kpedro88** [comment]
please test

**Comment by kpedro88** [comment]
+upgrade
changes are extremely minor, isolated to HGCHEFRecHits and downstream products in D46 workflow

**Comment by fabiocos** [comment]
+1

**Pull request merged**
