### PR TITLE
Changes to ape tool for python 3 compatibility and reduced bloat

### PR DESCRIPTION
**Pull request by mteroerd**
#### PR description:

- This PR is mainly supposed to ensure python 3 compatibility for the APE measuring tool. 
- More sanity checks were added to test/autoSubmitter/autoSubmitter.py and test/autoSubmitter/helpers.py. The additions ensure that files defined for a dataset do in fact exist and that files merged from multiple root files are not damaged.
- Automatic result plots were removed from test/autoSubmitter/autoSubmitter.py as this feature was not used and makes maintaning the code more complicated. Result plots can still be created using the code in test/plottingTools.
- Minor errors were fixed.

#### PR validation:

python3 compatibility was mainly enabled based on output of 2to3. Additionally, the code was dry-run in a CMSSW environment that was compiled with python3.

### CODE REVIEW

**Comment by mmusich** [comment]
please test for CMSSW_11_2_PY3_X

**Comment by pohsun** [comment]
+1

**Comment by silviodonato** [comment]
> DQMHistoTests: Total failures: 815

Is this expected? There are many changes in plots like `all_mini_*_min2,max-2,patJets_slimmedJets*__RECO_obj___pairDiscriVector__19__second.png`

eg. `all_mini_OldVSNew_TTbar14TeV2026D35wf20034p0c_min2,max-2,patJets_slimmedJetsAK8__RECO_obj___pairDiscriVector__1__second.png`
image

**Comment by silviodonato** [comment]
please test for CMSSW_11_2_PY3_X

**Comment by mmusich** [comment]
@silviodonato 

> Is this expected? There are many changes in plots like all_mini_*_min2,max-2,patJets_slimmedJets*__RECO_obj___pairDiscriVector__19__second.png

This is not expected to change any production related quantity, isn't the difference just caused by intrinsic differences in the Py3 build?

**Comment by silviodonato** [comment]
> @silviodonato
> 
> > Is this expected? There are many changes in plots like all_mini___min2,max-2,patJets_slimmedJets___RECO_obj___pairDiscriVector__19__second.png
> 
> This is not expected to change any production related quantity, isn't the difference just caused by intrinsic differences in the Py3 build?

You are right. Checking one more time I see that the baseline is `CMSSW_11_2_X_2020-06-30-2300`, so this is a good example of difference between py and py3.

**Comment by silviodonato** [comment]
abort

**Comment by silviodonato** [comment]
please test

**Comment by silviodonato** [comment]
please test

**Comment by silviodonato** [comment]
+1

**Pull request merged**
