### PR TITLE
Use SerialTaskQueues to protect shared resources

### PR DESCRIPTION
**Pull request by Dr15Jones**
Replaced the use of std::recursive_mutexes with SerialTaskQueues when serializing modules to protect a shared resource. This allows the framework to only schedule a TBB task to run when that resource is free thereby opening up thread to do other work while the resource is in use.

This satisfies phase 1.75 of the threaded framework development plan.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
@davidlange6 @smuzaffar Like last time, this is a potentially breaking change so I'd like it testes in CMSSW_8_1_DEVEL_X.

**Comment by Dr15Jones** [comment]
please test

**Comment by smuzaffar** [comment]
this time cms-bot/jenkins picked up the right release i.e. CMSSW_8_1_DEVEL_X_2016-08-25-2300 to test this PR.

**Comment by Dr15Jones** [comment]
Nice!

**Comment by Dr15Jones** [comment]
+1

**Comment by Dr15Jones** [comment]
I've been unable to isolate how this change has affected this unit test. It would help further the testing of this change to merge it into _DEVEL, assuming the usual pull request RelVals ran OK.

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
The failed test is not related to this pull request.

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
Both test failures are deficiencies in the tests themselves and not from this pull request. TestFWCoreFrameworkGlobalStreamOne failed because it has an artificial limit on one of its measurements that just happened to be exceeded. Looks like I still need to tune that cut. TestFWCoreIntegrationStandalone sometimes fails the same way in the IB. 

Neither of these should keep this change from merging into _DEVEL.

**Comment by Dr15Jones** [comment]
@smuzaffar Thanks!

**Pull request merged**
