### PR TITLE
CTPPS: miniAOD (minimal back-port of #17162)

### PR DESCRIPTION
**Pull request by jan-kaspar**
This is a minimal back-port of #17162 intended for the upcoming re-miniAOD campaign. Minimal in the sense that the DetId-related changes in #17162 are not back-ported.

`runTheMatrix.py -l limited` yields
```
	10 10 9 7 5 1 1 1 tests passed, 0 0 0 0 0 0 0 0 failed
```

Regarding the potential problem in #17162, I've run
```
runTheMatrix.py -l 136.731 -j 16 -t 8
```
5 times, on 3 different Lxplus nodes. There was one crash with a signature different from what is discussed for #17162, therefore non conclusive.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@jan-kaspar 
#17162 was reverted and the investigation appears to point to a solution that's not touching your code https://github.com/cms-sw/cmssw/issues/17288.
Please (re)submit a 90X PR (you will need to make a new branch or rebase the old branch to get it to work).

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/17282	195dc70
- implementation of the miniAOD part is the same as in the 90X version. 
- jenkins tests pass and comparisons show no differences
- in addition to tests by @jan-kaspar , I also ran 136.72[1-8] with 4 threads and they all completed. Note that xerces version in 80X is different from that in 90X. So, the stability may be coming from that or from different scheduling of modules in 80X, which is less advanced.

**Comment by monttj** [comment]
+1

**Comment by jan-kaspar** [comment]
This PR is now superseded by the cumulative back-port summarised in https://github.com/CTPPS/cmssw/issues/11.

**Pull request closed without merging**
