### PR TITLE
Removed debug globals used in Phase2L1ParticleFlow

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

The globals were replaced by passing an argument to the relevant functions. This avoids a static analyzer warning.

#### PR validation:

The code compiles.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by rekovic** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade

**Comment by qliphy** [comment]
+1

**Pull request merged**
