### PR TITLE
Modernize SinglePhotonJetPlusHOFilter

### PR DESCRIPTION
**Pull request by makortel**
### PR description:

In the context of #25090 this PR modernizes `SinglePhotonJetPlusHOFilter` by

- Remove unnecessary counters
- Make members `const`, initialize in initializer list, use naming convention
- Remove unnecessary includes
- Make the module global
- Use range-for
- Get event data with `getHandle()`
- Make parameters tracked
- Implement `fillDescriptions()`

#### PR validation:

Limited matrix runs.

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by fabiocos** [comment]
@chayanit @pgunnell @kfjack could you please have a look at this PR?

**Comment by kfjack** [comment]
Hi @fabiocos I checked the test results the skim files have been produced correctly. So the PR should be fine for me. Many thanks.

**Comment by chayanit** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
