### PR TITLE
[14_1_X] [Phase-2] Changed Phase-2 JME and BTV HLT paths to use the L1 P2GT emulator

### PR DESCRIPTION
**Pull request by SohamBhattacharya**
This PR:

 - Changes the Phase-2 JME and BTV HLT paths to use the L1 P2GT emulator.
Now all Phase-2 paths use the P2GT emulator. No significant change is expected in the output.
Testing on 100 events of [1], the trigger report for these paths is almost same before [2a] and after [2b] this change.

- Adds a seed (`pDoublePuppiJet112_112`) to the L1 abbreviated menu, which is needed by the dijet b-tagging HLT paths

- Cleans up `HLT_75_e33_cff.py` and `HLT_75e33_timing_cff.py` to stop running the P2GT emulator within the HLT config, as there is now a dedicated step (`-L1P2GT`) for that.

Tagging @cms-sw/l1-l2

[1] `/store/relval/CMSSW_14_1_0_pre2/RelValSMS-T1tttt_14TeV/GEN-SIM-DIGI-RAW/140X_mcRun4_realistic_v3_STD_2026D98_noPU-v6/2580000/00cf94e1-2e9d-47cd-8c71-b699f7550858.root`

[2a]
```
HLT-Report   HLT #  WasRun     L1S     Pre     HLT   %L1sPre    Rate  RateHi  Errors Name
HLT-Report      22     100     100     100      51  51.00000     0.0     0.0       0 HLT_AK4PFPuppiJet520
HLT-Report      23     100     100     100      77  77.00000     0.0     0.0       0 HLT_PFPuppiHT1070
HLT-Report      24     100     100     100      90  90.00000     0.0     0.0       0 HLT_PFPuppiMETTypeOne140_PFPuppiMHT140
HLT-Report      27     100     100     100      72  72.00000     0.0     0.0       0 HLT_PFHT330PT30_QuadPFPuppiJet_75_60_45_40_TriplePFPuppiBTagDeepCSV_2p4
HLT-Report      28     100     100     100      68  68.00000     0.0     0.0       0 HLT_PFHT200PT30_QuadPFPuppiJet_70_40_30_30_TriplePFPuppiBTagDeepCSV_2p4
HLT-Report      29     100     100     100      43  43.00000     0.0     0.0       0 HLT_DoublePFPuppiJets128_DoublePFPuppiBTagDeepCSV_2p4
HLT-Report      30     100     100     100      71  71.00000     0.0     0.0       0 HLT_PFHT330PT30_QuadPFPuppiJet_75_60_45_40_TriplePFPuppiBTagDeepFlavour_2p4
HLT-Report      31     100     100     100      70  70.00000     0.0     0.0       0 HLT_PFHT200PT30_QuadPFPuppiJet_70_40_30_30_TriplePFPuppiBTagDeepFlavour_2p4
HLT-Report      32     100     100     100      78  78.00000     0.0     0.0       0 HLT_DoublePFPuppiJets128_DoublePFPuppiBTagDeepFlavour_2p4
```

[2b]
```
HLT-Report   HLT #  WasRun     L1S     Pre     HLT   %L1sPre    Rate  RateHi  Errors Name
HLT-Report      23     100     100     100      51  51.00000     0.0     0.0       0 HLT_AK4PFPuppiJet520
HLT-Report      24     100     100     100      77  77.00000     0.0     0.0       0 HLT_PFPuppiHT1070
HLT-Report      25     100     100     100      92  92.00000     0.0     0.0       0 HLT_PFPuppiMETTypeOne140_PFPuppiMHT140
HLT-Report      28     100     100     100      72  72.00000     0.0     0.0       0 HLT_PFHT330PT30_QuadPFPuppiJet_75_60_45_40_TriplePFPuppiBTagDeepCSV_2p4
HLT-Report      29     100     100     100      68  68.00000     0.0     0.0       0 HLT_PFHT200PT30_QuadPFPuppiJet_70_40_30_30_TriplePFPuppiBTagDeepCSV_2p4
HLT-Report      30     100     100     100      43  43.00000     0.0     0.0       0 HLT_DoublePFPuppiJets128_DoublePFPuppiBTagDeepCSV_2p4
HLT-Report      31     100     100     100      71  71.00000     0.0     0.0       0 HLT_PFHT330PT30_QuadPFPuppiJet_75_60_45_40_TriplePFPuppiBTagDeepFlavour_2p4
HLT-Report      32     100     100     100      70  70.00000     0.0     0.0       0 HLT_PFHT200PT30_QuadPFPuppiJet_70_40_30_30_TriplePFPuppiBTagDeepFlavour_2p4
HLT-Report      33     100     100     100      78  78.00000     0.0     0.0       0 HLT_DoublePFPuppiJets128_DoublePFPuppiBTagDeepFlavour_2p4

```

### CODE REVIEW

**Comment by mmusich** [comment]
@SohamBhattacharya please rebase the branch to avoid the merge commit. Also please add newlines to all the newly added files (there were recently PRs to add them to all files in cmssw).

**Comment by SohamBhattacharya** [comment]
> @SohamBhattacharya please rebase the branch to avoid the merge commit. Also please add newlines to all the newly added files (there were recently PRs to add them to all files in cmssw).

Done. 
For my own knowledge: is there a plan to include adding newlines to `code-format`? That would make it easier for the future.

**Comment by mmusich** [comment]
> Done.

As far as I can see this was not rebased (at least I still see the merge commit). Please squash the commits.

> For my own knowledge: is there a plan to include adding newlines to code-format? That would make it easier for the future.

AFAIR, some degree of python linting has been in the plans of the Core framework group, though I don't know about concrete steps about that.

**Comment by mmusich** [comment]
Not sure why you need to keep two commits

**Comment by mmusich** [comment]
> Should be fixed now.

The commit message could be more informative.

**Comment by SohamBhattacharya** [comment]
> > Should be fixed now.
> 
> The commit message could be more informative.

The commit does pretty much what's said in the description.
But fine, it's updated now.

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
failures are unrelated.

looks like https://github.com/cms-sw/cmssw/pull/44641 was merged without the corresponding external update, there are widespread failures in the IB: https://cmssdt.cern.ch/SDT/html/cmssdt-ib/#/ib/CMSSW_14_1_X

**Comment by mmusich** [comment]
@cmsbuild, please test
   * new IB should be fixed.

**Comment by mmusich** [comment]
> That needs to be added. Can you please point me to the place where I should insert it?

without having tested it. 

https://github.com/cms-sw/cmssw/blob/6e82cc8aa6fff019b94eb34a5b5297c2eaa62573/Configuration/PyReleaseValidation/python/relval_steps.py#L4300

looks a place where to put it.
Let me add that I would have naively thought that would be @cms-sw/l1-l2 (or some L1T developer's) task to do that first (before this PR).

**Comment by SohamBhattacharya** [comment]
> > That needs to be added. Can you please point me to the place where I should insert it?
> 
> without having tested it.
> 
> https://github.com/cms-sw/cmssw/blob/6e82cc8aa6fff019b94eb34a5b5297c2eaa62573/Configuration/PyReleaseValidation/python/relval_steps.py#L4300
> 
Adding L1P2GT there now works -- tested with WF 24834.0

> looks a place where to put it. Let me add that I would have naively thought that would be @cms-sw/l1-l2 (or some L1T developer's) task to do that first (before this PR).

**Comment by mmusich** [comment]
test parameters:
   * workflow = 24834.78
   * relvals_opt = --what cleanedupgrade,standard,highstats,pileup,generator,extendedgen,production,identity,ged,machine,premix,nano,gpu,2017,2026

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
> DQMHistoTests: [Total failures: 6038](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_14_1_X_2024-04-17-1100+e804a0/62396/validateJR.html)

there is a lot of comparison failures in wf [11634.0](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_14_1_X_2024-04-17-1100+e804a0/62396/validateJR//11634.0_TTbar_14TeV+2021/all_mini_RECO_step3_inMINIAODSIM), which is a Run3 (2021) workflow and thus cannot be possibly affected in any way from this PR. In addition I have seen the same kind of comparison failures in more than one PR. I believe this workflow is experiencing some sort of intrinsic instability in the current IB.

**Comment by SohamBhattacharya** [comment]
Apart from the unrelated differences mentioned my @mmusich, it looks fine to me. TriggerResults show the modified paths haven't gained/lost events.

**Comment by aloeliger** [comment]
@SohamBhattacharya Thanks for taking a look at this.

**Comment by aloeliger** [comment]
+l1
- just to keep this moving along, L1T is fine with these changes.

**Comment by srimanob** [comment]
+Upgrade

**Comment by mmusich** [comment]
@cms-sw/pdmv-l2 your signature is required here

**Comment by mmusich** [comment]
> there is a lot of comparison failures in wf [11634.0](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_14_1_X_2024-04-17-1100+e804a0/62396/validateJR//11634.0_TTbar_14TeV+2021/all_mini_RECO_step3_inMINIAODSIM), which is a Run3 (2021) workflow and thus cannot be possibly affected in any way from this PR. In addition I have seen the same kind of comparison failures in more than one PR. I believe this workflow is experiencing some sort of intrinsic instability in the current IB.

just for the record, this was tracked in https://github.com/cms-sw/cmssw/issues/44779

**Comment by AdrianoDee** [comment]
+pdmv

**Comment by rappoccio** [comment]
+1

**Pull request merged**
