### PR TITLE
Remove Obsolete Code

### PR DESCRIPTION
**Pull request by ianna**
- Clean up dependencies
- Update tutorial
- Remove commented out code
- Remove obsolete/unused code

### CODE REVIEW

**Comment by ianna** [comment]
+1

**Comment by ianna** [comment]
@cmsbuild - it looks like a problem with IB - I do not see CondCore/CondDB package built or even mentioned.

**Comment by smuzaffar** [comment]
yes, there was problem with last IB due to coral. Today's 11h00 IB 
should have the fix.

**Comment by ianna** [comment]
@smuzaffar - thanks! I hope, the tests will be re-triggered.

**Comment by ianna** [comment]
+1

**Comment by smuzaffar** [comment]
please test

**Comment by ianna** [comment]
@cmsbuild  - the unit tests fail due to another PR problem:
```
class  HGCEEDetId found in libDataFormatsHGCDigi.so  is already in libDataFormatsForwardDetId.so 
```

**Comment by smuzaffar** [comment]
yes looks like #9166 has caused this and these unit tests are failing in the IB already.
@davidlange6 , this pull request can be included we need to fix the changes/duplicates introduced in #9166

**Pull request merged**
