### PR TITLE
FWCore/MessageService/test: Fix output options on standAlone_1.sh script

### PR DESCRIPTION
**Pull request by gartung**

### CODE REVIEW

**Comment by gartung** [comment]
please test

**Comment by gartung** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by smuzaffar** [comment]
@gartung , I have proposed a fix for the shell script to get standAloneWithMessageLogger from PATH ( see my comment here https://github.com/cms-sw/cmssw/pull/27212#issuecomment-503428075 ).

We also needed 
```
  <flags PRE_TEST="standAloneWithMessageLogger"/>
```
to make sure that standAloneWithMessageLogger is built before tandAloneWithMessageLoggerRunner

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
+core

**Comment by fabiocos** [comment]
+1

**Pull request merged**
