### PR TITLE
Revert "Move L1Trigger/CSCTrackFinder/src/core_ files to external package"

### PR DESCRIPTION
**Pull request by davidlange6**
Reverts cms-sw/cmssw#13866

### CODE REVIEW

**Comment by smuzaffar** [comment]
Do not revert it now. I think I have a fix which fixes workflow 27. I am testing it locally by building full release.

**Comment by davidlange6** [comment]
causing memory corruption in the release it seems

**Comment by davidlt** [comment]
The easiest solution is to remove all the hacks and just do e.g., `std::getenv("CMSSW_RELEASE_BASE") +  "/external/" + std::getenv("SCRAM_ARCH") + "/data/" + L1Trigger/CSCTrackFinder/data/core_2014_05_15/comp_dphi_8.dat"` or similar in the external.

**Comment by smuzaffar** [comment]
@davidlt , I like the idea

**Comment by davidlange6** [comment]
ah - sorry - i missed your comments
we can just revert the revert....

**Comment by smuzaffar** [comment]
no need to re-revert. I just wanted that revert does not go in the history of git. 
Anyway, as it is now in so just leave it there for next IB. It will give me more time for tests :-)

**Pull request merged**
