### PR TITLE
[Protobuf update] Bump to 3.11.3

### PR DESCRIPTION
**Pull request by mrodozov**
#### PR description:

Updates the protobuf files as described here 
https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_11_1_X/master/protobuf.spec#L8

#### PR validation:

It compiles with the new protobuf

### CODE REVIEW

**Comment by mrodozov** [comment]
@hqucms any suggestion how to "remake" the model.onnx or use another file , does this file "version" has anything to do with protobuf maybe ? 
it says:
`"- Failed to load model with error: Unknown model file format version."`
suggesting it has some versioning issues (although I don't think it should)

**Comment by hqucms** [comment]
@mrodozov The file version is not related to protobuf -- I tried to load the model.onnx w/ onnxruntime 1.2.0 from pypi and it reports the same error. 
I will replace the model to another one.

**Comment by hqucms** [comment]
@mrodozov 
I replaced the model in https://github.com/cms-sw/cmssw/pull/29510.

**Comment by jfernan2** [comment]
There are many warnings, are they expected?

**Comment by smuzaffar** [comment]
@jfernan2 , no these are not expected. @mrodozov can you please look in to this and provide a fix for warning such as
```
  CMSSW_11_1_X_2020-04-22-2300/src/DQMServices/Components/bin/fastHadd.cc:277:56: warning: 'void google::protobuf::io::CodedInputStream::SetTotalBytesLimit(int, int)' is deprecated: Please use the single parameter version of SetTotalBytesLimit(). The second parameter is ignored. [-Wdeprecated-declarations]
    input_coded.SetTotalBytesLimit(1024 * 1024 * 1024, -1);

```

there are 4 of such warnings.

**Comment by smuzaffar** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by smuzaffar** [comment]
@silviodonato , looks like this (along with  cms-sw/cmsdist#5743 ) is ready to go it. Hopefully this should fix PowerPC IBs.

**Comment by silviodonato** [comment]
+1

**Pull request merged**
