### PR TITLE
More flexible SOI handling

### PR DESCRIPTION
**Pull request by igv4321**
Added more flexible handling of SOI (sample of interest) so that the case of SOI=5 will be correctly handled. This is expected due to the impending change of SiPM dark current modelling in MC, where placement of SOI at a later time slice allows for skipping two initial time slices at which the dark current is not well modelled (as there is not enough history).

This change is not supposed to modify any test results.

The usual "runTheMatrix" sequence was run to validate.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by abdoulline** [comment]
NB: during Run1 we have had several HCAL modules with "precession" (unstability) of the clock synchronization wrt LHC clock. So that their SOI was moving back and force in TS range=(3,5). 
We did discuss this in the past in several PRs...
And once this PR add a special case with SOI=5 for our coming (soon) modification of MC Data frame size (with SOI=5) for >=Run3, it's "sensitive" to this Run1 problem.
I suppose it's not a showstopper.

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/28948	12f899b 
- code changes are in line with the PR description. The sample/range selection looks more appropriate now even for the drifting channels from Run 1.
- jenkins tests pass and comparisons with the baseline show differences only in Run 1 data tests, which are affected by the drifting channels mentioned in https://github.com/cms-sw/cmssw/pull/28948#issuecomment-585990138

**Comment by silviodonato** [comment]
>  And once this PR adds a special case with SOI=5 for our coming (soon) modification of MC Data frame size (with SOI=5) for >=Run3, it's "sensitive" to this old Run1 problem.

Could you give more details on this? Merging this PR, will we get a better or worse data(run1)/MC agreement?

**Comment by abdoulline** [comment]
@silviodonato 
Flexibility in general sounds better :) 
Now, in particular (for this Run1 issue)  - when in the data SOI happens to arrive to TS=5, with this PR it can be handled, which wasn't the case before. 
So, with this PR it becomes better, albeit it doesn't fully cure the Run1  issue, as the timing alignment was seamless/gradual (rather constant "precession" than quantized jumping between TS' 3,4,5)

**Comment by silviodonato** [comment]
+1
thanks

**Pull request merged**
