### PR TITLE
[14_0_X] Fix crash in PF Clustering due to empty HCAL RecHits collection

### PR DESCRIPTION
**Pull request by jsamudio**
#### PR description:

This fix addresses https://github.com/cms-sw/cmssw/issues/44668 where Alpaka-based PF Clustering was crashing at HLT when HCAL is off. The reason was due to the input HCAL RecHit number being used to specify the work division for kernels, and it was not protected against a case of requesting 0 blocks when there are no RecHits.

Included now are checks on the number of rechits and the SoA size to only launch the Alpaka kernels if they are non-zero.

#### PR validation:

Tested HLT configuration on data which is excluding HCAL, ECAL, or Pixel, using method outlined by @mmusich in https://github.com/cms-sw/cmssw/issues/44668#issuecomment-2045506118

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Verbatim backport of https://github.com/cms-sw/cmssw/pull/44693 meant for `14_0_X`. Needed to address https://github.com/cms-sw/cmssw/issues/44668 at HLT.

### CODE REVIEW

**Comment by mmusich** [comment]
backport of https://github.com/cms-sw/cmssw/pull/44693

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
type pf

**Comment by saumyaphor4252** [comment]
urgent
- Requested on behalf of HLT for data-taking operations
- To be included in 14_0_5

FYI @cms-sw/orp-l2 

Saumya 
(ORM)

**Comment by saumyaphor4252** [comment]
type bug-fix

**Comment by antoniovilela** [comment]
> urgent
> 
> * Requested on behalf of HLT for data-taking operations
> * To be included in 14_0_5
> 
> FYI @cms-sw/orp-l2
> 
> Saumya (ORM)

We will build a patch on top of 14_0_5 with this in.

**Comment by mmusich** [comment]
enable gpu

**Comment by mmusich** [comment]
test parameters:
   * workflow_opts_gpu= -w upgrade
   * workflows_gpu=12434.422, 12434.423,12434.424,12434.492

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mandrenguyen** [comment]
+`

**Comment by mandrenguyen** [comment]
+1
Let's try that again

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
