### PR TITLE
[DD4hep] Enable Run 3 DD4hep DB workflow with correct GT for PR & IB tests

### PR DESCRIPTION
**Pull request by cvuosalo**
Since Run 3 DD4hep workflows reading geometry from the DB are now functional, such a workflow can be added to the PR and IB tests.

11634.912 (ttbar) had been previously defined but left disabled. This PR enables this workflow for PR/IB tests. The GT for this workflow is also corrected.

#### PR validation:

The workflow runs successfully with: `runTheMatrix.py -l 11634.912 --ibeos`

### CODE REVIEW

**Comment by kskovpen** [comment]
+1

**Comment by srimanob** [comment]
Please test

**Comment by srimanob** [comment]
+Upgrade

The new workflow is running fine. I think if it enters IB and can run smoothly, it should be good to be relvals. I understand that GT that PdmV should use for relvals is `120X_mcRun3_2021_realistic_dd4hep_v1`
@cvuosalo @cms-sw/pdmv-l2

**Comment by qliphy** [comment]
+1

**Pull request merged**
