### PR TITLE
[10.2.X] GBRForest implementation without TMVA

### PR DESCRIPTION
**Pull request by guitargeek**
#### PR description:

Backport of https://github.com/cms-sw/cmssw/pull/24432 and subsequent fix https://github.com/cms-sw/cmssw/pull/25085 and adaption of the LowPtGsfElectron reconstruction code to the moved GBRForestTools.

This should resolve urgent issue https://github.com/cms-sw/cmssw/issues/26154.

Depends on external https://github.com/cms-sw/cmsdist/pull/4777.

Files with rebase conflicts that I had to solve manually:
* Here I just took the changes from 24432
  * RecoParticleFlow/PFProducer/plugins/PFEGammaProducer.cc
  * RecoParticleFlow/PFProducer/interface/PFEGammaAlgo.h
  * RecoParticleFlow/PFProducer/src/PFEGammaAlgo.cc
  * RecoEgamma/PhotonIdentification/plugins/PhotonMVAEstimator.cc
  * RecoEgamma/PhotonIdentification/interface/PhotonMVAEstimator.h
  * RecoEgamma/ElectronIdentification/plugins/ElectronIDValueMapProducer.cc
  * RecoEgamma/PhotonIdentification/plugins/PhotonIDValueMapProducer.cc

* These files were changed by another PR in the 10_3_X dev cycle (https://github.com/cms-sw/cmssw/pull/24131) before the PR to backport. I just took the code from master here to keep things easy:
  * RecoEgamma/ElectronIdentification/src/ElectronMVAEstimator.cc
  * RecoEgamma/ElectronIdentification/src/SoftElectronMVAEstimator.cc
  * RecoEgamma/ElectronIdentification/interface/ElectronMVAEstimator.h
  * RecoEgamma/ElectronIdentification/interface/SoftElectronMVAEstimator.h

#### PR validation:

Code compiles and local matrix tests pass.

If you want to test the PR locally as well, there are some extra steps needed besides the usual `git cms-merge-topic` or `git cms-rebase-topic`:
1. Get tinyxml2 [1] and put tinyxml2.h and tinyxml2.cc into CommonTools/MVAUtils/src/
2. Change `#include <tinyxml2.h>` in the GBRForestTools [2] to `#include "tinyxml2.h"`
3. Go into `RecoParticleFlow/PFProducer`, clone https://github.com/cms-data/RecoParticleFlow-PFProducer and rename the cloned repository to `data`.

[1] https://github.com/leethomason/tinyxml2
[2] https://github.com/cms-sw/cmssw/blob/master/CommonTools/MVAUtils/src/GBRForestTools.cc#L10

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test with cms-sw/cmsdist#4777

**Comment by guitargeek** [comment]
Yes, I will look into that. I also got the matrix tests running now on the SL6 machine available to me, so I will do my own testing of both options and then come back to these PRs.

**Comment by guitargeek** [comment]
So this test will fail I realized: the backport missed changing the weights files names in RecoParticleFlow, because the location of this configuration moved in the meantime. I fixed this now and also got my own matrix tests to run again, which all passed.

The full backport should be hereby ready, and I will check now how to realize a minimal solution.

**Comment by guitargeek** [comment]
I expected the matrix tests to fail, but the unit tests are another story. This is unexpected and probably not related to this PR. I hope that problem does not show up in the minimal solution... Anyway I fixed the matrix tests as I said, and probably it makes sense to test this PR again to have at least one tested solution ready.

**Comment by slava77** [comment]
@cmsbuild please test with cms-sw/cmsdist#4777

**Comment by slava77** [comment]
-1

it looks like a simple recipe based on #26176 works. So, this more extensive backport is not needed.

**Comment by guitargeek** [comment]
Reshuffling commits a little bit such that this can be merged on top of https://github.com/cms-sw/cmssw/pull/26176 if needed. Closing this PR.

**Pull request closed without merging**
