### PR TITLE
Updating MET Significance Parameters with 80X Run2016 tune

### PR DESCRIPTION
**Pull request by danbarto**
Updating the parameters for MET Significance with the latest tune (as used in JME-17-001).

### CODE REVIEW

**Comment by perrotta** [comment]
backport of #22315

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
please test
(the usual glitch with no indication about which AddOn test failed?)

**Comment by perrotta** [comment]
+1
- Identical to #22315, already merged in the master
- MET significance parameters are updated in miniAOD following the latest prescriptions of the MET group: meant to re-miniAODv2

**Comment by slava77** [comment]
hold

@perrotta 
changes made so far for 94X miniAOD were either additions [free to go] or changes to standard objects restricted by eras/modifiers run2_miniAOD_94XFall17 and run2_miniAOD_80XLegacy.
IIUC, this PR changes the default values of MET for everything.
It looks like in this case we can leave the backport restricted to the two eras/modifiers as well.

**Comment by perrotta** [comment]
My understanding was that reproducibily of miniAOD v1 was not granted with the new release.
But ok: if it is as Slava says I'm going to retract my "+1" here, and please @danbarto make the configuration depend on the era and allow the new one only for run2_miniAOD_94XFall17 and run2_miniAOD_80XLegacy in this 94_MAODX backport.

**Comment by perrotta** [comment]
Updated comment in https://github.com/cms-sw/cmssw/pull/22347#issuecomment-370129154: cancelled the "+1"

**Comment by slava77** [comment]
unhold

**Comment by danbarto** [comment]
Hi @perrotta, is there an example for an era dependent switch? I'm not quite sure what to do exactly. Thanks for your help!

**Comment by perrotta** [comment]
With a grep in the release I can find a possible example in ```RecoEgamma/EgammaPhotonProducers/python/reducedEgamma_cfi.py```

In your case, you can restore the previous values of the parameters, and then replace the new ones as, e.g.:
```
from Configuration.Eras.Modifier_run2_miniAOD_80XLegacy_cff import run2_miniAOD_80XLegacy
#Run II MC, based on 80X
run2_miniAOD_80XLegacy.toModify(METSignificanceParams,
   jpar = cms.vdouble(1.39,1.26,1.21,1.23,1.28),
   pjpar = cms.vdouble(-0.2586,0.6173)
)
#Run II data, based on 80X
run2_miniAOD_80XLegacy.toModify(METSignificanceParams_Data,
   jpar = cms.vdouble(1.38,1.28,1.22,1.16,1.10),
   pjpar = cms.vdouble(0.0033,0.5802)
)
from Configuration.Eras.Modifier_run2_miniAOD_94XFall17_cff import run2_miniAOD_94XFall17
#Run II MC, based on 80X
run2_miniAOD_94XFall17.toModify(METSignificanceParams,
   jpar = cms.vdouble(1.39,1.26,1.21,1.23,1.28),
   pjpar = cms.vdouble(-0.2586,0.6173)
)
#Run II data, based on 80X
run2_miniAOD_94XFall17.toModify(METSignificanceParams_Data,
   jpar = cms.vdouble(1.38,1.28,1.22,1.16,1.10),
   pjpar = cms.vdouble(0.0033,0.5802)
)
```

**Comment by slava77** [comment]
the following will be more compact and will avoid unnecessary copy-paste

```python
from Configuration.Eras.Modifier_run2_miniAOD_80XLegacy_cff import run2_miniAOD_80XLegacy
from Configuration.Eras.Modifier_run2_miniAOD_94XFall17_cff import run2_miniAOD_94XFall17

for mod in [ run2_miniAOD_80XLegacy, run2_miniAOD_94XFall17]:
    mod.toModify(METSignificanceParams, 
                             jpar = [1.39,1.26,1.21,1.23,1.28],
                             pjpar = [-0.2586,0.6173])
```

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
+1
- MET significance parameters updated in miniAOD following the latest prescriptions of the MET group
- The difference wrt the same PR now merged in the master is that in this 94X backport the updates are only allowed in the run2_miniAOD_80XLegacy and run2_miniAOD_94XFall17
- The jenkns tests cerify that the modifications only appears in those eras

**Comment by fabiocos** [comment]
+1

**Pull request merged**
