### PR TITLE
Include PPS Association Cuts in data and MC GTs

### PR DESCRIPTION
**Pull request by malbouis**
This PR adds the PPS Association Cuts record in data and MC GTs as requested in https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/4507/1.html .

The record for data is: `PPSAssociationCuts_Run3_v2`
The record for MC is: `PPSAssociationCuts_Run3_v1_mc`

The GT diffs are below.

**mcRun2_startup**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mcRun2_startup_v7/121X_mcRun2_startup_v8

**mcRun2_asymptotic_l1stage1**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mcRun2_asymptotic_l1stage1_v7/121X_mcRun2_asymptotic_l1stage1_v8

**mcRun2_design**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mcRun2_design_v7/121X_mcRun2_design_v8

**mcRun2_asymptotic_preVFP**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mcRun2_asymptotic_preVFP_v7/121X_mcRun2_asymptotic_preVFP_v8

**mcRun2_asymptotic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mcRun2_asymptotic_v7/121X_mcRun2_asymptotic_v8

**mcRun2cosmics_asymptotic_deco**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mcRun2cosmics_asymptotic_deco_v7/121X_mcRun2cosmics_asymptotic_deco_v8

**mcRun2_HeavyIon**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mcRun2_HeavyIon_v7/121X_mcRun2_HeavyIon_v8

**mcRun2_pA**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mcRun2_pA_v7/121X_mcRun2_pA_v8

**dataRun2**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_dataRun2_v11/121X_dataRun2_v9

**dataRun2_HEfail**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_dataRun2_HEfail_v11/121X_dataRun2_HEfail_v10

**dataRun2_relval**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_dataRun2_relval_v10/121X_dataRun2_relval_v11

**dataRun2_PromptLike_HI**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_dataRun2_PromptLike_HI_v10/121X_dataRun2_PromptLike_HI_v9

**dataRun3_HLT**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_dataRun3_HLT_v11/121X_dataRun3_HLT_v9

**dataRun2_HLT_relval**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_dataRun2_HLT_relval_v11/121X_dataRun2_HLT_relval_v9

**dataRun3_Express**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_dataRun3_Express_v10/121X_dataRun3_Express_v11

**dataRun3_Prompt**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_dataRun3_Prompt_v10/121X_dataRun3_Prompt_v9

**dataRun3**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_dataRun3_v10/121X_dataRun3_v8

**mc2017_design**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mc2017_design_v7/121X_mc2017_design_v9

**mc2017_realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mc2017_realistic_v7/121X_mc2017_realistic_v9
     
**mc2017cosmics_realistic_deco**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mc2017cosmics_realistic_deco_v7/121X_mc2017cosmics_realistic_deco_v9

**mc2017cosmics_realistic_peak**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mc2017cosmics_realistic_peak_v7/121X_mc2017cosmics_realistic_peak_v9

**upgrade2018_design**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_upgrade2018_design_v7/121X_upgrade2018_design_v8

**upgrade2018_realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_upgrade2018_realistic_v7/121X_upgrade2018_realistic_v8

**upgrade2018_realistic_RD**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_upgrade2018_realistic_RD_v7/121X_upgrade2018_realistic_RD_v8

**upgrade2018_realistic_HI**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_upgrade2018_realistic_HI_v7/121X_upgrade2018_realistic_HI_v8

**upgrade2018_realistic_HEfail**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_upgrade2018_realistic_HEfail_v7/121X_upgrade2018_realistic_HEfail_v8

**upgrade2018cosmics_realistic_deco**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_upgrade2018cosmics_realistic_deco_v10/121X_upgrade2018cosmics_realistic_deco_v9

**upgrade2018cosmics_realistic_peak**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_upgrade2018cosmics_realistic_peak_v7/121X_upgrade2018cosmics_realistic_peak_v8

**mcRun3_2021_design**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mcRun3_2021_design_v13/121X_mcRun3_2021_design_v15

**mcRun3_2021_realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mcRun3_2021_realistic_v15/121X_mcRun3_2021_realistic_v17

**mcRun3_2021cosmics_realistic_deco**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mcRun3_2021cosmics_realistic_deco_v15/121X_mcRun3_2021cosmics_realistic_deco_v17

**mcRun3_2021_realistic_HI**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mcRun3_2021_realistic_HI_v15/121X_mcRun3_2021_realistic_HI_v17

**mcRun3_2023_realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mcRun3_2023_realistic_v14/121X_mcRun3_2023_realistic_v16

**mcRun3_2024_realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mcRun3_2024_realistic_v14/121X_mcRun3_2024_realistic_v16

**mcRun4_realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mcRun4_realistic_v7/121X_mcRun4_realistic_v8

#### PR validation:

runTheMatrix.py -l limited,145,1325.516,281,1307,10424,7.21,11224,11024.2,250200.182,7.4,12034,7.23,12834,23234,138.2,138.1,136.8642,136.88811,136.897,11925 --ibeos -j16

It was tested together with PR #35766 

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

No backport is foreseen

### CODE REVIEW

**Comment by tvami** [comment]
+alca
  * unit test failure is know and is irrelevant
  * other test pass
  * probably it would have been better to have a Run-2 specific tag for the Run-2 GTs, but it's not used in Run-2 so it's somewhat irrelevant

**Comment by tvami** [comment]
Hi @qliphy this PR can go in first, we dont need to wait for https://github.com/cms-sw/cmssw/pull/35766
I'm wondering if you are fine merging this with the bad unit test, since it's a known ongoing issue (that will prob not get resolved over the weekend)?

**Comment by qliphy** [comment]
merge

**Comment by mmusich** [comment]
after this has been merged there are PR test errors:
https://github.com/cms-sw/cmssw/pull/35909#issuecomment-955305201

**Comment by mmusich** [comment]
> can go in first, we dont need to wait for #35766

This is not correct, this PR succeeded integration tests because it was tested together with  #35766 (as that PR removes the duplicated record insertion). 
The removal of the `ESSource` should have been done in this PR.

**Comment by francescobrivio** [comment]
> > can go in first, we dont need to wait for #35766
> 
> This is not correct, this PR succeeded integration tests because it was tested together with #35766 (as that PR removes the duplicated record insertion), see [#35914 (comment)](https://github.com/cms-sw/cmssw/pull/35914#issuecomment-954886569). The removal of the `ESSource` should have been done in this PR.

@tvami can you include this fix in your PR https://github.com/cms-sw/cmssw/pull/35909 ? we need to fix the broken IB asap

**Comment by tvami** [comment]
We discussed with @francescobrivio privately that what I'd need to include is already in https://github.com/cms-sw/cmssw/pull/35766 so we should make that go in asap, so I made that PR `urgent`. Sorry for not realizing that these were not independent.

**Pull request merged**
