### PR TITLE
Phase2-hgx247 Add a few new features for HGCal

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Add a few new features for HGCal and extend some methods in view of partial wafer

#### PR validation:

Use runTheMatrix test workflows

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
+1

**Comment by bsunanda** [comment]
Close this PR in view of PR #30323

**Pull request closed without merging**
