### PR TITLE
[NanoAOD, JMENanoAOD] Backport of #33824 (Remove jercVars variables, update puId config) to 11_2_X

### PR DESCRIPTION
**Pull request by nurfikri89**
Backport from #33824

#### PR description:

This PR aims to 

- Remove certain jercVars variables from the main NanoAOD but still keep them in the JMENano.
- Update configurations for pileup Id in JMENano.

With this PR, the event size for the main Nano is reduced  from **2.90 kb/event** to **2.86 kb/event**.  The comparison was made using 5K events from a TTJets RunIISummer20UL17MiniAODv2 sample. No event size changes for JMENano.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:
Original PR is #33824

### CODE REVIEW

**Comment by mariadalfonso** [comment]
please test 
(we need backport only on 10_6)

**Comment by nurfikri89** [comment]
@mariadalfonso ok. Should I close this PR?

**Comment by mariadalfonso** [comment]
+xpog

backport inline with master
(not strictly needed backport in 11_2 but can be useful if jmenano will be produced in 11-2 in the future)

**Comment by qliphy** [comment]
+1

**Pull request merged**
