### PR TITLE
Migrate some modules in RecoMET to esConsumes()

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

Part of #31061. These ones are fairly straightforward.

#### PR validation:

~~Code compiles.~~ Limited matrix runs.

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
@cmsbuild, please test

(limited matrix ran in a private test)

**Comment by slava77** [comment]
+reconstruction

for https://github.com/cms-sw/cmssw/pull/34943	022f847 
- code changes are technical, in line with the PR description
- jenkins tests pass

**Comment by qliphy** [comment]
+1

**Pull request merged**
