### PR TITLE
MTD Geometry: updated GeometricTimingDet to remove the residual dependency on DDSolidShape

### PR DESCRIPTION
**Pull request by fabiocos**
#### PR description:

This PR is a follow-up of #29905 as mentioned in https://github.com/cms-sw/cmssw/issues/28914#issuecomment-659680418 . The residual dependence of GeometricTimingDet on the DDD class ```DDSolidShape``` is removed through the provided map, and ```cms::DDSolidShape``` is now used. No impact is expected outside of ```Geometry/MTDNumberingBuilder```.

#### PR validation:

The MTD geometry unit tests are ok, test wf 23234.0 runs smoothly. The full output of the ```MTDNumberingBuilder``` test shows the expected change in shape of polycones:

```
71c71
<  shape = DDSolidShape index:5, name: Polycone_rz
---
>  shape = DDSolidShape index:7, name: Polycone_rrz
127c127
<  shape = DDSolidShape index:5, name: Polycone_rz
---
>  shape = DDSolidShape index:7, name: Polycone_rrz
183c183
<  shape = DDSolidShape index:5, name: Polycone_rz
---
>  shape = DDSolidShape index:7, name: Polycone_rrz
```

which anyway should have no practical effect on the model built in memory and its use.

### CODE REVIEW

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
the failure looks unrelated to this PR

**Comment by cvuosalo** [comment]
@fabiocos The output you show does not look right:
```
<  shape = DDSolidShape index:5, name: Polycone_rz
---
>  shape = DDSolidShape index:7, name: Polycone_rrz
```
I'm not sure of the context. Can you please explain this output some more?

**Comment by fabiocos** [comment]
@cvuosalo the test https://cmssdt.cern.ch/lxr/source/Geometry/MTDNumberingBuilder/test/mtd_cfg.py dumps all the properties of the ```GeometricTimingDet``` objects describing MTD, including the shape of each volume:

https://cmssdt.cern.ch/lxr/source/Geometry/MTDNumberingBuilder/test/GeometricTimingDetAnalyzer.cc#0155

For the top level volumes of the hierarchy, ```BarrelTimingLayer``` and ```EndcapTimingLayer``` this is a. polycone (for the time being, we will update ETL), and there is a change in its code, coherent with the DDD - DD4hep map provided by @ianna 
This does not appear in the regular unit test, which uses a compact output for reference size reasons, but is visible when comparing the full output of the test.

**Comment by fabiocos** [comment]
please test

**Comment by cvuosalo** [comment]
@fabiocos The output you showed is still not quite explained by the code you referenced, since the code line is:
```
shape = " << det->shape() << "\n\n"
```
while the output says "shape = DDSolidShape index:5, name: Polycone_rz".
But what I really want to check is that, from previous version to this PR, the enum value goes from 7 -> 5. If the value goes 5-> 7, then something strange is happening.

**Comment by fabiocos** [comment]
@cvuosalo concerning the printout, if you check the implementation of the ```<<``` operator for solid shapes https://cmssdt.cern.ch/lxr/source/DetectorDescription/Core/src/DDSolid.cc#0030 you see the format shown above.

The output is a diff between the new (5) and the old (7) output, you may easily verify it yourself by running https://cmssdt.cern.ch/lxr/source/Geometry/MTDNumberingBuilder/test/mtd_cfg.py for scenario D53 . Shape n. 7 is no more implemented as a polycone, do you agree?

**Comment by cvuosalo** [comment]
+1

**Comment by cvuosalo** [comment]
@fabiocos Thanks for the explanation and thanks for taking care of this issue.

**Comment by kpedro88** [comment]
+upgrade

**Comment by silviodonato** [comment]
+1

**Pull request merged**
