### PR TITLE
Undo update of Run-3 GTs in autoCondHLT

### PR DESCRIPTION
**Pull request by missirol**
#### PR description:

This PR reverts #35207, as that now conflicts with #35593 (see https://github.com/cms-sw/cmssw/pull/35593#issuecomment-939180555).

Keeping it as draft PR until @Martin-Grunewald can review.

#### PR validation:

No errors after running `addOnTests.py --tests=hlt_data_GRun` with #35593.

#### If this PR is a backport, please specify the original PR and why you need to backport that PR:

N/A

### CODE REVIEW

**Comment by missirol** [comment]
I first wanted to test this without #35593. In parallel, the latter can test with this one.

**Comment by missirol** [comment]
Differences in wf `11634.911` are not likely to be related to these changes. I don't know the reason, but this reminded of https://github.com/cms-sw/cmssw/issues/32963.

**Comment by tvami** [comment]
It must be some temporary glitch, our AlCa PR tested with this is very clean: 
https://github.com/cms-sw/cmssw/pull/35593#issuecomment-939352844

**Comment by Martin-Grunewald** [comment]
Sorry, why do we need this (rather than adding missing ES modules)?

**Comment by francescobrivio** [comment]
> Which data taking period is `runs > 342663`?

@Martin-Grunewald  sorry the run is actually 342670 ([OMS link](https://cmsoms.cern.ch/cms/runs/report?cms_run=342670&cms_run_sequence=GLOBAL-RUN)) which is the first run of CRUZET2021.

**Pull request merged**
