### PR TITLE
DT DQM legacy modules removal

### LINKED ISSUE #25090: Modules prohibiting concurrent lumis in RelVal workflows
I took the expanded python output from all of the gen-sim step of runTheMatrix jobs. From that I got a list of module names. Attached in the list of modules and their base class. There are two legacy modules, one EDAnalyzer and one EDFilter. 
EDAnalyzer MEtoMEComparitor
EDFilter CosmicGenFilterHelix

[gen-sim-modules.txt](https://github.com/cms-sw/cmssw/files/2539527/gen-sim-modules.txt)

### PR DESCRIPTION
**Pull request by jfernan2**
#### PR description:

This PR tries to asses the issue https://github.com/cms-sw/cmssw/issues/25090  in what concerns DT DQM Legacy modules.

The four conflicting classes:

DTDataIntegrityTask
DTDCSByLumiTask
DTResolutionAnalysisTask
DTSegmentAnalysisTask

are reconfigured to clear any conflicting module with concurrent LS or dropped their usage from DQM Offline configurations, leaving all the vs LS plots ONLY for DQM Online and removing them from DQM Offline.

The results imply a drop of 71 plots from workflows. Some other cleaning of the code has been done in parallel

#### PR validation:

Tested for DQM Online stand alone and with:

runTheMatrix.py -l limited

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

No backport is foreseen

(Partially) Resolves #25090

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
hold
A non seen issue with a summary plot to be investigated

**Comment by jfernan2** [comment]
unhold

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
please test with #29826

**Comment by jfernan2** [comment]
please abort

**Comment by jfernan2** [comment]
please test with #29826

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+dqm
Changes as expected

**Comment by silviodonato** [comment]
+1

**Pull request merged**
