### PR TITLE
Fixed segmentation violation in PhysicsTools/SelectorUtils/interface/PFJetIDSelectionFunctor in case subjets are of type pat::Jet

### PR DESCRIPTION
**Pull request by veelken**
fixed segmentation violation that occurred in subjet analyses in case a pat::Jet had daughters of type pat::Jet
(previous code only handled the case that daughters of pat::Jet were of type reco::PFJet)

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
please @veelken : replace the title of this PR with something a bit more descriptive

**Comment by veelken** [comment]
I have updated the title

**Comment by perrotta** [comment]
backport of #22298

**Comment by perrotta** [comment]
+1
- Identical to #22298 in the master
- The fix acts as wanted
- No differences expected in jenkins tests, none observed

**Comment by arizzi** [comment]
@fabiocos as the master equivalent is now merged please consider also merging this as it is needed for analysis (if there is any reason against that let us know and we will move this PR on the AN branch)

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Pull request merged**
