### PR TITLE
Fix 2016 FG bit as MB trigger

### PR DESCRIPTION
**Pull request by icali**
This update modify the FG calculation to accomodate the 2016 uHTR FW. The FG bits in 2016 are used to deliver minimum bias trigger.  Should the PR be made also for 8_1_X?

### CODE REVIEW

**Comment by nsmith-** [comment]
Will this also fill `HcalTriggerPrimitiveDigi::SOI_fineGrain(1)` for the HF TPs?
Also, is the unpacker change in the works?

**Comment by matz-e** [comment]
It'll fill that for the re-emulation. I haven't seen the FG bit set that way looking at data so far.

**Comment by civanch** [comment]
please test

**Comment by icali** [comment]
hello, I see that this pull request is still pending signatures. What is missing? what should I do to have it in the release asap?

**Comment by fwyzard** [comment]
I'd say that @mulhearn or @rekovic should sign it, and request its inclusion at the next ORP meeting - though it will likely be necessary to have #14534 integrated in 8.1.x first.

**Comment by mulhearn** [comment]
Sorry, missed this.  We just need to run our integration tests on this before signing...

**Comment by rekovic** [comment]
+1

Tests show this PR has no effect on the existing L1T functionality.

**Comment by rekovic** [comment]
For completion:
Tests of differences between L1T in vanilla CMSSW_8_0_14 and CMSSW_8_0_14+8_0_14+PR14471  reported here
http://rekovic.web.cern.ch/rekovic/cms/L1T/Stage2/l1t-integration/compare_test_CMSSW_8_0_14+PR14471-FG_MinBias_vs_test_CMSSW_8_0_14/
(i.e. There are no differences)

**Comment by davidlange6** [comment]
+1

**Pull request merged**
