### PR TITLE
[10_3_X] Strip packer: protect against invalid header types

### PR DESCRIPTION
**Pull request by pieterdavid**
Backport of https://github.com/cms-sw/cmssw/pull/25331

CC: @icali @stahlleiton @CesarBernardes @erikbutz @mmusich

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by icali** [comment]
Hi @fabiocos , 
yes, we would like indeed to ask for a patch release with this PR included.  
It would fix the HLT errors that we see now. Also if we are speaking of only few 100s events. We see that the merging timing is affected by failing jobs. 

If you agree to provide a patch release shortly, we could ask for a replay and target to have it online in already at the beginning of the week. 
Please let me know what you think being feasible/reasonable,
Cheers, 
Ivan

**Comment by perrotta** [comment]
+1
-  The fix adds the protection as announced in the PR description
-  Jenkins tests pass

**Comment by fabiocos** [comment]
+1

**Pull request merged**
