### PR TITLE
EMTF 2017 PR #2 - 2017 DataFormats

### PR DESCRIPTION
**Pull request by abrinke1**
Part 2 of set of PRs following PR #19741

Updated EMTF internal data formats for 2017, primarily adding info for RPCs, and adding new formats ("EMTFRoad") and functionalities for the upgraded EMTF emulator.

Temporarily have both 2016 and 2017 data formats at the same time, so some old and some new EMTF modules (in the intermediate PRs) can run at the same time.

Updated EMTF unpacker including several major improvements:
  * Input link monitoring in EMTFBlockCounters.cc
  * Unpack CPPF output in EMTFBlockRPC.cc
  * Significantly improved hit-to-track matching in EMTFBlockSP.cc

Still outputs empty collections of EMTFHit2016 and EMTFTrack2016 so we don't break the DQM sequences.

Changes grouped as follows:
DataFormats/L1TMuon/interface/EMTF/*.h
  * Updated unpacked objects to mirror changes in RAW EMTF DAQ output

EventFilter/L1TRawToDigi/plugins/implementations_stage2/EMTFBlockX.cc
  * Updated unpacking functions

EventFilter/L1TRawToDigi/plugins/implementations_stage2/EMTFBlockX.h
  * All deleted, not needed; match convention used by other unpacker

L1Trigger/L1TMuonEndCap/interface/TrackTools.X
  * New helper functions

### CODE REVIEW

**Comment by rekovic** [comment]
please test

**Comment by rekovic** [comment]
oops, 
this should be tested after #19741 is merged.

**Comment by thomreis** [comment]
No it should be fine. The commit from #19741seems to be also in this PR.

**Comment by abrinke1** [comment]
Of course, it could be merged on its own, skipping #19741.  That's up to @davidlange6 et. al., I suppose.  The PRs are split up for convenience in reviewing different commits, but they are all sequential.

**Comment by dmitrijus** [comment]
+1

**Comment by rekovic** [comment]
+1

**Comment by davidlange6** [comment]
hi @abrinke1 @rekovic - two small comments
 - please avoid uint - use unsigned int (this is somehow an existing problem)
 - please add the subsystem_package name to the include guards (eg, DataFormats_L1Muon_EMTFTracks2016_h)

**Comment by abrinke1** [comment]
@davidlange6, @smuzaffar @rekovic Requested changes committed.

**Comment by davidlange6** [comment]
please test

**Comment by rekovic** [comment]
+1

**Comment by davidlange6** [comment]
merge

**Comment by abrinke1** [comment]
Thanks, @davidlange6 !

**Pull request merged**
