### PR TITLE
[80X] update ECAL TPG tags and CSC bad chambers description as per request of HIN PAG

### PR DESCRIPTION
**Pull request by mmusich**
# Summary of changes in Global Tags 
 
## RunII simulation 
 
   * **RunII Proton-Lead scenario** : [80X_mcRun2_pA_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_mcRun2_pA_v4) as [80X_mcRun2_pA_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_mcRun2_pA_v3) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/80X_mcRun2_pA_v4/80X_mcRun2_pA_v3): 
      * update ECAL TPG tag to be in synch with Moriond MC production
      * more realistic CSC bad chamber list (w.r.t 2016 data)

attn: @mandrenguyen this is as per your [request](https://hypernews.cern.ch/HyperNews/CMS/get/hi-general/3662/1/1/1.html)

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
the compilation error doesn't seem to be related to this PR

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
