### PR TITLE
Run2-hcx177 Small bug fixes in view of Phase2 HCAL

### PR DESCRIPTION
**Pull request by bsunanda**
Changes in view of Phase2 sceanrio with post TDR HGCal

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by fabiocos** [comment]
@bsunanda sorry, the title mentions Phase2, but aren't these files used also for the 2018 geometry?
No effect is observed in the tests, but is any expected? Could you please comment on the expected impact of this PR (and possibly update the initial description)?

**Comment by bsunanda** [comment]
The xml files are for Phase2 and the code has a bug fix. This fix is not going to affect any of the xml files but it was logically wrong earlier

**Comment by bsunanda** [comment]
@ianna @civanch Please approve this PR

**Comment by fabiocos** [comment]
@ianna @civanch could you please check and sign in case?

**Comment by fabiocos** [comment]
@bsunanda the title of the PR mentions PhaseII, but this code touches the HCAL geometry as far as I can see. Could you please clarify?

**Comment by ianna** [comment]
+1

**Comment by fabiocos** [comment]
+1

changes to configurations refer to post-2018 scenarios, the change in code does not affect old situations (according to @bsunanda explanation)

**Pull request merged**
