### PR TITLE
Add EcalMustacheSCParameters and EcalSCDynamicDPhiParameters [11_2_X]

### PR DESCRIPTION
**Pull request by francescobrivio**
#### PR description:
This PR is a backport of PR #32959 to add the `EcalMustacheSCParameters` and `EcalSCDynamicDPhiParameters` to 112X GTs.

The GT diffs are as follows:
**Run 2 (L1 trigger stage 1)**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_mcRun2_asymptotic_l1stage1_v2/112X_mcRun2_asymptotic_l1stage1_v3

**2016 design**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_mcRun2_design_v2/112X_mcRun2_design_v3

**2016 realistic pre-VFP era**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_mcRun2_asymptotic_preVFP_v3/112X_mcRun2_asymptotic_preVFP_v4

**2016 realistic post-VFP era**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_mcRun2_asymptotic_v3/112X_mcRun2_asymptotic_v4

**2016 cosmics (asymptotic conditions)**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_mcRun2cosmics_asymptotic_deco_v3/112X_mcRun2cosmics_asymptotic_deco_v4

**Run 2 heavy ion**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_mcRun2_HeavyIon_v2/112X_mcRun2_HeavyIon_v3

**Run 2 proton-lead**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_mcRun2_pA_v2/112X_mcRun2_pA_v3

**Offline data**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_dataRun2_v8/112X_dataRun2_v9

**Offline data (HEM failure)**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_dataRun2_HEfail_v8/112X_dataRun2_HEfail_v9

**Offline data relval**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_dataRun2_relval_v8/112X_dataRun2_relval_v9

**Prompt-like HI data**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_dataRun2_PromptLike_HI_v6/112X_dataRun2_PromptLike_HI_v7

**2017 design**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_mc2017_design_v3/112X_mc2017_design_v4

**2017 realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_mc2017_realistic_v5/112X_mc2017_realistic_v6

**2017 realistic cosmics (tracker deco mode)**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_mc2017cosmics_realistic_deco_v5/112X_mc2017cosmics_realistic_deco_v6

**2017 realistic cosmics (tracker peak mode)**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_mc2017cosmics_realistic_peak_v5/112X_mc2017cosmics_realistic_peak_v6

**2018 design**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_upgrade2018_design_v5/112X_upgrade2018_design_v6

**2018 realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_upgrade2018_realistic_v8/112X_upgrade2018_realistic_v9

**2018 heavy ion**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_upgrade2018_realistic_HI_v8/112X_upgrade2018_realistic_HI_v9

**2018 realistic (HEM15/16 failure)**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_upgrade2018_realistic_HEfail_v8/112X_upgrade2018_realistic_HEfail_v9

**2018 cosmics (tracker deco mode)**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_upgrade2018cosmics_realistic_deco_v8/112X_upgrade2018cosmics_realistic_deco_v9

**2018 cosmics (tracker peak mode)**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_upgrade2018cosmics_realistic_peak_v8/112X_upgrade2018cosmics_realistic_peak_v9

**2021 design**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_mcRun3_2021_design_v13/112X_mcRun3_2021_design_v14

**2021 realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_mcRun3_2021_realistic_v16/112X_mcRun3_2021_realistic_v17

**2021 cosmics**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_mcRun3_2021cosmics_realistic_deco_v16/112X_mcRun3_2021cosmics_realistic_deco_v17

**2021 heavy ion**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_mcRun3_2021_realistic_HI_v16/112X_mcRun3_2021_realistic_HI_v17

**2023 realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_mcRun3_2023_realistic_v16/112X_mcRun3_2023_realistic_v17

**2024 realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_mcRun3_2024_realistic_v16/112X_mcRun3_2024_realistic_v17

#### PR validation:
A technical test was performed:
`runTheMatrix.py -l limited,12024.0,7.23,159.0,12834.0,7.4,11024.2,11224.0,7.21,7.24,10424.0,136.8642,7.22,1325.516 --ibeos -j 9`

#### if this PR is a backport please specify the original PR and why you need to backport that PR:
This PR is a backport of  #32959

### CODE REVIEW

**Comment by francescobrivio** [comment]
backport #32959

**Comment by francescobrivio** [comment]
test parameters:
  - workflow = 12024.0,7.23,159.0,12834.0,7.4,11024.2,11224.0,7.21,7.24,10424.0,136.8642,7.22,1325.516

**Comment by francescobrivio** [comment]
@cmsbuild please test

**Comment by christopheralanwest** [comment]
+1

- backport consistent with PR to master
- no changes in PR comparison tests, as expected for this technical change

**Comment by francescobrivio** [comment]
@silviodonato @dpiparo @qliphy do you need more information on this PR?

**Comment by qliphy** [comment]
+1

**Pull request merged**
