### PR TITLE
Zmumu validation tool set of commits

### PR DESCRIPTION
**Pull request by usarica**
- Updated the mass fitting scripts, integration to the All-in-One tool inside Alignment/OfflineValidation
- Does not work under CMSSW_7_4_6_patch5, works under CMSSW_7_4_11 with no difficulty
- Fitting and plotting scripts work for CMSSW_7_6_0_pre4, CMSSW_7_5_2 with no problems, actual cmsRun job needs to be checked after samples are available.

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by emiglior** [comment]
@mabarrio, @maralxplus
This maybe relevant for you as well as it contains improvements in the macros fitting M(mu+mu-) mass slices for the validation.
The backports are: CMSSW_74X #11197 and CMSSW_75X #11196

**Comment by usarica** [comment]
The last commit titled "Compatibility with #10477" is supposed to fix an error from the python config file when running a job. The error was due to the deletion of some of the old models in PR #10477. No errors are seen with this version yet.

**Comment by mmusich** [comment]
please test

**Comment by usarica** [comment]
I could only see a connection issue in the error log. Is there anything I should do?

**Comment by diguida** [comment]
-1
superseded by 11828

**Pull request closed without merging**
