### PR TITLE
[10X] added exception (on failed write) to reco::details::loadTMVAWeights

### PR DESCRIPTION
**Pull request by kreczko**
Adds a `cms::Exception("CannotWriteFile")` to `reco::details::loadTMVAWeights` when the weight file cannot be written (e.g. due to missing permissions). Fixes issue #21628.

### CODE REVIEW

**Comment by perrotta** [comment]
@kreczko : please apply  the suggestion given by the code-checker as in https://github.com/cms-sw/cmssw/pull/21638#issuecomment-348981250, so that the tests can start

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
+1
- It allows the code to throw in case of failures in opening the output file, instead of just giving a segmentation fault, as pointed out in #21628

**Comment by monttj** [comment]
+1
It clearly improves the error message.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
