### PR TITLE
[90X] PV-Validation for phase-I

### PR DESCRIPTION
**Pull request by mmusich**
Few miscellaneous fixes in the PV Validation tool to better deal with phase-I data:
   * allow dynamic selection via all-in-one metadata of the eta range of the probe track
   * allow selection of tracks avoiding either the barrel or the forward pixel partitions
   * allow choice of CPE used in the track refit (avoid templates for phase-I)
   * added aggregated canvases for the resolutions and pulls 
   * add steering of plotting style from ini metadata
   * add x- and y- transverse IP projections

Plots got out of this version:
 
##  Biases
biasescanvas_2016_mc_vs_2016_data_vs_pseudo_asympt_2017_vs_2017_mc_bpix

## Resolutions
resolutionscanvas_2016_mc_vs_2016_data_vs_pseudo_asympt_2017_vs_2017_mc_bpix

## Pulls
pullscanvas_2016_mc_vs_2016_data_vs_pseudo_asympt_2017_vs_2017_mc_bpix

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
@ghellwig @franzoni @arunhep:
is there any comment on this PR? If not please this sign-off, thanks.
M.

**Comment by ghellwig** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
