### PR TITLE
pybind11 enable interface that takes argc/argv

### PR DESCRIPTION
**Pull request by davidlange6**
should address most/all errors seen in the devel IB last night.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
Neither unit test failures appear to come from this pull request.

**Comment by Dr15Jones** [comment]
+1

**Comment by davidlange6** [comment]
hi @fabiocos - this PR affects only a new package that is so far used only in the DEVEL build - it should fix the last errors there...

**Comment by davidlange6** [comment]
@fabiocos - ping..

**Comment by fabiocos** [comment]
+1

**Comment by davidlange6** [comment]
hi @fabiocos - thanks to failing unit tests you need to merge not +1

**Comment by fabiocos** [comment]
merge

forcing the merge to by-pass unit test errors which look unrelated

**Pull request merged**
