### PR TITLE
[14_1_X] Fix crash in DeDxEstimatorRekeyer

### PR DESCRIPTION
**Pull request by stahlleiton**
#### PR description:

Backport of https://github.com/cms-sw/cmssw/pull/46312

### CODE REVIEW

**Comment by mandrenguyen** [comment]
please test

**Comment by mandrenguyen** [comment]
urgent

**Comment by jfernan2** [comment]
+1

**Comment by hqucms** [comment]
+1

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
