### PR TITLE
[HLT validation and DQM] update for new EXO displaced photon + HT path for 2023 (13_0_X)

### PR DESCRIPTION
**Pull request by jalimena**
#### PR description:

backport of #41061

#### PR validation:

Using the 11634.0 ttbar workflow, I have tested that the correct histograms are produced and filled in the harvested DQM file.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

This PR is the backport of #41061. It is needed for 2023 data-taking.

### CODE REVIEW

**Comment by emanueleusai** [comment]
please test

**Comment by emanueleusai** [comment]
backport of https://github.com/cms-sw/cmssw/pull/41061

**Comment by emanueleusai** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
