### PR TITLE
Complete integration of HP beamspot workflow for PCL

### PR DESCRIPTION
**Pull request by franzoni**
backport of https://github.com/cms-sw/cmssw/pull/22299

This PR completes the work needed to feed High-Precision beamspot measurements out of PCL to the LHC.

Dedicated workflow names are introduced duplicating the config. w.r.t to the normal workflow to allow for customization of the selections dropping confusing customization functions. (eventually we might drop the old version).

Relvals and ConfigDP tests are updated accordingly.

### CODE REVIEW

**Comment by franzoni** [comment]
Backport of #22299

**Comment by franzoni** [comment]
please test

**Comment by franzoni** [comment]
@cerminar @sarafiorendi @rmanzoni 
This is to test the Tier-0 handling of massi files already w/ 10_0

**Comment by lpernie** [comment]
+1

**Comment by fabozzi** [comment]
+1

**Comment by fabiocos** [comment]
+operations

**Comment by fabiocos** [comment]
@kpedro88 this PR is needed for test at P5, could you please check and sign or comment?

**Comment by kpedro88** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
