### PR TITLE
CSC DQM CSCMonitorModule fix for missing histo text labels

### PR DESCRIPTION
**Pull request by barvic**
CSC DQM CSCMonitorModule fix for missing histo labels in recent CMSSW/DQM releases
- Fixes issue with parsing of histograms booking configuration file with 'xml strings with spaces', which caused missing text labels on DQM histograms/plots

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by barvic** [comment]
@jfernan2 Is it just recent runTheMatrix timeout related error? I see that other PRs failed with similar messages as well.
Could be tests for this PR started again, when the error is fixed?

**Comment by jfernan2** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
