### PR TITLE
[HLT validation and DQM] update for new EXO displaced photon + HT path for 2023 (13_1_X)

### PR DESCRIPTION
**Pull request by jalimena**
#### PR description:

This PR updates the HLT validation and offline DQM for a new EXO displaced photon + HT path for 2023. It also cleans up the monitoring of photon +HT paths that have been dropped in the 2023 menu.

As a result of this PR, some DQM plots will be removed, and some will be added (more histograms removed than added).

#### PR validation:

Using the 11634.0 ttbar workflow, I have tested that the correct histograms are produced and filled in the harvested DQM file.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

This PR will be backported to 13_0_X for the 2023 HLT menu.

### CODE REVIEW

**Comment by emanueleusai** [comment]
please test

**Comment by emanueleusai** [comment]
please test

**Comment by emanueleusai** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
