### PR TITLE
Init for lumizcounting 92 x

### PR DESCRIPTION
**Pull request by xmniu**
Identical codes as PR 18899. Just another PR which targeted at 9_2_X branch in order to run production release on tier0.

### CODE REVIEW

**Comment by dmitrijus** [comment]
backport of https://github.com/cms-sw/cmssw/pull/19722

**Comment by dmitrijus** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Comment by fabozzi** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
