### PR TITLE
[GENERATORS] [LLVM14] Apply code checks

### PR DESCRIPTION
**Pull request by smuzaffar**
Applying code checks changes suggested by LLVM 14 ( which we want to integrate in cmssw once fully testing in CLANG IBs).
Mostly these changes are suggested by improved [performance-unnecessary-copy-initialization](https://releases.llvm.org/14.0.0/tools/clang/tools/extra/docs/clang-tidy/checks/performance-unnecessary-copy-initialization.html) check.

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@cms-sw/generators-l2 can you please review/sign this?

**Comment by perrotta** [comment]
merge

**Comment by Saptaparna** [comment]
Thanks, Andrea. Apologies for missing this.

**Pull request merged**
