### PR TITLE
Update of the Phase-2 GMT Emulator

### PR DESCRIPTION
**Pull request by zhenbinwu**
#### PR description:

Major ukpdate of the Phase-2 GMT Emulator:

1. Add the Phase-2 KMTF alogirthm for barrel muon
2. Get the Phase-2 OMTF and EMTF to the Phase-2 Standalone Muon ghost busting algorithm
4. Refined the Tracker Muon matching and quality bits for low pt muon
5. Restructure the TPS code into header and source files.
6. Update the Tracker Muon output to GT, sending quality score and isolation sum

### CODE REVIEW

**Comment by zhenbinwu** [comment]
This PR requires input from the Phase-2 OMTF #43687 and EMTF #43766. It seems OMTF was merged while EMTF is work in progress. I will wait for that PR and rebase.

**Comment by aloeliger** [comment]
@zhenbinwu Could you please merge https://github.com/zhenbinwu/cmssw/pull/2? This fixes a small configuration bug of the GMT->GT inputs.

**Comment by aloeliger** [comment]
@zhenbinwu Both of the required PRs for this PR have been merged. Could you please rebase this PR ontop of the current state of CMSSW_14_1?

**Comment by aloeliger** [comment]
> @zhenbinwu Both of the required PRs for this PR have been merged. Could you please rebase this PR ontop of the current state of CMSSW_14_1?

@zhenbinwu just a ping on the rebase.

**Comment by zhenbinwu** [comment]
> > @zhenbinwu Both of the required PRs for this PR have been merged. Could you please rebase this PR ontop of the current state of CMSSW_14_1?
> 
> @zhenbinwu just a ping on the rebase.

Thanks for the ping. The first rebase seems not working. I will try again tomorrow. I also have one patch will go in as well.

**Comment by zhenbinwu** [comment]
Mm.. this is messed up

**Comment by zhenbinwu** [comment]
Closing this PR while making another fresh PR

**Pull request closed without merging**
