### PR TITLE
Tested new configuration that works for HI runs

### PR DESCRIPTION
**Pull request by dinardo**
I updated the tracking configuration as in here:
http://cmslxr.fnal.gov/source/RecoVertex/PrimaryVertexProducer/python/OfflinePrimaryVertices_cfi.py

Now the application is able to read and process HI data.
- Mauro.

### CODE REVIEW

**Comment by fabiocos** [comment]
please test

not testing really much...

**Comment by andrius-k** [comment]
+1

**Comment by fabiocos** [comment]
@dinardo @andrius-k sorry, is this updated supposed to be valid only for HI?

**Comment by andrius-k** [comment]
@fabiocos I'm not sure about this. @dinardo Maybe you can elaborate?

**Comment by dinardo** [comment]
No no. It's valid for any kind of run.
There is check in the code: `process.runType.getRunType`
So it's good for any kind of data taking.

**Comment by fabiocos** [comment]
@dinardo right, but some settings were moved before the checks, I was wondering about that

**Comment by fabiocos** [comment]
+1

**Comment by dinardo** [comment]
Hi,
yes you are correct. But they are common to all run-type.

Is this going to go to the master branch or I need to push a new PR specifically for the master branch?

Cheers,
- Mauro.

**Comment by fabiocos** [comment]
@dinardo my bad, I overlooked the fact that this is not a backport. Please do asap a master version corresponding to this code

**Comment by dinardo** [comment]
Hi, which CMSSW verison shall I use to push the changed into the master?
- Mauro.

**Comment by fabiocos** [comment]
@dinardo you need to be based on 10_3_X, to which master points

**Comment by dinardo** [comment]
OK, done in CMSSW_10_3_X as you suggested:
PR #24679
- Mauro.

**Pull request merged**
