### PR TITLE
Muon HLT -  fix in TSGForOI

### PR DESCRIPTION
**Pull request by folguera**
Rescale the TSOS error before finding the compatible detector.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by perrotta** [comment]
@folguera : the fix is quite reasonable. I don't see any visible effect in the jenkins outputs, though: I imagine that some larger samples are needed in order to be able to see any reflection on the validation plots. Do you have any suggestion about how to quickly spot the effect of this fix? Could you please point out a presentation in which you showed it already?
In any case, I think this should go into 91X first: please provide a PR also for that cycle

**Comment by folguera** [comment]
@perrotta I cannot think of a quick way of spotting the difference, we simply though it made more sense to rescale before finding the compatible hits rather than doing it later... in the validation plots we ran offline we did not see any effect in terms of performance. 

In any case we will provide a PR in 91X.

**Comment by folguera** [comment]
@perrotta I've created the PR in 91X (#17862)  and the branch was immediately closed arguing that this branch is closed for updates.

**Comment by davidlange6** [comment]
and then asking you to create a PR in the master branch instead.Let me know if you have further problems doing that.

**Comment by perrotta** [comment]
+1
Same as #17917 in 91X
No changes visible in jenkin tests, but the effect of the fix on a larger stat sample shown in https://github.com/cms-sw/cmssw/pull/17917#issuecomment-287344452 goes in the wanted direction

**Comment by davidlange6** [comment]
+1

**Pull request merged**
