### PR TITLE
Stop using CSC trigger geometry

### PR DESCRIPTION
**Pull request by dildick**
* CSCTriggerGeometry is not thread-safe; use CSCGeometry instead. @kpedro88

### CODE REVIEW

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by dildick** [comment]
This should fix

<PRE>
#5  0x00007efdea40ce69 in CSCGeometry::chamber(CSCDetId) const () from /cvmfs/cms-ib.cern.ch/nweek-02466/slc6_amd64_gcc530/cms/cmssw/CMSSW_9_1_X_2017-04-06-1100/lib/slc6_amd64_gcc530/libGeometryCSCGeometry.so
#6  0x00007efdbdc7dd4e in CSCAnodeLCTProcessor::run(MuonDigiCollection<CSCDetId, CSCWireDigi> const*) () from /build/cmsbld/jenkins-workarea/workspace/ib-any-integration/CMSSW_9_1_X_2017-04-07-1100/lib/slc6_amd64_gcc530/libL1TriggerCSCTriggerPrimitives.so
#7  0x00007efdbdc5b516 in CSCMotherboardME11GEM::run(MuonDigiCollection<CSCDetId, CSCWireDigi> const*, MuonDigiCollection<CSCDetId, CSCComparatorDigi> const*, MuonDigiCollection<GEMDetId, GEMPadDigi> const*) () from /build/cmsbld/jenkins-workarea/workspace/ib-any-integration/CMSSW_9_1_X_2017-04-07-1100/lib/slc6_amd64_gcc530/libL1TriggerCSCTriggerPrimitives.so
</PRE>

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by dildick** [comment]
so after this commit I still have a bug somewhere. I crashes with [1]. Am I not deleting something that I should?

[1]
<PRE>
Thread 2 (Thread 0x7f6d64452700 (LWP 22391)):
#0  0x00007f6d76f2d37d in waitpid () from /lib64/libpthread.so.0
#1  0x00007f6d71dddda7 in edm::service::cmssw_stacktrace_fork() () from /cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc700/cms/cmssw/CMSSW_9_1_X_2017-04-05-2300/lib/slc6_amd64_gcc700/pluginFWCoreServicesPlugins.so
#2  0x00007f6d71dde54a in edm::service::InitRootHandlers::stacktraceHelperThread() () from /cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc700/cms/cmssw/CMSSW_9_1_X_2017-04-05-2300/lib/slc6_amd64_gcc700/pluginFWCoreServicesPlugins.so
#3  0x00007f6d7749294f in std::execute_native_thread_routine (__p=0x7f6d64d033b0) at ../../../../../libstdc++-v3/src/c++11/thread.cc:83
#4  0x00007f6d76f25aa1 in start_thread () from /lib64/libpthread.so.0
#5  0x00007f6d76c72aad in clone () from /lib64/libc.so.6
Thread 1 (Thread 0x7f6d75344dc0 (LWP 22336)):
#0  0x00007f6d76c69283 in poll () from /lib64/libc.so.6
#1  0x00007f6d71dde3c7 in full_read.constprop () from /cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc700/cms/cmssw/CMSSW_9_1_X_2017-04-05-2300/lib/slc6_amd64_gcc700/pluginFWCoreServicesPlugins.so
#2  0x00007f6d71ddeb7c in edm::service::InitRootHandlers::stacktraceFromThread() () from /cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc700/cms/cmssw/CMSSW_9_1_X_2017-04-05-2300/lib/slc6_amd64_gcc700/pluginFWCoreServicesPlugins.so
#3  0x00007f6d71de011c in sig_dostack_then_abort () from /cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc700/cms/cmssw/CMSSW_9_1_X_2017-04-05-2300/lib/slc6_amd64_gcc700/pluginFWCoreServicesPlugins.so
#4  <signal handler called>
#5  atomic_load_p (mo=atomic_memory_order_seq_cst, a=0x8) at include/jemalloc/internal/atomic.h:93
#6  atomic_read_p (p=0x8) at include/jemalloc/internal/atomic.h:94
#7  je_base_extent_hooks_get (base=0x0) at src/base.c:267
#8  0x00007f6d7844b043 in je_extent_hooks_get (arena=0x7f6d78468980 <je_arenas>) at src/extent.c:116
#9  extent_hooks_assure_initialized (arena=0x7f6d78468980 <je_arenas>, r_extent_hooks=0x7fff393cd6c8) at src/extent.c:128
#10 extent_record (extent=0x7f6d74d351b0, extents=0x7f6d7846a5e0 <je_arenas+7264>, r_extent_hooks=0x7fff393cd6c8, arena=0x7f6d78468980 <je_arenas>, tsdn=0x0) at src/extent.c:1304
#11 je_extents_dalloc (tsdn=tsdn@entry=0x0, arena=arena@entry=0x7f6d78468980 <je_arenas>, r_extent_hooks=r_extent_hooks@entry=0x7fff393cd6c8, extents=extents@entry=0x7f6d7846a5e0 <je_arenas+7264>, extent=0x7f6d74d351b0) at src/extent.c:373
#12 0x00007f6d78431532 in je_arena_extents_dirty_dalloc (extent=<optimized out>, r_extent_hooks=0x7fff393cd6c8, arena=0x7f6d78468980 <je_arenas>, tsdn=0x0) at src/arena.c:350
#13 arena_slab_dalloc (tsdn=0x0, arena=0x7f6d78468980 <je_arenas>, slab=<optimized out>) at src/arena.c:997
#14 0x00007f6d78433cd2 in arena_dalloc_bin_slab (bin=0x7f6d74f36040, slab=0x7f6d74d351b0, arena=0x7f6d78468980 <je_arenas>, tsdn=0x0) at src/arena.c:1572
#15 arena_dalloc_bin_locked_impl (junked=true, ptr=<optimized out>, slab=0x7f6d74d351b0, arena=0x7f6d78468980 <je_arenas>, arena@entry=0x7f6d74f2f8c0, tsdn=tsdn@entry=0x0) at src/arena.c:1623
#16 je_arena_dalloc_bin_junked_locked (tsdn=0x0, tsdn@entry=0x7f6d7533f800, arena=0x7f6d78468980 <je_arenas>, arena@entry=0x7f6d74f2f8c0, extent=0x7f6d74d351b0, ptr=<optimized out>) at src/arena.c:1638
#17 0x00007f6d78455f80 in je_tcache_bin_flush_small (tsd=0x7f6d7533f800, tcache=tcache@entry=0x7f6d74d2f980, tbin=tbin@entry=0x7f6d74d2fc10, binind=binind@entry=19, rem=rem@entry=32) at src/tcache.c:137
#18 0x00007f6d7842fc1e in je_tcache_dalloc_small (slow_path=<optimized out>, binind=<optimized out>, ptr=<optimized out>, tcache=<optimized out>, tsd=<optimized out>) at include/jemalloc/internal/tcache_inlines.h:263
#19 je_arena_sdalloc (slow_path=<optimized out>, tcache=<optimized out>, size=<optimized out>, ptr=<optimized out>, tsdn=<optimized out>) at include/jemalloc/internal/arena_inlines_b.h:326
#20 je_isdalloct (slow_path=<optimized out>, tcache=<optimized out>, size=<optimized out>, ptr=<optimized out>, tsdn=<optimized out>) at include/jemalloc/internal/jemalloc_internal.h:1138
#21 isfree (slow_path=<optimized out>, tcache=<optimized out>, usize=<optimized out>, ptr=<optimized out>, tsd=<optimized out>) at src/jemalloc.c:2042
#22 sdallocx (ptr=0x7f6ce054e180, size=<optimized out>, flags=<optimized out>) at src/jemalloc.c:2665
#23 0x00007f6d1b0d15dd in CSCTriggerPrimitivesBuilder::~CSCTriggerPrimitivesBuilder() () from /afs/cern.ch/work/d/dildick/public/GEM/CSCTriggerThreadSafe/CMSSW_9_1_X_2017-04-05-2300/lib/slc6_amd64_gcc700/libL1TriggerCSCTriggerPrimitives.so
#24 0x00007f6d1b132032 in CSCTriggerPrimitivesProducer::produce(edm::StreamID, edm::Event&, edm::EventSetup const&) const () from /afs/cern.ch/work/d/dildick/public/GEM/CSCTriggerThreadSafe/CMSSW_9_1_X_2017-04-05-2300/lib/slc6_amd64_gcc700/pluginCSCTriggerPrimitivesPlugins.so
</PRE>

**Comment by kpedro88** [comment]
@dildick I suspect you are somehow deleting something that was already deleted (that's usually what a crash in the destructor indicates.) I'll see if I notice anything...

**Comment by dildick** [comment]
@kpedro88 did you find anything?

**Comment by kpedro88** [comment]
@dildick I ran valgrind after merging your PR into `CMSSW_9_1_X_2017-04-10-1100` and compiling with debug symbols.
Full log: /afs/cern.ch/user/p/pedrok/public/forSven/log_valgrind.log
Excerpts of what seem like the most relevant issues: /afs/cern.ch/user/p/pedrok/public/forSven/log_valgrind_excerpt.log

Interestingly, workflow 21234.0 ran to completion for me, so the issue is probably some kind of memory corruption.

**Comment by dmitrijus** [comment]
+1

**Comment by slava77** [comment]
-1

compilation problems

**Comment by kpedro88** [comment]
please test

**Comment by dildick** [comment]
@kpedro88 this should address one of the issues in the valgrind report. I'll make a separate PR to clean up the remaining ones

**Comment by kpedro88** [comment]
Do those changes fully resolve the memory corruption issues you had observed?

**Comment by dildick** [comment]
I'm still checking that

**Comment by dildick** [comment]
@kpedro88 I ran valgrind on top of the most recent changes. Please find the log file here: 
<PRE>
/afs/cern.ch/work/d/dildick/public/GEM/CSCTriggerThreadSafe/CMSSW_9_1_0_pre2/src/21234.0_TTbar_14TeV+TTbar_14TeV_TuneCUETP8M1_2023D4_GenSimHLBeamSpotFull14+DigiFullTrigger_2023D4+RecoFullGlobal_2023D4+HARVESTFullGlobal_2023D4/full_valgrind.log
</PRE>

**Comment by kpedro88** [comment]
@dildick I still see in your log the same issues I had noticed here:
`/afs/cern.ch/user/p/pedrok/public/forSven/log_valgrind_excerpt.log`

I'm not sure if those issues were the ultimate cause of the crashes, though. If you can't identify a way to fix them (NB, the log I made has line numbers because I compiled with debug symbols), I would recommend trying a long run of one of the Phase2 workflows (1000 events or more) to see if any crash occurs.

**Comment by kpedro88** [comment]
@dildick I think this has to be rebased now that #17843 is merged

**Comment by dildick** [comment]
@kpedro88 I have not yet had the time to look at all the errors. I will have to put this on hold for a couple of weeks. After that I will rebase.

**Comment by dildick** [comment]
rebased. @kpedro88 can we go ahead with integrating this branch and addressing the memory corruption problems in a different one?

**Comment by kpedro88** [comment]
In general, we are not going to merge code that we suspect to be faulty. Are the memory problems really so difficult to fix?

**Comment by davidlange6** [comment]
hi all - is this PR relevant any more?

**Comment by dildick** [comment]
It is still relevant, but I'll close it for now until I've time to look at it.

**Pull request closed without merging**
