### PR TITLE
Remove the TIBDetId, TOBDetId, TIDDetId and TECDetId classes

### PR DESCRIPTION
**Pull request by pieterdavid**
After having migrated all uses of these classes to TrackerTopology (see https://github.com/cms-sw/cmssw/issues/19398 for the full list of PRs), they can be removed now.

CC @OlivierBondu @alesaggio @vidalm

### CODE REVIEW

**Comment by boudoul** [comment]
that is a really really great achievement ... Thanks !!!

**Comment by jfernan2** [comment]
@pieterdavid we don't have you identified as DQM developer in[1]. Are you working for HDQM or SiStrip DQM? Thanks
[1] https://twiki.cern.ch/twiki/bin/viewauth/CMS/DQMContacts

**Comment by fioriNTU** [comment]
@jfernan2 I let @pieterdavid reply, but he is a general framework developer trying to optimize our code. I guess he should be in one of your lists already, it is not the first time he pushes something in DQM.

**Comment by jfernan2** [comment]
@fioriNTU Then I guess it is HDQM, he was not in the list, added now

**Comment by jfernan2** [comment]
please test

**Comment by boudoul** [comment]
hi @jfernan2 , this is unfortunately where we reached the limit of the 'list of devoloper' for DQM  - @pieterdavid is not a DQM developer , he is a ... developer.  Which means that he's developing in  many packages, and DQM is one of it  when it's needed. For example the DetIds were  everywhere in cmssw, so he removed them (on the tracker DPG request) , factorizing packages per packages (to avoid big PR to review) and the DQM packages are part of this process - So you can add him in your list , in hDQM or DQM or any list you want, for sure it doesn't harm  but it doesn't make big sense actually ...

**Comment by pieterdavid** [comment]
Hi @jfernan2 , I think your question has been answered already by @fioriNTU and @boudoul : this is part of a tracker DPG EPR coding task that included migrating some code in DQM, commissioning etc. One clarification: this is not an optimization (their should not be a significant impact on performance), but the change was needed because the DetId layouts that were hardcoded in these classes will change for phase2.

**Comment by civanch** [comment]
+1

**Comment by jfernan2** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
