### PR TITLE
catch polymorphic exception by reference

### PR DESCRIPTION
**Pull request by Dr15Jones**
This silences a gcc 8 warning.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
@smuzaffar it looks like the test binaries were missing when the tests were run. However, the build logs says those binaries were built.

**Comment by smuzaffar** [comment]
please test
cms-bot had an issue with unittests, this should be fixed now.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
