### PR TITLE
[10.2.X] Change GT 2018 Pixel MC conditions

### PR DESCRIPTION
**Pull request by lpernie**
# Change Pixel conditions

## 2018
.  https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/102X_upgrade2018_realistic_v8/102X_upgrade2018_realistic_v9
.  https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/102X_upgrade2018cosmics_realistic_deco_v7/102X_upgrade2018cosmics_realistic_deco_v8

## 2023
.  https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/102X_upgrade2023_realistic_v6/102X_upgrade2023_realistic_v7

### CODE REVIEW

**Comment by lpernie** [comment]
please test

**Comment by lpernie** [comment]
please test

**Comment by fabiocos** [comment]
@lpernie I see DQM changes in 250202.181 and 150.0, besides 10824.0, I assume that this change is affecting any 2018 MC, right?

**Comment by lpernie** [comment]
Yes, it affects 2018 and 2023 realistic mc scenario

**Comment by lpernie** [comment]
+1

**Comment by boudoul** [comment]
Hi @lpernie , why 2023 ?

**Comment by boudoul** [comment]
Fortunately those tags are not consumed in 2023- It is fortunate because the pixel in 2023 has nothing to do with the currrent pixel, so in short, modifying 2023 doesn't harm , but not needed

**Comment by fabiocos** [comment]
@boudoul I did not spot any difference in Phase2 scenarios

**Comment by fabiocos** [comment]
+1

**Pull request merged**
