### PR TITLE
Update eventcontent structure for RecoBTag and RecoBTau

### PR DESCRIPTION
**Pull request by jeongeun**
#### PR description:  
Update event content definitions to explicitly have RECO to be a superset of AOD and for FEVT to be a superset of RECO. 2 files changed : 
+ RecoBTag_EventContent_cff.py 
+ RecoBTau_EventContent_cff.py

(The previous tasks are [PR#29025](https://github.com/cms-sw/cmssw/pull/29025), [PR#29158](https://github.com/cms-sw/cmssw/pull/29158), [PR#29225](https://github.com/cms-sw/cmssw/pull/29225), [PR#29299](https://github.com/cms-sw/cmssw/pull/29299), and [PR#29470](https://github.com/cms-sw/cmssw/pull/29470).)

#### PR validation:
Event Content comparison check was also done and there is no change with these updates.
Tested in CMSSW_11_1_X, the basic test all passed in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html).

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
```RecoBTau/Configuration/python/RecoBTau_EventContent_cff.py``` is an empty event content.
@XavierAtCERN @mverzett do we really need to keep it around? Couldn't we profit of this reorganization of the event content to just remove it, if it is not and it will not be used any more?

@jeongeun : in case we decide to maintain it, please take care of ```extend```ing the RECO event content with the AOD one, and the FEVT event content with the reco one, even of empty.

**Comment by jeongeun** [comment]
> `RecoBTau/Configuration/python/RecoBTau_EventContent_cff.py` is an empty event content.
> @XavierAtCERN @mverzett do we really need to keep it around? Couldn't we profit of this reorganization of the event content to just remove it, if it is not and it will not be used any more?
> 
> @jeongeun : in case we decide to maintain it, please take care of `extend`ing the RECO event content with the AOD one, and the FEVT event content with the reco one, even of empty.

**Comment by jeongeun** [comment]
@perrotta just to get it right, If this `RecoBTau_EventContent_cff.py` will not necessary, then we can erase it and the imported part in `Configuration/EventContent/python/EventContent_cff.py`. Is it right? : 

- `from RecoBTau.Configuration.RecoBTau_EventContent_cff import *`  [`import#L52`](https://github.com/cms-sw/cmssw/blob/master/Configuration/EventContent/python/EventContent_cff.py#L52), 
- `RECOEventContent.outputCommands.extend(RecoBTauRECO.outputCommands)`[`RecoBTauRECO#L447`](https://github.com/cms-sw/cmssw/blob/master/Configuration/EventContent/python/EventContent_cff.py#L447), 
- `AODEventContent.outputCommands.extend(RecoBTauAOD.outputCommands)`[`RecoBTauAOD#L486`](https://github.com/cms-sw/cmssw/blob/master/Configuration/EventContent/python/EventContent_cff.py#L486), 
- `FEVTEventContent.outputCommands.extend(RecoBTauRECO.outputCommands)`[`FEVT#L631`](https://github.com/cms-sw/cmssw/blob/master/Configuration/EventContent/python/EventContent_cff.py#L631), 
- `FEVTSIMEventContent.outputCommands.extend(RecoBTauRECO.outputCommands)`[`FEVTSIM#L677`](https://github.com/cms-sw/cmssw/blob/master/Configuration/EventContent/python/EventContent_cff.py#L677).

**Comment by perrotta** [comment]
> @perrotta just to get it right, If this `RecoBTau_EventContent_cff.py` will not necessary, then we can erase it and the imported part in `Configuration/EventContent/python/EventContent_cff.py`. Is it right? :
> 
> * `from RecoBTau.Configuration.RecoBTau_EventContent_cff import *`  [`import#L52`](https://github.com/cms-sw/cmssw/blob/master/Configuration/EventContent/python/EventContent_cff.py#L52),
> * `RECOEventContent.outputCommands.extend(RecoBTauRECO.outputCommands)`[`RecoBTauRECO#L447`](https://github.com/cms-sw/cmssw/blob/master/Configuration/EventContent/python/EventContent_cff.py#L447),
> * `AODEventContent.outputCommands.extend(RecoBTauAOD.outputCommands)`[`RecoBTauAOD#L486`](https://github.com/cms-sw/cmssw/blob/master/Configuration/EventContent/python/EventContent_cff.py#L486),
> * `FEVTEventContent.outputCommands.extend(RecoBTauRECO.outputCommands)`[`FEVT#L631`](https://github.com/cms-sw/cmssw/blob/master/Configuration/EventContent/python/EventContent_cff.py#L631),
> * `FEVTSIMEventContent.outputCommands.extend(RecoBTauRECO.outputCommands)`[`FEVTSIM#L677`](https://github.com/cms-sw/cmssw/blob/master/Configuration/EventContent/python/EventContent_cff.py#L677).

Correct @jeongeun 
However, if @XavierAtCERN or @mverzett do not suggest doing it here, it can be deferred to a forthcoming pull request. If we receive no feedback, I would suggest to just let the config as it is (just add the "extend" commands for RECO and FEVT)

**Comment by perrotta** [comment]
@jeongeun , since we got no comments, please go ahead with the minimal update suggested in https://github.com/cms-sw/cmssw/pull/29517#issuecomment-616598896 and https://github.com/cms-sw/cmssw/pull/29517#issuecomment-617790288 (i.e. just add the "extend" commands for RECO and FEVT), so that we can close this PR

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
+1
- Reorganization of the event content implemented as planned, with no changes on the output content
- jenkins tests pass

**Comment by silviodonato** [comment]
+1

**Pull request merged**
