### PR TITLE
Fix single particles variations for computation of type2 MET uncertainties

### PR DESCRIPTION
**Pull request by mmarionncern**
Same as #8391 for 75X

### CODE REVIEW

**Comment by monttj** [comment]
+1

**Comment by davidlange6** [comment]
@mmarionncern - looks like this PR does not merge now - could you rebase it?

**Comment by davidlange6** [comment]
@mmarionncern - is this pr needed?

**Comment by mmarionncern** [comment]
I though it was already merged few weeks ago. Superseeded by #8416.
I close the PR.

**Pull request closed without merging**
