### PR TITLE
HIP Killing and PreMixing for 80X

### PR DESCRIPTION
**Pull request by mdhildreth**
Add capabilities for luminosity scaling and PreMixing to HIP-killing code

### CODE REVIEW

**Comment by mdhildreth** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by davidlange6** [comment]
@mdhildreth - that did not go well - can you have a look?

**Comment by mdhildreth** [comment]
Huh...  Yes, I'll take a look...

**Comment by mdhildreth** [comment]
@iahmad-khan @smuzaffar @degano I forgot about moving the probability map file to externals.  Could you please replicate the /cmdist PR 2388 for 80X?  It's exactly the same files.

**Comment by smuzaffar** [comment]
please test with cms-sw/cmsdist#2448

**Comment by mdhildreth** [comment]
+1

**Comment by smuzaffar** [comment]
cms-sw/cmsdist#2448 is now merged for 80X (2016-09-06-1100 IB)

**Comment by mdhildreth** [comment]
Please test

**Comment by Dr15Jones** [comment]
@mdhildreth looks like this needs to be rebased.

**Comment by slava77** [comment]
-1

rebase is needed; from the context this PR shouldn't need reco

**Comment by mdhildreth** [comment]
Just rebased.

**Comment by mdhildreth** [comment]
please test

**Pull request merged**
