### PR TITLE
Payload Inspector: SiStrip Noise/Pedestals profile per module

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

This is a follow-up on PR https://github.com/cms-sw/cmssw/pull/28648.
Profiting of the extension of the developer level interface of the Payload Inspector meant to support plot-specific input parameters developed in that PR, new classes are added to the SiStrip Payload Inspector to display single `DetId` frames of Noise and Pedestals values.
In addition, the `TrackerMap` image classes templated against the saturation level of the z-axis are removed in favour of a unique instance in which such parameter is prompted by the user.  The new plots are tested via addition to existing unit tests. 

#### PR validation:

The PR validation relies on the existing and new unit tests added to this PR.

#### if this PR is a backport please specify the original PR:

This PR is not a backport.

**N.B.: this PR shall be put on hold until it is validated  in the development service environment.**

### CODE REVIEW

**Comment by ggovi** [comment]
please test

**Comment by ggovi** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Comment by mmusich** [comment]
@ggovi is there a development version of the `condDBBrowser` that can be used to test this PR?

**Pull request merged**
