### PR TITLE
Update JECs to `Spring15_v3` and enable new key for Ecal AlCaReco

### PR DESCRIPTION
**Pull request by mmusich**
## RunI simulation
- **RunI Ideal scenario** : [81X_mcRun1_design_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun1_design_v1) as [81X_mcRun1_design_v0](https://cms-conddb.cern.c
  h/cmsDbBrowser/list/Prod/gts/81X_mcRun1_design_v0) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_mcRun1_design_v1/81X_mcRun1_design_v0): 
  - updated `AlCaRecoTriggerBits` with `AlCaEcalTrg`
- **RunI Heavy Ions scenario** : [81X_mcRun1_HeavyIon_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun1_HeavyIon_v1) as [81X_mcRun1_HeavyIon_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun1_HeavyIon_v0) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_mcRun1_HeavyIon_v1/81X_mcRun1_HeavyIon_v0): 
  - updated `AlCaRecoTriggerBits` with `AlCaEcalTrg`
- **RunI Realistic scenario** : [81X_mcRun1_realistic_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun1_realistic_v1) as [81X_mcRun1_realistic_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun1_realistic_v0) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_mcRun1_realistic_v1/81X_mcRun1_realistic_v0): 
  - updated `AlCaRecoTriggerBits` with `AlCaEcalTrg`
- **RunI Proton-Lead scenario** : [81X_mcRun1_pA_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun1_pA_v1) as [81X_mcRun1_pA_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun1_pA_v0) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_mcRun1_pA_v1/81X_mcRun1_pA_v0): 
  - updated `AlCaRecoTriggerBits` with `AlCaEcalTrg`
## RunII simulation
- **RunII Ideal scenario** : [81X_mcRun2_design_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun2_design_v1) as [81X_mcRun2_design_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun2_design_v0) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_mcRun2_design_v1/81X_mcRun2_design_v0): 
  - updated `AlCaRecoTriggerBits` with `AlCaEcalTrg`
  - updated Jet Energy corrections to version `Spring16_25nsV3` 
- **RunII CRAFT scenario** : [81X_mcRun2cosmics_startup_peak_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun2cosmics_startup_peak_v1) as [81X_mcRun2cosmics_startup_peak_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun2cosmics_startup_peak_v0) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_mcRun2cosmics_startup_peak_v1/81X_mcRun2cosmics_startup_peak_v0): 
  - updated `AlCaRecoTriggerBits` with `AlCaEcalTrg`
  - updated Jet Energy corrections to version `Spring16_25nsV3`
- **RunII Asymptotic scenario** : [81X_mcRun2_asymptotic_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun2_asymptotic_v1) as [81X_mcRun2_asymptotic_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun2_asymptotic_v0) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_mcRun2_asymptotic_v1/81X_mcRun2_asymptotic_v0): 
  - updated `AlCaRecoTriggerBits` with `AlCaEcalTrg`
  - updated Jet Energy corrections to version `Spring16_25nsV3`
- **RunII Startup scenario** : [81X_mcRun2_startup_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun2_startup_v1) as [81X_mcRun2_startup_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun2_startup_v0) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_mcRun2_startup_v1/81X_mcRun2_startup_v0): 
  - updated `AlCaRecoTriggerBits` with `AlCaEcalTrg`
- **RunII Heavy Ions scenario** : [81X_mcRun2_HeavyIon_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun2_HeavyIon_v1) as [81X_mcRun2_HeavyIon_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun2_HeavyIon_v0) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_mcRun2_HeavyIon_v1/81X_mcRun2_HeavyIon_v0): 
  - updated `AlCaRecoTriggerBits` with `AlCaEcalTrg`
## RunII data
- **RunII Offline processing** : [81X_dataRun2_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_dataRun2_v1) as [81X_dataRun2_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_dataRun2_v0) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_dataRun2_v1/81X_dataRun2_v0): 
  - updated Jet Energy corrections to version `Spring16_25nsV3`
- **RunII Psuedo-Prompt processing** : [81X_dataRun2_Run2016B_Prompt_frozen_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_dataRun2_Run2016B_Prompt_frozen_v2) as [81X_dataRun2_Run2016B_Prompt_frozen_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_dataRun2_Run2016B_Prompt_frozen_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_dataRun2_Run2016B_Prompt_frozen_v2/81X_dataRun2_Run2016B_Prompt_frozen_v1): 
  - updated Jet Energy corrections to version `Spring16_25nsV3`
- **RunII Offline relval processing** : [81X_dataRun2_relval_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_dataRun2_relval_v1) as [81X_dataRun2_relval_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_dataRun2_relval_v0) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_dataRun2_relval_v1/81X_dataRun2_relval_v0): 
  - updated Jet Energy corrections to version `Spring16_25nsV3`
## Upgrade
- **PhaseI realistic scenario** : [81X_upgrade2017_realistic_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_upgrade2017_realistic_v3) as [81X_upgrade2017_realistic_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_upgrade2017_realistic_v2) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_upgrade2017_realistic_v3/81X_upgrade2017_realistic_v2): 
  - updated `AlCaRecoTriggerBits` with `AlCaEcalTrg`
  - update phase-I geometry for new BPIX module cable materials, new FPIX portcard material and dimensions as in #14700
- **PhaseI design scenario** : [81X_upgrade2017_design_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_upgrade2017_design_v3) as [81X_upgrade2017_design_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_upgrade2017_design_v2) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_upgrade2017_design_v3/81X_upgrade2017_design_v2): 
  - updated `AlCaRecoTriggerBits` with `AlCaEcalTrg`
  -  update phase-I geometry for new BPIX module cable materials, new FPIX portcard material and dimensions as in #14700

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
+1

**Comment by mmusich** [comment]
please test

**Comment by davidlange6** [comment]
+1

**Pull request merged**
