### PR TITLE
DD Compact View: Fix Excessive Output

### PR DESCRIPTION
**Pull request by ianna**
* Remove std::cout

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by fabiocos** [comment]
please test

just for check of the output, I will merge it anyway

**Comment by fabiocos** [comment]
@ianna if this printout is useful for debugging, may be it could be triggered by an #ifdef statement, or by using the MessageLogger (although a dependency on that would be introduced in that case), what do you think?

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

prevent next IB output files to be flooded by printouts, the fix is trivial
Possible further improvements for debugging/diagnostic can be added in a next IB if needed

**Pull request merged**
