### PR TITLE
Fix Unrunnable Schedule due to multiple offlineBeamSpots (81X)

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
Fix Unrunnable Schedule due to multiple offlineBeamSpots (81X)

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
@ssekmen, @lveldere 
Please sign for fastsim.
(BTW, the stage-2 L1T and HLT should work in FastSim - contrary what you presented today in the Plenary)

**Comment by lveldere** [comment]
It seems not to work 100%.
We'll get back to you when we have time to look into it.

We usually sign with the comparisons are available.
(I know this pr is trivial)

**Comment by Martin-Grunewald** [comment]
@lveldere 
Sorry, what exactly is not 100% working?

**Comment by lveldere** [comment]
I don't know yet.

**Comment by lveldere** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
