### PR TITLE
bsunanda"Phase2-hgx44 Complete the example of TB for HGCal

### PR DESCRIPTION
**Pull request by bsunanda**

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by smuzaffar** [comment]
cms-bot recognize new package

**Comment by civanch** [comment]
@bsunanda , sorry, why you choose the name "TestBeam" for the new package? Of course, this is possible but not inline with existing EcalTestbeam and HcalTestBeam.

**Comment by bsunanda** [comment]
@civanch Should I change it to HGCalTestBeam. I shall try that

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
please test

**Comment by bsunanda** [comment]
@smuzaffar I had to change the name from SimG4CMS/TestBeam to SimG4CMS/HGCalTestBeam due to Vladimir's comment. Please accept the new name. Thanks

**Comment by smuzaffar** [comment]
cms-bot?

**Comment by smuzaffar** [comment]
@bsunanda , done

**Comment by bsunanda** [comment]
@smuzaffar Thanks

**Comment by civanch** [comment]
+1

**Comment by cvuosalo** [comment]
+1

For #13719 8392934c6c109455dfd44082ec5dd81abf938b19

Completing a test beam example for the HGCAL.

The Reco code changes are satisfactory, and Jenkins tests against baseline CMSSW_8_1_X_2016-03-16-1100 show no significant differences.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
