### PR TITLE
Run3-TB49 Remove overlap in the beamline geometry

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Remove overlaps in the beam line geometry for the description of Oct 18 testbeam setup

#### PR validation:

Tested with cfg files in the area SimG4CMS/HGCalTestBeam/test

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade

**Comment by silviodonato** [comment]
+1

**Pull request merged**
