### PR TITLE
HLT menu migration to 1100pre12 template (PFProducer)

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
#### PR description:

HLT menu migration to 1100pre12 template (PFProducer)
Based on CMSSW_11_0_0_pre12

#### PR validation:

TSG tests

#### if this PR is a backport please specify the original PR:

N/A

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
Fixes issue https://github.com/cms-sw/cmssw/issues/28403

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by fabiocos** [comment]
@Martin-Grunewald I understand that the "frozen" 2018 menu keeps unchanged result, as this PR just moves a functionality between different parts of the configuration, am I correct?

**Comment by Martin-Grunewald** [comment]
Indeed that is the plan. However, there may be residual changes due to updated PF parameters, but those changes are acceptable.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
