### PR TITLE
Run3-hcx297 Take care of DDD or DD4Hep in esGetToken for Hcal code

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Take care of DDD or DD4Hep in esGetToken for Hcal code

#### PR validation:

Use runTheMatrix test workflows

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cvuosalo Please check this PR

**Comment by civanch** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
