### PR TITLE
dqm plot, pixel endcap roc occupancy in 80x

### PR DESCRIPTION
**Pull request by gouskos**

### CODE REVIEW

**Comment by dmitrijus** [comment]
Please provide a description and a corresponding 81x version of this PR.

**Comment by gouskos** [comment]
This PR adds a single DQM plot showing the ROC occupancy for the PIXEL endcaps [x-axis: Disks ; y-axis: blades] The corresponding PR in 81X is: #15237
Thank you.

**Comment by dmitrijus** [comment]
+1

**Comment by fioriNTU** [comment]
@dmitrijus can you please restart the tests? This is a quite urgent PR

**Comment by gouskos** [comment]
Please do not proceed with the tests yet to test something first

**Comment by gouskos** [comment]
Please do not proceed with the tests yet to test something first

**Comment by dmitrijus** [comment]
Ok, ping me once you are ready.

**Comment by gouskos** [comment]
please see also my comment on PR #15237 [the 81X version of this plot] Thank you

**Comment by dmitrijus** [comment]
+1

**Pull request merged**
