### PR TITLE
[PF] Fix RecoParticleFlow.PFProducer.pfGsfElectronCiCSelector_cfi

### PR DESCRIPTION
**Pull request by stahlleiton**
#### PR description:

This PR fixes the compilation issue on RecoParticleFlow.PFProducer.pfGsfElectronCiCSelector_cfi reported in https://github.com/cms-sw/cmssw/issues/45106#issuecomment-2140347324

#### PR validation:

python3 -m RecoParticleFlow.PFProducer.pfGsfElectronCiCSelector_cfi

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by jfernan2** [comment]
+1

**Comment by swagata87** [comment]
type pf

**Comment by rappoccio** [comment]
+1

**Pull request merged**
