### PR TITLE
Added additional entries to .gitignore

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

- ignore mac specific files
- ignore files used by some IDEs

#### PR validation:

Tested on Mac laptop. The extra files/directories are now ignored by git.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
assign core

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
I found this modification helpful when using my Mac laptop (plus different IDEs) for CMSSW code development.

**Comment by makortel** [comment]
Looks ok to me. @smuzaffar?

**Comment by makortel** [comment]
@smuzaffar Do you have any comments?

**Comment by smuzaffar** [comment]
> @smuzaffar Do you have any comments?

No, change looks good to me

**Comment by makortel** [comment]
+core

**Comment by rappoccio** [comment]
+1

**Pull request merged**
