### PR TITLE
Fix: 50ns used legacy L1

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
Fix: 50ns used legacy L1

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
@mulhearn

**Comment by davidlange6** [comment]
i'm not sure I follow what the "fix" is? Can you elaborate? @Martin-Grunewald @mulhearn

**Comment by Martin-Grunewald** [comment]
The era called ```Run2_50ns``` was containing the sub-era ```stage1L1Trigger```;
this is incorrect as 2015 50ns data taking was using the legacy L1 (only 2015
25ns used the stage1 L1). The PR corrects this in the era definition.

**Pull request merged**
