### PR TITLE
[104X] Change GT. Update offline GTs. Add 2018 Peak Cosmic Queue. Updated 2018 MC GTs.

### PR DESCRIPTION
**Pull request by lpernie**
# Offline Data
.  https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/103X_dataRun2_v3/103X_dataRun2_v4

# Offline Data Relval
.  https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/103X_dataRun2_relval_v6/103X_dataRun2_relval_v7

# 2018 MC realistic (updated ECAL conditions)
.  https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/103X_upgrade2018_realistic_v7/103X_upgrade2018_realistic_v8
.  https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/103X_upgrade2018_realistic_HEfail_v3/103X_upgrade2018_realistic_HEfail_v4

# 2018 MC HI realistic conditions (added CastorGains_PbPb_v1.0_mc)
.  https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/103X_upgrade2018_realistic_HI_v7/103X_upgrade2018_realistic_HI_v8

# Updated DECO 2018 Cosmic Queue (updated ECAL conditions)
.  https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/103X_upgrade2018cosmics_realistic_deco_v6/103X_upgrade2018cosmics_realistic_deco_v7

# Added PEAK 2018 Cosmic Queue
. https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/103X_upgrade2018cosmics_realistic_deco_v7/103X_upgrade2018cosmics_realistic_peak_v1

### CODE REVIEW

**Comment by lpernie** [comment]
please test

**Comment by fabiocos** [comment]
@lpernie but is the change of conditions for the run1 period done on purpose? 2012 test workflows shows differences (although the few I browsed are small).

**Comment by lpernie** [comment]
Hi @fabiocos no change has been done on run1 history.
The changes seems to me coming only from fluctuation of almost empty histograms.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
