### PR TITLE
Fixing tracking in SLHCDEV release

### PR DESCRIPTION
**Pull request by ebrondol**
In order to have tracking reconstruction working again with the new DetId scheme, the first solution is using the concept of detBrothers in the TkDetLayers builders for Phase2OT.
This is supposed to be not the definitive solution - the definitive one would include the possibility of not to use the DetBrothers and instead using the StackGeomDet directly in the MeasurementTracker class.
The rest of the changes in this PR are concerning the DPG tools used in order to study the efficiency of the tracking local reconstruction. It has been introduced the possibility to check if the selection done on DetId bits and the one done using the TkTopology are the same. 

This PR is an update of PR#12771 with the new WFs running.
@boudoul @delaere @venturia

### CODE REVIEW

**Comment by slava77** [comment]
are the files like Geometry/TrackerNumberingBuilder/test/trackerTopology_GeometryExtended2023Flat.txt
needed in the release or is it just some test output?
A quarter million line change looks pretty large to carry around.

**Comment by ebrondol** [comment]
Sure, I am sorry for the inconvenience.

**Comment by slava77** [comment]
@ebrondol 
what about  SLHCUpgradeSimulations/Geometry/test/PixelSkimmedGeometry_GeometryExtended2023Flat.txt  and SLHCUpgradeSimulations/Geometry/test/PixelSkimmedGeometry_GeometryExtended2023Tilted.txt ?

**Comment by ebrondol** [comment]
For this two files, I would like that @boudoul comments on that. They are produced with the two new WFs. I am not sure if they are needed or not for some database.

**Comment by VinInn** [comment]
@cmsbuild, please test

**Comment by davidlange6** [comment]
hum, if I run 
dlange@cmsdev01 CMSSW_8_0_X_2016-01-11-1100]$ runTheMatrix.py -l limited -i all > & go.3
[dlange@cmsdev01 CMSSW_8_0_X_2016-01-11-1100]$ $?
0: Command not found.

i don't get errors - @smuzaffar @degano @iahmad-khan - do you see errors in the logs?

**Comment by VinInn** [comment]
@davidlange6, how are we expected to progress on this?

**Comment by davidlange6** [comment]
so is this expected (and wanted?)

millions of the Alerts and then an exception
A L E R T! Layer-Rod-Module already present!
A L E R T! Layer-Rod-Module already present!
A L E R T! Layer-Rod-Module already present!
A L E R T! Layer-Rod-Module already present!
A L E R T! Layer-Rod-Module already present!
A L E R T! Layer-Rod-Module already present!
----- Begin Fatal Exception 12-Jan-2016 19:49:58 CET-----------------------
An exception of category 'StackedTrackerGeometryBuilder' occurred while
   [0] Processing run: 1
   [1] Running path 'L1TrackTrigger_step'
   [2] Calling beginRun for module TTClusterBuilder_PixelDigi_/'TTClustersFromPixelDigis'
   [3] Using EventSetup component StackedTrackerGeometryESModule/'' to make data StackedTrackerGeometry/'' in record StackedTrackerGeometryRecord
Exception Message:

**Comment by ebrondol** [comment]
As far as I know, the WF was customized in order to not run the L1TrackTrigger step because we know that in this moment is it not working in SLHCDEV. It has been discussed in PR#12093.
Not sure when and why it has been re-activated. @boudoul , do you know?

**Comment by boudoul** [comment]
Hi @davidlange6 : Indeed @mark-grimes removed the L1 Track Trigger step which is expected to fail . But he removed only in the supported scenarios - Looks like you see it in the TTI scenario (right) which has not been maintained .
The main scenarios to look at for the tests are :  
2023muon (TP legacy ) , 2023tilted (TP legacy but with Tilted) , and phase1 : 2017 , 2019 - Would be great that the final TP scenario worked too but I don't think it's configured in the PR test.
So the errors are expected and shoud be ignored , but maybe , to be more convenient to integrate PRs, we should refine the PR tests for only supported and legacy scenarios.

**Comment by boudoul** [comment]
@slava77 and @ebrondol ; the two files SLHCUpgradeSimulations/Geometry/test/PixelSkimmedGeometry_GeometryExtended2023Flat.txt and SLHCUpgradeSimulations/Geometry/test/PixelSkimmedGeometry_GeometryExtended2023Tilted.txt  can be safely removed from there

**Comment by davidlange6** [comment]
cmsbuild, please test

**Pull request merged**
