### PR TITLE
updated parameters and model for photon XGboost MVA (HLT) [14_0_X (backport)]

### PR DESCRIPTION
**Pull request by smorovic**
#### PR description:
* Latest XGBoost model in cms-data added to the unit test. Requires: https://github.com/cms-data/RecoEgamma-PhotonIdentification/pull/15
* Removed unused parameters and updating relevant parameters to the values intended for inclusion into the pp HLT menu.

#### PR validation:

Unit test added for the new model file.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport of:
https://github.com/cms-sw/cmssw/pull/44719
Reason: integration into the next 14_0 release for the proton-proton HLT menu

### CODE REVIEW

**Comment by mmusich** [comment]
backport of https://github.com/cms-sw/cmssw/pull/44719

**Comment by mmusich** [comment]
type egamma

**Comment by mmusich** [comment]
test parameters:
   * pull_request = https://github.com/cms-data/RecoEgamma-PhotonIdentification/pull/15

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by jfernan2** [comment]
+1

**Comment by mmusich** [comment]
+hlt

**Comment by rappoccio** [comment]
+1

**Pull request merged**
