### PR TITLE
Towards the first hlt menu for 2016 - 81X

### PR DESCRIPTION
**Pull request by perrotta**
Starting HLT menu for 2016.
This PR replaces #14426, which had problems of mergeability.
Based on CMSSW_8_1_X_2016-05-01-2300

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test
(rebased  to 810pre4)

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
