### PR TITLE
Allow TriggerSummaryProducerAOD to be configured to throw (92X)

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
Allow TriggerSummaryProducerAOD to be configured to throw (92X)

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
backport of #19745

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
