### PR TITLE
Add baseline time calculation for HGCal clusters 

### PR DESCRIPTION
**Pull request by lgray**
Calculate the arithmetic average cluster time for HGCal clusters using the PCA algorithm.

This is a good baseline for photons with no bias and good timing resolution, but causes tails and other issues for hadron showers (which are being worked out).

All calculations are done with respect to (0,0,0), so that tof will have to be vertex corrected for any further analysis.

A similar PR will come for the ECAL detailed time, but it's a bit more involved.

Performance for photons:
image

### CODE REVIEW

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
+1

For #15940 9dfb00f241ee6f4db0a4a54a478b00fd2ba37739

Adding an average cluster time for HGCal clusters. There should be no effect on non-HGCal code.

The code changes are satisfactory, and Jenkins tests against baseline CMSSW_8_1_X_2016-09-21-1100 show no significant differences, as expected.

**Comment by lgray** [comment]
@bendavid FYI

**Comment by davidlange6** [comment]
+1

**Pull request merged**
