### PR TITLE
PrimaryVertexMonitoring: don't use HP flag for Alignment plots at HLT

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

Title says it all.
Addresses https://github.com/cms-sw/cmssw/pull/33693#issuecomment-839065049.
Do not use HP flag for HLT tracks when compiling Alignment validation plots with vertices.

#### PR validation:

Run `runTheMatrix.py -l 12434 --ibeos -t 4 -j 8`
Plots that were empty before are now filled.

image

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Not a backport, no backport needed.
cc: @mtosi

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
Now plots in [/ HLT / Vertexing / hltPixelVertices / Alignment](https://tinyurl.com/yzq6vzre) and [/ HLT / Vertexing / hltTrimmedPixelVertices / Alignment](https://tinyurl.com/ydpydxea) are filled as expected.

**Comment by jfernan2** [comment]
+1
Thank you very much!!

**Comment by silviodonato** [comment]
+1

**Pull request merged**
