### PR TITLE
ECAL Timing Reco: CrossCorrelation algorithm update

### PR DESCRIPTION
**Pull request by nminafra**
This PR introduces:
- GoldenRatio minimization for CC algorithm:
> More details: https://en.wikipedia.org/wiki/Golden-section_search
- Implementation of kOOT flag for spike rejection:
> More details: https://indico.cern.ch/event/1114550/contributions/4887537/attachments/2451361/4200675/ECAL_DPG_25May22.pdf

A proposed test script is available here:
https://github.com/nminafra/cmssw/blob/ecalTimingCC_12_6_0_pre4/RecoLocalCalo/EcalRecProducers/test/testEcalUncalibRechitProducerWithCC_cfg.py

Profiling of the CC (this PR) and Ratio (default) are available here:
https://nminafra.web.cern.ch/cgi-bin/igprof-navigator/igreport_cc_Nov2022/20
https://nminafra.web.cern.ch/cgi-bin/igprof-navigator/igreport_ratio_Nov2022/20

CC has to run twice: once with OOT correction for better timing, a second time without OOT corrections for better spike rejection (see presentation above). Even running twice, CC is faster than Ratio.

@thomreis @jking79

### CODE REVIEW

**Comment by thomreis** [comment]
please test

**Comment by thomreis** [comment]
type ecal

**Comment by clacaputo** [comment]
enable profiling

**Comment by clacaputo** [comment]
please test

**Comment by clacaputo** [comment]
enable profiling

**Comment by clacaputo** [comment]
please test

**Comment by nminafra** [comment]
@clacaputo thanks for restarting the tests. 
Please, keep in mind that the new alorithm is not enabled by default so I think the profiling will run with the default time reconstruction (Ratio method).
To run the new code, you need to change the selected time reconstruction algorithm:
```
process.ecalMultiFitUncalibRecHit.algoPSet = cms.PSet( 
      timealgo = cms.string( "crossCorrelationMethod" ),
)    
```
As done in the suggested test file:
https://github.com/nminafra/cmssw/blob/ecalTimingCC_12_6_0_pre4/RecoLocalCalo/EcalRecProducers/test/testEcalUncalibRechitProducerWithCC_cfg.py

**Comment by clacaputo** [comment]
+reconstruction

- ecal new timing algorithm
- the new algorithm is not enabled by default, [see here](https://github.com/cms-sw/cmssw/pull/40262#issuecomment-1361732621)
- no reco/profiling differences seen, as expected

**Review by perrotta — COMMENTED** [review]
After your update you remain with a dead initialization (notified by the SA, that you should better get rid of

**Comment by nminafra** [comment]
Thanks @perrotta for the suggestions

**Comment by perrotta** [comment]
Thank you @nminafra 

You can now also remove https://github.com/cms-sw/cmssw/pull/40262/files#diff-a4f025f32fe02059a83e7acaa21d1884c35d899663994e907b0795f585e02c0dR72-R73

**Comment by nminafra** [comment]
> Thank you @nminafra
> 
> You can now also remove https://github.com/cms-sw/cmssw/pull/40262/files#diff-a4f025f32fe02059a83e7acaa21d1884c35d899663994e907b0795f585e02c0dR72-R73

ture, thanks!

**Comment by clacaputo** [comment]
+reconstruction 

re-sign

**Comment by perrotta** [comment]
+1

**Pull request merged**
