### PR TITLE
Phase2-hgx146 Add a new method for HGCalGeometry and add a test for corners

### PR DESCRIPTION
**Pull request by bsunanda**

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by ianna** [comment]
please test

**Comment by kpedro88** [comment]
+upgrade

**Comment by ianna** [comment]
+1

**Comment by bsunanda** [comment]
@fabiocos @kpedro88 Can this PR be merged. This helps the next PR which can reduce memory usage by Fireworks

**Comment by fabiocos** [comment]
+1

**Pull request merged**
