### PR TITLE
Report # events per Lumi for output files in framework job report

### PR DESCRIPTION
**Pull request by Dr15Jones**
DMWM needs to obtain the number of events written per LuminosityBlock for each output file.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
@ericvaandering

**Comment by Dr15Jones** [comment]
backport #17912

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by Dr15Jones** [comment]
+1

**Comment by Dr15Jones** [comment]
please test

**Comment by davidlange6** [comment]
+1

**Pull request merged**
