### PR TITLE
HIN Jet DQM module version 3

### PR DESCRIPTION
**Pull request by rkunnawa**
This is the updated HIN Jet DQM module v3, containing some bug fixes and new additions based on the PR #12002 which contains the centrality bin. We checked the matrix with the aforementioned PR merged. Once the Heavy Ion come up with a 75X version of that #12002, we will request a back port into 75X. 
Thanks!

### CODE REVIEW

**Comment by diguida** [comment]
please test

**Comment by diguida** [comment]
@rkunnawa @smdogra the 75X back-port of #12002 is ready, together with GT: #12213

**Comment by diguida** [comment]
@franzoni @mmusich

**Comment by rkunnawa** [comment]
@diguida, thanks for telling me about the backport. I will prepare a PR for that now. I will test it with merging the #12213.

**Comment by deguio** [comment]
please test

**Comment by rkunnawa** [comment]
@deguio and @danduggan, this has been in hold for about a week now and we are requesting the dqm signature for this PR. Please let me know if you need any additional information. 

Cheers
Raghav

**Comment by deguio** [comment]
ciao @rkunnawa 
please submit to 80x as well.
I think the changes are fine even if the use of containers to hold monitor elements would make the code more readable and more maintainable.
in general please don't comment code. just remove the commented lines from both c++ and python.
thanks,
F.

**Comment by rkunnawa** [comment]
Hi @deguio, Im testing the PR for 80X at the moment with the matrix. In the meanwhile, I can remove the commented out statements to this PR and we can test this again.

**Comment by rkunnawa** [comment]
@deguio, ive created a new PR for 80X with the same Jet DQM code (with removing some of the commented out code) #12353.

**Comment by deguio** [comment]
ok thanks. I triggered the tests there.

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
I am cleaning up the 76x queue aside from things for analysis workflows. I'm closing this pull request, please make sure the PR is in 80x. Thanks!

**Pull request closed without merging**
