### PR TITLE
Tracker Overlap Bugfixes

### PR DESCRIPTION
**Pull request by ianna**
* Move TOBPotting by ~mm
* Move TIBRailBottom by 0.05 cm
* Move TOBConnect23 out of TOBCFTube2

This PR replaces https://github.com/cms-sw/cmssw/pull/17339

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by ianna** [comment]
please test

**Comment by civanch** [comment]
@ianna , there is no overlaps.

**Comment by ianna** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
