### PR TITLE
Modifier to apply energy corrections to photons and electrons (miniAOD) for 76X

### PR DESCRIPTION
**Pull request by matteosan1**
Like  #10611 but for 76X. Implements most of the comments from Slava on the 75X version.
Payloads for GT have been queued for integration.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
-1

this doesn't merge anymore

**Comment by lgray** [comment]
@matteosan1 Since you're away I am taking over these PRs for you. I'll have to start new PRs though.
This is OK @slava77?

**Comment by slava77** [comment]
On 8/11/15 9:30 AM, Lindsey Gray wrote:
> @matteosan1 <https://github.com/matteosan1> Since you're away I am
> taking over these PRs for you. I'll have to start new PRs though.
> This is OK @slava77 <https://github.com/slava77>?

OK with me

**Comment by lgray** [comment]
@matteosan1 can you close this one too? thanks!

**Comment by matteosan1** [comment]
Done for all.

On 8/11/15 17:49, Lindsey Gray wrote:
>
> @matteosan1 <https://github.com/matteosan1> can you close this one 
> too? thanks!
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/cms-sw/cmssw/pull/10650#issuecomment-129939100>.
>

+++++++++++
Matteo Sani
University of California, San Diego, US.
Tel: +41227671577
CERN Office: 40-3-A02

**Pull request closed without merging**
