### PR TITLE
[12_3_X] Fix xml tag in PPS strips mapping

### PR DESCRIPTION
**Pull request by ChrisMisan**
#### PR description:

PR adds a missing closing tag to the strips xml mapping.

#### PR validation:

relvals 136.793, 136.874

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

original PR #37449

### CODE REVIEW

**Comment by francescobrivio** [comment]
type bugfix

**Comment by francescobrivio** [comment]
backport of #37449

**Comment by francescobrivio** [comment]
test parameters: 

- workflows = 136.793, 136.874

**Comment by francescobrivio** [comment]
@cmsbuild please test

**Comment by francescobrivio** [comment]
@ChrisMisan thanks for this backport! Could you please add "[12_3_X]" in the title?

**Comment by tvami** [comment]
+alca
 * Jenkins diffs are known

**Comment by tvami** [comment]
@ChrisMisan 
> And please mention in the title that these are the PPS strips, not the SiStrips :) (also for the master PR)

**Comment by qliphy** [comment]
+1

**Pull request merged**
