### PR TITLE
L1T O2O: degubing of uGMT + new prototype for caloParams payload + scripts' development

### PR DESCRIPTION
**Pull request by kkotov**
Few non-critical cosmetic changes to the L1T O2O utilities and scripts including:
0) #include<iomanip>
1) viewer for comparing the L1TMuonGlobalParams payloads (useful for debugging)
2) version of the prototyping caloParams, that O2O starts with and reloads with config from the online
3) fixes to the "trigger key validation" script and suppressing verbosity of the main runL1-O2O-iov.sh script

### CODE REVIEW

**Comment by ggovi** [comment]
please test

**Comment by smuzaffar** [comment]
Should we assign these new un-assigned packages to L1?
```
L1TriggerConfig/L1TConfigProducers
L1TriggerConfig/Utilities
```

**Comment by koskot77** [comment]
@smuzaffar yes, the two packages should be assigned to L1 as, if I'm not mistaking, was also done earlier to L1TriggerConfig/L1TUtmTriggerMenuProducers that is now moved into the L1TriggerConfig/L1TConfigProducers

**Comment by rekovic** [comment]
+1

**Comment by ggovi** [comment]
+1

**Comment by davidlange6** [comment]
@kkotov - as you might imagine, this PR needs a more appropriate title as well. Thanks

**Comment by kkotov** [comment]
@davidlange6 , done

**Comment by davidlange6** [comment]
+1

**Pull request merged**
