### PR TITLE
Fix TripletStep Task for HI Phase1

### PR DESCRIPTION
**Pull request by perrotta**
#### PR description:

It fixes a couple of Tasks in RecoHI/HiTracking , which resulted in a crash of workflow 150 in the IB since the merging of PR #28300. This is now solved by this PR.

#### PR validation:

Worrkflow 150.0 now runs to completion

@jeongeun

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
please abort

**Comment by perrotta** [comment]
please test workflow 150.0

**Comment by perrotta** [comment]
+1
- It fixes the tracking sequence for HI Phase1
- Wf 150.0  now runs successfully, other workflows not affected

**Comment by fabiocos** [comment]
+1

@perrotta thanks!

**Pull request merged**
