### PR TITLE
preparing for dasgoclient: implement get_value in cmssw_das_client

### PR DESCRIPTION
**Pull request by smuzaffar**
copied das_client.get_value from das_client into cmssw_das_client

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by Dr15Jones** [comment]
@smuzaffar I assume you'll approve this one when you are happy with it?

**Comment by smuzaffar** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Comment by Dr15Jones** [comment]
This broke a unit test: 
https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc6_amd64_gcc530/CMSSW_9_2_X_2017-05-18-2300/unitTestLogs/JetMETCorrections/Type1MET

**Pull request merged**
