### PR TITLE
Phase2-TB71 Add a new scenario to evaluate the August 2023 HGCal Test Beam

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Add a new scenario to evaluate the August 2023 HGCal Test Beam

#### PR validation:

Checked using dumping geometry for fireworks and with overlap checks

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
+geometry

**Comment by bsunanda** [comment]
@srimanob Please approve this

**Comment by srimanob** [comment]
+Upgrade

**Comment by perrotta** [comment]
+1

**Pull request merged**
