### PR TITLE
Migrate L1trigger from boost::format to {fmt}

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Migrate from `boost::format` to `fmt::sprintf`.

### CODE REVIEW

**Comment by fwyzard** [comment]
Just a suggestion, now that `{fmt}` is available in CMSSW.

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by silviodonato** [comment]
merge

**Comment by rekovic** [comment]
+1

**Pull request merged**
