### PR TITLE
bsunanda:Run2-alca68 Update all analysis scripts for IsoTrack calibrations

### PR DESCRIPTION
**Pull request by bsunanda**
These scripts are shared by a group of 7-8 people for IsoTrack calibration

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by mmusich** [comment]
+1

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by mmusich** [comment]
+1

**Comment by davidlange6** [comment]
+1
thanks - though git mv would be a good thing to learn about in order to make this more clear for next time...

**Pull request merged**
