### PR TITLE
Update dqmservices for protobuf changes

### PR DESCRIPTION
**Pull request by mrodozov**

### CODE REVIEW

**Comment by mrodozov** [comment]
@cmsbuild please test with cms-sw/cmsdist#3835

**Comment by mrodozov** [comment]
code checks misinterprets a lambda function definition with a variable definition and adds semicolon at the end of the square brackets, which leads to nonsense that doesn't compile could you please edit the label to test this ?

**Comment by smuzaffar** [comment]
please test with cms-sw/cmsdist#3835

**Comment by mrodozov** [comment]
please test with cms-sw/cmsdist#3835

**Comment by smuzaffar** [comment]
assign reconstruction
@slava77 , any objection on updating tensorflow to 1.6.0. We wanted to update protobuf and noticed that we can update tensorflow too which is using the newer protobuf.

**Comment by slava77** [comment]
> New categories assigned: reconstruction

perhaps we should just add a possibility for assignment of the externals.

**Comment by slava77** [comment]
Looking at https://github.com/tensorflow/tensorflow/compare/v1.5.0...v1.6.0
I see that 
 tensorflow/core/common_runtime/direct_session.cc and  tensorflow/core/common_runtime/direct_session.h have changed in some non-trivial way.

I see that jenkins tests passed. So, changes are probably not essential for the job integrity.
Still, a consistent update of the NTSession and TBBSession would be nice.

**Comment by dmitrijus** [comment]
+1

This is fine for DQM, however, we will need to bump fastHadd version once this is merged (and goes into production).

**Comment by slava77** [comment]
@riga 
please check the notes in https://github.com/cms-sw/cmssw/pull/22568#issuecomment-372456091
Are you available to update the CMSSW session implementations?

@smuzaffar @mrodozov 
how should we handle the update to NTSession and TBBSession (especially if it's considered somewhat essential).
The API did not change and the update in NTSession and TBBSession  can probably be done out of sync, but I'd like to hear from @riga  that this way (update to upstream implementation later) we will not trigger some unwanted issues.

**Comment by riga** [comment]
@slava77 Yes, I'm available for updating the TF session code. I will start looking into the diffs tomorrow morning.

**Comment by slava77** [comment]
@riga 
Thank you for providing the update quickly.

Was it clear that there were any operational issues that require TF 1.6 update to be in syn with  #22603 ?
I wanted to reduce integration inter-dependencies.

**Comment by riga** [comment]
@slava77 I couldn't test locally, but the interface changes should be backwards-compatible with TF 1.5 (most of the changes just do some restructuring of internal members).

**Comment by slava77** [comment]
unassign reconstruction
[in case it works]
we'll follow up in #22603

**Comment by fabiocos** [comment]
+1

**Pull request merged**
