### PR TITLE
Remove BasicFilter.h

### PR DESCRIPTION
**Pull request by Teemperor**
This file tries to define a "vitrual"[sic] function and wasn't
touched in years, so I think we can remove this.

### CODE REVIEW

**Comment by Teemperor** [comment]
Part of the work going on regarding the C++ modules migration of CMSSW (tracked as issue https://github.com/cms-sw/cmssw/issues/15248). This PR is not meant to refactor things, but just to make these headers compile.

**Comment by davidlange6** [comment]
please test

**Comment by slava77** [comment]
```
git grep -w -l BasicFilter
PhysicsTools/UtilAlgos/interface/BasicFilter.h
PhysicsTools/UtilAlgos/interface/EDFilterObjectWrapper.h
PhysicsTools/UtilAlgos/interface/EDFilterWrapper.h
```

This file BasicFilter is provided as a skeleton.
If there are compilation problems with it, it would be better to fix them.
Otherwise, some relevant changes need to be made in EDFilterObjectWrapper.h and EDFilterWrapper.h to contain appropriate documentation how to get a skeleton code

**Comment by davidlange6** [comment]
merge

**Comment by Teemperor** [comment]
Seems like this got already merged (sorry, hard to keep track with all the cmsbuild notifications). @slava77 Shall I make a new PR where I readd this file with the typo fixed?

**Comment by davidlange6** [comment]
sorry I missed @slava77  comment.

however EDFilter(Object)Wrapper do not directly use BasicFilter. So i don't see the relevance.
It looks like at some point in history there was a BasicMuonFilter (still referenced by BasicFilter!), but its gone. Looks like obsolete stuff to me.

**Comment by slava77** [comment]
as I said, I interpreted BasicFilter as a skeleton example.
This pattern may often not have a compiled code.

Perhaps I'm wrong and the other two files just have outdated edits referring to BasicFilter.
It would help to scrub mentions like this when files are removed.
(git grep should return no hits before git rm)

**Pull request merged**
