### PR TITLE
Run3-sim98 Make use of ESGetToken in some of the classes in SimG4Core/HelpfulWatchers

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Make use of ESGetToken in some of the classes in SimG4Core/HelpfulWatchers

#### PR validation:

Use the runTheMatrix test workflows

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
@bsunanda , is this watcher thread safe? if yes, in constructor you may add a line

isMT(true);

**Comment by bsunanda** [comment]
@civanch I don't think it is thread safe - it needs to run on single thread

**Comment by civanch** [comment]
+1

**Pull request merged**
