### PR TITLE
Update to new ONNXRuntime api

### PR DESCRIPTION
**Pull request by iarspider**
#### PR description:

Companion PR for cms-sw/cmsdist#8397

#### PR validation:

Bot tests

### CODE REVIEW

**Comment by smuzaffar** [comment]
code-checks with cms.week1.PR_744c3e3b/56.0-e224ff2c6291bfae75fddf2c3a257b07

**Comment by smuzaffar** [comment]
test parameters:
- pull_request = https://github.com/cms-sw/cmsdist/pull/8397

**Comment by smuzaffar** [comment]
test parameters:
- pull_request = cms-sw/cmsdist#8397

**Comment by mandrenguyen** [comment]
+reconstruction

**Comment by smuzaffar** [comment]
@cms-sw/dqm-l2 can you please review this? This change is needed for `onnxruntime 1.14.1`

@cms-sw/orp-l2 , this should be merged along with https://github.com/cms-sw/cmsdist/pull/8397

**Comment by emanueleusai** [comment]
+1

**Comment by rappoccio** [comment]
+1

**Pull request merged**
