### PR TITLE
Changes from scram build code-format-all

### PR DESCRIPTION
**Pull request by wddgit**
#### PR description:

Includes only changes from scram build code-format-all (clang format) and nothing else. This PR includes the last 2 Core packages. These are the only Core packages where clang format was not already run and the results already in a merged or pending PR. The one exception is the Skeletons package, where there is in an issue to remind us of the problems that need to be resolved.

#### PR validation:

The only test I performed was checking that the revised packages compile and build.

### CODE REVIEW

**Comment by wddgit** [comment]
please test

**Comment by makortel** [comment]
EOS is giving problems again?

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
+core

**Comment by fabiocos** [comment]
+1

**Pull request merged**
