### PR TITLE
RPC Fix for SLHC Code to 74X migration

### PR DESCRIPTION
**Pull request by pietverwilligen**

### CODE REVIEW

**Comment by civanch** [comment]
@pietverwilligen , trivial comments:

why you need "float s1 = static_cast<float>(1)-0.5;" and not "float s1=0.5;"?
std::cout should be commented out and/or substituted by LogInfo

**Comment by davidlange6** [comment]
closing in 74x - there is the same PR open in 75x (now the development release)

**Comment by pietverwilligen** [comment]
Hi Vladimir

Ok, will clean up the code for the float. However the std::cout I prefer to
keep. This is a tester, not code that is run in a reco or sim sequence.
greets
Piet

On Sun, Feb 15, 2015 at 9:24 PM, Vladimir Ivantchenko <
notifications@github.com> wrote:

> @pietverwilligen <https://github.com/pietverwilligen> , trivial comments:
>
> why you need "float s1 = static_cast(1)-0.5;" and not "float s1=0.5;"?
> std::cout should be commented out and/or substituted by LogInfo
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cms-sw/cmssw/pull/7742#issuecomment-74434991>.
>



-- 
Piet Verwilligen

INFN -- Sezione di Bari
Via E. Orabona 4
I-70125 Bari, Italy
Phone: +39 345 74 70 642

**Comment by pietverwilligen** [comment]
Hi David

I did not quite understand. Did you reopen the same PR7742 for 75X, or do I
have to do that and request the PR again?
Thanks
Piet

On Wed, Feb 18, 2015 at 8:28 AM, David Lange <notifications@github.com>
wrote:

> Closed #7742 <https://github.com/cms-sw/cmssw/pull/7742>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cms-sw/cmssw/pull/7742#event-237484964>.
>



-- 
Piet Verwilligen

INFN -- Sezione di Bari
Via E. Orabona 4
I-70125 Bari, Italy
Phone: +39 345 74 70 642

**Comment by civanch** [comment]
Hi Piet, just yesterday 7_5_X is created for new development, 7_4_X is focused on DIGI-RECO for start-up. I take out the concern for std::cout in test and your PR was cloned to 7774, now it is fully signed for 7_5_X. David have closed this one because it is not needed for 7_4_0.

**Comment by pietverwilligen** [comment]
Thanks a lot Vladimir.

**Pull request closed without merging**
