### PR TITLE
MTD geometry migration to DD4hep: test configuration and basic test analyzers

### PR DESCRIPTION
**Pull request by fabiocos**
#### PR description:

Initial development to migrate the MTD geometry description to the DD4hep backend. In this PR:

- a new phase 2 scenario D50 is introduced to reorganize the geometry components configuration in a cleaner and more standard way, both for the old and new backend. The geometry description obtained in this way is equivalent to D46 (last MTD geometry cleaning) and should serve also as the baseline for the integration of the new ETL description based on the MTD TDR. Materials are reorganized but the definition is kept unchanged for the time being;

- the initial DD4hep test configuration provided by @ianna is refreshed to have it fully operational, and a tracker mother volume is defined to avoid all the internal tracker complications. This volume has been verified to be equal to the one of D47;

- the two test analyzers TestMTDNumbering and TestMTDPosition have been rewritten for DD4hep, and the output compared with the original versions based on DetectorDescription. The numbering is equal (outputs differ only for the use of namespaces in the legacy volume paths), the reference positions appear identical in BTL, with the only differences being in rototranslation dumps:

```
< Translation vector and Rotation components: ,   1173.3774,     79.9841,     17.9438,     -0.1199,     -0.0000,      0.9928,      0.9928,     -0.0000,      0.1199,     -0.0000,      1.0000,     -0.0000
---
> Translation vector and Rotation components: ,   1173.3774,     79.9841,     17.9437,     -0.1199,     -0.0000,      0.9928,      0.9928,     -0.0000,      0.1199,     -0.0000,      1.0000,     -0.0000
```

while in ETL some reference positions appear different due to an issue with translations (z coordinate of ETL, to be further investigated):

```
< Translation vector and Rotation components: ,    313.5000,      0.0000,   3043.5000,      0.0000,     -1.0000,      0.0000,      1.0000,      0.0000,     -0.0000,     -0.0000,      0.0000,      1.0000
< Center global   =     313.500000      0.000000   3043.500000 r =     313.500000 phi =       0.000000
---
> Translation vector and Rotation components: ,    313.5000,     -0.0000,   3017.8500,     -0.0000,     -1.0000,     -0.0000,      1.0000,      0.0000,     -0.0000,     -0.0000,      0.0000,      1.0000
> Center global   =     313.500000     -0.000000   3017.850000 r =     313.500000 phi =      -0.000000
24c24
< Corner 1 global =     266.000000     24.500000   3043.650000 DeltaR =      53.446445
---
> Corner 1 global =     266.000000     24.500000   3018.000000 DeltaR =      53.446445
```

This code serves as a basis for any further debugging/development.

#### PR validation:

Code compiles and run, analyzers produce output that can be compared with the older versions.

### CODE REVIEW

**Comment by fabiocos** [comment]
code-checks

**Comment by fabiocos** [comment]
@pmeridian @parbol FYI

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by fabiocos** [comment]
These latest fixes solve the residual discrepancies in dumpETLpos. Here are the (irrelevant) differences in the centers seen:

```
< Center global   =     313.500000     -0.000000   3017.850000 r =     313.500000 phi =      -0.000000
> Center global   =     313.500000      0.000000   3017.850000 r =     313.500000 phi =       0.000000
< Center global   =     404.690000     -0.000000   3036.850000 r =     404.690000 phi =      -0.000000
> Center global   =     404.690000      0.000000   3036.850000 r =     404.690000 phi =       0.000000
< Center global   =     489.880000     -0.000000   3017.850000 r =     489.880000 phi =      -0.000000
> Center global   =     489.880000      0.000000   3017.850000 r =     489.880000 phi =       0.000000
< Center global   =      -0.000000    489.880000   3017.850000 r =     489.880000 phi =      90.000000
> Center global   =       0.000000    489.880000   3017.850000 r =     489.880000 phi =      90.000000
< Center global   =    -489.880000     -0.000000   3017.850000 r =     489.880000 phi =    -180.000000
> Center global   =    -489.880000      0.000000   3017.850000 r =     489.880000 phi =     180.000000
< Center global   =     581.610000     -0.000000   3036.850000 r =     581.610000 phi =      -0.000000
> Center global   =     581.610000      0.000000   3036.850000 r =     581.610000 phi =       0.000000
< Center global   =      -0.000000    581.610000   3036.850000 r =     581.610000 phi =      90.000000
> Center global   =       0.000000    581.610000   3036.850000 r =     581.610000 phi =      90.000000
< Center global   =    -581.610000     -0.000000   3036.850000 r =     581.610000 phi =    -180.000000
> Center global   =    -581.610000      0.000000   3036.850000 r =     581.610000 phi =     180.000000
< Center global   =     665.130000     -0.000000   3017.850000 r =     665.130000 phi =      -0.000000
> Center global   =     665.130000      0.000000   3017.850000 r =     665.130000 phi =       0.000000
< Center global   =     757.360000     -0.000000   3036.850000 r =     757.360000 phi =      -0.000000
> Center global   =     757.360000      0.000000   3036.850000 r =     757.360000 phi =       0.000000
< Center global   =      -0.000000    757.360000   3036.850000 r =     757.360000 phi =      90.000000
> Center global   =       0.000000    757.360000   3036.850000 r =     757.360000 phi =      90.000000
< Center global   =     839.190000     -0.000000   3017.850000 r =     839.190000 phi =      -0.000000
> Center global   =     839.190000      0.000000   3017.850000 r =     839.190000 phi =       0.000000
< Center global   =      -0.000000    839.190000   3017.850000 r =     839.190000 phi =      90.000000
> Center global   =       0.000000    839.190000   3017.850000 r =     839.190000 phi =      90.000000
< Center global   =     931.880000     -0.000000   3036.850000 r =     931.880000 phi =      -0.000000
> Center global   =     931.880000      0.000000   3036.850000 r =     931.880000 phi =       0.000000
< Center global   =      -0.000000    931.880000   3036.850000 r =     931.880000 phi =      90.000000
> Center global   =       0.000000    931.880000   3036.850000 r =     931.880000 phi =      90.000000
< Center global   =      -0.000000   -931.880000   3036.850000 r =     931.880000 phi =     -90.000000
> Center global   =       0.000000   -931.880000   3036.850000 r =     931.880000 phi =     -90.000000
< Center global   =    1012.000000     -0.000000   3017.850000 r =    1012.000000 phi =      -0.000000
> Center global   =    1012.000000      0.000000   3017.850000 r =    1012.000000 phi =       0.000000
< Center global   =      -0.000000   1012.000000   3017.850000 r =    1012.000000 phi =      90.000000
> Center global   =       0.000000   1012.000000   3017.850000 r =    1012.000000 phi =      90.000000
< Center global   =    1105.110000     -0.000000   3036.850000 r =    1105.110000 phi =      -0.000000
> Center global   =    1105.110000      0.000000   3036.850000 r =    1105.110000 phi =       0.000000
< Center global   =      -0.000000   1105.110000   3036.850000 r =    1105.110000 phi =      90.000000
> Center global   =       0.000000   1105.110000   3036.850000 r =    1105.110000 phi =      90.000000
< Center global   =    1183.500000     -0.000000   3017.850000 r =    1183.500000 phi =      -0.000000
> Center global   =    1183.500000      0.000000   3017.850000 r =    1183.500000 phi =       0.000000
< Center global   =       0.000000    489.880000  -3017.850000 r =     489.880000 phi =      90.000000
> Center global   =      -0.000000    489.880000  -3017.850000 r =     489.880000 phi =      90.000000
< Center global   =       0.000000    581.610000  -3036.850000 r =     581.610000 phi =      90.000000
> Center global   =      -0.000000    581.610000  -3036.850000 r =     581.610000 phi =      90.000000
< Center global   =       0.000000    757.360000  -3036.850000 r =     757.360000 phi =      90.000000
> Center global   =      -0.000000    757.360000  -3036.850000 r =     757.360000 phi =      90.000000
< Center global   =       0.000000   -757.360000  -3036.850000 r =     757.360000 phi =     -90.000000
> Center global   =      -0.000000   -757.360000  -3036.850000 r =     757.360000 phi =     -90.000000
< Center global   =       0.000000    839.190000  -3017.850000 r =     839.190000 phi =      90.000000
> Center global   =      -0.000000    839.190000  -3017.850000 r =     839.190000 phi =      90.000000
< Center global   =       0.000000   -839.190000  -3017.850000 r =     839.190000 phi =     -90.000000
> Center global   =      -0.000000   -839.190000  -3017.850000 r =     839.190000 phi =     -90.000000
< Center global   =       0.000000    931.880000  -3036.850000 r =     931.880000 phi =      90.000000
> Center global   =      -0.000000    931.880000  -3036.850000 r =     931.880000 phi =      90.000000
< Center global   =       0.000000   1012.000000  -3017.850000 r =    1012.000000 phi =      90.000000
> Center global   =      -0.000000   1012.000000  -3017.850000 r =    1012.000000 phi =      90.000000
< Center global   =       0.000000   1105.110000  -3036.850000 r =    1105.110000 phi =      90.000000
> Center global   =      -0.000000   1105.110000  -3036.850000 r =    1105.110000 phi =      90.000000
< Center global   =       0.000000   1183.500000  -3017.850000 r =    1183.500000 phi =      90.000000
> Center global   =      -0.000000   1183.500000  -3017.850000 r =    1183.500000 phi =      90.000000
< Center global   =       0.000000  -1183.500000  -3017.850000 r =    1183.500000 phi =     -90.000000
> Center global   =      -0.000000  -1183.500000  -3017.850000 r =    1183.500000 phi =     -90.000000
```

As this description is going to be replaced by another one that will not depend on the tracker algorithm I consider this satisfactory.

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
@ianna @kpedro88 this PR needs to be rebased after the integration of #28387

**Comment by ianna** [comment]
+1

**Comment by fabiocos** [comment]
rebased on CMSSW_11_0_X_2019-11-18-1100

**Comment by Dr15Jones** [comment]
Thanks for doing the esConsumes conversion!

**Comment by fabiocos** [comment]
@Dr15Jones I would like to use these analyzers as examples for the geometry navigation in DD4hep,
so I thought that having an up-to-date access to the records might be useful (although it was working correctly even with the older syntax)

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
@ianna @kpedro88 I consider this PR as complete for its purpose, i.e. to have a testbed for the MTD geometry in DD4hep to start with. Scenario D50 should be considered as a checkpoint to technically compare DetectorDescription and DD4hep implementations, using a new organization for data files, but it is not adding any new description, so I would not push to have a complete set of relvals corresponding to it (as they should not provide anything different wrt D46). This will be the basis for the initial implementation of the new ETL design (xml almost ready to be integrated, numbering scheme to be setup).

@ianna the latest updates after your last signature are merely technical, they do not change the geometrical description of the detector

**Comment by ianna** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade

**Comment by fabiocos** [comment]
+operations

**Comment by fabiocos** [comment]
+1

**Pull request merged**
