### PR TITLE
Fixing HGCal Hexagonal Geometry Round 2

### PR DESCRIPTION
**Pull request by lgray**
Continuation of #13038.

This PR fixes a hex wafer numbering bug arising from having used a map to store a list of wafer copy numbers. This meant that wafer indices did not contiguously span a given layer, and that property was assumed elsewhere in the code. This led to numerous out-of-bounds det ids in certain regions of the HGCal.

Part two of the fix was then to realize that "contiguous set of det ids" is not well defined in this geometry since the inner and outer radii are changing in the layers. The valid det ids in each layer are now indexed by a hash map.

The out-of-bounds detids no longer appear even in large samples, but there are a few cases where the sim and reco geometries do not map to each other correctly. That will come in another round of fixes.

@bsunanda

### CODE REVIEW

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by ianna** [comment]
@cmsbuild - it does not look like the errors are related to this PR

**Comment by lgray** [comment]
@slava77 is this error fixed in another PR? (or the next IB?)

**Comment by slava77** [comment]
@cmsbuild please test
[not sure if this retest is triggered too soon]

add on tests in the baseline IB look OK https://cmssdt.cern.ch/SDT/cgi-bin//showAddOnLogs.py/slc6_amd64_gcc493/www/mon/8.0-mon-23/CMSSW_8_0_X_2016-01-25-2300/addOnTests/
it looks like a file availability problem
https://hypernews.cern.ch/HyperNews/CMS/get/sw-develtools/2371/1/1/1/1/1/1/1.html

**Comment by Martin-Grunewald** [comment]
please test
(HIon problem should be solved)

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
Please begin review. Do not plan to add anything else.

**Comment by ianna** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by lgray** [comment]
@davidlange6 Would appreciate if this one is in the IBs next week as well. Just making sure it didn't slip past you.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
