### PR TITLE
HLT development incl. use of v4 of L1T (80X)

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
HLT development incl. use of v4 of L1T (80X)
This PR includes #13717 as that one is still not integrated!

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by perrotta** [comment]
@Martin-Grunewald : sorry Martin, but one last fix was still missing (see discussion in CMSHLT-711)
Committed here, I'm going to do the same also for the 81X branch

**Comment by perrotta** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by Martin-Grunewald** [comment]
@Dr15Jones, @fabozzi, @rekovic, @srimanob, @hengne, @mulhearn

This PR is replacing #13717 already signed by you, so please re-sign this one!

**Comment by Dr15Jones** [comment]
+1

**Comment by fabozzi** [comment]
+1

**Comment by mulhearn** [comment]
+1

**Pull request merged**
