### PR TITLE
Add unit test for Run 2 Scouting data formats

### PR DESCRIPTION
**Pull request by wddgit**
#### PR description:

Add a new unit test for the Run 2 Scouting data formats. This generates a data file containing Run 2 Scouting objects with known content. Then it reads it. It verifies that when we read it we obtain values that match the known written values for all the data fields in the objects. In particular all containers have content so all contained types are also read.

It also reads the old files in the DataFormats-Scouting data repository which are listed in the shell script. The plan is that each time a Run 2 Scouting data format is modified an additional file will be added. The data files required for this PR were generated with releases 8_0_7 (2016 data), 9_4_0 (2017 data), and 10_2_0 (2018 data). Note that to create those files those older releases were patched with extra test code which is in the first 3 commits in this PR.

There are 10 events with content and vector sizes varying from event to event.

This PR depends on the external DataFormats-Scouting, cms-data/DataFormats-Scouting#2. See issue #41040 for more information.

#### PR validation:

This only adds a unit test in DataFormats/Scouting which passes. It shouldn't affect anything else.

### CODE REVIEW

**Comment by wddgit** [comment]
please test with cms-data/DataFormats-Scouting#2

**Comment by wddgit** [comment]
Should I implement a PR to delete the older tests in the DataFormats/Scouting directory? I think it should be a separate PR.

**Comment by makortel** [comment]
> Should I implement a PR to delete the older tests in the DataFormats/Scouting directory? I think it should be a separate PR.

I agree it should be a separate PR. Please do (but let me tag @missirol just to make sure he doesn't object). Thanks!

**Comment by wddgit** [comment]
Note, I added use of argparse to the configuration file used to read files and that has the advantage that we do not need to replicate the configuration file for every old input file. I also applied that to the Run 3 tests in this PR. That is the only change to the run 3 tests and it allowed deleting a configuration file. Other than that, this PR is just follows the pre-existing pattern from the Run 3 unit tests.

**Comment by missirol** [comment]
> I agree it should be a separate PR. Please do (but let me tag @missirol just to make sure he doesn't object). Thanks!

No objection (indeed, I was going to ask if I should remove those older tests). Thanks for adding the improved tests!

Maybe it's worth asking if it's okay to leave the 'old' tests in place in 13_0_X and 13_1_X, or if it is preferred to backport the new Scouting tests to those older cycles.

**Comment by makortel** [comment]
> Maybe it's worth asking if it's okay to leave the 'old' tests in place in 13_0_X and 13_1_X, or if it is preferred to backport the new Scouting tests to those older cycles.

David and I discussed about that last week, and our plan is to leave the old tests in place in 13_0_X and 13_1_X. New developments (and external updates) get tested in `master` first, and we should avoid hard to backport anything that would even remotely seem to break the schema evolution into 13_0_X or 13_1_X, so backporting the new tests didn't seem to have any real value.

**Comment by missirol** [comment]
> > Maybe it's worth asking if it's okay to leave the 'old' tests in place in 13_0_X and 13_1_X, or if it is preferred to backport the new Scouting tests to those older cycles.
> 
> David and I discussed about that last week, and our plan is to leave the old tests in place in 13_0_X and 13_1_X. New developments (and external updates) get tested in `master` first, and we should avoid hard to backport anything that would even remotely seem to break the schema evolution into 13_0_X or 13_1_X, so backporting the new tests didn't seem to have any real value.

Okay, thanks for clarifying.

**Comment by wddgit** [comment]
I'll submit a PR to remove the old tests as soon as this PR is merged. I'll wait to avoid potential conflicts in BuildFile.xml.

**Comment by makortel** [comment]
+core

**Comment by perrotta** [comment]
+1
- This PR only touches unit tests: difference observed in the test outputs depends on the modified Phase2 HLT menu, whose PR is also included in the bot tests

**Pull request merged**
