### PR TITLE
Updated version of the boosted double SV tagger (74X)

### PR DESCRIPTION
**Pull request by ferencek**
Partial backport of #12442 (changes to MiniAOD not included).

**Update (Dec. 6, 2015):** Added backport of #12680

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
+1

For #12446 0d47850d9d28ed070b636a72c1dba25cb4de095a

Updating the boosted double SV tagger. #12442 and #12445 are the 80X and 76X versions of this PR.

The code changes are satisfactory, and Jenkins tests against baseline CMSSW_7_4_X_2015-11-16-1100 show no significant differences,

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
+1

For #12446 3ec8e194f5f66a19040d78c48ae9bf6a3c23f6a3

Second approval after small code changes. #12442 and #12445 are the 80X and 76X versions of this PR.

The code changes are satisfactory, and Jenkins tests still show no significant differences. See #12442 for detail on extended test results, which show no problems.

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
+1

For #12446 3ce12d5eac61509c8690689cc2e8ecd1934c9568

Third approval, following multi-threaded bug fix.

The code change is satisfactory, and Jenkins tests against baseline CMSSW_7_4_X_2015-12-06-1100 show no significant differences, as expected.

**Pull request merged**
