### PR TITLE
Run2-alca123 Modify AlCaReco code to accommodate new EE thresholds

### PR DESCRIPTION
**Pull request by bsunanda**
Needed for 2018 runs

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by lpernie** [comment]
+1

**Comment by bsunanda** [comment]
@fabiocos Fabio this PR needs to be back ported to 10_1 for AlCaReco jobs in Tier0. Could you please integrate this so that I can make the PR for back porting

**Comment by fabiocos** [comment]
+1

**Pull request merged**
