### PR TITLE
Replace state machine in EventProcessor

### PR DESCRIPTION
**Pull request by Dr15Jones**
Replaced the use of the boost state machin in the EventProcessor with a series of simple Transition Processors. This new structure paves the way to allowing multiple concurrent Runs and LuminosityBlocks in the system.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
