### PR TITLE
Support hitless seeds in GroupedCkfTrajectory

### PR DESCRIPTION
**Pull request by folguera**
Enable hitless seed compatibility to the GroupedCkfTrajectory so it can be used in the muon HLT reconstruction.  Change is transparent to any user of the GroupedCkfTrajectory. 

Removed unused function in BaseCkfTrajectoryBuilder.  Will need back port to 92X.

### CODE REVIEW

**Comment by perrotta** [comment]
@folguera , this PR has already conflicts to be solved: please fix them

**Comment by VinInn** [comment]
+1

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
@folguera : just in order to understand how this works now, in line

**Comment by folguera** [comment]
Hi @perrotta,

I can investigate how this is dealt with, but I don't know the details about this. I just simply changed that line that was also used by the older CkfTrajectoryBuilder and that we were using for the muon HLT reconstruction. 

In our case the temp trajectory has no measurement (hitless) but a direction of propagation, so I'm not sure that you don't have the direction in any case.  Am I making sense?

**Comment by VinInn** [comment]
@perotta, what makes you thinking that traj.direction() has no meaning if when traj.empty()?

**Comment by perrotta** [comment]
Ok, that direction is indeed just an enum, which keeps its meaning even if traj.empty(), see DataFormats/TrajectorySeed/interface/PropagationDirection.h: this is basically the answer to my question

**Comment by perrotta** [comment]
You write: "Change is transparent to any user of the GroupedCkfTrajectory". This means that currently all user never end up with traj.empty(), otherwise there should be some different behaviour for them.
The question is the following: is there any parameter or instruction in the code that prevents empty trajectories now, that will be switched off when you'll use the code for hitless seeds?

**Comment by VinInn** [comment]
@perotta,
is the opposite. currently a "user" with a hitless seed will produce a crash (in the first version there was even an assert)
now it will go through

Essentially this re-establishes the behaviour prior to Run2

btw there are no "user" of GroupedCkfTrajectory,  only TRK-POG

**Comment by perrotta** [comment]
(Slowly trying to understand how this code works... thank you @VinInn)

Well, currently in case of a hitless seed the method returns an uninitialized StateAndLayers(), which does not obviously imply to me that there will be a crash: does it?

If it does not crash, then it is not true that "Change is transparent to any user of the GroupedCkfTrajectory", unless there is some parameter or part of the code that prevents it.

Then, simplifying, my question is still: it never happened that some hitless seed entered that method AND the code did not crash? IOW: it is true that "Change is transparent to any user of the GroupedCkfTrajectory"?

**Comment by VinInn** [comment]
> On 21 Sep, 2017, at 3:49 PM, perrotta <notifications@github.com> wrote:
> 
> (Slowly trying to understand how this code works... thank you @VinInn)
> 
> Well, currently in case of a hitless seed the method returns an uninitialized StateAndLayers(), which does not obviously imply to me that there will be a crash: does it?
well it will fill the output of 
"CkfPattern: empty traj. Skipping."
and we never been reported such a case
> 
> If it does not crash, then it is not true that "Change is transparent to any user of the GroupedCkfTrajectory", unless there is some parameter or part of the code that prevents it.
> 
> Then, simplifying, my question is still: it never happened that some hitless seed entered that method AND the code did not crash? IOW: it is true that "Change is transparent to any user of the GroupedCkfTrajectory"?
Are you pretending a first principle proof?
Just be happy that you do not see any regression.
TRK-POG is happy

**Comment by perrotta** [comment]
+1
- It makes GroupedCkfTrajectory compatible to hit-less seeds, as it is already in CkfTrajectoryBuilder
- No visible regression on jenkins test results
- Not obvious whether it can affect also current use cases, but if so it is only with a negligible rate (it should have issued warning messages that were never noticed so far), and in any case it is endorsed by tracking POG, see https://github.com/cms-sw/cmssw/pull/20556#issuecomment-331163865

**Comment by davidlange6** [comment]
are these changes thought to be part of a non-reproducibility problem in dqm?
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_9_4_X_2017-09-17-2300+20556/22549/10042.0_ZMM_13+ZMM_13TeV_TuneCUETP8M1_2017_GenSimFull+DigiFull_2017+RecoFull_2017+ALCAFull_2017+HARVESTFull_2017/PixelPhase1V.html

**Comment by VinInn** [comment]
PixelPhase1 sim w/o any effect on reco?
yes.... (already reported several time)

**Comment by davidlange6** [comment]
It seems that way - sigh - would be great not to have that problem as we've beaten down other non-reproducibility and nan issues affecting the comparisons

**Comment by davidlange6** [comment]
+1

**Pull request merged**
