### PR TITLE
move edm plugin FedRawDataInputSource definition in the plugin directory

### PR DESCRIPTION
**Pull request by smuzaffar**
EDM plugin FedRawDataInputSource was defined in the shared library and so any edm plugin which links against EventFilterUtilities sees it and adds duplicate definitions. 

this should fix the error we have see in the latest 80X IBs
https://cms-sw.github.io/relvalLogDetail.html#slc6_amd64_gcc493;CMSSW_8_0_X_2015-11-18-1100

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

make sure that DQM/BeamMonitor is also rebuild along with this change.

**Comment by smuzaffar** [comment]
@davidlange6 , @slava77 I would like to include it for next IB 23h00 
any object on including this? This is just a clean up for the wrong plugin definition in the shared library

**Comment by slava77** [comment]
@smuzaffar 
which error is this fixing?

I see a lot of workflows failing due to 
```
from DQM.BeamMonitor.AlcaBeamMonitorClient_cff import *
  File "/afs/cern.ch/cms/sw/ReleaseCandidates/vol1/slc6_amd64_gcc493/cms/cmssw-patch/CMSSW_8_0_X_2015-11-18-1100/python/DQM/BeamMonitor/__init__.py", line 2, in 
    __path__.append(os.path.dirname(os.path.abspath(__file__).rsplit('/DQM/BeamMonitor/',1)[0])+'/cfipython/slc6_amd64_gcc493/DQM/BeamMonitor')
NameError: name 'os' is not defined
```
how is this related?
(OTOH, the matrix tests in jenkins tests of this PR passed OK)

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/12479	 4f7132d
- code change looks OK 
- jenkins tests pass (some tests failing in IB are passing with this PR; looks unrelated)

**Comment by smuzaffar** [comment]
FedRawDataInputSource  plugin was wrongly defined in the EventFilterUtilities shared library which is then used by many plugins from DQM/BeamMonitor/plugins (see https://github.com/cms-sw/cmssw/pull/12458#issuecomment-157680004). when we build with -j N then all of these DQM/BeamMonitor plugins generate cfipython/ file and all of try to write in cfipython/arch/DQM/BeamMonitor/_init__.py file. Due to parallel writing this file got curropeted 

```
#Automatically created by SCRAM
__path__.append(os.path.dirname(os.path.abspath(__file__).rsplit('/DQM/BeamMonitor/',1)[0])+'/cfipython/slc6_amd64_gcc493/DQM/BeamMonitor')
import os
__path__.append(os.path.dirname(os.path.abspath(__file__).rsplit('/DQM/BeamMonitor/',1)[0])+'/cfipython/slc6_amd64_gcc493/DQM/BeamMonitor’)
```

that is why we are seeing errors in IB

**Comment by slava77** [comment]
ah, ok, this is clear now
Please go ahead and merge this.

**Comment by smuzaffar** [comment]
merge

**Pull request merged**
