### PR TITLE
explicit type for input=output collections of `HLTJetsMatchedToFilteredJetsProducer`

### PR DESCRIPTION
**Pull request by missirol**
#### PR description:

The plugin `HLTPFJetsMatchedToFilteredJetsProducer` currently produces a collection of `reco::PFJet`s, but it uses `edm::View<reco::Candidate>` to read its input jet collection (I guess this was done to be able to use different types of jet collections in input, e.g. `reco::CaloJet`). The side effect is that the output `reco::PFJet`s are produced with [dummy values for what concerns their PF-specific quantities](https://github.com/cms-sw/cmssw/blob/CMSSW_12_6_0_pre2/HLTrigger/JetMET/interface/HLTPFJetsMatchedToFilteredJetsProducer.h#L77) (e.g. PF jet-energy fractions).

[CMSHLT-2450](https://its.cern.ch/jira/browse/CMSHLT-2450) highlighted a use case that would profit from having the full information of the input `reco::PFJet`s in the output product [0].

In order to so, this PR converts the plugin `HLTPFJetsMatchedToFilteredJetsProducer` to an instantiation of the plugin template `HLTJetsMatchedToFilteredJetsProducer`. With respect to the current version of `HLTPFJetsMatchedToFilteredJetsProducer`, one template argument is added, corresponding to the type of input and output jet collection, thus requiring the two to be equal.

Meant to be merely technical [1]. Changes are in principle possible [2], but not expected.

--

[0] This use case is not considered critical enough to justify backports of this PR.

[1] From a technical point of view, this update is fully backward-compatible, and it does not require any change to the HLT configurations.

[2] The output collection currently holds dummy values, and this PR will change that, filling them properly. If these values are used by anything downstream of these HLT modules (which I don't believe is the case, but I can't be 100% certain), this may lead to differences.

#### PR validation:

`addOnTests.py` and `runTheMatrix -l 11634.0` passed.

#### If this PR is a backport, please specify the original PR and why you need to backport that PR. If this PR will be backported, please specify to which release cycle the backport is meant for:

N/A

### CODE REVIEW

**Comment by missirol** [comment]
assign jetmet-pog

Asking Jet/MET L2s to review and sign off.

**Comment by missirol** [comment]
please test

**Comment by missirol** [comment]
+hlt

 - no differences in outputs of PR tests, as expected

**Comment by missirol** [comment]
@cms-sw/jetmet-pog-l2 , could you please review, and possibly sign, this PR? (see https://github.com/cms-sw/cmssw/pull/39431#issuecomment-1250020415)

FYI: @sparedes @alpakpinar

**Comment by miquork** [comment]
+1
This PR is very useful for us to get the PF fractions in.

**Comment by perrotta** [comment]
+1

**Pull request merged**
