### PR TITLE
update isSoftMuon( ) to use new soft muon Id

### PR DESCRIPTION
**Pull request by dayongwang**
Update isSoftMuon( ) to use new soft muon Id . The changes affect only analyses and not RECO or data format.  This can be included whenever convenient.

### CODE REVIEW

**Comment by slava77** [comment]
What's the plan for remaining 7X releases? Are you planning to propagate to 74X and 75X
or will these releases have a different isSiftMuon?

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by dayongwang** [comment]
@slava77 this fix was already there starting from CMSSW_7_3_0. This is just a backport to CMSS_7_2_X. Pull#8761 is the same backport to CMSSW_5_3_X

**Comment by battibass** [comment]
@slava77 to add just a little more info here: 73X and 74X are already OK as pointed by @dayongwang.
Anyhow, inclusion of this PR in 72X depends on your plan for the release, we have prepared the PR so that you have it in case you plan an update of 72X, but if the release cycle is closed (*) we are not pushing for an update only due to this change.
(*) https://indico.cern.ch/event/384917/session/4/contribution/3/material/slides/0.pdf

**Comment by slava77** [comment]
@cmsbuild please test
(the old comparisons got stuck)

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/8762	4224dc8
- code changes are the same as in 73X; they apply only to analysis-level parts of the code
- jenkins comparisons show no differences in stored RECO products
- jenkins comparisons show differences in DQM histograms filled with isSoftMuon ID function applied, as expected from the code change.

**Comment by davidlange6** [comment]
+1

**Comment by slava77** [comment]
@battibass @trocino
you can probably now update the twiki 
https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideMuonId#Soft_Muon
the function is now in 7_2_5 release

**Comment by battibass** [comment]
@slava77 done, thanks!

**Pull request merged**
