### PR TITLE
MTD: fix phase-2 config for RecoVertex and RecoTrack

### PR DESCRIPTION
**Pull request by kdeleo**
#### PR description:

In this PR a fix to RecoVertex and RecoTrack configuration files for phase-2 is made, following the changes made in https://github.com/cms-sw/cmssw/pull/43592.

For RecoVertex:
- address the comment from @slava77 in https://github.com/cms-sw/cmssw/pull/43592/files/e3e5c3ed60324c70b0f407820e10c6c5785863b3#diff-df2a0a87cb45575436295cfaa7ef61d4fcd0026ac5b9fc7351121de26ced0ef0
- add parameters for the use of MVA quality cut in 4D vertex reconstruction. The parameters were missing after the changes made in https://github.com/cms-sw/cmssw/pull/43846 for the configurations reorganization. 
 
For TrackValidation:
- remove time selection on generalTracksFromPV, enabled after the changes in https://github.com/cms-sw/cmssw/pull/43592. Since 3D vertices now have time, the tracks from 3D vertices have an additional time selection enabled, which causes a loss in efficiency of 5-10%. The time selection is removed for the validation of tracksFromPV.

#### PR validation:

Tested on TTbar_14TeV+PU200, expected changes in Tracking/TracksFromPV with the recovery of track efficiency loss.

### CODE REVIEW

**Comment by jfernan2** [comment]
@kdeleo you mention in the description a loss in efficiency of 5-10% but from the DQM plots of the PR test it looks like there is a slight gain in efficiency instead, am I right?

E.g. https://cmsweb.cern.ch/dqm/dev/start?runnr=1;dataset=/RelVal_wf24834_911_pr/CMSSW_14_1_X-PRcmssw_44872-62612/DQMIO;sampletype=offline_relval;filter=all;referencepos=overlay;referenceshow=all;referencenorm=False;referenceobj1=other%3A%3A/RelVal_wf24834_911_base/CMSSW_14_1_X-PRcmssw_44872-62612/DQMIO%3A%3A;referenceobj2=none;referenceobj3=none;referenceobj4=none;search=;striptype=object;stripruns=;stripaxis=run;stripomit=none;workspace=Everything;size=M;root=Tracking/TrackFromPV;focus=Tracking/TrackFromPV/effic_vs_coll;zoom=yes;

(blue is base, black is this PR)
overlay

**Comment by kdeleo** [comment]
> @kdeleo you mention in the description a loss in efficiency of 5-10% but from the DQM plots of the PR test it looks like there is a slight gain in efficiency instead, am I right?
> 
> E.g. https://cmsweb.cern.ch/dqm/dev/start?runnr=1;dataset=/RelVal_wf24834_911_pr/CMSSW_14_1_X-PRcmssw_44872-62612/DQMIO;sampletype=offline_relval;filter=all;referencepos=overlay;referenceshow=all;referencenorm=False;referenceobj1=other%3A%3A/RelVal_wf24834_911_base/CMSSW_14_1_X-PRcmssw_44872-62612/DQMIO%3A%3A;referenceobj2=none;referenceobj3=none;referenceobj4=none;search=;striptype=object;stripruns=;stripaxis=run;stripomit=none;workspace=Everything;size=M;root=Tracking/TrackFromPV;focus=Tracking/TrackFromPV/effic_vs_coll;zoom=yes;
> 
> (blue is base, black is this PR) overlay

@jfernan2 Yes, sorry for the confusion, the efficiency loss was caused by the previous PR in https://github.com/cms-sw/cmssw/pull/43592. This new PR is fixing the issue and there is an increase in efficiency.

**Comment by jfernan2** [comment]
+1

**Comment by fabiocos** [comment]
@cms-sw/dqm-l2 any comment about this PR?

**Comment by slava77** [comment]
> @cms-sw/dqm-l2 any comment about this PR?

ping

**Comment by slava77** [comment]
> > @cms-sw/dqm-l2 any comment about this PR?
> 
> ping

ping

**Comment by tjavaid** [comment]
+1

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
