### PR TITLE
Jingyu change layerout 74x

### PR DESCRIPTION
**Pull request by jingyucms**

### CODE REVIEW

**Comment by deguio** [comment]
thanks @jingyucms for this.
please submit the same for 75 and 76
ciao,
F.

**Comment by deguio** [comment]
ciao @jingyucms,
@diguida made me notice that probably the fed selected is the wrong one. shouldn't be the 813 used by default?

ciao,
F.

**Comment by jingyucms** [comment]
ciao @diguida @deguio 
813 should be connected with stage1layer2, and used as default 
809 should be connected with legacy gct
So I think this one should be fine

**Comment by deguio** [comment]
I read the opposite in the code. 809 is the one used by default.
F.

**Comment by deguio** [comment]
maybe I am missing something?

**Comment by deguio** [comment]
ok. the change makes sense.
F.

**Comment by deguio** [comment]
+1

**Comment by deguio** [comment]
@jingyucms 
this one is not yet merged. we have the chance to fix the subsystemFolder here. please modify the stage1 apps as follow:

-process.dqmEnv.subSystemFolder = 'L1T'
+process.dqmEnv.subSystemFolder = ‘L1TStage1'

and propagate the change to 75 and 76.
thanks,
F.

@vanbesien

**Comment by deguio** [comment]
-1
I guess that this one is now obsolete and can be closed.

**Pull request closed without merging**
