### PR TITLE
Add 2 workflows for default PR test, target for PPS plots

### PR DESCRIPTION
**Pull request by srimanob**
#### PR description:
PPS would like to request to add 2 workflows for PR test by default as the workflows used by default in CMSSW PR tests do not cover well the needs of PPS. Workflows include 2017C, 2018C Egamma (was ZeroBias but change after discussed with RECO conveners)

FYI
@jan-kaspar 

#### PR validation:
These workflows are part of relval_standard.py, and run regularly in relvals submitted by PdmV.

#### if this PR is a backport please specify the original PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by slava77** [comment]
> Workflows include 2017C, 2018C ZeroBias

isn't it possible to pick up a more physics-populated dataset
so that we can replace an existing workflow, instead of extending the "short" matrix?

**Comment by srimanob** [comment]
I would let @jan-kaspar comments on this, as the proposal from PPS on WFs which are sensible PPS cover only ZeroBias.

**Comment by jan-kaspar** [comment]
Let me copy here my answer to the parallel email thread.

We are almost indifferent about the trigger choice - we look at pile-up protons anyway. What is important to us is the run/LS selection. Therefore I believe that we can find a good candidate to suit the needs both of PPS and other sub-systems. For example, I looked at
  * 136.793, RunDoubleEG2017C -> about 20 reco protons in each PPS arm
  * 136.874, RunEGamma2018C -> about 40 reco protons in each PPS arm

The statistics is not huge, but probably OK. I looked in the generated cfg.py files and see maxEvents.input = 100. I presume that this is applied to all runTheMatrix jobs and therefore we cannot get (many) more protons by choosing a different dataset.

**Comment by slava77** [comment]
The number of events could be adjusted, but it has to be done with an assumption that the job still finishes in reasonable time (order 10 mins for the short matrix tests). So, 100 stays as a reasonable choice so far.

Did we have enough useful data in the low-pileup (or the high-beta*) runs?
This could be an alternative to get some more events with PPS, perhaps mostly for private tests rather than for the standard short matrix set up.

**Comment by srimanob** [comment]
List of workflows is updated as agreed.

**Comment by jan-kaspar** [comment]
> The number of events could be adjusted, but it has to be done with an assumption that the job still finishes in reasonable time (order 10 mins for the short matrix tests). So, 100 stays as a reasonable choice so far.

Thanks, I understand. I believe that those altogether ~100 reco protons would be sufficient
  * to spot a difference, when strictly no difference is expected
  * to judge on a trend, when it is expected.

> Did we have enough useful data in the low-pileup (or the high-beta*) runs?
> This could be an alternative to get some more events with PPS, perhaps mostly for private tests rather than for the standard short matrix set up.

For sure we will keep running our private tests - processing PPS data only we can afford many more events in a short time.

**Comment by chayanit** [comment]
+1

**Comment by jan-kaspar** [comment]
For completeness, I put here the proton xi histograms (sector 45, +z side) from the newly introduced WFs 136.793 (top) and 136.874 (bottom)

xi_hist_136 793

xi_hist_136 874

**Comment by kpedro88** [comment]
+upgrade

**Comment by silviodonato** [comment]
+1

**Pull request merged**
