### PR TITLE
Replaced AK4 and AK8 paths for particle net monitoring (2023)

### PR DESCRIPTION
**Pull request by marinakolosova**
This is a backport for:

Original PR: https://github.com/cms-sw/cmssw/pull/41655/
PR with fix:   https://github.com/cms-sw/cmssw/pull/41694

Changes:
* Renamed the paths to match the ones for 2023 (JIRA: [CMSHLT-2695](https://its.cern.ch/jira/browse/CMSHLT-2695), [CMSHLT-2759](https://its.cern.ch/jira/browse/CMSHLT-2759) )

### CODE REVIEW

**Comment by perrotta** [comment]
backport of https://github.com/cms-sw/cmssw/pull/41655
(plus bug fix in https://github.com/cms-sw/cmssw/pull/41694)

**Comment by perrotta** [comment]
please test workflow 140.031

**Comment by emanueleusai** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
