### PR TITLE
add timestamp dates in human readable form in the BeamSpot `DisplayParameters` template class

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

Simple addition of human readable timestamps (in UTC) for some of the `BeamSpotOnline` parameters in the dedicated paylaod inspector class.

#### PR validation:

Run the following command:

```bash
getPayloadData.py \
     --plugin pluginBeamSpotOnline_PayloadInspector \
     --plot plot_BeamSpotOnlineParameters \
     --tag BSonline_TS1_2023_bootstrap_v1 \
     --input_params '{}' \
     --time_type Lumi \
     --iovs '{"start_iov": "4294967297", "end_iov": "4294967297"}' \
     --db Prep \
     --test ;
```
and obtained the following plot:

image

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Not a backport, not to be backported

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by francescobrivio** [comment]
Thanks a lot for this Marco!
Just a (probably stupid) question: what happens for the "diff" plots (e.g. IOV vs IOV or tag vs tag)?

**Comment by mmusich** [comment]
>  Just a (probably stupid) question: what happens for the "diff" plots (e.g. IOV vs IOV or tag vs tag)?

nothing. We don't do the diff of the "second column" anyway: https://cern.ch/go/978l

**Comment by mmusich** [comment]
please test

**Comment by francescobrivio** [comment]
+1

 - PR according to description
 - tests are clean

**Comment by perrotta** [comment]
+1

**Pull request merged**
