### PR TITLE
Move slimmedAddPileupInfo to miniAOD_customizeMC (75X)

### PR DESCRIPTION
**Pull request by lgray**
backport of #10748

### CODE REVIEW

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
@slava77

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
@slava77 looks like this one got in a funny state. Please kick when possible.

**Comment by lgray** [comment]
@smuzaffar Hey, could you please manually start tests on this one in jenkins? It seems to have gotten into a bad state.

**Comment by smuzaffar** [comment]
In this case, the test which were started yesterday 
https://cmssdt.cern.ch/jenkins/job/ib-any-integration/lastFailedBuild/consoleFull
failed due to build machine failure. So jenkins was not able to update the status and cms-bot thinks that test are still running that is why it is not started them again.

I am started them now,

**Comment by lgray** [comment]
@smuzaffar thanks a lot!

**Comment by monttj** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
