### PR TITLE
[140X] implementation Z/Gamma plus Jet monitoring

### PR DESCRIPTION
**Pull request by esiam**
#### PR description:

Adding DQM code for Jets monitoring with Z/Gamma plus Jets analysis module. These changes were discussed with JME trigger group. ( @theochatzis , @slehti ) And they were also presented in the TSG group. ( @missirol , Silvia Goy Lopez ) 

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

This is a backport of this [PR](https://github.com/cms-sw/cmssw/pull/44411). The backport is needed because it will be used for monitoring 2024 pp data taking.

### CODE REVIEW

**Comment by mmusich** [comment]
backport of https://github.com/cms-sw/cmssw/pull/44411

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by theochatzis** [comment]
Hello, the test that doesn't pass [1004.0](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-cb959c/38599/runTheMatrixINPUT-results/1004.0_RunHI2011) is an old test from 2011 HION and furthermore it was not an issue in the PR to master branch. The reason is that this wf seems to not exist anymore in master. 
Maybe this should be removed also in 14_0_X? (do a backport of runTheMatrix.py from 14_1_X change? )
Best,
Sami and Theo

**Comment by mmusich** [comment]
>  Maybe this should be removed also in 14_0_X? (do a backport of runTheMatrix.py from 14_1_X change? )

attn: @mandrenguyen

**Comment by mandrenguyen** [comment]
> Hello, the test that doesn't pass [1004.0](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-cb959c/38599/runTheMatrixINPUT-results/1004.0_RunHI2011) is an old test from 2011 HION and furthermore it was not an issue in the PR to master branch. The reason is that this wf seems to not exist anymore in master. Maybe this should be removed also in 14_0_X? (do a backport of runTheMatrix.py from 14_1_X change? ) Best, Sami and Theo

Hi, indeed these old `--scenario HeavyIons` workflows are not going to work anymore.  Would you like  to remove it in this PR such that your PR can go forward?  Otherwise, I can take care of it in a separate PR, but that seems less practical.

**Comment by theochatzis** [comment]
Thanks @mandrenguyen , okay this makes sense. @esiam can you do an extra commit for this?

**Comment by esiam** [comment]
Hi! thank you all for your comments. I just pushed a new commit removing it.

**Comment by mmusich** [comment]
@esiam I am not sure to follow. 
You removed wf.  140.53 (# HIRun2011 HIMinBiasUPC) while the failing wf is 1004.0. See also the original commit in master from Matt that removed it: https://github.com/cms-sw/cmssw/commit/47ee613784d47bf9e9ecf237da2eebc94a393814.
Can you please explain?

**Comment by esiam** [comment]
Hi! Marco, I thought they were in runTheMatrix and did a false comparison of 140X and master. Apologies, and thank you for pointing the correct one. I will fix this.

**Comment by esiam** [comment]
I hope it is ok now. Sorry again.

**Comment by mmusich** [comment]
please test

**Comment by tjavaid** [comment]
+1
- spurious differences seen from unstable WF `12834.7` (open issue #39803 )

**Comment by srimanob** [comment]
+Upgrade

**Comment by AdrianoDee** [comment]
+pdmv
- wf-wise: "accidentally" back ports `1004` removal to 14_0_X.

**Comment by perrotta** [comment]
This PR is likely generating errors in the 14_0_X IBs for wfs 140.0, 145.0, 150.0 (see e.g. https://cmssdt.cern.ch/SDT/html/cmssdt-ib/#/relVal/CMSSW_14_0/2024-04-08-2300?selectedArchs=el8_amd64_gcc12&selectedFlavors=X&selectedStatus=failed):
```
----- Begin Fatal Exception 09-Apr-2024 02:21:47 CEST-----------------------
An exception of category 'ProductNotFound' occurred while
   [0] Processing  Event run: 1 lumi: 1 event: 1 stream: 0
   [1] Running path 'dqmoffline_step'
   [2] Prefetching for module ZGammaplusJetsMonitor/'Photon110Jet_monitoring'
   [3] Prefetching for module ChainedJetCorrectorProducer/'ak4PFPuppiL1FastL2L3Corrector'
   [4] Calling method for module L1FastjetCorrectorProducer/'ak4PFPuppiL1FastjetCorrector'
Exception Message:
Principal::getByToken: Found zero products matching all criteria
Looking for type: double
Looking for module label: fixedGridRhoFastjetAll
Looking for productInstanceName: 

   Additional Info:
      [a] If you wish to continue processing events after a ProductNotFound exception,
add "TryToContinue = cms.untracked.vstring('ProductNotFound')" to the "options" PSet in the configuration.

----- End Fatal Exception -------------------------------------------------
```

@esiam @cms-sw/dqm-l2 @cms-sw/pdmv-l2 please have a look

**Comment by mandrenguyen** [comment]
> > This PR is likely generating errors in the 14_0_X IBs for wfs 140.0, 145.0, 150.0
> 
> I guess all these are all "old" HI workflows that are not present in master (see e.g. this commit [01c75db](https://github.com/cms-sw/cmssw/commit/01c75db2cbdf096b31f28ea26956afa37ef5baf2)). @mandrenguyen would you agree in backporting that to 14_0_X?

Yes.  Just to confirm, you would like to me to make a PR removing the offending relval workflows from CMSSW_14_0_X, right?

**Comment by mmusich** [comment]
> Just to confirm, you would like to me to make a PR removing the offending relval workflows from CMSSW_14_0_X, right?

perhaps it's more straightforward, if you agree and have time to do it. Thanks!

**Comment by mandrenguyen** [comment]
> > Just to confirm, you would like to me to make a PR removing the offending relval workflows from CMSSW_14_0_X, right?
> 
> perhaps it's more straightforward, if you agree and have time to do it. Thanks!

Sure, I can do it this afternoon.

**Pull request merged**
