### PR TITLE
Added consumes to modules in DetectorDescription/DDCMS

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

Make use of the ESGetToken obtained.

#### PR validation:

Ran unit tests using the modules and they worked.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
Please review this pull request. It is needed for waiting framework changes.

**Comment by cvuosalo** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
