### PR TITLE
 implement Eras for HLT (90x) (alternative approach)

### PR DESCRIPTION
**Pull request by fwyzard**
These commits adapt the customisations for the Phase I pixel geometry and particle flow tracking to the `phase`Pixel` era.

The modifications are grouped in two functions, and the check for which Era is being applied is done only at the top level.

### CODE REVIEW

**Comment by fwyzard** [comment]
for an alternative approach, see #17041

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
@Martin-Grunewald @silviodonato @makortel do you have further suggestions after the last round of changes ?

**Comment by fwyzard** [comment]
please let me know if you prefer to have cedc62a or not

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
Note that I left in the `if "hlt" in producer.label(): ...` check, in case we still want to use the customisation function without using Eras:
```python
# modify the HLT configuration for the Phase I pixel geometry
def customizeHLTPhaseIPixelGeom(process):

    for esproducer in esproducers_by_type(process,"ClusterShapeHitFilterESProducer"):
         esproducer.PixelShapeFile = 'RecoPixelVertexing/PixelLowPtUtilities/data/pixelShape_Phase1TkNewFPix.par'
    for producer in producers_by_type(process,"SiPixelRawToDigi"):
        if "hlt" in producer.label():
            producer.UsePhase1 = cms.bool( True )
    return process
```

**Comment by silviodonato** [comment]
Thanks Andrea! I prefer to have cedc62a.
About the other possible changes to be added, @mtosi @JanFSchulte should we should add customizeHLTforHighPU in customizeHLTTrackingForPhaseI2017 ?

**Comment by fwyzard** [comment]
On 19 December 2016 at 17:51, Silvio Donato <notifications@github.com>
wrote:

> About the other possible changes to be added, @mtosi
> <https://github.com/mtosi> @JanFSchulte <https://github.com/JanFSchulte>
> should we should add customizeHLTforHighPU in customizeHLTTrackingForPhaseI2017
> ?
>
No - or at least, not yet.

I'd rather have a more complete review the tracking parameters in January.

As far as I know the relvals are still using pileup 35, so we do not need
those changes for the moment.

.A




-- 
Strategy is a system of expedients.

Generalfeldmarschall Helmuth Karl Bernhard Graf von Moltke

**Comment by Martin-Grunewald** [comment]
@fwyzard 
Yes, with  ```cedc62a```

**Comment by makortel** [comment]
@fwyzard Looks good to me.

**Comment by fwyzard** [comment]
@Martin-Grunewald @silviodonato can you '+1' this and #16977 if they pass your usual tests ?

**Comment by silviodonato** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
