### PR TITLE
Phase2-gex106 Remove BSC from Phase2 scenario and will be used in any new scenarios from now on

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Remove BSC from Phase2 scenario and will be used in any new scenarios from now on. It is now used in the new scenarios 2026D89 and 2026D90

#### PR validation:

Use the runTheMatrix test workflows 39834.0 and 40234.0

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

this counter does not exist anymore.

**Comment by bsunanda** [comment]
@srimanob Please sign this

**Comment by srimanob** [comment]
+Upgrade

This PR introduces F8 and is used in D89, D90. Since we don't use D89, D90 yet, except for the tracker study in the private sample. Updating the sub-detector combination should be OK.

**Comment by perrotta** [comment]
+1
- Modified scenarios accepted by the stakeholders

**Pull request merged**
