### PR TITLE
Removed unnecessary lambda capture in IO rules in DataFormats/TrackReco

### PR DESCRIPTION
**Pull request by Dr15Jones**
This fixes a clang warning.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by perrotta** [comment]
@Dr15Jones maybe I am missing the point... Why "unused" (see e.g. L44)?

**Comment by Dr15Jones** [comment]
@perrotta 'unused' was a poorly chosen word on my count. I should have said 'unnecessary'. Looking at the documentation about lambdas on cppreference.com:
https://en.cppreference.com/w/cpp/language/lambda

It states:
A lambda expression can read the value of a variable without capturing it if the variable
* has const non-volatile integral or enumeration type and has been initialized with a constant expression, or
* is constexpr and trivially copy constructible.

`HitSize` is a `const int` so falls under the category of a value that does not need to be explicitly captured.

**Comment by perrotta** [comment]
Thank you @Dr15Jones!
Indeed I missed the const'ness of the variable (and I'm learning something more about lambda functions) :-)

**Comment by perrotta** [comment]
+1
- Technical
- Jenkins tests pass

**Comment by Dr15Jones** [comment]
@perrotta the 'const do not need capture' was also something new I learned today as well. Your original question also taught me something new!

**Comment by fabiocos** [comment]
+1

**Pull request merged**
