### PR TITLE
Cmssw 8 0 x tau pog mini aod backport tau

### PR DESCRIPTION
**Pull request by alebihan**
Fix for phit at ecal entrance variable, compatible with Summer 16 training.

### CODE REVIEW

**Comment by slava77** [comment]
@alebihan 
some better title is needed (use the "Edit" button)
It's not fully clear to me that this is submitted to the correct repository already
@roger-wolf please confirm

**Comment by alebihan** [comment]
Hi, 
sorry, did a mistake with my PR wanted to submit it to the tau-pog repositery. Please discard it.

**Comment by roger-wolf** [comment]
Hi Slava, 

it is likely that happend not on purpose. A-C did you want to commit to tau-pog or to official-cmssw directly?

Cheers,
Roger

**Comment by alebihan** [comment]
Yes I'm sorry, I wanted to commit to the tau-pog repository, please 
discard this PR.

Thanks,

AC

**Comment by roger-wolf** [comment]
Hi A-C,

please PR to the CMSSW_8_0_X_tau-pog_miniAOD-backport-tauID then the 
branch CMSSW_8_0_X_tau-pog_miniAOD-backport is part of the PR to 
official-cmssw and should not recieve any commits any more unless Slava 
or Carl request them.

Cheers,
Roger

**Pull request closed without merging**
