### PR TITLE
Ecal pedestal PCL bug fix 

### PR DESCRIPTION
**Pull request by argiro**
Backport of  #23156

### CODE REVIEW

**Comment by lpernie** [comment]
please test

**Comment by arunhep** [comment]
+1

**Comment by fabiocos** [comment]
@argiro I understand that this fix has been tested to produce the db content where it was missing with no drawback, am I correct?

**Comment by argiro** [comment]
CorrectOn May 7, 2018 5:11 PM, Fabio Cossutti <notifications@github.com> wrote:@argiro I understand that this fix has been tested to produce the db content where it was missing with no drawback, am I correct?

**Pull request merged**
