### PR TITLE
updated HBHENegativeFlag class to access a1 and a2 functions directly

### PR DESCRIPTION
**Pull request by igv4321**
Made correction functions a1, a2, etc. accessible outside of OOTPileupCorrData.

Updated HBHENegativeFlag class so that it can be used together with current implementations of HCAL Method 1/Method 2.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
Possible HCAL issue?

For #7345 afa8dbee8f89dcae4ab224bfe7f8365348a80595
Extended tests performed against baseline CMSSW_7_4_X_2015-01-24-1400. About 300 DQM plots show minor differences, but two show visually large differences.

From WF 1313 (QCD):
eprofile

eprofile2

 @igv4321 or HCAL experts: Are these large differences a problem? Or are they to be expected for this PR?

Otherwise, the PR seems acceptable. Code changes are satisfactory. Compilation, unit tests, matrix tests, static checks are all OK. Extended tests are fine except for the issues mentioned above.

**Comment by slava77** [comment]
It looks like there are no calo-towers with energy above 300 GeV.
Is it special for these plots?

On 1/25/15 9:30 PM, cvuosalo wrote:
> Possible HCAL issue?
> 
> For #7345 <https://github.com/cms-sw/cmssw/pull/7345> afa8dbe
> <https://github.com/cms-sw/cmssw/commit/afa8dbee8f89dcae4ab224bfe7f8365348a80595>
> Extended tests performed against baseline CMSSW_7_4_X_2015-01-24-1400.
> About 300 DQM plots show minor differences, but two show visually large
> differences.
> 
> From WF 1313 (QCD):
> eprofile
> <https://cloud.githubusercontent.com/assets/5736159/5895047/2d0b509a-a4d9-11e4-94bb-56a18b1b5691.png>
> 
> eprofile2
> <https://cloud.githubusercontent.com/assets/5736159/5895048/36250e0a-a4d9-11e4-92e4-75ec19005d6c.png>
> 
> @igv4321 <https://github.com/igv4321> or HCAL experts: Are these large
> differences a problem? Or are they to be expected for this PR?
> 
> Otherwise, the PR seems acceptable. Code changes are satisfactory.
> Compilation, unit tests, matrix tests, static checks are all OK.
> Extended tests are fine except for the issues mentioned above.
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cms-sw/cmssw/pull/7345#issuecomment-71410903>.
> 

-- 
***********************************************************************
 Vyacheslav (Slava) Krutelyov
 TAMU: Physics Dept Texas A&M MS4242, College Station, TX 77843-4242
 CERN: 42-R-027
 AIM/Skype: siava16              googleTalk: slava77@gmail.com
 (630) 291-5128  Cell (US)       +41 76 275 7116 Cell (CERN)

-----------------------------------------------------------------------

**Comment by igv4321** [comment]
Sorry, I am missing something. How do I conclude that these plots exhibit large differences? It seems like the plotting script is using different glyphs (small horizontal lines for the first plot, filled squares for the second) in order to show some kind of a location (mean? median?). But those locations seem to be pretty consistent.

And yes, minor changes in the output are expected for this PR

**Comment by slava77** [comment]
The plots are profiles of calo tower time vs tower energy.
There are essentially no entries with calo-towers E above a few hundred GeV.
Carl, please post the scatter plots

**Comment by cvuosalo** [comment]
Here are the corresponding scatter plots for the two calo towers plots I previously posted, as requested by @slava77.

qcdhighhbscatter

qcdhighhbscatter2

It sounds like these small changes are to be expected for this PR.

**Comment by igv4321** [comment]
OK, now I see. Disappearance of large energy entries is not a small change. How do I figure out the commands which are run in WF 1313?

**Comment by slava77** [comment]
runTheMatrix.py -l 1313.0 -j 0
will make configs for you.
There's nothing special here in reco or in DQM. This is 3-3.5TeV dijet
sample

On 1/25/15 10:34 PM, igv4321 wrote:
> OK, now I see. Disappearance of large energy entries is not a small
> change. How do I figure out the commands which are run in WF 1313?
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cms-sw/cmssw/pull/7345#issuecomment-71413894>.
> 

-- 
***********************************************************************
 Vyacheslav (Slava) Krutelyov
 TAMU: Physics Dept Texas A&M MS4242, College Station, TX 77843-4242
 CERN: 42-R-027
 AIM/Skype: siava16              googleTalk: slava77@gmail.com
 (630) 291-5128  Cell (US)       +41 76 275 7116 Cell (CERN)

-----------------------------------------------------------------------

**Comment by igv4321** [comment]
Superseded by PR# 7508

**Pull request closed without merging**
