### PR TITLE
JME bugfixes port of #23499 

### PR DESCRIPTION
**Pull request by rappoccio**
Several JME bugs fixed here:

- AK8 jets needed rawFactor to reapply jet corrections
- AK4 jets needed muon fraction, addressing [this issue](https://github.com/cms-nanoAOD/cmssw/issues/169)
- Trigger objects needed AK8 jets, addressing [this issue](https://github.com/cms-nanoAOD/cmssw/issues/81)

9.4.x version is #23499 
10.1.x version is #23501

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by fabiocos** [comment]
@arizzi @gpetruc this is affecting NanoAOD, please have a look

**Comment by fabiocos** [comment]
@arizzi @gpetruc ping

**Comment by fabiocos** [comment]
@arizzi @gpetruc could you please check also this proposed update and sign it or comment?

**Comment by gpetruc** [comment]
will check now, but it would have been much easier if the PR had been done the proper way, i.e. first to cms-nanoAOD starting from the cms-nanoAOD master branch so that we can run the integration check

**Comment by davidlange6** [comment]
Your PR is unmergeable. Please have a look and possibly rebase it.

**Pull request closed without merging**
