### PR TITLE
Added updateJetCollection() function to jetTools.py and related changes to the PATJetUpdater and the pat::Jet class (74X)

### PR DESCRIPTION
**Pull request by ferencek**
Partial backport of #12863 (updates to the PATJetSlimmer excluded since they would affect the MiniAOD event content by changing the internal content of slimmed jets) + additional fix for the problem with jet correction factors in PATJetUpdater reported in https://hypernews.cern.ch/HyperNews/CMS/get/jes/574.html

**Update (Jan. 14, 2016):** Added backport of #12953

**Update (Jan. 19, 2016):** Added backport of #12988

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by ferencek** [comment]
Not sure I understand the error. I see a segmentation violation in a log file but I cannot reproduce the problem locally with this PR applied on top CMSSW_7_4_16. Also, the job does not seem to use any PAT objects or code modified by this PR.

**Comment by slava77** [comment]
@cmsbuild please test
maybe the issue in 135.4 was transient

**Comment by slava77** [comment]
@ferencek 
just to clarify,
similar to #11503, this PR by itself will also change miniAOD content (here the PATSlimmer is modified).
Please confirm.

My interpretation of the policy is that code affecting standard (centrally running) workflows can not be modified in a production release until an new processing version/target is defined.
An alternative straightforward in the release support perspective is to make the new feature (code changing the results) configurable and disabled by default, you can also provide a customization function to enable it if needed (maybe even central one "latestReMiniAOD" where all new features are incrementally added).
A less straightforward alternative is recipes on the twikis or such (relatively easy), or build up the case in the community for a new version or, otherwise, hope for some other reasons to appear beyond your needs.

**Comment by ferencek** [comment]
Hi Slava,

Correct, just like #11503, this PR changes the internal content of either
individual objects or their collections (in this case internal content of
slimmed  PAT jets). No changes to the event content definition are made.

I think for now probably the easiest solution for #11503 is to live with
private recipes and in the meantime people will migrate to 76X. For this
PR, though, I will remove the last commit that changes the PATJetSlimmer so
that the PR can be merged.

Best,
Dinko

(Sent from my phone. Please excuse the brevity, spelling, and punctuation.)

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by ferencek** [comment]
No longer relevant after 76X re-reco. Closing

**Pull request closed without merging**
