### PR TITLE
Removing obsolete code from CaloLayer1Setup

### PR DESCRIPTION
**Pull request by BenjaminRS**
#### PR description:

This PR removes obsolete code from the CaloLayer1 area which has been causing spurious elog warnings as described in [Issue#34309](https://github.com/cms-sw/cmssw/issues/34309). As suggested in this [comment to PR#35873](https://github.com/cms-sw/cmssw/pull/35873#issuecomment-954750836) I have removed the if else statement which was now obsolete.

### CODE REVIEW

**Comment by perrotta** [comment]
urgent

**Comment by perrotta** [comment]
please test with #35941,#35921

**Comment by rekovic** [comment]
+1

**Comment by qliphy** [comment]
@BenjaminRS  Should this be backported to 12_0_X to replace #35877?

**Comment by BenjaminRS** [comment]
Hi @qliphy - this can be backported to replace the [previous PR](https://github.com/cms-sw/cmssw/pull/35877) if you wish; however @perrotta [mentioned in this comment](https://github.com/cms-sw/cmssw/pull/35873#issuecomment-957325303) that the backport with the other solution can remain. Which is preferred course of action?

**Comment by qliphy** [comment]
> Hi @qliphy - this can be backported to replace the [previous PR](https://github.com/cms-sw/cmssw/pull/35877) if you wish; however @perrotta [mentioned in this comment](https://github.com/cms-sw/cmssw/pull/35873#issuecomment-957325303) that the backport with the other solution can remain. Which is the preferred course of action?

@BenjaminRS   Fine with me with the proposal from @perrotta as for 12_0_X

**Comment by tvami** [comment]
@BenjaminRS can I also ask you to include "CaloLayer1Setup" in the PR title? It's best to have the PR titles as descriptive as possible.

**Comment by BenjaminRS** [comment]
Hi @tvami -- sorry for that, I didn't realise it was so easy to change :)

**Comment by perrotta** [comment]
+1
- Thank you @BenjaminRS: let merge this one in the master, for now
- Then for the backport we can stick with the "simple solution" already submitted

**Pull request merged**
