### PR TITLE
Add PDF weight helper tool (76x)

### PR DESCRIPTION
**Pull request by bendavid**
This is a backport of
https://github.com/cms-sw/cmssw/pull/12787

This is a pure analysis-level tool for the moment, but having it in the release would simplify recipes for users, so we want it in 74x and 76x.

### CODE REVIEW

**Comment by bendavid** [comment]
Updated with last minor change (move to non-legacy EDAnalyzer class) from #13019

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by bendavid** [comment]
Any news on this and corresponding 74x pull request?
(Would be nice to avoid analysis recipes with merge-topic, at least for 76x)

**Comment by covarell** [comment]
+1

**Comment by bendavid** [comment]
Any possibility of eventually getting this into 76x and/or 74x for analysis use?

**Comment by monttj** [comment]
+1

**Comment by bendavid** [comment]
Is this a contender for longest open pull request?

**Pull request closed without merging**
