### PR TITLE
[CPP20][L1,UPGRADE] Replace some enums with constexpr ints

### PR DESCRIPTION
**Pull request by iarspider**
#### PR description:

Replace some enums with constexpr ints to avoid deprecated enum arithmetics. Replaces https://github.com/cms-sw/cmssw/pull/44489 following @makortel's suggestion.

#### PR validation:

Bot tests

### CODE REVIEW

**Comment by iarspider** [comment]
please test for CMSSW_14_1_CPP20_X

**Comment by iarspider** [comment]
please test for CMSSW_14_1_CPP20_X

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
please test for CMSSW_14_1_CPP20_X

**Comment by iarspider** [comment]
please test for CMSSW_14_1_CPP20_X

**Comment by aloeliger** [comment]
+l1
- Technical tweaks

**Comment by srimanob** [comment]
+Upgrade

**Comment by civanch** [comment]
+1

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
