### PR TITLE
revert SignalPropagationSpeed at GEMDigiProducer

### PR DESCRIPTION
**Pull request by yeckang**
#### PR description:

This PR is minor revert of the PR #27445.
For consistency with the comment line, the value of signalPropagationSpeed at GEMDigiProducer has reverted to the old version. And `cspeed` is converted to mm/ns to cm/ns for it. @kpedro88

### CODE REVIEW

**Comment by kpedro88** [comment]
Does this change also need to be propagated to https://github.com/cms-sw/cmssw/blob/caf88b0ed55bbf3910ff210aba3b4a884083c41d/SimMuon/GEMDigitizer/src/GEMSignalModel.cc#L101 ?

If so, maybe the conversion should be applied where `cspeed` is defined, so the value is always in mm/ns: https://github.com/cms-sw/cmssw/blob/caf88b0ed55bbf3910ff210aba3b4a884083c41d/SimMuon/GEMDigitizer/src/GEMSignalModel.cc#L26

**Comment by yeckang** [comment]
Ah, okay. Then I will change the initialization of `cspeed` as cm/ns.

**Comment by kpedro88** [comment]
please test

**Comment by kpedro88** [comment]
+upgrade

**Comment by civanch** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Pull request merged**
