### PR TITLE
Pixel Barycenters histograms in Tracker DQM [11_3_X]

### PR DESCRIPTION
**Pull request by mmusich**
backport of #34312 

#### PR description:

We added a total of nine histograms showing the coordinates of the barycenter derived by different parts of the Pixel detector. The histograms show the barycenter derived from BPIX, BPIX(x-), BPIX(x+), FPIX(z-), FPIX(z+), FPIX(z-,x-), FPIX(z-,x+), FPIX(z+,x-), FPIX(z+,x+).

#### PR validation:

The changes have been tested by running `runTheMatrix.py -l 10024` and `runTheMatrix.py -l 136.89`, which run without any failed steps and produces the desired additional histograms.
Below you can see a screenshot of one of the histograms produced.

image

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

This is a backport of https://github.com/cms-sw/cmssw/pull/34312 (originally from @dmeuser).
cc:
@sroychow @arossi83

### CODE REVIEW

**Comment by mmusich** [comment]
urgent 

this will be needed for CRUZET

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by jfernan2** [comment]
+1
9MEs added, no changes expected at Online DQM

**Comment by qliphy** [comment]
+1

**Pull request merged**
