### PR TITLE
Update Hydjet2 and Hydjet1

### PR DESCRIPTION
**Pull request by wouf**
Bug fixes and minor updates of Hydjet2

### CODE REVIEW

**Comment by covarell** [comment]
What is the plan to move Hydjet2 to cmsdist rather than CMSSW, as discussed at the GEN meeting?

**Comment by covarell** [comment]
Hi Andrey (please continue conversation here, not in private emails),

I know Hydjet is not included in external generators. My question was exactly if there is a plan to move it there.

**Comment by wouf** [comment]
I do not understand the reason for this. Also how it's possible? Hydjet 2 it is the interface of HYDJET++ and from the code point of view it's the different programs. Could You please point me to the meeting where it was discussed? What was the motivation of this?

**Comment by wouf** [comment]
Can anybody answer that?

**Comment by covarell** [comment]
This was discussed in the GEN meeting with Kurt Jung
https://indico.cern.ch/event/407404/

The normal way MC generators are used in CMS is not to copy the generator code in CMSSW, as it seems the case for Hydjet and other generators used in HI. 

Generators are kept in an external repository with their own versioning, independent of CMSSW, and then we maintain in CMSSW just an interface which calls the generator in order to produce the result in CMS-compliant formats. This ensures that generator developments and CMSSW developments go in parallel, because generator authors are not in general CMS people.

Why for HI this is different?

**Comment by wouf** [comment]
For Hydjets and Pyquen the story is different. Hydjet 1: main authors is in CMS HI group. Hydjet 1 at this moment used only in CMS. The same story for Pyquen. Hydjet 2: it is the next generation of Hydjet 1, based on HYDJET++, but with different development strategy (for example at this moment we discuss the possibility of migration of Hydjet 2  (but not HYDJET++) to the Pythia 8). Hydjet 2 is made specially for CMS HI.

**Comment by mkirsano** [comment]
hydjet 1.8 and hydjet++ 2.1 are in GENSER. They are downloaded there from the author's web site. So, technically it is possible to make hydjet++ an external package of cmssw (i.e. add it to cmsdist).
On the other hand, if this package is not used and developed outside CMS. there is a git repository
https://github.com/cms-externals. It is possible to keep and develop hydjet++ there. cmsdist can take the code from there using git commands.

**Comment by wouf** [comment]
This PR was made for Hydjet2_2_0_patch1 and  Hydjet1_9_patch1. Hydjet++ is used outside the CMS, but Hydjet 2, which is already included to CMSSW (such as Hydjet1.9) is not the same as HYDJET++.

**Comment by wouf** [comment]
Anyway this PR is just bug fixes for Hydjet 1.9 and Hydjet 2.2.0. So we need it before the next HI MC production.

**Comment by covarell** [comment]
+1

**Comment by davidlange6** [comment]
@cmsbuild, please test

**Comment by davidlange6** [comment]
@wouf - thisPR no longer merges. Could you rebase it?

**Comment by davidlange6** [comment]
@wouf - ping?

**Comment by wouf** [comment]
What You mean?

**Comment by wouf** [comment]
What's happened?

**Comment by davidlange6** [comment]
@wouf- I presume someone else changed a file that you have requested a change for.

**Comment by wouf** [comment]
So, what I have to do?

**Comment by davidlt** [comment]
@wouf rebase (`git rebase -i official-cmssw/CMSSW_7_6_X`) it and rebase will fail and will ask you to resolve the conflict.

**Comment by wouf** [comment]
It's not failed, it gives:

"git rebase -i official-cmssw/CMSSW_7_6_X "
                Successfully rebased and updated refs/heads/CMSSW_7_6_X.

**Comment by covarell** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
