### PR TITLE
MTD simulation: add support for pre-mixing in pileup management of MtdSimLayerCluster 

### PR DESCRIPTION
**Pull request by fabiocos**
#### PR description:

The ```MtdSimLayerCluster``` collection, used to encode MTD ```PSimHit``` clusters and associate them to both ```TrackingParticle``` collection and MTD reconstructed hits, was tested to properly handle pile-up in the classic ```MixingModule``` case, but was not adapted for pre-mixing.

This PR adds support for the pre-mixing case, and adds a simple analyzer to directly inspect the content of the ```MtdSimLayerCluster``` collection.

This addition can possibly serve as a basis for further extension to other MTD-truth collections.

#### PR validation:

Code compiles, run, and has been tested with the dumper code to combine signal and pile-up in test wf 25034.999.

### CODE REVIEW

**Comment by fabiocos** [comment]
please test

the last fix used in tests was not properly committed

**Comment by srimanob** [comment]
Hi @fabiocos 

Thanks for this. Should this PR be tested with Phase-2 premixing workflow?

**Comment by fabiocos** [comment]
@srimanob we have 25034.999 , that shows the bulk of differences of differences, right?

**Comment by civanch** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

Difference shows up only in Phase-2 premix workflow, 25034.999, as expected.

**Comment by rappoccio** [comment]
+1

**Pull request merged**
