### PR TITLE
L1T phase-2: Add the Phase2 L1T VertexFinder (corrected version)

### PR DESCRIPTION
**Pull request by cecilecaillol**
#### PR description:

Same as https://github.com/cms-sw/cmssw/pull/33609 but new PR because had to update to newer CMSSW and pulled more recent unrelated PRs.

This pull request includes:

An EDProducer that implements the primary-vertex-finding algorithms investigated for the L1T Interim TDR.
The EDAnalyser that was used to study the performance of these algorithms.
The Ntupler for analysis of vertexing algorithms.

The code for all of these is fully contained within L1Trigger/VertexFinder, and the l1tVertexFinder namespace; however of course in principle the name of this directory & namespace could be changed to conform to standard conventions.

A few more details on the EDProducer ...

Source code: interface/VertexProducer.h & plugins/VertexProducer.cc
It creates a l1t::VertexCollection, which is based on the L1T vertex data format class
l1vertices - vector of all vertices found by the algo defined in the Python config (default config uses "DBSCAN" algo)
Python config fragment (to be used by default for downstream algos): python/VertexProducer_cff.py
Parameter values are set to run DBSCAN vertex-finding algo
Other vertexing-finding algorithms can be run by changing the value of the Algorithm parameter in the VertexReconstruction parameter set.

Apart from that EDProducer, the other files in this pull request are:

Header + .cc files for AlgoSettings, L1Track, RecoVertex and `VertexFinder classes that are used by the vertex producer itself
interface/selection.h & src/selection.cc : Contains implementation of getPrimaryVertex function, that currently identifies highest-sum-pT vertex in vector of vertex objects.
plugins/VertexAnalyzer.cc : Implements the EDAnalyzer that we use to study the performance of vertex-finding algorithms
Header + .cc files for classes used by the EDAnalyzer: L1TrackTruthMatched, RecoVertexWithTP, Stub & TP

#### PR validation:

Same as https://github.com/cms-sw/cmssw/pull/33609#

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Same as https://github.com/cms-sw/cmssw/pull/33609#

### CODE REVIEW

**Comment by cecilecaillol** [comment]
please test

**Comment by cecilecaillol** [comment]
+l1

**Comment by cecilecaillol** [comment]
This is the same as https://github.com/cms-sw/cmssw/pull/33609 including the fix to address Silvio's comment. Could you please sign?

**Comment by silviodonato** [comment]
@cecilecaillol I see that https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-3ad3d2/15143/summary.html still complains of Duplicated Dictionaries https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-3ad3d2/15143/dupDict/lostDefs.txt
I'm not sure, but you can try to add a ClassVersioning as it was done in https://github.com/cms-sw/cmssw/pull/33446/files. Let's see if this fix the warning.

**Comment by cecilecaillol** [comment]
> @cecilecaillol I see that https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-3ad3d2/15143/summary.html still complains of Duplicated Dictionaries https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-3ad3d2/15143/dupDict/lostDefs.txt
> I'm not sure, but you can try to add a ClassVersioning as it was done in https://github.com/cms-sw/cmssw/pull/33446/files. Let's see if this fix the warning.

@silviodonato Thanks for the suggestion! Can you please explain how to do this (eg how to find the checksum value)?

**Comment by silviodonato** [comment]
> > @cecilecaillol I see that https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-3ad3d2/15143/summary.html still complains of Duplicated Dictionaries https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-3ad3d2/15143/dupDict/lostDefs.txt
> > I'm not sure, but you can try to add a ClassVersioning as it was done in https://github.com/cms-sw/cmssw/pull/33446/files. Let's see if this fix the warning.
> 
> @silviodonato Thanks for the suggestion! Can you please explain how to do this (eg how to find the checksum value)?

```
  <class name="l1t::Vertex" ClassVersion="10">
    <version ClassVersion="10" checksum="514139083"/>
  </class>
```

**Comment by silviodonato** [comment]
@cms-sw/core-l2 could you help us with the duplicate dictionary warning (https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-3ad3d2/15143/dupDict/lostDefs.txt)? Do we need to change something in https://github.com/cms-sw/cmssw/blob/master/Utilities/ReleaseScripts/scripts/duplicateReflexLibrarySearch.py ?

**Comment by Dr15Jones** [comment]
So I don't see why it is complaining about duplicate dicationaries. @smuzaffar any ideas?

As for versioning
You should add the class version, however, please start at 3, not 10.

```
  <class name="l1t::Vertex" ClassVersion="3">
    <version ClassVersion="3" checksum="514139083"/>
  </class>
```

**Comment by cecilecaillol** [comment]
please test

**Comment by makortel** [comment]
> So I don't see why it is complaining about duplicate dicationaries. @smuzaffar any ideas?

I think this specific report comes from this script https://github.com/cms-sw/cmssw/blob/master/Utilities/ReleaseScripts/scripts/duplicateReflexLibrarySearch.py, and suspect that the `equivDict` (or something) would need an update. (I did not spend enough time to fully understand the behavior of the script though)

**Comment by cecilecaillol** [comment]
The same warning about duplicated dictionairies is still there after the inclusion of class versioning. Do we really need to fix it before merging the PR? If so, can you please suggest other solutions?

**Comment by silviodonato** [comment]
@cms-sw/simulation-l2 do you have further comments?

**Comment by cecilecaillol** [comment]
+l1

**Comment by civanch** [comment]
+1

**Comment by silviodonato** [comment]
@cms-sw/core-l2 can we modify  https://github.com/cms-sw/cmssw/blob/master/Utilities/ReleaseScripts/scripts/duplicateReflexLibrarySearch.py later?

**Comment by makortel** [comment]
> @cms-sw/core-l2 can we modify https://github.com/cms-sw/cmssw/blob/master/Utilities/ReleaseScripts/scripts/duplicateReflexLibrarySearch.py later?

I'd be ~ok to proceed given that @smuzaffar is away.

**Pull request merged**
