### PR TITLE
DD4hep: Ecal Geometry Description

### PR DESCRIPTION
**Pull request by ianna**
#### PR description:

* Ecal geometry configuration and its test script

This PR is based on https://github.com/cms-sw/cmssw/pull/26371

#### PR validation:

```
cmsRun Geometry/EcalAlgo/test/python/testEcalGeometry.py
```
The error is due to a missing implementation of a **ecal:DDEcalBarrelNewAlgo** algorithm and should be ignored for now:
```
DD4CMS                 +++ Start executing algorithm DDCMS_ecal_DDEcalBarrelNewAlgo....
DD4CMS           ERROR ++ FAILED  NOT ADDING SUBDETECTOR 00000000 = ecal:DDEcalBarrelNewAlgo
```

#### if this PR is a backport please specify the original PR:

no back port is needed

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by kpedro88** [comment]
@ianna can you elaborate on the changes to MTD?

**Comment by ianna** [comment]
@kpedro88 - it's migration to dd4hep

**Comment by ianna** [comment]
@fabiocos and @smuzaffar - the same error here is unrelated to this PR:
```
GEN,SIM,DIGI,DIGI2RAW,RAW2DIGI,L1Reco,RECO,EI,ENDJOB
We have determined that this is simulation (if not, rerun cmsDriver.py with --data)
Step: GEN Spec: 
Loading generator fragment from Configuration.Generator.SingleElectronE120EHCAL_pythia8_cfi
Step: SIM Spec: 
Step: DIGI Spec: 
Step: DIGI2RAW Spec: 
Step: RAW2DIGI Spec: 
Step: L1Reco Spec: 
Step: RECO Spec: 
Step: EI Spec: 
Step: ENDJOB Spec: 
Traceback (most recent call last):
  File "/cvmfs/cms-ib.cern.ch/nweek-02570/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_6_X_2019-04-04-1100/bin/slc7_amd64_gcc700/cmsDriver.py", line 56, in <module>
    run()
  File "/cvmfs/cms-ib.cern.ch/nweek-02570/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_6_X_2019-04-04-1100/bin/slc7_amd64_gcc700/cmsDriver.py", line 28, in run
    configBuilder.prepare()
  File "/cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc700/cms/cmssw-patch/CMSSW_10_6_X_2019-04-04-2300/python/Configuration/Applications/ConfigBuilder.py", line 2251, in prepare
    self.pythonCfgCode += self.addCustomise()
  File "/cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc700/cms/cmssw-patch/CMSSW_10_6_X_2019-04-04-2300/python/Configuration/Applications/ConfigBuilder.py", line 860, in addCustomise
    raise Exception("cannot specify twice "+fcn+" as a customisation method") 
Exception: cannot specify twice customise as a customisation method
```

**Comment by ianna** [comment]
please test

**Comment by fabiocos** [comment]
please test

**Comment by smuzaffar** [comment]
please test
cms-bot PR https://github.com/cms-sw/cms-bot/pull/1115 should fix this

**Comment by ianna** [comment]
+1

**Comment by fabiocos** [comment]
@ianna this is effectively fully integrating #26371, am I correct?

**Comment by ianna** [comment]
> @ianna this is effectively fully integrating #26371, am I correct?

yes

**Comment by fabiocos** [comment]
@kpedro88 comments?

**Comment by kpedro88** [comment]
my signature is only required on this one and #26374 because they include #26371. If that one is integrated and then the others are rebased, I will not need to sign them.

**Comment by fabiocos** [comment]
@ianna now that #26371 has been merged, and that the further addition in #26374 is not impacting production workflow, I see this PR as useless

**Pull request merged**
