### PR TITLE
fix syntax warnings in matrix code

### PR DESCRIPTION
**Pull request by kpedro88**
#### PR description:

There were a few syntax warnings from the python3 checks (pointed out by @jpata in https://github.com/cms-sw/cmssw/pull/32128#issuecomment-740572127):
```
src/Configuration/PyReleaseValidation/python/MatrixUtil.py:120: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if len(self.run) is not 0 or self.ls:
src/Configuration/PyReleaseValidation/python/MatrixUtil.py:187: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if len(self.run) is not 0:
src/Configuration/PyReleaseValidation/python/relval_upgrade.py:42: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if (specialType is not 'baseline') and ( ('PU' in step and step.replace('PU','') in specialWF.PU) or (step in specialWF.steps) ):
```

These are now fixed.

#### PR validation:

runTheMatrix.py still works.

### CODE REVIEW

**Comment by kpedro88** [comment]
please test

**Comment by kpedro88** [comment]
+upgrade

**Comment by chayanit** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
