### PR TITLE
Implement a workaround for `-Warray-bounds` in LTO builds

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Implement a workaround for `-Warray-bounds` in LTO builds.

#### PR validation:

None.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

No backport foreseen.

### CODE REVIEW

**Comment by fwyzard** [comment]
please test with cms-sw/cmsdist#9301

**Comment by fwyzard** [comment]
please test with cms-sw/cmsdist#9301 for el9_amd64_gcc13

**Comment by smuzaffar** [comment]
please test with https://github.com/cms-sw/cmsdist/pull/9301

start normal (production arch) tests too

**Comment by smuzaffar** [comment]
@fwyzard , this will not work as `HeterogeneousCore/AlpakaInterface` does not generate alpaka backend. This change should go in to RecoTracker/PixelSeeding/plugins/BuildFile.xml

**Comment by fwyzard** [comment]
Mhm, I see.

So at the moment the behaviour is just like adding the flags by hand in `RecoTracker/PixelSeeding/plugins/BuildFile.xml` ?

**Comment by fwyzard** [comment]
please test with cms-sw/cmsdist#9301 for el9_amd64_gcc13

**Comment by smuzaffar** [comment]
> Mhm, I see.
> 
> So at the moment the behaviour is just like adding the flags by hand in `RecoTracker/PixelSeeding/plugins/BuildFile.xml` ?

yes exactly

**Comment by smuzaffar** [comment]
please test for CMSSW_14_1_CLANG_X

**Comment by smuzaffar** [comment]
@cms-sw/reconstruction-l2 , can you please review this? Change here is identical to https://github.com/cms-sw/cmssw/pull/45340 which you already have approved. This should fix the warnings for 14.1.X gcc 13 and build errors for CLANG IBs

**Comment by smuzaffar** [comment]
please ignore https://github.com/cms-sw/cmssw/pull/45455#issuecomment-2231016501 errors, these are due to broken CLANG IB

**Comment by mandrenguyen** [comment]
+reconstruction
Errors are to be ignored:  
https://github.com/cms-sw/cmssw/pull/45455#issuecomment-2231054287

**Comment by smuzaffar** [comment]
@cms-sw/orp-l2 , this fixes warnings for gcc12 and build errors for gcc13. Can you please review and approve this?

**Comment by rappoccio** [comment]
+1

**Comment by rappoccio** [comment]
merge

**Pull request merged**
