### PR TITLE
Twin mux theta plots

### PR DESCRIPTION
**Pull request by jfernan2**

### CODE REVIEW

**Comment by jfernan2** [comment]
Any update on this?
Thanks

**Comment by dmitrijus** [comment]
+1

**Comment by dmitrijus** [comment]
But you need a 81x port if you want this merged.

**Comment by dmitrijus** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by dmitrijus** [comment]
+1

**Comment by dmitrijus** [comment]
+1

**Comment by dmitrijus** [comment]
Can you put the new commit into 81x?

**Comment by jfernan2** [comment]
81X port is on PR 15122
https://github.com/cms-sw/cmssw/pull/15122

**Comment by vanbesien** [comment]
please test

**Comment by vanbesien** [comment]
@jfernan2  What is the status here?

**Comment by jfernan2** [comment]
@vanbesien We did this PR long time ago but, due to the urgency for these changes we pushed them through the DQMP5TagCollector twiki. So it is already online, but not in CMSSW if I understand correctly.
Thanks

**Comment by dmitrijus** [comment]
@jfernan2 You are correct. But in order to get into CMSSW, this PR requires an L1 signature.

**Comment by jfernan2** [comment]
Hi, 
This PR is rather old now, is there anything preventing this to be merged?
Thanks in advance

**Comment by vanbesien** [comment]
L1, can you please sign?

**Comment by jfernan2** [comment]
The 81X porting of this PR (#15122) has already been merged last week, is there anything preventing for L1 sign to this PR?
We urgently need this PR in order to have the DT offline DQM working properly.
Thank you very much in advance

**Comment by fcavallo** [comment]
I warmly support Javier's request: I see the DQM is running 8_0_20 and our (DT) trigger plots still don't get filled!

**Comment by jfernan2** [comment]
Please, any comment or objection to this PR?
Thanks

**Comment by dmitrijus** [comment]
Hi, no objections.
I wrote an email to L1 guys asking to sign it, hopefully this won't take much time.

**Comment by jfernan2** [comment]
Thank you!!

**Comment by rekovic** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
