### PR TITLE
Adding no-HF grid-based rho (76x forward-port #11773), and fixing existing bugged central rho values

### PR DESCRIPTION
**Pull request by rappoccio**
In the forward-port of #11773 now adding the fixed grid central version explicitly. 

Also, found a bug in the central "charged pileup" and "neutral hadron" rho values. They incorrectly overrode the "particleFlow" input source, so ALL of these were exactly the same. Now fixed.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
@cmsbuild please test
Hoping the previous Jenkins failure is transient

**Comment by cvuosalo** [comment]
+1

For #11855 0a575938b048e8165334999647fdf94b763c46ab

Adding an eta-restricted (no HF) grid-based rho for future use in Mini-AOD or RECO. There should be no other change in monitored quantities. #11771 and #11773 are the 74X and 75X versions of this PR, and they have already been approved by Reco.

The code changes are satisfactory. Jenkins tests failed to due errors in the IB unrelated to this PR. Local matrix tests against baseline CMSSW_7_6_0_pre6 show no significant differences, as expected. The addition of the new quantity is confirmed by the tests, but the product size increase is negligible.

**Comment by slava77** [comment]
hold
(or should it be "-1")
the keep statement is added only to RECO data tier.
It should be in AOD as well

**Comment by rappoccio** [comment]
@slava77 whoops, apologies. Done now.

**Comment by slava77** [comment]
Sal,
you have more to do now:
jenkins is not happy with your PR anymore: there is a merge conflict.
I suspect it's due to latest changes in 76X branch.
Please rebase to the latest IB version.

**Comment by rappoccio** [comment]
Yes, sorry, I meant to do this and forgot to do so. Jenkins should be happy now.

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by rappoccio** [comment]
Looks unrelated to this PR, no?

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by rappoccio** [comment]
I don't see the errors. Is this an xrootd problem or something?

**Comment by davidlt** [comment]
The process was terminated before it managed to print anything else, .e.g it was killed due to timeout.

**Comment by rappoccio** [comment]
Thanks David, I'll wait for a retest then.

**Comment by smuzaffar** [comment]
@cmsbuild, please test

**Comment by slava77** [comment]
NB: based on git grep, fixedGridRhoFastjetCentralChargedPileUp and fixedGridRhoFastjetCentralNeutral are not used in the code available in CMSSW.

**Comment by rappoccio** [comment]
Correct, this is not used except for analysis until now.

**Comment by cvuosalo** [comment]
+1

For #11855 22074baec1d7982bb2d0baadcecd1a1aa326f14c

Second approval after rebasing and minor addition. The change is satisfactory, and Jenkins tests against baseline CMSSW_7_6_X_2015-10-19-1100 show no significant differences, as expected.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
