### PR TITLE
adjust ranges and reduce binning

### PR DESCRIPTION
**Pull request by fioriNTU**
This PR optimize ranges and eventually reduce the binning of several plots. No change in the total number of plots.

### CODE REVIEW

**Comment by VinInn** [comment]
@cmsbuild please test

**Comment by fioriNTU** [comment]
Please wait before merging, I may revert the binning of on-track clusters, but I need some time to check

**Comment by fioriNTU** [comment]
Ok, after few checks this PR can be merged as it is, thanks!

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
