### PR TITLE
optimize: rely on Candidate pt,eta,phi without casting in MuonPFIsolationWithConeVeto

### PR DESCRIPTION
**Pull request by slava77**
visual optimization based on https://jiwoong.web.cern.ch/jiwoong/cgi-bin/igprof-navigator/igprofCPU_CMSSW_11_1_0_pre8PAT/28

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/30054	a4a7812
- jenkins tests show no differences as expected
- local test with 136.88811 shows about a factor of 2.7 speedup in muonPUPPINoLeptonsIsolation and muonPUPPIIsolation modules (still barely 0.1% improvement in this run2 workflow; the impact should be much larger in phase-2, around 5-7% speedup expected per job in PU200 miniAOD)

**Comment by silviodonato** [comment]
merge
cc: @santocch , technical change, no change in physics

**Comment by slava77** [comment]
just for completeness, since the optimization was focused on phase-2 workflow profiling: 
- on wf 23434.21 step4 (ttbar PU200 miniAOD) the speedup is 8% of the total job time

**Comment by santocch** [comment]
+1

**Pull request merged**
