### PR TITLE
[13_1_X] Fix LumiCache in AlcaBeamMonitor and OnlineBeamMonitor

### PR DESCRIPTION
**Pull request by francescobrivio**
#### PR description:
Backport of #41700

Fix concurrent lumi treatment of `AlcaBeamMonitor` and `OnlineBeamMonitor`, see master PR for more details.

#### PR validation:
See discussion in master PR

#### Backport:
Backport of #41700

### CODE REVIEW

**Comment by francescobrivio** [comment]
backport of #41700

**Comment by francescobrivio** [comment]
type bug-fix

**Comment by francescobrivio** [comment]
@cmsbuild please test

**Comment by tvami** [comment]
+db

**Comment by emanueleusai** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
