### PR TITLE
Phase2-hgx236 Remove the ERROR message from the algos

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Remove the ERROR message from the algos

#### PR validation:

Checked with the cfg files in Geometry/HGCalCommonData/test/python

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
What went wrong with the comparison tests?

**Comment by bsunanda** [comment]
@cvuosalo I believe this is because of transition to the new G4 version. The changes in the code only affects dd4hep applications and it stops printing an error message.

**Comment by cvuosalo** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade

**Comment by silviodonato** [comment]
+1

**Pull request merged**
