### PR TITLE
Important BUG FIX in parameter assignment of millepede-based tracker alignment

### PR DESCRIPTION
**Pull request by mschrode**
The bug corrupts the IOV-dependent alignment in releases compiled with
slc6_amd64_gcc472 and later. It is caused by using a dangling reference to
an edm::EventID object to determine the run number. At least with the gcc
versions in SLC6, this results in an incorrect determination of the current
IOV. Details are given in this presentation at the tracker-alignment meeting:

https://indico.cern.ch/event/342234/session/0/contribution/8/0/material/slides/0.pdf

The implementation is the outcome of a discussion of #6515 .

This PR supersedes #6516 .

### CODE REVIEW

**Comment by ktf** [comment]
@diguida, @mmusich ping. Is this still needed?

**Comment by diguida** [comment]
@ktf It is a backport of a bug-fix entering most recent release cycles, and IFAIK it has been used in this cycle for some alignment workflows, so I'd like it in. @mmusich to confirm.

**Comment by diguida** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
