### PR TITLE
[Backport of] HCAL: Bugfix of PFA1' Trigger Primitive algo by switching to integer based math

### PR DESCRIPTION
**Pull request by Michael-Krohn**
#### PR description:

Switching from double variable based math to integer variable based math in the TP energy algorithm. This is to match what is in the firmware on detector. Also, the logic blocks to perform the energy calculation for PFA1' and PFA2 have been separated. Again to match what is in the firmware on detector.

#### PR validation:

A basic technical test was performed: runTheMatrix.py -l limited -i all --ibeos

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

This PR is a backport of PR https://github.com/cms-sw/cmssw/pull/38753 to 124X, in order to make s/w match f/w.

### CODE REVIEW

**Comment by mariadalfonso** [comment]
please test

**Comment by mariadalfonso** [comment]
type bug-fix

**Comment by mariadalfonso** [comment]
ideally we want this for the Run3-MC
as this brings the software into agreement with the firmware for Run3

**Comment by cecilecaillol** [comment]
+l1

**Comment by cecilecaillol** [comment]
+l1

**Comment by perrotta** [comment]
backport of https://github.com/cms-sw/cmssw/pull/38753

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
@cms-sw/l1-l2 do you see any issue with this backport? Master version of this PR was merged since CMSSW_12_5_X_2022-07-22-2300

**Comment by cecilecaillol** [comment]
+l1

**Comment by perrotta** [comment]
+1

**Pull request merged**
