### PR TITLE
Fix for `L1TMuonGlobalParams_PayloadInspector`

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

As pointed out in https://github.com/cms-sw/cmssw/pull/45438#issuecomment-2293834884, the code implemented with https://github.com/cms-sw/cmssw/pull/45438 had some error that need to be fixed.

#### PR validation:

Relies on the augmented unit tests at `CondCore/L1TPlugins/test/testL1TObjectsPayloadInspector.cpp`

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

N/A

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
+1
- Unit test ends successfully
- Differences in wf 29634.911 are unrelated, see https://github.com/cms-sw/cmssw/issues/45505

**Comment by mmusich** [comment]
@cms-sw/l1-l2 please sign.

**Comment by aloeliger** [comment]
+l1
- @mmusich, apologies, just got back from vacation this morning.

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
