### PR TITLE
NanoAOD step added in upgrade 2017 samples

### PR DESCRIPTION
**Pull request by ahmad3213**
PR description:
NanoAOD step is added for upgrade 2017 samples (for both noPU and PU). The aim  nanoAOD production for all upgrade 2017 samples. 
Local test is done with a noPU and a PU sample as follows respectively 
runTheMatrix.py --what upgrade -l 10071.0 
runTheMatrix.py --what upgrade -l 10225.0

### CODE REVIEW

**Comment by zhenhu** [comment]
please test workflow 10071.0,10225.0

**Comment by zhenhu** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade

**Comment by kpedro88** [comment]
+1

**Pull request merged**
