### PR TITLE
Multi-threading support added for Heavy Ions HLT modules

### PR DESCRIPTION
**Pull request by kkrajczar**
This is a 7_4_X backport of PR #9071

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by kkrajczar** [comment]
The tests seem to have failed because of DAS-related issues, which are not related to this PR. The errors are of this kind:

 cmsDriver.py stepTraceback (most recent call last):
  File "/afs/cern.ch/cms/sw/ReleaseCandidates/vol0/slc6_amd64_gcc491/cms/cmssw/CMSSW_7_4_X_2015-05-12-2300/external/slc6_amd64_gcc491/bin/das_client.py", line 447, in <module>
    main()
  File "/afs/cern.ch/cms/sw/ReleaseCandidates/vol0/slc6_amd64_gcc491/cms/cmssw/CMSSW_7_4_X_2015-05-12-2300/external/slc6_amd64_gcc491/bin/das_client.py", line 355, in main
    print_from_cache(opts.cache, query)
  File "/afs/cern.ch/cms/sw/ReleaseCandidates/vol0/slc6_amd64_gcc491/cms/cmssw/CMSSW_7_4_X_2015-05-12-2300/external/slc6_amd64_gcc491/bin/das_client.py", line 321, in print_from_cache
    data = open(cache).read()
IOError: [Errno 2] No such file or directory: 'das-cache.file'

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
+1

For #9072 790edb236513d07e24c73998dd96691b83825f23

Migration of HI HLT code to support multi-threading. It should not change monitored physics quantities. This PR is the same as #9071, which is aimed at 75X.

The code changes are satisfactory, and Jenkins [tests](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-9072/12/summary.html) against baseline CMSSW_7_5_X_2015-05-12-2300 show no significant differences, as expected.

**Comment by kkrajczar** [comment]
I think this PR has been forgotten, the orp signoff is pending since ~16 days. The 75X counterpart of this PR has already been merged.

**Comment by davidlange6** [comment]
@kkrajczar  - merging in 75x is not sufficient for a backport - needs to be validated first (so in 750pre5). In any case why is this PR important for 74x?

**Comment by kkrajczar** [comment]
Dear David,

Thank you for the comment. I don't know what the precise timeline/relevance for this PR to get into 74X is apart from the fact that the module from this PR is used at HLT. I thought not having this PR integrated 16 days after it was signed (except by the orp) was unusual, and that it might have been overlooked. If that is not the case, and everything goes as expected, I'm sorry about the noise.

Cheers,
Krisztian

**Comment by davidlange6** [comment]
+1

**Pull request merged**
