### PR TITLE
HLT menu development for `13_2_X` (5/N) [`13_3_X`]

### PR DESCRIPTION
**Pull request by mmusich**
backport of https://github.com/cms-sw/cmssw/pull/43300

#### PR description:

Development of HLT menus for CMSSW_13_2_X.
   * This is the final integration of the development in 13_2_X before moving to the new production cycle

This is the PR for the master branch, which will then be backported down to 13_2_X (the latter is the release cycle currently used for Run-3 HLT-menu development).

This version of the HIon HLT menu corresponds to the latest online updates performed by TSG/FOG to the "V1.1" menu for the 2023 heavy-ion data-taking period (the corresponding frozen menu is not added to the release, as not included in any central releae validation workflow).

In addition, the following changes are included:
   * 161ffba99ae14ecc33411af83a047e0926fad749: Update of L1T HIon menu to `v1_1_5` in `autoCondHLT.py`
   * c87e5c428e928a0697bea5a9d4a70ad19fe3ead0: revert customization of `FEVTDEBUGHLTEventContent` introduced in PR  https://github.com/cms-sw/cmssw/pull/43141  

This update includes the integration of the following JIRA tickets:
- [CMSHLT-2970](https://its.cern.ch/jira/browse/CMSHLT-2970) [TSG]: Online changes on 2023 HION menu v1.1
- [CMSHLT-2790](https://its.cern.ch/jira/browse/CMSHLT-2790) [TSG]: Remove prescalers from `RatesMonitoring` and `HLTAnalyzerEndpath`
- [CMSHLT-2964](https://its.cern.ch/jira/browse/CMSHLT-2964) [TSG]: Update of ReleaseValidation EventContent for HIon DQM
- [CMSHLT-2963](https://its.cern.ch/jira/browse/CMSHLT-2963) [HIN]: Add `HIZeroBias` PDs and pass-throughs for randoms and new L1T-Jet(UPC) seeds to "V1.1" HIon menu
- [CMSHLT-2898](https://its.cern.ch/jira/browse/CMSHLT-2898) [HIN]: Compression settings of HLT `OutputModules` in 2023 HIon menu
- [CMSHLT-2958](https://its.cern.ch/jira/browse/CMSHLT-2958) [HIN]: Increase prescale by factor of 5 for `Dataset_HIOnlineMonitor`
- [CMSHLT-2947](https://its.cern.ch/jira/browse/CMSHLT-2947) [HIN]: Add (12) UPC HLT paths with corresponding L1 seeds for ZDC asymmetry
- [CMSHLT-2887](https://its.cern.ch/jira/browse/CMSHLT-2887) [HIG]: Technical: rationalise VBF-parking triggers
- [CMSHLT-2956](https://its.cern.ch/jira/browse/CMSHLT-2956) [HIN]: Add ZDC1n seeded trigger paths on top of V1.1
- [CMSHLT-2955](https://its.cern.ch/jira/browse/CMSHLT-2955) [HIN]: Change version number of `HLT_HI*_HighRate_v` to "3"

#### PR validation:

TSG integration tests.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Intermediate backport of https://github.com/cms-sw/cmssw/pull/43300 to CMSSW_13_3_X.

### CODE REVIEW

**Comment by mmusich** [comment]
enable gpu

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
+hlt
   * see https://github.com/cms-sw/cmssw/pull/43300#issuecomment-1815038315

**Comment by antoniovilela** [comment]
backport of #43300

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
