### PR TITLE
PPS: DQM XY plots for different LV1 triggers

### PR DESCRIPTION
**Pull request by jan-kaspar**
This PR adds XY hit maps from Si strip sensors separately for several LV1 seeds of interest.

Urgent: this PR is needed for the 90m run starting this Saturday.

### CODE REVIEW

**Comment by jfernan2** [comment]
Failing test in replay: 

----- Begin Fatal Exception 28-Jun-2018 08:53:29 CEST-----------------------
An exception of category 'BadToken' occurred while
   [0] Processing  Event run: 318712 lumi: 90 event: 2112326 stream: 0
   [1] Running path 'path'
   [2] Calling method for module TotemRPDQMSource/'totemRPDQMSource'
Exception Message:
A get using a EDGetToken with the C++ type 'BXVector<GlobalAlgBlk>' was made using an uninitialized token.
 Please check that the variable is being initialized from a 'consumes' call.
----- End Fatal Exception -------------------------------------------------

**Comment by jan-kaspar** [comment]
@jfernan2 The problem should be fixed by 6d90075. The problem was due to config files missing the module to unpack the L1 trigger data. I have tested it with
https://github.com/CTPPS/cmssw/blob/6d9007546875c4d0716fbc32f421868ce0ac0984/DQM/Integration/python/clients/ctpps_dqm_sourceclient-live_cfg.py
using test = True and it worked.

**Comment by jfernan2** [comment]
+1

**Comment by fabiocos** [comment]
@jan-kaspar is there a master corresponding version of this PR? Is this going to be used after the 90 m beta* run?

**Comment by jan-kaspar** [comment]
@fabiocos this PR is only for the 90m run, thus no master counterpart.

**Comment by fabiocos** [comment]
@jan-kaspar sorry, apart that having pieces of code just in an old release is not our policy, but where is this being used? This is not part of any official release at the moment, is it another piece of code run only at online DQM level and that will be forgotten in a few days time?

**Comment by jan-kaspar** [comment]
@fabiocos The code is deployed by the DQM just now, for the 90m runs. As you write, it is quite likely that it will be "forgotten" in few-days time. In agreement with the DQM team, this PR was made as a convenient way how to integrate the patch into the deployed DQM.

**Comment by davidlange6** [comment]
Yes, its a hack for online dqm. Probably best that these hacks go as PRs against some other repo as to avoid confusion and extra work for people following cmssw developments...

**Comment by jan-kaspar** [comment]
Fine with me. Is there a preferred repo for these patches?

**Comment by jan-kaspar** [comment]
This PR was only needed for online monitoring of the beta*=90m run.

**Pull request closed without merging**
