### PR TITLE
let the customuzation for CA call the changes for PhaseI geometry 

### PR DESCRIPTION
**Pull request by JanFSchulte**
This gets rid of having to call two customization on top of each other. No changes to the actual configuration.

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by hengne** [comment]
@JanFSchulte 
btw, is it possible to ==> 

 def customizeHLTPhaseIPixelGeom(process):
 
 	for esproducer in esproducers_by_type(process,"ClusterShapeHitFilterESProducer"):
 		 esproducer.PixelShapeFile = 'RecoPixelVertexing/PixelLowPtUtilities/data/pixelShape_Phase1TkNewFPix.par'

==> make a selection of only hlt modules above, as the way did below?

 	for producer in producers_by_type(process,"SiPixelRawToDigi"):
 		if "hlt" in producer.label():
 			producer.UsePhase1 = cms.bool( True )

**Comment by makortel** [comment]
```
$ fgrep \"ClusterShapeHitFilter\" HLT_25ns15e33_v4_cff.py
  ComponentName = cms.string( "ClusterShapeHitFilter" ),
      ClusterShapeHitFilterName = cms.string( "ClusterShapeHitFilter" ),
      ClusterShapeHitFilterName = cms.string( "ClusterShapeHitFilter" )
        ClusterShapeHitFilterName = cms.string( "ClusterShapeHitFilter" ),
      ClusterShapeHitFilterName = cms.string( "ClusterShapeHitFilter" ),
      ClusterShapeHitFilterName = cms.string( "ClusterShapeHitFilter" ),
        ClusterShapeHitFilterName = cms.string( "ClusterShapeHitFilter" ),
        ClusterShapeHitFilterName = cms.string( "ClusterShapeHitFilter" ),

```
Simple grep indicates that the `fragment.ClusterShapeHitFilterESProducer` is likely being used, so probably a blind limitation to `hlt*` ESModules will not work.

**Comment by hengne** [comment]
and, is it really not possible to use eras to modify these parameters for phase1?
could some codes like below work?

at the end of :
HLTrigger/Configuration/python/HLT_GRun_cff.py

add: 
```
from Configuration.Eras.Modifier_phase1Pixel_cff import phase1Pixel

for esproducer in esproducers_by_type(fragment,"ClusterShapeHitFilterESProducer"):
    phase1Pixel.toModify(esproducer,  PixelShapeFile = 'RecoPixelVertexing/PixelLowPtUtilities/data/pixelShape_Phase1TkNewFPix.par'  )

for producer in producers_by_type(fragment,"SiPixelRawToDigi"):
      phase1Pixel.toModify(producer, UsePhase1=True)
```

**Comment by fwyzard** [comment]
This is actually something I need to look into.

**Comment by Martin-Grunewald** [comment]
What is the matter? HLT is run standalone anyway, so no need to worry about interfering
with RECO (HLT+RECO in one go is not validated).

**Comment by hengne** [comment]
the thing is this customization function customizeHLTPhaseIPixelGeom(process) is supposed to give the "default" correct configuration of the hlt menu to use 2017 pixel geometry. If this is the "default" it can be either implemented as the default in the HLT package (either the HLT_xxx_cff.py or the customizeHLTforXXX.py ) or in the runTheMatrix configurations through this customization function. 

 In the later case, it should be best to only apply the customization function on the HLT step, but the current matrix upagrade framework hasn't implement that separation yet,  it will by default apply the it to all steps (includeing reco).  

it would be subject to a discussion where to implement this default is the best way, but to me, it would be more natural to implement in the scope of hlt.

**Comment by Martin-Grunewald** [comment]
I thought we also want w/flows without, so it can't be applied always but must be switched by some changeable parameter.

**Comment by mtosi** [comment]
my 2 cents:
for having the proper configuration on 2017 geometry @ HLT
we need to make sure function customizeHLTPhaseIPixelGeom(process) [1] is **always** used / called

I also thought HLT menu in the release could make use of the Era,
but @Martin-Grunewald and @silviodonato are the experts on this

once such a feature (or analogous one) is implemented,
we can get rid of the customization function called by cmsDriver command


[1]
https://github.com/JanFSchulte/cmssw/blob/156561925e6469fcfe09bd117afa0af41e1adcf1/HLTrigger/Configuration/python/customizeHLTTrackingForPhaseI2017.py#L10

**Comment by Martin-Grunewald** [comment]
we do not have Eras in HLT customisations (Andrea B was looking into that but I guess this will take some time)

**Comment by hengne** [comment]
@Martin-Grunewald indeed, i also checked the configurations files in HLTrigger/Configuration  , eras is not implemented, but it should be easy to implement, some codes as i suggested here https://github.com/cms-sw/cmssw/pull/16868#issuecomment-265147665   should in principle work.

**Comment by hengne** [comment]
bottom line is we had this customization function here, the production can be done anyway with it in case the implementation of eras takes time.

**Comment by fwyzard** [comment]
@hengne , using Eras for `customizeHLTPhaseIPixelGeom` is indeed easy; however I have not been able to do it for `customizeHLTForPFTrackingPhaseI2017` yet

**Comment by fwyzard** [comment]
this is being implemented with Eras in #16977, please close

**Pull request closed without merging**
