### PR TITLE
add track algo and originalAlgo to PackedCandidates

### PR DESCRIPTION
**Pull request by slava77**
This PR adds track algo and originalAlgo to PackedCandidates as `uint8_t` data members; the values are filled with the same selections as other track properties (mainly driven by `pt> minPtForTrackProp`, the cut is at 0.95 GeV)

The primary use case so far is in the tag-and-probe measurements of tracking performance where general and muon tracking iterations need to be separated and the analysis is forced to use AOD, while a switch to miniAOD should be possible.

More use cases can arise for improved track quality selection and lower level debugging in miniAOD.

Tested in CMSSW_13_0_0_pre4 on `/store/relval/CMSSW_13_0_0_pre4/RelValTTbar_14TeV/GEN-SIM-RECO/PU_130X_mcRun3_2022_realistic_v2-v2/00000/{08b3cb94-2a3e-42c8-9374-46b4264dbef7.root,1a2b2a1d-133a-435c-b275-a4e3b651e71c.root,50823067-81cd-459a-baf7-aabc7851cce5.root,902c1d68-aa8e-49ea-94df-228edecdd3e9.root}` with 4000 events running PAT step (step4 from wf 11834.21).

- the sum of all products (using `edmEventSize`) compressed size increases by 238 B/ev or 0.27%
- The `packedPFCandidates` collection size increases by 0.5% or 205 B/event (from 43.3 kiB/ev)

This was proposed to XPOG in the [Jan 25 meeting](https://indico.cern.ch/event/1232579/?note=222311#6-pog-roundtable) (before the code was implemented and consequently before the file size measurements mentioned above)

### CODE REVIEW

**Comment by slava77** [comment]
type tracking

@mmusich

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by mandrenguyen** [comment]
@slava77 the`algo` assignment is from the track merging, based on which iteration gives the highest quality track, right?  `originalAlgo` is presumably the first iteration to find the track.  Can you remind me why the latter is important to keep track of?

**Comment by slava77** [comment]
> @slava77 the`algo` assignment is from the track merging, based on which iteration gives the highest quality track, right? `originalAlgo` is presumably the first iteration to find the track. Can you remind me why the latter is important to keep track of?

The `algo` is roughly as you describe but details may be more complicated (e.g. a more pure `initialStep` could be stopped earlier during building/fitting and may be overtaken with quality-driven assignment of a track made with a `jetCore` iteration in the final `algo`).

Knowledge of the `originalAlgo` turned out to be useful in the context of mkFit integration.
Also, it probably gives a smaller bias in the efficiency measurement compared to the `algo` when selecting purely tracker-driven iterations.

**Comment by slava77** [comment]
hold

I think I'm not filling it right

**Comment by slava77** [comment]
In the initial submission I missed to update the copy methods. Now the size impact is more significant

- The file size on disk increases per event by 1.45 kiB/ev (from 110 kiB); a 1.3% increase
- the sum of all products (using `edmEventSize`) compressed size increases by 1.43 kiB/ev or 1.3%
- The `packedPFCandidates` collection size increases by 3.2% or 1.41 kiB/event (from 43.3 kiB/ev)
(the PR description was updated)

I suppose that now the question is if this is acceptable or we need to add a lower pt cut.

**Comment by mmusich** [comment]
> I suppose that now the question is if this is acceptable or we need to add a lower pt cut.

@cms-sw/xpog-l2 @cms-sw/reconstruction-l2 please chime in here.

**Comment by mandrenguyen** [comment]
@mmusich well, it's a significant price to pay, clearly.  If the interest is limited to decided tracking studies, I guess we have to weight the inconvenience of using AOD for that, vs. the cost of increasing the miniAOD size.
Just stating the obvious here, that's about all I can contribute with the facts at hand.

**Comment by mandrenguyen** [comment]
Incidentally, would it save space to only set the originalAlgo when it's different than algo?
I'm assuming they are the same the majority of the time.

**Comment by mmusich** [comment]
> Incidentally, would it save space to only set the originalAlgo when it's different than algo?

I guess that's a good suggestion, but maybe even saving just the `originalAlgo` could work (pending confirmation from the developers).

> If the interest is limited to decided tracking studies, 

this would open up the possibility to use miniAOD also for other studies than the one in the description, e.g. re-vertexing studies and IP performance (and hence lessen e.g. the requirement for a new SKIM of the data). Also given that tracking performance studies are in high demand, creating hurdles with inaccessible datasets doesn't seem a good option - staging AOD is getting increasingly painful (@jordan-martins, - I can't find Kaori's gitHub nick).

**Comment by slava77** [comment]
The last update now fills the algo/originalAlgo at the same time as more detailed track properties (`pt > minPtForTrackProp`). This reduces the size increase from 1.3% to 0.3% of the file size. Can we stay with this?

- The file size on disk increases per event by 316 B/ev (from 110 kiB); a 0.35% increase
- the sum of all products (using `edmEventSize`) compressed size increases by 311 B/ev or 0.35%
- The `packedPFCandidates` collection size increases by 0.7% or 278 B/event (from 43.3 kiB/ev)
(the PR description was updated)

**Comment by slava77** [comment]
unhold

**Comment by slava77** [comment]
> I tested saving only one and the size decreases by only 35% (not 50%); it looks like the compression already figures out similar/same values.

OTOH, only 5% of non-zero algos have a different originalAlgo. So, perhaps a smarter variant is indeed worth an effort.

**Comment by slava77** [comment]
In the latest variant I 
- repacked the two iteration chars to a uint16_t, which provides a noticeable size decrease from `+278 B/evt` to `+212 B/evt` in 4K events of `packedPFCandidates`
- save the upper byte only if the `originalAlgo` is not equal to `algo`, which happens only in 5% cases. This gives a small saving reducing total increase in `packedPFCandidates` to just `+205 B/evt`. Evidently the compression is already very effective in this case.

So, now over 4K events
- the sum of all products (using `edmEventSize`) compressed size increases by 238 B/ev or 0.27%
- The `packedPFCandidates` collection size increases by 0.5% or 205 B/event (from 43.3 kiB/ev)
(the PR description was updated)

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by mandrenguyen** [comment]
+reconstruction
Modest increase in miniAOD size as explained in https://github.com/cms-sw/cmssw/pull/41183#issuecomment-1487046900
Adds an extra integer that specifies which iteration tracks that are linked to PF charged hadrons come from. 
Needed for tracking studies.

**Comment by slava77** [comment]
@cms-sw/xpog-l2 
do you have additional comments for this PR?
Please check and comment or sign.
Thank you.

**Comment by vlimant** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
