### PR TITLE
new features for offline Tk DQM scripts: 75X

### PR DESCRIPTION
**Pull request by vdutta**
75X version of #10757
- Automatic creation of root files with information from SiStrip tracker maps indexed by DetId, will be done at the time of tracker map creation by Tracker Offline shifter.
- Addition of run numbers to the headings of the tracker maps created offline.

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
+1 for https://github.com/vdutta/cmssw/commit/24a92a37cc43c88ef131102521442a694a7ab25b

**Comment by deguio** [comment]
-1
rebase needed

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1

**Comment by diguida** [comment]
+1
backport of #10759 (tests passed, still not in...)

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
+1

**Comment by deguio** [comment]
-1
needs rebase

**Comment by deguio** [comment]
@vdutta 
could you please rebase this one so that we keep 75 aligned with the following cycles?
thanks in advance,
F.

**Comment by vdutta** [comment]
@deguio Done, it needed a second update because it got out of sync again after the first one.

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1

**Comment by mmusich** [comment]
+1

**Comment by diguida** [comment]
+1

**Comment by diguida** [comment]
@mmusich don't touch my PR ;-)

**Comment by davidlange6** [comment]
+1

**Pull request merged**
