### PR TITLE
Use FileInPath to use CMS Style File Location

### PR DESCRIPTION
**Pull request by ianna**
* Refer to XML files CMS-style
* Add a test analyzer to store detector geometry
* Add a test analyzer to access vectors

To view stored test geometry:
```
$ root cmsDD4HepGeom.root
root [1] TGeoManager *test = dynamic_cast<TGeoManager*>(_file0->Get("world"))
root [2] test->GetTopVolume()->Draw("OGL")
```
screenshot 2018-05-11 12 39 46

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
please test

**Comment by fabiocos** [comment]
@ianna good to hear that DD4Hep will move under the LGPLv3 licence. Concerning this PR:

- testShapes.py and dump.py looks full test configuration files more than fragments to be included, would not be better to have them in the test subdirectory?

**Comment by ianna** [comment]
@fabiocos - indeed, I'll move them to test.

The error is a bug. Thanks for reporting it.
```
cmsRun DetectorDescription/DDCMS/python/dump.py
```

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by alja** [comment]
+1

**Comment by fabiocos** [comment]
+1

the test configurations now run producing the required dumps

**Pull request merged**
