### PR TITLE
Run3-gem62E Correct use of ESGetToken for GEMGeometry using suggestion from Matti

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Correct use of ESGetToken for GEMGeometry using suggestion from Matti (in PR #34214)

#### PR validation:

Use the runTheMatrix test workflows

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by civanch** [comment]
@srimanob, let us merge also this PR

**Comment by bsunanda** [comment]
@srimanob Please approve this PR.

**Comment by srimanob** [comment]
@bsunanda @makortel 
Sorry for the late. I was not sure from @makortel comment,
https://github.com/cms-sw/cmssw/pull/34214#discussion_r656695574
I understand that the comment is to keep using getHandle, but the PR seems to confirm on using getData. Could you please confirm? Thanks.

**Comment by makortel** [comment]
> I was not sure from @makortel comment,
> [#34214 (comment)](https://github.com/cms-sw/cmssw/pull/34214#discussion_r656695574)
> I understand that the comment is to keep using getHandle

I just wanted to point out that going from `getHandle()` to `getData()` changes functionality (and that checking `&iSetup.getData() != nullptr` doesn't make sense). Personally I'm in favor of `getData()` and letting exceptions being thrown when a necessary data product is missing, especially for configuration errors (although there can be cases where data processing should continue even when something is missing).

**Comment by srimanob** [comment]
Thanks @makortel 
Then this PR seems reasonable change then.

**Comment by srimanob** [comment]
+Upgrade

**Comment by qliphy** [comment]
+1

**Pull request merged**
