### PR TITLE
Fix bug related to cmsRun exit code with FileReadError, 13_3_X back port

### PR DESCRIPTION
**Pull request by wddgit**
#### PR description:

Fix bug related to cmsRun exit code with FileReadError exception. It was returning 8001 instead of 8021. See Issue https://github.com/cms-sw/cmssw/issues/42179 for more discussion.

#### PR validation:

Relies on existing tests. In addition, there is a new unit test in 14_0_X.

### CODE REVIEW

**Comment by wddgit** [comment]
please test

**Comment by makortel** [comment]
+core

**Comment by antoniovilela** [comment]
@wddgit 
Just to confirm, it is not intended to backport https://github.com/cms-sw/cmssw/pull/43579/files#diff-6bd75e9194ed7be5dc7abade07e02957d83ddeda583a38f120fef14971a4fdf7, correct?

**Comment by makortel** [comment]
> Just to confirm, it is not intended to backport https://github.com/cms-sw/cmssw/pull/43579/files#diff-6bd75e9194ed7be5dc7abade07e02957d83ddeda583a38f120fef14971a4fdf7, correct?

Correct (omitting the test for the backports was mentioned also in the description of https://github.com/cms-sw/cmssw/pull/43579)

**Comment by wddgit** [comment]
Yes. It was intentional. It would have been difficult to backport the unit test. The file ```testSchemaEvolution.sh``` didn't exist before 13_3_X and there were changes between 13_3_X  and 14_0_X in that file. It would have been a lot of work to backport because I would have had to backport all the schema evolution test development. The bug fix itself is identical so far in all the backports. It also only affects one file and probably we won't backport any else that might interact with this area of the code.

**Comment by antoniovilela** [comment]
> > Just to confirm, it is not intended to backport https://github.com/cms-sw/cmssw/pull/43579/files#diff-6bd75e9194ed7be5dc7abade07e02957d83ddeda583a38f120fef14971a4fdf7, correct?
> 
> Correct (omitting the test for the backports was mentioned also in the description of #43579)

True, thanks.

**Comment by antoniovilela** [comment]
> Yes. It was intentional. It would have been difficult to backport the unit test. The file `testSchemaEvolution.sh` didn't exist before 13_3_X and there were changes between 13_3_X and 14_0_X in that file. It would have been a lot of work to backport because I would have had to backport all the schema evolution test development. The bug fix itself is identical so far in all the backports. It also only affects one file and probably we won't backport any else that might interact with this area of the code.

Thanks.

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
