### PR TITLE
Fix Phase2 memory corruption

### PR DESCRIPTION
**Pull request by kpedro88**
This PR addresses two of the memory corruption issues in Phase2 workflows, found by valgrind and noted in #16493 (which contains extensive discussion of the causes).

### CODE REVIEW

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by monttj** [comment]
+1

**Comment by cvuosalo** [comment]
@kpedro88: Why does this fix make small changes to tracking, jet, and tagging quantities? Changes are appearing in the Jenkins DQM plots.

**Comment by kpedro88** [comment]
@cvuosalo `GenericBinFinderInZ` is used in Phase2 tracking code. Before this fix, it could try to access uninitialized memory (`reserve`d but not `push_back`d). I presume the use of uninitialized values happened fairly infrequently or there would have been obvious physics performance indicators.

**Comment by slava77** [comment]
On 11/23/16 4:34 PM, Kevin Pedro wrote:
> @cvuosalo <https://github.com/cvuosalo> |GenericBinFinderInZ| is used in
> Phase2 tracking code. Before this fix, it could try to access
> uninitialized memory (|reserve|d but not |push_back|d). I presume the
> use of uninitialized values happened fairly infrequently or there would
> have been obvious physics performance indicators.

GenericBinFinderInZ is used in muon code since a while (CMSSW_1).
Did you find a bug or is it a kludge fixing a  problem with an origin
somewhere else?

**Comment by kpedro88** [comment]
It looks like an actual bug to me.
```
theNbins( last-first)
theBins.reserve(theNbins);
for (ConstItr i=first; i<last-1; i++) {
```
With that setup, `theBins` reserves 1 more entry than gets filled (`last-1` is never pushed back). `GenericBinFinderInZ::binIndex(T z)` can return any index up through `theNbins-1`, which can then be used with `GenericBinFinderInZ::binPosition(int ind)` to access values in `theBins`. `theBins[theNbins-1]` is uninitialized (according to both the above logic and valgrind).

**Comment by slava77** [comment]
On 11/23/16 4:58 PM, Kevin Pedro wrote:
> It looks like an actual bug to me.
> 
> |theNbins( last-first) theBins.reserve(theNbins); for (ConstItr i=first;
> i<last-1; i++) { |
> 
> With that setup, |theBins| reserves 1 more entry than gets filled
> (|last-1| is never pushed back). |GenericBinFinderInZ::binIndex(T z)|
> can return any index up through |theNbins-1|, which can then be used
> with |GenericBinFinderInZ::binPosition(int ind)| to access values in
> |theBins|. |theBins[theNbins-1]| is uninitialized (according to both the
> above logic and valgrind).

OK.
Looks like the muon code didn't use the binPosition method to stumble on
theBins size mismatch

**Comment by cvuosalo** [comment]
Tests in progress...

**Comment by cvuosalo** [comment]
+1

For #16696 4ce4f0f80a447c74e8b6eb0e5301f9c3c05d39f9

Fixing two memory corruption problems seen in Phase 2 testing.

#16697 is the 81X version of this PR.

The code changes are satisfactory. Jenkins tests against baseline CMSSW_9_0_X_2016-11-19-1100 show no significant differences, except in Phase 2 workflows, where there are numerous tiny, insignificant differences. A test of workflow 1321.0_SingleMuPt100 with 1000 events against baseline CMSSW_9_0_X_2016-11-19-1100 shows no significant differences, while a test of Phase 2 workflow 23234.0_TTbar_14TeV+TTbar_14TeV_TuneCUETP8M1_2023D5_GenSimHLBeamSpotFull14+DigiFull_2023D5 with 150 events against baseline CMSSW_9_0_X_2016-11-21-1400 shows numerous tiny, insignificant differences in downstream Reco quantities related to jets, tracks, and vertices.

**Pull request merged**
