### PR TITLE
bsunanda:Run2-hcx67 Default 2017 scenario which has 2017 pixel but 2016 HCAL

### PR DESCRIPTION
**Pull request by bsunanda**
The 2017dev version has 2017 pixel and 2017 HCAL

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by davidlange6** [comment]
@bsunanda - We need the reverse of this - we need the 2017 geometry to be working (as it has been), so 2017dev should be the 2017 hcal (not working yet) until its working.

**Comment by bsunanda** [comment]
@davidlange6 That is precisely what it is. 2017 is the one with 2016 HCAL and 2017 pixel and it is supposed to be working while 2017dev is the one with 2017 HCAL and Pixel where we have to put more work to make it working

**Comment by davidlange6** [comment]
ok, I misread - testing now.. Thanks

**Comment by davidlange6** [comment]
workflow 10039 still has a problem

----- Begin Fatal Exception 16-Feb-2016 20:19:10 CET-----------------------
An exception of category 'Filling of conditions failed' occurred while
   [0] Processing run: 1 lumi: 1 event: 1
   [1] Running path 'digitisation_step'
   [2] Calling event method for module MixingModule/'mix'
   [3] Using EventSetup component HcalDbProducer/'hcal_db_producer' to make data HcalDbService/'' in record HcalDbRecord
   [4] Using EventSetup component HcalHardcodeCalibrations/'es_hardcode' to make data HcalGainWidths/'' in record HcalGainWidthsRcd
Exception Message:
 no valid filling possible for Conditions of type HcalGainWidths for DetId (0x43300448) (HB -1,72,3)
----- End Fatal Exception -------------------------------------------------
Another exception was caught while trying to clean up files after the primary fatal exception.
16-Feb-2016 20:19:10 CET  Closed file file:step1.root

**Comment by bsunanda** [comment]
@davidlange6 This will be cured after merging of bsunanda:Run2-hcx66

**Comment by davidlange6** [comment]
ok, checking that (since its merged since a few hours its not in my test)

**Comment by davidlange6** [comment]
can be good if you take over the testing... not so simple [its progress though]

%MSG-e HCAL:  MixingModule:mix 16-Feb-2016 21:11:42 CET Run: 1 Event: 1
Inconsistent dense packing between current topology (10) and calibration object (0)
%MSG
----- Begin Fatal Exception 16-Feb-2016 21:11:51 CET-----------------------
An exception of category 'Conditions mismatch' occurred while
   [0] Processing run: 1 lumi: 1 event: 1
   [1] Running path 'digitisation_step'
   [2] Calling event method for module MixingModule/'mix'
Exception Message:
Requested conditions of type HcalGains for cell (0x43182c42) (HB 11,66,1) got conditions for cell (0x42004290) (HB -5,16,1)
----- End Fatal Exception -------------------------------------------------
Another exception was caught while trying to clean up files after the primary fatal exception.
16-Feb-2016 21:11:51 CET  Closed file file:step1.root

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@davidlange6 Now the workflow 10039 runs without crashes. I do not know why but had to check out L1Trigger/L1TGlobal and compile before the who;e thing works

**Comment by bsunanda** [comment]
@ianna Could you please review and sign this. It is needed to make the 2017 workflow operational

**Comment by ianna** [comment]
+1

**Pull request merged**
