### PR TITLE
[13_0_X] Remove call to alpaka::getDev() in test code when allocating TestDeviceCollection

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

Backport of #40789 (same commit)

#### PR validation:

None beyond #40789

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport of #40789 to 13_0_X in order to keep the Alpaka code consistent between 13_0_X and 13_1_X.

### CODE REVIEW

**Comment by makortel** [comment]
enable gpu

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by fwyzard** [comment]
+heterogeneous

**Comment by perrotta** [comment]
backport of https://github.com/cms-sw/cmssw/pull/40789

**Comment by perrotta** [comment]
+1

**Pull request merged**
