### PR TITLE
Add missing newlines in Utilities modules

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Add missing newlines at the end of the files under
```
Utilities/RelMon
Utilities/ReleaseScripts
Utilities/StorageFactory
```
.

#### PR validation:

None.

### CODE REVIEW

**Comment by fwyzard** [comment]
please test

**Comment by makortel** [comment]
+core

**Comment by tjavaid** [comment]
+1

**Comment by rappoccio** [comment]
+1

**Pull request merged**
