### PR TITLE
various updates to the FastTimerService and ThroughputService

### PR DESCRIPTION
**Pull request by fwyzard**
- Let the `FastTimerServce` account resources spent in `acquire()`.
    For modules that implement the acquire()/produce() semantic, the per-event measurements are reset and accounted after the call to acquire(), and updated after the call to produce();
    For modules that do not implement the acquire()/produce() semantic
there should be no changes.

  - Clean up defaulted constructors and destructors.

  - Remove the unsafe `FastTimerService::query...()` methods.
    Those methods are not protected against accessing a module's properties *before* a module has actually run, or even *while* it is running.
    The only use case left in CMSSW was a `LogVerbatim` message in the `IsoTrig` `EDAnalyzer`.

  - Move the `FastTimerService` code base into the plugins directory.

  - Add support for reading the processor model on BSD and OS X (untested).

  - Optionally, the `ThroughputService` can arrange plots in a per-cpu-name folder, and the `ThroughputServiceClient` should merge them back.

### CODE REVIEW

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by fwyzard** [comment]
@Dr15Jones , let me know if you would rather have `memory_usage.[h|cc]` and/or `processor_model.[h|cc]` somewhere more central.

**Comment by davidlange6** [comment]
please test

**Comment by fwyzard** [comment]
+1

**Comment by fwyzard** [comment]
While I would like to push at least two more change sets, I doubt I will be able to do so before leaving on Friday.
Thus, I would say the PR is be good to be integrated in its present shape - I will try to follow up on the rest by the end of July.

**Comment by fabiocos** [comment]
@fwyzard besides seeing no problem in the short matrix (or IB after integration), which kind of validation was done/will be done on such update?

**Comment by fwyzard** [comment]
@fabiocos I am not aware of any offline workflow that should be affected by these changes.
For the HLT, I will not be able to run any tests for the next couple of weeks - I do not know if the STORM or FOG groups will test it further in the meantime.

**Comment by lpernie** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
