### PR TITLE
Phase2-hgx299 Add the dd4hep version of the algorithm to make rotated full wafers as in #36898

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Add the dd4hep version of the algorithm to make rotated full wafers as in #36898

#### PR validation:

Tested together with #36898 for the dd4hep version

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cvuosalo @srimanob please approve this PR

**Comment by bsunanda** [comment]
@cvuosalo @srimanob please approve this PR

**Comment by cvuosalo** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

The code introduced in this PR is in line with the description. PR test runs fine, and no change is observed (as expected).

**Comment by qliphy** [comment]
+1

**Pull request merged**
