### PR TITLE
Fixing HGCal Hexagonal Geometry Round 1

### PR DESCRIPTION
**Pull request by lgray**
This PR fixes a number of bugs in the HGCal geometry.
Previous to this PR the HGCal Hex geometry did not produce simhits.
- Set the silicon as the sensitive detector to read out.
- Logically factorize EE and HE cells and wafers so they can be read out separately.
- Fix packing of hexagon indices to be compatible with the ranges of wafers/cells/layers encountered
- Speed ups to the DDD constants class

Event display for RECO geometry of pT = 35 GeV electron seems to be OK.
screen shot 2016-01-22 at 18 30 39
Likewise, energy distributions look good now.
screen shot 2016-01-22 at 16 24 57

While simulating, there are still invalid detids encountered in the sensitive detector, so I do not think we are done yet.

@bsunanda

### CODE REVIEW

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
@sethzenz @kpedro88 @cseez

**Comment by lgray** [comment]
oops, forgot a commit.

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by ianna** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
