### PR TITLE
Prompt DQM for Pure MET Triggers 93X

### PR DESCRIPTION
**Pull request by physicist87**
https://its.cern.ch/jira/browse/CMSHLT-1421

This PR is for Pure MET Triggers. 

This PR is related to #19685 

We only modified METMonitor_cff.py to add MET Triggers.

### CODE REVIEW

**Comment by mtosi** [comment]
@cmsbuild, please test

**Comment by mtosi** [comment]
@physicist87 I think you need to rebase

**Comment by physicist87** [comment]
@mtosi  I see the status of #19685. I think their are some problem during the test the PR.  So I guess this PR also have same problem.

**Comment by mtosi** [comment]
what about the following trigger paths ?

HLT_L1ETMHadSeeds_v*
HLT_PFMET200_HBHE_BeamHaloCleaned_v*
HLT_PFMET200_HBHECleaned_v*
HLT_PFMET200_NotCleaned_v*
HLT_PFMET250_HBHECleaned_v*
HLT_PFMET300_HBHECleaned_v*
HLT_PFMETTypeOne200_HBHE_BeamHaloCleaned_v*

**Comment by mtosi** [comment]
tracked by https://github.com/cms-sw/cmssw/issues/19142

**Comment by physicist87** [comment]
@mtosi Oh I'm sorry I added wrong file. So I missed triggers you mentioned I will updated this PR sorry.

**Comment by fwyzard** [comment]
@cmsbuild, please abort

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by dmitrijus** [comment]
+1

**Comment by fwyzard** [comment]
@physicist87 if you don't mind, I will include your commits in a single PR where I am merging other changes, to avoid conflicts with other PRs.

We should keep this PR open until the other is merged.

**Comment by fwyzard** [comment]
@davidlange6 this PR is signed by DQM, and I think the changes are only in the python configuration.

Do you have any objections if I include it in a second "merged" PR to fix the various conflicts ?

**Comment by davidlange6** [comment]
hi @fwyzard - i can't really comment - this PR looks to contain several others, so I don't know what the new/unique stuff in this PR actually is..

**Comment by fwyzard** [comment]
These PR have been forced to include others' developments, because there were not being integrated. 

How do you suggest to proceed ?

.A

**Comment by physicist87** [comment]
@fwyzard  This pr has problem during Test. Should I fix it ? I think I missed your last commit (remove multiple definition of the same modules : https://github.com/cms-sw/cmssw/pull/19685/commits/c6f38149975d0c5a4732874c1930c763e0ca6a9a). 
Should I fix this PR ?

**Comment by fwyzard** [comment]
@davidlange6 for example you could look at the commit history; AFAICT only the last two commits are new for this PR
  - 10d4efb2e5786d1a7812f7585841b7d9ea91c6fe
  - 2ce204ce8ea736f7342aae515d8be3d761355616
and they touch only the python configuration 
  - DQMOffline/Trigger/python/METMonitor_cff.py

I am going to include these changes directly in #19685 or in a follow up PR.

**Comment by davidlange6** [comment]
> On Jul 13, 2017, at 8:52 AM, Andrea Bocci <notifications@github.com> wrote:
> 
> @davidlange6 for example you could look at the commit history; AFAICT only the last two commits are new for this PR
> 
> 	• 10d4efb
> 	• 2ce204c
> and they touch only the python configuration
> 	• DQMOffline/Trigger/python/METMonitor_cff.py
> I am going to include these changes directly in #19685 or in a follow up PR.

which is to say this PR has picked up a bunch of orthogonal unneeded (for the development and testing of this PR) stuff. Is this due to some set of instructions people are following that should be fixed?

I think there are also changes in METMonitor.cc/h

anyway seems the only questions are 
how many histogram bins this adds 
that "unsigned" needs to be unsigned int.
to avoid the unneeded copy of the reco::Vertex by making vtx a const pointer.

**Comment by fwyzard** [comment]
hi David,
@physicist87 should answer about the number of bins.

The reason for picking up the previous PRs is because you keep nor merging them, so I'm doing it in #19685 to avoid having to resolve conflicts every single time.

I *did* do the merge locally, and as I wrote the only changes introduced by this PR are in `DQMOffline/Trigger/python/METMonitor_cff.py`

You comments about the code then should be addressed to the relevant PR.

**Comment by davidlange6** [comment]
> On Jul 13, 2017, at 9:27 AM, Andrea Bocci <notifications@github.com> wrote:
> 
> hi David,
> @physicist87 should answer about the number of bins.
> 
> The reason for picking up the previous PRs is because you keep nor merging them, so I'm doing it in #19685 to avoid having to resolve conflicts every single time.
> 

I don't understand what you mean actually.  There are aparently a few files changed - but there a bunch of changes in unrelated files added. We aren't in CVS after all. Sorry that making and addressing comments takes time - but I think i'm doing my part to keep up.


> I did do the merge locally, and as I wrote the only changes introduced by this PR are in DQMOffline/Trigger/python/METMonitor_cff.py
> 
> You comments about the code then should be addressed to the relevant PR.

Sorry I cannot work that way (since I'm bad at guessing). We need PRs that have independent changes. Of course sometimes a PR will have to pick up some changes and then rebased if the same piece of a file is changed by multiple PRs. But that is not what we are talking about.

**Comment by fwyzard** [comment]
> Sorry I cannot work that way (since I'm bad at guessing). We need PRs that have independent changes. Of course sometimes a PR will have to pick up some changes and then rebased if the same piece of a file is changed by multiple PRs. But that is not what we are talking about.

That would have been possible one and a half months ago.

In the meantime the PRs accumulated, done by over 10 different people for the same or different code base and python configurations, merging one another and conflicting with one another.

So, now I'm trying to sort out the mess. 

What I would ask is to trust what I tell you about which commits "belong" to each PR, in order to base you comments only on the relevant part, and to let me know which ones you consider "ok" to be merged, so I can add them one by one to #19685 (or a follow up I'll be making shortly after).

**Comment by physicist87** [comment]
@fwyzard 
Dear andrea, should I answer the number of bins for each histograms in METMonitor.cc ?

**Comment by fwyzard** [comment]
yes, please: with the given python configuration, how many bins do we get, counting all the histograms ?

**Comment by davidlange6** [comment]
> On Jul 13, 2017, at 11:54 AM, Andrea Bocci <notifications@github.com> wrote:
> 
> Sorry I cannot work that way (since I'm bad at guessing). We need PRs that have independent changes. Of course sometimes a PR will have to pick up some changes and then rebased if the same piece of a file is changed by multiple PRs. But that is not what we are talking about.
> 
> That would have been possible one and a half months ago.
> 
> In the meantime the PRs accumulated, done by over 10 different people for the same or different code base and python configurations, merging one another and conflicting with one another.
> 
> So, now I'm trying to sort out the mess.
> 
> What I would ask is to trust what I tell you about which commits "belong" to each PR, in order to base you comments only on the relevant part, and to let me know which ones you consider "ok" to be merged, so I can add them one by one to #19685 (or a follow up I'll be making shortly after).
> 

I simply don't see how your generic point applies here at all. But ok, lets try and see if it works without creating lots of work. Probably you should just make a list for each pr.

**Comment by fwyzard** [comment]
Mhm, a list of what ?

**Comment by physicist87** [comment]
@davidlange6 @fwyzard  
In this PR, I only updated Pure MET Trigger  modifying METMonitor_cff.py .
The Trigger List is 

HLT_L1ETMHadSeeds_v*
HLT_CaloMHT90_v*
HLT_CaloMET70_HBHECleaned_v*
HLT_CaloMET80_HBHECleaned_v*
HLT_CaloMET80_NotCleaned_v*
HLT_CaloMET90_HBHECleaned_v*
HLT_CaloMET90_NotCleaned_v*
HLT_CaloMET100_HBHECleaned_v*
HLT_CaloMET100_NotCleaned_v*
HLT_CaloMET110_NotCleaned_v*
HLT_CaloMET250_HBHECleaned_v*
HLT_CaloMET250_NotCleaned_v*
HLT_CaloMET300_HBHECleaned_v*
HLT_CaloMET350_HBHECleaned_v*
HLT_PFMET200_HBHE_BeamHaloCleaned_v*
HLT_PFMET200_HBHECleaned_v*
HLT_PFMET200_NotCleaned_v*
HLT_PFMET250_HBHECleaned_v*
HLT_PFMET300_HBHECleaned_v*
HLT_PFMETTypeOne200_HBHE_BeamHaloCleaned_v*

Total Triggers are 20. 

And each trigger has 
deltaphi_jet1jet2  ( nbins : 64, numerator & denominator   ), 
deltaphi_metjet1 ( nbins : 64, numerator & denominator    ),
metPhi_( # of Bins : 64, numerator & denominator  ),
metVsLS_ ( #of Bins :2500 , numerator & denominator  ),
met_ (#of Bins : 200, numerator & denominator )
met_variable (# of bins : 25 ,numerator & denominator)
effic_met ( #of Bins : 200 ),
effic_metPhi ( #of Bins : 64 ),
effic_met_variable ( # of bins : 25 ),
effic_met_vs_LS ( #of Bins : 2500  ). So total the number of bins is 8627 for each trigger which I add. 

Total of the number of bins : 8627 *20 = 172540.

**Pull request merged**
