### PR TITLE
[10.1.X] Updates in SiStrip PI classes: activate tests and additional plots for Strip Noise, Gains and Bad Components

### PR DESCRIPTION
**Pull request by mmusich**
Several updates in the Strip Payload  Inspector:
   * make the SiStrip PI unit tests actually be exercised; 
   * add history of min,max and rms of SiStrip ApvGains;
   * add Strip Noise comparison by region of mean,rms,min & max by module;
   * add Strip Noise aggregate values comparison plots;
   * add detailed (by Module, Fiber, APV and Strip) comparison of Strip Bad Components between two IOVs;
   * add fraction of bad components to total in Strip Bad Components analysis comparison between two IOVs;

### CODE REVIEW

**Comment by ggovi** [comment]
+1

**Comment by fabiocos** [comment]
@mmusich is this code running just in the cpp code modified here in a standalone mode? Or is it part of more general workflows?

**Comment by mmusich** [comment]
@fabiocos I am not sure to understand your question. This code is not run anywhere in production workflows, but it is used to create the plots displayed in the [payload inspector](https://cms-conddb.cern.ch/cmsDbBrowser/payload_inspector/Prod). As such there is no guarantee it stays functional, as it is not probed in relvals, etc. 
The file `CondCore/SiStripPlugins/test/testSiStripPayloadInspector.cpp` used to allow the expert user to test some of the classes in standalone mode, but was not possible to run an actual unit test, due to the fact that before this commit https://github.com/cms-sw/cmssw/pull/21617/commits/a17b352e80e834ad7e6d35aa4eed583a801ac9e4, only direct oracle connection was supported, which is not supposed to work in the offline world unless reading credentials are supplied. 
Now, it is possible to read from `fronTier` and so it can be made part of a unit test.
Hope this answers your questions.

**Comment by fabiocos** [comment]
@mmusich this is what I wanted to understand, thanks

**Comment by fabiocos** [comment]
+1

**Pull request merged**
