### PR TITLE
ecalDigis: do not explicitly set default value

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

`ecalDigis.DoRegional = False` is the default value, no need to set it explicitly in the cff files.

### CODE REVIEW

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by fwyzard** [comment]
I would say the the error
```
Begin processing the 1st record. Run 320822, Event 26886180, LumiSection 17 on stream 0 at 14-May-2020 11:33:46.247 CEST
----- Begin Fatal Exception 14-May-2020 11:33:57 CEST-----------------------
An exception of category 'ProductNotFound' occurred while
   [0] Processing  Event run: 320822 lumi: 17 event: 26886180 stream: 0
   [1] Prefetching for module PFCandidateDQMAnalyzer/'ElectronValidation1'
   [2] Prefetching for module PATElectronSlimmer/'slimmedElectrons'
   [3] Prefetching for module PATElectronSelector/'selectedPatElectrons'
   [4] Prefetching for module PATElectronProducer/'patElectrons'
   [5] Prefetching for module CITKPFIsolationSumProducerForPUPPI/'egmElectronPUPPIIsolation'
   [6] Calling method for module PATPackedCandidateProducer/'packedPFCandidates'
Exception Message:
Principal::getByToken: Found zero products matching all criteria
Looking for type: edm::ValueMap<float>
Looking for module label: puppi
Looking for productInstanceName: 

----- End Fatal Exception -------------------------------------------------
```
is unrelated to this PR.

**Comment by slava77** [comment]
@cmsbuild please test with #29826 
this will be needed until jenkins moves on to 05-14-1100 IB

**Comment by silviodonato** [comment]
abort

**Comment by silviodonato** [comment]
please test

**Comment by silviodonato** [comment]
+1

**Pull request merged**
