### PR TITLE
Adding no-HF grid-based rho : 76x forward-port

### PR DESCRIPTION
**Pull request by rappoccio**
Forward port of #11771

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
There is no explicit keep statement here.
It is required from 76X (well, the mechanism is almost in place: AOD and RECO will miss this product).

**Comment by rappoccio** [comment]
Weird. Merged for me. I will close this and re-open with another branch.

**Comment by slava77** [comment]
regarding https://github.com/cms-sw/cmssw/pull/11774#issuecomment-147824852
I think it's the result of changes in the latest IBs compared to what's allowed for jenkins to be used for tests (it used CMSSW_7_6_X_2015-10-12-1100)

Sal, I think you can reopen the PR and we wait for a working IB to restart the tests.

**Comment by rappoccio** [comment]
@slava77 OK I will wait then. This was reopened.

**Comment by smuzaffar** [comment]
please test

**Comment by slava77** [comment]
Sal,
you still need to add  keep statements for fixedGridRhoFastjetCentral in 
RecoJets/Configuration/python/RecoJets_EventContent_cff.py
This is needed in 76X

**Comment by rappoccio** [comment]
Doesn't this get added here? 

https://github.com/rappoccio/cmssw/blob/a3fbc0333111cc90f4d4880f4503005ee00b0c1e/RecoJets/Configuration/python/RecoJets_EventContent_cff.py#L76

**Comment by slava77** [comment]
No, your commit blob points to what's in 75X.
It looks like you will need to redo this PR starting from a recent 76X (pre7 will work) so that the EventContent file is picked up correctly

**Comment by rappoccio** [comment]
Ahh, yes, okay this changed in 76x for whatever reason. I will close this and reopen with a new branch (this is also used for the 75x PR).

**Comment by rappoccio** [comment]
See here for new PR : https://github.com/cms-sw/cmssw/pull/11855

**Pull request closed without merging**
