### PR TITLE
Clean up from conddb V1 code: step II

### PR DESCRIPTION
**Pull request by ggovi**
- Removed all the dependencies on CondCore/IOVService
- The CondCore/IOVService package is left empty ( can be removed )
- The Conddb V1 python binding in  CondCore/Utilities/ package has been also removed. This implies the deletion of all the PayloadInspector plugins implemented in the various CondCore/[Detector]Plugins packages.
- The command line tools for V1 in CondCore/Utilities have been removed.

### CODE REVIEW

**Comment by ggovi** [comment]
@cmsbuild please test

**Comment by diguida** [comment]
@ggovi the web diff shows that the V1 binaries are still there, with no changes. I am checking out the branch locally in order to be fully sure.
OTOH, it looks ok to me.

**Comment by diguida** [comment]
````
$ git diff --stat CMSSW_8_0_X_2015-12-02-2300
CondCore/BeamSpotPlugins/plugins/BeamSpotObjectsPyWrapper.cc           | 209 ---------------------------------------------------------------------
 CondCore/BeamSpotPlugins/plugins/BuildFile.xml                         |  12 ----
 CondCore/CSCPlugins/plugins/BuildFile.xml                              |  12 ----
 CondCore/CSCPlugins/plugins/CSCBadChambersPyWrapper.cc                 |  46 ----------------
 CondCore/CSCPlugins/src/plugin.cc                                      |  10 ++--
 CondCore/CalibPlugins/plugins/BuildFile.xml                            |   9 ---
 CondCore/CalibPlugins/plugins/PedestalPyWrapper.cc                     | 126 ------------------------------------------
 CondCore/CalibPlugins/src/plugin.cc                                    |   8 +--
 CondCore/CondDB/BuildFile.xml                                          |   6 +-
 CondCore/CondDB/interface/Binary.h                                     |  14 -----
 CondCore/CondDB/interface/ConnectionPool.h                             |   5 +-
 CondCore/CondDB/interface/KeyList.h                                    |   3 +-
 CondCore/CondDB/interface/Serialization.h                              |  98 ++++++++++++++-------------------
 CondCore/CondDB/interface/Session.h                                    |  29 +---------
 CondCore/CondDB/src/Binary.cc                                          |  14 +----
 CondCore/CondDB/src/ConnectionPool.cc                                  |  34 ++----------
 CondCore/CondDB/src/KeyList.cc                                         |   1 -
 CondCore/CondDB/src/OraDbSchema.cc                                     | 407 --------------------------------------------------------------------------------------------------------------------------------------
 CondCore/CondDB/src/OraDbSchema.h                                      | 188 --------------------------------------------------------------
 CondCore/CondDB/src/Session.cc                                         |  65 ----------------------
 CondCore/CondDB/src/SessionImpl.cc                                     |  74 +++----------------------
 CondCore/CondDB/src/SessionImpl.h                                      |   7 +--
 CondCore/CondDB/test/testConditionDatabase_0.cpp                       |  57 +++++++------------
 CondCore/CondDB/test/testConditionDatabase_1.cpp                       |   2 +-
 CondCore/CondDB/test/testConditionDatabase_2.cpp                       |   2 +-
 CondCore/CondDB/test/testFrontier.cpp                                  |   2 +-
 CondCore/CondDB/test/testPayloadProxy.cpp                              |   2 +-
 CondCore/CondDB/test/testReadWritePayloads.cpp                         |   4 +-
 CondCore/DBCommon/plugins/BuildFile.xml                                |   1 -
 CondCore/DBCommon/plugins/FrontierProxy.cc                             |   5 --
 CondCore/DBOutputService/src/PoolDBOutputService.cc                    |   4 +-
 CondCore/DTPlugins/plugins/BuildFile.xml                               |  90 ------------------------------
 CondCore/DTPlugins/plugins/DTCCBConfigPyWrapper.cc                     |  60 --------------------
 CondCore/DTPlugins/plugins/DTDeadFlagPyWrapper.cc                      |  60 --------------------
 CondCore/DTPlugins/plugins/DTHVStatusPyWrapper.cc                      |  60 --------------------
 CondCore/DTPlugins/plugins/DTLVStatusPyWrapper.cc                      |  60 --------------------
 CondCore/DTPlugins/plugins/DTPerformancePyWrapper.cc                   |  60 --------------------
 CondCore/DTPlugins/plugins/DTRangeT0PyWrapper.cc                       |  60 --------------------
 CondCore/DTPlugins/plugins/DTReadOutMappingPyWrapper.cc                |  60 --------------------
 CondCore/DTPlugins/plugins/DTStatusFlagPyWrapper.cc                    |  60 --------------------
 CondCore/DTPlugins/plugins/DTT0PyWrapper.cc                            |  60 --------------------
 CondCore/DTPlugins/plugins/DTTPGParametersPyWrapper.cc                 |  60 --------------------
 CondCore/DTPlugins/src/plugin.cc                                       |   3 +-
 CondCore/EcalPlugins/plugins/BuildFile.xml                             | 222 -------------------------------------------------------------------------
 CondCore/EcalPlugins/plugins/ESGainPyWrapper.cc                        |  62 ---------------------
 CondCore/EcalPlugins/plugins/EcalADCToGeVConstantPyWrapper.cc          |  63 ---------------------
 CondCore/EcalPlugins/plugins/EcalAlignmentPyWrapper.cc                 |  77 --------------------------
 CondCore/EcalPlugins/plugins/EcalChannelStatusPyWrapper.cc             | 496 -------------------------------------------------------------------------------------------------------------------------------------------------------------------
 CondCore/EcalPlugins/plugins/EcalDAQTowerStatusPyWrapper.cc            | 290 -----------------------------------------------------------------------------------------------
 CondCore/EcalPlugins/plugins/EcalDCSTowerStatusPyWrapper.cc            | 333 -------------------------------------------------------------------------------------------------------------
 CondCore/EcalPlugins/plugins/EcalDQMChannelStatusPyWrapper.cc          | 380 -----------------------------------------------------------------------------------------------------------------------------
 CondCore/EcalPlugins/plugins/EcalDQMTowerStatusPyWrapper.cc            | 336 --------------------------------------------------------------------------------------------------------------
 CondCore/EcalPlugins/plugins/EcalFloatCondObjectContainerPyWrapper.cc  | 334 --------------------------------------------------------------------------------------------------------------
 CondCore/EcalPlugins/plugins/EcalFunParamsPyWrapper.cc                 |  73 ------------------------
 CondCore/EcalPlugins/plugins/EcalGainRatiosPyWrapper.cc                | 311 ------------------------------------------------------------------------------------------------------
 CondCore/EcalPlugins/plugins/EcalLaserAPDPNRatiosPyWrapper.cc          | 296 -------------------------------------------------------------------------------------------------
 CondCore/EcalPlugins/plugins/EcalLinearCorrectionsPyWrapper.cc         | 296 -------------------------------------------------------------------------------------------------
 CondCore/EcalPlugins/plugins/EcalMappingElectronicsPyWrapper.cc        |  60 --------------------
 CondCore/EcalPlugins/plugins/EcalPedestalsPyWrapper.cc                 | 413 ----------------------------------------------------------------------------------------------------------------------------------------
 CondCore/EcalPlugins/plugins/EcalPulseShapesPyWrapper.cc               | 352 --------------------------------------------------------------------------------------------------------------------
 CondCore/EcalPlugins/plugins/EcalPulseSymmCovariancesPyWrapper.cc      | 359 ----------------------------------------------------------------------------------------------------------------------
 CondCore/EcalPlugins/plugins/EcalPyWrapperFunctions.h                  | 110 ------------------------------------
 CondCore/EcalPlugins/plugins/EcalTBWeightsPyWrapper.cc                 |  66 ----------------------
 CondCore/EcalPlugins/plugins/EcalTPGCrystalStatusPyWrapper.cc          | 336 --------------------------------------------------------------------------------------------------------------
 CondCore/EcalPlugins/plugins/EcalTPGFineGrainEBIdMapPyWrapper.cc       |  45 ---------------
 CondCore/EcalPlugins/plugins/EcalTPGLinearizationConstPyWrapper.cc     | 311 ------------------------------------------------------------------------------------------------------
 CondCore/EcalPlugins/plugins/EcalTPGLutIdMapPyWrapper.cc               |  45 ---------------
 CondCore/EcalPlugins/plugins/EcalTPGPedestalsPyWrapper.cc              | 302 ---------------------------------------------------------------------------------------------------
 CondCore/EcalPlugins/plugins/EcalTPGPhysicsConstPyWrapper.cc           |  59 --------------------
 CondCore/EcalPlugins/plugins/EcalTPGStripStatusPyWrapper.cc            | 218 ------------------------------------------------------------------------
 CondCore/EcalPlugins/plugins/EcalTPGTowerStatusPyWrapper.cc            |  91 ------------------------------
 CondCore/EcalPlugins/plugins/EcalTPGWeightIdMapPyWrapper.cc            |  46 ----------------
 CondCore/EcalPlugins/plugins/EcalTimeBiasCorrectionsPyWrapper.cc       |  52 ------------------
 CondCore/EcalPlugins/plugins/EcalTimeOffsetConstantPyWrapper.cc        |  45 ---------------
 CondCore/EcalPlugins/plugins/EcalWeightXtalGroupsPyWrapper.cc          |  62 ---------------------
 CondCore/HIPlugins/plugins/BuildFile.xml                               |   9 ---
 CondCore/HIPlugins/plugins/CentralityTablePyWrapper.cc                 |  52 ------------------
 CondCore/HcalPlugins/plugins/BuildFile                                 | 178 -----------------------------------------------------------
 CondCore/HcalPlugins/plugins/BuildFile.xml                             | 132 --------------------------------------------
 CondCore/HcalPlugins/plugins/HcalChannelQualityPyWrapper.cc            | 209 ---------------------------------------------------------------------
 CondCore/HcalPlugins/plugins/HcalGainWidthsPyWrapper.cc                | 190 ---------------------------------------------------------------
 CondCore/HcalPlugins/plugins/HcalGainsPyWrapper.cc                     | 183 ------------------------------------------------------------
 CondCore/HcalPlugins/plugins/HcalLUTCorrsPyWrapper.cc                  | 184 -------------------------------------------------------------
 CondCore/HcalPlugins/plugins/HcalLutMetadataPyWrapper.cc               | 255 ------------------------------------------------------------------------------------
 CondCore/HcalPlugins/plugins/HcalPFCorrsPyWrapper.cc                   | 183 ------------------------------------------------------------
 CondCore/HcalPlugins/plugins/HcalPedestalsPyWrapper.cc                 | 201 ------------------------------------------------------------------
 CondCore/HcalPlugins/plugins/HcalQIEDataPyWrapper.cc                   | 313 -------------------------------------------------------------------------------------------------------
 CondCore/HcalPlugins/plugins/HcalRespCorrsPyWrapper.cc                 | 183 ------------------------------------------------------------
 CondCore/HcalPlugins/plugins/HcalTimeCorrsPyWrapper.cc                 | 184 -------------------------------------------------------------
 CondCore/HcalPlugins/plugins/HcalValidationCorrsPyWrapper.cc           | 184 -------------------------------------------------------------
 CondCore/HcalPlugins/plugins/HcalZSThresholdsPyWrapper.cc              | 184 -------------------------------------------------------------
 CondCore/IOVService/BuildFile.xml                                      |   6 --
 CondCore/IOVService/doc/IOVService.doc                                 |  46 ----------------
 CondCore/IOVService/interface/IOVEditor.h                              | 150 --------------------------------------------------
 CondCore/IOVService/interface/IOVNames.h                               |  43 ---------------
 CondCore/IOVService/interface/IOVProxy.h                               | 244 --------------------------------------------------------------------------------
 CondCore/IOVService/interface/IOVSchemaUtility.h                       |  33 -----------
 CondCore/IOVService/interface/KeyList.h                                |  75 -------------------------
 CondCore/IOVService/interface/KeyListProxy.h                           |  59 --------------------
 CondCore/IOVService/interface/PayloadProxy.h                           | 148 -------------------------------------------------
 CondCore/IOVService/src/IOVEditor.cc                                   | 550 ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 CondCore/IOVService/src/IOVProxy.cc                                    | 317 --------------------------------------------------------------------------------------------------------
 CondCore/IOVService/src/IOVSchemaUtility.cc                            |  80 ---------------------------
 CondCore/IOVService/src/KeyList.cc                                     |  32 -----------
 CondCore/IOVService/src/PayloadProxy.cc                                | 143 -----------------------------------------------
 CondCore/IOVService/src/T_EventSetup_KeyList.cc                        |   5 --
 CondCore/IOVService/test/BuildFile.xml                                 |  17 ------
 CondCore/IOVService/test/classes.h                                     |   1 -
 CondCore/IOVService/test/classes_def.xml                               |   3 -
 CondCore/IOVService/test/testIOVCopy.cc                                |  68 -----------------------
 CondCore/IOVService/test/testIOVDelete.cc                              |  51 -----------------
 CondCore/IOVService/test/testIOVEditor.cc                              | 205 --------------------------------------------------------------------
 CondCore/IOVService/test/testIOVIterator.cc                            | 211 ----------------------------------------------------------------------
 CondCore/IOVService/test/testIOVReplaceInterval.cc                     |  97 --------------------------------
 CondCore/IOVService/test/testPayloadObj.h                              |  10 ----
 CondCore/IOVService/test/testqueryPContainer.cc                        |  49 -----------------
 CondCore/IOVService/xml/CONDIOV_3.0.xml                                |  14 -----
 CondCore/IOVService/xml/IOV_basic_0.xml                                |  16 ------
 CondCore/PhysicsToolsPlugins/src/PerformanceRecordPlugin.cc            |   3 +-
 CondCore/PopCon/test/stubs/EffSourceHandler.cc                         |   3 +-
 CondCore/RPCPlugins/plugins/BuildFile.xml                              |  62 ---------------------
 CondCore/RPCPlugins/plugins/RPCObGasPyWrapper.cc                       | 581 -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 CondCore/RPCPlugins/plugins/RPCObImonPyWrapper.cc                      | 576 ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 CondCore/RPCPlugins/plugins/RPCObPVSSmapPyWrapper.cc                   |  61 --------------------
 CondCore/RPCPlugins/plugins/RPCObTempPyWrapper.cc                      | 558 ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 CondCore/RPCPlugins/plugins/RPCObVmonPyWrapper.cc                      | 580 ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 CondCore/RegressionTest/BuildFile.xml                                  |   6 --
 CondCore/RegressionTest/doc/Regression Testing Suite.pdf               | Bin 826597 -> 0 bytes
 CondCore/RegressionTest/doc/Regression testing documentation.pdf       | Bin 323502 -> 0 bytes
 CondCore/RegressionTest/doc/Regression testing documentation.txt       | 211 ----------------------------------------------------------------------
 CondCore/RegressionTest/interface/ArrayPayload.h                       |  49 -----------------
 CondCore/RegressionTest/interface/PrimitivePayload.h                   |  26 ---------
 CondCore/RegressionTest/interface/RegressionTestPayload.h              |  27 ---------
 CondCore/RegressionTest/interface/TestFunct.h                          |  49 -----------------
 CondCore/RegressionTest/python/common_db.py                            |  44 ---------------
 CondCore/RegressionTest/python/config.conf                             |  13 -----
 CondCore/RegressionTest/python/migrate.sql                             |  21 -------
 CondCore/RegressionTest/python/reference_db.py                         |  72 ------------------------
 CondCore/RegressionTest/python/results_db.py                           | 240 -------------------------------------------------------------------------------
 CondCore/RegressionTest/python/results_mgr.py                          |  75 -------------------------
 CondCore/RegressionTest/python/run_regression.py                       | 410 ---------------------------------------------------------------------------------------------------------------------------------------
 CondCore/RegressionTest/python/sequences.xml                           |  42 --------------
 CondCore/RegressionTest/python/setup_regression.py                     | 109 ------------------------------------
 CondCore/RegressionTest/python/webApp.py                               | 377 ----------------------------------------------------------------------------------------------------------------------------
 CondCore/RegressionTest/python/web_results_display.py                  | 145 ------------------------------------------------
 CondCore/RegressionTest/src/ArrayPayload.cc                            | 189 --------------------------------------------------------------
 CondCore/RegressionTest/src/PrimitivePayload.cc                        |  67 ----------------------
 CondCore/RegressionTest/src/RegressionTestPayload.cc                   |  58 -------------------
 CondCore/RegressionTest/src/TestFunct.cc                               | 270 -----------------------------------------------------------------------------------------
 CondCore/RegressionTest/test/BuildFile.xml                             |  19 -------
 CondCore/RegressionTest/test/classes.h                                 |  19 -------
 CondCore/RegressionTest/test/classes_def.xml                           |  16 ------
 CondCore/RegressionTest/test/setupDB.cc                                | 110 ------------------------------------
 CondCore/RegressionTest/test/testCompat.cc                             | 165 ------------------------------------------------------
 CondCore/RegressionTest/test/testExport.cc                             |  94 -------------------------------
 CondCore/RunInfoPlugins/plugins/BuildFile.xml                          |  45 ---------------
 CondCore/RunInfoPlugins/plugins/FillInfoPyWrapper.cc                   |  63 ---------------------
 CondCore/RunInfoPlugins/plugins/L1TriggerScalerPyWrapper.cc            | 137 ---------------------------------------------
 CondCore/RunInfoPlugins/plugins/RunInfoPyWrapper.cc                    |  87 -----------------------------
 CondCore/RunInfoPlugins/plugins/RunNumberPyWrapper.cc                  |  78 --------------------------
 CondCore/RunInfoPlugins/plugins/RunSummaryPyWrapper.cc                 |  94 -------------------------------
 CondCore/SiStripPlugins/plugins/AlCaRecoTriggerBitsPyWrapper.cc        |  71 ------------------------
 CondCore/SiStripPlugins/plugins/BuildFile.xml                          | 174 +--------------------------------------------------------
 CondCore/SiStripPlugins/plugins/Phase2TrackerCablingPyWrapper.cc       |  59 --------------------
 CondCore/SiStripPlugins/plugins/SiStripApvGainPyWrapper.cc             |  61 --------------------
 CondCore/SiStripPlugins/plugins/SiStripBackPlaneCorrectionPyWrapper.cc |  60 --------------------
 CondCore/SiStripPlugins/plugins/SiStripBadStripPyWrapper.cc            |  61 --------------------
 CondCore/SiStripPlugins/plugins/SiStripBaseDelayPyWrapper.cc           |  60 --------------------
 CondCore/SiStripPlugins/plugins/SiStripConfObjectPyWrapper.cc          |  61 --------------------
 CondCore/SiStripPlugins/plugins/SiStripDetVOffPyWrapper.cc             |  63 ---------------------
 CondCore/SiStripPlugins/plugins/SiStripFedCablingPyWrapper.cc          |  61 --------------------
 CondCore/SiStripPlugins/plugins/SiStripLatencyPyWrapper.cc             |  61 --------------------
 CondCore/SiStripPlugins/plugins/SiStripLorentzAnglePyWrapper.cc        |  60 --------------------
 CondCore/SiStripPlugins/plugins/SiStripNoisesPyWrapper.cc              |  61 --------------------
 CondCore/SiStripPlugins/plugins/SiStripPedestalsPyWrapper.cc           |  61 --------------------
 CondCore/SiStripPlugins/plugins/SiStripRunSummaryPyWrapper.cc          |  60 --------------------
 CondCore/SiStripPlugins/plugins/SiStripSummaryPyWrapper.cc             | 169 --------------------------------------------------------
 CondCore/SiStripPlugins/plugins/SiStripThresholdPyWrapper.cc           |  61 --------------------
 CondCore/Utilities/BuildFile.xml                                       |   3 -
 CondCore/Utilities/bin/BuildFile.xml                                   |  39 -------------
 CondCore/Utilities/bin/cmscond_2XML.cpp                                | 252 -----------------------------------------------------------------------------------
 CondCore/Utilities/bin/cmscond_authentication_manager.cpp              |   2 -
 CondCore/Utilities/bin/cmscond_delete_iov.cpp                          |  64 ---------------------
 CondCore/Utilities/bin/cmscond_duplicate_iov.cpp                       | 145 ------------------------------------------------
 CondCore/Utilities/bin/cmscond_edit_iov.cpp                            |  84 ----------------------------
 CondCore/Utilities/bin/cmscond_encode_db_file.cpp                      |  92 -------------------------------
 CondCore/Utilities/bin/cmscond_export_database.cpp                     | 284 ---------------------------------------------------------------------------------------------
 CondCore/Utilities/bin/cmscond_export_iov.cpp                          |   7 ---
 CondCore/Utilities/bin/cmscond_list_iov.cpp                            | 261 --------------------------------------------------------------------------------------
 CondCore/Utilities/bin/cmscond_load_iov.cpp                            | 108 ------------------------------------
 CondCore/Utilities/bin/cmscond_safe_duplicate.cpp                      | 217 -----------------------------------------------------------------------
 CondCore/Utilities/bin/cmscond_safe_import.cpp                         | 227 ---------------------------------------------------------------------------
 CondCore/Utilities/bin/cmscond_schema_iov.cpp                          |  60 --------------------
 CondCore/Utilities/bin/cmscond_schema_logdb.cpp                        |  52 ------------------
 CondCore/Utilities/bin/cmscond_schema_manager.cpp                      |  79 --------------------------
 CondCore/Utilities/bin/cmscond_truncate_iov.cpp                        |  73 ------------------------
 CondCore/Utilities/bin/conddb_copy_iov.cpp                             |  49 ++---------------
 CondCore/Utilities/bin/conddb_import.cpp                               |  32 +----------
 CondCore/Utilities/bin/conddb_migrate.cpp                              | 182 ------------------------------------------------------------
 CondCore/Utilities/bin/conddb_migrate_gt.cpp                           | 241 -------------------------------------------------------------------------------
 CondCore/Utilities/bin/conddb_test_gt_load.cpp                         |   3 +-
 CondCore/Utilities/bin/conddb_test_gt_perf.cpp                         |   6 +-
 CondCore/Utilities/bin/conddb_validate.cpp                             | 169 --------------------------------------------------------
 CondCore/Utilities/interface/CondBasicIter.h                           | 112 -------------------------------------
 CondCore/Utilities/interface/CondCachedIter.h                          |  16 ------
 CondCore/Utilities/interface/CondDBImport.h                            |   3 +-
 CondCore/Utilities/interface/CondDBTools.h                             |  20 +------
 CondCore/Utilities/interface/CondIter.h                                |  76 -------------------------
 CondCore/Utilities/interface/CondPyInterface.h                         | 102 ----------------------------------
 CondCore/Utilities/interface/ExportIOVUtilities.h                      |  14 -----
 CondCore/Utilities/interface/InspectorPythonWrapper.h                  |  54 ------------------
 CondCore/Utilities/interface/PayLoadInspector.h                        | 156 ----------------------------------------------------
 CondCore/Utilities/plugins/BuildFile.xml                               |   7 ---
 CondCore/Utilities/plugins/CondPyWrappers.cc                           | 265 ---------------------------------------------------------------------------------------
 CondCore/Utilities/python/cond2xml.py                                  |   4 --
 CondCore/Utilities/src/CondBasicIter.cc                                |  97 --------------------------------
 CondCore/Utilities/src/CondDBFetch.cc                                  |  17 +++---
 CondCore/Utilities/src/CondDBImport.cc                                 |  36 +-----------
 CondCore/Utilities/src/CondDBTools.cc                                  | 275 +++---------------------------------------------------------------------------------------
 CondCore/Utilities/src/CondPyInterface.cc                              | 272 -----------------------------------------------------------------------------------------
 CondCore/Utilities/src/ExportIOVUtilities.cc                           | 217 -----------------------------------------------------------------------
 CondCore/Utilities/src/classes.h                                       |   1 -
 CondCore/Utilities/src/classes_def.xml                                 |   3 +-
 CondCore/Utilities/test/testBasicPayload.cpp                           |   2 +-
 CondTools/L1Trigger/BuildFile.xml                                      |   2 -
 CondTools/L1Trigger/interface/DataManager.h                            |   1 -
 CondTools/L1Trigger/src/DataWriter.cc                                  |   2 -
 CondTools/Utilities/test/BuildFile.xml                                 |   2 -
 CondTools/Utilities/test/PlotIOV.cpp                                   | 195 ----------------------------------------------------------------
 CondTools/Utilities/test/classes.h                                     |  42 --------------
 CondTools/Utilities/test/classes_def.xml                               |  25 ---------
 CondTools/Utilities/test/testCondIter_Blob.cpp                         |  47 ----------------
 CondTools/Utilities/test/testCondIter_DirectDB.cpp                     | 132 --------------------------------------------
 CondTools/Utilities/test/testCondIter_LocalDB.cpp                      | 126 ------------------------------------------
 CondTools/Utilities/test/testCondIter_Performance.cpp                  | 405 -------------------------------------------------------------------------------------------------------------------------------------
 CondTools/Utilities/test/testCondIter_PerformanceDirect.cpp            | 371 --------------------------------------------------------------------------------------------------------------------------
 CondTools/Utilities/test/testCondIter_Plots.cpp                        | 354 --------------------------------------------------------------------------------------------------------------------
 CondTools/Utilities/test/testCondIter_Print.cpp                        |  82 ---------------------------
 CondTools/Utilities/test/testCondIter_PrintA.cpp                       |  42 --------------
 CondTools/Utilities/test/testCondIter_PrintB.cpp                       |  44 ---------------
 240 files changed, 133 insertions(+), 27521 deletions(-)
````

**Comment by diguida** [comment]
this does not agree with the github report: `240 changed files with 98 additions and 9,362 deletions.`

**Comment by diguida** [comment]
OK, It is github doing the wrong thing:
````
$ git checkout -b conddbV2-remove-V1-deps-1 ggovi/conddbV2-remove-V1-deps-1
$ git checkout from-CMSSW_8_0_X_2015-12-07-1100
$ git checkout -b from-CMSSW_8_0_X_2015-12-07-1100_conddbV2-remove-V1-deps-1
$ git merge conddbV2-remove-V1-deps-1
Merge made by the 'recursive' strategy.
...
 240 files changed, 133 insertions(+), 27521 deletions(-)
$ git diff --stat from-CMSSW_8_0_X_2015-12-07-1100
...
 240 files changed, 133 insertions(+), 27521 deletions(-)
````

**Comment by diguida** [comment]
+1

**Comment by ggovi** [comment]
+1

**Comment by ggovi** [comment]
@mulhearn mike - any objection?

**Comment by mulhearn** [comment]
+1

**Comment by mulhearn** [comment]
for the record, no objection!

**Comment by lgray** [comment]
@slava77 @bsunanda @ggovi It's either this PR or another in the the IB that this went in that broke the HGCal unit tests. I think it makes it clear that we need HGCal in standard run the matrix tests for 80X.

What breaks is a customization function for the RPCs which are needed for the modified geometry.
In particular, this function for correcting the RPC conditions appears to be outdated and broken:
https://github.com/cms-sw/cmssw/blob/CMSSW_8_0_X/SLHCUpgradeSimulations/Configuration/python/fixMissingUpgradeGTPayloads.py#L3-L18
Is there a more modern version of it? Ir is there something I must do to make condbv1 work here?

@boudoul Any way we could even put GEN-SIM in for HGCal in 80X? It even seems this is failing in Geant.

**Comment by mmusich** [comment]
@lgray what about migrating the tags to condDBv2 and maked them consumed from there? @pietverwilligen

**Comment by lgray** [comment]
I have no preference, so long as everything works.
I have no idea where this stuff should go since it's the muon community's responsibility.
Hopefully they can find someone to do it.

**Comment by mmusich** [comment]
@lgray I have a preference. Actually is very bad to discover this sort of customizations around.

**Comment by lgray** [comment]
@mmusich The SLHC release was a bit like the Wild West, there is some weird stuff going on in there. If it can be cleaned up in a reasonable way that is fine with me. Regardless of that, it must work again in some way.

**Comment by diguida** [comment]
@lgray @mmusich @pietverwilligen I propose the following:

1. remove the un-needed customisations in https://github.com/cms-sw/cmssw/blob/CMSSW_8_0_X/SLHCUpgradeSimulations/Configuration/python/fixMissingUpgradeGTPayloads.py 
1. move to CondDBv2 the necessary ones
1. I can produce a not-so-final PhaseII GT, but it would be good if you can summarise the conditions needed for your tests.

**Comment by diguida** [comment]
@lgray can you point us to the failing tests, please?

**Comment by mmusich** [comment]
#12821 should be something for starters

**Comment by boudoul** [comment]
hello @lgray and @mmusich : about the comment " Actually is very bad to discover this sort of customizations around." we should be a bit fair here... This has nothing to do with "Wild West" but if the phase2GT requested at that time would have been actually made, the customized would not have been added...

**Comment by mmusich** [comment]
@boudoul making custom Global Tags for the upgrade using the V1 backend was a nightmare... 
If we come up with a list of things we want to include in a dedicated Phase-II GT it's now straightforward to open a PhaseII scenario and populate the 80X queue.

**Pull request merged**
