### PR TITLE
Code cleanup in TauPOG repositories + a fix that falls back to gsfTracks for leading charged candidates for which kftTracks are not available

### PR DESCRIPTION
**Pull request by roger-wolf**
Dear all, 

this is a small PR which contains cleanup work in the TauPOG related repositories. I'm citing from a comment that @mbluj has made: 

"""
   * Fix in the RecoTauTag/RecoTau/plugins/PFTauTransverseImpactParameters.cc module allowing to use a gsfTrack associated to the tau leading charged candidate when it does not posses a KFTrack. It happens for candidates identified by PFlow as electrons (id==+-11). Usage of gsfTrack in a such case is a standard procedure in other tau modules, e.g. PV and SV producers.
   * Cleaning of unused code: usually removal of not needed includes, once removal of a handle of not used collection.

The changes will result in small changes in reconstructed impact parameters and output of MVAIso discriminants. 
"""

I've verified the change and during the standard quick validation procedures that we usually use for small changes like this I have observed the really small changes w.r.t. to before esp. in the MVA tau isolation. 

Cheers,
Roger

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
@roger-wolf : please fix the title with "tau" showing up somewhere, and mentioning the fix which allows using the gsfTrack associated to the tau leading charged candidate

The fix leads to some regression, as expected: can you add/link a few plots that show which are the expected changes?

**Comment by mbluj** [comment]
Hello,
On Mon, Dec 4, 2017 at 7:27 PM, perrotta <notifications@github.com> wrote:

> @roger-wolf <https://github.com/roger-wolf> : please fix the title with
> "tau" showing up somewhere, and mentioning the fix which allows using the
> gsfTrack associated to the tau leading charged candidate
>
> The fix leads to some regression, as expected: can you add/link a few
> plots that show which are the expected changes?
>
please find a few plots attached, showing small changes in distribution of
the transverse (dxy) and 3d (ip3d) impact parameters, and MVAIso score
obtained with original and modified code using genuine taus from the ZTT
RelVal sample. One can see small (almost marginal) differences between
results with the two codes. Note: the results were obtained with CMSSW
9_4_0 on which this fix originally based, but as the changes in the code
are small and 94X and current 10_0_X releases are very close each other we
do not think it makes any problem.
[image: Inline image 2][image: Inline image 3][image: Inline image 1]

**Comment by perrotta** [comment]
Thank you @roger-wolf and @mbluj : your plots confirm what is also visible in the outputs of the jenkins tests, that is the regression due to the fix is rather limited. It is good to have it, however, to conform with the other tau modules

**Comment by perrotta** [comment]
+1
- The update does what is declared: clean up of the unused code, and a fix in the PFTauTransverseImpactParameters.cc module which allows to use a gsfTrack associated to the tau leading charged candidate when it does not posses a KFTrack 
- Some small regression in the tau outputs is expected and observed because of the fix

**Comment by davidlange6** [comment]
+1

**Pull request merged**
