### PR TITLE
Fix Dependency violation in muon geometry builders

### PR DESCRIPTION
**Pull request by silviodonato**
#### PR description:

This PR solves the following dependency errors:
```
>> Checking dependency for Geometry/DTGeometryBuilder/plugins/DTGeometryValidate.cc
  ****ERROR: Dependency violation (direct): Geometry/DTGeometryBuilder/plugins/DTGeometryValidate.cc Fireworks/Core/interface/FWGeometry.h
  ****ERROR: Dependency violation (direct): Geometry/DTGeometryBuilder/plugins/DTGeometryValidate.cc Fireworks/Core/interface/FWRecoGeom.h
>> Done Checking dependency for Geometry/DTGeometryBuilder/plugins/DTGeometryValidate.cc
>> Checking dependency for Geometry/GEMGeometryBuilder/plugins/GEMGeometryValidate.cc
  ****ERROR: Dependency violation (direct): Geometry/GEMGeometryBuilder/plugins/GEMGeometryValidate.cc Fireworks/Core/interface/FWGeometry.h
  ****ERROR: Dependency violation (direct): Geometry/GEMGeometryBuilder/plugins/GEMGeometryValidate.cc Fireworks/Core/interface/FWRecoGeom.h
>> Done Checking dependency for Geometry/GEMGeometryBuilder/plugins/GEMGeometryValidate.cc
>> Checking dependency for Geometry/GEMGeometryBuilder/plugins/ME0GeometryValidate.cc
  ****ERROR: Dependency violation (direct): Geometry/GEMGeometryBuilder/plugins/ME0GeometryValidate.cc Fireworks/Core/interface/FWGeometry.h
  ****ERROR: Dependency violation (direct): Geometry/GEMGeometryBuilder/plugins/ME0GeometryValidate.cc Fireworks/Core/interface/FWRecoGeom.h
>> Done Checking dependency for Geometry/GEMGeometryBuilder/plugins/ME0GeometryValidate.cc
>> Checking dependency for Geometry/RPCGeometryBuilder/plugins/RPCGeometryValidate.cc
  ****ERROR: Dependency violation (direct): Geometry/RPCGeometryBuilder/plugins/RPCGeometryValidate.cc Fireworks/Core/interface/FWGeometry.h
  ****ERROR: Dependency violation (direct): Geometry/RPCGeometryBuilder/plugins/RPCGeometryValidate.cc Fireworks/Core/interface/FWRecoGeom.h
>> Done Checking dependency for Geometry/RPCGeometryBuilder/plugins/RPCGeometryValidate.cc
>> Checking dependency for L1Trigger/L1THGCalUtilities/plugins/ntuples/HGCalTriggerNtupleGen.cc

```

See https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc7_amd64_gcc820/CMSSW_11_2_X_2020-11-23-2300/depViolationLogs/Geometry/CSCGeometryBuilder

#### PR validation:

I tested `ReleaseDepsChecks.pl`and the errors disappeared after the fix .

### CODE REVIEW

**Comment by silviodonato** [comment]
@cms-sw/externals-l2 actually I'm not sure why we need `Fireworks/Core` to be outside `library`

**Comment by silviodonato** [comment]
please test

**Comment by makortel** [comment]
I'm a bit confused how exactly moving the `use` declaration from a `<library>` element to the "top level" of the `BuildFile.xml` helps to remove the dependence (my understanding is that all declared libraries will depend on the top level dependencies).

I'm also confused what exactly is being violated here. `Geometry` package depending on `Fireworks` package?

**Comment by silviodonato** [comment]
Thanks @makortel , the origin of the dependency is here https://github.com/cms-sw/cmssw/blob/727a6f30b8dfadea600f5f15431eec3cf1e717b2/Geometry/CSCGeometryBuilder/plugins/CSCGeometryValidate.cc#L27
It was introduced with #29111. @slomeo would it be possible to remove the dependency on `Fireworks` in `CSCGeometryValidate.cc`? 

> I'm a bit confused how exactly moving the use declaration from a <library> element to the "top level" of the BuildFile.xml helps to remove the dependence (my understanding is that all declared libraries will depend on the top level dependencies).

I'm confused as well, it might be just a bug of `ReleaseDepsChecks.pl`

**Pull request closed without merging**
