### PR TITLE
Avoid writing off beginning of arrays in RPCMonitorClient

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

The UBSAN build reported that an index of -2 was being used as an index into the arrays.

#### PR validation:

Code compiles.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by jfernan2** [comment]
6 variables are veing removed from RPC/EventInfo, @slezki @jeongsumin @andresib can you confirm this is fine from DQM RPC side?

**Comment by jeongsumin** [comment]
Hello, @jfernan2 , I'm sorry for check this late. There is no problem on the RPC DQM side.

And FYI, now I joined the company this January. So I cannot work for CMSSW from now on.
Instead of me, @Somhammer (klar.wind0425@gmail.com) will take over my work.

**Comment by jfernan2** [comment]
+1
Thanks @jeongsumin Good luck in industry.
I take note of @Somhammer in https://twiki.cern.ch/twiki/bin/viewauth/CMS/DQMContacts#RPC

**Comment by silviodonato** [comment]
+1

**Pull request merged**
