### PR TITLE
fix bpix efficiency 76x

### PR DESCRIPTION
**Pull request by fioriNTU**

### CODE REVIEW

**Comment by deguio** [comment]
please remove the obsolete lines instead of commenting them.
moreover I am not sure I understand the change in spacing for the equivalent PR in 74: #11468

**Comment by fioriNTU** [comment]
Hi Federico,
I would like to leave the commented lines since they should be 
reintroduced for the phase I upgrade.
The change in spacing in 74x is due to the fact that in that branch I 
have fixed also the indentation of the code, while I didn't fot 75x and 76x.

FF

Il 28/09/2015 11.58, Federico De Guio ha scritto:
>
> please remove the obsolete lines instead of commenting them.
> moreover I am not sure I understand the change in spacing for the 
> equivalent PR in 74: #11468 <https://github.com/cms-sw/cmssw/pull/11468>
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/cms-sw/cmssw/pull/11487#issuecomment-143697856>.
>



---
Questa e-mail è stata controllata per individuare virus con Avast antivirus.
https://www.avast.com/antivirus

**Comment by deguio** [comment]
+1
this is fine for me since we are talking about indentation, but normally one should try to keep consistency between branches as much as possible.

**Comment by deguio** [comment]
please test

**Comment by davidlange6** [comment]
@fioriNTU - could all of these commented code be removed? It will be there in the git history if you need to recover it someday

**Comment by fioriNTU** [comment]
Hi David,
incidentally I have been pinged to add some new monitor element in the 
same package, I was thinking to close these PRs, add the new code, apply 
the modifications that you and Federico asks (remove comments and 
correct indentation in 76x and 75x) and resubmit the PRs. Is this ok?

FF

Il 29/09/2015 07.40, David Lange ha scritto:
>
> @fioriNTU <https://github.com/fioriNTU> - could all of these commented 
> code be removed? It will be there in the git history if you need to 
> recover it someday
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/cms-sw/cmssw/pull/11487#issuecomment-143950973>.
>



---
Questa e-mail è stata controllata per individuare virus con Avast antivirus.
https://www.avast.com/antivirus

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
