### PR TITLE
Address residual code review for Timing PRs

### PR DESCRIPTION
**Pull request by lgray**
Follow up code review for #15710.

### CODE REVIEW

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by makortel** [comment]
What about the incorrect placement of 
```
eras.phase2_timing.toModify( quickTrackAssociatorByHits, ...)
eras.phase2_timing.toModify( tpClusterProducer, ...)
```
in `RecoVertex/Configuration/python/RecoVertex_cff.py`? (and I'm tempted to argue that both should be `phase2_tracker`)

**Comment by lgray** [comment]
@makortel Actually, since that modification gets used in a few places in different eras that are notionally independent of each other, I think it might be a good idea to write a centralize function to make the changes and then have each era call that function.

i.e. what if someone wants to run timing era without phase 2 tracker? or hgcal without phase2 tracker?

**Comment by makortel** [comment]
@lgray For timing era with phase0/phase1 tracker, why the default parameters of `quickTrackAssociatorByHits` and `tpClusterProducer` would not work?

(anyway my main "problem" is with the wrong placement of the era customizations, they should be moved to corresponding _cfi's; ok, `tpClusterProducer` needs a bit more since the _cfi is auto-generated)

**Comment by lgray** [comment]
Uff, you are right. Too early here. Easy enough to make the changes.

**Comment by lgray** [comment]
@makortel Where's the code that generates the tpClusterProducer _cfi ?

**Comment by makortel** [comment]
https://github.com/cms-sw/cmssw/blob/CMSSW_8_1_X/SimTracker/TrackerHitAssociation/plugins/ClusterTPAssociationProducer.cc#L73

**Comment by lgray** [comment]
Oh, fun, where would you prefer I put the era customization in that case?

On Thu, Sep 22, 2016 at 8:05 AM, Matti Kortelainen <notifications@github.com

**Comment by makortel** [comment]
By the way, if you're indeed making the `tpClusterProducer` customization with `phase2_tracker`, could you also remove the corresponding customizations from
https://github.com/cms-sw/cmssw/blob/CMSSW_8_1_X/SLHCUpgradeSimulations/Configuration/python/phase2TkFlat.py#L78
https://github.com/cms-sw/cmssw/blob/CMSSW_8_1_X/SLHCUpgradeSimulations/Configuration/python/phase2TkTilted.py#L77
since you're essentially doing the era migration of those parts? :)

FYI @ebrondol

**Comment by makortel** [comment]
@lgray Two options:

1. make `tpClusterProducer_cff` that imports the _cfi and makes the customizations, and migrate everything already importing the _cfi to import _cff
2. modify the .cc to generate e.g. `tpClusterProducerDefault_cfi`, and then make `tpClusterProducer_cfi.py` that imports the `..Default_cfi` and makes the customization; no migration of importers needed

(nowadays my personal preference is on 2 since it's simpler to do)

**Comment by makortel** [comment]
There is also an open issue on the matter #13326 :)

**Comment by lgray** [comment]
@makortel How about this? Let me know if it's OK and I'll start tests.

**Comment by makortel** [comment]
@lgray Looks perfect, thanks!

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by civanch** [comment]
+1

**Comment by slava77** [comment]
@lgray 
Looking at #15710 I see that most issues are addressed. 
The following are still not:
- https://github.com/cms-sw/cmssw/pull/15710#r78242269  in ``` DAClusterizerInZT::fill ```
- https://github.com/cms-sw/cmssw/pull/15710#r79246216 ```DAClusterizerInZT::update ``` copy-paste replica
- https://github.com/cms-sw/cmssw/pull/15710#r79246955 indentation in RecoVertex/VertexPrimitives/interface/VertexState.h and other files

**Comment by lgray** [comment]
DAClusterizerInZT::fill() is fixed since some time...
https://github.com/cms-sw/cmssw/blob/CMSSW_8_1_X/RecoVertex/PrimaryVertexProducer/src/DAClusterizerInZT.cc#L28

The rest I'll get to, thanks!

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by smuzaffar** [comment]
@slava77 , you can find the PR comparison results using new cms-bot changes https://github.com/cms-sw/cms-bot/pull/749 here https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_8_1_X_2016-09-26-1500+15938/16066/

**Comment by slava77** [comment]
On 9/27/16 12:24 AM, Malik Shahzad Muzaffar wrote:
> @slava77 <https://github.com/slava77> , you can find the PR comparison
> results using new cms-bot changes cms-sw/cms-bot#749
> <https://github.com/cms-sw/cms-bot/pull/749> here
> https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_8_1_X_2016-09-26-1500+15938/16066/
> 

Thank you.
This looks good.

I was mostly worrying that I missed something in the miniAOD monitoring
script.
The new directories and logs in them show up as I expected.

So, please go ahead and merge if you don't have any other concerns.

**Comment by lgray** [comment]
@civanch Could you resign?

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/15938 4053c58
- changes in the code are in line with the description 
- jenkins tests pass and comparisons with baseline show no differences
- local test of the timing workflow 22424.0 shows no differences either (comparisons include vertices with timing)

**Comment by lgray** [comment]
@civanch Please take a look and sign off, unless there is a problem!

**Comment by lgray** [comment]
OK, I'll rebase in a bit.

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/15938 8bc21be
- re-signoff after rebase, needed to adjust after #16001
- jenkins tests pass and comparisons show no differences, which include D3Timing wf 22424.0

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
