### PR TITLE
Fix error code on fallback file open error with test, 12_5_X backport

### PR DESCRIPTION
**Pull request by wddgit**
#### PR description:

Fix error code returned by cmsRun on a FallbackFileOpenError. There was a bug where it returns FileOpenError in the fallback case.

There is more discussion and more information related to this bug in issue https://github.com/cms-sw/cmssw/issues/42040. FYI @stlammel

#### PR validation:

Includes new unit test. New unit test and existing tests pass. This should only affect the behavior after an exception occurs. It should not affect the output of successful cmsRun processes.

Backport of https://github.com/cms-sw/cmssw/pull/42249.

### CODE REVIEW

**Comment by wddgit** [comment]
please test

**Comment by perrotta** [comment]
backport of https://github.com/cms-sw/cmssw/pull/42249

**Comment by makortel** [comment]
+core

**Comment by perrotta** [comment]
+1

**Pull request merged**
