### PR TITLE
Add DQM/TrackerRemapper package

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

The goal of this PR is to introduce a new package `DQM/TrackerRemapper` which is targeted to contain software meant to produce various visualizations of the Pixel and Strip Tracker,  scattered previously in other places (mainly in `CondCore/SiPixelPlugins`), mainly to avoid awkward dependencies from `CondCore`.
The new package contains the following interfaces:
   * `Phase1PixelMaps`: meant for separate Phase-1 Pixel Barrel and Forward Maps;
   * `Phase1PixelROCMaps`: meant for Phase-1 Pixel maps at the ROC-level;
   * `Phase1PixelSummaryMap:` meant for Summary Phase-1 Pixel maps; 
   * `SiStripTkMaps.h`: meant for Strip Tracker Maps

These classes are depend on `TH2Poly` objects built using the raw data available at https://github.com/cms-data/DQM-SiStripMonitorClient/tree/master/Geometry.
The new classes are then used in various places (mainly in the Pixel and Strip Payload Inspector packages), but also in some analyzers in `Alignment/OfflineValidation`.

In addition it contains two analyzers that are meant for re-mapping studies of existing DQM histograms: 
  * `SiPixelPhase1Analyzer`
  * `TrackerRemapper`

These are useful to produce more easily readable histograms from the DQM histograms available on the GUI.
We foresee this package to evolve to include also visualization aids for the Phase-2 Trackers.

#### PR validation:

This branch passes unit tests, as well as private tests.
An example plot obtainable with the following command is:

```bash
getPayloadData.py \
    --plugin pluginSiPixelLorentzAngle_PayloadInspector \
    --plot plot_SiPixelLorentzAngleFullPixelMap \
    --tag SiPixelLorentzAngle_v11_offline \
    --time_type Run \
    --iovs '{"start_iov": "324245", "end_iov": "324245"}' \
    --db Prod \
    --test ;
```
image

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Not a backport, no backport is needed.

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by smuzaffar** [comment]
assign dqm

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by jfernan2** [comment]
@mmusich  apart from some couts in the code, do you plan to enable these plots at some point in DQM sequences or just plan to run these classes in some stand alone way?
Thanks

**Comment by mmusich** [comment]
>  apart from some couts in the code

There are no `cout`s in the DQM code. The one that exist (in the CondDB code)  are protected by `ifdef`s and are meant to be used in debug mode.

>  do you plan to enable these plots at some point in DQM sequences or just plan to run these classes in some stand alone way?

They are meant to be used exclusively in standalone.

**Comment by ggovi** [comment]
+1

**Comment by jfernan2** [comment]
+1

**Comment by mmusich** [comment]
... and now this has a merge conflict....

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by jfernan2** [comment]
+1

**Comment by mmusich** [comment]
Sorry for the iterations. The last round of commits addresses violation of [cmssw coding rule 4.3](https://cms-sw.github.io/cms_coding_rules.html):
> Header ﬁles must not contain any implementation except for class templates and code to be inlined.

now it should be in the final version.

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by jfernan2** [comment]
+1

**Comment by ggovi** [comment]
+1

**Comment by mmusich** [comment]
@malbouis, @yuanchao, @christopheralanwest, @tlampen, @francescobrivio 
please review at earliest convenience, the changes in the AlCa package (`Alignment/OfflineValidation`) are somewhat trivial:
   * [re-ordering of includes in a build file](https://github.com/cms-sw/cmssw/pull/33280/files#diff-867d10c4dd4f0cc9a19445b3518ff9dad69d36e5cce9c484d9023c3ed8190233)
   * changes reflecting the change of naming of a public method from upper to lower case to follow coding rules [1](https://github.com/cms-sw/cmssw/pull/33280/files#diff-7a807025caafccc4416fbcdc4edd1c251fd09817c07043f4ccf1842f1db80d3e) and [2](https://github.com/cms-sw/cmssw/pull/33280/files#diff-e87a674ab49875bbebf3f965311e7e2e6f0f865e5885eeefb11f0817deca7f69)
   
Thank you

**Comment by christopheralanwest** [comment]
+alca

- Changes within AlCa domain are mainly technical

**Comment by silviodonato** [comment]
+1

**Pull request merged**
