### PR TITLE
Skim EXO HighMET

### PR DESCRIPTION
**Pull request by afrankenthal**
#### PR description:

This PR adds a common EXOHighMET skim that addresses the Run 3 needs of several EXO analyses. Specifically, it runs on top of the RAW+RECO data tier to allow analyzers to access detailed hit information (RECO) and to use the dataset for analysis R&D (RAW), such as ML and other reconstruction improvements.

We have realized that the needs of the EXO analyses differ in a non-negligible way from the existing JME HighMET skim [1]. The JME goals with such a skim are to study the behavior of high-MET tail and to develop and test different noise cleaning strategies. They have found for example that the RAW data tier is not so relevant for their use-case. They also don't need all the events collected for this purpose.

The proposed skim selects events on or near the plateau of the MET trigger efficiency, with MET pT > 200 GeV. There is currently no additional filter on the event content of the skim. The skim rate as tested on a file in the MET 2018A dataset is 2.7%, selecting 194 out of 7219 events.

This skim will be useful for several analyses, for example [2]:

- Delayed jets (EXO-19-001)
- Inelastic dark matter (EXO-20-010)
- Disappearing tracks (EXO-19-010)
- LLP hadronic decays in the ECAL
- Fractionally charged particles (EXO-19-006)
- Heavy Stable Charged Particles (HSCP)

And we believe others will also benefit from it.

[1] https://indico.cern.ch/event/1042443/contributions/4379421/attachments/2257197/3831154/HighMETSkim_JME_3June2021.pdf

[2] https://indico.cern.ch/event/1086811/contributions/4568933/attachments/2329715/3969638/EXO_skim_plans_run3_JME_20211018.pdf

#### PR validation:

This has been verified on CMSSW_12_4_0_pre3 with two test configs: `Configuration/Skimming/test/test_EXOHighMET_onQCD_cfg.py` and `Configuration/Skimming/test/test_EXOHighMET_onData_cfg.py`. Both in terms of number of events and file size, we get a roughly 2.7% rate on data. For completeness, we also test on a very high pT QCD MC sample, and here the skim rate is 12%.

### CODE REVIEW

**Comment by kskovpen** [comment]
please test

**Comment by kskovpen** [comment]
+pdmv

**Comment by perrotta** [comment]
The two (big) test configs only differ for the input dataset and the global tag.
To easen maintainability, wouldn't be better to have they merged into one single config file, allowing to switch between the two cases, real data and QCD MC?

**Comment by afrankenthal** [comment]
Hi @perrotta that makes sense. I've consolidated the two configs with a VarParsing option 'runOnData', defaulting to True since that's the one we really care about.

**Comment by kskovpen** [comment]
+pdmv

**Comment by perrotta** [comment]
+1

**Pull request merged**
