### PR TITLE
Added protection for invalid GhostTrackStates (92X)

### PR DESCRIPTION
**Pull request by ferencek**
Backport of #21120

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
+1
- This fix modifies the GhostTrackFitter, and therefore it may potentially affect also standard reco workflows
- In spite of that, I think it can be backported anyhow to 92X: the net result is that the job wouldn't crash because of segmentation violation in case of invalid states, while it will gently continue without updating, as it happens in the case of a valid state with a too large chi2 (or ndof=0)
- (The fact that no related crashes were ever reported, to my knowledge, in standard reco shows that the issue is not that frequent in it)

**Comment by perrotta** [comment]
I temporarily removed the "+1" simply because I was too fast: the comparisons were not produced yet...
At the same time, if anybody thinks it shouldn't be backported he/she can intervene in the thread

**Comment by perrotta** [comment]
+1
- (Repeating what in https://github.com/cms-sw/cmssw/pull/21178#issuecomment-342182578 after the arrival of the jenkins comparisons)
- This fix modifies the GhostTrackFitter, and therefore it may potentially affect also standard reco workflows
- In spite of that, I think it can be backported anyhow to 92X: the net result is that the job wouldn't crash because of segmentation violation in case of invalid states, while it will gently continue without updating, as it happens in the case of a valid state with a too large chi2 (or ndof=0)
- (The fact that no related crashes were ever reported, to my knowledge, in standard reco shows that the issue is not that frequent in it)

**Comment by ferencek** [comment]
As far as I am aware, all the problem reported so far involved running b 
tagging from MiniAOD. So most likely something in the way the track info 
is compressed in MiniAOD starts to trigger this rare crash while it 
appears it does occur in RECO/AOD for the same events where crashes 
occur in MiniAOD.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
