### PR TITLE
Adding HFsumET+HighPt and MB triggers to offline HLT DQM

### PR DESCRIPTION
**Pull request by zc11**
offline HLT DQM for MB trigger
offline HLT DQM for HFsumET+HighPt trigger
modification of trigger name for HM+HighPt trigger

### CODE REVIEW

**Comment by dmitrijus** [comment]
You need to provide an upstream PR (81x), before you can get this one merged.
Also, set the title to something more clear, for example "Adding HFsumET+HighPt triggers to offline HLT DQM"

**Comment by zc11** [comment]
The change is a part of 81x PR https://github.com/cms-sw/cmssw/pull/15920

**Comment by dmitrijus** [comment]
Thanks!

**Comment by dmitrijus** [comment]
+1

**Comment by zc11** [comment]
Change name of DQM trigger path due to change in HLT configuration.

**Comment by zc11** [comment]
Sorry for many changes to this PR. This should be the last one.......

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
