### PR TITLE
[HeaderCheck][RECO][ANA] Cleanup headers to avoid header inconsistency errors

### PR DESCRIPTION
**Pull request by smuzaffar**
Deleted unused headers from package/interface directory.

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by perrotta** [comment]
- The removed "CommonTools/CandAlgos/interface/NamedCandCombiner.h" is the only user of the "CommonTools/CandUtils/interface/NamedCandCombiner.h" class. As such, one could also remove
  - CommonTools/CandUtils/interface/NamedCandCombiner.h
  - CommonTools/CandUtils/interface/NamedCandCombinerBase.h
  - CommonTools/CandUtils/src/NamedCandCombiner.cc

Not clear whether they may still have any usage in analysis or private code, though...

- "CommonTools/ParticleFlow/interface/TopProjectors.h" and "CommonTools/ParticleFlow/interface/TopProjectorAlgo.h" look like being replaced by "CommonTools/ParticleFlow/interface/TopProjector.h" since 5_3 at least: ok to remove

- "CommonTools/UtilAlgos/interface/ChargeSelector.h" includes obsolete headers (since 5_3 at least) and it can be removed

- "CommonTools/UtilAlgos/interface/ObjectCounter.h" has no usage inside cmssw (since 5_3 at least), but I don't know how to verify whether it is still used in analysis or private code

- "PhysicsTools/SelectorUtils/interface/Expressions.h" has no usage inside cmssw (since 5_3 at least), but I don't know how to verify whether it is still used in analysis or private code

**Comment by fabiocos** [comment]
@santocch do you know whether there is any potential analysis use of the headers marked by @perrotta  ?

**Comment by perrotta** [comment]
@smuzaffar @santocch , since the 11_0 queue is now open, one could try to remove all those headers. quite likely all really unneeded, and possibly restore them later only in case of need in analysis code.

@smuzaffar by the way, do you plan to remove also the files in ```CommonTools/CandUtils``` (see first bullet in https://github.com/cms-sw/cmssw/pull/26663#issuecomment-491238831)?

**Comment by smuzaffar** [comment]
@perrotta for now I want to get headers checks clean so that we can mark PR tests failed if there are inconsistent headers that is why I was not touch other files.

May be we can do another round of headers cleanup for all those headers which are not included in any cc file.

**Comment by perrotta** [comment]
+1
- All removed headers seem obsolete enough to be safely removed in 11_0_X
- Jenkins tests pass

**Comment by fabiocos** [comment]
@santocch I move forward with the integration as no comment so far, in case please post notes

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Comment by santocch** [comment]
+1

**Pull request merged**
