### PR TITLE
[13_2_X] Online DQM fed client: use rawDataRepacker for HCAL FEDIntegrity Task in HI runs (backport of 43120)

### PR DESCRIPTION
**Pull request by syuvivida**
#### PR description:

As suggested by @mmusich, in the current heavy ion HLT menu, `Dataset_HIOnlineMonitor` still keeps the event product `FEDRawDataCollection_rawDataCollector_*_*`. This product includes non-zero suppressed Tracker FEDs and may be the cause why in some HI runs, DQM streamer files are way over the 2GB limit. Therefore, we tested the DQM client codes with a test streamer that does not contain `FEDRawDataCollection_rawDataCollector_*_*` and see if any DQM client crashes. We found the crash of this client `fed_dqm_sourceclient-live` could be easily fixed with the change of inputTag for `hcalFEDIntegrityTask.tagFEDs`.

With this update, the client `fed_dqm_sourceclient-live` could run on streamers that either include rawDataCollector or not. The PR does not rely on other PRs.

#### PR validation:

More information could be found in [PR 43120](https://github.com/cms-sw/cmssw/pull/43120)

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

backport of [43120](https://github.com/cms-sw/cmssw/pull/43120)
This PR could be applied on top of current existing online DQM release.

### CODE REVIEW

**Comment by tjavaid** [comment]
backport of #43120

**Comment by tjavaid** [comment]
please test

**Comment by tjavaid** [comment]
+1

**Comment by rappoccio** [comment]
+1

**Pull request merged**
