### PR TITLE
Simps to customphysics 7 1

### PR DESCRIPTION
**Pull request by lowette**
#### PR description:

This PR includes the code necessary to simulate SIMPs, implementing them as heavy neutrons with a configurable mass and as only interaction a clone of Geant's neutron's inelastic process.
This is very specific code for signal generation of the EXO-17-010 analysis. More information can be found in this presentation: https://indico.cern.ch/event/792362/contributions/3299414/attachments/1791002/2917852/190205_Lowette_SIMPSimulation.pdf

#### PR validation:

This code has been validated, among other things, by showing this SIMP simulation at 1GeV to give identical results to a simulation with a real Geant neutron replacing the SIMP. More information also in the talk mentioned above.

Note that this code has so far only been used to simulate a signal in 7_1_X, thus the initial PR  in this branch. Next, it will be forward-ported to 10_6_X.

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by fabiocos** [comment]
@lowette @civanch do we want to keep this code alive in the master branch? I understand that this is a special case, to store in an official repository an ad-hoc model used for a physics publication that is unclear whether will be used in the future.

**Comment by lowette** [comment]
I am preparing the same code to be integrated for 10_6_X too. There is a dangling to do with a change in GEANT which I need to figure out, and then test the workflow again; however, it's grant proposal and Moriond time, so that PR may take a little longer before it comes...

**Comment by fabiocos** [comment]
@lowette @civanch any news about this?

**Comment by civanch** [comment]
@lowette , what about making PR for the master?

**Comment by civanch** [comment]
@lowette , what about making PR for the master? We need finally integrate it but first we have to have master version. Have you any chance doing this?

**Comment by lowette** [comment]
This is on hold until we conclude on the last points in the analysis. Due to circumstances this has received only epsilon time in the past months...

**Comment by silviodonato** [comment]
hold

**Comment by silviodonato** [comment]
Hi @lowette , I would suggest to close this PR and open it again as soon as you have some news.

**Comment by silviodonato** [comment]
I'm closing the PRs with no activity in the last months. @lowette  please open it again as soon as you have news.

**Comment by silviodonato** [comment]
please close

**Comment by fabiocos** [comment]
@silviodonato please note that there is a long story behind this PR, which was originally meant to keep track within CMSSW of the implementation of an ad-hoc physics model used for a paper, under explicit request of the people involved in the paper scrutiny. I had kept on hold its integration pending a master version by @lowette to be approved by @civanch that never came. 

I believe that integrating this code in the release in which the production was made may stay as a legacy, but it would be meaningful to have a version of it in more modern releases.

@lowette @civanch any chance to get that? Anyway if this PR is just closed everything is lost, I would advice at a minimum to integrate it in that case.

**Comment by fabiocos** [comment]
reopened in agreement with @silviodonato , I will check a possible forward port to master.
@civanch any comment about this?

**Comment by fabiocos** [comment]
@smuzaffar curious, do you understand why did cmsbuild close it again?

**Comment by smuzaffar** [comment]
because of https://github.com/cms-sw/cmssw/pull/26094#issuecomment-572058651 comment :-)

**Comment by smuzaffar** [comment]
can you try 'reopen' comment?

**Comment by smuzaffar** [comment]
@silviodonato , can you please try 'reopen' comment to reopen this PR?

**Comment by silviodonato** [comment]
@smuzaffar , it works, thanks!

**Comment by smuzaffar** [comment]
@silviodonato, because of https://github.com/cms-sw/cmssw/pull/26094#issuecomment-572058651 comment, cms-bot thinks that this PR should be closed, that is why it is closing it. Please add a new comment 'reopen' to instruct bot keep it open

**Comment by silviodonato** [comment]
reopen

**Comment by smuzaffar** [comment]
looks like bot did not react to the comment, I am looking it to it.

**Comment by civanch** [comment]
I will have a look how this can be forward-ported. This is not straightforward - few classes should be changed according to modifications (including MT related) accumulated since 7_1.

**Comment by silviodonato** [comment]
unhold

**Comment by silviodonato** [comment]
code-checks

**Comment by silviodonato** [comment]
please test

**Comment by silviodonato** [comment]
+1

**Pull request merged**
