### PR TITLE
Change Sonic to use ExternalFailure exception

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

Using the new exception type will make cmsRun return a more meaningful return value (which is what most code which launch cmsRun use to classify failures).

#### PR validation:

Code compiles.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
Comparison differences are related to https://github.com/cms-sw/cmssw/issues/39803

**Comment by makortel** [comment]
+heterogeneous

**Comment by makortel** [comment]
@cms-sw/orp-l2 Could this PR be merged? Thanks!

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
