### PR TITLE
Handling of FOG special HLT menus [140X]

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
#### PR description:

Handling of FOG special HLT menus [140X]

https://its.cern.ch/jira/browse/CMSHLT-3092 : Completion of the offline "Special" table and lists of paths for individual special menus

See also discussion here:
https://docs.google.com/document/d/1XxsH3qXt7ZO4LIuwQg-I-Lp5rekkWsxSEG_Mwv1nh0Q/edit#heading=h.p0nxi1qdtn0t

#### PR validation:

Executing scripts

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport of #44311 to 2024 data taking release

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
backport of https://github.com/cms-sw/cmssw/pull/44311

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by rappoccio** [comment]
+1

**Pull request merged**
