### PR TITLE
Support HLT tracks in alignment validation

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

It is in the plans to start using `hltMergedTracks` from the `SteamHLTMonitor` PD in the tracker alignment procedure in order to minimize the drift between the derived alignment correction / validations and their actual usage in production (at the HLT).
This PR proposes a couple of minimal fixes in order to be able to run the standard setup.
There are two commits:
   *  7e521a44196748b3992e44a4ebd6827a31181510 supports the `hltMergedTracks` collection in the common track selection and refitting sequence
   * 158027538da53cbef4db0c3d750aa283384a5bd8 supports the `SiStripMatchedRecHit2D` and `ProjectedSiStripRecHit2D` collections in `TrackerTrackHitFilter`. Encountering hits from either of these two collections was leading to a runtime exception of the type:
   
```   
----- Begin Fatal Exception 05-Jul-2023 19:33:49 CEST-----------------------
An exception of category 'Unknown RecHit Type' occurred while
   [0] Processing  Event run: 370102 lumi: 668 event: 1557577232 stream: 0
   [1] Running path 'p'
   [2] Calling method for module TrackerTrackHitFilter/'TrackerTrackHitFilter'
   
Exception Message:
RecHit of type 22SiStripMatchedRecHit2D not supported. (use c++filt to demangle the name)
----- End Fatal Exception -------------------------------------------------
```
These two collections (as the previously stated in the removed comment) did not happen anymore since CMSSW > 2_0_X because of hit splitting in stereo modules in offline reconstruction, but in HLT tracking stereo hit splitting is not performed.
In order to cope with the  `SiStripMatchedRecHit2D`, the cut on the S/N is performed by taking the average of the stereo and mono hits.

#### PR validation:

Tested the minimal configuration provided by @henriettepetersen (available [here](https://gist.github.com/mmusich/ff4d8ba8d9b852e67ffad514dc026cbf)).

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Not a backport. Not clear at this point if a backport for 2023 to 13.0.X is useful or not.

### CODE REVIEW

**Comment by mmusich** [comment]
test parameters:
   * addpkg = Alignment/OfflineValidation
   * workflows = 1001.2, 1001.3

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by tvami** [comment]
+alca
 * tests pass
 * trusting private alignment validation

**Comment by lakshmip2609** [comment]
The tracker alignment team has performed internal validation using `hltMergedTracks` from the `SteamHLTMonitor` PD after implementing the fix proposed in this PR. The validation ran successfully, and the obtained results look reasonable. We would like to leave here a link to a presentation summarising this study to serve as a future reference: https://indico.cern.ch/event/1271491/#16-validation-of-conditions-wi

**Comment by mmusich** [comment]
@cms-sw/reconstruction-l2 ping

**Comment by clacaputo** [comment]
+1

**Comment by rappoccio** [comment]
+1

**Comment by mmusich** [comment]
@cms-sw/orp-l2, if I want this to be backported to 13.0.x can you clarify now how many and which backports do we need? All cycles in between (13.2.x, 13.1x, 13.0.x)?

**Comment by perrotta** [comment]
> @cms-sw/orp-l2, if I want this to be backported to 13.0.x can you clarify now how many and which backports do we need? All cycles in between (13.2.x, 13.1x, 13.0.x)?

@mmusich yes having the same fixes/updates in all intermediate cycles is the preferred options, unless there are reasons to avoid any of them

**Pull request merged**
