### PR TITLE
Calibration, linking, resolution parameterization for PF for HGCal

### PR DESCRIPTION
**Pull request by sethzenz**
improvements to cluster calibration, linking, and resolution parameterization in PF for HGCal @pfs @lgray @vandreev11

### CODE REVIEW

**Comment by mark-grimes** [comment]
@lgray (and @vandreev11), is this part of the changes you were talking about in the upgrade reco meeting this morning?

**Comment by vandreev11** [comment]
@mark-grimes, @lgray, @pfs
yes, this should be included in the coming release/relvals production.

**Comment by lgray** [comment]
@mark-grimes just to clarify here, we are waiting first on a zero pileup reprocessing at the lpc to check that everything is ok. We will post plots here with the outcome.

**Comment by lgray** [comment]
This PR should bring improved event content, increasing the charged hadron fraction and reducing the photon fraction.

**Comment by mark-grimes** [comment]
please test

**Comment by mark-grimes** [comment]
merge

**Pull request merged**
