### PR TITLE
MTD geometry: add test and unit test to probe the BTL pixel structure provided by RectanbgularMTDTopology

### PR DESCRIPTION
**Pull request by fabiocos**
#### PR description:

This PR adds a test to ```Geometry/MTDGeometryBuilder``` to compare the ideal positions of BTL crystals with the reconstructed positions through ```MTDGeometry``` and ```RectangularMTDTopology```. In case of anomalous differences (a tolerance is defined in the test) a message is written in the output of the unit test, causing it to fail.

A minor code cleaning is added in the BTL digitization as well, no change is implied.

#### PR validation:

The test runs, provide the expected output, and the standard unit test succeeds with a tolerance defined at 0.5 microns for the difference between ideal and reconstructed positions (differences are below 250 nm).

### CODE REVIEW

**Comment by fabiocos** [comment]
please test

**Comment by cvuosalo** [comment]
+1

**Comment by fabiocos** [comment]
@silviodonato @qliphy I see the clang-tidy warnings, as they are unrelated to the development in this PR, which affects ```BTLDeviceSim.cc``` in a marginal way, I suggest to move that fix into a separate, dedicated PR

**Comment by fabiocos** [comment]
actually I see that @makortel is already handling the migration if SimFatTiming in his #31697

**Comment by civanch** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

By the way, I just see that we mix on using DD4Hep and DD4hep across CMSSW. I assume the right one is DD4hep with small g. Ones with DD4Hep are, e.g.,
- MagneticField/Engine/test/runTest.sh
- Geometry/DTGeometryBuilder/src/DTGeometryBuilderFromDD4Hep.cc
Maybe something to clean up in future? @silviodonato @qliphy @cvuosalo @civanch. What do you think? Should we open an issue to follow up later?

**Comment by silviodonato** [comment]
+1
@srimanob good catch. Yes, please open an issue to track it

**Pull request merged**
