### PR TITLE
[DD4hep] Bugfix for DDFilteredView::navPos

### PR DESCRIPTION
**Pull request by ianna**
#### PR description:

* Check if there is an iterator

@fabiocos - FYI

Hopefully it fixes the problem you've reported.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by fabiocos** [comment]
please test

@ianna thanks! I'll do a test to whether that is enough to prevent the crashes I've observed

**Comment by cvuosalo** [comment]
With this change, the caller needs to remember to check whether the returned `nav_type` vector is empty. How about an interface like:
```
bool DDFilteredView::navPos(DDFilteredView::nav_type &pos) const;
```
`navPos` would return false if `pos` ends up empty. This interface would remind the user that `pos` could be empty. I've just been fixing crashing bugs where developers assumed incorrectly that vectors were not empty, so I think it is good to make the interface remind the user of this danger.

**Comment by fabiocos** [comment]
@ianna thanks, with this fix if I print ```navPos().size()``` in https://cmssdt.cern.ch/lxr/source/DetectorDescription/DDCMS/plugins/test/DDTestFilteredView.cc#0046  for the MTD geometry I do not get any more a crash. 

Concerning the comment of @cvuosalo I am not sure about the general sue of this method. In my case I was mostly checking its size, so this should be safe against your new implementation. Of course the real issue is why this vector could be empty, and if there are cases in the code where this is unexpected but it happens anyway

**Comment by ianna** [comment]
> With this change, the caller needs to remember to check whether the returned `nav_type` vector is empty. How about an interface like:
> 
> ```
> bool DDFilteredView::navPos(DDFilteredView::nav_type &pos) const;
> ```
> 
> `navPos` would return false if `pos` ends up empty. This interface would remind the user that `pos` could be empty. I've just been fixing crashing bugs where developers assumed incorrectly that vectors were not empty, so I think it is good to make the interface remind the user of this danger.

I do not see an advantage in creating an additional variable to check a standard container state. In fact, I'd be promoting a range-based `for` loop iteration instead of using an `operator[]` where no bounds checking is performed. Since C++11 there is a mandatory elision of copy and move operations, so there is no advantage in passing a reference here either.

IMHO, current version:
```c++
auto myPos = navPos();
for(auto const& it : myPos) {
  check(it);
}
```
is cleaner then proposed:
```c++
DDFilteredView::nav_type myPos;
if(navPos(myPos)) {
  for(int i = 0; i < myPos.size(); i++) {
    check(navPos[i]);
  }
}

**Comment by cvuosalo** [comment]
+1

**Comment by cvuosalo** [comment]
@ianna OK, the interface is fine as-is. The next time `DDFilteredView.h` is edited, it would be good to mention in the comment for `navPos` that it could return an empty vector, just to remind the user not to blindly dereference it.

**Comment by silviodonato** [comment]
+1

**Pull request merged**
