### PR TITLE
[101X][GT updates] ECAL threshold, PF corrections, GEM geometry, HCAL conditions for 2018

### PR DESCRIPTION
**Pull request by lpernie**
# Summary of changes in Global Tags

## RunII data

   * **RunII HLTHI processing** : [101X_dataRun2_HLTHI_frozen_v7](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_dataRun2_HLTHI_frozen_v7) as [101X_dataRun2_HLTHI_frozen_v6](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_dataRun2_HLTHI_frozen_v6) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/101X_dataRun2_HLTHI_frozen_v7/101X_dataRun2_HLTHI_frozen_v6):
      * Ecal PFRecHit Thresholds 
      * PFClusterCor (ecal and jetmet)

   * **RunII HLT relval processing** : [101X_dataRun2_HLT_relval_v7](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_dataRun2_HLT_relval_v7) as [101X_dataRun2_HLT_relval_v6](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_dataRun2_HLT_relval_v6) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/101X_dataRun2_HLT_relval_v7/101X_dataRun2_HLT_relval_v6):
      * Ecal PFRecHit Thresholds 
      * PFClusterCor (ecal)
      * L1Menu_Collisions2018_v0_0_1

   * **RunII Offline processing** : [101X_dataRun2_v8](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_dataRun2_v8) as [101X_dataRun2_v7](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_dataRun2_v7) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/101X_dataRun2_v8/101X_dataRun2_v7):
      * Ecal PFRecHit Thresholds
      * PFClusterCor (ecal)
      * Hcal offline RespCorrs, RecoParams
      * PFCalibration_v9_mc

   * **RunII Offline relval processing** : [101X_dataRun2_relval_v8](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_dataRun2_relval_v8) as [101X_dataRun2_relval_v7](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_dataRun2_relval_v7) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/101X_dataRun2_relval_v8/101X_dataRun2_relval_v7):
      * Ecal PFRecHit Thresholds
      * Hcal offline RespCorrs, RecoParams
      * PFClusterCor (ecal)
      * PFCalibration_v9_mc
      * L1Menu_Collisions2018_v0_0_1

   * **RunII Prompt processing** : [101X_dataRun2_PromptLike_v8](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_dataRun2_PromptLike_v8) as [101X_dataRun2_PromptLike_v7](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_dataRun2_PromptLike_v7) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/101X_dataRun2_PromptLike_v8/101X_dataRun2_PromptLike_v7):
      * Ecal PFRecHit Thresholds
      * ecalPFClusterCor2018V1_E
      * L1Menu_Collisions2018_v0_0_1
      * PFCalibration_v9_mc

   * **RunI HLT processing** : [101X_dataRun2_HLT_frozen_v6](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_dataRun2_HLT_frozen_v6) as [101X_dataRun2_HLT_frozen_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_dataRun2_HLT_frozen_v5) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/101X_dataRun2_HLT_frozen_v6/101X_dataRun2_HLT_frozen_v5):
      * Ecal PFRecHit Thresholds

## RunI simulation

   * **RunI Heavy Ions scenario** : [101X_mcRun1_HeavyIon_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_mcRun1_HeavyIon_v4) as [101X_mcRun1_HeavyIon_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_mcRun1_HeavyIon_v2) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/101X_mcRun1_HeavyIon_v4/101X_mcRun1_HeavyIon_v2):
      * PF Calibration (ecal, jetmet)
      * Ecal PFRecHit Thresholds

   * **RunI Ideal scenario** : [101X_mcRun1_design_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_mcRun1_design_v4) as [101X_mcRun1_design_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_mcRun1_design_v2) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/101X_mcRun1_design_v4/101X_mcRun1_design_v2):
      * PF Calibration (ecal, jetmet) 
      * PFCalibration (jet met)

   * **RunI Proton-Lead scenario** : [101X_mcRun1_pA_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_mcRun1_pA_v4) as [101X_mcRun1_pA_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_mcRun1_pA_v2) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/101X_mcRun1_pA_v4/101X_mcRun1_pA_v2):
      * EcalPFRecHitThresholds_2018_v1_mc 
      * PF Calibration (ecal, jetmet)

   * **RunI Realistic scenario** : [101X_mcRun1_realistic_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_mcRun1_realistic_v4) as [101X_mcRun1_realistic_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_mcRun1_realistic_v2) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/101X_mcRun1_realistic_v4/101X_mcRun1_realistic_v2):
      * EcalPFRecHitThresholds_2018_v1_mc
      * PF Calibration (ecal, jetmet)

## RunII simulation

   * **RunII Asymptotic scenario** : [101X_mcRun2_asymptotic_v6](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_mcRun2_asymptotic_v6) as [101X_mcRun2_asymptotic_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_mcRun2_asymptotic_v4) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/101X_mcRun2_asymptotic_v6/101X_mcRun2_asymptotic_v4):
      * EcalPFRecHitThresholds
      * PF Calibration (ecal, jetmet)

   * **RunII CRAFT scenario** : [101X_mcRun2cosmics_startup_deco_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_mcRun2cosmics_startup_deco_v5) as [101X_mcRun2cosmics_startup_deco_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_mcRun2cosmics_startup_deco_v3) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/101X_mcRun2cosmics_startup_deco_v5/101X_mcRun2cosmics_startup_deco_v3):
      * EcalPFRecHitThresholds
      * PF Calibration (ecal, jetmet)

   * **RunII Heavy Ions scenario** : [101X_mcRun2_HeavyIon_v6](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_mcRun2_HeavyIon_v6) as [101X_mcRun2_HeavyIon_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_mcRun2_HeavyIon_v4) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/101X_mcRun2_HeavyIon_v6/101X_mcRun2_HeavyIon_v4):
      * EcalPFRecHitThresholds
      * PF Calibration (ecal, jetmet)

   * **RunII Ideal scenario** : [101X_mcRun2_design_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_mcRun2_design_v5) as [101X_mcRun2_design_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_mcRun2_design_v3) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/101X_mcRun2_design_v5/101X_mcRun2_design_v3):
      * EcalPFRecHitThresholds
      * PF Calibration (ecal, jetmet)

   * **RunII Proton-Lead scenario** : [101X_mcRun2_pA_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_mcRun2_pA_v5) as [101X_mcRun2_pA_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_mcRun2_pA_v3) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/101X_mcRun2_pA_v5/101X_mcRun2_pA_v3):
      * EcalPFRecHitThresholds
      * PF Calibration (ecal, jetmet)

   * **RunII Startup scenario** : [101X_mcRun2_startup_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_mcRun2_startup_v5) as [101X_mcRun2_startup_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_mcRun2_startup_v3) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/101X_mcRun2_startup_v5/101X_mcRun2_startup_v3):
      * EcalPFRecHitThresholds
      * PF Calibration (ecal, jetmet)

## Upgrade
   * **LS2 realistic scenario** : [101X_postLS2_realistic_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_postLS2_realistic_v5) as [101X_postLS2_realistic_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_postLS2_realistic_v4) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/101X_postLS2_realistic_v5/101X_postLS2_realistic_v4):
      * CSC Chamber Time Corrections
      * L1Menu_Collisions2018_v0_0_1
      * GEM Geometry
      * PF Correction (ECAL)
      * EcalPFRecHitThresholds
      * PFCalibration (jet met)

   * **LS2 ideal scenario** : [101X_postLS2_design_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_postLS2_design_v5) as [101X_postLS2_design_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_postLS2_design_v4) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/101X_postLS2_design_v5/101X_postLS2_design_v4):
      * CSC Chamber Time Corrections
      * L1Menu_Collisions2018_v0_0_1
      * GEM Geometry
      * PF Correction (ECAL)
      * EcalPFRecHitThresholds
      * PFCalibration (jet met)

   * **PhaseII realistic scenario** : [101X_upgrade2023_realistic_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_upgrade2023_realistic_v5) as [101X_upgrade2023_realistic_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_upgrade2023_realistic_v4) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/101X_upgrade2023_realistic_v5/101X_upgrade2023_realistic_v4):
      * CSC Chamber Time Corrections
      * L1Menu_Collisions2018_v0_0_1
      * GEM Geometry
      * PF Correction (ECAL)
      * EcalPFRecHitThresholds
      * PFCalibration (jet met)

   * **PhaseI 2018 cosmics scenario** : [101X_upgrade2018cosmics_realistic_deco_v8](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_upgrade2018cosmics_realistic_deco_v8) as [101X_upgrade2018cosmics_realistic_deco_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_upgrade2018cosmics_realistic_deco_v5) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/101X_upgrade2018cosmics_realistic_deco_v8/101X_upgrade2018cosmics_realistic_deco_v5):
      * CSC Chamber Time Corrections
      * L1Menu_Collisions2018_v0_0_1
      * GEM Geometry
      * PF Correction (ECAL)
      * EcalPFRecHitThresholds
      * PFCalibration (jet met)
      * Hcal QIEData, SiPMParam, Gains, Pedestal, Widths (effective and not)

   * **PhaseI 2018 design scenario** : [101X_upgrade2018_design_v8](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_upgrade2018_design_v8) as [101X_upgrade2018_design_v7](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_upgrade2018_design_v7) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/101X_upgrade2018_design_v8/101X_upgrade2018_design_v7):
      * CSC Chamber Time Corrections
      * L1Menu_Collisions2018_v0_0_1
      * GEM Geometry
      * PF Correction (ECAL)
      * EcalPFRecHitThresholds
      * PFCalibration (jet met)
      * Hcal QIEData, SiPMParam, Gains, Pedestal, Widths (effective and not)

   * **PhaseI 2018 realistic scenario** : [101X_upgrade2018_realistic_v7](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_upgrade2018_realistic_v7) as [101X_upgrade2018_realistic_v6](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_upgrade2018_realistic_v6) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/101X_upgrade2018_realistic_v7/101X_upgrade2018_realistic_v6):
      * CSC Chamber Time Corrections
      * L1Menu_Collisions2018_v0_0_1
      * GEM Geometry
      * PF Correction (ECAL)
      * EcalPFRecHitThresholds
      * PFCalibration (jet met)
      * Hcal QIEData, SiPMParam, Gains, Pedestal, Widths (effective and not)

## 2017_MC

   * **PhaseI 2017 cosmics peak scenario** : [101X_mc2017cosmics_realistic_peak_v7](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_mc2017cosmics_realistic_peak_v7) as [101X_mc2017cosmics_realistic_peak_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_mc2017cosmics_realistic_peak_v5) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/101X_mc2017cosmics_realistic_peak_v7/101X_mc2017cosmics_realistic_peak_v5):
      * PF Calibration (ecal, jetmet)
      * EcalPFRecHitThresholds

   * **PhaseI 2017 cosmics scenario** : [101X_mc2017cosmics_realistic_deco_v7](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_mc2017cosmics_realistic_deco_v7) as [101X_mc2017cosmics_realistic_deco_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_mc2017cosmics_realistic_deco_v5) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/101X_mc2017cosmics_realistic_deco_v7/101X_mc2017cosmics_realistic_deco_v5):
      * PF Calibration (ecal, jetmet)
      * EcalPFRecHitThresholds

   * **PhaseI 2017 design scenario** : [101X_mc2017_design_IdealBS_v7](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_mc2017_design_IdealBS_v7) as [101X_mc2017_design_IdealBS_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_mc2017_design_IdealBS_v5) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/101X_mc2017_design_IdealBS_v7/101X_mc2017_design_IdealBS_v5):
      * PF Calibration (ecal, jetmet)
      * EcalPFRecHitThresholds

   * **PhaseI 2017 realistic scenario** : [101X_mc2017_realistic_v7](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_mc2017_realistic_v7) as [101X_mc2017_realistic_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_mc2017_realistic_v5) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/101X_mc2017_realistic_v7/101X_mc2017_realistic_v5):
      * PF Calibration (ecal, jetmet)
      * EcalPFRecHitThresholds

### CODE REVIEW

**Comment by lpernie** [comment]
backport of 22833

**Comment by lpernie** [comment]
please test

**Comment by arunhep** [comment]
@cmsbuild please test

**Comment by arunhep** [comment]
please test

**Comment by arunhep** [comment]
errors were not related to the PR

**Comment by lpernie** [comment]
please test

**Comment by lpernie** [comment]
please test

**Comment by lpernie** [comment]
Hi @slava77 , my understanding from the discussion at PPD is that thresholds should be changed everywhere, run1 included. Maybe I mis-understood and this do not apply to Run1?

**Comment by slava77** [comment]
> Hi @slava77 , my understanding from the discussion at PPD is that thresholds should be changed everywhere, run1 included. Maybe I mis-understood and this do not apply to Run1?

@amassiro @crovelli 
please comment about increasing thresholds in run-1.
I thought that the eventual plan was to keep the thresholds at a reasonably fixed n*sigma value.

**Comment by arunhep** [comment]
@slava77
if we want to apply the same PF calibrations also for run1 and run2 until 2017 then we have to propagate back the threshold changes. Both JetMET and EGM is reluctant to introduce IOV based tags for data to separate the pf calibrations between different periods.
for JetMET the limitation comes from the code as the payload and code goes hand in hand.

**Comment by slava77** [comment]
On 4/5/18 6:29 PM, Arun Kumar wrote:
> @slava77 <https://github.com/slava77>
> if we want to apply the same PF calibrations also for run1 and run2
> until 2017 then we have to propagate back the threshold changes. Both
> JetMET and EGM is reluctant to introduce IOV based tags for data to
> separate the pf calibrations between different periods.
> for JetMET the limitation comes from the code as the payload and code
> goes hand in hand.

OK, perhaps the benefit of a more uniform response across the board
outweighs the benefits of better performance for the past data taking.

**Comment by Sam-Harper** [comment]
>POGs should confirm, if no unclustered information (where with unclustered I mean using PF-rechits not clustered into a PF-cluster) is used in any object,
Detector based ECAL isolation used by HEEP I think and thats it. 

Also I'm not totally worried about the sigma being too high, how high are we talking about. A factor 2? If so thats fine, remember we were on the edge of 1 sigma vs 2 sigma cuts, both seemed okay.

Finally as of right now E/gamma does not support the re-recoing of data in any release other than the release series of that year. For precisely this issue. Once the dust settles of startup, we can revisit this and make sure we have optimal settings for each year and its all setup up with the approprate modifiers

**Comment by crovelli** [comment]
Hi @slava77, all,

we don't see the need to increase the thresholds for Run1. The ECAL noise
was not that high and the low 80/300 MeV thresholds were already applied
also in Run1 - so we're safe. Also, as stated by @Sam-Harper, we do not
support the re-recoing of data in any release other than the release series
of that year.
In case a re-reco of Run1 data is needed, this has to be studied (also
because the EGamma reco was completely different at the Run1 time)

**Comment by fabiocos** [comment]
@arunhep @lpernie the corresponding 10_2_X PR #22833 is not yet signed, could you please sign it if we need to speed up integration?

**Comment by slava77** [comment]
On 4/6/18 2:06 AM, crovelli wrote:
> Hi @slava77, all,
> 
> we don't see the need to increase the thresholds for Run1. The ECAL noise
> was not that high and the low 80/300 MeV thresholds were already applied
> also in Run1 - so we're safe.


> Also, as stated by @Sam-Harper, we do not
> support the re-recoing of data in any release other than the release series
> of that year.

the current release policy is still that all data taken since 2010 can
be reconstructed in every latest release.
The quality of that reconstruction is apparently getting more and more
degraded.

**Comment by arunhep** [comment]
backport of #22833

**Comment by Sam-Harper** [comment]
>the current release policy is still that all data taken since 2010 can
>be reconstructed in every latest release.
>The quality of that reconstruction is apparently getting more and more
>degraded.

Agreed and we should do something about it, its an issue.

**Comment by fabiocos** [comment]
please test workflow 136.77,136.778

**Comment by fabiocos** [comment]
Same failure as in 10_2_X, it should be fixed by #22893

**Comment by fabiocos** [comment]
please test workflow 136.77,136.778 with #22893

**Comment by fabiocos** [comment]
Combined with the fix #22893 in #22897

**Comment by davidlange6** [comment]
Your PR is unmergeable. Please have a look and possibly rebase it.

**Comment by lpernie** [comment]
My understanding is that PR #22897 is now including this PR and the FIX, so this PR in not needed anymore.

**Comment by fabiocos** [comment]
@lpernie @arunhep at this point I assume we can close it, right?

**Comment by arunhep** [comment]
i think this PR https://github.com/cms-sw/cmssw/pull/22897 from you have merged these changes already. so this can be closed.

**Pull request closed without merging**
