### PR TITLE
MiniAOD reprocessing (74X, BTV): SoftElectron tagger bugfixes

### PR DESCRIPTION
**Pull request by ferencek**
Partial backport of #9673

This PR is part of preparations for possible MiniAOD reprocessing of the Spring15 MC and 50ns Run2012B Data in 74X. More info at the following links:
- https://hypernews.cern.ch/HyperNews/CMS/get/physics-validation/2445.html
- https://twiki.cern.ch/twiki/bin/view/CMS/MiniAODSpring15pass2#BTV

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
Hi, please note the for AdaBoost and Grad boost BDTs you can now use GBRForest to access/store the BDT. It has a much smaller memory footprint and is threadsafe (meaning no need for mutex and you can use the edm::GlobalCache/RunCache/LumiBlockCache extensions to EDProducers. 

See #10275 , #10327 , #10143 for details and examples.

**Comment by ferencek** [comment]
@lgray, switching of the existing TMVA-based b-taggers to GBRForest is in our plans. However, not in this PR. This is primarily driven by the fact that the b-taggers reside in the EventSetup and are therefore created only once per job and are shared across different threads. Nevertheless, the reduced memory footprint and thread-safety of GBRForest are good enough reason to eventually switch.

Probably the best strategy would be to update https://github.com/cms-sw/cmssw/blob/CMSSW_7_6_X/CommonTools/Utils/interface/TMVAEvaluator.h and add a possibility of internally using an instance of GBRForest. Since GBRForest payloads can also be stored in the CondDB, it would also be nice to have a possibility to read payloads from a global tag rather than "externals". All of this requires some development and testing which can hopefully happen in 76X. Also, since the b-taggers reside in the EventSetup, I'm a bit uncertain whether `edm::GlobalCache` needs or can be used and how that would be implemented.

**Comment by lgray** [comment]
If you have things in the eventsetup that you're retrieving you can use the edm::RunCache or edm::LuminosityBlockCache to store them efficiently between all instances of an edm::stream module. 

As for development that's totally understandable, didn't notice this was targetted for 74X.
Good that you are planning this migration for 7-series at some point.

**Comment by Dr15Jones** [comment]
There is no need to use an ```edm::RunCache``` or ```edm::LuminosityBlockCache``` if the ```EventSetup``` products are just used directly. Reading from the ```EventSetup``` is fast.

**Comment by lgray** [comment]
Fair enough.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
(jenkins tests were started manually)

**Comment by slava77** [comment]
modulo the performance consistency problem this is +1

for https://github.com/cms-sw/cmssw/pull/10363	0d095d6
- The code changes are affecting the regular/underlying pp reco and the implementation does not really allow a switch from one version to another, which introduces inconsistency with the mainstream 74X reconstruction. This is a topic for discussion in a separate meeting (not this PR thread)
- I confirmed by cherry-picking these commits that the code changes in  this PR are the same as what we have in 75X (cherry-pick in 75X introduces zero diffs to 75X)
- jenkins tests pass and comparisons with baseline show differences only in softPFElectronBJetTags  (larger diffs) and in pfCombinedMVA  (smaller diffs)

**Comment by slava77** [comment]
+1

based on review above and the re-miniAOD discussion.

**Comment by davidlange6** [comment]
closing PRs included in #10649

**Pull request closed without merging**
