### PR TITLE
preserve integer divisions compatible with python3 syntax

### PR DESCRIPTION
**Pull request by davidlange6**
these are the only cases I see if cf*.py files where the division behavior would otherwise change in python3 vs python2 (I'm still looking for others... and of course there are the non-cf* files)

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by andrius-k** [comment]
+1

**Comment by fabiocos** [comment]
@kpedro88 @rekovic this looks fairly simple and technical, I would like to move forward with it, could you please have a look?

**Comment by kpedro88** [comment]
+upgrade

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Pull request merged**
