### PR TITLE
HIN High-pT trigger DQM for 81X (CMSHLT-1110)

### PR DESCRIPTION
**Pull request by FHead**
In this PR, the DQM setup for the monitoring of the trigger paths requested in https://its.cern.ch/jira/browse/CMSHLT-1110 is asked for integration. No C++ code change is proposed, we require only python level changes.

### CODE REVIEW

**Comment by dmitrijus** [comment]
+1

**Comment by dmitrijus** [comment]
Please add this (and the 80x version) to https://twiki.cern.ch/twiki/bin/viewauth/CMS/DQMHeavyIon2016
So we (DQM) can follow-up with its integration faster.

**Comment by FHead** [comment]
I added both #16431 and #16432 to the twiki page.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
