### PR TITLE
Updating the WP of the Muon MVA ID

### PR DESCRIPTION
**Pull request by andrea21z**
#### PR description:
We have updated the Muon MVA ID model and we need to change the cut of the  WP Tight, Cuts in IP are also added to the Tight working point.

- Related [PR](https://github.com/cms-sw/cmssw/pull/36179).
- This MVA  has been presented in several Muon POG meetings: https://indico.cern.ch/event/1135971/contributions/4766180/attachments/2402974/4109990/muonMVAupdate_7mar2022.pdf
- The analysis is documented in this Analysis Note: https://gitlab.cern.ch/tdr/notes/AN-21-107
- Twiki: https://twiki.cern.ch/twiki/bin/view/CMS/LeptonMVAID
- Cadiline: https://cms.cern.ch/iCMS/analysisadmin/cadilines?line=MUO-22-001 
- Related PR: to include the MVA model in data repository, in .onnx format -> https://github.com/cms-data/RecoMuon-MuonIdentification/pull/8

#### PR validation:

We execute the basic tests suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by jpata** [comment]
> This is a backport of the already merged https://github.com/cms-sw/cmssw/pull/36179.

Probably there is some confusion about what a backport means. Please see here: https://cms-sw.github.io/tutorial-resolve-conflicts.html -> "Backporting a PR" for an explanation and clarify in the description if a backport is intended (in any case, a PR against master such as this one is needed).

**Comment by jpata** [comment]
@cmsbuild please test

**Comment by andrea21z** [comment]
> "Backporting a PR" for an explanation and clarify in the description if a backport is intended (in any case, a PR against master such as this one is needed).

Ok, understood.  

On the other hand, we just found a possible bug and we want to do a couple more checks to be sure before the PR is merged, so I think it's best to stop the PR checks for the moment. @jpata sorry for this ...

**Comment by clacaputo** [comment]
> * In the output there are 3 changes: a new branch with the output of the MVA (muon.mvaIDValue()), two new Selectors with the definition of the proposed Working Points (reco::Muon::MvaIDwpMedium, reco::Muon::MvaIDwpTight)

Hi @andrea21z , I don't see these changes in this PR, I suppose it is just a copy&paste from the description of https://github.com/cms-sw/cmssw/pull/36179. Could you please edit the description, it's misleading. Thank you

**Comment by clacaputo** [comment]
@cmsbuild please test

**Comment by clacaputo** [comment]
Hello @andrea21z , do you have any plots comparing the old model and the new one?

**Comment by andrea21z** [comment]
> Hello @andrea21z , do you have any plots comparing the old model and the new one?

Hello @clacaputo, what types of plots would you like to see? The only change with respect to the old model is that we removed a cut in Isolation used to select the muons to train the model.

**Comment by clacaputo** [comment]
Hi @andrea21z also a reference to a more recent presentation with the new model should be enough. Thanks

**Comment by andrea21z** [comment]
> > > Hello @andrea21z , do you have any plots comparing the old model and the new one?
> > 
> > 
> > Hello @clacaputo, what types of plots would you like to see? The only change with respect to the old model is that we removed a cut in Isolation used to select the muons to train the model.
> 
> Hi @andrea21z , a comparison of the output distribution `mvaIDValue` of the two models, so I can crosscheck that what I see in the comparisons are similar to what you have obtained. Thanks

New MVA on the right and old MVA on the left.
image

**Comment by andrea21z** [comment]
> Hi @andrea21z also a reference to a more recent presentation with the new model should be enough. Thanks

[Here](https://indico.cern.ch/event/1135971/contributions/4766180/attachments/2402974/4109990/muonMVAupdate_7mar2022.pdf) you can find the latest presentation in the Muon POG meeting,

**Comment by clacaputo** [comment]
Hi @andrea21z , thanks for the link. Could you please confirm me that the new model produces an output more shifted towards 0.9 for prompt muons wrt the old model? I can't get this info from the slides.

Here an examples for wf `1330.0` `ZMM_13TeV_TuneCUETP8M1` run2 condition

all_mini_OldVSNew_ZMM13TeVwf1330p0c_patMuons_slimmedMuons__RECO_obj_mvaIDValue

**Comment by andrea21z** [comment]
> Hi @andrea21z , thanks for the link. Could you please confirm me that the new model produces an output more shifted towards 0.9 for prompt muons wrt the old model? I can't get this info from the slides.
> 
> Here an examples for wf `1330.0` `ZMM_13TeV_TuneCUETP8M1` run2 condition
> 
> all_mini_OldVSNew_ZMM13TeVwf1330p0c_patMuons_slimmedMuons__RECO_obj_mvaIDValue

Yes, I confirm this is expected. The output distribution of the new model (slide 14) has the maximum around 0.9 and prompt muons have values between 0.7 and 0.9.

**Comment by clacaputo** [comment]
+reconstruction

- the PR changes muon MVA ID cut due to an updated MVA model https://github.com/cms-sw/cmssw/pull/36179
- reco changes are in line with the expectations
- to be merged together with https://github.com/cms-sw/cmssw/pull/36179

**Comment by perrotta** [comment]
@cmsbuild please test
(tests have disappeared, and must be refreshed)

**Comment by perrotta** [comment]
+1

**Pull request merged**
