### PR TITLE
Small update of tauID python tool (10_6_X)

### PR DESCRIPTION
**Pull request by mbluj**
#### PR description:

Small change in tauID python tool which allows to add new tauIDs to an already existing PATTauIDEmbedder module.

#### PR validation:

Validated with MiniAOD workflow. 
Differences are not expected.

#### if this PR is a backport please specify the original PR:

Backport of  #27397

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
backport of #27397

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/27398	fd4728f
- the backport is correct (the same py code changes as in the master version); this does not affect [yet] the standard workflows
- jenkins tests pass

**Comment by fabiocos** [comment]
+1

**Pull request merged**
