### PR TITLE
Code to process phase2 version of deepTauID v2p5

### PR DESCRIPTION
**Pull request by mbluj**
#### PR description:

This PR adds code for a phase-2 version of DeepTau discriminator. The network structure is identical to that of Run-2/3 DeepTau v2p5, therefore code modifications are small. The changes include:
* Adding scaling parameters and working points for the new training;
* A new "year" identifier introduced to separate this new phase-2 training and current Run-2/3 v2p5 (2026 vs 2018)
* The electron input collection used for the new phase2 deepTauID is sum of two collections: `slimmedElectrons` (gsfElectrons in EB) and `slimmedElectronsHGC` (HGCal electrons in endcaps). Notes: 1. The latter collection is called `slimmedElectronsFromMultiCl` in older CMSSW (<13_0) release series (and samples produced with them) which can cause some problems with running on old samples; 2. The same merged electron collection is used by old-style anti-electron tau discriminant for phase-2;
* The new deepTauID replaces old-style BDT-based tauIDs in miniAOD.

The performance of this phase 2 DeepTau discriminator is documented in [AN-22-090](https://icms.cern.ch/tools-api/restplus/relay/piggyback/notes/AN/2022/90/files/3/download).

The PR to cms-data with the data-model is here: https://github.com/cms-data/RecoTauTag-TrainingFiles/pull/11

Backport of the PRs to 12_5/12_6 is foreseen.

To run standalone test, one can run the configuration file `RecoTauTag/RecoTau/test/runDeepTauIDsOnMiniAOD.py` after setting the flag `phase2 = True` in that file.

#### PR validation:

Validated with the standalone test mentioned above and with miniAOD workflows, matrix tests, `runTheMatrix.py -l limited -i all --ibeos`, successful.
Note: the tests should be run with data-model here: https://github.com/cms-data/RecoTauTag-TrainingFiles/pull/11

### CODE REVIEW

**Comment by mbluj** [comment]
Hello,
this PR must have been overlooked, can someone trigger tests, please?

**Comment by swertz** [comment]
please test with https://github.com/cms-data/RecoTauTag-TrainingFiles/pull/11

**Comment by mbluj** [comment]
All automated tests seem be OK. Is there anything we can do to help with review of this PR?

**Comment by swertz** [comment]
+xpog

Expected changes in tauID products for Phase2 MINIAODs.

Thanks for the reminder @mbluj

**Comment by clacaputo** [comment]
+reconstruction

**Comment by perrotta** [comment]
+1

**Comment by mbluj** [comment]
Just a reminder: this PR requires that also data-model PR https://github.com/cms-data/RecoTauTag-TrainingFiles/pull/11 is merged and then propagated to cms-dist.

**Pull request merged**
