### PR TITLE
add AK4Fwd and AK8Fwd paths to DQM 

### PR DESCRIPTION
**Pull request by kirschen**
(in subfolder as done for the standard AK8 paths last year).
Needed for:
https://its.cern.ch/jira/browse/CMSHLT-1266

### CODE REVIEW

**Comment by mtosi** [comment]
@dmitrijus can we start the integration test, please ?

**Comment by dmitrijus** [comment]
+1

**Comment by mtosi** [comment]
we are anyhow missing the turnON .....

**Comment by davidlange6** [comment]
+1

**Pull request merged**
