### PR TITLE
Minor updates to Sonic (Core and Triton)

### PR DESCRIPTION
**Pull request by kpedro88**
#### PR description:

* use `edm::allowedValues` for base client mode parameter description
* use `edm::Span` to avoid copying output vectors in Triton
* reorganize Triton output format as `std::vector<edm::Span<...>>` (# entries = batch size), and reorganize input format similarly for consistency; assign aliases `TritonOutput` and `TritonInput` to make the interfaces nicer
* allow selecting only some outputs from server (if empty, keep all outputs)
* reorganize utility function for printing collections

#### PR validation:

Ran SonicCore unit tests and SonicTriton standalone tests.

attn: @violatingcp @drankincms @nhanvtran @jeffkrupa @jmduarte @lgray @jpata

### CODE REVIEW

**Comment by kpedro88** [comment]
please test

**Comment by makortel** [comment]
Looks ok to me. @fwyzard, do you have anything to comment?

**Comment by fwyzard** [comment]
+1

**Comment by fwyzard** [comment]
looks OK to me from a cursory look

**Comment by silviodonato** [comment]
+1

**Pull request merged**
