### PR TITLE
[CalibMuon] Move and merge .h and .cc files used by plugin

### PR DESCRIPTION
**Pull request by smuzaffar**
Following the suggested https://github.com/cms-sw/cmssw/pull/34761#pullrequestreview-723838671, this PR moves all the `.h and .cc` files used only by plugin in to plugins directory. Cleans up the BuildFile and fixes the python warnings
```
src/CalibMuon/DTCalibration/python/PlottingTools/plotT0FromHistos.py:7: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if sl is 3 and station is 4: return 11
src/CalibMuon/DTCalibration/python/PlottingTools/plotT0FromHistos.py:7: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if sl is 3 and station is 4: return 11
src/CalibMuon/DTCalibration/python/PlottingTools/plotT0FromHistos.py:8: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if sl is 2 and station is 4: return None
src/CalibMuon/DTCalibration/python/PlottingTools/plotT0FromHistos.py:8: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if sl is 2 and station is 4: return None

```

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by slava77** [comment]
+reconstruction

for https://github.com/cms-sw/cmssw/pull/34853	953b652 
- code changes are technical for reco, updating only build files in RecoLocalMuon/DTRecHit
- jenkins tests pass

**Comment by tvami** [comment]
+alca

**Comment by qliphy** [comment]
+1

**Pull request merged**
