### PR TITLE
Change photon & electron regressions back to fractionized shower shapes 

### PR DESCRIPTION
**Pull request by lgray**
Use fraction-ized shower shapes in the photon and electron regressions, as is done in the training.

This is the result of closer double-checking with the person who produced the photon regression.

@matteosan1

### CODE REVIEW

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
@cmsbuild please test

@slava77 I am done double checking for residual use of full5x5. Done messing with this PR.

**Comment by slava77** [comment]
@lgray both 
``` modifyObject(pat::Electron& ele) ``` and ```modifyObject(pat::Photon& pho) ``` were changed.
The PR description suggests it's only for photons.
Please confirm that the change is as desired.
And if so, please update the PR description

**Comment by lgray** [comment]
@slava77 done

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/10921	 0c57abf
- changes in the code are in line with the PR description
- jenkins tests passed and comparisons with baseline show minor differences in the miniAOD DQM for electrons
the following plot is from 25202 (ttbar with PU=35@25ns MC run2)
wf25202_slimmedele_det

**Comment by davidlange6** [comment]
+1

**Pull request merged**
