### PR TITLE
migrate modules used by the HLT menu to multithreading (75x)

### PR DESCRIPTION
**Pull request by fwyzard**
migrate the following modules to be `stream` or `global` modules:
- EcalRecalibRecHitProducer
- EgammaHLTNxNClusterProducer
- HLTRegionalEcalResonanceFilter
- IPTCorrector
- IsolatedEcalPixelTrackCandidateProducer
- IsolatedPixelTrackCandidateProducer
- L1GlobalTrigger
- L1TCaloUpgradeToGCTConverter
- LaserAlignmentEventFilter
- TriggerResultsFilter
- TriggerResultsFilterFromDB

This is a backport #10909 to 75x.

### CODE REVIEW

**Comment by fwyzard** [comment]
@cmsbuild please test

**Comment by fwyzard** [comment]
I've dropped  the migration of RPCPointProducer for the time being.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by fwyzard** [comment]
updated to address Chris comments (at #10909)

**Comment by fwyzard** [comment]
@cmsbuild please test

**Comment by fwyzard** [comment]
-1

**Comment by fwyzard** [comment]
more work is needed for the modules that read the L1GtTriggerMenu from the EventSetup

**Comment by fwyzard** [comment]
+1

**Comment by fwyzard** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cmsbuild please test
[assuming that the last attempt failed for some bot/git related reasons]

**Comment by fwyzard** [comment]
This has been split into #10966, #10967, #10968, #10969, #10970, while #10965 keeps track of the overall migration.

**Pull request closed without merging**
