### PR TITLE
[102X] Change GT. Fix 2016 MC ECAL PF Rechit thresh

### PR DESCRIPTION
**Pull request by lpernie**
# 2016 MC GTs
. https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/102X_mcRun2_design_v2/102X_mcRun2_design_v3
. https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/102X_mcRun2_startup_v2/102X_mcRun2_startup_v3
. https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/102X_mcRun2_asymptotic_v3/102X_mcRun2_asymptotic_v4
. https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/102X_mcRun2cosmics_startup_deco_v2/102X_mcRun2cosmics_startup_deco_v3
. https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/102X_mcRun2_HeavyIon_v2/102X_mcRun2_HeavyIon_v3
. https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/102X_mcRun2_pA_v2/102X_mcRun2_pA_v3

### CODE REVIEW

**Comment by lpernie** [comment]
please test

**Comment by lpernie** [comment]
backport of #25256 and #25255

**Comment by lpernie** [comment]
+1

**Comment by franzoni** [comment]
greetings @lpernie @tocheng 
can you describe what fix is being deployed here ?
Thanks!

**Comment by lpernie** [comment]
Hi @franzoni ,
The ECAL rechit PF thresholds was an hardcoded value in the past. Later this threshold has been ported into the GT with the EcalPFRecHitThresholds TAG.
2016 GTs  in autocond contains 2018 TAG, and not the 2016 one. This is what has been fixed by this PR.

**Comment by fabiocos** [comment]
@lpernie so you confirm that this is updating autoCond to the GT used for MC production

**Comment by lpernie** [comment]
Hi @fabiocos . The is currently no MC production for 2016.
The production will be for ultralegacy, using 104X release where this fix to the 2016 GT already has been merged.

**Comment by fabiocos** [comment]
+1

**Comment by franzoni** [comment]
thanks @lpernie

**Pull request merged**
