### PR TITLE
Reduce TIB Rail Width to Avoid Overlap with TOB

### PR DESCRIPTION
**Pull request by ianna**
* Reduce TIB rail width to avoid extrusion

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
@civanch - FYI

**Comment by civanch** [comment]
@ianna , @davidlange6 , I just recheck and with this PR tracker is cleaned from overlaps.

**Comment by ianna** [comment]
+1

**Comment by ianna** [comment]
@civanch - I've uploaded new tag for 2017:
```
XMLFILE_Geometry_90YV8_Extended2017_mc
```
do we need to update 2018?

@franzoni - FYI

**Comment by civanch** [comment]
@ianna , I think all current fixes in geometry to 2017 should also go into 2018 and beyond.

**Comment by ianna** [comment]
@civanch - the tag for 2018 is:
```
XMLFILE_Geometry_90YV9_Extended2018_mc
```
I'll submit GT requests for both 2017 and 2018 queues

**Comment by davidlange6** [comment]
+1

**Pull request merged**
