### PR TITLE
More 2017 data relvals

### PR DESCRIPTION
**Pull request by fabozzi**
Adding more 2017B data relvals

### CODE REVIEW

**Comment by fabozzi** [comment]
please test

**Comment by fabozzi** [comment]
@franzoni @arunhep

**Comment by fabozzi** [comment]
please test workflow 136.781,136.782,136.783,136.784,136.785,136.786,136.787,136.788,136.789,136.790

**Comment by fabozzi** [comment]
please test

**Comment by fabozzi** [comment]
please test workflow 136.781

**Comment by fabozzi** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
