### PR TITLE
Run2-alca133 Change prescale factor for IsoTrack filter

### PR DESCRIPTION
**Pull request by bsunanda**
Reduces data volume for AlCaReco file by 45% without losing statistics for calibrating scale factor

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by arunhep** [comment]
please see comment here : https://github.com/cms-sw/cmssw/pull/23344#issuecomment-392535129

**Comment by fabiocos** [comment]
@arunhep well, we should have some test before, no? As far as I can see, the short matrix does not seem to probe this change, nothing looks modified in the output. How was it practically tested?

**Comment by arunhep** [comment]
@bsunanda can provide more details for testing. I dont have means to check it.

**Comment by bsunanda** [comment]
The Filter filters on average 1% of events. So it is difficult to spot changes in o/p size due to the filter. This has been tested outside with larger # of input events and the reduction in data volume is tested.
________________________________

**Comment by fabiocos** [comment]
+1

**Pull request merged**
