### PR TITLE
Added Herwig7 Workflow for wmLHEGS production

### PR DESCRIPTION
**Pull request by Andrej-CMS**
Dear all,
this PR introduces a workflow for wmLHEGS production with Powheg and Herwig7
Kind regards,
Andrej

### CODE REVIEW

**Comment by Andrej-CMS** [comment]
@kpedro88  fixed that issue

**Comment by kpedro88** [comment]
please test workflow 1367

**Comment by alberto-sanchez** [comment]
+1

**Comment by kpedro88** [comment]
There are a couple of suspicious messages in the [step1 logs](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-23732/28978/runTheMatrix-results/1367.0_TTbar_13TeV_Pow_herwig7+TTbar_13TeV_Pow_herwig7+DIGIUP17+RECOUP17+HARVESTUP17/step1_TTbar_13TeV_Pow_herwig7+TTbar_13TeV_Pow_herwig7+DIGIUP17+RECOUP17+HARVESTUP17.log) for workflow 1367:
```
Error: No such file or directory: cmsgrid_final.lhe
* A warning exception occurred in the initialization of EventGenerator: 
LesHouchesReader LesHouchesReader has the IDWTUP flag set to 3 which is not supported by this reader, the produced events may not be sampled correctly. It is up to sub-classes of LesHouchesReader to correctly convert to match IDWTUP +/- 1. Will try to make intelligent guesses to get correct statistics.
In most cases this should be sufficient. Unset <interface>WeightWarnings</interface> to avoid this message,or set <interface>Weighted</interface> to on.
* A warning exception occurred in the initialization of EventGenerator: 
When scanning events, the LesHouschesReader 'LesHouchesReader' found undeclared processes.
* A warning exception occurred in the initialization of EventGenerator: 
LesHouchesReader LesHouchesReader has the IDWTUP flag set to 3 which is not supported by this reader, the produced events may not be sampled correctly. It is up to sub-classes of LesHouchesReader to correctly convert to match IDWTUP +/- 1. Will try to make intelligent guesses to get correct statistics.
In most cases this should be sufficient. Unset <interface>WeightWarnings</interface> to avoid this message,or set <interface>Weighted</interface> to on.
* A warning exception occurred in the initialization of EventGenerator: 
When scanning events, the LesHouschesReader 'LesHouchesReader' found undeclared processes.
Error: The object '/Herwig/EventHandlers/Luminosity' was not created as another object with that name already exists.
Error: The object '/Herwig/EventHandlers/LesHouchesHandler' was not created as another object with that name already exists.
Error: The object '/Herwig/Cuts/NoCuts' was not created as another object with that name already exists.
Error: The object '/Herwig/Partons/LHAPDF' was not created as another object with that name already exists.
Error: The object '/Herwig/EventHandlers/LesHouchesReader' was not created as another object with that name already exists.
Error: The object '/Herwig/Partons/PDFSet' was not created as another object with that name already exists.
```

Are these expected?

**Comment by kpedro88** [comment]
@Andrej-CMS ping

**Comment by Andrej-CMS** [comment]
Hello @kpedro88 ,
The warnings and errors are pretty much expected. 
The first error "Error: No such file or directory: cmsgrid_final.lhe" is due to the fact that CMSSW tries to execute the GeneratorFilter before ExternalLHEProducer and I "fixed" by simply executing the read in of the LHE file twice. This is why the first time it says that the LHE file doesn't exist. 

The GEN production still works fine and the events are correct. The rest of the errors is related reading the settings twice, but it doesn't do anything for the production.

If you have any idea how to surpass that or not make CMSSW execute the process.generator step before ExternalLHEProducer, please let me know. I already made a HN thread in February because of this, but there was no reply from the CMSSW experts.

Kind regards,

Andrej

**Comment by kpedro88** [comment]
@Andrej-CMS okay, if the errors aren't specific to this workflow, then it's fine for this PR.

@alberto-sanchez maybe you can follow up on improving the generation sequence?

**Comment by kpedro88** [comment]
+1

**Comment by fabiocos** [comment]
@fabozzi @prebello any objection?

**Comment by prebello** [comment]
@fabiocos @Andrej-CMS @kpedro88 
we see that it is implemented as 2017 standard relval.
 Is it planned to be used only for IB test?

**Comment by Andrej-CMS** [comment]
I was asked @agrohsje to privide a work flow for LHE showering with Herwig7. Maybe Alexander can comment for which purposes it should be used.

**Comment by agrohsje** [comment]
Dear all,
it was indeed triggered by the discussion we had about the IB tests and could be nice to have assuming H7 usage will ramp up.
Cheers, Alexander.

**Comment by prebello** [comment]
+1

 for IB test then no objections @fabiocos

**Comment by fabiocos** [comment]
@Andrej-CMS @agrohsje thanks, I guess that @prebello question, and mine, is: do you need a standard complete workflow for this, or a GEN-only (5XX) would be sufficient? What are the checks you need to do on fully reconstructed events? Is this related to JetMET studies?

**Comment by agrohsje** [comment]
To my mind 5xx should be totally sufficient.

**Comment by fabiocos** [comment]
so @Andrej-CMS what is your position? Do we really need a complete workflow?

**Comment by kpedro88** [comment]
@smuzaffar @fabiocos I think the bot re-read my +1 and decided to merge it... do I need to go edit all of my +1s on open PRs to +upgrade?

**Comment by fabiocos** [comment]
@kpedro88 the dangerous life of managers with superpowers :-) 

I think that now for upgrade you should sign with +upgrade (@smuzaffar could you please confirm?)
In any case it is not a major problem, we can replace 1367 later with some 5XX if there is not strong reason to have a complete workflow. But may be there is, I imagine it could be interesting for JetMET. I would like to know @Andrej-CMS motivation

**Comment by smuzaffar** [comment]
ah right, did not think of this situation @kpedro88 . I will update all of your +1 to +upgrade.

**Comment by smuzaffar** [comment]
Ok all +1 of converted to +upgrade for open PRs. I will see if I have update bot to automatically convert +1 to +category if comment is before sometime. This might be useful for future L2 with L1 powers :-)

**Comment by smuzaffar** [comment]
@kpedro88 , https://github.com/cms-sw/cms-bot/commit/f0f55db90b684e04144b8b51aab6b70639253888 should allow to treat any of your +1 (made before 2018-07-13) as +upgrade.

**Comment by Andrej-CMS** [comment]
Hello @kpedro88 ,
I'm perfectly fine with a 5XX workflow. I will update the PR.
Kind regards,
Andrej

**Comment by fabiocos** [comment]
@Andrej-CMS @agrohsje @alberto-sanchez @covarell it looks like that the Powheg gridpack used here is not good to be used on gcc700, see the failures in 

https://cmssdt.cern.ch/SDT/html/cmssdt-ib/#/relVal/CMSSW_10_2/2018-07-12-2300?selectedArchs=slc6_amd64_gcc630&selectedArchs=slc7_amd64_gcc630&selectedArchs=slc7_amd64_gcc700&selectedArchs=slc6_amd64_gcc700&selectedFlavors=X&selectedStatus=failed

13:21 cmsdev15 523> ./pwhg_main 
./pwhg_main: /usr/lib64/libgfortran.so.3: version `GFORTRAN_1.4' not found (required by ./pwhg_main)

could you please provide a fixed gridpack?

**Comment by covarell** [comment]
@Andrej-CMS, in the externalLHEProducer here:

https://github.com/cms-sw/cmssw/pull/23732/files#diff-d8e257c3e187674153a582b3d163830c

you just need to replace the gridpack location as in:

https://github.com/covarell/cmssw/blob/c00fa1089beab35fc82166e69815bc06fe26bfdb/Configuration/Generator/python/TTbar_Pow_LHE_13TeV_cff.py

It's better if you do it, since it is in your cmssw branch...

**Pull request merged**
