### PR TITLE
HGCal ID variables

### PR DESCRIPTION
**Pull request by SohamBhattacharya**
#### PR description:

This is a backport of PR #32519.

### CODE REVIEW

**Comment by fwyzard** [comment]
please test

**Comment by jpata** [comment]
@SohamBhattacharya before I start the matrix tests, is there a way to make sure this code is running in a workflow?

**Comment by fwyzard** [comment]
I don't think it runs as part of any workflows, at least until there will be a Phase 2 HLT in the release (maybe in 11.3.x or 12.0.x).

**Comment by jpata** [comment]
@cmsbuild please test

**Comment by jpata** [comment]
+reconstruction

- direct backport of  #32519 (same branch)
- no issues with the tests (the code does not run in jenkins)
- validation was done by the HLT team

**Comment by perrotta** [comment]
backport of  #32519

**Comment by Martin-Grunewald** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
