### PR TITLE
add beginStream as a top level function

### PR DESCRIPTION
**Pull request by gartung**

### CODE REVIEW

**Comment by gartung** [comment]
@cdj

**Comment by gartung** [comment]
@Dr15Jones

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by Dr15Jones** [comment]
The test failures are not from this pull request

**Comment by Dr15Jones** [comment]
+1

**Comment by Dr15Jones** [comment]
+1

**Comment by gartung** [comment]
@slava77, @davidlange6, @degano, @smuzaffar, @Dr15Jones 
Can this be merged please.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by davidlange6** [comment]
+1

**Pull request merged**
