### PR TITLE
Introduce `SiPixelQualityPlotter`

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

It is sometimes useful (required) to produce plots of the fraction of luminosity a given pixel component is bad, in order to either use the information for the dynamic bad FED channel simulation or just for display purposes (e.g. to take decisions about what components to mask).  
I port in `cmssw` a private code that has been used for this purpose in the past years.

#### PR validation:

This PR introduces a unit test for the introduced class. 
I tested it successfully with `scram b runtests_SiPixelCondPlottingTests` and obtained [these pictures](http://musich.web.cern.ch/musich/display/SiPixelCondPlottingTests/). 
Here's an example:

image

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Not a backport.

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by tvami** [comment]
+db
 * unit test passed: https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-26e13f/32811/unitTests/src/CondTools/SiPixel/test/SiPixelCondPlottingTests/testing.log

**Comment by mmusich** [comment]
> Reco comparison results: 3102 differences found in the comparisons
> DQMHistoTests: Total failures: 7837

There is nothing in this PR they can possibly lead to this.

**Comment by perrotta** [comment]
please test
(to see if it reproduces)

**Comment by perrotta** [comment]
+1

**Pull request merged**
