### PR TITLE
Evt gen mixing bs patch 2015 02 19

### PR DESCRIPTION
**Pull request by inugent**
Adding Patch to fix mixing for Bs to patch for EventGen overlap bug and including Bs in the relval.

### CODE REVIEW

**Comment by covarell** [comment]
The patch for Bs mixing turnoff in Pythia appears to be applied to Bs->mumu only. In general it is not safe to expect that the user knows about the command to be given in the configuration every time EvtGen is called.

@mkirsano @inugent is there an easy way to force fmasterGen->readString('ParticleDecays:bMix = off') in Pythia8Interface if a specific component of ExternalDecays is called (EvtGen in this case?)

**Comment by inugent** [comment]
There is a way to use special setting as in the PhotosInterface, but the command but it would only with pythia8 I will try to add this.... and update this pull request.

**Comment by inugent** [comment]
Fix has been added - requires patch to EvtGenInterface, ExternalDecays and Pythia8Interface.

**Comment by covarell** [comment]
+1 
Full validation to be performed with RelVals but clearly fixing previous issues

**Comment by inugent** [comment]
will open a new pull since it was broken by push after running git cms-merge-topic

**Pull request closed without merging**
