### PR TITLE
fixed macros to be compatible with Root 6

### PR DESCRIPTION
**Pull request by friccita**
In Validation/Geometry/test, some of the root macros for producing material budget plots could not compile, due in some cases to having a structure incompatible with Root 6, and in some cases to typos and missing or improperly placed function/object/variable declarations. These bugs have been fixed in the following macros:
- MaterialBudget.C
- MaterialBudget_TDR.C
- ECALMaterialBudgetCompare.C
- TrackerMaterialBudgetComparison.C

They can now compile in Root 6.

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1

**Comment by friccita** [comment]
I have just tacked on a new change, in which I edited Geometry/TrackerCommonData/data/Materials/Makefile so that the Fortran code for generating the properties of material mixtures can be compiled. Previously the compilation was crashing because the Makefile referred to some libraries that could not be found.

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
