### PR TITLE
Clean buildfiles in DQM

### PR DESCRIPTION
**Pull request by guitargeek**
#### PR description:

Another quick partially automatic BuildFile cleaning PR in the style of many before (for example #29541), this time covering all DQM subsystems.

In a few files, I added previously missing includes that were previously gotten indirectly, such that the BuildFile cleaning script does not give false positives.

#### PR validation:

CMSSW compiles. It was checked that all newly added dependencies are actually required by the package with `git grep`.

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by silviodonato** [comment]
Kind reminder @rekovic

**Comment by silviodonato** [comment]
merge
@rekovic  please let me know if you have any objections

**Pull request merged**
