### PR TITLE
FastSim Tracking without sim info

### PR DESCRIPTION
**Pull request by a-kapoor**
please test
Got rid of all direct sim-info for creating seed and tracks. Instead fullsim global region and seed creator is used to create seeds. Moreover, track candidates are now initialized using back propagated seed state and not sim-track and sim-vertex information.

### CODE REVIEW

**Comment by lveldere** [comment]
please test

**Comment by lveldere** [comment]
please test

**Comment by VinInn** [comment]
please add FastSim to title

**Comment by lveldere** [comment]
please test

**Comment by lveldere** [comment]
please test

**Comment by lveldere** [comment]
please test

(retriggering, because comparisons don't show up)

**Comment by lveldere** [comment]
+1

Can't wait forever on comparisons.
private validation looks good.

**Pull request merged**
