### PR TITLE
Added LongLived DQM plots; minor fixes for plots on Data

### PR DESCRIPTION
**Pull request by jpazzini**
Added profiles to monitor LongLived features
Minor fixes in data to avoid errors due to the request of JetCorrector, not available for all the tested samples.

### CODE REVIEW

**Comment by deguio** [comment]
please remove the commented lines and submit to 81x first.
thanks,
F.

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1
provided it passes the tests

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Comment by dmitrijus** [comment]
+1

**Pull request merged**
