### PR TITLE
Fix caloTruthProducer_cfi for fastsim

### LINKED ISSUE #23304: Failure in wf 250399 induced by the phase2 premixing code update #23065
After the merge of #23065 , the test workflow 250399.0 fails because of a configuration problem, see 

https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc6_amd64_gcc630/CMSSW_10_2_X_2018-05-23-2300/pyRelValMatrixLogs/run/250399.0_FS_PREMIXUP15_PU25+FS_PREMIXUP15_PU25/step1_FS_PREMIXUP15_PU25+FS_PREMIXUP15_PU25.log

The problems happens in

  File "/cvmfs/cms-ib.cern.ch/nweek-02525/slc6_amd64_gcc630/cms/cmssw/CMSSW_10_2_X_2018-05-23-2300/python/SimGeneral/MixingModule/caloTruthProducer_cfi.py", line 38, in <module>
    premix_stage1.toModify(caloParticles, premixStage1 = True)

due to

KeyError: 'Unknown parameter name premixStage1 specified while calling Modifier'

### PR DESCRIPTION
**Pull request by makortel**
Fixes #23304.

Tested in CMSSW_10_2_X_2018-05-23-2300, 250399 runs again, no other changes expected.

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test workflow 250399.0

**Comment by fabiocos** [comment]
@makortel thanks, I tested it independently and I see it solves the problem. @civanch I will merge it for an out-of-time IB this afternoon, as it looks simple and we verified that it solves the observed issue. I will appreciate if in case you manage to check and sign before that

**Comment by civanch** [comment]
+1

**Comment by fabiocos** [comment]
The test output confirms the validity of the fix

**Comment by fabiocos** [comment]
+1

**Pull request merged**
