### PR TITLE
[L1][BuildFile] Use ifarch instead of ifarchitecture to match system arch only.

### PR DESCRIPTION
**Pull request by smuzaffar**
- BuildFile cleanup: Use ifarch to match the exact arch
- Fixed unit tests to use CMSSW_RELEASE_BASE if `CondTools/L1TriggerExt` package is not available in local dev area

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by cecilecaillol** [comment]
+l1

**Comment by perrotta** [comment]
@smuzaffar the unit test errors look correlated to this PR: do you have any idea why?

**Comment by smuzaffar** [comment]
ok @perrotta tests fail as they need a python configuration from another package ( CondTools/L1TriggerExt/test/L1ConfigWritePayloadOnlineExt_cfg.py ). This is nothing to do with the change I made here but anyway I will provide a fix

**Comment by smuzaffar** [comment]
@cms-sw/l1-l2 , can you please re-review this change

**Comment by cecilecaillol** [comment]
+l1

**Comment by perrotta** [comment]
+1

**Pull request merged**
