### PR TITLE
Phase-2 L1T: Fix GT packed format for Correlator e/gamma and tau objects

### PR DESCRIPTION
**Pull request by cerminar**
#### PR description:

This PR addresses a bug in converting the hardware data format used in the Correlator to the GT one.

### CODE REVIEW

**Comment by epalencia** [comment]
Please test

**Comment by epalencia** [comment]
Please test

**Comment by epalencia** [comment]
+l1

**Comment by srimanob** [comment]
type bug-fix

**Comment by srimanob** [comment]
+Upgrade

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
