### PR TITLE
[14_1_X] New Inputs for D110 And Enabling HIN Phase2 Wf

### PR DESCRIPTION
**Pull request by AdrianoDee**
#### PR description:

Plain back-port of #46355.

#### PR validation:

New inputs works.

### CODE REVIEW

**Comment by AdrianoDee** [comment]
test parameters:
- relval_opts = -w upgrade
- workflows = 29751.85

**Comment by AdrianoDee** [comment]
back-port of https://github.com/cms-sw/cmssw/pull/46355

**Comment by AdrianoDee** [comment]
please test

**Comment by AdrianoDee** [comment]
backport of https://github.com/cms-sw/cmssw/pull/46355

**Comment by AdrianoDee** [comment]
@cms-sw/upgrade-l2 gentle ping :)

**Comment by Moanwar** [comment]
+Upgrade

**Comment by AdrianoDee** [comment]
+pdmv

**Comment by AdrianoDee** [comment]
please test

**Comment by AdrianoDee** [comment]
@cms-sw/orp-l2 this is not strictly needed but since this include the HIN Run4 workflow it maybe useful to have them in. Let me know what you think.

**Pull request merged**
