### PR TITLE
Tune dependent reweighting

### PR DESCRIPTION
**Pull request by zleba**
Small change that allows having a different reweighting function for each tune.
We observed that at highPt the MC behaviour is very tune(PDF) dependent.
The generator fragment can currently contain
 reweightGenEmp = cms.PSet(
        tune = cms.string('CP5')
    )
which will do MC reweighting suitable for CP5 tune.
Without the tune option fragment behaves as before (backward compatibility).

### CODE REVIEW

**Comment by alberto-sanchez** [comment]
please test

**Comment by zleba** [comment]
@alberto-sanchez  The modified files are quite stable across version, so the same changes can be done on master.
Should I create new pull request for the master branch?
In my rep. is basically this commit
https://github.com/zleba/cmssw/commit/0b51a1c58332c4093e0090647dc1d6dd19f7c5c4

In the end we want to use this feature for 2017 and 2018 MC production, so in some way to backport to 9_3_X and 10_X_X

**Comment by alberto-sanchez** [comment]
Hi @zleba,   
Yes, it has to go to master, and then to the other releases where you want to use, in this case
10_2_X, 9_3_X

**Comment by alberto-sanchez** [comment]
backport #24179

**Comment by alberto-sanchez** [comment]
+1

**Comment by zleba** [comment]
Hi, yes, with the old MC fragments the behaviour is preserved.
For the Pythia 8 runs with the newest CP5 tune the default reweighting does not work good, so one can set tune equal 'CP5' and reweighting formula with different values of parameters will be used (appropriate for CP5).

There are 6 parameters of the reweighting formula, and in the code the values are hardcoded for CP5 tune and for the older CUETP8 tune (default), the other possibility would be to read the parameters from the fragment itself.
Currently, with any new Py8 tune we need to change the CMSSW code to add the proper reweighting parameters for the new tune.

**Comment by fabiocos** [comment]
@zleba thank you for the confirmation, as far as this backport is concerned it looks ok. But in general would not be advisable to have these parameters passed through a PSet? Having them hardcoded looks a fragile solution in general...

**Comment by fabiocos** [comment]
+1

**Pull request merged**
