### PR TITLE
Adding the possibility of additional weights (scale / pdf variation) for Sherpa 2.2, storing the relevant information in GenRunInfoProduct

### PR DESCRIPTION
**Pull request by thuer**
Adding the possibility of additional weights (scale / pdf variation) for Sherpa 2.2. Sherpa stores the weighst in form of named weights which we do not do in CMSSW, so the relevant names are stored in GenRunInfoProduct

### CODE REVIEW

**Comment by vciulli** [comment]
This is ok to me

**Comment by govoni** [comment]
+1

**Comment by covarell** [comment]
+1

**Comment by thuer** [comment]
@covarell We changed it to use the GenLumiInfoHeader in 81X, see #13756 , should I do the same for 80X?

**Comment by covarell** [comment]
Ah, yes, sorry I thought this was already in the previous commit

**Comment by covarell** [comment]
-1

**Pull request closed without merging**
