### PR TITLE
Add PA-specific ALCARECO producers 80X

### PR DESCRIPTION
**Pull request by jrcastle**
backport of #16109

### CODE REVIEW

**Comment by jrcastle** [comment]
@mandrenguyen

**Comment by mmusich** [comment]
backport of https://github.com/cms-sw/cmssw/pull/16109

**Comment by mmusich** [comment]
please test

**Comment by jrcastle** [comment]
In attempt to update the labels, backport of #16109

**Comment by jrcastle** [comment]
backport of #16109

**Comment by mmusich** [comment]
please test

**Pull request closed without merging**
