### PR TITLE
Speed up filesFromList and filesFromDASQuery in ConfigBuilder.py 

### PR DESCRIPTION
**Pull request by kpedro88**
#### PR description:

Thanks to @DryRun for pointing out that the function `filesFromList()` was unnecessarily slow, especially when parsing an entire premixed pileup sample.

Loading a text file list generated by this command:
```
dasgoclient -query="file dataset=/Neutrino_E-10_gun/RunIISummer17PrePremix-PUAutumn18_102X_upgrade2018_realistic_v15-v1/GEN-SIM-DIGI-RAW" > Neutrino_E-10_gun_RunIISummer17PrePremix-PUAutumn18_102X_upgrade2018_realistic_v15-v1_GEN-SIM-DIGI-RAW.txt
```

Before the change: 20.75 minutes
After the change: 2.8 seconds

The same fix is propagated to `filesFromDASQuery()`.

#### PR validation:

Confirmed same output from function.

### CODE REVIEW

**Comment by kpedro88** [comment]
please test

**Comment by kpedro88** [comment]
please test

**Comment by kpedro88** [comment]
code-checks

**Comment by DryRun** [comment]
Thanks for making the PR, @kpedro88 . Should this be backported to the DR campaign releases, 8_0_X/9_4_X/10_2_X?

**Comment by kpedro88** [comment]
10_6_X is probably the most impactful backport, but I can also backport to the other suggested release cycles.

I'd like to get the master PR approved first, though, to streamline the backporting process.

@silviodonato please take a look

**Comment by silviodonato** [comment]
+operations

**Comment by silviodonato** [comment]
Yes, 10_6_X is the most important backport (Run-2 ultra legacy). The improvement is impressive ( 20.75 minutes --> 2.8 seconds) so I would backport also to 10_2_X, that is used for Run-2 analysis. Also a backport to 8_0_X and 9_4_X can be useful for the DR campaigns.

**Comment by silviodonato** [comment]
+1

**Pull request merged**
