### PR TITLE
Correct the sampic record name

### PR DESCRIPTION
**Pull request by ChrisMisan**
#### PR description:

This PR resolves PCL harvester crash by correcting the sampic record name. 

#### PR validation:
PR was validated with the tarball /afs/cern.ch/user/c/cmst0/public/PausedJobs/ALCAPPS/job_27. The PR will be followed by the new relval test for sampic PCL.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport to the 12_4 will follow.

### CODE REVIEW

**Comment by ChrisMisan** [comment]
type ctpps, bug-fix

**Comment by ChrisMisan** [comment]
urgent

- backport is urgent

**Comment by ChrisMisan** [comment]
please test

**Comment by tvami** [comment]
> This PR resolves https://github.com/cms-AlCaDB/AlCaTools/issues/67 by


@ChrisMisan this is not true after all, since you didnt introduce a new relval

**Comment by tvami** [comment]
+1
 * the PR description needs modification
 * trusting the private test from the author

**Comment by qliphy** [comment]
+1

**Pull request merged**
