### PR TITLE
Run3-sim146X Try to see the impact of additional SD's of HCAL in the Run3 scenario for dd4hep

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Try to see the impactc of additional SD's of HCAL in the Run3 scenario for dd4hep

#### PR validation:

Use the code to check the impact of the extra SDs of HCAL with the dd4hep definition

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@civanch Could you please approve this PR? I have a few other codes to commit after this. I may have found the issue for HF discrepancy

**Comment by civanch** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
