### PR TITLE
Remove unused instance of TrajectoryStateTransform

### PR DESCRIPTION
**Pull request by perrotta**
This could replace #25742 by simply removing the unneeded instance
@Dr15Jones do you see any counterindication?

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
Uhm... The tests show a difference in the conversion output in wf 25, where one less conversion is present with respect to the baseline. That's curious...

**Comment by slava77** [comment]
On 1/23/19 1:42 PM, perrotta wrote:
> Uhm... The tests show a difference in the conversion output in wf 25,
> where one less conversion is present with respect to the baseline.
> That's curious...
> 
> —

this might be random.
perhaps try again with the next IB; it may go away.

**Comment by perrotta** [comment]
please test
(Let retry in a fresher IB. I think the difference observed are unrelated, since they show up identically in the tests of other, uncorrelated pull requests, e.g. #25741. I was initially puzzled because this PR does touch a conversion related plugin, even though such a plugin doesn't seem to be used anywhere as of now by now.)

**Comment by fabiocos** [comment]
+1

**Pull request merged**
