### PR TITLE
Phase2-hgx282Z Remove the HCAL option in the validation codes in HGCalValidation/test

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Remove the HCAL option in the validation codes in HGCalValidation/test

#### PR validation:

Use test codes in Validation/HGCalValidation/test/python

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by jfernan2** [comment]
+1

**Comment by qliphy** [comment]
The previous "IB is having errors in the relvals.The error does NOT come from this pull request".   To run the test again with new IB to make sure the comparison is ok.

**Comment by qliphy** [comment]
please test

**Comment by qliphy** [comment]
+1

**Pull request merged**
