### PR TITLE
Validation packages: cleanup clang warnings for missing override

### PR DESCRIPTION
**Pull request by gartung**
Add override keyword where needed. Remove unused functions.

### CODE REVIEW

**Comment by gartung** [comment]
@Dr15Jones

**Comment by Dr15Jones** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by fabiocos** [comment]
The differences observed in tests are due to the FastSim fix added to this PR test, and affect only the corresponding FastSim Relval, so look unrelated to the present PR.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
