### PR TITLE
[Online DQM] re-introduce unit tests for visualization

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

Apparently #35593 has fixed a long-standing issue, leading to not being able to run the visualization unit tests.

#### PR validation:

Run `cmsRun DQM/Integration/python/clients/visualization-live_cfg.py unitTest=True` in a recent IB (rebased to HEAD of CMSSW_12_1_X) adding commit 9870cee9372e5aa8fadbc42e88994c97c0ac92d7 (proposed in https://github.com/cms-sw/cmssw/pull/35639) and it run successfully. 

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

### CODE REVIEW

**Comment by jfernan2** [comment]
+1

**Comment by perrotta** [comment]
please test
(just check if there are no issues in running this standalone, so that we can merge even before #35639)

**Comment by mmusich** [comment]
@cmsbuild, please test with #35639

**Comment by mmusich** [comment]
unhold

**Comment by perrotta** [comment]
+1

**Pull request merged**
