### PR TITLE
Switch l1tstage2 DQM client to run3

### PR DESCRIPTION
**Pull request by benkrikler**
#### PR description:
This PR is to migrate the stage2 L1Trigger DQM code to use the Run3 era modifiers.  Changes should be minimal at this point and from my tests this seems correct.

Relates to this PR from @dinyar https://github.com/cms-sw/cmssw/pull/31951 

#### PR validation:
I have tested this PR running the clients on a specific run and compared the outputs - things seem as expected to me.

### CODE REVIEW

**Comment by dinyar** [comment]
Hi @benkrikler, @jfernan2,

Thanks! This should be used in the MWGR next week. I assume we need a backport to 11_1_X?

Cheers,
Dinyar

**Comment by jfernan2** [comment]
Hi @dinyar 
Yes MWGR implies indeed backport to 11_1_X

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
