### PR TITLE
80X HLT June15th train

### PR DESCRIPTION
**Pull request by perrotta**
Update HLT menu up to /dev/CMSSW_8_0_0/HLT/V381, i.e. frozen/online versions 2.2

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by perrotta** [comment]
DAS error again...

**Comment by perrotta** [comment]
please test

**Comment by davidlange6** [comment]
+1

**Pull request merged**
