### PR TITLE
reject seed candidates not part of superclusters [93X]

### PR DESCRIPTION
**Pull request by kpedro88**
Backport of #20458

### CODE REVIEW

**Comment by kpedro88** [comment]
assign upgrade

**Comment by kpedro88** [comment]
please test

**Comment by kpedro88** [comment]
+1

**Comment by kpedro88** [comment]
please test

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/20459	57e3745
- same as the master version https://github.com/cms-sw/cmssw/pull/20458	57e3745; relevant only for cases where processing would crash [currently happens frequently enough in HGCAL reco ]
- jenkins tests pass

**Comment by kpedro88** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
