### PR TITLE
[94X] Make muon HLT (L3/TkMu) work in phaseII scenarios

### PR DESCRIPTION
**Pull request by battibass**
This PR:
- makes `TSGForOI` work in Phase2  (as done for offline the outside-in muon iteration in [PR 18553](https://github.com/cms-sw/cmssw/pull/18553))
- fixes a small initilaization issue in `MaskedMeasurementTrackerEventProducer`

### CODE REVIEW

**Comment by slava77** [comment]
@battibass 
passing code-checks is required
please apply the patch

**Comment by perrotta** [comment]
please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/20723	4832fd5
- updates to make TSGForOI used in HLT to work in phase2
- jenkins tests pass and comparisons show no differences (phase-2 workflows do not include HLT algorithms, only a fake table)

**Comment by slava77** [comment]
assign upgrade

**Comment by davidlange6** [comment]
merge

**Pull request merged**
