### PR TITLE
Primary vertexing speed improvements

### PR DESCRIPTION
**Pull request by lgray**
Speed improvements for slowly converging cases in 140/200PU. First found in KNL runs but shown to be a problem in Xeon as well.

Primary fix here is to move an expensive calculation out of a loop and also to short circuit that loop when more than 2 tracks are found in the vertex.

Factor many speed improvement for problem events. Should also improve the typical vertexing time, from same short circuit.

### CODE REVIEW

**Comment by lgray** [comment]
@gartung @Dr15Jones

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
@slava77 this one fixes the events that occasionally take hours in 200PU. All the credit to @gartung. :-)

**Comment by gartung** [comment]
I just tested Chris' suggestions.

**Comment by lgray** [comment]
@bendavid You may be interested in this one too.

**Comment by lgray** [comment]
@cmsbuild please test

(note, speedup only expected now in the non-vectorized code, after further
understanding)

**Comment by slava77** [comment]
@lgray 
please provide timing values here (better in the description of the PR; can be quotes from @gartung  FWIW)

**Comment by Dr15Jones** [comment]
I believe we didn't find any appreciable speed improvements from this change.

**Comment by lgray** [comment]
Yes, the speed improvement was from a bug :-(

**Comment by slava77** [comment]
-1

OK, then this can move to 91X; given no significant improvement

**Pull request closed without merging**
