### PR TITLE
adding decay file for  longlived stable

### PR DESCRIPTION
**Pull request by alberto-sanchez**

### CODE REVIEW

**Comment by covarell** [comment]
+1

**Comment by davidlt** [comment]
Error not related to the changes. Jenkins picked an older IB (1100 our instead of 2300 which had Protocol Buffers updates). The way testing it works is that it picks IB + all other changes already merged + your changes. That's why it failed.

**Comment by covarell** [comment]
please test

**Comment by covarell** [comment]
Retrying now

**Comment by davidlange6** [comment]
this request is now available via an external data file - no need to include it here as well
https://github.com/cms-data/GeneratorInterface-EvtGenInterface

**Pull request closed without merging**
