### PR TITLE
Instrument cmssw for nvidia nvprof/nvvm (10.1.x)

### PR DESCRIPTION
**Pull request by fwyzard**
Instrument cmssw for nvprof/nvvm
  - implement a Service to provide CMSSW-aware annotations to nvprof/nvvm
  - highlight selected modules and delayed modules
  - update for CMSSW 10.0.x

### CODE REVIEW

**Comment by fwyzard** [comment]
@makortel let me know if you think this should go in a different package

**Comment by fwyzard** [comment]
type new-feature

**Comment by makortel** [comment]
@fwyzard I have some suggestions/thoughts for other places
* `HeterogeneousCore/CudaService` (or `CudaServices` or `CUDAServices`)
  * The outcome of the hackathon was to suggest `HeterogeneousCore` top-level package for core components for heterogeneous algorithms
  * I placed (in my development branch) the initial version of CUDA resource managing service to `HeterogeneousCore/CudaService`
  * It could be useful (as your package naming also suggests) to put all CUDA-dependent core components to a single place
  * Taking into account the official capitalization of CUDA (which I ignored), how about `HeterogeneousComputing/CUDAServices`?
* Alternative placement could be under `PerfTools`
   * The service is related to profiling
   * On the other hand, e.g. IgProf stuff is elsewhere so the argument is somewhat weak
* If we would stick with `FWCore/CUDAServices`, should the resource managing service to be placed in the same package as well?
   * I think it would be confusing to have several sub-packages in different top-level packages with "CUDAService" in their name (so yes to the question above)
   * I think the CUDA resource managing service should be on the same top-level package as the other core components for heterogeneous algorithms

@felicepantaleo

**Comment by fwyzard** [comment]
OK, I'll move it to `HeterogeneousComputing/CUDAServices` .

**Comment by makortel** [comment]
Sorry! I was supposed to suggest `HeterogeneousCore/CUDAServices`.

**Comment by fwyzard** [comment]
OK, I'll use that.

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by fwyzard** [comment]
Please merge #22009 instead.

**Pull request closed without merging**
