### PR TITLE
Restore the original behaviour of PR 22131, revert PR 22239

### PR DESCRIPTION
**Pull request by fabiocos**
After the integration of #22314 the problem causing the crash discussed in the issue #22207 has been removed. This PR restores the originally intended behaviour.

### CODE REVIEW

**Comment by fabiocos** [comment]
@gpetruc FYI

**Comment by fabiocos** [comment]
please test workflow 1325.5

**Comment by slava77** [comment]
@fabiocos 
for the future similar cases,
it's more straightforward to just revert #22239.
Every merged PR has a "revert" button at the end of the web page.

**Comment by fabiocos** [comment]
@slava77 you are right, this case was fairly trivial anyway. Please let me know if you have some concern with the PR, otherwise we may integrate it, the problem in 1325.5 looks now gone.

**Comment by slava77** [comment]
@fabiocos 
it looks like we need to revert this PR.

the data PR using 80XLegacy inputs now takes more than 1h to execute instead of just a few mins.
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-22338/26297/runTheMatrix-results/136.7611_RunJetHT2016E_reminiaod+RunJetHT2016E_reminiaod+REMINIAOD_data2016_HIPM+HARVESTDR2_REMINIAOD_data2016_HIPM/step2_RunJetHT2016E_reminiaod+RunJetHT2016E_reminiaod+REMINIAOD_data2016_HIPM+HARVESTDR2_REMINIAOD_data2016_HIPM.log

This seems to affect only the data 80X re-miniAOD, while MC is OK.
In my local tests with timing printed out for 136.7611 I see that patTrigger now takes 90 s/event instead of ~50 ms/event.

@apana @gpetruc   please check if there could be a relatively quick solution.

**Comment by apana** [comment]
Weird. I'll have a look.

**Pull request merged**
