### PR TITLE
Improvements for upgrade matrix (81X)

### PR DESCRIPTION
**Pull request by kpedro88**
Backport of #16665

### CODE REVIEW

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by govoni** [comment]
+1

**Comment by hengne** [comment]
+1

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by hengne** [comment]
+1

**Comment by perrozzi** [comment]
+1

**Comment by iahmad-khan** [comment]
@kpedro88 the new workflows are failing. 23621.0 , 23634.0 , 23646.0 , 23653.0 in 81x. 

https://cms-sw.github.io/relvalLogDetail.html#slc6_amd64_gcc530;CMSSW_8_1_X_2016-11-27-2300


```
GEN,SIM,ENDJOB
We have determined that this is simulation (if not, rerun cmsDriver.py with --data)
Step: GEN Spec: 
Loading generator fragment from Configuration.Generator.TenMuE_0_200_pythia8_cfi
Step: SIM Spec: 
Step: ENDJOB Spec: 
customising the process with cust_2023tilted from SLHCUpgradeSimulations/Configuration/combinedCustoms
Traceback (most recent call last):
  File "/cvmfs/cms-ib.cern.ch/2016-49/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_X_2016-11-27-2300/bin/slc6_amd64_gcc530/cmsDriver.py", line 55, in <module>
    run()
  File "/cvmfs/cms-ib.cern.ch/2016-49/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_X_2016-11-27-2300/bin/slc6_amd64_gcc530/cmsDriver.py", line 27, in run
    configBuilder.prepare()
  File "/cvmfs/cms-ib.cern.ch/2016-49/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_X_2016-11-27-2300/python/Configuration/Applications/ConfigBuilder.py", line 2192, in prepare
    self.pythonCfgCode += self.addCustomise()
  File "/cvmfs/cms-ib.cern.ch/2016-49/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_X_2016-11-27-2300/python/Configuration/Applications/ConfigBuilder.py", line 873, in addCustomise
    raise Exception("config "+f+" has no function "+fcn)
Exception: config SLHCUpgradeSimulations/Configuration/combinedCustoms has no function cust_2023tilted
```

Maye be it has problem with. https://github.com/cms-sw/cmssw/pull/16385

**Comment by makortel** [comment]
This was fixed for 90X in #16682. (feel free to backport)

**Comment by iahmad-khan** [comment]
@kpedro88 can you please make a PR for 81x ( backport of #16682 )

**Comment by kpedro88** [comment]
submitted #16781

**Pull request merged**
