### PR TITLE
Removed unused headers from GeneratorInterface/Pythia6Interface

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

The headers removed are deprecated.

#### PR validation:

Code compiles.

### CODE REVIEW

**Comment by rappoccio** [comment]
This one seems pretty safe to me, as soon as we get @cms-sw/generators-l2 signoff we can merge.

**Comment by rappoccio** [comment]
Since there are several PRs that are almost identical (see mentions) maybe we should just merge them all so we don't have 5 IB machines running in parallel with the same test?

**Comment by SiewYan** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
