### PR TITLE
Remove lumi-offset from HF LUTs

### PR DESCRIPTION
**Pull request by akhukhun**

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by mulhearn** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Comment by abdoulline** [comment]
@mmusich: may we have it finally approved (& merged) ?

**Comment by mmusich** [comment]
+1

**Comment by mmusich** [comment]
@abdoulline even if it was ORP approved seems not to have been merged. Sorry if my pending signature delayed

**Pull request merged**
