### PR TITLE
add missing dependencies in DataFormats BuildFiles

### PR DESCRIPTION
**Pull request by davidlange6**
#### PR description:

missing things identified as part of the root modules work.

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by perrotta** [comment]
+1
- Technical
- Jenkins tests pass

**Comment by vgvassilev** [comment]
Part of the meta-issue #15248

**Comment by fabiocos** [comment]
+1

@rekovic @kpedro88 please check, it looks straightforward and technical

**Comment by fabiocos** [comment]
merge

**Comment by kpedro88** [comment]
+upgrade

**Pull request merged**
