### PR TITLE
Fix for issue #12036

### PR DESCRIPTION
**Pull request by jasperlauwers**
- Added a security to the code so a mistake in the config file will give an error. 
- Fixed the mistake for VBFHToInv in the config that was causing the problem.

### CODE REVIEW

**Comment by davidlt** [comment]
ping^1

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1

**Comment by jasperlauwers** [comment]
Just noticed this PR is still open.. can it be merged?

**Comment by davidlange6** [comment]
I am cleaning up the 76x queue aside from things for analysis workflows. I'm closing this pull request, please make sure the PR is in 80x. Thanks!

**Pull request closed without merging**
