### PR TITLE
Add PFTauDiscriminator based on IP

### PR DESCRIPTION
**Pull request by azotz**
#### PR description:

The main purpose is to use this producer for the displaced tau triggers in Run3.

#### PR validation:

Code checks and runTheMatrix tests have been performed on top of CMSSW_12_4_0_pre2

The producer can be tested via:
```
cp /afs/cern.ch/user/a/azotz/public/displacedTaus/* .
cmsRun customise_hlt_12_3_0.py
```

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

This is not a backport, but a backport to 12_3_X is planned

### CODE REVIEW

**Comment by clacaputo** [comment]
@cmsbuild , please test

**Comment by azotz** [comment]
Hello @clacaputo,
are there any further steps needed from our side to progress this PR?

**Comment by clacaputo** [comment]
Hello @azotz , I'm just checking something related to `StringCutObjectSelector `

**Comment by qliphy** [comment]
+1

**Pull request merged**
