### PR TITLE
DD4hep: Ecal Preshower Algorithm Migration

### PR DESCRIPTION
**Pull request by ianna**
#### PR description:

* DDEcalPreshowerAlgo migrated to DD4hep **_ASIS_**

Note: The PR is based on https://github.com/cms-sw/cmssw/pull/27501

#### PR validation:
Screen Shot 2019-07-16 at 14 51 03
Screen Shot 2019-07-16 at 14 51 13

#### if this PR is a backport please specify the original PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
@fabiocos - if this PR goes in IBs before @kpedro88's there will be no need to change the conflicting file again.

**Comment by kpedro88** [comment]
@ianna this PR does not remove all references to 2023 files in the xml:
https://github.com/cms-sw/cmssw/blob/f471ffb8d8f97a0599fce9520f1768ad63f29e7d/Geometry/EcalCommonData/data/dd4hep/cms-ecal-geometry.xml#L44-L45

**Comment by fabiocos** [comment]
@ianna are these versions of beampipe supposed to be for Run3? In this case I suggest they are renamed to 2021. I would say so, they appears also in the scenario 2019 (could you please remind me what is this scenario supposed to be ?)

**Comment by ianna** [comment]
@fabiocos - yes, I agree, that is what I suggested to @kpedro88. However, it's not in the scope of this PR.

**Comment by ianna** [comment]
> @ianna are these versions of beampipe supposed to be for Run3? In this case I suggest they are renamed to 2021. I would say so, they appears also in the scenario 2019 (could you please remind me what is this scenario supposed to be ?)

2019 was renamed to 2021

**Comment by ianna** [comment]
> @ianna this PR does not remove all references to 2023 files in the xml:
> 
> https://github.com/cms-sw/cmssw/blob/f471ffb8d8f97a0599fce9520f1768ad63f29e7d/Geometry/EcalCommonData/data/dd4hep/cms-ecal-geometry.xml#L44-L45

@kpedro88 - the dependency is removed

**Comment by ianna** [comment]
please test

**Comment by fabiocos** [comment]
@ianna thanks, as this is a test configuration I understand the change should not be an issue in itself right?

**Comment by ianna** [comment]
> @ianna thanks, as this is a test configuration I understand the change should not be an issue in itself right?

no, it's not an issue as long as the PR does not get delayed by the changes elsewhere.

**Comment by ianna** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
