### PR TITLE
APE tool implemented, PR #10601and PR#12783 backported

### PR DESCRIPTION
**Pull request by cschomak**
PR #10601 backported to 74X:
APE tool implemented into the release
TrackerTreeGenerator (necessary for the APE tool, but might also used for other purposes) included in Alignment/TrackerAlignment
Fixes for ApeSettingAlgorithm in CommonAlignmentAlgorithm

PR #12783 backported to APE tool in 74X:
cmsStage, cmsLs, cmsRm statements replaced by xrdcp, eos ls/rm

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
please test

**Comment by cschomak** [comment]
Do these failed checks have anything to do with my code? I do not see any connection

**Comment by mmusich** [comment]
@cschomak no, sorry this slipped out of my attention

**Comment by mmusich** [comment]
@cmsbuild please test

**Comment by cschomak** [comment]
I think the PR still needs to be signed or am I wrong?

**Comment by ghellwig** [comment]
May I ask, why this has not been merged, yet?

**Comment by diguida** [comment]
@ghellwig before approving it we should see it working fine in open cycles.
It was approved in 76X as development release, but approved only for 75X back port.
Sorry for missing this: reviewing...

**Comment by diguida** [comment]
I see small differences between this PR and #10601 
* One extra blank line in `Alignment/APEEstimation/plugins/ApeEstimator.cc` (nothing serious)
* Different handling of GT in a test skim setup: https://github.com/cms-sw/cmssw/pull/10893/files#diff-9d66e5769a5f7536408c393f8434f842R121 FYI, the correct implementation is like https://github.com/cms-sw/cmssw/pull/10601/files#diff-9d66e5769a5f7536408c393f8434f842R121 where you select the GT for data re-reco used in RelVal, not a fixed GT (in your case, Prompt)
* A missing file `Alignment/CommonAlignmentProducer/python/AlignmentProducer_cff.py`, actually with 0 differences in #10601: most likely an artefact of the web GUI.

**Comment by diguida** [comment]
@cschomak I can approve this as it is, but it would be preferable if you set the correct GT in https://github.com/cms-sw/cmssw/pull/10893/files#diff-9d66e5769a5f7536408c393f8434f842R121 following https://github.com/cms-sw/cmssw/pull/10601/files#diff-9d66e5769a5f7536408c393f8434f842R121

**Comment by ghellwig** [comment]
@cschomak: If you think, that it should be in the release, can you also take care of cherry-picking your commit concerning the obsolete cms* scripts?

**Comment by cschomak** [comment]
I changed the GT and replace the cmsStage, cmsLs etc scripts as Gregor suggested

**Comment by mmusich** [comment]
please test

**Comment by diguida** [comment]
please test

**Comment by diguida** [comment]
@cschomak thanks.
The commit https://github.com/cms-sw/cmssw/commit/5c1998eb0970bdddd82b438a5a7c974263c48c6a is a back port of https://github.com/ghellwig/cmssw/commit/455f1a5721528beb7152014d7771bdad415d906f in #12783 plus the GT change. 
Can you please update the description of this PR, please?

**Comment by cschomak** [comment]
@diguida I changed the title and the description of the PR

**Comment by diguida** [comment]
+1
Back port of #10601 and https://github.com/cms-sw/cmssw/commit/455f1a5721528beb7152014d7771bdad415d906f of #12783 in https://github.com/cms-sw/cmssw/commit/5c1998eb0970bdddd82b438a5a7c974263c48c6a

**Comment by davidlange6** [comment]
+1

**Pull request merged**
