### PR TITLE
Implemented new cumulative histograms and made independent from any …

### PR DESCRIPTION
**Pull request by dinardo**
…previous(old) beamspot values

### CODE REVIEW

**Comment by dinardo** [comment]
Dear All,
I would like to stress this is rather important fix
(see recent email thread on beam spot hyper-news).
If possible I would like to push this PR through.
Many thanks and kind regards.
- Mauro.

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1
online only
(the PR is already running in prod)

**Comment by dinardo** [comment]
Hi, I was wondering why this is still open.
Were you able to merge ?
Many thanks,
- Mauro.

**Pull request closed without merging**
