### PR TITLE
MiniAOD tweaks

### PR DESCRIPTION
**Pull request by ferencek**
Code changes:
- removed unnecessary lines in the MiniAOD configuration (discussed in #8377)
- implemented in jetTools.py more robust handling of IVF modules which do not have to be re-run in PAT and MiniAOD workflows since they are already run in the standard reconstruction

### CODE REVIEW

**Comment by davidlange6** [comment]
@cmsbuild, please test

**Comment by monttj** [comment]
+1

**Comment by davidlange6** [comment]
@ferencek - i also ran into issues with this runIVF if statement - using if processName=='RECO' is fragile at best. Do you know what triggers the need for this? eg, can't the cffs be divided such that the vertexing cffs are loaded by the user when they want to rerun?

**Comment by ferencek** [comment]
@davidlange6, the main issue is that RecoBTag/Configuration/python/RecoBTag_cff.py also loads vertexing modules from RecoVertex/AdaptiveVertexFinder/python/inclusiveVertexing_cff.py so when the MiniAOD production is run, all of these vertexing modules are re-run in the unscheduled mode. This is not really needed since the secondary vertices are already produced in the standard reconstruction. In order to prevent re-running of the vertexing modules, the jetTools.py is unloading them from the process but in a way that is indeed not very robust.

Since all the vertexing modules are already run in the standard reconstruction, it would probably be best to remove loading of the vertexing modules from RecoBTag/Configuration/python/RecoBTag_cff.py @slava77, do you have any additional suggestions?

**Comment by davidlange6** [comment]
> On Mar 30, 2015, at 4:35 PM, Dinko Ferencek <notifications@github.com> wrote:
> 
> @davidlange6, the main issue is that RecoBTag/Configuration/python/RecoBTag_cff.py also loads vertexing modules from RecoVertex/AdaptiveVertexFinder/python/inclusiveVertexing_cff.py so when the MiniAOD production is run, all of these vertexing modules are re-run in the unscheduled mode. This is not really needed since the secondary vertices are already produced in the standard reconstruction. In order to prevent re-running of the vertexing modules, the jetTools.py is unloading them from the process but in a way that is indeed not very robust.
> 
> Since all the vertexing modules are already run in the standard reconstruction, it would probably be best to remove loading of the vertexing modules from RecoBTag/Configuration/python/RecoBTag_cff.py @slava77, do you have any additional suggestions?
> 

Seems RecoBTag_cff does not use any of the 4 modules defined in inclusiveVertexing_cff.py
Perhaps then its trivial to remove it. (i’m not quite sure why it has any effect as RecoBTag_cff is not loaded into the process but just imported as an object that is then used. But the other solution would then be a cff that defines all the individual modules needed for jetTools.py which then RecoBTag_cff.py uses.

**Comment by slava77** [comment]
Hi David,

IVF is needed only for BTagging. So, it's added in btagging "master"
config defining the bragging sequence.

RECO sequences are not pruned a-priori.
I don't think that decoupling what's needed and what's not needed
(pruning) RECO files driven by miniAOD needs will get us far.

The miniAOD (a-priori pruned) should import needed modules only.

Maybe I missed something in this thread and some refactoring of RecoBTag
may help.



On 3/30/15 5:07 PM, David Lange wrote:
> 
>> On Mar 30, 2015, at 4:35 PM, Dinko Ferencek <notifications@github.com> wrote:
>> 
>> @davidlange6, the main issue is that RecoBTag/Configuration/python/RecoBTag_cff.py also loads vertexing modules from RecoVertex/AdaptiveVertexFinder/python/inclusiveVertexing_cff.py so when the MiniAOD production is run, all of these vertexing modules are re-run in the unscheduled mode. This is not really needed since the secondary vertices are already produced in the standard reconstruction. In order to prevent re-running of the vertexing modules, the jetTools.py is unloading them from the process but in a way that is indeed not very robust.
>> 
>> Since all the vertexing modules are already run in the standard reconstruction, it would probably be best to remove loading of the vertexing modules from RecoBTag/Configuration/python/RecoBTag_cff.py @slava77, do you have any additional suggestions?
>> 
> 
> Seems RecoBTag_cff does not use any of the 4 modules defined in
> inclusiveVertexing_cff.py
> Perhaps then its trivial to remove it. (i’m not quite sure why it has
> any effect as RecoBTag_cff is not loaded into the process but just
> imported as an object that is then used. But the other solution would
> then be a cff that defines all the individual modules needed for
> jetTools.py which then RecoBTag_cff.py uses.
> 
> 
>> —
>> Reply to this email directly or view it on GitHub.
>> 
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cms-sw/cmssw/pull/8577#issuecomment-87716307>.
> 

-- 
***********************************************************************
 Vyacheslav (Slava) Krutelyov
 TAMU: Physics Dept Texas A&M MS4242, College Station, TX 77843-4242
 CERN: 42-R-027
 AIM/Skype: siava16              googleTalk: slava77@gmail.com
 (630) 291-5128  Cell (US)       +41 76 275 7116 Cell (CERN)

-----------------------------------------------------------------------

**Comment by ferencek** [comment]
@davidlange6, @slava77, I implemented what is hopefully a more robust handling of IVF modules.

**Comment by davidlange6** [comment]
@ferencek - great - thanks. this looks safer to me.

**Comment by ferencek** [comment]
@monttj, can you please sign again. Thanks

**Pull request merged**
