### PR TITLE
hltGetConfiguration: remove --online/--offline option

### PR DESCRIPTION
**Pull request by fwyzard**

### CODE REVIEW

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
@silviodonato @Martin-Grunewald can you check that this doesn't break anything ?

**Comment by Martin-Grunewald** [comment]
It breaks a lot of things as we use ```--offline``` which is now
```hltGetConfiguration: error: unrecognized arguments: --offline```
So we need to remove it from all scripts.

**Comment by fwyzard** [comment]
Ah, of course.

If you prefer I can try to make the old option accepted but ignored ?

.A

**Comment by Martin-Grunewald** [comment]
yes, that would be a quick way out indeed!

**Comment by davidlange6** [comment]
hi - @fwyzard - is this obsolete?

**Comment by fwyzard** [comment]
No, just on my list of things to update...

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by fwyzard** [comment]
@cmsbuild, abort test

**Comment by davidlange6** [comment]
please test

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by fwyzard** [comment]
@Martin-Grunewald can you check that this does not break any STORM scripts now ?

**Comment by fwyzard** [comment]
@cmsbuild, abort tests

**Comment by fwyzard** [comment]
found a problem with the handling of the global tags, fix is coming

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by fwyzard** [comment]
@Martin-Grunewald @silviodonato , please check :-)

**Comment by fwyzard** [comment]
I doubt the errors come from these changes, since we don't run `hltGetConfiguration ` anywhere I know of...

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
