### PR TITLE
Bugfix for cavern

### PR DESCRIPTION
**Pull request by slomeo**
Geometry 2018: Update Cavern and mb4shields for neutrons

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade

**Comment by fabiocos** [comment]
@ianna @cvuosalo @slomeo this is for special studies, that configuration was already used in productions?

**Comment by slomeo** [comment]
> @ianna @cvuosalo @slomeo this is for special studies, that configuration was already used in productions?

No, I have never used it for a production. When a (little) MC sample ,with Geo2018 (updated cavern and mb4shields) will be done, and it will be ok (now I have seen a too high background rate, perhaps because there was not a detailed cavern) I will request a central production.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
