### PR TITLE
bsunanda:Run2-gem22 Add 2017 GE11 slice (backport from 9_0_X)

### PR DESCRIPTION
**Pull request by bsunanda**

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by ianna** [comment]
@bsunanda - if it is a 2017 slice, why its definition is under PhaseII? and why numbering includes GEMs 21L and 21S? the latter would give warning messages about missing chambers.

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@ianna I moved the gem11.xml to data/Run2. I do not see where 21L/S are included in the xml file. There is no warning message while running the code

**Comment by ianna** [comment]
+1

**Comment by davidlange6** [comment]
no need for this back port.

**Pull request closed without merging**
