### PR TITLE
using HLT:@relval2016 for phase1 relvals

### PR DESCRIPTION
**Pull request by fabozzi**
Since PR  #16333 has been merged, we move to HLT:@relval2016 for phase1 relvals, as asked by TSG/Storm

@silviodonato

### CODE REVIEW

**Comment by fabozzi** [comment]
please test

**Comment by silviodonato** [comment]
Thanks Francesco. add in cc: @Martin-Grunewald  @fwyzard

**Comment by silviodonato** [comment]
The HLT steps ran without error. 
Are these errors originated by CMSSW_8_1_X_2016-10-28-1100 ?

**Comment by mmusich** [comment]
The 2017 error looks worrisome:
```
cmsRun: /build/cmsbuild/jenkins-workarea/workspace/build-any-ib/w/tmp/BUILDROOT/5807ca27a61cace36698b4e41c6310d3/opt/cmssw/slc6_amd64_gcc530/cms/cmssw-patch/CMSSW_8_1_X_2016-10-28-1100/src/Geometry/HcalTowerAlgo/src/HcalGeometry.cc:127: virtual DetId HcalGeometry::getClosestCell(const GlobalPoint&) const: Assertion `bestId != HcalDetId()' fail
```

**Comment by silviodonato** [comment]
I'm wondering how a different HLT can crash the ALCA step (step1, 2 and 3 are ok)

**Comment by mmusich** [comment]
It's not the HLT menu, imho

**Comment by davidlange6** [comment]
trigger path changes activating code that hasn’t been running and needs to be taught about the new hcal?

**Comment by makortel** [comment]
I suspect a(/the?) problem is that the 2017 ALCAReco configurations do not have `--era Run2_2017` https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-16384/16046/runTheMatrix-results/10021.0_TenMuE_0_200+TenMuE_0_200_pythia8_2017_GenSimFull+DigiFull_2017+RecoFull_2017+ALCAFull_2017+HARVESTFull_2017/step4_ALCA.py

Correct fix would be to fix these two `RecoFull`'s to `ALCAFull`
```
1829    upgradeStepDict['ALCAFull'][k] = {...
...
1836    if cust!=None : upgradeStepDict['RecoFull'][k]['--customise']=cust
1837    if era is not None: upgradeStepDict['RecoFull'][k]['--era']=era
```
https://github.com/cms-sw/cmssw/blob/CMSSW_8_1_X/Configuration/PyReleaseValidation/python/relval_steps.py#L1836
(rather obvious copy-paste mistake in #16168 when looking it now).

(On a longer term there is a lot of room to reduce copy-paste in `relval_steps.py`, IMHO)

**Comment by makortel** [comment]
Additional note (apologies if this has already been discussed/agreed elsewhere): with the addition of HLT to 2017 workflows the DQM team (@vanbesien, @dmitrijus, @rappoccio) way want to take a look of enabling the HLT DQM+validation modules in these workflows.

**Comment by mmusich** [comment]
Thanks @makortel for spotting, but doens't seem to be enough. I've retried this here https://github.com/cms-sw/cmssw/pull/16386. I suspect to work correctly needs some work on the `Calibration/HcalAlCaRecoProducers/plugins/AlCaHBHEMuonFilter.cc` module.

**Comment by davidlange6** [comment]
lets work on #16386

**Pull request closed without merging**
