### PR TITLE
Updates on GE21 online/offlineDQM plots with division on modules, a backport to 12_4_X

### PR DESCRIPTION
**Pull request by quark2**
#### PR description:

This PR provides massive updates on GE21 onlineDQM/offlineDQM plots. This work is focusing on the division of GE21 information by modules (M1-M4). It is necessary because of the electronic configuration of GE21 chambers.

It is also included that the module information is propagated to the GEM unpacker in a better way, which is done by @yeckang.

#### PR validation:

Tests are done with `cmsRun $CMSSW_RELEASE_BASE/src/DQM/Integration/python/clients/gem_dqm_sourceclient-live_cfg.py unitTest=True runNumber=361054 dataset=/ExpressPhysics/Run2022F-Express-v1/FEVT` and `runTheMatrix.py -l limited -i all --ibeos` since it makes effects on P5 and reconstruction

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

This PR is a backport of #39985 to 12_4_X.

@jshlee @watson-ij @seungjin-yang @yeckang

### CODE REVIEW

**Comment by emanueleusai** [comment]
type gem

**Comment by emanueleusai** [comment]
backport of https://github.com/cms-sw/cmssw/pull/39985

**Comment by emanueleusai** [comment]
please test

**Comment by emanueleusai** [comment]
hold

- this backport is not to be merged since it contains changes to reco. This backport is only for the deployment to DQM online systems

**Comment by micsucmed** [comment]
HI @quark2, we weren't able to merge this PR into our latest version of 12_4_X (12_4_10_patch3) given that it presents merge conflicts for the following files:
```
[0] Auto-merging DQM/GEM/plugins/GEMDAQStatusSource.cc
[0] CONFLICT (content): Merge conflict in DQM/GEM/plugins/GEMDAQStatusSource.cc
[0] Auto-merging DataFormats/GEMDigi/interface/GEMOHStatus.h
[0] CONFLICT (content): Merge conflict in DataFormats/GEMDigi/interface/GEMOHStatus.h
[0] Auto-merging DataFormats/GEMDigi/interface/GEMVFATStatus.h
[0] CONFLICT (content): Merge conflict in DataFormats/GEMDigi/interface/GEMVFATStatus.h
[0] Auto-merging DataFormats/GEMDigi/src/classes_def.xml
[0] CONFLICT (content): Merge conflict in DataFormats/GEMDigi/src/classes_def.xml
[0] Auto-merging EventFilter/GEMRawToDigi/plugins/GEMRawToDigiModule.cc
[0] CONFLICT (content): Merge conflict in EventFilter/GEMRawToDigi/plugins/GEMRawToDigiModule.cc
```
After verifying, we are already running PR [39489](https://github.com/cms-sw/cmssw/pull/39489) onto of this 12_4_X CMSSW release. This is most likely why the conflicts present while merging.

**Comment by emanueleusai** [comment]
@quark2 I believe the 12_5 and master version of https://github.com/cms-sw/cmssw/pull/39489 are merged already, so it should not be necessary

**Comment by emanueleusai** [comment]
please test

**Comment by emanueleusai** [comment]
+1

- differences in GEM DQM plots as expected

**Pull request closed without merging**
