### PR TITLE
[DQM/EcalMonitorTasks] Add MEM FE Status and Integrity Error Plots

### PR DESCRIPTION
**Pull request by alejands**
#### PR description:

During a MWGR in November 2020 (but also a few times in Run2) we noticed EcalElectronicsIds coming from the ECAL calibration stream with seemingly unphysical detector coordinates. Specifically, these were coming from the EcalIntegrityMemBlockSizeErrors collection and occurred for a number of events in runs 338624 and 338628. At least in run 338628, this was always occurring with the same unphysical coordinates:

MemBlockSizeError:
dccId: 24
towerId: 70

It turns out that towerIDs 69 and 70 correspond to the MEM boxes for most ECAL SMs. These MEM boxes also have a front-end (FE) status that was not being displayed, due to the code assuming these coordinates are unphysical.

Integrity errors for towerID 69 had been masked before not knowing that these towerIDs do have a meaning: https://github.com/cms-sw/cmssw/commit/95eed04a96ac618a285c8388001c3542a3f0445f

In this PR we now handle the two additional tower IDs and plots the FE status and integrity errors for these MEM boxes. The plots contain two bins for each SM corresponding to tower IDs 69 and 70, respectively. The plots are indexed by ECAL DCC ID, where each DCC ID corresponds to a SM. The mapping from DCC ID to SM name appears below.
```
01:EE-07  19:EB-10  37:EB+10
02:EE-08  20:EB-11  38:EB+11
03:EE-09  21:EB-12  39:EB+12
04:EE-01  22:EB-13  40:EB+13
05:EE-02  23:EB-14  41:EB+14
06:EE-03  24:EB-15  42:EB+15
07:EE-04  25:EB-16  43:EB+16
08:EE-05  26:EB-17  44:EB+17
09:EE-06  27:EB-18  45:EB+18
10:EB-01  28:EB+01  46:EE+07
11:EB-02  29:EB+02  47:EE+08
12:EB-03  30:EB+03  48:EE+09
13:EB-04  31:EB+04  49:EE+01
14:EB-05  32:EB+05  50:EE+02
15:EB-06  33:EB+06  51:EE+03
16:EB-07  34:EB+07  52:EE+04
17:EB-08  35:EB+08  53:EE+05
18:EB-09  36:EB+09  54:EE+06
```
#### PR validation:

New plots successfully generated with online ECAL DQM workflow and uploaded to a private DQM GUI without any issues.

#### Backport:

A backport of this PR to CMSSW_11_2_X has been submitted here: https://github.com/cms-sw/cmssw/pull/32481

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
@alejands the PR is adding the plot also to Offline DQM but the output is somehow nasty to read, I guess that due to the deployment PR https://github.com/dmwm/deployment/pull/1007  not yet implemented with the right plugin

But, do you want this plot in Offline too? Or just in Online?

**Comment by jfernan2** [comment]
BTW: we also need a backport to 11_2_X in order to test it at P5

**Comment by alejands** [comment]
@jfernan2 The plots are custom made compared to the rest of the ECAL DQM workflow, and the deployment PR cleans them up.

We do want this plot in Offline too. We can also go ahead and submit a backport PR for 11_2_X.

**Comment by alejands** [comment]
We have gone ahead and submitted a backport to 11_2_X here: https://github.com/cms-sw/cmssw/pull/32481

**Comment by jfernan2** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
