### PR TITLE
add 3 production workflows for premix2018

### PR DESCRIPTION
**Pull request by zhenhu**

### CODE REVIEW

**Comment by zhenhu** [comment]
please test workflow 250200.118,250202.118,250206.118

**Comment by kpedro88** [comment]
+upgrade

**Comment by zhenhu** [comment]
+1

**Comment by fabiocos** [comment]
@zhenhu is DQM excluded on purpose from these workflows? Could you please clarify why for my understanding?

**Comment by prebello** [comment]
@fabiocos 
my few percent: these are MC production workflows, aimed to mimic exactly the cmsdrivers of MccM campaigns . Therefore no DQM/harvesting outputs are applied.

**Comment by fabiocos** [comment]
@prebello thanks, so I understand that what is being tested is 1) functionality of the workflow and 2) check of the log files

**Comment by prebello** [comment]
@fabiocos yes. The content of MiniAOD and NanoAOD outputs would be checked, when necessary, by the POGs and PAGs as well. Otherwise it would be a copy of the usual relvals as well as unfriendly to computing resources.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
