### PR TITLE
move kalmanLUTs.root to cms-data external

### LINKED ISSUE #33303: Duplicate L1 data files causing cmsdist PRs to fails
Root file  `L1Trigger/L1TMuon/data/bmtf_luts/kalmanLUTs.root` added by https://github.com/cms-sw/cmssw/pull/33078  should have been updated via https://github.com/cms-data/L1Trigger-L1TMuon repository. We now have a problem that there are two files with same name in CMSSW_SEARCH_PATH ( one via CMSSW_BASE/src and other with cms data). During cmsdist and external PR tests this file is picked up from cms/data directory (and causing PR to fail https://github.com/cms-externals/evtgen/pull/2#issuecomment-810585253) and for normal cmssw PR and IB it is picked up from CMSSW_BASE/src. 

I will open a cms-data/L1Trigger-L1TMuon PR to update kalmanLUTs.root from cmssw but in future. In future, we should avoid adding any root files in cmssw.

I will also add a PR check to make sure that we do not have any duplicate data files in cmssw and cms-data

### PR DESCRIPTION
**Pull request by smuzaffar**
Fixes #33303
This fixes the issue due to duplicate kalmanLUTs.root file in cmssw and cms-data ( see #33303 ).

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test
although test should fail

**Comment by smuzaffar** [comment]
test parameters:
- pull_requests = cms-data/L1Trigger-L1TMuon#20
- disable_poison = true

**Comment by smuzaffar** [comment]
please test

**Comment by cecilecaillol** [comment]
+l1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
