### PR TITLE
fixes for parameter scan functionality

### PR DESCRIPTION
**Pull request by bendavid**
Fixes some simple, but critical issues with the lhe parameter scan functionality.
(Mainly adding a maximum value for the random seed, which otherwise can cause madgraph to crash.)

### CODE REVIEW

**Comment by bendavid** [comment]
please test

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by covarell** [comment]
+1

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
+1

**Pull request merged**
