### PR TITLE
Phase2-hgx279 Next step for V15 geometry for HGCal

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Next step for V15 geometry for HGCal (can load the parameters)

#### PR validation:

Use the runTheMatrix test workflows to test this

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@srimanob @kpedro88 Please approve this. Waiting for its integration to move to next step

**Comment by srimanob** [comment]
+Upgrade

**Comment by qliphy** [comment]
+1

**Pull request merged**
