### PR TITLE
Add PbPbHighPtJets skim for 2024 PbPb

### PR DESCRIPTION
**Pull request by cfmcginn**
#### PR description:

This PR adds a new skim for high-pT jets (pT > 300, |eta| < 2.4) saving RAW-RECO in PbPb. Should correspond to no greater than 100k events (estimate from 2018 data puts it at ~20k). To be applied to the hadronic physics PDs (i.e. not HIForward/UPCs).

@mandrenguyen 

#### PR validation:

Tested in CMSSW_14_2_X_2024-10-20-0000, compiles and appears to run when tested w/ runTheMatrix.py -l 142.0 -n -e, modifying step 3 to include the newly defined PbPbHighPtJets skim as:
```
-s RAW2DIGI,L1Reco,RECO,SKIM:PbPbHighPtJets,PAT
```
The output appears correctly sensitive to specified trigger path and threshold cuts. 

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

To be backported to 14_1_X. EDIT: Backport is now up here https://github.com/cms-sw/cmssw/pull/46514

### CODE REVIEW

**Comment by mandrenguyen** [comment]
[youyingli](https://github.com/youyingli) This is the last PR needed for PbPb data taking this year (well, it's backport).  As you suggested let's follow up with @cms-sw/pdmv-l2 how to do test these.

**Comment by mandrenguyen** [comment]
please test

**Comment by mandrenguyen** [comment]
[cfmcginn](https://github.com/cfmcginn) please proceed with a 14_1_X backport

**Comment by stahlleiton** [comment]
Should this skim be also included in the [autoSkim](https://github.com/cms-sw/cmssw/blob/master/Configuration/Skimming/python/autoSkim.py#L45) file?

**Comment by youyingli** [comment]
> Should this skim be also included in the [autoSkim](https://github.com/cms-sw/cmssw/blob/master/Configuration/Skimming/python/autoSkim.py#L45) file?

Yes, it should be added. However, #46447 also modified this line which could conflict.

**Comment by cfmcginn** [comment]
I will setup the backport. For the autoSkim line, perhaps it makes sense for me to update after https://github.com/cms-sw/cmssw/pull/46447 is merged?

**Comment by mandrenguyen** [comment]
> I will setup the backport. For the autoSkim line, perhaps it makes sense for me to update after #46447 is merged?

I think it's best to just update everything now, and we handle the merge conflicts as they arise.

**Comment by cfmcginn** [comment]
> > I will setup the backport. For the autoSkim line, perhaps it makes sense for me to update after #46447 is merged?
> 
> I think it's best to just update everything now, and we handle the merge conflicts as they arise.

Understood, will do

**Comment by cfmcginn** [comment]
Backport to 14_1_X created; PR here: https://github.com/cms-sw/cmssw/pull/46514 (also edited initial message with this info)

**Comment by mandrenguyen** [comment]
please test

**Comment by mandrenguyen** [comment]
urgent

**Comment by AdrianoDee** [comment]
+pdmv

**Comment by mandrenguyen** [comment]
+1

**Comment by mandrenguyen** [comment]
+1

**Comment by smuzaffar** [comment]
@cfmcginn  , this PR now has conflicts, can you please resolve it?

**Comment by cfmcginn** [comment]
> @cfmcginn , this PR now has conflicts, can you please resolve it?

I believe the conflict is resolved

**Comment by mandrenguyen** [comment]
+1

**Comment by AdrianoDee** [comment]
+pdmv
Failures relates to https://github.com/cms-sw/cmssw/issues/46555

**Comment by AdrianoDee** [comment]
please test with https://github.com/cms-sw/cmssw/pull/46559

**Comment by mandrenguyen** [comment]
+1

**Comment by mandrenguyen** [comment]
merge
Tests are passed, just comparisons are just slow

**Pull request merged**
