### PR TITLE
add client to razor paths (PR for 93X)

### PR DESCRIPTION
**Pull request by maojiajing**
Add client to HLT Razor paths.
To make efficiency plots automatically in dqm.
Relevant files:
DQMOffline/Trigger/python/RazorMonitor_Client_cff.py
DQMOffline/Trigger/python/SusyMonitoring_Client_cff.py
same development as PR#20462 for 92X

### CODE REVIEW

**Comment by mtosi** [comment]
@cmsbuild, please test

**Comment by maojiajing** [comment]
Hi, I fixed the include line in susy client.
Now it includes the razor client in susy client.
Local test with same development in recent CMSSW release (CMSSW_9_3_X_2017-09-14-1100):
/afs/cern.ch/user/j/jmao/work/public/releases/RazorDQM/CMSSW_9_3_X_2017-09-14-1100/src/DQM_V0001_R000302523__Global__CMSSW_X_Y_Z__RECO.root
Sorry for any inconvenience.

**Comment by davidlange6** [comment]
Closing PR as it is not needed for this release cycle. CMSSW_9_3_X is planned for use only for 2017 GEN-SIM production and HGCal TDR production.

**Comment by mtosi** [comment]
@maojiajing can you please confirm you have the PR for the master (94x, now) ?

**Comment by maojiajing** [comment]
Hello, the PR #20508 for the master (94x) is already merged.
PR#20508 for 94x/master
https://github.com/cms-sw/cmssw/pull/20508

**Comment by mtosi** [comment]
great to hear !
thanks

**Pull request closed without merging**
