### PR TITLE
relval update to fix hlt in 2017 wfs

### PR DESCRIPTION
**Pull request by hengne**
- relval update to fix hlt in 2017 wfs :
add customization function as the default, to customize the hlt modules using the 2017 pixel geometry

- add one fullsim pu workflow ttbarlepton for hlt validation

- update gen-sim input string for 2017 workflows

### CODE REVIEW

**Comment by hengne** [comment]
please test

**Comment by hengne** [comment]
+1

**Comment by silviodonato** [comment]
Let me point #16978 , that is the PR adding Eras at HLT in 81X

**Comment by mtosi** [comment]
sorry, but it is not clear to me if this PR is still needed
because, HLT has been migrated to use the Era
@hengne could you please comment on this ?
thanks a lot

**Comment by fabozzi** [comment]
Hello Mia, I did not follow this PR, but as you say I think this is no more needed. I see there is also the introduction of a new wf here, that probably should move on (with a new PR)

**Comment by mtosi** [comment]
thanks for the comment

  mia

**Pull request closed without merging**
