### PR TITLE
return valid only finite pathLength in plane crossings algorithms in TrackingTools

### PR DESCRIPTION
**Pull request by slava77**
- [first commit 5247666] properly return on failing crossing in `TECLayer::computeCrossings` 
    - a bug from 2007 https://github.com/cms-sw/cmssw/commit/8198b00b0e5f66def9d5fe8cba9c167c5901f713#diff-f972dac0360a5d1ded73517ea4daa1e9370257d7b5235d6a2619c69a6fdeeeb6R165
    - all differences in jenkins comparisons are from this commit
- [second commit 8a51ab2] add check for finite result in the return flag of `HelixForwardPlaneCrossing` and `StraightLinePlaneCrossing` (a check already exists in a more complex case in `HelixArbitraryPlaneCrossing2Order`, which is subsequently used in `HelixArbitraryPlaneCrossing`)
    - this specifically targets inifinite/NaN values observed in the issue reported in https://hypernews.cern.ch/HyperNews/CMS/get/recoDevelopment/1706.html
    - the first commit is still required though to exit properly on failed helix-plane crossing

@mtosi @vmariani 
please cross-check

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
> Reco comparison results: 884 differences found in the comparisons

Based on the differences, the differences are more likely in conversions. This is somewhat expected from both updates (directly in `TECLayer` and in the `HelixForwardPlaneCrossing` called by it or eslewhere). 

I'm investigating the impact; I suspect that the lack of return on bad values in `TECLayer` is the main reason

**Comment by slava77** [comment]
> I'm investigating the impact; I suspect that the lack of return on bad values in `TECLayer` is the main reason

I can confirm that all differences in jenkins job comparisons are from the first commit which actually adds `return` statements after bad intersection checks.
I tested locally with workflows `1000.0,4.53,136.731,136.793,136.874,10824.0`.

I can sign after I get feedback from TRK POG (@mtosi @vmariani )

**Comment by mtosi** [comment]
ciao
thanks for this PR

looking at the code, indeed, it seems that there were missing `return` (as it is done --indeed-- in https://github.com/cms-sw/cmssw/blob/52476660ae6122c3536bdc1974273e870dc46526/RecoTracker/TkDetLayers/src/TOBRod.cc#L115)

+1, and thanks !

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/33157	8a51ab2
- after the confirmation in https://github.com/cms-sw/cmssw/pull/33157#issuecomment-800257836

**Comment by qliphy** [comment]
+1

**Pull request merged**
