### PR TITLE
Create Data Format for Phase2TrackerCluster1D

### PR DESCRIPTION
**Pull request by thomaslenzi**
Added a new Data Format to describe the outer tracker clusters for Phase2.

### CODE REVIEW

**Comment by degano** [comment]
@cmsbuild please test

**Comment by thomaslenzi** [comment]
In the last commit I anticipated possible reactions regarding the choice of using edm or edmNew. I changed the files to keep only edmNew related definitions.

**Comment by degano** [comment]
@cmsbuild please test

**Comment by thomaslenzi** [comment]
Dear @degano, @nclopezo, @fratnikov, @mark-grimes,
May I get some feedback on how I can make this PR go forward?
Thank you,
Thomas

**Comment by degano** [comment]
@thomaslenzi we have a new package: DataFormats/Phase2TrackerCluster1D, first this must be assigned to one of the existing L2 categories. You can check them in cms-bot: https://github.com/cms-sw/cms-bot/blob/master/categories.py#L47. This is possibly (one of) the reason @mark-grimes didn't accept this PR yet.

**Comment by davidlange6** [comment]
Is for Reco
(this name is far too specific, but for development in 62xSLHC I don't have a strong reason to fix it now vs later)

**Comment by thomaslenzi** [comment]
Hi @davidlange6, 
I can rename the package to "Phase2TrackerCluster" if needed, but I don't think I can get less specific than this without bringing confusion in the different type of cluster data formats that exist (SiPixelClusters, SiStripClusters, ...).

**Comment by slava77** [comment]
Phase2TrackerCluster should be ok
we have a Phase2TrackerDigi so, some convention already

**Comment by thomaslenzi** [comment]
I renamed the package to "Phase2TrackerCluster", and rebased my branch to the latest IB to be in phase with the official CMSSW repository.

**Comment by mark-grimes** [comment]
merge

Categorisation for the new package has been requested in cms-sw/cms-bot#310.

**Comment by thomaslenzi** [comment]
Thank you all for your comments and feedback!

**Pull request merged**
