### PR TITLE
Test AdaBoost conversion to GBRForest (74X)

### PR DESCRIPTION
**Pull request by lgray**
Backport of #10327

### CODE REVIEW

**Comment by lgray** [comment]
@slava77 @cvuosalo This depends on an IB that is not released yet. I'll submit tests when it's out.

**Comment by lgray** [comment]
This PR also needs to wait until #10370 is merged into CMSSW 74X.

**Comment by slava77** [comment]
The alternative is to include that PR here as well and not wait

**Comment by lgray** [comment]
@slava77 this is waiting anyway for the next IB that has the weight files.

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
@cmsbuild please test
Running on the IBs with all PRs this depends on integrated.

**Comment by cvuosalo** [comment]
+1

For #10475 8bacb998f4539a606838f1049dd25bf0b68d61b6

Converting GsfElectronAlgo / Producers to use edm::GlobalCache object + GBRForest. There should be no significant change in monitored quantities, though there may be some jitter. This PR is the 74X backport of #10327, which has already been merged into 76X.

The code changes are satisfactory, and Jenkins tests against baseline CMSSW_7_4_X_2015-07-30-2300 show no significant differences, as expected. Errors in the Jenkins tests are not related to this PR.

**Comment by lgray** [comment]
@cmsbuild please wake up!

**Comment by slava77** [comment]
+1
... in case there was an errant character in https://github.com/cms-sw/cmssw/pull/10475#issuecomment-126828440

**Comment by lgray** [comment]
@davidlange6 reminder that this needs to go into 74X 
Pertinent 76X and 75X relvals check out for relevant quantities.

**Pull request merged**
