### PR TITLE
Minor updates in CSC TP configurations for B904 tests

### PR DESCRIPTION
**Pull request by dildick**
#### PR description:

@jfernan2  Recall that I recently closed https://github.com/cms-sw/cmssw/pull/34780 without merging it, because I did not want to introduce additional emulator changes while we're still investigating the performance of the Run-3 trigger primitives in the forward region for high-pT muons. Nevertheless PR https://github.com/cms-sw/cmssw/pull/34780 does have a few updates for our B904 test-stands. In particular we are testing the Run-3 firmware for ME2/1 this week (and the DMBSlot2 in currently wrong).

#### PR validation:

Code compiles. Only test configurations.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by smorovic** [comment]
+1

**Comment by rekovic** [comment]
+1

**Pull request merged**
