### PR TITLE
[Sim] Move public headers on to interface directory

### PR DESCRIPTION
**Pull request by smuzaffar**
As reported in #34718 , this PR moves headers in interface directory for `Sim*`
```
      2 src/SimCalorimetry/EcalSelectiveReadoutAlgos/src/EcalSelectiveReadout.h
      4 src/SimDataFormats/GeneratorProducts/data/hepev4.inc
      4 src/SimDataFormats/GeneratorProducts/data/stdhep.inc
      1 src/SimMuon/DTDigitizer/test/Histograms.h
      4 src/SimTracker/SiPhase2Digitizer/plugins/Phase2TrackerDigitizerFwd.h
      3 src/SimTracker/TrackAssociation/plugins/CosmicParametersDefinerForTPESProducer.h
      4 src/SimTracker/TrackAssociation/plugins/ParametersDefinerForTPESProducer.h
```

### CODE REVIEW

**Comment by smuzaffar** [comment]
code-checks

**Comment by smuzaffar** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by jfernan2** [comment]
+1

**Comment by agrohsje** [comment]
+generators
failure unrelated to the pr

**Comment by srimanob** [comment]
+Upgrade

For the upgrade part, SimTracker/SiPhase2Digitizer
FYI @cms-sw/trk-dpg-l2

**Comment by perrotta** [comment]
merge

**Pull request merged**
