### PR TITLE
Adding Phase2 tracker T25 and T26 (for IT sensor technology studies)

### PR DESCRIPTION
**Pull request by adewit**
#### PR description:

This PR introduces two new phase-2 Tracker layouts proposed with the IT sensors performance Task Force. They correspond to an updated evaluation of the area of the Inner Tracker that can be instrumented with 3D sensors (see https://indico.cern.ch/event/988838/contributions/4258167/attachments/2202703/3736635/em20210305.pdf).

This was mentioned previously in: https://github.com/cms-sw/cmssw/issues/33064#issuecomment-799341672

This introduces:
  -  T25, a Tracker based on T21, with 25x100 um2 3D pixels in Inner Tracker TBPX Layer1 and 25x100 um2 planar pixels elsewhere.
 -   T26, a Tracker based on T21, with 25x100 um2 3D pixels in Inner Tracker TBPX Layer1, 25x100 um2 planar pixels in TBPX Layer2, Layer3, Layer4 and 50x50 um2 pixels in TFPX and TEPX.

There are no changes in the OT wrt T21

T25:
Geometry scenario: 2026D80.
Workflows: 36[2|3]xx (no PU), 36[4|5]xx (PU).

T26:
Geometry scenario: 2026D81.
Workflows: 36[6|7]xx (no PU), 36[8|9]xx (PU).

#### PR validation:

- Checked XMLs make sense from Tracker design point of view
- Checked overlaps with Fireworks
- Checked workflow numbering
- Checked that workflows with scenarios D80 and D81 run smoothly with no extra errors / warnings

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Not a backport

@emiglior @mmusich @tsusa FYI

### CODE REVIEW

**Comment by adewit** [comment]
Marco's comments on an earlier version of the diff (pre- PR) were implemented, but the conversations can't be marked as resolved.

**Comment by mmusich** [comment]
test parameters:
- workflows: 36234.0, 36634.0

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by silviodonato** [comment]
urgent

**Comment by srimanob** [comment]
+Upgrade

This PR is to add new geometry, with no change on existing geometries, code.

**Comment by chayanit** [comment]
+1

**Comment by francescobrivio** [comment]
+alca
- adds new geometries (`T25,T26`) and leaves untouched the already existing ones

**Comment by silviodonato** [comment]
+operations

**Comment by jpata** [comment]
+reconstruction
- no observed reco changes
- minimal code changes in reco (`PixelCPEGeneric` and `phase2_3DPixels ` modifiers for PixelCPEGenericESProducer)

**Comment by civanch** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Comment by mmusich** [comment]
thanks @silviodonato!

**Comment by emiglior** [comment]
thanks indeed!

**Pull request merged**
