### PR TITLE
Migrate module config in DPGAnalysis to use default cfipy

### PR DESCRIPTION
**Pull request by jeongeun**
#### PR description: 
Optimization of the python configurations: Improve maintainability by cleaning up the duplicated and cloning from the default/reference configurations. 

In this PR, 6 files were changed.  Configuration/EcalTB/python/reco_application_2006h2rawdata_ecalLocalReco_cfg.py
DPGAnalysis/HcalTools/python/remoteMonitoring_LASER_era2018_cfg.py
DPGAnalysis/HcalTools/python/remoteMonitoring_LASER_era2019_cfg.py
DPGAnalysis/HcalTools/python/remoteMonitoring_LED_IterMethod_cfg.py
DPGAnalysis/HcalTools/python/remoteMonitoring_LED_era2018_cfg.py
DPGAnalysis/HcalTools/python/remoteMonitoring_LED_era2019_cfg.py

#### PR validation:
Event Content comparison check was also done and there is no change with these updates.
Tested in CMSSW_12_2_X, the basic test all passed in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html).

### CODE REVIEW

**Comment by clacaputo** [comment]
@cmsbuild please test

**Comment by jfernan2** [comment]
+1

**Comment by jpata** [comment]
+reconstruction
- technical python migration

**Comment by perrotta** [comment]
+1

**Pull request merged**
