### PR TITLE
GT Updates with inclusion of RPCLink Maps for L1T, HCAL Pedestals and widths, StripBadChannel for MCV2

### PR DESCRIPTION
**Pull request by arunhep**
# Summary of changes in Global Tags 
 
## RunI simulation 
 
   * **RunI Heavy Ions scenario** : [94X_mcRun1_HeavyIon_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_mcRun1_HeavyIon_v1) as [94X_mcRun1_HeavyIon_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_mcRun1_HeavyIon_v0) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_mcRun1_HeavyIon_v1/94X_mcRun1_HeavyIon_v0): 
      * update of RPC Link maps needed for L1T

   * **RunI Ideal scenario** : [94X_mcRun1_design_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_mcRun1_design_v1) as [94X_mcRun1_design_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_mcRun1_design_v0) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_mcRun1_design_v1/94X_mcRun1_design_v0): 
      * update of RPC Link maps needed for L1T

   * **RunI Proton-Lead scenario** : [94X_mcRun1_pA_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_mcRun1_pA_v1) as [94X_mcRun1_pA_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_mcRun1_pA_v0) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_mcRun1_pA_v1/94X_mcRun1_pA_v0): 
      * update of RPC Link maps needed for L1T

   * **RunI Realistic scenario** : [94X_mcRun1_realistic_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_mcRun1_realistic_v1) as [94X_mcRun1_realistic_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_mcRun1_realistic_v0) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_mcRun1_realistic_v1/94X_mcRun1_realistic_v0): 
      * update of RPC Link maps needed for L1T

## RunII simulation 
 
   * **RunII Asymptotic scenario** : [94X_mcRun2_asymptotic_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_mcRun2_asymptotic_v0) as [93X_mcRun2_asymptotic_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/93X_mcRun2_asymptotic_v2) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_mcRun2_asymptotic_v0/93X_mcRun2_asymptotic_v2): 
      * update of RPC Link maps needed for L1T

   * **RunII CRAFT scenario** : [94X_mcRun2cosmics_startup_deco_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_mcRun2cosmics_startup_deco_v0) as [93X_mcRun2cosmics_startup_deco_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/93X_mcRun2cosmics_startup_deco_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_mcRun2cosmics_startup_deco_v0/93X_mcRun2cosmics_startup_deco_v1): 
      * update of RPC Link maps needed for L1T

   * **RunII Heavy Ions scenario** : [94X_mcRun2_HeavyIon_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_mcRun2_HeavyIon_v0) as [93X_mcRun2_HeavyIon_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/93X_mcRun2_HeavyIon_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_mcRun2_HeavyIon_v0/93X_mcRun2_HeavyIon_v1): 
      * update of RPC Link maps needed for L1T

   * **RunII Ideal scenario** : [94X_mcRun2_design_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_mcRun2_design_v0) as [93X_mcRun2_design_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/93X_mcRun2_design_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_mcRun2_design_v0/93X_mcRun2_design_v1): 
      * update of RPC Link maps needed for L1T

   * **RunII Proton-Lead scenario** : [94X_mcRun2_pA_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_mcRun2_pA_v0) as [93X_mcRun2_pA_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/93X_mcRun2_pA_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_mcRun2_pA_v0/93X_mcRun2_pA_v1): 
      * update of RPC Link maps needed for L1T

   * **RunII Startup scenario** : [94X_mcRun2_startup_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_mcRun2_startup_v0) as [93X_mcRun2_startup_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/93X_mcRun2_startup_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_mcRun2_startup_v0/93X_mcRun2_startup_v1): 
      * update of RPC Link maps needed for L1T

## RunI data 
 
   * **RunI HLT processing** : [94X_dataRun2_HLT_frozen_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_dataRun2_HLT_frozen_v3) as [94X_dataRun2_HLT_frozen_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_dataRun2_HLT_frozen_v2) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_dataRun2_HLT_frozen_v3/94X_dataRun2_HLT_frozen_v2): 
      * update of RPC Link maps needed for L1T

   * **RunI Offline processing** : [94X_dataRun2_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_dataRun2_v2) as [94X_dataRun2_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_dataRun2_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_dataRun2_v2/94X_dataRun2_v1): 
      * update of RPC Link maps needed for L1T

## RunII data 
 
   * **RunII HLTHI processing** : [94X_dataRun2_HLTHI_frozen_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_dataRun2_HLTHI_frozen_v2) as [94X_dataRun2_HLTHI_frozen_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_dataRun2_HLTHI_frozen_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_dataRun2_HLTHI_frozen_v2/94X_dataRun2_HLTHI_frozen_v1): 
      * update of RPC Link maps needed for L1T

   * **RunII HLT relval processing** : [94X_dataRun2_HLT_relval_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_dataRun2_HLT_relval_v2) as [94X_dataRun2_HLT_relval_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_dataRun2_HLT_relval_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_dataRun2_HLT_relval_v2/94X_dataRun2_HLT_relval_v1): 
      * update of RPC Link maps needed for L1T

   * **RunII Offline processing** : [94X_dataRun2_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_dataRun2_v2) as [94X_dataRun2_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_dataRun2_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_dataRun2_v2/94X_dataRun2_v1): 
      * update of RPC Link maps needed for L1T

   * **RunII Offline relval processing** : [94X_dataRun2_relval_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_dataRun2_relval_v3) as [94X_dataRun2_relval_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_dataRun2_relval_v2) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_dataRun2_relval_v3/94X_dataRun2_relval_v2): 
      * update of RPC Link maps needed for L1T

   * **RunII Prompt processing** : [94X_dataRun2_PromptLike_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_dataRun2_PromptLike_v3) as [94X_dataRun2_PromptLike_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_dataRun2_PromptLike_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_dataRun2_PromptLike_v3/94X_dataRun2_PromptLike_v1): 
      * update of RPC Link maps needed for L1T

   * **RunI HLT processing** : [94X_dataRun2_HLT_frozen_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_dataRun2_HLT_frozen_v3) as [94X_dataRun2_HLT_frozen_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_dataRun2_HLT_frozen_v2) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_dataRun2_HLT_frozen_v3/94X_dataRun2_HLT_frozen_v2): 
      * update of RPC Link maps needed for L1T

## Upgrade 
 
   * **PhaseII realistic scenario** : [94X_upgrade2023_realistic_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_upgrade2023_realistic_v0) as [93X_upgrade2023_realistic_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/93X_upgrade2023_realistic_v2) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_upgrade2023_realistic_v0/93X_upgrade2023_realistic_v2): 
      * update of RPC Link maps needed for L1T
      * update of SiStrip Bad channel tag : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3281.html
      * update of HCAL Electronics map : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3277.html

   * **PhaseI 2018 cosmics scenario** : [94X_upgrade2018cosmics_realistic_deco_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_upgrade2018cosmics_realistic_deco_v1) as [94X_upgrade2018cosmics_realistic_deco_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_upgrade2018cosmics_realistic_deco_v0) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_upgrade2018cosmics_realistic_deco_v1/94X_upgrade2018cosmics_realistic_deco_v0): 
      * update of RPC Link maps needed for L1T
      * update of SiStrip Bad channel tag : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3281.html

   * **PhaseI 2018 design scenario** : [94X_upgrade2018_design_IdealBS_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_upgrade2018_design_IdealBS_v2) as [94X_upgrade2018_design_IdealBS_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_upgrade2018_design_IdealBS_v2) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_upgrade2018_design_IdealBS_v2/94X_upgrade2018_design_IdealBS_v2): 
      * update of RPC Link maps needed for L1T

   * **PhaseI 2018 realistic scenario** : [94X_upgrade2018_realistic_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_upgrade2018_realistic_v2) as [94X_upgrade2018_realistic_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_upgrade2018_realistic_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_upgrade2018_realistic_v2/94X_upgrade2018_realistic_v1): 
      * update of RPC Link maps needed for L1T
      * update of SiStrip Bad channel tag : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3281.html

## 2017_MC 
 
   * **PhaseI 2017 cosmics peak scenario** : [94X_mc2017cosmics_realistic_peak_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_mc2017cosmics_realistic_peak_v1) as [94X_mc2017cosmics_realistic_peak_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_mc2017cosmics_realistic_peak_v0) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_mc2017cosmics_realistic_peak_v1/94X_mc2017cosmics_realistic_peak_v0): 
      * update of HCAL Pedestals, Pedestal widths and QIE : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3265.html
      * update of SiStrip Bad channel tag : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3281.html
      * update of RPC maps needed for L1T

   * **PhaseI 2017 cosmics scenario** : [94X_mc2017cosmics_realistic_deco_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_mc2017cosmics_realistic_deco_v1) as [94X_mc2017cosmics_realistic_deco_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_mc2017cosmics_realistic_deco_v0) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_mc2017cosmics_realistic_deco_v1/94X_mc2017cosmics_realistic_deco_v0): 
      * update of HCAL Pedestals, Pedestal widths and QIE : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3265.html
      * update of SiStrip Bad channel tag : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3281.html
      * update of RPC maps needed for L1T

   * **PhaseI 2017 design scenario** : [94X_mc2017_design_IdealBS_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_mc2017_design_IdealBS_v2) as [94X_mc2017_design_IdealBS_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_mc2017_design_IdealBS_v0) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_mc2017_design_IdealBS_v2/94X_mc2017_design_IdealBS_v0): 
      * update of HCAL Pedestals, Pedestal widths and QIE : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3265.html
      * update of RPC maps needed for L1T
      * update of Jet Probability calibration for b-tagging

   * **PhaseI 2017 realistic scenario** : [94X_mc2017_realistic_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_mc2017_realistic_v2) as [94X_mc2017_realistic_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_mc2017_realistic_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_mc2017_realistic_v2/94X_mc2017_realistic_v1): 
      * update of HCAL Pedestals, Pedestal widths and QIE : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3265.html
      * update of RPC maps needed for L1T
      * update of SiStrip Bad channel tag : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3281.html

### CODE REVIEW

**Comment by arunhep** [comment]
please test

**Comment by arunhep** [comment]
attn @rekovic

**Comment by arunhep** [comment]
please test

**Comment by rekovic** [comment]
@arunhep Thanks.

**Comment by arunhep** [comment]
+1

**Comment by davidlange6** [comment]
hi @arunhep - is the increase in EE hits for 2017 PU MC somehow expected?

**Comment by arunhep** [comment]
@davidlange6 I checked 25202 workflow and could not see a difference in EE directory. can you point me to the distributions where you see differences. Thanks.

**Comment by davidlange6** [comment]
Right - thats a 2016 workflow.look at 10224

**Comment by arunhep** [comment]
@davidlange6 are you talking about differences here? https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_9_4_X_2017-10-05-2300+20758/22925/10024.0_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2017_GenSimFull+DigiFull_2017+RecoFull_2017+ALCAFull_2017+HARVESTFull_2017/EcalEndcap.html

I can try to run on more events and see if the differences are of statistical nature only.

**Comment by davidlange6** [comment]
I was more focused on physics plots - eg 

https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_9_4_X_2017-10-05-2300+20758/22925/validateJR/all_OldVSNew_TTbar13TeVPU2017wf10224p0/all_OldVSNew_TTbar13TeVPU2017wf10224p0c_EcalRecHitsSorted_ecalRecHit_EcalRecHitsEE_RECO_obj_obj_energy.png

**Comment by arunhep** [comment]
@davidlange6 
trying to run runTheMatrix.py -l 10024 --command='--conditions 94X_mc2017_realistic_v1 -n 100' to get the reference plots for more events and would like to repeat this with target GT as well. 
Step1 is stuck and not working. This has been the case since yesterday.

**Comment by davidlange6** [comment]
that command works ok for me (step2 is running now). What does "stuck" mean exactly?

**Comment by arunhep** [comment]
@davidlange6 I do have the root files now with 100 events for both reference and new GT.
Could you please tell how can I make plots like : https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_9_4_X_2017-10-05-2300+20758/22925/validateJR/all_OldVSNew_TTbar13TeVPU2017wf10224p0/

**Comment by arunhep** [comment]
@slava77 Can you please point me to tool which makes plots like this? I want to make some plots with more statistics.
: https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_9_4_X_2017-10-05-2300+20758/22925/validateJR/all_OldVSNew_TTbar13TeVPU2017wf10224p0/

**Comment by franzoni** [comment]
hello @davidlange6 @arunhep 
this plot

 cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_9_4_X_2017-10-05-2300+20758/22925/validateJR/all_OldVSNew_TTbar13TeVPU2017wf10224p0/all_OldVSNew_TTbar13TeVPU2017wf10224p0c_EcalRecHitsSorted_ecalRecHit_EcalRecHitsEE_RECO_obj_obj_energy.png

 from the same set as https://github.com/cms-sw/cmssw/pull/20758#issuecomment-335105580

indicates that different events are being used
between the reference and the target plots (Not sure what triggers that change); both EB and EE sorted collection rechit size are smaller.

**Comment by arunhep** [comment]
running over 100 events for wf 10024 with reference and target GT I got the following plots of rechit energy spectrums for EE- and EE+. They look very much compatible.

[RecHit_Energy_EEminus.pdf](https://github.com/cms-sw/cmssw/files/1373677/RecHit_Energy_EEminus.pdf)

[RecHit_Energy_EEplus.pdf](https://github.com/cms-sw/cmssw/files/1373676/RecHit_Energy_EEplus.pdf)

**Comment by davidlange6** [comment]
+1

thanks for the checks

**Pull request merged**
