### PR TITLE
Validation/Geometry: Add reference plots to Material Budget test

### PR DESCRIPTION
**Pull request by vargasa**
Add reference plots to Material Budget @cmsbuild test as discussed previously https://github.com/cms-sw/cmssw/pull/25133#issuecomment-437490838

### CODE REVIEW

**Comment by andrius-k** [comment]
please test

**Comment by cvuosalo** [comment]
+1

**Comment by andrius-k** [comment]
+1

**Comment by fabiocos** [comment]
@vargasa looking at https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-25397/31948/materialBudgetTrackerPlots/ the reference files are shown, but the new files produced are not, their path does not seem correct in the html

**Comment by vargasa** [comment]
@fabiocos Good catch. It actually requires https://github.com/cms-sw/cmssw/pull/25382 to be merged first (and possibly to rerun the test) as some of the files were renamed there

**Comment by fabiocos** [comment]
hold

pending the integration of #25382

**Comment by fabiocos** [comment]
unhold

**Comment by fabiocos** [comment]
please test

**Comment by vargasa** [comment]
For some reason it looks like https://github.com/cms-sw/cmssw/pull/25382 was not applied by the time of the test:

https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-25397/32032/materialBudgetTrackerPlots/Tracker_l_vs_z_vs_R_bw.png

When #25382 renamed the file to:

https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-25382/32012/materialBudgetTrackerPlots/Tracker_l_vs_z_vs_R_Extended2017Plan1_bw.png

Which is the one that is being linked in the file (as a relative path):

```
<img class="PullRequest" src="Tracker_l_vs_z_vs_R_Extended2017Plan1_bw.png" width="1000"/>
```

@fabiocos could we `please test` it again?

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
+1

the materia; budget plots are correctly shown. @vargasa nice piece of work!

**Comment by vargasa** [comment]
> nice piece of work!
That's because it comes from all of us ;)

**Pull request merged**
