### PR TITLE
HCAL: update of DPGAnalysis/HcalTools for 2023 Run3

### PR DESCRIPTION
**Pull request by zhokin2**
Concerning RMT and CMT. These are mostly semi-privately run macros. We use remote monitoring tool(RMT) for analysis of local hcal data to see suspesion channels. In framework of RMT the phi-symmetry monitoring(PSM) is also available. PSM is developed for global runs to facilitate calibration of hcal data by method of moments and iterative method. CMT - certification monitoring tool is developed to facilitate certification of hcal data. This tool analyses in details behaviour of estimators as function of lumi-section. This tool produces as plots and tables. These information is presenting in dedicated sites for analysis by certification experts.

CMT(Alexander Zhokin): added graphs of charge and time correlation relative to GlobalRMT,
this applies to common code and macros;
tiny update to condor related scripts;
see examples here:
https://cms-conddb.cern.ch/eosweb/hcal/HcalRemoteMonitoring/GlobalRMT/GLOBAL_362596/HE_Tile.html

RMT(Olga Kodolova): update on scripts to run crontab using local runs of 
type MIX_LED and MIX_PEDESTAL;
see examples here:
https://cms-hcal-dpg.web.cern.ch/cms-hcal-dpg/HcalRemoteMonitoring/RMT/MIXED_LED_363217/MAP.html

talk of Olga Kodolova on calibration meeting in Sep. 2022:
https://indico.cern.ch/event/1195494/contributions/5025090/attachments/2504140/4302195/Monitoring.pdf

my talk on HCAL DPG meeting in Nov. 2022:
https://indico.cern.ch/event/1082970/contributions/4565247/attachments/2328302/3966806/HCAL-DPG-Workshop2021.pdf

#### PR validation:

scram build code-checks

scram build code-format

scram b

the CMT, RMT and PSM tests were done locally and with use of cms-sites :

https://cms-conddb.cern.ch/eosweb/hcal/HcalRemoteMonitoring/RMT
https://cms-conddb.cern.ch/eosweb/hcal/HcalRemoteMonitoring/CMT
https://cms-conddb.cern.ch/eosweb/hcal/HcalRemoteMonitoring/GlobalRMT
https://cms-conddb.cern.ch/eosweb/hcal/HcalRemoteMonitoring/GlobalPSM
https://cms-conddb.cern.ch/eosweb/hcal/HcalRemoteMonitoring/ALCARECOPSM
https://cms-conddb.cern.ch/eosweb/hcal/HcalRemoteMonitoring/IMPSM  -->

### CODE REVIEW

**Comment by zhokin2** [comment]
some files to be removed...

**Comment by emanueleusai** [comment]
type hcal

**Comment by emanueleusai** [comment]
please test

**Comment by emanueleusai** [comment]
+1

**Comment by perrotta** [comment]
The code is rather convolute, and the warnings issued by the static analyzer may point to some possible fix/improvement to DPGAnalysis/HcalTools/plugins/CMTRawAnalyzer.cc
In any case, these are mostly private scripts intended for HCAL monitoring. Provided @cms-sw/hcal-dpg-l2 confirm that they are good as such, this PR can be merged in CMSSW

**Comment by abdoulline** [comment]
@perrotta   Hi Andrea,  I suppose so. 
I mean Alexandr  (@zhokin2) certainly needs to look at the warnings 
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-2364a3/30349/llvm-analysis -> 
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-2364a3/30349/llvm-analysis/runStaticChecks.log
may be just "a posteriori" ?

**Comment by perrotta** [comment]
Thank you @abdoulline
Sure, improvements are welcome in new possible PRs. Before adding 7k lines of new code to CMSSW I just wanted to get confirmed that this was done in agreement with the HCAL DPG. As far as I understand this is the case: fixes and adjustments can get provided in a followup PR.

**Comment by perrotta** [comment]
+1

**Pull request merged**
