### PR TITLE
bsunanda:Run2-hcx70 Backport PR 13491(scenario with new HCAL TP)

### PR DESCRIPTION
**Pull request by bsunanda**
Additional scenario allowing new HCAL Trigger Primitive keeping 2015 layout of HCAL readout channels

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@ianna @davidlange6 please take a look at this PR for 8_0_X. If possible it be included in 8_0_1.

**Comment by ianna** [comment]
+1

**Comment by abdoulline** [comment]
@davidlange6  
may we get it in 800p3?

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by ianna** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
