### PR TITLE
Run3-alca196 Collapse .h and .cc files in DQMOffline/CalibCalo and reorganize the files

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Collapse .h and .cc files in DQMOffline/CalibCalo and reorganize the files

#### PR validation:

Use the runTheMatrix test workflows 

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@qliphy @perrotta @smuzaffar These are spurious failures. If this happens in all test scenarios the corresponding workflows should not be present in the testing. Please take care of this

**Comment by smuzaffar** [comment]
please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by jfernan2** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
