### PR TITLE
Clean up CSCRawToDigi for Run-3 

### PR DESCRIPTION
**Pull request by dildick**
#### PR description:

- Remaining header files in src/ were moved to interface/
- Very old CSC cabling maps in python/ were removed
- Configurations in test/ were consolidated into `testCSCDigi2Raw_cfg.py` for Run-3
- Old doc/ file was deleted
- Header guards according to CMS style

#### PR validation:

Code compiles

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

FYI @ptcox, @barvic: after this PR we should start putting in the pieces for the GEM data and Run-3 CSC CLCTs and LCTs.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by dildick** [comment]
@slava77 Not sure why `scram b vclean && BUILD_LOG=yes scram b -k -j 16` did not report this last time...

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by perrotta** [comment]
@dildick , can you post here some instruction about how to run the new test config testCSCDigi2Raw_cfg.py?

**Comment by dildick** [comment]
@perrotta I'll add a README file.

**Comment by dildick** [comment]
@perrotta See my last commit for an example.

**Comment by perrotta** [comment]
> @perrotta See my last commit for an example.

Thank you @dildick , I'll give it a try

**Comment by dildick** [comment]
@ptcox @barvic Would you have time to try out `testCSCDigi2Raw_cfg.py`? Please let me know if there is any functionality that I should add. Thanks!

**Comment by dildick** [comment]
@perrotta Let me know if you found the new configuration useful, or if anything should be added.

**Comment by ptcox** [comment]
Hi Sven,

This looks good to me. I am not set up to try it, I'm afraid. The last 
time I messed with these files was to implement 'consumes', and all I 
did then was made sure they'd compile and build.

Tim

**Comment by perrotta** [comment]
> @perrotta Let me know if you found the new configuration useful, or if anything should be added.

@dildick yes, I was able to run the configuration following your recipe (thank you), and it ended up correctly.
I am ready to sign this PR for reco: I was just wating in case @ptcox or @barvic suggest adding anything to that script, as you asked them [previously](https://github.com/cms-sw/cmssw/pull/31363#issuecomment-689152286) in this thread. Otherwise, this PR is already fine for me.

**Comment by perrotta** [comment]
Ok, message from Tim arrived while I was writing...
Going to sign for reco now, then

**Comment by perrotta** [comment]
+1
- Clean up of the code and new monitoring scripts were provided as intended
- Jenkins tests pass and show no differences in reco (or any other) outputs

**Comment by silviodonato** [comment]
+1

**Pull request merged**
