### PR TITLE
Adding label HLT for PFCalibrationRcd

### PR DESCRIPTION
**Pull request by mmusich**
# Summary of Changes in the GT
## RunII simulation
- **RunII Ideal scenario** : [76X_mcRun2_design_v11](https://cms-conddb.cern.ch/browser/#list/Prod/gts/76X_mcRun2_design_v11) as [76X_mcRun2_design_v10](https://cms-conddb.cern.ch/browser/#list/Prod/gts/76X_mcRun2_design_v10) with the following [changes](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/76X_mcRun2_design_v11/76X_mcRun2_design_v10):  
  - updated Preshower pedestals as per pedestal run in low gain taken in Run2015D
  - updated Preshower Zero suppression thresholds with 6 ADC
- **RunII Asymptotic scenario** : [76X_mcRun2_asymptotic_v11](https://cms-conddb.cern.ch/browser/#list/Prod/gts/76X_mcRun2_asymptotic_v11) as [76X_mcRun2_asymptotic_v10](https://cms-conddb.cern.ch/browser/#list/Prod/gts/76X_mcRun2_asymptotic_v10) with the following [changes](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/76X_mcRun2_asymptotic_v11/76X_mcRun2_asymptotic_v10): 
  - updated Preshower bad channels as per Run2015D
  - updated Preshower pedestals as per pedestal run in low gain taken in Run2015D
  - updated Preshower Zero suppression thresholds with 6 ADC
- **RunII Startup scenario** : [76X_mcRun2_startup_v11](https://cms-conddb.cern.ch/browser/#list/Prod/gts/76X_mcRun2_startup_v11) as [76X_mcRun2_startup_v10](https://cms-conddb.cern.ch/browser/#list/Prod/gts/76X_mcRun2_startup_v10) with the following [changes](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/76X_mcRun2_startup_v11/76X_mcRun2_startup_v10): 
  - updated Preshower bad channels as per Run2015D
  - updated Preshower pedestals as per pedestal run in low gain taken in Run2015D
  - updated Preshower Zero suppression thresholds with 6 ADC
- **RunII Heavy Ions scenario** : [76X_mcRun2_HeavyIon_v11](https://cms-conddb.cern.ch/browser/#list/Prod/gts/76X_mcRun2_HeavyIon_v11) as [76X_mcRun2_HeavyIon_v10](https://cms-conddb.cern.ch/browser/#list/Prod/gts/76X_mcRun2_HeavyIon_v10) with the following [changes](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/76X_mcRun2_HeavyIon_v11/76X_mcRun2_HeavyIon_v10): 
  - updated Preshower bad channels as per Run2015D
  - updated Preshower pedestals as per pedestal run in low gain taken in Run2015D
  - updated Preshower Zero suppression thresholds with 6 ADC
## RunI data
- **RunI Offline processing** : [76X_dataRun1_v10](https://cms-conddb.cern.ch/browser/#list/Prod/gts/76X_dataRun1_v10) as [76X_dataRun1_v9](https://cms-conddb.cern.ch/browser/#list/Prod/gts/76X_dataRun1_v9) with the following [changes](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/76X_dataRun1_v10/76X_dataRun1_v9): 
  - added a label for PF hadron calibration specific for HLT usage.
## RunII data
- **RunII Offline processing** : [76X_dataRun2_v10](https://cms-conddb.cern.ch/browser/#list/Prod/gts/76X_dataRun2_v10) as [76X_dataRun2_v9](https://cms-conddb.cern.ch/browser/#list/Prod/gts/76X_dataRun2_HLT_v9) with the following [changes](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/76X_dataRun2_v10/76X_dataRun2_v9): 
  - added a label for PF hadron calibration specific for HLT usage
## Upgrade
- **PhaseI design scenario** : [76X_upgrade2017_design_v7](https://cms-conddb.cern.ch/browser/#list/Prod/gts/76X_upgrade2017_design_v7) as [76X_upgrade2017_design_v6](https://cms-conddb.cern.ch/browser/#list/Prod/gts/76X_upgrade2017_design_v6) with the following [changes](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/76X_upgrade2017_design_v7/76X_upgrade2017_design_v6): 
  - updated Preshower bad channels as per Run2015D
  - updated Preshower pedestals as per pedestal run in low gain taken in Run2015D
  - updated Preshower Zero suppression thresholds with 6 ADC  

Needed for #12100 to pass `addOn` tests

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
+1

**Comment by diguida** [comment]
please acknowledge changes

**Comment by mmusich** [comment]
@cmsbuild please acknowledge changes

**Comment by diguida** [comment]
please test

**Comment by mmusich** [comment]
@cmsbuild please test

**Comment by mmusich** [comment]
@davidlange6 we have recycled the backport of #12109 to include the (hopefully) final version of the MC GT including the fix in the ES.

**Comment by diguida** [comment]
fixed the synchronisation type. This tests that the checks in the code *do* work @ggovi

**Comment by diguida** [comment]
please test

**Comment by diguida** [comment]
please test
Frontier caches were still not picking the right value.

**Comment by mmusich** [comment]
is this the error in the tests?

```
----- Begin Fatal Exception 28-Oct-2015 09:48:16 CET-----------------------
An exception of category 'FileReadError' occurred while
   [0] Calling InputSource::readFile_
   [1] Opening DQM Root file
Exception Message:
Input file file:dqm_missing.root appears to be corrupted since it does not have the proper internal structure.
 Check to see if the file was closed properly.
----- End Fatal Exception -------------------------------------------------
```
doesn't seem related to this PR

**Comment by davidlange6** [comment]
seems like it should be a glitch..

**Comment by fwyzard** [comment]
@davidlange6 just let me know if I should rebase this on top of CMSSW_7_6_X and/or update it to #12114 .

**Comment by mmusich** [comment]
please test

**Comment by davidlange6** [comment]
@slava77, @cvuosalo - this may be of interest for your checks

**Comment by davidlange6** [comment]
@mmusich @diguida - could you confirm this is the sort of change expected? (smaller on the high level objects)

https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_7_6_X_2015-10-27-2300+12114/10951/validateJR/all_OldVSNew_TTbarPUwf50202p0/all_OldVSNew_TTbarPUwf50202p0c_log10EcalRecHitsSorted_ecalPreshowerRecHit_EcalRecHitsES_RECO_obj_obj_energy.png

**Comment by mmusich** [comment]
+1

**Comment by mmusich** [comment]
Hi @davidlange6, yes it's expected there were substantial changes in the PreShower digitization conditions to allow better data/mc comparison. Let me point the Ecal DPG to the comparison as well. @emanueledimarco @shervin86

**Comment by mmusich** [comment]
For reference [Talk at AlCa Meeting Oct 26th](https://indico.cern.ch/event/368363/contribution/2/attachments/1176606/1701314/AlCaDB-v8.pdf)

**Comment by davidlange6** [comment]
ok - I’ll merge once we see an Ecal DPG confirmation (even if its quite late to be introducing such macroscopic changes)

**Comment by diguida** [comment]
@davidlange6 clarification on the commits: 

* https://github.com/mmusich/cmssw/commit/3c2dbc7937adaa4bc2eedb4030617126a0902842 is already merged as it was cherry picked by #12100 in https://github.com/fwyzard/cmssw/commit/cb1273cd198da985834965d59356c472b54e6e96.

* https://github.com/mmusich/cmssw/commit/bee66c2e63f42f434e9cd95740d37c49a7e6ffef has been cherry picked by #12168 https://github.com/diguida/cmssw/commit/662a6ccc62f2d7ed543bffc0560ae754a0b78079 

As soon as @emanueledimarco and @shervin86 confirm this is expected behaviour, we can supersede this one and merge #12168 (as it contains also #12095 plus the fix of the snapshot time).

**Comment by emanueledimarco** [comment]
@diguida @cmkuo @shervin86 (moving a private discussion here)
I was expecting that, based on the plots shown by Fabrice earlier, the cleaning removes the 
bad rechits which populated the low energy shoulder of the distribution, so the change should go in the opposite direction (increasing the energy). Isn't it?

**Comment by mmusich** [comment]
@emanueledimarco this PR is closed, please move the discussion to #12168

**Pull request closed without merging**
