### PR TITLE
 [14_2_X] Improve TICL Association Map and update TICL event content

### PR DESCRIPTION
**Pull request by felicepantaleo**
backport of https://github.com/cms-sw/cmssw/pull/46700 to 14_2_X needed to include bug fixes to HGCal validation.

### CODE REVIEW

**Comment by felicepantaleo** [comment]
@cmsbuild please test

**Comment by felicepantaleo** [comment]
ignore tests-rejected with ib-failure

**Comment by jfernan2** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by antoniovagnerini** [comment]
+dqm

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
