### PR TITLE
[PPS] Timing detectors tracks window reduced to 25 ns in lite tracks format

### PR DESCRIPTION
**Pull request by forthommel**
#### PR description:

The size of the time slice for tracks in PPS diamond timing detectors is reduced to the one 25 ns window of interest at the `miniAOD` lite data format level.

#### PR validation:

Compiles, and runs for the 2017-2018 periods where PPS diamond were in place and calibrated.

#### if this PR is a backport please specify the original PR: N/A

Before submitting your pull requests, make sure you followed this checklist:
- [x] verify that the PR is really intended for the chosen branch
- [x] verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- [x] verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by forthommel** [comment]
Sorry, thanks to the `code-format` this PR went from a very simple and direct fix to a huge coding convention change...

**Comment by forthommel** [comment]
Reminder: my original proposal was 93faf6f57e29893627058e6b48d05d19d129ef19

**Comment by perrotta** [comment]
please test

**Comment by slava77** [comment]
@forthommel 
the comparisons came back with no differences.
Should this be tested on more event to be able to notice a difference?
Some quantified expected change would be nice to see (better be in the PR description as well).

**Comment by slava77** [comment]
> The size of the time slice for tracks in PPS diamond timing detectors is reduced to the one 25 ns window of interest at the `miniAOD` lite data format level.

please add a link to some slides to justify this selection.
Is the new selection implying that the job is running on a newly calibrated data (106X release reco inputs)?

Would this +/-12.5 ns selection still work for the data made in earlier releases (e.g. the original Run2 reco, 80X , 94X, or 102X)? If no, some appropriate modifiers should be applied to keep the right selection.

**Comment by slava77** [comment]
On 5/8/19 7:16 AM, Laurent Forthomme wrote:
> Sorry for the radio silence, I am currently busy with another project
> these days. You mean there is a possibility this lite tracks collection
> producer will be re-ran in the future with legacy releases?

yes, it is quite possible.

> track timing calculation was introduced with #26327 (previously
CTPPSDiamondLocalTrack input collection had t=0).

the cut is applied on t + OOT*25.
Is the OOT unchanged by the calibrations?

Should we expect more or less events passing without the calibration
applied (i.e
with the cut applied to "0 + OOT*25" as would be read from the older data) ?

> see e.g. in slide 5 of this AlCaDB presentation).

from this and perhaps p4 I would conclude that the proposed cut is going
to be safe for all data, even uncalibrated.
Please confirm (if confirmed, this PR can just be signed as is).

**Comment by slava77** [comment]
it looks like github.com is continuing to go crazy
my last comment from 30 mins ago is appearing earlier than my comment from 5 hours ago
https://github.com/cms-sw/cmssw/pull/26607#issuecomment-490515821

I'm re-quoting it here for a more linear reading



>> On 5/8/19 7:16 AM, Laurent Forthomme wrote: Sorry for the radio silence, I am currently busy with another project these days. You mean there is a possibility this lite tracks collection producer will be re-ran in the future with legacy releases?

> yes, it is quite possible.

>> track timing calculation was introduced with #26327 (previously
>> CTPPSDiamondLocalTrack input collection had t=0).

> the cut is applied on t + OOT*25. Is the OOT unchanged by the calibrations? Should we expect more or less events passing without the calibration applied (i.e with the cut applied to "0 + OOT*25" as would be read from the older data) ?

>> see e.g. in slide 5 of this AlCaDB presentation).

> from this and perhaps p4 I would conclude that the proposed cut is going to be safe for all data, even uncalibrated. Please confirm (if confirmed, this PR can just be signed as is).

**Comment by forthommel** [comment]
@slava77 
> Is the OOT unchanged by the calibrations?

Yes, it is only propagated from rechits level information

> Should we expect more or less events passing without the calibration
applied (i.e with the cut applied to "0 + OOT*25" as would be read from the older data) ?

If one considers older releases (no timing reconstruction), t = 0 falls 100% of the time within this time window selection. For early 2017 data (before run 302159 where multiple OOT ranges are expected), an overall reduction. Unchanged elsewhere.

> from this and perhaps p4 I would conclude that the proposed cut is going to be safe for all data, even uncalibrated. Please confirm (if confirmed, this PR can just be signed as is).

:+1:

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/26607	6033dd3
- code changes are in line with the PR description and the follow up review
- jenkins tests pass and comparisons with the baseline show no differences (this, however, is because there is no data with ```ctppsDiamondLocalTracks``` used in the tests)
    - the signoff is based mostly on visual inspection of somewhat trivial change in the track selection logic.

**Comment by forthommel** [comment]
> > The size of the time slice for tracks in PPS diamond timing detectors is reduced to the one 25 ns window of interest at the `miniAOD` lite data format level.
> 
> please add a link to some slides to justify this selection.
> Is the new selection implying that the job is running on a newly calibrated data (106X release reco inputs)?
> 
> Would this +/-12.5 ns selection still work for the data made in earlier releases (e.g. the original Run2 reco, 80X , 94X, or 102X)? If no, some appropriate modifiers should be applied to keep the right selection.

Hi @slava77 
Sorry for the radio silence, I am currently busy with another project these days. You mean there is a possibility this lite tracks collection producer will be re-ran in the future with legacy releases?
By the way, this skimming is only meaningful from `10_6_X` on, as the timing detectors' track timing calculation was introduced with https://github.com/cms-sw/cmssw/pull/26327 (previously `CTPPSDiamondLocalTrack` input collection had `t=0`).
Now, for the quantitative study of the overall size reduction, I may try to produce this for 2017 as for 2018 this range is not changing anything. This +- 12.5 ns window opening corresponds to one single acquisition window (centered on 0 with the use the timing calibration introduced earlier, see e.g. in slide 5 of [this AlCaDB presentation](https://indico.cern.ch/event/816634/contributions/3409095/attachments/1835633/3007479/pps-timing-calibration-forthomme.pdf)). In 2017 we were collecting 5, 3, 2, and progressively 1x25 ns time windows, and remained with 1 in 2018.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
