### PR TITLE
Updated ParameterDescription in EcalUncalibRecHitWorkerMultiFit.cc

### PR DESCRIPTION
**Pull request by jking79**
Updated ParameterDescription in EcalUncalibRecHitWorkerMultiFit.cc to show crossCorrelationMethod parameters

#### PR description:

ParameterDescription in EcalUncalibRecHitWorkerMultiFit.cc was not updated to reflect transition to crossCorrelationMethod as default ECAL rechit time reconstruction.  ParameterDescription where updated.

### CODE REVIEW

**Comment by thomreis** [comment]
type ecal

**Comment by thomreis** [comment]
please test

**Comment by clacaputo** [comment]
Hi @jking79 , should these update parameters produce some differences in reconstruction?

**Comment by jking79** [comment]
Hello Claudio,

No, it does not. This PR only updates entries in edm::ParameterDescription that we overlooked when we switched the ECAL timing reconstruction.  I will also be backporting this update to 13_1 after this PR goes through.

Excelsior,

Jack

**Comment by perrotta** [comment]
I miss the purpose of this PR. You update the default parameters in order to make them identical to the ones in RecoLocalCalo/EcalRecProducers/python/ecalMultiFitUncalibRecHit_cfi.py

In principle this is not needed. Unless you want to prevent the danger of having two identically named files with different config content:
1) RecoLocalCalo/EcalRecProducers/python/ecalMultiFitUncalibRecHit_cfi.py
2) cfipython/RecoLocalCalo/EcalRecProducers/ecalMultiFitUncalibRecHit_cfi.py

I think that the main issue with those configs is exactly that: there are two config with the same name and address path, and this can generate confusion.

Please either:
- remove the explicit RecoLocalCalo/EcalRecProducers/python/ecalMultiFitUncalibRecHit_cfi.py and stick on the default ecalMultiFitUncalibRecHit_cfi.py, or
- rename differently the default file, so that only the explicit one is picked by the configurations and there are no possible issues any more.

Even better if you keep the file with the explicit configuration and in it
```PYTHON
from RecoLocalCalo.EcalRecProducers.defaultEcalMultiFitUncalibRecHit_cfi import *
ecalMultiFitUncalibRecHit = defaultEcalMultiFitUncalibRecHit.clone()
```
(or whatever better name you invent for the default config) and you can modify the cloned parameters, if needed, without touching the C++ code.

**Comment by rappoccio** [comment]
hold

Place on explicit hold until comments from Andrea are addressed.

**Comment by jking79** [comment]
Per Andrea Perrotta suggestion, removed  RecoLocalCalo/EcalRecProducers/python/ecalMultiFitUncalibRecHit_cfi.py.  
Per Thomas Reis suggestion, removed unneeded variables from CC reconstruction algorithm.

**Comment by jking79** [comment]
Ran scram build code-format to apply code format

**Comment by thomreis** [comment]
please test

**Comment by perrotta** [comment]
> Per Andrea Perrotta suggestion, removed RecoLocalCalo/EcalRecProducers/python/ecalMultiFitUncalibRecHit_cfi.py

Ok, since you removed the explicit python configuration (which was not the preferred option among the ones that I suggested in https://github.com/cms-sw/cmssw/pull/42045#issuecomment-1618900420) I assume that you don't plan to update it any further in the (at least near) future

**Comment by perrotta** [comment]
unhold

**Comment by thomreis** [comment]
We decided to remove it completely in the end to not have to change the name for the default config, which would have affected also the default configuration for other algorithms. If it turns out that it would be better to keep the explicit cfi files it can be done in a separate PR consistently for all uncalibrated rechit algorithms.

**Comment by clacaputo** [comment]
+1

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
> * Reco comparison results: 152 differences found in the comparisons

There are diffs in reco.

In fact the configuration of the python file created by the fillDescriptions method is different from the one in the previous ecalMultiFitUncalibRecHit_cfi.py config file.

The difference is in the parameter `gainSwitchUseMaxSampleEB` which was `cms.bool(True)` in previous ecalMultiFitUncalibRecHit_cfi.py, while it is defaulted at `False` in the fillDescriptions, see https://github.com/cms-sw/cmssw/pull/42045/files#diff-122023a56b1159fb6bc63f3e5221ac35bc0bcf6a1bc08bc7109aea5b11ecc64cR733

Please check

**Comment by thomreis** [comment]
Hi @perrotta , is it true that in the current situation the parameters in the cfi file in RecoLocalCalo/EcalRecProducers/python/ecalMultiFitUncalibRecHit_cfi.py take priority over the default ones generated by fillDescriptions in cfipython/RecoLocalCalo/EcalRecProducers/ecalMultiFitUncalibRecHit_cfi.py?
If so then `gainSwitchUseMaxSampleEB` should be set to `True` also in the fillDescriptions defaults.

**Comment by perrotta** [comment]
I think that the configurations for the different instances of the EcalUncalibRecHitProducer module are rather confusing in the current cmssw. The following python configuration files are duplicated:
```
RecoLocalCalo/EcalRecProducers/python/ecalAnalFitUncalibRecHit_cfi.py		
RecoLocalCalo/EcalRecProducers/python/ecalFixedAlphaBetaFitUncalibRecHit_cfi.py		
RecoLocalCalo/EcalRecProducers/python/ecalGlobalUncalibRecHit_cfi.py		
RecoLocalCalo/EcalRecProducers/python/ecalMaxSampleUncalibRecHit_cfi.py		
RecoLocalCalo/EcalRecProducers/python/ecalMultiFitUncalibRecHit_cfi.py		
RecoLocalCalo/EcalRecProducers/python/ecalRatioUncalibRecHit_cfi.py		
RecoLocalCalo/EcalRecProducers/python/ecalWeightUncalibRecHit_cfi.py		
```
and
```
cfipython/RecoLocalCalo/EcalRecProducers/ecalAnalFitUncalibRecHit_cfi.py		
cfipython/RecoLocalCalo/EcalRecProducers/ecalFixedAlphaBetaFitUncalibRecHit_cfi.py		
cfipython/RecoLocalCalo/EcalRecProducers/ecalGlobalUncalibRecHit_cfi.py		
cfipython/RecoLocalCalo/EcalRecProducers/ecalMaxSampleUncalibRecHit_cfi.py		
cfipython/RecoLocalCalo/EcalRecProducers/ecalMultiFitUncalibRecHit_cfi.py		
cfipython/RecoLocalCalo/EcalRecProducers/ecalRatioUncalibRecHit_cfi.py		
cfipython/RecoLocalCalo/EcalRecProducers/ecalWeightsUncalibRecHit_cfi.py		
```


Since you are cleaning ecalMultiFitUncalibRecHit with this PR, I would suggest to clean all them at once, which is at the end the purpose of this PR

To do so, a possible suggestion is:

1) Replace in RecoLocalCalo/EcalRecProducers/plugins/EcalUncalibRecHitProducer.cc
```C++
descriptions.add("ecal" + algoName + "UncalibRecHit", desc);
```
with something like (e.g.)
```C++
descriptions.add("ecal" + algoName + "DefaultUncalibRecHit", desc);
```

2) Update all the explicit configuration files above with something like (e.g. for ecalMultiFitUncalibRecHit)
```PYTHON
from RecoLocalCalo.EcalRecProducers.ecalMultiFitDefaultUncalibRecHit_cfi import ecalMultiFitDefaultUncalibRecHit as _ecalUncalibRecHit
ecalMultiFitUncalibRecHit = _ecalUncalibRecHit.clone()
```
and you can still possibly easily update all parameters which are different from the default ones set by the fillDescription method without having to touch the C++ code, e.g.
```PYTHON
from RecoLocalCalo.EcalRecProducers.ecalMultiFitDefaultUncalibRecHit_cfi import ecalMultiFitDefaultUncalibRecHit as _ecalUncalibRecHit
ecalMultiFitUncalibRecHit = _ecalUncalibRecHit.clone(
  gainSwitchUseMaxSampleEB = True,                            
)
```

As I wrote [before](https://github.com/cms-sw/cmssw/pull/42045#issuecomment-1618900420), this is the cleanest way for not having duplicated configuration files in CMSSW, still being able to update them easily

**Comment by rappoccio** [comment]
hold

Please address comments [here](https://github.com/cms-sw/cmssw/pull/42045#issuecomment-1662209613)

**Comment by perrotta** [comment]
@jking79 please apply also https://github.com/cms-sw/cmssw/pull/42045#issuecomment-1662209613
(as of now this PR is basically doing nothing)

**Comment by jking79** [comment]
The intent of the PR was to make the necessary changes to the configs in order to finish making the CC timing algorithm the default for reconstruction, which is what I understood the changes made in this PR where for.  The changes you are proposing, while I am sure would be beneficial, are beyond my expertise and beyond what I am at liberty to do.

**Comment by perrotta** [comment]
> The intent of the PR was to make the necessary changes to the configs in order to finish making the CC timing algorithm the default for reconstruction, which is what I understood the changes made in this PR where for. The changes you are proposing, while I am sure would be beneficial, are beyond my expertise and beyond what I am at liberty to do.

After the last fix, the config is identical to the one which was in ecalMultiFitUncalibRecHit_cfi.py before this PR.
There is nothing wrong in merging this as such, but it is really doing nothing in practice.
If you implement https://github.com/cms-sw/cmssw/pull/42045#issuecomment-1662209613 you can fix the issue in current CMSSW of having duplicated configuration files.

**Comment by jking79** [comment]
> > The intent of the PR was to make the necessary changes to the configs in order to finish making the CC timing algorithm the default for reconstruction, which is what I understood the changes made in this PR where for. The changes you are proposing, while I am sure would be beneficial, are beyond my expertise and beyond what I am at liberty to do.
> 
> After the last fix, the config is identical to the one which was in ecalMultiFitUncalibRecHit_cfi.py before this PR. There is nothing wrong in merging this as such, but it is really doing nothing in practice. If you implement [#42045 (comment)](https://github.com/cms-sw/cmssw/pull/42045#issuecomment-1662209613) you can fix the issue in current CMSSW of having duplicated configuration files.

Making the information in ParameterSetDescription match the changes made in ecalMultiFitUncalibRecHit_cfi.py  for the CC timing method was the intent of the PR and what I was asked to do by the ECAL DPG.  As for the changes you are proposing, I am not at liberty to implement them.  Cleaning up the issue of having duplicate configuration files in the current CMSSW will need to be done in a separate PR by someone with the expertise and authorization to do so.

**Comment by perrotta** [comment]
Superseded by #42579, which is identical to this PR but the same config cleaning implemented here is propagated also to the other EcalUncalibRecHitProducer configuration modules

**Pull request closed without merging**
