### PR TITLE
L1REPACK 2016 2015

### PR DESCRIPTION
**Pull request by rekovic**
L1REPACK:Full2015Data workflow is defined. 
Necessary conditions configuration for HFTP1x1 are included, as well as geometry Extended2016Reco (Hcal geometry needed for HF TP1x1).

Usually, the geometry flag is passed to cmsDriver.py as --geometry=Extended2016,Extended2016Reco
but this geometry configuration is already loaded in the workflow which is meant to be used out box for the HLT folks.

L1REPACK:Full is redefined to be compatible with 2016 data.

### CODE REVIEW

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by fwyzard** [comment]
@rekovic looks like this should be rebased on a more recent IB ?

**Comment by rekovic** [comment]
@fwyzard  I imagine that would require much fewer signatures.  Preferred to use the same branch as for  80x PR. (#14387)

**Comment by fwyzard** [comment]
I understand the preference - and that's my initial approach as well.
By now 8.0.x and 8.1.x are diverging enough that it keeps the PRs and history cleaner if you use a different branch; what I do in these cases is
  - prepare the 80x branch and pull request
  - create a new 8.1.x working area
  - add and fetch the repository with the 8.0.x branch
  - cherry-pick the commits into a new branch:
```
git cherry-pick official-cmssw/CMSSW_8_0_X..cms-l1t-offline/rekovic-L1REPACK-2016-2015
git push cms-l1t-offline HEAD:rekovic-L1REPACK-2016-2015_81x
```

**Comment by rekovic** [comment]
@fwyzard Thanks for the short recipe.  Effect is the same as rebase onto, and slightly more linear.

**Comment by mmusich** [comment]
@rekovic this still requires alca signature, which I think we don't need to

**Comment by rekovic** [comment]
@mmusich  This PR will be closed as it is replaced by #14392.

**Pull request closed without merging**
