### PR TITLE
Backport of new Phase-2 L1T packages to 11_1_X

### PR DESCRIPTION
**Pull request by silviodonato**
#### PR description:
This PR is a backport of all new Phase-2 L1T code to 11_1_X.
The L1T 11_2_X code has been taken from CMSSW_11_2_X_2020-07-02-2300.

Backported packages
DTTriggerPhase2
L1CaloTrigger
L1TTrackMatch
TrackerDTC
TrackFindingTMTT
TrackFindingTracklet

The PR should work with https://github.com/cms-sw/cmsdist/pull/6024

cc: @rekovic

### CODE REVIEW

**Comment by silviodonato** [comment]
please test with cms-sw/cmsdist#6024

**Comment by silviodonato** [comment]
@smuzaffar @makortel @mkirsano shall I take some action to "declare" the new backported packages ?

**Comment by silviodonato** [comment]
merge

**Comment by makortel** [comment]
@silviodonato 

> shall I take some action to "declare" the new backported packages ?

Could you elaborate what do you mean with "declaring new backported packages"?

**Pull request merged**
