### PR TITLE
Deterministic DRN

### PR DESCRIPTION
**Pull request by ssrothman**
#### PR description:

This PR addresses issue #41060 where the outputs from the photonDRN model was observed to be non-deterministic. We have determined that this is due to a problem with the scheduler in the Triton ensemble model backend. This pull request contains code changes needed to convert from the ensemble model setup to a pure pytorch combined model. A companion cms-data PR will contain the necessary changes to the model config. 

#### PR validation:

Local testing of workflow `10805.31_SingleGammaPt35+2018_photonDRN` has shown perfectly deterministic behavior.

### CODE REVIEW

**Comment by simonepigazzini** [comment]
please test

**Comment by simonepigazzini** [comment]
+1

**Comment by mmusich** [comment]
please test

**Comment by rappoccio** [comment]
+1

**Pull request merged**
