### PR TITLE
Run3-alca226A Modify HOCalibAnalyzer as suggested by ALCA reviewer

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Modify HOCalibAnalyzer as suggested by ALCA reviewer

#### PR validation:

Use the runTheMatrix test workflows 

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by ChrisMisan** [comment]
@bsunanda please squash the code-checks commit

**Comment by ChrisMisan** [comment]
type hcal

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by ChrisMisan** [comment]
please abort
@bsunanda please squash the commits, there is no need to run the tests twice

**Comment by ChrisMisan** [comment]
@bsunanda can you also collapse the if statements to loops?

**Comment by bsunanda** [comment]
It will be a complicated loop. Some of the "if"'s have some conditional things inside it and some don't. I have to think about the most optimum way of making the loop. I shall leave it for the future. I just squash the PR

**Comment by ChrisMisan** [comment]
please test

**Comment by ChrisMisan** [comment]
+alca

- includes some of the code improvements recommended in https://github.com/cms-sw/cmssw/pull/39063#issuecomment-1216468082
- differences only in MTD

**Comment by qliphy** [comment]
+1

**Pull request merged**
