### PR TITLE
Fix on the findAndChange for a new All-in-one.

### PR DESCRIPTION
**Pull request by TomasKello**
#### PR description:

This is a small fix addressing issues with a global configuration for a new All-in-one validation tool: 
- fix on the findAndChange macro to recognize all protocols in a search path,
- automated parsing of the ROOT colors to the integer values,
- fix on the problem with a decimals in the plot's right-corner label (e.g. 13.6 TeV)

#### PR validation:
Run the package tests:

`scram b runtests use-ibeos`

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

N/A

FYI @consuegs @henriettepetersen @amecca

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by TomasKello** [comment]
Seems all is fine. After discussion, @amecca will yet add one more commit to this PR to preserve his authorship (I only did small changes). He will add an example of working configuration showing new feature (as there is never enough working examples).

**Comment by mmusich** [comment]
type bug-fix

**Comment by TomasKello** [comment]
> @TomasKello, before re-launching tests, would you mind re-basing to avoid the merge in the commit history?

Done, please proceed.

**Comment by mmusich** [comment]
@cmsbuild please test

**Comment by TomasKello** [comment]
All tests passed, can we please merge?

**Comment by perrotta** [comment]
+alca

**Comment by perrotta** [comment]
+1

**Pull request merged**
