### PR TITLE
TopMonitoring: Updated fully hadronic paths and ele, fully hadronic t…

### PR DESCRIPTION
**Pull request by skonstantinou**
Fully hadronic paths have been updated according to [1]. The b-tagging algorithm changed from CSV to DeepCSV. Tighter cuts in the fully hadronic selection have been applied. 
In the electron selection, the loose isolation cut has been removed (a cut on the relIso is included in electron ID)

[1] https://its.cern.ch/jira/browse/CMSHLT-1857

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by fabiocos** [comment]
@skonstantinou @jfernan2 the description of the PR says that DeppCSV is added, but from the code I would naively say it is removed, could you please clarify?

**Comment by skonstantinou** [comment]
@fabiocos @jfernan2 The b-tagging algorithm used for the fully hadronic paths has changed to DeepCSV [1].
This means that there is no difference between the selections in [2] and [3] and the later can be removed

[1] https://github.com/cms-sw/cmssw/pull/23691/files#diff-148c698ded5b0a43d10260cde15eb620R360
[2] https://github.com/cms-sw/cmssw/pull/23691/files#diff-148c698ded5b0a43d10260cde15eb620L352
[3] https://github.com/cms-sw/cmssw/pull/23691/files#diff-148c698ded5b0a43d10260cde15eb620L560

**Comment by fabiocos** [comment]
@skonstantinou ok thanks

**Comment by fabiocos** [comment]
+1

**Pull request merged**
