### PR TITLE
Updating the radiation map to be used with GeometryExtended2026D86Reco

### PR DESCRIPTION
**Pull request by pfs**
#### PR description:

This PR updates the radiation map to be used with the 47-layer geometry of HGCAL, following the latest Fluka simulations by BRIL.
The plotting validation tool under SimCalorimetry/HGCalSimAlgos is also updated.

#### PR validation:

The radiation maps (fluence and dose) for D49 (50-layer) and D86 (47-layer) have been inspected and found to be compatible with the expectations from Fluka.
A summary can be found in the following PDF

[RadiationMapHGCAL.pdf](https://github.com/cms-sw/cmssw/files/7116636/RadiationMapHGCAL.pdf)

### CODE REVIEW

**Comment by srimanob** [comment]
@cmsbuild please test

**Comment by civanch** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

**Comment by qliphy** [comment]
+1

**Pull request merged**
