### PR TITLE
Phase2-TB76X Add an aalyzer for HGCal TB sudies using  inch wafers

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Add an aalyzer for HGCal TB sudies using  inch wafers

#### PR validation:

Being used by people who are analysing 2023 August TB runs for HGCal

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
