### PR TITLE
Fix path name in HLT BTV valdiation code

### PR DESCRIPTION
**Pull request by silviodonato**
Replacement of "HLT_CaloMHTNoPU90_PFMET90_PFMHT90_IDLoose_" with "HLT_CaloMHTNoPU90_PFMET90_PFMHT90_IDTight_", 
according to:
https://its.cern.ch/jira/browse/CMSHLT-333

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
@silviodonato the test errors look to be related to your pr. Could you have a look?

**Comment by silviodonato** [comment]
I forgot to modify also  HLTriggerOffline/Btag/python/HltBtagPostValidation_cff.py !
Now I've fixed.

**Comment by deguio** [comment]
+1
please test

**Comment by deguio** [comment]
please test

**Comment by davidlange6** [comment]
+1

**Comment by perrotta** [comment]
Since data taking (and corresponding validation) is actually done with 74X, does it exist (or do you foresee) a 74X counterpart of this pull request?

**Comment by silviodonato** [comment]
Hi Andrea, I've just tried to do it, but I noticed that in 74X we still have the old HLT menu ( http://cmslxr.fnal.gov/source/HLTrigger/Configuration/python/HLT_25ns14e33_v1_cff.py?v=CMSSW_7_4_6 ), it means that we have to keep the old HLT path names:
- HLT_PFMET120_NoiseCleaned_BTagCSV07_v
- HLT_CaloMHTNoPU90_PFMET90_PFMHT90_IDLoose_

**Comment by perrotta** [comment]
Ciao Silvio.
This is something that you must agree with DQM gurus. Yes, the HLT menu which is in the release is still the old frozen one, and it will remain as such because of  the possible next MC productions. But 74X is also used for the data taking at P5, were the latest HLT menu is going to be deployed. I don't know which is the policy, but I would say that any DQM module in 74X should be able to run with both "old" and "new" path names. Would the new path names be not taken into account by this DQM then they will never be monitored during data taking.

**Comment by silviodonato** [comment]
@danduggan, @deguio can you comment the issue?
In my opinion, unless you've planned to update the HLT menu in 74X, I should keep the old trigger names.
As the validation code is run on RelVal only (and not on data), it is not a problem if we have different trigger names on data. Is it?

**Comment by silviodonato** [comment]
The issue has been solved with https://github.com/cms-sw/cmssw/pull/10493

**Pull request merged**
