### PR TITLE
Update DQMServices for protobuf 3.6.1.2 and tensorflow interfaces for TF 1.13.1

### PR DESCRIPTION
**Pull request by mrodozov**
Following instructions to update those file when updating protobuf in here:
https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_10_5_X/gcc700/protobuf.spec

### CODE REVIEW

**Comment by mrodozov** [comment]
plese test with https://github.com/cms-sw/cmsdist/pull/4684

**Comment by mrodozov** [comment]
please test with https://github.com/cms-sw/cmsdist/pull/4684

**Comment by smuzaffar** [comment]
please test with cms-sw/cmsdist#4684

**Comment by mrodozov** [comment]
please test with cms-sw/cmsdist#4684

**Comment by mrodozov** [comment]
abort

**Comment by mrodozov** [comment]
please test with cms-sw/cmsdist#4684

**Comment by mrodozov** [comment]
those should not be combined with changes for protobuf ... should be separate PR :/

**Comment by smuzaffar** [comment]
hold
this needs cmsdist update too.

**Comment by mrodozov** [comment]
please test with https://github.com/cms-sw/cmsdist/pull/4712

**Comment by smuzaffar** [comment]
please test with cms-sw/cmsdist#4712

**Comment by mrodozov** [comment]
please test with cms-sw/cmsdist#4712

**Comment by mrodozov** [comment]
please test with https://github.com/cms-sw/cmsdist/pull/4813

**Comment by mrodozov** [comment]
We have gcc 7.4.1 in the cmsdist IB/CMSSW_10_6_X/gcc700next branch, which brings this gcc version into DEVEL branch. The externals build fine, but cmssw tensorflow interfaces need adjustment (and this PR). I see @riga is the author of this part of the code, so I'll ask him to help with that. 
@slava77 FYI

**Comment by riga** [comment]
@mrodozov [Abseil-cpp (`absl`)](https://github.com/abseil/abseil-cpp) was added as a dependency in TF 1.11 (compare [stringpiece.h @ 1.10](https://github.com/tensorflow/tensorflow/blob/v1.10.0/tensorflow/core/lib/core/stringpiece.h) vs. [stringpiece.h @ 1.11](https://github.com/tensorflow/tensorflow/blob/v1.11.0/tensorflow/core/lib/core/stringpiece.h)), so this might be added to https://github.com/cms-sw/cmsdist/pull/4712.

**Comment by mrodozov** [comment]
please test with cms-sw/cmsdist#4813

**Comment by smuzaffar** [comment]
please test with cms-sw/cmsdist#4813
run tests based on newer IB (with new geant4)

**Comment by mrodozov** [comment]
please test with https://github.com/cms-sw/cmsdist/pull/4890

**Comment by mrodozov** [comment]
@VinInn how do we recreate the test_graph_tfadd.pb file (I'd assume using the config.pbtxt somehow ?). 
It doesn't work with the old one (maybe because of protobuf version change)

**Comment by VinInn** [comment]
have a look into
https://twiki.cern.ch/twiki/bin/view/Main/VIKeras2Inference

**Comment by mrodozov** [comment]
The converter needs and .h5 input for the .pb (as far as I can understand)

**Comment by davidlange6** [comment]
i think you can load, convert to json and remake the pb.. I have all but the last step working. will try to provide a recipe

**Comment by davidlange6** [comment]
I think this should work

from google.protobuf import json_format
import tensorflow as tf

# read the initial file
f=tf.gfile.GFile('test_graph_tfadd.pb', 'rb')
graph_def = tf.GraphDef()
graph_def.ParseFromString(f.read())
json_string = json_format.MessageToJson(graph_def)
f2=open('my-model.json','w')
f2.write(json_string)
f2.close()

then with your new tensorflow stack
from google.protobuf import json_format
import tensorflow as tf

f3=open('my-model.json','r')
json_string2=f3.read()

graph_def2 = tf.GraphDef()
json_format.Parse(json_string,graph_def2)
json_string3 = json_format.MessageToJson(graph_def2)
tf.train.write_graph(graph_def2,'./my-model','newtf.pb',as_text=False)

**Comment by riga** [comment]
@davidlange6 Thanks for that hint, the new .pb file seems to work.

**Comment by davidlange6** [comment]
Cool - could you put it into the test directory in some form so we will remember in a year

[but what you committed looks like a json version not a pb version?]

**Comment by mrodozov** [comment]
https://github.com/cms-sw/cmsdist/pull/4890

**Comment by mrodozov** [comment]
I retried if there was something wrong, protobuf version is 3.6.1 tf 1.13.1 when I'm recreating it from the .json - the file is the as it was.

**Comment by mrodozov** [comment]
plase test with https://github.com/cms-sw/cmsdist/pull/4890

**Comment by perrotta** [comment]
please test with cms-sw/cmsdist#4890

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
Relvals doesn't finish because of gdb hang on runtime error:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-25889/34379/runTheMatrix-results/27434.0_TTbar_14TeV+TTbar_14TeV_TuneCUETP8M1_2023D35_GenSimHLBeamSpotFull14+DigiFullTrigger_2023D35+RecoFullGlobal_2023D35+HARVESTFullGlobal_2023D35/step3_TTbar_14TeV+TTbar_14TeV_TuneCUETP8M1_2023D35_GenSimHLBeamSpotFull14+DigiFullTrigger_2023D35+RecoFullGlobal_2023D35+HARVESTFullGlobal_2023D35.log 

In the first test, different relval crashed with the same reason:
Module: DeepFlavourTFJetTagsProducer:pfDeepFlavourJetTagsSlimmedDeepFlavour (crashed)
see
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-25889/34363/runTheMatrix-results/10042.0_ZMM_13+ZMM_13TeV_TuneCUETP8M1_2017_GenSimFull+DigiFull_2017+RecoFull_2017+HARVESTFull_2017+ALCAFull_2017/step3_ZMM_13+ZMM_13TeV_TuneCUETP8M1_2017_GenSimFull+DigiFull_2017+RecoFull_2017+HARVESTFull_2017+ALCAFull_2017.log

**Comment by slava77** [comment]
@mrodozov please clarify on the status of this PR.
Thank you.
It looks like it is still not ready for review, a work in progress.

**Comment by mrodozov** [comment]
@slava77 we merged the changes from here into DEVEL to have an IB to work against.

**Comment by slava77** [comment]
> @slava77 we merged the changes from here into DEVEL to have an IB to work against.

Please clarify on the status of making this PR applicable for the regular master version of CMSSW.
Thank you.

**Comment by davidlange6** [comment]
it needs to run without hanging first... Any review is certainly useful in the meanwhile.

**Comment by slava77** [comment]
@mrodozov 
please clarify on the status of this PR.
Thank you.

**Comment by slava77** [comment]
> it needs to run without hanging first... Any review is certainly useful in the meanwhile.
> […](#)

is the origin of the hanging understood?

I noticed in 1.12 notes https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md#bug-fixes-and-other-changes-2 that there was a change from jemalloc to the system malloc.
Could a mix of allocators lead to problems?

**Comment by slava77** [comment]
> @mrodozov
> please clarify on the status of this PR.
> Thank you.

ping

**Comment by mrodozov** [comment]
I'll reopen it when we are ready

**Pull request closed without merging**
