### PR TITLE
dynamic conditions for PPS direct simulation

### PR DESCRIPTION
**Pull request by jan-kaspar**
#### PR description:

This PR improves the [PPS direct simulation](https://twiki.cern.ch/twiki/bin/viewauth/CMS/TaggedProtonsDirectSimulation) by allowing for non-constant conditions during a single cmsRun execution. This is essential for PPS since the relevant conditions (often LHC related) change during each year (often at LHC Technical Stop, "TS").

The proposed solution was presented in [Proton POG meeting](https://indico.cern.ch/event/962678/contributions/4050007/attachments/2115486/3561622/dynamic_conditions.pdf). In short, there's a new ES setup module which randomly generates conditions relevant for PPS simulation (at configurable frequency). The random generation follows distributions extracted from data, in proportions following the integrated luminosity.

#### PR validation:

The two PDF summaries below compare the results obtained with SW before (blue) and after (red dashed) this PR.
 * [reco_cmp.pdf](https://github.com/cms-sw/cmssw/files/5573982/reco_cmp.pdf) - no difference in data reconstruction (as expected)
 * [dirsim_cmp.pdf](https://github.com/cms-sw/cmssw/files/5573981/dirsim_cmp.pdf) - some differences in direct simulation (as expected)
    * before this PR, the simulation could be performed only for a single period, thus the "per year" rows miss the blue curve
    * row "2016", the two periods (pre- and post-TS2) are correctly represented in the xangle histogram (185 an 140 urad, resp) and with the correct weight (higher L_int in pre-TS2)
    * row "2016 postTS2" - perfect agreement before vs. after as expected
    * row "2017": both beta* values (0.4 for pre-TS2 and 0.3 for post-TS2) are correctly represented
    * rows "2017_postTS2" and "2018_postTS2" - compatible shapes but not perfect overlap - expected since this PR changes the order or random values generations, thus the samples of xangles/beta* are a little different

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by cvuosalo** [comment]
+1

**Comment by jfernan2** [comment]
+1

**Comment by ggovi** [comment]
+1

**Comment by silviodonato** [comment]
kind reminder @cms-sw/alca-l2

**Comment by jan-kaspar** [comment]
@cms-sw/alca-l2 Can we facilitate your review in any way?

**Comment by silviodonato** [comment]
urgent

**Comment by silviodonato** [comment]
@cms-sw/alca-l2 ?

**Comment by silviodonato** [comment]
@jan-kaspar I tried this PR with 
```
cmsDriver.py stepTest  --conditions auto:phase1_2021_realistic -s RAW2DIGI,L1Reco,RECO --datatier GEN-SIM-RECO -n 10 --geometry DB:Extended --era Run3 --eventcontent RECOSIM --filein file:/afs/cern.ch/work/s/sdonato/public/debug_PPS/badd237c-4857-4f48-b10f-52c832f57f02_ev1126.root
```
(see #32340).

And I'm still getting 
```
----- Begin Fatal Exception 01-Dec-2020 11:51:52 CET-----------------------
An exception of category 'NoRecord' occurred while
   [0] Processing  Event run: 1 lumi: 12 event: 1126 stream: 0
   [1] Running path 'RECOSIMoutput_step'
   [2] Prefetching for module PoolOutputModule/'RECOSIMoutput'
   [3] Prefetching for module LogErrorHarvester/'logErrorHarvester'
   [4] Calling method for module CTPPSProtonProducer/'ctppsProtons'
Exception Message:
No "LHCInfoRcd" record found in the EventSetup.n
 Please add an ESSource or ESProducer that delivers such a record.
----- End Fatal Exception -------------------------------------------------

```

Please note that in #32340 we are getting error in Run-3 and HI workflows.

**Comment by jan-kaspar** [comment]
My comment https://github.com/cms-sw/cmssw/issues/32340#issuecomment-736319131 was more a conceptual one. I apologise if it was understood that this PR would fix the problem.

This PR applies the idea of "dynamically generated" conditions to the "direct" simulation of PPS (https://twiki.cern.ch/twiki/bin/viewauth/CMS/TaggedProtonsDirectSimulation) not to the standard simulation. But I guess that the same concept can be used also for the standard simu (TBC).

In general, PPS is still missing several pieces for 2021 scenario, let me just mention this PR #31484.

Therefore I guess that it is appropriate to (temporarily) disable PPS reco (and possibly simu) for Run3 wfs - as I saw that you prepare elsewhere.

**Comment by civanch** [comment]
@jan-kaspar , if PPS would be disabled from SIM for Run-3 WFs, then it will be never enabled back for the Run-3 standard production, because the production geometry will be frozen. If there is no geometry, we have no SIM hits, DIGI-RECO will be configured assuming no PPS hits. All analysis will remain private.

This may be a reality but why not to try to push PPS to be on some acceptable level within CMSSW? At least, to have correct geometry description.

**Comment by jan-kaspar** [comment]
@civanch Thanks for pointing out technical details for simu - I acknowledge that I am not an expert. I wish to comment only for reco. I dared to mention simu in my previous comment since I am puzzled. It seems that the LHCInfo is missing for the WF. This means that, e.g. the LHC xangle is undefined. If it is undefined, then one cannot tell how to propagate forward protons from the IP to the RPs. Consequently I don't know what the simu does...

As for the solution of the current "crisis" I'd agree to *temporarily* disable PPS reco. We *should* re-enable it once the problem with conditions is understood and solved.

**Comment by jan-kaspar** [comment]
For the recent dicussions in https://github.com/cms-sw/cmssw/issues/32340#issuecomment-738694584 and elsewhere, let me comment that:
 * this PR adds the *possibility* to use the "dynamic" conditions (not an *obligation*)
 * this PR only touches the "direct" (fast) simulation of PPS, thus no central workflow
 * for PPS use, this PR has been approved by the Proton POG
Therefore I believe that it is still worth merging it, while we can have more general discussion meanwhile.

**Comment by silviodonato** [comment]
@cms-sw/alca-l2 please review/sign this PR. My comment was unrelated to this PR (see #32346 ).

**Comment by silviodonato** [comment]
urgent
if there are no comments/objections, I will merge it tomorrow after the meeting

**Comment by christopheralanwest** [comment]
+alca

**Comment by silviodonato** [comment]
+1

**Pull request merged**
