### PR TITLE
[Backport 123X] pT dependent ROI producers for Muon HLT

### PR DESCRIPTION
**Pull request by khaosmos93**
Backport of #37286. The backport is needed for the first Run 3 data taking.
No difference in codes w.r.t. the original PR.

### CODE REVIEW

**Comment by missirol** [comment]
urgent

Requested by TSG for `12_3_0`, see https://github.com/cms-sw/cmssw/pull/37286#issuecomment-1086720064.

**Comment by missirol** [comment]
please test

**Comment by clacaputo** [comment]
+reconstruction

- backport of https://github.com/cms-sw/cmssw/pull/37286

**Comment by qliphy** [comment]
+1

**Pull request merged**
