### PR TITLE
remove unnecessary #include

### PR DESCRIPTION
**Pull request by fwyzard**

### CODE REVIEW

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by fwyzard** [comment]
OK, I see that I need to test building all those packages locally.

I'll try to have a PR for the 1100 IB.

.A

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by smuzaffar** [comment]
@fwyzard , can you please integrate the change of https://github.com/cms-sw/cmssw/pull/21424/files in here

**Comment by fwyzard** [comment]
Sure, done.

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by smuzaffar** [comment]
@cmsbuild, please test

**Comment by davidlange6** [comment]
merge

**Pull request merged**
