### PR TITLE
First attempt to fix DQM GUI urls in RelMon

### PR DESCRIPTION
**Pull request by jfernan2**
#### PR description:

This PR tries to fix issue https://github.com/cms-sw/cmssw/issues/27800
Links points to root Everything workspace instead of dedicated folder to simplify

#### PR validation:

Tested locally

#### if this PR is a backport please specify the original PR:

No backport

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by perrotta** [comment]
I wonder why   "Utilities/RelMon" is in the "reconstruction" category instead of "dqm": just a mistake or is there any reason behind?

**Comment by slava77** [comment]
@smuzaffar @mrodozov 
this should technically be tested with the cms-bot
What is the right command to test with the bot using the updated relmon?

**Comment by mrodozov** [comment]
@slava77 testing the python files could be generalize up to "if they compile" (and they does in this case) but for the "what they produce when run" I think a unit test will be required (if there is none, I don't know). Assuming there is no test the proper way to test it would be to ask @jfernan2 what was used to local test it, add it as a unit test and rerun. Apart from that, the python part just ... compiles. If it didn't the scram command would've failed.

**Comment by jfernan2** [comment]
@mrodozov  in my test I just made sure that the piece of python code I am modifying/introducing was working locally (with a print) as expected, producing the desired string for the url link. Not a real unit test.
Nevertheless, the code as it is now before this PR, it is just putting a plain link to the DQM RelVal GUI, which nobody is using since the actual ROOT files compared by RelMon are not loaded

**Comment by perrotta** [comment]
@jfernan2 : I think that this code, and the whole "Utilities/RelMon" package, should belong to dqm rather than reconstruction. If you agree with it, I could just switch "Utilities/RelMon" to dqm in the categories map. Or alternatively, we can can at least share it if you think there are reasons for having it in reco that I am not aware of.
In the meanwhile, I'd just assign this PR to you

**Comment by perrotta** [comment]
assign dqm

**Comment by slava77** [comment]
> @slava77 testing the python files could be generalize up to "if they compile" (and they does in this case) but for the "what they produce when run" I think a unit test will be required (if there is none, I don't know). Assuming there is no test the proper way to test it would be to ask @jfernan2 what was used to local test it, add it as a unit test and rerun. Apart from that, the python part just ... compiles. If it didn't the scram command would've failed.

Just to be sure, what I meant is that the code updated here is used by cms-bot in the run-pr-comparisons jobs
https://github.com/cms-sw/cms-bot/blob/ae1038f46919118a51636f6aeca3aff7dc6869f4/run-pr-comparisons#L71
My question was if there is a way to run the cms-bot comparisons on top of the build using this PR.

**Comment by jfernan2** [comment]
@perrotta fine by us (DQM). I do not know why it is under reco umbrella (historical reasons?), I just learnt it was this way when creating this PR

**Comment by mrodozov** [comment]
> Not a real unit test

it's not exactly a unit test to test a "unit" but that's not unusual to test pieces like this when required. Example is this:
https://github.com/cms-sw/cmssw/tree/master/PhysicsTools/PythonAnalysis/test
which is full of scripts that are testing something. And we refer to it as "unit test" although they are not exactly unit tests

**Comment by perrotta** [comment]
Thak you @jfernan2 : cms-bot PR https://github.com/cms-sw/cms-bot/pull/1190 makes the switch

**Comment by perrotta** [comment]
+1
- (reco pass-through)

**Comment by jfernan2** [comment]
I am sorry @mrodozov but I am not able to create a test file like you propose which mimics the RelMon environment. 
@slava77 in the run-pr-comparison jobs by cms-bot, RelMon is running standalone so that DQM root files are not uploaded to any DQM GUI, except by the bin-by-bin comparison tool which actually uploads them to the development GUI for a real comparison

**Comment by jfernan2** [comment]
+1
This PR is not breaking any RelMon functionality at all: it just replaces a general link to the DQM RelVal GUI by a dedicated url with the files involved in the comparison. In the worst case scenario, non-existing root files in GUI like RelMon standalone tests or malformed url, the link will still work pointing to the RelVal GUI as it was previously

**Comment by kpedro88** [comment]
+1

**Comment by fabiocos** [comment]
@jfernan2 @perrotta @slava77 we already discussed this point in the recent past, as far as I know RelMon is historically under the reconstruction umbrella because it was originally developed by @dpiparo working with @VinInn to monitor and study workflows and in particular RECO performances. But strictly speaking is more a DQM tool than a RECO one IMO

**Pull request merged**
