### PR TITLE
Test workflows for lepton time-life customization of NanoAOD

### PR DESCRIPTION
**Pull request by mbluj**
#### PR description:

This PR adds test workflows for lepton time-life customization of NanoAOD.
Those workflows completes inclusion of the customization into CMSSW and were requested in the original PR: https://github.com/cms-sw/cmssw/pull/43525#issuecomment-1960039636.

Backport of this PR is not foreseen.

#### PR validation:

The newly added workflows run successfully like this:
```
runTheMatrix.py -l 2500.403,2500.316 -i all --ibeos
```

### CODE REVIEW

**Comment by vlimant** [comment]
enable nano

**Comment by vlimant** [comment]
please test

**Comment by mbluj** [comment]
Rebased to fix issue with merging in tests.

**Comment by vlimant** [comment]
please test

**Comment by srimanob** [comment]
+Upgrade

**Comment by AdrianoDee** [comment]
+pdmv

**Comment by rappoccio** [comment]
+1

**Pull request merged**
