### PR TITLE
Removed obsolete PrintInfo() function from G4muDarkBremsstrahlung

### LINKED ISSUE #38935: [G4VECGEOM_X] IB reports compiler errors for both gcc10 and gcc11.
Hello,

IB `G4VECGEOM_X` is reporting compiler errors leading to failures in tests and relvals. See failures at [CMSSW_12_5_G4VECGEOM_X_2022-08-01-2300](https://cmssdt.cern.ch/SDT/cgi-bin/showBuildLogs.py/el8_amd64_gcc10/www/mon/12.5.G4VECGEOM-mon-23/CMSSW_12_5_G4VECGEOM_X_2022-08-01-2300).

We think it could be broken because of [#38329](https://github.com/cms-sw/cmssw/pull/38329).

In addition, the `G4` version of `G4VECGEOM_X` is 11.0.6 and in `12_5_X` is 10.7.2. Could it be because function `PrintInfo` was marked "obsolete" in 10.7.2  (https://github.com/cms-externals/geant4/blob/cms/v10.7.2/source/processes/electromagnetic/utils/include/G4VEmProcess.hh) and it was removed in 11.0.6?

Many thanks,
Andrea.

### PR DESCRIPTION
**Pull request by revering**
Removed PrintInfo() function from G4muDarkBremsstrahlung to resolve #38935

The process generation ran successfully with PrintInfo() removed, and hopefully its removal will fix the IB compiler errors noted in the issue.

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test for CMSSW_12_5_G4VECGEOM_X

**Comment by civanch** [comment]
@revering , please, add he fix of G4muDarkBremsstahlungModel: substitute 

element->GetA() by element->GetN()

**Comment by revering** [comment]
I've implemented the change to GetN() and using the Geant4 muon particle definition to get the muon mass instead of a hardcoded value. The muon mass is used in many functions, so I added it as a class member and initialized it with 
muonMass = G4MuonMinus::MuonMinusDefinition()->GetPDGMass() / CLHEP::GeV
instead of using the dynamic particle.

**Comment by qliphy** [comment]
@revering   Please also backport this to 12_4_X

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by civanch** [comment]
@revering , please make modification in 10_6 PR, make also backport of this PR to 12_4.

**Comment by qliphy** [comment]
+1

**Pull request merged**
