### PR TITLE
Run3-gex1180Z Backport PRs #45716 and #45725 with the correction for GE21 positions in the 2024 scenario definition

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Backport PRs #45716 and #45725 with the correction for GE21 positions in the 2024 scenario definition

#### PR validation:

Use the runTheMatrix test workflows

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backports of #45716 (corrected GE21 geometry) and #45721 (modified 2024 scenario)

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
+geometry

**Comment by bsunanda** [comment]
@srimanob Please approve this

**Comment by srimanob** [comment]
+Upgrade

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
