### PR TITLE
EgHLT Phase-II showershape fix : 11_2_X

### PR DESCRIPTION
**Pull request by Sam-Harper**
#### PR description:

This PR disables the calculation of ECAL showershape variables for superclusters which are not in the ECAL. It sets the showershapes to zero so that by default they pass, this makes things easier to build a trigger as it avoids having to OR the ECAL and HGCAL showershape filters (which likely eventually will be made into a single filter but that is not for today).

No physics changes are expected, the change in behaviour is a crash is prevented for PhaseII

#### PR validation:

PhaseII E/gamma HLT workflows do not crash.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

https://github.com/cms-sw/cmssw/pull/32469:  bug fix to run E/gamma HLT Phase-II

### CODE REVIEW

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by smuzaffar** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by Martin-Grunewald** [comment]
+1

**Comment by silviodonato** [comment]
backport of #32469

**Comment by silviodonato** [comment]
+1

**Pull request merged**
