### PR TITLE
New codes for Strip O2O

### PR DESCRIPTION
**Pull request by hqucms**
Bug fixes.
New classes for DCS/DAQ O2O payload transfer.
Plugins for SiStripDetVOff trend plots and tkMap plots.

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
@hqucms I am wondering it the huge dat files 

`CalibTracker/SiStripDCS/data/StripPSUDetIDMap_FromFeb2016.dat `
and
`CalibTracker/SiStripDCS/data/StripPSUDetIDMap_FromAug2013.dat`

should not be included in the data-repo instead https://github.com/cms-data/

@smuzaffar can you remind us the procedure? If I remember correctly we need to create an appropriate folder in there and add it as external?
Thanks,

Marco

**Comment by smuzaffar** [comment]
@mmusich , we need to create cms-data/data-CalibTracker-SiStripDCS external repo and add these data files there.
@degano , can you please take care of these data files?

**Comment by davidlange6** [comment]
why are these data important to be tracked in the code repo? Neither is used in code committed.

**Comment by hqucms** [comment]
These data files are the mapping from power supplies to the Strip detector. They are necessary for the running of DCS O2O and are specified in the configuration files.

**Comment by davidlange6** [comment]
so naively they should be in a DB. but anyway, I don’t see the configuration files you mention. Can you be specific?

**Comment by hqucms** [comment]
It's used in e.g., CalibTracker/SiStripDCS/test/dcs_o2o_template_cfg.py.

**Comment by degano** [comment]
I've created the data repository here: https://github.com/cms-data/data-CalibTracker-SiStripDCS/tree/master.
Please feel free to make a PR to that repository containing the desired data once established what's needed.

**Comment by hqucms** [comment]
@degano Thank you! I have created a PR with the two data files.

**Comment by davidlange6** [comment]
@hqucms @degano - apologies - this PR dropped off of my list last week - we can support keeping the current power supply map in cmssw if it is needed to run the o2o - however, cmssw is not the means by which to track the history of this map.  So, lets add the current map (neither of the ones requested it seems?) to the data repo  and remove all the maps from this PR. Thanks!

**Comment by mmusich** [comment]
please test

**Comment by hqucms** [comment]
@davidlange6 @degano The two data files are removed from this PR and only the current map (StripPSUDetIDMap_FromFeb2016.dat) is added to the data repo now (https://github.com/cms-data/data-CalibTracker-SiStripDCS/pull/1).

**Comment by hqucms** [comment]
@cmsbuild please test

**Comment by ggovi** [comment]
please test

**Comment by mmusich** [comment]
+1

**Comment by ggovi** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
