### PR TITLE
Initialize variables in tmtt::Settings

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

valgrind found use of uninitialized values for code that calls the default constructor.

#### PR validation:

Code compiles. Have not rerun valgrind yet.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
The valgrind report is

```
==3764354== Conditional jump or move depends on uninitialised value(s)
==3764354==    at 0x6DC4FB5: ??? (in /usr/lib64/libm-2.28.so)
==3764354==    by 0x6D5C407: pow (in /usr/lib64/libm-2.28.so)
==3764354==    by 0x5D910C71: tmtt::DigitalStub::DigitalStub(tmtt::Settings const*, double, double, double, unsigned int) (in /cvmfs/cms.cern.ch/el8_amd64_gcc12/cms/cmssw/CMSSW_14_1_0_pre5/lib/el8_amd64_gcc12/libL1TriggerTrackFindingTMTT.so)
==3764354==    by 0x5D95959D: tmtt::Stub::Stub(tmtt::Settings const*, unsigned int, double, double, double, double, unsigned int, double, unsigned int, unsigned int, bool, bool, bool, float, float, unsigned int) (in /cvmfs/cms.cern.ch/el8_amd64_gcc12/cms/cmssw/CMSSW_14_1_0_pre5/lib/el8_amd64_gcc12/libL1TriggerTrackFindingTMTT.so)
==3764354==    by 0x5D7C9103: trklet::HybridFit::Fit(trklet::Tracklet*, std::vector<trklet::Stub const*, std::allocator<trklet::Stub const*> >&) (in /cvmfs/cms.cern.ch/el8_amd64_gcc12/cms/cmssw/CMSSW_14_1_0_pre5/lib/el8_amd64_gcc12/libL1TriggerTrackFindingTracklet.so)
==3764354==    by 0x5D7EF92A: trklet::PurgeDuplicate::execute(std::vector<trklet::Track, std::allocator<trklet::Track> >&, unsigned int) (in /cvmfs/cms.cern.ch/el8_amd64_gcc12/cms/cmssw/CMSSW_14_1_0_pre5/lib/el8_amd64_gcc12/libL1TriggerTrackFindingTracklet.so)
==3764354==    by 0x5D8001F9: trklet::Sector::executePD(std::vector<trklet::Track, std::allocator<trklet::Track> >&) (in /cvmfs/cms.cern.ch/el8_amd64_gcc12/cms/cmssw/CMSSW_14_1_0_pre5/lib/el8_amd64_gcc12/libL1TriggerTrackFindingTracklet.so)
==3764354==    by 0x5D8516A0: trklet::TrackletEventProcessor::event(trklet::SLHCEvent&, std::vector<std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::allocator<std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > >&, std::vector<std::vector<trklet::StubStreamData, std::allocator<trklet::StubStreamData> >, std::allocator<std::vector<trklet::StubStreamData, std::allocator<trklet::StubStreamData> > > >&) (in /cvmfs/cms.cern.ch/el8_amd64_gcc12/cms/cmssw/CMSSW_14_1_0_pre5/lib/el8_amd64_gcc12/libL1TriggerTrackFindingTracklet.so)
==3764354==    by 0x5D6E5DAC: L1FPGATrackProducer::produce(edm::Event&, edm::EventSetup const&) (in /cvmfs/cms.cern.ch/el8_amd64_gcc12/cms/cmssw/CMSSW_14_1_0_pre5/lib/el8_amd64_gcc12/pluginTrackFindingTrackletPlugins.so)

==3764354==  Uninitialised value was created by a heap allocation
==3764354==    at 0x403BEE1: operator new(unsigned long) (in /cvmfs/cms.cern.ch/el8_amd64_gcc12/external/valgrind/3.23.0-143b83b3001a13f5bb2e0a4b5445fed5/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==3764354==    by 0x5D7C9F92: trklet::HybridFit::Fit(trklet::Tracklet*, std::vector<trklet::Stub const*, std::allocator<trklet::Stub const*> >&) (in /cvmfs/cms.cern.ch/el8_amd64_gcc12/cms/cmssw/CMSSW_14_1_0_pre5/lib/el8_amd64_gcc12/libL1TriggerTrackFindingTracklet.so)
==3764354==    by 0x5D7EF92A: trklet::PurgeDuplicate::execute(std::vector<trklet::Track, std::allocator<trklet::Track> >&, unsigned int) (in /cvmfs/cms.cern.ch/el8_amd64_gcc12/cms/cmssw/CMSSW_14_1_0_pre5/lib/el8_amd64_gcc12/libL1TriggerTrackFindingTracklet.so)
==3764354==    by 0x5D8001F9: trklet::Sector::executePD(std::vector<trklet::Track, std::allocator<trklet::Track> >&) (in /cvmfs/cms.cern.ch/el8_amd64_gcc12/cms/cmssw/CMSSW_14_1_0_pre5/lib/el8_amd64_gcc12/libL1TriggerTrackFindingTracklet.so)
==3764354==    by 0x5D8516A0: trklet::TrackletEventProcessor::event(trklet::SLHCEvent&, std::vector<std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::allocator<std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > >&, std::vector<std::vector<trklet::StubStreamData, std::allocator<trklet::StubStreamData> >, std::allocator<std::vector<trklet::StubStreamData, std::allocator<trklet::StubStreamData> > > >&) (in /cvmfs/cms.cern.ch/el8_amd64_gcc12/cms/cmssw/CMSSW_14_1_0_pre5/lib/el8_amd64_gcc12/libL1TriggerTrackFindingTracklet.so)
==3764354==    by 0x5D6E5DAC: L1FPGATrackProducer::produce(edm::Event&, edm::EventSetup const&) (in /cvmfs/cms.cern.ch/el8_amd64_gcc12/cms/cmssw/CMSSW_14_1_0_pre5/lib/el8_amd64_gcc12/pluginTrackFindingTrackletPlugins.so)

```

**Comment by skinnari** [comment]
FYI @tomalin

**Comment by Dr15Jones** [comment]
The DAS errors are seen elsewhere and are unrelated to this PR

**Comment by Dr15Jones** [comment]
please test

let's see if we get lucky this time

**Comment by tomalin** [comment]
This PR looks OK. Though the reason that the default constructor leaves data members undefined, is that if a CMSSW job calls  default constructor, it means that only a small fraction of the TMTT tracking algorithm is being run, so these undefined data members are not needed (and are not accessed). So the fix should not change performance.

**Comment by Dr15Jones** [comment]
@tomalin I believe your assumption about `so these undefined data members are not needed (and are not accessed).` is not correct as the valgrind job reports that the uninitialized data is being accessed.

**Comment by Dr15Jones** [comment]
With this change in, valgrind no longer reports the orginal issue. There is a new issue which I will look into

```
==1229070== Conditional jump or move depends on uninitialised value(s)
==1229070==    at 0x5D87CE23: tmtt::Utility::matchingTP(tmtt::Settings const*, std::vector<tmtt::Stub const*, std::allocator<tmtt::Stub const*> > const&, unsigned int&, std::vector<tmtt::Stub const*, std::allocator<tmtt::Stub const*> >&) (in /build/chrjones/dd4hep/CMSSW
_14_1_0_pre5/lib/el8_amd64_gcc12/libL1TriggerTrackFindingTMTT.so)
==1229070==    by 0x5D87D745: tmtt::Utility::matchingTP(tmtt::Settings const*, std::vector<tmtt::Stub*, std::allocator<tmtt::Stub*> > const&, unsigned int&, std::vector<tmtt::Stub const*, std::allocator<tmtt::Stub const*> >&) (in /build/chrjones/dd4hep/CMSSW_14_1_0_pre5
/lib/el8_amd64_gcc12/libL1TriggerTrackFindingTMTT.so)
==1229070==    by 0x5D6E98DD: trklet::HybridFit::Fit(trklet::Tracklet*, std::vector<trklet::Stub const*, std::allocator<trklet::Stub const*> >&) (in /build/chrjones/dd4hep/CMSSW_14_1_0_pre5/lib/el8_amd64_gcc12/libL1TriggerTrackFindingTracklet.so)
==1229070==    by 0x5D70F92A: trklet::PurgeDuplicate::execute(std::vector<trklet::Track, std::allocator<trklet::Track> >&, unsigned int) (in /build/chrjones/dd4hep/CMSSW_14_1_0_pre5/lib/el8_amd64_gcc12/libL1TriggerTrackFindingTracklet.so)
==1229070==    by 0x5D7201F9: trklet::Sector::executePD(std::vector<trklet::Track, std::allocator<trklet::Track> >&) (in /build/chrjones/dd4hep/CMSSW_14_1_0_pre5/lib/el8_amd64_gcc12/libL1TriggerTrackFindingTracklet.so)
==1229070==    by 0x5D7716A0: trklet::TrackletEventProcessor::event(trklet::SLHCEvent&, std::vector<std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::
allocator<char> > > >, std::allocator<std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > >&, std::vector<std::vector<trklet::St
ubStreamData, std::allocator<trklet::StubStreamData> >, std::allocator<std::vector<trklet::StubStreamData, std::allocator<trklet::StubStreamData> > > >&) (in /build/chrjones/dd4hep/CMSSW_14_1_0_pre5/lib/el8_amd64_gcc12/libL1TriggerTrackFindingTracklet.so)
==1229070==    by 0x5D605DAC: L1FPGATrackProducer::produce(edm::Event&, edm::EventSetup const&) (in /build/chrjones/dd4hep/CMSSW_14_1_0_pre5/lib/el8_amd64_gcc12/pluginTrackFindingTrackletPlugins.so)
```

**Comment by makortel** [comment]
@cms-sw/l1-l2 Could you please review and sign? Thanks!

**Comment by aloeliger** [comment]
@makortel are we expecting additional fixes from @Dr15Jones before this is finalized, or should we just sign now?

**Comment by Dr15Jones** [comment]
No additional changes are planned.

**Comment by aloeliger** [comment]
+l1

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
