### PR TITLE
Mark legacy EDModule constructors deprecated

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

We've noticed on a few occasions that marking the legacy EDModule base classes as `CMS_DEPRECATED` does not cover all the classes that inherit from these base classes. Marking functions deprecated seems to be more reliable to generate warnings, so this PR marks the constructors of the legacy EDModule base classes as `CMS_DEPRECATED`.

#### PR validation:

A legacy EDAnalyzer https://github.com/cms-sw/cmssw/blob/12_4_0_pre2/OnlineDB/SiStripO2O/plugins/SiStripPayloadMapTableCreator.cc that doesn't generate a warning in 12_4_0_pre2, generates a warning with this PR.

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
I checked to build log, and
* the warning from the class with deprecation annotation flagged 395 files
* the warning from the constructor with deprecation annotation flagged 455 files
* 303 files were the same, 92 were flagged by class annotation only, 152 were flagged by constructor annotation only

I checked a few of the files flagged by class annotation only, and in those the EDModule itself was already threading-aware, but the file `#include`d the header of a legacy module. I'm thinking to drop the class annotation, and go over the 92 files to remove the unnecessary `#include` (assuming they all were caused by that).

**Comment by Dr15Jones** [comment]
> I'm thinking to drop the class annotation, and go over the 92 files to remove the unnecessary #include (assuming they all were caused by that).

OK. Although it really is the class that is deprecated (so what is there is actually better documentation) and we want to get rid of those headers so we do want to catch cases where the header is improperly included.

**Comment by makortel** [comment]
> > I'm thinking to drop the class annotation, and go over the 92 files to remove the unnecessary #include (assuming they all were caused by that).
> 
> OK. Although it really is the class that is deprecated (so what is there is actually better documentation) and we want to get rid of those headers so we do want to catch cases where the header is improperly included.

I agree annotating the class is much more clear, but I was thinking if two different kinds of warnings for the same issue would be confusing. Or should we understand them as strictly speaking separate issues (`#include` of deprecated header vs. actually deriving from a deprecated class)?

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
@cmsbuild, please test

9.0 again

**Comment by makortel** [comment]
9.0 shows still differences. Maybe this is another symptom of https://github.com/cms-sw/cmssw/issues/34448? The changes in this PR are purely technical.

**Pull request merged**
