### PR TITLE
NanoAOD: runTheMatrix and cmsDriver support

### PR DESCRIPTION
**Pull request by arizzi**
this PR adds cmsDriver support for nanoAOD and some workflows in runTheMatrix.

In this PR we do NOT add NanoAOD to the standard runTheMatrix workflows and relvals so that we avoid spoiling the relval production with unknown output module.

On the other hand some workflows are defined to do dedicated tests of NanoAOD production 
runTheMatrix.py -l '1325.6,1325.7,1325.8,1329.1'

and can be used for injections tests

@gpetruc @fabozzi

### CODE REVIEW

**Comment by slava77** [comment]
@arizzi 
please add one workflow to the short matrix as well
https://github.com/cms-sw/cmssw/blob/3337ca4/Configuration/PyReleaseValidation/scripts/runTheMatrix.py#L60

**Comment by arizzi** [comment]
@slava77 I explicitelly removed it because we are not sure if the production infrastructure will handle it when making relvals. The plan is:
- in pre3 we test injecting by hand that Nano do not spoil anything
- once the above is verified we enable the workflows in the short list

(in fact 2659b762ce230d20d8275c23c0d01df855b11bfe explictelly disable those workflows)

**Comment by davidlange6** [comment]
adding a workflow to runTheMatrix has no effect on what is submitted to the relval system... Go ahead and add it back so it gets tested (aside from the production infrastructure) normally (and we can all more easily agree on what _should_ be tested in relvals once ready to do so.

**Comment by arizzi** [comment]
@davidlange6 see the comments from @fabozzi on #20626 

The workflows are anyhow tested with runtests.sh implemented and already merged in #20626

**Comment by davidlange6** [comment]
right - that is presumably why @slava77 suggested to "add one workflow".

**Comment by fabozzi** [comment]
@arizzi 
Adding the NanoAOD step only to 1 workflow (136.788) is fine to me. It will allow to test the wf already in the test, and in relval submission we can handle it (I was more against to add it to *all* upgrade relvals)

**Comment by slava77** [comment]
On 10/12/17 5:48 AM, arizzi wrote:
> @davidlange6 <https://github.com/davidlange6> see the comments from
> @fabozzi <https://github.com/fabozzi> on #20626
> <https://github.com/cms-sw/cmssw/pull/20626>

which of the comments was it?
IIRC the issue was with having nano appended to the standard wfs making
RECO/AOD.

> 
> The workflows are anyhow tested with runtests.sh implemented and already
> merged in #20626 <https://github.com/cms-sw/cmssw/pull/20626>

unit test outputs are not easily exposed (output files are not available
at all, only the log file is inlined in the combined unittests log).
Having it in the short matrix is much better.

**Comment by arizzi** [comment]
@slava77 @fabozzi 
just decide what you prefer
a) add 1 Nano-only WF , e.g. 1325.6, to the "limited" set in runTheMatrix 
b) add Nano step in one of the wf after RECO/AOD (e.g. restore 136.788+NANO)
c) both (a) and (b)

**Comment by slava77** [comment]
On 10/12/17 5:56 AM, arizzi wrote:
> @slava77 <https://github.com/slava77> @fabozzi <https://github.com/fabozzi>
> just decide what you prefer
> a) add 1 Nano-only WF , e.g. 1325.6, to the "limited" set in runTheMatrix
> b) add Nano step in one of the wf after RECO/AOD (e.g. restore 136.788+NANO)
> c) both (a) and (b)

either are fine for me
a) is more restrictive
because nano will have to be compatible with the globally distributed mini.

**Comment by fabozzi** [comment]
@slava77 @arizzi 
- add in shortMatrix 1325.6 can go plain to me
- adding the 136.788 with Nano step will produce a not-needed (for the moment) output in this relval. It is a minimal impact, so I have no objection if @slava77 thinks it is good to have it.

**Comment by arizzi** [comment]
so we go for (a) only using 1325.7 workflow (that is the "production workflow" with 2 steps)

**Comment by fabozzi** [comment]
please test

**Comment by arizzi** [comment]
you guys want to retrigger the tests with the update in the cmsDrivers in runtests.sh ?

**Comment by fabozzi** [comment]
please test

**Comment by fabozzi** [comment]
+1

**Pull request merged**
