### PR TITLE
relval matrix update

### PR DESCRIPTION
**Pull request by fabozzi**
using run 274199 for 2016B relvals
using 2016 data wf for testing
as discussed in PR #14839 
@slava77

### CODE REVIEW

**Comment by fabozzi** [comment]
please test

**Comment by slava77** [comment]
there should be a check for T2_CERN_CH in the DAS query of step1.
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-14869/13488/runTheMatrix-results/136.731_RunSinglePh2016B+RunSinglePh2016B+HLTDR2_2016+RECODR2_2016reHLT+HARVESTDR2/cmdLog
was it dropped intentionally?

The file is readable with xrootd  (I have ``` Successfully opened file root://xrootd-cms.infn.it//store/data ```).
@smuzaffar is it possible for jenkins jobs to have a grid proxy?

**Comment by smuzaffar** [comment]
@slava77 , yes we have a grid certificate for cmsbuild and we can have grid proxy.

**Comment by fabozzi** [comment]
please test

**Comment by fabozzi** [comment]
I have transferered files to T2_CERN_CH
@slava77 I think we dropped T2_CERN_CH check intentionally because it is giving frequent failures when preparing relval submissions (so we had to remove by hand every time)

**Comment by davidlange6** [comment]
+1

**Pull request merged**
