### PR TITLE
Pixel Heterogeneous DQM: add 1D differnce plots in vertex comparison module.

### PR DESCRIPTION
**Pull request by sroychow**
#### PR description:
This PR adds 1D difference histograms in Pixel vertex comparison module and makes the 2D comparison in x, y with the correction on top of Beamspot.

#### PR validation:
11634.503 runs.
#### if this PR is a backport please specify the original PR and why you need to backport that PR:
Backport to 12.4 and 12.3 needed.

### CODE REVIEW

**Comment by mmusich** [comment]
enable gpu

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
type tracking

**Comment by emanueleusai** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
