### PR TITLE
Added esConsumes to TauDiscriminationAgainstCaloMuon

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

Part of the esConsumes migration.

#### PR validation:

Code compiles.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
@makortel FYI

**Comment by Dr15Jones** [comment]
please test

**Comment by slava77** [comment]
+reconstruction

for https://github.com/cms-sw/cmssw/pull/35293	bbb1345
- code changes are technical, in line with the PR description/title
- jenkins tests pass and comparisons with the baseline show no (relevant) differences

**Comment by qliphy** [comment]
+1

**Pull request merged**
