### PR TITLE
Miscellaneous updates to CaloLayer1 DQM services

### PR DESCRIPTION
**Pull request by nsmith-**
93x PR #20465 

Do backports need code-check? seems pointless..

### CODE REVIEW

**Comment by dmitrijus** [comment]
@nsmith- Not really, but because the code-checks introduced a new commit upstream, this PR stops being a backport (and will not be merged).

In other words, both PRs should contain the exact same changes. And if you add a commit upstream, you should add it here too.

**Comment by nsmith-** [comment]
Ok I cherry-picked the code check.

**Comment by dmitrijus** [comment]
+1

**Comment by thomreis** [comment]
backport of #20465

**Comment by thomreis** [comment]
Hi @nsmith- 
Data taking with 92x has finished. This can be closed.

**Comment by davidlange6** [comment]
CMSSW_9_2_X developement work is completed. Closing remaining PRs

**Pull request closed without merging**
