### PR TITLE
Add tracking only PU workflows

### PR DESCRIPTION
**Pull request by AdrianoDee**
#### PR description:

This PR adds to the matrix the `trackingOnly` wfs with `PU`.

#### PR validation:

Running `11834.1` and `21034.1`.

### CODE REVIEW

**Comment by AdrianoDee** [comment]
test parameters:

- workflows = 11834.1, 22224.1
- relvals_opt= -w upgrade

**Comment by AdrianoDee** [comment]
please test

**Comment by AdrianoDee** [comment]
Indeed, I would add it to the release since I've received some requests about PU wf running tracking only that could be used for developments and it could ease things up. 

Anyway, I've tested the `22224.0` (that should have not been touched by this release) locally and it fails with the same error. Seems more a problem of the wf itself. I'm investigating it. In the meanwhile I'd restart the tests with the `D88` one.

**Comment by AdrianoDee** [comment]
test parameters:

- workflows = 11834.1, 21034.1
- relvals_opt= -w upgrade

**Comment by AdrianoDee** [comment]
please test

**Comment by srimanob** [comment]
+Upgrade

This PR add PU for tracking only workflows. Tested workflows, `11834.1, 21034.1`, run fine.

**Comment by srimanob** [comment]
Kindly ping @cms-sw/pdmv-l2

**Comment by srimanob** [comment]
@cmsbuild please test

Retrigger the test after almost 2 weeks.

**Comment by mmusich** [comment]
just to understand what's still pending here? @cms-sw/pdmv-l2

**Comment by kskovpen** [comment]
+pdmv

**Comment by rappoccio** [comment]
+1

**Pull request merged**
