### PR TITLE
Make sure the GlobalAlgBlk is not empty before accessing member data

### PR DESCRIPTION
**Pull request by apana**
Add a check that the GlobalAlgBlk is not empty when trying to get the prescale column number from the unpacked data

### CODE REVIEW

**Comment by fabiocos** [comment]
please test workflow 134.813

**Comment by fabiocos** [comment]
please test workflow 134.813

**Comment by rekovic** [comment]
+1

**Comment by rekovic** [comment]
@apana 
I know that your https://github.com/cms-sw/cmssw/pull/22962 includes the backport of this. 
For safety, can we please, have a 10_1_X PR which is just a backport  of this PR.

**Comment by fabiocos** [comment]
@dmitrijus @jfernan2 could you please check and sign?

**Comment by fabiocos** [comment]
+1

**Comment by thomreis** [comment]
Hi @apana 
why did you put the empty sum collection check back in? We have removed it because this causes alarms if the calo L2 is not in the run.

**Pull request merged**
