### PR TITLE
HIUCC offline DQM 2D sumEt vs SiPixelClusters

### PR DESCRIPTION
**Pull request by BetterWang**
2D histogram plot sumEt vs SiPixelClusters for HLT_HIUCC, same as #12522

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
Hi @BetterWang - could you give this PR a more descriptive title for the release notes? Thanks!

**Comment by davidlange6** [comment]
@BetterWang - ping?

**Comment by BetterWang** [comment]
Hi @davidlange6 , Sorry for the delay. Just updated the title and description.

**Comment by davidlange6** [comment]
Thanks!

**Comment by davidlange6** [comment]
+1

**Pull request merged**
