### PR TITLE
Do not dereference a nullptr in PATIsolatedTrackProducer

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

This was uncovered by UBSAN.

#### PR validation:

The code compiles. This is a technical change only and should have no effects on the outcome of a job.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by perrotta** [comment]
+1
- Technical fix
- Jenkins tests pass

**Comment by santocch** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
