### PR TITLE
fix DBG IBs warnings about EDM_ML_DEBUG redefined

### PR DESCRIPTION
**Pull request by smuzaffar**
In DBG IBs ( build with `-g -O3 -DEDM_ML_DEBUG` flags)  there many warnings about redefinition of EDM_ML_DEBUG. This PR proposes to either remove the definition from code or protect it by first checking if it is already set.

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by jfernan2** [comment]
+1

**Comment by yuanchao** [comment]
+1

* fixed EDM_ML_DEBUG redefined
* unit tests passed

**Comment by makortel** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
