### PR TITLE
Fix two bugs in CommonTools/Utils unit tests found by ASAN

### PR DESCRIPTION
**Pull request by dan131riley**
#### PR description:

ASAN found two fairly trivial bugs in the CommonTools/Utils unit tests.  One bug used the wrong type for the local geometry, which violated an assumption made by the BaseTrackerRecHit here:

https://github.com/cms-sw/cmssw/blob/30a2ff8ff13aaa416259453b54ad0b62588edc91/DataFormats/TrackerRecHit2D/interface/BaseTrackerRecHit.h#L29

The second bug takes a reference to a vector element which can be invalidated if the vector resizes.  This fix preallocates the vector so that it does not resize.

#### PR validation:

Tests were re-run in an ASAN build and verified that the bugs were fixed.  No effect on anything outside the package unit tests.

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by santocch** [comment]
+1

**Comment by perrotta** [comment]
@dan131riley , could you please about the bug fixed in ```testCutParser.cc```?
(Ok, it is test code which does not enter in any workflow; still, I would like to understand it, for my own education).

SiStripMatchedRecHit2D derives from BaseTrackerRecHit, and in both cases a ```GeomDet``` argument is required in the constructor, and not a ```TrackerGeomDet```. I would (naively?) say that either there is a bug in our code (which assumes ```TrackerGeomDet``` functionalities without requiring that class as argument), or this is not really a "bug" but simply there is an implicit assumption (certified by the ```static_cast```) that a ```TrackerGeomDet``` will be fed instead.

What is the correct explanation?

**Comment by dan131riley** [comment]
@perrotta Unfortunately, the GeomDet code is full of static casts that implicitly assume the types.  I took a look at what would be involved in changing BaseTrackerRecHit to take an explicit TrackerGeomDet, and found that the changes would ripple throughout the GeomDet code.  It would be a massive refactoring to make the code compile-time type safe.  It could be made run-time type safe by changing to dynamic casts.  I'm currently running a limited matrix with that one cast changed to be dynamic, but I don't expect it to find anything.  If it does, further investigation will certainly be warranted.

**Comment by perrotta** [comment]
> @perrotta Unfortunately, the GeomDet code is full of static casts that implicitly assume the types. I took a look at what would be involved in changing BaseTrackerRecHit to take an explicit TrackerGeomDet, and found that the changes would ripple throughout the GeomDet code. It would be a massive refactoring to make the code compile-time type safe. It could be made run-time type safe by changing to dynamic casts. I'm currently running a limited matrix with that one cast changed to be dynamic, but I don't expect it to find anything. If it does, further investigation will certainly be warranted.

Thank you Dan, this roughly corresponds to what I suspected. Indeed, a massive refactoring of the code would require a major effort, which certainly goes beyond the scope of these fixes. If really needed/wanted it should be rather coordinated by the tracking POG, I guess.
For the moment I think that the fix you are proposing here is safe enough for its purposes.

**Comment by perrotta** [comment]
+1
- Technical, and only affecting a test area
- Jenkins tests pass

**Comment by fabiocos** [comment]
+1

**Pull request merged**
