### PR TITLE
EL9: Fix OpenSSL warnings

### PR DESCRIPTION
**Pull request by smuzaffar**
These chanegs should fix the remaining OpenSSL warnings
```
PhysicsTools/SelectorUtils/interface/VersionedSelector.h:60:8: warning: 'unsigned char* MD5(const unsigned char*, size_t, unsigned char*)' is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
    60 |     MD5((unsigned char*)tracked.c_str(), tracked.size(), id_md5_);
```

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test for el9_amd64_gcc11

**Comment by smuzaffar** [comment]
+core

**Comment by emanueleusai** [comment]
Are the unit test failures in el9_amd64_gcc11 understood?

**Comment by smuzaffar** [comment]
please test for el9_amd64_gcc11
@emanueleusai , yes unit test for el9/gcc11 is known issue. el9/gcc11 is a new arch and was only added this week while PR tests were trying to use dasgoclinet from last week's IB area. Anyway, I have restarted the tests for el9/gcc11 and this time it should work

**Comment by smuzaffar** [comment]
el9/gcc11 unit test failed as we have not yet build any release for this architecture and that is why unit test failed to find dasgoclient.
```
ls: cannot access 'el9_amd64_*/cms/dasgoclient/v*/bin/dasgoclient': No such file or directory
ls: cannot access '/cvmfs/cms.cern.ch/el9_amd64_*/cms/dasgoclient/': No such file or directory
``` 

I will update bot to use `/cvmfs/cms-ib.cern.ch` instead of `/cvmfs/cms.cern.ch`

**Comment by jpata** [comment]
There are a lot of reco changes, already at the rechits. If I recall, this happened if e.g. random number generator state changed. Does this seem plausible here?

Independently, I see the reco-related changes are to the VIDSelector code. As I understand, @cms-sw/egamma-pog-l2 is using them in some private calibration workflows. Can you please verify that they still work with this PR?

**Comment by smuzaffar** [comment]
@jpata , these changes are for `el9/gcc11` vs `slc7/gcc10` so think these are fine. There are no changes for production arch https://github.com/cms-sw/cmssw/pull/37629#issuecomment-1103965841

**Comment by jpata** [comment]
oh, right. for my education, is the baseline the bot is using for the comparisons with the same arch as this test, or with the production arch?

**Comment by smuzaffar** [comment]
baseline is always generated (and used for comparsion) for the production arch of  the release e.g. for cmssw 12.4.X the production arch is `slc7_amd64_gcc10`. So even if PR tests are run for `*_ppc64le_*` the baseline will be from production arch

**Comment by jpata** [comment]
@smuzaffar this should also be testable (and give no differences) in the production arch, right? Just to make sure it does not break private egamma code.

**Comment by smuzaffar** [comment]
yes @jpata  , it has already been tested  see https://github.com/cms-sw/cmssw/pull/37629#issuecomment-1103965841

**Comment by tvami** [comment]
type bug-fix

**Comment by tvami** [comment]
+db
 * unit test testing the changes passes
 * jenkins tests pass

**Comment by mmusich** [comment]
> ---> test testCalibTrackerSiStripESProducersByHand had ERRORS
---> test testPixelDBs had ERRORS
---> test testCondToolsSiStripBuildersReaders had ERRORS

all of this is related to https://github.com/cms-sw/cmssw/pull/37593#issuecomment-1109170271

**Comment by tvami** [comment]
@cmsbuild , please test with https://github.com/cms-sw/cmssw/pull/37674

**Comment by emanueleusai** [comment]
+1

**Comment by smuzaffar** [comment]
@cms-sw/generators-l2 kind reminder to review this

**Comment by SiewYan** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
