### PR TITLE
Geometry: Move DOMCount Regression Test to Geometry/CMSCommonData

### PR DESCRIPTION
**Pull request by ianna**
#### PR description:

* The DOMCount test has been failing regularly due to the frequent changes in the list of the scenarios. Move it closer to the responsible for the changes package.

#### PR validation:

```scram b runtests``` should trigger an appropriate test

#### if this PR is a backport please specify the original PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by ianna** [comment]
@smuzaffar and @mrodozov - FYI. This should fix the regular failures for good.

**Comment by ianna** [comment]
please test

**Comment by fabiocos** [comment]
@ianna @smuzaffar as far as I can see this addresses the failure https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc700/CMSSW_11_0_X_2019-07-11-1100/unitTestLogs/DetectorDescription/RegressionTest#/3445-3445 starting in CMSSW_11_0_X_2019-07-10-2300 due to the update in #27449

**Comment by ianna** [comment]
+1

**Comment by ianna** [comment]
> @ianna @smuzaffar as far as I can see this addresses the failure https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc700/CMSSW_11_0_X_2019-07-11-1100/unitTestLogs/DetectorDescription/RegressionTest#/3445-3445 starting in CMSSW_11_0_X_2019-07-10-2300 due to the update in #27449

Yes, we've discussed this with @mrodozov and @smuzaffar this morning. If @kpedro88 has time he could update the shell script to pick up the list of files for the test automatically...

**Comment by kpedro88** [comment]
@ianna I will rebase the renaming PR on top of this one and try to automate the list of phase 2 geometry files used here

**Comment by kpedro88** [comment]
+upgrade

**Comment by fabiocos** [comment]
+1

@ianna thanks for fixing the problem. I am not sure that moving the test in another place will significantly improve the situation in case of changes, but it does not harm and it may be logically motivated

**Pull request merged**
