### PR TITLE
MTD geometry: remove code for obsolete ETL ring-based scenario

### PR DESCRIPTION
**Pull request by fabiocos**
#### PR description:

In this PR the MTD geometry description, both in the ```Geometry``` and ```RecoMTD``` packages, is cleaned by removing code that refers to the ETL ring-based scenario. The latest default scenario when this was active was D49, dropped from the release since a while.

The ETL numbering scheme is cleaned for the corresponding possible numbering construction.

At the same time, the unit test in ```RecoMTD/DetLayers``` is updated, by adding a test of the module finding in BTL with a scan in phi at fixed z.

#### PR validation:

Code compiles, the MTD geometry unit tests are correctly running.

### CODE REVIEW

**Comment by fabiocos** [comment]
please abort

**Comment by fabiocos** [comment]
hold

**Comment by fabiocos** [comment]
unhold

**Comment by fabiocos** [comment]
please test with https://github.com/cms-data/Geometry-TestReference/pull/13

**Comment by civanch** [comment]
+1

**Comment by emanueleusai** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

Code cleaning on obsolete geometry. No change is expected from current Phase-2 workflows.

**Comment by clacaputo** [comment]
+reconstruction

**Comment by perrotta** [comment]
> please test with [cms-data/Geometry-TestReference#13](https://github.com/cms-data/Geometry-TestReference/pull/13)

@fabiocos I miss to recognize where this external data file is accessed in this code: could you please point it out to me?

**Comment by fabiocos** [comment]
@perrotta it is the reference file used in the unit test of ```RecoMTD/DetLayers```: https://github.com/cms-sw/cmssw/blob/master/RecoMTD/DetLayers/test/runTest.sh#L18
This PR adds, on top of the cleaning, an extra printout to show that the reconstruction navigation geometry correctly find modules at a fixed z in BTL while performing a scan. This test is useful also related to the checks mentioned in https://indico.cern.ch/event/1306288/contributions/5493532/attachments/2683819/4656070/MTDDPG-BTLmatching_20230714.pdf , which were based on https://github.com/cms-sw/cmssw/pull/42178

**Comment by fabiocos** [comment]
PS: more cleaning could be done in the BTL geometry part, once MTD geometry scenario I15 is definitely kicked out of the release cycle, see https://github.com/cms-sw/cmssw/blob/master/Configuration/Geometry/README.md

**Comment by perrotta** [comment]
+1

**Pull request merged**
