### PR TITLE
DRAFT: nano: adaptation to run in Prompt

### PR DESCRIPTION
**Pull request by mariadalfonso**
This draft PR: attempt to update the nano sequence to run together with mini (reco + DQM)
* replaced all the Sequence with Task (this is needed otherwise we have "ScheduleExecutionFailure"
very long list of modules with order problems here ~ http://dalfonso.web.cern.ch/dalfonso/orderingModulesNano.txt)
* moved some customisation from nano_cff to each object

For the moment: photon/electron//METrecalibration are dummy
These objects recycle sequence used for miniAOD called from inside the nano_cff.py
I will need to follow with EGM/JME POGS
run3_nanoAOD_devel at the end should not be used as the master version should be able to run straigh on the newer nano.

TESTED so far:
1)  nanoGen (porting complete) wf 546 works

2) 106Xv2 (i.e. nanoV9) wf 136.8523 runs

3) cmsDriver.py step3 --conditions auto:phase1_2021_realistic -s RAW2DIGI,L1Reco,RECO,RECOSIM,EI,PAT,NANO,VALIDATION:@standardValidation+@miniAODValidation,DQM:@standardDQM+@ExtraHLT+@miniAODDQM --datatier GEN-SIM-RECO,MINIAODSIM,NANOAODSIM,DQMIO -n 10 --geometry DB:Extended --era Run3,run3_nanoAOD_devel --eventcontent RECOSIM,MINIAODSIM,NANOEDMAODSIM,DQM --filein file:step2.root --fileout file:step3.root

runs with step2 from wf 11634.0

4) previous eras fails tested because of the shortcut  in photon/electron/tau/boostedtau/METrecalibration 
136.8521 (102Xv1)
136.7952 (94Xv2)

5) JMEnano will stop working:
JME sequences too customs and need to by updated by JME
https://github.com/cms-sw/cmssw/blob/master/PhysicsTools/NanoAOD/python/custom_jme_cff.py

### CODE REVIEW

**Comment by mariadalfonso** [comment]
please test 546,547,548

(nanoGen workflows)

**Comment by smuzaffar** [comment]
please test workflow 546.0,547.0,548.0

**Comment by mariadalfonso** [comment]
please test workflow 546.0

**Comment by mariadalfonso** [comment]
not clear why all WF are tested and not only what we asked in https://github.com/cms-sw/cmssw/pull/34329#issuecomment-873669421 and https://github.com/cms-sw/cmssw/pull/34329#issuecomment-873654447
It seems that the test asked are in addition, not exclusively

regarding the 546.0,547.0,548.0
they run as expected https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-be3056/16453/summary.html
and 546.0 pass as expected https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-be3056/16454/summary.html

for the rest, I will update the PR once I talked to the EGM/TAU/JME as mentioned I the PR description

**Comment by makortel** [comment]
> not clear why all WF are tested and not only what we asked in [#34329 (comment)](https://github.com/cms-sw/cmssw/pull/34329#issuecomment-873669421) and [#34329 (comment)](https://github.com/cms-sw/cmssw/pull/34329#issuecomment-873654447)
> It seems that the test asked are in addition, not exclusively

Correct, the explicitly asked workflows are run in addition to the standard set of workflows run in the tests.

**Comment by mariadalfonso** [comment]
please test workflow 136.8523

**Comment by mariadalfonso** [comment]
please test

**Comment by mariadalfonso** [comment]
please test

**Comment by mariadalfonso** [comment]
@makortel 
do you know what can cause this crash ?
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-be3056/16921/runTheMatrix-results/1325.81_TTbar_13_106Xv1NanoAODINPUT+TTbar_13_106Xv1NanoAODINPUT+NANOEDMMC2017_106XMiniAODv1+HARVESTNANOAODMC2017_106XMiniAODv1/step2_TTbar_13_106Xv1NanoAODINPUT+TTbar_13_106Xv1NanoAODINPUT+NANOEDMMC2017_106XMiniAODv1+HARVESTNANOAODMC2017_106XMiniAODv1.log

**Comment by makortel** [comment]
> do you know what can cause this crash ?

Never seen before, I opened an issue https://github.com/cms-sw/cmssw/issues/34523

**Comment by makortel** [comment]
@cmsbuild, please test

Let's see if it was random or reproducible

**Comment by mariadalfonso** [comment]
@cmsbuild, please test

(sorry I interrupted Matti test)

**Comment by mariadalfonso** [comment]
@makortel 
The error seems reproducible although if process a different set of events
i.e. the 1325.81 crash once at the 23 and once at the 13

**Comment by makortel** [comment]
@mariadalfonso Note that the stack traces in https://github.com/cms-sw/cmssw/pull/34329#issuecomment-881866660 are different than in the earlier test. These symptoms support the "something overwriting memory" hypothesis in https://github.com/cms-sw/cmssw/issues/34523. Valgrind pointed to some invalid writes in `pat::MET`.

**Comment by Dr15Jones** [comment]
This appears to be a bug in the pat::MET object

https://github.com/cms-sw/cmssw/issues/34523#issuecomment-882643898

**Comment by makortel** [comment]
It seems to me that something in this PR leads to `pat::MET` being used in incorrect way in `SimpleFlatTableProducer`. Adding the assertion @Dr15Jones suggested in https://github.com/cms-sw/cmssw/issues/34523#issuecomment-882643898 could help to debug further.

**Comment by mariadalfonso** [comment]
please test

**Comment by mariadalfonso** [comment]
please test

**Comment by mariadalfonso** [comment]
status so far :)

0. the 8X fail on the genSubJetAK8Table (module that should be deactivated)
1. differences are seen in the ele.photon.met as expected (since I deactivated them),
but the jetTable should not show any difference in the run2_nanoAOD_106Xv1 and run2_nanoAOD_106Xv2 , and it does
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_0_X_2021-07-25-2300+be3056/44349/validateJR.html

once I fix this jet, I move all the non ele/ph/met in a separate PR that can be merged right away w.o breaking anything

**Comment by mariadalfonso** [comment]
please test

**Comment by mariadalfonso** [comment]
I close this, given that has been splitted in 3 smaller PRs

**Pull request closed without merging**
