### PR TITLE
Revert "Revert "Run3-gex83B Convert all SD's in SimG4CMS/ShowerLibraryProducer using the new way of initiating""

### PR DESCRIPTION
**Pull request by qliphy**
Reverts cms-sw/cmssw#34535
Following https://github.com/cms-sw/cmssw/issues/34533#issuecomment-881894360

### CODE REVIEW

**Comment by qliphy** [comment]
please test

**Comment by qliphy** [comment]
@bsunanda @civanch Let's re-test this. Sorry for the inconvenience.

**Comment by civanch** [comment]
@qliphy ,   sorry for the mess.

**Comment by bsunanda** [comment]
I wonder why you reverted this. I would have made necessary changes in a future PR
________________________________

**Comment by civanch** [comment]
@bsunanda , yes, I was wrong.

**Comment by civanch** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
