### PR TITLE
MultiCluster-CaloParticle associator

### PR DESCRIPTION
**Pull request by lecriste**
#### PR description:

This PR introduces an associator that can be consumed by several analyzers, removing code duplication. The first replacement is made for the `HGVHistoProducerAlgo::fill_multi_cluster_histos` method, no changes are expected in the output.

#### PR validation:

`runTheMatrix -l limited`

### CODE REVIEW

**Comment by slava77** [comment]
> Code check has found code style and quality issues which could be resolved by applying following patch(s)

please follow up; we can not do further tests without it

**Comment by slava77** [comment]
> > Code check has found code style and quality issues which could be resolved by applying following patch(s)
> 
> please follow up; we can not do further tests without it

**Comment by slava77** [comment]
@lecriste 
(tagging explicitly, in case the earlier messages got lost)

**Comment by lecriste** [comment]
Hi Slava, after opening the PR I found a corner case in which results differ from original code.
I would push the code-checks patch together with the fix commit once I have it.
Please let me know if that's not OK with you.

**Comment by slava77** [comment]
>  Please let me know if that's not OK with you.

OK.
I was just pinging to make sure you received the message(s).

**Comment by slava77** [comment]
@lecriste 
please clarify on the current status of the PR
Thank you.

**Comment by lecriste** [comment]
We decided to change a reco DataFormat (the Trackster) along with a SimDataFormat, in order to proceed with the implementation of the associator in this PR and, at the same time, keep the current feature of a dedicated validation per TICL iteration.
I am using this branch to test locally the DataFormat change, once happy I will open a separated PR for that and then come back to this one.

**Comment by silviodonato** [comment]
@lecriste I converted this PR to a draft. Please re-open this PR when it is ready to be reviewed.

**Comment by slava77** [comment]
@lecriste 
please clarify on the status and plans for this PR.
Thank you.

**Comment by lecriste** [comment]
I need to rebase it to the other merged/open PRs and adapt the code to use the new Trackster data format.
Will do by next week.

**Comment by lecriste** [comment]
This PR is superseded by #33384, which contains only the associator implementation.
We do not use it in `Validation/HGCalValidation/src/HGVHistoProducerAlgo.cc` because we are going to replace `MultiCluster` with `Trackster` therein.

**Pull request closed without merging**
