### PR TITLE
Fix thread safety issue in HLTBTagPerformanceAnalyzer

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

Make global variables const, move them to anonymous namespace. Fixes workflow 10803.0 that fails in the latest IB (following the merge of https://github.com/cms-sw/cmssw/pull/28813)
http://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc820/CMSSW_11_1_X_2020-03-03-1100/pyRelValMatrixLogs/run/10803.0_SingleElectronPt1000+SingleElectronPt1000_pythia8_2018_GenSimFullINPUT+DigiFull_2018+RecoFull_2018+HARVESTFull_2018+ALCAFull_2018+NanoFull_2018/step3_SingleElectronPt1000+SingleElectronPt1000_pythia8_2018_GenSimFullINPUT+DigiFull_2018+RecoFull_2018+HARVESTFull_2018+ALCAFull_2018+NanoFull_2018.log

Made jointly with @Dr15Jones.

#### PR validation:

Workflow 10803.0 runs.

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test workflow 10803.0

**Comment by silviodonato** [comment]
merge

dqm:  @andrius-k @jfernan2 @kmaeshima @fioriNTU @schneiml
Please have a look. I merged because I wanted this PR in the night IB and in pre4.

**Comment by jfernan2** [comment]
+1

**Comment by schneiml** [comment]
Thanks @makortel !

Also, seeing the PR test results as of now, which now compare the `edm::stream` DQM modules running multi-trheaded (in the IB) and single-threaded (in the PR tests), it seems that apart from the well-known `LETDC` plots, everything reproduces properly (and we should blacklist those 3 `ProvInfo` MEs). This is much better than I feared!

**Pull request merged**
