### PR TITLE
Fix phase2 tracker premixed digis

### LINKED ISSUE #29563: Phase2 Tracker Premixed DIGIs are broken
Two problems have been detected in the Premixing vs Standard Mixing validation for the Phase-2 Trackers:

## Issue with Inner Tracker digis
Full details in this presentation from @suchandradutta:

https://indico.cern.ch/event/879033/contributions/3840120/.

In short:
- premixing stage1 uses a single electron to ADC (=135) conversion factor for both IT (inner tracker) / OT  (outer tracker)
https://github.com/cms-sw/cmssw/blob/9abb3c7dc5a6754abec4dd055d3b52a490b33bfd/SimTracker/SiPhase2Digitizer/python/phase2TrackerDigitizer_cfi.py#L230-L240
- premixing stage2 (first step) uses again the same value for both IT and OT https://github.com/cms-sw/cmssw/blob/9abb3c7dc5a6754abec4dd055d3b52a490b33bfd/SimGeneral/PreMixingModule/python/mixOne_premix_on_sim_cfi.py#L227
- the final digitization step in stage2 uses instead 600 for IT: https://github.com/cms-sw/cmssw/blob/9abb3c7dc5a6754abec4dd055d3b52a490b33bfd/SimTracker/SiPhase2Digitizer/python/phase2TrackerDigitizer_cfi.py#L23 while 135 is used for OT: https://github.com/cms-sw/cmssw/blob/9abb3c7dc5a6754abec4dd055d3b52a490b33bfd/SimTracker/SiPhase2Digitizer/python/phase2TrackerDigitizer_cfi.py#L105

As a result of the double (lossy) conversion performed with different conversion factors in the Inner Tracker there is a noticeable change in the final ADC distributions (red is Premixing, green is Std Mixing)

image

Few concrete examples for some `SimHits` are as follows:

| Charge [e-] | Charge (ADC) (standard mix) e/ADC = 600 | Charge [ADC] (premix step1) e/ADC = 135 | Charge [e-] (premix step2) e/ADC = 135 | Charge [ADC] (premix final) e/ADC = 600 |
| ------------- | ------------- | ------------- | ------------- | ------------- |
| 3639.4 | 6 (6.07) | 26 | 3510.0 | 5 (5.85) | 
| 8435.7 | 14 (14.06) | 62| 8370.0 | 13 (13.95)|
| 9000.6 |15 (15.0) | 66 | 8910.0 | 14 (14.85)| 
| 4234.6 | 7 (7.06) | 31 | 4185.0 | 6 (6.97) |
|13896.1 |23 (23.16) | 102 | 10037.7 | 22 (22.95) |

This in principle can be recovered by allowing the collections of `PixelDigi`s produced by the premixing stage1 and the signal digitization in step2 with two different conversion factor for IT and OT and then let the `PreMixingPhase2TrackerWorker` to undo the conversion separately for IT and OT.

## Issue with Outer Tracker digis
In addition it was noticed that the fraction of OverThreshold digis in the premixed case for the PS modules is always 1, while it has a non-trivial distribution for the standard mixing case, see plot below:

image
 
As a possible solution we need to  configure the digitizer to have analog readout for OT (at least for the PSS layers) at step 1 of pre-mixing, as the actual charge information is essential.

cc:
@suchandradutta @emiglior @skinnari @tsusa

### PR DESCRIPTION
**Pull request by mmusich**
resolves https://github.com/cms-sw/cmssw/issues/29563

#### PR description:

Solves the two issues reported at https://github.com/cms-sw/cmssw/issues/29563 by:
1. allowing the collections of `PixelDigi`s produced by the premixing stage-1 and the signal digitization in step2 with two different conversion factor for IT and OT and then let the PreMixingPhase2TrackerWorker to undo the conversion separately for IT and OT.
2.  configuring the Phase-2 digitizer to have analog readout for OT (for the PSS layers) at step 1 of pre-mixing, as actual charge information is essential.

#### PR validation:

Validation has been run twice:
  *  I tested wf 23461.99 (SingleNu gun - premixed, PU=200, Geometry = D49) and compared it with the same workflow run in a vanilla CMSSW_11_1_0_pre6 release and with the equivalent standard mixing workflow 23461.0 (SingleNu gun - standard mixing, PU=200, Geometry = D49).
  * @suchandradutta tested also the changes with a signal TTbar + PU=200 sample and obtained the results below:

1. IT digis issue: 
image

2. OT digis issue:
image

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

This PR is not a backport.
@suchandradutta @emiglior @skinnari @tsusa

### CODE REVIEW

**Comment by kpedro88** [comment]
test parameters
workflows = 20634.99

**Comment by kpedro88** [comment]
please test

**Comment by kpedro88** [comment]
+upgrade

**Comment by civanch** [comment]
+1

**Comment by silviodonato** [comment]
please test workflow 23234.1001, 23434.1001

**Comment by silviodonato** [comment]
+1

**Pull request merged**
