### PR TITLE
[13_1_X] Update 2023 MC GT, VtxSmearing, PU library and fix RPC geometry in 2022/2023 MC GTs

### PR DESCRIPTION
**Pull request by saumyaphor4252**
#### PR description:

Backport of https://github.com/cms-sw/cmssw/pull/42139 and https://github.com/cms-sw/cmssw/pull/42265

This PR updates:

- The 2023 MC realistic GTs
  - See this [CMSTalk post](https://cms-talk.web.cern.ch/t/mc-call-for-conditions-for-2023-mc/24376/21) for a full list of updates
- New VtxSmearing for 2023 (`Realistic25ns13p6TeVEarly2023Collision`) included in https://github.com/cms-sw/cmssw/pull/41719
- The 2023 GEN-SIM PU library compatible with the 2023 BeamSpot
    - The samples have been produced by PdmV in [PDMVRELVALS-203](https://its.cern.ch/jira/browse/PDMVRELVALS-203)

In addition
- All the 2022 and 2023 MC GTs are updated with the RPC geometry fix for the issue in the RPC chambers requested in [this CMS Talk post](https://cms-talk.web.cern.ch/t/fix-for-rpc-geometry-for-run3-data-and-mc/25678) [1]. 

[1] https://cms-talk.web.cern.ch/t/fix-for-rpc-geometry-for-run3-data-and-mc/25678

**GT Differences**:
- See master PRs

#### PR validation:
GTs tested locally with `runTheMatrix.py -l 12034.0,11634.0,7.23,7.24,159.0,159.1,12434.0,160.1,12834.0  -j 8 --ibeos` and `runTheMatrix.py -l 13734.0 --what upgrade`

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

backport of https://github.com/cms-sw/cmssw/pull/42139 and https://github.com/cms-sw/cmssw/pull/42265

### CODE REVIEW

**Comment by saumyaphor4252** [comment]
backport of https://github.com/cms-sw/cmssw/pull/42139

**Comment by saumyaphor4252** [comment]
test parameters:

- workflows = 12034.0,11634.0,7.23,7.24,159.0,159.1,12434.0,160.1,12834.0

**Comment by saumyaphor4252** [comment]
backport of https://github.com/cms-sw/cmssw/pull/42265

**Comment by srimanob** [comment]
@cmsbuild please test

**Comment by tvami** [comment]
+alca

**Comment by srimanob** [comment]
Kindly ping @cms-sw/pdmv-l2 
So that I can make backport of FastSim. Thx.

**Comment by sunilUIET** [comment]
+pdmv

**Comment by francescobrivio** [comment]
@perrotta @rappoccio ping - can we merge this asap?
It's blocking the 131X backport of https://github.com/cms-sw/cmssw/pull/42358 , and AFIU all the other release backports are merged already

**Comment by rappoccio** [comment]
+1

**Pull request merged**
