### PR TITLE
Migrate CondTools-Ecal modules to use esconsumes

### PR DESCRIPTION
**Pull request by sroychow**
#### PR description:
Part of #31061. Migrates modules of ```CondTools/Ecal``` to use esConsumes. 

#### PR validation:
Code compiles and scram checker doesn't show the EventSetup get warnings.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:
NA.

### CODE REVIEW

**Comment by sroychow** [comment]
@cmsbuild please test

**Comment by ggovi** [comment]
+1

**Review by perrotta — COMMENTED** [review]
Migration in the package is not complete yet: still missing CondTools/Ecal/src/ESDBCopy.cc

Please also have a look at the static analyzer, which points out a large number of dead initializations or assignments. That should also get eventually fixed, (not necessarily in this PR) as those dead assignments may hide/witness possible real issues in the logic of the code.

**Comment by thomreis** [comment]
> Migration in the package is not complete yet: still missing CondTools/Ecal/src/ESDBCopy.cc
> 
This is done in #35149 .

**Comment by sroychow** [comment]
@cmsbuild please test

**Comment by tvami** [comment]
+db

* Giacomo already signed a previous version

**Comment by perrotta** [comment]
+1

**Pull request merged**
