### PR TITLE
added esConsumes to modules in L1Trigger/TrackTrigger

### PR DESCRIPTION
**Pull request by JamminJones**
#### PR description:
added esConsumes to 2 modules 

#### PR validation:

the code compiles

### CODE REVIEW

**Comment by Dr15Jones** [comment]
This was done under my supervision. The developer is my son.

**Comment by kpedro88** [comment]
please test

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
ping

**Comment by kpedro88** [comment]
+upgrade

**Comment by silviodonato** [comment]
merge
cc: @rekovic

**Pull request merged**
