### PR TITLE
[12.4.X] Limit `SiPixelLA` and `SiSiStripHitEff` PCL DB uploads to avoid opening spurious IoVs

### PR DESCRIPTION
**Pull request by mmusich**
backport of #38481

#### PR description:

It was noticed by shifters that in the [pclSpy](https://cms-conddb-prod.cern.ch/pclSpy/app/workflow?runClass=Collisions22) the `SiPixelLA_pcl` and `SiStripBadStripRcdHitEff_pcl` keep being updated even if other tracker worfklows are not (e.g. because the tracker is not in Global DAQ or the HV is not ON). This happens because in both cases, even if either the payload is identical to the one on the last open IOV (in the Lorentz Angle case) or if there are no valid counts to extract a hit efficiency measurement, some "null" payloads are uploaded anyway (see e.g. [LA tag](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/tags/SiPixelLorentzAngle_byPCL_v0_prompt) and [BadComponents from hit efficiency tag](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/tags/SiStripBadChannel_FromHitEfficiency_v0_prompt)). This can cause some confusion to non-expert eyes. This PR solves the issue - as well as removing the minimal DB overhead of dealing with unnecessary uploads.

#### PR validation:

`cmssw` compiles, run successfully unit tests as well as `runTheMatrix.py -l 1001.0,1001.2 -t 4 -j 8`

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

verbatim backport of #38481

### CODE REVIEW

**Comment by francescobrivio** [comment]
type trk,performance-improvements

**Comment by francescobrivio** [comment]
test parameters:

 - workflows = 1001.0,1001.2

**Comment by francescobrivio** [comment]
@cmsbuild please test

**Comment by tvami** [comment]
+alca
 * master working fine in the IBs

**Comment by perrotta** [comment]
+1

**Pull request merged**
