### PR TITLE
DD Generic Singleton Pattern

### PR DESCRIPTION
**Pull request by ianna**
* Simple to reuse the same implementation across all singletons use cases
* More than a single singleton can be constructed for the same type
* A singleton can be applied to any type which one can construct, not necessarily with a default constructor
* Defer the singleton initialization until the first use
* The singleton initialization is thread safe:
    * Only a single thread will initialize the singleton
    * All the threads will use the same initialized instance
* Using  the singleton is as fast as direct pointer access
* Add unit test and a couple of tests for valgrind

```
$ valgrind --leak-check=full --show-leak-kinds=all ../../../test/slc6_amd64_gcc630/testSingleton
==16045== Memcheck, a memory error detector
==16045== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==16045== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==16045== Command: ../../../test/slc6_amd64_gcc630/testSingleton
==16045== 
Hello world
==16045== 
==16045== HEAP SUMMARY:
==16045==     in use at exit: 0 bytes in 0 blocks
==16045==   total heap usage: 2 allocs, 2 frees, 72,736 bytes allocated
==16045== 
==16045== All heap blocks were freed -- no leaks are possible
==16045== 
==16045== For counts of detected and suppressed errors, rerun with: -v
==16045== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 4 from 4)

```
```
$ valgrind --leak-check=full --show-leak-kinds=all ../../../test/slc6_amd64_gcc630/testSingletonInit 
==2464== Memcheck, a memory error detector
==2464== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==2464== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==2464== Command: ../../../test/slc6_amd64_gcc630/testSingletonInit
==2464== 
Initialized
Hello
==2464== 
==2464== HEAP SUMMARY:
==2464==     in use at exit: 0 bytes in 0 blocks
==2464==   total heap usage: 2 allocs, 2 frees, 72,736 bytes allocated
==2464== 
==2464== All heap blocks were freed -- no leaks are possible
==2464== 
==2464== For counts of detected and suppressed errors, rerun with: -v
==2464== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 4 from 4)
```
Note, test1 uses getInstance():
```
Package DetectorDescription/DDCMS: Running test testSingletonBenchmark
 
===== Test "testSingletonBenchmark" ====
Benchmark 'test1' took 0.000699 millis
Benchmark 'test2' took 0.001109 millis
Benchmark 'test3' took 0.001125 millis
Benchmark 'test4' took 0.000953 millis
Benchmark 'test5' took 0.000975 millis
Benchmark 'test6' took 0.001117 millis

---> test testSingletonBenchmark succeeded
```

### CODE REVIEW

**Comment by Dr15Jones** [comment]
I believe a better way is to use a static `getInstance()` class method. The method would be written as
```C++
template<typename T>
T* getInstance() {
   static std::unique_ptr<T> s_instance{ std::make_unique<T>() };
   return s_instance.get();
}
```

This avoids the problem of having to declare the `m_instance` as well as `__attribute__(( unused ))` specification.

I would then change your class to hold the pointer, thereby avoiding the slight overhead of calling `getInstance()` on each use of `DDSingleton`.
```C++
DDSingleton() : m_instance(getInstance()) {}
...
T* m_instance;
```

**Comment by ianna** [comment]
@Dr15Jones - Thanks for looking into this! I just fancied using lambda expressions and the C++11 thread safety guarantee for function-local statics. I'll implement your suggestion and run the comparison tests.

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
+1

**Pull request merged**
