### PR TITLE
Enable fastjet area computation by default

### PR DESCRIPTION
**Pull request by ahinzmann**
This is usually activated in:
https://github.com/cms-sw/cmssw/blob/CMSSW_7_4_X/RecoJets/Configuration/python/RecoPFJets_cff.py#L38
However, if people pick up the original cfis for the jet producers, the end up with jets without area computed and wrong L1 jet energy corrections applied.
This pull request is to avoid this very frequent bug once and for all.

This PR has no effect on RECO/AOD/MiniAOD, since there fastjet area computation is already activated.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

Andreas,  which collections now have it enabled and what's the effect on timing for them?
(in case, say, this comes at a cost in GEN or similar fast workflows)

**Comment by ahinzmann** [comment]
Indeed GenJets shouldn't be touched, so I inverted that.
Now it should have absolutely no impact on timing and size of any workflow in the matrix.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
... checking this locally (not everything is monitored in DQM/validation to be noticed in jenkins diffs)

**Comment by ahinzmann** [comment]
I didn't explicitly check if this affects HLT somehow.
Checkdeps didn't find any connection to HLT, but it probably can't do that.
git cms-checkdeps
>> Checking RecoJets/JetProducers CMSSW_7_6_X_2015-08-31-2300
   x RecoJets/JetProducers/python/PFJetParameters_cfi.py
Packages to check out and compile: 3
FastSimulation/ParticleFlow (python)
RecoHI/HiJetAlgos (python)
TopQuarkAnalysis/TopPairBSM (python)

**Comment by slava77** [comment]
Andreas,

I observe behavior different from what you are claiming in the PR subject: 
some jets change and it's not clear to me if the area computation is meaningful for them.

In the regular pp data/MC processing workflows we get ak8PFJetsCHSFiltered, ak8PFJetsCHSPruned, and ak8PFJetsCHSSoftDrop now running with jet area (previously set to false). Here it triggers an increase in CPU by about a factor of 10 on PU~20 data (from ~4-5 ms/evt to ~50 ms/evt for each module). 
This is a 1% increase of total RECO time and should have a reasonable explanation for the introduced cost.

Please comment.

**Comment by ahinzmann** [comment]
In the past the knowledge of the jet area of groomed jets compared to ungroomed jets and was used to estimate the difference in L1FastJet jet energy corrections for these different jet types. That allowed to make sure that the jet energy scale of ungroomed jets was usable for groomed jets. (I was not aware we never computed this info in RECO)
I would personally judge this important enough to have this info in RECO/AOD and MiniAOD.
@rappoccio @jdolen @nhanvtran : What is your take?

**Comment by slava77** [comment]
On 9/8/15 3:37 AM, ahinzmann wrote:
> In the past the knowledge of the jet area of groomed jets compared to
> ungroomed jets and was used to estimate the difference in L1FastJet jet
> energy corrections for these different jet types. That allowed to make
> sure that the jet energy scale of ungroomed jets was usable for groomed
> jets. (I was not aware we never computed this info in RECO)
> I would personally judge this important enough to have this info in
> RECO/AOD and MiniAOD.
> @rappoccio <https://github.com/rappoccio> @jdolen
> <https://github.com/jdolen> @nhanvtran <https://github.com/nhanvtran> :
> What is your take?

It seems to me that the area for these jets is not really needed.
(considering that it was not available since inception)

Is there a way to make the computation faster?
Something like a grid-based computation.

**Comment by slava77** [comment]
@rappoccio @jdolen @nhanvtran @ahinzmann 
ping

**Comment by slava77** [comment]
@rappoccio @jdolen @nhanvtran @ahinzmann
ping

Do we have to have jet area on substructure jets?
If not, this PR will either go away or will need to be modified to disable jet area computation for substructure jets.

**Comment by rappoccio** [comment]
Hey Guys,

I'm really sorry, this got lost in the sea of my git notifications and I totally missed it. 

So far, the only thing we're using these jets for is to add the mass to miniAOD in the end. If we use the full four vector with jet corrections then this would indeed be needed. At the moment we don't really know if we will need it for the analysis cases we're looking at. 

If we want them in, though, we can / should do the AK8 preclustering and only do the area-based computation for jets with pt > 200 GeV or something, like we do for the top-tagging jets : 

https://github.com/cms-sw/cmssw/blob/CMSSW_7_6_X/RecoJets/Configuration/python/RecoPFJets_cff.py#L179

Cheers,
Sal

**Pull request closed without merging**
