### PR TITLE
Add consumes to ES modules in RecoLocalTracker/SiPixelRecHits

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

As part of the change, consolidated header and source files.

#### PR validation:

The code compiles.
This is only a technical change so should not change results.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
I can not reproduce the problem in my local area.

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
please abort test

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/27614	ff0575c
- technical; code changes are in line with the PR description and the follow up review
- jenkins tests pass and comparisons with the baseline show no differences

PixelCPEGenericESProducer and PixelCPETemplateRecoESProducer may benefit from fillDescriptions at some point soon to get rid of the ```existsAs```

**Comment by kpedro88** [comment]
+1

**Comment by makortel** [comment]
part of #26748

**Pull request merged**
