### PR TITLE
Fine-tune code formatting in GEDGsfElectronFinalizer.cc

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

Addresses @perrotta's comments https://github.com/cms-sw/cmssw/pull/27194#discussion_r298038015 and https://github.com/cms-sw/cmssw/pull/27194#discussion_r298038058.

#### PR validation:

Code compiles.

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by perrotta** [comment]
+1
- Technical, only comment lines moved

**Comment by fabiocos** [comment]
@markortel thanks for taking care

**Comment by fabiocos** [comment]
+1

**Pull request merged**
