### PR TITLE
Backport: Fixes to L2Tau CNN and deepTauID for HLT

### PR DESCRIPTION
**Pull request by azotz**
#### PR description:

This PR fixes critical issues found in L2NNTag modules and deepTauID for HLT. The PR contains the following changes:

* Add default values for configurable parameters where those have not been set to allow correct parsing to ConfDB;
* Allow a pass-through at L2 for all L1 taus with pt above a configurable threshold in L2NNTauTag to avoid observed drop of efficiency for taus with gen_vis_pt > 500 GeV (for gen_vis_pt < 500 GeV the algo efficiency is above 90%). We estimated that the rate with the pass-though threshold of 250 GeV (default) does not significantly change: for the 3 kHz Working Point (WP) it goes from 2999.7 Hz to 3026.4 Hz (0.9%); changes are similar for other WPs.

The changes are simple fixes and do not change behavior of the modules, but on the other hand are critical as without them L2Tau CNN and deepTauID cannot be deployed at HLT.

#### PR validation:

please refer to https://github.com/cms-sw/cmssw/pull/36009

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

This is a backport of https://github.com/cms-sw/cmssw/pull/36009 to 12_1_X.
The reason of this PR is to backport the fixes concerning critical issues found in L2NNTag modules and deepTauID for HLT.

### CODE REVIEW

**Comment by missirol** [comment]
In my understanding, the `L2TauTagFilter` producer is not used in any central workflow, so the physics change in it for high-pT taus should not affect any outputs. I guess this makes it okay to backport these updates.

The other changes are limited to `fillDescriptions` methods.

**Comment by missirol** [comment]
please test

**Comment by slava77** [comment]
backport of #36009

**Comment by slava77** [comment]
+reconstruction

for https://github.com/cms-sw/cmssw/pull/36089	22c4707
- code changes are the same as in #36009 , which was merged in CMSSW_12_2_X_2021-11-10-1100
- jenkins tests pass and comparisons with the baseline show no (relevant) differences
    - the differences appearing in the reco electron plots are only in `mvaOutput().dnn_e_bkgPhoton` variable, which is not initialized; the fix to that is in #36091

**Comment by missirol** [comment]
+hlt

**Comment by qliphy** [comment]
+1

**Pull request merged**
