### PR TITLE
Added IOV synchronization callbacks to ActivityRegistry

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

- Can now follow when EventSetup is attempting to synchronize its Records
- Extended the Tracer service to use new callbacks

#### PR validation:

Code compiles. All framework unit tests pass.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
Please test

**Comment by Dr15Jones** [comment]
Please test

**Comment by makortel** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
