### PR TITLE
Geometry: add Phase2 scenarios D107 = T32+C17+M11+I17+O9+F8 and D108 = T35+C19+M11+I17+O9+F8

### PR DESCRIPTION
**Pull request by fabiocos**
#### PR description:

This PR follows #43760 , adding another geometry scenario D107 = T32+C17+M11+I17+O9+F8 needed to parallelize the validation of the various new components of geometry (D107 = D98 + MTD I17 + Muons M11). Per request of @srimanob in https://github.com/cms-sw/cmssw/pull/43760#issuecomment-1911926335

#### PR validation:

Code compiles using the standard procedures for creation of new geometry scenarios.

### CODE REVIEW

**Comment by fabiocos** [comment]
please test workflow 28434.0

**Comment by fabiocos** [comment]
@srimanob here is the addition required in your plan for the separate MTD geometry validation

**Comment by srimanob** [comment]
Thx very much @fabiocos 
Let's discuss tomorrow before merging.

**Comment by srimanob** [comment]
Hi @fabiocos @bsunanda 

Would it be possible to extend this PR to include D108 = T35+C19+M11+I17+O9+F8 which is expected geometry for Phase-2 production as agreed in the SIM meeting? For D107, I re-think and prefer to keep it, in case we have issue with tracker validation, we can use D107 for the 2nd round of validation. Thx.

**Comment by bsunanda** [comment]
Please let this PR be merged after #43769. I have to make a V18 geometry version with no gaps soon after that. I can include this scenario at that time
________________________________

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by AdrianoDee** [comment]
please test

**Comment by srimanob** [comment]
test parameters:
- workflows = 28434.0,28834.0
- relvals_opt = --what cleanedupgrade,standard,highstats,pileup,generator,extendedgen,production,identity,ged,machine,premix,nano,gpu,2017,2026

**Comment by srimanob** [comment]
@cmsbuild please test

I see the new IB is available, CMSSW_14_0_X_2024-02-05-2300

**Comment by bsunanda** [comment]
+geometry

**Comment by srimanob** [comment]
+Upgrade

**Comment by bsunanda** [comment]
@sunilUIET @srimanob Please approve this

**Comment by AdrianoDee** [comment]
+pdmv

**Comment by fabiocos** [comment]
@srimanob @bsunanda @emiglior for era and tracker conditions I checked the corresponding already existing scenarios with the same component, please cross-check it

**Comment by emiglior** [comment]
> @srimanob @bsunanda @emiglior for era and tracker conditions I checked the corresponding already existing scenarios with the same component, please cross-check it

@fabiocos: conditions checked for tracker +1

**Comment by bsunanda** [comment]
@rappoccio, @antoniovilela Please merge this PR

**Pull request merged**
