### PR TITLE
[106X] nanoAOD: fix electron IP sign 

### PR DESCRIPTION
**Pull request by swertz**
#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Backport of #31495 for re-nano of existing UL miniAOD in 106X (additional changes come from code format)

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
backport of #31495

**Comment by perrotta** [comment]
This backport PR imports all clang format updates for `leptonUpdater.cc` from the master: I have checked that the differences are only due to those style related changes, i.e. there is nothing substantial. In spite of the large number of changes integrated with this PR I am in favor of importing all them here, something which may simplify possible further future backports.

**Comment by perrotta** [comment]
@mrodozov @smuzaffar bot tests seem to be stuck since this morning...

**Comment by swertz** [comment]
> This backport PR imports all clang format updates for leptonUpdater.cc from the master

I actually ran clang format in 106X and naively applied the suggested changes, I wasn't sure if code format checks were run for backports...

**Comment by smuzaffar** [comment]
@perrotta , last night we had issues with CVMFS publisher which was only fixed this morning at 10h. This caused a large backlog of jobs in jenkins.

**Comment by mariadalfonso** [comment]
please test

**Comment by perrotta** [comment]
+1
- Identical to #31495 in the master, modulo a clang-compliant reformatting of leptonUpdater.cc
- It only affects nanoAOD, and therefore there is no counterindication from reco for the backport
- Jenkins tests pass and show no differences besides the nanoAOD ones

**Comment by mariadalfonso** [comment]
+xpog

changes inline as master
only the previously made nano are updated for ip, the reminiAOD for UL have the fix at the source

**Comment by santocch** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
