### PR TITLE
Drop unnecessary 'drop *'

### PR DESCRIPTION
**Pull request by srimanob**
#### PR description:
Backport of https://github.com/cms-sw/cmssw/pull/30576

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by perrotta** [comment]
backport of #30576

**Comment by perrotta** [comment]
+1
- Remove unneeded drop statement from an event content PSet
- Jenkins tests pass, with no differences in outputs
- Backport doesn't hurt, and could even avoid possible issues in case of misuse of that PSet

**Comment by silviodonato** [comment]
merge

**Comment by santocch** [comment]
+1

**Pull request merged**
