### PR TITLE
Commenting unused variables

### PR DESCRIPTION
**Pull request by mrodozov**
Avoids warnings from unused variables

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by fioriNTU** [comment]
@davidlange6 did you ask to do this?
@mrodozov sorry but I can't track your github username to any DQM developer, could you tell me who you are and why are you editing DQM code?

**Comment by davidlange6** [comment]
yes - recent changes have introduced compilation warnings that we have fixed.

**Comment by fioriNTU** [comment]
ok, fine, sorry for the noise ... and thanks

**Pull request merged**
