### PR TITLE
Add a flag to prevent storage of LHEXMLStringProduct, update the dump…

### PR DESCRIPTION
**Pull request by efeyazgan**
backport of #22935

### CODE REVIEW

**Comment by efeyazgan** [comment]
please test

**Comment by qliphy** [comment]
This seems to be a random error?  Also appeared here https://github.com/cms-sw/cmssw/pull/24585  and seems to disappear after a 2nd try...

**Comment by qliphy** [comment]
please test

**Comment by fabiocos** [comment]
@efeyazgan @prebello @pgunnell @qliphy the backport should be ok, as the content of the data structure is not modified, just an empty object if filled instead of the large blob of text

**Comment by fabiocos** [comment]
+1

**Pull request merged**
