### PR TITLE
pA vertex smearing update (80X)

### PR DESCRIPTION
**Pull request by mandrenguyen**
Backport of #16786

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by mandrenguyen** [comment]
@civanch  Can you please sign this 80X version as well, since you signed off on the 90X version.  David indicates that an 81X version is not necessary.

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by perrozzi** [comment]
+1

**Comment by perrozzi** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by mandrenguyen** [comment]
Superseded by #16975

**Pull request closed without merging**
