### PR TITLE
Update of the lostTrack collection for MUO (back-port of #29389)

### PR DESCRIPTION
**Pull request by sscruz**
#### PR description:

Backport from #29389, update of the lostTrack collection for MUO 
https://github.com/cms-sw/cmssw/issues/27889
#### PR validation:

This PR has been validated with 136.8311

This PR is back-port from #29389, needs to be in 10_6_X for the UL re-miniAOD

### CODE REVIEW

**Comment by perrotta** [comment]
@sscruz 
- Please edit the title of the PR with something more meaningful
- The last commit, which includes also the adjustments for the code checks, makes quite complicate to compare with the previous version of the code: is it necessary? Are there plans for further updates that suggest you to make identically the same the code in 10_6 and in the master?
  - If not, I would rather revert that commit
- Backports in a production release must satisfy the "no change" rule: the new ```lostTrack``` features should be made configurable and only switched on by the ```run2_miniAOD_devel``` modifier

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
The output of the automatic tests confirms that there are no changes in the reco outputs with the default setting, as it should.

Going a bit further, let me notice that this PR adds:
- A "pass-through" cut to enlarge the sample of ```lostTracks```
- A muon id to those ```lostTracks```, that was missing before (only pions and electrons were considered)

Instead of having a single ```bool``` that steers both changes at once, I would rather customize differently:
- define the default value for ```passThroughCut``` as ```cms.string("false")```, which has to be reported to ```cms.string("pt>2")``` with the ```run2_miniAOD_devel``` modifier
- add a bool switch to be only applied at [line 250 of PATLostTracks.cc](https://github.com/cms-sw/cmssw/pull/29529/commits/47ecd7a34db8c385e1284a402db75b3e2452c324#diff-4cf30fc26fd4c278f2c4db56c61456d2R250); you can call it ```allowMuonId``` (e.g.), and set it "true" with the ```run2_miniAOD_devel``` modifier

As such, one can control separately the size of the ```lostTracks``` and the muonId in them.
What do you think?

**Comment by sscruz** [comment]
> The output of the automatic tests confirms that there are no changes in the reco outputs with the default setting, as it should.
> 
> Going a bit further, let me notice that this PR adds:
> 
>     * A "pass-through" cut to enlarge the sample of `lostTracks`
> 
>     * A muon id to those `lostTracks`, that was missing before (only pions and electrons were considered)
> 
> 
> Instead of having a single `bool` that steers both changes at once, I would rather customize differently:
> 
>     * define the default value for `passThroughCut` as `cms.string("false")`, which has to be reported to `cms.string("pt>2")` with the `run2_miniAOD_devel` modifier
> 
>     * add a bool switch to be only applied at [line 250 of PATLostTracks.cc](https://github.com/cms-sw/cmssw/pull/29529/commits/47ecd7a34db8c385e1284a402db75b3e2452c324#diff-4cf30fc26fd4c278f2c4db56c61456d2R250); you can call it `allowMuonId` (e.g.), and set it "true" with the `run2_miniAOD_devel` modifier
> 
> 
> As such, one can control separately the size of the `lostTracks` and the muonId in them.
> What do you think?

sure, sounds good, i will push it in a bit

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
backport of #29389

**Comment by perrotta** [comment]
+1
- lostTracks collection is updated by enlarging the sample with looser cuts, and adding a muonID to those lostTracks
- That collection is not modified in the default config, being the update only enabled for the ```run2_miniAOD_devel``` modifier
- Size increase was evaluated for the master version of this PR and deemed acceptable
- Jenkins tests pass and show no differences with the default config, as it should
- Modifications to the lostTracks and isolatedTracks show up as expected when the ```run2_miniAOD_devel``` modifier is enabled

**Comment by santocch** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
