### PR TITLE
[92x] L1T EMTF 2017 Full  

### PR DESCRIPTION
**Pull request by rekovic**
92X - rebased  94x EMTF PRs #19743 #20006 #20286

Once the tests pass with the inital PR:

There are a few other things related to EMTF
which are already merged to integration branch
that I should add on top the currently testing PR,
but for now, I want to make sure this one passes.

Things to add later:

- v96.14
EMTF Remove include of depricated header file in Online producer that
was causing problem to HLT with git cms-checkdeps -A -a .

- v96.21
EMTF: value-initialise EMTFPtLUT variables before use (#595)

- v96.28
EMTF water leak fix and 2016 / 17 conditions configurations via
hackConditions (#604).

### CODE REVIEW

**Comment by rekovic** [comment]
please test

**Comment by rekovic** [comment]
Attn @abrinke1 @jiafulow

**Comment by abrinke1** [comment]
Hi @rekovic 
Thanks for putting this together.  Just so I understand: this PR contains all the changes proposed so far for 94X?  And the additional changes you propose for later are edits already in the l1t-integration code?
Thanks,
Andrew

**Comment by rekovic** [comment]
@abrinke1 
Correct.

**Comment by rekovic** [comment]
need correct externals

**Comment by rekovic** [comment]
@smuzaffar Can we please have a 92x version of externals PR  https://github.com/cms-sw/cmsdist/pull/3407

**Comment by gudrutis** [comment]
@rekovic @smuzaffar 
For 9_2_X external pull request is https://github.com/cms-sw/cmsdist/pull/3487

**Comment by gudrutis** [comment]
please test with cms-sw/cmsdist#3487

**Comment by rekovic** [comment]
+1

The above mentioned commits from l1t-integration branch are already part of 94x version and  part of this 92x rebased version, by construction.

**Comment by dmitrijus** [comment]
+1

**Comment by ggovi** [comment]
+1

**Comment by ghellwig** [comment]
+1

**Comment by rekovic** [comment]
@davidlange6 please merge this one

**Comment by davidlange6** [comment]
CMSSW_9_2_X developement work is completed. Closing remaining PRs

**Pull request closed without merging**
