### PR TITLE
FastSim sampling of nuclear interation using Geant4 FTF model

### PR DESCRIPTION
**Pull request by civanch**
An alternative method to sample nuclear interaction inside tracker is introduced. Geant4 FTF model is used. New option is disabled by default, so current FastSim results should be unchanged.

Extra dependences of FastSim on clhep and Geant4 are added.

### CODE REVIEW

**Comment by lveldere** [comment]
+1

@civanch 

did I get this right:
to switch this on set
NuclearInteraction = cms.bool(True)
G4NuclearInteraction = cms.bool(True)

**Comment by civanch** [comment]
Sorry incorrect file was committed

**Comment by civanch** [comment]
please test

**Comment by lveldere** [comment]
this error is unrelated
should be fixed in next IB

**Comment by degano** [comment]
@cmsbuild please test

**Comment by degano** [comment]
@cmsbuild please test

**Comment by civanch** [comment]
+1

**Pull request merged**
