### PR TITLE
[10.0.X] Streamline usage of 'Alignables' + clang and static analyzer warning fixes

### PR DESCRIPTION
**Pull request by ghellwig**
The typedef `Alignables` is (re-)defined in multiple places.
This PR streamlines their usage together with turning copies of these vectors to const references when a copy is not needed.
It is also one step towards better ownership handling of the composite alignables.

Also fixes a few warnings noticed in previous PRs.

Purely technical modifications with no changes in behaviour expected.

attn.: @lpernie as I am modifying classes in MuonAlignment

### CODE REVIEW

**Comment by ghellwig** [comment]
please test

**Comment by ghellwig** [comment]
please test
(a debug statement slipped through the cracks in the initial version...)

**Comment by lpernie** [comment]
Hello @ghellwig , sorry for the slow reply, I was away last week.
Thanks for this. Let me give a deeper look, but it seems these are just technical modifications.
Anyway, I will need to change accordingly also our muon alignment code that is not in cmssw.

**Comment by lpernie** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
