### PR TITLE
FixAxisLimits

### PR DESCRIPTION
**Pull request by fioriNTU**
Fix the range of axis limits for Strip and Pixel cluster number plots to fit the higher luminosity of the machine

### CODE REVIEW

**Comment by dmitrijus** [comment]
+1

**Comment by fioriNTU** [comment]
Not my fault, the file for the mixing module is missing, could someone 
retrigger the test?

Il 06/07/2016 19.06, cmsbuild ha scritto:

**Comment by davidlange6** [comment]
please test

@fioriNTU - how many bins does this add to DQM in total?

**Comment by fioriNTU** [comment]
@davidlange6 it adds 850 bins in total.

**Pull request merged**
