### PR TITLE
[12.3.X] Add `DiMuonVertexMonitor` module and use it for `ALCARECOTkAlDiMuonAndVertexDQM`

### PR DESCRIPTION
**Pull request by mmusich**
backport of https://github.com/cms-sw/cmssw/pull/38378 and https://github.com/cms-sw/cmssw/pull/38463

#### PR description:

PR  https://github.com/cms-sw/cmssw/pull/33770 added a new ALCARECO producer (`ALCARECOTkAlDiMuonAndVertex`).
This PR adds the DQM monitoring for that stream and adds a new DQM Analyzer (`DiMuonVertexMonitor`)  to monitor the properties of the selected di-muon vertices.
I profit of this PR to make a clean-up of the `TkAlCaRecoMonitor` module as well in commit  2931aac8b3abf332dae02a7b64924e7789bf837f.

#### PR validation:

Run successfully a modified version of 136.887 to include the `TkAlDiMuonAndVertex` ALCARECO producer.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

almost verbatim backport of https://github.com/cms-sw/cmssw/pull/38378 + https://github.com/cms-sw/cmssw/pull/38463 (needed to change GT and input files in the unit tests).
I am opening since there is a window for a new release to be used at Tier-0 - no big hopes of getting it in, though.

### CODE REVIEW

**Comment by mmusich** [comment]
type new-feature

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by emanueleusai** [comment]
+1

**Comment by qliphy** [comment]
please test

**Comment by mmusich** [comment]
...what's the objection in merging this?

**Comment by qliphy** [comment]
@mmusich  As mentioned in last ORP,  we plan to close 12_3_X as 12_4_X is now deployed.  This can be discussed again at today's ORP though.

**Comment by perrotta** [comment]
> ...what's the objection in merging this?

@mmusich what's the purpose of merging in 12_3_X?

**Comment by mmusich** [comment]
> what's the purpose of merging in 12_3_X

E.g. validation of private samples produced in this cycle...

**Comment by mmusich** [comment]
@qliphy 

> As mentioned in last ORP, we plan to close 12_3_X as 12_4_X is now deployed

Not everyone follows all ORP meetings. Also it seems this stayed idle for 20 days before you reached that conclusion

**Comment by perrotta** [comment]
Verbatim backport of https://github.com/cms-sw/cmssw/pull/38378 and https://github.com/cms-sw/cmssw/pull/38463

**Comment by perrotta** [comment]
@mmusich we are empting the queues for the to be closed cycles 12_2_X and 12_3_X.
Do you still need this PR being merged in the 12_3_X IB for your "validation of private samples produced in this cycle"? If so, it can be merged. Otherwise, we will close it.
Please let us know.

**Comment by mmusich** [comment]
>  Otherwise, we will close it.

let's close it. Unfortunately it didn't make it in time to 12.3.x to be useful.

**Pull request closed without merging**
