### PR TITLE
Remove unneeded header includes from DQM/CTPPS plugins

### PR DESCRIPTION
**Pull request by perrotta**
#### PR description:

As a follow up of #40895, a few unnecessary header includes are removed from the newly added plugins, in order to reduce unnecessary dependencies

Added also the removal of explicit ctppsRandomDQMSource_cfi.py, as suggested by @AndreaBellora , because it is already created automatically by the `fillDescriptions` method of the plugin

@AndreaBellora FYI

#### PR validation:

It builds

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by AndreaBellora** [comment]
Thanks @perrotta! To be fair there is still a useless duplication that I noticed: 
DQM/CTPPS/python/ctppsRandomDQMSource_cfi.py is not really needed since DQM/CTPPS/plugins/CTPPSRandomDQMSource.cc contains a fillDescriptions method with the same parameters. I don't want to create delays though, do you think we should fix that too?

**Comment by perrotta** [comment]
please abort

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
Reco tracking changes in the mkfit workflow are obviously unrelated

**Comment by emanueleusai** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
