### PR TITLE
Avoid updating LHERunInfoProduct at end Run in ExternalLHEProducer

### LINKED ISSUE #93: Avoid updating LHERunInfoProduct at end Run in ExternalLHEProducer
This is a change also needed for #88 but can be used without that change.

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

If more than one file is begin used, each files header is read at begin Run time and their info is merged together.

The framework wants to remove the ability for EDProducers to modify at end Run/LuminosityBlock time what the module injected at begin Run/LuminosityBlock time.

#### PR validation:

Code compiles. Unit tests in the package succeed.

resolves makortel/framework#93

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
@makortel FYI

**Comment by Dr15Jones** [comment]
resolves https://github.com/makortel/framework/issues/93

**Comment by agrohsje** [comment]
+generators

**Comment by qliphy** [comment]
+1

**Pull request merged**
