### PR TITLE
Adapt uGMT DQM for new readout menu following the disabling of the zero suppression

### PR DESCRIPTION
**Pull request by dinyar**
#### PR description:

This PR updates the uGMT DQM following changes made to the readout menu after we disabled the zero suppression. It also includes some changes to add plots for the new hadronic showers.

In particular:
- Removed zero suppression folder from uGMT DQM
- Ignored BX range mismatches in uGMT muon copy comparisons. (We now read out only the central BX for the copies but +/-2 for the main outputs.)
- Ignore BX range mismatches for the data-emulator comparisons for the same reason.
- Move the main uGMT DQM plots behind the fat events filter as otherwise the BX distribution plots would be heavily biased towards the central BX. (Because only the central BX is read out in standard events for the inputs.)
- Enable uGMT muon copy comparisons for all events (not just the validation events).
- Remove alerting on incorrect zero suppression and disable BX range checks.
- Add hadronic shower comparisons between the EMTF outputs and uGMT inputs
- Add uGMT muon showers to DQM quality tests

#### PR validation:

Ran the usual `runTheMatrix` and `scram` checks.

### CODE REVIEW

**Comment by dinyar** [comment]
attn @vukasinmilosevic for L1T DQM

**Comment by dinyar** [comment]
Will have another look at this, might have removed the uGMT standard plots entirely by mistake..

**Comment by dinyar** [comment]
So, it looks like those plots are just not generated because no events passed the fat events filter (see [1]). What's not clear to me is whether this is an issue e.g., for RelVals or other offline workflows? Removing the draft state to indicate that expert feedback would be useful.

-d

[1] https://github.com/cms-sw/cmssw/blob/5b56ea4f85b845ed3238c59310f79185ff481ab5/DQM/Integration/python/clients/l1tstage2_dqm_sourceclient-live_cfg.py#L81

**Comment by dinyar** [comment]
I've updated this PR now and created a module that only contains the BX distributions. That module is run after the fat events filter, while the standard uGMT DQM plots continue to get all events. I believe this solves the issue.

**Comment by perrotta** [comment]
please test

**Comment by dinyar** [comment]
From working with the DQM today I'd like to make some more changes to this. Will commit a bit later today.

**Comment by pmandrik** [comment]
please test

**Comment by pmandrik** [comment]
Hi, this one affect l1t_dqm_sourceclient-*_cfg.py clients. We need a backport to  CMSSW_12_3_X to test it at P5

**Comment by dinyar** [comment]
Hi @pmandrik,

Ok, done (#38172). Shall I also create one for 12_4_X as I'd like to have it deployed to P5?

Cheers,
Dinyar

**Comment by pmandrik** [comment]
> Hi @pmandrik,
> 
> Ok, done (#38172). Shall I also create one for 12_4_X as I'd like to have it deployed to P5?
> 
> Cheers, Dinyar

Hi, at the moment CMSSW_12_3_4_patch2 is used at the DQM production machines, please check [DQM playback](https://cmsweb.cern.ch/dqm/online-playback/) and let me know if it is ready to be deployed at P5 for operation, the 12_4_X is probably also useful but not at the moment

**Comment by emanueleusai** [comment]
+1

**Comment by qliphy** [comment]
Discussions are still ongoing in 12_3_X on P5 tests:
https://github.com/cms-sw/cmssw/pull/38172

**Comment by qliphy** [comment]
+1

**Pull request merged**
