### PR TITLE
Changes to PartonShowerBsHepMCFilter and LHEGenericFilter

### PR DESCRIPTION
**Pull request by perrozzi**
PartonShowerBsHepMCFilter searches now a B-hadron among status 2 (i.e. outgoing) particles to accept the event
LHEGenericFilter accepts now several logics for a given numRequired, i.e. LT meaning < NumRequired, GT >, EQ =, NE !=

### CODE REVIEW

**Comment by bendavid** [comment]
Are all of these changes already in 76x?

**Comment by perrozzi** [comment]
no. I can make a PR also for that branch

**Comment by bendavid** [comment]
yes please do

**Comment by perrozzi** [comment]
btw, I am trying to cherrypick but doesn't work, is there another semi-automatic procedure to recover the commits or shall I proceed "by hand"?

**Comment by bendavid** [comment]
Why doesn't cherry-pick work?

**Comment by perrozzi** [comment]
no idea...
I am in CMSSW_7_6_0_pre2
I added 
git cms-addpkg GeneratorInterface/GenFilters
git cms-addpkg GeneratorInterface/Core
and when I do
git cherry-pick 2e6b88d0bbe50406037a1671a2b09fe69df98323..f14bc79cd0e01cf1266afe2e5c6e3fad32b6312a
it returns a long series of error messages unrelated to the files belonging to the commits...

[...]
error: addinfo_cache failed for path 'HLTrigger/JetMET/plugins/HLTRHemisphere.cc'
error: addinfo_cache failed for path 'HLTrigger/JetMET/plugins/HLTCAWZTagFilter.cc'
error: addinfo_cache failed for path 'Geometry/TrackerCommonData/plugins/DDPixFwdDiskAlgo.h'
error: addinfo_cache failed for path 'Geometry/TrackerCommonData/plugins/DDPixBarLayerUpgradeAlgo.h'
error: addinfo_cache failed for path 'FastSimulation/TrackingRecHitProducer/interface/SiStripGaussianSmearingRecHitConverterAlgorithm.h'
error: addinfo_cache failed for path 'FastSimulation/TrackingRecHitProducer/interface/SiPixelGaussianSmearingRecHitConverterAlgorithm.h'
error: addinfo_cache failed for path 'DetectorDescription/RegressionTest/bin/DDErrorReport.cpp'
error: addinfo_cache failed for path 'DataFormats/BTauReco/interface/CATopJetTagInfo.h'
# On branch from-CMSSW_7_6_0_pre2
# You are currently cherry-picking.
#   (all conflicts fixed: run "git commit")
#
nothing to commit, working directory clean
The previous cherry-pick is now empty, possibly due to conflict resolution.
If you wish to commit it anyway, use:

    git commit --allow-empty

Otherwise, please use 'git reset'

**Comment by bendavid** [comment]
Well the first few commits are probably already in 76x

**Comment by perrozzi** [comment]
even if I remove pierluigi's commits, only 3 files, the status is

bash-4.1$ git status
# On branch from-CMSSW_7_6_0_pre2
# You are currently cherry-picking.
#   (fix conflicts and run "git commit")
#
# Changes to be committed:
#
#       new file:   GeneratorInterface/GenFilters/python/LHEGenericFilter_cfi.py
#
# Unmerged paths:
#   (use "git add/rm <file>..." as appropriate to mark resolution)
#
#       deleted by us:      GeneratorInterface/GenFilters/interface/LHEGenericFilter.h
#       deleted by us:      GeneratorInterface/GenFilters/src/LHEGenericFilter.cc
#

i.e. 3 out of 7 files are modified

**Comment by bendavid** [comment]
Well ok if there are real conflicts they have to be resolved.  Otherwise some non-trival rebase.  Or else indeed just do it by hand.

**Comment by perrozzi** [comment]
(I'll do it by hand...)

**Comment by perrozzi** [comment]
https://github.com/cms-sw/cmssw/pull/11188

**Comment by perrozzi** [comment]
https://github.com/cms-sw/cmssw/pull/11190 should not suffer from the problem, closing this PR

**Comment by perrozzi** [comment]
(also the PR on this branch is still relevant)

**Comment by perrozzi** [comment]
Hi, since the PR https://github.com/cms-sw/cmssw/pull/11190 has been merged and this one is a clone for 71X (including the last commit to add edm::LogError, I would kindly ask to approve it to have asap a CMSSW production release incorporating these features. thanks a lot

**Comment by bendavid** [comment]
+1

**Pull request merged**
