### PR TITLE
Phase2-hcx191 Take care of hfnose in view of change in algorithm

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

The algorithms of making HGCal geometry has been modified and it needs more input constants. The same algorithm is used in describing HFNose and needed updating

#### PR validation:

The changes are tested by re-running the workflow 26234.0 which was broken

#### if this PR is a backport please specify the original PR:

If the HGCal code are back ported this change also needs back porting

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
+1

**Comment by fabiocos** [comment]
@bsunanda this code was not previously used in production, am I correct?

**Comment by bsunanda** [comment]
This gives rise to a special scenario D31 with the nose detector in front of HF. This is a possible upgrade which is studied by a group of people from Hcal and HGCal community.

**Comment by bsunanda** [comment]
Currently Maria Rosaria is one of the persons who is seriously pursuing this. Kenichi and his students also looked into this.

**Comment by fabiocos** [comment]
@bsunanda @kpedro88 my question is: was this already used for some official production or not? I understand it wasn't...

**Comment by kpedro88** [comment]
It was not, as far as I know.

**Comment by bsunanda** [comment]
Fabio - you are right. No official production is done so far. The chain works only unto Didi stage. RecHits (equivalent) are made in some private analyses

**Comment by fabiocos** [comment]
+1

**Pull request merged**
