### PR TITLE
Update the `convertToRaw` script [12.4.x]

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Update the `convertToRaw` script:
  - change the default to 100 events per file, to match the value currently used online;
  - Improve the handling of the output and exit status of the subprocesses;
  - write a `run####_cff.py` file with the Source and Services to process the converted files;
  - add the `-r`/`--range` option to restrict the processing to a range of runs and lumisections;
  - add the `-v/--verbose` option to print additional message while preprocessing and converting the input files.

#### PR validation:

The new version runs and selects lumisections correctly.

Here is a sample output from running `convertToRaw` over one .root file:
```
$ convertToRaw -o /gpu_data/store/data/Run2022C/HLTPhysics/FED/v1 -r 34-65 root://eoscms.cern.ch//eos/cms/tier0/store/data/Run2022C/EphemeralHLTPhysics11/RAW/v1/000/357/329/00000/9e43f951-59ef-4dbf-85d1-28b5fa5f664f.root 
preprocessing input file root://eoscms.cern.ch//eos/cms/tier0/store/data/Run2022C/EphemeralHLTPhysics11/RAW/v1/000/357/329/00000/9e43f951-59ef-4dbf-85d1-28b5fa5f664f.root
  run 357329, lumisetion 29 is outside of the given range and will be skipped
  run 357329, lumisetion 30 is outside of the given range and will be skipped
  run 357329, lumisetion 31 is outside of the given range and will be skipped
  run 357329, lumisetion 32 is outside of the given range and will be skipped
  run 357329, lumisetion 33 is outside of the given range and will be skipped
  run 357329, lumisetion 34 with 463 events will be processed
  run 357329, lumisetion 35 with 431 events will be processed

found run 357329, lumi 34, with 463 events
cmsRun \
  /data/user/fwyzard/CMSSW_12_4_6/src/HLTrigger/Tools/python/convertToRaw.py \
  inputFiles=root://eoscms.cern.ch//eos/cms/tier0/store/data/Run2022C/EphemeralHLTPhysics11/RAW/v1/000/357/329/00000/9e43f951-59ef-4dbf-85d1-28b5fa5f664f.root \
  runNumber=357329 \
  lumiNumber=34 \
  eventsPerLumi=11655 \
  eventsPerFile=100 \
  outputPath=/gpu_data/store/data/Run2022C/HLTPhysics/FED/v1/run357329_ls0034

found run 357329, lumi 35, with 431 events
cmsRun \
  /data/user/fwyzard/CMSSW_12_4_6/src/HLTrigger/Tools/python/convertToRaw.py \
  inputFiles=root://eoscms.cern.ch//eos/cms/tier0/store/data/Run2022C/EphemeralHLTPhysics11/RAW/v1/000/357/329/00000/9e43f951-59ef-4dbf-85d1-28b5fa5f664f.root \
  runNumber=357329 \
  lumiNumber=35 \
  eventsPerLumi=11655 \
  eventsPerFile=100 \
  outputPath=/gpu_data/store/data/Run2022C/HLTPhysics/FED/v1/run357329_ls0035

```

And the corresponding `/gpu_data/store/data/Run2022C/HLTPhysics/FED/v1/run357329_cff.py` file:
```python
import FWCore.ParameterSet.Config as cms

from EventFilter.Utilities.FedRawDataInputSource_cfi import source as _source
source = _source.clone(
    eventChunkSize = 200,   # MB
    eventChunkBlock = 200,  # MB
    numBuffers = 4,
    maxBufferedFiles = 4,
    fileListMode = True,
    fileNames = (
        '/gpu_data/store/data/Run2022C/HLTPhysics/FED/v1/run357329/run357329_ls0034_index000000.raw',
        '/gpu_data/store/data/Run2022C/HLTPhysics/FED/v1/run357329/run357329_ls0034_index000001.raw',
        '/gpu_data/store/data/Run2022C/HLTPhysics/FED/v1/run357329/run357329_ls0034_index000002.raw',
        '/gpu_data/store/data/Run2022C/HLTPhysics/FED/v1/run357329/run357329_ls0034_index000003.raw',
        '/gpu_data/store/data/Run2022C/HLTPhysics/FED/v1/run357329/run357329_ls0034_index000004.raw',
        '/gpu_data/store/data/Run2022C/HLTPhysics/FED/v1/run357329/run357329_ls0035_index000000.raw',
        '/gpu_data/store/data/Run2022C/HLTPhysics/FED/v1/run357329/run357329_ls0035_index000001.raw',
        '/gpu_data/store/data/Run2022C/HLTPhysics/FED/v1/run357329/run357329_ls0035_index000002.raw',
        '/gpu_data/store/data/Run2022C/HLTPhysics/FED/v1/run357329/run357329_ls0035_index000003.raw',
        '/gpu_data/store/data/Run2022C/HLTPhysics/FED/v1/run357329/run357329_ls0035_index000004.raw'
    )
)

from EventFilter.Utilities.EvFDaqDirector_cfi import EvFDaqDirector as _EvFDaqDirector
EvFDaqDirector = _EvFDaqDirector.clone(
    buBaseDir = '/gpu_data/store/data/Run2022C/HLTPhysics/FED/v1',
    runNumber = 357329
)

from EventFilter.Utilities.FastMonitoringService_cfi import FastMonitoringService as _FastMonitoringService
FastMonitoringService = _FastMonitoringService.clone()
```

#### If this PR is a backport please specify the original PR and why you need to backport that PR.

Backport of #39047 to 12.4.x to convert data for use by the HLT studies.

### CODE REVIEW

**Comment by fwyzard** [comment]
please test

**Comment by missirol** [comment]
+hlt

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
please test

**Comment by missirol** [comment]
please abort

Tests seem stuck.

**Comment by missirol** [comment]
please test

**Comment by missirol** [comment]
The tests for this PR are somehow having trouble since Saturday.

@smuzaffar , could you please suggest what to do?

**Comment by fwyzard** [comment]
@cmsbuild, please abort

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by smuzaffar** [comment]
> The tests for this PR are somehow having trouble since Saturday.
> 
> @smuzaffar , could you please suggest what to do?

@missirol , so some strange reason but was running `comparison/input` test which never finished. I will check what triggered this test. Anyway, last PR test request is running fine and results should be available in and hour

**Comment by smuzaffar** [comment]
@missirol , the original PR relval job for testing `input` failed ( https://cmssdt.cern.ch/jenkins/job/ib-run-pr-relvals/23310/) and our auto-retry of failed jenkins had restarted it (https://cmssdt.cern.ch/jenkins/job/ib-run-pr-relvals/23312/) with some missing parameters (specially missing `DO_COMPARIOSN=false`). This caused the extra `comparison/input` test. @aandvalenzuela is looking in to improve the auto-retry job so that it can pass all the build parameters.

**Comment by missirol** [comment]
@smuzaffar , sounds good, thanks for having a look.

**Comment by missirol** [comment]
+hlt

**Pull request merged**
