### PR TITLE
Updating Muon tomography codes to display Scintillator hits

### PR DESCRIPTION
**Pull request by indra-ehep**
#### PR description:

This will add features to display the HGCAL Scintillator hits as part of Muon Tomography plots. It will assist to spot the location of Scintillator hits to confirm, if there is any displacement than the nominal expected position.

#### PR validation:

Not required

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Not required.

### CODE REVIEW

**Comment by emanueleusai** [comment]
please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by emanueleusai** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
