### PR TITLE
Run3-alca161 Correct some of the scripts used for IsoTrack Calibration

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Correct some of the scripts for PU correction to be used for isotrack calibration

#### PR validation:

Tested privately using MC samples and results presented in the HCAL DPG

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special;

### CODE REVIEW

**Comment by christopheralanwest** [comment]
please test

**Comment by pohsun** [comment]
+1

**Comment by silviodonato** [comment]
@bsunanda, could you extend the PR description, please?
I see you are adding some commented lines, a new function (`combine`) that is not used, some changes in the file name.  The actual change seems in https://github.com/cms-sw/cmssw/pull/29017/files#diff-c718505a17e3de9a782dd5614a3bdeaaR144-R156 and https://github.com/cms-sw/cmssw/pull/29017/files#diff-0c8d163a2377a93b975dc456b3f9d414R74-R75 . Thanks!

**Comment by silviodonato** [comment]
+1

**Pull request merged**
