### PR TITLE
Update Hcal MC pulse shapes in all Global Tags

### PR DESCRIPTION
**Pull request by mmusich**
# Summary of changes in Global Tags
## RunII simulation
- **RunII Ideal scenario** : [81X_mcRun2_design_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun2_design_v4) as [81X_mcRun2_design_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun2_design_v3) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_mcRun2_design_v4/81X_mcRun2_design_v3): 
  - Updated Hcal pulse shapes to correct shift on the reco timing for HB+ iphi=54 in MC samples
- **RunII CRAFT scenario** : [81X_mcRun2cosmics_startup_peak_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun2cosmics_startup_peak_v4) as [81X_mcRun2cosmics_startup_peak_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun2cosmics_startup_peak_v3) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_mcRun2cosmics_startup_peak_v4/81X_mcRun2cosmics_startup_peak_v3): 
  - Updated Hcal pulse shapes to correct shift on the reco timing for HB+ iphi=54 in MC samples
- **RunII Asymptotic scenario** : [81X_mcRun2_asymptotic_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun2_asymptotic_v4) as [81X_mcRun2_asymptotic_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun2_asymptotic_v3) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_mcRun2_asymptotic_v4/81X_mcRun2_asymptotic_v3): 
  - Updated Hcal pulse shapes to correct shift on the reco timing for HB+ iphi=54 in MC samples
- **RunII Startup scenario** : [81X_mcRun2_startup_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun2_startup_v4) as [81X_mcRun2_startup_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun2_startup_v3) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_mcRun2_startup_v4/81X_mcRun2_startup_v3): 
  - Updated Hcal pulse shapes to correct shift on the reco timing for HB+ iphi=54 in MC samples
## RunII data
- **RunII HLT relval processing** : [81X_dataRun2_HLT_relval_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_dataRun2_HLT_relval_v2) as [81X_dataRun2_HLT_relval_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_dataRun2_HLT_relval_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_dataRun2_HLT_relval_v2/81X_dataRun2_HLT_relval_v1): 
  - updated HcalMCParams (to reflect MC pulse shapes update)
  - technical change of the Tracker Alignment tag (preparation for PCL)
- **RunII HLT relval processing** : [81X_dataRun2_HLTHI_frozen_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_dataRun2_HLTHI_frozen_v1) as [81X_dataRun2_HLTHI_frozen_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_dataRun2_HLTHI_frozen_v0) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_dataRun2_HLTHI_frozen_v1/81X_dataRun2_HLTHI_frozen_v0): 
  - updated HcalMCParams (to reflect MC pulse shapes update)
  - technical change of the Tracker Alignment tag (preparation for PCL) 
- **RunII HLT Heavy-lon processing** : [81X_dataRun2_HLT_frozen_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_dataRun2_HLT_frozen_v1) as [81X_dataRun2_HLT_frozen_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_dataRun2_HLT_frozen_v0) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_dataRun2_HLT_frozen_v1/81X_dataRun2_HLT_frozen_v0): 
  - updated HcalMCParams (to reflect MC pulse shapes update)
  - technical change of the Tracker Alignment tag (preparation for PCL) 
- **RunII Offline relval processing** : [81X_dataRun2_relval_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_dataRun2_relval_v4) as [81X_dataRun2_relval_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_dataRun2_relval_v3) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_dataRun2_relval_v4/81X_dataRun2_relval_v3): 
  - updated HcalMCParams (to reflect MC pulse shapes update)
- **RunII Offline processing** : [81X_dataRun2_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_dataRun2_v3) as [81X_dataRun2_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_dataRun2_v2) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_dataRun2_v3/81X_dataRun2_v2): 
  - updated HcalMCParams (to reflect MC pulse shapes update)
## Upgrade
- **PhaseI realistic scenario** : [81X_upgrade2017_design_v8](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_upgrade2017_design_v8) as [81X_upgrade2017_design_v7](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_upgrade2017_design_v7) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_upgrade2017_design_v8/81X_upgrade2017_design_v7): 
  - Updated Hcal pulse shapes to correct shift on the reco timing for HB+ iphi=54 in MC samples
- **PhaseI design scenario** : [81X_upgrade2017_design_v8](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_upgrade2017_design_v8) as [81X_upgrade2017_design_v7](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_upgrade2017_design_v7) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_upgrade2017_design_v8/81X_upgrade2017_design_v7): 
  - Updated Hcal pulse shapes to correct shift on the reco timing for HB+ iphi=54 in MC samples

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
please test

**Comment by perrotta** [comment]
@mmusich: the only commit included in this PR's is already merged in 81X with #15327
I think that this PR can get closed.

**Comment by mmusich** [comment]
@perrotta: no!
I update the branch and pushed one other commit after my previous one was merged together with your PR. This PR now supersedes the version of `autoCond` in yours.

**Comment by perrotta** [comment]
Ops: it only showed one committ in git, and therefore I thought it was actually the old one.
Thank you for telling. Ciao.

**Comment by mmusich** [comment]
@perrota, sorry for the confusion, I didn't want to waste the branch :)

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
+1

**Comment by davidlange6** [comment]
@mmusich - the hcal results are strangely unchanged by this PR - is that expected for some reason?

**Comment by mmusich** [comment]
@davidlange6 sorry, I don't understand the question.
I do see changes in:
   * Run2 simulation 25ns: [link](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_8_1_X_2016-08-05-1100+15335/15178/validateJR/all_OldVSNew_TTbarPUwf25202p0/)
   * Run2 simulation 50ns: [link](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_8_1_X_2016-08-05-1100+15335/15178/validateJR/all_OldVSNew_TTbarPUwf50202p0/)
   * Upgrade 2017: [link](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_8_1_X_2016-08-05-1100+15335/15178/validateJR/all_OldVSNew_SingleMu13Pt1wf1306p0/)
   * Upgrade 2023: [link](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_8_1_X_2016-08-05-1100+15335/15178/validateJR/all_OldVSNew_TTbar13TeV2023wf10624p0/)

Actually I am surprised to see changes elsewhere than Hcal in the Run2 MC comparisons, when the only actual change is in Hcal: https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_mcRun2_asymptotic_v4/81X_mcRun2_asymptotic_v3

**Comment by davidlange6** [comment]
+1

**Pull request merged**
