### PR TITLE
Turning back on cluster plots for offline DQM for HI

### PR DESCRIPTION
**Pull request by threus**
Turning back on cluster plots for offline DQM for HI

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1

**Comment by slava77** [comment]
merge

memory reduction is evident: SiStripMonitorCluster use in histograms goes down from 934MiB to 11MiB

**Comment by deguio** [comment]
this is expected and due to
+SiStripMonitorCluster.Mod_On = False

should give some more oxigen to T0.

**Pull request merged**
