### PR TITLE
Move logintpack and libminifloat under DataFormats/Math, and add unit tests for logintpack::pack16 etc

### PR DESCRIPTION
**Pull request by makortel**
This PR adds unit tests for `logintpack::pack16()` etc functions, in the case that `base` is something smaller than 32768. I did these mainly to understand and make sure the 16-bit packing/unpacking work as I expected with smaller-than-15-bit `base`.

In addition, after some discussion below, the logintpack and libminifloat are moved under `DataFormats/Math` to be better usable outside PackedCandidates without adding a dependence on `DataFormats/PatCandidates`.

Tested in CMSSW_10_1_0, no changes expected.

### CODE REVIEW

**Comment by makortel** [comment]
I'm planning to use `liblogintpack` for phase2 premixing (from package under `Sim*`, @civanch), so let me wonder out loud already now if in light of that the `liblogintpack` and `libminifloat` are still best placed in this `DataFormats/PatCandidates` package? (I'm not claiming they should be moved, just asking beforehand the opinions of people)

In practice `liblogintpack` is header-only, so `#include`ng it does not create physical dependence, so maybe my pondering is more academical.

**Comment by slava77** [comment]
On 4/4/18 5:34 AM, Matti Kortelainen wrote:
> I'm planning to use |liblogintpack| for phase2 premixing (from package
> under |Sim*|, @civanch <https://github.com/civanch>), so let me wonder
> out loud already now if in light of that the |liblogintpack| and
> |libminifloat| are still best placed in this |DataFormats/PatCandidates|
> package? (I'm not claiming they should be moved, just asking beforehand
> the opinions of people)
> 
> In practice |liblogintpack| is header-only, so |#include|ng it does not
> create physical dependence, so maybe my pondering is more academical.
> 

I think that the generic parts can easily be moved to DataFormats/Math

**Comment by arizzi** [comment]
@makortel IIRC it is now possible to use the special "comment syntax" of Double32_t in our dict generation.
I did not test myself but Danilo said that now you can do
<pre>
<class name="myclass" />
   <field name="_myDataMember" comment="hello" />
...
</pre>

and this can be used  with this comment syntax:
https://root.cern.ch/root/html/tutorials/io/double32.C.html

The advantage would be that you do not need to do packing/unpacking in your class but it would be handled by root (on the other hand it introduces explicit dependency on root as a backend for this kind of data compression)

**Comment by makortel** [comment]
@arizzi Interesting, thanks for the link. Following it, I'd interpret "x is converted to y bit unsigned integer" such that the mapping from floating point to integer is linear. But I believe in my case the logarithmic mapping of `liblogintpack` would work better (values span over several orders of magnitude, relative precision is more meaningful than absolute).

**Comment by arizzi** [comment]
I think they also have some float truncation that is more similar to our reduced mantissa and liblogintpack, but I never really tested those because we couldn't use them when statred with miniaod.

**Comment by gpetruc** [comment]
no objections at moving things to DataFormats/Math

**Comment by makortel** [comment]
@arizzi Thanks for point it out, reading the page carefully there is indeed "x converted to Float_t with truncated precision at 6 bits" and "if ... the double word will be converted to a float and its mantissa truncated to nbits significative bits".

I'll try this option out as well (I'm currently packing the values inside a bitfield, so the outcome depends partly on how well ROOT manages to compress the "remaining" part of the bitfield).

**Comment by slava77** [comment]
> I'll try this option out as well (I'm currently packing the values inside a bitfield, so the outcome depends partly on how well ROOT manages to compress the "remaining" part of the bitfield).

It looks like your comment was related to a discussion not related to the unit test in this PR.

@makortel 
please clarify if you are planning to update this PR.

**Comment by makortel** [comment]
@cmsbuild, please test

Moved libminifloat and logintpack under `DataFormats/Math`.

@slava77 I'm done now.

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/22837	31eeb78
- changes are in line with the PR description; no changes in behavior of standard workflows is expected
- jenkins tests pass and comparisons with the baseline show no differences

**Comment by slava77** [comment]
@dmitrijus 
a DQM signature is missing for this PR. Please check.
Thank you.

**Comment by dmitrijus** [comment]
+1

**Comment by arizzi** [comment]
btw, would it make sense to add those function to the dictionaries so that they are loadable in PyROOT/FWlite ?

**Comment by makortel** [comment]
> btw, would it make sense to add those function to the dictionaries so that they are loadable in PyROOT/FWlite ?

I don't disagree, but could that be left for a subsequent PR (by someone who knows what exactly should be put to `classes_def.xml`)?

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Pull request merged**
