### PR TITLE
PPS Geant4 sensitive detectors

### PR DESCRIPTION
**Pull request by civanch**
#### PR description:
Evaluating #37409 number of problems were identified in Geant4 sensitive detector (SD) classes of PPS. In this PR all 3 PPS SDs are updated:
  1. No more run time checks on physics volumes names, because geometry is fixed and depth in geometry structures is also fixed (all other sub-detectors do not use names in run time).
  2. Corrected signatures of methods: which are public/private/protected according to the base class.
  3. Removed unused methods and variables.
  4. Renamed variables to follow code guidelines.
  5. Make all 3 SD classes uniform.
  6. Check energy deposition at a step and any run time processing is performed only if it is above zero.
  7. Improved debug printouts. 
  8. Removed obsolete classes.

No change is expected in testing.

#### PR validation:
private

#### if this PR is a backport please specify the original PR and why you need to backport that PR: 

no backport is expected

### CODE REVIEW

**Comment by civanch** [comment]
@fabferro , in general this PR is technical and should not change physics but independent checks may be useful.

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by civanch** [comment]
please test for CMSSW_12_4_GEANT4_X

**Comment by civanch** [comment]
The lost of regression for GEANT4 branch comparison likely connected with not correct comparisons. Locally, this PR does not change list of hits.

**Comment by perrotta** [comment]
> @fabferro , in general this PR is technical and should not change physics but independent checks may be useful.

I think this PR can be merged. But please @fabferro or someone else from @cms-sw/ctpps-dpg-l2 have a look and let us know

**Comment by diemort** [comment]
@civanch @perrotta @fabferro I'll perform local tests in the following days and let you.

**Comment by diemort** [comment]
@civanch @perrotta @fabferro FYI, I got small differences after these changes, but want to double-check before a final answer. Hope to finish it by tomorrow.

**Comment by qliphy** [comment]
@diemort  Any news? Thanks!

**Comment by diemort** [comment]
@qliphy I'm getting some unexpected differences in 12_4. Let me further check to be sure. Feedback ASAP.

**Comment by qliphy** [comment]
@diemort thanks! any follow up?

**Comment by diemort** [comment]
@civanch @perrotta  @qliphy I'm sorry for the late feedback, but I had to deal with some issues in our simulation. I've made a comparison between a base simulation and the changes proposed in this PR: validation plots shown [here](https://twiki.cern.ch/twiki/bin/view/CMS/PPSSimulationGit37648).

From my side, no issues are found with the proposed changes. If @fabferro agrees, merging may proceed.

**Comment by fabferro** [comment]
> @civanch @perrotta @qliphy I'm sorry for the late feedback, but I had to deal with some issues in our simulation. I've made a comparison between a base simulation and the changes proposed in this PR: validation plots shown [here](https://twiki.cern.ch/twiki/bin/view/CMS/PPSSimulationGit37648).
> 
> From my side, no issues are found with the proposed changes. If @fabferro agrees, merging may proceed.

Then it's ok for me to go on with merging.

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
Thank you @diemort and @fabferro 
Let refresh the 12 days old tests , then we'll proceed to merge this PR

**Pull request merged**
