### PR TITLE
Introduce Payload Inspector for SiPixel conditions

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

This PR aims to introduce the first few classes for the inspection of SiPixel conditions, namely the `SiPixelLorentzAngle` and the `SiPixelQuality`. More classes for other conditions types will be added at a later time.  

#### PR validation:
The code has been privately tested using the scripts provided in the  `CondCore/SiPixelPlugins/test` directory.
In the particular case of the `SiPixelQuality` Bad ROC maps a dedicated validation has been done, by cross-checking the output of the payload inspector, with the content of the `MonitorElement`s used for monitoring the PCL output in the Phase-1 pixel DQM ( [example](https://tinyurl.com/yxd852hc) )
Example of output image to be displayed in [Conditions Browser](https://cms-conddb.cern.ch/cmsDbBrowser/payload_inspector/Prod) from one of the classes introduced here: 

CheckROCsBPix

#### if this PR is a backport please specify the original PR:

This PR is not a backport.
cc:
@tvami @tsusa

### CODE REVIEW

**Comment by mmusich** [comment]
waiting for @ggovi to come back, can at least tests be started here?

**Comment by fabiocos** [comment]
code-checks

**Comment by fabiocos** [comment]
@mmusich this PR is not supposed to affect production workflows, but it provides standalone tools to inspect payloads, am I correct?

**Comment by mmusich** [comment]
@fabiocos 
>  PR is not supposed to affect production workflows, but it provides standalone tools to inspect payloads, am I correct?

that's right. It needs to be in release in order for the ConDB Browser to be able to access to the plugin libraries.

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
+1

**Pull request merged**
