### PR TITLE
Update anti-e tau discriminant (102X)

### PR DESCRIPTION
**Pull request by mbluj**
This PR is to update an MVA anti-e tau discriminant as preparation to introduction of discriminants with a new training with current data, it is backport of #24800 to 102X.

### CODE REVIEW

**Comment by perrotta** [comment]
backport of #24800

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
@mbluj could you please comment with more detail the issue discussed in https://github.com/cms-sw/cmssw/pull/24800#pullrequestreview-162442159 for the PR merged in the master?
How can we get assured that this PR (and the one submitted for 94X) will satisfy the no-change policy for the closed releases used for production? Could you please provide more details, links, etc to what you wrote in https://github.com/cms-sw/cmssw/pull/24800#discussion_r223350747?

**Comment by mbluj** [comment]
> @mbluj could you please comment with more detail the issue discussed in [#24800 (review)](https://github.com/cms-sw/cmssw/pull/24800#pullrequestreview-162442159) for the PR merged in the master?
> How can we get assured that this PR (and the one submitted for 94X) will satisfy the no-change policy for the closed releases used for production? Could you please provide more details, links, etc to what you wrote in [#24800 (comment)](https://github.com/cms-sw/cmssw/pull/24800#discussion_r223350747)?

Could you please clarify if you are specifically concerned by the updated name of a parameter in the `PATTauDiscriminationAgainstElectronMVA6_cfi.py` file (the bug fix) or some other issues? It is not clear for me.

**Comment by perrotta** [comment]
I am "concerned" by the possible usage of a modified PATTauDiscriminationAgainstElectronMVA6 in miniAOD productions that could in principle modify the physiscs output with respect to what already produced with the same release cycle. You wrote already that such a config is not used in miniAOD production, and therefore a few links that demonstrate that it does not enter the reco/miniAOD sequences is perfectly fine for me.

**Comment by mbluj** [comment]
> > @mbluj could you please comment with more detail the issue discussed in [#24800 (review)](https://github.com/cms-sw/cmssw/pull/24800#pullrequestreview-162442159) for the PR merged in the master?
> > How can we get assured that this PR (and the one submitted for 94X) will satisfy the no-change policy for the closed releases used for production? Could you please provide more details, links, etc to what you wrote in [#24800 (comment)](https://github.com/cms-sw/cmssw/pull/24800#discussion_r223350747)?
> 
> Could you please clarify if you are specifically concerned by the updated name of a parameter in the `PATTauDiscriminationAgainstElectronMVA6_cfi.py` file (the bug fix) or some other issues? It is not clear for me.

Waiting on your answer I summarize changes introduced by this PR:
1. Code cleaning
   * most impornat

**Comment by mbluj** [comment]
I'm sorry, I closed (and then opened) the PR by chance. I'm I a way to answer the question.

**Comment by mbluj** [comment]
> I am "concerned" by the possible usage of a modified PATTauDiscriminationAgainstElectronMVA6 in miniAOD productions that could in principle modify the physiscs output with respect to what already produced with the same release cycle. You wrote already that such a config is not used in miniAOD production, and therefore a few links that demonstrate that it does not enter the reco/miniAOD sequences is perfectly fine for me.

`PATTauDiscriminationAgainstElectronMVA6` is not used by any official workflow, but its PFRecoTau version (`PFRecoTauDiscriminationAgainstElectronMVA6.cc`) sharing the same algorithm is. Regardless, the changes by this PR do not change results within precision obtained with ~164k of Z->ll+jets events (mixture of genuine taus and e/mu/j->tau fakes) which is considered to be sufficient.
Please find comparison results in attached slides: [compareTauVariables_antieMVA6v1.pdf](https://github.com/cms-sw/cmssw/files/2610918/compareTauVariables_antieMVA6v1.pdf)

**Comment by perrotta** [comment]
Thank you @mbluj 

The only change in this PR that can potentially affect the physics output is the bug fix you listed as (1) in https://github.com/cms-sw/cmssw/pull/25317#issuecomment-441210594 ("Change of the name of a parameter in PATTauDiscriminationAgainstElectronMVA6_cfi.py").  All other updates are not expected to modify any output, instead, as you also verified with your comparisons.

Now, the answer to my question is your "the module is expected to be run on top of MiniAOD in user workflows and/or as part of ReMiniAOD/NanoAOD production. However, due to lack of a new training of the anti-e MVA which is substantially better than one currently run in RECO workflows the cfi has not been used in official workflows", which confirms that none of the official productions made so far had ever used the "bugged" module config, and cannot therefore get its output modified by this bug fix. As far as I understand, this can be considered enough to guarantee that the "no change policy" is satisfied for this backport.

**Comment by mbluj** [comment]
> 
> 
> Thank you @mbluj
> 
> The only change in this PR that can potentially affect the physics output is the bug fix you listed as (1) in [#25317 (comment)](https://github.com/cms-sw/cmssw/pull/25317#issuecomment-441210594) ("Change of the name of a parameter in PATTauDiscriminationAgainstElectronMVA6_cfi.py"). All other updates are not expected to modify any output, instead, as you also verified with your comparisons.
> 
> Now, the answer to my question is your "the module is expected to be run on top of MiniAOD in user workflows and/or as part of ReMiniAOD/NanoAOD production. However, due to lack of a new training of the anti-e MVA which is substantially better than one currently run in RECO workflows the cfi has not been used in official workflows", which confirms that none of the official productions made so far had ever used the "bugged" module config, and cannot therefore get its output modified by this bug fix. As far as I understand, this can be considered enough to guarantee that the "no change policy" is satisfied for this backport.

Yes, I confirm this. Regerdless, it is not possible to run the module with the non-fixed parameter name as it requires the name after the fix.

**Comment by perrotta** [comment]
+1
- This backport includes some code cleaning and a fix to a configuration file never used in the current productions, and therefore it does not violate the "no change" policy for the backports
- Jenkins tests pass

**Comment by fabiocos** [comment]
+1

as discussed in the review, the backward compatibility of production workflows looks ensured by this code change, so it makes sense to merge it in view of new nanoAOD campaigns

**Pull request merged**
