### PR TITLE
Fix Nano sequence for Premix-ProdLike .9921 relvals

### LINKED ISSUE #35596: Failures in 23434.9921 and 34834.9921 workflows
Workflows 23434.9921 and 34834.9921 fail in step6 in CMSSW_12_1_X_2021-10-08-1100 with
```
----- Begin Fatal Exception 08-Oct-2021 19:31:20 CEST-----------------------
An exception of category 'ProductNotFound' occurred while
   [0] Processing  Event run: 1 lumi: 7 event: 603 stream: 0
   [1] Running path 'NANOEDMAODSIMoutput_step'
   [2] Prefetching for module PoolOutputModule/'NANOEDMAODSIMoutput'
   [3] Prefetching for module GlobalVariablesTableProducer/'ttbarCategoryTable'
   [4] Prefetching for module GenTtbarCategorizer/'categorizeGenTtbar'
   [5] Calling method for module GenHFHadronMatcher/'matchGenCHadron'
Exception Message:
Principal::getByToken: Found zero products matching all criteria
Looking for type: reco::JetFlavourInfoMatchingCollection
Looking for module label: slimmedGenJetsFlavourInfos
Looking for productInstanceName: 

   Additional Info:
      [a] If you wish to continue processing events after a ProductNotFound exception,
add "SkipEvent = cms.untracked.vstring('ProductNotFound')" to the "options" PSet in the configuration.

----- End Fatal Exception -------------------------------------------------
```
https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc900/CMSSW_12_1_X_2021-10-08-1100/pyRelValMatrixLogs/run/23434.9921_TTbar_14TeV+2026D49PU_PMXS1S2ProdLike+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14INPUT+PREMIX_PremixHLBeamSpot14PU+DigiTriggerPU+RecoGlobalPU+MiniAODPU+NanoPU/step6_TTbar_14TeV+2026D49PU_PMXS1S2ProdLike+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14INPUT+PREMIX_PremixHLBeamSpot14PU+DigiTriggerPU+RecoGlobalPU+MiniAODPU+NanoPU.log#/
https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc900/CMSSW_12_1_X_2021-10-08-1100/pyRelValMatrixLogs/run/34834.9921_TTbar_14TeV+2026D76PU_PMXS1S2ProdLike+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14INPUT+PREMIX_PremixHLBeamSpot14PU+DigiTriggerPU+RecoGlobalPU+MiniAODPU+NanoPU/step6_TTbar_14TeV+2026D76PU_PMXS1S2ProdLike+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14INPUT+PREMIX_PremixHLBeamSpot14PU+DigiTriggerPU+RecoGlobalPU+MiniAODPU+NanoPU.log#/

### PR DESCRIPTION
**Pull request by srimanob**
#### PR description:
Fix https://github.com/cms-sw/cmssw/issues/35596

#### PR validation:
The following runTheMatrix.py gives the proper config
`runTheMatrix.py --what upgrade -l 34834.9921 -t 8 --wm init`

#### if this PR is a backport please specify the original PR and why you need to backport that PR:
No need of backport.

### CODE REVIEW

**Comment by srimanob** [comment]
type bug-fix

**Comment by srimanob** [comment]
@cmsbuild please test

**Comment by perrotta** [comment]
Thank you @srimanob !

**Comment by qliphy** [comment]
@cms-sw/pdmv-l2  Any comment?

**Pull request merged**
