### PR TITLE
L2 tau identification with a CNN

### PR DESCRIPTION
**Pull request by azotz**
#### PR description:

In this PR the implementation of a machine learning based approach for the L2 taus is introduced. The chosen ML algorithm is a CNN trained with different hadronic taus production mechanisms (and reweighed in order to avoid overtraining for specific production mechanisms) versus fake taus coming from QCD. 

You can find: 
- the L2TauNNTagProducer which produces the CNN outputs for given L1Tau collections (>=1 collection). For each collection a vector of CNN output is created;
- the L2TauNNTagFilter which takes in input a L1 collection (just 1 in this case), the vector of CNN outputs and the CNN threshold. For the threshold, three different Working Points have been defines in order reach three different desired rate values (3kHz, 4kHz and 5kHz) - evaluated on  EphemeralHLTPhysicsX. For more information see the presentation at the TSG meeting [1]
- The L2TauML production file and a custom function (testL2TauTag) that includes the L2TauTagProducer+Filter 
- instruction on how to run the test in a README.md file
- A unit test based on the test mentioned above

The trained CNN and the normalization file (needed to normalize the matrix which will be given in input to the CNN) is currently in the private fork [2] of the RecoTauTag-TrainingFiles repository as you can see from the instructions in the md file. The training files are planned to be provided via `cms-sw/cms-data`, see [3].

[1] https://indico.cern.ch/event/1040952/contributions/4401915/attachments/2260841/3837378/L2TauIDCNN.pdf
[2] https://github.com/valeriadamante/RecoTauTag-TrainingFiles/tree/L2Taus
[3] https://github.com/cms-data/RecoTauTag-TrainingFiles/pull/7

#### PR validation:
The PR has been validated on top of 12_1_0_pre4. The provided test has been validated and runs smoothly.

The following tests were run and passed as expected, since this PR does not include any change to the official workflows:
```
scram b distclean 
git cms-checkdeps -a -A
scram b -j 8
scram b runtests
runTheMatrix.py -l limited -i all --ibeos
```

#### if this PR is a backport please specify the original PR and why you need to backport that PR:
This PR is not a backport.

### CODE REVIEW

**Comment by mbluj** [comment]
@missirol  We fixed a small bug, cleaned customisation function, updated recipe in README and **added a unit test**. In addition we rebased to newer IB as one previously used has problems with patatrack customisation.

Note: to test this PR (in particularly to run related unit test) one needs to checkout CNN training and normalisation files PR'ed here: https://github.com/cms-data/RecoTauTag-TrainingFiles/pull/7

**Review by missirol — CHANGES_REQUESTED** [review]
Here's the review of these updates (sorry for sending this a bit late).

Thanks for adding the unit test. I tested the recipe manually, and it works. To test it via GitHub, the path to the files needs to be under `RecoTauTag/TrainingFiles/data` (not `RecoTauTag/TrainingFiles`; see comments in the review).

I have one general question (as a layman of ML backends, and how they are used in CMSSW): iiuc, the model and inference here is done with TF; I have seen examples where ONNXRuntime provides better performance compared to TF (see a recent example in https://github.com/cms-sw/cmssw/pull/35698). Would it be useful to move to ONNXRuntime in this particular case, and are there plans to do so (could be done in a separate PR, of course)?

**Review by missirol — CHANGES_REQUESTED** [review]
Thanks for addressing the first comments.

I added a few more minor comments after a 2nd look (I didn't test them, so forgive typos/oversights).

**Comment by azotz** [comment]
@missirol I implemented the proposed changes.

**Comment by mbluj** [comment]
> please test

It should be tested with cms-data/RecoTauTag-TrainingFiles#7, otherwise unit test added for this development will fail.

**Comment by perrotta** [comment]
test parameters:
- pull_request = cms-data/RecoTauTag-TrainingFiles#7

**Comment by missirol** [comment]
+hlt

note: https://github.com/cms-data/RecoTauTag-TrainingFiles/pull/7 should be merged before this PR

**Pull request merged**
