### PR TITLE
Unify geometry scripts

### PR DESCRIPTION
**Pull request by kpedro88**
#### PR description:

* unify operations of 2021 and 2026 geometry scripts, using configurable GeometryGenerator object
* replace optparse w/ argparse and other minor improvements
* improve Era recommendations
* regenerate Phase 2 dd4hep xml files to match script output (and add a few missing ones)
* simplify unit test setup and improve tests to check for missing files

#### PR validation:

Ran unit tests and checked script output.

Because there are several open PRs adding new Phase2 scenarios, I'm happy to rebase this PR once those are merged, to keep everything consistent.

attn: @ianna @cvuosalo @fabiocos

### CODE REVIEW

**Comment by kpedro88** [comment]
please test

**Comment by ianna** [comment]
Thanks, @kpedro88 !

**Comment by cvuosalo** [comment]
+1

**Comment by fabiocos** [comment]
@kpedro88 nice piece of work. As far as MTD is concerned please go ahead, @icosivi has for the time being withdrawn its addition of scenarios, it will come back later on.

**Comment by kpedro88** [comment]
now rebased to master

**Comment by kpedro88** [comment]
please test

**Comment by cvuosalo** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade

**Comment by silviodonato** [comment]
+1

**Pull request merged**
