### PR TITLE
106X backport: jetNDauChargedMVASel for nanoAOD electrons & muons for topMVA inputs

### PR DESCRIPTION
**Pull request by schoef**
This is just the backport of [#31944 ] to 106X

### CODE REVIEW

**Comment by mariadalfonso** [comment]
please test

**Comment by mariadalfonso** [comment]
+xpog
changes inline with master

**Comment by santocch** [comment]
+1

**Comment by silviodonato** [comment]
backport of #31944

**Comment by silviodonato** [comment]
+1

**Pull request merged**
