### PR TITLE
Fixed fast sim sampling of ECAL hits

### PR DESCRIPTION
**Pull request by civanch**
#### PR description:
In this PR a contradiction between "FineCalo" mechanism of MCTruth and GFlash hit sampling in ECAL is resolved. In the case of GFlash sampling of hits, there is no Geant4 touchable defined, which provoke a crash. 

Another fix is introduce in low-energy GFlash model.

These modifications should not affect baseline simulation.

#### PR validation:
private

### CODE REVIEW

**Comment by civanch** [comment]
bug

**Comment by civanch** [comment]
type bug-fix

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
@bsunanda , this PR is needed, because it is not possible simultaneously use GFlash approach and check touchable.

**Comment by civanch** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
