### PR TITLE
Files for new beam spots, final numbers for XeXe

### PR DESCRIPTION
**Pull request by gsfs**

### CODE REVIEW

**Comment by lpernie** [comment]
please test

**Comment by lpernie** [comment]
Hi @gsfs could you add a description? Thanks.

**Comment by lpernie** [comment]
assign alca

**Comment by lpernie** [comment]
@arunhep

**Review by lpernie — COMMENTED** [review]
. Why do you change VtxSmearedRealisticHICollisionZ2015_cfi withVtxSmearedRealisticHICollisionFixZ2015_cfi?
. For VtxSmearedRealistic5TeVppCollision2017_cfi what BS are you using? The one provided from Ian id only for XeXe
. Is Emittance = cms.double(4.33e-08) correct? It seems not not the value in the slides from ian

**Comment by gsfs** [comment]
The answers to your questions:
> Why do you change VtxSmearedRealisticHICollisionZ2015_cfi withVtxSmearedRealisticHICollisionFixZ2015_cfi?
  An error was found in the previous PbPb beam spot. See comment lines added to the code for more information:
+# updated numbers for 2015 PbPb data with Z centroid from fixed beamspot fits
 +# See discussion here https://hypernews.cern.ch/HyperNews/CMS/get/hi-general/3968.html
 +# See plot of difference here: https://www.dropbox.com/s/tsnkgvvpkdqjtyq/vzDataMCOverlay_c_20170420.pdf?dl=0

> For VtxSmearedRealistic5TeVppCollision2017_cfi what BS are you using? The one provided from Ian is only for XeXe
   This is a placeholder only. I wanted to make all of the code changes at the same time and then only update the values of the parameters when they are final.

>  Is Emittance = cms.double(4.33e-08) correct? It seems not the value in the slides from ian
   I believe it is correct. Will work with Ian and HIN folks to confirm. I found this value using the sigmaX and sigmaY values on the slides from Ian. Specifically, I averaged them and then used the formula (sigma)^2=emittance X beta* with beta*=30. This formula can be found many places, including here:
   https://lpc.web.cern.ch/lumi2.html

**Comment by lpernie** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
