### PR TITLE
[14_1_X SIM] Improved destruction of Geant4

### PR DESCRIPTION
**Pull request by civanch**
#### PR description:
In this PR the order of destruction actions end of run is performed. It should fix the issue #44009 - G4PhysicalVolumeStore is cleaned only if it is created. As a result the trace from some CMSSW crashes will be more correct. This PR should not affect any WF, the only expected result should be in trace, when a crash happens .

#### PR validation:
private

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by iarspider** [comment]
please test for CMSSW_14_1_ROOT6_X

**Comment by civanch** [comment]
+1

**Comment by rappoccio** [comment]
+1

**Pull request merged**
