### PR TITLE
Misc cleanup for GCC 6 (missing header, integer overflow, wrong address usage, ..)

### PR DESCRIPTION
**Pull request by davidlt**
The following contains various small cleanup to get packages compiling with GCC 6.0.0. Note that majority to them were reported by Clang for a long time. I guess, the most interesting part is `DataFormats/Math/test/testAtan2.cpp` because it's obviously gonna force integer overflow, but that is undefined behaviour in C++. This patch currently suggests to remove the offending lines.

Commit messages might contain more information.

### CODE REVIEW

**Comment by davidlt** [comment]
Tests are running.

**Comment by davidlt** [comment]
Unrelated.

**Comment by slava77** [comment]
better wait for a working IB and test there again.

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
The static analyzer warns that `EcalDumpRaw.h` is not thread-safe. A fix in this PR or a later one would be good.
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-13634/11786/llvm-analysis/report-5f3b1b.html#EndPath

**Comment by cvuosalo** [comment]
+1

For #13634 580f0fd10267400392abe2fc8038b7cad5cd83fe

Clean-up of nonsense/no-op code that was causing gcc 6 errors. There should be no change in monitored quantities.

The code changes are satisfactory, and Jenkins tests against baseline CMSSW_8_1_X_2016-03-08-1100 show no significant differences, as expected.

**Pull request merged**
