### PR TITLE
Online HCAL DQM adding a 3rd application

### PR DESCRIPTION
**Pull request by vkhristenko**
a follow up on this PR: https://github.com/cms-sw/cmssw/pull/13561

HCAL DQM would like to add a 3rd application to the 2 existing ones. It doesn't affect the offline processing, in that sense it's identical to the PR above. However it adds DQM/Integration.... hcal2_source... configuration-application to be used in Online DQM together with the standard 2.

VK

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by vanbesien** [comment]
please test

**Comment by vanbesien** [comment]
please test

**Comment by deguio** [comment]
please test

**Comment by vkhristenko** [comment]
just added a single if statement...

VK

**Comment by vanbesien** [comment]
please test

**Comment by vkhristenko** [comment]
I'm suspending this PR for the moment!
I have found an issue in my logic for Offline processing and have been recoding it since Friday. I need a few more days - prolly just 1 to finish tests.. I know I'm running late - doing my best!

VK

**Comment by vkhristenko** [comment]
I'm reopening this PR as HCAL DQM CMSSW part is ready.

After the Readiness Reaview a few problems were observed + there were requests which I wante to finish off. Changes:

1) HcalTasks also contains "src" to generate a lib from that to be used by plugins. 
2) Summary generation - or Status generation was completely rewritten.

DQM OFfline Sequences were updated. everything is tested with whiterabbit... and works good.
HCAL DQM is ready now! I know I've said that before, but I think we are ready now.

VK

**Comment by deguio** [comment]
please test

**Comment by vkhristenko** [comment]
@deguio , not sure what is wrong with 134.911. I tried it locally on lxplus and it runs fine.
Just to point out that it didn't work for me with gcc530, but with gcc493 it worked fine.
530 has import issues in configs....
VK

**Comment by vkhristenko** [comment]
may be we can try to retest??? I can't reproduce the same...
runTheMatrix.py -l 134.911..... but for gcc493...

Also, 81X worked just fine.....

**Comment by deguio** [comment]
please test

**Comment by vkhristenko** [comment]
Doesn't make sense...
Can someone explain to me why in 1 case it fails but in the other it doesn't???
Moreover, i've seen a similar issue multiple times in online workflow as well for instance...

It fails/signals upon entering a function and then falls on one of these guys...
        installCustomHandler(SIGBUS,sig_dostack_then_abort);
        installCustomHandler(SIGSEGV,sig_dostack_then_abort);
        installCustomHandler(SIGILL,sig_dostack_then_abort);

VK

**Comment by dmitrijus** [comment]
+1
already approved in 81x and has been running on online/production for a long time :)

**Comment by dmitrijus** [comment]
hold
The segfault in https://github.com/cms-sw/cmssw/pull/13805#issuecomment-218769015 needs to be understood and fixed before

**Comment by dmitrijus** [comment]
unhold
but please merge 81x version first: https://github.com/cms-sw/cmssw/pull/14491

**Comment by dmitrijus** [comment]
+1

**Pull request merged**
