### PR TITLE
 Adding the Ecal Endcaps to the ML based online ECAL DQM [13_0_X]

### PR DESCRIPTION
**Pull request by abhih1**
#### PR description:

This PR introduces the Ecal Endcaps into the autoencoder-based online ECAL DQM feature, which was implemented for EB in https://github.com/cms-sw/cmssw/pull/35990.
Separate Autoencoder (AE) models with ResNet architecture are trained for EE+ and EE-, apart from the model for EB, on certified good data (digi occupancy) from 2018 runs.

On giving an input occupancy map to the AE, the encoder part of the AE encodes and learns the features and the decoder reconstructs the data from the encoded latent space to match the input as closely as possible. The reconstruction loss is then calculated, which is a mean squared error (MSE) between the input and output images at a tower level. Thus given an anomalous tower, the AE which has learnt the features of the good data will have a hard time reconstructing it and give a higher loss on the anomaly than on the good towers. A quality threshold is then applied on this loss map which marks it as Good or Bad, which is then stored as an ML quality summary plot.
New correction factors are derived from 2022 collisions data to use in the pre-processing and inference, which follows the same steps as used for EB.

This PR thus introduces ML Quality summary plots for EE- and EE+, along with Loss Map and reconstructed occupancy maps from the AE.
It also introduces a trend plot to monitor the no. of bad towers flagged by the AE per lumisection in a run, as well as the map of these bad towers in an occupancy-like plot. This would be very helpful in monitoring per lumisection behaviour of bad towers/channels.

Please note that this PR should be tested along with the files added to https://github.com/cms-data/DQM-EcalMonitorClient/pull/3

#### PR validation:

The code was validated by running the online Ecal DQM configuration and the resultant plots were examined by uploading the output file to a DQM test gui.
The new plots are confirmed and look reasonable.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

This is a backport to 13_0_X which is currently used in production
The master PR is: https://github.com/cms-sw/cmssw/pull/41175

### CODE REVIEW

**Comment by perrotta** [comment]
backport of https://github.com/cms-sw/cmssw/pull/41175

**Comment by emanueleusai** [comment]
type ecal

**Comment by emanueleusai** [comment]
please test with https://github.com/cms-data/DQM-EcalMonitorClient/pull/3

**Comment by emanueleusai** [comment]
tests at p5 completed

**Comment by emanueleusai** [comment]
+1

**Comment by rappoccio** [comment]
hold

* The master branch PR has not been integrated nor signed, but this one was preemptively signed. We will wait for the master to converge before merging.

**Comment by abhih1** [comment]
@rappoccio The master PR has been merged.

**Comment by perrotta** [comment]
> @rappoccio The master PR has been merged.

Yes. Now you must propagate the latest changes in MLClient.cc in this backport, or explain why they cannot/shouldn't be backported. Then we can unhold this

**Comment by abhih1** [comment]
> > @rappoccio The master PR has been merged.
> 
> Yes. Now you must propagate the latest changes in MLClient.cc in this backport, or explain why they cannot/shouldn't be backported. Then we can unhold this

The latest changes in MLClient.cc was to solve the conflict with the PR for new ONNXRuntime api by https://github.com/cms-sw/cmssw/pull/41118 related to https://github.com/cms-sw/cmsdist/pull/8397 

As far as I can see, this API change is not backported to 13_0_X.
The onnxruntime for 13_0_X is 1.10.0 : https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_13_0_X/cs9/onnxruntime.spec#L1

**Comment by perrotta** [comment]
unhold

**Comment by rappoccio** [comment]
+1

**Pull request merged**
