### PR TITLE
Offline DQM for 2016 pPb Muon HLT

### PR DESCRIPTION
**Pull request by stahlleiton**
This PR is meant for pPb 2016 run and it includes the modifications needed in Offline DQM for the muon HLT triggers.  The first change corresponds to update the list of trigger paths in HLTMuonOfflineAnalyzer so that it includes the new muon pPb triggers. We might also consider to change the pT cut of the Jpsi efficiency plots (see https://github.com/cms-sw/cmssw/blob/CMSSW_8_1_X/DQMOffline/Trigger/src/HLTMuonMatchAndPlot.cc#L305 ) but this is still under discussion.

### CODE REVIEW

**Comment by stahlleiton** [comment]
It would be great if someone could please start the test of this PR

**Comment by stahlleiton** [comment]
Could someone please test this PR?

**Review by dmitrijus — APPROVED** [review]

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
