### PR TITLE
backport CSCCLCTPreTriggerDigi for ULHLT

### PR DESCRIPTION
**Pull request by srimanob**
#### PR description:

Back port of needed classes to pass eventcontent in 10_5/6 to 8_0 for UL validation. Discussion and test report is in https://github.com/cms-sw/cmssw/issues/26206

#### PR validation:

The success test with this PR is reported in 
https://github.com/cms-sw/cmssw/issues/26206#issuecomment-476378554

#### if this PR is a backport please specify the original PR:
https://github.com/cms-sw/cmssw/pull/26106

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by srimanob** [comment]
@civanch @fabiocos 
Could you please trigger the test? Thx.

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
@civanch this is just the backport of a data format without any producer, so it should be technical and clean to merge preserving back-ward compatibility

**Comment by civanch** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
