### PR TITLE
Revert "Use likelihood fit instead of chi-square fit in PVValidation"

### PR DESCRIPTION
**Pull request by smuzaffar**
Reverts cms-sw/cmssw#43588

See https://github.com/cms-sw/cmssw/issues/43722 for details

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by makortel** [comment]
urgent

**Comment by perrotta** [comment]
+alca
- It reverts https://github.com/cms-sw/cmssw/pull/43588
 following the discussion in https://github.com/cms-sw/cmssw/issues/43722
- This is possible after the merging of https://github.com/cms-sw/cmssw/pull/43726 which converts a root error (new in Minuit2, while Hesse Matrix not being positive definite was not printed as a root error in previous Minuit, even if there) from a cms-exception into a LogError

**Comment by smuzaffar** [comment]
@cms-sw/orp-l2 , can you please get this in next IB

**Comment by rappoccio** [comment]
+1

**Pull request merged**
