### PR TITLE
bug fix for stage1 dqm

### PR DESCRIPTION
**Pull request by jingyucms**
Trying to fix 3 bugs for stage1 dqm:
1) change Stage1 Client histogram folder
2) make sure GMT fed will not be affected when swap GT fiber between stage1 and legacy
3) restrict layer2 to unpack only 1Bx for data emulator comparison

same as #10354

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1

**Comment by deguio** [comment]
-1
this seems to be buggy
F.

**Comment by jingyucms** [comment]
please test

**Comment by mulhearn** [comment]
please test

**Comment by mulhearn** [comment]
+1

**Comment by mulhearn** [comment]
@jingyucms:  can you prepare a 74X version of this PR?

**Comment by jingyucms** [comment]
@mulhearn the 74x version of this PR is #10463 and #10442(from you)
I guess as we are working on 748 for stage1, it is better if this two can be in. (If I still get the chance)

**Comment by deguio** [comment]
-1
please rebase this one

**Comment by deguio** [comment]
the equivalent of this PR has been merged in 74 already

**Comment by deguio** [comment]
please rebase asap.
thanks,
F.

**Comment by jingyucms** [comment]
close
covered by 10662

**Pull request closed without merging**
