### PR TITLE
Make usage of TDC cuts on HF min-bias bits configurable

### PR DESCRIPTION
**Pull request by christopheralanwest**
Recently the HCAL implemented cuts on TDC timing in HF trigger primitives to reduce the contribution of (out-of-time) HF noise to the L1 ETMHF rate. Currently the trigger primitive emulation applies these cuts to both the E<sub>T</sub> calculation as well as the minimum-bias feature bit. But it is desired to apply these cuts only to the E<sub>T</sub> calculation, as the contribution of HF noise is unimportant in low-PU and HI runs, where the min-bias bit is used; this is also the default behavior of the firmware.

This PR implements the ability to ignore TDC cuts when computing the min-bias feature bit in emulation. The plots below compare data versus emulation for the min-bias feature bit in HcalNZS data [1] for three cases:

- the current TP emulation
- the modified TP emulation, but with `useTDCInMinBiasBits` set to true; this reproduces the existing behavior
- the modified TP emulation, but with `useTDCInMinBiasBits` set to the default (false), which provides perfect agreement between data and emulation

Current |  `useTDCInMinBiasBits` = true | `useTDCInMinBiasBits` = false
------------ | ------------- | -------------
fg1_emul_vs_fg1_after_fix_use_tdc_run320059|fg1_emul_vs_fg1_before_fix_run320059| fg1_emul_vs_fg1_after_fixrun320059

In all three cases, the E<sub>T</sub> correlation has also been verified to be perfect, as expected; this PR should not change any aspect of the E<sub>T</sub> correlation.

As the TDC cuts are not used in simulation (the relevant noise sources are not simulated) and the cuts were only introduced in run 319549, this PR should have no effect on any PR comparison test.

In addition, a unrelated change was made to some of the methods of the `HcalTriggerPrimitiveAlgo`, which had names that referenced the year in which a particular upgrade was performed. A more logical naming convention has been introduced, which is based on the type of digis that enter the algorithm.

A backport PR will be generated for use in the online DQM, which monitors the correlation between data and emulated TPs.

[1] /store/data/Run2018C/HcalNZS/RAW/v1/000/320/059/00000/6A727A3E-F78D-E811-8743-FA163E089CCC.root

### CODE REVIEW

**Comment by thomreis** [comment]
please test

**Comment by thomreis** [comment]
Hi @christopheralanwest 
I guess you also want to make a backport PR to the 10_2_X branch since master now points to 10_3_X.

**Comment by thomreis** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Pull request merged**
