### PR TITLE
Simplify L1TPhase2MuonOffline and fix the matching with gen muons in it

### PR DESCRIPTION
**Pull request by perrotta**
#### PR description:

The last item listed in the github issue https://github.com/cms-sw/cmssw/issues/39194 reports about a non reproducibility observed in DQM in the PR tests for the efficiencies for Phase2 muons.

The class that provides those efficiency plots is L1TPhase2MuonOffline, recently introduced in the release with the merging of #38442.

I do not expect that this PR can fix such a non reproducibility issue (say I would be surprised if so). However, cleaning the code a bit could help possible further degugging of the same. This is what this PR is intended to.

@cms-sw/l1-l2 please only consider this PR if it does not interfere with other updates that you are independently implementing in that code to fix the reported issue. Still you can take these simplifications into account for your own code, if so.

Further simplifications and or optimizations are also certainly possible for this code!

#### PR validation:

It compiles and runs on a few Phase2 workflows

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
I've found a bug in the method L1TPhase2MuonOffline::matchMuonsToGen as it was coded in origin: the match was saved even if there was actually no match, with a null pointer for the muon. I don't know if it is the possible culprit for the issue of the non reproducibility reported in the PR description, but it certainly needs to be fixed.

A fix is now coded in the commit [01f6d9f](https://github.com/cms-sw/cmssw/pull/39283/commits/01f6d9fe11c06236311e3f13af402aa783d5f5fb)

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
please abort

**Comment by perrotta** [comment]
plese test

**Comment by cecilecaillol** [comment]
+l1

**Comment by perrotta** [comment]
type bugfix

**Comment by emanueleusai** [comment]
+1

- differences in L1T DQM plots noted in https://github.com/cms-sw/cmssw/issues/39194 already (and the reason for this PR)

**Comment by perrotta** [comment]
+1

**Pull request merged**
