### PR TITLE
Phase2-hgx322 Attempt to find the missing hits in the partial wafers in HGCalHESilicon section of the V17 geometry

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Attempt to find the missing hits in the partial wafers in HGCalHESilicon section of the V17 geometry

#### PR validation:

Use the runTheMatrix test workflows

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

This is a bug fix. Otherwise nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by srimanob** [comment]
Not sure I understand the PR title and description. What change in XML is kind of bug-fix or something else?

**Comment by bsunanda** [comment]
It is a bug fix. The name of the sensitive layer triggers the recording of hits. There was a mistake in the past and that is why no hits were recorded in the partial wafers of the HE section in the V17 geometry. The muon tomography test discovered this (earlier we had missing hits in the EE section as well which was due to a different error in the code and fixed recently)

**Comment by bsunanda** [comment]
+geometry

**Comment by bsunanda** [comment]
type bug-fix

**Comment by perrotta** [comment]
+1

**Pull request merged**
