### PR TITLE
a few missing includes/dependencies in DataFormats

### PR DESCRIPTION
**Pull request by davidlange6**
#### PR description:

Parts of #28219  that are not in #28209 

Fix some missing includes and missing dependencies in DataFormats packages.

### CODE REVIEW

**Comment by vgvassilev** [comment]
Part of the mega meta-issue #15248

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
please test

**Comment by perrotta** [comment]
+1
- Technical
- Jenkins tests pass

**Comment by Martin-Grunewald** [comment]
+1

**Comment by santocch** [comment]
+1

**Comment by smuzaffar** [comment]
@fabiocos , can we get this in next IB. This will be help fixing some issues for CXXMODULE IB.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
