### PR TITLE
Phase2-hgx354A Attempt to make xml files for cassette tests from an overall silicon wafer flat file of HGCal

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Attempt to make XML files for cassette tests from an overall silicon wafer flat file of HGCal

#### PR validation:

Use the modified script to make XML files

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by bsunanda** [comment]
@srimanob Please approve this PR. The changes are meant for cassette test code

**Comment by srimanob** [comment]
+Upgrade

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
