### PR TITLE
Fix for SiPixelRecHitFromCUDA crash during online GPU tests

### PR DESCRIPTION
**Pull request by czangela**
#### PR description:

These changes address the GPU error brought up in #34831 [comment](https://github.com/cms-sw/cmssw/issues/34831#issuecomment-896409931). [1]

The was error apparently was due to a `digi` at `row` 0 `col` 0, and the `adc` value not being (correctly) set in the packing, and then when checking in [SiPixelDigisClustersFromSoA.cc#137](https://cmssdt.cern.ch/dxr/CMSSW/source/RecoLocalTracker/SiPixelClusterizer/plugins/SiPixelDigisClustersFromSoA.cc#137) that one digi was skipped, so the associated cluster never got created, so later one ends up with one more rechit than actual clusters in that one module.

This is the actual digi being lost:
`Digi index 754; clusid 8; rawIdArr 344545284; adc 25661, pdigi: 00000000000000000000000000000000`

The condition `digis.pdigi(i) == 0`  was initially meant to check whether the digi was left uninitialized from the [RawToDigi_kernel](https://cmssdt.cern.ch/dxr/CMSSW/source/RecoLocalTracker/SiPixelClusterizer/plugins/SiPixelRawToClusterGPUKernel.cu#361-363). But the problem is that a packed digi can be all zeros. For checking uninitialized digis, this condition is changed to `digis.rawIdArr(i) == 0`.

Other than that, to filter noisy/dead pixel digis the condition `digis.adc(i) == 0` was added well, [based on the treating of noisy/dead pixels in the calibDigis kernel](https://cmssdt.cern.ch/dxr/CMSSW/source/RecoLocalTracker/SiPixelClusterizer/plugins/gpuCalibPixel.h#57-59).

[1]
```
cmsRun: /data/cmsbld/jenkins/workspace/auto-builds/CMSSW_11_3_4-slc7_amd64_gcc900/build/CMSSW_11_3_4-build/tmp/BUILDROOT/58d469321d6ecb0427dd1e9f6c3703d5/opt/cmssw/slc7_amd64_gcc900/cms/cmssw/CMSSW_11_3_4/src/RecoLocalTracker/SiPixelRecHits/plugins/SiPixelRecHitFromCUDA.cc:143: 
virtual void SiPixelRecHitFromCUDA::produce(edm::Event&, const edm::EventSetup&): 
Assertion `nhits <= dsv.size()' failed.


A fatal system signal has occurred: abort signal
The following is the call stack containing the origin of the signal.

...

Module: SiPixelRecHitFromCUDA:hltSiPixelRecHits@cuda (crashed)
```

#### PR validation:

Atm it was only checked that the recipe described in #34831 does not crash in 11_3_4.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
enable gpu

**Comment by slava77** [comment]
abort test

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by tvami** [comment]
type bug-fix

**Comment by slava77** [comment]
> Probably an **extra look at packing on the GPU is required and maybe a fix as well**.

shouldn't the fix be done upstream?

What was the reason that a non-zero adc was computed for this digi while the packed value is 0?
Is it meaningful to write out a digi with a packed value 0 in the output digi collection?

Unless it's clear that this behavior is expected by design, if this is somehow time critical and can not be fixed upstream now, please add a LogWarning message for the `pdigi==0 && adc != 0`.

**Comment by tsusa** [comment]
> > Probably an **extra look at packing on the GPU is required and maybe a fix as well**.
> 
> shouldn't the fix be done upstream?
> 
> What was the reason that a non-zero adc was computed for this digi while the packed value is 0?
> Is it meaningful to write out a digi with a packed value 0 in the output digi collection?
> 
> Unless it's clear that this behavior is expected by design, if this is somehow time critical and can not be fixed upstream now, please add a LogWarning message for the `pdigi==0 && adc != 0`

@slava77  this was meant to be a quick fix just to prevent a crash. We are working on the proper (upstream) fix

**Comment by fwyzard** [comment]
> We are working on the proper (upstream) fix

Then let's wait for the proper fix, please.

**Comment by czangela** [comment]
I changed the check for `digis.rawIdArr(i) == 0`.
Basically this check was intended to detect uninitialized digis from here: https://cmssdt.cern.ch/dxr/CMSSW/source/RecoLocalTracker/SiPixelClusterizer/plugins/SiPixelRawToClusterGPUKernel.cu#361-363
But the problem is that some packed digis can actually be all zero, `row == 0, col == 0` and occasionally yes `adc == 0`. So one should either just check for `rawIdArr == 0` or invalidModuleId.

**Comment by czangela** [comment]
> > Probably an **extra look at packing on the GPU is required and maybe a fix as well**.
> 
> shouldn't the fix be done upstream?
> 
> What was the reason that a non-zero adc was computed for this digi while the packed value is 0?

So this is not the `adc` value anymore, but the `electrons` after calibration.

> Is it meaningful to write out a digi with a packed value 0 in the output digi collection?

Yes, row and col can be 0, and based on a conversation with Danek, we don't want to discard digis with adc = 0. So in a rare occasion, it can be that the packed digi value is 0.

> Unless it's clear that this behavior is expected by design, if this is somehow time critical and can not be fixed upstream now, please add a LogWarning message for the `pdigi==0 && adc != 0`.

A warning of this kind is not required, because by this time the two values don't represent the same thing, adc vs. electrons, so it doesn't make sense to compare them and issue a warning in case of inequality.

**Comment by fwyzard** [comment]
ok, @czangela explained to me that this is actually the correct fix - still, she might look at adding some comments and/or making the check more explicit

**Comment by fwyzard** [comment]
please test

**Comment by tsusa** [comment]
please test

**Comment by slava77** [comment]
+reconstruction

for https://github.com/cms-sw/cmssw/pull/35229	1444e50
- code changes are in line with the PR follow up review and discussion
    - the PR description is a bit outdated; @czangela please update the text there.
- jenkins tests pass and comparisons with the baseline show no relevant differences (the small diffs in the GPU pixel tracking wf 10824.502 are more likely from non-repeatability of the workflow results in vertexing)

**Comment by fwyzard** [comment]
Sorry for the delay, it took me a wile to put together an online-like HLT menu for CMSSW 12.0.x/12.1.x.

I can confirm that this PR fixes the crash that was [observed](https://github.com/cms-sw/cmssw/issues/34831#issuecomment-897909027) in run 344676 .

@czangela, could you prepare a backport to CMSSW 12.0.x, please ?

**Comment by fwyzard** [comment]
+heterogeneous

**Comment by perrotta** [comment]
+1
- bug fix

**Comment by czangela** [comment]
I updated the description and added the backport to 12_0_X. @slava77 @fwyzard

**Pull request merged**
