### PR TITLE
Phase2-hgx341X Try to provide more realistic names to some of the variables in Geometry/HGCalCommonData/plugins/dd4hep codes

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Try to provide more realistic names to some of the variables in the codes of Geometry/HGCalCommonData/plugins/dd4hep

#### PR validation:

Use the runTheMatrix test workflows

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by bsunanda** [comment]
@srimanob Please approve this

**Comment by srimanob** [comment]
+Upgrade

**Comment by rappoccio** [comment]
+1 

technical

**Pull request merged**
