### PR TITLE
Random generator service for FastSim

### PR DESCRIPTION
**Pull request by civanch**
Recently it was discovered, that some of components of FastSim calls CLHEP default directly instead of access to the generator via CMSSW Service. Potentially, this may provide data race and/or non-reproducibility of results in MT mode, because the default CLHEP engine is static. Due to this problem we stack with migration to the recent CLHEP 4.2.0.0

Currently, known places in FastSim where CLHEP or Geant4 calls to engine are used : HF shower library, FTF nuclear interaction, CTTPS forward simulation.

FastSim has utility which access CMSSW Service correctly. In this clean-up a thread save method to initialise random engine is added using FullSim approach, so in all sampling, even in Geant4 components, the same random generator will be used. Current default for FastSim is TRandom3 but any other may be configured. Additionally, the inline methods of this utility are modified to reduce number of "if" and to use common interface to Gauss and Poisson sampling.

The payment for this fix - direct dependence of FastSim/Utilities on Geant4. Note, that FastSim already depends on Geant4 directly and indirectly, I do not think that this dependence make a problem. Also random number sequence will be different, so many differences should be seen in FastSim WFs.

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
Hi, @Dr15Jones, you may be want to comment on this PR?

**Comment by davidlange6** [comment]
this doesn't make sense- we don't need to go through G4 to get random numbers in CMS..

**Comment by Dr15Jones** [comment]
@davidlange6 It appears to me that with this pull request, the random numbers come from CMS via the RandomNumberGenerator service. The G4 part is just passing the CMS random engine to G4 to use since, under the hood, fastsim is calling G4 components which need a random number.

**Comment by civanch** [comment]
@davidlange6 , internally, HF Shower library use G4 methods and FastSim FTF nuclear generator in tracker use Geant4 model. Potentially, there may be other consumers of Geant4.

**Comment by ssekmen** [comment]
Indeed, this is the G4 usage we have now (although the FTP nuclear interactions are currently not actively used).

**Comment by davidlange6** [comment]
Indeed - I missed that point - so then we should ensure in either a more central, or more targeted  location that g4 is initialized in fastsim jobs- buried in a class within FastSimulation/Utilities hardly seems like the place for that (as this class is _not_ used by G4 and does not currently use G4) That way we control dependencies

**Comment by civanch** [comment]
What about FamosProducer? The same line of code may be moved there.

This may work but I am not 100% sure. The choice of Utility was done for reason, that other Producers may use the same FastSimUtility , so it is more safe (number of plugins in FastSim sequence is big enough and may be some also use random numbers). A solution would be to include the same line in all producers we have for today (which use random numbers).

**Comment by davidlange6** [comment]
how about in a trivial  new plugin living in SimG4Core?

**Comment by ssekmen** [comment]
I don't think FamosProducer is more central compared to FastSimulation/Utilities, which is already used by many fastsim modules.
If a new plugin in SimG4Core is easier to keep under control, this is also ok.

**Comment by civanch** [comment]
@Dr15Jones , a basic question: are we sure that all FastSim plugins are in the same streamID? If not, how we should handle this? This is a general question also for FullSim where we in one plugin smear interaction point and in Oscar generate hits.

**Comment by Dr15Jones** [comment]
Plugins called from the same module instance for the same event will be on the same thread and will therefore have the same stream ID. As long as G4 is using a thread_local to hold the random engine, everything will be fine.

**Comment by civanch** [comment]
In that case may be FamosProducer is a correct solution? Making extra empty producer in SimG4Core do a problem, but at the same time, may be easily forgotten by FastSim developers inside their unit tests and other evolutions.

**Comment by civanch** [comment]
The G4Random engine definition was moved to FamosProducer and after 4 events of ttbar random sequence become different. It was discovered that inside FastSimulation/TrackingRecHitProducer sub-library a different method to define random engine is used. The proposed modification makes redefinition of the engine per event as it is done in FamosProducer.

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
Needs more study...

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
@davidlange6 , @ssekmen,   TrackingRecHitProducer library is done correctly, I have returned it to the previous variant. Geant4 random is initialised in FamosProducer. Many differences are expected.

**Comment by civanch** [comment]
@ssekmen , can you sign this PR?

**Comment by ssekmen** [comment]
+1

**Comment by davidlange6** [comment]
adding a g4 dependency to FastSimulation/EventProducerdoesn't look like a good idea. in addition, you are still relying on luck that this code gets called before the fastsim code that depends on g4 does... Did you evaluate moving the initialization to the code that actually uses Geant4 in the FastSim workflow?

**Comment by civanch** [comment]
Hi @davidlange6 , there are currently two places where G4Random is used: in HF shower library (this is used by default) and in hadronic interaction sampling in tracker (in alternative model). We cannot exclude in future usage of G4Random or Geant4 itself somewhere else, in particular in digitisation. I think that initialising of G4Random in FamosProducer is the most safe solution, because whatever you will do downstream G4Random is already correctly initialised. The fact of dependence of FamosProducer on Geant4 is not a big problem taking into account the fact that HF shower library practically depend on Geant4 and Famos is using it.

**Comment by davidlange6** [comment]
-1
as defined in the release meeting, only viable spot to initial g4 randoms is in the module(s) that will use them

**Comment by civanch** [comment]
@davidlange6 , FamosProducer (where G4Random is initialised) is the correct place, because from it HF library is called and also tracking inside tracker is performed. Any other module may have problem.

**Comment by civanch** [comment]
@davidlange6 , may be extra explanations required: RandomNumberGeneratorService centrally handle random generators and seeds per the list of producers. One is OscarProducer, another FamosProducer. In Oscar the generator engine is given to G4Random, so Geant4 uses one random number sequence. In FamosProducer there is an internal object which keeps random engine and is transformed to each sub-module of hit sampling via interface. If Geant4 classes are used than in parallel thge same instance of random engine should be given to G4Random. Within a producer (Oscar or Famos) the radnom sequence is coming from one engine, the work for different classes is performed in fixed sequence. When Famos or Oscar complete run time method ::produce(...) other producers may be involved, at this point it is the responsibility of the framework to handle correctly random numbers, normally for each producer this service provides a new random engine. After Famos and Oscar Geant4 random numbers are not used. So, for me this PR is correct.

**Comment by davidlange6** [comment]
lets look at each usage

For the SL - here is a good spot for this initialization
void const FastHFShowerLibrary::initHFShowerLibrary(const edm::EventSetup& iSetup) {

for MaterialEffects stuff - I would do it here:
MaterialEffects::MaterialEffects(const edm::ParameterSet& matEff)
by adding a EventSetup argument. Then you have much cleaner library dependencies

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
DAS error - not connected to this PR

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1
the updated implementation provides the same random sequence as the previous one (checked in local test)

**Comment by fabiocos** [comment]
@civanch There was also a residual comment about the MaterialEffects package, where the geant4 dependency is still there. Could you please comment?

**Comment by fabiocos** [comment]
please test workflow 135.1

**Comment by civanch** [comment]
@fabiocos , since long we have an alternative FastSim hadronic model for nuclear interaction in tracker, which based on FTF Geant4 model. For that we introduced FastSim dependence on Geant4. From my point of view, this model is technically much better than the default FastSim model. I have in mind adding more Geant4 based models for FastSim.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
