### PR TITLE
[13_0_X backport ] Fall17V2 photon IDs and Isolations saved only in Run2 Nanos

### PR DESCRIPTION
**Pull request by Prasant1993**
#### PR description:

Backport of PR #42255 (Add 4 Isolation variables for Photon to NanoAOD) and #42247 (Add hasConversionTracks to nano). See description there. 

#### PR validation:

Same as #42255 

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport required for processing of 2022 and 2023 data/MC which will happen in 13_0_X.

### CODE REVIEW

**Comment by simonepigazzini** [comment]
enable nano

**Comment by simonepigazzini** [comment]
please test

**Comment by simonepigazzini** [comment]
please test

**Comment by simonepigazzini** [comment]
@Prasant1993 what is your time scale for the electron PR? we would like to launch a NANO production very soon and would like to finalize the release for that this week.

Thank you

**Comment by simonepigazzini** [comment]
btw, http://tinyurl.com/2xkm4m6g some of the added variables are empty. Chiefly "hasConvertionTracks"

**Comment by Prasant1993** [comment]
> @Prasant1993 what is your time scale for the electron PR? we would like to launch a NANO production very soon and would like to finalize the release for that this week.
> 
> Thank you

Hi @simonepigazzini, yes I will do the electron PR by doing the necessary changes as photons  by tomorrow.

**Comment by Prasant1993** [comment]
> btw, http://tinyurl.com/2xkm4m6g some of the added variables are empty. Chiefly "hasConvertionTracks"

Thanks for pointing this out. The name of this DQM  histogram is  not correctly saved.  It is currently saved as "hasConversionTrackTracks". 
However, it should be saved as "hasConversionTracks" as the right variable.
So it is also wrong in this PR #42247 by @JaLuka98 .  
I will correct this in this PR.

**Comment by simonepigazzini** [comment]
please test

**Comment by antoniovilela** [comment]
+1

**Comment by antoniovilela** [comment]
please abort

**Pull request merged**
