### PR TITLE
Payload inspector framework moved to pybind11

### PR DESCRIPTION
**Pull request by ggovi**
#### PR description:

In the PayloadInspector module, we have adopted a binding C++/python to provide interoperability between the manipulation of payload data within the C++, and the rendering of plots in a python-based web application. 
In this PR we replace the binding based on boost::python with pybind11.

The macro for the generation of the PayloadInspector plugins has been replaced and can be successfully applied to the various subsystems.

#### PR validation:

Unit/integration test + deployment in the DEMO slot within the Payload Inspector web app (Conddb browser )

### CODE REVIEW

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by qliphy** [comment]
(partial) duplicate of #34692

**Comment by smuzaffar** [comment]
@ggovi , I would suggest to go ahead and sign this PR and we close the other one

**Comment by ggovi** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
