### PR TITLE
Remove obsolete Digi collections

### PR DESCRIPTION
**Pull request by rovere**
#### PR description:

Remove some obsolete `HGCAL` Digi collections that are no longer needed.
Expect no regression.

#### PR validation:

Limited Matrix runs smoothly.

### CODE REVIEW

**Comment by rovere** [comment]
@cmsbuild please test

**Comment by rovere** [comment]
+1

**Comment by AdrianoDee** [comment]
+1

**Comment by civanch** [comment]
+1

**Pull request merged**
