### PR TITLE
[GT Updates] PixelDynamicInEff, PixelQuality, HCALQuality, ECALTPG, JetProbability BTag Calib

### PR DESCRIPTION
**Pull request by arunhep**
# Summary of changes in Global Tags 
 
## MC 2017
 
   * **PhaseI 2017 cosmics peak scenario** : [94X_mc2017cosmics_realistic_peak_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_mc2017cosmics_realistic_peak_v0) as [93X_mc2017cosmics_realistic_peak_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/93X_mc2017cosmics_realistic_peak_v3) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_mc2017cosmics_realistic_peak_v0/93X_mc2017cosmics_realistic_peak_v3): 
      * update of Jet Probability calibration for b-tagging : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3231.html
      * update of HCAL channel quality : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3259.html
      * update of Pixel channel Quality : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3244.html
      * update of ECAL TPG tags

   * **PhaseI 2017 cosmics scenario** : [94X_mc2017cosmics_realistic_deco_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_mc2017cosmics_realistic_deco_v0) as [93X_mc2017cosmics_realistic_deco_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/93X_mc2017cosmics_realistic_deco_v3) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_mc2017cosmics_realistic_deco_v0/93X_mc2017cosmics_realistic_deco_v3): 
      * update of Jet Probability calibration for b-tagging : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3231.html
      * update of HCAL channel quality : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3259.html
      * update of Pixel channel Quality : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3244.html
      * update of ECAL TPG tags

   * **PhaseI 2017 realistic scenario** : [94X_mc2017_realistic_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_mc2017_realistic_v1) as [94X_mc2017_realistic_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_mc2017_realistic_v0) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_mc2017_realistic_v1/94X_mc2017_realistic_v0): 
      * update of Pixel dynamic inefficiency for 2017 : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3257.html
      * update of Jet Probability calibration for b-tagging : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3231.html
      * update of HCAL channel quality : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3259.html
      * update of Pixel channel Quality : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3244.html
      * update of ECAL TPG tags

## Upgrade

   * **PhaseI 2018 cosmics scenario** : [94X_upgrade2018cosmics_realistic_deco_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_upgrade2018cosmics_realistic_deco_v0) as [93X_upgrade2018cosmics_realistic_deco_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/93X_upgrade2018cosmics_realistic_deco_v2) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_upgrade2018cosmics_realistic_deco_v0/93X_upgrade2018cosmics_realistic_deco_v2): 
      * update of Jet Probability calibration for b-tagging : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3231.html
      * update of Pixel channel Quality : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3244.html
      * update of ECAL TPG tags

   * **PhaseI 2018 design scenario** : [94X_upgrade2018_design_IdealBS_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_upgrade2018_design_IdealBS_v1) as [94X_upgrade2018_design_IdealBS_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_upgrade2018_design_IdealBS_v0) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_upgrade2018_design_IdealBS_v1/94X_upgrade2018_design_IdealBS_v0): 
      * update of Jet Probability calibration for b-tagging : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3231.html

   * **PhaseI 2018 realistic scenario** : [94X_upgrade2018_realistic_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_upgrade2018_realistic_v1) as [94X_upgrade2018_realistic_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_upgrade2018_realistic_v0) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_upgrade2018_realistic_v1/94X_upgrade2018_realistic_v0): 
      * update of Jet Probability calibration for b-tagging : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3231.html
      * update of ECAL TPG tags
      * update of Pixel dynamic inefficiency for 2017 : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3257.html
      * update of Pixel channel Quality : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3244.html

### CODE REVIEW

**Comment by arunhep** [comment]
Attn. @franzoni @tvami @boudoul @cmkuo @amassiro @veszpv @jkarancs

**Comment by arunhep** [comment]
@cmsbuild please test

**Comment by arunhep** [comment]
+1
changes at right places. More evaluation will be done in relval campaign for next pre release.

**Comment by davidlange6** [comment]
please test 250202.17

**Comment by arunhep** [comment]
> please test 250202.17
@davidlange6 what is this test?

**Comment by davidlange6** [comment]
its 2017+pileup
but in any case it won't give me what I want - do we have some plots of the effect on tracking for a PU relval? (I see the ones for pu=0 have essentially no change, which is good)

**Comment by arunhep** [comment]
ok. it seems like the tests have not started with your command. May be the syntax is not correct.

The following presentation shows the effect of this dynamic inefficiency on Hit efficiency : https://indico.cern.ch/event/649348/contributions/2729531/attachments/1527096/2388119/2017_09_20_PixelOfflineMeeting_EffLossUpdate.pdf

@jkarancs can provide more details if needed.

**Comment by davidlange6** [comment]
hi @arunhep - i don't mean developer level checks, I mean ones using this PR (eg, what RECO is doing for RECO PRs). maybe you have done something?

I've added a 2017 PU workflow to PR tests (hopefully).

**Comment by davidlange6** [comment]
please test

**Comment by ghellwig** [comment]
> please test 250202.17
@davidlange6 I might be mistaken, but did you intend to write this?:
```
please test workflow 250202.17
```

**Comment by davidlange6** [comment]
Yes - but I moved onto a more complete solution now that hopefully will provide also comparisons.



On 29 Sep 2017, at 11:12, Gregor Mittag <notifications@github.com<mailto:notifications@github.com>> wrote:


please test 250202.17
@davidlange6<https://github.com/davidlange6> I might be mistaken, but did you intend to write this?:

please test workflow 250202.17

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
+1
No noticeable changes seen in hits on tracks with pu35

**Pull request merged**
