### PR TITLE
Phase I Beampipe Overlap Fix

### PR DESCRIPTION
**Pull request by ianna**
* Extend BEAM Air envelope to cover both bellows

Note, based on (already merged) https://github.com/cms-sw/cmssw/pull/16401

before and after the fix:
screenshot 2016-11-01 16 00 15
screenshot 2016-11-01 15 59 37

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
@davidlange6 - this PR needs only geometry signature because the rest of changes come from an already merged #16401, but it looks like PR rebasing does not show it yet.

**Comment by dmitrijus** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
