### PR TITLE
Changing FFTJet modules to stream modules

### PR DESCRIPTION
**Pull request by igv4321**
#### PR description:

Changed all FFTJet modules to stream modules. This is just a technical fix, no change is expected for any outputs.

#### PR validation:

runTheMatrix was run as well as some private checks.

### CODE REVIEW

**Comment by jpata** [comment]
@igv4321 thanks for this. For my understanding, do the FFTJet modules run in any matrix workflow? Or what's their use case currently?

**Comment by jpata** [comment]
@igv4321 thanks for this. For my understanding, do the FFTJet modules run in any matrix workflow? Or what's their use case currently?

**Comment by igv4321** [comment]
FFTJet modules do not run in any matrix workflow. The code is currently dormant. I hope to get a student to work on multiresolution jet reconstruction, then we will start using it again.

**Comment by jpata** [comment]
+reconstruction
- technical
- it was not tested that it runs now after the changes (I leave it to the author to test it in the future)

**Comment by perrotta** [comment]
+1

**Pull request merged**
