### PR TITLE
Replace reference to ParameterSet with explicit parameter values in HBHEDarkening

### LINKED ISSUE #621: Replace reference to ParameterSet with explicit parameter values in `CalibCalorimetry/HcalPlugins/src/HBHEDarkeningEP.h`
Done in https://github.com/cms-sw/cmssw/pull/42528

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

This PR replaces a reference to `edm::ParameterSet` with explicitly parsed data structures for the configuration parameters. This change is needed for https://github.com/cms-sw/cmssw/pull/42503.

Resolves https://github.com/makortel/framework/issues/621

#### PR validation:

Code compiles.

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by tvami** [comment]
@cmsbuild, please test

**Comment by francescobrivio** [comment]
+1

 - technical PR
 - tests are clean

**Comment by perrotta** [comment]
+1

**Pull request merged**
