### PR TITLE
Change DQMEDHarvester from an edm::one::EDAnalyzer to an edm::one::EDProducer

### PR DESCRIPTION
**Pull request by gartung**
Resubmit of #18701

This also changes all config files for classes that directly or indirectly
inherit from DQMEDHarvester. The config for these classes was changed
from cms.EDAnalyzer to cms.EDProducer.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by dmitrijus** [comment]
Can this comment be implemented? Would be very useful..
https://github.com/cms-sw/cmssw/issues/15866#issuecomment-301462359

**Comment by gartung** [comment]
Ask @Dr15Jones

**Comment by kpedro88** [comment]
+1

**Comment by Dr15Jones** [comment]
Either this pull request or #18751 will be used, not both.

**Comment by Dr15Jones** [comment]
please abort

**Comment by Dr15Jones** [comment]
@gartung please close this one

**Pull request closed without merging**
