### PR TITLE
Changes to disable DDU trigger plots in DT DQM Online Trigger checks …

### PR DESCRIPTION
**Pull request by jfernan2**
…and disable check on RPC paths for TriggerEfficiency studies in DT DQM Offline. Port to 81X of PR 16679

### CODE REVIEW

**Comment by dmitrijus** [comment]
+1

**Comment by dmitrijus** [comment]
80x: https://github.com/cms-sw/cmssw/pull/16679

**Comment by davidlange6** [comment]
hi- what is the 90x pr (the development release) for this?

**Comment by jfernan2** [comment]
Hi,
90X PR is #16739

**Comment by dmitrijus** [comment]
+1

**Comment by dmitrijus** [comment]
+1

**Pull request closed without merging**
