### PR TITLE
Drop local copy of conifer.h in favor of conifer external

### PR DESCRIPTION
**Pull request by smuzaffar**
This PR removes the local copy of `conifer.h` in favor of external `conifer` package. See https://github.com/cms-sw/cmssw/pull/42663

This requires https://github.com/cms-sw/cmsdist/pull/8786

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test with https://github.com/cms-sw/cmsdist/pull/8786

**Comment by aloeliger** [comment]
+l1

**Comment by smuzaffar** [comment]
Milestone for this pull request has been moved to CMSSW_14_0_X.Please open a backport if it should also go in to CMSSW_13_3_X.

**Comment by srimanob** [comment]
+Upgrade

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
