### PR TITLE
TkAl: add pool check to condor submission

### PR DESCRIPTION
**Pull request by adewit**
#### PR description:

This adds, for the TkAl validation tool and millepede job submission, a check for which condor pool has been set up. If there is a mismatch between that and the requested resources, the code exits and tells the user to set up the correct pool via `module load`. Also of interest to @connorpa @vbotta

#### PR validation:

Tested various condor submissions with different initial conditions; this change has the intended behaviour
#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Not a backport

### CODE REVIEW

**Comment by christopheralanwest** [comment]
please test

**Comment by christopheralanwest** [comment]
please test

**Comment by pohsun** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
