### PR TITLE
[11_2_X] EMTF Emulator Update to Add Displaced Muon pT & Dxy Assignment

### PR DESCRIPTION
**Pull request by eyigitba**
#### PR description:

This PR updates EMTF emulator by adding a new class (`PtAssignmentEngineDxy`) that handles vertex unconstrained pT and Dxy assignment. The changes should not affect anything for prompt muons. The main changes are:

- Added `PtAssignmentEngineDxy` and necessary changes to the EMTF algorithm to support it.
- Added setters and getters for vertex unconstrained pT and Dxy to `EMTFTrack`

#### PR validation:

Validated with:

- scram b runtests
- runTheMatrix.py -l limited -i all --ibeos

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

This is a backport of PR #32813, which is done to include this update in Run 3 MC campaigns and upcoming MWGRs.

Notifications: @jiafulow

### CODE REVIEW

**Comment by rekovic** [comment]
please remove the data file 
L1Trigger/L1TMuonEndCap/data/emtfpp_tf_graphs/model_graph.displ.5.pb 
 and PRit to external data repostitory https://github.com/cms-l1t-offline/L1Trigger-L1TMuon

**Comment by silviodonato** [comment]
test parameters:
  - pull_request = https://github.com/cms-l1t-offline/L1Trigger-L1TMuon/pull/10

**Comment by silviodonato** [comment]
test parameters:
  - pull_request = cms-l1t-offline/L1Trigger-L1TMuon|#10

**Comment by mrodozov** [comment]
the PR is on the for of cms-data instead of that branch being used for a cms-data PR :) 
it's a fork of a fork :D ok let me fix it after the meeting

**Comment by mrodozov** [comment]
test parameters:
    pull_request = https://github.com/cms-data/L1Trigger-L1TMuon/pull/19

**Comment by mrodozov** [comment]
looks like this is backport of https://github.com/cms-sw/cmssw/pull/32641 on 11_2

**Comment by mrodozov** [comment]
please test

**Comment by eyigitba** [comment]
The main PR (#32641 ) had some thread safety issues in the IB. I am now fixing those with a new PR.

Should I update this PR directly or should I wait for it to be merged and submit another backport?

**Comment by mrodozov** [comment]
It's up to you actually, you could do either. A benefit of keeping this PR would be that the externals for it are already built and in place, it will take less time to setup the test this way. With a new backport even tho the externals are not required to be rebuild they'll still need to be installed which is taking some time. 
If the fix is not a major change just cherry-pick it's commits (if possible) on top of this one

**Comment by eyigitba** [comment]
@mrodozov thanks for the quick reply. I'll keep this PR then. The changes are pretty minor anyway.

**Comment by mrodozov** [comment]
I understand it needs the same data external + code changes from the last commit

**Comment by mrodozov** [comment]
please test

**Comment by eyigitba** [comment]
> I understand it needs the same data external + code changes from the last commit

yes that's correct

**Comment by silviodonato** [comment]
If you have updated the code  to #32813, please update the PR description (ie. please remove  #32641)

**Comment by eyigitba** [comment]
> If you have updated the code to #32813, please update the PR description (ie. please remove #32641)

Sorry about that. I updated the PR description to point to the correct PR.

**Comment by rekovic** [comment]
+1

**Comment by qliphy** [comment]
+1

**Comment by christopheralanwest** [comment]
There are many failing relvals in the 11_2_X IBs, with errors such as:
```
----- Begin Fatal Exception 12-Feb-2021 01:54:37 CET-----------------------
An exception of category 'FileInPathError' occurred while
   [0] Processing  Event run: 1 lumi: 1 event: 3 stream: 1
   [1] Running path 'FEVTDEBUGHLToutput_step'
   [2] Prefetching for module PoolOutputModule/'FEVTDEBUGHLToutput'
   [3] Prefetching for module RawDataCollectorByLabel/'rawDataCollector'
   [4] Prefetching for module L1TDigiToRaw/'gmtStage2Raw'
   [5] Calling method for module L1TMuonEndCapTrackProducer/'simEmtfDigis'
Exception Message:
edm::FileInPath unable to find file L1Trigger/L1TMuon/data/emtf_luts/model_graph.displ.5.pb anywhere in the search path.
The search path is defined by: CMSSW_SEARCH_PATH
${CMSSW_SEARCH_PATH} is: /data/cmsbld/jenkins/workspace/ib-run-relvals/CMSSW_11_2_X_2021-02-11-2300/poison:/data/cmsbld/jenkins/workspace/ib-run-relvals/CMSSW_11_2_X_2021-02-11-2300/src:/data/cmsbld/jenkins/workspace/ib-run-relvals/CMSSW_11_2_X_2021-02-11-2300/external/cc8_amd64_gcc9/data:/cvmfs/cms-ib.cern.ch/nweek-02667/cc8_amd64_gcc9/cms/cmssw-patch/CMSSW_11_2_X_2021-02-11-2300/poison:/cvmfs/cms-ib.cern.ch/nweek-02667/cc8_amd64_gcc9/cms/cmssw-patch/CMSSW_11_2_X_2021-02-11-2300/src:/cvmfs/cms-ib.cern.ch/nweek-02667/cc8_amd64_gcc9/cms/cmssw-patch/CMSSW_11_2_X_2021-02-11-2300/external/cc8_amd64_gcc9/data
Current directory is: /data/cmsbld/jenkins/workspace/ib-run-relvals/CMSSW_11_2_X_2021-02-11-2300/pyRelval/135.1_TTbar_13+TTbarFS_13+HARVESTUP15FS+MINIAODMCUP15FS
----- End Fatal Exception -------------------------------------------------
```

These are apparently a consequence of merging this PR. Is a fix underway?

**Comment by eyigitba** [comment]
This looks like the data file from cms-data/L1Trigger-L1TMuon#19 is missing somehow. I don't know why. @rekovic can we do something about this?

**Comment by qliphy** [comment]
@eyigitba @rekovic @silviodonato @smuzaffar    It seems that we need to update 11_2 tag  for L1Trigger-L1TMuon to V01-03-00: similarly as done in the PR for master: https://github.com/cms-sw/cmsdist/pull/6616

**Comment by smuzaffar** [comment]
done here https://github.com/cms-sw/cmsdist/pull/6646 and merged for next Ib

**Pull request merged**
