### PR TITLE
Removed legacy EDAnalyzer interface

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

- All uses of edm::EDAnalyzer should have already been removed from CMSSW. This now removes that interface from the framework.

#### PR validation:

Framework code compiles.

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by Dr15Jones** [comment]
I put back the EDAnalyzer.h file with an embedded `#error` to match what was done with EDProducer.h and EDFilter.h. I then added that header to the list of headers to ignore when doing header consistency checks.

**Comment by makortel** [comment]
+1

**Comment by makortel** [comment]
release-note: This PR is the final step in removing the support for legacy EDModules. Any code using legacy EDModule base classes outside CMSSW needs to be migrated to one of the base classes supporting multithreading. Please see documentation in https://twiki.cern.ch/twiki/bin/view/CMSPublic/FWMultithreadedFrameworkModuleTypes.

**Comment by perrotta** [comment]
+1

**Pull request merged**
