### PR TITLE
Extend the definition of good cell for v17 version of HGCal Geometry

### PR DESCRIPTION
**Pull request by Pruthvi-ch**
PR description:

Extend the definition of good cell for partial wafers in v17 version of HGCal Geometry.

PR validation:

Use the runTheMatrix test workflows

if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
+1

**Comment by bsunanda** [comment]
@srimanob Can you approve this PR?

**Comment by srimanob** [comment]
+Upgrade

Extension used for V17 HGCal. No change is expected from short matrix as no wf on C18 (V17) HGCal runs.

**Comment by qliphy** [comment]
+1

**Pull request merged**
