### PR TITLE
Add 2024 HiMix MC RelVal workflows

### PR DESCRIPTION
**Pull request by mandrenguyen**
#### PR description:

HiMix is the primary type of MC dataset used for heavy ions, where we overlay a pp signal on a background from the Hydjet generator. 
These use the same mechanism as pp PU workflows.  Hydjet GEN-SIM was produced in 14_1_0_pre7.

#### PR validation:

Was tested with 332.  New wfs are 330,331,332

A backport to 14_1_X will be needed.

### CODE REVIEW

**Comment by mandrenguyen** [comment]
please test workflow 330,331,332

**Comment by AdrianoDee** [comment]
+pdmv

**Comment by mandrenguyen** [comment]
@cms-sw/upgrade-l2 can you have a look please?

**Comment by srimanob** [comment]
+Upgrade

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
