### PR TITLE
HCAL Phase1 bug fixes

### PR DESCRIPTION
**Pull request by kpedro88**
1) It was found in private tests that QIE10 simulated digis appeared to have only pedestals with no signals. The problem was traced to:
https://github.com/cms-sw/cmssw/blob/CMSSW_8_1_X/SimCalorimetry/CaloSimAlgos/interface/CaloTDigitizer.h#L130

```
theHitResponse->clear();
```

The same CaloHitResponse was being used for HF QIE8 and HF QIE10. Using separate CaloHitResponse objects solves the problem. This fix will be backported to 80X.

2) In #13861, a bug was introduced in HcalDbHardcode: pedestals were set to 0 unless `fSmear` was enabled. This has been corrected. I also addressed a few lingering code review comments from @civanch that didn't make it into the previous PR. These fixes are 81X-only.

### CODE REVIEW

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by civanch** [comment]
+1

**Comment by kpedro88** [comment]
@mmusich can you look at this? It would be nice to have these fixes in the next prerelease

**Comment by mmusich** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
