### PR TITLE
Disable Not Working leading edge recovery for saturated ECAL RecHits (7_4_X back-port)

### PR DESCRIPTION
**Pull request by emanueledimarco**
- Back-porting this change also in the 7_4_X branch. 
- The full comments are in the PR #8717.

@argiro @cerminar @pierinim @ferriff @crovelli @paramatti please also follow this.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

Some more details on the physics impact are needed here. (Response changes, fraction of hits affected, data vs mc)

**Comment by slava77** [comment]
... ok, there are details in the 75x commit

**Comment by slava77** [comment]
@cmsbuild please test
trying one more time

**Comment by emanueledimarco** [comment]
same update as in the 75X branch (PR #8717)

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/8720	e62dab2
tested in CMSSW_7_4_0 /test area sign538/
The review discussion was ongoing in the 75X thread of this PR #8717.
The last notes leading to the signoff are at https://github.com/cms-sw/cmssw/pull/8717#issuecomment-94119755

Briefly: changes are only at very high energies for saturated crystals; at least in a sample fairly close to the saturation phase space the changed code doesn't show significant changes in performance.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
