### PR TITLE
Include EcalSimComponentShapeRcd in all MC GTs and remove TkAl Rcds from Phase2 MC GT

### PR DESCRIPTION
**Pull request by saumyaphor4252**
#### PR description:
This PR:
- Integrates the `EcalSimComponentShapeRcd` record in the MC GTs introduced in https://github.com/cms-sw/cmssw/pull/40855 by updating the 
  - Phase1 GTs with tag `EcalSimComponentShape_PhaseI`
  - Phase2 GT with tag `EcalSimComponentShape_PhaseII`
  as requested in this [CMS Talk post](https://cms-talk.web.cern.ch/t/add-new-conditions-ecalsimcomponentshape-in-gt-for-improved-digi-simulation/21448) [1]. 
- In addition, with this PR also removes the TkAl Records from the Phase2 MC GT, since the tracker alignment is switched off by default in all Phase-2 geometries. More details and the original request can be found in this [CMS Talk post](https://cms-talk.web.cern.ch/t/phase-1-tracker-alignment-tags-in-phase-2-global-tags/21264) [2].

[1] https://cms-talk.web.cern.ch/t/add-new-conditions-ecalsimcomponentshape-in-gt-for-improved-digi-simulation/21448
[2] https://cms-talk.web.cern.ch/t/phase-1-tracker-alignment-tags-in-phase-2-global-tags/21264/2

**GT Differences with the last ones are here**:
- **Run1 Design**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_mcRun1_design_v1/131X_mcRun1_design_v1

- **Run1 Realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_mcRun1_realistic_v1/131X_mcRun1_realistic_v1

- **Run1 HI**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_mcRun1_HeavyIon_v1/131X_mcRun1_HeavyIon_v1

- **Run2 Startup**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_mcRun2_startup_v1/131X_mcRun2_startup_v1

- **Run2 l1stage1**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_mcRun2_asymptotic_l1stage1_v1/131X_mcRun2_asymptotic_l1stage1_v1

- **Run2 design**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_mcRun2_design_v1/131X_mcRun2_design_v1

- **Run2 pre VFP**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_mcRun2_asymptotic_preVFP_v1/131X_mcRun2_asymptotic_preVFP_v1

- **Run2 Asymptotic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_mcRun2_asymptotic_v1/131X_mcRun2_asymptotic_v1

- **Run2 MC cosmics**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_mcRun2cosmics_asymptotic_deco_v1/131X_mcRun2cosmics_asymptotic_deco_v1

- **Run2 MC HI**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_mcRun2_HeavyIon_v1/131X_mcRun2_HeavyIon_v1

- **Run2 MC pA**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_mcRun2_pA_v1/131X_mcRun2_pA_v1

- **Phase1 2017 design**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_mc2017_design_v2/131X_mc2017_design_v1

- **Phase1 2017 realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/130X_mc2017_realistic_v1/131X_mc2017_realistic_v1

- **Phase1 2017 cosmics**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_mc2017cosmics_realistic_deco_v2/131X_mc2017cosmics_realistic_deco_v1

- **Phase1 2017 cosmics peak**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_mc2017cosmics_realistic_peak_v2/131X_mc2017cosmics_realistic_peak_v1

- **Phase1 2018 design**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_upgrade2018_design_v4/131X_upgrade2018_design_v1

- **Phase1 2018 realistic**   
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_upgrade2018_realistic_v2/131X_upgrade2018_realistic_v1

- **Phase1 2018 realistic RD**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_upgrade2018_realistic_RD_v3/131X_upgrade2018_realistic_RD_v1

- **Phase1 2018 realistic HI**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_upgrade2018_realistic_HI_v2/131X_upgrade2018_realistic_HI_v1

- **Phase1 2018 realistic HEfail**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_upgrade2018_realistic_HEfail_v2/131X_upgrade2018_realistic_HEfail_v2

- **Phase1 2018 cosmics**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_upgrade2018cosmics_realistic_deco_v2/131X_upgrade2018cosmics_realistic_deco_v1

- **Phase1 2018 cosmics peak**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_upgrade2018cosmics_realistic_peak_v2/131X_upgrade2018cosmics_realistic_peak_v1

- **Phase1 2022 design**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/130X_mcRun3_2022_design_v2/131X_mcRun3_2022_design_v1

- **Phase1 2022 realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/130X_mcRun3_2022_realistic_v2/131X_mcRun3_2022_realistic_v1

- **Phase1 2022 realistic postEE**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/130X_mcRun3_2022_realistic_postEE_v2/131X_mcRun3_2022_realistic_postEE_v1

- **Phase1 2022 cosmics**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/130X_mcRun3_2022cosmics_realistic_deco_v2/131X_mcRun3_2022cosmics_realistic_deco_v1

- **Phase1 2022 cosmics design**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/130X_mcRun3_2022cosmics_design_deco_v2/131X_mcRun3_2022cosmics_design_deco_v1

- **Phase1 2022 realistic hi**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/130X_mcRun3_2022_realistic_HI_v3/131X_mcRun3_2022_realistic_HI_v1

- **Phase1 2023 design**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/130X_mcRun3_2023_design_v3/131X_mcRun3_2023_design_v1

- **Phase1 2023 realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/130X_mcRun3_2023_realistic_v4/131X_mcRun3_2023_realistic_v1

- **Phase1 2023 cosmics**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/130X_mcRun3_2023cosmics_realistic_deco_v3/131X_mcRun3_2023cosmics_realistic_deco_v1

- **Phase1 2023 cosmics design**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/130X_mcRun3_2023cosmics_design_deco_v3/131X_mcRun3_2023cosmics_design_deco_v1

- **Phase1 2023 realistic hi**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/130X_mcRun3_2023_realistic_HI_v4/131X_mcRun3_2023_realistic_HI_v1

- **Phase1 2024 realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/130X_mcRun3_2024_realistic_v4/131X_mcRun3_2024_realistic_v1

- **Phase2 realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/130X_mcRun4_realistic_v3/131X_mcRun4_realistic_v1

#### PR validation:
- The ECAL changes tested locally with https://github.com/cms-sw/cmssw/pull/40855 using 
 `runTheMatrix.py -l 25.0,8.0 -j10 --ibeos` 
- The TkAl Record removal was tested locally with
`runTheMatrix.py -l 22034.0,25234.0,24834.0 -j10 --ibeos`
- The PR https://github.com/cms-sw/cmssw/pull/40855 should be tested with this.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:
Not a backport, no backport foreseen for now.

### CODE REVIEW

**Comment by mmusich** [comment]
e.g. [20834.0 is failing](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-802495/31327/runTheMatrix-results/20834.0_TTbar_14TeV+2026D88/step2_TTbar_14TeV+2026D88.log) with:
```
----- Begin Fatal Exception 16-Mar-2023 18:40:54 CET-----------------------
An exception of category 'Configuration' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing module: class=MixingModule label='mix'
Exception Message:
MissingParameter: Parameter 'componentWaveform' not found.
----- End Fatal Exception -------------------------------------------------
```

I guess because of https://github.com/cms-sw/cmssw/pull/40855

**Comment by jhakala** [comment]
Hi all, sorry about that. I made a commit ([here](https://github.com/cms-sw/cmssw/pull/40855/commits/95e50ffb0c1174ba5e02d7dc418a44f80502591b)) to fix it.

**Comment by tvami** [comment]
@cmsbuild please test

**Comment by tvami** [comment]
+alca
 * tests pass

**Comment by tvami** [comment]
@cms-sw/orp-l2 this PR has to come before https://github.com/cms-sw/cmssw/pull/40855 (tho it can go in alone, does not necessarily need to merge together)

**Comment by perrotta** [comment]
+1
- It can be merged even before https://github.com/cms-sw/cmssw/pull/40855 (which is still a work in progress)

**Pull request merged**
