### PR TITLE
Reduce complexity of erasing elements from vectors in PATTauHybridProducer [14_0_X]

### PR DESCRIPTION
**Pull request by mbluj**
#### PR description:

This PR contains an update to `PATTauHybridProducer` to reduce complexity of erasing elements from vectors by using `std::remove_if` instead of looping over elements of the vectors. Originally proposed in https://github.com/cms-sw/cmssw/pull/44067#issuecomment-1964349862.
It is a technical improvement not affecting physics.

Backport of  #44266 to CMSSW 14_0 series.

#### PR validation:

Tested in the context of original CMSSW.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport to 14_0 for 2024 Nano production.

### CODE REVIEW

**Comment by vlimant** [comment]
enable nano

**Comment by mbluj** [comment]
> spurious difference in nano ; what's the reason again ?

I think, it should not be related to this technical PR.

**Comment by vlimant** [comment]
+1
we will need a renewed understanding of why the tau reconstruction is not deterministic #44309

**Comment by mandrenguyen** [comment]
+1

**Comment by rappoccio** [comment]
+1

**Pull request merged**
