### PR TITLE
Add the HGCAL-Seeded ElectronSeed collection to the FEVT and RECO event contents. [93X]

### PR DESCRIPTION
**Pull request by kpedro88**
Backport of #20368

### CODE REVIEW

**Comment by kpedro88** [comment]
please test

**Comment by kpedro88** [comment]
assign upgrade

**Comment by kpedro88** [comment]
+1

**Comment by perrotta** [comment]
#20368 is already included in the latest 93X IB (CMSSW_9_3_X_2017-09-06-2300); therefore this backport can be closed.

**Comment by slava77** [comment]
> #20368 is already included in the latest 93X

that PR is also in CMSSW_9_4_X_2017-09-06-2300
@smuzaffar @davidlange6 
Was it an intended behavior for just one IB, or will it continue for more?

**Comment by smuzaffar** [comment]
@slava77 , @perrotta  #20368 is only in 94X. Looks like there is bug in the script which generate the IB pages that is why it is showing that #20368 is psrt of 93X. I will check this tomorrow.

**Comment by slava77** [comment]
https://github.com/cms-sw/cmssw/compare/CMSSW_9_3_X_2017-09-06-1100...CMSSW_9_3_X_2017-09-06-2300
shows that  #20368 is in CMSSW_9_3_X_2017-09-06-2300.
So, I don't think it's the showIB to blame.

**Comment by smuzaffar** [comment]
but I do not see the changes here in https://github.com/cms-sw/cmssw/commits/CMSSW_9_3_X/TrackingTools/Configuration/python/TrackingTools_EventContent_cff.py.

Ah my bad, 93X is still using master branch to tag. I am fixing it and re-building 93X IB now.

**Comment by kpedro88** [comment]
@smuzaffar does this mean this PR should be closed or not? What about #20408?

**Comment by smuzaffar** [comment]
@kpedro88 , no both of these should remain open if they are meant for 93X (they are not in 93X yet). I will check if I can fix showIB to ignore 93X 06-1100 and 06-2300 IBs to get the correct PRs list which went in to 93X

**Comment by perrotta** [comment]
+1
Identical to #20368, merged in 93X

**Comment by davidlange6** [comment]
+1

**Pull request merged**
