### PR TITLE
cleaning RunTheMatrix (dedicated python file for the upgrade workflows definition)

### PR DESCRIPTION
**Pull request by boudoul**
Following a suggestion from @davidlange6 , I created a separated file (upgradeWorkflowComponents.py) which does contain the definition and the components  of the upgrade workflows - I didn't change anything neither in the numbering nor the definitions (just moved what was in relval_steps into upgradeWorkflowComponents.py and import it) .
This will definitely make relval_steps a bit lighter, and will facilitate the introduction of the upgrade worflows in the 7X version  of runthematrix (once we will be ready to do so) without having to deal with a giant relval_steps.py

### CODE REVIEW

**Comment by degano** [comment]
@cmsbuild please test

**Comment by franzoni** [comment]
Hello Gaelle @boudoul , is this PR superseded by #7313 ?

**Comment by boudoul** [comment]
hi Giovanni @franzoni , I completely missed your comment, sorry for the delay - 
No this PR is NOT superseded by #7313 - This PR is for 62XSLHC, (#7313 was for 74X) -

**Comment by mark-grimes** [comment]
merge

Github is saying there are conflicts but I can successfully merge locally onto the head, see if this goes through.  I tried rerunning a few matrix tests just in case but they seem fine.

**Comment by mark-grimes** [comment]
@boudoul, could you close this?  Changes have been integrated with #7554.

**Comment by boudoul** [comment]
ah yes, closing now

**Pull request closed without merging**
