### PR TITLE
Run2-hcx151 Correct for geometry access for Hcal

### PR DESCRIPTION
**Pull request by bsunanda**
Access to getPosition for Hcal is better done from HcalGeometry rather than CaloCellGeometry

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@ssekmen, @civanch, @mdhildreth, @lveldere Could you review this PR and approve

**Comment by civanch** [comment]
+1
mainly code check modifications - the improvement itself is in 2 lines only, seems to be safe.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
