### PR TITLE
[NanoAOD, JMENanoAOD] Backport of #33824 (Remove jercVars variables, update puId config) to 10_6_X

### PR DESCRIPTION
**Pull request by nurfikri89**
Backport from #33824

#### PR description:

This PR aims to 

- Remove certain jercVars variables from the main NanoAOD but still keep them in the JMENano.
- Update configurations for pileup Id in JMENano.

With this PR, the event size for the main Nano is reduced  from **2.90 kb/event** to **2.86 kb/event**.  The comparison was made using 5K events from a TTJets RunIISummer20UL17MiniAODv2 sample. No event size changes for JMENano.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:
Original PR is #33824

### CODE REVIEW

**Comment by mariadalfonso** [comment]
@nurfikri89 
you need to add back the deleted variable to make the nanoV8 identical to before
using this `(run2_nanoAOD_106Xv1 & ~run2_nanoAOD_devel)`

**Comment by mariadalfonso** [comment]
please test

**Comment by mariadalfonso** [comment]
backport of #33824

**Comment by mariadalfonso** [comment]
+xpog

changes inline with master; v8 nano protected

**Comment by qliphy** [comment]
+1

**Pull request merged**
