### PR TITLE
Foward-port L1T algorithms (l1t-tsg-v3) to 81X.

### PR DESCRIPTION
**Pull request by mulhearn**
Do not merge.

This PR is a placeholder for now.  This is the complete set of changes that currently allow me to bitwise reproduce the results of l1t-tsg-v3 under 801.  It includes a revert of the HF TP scale change and a local copy of an HF TP conditions from pre6 into 801.  Obviously we don't want either of these, but I wanted to start from something bitwise equivalent, so that we are certain any changes in final version of PR are due to TP updates only.

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
Could we get a 80X PR as well?
Thanks!

**Comment by mulhearn** [comment]
Yes, but I would like to sort out the issue with HF TPs first, or do you need an 80X version for e.g. your own testing?

**Comment by Martin-Grunewald** [comment]
Just asking - in the TSG meeting it was stated that you provide all PRs by Monday :)

**Comment by mulhearn** [comment]
This is working now.  Proper PR soon.

**Pull request closed without merging**
