### PR TITLE
HLT BPTX added

### PR DESCRIPTION
**Pull request by KiSooLee**
HLT_HIL2Mu3BPTX, HLT_HIL3Mu3BPTX, HLT_HIL1DoubleMu0BPTX, HLT_HIL2DoubleMu0BPTX added

### CODE REVIEW

**Comment by KiSooLee** [comment]
This branch is almost same with base branch.
But previously there were some unnecessary files.
According to https://github.com/cms-sw/cmssw/pull/10813/files
HLT_User_cff.py
HLTrigger/Configuration/python/HLT_User_cff.py
Are unnecessary file.
So I want to merge without these two files.

**Comment by degano** [comment]
@cmsbuild please test

**Comment by deguio** [comment]
+1
it seems to me that these changes are present in 76 and 75 already.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
