### PR TITLE
Add back SMatrixNoInit

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
I first want to see Danilo's new version in before merging this.

**Comment by ktf** [comment]
@VinInn @wmtan @davidlange6

**Comment by ktf** [comment]
Requires cms-sw/cmsdist#1435

**Comment by wmtan** [comment]
If I do a "git grep -w SMatrixNoInit" in 7_5_X, I see that it is used in 12 files.  This PR touches only three of them.  What happened to the changes in the other 9 files?

**Comment by ktf** [comment]
I'm probably missing a separate commit. Will look for this.

**Comment by ktf** [comment]
It should now have all the `SMatrixNoInit` back once we get an IB with Vincenzo / Danilo patch in I'll check it compiles and merge.

**Comment by slava77** [comment]
is this really ROOT6 specific or is it an improvement just happened to be tested out of mainstream?

**Comment by davidlange6** [comment]
the smatrix work is already in the root5 branch.

**Comment by slava77** [comment]
ah, indeed, as of #3663 a year ago; it was the root6 issue that we had to go back in #4066 in root6 branch

**Comment by ktf** [comment]
New root is in place. Merging this.

**Pull request merged**
