### PR TITLE
 Backport to 13_1_X of #41275 Introduce (Robust)ParTAK4 jet tagger, DeepJet model update for Run 3, remove DeepCSV from nano

### PR DESCRIPTION
**Pull request by AlexDeMoor**
#### PR description:

See description of https://github.com/cms-sw/cmssw/pull/41275 - new tagger for Run 3 for MiniAOD and NanoAOD, update of DeepJet for Run 3, and removing outdated DeepCSV for Run 3.
Additions are verbatim copies of original PR, modifications have been updated to be in line with latest PNet additions into the same packages.

Collaboration with @AnnikaStein 

#### PR validation:

Compilation, basic checks similar to original PR.

`scram b runtests
scram build code-checks
scram build code-format
scram build updateclassversion`

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport of https://github.com/cms-sw/cmssw/pull/41275

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by simonepigazzini** [comment]
the tests probably started before the cms-data PR became fully integrated. Trying again the same config.

**Comment by simonepigazzini** [comment]
enable nano

**Comment by perrotta** [comment]
test parameters:
- pull_request = cms-sw/cmsdist#8495

**Comment by perrotta** [comment]
backport of https://github.com/cms-sw/cmssw/pull/41275

**Comment by perrotta** [comment]
please abort

**Comment by perrotta** [comment]
please test
(To be sure that it picks the correct cmsdist PR: maybe I was too fast before...)

**Comment by AnnikaStein** [comment]
Could the tests be restarted (with the usual test parameters)? If it's a timeout only, maybe next run on another machine we are lucky and it works just fine.

**Comment by simonepigazzini** [comment]
please test

**Comment by simonepigazzini** [comment]
let's see. Anyway I think we can be happy given that the changes to NANO are identical to the original PR.
@AnnikaStein can you please confirm that the changes in the DAQ for NANO are as expected?

**Comment by AnnikaStein** [comment]
> let's see. Anyway I think we can be happy given that the changes to NANO are identical to the original PR. @AnnikaStein can you please confirm that the changes in the DAQ for NANO are as expected?

@simonepigazzini looking alright, RobustParTAK4 got added for the Run 2 workflows 2500.31 -- 332 (based on the modifier), and the plots for 12.2, 12.4, 12.6 (2500.401 -- 601) exist but are filled with -1 only, as the mini is not rerun again - so these results are all expected, similar to what we had for the other PRs.

btagCMVA is gone from the plots (was empty anyway), DeepCSV which used to be filled in the DQM is now also gone for Run 3

**Comment by simonepigazzini** [comment]
+1

**Comment by clacaputo** [comment]
+reconstruction

**Comment by rappoccio** [comment]
+1

**Pull request merged**
