### PR TITLE
[10.2.X] fix of IB test failures by updating the prompt GT

### PR DESCRIPTION
**Pull request by arunhep**
this is the fix for the problems mentioned here : https://github.com/cms-sw/cmssw/issues/22865#issuecomment-379442549
@fabiocos i will open a similar one for 10.1.X
I dont have write access to PR opened by @lpernie but may be you could merge the PR to be opened by me in 10.1.X along with #22834

### CODE REVIEW

**Comment by arunhep** [comment]
please test workflow 136.77,136.778

**Comment by fabiocos** [comment]
@arunhep thanks, the failing workflows are now completing correctly, if the comparison is ok we should integrate this fix by this evening

**Comment by fabiocos** [comment]
@arunhep @lpernie could you please sign the PR in case? I will merge it for tonight's IB

**Comment by arunhep** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
