### PR TITLE
fix alignment validation plotting macro

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

Trivial  bug-fix of off-by-one issue introduced in PR https://github.com/cms-sw/cmssw/pull/27984/

#### PR validation:

Plotting of alignment PV Validation now works.

#### if this PR is a backport please specify the original PR:

NA
cc: 
@adewit @connorpa

### CODE REVIEW

**Comment by mmusich** [comment]
type bug-fix

**Comment by tlampen** [comment]
please test

**Comment by tlampen** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
