### PR TITLE
[`Alignment/OfflineValidation`] restructure the primary-vertex related unit tests

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

In (partial) response of the https://github.com/cms-sw/cmssw/pull/40567#issuecomment-1402055015:
   * further lowering down the amount of event used in the phase-2 flavor of unit test (from 100 to 10)
   * merge phase-1 and phase-2 test configurations in the same file
   * rename the unit test to be more descriptive

#### PR validation:

Run successfully `scram b runtests_PrimaryVertex`

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

N/A

### CODE REVIEW

**Comment by smuzaffar** [comment]
thanks @mmusich for looking in to it. We also noticed that test was reading a 90GB large file (root://eoscms.cern.ch//eos/cms/store/user/cmsbuild/store/relval/CMSSW_12_5_3/RelValMinBias_14TeV/GEN-SIM-RECO/125X_mcRun4_realistic_v5_2026D88PU-v1/2590000/22e22ae6-a353-4f2e-815e-cc5efee37af9.root ) and job just hands after printing 
```
Begin processing the 1st record. Run 1, Event 6602, LumiSection 67 on stream 1 at 25-Jan-2023 16:38:50.763 CET
```
I guess it is waiting for input file to be available and then we get message like
```
[2023-01-25 15:50:00.751186 +0100][Error  ][PostMaster        ] [eoscms.cern.ch:1094] Forcing error on disconnect: [ERROR] Operation interrupted.
```
could this large file be the issue here?

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
> could this large file be the issue here?

I am not sure in what sense the size the can be an issue here, excepted that since this is a PU=200 MC sample the computation will be on the heavy side. On the other hand I am planning to move to a (lighter) ALCARECO sample, once that's available (should be for the next pre-release, as it needs  https://github.com/cms-sw/cmssw/pull/40548 to be processed correctly)

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
@smuzaffar 

to test one of the non-AMD archs would this:

>  please test for el8_ppc64le_gcc11

work out of the box?

**Comment by mmusich** [comment]
@cmsbuild, please test for el8_ppc64le_gcc11

**Comment by mmusich** [comment]
unit tests did run correctly now also for `el8_ppc64le_gcc11`, which is recently [failing in IBs](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_ppc64le_gcc11/CMSSW_13_0_X_2023-01-25-2300/unitTestLogs/Alignment/OfflineValidation#/1930-1930)  see [log for the last round of PR tests](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-8d946a/30187/unitTests/src/Alignment/OfflineValidation/test/PrimaryVertex/testing.log).
Given - in addition - the positive outcome of the [regular round of tests](https://github.com/cms-sw/cmssw/pull/40612#issuecomment-1404834725) @cms-sw/alca-l2 feel free to sign.

**Comment by smuzaffar** [comment]
please test for el8_aarch64_gcc11

lets tests it for aarch64 too

**Comment by tvami** [comment]
I see
 > cms/40612/el8_aarch64_gcc11/unittest — Some unit tests were failed.

with " [ERROR] Operation interrupted."

maybe no point in running the relvals for `el8_aarch64_gcc11` ?

**Comment by mmusich** [comment]
the failure [for el8_aarch64_gcc11](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-8d946a/30189/unitTests/src/Alignment/OfflineValidation/test/Miscellanea/testing.log) happens in a different test than the one failing in IBs and look related to eos issues, so conclusions at https://github.com/cms-sw/cmssw/pull/40612#issuecomment-1404913270 still hold.

**Comment by smuzaffar** [comment]
for `aarch64` [test failed](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-8d946a/30189/unitTests/src/Alignment/OfflineValidation/test/Miscellanea/testing.log) as it was killed after 1h of runtime . ` [ERROR] Operation interrupted.` is just a side effect of killing the process. We ran this test on one of our arm node and it took 3 hours.

**Comment by mmusich** [comment]
> We ran this test on one of our arm node and it took 3 hours.

though there is plenty of xrootd warnings:
```
[2023-01-26 13:57:50.894487 +0100][Error  ][XRootD            ] [p06636710w24543.cern.ch:1095] Impossible to send message kXR_readv (handle: 0x00000000, chunks: [(offset: 36925710, size: 478547); (offset: 37449998, size: 339845); (offset: 37789843, size: 76581); (offset: 37867397, size: 447787); (offset: 38315184, size: 76501); (offset: 38391685, size: 416947); (offset: 38808632, size: 107341); (offset: 38915973, size: 2358); (offset: 38918331, size: 138181); (offset: 39824261, size: 10346); (offset: 39834607, size: 136424); (offset: 40034694, size: 395852); (offset: 40430546, size: 128436); (offset: 40558982, size: 503794); (offset: 41062776, size: 20494); (offset: 41083270, size: 13776); (offset: 42592945, size: 122); (offset: 42750865, size: 33221); (offset: 44671144, size: 1748); (offset: 44902500, size: 367); (offset: 45014557, size: 2100); ], total size: 3330768). Trying to recover.
[2023-01-26 13:57:50.894932 +0100][Error  ][XRootD            ] [p06636710w24543.cern.ch:1095] Unable to get the response to request kXR_readv (handle: 0x00000000, chunks: [(offset: 36925710, size: 478547); (offset: 37449998, size: 339845); (offset: 37789843, size: 76581); (offset: 37867397, size: 447787); (offset: 38315184, size: 76501); (offset: 38391685, size: 416947); (offset: 38808632, size: 107341); (offset: 38915973, size: 2358); (offset: 38918331, size: 138181); (offset: 39824261, size: 10346); (offset: 39834607, size: 136424); (offset: 40034694, size: 395852); (offset: 40430546, size: 128436); (offset: 40558982, size: 503794); (offset: 41062776, size: 20494); (offset: 41083270, size: 13776); (offset: 42592945, size: 122); (offset: 42750865, size: 33221); (offset: 44671144, size: 1748); (offset: 44902500, size: 367); (offset: 45014557, size: 2100); ], total size: 3330768)
[2023-01-26 14:18:05.451594 +0100][Error  ][PostMaster        ] [eoscms.cern.ch:1094] Forcing error on disconnect: [ERROR] Operation interrupted.
```

**Comment by smuzaffar** [comment]
@mmusich , note that we do run a lot of tests (unit tests, add-on and relvals) on these arm nodes and we have not seen many issues with xrootd reading input data from eos. As I mentioned earlier, this test is ready a 80GB file using xrootd from eos. Can we try using a smaller size file and see how it goes?

**Comment by smuzaffar** [comment]
@mmusich , I do not think that reducing the number of events is going to solve the issue here. Job was processing/waiting for first event ([see log](Begin processing the 1st record. Run 1, Event 6002, LumiSection 61 on stream 0 at 26-Jan-2023 13:47:20.547 CET) ) and then it was killed

**Comment by mmusich** [comment]
@smuzaffar 

> As I mentioned earlier, this test is ready a 80GB file using xrootd from eos. Can we try using a smaller size file and see how it goes?

uh?!?

```
$ eos ls -lh /eos/cms/store/user/cmsbuild/store/relval/CMSSW_12_5_0_pre5/RelValTTbar_14TeV/GEN-SIM-RECO/PU_125X_mcRun3_2022_realistic_v3-v1/10000/0136c33f-3ff9-4602-8578-906ae6e0160b.root
-rw-r--r--   2 cmsbuild zh             4.56 G Jan 26 11:42 0136c33f-3ff9-4602-8578-906ae6e0160b.root
```

**Comment by smuzaffar** [comment]
ah ok, I thought test was still using [a].

[a]
```
[muzaffar@lxplus768 ~]$ ls -lh /eos/cms/store/user/cmsbuild/store/relval/CMSSW_12_5_3/RelValMinBias_14TeV/GEN-SIM-RECO/125X_mcRun4_realistic_v5_2026D88PU-v1/2590000/22e22ae6-a353-4f2e-815e-cc5efee37af9.root 
-rw-r--r--. 1 cmsbuild zh 91G Jan 26 11:42 /eos/cms/store/user/cmsbuild/store/relval/CMSSW_12_5_3/RelValMinBias_14TeV/GEN-SIM-RECO/125X_mcRun4_realistic_v5_2026D88PU-v1/2590000/22e22ae6-a353-4f2e-815e-cc5efee37af9.root
```

**Comment by mmusich** [comment]
> ah ok, I thought test was still using [a].

yes, it's still using that, but it's another test (the one that now doesn't fail anymore)

**Comment by mmusich** [comment]
@cmsbuild, please test for el8_aarch64_gcc11

in the last push I reduced the input file size also for the phase-2 test:
```
$ eos ls -lh /store/relval/CMSSW_12_6_0_pre5/RelValTTbar_14TeV/GEN-SIM-RECO/125X_mcRun4_realistic_v5_2026D88noPU-v1/2590000/57cbe250-487d-4a47-998b-48f9028a0058.root
-rw-r--r--   2 cmsprd   zh             5.94 G Dec  5 21:37 57cbe250-487d-4a47-998b-48f9028a0058.root
```

lets' see how it goes

**Comment by tvami** [comment]
+alca
 * tests pass for `el8_aarch64_gcc11` as well now

**Comment by smuzaffar** [comment]
thanks a lot @mmusich. Indeed tests look good now. Test were run on the slowest arm node and finished with in time limits.

**Comment by perrotta** [comment]
+1

**Pull request merged**
