### PR TITLE
remove a bunch of unneeded Pythia6 configs

### PR DESCRIPTION
**Pull request by kpedro88**
@davidlange6 @hengne requested followup to #16535. I went through and found all the Pythia6 configs in `Configuration/Generator` that had obvious Pythia8 counterparts (identical filenames except with either "TuneCUETP8M1" or "pythia8" in the newer version). I also checked that none of the removed files are used anywhere in `Configuration/PyReleaseValidation`.

There are still a number of configs that don't have any Pythia8 counterpart. If PDMV wants to move all of those to Pythia8 as well, probably better to appoint someone to do it...

### CODE REVIEW

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by kpedro88** [comment]
The AddOn test failure demonstrates that some of these configs might be used outside of relvals, so I checked for any usage of each file and updated that usage to the pythia8 version.

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by dmitrijus** [comment]
+1

**Comment by perrozzi** [comment]
+1

**Comment by Martin-Grunewald** [comment]
+1

**Pull request merged**
