### PR TITLE
Run4-gem63B Add 2 useful scripts to test dd4hep for Phase2

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Add 2 useful scripts to test dd4hep for Phase2

#### PR validation:

These scripts are used in debugging usage of dd4hep for Phase2 geometries

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
