### PR TITLE
A backport of the fix on issue #38044 to 12_4_X

### PR DESCRIPTION
**Pull request by quark2**
#### PR description:
This PR fixes issue #38044. The issue has been fixed, replacing part of calculations with a massive loop by lighter codes.

It is also a backport of #38101 to CMSSW_12_4_X.

#### PR validation:
Test are done and one can check again by `runTheMatrix` workflows

@jshlee @watson-ij

### CODE REVIEW

**Comment by emanueleusai** [comment]
please test

**Comment by emanueleusai** [comment]
+1

**Comment by qliphy** [comment]
please abort 
some jobs are stuck

**Comment by qliphy** [comment]
please test

**Comment by qliphy** [comment]
+1

**Pull request merged**
