### PR TITLE
Run3-gex110X Take care of Carl's comment for PR #36648

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Take care of Carl's comment for PR #36648. The comment is to move the file "pixfwd.xml" in something like "data/pixfwd/2021/v1/pixfwd.xml" which is done here.

#### PR validation:

Tested using workflows in the directory Geometry/ForwardCommonData/test

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

Carl comment is implemented

**Comment by qliphy** [comment]
+1

**Comment by tvami** [comment]
Hi @bsunanda does this need to be backported to 12_2_X? (Sorry if it was, I didnt see the link to this PR)

**Comment by bsunanda** [comment]
This PR is backported and is apart of #36740 and is now documented in its history
________________________________

**Comment by perrotta** [comment]
> This PR is backported and is apart of #36740 and is now documented in its history
>

I'm sorry @bsunanda , but none of the files modified here or in #36648 is included in the backport PR #36740
Could you please check, and provide the necessary amendments if needed?

**Pull request merged**
