### PR TITLE
[PPS] Systematic use of emplace_back

### PR DESCRIPTION
**Pull request by forthommel**
#### PR description:

This PR drops unnecessary constructor+copy operations for several producer plugins within the "PPS space". All thanks to the `emplace_back` method introduced in #26069 for `edm::DetSet<T>` containers.

#### PR validation:

Code compiles, plugins run.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

Before submitting your pull requests, make sure you followed this checklist:
- [x] verify that the PR is really intended for the chosen branch
- [x] verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- [x] verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by perrotta** [comment]
+1
- Technical
- Jenkins tests pass

**Comment by christopheralanwest** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
