### PR TITLE
add PV monitoring @HLT

### PR DESCRIPTION
**Pull request by mtosi**
forward port of PR [#17667](https://github.com/cms-sw/cmssw/pull/17667)
and
fix of PR [#17693](https://github.com/cms-sw/cmssw/pull/17693), which have some issues w/ merging

### CODE REVIEW

**Comment by silviodonato** [comment]
please test

**Comment by silviodonato** [comment]
+1

**Comment by perrotta** [comment]
+1
(Mostly DQM, it only touches Reco through Validation)

**Comment by fabozzi** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by dmitrijus** [comment]
+1

**Comment by Martin-Grunewald** [comment]
Looks like this PR creates problems:

```
%MSG-w PrimaryVertexAnalyzer4PUSlimmed:   PrimaryVertexAnalyzer4PUSlimmed:hltPi\
xelPVanalysis 22-Mar-2017 08:08:21 CET  Run: 1 Event: 101
Skipping vertex collection: hltPixelVertices since it is missing.
%MSG
%MSG-w PrimaryVertexAnalyzer4PUSlimmed:   PrimaryVertexAnalyzer4PUSlimmed:hltPi\
xelPVanalysis 22-Mar-2017 08:08:21 CET  Run: 1 Event: 101
Skipping vertex collection: hltTrimmedPixelVertices since it is missing.
%MSG
----- Begin Fatal Exception 22-Mar-2017 08:08:21 CET-----------------------
An exception of category 'ProductNotFound' occurred while
   [0] Processing Event run: 1 lumi: 3 event: 101
   [1] Running path 'prevalidation_step'
   [2] Prefetching for module PrimaryVertexAnalyzer4PUSlimmed/'hltPVanalysis'
   [3] Calling method for module VertexAssociatorByPositionAndTracksProducer/'v\
ertexAssociatorByPositionAndTracks4pixelTracks'
Exception Message:
Principal::getByToken: Found zero products matching all criteria
Looking for type: edm::AssociationMap<edm::OneToManyWithQualityGeneric<std::vec\
tor<TrackingParticle>,edm::View<reco::Track>,double,unsigned int,edm::RefProd<s\
td::vector<TrackingParticle> >,edm::RefToBaseProd<reco::Track>,edm::Ref<std::ve\
ctor<TrackingParticle>,TrackingParticle,edm::refhelper::FindUsingAdvance<std::v\
ector<TrackingParticle>,TrackingParticle> >,edm::RefToBase<reco::Track> > >
Looking for module label: tpToHLTpixelTrackAssociation
Looking for productInstanceName:

   Additional Info:
      [a] If you wish to continue processing events after a ProductNotFound exc\
eption,
add "SkipEvent = cms.untracked.vstring('ProductNotFound')" to the "options" PSe\
t in the configuration.

----- End Fatal Exception -------------------------------------------------
```

**Comment by Martin-Grunewald** [comment]
Or this one:

```
----- Begin Fatal Exception 22-Mar-2017 08:16:50 CET-----------------------
An exception of category 'ProductNotFound' occurred while
   [0] Processing Event run: 1 lumi: 3 event: 103
   [1] Running path 'dqmofflineOnPAT_step'
   [2] Calling method for module PrimaryVertexMonitor/'hltVerticesPFFilterMonit\
oring'
Exception Message:
Principal::getByToken: Found zero products matching all criteria
Looking for type: std::vector<reco::Vertex>
Looking for module label: hltVerticesPFFilter
Looking for productInstanceName:

   Additional Info:
      [a] If you wish to continue processing events after a ProductNotFound exc\
eption,
add "SkipEvent = cms.untracked.vstring('ProductNotFound')" to the "options" PSe\
t in the configuration.

----- End Fatal Exception -------------------------------------------------
----- Begin Fatal Exception 22-Mar-2017 08:16:50 CET-----------------------
An exception of category 'ProductNotFound' occurred while
   [0] Processing Event run: 1 lumi: 3 event: 102
   [1] Running path 'dqmofflineOnPAT_step'
   [2] Calling method for module PrimaryVertexMonitor/'hltVerticesPFFilterMonit\
oring'
Exception Message:
Principal::getByToken: Found zero products matching all criteria
Looking for type: std::vector<reco::Vertex>
Looking for module label: hltVerticesPFFilter
Looking for productInstanceName:

   Additional Info:
      [a] If you wish to continue processing events after a ProductNotFound exc\
eption,
add "SkipEvent = cms.untracked.vstring('ProductNotFound')" to the "options" PSe\
t in the configuration.
```

**Comment by Martin-Grunewald** [comment]
It affects PRef and PIon HLT menus, which probably do not contain the module.
But as always, subsequent modules should NOT CRASH when the input collection is missing!

**Comment by davidlange6** [comment]
yes, I was just seeing the same thing - will revert for now while this can be fixed.

**Comment by mtosi** [comment]
opsi
can you please point me to the workflows which show these issues, please ?
I thought I had fixed them, but ....
thanks !

**Comment by davidlange6** [comment]
https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc6_amd64_gcc630/CMSSW_9_1_X_2017-03-21-2300/pyRelValMatrixLogs/run/134.805_RunMET2015C+RunMET2015C+HLTDR2_25ns+RECODR2_25nsreHLT_HIPM+HARVESTDR2/step3_RunMET2015C+RunMET2015C+HLTDR2_25ns+RECODR2_25nsreHLT_HIPM+HARVESTDR2.log

**Comment by mtosi** [comment]
I'm confused :(
I ran 
`runTheMatrix.py -l 134.805 &`
and I have 
```
134.805_RunMET2015C+RunMET2015C+HLTDR2_25ns+RECODR2_25nsreHLT_HIPM+HARVESTDR2 Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED  - time date Wed Mar 22 13:28:42 2017-date Wed Mar 22 13:05:20 2017; exit: 0 0 0 0
1 1 1 1 tests passed, 0 0 0 0 failed
```

I'm in the branch 
```
git branch
  CMSSW_9_1_X
  backport-attempt
  backport-from-CMSSW_9_0_X
  from-CMSSW_9_1_X_2017-03-20-1100
* pvMonitoring@HLT_91x
```

under
```
echo $CMSSW_BASE/
/afs/cern.ch/work/t/tosi/public/trackingHLT/DQM/cleanAREA/CMSSW_9_1_X_2017-03-20-1100/
```

**Comment by davidlange6** [comment]
maybe your branch is not in a consistent state? You can try 

CMSSW_9_1_X_2017-03-21-2300 (not working in our tests, your PR in)
CMSSW_9_1_X_2017-03-22-1100 (working in our tests, your PR out)

**Comment by Dr15Jones** [comment]
@wddgit  Could be an interaction with the Task pull request.

**Comment by davidlange6** [comment]
it didn't seem likely to me. but maybe you can confirm if there is a potential conflict

**Comment by wddgit** [comment]
Just quickly skimming this PR, I cannot see anything I would expect to interact badly with the Tasks PR. At this point, I think the Tasks PR is unrelated to these failures. If you find more evidence pointing in that direction, ask and I will take a closer look.

This problem did start at the same point in time and the Tasks PR modifies a lot of the code that processes the python configurations so it reasonable to suspect it. On the hand, the Tasks PR mostly effects which modules are configured to run in unscheduled mode. It should not affect things that are put on Paths or EndPaths and it looks like the content in this PR is all on Paths or EndPaths.

**Comment by mtosi** [comment]
I've just done
```
cmsrel CMSSW_9_1_X_2017-03-22-1100
cd CMSSW_9_1_X_2017-03-22-1100/src/
cmsenv
git cms-merge-topic 17996
```
but I get
You are on branch from-CMSSW_9_1_X_2017-03-22-1100
From .
 * [new ref]                    -> merge-attempt
From https://github.com/cms-sw/cmssw
 * [new ref]         refs/pull/17996/head -> cms-sw/refs/pull/17996/head
Switched to branch 'merge-attempt'
Already up-to-date.
Switched to branch 'from-CMSSW_9_1_X_2017-03-22-1100'
Checking out these packages: 0

what should  I do ?
thanks

**Comment by Dr15Jones** [comment]
I think the problem you are encountering is the fact that the pull request was merged (and then reverted) and therefore git sees no reason to merge it again. Maybe it would be better to try to do a 'rebase' of your original branch onto the master branch

**Pull request merged**
