### PR TITLE
TriggerResultFilters: accept arbitrary Path names

### PR DESCRIPTION
**Pull request by fwyzard**
- accept arbitrary Path names
- rename the internal classes for consistency
- update test files for the new functionality
- prevent segfault if an L1 trigger is used in the expression without passing the L1 results collection

### CODE REVIEW

**Comment by fwyzard** [comment]
backport #7108 to 7.3.x

**Comment by Martin-Grunewald** [comment]
+1

**Comment by Martin-Grunewald** [comment]
please test

**Comment by davidlange6** [comment]
+1

**Pull request merged**
