### PR TITLE
Phase2-hgx3341I Final step to prepare the V18 version of HGCal geometry which allows non-ero cassette shifts

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Final step to prepare the V18 version of HGCal geometry which allows non-ero cassette shifts

#### PR validation:

Use the dump and overlap check scripts inside Geometry/HGCalCommonData

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

This PR is for new V18 HGCal. No change in current geometry/workflow.

**Comment by bsunanda** [comment]
@perrotta Please merge this PR before making pre3

**Comment by perrotta** [comment]
+1

**Pull request merged**
