### PR TITLE
Add record type HeavyIonRPRcd to 2021 HI global tag

### PR DESCRIPTION
**Pull request by christopheralanwest**
#### PR description:

This change really should have been included in PR #31645 but was inadvertently omitted. A tag corresponding to record type `HeavyIonRPRcd` is needed by the recently merged PR #31129 and its absence currently results in 2021 HI workflows 140.5611, 159.0, and 310.0 failing in the IB. The same tag that was added to the 2018 HI GT is added to the 2021 HI in this PR.

**2021 heavy ion**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_mcRun3_2021_realistic_HI_v11/112X_mcRun3_2021_realistic_HI_v12

Attn: @Martin-Grunewald @mandrenguyen @BetterWang 

#### PR validation:

Physics validation has been described in PR #31645. In addition, a technical test of the previously failing workflows has been performed:

`runTheMatrix.py -l 140.5611,159.0,310.0 --ibeos`

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

This PR is not a backport and should not be backported.

### CODE REVIEW

**Comment by mrodozov** [comment]
test_parameters:
- workflows=140.5611,150.0,159.0,159.1,159.2,159.3,159.4,310.0,311.0,312.0

**Comment by mrodozov** [comment]
please test

**Comment by christopheralanwest** [comment]
test parameters
workflows=140.5611,150.0,159.0,159.1,159.2,159.3,159.4,310.0,311.0,312.0

**Comment by christopheralanwest** [comment]
please test

**Comment by mandrenguyen** [comment]
140.5611 should be fixed by adding the relevant record to the data GT, as discussed in a private email thread.
150 should be fixed by the following change to Configuration/PyReleaseValidation/python/relval_steps.py
hiAlca2018 = {'--conditions':'auto:phase1_2018_realistic', '--era':'Run2_2018'}
-->
hiAlca2018 = {'--conditions':'auto:phase1_2018_realistic_hi', '--era':'Run2_2018'}

**Comment by mrodozov** [comment]
@mandrenguyen I can add the change you are suggesting for 150 and get the changes from this PR on top of it, what should be done for 140.5611 ? 
I'd like to put it together in another PR and merge it before the next IB because it's failing in many places and I'd like to fix it asap

**Comment by mandrenguyen** [comment]
@mrodozov The record 'HeavyIonRPRcd' has to be added to the data GT as well.  I think @BetterWang and/or @christopheralanwest should comment.

**Comment by christopheralanwest** [comment]
> @mrodozov The record 'HeavyIonRPRcd' has to be added to the data GT as well. I think @BetterWang and/or @christopheralanwest should comment.

Which tag of record type `HeavyIonRPRcd` should be added to the `auto:run2_data_promptlike_hi` GT?

**Comment by BetterWang** [comment]
> > @mrodozov The record 'HeavyIonRPRcd' has to be added to the data GT as well. I think @BetterWang and/or @christopheralanwest should comment.
> 
> Which tag of record type `HeavyIonRPRcd` should be added to the `auto:run2_data_promptlike_hi` GT?

Yes

**Comment by TabrisXiao** [comment]
Hi Chris, I confirm that the tag: HeavyIonRPRcd_PbPb2018_EventPlaneCalibration_data_offline_v2 is the correct one needed to be added. (https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/tags/HeavyIonRPRcd_PbPb2018_EventPlaneCalibration_data_offline_v2) I think I requested it before but it is still pending.

**Comment by christopheralanwest** [comment]
please test

**Comment by christopheralanwest** [comment]
The last commit addresses the issues described in the thread starting at https://github.com/cms-sw/cmssw/pull/31129#issuecomment-717253621.

**Comment by christopheralanwest** [comment]
+alca

**Comment by chayanit** [comment]
+1

**Comment by silviodonato** [comment]
merge
to fix the relvals in the morning IB
@kpedro88 let us know later if you have any comments

**Comment by kpedro88** [comment]
+upgrade

**Pull request merged**
