### PR TITLE
Switch resolution from Gaussian sigma to stdev for Phase2 L1T tracks

### PR DESCRIPTION
**Pull request by emacdonald16**
#### PR description:
Switched the track resolution plots to use standard deviation instead of Gaussian fit and sigma. This improves durability, in particular for cases where there are low statistics and poor fitting. This will change the resolution plots slightly, but will make it easier to spot problems or bugs. All other plots remain the same.

In addition, I cleaned up the code a tad, to make it more compact.

This is also a potential fix for Issue #31644 

#### PR validation:
Checked before and after comparisons of the resolution plots to make sure the change was reasonable and as expected, on a ttbar+200PU sample. 
Ran runTheMatrix for wf 23234.0
Ran code checks (scram build code-checks; scram build code-format)

#### if this PR is a backport please specify the original PR and why you need to backport that PR:
Not a backport

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
@emacdonald16 apart from changes in the invoved *Resolution MEs, I see changes in pTResVsEta* MEs
Are these expected too?
Thanks

**Comment by emacdonald16** [comment]
Yes, @jfernan2, these are expected. They are the pT resolution plots, and will change just from switching the definition of the resolution to be the standard deviation instead of a gaussian fit

**Comment by jfernan2** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
