### PR TITLE
move to pybind11 parameteset reader as default. fix some buildfiles

### PR DESCRIPTION
**Pull request by davidlange6**
#### PR description:

This exchanges the boost_python parameterset reader for one based on pybind11 for cmsRun and other users of FWCore/ParameterSetReader package.

A subsequent step will be to remove the boost_python version.

#### PR validation:

Similar implementation is running in DEVEL build (but this PR will be a better check of the output consistency). Unit tests of affected packages pass. runTheMatrix tests that i did were also ok.

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by Dr15Jones** [comment]
@davidlange6 the unit test failure does look related to the python change.

**Comment by davidlange6** [comment]
yes, it is.. i'm not sure why running the tests earlier did not catch this, but it does now..

**Comment by davidlange6** [comment]
It seems the pybind11 implementation is not fully getting cleaned up after something catches an exception (in this unit test the exception is supposed to happen..) For the moment, I'm moving the part of this unit test with an exception to the last part of the test - but I need to address the problem as a followup pr.

anyway, why does this come up now ? I had moved a few of the last unit tests still using boost in the devel branch to use pybind11... this was one of them.

**Comment by davidlange6** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by Dr15Jones** [comment]
@davidlange6 
> For the moment, I'm moving the part of this unit test with an exception to the last part of the test - but I need to address the problem as a followup pr.

Could you make an issue as a reminder? Or is your plan to have another PR very soon?

**Comment by davidlange6** [comment]
sure I will

now more importantly there are physics changes. So not good.

**Comment by davidlange6** [comment]
hold

**Comment by davidlange6** [comment]
unhold

sorry, I was confused. There is no problem with the results..

**Comment by fabiocos** [comment]
+1

**Pull request merged**
