### PR TITLE
Stop invalid LCTs from being produced. Fix the duplicated LCT issue. (Backport of #23769)

### PR DESCRIPTION
**Pull request by dildick**
@tahuang1991 @jiafulow FYI

### CODE REVIEW

**Comment by thomreis** [comment]
backport of #23769

**Comment by thomreis** [comment]
please test

**Comment by thomreis** [comment]
+1

**Comment by kpedro88** [comment]
@dildick can you make the PR title more informative?

**Comment by dildick** [comment]
@kpedro88 Done.

**Comment by kpedro88** [comment]
+upgrade

**Comment by dildick** [comment]
@fabiocos Can you this PR be integrated? Thank you.

**Comment by kpedro88** [comment]
@dildick it is on my list for the next 10_2 release

**Comment by kpedro88** [comment]
+1

**Pull request merged**
