### PR TITLE
Updated configurations in Geometry* to new MessageLogger syntax

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

All configurations in Geometry* subsystems which explicitly create a MessageLogger have been converted to the new syntax.
#### PR validation:

All files were passed to `python` and no failures as a result of these change were seen.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
please test

**Comment by kpedro88** [comment]
@bsunanda FYI

**Comment by kpedro88** [comment]
+upgrade

**Comment by civanch** [comment]
+1


better to integrate this asap

**Comment by qliphy** [comment]
+1

**Pull request merged**
