### PR TITLE
[12_4_X backport] Do NaN-check before accepting a PF candidate for computing photon's isolation

### PR DESCRIPTION
**Pull request by swagata87**
#### PR description:

This is a backport of https://github.com/cms-sw/cmssw/pull/39120. 
The need for backport to 12_4_X is explained in [original PR's description](https://github.com/cms-sw/cmssw/pull/39120#issue-1345133496) and [also here](https://github.com/cms-sw/cmssw/pull/39120#discussion_r953582553). To reiterate, photon's PF isolation is `nan` in some rare cases in Run3 data and MC. This PR fixes that. So it would be nice if 12_4_X MC production release has this fix in. This will also be useful for the rest of the prompt-reco data. 

Related github issue: https://github.com/cms-sw/cmssw/issues/39110

### CODE REVIEW

**Comment by swagata87** [comment]
backport of https://github.com/cms-sw/cmssw/pull/39120

**Comment by swagata87** [comment]
type egamma

**Comment by swagata87** [comment]
@cmsbuild please test

**Comment by jpata** [comment]
+reconstruction
- bugfix/mitigation for https://github.com/cms-sw/cmssw/issues/39110
- physics changes expected insofar as rare NaN values become non-NaN in photon iso (not visible in the tests)
- backport of https://github.com/cms-sw/cmssw/pull/39120

**Comment by jpata** [comment]
thank you @swagata87 for the quick action!

**Comment by swagata87** [comment]
> thank you @swagata87 for the quick action!

no problem, 
thank you for all the help and suggestions in the original PR to make the code more coherent and understandable.

**Comment by perrotta** [comment]
+1

**Pull request merged**
