### PR TITLE
Data vs emulator plots in CSC DQM [11_2_X]

### PR DESCRIPTION
**Pull request by dildick**
#### PR description:

With this PR we add histograms for CSC trigger primitives (ALCT, CLCT, LCT) data vs emulator comparisons. There are 1D histograms for each TP property and "data-emulator" plots - which ideally are empty. Backport needed for next MWGRs.

#### PR validation:

Code compiles.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Backport of https://github.com/cms-sw/cmssw/pull/33085

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by silviodonato** [comment]
Is it required for the MWGR?

**Comment by silviodonato** [comment]
> Backport needed for next MWGRs.

The answer was in the PR description

**Comment by jfernan2** [comment]
At least this comment of the master version of the PR still holds here too:
https://github.com/cms-sw/cmssw/pull/33085#issuecomment-795476862

**Comment by dildick** [comment]
Backported 4 commits from the 11_3_X PR.

**Comment by dildick** [comment]
@jfernan2 Can you run the tests, please?

**Comment by jfernan2** [comment]
please test

**Comment by dildick** [comment]
@jfernan2  

For these newly added WFs I need to insert the GEM pad producer and GEM pad cluster producer into the L1T sequence for DQM. That is until the GEM cluster unpackers become available. Once they are available in the unpacker sequence, I can take them out.

In any case, this can be fixed easily.

```
----- Begin Fatal Exception 26-Mar-2021 15:31:55 CET-----------------------
An exception of category 'ProductNotFound' occurred while
   [0] Processing  Event run: 337973 lumi: 289 event: 5152578 stream: 0
   [1] Running path 'dqmoffline_step'
   [2] Calling method for module CSCTriggerPrimitivesProducer/'valCscStage2Digis'
Exception Message:
Principal::getByToken: Found zero products matching all criteria
Looking for type: MuonDigiCollection<GEMDetId,GEMPadDigiCluster>
Looking for module label: simMuonGEMPadDigiClusters
Looking for productInstanceName: 

   Additional Info:
      [a] If you wish to continue processing events after a ProductNotFound exception,
add "SkipEvent = cms.untracked.vstring('ProductNotFound')" to the "options" PSet in the configuration.

----- End Fatal Exception -------------------------------------------------
```

**Comment by dildick** [comment]
Yep!
```
138.2_RunCosmics2020+RunCosmics2020+RECOCOSDEXPRUN3+ALCACOSDEXPRUN3+HARVESTDCEXPRUN3 Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED  - time date Fri Mar 26 13:01:54 2021-date Fri Mar 26 12:51:33 2021; exit: 0 0 0 0
1 1 1 1 tests passed, 0 0 0 0 failed
```

**Comment by jfernan2** [comment]
please test

**Comment by dildick** [comment]
@jfernan2 I had to separate the Run-2 from Run-3 for the Stage-2 L1T sequence in the DQM. After the last commit WF 1330.0 now runs (and so should other Run-2 WFs)
```
1330.0_ZMM_13+ZMM_13+DIGIUP15+RECOUP15_L1TMuDQM+HARVESTUP15_L1TMuDQM+NANOUP15 Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Sun Mar 28 20:49:07 2021-date Sun Mar 28 20:20:48 2021; exit: 0 0 0 0 0
1 1 1 1 1 tests passed, 0 0 0 0 0 failed
```

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
please test

**Comment by dildick** [comment]
So 11_3_X version is ok. The 11_2_X version crashes. Note that both have the exact same code. So somehow we're missing the unpacker `muonCSCDigis` in the 11_2_X version

**Comment by dildick** [comment]
@jfernan2 Could this be the problem: https://github.com/cms-sw/cmssw/blob/master/DQM/Integration/python/clients/l1tstage2emulator_dqm_sourceclient-live_cfg.py#L60?

**Comment by jfernan2** [comment]
> 
> 
> So 11_3_X version is ok. The 11_2_X version crashes. Note that both have the exact same code. So somehow we're missing the unpacker `muonCSCDigis` in the 11_2_X version

NO, I am not saying 11_3_X is OK. At Online DQM@P5 we can only test 11_2_X at this point. So, if both PRs are the same, I envisage the same crash

**Comment by jfernan2** [comment]
> 
> 
> @jfernan2 Could this be the problem: https://github.com/cms-sw/cmssw/blob/master/DQM/Integration/python/clients/l1tstage2emulator_dqm_sourceclient-live_cfg.py#L60?
> 
> or this https://github.com/cms-sw/cmssw/blob/master/DQM/Integration/python/clients/l1tstage2_dqm_sourceclient-live_cfg.py#L58?
> 
> The `l1tEmulatorMonitorPath` is crashing which is mentioned in the first configuration, so `l1tstage2emulator_dqm_sourceclient-live_cfg.py` is the one that needs to be fixed.

Indeed that client is the one crashing since those are the clients running at Online and that one contains the path l1tEmulatorMonitorPath

**Comment by dildick** [comment]
Ok. I'll fix it for 11_2 and 11_3

**Comment by jfernan2** [comment]
please test

**Comment by dildick** [comment]
Approximate backport of the 11_3_X version. GEM-CSC integrated local trigger switched off (since not yet at P5). I ran the integration test successfully. 
```
-bash-4.2$  cmsRun DQM/Integration/python/clients/l1tstage2emulator_dqm_sourceclient-live_cfg.py unitTest=True
Querying DAS for files...
the query is file run=334393 dataset=/ExpressCosmics/Commissioning2019-Express-v1/FEVT lumi=1
DAS succeeded after 1 attempts 0
found files:  ['/store/express/Commissioning2019/ExpressCosmics/FEVT/Express-v1/000/334/393/00000/D0F052ED-9CA5-F547-BA73-2AA370D51AE8.root']
edmFileUtil --catalog file:/cvmfs/cms-ib.cern.ch/SITECONF/local/PhEDEx/storage.xml?protocol=xrootd --events /store/express/Commissioning2019/ExpressCosmics/FEVT/Express-v1/000/334/393/00000/D0F052ED-9CA5-F547-BA73-2AA370D51AE8.root | tail -n +9 | head -n -5 | awk '{ print $3 }'
the query is file run=334393 dataset=/ExpressCosmics/Commissioning2019-Express-v1/FEVT lumi=2
DAS succeeded after 1 attempts 0
found files:  ['/store/express/Commissioning2019/ExpressCosmics/FEVT/Express-v1/000/334/393/00000/FE21789A-F777-0B43-A1F5-E43F1FD52D19.root']
edmFileUtil --catalog file:/cvmfs/cms-ib.cern.ch/SITECONF/local/PhEDEx/storage.xml?protocol=xrootd --events /store/express/Commissioning2019/ExpressCosmics/FEVT/Express-v1/000/334/393/00000/FE21789A-F777-0B43-A1F5-E43F1FD52D19.root | tail -n +9 | head -n -5 | awk '{ print $3 }'
Got 2 files.
Loaded configuration file from: []
dqmRunConfig: cms.PSet(
    collectorHost = cms.untracked.string('127.0.0.1'),
    collectorPort = cms.untracked.int32(9190),
    type = cms.untracked.string('userarea')
)
Monitoring file not found, disabling.
01-Apr-2021 20:33:03 CDT  Initiating request to open file root://cmsxrootd-site.fnal.gov//store/express/Commissioning2019/ExpressCosmics/FEVT/Express-v1/000/334/393/00000/D0F052ED-9CA5-F547-BA73-2AA370D51AE8.root
...
Begin processing the 200th record. Run 334393, Event 32986, LumiSection 2 on stream 0 at 01-Apr-2021 20:37:19.361 CDT
01-Apr-2021 20:37:19 CDT  Writing DQM Root file: ./upload/DQM_V0001_L1TEMU_R000334393.root
DQMFileSaver::globalEndRun()
01-Apr-2021 20:37:19 CDT  Closed file root://cmsxrootd.fnal.gov//store/express/Commissioning2019/ExpressCosmics/FEVT/Express-v1/000/334/393/00000/FE21789A-F777-0B43-A1F5-E43F1FD52D19.root
```

**Comment by dildick** [comment]
Output from `runTheMatrix.py -l limited`

```
4.22_RunCosmics2011A+RunCosmics2011A+RECOCOSD+ALCACOSD+SKIMCOSD+HARVESTDC Step0-DAS_ERROR Step1-NOTRUN Step2-NOTRUN Step3-NOTRUN Step4-NOTRUN  - time date Thu Apr  1 20:42:59 2021-date Thu Apr  1 20:42:00 2021; exit: 1 0 0 0 0
4.53_RunPhoton2012B+RunPhoton2012B+HLTD+RECODR1reHLT+HARVESTDR1reHLT Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED  - time date Thu Apr  1 21:01:50 2021-date Thu Apr  1 20:42:00 2021; exit: 0 0 0 0
5.1_TTbar+TTbarFS+HARVESTFS Step0-PASSED Step1-PASSED  - time date Thu Apr  1 20:50:32 2021-date Thu Apr  1 20:42:01 2021; exit: 0 0
7.3_CosmicsSPLoose_UP18+CosmicsSPLoose_UP18+DIGICOS_UP18+RECOCOS_UP18+ALCACOS_UP18+HARVESTCOS_UP18 Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Thu Apr  1 20:55:53 2021-date Thu Apr  1 20:42:01 2021; exit: 0 0 0 0 0
8.0_BeamHalo+BeamHalo+DIGICOS+RECOCOS+ALCABH+HARVESTCOS Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Thu Apr  1 20:55:35 2021-date Thu Apr  1 20:43:00 2021; exit: 0 0 0 0 0
9.0_Higgs200ChargedTaus+Higgs200ChargedTaus+DIGI+RECO+HARVEST Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED  - time date Thu Apr  1 21:02:17 2021-date Thu Apr  1 20:50:33 2021; exit: 0 0 0 0
25.0_TTbar+TTbar+DIGI+RECOAlCaCalo+HARVEST+ALCATT Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Thu Apr  1 21:10:07 2021-date Thu Apr  1 20:55:35 2021; exit: 0 0 0 0 0
135.4_ZEE_13+ZEEFS_13+HARVESTUP15FS+MINIAODMCUP15FS Step0-PASSED Step1-PASSED Step2-PASSED  - time date Thu Apr  1 21:05:28 2021-date Thu Apr  1 20:55:54 2021; exit: 0 0 0
136.731_RunSinglePh2016B+RunSinglePh2016B+HLTDR2_2016+RECODR2_2016reHLT_skimSinglePh_HIPM+HARVESTDR2 Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED  - time date Thu Apr  1 21:22:27 2021-date Thu Apr  1 21:01:51 2021; exit: 0 0 0 0
136.7611_RunJetHT2016E_reminiaod+RunJetHT2016E_reminiaod+REMINIAOD_data2016_HIPM+HARVESTDR2_REMINIAOD_data2016_HIPM Step0-PASSED Step1-PASSED Step2-PASSED  - time date Thu Apr  1 21:10:31 2021-date Thu Apr  1 21:02:18 2021; exit: 0 0 0
136.793_RunDoubleEG2017C+RunDoubleEG2017C+HLTDR2_2017+RECODR2_2017reHLT_skimDoubleEG_Prompt+HARVEST2017 Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED  - time date Thu Apr  1 21:32:03 2021-date Thu Apr  1 21:05:28 2021; exit: 0 0 0 0
136.8311_RunJetHT2017F_reminiaod+RunJetHT2017F_reminiaod+REMINIAOD_data2017+HARVEST2017_REMINIAOD_data2017 Step0-PASSED Step1-PASSED Step2-PASSED  - time date Thu Apr  1 21:17:07 2021-date Thu Apr  1 21:10:08 2021; exit: 0 0 0
136.8523_RunJetHT2018C_nanoULremini+RunJetHT2018C_nanoULremini+NANOEDM2018_106Xv2+HARVESTNANOAOD2018_106Xv2 Step0-PASSED Step1-PASSED Step2-PASSED  - time date Thu Apr  1 21:19:35 2021-date Thu Apr  1 21:10:31 2021; exit: 0 0 0
136.874_RunEGamma2018C+RunEGamma2018C+HLTDR2_2018+RECODR2_2018reHLT_skimEGamma_Offline_L1TEgDQM+HARVEST2018_L1TEgDQM Step0-PASSED Step1-FAILED Step2-NOTRUN Step3-NOTRUN  - time date Thu Apr  1 21:22:21 2021-date Thu Apr  1 21:17:07 2021; exit: 0 21504 0 0
136.88811_RunJetHT2018D_reminiaodUL+RunJetHT2018D_reminiaodUL+REMINIAOD_data2018UL+HARVEST2018_REMINIAOD_data2018UL Step0-PASSED Step1-FAILED Step2-NOTRUN  - time date Thu Apr  1 21:25:27 2021-date Thu Apr  1 21:19:36 2021; exit: 0 21504 0
140.53_RunHI2011+RunHI2011+RECOHID11+HARVESTDHI Step0-PASSED Step1-PASSED Step2-PASSED  - time date Thu Apr  1 21:33:25 2021-date Thu Apr  1 21:22:22 2021; exit: 0 0 0
140.56_RunHI2018+RunHI2018+RECOHID18+HARVESTDHI18 Step0-PASSED Step1-FAILED Step2-NOTRUN  - time date Thu Apr  1 21:28:36 2021-date Thu Apr  1 21:22:27 2021; exit: 0 21504 0
158.01_HydjetQ_reminiaodPbPb2018_INPUT+HydjetQ_reminiaodPbPb2018_INPUT+REMINIAODHI2018PPRECOMB+HARVESTHI2018PPRECOMINIAOD Step0-DAS_ERROR Step1-NOTRUN Step2-NOTRUN  - time date Thu Apr  1 21:25:30 2021-date Thu Apr  1 21:25:28 2021; exit: 1 0 0
1306.0_SingleMuPt1_UP15+SingleMuPt1_UP15+DIGIUP15+RECOUP15+HARVESTUP15 Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED  - time date Thu Apr  1 21:36:51 2021-date Thu Apr  1 21:25:30 2021; exit: 0 0 0 0
1325.81_TTbar_13_106Xv1NanoAODINPUT+TTbar_13_106Xv1NanoAODINPUT+NANOEDMMC2017_106XMiniAODv1+HARVESTNANOAODMC2017_106XMiniAODv1 Step0-DAS_ERROR Step1-NOTRUN Step2-NOTRUN  - time date Thu Apr  1 21:28:37 2021-date Thu Apr  1 21:28:36 2021; exit: 1 0 0
1330.0_ZMM_13+ZMM_13+DIGIUP15+RECOUP15_L1TMuDQM+HARVESTUP15_L1TMuDQM+NANOUP15 Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Thu Apr  1 21:43:01 2021-date Thu Apr  1 21:28:38 2021; exit: 0 0 0 0 0
101.0_SingleElectronE120EHCAL+SingleElectronE120EHCAL Step0-PASSED  - time date Thu Apr  1 21:33:45 2021-date Thu Apr  1 21:32:03 2021; exit: 0
312.0_Pyquen_ZeemumuJets_pt10_2760GeV_2021+Pyquen_ZeemumuJets_pt10_2760GeV_2021+DIGIHI2021MIX+RECOHI2021MIX+HARVESTHI2021PPRECO Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED  - time date Thu Apr  1 21:54:56 2021-date Thu Apr  1 21:33:25 2021; exit: 0 0 0 0
25202.0_TTbar_13+TTbar_13+DIGIUP15_PU25+RECOUP15_PU25+HARVESTUP15_PU25+NANOUP15_PU25 Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Thu Apr  1 21:55:24 2021-date Thu Apr  1 21:33:45 2021; exit: 0 0 0 0 0
1000.0_RunMinBias2011A+RunMinBias2011A+TIER0+SKIMD+HARVESTDfst2+ALCASPLIT Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Thu Apr  1 21:58:14 2021-date Thu Apr  1 21:36:51 2021; exit: 0 0 0 0 0
1001.0_RunMinBias2011A+RunMinBias2011A+TIER0EXP+ALCAEXP+ALCAHARVDSIPIXELCALRUN1+ALCAHARVD1+ALCAHARVD2+ALCAHARVD3+ALCAHARVD4+ALCAHARVD5 Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED Step5-PASSED Step6-PASSED Step7-PASSED Step8-PASSED  - time date Thu Apr  1 22:01:50 2021-date Thu Apr  1 21:43:01 2021; exit: 0 0 0 0 0 0 0 0 0
10024.0_TTbar_13+2017+TTbar_13TeV_TuneCUETP8M1_GenSim+Digi+RecoFakeHLT+HARVESTFakeHLT+ALCA+Nano Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED Step5-PASSED  - time date Thu Apr  1 22:11:43 2021-date Thu Apr  1 21:54:56 2021; exit: 0 0 0 0 0 0
10042.0_ZMM_13+2017+ZMM_13TeV_TuneCUETP8M1_GenSim+Digi+RecoFakeHLT+HARVESTFakeHLT+ALCA+Nano Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED Step5-PASSED  - time date Thu Apr  1 22:09:06 2021-date Thu Apr  1 21:55:24 2021; exit: 0 0 0 0 0 0
10224.0_TTbar_13+2017PU+TTbar_13TeV_TuneCUETP8M1_GenSim+DigiPU+RecoFakeHLTPU+HARVESTFakeHLTPU+Nano Step0-PASSED Step1-FAILED Step2-NOTRUN Step3-NOTRUN Step4-NOTRUN  - time date Thu Apr  1 22:07:34 2021-date Thu Apr  1 21:58:14 2021; exit: 0 21504 0 0 0
10824.0_TTbar_13+2018+TTbar_13TeV_TuneCUETP8M1_GenSim+Digi+RecoFakeHLT+HARVESTFakeHLT+ALCA+Nano Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED Step5-PASSED  - time date Thu Apr  1 22:14:58 2021-date Thu Apr  1 22:01:51 2021; exit: 0 0 0 0 0 0
11634.0_TTbar_14TeV+2021+TTbar_14TeV_TuneCP5_GenSim+Digi+Reco+HARVEST+ALCA Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Thu Apr  1 22:20:40 2021-date Thu Apr  1 22:07:34 2021; exit: 0 0 0 0 0
12434.0_TTbar_14TeV+2023+TTbar_14TeV_TuneCP5_GenSim+Digi+Reco+HARVEST+ALCA Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Thu Apr  1 22:24:24 2021-date Thu Apr  1 22:09:07 2021; exit: 0 0 0 0 0
23234.0_TTbar_14TeV+2026D49+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14+DigiTrigger+RecoGlobal+HARVESTGlobal Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED  - time date Thu Apr  1 22:40:00 2021-date Thu Apr  1 22:11:43 2021; exit: 0 0 0 0
23434.999_TTbar_14TeV+2026D49PU_PMXS1S2PR+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14+PREMIX_PremixHLBeamSpot14PU+DigiTriggerPU+RecoGlobalPU+HARVESTGlobalPU Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Thu Apr  1 22:49:28 2021-date Thu Apr  1 22:14:58 2021; exit: 0 0 0 0 0
28234.0_TTbar_14TeV+2026D60+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14+DigiTrigger+RecoGlobal+HARVESTGlobal Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED  - time date Thu Apr  1 22:40:56 2021-date Thu Apr  1 22:20:40 2021; exit: 0 0 0 0
250202.181_TTbar_13UP18+TTbar_13UP18+PREMIXUP18_PU25+DIGIPRMXLOCALUP18_PU25+RECOPRMXUP18_PU25+HARVESTUP18_PU25 Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Thu Apr  1 22:46:07 2021-date Thu Apr  1 22:24:25 2021; exit: 0 0 0 0 0
33 28 27 22 14 4 1 1 1 tests passed, 3 4 0 0 0 0 0 0 0 failed
```

**Comment by jfernan2** [comment]
> Approximate backport of the 11_3_X version

Why the backport is now approximate? Can you elaborate a bit? Thanks

**Comment by dildick** [comment]
The GEM-CSC integrated local trigger emulator runs by default in run-3 eras in CMSSW_11_3_X. But the integrated local trigger firmware has not yet been deployed at P5. So in the L1T DQM re-emulation sequence in CMSSW_11_2_X I turned the integrated local trigger off.

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+1
Tested succesfully at DQM@P5

**Comment by silviodonato** [comment]
+1

**Pull request merged**
