### PR TITLE
Make ElectronMVA usable in FWlite again

### PR DESCRIPTION
**Pull request by guitargeek**
Hi,

in the discussion about issue https://github.com/cms-sw/cmssw/issues/23676 it became evident that the current electron MVA ID does not work in FWlite/Python. Mainly the reason for this was that the MVA classes have to get additional variables not in the objects from edm::ValueMaps and the objects therefore need to be wrapped in something Ref-like (`edm::Ptr`s in the current implementation).

To get around this, we propose to add another helper class (`MVAVariableHelper`) to the Egamma MVA framework which calculates the extra variables and passes is to the MVA classes, which in turn don't need any other event or provenance information no more. The same function used by the new MVAVariableHelper to get the extra electron variables can also used in FWLite. An example will be included in the test code. There is also a new Python wrapper class which makes using the most recent Electron MVAs for 2016 and 2017 in Python very easy.

Furthermore, I cleaned up the MVANtuplizers a bit and more importantly changed the interface of the ConversionTools to not require edm::Handles anymore. Which makes their usage a bit more consistent in FWlite/Python with the other code I wrote.

Local matrix tests pass and I checked the output of the new fwlite test and the ElectronMVANtuplizer for numerical agreement of MVA values. Validation plots here [1]. If one wants to reproduce the comparison, the pt threshold in the ElectronMVANtuplizer has to be set to zero [2] and one could make the comparison plots with this script for example.

I hope everyone is fine with these changes and I don't have to touch the MVA code again any time soon.

Cheers,
Jonas

Shout-out to who discussed in the issue-thread @Dr15Jones, @makortel and of course to @cbernet for the nice discussion and help but in particular the FWlite example!

[1] https://rembserj.web.cern.ch/rembserj/plots/CMSSW_PRs/25337/
[2] https://github.com/cms-sw/cmssw/blob/master/RecoEgamma/ElectronIdentification/plugins/ElectronMVANtuplizer.cc#L424
[3] https://gitlab.cern.ch/snippets/636

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by Sam-Harper** [comment]
@guitargeek , thank you for this, really appreciate it!

**Comment by cbernet** [comment]
Hi all, I really appreciate this as well, and I would like to thank again @guitargeek very much for all the work. Just one thing though, there are a couple very small developments missing before we can apply the mva ID in FWLite. I did a PR to @guitargeek for that (https://github.com/guitargeek/cmssw/pull/1) and we will need to add these developments here (or in a later PR) when we're done. 

@lucastorterotot @GaelTouquet

**Comment by guitargeek** [comment]
Ok that should be it! The working point implementation by @cbernet was merged, tested and validated as well by the snippet linked in my original post. Histograms with the MVA decisions were added as well, and it has been asserted in Python that the decisions by FWlite and the full framework are identical.

**Comment by perrotta** [comment]
please test

**Comment by guitargeek** [comment]
Here the backport for @cbernet to 9_4_X:

https://github.com/guitargeek/cmssw/tree/EgammaID_FWlite_949

It's based on the official egamma Fall17V2 ID recipe plus merging all my RecoEgamma PRs up to this one in the right order, plus the new weight files so one does not have to clone some externals.

Maybe I should have done something like this for the 10_2_X PR @perrotta, then there are basically no rebase conflicts which can be wrongly resolved.  But I was afraid that would be too much for a backport.

Anyway we have now the most important part which is the V2 photon IDs almost backported to 10_2_X and a private branch to get all the Egamma ID developments from master back in 9_4_X. I think that's a good status.

**Comment by andrius-k** [comment]
+1

**Comment by davidlange6** [comment]
Your PR is unmergeable. Please have a look and possibly rebase it.

**Comment by perrotta** [comment]
please test

**Comment by andrius-k** [comment]
please test

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
I quickly glanced at the timing performance of the new code. With the TTbar PU workflow 25202 I could verify that there is indeed also evidence of some little optimization with this code, although the modules involved were not large CPU consumers even before:

```
  delta/mean delta/orJob     original                   new       module name
  ---------- ------------     --------                  ----       ------------
     removed      -0.00%         0.04 ms/ev ->         0.00 ms/ev electronMVAVariableHelper
   -0.514217      -0.01%         1.15 ms/ev ->         0.68 ms/ev gedGsfElectrons
   -0.261770      -0.00%         1.44 ms/ev ->         1.11 ms/ev electronMVAValueMapProducer
   -0.218485      -0.00%         1.01 ms/ev ->         0.81 ms/ev gedPhotons
  ---------- ------------     --------                  ----       ------------
Job total:  8.7089 s/ev ==> 8.56415 s/ev
```

**Comment by perrotta** [comment]
+1
- The updates to the code clean it a bit and fulfil the purpose reported in the PR description of making ElectronMVA usable in FWlite, as demonstrated by the validation plots provided
- This goes together with an overall optimization of the code itself
- Jenkins tests pass, and show no differences in the reco output, as it was in the purpose of this PR

**Comment by fabiocos** [comment]
@peruzzim @fgolf this PR is touching also the nanoAOD configuration, please check that it is not interfering with your developments, and sign it in case

**Comment by fabiocos** [comment]
@peruzzim @fgolf do I understand correctly that this is ok for you?

**Comment by fabiocos** [comment]
+1

the fwlite test provided runs smoothly

**Comment by fabiocos** [comment]
merge

@peruzzim @fgolf please note this merge affects you

**Comment by fabiocos** [comment]
@peruzzim @fgolf now that the xpog category has been assigned, please sign it for reference

**Comment by peruzzim** [comment]
+xpog

for the modification to `nano_cff.py`, as NANOAOD workflows run and show no difference

**Pull request merged**
