### PR TITLE
Phase2-hgx360k Update he name of the file dict2026geometry to dictRun4 in Geometry/CMSCommonData and Fireworks/Geometry

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Update he name of the file dict2026geometry to dictRun4 in Geometry/CMSCommonData and Fireworks/Geometry

#### PR validation:

Tested using the runTheMatrix test workflows

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by alja** [comment]
+1

**Comment by bsunanda** [comment]
+geometry

**Comment by bsunanda** [comment]
@Moanwar, @srimanob, @subirsarkar Please approve this PR

**Comment by Moanwar** [comment]
+Upgrade

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
