### PR TITLE
Geometry 2018 (updated Cavern and new shields)

### PR DESCRIPTION
**Pull request by slomeo**
scripts to create payloads for this specific scenario (Geometry 2018 + updated cavern and new neutron shields)

### CODE REVIEW

**Comment by kpedro88** [comment]
please test

**Comment by kpedro88** [comment]
+upgrade

**Comment by cvuosalo** [comment]
+1

**Comment by fabiocos** [comment]
@ggovi you review is needed in order to move forward

**Comment by ggovi** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
