### PR TITLE
EGM ID Update 74X

### PR DESCRIPTION
**Pull request by lgray**
This pull request implements one new photon ID, it is not added to MiniAOD.

Updates:
- Effective areas 
- A new cut class for the 25ns photon ID
- The new (and only) 25ns photon ID.

### CODE REVIEW

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
@ikrav

**Comment by lgray** [comment]
@cmsbuild please test

Unit test failure due to EOS issue.

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
+1

For #12738 a1c4ad5fc8fadf90b5d8a1a3e8aa85c8b15f093c

Adding a new photon ID. #12740 and #12742 are the 80X and 76X versions of this PR, and the former has already been approved by Reco.

The code changes are satisfactory, and Jenkins tests against baseline CMSSW_7_4_X_2015-12-06-1100 show no significant differences. An extended test performed for #12740 also shows no significant differences.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
