### PR TITLE
fix DQM sequence name for `TkAlCosmicsDuringCollisions0T` track collection (within `TkAlCosmics0T`)

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

Title says it all, follows up to https://github.com/cms-sw/cmssw/pull/40661#issuecomment-1415876585

#### PR validation:

Run  `runTheMatrix.py -l 1005.0 -t 4 -j 8` successfully and checked that there are no residual warning 

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

N/A

### CODE REVIEW

**Comment by mmusich** [comment]
type bug-fix

**Comment by mmusich** [comment]
test parameters:
   * workflow = 1005.0

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
As expected the error message [present in IBs](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_amd64_gcc11/CMSSW_13_0_X_2023-02-03-2300/pyRelValMatrixLogs/run/1005.0_RunCosmics2022F/step2_RunCosmics2022F.log#/40) is now gone (see [log](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-65bb4c/30396/runTheMatrix-results/1005.0_RunCosmics2022F/step2_RunCosmics2022F.log))

**Comment by emanueleusai** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
