### PR TITLE
Remove Debug Code form CSCDetId

### PR DESCRIPTION
**Pull request by ianna**
- Move CSCDetId validity checks to unit test

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
@VinInn - as discussed yesterday

**Comment by VinInn** [comment]
@Ianna, thanks!

**Comment by ianna** [comment]
@cmsbuild - the errors seem to be unrelated:
```
Running script: /tmp/cmsbuild/workspace/ib-any-integration/CMSSW_8_0_X_2016-01-19-2300/src/TopQuarkAnalysis/TopEventSelection/test/runtests.sh
# Conditions read from  CMS_CONDITIONS  via FrontierProd 
----- Begin Fatal Exception 20-Jan-2016 13:29:54 CET-----------------------
An exception of category 'ConfigFileReadError' occurred while
   [0] Processing the python configuration file named /tmp/cmsbuild/workspace/ib-any-integration/CMSSW_8_0_X_2016-01-19-2300/src/TopQuarkAnalysis/TopEventSelection/test/ttSemiLepSignalSelMVAComputer_cfg.py
Exception Message:
python encountered the error: <type 'exceptions.ImportError'>
No module named DBCommon.CondDBSetup_cfi
----- End Fatal Exception -------------------------------------------------
Failure using ttSemiLepSignalSelMVAComputer_cfg.py: status 90
status = 23040

---> test runtestTqafTopEventSelection had ERRORS
 
^^^^ End Test runtestTqafTopEventSelection ^^^^
Package TopQuarkAnalysis/TopTools: Running test runtestTqafTopTools
```

**Comment by ianna** [comment]
please test

**Comment by smuzaffar** [comment]
yes looks like CMSSW_8_0_X_2016-01-19-2300 release is not good for PR testing. I have marked it as a bad release and restarted the tests which should now use  CMSSW_8_0_X_2016-01-19-1100

**Comment by ianna** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
