### PR TITLE
HcalDQM: Add FED integrity module, backport of #38387

### PR DESCRIPTION
**Pull request by lwang046**
#### PR description:
Backport of PR #38387, based on top of CMSSW_12_3_5_patch1 for P5 (online DQM).

#### PR validation:
Testes and verified with actual data from recent Run#352567

### CODE REVIEW

**Comment by emanueleusai** [comment]
please test

**Comment by emanueleusai** [comment]
testing at p5

**Comment by emanueleusai** [comment]
@lwang046 just to confirm, do you need this deployed at P5?

**Comment by lwang046** [comment]
Hi @emanueleusai , it's was an ancient request to have HCal included in the FED summary map. I think it's okay to have it tested and deployed now if it is deemed to be included sooner or later.

**Comment by emanueleusai** [comment]
test at P5 successful

**Comment by emanueleusai** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
