### PR TITLE
Adding fastjet shape correction for analysis in 75x (port of #11285)

### PR DESCRIPTION
**Pull request by rappoccio**
Forward-port of #11285.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
+1

For #11286 fa97fcfd2b0582eff8b12f92af6854fff2eba813

Adding Fast Jet shape correction, but disabled by default. There should be no change in standard workflows. The shape correction is intended for expert use by analysts. #11285 is the 74X version of this PR, and it has already been approved by Reco.

The code changes are satisfactory, and Jenkins tests against baseline CMSSW_7_5_X_2015-09-16-1100 show no significant differences, as expected.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
