### PR TITLE
Bug fix to the HiPuRhoProducer.cc

### PR DESCRIPTION
**Pull request by FHead**
This is the backport to CMSSW 11_2_X of PR https://github.com/cms-sw/cmssw/pull/36489
More information can be found in the original PR.

It addresses issue https://github.com/cms-sw/cmssw/issues/37841.

It passed basic matrix tests

@mandrenguyen

### CODE REVIEW

**Comment by qliphy** [comment]
please test

**Comment by clacaputo** [comment]
Hi @FHead and @mandrenguyen , do we need to put this change behind a modifier? You mentioned (#37841 ) that this PR is needed for "partial reprocessing" some PbPb data and MC, so there are going to be some discrepancies between dataset/samples, produced with two different versions of the reconstruction code

**Comment by mandrenguyen** [comment]
@clacaputo So you would like to dedicated process modifier for the two backports, specifically for this reprocessing?

**Comment by clacaputo** [comment]
Hi @mandrenguyen, having a modifier would be ideal

**Comment by mandrenguyen** [comment]
@clacaputo  I have created a process modifier in #37984
If that works for you, we can close this PR, since it's already included there.

**Comment by FHead** [comment]
Since this is covered in https://github.com/cms-sw/cmssw/pull/37984, I will close this one

**Pull request closed without merging**
