### PR TITLE
Phase2-gex127M Make some protection in accessing inpu collections for MTD so that some FasTsim tests can proceed

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Make some protection in accessing inpu collections for MTD so that some FasTsim tests can proceed

#### PR validation:

Use the runTheMatrix test workflows

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by jpata** [comment]
Can you provide some details on the changes to the log verbosity in production? Or do I understand correctly that since it would have resulted in a crash, this code is not running in any default production?

**Comment by bsunanda** [comment]
For regular workflows in production or standard relval's, we do not come across these warnings. We get stuck when we try to develop FastSim workflows for Phase2 scenario. Once the workflows are fully developed, we would not get these mising collections.

**Comment by jpata** [comment]
+reconstruction
- prevents crash in Phase2 FastSim (not running by default anywhere)
- no changes to reco

**Comment by srimanob** [comment]
+Upgrade

This is a technical PR to add the protection of missing collections. The aim is for Phase-2 FastSim dev. There is no change expected for existing FullSim workflow.

**Comment by perrotta** [comment]
+1

**Pull request merged**
