### PR TITLE
Run4-sim78 Add a few methods for HGCal scinitllator part

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Add a few methods for HGCal scinitllator part to provide a better link to reality 

#### PR validation:

Tested using runTheMatrix workflow

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade

**Comment by silviodonato** [comment]
+1

**Pull request merged**
