### PR TITLE
New working point for B parking skim

### PR DESCRIPTION
**Pull request by gkaratha**
Dear all,

Please consider this new PR. Its a better WP for B parking skimming. No code has been changed. Only the WP. The new WP has 6.5% rate while keeping a bit more than 29% in efficiency. Thanks.

Best regards,
George Karathanasis

### CODE REVIEW

**Comment by gkaratha** [comment]
@bainbrid @mverzett

**Comment by prebello** [comment]
hi @kfjack could you please take a look ?
thank you

**Comment by kfjack** [comment]
Hi @prebello I think this change is totally okay (only changed one single threshold)! Many thanks.

**Comment by fabiocos** [comment]
@gkaratha sorry to be pedantic, but please update the title to something a bit more explicative (New working point for B parking skim ?)

**Comment by fabiocos** [comment]
please test workflow 136.898

**Comment by gkaratha** [comment]
Dear @fabiocos ,

You are right it was an awful name. Thanks for the suggestion.

Best,
George

**Comment by prebello** [comment]
+1

Thank you @kfjack

**Comment by fabiocos** [comment]
@gkaratha if you have any plot showing the improvement please attach it to this PR

**Comment by fabiocos** [comment]
+1

**Comment by gkaratha** [comment]
Dear @fabiocos ,

Yes, gladly. I have attached it. Thanks.

Best regards,
George

wp

**Pull request merged**
