### PR TITLE
Cleanup geant4 user code

### PR DESCRIPTION
**Pull request by civanch**
#### PR description:
Code clean-up, debug information improvement, dead code removal. No change of results of any WF is expected.

Added optional features:
1) detailed verbatim printout for MCtruth
2) added possibility to add Geant4 UI commands end of run
3) added command based scoring, which extend capabilities to study neutron and other background

#### PR validation:
private

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

unit test problem connected with DAS not this PR

**Comment by qliphy** [comment]
please test

**Comment by civanch** [comment]
Now the results are even better than in previous test.

**Comment by qliphy** [comment]
@civanch There is still some reco differences, for example:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_5_X_2022-05-18-1100+145706/50390/validateJR/all_OldVSNew_TTbar14TeV2026D88PUwPRMXwf39634p999/all_OldVSNew_TTbar14TeV2026D88PUwPRMXwf39634p999c_log10ticlTracksters_ticlSimTracksters__RECO_obj_regressed_energy.png
Would you please have a check?

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

there are small shift in one RECO histograms in Phase-2 WFs. These differences are small, I have not true explanation, may be numerical non-reproducibility, because hits and tracking particles are the same in my tests and all other histograms show very good agreement. I would indeed merge this PR even with these small effect . In queue there are modifications which will change simulation histories and will require real validation.

**Comment by perrotta** [comment]
Well, differences are not really that small. And the trend is exactly the same in all workflows (i.e. they are not stat fluctuations): events move from the negative to the positive part of these plots:
image

Perhaps some investigation is in order, possibly with the help of @cms-sw/hgcal-dpg-l2

**Comment by pfs** [comment]
I ran a local test to verify things up to DIGI level [1]  and I  confirm what the DQM report says: comparisons up to DIGI level are not affected by the PT. An example of the correlation of the DIGIS in CE-E before and after

image

The plot picked by @perrotta is at RECO but it's using some SIM information to build the trackster. The differences seem to indicate that the PR has non-neglible effect on this. @rovere @felicepantaleo can  probably comment if they spot something particular which may be affectingt.


[1] runTheMatrix.py -w upgrade -l 38624.0

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by civanch** [comment]
@qliphy , @perrotta , finally the situation with RECO plot is fully understood. There was bug in the code and the PR was correct. The bug fix is excluded now - I will add the fix in the next PR may be  together with the another fix in this area. In this PR, there are already several useful improvements, which do not change results, so better to merge as it is.

**Comment by civanch** [comment]
@perrotta , yes, exactly. It is not good to mix technical modifications with the bug fix, which change validation plots. 

The bug itself is not dramatic: intermediate Lorentz vector for MC truth is filled with kinetic energy instead of total energy. For relativistic particles the difference is small - what we observe in the reco plots. 

I see also over-complicate logic in the code for MCtruth: very difficult to explain, which particles are included in MC truth and why. It is likely due to historical reasons. In the bug-fix PR will try to make it more transparent. This will change validation plots, so a new PR should be maximally simple to be discussed with dpg, especially from hgcal.

**Comment by perrotta** [comment]
Fine, thank you: this can be merged.
@civanch maybe squashing all 15 commits into one could help future developers who may want to investigate the history of this code: what do you think?

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
