### PR TITLE
Add source_only flag for source-only dependencies in reco

### PR DESCRIPTION
**Pull request by guitargeek**
#### PR description:

Add `source_only` flag for source-only dependencies in `reco`. These dependencies were automatically found with [this script](https://github.com/guitargeek/PKGBUILDs/blob/master/cmssw/update_source_only.py).

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

No backport intended.

### CODE REVIEW

**Comment by fwyzard** [comment]
what is a `source_only="1"` dependency ?

**Comment by perrotta** [comment]
@cmsbuild please test

**Comment by VinInn** [comment]
> what is a `source_only="1"` dependency ?

My interpretation is "header-only" dependency: for instance "Geometry/CommonDetUnit" does not have any "src" directory

**Comment by perrotta** [comment]
+1
- Technical
- Jenkins tests pass

**Comment by srimanob** [comment]
Hi @guitargeek 
What is the benefit to have this `source_only` flag? Thanks.

**Comment by guitargeek** [comment]
The `source_only` flag indicates that this is a dependency that doesn't need to be linked against.

The benefits are more indirect, because scram automatically detects if the linking is needed:
1) More opportunities to uncover actually missing includes or dependencies (just like it happened in https://github.com/cms-sw/cmssw/pull/33728)
2) More information to analyze the dependency graph only by looking at the BuildFiles
3) Most important for me and the reason that I do this PR: the build system can know without looking at the dependency if linking is needed. This is useful for my attempt to [build CMSSW with CMake on Arch Linux](https://github.com/guitargeek/PKGBUILDs/tree/master/cmssw), in particular if you want to Build only parts of CMSSW and be agnostic about remaining packages.

So the benefits for building CMSSW with sram are not so tangible, but it's useful information in the BuildFile that can be used for various things like dependency analysis and trying out other build systems.

**Comment by fwyzard** [comment]
Is there a way to autodetect when the declarations in a BuildFile (no dependency, compile-only dependency, full dependency) go out of sync with what the source code actually uses ?

**Comment by guitargeek** [comment]
I don't know about autodetecting this, but it's a good question. You're thinking about the situation where the header-only dependency becomes a not-header-only-dependency, right? I also thought about this and I think the `source_only` flag is only beneficial here. Because either a) it doesn't compile without removing the flag or b) it still works, in which case we avoid unnecessary linking because we depend only on a subset of the library that is header only. So I really think this flag does only good and no harm.

**Comment by VinInn** [comment]
Header-only dependencies do not need to be declared as they are implicit in the cmssw include patch search.
So just remove them.

**Comment by guitargeek** [comment]
I think you can't just remove it, because the header-only dependency might export other header-only *external* dependencies that extend the search path.

**Comment by srimanob** [comment]
+Upgrade

Maybe there will be additional concerns that can be discussed during the release meeting or core SW meeting?
@silviodonato @qliphy @makortel

**Comment by davidlange6** [comment]
They do need to be declared even if indeed the current release include paths hide the need from the developer..

**Comment by fwyzard** [comment]
> They do need to be declared even if indeed the current release include paths hide the need from the developer..

Not saying they shouldn't be declared - but what are the reasons ?
Bringing in additional externals is one. Are there others ?

**Comment by davidlange6** [comment]
Having (or wanting to be able to have) build rules that depend on knowing header-only dependencies - Ones I know about are: 1) picking up external include paths; 2)  picking up cmssw includes for c++ modules. There may be other cases that I’m not aware of.

**Comment by Martin-Grunewald** [comment]
+1

**Comment by fwyzard** [comment]
> Having (or wanting to be able to have) build rules that depend on knowing header-only dependencies - Ones I know about are: 1) picking up external include paths; 2) picking up cmssw includes for c++ modules. There may be other cases that I’m not aware of.

OK.

So, back to my previous question... any way to make it automatic, at least for the intra-CMSSW dependencies ?

**Comment by davidlange6** [comment]
I opened an issue for that a few months ago. It didn't get much support...

On May 17, 2021 12:07 PM, Andrea Bocci ***@***.***> wrote:

Having (or wanting to be able to have) build rules that depend on knowing header-only dependencies - Ones I know about are: 1) picking up external include paths; 2) picking up cmssw includes for c++ modules. There may be other cases that I’m not aware of.

OK.

So, back to my previous question... any way to make it automatic, at least for the intra-CMSSW dependencies ?

**Comment by davidlange6** [comment]
Though we'd have to fix all circular dependencies first:(

On May 17, 2021 12:07 PM, Andrea Bocci ***@***.***> wrote:

Having (or wanting to be able to have) build rules that depend on knowing header-only dependencies - Ones I know about are: 1) picking up external include paths; 2) picking up cmssw includes for c++ modules. There may be other cases that I’m not aware of.

OK.

So, back to my previous question... any way to make it automatic, at least for the intra-CMSSW dependencies ?

**Comment by smuzaffar** [comment]
@VinInn , scram currently uses `source_only` attribute to make sure that any generated headers/sources are available before trying to complie the package. One of the main reason to add this is for CXXMODULE IBs where we want to make sure that `pcm` files are generated in order. There are many packages with header only dependencies and `pcm` for each of them should be generated in correct order.

**Comment by smuzaffar** [comment]
by the way, currently `source_only` is doing nothing except to make sure that `pcm`  are generated in order . So it is not bringing in the externals deps. If one wants to dep on full deps (cmssw and external s) of a package then they should just use `<use name="subsystem/package"/>` format

**Comment by silviodonato** [comment]
+1

**Pull request merged**
