### PR TITLE
Run3-hcx309 Rearrange the files to remove .h files from SimCalorimetry/HcalSimProducers/src

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Rearrange the files to remove .h files from SimCalorimetry/HcalSimProducers/src

#### PR validation:

Use the runTheMatrix test workflows 

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by perrotta** [comment]
Since you recombined the files in the plugin area, please remove now:
SimCalorimetry/HcalSimProducers/src/HcalDigiAnalyzer.h
SimCalorimetry/HcalSimProducers/src/HcalDigiStatistics.h
SimCalorimetry/HcalSimProducers/src/HcalHitAnalyzer.h

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by perrotta** [comment]
+1

**Comment by Dr15Jones** [comment]
This broke the IB. HcalDigiProducer needs to be in the src directory as it needs to be linkable with the mixing module.

**Comment by bsunanda** [comment]
I am making a PR to move it out to src
________________________________

**Pull request merged**
