### PR TITLE
Migration of HLT menus to 11_0_0 Template (11_0_X)

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
#### PR description:

Migration of HLT menus to 11_0_0 Template (11_0_X)
Based on CMSSW_11_0_0

#### PR validation:

TSG tests

#### if this PR is a backport please specify the original PR:

11_0 fork, not a backport!

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
2018 menu needs migration as well!

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
