### PR TITLE
Clean unused dependencies from BuildFiles

### PR DESCRIPTION
**Pull request by guitargeek**
#### PR description:

Another quick BuildFile cleaning PR in the style of many before (for example https://github.com/cms-sw/cmssw/pull/36144).

In many cases, the dependencies had to be moved to the appropriate BuildFile, for example from a plugins directory to the library directory or vice versa.

In one place, a missing include has been added to not cause a false positive in my BuildFile checker.

This PR cleans unnecessary includes from CMSSW BuildFiles that were added in the last months.

#### PR validation:

CMSSW compiles.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

No backport intended.

### CODE REVIEW

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by jfernan2** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

Tachnical PR, no change is expected. PR test runs fine.

**Comment by smuzaffar** [comment]
please test for CMSSW_12_3_UBSAN_X

lets tests for ubsan which normally fails due to such cleanup

**Comment by yuanchao** [comment]
Lots of build errors and tests comparison failes for CMSSW_12_3_UBSAN_X

**Comment by cecilecaillol** [comment]
+l1

**Comment by clacaputo** [comment]
Hi @smuzaffar , I see a lot of distributions having differences for RECO. Is something expected with UBSAN build? How does it differentiate from a usual build?

**Comment by smuzaffar** [comment]
comparison differences are expected for ubsan, so please ignore those. Ubsan tests are mostly to make sure that ubsan can build without link errors. https://github.com/cms-sw/cmssw/pull/36834#issuecomment-1025366323 looks good for build part to all looks good with this cleanup

**Comment by francescobrivio** [comment]
+1
 
 - trivial changes on the alca/db side
 - successful compilation for UBSAN build (see https://github.com/cms-sw/cmssw/pull/36834#issuecomment-1025512776 and https://github.com/cms-sw/cmssw/pull/36834#issuecomment-1025366323)
 - no differences/failures observed for standrd CMSSW compilation (see https://github.com/cms-sw/cmssw/pull/36834#issuecomment-1025064525)

**Comment by civanch** [comment]
+1

**Comment by guitargeek** [comment]
Hi @clacaputo, I hope Shazad's comment cleared your doubt. Can you please approve?

**Comment by guitargeek** [comment]
Hi @santocch, can you please take a look and approve? And @perrotta, this PR can also be merged without the `analysis` signoff as this is usually the slowest to get.

**Comment by clacaputo** [comment]
+reconstruction

- technical PR
- RECO changes found in the test are related to UBSAN build and can be ignored https://github.com/cms-sw/cmssw/pull/36834#issuecomment-1025512776

**Comment by perrotta** [comment]
+1

**Comment by perrotta** [comment]
merge

**Comment by santocch** [comment]
+1

**Pull request merged**
