### PR TITLE
Fix testCUDAService unit test

### LINKED ISSUE #40616: [PowerPC] Unit test testCUDAService fails
Failing at least since `CMSSW_13_0_X_2023-01-19-2300`. Log ([link](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_ppc64le_gcc11/CMSSW_13_0_X_2023-01-25-2300/unitTestLogs/HeterogeneousCore/CUDAServices#/)):

```
===== Test "testCUDAService" ====

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
testCUDAService is a Catch v2.13.6 host application.
Run with -? for options

-------------------------------------------------------------------------------
Tests of CUDAService
  CUDAService enabled
  Enabled only if there are CUDA capable GPUs
-------------------------------------------------------------------------------
/scratch/cmsbuild/jenkins_a/workspace/build-any-ib/w/tmp/BUILDROOT/6f55c87ee4256a45b80226ccc4e367a5/opt/cmssw/el8_ppc64le_gcc11/cms/cmssw/CMSSW_13_0_X_2023-01-25-2300/src/HeterogeneousCore/CUDAServices/test/testCUDAService.cpp:39
...............................................................................

/scratch/cmsbuild/jenkins_a/workspace/build-any-ib/w/tmp/BUILDROOT/6f55c87ee4256a45b80226ccc4e367a5/opt/cmssw/el8_ppc64le_gcc11/cms/cmssw/CMSSW_13_0_X_2023-01-25-2300/src/HeterogeneousCore/CUDAServices/test/testCUDAService.cpp:39: FAILED:
due to unexpected exception with message:
  An exception of category 'NotFound' occurred.
  Exception Message:
  No ServiceRegistry has been set for this thread. Tried to ask availability of
  a Service edm::ResourceInformation

-------------------------------------------------------------------------------
Tests of CUDAService
  CUDAService enabled
-------------------------------------------------------------------------------
/scratch/cmsbuild/jenkins_a/workspace/build-any-ib/w/tmp/BUILDROOT/6f55c87ee4256a45b80226ccc4e367a5/opt/cmssw/el8_ppc64le_gcc11/cms/cmssw/CMSSW_13_0_X_2023-01-25-2300/src/HeterogeneousCore/CUDAServices/test/testCUDAService.cpp:36
...............................................................................

/scratch/cmsbuild/jenkins_a/workspace/build-any-ib/w/tmp/BUILDROOT/6f55c87ee4256a45b80226ccc4e367a5/opt/cmssw/el8_ppc64le_gcc11/cms/cmssw/CMSSW_13_0_X_2023-01-25-2300/src/HeterogeneousCore/CUDAServices/test/testCUDAService.cpp:36: FAILED:
due to unexpected exception with message:
  An exception of category 'NotFound' occurred.
  Exception Message:
  No ServiceRegistry has been set for this thread. Tried to ask availability of
  a Service edm::ResourceInformation

===============================================================================
test cases: 1 | 1 failed
assertions: 4 | 2 passed | 2 failed


---> test testCUDAService had ERRORS
TestTime:1
^^^^ End Test testCUDAService ^^^^
>> Tests for package HeterogeneousCore/CUDAServices ran.

```

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

Resolves https://github.com/cms-sw/cmssw/issues/40616. I also added some tests that the `ResourceInformation` service gets filled by `CUDAService`.

#### PR validation:

Tested both with and without a GPU (on `amd64`) that the unit test runs.

### CODE REVIEW

**Comment by makortel** [comment]
enable gpu

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
+heterogeneous

**Comment by perrotta** [comment]
+1

**Pull request merged**
