### PR TITLE
Fix bug in Track's magnetic field determination

### PR DESCRIPTION
**Pull request by alja**
A FWMagField::m_source was not updated in FWMagField::checkFieldInfo(). This flag was read in the Track proxy builder which did field estimation instead of getting field from event data:
https://github.com/cms-sw/cmssw/blob/CMSSW_7_5_X/Fireworks/Tracks/plugins/FWTrackProxyBuilder.cc#L65

unnamed

### CODE REVIEW

**Comment by alja** [comment]
+1

**Comment by alja** [comment]
The PR also contains changes for stand-alone version of cmsShow.

**Comment by alja** [comment]
-1 Need to add one more change.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
