### PR TITLE
latest calibrations from Pedro + global compensation plugin

### PR DESCRIPTION
**Pull request by lgray**
- Update to HGCal Calibrations with better pi/e determination
- Improved new global hadron compensation plugin for PandoraPFA

@pfs @vandreev11 @sethzenz @kpedro88

### CODE REVIEW

**Comment by lgray** [comment]
@mark-grimes We are waiting on some final checks in 140PU to make sure everything is OK. We'll update here with if this is necessary for the release or not.

**Comment by lgray** [comment]
@mark-grimes got the OK-to-go from @pfs, please integrate this and cut the release.

@vandreev11

**Comment by mark-grimes** [comment]
Okay.  @fratnikov is looking after integration at the moment so he'll take care of it when he comes online around now.

@fratnikov, the release will also need the other things in the queue.  A patch release is probably enough (changing the Pandora external again would have required a full release).

**Comment by lgray** [comment]
@mark-grimes @fratnikov There will be one more PR. Just a moment.

**Comment by lgray** [comment]
@mark-grimes actually let me add it here...

**Comment by lgray** [comment]
@mark-grimes @fratnikov done, please use this.

**Comment by fratnikov** [comment]
please test

**Comment by fratnikov** [comment]
merge
tested also with 15661 and 15861

**Pull request merged**
