### PR TITLE
Cleanup PFHBHERecHitCreatorMaxSample etc

### PR DESCRIPTION
**Pull request by hatakeyamak**
#### PR description:

Remove PFHBHERecHitCreatorMaxSample-related file and some other unused PFClusterProducer config files. Addressing comments on:
https://github.com/cms-sw/cmssw/issues/17529

#### PR validation:

Made sure a few representative matrix tests run without a problem.

#### if this PR is a backport please specify the original PR:

This is not a backport.

@bendavid @jpata

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

so long, method 1.5. :wave:

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by hatakeyamak** [comment]
Ping...

**Comment by perrotta** [comment]
+1
- Removing some unused PFClusterProducer and related config doesn't harm the automatic tests, which show non difference wrt baseline as expected

**Comment by fabiocos** [comment]
+1

**Pull request merged**
