### PR TITLE
Add module for validating tracks in miniAOD and fix track-to-PackedCandidate association

### PR DESCRIPTION
**Pull request by makortel**
This PR adds a DQM module for comparing the tracks embedded in PackedCandidates to the corresponding generalTracks. The comparison is performed by filling a set of histograms from differences of several quantities that are expected to be equal within the numerical accuracy (two exceptions being "diffNdof" and "diffHitPatternNumberOfLostPixelHits", to be documented on some twiki page).

I also decided to include #9564 here since it is a prerequisite and its integration hasn't progressed yet. Without it the code would sooner or later throw an exception with

```
Exception Message:
Association: index in the map out of upper boundary
```

Tested in CMSSW_7_5_X_2015-06-06-2300 with wf 11325. No other changes expected than new histograms under "Tracking/PackedCandidate" folder.

@rovere @VinInn @arizzi @gpetruc

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by makortel** [comment]
ping

**Comment by deguio** [comment]
-1
I fear this one needs a rebase. moreover, since the module you added will run on both data and MC, I would propose to make it available under DQM or DQMOffline instead of Validation. normally the validation modules are included in the validation sequence that runs over the MC.
thanks,
F.

**Comment by makortel** [comment]
@deguio I can certainly move it (I wasn't sure where to place it, and ended up with Validation since I'm familiar with it and `miniAODDQMSequence` was already also taken from there). I don't think we have anything tracking related under DQMOffline. Under DQM we seem to have
```
DQM/TrackingMonitor/
DQM/TrackingMonitorClient/
DQM/TrackingMonitorSource/
```
but I don't really know which one would be most appropriate.

**Comment by rovere** [comment]
I'd use plain DQM/TrackingMonitor.
I'd refrain from adding another package.

**Comment by makortel** [comment]
Thanks @rovere, I'll go with that then.

**Comment by deguio** [comment]
thanks @makortel 
I agree with @rovere. updating here should update #9801 as well

**Comment by makortel** [comment]
As discussed above, I moved PackedCandidateTrackValidator to DQM/TrackingMonitor package. I tested in 750pre6 with wf 11325 that the results stay the same (but did not rebase).

**Comment by deguio** [comment]
+1
thanks @makortel

**Comment by makortel** [comment]
Whoops, that incorrect import passed my tests (i.e. I forgot `scram b clean` first...). Now it should work.

**Comment by deguio** [comment]
+1

**Comment by monttj** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
