### PR TITLE
Used importlib in scripts

### PR DESCRIPTION
**Pull request by sroychow**
#### PR description:
Proposed fix to #34489.

#### PR validation:
Checked locally that the dump output remains the same after the changes.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:
NA

### CODE REVIEW

**Comment by makortel** [comment]
@davidlange6 Can you comment if this looks reasonable?

**Comment by davidlange6** [comment]
I think the new syntax is correct ... but apparently also one that is going to be deprecated.. See the suggestion here:

https://github.com/conan-io/conan/issues/3441#issuecomment-419480963

**Comment by smuzaffar** [comment]
Milestone for this pull request has been moved to CMSSW_14_0_X.Please open a backport if it should also go in to CMSSW_13_3_X.

**Comment by smuzaffar** [comment]
ping

**Comment by makortel** [comment]
Given that this PR is a draft and has been unattended for 3 years, I think we can close it

**Comment by makortel** [comment]
-core

**Pull request closed without merging**
