### PR TITLE
Cluster multiplicity74 x

### PR DESCRIPTION
**Pull request by fioriNTU**
retune of bundaries between cluster multiplicity regions

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1

**Comment by fioriNTU** [comment]
Hi, I wonder why this PR is not yet merged, can somebody clarify?
Also the equivalent PR for 75x is not yet merged.

FF

**Comment by deguio** [comment]
each change needs to be merged in 76 and go through a full validation cycle there before being merged in other closed cycles.

**Comment by fioriNTU** [comment]
Hi Federico,
actually this change has been merged in 76x, it is PR #11341. Moreover 
this PR is only a change of two parameters in a cfi file, should not 
give any problem.
Thanks anyway for fast feedback.

FF

Il 28/09/2015 16.08, Federico De Guio ha scritto:
>
> each change needs to be merged in 76 and go through a full validation 
> cycle there before being merged in other closed cycles.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/cms-sw/cmssw/pull/11338#issuecomment-143752950>.
>



---
Questa e-mail è stata controllata per individuare virus con Avast antivirus.
https://www.avast.com/antivirus

**Comment by davidlange6** [comment]
+1

**Pull request merged**
