### PR TITLE
Fix test unit failure 

### PR DESCRIPTION
**Pull request by ebrondol**
Removing these lines since they are already defined in `DataFormats/Phase2TrackerCluster/src/classes_def.xml` 
in this way the Test Unit should not failing anymore.

No changes are expected.

@smuzaffar @slava77

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by smuzaffar** [comment]
@ebrondol , it did fix the unit tests
```
---> test mayown_t succeeded
---> test testOmniClusterRef succeeded
---> test testDoc succeeded
---> test testNew succeeded
---> test DetectorDescriptionParserTE succeeded
---> test testmat succeeded
---> test testDDCompactView succeeded
---> test dumpDDCompactView succeeded
---> test dumpDDExpandedView succeeded
```

**Comment by slava77** [comment]
@cmsbuild please test
comparisons got stuck

The following is a comment to cms-bot/run-pr-comparisons (not the best placement)
there is an error message in the console at the end
https://cmssdt.cern.ch/jenkins/job/compare-root-files-short-matrix/14210/console
```
+ xargs sh -c 'sed -i -s s/../RelMonSummary.html/RelMonSummary.html/g || true'
sed: -e expression #1, char 25: unknown option to `s'
```
likely unrelated to the comparisons getting stuck.
Still, something to fix. It may be easier to use ``` ? ``` instead of ``` / ``` in sed in this case

**Comment by smuzaffar** [comment]
cms-bot/run-pr-comparisons updated

**Comment by cvuosalo** [comment]
+1

For #14690 a92116c4ea2e515a8261d65645804675a2049c2c

Removing duplicate Phase 2 tracker items from classes_def.xml file to fix unit test. There should be no change in monitored quantities.

Jenkins tests against baseline CMSSW_8_1_X_2016-05-29-2300 show no significant differences, as expected. Upgrade workflow 10600.0_FourMuPt1_200 was run successfully, including the RECO step.

**Comment by smuzaffar** [comment]
@davidlange6 , we should include this in for next IB to get rid of failing unit tests.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
