### PR TITLE
Migration of HLT to CMSSW_10_0_0

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
Migration of HLT to CMSSW_10_0_0
(Based on CMSSW_10_0_0)

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
