### PR TITLE
Code cleanup, debug improvements, bug fixes in Tracking code

### PR DESCRIPTION
**Pull request by VinInn**
Mostly cleanup and improvement of debug code.
Fixed a bug in the handling of CCC in the Trajectory.
Negligible regression expected due to the bug fix.

### CODE REVIEW

**Comment by VinInn** [comment]
@cmsbuild, please test

**Comment by slava77** [comment]
@cmsbuild please test
81X IB is out.

**Comment by cvuosalo** [comment]
@VinInn: Are the Jenkins RelVal failures related to this PR? I don't see them in the base IB.

**Comment by VinInn** [comment]
FastSim? possible. I do not understand why FastSim is going through there though

**Comment by VinInn** [comment]
@cmsbuild, please test

**Comment by cvuosalo** [comment]
Jenkins test results show numerous differences in SiStrip quantities, but they are very tiny and insignificant. Here's an example from workflow 25202.0_TTbar_13:

cluster

**Comment by cvuosalo** [comment]
An extended test is in progress...

**Comment by slava77** [comment]
On 2/22/16 12:59 PM, Carl Vuosalo wrote:
> Jenkins test results show numerous differences in SiStrip quantities,
> but they are very tiny and insignificant. Here's an example from
> workflow 25202.0_TTbar_13:
> 
> cluster
> <https://cloud.githubusercontent.com/assets/5736159/13232428/b77c288c-d974-11e5-8127-47b2ca125219.png>

Are there any changes other than in HLT/*SiStrip/*OffTrack ?

**Comment by cvuosalo** [comment]
Jenkins results also have similar very tiny changes in HLT/Run summary/Tracking in various categories.

**Comment by cvuosalo** [comment]
@VinInn: Could you please comment on whether the following differences should be expected from this PR? They are the results of an extended test of workflow 25202.0_TTbar_13 with 70 events against baseline CMSSW_8_1_X_2016-02-18-2300. The test results include about a hundred more similar difference plots, all with very tiny differences.

res
fakerate

**Comment by VinInn** [comment]
Tiny changes may appear due to the bug fix.
the muon resolution looks a migration between two nearby bins, the fake rate change looks small
@mtosi tested in HLT and gave green light

**Comment by slava77** [comment]
@VinInn please point out the bugfix.
Is it all in 83d0cdd3f6 ?

If it changes behavior, I'm curious why is this specific to HLT? If I interpreted @cvuosalo comments correctly, there are no changes in reco products.
... actually looking at the diffs myself, I see small changes in 9.0 and 1330.0

I guess we are better off running a few more checks, maybe 1313 and 25202 to know the size of the bugfix, in particular in perspective of what we miss now in 80X.

**Comment by VinInn** [comment]
Yes, the bug fix is  83d0cdd.  (plus additional fix to the fix).
Marco and Mia run extensive tests to assess that we are not missing anything in 80X.
The reasons are complex, and related to the way the update works and how segments are merged.
As different code run in HLT and Reco (you know grouped vs classic Ckf), some differences may be observed.

**Comment by slava77** [comment]
On 2/23/16 7:09 AM, Vincenzo Innocente wrote:
> Yes, the bug fix is 83d0cdd
> <https://github.com/cms-sw/cmssw/commit/83d0cdd3f648a4a5a7b956ed6ccc1f376f78ba56>.
> (plus additional fix to the fix).
> Marco and Mia run extensive tests to assess that we are not missing
> anything in 80X.
> The reasons are complex, and related to the way the update works and how
> segments are merged.
> As different code run in HLT and Reco (you know grouped vs classic Ckf),
> some differences may be observed.

Vincenzo

Thank you for the clarification.
Please update the PR description
It currently says " No regression expected", which is not quite correct.

Maybe Marco and Mia can share the diffs from the extensive tests.

**Comment by mtosi** [comment]
running on data I found the following
numberofvalidrechitspertrack_gentk_iter2merged

globalefficiencies_iter2merged

**Comment by cvuosalo** [comment]
An extended test of workflow 1313.0_QCD_Pt_3000_3500_13 with 70 events against baseline CMSSW_8_1_X_2016-02-18-2300 shows a little jitter in about 150 RECO quantities. There also tiny changes in DQM plots similar to those shown above, with the addition of tiny differences in CtaggerTag and Egamma plots. Examples of the largest differences are shown below.

tagsip
escmatch

**Comment by cvuosalo** [comment]
+1

For #13386 5e5aa84c8503fd41406f3b00a8b03b298853e2a8

Bug fix in the handling of the cluster charge cut in the trajectory, plus some code clean-up.

The code changes are satisfactory. Jenkins tests against baseline CMSSW_8_1_X_2016-02-19-2300 show some tiny, insignificant differences, as discussed above. Extended tests of workflows 1313.0_QCD_Pt_3000_3500_13 and 25202.0_TTbar_13 with 70 events each against baseline CMSSW_8_1_X_2016-02-18-2300 also show similar, tiny, insignificant differences, as shown above. Memory usage and CPU time are not changed appreciably.

Full extended test comparisons are attached:
[pr13386test.gz](https://github.com/cms-sw/cmssw/files/143341/pr13386test.gz)

**Comment by mmusich** [comment]
+1
AlCa related changes are only in CondFormats:  `CondFormats/SiStripObjects/src/SiStripNoises.cc`
@ggovi please have a look

**Comment by VinInn** [comment]
@ggovi, please

**Pull request merged**
