### PR TITLE
phase2-sim155 Update the scripts to enable run on new scenarios of Phase2 geometry

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Update the scripts to enable run on new scenarios of Phase2 geometry

#### PR validation:

Use the scripts to analyse all new Phase2 scenarios

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

No needs to repeat the test. The problem #44666 is known and will be fixed soon.

**Comment by antoniovilela** [comment]
please test
   - Let's refresh in any case.

**Comment by rappoccio** [comment]
+1

**Pull request merged**
