### PR TITLE
Removed JetIdCleaning from SUSY path names (CMSHLT-601 for 76X)

### PR DESCRIPTION
**Pull request by mrcarver**

### CODE REVIEW

**Comment by smuzaffar** [comment]
@cmsbuild, please test

**Comment by mrcarver** [comment]
I think there is something strange with why this test failed. The only update I made for this PR was to update a string a python file from the /src/HLTriggerOffline directory which should have no effect on the reconstruction step of the add on test. Could you please investigate this a bit further and advise on how to continue? Thanks

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1
provided it passes the tests

**Comment by smuzaffar** [comment]
please test

**Comment by davidlange6** [comment]
+1

**Pull request merged**
