### PR TITLE
[DD4hep] Final Changes to Replace tbb with std - requires a DD4hep update

### PR DESCRIPTION
**Pull request by ianna**
#### PR description:

* Final changes that replace tbb with std

Note: requires https://github.com/AIDASoft/DD4hep/pull/723 to be merged in DD4hep master.

```log
TimeModule> 1 1 test DDCMSDetector 1.77687
TimeModule> 1 1 testVectors DDTestVectors 0.000743151
TimeModule> 1 1 testDump DDTestDumpFile 0.47807
TimeModule> 1 1 testGeoIter DDTestDumpGeometry 6.12371
TimeModule> 1 1 p PathStatusInserter 5.60284e-05
TimeModule> 1 1 TriggerResults TriggerResultInserter 2.81334e-05
TimeEvent> 1 1 8.38048
MemoryReport> Peak virtual size 812.355 Mbytes
rss = 247.629
```

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by ianna** [comment]
hold

**Comment by ianna** [comment]
code check failures are expected - this requires an external update

**Comment by mrodozov** [comment]
please test with cms-sw/cmsdist#6315, cms-sw/cmssw#31821

**Comment by mrodozov** [comment]
So I tried to see the order but the test doesn't start since the code-checks doesn't work

**Comment by ianna** [comment]
> So I tried to put them in order but the test doesn't start since the code-checks requirements are not there

@mrodozov - Thanks! I've updated it, that should fix an un-mergeable conflict. There are actually three PRs needed. I'll update this information on the cmsdist PR.

**Comment by ianna** [comment]
merged in #31879

**Pull request closed without merging**
