### PR TITLE
Fix unused vars warnings in Reco pkgs

### PR DESCRIPTION
**Pull request by mrodozov**
Fix the warnings listed here 
https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc6_amd64_gcc630/CMSSW_9_4_X_2017-10-09-2300/RecoParticleFlow/PFProducer
https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc6_amd64_gcc630/CMSSW_9_4_X_2017-10-09-2300/RecoEcal/EgammaCoreTools

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/20876	ac31425
- technical; unused variables appear to be there from past developments or debugs no longer present/necessary
- jenkins tests pass

**Comment by davidlange6** [comment]
+1

**Pull request merged**
