### PR TITLE
Phase2-gem53 Preparation for a new muon scenario with GE0 rather than ME0

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Preparation for a new muon scenario with GE0 rather than ME0

#### PR validation:

Tested using a configuration in Geometry/MuonCommonData/test

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@slomeo @watson-ij I have made this PR in view of Ian's message about making GE0 rather than ME0 for future muon scenario. There is a cfi file Geometry/MuonCommonData/python/testGE0.xml to test the scenario. It surely works for SIM step. I wonder about the RECO step. Could one of you test that part utilizing this PR

**Comment by watson-ij** [comment]
Hi @bsunanda based on the geometry dump code, it looks like the reco geometry is building correctly. The RECO won't fully run with GE0 until I make some updates though, e.g. layers 3-6 of GE0 won't currently be used in the GEM emap, and upstream of RecoLocal, the Muon geometry won't build with GE0, for instance. I'm currently working on this.

(Looking just through the GEMSpecs/MuonNumbering) I'm not sure I understand what the difference between this geometry and the previous GE0 geometry you build for us is though? From conversations with @jshlee, the default we would eventually want is GE0 with the 16 eta partition with the GE2/1, but it looks like we still use the 8 partition version here. Im also not sure how the muon numbering is working, since it looks like we've gone back to the m0_* variables in this version, while the previous version integrated GE0 to use the mg_* variables?

**Comment by bsunanda** [comment]
@watson-ij I changed from 8 strip to 16 strip version for GE21. I do not think mg_* vs m0_* is an issue.  Please make the changes in the Reco code and let me know.

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by kpedro88** [comment]
+upgrade
just some xml and test files, no complete scenario yet

**Comment by cvuosalo** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
