### PR TITLE
Update HLT menu to V3.0 (101X)

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
Update HLT menu to V3.0 (101X)
Based on CMSSW_10_1_7.
Does not change the HLT menu used for production, @relval2018, only development HLT menus.

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
backport of #23729

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by fabiocos** [comment]
+1

changes do not affect the frozen 2018v21 menu provided in 10_1_7, they further update the GRun menu which was anyway already updated in 10_1_7

**Pull request merged**
