### PR TITLE
New STXS Stage 1.1

### PR DESCRIPTION
**Pull request by yhaddad**
Adding the new STXS stage 1.1 categorisation for Higgs analyses following the recommendations of Higgs Cross Section Working Group [1].
[1] - https://twiki.cern.ch/twiki/bin/view/LHCPhysics/LHCHXSWGFiducialAndSTXS#Stage_1_1

### CODE REVIEW

**Comment by efeyazgan** [comment]
@intrepid42 @xjanssen could you please take a look at this? thanks.

**Comment by intrepid42** [comment]
Hi, I see a bunch of HepMC calls so that this would not be accepted for a plugin by Rivet core. This can be a problem if the HTXS code is supposed to be the base for official Higgs Rivet analyses.
Otherwise, no problem to run this ATLAS/CMS-internal. I assume the correct physics function was validated by the LHCHXSWG?

**Comment by yhaddad** [comment]
This wasn't meant to be an official Rivet analysis, but rather just a tool to have the STXS classification as defined in [1]. The physics function was indeed validated by the LHCHXSWG.

[1] - https://gitlab.cern.ch/LHCHIGGSXS/LHCHXSWG2/STXS

**Comment by efeyazgan** [comment]
please test

**Comment by peruzzim** [comment]
could GEN please complete the review of this PR? it's needed for UL and next re-nano

**Comment by efeyazgan** [comment]
+1

**Comment by peruzzim** [comment]
@yhaddad could you please backport this to 10_2_X? Thanks

**Comment by janekbechtel** [comment]
Hi, thanks for this PR! We will need the updated version timely for production of filtered GEN-SIM events for H->tautau. We noticed a (what we believe is) a typo in the official LHCHXSWG code (*) which you took over (**). I believe this should be "505" instead of "405". Could you fix this in the PR?

(*) https://gitlab.cern.ch/LHCHIGGSXS/LHCHXSWG2/STXS/blob/master/HiggsTemplateCrossSections.h#L98
(**) https://github.com/cms-sw/cmssw/blob/965d6d93e608daa6e76407b5dad0809f99a9aeee/SimDataFormats/HTXS/interface/HiggsTemplateCrossSections.h#L142

**Comment by yhaddad** [comment]
@janekbechtel nicely spotted! It is indeed a typo. 
Now it fixed in the PR. I will let HXSWG about this issue. Thanks.

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
@efeyazgan @qliphy @alberto-sanchez any comment or objection? Otherwise the nanoAOD preparation would benefit from this to be merged asap

**Comment by peruzzim** [comment]
hello, sorry to come back on this, could GEN please review? then we need this backported also to 10_6_X and 10_2_X (should be trivial backports)

**Comment by efeyazgan** [comment]
+1

**Comment by peruzzim** [comment]
@yhaddad it looks like unfortunately you forgot to update the HTXS::HiggsClassification class here:
https://github.com/cms-sw/cmssw/blob/bf8f7eeb27559568305638e7599cf59186706824/SimDataFormats/HTXS/interface/HiggsTemplateCrossSections.h#L298
and here:
https://github.com/cms-sw/cmssw/blob/bf8f7eeb27559568305638e7599cf59186706824/SimDataFormats/HTXS/interface/HiggsTemplateCrossSections.h#L316

**Comment by yhaddad** [comment]
@perrozzi you're right! Sorry, I have inadvertently forgotten to update these two functions. This should be fixed now.

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
@perrozzi @efeyazgan @qliphy @alberto-sanchez is this PR now ready for integration? Is there any validation report?

**Comment by peruzzim** [comment]
@yhaddad please also backport to 10_6_X

**Comment by yhaddad** [comment]
please check #26847 for backport to 10_6_X

**Comment by qliphy** [comment]
@fabiocos   This PR looks good to me.    
About validations,  @yhaddad have you done any checks?

**Comment by fabiocos** [comment]
@yhaddad @qliphy as this is needed for backport for the UL nanoAOD part, it would be good to converge quickly if possible

**Comment by yhaddad** [comment]
@qliphy I have done basics checks: if the modification doesn't break any existing code and if it runs as it should. Is there any additional check you me to do?

**Comment by qliphy** [comment]
+1

**Comment by fabiocos** [comment]
+1

all the changes observed are concentrated in NANO workflows

**Pull request merged**
