### PR TITLE
2024 Data RelVals and `InputInfo` Events Skimming (actually) Working

### PR DESCRIPTION
**Pull request by AdrianoDee**
#### PR description:

This PR proposes few things:

1. the introduction of a new script `das-up-to-nevents.py` that, given in input a dataset name, allows to get the list of files corresponding to N events. The dataset is also automatically skimmed to include only the run and the lumis from the latest and greatest Golden data certification json;

2. a fix to the fact that  the `InputInfo` class, while accepting as input a variable `events` does not really use it to skim the result of the das query. It's only really used in a [log](https://github.com/AdrianoDee/cmssw/blob/1d62219e28a38c574b9cc9af52ec07d34ab5303e/Configuration/PyReleaseValidation/python/MatrixReader.py#L389). I find it ambiguous and a bit confusing. In practice it also means that for 2023 and 2022 RelVals we have been running on O(few millions) events per pre-release (see e.g. [CMSSW_14_1_0_pre3__Data_Run3_2023_Data-RunEGamma2023D](https://cms-pdmv-prod.web.cern.ch/relval/relvals?prepid=CMSSW_14_1_0_pre3__Data_Run3_2023_Data-RunEGamma2023D-00001&shown=1082367&page=0&limit=50)). While this is nice in terms of being able to do that (kudos on computing!) it usually slows down a lot the RelVal production. This leverages on the script introduced in (1).

3. the addition of 2024 data RelVals for Eras from B to F as `standard` wfs with `2024.*` prefix. These are run with:
   - `Run3_2024` era; 
   - `HLT:@relval2024` (currently pointing at GRun);
   - running on 50k events using the script in (1) and the script in (2)

4. a new set of RelVals under `relvals_data_highstats.py` that should include all the higher statistics data RelVals workflows with 150k,250k,500k and 1M events. For the moment it includes only the 2024 wfs. This set is not turned on by default to avoid to have an over crowded matrix.

All the needed input RAW samples have been copied via Rucio at `T2_CH_CERN`.
 
#### PR validation:

Running (e.g.) `runTheMatrix.py -w data,standard -l 12024.003015, 2024.00405, 2024.007005, 2024.0091, 2024.012005, 2024.013025, 2024.10305, 2024.108005, 2024.108015, 2024.210025, 2024.211015, 2024.2111, 2024.212025, 2024.213015, 2024.214025, 2024.21405, 2024.303015, 2024.310025, 2024.31305, 2024.3141, 2024.400005, 2024.402015`

### CODE REVIEW

**Comment by AdrianoDee** [comment]
plese test

**Comment by AdrianoDee** [comment]
please test

**Comment by AdrianoDee** [comment]
test parameters:
- workflows = 143.0011,143.0021,143.0031,143.0041,143.0051,143.0061,143.0071,143.0081,143.0091,143.0101,143.0111,143.0121,143.0131,143.0141,143.0151,143.0161,143.0171,143.0181,143.0191,143.0201,143.0211,143.0221,143.0231,143.0241,143.0251,143.0261,143.0271,143.0281,143.0291,143.0301

**Comment by AdrianoDee** [comment]
please test
(running only with the 100k wfs for which I have copied the samples at `T2_CH_CERN`)

**Comment by AdrianoDee** [comment]
please test

**Comment by AdrianoDee** [comment]
test parameters:
- workflows = 143.0011

**Comment by AdrianoDee** [comment]
please test
(let's go simple, I can't reproduce the DAS error locally)

**Comment by smuzaffar** [comment]
please test

**Comment by AdrianoDee** [comment]
please test
(all files should be at `T2_CH_CERN` now)

**Comment by AdrianoDee** [comment]
please test

- I can't really reproduce the error offline, but it seems, [from the error report](https://cmssdt.cern.ch/jenkins/job/ib-run-pr-relvals/44760/consoleText), that there's an additional newline coming from the das query that is making `das-up-to-nevents.py` fail. Hopefully this should fix it.

**Comment by AdrianoDee** [comment]
test parameters:

**Comment by AdrianoDee** [comment]
please test

**Comment by AdrianoDee** [comment]
please abort

**Comment by AdrianoDee** [comment]
please test

**Comment by AdrianoDee** [comment]
please test

**Comment by AdrianoDee** [comment]
(need to check the logs again to understand what's going on)

**Comment by AdrianoDee** [comment]
test parameters:

- workflows = 143.0011

**Comment by AdrianoDee** [comment]
please test

**Comment by AdrianoDee** [comment]
please test

**Comment by AdrianoDee** [comment]
test parameters:

**Comment by AdrianoDee** [comment]
please test

**Comment by AdrianoDee** [comment]
please abort

**Comment by AdrianoDee** [comment]
please test

**Comment by AdrianoDee** [comment]
please abort

**Comment by AdrianoDee** [comment]
please test

**Comment by AdrianoDee** [comment]
please test

**Comment by AdrianoDee** [comment]
test_parameters:
- workflow_opts = -w data
- workflows = 2024.003015, 2024.00405, 2024.007005, 2024.0091, 2024.012005, 2024.013025, 2024.10305, 2024.108005, 2024.108015, 2024.210025, 2024.211015, 2024.2111, 2024.212025, 2024.213015, 2024.214025, 2024.21405, 2024.303015, 2024.310025, 2024.31305, 2024.3141, 2024.400005, 2024.402015

**Comment by AdrianoDee** [comment]
test_parameters:
- workflow_opts = -w data, standard
- workflows = 2024.003015, 2024.00405, 2024.007005, 2024.0091, 2024.012005, 2024.013025, 2024.10305, 2024.108005, 2024.108015, 2024.210025, 2024.211015, 2024.2111, 2024.212025, 2024.213015, 2024.214025, 2024.21405, 2024.303015, 2024.310025, 2024.31305, 2024.3141, 2024.400005, 2024.402015

**Comment by AdrianoDee** [comment]
test parameters:
- workflow_opts = -w data
- workflows = 2024.003015, 2024.00405, 2024.007005, 2024.0091, 2024.012005, 2024.013025, 2024.10305, 2024.108005, 2024.108015, 2024.210025, 2024.211015, 2024.2111, 2024.212025, 2024.213015, 2024.214025, 2024.21405, 2024.303015, 2024.310025, 2024.31305, 2024.3141, 2024.400005, 2024.402015

**Comment by AdrianoDee** [comment]
please test

**Comment by AdrianoDee** [comment]
test parameters:
- workflow_opts = -w data, standard
- workflows = 2024.003015, 2024.00405, 2024.007005, 2024.0091, 2024.012005, 2024.013025, 2024.10305, 2024.108005, 2024.108015, 2024.210025, 2024.211015, 2024.2111, 2024.212025, 2024.213015, 2024.214025, 2024.21405, 2024.303015, 2024.310025, 2024.31305, 2024.3141, 2024.400005, 2024.402015

**Comment by AdrianoDee** [comment]
please test

**Comment by AdrianoDee** [comment]
test parameters:
- workflow_opts = -w data, standard
- workflows = 2024.003015, 2024.00405, 2024.007005, 2024.0091

**Comment by AdrianoDee** [comment]
please test

**Comment by AdrianoDee** [comment]
test parameters:

**Comment by AdrianoDee** [comment]
please test

**Comment by AdrianoDee** [comment]
+pdmv

**Comment by srimanob** [comment]
+Upgrade

**Comment by mandrenguyen** [comment]
+1

**Comment by AdrianoDee** [comment]
@smuzaffar let me have a look

**Pull request merged**
