### PR TITLE
Protecting E/gamma Scale and Smearing from "nan" energies : 102X

### PR DESCRIPTION
**Pull request by Sam-Harper**
102X flavour of https://github.com/cms-sw/cmssw/pull/24093

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/24154	2e48433
- the implementation is in line with the PR description. This presently should affect only very rare cases with NaN inputs and (most likely) leading to a crash as reported in https://its.cern.ch/jira/browse/CMSCOMPPR-3266. 
    - the backport from the master is correct: the same topic branch is used
- jenkins tests pass and comparisons with the baseline show no differences

**Comment by slava77** [comment]
backport of #24093

**Comment by slava77** [comment]
type bugfix

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/24151	289f958
- the implementation is in line with the PR description. This presently should affect only very rare cases with NaN inputs and (most likely) leading to a crash as reported in https://its.cern.ch/jira/browse/CMSCOMPPR-3266. 
    - the backport from the master is correct: the same code changes are applied as in https://github.com/cms-sw/cmssw/pull/24093	2e48433
- jenkins tests pass and comparisons with the baseline show no differences

**Comment by fabiocos** [comment]
+1

**Pull request merged**
