### PR TITLE
PPS: update of era modifiers

### PR DESCRIPTION
**Pull request by jan-kaspar**
#### PR description:

This PR proposes a tiny reorganisation of (CT)PPS era modifiers in order to avoid mistakes and provide flexibility needed for Run 3. The motivation and the selected solution are described in https://github.com/cms-sw/cmssw/issues/33080 and [PPS SW meeting presentation on 10 Mar 2021](https://indico.cern.ch/event/1016318/contributions/4265132/attachments/2205339/3731168/kaspar_PPS_SW_meeting.pdf). In brief, the changes include:
  * new era modifier `ctpps` introduced - turned on for all eras where PPS was/is active
  * the meaning of `ctpps_2016` is restricted to 2016 only

This update shall be transparent whenever `Run2_20XY` or `Run3` modifier chains are used.

This is a technical update, no change in test results expected.

No backport is foreseen.

#### PR validation:

Below, two comparisons before this PR (blue) vs. after the PR (red dashed) are attached:
  * direct simulation: [dirsim_cmp.pdf](https://github.com/cms-sw/cmssw/files/6187897/dirsim_cmp.pdf)
  * reconstruction: [reco_cmp.pdf](https://github.com/cms-sw/cmssw/files/6187898/reco_cmp.pdf)
 
No change observed, as expected.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by jan-kaspar** [comment]
I've analysed most of the failing tests from https://github.com/cms-sw/cmssw/pull/33250#issuecomment-804921039. All of them have `Run3` era declared.

As far as I understand, the test failures are not due to a bug in this PR, but due to the fact that this PR fixes a bug which prevented observing the problem earlier. It has to do with this line:
  https://github.com/cms-sw/cmssw/blob/master/Geometry/VeryForwardGeometry/python/geometryRPFromDB_cfi.py#L19
Up to now, by mistake, `isRun2` was set to `True` even if `Run3` era was declared. This is now fixed and it exposes the upstream problem - the Run3 geometry which is now in GT(s) is in fact still the old Run2 geometry. Because of the differences introduced in #31484, parsing Run2 geometry with `isRun2=false` yields problems, namely the diamond detectors are assigned wrong ids - and this leads to the exception seen in the logs.

This has not been intercepted by my tests since they use the geometry loaded from XML files - and this is correct.

As far as I understand, we need urgently to upload the Run3 (diamond) geometry to DB, otherwise we are stuck.

@forthommel @wpcarvalho @clemencia : can you please double check my assessment and, if correct, could you please update the Run3 DB and GTs (to be compatible with the XML files in the CMSSW code)?

@fabferro FYI

**Comment by makortel** [comment]
> As far as I understand, we need urgently to upload the Run3 (diamond) geometry to DB, otherwise we are stuck.

FYI @cms-sw/geometry-l2

**Comment by silviodonato** [comment]
FYI @cms-sw/alca-l2

**Comment by jan-kaspar** [comment]
> @jan-kaspar why the comparisons for the "direct simulation" posted in the PR description do not show differences in the 2021 case? If I understand correctly your [explanation for the origin of the failing tests](https://github.com/cms-sw/cmssw/pull/33250#issuecomment-806529096), without this PR you should have picked the run2 geometry for that test, while with this PR the correct run3 geometry (in your case, as taken from the xml file) should have been used instead.

Unlike other WFs, the "direct" simulation loads the geometry from XML files (where the Run3 geometry is already correct):
  https://github.com/cms-sw/cmssw/blob/master/Validation/CTPPS/python/simu_config/year_2021_cff.py#L38

> (By the way, for the "reconstruction" case there is no "2021" run3 comparison in your plots)

This comparison may be better called "LHC data reco" comparison as it is run on real LHC data. Obviously, they do not yet exist for Run3, thus they are missing there.

**Comment by wpcarvalho** [comment]
> @forthommel @wpcarvalho @clemencia : can you please double check my assessment and, if correct, could you please update the Run3 DB and GTs (to be compatible with the XML files in the CMSSW code)?
> 
> @fabferro FYI

I started looking at the problem and hope we can provide a solution soon.

**Comment by civanch** [comment]
@cvuosalo , in the new Run-3 geometry we have also diamond detectors or not yet?

**Comment by cvuosalo** [comment]
@civanch The Run 3 simulation geometry for 11_3 contains a PPS diamond detector assembly.

**Comment by perrotta** [comment]
@jan-kaspar @wpcarvalho : having the updated PPS run3 geometry in the GT goes beyond the limited scope of this PR.
Next week, ~ on Tuesday, is the deadline for the last open pre-release of 11_3, and it would be a pity if that geometry cannot be loaded by then. Do you have this schedule in mind for your update? I think that the integration of this PR could follow shortly after it.

**Comment by jan-kaspar** [comment]
> @jan-kaspar @wpcarvalho : having the updated PPS run3 geometry in the GT goes beyond the limited scope of this PR.
> Next week, ~ on Tuesday, is the deadline for the last open pre-release of 11_3, and it would be a pity if that geometry cannot be loaded by then. Do you have this schedule in mind for your update? I think that the integration of this PR could follow shortly after it.

I agree, updating the geometry is conceptually unrelated to this PR. This PR just unveils a problem which should have been fixed earlier. This problem now blocks this PR and other PPS developments and therefore, I agree, the geometry problem should be addressed quasi immediately. We discussed it in the PPS SW meeting yesterday and indeed we gave this fix the highest priority. 
 @wpcarvalho has made progress in providing a solution. I let him confirm the timeline, but I hope to be on time for the Tuesday deadline. I don't mind if this PR delayed because of this.

**Comment by wpcarvalho** [comment]
Sorry for not replying earlier, for some unknown reason the GitHub notifications started to go to my Spam folder. 
I have build a geometry file which may fix the problem but have to check if it is correctly done and if any validation is needed. I will contact @cvuosalo in a separate thread to clarify this issue.

**Comment by perrotta** [comment]
test parameters:

workflow = 11725.0,11925.0
pull_request = #33404

**Comment by perrotta** [comment]
please test

**Comment by silviodonato** [comment]
This PR has been included in #33415

**Comment by perrotta** [comment]
-1
(Now included in #33415, please close this PR)

**Comment by jan-kaspar** [comment]
Closing as included in #33415

**Pull request closed without merging**
