### PR TITLE
Changed eta ZS mask for null-word check

### PR DESCRIPTION
**Pull request by panoskatsoulis**
Just updated the file DQM/L1TMonitor/python/L1TStage2BMTF_cff.py to include the valid BMTF ZS masks.

### CODE REVIEW

**Comment by thomreis** [comment]
please test

**Comment by thomreis** [comment]
@dmitrijus @jfernan2 please sign.

**Comment by thomreis** [comment]
@dmitrijus @jfernan2 please sign. We would like to get the open PRs into 10_1.

**Comment by dmitrijus** [comment]
+1

**Comment by fabiocos** [comment]
@panoskatsoulis in which test is this change supposed to show its effect, if any?

**Comment by thomreis** [comment]
@fabiocos this is for the online DQM ZS monitoring. The ZS menu in the DQM module must be the same than the one used in the FW. This PR updates the ZS menu used in the DQM to the one used in the FW.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
