### PR TITLE
Make Process.prune() to prune also Tasks, and add --prune option to edmConfigDump

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

This PR is a (partial) follow-up on issue #28172. In addition to the title, this PR makes `edmConfigDump` to use `ArgumentParser` and `print_function`.

#### PR validation:

Unit tests run.

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by Dr15Jones** [comment]
+1

**Comment by wddgit** [comment]
I did not carefully read the code. This is a question. Does this account for the fact that a Task can be associated with the Schedule as an alternative to associating it with a Path, EndPath, or Sequence?

**Comment by makortel** [comment]
> I did not carefully read the code. This is a question. Does this account for the fact that a Task can be associated with the Schedule as an alternative to associating it with a Path, EndPath, or Sequence?

Thanks David, that fact is not accounted for (and need to be fixed). I'll abort the tests to prevent accidental "fully signed".

**Comment by makortel** [comment]
@cmsbuild, please abort

**Comment by fabiocos** [comment]
@makortel thanks, I see that you have updated edmConfigDump so as to be compatible with python3, I was about to do the same in order to validate the fix for DataProcessing

**Comment by Dr15Jones** [comment]
hold

**Comment by makortel** [comment]
Tasks associated directly to `cms.Schedule` are now kept.

**Comment by Dr15Jones** [comment]
unhold

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by fabiocos** [comment]
the failures are unrelated to this PR, anyway a fix for most of the problems should have already entered

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
please test

now the number of failing tests should be definitely smaller, and anyway unrelated to this PR
@Dr15Jones any further comment on this?

**Comment by Dr15Jones** [comment]
+1

**Comment by fabiocos** [comment]
@makortel I am sorry, I overlooked the fact that this PR and #28184 were in conflicts in Config.py .
As far as I can see keeping your changes should not be an issue provided that the ```dumpPython()``` calls are cleaned. Looking at the Resolve conflicts proposal I see that the resolution looks simple, but then a further update to two calls of ```dumpPython()``` is needed. I may do it, or let you adjust if you prefer.

**Comment by makortel** [comment]
@fabiocos No problem, I'll rebase.

**Comment by fabiocos** [comment]
of course the unit tests failures are irrelevant as unrelated to this PR.

**Comment by makortel** [comment]
Rebased on top of CMSSW_11_0_X_2019-10-17-2300

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by Dr15Jones** [comment]
+1
the unit test failures are unrelated to this pull request

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Pull request merged**
