### PR TITLE
Fireworks 11_2_X Updates for GEM detector visualization

### PR DESCRIPTION
**Pull request by alja**
This PR adds checks for valid GEMDetId and draws simplified GEM Detector in 3D and projected views.

Screen Shot 2020-10-28 at 10 54 16 AM
Screen Shot 2020-10-28 at 11 11 35 AM

### CODE REVIEW

**Comment by alja** [comment]
@jshlee Please check.

**Comment by alja** [comment]
+1

**Comment by alja** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
