### PR TITLE
CondTools/L1Trigger/plugins: change return type of ESProducers to unique_ptr

### PR DESCRIPTION
**Pull request by gartung**

### CODE REVIEW

**Comment by gartung** [comment]
@Dr15Jones

**Comment by thomreis** [comment]
please test

**Comment by Dr15Jones** [comment]
looks good to me

**Comment by ggovi** [comment]
+1

**Comment by fabiocos** [comment]
@thomreis @rekovic @nsmith- could you please have a look and sign in case or comment?

**Comment by thomreis** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
