### PR TITLE
EMTF and uGMT shower triggers (HadronicShowerTrigger-5)

### PR DESCRIPTION
**Pull request by dildick**
#### PR description:

Following #33446, I introduce the hadronic shower trigger emulator in the EMTF and uGMT for Run-3. Most of the logic resides in `SectorProcessorShower`, so that we retain maximum flexibility to adjust the algorithms during data taking. Both emulators are standalone and do not interfere with existing emulators. Currently, there are not yet included in any workflow.

#### PR validation:

Ran `runTheMatrix -l limited`. There should be no differences in any workflow.

```
4.22_RunCosmics2011A+RunCosmics2011A+RECOCOSD+ALCACOSD+SKIMCOSD+HARVESTDC Step0-DAS_ERROR Step1-NOTRUN Step2-NOTRUN Step3-NOTRUN Step4-NOTRUN  - time date Wed Apr 28 11:33:51 2021-date Wed Apr 28 11:33:51 2021; exit: 1 0 0 0 0
4.53_RunPhoton2012B+RunPhoton2012B+HLTD+RECODR1reHLT+HARVESTDR1reHLT Step0-DAS_ERROR Step1-NOTRUN Step2-NOTRUN Step3-NOTRUN  - time date Wed Apr 28 11:33:51 2021-date Wed Apr 28 11:33:51 2021; exit: 1 0 0 0
5.1_TTbar+TTbarFS+HARVESTFS Step0-PASSED Step1-PASSED  - time date Wed Apr 28 11:39:49 2021-date Wed Apr 28 11:33:52 2021; exit: 0 0
7.3_CosmicsSPLoose_UP18+CosmicsSPLoose_UP18+DIGICOS_UP18+RECOCOS_UP18+ALCACOS_UP18+HARVESTCOS_UP18 Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Wed Apr 28 11:45:14 2021-date Wed Apr 28 11:33:52 2021; exit: 0 0 0 0 0
8.0_BeamHalo+BeamHalo+DIGICOS+RECOCOS+ALCABH+HARVESTCOS Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Wed Apr 28 11:44:38 2021-date Wed Apr 28 11:33:53 2021; exit: 0 0 0 0 0
9.0_Higgs200ChargedTaus+Higgs200ChargedTaus+DIGI+RECO+HARVEST Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED  - time date Wed Apr 28 11:51:28 2021-date Wed Apr 28 11:33:53 2021; exit: 0 0 0 0
25.0_TTbar+TTbar+DIGI+RECOAlCaCalo+HARVEST+ALCATT Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Wed Apr 28 12:04:59 2021-date Wed Apr 28 11:39:49 2021; exit: 0 0 0 0 0
135.4_ZEE_13+ZEEFS_13+HARVESTUP15FS+MINIAODMCUP15FS Step0-PASSED Step1-PASSED Step2-PASSED  - time date Wed Apr 28 11:53:09 2021-date Wed Apr 28 11:44:39 2021; exit: 0 0 0
136.731_RunSinglePh2016B+RunSinglePh2016B+HLTDR2_2016+RECODR2_2016reHLT_skimSinglePh_HIPM+HARVESTDR2 Step0-DAS_ERROR Step1-NOTRUN Step2-NOTRUN Step3-NOTRUN  - time date Wed Apr 28 11:45:15 2021-date Wed Apr 28 11:45:14 2021; exit: 1 0 0 0
136.7611_RunJetHT2016E_reminiaod+RunJetHT2016E_reminiaod+REMINIAOD_data2016_HIPM+HARVESTDR2_REMINIAOD_data2016_HIPM Step0-DAS_ERROR Step1-NOTRUN Step2-NOTRUN  - time date Wed Apr 28 11:45:15 2021-date Wed Apr 28 11:45:15 2021; exit: 1 0 0
136.793_RunDoubleEG2017C+RunDoubleEG2017C+HLTDR2_2017+RECODR2_2017reHLT_skimDoubleEG_Prompt+HARVEST2017 Step0-DAS_ERROR Step1-NOTRUN Step2-NOTRUN Step3-NOTRUN  - time date Wed Apr 28 11:45:16 2021-date Wed Apr 28 11:45:15 2021; exit: 1 0 0 0
136.8311_RunJetHT2017F_reminiaod+RunJetHT2017F_reminiaod+REMINIAOD_data2017+HARVEST2017_REMINIAOD_data2017 Step0-DAS_ERROR Step1-NOTRUN Step2-NOTRUN  - time date Wed Apr 28 11:45:16 2021-date Wed Apr 28 11:45:16 2021; exit: 1 0 0
136.8523_RunJetHT2018C_nanoULremini+RunJetHT2018C_nanoULremini+NANOEDM2018_106Xv2+HARVESTNANOAOD2018_106Xv2 Step0-DAS_ERROR Step1-NOTRUN Step2-NOTRUN  - time date Wed Apr 28 11:45:17 2021-date Wed Apr 28 11:45:16 2021; exit: 1 0 0
136.874_RunEGamma2018C+RunEGamma2018C+HLTDR2_2018+RECODR2_2018reHLT_skimEGamma_Offline_L1TEgDQM+HARVEST2018_L1TEgDQM Step0-DAS_ERROR Step1-NOTRUN Step2-NOTRUN Step3-NOTRUN  - time date Wed Apr 28 11:45:17 2021-date Wed Apr 28 11:45:17 2021; exit: 1 0 0 0
136.88811_RunJetHT2018D_reminiaodUL+RunJetHT2018D_reminiaodUL+REMINIAOD_data2018UL+HARVEST2018_REMINIAOD_data2018UL Step0-DAS_ERROR Step1-NOTRUN Step2-NOTRUN  - time date Wed Apr 28 11:45:18 2021-date Wed Apr 28 11:45:17 2021; exit: 1 0 0
140.53_RunHI2011+RunHI2011+RECOHID11+HARVESTDHI Step0-DAS_ERROR Step1-NOTRUN Step2-NOTRUN  - time date Wed Apr 28 11:45:18 2021-date Wed Apr 28 11:45:18 2021; exit: 1 0 0
140.56_RunHI2018+RunHI2018+RECOHID18+HARVESTDHI18 Step0-DAS_ERROR Step1-NOTRUN Step2-NOTRUN  - time date Wed Apr 28 11:45:19 2021-date Wed Apr 28 11:45:18 2021; exit: 1 0 0
158.01_HydjetQ_reminiaodPbPb2018_INPUT+HydjetQ_reminiaodPbPb2018_INPUT+REMINIAODHI2018PPRECOMB+HARVESTHI2018PPRECOMINIAOD Step0-DAS_ERROR Step1-NOTRUN Step2-NOTRUN  - time date Wed Apr 28 11:45:19 2021-date Wed Apr 28 11:45:19 2021; exit: 1 0 0
1306.0_SingleMuPt1_UP15+SingleMuPt1_UP15+DIGIUP15+RECOUP15+HARVESTUP15 Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED  - time date Wed Apr 28 12:02:50 2021-date Wed Apr 28 11:45:19 2021; exit: 0 0 0 0
1325.81_TTbar_13_106Xv1NanoAODINPUT+TTbar_13_106Xv1NanoAODINPUT+NANOEDMMC2017_106XMiniAODv1+HARVESTNANOAODMC2017_106XMiniAODv1 Step0-DAS_ERROR Step1-NOTRUN Step2-NOTRUN  - time date Wed Apr 28 11:51:29 2021-date Wed Apr 28 11:51:28 2021; exit: 1 0 0
1330.0_ZMM_13+ZMM_13+DIGIUP15+RECOUP15_L1TMuDQM+HARVESTUP15_L1TMuDQM+NANOUP15 Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Wed Apr 28 12:15:40 2021-date Wed Apr 28 11:51:29 2021; exit: 0 0 0 0 0
101.0_SingleElectronE120EHCAL+SingleElectronE120EHCAL Step0-PASSED  - time date Wed Apr 28 11:57:04 2021-date Wed Apr 28 11:53:09 2021; exit: 0
312.0_Pyquen_ZeemumuJets_pt10_2760GeV_2021+Pyquen_ZeemumuJets_pt10_2760GeV_2021+DIGIHI2021MIX+RECOHI2021MIX+HARVESTHI2021PPRECO Step0-FAILED Step1-NOTRUN Step2-NOTRUN Step3-NOTRUN  - time date Wed Apr 28 12:00:43 2021-date Wed Apr 28 11:57:05 2021; exit: 23808 0 0 0
25202.0_TTbar_13+TTbar_13+DIGIUP15_PU25+RECOUP15_PU25+HARVESTUP15_PU25+NANOUP15_PU25 Step0-PASSED Step1-FAILED Step2-NOTRUN Step3-NOTRUN Step4-NOTRUN  - time date Wed Apr 28 12:11:35 2021-date Wed Apr 28 12:00:44 2021; exit: 0 23808 0 0 0
1000.0_RunMinBias2011A+RunMinBias2011A+TIER0+SKIMD+HARVESTDfst2+ALCASPLIT Step0-DAS_ERROR Step1-NOTRUN Step2-NOTRUN Step3-NOTRUN Step4-NOTRUN  - time date Wed Apr 28 12:02:52 2021-date Wed Apr 28 12:02:50 2021; exit: 1 0 0 0 0
1001.0_RunMinBias2011A+RunMinBias2011A+TIER0EXP+ALCAEXP+ALCAHARVDSIPIXELCALRUN1+ALCAHARVD1+ALCAHARVD2+ALCAHARVD3+ALCAHARVD4+ALCAHARVD5 Step0-DAS_ERROR Step1-NOTRUN Step2-NOTRUN Step3-NOTRUN Step4-NOTRUN Step5-NOTRUN Step6-NOTRUN Step7-NOTRUN Step8-NOTRUN  - time date Wed Apr 28 12:02:52 2021-date Wed Apr 28 12:02:52 2021; exit: 1 0 0 0 0 0 0 0 0
10024.0_TTbar_13+2017+TTbar_13TeV_TuneCUETP8M1_GenSim+Digi+RecoFakeHLT+HARVESTFakeHLT+ALCA+Nano Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED Step5-PASSED  - time date Wed Apr 28 12:36:01 2021-date Wed Apr 28 12:02:52 2021; exit: 0 0 0 0 0 0
10042.0_ZMM_13+2017+ZMM_13TeV_TuneCUETP8M1_GenSim+Digi+RecoFakeHLT+HARVESTFakeHLT+ALCA+Nano Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED Step5-PASSED  - time date Wed Apr 28 12:28:29 2021-date Wed Apr 28 12:05:00 2021; exit: 0 0 0 0 0 0
10224.0_TTbar_13+2017PU+TTbar_13TeV_TuneCUETP8M1_GenSim+DigiPU+RecoFakeHLTPU+HARVESTFakeHLTPU+Nano Step0-PASSED Step1-FAILED Step2-NOTRUN Step3-NOTRUN Step4-NOTRUN  - time date Wed Apr 28 12:23:30 2021-date Wed Apr 28 12:11:36 2021; exit: 0 23808 0 0 0
10824.0_TTbar_13+2018+TTbar_13TeV_TuneCUETP8M1_GenSim+Digi+RecoFakeHLT+HARVESTFakeHLT+ALCA+Nano Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED Step5-PASSED  - time date Wed Apr 28 12:38:29 2021-date Wed Apr 28 12:15:41 2021; exit: 0 0 0 0 0 0
11634.0_TTbar_14TeV+2021+TTbar_14TeV_TuneCP5_GenSim+Digi+Reco+HARVEST+ALCA Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Wed Apr 28 12:46:51 2021-date Wed Apr 28 12:23:30 2021; exit: 0 0 0 0 0
11634.911_TTbar_14TeV+2021_DD4hep+TTbar_14TeV_TuneCP5_GenSim+Digi+Reco+HARVEST+ALCA Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Wed Apr 28 12:55:47 2021-date Wed Apr 28 12:28:30 2021; exit: 0 0 0 0 0
12434.0_TTbar_14TeV+2023+TTbar_14TeV_TuneCP5_GenSim+Digi+Reco+HARVEST+ALCA Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Wed Apr 28 12:57:08 2021-date Wed Apr 28 12:36:02 2021; exit: 0 0 0 0 0
23234.0_TTbar_14TeV+2026D49+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14+DigiTrigger+RecoGlobal+HARVESTGlobal Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED  - time date Wed Apr 28 13:08:59 2021-date Wed Apr 28 12:38:30 2021; exit: 0 0 0 0
28234.0_TTbar_14TeV+2026D60+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14+DigiTrigger+RecoGlobal+HARVESTGlobal Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED  - time date Wed Apr 28 13:19:52 2021-date Wed Apr 28 12:46:52 2021; exit: 0 0 0 0
34634.0_TTbar_14TeV+2026D76+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14+DigiTrigger+RecoGlobal+HARVESTGlobal Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED  - time date Wed Apr 28 13:26:41 2021-date Wed Apr 28 12:55:47 2021; exit: 0 0 0 0
34834.999_TTbar_14TeV+2026D76PU_PMXS1S2PR+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14+PREMIX_PremixHLBeamSpot14PU+DigiTriggerPU+RecoGlobalPU+HARVESTGlobalPU Step0-PASSED Step1-FAILED Step2-NOTRUN Step3-NOTRUN Step4-NOTRUN  - time date Wed Apr 28 13:16:30 2021-date Wed Apr 28 12:57:09 2021; exit: 0 21504 0 0 0
250202.181_TTbar_13UP18+TTbar_13UP18+PREMIXUP18_PU25+DIGIPRMXLOCALUP18_PU25+RECOPRMXUP18_PU25+HARVESTUP18_PU25 Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Wed Apr 28 13:40:34 2021-date Wed Apr 28 13:09:00 2021; exit: 0 0 0 0 0
22 18 17 16 11 3 0 0 0 tests passed, 16 3 0 0 0 0 0 0 0 failed
```

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

@dinyar

### CODE REVIEW

**Comment by cecilecaillol** [comment]
please test

**Comment by dildick** [comment]
@cecilecaillol Could you also restart the tests here? Thanks.

**Comment by cecilecaillol** [comment]
please test

**Comment by cecilecaillol** [comment]
+l1

**Comment by civanch** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
