### PR TITLE
Use esConsumes in HcalRawToDigiGPU

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

Part of #31061.

#### PR validation:

Code compiles.

### CODE REVIEW

**Comment by makortel** [comment]
test parameters:
  - enable_tests = gpu

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by slava77** [comment]
+reconstruction

for https://github.com/cms-sw/cmssw/pull/36112	bda44a0 
- code changes are technical, in line with the PR title/description
- jenkins tests pass

**Comment by qliphy** [comment]
+1

**Pull request merged**
