### PR TITLE
HLT menu development for `14_0_X` (11/N) [`14_1_X`]

### PR DESCRIPTION
**Pull request by mmusich**
backport of https://github.com/cms-sw/cmssw/pull/46129

#### PR description:

Development of HLT menus for `CMSSW_14_0_X` (branch `CMSSW_14_1_X`): **this is the close-out PR for HLT development in the CMSSW_14_0_X cycle**.
   * This is the PR for the CMSSW_14_1_X branch, which will then be backported down to 14_0_X (the latter is the release cycle currently used for Run-3 HLT-menu development).
   * These updates correspond to the changes accumulated in the 14_0_X release cycle after the "V1.4" (last) menu for the 2024 pp data-taking period was released, and target the 2024 HIon and PRef data-taking as well as the first pp menu for 2025.
   
This update includes the integration of the following JIRA tickets:
- [CMSHLT-3335](https://its.cern.ch/jira/browse/CMSHLT-3335) [TSG/HIon] Clean-up HIon subtable from unused L1T seeds for 2024 data-taking

In addition, the following changes are included:
   * bbf469361766c9694c860323ae568350ee67798d: update of L1T HIon menu in TSG GTs to `L1Menu_CollisionsHeavyIons2024_v1_0_0_xml` ([CMSLITDPG-1314](https://its.cern.ch/jira/browse/CMSLITDPG-1314))
   * 3ae03d4be7594894a998b3409942abd8b5fe249f: update of L1T PRef menu in TSG GTs to `L1Menu_CollisionsPPRef2024_v1_0_0_xml` ([CMSLITDPG-1207](https://its.cern.ch/jira/browse/CMSLITDPG-1207))

#### PR validation:

TSG Integration tests.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

backport of https://github.com/cms-sw/cmssw/pull/46129 to the 2024 HIon production cycle (CMSSW_14_1_X)

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
type hlt-integration

**Comment by mmusich** [comment]
+hlt

**Comment by mmusich** [comment]
@cms-sw/orp-l2 please merge this,  we'll need shortly to push more changes to ease integration of more HIon and PRef tickets

**Comment by mmusich** [comment]
urgent

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
