### PR TITLE
Ecal laser alphas

### PR DESCRIPTION
**Pull request by depasse**
Replace PR Ecal laser alphas (#17234)
Laser alpha now Xtal by Xtal from a txt file (before, only a mean for Russian/Chinese Xtals).

Please test with cms-sw/cmsdist#2831 cms-bot command

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test with cms-sw/cmsdist#2831

**Comment by depasse** [comment]
Pb with FileInPath :

When I want to test the "fromFile" version (the byType works) :

$ cmsRun create_alpha_trivial_fromFILE.py
----- Begin Fatal Exception 18-Feb-2017 09:09:20 CET-----------------------
An exception of category 'ConfigFileReadError' occurred while
   [0] Processing the python configuration file named create_alpha_trivial_fromFILE.py
Exception Message:
python encountered the error: <type 'exceptions.RuntimeError'>
edm::FileInPath unable to find file CalibCalorimetry/EcalTrivialCondModules/data/EBLaserAlpha_fromFile.txt anywhere in the search path.
The search path is defined by: CMSSW_SEARCH_PATH
${CMSSW_SEARCH_PATH} is: /afs/cern.ch/work/d/depasse/cmssw/CMSSW_9_0_0_pre4/src:/afs/cern.ch/work/d/depasse/cmssw/CMSSW_9_0_0_pre4/external/slc6_amd64_gcc530/data:/cvmfs/cms.cern.ch/slc6_amd64_gcc530/cms/cmssw/CMSSW_9_0_0_pre4/src:/cvmfs/cms.cern.ch/slc6_amd64_gcc530/cms/cmssw/CMSSW_9_0_0_pre4/external/slc6_amd64_gcc530/data
Current directory is: /afs/cern.ch/work/d/depasse/cmssw/CMSSW_9_0_0_pre4/src/CondTools/Ecal/test/alpha

----- End Fatal Exception -------------------------------------------------

What must I add/do ?  Thanks.

**Comment by depasse** [comment]
I will wait for a next week version.  It appears that the new  github directory is still not active?  

or my syntax is not correct ? :

process.EcalTrivialConditionRetriever.EBLaserAlphaFile = cms.untracked.FileInPath('CalibCalorimetry/EcalTrivialCondModul
es/data/EBLaserAlpha_fromFile.txt')

 ~/WORK/cmssw/CMSSW_9_0_X_2017-02-17-2300/src/CondTools/Ecal/test/alpha $ cmsRun create_alpha_trivial_fromFILE.py
----- Begin Fatal Exception 18-Feb-2017 10:19:28 CET-----------------------
An exception of category 'ConfigFileReadError' occurred while
   [0] Processing the python configuration file named create_alpha_trivial_fromFILE.py
Exception Message:
python encountered the error: <type 'exceptions.RuntimeError'>
edm::FileInPath unable to find file CalibCalorimetry/EcalTrivialCondModules/data/EBLaserAlpha_fromFile.txt anywhere in the search path.
The search path is defined by: CMSSW_SEARCH_PATH
${CMSSW_SEARCH_PATH} is: /afs/cern.ch/work/d/depasse/cmssw/CMSSW_9_0_X_2017-02-17-2300/src:/afs/cern.ch/work/d/depasse/cmssw/CMSSW_9_0_X_2017-02-17-2300/external/slc6_amd64_gcc530/data:/cvmfs/cms-ib.cern.ch/week1/slc6_amd64_gcc530/cms/cmssw/CMSSW_9_0_X_2017-02-17-2300/src:/cvmfs/cms-ib.cern.ch/week1/slc6_amd64_gcc530/cms/cmssw/CMSSW_9_0_X_2017-02-17-2300/external/slc6_amd64_gcc530/data
Current directory is: /afs/cern.ch/work/d/depasse/cmssw/CMSSW_9_0_X_2017-02-17-2300/src/CondTools/Ecal/test/alpha

----- End Fatal Exception -------------------------------------------------

Thanks a lot.

**Comment by depasse** [comment]
Test with a more recent version : .txt files in https://github.com/cms-data/CalibCalorimetry-EcalTrivialCondModules still not reachable

 ~/WORK/cmssw/CMSSW_9_0_X_2017-02-19-2300/src/CondTools/Ecal/test/alpha $ cmsRun create_alpha_trivial_fromFILE.py
----- Begin Fatal Exception 20-Feb-2017 11:29:40 CET-----------------------
An exception of category 'ConfigFileReadError' occurred while
   [0] Processing the python configuration file named create_alpha_trivial_fromFILE.py
Exception Message:
python encountered the error: <type 'exceptions.RuntimeError'>
edm::FileInPath unable to find file CalibCalorimetry/EcalTrivialCondModules/data/EBLaserAlpha_fromFile.txt anywhere in the search path.
The search path is defined by: CMSSW_SEARCH_PATH
${CMSSW_SEARCH_PATH} is: /afs/cern.ch/work/d/depasse/cmssw/CMSSW_9_0_X_2017-02-19-2300/src:/afs/cern.ch/work/d/depasse/cmssw/CMSSW_9_0_X_2017-02-19-2300/external/slc6_amd64_gcc530/data:/cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc530/cms/cmssw-patch/CMSSW_9_0_X_2017-02-19-2300/src:/cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc530/cms/cmssw-patch/CMSSW_9_0_X_2017-02-19-2300/external/slc6_amd64_gcc530/data
Current directory is: /afs/cern.ch/work/d/depasse/cmssw/CMSSW_9_0_X_2017-02-19-2300/src/CondTools/Ecal/test/alpha

----- End Fatal Exception -------------------------------------------------

**Comment by smuzaffar** [comment]
my bad @depasse , I forgot to add the new data-CalibCalorimetry-EcalTrivialCondModules but it is fixed now and CMSSW_9_0_X_2017-02-20-1200 IB should have it (which is being build right now).

**Comment by smuzaffar** [comment]
anyway, for your local tests you can just copy the data files in your ```<devarea>/external/slc6_amd64_gcc530/data/CalibCalorimetry/EcalTrivialCondModules/data``` directory and then use FileInPath to access these.

**Comment by depasse** [comment]
@smuzaffar : testing locally, I obtain now : Exception Message:
ValueError type of EBLaserAlphaFile is expected to be string but declared as FileInPath

I have naively tried <std:::FileInPath> replacing <std::string> but it doesn't work.  
Do you have an example of a code using FileInpath files ?  Thanks.

**Comment by smuzaffar** [comment]
see example here
https://github.com/cms-sw/cmssw/blob/53327033fb356b2a704464439ce79fa47a9d1678/CalibMuon/RPCCalibration/python/RPCFakeESProducer_cfi.py#L5
https://github.com/cms-sw/cmssw/blob/53327033fb356b2a704464439ce79fa47a9d1678/CalibMuon/RPCCalibration/src/RPCCalibSetUp.cc#L38

**Comment by depasse** [comment]
Testing in CMSSW_9_0_X_2017-02-20-2300  does not require now the CMSSW /data directory.  
BUT I have committed a change in https://github.com/depasse/CalibCalorimetry-EcalTrivialCondModules/blob/master/data/EBLaserAlpha_fromFile.txt  to verify that the new values were taken into account and it was still the old ones.  
What is the procedure?   I must redo a PR to take the new values into account ?  Or is there a delay ? Or the files are still taken in an old place (which one ?)

**Comment by depasse** [comment]
@smuzaffar : I have changed the values in depasse/CalibCalorimetry..../data  but I suppose the real files used are at top-level of https://github.com/cms-data/CalibCalorimetry-EcalTrivialCondModules/upload/master (where I may not upload files).  So how to proceed ?  A PR ?

**Comment by smuzaffar** [comment]
files needs to be on top level directory. Packaging system takes care of putting them in right place.
I would suggest to clone  https://github.com/cms-data/CalibCalorimetry-EcalTrivialCondModules and apply your changes, push it to your repo and make a PR.

**Comment by smuzaffar** [comment]
@depasse , new tag of  CalibCalorimetry-EcalTrivialCondModules with your updates should be in next IB (23h00 today)
https://github.com/cms-sw/cmsdist/pull/2847

**Comment by depasse** [comment]
Any news about the PR testing ?
It finally worked in CMSSW_9_0_X_2017-02-21-2300 (and used since).
Thanks.

**Comment by ghellwig** [comment]
please test

**Comment by ghellwig** [comment]
@depasse I just started the tests, but now I realize that there is [a question from you](https://github.com/cms-sw/cmssw/pull/17546#issuecomment-281309751) to be addressed.
I think this can be done best by @smuzaffar.

**Comment by smuzaffar** [comment]
@ghellwig , issue was resolved and @depasse changes are already in IB.

**Comment by ghellwig** [comment]
please test

**Comment by ghellwig** [comment]
to refresh the test results

**Comment by franzoni** [comment]
+1

**Comment by ggovi** [comment]
+1

**Comment by franzoni** [comment]
hello @depasse 
the equivalent of this PR has been merged in 91x in https://github.com/cms-sw/cmssw/pull/17719
91x is about to close and be deployed in production

is this PR targeting 90x still of need ? In which case, can you give us the rational.
If not, would you consider closing it.

Thanks!

**Pull request closed without merging**
