### PR TITLE
Addition of HLT_Ele30_WPTight_Gsf to OfflineDQM and cleanups

### PR DESCRIPTION
**Pull request by RSalvatico**
The purpose of this PR is to:

- add `HLT_Ele30_WPTight_Gsf` to the OfflineDQM among the monitored paths in `HLT/EGM/TagAndProbeEffs`, as requested by TSG in [CMSHLT-2810](https://its.cern.ch/jira/browse/CMSHLT-2810);
- change the offline electron and photon IDs for EGM to the newest Run3 ones ([electrons](https://github.com/cms-sw/cmssw/blob/master/RecoEgamma/ElectronIdentification/python/Identification/cutBasedElectronID_Winter22_122X_V1_cff.py), [photons](https://github.com/cms-sw/cmssw/blob/master/RecoEgamma/PhotonIdentification/python/Identification/cutBasedPhotonID_RunIIIWinter22_122X_V1_cff.py));
- clean up, removing HEM/HEP plots (which were relevant in 2017) and removing trigger paths which are no longer in the menu.

### CODE REVIEW

**Comment by RSalvatico** [comment]
type egamma

**Comment by RSalvatico** [comment]
please test

**Comment by swagata87** [comment]
Hello @smuzaffar @perrotta 
(sorry if you are not responsible for this, in that case kindly redirect to those who are responsible). 
Currently the POG L2s have rights to issue test commands etc. But as you know the POG L2s are changing soon. 
From EGamma side we would like the incoming L2 Riccardo to be added to the list so that he has rights.  
Is it something that will be taken care of centrally by you? Or should we make PRs ourselves to add him to the list?
Thank you!

**Comment by swagata87** [comment]
please test

**Comment by smuzaffar** [comment]
> Hello @smuzaffar @perrotta (sorry if you are not responsible for this, in that case kindly redirect to those who are responsible). Currently the POG L2s have rights to issue test commands etc. But as you know the POG L2s are changing soon. From EGamma side we would like the incoming L2 Riccardo to be added to the list so that he has rights. Is it something that will be taken care of centrally by you? Or should we make PRs ourselves to add him to the list? Thank you!

@swagata87 , please open a PR for [cms-bot](https://github.com/cms-sw/cms-bot/blob/master/categories.py#L113 ) and add the new L2.

**Comment by emanueleusai** [comment]
can you explain why this PR yields change in PAG's HLT DQM paths such as DQM/SUSY, etc?
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_13_2_X_2023-06-22-1100+dfb1a7/57638/12434.0_TTbar_14TeV+2023/HLT_SUSY.html

**Comment by RSalvatico** [comment]
Hi, I am on holiday and not able to browse the code much. The differences you point out seem to be related to electron HLT paths. One of the changes I have made concerns the electron IDs for the tag&probe that we use to measure trigger efficiencies. I suspect that these PAG's DQMs inherit that from EGM. Different offline IDs --> different efficiencies.

**Comment by emanueleusai** [comment]
makes sense, thanks for looking into it

**Comment by emanueleusai** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
