### PR TITLE
updated GEN-SIM input; fixed HI wf's INPUT

### PR DESCRIPTION
**Pull request by fabozzi**
updated GEN-SIM recycling
fixed GEN-SIM INPUT for HI wf's

### CODE REVIEW

**Comment by franzoni** [comment]
hello @kkrajcza, 
The workflow 280 runs the proton-proton DIGI and RECO, which was a deliberate choice;
is the reco beamspot provided by the GT auto:run1_mc consistent with the SIM beamspot Realistic5TeVPPbBoost ?
Cheers. G.

**Comment by mandrenguyen** [comment]
@franzoni 

Good catch, the answer is no.
This is a pPb workflow and pPb beam conditions are not currently being maintained in 74X.
We probably want to maintain this workflow, as we will eventually have pPb collisions again, and reprocessing of the 2013 data is possible (although not currently scheduled).
Maintaining the corresponding pPb GTs in 74X  is probably not essential though, given the other priorities at the moment for all involved.

A stop-gap solution would be to simply use the pp beamspot corresponding to run1_mc.
This means that we would be running unboosted pPb, which is not what we record, but would at least maintain the technical viability of running the workflow (although not the boost tool).
Another solution would be to add a customize fragment to switch the beamspot.
Maybe you have a better suggestion.

**Comment by franzoni** [comment]
the two last entries in the conversation of this PR refer to another PR (the discussion has continued there)

**Comment by franzoni** [comment]
+1
all standard and premix workflows tested CMSSW_7_4_X_2015-03-01-0200
all workflows ok (except 280.0_AMPT_PPb_5020GeV_MinimumBias+AMPT_PPb_5020GeV_MinimumBias+DIGI+RECO+HARVEST which is known and being addressed by HIN)
No differences of 75x with respect to the 74 IB => the tests sufficient.

Thanks @fabozzi @nancymarinelli

**Comment by davidlange6** [comment]
+1

**Pull request merged**
