### PR TITLE
Raw data mapper sequence backport

### PR DESCRIPTION
**Pull request by icali**
hi, it is a backport of #24910. No changes in the code.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test workflow 140.55

**Comment by slava77** [comment]
backport of #24910

**Comment by prebello** [comment]
+1 

tests approved

**Comment by boudoul** [comment]
dear @prebello , as usual the review process is implying to look first at the master PR , could you please  sign there ?

**Comment by fabiocos** [comment]
+operations

**Comment by fabiocos** [comment]
@mommsen @kpedro88 at this point I think we should move forward with this backport and build 10_3_0

**Comment by fabiocos** [comment]
+1

the backport corresponds to the original version of the code approved nd merged in master

**Comment by fabiocos** [comment]
merge

**Pull request merged**
