### PR TITLE
[HeaderCheck][Reco] CommonTools/RecoAlgos

### PR DESCRIPTION
**Pull request by mrodozov**
- Remove header (missed a spot in  CommonTools/RecoAlgos )

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by perrotta** [comment]
+1
- This "CommonTools/RecoAlgos/interface/PhotonSelector.h" is replaced by a PhotonSelector plugin (CommonTools/RecoAlgos/plugins/PhotonSelector.cc) that does not depend on it, since 5_3 at least
- There is no other usage of this header in cmssw, and given the existing plugin I imagine it is not even used in analysis or private code
- As such, I expect this can be safely merged already in the UL release; to be extra-safe, however, the release managers could decide to postpone merging it to the next cycle, 11_0
- Jenkins tests pass and show no differences

**Comment by fabiocos** [comment]
hold

@perrotta I agree with your remark, I do not see reasons to rush

**Comment by fabiocos** [comment]
unhold

**Comment by fabiocos** [comment]
+1

**Pull request merged**
