### PR TITLE
Run3-hcx373X Correct the HcalTopology class for 2 new geometry modes - backport #46308

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Correct the HcalTopology class for 2 new geometry modes - backport #46308

#### PR validation:

Use the runTheMatrix test workflows

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport of #46308

### CODE REVIEW

**Comment by Dr15Jones** [comment]
Several places in the newest commit you have `phase2()` but following the old logic it should now be `!phase2()`.

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@perrotta Please approve this

**Comment by mandrenguyen** [comment]
backport of https://github.com/cms-sw/cmssw/pull/46308

**Comment by bsunanda** [comment]
@perrotta Please sign this. I am preparing the correct implementation of HcalTopology given what I wrote earlier for different eras of HCAL. This version is adequate for CMSSW_14_1_X.

**Comment by bsunanda** [comment]
@perrotta Please approver this PR for 14_1_X

**Comment by bsunanda** [comment]
@perrotta Please approver this PR for 14_1_X. We have to use it in 14_1_X for ZDC testing

**Comment by perrotta** [comment]
> @perrotta Please approver this PR for 14_1_X. We have to use it in 14_1_X for ZDC testing

@bsunanda private tests can be done with CMSSW_14_1_2 (or any newer CMSSW_14_1_X IB), as they were already started by the ZDC group. I see no reason tu hurry up: I will just follow the usual procedure, and sign this only once the PR merged in master shows that it has no issues in the IB tests. In the meanwhile, always to speed up, you can add here the additional commit as of #46357, so that they can be backported in one single pass.

**Comment by bsunanda** [comment]
@perrotta Please approve this PR. The Topology class needs further changes and that can be ported back once this is integrated. Please do this urgently

**Comment by bsunanda** [comment]
@perrotta I shall add the deletion of the obsolete constructor in this PR

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by perrotta** [comment]
+1
- Verbatim backport of #46308 and #46357
- The failing unit test has an unrelated das error

**Comment by bsunanda** [comment]
+geometry

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by mandrenguyen** [comment]
@bsunanda there are some conflicts here now

**Comment by bsunanda** [comment]
The right version of the HcalTopology class is already there. It is better to close this PR and open a new PR to correct the scripts of calowriter

**Pull request closed without merging**
