### PR TITLE
Phase2-hgx301 Use messagelogger service instead of cout

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Use messagelogger service instead of cout in Geometry/HGCalCommonData

#### PR validation:

Use runTheMatrix test workflows and cfg's in the test area

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

This PR to move from `cout` to messagelogger service in Geometry/HGCalCommonData

**Comment by srimanob** [comment]
@cmsbuild please test

This is a test not related to the PR content, just to see if we can get rid of perculiar report on default workflow comparison. Sorry for inconvenience @bsunanda

**Comment by perrotta** [comment]
+1

**Pull request merged**
