### PR TITLE
GEMGeometryBuilderDB-fix [92X]

### PR DESCRIPTION
**Pull request by jshlee**
Backport of #20260

For data-taking

@kpedro88 @ianna @calabria @arunhep

### CODE REVIEW

**Comment by kpedro88** [comment]
please test

**Comment by kpedro88** [comment]
+1

**Comment by ianna** [comment]
+1

**Comment by kpedro88** [comment]
should this be closed in favor of a backport of #20562?

**Comment by jshlee** [comment]
since #20562 is merged, I will close this.

**Pull request closed without merging**
