### PR TITLE
HLT updates for the 25ns menu - 76X

### PR DESCRIPTION
**Pull request by perrotta**
HLT menu updates on top of what already merged in CMSSW_7_6_X, i.e.
- Remove HBHE Noise Cleaner from all paths in the menu, and rename a few paths accordingly
- Adjust the threshold to the MET200 path, so that it is really set at 200 GeV, as it should
- Split Stream A into three Physics streams, as it was done already for the 50ns menu
- Rename DQMOffline stream as HLTMonitor

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by davidlange6** [comment]
@perrotta - please give a bit more description of the changes. Thanks

**Comment by perrotta** [comment]
@davidlange6: done now in the PR description at the top


David Lange <notifications@github.com> ha scritto:

**Comment by davidlange6** [comment]
+1

**Pull request merged**
