### PR TITLE
[HeaderCheck][RECO1] Cleanup headers to avoid header inconsistency errors

### PR DESCRIPTION
**Pull request by smuzaffar**
- removed obsolete headers
- all of these are already marked to be delete
  -  RecoTracker/Record/interface/Records.h is not used by any thing

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by slava77** [comment]
it would be better to delete obviously obsolete files separately from those that contain real code which may be used in some analysis and could require a revert/recovery

**Comment by perrotta** [comment]
+1
- Technical: 
  - all removed headers are obsolete
  - RecoTracker/Record/interface/Records.h is never used, and it is also wrong as it refers to a non-existing "RecoTracker/Records" (with final "s") package

**Comment by fabiocos** [comment]
+1

**Pull request merged**
