### PR TITLE
Phase 2 tracker: adding tracker T31 

### PR DESCRIPTION
**Pull request by adewit**
#### PR description:

This adds a new tracker (T31) that is identical to T24, except for the outer radius of the tracker volume, which is reduced by 2cm to avoid clashes with the BTL in a soon-to-be integrated development on the MTD geometry.

This does not affect the positions of any of the tracker components.

The PR only adds this new tracker, so that the addition of a detector description and workflows using this tracker can be left for the integration of the new MTD geometry.

FYI @emiglior @fabiocos 

#### PR validation:

Ran code-checks and code-format. It was checked that the reduction of this volume is harmless for the positioning of tracker components

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Not a backport

### CODE REVIEW

**Comment by srimanob** [comment]
@cmsbuild please test

**Comment by fabiocos** [comment]
@adewit @emiglior thank you a lot, this looks perfectly consistent with the engineering drawings we have been point to, see[ the latest BTL-Tracker integration discussion](https://indico.cern.ch/event/1092511/)

**Comment by srimanob** [comment]
+Upgrade

T31 is the same as T24 (and T21) with the outer radius of the tracker is reduced by 2 cm. This T31 should be used with new BTL.

**Comment by bsunanda** [comment]
+geometry

**Comment by perrotta** [comment]
+1

**Pull request merged**
