### PR TITLE
Explicitly register to produce on end transition

### PR DESCRIPTION
**Pull request by Dr15Jones**
All modules which produce on end Run or end LuminosityBlock now explicitly call produces with that information. This is needed to properly schedule modules in upcoming framework changes.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
This change causes no functional behavior changes, it is just anticipating a change to the framework.

**Comment by Dr15Jones** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by ghellwig** [comment]
+1

**Comment by perrozzi** [comment]
+1

**Comment by dmitrijus** [comment]
+1

**Comment by fabozzi** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/18427	f987d94
- reco is only in RecoLuminosity/LumiProducer/plugins/LumiProducer.cc : the begin/end transitions are assigned correctly for the run/lumi products
- jenkins tests pass

**Comment by rekovic** [comment]
+1

**Pull request merged**
