### PR TITLE
Update disp mu mu producer

### PR DESCRIPTION
**Pull request by jsalfeld**
#### PR description:

In its current version, the HLTDisplacedmumuVtxProducer requires matching of the input muons with objects passing a filter. It is not always useful to run a filter prior to the vertex producer I believe, and hence I make this optional.

This pull request is intended to remove the dependency of running a filter prior to the HLTDisplacedmumuVtxProducer

#### PR validation:

I checked compilation in 11_2_0_pre8, and functionality in CMSSW_11_1_0 where the same results for displaced vertices are present and muons are present before and after the change in the scouting event content.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Comment by jsalfeld** [comment]
Can we back port this to CMSSW_11_1_0 ?

**Comment by qliphy** [comment]
@jsalfeld   Yes. Please note we plan to make the next 11_1_X release by this Friday for the next MWGR.

**Comment by jsalfeld** [comment]
> @jsalfeld Yes. Please note we plan to make the next 11_1_X release by this Friday for the next MWGR.

Thanks a lot @qliphy , the PR is here https://github.com/cms-sw/cmssw/pull/32075

**Pull request merged**
