### PR TITLE
[124X] Fixed PPS Global Alignment path

### PR DESCRIPTION
**Pull request by MatiXOfficial**
#### PR description:

See https://github.com/cms-sw/cmssw/pull/38930

#### PR validation:

See https://github.com/cms-sw/cmssw/pull/38930

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport of https://github.com/cms-sw/cmssw/pull/38930

### CODE REVIEW

**Comment by tvami** [comment]
backport of https://github.com/cms-sw/cmssw/pull/38930

**Comment by tvami** [comment]
test parameters:
  - workflows = 1042

**Comment by tvami** [comment]
type bugfix,ctpps

**Comment by tvami** [comment]
urgent
 * needed for datataking

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by ChrisMisan** [comment]
+alca

- differences in msgLogger and MTD
- relval 1042 passes

**Comment by qliphy** [comment]
+1

**Pull request merged**
