### PR TITLE
Fix the MadGraph5 LO multithread utility

### PR DESCRIPTION
**Pull request by colizz**
#### PR description:

The MadGraph5 LO multithread feature is a part of the GEN multithread utilities (it is not used in official production).
In this PR we fix several spotted issues for the MG LO multithread feature:

- apply a patch to MadGraph5 for the "readonly" gridpack mode, identified in https://answers.launchpad.net/mg5amcnlo/+question/696856 ;
- do "restore_data" manually as required by the "readonly" mode;
- use a corrected LHE merging script.

A backport to 10_6_X is also needed.

#### PR validation:

In the recent GEN efforts to validate on multiple multithreading modules, this utility has been tested on the LHE step produced by MG5 LO, for ~100 recent UL16/17 processes on McM.
Physics results are consistent between the default generator configuration and with the MG5 LO multithread feature applied. Please see plots in the [link](https://coli.web.cern.ch/coli/validation/mt-v2/LHE/nanoplot/). See [here](https://twiki.cern.ch/twiki/bin/view/CMSPublic/WorkBookGenMultithread#Internal_multithreading_for_MG5) for the configuration to activate this utility.

### CODE REVIEW

**Comment by agrohsje** [comment]
Isn't the patch version specific? Should we really have it here instead of genproduction? We could apply patching for existing gridpacks via checking script.

**Comment by colizz** [comment]
> Isn't the patch version specific? Should we really have it here instead of genproduction? We could apply patching for existing gridpacks via checking script.

Yes we should put it in genproduction eventually. The reason we put a patch here is to benefit all existing gridpacks with MG>=2.6.1; and that MG before version 2.7.2 will have some specific patches applied (note that we haven't moved to 2.7 yet).
The patch is flexible to handle all past versions of our gridpack.
For the last item, which checking script do you mean for specific? Is it a tool for genproduction or cmssw?

**Comment by agrohsje** [comment]
We have some 2.7 samples for polarization. Are you saying the patch works for 2.6.1, 2.6.5 and 2.7.x? Then all ultra legacy cases would be covered.

**Comment by agrohsje** [comment]
please test

**Comment by colizz** [comment]
> We have some 2.7 samples for polarization. Are you saying the patch works for 2.6.1, 2.6.5 and 2.7.x? Then all ultra legacy cases would be covered.

sorry we need a small correction. The newly added patch is pretty new and will not be fixed until 2.9.x or 3.1.x, so I'll modify the if-else statement. Thanks for your reminder.
Then it works for all exisiting 2.6.1, 2.6.5 and 2.7.x gridpacks.

When we officially move to MG 2.7.x or more, I'll implement in the genproduction repo the feature inside `runcmsgrid_LO.sh` and also add patches there. Then the implementation of this multithread method will become more straightforward.

**Comment by qliphy** [comment]
please test

**Comment by qliphy** [comment]
There are many differences from DQM/TimerService which are known and fixed:  https://github.com/cms-sw/cmssw/issues/34445
Let's re-trigger the test.

**Comment by qliphy** [comment]
please test

**Comment by qliphy** [comment]
merge

**Pull request merged**
