### PR TITLE
Phase2-hcx366 Avoid the warning printout for RPD volume placement

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Avoid the warning printout for RPD volume placement

#### PR validation:

Use the runTheMatrix test workflows

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

May have to backport this to 14_1_X

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
+geometry

**Comment by subirsarkar** [comment]
+Upgrade

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
