### PR TITLE
Cleanup duplicate pileup jet ID configurations

### PR DESCRIPTION
**Pull request by ahinzmann**
A cleanup of the PU jet ID configs which are duplicate as a followup of #10398.

The configs under 1. are kept while those under 2. and 3. are dropped and their content is integrated into 1.:

```
This one is from 2013 and kept in sync with MVA MET in 2013:
https://github.com/jbrands/cmssw/blob/newOfflinePuID_new/RecoJets/JetProducers/python/PileupJetID_cfi.py
https://github.com/jbrands/cmssw/blob/newOfflinePuID_new/RecoJets/JetProducers/python/PileupJetIDParams_cfi.py
https://github.com/jbrands/cmssw/blob/newOfflinePuID_new/RecoJets/JetProducers/python/PileupJetIDCutParams_cfi.py
It is used in MET.

This one was introduced in 2014 and kept in sync with MET in 2014:
https://github.com/jbrands/cmssw/blob/newOfflinePuID_new/RecoJets/JetProducers/python/pileupjetidproducer_cfi.py
https://github.com/jbrands/cmssw/blob/newOfflinePuID_new/RecoJets/JetProducers/python/puJetIDParams_cfi.py
https://github.com/jbrands/cmssw/blob/newOfflinePuID_new/RecoJets/JetProducers/python/puJetIDAlgo_cff.py
It is used in MET and DQM.

This one was introduced in 2014 for MiniAOD and is yet another copy:
https://github.com/jbrands/cmssw/blob/newOfflinePuID_new/PhysicsTools/PatAlgos/python/slimming/pileupJetId_cfi.py
```

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
+1

For #10625 a83e4215c155eec25aa9950142af762e24a7854e

Clean-up of duplicate pile-up jet ID configurations. There should be no change in monitored quantities.

The code changes are satisfactory, and Jenkins [tests](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-10625/7057/summary.html) against baseline CMSSW_7_6_X_2015-08-07-1100  show no significant differences, as expected. A check of the expanded RECO config for workflow 25202.0 confirms that the code changes do appear in the config.

**Comment by gpetruc** [comment]
When this PR is ready, can you prepare the backports for this + #10398?
Thanks,
Giovanni

**Comment by ahinzmann** [comment]
FYI: There is currently a bug in this new offline jet ID code. Only once this is fixed and validated, we can make the backport.

**Comment by ahinzmann** [comment]
Bug fixed in #10730. Validation ongoing.

**Comment by deguio** [comment]
+1

**Comment by slava77** [comment]
@monttj please check this one
Thank you

**Comment by monttj** [comment]
+1

**Comment by gpetruc** [comment]
backports?

**Comment by ahinzmann** [comment]
While software-wise everything is validated, the training weights are still being validated and until this is done, backport to 74/75 is on hold.
Still need to check
1. this training is optimal for ak4 (for mvaMET) and ak4CHS (for jets) my comparing two separate trainings.
2. this training performs well for mvaMET.

**Comment by gpetruc** [comment]
Is what we currently have in 74X good for physics?
If that one isn't good anyway, then I'd rather have this one if it has a
chance of being good: at worst, if the validation fails, we will have just
replaced one random number with another random number, but if instead the
validation is successful people will be able to use it.
This is especially true for the more basic scenario of people using it on
the ak4CHS jets: mvaMET anyway is currently not in MiniAOD and so the few
people who use need to run more complex recipes and they can recompute a
new PuJetID if needed, while the same computation would add some burden to
the much larger number of users of the slimmedJets.

**Comment by ahinzmann** [comment]
ok, if mvaMET is not in MiniAOD, including this one would make sense.
@jbrands : Since you started validating this one yesterday, could you post the new ROC curve comparison of 53 vs 74 here? (based on the current weights, not the new ones which are still in the works)

**Comment by ahinzmann** [comment]
Johannes confirmed that this discriminant performs better than the 53X training in 76X (though not reaching the Run I performance yet).

roc_pt20to30_eta0to2
roc_pt20to30_eta2to3
roc_pt20to30_eta3to5
roc_pt30to50_eta0to2
roc_pt30to50_eta2to3
roc_pt30to50_eta3to5

**Pull request merged**
