### PR TITLE
Cleanup of HLT customization files moved into ConfDB menus (90X)

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
Cleanup of HLT customization files moved into ConfDB menus (90X)
Based on CMSSW_9_0_X_2017-03-13-1100.

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
backport

**Comment by Martin-Grunewald** [comment]
Need to wait for an IB with #17853 integrated and run jenkins tests again.

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
