### PR TITLE
Sync with stand-alone Pixel Calibration Code

### PR DESCRIPTION
**Pull request by OzAmram**
This is a PR to sync with changes made to the pixel calibration procedure. The idea is to call the actual CMSSW functions that are used in the pixel calibrations procedure rather than separately coded versions of them (like was done previously). To do this we needed to modify the objects and code structure a bit. The most significant changes are adding a sideload() function to SiPixelTemplate object to allow loading of partial templates, and moving the generic_position_formula() to a separate file.

These changes are all internal to the pixel code and we expect no changes in output.

We have tested by running the tracking validation and seeing that the PR makes no difference in the output at all.

Slides about this were shown in the pixel offline meeting. [Here](https://indico.cern.ch/event/879467/contributions/3746113/attachments/1985814/3308855/sideload_PR_feb11.pdf)

@cmantill @pmaksim1 @tvami @mmusich @tsusa

### CODE REVIEW

**Comment by mmusich** [comment]
Hi @OzAmram you need to apply the code format changes by running `scramv1 b code-format` in your local area for the PR to be processed.
I noticed in the commit history there is a huge merge commit https://github.com/cms-sw/cmssw/commit/4edeedf83c6f747d92604dcd110bbcdd85e99633, I am not sure that is acceptable from the release managers. Can it be rebased?

**Comment by OzAmram** [comment]
Ok I undid the merge in my local area and am trying the rebase now. There are some merge conflicts that I need to resolve by hand. I will apply the code format changes ontop at the end.

**Comment by OzAmram** [comment]
Ok the rebase is proving to be extremely painful. Essentially I have to redo all of the merging I did by hand for many commits in the history because there are a lot of conflicts. Is it acceptable if I just start a new branch based on the latest release and then copy all the change files into that?

**Comment by mmusich** [comment]
I think so, provided you and Petar are ok with losing the intermediate commit history.

**Comment by pmaksim1** [comment]
I'm OK.  Not merging by hand *once again* is worth it :)

**Comment by OzAmram** [comment]
Ok I made a new pull request without all the intermediate commit history and with the clang format changes on top. 
https://github.com/cms-sw/cmssw/pull/28945

**Pull request closed without merging**
