### PR TITLE
Replace Geometry_cff with GeometryDB_cff in RecoEcal

### PR DESCRIPTION
**Pull request by jeongeun**
**PR description:**
Review on the Reco part of https://github.com/cms-sw/cmssw/issues/31113

`process.load("Configuration.StandardSequences.Geometry_cff")`
 was outdated https://github.com/cms-sw/cmssw/pull/8810 
It should be replaced with
`process.load("Configuration.StandardSequences.GeometryDB_cff")`

In this PR, RecoEcal configuration files (2 files) are fixed.
```
modified:   RecoEcal/EgammaClusterProducers/test/testRecoEcal_cfg.py
modified:   RecoEcal/EgammaClusterProducers/test/testRecoEcal_cfgV2.py
```

#### PR validation:
Tested in CMSSW_12_5_X, the basic test all passed in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by clacaputo** [comment]
@cmsbuild please test

**Comment by clacaputo** [comment]
Dear @cms-sw/ecal-dpg-l2 , it seems to me the config files fixed by this PR aren't updated since `CMSSW_3_X_Y` cycle.
Do you know if we still need it, maybe used in some unit-test, or we can remove them? Thanks

**Comment by clacaputo** [comment]
> Dear @cms-sw/ecal-dpg-l2 , it seems to me the config files fixed by this PR aren't updated since `CMSSW_3_X_Y` cycle. Do you know if we still need it, maybe used in some unit-test, or we can remove them? Thanks

A kind ping to @cms-sw/ecal-dpg-l2 , please, if you can have a look. Thanks

**Comment by clacaputo** [comment]
Hi @thomreis, could you please have a look at these cfgs and check with ecal people whether they are still needed? Thanks

**Comment by thomreis** [comment]
Hi @clacaputo these test config files are not needed anymore as far as I can tell and can be removed.

**Comment by clacaputo** [comment]
> Hi @clacaputo these test config files are not needed anymore as far as I can tell and can be removed.

Thanks, @thomreis . @jeongeun , could you please take care of it?

**Comment by jpata** [comment]
@cmsbuild please test

**Comment by jpata** [comment]
+reconstruction
- delete outdated files

**Comment by perrotta** [comment]
+1

**Pull request merged**
