### PR TITLE
[DD4hep] Different Material Warnings to Debug Messages

### PR DESCRIPTION
**Pull request by ianna**
#### PR description:

* Silence the differences in `ElementaryMaterials` warnings by moving them to a debug category controlled with a debug tag

@bsunanda - FYI

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by cvuosalo** [comment]
Thanks for taking care of this. You beat me to it.

**Comment by cvuosalo** [comment]
This PR has some of the files from your other PRs. I suppose Git will be able to sort things out.

**Comment by cvuosalo** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade

**Comment by silviodonato** [comment]
+1

**Pull request merged**
