### PR TITLE
Add TopLHEFilter

### PR DESCRIPTION
**Pull request by ohindrichs**
#### PR description:

This is a filter acting on the LHE output. It clusters the final LHE particles using the anti-kt jet algorithm. A cut on the minimum pT > 350 GeV  is selected. This filter is  a loose pre-selection of the AK8-jet pT > 650 GeV filter at particle level used in the production of TT_AK8HT650* samples. The pre-filter selects at LHE level 99.8% of the events with a jet of pT > 650 GeV at particle level, while only 3% of the inclusive ttbar sample passes the filter. Therefore, the number of  events that have to be showered before the filter decision is drastically reduced.    

#### PR validation:

Tests have shown that this pre-filter reduces the the run time per event from  ~1.3s to ~0.2s.

### CODE REVIEW

**Comment by alberto-sanchez** [comment]
@ohindrichs Is there any PR in master for this?

**Comment by ohindrichs** [comment]
@alberto-sanchez No, should I make a PR in master for this? I did not test this.

**Comment by alberto-sanchez** [comment]
@ohindrichs yes, make a pr for master.

**Comment by alberto-sanchez** [comment]
please test

**Comment by srimanob** [comment]
Is this specific to TOP, or for jet in general?
If it's latter case, should the module name be more general, like JetLHEFilter?
@alberto-sanchez @ohindrichs @qliphy

**Comment by alberto-sanchez** [comment]
please test

**Comment by alberto-sanchez** [comment]
backport #27809

**Comment by alberto-sanchez** [comment]
@ohindrichs this looks good. If I understand correctly a port to 10_6_X is also needed.

**Comment by qliphy** [comment]
+1

**Comment by qliphy** [comment]
please test

**Comment by alberto-sanchez** [comment]
@ohindrichs please propagate the latest commit to master and 10_6

**Comment by ohindrichs** [comment]
@alberto-sanchez master and 10_6 have been updated to the latest version

**Comment by alberto-sanchez** [comment]
+1

**Pull request merged**
