### PR TITLE
Add Phase-2 workflow with Phase-2 ECal trigger primitive, also with ECal component

### PR DESCRIPTION
**Pull request by srimanob**
#### PR description:
This PR adds workflows to test ECal Phase-2 Trigger Primitive, with also ECAL component.

This PR needs https://github.com/cms-sw/cmssw/pull/42633 and https://github.com/cms-data/SimCalorimetry-EcalEBTrigPrimProducers/pull/1 to test

#### PR validation:
Run workflow 24834.633,24834.634,24834.635

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:
No need to backport

### CODE REVIEW

**Comment by srimanob** [comment]
test parameters:
- pull_requests = https://github.com/cms-sw/cmssw/pull/42633,https://github.com/cms-data/SimCalorimetry-EcalEBTrigPrimProducers/pull/1
- workflows = 24834.633,24834.634,24834.635
- relvals_opt = --what cleanedupgrade,standard,highstats,pileup,generator,extendedgen,production,identity,ged,machine,premix,nano,gpu,2017,2026

**Comment by srimanob** [comment]
@cmsbuild please test

**Comment by srimanob** [comment]
type ecal-dpg

**Comment by srimanob** [comment]
type ecal

**Comment by srimanob** [comment]
assign ecal-dpg

**Comment by smuzaffar** [comment]
Milestone for this pull request has been moved to CMSSW_14_0_X.Please open a backport if it should also go in to CMSSW_13_3_X.

**Comment by srimanob** [comment]
Replace with https://github.com/cms-sw/cmssw/pull/43635

**Pull request closed without merging**
