### PR TITLE
Update the default relval for the recoMET tests

### PR DESCRIPTION
**Pull request by mmarionncern**
Update of the relval files used in the recoMET tests. 
Don't have any impact on the framework.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
@mmarionncern:

This PR is failing its unit tests. The 76X version did not have this problem. You can see more in the unit test log: https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-10765/7287/unitTests.log

Here's the error:

----- Begin Fatal Exception 14-Aug-2015 15:16:17 CEST-----------------------
An exception of category 'ProductNotFound' occurred while
   [0] Processing run: 1 lumi: 9 event: 401
   [1] Running path 'p'
   [2] Calling event method for module PFClusterRefCandidateMerger/'pfClusterRefsForJets'
Exception Message:
Principal::getByToken: Found zero products matching all criteria
Looking for type: std::vector<reco::RecoPFClusterRefCandidate>
Looking for module label: pfClusterRefsForJetsHF
Looking for productInstanceName: 

   Additional Info:
      [a] If you wish to continue processing events after a ProductNotFound exception,
add "SkipEvent = cms.untracked.vstring('ProductNotFound')" to the "options" PSet in the configuration.

----- End Fatal Exception -------------------------------------------------

**Comment by mmarionncern** [comment]
@cvuosalo Looking deeper into the failing test (pfClusterMET test)), there is no way it could have worked so far since it was in place. The test was actually bypassed due to the lack of proper data file, and this is what is happening for the 76X version.
I am currently fixing both 75X and 76X versions of that particular test.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
+1

For #10765 ea44ec6ab5758663579cecf82d70c42c239cb67c

Update of the RelVal files used in the recoMET tests. Two 76X PRs, #10766 and #10818, contain the changes in this PR. #10766 has already been merged.

Jenkins [tests](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-10765/7398/summary.html) against baseline CMSSW_7_5_X_2015-08-17-1100 show no problems nor significant differences.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
