### PR TITLE
Fix CkfTrackCandidates_cfi.py (10_2)

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
Fix CkfTrackCandidates_cfi.py (10_2)
Based on 10_0_0
Add missing parameter explicitly with default set to reproduce old behaviour.
Needed for ConfDB parsing.

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
backport of #24435

**Comment by perrotta** [comment]
+1
- The missing parameter is accessed in the code as 
```
    reverseTrajectories(conf.existsAs<bool>("reverseTrajectories") && conf.getParameter<bool>("reverseTrajectories")),
```
and therefore explicitely adding it as "false" in the config  reproduces the old behaviour
- Jenkins tests pass with no differences, as expected

**Comment by fabiocos** [comment]
+1

**Pull request merged**
