### PR TITLE
Add all direct deps to BuildFile for RecoTracker/TkHitPairs

### PR DESCRIPTION
**Pull request by davidlange6**
for all packages that still should be made into cxx modules (well, current list of them). Additions made by looking for packages directly included in interface or src.

### CODE REVIEW

**Comment by vgvassilev** [comment]
The meta issue #15248 tracks the C++ modules-related work.

**Comment by davidlange6** [comment]
please test

**Comment by VinInn** [comment]
I remember a campaign few years ago that removed all redundant dependencies (and include files)

**Comment by davidlange6** [comment]
Right - My spot checks (at the level of 5-10 packages only) have shown that clean campaign to have removed incorrectly included packages but it did not add incorrectly missing ones.

Eg, for this package, the old campaign removed "DataFormats/SiStripDetId”, which this PR does add back.


On Jun 25, 2020, at 5:29 PM, Vincenzo Innocente <notifications@github.com<mailto:notifications@github.com>> wrote:



I remember a campaign few years ago that removed all redundant dependencies (and include files)

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/30411	3147373 
- technical

**Comment by silviodonato** [comment]
+1

**Pull request merged**
