### PR TITLE
PuppiNNTau to Phase2GT interface refactor

### PR DESCRIPTION
**Pull request by HaarigerHarald**
#### PR description:

Streamlines the GT interface especially the flip of the charge is necessary to be in line with other subsystems.

See: https://github.com/cms-l1t-offline/cmssw/pull/1225 and https://github.com/cms-l1t-offline/cmssw/pull/1238

### CODE REVIEW

**Comment by aloeliger** [comment]
please test

**Comment by epalencia** [comment]
Please test

**Comment by aloeliger** [comment]
+l1

**Comment by srimanob** [comment]
@cmsbuild 

Refresh the test

**Pull request merged**
