### PR TITLE
Use HCAL noise cuts from DB only for Run3 and Phase2

### PR DESCRIPTION
**Pull request by swagata87**
#### PR description:

Follow-up of the PR https://github.com/cms-sw/cmssw/pull/43612.
In particular, this aims to solve the issue discussed in https://github.com/cms-sw/cmssw/pull/43612#issuecomment-1882484274 and subsequent comments (https://github.com/cms-sw/cmssw/pull/43612#issuecomment-1882700117, https://github.com/cms-sw/cmssw/pull/43612#issuecomment-1883159855 etc). 

#### PR validation:

`136.8` and `136.781`, which are crashing in current IBs with this type of error[*] ran fine after the changes in this PR.

[*]  
Requested conditions of type HcalPFCuts for cell (0x4538403f) (HE 16,63,3) got conditions for cell (0x0) 
Requested conditions of type HcalPFCuts for cell (0x45184441) (HE 17,65,1) got conditions for cell (0x0)

### CODE REVIEW

**Comment by mmusich** [comment]
type pf

**Comment by mmusich** [comment]
type bug-fix

**Comment by mmusich** [comment]
test parameters:
   * workflows = 136.8, 136.781

**Comment by mmusich** [comment]
+hlt
   * fixes failures reported at https://github.com/cms-sw/cmssw/pull/43612#issuecomment-1882484274

**Comment by mmusich** [comment]
urgent

**Comment by jfernan2** [comment]
+1

**Comment by rappoccio** [comment]
+1

**Pull request merged**
