### PR TITLE
Migration to DD4hep for GEM DB loader

### PR DESCRIPTION
**Pull request by slomeo**
**PR description:**

This PR (only for GEM) followed what I did for DT in the PR #32781 (to be signed and merged)  . 

**PR validation:**

1) Validation by using "cmsRun CondTools/Geometry/test/gemgeometrywriter.py" (with DDD and DD4hep):
by checking printouts for both DD & DD4Hep build methods within the GEMGeometryParsFromDD Class in order to compare some DetId parameters (see below):

//DDD

(0) GEMGeometryParsFromDD - DDD 
(1) DDD, tran vector 1877.54  331.06  5695.5
(4) DDD, Chamber DetID 687898914 Name GEMBox11L dx1 141.087 dx2 254.993 dy 641.5 dz 17.35
(1) DDD, tran vector 2377.3  419.183  5692.09
(5) DDD, Eta Partion DetID 688423202 Name GHA101 dx1 205.701 dx2 222.929 dy 97.025 dz 1.4875 nStrips 384 nPads 192 dPhi 0.177151

and so on...

//DD4Hep 

(0) GEMGeometryParsFromDD - DD4HEP 
(1) DD4HEP, tran vector 1877.54  331.06  5695.5
(4) DD4HEP, Chamber DetID 687898914 Name GEMBox11L dx1 141.087 dx2 254.993 dy 641.5 dz 17.35
(1) DD4HEP, tran vector 2377.3  419.183  5692.09
(5) DD4HEP, Eta Partion DetID 688423202 Name GHA101 dx1 205.701 dx2 222.929 dy 97.025 dz 1.4875 nStrips 384 nPads 192 dPhi 0.177151

and so on..

The DD part of the code has not been touched by this PR (except for the printouts). Added "/ dd4hep::mm;", where it was necessary, in the DD4Hep part of the code.

2) Validation by using a dump script, not included in this PR (because it uses a local .mb file). 
Details are present in [*] at the end of this PR description.

// DDD

GEMGeometryESModule::produce :: GEMGeometryBuilder builder db
GEMGeometry found with 2 regions

Region 0:-1 with 1 staions

Station 0:1:GE-1/1 with 1 rings

Ring 0:1 with 36 superChambers

SuperChamber 0: Re -1 Ri 1 St 1 La 0 Ch 35 Ro 0  with 2 chambers

Chamber 0: Re -1 Ri 1 St 1 La 1 Ch 35 Ro 0  with 8 etaPartitions

EtaPartition 0: Re -1 Ri 1 St 1 La 1 Ch 35 Ro 1 GHA111 with 384 strips of pitch 0.10517 and 192 pads of pitch 0.21034

EtaPartition 1: Re -1 Ri 1 St 1 La 1 Ch 35 Ro 2 GHA112 with 384 strips of pitch 0.0974638 and 192 pads of pitch 0.194927

EtaPartition 2: Re -1 Ri 1 St 1 La 1 Ch 35 Ro 3 GHA113 with 384 strips of pitch 0.0903565 and 192 pads of pitch 0.180713

EtaPartition 3: Re -1 Ri 1 St 1 La 1 Ch 35 Ro 4 GHA114 with 384 strips of pitch 0.0838485 and 192 pads of pitch 0.167697

EtaPartition 4: Re -1 Ri 1 St 1 La 1 Ch 35 Ro 5 GHA115 with 384 strips of pitch 0.077825 and 192 pads of pitch 0.15565

EtaPartition 5: Re -1 Ri 1 St 1 La 1 Ch 35 Ro 6 GHA116 with 384 strips of pitch 0.0722858 and 192 pads of pitch 0.144572

EtaPartition 6: Re -1 Ri 1 St 1 La 1 Ch 35 Ro 7 GHA117 with 384 strips of pitch 0.0671505 and 192 pads of pitch 0.134301

EtaPartition 7: Re -1 Ri 1 St 1 La 1 Ch 35 Ro 8 GHA118 with 384 strips of pitch 0.0624191 and 192 pads of pitch 0.124838

and so on

// DD4Hep

GEMGeometryESModule::produce :: GEMGeometryBuilder builder db
GEMGeometry found with 2 regions

Region 0:-1 with 1 staions

Station 0:1:GE-1/1 with 1 rings

Ring 0:1 with 36 superChambers

SuperChamber 0: Re -1 Ri 1 St 1 La 0 Ch 35 Ro 0  with 2 chambers

Chamber 0: Re -1 Ri 1 St 1 La 1 Ch 35 Ro 0  with 8 etaPartitions

EtaPartition 0: Re -1 Ri 1 St 1 La 1 Ch 35 Ro 1 GHA111 with 384 strips of pitch 0.10517 and 192 pads of pitch 0.21034

EtaPartition 1: Re -1 Ri 1 St 1 La 1 Ch 35 Ro 2 GHA112 with 384 strips of pitch 0.0974638 and 192 pads of pitch 0.194927

EtaPartition 2: Re -1 Ri 1 St 1 La 1 Ch 35 Ro 3 GHA113 with 384 strips of pitch 0.0903565 and 192 pads of pitch 0.180713

EtaPartition 3: Re -1 Ri 1 St 1 La 1 Ch 35 Ro 4 GHA114 with 384 strips of pitch 0.0838485 and 192 pads of pitch 0.167697

EtaPartition 4: Re -1 Ri 1 St 1 La 1 Ch 35 Ro 5 GHA115 with 384 strips of pitch 0.077825 and 192 pads of pitch 0.15565

EtaPartition 5: Re -1 Ri 1 St 1 La 1 Ch 35 Ro 6 GHA116 with 384 strips of pitch 0.0722858 and 192 pads of pitch 0.144572

EtaPartition 6: Re -1 Ri 1 St 1 La 1 Ch 35 Ro 7 GHA117 with 384 strips of pitch 0.0671505 and 192 pads of pitch 0.134301

EtaPartition 7: Re -1 Ri 1 St 1 La 1 Ch 35 Ro 8 GHA118 with 384 strips of pitch 0.0624191 and 192 pads of pitch 0.124838

and so on

The conclusion is that the validation of the GEM DB Loader Migration to DD4Hep is fine.

**if this PR is a backport please specify the original PR and why you need to backport that PR:**

nothing special

[*]

In CMSSW_11_3_X_2021-02-21-0000 (for DDD) and CMSSW_11_3_X_2021-02-21-2300 (for DD4Hep)

a) In /condTools/Geom/test 
cp writehelp/* .

b) ./createExtended2021Payload.sh 113YV10 (for DDD and 113YV11 for DD4Hep)

Then I created a
script called "dumpGEMGeometry_DB_cfg.py" and the lines are:
+++++++
import FWCore.ParameterSet.Config as cms

process = cms.Process('DUMP')

process.load("CondCore.CondDB.CondDB_cfi")
process.load("Configuration.StandardSequences.FrontierConditions_GlobalTag_cff")
process.load('Geometry.MuonCommonData.testGE0XML_cfi')
process.load("FWCore.MessageLogger.MessageLogger_cfi")
process.load("Geometry.MuonNumbering.muonGeometryConstants_cff")
process.load("Geometry.GEMGeometryBuilder.gemGeometryDB_cfi")
process.load("Geometry.GEMGeometryBuilder.gemGeometryDump_cfi")

process.MessageLogger = cms.Service("MessageLogger",
    destinations = cms.untracked.vstring('myLogGEM'),
    myLogGEM = cms.untracked.PSet(
        threshold = cms.untracked.string('INFO'),
    )
)

process.muonGeometryConstants.fromDD4Hep = True

from Configuration.AlCa.autoCond import autoCond
process.GlobalTag.globaltag = autoCond['mc']
process.GlobalTag.toGet = cms.VPSet(cms.PSet(record = cms.string('GEMRecoGeometryRcd'),
tag = cms.string('GEMRECO_Geometry_113YV10'),
connect = cms.string("sqlite_file:/afs/cern.ch/user/s/slomeo/CMSSW_11_3_X_2021-02-21-0000/src/CondTools/Geometry/test/myfile.db")))

process.source = cms.Source('EmptySource')

process.maxEvents = cms.untracked.PSet(
    input = cms.untracked.int32(1)
)

process.p = cms.Path(process.gemGeometryDump)
++++++++++++

This script (not included in this PR) is located in https://cmssdt.cern.ch/lxr/source/Geometry/GEMGeometryBuilder/test/python/
and calls GEMGeometryDump Class (already present) by using "cmsRun dumpGEMGeometry_DB_cfg.py"

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by cvuosalo** [comment]
+1

**Comment by ggovi** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

**Comment by qliphy** [comment]
+1

**Pull request merged**
