### PR TITLE
Adding Ele20_WPX and DiEle27_WPTightCaloOnly to HLT DQM

### PR DESCRIPTION
**Pull request by Sam-Harper**
This PR adds
HLT_Ele20_WPTight_Gsf
HLT_Ele20_WPLoose_Gsf
HLT_Ele20_eta2p1_WPLoose_Gsf
HLT_DiEle27_WPTightCaloOnly_L1DoubleEG

to the E/gamma HLT T&P DQM

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by mtosi** [comment]
can you please do the backport for 92x as well ?
thanks !

**Comment by mtosi** [comment]
tracked by https://github.com/cms-sw/cmssw/issues/19142

**Comment by Sam-Harper** [comment]
Of course: done https://github.com/cms-sw/cmssw/pull/19611

**Comment by mtosi** [comment]
thanks
  mia

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
