### PR TITLE
Decrease temporary memory held by PuppiProducer

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

Avoid holding memory between Events which is then released at the beginning of the next Event.
Also did code modernization/improvements.

This was discovered while using ModuleEventAllocMonitor service on a ReReco job.

#### PR validation:

Code compiles.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
@makortel FYI

**Comment by Dr15Jones** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by mandrenguyen** [comment]
+1

**Comment by makortel** [comment]
Comparison differences are related to https://github.com/cms-sw/cmssw/issues/39803 and https://github.com/cms-sw/cmssw/issues/46416

**Pull request merged**
