### PR TITLE
Added missing link to DQM/Physics

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

Need to link with JetMETCorrections/JetCorrector to fix UBSAN builds.

#### PR validation:

Compiles and links using the CMSSW_11_0_UBSAN_X_2019-06-21-2300 IB.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by fabiocos** [comment]
+1

@jfernan2 the update looks technical and simple

**Comment by fabiocos** [comment]
merge

**Comment by jfernan2** [comment]
+1

**Pull request merged**
