### PR TITLE
FastSim memory fix in TrajectorySeedProducer -- backport to 102X

### PR DESCRIPTION
**Pull request by ssekmen**
backport of #25824 , the FastSim tracking memory fix

### CODE REVIEW

**Comment by ssekmen** [comment]
@fabiocos , @Dr15Jones , it is perhaps best to also do a sanitizer check for the 102X backport?  I did not immediately see a 10_2_ASAN_X release.  How should we proceed?  Thanks.

**Comment by Dr15Jones** [comment]
> it is perhaps best to also do a sanitizer check for the 102X backport? I did not immediately see a 10_2_ASAN_X release. How should we proceed? Thanks.

@smuzaffar ideas?

**Comment by ssekmen** [comment]
by the way, we will also need this for 94X (backport is a bit trickier, but is being prepared now).  If you have suggestions for both milestones, it would be very helpful.

**Comment by ssekmen** [comment]
please test

**Comment by kpedro88** [comment]
backport of #25824

**Comment by srimanob** [comment]
@ssekmen @Dr15Jones @smuzaffar 
Do you have test in mind to do?

With decision with Physics, we agree that only memory fix (this PR) should be merged, to allow us to start FastSim for 2018. If it takes long, we have to consider to use 10_2_11.

Other PRs that change physics object efficiencies should not be merged to 9_4, 10_2. They can target for UL.

**Comment by ssekmen** [comment]
@srimanob , we wanted to run with a special build which can show whether the issue has disappeared or not.  But this special build seems not to exist for 102 or 94.  However, since this test worked in 105X, it is perhaps safe to assume that the backports would work too.

**Comment by fabiocos** [comment]
@ssekmen @srimanob in principle if the test passed in master, and the backport is fully consistent as it looks. I discussed with @smuzaffar and a single IB with the sanitizer can be made in 10_2_X to allow the authors to repeat the test

**Comment by prebello** [comment]
FYI @pgunnell concerning memory fix

**Comment by kpedro88** [comment]
@smuzaffar what is the status of the special ASAN IB? (I don't see it listed yet in the usual places.)

**Comment by kpedro88** [comment]
@smuzaffar if an ASAN IB is not forthcoming, please let me know ASAP and I will just merge this PR. This is a major blocker for production right now.

**Comment by kpedro88** [comment]
@ssekmen @angirar the ASAN IB is now available: CMSSW_10_2_ASAN_X_2019-02-09-1100

Please test this PR with it ASAP.

**Comment by smuzaffar** [comment]
as you already noticed, ASAN IB is now available. It will remain installed till Saturday 16th JAN.

**Comment by ssekmen** [comment]
Thanks a lot @smuzaffar .  Could you also make one for 94X?
@kpedro88 , @fabiocos , the ASAN test seems successful.  We can proceed with the merge.

**Comment by ssekmen** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Comment by smuzaffar** [comment]
@ssekmen , CMSSW_9_4_ASAN_X_2019-02-10-2300 is available but might not be usable as there are build error ( https://cmssdt.cern.ch/SDT/html/cmssdt-ib/#/ib/CMSSW_9_4_X )

**Comment by ssekmen** [comment]
Thanks @smuzaffar , but it indeed seems not to be usable.  I tried compiling both using the current FastSimulation/Tracking package and the modified version (#25865), and they give the error in [1].
I am guessing that this has to do with the build error rather than the FastSim code itself.

[1]
==27234==Your application is linked against incompatible ASan runtimes.
config/SCRAM/GMake/Makefile.rules:2068: recipe for target 'lib/slc6_amd64_gcc630/FastSimulationTrackingPlugins.edmplugin' failed
gmake: *** [lib/slc6_amd64_gcc630/FastSimulationTrackingPlugins.edmplugin] Error 1
gmake: *** [There are compilation/build errors. Please see the detail log above.] Error 2

**Pull request merged**
