### PR TITLE
EGM-certified photon IDs for 2016 data: cut based and MVA

### PR DESCRIPTION
**Pull request by ikrav**
This PR contains EGM certified cut-based and MVA photon IDs tuned on 80X samples. They are intended to be used on 2016 data. This new photon MVA uses CITK-based isolation calculation that caused several minor changes in EGM sequences that go outside of the new IDs themselves.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cmsbuild please test
the last round failed due to file I/O errors

let's see if these are transient

**Comment by slava77** [comment]
There are merge conflicts in 
```
 PhysicsTools/PatAlgos/python/slimming/miniAOD_tools.py
PhysicsTools/SelectorUtils/python/tools/vid_id_tools.py
RecoEgamma/PhotonIdentification/python/egmPhotonIDs_cff.py 
```
please resolve these before we can proceed

**Comment by ikrav** [comment]
Hi Slava,
  I do not know how these conflicts came to be. I started with 900pre5, merged in my private branch (also rebased to 900pre5). Everything got merged/resolved/committed during that time. I do not know how now suddenly there are conflicts (unless 900pre5 is somehow different from master at this point). Anyways, I have resolved the conflicts by simply keeping my version of the conflicting places.
Ilya

**Comment by slava77** [comment]
On 3/30/17 5:41 PM, ikrav wrote:
> Hi Slava,
> I do not know how these conflicts came to be. I started with 900pre5,
> merged in my private branch (also rebased to 900pre5). Everything got
> merged/resolved/committed during that time. I do not know how now
> suddenly there are conflicts (unless 900pre5 is somehow different from
> master at this point). Anyways, I have resolved the conflicts by simply
> keeping my version of the conflicting places.

900pre5 is different from the head of 91X.
There was a rather significant change from #17801
.. maybe there were more

**Comment by slava77** [comment]
@cmsbuild please test

conflicts are gone now

**Comment by slava77** [comment]
Errors in the tests appear to be related to this PR:
```
   [6] Calling method for module PATPhotonProducer/'patPhotons'
Exception Message:
Principal::getByToken: Found zero products matching all criteria
Looking for type: edm::ValueMap<bool>
Looking for module label: egmPhotonIDs
Looking for productInstanceName: cutBasedPhotonID-Spring15-25ns-V1-standalone-loose

```

@ikrav 
Please test your changes before updating the PR
``` runTheMatrix.py -l limited -i all ``` should be enough.

**Comment by ikrav** [comment]
Hi Slava,

   I did test my changes before submitting (with the matrix limited). No errors - in 900pre5. 
At the point when I started preparing this PR you said (if I remember right) that at that point 
master and 900pre5 are pretty much the same. But I guess enough time has passed and 
master moved on. 

I will work on the update to have that fixed.

Ilya

**Comment by slava77** [comment]
Hi Ilya,

Please clarify on the status of updates expected for this PR.

Thank you.

**Comment by ikrav** [comment]
Hi Slava,

   This is converging. There was a relatively large scale change from sequences
to tasks done very recently in 91X and that affected quite a few EGM files. I adjusted 
the code and tested it. There are only a few suggestions from David Dagenhart that 
I wanted to consider before pushing the changes.

Ilya

**Comment by kpedro88** [comment]
-1
improper merge/rebase

**Comment by ikrav** [comment]
Hi Slava,

  I have updated my branch for this PR. Now the matrix tests work.
Ilya

**Comment by ikrav** [comment]
Hi, what does it mean? Does it mean I have to do something about it?
Guidance would be appreciated. The branch from which the PR was submitted
was rebased to 900pre5 which was alright as I was told, at least at the time
this branch was being prepared originally.

Ilya

**Comment by kpedro88** [comment]
Your PR now contains 173 commits, which is not acceptable. I assume you merged your old branch into a newer release - this is not correct practice to update a PR.

**Comment by ikrav** [comment]
… I am missing something, I guess I am lacking understanding of how git works.
I had 900pre5 based release. Since there were conflicts reported in the tests for master,
I checked out the latest 91X (as of that point), namely CMSSW_9_1_X_2017-04-03-1100, 
and merged into it my 900pre5-based branch. Then I added two commits, and pushed them
to my branch. I do not know how the rest appeared there. I did not rebase since I submitted
the PR, and committed only two commits explicitly.

    In fact, I think I checked the branch of my PR before making making my most recent
changes, and it already had a ton of other people’s commits. I do not know what this means,
I assumed that once I submit a branch as a PR, other people start messing with it.

  Any guidance?

Ilya

**Comment by kpedro88** [comment]
Every branch of CMSSW has all the historical commits in it. Merging a new IB into your old branch creates duplicates of all the commits in the new IB that are more recent than the base of your branch. This is why it is not an appropriate way to update a PR. Instead, you should rebase your branch - `git rebase` is a tool that will automatically apply the commits from your branch to the new IB.

Since this branch is already messed up, it is usually easier to create a new version of the branch (starting from the new IB) and use `git cherry-pick` to apply your commits from this branch.

**Comment by ikrav** [comment]
It is maybe the same thing (and part of what I do not understand), but I did not merge a new
IB into old branch. Instead, I merged the old branch into the IB. 
  
In the past, using the latest IB as a base for a PR was problematic, because when I came back a month
later, I was not able to recreate the release because IB releases are gone after some time 
(and I needed that to prepare another PR on related code). Is there another option for rebasing that
is not the latest IB?

Thanks,
Ilya

**Comment by kpedro88** [comment]
You can rebase to a prerelease or release, but that will only help if the prerelease or release contains the commit that causes the merge conflict.

Rebase is a git-only operation - it doesn't matter if the IB gets deleted. All you really need to know is the hash of the latest commit before your new commits. If the IB expires, you can just rebase to a newer IB.

**Comment by ikrav** [comment]
Ok, I can restart with the latest IB, but cherry-picking is going to be hard. There is a ton 
of commits, and not only by me, that need to go in. The present branch of PR has a lot of stuff 
both before and after and  in-between the relevant commits. I will try a few things, and if I get stuck, 
I will have to ask for expert help.

Ilya

**Comment by rafaellopesdesa** [comment]
@ikrav I think @kpedro88 meant for you to cherry-pick only *your* commits over a recent IB. The rest will be there.

**Comment by slava77** [comment]
On 4/11/17 2:45 PM, ikrav wrote:
> 
> Ok, I can restart with the latest IB, but cherry-picking is going to be
> hard. There is a ton
> of commits, and not only by me, that need to go in. The present branch
> of PR has a lot of stuff
> both before and after and in-between the relevant commits. I will try a
> few things, and if I get stuck,
> I will have to ask for expert help.

If the history of making the old PR is not needed,
just check first that your local version has all files correctly
and then copy that to a fresh area and commit in a new branch in a
single commit (or factorize if necessary)
and then either override this PR or make a new one.


		--slava

> 
> Ilya
>

**Comment by rafaellopesdesa** [comment]
well, or that.

**Comment by ikrav** [comment]
I am going to close this PR and open a new one shortly that is cleaned up from
all the spurious commits and is submitted from a branch derived from a very recent
IB release.

Thanks to everyone for advice.

Ilya

**Pull request closed without merging**
