### PR TITLE
add missing dependency in CondFormats/RPCObjects

### PR DESCRIPTION
**Pull request by davidlange6**
as identified by the modules IB build

### CODE REVIEW

**Comment by davidlange6** [comment]
please test


On Jul 10, 2020, at 8:09 AM, cmsbuild <notifications@github.com<mailto:notifications@github.com>> wrote:



+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-30628/16896

  *   This PR adds an extra 12KB to repository

**Comment by ggovi** [comment]
+1

**Comment by pohsun** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
