### PR TITLE
Removed unused variables in SiPixelChargeReweightingAlgorithm

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

This fixes a clang warning.

#### PR validation:

Compiling the code with clang does not generate any warnings.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
@makortel FYI

**Comment by civanch** [comment]
+1

this PR cannot be responsible for RelVal timeout

**Comment by perrotta** [comment]
+1

**Comment by perrotta** [comment]
merge

**Pull request merged**
