### PR TITLE
Catch and rethrow xml exceptions in TotemDAQMappingESSourceXML

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

The exceptions are converted to cms::Exceptions.
Unknown exceptions were seen from this code in the IBs.

#### PR validation:

Code compiles.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
@makortel FYI

**Comment by Dr15Jones** [comment]
please test

**Comment by grzanka** [comment]
@Dr15Jones You wrote that `Unknown exceptions were seen from this code in the IBs.` Can you elaborate a bit more on what exactly has happen ? Is it a sign that the XML files were not parsed correctly ?

**Comment by Dr15Jones** [comment]
The failure was seen in 

https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el9_aarch64_gcc11/CMSSW_13_1_X_2023-04-11-2300/unitTestLogs/Calibration/PPSAlCaRecoProducer#/

with the only error message being

```
----- Begin Fatal Exception 12-Apr-2023 04:26:00 CEST-----------------------
An exception of category 'Unknown' occurred while
   [0] Processing  Event run: 322022 lumi: 1025 event: 1759844338 stream: 0
   [1] Running path 'ALCARECOoutput_step'
   [2] Prefetching for module PoolOutputModule/'ALCARECOoutput'
   [3] Prefetching for module TotemVFATRawToDigi/'totemTimingRawToDigiAlCaRecoProducer'
   [4] Calling method for EventSetup module TotemDAQMappingESSourceXML/'totemDAQMappingESSourceXML_TotemTiming'
Exception Message:
An exception of unknown type was thrown.
----- End Fatal Exception -------------------------------------------------
```

The reason I made this PR is so we could actually see the error message.

**Comment by grzanka** [comment]
> The failure was seen in
> 
> https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el9_aarch64_gcc11/CMSSW_13_1_X_2023-04-11-2300/unitTestLogs/Calibration/PPSAlCaRecoProducer#/
> 
> with the only error message being
> 
> ```
> ----- Begin Fatal Exception 12-Apr-2023 04:26:00 CEST-----------------------
> An exception of category 'Unknown' occurred while
>    [0] Processing  Event run: 322022 lumi: 1025 event: 1759844338 stream: 0
>    [1] Running path 'ALCARECOoutput_step'
>    [2] Prefetching for module PoolOutputModule/'ALCARECOoutput'
>    [3] Prefetching for module TotemVFATRawToDigi/'totemTimingRawToDigiAlCaRecoProducer'
>    [4] Calling method for EventSetup module TotemDAQMappingESSourceXML/'totemDAQMappingESSourceXML_TotemTiming'
> Exception Message:
> An exception of unknown type was thrown.
> ----- End Fatal Exception -------------------------------------------------
> ```
> 
> The reason I made this PR is so we could actually see the error message.

Its interesting, am I correct the error seems to appear only in last IB and only for specific architecture (fails on aarch64, works on amd64) ?

**Comment by iarspider** [comment]
> Its interesting, am I correct the error seems to appear only in last IB and only for specific architecture (fails on aarch64, works on amd64) ?

Yes, only in the latest IB, only for aarch64. And I have tried reproducing the failure locally, but could not.

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
@cmsbuild , please test for el9_aarch64_gcc11

**Comment by tvami** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
