### PR TITLE
Remove unused magnetic field geometry tags from all GTs

### LINKED ISSUE #20: Remove MFGeometry_120812  and MFGeometry_130503
these both run from run number 1 and are superseded by MFGeometry_160812 and MFGeometry_90322 (these numbers are FEM version numbers)
In principle could be removed from all new tags in autoCond + online tags as well
HN link: https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/4450.html

### PR DESCRIPTION
**Pull request by tvami**
#### PR description:

This PR removes the unused 
```
MFGeometryFileRcd | 130503 | MFGeometry_130503
MFGeometryFileRcd | 120812 | MFGeometry_120812
```
tags from all GTs. These tags have been superseded a long time ago by 
```
MFGeometryFileRcd | 90322 | MFGeometry_90322
MFGeometryFileRcd | 160812 | MFGeometry_160812
```
but have never been removed from the GTs. See the request in [1] and the diffs in [2], they only show these 2 tags.

[1] 
https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/4450.html

[2] 
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mcRun1_design_v1/121X_mcRun1_design_v2
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mcRun1_realistic_v1/121X_mcRun1_realistic_v2
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mcRun1_HeavyIon_v1/121X_mcRun1_HeavyIon_v2
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mcRun2_startup_v1/121X_mcRun2_startup_v2
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mcRun2_asymptotic_l1stage1_v1/121X_mcRun2_asymptotic_l1stage1_v2
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mcRun2_design_v1/121X_mcRun2_design_v2
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mcRun2_asymptotic_preVFP_v1/121X_mcRun2_asymptotic_preVFP_v2
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mcRun2_asymptotic_v1/121X_mcRun2_asymptotic_v2
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mcRun2cosmics_asymptotic_deco_v1/121X_mcRun2cosmics_asymptotic_deco_v2
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mcRun2_HeavyIon_v1/121X_mcRun2_HeavyIon_v2
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mcRun2_pA_v1/121X_mcRun2_pA_v2
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_dataRun2_v1/121X_dataRun2_v2
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_dataRun2_HEfail_v1/121X_dataRun2_HEfail_v2
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_dataRun2_relval_v1/121X_dataRun2_relval_v2
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_dataRun2_PromptLike_HI_v1/121X_dataRun2_PromptLike_HI_v2
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_dataRun3_HLT_v1/121X_dataRun3_HLT_v2
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_dataRun2_HLT_relval_v1/121X_dataRun2_HLT_relval_v2
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_dataRun3_Express_v1/121X_dataRun3_Express_v2
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_dataRun3_Prompt_v1/121X_dataRun3_Prompt_v2
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_dataRun3_v1/121X_dataRun3_v2
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mc2017_design_v1/121X_mc2017_design_v2
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mc2017_realistic_v1/121X_mc2017_realistic_v2
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/120X_mc2017_realistic_forppRef5TeV_v2/120X_mc2017_realistic_forppRef5TeV_v2
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mc2017cosmics_realistic_deco_v1/121X_mc2017cosmics_realistic_deco_v2
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mc2017cosmics_realistic_peak_v1/121X_mc2017cosmics_realistic_peak_v2
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_upgrade2018_design_v1/121X_upgrade2018_design_v2
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_upgrade2018_realistic_v1/121X_upgrade2018_realistic_v2
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_upgrade2018_realistic_RD_v1/121X_upgrade2018_realistic_RD_v2
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_upgrade2018_realistic_HI_v1/121X_upgrade2018_realistic_HI_v2
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_upgrade2018_realistic_HEfail_v1/121X_upgrade2018_realistic_HEfail_v2
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_upgrade2018cosmics_realistic_deco_v3/121X_upgrade2018cosmics_realistic_deco_v4
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_upgrade2018cosmics_realistic_peak_v1/121X_upgrade2018cosmics_realistic_peak_v2
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mcRun3_2021_design_v3/121X_mcRun3_2021_design_v4
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mcRun3_2021_realistic_v4/121X_mcRun3_2021_realistic_v5
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mcRun3_2021cosmics_realistic_deco_v4/121X_mcRun3_2021cosmics_realistic_deco_v5
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mcRun3_2021_realistic_HI_v4/121X_mcRun3_2021_realistic_HI_v5
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mcRun3_2023_realistic_v3/121X_mcRun3_2023_realistic_v4
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mcRun3_2024_realistic_v3/121X_mcRun3_2024_realistic_v4
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mcRun4_realistic_v1/121X_mcRun4_realistic_v2

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

This is not a backport and no backport is needed

resolves https://github.com/cms-AlCaDB/AlCaTools/issues/20

### CODE REVIEW

**Comment by tvami** [comment]
test parameters:
  - workflows = 140.0,200.0,202.0,203.0,204.0,205.0,4001.0,4006.0,4007.0,4008.0,11634.0,12434.0,12834.0,1325.516,50200.0,7.22,145.0,281.0,10424.0,7.21,11224.0,250200.182,11024.2,7.4,12034.0,7.23,159.0,12834.0,7.24

**Comment by tvami** [comment]
cc @namapane

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by francescobrivio** [comment]
@tvami what about 120X_mc2017_realistic_forppRef5TeV_v2? Should we remove the tags from there as well?

**Comment by francescobrivio** [comment]
@tvami @perrotta @qliphy I also see (beside usual MessageLogger erros) some nulls in the "Info" section of wfs 312.0 and 25202.0. I don't think they are related to this PR, but I can't find anything in the logs (or maybe I'm not looking in the right place). Any suggestion?

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
> @tvami what about 120X_mc2017_realistic_forppRef5TeV_v2? Should we remove the tags from there as well?

I think we internally just agreed not to touch this

**Comment by quark2** [comment]
This PR seems having no significant relation with PR #35335. The PR just added some more rows on an onlineDQM histogram (and fixed some typo).

Best regards, 
Byeonghak Ko

**Comment by tvami** [comment]
> * DQMHistoTests: Total failures: 0

Yay, tests came back clear, no changes, as expected

**Comment by perrotta** [comment]
+1

**Pull request merged**
