### PR TITLE
Remove cscTriggerPrimitiveDigis to prevent online client from crashing.

### PR DESCRIPTION
**Pull request by dildick**
Needs to be back-ported to 10_3 for HI running.
@threus @ptcox @barvic

### CODE REVIEW

**Comment by andrius-k** [comment]
Hi @dildick, I can't seem to fins you in the [DQM contacts list](https://twiki.cern.ch/twiki/bin/viewauth/CMS/DQMContacts). Could you please introduce yourself shortly?

**Comment by barvic** [comment]
Hi @andrius-k, just in case, Sven works with CSC and currently handling parts of our outdated CSC trigger-related code.

**Comment by ptcox** [comment]
Sven is not a DQM developer, per se  - he's a CSC trigger primitive 
expert. His clean up of superseded trigger primitive code accidentally 
missed this online DQM config file. He's submitting the pull request to 
correct it as a favour to the rest of us.

Regards, Tim (CSC DPG)

Andrius wrote on 18/10/17 15:46 :

**Comment by andrius-k** [comment]
please test

Thanks for clarification!

**Comment by fabiocos** [comment]
@jfernan2 @andrius-k is there any issue with this PR, or could we move it forward?

**Pull request merged**
