### PR TITLE
[13_0_X] HcalDQM: Fix HFRaddam event type for online DQM deployment

### PR DESCRIPTION
**Pull request by lwang046**
Backport of #40916

### CODE REVIEW

**Comment by abdoulline** [comment]
A good practice for backports is to include in the PR title a release series "prefix" like:  "[13_0_X] ..."

**Comment by emanueleusai** [comment]
type hcal

**Comment by emanueleusai** [comment]
please test

**Comment by emanueleusai** [comment]
backport of https://github.com/cms-sw/cmssw/pull/40916

**Comment by emanueleusai** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
