### PR TITLE
Merge .h and .cc files of plugins in some CommonTools packages

### PR DESCRIPTION
**Pull request by guitargeek**
#### PR description:

Part of the series of PRs that merges `.h` files with the `.cc` files of the plugins in some CMSSW subsystems.

This continues the work done in https://github.com/cms-sw/cmssw/pull/34660.

It makes maintaining the plugins much easier and also excludes the possibility to wrongly include plugin header files.

The changes made in this PR are only copy-paste and sorting includes to make the review easy.

Note that the `ShallowCloneProducer.h` file was moved from `CommonTools/CandAlgos/interface` to `CommonTools/RecoAlgos/plugins` because it is the only place where it is used.

#### PR validation:

CMSSW compiles.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

No backport intended.

### CODE REVIEW

**Comment by jpata** [comment]
@cmsbuild code-checks

**Comment by jpata** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cmsbuild please test

**Review by jpata — COMMENTED** [review]
I checked that all the code changes look reasonable, nothing unexpected.

The reco differences in 1325.81, 136.731 seem to be related to the DNN non-reproducibility: https://github.com/cms-sw/cmssw/issues/32628
Dumping the pairDiscri names:
```
73 pfParticleNetJetTags:probWcq
100 pfParticleNetDiscriminatorsJetTags:HccvsQCD
103 pfParticleNetDiscriminatorsJetTags:ZbbvsQCD
```

PFMet still looks like a legacy class, pinged PF contacts. It is not a blocker for this PR as such, can be a follow-up.

**Comment by jpata** [comment]
+reconstruction
- technical, no unexpected reco changes (ONNX inference shows non-reproducibility here)
- follow-up may be required to migrate PFMet to `edm::one/edm::stream`: https://github.com/cms-sw/cmssw/pull/35216#discussion_r709966243 cc @laurenhay @marksan87

**Comment by qliphy** [comment]
+1

**Pull request merged**
