### PR TITLE
New APE measurement workflow

### PR DESCRIPTION
**Pull request by mteroerd**
#### PR description:

4ec9659042efc550feab5323983978c86c26fe2d : Added new workflow for measuring APE using DAGMan and HTCondor. 
To execute, run, e.g., "python3 apeMeasurement.py -c mc_example.yaml" (should use el8 for this dataset).

fddb4bd5b9fd000c39b93c0fe19fb562db6a0147 : Removing obsolete files that are not used. Mostly old plotting scripts in macros/.

e75e715e280ba7724b38ca00eb2192b70121aaf8 : Removing some references to obsolete files.

#### PR validation:

Ran the workflow with several different configurations. Also replicated a previous MC 2023 APE campaign (as configured in mc_example.yaml) in order to ensure the same results.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Not a backport, not sure if backports will be needed (probably not).

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by perrotta** [comment]
@mteroerd this PR adds new test configs: is any unit test foreseen with them?

**Comment by mteroerd** [comment]
> @mteroerd this PR adds new test configs: is any unit test foreseen with them?

I think that these configs would not work in a unit test, as they'd require access to dasgoclient. I agree it makes sense to include a unit test for the new work flow, but since I am short on time to work on this much more and because my contract will end this month, this will probably be a task for my successor, along with the inclusion of a few more features that would make sense.

**Comment by perrotta** [comment]
+alca
- New test configs added, tested and validated under the responsibility of the Alignment/APE group

**Comment by rappoccio** [comment]
+1

**Pull request merged**
