### PR TITLE
 Vertex and tracking DQM: fix histo scales, add ngood vertex, Add valid,lost,missing inner/outer hits 2d-histos

### PR DESCRIPTION
**Pull request by VinInn**
back port of #11044

### CODE REVIEW

**Comment by VinInn** [comment]
@cmsbuild , please test

**Comment by deguio** [comment]
please test

**Comment by VinInn** [comment]
@cmsbuild please test again

**Comment by smuzaffar** [comment]
please test
@VinInn , cms-bot is very sensitive about the wordings, so it will mind the "again" word at the end :smile:

**Comment by VinInn** [comment]
I would like a fast integration of this PR If we move to 75x for DQM after TS2...

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
