### PR TITLE
 auto pseudo parabolic for data taking or field from DB for B 0T mostly (fix of #9009 )

### PR DESCRIPTION
**Pull request by slava77**
This provides a python-based auto-selection of the field to be served in the tracker as parabolicMF.
- proper parabolic for 3.8 T
- uniform 0 for 0 T
- parameterized engine values for intermediate field values

### CODE REVIEW

**Comment by slava77** [comment]
diffs don't make sense anymore :(

**Comment by davidlange6** [comment]
yea - sorry...

**Comment by slava77** [comment]
I have to disconnect now.
Next time online in about 12 hours

**Comment by slava77** [comment]
ok, maybe not just yet offline

**Pull request closed without merging**
