### PR TITLE
Warn about bit number above trigger collections sizes only once per event/bx

### PR DESCRIPTION
**Pull request by perrotta**
#### PR description:

Logs in a few test outputs are now flooded by warning messages from L1TGlobalProducer. This makes difficult to find other warnings and debug possible other issues in the code. 

For example, in wf 136.731 the MessageLogger Summary says:
```
MessageLogger Summary

 type     category        sev    module        subroutine        count    total
 ---- -------------------- -- ---------------- ----------------  -----    -----
    1 Configuration        -w HLTHighLevel:ALC                       2        2
    2 L1TGlobal            -w L1TGlobalProduce                   10868    10868
    3 HLTConfigProvider    -e DQMPFCandidateAn                       2        2
    4 HLTConfigProvider    -e METAnalyzer:pfMe                       2        2
    5 HLTConfigProvider    -e METAnalyzer:pfPu                       2        2
    6 TimeReport           -e AfterModEndJob                         1*       1
    7 hltPrescaleTable     -e PATTriggerProduc                       1        1
    8 fileAction           -s file_close                             1        1
    9 fileAction           -s file_open                              2        2

* Some occurrences of this message were suppressed in all logs, due to limits.

 type    category    Examples: run/evt        run/evt          run/evt
 ---- -------------------- ---------------- ---------------- ----------------
    1 Configuration        274199/39389360  274199/38626099  
    2 L1TGlobal            274199/39389360  274199/39389360  274199/39733340
    3 HLTConfigProvider    Run: 274199      Run: 274199      
    4 HLTConfigProvider    Run: 274199      Run: 274199      
    5 HLTConfigProvider    Run: 274199      Run: 274199      
    6 TimeReport           EndJob                            
    7 hltPrescaleTable     274199/39389360                   
    8 fileAction           PostGlobalEndRun                  
    9 fileAction           pre-events       pre-events       

Severity    # Occurrences   Total Occurrences
--------    -------------   -----------------
Warning             10870               10870
Error                   8                   8
System                  3                   3
```

Those warnings are repeated for every BX in the event and for every bit number above the vector dimension thresholds. Since there is no information on the bit number itself, having that message repeated multiple time is completely useless.

One possibility to reduce the number of those logWarnings is to have them only printed once per event (this is needed, because different events my have different trigger menus) and per bx, and **not** for every single bit in a given bx. This is what is implemented in this PR. (Actually, I don't think that repeating the same warning at every bx can have any usefulness, but I did not want to hit thread safety issues in doing it).

With this PR, the MessageLogger Summary for the same  wf 136.731 becomes:

```
MessageLogger Summary

 type     category        sev    module        subroutine        count    total
 ---- -------------------- -- ---------------- ----------------  -----    -----
    1 Configuration        -w HLTHighLevel:ALC                       2        2
    2 L1TGlobal            -w L1TGlobalProduce                    1000     1000
    3 HLTConfigProvider    -e DQMPFCandidateAn                       2        2
    4 HLTConfigProvider    -e METAnalyzer:pfMe                       2        2
    5 HLTConfigProvider    -e METAnalyzer:pfPu                       2        2
    6 hltPrescaleTable     -e PATTriggerProduc                       1        1
    7 fileAction           -s file_close                             1        1
    8 fileAction           -s file_open                              2        2

 type    category    Examples: run/evt        run/evt          run/evt
 ---- -------------------- ---------------- ---------------- ----------------
    1 Configuration        274199/39389360  274199/38626099  
    2 L1TGlobal            274199/39389360  274199/39389360  274199/39733340
    3 HLTConfigProvider    Run: 274199      Run: 274199      
    4 HLTConfigProvider    Run: 274199      Run: 274199      
    5 HLTConfigProvider    Run: 274199      Run: 274199      
    6 hltPrescaleTable     274199/39389360                   
    7 fileAction           PostGlobalEndRun                  
    8 fileAction           pre-events       pre-events       

Severity    # Occurrences   Total Occurrences
--------    -------------   -----------------
Warning              1002                1002
Error                   7                   7
System                  3                   3
```

The outputs are not yet fully cleaned, but with a factor 10 reduction of the repeatedly identical messages the logs already become much better readable and inspectable for other messages.

To the attention of @cms-sw/l1-l2

#### PR validation:

It compiles and actually cleans up (a bit) the logs, without removing information from the warning message

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by silviodonato** [comment]
Any objections @cms-sw/l1-l2 ?

**Comment by rekovic** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
