### PR TITLE
Initial Implementation of Tasks in CMS Configurations

### PR DESCRIPTION
**Pull request by wddgit**
This includes the initial implementation of the Task feature in the Core CMS configuration code. It allows creating Tasks, adding modules to them, and associating them to sequences, paths, end paths, and the schedule. In many ways Tasks behave like Sequences except that the order modules appear on Tasks does not matter. New unit tests were added to test the Core code changes.

This PR also includes changes to migrate a lot of configuration code to use Tasks. Large parts of PAT configuration code, all PAT tools, and some parts of RECO code were migrated. In particular, code that was used by runTheMatrix.py tests, IB unit tests, and other test configurations and that was already using unscheduled execution mode was migrated. Although large numbers of configuration files were migrated, an even larger number of configuration files were not migrated yet. There remains much migration work to be done. But the unmigrated configurations are not broken by this PR and should continue to run successfully. At a future date, the other code can be incrementally migrated as resources become available to do the work.

This PR modifies the convertToUnscheduled function to work properly with the new Task feature. EDProducers and EDFilters removed from paths and endpaths are automatically placed on a Task.

There are also changes to ConfigBuilder.py.

A duplicate of the PR was already submitted to 9_0_X with number #17430. Because of the size and complexity of this PR and the risk associated with it, at the Core meeting we decided to also submit this to the DEVEL branch where it can be immediately integrated and that will lead to additional testing while the 9_0_X PR is under review.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
@shahzad @davidlange6 if the tests succeed, please go ahead an merge this into DEVEL.

**Comment by Dr15Jones** [comment]
The unit test failure is unrelated to this pull request.

**Comment by Dr15Jones** [comment]
@davidlange6 @smuzaffar please merge this into DEVEL so we can get wider scale tests and can be sure future changes to CMSSW are not breaking this change.

**Comment by smuzaffar** [comment]
I am merging it now and starting an IB (17h00)

**Comment by Dr15Jones** [comment]
@smuzaffar thanks!

**Pull request merged**
