### PR TITLE
Allow storing uint32_t and double in NanoAOD, and flat tables in the Runs tree, for ALCANANO

### PR DESCRIPTION
**Pull request by pieterdavid**
#### PR description:

While trying to migrate the SiStrip calibration trees (flat trees produced from ALCARECO by the DPG) to the NanoAOD framework, we ran into a few limitations:
- `nanoaod::FlatTable` can only contain Float, Int, UInt8_t and Bool columns. For calibration purposes UInt32_t (DetId) is also commonly needed, as well as double, for the few cases where the full precision should be kept.
- the NanoAODOutputModule can only handle summary tables for the Runs tree, while flat tables can also be very useful (e.g. to store a few conditions-derived quantities)

This PR adds these (the code changes follow the existing code as much as possible). Since the FlatTable dataformat needs additional members for the new types, the class version is updated. I hope that doesn't cause compatibility problems.
The changes may also be useful for similar efforts in other DPGs and POGs (in case more types need to be added they could be included here).

#### PR validation:

Implemented a flat tree with all variables for the measurement of the SiStrip Lorentz angle and backplane correction (based on SiStripCalCosmics), which uses the new types and puts a flat table in the runs tree - full validation is ongoing, but the produced file looks technically sound (the work-in-progress code can be found [here](https://github.com/pieterdavid/cmssw/compare/nanoadduint32doubleandrunflattables...pieterdavid:try_nano_calibtrees_3_1130pre6), the relevant config is [this one](https://github.com/pieterdavid/cmssw/compare/nanoadduint32doubleandrunflattables...pieterdavid:try_nano_calibtrees_3_1130pre6#diff-2c068eefe192ac5d543c9519bf6823fad145c3dffed0d5643138af2be938dde1)).

CC: @ataliercio @robervalwalsh @mmusich @tsusa @mariadalfonso @gouskos

### CODE REVIEW

**Comment by mariadalfonso** [comment]
please test

**Comment by qliphy** [comment]
kindly ping @cms-sw/xpog-l2

**Comment by mariadalfonso** [comment]
please test

(retest with newer IB before merging)

**Comment by gouskos** [comment]
+xpog

Changes proposed in this PR in accordance with the description.
Functionalities introduced can be useful for other cases beyond the SiStrip studies.
PR tested and no changes in the size or content of nanoAOD observed [as expected]

**Comment by qliphy** [comment]
+1

**Pull request merged**
