### PR TITLE
Added MixMax random number generator

### PR DESCRIPTION
**Pull request by civanch**
New MixMax random number generator is added (this is a replacement of #21066). The default is not changed, so no change in test results is expected. The new generator is expected to have the best random properties compared with any other used by CMS. For some details and references see: https://indico.cern.ch/event/679788/contributions/2784242/attachments/1556849/2449087/VIGeant4Valid.pdf 

Unit test is also updated in order to test the new generator.

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
