### PR TITLE
  back porting the PR #18629

### PR DESCRIPTION
**Pull request by suchandradutta**
Updating configurations files to read geometry properly from XML (not from DB as done here on purpose)  Already included in 92X  
https://github.com/cms-sw/cmssw/pull/18629

@mmusich

### CODE REVIEW

**Comment by mmusich** [comment]
backport of https://github.com/cms-sw/cmssw/pull/18629

**Comment by mmusich** [comment]
@suchandradutta thanks!

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
Closing PR. CMSSW_9_1_X is for muon TDR upgrade changes only (CMSSW_9_2_X for data taking)

**Pull request closed without merging**
