### PR TITLE
Replace Legacy EDAnalyzer with Thread-friendly in Geometry

### PR DESCRIPTION
**Pull request by ianna**
- Replace legacy EDAnalyzer with thread-friendly one
- Clean up dead assignments

### CODE REVIEW

**Comment by ianna** [comment]
@cmsbuild please test

**Comment by ianna** [comment]
@cmsbuild please test

**Comment by ianna** [comment]
@smuzaffar - how come a package pulled from git needs an approval as a new one?

**Comment by ianna** [comment]
+1

**Comment by ianna** [comment]
@cmsbuild please test

**Comment by smuzaffar** [comment]
@ianna , here new package means either a new package or a package without any category. 
I guess Geometry/HGCalGeometry should belong to geometry category ....right?

**Comment by ianna** [comment]
@smuzaffar - yes, thanks!

**Comment by ianna** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
