### PR TITLE
[ALCA] Apply code-checks/format with misc-definitions-in-headers

### PR DESCRIPTION
**Pull request by smuzaffar**
code-checks/format applied on full cmssw

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
ping @cms-sw/alca-l2

**Comment by francescobrivio** [comment]
+alca
 - technical
 - differences and failures (all from MessageLogger) not related to this PR

**Comment by qliphy** [comment]
+1

**Pull request merged**
