### PR TITLE
Added consume for TrackerParametersESModule

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

Added consumes and use the ESGetToken that is provided.

#### PR validation:

Used runTheMatrix.py to start a job which used this module. The job ran fine.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
Please review this pull request. It is needed for waiting framework changes.

**Comment by cvuosalo** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
