### PR TITLE
A possible solution for RPCAMCLink out-of-range issue

### PR DESCRIPTION
**Pull request by zhangcg123**
#### PR description:

After the PR #38564 merged, there is an issue about RPCAMCLink #38939.

The reason for the crash is that during the run 314890 (used by the workflow 136.8561_RunZeroBias) the CPPF data were considered as corrupted. The reason was an firmware update, which led to some problems.. The CPPF good data have been restored after the run 315764.( Copy from https://github.com/cms-sw/cmssw/issues/38939#issuecomment-1210364325 )

This is fixed by adding a sanity check to RPCCPPFUnpacker. 

#### PR validation:
runTheMatrix.py -l 136.8561 --job-reports -t 4 --ibeos

### CODE REVIEW

**Comment by zhangcg123** [comment]
@mileva @andresib @minerva1993 @jhgoh, Dear RPC experts, please take a look at this.

**Comment by mileva** [comment]
Hi @mandrenguyen !
Thank you for mentioning @cms-sw/muon-dpg-l2  and also the RPCs!
I am not an firmware expert, but after a short discussion with @zhangcg123 I think the proposed value is correct.
Further to the RPCAMCLink [class](https://github.com/cms-sw/cmssw/blob/c3b26e0cb857ef2629325f6522fb7c538351066f/CondFormats/RPCObjects/interface/RPCAMCLink.h#L23),
it should be OK.
At least I hope.
As this is quite specific value and we do not expect to change, I agree to remain hardcoded.
Regards!
Roumyana

**Comment by perrotta** [comment]
please test workflow 136.8561
(Thank you @zhangcg123 )

**Comment by mandrenguyen** [comment]
+reconstruction

**Comment by perrotta** [comment]
+1

**Comment by perrotta** [comment]
@zhangcg123 please prepare a backport for CMSSW_12_5_X

**Pull request merged**
