### PR TITLE
Fix for PoolDBESSource_cfi - properly moved to V2

### PR DESCRIPTION
**Pull request by ggovi**
This fix complete the move to V2 for the cfg files provided with CondCore/ESSources package (76X version)

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
@ggovi 
Can you please make a PR for 75X as well?
Thanks!

**Comment by Martin-Grunewald** [comment]
Ah, never mind, I now see it is https://github.com/cms-sw/cmssw/pull/10978
Thanks!

**Comment by mmusich** [comment]
please test

**Comment by ggovi** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Comment by ggovi** [comment]
@mmusich ping!!

**Comment by mmusich** [comment]
+1
pong!

**Pull request merged**
