### PR TITLE
Fixed MUON System overlaps for DD4hep Scenario 2021

### PR DESCRIPTION
**Pull request by slomeo**
**PR description:**

This PR has been triggered by what @vargasa wrote in PR #31182. All the overlaps inside the MUON System have been fixed. 

**PR validation:**

1) validation by "cmsShow.exe -c overlaps.fwc --sim-geom-file cmsDD4HepGeom.root --tgeo-name=CMS"
The attached picture shows, after this PR, no Muon overlaps but apparent remaining overlaps in PPS and ZDC.

2) validation by "nohup cmsRun SimG4Core/PrintGeomInfo/test/python/g4OverlapCheckDD4Hep_cfg.py >& overlaps.out &"

Before this PR the result was:  /afs/cern.ch/user/s/slomeo/public/Overlaps/overlaps.out.orig (i.e YB* volumes have some overlaps)

After this PR the result is: /afs/cern.ch/user/s/slomeo/public/Overlaps/overlaps.out (i.e there are not YB* volumes anymore)
 
3) validation by runTheMatrix.py -l 25202.1 :

25202.1_TTbar_13+TTbar_13+DIGIUP15APVSimu_PU25+RECOUP15_PU25+HARVESTUP15_PU25 Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED  - time date Fri Sep 11 12:27:34 2020-date Fri Sep 11 12:06:10 2020; exit: 0 0 0 0
1 1 1 1 tests passed, 0 0 0 0 failed

**if this PR is a backport please specify the original PR and why you need to backport that PR:**

nothing special

overlaps

### CODE REVIEW

**Comment by slomeo** [comment]
@civanch @cvuosalo : please can you allow me to perform "please test" for this PR?

**Comment by civanch** [comment]
please test

**Comment by ianna** [comment]
Are 50 cm overlaps real? Is it something new?

**Comment by slomeo** [comment]
> Are 50 cm overlaps real? Is it something new?

No, it is not new. I attached the same picure 10 days ago (before this PR), please see my post to @bsunanda in the PR #31182. The 50 cm overlaps are not in MUON... I don't know if they are real or not... I hope no

**Comment by bsunanda** [comment]
I shall have a look - do we have a most up-to-date PPS in the IB?
________________________________

**Comment by slomeo** [comment]
I'm reading the log of the failed test, but I don't understand exactly what is the error? This one: "===== Test "test2021Geometry" ====
cmsExtendedGeometry2021ZeroMaterialXML_cfi.py differs
cmsExtendedGeometry2021ZeroMaterial.xml differs"

**Comment by kpedro88** [comment]
@slomeo you have to update all relevant geometries in the geometry script:
https://github.com/cms-sw/cmssw/tree/master/Configuration/Geometry#run-3-geometries

**Comment by slomeo** [comment]
@kpedro88 : I changed only the muonYoke.xml (putting it in a new directory 2021/v4) and I edited dict2021Geometry.py, do I need to create a M2 for Scenario2021 instead of M1?

**Comment by kpedro88** [comment]
@slomeo you do not need to create a new subdetector version. You need to run `generate2021Geometry.py` for *all* 2021 scenarios that use the M1 subdetector. As shown in the readme I previously linked, there are two detector combinations: `2021` and `2021ZeroMaterial`.

**Comment by slomeo** [comment]
@kpedro88 : Ok, now I understand

**Comment by civanch** [comment]
please test

**Comment by cvuosalo** [comment]
@slomeo In the PR description, please write that the picture shows, after this PR, no Muon overlaps but apparent remaining overlaps in PPS and ZDC.

**Comment by cvuosalo** [comment]
+1

**Comment by slomeo** [comment]
> @slomeo In the PR description, please write that the picture shows, after this PR, no Muon overlaps but apparent remaining overlaps in PPS and ZDC.

@cvuosalo : I updated the PR description.

**Comment by vargasa** [comment]
Hi Sergio. Can you make a comment with the list of remaining overlaps in
CMS from your (g4) logs in the issue please? (To keep it updated) Thanks a
lot!

**Comment by slomeo** [comment]
@vargasa : please find below (see [+]) what you requested.

**CAVEAT**: in this list I added only the name of the volumes where are present overlaps but the number of the overlaps is greater than then the number of the volumes listed here, for example:
 ----
Overlap is detected for volume EHAWR_1:1 (G4SubtractionSolid) with EHAWR_2:2  
and 
Overlap is detected for volume EHAWR_2:2 (G4SubtractionSolid) with its mother volume EFAW
----
(i.e EHAWR_2:2 is cited two times, and so on)

For the complete list please see /afs/cern.ch/user/s/slomeo/public/Overlaps/overlaps.out 

[+]
          Overlap is detected for volume ebalgo:ESPM_1:1 (G4SubtractionSolid)
          Overlap is detected for volume ebalgo:ESPM_2:2 (G4SubtractionSolid)
          Overlap is detected for volume ebalgo:ESPM_3:3 (G4SubtractionSolid)
          Overlap is detected for volume ebalgo:ESPM_4:4 (G4SubtractionSolid)
          Overlap is detected for volume ebalgo:ESPM_5:5 (G4SubtractionSolid)
          Overlap is detected for volume ebalgo:ESPM_6:6 (G4SubtractionSolid)
          Overlap is detected for volume ebalgo:ESPM_7:7 (G4SubtractionSolid)
          Overlap is detected for volume ebalgo:ESPM_8:8 (G4SubtractionSolid)
          Overlap is detected for volume ebalgo:ESPM_9:9 (G4SubtractionSolid)
          Overlap is detected for volume ebalgo:ESPM_10:10 (G4SubtractionSolid)
          Overlap is detected for volume ebalgo:ESPM_11:11 (G4SubtractionSolid)
          Overlap is detected for volume ebalgo:ESPM_12:12 (G4SubtractionSolid)
          Overlap is detected for volume ebalgo:ESPM_13:13 (G4SubtractionSolid)
          Overlap is detected for volume ebalgo:ESPM_14:14 (G4SubtractionSolid)
          Overlap is detected for volume ebalgo:ESPM_15:15 (G4SubtractionSolid)
          Overlap is detected for volume ebalgo:ESPM_16:16 (G4SubtractionSolid)
          Overlap is detected for volume ebalgo:ESPM_17:17 (G4SubtractionSolid)
          Overlap is detected for volume ebalgo:ESPM_18:18 (G4SubtractionSolid)
          Overlap is detected for volume ebalgo:ESPM_19:19 (G4SubtractionSolid)
          Overlap is detected for volume ebalgo:ESPM_20:20 (G4SubtractionSolid)
          Overlap is detected for volume ebalgo:ESPM_21:21 (G4SubtractionSolid)
          Overlap is detected for volume ebalgo:ESPM_22:22 (G4SubtractionSolid)
          Overlap is detected for volume ebalgo:ESPM_23:23 (G4SubtractionSolid)
          Overlap is detected for volume ebalgo:ESPM_24:24 (G4SubtractionSolid)
          Overlap is detected for volume ebalgo:ESPM_25:25 (G4SubtractionSolid)
          Overlap is detected for volume ebalgo:ESPM_26:26 (G4SubtractionSolid)
          Overlap is detected for volume ebalgo:ESPM_27:27 (G4SubtractionSolid)
          Overlap is detected for volume ebalgo:ESPM_28:28 (G4SubtractionSolid)
          Overlap is detected for volume ebalgo:ESPM_29:29 (G4SubtractionSolid)
          Overlap is detected for volume ebalgo:ESPM_30:30 (G4SubtractionSolid)
          Overlap is detected for volume ebalgo:ESPM_31:31 (G4SubtractionSolid)
          Overlap is detected for volume ebalgo:ESPM_32:32 (G4SubtractionSolid)
          Overlap is detected for volume ebalgo:ESPM_33:33 (G4SubtractionSolid)
          Overlap is detected for volume ebalgo:ESPM_34:34 (G4SubtractionSolid)
          Overlap is detected for volume ebalgo:ESPM_35:35 (G4SubtractionSolid)
          Overlap is detected for volume ebalgo:ESPM_36:36 (G4SubtractionSolid)
          Overlap is detected for volume EHAWR_1:1 (G4SubtractionSolid)
          Overlap is detected for volume EHAWR_2:2 (G4SubtractionSolid)
          Overlap is detected for volume esalgo:SFAbs1PbLinPb_1:1 (G4SubtractionSolid)
          Overlap is detected for volume esalgo:SFAbs1PbLOutAl_1:1 (G4SubtractionSolid)
          Overlap is detected for volume esalgo:SFAbs2PbLinPb_1:1 (G4SubtractionSolid)
          Overlap is detected for volume esalgo:SFAbs2PbLOutAl_1:1 (G4SubtractionSolid)
          Overlap is detected for volume RP_220_Right_Station_1:1 (G4Tubs)
          Overlap is detected for volume BumpBond_1:1 (G4Box)
          Overlap is detected for volume BumpBond_2:2 (G4Box)
          Overlap is detected for volume BumpBond_3:3 (G4Box)
          Overlap is detected for volume BumpBond_4:4 (G4Box)
          Overlap is detected for volume BumpBond_5:5 (G4Box)
          Overlap is detected for volume BumpBond_6:6 (G4Box)
          Overlap is detected for volume Bottom_Wall_1:1 (G4SubtractionSolid)
          Overlap is detected for volume CTPPS_Diamond_Main_Box_1:1 (G4UnionSolid)
          Overlap is detected for volume CTPPS_Diamond_Plane_1:1 (G4Box)
          Overlap is detected for volume CTPPS_Diamond_Plane_2:2 (G4Box)
          Overlap is detected for volume CTPPS_Diamond_Plane_3:3 (G4Box)
          Overlap is detected for volume CTPPS_Diamond_Plane_4:4 (G4Box)
          Overlap is detected for volume RP_220_Left_Station_1:1 (G4Tubs)
          Overlap is detected for volume Bottom_Wall_1:1 (G4SubtractionSolid)
          Overlap is detected for volume RP_210_Right_Station_1:1 (G4Tubs)
          Overlap is detected for volume RP_210_Left_Station_1:1 (G4Tubs)

**Comment by kpedro88** [comment]
+upgrade

**Comment by silviodonato** [comment]
> Hi Sergio. Can you make a comment with the list of remaining overlaps in CMS from your (g4) logs in the issue please? (To keep it updated) Thanks a lot!

I see you updated https://github.com/cms-sw/cmssw/issues/31182 with the overlaps

**Comment by silviodonato** [comment]
+1

**Pull request merged**
