### PR TITLE
Fix lostTracks producer not setting lostInnerHits

### PR DESCRIPTION
**Pull request by elusian**
#### PR description:

As shown at the PPD meeting last Thursday, the lostTracks producer has a bug that leaves the `lostInnerHits` of the `PackedCandidate` unset (and thus at its default value of `validHitInFirstPixelBarrelLayer`). Other than in `lostInnerHits` the bug propagates in the number of valid pixel hits and the number of pixel and tracker layers with measurements in the `HitPattern` of the `bestTrack` of the candidate. 

This bug is present in both the V1 and V2 of the miniAOD.

DQM plots showing the effects of the bug in V1 and V2 (from the miniAOD V1 vs V2 validation):
- [lostInnerHits](https://tinyurl.com/y2sjwjck)
- [number of lostInnerHits from the HitPattern](https://tinyurl.com/yyfvawbw)
- [HitPattern has valid hits in the first pixel barrel](https://tinyurl.com/y3lgnxjz)
- [number of valid pixel hits](https://tinyurl.com/y3hsdnb5)
- [number of pixel layers with measurements](https://tinyurl.com/y62ssf3z)
- [number of tracker layer with measurements](https://tinyurl.com/y52hg7ab)

As agreed with xPOG and TAU POG ( @mariadalfonso , @gouskos , @mbluj ), this PR fixes the bug by adding the call to `setLostInnerHits` as the code from the packedPFCandidates producer does. This fix has been checked running the workflow 136.8311 and the issue was solved (see attached figures).

#### PR validation:

This PR has been validated with `runTheMatrix.py -l limited -i all --ibeos` and all checks are ok. 
The final output is 
37 36 35 26 17 4 1 1 1 tests passed, 0 0 0 0 0 0 0 0 0 failed
In particular the DQM output of 136.8311 shows the differences which are expected: inside Tracking/PackedCandidates/lostracks, see above list, all the mentioned plots are now cured.

### CODE REVIEW

**Comment by mtosi** [comment]
it seems the system is preventing @elusian to upload the images (any ideas ?)
in the meantime, here they are

image
image
image
image
image
image

**Comment by mtosi** [comment]
@cmsbuild, please test

**Comment by mtosi** [comment]
bugfix

**Comment by perrotta** [comment]
type bugfix

**Comment by slava77** [comment]
assign xpog

**Comment by jpata** [comment]
+reconstruction
- bugfix for PATLostTracks lostInnerHits
- code changes look fine and in line with the description
- the only relevant changes in the reco monitoring plots are for the lostTracks::qualityFlags/status values, which is expected

**Comment by jpata** [comment]
@cms-sw/xpog-l2 kind ping, this could be a good target for the prerelease tomorrow (urgent).
Also, please clarify the backport plans.
Thanks!

**Comment by mbluj** [comment]
UL reMiniAOD production is ongoing so I do not see reasons of backport to 106X. Are any productions for physics expected with CMSSW>106X and <master (113X) (e.g. run-3 ore-production)? If not, I do not see a use-case for taus.

**Comment by mariadalfonso** [comment]
+xpog
changes inline with description

**Comment by mariadalfonso** [comment]
@elusian

please backport to 11_2 so that it enter the release for the reminiAOD for HeavyIon

**Comment by qliphy** [comment]
+1

**Pull request merged**
