### PR TITLE
Changing the name of the path HLT_Ele23_WPLoose_Gsf_CentralPFJet30_BTagCVS07_v1 to HLT_Ele23_WPLoose_Gsf_CentralPFJet30_BTagCSV07_v1 (cvs -> csv)

### PR DESCRIPTION
**Pull request by soureek**
The name of one of the back up path for Top:
HLT_Ele23_WPLoose_Gsf_CentralPFJet30_BTagCVS07_v1
is changed to 
HLT_Ele23_WPLoose_Gsf_CentralPFJet30_BTagCSV07_v1

(cvs->csv)

in the following files
DQMOffline/Trigger/python/singletopHLTEventDQM_cfi.py
DQMOffline/Trigger/python/topSingleLeptonHLTEventDQM_cfi.py
HLTriggerOffline/Top/python/singletopHLTEventValidation_cfi.py
HLTriggerOffline/Top/python/topSingleLeptonHLTEventValidation_cfi.py

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
@Soureek89 
please change the title of this PR to something meaningful for the release notes.

**Comment by Soureek89** [comment]
The name of the PR has been changed.

**Comment by deguio** [comment]
@Soureek89 
please just remove the commented lines. they are anyway available in the git history.
thanks,
F.

**Comment by Soureek89** [comment]
I have removed the commented lines in the 4 relevant files. Please check.

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
