### PR TITLE
Fixes in HLTriggerOffline/SUSYBSM (rebase of #8137)

### PR DESCRIPTION
**Pull request by jruizvar**
Correct names according to trigger menu /dev/CMSSW_7_4_0/GRun/V33. This request supersedes #8137. 

The corresponding PR for 75X was done in #8177

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by jruizvar** [comment]
By mistake I had deleted some parameters yielding the errors above. I have put the parameters back. 

Could you please run the test again? Thanks, and sorry for the inconveniences.

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Comment by davidlange6** [comment]
@jruizvar - it looks like this PR no longer merges - could you rebase it please. Thanks

**Comment by jruizvar** [comment]
We are waiting new modules to be added in the HLTriggerOffline/SUSYBSM package. In my opinion, #9027 should be merged first and then I will rebase this.

**Comment by deguio** [comment]
@jruizvar 
#9027 also needs a rebase. could you take care of that?
thanks,
F.

**Comment by davidlange6** [comment]
#9027 will also need 75x testing - so perhaps its best that I close this PR and a new one can be opened next week with the combined request.

**Pull request closed without merging**
