### PR TITLE
Run3-sim88 Make use of ESGetToken in a number of Analyzers used for SIM data

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Make use of ESGetToken in a number of Analyzers used for SIM data

#### PR validation:

Test using cfg's in the test areas

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by bsunanda** [comment]
@srimanob Please approve this

**Comment by srimanob** [comment]
+Upgrade

**Comment by qliphy** [comment]
"Reco comparison results: 5125 differences found in the comparisons"

@bsunanda  Just to confirm, are the differences expected?

**Comment by srimanob** [comment]
@qliphy 
Thanks for rechecking. I missed that warning. 
The change in code is on HGCAL, but the PR also touches include lines in SimG4CMS which I don't expect to see a change.

**Comment by perrotta** [comment]
please test
(let give another try: it is hard to believe that this simulation related PR can affect in such a relevant way miniAOD jets, also in real data workflow)

**Comment by perrotta** [comment]
Now there are widespread differences only in the HI workflow 140.53. But the input datasets used for the output comparisons [in the baseline](https://cmssdt.cern.ch/SDT/jenkins-artifacts/ib-baseline-tests/CMSSW_12_0_X_2021-07-17-1100/slc7_amd64_gcc900/-GenuineIntel/matrix-results/140.53_RunHI2011+RunHI2011+RECOHID11+HARVESTDHI/step1_dasquery.log) and [in the PR test](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-9d78fa/16953/runTheMatrix-results/140.53_RunHI2011+RunHI2011+RECOHID11+HARVESTDHI/step1_dasquery.log) are different. Therefore these differences are explained.

**Comment by perrotta** [comment]
I think that the differences observed in miniAOD jets during the [previous comparisons](https://github.com/cms-sw/cmssw/pull/34405#issuecomment-876740525) were transient: it may be interesting to understand what was who originated them, but it is quite unlikely that it was due to this PR

**Comment by bsunanda** [comment]
The differences are due to input changes. This PR only changes how the analyzers should access objects from Event Setup. They do not modify the Event in any way. These are not producers.

**Comment by srimanob** [comment]
+Upgrade

Yeah, the last test looks better.

**Comment by perrotta** [comment]
+1

**Pull request merged**
