### PR TITLE
[DBG] Fix comparison of integer expressions of different signedness

### LINKED ISSUE #42331: [DBG_X] Compilation failure due to signed/unsigned comparision in SiPixelDigisClustersFromSoAT
Compilation failure in IB CMSSW_13_3_DBG_X_2023-07-20-2300 ([full log](https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/el8_amd64_gcc11/CMSSW_13_3_DBG_X_2023-07-20-2300/RecoLocalTracker/SiPixelClusterizer)):
```
/data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/9a03ff54ef53dbd2dc0132c33064f253/opt/cmssw/el8_amd64_gcc11/cms/cmssw/CMSSW_13_3_DBG_X_2023-07-20-2300/src/RecoLocalTracker/SiPixelClusterizer/plugins/SiPixelDigisClustersFromSoA.cc: In instantiation of 'void SiPixelDigisClustersFromSoAT<TrackerTraits>::produce(edm::StreamID, edm::Event&, const edm::EventSetup&) const [with TrackerTraits = pixelTopology::HIonPhase1]':
/data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/9a03ff54ef53dbd2dc0132c33064f253/opt/cmssw/el8_amd64_gcc11/cms/cmssw/CMSSW_13_3_DBG_X_2023-07-20-2300/src/RecoLocalTracker/SiPixelClusterizer/plugins/SiPixelDigisClustersFromSoA.cc:74:6:   required from here
  /data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/9a03ff54ef53dbd2dc0132c33064f253/opt/cmssw/el8_amd64_gcc11/cms/cmssw/CMSSW_13_3_DBG_X_2023-07-20-2300/src/RecoLocalTracker/SiPixelClusterizer/plugins/SiPixelDigisClustersFromSoA.cc:186:26: error: comparison of integer expressions of different signedness: 'int32_t' {aka 'int'} and 'const uint32_t' {aka 'const unsigned int'} [-Werror=sign-compare]
   186 |     assert(digis.clus(i) < TrackerTraits::maxNumClustersPerModules);
      |            ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/9a03ff54ef53dbd2dc0132c33064f253/opt/cmssw/el8_amd64_gcc11/cms/cmssw/CMSSW_13_3_DBG_X_2023-07-20-2300/src/RecoLocalTracker/SiPixelClusterizer/plugins/SiPixelDigisClustersFromSoA.cc: In instantiation of 'void SiPixelDigisClustersFromSoAT<TrackerTraits>::produce(edm::StreamID, edm::Event&, const edm::EventSetup&) const [with TrackerTraits = pixelTopology::Phase2]':
/data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/9a03ff54ef53dbd2dc0132c33064f253/opt/cmssw/el8_amd64_gcc11/cms/cmssw/CMSSW_13_3_DBG_X_2023-07-20-2300/src/RecoLocalTracker/SiPixelClusterizer/plugins/SiPixelDigisClustersFromSoA.cc:74:6:   required from here
  /data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/9a03ff54ef53dbd2dc0132c33064f253/opt/cmssw/el8_amd64_gcc11/cms/cmssw/CMSSW_13_3_DBG_X_2023-07-20-2300/src/RecoLocalTracker/SiPixelClusterizer/plugins/SiPixelDigisClustersFromSoA.cc:186:26: error: comparison of integer expressions of different signedness: 'int32_t' {aka 'int'} and 'const uint32_t' {aka 'const unsigned int'} [-Werror=sign-compare]
 /data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/9a03ff54ef53dbd2dc0132c33064f253/opt/cmssw/el8_amd64_gcc11/cms/cmssw/CMSSW_13_3_DBG_X_2023-07-20-2300/src/RecoLocalTracker/SiPixelClusterizer/plugins/SiPixelDigisClustersFromSoA.cc: In instantiation of 'void SiPixelDigisClustersFromSoAT<TrackerTraits>::produce(edm::StreamID, edm::Event&, const edm::EventSetup&) const [with TrackerTraits = pixelTopology::Phase1]':
/data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/9a03ff54ef53dbd2dc0132c33064f253/opt/cmssw/el8_amd64_gcc11/cms/cmssw/CMSSW_13_3_DBG_X_2023-07-20-2300/src/RecoLocalTracker/SiPixelClusterizer/plugins/SiPixelDigisClustersFromSoA.cc:74:6:   required from here
  /data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/9a03ff54ef53dbd2dc0132c33064f253/opt/cmssw/el8_amd64_gcc11/cms/cmssw/CMSSW_13_3_DBG_X_2023-07-20-2300/src/RecoLocalTracker/SiPixelClusterizer/plugins/SiPixelDigisClustersFromSoA.cc:186:26: error: comparison of integer expressions of different signedness: 'int32_t' {aka 'int'} and 'const uint32_t' {aka 'const unsigned int'} [-Werror=sign-compare]
 cc1plus: some warnings being treated as errors
```

Pinging @AdrianoDee as the author of https://github.com/cms-sw/cmssw/pull/41632

### PR DESCRIPTION
**Pull request by smuzaffar**
Fixes https://github.com/cms-sw/cmssw/issues/42331

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test for CMSSW_13_3_DBG_X
(just to see if compilation/build issue is fixed)

**Comment by smuzaffar** [comment]
@cms-sw/reconstruction-l2 , can you please review this. This is to fix the DBG IBs build issues. The Pr results for production arch are available https://github.com/cms-sw/cmssw/pull/42405#issuecomment-1655541797

**Comment by mandrenguyen** [comment]
@smuzaffar Were you expecting all these failing tests?

**Comment by mmusich** [comment]
> Were you expecting all these failing tests?

I think one does:

   *  in https://github.com/cms-sw/cmssw/issues/41088 already / seen reported
```   
----- Begin Fatal Exception 28-Jul-2023 15:14:53 CEST-----------------------
An exception of category 'Invalid DetId' occurred while
   [0] Calling method for module HGCalBackendLayer1Producer/'l1tHGCalBackEndLayer1Producer'
   [1] Prefetching for EventSetup module HGCalTriggerGeometryESProducer/'l1tHGCalTriggerGeometryESProducer'
   [2] Calling method for EventSetup module HGCalGeometryESProducer/'HFNoseGeometryESProducer'
Exception Message:
Cannot initialize HGCSiliconDetId from 6c8bd800
----- End Fatal Exception -------------------------------------------------
```

   *  in https://github.com/cms-sw/cmssw/issues/42162 already seen / reported
```
----- Begin Fatal Exception 28-Jul-2023 11:30:09 CEST-----------------------
An exception of category 'CorruptedData' occurred while
   [0] Processing  Event run: 362321 lumi: 231 event: 111758106 stream: 0
   [1] Running path 'HLT_HIZeroBias_v6'
   [2] Calling method for module SiStripClusters2ApproxClusters/'hltSiStripClusters2ApproxClusters'
Exception Message:
[SiStripNoises::getNoise] looking for SiStripNoises for a strip out of range: strip 512
----- End Fatal Exception -------------------------------------------------
```

**Comment by smuzaffar** [comment]
yes @mandrenguyen , this PR only fixes the build part. relval failures need more fixes as mentioned https://github.com/cms-sw/cmssw/pull/42405#issuecomment-1660169643

**Comment by perrotta** [comment]
+1

**Pull request merged**
