### PR TITLE
Backport muon shower (un)packing and DQM to 12_2_X

### PR DESCRIPTION
**Pull request by dinyar**
#### PR description:

This is a backport PR comprising multiple original ones. It contains unpackers and packers for hadronic showers at the uGMT inputs and outputs as well as the DQM for muon showers. 

Ideally this should be used in the P5 DQM as soon as possible, could you let me know if this isn't the correct branch to target for this?

attn: @vukasinmilosevic 

#### PR validation:

Ran `runTheMatrix.py -l limited -i all --ibeos` as well as `scram b runtests` after rebasing/cherry-picking.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Original PRs:
* #35627
* #36462
* #36877
* #36920

I would like to have these changes available in the DQM at P5. They are not required for T0 or HLT.

### CODE REVIEW

**Comment by jfernan2** [comment]
12_2_X at present is the right branch to target Online DQM, it will be tested tomorrow

**Comment by jfernan2** [comment]
test parameters:
- addpkg = DQM/Integration

**Comment by jfernan2** [comment]
please test

**Comment by perrotta** [comment]
@dinyar could you please verify and confirm that whatever is backported here for 12_2_X is already available in the master AND in 12_3_X?
12_3_X will become rather soon the new datataking releas in place of 12_2_X, and whatever is implemented in 12_2 cannot miss in the newer cycle that will subsitute it at P5

**Comment by dinyar** [comment]
Hi @perrotta,

Yes, I confirm that is the case. (I checked that the PRs listed all had milestone CMSSW_12_3_X and that all commits in this PR are present in those PRs.)

Cheers,
Dinyar

**Comment by jfernan2** [comment]
+1
Tested successfully in Online DQM at P5 (no crashes). Minor differences due to changes in the PR description:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_2_X_2022-03-13-0000+73f863/48913/dqm-histo-comparison-summary.html

**Comment by perrotta** [comment]
+1
- It faithfully reproduces the four PRs listed in the PR description and already merged in 12_3_X and in the master

**Comment by dinyar** [comment]
> +1 Tested successfully in Online DQM at P5 (no crashes). Minor differences due to changes in the PR description: https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_2_X_2022-03-13-0000+73f863/48913/dqm-histo-comparison-summary.html


Hi @jfernan2,

I think this hasn't been deployed to online DQM yet, correct? It's not urgent, but do you have a timeline already for when I should expect it? (If there is something needed from my side please also let me know.)

Cheers,
Dinyar

**Comment by ahmad3213** [comment]
> I think this hasn't been deployed to online DQM yet, correct?

Correct

 > It's not urgent, but do you have a timeline already for when I should expect it? (If there is something needed from my side please also let me know.)

We can try to put in production today

**Pull request merged**
