### PR TITLE
Make puppi algo better readable

### PR DESCRIPTION
**Pull request by ahinzmann**
Make puppi algo better readable. Consistently use one ID for particles throughout the code.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

curiously enough, there is no overlap in the context lines with #27929

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/28104	062fa20 
- somewhat technical cleanup
- jenkins tests pass and comparisons with the baseline show no differences

**Comment by fabiocos** [comment]
it looks like there is no real conflict with other open PRs, so it may enter

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

@santocch please have a look

**Comment by santocch** [comment]
+1

**Pull request merged**
