### PR TITLE
Backport particle level runtime improvements for Nano 106X

### PR DESCRIPTION
**Pull request by kdlong**
#### PR description:

Backport particle level runtime improvements for Nano

#### PR validation:

Tested Nano v8 sequence

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Backport of #34590

For more efficient running (avoid re-running jet clustering, particle level producer multiple times) of NanoAOD, which stays in 106 for the immediate future.

### CODE REVIEW

**Comment by mariadalfonso** [comment]
please test

**Comment by agrohsje** [comment]
+generators

**Comment by mariadalfonso** [comment]
+xpog

verified no changes introduced in the nano-content
this is intended fo speed up of nano-prodution

**Comment by perrotta** [comment]
Identical backport of #34590

**Comment by perrotta** [comment]
please test

**Comment by qliphy** [comment]
+1

**Pull request merged**
