### PR TITLE
Update for GEN infos in 74X or later

### PR DESCRIPTION
**Pull request by emiglior**
This PR superseeds #10071. 
In addition to the previous changes it includes the first round of modifications to fill properly the GEN level infos from pythia8 and NLO Monte Carlo generators.
RECO is not affected.
@maralxplus, @mabarrio This can be of interest for you as well as it affects the format of the trees created by MuScleFit  as it includes an event weight useful for NLO MC,

### CODE REVIEW

**Comment by davidlange6** [comment]
what is the 76x and 75x version of this pr?

**Comment by emiglior** [comment]
@davidlange6 The PR for 75x is #10477 
I  have not yet prepared the PR for 76x

**Comment by monttj** [comment]
please test

**Comment by monttj** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
