### PR TITLE
PPS DQM plots for new RPOTs 45-220-NR-HR and 56-220-NR-HR (backport of 41389) [13_1_X]

### PR DESCRIPTION
**Pull request by grzanka**
#### PR description:

This PR adds new plots to the DQM for two Roman Pots (previously not included in DQM).
Is it needed in the Online DQM GUI

#### PR validation:

Standard runTheMatrix and manual tests on new data by @smorovic

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport of https://github.com/cms-sw/cmssw/pull/41389

### CODE REVIEW

**Comment by smorovic** [comment]
please test

**Comment by emanueleusai** [comment]
type ctpps

**Comment by emanueleusai** [comment]
backport of https://github.com/cms-sw/cmssw/pull/41389

**Comment by emanueleusai** [comment]
please test

**Comment by smorovic** [comment]
+1

**Comment by mandrenguyen** [comment]
+1

**Comment by emanueleusai** [comment]
+1

**Comment by rappoccio** [comment]
+1

**Pull request merged**
