### PR TITLE
Removed unused fwkJobReports from MessageLogger in EventFilter Subsystem

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

The parameter fwkJobReports is an obsolete parameter which has had no functionality for many years.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
@cms-sw/l1-l2 please sign, this pull request is holding up further development.

**Comment by Dr15Jones** [comment]
@cms-sw/l1-l2 ping

**Comment by silviodonato** [comment]
merge
@cms-sw/l1-l2

**Pull request merged**
