### PR TITLE
[CORE] Apply code-checks/format

### PR DESCRIPTION
**Pull request by smuzaffar**
code-checks/format applied on full cmssw with extra misc-definitions-in-headers clang-tidy check

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by makortel** [comment]
@cmsbuild, please test

I'd like to see cleaner comparisons (even if the code changes are trivial).

**Comment by makortel** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
