### PR TITLE
PCL SiPixel Alignment: integration of quality checks on payload and DQM module

### PR DESCRIPTION
**Pull request by cerminar**
This PR modifies only the PCL sequences for the alignment of the Pixel large structures.
It integrates the needed checks for the creation of the payload and the DQM module to monitor the movements of the alignables.

This is needed to start testing the new workflow in production environment.

This is equivalent to PR #13983 for 81X.

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
+1

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
+1
provided jenkins agrees

**Comment by davidlange6** [comment]
+1

**Pull request merged**
