### PR TITLE
remove some deprecation warnings from `DQMServices/Components`

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

Title says it all, remove *some* deprecation warnings from `DQMServices/Components`.
In response to https://github.com/cms-sw/cmssw/pull/37665#issuecomment-1113664103
Technical, part of the migrations in https://github.com/cms-sw/cmssw/issues/36404.
Profited to clean-up headers and merging plugin header with implementations.

#### PR validation:

`cmssw` compiles

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

### CODE REVIEW

**Comment by mmusich** [comment]
Screenshot from 2022-04-29 23-28-54

ah, I see now that the conflicts are coming from https://github.com/cms-sw/cmssw/pull/37706/.
Will rebase once there's an IB with it.

**Comment by emanueleusai** [comment]
please test

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by emanueleusai** [comment]
+1

**Comment by qliphy** [comment]
@mmusich  Please have a look at some Static Checks warnings:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-a0a8e9/24454/llvm-analysis/runStaticChecks.log

**Comment by mmusich** [comment]
@qliphy none of these have been introduced by me, see please the SA output of [CMSSW_12_4_X_2022-05-05-2300](https://cmssdt.cern.ch/SDT/jenkins-artifacts/ib-static-analysis/CMSSW_12_4_X_2022-05-05-2300/slc7_amd64_gcc10/llvm-analysis/index.html):

Screenshot from 2022-05-06 10-22-05

Screenshot from 2022-05-06 10-22-25

Screenshot from 2022-05-06 10-22-43

as such they should be treated by the DQM core team.

**Comment by qliphy** [comment]
+1

**Pull request merged**
