### PR TITLE
Ignoring raw channel ids in the unit test database dump comparison

### PR DESCRIPTION
**Pull request by igv4321**
#### PR description:

Purely technical update of a unit test, will not affect any workflows. Avoiding raw channel id comparison in the unit test of the database dump, as these ids can change.

#### PR validation:

Unit test was successfully run.

### CODE REVIEW

**Comment by perrotta** [comment]
Thank you @igv4321 
As soon as @bsunanda will revert the commit that comments out the unit test in #43200, these two PRs can be tested together.
One question: why do you need to ignore the raw channel ids in the comparison? IOW, why is it not possible to modify the reference file CondTools/Hcal/data/hcalpfcuts.txt to take into account the modified raw channel IDs?

**Comment by igv4321** [comment]
@bsunanda answered why raw channel ids should be ignored in https://github.com/cms-sw/cmssw/pull/43200#issuecomment-1798630729 

It is possible to modify CondTools/Hcal/data/hcalpfcuts.txt, but if raw channel ids are to be ignored, there is no point in doing that.

**Comment by bsunanda** [comment]
I am a bit confused now. Should I bring back the Unit test? Please let me know
________________________________

**Comment by perrotta** [comment]
> I am a bit confused now. Should I bring back the Unit test? Please let me know

Yes @bsunanda please bring back the unit test: it will succeed once this PR gets merged

**Comment by perrotta** [comment]
> @bsunanda answered why raw channel ids should be ignored in [#43200 (comment)](https://github.com/cms-sw/cmssw/pull/43200#issuecomment-1798630729)

What I did not understand from that answer is the following:
- is the comparison of the rawID values useless, in that case it is perfectly fine to remove it from the test;
- or it is still useful to be performed but it "requires changes in the code as well as [] in the data area", in which case I would apply those required changes to maintain the functionality to compare the rawID values.

In the first case, I think this PR is perfect as such. In the second case I would update it so that the comparison of the rawID values is still possible.

**Comment by igv4321** [comment]
I am not sure if the comparison of the rawID values is useful or useless, perhaps @bsunanda can comment on that. The point of this particular unit test is to ensure that the text and the database I/O work correctly for HcalPFCuts. Validation of Hcal channel mapping schemes is beyond the intended scope of this test.

**Comment by bsunanda** [comment]
Well we have to modify the DetId definition. This requires changes in the RawID value - we have to specify some bits to define the format of the RawID and that clearly changes RawId value from past to present. I am not sure if such changes will be there in the future. This is the second DetID where the internal bit definitions need to be modified. There were other DetId's which were changed - there we have to go from one class to another class. In any case, RawID is supposed to be a private member and playing with its bits should be kept provate.
________________________________

**Comment by perrotta** [comment]
please test with #43200

**Comment by perrotta** [comment]
@cms-sw/orp-l2 this PR is needed by https://github.com/cms-sw/cmssw/pull/43200, but since it only removes one check from a test unit it can even be merged independently (even though having tested them together it apparently "requires externals" to get merged)

**Comment by antoniovilela** [comment]
> @cms-sw/orp-l2 this PR is needed by #43200, but since it only removes one check from a test unit it can even be merged independently (even though having tested them together it apparently "requires externals" to get merged)

Thanks

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
