### PR TITLE
remove ifdefs in DataFormats/Common

### PR DESCRIPTION
**Pull request by davidlange6**
Remove ROOTCLING ifdefs. This means I could also remove the ifdefs around DSVN_USE_ATOMIC.
This does trigger a new class version.

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by silviodonato** [comment]
please test

**Comment by davidlange6** [comment]
Why? These will just fail again

On Jul 28, 2020, at 4:45 PM, Silvio Donato <notifications@github.com<mailto:notifications@github.com>> wrote:



please test

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
please test

**Comment by makortel** [comment]
> make offset in DetSetVectorTrans::Item persistent as it needs to be

I wonder how it worked before if `DetSetVectorTrans::Item::offset` should have been persistent (or it didn't and the part of `edmNew::DetSetVector` interface using `offset` is not (heavily) used?).

**Comment by davidlange6** [comment]
I’m wondering that too:) but I’ll eventually convince root to convert it properly I think

**Comment by davidlange6** [comment]
please test

**Comment by makortel** [comment]
> > make offset in DetSetVectorTrans::Item persistent as it needs to be
> 
> I wonder how it worked before if `DetSetVectorTrans::Item::offset` should have been persistent (or it didn't and the part of `edmNew::DetSetVector` interface using `offset` is not (heavily) used?).

I confused myself, in master the `DetSetVectorTrans::Item::offset` is persistent.

**Comment by makortel** [comment]
@Dr15Jones Could you take a look of this as well?

**Comment by Dr15Jones** [comment]
@makortel I actually had taken a look and didn't seem anything obvious. As long as the backwards compatibility was checked (which I believe @davidlange6 did) then it should be OK.

**Comment by makortel** [comment]
Thanks Chris.

**Comment by makortel** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
