### PR TITLE
Make sure task object is owned by the lambda for prePrefetchSelectionAsync call

### PR DESCRIPTION
**Pull request by Dr15Jones**
The Service's were not being deleted in the case that prePrefetchSelectionAsync is called
and the selection rejected an event. This was because the ServiceToken was being held by
the RunModuleTask object and that object was never destroyed. Using a helper class held
by an std::shared_ptr we can make sure the task is deleted if the task is not going to
be run.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
Fixes bug introduced in #21035

**Comment by Dr15Jones** [comment]
The test failures are from the IB not this pull request

**Comment by Dr15Jones** [comment]
+1

**Comment by davidlange6** [comment]
merge

**Pull request merged**
