### PR TITLE
Fix a minor error in DQM/L1TMonitor BuildFile

### PR DESCRIPTION
**Pull request by dmitrijus**
It needs to generate a proper edm plugin.

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1

**Comment by smuzaffar** [comment]
as this is now proper plugin so other package e.g. DQMOffline/L1Trigger can not link against it. You need tio cleanup this dependency. We have a build errror due to this in IBs

**Comment by smuzaffar** [comment]
@davidlange6 , we need to revert it (if there is no fix already approved) to get a working IB

**Comment by deguio** [comment]
ok, thanks. I will ask dmitrijus to submit a proper fix.
how did it pass the tests in 81x? I see that the corresponding PR #13620 is failing in 80x as expected.

**Comment by smuzaffar** [comment]
cms-checkdeps should have checked out DQMOffline/L1Trigger locally and then it should have failed but looks like cms-checkdeps is not reading the full dependency information from the patch and full release. I am looking in to this.

**Comment by smuzaffar** [comment]
OK, it is not that bad. It does read the dependency information for headers and python files but not for BuildFiles. This needs to be fixed in cmsdist for building patch releases. I will update cmsdist to generate full dependency information for BuildFiles too.

**Comment by dmitrijus** [comment]
Did not expect this package to be a dependency, just plugins.
Closing this PR, I will make another proper PR with library + plugins.

**Pull request merged**
