### PR TITLE
Move run2 era to run2_common

### PR DESCRIPTION
**Pull request by mark-grimes**
This is on top of #7839 which is most of the changes, so I guess most of the discussion should be on there.

I put this in a separate pull request so that the changes are clear (although at the moment the #7839 changes are also shown here).  This pull request changes all of the `run2` era modifications to `run2_common` then removes the `run2` era.  Users should specify `Run2_25ns`, `Run2_50ns` or `Run2_HI` instead, all of which include any `run2_common` changes.

This touches a lot of packages but the changes are trivial.

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
should this one be submitted to 75 as well?

**Comment by slava77** [comment]
Did jenkins get stuck?
It's been a while since the tests were triggered.

**Comment by mark-grimes** [comment]
> should this one be submitted to 75 as well?

I guess it needs to go in at some point.  Shall I put in pull requests for everything or can they be duplicated automatically?

**Comment by civanch** [comment]
+1

**Comment by lveldere** [comment]
+1

**Pull request merged**
