### PR TITLE
[backport to 12_4_X] modify nanoDQMIO configuration

### PR DESCRIPTION
**Pull request by LukaLambrecht**
#### PR description:

This PR prepares the production of the nanoDQMIO dataset for 2022 data.
The modifications are twofold:

- The configuration file listing the monitoring elements (MEs) to be stored is modified in accordance with the requests from subsystems.
- The selection of the MEs is changed so that only those MEs that exactly match a pattern in the configuration file are stored. Previously, each ME that contained a pattern in the configuration file was stored, leading to the storing of some unneeded MEs with overlapping names.

More information on the context of this PR can be found in this [google doc](https://docs.google.com/document/d/1VvDBvkMlKeJWKg9km30Kg3f1Lv3KB2HXE9Ne4HBbKLo/edit?usp=sharing) (note: under development, subject to change).

#### PR validation:

The modified selection and configuration was used to produce nanoDQMIO files locally. No issues were observed and the content of the nanoDQMIO file in terms of ME content is as expected. The usual runTheMatrix.py -l limited -i all --ibeos tests were run for the original PR to master.

#### Backport

This is a backport of [PR40266](https://github.com/cms-sw/cmssw/pull/40266).
It is needed since we would use the updated nanoDQMIO configuration for the reprocessing of 2022 data.

### CODE REVIEW

**Comment by rvenditti** [comment]
please test

**Comment by LukaLambrecht** [comment]
Sorry for an additional commit, but two more MEs for ECAL were requested.
The commit does not affect any source code, only two additions to the nanoDQMIO configuration file.

**Comment by rvenditti** [comment]
please test

**Comment by emanueleusai** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
