### PR TITLE
Various fixes for pixel clustering on GPU [12.4.x]

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Various fixes for pixel clustering on GPU:
  - when building in debug mode (`g++ -DGPU_DEBUG`) synchronise only the current stream instead of the whole device after each operation;
  - size the kernel grid based on the correct number of pixel modules for Phase-1;
  - remove obsolete debug statement that does not compile any more.

#### PR validation:

None.

#### If this PR is a backport please specify the original PR and why you need to backport that PR.

Backport of https://github.com/cms-sw/cmssw/pull/38920 for data taking at HLT.

### CODE REVIEW

**Comment by jpata** [comment]
enable gpu

**Comment by jpata** [comment]
@cmsbuild please test

**Comment by fwyzard** [comment]
urgent

I would like to have this in 12.4.x in order to simplify further debugging

**Comment by jpata** [comment]
+reconstruction
- direct backport of https://github.com/cms-sw/cmssw/pull/38920, required for HLT

**Comment by qliphy** [comment]
+1

**Pull request merged**
