### PR TITLE
DQM: Fix broken plots by MuonTrackValidator

### PR DESCRIPTION
**Pull request by schneiml**
#### PR description:

We got a report that in the `11_1_0_pre4` relvals, some Moun Validation plots appear completely black in the DQMGUI. This is due to `NaN`s in the bin limits, which are in turn due to (apparently) not idempotent code in `BinLogX`, called in booking to change the binning of the `vs_pt` plots, which is a problem with the introduction of `edm::stream` based `DQMEDAnalyzer` in pre4.

This issue can be fixed by moving the call to `BinLogX` into a booking callback. This fixes `MuonTrackValidator`, there is another `BinLogX` in another module that might have the same issue.

The issue was not spotted in #28813 for multiple reasons:
- The problem only appears when running multiple streams; therefore not in the normal PR tests.
- The relevant plots are probably never filled in the PR/IB tests. _Basically_ not a problem, as this is a booking issue, but
- The bin-to-bin comparison tool only checks bin values, not axis data. @andrius-k promised an improvement to cover this in the future.

#### PR validation:
Tested multi-threaded using
```
runTheMatrix.py -l 11634.7 -t 8
```
The `NaN`s disappeared (for one random affected ME):
```
diff <(dqmdumpme.py 11634.7_*/DQM_*.root Muons/RecoMuonV/MuonTrack/tevMuons_picky/dzres_vs_pt) <(dqmdumpme.py base/11634.7_*/DQM_*.root Muons/RecoMuonV/MuonTrack/tevMuons_picky/dzres_vs_pt)
83c83
<         0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
...
352,364c352,355
<         0., 0., 0., 0.]], dtype=float32), [(array([8.99999976e-01, 1.04997325e+00, 1.22493768e+00, 1.42905772e+00,
<        1.66719151e+00, 1.94500732e+00, 2.26911759e+00, 2.64723635e+00,
<        3.08836389e+00, 3.60300016e+00, 4.20339298e+00, 4.90383339e+00,
<        5.72099400e+00, 6.67432404e+00, 7.78651285e+00, 9.08403301e+00,
<        1.05977688e+01, 1.23637495e+01, 1.44240093e+01, 1.68275795e+01,
<        1.96316776e+01, 2.29030437e+01, 2.67195320e+01, 3.11719971e+01,
<        3.63664093e+01, 4.24264030e+01, 4.94962120e+01, 5.77441025e+01,
<        6.73664093e+01, 7.85921555e+01, 9.16884918e+01, 1.06967201e+02,
<        1.24791901e+02, 1.45586853e+02, 1.69847031e+02, 1.98149841e+02,
<        2.31168961e+02, 2.69690125e+02, 3.14630493e+02, 3.67059601e+02,
<        4.28225372e+02, 4.99583588e+02, 5.82832764e+02, 6.79954285e+02,
<        7.93259460e+02, 9.25445923e+02, 1.07965955e+03, 1.25957080e+03,
<        1.46946204e+03, 1.71432886e+03, 1.99999963e+03]), array([-0.05 , -0.049, -0.048, -0.047, -0.046, -0.045, -0.044, -0.043,
---
>         0., 0., 0., 0.]], dtype=float32), [(array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
>        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
>        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
>        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]), array([-0.05 , -0.049, -0.048, -0.047, -0.046, -0.045, -0.044, -0.043,
```

### CODE REVIEW

**Comment by schneiml** [comment]
please test

let's see if the tests pick this up. As outlined above, I expect they won't.

**Comment by schneiml** [comment]
I uploaded the output from my private test to a GUI: https://tinyurl.com/w892nvl
The formerly black plots are not black here.

**Comment by jfernan2** [comment]
+1
Muon people agreed on the fix

**Comment by jfernan2** [comment]
urgent

**Comment by jfernan2** [comment]
bugfix

**Comment by jfernan2** [comment]
type bugfix

**Comment by silviodonato** [comment]
+1

**Pull request merged**
