### PR TITLE
[NanoAOD,BTVNano] Btvnano integration as customized module

### PR DESCRIPTION
**Pull request by Ming-Yan**
#### PR description:

- integrate the [PFNano](https://github.com/cms-jet/PFNano/tree/master) to customized NanoAOD module  according to the discussion with [XPOG](https://indico.cern.ch/event/1263032/contributions/5450887/attachments/2671841/4631770/230622_XPOG.pdf)
- additional PFCands, variables to derive SFs are included

time& size report [doc](https://btvweb.web.cern.ch/btvNanoDoc/)

**MC** (test with `/store/mc/Run3Summer22EEMiniAODv4/QCD_PT-15to20_MuEnrichedPt5_TuneCP5_13p6TeV_pythia8/MINIAODSIM/130X_mcRun3_2022_realistic_postEE_v6-v2/2520000/177762d0-23ed-436f-aa0d-a20c33e33dc3.root`)
size :  5.61 kb/event
TimeReport ---------- Event  Summary ---[sec]----
TimeReport       event loop CPU/event = 0.072606
TimeReport      event loop Real/event = 0.032194
TimeReport     sum Streams Real/event = 0.096403
TimeReport efficiency CPU/Real/thread = 0.563817

**data**  (test with `/store/data/Run2022C/BTagMu/MINIAOD/22Sep2023-v1/40000/fc8f31f6-4bf7-4b51-8f6d-ef0833c1e383.root`)
size :  5.91 kb/event
TimeReport ---------- Event  Summary ---[sec]----
TimeReport       event loop CPU/event = 0.101517
TimeReport      event loop Real/event = 0.040990
TimeReport     sum Streams Real/event = 0.139760
TimeReport efficiency CPU/Real/thread = 0.619164

#### PR validation:

- passes the standard runTheMatrix test: runTheMatrix.py -l limited -i all --ibeos

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
-1
wrong branch or rebase needed.

**Comment by mmusich** [comment]
@Ming-Yan could you please rebase your commits such that they merge on the master (CMSSW_14_0_X) branch?

**Comment by Ming-Yan** [comment]
> @Ming-Yan could you please rebase your commits such that they merge on the master (CMSSW_14_0_X) branch?

HI @mmusich thanks for the comments, I am trying to merge to the master branch but I still have some technical issue where  the some files are not present locally.  This is still in progress, sorry about the buggy PR

**Comment by Ming-Yan** [comment]
rebase in other branches close this PR

**Pull request closed without merging**
