### PR TITLE
PCC Event Producer 11_1_X target

### PR DESCRIPTION
**Pull request by samhiggie**
PR description:
Continuation of PR #28807 
and rebase of PR #28992  - will close after verification

Changed some of the names of the producers to match the nomenclature by most modules in cmssw.

Added a fillDescription method so that the new AlCaPCCEventProducer may be added to the HLT configuration

Removed a PSet formatting

PR validation:
Compiles and Runs with local test files and HLT configuration like:
hltGetConfiguration /users/sharper/2019/alca/alcaLumi --setup /dev/CMSSW_10_6_0/GRun/V3 --globaltag auto:run2_hlt_GRun --unprescale > hlt.py
(must replace AlcaPCCProducer with AlcaPCCEventProducer)
FastReport Info:

FastReport CPU time sched. / depend. Real time sched. / depend. Alloc. sched. / depend. Dealloc. sched. / depend. Processes and Paths
FastReport 3.4 ms 3.4 ms 6.3 ms 6.3 ms +3333 kB +3333 kB -3081 kB -3081 kB Alca_LumiPixelsCounts_ZeroBias_v1
FastReport 0.0 ms 0.0 ms 0.1 ms 0.1 ms +0 kB +0 kB +0 kB +0 kB Alca_LumiPixelsCounts_Random_v1

### CODE REVIEW

**Comment by samhiggie** [comment]
Hello @slava77 , I've successfully rebased on this branch. With no conflicts. 

This was frustrating though, as all the commits that I had posted I needed to go through and many contained changes that were not necessary or I changed in order to forget them. In the future, is there a way I can just drop commits that are useless so I don't need to go through each one?
OR  if the state of the branch is in good condition is it possible to just sign off on the conflicts? 

Thanks for the help!

**Comment by samhiggie** [comment]
code formatting suggestions have been applied, thanks @cmsbuild !

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
the error is 
```
   [1] Constructing module: class=AlcaPCCProducer label='alcaPCCProducerZBFromRECO'
Exception Message:
MissingParameter: Parameter 'pixelClusterLabel' not found.
```

**Comment by samhiggie** [comment]
Thanks @slava77 , I will make sure the label is included ASAP. Very strange... as these commits should have only effected the AlcaPCCEventProducer.

**Comment by samhiggie** [comment]
Ah, I fixed the PSet criteria in the AlCaPCCProducer as well. 
https://github.com/cms-sw/cmssw/pull/29069/commits/5dbe317b8002779369cb1c0055acd3f37a474131

Would you recommend changing it back or editing the dependencies?

**Comment by slava77** [comment]
> Would you recommend changing it back or editing the dependencies?

I'd update downstream (unless there was a design decision in the past to have the config organized this way)
e.g. in Calibration/LumiAlCaRecoProducers/python/ALCARECOAlCaPCCZeroBiasFromRECO_cff.py
```python
alcaPCCProducerZBFromRECO = alcaPCCProducer.clone(
    pixelClusterLabel = "siPixelClusters", 
    trigstring = "alcaPCCZeroBiasFromRECO"
)
```

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/29069	1136d16 
- changes in reco category are trivial, only in a commented out line in DataFormats/Luminosity/interface/PixelClusterCounts.h
- jenkins tests pass

**Comment by pohsun** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
