### PR TITLE
L1TkMuon Filter: adding duplicate removal and implementing L1 quality cuts 11

### PR DESCRIPTION
**Pull request by Sam-Harper**
#### PR description:

This PR adds the l1 muon quality selection and l1 muon duplicate removal

#### PR validation:

On 10000 MB events rate goes from 87+/-16kHz to 24kHz +/-8kHz for tripple mu 7_5_5 which now matches the L1 reference (https://twiki.cern.ch/twiki/bin/view/CMS/PhaseIIL1TriggerMenuTools)

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

backport of https://github.com/cms-sw/cmssw/pull/33026

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by fwyzard** [comment]
see comments on #33026

**Comment by Martin-Grunewald** [comment]
+1

**Comment by Sam-Harper** [comment]
ah little bit too hasty Martin, I still need to address Andrea's comments but thank you for the fast response!

**Comment by Martin-Grunewald** [comment]
-1
apologies, @Sam-Harper

**Comment by Sam-Harper** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
