### PR TITLE
Fixes/impovements towards the first production version of the custom muon DPG NANO

### PR DESCRIPTION
**Pull request by battibass**
#### PR description:

Update of common muon ntuple content + fixes based on feedback from analysers/users:

- fix bug generating broken flat table in CSC TnP producer
- add missing information to allow DT TnP analysis
- add CSC/DT segment extrapolation to nearby RPC chambers
- fix propagation issue in GEMMuonExtTable producer
- add producer writing online luminosity information

Last [report at xPOG workshop](https://indico.cern.ch/event/1263032/timetable/#12-experience-and-plans-muondp)

#### PR validation:

Compilation and use in private production (ran using 13_0_X and covering Run2023_v1) for now. Though `cmsDriver.py` customisations are available, ntuple production is not included, at present, in any central workflow.

### CODE REVIEW

**Comment by battibass** [comment]
@vlimant, unless I forgot (thing that might well be possible) we spoke about the fact that this should be done, but never nailed down all details.

Anyhow, I am happy to agree on how to properly add a workflow to the nano matrix and include it in this PR, if you think this the best way to proceed.

**Comment by smuzaffar** [comment]
Milestone for this pull request has been moved to CMSSW_14_0_X.Please open a backport if it should also go in to CMSSW_13_3_X.

**Comment by battibass** [comment]
As discussed during the cross-POG meeting on November 15th, I've added muDPG-NANO workflows to `runTheMatrix.py` by using the `autoNANO.py`.

I add here some numbers from testing the two new workflows:

**timing on lxplus** (100 events are processed by default)

```bash
$ time runTheMatrix.py -w nano -l 2500.312
real    2m28.950s
user    1m12.547s
sys     0m4.669s
```

```bash
$ time runTheMatrix.py -w nano -l 2500.313
real    1m7.110s
user    0m26.173s
sys     0m3.949s
```

**size/event of the event branches** (from `PhysicsTools/NanoAOD/test/inspectNanoFile.py`):

- `muDPGNANO130Xrun3` ~ 7.0 kB/ev
- `muDPGNANOBkg130Xrun3` ~ 1.5 kB/ev

**Comment by battibass** [comment]
please test

**Comment by vlimant** [comment]
+1
many thanks @battibass !

**Comment by AdrianoDee** [comment]
test parameters:
- workflows = 2500.313,2500.312

**Comment by AdrianoDee** [comment]
test parameters:
- workflows_nano = 2500.313,2500.312

**Comment by AdrianoDee** [comment]
please test

**Comment by srimanob** [comment]
+Upgrade

2 new workflows run fine.

**Comment by AdrianoDee** [comment]
+pdmv 
workflow-wise everything's good

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
