### PR TITLE
Backport of code changes to 106X for PR 30922 : Enabling re-application of Type1 Corrections for PuppiMET and adding PUPPI MET Uncertainties

### PR DESCRIPTION
**Pull request by saghosh**
#### PR description:

This is a backport to 106X for the merged CMSSW PR 30922 : https://github.com/cms-sw/cmssw/pull/30922

Reapplication of JECs for Type-1 corrections for PuppiMET is not performed to include the latest JECs during NanoAOD production.
https://github.com/cms-sw/cmssw/blob/master/PhysicsTools/NanoAOD/python/nano_cff.py#L198

This is particularly relevant for 2018D in which the MiniAOD is PROMPT RECO.
It is not possible to re-apply JECs on the fly since the AK4PuppiJet collection is not stored in NanoAOD.

Also uncertainties for PuppiMET, particularly UnclusteredEnergy Uncertainties and the JER, JES down uncertainties are missing.
Only part of the uncertainties were added previously : https://github.com/cms-nanoAOD/cmssw/pull/516/files

This issue is already raised in the NanoAOD git area :
cms-nanoAOD#523
And also CMSSW github issue:
#30304

#### PR validation:

Checked successfully with runTheMatrix test workflows

For verification of code, please see the slides linked below
https://indico.cern.ch/event/924615/contributions/3885484/attachments/2049952/3435787/Pre_EPR_MET_June3.pdf

#### if this PR is a backport please specify the original PR and why you need to backport that PR:
Backport of:
https://github.com/cms-sw/cmssw/pull/30922

Required for UltraLegacy reprocessing , JME NanoAOD

### CODE REVIEW

**Comment by saghosh** [comment]
@mariadalfonso @lathomas : I was told to make sure all the changes are within the condition for modifier run2_miniAOD_devel.
Can you please check, and recommend if any other modifiers need to be used.

**Comment by mariadalfonso** [comment]
> @mariadalfonso @lathomas : I was told to make sure all the changes are within the condition for modifier run2_miniAOD_devel.
> Can you please check, and recommend if any other modifiers need to be used.

I'm not sure I understand here:
* first run2_miniAOD_devel had been move to run2_miniAOD_UL.
* second we want to fix the type1MET only on previously made mini
Your PR analysis doesn't change mini, only nano (policy: Mini should not change, for nano we can change as soon as is consisted with calibration).

Finally updates on the PhysicsTools/NanoAOD/python/nanoDQM_cfi.py present in master are missing

**Comment by saghosh** [comment]
@mariadalfonso Thanks for the clarification, code now synchronised with that for the master

**Comment by mariadalfonso** [comment]
please test

**Comment by mariadalfonso** [comment]
+xpog
backport inline with master

For new UL (reMini and run2_nanoAOD_106Xv1 ) type1 MET fixed with:
* new v15 puppi tune used for the rawPuppiMET
* type1MET correction done on the fly with ak4 puppi jets (still with v15) and with the appropriate jets. [Not possible to do a posteriori since the ak4 puppi jets are not stored in nano].

puppiMET weights for EOY not touched, only type1 corrections are reapplied.

**Comment by silviodonato** [comment]
@saghosh @cms-sw/xpog-l2 This PR change the standard workflowa 1325.7 (see Physics/NanoAODDQM/PuppiMET https://tinyurl.com/y4fdzdtc) image.
Workflow 1325.7 is a nanoAOD production using a 94X MiniAOD as input (it uses the `run2_nanoAOD_94XMiniAODv2` modifier).
Could you clarify if this behaviour is expected and in general how do you treat the "no-change rule" in NanoAOD? Thanks

**Comment by saghosh** [comment]
> @saghosh @cms-sw/xpog-l2 This PR change the standard workflowa 1325.7 (see Physics/NanoAODDQM/PuppiMET https://tinyurl.com/y4fdzdtc) image.
> Workflow 1325.7 is a nanoAOD production using a 94X MiniAOD as input (it uses the `run2_nanoAOD_94XMiniAODv2` modifier).
> Could you clarify if this behaviour is expected and in general how do you treat the "no-change rule" in NanoAOD? Thanks

@mariadalfonso : could you please let me know if the changes for correcting the PUPPI MET have to be placed under a modifier? (perhaps run2_nanoAOD_106Xv1 ?)

**Comment by mariadalfonso** [comment]
> @saghosh @cms-sw/xpog-l2 This PR change the standard workflowa 1325.7 (see Physics/NanoAODDQM/PuppiMET https://tinyurl.com/y4fdzdtc) image.
> Workflow 1325.7 is a nanoAOD production using a 94X MiniAOD as input (it uses the `run2_nanoAOD_94XMiniAODv2` modifier).
> Could you clarify if this behaviour is expected and in general how do you treat the "no-change rule" in NanoAOD? Thanks

yes, this PR is expected to change the puppi Type1MET when running in the previous nano.

policy: Mini-objects should not change, for nano we should fix/update the analysis recipe as soon as is consisted with calibration.

**Comment by silviodonato** [comment]
merge
as discussed at the ORP meeting, there are no on-going nanoaod production in `10_6_X`
@cms-sw/analysis-l2 please let us know if you have any comments

**Comment by santocch** [comment]
+1

**Pull request merged**
