### PR TITLE
L1T Correlator support for TMUX 18 in the barrel

### PR DESCRIPTION
**Pull request by gpetruc**
#### PR description:

This PR follows up on https://github.com/cms-sw/cmssw/pull/42643 adding the emulators to run the layer 1 barrel part at time multiplex period of 18 instead of 6, necessary for some studies for the Annual Review and P2UG Review.

There's no change in behaviour in the default configuration, the code changes in existing modules are just to allow this extra possibility.

The corresponding PR to cms-l1t-offline is https://github.com/cms-l1t-offline/cmssw/pull/1187

#### PR validation:

In CMSSW 13_3_X, as used in the cms-l1t-offline PR, the emulator was validated against the firmware, and against a simplified "ideal" emulation that doesn't try to implement all the internals of the firmware (buffers, truncations, etc.) but that gives the same results except in some corner cases.

 * Usual code-checks, code-format, etc.
 * `runTheMatrix.py -l 24834.0` which runs `TTbar_14TeV_TuneCP5_2026D98_GenSimHLBeamSpot14INPUT` + `DigiTrigger_2026D98` + `RecoGlobal_2026D98` + `HARVESTGlobal_2026D98+ALCAPhase2_2026D98` 
   * this runs the nominal L1T correlator configuration, so no change is expected (the new code is not run)
 * `cmsRun make_l1ct_binaryFiles_cfg.py --tm18 --serenity` under L1Trigger/Phase2L1ParticleFlow/test
   *  this runs also the tmux18 variation

### CODE REVIEW

**Comment by aloeliger** [comment]
please test

**Comment by aloeliger** [comment]
+l1
- Already reviewed by L1 as part of https://github.com/cms-l1t-offline/cmssw/pull/1187

**Comment by epalencia** [comment]
ping @cms-sw/upgrade-l2

**Comment by srimanob** [comment]
+Upgrade

**Comment by rappoccio** [comment]
+1

**Pull request merged**
