### PR TITLE
Run "high level muon reconstruction" for heavy ions

### PR DESCRIPTION
**Pull request by echapon**
The purpose of this PR is to run a MuonProducer at the end of reconstruction, with the main goal to fill the isPFMuon() flag. This also involves changing some collection tags, as the formerly defined "muons" collection is now transient and called "hiMuons1stStep".

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

@echapon is there going to be a backport to 75X?

**Comment by echapon** [comment]
Yes, I'll make a 75X PR too very soon.

**Comment by cvuosalo** [comment]
+1

For #10654 87bff1a5f45bffc16ffd4871ab64eaaa3081677e

Adding high-level muon reconstruction for Heavy Ions.

The code changes are satisfactory, and Jenkins [tests](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-10654/7101/summary.html) against baseline CMSSW_7_6_X_2015-08-10-1100 show the added muons for HI workflow 140.53 but no other significant differences. A timing test for 140.53 shows that muon processing time is nearly the same, with just a change in the name of the muon collection:

Timing change from baseline to PR 10654
       added      +5.07%         0.00 ms/ev ->      1244.62 ms/ev hiMuons1stStep
   -1.998846      -5.16%      1268.27 ms/ev ->         0.37 ms/ev muons

**Comment by slava77** [comment]
@cvuosalo 
please put the copy-pasted time summary inside triple back-quotes (it looks better mono-spaced)
Do I understand it correctly that in terms of CPU, the net effect is almost zero?
+1245 - 1268 essentially cancel

**Comment by cvuosalo** [comment]
@slava77:
Yes, the muon timing change between the baseline and the PR is approximately zero.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
