### PR TITLE
Update hlt customisations 11.2.x

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Extend the functionality of the `hltGetConfiguration --hilton` option:
  - use the DAQ source and output modules
  - do not apply the STORM-specific customisation

#### PR validation:

None.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Backport #32961 to the CMSSW 11.2.x stable branch.

### CODE REVIEW

**Comment by fwyzard** [comment]
backport #32961

**Comment by fwyzard** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
