### PR TITLE
added esConsumes to modules in EventFilter/CSCRawToDigi

### PR DESCRIPTION
**Pull request by JamminJones**
#### PR description:

added esConsumes to 3 modules

#### PR validation:

the code compiles

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by Dr15Jones** [comment]
This change was done under my direction.

**Review by slava77 — COMMENTED** [review]
since the header files for files declaring plugins are not needed, this could be a good opportunity to merge them into the corresponding plugin implementation files.

This affects
- EventFilter/CSCRawToDigi/interface/CSCDCCUnpacker.h
- EventFilter/CSCRawToDigi/interface/CSCDigiValidator.h

**Comment by Dr15Jones** [comment]
@slava77 I’m working with a freshman undergrad with limited programming experience. As such, I was hoping to minimize the changes to the code to only be what was needed for the consumes migration.

**Comment by slava77** [comment]
> @slava77 I’m working with a freshman undergrad with limited programming experience. As such, I was hoping to minimize the changes to the code to only be what was needed for the consumes migration.

if merging two files is too complicated, please at least move the headers to the /plugins directory

**Comment by Dr15Jones** [comment]
please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/30153	ad6fde6 
- code changes are in line with the PR title/description and the follow up review
- jenkins tests pass and comparisons with the baseline show no differences as expected

**Comment by silviodonato** [comment]
+1

**Pull request merged**
