### PR TITLE
eg hlt filter threshold reduction to 15 \GeV from 20\GeV

### PR DESCRIPTION
**Pull request by Soumyatifr**
#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by Soumyatifr** [comment]
Adding H to gg convener @lfinco here to keep track

**Comment by swertz** [comment]
enable nano

**Comment by swertz** [comment]
please test

**Comment by swertz** [comment]
Hi @Soumyatifr , I'm surprised to not see any difference in the tests. Of course this might entirely be due to the samples we use for those tests (e.g. TTbar or Muon data), that wouldn't contain events triggered with low-pt photon paths...

On the other hand, looking at the filters for which the objects are stored, I don't see any such low pt photons either. Are you sure you don't need to add some corresponding filters? A trigger object will only be saved if it passes at least one of the listed filters.

**Comment by swagata87** [comment]
> On the other hand, looking at the filters for which the objects are stored, I don't see any such low pt photons either. Are you sure you don't need to add some corresponding filters? A trigger object will only be saved if it passes at least one of the listed filters.

in a previous PR (https://github.com/cms-sw/cmssw/pull/40711), he added this filter -> `hltEG18TrackIso60Iso60CaloId15b35eR9Id50b90eHE12b10eR9Id50b80eTrackIsoUnseededFilter`
(yeah that's a awfully long name)

it appears here:
https://github.com/cms-sw/cmssw/blob/3547eeacc5fe3b8f2360b3e6eda69aa0c3eb7d9f/PhysicsTools/NanoAOD/python/triggerObjects_cff.py#L102

It's a photon leg with 18 GeV Et cut

**Comment by swertz** [comment]
Thanks @swagata87 , I'd overlooked that one - and indeed also in https://github.com/cms-sw/cmssw/pull/40711 there were no events in the tests passing that filter, due to the choice of samples... All good then.

**Comment by swertz** [comment]
+1

**Comment by perrotta** [comment]
+1

**Comment by vlimant** [comment]
is there a 13.0 back port expected for this ?

**Comment by swertz** [comment]
Indeed, @Soumyatifr can you please take care?

**Comment by swertz** [comment]
@Soumyatifr , kind ping for a backport to 13_0_X.

**Comment by swertz** [comment]
Hi @Soumyatifr @swagata87 just a reminder that if you want this included for NanoAODv12 and 2023 data prompt NanoAOD, there should be a backport to 13_0_X.

**Comment by swagata87** [comment]
I was expecting that Soumya or someone from Higgs to gamma gamma would respond to this. They are the primary user of the HLT path/filter in question here. I will send an email to the Hgg convenors now.

**Comment by Soumyatifr** [comment]
Hi @swertz Here it is: https://github.com/cms-sw/cmssw/pull/41115

**Pull request merged**
