### PR TITLE
[100X GT update][2017 MC] ECAL threshold + Hcal MCParams update

### PR DESCRIPTION
**Pull request by lpernie**
CHANGES:
**2018 realistic**
Diff with old GT:
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/100X_upgrade2018_realistic_v6/100X_upgrade2018_realistic_v7
-> New ECAL threshold
MOTIVATION: https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3465.html

**phase1_2017_design**
Diff with old GT:
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/100X_mc2017_design_IdealBS_v1/100X_mc2017_design_IdealBS_v2
-> Hcal MCParams update

**phase1_2017_realistic** 
Diff with old GT:
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/100X_mc2017_realistic_v2/100X_mc2017_realistic_v1
-> Hcal MCParams update

**phase1_2017_cosmics** 
Diff with old GT:
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/100X_mc2017cosmics_realistic_deco_v2/100X_mc2017cosmics_realistic_deco_v1

**phase1_2017_cosmics_peak** 
Diff with old GT:
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/100X_mc2017cosmics_realistic_peak_v2/100X_mc2017cosmics_realistic_peak_v1
-> Hcal MCParams update

MOTIVATIONS:
Change motivated here [0], [1] to solve [2].
[0] https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3190.html
[1] https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3458.html
[2] https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3456.html

### CODE REVIEW

**Comment by lpernie** [comment]
please test

**Comment by lpernie** [comment]
+1

**Comment by lpernie** [comment]
please test

**Comment by lpernie** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
