### PR TITLE
CMSSW_12_2_X: Fix crash in the trigger table view controllers

### PR DESCRIPTION
**Pull request by alja**
Correctly detect string type setters in auto generated controller GUI.

### CODE REVIEW

**Comment by alja** [comment]
+1

**Comment by perrotta** [comment]
backport of #37350

**Comment by perrotta** [comment]
@alja if you want to backport in 12_2, please also provide a backport for the intermediate cycle (between 12_2 and the master 12_4) CMSSW_12_3_X

**Comment by alja** [comment]
@perrotta The CMSSW_12_3_X needs the correction too. Do I need to create a PR for this as well?

**Comment by perrotta** [comment]
> @perrotta The CMSSW_12_3_X needs the correction too. Do I need to create a PR for this as well?

yes, please

**Comment by qliphy** [comment]
+1

**Pull request merged**
