### PR TITLE
Add muon shower comparison plots

### PR DESCRIPTION
**Pull request by dinyar**
#### PR description:

This PR adds comparison plots for hadronic showers between
* the EMTF outputs and the uGMT inputs (currently deactivated until EMTF has an unpacker for its output showers)
* the uGMT emulated and unpacked outputs
* the six copies of uGMT outputs

#### PR validation:

Ran the emulator workflow on a private raw file containing showers without issues. This doesn't test the full functionality as we don't have muon shower copies outside of a global run and currently there are no unpacked showers from EMTF, however no crashes etc. were observed so I think this could go in for further validation at P5 and once we have EMTF unpackers.

attn: @vukasinmilosevic

### CODE REVIEW

**Comment by jfernan2** [comment]
test parameters:
- addpkg = DQM/Integration

**Comment by jfernan2** [comment]
please test

**Comment by pmandrik** [comment]
Hello, @dinyar , please create the backport of the PR to CMSSW_12_2_1 also.

**Comment by dinyar** [comment]
Hi @pmandrik,

In principle this PR isn't needed for the next MWGR and I'll be on holidays for it's duration, so unless you object I'd prefer to do a potential backport only upon my return. Let me know what you prefer.

Cheers,
Dinyar

**Comment by pmandrik** [comment]
Thanks for the answer, then we do not have any reasons to rush, have a good holiday!

**Comment by qliphy** [comment]
+1

**Pull request merged**
