### PR TITLE
Modified photon selection for heavy-ion miniAOD

### PR DESCRIPTION
**Pull request by mandrenguyen**
#### PR description:

Photon selection modified for heavy-ion miniAOD. 

#### PR validation:

Tested with workflow 159

### CODE REVIEW

**Comment by perrotta** [comment]
please test workflow 159

**Comment by perrotta** [comment]
@cmsbuild please test with #30354  workflow 140.5611

**Comment by perrotta** [comment]
please test with #30354 workflow 140.5611

**Comment by perrotta** [comment]
please test workflow 140.5611 with #30354

**Comment by perrotta** [comment]
+1
- The new HI photon selection for Run3 has been compared with the current one thanks to the new HI re-miniAOD workflows defined with #30354: the size of modified objects is rather similar to the one obtainable with the current (pp) selection, rather there is overall some slight reduction in the event size 
- Jenkins tests pass and show no differences anywhere else

**Comment by silviodonato** [comment]
+1

**Pull request merged**
