### PR TITLE
"Seal" L1T unpacking plugin declarations (backport to 80X).

### PR DESCRIPTION
**Pull request by matz-e**
Factor out headers for the (un)packing of the L1T and seal the modules in the plugins directory. Allows other packages to depend on L1TRawToDigi as a library, as needed for DQM.

Backport of #15387. Fixes cms-l1t-offline/cmssw#398.

### CODE REVIEW

**Comment by dmitrijus** [comment]
+1

**Comment by mdhildreth** [comment]
please test

**Comment by matz-e** [comment]
@mulhearn can we get this merged to avoid merge conflicts, please?

**Comment by thomreis** [comment]
@matz-e I still get the runtime error when trying this with my DQM developments:

```
05-Sep-2016 11:24:06 CEST  Successfully opened file file:/afs/cern.ch/work/t/treis/public/data/run277981/run277981_ls0140_streamDQM_mrg-c2f12-23-01.dat
Begin processing the 1st record. Run 277981, Event 106464574, LumiSection 140 at 05-Sep-2016 11:24:11.119 CEST
----- Begin Fatal Exception 05-Sep-2016 11:24:11 CEST-----------------------
An exception of category 'PluginLibraryLoadError' occurred while
   [0] Processing run: 277981 lumi: 140 event: 106464574
   [1] Running path 'rawToDigiPath'
   [2] Calling event method for module L1TRawToDigi/'bmtfDigis'
Exception Message:
unable to load /afs/cern.ch/work/t/treis/ugmt/dqm/clean/tests/CMSSW_8_0_16/lib/slc6_amd64_gcc530/poisoned/plugin-poisoned-EventFilterL1TRawToDigiAuto.so because /afs/cern.ch/work/t/treis/ugmt/dqm/clean/tests/CMSSW_8_0_16/lib/slc6_amd64_gcc530/poisoned/plugin-poisoned-EventFilterL1TRawToDigiAuto.so: cannot open shared object file: No such file or directory
----- End Fatal Exception -------------------------------------------------
```

My setup:
```
cmsrel CMSSW_8_0_16
cd CMSSW_8_0_16/src/
cmsenv
git cms-init 
git cms-addpkg DQM/Integration
git cms-addpkg DQM/L1TMonitor
git cms-addpkg EventFilter/L1TRawToDigi
git remote add matz-e git@github.com:matz-e/cmssw.git
git fetch matz-e 
git pull matz-e seal_80x
git remote add thomreis git@github.com:thomreis/cmssw.git
git fetch thomreis
git pull my-cmssw l1Muon-DQM_CMSSW_8_0_16_testsetup
scram b -j7
cmsRun DQM/Integration/python/clients/l1tstage2_dqm_sourceclient-live_localtest_cfg.py
```

**Comment by matz-e** [comment]
@thomreis I lost two plugin declarations for the BMTF… could you test and confirm again, please?

**Comment by thomreis** [comment]
@matz-e now it works. Thanks.

**Comment by rekovic** [comment]
+1

**Comment by matz-e** [comment]
Rebased to resolve conflicts. Is there a way to get this in faster?

**Comment by rekovic** [comment]
@matz-e
Where is the rebased PR?  This same one?  It is difficult to see what changed.

**Comment by matz-e** [comment]
Yes, it's the same one. Nothing changed functionality-wise, the last commit dealt with the conflict, which was another (un)packer.

**Comment by rekovic** [comment]
+1

**Comment by thomreis** [comment]
@matz-e this probably needs yet another rebase.
Basically every time another L1 PR gets merged this one breaks again.

**Comment by matz-e** [comment]
Noticed that — just hadn't had the time to deal with it yet…

**Comment by matz-e** [comment]
Next iteration. With the exception of a `DAS_ERROR`, `runTheMatrix.py` seemed to be fine with this rebase.

@thomreis is there another bit-by-bit L1 comparison we could run?

**Comment by thomreis** [comment]
@matz-e not that I know of.

**Comment by matz-e** [comment]
Hm. OK.

**Comment by rekovic** [comment]
+1

**Comment by thomreis** [comment]
@davidlange6 this is ready to be merged. Can we get it in before any L1 PR in order not to break the mergeability again? The 81x version has been merged already a week ago.

**Comment by thomreis** [comment]
What is blocking this from getting merged?

**Comment by dmitrijus** [comment]
Nothing. On my list to ping at the orp.

**Comment by matz-e** [comment]
Thanks!

**Comment by thomreis** [comment]
I don't see this in the list of pending PRs (http://cms-sw.github.io/stats/pending-prs.html). It is only in the ORP161018 doc, marked as to be merged. What is the reason for this?

**Comment by thomreis** [comment]
Oh great. Conflicts again. As said before, this should be merged before L1 PRs to avoid conflicts.

**Comment by matz-e** [comment]
Well, the conflicts are going to show up in one place or the other. Are there any more L1T (un)packing PRs?

**Comment by thomreis** [comment]
Yes, but better to fix the conflicts once in L1 than several times here. Anyway, I don't see open ones anymore at the moment.

**Comment by rekovic** [comment]
+1

**Comment by rekovic** [comment]
@thomreis FYI, There will be another L1T PR for the patch of TowerCounting needed for pPb run.

**Comment by rekovic** [comment]
@thomreis It should not have conflicts with this PR and should go in smooth.

**Comment by dmitrijus** [comment]
@davidlange6 Please merge, this is blocking further L1T development.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
