### PR TITLE
Improved loading of b-tag EventSetup in PAT

### PR DESCRIPTION
**Pull request by ferencek**
This PR addresses a long-standing issue with loading of the standard reco b-tagging producers when adding or switching jet collections in PAT. As a consequence, the standard reco b-tagging producers  end up being re-run even when that is not needed.

In some cases, such as the MiniAODv2 production in 74X, re-running of the standard reco b-tagging producers might be needed and for such cases the `loadStdRecoBTag` switch was added to `jetTools.py` that allows loading of the standard reco b-tagging producers.

All the code changes in this PR should be completely transparent and have no impact on the standard reconstruction.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
Notes 
for https://github.com/cms-sw/cmssw/pull/12848	 bf60382
- jenkins tests pass and comparisons with baseline show no differences
- tested locally in CMSSW_8_0_0_pre4 by rerunning PAT step (with miniAOD validation and dqm) on outputs of 70 events from 25202 (ttbar PU35@25ns)
    - using reco file as input, the job runs to completion and there are no changes in the outputs based on file size and on validation plots; timer/tracer details show that the btagging sequence is not running and the combined miniAOD job time is reduced by about 16% (from 2.7 to 2.3 s/evt in my test)
    - using AOD file as input, the job crashes with 
```
   [5] Calling produce method for unscheduled module PATJetProducer/'patJets'
Exception Message:
Principal::getByToken: Found zero products matching all criteria
Looking for a container with elements of type: reco::BaseTagInfo
Looking for module label: pfSecondaryVertexTagInfos
```
tagInfos are added to patJets in miniAOD 
https://github.com/cms-sw/cmssw/blob/CMSSW_8_0_0_pre4/PhysicsTools/PatAlgos/python/slimming/miniAOD_tools.py#L148
tagInfos are not a part of AOD and should be recreated.
The requirement to add tagInfos to patJets should either be removed or the btagging sequence reintroduced (partially?) to miniAOD.

@arizzi @gpetruc

**Comment by ferencek** [comment]
@slava77, a fix for loading necessary TagInfos should be in place now.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/12848	 bf60382
- code changes are OK
- jenkins tests pass and show no differences
- local tests of miniAOD workflow from RECO and AOD inputs now run to completion and comparisons show no differences (based on miniAOD DQM, and also file output products sizes). 30 producer modules from b-tagging sequence are not (re)running anymore. The reduction in CPU of the miniAOD workflow in the pu35@25ns is ~10% (0.28 s/evt in my setup).

**Pull request merged**
