### PR TITLE
retain name of script that is fed to cmsRun in pybind11 interface

### PR DESCRIPTION
**Pull request by davidlange6**
#### PR description:

retain name of script that is fed to cmsRun in pybind11 interface

#### PR validation:

Fixes unit test failing in DEVEL build in FWCore/Integration package

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by Dr15Jones** [comment]
Does this make for better error messages?

**Comment by Dr15Jones** [comment]
+1

**Comment by davidlange6** [comment]
I didn't test that intentionally - from my small tests, I believe that it has no impact.

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by fabiocos** [comment]
@davidlange6 the regular PR tests are not testing anything here, am I correct? So we could just move forward

**Comment by fabiocos** [comment]
+1

**Comment by davidlange6** [comment]
there are unit tests in FWCore/PyDevParameterSet that are testing this change, but none of the standard workflows or other unit tests are affected (aside from in DEVEL).

**Pull request merged**
