### PR TITLE
Run3-alca174 Utilize ESGetToken in most of the classes in the package HcalCalibAlgos

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Utilize ESGetToken in most of the classes in the package HcalCalibAlgos

#### PR validation:

Use the runTheMatrix test workflows

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by christopheralanwest** [comment]
Is there a reason that you have not modified the `get()` statement at L354 of `RecAnalyzerMinbias.cc` here: https://github.com/cms-sw/cmssw/pull/31873/files#diff-fc3f153655a77be4f14b929f7e86b7d3ef9a53be5275c62910abb7c2d5f81781R354 even though you are making other modifications to that file in this PR?

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by christopheralanwest** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
