### PR TITLE
Small updates and fixes for geometry comparison tool

### PR DESCRIPTION
**Pull request by cschomak**
global_pixel_2_final
- Implemented a meaningful loop in TrackerGeometryCompare instead of one that either gives an exception or a 'break' at the first iteration
- Implemented comparison plots which show only the pixel (see example with quite large differences)

### CODE REVIEW

**Comment by ghellwig** [comment]
please test

**Comment by ghellwig** [comment]
@cschomak looking quickly over the changes, I see that you also changed the way the diffs are computed, but I thought we agreed on postponing this and only add the pixel overview plots for the time being.

**Comment by cschomak** [comment]
@ghellwig the change is only the sign of the translations (what you did in https://github.com/ghellwig/cmssw/commit/8e40556607df952934d4f18524dfe5609619871b). My understanding was that we want to fix the sign anyway and only postponed possible changes of the rotations.

**Comment by ghellwig** [comment]
@cschomak I only fear if we fix only the sign of the translation, it can be easily forgotten to take care also of the rotations as we seldomly check these plots
And normally it also does not matter if the sign of the translations is correct as we care most of the time only about systematic trends or the size of the movement.

**Comment by cschomak** [comment]
@ghellwig ok. I changed this back and made a note in the code

**Comment by ghellwig** [comment]
please test

**Comment by ghellwig** [comment]
+1
@cschomak can you also for documentation provide an example of the new pixel-overview plot in the PR description, please?

**Comment by cschomak** [comment]
@ghellwig I added an example plot to the description above

**Comment by ghellwig** [comment]
thanks!

**Comment by davidlange6** [comment]
+1

**Pull request merged**
