### PR TITLE
[10.1.X] Add leftout parameters for FedChannelDigis

### PR DESCRIPTION
**Pull request by mmusich**
Greetings,
in recent releases `SiStripRawToDigiModule` expects to be configured for:
   *  `LegacyUnpacker`  : https://github.com/cms-sw/cmssw/blob/137e7014743a17b31d234e8d71a45fa92543959a/EventFilter/SiStripRawToDigi/plugins/SiStripRawToDigiModule.cc#L37
   *  `DoAPVEmulatorCheck` : https://github.com/cms-sw/cmssw/blob/137e7014743a17b31d234e8d71a45fa92543959a/EventFilter/SiStripRawToDigi/plugins/SiStripRawToDigiModule.cc#L48

Both of those parameters have no default and are not defined in `EventFilter/SiStripRawToDigi/python/FedChannelDigis_cfi.py`, giving issues at runtime when trying to reconstruct events from the Cosmic Rack (see [details here](https://twiki.cern.ch/twiki/bin/viewauth/CMS/CosmicRackTracking#cRACK_tracking_code_setup)). 
To solve this issue, I've copied the value of those parameters from `EventFilter/SiStripRawToDigi/python/SiStripDigis_cfi.py`

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
@OlivierBondu : FedChannelDigis_cfi is only used by the DQM for SiStripCommissioning
Could you please confirm that the values of the parameters choosen by @mmusich are the one needed for it?

**Comment by OlivierBondu** [comment]
@perrotta : the values look correct to me, yes. On the other hand IIUC this shouldn't break anything but would help a great deal to have the cosmic rack running

**Comment by perrotta** [comment]
Thank you Olivier.

It was clear that it doesn't break anything (it fixes that config, in  
fact): but since we had to assign some new parameter to the config, I  
just wanted to check that such values were the one endorsed by SiStrip  
DPG

Olivier Bondu <notifications@github.com> ha scritto:

**Comment by perrotta** [comment]
+1
- Configuration fixed by adding two missing parameters
- The inserted values are the ones requested by the SiStrip DPG

**Pull request merged**
