### PR TITLE
Use the mergeResourcesJson.py script bundled with CMSSW

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Use the `mergeResourcesJson.py` script bundled with CMSSW, instead of checking out the circles repository.

#### PR validation:

None.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

No backport foreseen.

### CODE REVIEW

**Comment by fwyzard** [comment]
enable hlt_p2_timing

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
@rovere FYI

**Comment by Martin-Grunewald** [comment]
+1

**Comment by rappoccio** [comment]
+1

**Pull request merged**
