### PR TITLE
Geometry: Remove Custom SpecPars from T23 Dict

### PR DESCRIPTION
**Pull request by vargasa**
#### PR description:

Remove `TrackerMaterialAnalysis` SpecPars from `T23`:
Partially reverts https://github.com/cms-sw/cmssw/commit/336ef8d1852d2edd160ce46a30971977b0f4c685
Please see: https://github.com/cms-sw/cmssw/pull/31112#discussion_r472855933

#### PR validation:

```
python Configuration/Geometry/scripts/generate2026Geometry.py -t
```

#### Notes:
Please test with `wf. 30234.0`

FYI: @mmusich, @kpedro88

### CODE REVIEW

**Comment by mmusich** [comment]
test parameters
workflows = 30234.0

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
@vargasa thanks.
Step 3 of 30234.0 looks clean now [link to log](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-ffec32/8829/runTheMatrix-results/30234.0_TTbar_14TeV+2026D65+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14+DigiTrigger+RecoGlobal+HARVESTGlobal/step3_TTbar_14TeV+2026D65+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14+DigiTrigger+RecoGlobal+HARVESTGlobal.log)

**Comment by kpedro88** [comment]
+upgrade

**Comment by cvuosalo** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
