### PR TITLE
Fix for the parameter set of the AlcaPCCIntegrator module

### LINKED ISSUE #61: Change AlcaPCCIntegrator params to traced
Discussed here
https://github.com/cms-sw/cmssw/pull/37538/files#r848720360

This issue was in the code already, but this parameter should be tracked (impacts physics). Could edm::InputTag parameter type be used directly? Also, is the nested AlcaPCCIntegratorParameters really necessary? It doesn't seem to provide any value here (but I may be missing something).

Also, if the thePCCInputTag_ is only used as an argument for consumes(), it does not have to be a member variable of the class (causing minuscule memory increase throughout the job).

https://github.com/cms-sw/cmssw/blob/78daa840cbdb6216bcca00a73004a764a8edd8d9/Calibration/LumiAlCaRecoProducers/plugins/AlcaPCCIntegrator.cc#L56-L62

### PR DESCRIPTION
**Pull request by radla118**
#### PR description:

Fixes https://github.com/cms-AlCaDB/AlCaTools/issues/61. This is a follow-up PR of the https://github.com/cms-sw/cmssw/pull/37538. The input parameters of the AlcaPCCIntegrator producer are clarified (see https://github.com/cms-sw/cmssw/pull/37538#discussion_r848720360), and the member variables are fixed (https://github.com/cms-sw/cmssw/pull/37538#discussion_r862803323). The changes affect some of the configuration files, but the overall workflow and the output is not modified.

#### PR validation:

Verified by running runtTheMatrix.py -l 1020.0

### CODE REVIEW

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
@radla118 please update the PR description with "Fixes https://github.com/cms-AlCaDB/AlCaTools/issues/61 "
Thanks!

**Comment by tvami** [comment]
+alca
 * tests pass, PR is according to the description

**Comment by perrotta** [comment]
+1

**Pull request merged**
