### PR TITLE
Refine RuInfo payload inspector

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

The goal of this PR is two-fold
   1. first: is to improve the graphical appearance of the output of the `RunInfoParameters` plotting class. This now contains human readable run start and end times as well as small descriptor if the payload is valid, invalid or fake. 
   2. second: at the moment, the trend plots of values vs run-number (e.g. `RunInfoBFieldHistory`) are polluted by fake payloads which in production are interposed between valid ones. In order to discard them in plotting a hack in `CondCore/Utilities/interface/PayloadInspector.h` has been introduced in order to treat the case in which the return type of `getFromPayload` is a `std::pair<bool, float>`, where the boolean stores the information whether the payload is fake or not.

#### PR validation:

This a graphical display with this [script](https://github.com/mmusich/cmssw/blob/3cf29b197c640f47e218fd2f93f5aa6f9788966d/CondCore/RunInfoPlugins/test/plot2JsonTimeSeries.py) of the output of running the command:
```python
getPayloadData.py --plugin pluginRunInfo_PayloadInspector --plot plot_RunInfoBFieldHistory --tag runinfo_31X_hlt --time_type Run --iovs '{"start_iov": "312000", "end_iov": "312260"}' --db Prod --test ;
```
with this branch and the master branch, showing how the fake payloads are epurated.

comparison_masterbranch_vs_thisPR_json

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

This PR is not a backport and no backport is needed.

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by ggovi** [comment]
+1

**Comment by mmusich** [comment]
@cmsbuild ping?

**Comment by qliphy** [comment]
+1

**Pull request merged**
