### PR TITLE
Implementing HLTConfigData::globalTag() function (80X)

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
Implementing HLTConfigData::globalTag() function
Forward port of #13145

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
Uaahh not this again!

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
