### PR TITLE
TrackingTools/Producers: Remove class members not needed.

### PR DESCRIPTION
**Pull request by gartung**
Remove class members not needed.
Return shared_ptr directly from make_shared.

### CODE REVIEW

**Comment by gartung** [comment]
@Dr15Jones

**Comment by Dr15Jones** [comment]
These look good. An even better change would be to make the return type a `std::unique_ptr` to make it even clearer that that module does not own the object being made.

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
please test

**Comment by slava77** [comment]
@cmsbuild please test

it looks like the failures are gone based on the recent jenkins tests

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/21985	961e741
- technical
- jenkins tests pass

**Comment by fabiocos** [comment]
+1

**Pull request merged**
