### PR TITLE
Implemented time window selection for HGCalLayerClusters

### PR DESCRIPTION
**Pull request by Mourtz**
@rovere

### CODE REVIEW

**Comment by alja** [comment]
+1

**Comment by fabiocos** [comment]
@Mourtz @alja could you please have a look at the test outcome?

**Comment by Mourtz** [comment]
Should be fine now

**Comment by Mourtz** [comment]
@cmsbuild please test

**Comment by fabiocos** [comment]
please test

**Comment by alja** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
