### PR TITLE
Remove EcalDeadChannelRecoveryNN

### PR DESCRIPTION
**Pull request by perrotta**
#### PR description:

Following the issue reported in https://github.com/cms-sw/cmssw/issues/27657, the following files were said to be removed after the merging of #27175 in the master:
- EcalDeadChannelRecoveryNN class
- All the content of the ```RecoLocalCalo/EcalDeadChannelRecoveryAlgos/test``` directory

Further:
- Removed unneeded dependency and includes of EcalRecHit, as pointed out by the unit tests

#### PR validation:

It builds

@nancymarinelli @taroni
@crovelli @argiro @zghiche @fcouderc

### CODE REVIEW

**Comment by perrotta** [comment]
@nancymarinelli @taroni I think that one should further update the config in
RecoLocalCalo/​EcalRecProducers/​python/​ecalTBSimRecHit_cfi.py
but I'd let you deal with it in a separate PR

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
+1
- Unused code is removed from CMSSW, also following the suggestion of the responsibles of the package in #27657
- Jenkins tests pass

**Comment by fabiocos** [comment]
+1

**Pull request merged**
