### PR TITLE
bsunanda:Run2-hcx102 Changing the names of cfi/cff to make them more explicit

### PR DESCRIPTION
**Pull request by bsunanda**

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by ianna** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Comment by davidlange6** [comment]
great - thanks @bsunanda  - but can you pick either plan1 or plan01? I guess plan1 is the more cms used name..

**Comment by kpedro88** [comment]
I think the idea of "plan01" is that file is the same for plan0 and plan1

**Comment by davidlange6** [comment]
Is it also the same for planN?




On 9 Feb 2017, at 15:22, Kevin Pedro <notifications@github.com<mailto:notifications@github.com>> wrote:


I think the idea of "plan01" is that file is the same for plan0 and plan1

**Comment by kpedro88** [comment]
Our plan is to merge RecHits into the phase0 depth segmentation scheme regardless of the value of N (as long as <36), so I think it should be the same.

**Comment by bsunanda** [comment]
I believe Plan01 will be the same for all planN where N < 36. For N=36 it will be a RecNumbering18.

**Comment by davidlange6** [comment]
> On Feb 9, 2017, at 4:45 PM, bsunanda <notifications@github.com> wrote:
> 
> I believe Plan01 will be the same for all planN where N < 36. For N=36 it will be a RecNumbering18.
> 

18:) of course…  ok thanks

**Comment by davidlange6** [comment]
+1

**Pull request merged**
