### PR TITLE
suppress a to-do reminder in PFEGammaAlgo.cc from LogWarning to LogInfo

### PR DESCRIPTION
**Pull request by slava77**
I'm downgrading the severity of the message "Need to implement proper merging of two gsf candidates!" and put it on the list of reco issues in #23216

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/23217	8cc38f1
- this is another PR in a series of cleanup of logError/logWarning in the prompt reco jobs (based on tests in run 315420)
- jenkins tests pass and changes in the reco outputs show up only in the logError monitoring

**Comment by fabiocos** [comment]
+1

**Pull request merged**
