### PR TITLE
Enable Laser 4 plots in ECAL DQM [13_2_X]

### PR DESCRIPTION
**Pull request by abhih1**
#### PR description:

This PR is to enable the new commissioned green laser plots, named Laser 4 in the ECAL DQM.

#### PR validation:

PR is validated by running the ECAL online DQM configuration and verifying the plots on a test DQM GUI.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

This is a backport to 13_2_X which is in production at the moment.
The master PR is https://github.com/cms-sw/cmssw/pull/42805

### CODE REVIEW

**Comment by emanueleusai** [comment]
please test

**Comment by emanueleusai** [comment]
type ecal

**Comment by emanueleusai** [comment]
backport of https://github.com/cms-sw/cmssw/pull/42805

**Comment by emanueleusai** [comment]
+1

- test p5 ok

**Comment by rappoccio** [comment]
+1

**Pull request merged**
