### PR TITLE
Add pythia8 gun to generate particles with flat pt and Lxy (transverse displacement)

### PR DESCRIPTION
**Pull request by mbluj**
#### PR description:

This PR adds a new pythia8 gun to generate particles with flat pt and Lxy (transverse displacement). The gun has number of parameters to tune phase-space of generate particles. It is planned to use the gun to produce a sample of displaced taus to train DNN-based tauID dedicated to displaced taus. 

This PR contains the pythia8 gun itself and an example cfi file.

It is foreseen to back-port this gun to 12_4_X and 10_6_X for production of Run-3 and Run-2 samples. The cmsDriver command to repeat the test as follows:
```
cmsDriver.py GeneratorInterface/Pythia8Interface/python/Py8PtLxyGun_4tau_cfi.py --fileout file:gensim.root \
--mc --eventcontent RAWSIM --datatier GEN-SIM --era Run3 --conditions 124X_mcRun3_2021_realistic_v1 \
--beamspot Run3RoundOptics25ns13TeVLowSigmaZ --step GEN,SIM --geometry DB:Extended --nThreads 4 \
--nConcurrentLumis 1 --python_filename GEN-SIM_step_cfg.py -n 1000 --no_exec
```
The gun is not used in any official workflow.

#### PR validation:

The gun was tested by using it with typical gen-sim workflow (as Run-3 Summer21 production).

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by qliphy** [comment]
please test

**Comment by SiewYan** [comment]
@mbluj, is that possible to show the private validated results? As you have mentioned the gun is not used in any official workflow? Thanks

**Comment by mbluj** [comment]
> @mbluj, is that possible to show the private validated results? As you have mentioned the gun is not used in any official workflow? Thanks

Sure. What kind of validation results would you like me to provide? Printouts from running, some distributions?

**Comment by Saptaparna** [comment]
Hi @mbluj perhaps plots that show that the transverse displacement is working for single photons? Just a suggestion.

**Comment by mbluj** [comment]
> Hi @mbluj perhaps plots that show that the transverse displacement is working for single photons? Just a suggestion.

OK, fine. We created this module and tested it for taus, so I will show distributions for them, but at gen level (before decay and interaction with detector material) type of particle is irrelevant.

**Comment by Saptaparna** [comment]
Sounds good.

**Comment by Saptaparna** [comment]
Looks good to me.

**Comment by Saptaparna** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
