### PR TITLE
LLP GenFilter based on transverse displacement and pdgId - backport #37669

### PR DESCRIPTION
**Pull request by Raffaella07**
#### PR description:

The filter generalizes MCLongLivedParticles GenFilter (filter was included in GenFilters up to CMSSW_11_0_X/ ,
 for CMSSW_10_2_X/ see  https://github.com/cms-sw/cmssw/blob/CMSSW_10_2_X/GeneratorInterface/GenFilters/src/MCLongLivedParticles.cc
It selects particles based on transverse displacement (by means of a lower and/or upper cut) and pdgIds.
The filter is developed for searches of long lived HNLs in B meson decays (@rmanzoni  @pandolf  @amlyon)

The filter is included in the `plugins` subdirectory of `GeneratorInterface/GenFilters` . 
It is possible to retrieve the original filter behavior by setting the lower cut only and leaving the pdgIds unspecified.
NOTE: the filter syntax has changed with respect to the original version, as a lower (LengMin) and an upper (LengMax) cut can be specified, while in the CMSSW_11_0_X/  version there was only a lower cut parameter.

#### PR validation:

Filter behavior can be tested in the `test` subdirectory of  `GeneratorInterface/GenFilters` through the module `test_MCLongLivedFilter_cfg.py`

Backporting #37669

### CODE REVIEW

**Comment by SiewYan** [comment]
please test

**Comment by qliphy** [comment]
@Raffaella07   Please clarify the purpose to backport this PR to 10_2_X,  is it for specific MC production?
@cms-sw/generators-l2

**Comment by Raffaella07** [comment]
> @Raffaella07 Please clarify the purpose to backport this PR to 10_2_X, is it for specific MC production? @cms-sw/generators-l2

Yes, we would like to use this filter for a MC production of B samples decaying into HNLs, the whole generation tool is developed in CMSSW_10_2_15

**Comment by qliphy** [comment]
> > @Raffaella07 Please clarify the purpose to backport this PR to 10_2_X, is it for specific MC production? @cms-sw/generators-l2
> 
> Yes, we would like to use this filter for a MC production of B samples decaying into HNLs, the whole generation tool is developed in CMSSW_10_2_15

Would you please tell us more details (e.g. which MC campaign) or provide links to slides?

**Comment by Raffaella07** [comment]
We need the filter for a MC campaign under BParking conditions; in this campaign, long lived HNL particles will be produced and we need the filter to constrain their decays within the tracker volume.
The new  MC campaign will more or less resemble (provided a few tuning in terms of stats etc.) the first MC campaign requested for the analysis [2], for which a new filter was PRd as well [3]- this filter introduced a cut on displacement as well. 

Unfortunately, the filter we PRd for the last production was not directly applicable to this new generation campaign, as we are trying to enlarge our acceptance and the filter is constrained to search for particles of a single specific flavor, while under the new conditions we would need more than one. 

We therefore decided to generalize a filter that was already existing for LLP particles, since in this way we can factorize the displacement cuts and other requests on the event in different filters, and be more flexible. 
Moreover, we thought this generalization might be useful for several analyses, as it allows now to specify several flavors for the particles to be filtered, and select elements in a customizable window for the transverse displacement of the particles.

**Comment by perrotta** [comment]
@Raffaella07 , thank you for your explanation.
But haven't B-parking analysis moved to (UL) 10_6 already?
Maybe @cms-sw/btv-pog-l2 can help us understanding the plans.

Even if this filter aims at some analysis still going on with the old 10_2 release, still the normal development plan should be followed:
- Develop and merge first in master
- Backport to the release cycle in which you plan to use it, and possibly also in all intermediate releases between the master and that cycle where it could also be used. For example, I expect that this filter could be also needed in the official B-parking release 10_6

**Comment by Raffaella07** [comment]
@perrotta not all the BParking analyses have moved to UL, though there is a long term plan to move everything on UL and 10_6. This analysis in particular won't move to UL and 10_6 anytime soon. Still our plan is to backport this filter to 10_6 as well, we wanted to get things going for the master and 10_2 releases first, and check that everything is in order.

We have already in place the pull request for master (#https://github.com/cms-sw/cmssw/pull/37669), can you tell me if are there any other actions expected on our side there?

Thanks to everyone for the very quick feedbacks!

**Comment by perrotta** [comment]
backport of #37669
(it was even written in the title, indeed...)

**Comment by qliphy** [comment]
please abort 
previous seems to be stuck

**Comment by qliphy** [comment]
please test

**Comment by amlyon** [comment]
Dear experts, 

Here again, if everything is completed, would it be possible to proceed to the merge of this PR?

We also wanted to ask you about the further steps to be undertaken such that the CMSSW release is created? We remind that the updated gen-filter imported in this PR will be used for a central MC production. The MC contact taking care of the MC request is Si Hyun Jeon @sihyunjeon .

We would be grateful if the release could be created in the best delays, ideally by the end of the week, such that the MC production can be launched as soon as possible.

We thank you a lot for your understanding and cooperation.

**Comment by qliphy** [comment]
@Raffaella07 Please first fix asap the PR in master (#37669),  and then update this backported one.

**Comment by amlyon** [comment]
Dear experts, 

Here again, would it be possible to test and merge as early as possible? 

As stated above, we are in fact under quite some time pressure, as the material imported in this PR is needed for a central MC production, that we plan to launch early next week.

Once the PRs (master and backport) are merged, could you please proceed to the creation of the release, or point me to the steps that I need to undertake to get it done?

Once again, thank you a lot for your understanding and collaboration!

**Comment by SiewYan** [comment]
@Raffaella07 , have you propagated changes from the master #37669 ? If so, i will issue the test, please let me know

**Comment by Raffaella07** [comment]
> @Raffaella07 , have you propagated changes from the master PR #37669 ? If so, i will issue the test, please let me know

Yes, for what I could. Most of the code is exactly the same, do expect some differences due to the fact that we are using  releases with major differences for the two PR : 

-https://github.com/cms-sw/cmssw/pull/37669 has only a .cc file in which the filter is defined and implemented, in the directory <GeneratorInterface/GenFilters/plugins>, while here we have a .h in<GeneratorInterface/GenFilters/interface> with filter definition and a .cc in <GeneratorInterface/GenFilters/src> 
- The EDFilter libraries can be found in different locations in the two PRs (<FWCore/Framework/interface/global/EDFilter.h> for https://github.com/cms-sw/cmssw/pull/37669 and (<FWCore/Framework/interface/EDFilter.h> for this backport)

and due to the fact that in CMSSW_10_2_X the filter MCLongLivedParticles already exists( https://github.com/cms-sw/cmssw/blob/CMSSW_10_2_X/GeneratorInterface/GenFilters/src/MCLongLivedParticles.cc), so we had to ensure backwards compatibility by using "theCut" parameter, which is obsolete and not present in https://github.com/cms-sw/cmssw/pull/37669 

All the applicable comments and suggestions for https://github.com/cms-sw/cmssw/pull/37669 have been implemented also in this backport. 

If you would kindly start the tests, in the meantime I will upload the validation plots for this filter as well, as we did for https://github.com/cms-sw/cmssw/pull/37669

**Comment by SiewYan** [comment]
please test

**Comment by perrotta** [comment]
@Raffaella07 please backport the very same code that will be finally merged in master: I see no reason to allow differences in them (or just point them out case by case, so that they can be discussed and possibly approved).

The fact that this filter already existed in the release is not a reason for the differences: you are applying changes in that code anyhow, and those changes need to be propagated everywhere anyhow. Alternatively, you can define a different filter, which does not require modifying the existing MCLongLivedParticles: if you plan to do so, please allow the same "new" filter name in the master PR, so that the very same code can get backported here (and possibly also in all intermediate releases still involved in possible productions, e.g. 10_6 for UL analyses)

**Comment by Raffaella07** [comment]
Hello everyone! 
After the latest advice from the experts, we have decided to add a new filter rather than updating an existing one. Therefore, we are closing this PR as it is and opening a new one to backport the already merged #37669. Thanks a lot for your work and support, and so sorry for the spam, see you on the other backport!

**Pull request closed without merging**
