### PR TITLE
Adapting VID & Nano to the new E/gamma UL format + adding HEEP V7.1: 106X

### PR DESCRIPTION
**Pull request by Sam-Harper**
#### PR description:
This is the VID & Nano adaptions PR to take advantage of the 10_6 e/gamma dataformats now backported to 10_6. It also adds HEEP V7.1

#### if this PR is a backport please specify the original PR:

backport of https://github.com/cms-sw/cmssw/pull/26486

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by peruzzim** [comment]
+xpog

it's the same commit cffbf72 as in #26486

**Comment by perrotta** [comment]
backport of #26486

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/26786	cffbf72
- this is a trivial backport of #26486 (the same topic branch is used as in the master version)
- jenkins tests pass

**Comment by santocch** [comment]
+1

**Comment by perrotta** [comment]
@peruzzim 
This PR should be closed as superseeded by #26845 (reco specific part of that newer PR is identical, but the nanoAOD configs are updated there)

**Comment by peruzzim** [comment]
as preferred by integration team, one could also merge them in sequence

**Comment by perrotta** [comment]
> as preferred by integration team, one could also merge them in sequence

If you merge them in sequence, the second one will have to be rebased: extra work (and completely useless)  for you and for the release managers

**Comment by fabiocos** [comment]
hold

@perrotta @Sam-Harper so this PR is embedded and updated in #26845, so I will move forward with the integration of that one directly

**Comment by Sam-Harper** [comment]
okay thats sounds sensible, I'll close this one then?

**Comment by fabiocos** [comment]
@Sam-Harper at this point I would say so

**Comment by Sam-Harper** [comment]
excellent, done

**Pull request closed without merging**
