### PR TITLE
get rid of existsAs in (some) tracking code

### PR DESCRIPTION
**Pull request by mtosi**
this PR is mainly meant for getting rid of some existsAs in the tracking code
towards 2016 confDB template in 80x

a customization function for HLT (back-compatibility) is also provided
hopefully w/ all relevant modules and proper setting

I realized that there was a typo in 2 modules
=> I have corrected it as well (MaxDispacement --> MaxDisplacement)

### CODE REVIEW

**Comment by slava77** [comment]
Mia,
please post a message when you are done with commits on your side

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by Martin-Grunewald** [comment]
Hi,

If the fillDescription is done properly, one does not need all those entries in the customize for HLT file,
as fillDescription will take care to insert in case the parameter is missing in the py file.

**Comment by Martin-Grunewald** [comment]
This PR must be delayed until after #12816 is integrated, at which point you likely have to re-edit the customisation file.

**Comment by VinInn** [comment]
@cmsbuild, please test

**Comment by VinInn** [comment]
@cmsbuild, please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by mtosi** [comment]
the error triggered by HI module was due to
1. missing useMultipleScattering in the config (expected, this parameter is new)
2. missing useFakeVertices in the config (this parameter was not new !)

**Comment by VinInn** [comment]
@cmsbuild, please test

**Comment by mtosi** [comment]
also RecoTracker/ConversionSeedGenerators/python/ConversionStep_cff.py needed to be updated (sorry, I missed it in previous commits)
now, it should be fixed

I do not understand why 140.53 is still failing, though
I explicitly checked it in my working area
and it worked after my commit on the HI packages

**Comment by VinInn** [comment]
@cmsbuild, please test

**Comment by VinInn** [comment]
@mtosi, previous test results was for Tested at: 21b0489 , before your latest commit

**Comment by mtosi** [comment]
last reported crash should be fixed by https://github.com/mtosi/cmssw/commit/6ee1ef564a87f219b8f0d1bcce2c46c2d3994a6c
(sorry for the many commits)

**Comment by mtosi** [comment]
is it possible to test, please ?
thanks much

**Comment by VinInn** [comment]
@mtosi, it is successfully tested tested at 6ee1ef5

**Comment by Martin-Grunewald** [comment]
Newly added file ```HLTrigger/Configuration/python/customizeHLTfor2016trackingTemplate.py```
does not seem to be used in this PR.

**Comment by cvuosalo** [comment]
@mtosi: The Jenkins DQM comparison shows about 2000 HLT-related tiny differences for workflow 	50202.0_TTbar_13. From the description of this PR, I would not expect any differences to be generated. Could you please add to the PR description an explanation of what changes to event content and Reco quantities should be expected from this PR?

**Comment by Martin-Grunewald** [comment]
@mtosi 
1) please comment on my question above concerning the unused file
2) now that #12816 is merged, you need to resolve the merge conflicts in this PR
(most likely resulting from customizeHLTforCMSSW.py which is changed in both PRs)

**Comment by fwyzard** [comment]
As far as I know,
`HLTrigger/Configuration/python/customizeHLTfor2016trackingTemplate.py` is
available to implement a 2016-like confguration, but is not picked up by
default.
It may be useful for POGs to check the new configuration before the actual
migration in ConfDB (if we decide to do it), but strictly speaking is not
necessary.

**Comment by Martin-Grunewald** [comment]
Hmm, this would need instructions to be posted somewhere (tk wiki?) for the POGs to pickup on!

**Comment by slava77** [comment]
-1
superseded by 13062

**Pull request closed without merging**
