### PR TITLE
Backport of Candidate Seeded Pixel Recovery

### PR DESCRIPTION
**Pull request by JanFSchulte**
Backport of PR #22005 to 10_0_X.

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by perrotta** [comment]
+1
- Identical to #22005, now merged in the master
- It may be needed for HLT development studies in 10_0_X, and for that usage a backport to 10_0 can be justified: I will assign this PR also to HLT just to certify it
- It implements the new feature of combining the automated doublet recovery with the candidate seeded tracking regions (used at HLT). Such new feature must be switched on by setting the seedingMode parameter to "Candidate", while the default behaviour is not modified wrt previous one
- No differences are expected in standard tests outputs, none were observed

**Comment by perrotta** [comment]
assign HLT

**Comment by JanFSchulte** [comment]
Just to know what to report to the TSG, what is the status here? Is HLT still required to do anything for this PR?

**Comment by fabiocos** [comment]
+1

**Comment by Martin-Grunewald** [comment]
+1

**Pull request merged**
