### PR TITLE
Update tests in PythonAnalysis - executables no longer end with 3

### PR DESCRIPTION
**Pull request by davidlange6**
follows changes in https://github.com/cms-sw/cmsdist/pull/7330

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test with cms-sw/cmsdist#7330

**Comment by qliphy** [comment]
please test

**Comment by davidlange6** [comment]
was not expected to work without the cmsdist change...

**Comment by davidlange6** [comment]
please test with cms-sw/cmsdist#7330

**Comment by davidlange6** [comment]
please abort

**Comment by davidlange6** [comment]
please test with cms-sw/cmsdist#7330

**Comment by smuzaffar** [comment]
this looks good, it should be merged along with cms-sw/cmsdist#7330

**Comment by qliphy** [comment]
+1

**Comment by qliphy** [comment]
merge

**Comment by santocch** [comment]
+1

**Pull request merged**
