### PR TITLE
Update for simulation of pixel bad components

### PR DESCRIPTION
**Pull request by ferencek**
#### PR description:

This is a backport of https://github.com/cms-sw/cmssw/pull/44276 and https://github.com/cms-sw/cmssw/pull/44320. The primary goal was to backport https://github.com/cms-sw/cmssw/pull/44320 but to be able to cherry-pick its commit from the CMSSW_14_1_X branch, https://github.com/cms-sw/cmssw/pull/44276 had to be cherry-picked first (they both modify `SimGeneral/MixingModule/python/pixelDigitizer_cfi.py`).

This PR is relevant for the Run 3 MC production.

@sroychow

### CODE REVIEW

**Comment by mmusich** [comment]
backport of https://github.com/cms-sw/cmssw/pull/44276
backport of https://github.com/cms-sw/cmssw/pull/44320

**Comment by mmusich** [comment]
type bug-fix

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by civanch** [comment]
+1

differences for 2018 simulation were discussed in #44276 and #44320 .

**Comment by antoniovilela** [comment]
+1
   - Can include it in 14_0_2 since will wait for the 14_0_X IB.

**Pull request merged**
