### PR TITLE
Adding v2 of 50ns L1T Menu (75X)

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
Adding v2 of 50ns L1T Menu (75X) and support for it.
The L1 xml file is provided by Takashi MATSUSHITA takashi.matsushita@cern.ch

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by mulhearn** [comment]
+1

**Comment by Martin-Grunewald** [comment]
Fixed type in filename

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
@mulhearn Can you please re-sign this PR?
Thanks!

**Comment by Martin-Grunewald** [comment]
@mulhearn Can you please re-sign this PR?
Thanks!

**Comment by Martin-Grunewald** [comment]
@mulhearn 
Please let me know what is holding up your re-signature on this PR.

**Pull request closed without merging**
