### PR TITLE
Phase2-hgx315X Make use of the goodCell method for partial wafers in defining valid DetId and rearranging a few parameters

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Make use of the goodCell method for partial wafers in defining valid DetId and rearranging a few parameters

#### PR validation:

Use cfg's in Geometry/HGCalCommonData/test/python

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@srimanob Please approve this PR

**Comment by srimanob** [comment]
+Upgrade

**Comment by qliphy** [comment]
+1

**Comment by qliphy** [comment]
An [issue](https://github.com/cms-sw/cmssw/issues/38268) is opened:  136.8562 is failing in master IB.

**Comment by bsunanda** [comment]
Can you please provide the issue
________________________________

**Comment by qliphy** [comment]
@bsunanda  Please ignore the message. I posted in the wrong place.

**Pull request merged**
