### PR TITLE
(re)introduce hit pair limit in iterative tracking seeding (port of #24818 )

### PR DESCRIPTION
**Pull request by slava77**
backport of #24818

copy-paste of the description in 104X follows:

This PR is somewhat inspired by issues reported in https://hypernews.cern.ch/HyperNews/CMS/get/tier0-Ops/2014.html

The target module(s) in this PR are of HitPairEDProducer kind.
To define a limit I used a somewhat ad-hoc limit of \~0.5 GB of output data per event.
This leads to 
- a limit of 50M pairs for produceIntermediateHitDoublets = True (producing 2 ints per entry)
- a limit of 12M pairs for produceSeedingHitSets = True (producing 4 rechit pointers per entry)

As a specific case test, I used PromptReco_Run323420_EGamma from the HN thread and find that with this PR the job is expected to be processable:
- single thread RSS peak moves down from 22GB to 7GB
    - 8-thread RSS peak with this PR is around 13GB

Note that I made a guess for a bottom-up limit: for 10K real particles in an event (PU200 has about 10K tracking particles with pt>0.5 GeV and |eta|<4), for at worst \~50 layer pairs (as a still sensible large number)
- 12M limit would correspond to \~4% purity in created pairs
- 50M limit would correspond to \~1% purity in created pairs

This sounds safe enough from these "first principles".

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cmsbuild please test

hoping that CMSSW_10_2_X_2018-10-19-2300 has no/less failed workflows

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/24942	fcc4527
- jenkins tests pass and comparisons with the baseline show no relevant differences

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/24942	fcc4527
- jenkins tests pass and comparisons with the baseline show no relevant differences

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/24942	fcc4527
- jenkins tests pass and comparisons with the baseline show no relevant differences

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/24942	fcc4527
- jenkins tests pass and comparisons with the baseline show no relevant differences

**Comment by slava77** [comment]
it looks like my multiple "+1"s made the bot invert the signature.
@smuzaffar please check

**Comment by slava77** [comment]
+1

trying again
it looks like the github issues are mostly over

**Comment by fabiocos** [comment]
@slava77 for 10_3_X this backport has been punt on hold as not strictly needed. What is the plan for 10_2_X, and which is the target? Strictly speaking this would affect the physics output in the middle of an ongoing MC production as it does not affect HI only, am I correct?

**Comment by slava77** [comment]
On 11/12/18 1:00 AM, Fabio Cossutti wrote:
> @slava77
> for 10_3_X this backport has been punt on hold as not strictly needed.
> What is the plan for 10_2_X, and which is the target? Strictly speaking
> this would affect the physics output in the middle of an ongoing MC
> production as it does not affect HI only, am I correct?
> 
> —

If I'm not mistaken, you asked for the backport(s).
I can close in case I misunderstood.

**Comment by fabiocos** [comment]
hold

relevant only for HI studies

**Comment by slava77** [comment]
this look useless now for operations purposes

**Pull request closed without merging**
