### PR TITLE
Converted DTDigiToRawModule to a stream EDProducer

### PR DESCRIPTION
**Pull request by sabasehrish**

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

a somewhat cursory look shows that there are no thread unsafe members or calls

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/17413	492a4f3
- technical change, as given in the title
- jenkins tests pass

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/17413	c9b9d86
- ```override``` added to ```produce``` method
- jenkins tests pass

**Comment by davidlange6** [comment]
+1

**Pull request merged**
