### PR TITLE
PPS - RawToDigi update to handle mappings from CondDB [update of PR 42711]

### PR DESCRIPTION
**Pull request by grzanka**
#### PR description:

This is an update of PR #42711. I had troubles to rebase it on top of newest CMSSW and found it easier to make a new PR.
This may also facilitate testing with the last update.

This PR is a next step in a way to resolve an issue from https://github.com/cms-sw/cmssw/pull/40765 - Transfer of all PPS detectors' mappings from XML to CondDB.

In this PR:

Updates of [TotemVFATRawToDigi.cc](https://github.com/CTPPS/cmssw/blob/6105ec09f9adba0ecaa36a6ab1ac23f249a67c6f/EventFilter/CTPPSRawToDigi/plugins/TotemVFATRawToDigi.cc)

add use of new TotemAnalysisMaskRcd separated from TotemReadoutRcd and introduced in https://github.com/cms-sw/cmssw/pull/42471;
handle retrieving objects from records using EventSetup::getHandle()
Changes in [ctppsRawToDigi_cff.py](https://github.com/cms-sw/cmssw/compare/master...CTPPS:cmssw:raw_to_digi_updates#diff-1eb4c964687bc0dbea0102fa7d717cc7f42908aa1979fbc22cde1db187b8e3fa):

remove imports of XML files containing mappings - now mappings will be taken from a GT
New config fragment: [ctppsRawToDigi_xml_cff.py](https://github.com/cms-sw/cmssw/compare/master...CTPPS:cmssw:raw_to_digi_updates#diff-ca62e8d0446df10a4cd189d5eabaecbaf40ca005968588089ab54e075954ad6a) which is an old [ctppsRawToDigi_cff.py](https://github.com/cms-sw/cmssw/compare/master...CTPPS:cmssw:raw_to_digi_updates#diff-1eb4c964687bc0dbea0102fa7d717cc7f42908aa1979fbc22cde1db187b8e3fa) - it imports XML files with mappings

New config ([strip_dqm_test_xml_cfg.py](https://github.com/cms-sw/cmssw/compare/master...CTPPS:cmssw:raw_to_digi_updates#diff-59e872634532ac0d26ee88ec4b59dd48d6ddca7dc15965feeb025016c3a7d278)) to read mappings from XML instead of GT (just for test and internal use)

#### PR validation:

<p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; color: rgb(14, 17, 22); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">We have created Tags containing records with mappings for each detector. Created Tags:</p>

TAG | Record
-- | --
PPSDAQMapping_TrackingStrip_test_v1 | TotemReadoutRcd
PPSDAQMapping_TimingDiamond_test_v1 | TotemReadoutRcd
PPSDAQMapping_TotemTiming_test_v1 | TotemReadoutRcd
PPSDAQMapping_TotemT2_test_v1 | TotemReadoutRcd
PPSAnalysisMask_test_v1 | TotemAnalysisMaskRcd

<p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; color: rgb(14, 17, 22); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">To validate changes in TotemVFATRawToDigi I ran the rawToDigi and the reconstruction (<code class="notranslate" style="box-sizing: border-box; font-family: ui-monospace, SFMono-Regular, &quot;SF Mono&quot;, Menlo, Consolas, &quot;Liberation Mono&quot;, monospace; font-size: 11.9px; padding: 0.2em 0.4em; margin: 0px; white-space: break-spaces; background-color: var(--bgColor-neutral-muted, var(--color-neutral-muted)); border-radius: 6px;">process.ctppsRawToDigi</code><span> </span>and<span> </span><code class="notranslate" style="box-sizing: border-box; font-family: ui-monospace, SFMono-Regular, &quot;SF Mono&quot;, Menlo, Consolas, &quot;Liberation Mono&quot;, monospace; font-size: 11.9px; padding: 0.2em 0.4em; margin: 0px; white-space: break-spaces; background-color: var(--bgColor-neutral-muted, var(--color-neutral-muted)); border-radius: 6px;">process.recoCTPPS</code><span> </span>in config's<span> </span><code class="notranslate" style="box-sizing: border-box; font-family: ui-monospace, SFMono-Regular, &quot;SF Mono&quot;, Menlo, Consolas, &quot;Liberation Mono&quot;, monospace; font-size: 11.9px; padding: 0.2em 0.4em; margin: 0px; white-space: break-spaces; background-color: var(--bgColor-neutral-muted, var(--color-neutral-muted)); border-radius: 6px;">process.path</code>) with the use of Tags and then with the use of XML files. Because TotemAnalysisMaskRcd cannot be taken from XML in both cases it was loaded from a Tag - but it shouldn't make any difference since this record contains empty object and no data.</p><p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; color: rgb(14, 17, 22); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Then I compared plots generated with the use of Tags with plots generated with the use of XMLs. They looked the same.</p><p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; color: rgb(14, 17, 22); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">This test has been done for all detectors (TimingDiamond, TrackingStrips, TotemT2, TotemTiming) and here are the resulting plots:<span> </span><a href="https://cernbox.cern.ch/s/jQ1ofbYnBNbiCOs" rel="nofollow" style="box-sizing: border-box; background-color: transparent; color: var(--fgColor-accent, var(--color-accent-fg)); text-decoration: underline; text-underline-offset: 0.2rem;">https://cernbox.cern.ch/s/jQ1ofbYnBNbiCOs</a></p>

### CODE REVIEW

**Comment by smuzaffar** [comment]
Milestone for this pull request has been moved to CMSSW_14_0_X.Please open a backport if it should also go in to CMSSW_13_3_X.

**Comment by perrotta** [comment]
Thank you @grzanka 
I tested this PR with wf 11634, as in https://github.com/cms-sw/cmssw/pull/42711#issuecomment-1785749354, and the candidate GT `133X_mcRun3_2022_realistic_Candidate_2023_10_27_06_10_07` that had been provided by Saumya, and I can confirm that the workflow finishes without errors: great!

**Comment by tjavaid** [comment]
please test

**Comment by perrotta** [comment]
@grzanka could you please close this PR, as you already managed to rebase correctly https://github.com/cms-sw/cmssw/pull/42711.

@tjavaid please abort the tests, to save resources: they will not succeed anyhow without the needed GT updates that are in another PR, and moreover this PR is a duplicate of https://github.com/cms-sw/cmssw/pull/42711 that will get closed

**Comment by tjavaid** [comment]
please abort

**Comment by grzanka** [comment]
> @grzanka could you please close this PR, as you already managed to rebase correctly #42711.

done

**Pull request closed without merging**
