### PR TITLE
Payload generator 7 4 x

### PR DESCRIPTION
**Pull request by andrewj314**
Backport of #9945 to 7_4_X

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/10070	a4bfa55
- based on visual code inspection, the changes are the same as in https://github.com/cms-sw/cmssw/pull/9945	cf2e034
- from #9945 signoff: event processing workflows are not affected, confirmed by jenkins (no differences in comparisons)

**Comment by ggovi** [comment]
+1

**Comment by mmusich** [comment]
+1

**Comment by davidlange6** [comment]
@andrewj314 - I think this is obsolete- (it doesn't merge) - will close..

**Pull request closed without merging**
