### PR TITLE
Tracker DQM HI Quality Test tuning for Offline and Online (backport of #25374)

### PR DESCRIPTION
**Pull request by arossi83**
Updates of some DQM Quality Test threshold for both Offline and Online Tracker DQM. Mainly for HI data taking, selection of the correct parameters via Era modifier. Backport of #25374

This PR reverts back some changes done on #25254 since now the correct configuration parameters are selected via Era Modifier

### CODE REVIEW

**Comment by arossi83** [comment]
@fabiocos with this PR I addressed your requests done on #25254. Now the same changes have been submitted also to master.

**Comment by andrius-k** [comment]
please test

**Comment by andrius-k** [comment]
+1

Is this PR needed for offline? If not I think it could be closed.

**Comment by arossi83** [comment]
@andrius-k this PR (should) not change at all what the Offline does actually but it makes everything more robust. Moreover this PR addresses some requests from @fabiocos did on PR #25254 (which was merged quickly since it was needed for HI offline DQM

**Comment by fabiocos** [comment]
+1

**Pull request merged**
