### PR TITLE
Code Fix to read tower geometry correctly in Ecal DQM StatusManager  [12_3_X]

### PR DESCRIPTION
**Pull request by abhih1**
#### PR description:

This PR fixes the code to read tower geometry correctly in Ecal DQM StatusManager.
Additionally the `toGet` method of accessing the DB tags is removed from the Ecal DQM config, on the suggestion of AlcaDB.

#### PR validation:
PR is validated by running a local test which creates an sqlite file which is uploaded to the DB and verified with an online DQM run on a test DQM GUI. Everything looks as expected.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:
Backport of https://github.com/cms-sw/cmssw/pull/38357
Backport needed to maintain continuity in production versions

### CODE REVIEW

**Comment by emanueleusai** [comment]
please test

**Comment by emanueleusai** [comment]
type ecal

**Comment by emanueleusai** [comment]
backport of #38357

**Comment by tvami** [comment]
assign alca

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by malbouis** [comment]
@cmsbuild , please test with #38459

**Comment by tvami** [comment]
+alca
 * that unit test is knowns to fail, has nothing to do with this PR
 * otherwise the relevant unit test passes
 * https://github.com/cms-sw/cmssw/pull/38459 should merge first

**Comment by emanueleusai** [comment]
testing at P5

**Comment by francescobrivio** [comment]
urgent

 - I understood from Rosma this was succesfully tested in P5

**Comment by abhih1** [comment]
> urgent
> 
>     * I understood from Rosma this was succesfully tested in P5

If this is the online playback of this PR run 354296: https://cmsweb.cern.ch/dqm/online-playback/session
then the tag is not working. The red towers in the ECAL global summary plots should be dark red if the tag has gone through.  
Please do not merge unless this is correct.

**Comment by tvami** [comment]
I dont think that's that playback.
The GT is incorrect
https://cmsweb.cern.ch/dqm/online-playback/start?runnr=0;dataset=/Global/Online/ALL;sampletype=live;filter=all;referencepos=overlay;referenceshow=customise;referencenorm=True;referenceobj1=refobj;referenceobj2=none;referenceobj3=none;referenceobj4=none;search=;striptype=object;stripruns=;stripaxis=run;stripomit=none;workspace=Info;size=M;root=Quick%20collection;focus=Info/ProvInfo/Globaltag;zoom=yes;

it should be v13 or the candidate we provided

https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_dataRun3_HLT_v12/123X_dataRun3_HLT_v13

**Comment by francescobrivio** [comment]
> > urgent
> > ```
> > * I understood from Rosma this was succesfully tested in P5
> > ```
> 
> If this is the P5 online playback of this PR run 354296: https://cmsweb.cern.ch/dqm/online-playback/session then the tag is not working. The red towers in the ECAL summary plots should be dark red/dark yellow if the tag has gone through. Please do not merge unless this is corrected.

@abhih1 I think the test was done with the old GT.

@ahmad3213 @rvenditti please repeat the playback tast using HLT GT: `123X_dataRun3_HLT_v13`

**Comment by abhih1** [comment]
Ok thanks! Dear Core DQM, Please post a link with the correct playback set so that I can verify.

**Comment by emanueleusai** [comment]
we are investigating now

**Comment by emanueleusai** [comment]
we are repeating tests with v13

**Comment by abhih1** [comment]
> we are repeating tests with v13

Thanks. Looks OK now.

**Comment by emanueleusai** [comment]
it looks like you checked the results of the replay already. Everything is running ok on our side as well, so I am approving

**Comment by emanueleusai** [comment]
+1

**Comment by qliphy** [comment]
+1

**Comment by qliphy** [comment]
merge

**Pull request merged**
