### PR TITLE
[UBSAN] Fix errors in RecoVertex/PrimaryVertexProducer and PhysicsTools/PatAlgos

### LINKED ISSUE #43341: [UBSAN] runtime error: reference binding to null pointer
In UBSAN_X IBs, we see the runtime errors about "reference binding to null pointer" [reported](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_amd64_gcc12/CMSSW_14_0_UBSAN_X_2023-11-17-2300/pyRelValMatrixLogs/run/138.3_RunMinimumBias2021Splash/step3_RunMinimumBias2021Splash.log#/1859) in RelVal 138.3:
<details>
<summary>Some stack traces</summary>

```
/pool/condor/dir_44888/jenkins/workspace/build-any-ib/w/el8_amd64_gcc12/external/gcc/12.3.1-40d504be6370b5a30e3947a6e575ca28/include/c++/12.3.1/bits/stl_iterator.h:1096:17: runtime error: reference binding to null pointer of type 'double'
    #0 0x147f2306a9ef  (/cvmfs/.../CMSSW_14_0_UBSANR630_X_2023-11-19-2300/lib/el8_amd64_gcc12/libRecoVertexPrimaryVertexProducer.so+0x4d69ef)
    #1 0x147f2307c513  (/cvmfs/.../CMSSW_14_0_UBSANR630_X_2023-11-19-2300/lib/el8_amd64_gcc12/libRecoVertexPrimaryVertexProducer.so+0x4e8513)
    #2 0x147f23090659  (/cvmfs/.../CMSSW_14_0_UBSANR630_X_2023-11-19-2300/lib/el8_amd64_gcc12/libRecoVertexPrimaryVertexProducer.so+0x4fc659)
    #3 0x147f235929b6  (/cvmfs/.../CMSSW_14_0_UBSANR630_X_2023-11-19-2300/lib/el8_amd64_gcc12/pluginRecoVertexPrimaryVertexProducerPlugins.so+0x1159b6)
    #4 0x14814028104e in edm::stream::EDProducerAdaptorBase::doEvent(edm::EventTransitionInfo const&, edm::ActivityRegistry*, edm::ModuleCallingContext const*) /pool/condor/dir_44888/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/017a81777288b3c2017036092c9ddf12/opt/cmssw/el8_amd64_gcc12/cms/cmssw/CMSSW_14_0_UBSANR630_X_2023-11-19-2300/src/FWCore/Framework/src/stream/EDProducerAdaptorBase.cc:82
    #5 0x14814012f2c8 in edm::WorkerT<edm::stream::EDProducerAdaptorBase>::implDo(edm::EventTransitionInfo const&, edm::ModuleCallingContext const*) /pool/condor/dir_44888/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/017a81777288b3c2017036092c9ddf12/opt/cmssw/el8_amd64_gcc12/cms/cmssw/CMSSW_14_0_UBSANR630_X_2023-11-19-2300/src/FWCore/Framework/src/WorkerT.cc:202
    #6 0x14813f90806f in edm::workerhelper::CallImpl<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >::call(edm::Worker*, edm::StreamID, edm::EventTransitionInfo const&, edm::ActivityRegistry*, edm::ModuleCallingContext const*, edm::StreamContext const*) /pool/condor/dir_44888/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/017a81777288b3c2017036092c9ddf12/opt/cmssw/el8_amd64_gcc12/cms/cmssw/CMSSW_14_0_UBSANR630_X_2023-11-19-2300/src/FWCore/Framework/interface/maker/Worker.h:666
    #7 0x14813f90806f in edm::Worker::runModule<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::TransitionInfoType const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*)::{lambda()#1}::operator()() const /pool/condor/dir_44888/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/017a81777288b3c2017036092c9ddf12/opt/cmssw/el8_amd64_gcc12/cms/cmssw/CMSSW_14_0_UBSANR630_X_2023-11-19-2300/src/FWCore/Framework/interface/maker/Worker.h:1171
    #8 0x14813f90806f in decltype ({parm#1}()) edm::convertException::wrap<edm::Worker::runModule<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::TransitionInfoType const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*)::{lambda()#1}>(edm::Worker::runModule<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::TransitionInfoType const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*)::{lambda()#1}) /pool/condor/dir_44888/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/017a81777288b3c2017036092c9ddf12/opt/cmssw/el8_amd64_gcc12/cms/cmssw/CMSSW_14_0_UBSANR630_X_2023-11-19-2300/src/FWCore/Utilities/interface/ConvertException.h:21
    #9 0x14813f908a79 in bool edm::Worker::runModule<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::TransitionInfoType const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*) /pool/condor/dir_44888/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/017a81777288b3c2017036092c9ddf12/opt/cmssw/el8_amd64_gcc12/cms/cmssw/CMSSW_14_0_UBSANR630_X_2023-11-19-2300/src/FWCore/Framework/interface/maker/Worker.h:1170
    #10 0x14813f908a79 in std::__exception_ptr::exception_ptr edm::Worker::runModuleAfterAsyncPrefetch<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(std::__exception_ptr::exception_ptr, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::TransitionInfoType const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*) /pool/condor/dir_44888/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/017a81777288b3c2017036092c9ddf12/opt/cmssw/el8_amd64_gcc12/cms/cmssw/CMSSW_14_0_UBSANR630_X_2023-11-19-2300/src/FWCore/Framework/interface/maker/Worker.h:1084
    #11 0x14813f920dcf in edm::Worker::RunModuleTask<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >::execute() /pool/condor/dir_44888/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/017a81777288b3c2017036092c9ddf12/opt/cmssw/el8_amd64_gcc12/cms/cmssw/CMSSW_14_0_UBSANR630_X_2023-11-19-2300/src/FWCore/Framework/interface/maker/Worker.h:495
    #12 0x14814142e759 in operator() /pool/condor/dir_44888/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/017a81777288b3c2017036092c9ddf12/opt/cmssw/el8_amd64_gcc12/cms/cmssw/CMSSW_14_0_UBSANR630_X_2023-11-19-2300/src/FWCore/Concurrency/src/WaitingTaskList.cc:206
    #13 0x14814142e759 in task_ptr_or_nullptr_impl<const edm::WaitingTaskList::announce()::<lambda()>&> /pool/condor/dir_44888/jenkins/workspace/build-any-ib/w/el8_amd64_gcc12/external/tbb/v2021.9.0-e755918dac6a30ec36eff63ac4f7ddec/include/oneapi/tbb/task_group.h:115
    #14 0x14814142e759 in task_ptr_or_nullptr<const edm::WaitingTaskList::announce()::<lambda()>&> /pool/condor/dir_44888/jenkins/workspace/build-any-ib/w/el8_amd64_gcc12/external/tbb/v2021.9.0-e755918dac6a30ec36eff63ac4f7ddec/include/oneapi/tbb/task_group.h:125
    #15 0x14814142e759 in execute /pool/condor/dir_44888/jenkins/workspace/build-any-ib/w/el8_amd64_gcc12/external/tbb/v2021.9.0-e755918dac6a30ec36eff63ac4f7ddec/include/oneapi/tbb/task_group.h:452
    #16 0x14813874f95a in tbb::detail::d1::task* tbb::detail::r1::task_dispatcher::local_wait_for_all<false, tbb::detail::r1::outermost_worker_waiter>(tbb::detail::d1::task*, tbb::detail::r1::outermost_worker_waiter&) /data/cmsbld/jenkins/workspace/auto-builds/CMSSW_13_3_0_pre3-el8_amd64_gcc12/build/CMSSW_13_3_0_pre3-build/BUILD/el8_amd64_gcc12/external/tbb/v2021.9.0-e755918dac6a30ec36eff63ac4f7ddec/tbb-v2021.9.0/src/tbb/task_dispatcher.h:322
    #17 0x14813874f95a in tbb::detail::d1::task* tbb::detail::r1::task_dispatcher::local_wait_for_all<tbb::detail::r1::outermost_worker_waiter>(tbb::detail::d1::task*, tbb::detail::r1::outermost_worker_waiter&) /data/cmsbld/jenkins/workspace/auto-builds/CMSSW_13_3_0_pre3-el8_amd64_gcc12/build/CMSSW_13_3_0_pre3-build/BUILD/el8_amd64_gcc12/external/tbb/v2021.9.0-e755918dac6a30ec36eff63ac4f7ddec/tbb-v2021.9.0/src/tbb/task_dispatcher.h:458
    #18 0x14813874f95a in tbb::detail::r1::arena::process(tbb::detail::r1::thread_data&) /data/cmsbld/jenkins/workspace/auto-builds/CMSSW_13_3_0_pre3-el8_amd64_gcc12/build/CMSSW_13_3_0_pre3-build/BUILD/el8_amd64_gcc12/external/tbb/v2021.9.0-e755918dac6a30ec36eff63ac4f7ddec/tbb-v2021.9.0/src/tbb/arena.cpp:137
    #19 0x14813874f95a in tbb::detail::r1::market::process(rml::job&) /data/cmsbld/jenkins/workspace/auto-builds/CMSSW_13_3_0_pre3-el8_amd64_gcc12/build/CMSSW_13_3_0_pre3-build/BUILD/el8_amd64_gcc12/external/tbb/v2021.9.0-e755918dac6a30ec36eff63ac4f7ddec/tbb-v2021.9.0/src/tbb/market.cpp:599
    #20 0x148138751b0d in tbb::detail::r1::rml::private_worker::run() /data/cmsbld/jenkins/workspace/auto-builds/CMSSW_13_3_0_pre3-el8_amd64_gcc12/build/CMSSW_13_3_0_pre3-build/BUILD/el8_amd64_gcc12/external/tbb/v2021.9.0-e755918dac6a30ec36eff63ac4f7ddec/tbb-v2021.9.0/src/tbb/private_server.cpp:271
    #21 0x148138751b0d in tbb::detail::r1::rml::private_worker::thread_routine(void*) /data/cmsbld/jenkins/workspace/auto-builds/CMSSW_13_3_0_pre3-el8_amd64_gcc12/build/CMSSW_13_3_0_pre3-build/BUILD/el8_amd64_gcc12/external/tbb/v2021.9.0-e755918dac6a30ec36eff63ac4f7ddec/tbb-v2021.9.0/src/tbb/private_server.cpp:221
    #22 0x14813725b1c9 in start_thread (/lib64/libpthread.so.0+0x81c9)
    #23 0x148136ec7e72 in __clone (/lib64/libc.so.6+0x39e72)

/pool/condor/dir_44888/jenkins/workspace/build-any-ib/w/el8_amd64_gcc12/external/gcc/12.3.1-40d504be6370b5a30e3947a6e575ca28/include/c++/12.3.1/bits/stl_vector.h:1207:16: runtime error: reference binding to null pointer of type 'value_type'
    #0 0x147f2306a9db  (/cvmfs/.../CMSSW_14_0_UBSANR630_X_2023-11-19-2300/lib/el8_amd64_gcc12/libRecoVertexPrimaryVertexProducer.so+0x4d69db)
    #1 0x147f2307c513  (/cvmfs/.../CMSSW_14_0_UBSANR630_X_2023-11-19-2300/lib/el8_amd64_gcc12/libRecoVertexPrimaryVertexProducer.so+0x4e8513)
    #2 0x147f23090659  (/cvmfs/.../CMSSW_14_0_UBSANR630_X_2023-11-19-2300/lib/el8_amd64_gcc12/libRecoVertexPrimaryVertexProducer.so+0x4fc659)
    #3 0x147f235929b6  (/cvmfs/.../CMSSW_14_0_UBSANR630_X_2023-11-19-2300/lib/el8_amd64_gcc12/pluginRecoVertexPrimaryVertexProducerPlugins.so+0x1159b6)
    #4 0x14814028104e in edm::stream::EDProducerAdaptorBase::doEvent(edm::EventTransitionInfo const&, edm::ActivityRegistry*, edm::ModuleCallingContext const*) /pool/condor/dir_44888/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/017a81777288b3c2017036092c9ddf12/opt/cmssw/el8_amd64_gcc12/cms/cmssw/CMSSW_14_0_UBSANR630_X_2023-11-19-2300/src/FWCore/Framework/src/stream/EDProducerAdaptorBase.cc:82
    #5 0x14814012f2c8 in edm::WorkerT<edm::stream::EDProducerAdaptorBase>::implDo(edm::EventTransitionInfo const&, edm::ModuleCallingContext const*) /pool/condor/dir_44888/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/017a81777288b3c2017036092c9ddf12/opt/cmssw/el8_amd64_gcc12/cms/cmssw/CMSSW_14_0_UBSANR630_X_2023-11-19-2300/src/FWCore/Framework/src/WorkerT.cc:202
    #6 0x14813f90806f in edm::workerhelper::CallImpl<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >::call(edm::Worker*, edm::StreamID, edm::EventTransitionInfo const&, edm::ActivityRegistry*, edm::ModuleCallingContext const*, edm::StreamContext const*) /pool/condor/dir_44888/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/017a81777288b3c2017036092c9ddf12/opt/cmssw/el8_amd64_gcc12/cms/cmssw/CMSSW_14_0_UBSANR630_X_2023-11-19-2300/src/FWCore/Framework/interface/maker/Worker.h:666
    #7 0x14813f90806f in edm::Worker::runModule<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::TransitionInfoType const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*)::{lambda()#1}::operator()() const /pool/condor/dir_44888/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/017a81777288b3c2017036092c9ddf12/opt/cmssw/el8_amd64_gcc12/cms/cmssw/CMSSW_14_0_UBSANR630_X_2023-11-19-2300/src/FWCore/Framework/interface/maker/Worker.h:1171
    #8 0x14813f90806f in decltype ({parm#1}()) edm::convertException::wrap<edm::Worker::runModule<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::TransitionInfoType const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*)::{lambda()#1}>(edm::Worker::runModule<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::TransitionInfoType const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*)::{lambda()#1}) /pool/condor/dir_44888/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/017a81777288b3c2017036092c9ddf12/opt/cmssw/el8_amd64_gcc12/cms/cmssw/CMSSW_14_0_UBSANR630_X_2023-11-19-2300/src/FWCore/Utilities/interface/ConvertException.h:21
    #9 0x14813f908a79 in bool edm::Worker::runModule<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::TransitionInfoType const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*) /pool/condor/dir_44888/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/017a81777288b3c2017036092c9ddf12/opt/cmssw/el8_amd64_gcc12/cms/cmssw/CMSSW_14_0_UBSANR630_X_2023-11-19-2300/src/FWCore/Framework/interface/maker/Worker.h:1170
    #10 0x14813f908a79 in std::__exception_ptr::exception_ptr edm::Worker::runModuleAfterAsyncPrefetch<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(std::__exception_ptr::exception_ptr, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::TransitionInfoType const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*) /pool/condor/dir_44888/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/017a81777288b3c2017036092c9ddf12/opt/cmssw/el8_amd64_gcc12/cms/cmssw/CMSSW_14_0_UBSANR630_X_2023-11-19-2300/src/FWCore/Framework/interface/maker/Worker.h:1084
    #11 0x14813f920dcf in edm::Worker::RunModuleTask<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >::execute() /pool/condor/dir_44888/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/017a81777288b3c2017036092c9ddf12/opt/cmssw/el8_amd64_gcc12/cms/cmssw/CMSSW_14_0_UBSANR630_X_2023-11-19-2300/src/FWCore/Framework/interface/maker/Worker.h:495
    #12 0x14814142e759 in operator() /pool/condor/dir_44888/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/017a81777288b3c2017036092c9ddf12/opt/cmssw/el8_amd64_gcc12/cms/cmssw/CMSSW_14_0_UBSANR630_X_2023-11-19-2300/src/FWCore/Concurrency/src/WaitingTaskList.cc:206
    #13 0x14814142e759 in task_ptr_or_nullptr_impl<const edm::WaitingTaskList::announce()::<lambda()>&> /pool/condor/dir_44888/jenkins/workspace/build-any-ib/w/el8_amd64_gcc12/external/tbb/v2021.9.0-e755918dac6a30ec36eff63ac4f7ddec/include/oneapi/tbb/task_group.h:115
    #14 0x14814142e759 in task_ptr_or_nullptr<const edm::WaitingTaskList::announce()::<lambda()>&> /pool/condor/dir_44888/jenkins/workspace/build-any-ib/w/el8_amd64_gcc12/external/tbb/v2021.9.0-e755918dac6a30ec36eff63ac4f7ddec/include/oneapi/tbb/task_group.h:125
    #15 0x14814142e759 in execute /pool/condor/dir_44888/jenkins/workspace/build-any-ib/w/el8_amd64_gcc12/external/tbb/v2021.9.0-e755918dac6a30ec36eff63ac4f7ddec/include/oneapi/tbb/task_group.h:452
    #16 0x14813874f95a in tbb::detail::d1::task* tbb::detail::r1::task_dispatcher::local_wait_for_all<false, tbb::detail::r1::outermost_worker_waiter>(tbb::detail::d1::task*, tbb::detail::r1::outermost_worker_waiter&) /data/cmsbld/jenkins/workspace/auto-builds/CMSSW_13_3_0_pre3-el8_amd64_gcc12/build/CMSSW_13_3_0_pre3-build/BUILD/el8_amd64_gcc12/external/tbb/v2021.9.0-e755918dac6a30ec36eff63ac4f7ddec/tbb-v2021.9.0/src/tbb/task_dispatcher.h:322
    #17 0x14813874f95a in tbb::detail::d1::task* tbb::detail::r1::task_dispatcher::local_wait_for_all<tbb::detail::r1::outermost_worker_waiter>(tbb::detail::d1::task*, tbb::detail::r1::outermost_worker_waiter&) /data/cmsbld/jenkins/workspace/auto-builds/CMSSW_13_3_0_pre3-el8_amd64_gcc12/build/CMSSW_13_3_0_pre3-build/BUILD/el8_amd64_gcc12/external/tbb/v2021.9.0-e755918dac6a30ec36eff63ac4f7ddec/tbb-v2021.9.0/src/tbb/task_dispatcher.h:458
    #18 0x14813874f95a in tbb::detail::r1::arena::process(tbb::detail::r1::thread_data&) /data/cmsbld/jenkins/workspace/auto-builds/CMSSW_13_3_0_pre3-el8_amd64_gcc12/build/CMSSW_13_3_0_pre3-build/BUILD/el8_amd64_gcc12/external/tbb/v2021.9.0-e755918dac6a30ec36eff63ac4f7ddec/tbb-v2021.9.0/src/tbb/arena.cpp:137
    #19 0x14813874f95a in tbb::detail::r1::market::process(rml::job&) /data/cmsbld/jenkins/workspace/auto-builds/CMSSW_13_3_0_pre3-el8_amd64_gcc12/build/CMSSW_13_3_0_pre3-build/BUILD/el8_amd64_gcc12/external/tbb/v2021.9.0-e755918dac6a30ec36eff63ac4f7ddec/tbb-v2021.9.0/src/tbb/market.cpp:599
    #20 0x148138751b0d in tbb::detail::r1::rml::private_worker::run() /data/cmsbld/jenkins/workspace/auto-builds/CMSSW_13_3_0_pre3-el8_amd64_gcc12/build/CMSSW_13_3_0_pre3-build/BUILD/el8_amd64_gcc12/external/tbb/v2021.9.0-e755918dac6a30ec36eff63ac4f7ddec/tbb-v2021.9.0/src/tbb/private_server.cpp:271
    #21 0x148138751b0d in tbb::detail::r1::rml::private_worker::thread_routine(void*) /data/cmsbld/jenkins/workspace/auto-builds/CMSSW_13_3_0_pre3-el8_amd64_gcc12/build/CMSSW_13_3_0_pre3-build/BUILD/el8_amd64_gcc12/external/tbb/v2021.9.0-e755918dac6a30ec36eff63ac4f7ddec/tbb-v2021.9.0/src/tbb/private_server.cpp:221
    #22 0x14813725b1c9 in start_thread (/lib64/libpthread.so.0+0x81c9)
    #23 0x148136ec7e72 in __clone (/lib64/libc.so.6+0x39e72)
```

</details>

(the actual failure of this relval is probably not related to these errors, see [#37362](https://github.com/cms-sw/cmssw/issues/37362))

### PR DESCRIPTION
**Pull request by iarspider**
Fixes https://github.com/cms-sw/cmssw/issues/43341 as suggested by @slava77 in https://github.com/cms-sw/cmssw/issues/43341#issuecomment-1824477214 and @makortel in https://github.com/cms-sw/cmssw/issues/43341#issuecomment-1828168711.

Validation: bot tests

### CODE REVIEW

**Comment by iarspider** [comment]
please test workflow 138.3 for CMSSW_14_0_UBSAN_X

(This RelVal will most likely segfault due to #37362, but the runtime error should be gone)

**Comment by iarspider** [comment]
please test workflow 138.3 for CMSSW_14_0_UBSAN_X

**Comment by iarspider** [comment]
please test workflow 138.3

**Comment by slava77** [comment]
@iarspider 
you may want to update the PR description and perhaps the title as well to mention the fix in PhysicsTools/PatAlgos, which has nothing to do with RecoVertex.

**Comment by jfernan2** [comment]
+1

**Comment by vlimant** [comment]
+1

**Comment by rappoccio** [comment]
+1

**Pull request merged**
