### PR TITLE
bsunanda:Run2-hcx39 Add a scenario with PhaseI tracker, PhaseII muon for HGCAL

### PR DESCRIPTION
**Pull request by bsunanda**
@lgray This is the scenario with V5 HGCal

### CODE REVIEW

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by bsunanda** [comment]
The failures have nothing to do with this PR. This PR only adds 2 python scripts which are not used by the failed tests. Can one restart the test.
________________________________

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by ianna** [comment]
@bsunanda and @lgray - wouldn't it be better to call the scenario Extended2023? HGCal is a baseline.

**Comment by lgray** [comment]
@ianna This scenario is a pretty special Frankstein's monster version of CMS. It is certainly not Extended2023 since it has the present tracker in it

I propose, instead, to rename the scenario PostLS1HGCalMuonTest. That is more descriptive and less confusing and also indicates it's for testing.

**Comment by ianna** [comment]
@lgray - Extended2023 scenario as it is now is also pretty special with Phase1 tracker. It would be better to converge towards a final one.

**Comment by lgray** [comment]
@ianna HGCal should proceed at its own pace an should not be bound to waiting for the tracker or any other detector. We could agree to remove this particular scenario when it is no longer necessary? I would prefer not to wait on any other development timelines for the ability to test HGCal software in a structured way.

**Comment by ianna** [comment]
@lgray - ok. May I ask to update Extended2023 then? Please, keep it in sync with this one.

**Comment by lgray** [comment]
@ianna If you think it is useful to do so, sure.

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
@Dr15Jones Looks like there something wrong with your parser?
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-11679/8708/addOnTests/hlt_data_50nsGRun/cmsDriver.py_RelVal_-s_HLT:50nsGRun,RAW2DIGI,L1Reco,RECO_--data_--scenario=pp_-n_10_--conditions_auto:run2_data_50nsGRun_--relval_9000,50_--datatier_.log

**Comment by lgray** [comment]
@bsunanda Mind updating Extended2023 in 76X and adding it to this PR as requested by @ianna?

**Comment by Dr15Jones** [comment]
#11684 fixes the problem

**Comment by lgray** [comment]
@Dr15Jones OK, thanks. I'll wait for the IBs to update.

**Comment by bsunanda** [comment]
Hi Yana

I do not see the python subdirectory in Geometry/TrackerNumberingBuilder. What has gone wrong? How to get the files trackerTopology_cfi.py or trackerNumberingGeometry_cfi.py files? Are they in cfipython? Regards

Sunanda
________________________________

**Comment by bsunanda** [comment]
Updated taking comments from Yana
@cmsbuild please initiate the tests
________________________________

**Comment by lgray** [comment]
@cmsbuild please test

(@bsunanda you are not on the list of people who can do this, as far as I know)

**Comment by ianna** [comment]
+1

**Comment by lgray** [comment]
@davidlange6 can you bring this one in too? ToT PR needs it.

**Comment by lgray** [comment]
@bsunanda Can you please close this PR, it is no longer necessary.

**Comment by bsunanda** [comment]
Integrated to 8_0_X. So close this

**Pull request closed without merging**
