### PR TITLE
L1 Scouting Online Selection modules

### PR DESCRIPTION
**Pull request by Mmiglio**
#### PR description:
This PR introduces the modules used for the L1 Scouting Online selection, which will complement the "Zero bias" stream. 
The selection stream was discussed during L1 Trigger DPG meetings (e.g. [link](https://indico.cern.ch/event/1425692/contributions/5996288/attachments/2874131/5032890/24_06_10__L1DPG__stream-rates%20(1).pdf ))

Related to this PR, a new category is introduced with https://github.com/cms-sw/cms-bot/pull/2276.

#### PR validation:

The PR has been validate using files collected in the "Zero Bias" stream, e.g.
```
cmsRun test/L1ScoutingSelector.py inFile=file:root://xrootd-cms.infn.it///store/data/Run2024F/L1Scouting/L1SCOUT/v1/000/382/580/00000/00c66a36-4a65-4b2a-a637-0b02629cb1da.root numOrbits=100 outFile=/tmp/dump.root
```
In parallel, it was successfully tested in the Scouting system at P5.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

We would like this PR to be backported in a data-taking release (14_0_X) in order to collect data from pp collisions during 2024.

### CODE REVIEW

**Comment by smorovic** [comment]
@cmsbuild please test

**Comment by smorovic** [comment]
https://github.com/cms-sw/cms-bot/pull/2278 adds new package to cms-bot

**Comment by smorovic** [comment]
+daq

**Comment by Mmiglio** [comment]
https://github.com/cms-sw/cms-bot/pull/2276 assigns  this new package to `l1t` category. Can this PR be updated as well? 
adding @aloeliger as discussed in last week's L1 offline software meeting.

**Comment by epalencia** [comment]
+l1

**Comment by rappoccio** [comment]
+1

**Pull request merged**
