### PR TITLE
[12_4_X] Include EGM and L1T tags in mcRun3 and data GTs

### PR DESCRIPTION
**Pull request by tvami**
#### PR description:

See [PR38283](https://github.com/cms-sw/cmssw/pull/38283)

The GT diffs are listed below:
run3_hlt
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts//123X_dataRun3_HLT_frozen_v6/123X_dataRun3_HLT_frozen_v5

run3_hlt_relval
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts//124X_dataRun3_HLT_relval_v1/123X_dataRun3_HLT_relval_v9

run3_data
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts//124X_dataRun3_v2/124X_dataRun3_v1

run3_data_relval
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts//124X_dataRun3_relval_v2/124X_dataRun3_relval_v1

phase1_2022_design
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts//124X_mcRun3_2022_design_v4/124X_mcRun3_2022_design_v3

phase1_2022_realistic
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts//124X_mcRun3_2022_realistic_v4/124X_mcRun3_2022_realistic_v3

phase1_2022_cosmics
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts//124X_mcRun3_2022cosmics_realistic_deco_v5/124X_mcRun3_2022cosmics_realistic_deco_v4

phase1_2022_cosmics_design
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts//124X_mcRun3_2022cosmics_design_deco_v4/124X_mcRun3_2022cosmics_design_deco_v3

phase1_2022_realistic_hi
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts//124X_mcRun3_2022_realistic_HI_v4/124X_mcRun3_2022_realistic_HI_v3

phase1_2023_realistic
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts//124X_mcRun3_2023_realistic_v4/124X_mcRun3_2023_realistic_v3

phase1_2024_realistic
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts//124X_mcRun3_2024_realistic_v4/124X_mcRun3_2024_realistic_v3

phase2_realistic
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts//124X_mcRun4_realistic_v5/124X_mcRun4_realistic_v4

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Backport of https://github.com/cms-sw/cmssw/pull/38283

### CODE REVIEW

**Comment by tvami** [comment]
test parameters:
 * workflows = 136.897, 12034.0, 7.23, 12834.0

**Comment by tvami** [comment]
type l1t,egamma

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
backport of https://github.com/cms-sw/cmssw/pull/38283

**Comment by francescobrivio** [comment]
+alca

 - @tvami could you add to the PR description the GT diff links?

**Comment by tvami** [comment]
> could you add to the PR description the GT diff links?

Done, straight copy paste from the master PR

**Comment by qliphy** [comment]
+1

**Pull request merged**
