### PR TITLE
Removed using namespace from DDRegistry.h

### PR DESCRIPTION
**Pull request by Dr15Jones**

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by fabiocos** [comment]
+1

@Dr15Jones for my understanding, is this just aesthetics?

**Comment by Dr15Jones** [comment]
> @fabiocos wrote "for my understanding, is this just aesthetics?"

It is more than that. Doing a `using namespace` at file scope moves all the items in that namespace into the 'global' scope. Doing such in a header file is considered to be a very bad idea (which is why the static analyzer spots such cases). Effectively, one is 'infecting' all other header files that include the first header file with the same problem.

**Comment by fabiocos** [comment]
@Dr15Jones ok, as this is an interface I see the issue, there were several cleaning actions in the past as well...

**Pull request merged**
