### PR TITLE
adding Dstar filter for enriched MC production

### PR DESCRIPTION
**Pull request by vmariani**
D\* filter for official enriched Monte Carlo samples for 7_1_X

### CODE REVIEW

**Comment by govoni** [comment]
+1

**Comment by bendavid** [comment]
Is this functionality not contained in any of the existing filters?

If this is not already in 80x, then an additional pull request needs to be opened for 80x.

**Comment by vmariani** [comment]
Dear Josh,

this filter is not contained in any of the existing filters.
I just opened the pull request for 8_0_x.

Regards,
Valentina

Il 13/11/2015 10.26, Josh Bendavid ha scritto:

**Comment by davidlange6** [comment]
+1

**Pull request merged**
