### PR TITLE
[SIMULATION-UPGRADE] [Clang]Cleanup clang-analyzer warnings

### PR DESCRIPTION
**Pull request by smuzaffar**
Fixes clang-analyzer warning https://cmssdt.cern.ch/SDT/jenkins-artifacts/ib-static-analysis/CMSSW_14_2_X_2024-10-02-1100/el8_amd64_gcc12/build-logs/SimCalorimetry/HGCalSimAlgos/log.html

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by civanch** [comment]
@subirsarkar , please approve this PR - very technical

**Comment by Moanwar** [comment]
+Upgrade

**Comment by mandrenguyen** [comment]
+1

**Comment by subirsarkar** [comment]
+Upgrade

**Pull request merged**
