### PR TITLE
DD4hep: testDDAngularAlgorithm tweak

### PR DESCRIPTION
**Pull request by vargasa**
Fix testDDAngularAlgorithm namespace

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by smuzaffar** [comment]
@vargasa , we did a cleanup of some large data files which were merge in cmssw repo few days ago. Due to this cleanup this PR is now in a bad state (includes all the commits which we rewrite to avoid the large data files), Can you please rebase this PR based on new head?

**Comment by perrotta** [comment]
-1
(Not for reco, rebase needed)

**Comment by fabiocos** [comment]
please test

**Comment by cvuosalo** [comment]
+1

**Pull request merged**
