### PR TITLE
added esConsumes to modules in L1Trigger/L1TGEM

### PR DESCRIPTION
**Pull request by JamminJones**
#### PR description:

added esConsumes to 6 modules
#### PR validation:

the code compiles

### CODE REVIEW

**Comment by Dr15Jones** [comment]
This change was done under my supervision.

**Comment by Dr15Jones** [comment]
please test

**Comment by silviodonato** [comment]
do you have any comments @rekovic ?

**Comment by Dr15Jones** [comment]
ping

**Comment by rekovic** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
