### PR TITLE
[HETEROGENEOUS] Various fixes/improvements for unit test

### PR DESCRIPTION
**Pull request by smuzaffar**
Use full `$CMSSW_BASE/src` path which will allow us to run this test from any directory.

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by makortel** [comment]
Hmh, comparisons of 11634.914 reports a difference in this top-level histogram
image

I have no idea what that is, but this PR can not be causing it.

**Comment by makortel** [comment]
+heterogeneous

**Comment by rappoccio** [comment]
+1

Technical.

**Pull request merged**
