### PR TITLE
[10.1.X] Resurrection of Lorentz angle calibration integrated into MillePede alignment

### PR DESCRIPTION
**Pull request by ghellwig**
- integrated Lorentz angle calibration allows to use 0T and 3.8T data simultaneously in an alignment
- fixes code that was broken by alignment framework changes that happened since this became unmaintained
- changes have been validated and presented during the [Tracker DPG meeting on 21-March-2018](https://indico.cern.ch/event/688840/?showDate=all&showSession=all#35-la-calibration-in-alignment)

### CODE REVIEW

**Comment by ghellwig** [comment]
please test

**Comment by lpernie** [comment]
+1

**Comment by ghellwig** [comment]
thanks @lpernie

**Comment by fabiocos** [comment]
+1

**Pull request merged**
