### PR TITLE
Fix crash in DeDxEstimatorRekeyer

### PR DESCRIPTION
**Pull request by stahlleiton**
#### PR description:

This PR fixes the issue reported in https://github.com/cms-sw/cmssw/issues/46307

#### PR validation:

Tested by running over the crashing HIForward event reported by T0.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport to be made for 14_1_X

### CODE REVIEW

**Comment by mandrenguyen** [comment]
please test

**Comment by mandrenguyen** [comment]
urgent

**Comment by jfernan2** [comment]
+1

**Comment by mandrenguyen** [comment]
ping @cms-sw/xpog-l2

**Comment by hqucms** [comment]
+1

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
