### PR TITLE
Phase2-hgx333D Take care of invalid SiHits for V17 geometry of HGCal

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Take care of invalid SiHits for V17 geometry of HGCal

#### PR validation:

Use the scripts in Validation/HGCalValidation/scripts

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

Main modifications are in WF 23234.0 and they are expected

**Comment by bsunanda** [comment]
@srimanob Please sign this PR

**Comment by srimanob** [comment]
+Upgrade

With this PR, differences shown in PR test comes from D94 which is C20 (HGCal (v17)) as expected.

**Comment by srimanob** [comment]
Just curiosity, why this PR comes after https://github.com/cms-sw/cmssw/pull/40208, not in the same time (e.g. why the error does not show in the previous test)? Is the test script you are using for this PR different than the previous PR?

**Comment by bsunanda** [comment]
@srimanob During the first phase of testing we used 1000 single muon and a few hundred ttbar events, We made corrections on the basis of discrepancies observed there. We increase statistics by a factor of 5 and observed more cases which we correct now. We plan to increase statistics by a factor of 10 more in future.

**Comment by perrotta** [comment]
+1

**Pull request merged**
