### PR TITLE
Move DynamicWeightChoiceGenInfo into a LuminosityBlockCache

### PR DESCRIPTION
**Pull request by wddgit**
#### PR description:

Move DynamicWeightChoiceGenInfo into a LuminosityBlockCache. The primary goal for this change is to have DynamicWeightChoiceGenInfo always be set properly. Currently, it appears in the code that there is a possibility for it to use some values from an earlier lumi because all the values it contains are not always set at begin lumi. I'm not sure if this ever actually happens in practice. That would depend on the input.

The Core group's motivation to look at this code is that we are currently surveying all CMSSW to look for problems that a new Framework behavior might cause. The new behavior allows a stream to skip a lumi if at the time the stream is starting on the lumi at least one other stream has processed the lumi and all the events were already processed. Specifically the stream would skip the stream begin lumi and stream end lumi transitions. The performance advantage related to this occurs when there is an event that takes an extremely long time to process. That stream cannot finish its current lumi or any subsequent lumis. As other streams finish subsequent lumis, the limit on concurrent lumi is reached and all the other streams get stuck.

This lumi skipping would cause modules that rely on values set in previous lumis to get non reproducible results if those previous lumis might or might not have been skipped.

After this change, each weight choice object will be recreated from nothing for each lumi. This was already occurring for the first lumi in each run (but not later lumis in the run).

This change also has some side benefits.

* The weight choice is only initialized once per lumi instead of once per lumi per stream.
* There is only one copy in memory per lumi instead of one per stream per lumi.
* The weight choice object will be in the LuminosityBlockCache and that is similar to the way the other weight choice object is already in the RunCache.
* There were two constant vectors that I pulled out of the cache entirely and just made constexpr arrays.

The biggest change in the code is that a large block of code was moved from streamBeginLuminosityBlock to globalBeginLuminosityBlock.

Unless I made a mistake, I believe the results should be identical before and after. Exactly the same things should be happening during begin lumi to set the values in the weight choice object.

#### PR validation:

It builds. There is no unit test. Dozens of runTheMatrix.py tests at least execute this code. I also ran test 548.0 step3 and printed out values from the structure whose initialization was modified and contents are identical.

FYI @makortel

### CODE REVIEW

**Comment by wddgit** [comment]
please test

**Comment by makortel** [comment]
FYI @cms-sw/generators-l2

**Comment by makortel** [comment]
> Currently, it appears in the code that there is a possibility for it to use some values from an earlier lumi because all the values it contains are not always set at begin lumi. I'm not sure if this ever actually happens in practice. That would depend on the input.

We were wondering if the "input data products missing" for some lumis is something that is expected to happen in production? Or would that point to a mistake (e.g. in configuration)? @cms-sw/xpog-l2 @cms-sw/generators-l2

**Comment by vlimant** [comment]
enable nano

**Comment by vlimant** [comment]
please test

**Comment by vlimant** [comment]
a little tricky, as person power for GEN/NANO features is essentially negative.

> We were wondering if the "input data products missing" for some lumis is something that is expected to happen in production? Or would that point to a mistake (e.g. in configuration)? @cms-sw/xpog-l2 @cms-sw/generators-l2

my cents would be that anything that relies on assigned values at a random earlier lumi is suspicious to say the least, and what you propose is a better behaviour. @cms-sw/generators-l2 do we have an example of a sample where the gen weight information is mandatory, so that we can run on this as a test that things are looking ok after the fwk change requested here ?

**Comment by wddgit** [comment]
I will try to answer the question Matti asked, @makortel. Matti and I had discussed this before I submitted the PR and my original thought was that we should make the module throw if a product was not found. But after I looked at it more, I realized this module is intentionally designed to handle cases where some possible input product is not found. If you look here:

https://cmssdt.cern.ch/dxr/CMSSW/source/PhysicsTools/NanoAOD/plugins/GenWeightsTableProducer.cc#325

There are 3 cases:

* The "if" case handles the case where the LHEEventProduct product is found.
* The "else if" case, handles cases where that product is not found and the GenLumiInfoHeader product was found in the LuminosityBlock.
* The "else" case handles cases where both products are not found.

I don't know which of these cases are actually executed in production. The second case is the one most affected by the changes I made, but the other two also might also be affected under certain circumstances. Exactly how that works out would depend on the input data and configuration, which I do not understand very well.

So I no longer think we could simply throw an exception if a product is not found.

I'll add one more comment unrelated to all that. With the changes in this PR, the first lumi in a run should give exactly identical results. After the first lumi in a run, the results would only differ if the module was actually using values set in a previous lumi.

**Comment by wddgit** [comment]
I guess the conclusion from the discussion is there is not an expert responsible for this code and that I need to figure out how to test this myself.  I will try to find a test that runs the module, maybe add some temporary print statements (that I remove when done) and make sure it actually runs and the part I modified gives the results as before. I'll try the RelVal tests listed in the "Nano Comparison Summary". Hopefully one of those will actually run the module and use the object in the lumi.

**Comment by vlimant** [comment]
how urgent is this change for 14.0, and could we postpone a bit until we figure out how to test this? workflows in the matrix are unlikely to cover this in details

**Comment by makortel** [comment]
From `core` side this change is not urgent for 14_0_X (the framework-side change won't go there anyway).

**Comment by makortel** [comment]
@vlimant Do I understand correctly that XPOG and GEN would come up with some way to test this module?

**Comment by vlimant** [comment]
we will try to figure something out indeed, but if we can avoid the 14.0 rush, that'd be great

**Comment by makortel** [comment]
Thanks @vlimant, we can wait for the 14_0_0 to be finalized before coming back to the tests.

**Comment by wddgit** [comment]
There is no urgent rush on this, but I don't want it to be forgotten. 14.0.0 is out now. Any idea on the time scale for a test on this? Best would be if an expert could test it entirely. Or if manpower isn't available, I could try to do a test myself, but it would be very helpful if at least a configuration could be provided that at least runs the module.

Behavior and output shouldn't change. The test should just confirm this (that I didn't break something).

**Comment by vlimant** [comment]
@bbilin suggested to use a sample from any of https://cms-pdmv-prod.web.cern.ch/grasp/samples?campaign=Run3Summer23*GS&nanoaod=*&dataset=DY, for example [/DYto2E_MLL-2500to4000_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer23BPixMiniAODv4-130X_mcRun3_2023_realistic_postBPix_v2-v3/MINIAODSIM](https://cmsweb.cern.ch/das/request?input=/DYto2E_MLL-2500to4000_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer23BPixMiniAODv4-130X_mcRun3_2023_realistic_postBPix_v2-v3/MINIAODSIM) and verify the integrity of the affected branches

**Comment by makortel** [comment]
@vlimant Thanks. Is there some existing machinery (e.g. configuration, `cmsDriver` snippet, one of the workflows used in the PR tests) that could be used to process the `MINIAODSIM` such that this module is used? (and maybe something to inspect the resulting NANO?)

If not, it might be easier for us to craft a synthetic test.

**Comment by makortel** [comment]
> Is there some existing machinery (e.g. configuration, `cmsDriver` snippet, one of the workflows used in the PR tests) that could be used to process the `MINIAODSIM` such that this module is used?

Actually, would it make sense to add a NANO workflow using that sample for IB/PR tests so that this module would get exercised automatically in the future too?

**Comment by wddgit** [comment]
I'll try this exercise. I'll temporarily add a line in my working area at the beginning of the produce function that always throws in the module modified by this PR. Then I'll try runTheMatrix and see if anything fails.

**Comment by wddgit** [comment]
By adding a test where I temporarily added an exception throw every time the GenWeightsTableProducer is executed and running all the runTheMatrix tests I can now see the module is executed in the tests by a few dozen of the tests. I'll temporarily add some print statements in my working area and look at it with the debugger long enough to convince myself the module is behaving the same as  before for test 548.0 step3 and that should be good enough.

**Comment by wddgit** [comment]
After I printed out the contents of the structure whose initialization was modified in test 548.0 step 3, I get the same values with the changes and without modifications. This seems to be working identically. Now that it is tested I recommend approval unless you can see some problem. I'll edit the comment at the top also.

**Comment by vlimant** [comment]
+1

**Comment by rappoccio** [comment]
+1

**Pull request merged**
