### PR TITLE
[GEM] add DQM plots for GE21/GE0 and Fix on massive LogWarnings

### PR DESCRIPTION
**Pull request by quark2**
#### PR description:
There is issue #37906, massive LogWarnings from GEM DQM. It was due to the incomplete part of GE21/GE0. As progress on the development for GE21/GE0 DQM, the part has been updated and there are no more such LogWarnings.

#### PR validation:
Test are done and one can check again by `runTheMatrix` workflows

@jshlee @watson-ij

### CODE REVIEW

**Comment by emanueleusai** [comment]
please test

**Comment by emanueleusai** [comment]
@quark2 the PR add ~70Mb, that is more than 200 plots. Is this addition justified by the addition of MEs for GE21/GE0? are the plots all needed?

Given this is a significant addition to DQM monitoring elements I would recommend modifying the title to something along the lines of: "[GEM] add DQM plots for GE21/GE0 and Fix on massive LogWarnings"

**Comment by quark2** [comment]
Hi @emanueleusai, 

Yep, that's a good idea. Thanks! I've changed it.

**Comment by emanueleusai** [comment]
@quark2 thank you!

Can you comment on this too?

> the PR add ~70Mb, that is more than 200 plots. Is this addition justified by the addition of MEs for GE21/GE0? are the plots all needed?

**Comment by quark2** [comment]
@emanueleusai Ahh, sorry, I forgot to answer that...

Yep, these additional plots are expected and desired to be added, which is requested by GEM DPG.

**Comment by emanueleusai** [comment]
@quark2 Thank you very much for the clarification

**Comment by perrotta** [comment]
+1

**Pull request merged**
