### PR TITLE
[14_1_X] Era for UPC re-reco of 2016 pPb data

### PR DESCRIPTION
**Pull request by stahlleiton**
#### PR description:

Backport of https://github.com/cms-sw/cmssw/pull/46087

#### PR validation:

Tested using the relvals 180,180.1,181,181.1,141.901,142.901,142.903

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

### CODE REVIEW

**Comment by mandrenguyen** [comment]
backport of https://github.com/cms-sw/cmssw/pull/46087

**Comment by mandrenguyen** [comment]
please test

**Comment by AdrianoDee** [comment]
+pdmv

**Comment by perrotta** [comment]
+alca
- Verbatim backport of #46087

**Comment by jfernan2** [comment]
+1

**Comment by Moanwar** [comment]
+Upgrade

**Comment by perrotta** [comment]
@mandrenguyen this is also fully signed: could you please merge?

**Pull request merged**
