### PR TITLE
[102X][GT updates]  ECAL threshold, PF corrections, GEM geometry, HCAL conditions for 2018

### PR DESCRIPTION
**Pull request by lpernie**
# Summary of changes in Global Tags

## RunII data

   * **RunII HLTHI processing** : [101X_dataRun2_HLTHI_frozen_v7](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_dataRun2_HLTHI_frozen_v7) as [101X_dataRun2_HLTHI_frozen_v6](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_dataRun2_HLTHI_frozen_v6) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/101X_dataRun2_HLTHI_frozen_v7/101X_dataRun2_HLTHI_frozen_v6):
      * Ecal PFRecHit Thresholds 
      * PFClusterCor (ecal and jetmet)

   * **RunII HLT relval processing** : [101X_dataRun2_HLT_relval_v7](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_dataRun2_HLT_relval_v7) as [101X_dataRun2_HLT_relval_v6](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_dataRun2_HLT_relval_v6) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/101X_dataRun2_HLT_relval_v7/101X_dataRun2_HLT_relval_v6):
      * Ecal PFRecHit Thresholds 
      * PFClusterCor (ecal)
      * L1Menu_Collisions2018_v0_0_1

   * **RunII Offline processing** : [101X_dataRun2_v8](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_dataRun2_v8) as [101X_dataRun2_v7](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_dataRun2_v7) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/101X_dataRun2_v8/101X_dataRun2_v7):
      * Ecal PFRecHit Thresholds
      * PFClusterCor (ecal)
      * Hcal offline RespCorrs, RecoParams
      * PFCalibration_v9_mc

   * **RunII Offline relval processing** : [101X_dataRun2_relval_v8](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_dataRun2_relval_v8) as [101X_dataRun2_relval_v7](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_dataRun2_relval_v7) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/101X_dataRun2_relval_v8/101X_dataRun2_relval_v7):
      * Ecal PFRecHit Thresholds
      * Hcal offline RespCorrs, RecoParams
      * PFClusterCor (ecal)
      * PFCalibration_v9_mc
      * L1Menu_Collisions2018_v0_0_1

   * **RunII Prompt processing** : [101X_dataRun2_PromptLike_v8](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_dataRun2_PromptLike_v8) as [101X_dataRun2_PromptLike_v7](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_dataRun2_PromptLike_v7) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/101X_dataRun2_PromptLike_v8/101X_dataRun2_PromptLike_v7):
      * Ecal PFRecHit Thresholds
      * ecalPFClusterCor2018V1_E
      * L1Menu_Collisions2018_v0_0_1
      * PFCalibration_v9_mc

   * **RunI HLT processing** : [101X_dataRun2_HLT_frozen_v6](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_dataRun2_HLT_frozen_v6) as [101X_dataRun2_HLT_frozen_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_dataRun2_HLT_frozen_v5) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/101X_dataRun2_HLT_frozen_v6/101X_dataRun2_HLT_frozen_v5):
      * Ecal PFRecHit Thresholds

## RunI simulation

   * **RunI Heavy Ions scenario** : [101X_mcRun1_HeavyIon_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_mcRun1_HeavyIon_v4) as [101X_mcRun1_HeavyIon_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_mcRun1_HeavyIon_v2) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/101X_mcRun1_HeavyIon_v4/101X_mcRun1_HeavyIon_v2):
      * PF Calibration (ecal, jetmet)
      * Ecal PFRecHit Thresholds

   * **RunI Ideal scenario** : [101X_mcRun1_design_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_mcRun1_design_v4) as [101X_mcRun1_design_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_mcRun1_design_v2) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/101X_mcRun1_design_v4/101X_mcRun1_design_v2):
      * PF Calibration (ecal, jetmet) 
      * PFCalibration (jet met)

   * **RunI Proton-Lead scenario** : [101X_mcRun1_pA_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_mcRun1_pA_v4) as [101X_mcRun1_pA_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_mcRun1_pA_v2) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/101X_mcRun1_pA_v4/101X_mcRun1_pA_v2):
      * EcalPFRecHitThresholds_2018_v1_mc 
      * PF Calibration (ecal, jetmet)

   * **RunI Realistic scenario** : [101X_mcRun1_realistic_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_mcRun1_realistic_v4) as [101X_mcRun1_realistic_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_mcRun1_realistic_v2) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/101X_mcRun1_realistic_v4/101X_mcRun1_realistic_v2):
      * EcalPFRecHitThresholds_2018_v1_mc
      * PF Calibration (ecal, jetmet)

## RunII simulation

   * **RunII Asymptotic scenario** : [101X_mcRun2_asymptotic_v6](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_mcRun2_asymptotic_v6) as [101X_mcRun2_asymptotic_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_mcRun2_asymptotic_v4) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/101X_mcRun2_asymptotic_v6/101X_mcRun2_asymptotic_v4):
      * EcalPFRecHitThresholds
      * PF Calibration (ecal, jetmet)

   * **RunII CRAFT scenario** : [101X_mcRun2cosmics_startup_deco_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_mcRun2cosmics_startup_deco_v5) as [101X_mcRun2cosmics_startup_deco_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_mcRun2cosmics_startup_deco_v3) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/101X_mcRun2cosmics_startup_deco_v5/101X_mcRun2cosmics_startup_deco_v3):
      * EcalPFRecHitThresholds
      * PF Calibration (ecal, jetmet)

   * **RunII Heavy Ions scenario** : [101X_mcRun2_HeavyIon_v6](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_mcRun2_HeavyIon_v6) as [101X_mcRun2_HeavyIon_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_mcRun2_HeavyIon_v4) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/101X_mcRun2_HeavyIon_v6/101X_mcRun2_HeavyIon_v4):
      * EcalPFRecHitThresholds
      * PF Calibration (ecal, jetmet)

   * **RunII Ideal scenario** : [101X_mcRun2_design_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_mcRun2_design_v5) as [101X_mcRun2_design_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_mcRun2_design_v3) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/101X_mcRun2_design_v5/101X_mcRun2_design_v3):
      * EcalPFRecHitThresholds
      * PF Calibration (ecal, jetmet)

   * **RunII Proton-Lead scenario** : [101X_mcRun2_pA_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_mcRun2_pA_v5) as [101X_mcRun2_pA_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_mcRun2_pA_v3) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/101X_mcRun2_pA_v5/101X_mcRun2_pA_v3):
      * EcalPFRecHitThresholds
      * PF Calibration (ecal, jetmet)

   * **RunII Startup scenario** : [101X_mcRun2_startup_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_mcRun2_startup_v5) as [101X_mcRun2_startup_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_mcRun2_startup_v3) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/101X_mcRun2_startup_v5/101X_mcRun2_startup_v3):
      * EcalPFRecHitThresholds
      * PF Calibration (ecal, jetmet)

## Upgrade
   * **LS2 realistic scenario** : [101X_postLS2_realistic_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_postLS2_realistic_v5) as [101X_postLS2_realistic_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_postLS2_realistic_v4) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/101X_postLS2_realistic_v5/101X_postLS2_realistic_v4):
      * CSC Chamber Time Corrections
      * L1Menu_Collisions2018_v0_0_1
      * GEM Geometry
      * PF Correction (ECAL)
      * EcalPFRecHitThresholds
      * PFCalibration (jet met)

   * **LS2 ideal scenario** : [101X_postLS2_design_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_postLS2_design_v5) as [101X_postLS2_design_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_postLS2_design_v4) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/101X_postLS2_design_v5/101X_postLS2_design_v4):
      * CSC Chamber Time Corrections
      * L1Menu_Collisions2018_v0_0_1
      * GEM Geometry
      * PF Correction (ECAL)
      * EcalPFRecHitThresholds
      * PFCalibration (jet met)

   * **PhaseII realistic scenario** : [101X_upgrade2023_realistic_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_upgrade2023_realistic_v5) as [101X_upgrade2023_realistic_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_upgrade2023_realistic_v4) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/101X_upgrade2023_realistic_v5/101X_upgrade2023_realistic_v4):
      * CSC Chamber Time Corrections
      * L1Menu_Collisions2018_v0_0_1
      * GEM Geometry
      * PF Correction (ECAL)
      * EcalPFRecHitThresholds
      * PFCalibration (jet met)

   * **PhaseI 2018 cosmics scenario** : [101X_upgrade2018cosmics_realistic_deco_v8](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_upgrade2018cosmics_realistic_deco_v8) as [101X_upgrade2018cosmics_realistic_deco_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_upgrade2018cosmics_realistic_deco_v5) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/101X_upgrade2018cosmics_realistic_deco_v8/101X_upgrade2018cosmics_realistic_deco_v5):
      * CSC Chamber Time Corrections
      * L1Menu_Collisions2018_v0_0_1
      * GEM Geometry
      * PF Correction (ECAL)
      * EcalPFRecHitThresholds
      * PFCalibration (jet met)
      * Hcal QIEData, SiPMParam, Gains, Pedestal, Widths (effective and not)

   * **PhaseI 2018 design scenario** : [101X_upgrade2018_design_v8](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_upgrade2018_design_v8) as [101X_upgrade2018_design_v7](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_upgrade2018_design_v7) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/101X_upgrade2018_design_v8/101X_upgrade2018_design_v7):
      * CSC Chamber Time Corrections
      * L1Menu_Collisions2018_v0_0_1
      * GEM Geometry
      * PF Correction (ECAL)
      * EcalPFRecHitThresholds
      * PFCalibration (jet met)
      * Hcal QIEData, SiPMParam, Gains, Pedestal, Widths (effective and not)

   * **PhaseI 2018 realistic scenario** : [101X_upgrade2018_realistic_v7](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_upgrade2018_realistic_v7) as [101X_upgrade2018_realistic_v6](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_upgrade2018_realistic_v6) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/101X_upgrade2018_realistic_v7/101X_upgrade2018_realistic_v6):
      * CSC Chamber Time Corrections
      * L1Menu_Collisions2018_v0_0_1
      * GEM Geometry
      * PF Correction (ECAL)
      * EcalPFRecHitThresholds
      * PFCalibration (jet met)
      * Hcal QIEData, SiPMParam, Gains, Pedestal, Widths (effective and not)

## 2017_MC

   * **PhaseI 2017 cosmics peak scenario** : [101X_mc2017cosmics_realistic_peak_v7](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_mc2017cosmics_realistic_peak_v7) as [101X_mc2017cosmics_realistic_peak_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_mc2017cosmics_realistic_peak_v5) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/101X_mc2017cosmics_realistic_peak_v7/101X_mc2017cosmics_realistic_peak_v5):
      * PF Calibration (ecal, jetmet)
      * EcalPFRecHitThresholds

   * **PhaseI 2017 cosmics scenario** : [101X_mc2017cosmics_realistic_deco_v7](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_mc2017cosmics_realistic_deco_v7) as [101X_mc2017cosmics_realistic_deco_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_mc2017cosmics_realistic_deco_v5) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/101X_mc2017cosmics_realistic_deco_v7/101X_mc2017cosmics_realistic_deco_v5):
      * PF Calibration (ecal, jetmet)
      * EcalPFRecHitThresholds

   * **PhaseI 2017 design scenario** : [101X_mc2017_design_IdealBS_v7](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_mc2017_design_IdealBS_v7) as [101X_mc2017_design_IdealBS_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_mc2017_design_IdealBS_v5) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/101X_mc2017_design_IdealBS_v7/101X_mc2017_design_IdealBS_v5):
      * PF Calibration (ecal, jetmet)
      * EcalPFRecHitThresholds

   * **PhaseI 2017 realistic scenario** : [101X_mc2017_realistic_v7](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_mc2017_realistic_v7) as [101X_mc2017_realistic_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/101X_mc2017_realistic_v5) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/101X_mc2017_realistic_v7/101X_mc2017_realistic_v5):
      * PF Calibration (ecal, jetmet)
      * EcalPFRecHitThresholds

### CODE REVIEW

**Comment by lpernie** [comment]
please test

**Comment by lpernie** [comment]
please test

**Comment by lpernie** [comment]
please test

**Comment by arunhep** [comment]
the error seems unrelated to this PR.

```
%MSG
----- Begin Fatal Exception 05-Apr-2018 21:43:05 CEST-----------------------
An exception of category 'fastsim::ParticleManager' occurred while
   [0] Processing  Event run: 1 lumi: 1 event: 57 stream: 0
   [1] Running path 'simulation_step'
   [2] Calling method for module FastSimProducer/'fastSimProducer'
Exception Message:
unknown pdg id: 9010221
```
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-22833/27317/addOnTests/fastsim1/cmsDriver.py_TTbar_13TeV_TuneCUETP8M1_cfi_--conditions_auto:run2_mc_l1stage1_--fast__-n_100_--eventcontent_AODSIM,DQM_--relval_100000,1000_-s_GEN,SIM,.log

@lpernie anyways the GT corresponding to this key : run2_mc_l1stage1 is frozen and should not be changed unless explicitly required.

**Comment by lpernie** [comment]
The error come from the workflow:
cmsDriver.py TTbar_13TeV_TuneCUETP8M1_cfi --conditions 93X_mcRun2_asymptotic_v6 --fast  -n 100 --eventcontent AODSIM,DQM --relval 100000,1000 -s GEN,SIM,RECOBEFMIX,DIGI:pdigi_valid,L1,DIGI2RAW,L1Reco,RECO,EI,VALIDATION  --customise=HLTrigger/Configuration/CustomConfigs.L1THLT --datatier GEN-SIM-DIGI-RECO,DQMIO --beamspot NominalCollision2015 --era Run2_25ns

That it seems to cause:
----- Begin Fatal Exception 05-Apr-2018 21:43:05 CEST-----------------------
An exception of category 'fastsim::ParticleManager' occurred while
   [0] Processing  Event run: 1 lumi: 1 event: 57 stream: 0
   [1] Running path 'simulation_step'
   [2] Calling method for module FastSimProducer/'fastSimProducer'
Exception Message:
unknown pdg id: 9010221

I tried locally, and it works fine to me.

**Comment by lpernie** [comment]
please test

**Comment by lpernie** [comment]
@makortel @arunhep thanks (I did not read your comemnts initially)
(I will then use use old run2_mc_l1stage1 GT and re-trigger test)

**Comment by lpernie** [comment]
please test

**Comment by fabiocos** [comment]
@arunhep @lpernie anything keeping this PR on hold as the corresponding 101X backport is signed?

**Comment by arunhep** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
