### PR TITLE
Remove HLT process name out from L1CaloTrigger

### PR DESCRIPTION
**Pull request by srimanob**
#### PR description:
Currently, L1 step can't run if process name is not `HLT`.  Following code check by @Martin-Grunewald the process name is hardcode in `L1Trigger/L1CaloTrigger/python/`. This PR is to remove them out as the L1 step should not depend on HLT process (name). However, this will need confirmation from L1T expert.

Note that, it is unclear to me if `l1EGammaCrystalsProducer_cfi.py` is still in used.

(*)
https://docs.google.com/document/d/1DU5MzzIeyGyXYbzTtfreCnsZ9FAmbI6_daFy0vklTos/edit#bookmark=id.qcivq83cr9gj

#### PR validation:
Test with wf `39434.75 `. With the following modified cmsDriver of step2, job is running fine.
`cmsDriver.py step2  -s DIGI:pdigi_valid,L1TrackTrigger,L1,DIGI2RAW --conditions auto:phase2_realistic_T21 --datatier GEN-SIM-DIGI-RAW -n 10 --eventcontent FEVTDEBUGHLT --geometry Extended2026D88 --era Phase2C17I13M9 --io DigiTrigger_HLT75e33_2026D88.io --python DigiTrigger_HLT75e33_2026D88_noHLT.py -n 50 --no_exec --filein  file:step1.root  --fileout file:step2_noHLT.root  --nThreads 8`

#### if this PR is a backport please specify the original PR and why you need to backport that PR:
No need of backport.

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
Thanks @srimanob

**Comment by cecilecaillol** [comment]
+l1

**Comment by srimanob** [comment]
Hi @cecilecaillol 

Is l1EGammaCrystalsProducer_cfi.py still in use?

Thx.

**Comment by srimanob** [comment]
Hi @cecilecaillol 

I see from the link you point to is on `L1EGammaCrystalsEmulatorProducer_cfi`, but not `l1EGammaCrystalsProducer_cfi`.

**Comment by cecilecaillol** [comment]
@srimanob l1EGammaCrystalsProducer_cfi is not used anymore, we always take the emulated version

**Comment by srimanob** [comment]
Thanks @cecilecaillol for confirmation. I then remove the obsolete/unused config to avoid confusion.

**Comment by cecilecaillol** [comment]
+l1

**Comment by qliphy** [comment]
+1

**Pull request merged**
