### PR TITLE
Backport of #11828: No more cmsStage etc. scripts

### PR DESCRIPTION
**Pull request by hroskes**
https://hypernews.cern.ch/HyperNews/CMS/get/tif-alignment/465.html
Also rebased on #11197 which would have generated a merge conflict

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by diguida** [comment]
please test
Comments in #11828 addressed: the conddb version here is kept.

**Comment by mmusich** [comment]
+1

**Comment by mmusich** [comment]
ping  @monttj @vadler

**Comment by ghellwig** [comment]
I see that this has not been approved, yet. However, this PR is critical for a working version of the tool in 74X because the cms* scripts will be no longer available from January on.

**Comment by mmusich** [comment]
@ghellwig it's still analysis pending. Let me ping again @monttj and @vadler

**Comment by ghellwig** [comment]
ok, thanks!

**Comment by hroskes** [comment]
I guess it's time to close this since 74X hasn't been updated since February?

**Comment by ghellwig** [comment]
@hroskes I agree, since one can use 80X for all our use cases, right?

**Pull request closed without merging**
