### PR TITLE
L1T phase-2 Update old PF emulators with E/gamma integration, and add new emulators

### PR DESCRIPTION
**Pull request by cecilecaillol**
Backport of #33605
#### PR description:

This PR:

    integrates the E/gamma emulation into the existing PF setup, from @cerminar. No changes are expected on PF side, and the performance of the new e/gamma should be broadly compatible with the old one
    adds the PF & E/gamma emulators based on HLS datafomats. These are provided in a separate file, L1Trigger/Phase2L1ParticleFlow/python/l1ctLayer1_cff.py producing a collections of PF & Puppi candidates called l1ctLayer1:PF and l1ctLayer1:Puppi and of e/gamma candidates l1ctLayer1EG.

#### PR validation:

Rebase from https://github.com/cms-l1t-offline/cmssw/pull/893

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Rebase from https://github.com/cms-l1t-offline/cmssw/pull/893

### CODE REVIEW

**Comment by cecilecaillol** [comment]
@rekovic I am trying to rebase first the commits from Giovanni and Gianluca about the egamma and PF emulators. Does this PR look ok? You can close it if not.

**Comment by cecilecaillol** [comment]
please test

**Comment by cecilecaillol** [comment]
> This will be difficult to review. Can you clarify few things:
> 
>     * Are all in master already?
> 
>     * Which are ones that we may need for the next MWGR?
> 
>     * How to validate changes ?
> 
> 
> Thanks.

@srimanob This contains changes for Phase-2 only, so it is not needed for next MWGR. 
The files are not in master, we are rebasing our branch to 11_3_X directly.
About the validation this was checked within our branch (code committed 1 month ago). I can also ask the relevant L1 expecrt to check. I dont know if you have other suggestions

**Comment by cecilecaillol** [comment]
@kpedro88 Ok, thanks, that makes sense, I will proceed like that.

**Comment by srimanob** [comment]
hold

**Comment by silviodonato** [comment]
kind reminder @cecilecaillol

**Comment by cecilecaillol** [comment]
@silviodonato The PR to 120X is in progress: https://github.com/cms-sw/cmssw/pull/33605. When it is done it will be backported to 11_3_x

**Pull request closed without merging**
