### PR TITLE
Adding FatJet trigger objects and filters for 

### PR DESCRIPTION
**Pull request by ATumasyan**
#### PR description:
Added new FatJet trigger Filters with ParticleNet BBTag
Some unnecessary collections and filters were removed to make filterBits more understandable.
In particular:

mksel(["hltAK8SingleCaloJet200"]), # 0 # kept

mksel(["hltAK8DoublePFJet250"]), # 1 # not needed as hltAK8PFJetsCorrected is stored

mksel(["hltAK8DoublePFJet270"]), # 2 # not needed as hltAK8PFJetsCorrected is stored

mksel(["hltAK8DoublePFJetSDModMass30"]), # 3 kept

mksel(["hltAK8DoublePFJetSDModMass50"]), # 4 kept

mksel(["hltAK8PFJetsCorrectedMatchedToCaloJets200"]), # 5 # no need as both "hltAK8PFJetsCorrected" and "hltAK8SingleCaloJet200" are stored

mksel(["hltSingleAK8PFJet220","hltSingleAK8PFJet230"]), # 6 # no need as both "hltAK8PFJetsCorrected" and "hltAK8SingleCaloJet200" (hence hltAK8PFJetsCorrectedMatchedToCaloJets200) are stored.

mksel(["hltAK8PFSoftDropJets220","hltAK8PFSoftDropJets230"]), # kept

mksel(["hltAK8SinglePFJets220SoftDropMass40","hltAK8SinglePFJets230SoftDropMass40"]), # the same as above, this is the only filter which uses the collection above, so removed

mksel(["hltAK8PFJets220SoftDropMass40"]), # could be reached with the filter PNet filters which are added

mksel(["hltAK8SinglePFJets220SoftDropMass40PNetBBTag0p06"]), # 11 # kept

mksel(["hltAK8SinglePFJets230SoftDropMass40PNetTauTauTag0p03"]), # worth to move to boosted Tau

#### PR validation:
Tested with CMSSW_13_1_0

### CODE REVIEW

**Comment by simonepigazzini** [comment]
please test

**Comment by simonepigazzini** [comment]
@mstamenk, @ATumasyan can you please clarify the overlap between this PR and the one we merged some weeks ago: https://github.com/cms-sw/cmssw/pull/41692 ?

**Comment by ATumasyan** [comment]
@simonepigazzini  I checked and found out, that with the previous modification the output did not contain all the filters and collections, which were added. The reason was the line:
sel = cms.string("type(85) && pt > 120 && coll('hltAK8PFJetsCorrected')")
which now modified to
sel = cms.string("type(85) && pt > 120")
Second point is, that some of the previously added lines (filters and collections) can be skipped (please see the description at the very top), making trigger_bits more understandable

**Comment by vlimant** [comment]
@mstamenk can you please confirm ; and then we need the adequate back port to 13.0 and 13.1 if you want this in prompt.
#41985 and #41974

**Comment by mstamenk** [comment]
Hi @ATumasyan , 

`mksel(["hltAK8SinglePFJets230SoftDropMass40PNetTauTauTag0p03"]), # worth to move to boosted Tau`

I only see it removed so far, is this expected? 

Regarding the rest, I think I agree with the updates.

**Comment by ATumasyan** [comment]
Hi @mstamenk 
Yes, I only removed it, but I think it was already included in boosted Tau:  id = cms.int32(1515)

**Comment by mstamenk** [comment]
But if I have 2 boosted taus, how do I know which one fired the trigger?

**Comment by ATumasyan** [comment]
@mstamenk as far as I understand "hltAK8SinglePFJets230SoftDropMass40PNetTauTauTag0p03" is looking for boosted pair of Taus. Not really sure that I understand the question correctly, but basically it should be with the trigger object matching.
And for that you need to store needed trigger object (or filter).
What I was saying, is that "hltAK8SinglePFJets230SoftDropMass40PNetTauTauTag0p03" filter was already stored in BoostedTau block. And if it worked there properly (I did not checked), then there is no need to add this filter once again in FatJet block.

**Comment by mstamenk** [comment]
Ah apologies, I should have checked and I missed that point. 

All good, thanks a lot for the update!

**Comment by simonepigazzini** [comment]
+xpog

@ATumasyan, can you please open backports to 13_1_X and 13_0_X such that we can have this eventually deployed for prompt nano? Thank you.

**Comment by perrotta** [comment]
please test
(past ones has expired)

**Comment by perrotta** [comment]
+1

**Comment by ATumasyan** [comment]
@simonepigazzini 
>can you please open backports to 13_1_X and 13_0_X such that we can have this eventually deployed for prompt nano? 
I'm sorry, but I don't really understand what should I do, can you please instruct, I'm not good at git

**Comment by simonepigazzini** [comment]
Hi, you should make the same changes starting from one of the most recent 13_0_X and 13_1_X releases, and open to pull request selecting as branch not the master (as done for this one) but the 13_0_X and 13_1_X branches. See this one as an example https://github.com/cms-sw/cmssw/pull/41985.

**Pull request merged**
