### PR TITLE
add EventGenerationFailure exit code 

### PR DESCRIPTION
**Pull request by perrozzi**
to catch missing or exceeding LHE events

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by Dr15Jones** [comment]
Please also add an entry here
https://github.com/cms-sw/cmssw/blob/master/FWCore/Utilities/src/EDMException.cc#L43

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by perrozzi** [comment]
+1

**Comment by Dr15Jones** [comment]
The unit test failures are from the IB, not this pull request.

**Comment by Dr15Jones** [comment]
The comparison differences are only with the number of entries in the MessageLogger. That value is known to vary based on exact when other modules run with respect to the modules that the MessageLogger is explicitly waiting upon.

**Comment by perrozzi** [comment]
@bendavid fyi

**Comment by davidlange6** [comment]
merge

**Pull request merged**
