### PR TITLE
DQM: Fix empty lumis with per-lumi plots in DQMOneEDAnalyzer

### LINKED ISSUE #29605: Segmentation fault in HcalOfflineHarvesting in recent IB
We are seeing segmentation faults in 3 of the integration build workflows. The stack trace is
```
#4  &lt;signal handler called&gt;
#5  0x00002ab08a2ea5b8 in hcaldqm::DigiRunSummary::endLuminosityBlock(dqm::implementation::IBooker&amp, dqm::implementation::IGetter&amp, edm::LuminosityBlock const&amp, edm::EventSetup const&amp) () from /cvmfs/cms-ib.cern.ch/nweek-02626/slc7_amd64_gcc820/cms/cmssw-patch/CMSSW_11_1_X_2020-04-30-1100/lib/slc7_amd64_gcc820/libDQMHcalTasks.so
#6  0x00002ab08a22d7d8 in HcalOfflineHarvesting::_dqmEndLuminosityBlock(dqm::implementation::IBooker&amp, dqm::implementation::IGetter&amp, edm::LuminosityBlock const&amp, edm::EventSetup const&amp) () from /cvmfs/cms-ib.cern.ch/nweek-02626/slc7_amd64_gcc820/cms/cmssw-patch/CMSSW_11_1_X_2020-04-30-1100/lib/slc7_amd64_gcc820/pluginDQMHcalTasksAuto.so
#7  0x00002ab08a1fa0ca in DQMEDHarvester::endLuminosityBlockProduce(edm::LuminosityBlock&amp, edm::EventSetup const&amp) () from /cvmfs/cms-ib.cern.ch/nweek-02626/slc7_amd64_gcc820/cms/cmssw-patch/CMSSW_11_1_X_2020-04-30-1100/lib/slc7_amd64_gcc820/pluginDQMHcalTasksAuto.so
```

The likely culprits are either #29544 or #29586. The former changed code in that same package while the latter could be causing a module that was not being run before to now be run.

### PR DESCRIPTION
**Pull request by schneiml**
#### PR description:

As reported in #29605, it can happen that a `DQMOneEDAnalyzer` does not
produce its per lumi MEs, because there were no events in the
Lumisection and it only calls `enterLumi` as needed per event.

To prevent this, we need to make sure that lumi ME are always created
for every ME, but we can't have lumi transitions in `DQMOneEDAnalyzer`, so
it needs to happen in a global callback. But there we can't safely use
`enterLumi`, since that would corrupt the module's local MEs.

The solution is to have a new method, `initLumi`, dedicated to
initializing global MEs, but not touching local MEs. This is actually a
nice thing in general, since now `initLumi`/`cleanupLumi` form a symmetrical
pair (create/destroy global MEs), as well as `enterLumi`/`leaveLumi` (update
local MEs). All of these are idempotent, as before.

There are a bunch of corner cases around booking: `initLumi` *must* be
called before `enterLumi`, but the global callback that triggers it
globally might (will) happen before booking has happened for the module.
So we also need to do it after booking. There is a race related to lumi
MEs if `globalBeginLumi` can happen *before* `beginRun` finishes for all
plugins. This should not happen for now, as I understand.

This should fix #29605.

The "empty lumis" unit test is quite ugly, since `EmptySource` does not really support empty lumisections.

#### PR validation:

4.28 passes in my local test. A new unit test tests empty lumisections.

### CODE REVIEW

**Comment by silviodonato** [comment]
please test workflow 4.28 134.807 136.757 1360.0 25210.0
Thanks @schneiml for providing a fix in time for 11_1_0_pre7

**Comment by silviodonato** [comment]
ping @cmsbuild

**Comment by silviodonato** [comment]
@cmsbuild please test workflow 4.28 134.807 136.757 1360.0 25210.0

**Comment by smuzaffar** [comment]
@silviodonato  tests were not started as the comment was not wrong. Please see http://cms-sw.github.io/cms-bot-cmssw-cmds.html for correct syntax. Basically you have to use `,` to separate the workflows.

**Comment by silviodonato** [comment]
> @silviodonato tests were not started as the comment was not wrong. Please see http://cms-sw.github.io/cms-bot-cmssw-cmds.html for correct syntax. Basically you have to use `,` to separate the workflows.

thanks!

**Comment by silviodonato** [comment]
merge

**Comment by silviodonato** [comment]
See https://github.com/cms-sw/cmssw/issues/29743

**Comment by jfernan2** [comment]
+1

**Pull request merged**
