### PR TITLE
Run3-hcx238 Tidy up Hcal related agorithms and corresonding test examples

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Tidy up 3 algorithms for defining geometry of hadron calorimeter and the test beam setups. Also update the test examples. Also add an extra method for converting areas in cm^2 to mm^2.

#### PR validation:

Tested with example configurations in Geometry/HcalAlgo/test/python

#### if this PR is a backport please specify the original PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by ianna** [comment]
+1

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/28376	2a46b88 
- changes in reco category packages are only in DataFormats/Math/interface/GeantUnits.h where a new simple method is added

**Comment by fabiocos** [comment]
+1

**Pull request merged**
