### PR TITLE
update FastSim recycling strings for 9_4_X

### PR DESCRIPTION
**Pull request by zhenhu**
Solve the 9_4_X IB failures reported in issue #25104

### CODE REVIEW

**Comment by prebello** [comment]
@zhenhu I was checking the 9_4_X FastSim strings. As a matter of padronization, maybe you want to change their "baseDataSetRelease" numbers to # 17 and # 18, to be coherent with master?  #15 and #16 are dedicated to 2018 FullSim premix strings in master, and could cause confusion.
https://github.com/cms-sw/cmssw/blob/master/Configuration/PyReleaseValidation/python/relval_steps.py

**Comment by zhenhu** [comment]
Hi @prebello , good point, but maybe it's better to change the master. 
I mean, swap #15 #16 with #17 #18 in the master.

**Comment by prebello** [comment]
yes @zhenhu, it could be. I will make a PR.

**Comment by fabiocos** [comment]
@zhenhu @prebello sorry I am not sure to follow your discussion: aren't these versions part of the existing dataset name already? And where are exactly these v17 and v18 present in master? I am unable to catch them...

Anyway, do you confirm this PR is ok as it is?

**Comment by prebello** [comment]
Hi @fabiocos 
the difference between master and 94X is from line 621 to 624 (FullSim and FastSim strings)
https://github.com/cms-sw/cmssw/blob/master/Configuration/PyReleaseValidation/python/relval_steps.py#L621

This PR is ok. I will change the numbers (swap FullSim and FastSim) in master instead (easiest procedure)

**Comment by fabiocos** [comment]
@prebello ah now I see what you mean, #15 is the position in the fragment list, sorry, I confused with the accidentally similar version in the dataset name

**Comment by fabiocos** [comment]
merge

@kpedro88 nothing really relevant for upgrade, in case please sign for reference

**Comment by kpedro88** [comment]
+upgrade

**Pull request merged**
