### PR TITLE
Avoid making three copies of a large PSet in TrackingMonitor

### PR DESCRIPTION
**Pull request by Dr15Jones**
TrackingMonitor and two of its helpers (TrackAnalyzer and
TrackBuildingAnalyzer) were making copies of the module's PSet.
This PSet was quite large and making three copies per Stream is
not good. Now the module caches the PSet ID and gets the PSet
from the Registry when needed and passes the PSet to the helpers
when they need it.

The helpers also had virtual functions even though no other classes
inherited from them. These were de-virtualized.

TrackAnalyzer was not a unique name (a module with the same name
exists) so the class was moved to the dqm namespace.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
@slava77 I found this from your igprof report. These were major contributors to memory being held from calling the `edm::ParameterSet` copy constructor. Your report said each of the three classes was holding 0.5MB of configuration parameters.

**Comment by Dr15Jones** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
Last time, I didn't have a config to test (the input file I was using went away). This time I tested the failing configurations to prove the change works.

**Comment by Dr15Jones** [comment]
It appears the AddOn test failures were all caused by EOS file failures.

**Comment by Martin-Grunewald** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
