### PR TITLE
Run3-gex20 Take care of dd4hep flag to initiate GEM geometry in RECO+dd4hep context

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Take care of dd4hep flag to initiate GEM geometry in RECO+dd4hep context

#### PR validation:

Tested using step2 example in SimG4Core/Configuration/test

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
+1

**Comment by ianna** [comment]
@kpedro88 - please, review. This is blocking a RECO step with DD4hep. Thanks

**Comment by ianna** [comment]
@silviodonato, @dpiparo, @qliphy - would it be possible to integrate it for 11 am IB? Thanks.

**Comment by silviodonato** [comment]
merge
@kpedro88 @bsunanda @ianna 
should we propagate this change to all `gemGeometry_cfi`?
https://cmssdt.cern.ch/lxr/search?%21v=CMSSW_11_2_X_2020-10-14-1100&_filestring=&_string=gemGeometry_cfi

**Comment by ianna** [comment]
> merge
> @kpedro88 @bsunanda @ianna
> should we propagate this change to all `gemGeometry_cfi`?
> https://cmssdt.cern.ch/lxr/search?%21v=CMSSW_11_2_X_2020-10-14-1100&_filestring=&_string=gemGeometry_cfi

@silviodonato - yes, all sub detector geometry and numbering builders should define a dd4hep Era.

**Comment by kpedro88** [comment]
+upgrade
@ianna in general, please do not expect every PR to be reviewed with less than 24 hour turnaround

**Comment by cvuosalo** [comment]
@bsunanda Is the file `Configuration/Geometry/GeometryDD4hepExtended2021Reco_cff.py` missing from this PR? I ran step 2 with this PR, and it failed with the original error. I needed to change `GeometryDD4hepExtended2021Reco_cff.py` to allow step 2 to prevent the error with the GEM ES module.

**Comment by bsunanda** [comment]
Please use GeometryExtended2021Reco_cff.py which is the same for DDD and DD4Hep
________________________________

**Pull request merged**
