### PR TITLE
Phase2-sim31 Add the changes needed for GeantV

### PR DESCRIPTION
**Pull request by bsunanda**
The CaloSteppingAction is now equipped with corresponding calls for Geant4 and GeantV

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by fabiocos** [comment]
please test

**Comment by civanch** [comment]
@bsunanda , why we use ifdef inside this class? I do not think we need this stepping action class for normal Geant4 run.

**Comment by civanch** [comment]
@bsunanda, do we need this PR anymore?

**Comment by bsunanda** [comment]
@civanch No - we took totally different solution. I am closing this

**Comment by bsunanda** [comment]
This PR is not needed any more. A different solution is taken

**Pull request closed without merging**
