### PR TITLE
Add low pT electron payloads to Run 2 data/MC and Run 3 MC GTs [10_6_X]

### PR DESCRIPTION
**Pull request by christopheralanwest**
#### PR description:

This PR is a backport of PR #32421; see the description of that PR for details. The GT diffs in this PR are identical to the corresponding PR to master.

The GT diffs are as follows:

**Run 1 design**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_mcRun1_design_v3/106X_mcRun1_design_v4

**Run 1 realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_mcRun1_realistic_v3/106X_mcRun1_realistic_v4

**Run 1 heavy ion**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_mcRun1_HeavyIon_v3/106X_mcRun1_HeavyIon_v4

**Run 1 proton-heavy ion**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_mcRun1_pA_v3/106X_mcRun1_pA_v4

**Run 2 startup**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_mcRun2_startup_v4/106X_mcRun2_startup_v5

**Run 2 (L1 trigger stage 1)**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_mcRun2_asymptotic_l1stage1_v4/106X_mcRun2_asymptotic_l1stage1_v5

**2016 design**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_mcRun2_design_v7/106X_mcRun2_design_v8

**2016 realistic pre-VFP era**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_mcRun2_asymptotic_preVFP_v9/106X_mcRun2_asymptotic_preVFP_v10

**2016 realistic post-VFP era**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_mcRun2_asymptotic_v15/106X_mcRun2_asymptotic_v16

**2016 cosmics (asymptotic conditions)**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_mcRun2cosmics_asymptotic_deco_v2/106X_mcRun2cosmics_asymptotic_deco_v3

**Run 2 heavy ion**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_mcRun2_HeavyIon_v4/106X_mcRun2_HeavyIon_v5

**Run 2 proton-lead**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_mcRun2_pA_v5/106X_mcRun2_pA_v6

**Offline data**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_dataRun2_v32/106X_dataRun2_v33

**Offline data relval**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_dataRun2_relval_v30/106X_dataRun2_relval_v31

**Prompt-like data (HEM15/15 failure)**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_dataRun2_PromptLike_HEfail_v13/106X_dataRun2_PromptLike_HEfail_v14

**Prompt-like data**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_dataRun2_PromptLike_v14/106X_dataRun2_PromptLike_v15

**Prompt-like HI data**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_dataRun2_PromptLike_HI_v14/106X_dataRun2_PromptLike_HI_v15

**2017 design**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_mc2017_design_IdealBS_v5/106X_mc2017_design_IdealBS_v6

**2017 realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_mc2017_realistic_v8/106X_mc2017_realistic_v9

**2017 realistic cosmics (tracker deco mode)**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_mc2017cosmics_realistic_deco_v3/106X_mc2017cosmics_realistic_deco_v4

**2017 realistic cosmics (tracker peak mode)**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_mc2017cosmics_realistic_peak_v3/106X_mc2017cosmics_realistic_peak_v4

**2018 design**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_upgrade2018_design_v6/106X_upgrade2018_design_v8

**2018 realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_upgrade2018_realistic_v15/106X_upgrade2018_realistic_v16

**2018 heavy ion**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_upgrade2018_realistic_HI_v6/106X_upgrade2018_realistic_HI_v7

**2018 realistic (HEM15/16 failure)**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_upgrade2018_realistic_HEfail_v15/106X_upgrade2018_realistic_HEfail_v16

**2018 cosmics (tracker deco mode)**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_upgrade2018cosmics_realistic_deco_v12/106X_upgrade2018cosmics_realistic_deco_v13

**2018 cosmics (tracker peak mode)**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_upgrade2018cosmics_realistic_peak_v12/106X_upgrade2018cosmics_realistic_peak_v13

**2021 design**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_upgrade2021_design_v5/106X_upgrade2021_design_v6

**2021 realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_upgrade2021_realistic_v11/106X_upgrade2021_realistic_v12

**2021 cosmics**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_upgrade2021cosmics_realistic_deco_v4/106X_upgrade2021cosmics_realistic_deco_v5

**2023 realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_upgrade2023_realistic_v5/106X_upgrade2023_realistic_v6

#### PR validation:

See the description of the original PR #32421 for details. In addition, a technical test was performed:

`runTheMatrix.py -l limited,1325.516,7.22,136.8642,10424.0,7.21,11224.0,11024.2,7.4,12024.0,7.23,159.0,12834.0,1325.518,136.88811 --ibeos`

This technical test was done without the PR that consumes these conditions, however, as that PR is not yet available.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

This PR is a backport of PR #32421. It is needed for an eventual re-miniAOD that includes low pT electrons.

### CODE REVIEW

**Comment by christopheralanwest** [comment]
test parameters
- workflow = 1325.516,7.22,136.8642,10424.0,7.21,11224.0,11024.2,7.4,12024.0,7.23,159.0,12834.0,1325.518,136.88811

**Comment by christopheralanwest** [comment]
please test

**Comment by christopheralanwest** [comment]
please test

I have no problem running the failed DAS query so the problem seems transient.

**Comment by christopheralanwest** [comment]
+1

- backport consistent with the PR to master
- no changes observed, as expected because backport PR that consumes the new labeled records introduced in this PR have not been made.
- for several workflows that failed due to DAS errors, I checked in local tests that the workflows run successfully: `runTheMatrix.py -l 136.789,136.827,136.841,136.852 --ibeos`

**Comment by silviodonato** [comment]
+1

**Pull request merged**
