### PR TITLE
Introduce DQM memory usage script

### PR DESCRIPTION
**Pull request by dmitrijus**
Due to *popular* demand, this adds dqmMemoryStats.py script.

This won't draw a chart or anything, just a simple text breakdown of
histograms in DQM.

Usage:

`dqmMemoryStats.py -x -i step3_inDQM.root` will output the memory usage
for that file. It will output: `Total bytes: 251.78 MiB`.

`--summary` Will also output a summary table will output biggest offenders.

```
dqmMemoryStats.py -x -i step3_inDQM.root --summary

************************* DQM level 2 folder breakdown *************************
* Size cutoff: 1.00 MiB                                                        *
********************************************************************************
31.92 MiB        TrackerHitsV/TrackerHit
12.91 MiB        Muons/RecoMuonV
12.81 MiB        Vertexing/PrimaryVertexV
11.40 MiB        HLT/JME
...
```

Setting `-r/--ref <file>` flag will compare two files.

```
dqmMemoryStats.py -x -i step3_inDQM.root -r DQM_*_RECO.root --summary

************************* DQM level 1 folder breakdown *************************
********************************************************************************
-2721.23 KiB     EcalBarrel
-1364.68 KiB     EcalEndcap
-1255.52 KiB     HLT
...
```

Both `-i` and `-r` can be either DQM IO or DQM root files or any
combination of those. The script autodetects format.

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
