### PR TITLE
Monopole SKIM preparation for Run 3

### PR DESCRIPTION
**Pull request by ThOliveira23**
PR description:

Provide an update to the trigger paths to be employed in the MONOPOLE SKIM file for the Run 3. The additional inclusion of trigger paths associated with MET can be mentioned.
Additionally, the inclusion of the EXOMONOPOLE SKIM file to be executed in the MET and JetMET datasets for the Run 3.

PR validation: The PR was validated through the the basic test procedure available in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

FYI: @malbouis, @srimanob, @CarstenHensel

### CODE REVIEW

**Comment by tvami** [comment]
@cmsbuild  please test

**Comment by smuzaffar** [comment]
please test

**Comment by ThOliveira23** [comment]
Dear @cms-sw/pdmv-l2 could you kindly review and sign this PR. We would like to have it for the restart of the pp data taking starting period.

**Comment by tvami** [comment]
@cmsbuild please test

**Comment by srimanob** [comment]
+Upgrade

**Comment by youyingli** [comment]
Hi @cms-sw/pdmv-l2, could you please sign this PR?

**Comment by sunilUIET** [comment]
+pdmv

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
