### PR TITLE
Run4-hgx259 Make the cfg's up-to-date for HGCAL

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Make the cfg's up-to-date for HGCAL

#### PR validation:

Tested the cfg's in Validation/HGCalValidation/test

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by rovere** [comment]
Would it make sense, instead of copy&paste the same configuration file with a different `VXY` version, to use a generic skeleton with `VarParsing` to configure it properly at runtime?

**Comment by bsunanda** [comment]
@rovere I shall look into that issue later on. Would prefer this PR to be integrated so that others can use this.

**Comment by bsunanda** [comment]
@jfernan2, @fioriNTU Could you approve this?

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by jfernan2** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
