### PR TITLE
Phase2-hgx264x Correct a small issue in HGCalGeometry and update some test codes

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Correct a small issue in HGCalGeometry and update some test codes (also update some cfg's in view of changed scenarios)

#### PR validation:

Tested using some of the runTheMatrix workflows

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade

**Comment by qliphy** [comment]
+1

**Pull request merged**
