### PR TITLE
Add Detailed Cavern to 2019 Scenario

### PR DESCRIPTION
**Pull request by ianna**
* Add detailed cavern

Note: overlaps need to be addressed

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by kpedro88** [comment]
@ianna thanks - I have a branch in development for a 2019 workflow, I'll rebase it on top of this once it's merged. (It's also waiting on fixes from other PRs at the moment.)

**Comment by ianna** [comment]
+1

@kpedro88 - ok, I'll be fixing the overlaps later. It can wait for your branch.

**Comment by kpedro88** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
