### PR TITLE
Phase2-hgx360A Modify the V19 longitudinal structure of HGCal according to Meeting specification of 06/09/2024

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Modify the V19 longitudinal structure of HGCal according to Meeting specification of 06/09/2024

#### PR validation:

Dumped the geometry for viewing with fireworks

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
+geometry

**Comment by bsunanda** [comment]
@srimanob Please approve this PR

**Comment by srimanob** [comment]
+Upgrade

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
