### PR TITLE
Add data-vs-emulator plots for L1T shower DQM

### PR DESCRIPTION
**Pull request by zuoxunwu**
#### PR description:

This PR adds 2D summary plots for data vs emulator comparison on L1T shower objects to the online DQM monitor and monitor client modules. There are 2 summary plots for each of the ALCT showers, CLCT showers, LCT combined showers, and EMTF showers. The plot setting follows the CSC TP plots in [PR#36226](https://github.com/cms-sw/cmssw/pull/36226).

At the moment shower objects are not implemented in CSC or EMTF firmwares. Emulation is used in the place of data in this PR and the setting will be updated to data once showers are available.

#### PR validation:

This PR is tested with 10k events in a Higgs to LLP to 4b sample, plot examples are available at [link](https://xzuo.web.cern.ch/ShowerDQM/data_vs_emul/) 

The PR passed local unit tests and matrix tests. The standard code format is applied.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A.

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
@zuoxunwu the added plots apper empty in all tested workflows, is this expected? Specially L1TEMU / L1TdeStage2EMTF / Shower
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_3_X_2021-12-07-1100+879a18/47317/dqm-histo-comparison-summary.html

**Comment by zuoxunwu** [comment]
@jfernan2 Thanks for checking. Yes, it is expected. 
It looks the tests with Run 3 setting are all TTbar. The shower trigger asks for a high multiplicity of CSC LCTs in the same chamber, which should not be present in TTbar events. 
And luckily we actually have a few entries in L1TEMU/L1TdeCSCTPGShower in test [11634.911](https://cmsweb.cern.ch/dqm/dev/start?runnr=1;dataset%3D/RelVal_wf11634_911_pr/CMSSW_12_3_X-PRcmssw_36396-21074/DQMIO;sampletype%3Doffline_relval;workspace%3DEverything;). It looks like these entries come from detector noise (not sure how that is simulated in this test sample).
So things are working as expected:)

**Comment by jfernan2** [comment]
+1

**Comment by qliphy** [comment]
+1

**Comment by VinInn** [comment]
does not compile with #35627

**Pull request merged**
