### PR TITLE
[12_4_X] Don't save flat nano in the ECAL ALCANANO wf

### PR DESCRIPTION
**Pull request by tvami**
#### PR description:

See https://github.com/cms-sw/cmssw/pull/38510

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport of https://github.com/cms-sw/cmssw/pull/38510

### CODE REVIEW

**Comment by tvami** [comment]
test parameters:
  - workflows = 139.005

**Comment by tvami** [comment]
type ecal

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
backport of https://github.com/cms-sw/cmssw/pull/38510

**Comment by tvami** [comment]
urgent
 * should go into the release built tomorrow

**Comment by francescobrivio** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
