### PR TITLE
[DD4hep] Enable DD4hep workflows to use DD4hep for the magnetic field

### PR DESCRIPTION
**Pull request by cvuosalo**
Up to now, DD4hep workflows were using old DD for the magnetic field. The DD4hep magnetic field producer was already in place, but it wasn't called. This PR uses the dd4hep modifier to call the DD4hep producer for DD4hep workflows, and the old DD producer for old DD workflows.

Creating a new DD4hep detector for the magnetic field with the same name as the one used for the CMS detector caused a conflict, so a new, unique name has been provided for the magnetic field `cms::DDDetector`. 

#### PR validation:

Debug output from the old DD 11634.0 and DD4hep 11634.911 workflows were checked to see that either old DD or DD4hep was being used as appropriate.

No backport is needed.

### CODE REVIEW

**Comment by cvuosalo** [comment]
@ianna Please review and let me know your comments.

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by namapane** [comment]
@cvuosalo my understanding was that the modifier would have been put in Configuration/StandardSequences/python/MagneticField_cff.py , not in MagneticField/Engine/python/volumeBasedMagneticFieldFromDB_cfi.py ... 
If you prefer it this way I think we should also remove ​MagneticField/​Engine/​python/​volumeBasedMagneticFieldFromDB_dd4hep_cfi.py and adapt the IB tests that are run with https://cmssdt.cern.ch/lxr/source/MagneticField/Engine/test/runTest.sh.

**Comment by cvuosalo** [comment]
Comparison differences in DD4hep workflow 11634.911 are expected since the magnetic field was changed from old DD to DD4hep. The differences are just statistical fluctuations caused by a change in the simulation histories.

**Comment by cvuosalo** [comment]
@namapane I followed examples of using the dd4hep modifier in the way I implemented this PR. I couldn't figure out a way to put the fix in `MagneticField_cff.py`. I can remove `volumeBasedMagneticFieldFromDB_dd4hep_cfi.py` if there is no other use for it.

**Comment by cvuosalo** [comment]
@fabiocos Could you please review this PR and let me know if I am using the dd4hep modifier appropriately?
Thanks.

**Comment by namapane** [comment]
> 
> 
> @namapane I followed examples of using the dd4hep modifier in the way I implemented this PR. I couldn't figure out a way to put the fix in `MagneticField_cff.py`. I can remove `volumeBasedMagneticFieldFromDB_dd4hep_cfi.py` if there is no other use for it.

Can't the exact same modifier be simply put at the end of MagneticField_cff.py? I have no experience with these modifiers so maybe there's something preventing this to work.

Otherwise, volumeBasedMagneticFieldFromDB_dd4hep_cfi.py becomes redundant, but considers that, as I mentioned, 
it is used for IB tests in https://cmssdt.cern.ch/lxr/source/MagneticField/Engine/test/runTest.sh, so that should be adapted to force using the dd4hep version when needed. 

If that's too complicated we can ignore the problem for a while  given that at some point the DDD version will be dropped anyhow (right?)

**Comment by ianna** [comment]
@cvuosalo - I agree with @namapane the modifier should go in MagneticField_cff.

**Comment by fabiocos** [comment]
@cvuosalo the usual workflows built with ```cmsDriver.py``` are ultimately using ```MagneticField_cff.py``` to define the configuration:

https://github.com/cms-sw/cmssw/blob/master/Configuration/Applications/python/ConfigBuilder.py#L1053

In this case the top level configuration where it seems most appropriate to add the ```dd4hep``` customisation is this, I tend to agree with @namapane and @ianna . It looks the highest level place where you do not risk to miss anything else to me.

**Comment by jpata** [comment]
Hello, FWIW just to add the reco 2 cents - I would tend to agree with the comments above.

`_VolumeBasedMagneticFieldESProducer_dd4hep` added here seems redundant compared to what's in `MagneticField/Engine/python/volumeBasedMagneticFieldFromDB_dd4hep_cfi.py`. Why not do something like the following in `MagneticField_cff.py`?

```python
from MagneticField.Engine.volumeBasedMagneticFieldFromDB_dd4hep_cfi import VolumeBasedMagneticFieldESProducer as _VolumeBasedMagneticFieldESProducer_dd4hep
from Configuration.ProcessModifiers.dd4hep_cff import dd4hep
dd4hep.toReplaceWith(VolumeBasedMagneticFieldESProducer, _VolumeBasedMagneticFieldESProducer_dd4hep)
```

Apologies if I miss something basic here.

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
@jpata Thanks for the suggestion. I made the change you mentioned.

**Comment by jpata** [comment]
Thx @cvuosalo 

@namapane @ianna just to confirm, does this look OK for you?
https://github.com/cms-sw/cmssw/pull/33076/commits/083fc79b37696e362556e0bd06e95b4a14fa470f

**Comment by namapane** [comment]
Yes it looks fine to me. Thanks @cvuosalo for taking care of this!

**Comment by jpata** [comment]
+reconstruction
- switches the dd4hep magnetic field provider with the corresponding modifier
- code changes look fine (very limited reco changes)
- no reco output changes as expected

**Comment by qliphy** [comment]
+operations

**Comment by qliphy** [comment]
+1

**Pull request merged**
