### PR TITLE
Enable EMTF regional shower DQM with unpacked inputs (backport)

### PR DESCRIPTION
**Pull request by zuoxunwu**
#### PR description:
Backport of [PR#37634](https://github.com/cms-sw/cmssw/pull/37634) and [PR#37544](https://github.com/cms-sw/cmssw/pull/37544) to enable EMTF shower DQM modules with unpacked info as inputs.

#### PR validation:

Passed local unit tests and matrix tests 

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

This is a backport of [PR#37634](https://github.com/cms-sw/cmssw/pull/37634) and [PR#37544](https://github.com/cms-sw/cmssw/pull/37544) to have the DQM plots for the incoming cosmic data-taking.

EMTF operation contact @eyigitba

### CODE REVIEW

**Comment by emanueleusai** [comment]
please test

**Comment by emanueleusai** [comment]
testing at P5

**Comment by emanueleusai** [comment]
+1

**Comment by perrotta** [comment]
backport of #37544
(as well as #37634)

**Comment by perrotta** [comment]
+1
- Verbatim backport of two PRs merged in master since several weeks already

**Pull request merged**
