### PR TITLE
Change the track associator in HI Track Validation

### PR DESCRIPTION
**Pull request by kkrajczar**
This PR is a workaround to the "RuntimeError: An entry in sequence tracksValidationFS has no label" error observed in recent IBs for HI Validation. That problem seems to be caused by PR #7175 (main authors are @Dr15Jones and @davidlange6). Please see other comments in that PR, PR #7175 .

### CODE REVIEW

**Comment by davidlange6** [comment]
-1 - do not change parameters of existing modules - the clone is needed

**Comment by degano** [comment]
@cmsbuild please test

**Comment by kkrajczar** [comment]
Hi David,

It turned out that the parameter already had the value it was changed to ('reco'), so I removed the superfluous parameter change. Now, the existing module is used as is.

**Comment by kkrajczar** [comment]
Dear all,

The RelVal failure does not seem to have anything to do with this PR, the error message points to a file access/RelVal setup issue: "RootInputFileSequence::readOneRandom(): no input files specified for secondary input source.". The other tests are all ok as can be seen at https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-7404/2182/runTheMatrix-results/runall-report-step123-.log.

What is to be done in this case? Can we ask for a re-test without the (independently) broken RelVal workflow?

**Comment by degano** [comment]
@cmsbuild please test

**Comment by deguio** [comment]
+1

**Pull request merged**
