### PR TITLE
DeepCore model 2.2.1

### PR DESCRIPTION
**Pull request by bouchamaouihichem**
#### PR description:

This PR updates the model used when ```--procModifiers seedingDeepCore``` is used in CMSSW workflows. The DeepCoreSeedGenerator.cc file is updated with the new model path as well as new prediction thresholds. This PR depends on [another PR](https://github.com/cms-data/RecoTracker-TkSeedGenerator/pull/3), which will add the DeepCore 2.2.1 model.

Relevant Links:

- [Track POG Update 09/11/2023](https://indico.cern.ch/event/1315747/contributions/5553878/attachments/2712109/4709601/DeepCore_TrackPOG_23_0911.pdf)
- [DeepCore 2 Website](https://hboucham.web.cern.ch) (includes testing workflows and documentation)
- [DeepCore 2 repository](https://github.com/bouchamaouihichem/DeepCore)

#### PR validation:

Workflows 11923.17/0 and 11834.17/0. More details provided in the slides of [Track POG Update 09/11/2023](https://indico.cern.ch/event/1315747/contributions/5553878/attachments/2712109/4709601/DeepCore_TrackPOG_23_0911.pdf) and all the plots are in [DeepCore 2 Website](https://hboucham.web.cern.ch).

### CODE REVIEW

**Comment by slava77** [comment]
@bouchamaouihichem 
it looks like you have used a wrong target branch for this PR. Your branch seems to derive from CMSSW_13_0_X

Current development release is 13_3_X. Please use e.g. CMSSW_13_3_0_pre3 and resubmit.
Considering that your changes affect only a specific tracking package file, even an older pre-release should still work.
It should be possible to follow `git cms-rebase-topic` as described in http://cms-sw.github.io/tutorial-resolve-conflicts.html

For the future, in any case, before pushing "Create pull request" check that the differences contain only what you want to propose.

**Comment by mmusich** [comment]
I isolated the only relevant commit at https://github.com/cms-sw/cmssw/pull/38169 (just for testing)

**Comment by slava77** [comment]
@bouchamaouihichem 
please close this PR, it is superseded by #42851

**Comment by mmusich** [comment]
@cmsbuild please close

**Pull request closed without merging**
