### PR TITLE
[CLANG] remove unused variables

### PR DESCRIPTION
**Pull request by smuzaffar**
https://github.com/cms-sw/cmssw/pull/41528 clean also introduced a unused variable warning, this PR fixes it

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by emanueleusai** [comment]
+1

**Comment by smuzaffar** [comment]
@rappoccio , can we get this in for next IB? This should fix the compilation warnings we see in 13.2.X

**Pull request merged**
