### PR TITLE
Phase2-hgx164 Enable saving Digi results of HFNose and instead of PR #24913

### PR DESCRIPTION
**Pull request by bsunanda**
This is in place of PR #24848 and #24913 which are closed

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@andrius-k @kpedro88 @perrotta @iana @civanch Could you sign this PR which has to be remade because of issues in conflicts

**Comment by perrotta** [comment]
+1
- Faithfull backport of previous #24913, already signed by reco
- For that PR:
  - Workflow 26234.0 runs to completion without crashing (which is not the case in the baseline)
  - Other workflows and upgrade scenarios not touched by this PR
  - Jenkins tests pass

**Comment by kpedro88** [comment]
+upgrade

**Comment by bsunanda** [comment]
@ianna @civanch @fabiocos Could you sign and merge this PR?

**Comment by bsunanda** [comment]
@ianna @civanch @fabiocos  Ping again

**Comment by fabiocos** [comment]
+operations

the StandardSequences update is coherent with the PR target

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

@ianna @civanch you already signed the previous PR, please sign this as well for reference, I move anyway forward with the merge

**Comment by cvuosalo** [comment]
+geometry

**Pull request merged**
