### PR TITLE
remove gtEvmDigis from run2 configuration

### PR DESCRIPTION
**Pull request by davidlange6**
remove gtEvmDigis from run2 configuration as requested by L1 experts

### CODE REVIEW

**Comment by davidlange6** [comment]
@cmsbuild, please test

**Comment by davidlange6** [comment]
@cmsbuild, please test

**Comment by davidlange6** [comment]
i will bypass this so that things get into the IB for testing.  @slava77, let me know if you see any problem in your testing.

**Comment by slava77** [comment]
I'll check on a lower priority; visually the changes are as expected.

**Comment by slava77** [comment]
These changes didn't make it to 74X so far.
I suppose a separate PR is needed.

**Comment by slava77** [comment]
@davidlange6 
these changes are still not in 74X

[how to avoid this problem in the future ... same story as hcalnzs, apparently]

**Comment by slava77** [comment]
Another way is to have a strategy/policy  to  have PRs for the appropriate release range, before merging a PR from an old release (basically, never really rely on automated forward ports)

**Comment by davidlange6** [comment]
ok - so that is the current policy, but relies on humans that sometimes change their priority when fixing urgent issues..

**Pull request merged**
