### PR TITLE
[TF] Accept const graphs in session creation

### PR DESCRIPTION
**Pull request by riga**
#### PR description

This PR adds a small change to the TensorFlow interface that allows the `tensorflow::createSession` calls to accept pointers to *constant* `Graph` / `MetaGraph` objects. This allows making graph objects constant in global caches when running multi-threaded.

The change was suggested in [#32222  (comment)](https://github.com/cms-sw/cmssw/pull/32222/files#r529850491) and https://github.com/cms-sw/cmssw/pull/32128#issuecomment-726425146 and could benefit the ongoing integrations.

#### PR validation

The tests coming with the TF interface itself were not changed and still pass as changes are minimal and predictable.

@mialiu149 @makortel @vlimant

### CODE REVIEW

**Comment by makortel** [comment]
code-checks

**Comment by makortel** [comment]
Thanks @riga!

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by slava77** [comment]
it looks like the bot is asleep

**Comment by slava77** [comment]
code-checks

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@smuzaffar @mrodozov 
please take a look at the PR testing setup; something is locking this one up

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/32271	dc7ba4c
- technical

**Comment by santocch** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
