### PR TITLE
CondTools/SiPixel: apply necessary changes to work with python3

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

Fixed unit tests in `CondTools/SiPixel`, addressing https://github.com/cms-sw/cmssw/pull/31796#issuecomment-723684008
As done previously in https://github.com/cms-sw/cmssw/pull/31166
   * converted to `print` function
   * use `next` function
   * use `io.open`

#### PR validation:

The unit tests were run under a python 2 and a python 3 RelVal.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Not a backport, no backport needed.
cc: @tvami

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild please test for CMSSW_11_2_PY3_X

**Comment by mmusich** [comment]
@mrodozov FYI

**Comment by ggovi** [comment]
+1

**Comment by silviodonato** [comment]
please test
for the standard release (py2)

**Comment by silviodonato** [comment]
+1

**Pull request merged**
