### PR TITLE
Remove 2D pixel template B field warning for 0T

### PR DESCRIPTION
**Pull request by OzAmram**
This is a small PR to remove the UnexpectedMagneticField warning for the 2D pixel templates on 0T. The 2D templates are never used for 0T (see [here](https://github.com/cms-sw/cmssw/blob/master/RecoLocalTracker/SiPixelRecHits/src/PixelCPEClusterRepair.cc#L109-L112) ) so there is no need to print the warning. 

This addresses issue #31956. 

@mmusich @tvami @ferencek @tsusa

### CODE REVIEW

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by mmusich** [comment]
@cmsbuild, please abort

**Comment by mmusich** [comment]
test paramaters:
   * workflows = 11634.24, 11834.24

**Comment by mmusich** [comment]
@cmsbuild, please test

to actually test 0T (data and MC) workflows

**Comment by mmusich** [comment]
As expected the message about `UnexpectedMagneticFieldUsingNonIdealPixel2DTemplate` which is present in the[ IB logs]( https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc7_amd64_gcc900/CMSSW_12_0_X_2021-07-07-2300/pyRelValMatrixLogs/run/138.2_RunCosmics2020+RunCosmics2020+RECOCOSDEXPRUN3+ALCACOSDEXPRUN3+HARVESTDCEXPRUN3/step2_RunCosmics2020+RunCosmics2020+RECOCOSDEXPRUN3+ALCACOSDEXPRUN3+HARVESTDCEXPRUN3.log) is gone in [this PR logs](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-d4a994/16572/runTheMatrix-results/138.2_RunCosmics2020+RunCosmics2020+RECOCOSDEXPRUN3+ALCACOSDEXPRUN3+HARVESTDCEXPRUN3/step2_RunCosmics2020+RunCosmics2020+RECOCOSDEXPRUN3+ALCACOSDEXPRUN3+HARVESTDCEXPRUN3.log).

**Comment by tvami** [comment]
+alca

**Comment by qliphy** [comment]
+1

**Comment by tvami** [comment]
With Tanja we just realized that the goal of this PR has not been reached since the current data taking happens in 11_3_X , so all the CRUZET reco will have the message that we wanted to avoid. @OzAmram can you make a backport?

**Comment by OzAmram** [comment]
Ok I made the backport #34578

**Pull request merged**
