### PR TITLE
Add combined premixing workflow for FastSim

### PR DESCRIPTION
**Pull request by makortel**
This PR adds a combined premixing workflow for Fastsim (i.e. what #22956 did for Fullsim). As with #22956, the goal of the workflow is development, PR, and IB level testing of the full chain of changes affecting the premixing stage1. For simplicitly I left the MiniAOD step out because I would have had to duplicate `MINIAODMCUP15FS` for `--filein file:step2.root`, and I don't think it is strictly needed for the aforementioned goal (DQM histograms are enough).

Tested in 10_2_0, no changes expected in existing workflows.

@kpedro88 @mdhildreth

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test workflow 250402.1

**Comment by makortel** [comment]
@cmsbuild, please abort

Realized, after a more careful look of my test, that the current approach was too simple.

**Comment by makortel** [comment]
@cmsbuild, please test workflow 250402.1

Fixed the input files for the stage2 step similarly to FullSim in #22956 (i.e. in a straightforward, but ugly way).

**Comment by kpedro88** [comment]
+upgrade

**Comment by fabiocos** [comment]
@fabozzi @prebello could you please have a look and sign it in case?

**Comment by fabiocos** [comment]
+1

**Pull request merged**
