### PR TITLE
Run2-alca92 Change output command for IsoTrack AlCaReco jobs

### PR DESCRIPTION
**Pull request by bsunanda**
Two collections are added - information about L1 trigger information and prerechit collection for HBHE. This changes the o/p from 0.46 MB per stored event to 0.48 MB per event - an increase by 3.8%

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@arunhep @lpernie Please approve this PR

**Comment by arunhep** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
