### PR TITLE
HcalDQM: update hcal FED list for crate 3-FED readout, back port to 12_0

### PR DESCRIPTION
**Pull request by lwang046**
#### PR description:
Backport of PR #35617
Update the FED/Crate mapping list based on [https://cmshcal.docs.cern.ch/hcos/crateFedMap/](https://cmshcal.docs.cern.ch/hcos/crateFedMap/ )

#### PR validation:
tested under CMSSW_12_0_2_patch1 with `cmsRun DQM/Integration/python/clients/hcal_dqm_sourceclient-live_cfg.py` on recent data inputfile without errors

### CODE REVIEW

**Comment by jfernan2** [comment]
Hi @lwang046 
It seems your PR crashes at P5 with the hcalcalib client:
https://cmsweb.cern.ch/dqm/dqm-square/tmp/tmp/content_parser_playbackPARSER_run502028PARSER_job13.log
which is not tested by UnitTests
Can you please have a look?

**Comment by jfernan2** [comment]
The file is created on the fly at DQM playback Online machine to emulate live conditions, so it does not exist right now.
However I understand the crash may be repdroduce with any other recent file so I have copied this one for you on:
/afs/cern.ch/user/j/jfernan/public/forLong/run502031_ls0999_streamDQMCalibration_mrg-c2f12-23-01.dat
HTH

**Comment by perrotta** [comment]
backport of #35617

**Comment by perrotta** [comment]
+1
- Master version of this PR succesfully merged in CMSSW_12_1_X_2021-10-14-2300
- Identical to #35617 (a part a few comment lines in the code)

**Pull request merged**
