### PR TITLE
Clean offline DQM of Photon "smin" triggers and adding CSCCluster50_Photon20Unseeded

### PR DESCRIPTION
**Pull request by smdogra**
Hi, 
#### PR description:
As per the JIRA, 
https://its.cern.ch/jira/browse/CMSHLT-3081
Clean offline DQM of Photon "smin" triggers and adding the DQM for HLT_CSCcluster50_Photon20Unseeded

The following two files were changed to implement the proposed changes 
https://github.com/cms-sw/cmssw/blob/1e2c4980d73549aad8a2c4db1034bd15d2468e0b/DQMOffline/Trigger/python/PhotonMonitor_cff.py
https://github.com/cms-sw/cmssw/blob/1e2c4980d73549aad8a2c4db1034bd15d2468e0b/HLTriggerOffline/Exotica/python/analyses/hltExoticaDisplacedDiPhoton_cff.py

#### PR validation:
The PR is validated with  runTheMatrix.py  -l 12834.0 with no error.  Th

#### If this PR is a backport
Not intended  

Thank you

### CODE REVIEW

**Comment by tjavaid** [comment]
@cmsbuild  please test

**Comment by tjavaid** [comment]
please test

- re-triggrering for fresh results

**Comment by tjavaid** [comment]
+1

**Comment by antoniovilela** [comment]
+1

**Comment by mmusich** [comment]
@smdogra should this PR be backported to CMSSW_14_0_X ?

**Pull request merged**
