### PR TITLE
Backported PR #20613 (94X) to 92X

### PR DESCRIPTION
**Pull request by slehti**
Backported HLTTauValidation updates in PR #20613 (94X) to 92X

### CODE REVIEW

**Comment by mtosi** [comment]
@cmsbuild, please test

**Comment by dmitrijus** [comment]
If this is a backport, why does it have extra changes?

**Comment by slehti** [comment]
I did not cherry-pick due to several commits and merge conflicts in picking them. So I copied the files from CMSSW_9_4_0_pre2 to guarantee the 94 and 92 versions are the same. The development itself was originally done in 92x.

Extra changes I found:
HLTTauPostProcessor_cfi.py: variables renamed by removing _.

HLTTauDQMTagAndProbePlotter.cc:
< HLTTauDQMTagAndProbePlotter::~HLTTauDQMTagAndProbePlotter() {
< }
---
> HLTTauDQMTagAndProbePlotter::~HLTTauDQMTagAndProbePlotter() = default;

I have no strong opinion whether these should go or not go to 92x.

**Comment by dmitrijus** [comment]
If you copy files, you must coordinate that with @mtosi, because you are creating tons of future conflicts...

And, on a side note, If you don't have a strong opinion whether it should go into 92x, then it should not go into 92x.

**Comment by slehti** [comment]
Made a new PR (#20955) where I cherry picked the changes from 94X, closing this one.

**Pull request closed without merging**
