### PR TITLE
updating JECs and Tracker Alignment tag for HLT

### PR DESCRIPTION
**Pull request by mmusich**
# Summary of changes in Global Tags
## RunII simulation
- **RunII Ideal scenario** : [80X_mcRun2_design_v16](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_mcRun2_design_v16) as [80X_mcRun2_design_v15](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_mcRun2_design_v15) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/80X_mcRun2_design_v16/80X_mcRun2_design_v15): 
  - updated JEC to `Spring16_25ns_v3` [HN](https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2417.html)
- **RunII Asymptotic scenario** : [80X_mcRun2_asymptotic_v16](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_mcRun2_asymptotic_v16) as [80X_mcRun2_asymptotic_v15](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_mcRun2_asymptotic_v15) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/80X_mcRun2_asymptotic_v16/80X_mcRun2_asymptotic_v15): 
  - updated JEC to `Spring16_25ns_v3` [HN](https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2417.html)
## RunII data
- **RunII Offline processing** : [80X_dataRun2_v17](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_dataRun2_v17) as [80X_dataRun2_v16](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_dataRun2_v16) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/80X_dataRun2_v17/80X_dataRun2_v16): 
  - updated JEC to `Spring16_25ns_v3` [HN](https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2417.html) as in ICHEP2016B re-reco
- **RunII HLTHI processing** : [80X_dataRun2_HLTHI_frozen_v10](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_dataRun2_HLTHI_frozen_v10) as [80X_dataRun2_HLTHI_frozen_v9](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_dataRun2_HLTHI_frozen_v9) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/80X_dataRun2_HLTHI_frozen_v10/80X_dataRun2_HLTHI_frozen_v9): 
  - technical change of Tracker Alignment tag to allow enabling of `SiPixelAli` PCL worfklow
- **RunII HLT processing** : [80X_dataRun2_HLT_frozen_v13](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_dataRun2_HLT_frozen_v13) as [80X_dataRun2_HLT_frozen_v12](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_dataRun2_HLT_frozen_v12) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/80X_dataRun2_HLT_frozen_v13/80X_dataRun2_HLT_frozen_v12): 
  - technical change of Tracker Alignment tag to allow enabling of `SiPixelAli` PCL worfklow
- **RunII HLT relval processing** : [80X_dataRun2_HLT_relval_v12](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_dataRun2_HLT_relval_v12) as [80X_dataRun2_HLT_relval_v11](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_dataRun2_HLT_relval_v11) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/80X_dataRun2_HLT_relval_v12/80X_dataRun2_HLT_relval_v11): 
  - technical change of Tracker Alignment tag to allow enabling of `SiPixelAli` PCL worfklow
- **RunII Offline relval processing** : [80X_dataRun2_relval_v15](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_dataRun2_relval_v15) as [80X_dataRun2_relval_v14](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_dataRun2_relval_v14) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/80X_dataRun2_relval_v15/80X_dataRun2_relval_v14): 
  - updated JEC to `Spring16_25ns_v3` [HN](https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2417.html) ) as in ICHEP2016B re-reco
# 

Side note: the change of snapshot will allow to "see" in the data (HLT and RECO) Global Tags the new IOV for 2016B as in the ICHEP Re-Reco @fabozzi

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
nice...

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
```
----- Begin Fatal Exception 13-Jul-2016 18:35:26 CEST-----------------------
An exception of category 'FallbackFileOpenError' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing input source of type PoolSource
   [2] Calling RootFileSequenceBase::initTheFile()
   [3] Calling StorageFactory::open()
   [4] Calling XrdFile::open()
Exception Message:
Failed to open the file 'root://xrootd-cms.infn.it//store/relval/CMSSW_8_0_0/RelValTTbar_13/GEN-SIM-RECO/80X_mcRun2_asymptotic_v4-v1/10000/1C687FB0-7BD9-E511-AFED-0CC47A78A4BA.root'
   Additional Info:
      [a] XrdCl::File::Open(name='root://eoscms.cern.ch//eos/cms/store/relval/CMSSW_8_0_0/RelValTTbar_13/GEN-SIM-RECO/80X_mcRun2_asymptotic_v4-v1/10000/1C687FB0-7BD9-E511-AFED-0CC47A78A4BA.root', flags=0x10, permissions=0660) => error '[ERROR] Server responded with an error: [3011] Unable to open file /eos/cms/store/relval/CMSSW_8_0_0/RelValTTbar_13/GEN-SIM-RECO/80X_mcRun2_asymptotic_v4-v1/10000/1C687FB0-7BD9-E511-AFED-0CC47A78A4BA.root; No such file or directory
' (errno=3011, code=400). No additional data servers were found.
      [b] Last URL tried: root://eoscms.cern.ch:1094//eos/cms/store/relval/CMSSW_8_0_0/RelValTTbar_13/GEN-SIM-RECO/80X_mcRun2_asymptotic_v4-v1/10000/1C687FB0-7BD9-E511-AFED-0CC47A78A4BA.root?tried=
      [c] Problematic data server: eoscms.cern.ch:1094
      [d] Disabled source: eoscms.cern.ch:1094
      [e] Input file root://eoscms.cern.ch//eos/cms/store/relval/CMSSW_8_0_0/RelValTTbar_13/GEN-SIM-RECO/80X_mcRun2_asymptotic_v4-v1/10000/1C687FB0-7BD9-E511-AFED-0CC47A78A4BA.root could not be opened.
Fallback Input file root://xrootd-cms.infn.it//store/relval/CMSSW_8_0_0/RelValTTbar_13/GEN-SIM-RECO/80X_mcRun2_asymptotic_v4-v1/10000/1C687FB0-7BD9-E511-AFED-0CC47A78A4BA.root also could not be opened.
Original exception info is above; fallback exception info is below.
      [f] XrdCl::File::Open(name='root://xrootd-cms.infn.it//store/relval/CMSSW_8_0_0/RelValTTbar_13/GEN-SIM-RECO/80X_mcRun2_asymptotic_v4-v1/10000/1C687FB0-7BD9-E511-AFED-0CC47A78A4BA.root', flags=0x10, permissions=0660) => error '[ERROR] Operation expired' (errno=0, code=206). No additional data servers were found.
      [g] Last URL tried: root://cms-xrd-global.cern.ch:1094//store/relval/CMSSW_8_0_0/RelValTTbar_13/GEN-SIM-RECO/80X_mcRun2_asymptotic_v4-v1/10000/1C687FB0-7BD9-E511-AFED-0CC47A78A4BA.root?tried=+1213cmsxrootd1.fnal.gov1213xrootd.unl.edu,+1213xrootd.ba.infn.it,
      [h] Problematic data server: cms-xrd-global.cern.ch:1094
      [i] Disabled source: cms-xrd-global.cern.ch:1094
----- End Fatal Exception -------------------------------------------------
```
still seems to be unrelated to this PR.

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
@cmsbuild please test

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
@cmsbuild please test

**Comment by mmusich** [comment]
+1

**Comment by mmusich** [comment]
@davidlange6 just to clarify the apparent change in the run2 MC GTs, it should not change the physics performance, since in the new payloads (V3 vs V1) a new level of correction (not consumed) is added, while keeping the rest the same. Please refer to this thread [HN link](https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2417/1/1/1/2/1/1.html) @blinkseb FYI.

**Comment by davidlange6** [comment]
@mmusich - when discussed yesterday this PR affected only data - however it looks like MC GTs are also updated. Are these already in use for production?

**Comment by mmusich** [comment]
Hi @davidlange6,
see please my comment https://github.com/cms-sw/cmssw/pull/15174#issuecomment-233681377. 
The change is somewhat only technical being the content of the level of the Jet corrections consumed at miniAOD the same. I think the JETMET group changed the nomenclature mostly to keep the same version number of the data ones (see here: https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2417/1/1/1.html). 
On a side note, this has already been validated in 81x.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
