### PR TITLE
NanoAODv6 updates [106X]

### PR DESCRIPTION
**Pull request by peruzzim**
backport #28122

PR description:
This pull request is the backport to 10_6_X of the updates for the NanoAODv6 campaign.
It's a cumulative backport of #28103 and #28122.
Depends on #28094 and #28136.

PR validation:
Usual validation in the cms-nanoAOD integration repository.

### CODE REVIEW

**Comment by peruzzim** [comment]
I open this already, to have a clearer bookkeeping and avoid forgetting backports.
The tests should run fine, but the configuration for running on UL samples is actually incorrect and will need a fix.

**Comment by peruzzim** [comment]
please test workflow 1325.6,1325.7,1325.8,1329.1,136.7722,136.7952,136.8521 with #28094,#28136

**Comment by peruzzim** [comment]
please test workflow 1325.6,1325.7,1325.8,1329.1,136.7722,136.7952,136.8521 with #28094,#28136

retesting after #28136 update

**Comment by santocch** [comment]
+1

**Comment by peruzzim** [comment]
Updated with backport of #28196

**Comment by peruzzim** [comment]
please test workflow 1325.6,1325.7,1325.8,1329.1,136.7722,136.7952,136.8521

**Comment by peruzzim** [comment]
please test workflow 1325.6,1325.7,1325.8,1329.1,136.7722,136.7952,136.8521

I retest because I suspect the previous test did not pick up a PR that had been just merged in the IB

**Comment by peruzzim** [comment]
+xpog

changes in NanoAOD products

**Comment by fabiocos** [comment]
@peruzzim this PR is including also #28196 right?

**Comment by peruzzim** [comment]
> @peruzzim this PR is including also #28196 right?

Yes, it does.

**Comment by fabiocos** [comment]
+operations

**Comment by fabiocos** [comment]
+1

**Pull request merged**
