### PR TITLE
Phase2-hgx291 Bug fix to address rotated layers in D86

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Bug fix to address rotated layers in D86. The changes will affect all workflows with HGCal. Mapping from position to DetId and vice versa are revised. This affects the public methods used in HGCalGeometry (getPosition, getClosestCell) and in HGCalDDDConstants (locateCell, locateCellHex, waferFromPosition, waferPosition). In the process the access method of getting position from ID is modified - earlier it was split between HGCalGeometry and HGCalDDConstant. Now it is done entirely in HGCalDDDConstants and this has affected the precision and hence there will be small changes in all earlier results.

#### PR validation:

Use the runTheMatrix test workflows 

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by rovere** [comment]
assign hgcal-dpg

**Review by rovere — CHANGES_REQUESTED** [review]

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by rovere** [comment]
Ciao @bsunanda 
* regarding your point (2), I saw no calls to random number engines in this PR. I assume this could be a side effect related to the way in which partial wafers are treated? 
* On a side note: is it comfortable that we have the geometry handling and definition mixed with the random number generator sequence? In cases like this, it will just add noisy-random changes while running the comparisons. It would be nice to see where and why those random numbers are generated.
* On another side note: was it mandatory to couple the `the edge effect` with the real bug fix for the rotated geometry? This is adding complexity and noise to something that should have been, instead, rather trivial to debug and compare with previous versions.

**Comment by bsunanda** [comment]
SimG4CMS/Calo/src/HGCalNumberingScheme calls functions in HGCalDDDConstants and that might cause some additional SimHits. After these changes the difference will entirely due to transformation from DtId to position and vice versa. I believe the current version is better than the earlier one in resolving these issues.

**Review by rovere — CHANGES_REQUESTED** [review]

**Comment by rovere** [comment]
Ciao @bsunanda 
I must confess I still did not fully understand the extent of the bug. From the discussion we had during the DPG Meeting today [Oct 13 2021] (by the way, thanks for preparing the slides!) I understand that my rather long explanation above [this one](https://github.com/cms-sw/cmssw/pull/35563#issuecomment-942112614), despite it makes sense with respect to what we observe in the comparison, is completely wrong. 
Can I at least ask you to go over that and **edit** that so that it reflects the exact content of the bug, the fix and the side effects? Maybe you'll be able to remember all this in one or two months, even more, but, as far as I'm concerned,  I don't feel comfortable addressing any specific question anyone would ask related to the content of this PR.
I realise I'm asking for additional work from your side: on the other hand this, I believe, is for a greater good now and in the longer term.

Really appreciated.

**Comment by bsunanda** [comment]
Earlier versions used to divide the work in 2 parts for getting a position from ID: getting the local coordinate inside the wafer (done in HGCalDDDConstant) and then applying a transformation (involving a transformation matrix) in HGCalGeometry. This was OK for unrotated layers - solution around that is to do the entire work in HGCalDDDConstant - it avoids any rotation for unrotated wafers (simply flipping the sign of x between wafers on +z and-z side). So the precision is better for unrotated layers now. 

Regarding getting the cell ID for partial wafers (in the SIM step) is checked to be correct for rotated layers. This is also checked to be correct for unrotated layers.

So the geometry is tested for the new version. The changes in earlier scenarios are due to some precision changes in these 2 steps.

**Comment by bsunanda** [comment]
@rovere Does the explanation above explain the issue?

**Comment by rovere** [comment]
Ciao @bsunanda, let me see if I got it after further digging into the code.
I ask you specific questions: please respond directly to them, w/o starting
another separate reply, otherwise we will never converge.

* The bug was affecting only rotated layers. For rotated layers here we really
  mean the 30 degrees rotation of the FH section of HGCAL, right? That's the
  only rotation you ever put in place as such. If the answer to that is yes, the
  only way I see to test this is to use a workflow with the `D86` geometry. In
  that case, running with and w/o this PR applied, I do expect a shift (i.e.
  rotation) of the position of the `RecHits`. Looking at the content of the PR
  and
  [here](https://cmssdt.cern.ch/dxr/CMSSW/source/Geometry/HGCalCommonData/src/HGCalGeomParameters.cc#1465-1472),
  the answer seems to be yes. By the way, the double conversion from Philippe's
  convention for rotation (second line in the so called flat file) to the
  internal _rotation convention_ is misleading, to say the least.

* I still do not understand why the changes at `SimHit` level are present only
  in the CE-E section which, following the discussion at the previous point,
  should not be affected at all. If, as you claim, now the position is computed
  in another way, why the _precision_ you mention is showing up only in the
  `CE-E` sections and nowhere else? And why it is not present in all `CE-E`
  layers?

**Comment by bsunanda** [comment]
@rovere That is fine. But this PR stands in the way of going forward with other geometry changes

**Comment by rovere** [comment]
Ciao @bsunanda,
thanks a lot for your answers.
In the meantime, I did some of the checks myself. I share my findings to speed up the review process.

* This PR will have **small** consequences on the retrieved position for the cells on all layers (I checked only CE-E and CE-H). The following table compares the `SimHit` position using the `baseline release` and `baseline+PR`. The amount of the change is within floating-point precision (5th to 6th digit).

| Number of SimHits with Diff position | layer type| layer Number |
| -------------------------- | -------------|------------------- |
| 89 | HGCalEESensitive | layer1 |
| 120 | HGCalEESensitive | layer10 |
| 101 | HGCalEESensitive | layer11 |
| 87 | HGCalEESensitive | layer12 |
| 90 | HGCalEESensitive | layer13 |
| 52 | HGCalEESensitive | layer14 |
| 87 | HGCalEESensitive | layer15 |
| 70 | HGCalEESensitive | layer16 |
| 68 | HGCalEESensitive | layer17 |
| 46 | HGCalEESensitive | layer18 |
| 47 | HGCalEESensitive | layer19 |
| 83 | HGCalEESensitive | layer2 |
| 33 | HGCalEESensitive | layer20 |
| 60 | HGCalEESensitive | layer21 |
| 45 | HGCalEESensitive | layer22 |
| 59 | HGCalEESensitive | layer23 |
| 39 | HGCalEESensitive | layer24 |
| 40 | HGCalEESensitive | layer25 |
| 26 | HGCalEESensitive | layer26 |
| 41 | HGCalEESensitive | layer27 |
| 25 | HGCalEESensitive | layer28 |
| 110 | HGCalEESensitive | layer3 |
| 111 | HGCalEESensitive | layer4 |
| 129 | HGCalEESensitive | layer5 |
| 116 | HGCalEESensitive | layer6 |
| 134 | HGCalEESensitive | layer7 |
| 133 | HGCalEESensitive | layer8 |
| 113 | HGCalEESensitive | layer9 |
| 55 | HGCalHESiliconSensitive | layer1 |
| 11 | HGCalHESiliconSensitive | layer10 |
| 10 | HGCalHESiliconSensitive | layer11 |
| 13 | HGCalHESiliconSensitive | layer12 |
| 8 | HGCalHESiliconSensitive | layer13 |
| 8 | HGCalHESiliconSensitive | layer14 |
| 2 | HGCalHESiliconSensitive | layer16 |
| 1 | HGCalHESiliconSensitive | layer17 |
| 3 | HGCalHESiliconSensitive | layer18 |
| 54 | HGCalHESiliconSensitive | layer2 |
| 2 | HGCalHESiliconSensitive | layer22 |
| 56 | HGCalHESiliconSensitive | layer3 |
| 51 | HGCalHESiliconSensitive | layer4 |
| 67 | HGCalHESiliconSensitive | layer5 |
| 48 | HGCalHESiliconSensitive | layer6 |
| 38 | HGCalHESiliconSensitive | layer7 |
| 57 | HGCalHESiliconSensitive | layer8 |
| 11 | HGCalHESiliconSensitive | layer9 |

I'm not sure why those differences do not show up in the DQM comparison, but that's not relevant, at this point.

* I checked also the `SimHit` position on layers 2, 4 and 6 in the CE-H section and I see that they are rotated, but not exactly by 30 degrees. Here is an example:

```
Detector HGCalHESiliconSensitive zside = -1 sector|wafer = 4:3 type = 0 layer = 2 cell = 20:8 energy = 3.48937e-05 energyem = 0 energyhad = 3.48937e-05 time = 13.0447
-92219114 global coordinate (441.719,418.431,-3731.49) time 13.0447:12.6113
- -----------------------   gx = 441.719 gy = 418.431 gz = -3731.49 phi = 0.75833 eta = -2.51339
+92219114 global coordinate (124.988,666.952,-3742.4) time 13.0447:12.6868
+ -----------------------   gx = 124.988 gy = 666.952 gz = -3742.4 phi = 1.38554 eta = -2.40877
```

As you can see there's a **shift in Z position** and the rotation is close to **36 degrees**. **Is that expected?** This is using workflow `38634` and comparing `baseline` and `baseline+PR`.

Thanks!

**Comment by rovere** [comment]
Ciao @bsunanda, 
I would not trust myself writing validation code related to the position of HGCAL detectors and cells.

You did not understand what I wrote before. What I see is a **non-30-degree** rotation of the very same cell on any of the affected layers (2,4,6 in CE-H) when comparing its position **before** and **after** merging this PR. I'm not comparing the position of the same cell across sibling rotated and non-rotated layers.

To check the position of the cells, all I did was to enable the `LogVerbatim` printouts in the `HGCalSimHitValidation.cc` file.
In particular, the `diff` snippet I reported comes from [here](https://github.com/cms-sw/cmssw/blob/15e787ced1a99dd86340b8eb213703b02efb7bda/Validation/HGCalValidation/plugins/HGCalSimHitValidation.cc#L183-L236).

I confirm that the position as computed by our _official `SimHit` validation code_ **are different** with respect to the position computed by the test script included in this PR.

Could you please cross check?

**Comment by bsunanda** [comment]
@rovere SimHitValidation code makes use of the method locateCell with the option that it needs o/p in Sim format while I used in my testing code the method getPosition of HGCalGeometry which in turn makes use of the same (locateCell) method with the option that it needs o/p in Reco format. The only difference is that in one case it returns in mm and in the other in cm. The issue may be in earlier version the coe was wrong - may be it does a part of the job (cell Id to x,y) correctly but other part (wafer to x,y) wrongly. Once I know that the earlier code of HGCalDDConstant was buggy, I would rely more on what I see in the current code. I inject the same wafer u,v and cell u,v in 2 layers - one unrotated and one rotated and see the difference. I do not go through the step of simulation in the process. I just observe at the level of geometry. Once the code is integrated I shall examine all the validation code in detail. The HGCalSimHitValidation code is OK as far as getting the position information.

**Comment by rovere** [comment]
Ciao @bsunanda,
the `HGCalSimHitValidation` is not ok in getting the position information, as far as I can tell.
The same DetId will be _placed_ in two different places if its position is decoded inside the `HGCalSimHitValidation` or inside the test code you added to this PR.
If you apply your PR, enable the dump of the position inside `HGCalSimHitValidation` and compare the position of a DetId on any of the layers 2,4, and 6 of `CE-H`, you will get different numbers. Clearly, by different, I do not mean in terms of cm vs mm.

**Comment by bsunanda** [comment]
@rovere What you suggested is an issue for the Validation package which can be looked into independently

**Comment by srimanob** [comment]
Hi @bsunanda @rovere 

Thanks for introducing the fix, and reviewing the PR. I'm not sure if you can converge with the discussion in PR, or we should have a discussion verbally somewhere, i.e. HGCAL DPG meeting? Thanks.

**Comment by bsunanda** [comment]
@rovere I activated the debug switch in HGCalSimHitValidation and took out a few ID's from there and tried with the code of HGCalGeometryRotTest and I do get identical results when scale by a factor of 10 for cm->mm. Here are the results:
From SimHitValidation:
Detector HGCalHESiliconSensitive zside = 1 sector|wafer = -5:-10 type = 2 layer = 3 cell = 7:14 energy = 1.43931e-05 energyem = 0 energyhad = 1.43931e-05 time = 61.2611
983d55c7 global coordinate (69.3503,-1498.13,3805.45) time 61.2611:13.6438
 -----------------------   gx = 69.3503 gy = -1498.13 gz = 3805.45 phi = -1.52454 eta = 1.66104

From HGCalGeometryRotTest
Layer: 29 U -5 V -10 Position (0, -145.008) phi -90
 HGCSiliconDetId::EE:HE= 0:1 type= 2 z= 1 layer= 3 wafer(u,v:x,y)= (-5,-10:0,-20) cell(u,v:x,y)= (7,14:20,-8) Position  (6.93503,-149.813,380.545)  phi -87.3496

From SimHitValidation:
Detector HGCalHESiliconSensitive zside = 1 sector|wafer = 1:3 type = 0 layer = 1 cell = 4:10 energy = 3.2011e-05 energyem = 0 energyhad = 3.2011e-05 time = 12.4293
90118544 global coordinate (74.4737,378.969,3679.35) time 12.4293:12.3404
 -----------------------   gx = 74.4737 gy = 378.969 gz = 3679.35 phi = 1.37675 eta = 2.94998

From HGCalGeometryRotTest
Layer: 27 U 1 V 3 Position (8.37204, 43.5024) phi 79.1066
 HGCSiliconDetId::EE:HE= 0:1 type= 0 z= 1 layer= 1 wafer(u,v:x,y)= (1,3:1,6) cell(u,v:x,y)= (4,10:-4,-14) Position  (7.44737,37.8969,367.935)  phi 78.8821

From SimHitValidation:
Detector HGCalHESiliconSensitive zside = 1 sector|wafer = -1:2 type = 0 layer = 2 cell = 6:1 energy = 6.69811e-05 energyem = 0 energyhad = 6.69811e-05 time = 12.6551

From HGCalGeometryRotTest
Layer: 28 U -1 V 2 Position (14.5008, 41.8602) phi 70.8934
 HGCSiliconDetId::EE:HE= 0:1 type= 0 z= 1 layer= 2 wafer(u,v:x,y)= (-1,2:4,4) cell(u,v:x,y)= (6,1:-31,-1) Position  (8.49488,37.9303,374.24)  phi 77.3763

From SimHitValidation:
90214426 global coordinate (84.9488,379.303,3742.4) time 12.6551:12.5505
Detector HGCalHESiliconSensitive zside = 1 sector|wafer = 2:0 type = 0 layer = 2 cell = 10:8 energy = 3.66259e-05 energyem = 3.66259e-05 energyhad = 0 time = 12.6634
9020090a global coordinate (-310.036,-178.999,3742.4) time 12.6634:12.5403
 -----------------------   gx = -310.036 gy = -178.999 gz = 3742.4 phi = -2.61799 eta = 3.04238

From HGCalGeometryRotTest
Layer: 28 U 2 V 0 Position (-29.0016, -16.7441) phi -150
 HGCSiliconDetId::EE:HE= 0:1 type= 0 z= 1 layer= 2 wafer(u,v:x,y)= (2,0:-4,0) cell(u,v:x,y)= (10,8:-10,0) Position  (-31.0036,-17.8999,374.24)  phi -150

SO I DONOT SEE any issue with HGCALSimHitValidation

**Comment by rovere** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

Note:

- If this PR targets D86, we should run the test with D86 workflow, apart from the private one. The way I do is the standard way of PR testing. The PR test with the short matrix you have done so far using "please test", which does not include D86 workflow.
- As the result of the PR, it affects all geometries, not only D86. This should be commented in the open validation campaign. Note to @cms-sw/pdmv-l2

**Comment by bsunanda** [comment]
@perrotta @qliphy Could you integrate this quickly. Waiting for some bug fixes which has to follow this integration

**Pull request merged**
