### PR TITLE
Adding plugin to monitor Pixel dead FED channels

### PR DESCRIPTION
**Pull request by fioriNTU**
With this PR a separate plugin to monitor Pixel dead FED channels is added, this is fundamental to keep under control the "stuck TBM" issue and hence to assess the Powercycling procedure and rate for 2018.

In the same PR a significant number of less useful plots is disabled in the RAWData plugin

### CODE REVIEW

**Comment by dmitrijus** [comment]
please test

**Comment by fioriNTU** [comment]
@fabiocos this is important to be merged in 10_1_X

**Comment by dmitrijus** [comment]
+1

**Comment by dmitrijus** [comment]
@fioriNTU you need to assign a new package. The message from the bot above tells you how.

**Comment by fioriNTU** [comment]
@dmitrijus thanks for the hint, I didn't pay attention to that message, my bad.
The PR is submitted https://github.com/cms-sw/cms-bot/pull/958 , shall I advertise someone to get it approved?

**Comment by davidlange6** [comment]
what is the motivation for such a small package ? Is this expected to grow (10x) in the near future?

**Comment by fioriNTU** [comment]
@davidlange6 this package is the first attempt to monitor in DQM dead FED channels in the Pixel detector. plots here should be fundamental to monitor the stuck TBM issue which triggers the dangerous (for DCDC converters) powercycles of the detector. So, I am quite sure this package will grow, I am not sure that it will x10.
Then in the PixelPhase1 DQM code, we have a different package to monitor each different quantity ( Clusters, Digi, RecHits ...) since here we monitor a new object, I wanted to preserve this structure.

**Comment by davidlange6** [comment]
> On Mar 8, 2018, at 11:24 AM, fioriNTU <notifications@github.com> wrote:
> 
> @davidlange6 this package is the first attempt to monitor in DQM dead FED channels in the Pixel detector. plots here should be fundamental to monitor the stuck TBM issue which triggers the dangerous (for DCDC converters) powercycles of the detector. So, I am quite sure this package will grow, I am not sure that it will x10.
> Then in the PixelPhase1 DQM code, we have a different package to monitor each different quantity ( Clusters, Digi, RecHits ...) since here we monitor a new object, I wanted to preserve this structure.

(as discussed previously...) - its not a such a great structure - you see now that you have a bunch of one file packages. Now is probably a good time to consolidate?

**Comment by fioriNTU** [comment]
@davidlange6 I surely have not your knowledge to judge how having packages made of single files can impact on the resource usage. By my naive point of view, keeping the code clean and as short as possible and keeping separate the different quantities needed to monitor, is helping a lot in development and maintenance. After a cpl of years, and a lot of fights to get this code in the release, I agree we should work on a general optimization, however I am not sure this is the right moment to proceed on this, the Tracker DQM plan is to review all this in LS2 and focus on data scrutiny in 2018.

**Comment by davidlange6** [comment]
perhaps a good start is to give the new package a generic name and start adding add new analyzers to it. Then the few hours needed for the general migration can happen later.

**Comment by fioriNTU** [comment]
@davidlange6 ok, we can put all analyzers together inside a generic PixelPhase1DQM package, I never though to this, the general structure is inherited by the Phase0 and Strip ones. This is surely feasible before LS2, I was thinking to the more general restyling we discussed last year. Anyway this package is to be integrated for the first collisions, I believe it can be done as it is, right?

**Comment by davidlange6** [comment]
> On Mar 8, 2018, at 12:27 PM, fioriNTU <notifications@github.com> wrote:
> 
> @davidlange6 ok, we can put all analyzers together inside a generic PixelPhase1DQM package, I never though to this, the general structure is inherited by the Phase0 and Strip ones. This is surely feasible before LS2, I was thinking to the more general restyling we discussed last year. Anyway this package is to be integrated for the first collisions, I believe it can be done as it is, right?

i was proposing to put the new analyzer into a generically named package now (eg DQM/SiPixelPhase1)

**Comment by fioriNTU** [comment]
@davidlange6 this mean I have to resubmit a PR in CMSSW, retest everything and wait for the process of testing and integration again. Fine, we will get in the production release for collisions? If you assure me we will be in time, it's ok, otherwise I would propose to merge it as it is. It is really going to break the production system?

**Comment by davidlange6** [comment]
> On Mar 8, 2018, at 12:35 PM, fioriNTU <notifications@github.com> wrote:
> 
> @davidlange6 this mean I have to resubmit a PR in CMSSW, retest everything and wait for the process of testing and integration again. Fine, we will get in the production release for collisions? If you assure me we will be in time, it's ok, otherwise I would propose to merge it as it is. It is really going to break the production system?

and we'll have the same discussion next time....

**Comment by fabiocos** [comment]
@fioriNTU when I looked at this code I had a similar thought as David. I see several of these one class packages are present, I think that combining them should not be terribly complex. By when could you have it ready? You could start to turn this PR into the generic package (we need a new one anyway), and then add commits to migrate other pieces here. This might be done in stages if too long, although I guess it should be relatively straightforward...

**Comment by fioriNTU** [comment]
@fabiocos this is true, it doesn't require much time, I could do it in ~ a day with 100% commitment on this (with all the tests, etc), but I have not that "day" at the moment. And there is nobody else at the moment in the Tracker DQM group that could do it in a safe way. My concern here is that I am asked to move the code in a "generic package", meaning I have to resubmit this PR, plus I have to resubmit the other one in the "bot" changing the name of a folder/package to a "generic one" while the code inside will not be generic at all. It looks to me quite unreasonable. And more, it looks to me I have to create this "generic package" only to make sure to do not forget to do the "homework". I just ask to be reasonable, merge this as it is for now (the "first step" you ask, won't change anything), and then plan for a restyle in a cpl of weeks timescale. In the meantime people can run the code and make their checks. Is it feasible?
(adding @davidlange6)

**Comment by fabiocos** [comment]
@fioriNTU let's try to converge: since a new package is implied anyway, please rename SiPixelPhase1DeadChannels to SiPixelPhase1 . Then when you or someone else will have "that day" all the other one-class packages may be moved there. I assume that this can be done in much less than one day.

**Comment by fioriNTU** [comment]
@fabiocos I want indeed to converge and if you push so strongly, probably is worth to make this change.
However let me clarify better my point, this PR is ready to be merged, the other PR in the cms-bot (https://github.com/cms-sw/cms-bot/pull/958) has been merged this morning. The change you ask is trivial, anyway it require to update this PR (and hence restart the tests, etc ...) and place another one in cms-bot. The final result will be to have changed nothing in the actual code that will run in production. I believe this quite an inefficient way to spend my time and also yours. 

Then I perfectly understand your point and the code structure will be changed as you suggest,  all the analyzers under the same package. This change will be made soon, before two weeks, I give you my word. As you noticed it is quite easy (even if require to touch also the DQM HLT code, whic in general is not my "property"). Your urgency in asking me to kindly waste one hour of my life to change a string in what I committed, make me feel a kind of a "bad guy". 

So, let me ask again to merge it as it is, please.

**Comment by fabiocos** [comment]
@fioriNTU I think that the real waste of time is this kind of conversation, the request might have been done in the meanwhile

**Comment by fabiocos** [comment]
+1

**Pull request merged**
