### PR TITLE
Electron and photon masses are set to zero

### PR DESCRIPTION
**Pull request by rgoldouz**
Hello,
The electron and photon mass are not saved properly and nanoAOD users reported that many times. It is not related to nanoAOD. The problem is available in miniAOD too.
You can check the printout here
root [6] Events->Scan("Photon_mass:Electron_mass:Muon_mass:Tau_mass")
***********************************************************************
*    Row   * Instance * Photon_ma * Electron_ * Muon_mass *  Tau_mass *
***********************************************************************
*        0 *        0 * 1.348e-06 *           *           * 0.9638671 *
*        1 *        0 *         0 *           * 0.1057128 * 0.1395263 *
*        2 *        0 * 4.768e-07 *           *           * 0.3725585 *
*        2 *        1 * -2.23e-07 *           *           *           *
*        3 *        0 * 1.192e-07 *           * 0.1057128 * 0.1395263 *
*        3 *        1 * 2.919e-07 *           *           *           *
*        4 *        0 * -2.69e-06 *           *           *           *
*        4 *        1 *         0 *           *           *           *
*        5 *        0 * 6.742e-07 * 0.0024929 *           *           *
*        6 *        0 *           * -0.004924 * 0.1057128 * 0.1395263 *
*        6 *        1 *           * 0.0061264 * 0.1057128 * 0.1395263 *
*        7 *        0 * 6.421e-07 * 0.0085830 *           * 0.1395263 *
*        7 *        1 * 1.907e-06 * -0.018432 *           *           *
*        7 *        2 * 1.348e-06 *           *           *           *
*        8 *        0 *         0 * -0.020462 *           * 1.0068359 *

I checked and found that the problem is not from the EGamma code but from TLorentzVector root class. I found that the TLorentz vector is set via pxpypzE for all object candidates. It seems fine but when I tested locally for a particle with pxpypzE=(1,1,1,sqrt(3)) I did not get the mass==0. You can easily reproduce it
root -l
root [1] typedef ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D > XYZTLorentzVectorD
root [2] XYZTLorentzVectorD newP4(1,1,1,sqrt(3));
root [3] newP4.M()
(double) -2.1073424e-08

It is because of the precision problem in TLorentz vector and it is recommended to use PxPyPzM to have correct masses for low mass objects.
https://root.cern.ch/doc/master/classROOT_1_1Math_1_1PxPyPzM4D.html

So I set the electron and photon masses by hand to 0 GeV , respectively.

Thanks,
Reza

### CODE REVIEW

**Comment by jpata** [comment]
@cmsbuild please test

**Comment by jpata** [comment]
thanks @rgoldouz. should the previous PR be closed? If so, please close the old one.

**Comment by rgoldouz** [comment]
Hi @jpata 

Done.

Thanks,
Reza

**Comment by jpata** [comment]
I'm surprised to see differences in MET corrections and uncertainties:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_3_X_2022-02-13-2300+5d6736/48363/validateJR/all_mini_OldVSNew_RunDoubleEG2017Cwf136p793/

https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_3_X_2022-02-13-2300+5d6736/48363/validateJR/all_mini_OldVSNew_RunDoubleEG2017Cwf136p793/all_mini_OldVSNew_RunDoubleEG2017Cwf136p793c_patMETs_slimmedMETs__reRECO_obj_0__corrections__1__dpx58.png


maybe @michaelwassmer has some idea why this can happen by changing the electron mass?

**Comment by michaelwassmer** [comment]
Sorry for not answering earlier. This week I'm already busy with a lot of other things, so I try to have a look at it next week.

**Comment by jpata** [comment]
@cmsbuild please test

**Comment by jpata** [comment]
what I don't understand here is why only the MET corrections differ, and not the MET itself, if the electron 4-vector changes.

**Comment by michaelwassmer** [comment]
That's what I'm also currently trying to figure out.

**Comment by jpata** [comment]
Thank you @michaelwassmer for the investigation. So I understand based on the above that it's an idiosyncrasy of the MET corrections code and not a problem.
Based on this I think we can move forward with this PR.

**Comment by michaelwassmer** [comment]
Yeah I think so too. I try to look into this a little bit more, since I'm curious, but I think the MET object is still fine after this PR.

**Comment by jpata** [comment]
+reconstruction
- fixes the electron mass to 0, with resulting small changes in downstream quantities

**Comment by qliphy** [comment]
@rgoldouz  Please edit the PR title and description more meaningful,   probably following your original PR #36889
For example, current PR title is "electron mass set to zero",  but you set also photon mass to zero.

**Comment by rgoldouz** [comment]
> @rgoldouz Please edit the PR title and description more meaningful, probably following your original PR #36889 For example, current PR title is "electron mass set to zero", but you set also photon mass to zero.

Hi @qliphy , Done. Thanks.

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
> > @rgoldouz Please edit the PR title and description more meaningful, probably following your original PR #36889 For example, current PR title is "electron mass set to zero", but you set also photon mass to zero.
> 
> Hi @qliphy , Done. Thanks.

Uhm, @rgoldouz what you did instead was to add two more (empty) commits with the title that @qliphy suggested for this PR. And this by the way forced us to relaunch the tests.
Assuming that the title that you assigned for the additional commits is the one that you wanted to give to the PR, I modified the title of this PR accordingly. Please update it (by clicking the "Edit" button on the right side of the title in this github thread) if you want to adjust it further.

**Comment by jpata** [comment]
+reconstruction
- no relevant changes since https://github.com/cms-sw/cmssw/pull/36954#issuecomment-1058019781

**Comment by qliphy** [comment]
+1

**Comment by swagata87** [comment]
type egamma 

it's rather hard to find out later on unless its tagged as egamma... so...

**Pull request merged**
