### PR TITLE
fix crash in case Limit on the number of clusters is really exceeded for 808

### PR DESCRIPTION
**Pull request by VinInn**
back port of #14662

### CODE REVIEW

**Comment by VinInn** [comment]
@cmsbuild , please test

**Comment by VinInn** [comment]
It NEEDS to be tested as the code has been copied and recommited.

**Comment by slava77** [comment]
Is there any reason to believe that 80X test will not give the needed behavior?
There are no IBs or jenkins test queues in \*patches branches

**Comment by VinInn** [comment]
@slava77 if you trust my
```
cp ../../CMSSW_8_0_X_2016-05-25-2300/src//RecoLocalTracker/SiPixelClusterizer/plugins/SiPixelClusterProducer.cc RecoLocalTracker/SiPixelClusterizer/plugins/SiPixelClusterProducer.cc
```

**Comment by slava77** [comment]
@VinInn 
I can see that the diff is the same (including the context lines).
Usually it's convincing enough.

**Comment by davidlange6** [comment]
I'll start a build and wait for the 80x tests and a reco +1 before uploading a patch

**Comment by slava77** [comment]
+1
(postfactum)

for https://github.com/cms-sw/cmssw/pull/14668	 	1bc4b10
- code change is to destruct the FastFiller to timely tell that the filled DetSet is not being filled anymore (m_filling=false) and with this also avoid a crash in DetSetVector::swap call
- tested on provided HLT raw file run274094_ls0292_index000012_fu-c2d32-22-03_pid77180.raw  : the crash is gone

**Pull request merged**
