### PR TITLE
Run3-gex62 Add debug statement to find issues in geometry definition of EB in dd4hep

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Add debug statement to find issues in geometry definition of EB in dd4hep

#### PR validation:

Use the runTheMatrix test workflows

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

This PR is needed for debug problems - was discussed with geometry group

**Comment by civanch** [comment]
urgent

**Comment by cvuosalo** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
