### PR TITLE
Fastsim Tracking: sync track id flag definitions with FullSim

### PR DESCRIPTION
**Pull request by lveldere**
Sync track id flag definitions with FullSim
A low statistics validation was performed,
and a much improved prediction of the track high purity criterium is observed.

FastSim cfg for track id is now imported from full tracking.

TrackProducers are imported from full tracker and edited only when needed for FastSim,
to better show the differences between FastSim and FullSim.

For the same reason, tracking collection names now follow full tracking convention.

One exception are the track seeds.
this will be fixed after merging of
https://github.com/lveldere/cmssw/compare/nSigmaZSelection
We also plan to change cfg file names to follow conventions of full tracking.

@VinInn @rovere

### CODE REVIEW

**Comment by lveldere** [comment]
+1

https://mkortela.web.cern.ch/mkortela/tracking/validation/CMSSW_7_4_0_pre6_fastsim/index.html

**Comment by lveldere** [comment]
https://mkortela.web.cern.ch/mkortela/tracking/validation/CMSSW_7_4_0_pre6_fastsim/index.html
still need to check the unit tests

**Comment by lveldere** [comment]
+1

@cmsbuild please test

**Comment by davidlange6** [comment]
+1

**Comment by lveldere** [comment]
thanks!

**Pull request merged**
