### PR TITLE
Improved scripts used to write 2024 Geom DB payloads

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

Removed use of sed and instead pass as command line arguments.

#### PR validation:

Tried to run steps outlined in #46290 but still failing because of a ZdcTopology being missing from the geometry description being used.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
The most recent change avoids the exception from ZdcTopology.

**Comment by Dr15Jones** [comment]
assign geometry

**Comment by Dr15Jones** [comment]
With the Zdc change, I do see the following error
```
[2024-10-08 10:35:30,697] ERROR: There is no tag, global tag or (unique) payload named XMLFILE_Geometry_142DD4hepV1_Extended2024ZeroMaterial_mc in the database.
```

which I do not know if that is a real error or an expected message.

**Comment by Dr15Jones** [comment]
With the last change, I found the bug causing the ERROR and now everything appears to run without a problem.

**Comment by perrotta** [comment]
+db

**Comment by bsunanda** [comment]
+geometry

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
