### PR TITLE
RecoTracker/TrackProducer: fix for clang warning -Woverloaded-virtual

### PR DESCRIPTION
**Pull request by gartung**
In file included from /build/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/c6796210c53b02f1870cdf07f5d562c4/opt/cmssw/slc6_amd64_gcc630/cms/cmssw/CMSSW_10_1_CLANG_X_2018-03-26-2300/src/RecoTracker/TrackProducer/plugins/SealModules.cc:3:
  /build/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/c6796210c53b02f1870cdf07f5d562c4/opt/cmssw/slc6_amd64_gcc630/cms/cmssw/CMSSW_10_1_CLANG_X_2018-03-26-2300/src/RecoTracker/TrackProducer/plugins/DAFTrackProducer.h:29:8: warning: 'DAFTrackProducer::getFromEvt' hides overloaded virtual functions [-Woverloaded-virtual]
   void getFromEvt(edm::Event&, edm::Handle<TrajTrackAssociationCollection>&, reco::BeamSpot&);
       ^
/build/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/c6796210c53b02f1870cdf07f5d562c4/opt/cmssw/slc6_amd64_gcc630/cms/cmssw/CMSSW_10_1_CLANG_X_2018-03-26-2300/src/RecoTracker/TrackProducer/interface/TrackProducerBase.h:66:16: note: hidden overloaded virtual function 'TrackProducerBase<reco::Track>::getFromEvt' declared here: type mismatch at 2nd parameter ('edm::Handle<TrackCandidateCollection> &' (aka 'Handle<vector<TrackCandidate> > &') vs 'edm::Handle<TrajTrackAssociationCollection> &' (aka 'Handle<AssociationMap<OneToOne<vector<Trajectory>, vector<reco::Track>, unsigned short> > > &'))
  virtual void getFromEvt(edm::Event&, edm::Handle<TrackCandidateCollection>&, reco::BeamSpot&);
               ^
/build/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/c6796210c53b02f1870cdf07f5d562c4/opt/cmssw/slc6_amd64_gcc630/cms/cmssw/CMSSW_10_1_CLANG_X_2018-03-26-2300/src/RecoTracker/TrackProducer/interface/TrackProducerBase.h:68:16: note: hidden overloaded virtual function 'TrackProducerBase<reco::Track>::getFromEvt' declared here: type mismatch at 2nd parameter ('edm::Handle<TrackView> &' (aka 'Handle<View<reco::Track> > &') vs 'edm::Handle<TrajTrackAssociationCollection> &' (aka 'Handle<AssociationMap<OneToOne<vector<Trajectory>, vector<reco::Track>, unsigned short> > > &'))
  virtual void getFromEvt(edm::Event&, edm::Handle<TrackView>&, reco::BeamSpot&);
               ^

### CODE REVIEW

**Comment by perrotta** [comment]
@cmsbuild please test

**Comment by perrotta** [comment]
@cmsbuild please test
(I expect that differences in tests disappear once the extra commits are not tested together)

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/22764	a907b1d
- technical disambiguation of the method name (the DAFTrackProducer::getFromEvt was not meant to override, it's just different. The DAFTrackProducer is not used in production.
- jenkins tests pass

**Comment by fabiocos** [comment]
+1

**Pull request merged**
