### PR TITLE
use pfnInPath to find the DDLSchema.xsd

### PR DESCRIPTION
**Pull request by smuzaffar**
This should fix the failing unit test. The data file was not read using FileInPath. This PR proposes to use pfnInPath to search the DDLSchema.xsd file.

@qliphy , this should fix the https://github.com/cms-sw/cmssw/pull/34087#issuecomment-860137766 issue

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@cms-sw/geometry-l2 @cms-sw/upgrade-l2 can you please sign it? Juts just updates the unit test ot find the data file using FileInPath instead of explicitly searching it under `LOCAL_TOP_DIR or CMSSW_RELEASE_BASE`.

@qliphy @silviodonato this is just a technical fix and safe to merge

**Comment by civanch** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

**Pull request merged**
