### PR TITLE
Remove deprecated std::iterator from MagneticField/Interpolation/src/bstream_iterator.h

### PR DESCRIPTION
**Pull request by jfernan2**
#### PR description:
Addressing issue https://github.com/cms-sw/cmssw/issues/43009

This PR removes the C++17 deprecated std::iterator in MagneticField/Interpolation/src/bstream_iterator.h in favor of the explicit declaration of the five iterator traits, as suggested by the link posted in the original issue.

@makortel I would appreciate your feedback on whether this is the correct approach/solution to the issue.
PR validation:

Code compiles.
Completed successfully the tests from scram b runtests
Backport:

Not a backport, no backport needed

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
I realize now that this file is not used/referenced anywhere in CMSSW, so it may be deprecated since scram b and usual tests do not complain of its absence. So we think this file may be safely removed

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by rappoccio** [comment]
+1

**Pull request merged**
