### PR TITLE
dead ES regions with corrected energy for each plane. Fixes inconsistency in regression training

### PR DESCRIPTION
**Pull request by argiro**

### CODE REVIEW

**Comment by slava77** [comment]
@argiro 
please provide some details on expected changes in performance.
Ideally, a link to slides or other similar document would work.

Thank you.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@argiro in case you missed,
please respond to https://github.com/cms-sw/cmssw/pull/17145#issuecomment-271944084

Thank you

**Comment by argiro** [comment]
@slava77 sorry for the late reply, here is some material in slide 4.
Presumably there will be no appreciable changes in the comparison, but the way in which the energy is reassigned to the dead/working plane matters for the regression
 
https://indico.cern.ch/event/578798/contributions/2398509/attachments/1386873/2111046/20161212_ES_Status.pdf

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/17145	72dba60
- changes are in line with the description in the supplied slides 
- jenkins tests pass and comparisons with baseline show no differences
- local tests with several other available matrix data workflows for 2016 show no differences in the outputs ... and the reason is that the GT for data uses ESEEIntercalibConstantsRcd	ESEEIntercalibConstants_LG_offline_data_default which has gammaLow1,2=1 and these lead to identical values for PS before and after the changes in this PR.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
