### PR TITLE
update track candidate DQM code

### PR DESCRIPTION
**Pull request by mtosi**
as PR https://github.com/cms-sw/cmssw/pull/10125

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by mtosi** [comment]
sorry, I forgot to delete one line in a file,
now it should work

**Comment by deguio** [comment]
please test

**Comment by mtosi** [comment]
uhmmm,
I'm sorry
but the following error
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-10126/57/runTheMatrix-results/1306.0_SingleMuPt1_UP15+SingleMuPt1_UP15+DIGIUP15+RECOUP15+HARVESTUP15+MINIAODMCUP15/step5_SingleMuPt1_UP15+SingleMuPt1_UP15+DIGIUP15+RECOUP15+HARVESTUP15+MINIAODMCUP15.log

seems to be not related to this PR, or am I missing something ?
thanks

**Comment by mtosi** [comment]
any news on this ?

**Comment by deguio** [comment]
+1

**Comment by deguio** [comment]
please test

**Comment by davidlange6** [comment]
+1

**Comment by VinInn** [comment]
@rovere  this PR breaks  the run1 tracking customize function.

```
25.0_TTbar+TTbarINPUT+DIGI+RECOAlCaCalo+HARVEST+ALCATT]$ cmsDriver.py step3 --datatier GEN-SIM-RECO,DQMIO --conditions auto:run1_mc -s RAW2DIGI,L1Reco,RECO,EI,ALCA:EcalCalZElectron+EcalCalWElectron+EcalUncalZElectron+EcalUncalWElectron+HcalCalIsoTrk,VALIDATION,DQM --eventcontent RECOSIM,DQM -n 100 --filein file:step2.root --fileout file:step3.root --customise RecoTracker/Configuration/customiseForRunI.customiseForRunI
```

produces
```
----- Begin Fatal Exception 31-Jul-2015 13:39:55 CEST-----------------------
An exception of category 'ProductNotFound' occurred while
   [0] Processing run: 1 lumi: 47 event: 4601
   [1] Running path 'dqmoffline_step'
   [2] Calling event method for module TrackingMonitor/'TrackSeedMonjetCoreRegionalStep'
Exception Message:
Principal::getByToken: Found zero products matching all criteria
Looking for type: std::vector<TrackCandidate>
Looking for module label: jetCoreRegionalStepTrackCandidates
Looking for productInstanceName: 
```

**Pull request merged**
