### PR TITLE
DQM GT to 112X in view of MWGR CMSSW 113X 

### PR DESCRIPTION
**Pull request by jfernan2**
#### PR description:

Forward port of https://github.com/cms-sw/cmssw/pull/32800

Using GT "112X_dataRun3_HLT_v1" for the moment to solve IB crashes in https://github.com/cms-sw/cmssw/issues/32796

Tested that the issue above is solved

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by silviodonato** [comment]
urgent 
for the MWGR

**Comment by christopheralanwest** [comment]
please test

A new IB in which the `edm::FileInPath` exceptions are not present is available. I would like to resolve the problems in the IB ASAP, so please forgive me for triggering the tests on a PR that does not require alca signature.

**Comment by jfernan2** [comment]
+1
Thanks @christopheralanwest

**Comment by silviodonato** [comment]
+1

**Pull request merged**
