### PR TITLE
Adding HtoZZ UL ID and phase II photon and electron ID configs

### PR DESCRIPTION
**Pull request by jainshilpi**
This PR concerns the addition of configs needed for running VID for recently tuned HtoZZ ID for UL. As well in the same PR, I am adding the relevant configs for phase II EB photon (MVA based) and electron IDs (cut based). The added configs can then be used by analysers with EgammaPostRecoTools to embed in the PAT objects. Files modified/added:

(1) RecoEgamma/ElectronIdentification/python/ElectronMVAValueMapProducer_cfi.py
(2) RecoEgamma/ElectronIdentification/python/Identification/mvaElectronID_Summer16UL_ID_ISO_cff.py
(3) RecoEgamma/ElectronIdentification/python/Identification/mvaElectronID_Summer17UL_ID_ISO_cff.py
(4) RecoEgamma/ElectronIdentification/python/Identification/mvaElectronID_Summer18UL_ID_ISO_cff.py
(5) RecoEgamma/ElectronIdentification/python/Identification/cutBasedElectronID_Summer20_PhaseII_V0_cff.py
(6) RecoEgamma/PhotonIdentification/python/Identification/mvaPhotonID_Summer20_PhaseII_V0_cff.py

The related presentations can be seen here:
HtoZZ electron ID: https://indico.cern.ch/event/895972/contributions/4297090/attachments/2219102/3757479/ElectronID_Egamma31032021.pdf
Phase II photon ID: https://indico.cern.ch/event/879937/contributions/4108370/
Phase II electron ID: https://indico.cern.ch/event/1000891/contributions/4203637/

The related PR for MVA files for electron (HtoZZ run II UL) and photon (phase II) IDs are here:
https://github.com/cms-data/RecoEgamma-ElectronIdentification/pull/18
https://github.com/cms-data/RecoEgamma-PhotonIdentification/pull/8

### CODE REVIEW

**Comment by slava77** [comment]
in case this needs to be backported to 106X for the UL needs, I think that it's better to split this PR into a UL-only PR and another Phase-2 specific PR.

Please clarify also if there is a plan to backport the phase-2 part to some older release.

**Comment by jainshilpi** [comment]
Hi Slava, yes I think it will be good to backport the HtoZZ to 106X. Shall I then close this PR and re-open separate ones? 
Discussing with @SohamBhattacharya, for phase-2, its fine to have from 12X - so no backport needed at this point.

**Comment by slava77** [comment]
> Hi Slava, yes I think it will be good to backport the HtoZZ to 106X. Shall I then close this PR and re-open separate ones?

that's perhaps easier.
Thank you.

**Comment by jainshilpi** [comment]
okay, I'll close this one and prepare 2 separate - thanks

**Pull request closed without merging**
