### PR TITLE
Add gen fragment for LLP relval

### PR DESCRIPTION
**Pull request by kakwok**
This PR is for adding the gen-fragment for relval sample for the new LLP seeds as per dicussion here:

https://its.cern.ch/jira/browse/PDMVRELVALS-152

The fragment is taken from the signal sample used in the TSG sample:
https://cms-pdmv.cern.ch/mcm/public/restapi/requests/get_fragment/HCA-Run3Winter20GS-00030/0

The backport to 12_4_X is https://github.com/cms-sw/cmssw/pull/38490

### CODE REVIEW

**Comment by SiewYan** [comment]
please test

**Comment by SiewYan** [comment]
@kakwok , thanks for the PR. Have you performed validation locally on this fragment? Do you mind sharing it here? Thanks

**Comment by kakwok** [comment]
Hi @SiewYan , do you have instructions to perform the validation? 
I have not done it myself, but it's directly taken from the TSG campaign for Run 3 MC here:
https://cms-pdmv.cern.ch/mcm/public/restapi/requests/get_fragment/HCA-Run3Winter20GS-00030/0

Is this good enough?

**Comment by Saptaparna** [comment]
Hi, is this a new configuration for Pythia or is this a filter? Are you filter anything? Also, do you want this to target 13.6 TeV or 14 TeV? Run III is 13.6 TeV as you know.

**Comment by Saptaparna** [comment]
Following up, since this a configuration file:
`Pythia8GeneratorFilter` -> `Pythia8ConcurrentHadronizerFilter`

**Comment by kakwok** [comment]
Hi @Saptaparna, thanks for your help! I've updated the PR as per your suggestion.

**Comment by SiewYan** [comment]
please test

**Comment by Saptaparna** [comment]
Sorry, I just noticed something: the hadronizer should be

`Pythia8ConcurrentGeneratorFilter` instead of `Pythia8ConcurrentHadronizerFilter` as your workflow is a Pythia only workflow. My apologies for failing to notice this before.

**Comment by perrotta** [comment]
> Sorry, I just noticed something: the hadronizer should be
> 
> `Pythia8ConcurrentGeneratorFilter` instead of `Pythia8ConcurrentHadronizerFilter` as your workflow is a Pythia only workflow. My apologies for failing to notice this before.

You can remove the "+1", then, by editing https://github.com/cms-sw/cmssw/pull/38496#issuecomment-1181940581

**Comment by SiewYan** [comment]
-1

**Comment by SiewYan** [comment]
Awaiting changes suggested on https://github.com/cms-sw/cmssw/pull/38496#issuecomment-1181946945

**Comment by SiewYan** [comment]
@kakwok , do you have any update on the suggested changes? Thanks.

**Comment by kakwok** [comment]
@SiewYan Sorry for the late response. Just fixed it.

**Comment by SiewYan** [comment]
please test

**Comment by SiewYan** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
