### PR TITLE
Add frozen V2.2 and work toward V3 HLT menu (92X)

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
Add frozen V2.2 and work toward V3 HLT menu (92X)
Based on CMSSW_9_2_8

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
backport of #20070

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by Martin-Grunewald** [comment]
@Dr15Jones 
please sign for the changes in addOntests.py ...

**Comment by Dr15Jones** [comment]
+1
for addOnTests changes

**Comment by davidlange6** [comment]
merge

**Pull request merged**
