### PR TITLE
Phase2-gex46 Update the FineCalo path for the Phas2 detectors

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Update the FineCalo path for the Phas2 detectors

#### PR validation:

Make use of the runTheMatrix test workflows 

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by cvuosalo** [comment]
What is the criteria for which scenarios get v2 and which get v5?

**Comment by bsunanda** [comment]
V2 decides only HGCal as a fine calorimeter while V5 decides HGCal and HFNose as fine calorimeters. So in scenarios with HFNose I use v5 and for others v2

**Comment by cvuosalo** [comment]
+1

**Comment by srimanob** [comment]
Hi @bsunanda 
Not sure if I confuse, but in the way you manage v2, v5 of CaloUtil.xml, don't you need to add v2 file also? I think it does not exist in master. Thanks.

**Comment by bsunanda** [comment]
Sorry I do not understand. CaloUtil.xml files for 2026 are in Geometry/HGCalSimData/data/CaloUtil/2026/vX with v's running from v1 till v5. The master has v1, v2, v3, v4 and this PR adds v5. Could you please clarify your comment a bit more?

**Comment by srimanob** [comment]
Ah, I somehow check on the wrong branch, I see it now. Thanks.

**Comment by srimanob** [comment]
+Upgrade

**Comment by qliphy** [comment]
+1

**Pull request merged**
