### PR TITLE
Update non-aged noise for V9 geometries

### PR DESCRIPTION
**Pull request by rovere**

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by kpedro88** [comment]
hold
because 10_4_0_mtd2 has already been released and may be used for MTD TDR DIGI production, we need to be careful introducing changes that might interfere with reusing the DIGI files in a later release

**Comment by kpedro88** [comment]
unhold

**Comment by kpedro88** [comment]
+upgrade

**Comment by fabiocos** [comment]
+1

**Pull request merged**
