### PR TITLE
Improvements/fixes on the conddb CLI tools

### PR DESCRIPTION
**Pull request by ggovi**
#### PR description:

In this PR:
- listRuns command also provide the start/end run time in timestamp IOV value
- edit command for IOVs returns error if the referenced Payload hash is not found in the concerned database
#### PR validation:

Edit being an interactive command, the tests has been executed on 'private' basis

### CODE REVIEW

**Comment by ggovi** [comment]
please test

**Comment by ggovi** [comment]
please test

**Comment by ggovi** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
