### PR TITLE
Fix bug in NanoGEN precision setting

### PR DESCRIPTION
**Pull request by kdlong**
#### PR description:

Fix bug in precision setting of gen variables in NanoGEN

#### PR validation:

It works as intended now

### CODE REVIEW

**Comment by mariadalfonso** [comment]
please test workflow 546,547,548

**Comment by mariadalfonso** [comment]
@kdlong 
the bug fix proposed here is not correct we are mixing Phi with Eta.

Step: DQM Spec: ['@nanogenDQM']
customising the process with customizeNanoGENFromMini from PhysicsTools/NanoAOD/nanogen_cff
Traceback (most recent call last):
  File "/cvmfs/cms-ib.cern.ch/nweek-02652/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_X_2020-10-27-1100/bin/slc7_amd64_gcc820/cmsDriver.py", line 56, in <module>
    run()
  File "/cvmfs/cms-ib.cern.ch/nweek-02652/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_X_2020-10-27-1100/bin/slc7_amd64_gcc820/cmsDriver.py", line 28, in run
    configBuilder.prepare()
  File "/cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc820/cms/cmssw-patch/CMSSW_11_2_X_2020-10-27-2300/python/Configuration/Applications/ConfigBuilder.py", line 2273, in prepare
    self.pythonCfgCode += self.addCustomise()
  File "/cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc820/cms/cmssw-patch/CMSSW_11_2_X_2020-10-27-2300/python/Configuration/Applications/ConfigBuilder.py", line 885, in addCustomise
    self.process=getattr(package,fcn)(self.process)
  File "/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_2_X_2020-10-27-2300/python/PhysicsTools/NanoAOD/nanogen_cff.py", line 77, in customizeNanoGENFromMini
    nanoGenCommonCustomize(process)
  File "/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_2_X_2020-10-27-2300/python/PhysicsTools/NanoAOD/nanogen_cff.py", line 56, in nanoGenCommonCustomize
    setGenEtaPrecision(process, CandVars.eta.precision)
  File "/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_2_X_2020-10-27-2300/python/PhysicsTools/NanoAOD/nanogen_cff.py", line 137, in setGenEtaPrecision
    process.metMCTable.variables.eta.precision = precision
AttributeError: 'PSet' object has no attribute 'eta'

**Comment by kdlong** [comment]
@mariadalfonso yes sorry, I thought I had tested this code but in fact it was never called previously. I fixed this and did a small amount of refactoring as well

**Comment by mariadalfonso** [comment]
please test workflow 546,547,548

**Comment by mariadalfonso** [comment]
+xpog

updates only to GENnano  inline with description

**Comment by silviodonato** [comment]
merge
@santocch please have a look

**Comment by santocch** [comment]
+2

**Comment by santocch** [comment]
+1

**Pull request merged**
