### PR TITLE
Improved ExternalFailed exception messages

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

Added information about length of time used when waiting.

#### PR validation:

Code compiles.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by makortel** [comment]
Differences likely caused by https://github.com/cms-sw/cmssw/pull/33923 being included. Let's retest on the next IB.

**Comment by agrohsje** [comment]
Hi @makortel, you suggest to wait with signing?

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
Even if there is no way for this PR to cause such differences, I wanted to see cleaner comparisons.

**Comment by makortel** [comment]
+1

**Comment by agrohsje** [comment]
+generators

**Comment by qliphy** [comment]
+1

**Pull request merged**
