### PR TITLE
Phase2-gex165 Remove the BSC detector from the description of all phase2 scenarios

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Remove the BSC detector from the description of all phase 2 scenarios. Also, remove the descriptions of all depreciated sub-detector scenarios

#### PR validation:

Use the runTheMatrix test workflows 

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

**Comment by perrotta** [comment]
There are quite several changes in output.
Can someone comment about them, and confirm that they are all expected?

**Comment by perrotta** [comment]
+1

**Comment by srimanob** [comment]
Hi @civanch @bsunanda 

With this PR, should 'BSCSensitiveDetector' should also be deleted for Phase-2 in 
https://github.com/cms-sw/cmssw/blob/master/SimG4Core/Application/python/g4SimHits_cfi.py#L709 ? Thanks.

**Comment by civanch** [comment]
@srimanob , you are right. I suspect that current configuration harmless but this deletion should be done.

**Pull request merged**
