### PR TITLE
HLT menu development for `13_3_X` (3/N)

### PR DESCRIPTION
**Pull request by mmusich**
backport of https://github.com/cms-sw/cmssw/pull/43867

#### PR description:

Development of HLT menus for CMSSW_13_3_X:

   * this is an intermediate update towards the 2024 proton-proton run data-taking (and the **final one** foreseen to happen in the CMSSW_13_3_X cycle before moving to a new template in CMSSW_14_0_X).

This is the PR for the master branch, which will then be backported down to 13_3_X (the latter is the release cycle currently used for Run-3 HLT-menu development).

This update includes the integration of the following JIRA tickets:
- [CMSHLT-2993](https://its.cern.ch/jira/browse/CMSHLT-2993) [MUO]: HLT path for High-pT muons seeded by the L1 Muon Shower Trigger

#### PR validation:

TSG integration tests.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Verbatim backport of https://github.com/cms-sw/cmssw/pull/43867  to CMSSW_13_3_X.

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by mmusich** [comment]
+hlt

**Comment by rappoccio** [comment]
+1

**Comment by Martin-Grunewald** [comment]
seems stuck?

**Pull request merged**
