### PR TITLE
[FastSimulation/TrackingRecHitProducer] Move boost spirit headers to source file

### PR DESCRIPTION
**Pull request by camolezi**
#### PR description:
We can move the boost spirit includes to the implementation file.
Since TrackerDetIdSelectorGrammar is only used here, we can isolate it in the source file. 
This change will increase modularity, and possibly helps us with c++20 clang modules.

#### PR validation:
Code compiled

#### if this PR is a backport please specify the original PR and why you need to backport that PR:
@vgvassilev @davidlange6

### CODE REVIEW

**Comment by silviodonato** [comment]
Do you have any comments @cms-sw/fastsim-l2 ?

**Comment by civanch** [comment]
@sbein , what about this PR? @camolezi , I would indeed use "const std::string&".

**Comment by silviodonato** [comment]
Kind reminder @sbein @camolezi

**Comment by camolezi** [comment]
> @sbein , what about this PR? @camolezi , I would indeed use "const std::string&".

@civanch. Do you mean changing passSelection(std::string selectionStr) to passSelection(std::string& selectionStr)?

**Comment by civanch** [comment]
Exactly.

**Comment by civanch** [comment]
please test

**Comment by silviodonato** [comment]
Do you have any further comment @civanch ?

**Comment by civanch** [comment]
is fine to me. @sbein , can you sign this PR?

**Comment by civanch** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
