### PR TITLE
Phase2-hgx360M Change 2026 to Run4 in the scenario definitions of the scripts in Validation/Geometry

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Change 2026 to Run4 in the scenario definitions of the scripts in Validation/Geometry

#### PR validation:

Tested all the scripts

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
+geometry

**Comment by antoniovagnerini** [comment]
+1
- spurious differences from HGCal DQM test (open issue  #46416)

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
