### PR TITLE
[RFC] Test clang-tidy --checks performance-implicit-conversion-in-loop

### PR DESCRIPTION
**Pull request by fwyzard**
See the description at https://clang.llvm.org/extra/clang-tidy/checks/performance-implicit-conversion-in-loop.html .

### CODE REVIEW

**Comment by fwyzard** [comment]
These should already be flagged ?

**Comment by alja** [comment]
+1

**Comment by pohsun** [comment]
+1

**Comment by ggovi** [comment]
+1

**Comment by mrodozov** [comment]
- note
not using it , another check will cover it

**Pull request closed without merging**
