### PR TITLE
Phase2-hgx335E Update the validity test of partial wafers of V16 geometry as well as the test kits

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Update the validity test of partial wafers of V16 geometry as well as the test kits. Expect small changes in all scenarios using V16 geometry of HGCal or HFNose

#### PR validation:

Use the test scripts in Geometry/HGCalCommonData/test/python

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing sp[ecial

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
+geometry

**Comment by srimanob** [comment]
Hi @bsunanda 
I assume we don't expect the change from this PR. The PR test shows the change in Phase-2 workflow, https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_13_0_X_2023-01-22-2300+b09217/55138/validateJR.html. Should we re-trigger the test?

**Comment by bsunanda** [comment]
@srimanob Since the validity test is modified for v16, we expect to see some changes in Phase2 scenarios

**Comment by srimanob** [comment]
+Upgrade

Change in D88 is expected as mentioned in the PR description and https://github.com/cms-sw/cmssw/pull/40585#issuecomment-1401534680. Thx @bsunanda

**Comment by perrotta** [comment]
+1

**Pull request merged**
