### PR TITLE
Adding 2 data workflows to test 90 m beta* Totem run reconstruction

### PR DESCRIPTION
**Pull request by fabozzi**
As a follow-up to the discussion in #23275 we deploy 2 data workflows to test reconstruction for Totem run.

### CODE REVIEW

**Comment by fabozzi** [comment]
please test workflow 136.8561,136.8562

**Comment by fabozzi** [comment]
please test workflow 136.8561,136.8562

**Comment by fabozzi** [comment]
please test workflow 136.8561,136.8562

**Comment by fabozzi** [comment]
The new relvals run OK; but now we see this error in the addOn tests like:
----- Begin Fatal Exception 31-May-2018 14:48:42 CEST-----------------------
An exception of category 'CTPPSGeometry' occurred while
   [0] Processing  Event run: 295606 lumi: 1 event: 37585 stream: 1
   [1] Running path 'reconstruction_step'
   [2] Calling method for module TotemRPUVPatternFinder/'totemRPUVPatternFinder'
Exception Message:
Not found RP device with ID 1981284352, i.e. subDet=3 arm=0 station=0 rp=3

Not clear to me how it is related to the aupdated GT we are using.

**Comment by arunhep** [comment]
@fabozzi this could be related because I have replaced all the history of CTPPS geometry with a single IOV tag containing TOTEM inside.
The run being probed in add-on test is 295606 and according to the original tag : 
https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/tags/XMLFILE_CTPPS_Geometry_101YV3_hlt

it was consuming the payload fbc7e091f0c7928beea980d692dc8f3d0f1b5c31 and now it is consuming 7074ae1110e00c24e6b43118e5131c329dfe7912
may be @ianna can help us here in understanding the difference between these two updates.

there are two solutions : 

1. update the add-on test with a run containing the CTPPS geometry that can be compatible with the present geometry proposed

2. I provide multi-IOV tag and prepare another GT. But in that case, the tag will be different from regular hlt tag because we can't really propagate geometry with TOTEM in past for the present tag

**Comment by fabiocos** [comment]
@arunhep sorry, but we cannot use in the release a run2 GT that prevents us to run on whatever past CTPPS configuration, this solution cannot work. Here the issue is to replace the geometry record for the past CTPPS run so as to have this test working on old data, while having all the rest working as usual. If I understand your comment this cannot be done?

**Comment by arunhep** [comment]
@fabiocos okay then let me prepare a GT which is also compatible with old CTPPS configuration

**Comment by arunhep** [comment]
@fabozzi please include this commit : https://github.com/cms-sw/cmssw/commit/394f2d0724c413d45d705d553bf978c541c31c1d
this should fix the problem of add-on tests

https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/102X_dataRun2_PromptLike_v3/102X_dataRun2_PromptLike_v2

**Comment by fabiocos** [comment]
please test workflow 136.8561,136.8562

**Comment by lpernie** [comment]
please test

**Comment by fabiocos** [comment]
please test workflow 136.8561,136.8562

**Comment by prebello** [comment]
+1

tests approved and injected samples ready for Totem checks at 
https://dmytro.web.cern.ch/dmytro/cmsprodmon/requests.php?campaign=CMSSW_10_2_0_pre4__data2018_hBStar-1527764317

**Comment by fabiocos** [comment]
@arunhep @kpedro88 so is this PR finally ok for you? From the GT point of view the only change is the CTPPS geometry, right?

**Comment by kpedro88** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
