### PR TITLE
Remove global declarations in classes.h

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

The declaration of a variable of a given type is no longer necessary to generate a ROOT dictionary.

This was found by the static analyzer.

#### PR validation:

The code compiles and the resultant .rootmap file is functionally identical to the original one.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

@santocch FYI

**Comment by santocch** [comment]
+1

**Pull request merged**
