### PR TITLE
Add fixed HLLHC vertex generator (HLLHC_Fix)

### PR DESCRIPTION
**Pull request by simonepigazzini**

### CODE REVIEW

**Comment by fratnikov** [comment]
please test

**Comment by fratnikov** [comment]
@simonepigazzini What is the difference between new HLLHCEvtVtxGeneratorFix and old HLLHCEvtVtxGenerator. They look very closely related... Probably one can be inherited from another?

**Comment by mark-grimes** [comment]
As I understand it, they're exactly the same apart from a lack of [c_light in the time calculation](https://github.com/cms-sw/cmssw/pull/8320/files#diff-4d8ead4f190590078a9dd11739b61e30R80) (as [seen here](https://github.com/cms-sw/cmssw/blob/CMSSW_6_2_X_SLHC/IOMC/EventVertexGenerators/src/HLLHCEvtVtxGenerator.cc#L82) for the HLLHC beamspot), which fixes the bug in the time.  @boudoul was keen to keep the original bugged HLLHC beamspot for production samples for studies that aren't sensitive to the time.

**Comment by simonepigazzini** [comment]
@fratnikov I can rewrite the new class so that it inherits from the old one if you prefer.

**Comment by boudoul** [comment]
The original HLLHC should eventually disappear in benefit of HLLHC_Fix (since HLLHC is buggy), but for the moment we cannot fix directly the original class in order to keep the compatibility with the present gensim (simulation frozen due to TP production) - so I would suggest  to keep the PR as it is for the moment.

**Comment by mark-grimes** [comment]
merge

I agree with @boudoul, and pushing through so HGCal can have a release on Lucia's request.

**Pull request merged**
