### PR TITLE
Move Sequence to Task for RecoLocalCalo config files

### PR DESCRIPTION
**Pull request by jeongeun**
#### PR description: Move Sequence to Tasks in RecoLocalCalo configurations.
1) For a cms.Sequence object that is built from modules or cms.Sequence objects introduce a cms.Task with an equivalent content and make this cms.Sequence object directly from the newly introduced cms.Task. [More details about Task objects](https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideAboutPythonConfigFile#Task_Objects)
2) Remove cms.Sequence objects from the Reconstruction configuration.  
I replaced the sequence by instantiating it with a task.
#### PR validation:
Tested in CMSSW_11_0_X_2019-07-07-2300 release, The PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html).

### CODE REVIEW

**Comment by rovere** [comment]
Could we test this also with the workflow 29093.52? It touches configurations used also by TICL with its customize and I'd like to be sure nothing gets broken.
Thanks!

**Comment by perrotta** [comment]
please test workflow 29093.52

**Comment by kpedro88** [comment]
The problem appears to be:
```
  File "/build/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_0_X_2019-07-07-2300/python/Configuration/StandardSequences/Reconstruction_cff.py", line 6, in <module>
    from RecoLocalCalo.Configuration.RecoLocalCalo_cff import *
  File "/build/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_0_X_2019-07-07-2300/python/RecoLocalCalo/Configuration/RecoLocalCalo_cff.py", line 37, in <module>
    from RecoLocalCalo.Configuration.hgcalLocalReco_cff import *
  File "/build/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_0_X_2019-07-07-2300/python/RecoLocalCalo/Configuration/hgcalLocalReco_cff.py", line 19, in <module>
    particleFlowClusterHGCalFromMultiCl )
  File "/cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc700/cms/cmssw-patch/CMSSW_11_0_X_2019-07-07-2300/python/FWCore/ParameterSet/SequenceTypes.py", line 1280, in __init__
    self.add(*items)
  File "/cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc700/cms/cmssw-patch/CMSSW_11_0_X_2019-07-07-2300/python/FWCore/ParameterSet/SequenceTypes.py", line 1292, in add
    raise RuntimeError("Adding an entry of type '" + type(item).__name__ + "'to a Task.\n"
RuntimeError: Adding an entry of type 'Sequence'to a Task.
It is illegal to add this type to a Task.
```

**Comment by slava77** [comment]
It's strange that this did not show up during the tests prior to the PR submission


> Tested in CMSSW_11_0_X_2019-07-07-2300 release, The PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html).

**Comment by jeongeun** [comment]
I'll re-check this and close this PR.

**Pull request closed without merging**
