### PR TITLE
drop tracking DQM histos (which contribute to memory issues @tier0)

### PR DESCRIPTION
**Pull request by mtosi**
as reported/suggested/requested by tracking POG
(@rovere @VinInn @makortel)
recent issues reported by tier0 related to memory consuption
might be related to some plots done by the tracking DQM
(or at least, given the current framework, such plots are highly stressing the system)

this PR should switch off many of them

@davidlange6 , do you like this ?

### CODE REVIEW

**Comment by mtosi** [comment]
in order to really quantify the fix
you should make use of the config used @tier0 on ZeroBias PD

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
