### PR TITLE
remove obsolete DataFormats/Phase2ITPixelCluster package 

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

This PR removes from `DataFormats` the phase2 IT pixel clusters introduced in 2016 in preparation of the TRK TDR (similarly to Phase2TrackerCluster introduced for OT) but then not used. The removal entails the entire subsystem `DataFormats/Phase2ITPixelCluster`.
The producer class has been already removed in PR #19360.
Please be aware from https://github.com/cms-sw/cmssw/pull/19360#issuecomment-310103329
of possible issues occurring when removing the package that may require a full build. 

#### PR validation:

It compiles and passes `runTheMatrix.py -l limited -i all -j 8 -t 4 --ibeos`

#### if this PR is a backport please specify the original PR:

This is not a backport.
cc:
@emiglior @pwittich

### CODE REVIEW

**Comment by kpedro88** [comment]
@mmusich just to confirm, these objects were never used in any central production?

**Comment by kpedro88** [comment]
please test

**Comment by mmusich** [comment]
> @mmusich just to confirm, these objects were never used in any central production?

@kpedro88 that's my understanding, as it was never possible to make tracking work with the rechits made out of these clusters, but I let @emiglior confirm.

**Comment by emiglior** [comment]
No tracks were produced using Phase2ITPixelClusters
I cannot exclude they were added to the local reco sequence in the RelVals of some 81X pre-release

**Comment by kpedro88** [comment]
+upgrade

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/27662	b75da1d
- complete removal of DataFormats/Phase2ITPixelCluster package (the PR description could be a bit more explicit about it)
- jenkins tests pass

**Comment by mmusich** [comment]
@slava77 
> complete removal of DataFormats/Phase2ITPixelCluster package (the PR description could be a bit more explicit about it)

You mean the PR title or the PR description? I can edit the title to make it explicit a package is removed.

**Comment by slava77** [comment]
> You mean the PR title or the PR description? I can edit the title to make it explicit a package is removed.

either way is fine.
I just wanted to have it a bit more clear that not just some classes are removed, the full package is gone.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
