### PR TITLE
Remove direct dependency on PythonParameterSet from FWCore/SerivceRegistry

### PR DESCRIPTION
**Pull request by davidlange6**
#### PR description:

Remove direct dependency on PythonParameterSet from FWCore/SerivceRegistry
(affects tests/binaries only - but cascades into build files)

Motivation is to remove libFWCoreParameterSetReader dependency from libFWCoreServiceRegistry

#### PR validation:

compiles ok - just code rearrangement.

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
please test




On 10 Mar 2019, at 22:51, cmsbuild <notifications@github.com<mailto:notifications@github.com>> wrote:


+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-26138/8704

  *   This PR adds an extra 28KB to repository

**Comment by fabiocos** [comment]
@davidlange6 the failure of the unit test is independent on this PR

**Comment by cvuosalo** [comment]
+1

**Comment by Dr15Jones** [comment]
please test

**Comment by fabiocos** [comment]
@davidlange6 @Dr15Jones @alja @ggovi  the unit test failure is unrelated to this PR, do you have any further comment?

**Comment by Dr15Jones** [comment]
+1
since the unit test failure is unrelated

**Comment by alja** [comment]
+1

**Comment by santocch** [comment]
+1

**Comment by fabiocos** [comment]
@ggovi I assume the update to CondCore is ok for you, please check and sign it in case, I will move forward with this update

**Comment by fabiocos** [comment]
+1

**Comment by davidlange6** [comment]
hi @fabiocos - you need to do 'merge'...

**Comment by fabiocos** [comment]
@davidlange6 I was waiting to see whether it was coming from @ggovi approval. In any case perhaps the test failure requires an explicit merge

**Comment by fabiocos** [comment]
merge

**Comment by fwyzard** [comment]
@davidlange6 @Dr15Jones 

what was the rationale for this change ?

just to make sure that all test involving Services break and have to be modified, copying the same 3 lines over and over, and adding an explicit dependency on a new package ?

**Pull request merged**
