### PR TITLE
updating trigger names in MssmHbbMonitoring and MssmHbbBtagTriggerMon…

### PR DESCRIPTION
**Pull request by antoniovagnerini**
…itoring

### CODE REVIEW

**Comment by mtosi** [comment]
@cmsbuild, please test

**Comment by mtosi** [comment]
@antoniovagnerini 
please
1. add few comments in order to understand the reason of this PR, which is the HLT menu version, etc
2. please, quantify the change in #bins (if any)

**Comment by antoniovagnerini** [comment]
sure, the PR is necessary to update the trigger names for the MssmHbbMonitor and the MssmHbbBtagTriggerMonitor to the naming convention adopted since HLT menu v2.0.
There are no other changes.

Without such changes, ALL the numerator MssmHbb DQM plots produced by the Client are empty. This can be checked for example by looking at https://goo.gl/3zvg6x

**Comment by mtosi** [comment]
thanks
they are produced by the Source, not the Client ;)

they should have been spotted by the HIG validator in the most recent 93x release validation campaigns !!!!!!

**Comment by antoniovagnerini** [comment]
so now only signatures are missing right?

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
