### PR TITLE
Phase2-sim121 Prints out G4VSolid parameters to debug issues in scenarios created using DD4hep

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Prints out G4VSolid parameters to debug issues in scenarios created using DD4hep

#### PR validation:

Use the cfg in the test area to debug 2 versions of 2026 geometries created using DDD and DD4hep

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
