### PR TITLE
Phase2-hgx310 Correct cassette positioning in view of modified flat file format for HGCal silicon

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Correct cassette positioning in view of modified flat file format for HGCal silicon

#### PR validation:

Rcreated components of the new XML files

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cvuosalo @civanch @srimanob  Please review this PR and sign it so that we can proceed to the next step

**Comment by civanch** [comment]
+1

**Comment by bsunanda** [comment]
@srimanob Please sign this. Waiting for the next step of V17

**Comment by srimanob** [comment]
Hi @bsunanda 
Does the correction of the cassette positioning not reflected in the PR test?
In the PR description, you said "Rcreated components of the new XML files". Don't you need to update also XML?

Thanks for clarification.

**Comment by bsunanda** [comment]
@srimanob Concept of cassette in CMSSW HGCal description will be introduced only with v17 version. They code is in preparation for that.

**Comment by srimanob** [comment]
+Upgrade

This PR is used to prepare V17. No change is expected.

@bsunanda would you mind to update PR description to make it more clear. I have to admit that reading it without inside HGCal information, I can't understand what the PR is and what to expect from the PR. Thanks,

**Comment by perrotta** [comment]
+1

**Pull request merged**
