### PR TITLE
Event filter utilities fix clang warning

### PR DESCRIPTION
**Pull request by gartung**

### CODE REVIEW

**Comment by gartung** [comment]
@Dr15Jones

**Comment by fwyzard** [comment]
+1

**Comment by Dr15Jones** [comment]
please test

**Comment by cvuosalo** [comment]
In RawEventFileWriterForBU.cc/h, RawEventFileWriterForBU::instance is a thread-unsafe private static member that is set but never used. It probably could be deleted, unless there is some special reason for keeping it. Fixing it would eliminate a static analyzer warning, but this fix could wait for a later PR.

**Comment by cvuosalo** [comment]
+1

For #11008 4dc535c3d20d5adf14ffe07d2e1df8257315ea4e

Fixing Clang warnings in event filter utilities. There should be no change in run-time behavior.

The code changes are satisfactory, and Jenkins [tests](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-11008/7726/summary.html) against baseline CMSSW_7_6_X_2015-08-28-1100 show no significant differences, as expected.

**Pull request merged**
