### PR TITLE
Backport: Update RPC time resolution parameters

### PR DESCRIPTION
**Pull request by jhgoh**
Backport of #18674, to be unsed in the muon TDR production.

@bapavlov @calabria @jshlee @kpedro88

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
Hi @jhgoh - this PR has merge conflicts. Please rebase

**Comment by jhgoh** [comment]
fixed conflict.

**Comment by davidlange6** [comment]
please test

**Pull request merged**
