### PR TITLE
More plots from GE21 for the GEM DQMs, a backport to 12_3_X

### PR DESCRIPTION
**Pull request by quark2**
#### PR description:
We have several updates on GEM DQMs.

- Migrations of some plots to other places (online -> offline or vice versa)
- More plots for GE21 is now available

This PR is the backport of #38398 (+#38526) to CMSSW_12_3_X.

#### PR validation:
Test are done and one can check again by `runTheMatrix` workflows

@jshlee @watson-ij @seungjin-yang

### CODE REVIEW

**Comment by emanueleusai** [comment]
type gem

**Comment by emanueleusai** [comment]
type feature

**Comment by emanueleusai** [comment]
backport of #38398

**Comment by emanueleusai** [comment]
please test

**Comment by emanueleusai** [comment]
testing at P5

**Comment by emanueleusai** [comment]
@quark2 do you need this deployed online?

**Comment by quark2** [comment]
Hi @emanueleusai, 

Yep, we need this update to be deployed in P5.

**Comment by jpata** [comment]
+reconstruction
- on the reco side, it's transparent / minimal (no observed changes)
- the reco part is a direct backport of https://github.com/cms-sw/cmssw/pull/38398

**Comment by quark2** [comment]
I've found that an update on the configurations on some plots is needed to avoid unexpected issues

**Comment by quark2** [comment]
Hi @tvami, 

Not yet, I'm now making the PR to the master. I'll notice when it is ready.

Best regards, 
Byeonghak Ko

**Comment by tvami** [comment]
OK, with this it seems this will not enter 12_3_6, given that the PR touches the `reco`, I'm not sure if it can be applied on the top of 12_3_6 in DQM. @qliphy @perrotta ?

**Comment by jpata** [comment]
+reconstruction
- resign with no reco-related changes
- on the reco side, it's transparent / minimal (no observed changes)
- the reco part is a direct backport of https://github.com/cms-sw/cmssw/pull/38398

**Comment by emanueleusai** [comment]
tests at P5 completed successfully

**Comment by emanueleusai** [comment]
+1

**Comment by perrotta** [comment]
The modification on EventFilter/GEMRawToDigi/plugins/GEMRawToDigiModule.cc touches reco. But they are said to just add small items that keep simple bitwise statuses, and these are not used anywhere except onlineDQM and offlineDQM, see https://github.com/cms-sw/cmssw/pull/38398#issuecomment-1162088489

However, to stay on the safe side, I would suggest that this PR is only included in the online DQM release for 12_3_X, but not included in the central now closed release

**Comment by quark2** [comment]
Hi @perrotta, 

I think it's surely okay. Btw for the onlineDQM release, we also need to merge #38546 to the release.

**Comment by emanueleusai** [comment]
wait does this mean you need #38546 deployed online as well? as it stands right now we just deployed #38499

**Comment by quark2** [comment]
> However, to stay on the safe side, I would suggest that this PR is only included in the online DQM release for 12_3_X, but not included in the central now closed release

@perrotta 
Can I ask where I can check the online/offline DQM release schedule?

**Comment by quark2** [comment]
@emanueleusai 
Exactly... Even it's more important than this PR.

**Comment by tvami** [comment]
@quark2 why didnt you add the commit https://github.com/cms-sw/cmssw/pull/38546/commits/a99221e5944edd56bb39cd060bf4efba6e0a9ccd to this PR?

**Comment by emanueleusai** [comment]
#38546 is not tagged as DQM (doesn't touch DQM code) nor it was mentioned here until a few minutes ago so we were completely unaware of this. In the future please let us know explicitly if you need some additional PR on top of the online release! ;)

**Comment by quark2** [comment]
I didn't take care enough of the new PR... I should make a notification. Sorry about that.

> @quark2 why didnt you add the commit [a99221e](https://github.com/cms-sw/cmssw/commit/a99221e5944edd56bb39cd060bf4efba6e0a9ccd) to this PR? (Is it just logically a very different change from what you change in this PR? )

The reason is explained well by @emanueleusai. The PR is for GEM unpacker. But it's quite related to GEM onlineDQM.

**Comment by quark2** [comment]
@emanueleusai 
Then is #38546 not able to be deployed to the onlineDQM release...?

**Comment by emanueleusai** [comment]
@quark2 #38546 and #38499 have been deployed online on top of 12_3_6 are you seeing any problems with the DQM plots in the GUI?

**Comment by quark2** [comment]
Hi @emanueleusai, 

It looks like everything works well (although the GUI layouts for GEM are not updated yet; we are working on it). Thanks!

**Comment by quark2** [comment]
Hi, 

It seems like this PR has passed all the tests but it is not merged. We expected to see the update to be deployed not only to onlineDQM but also to offlineDQM, and the results from the latest runs don't have it...

**Comment by pmandrik** [comment]
> Hi,
> 
> It seems like this PR has passed all the tests but it is not merged. We expected to see the update to be deployed not only to onlineDQM but also to offlineDQM, and the results from the latest runs don't have it...

Hi, changes to Offline will be propagated when new release of CMSSW with this PR will be installed to process events at Tier0.

**Comment by perrotta** [comment]
@quark2 @pmandrik

Short answer: this PR will not be merged in CMSSW_12_3_7

Longish answer:
- This PR [touches reco](https://github.com/cms-sw/cmssw/pull/38499#issuecomment-1169610620), even if in a rather light way: therefore, the rule says it will NOT be merged in the central CMSSW release of a stable cycle
- This was already agreed here [above](https://github.com/cms-sw/cmssw/pull/38499#issuecomment-1169631089) by @quark2
- Nonetheless, the discussion about the possibility to merge it in 12_3_X was repeated at the last ORP meeting: nobody spoke against it, neither the authors nor DQM; if you don't come at the release planning meeting where your PRs can be discussed, you cannot jump up at the last minute and ask to change a decision taken there

**Comment by quark2** [comment]
@perrotta 

Ahh, okay... I didn't know exactly what is the consequence of the decision at that time. Sorry for the confusion.

**Comment by qliphy** [comment]
hold
as discussed at recent several ORP meetings,  12_3_X is now deprecated.

**Comment by perrotta** [comment]
As anticipated already several times during the ORP meetings, the 12_2_X and 12_3_X queues must be considered as closed. We consequently close this longstanding and apparently unattended PR, in order to clean up the queue. Please feel free to reopen it (with a valid justification) if you really think that it should be still merged, instead.

**Pull request closed without merging**
