### PR TITLE
Moved ClusterRemovalRefSetter to TrackingTools/PatternTools

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

ClusterRemovalRefSetter depends on FWCore/Framework which is not an allowed dependency for a class in DataFormats.

TrackingTools/PatternTools was chosen based on what packages were already dependencies of the packages using ClusterRemovalRefSetter.

#### PR validation:

The code compiles.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
@davidlange6 FYI

**Comment by Dr15Jones** [comment]
please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/31749	932f49d 
- technical
- jenkins tests pass

**Comment by qliphy** [comment]
+1

**Pull request merged**
