### PR TITLE
Changes of geometry comparison tool backported from 75X

### PR DESCRIPTION
**Pull request by cschomak**
- Updates and bugfixes made in 75X backported
- relevant pull requests are 9200, 9204 and 9432
- Fixes bugs introduced by the use of extended alignment parameter errors
- Fixed bugs in ArrowPlots.C
- Added additional plots to compare the rotations of modules
- Created subfolder structure for a better overview over the plots

### CODE REVIEW

**Comment by diguida** [comment]
please test

**Comment by mmusich** [comment]
failures are unrelated to the PR

**Comment by diguida** [comment]
please test

**Comment by mmusich** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Comment by mmusich** [comment]
+1

**Pull request merged**
