### PR TITLE
Fix avoiding dqmofflineOnPAT_step duplications

### PR DESCRIPTION
**Pull request by jfernan2**
#### PR description:

Fix to avoid  duplicated sequences with dqmOffline_step for cmsDriver DQM:selections not defined in autoDQM or without PostDQM sequence

#### PR validation:

Tested with  runTheMatrix.py -l all -i all --ibeos

#### if this PR is a backport please specify the original PR:

No backport expected

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
hold
This change needs deeper research...

**Comment by fabiocos** [comment]
@jfernan2 I am afraid the changed in wf 11634.0 are not related to this PR but to some non reproducibility around since a week or so.

**Comment by jfernan2** [comment]
unhold

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
please test

**Comment by fabiocos** [comment]
@jfernan2 could you please point me to a pattern that would lead to the problem removed by this PR? Which test workflow is showing it?

**Comment by jfernan2** [comment]
@fabiocos  yes, this was spotted by @missirol duplication occurs for example in customized settings like:

cmsDriver.py step1 --conditions auto:phase1_2018_realistic     --customise Configuration/DataProcessing/Utils.addMonitoring     --datatier DQMIO --era Run2_2018 --eventcontent DQM --filein /store/relval/CMSSW_10_6_1/RelValTTbarLepton_13UP18/FEVTDEBUGHLT/PUpmx25ns_106X_upgrade2018_realistic_v6_ul18hlt_premix_hs-v1/20000/1A05F6A1-AE1B-724C-B9E2-A081DE805133.root     --geometry DB:Extended --mc --nThreads 1 --runUnscheduled --step     DQM:offlineHLTSourceOnAOD -n 100

**Comment by fabiocos** [comment]
+operations 

the use case mentioned by @jfernan2 is fixed, while the normal workflows look unaffected

**Comment by fabiocos** [comment]
+1

**Pull request merged**
