### PR TITLE
Change parameters for ECAL MLDQM [14_0_X]

### PR DESCRIPTION
**Pull request by abhih1**
#### PR description:

This PR changes certain parameters and thresholds for the ML based DQM quality plot in ECAL to better accommodate the high luminosity runs in 2024. 

#### PR validation:

The PR was validated by running the online Ecal DQM configuration and the resultant plots were examined by uploading the output file to a DQM test gui. The new plots look reasonable.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

This is a backport to 14_0_X which is currently used in production.  Master PR is https://github.com/cms-sw/cmssw/pull/44929

### CODE REVIEW

**Comment by tjavaid** [comment]
please test

**Comment by tjavaid** [comment]
backport of #44929

**Comment by tjavaid** [comment]
+1

- P5 tests OK
- spurious differences seen from unstable WF `12834.7` (open issue #39803 )

**Comment by rappoccio** [comment]
+1

**Pull request merged**
