### PR TITLE
SiStrip use LFN for unit test input

### PR DESCRIPTION
**Pull request by sroychow**
#### PR description:
This PR addresses issue #40097 
#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:
N/A

### CODE REVIEW

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by mmusich** [comment]
type trk, bug-fix

**Comment by mmusich** [comment]
resolves #40097

**Comment by sroychow** [comment]
please test

**Comment by tvami** [comment]
+alca
 * tests pass

**Pull request merged**
