### PR TITLE
remove obsolete CINT ifdef as it is no longer needed

### PR DESCRIPTION
**Pull request by davidlange6**
fixes (one) error seen in modules IB last night.

### CODE REVIEW

**Comment by davidlange6** [comment]
please test


On Jul 22, 2020, at 8:42 AM, cmsbuild <notifications@github.com<mailto:notifications@github.com>> wrote:



A new Pull Request was created by @davidlange6<https://github.com/davidlange6> (David Lange) for master.

It involves the following packages:

JetMETCorrections/JetCorrector

@perrotta<https://github.com/perrotta>, @jpata<https://github.com/jpata>, @cmsbuild<https://github.com/cmsbuild>, @santocch<https://github.com/santocch>, @slava77<https://github.com/slava77> can you please review it and eventually sign? Thanks.
@mmarionncern<https://github.com/mmarionncern>, @gouskos<https://github.com/gouskos>, @ahinzmann<https://github.com/ahinzmann>, @rappoccio<https://github.com/rappoccio>, @jdamgov<https://github.com/jdamgov>, @jdolen<https://github.com/jdolen>, @nhanvtran<https://github.com/nhanvtran>, @gkasieczka<https://github.com/gkasieczka>, @clelange<https://github.com/clelange>, @schoef<https://github.com/schoef>, @mariadalfonso<https://github.com/mariadalfonso>, @seemasharmafnal<https://github.com/seemasharmafnal> this is something you requested to watch as well.
@silviodonato<https://github.com/silviodonato>, @dpiparo<https://github.com/dpiparo> you are the release manager for this.

cms-bot commands are listed here<http://cms-sw.github.io/cms-bot-cmssw-cmds.html>

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/30869	be1cec2 
- technical
- jenkins tests pass with no differences in comparisons
- checked also with  CondFormats/JetMETObjects/test/TestCorrections.C to see that the JetCorrector still works interactively

**Comment by santocch** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
