### PR TITLE
[9_4_X] Egamma Fall17 V2 IDs

### PR DESCRIPTION
**Pull request by guitargeek**
Hi all,

this PR aims to backport the following Fall17 V2 IDs:
* Electron cut based (from https://github.com/cms-sw/cmssw/pull/23477)
* Electron MVA (from https://github.com/cms-sw/cmssw/pull/23700)
* Photon cut based and MVA (from https://github.com/cms-sw/cmssw/pull/25293)

__This PR depends on__ https://github.com/cms-sw/cmsdist/pull/4546 for updated weight files.

This backport is done in a "minimal" fashion, meaning the goal was just to get the same ID functionality as in master and not backporting the full list of technical improvements between 9_4_X and master.

For the cut based IDs, backporting with cherry-picks was trivial, while the MVAs were more involved with renamed weight files for all past MVAs. For this reason, all value maps produced by the Egamma MVA machinery were validated. As a reference, the most recent 10_4_X integration build was used for the Fall17 V2 MVAs and 9_4_12 for all other MVAs. All Egamma MVAs which can be possible configured in 9_4_X were validated, not only the ones activated in the MVAValueMapProducers.

Integrating the V2 electron MVA was not as trivial as expected as variables were ordered and defined slightly different compared to V1. For now, this was solved with branchings in the ElectronMVAEstimatorFall17 class.

Validation plots for all photon ID value maps:
https://rembserj.web.cern.ch/rembserj/plots/CMSSW_PRs/25408/

  * target: CMSSW_9_4_12 plus this PR and the external PR
  * reference: CMSSW_10_4_0_pre2 and CMSSW_9_4_12

Validation workflow:

  * Dump all relevant ID value maps to ROOT file with this configuration [1a,1b], running on DY+Jets
  * Compare ROOT file from reference and target with this script [2]

[1a] https://github.com/guitargeek/cmssw/blob/EgammaID_validation/RecoEgamma/EgammaTools/test/testElectronIDs_cfg.py
[1b] https://github.com/guitargeek/cmssw/blob/EgammaID_validation/RecoEgamma/EgammaTools/test/testPhotonIDs_cfg.py
[2] https://github.com/guitargeek/cmssw/blob/EgammaID_validation/RecoEgamma/EgammaTools/test/compare_columns.py

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by guitargeek** [comment]
Hi @perrotta, you have to test with the externals. Sorry, I should have referenced the needed externals at the en of the original post, as I have always done.

**Comment by perrotta** [comment]
abort tests

**Comment by perrotta** [comment]
Thank you @guitargeek . I should have remembered it, in fact, instead of automatically start tests...

**Comment by guitargeek** [comment]
@perrotta, I think the bot got stuck in limbo now, when looking at the terminal output...

**Comment by perrotta** [comment]
Uhm... No, I think the problem is that we can't run the central tests with two separate externals.

@smuzaffar @slava77 : could you please remind me how to deal with these cases? Should we wait that at least one of the external is merged? (If it has no counterindications, as it only adds new IDs, I would then suggest to merge them since now, and then we can go ahead testing this PR)

**Comment by guitargeek** [comment]
Sorry, that will not work, because in the external PRs we didn't only add the new IDs, but also gzipped the old weight files. So I suppose this PR has to be split up in electrons and photons, in case it will be confirmed that two external PRs are not possible to test with.

**Comment by slava77** [comment]
On 12/4/18 6:35 AM, Jonas Rembser wrote:
> Sorry, that will not work, because in the external PRs we didn't only
> add the new IDs, but also gzipped the old weight files. So I suppose
> this PR has to be split up in electrons and photons, in case it will be
> confirmed that two external PRs are not possible to test with.
> 
> —

just make a joint/merged backport of the externals

**Comment by guitargeek** [comment]
Haha, right! Why did I not think of that...

**Comment by guitargeek** [comment]
Alright @perrotta and @slava77, this PR now only depends on one external PR (see entry post).

I'm still laughing at my stupidity by the way.

**Comment by perrotta** [comment]
please test with  cms-sw/cmsdist#4546

**Comment by perrotta** [comment]
@guitargeek could you please provide here the same kind of validation plots that you prepared for the 10_2_X (here for both electron and photon ids). i.e.:
- comparison of the ids using latest 10_4_X as reference (to certify that the backport reproduce faithfully what integrated in the master);
- comparison of the old ids using 9_4_X as reference (to certify that none of the old ids got touched by this backport)

**Comment by guitargeek** [comment]
There you go @perrotta, I changed the plots behind the initial link to be separate for 9_4_X and 10_4_X references and to include the cut based IDs as well.

**Comment by perrotta** [comment]
Thank you @guitargeek !

**Comment by perrotta** [comment]
-1
- The validation plots provided show that the old IDs are not touched and the new ones faithfullly reproduce what already merged in the master. However, after some discussion with @fabiocos , we agreed that there was no real need to backport all this in a closed and stable old production release, As soon as #25372 willl get merged in 10_2_X, everything here will be available in a release which can be used since now for all analyses. Therefore, I'd suggest to get rid of this large backport and rather stick on 10_2 for retrieving the very same functionalities
- Please close this PR if you agree with it. Do not close it IF AND ONLY IF there are really strong physics motivations for having these functionalities in the old 9_4 (i.e. if for any reason 10_2 cannot be used instead) and this is worth the remote but non vanishing risk of jeopardizing a closed and stable release for it. PLease let us know in that case.

**Comment by guitargeek** [comment]
Many people use the Egamma V2 IDs in the 9_4_X release via one of my private branches right now, in particular the electron MVA.

The was I see it is that in reality most analyzers right now use 9_4_X with a lot of cms-merge-topics for their work. This way of working IMHO seriously harms reproducibility and has a large error surface. I think it even reduces analysis credibility since every cms-merge-topic of some random branch in a collaborators cmssw fork i a weak spot for any analysis, since one can't be sure how well it was validated.

Therefore, I think  that any backport that allows the analyzers to drop a merge-topic should be considered. We should definitely ask @Sam-Harper, @lsoffi,  @michelif and @swagata87 about this as well.

**Comment by perrotta** [comment]
What about telling those analyzers to move their analyses to 10_2?

Jonas Rembser <notifications@github.com> ha scritto:

**Comment by michelif** [comment]
Hi all,
Yes, of course, we reccomend analyses to move to 10_2 but many of them are still using 9_4 and are in advanced state. I understood at the meeting that we agreed on a minimal backport, only the ids and not the rest, to avoid conflicts and merge-topic manual recipes and make life easier. Of course at a certain point we expect everyone running at least in 10_2.

**Comment by Sam-Harper** [comment]
>What about telling those analyzers to move their analyses to 10_2?

Ha! I had a devil of a time trying to get them to 94X.  The problem here is that are targeting the less technical minded of the collaboration. The folks with strong technical skills already can easily merge the branches and/or have moved to 10_2. The less experienced technical folks have not and we are trying to make things easier for them

**Comment by Sam-Harper** [comment]
So to follow up on this, we will discuss in PPD coordination today about what release we recommend for 2017 analysis which is currently 9_4_X. We will report back on the outcome of this dicussion

**Comment by perrotta** [comment]
This PR is not just a backport (a selected part) of three PRs now merged in the master: it further adds many lines of brand new code needed to adapt these chunks of backports to the rest of 94X. This can be a dangerous exercise to be applied on top of a closed and supposedly stable release. Nevertheless, Physics and PPD coordinations are asking to try to integrate this PR in 94X for the sake of the physics analyses. Let try to restart the reco review, then.

The main differences I could spot with an eye inspection of the original and the backported/new code are the following:

- (#23477 was fully backported, no differences in the affected files)
- Modifications missing for (#23700)
  - RecoEgamma/EgammaTools/interface/AnyMVAEstimatorRun2Base.h
  - RecoEgamma/EgammaTools/interface/GBRForestTools.h + cc  -> Probably ok, new methods not used here
  - RecoEgamma/EgammaTools/interface/MVAVariableManager.h
  - RecoEgamma/EgammaTools/python/egammaObjectModificationsInMiniAOD_cff.py  -> OK, just refactorized
  - RecoEgamma/ElectronIdentification/BuildFile.xml -> OK, just minor cleaning
  - RecoEgamma/ElectronIdentification/data/ElectronIDVariables.txt -> together with MVAVariableManager
  - RecoEgamma/ElectronIdentification/data/ElectronMVAEstimatorRun2Fall17V1Variables.txt -> together with MVAVariableManager
  - RecoEgamma/ElectronIdentification/data/ElectronMVAEstimatorRun2Variables.txt -> together with MVAVariableManager
  - RecoEgamma/ElectronIdentification/interface/ElectronMVAEstimatorRun2.h + .cc -> (it replaces the specific ElectronMVAEstimator's)
  - RecoEgamma/ElectronIdentification/interface/ElectronMVAVariableHelper.h + .cc
  - RecoEgamma/ElectronIdentification/plugins/BuildFile.xml -> OK, just minor cleaning
  - RecoEgamma/ElectronIdentification/plugins/ElectronMVANtuplizer.cc -> Ok, new ntuplizer
  - RecoEgamma/ElectronIdentification/plugins/cuts/GsfEleMVACut.cc -> Maybe ok (cut string used in master instead)
  - RecoEgamma/ElectronIdentification/plugins/cuts/GsfEleMVAExpoScalingCut.cc -> OK, just removed
  - RecoEgamma/ElectronIdentification/python/ElectronMVAValueMapProducer_cfi.py -> Ok, it is for the helper
  - RecoEgamma/ElectronIdentification/python/Identification/mvaElectronID_Fall17_iso_V1_cff.py + V2 + noIso +Spring15 + Spring16
  - RecoEgamma/ElectronIdentification/python/Identification/mvaElectronID_tools.py
  - RecoEgamma/ElectronIdentification/python/Training/ElectronMVANtuplizer_cfg.py
  - RecoEgamma/ElectronIdentification/python/egmGsfElectronIDs_cff.py -> Ok, it just adds the electronMVAVariableHelper module
  - RecoEgamma/ElectronIdentification/python/Identification/mvaElectronID_Fall17_iso_V2_cff.py -> Likely correct backport, but hard to evaluate
    - Same for noIso
  - RecoEgamma/PhotonIdentification/data/*.txt -> Ok, new data
  - RecoEgamma/PhotonIdentification/interface/PhotonMVAEstimator.h
  - RecoEgamma/PhotonIdentification/plugins/PhotonIDValueMapProducer.cc
  - RecoEgamma/PhotonIdentification/plugins/PhotonMVAEstimator -> OK, used the GBRForestTools::createGBRForest() instead of a local createSingleReader()
  - RecoEgamma/PhotonIdentification/plugins/PhotonMVANtuplizer.cc -> Ok, new ntuplizer
  - RecoEgamma/PhotonIdentification/test/testPhotonMVA_cfg.py
- Additional modified files for #25408
  - RecoEgamma/ElectronIdentification/python/Identification/mvaElectronID_PHYS14_PU20bx25_nonTrig_V1_cff.py -> gzipped data is ok? Yes, this file does not exist in newer releases
  - RecoEgamma/PhotonIdentification/test/testPhotonMVA_cfg.py -> ok, this test was not there in 94X

Validation plots provided and linked in the PR description show a nice agreement for all photon and electron ids, and this is reassuring. In any case, please @guitargeek go through the list of all differences I spotted in the code, and check whether there is anything that doesn't sound correct to you

I have removed the reco "-1" by now, so that this PR can re-appear on our list and a decision about a possible backport can be taken.

**Comment by guitargeek** [comment]
Hi @perrotta, there is not much more I can add to your detailed comment! I also checked that all the gzipped weight files are in the most recent version of [1], even for disabled IDs like the PHYS14 one.

The differences #23700 are all intended and related to the new MVA infrastructure that was decided to not backport completely.

[1] https://github.com/cms-data/RecoEgamma-ElectronIdentification/tree/master/PHYS14

**Comment by perrotta** [comment]
please test with cms-sw/cmsdist#4546

**Comment by perrotta** [comment]
+1
- This PR is not just a backport of (a selected part) of three PRs now merged in the master: it further adds several lines of brand new code needed to adapt these chunks of backports to the rest of 94X. This is potentially a dangerous exercise to be applied on top of a closed and supposedly stable release.
- However, after a detailed inspection of the code submitted I believe that the porting was done correctly, and that the parts of code that were not backported are all intended and related to the new MVA infrastructure that was decided to not backport completely (thank you @guitargeek for having checked it twice and confirmed)
- As a further confirmation, the validation plots provided show a nice agreement for all photon and electron ids: the ones that were already in 94X are not changed, and the outputs of the newly added ones correspond to the output of the same ids merged in the master
- Jenkins tests do not show other differences besides the additional ids in all miniAOD outputs
- It also needs cms-sw/cmsdist#4546 to be  merged

**Comment by perrotta** [comment]
@fabiocos this PR do not modify existing reco or miniAOD content, but it adds the one corresponding to the new ids. Should we require that the new ids are only added conditionally to a (era driven?) flag, as we requested in other similar cases?

**Comment by guitargeek** [comment]
@perrotta another possibility is to just not ass the ID to miniAOD, since it will be used for analysis and not production.

**Comment by fabiocos** [comment]
@guitargeek @perrotta I think we should use the same approach as before, so add the new information conditionally (or only to analysis/nanoaod) so as to avoid creating mixed situations in possible MC processing

**Comment by perrotta** [comment]
I agree.
Going to remove the "+1" while waiting for this update.

Fabio Cossutti <notifications@github.com> ha scritto:

**Comment by guitargeek** [comment]
So conditionally? WIth toModify? Which era should I use then,  @fabiocos, @perrotta? Thanks!

**Comment by perrotta** [comment]
@fabiocos : would you suggest using any of the existing eras as in Configuration/StandardSequences/python/Eras.py, or to define a brand new one instead?

**Comment by slava77** [comment]
On 1/15/19 4:49 AM, perrotta wrote:
> @fabiocos
> : would you suggest using any of the existing eras as in
> Configuration/StandardSequences/python/Eras.py, or to define a brand new
> one instead?
> 
> —

perhaps the same solution as used in 10_2_X can be used?
run2_miniAOD_devel

**Comment by Sam-Harper** [comment]
So one thing on this, I'm a little confused and am concerned that different parts of CMS are hearing different things. At the time of the PR, there was no policy that all analyses had to use 102X and I raised the issue that this was creating such a policy which I felt needed to be discussed amoungst a wider audience.  I am of course sympathetic to the release stability concerns.  

Now we seem to have a new policy enacted from physics coordination which says there will be no backports to 94X  and "POGs and PAG analysts should move to CMSSW_10_2_X (from
CMSWW_9_4_X) as the analysis release" (see slide 8 of https://indico.cern.ch/event/788381/contributions/3275680/attachments/1777972/2891342/pc-20190116-v1.pdf)

In light of this, do we want to do this backport? I wanted this backport when 94X was still a recommended release and there was no central push to move analyses to 102X. Now there is a policy here, this swings back to not needing this PR.  My concern before was say POG X saying use 102X, POG Y saying use 94X etc but now that has been resolved.

**Comment by fabiocos** [comment]
@Sam-Harper there has been a discussion with Physics Coordination and XPOG about what to do for analysis code backports, that was also recalled at the ORP meeting. In the medium - long term I think we agreed to try to move as much as possible the analysis activity towards a more modern release, 10_2_X, or report which are the code show-stoppers that prevent to do this. Analyses close to converge should not be asked for such a move of course (at least for what I am concerned from the release point of view), those with a long way to go in front of them could/should in my view consider doing the effort to move forward towards a more up-to-date code base. 

On the other hand this backport was already available, you were complaining about its non integration, and I agreed with @perrotta to move forward with it, as part of the non-trivial job was already done. What I would like to avoid is to continue this kind of backports in 9_4_X unless there is a compelling reason for them.

**Comment by Sam-Harper** [comment]
@fabiocos , thank you and thank you @perrotta  for this. Indeed the situation seemed to be clarified at PC, the slides didnt capture the full meaning expressed.

**Comment by guitargeek** [comment]
Pardon me @Sam-Harper and @fabiocos, I did not understand if there is any action from my side required here now. Should I close this, remove the ID from MiniAOD, add a modifier (if yes, which one?) or just do nothing?

**Comment by perrotta** [comment]
@guitargeek : if we agree on eventualy merging this PR the same conditional inclusion of the new IDs in miniAOD as you already did in https://github.com/cms-sw/cmssw/pull/25372/files#diff-76dede28e7751d7bb6c5c9542de4155cR330 should be provided here, i.e. make it dependent on the ```run2_miniAOD_devel``` era

**Comment by fabiocos** [comment]
@guitargeek I confirm what @perrotta says

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
please abort

**Comment by perrotta** [comment]
please test with cms-sw/cmsdist#4546

**Comment by perrotta** [comment]
@mrodozov @smuzaffar : sorry to bother you again, but this is re-happening: https://github.com/cms-sw/cmssw/pull/25408#issuecomment-456720943

Is there anything we can do for it (e.g. keep trying ), or it is something that only you can solve?

**Comment by smuzaffar** [comment]
@perrotta , may be our mirror in /cvmfs (which is used as reference) is causing this error. For now I  have added some debug statements to see where is error happens.
I have restarted the tests.

**Comment by perrotta** [comment]
Thank you Shahzad!

Malik Shahzad Muzaffar <notifications@github.com> ha scritto:

**Comment by perrotta** [comment]
+1
- Since the reco signature in  https://github.com/cms-sw/cmssw/pull/25408#issuecomment-453910264 a conditional inclusion of the Fall17 V2 Egamma IDs only for the ```run2_miniAOD_devel``` modifier was implemented. No effect is visible now on jenkins tests, as it should. I repeat below the same comments written for the previous signature.
- This PR is not just a backport of (a selected part) of three PRs now merged in the master: it further adds several lines of brand new code needed to adapt these chunks of backports to the rest of 94X. This is potentially a dangerous exercise to be applied on top of a closed and supposedly stable release.
- However, after a detailed inspection of the code submitted I believe that the porting was done correctly, and that the parts of code that were not backported are all intended and related to the new MVA infrastructure that was decided to not backport completely (thank you @guitargeek for having checked it twice and confirmed)
- As a further confirmation, the validation plots provided show a nice agreement for all photon and electron ids: the ones that were already in 94X are not changed, and the outputs of the newly added ones correspond to the output of the same ids merged in the master (now only in correspondence of the 
```run2_miniAOD_devel``` modifier)
- When the ```run2_miniAOD_devel``` modifier is enabled the jenkins tests do not show other differences besides the additional ids in all miniAOD outputs
- It also needs cms-sw/cmsdist#4546 to be merged

**Comment by fabiocos** [comment]
+operations

the modification to Eras and StandardSequences is coherent with the purpose of the PR

**Comment by fabiocos** [comment]
@smuzaffar we need to merge cms-sw/cmsdist#4546 before merging this PR. Some older files are replaced by new ones, so I would merge this later this evening to minimize the risk of problems (although the development activity on the 9_4_X branch is reduced)

**Comment by smuzaffar** [comment]
@fabiocos , https://github.com/cms-sw/cmsdist/pull/4546 is merged now

**Comment by fabiocos** [comment]
+1

@smuzaffar thanks

**Comment by fabiocos** [comment]
merge

**Pull request merged**
