### PR TITLE
[14_1_X] Extend lowPt egamma modifier to conversions

### PR DESCRIPTION
**Pull request by stahlleiton**
#### PR description:

Backport of https://github.com/cms-sw/cmssw/pull/46485 
done on top of PR: https://github.com/cms-sw/cmssw/pull/46477

@mandrenguyen 

#### PR validation:

runTheMatrix.py -l 180,180.1,181,181.1  with PR https://github.com/cms-sw/cmssw/pull/46477

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by mandrenguyen** [comment]
backport of https://github.com/cms-sw/cmssw/pull/46485

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
