### PR TITLE
Single lq filter 76 x

### PR DESCRIPTION
**Pull request by dnash86**
This is the single LQ gen filter, it will be needed in 71X releases for GEN-SIM.  Backport PR to be sent as well.

### CODE REVIEW

**Comment by covarell** [comment]
These filters look really trivial... Why cannot they be realized using (chains of) the existing GenFilters? E.g.:
https://github.com/cms-sw/cmssw/blob/CMSSW_7_6_X/GeneratorInterface/GenFilters/src/MCParticlePairFilter.cc

**Comment by dnash86** [comment]
The filters certainly are trivial in comparison to that one, they were based off of https://github.com/cms-sw/cmssw/blob/CMSSW_7_6_X/GeneratorInterface/GenFilters/src/LQGenFilter.cc

I guess we will check the MCParticlePairFilter, test with it, and then possibly close this PR.

**Comment by dnash86** [comment]
@covarell What do you mean by "chains of"?  Could we require all passing events to have a pair of status 23 electrons by configuring the MCParticlePairFilter this way:

examplesinglelqfilter = cms.EDFilter("MCParticlePairFilter",
     Status = cms.untracked.vint32(23,23),
     MinPt = cms.untracked.vdouble(0., 0.),
     MinP = cms.untracked.vdouble(0., 0.),
     MaxEta = cms.untracked.vdouble(100., 100.),
     MinEta = cms.untracked.vdouble(-100, -100),
     ParticleID1 = cms.untracked.vint32(11),
     ParticleID2 = cms.untracked.vint32(11)
 )

If it is indeed that simple, then we certainly do not need this PR.

**Comment by covarell** [comment]
-1

**Pull request closed without merging**
