### PR TITLE
Alignment: use ClassDefOverride instead of ClassDef to avoid inconsistent-missing-override warning

### PR DESCRIPTION
**Pull request by smuzaffar**

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by ghellwig** [comment]
@smuzaffar I assume the trailing `Override` is too much, right?

**Comment by smuzaffar** [comment]
oops, yes pasted on wrong place @ghellwig . It is fixed now

**Comment by smuzaffar** [comment]
please test

**Comment by ghellwig** [comment]
+1
provided jenkins agrees

**Comment by davidlange6** [comment]
+1

**Pull request merged**
