### PR TITLE
Reduce boost dependency in CalibCalorimetry/EcalLaserSorting

### PR DESCRIPTION
**Pull request by camolezi**
#### PR description:
Changed boost::ptr_list for std::list<std::unique_ptr<>>.
The code should have the same behavior and also similar performance. 

#### PR validation:
Passed on basic runTheMatrix test.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

@vgvassilev @davidlange6

### CODE REVIEW

**Comment by christopheralanwest** [comment]
please test

**Comment by christopheralanwest** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
