### PR TITLE
Require  highPurity for isolated tracks in heavy-ion workflows

### PR DESCRIPTION
**Pull request by mandrenguyen**
#### PR description:

In #31647 it was pointed out that isolatedTracks has a high CPU consumption in central heavy-ion events.  
This PR requires that only highPurity tracks are considered, which cuts the timing by a factor of 4 in wf 140.5611 
Non-highPurity tracks have a rather large fake rate and are not used for many purposes. 

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by jpata** [comment]
PF group @bendavid @hatakeyamak let us know if you think this function is still needed?

**Comment by jpata** [comment]
Thanks Matt for this PR and Slava for running the tests. It looks like the only reco differences are in the HI workflow 158.01, with a reduction in tracks as expected. 

https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_11_2_X_2020-10-08-2300+b1e6ab/39223/validateJR/all_OldVSNew_HydjetQB12ppRECOin2018reMINIAODwf158p01/all_OldVSNew_HydjetQB12ppRECOin2018reMINIAODwf158p01c_log10patIsolatedTracks_isolatedTracks__DQM_obj_pt.png
image

https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_11_2_X_2020-10-08-2300+b1e6ab/39223/validateJR/all_OldVSNew_HydjetQB12ppRECOin2018reMINIAODwf158p01/all_OldVSNew_HydjetQB12ppRECOin2018reMINIAODwf158p01c_patIsolatedTracks_isolatedTracks__DQM_obj_isHighPurityTrack.png
image

If these low-purity tracks are not used by HI as you say, then this change is lightweight and I think very welcome. I have no comments on the code, it looks fine as it is. I notice there are no `fillDescriptions` for the producer, but maybe they are hidden somewhere with inheritance.

@mandrenguyen can you comment if you expect any retuning of downstream track-dependent quantities in HI from this?

**Comment by mandrenguyen** [comment]
@jpata It doesn't appear any downstream modules in miniAOD consume isolatedTracks.   I'm not really sure what this collection is used for, honestly.   I do see in LXR that it's used  in a muon POG skim, perhaps they are the main customer?   Presumably no one has ever used this collection in PbPb events, since we haven't yet ever produced miniAOD.

**Comment by jpata** [comment]
OK, thanks for the clarifications. In this case, I only see a possible issue that it's adding extra functionality to the PATIsolatedTrackProducer which could perhaps also be achieved in the HI workflows by adding a PATObjectSelector in front of isolatedTracks. This would help to decouple functionality between various modules and perhaps be more modular.

**Comment by slava77** [comment]
> OK, thanks for the clarifications. In this case, I only see a possible issue that it's adding extra functionality to the PATIsolatedTrackProducer which could perhaps also be achieved in the HI workflows by adding a PATObjectSelector in front of isolatedTracks. This would help to decouple functionality between various modules and perhaps be more modular.

IIRC, isolatedTracks from the start had somewhat elaborate selections in the producer itself.
@jpata 
Is your point to move out all of the selections out of PhysicsTools/PatAlgos/plugins/PATIsolatedTrackProducer.cc or just for this HP track selection?
For the latter, it seems like too much of an overhead.
Either way, I recall that the module relies on Ref/Ptr information between multiple collections; so, having a skimmed/thinned collection as input may end up complicating the logic of the producer itself and making the combination much more complex.

**Comment by mandrenguyen** [comment]
@jpata We create a collection called highPurityGeneralTracks using TrackSelector.  However, when I use it as input to isolatedTracks, I get the error 
ValueMap: no associated value for given product and index

I believe that comes from the fact that particle flow uses the full generalTracks as input.

**Comment by mandrenguyen** [comment]
> IIRC, isolatedTracks from the start had somewhat elaborate selections in the producer itself.

It looks like you can hand it a string as a selection, but that's only for the dE/dx part of the code.

**Comment by jpata** [comment]
OK good, thanks for the checks, then I see no reason to go forward as implemented and tested already here.

**Comment by jpata** [comment]
+reconstruction

- introduces new boolean `useHighPurity` for `PATIsolatedTrackProducer`
- the default settings do not affect any workflows
- enabled for HI workflows, in which case, only tracks passing high purity selection are used
- we see only the expected reco differences, only in HI workflows

**Comment by santocch** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
