### PR TITLE
change L1T DQM QTest for stage1 and include stage1 HI run configuration 

### PR DESCRIPTION
**Pull request by jingyucms**
New PR for stage1 pp layout change and stage1 HIon monitoring. To replace PR11756

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1
provided it passes the tests

**Comment by mulhearn** [comment]
+1

**Comment by jingyucms** [comment]
@slava77 76x version for #11777 and #11923

**Comment by deguio** [comment]
please test
I believe this one is final. @jingyucms please confirm.
thanks,
F.

**Comment by deguio** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by mulhearn** [comment]
+1

**Comment by jingyucms** [comment]
Yes this one is final. @deguio @mulhearn

**Comment by jingyucms** [comment]
@davidlange6 Can this merge?

**Comment by davidlange6** [comment]
I am cleaning up the 76x queue aside from things for analysis workflows. I'm closing this pull request, please make sure the PR is in 80x. Thanks!

**Pull request closed without merging**
