### PR TITLE
bsunanda:Run2-alca47 Missed out changes in the parameter values for the IsoTrack producers (done correctly for 8_0_X version)

### PR DESCRIPTION
**Pull request by bsunanda**
Some of the changes in the parameter values for HcalIsolatedTrackReco were missed out for 8_1_X (OK in 8_0_X). Also the default description in the trigger were made to match with what is in the HLT menu.

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by mmusich** [comment]
+1

**Comment by davidlange6** [comment]
@bsunanda - please change the title of this PR to be more descriptive of the actual change. Thanks!

**Comment by bsunanda** [comment]
@davidlange6 Changed the title

**Pull request merged**
