### PR TITLE
Geant4 tracking in magnetic field parameters

### PR DESCRIPTION
**Pull request by civanch**
#### PR description:
Configuration of Geant4 tracking in magnetic field includes now 3 areas:
1) relativistic tracks (E > 200 MeV) inside central CMS
2) low-energy tracks (E < 20 MeV)
3) remaining tracks
Such configuration ensure unbiased simulation trajectories for relativistic tracks (bias below 0.1 micron for tracker hits) and do not bring extra CPU penalty and extra Geant4 tracking problems. Detailed discussion on the problem is in #31665.

This PR change simulation histories, so many differences are expected in MC WFs.

#### PR validation:
private

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

@silviodonato, @qliphy, let us discuss at the release meeting this PR: when it is the best time to merge it.

**Comment by silviodonato** [comment]
hold
see https://github.com/cms-sw/cmssw/pull/32063#issuecomment-724586188

**Comment by silviodonato** [comment]
unhold

**Comment by silviodonato** [comment]
+1
@cms-sw/pdmv-l2 FYI this PR will be the cause of the statistic fluctuation in pre9 validation

**Pull request merged**
