### PR TITLE
PR 101X l1To2o fixes in EMTF and BMTF

### PR DESCRIPTION
**Pull request by gekobs**
**PR 101X**
This PR contains:
- PR #20929
- PR #22669
- A small change in fakeEmtfParams_cff.py that allows running on conddb machines at P5.

### CODE REVIEW

**Comment by rekovic** [comment]
please test

**Comment by fabiocos** [comment]
please test

**Comment by rekovic** [comment]
This is now tested on the CondDB machines running L1T O2O (in directory `/data/O2O/L1T/v12.1/`) in the offline mode writing to sqlite file.  The results are as expected:
- BMTF and OMTF tags are updated to Stage2v1
- Proper masking of DT channels done in BMTF depending if key is cosmics or p-p.

We plan to move `/data/O2O/L1T/v12.1/` into production tomorrow.

**Comment by rekovic** [comment]
+1

**Comment by ggovi** [comment]
+1

**Comment by thomreis** [comment]
This PR contains also commits from #20939, not #20929 as mentioned in the description.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
