### PR TITLE
Introduce new utilities for writing Alpaka kernels [13.3.x]

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Introduce four new utilities for writing Alpaka kernels:
  - `blocks_with_stride(acc, size)`
  - `elements_in_block(acc, block, size)`
  - `once_per_grid(acc)`
  - `once_per_block(acc)`

Simplify the unit tests, and extend them to cover the newly introduced functionality.

---

##### blocks_with_stride

`blocks_with_stride(acc, size)` returns a range than spans the (virtual) block indices required to cover the given problem size.

For example, if size is 1000 and the block size is 16, it will return the range from 0 to 62 (63 blocks of 16 elements covers 1008 elements, enough for a total size of 1000).
If the work division has more than 63 blocks, only the first 63 will perform one iteration of the loop, and the other will exit immediately.
If the work division has less than 63 blocks, some of the blocks will perform more than one iteration, in order to cover then whole problem space.

All threads in a block see the same loop iterations, while threads in different blocks may see a different number of iterations.

##### elements_in_block

`elements_in_block(acc, block, size)` returns a range that spans all the elements within the given block. Iterating over the range yields values of type `ElementIndex`, that contain both `.global` and `.local` indices of the corresponding element.

If the work division has only one element per thread, the loop will perform at most one iteration.
If the work division has more than one elements per thread, the loop will perform that number of iterations, or less if it reaches size.

##### once_per_grid

`once_per_grid(acc)` evaluates to true for a single thread within the kernel execution grid.

Usually the condition is true for block 0 and thread 0, but these indices should not be relied upon.

##### once_per_block

`once_per_block(acc)` evaluates to true for a single thread within the block.

Usually the condition is true for thread 0, but this index should not be relied upon.

#### PR validation:

The updated unit tests compile and pass.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport of #43205 to `CMSSW_13_3_X`.

### CODE REVIEW

**Comment by fwyzard** [comment]
backport #43205

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
+heterogeneous

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
