### PR TITLE
HLT migration to 12_3_0_pre1

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
#### PR description:

HLT migration to 12_3_0_pre1
(plus some ALCAPPS bug fixes)

#### PR validation:

TSG tests

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by perrotta** [comment]
@Martin-Grunewald which is the purpose of migrating to 12_3_0_pre1, which is absolutely identical to 12_2_0_pre3?

**Comment by Martin-Grunewald** [comment]
It is for the 12_3 release series - also, I had hoped the 12_2_0_pre3 migration would have gotten in before the 12_3 was opened, but that was not the case.

**Comment by Martin-Grunewald** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
