### PR TITLE
[13.2.X] Add `SiStripApproximateClusterCollection` as a simple format for RAW 

### PR DESCRIPTION
**Pull request by mmusich**
backport of https://github.com/cms-sw/cmssw/pull/42495

#### PR description:

Based on the issue "Dataformat compatibility issue for HI SiStrip cluster in RAW" (https://github.com/cms-sw/cmssw/issues/39106)

Aim: changing Data-format (`edmNew::DetSetVector`) in RAW to be simple-enough for infinite backwards compatibility. -> It has to be readable by all future CMSSW releases.
Re-defining the corresponding final data-types directly in the ApproximatedClusters.
Need to be straightforward to convert from `edmNew::DetSetVector`.

The simplified data format has updated (recommended by Matti in 2022 Sep)
(https://github.com/cms-sw/cmssw/compare/master...makortel:cmssw:siStripApproximateClusterCollection_v2)

Target : 13_2_X release for the 2023 HeavyIon data-taking.
#### PR validation:

Tested in `CMSSW_13_3_X_2023-08-02-1100`, the basic test passed in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html):
   *  passes `runTheMatrix.py -l 140.58 -t 4 -j 8 --ibeos`

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Verbatim backport of https://github.com/cms-sw/cmssw/pull/42495 to be used for 2023 Heavy Ion data-taking

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mandrenguyen** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

From the upgrade side, only removing workflow and step.

**Comment by sunilUIET** [comment]
+pdmv

**Comment by perrotta** [comment]
+1

**Pull request merged**
