### PR TITLE
Run3-alca185 Rearrange the file HcalHBHEMuonSimAnalyzer and remove duplication

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Rearrange the file HcalHBHEMuonSimAnalyzer and remove duplication

#### PR validation:

Tested by using the application on MC file

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by qliphy** [comment]
Thanks @bsunanda for  this fix for https://github.com/cms-sw/cmssw/issues/33896

**Comment by qliphy** [comment]
please test

**Comment by qliphy** [comment]
@bsunanda  HcalHBHEMuonSimAnalyzer should also be removed from https://github.com/cms-sw/cmssw/blob/master/Calibration/IsolatedParticles/plugins/BuildFile.xml#L73-L74

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by qliphy** [comment]
kindly ping @cms-sw/alca-l2 
this is fix the issue https://github.com/cms-sw/cmssw/issues/33896

**Comment by yuanchao** [comment]
+1
* HcalHBHEMuonSimAnalyzer rearrange and remove duplication
* build warnings not due to this analyzer

**Comment by qliphy** [comment]
+1

**Pull request merged**
