### PR TITLE
(DAQ) Streamer output unit test and removal of the old output module (master/12_4_X)

### PR DESCRIPTION
**Pull request by smorovic**
#### PR description:

- New unit test does additional check with output HLT results stored in streamer header with the DQM streamer source. Also merged two scripts for the unit test and other test which can't run as unit test.
- Removal of the ShmStreamConsumer module which is obsolete and no longer used in production DAQ/HLT. Removes references also in cfi files.

#### PR validation:

Covered by the included unit test.

### CODE REVIEW

**Comment by smorovic** [comment]
@cmsbuild please test

**Comment by smorovic** [comment]
+1

**Comment by jfernan2** [comment]
+1

**Comment by qliphy** [comment]
+EvFDaqDirector1

**Comment by qliphy** [comment]
+1

**Pull request merged**
