### PR TITLE
[DQM] Fix for DQM merging exception due to duplicated labels 12_2_X

### PR DESCRIPTION
**Pull request by jfernan2**
#### PR description:
Backport of https://github.com/cms-sw/cmssw/pull/36778

This PR fixes the crash in DQM merging due to duplicated lables reported on:
https://hypernews.cern.ch/HyperNews/CMS/get/tier0-Ops/2328/1/1/1/1/1.html

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by perrotta** [comment]
backport of #36778

**Comment by tvami** [comment]
Type bug-fix

**Comment by jfernan2** [comment]
+1

**Comment by perrotta** [comment]
+1

**Comment by perrotta** [comment]
merge

**Pull request merged**
