### PR TITLE
add feds

### PR DESCRIPTION
**Pull request by elaird**
This PR (for 75X) contains a cherry-picked commit from the merged 73X PR: https://github.com/cms-sw/cmssw/pull/8223

CC: @abdoulline

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test
@nclopezo is bot asleep?
@elaird is this change in 74X as well?

**Comment by elaird** [comment]
@slava77 the 74X PR is here: https://github.com/cms-sw/cmssw/pull/8689

**Comment by nclopezo** [comment]
Hi Slava,
Yes, there are some issues with mesos. I ran it by hand and @cmsbuild read this PR.

**Comment by slava77** [comment]
@cmsbuild please test

there are a lot seemingly unrelated differences (in fastsim workflows; in 4.53)
try to rerun to get it clean

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/8688	46b6a48

 the same code changes were signed off and tested in 73X in #8223

**Comment by slava77** [comment]
@cmsbuild @nclopezo @degano 
rerunning the tests helped partially: not 140.53 shows up with a lot of differences (another das glitch?)
It sounds like we can't get the same list of files from das by repeating a query after a few hours.
We will need some check or that step1_dbsquery files match in baseline and the comparison.

**Comment by davidlange6** [comment]
@slava77 - the check you suggest belongs in cmsDriver not in the IB system if reproducibility of the file list is a desirable feature (seems like it should be)

**Comment by slava77** [comment]
Hi David,
cmsDriver knows nothing about having to compare A with B. That's why I think the check of exceptions between two passes (baseline and PR+baseline) used in jenkins for comparisons belong in the comparison machinery.

**Comment by davidlange6** [comment]
Either the das output is expected to be the same or not when run a few hours/days apart. if yes, then seeing a difference is a sign of a bug (not in the IB system) that we should fix at it source. if not, then we don’t expect reproducibility when comparing A with B. 

Since the relval_steps command does a sort which intents to make things reproducible, then I guess there is a bug? Perhaps we just need a —limit=0 to get all the results. 

Which workflow shows the difference?

**Comment by slava77** [comment]
it happens for different workflows
apparently the behavior is occasionally a das query returns a smaller total number of files; after the sort this turns into different files produced.
Other than forcing cmsDriver to know which files it should run, there's no way to distinguish an accidental failure from a change in the dataset content.

I'm only asking for the comparison script(s) to inform that the inputs were different. The operator will have to decide what to do, to request another test or not.

**Comment by davidlange6** [comment]
> On Apr 13, 2015, at 5:19 AM, Slava Krutelyov <notifications@github.com> wrote:
> 
> it happens for different workflows
> apparently the behavior is occasionally a das query returns a smaller total number of files; after the sort this turns into different files produced.
> Other than forcing cmsDriver to know which files it should run, there's no way to distinguish an accidental failure from a change in the dataset content.
> 
> I'm only asking for the comparison script(s) to inform that the inputs were different. The operator will have to decide what to do, to request another test or not.

I meant which workflow shows the problem in this PR? I’d like to see what fails - If das is not giving the same results when called repeatedly if the data is still there at CERN and we aren’t just hitting the number of files to return maximum, that is a bug to report. I presume it has not been..

Other than being the bug of the moment, I’m not sure why this would be something to flag (as this quickly would fail to scale in code maintenance). If we’ve understood it to be a das feature rather than bug, then we can revisit.

David

**Comment by slava77** [comment]
140.53 in the test of https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-8688/4174/summary.html

**Comment by slava77** [comment]
and 4.53 in https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-8688/4154/summary.html

**Comment by davidlange6** [comment]
Thanks

Naively, the output of 

https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_7_5_X_2015-04-11-1100+8688/7089/files/4.53_RunPhoton2012B+RunPhoton2012B+HLTD+RECODreHLT+HARVESTDreHLT+MINIAODDreHLT/CMSSW_7_5_X_2015-04-11-1100-step1_dasquery.log

is surprising to me..

**Comment by davidlange6** [comment]
+1

**Pull request merged**
