### PR TITLE
solve mg5 tmpdir problem from ExternalLHEProducer

### PR DESCRIPTION
**Pull request by perrozzi**
10_1_X needed for Summer18 samples...

### CODE REVIEW

**Comment by perrozzi** [comment]
backport of https://github.com/cms-sw/cmssw/pull/23004

**Comment by perrozzi** [comment]
+1

**Comment by perrozzi** [comment]
Hi, also in this case a patch release would be very welcome as 10_1 is used for 2018 POG samples (currently in production) with Summer18 campaign...

**Comment by fabiocos** [comment]
+1

**Comment by efeyazgan** [comment]
@fabiocos  when is a patch release forseen? This will make GEN's life easier for summer18 requests. Thanks.

**Pull request merged**
