### PR TITLE
bsunanda:Run2-hcx37    Update the hit validation package to match Phase2 simulation

### PR DESCRIPTION
**Pull request by bsunanda**
Accommodate variable number of depths

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
-1
ciao @bsunanda 
this doesn't merge anymore...
could you please rebase?
thanks,
F.

**Comment by bsunanda** [comment]
@deguo It merges with CMSSW_7_6_X_2015-10-06-2300. Which IB shall I try?

**Comment by bsunanda** [comment]
Which IB shall I test against?
________________________________

**Comment by bsunanda** [comment]
When I want to push after resolving conflict, committing and rebasing I get the error:
error: src refspec HEAD/Run2-hcx37 does not match any.
error: failed to push some refs to 'git@github.com:bsunanda/cmssw.git'
@deguio please suggest how to resolve
________________________________
From: Sunanda Banerjee
Sent: 07 October 2015 12:12
To: cms-sw/cmssw; cms-sw/cmssw
Subject: RE: [cmssw] bsunanda:Run2-hcx37 Update the hit validation package to match Phase2 simulation (#11634)

Which IB shall I test against?
________________________________

**Pull request closed without merging**
