### PR TITLE
11.1.X  [Tracker Alignment] All-in-one tool support of multiple tags in user-inputed sqlite file

### PR DESCRIPTION
**Pull request by mmusich**
backport of  #30077

#### PR description:

In this commit: https://github.com/cms-sw/cmssw/commit/ca150f34c8908b194219de64eb4b2fa16ac06491 we introduced a new method in order to read local sqlite files in the tracker alignment all-in-one tool, by using `conddblib` to check contents of sqlite files.
In the original implementation in PR #29339 I did not foresee to put more than one tag into a local sqlite file, but this appears to be a required use case.
The issue and the fix have been provided by @adewit.
I profit of this PR also to update the unit test to cover this use-case. 

#### PR validation:

Relies on the existing unit test in the subsystem. I have tested this in `CMSSW_11_1_X_2020-06-02-1100`

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

This PR is a *verbatim* backport of #30077

### CODE REVIEW

**Comment by mmusich** [comment]
type bug-fix

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by silviodonato** [comment]
merge
alca:  @pohsun @tlampen @tocheng @christopheralanwest
please let me know if you have any comments, I'm merging this now because I'm building a preliminary 11_1_0_pre9 release.

**Comment by tlampen** [comment]
+1

**Pull request merged**
