### PR TITLE
migrate ootPhoton to use GEDPhotonProducer

### PR DESCRIPTION
**Pull request by slava77**
Legacy PhotonProducer was not good enough for ootPhotons: important functionality (some of showerShapeVariables) was missing.
There was an attempt to update the legacy photon producer in  #19060, but it effectively lead to a copy of GEDPhotonProducer.
This PR makes needed changes to make GEDPhotonProducer work for non-GED setup (no PFEGammaCandidates on inputs)

I checked on wf 136.761 and see that only showerShapeVariables_ show up which were zero in the baseline. Kinematics of the ootPhotons and other variables did not change. The chosen workflow is not the best though (only 4 OOT photons in 200 events). 
From visual inspection (confirmed by @kmcdermo ) this PR should produce correct outputs.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cmsbuild please test

140.53 runs OK locally with the last update.

**Comment by slava77** [comment]
@cmsbuild please test

```das_client --limit 0 --query 'lumi,file dataset=/SinglePhoton/Run2016B-v2/RAW run=274199' ``` works OK locally

**Comment by slava77** [comment]
@cmsbuild please test

@smuzaffar @davidlange6 
was the issue with ```136.731 step1 DAS Error``` resolved already?

**Comment by slava77** [comment]
On 6/16/17 5:24 AM, David Lange wrote:
> its "fixed" in the 1100 IB

OK.
So, this test attempt will still fail, since jenkins is still on -2300

>

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@kmcdermo @Sam-Harper
I would like to note the following

The comparisons show that there is a difference in caloPosition of the photon produced by GEDPhotonProducer compared to the PhotonProducer.
In the first case it's plain supercluster position
https://github.com/cms-sw/cmssw/blob/CMSSW_9_2_3/RecoEgamma/EgammaPhotonProducers/src/GEDPhotonProducer.cc#L542
In the PhotonProducer case it depends on r9 of the photon: high r9 photons are assigned a recalculated value based on *SC seed hits only*
https://github.com/cms-sw/cmssw/blob/CMSSW_9_2_3/RecoEgamma/EgammaPhotonProducers/src/PhotonProducer.cc#L376

Here is a sample of differences in workflow 136.761 after running on 400 events
```
* row    * instance * new.cPos.rho * old.cPos.rho * new.cPos.eta * old.cPos.eta * new.cPos.phi * old.cPos.phi * 
*       17 *        0 * 135.71141 * 135.76794 * 1.9394868 * 1.9376318 * 1.2528892 *  1.252316 *
*       26 *        0 * 136.14703 * 136.21090 * 2.9614338 * 2.9631238 * 0.9972192 * 0.9968107 *
*       48 *        0 * 139.29187 * 139.33931 * 1.9979250 * 1.9972713 * -0.355479 * -0.355387 *
*       49 *        0 * 136.83493 * 136.85549 * -3.017255 * -3.017694 * -1.057516 * -1.057394 *
*      347 *        0 * 137.80714 * 137.87281 * -1.110373 * -1.112018 * -0.778601 * -0.778133 *
```

I can guess that for a uniform treatment, you'd rather have the position the same as in gedPhotons, which use the same PF clustering as OOT photons.

Please confirm.

For the possible future migration of the legacy PhotonProducer to use the GEDPhotonProducer, this position recalculation will need to be added to GEDPhotonProducer.

**Comment by kmcdermo** [comment]
@slava77 , you are correct in asserting a more uniform treatment is preferred.  Given that we use the same steps in forming superclusters for the ootPhotons as the gedPhotons, it would be better to have the same caloPosition assignment as the gedPhotons.

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/19264	08544d2
- jenkins tests pass and comparisons with baseline show only a difference in reduced EB rechits, which corresponds to a small change in the definition of reference point to select these hits
- local tests results are provided in the PR description

**Comment by davidlange6** [comment]
+1

**Pull request merged**
