### PR TITLE
Add new L1T menu for Run-3 MC GTs

### PR DESCRIPTION
**Pull request by tvami**
#### PR description:

Add new L1T menu for Run-3 MC GTs as requested in https://cms-talk.web.cern.ch/t/mc-run3-update-l1menu-in-gts/7522

The new GTs, and their diffs wrt to the autoCond are
 * 123X_mcRun3_2021_design_v9
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_mcRun3_2021_design_v8/123X_mcRun3_2021_design_v9
 * 123X_mcRun3_2021_realistic_v9
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_mcRun3_2021_realistic_v8/123X_mcRun3_2021_realistic_v9
 * 123X_mcRun3_2021cosmics_realistic_deco_v9
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_mcRun3_2021cosmics_realistic_deco_v8/123X_mcRun3_2021cosmics_realistic_deco_v9
 * 123X_mcRun3_2021_realistic_HI_v9
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_mcRun3_2021_realistic_HI_v8/123X_mcRun3_2021_realistic_HI_v9
 * 123X_mcRun3_2023_realistic_v9
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_mcRun3_2023_realistic_v8/123X_mcRun3_2023_realistic_v9
 * 123X_mcRun3_2024_realistic_v9
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_mcRun3_2024_realistic_v8/123X_mcRun3_2024_realistic_v9

Diffs are in the requested `L1Menu_Collisions2022_v0_1_5_xml` tag only.

#### PR validation:

workflows = 12034.0,11634.0,7.23,159.0,12434.0,12834.0

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

### CODE REVIEW

**Comment by tvami** [comment]
test parameters:
  - workflows = 12034.0,11634.0,7.23,159.0,12434.0,12834.0

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by francescobrivio** [comment]
+alca

 - new results are clean (except the usual few MTD differences)

**Comment by perrotta** [comment]
+1

**Pull request merged**
