### PR TITLE
fix use after scope in `DMRChecker::bookResidualsHistogram`

### LINKED ISSUE #37765: Use after scope in DMRChecker::bookResidualsHistogram
ASAN found a stack-use-after-scope in `DMRChecker::bookResidualsHistogram()`

```
==24226==ERROR: AddressSanitizer: stack-use-after-scope on address 0x7ffc446a3140 at pc 0x2b899569c8c7 bp 0x7ffc446a24c0 sp 0x7ffc446a1c70
READ of size 16 at 0x7ffc446a3140 thread T0
    #0 0x2b899569c8c6 in printf_common ../../../../libsanitizer/sanitizer_common/sanitizer_common_interceptors_format.inc:553
    #1 0x2b899569e235 in __interceptor_vsnprintf ../../../../libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:1668
    #2 0x2b8997f25505 in Format(char const*, __va_list_tag*) (/cvmfs/cms-ib.cern.ch/nweek-02730/slc7_amd64_gcc11/cms/cmssw/CMSSW_12_4_ASAN_X_2022-04-29-1100/external/slc7_amd64_gcc11/lib/libCore.so+0x1f3505)
    #3 0x2b8997f2a40b in Form(char const*, ...) (/cvmfs/cms-ib.cern.ch/nweek-02730/slc7_amd64_gcc11/cms/cmssw/CMSSW_12_4_ASAN_X_2022-04-29-1100/external/slc7_amd64_gcc11/lib/libCore.so+0x1f840b)
    #4 0x2b89f0c9b6ff in DMRChecker::bookResidualsHistogram(TFileDirectory, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) (/cvmfs/cms-ib.cern.ch/nweek-02730/slc7_amd64_gcc11/cms/cmssw/CMSSW_12_4_ASAN_X_2022-04-29-1100/lib/slc7_amd64_gcc11/pluginAlignmentOfflinevalidationPlugins.so+0x1dd6ff)
    #5 0x2b89f0cadffe in DMRChecker::beginJob() (/cvmfs/cms-ib.cern.ch/nweek-02730/slc7_amd64_gcc11/cms/cmssw/CMSSW_12_4_ASAN_X_2022-04-29-1100/lib/slc7_amd64_gcc11/pluginAlignmentOfflinevalidationPlugins.so+0x1efffe)
```

I think the problem may be here:

https://github.com/cms-sw/cmssw/blob/1481a9564a25d5a6a65c426cb387a81f2e7ba66c/Alignment/OfflineValidation/plugins/DMRChecker.cc#L1968-L1972

where `.c_str()` is called on temporary objects that  immediately go out of scope.  No idea why this wasn't noticed before, it doesn't look like that code has been changed recently.

### PR DESCRIPTION
**Pull request by mmusich**
resolves https://github.com/cms-sw/cmssw/issues/37765

#### PR description:

Title says is all, fix for https://github.com/cms-sw/cmssw/issues/37765

#### PR validation:

`cmssw` compiles, run successfully unit tests of package `Alignment/OfflineValidation` with these changes in`CMSSW_12_4_ASAN_X_2022-05-02-1100`.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

### CODE REVIEW

**Comment by mmusich** [comment]
test parameters:
   * release = CMSSW_12_4_ASAN_X

**Comment by mmusich** [comment]
type bug-fix

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by tvami** [comment]
type trk

**Comment by mmusich** [comment]
the affected unit test comes out actually fine: [log](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-288732/24438/unitTests/src/Alignment/OfflineValidation/test/testAlignmentOfflineValidation/testing.log).
The [other failures ](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-288732/24438/unitTests/failed.html)are unrelated:
   * [testSiStripHitEfficiency](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-288732/24438/unitTests/src/CalibTracker/SiStripHitEfficiency/test/testSiStripHitEfficiency/testing.log) => https://github.com/cms-sw/cmssw/issues/37781
   * [DRNTest](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-288732/24438/unitTests/src/RecoEcal/EgammaClusterProducers/test/DRNTest/testing.log) => https://github.com/cms-sw/cmssw/issues/37767
   
@tvami shall we stop here and re-test with the standard build?

**Comment by tvami** [comment]
> @tvami shall we stop here and re-test with the standard build?

We can just trigger the standard test on the top of this, not necessary to kill this

**Comment by mmusich** [comment]
> We can just trigger the standard test on the top of this, not necessary to kill this

It will show the failure in the bottom check box, which is misleading.

**Comment by tvami** [comment]
+alca
 * tests pass
 * unit test reported in https://github.com/cms-sw/cmssw/issues/37765 is passing in ASAN, other issues are understood
 * standard CMSSW diffs are known as well

**Comment by qliphy** [comment]
+1

**Pull request merged**
