### PR TITLE
Run3 hcx267 Add a new method to HcalGeometry to get position from id packed using TestNumbering

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Add a new method to HcalGeometry to get position from id packed using TestNumbering

#### PR validation:

Tested using a test configuration in SimG4CMS/Calo

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@ianna The HcalGeometry has now a method getPosition(uint32_t, bool) which returns the position for SimHit id produced using testNumbering if the second argument is true and the first argument is the ID in uint32_t

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
