### PR TITLE
Backport to 80X: Flip the soft lepton sIP in case the Negative CTagger is used

### PR DESCRIPTION
**Pull request by smoortga**
This is a backport to CMSSW_8_0_X of the recent commit #15478 (which was in CMSSW_8_1_X) and which was merged today (18 August 2016).

@mverzett, @kovitang and @monttj are interested in following this PR

### CODE REVIEW

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
backport #15478

**Comment by cvuosalo** [comment]
+1

For #15510 897d1ea89eb46413ebb47d3327cabfe6efa0a50e

Allow sign flipping of the softElectron and softMuon impact parameters for the negative c tagger. There should be no change in monitored RECO quantities.

#15478 is the 81X version of this PR, and it has already been merged.

The code changes are satisfactory, and Jenkins tests against baseline CMSSW_8_0_X_2016-08-18-1100 show no significant differences, as expected.

**Comment by davidlange6** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Comment by davidlange6** [comment]
@smuzaffar - seems the bot is confused here - it thinks there are signatures pending for some reason?

**Comment by smuzaffar** [comment]
humm, may be due to backport label. I am looking

**Comment by smuzaffar** [comment]
fixed (new labels urgent, bug-fix, backport and new-features were blocking the removal of pending-signatures)

**Pull request merged**
