### PR TITLE
Added consumes to EcalNextToDeadChannelESProducer

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

Also use ESGetToken returned by consumes.

#### PR validation:

The code compiles.
This is a technical change so should not change results.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
code-checks

**Comment by Dr15Jones** [comment]
please test

**Comment by perrotta** [comment]
+1
- Technical
- Jenkins tests pass

**Comment by kpedro88** [comment]
+1

**Comment by makortel** [comment]
part of #26748

**Pull request merged**
