### PR TITLE
fixed cmsLHEtoEOSManager and added unit test to test it

### PR DESCRIPTION
**Pull request by smuzaffar**
As reported https://hypernews.cern.ch/HyperNews/CMS/get/prep-ops/7320/1.html , cmsLHEtoEOSManager.py does not work for uploading the lhe files. This PR should fix the following issues
- checking of existence of file
- uploading the new LHE file
- fix the checksum commands use `xrdfs query checksum` instead of `eos checksum`

Also added the unit test to make sure that various commands for this scripts properly works. Unit test does the following
- list an existing LHE file and copy it locally
- copy a tmp copy of this file in to cmsbuild eos area
- update  the existing tmp copy
- Do not fail if adler32 is not available from AFS. For IBs and PR tests we do not have access to AFS, so unit test should not fail if it can ot run adler32. Looks like checksum checking is an optional thing https://github.com/cms-sw/cmssw/blob/master/GeneratorInterface/LHEInterface/scripts/cmsLHEtoEOSManager.py#L90-L97

Note that unit test only runs it user has `cmsbuild` token (so it should work for IBs and PR tests)

### CODE REVIEW

**Comment by qliphy** [comment]
Thanks @smuzaffar .
Adding also @cms-sw/pdmv-l2

**Comment by qliphy** [comment]
test parameters:
- workflows = 1370.0,1370.17,1370.18,25215.0,25215.17,25215.18

**Comment by qliphy** [comment]
please test

**Comment by qliphy** [comment]
@smuzaffar   There is a unit error with cmsLHEtoEOSManager.py:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-b17e60/10242/unitTests.log

Traceback (most recent call last):
  File "/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_2_X_2020-10-23-1100/src/GeneratorInterface/LHEInterface/scripts/cmsLHEtoEOSManager.py", line 238, in <module>
    exeCheckSum = subprocess.Popen(["/afs/cern.ch/cms/caf/bin/cms_adler32",f], stdout=subprocess.PIPE) 
  File "/cvmfs/cms-ib.cern.ch/week1/slc7_amd64_gcc820/external/python/2.7.15-bcolbf2/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/cvmfs/cms-ib.cern.ch/week1/slc7_amd64_gcc820/external/python/2.7.15-bcolbf2/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
+ ERR=1
+ popd
/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_2_X_2020-10-23-1100
+ rm -rf test_cmsLHEtoEOSManager
+ xrdfs root://eoscms.cern.ch/ rm /eos/cms/store/user/cmsbuild/unittest/lhe/ibs/1/1603458798-d3d90891282278bfe1031e7ad4c7688a.lhe.xz
[ERROR] Server responded with an error: [3011] Unable to remove /eos/cms/store/user/cmsbuild/unittest/lhe/ibs/1/1603458798-d3d90891282278bfe1031e7ad4c7688a.lhe.xz; No such file or directory

**Comment by smuzaffar** [comment]
ah these hard coded paths `/afs/cern.ch/cms/caf/bin/cms_adler32`
I will fix this one

**Comment by smuzaffar** [comment]
please test

**Comment by agrohsje** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
