### PR TITLE
Fix the mismatch in transition ID for idealGeo

### PR DESCRIPTION
**Pull request by michael-pitt**
#### PR description:

This RP fixes an error caused by loading misaligned geometry record together with the aligned geometry record and hit the transitionID error:

> The transition ID stored in the ESGetToken does not match the transition where the token is being used

This is happens if a user set buildMisalignedGeometry=True in [CTPPSGeometryESModule.cc](https://github.com/cms-sw/cmssw/blob/master/Geometry/VeryForwardGeometryBuilder/plugins/CTPPSGeometryESModule.cc)

#### PR validation:

```
cmsrel CMSSW_12_4_3
cd CMSSW_12_4_3/src
cmsenv
voms-proxy-init --voms cms --valid 168:00
cmsRun cfg.py
```
where the `cfg.py` is the following:

```
import FWCore.ParameterSet.Config as cms
 
from Configuration.StandardSequences.Eras import eras
process = cms.Process("trackBasedAlignment", eras.Run3)
 
# minimum of logs
process.MessageLogger = cms.Service("MessageLogger",
  statistics = cms.untracked.vstring(),
  destinations = cms.untracked.vstring('cout'),
  cout = cms.untracked.PSet(
    threshold = cms.untracked.string('WARNING')
  )
)
 
# input data
process.source = cms.Source("PoolSource",
    skipBadFiles = cms.untracked.bool(True),
    fileNames = cms.untracked.vstring(
        '/store/data/Run2022A/ZeroBias/RAW/v1/000/354/329/00000/e2fefed8-a6e8-42d3-90b3-d8df8534769d.root'
    ),
)
 
#load condisions using GT
process.load('Configuration.StandardSequences.FrontierConditions_GlobalTag_cff')
from Configuration.AlCa.GlobalTag import GlobalTag
process.GlobalTag = GlobalTag(process.GlobalTag, '124X_dataRun3_Prompt_Candidate_2022_07_26_15_08_24', '')
 
# PPS reco modules
process.load("EventFilter.CTPPSRawToDigi.ctppsRawToDigi_cff")
process.load("RecoPPS.Configuration.recoCTPPS_cff")
 
# reload geometry
process.load("Geometry.VeryForwardGeometry.geometryRPFromDD_2022_cfi")
process.ctppsGeometryESModule.buildMisalignedGeometry = cms.bool(True) #false will just complain about missing VeryForwardMisalignedGeometryRecord
 
# initial alignments
process.load("CalibPPS.ESProducers.ctppsRPAlignmentCorrectionsDataESSourceXML_cfi")
process.ctppsRPAlignmentCorrectionsDataESSourceXML.RealFiles = cms.vstring()
process.es_prefer_AlignmentCorrections = cms.ESPrefer("CTPPSRPAlignmentCorrectionsDataESSourceXML","ctppsRPAlignmentCorrectionsDataESSourceXML")
 
# aligner
process.load("CalibPPS.AlignmentRelative.ppsStraightTrackAligner_cfi")
 
process.ppsStraightTrackAligner.verbosity = 1
 
process.ppsStraightTrackAligner.tagUVPatternsStrip = cms.InputTag("totemRPUVPatternFinder")
process.ppsStraightTrackAligner.tagDiamondHits = cms.InputTag("")
process.ppsStraightTrackAligner.tagPixelHits = cms.InputTag("")
process.ppsStraightTrackAligner.tagPixelLocalTracks = cms.InputTag("ctppsPixelLocalTracks")
 
process.ppsStraightTrackAligner.maxEvents = int(1E5)
 
process.ppsStraightTrackAligner.rpIds = [103,104,105,123,124,125]
process.ppsStraightTrackAligner.excludePlanes = cms.vuint32()
process.ppsStraightTrackAligner.z0 = +217000
 
process.ppsStraightTrackAligner.maxResidualToSigma = 30
process.ppsStraightTrackAligner.minimumHitsPerProjectionPerRP = 3
 
process.ppsStraightTrackAligner.removeImpossible = True
process.ppsStraightTrackAligner.requireNumberOfUnits = 2
process.ppsStraightTrackAligner.requireOverlap = False
process.ppsStraightTrackAligner.requireAtLeast3PotsInOverlap = True
process.ppsStraightTrackAligner.additionalAcceptedRPSets = ""
 
process.ppsStraightTrackAligner.cutOnChiSqPerNdf = True
process.ppsStraightTrackAligner.chiSqPerNdfCut = 500
 
process.ppsStraightTrackAligner.maxTrackAx = 0.5E-3
process.ppsStraightTrackAligner.maxTrackAy = 0.5E-3
 
optimize="s"
process.ppsStraightTrackAligner.resolveShR = True
process.ppsStraightTrackAligner.resolveShZ = False
process.ppsStraightTrackAligner.resolveRotZ = False
 
process.ppsStraightTrackAligner.constraintsType = "standard"
process.ppsStraightTrackAligner.standardConstraints.units = cms.vuint32(101,121)
process.ppsStraightTrackAligner.oneRotZPerPot = False
process.ppsStraightTrackAligner.useEqualMeanUMeanVRotZConstraints = True
 
process.ppsStraightTrackAligner.algorithms = cms.vstring("Jan")
 
process.ppsStraightTrackAligner.JanAlignmentAlgorithm.stopOnSingularModes = False
 
results_dir="./"
 
process.ppsStraightTrackAligner.taskDataFileName = "" # results_dir + "/task_data.root"
 
process.ppsStraightTrackAligner.fileNamePrefix = results_dir + "/results_iteration_"
process.ppsStraightTrackAligner.expandedFileNamePrefix = results_dir + "/results_cumulative_expanded_"
process.ppsStraightTrackAligner.factoredFileNamePrefix = results_dir + "/results_cumulative_factored_"
 
process.ppsStraightTrackAligner.diagnosticsFile = results_dir + '/diagnostics.root'
process.ppsStraightTrackAligner.buildDiagnosticPlots = True
process.ppsStraightTrackAligner.JanAlignmentAlgorithm.buildDiagnosticPlots = True
 
 
# processing sequence
process.p = cms.Path(
  # it is important to re-run part of the reconstruction as it may influence
  # the choice of rec-hits used in the alignment
  process.ctppsRawToDigi * process.recoCTPPS * process.ppsStraightTrackAligner
)
```

### CODE REVIEW

**Comment by fabferro** [comment]
> A new Pull Request was created by @michael-pitt (Michael Pitt) for master.
> 
> It involves the following packages:
> 
>     * Geometry/VeryForwardGeometryBuilder (**geometry**)
> 
> 
> @civanch, @Dr15Jones, @makortel, @ianna, @mdhildreth, @cmsbuild, @bsunanda can you please review it and eventually sign? Thanks. @bsunanda, @fabferro, @fabiocos, @grzanka this is something you requested to watch as well. @perrotta, @dpiparo, @rappoccio you are the release manager for this.
> 
> cms-bot commands are listed [here](http://cms-sw.github.io/cms-bot-cmssw-cmds.html)

Since this bug fix is important for PPS alignment data, I would suggest to backport it to 12_4 and 12_5 if still possible.

**Comment by civanch** [comment]
please test

**Comment by michael-pitt** [comment]
Hi @civanch the extra tokens were added to fix the error. The code was using 3 tokens: 
```
idealGDToken_ = c1.consumesFrom<DetGeomDesc, IdealGeometryRecord>(edm::ESInputTag());
realAlignmentToken_ = c1.consumesFrom<CTPPSRPAlignmentCorrectionsData, RPRealAlignmentRecord>(edm::ESInputTag());
misAlignmentToken_ = c2.consumesFrom<CTPPSRPAlignmentCorrectionsData, RPMisalignedAlignmentRecord>(edm::ESInputTag());
```
and the error occur when [CTPPSGeometryESModule::produceGD](https://github.com/cms-sw/cmssw/blob/master/Geometry/VeryForwardGeometryBuilder/plugins/CTPPSGeometryESModule.cc#L73) consumes idealGDToken_  with misAlignmentToken_ . So I added another consumer
```
idealGDToken2_ = c2.consumesFrom<DetGeomDesc, IdealGeometryRecord>(edm::ESInputTag());
```
to avoid mismatch. 

btw, in the older version of the code ([CMSSW_11_1_X/.../CTPPSGeometryESModule.cc](https://github.com/cms-sw/cmssw/blob/CMSSW_11_1_X/Geometry/VeryForwardGeometryBuilder/plugins/CTPPSGeometryESModule.cc#L89) use Tokens, which were initialized with the function. I tried to do the same, but somehow hit multiple errors.

**Comment by civanch** [comment]
@bsunanda , what do you think? Can we accept this fix?

**Comment by makortel** [comment]
The replication of tokens is correct. Taking `idealGDToken_` as an example, the existing token is registered for use in `CTPPSGeometryESModule::produceRealGD()`
https://github.com/cms-sw/cmssw/blob/6364eea90e08621e448ef2f3958f16dfc649c140/Geometry/VeryForwardGeometryBuilder/plugins/CTPPSGeometryESModule.cc#L123-L124
and can not be used in any other produce function. The use in `CTPPSGeometryESModule::produceMisalignedGD()` needs a separate token object.

**Comment by civanch** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
