### PR TITLE
Add esConsumes to EcalTrigPrimProducer

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

Refactored code to allow EcalTrigPrimProducer to be able to call esConsumes for all EventSetup data products it needs.
Major change involved removing EventSetup access from the various helper classes, although several didn't use it at all.

#### PR validation:

Code compiles.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by silviodonato** [comment]
kind reminder @cms-sw/l1-l2

**Comment by qliphy** [comment]
ping @rekovic @cecilecaillol

**Comment by rekovic** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
