### PR TITLE
Settings for Herwig7 CH2 tune

### PR DESCRIPTION
**Pull request by EmyrClement**
Adding fragments for new Herwig7 tune.  Also including fragment for setting long lived (ctau>10mm) particles as stable (as in Pythia).

### CODE REVIEW

**Comment by efeyazgan** [comment]
please test

**Comment by efeyazgan** [comment]
+1

**Comment by fabiocos** [comment]
@efeyazgan @alberto-sanchez I assume this was tested in standalone checks, am I correct?

**Comment by qliphy** [comment]
yes, @EmyrClement has tested that:  https://ejclemen.web.cern.ch/ejclemen/NNPDF_NNLO_noPythia/CMS_Internal_FSQ_15_007/index.html

**Comment by fabiocos** [comment]
+1

**Pull request merged**
