### PR TITLE
new version of pileUp calculation script

### PR DESCRIPTION
**Pull request by jsalfeld**

### CODE REVIEW

**Comment by jsalfeld** [comment]
please back-port CMSSW 7_4, 7_5 and 7_6

**Comment by ggovi** [comment]
+1

**Comment by davidlange6** [comment]
@jsalfeld - the new script seems to be a simple extension of the old one - do we really need both?

**Comment by jsalfeld** [comment]
Yes this script runs over a different csv file format (lumiCalc -> brilcalc). Since Run-1 data is still being analyzed the "old" script is still needed.

**Comment by jsalfeld** [comment]
But now that I think, it should probably be named estimatePileup_makeJSON_Run2.py .

Can you do that? otherwise it does not matter, sorry about that.

**Comment by davidlange6** [comment]
@jsalfeld - ok thanks. The easiest way to change the name is just to do a git mv x y on your branch. Or we can do this as a second PR, whichever you prefer.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
