### PR TITLE
Fix runTheMatrix interactive and add tests.

### PR DESCRIPTION
**Pull request by rovere**
#### PR description:

Recent addition of tests to `runTheMatrix` caused a crash while running it _interactively_. This PR fixes the crash.
An additional test has also been added to periodically check the validity of the `--interactive` option of `runTheMatrix`.

#### PR validation:

`runTheMatrix` still works.

### CODE REVIEW

**Comment by srimanob** [comment]
@cmsbuild please test

Re-trigger the test after a week.

**Comment by srimanob** [comment]
Hi @rovere 
I see that the unit test work as expected in https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-520e8e/30128/unitTests/src/Configuration/PyReleaseValidation/test/test-runTheMatrix-interactive/testing.log
Could you please confirm?

By the way, is the test considered to be OK in terms of resource? It seems to be a long printout, but maybe it is OK.

**Comment by rovere** [comment]
Ciao @srimanob thanks for looking into this.
Part of the printouts come directly from `runTheMatrix` and, unless redirected otherwise, they'll be part of the output. They are sent to `stdout`, not `stderr`, so one cannot really disentangle them.
Apart from that, everything looks ok from my side.

**Comment by srimanob** [comment]
+Upgrade

**Comment by srimanob** [comment]
Kindly ping @cms-sw/pdmv-l2

**Comment by srimanob** [comment]
@cmsbuild please test

Refresh the test

**Comment by kskovpen** [comment]
+pdmv

**Comment by perrotta** [comment]
+1

**Pull request merged**
