### PR TITLE
Bug fix for compatible mode in UETableProducer. Don't overwrite pytho…

### PR DESCRIPTION
**Pull request by mverwe**
…n files in make_db.sh.
Does not have impact on reconstruction. Bug fix for DB generation.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test
... jenkins is down though, unclear if this message will be queued or just missed

**Comment by smuzaffar** [comment]
@slava77 , jenkins is up again but web access via cmssdt is not configured yet
Any, cms bot should see these messages and trigger the tests properly

**Comment by slava77** [comment]
@mverwe 
please make a PR in 76X (80X will get it by auto-forward-port from 76X).

**Comment by mverwe** [comment]
@slava77 
PR for 76X made: #12239

**Comment by cvuosalo** [comment]
+1

For #12227  581060b6c88cd64996efbc6d07d3a55c712bf158

Bug fix in Heavy Ion UETableProducer for DB generation. There should be no change in monitored quantities. #12239 is the 76X version of this PR.

The code change is satisfactory, though thread safety will need to be addressed in the 76X version. Jenkins [tests](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-12227/9415/summary.html) against baseline CMSSW_7_5_X_2015-11-01-2300 show no significant differences, as expected.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
