### PR TITLE
Btv hlt dqm offline

### PR DESCRIPTION
**Pull request by alebihan**
Adding HLT BTV histograms in DQMOffline.

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by perrotta** [comment]
Since data taking (and corresponding validation) is actually done with 74X, does it exist (or do you foresee) a 74X counterpart of this pull request?

**Comment by alebihan** [comment]
Hi Andrea,

So far there is no 74X counterpart of this PR. Will the 25 ns data 
taking use 74X. If yes we should probably submit it to 74X as well (if 
possible).

Thanks,
Anne-Catherine

**Comment by perrotta** [comment]
Hi Anne-Catherine.

As far as I can see this PR allows the monitoring of the two HLT paths
- HLT_QuadPFJet_SingleBTagCSV_VBF_Mqq500
- HLT_PFMET120_NoiseCleaned_BTagCSV0p72

Independently on the release that will be used for 25ns, those two paths are also in the current 50ns menu, and I imagine that you want/should monitor them since now. Therefore: 74X.

Thank you,
Andrea

**Comment by alebihan** [comment]
Hi Andrea,

Thanks for the clarification, have submitted it to 74X as well :
https://github.com/cms-sw/cmssw/pull/10211

Cheers,

AC

**Comment by deguio** [comment]
ciao @alebihan 
is this PR final? I see that the harvester basically doesn't do anything. if it is not needed please just remove it (.h, .cc, .cfi)

the BTVHLTOfflineSource class instead needs some cleaning. please remove the commented code and the includes which are not used.

moreover the initialization of the hltConfigProvider should go in the dqmBeginRun together with the definition of the interesting paths. you can follow the instructions at:
https://twiki.cern.ch/twiki/bin/viewauth/CMS/ThreadedDQM#The_DQMEDAnalyzer

I will reject this one for now but feel free to push to the same branch (same story for 75 and 74).

thanks and sorry for being so late.
F.

**Comment by deguio** [comment]
-1

**Comment by deguio** [comment]
honestly I don't understand the need for the setHistos method.
I would go simple and use the original MonitorElements as they are. no need to get the TH1 out of them.
you can take a look at:
https://github.com/cms-sw/cmssw/blob/CMSSW_7_6_X/DQMServices/Examples/interface/DQMExample_Step1.h
https://github.com/cms-sw/cmssw/blob/CMSSW_7_6_X/DQMServices/Examples/src/DQMExample_Step1.cc

thanks,
F.

**Comment by deguio** [comment]
@alebihan
please let me know if you plan to converge on this soon (in the next ~2 days). I will ask for a new release at tomorrow's orp meeting.
thanks,
F.

@puigh

**Comment by silviodonato** [comment]
I prepared a new PR including the suggestions by @deguio : https://github.com/cms-sw/cmssw/pull/10501 . 
Please ignore this PR and consider https://github.com/cms-sw/cmssw/pull/10501 only.

**Pull request closed without merging**
