### PR TITLE
[MTD] Update MTD hit pattern + add outermost hits position in the TrackExtenderWithMTD

### PR DESCRIPTION
**Pull request by martinamalberti**
#### PR description:
This PR includes 
1) an update of the hit pattern for MTD 
2) the addition of a ValueMap, filled within the TrackExtenderWithMTD, to store the track outermost hit position (R for tracks with hits in BTL, Z for tracks with hits in ETL).

#### PR validation:
The code was tested on wf 24906.0 and 24807.0.

### CODE REVIEW

**Comment by civanch** [comment]
+1

**Comment by mandrenguyen** [comment]
+1

**Comment by tjavaid** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

**Comment by rappoccio** [comment]
+1

**Pull request merged**
