### PR TITLE
[BTV] Backport of #40803 (PUPPI ValueMap-compatible Deep taggers info producers)

### PR DESCRIPTION
**Pull request by nurfikri89**
Backport from #40803 

Original PR description:

The main goal of this PR is to modify several BTV Deep taggers info producers, which are used to retrieve the features of each jet , to retrieve the puppi weight for each PF candidate from a `ValueMap<float>` produced by `PuppiProducer`. The (fallback) puppi weight value is set to be `1.0` before accessing the weight from the ValueMap. If users do not set the `fallback_puppi_weight` flag to be `true` and does not specify a source for `puppi_value_map`, an exception is thrown. A new optional flag `is_weighted_jet` is introduced so that users can make specify to apply the puppi weights on the PF constituents' four-vector. The flag should be set to `true` for Puppi jets.

A new function, `setupPackedPuppi()`, is defined in `PhysicsTools/PatAlgos/python/tools/jetTools.py` that can be called to setup a `PuppiProducer` instance and provides a common puppi weight ValueMap for any module which requires one.

#### PR validation:
- Validation plots comparing the input variables before and after the fix can be found in this JMAR meeting virtual [contribution](https://indico.cern.ch/event/1254328/#4-virtual-puppi-valuemap-compa). 
- passes the usual runTheMatrix test: `runTheMatrix.py -l limited -i all --ibeos`
- passes JMENanoAOD workflows: `runTheMatrix.py -i all --ibeos -l 10224.15,11024.15,25202.15,11634.15`
- passes reMiniAOD and reNanoAOD workflows: `runTheMatrix.py -i all --ibeos -l 1325.518,2500.312`

### CODE REVIEW

**Comment by nurfikri89** [comment]
FYI @AnnikaStein, @AlexDeMoor and @demuller

**Comment by mandrenguyen** [comment]
backport of #40803

**Comment by mandrenguyen** [comment]
type btv

**Comment by mandrenguyen** [comment]
+1

**Comment by simonepigazzini** [comment]
+1

**Pull request merged**
