### PR TITLE
Add XML file for L1Menu_Collisions2015_50ns_v0 menu

### PR DESCRIPTION
**Pull request by vasile-ghete**
The PR contains only the XML file for L1Menu_Collisions2015_50ns_v0 menu, so it can be merged w/o HLT changes, Changes to use it must be included in another PR.

### CODE REVIEW

**Comment by degano** [comment]
@cmsbuild please test

**Comment by Martin-Grunewald** [comment]
@cmsbuild, @nclopezo 
this PR seems stuck in testing, please check
@mulhearn 
please sign

**Comment by nclopezo** [comment]
@Martin-Grunewald 
I just restarted the tests.

**Comment by mulhearn** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
