### PR TITLE
[92x] EcalPedestal PCL workflow: fixes and improvements

### PR DESCRIPTION
**Pull request by cerminar**
This PR addresses some issues of this new PCL workflow. It would be useful to have this integrated to complete tests @ tier0

 - fix RAW output module in TestEnable AlcaRAW scenario
 - fix ALCAPROMPT data-tier in alcaskimming
 - add the needed metadata for the GUI to the DQM file produced by the workflow
 - decouple RAW production from actual PCL processing (should be safer for the RAW)
 - change the relval workflow 1010 accordingly

### CODE REVIEW

**Comment by cerminar** [comment]
please test

**Comment by arunhep** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Comment by fabozzi** [comment]
+1

**Comment by davidlange6** [comment]
merge

**Pull request merged**
