### PR TITLE
Wprime paths backported to 92X

### PR DESCRIPTION
**Pull request by gomber**
@fwyzard Here is the PR correspondign to #19250 back ported to 92X.

Regards
Bhawna

### CODE REVIEW

**Comment by dmitrijus** [comment]
The number of changes mismatch the upstream version.
Please give a good explanation why it is the case. 

Most likely you actually forgot to include all the necessary changes.

**Comment by gomber** [comment]
@dmitrijus sorry for not being clear, but this PR needs to run on top of  #19613 (which is a back port of #19119 )

**Comment by dmitrijus** [comment]
@gomber So, then we wait until  #19613 is merged. Which probably won't happen, since that PR is closed.

**Comment by gomber** [comment]
@dmitrijus ok I found the correct PR https://github.com/cms-sw/cmssw/pull/19616
Sorry got confused with different PR's with the same open. SO this code needs to run on top of #19616

**Pull request closed without merging**
