### PR TITLE
Remove MallocOpts as obsolete

### LINKED ISSUE #36500: Is MallocOpts still useful?
Question raised in https://github.com/cms-sw/cmssw/pull/36467

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

Resolves https://github.com/cms-sw/cmssw/issues/36500

#### PR validation:

Framework unit tests run

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
@Dr15Jones Do you agree?

**Comment by Dr15Jones** [comment]
> Do you agree?

yes.

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by perrotta** [comment]
please test
(just to check whether in the new IB the differences in 11634.X workflows do disappear)

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
(apparently I'm testing "just for fun"...)

**Comment by makortel** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
