### PR TITLE
Add consumes interface for ObjectViewCleaner

### PR DESCRIPTION
**Pull request by wmtan**
Add the consumes interface for ObjectViewCleaner
Also changed one loop to a range for loop for consistency, clarity and maintainability.

### CODE REVIEW

**Comment by deguio** [comment]
+1

**Comment by wmtan** [comment]
I just updated this PR to include the gtByLabel to getByToken migration.

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
