### PR TITLE
[13_0_X backport ]change era to Run3_2023 for 2023 WFs

### PR DESCRIPTION
**Pull request by sunilUIET**
#### PR description:

This PR is to change era from "Run3" to "Run3_2023" for relval WFs defined for 2023 conditions. This is a backport of #41319 

#### PR validation:

Need to be tested with PR #41368

### CODE REVIEW

**Comment by sunilUIET** [comment]
test parameters:

relvals_opt= -w upgrade
workflows = 12402.0

**Comment by sunilUIET** [comment]
@cmsbuild please test with #41368

**Comment by sunilUIET** [comment]
+pdmv

**Comment by rappoccio** [comment]
+1

Bypassing upgrades for expediency, this is a trivial PR

**Comment by rappoccio** [comment]
merge

**Pull request merged**
