### PR TITLE
Fix undefined behavior in CaloPoint

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

Always set the enum value to an allowed value.

This was uncovered by the UBSAN IB

#### PR validation:

Code compiles.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
Please test

**Comment by Dr15Jones** [comment]
ping

**Review by sbein — APPROVED** [review]

**Comment by sbein** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
