### PR TITLE
Fix unit test testUCTUnpacker

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

- handle case where have empty input
- initialize memory buffers to avoid possible reading of uninitialzed memory
- properly find the input file

#### PR validation:

Code compiles and unit test now passes.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
This change has no effect on the RelVals so the test failure can not be caused by this.

**Comment by aloeliger** [comment]
please test

**Comment by aloeliger** [comment]
+l1

**Comment by perrotta** [comment]
+1

**Pull request merged**
