### PR TITLE
Run3-hcx294 Update HCAL code in material budget studies for DD4HEP

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Update HCAL code in material budget studies using DD4HEP

#### PR validation:

Tested using scripts in Validation/Geometry/test

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by jfernan2** [comment]
+1

**Comment by cvuosalo** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
