### PR TITLE
Store PS weights in 94X

### PR DESCRIPTION
**Pull request by EmyrClement**
This is a similar PR to #25860, which was the backport to 93X, this is a combined backport #21477, #24209, #24305, and (partial) #21073.

The changes are needed to store PS weights in the RunIIpp5Spring18wmLHEGS campaign.

### CODE REVIEW

**Comment by efeyazgan** [comment]
please test

**Comment by efeyazgan** [comment]
+1

**Comment by fabiocos** [comment]
@efeyazgan @qliphy @alberto-sanchez @franzoni @srimanob this PR is technically ok, but effectively will modify the GEN event weight content of samples in the middle of an existing campaign. Are we sure we want it?

**Comment by efeyazgan** [comment]
I think it should be fine if we inform MC contacts and analyzers. I think apart from heavy ions, 5 TeV run, and fastsim no one is using 94X for gen production.  
@gkrintir anything to add?

**Comment by gkrintir** [comment]
Hello,

right. MC contacts and analyzers will be informed for this extra feauture.

This modification is **needed** to add the PS weights for samples (ttbar,tW) that we initially thought they already included them. :[

To avoid any confusions we can discuss with Pdmv, e.g., to add a proper extension in the PDs name maybe?

**Comment by fabiocos** [comment]
Adding PdmV experts @pgunnell @prebello @zhenhu for info

**Comment by efeyazgan** [comment]
"To avoid any confusions we can discuss with Pdmv, e.g., to add a proper extension in the PDs name maybe?" --> is a good idea.

**Comment by fabiocos** [comment]
Ok, the PR as it is does not change anything, it requires that the PSet is activated in some configuration fragment. So strictly speaking as far as I am concerned it can go. But of course PPD/PdmV should be aware of the possible consequences of its activation. The event format as such is untouched, but the GenEvent weights stored might differ from one sample to another depending on the use of these settings.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
