### PR TITLE
HLT menu updates on top of what was in CMSSW_7_4_1

### PR DESCRIPTION
**Pull request by perrotta**
- Switch saveTag=true in several filters (to allow inspecting them in the analyses)
- Migrate to a new ConfDB template
- Update a few L1 seeds for EXO paths
- Replace PFMHTIDLoose with PFMHTIDTight

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
+1

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by perrotta** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by Martin-Grunewald** [comment]
+1

**Pull request merged**
