### PR TITLE
Run3-gex164X One more alternative suggestion for addressing RPC issue

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

One more alternative suggestion for addressing RPC issue

#### PR validation:

Tested against overlap

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by bsunanda** [comment]
Please do not merge this PR right now. Wait till some tests are made with pre2

**Comment by perrotta** [comment]
hold
> Please do not merge this PR right now. Wait till some tests are made with pre2

**Comment by bsunanda** [comment]
@perrotta Could you please uphold this now? The tests with the other PR is over and results are positive. We have made the fix in the official scenarios. So this change can stay as an alternative and this deals with only demonstration chambers and that will be sorted out later by the muon group.

**Comment by bsunanda** [comment]
@cmsbuild unsold

**Comment by perrotta** [comment]
unhold

**Pull request merged**
