### PR TITLE
bsunanda:Run2-alca37 Fix bug to avoid run-time error for Pythia8

### PR DESCRIPTION
**Pull request by bsunanda**

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by covarell** [comment]
+1

**Comment by davidlange6** [comment]
+1
wondering how this did not get noticed in the validation done before requesting a back port (and a special release, which is wasted..)

**Comment by covarell** [comment]
@bsunanda should answer this, but I believe a particle not recognized by PDT must be a very rare event (usually these errors are triggered by some weird light mesons)

**Comment by bsunanda** [comment]
I concentrated on Pythia6 at that time which had no such errors. For Pythia8 it is very rare but it happens when one goes above a few 1000 events. We understand that Pythia8 will now be used and in that process we discovered the shortcoming. Sorry for overlooking this.
________________________________

**Pull request merged**
