### PR TITLE
Changes from scram build format-all on FWCore

### PR DESCRIPTION
**Pull request by wddgit**
#### PR description:

The first commit includes only changes from scram build code-format-all and nothing else. This PR includes all the packages in the FWCore subsystem not previously formatted, except the Skeletons package.

There were a few addition changes that showed up in code-checks in the second commit.

I also manually added one fix in the third commit to disambiguate the name of a preprocessor macro. Previously the compiler did not complain because the definitions in FWCore and Fireworks were identical, but the spacing change introduced by clang format caused the compiler to start issuing warnings.

#### PR validation:

The only test I performed was checking that the revised packages compile and build.

### CODE REVIEW

**Comment by wddgit** [comment]
please test

**Comment by smuzaffar** [comment]
@wddgit , due to code formatting,  number of lines in UnitTestClient_Ad.cc are changed. So you also need to update the reference log file
 
https://github.com/cms-sw/cmssw/blob/02d4198c0b6615287fd88e9a8ff650aea994412e/FWCore/MessageService/test/unit_test_outputs/u1d_debugs.log#L2

https://github.com/cms-sw/cmssw/blob/02d4198c0b6615287fd88e9a8ff650aea994412e/FWCore/MessageService/test/unit_test_outputs/u1d_debugs.log#L5

**Comment by wddgit** [comment]
please test

**Comment by wddgit** [comment]
This is possibly not the correct place for this comment, but I was just trying to create another pull request on the IOPool Subsystem by running scram build code-format-all. I am getting very different results from clang-format. It is not indenting in namespaces. Did something change in the parameters we are passing to clang format? My new area is based on CMSSW_10_6_X_2019-05-07-1100 on cmsdev34. Probably I've made some blunder in my setup, but I am puzzled by this. The history is below:

```
 1007  cmsrel CMSSW_10_6_X_2019-05-07-1100
 1008  cd CMSSW_10_6_X_2019-05-07-1100/src/
 1009  pwd
 1010  cmsenv
 1011  ls
 1012  git cms-addpkg IOPool/Common
 1013  git cms-addpkg IOPool/Input
 1014  git cms-addpkg IOPool/Output
 1015  git cms-addpkg IOPool/Provenance
 1016  git cms-addpkg IOPool/SecondaryInput
 1017  git cms-addpkg IOPool/Streamer
 1018  git cms-addpkg IOPool/TFileAdaptor
 1019  ls
 1020  ls IOPool/
 1021  pwd
 1022  scram b -j 8
 1023  pwd
 1024  scram build code-format-all
...
```

**Comment by fabiocos** [comment]
+1

**Pull request merged**
