### PR TITLE
Hlt dqm take 3

### PR DESCRIPTION
**Pull request by davidlange6**
Following #19731 - but without BPH plugin changes still under review.

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
hi @dmitrijus - it looks like this adds to the existing set of things misconfigured for the HI DQM. (140.53 step2) - please have a look and clean things. Thanks

**Comment by lathomas** [comment]
Hi, 

Sorry for not following this better but what's preventing this PR to be merged? Is there any action possible on our side (POG/PAG DQM) to move on? 

Thanks !

**Comment by davidlange6** [comment]
it was merged in July...

**Comment by lathomas** [comment]
Stupid me. I looked too fast :) Thanks and sorry for the noise.

**Pull request merged**
