### PR TITLE
Unsch RECO together mini aod (aka PAT) step

### PR DESCRIPTION
**Pull request by franzoni**
++ data and full sim (noPU, PU, premix) => Unsch RECO together mini aod

. astSim not migrated to unscheduled
. full standard+PU tests are ok, the crashes (the 3 prod workflows) are known (dqmAk4PFL1FastL2L3ResidualCorrector) and being worked on by DQM
. double url for DQM gui upload

++ will be fwd ported to 75x and 76x

### CODE REVIEW

**Comment by franzoni** [comment]
please test

**Comment by franzoni** [comment]
+1

**Comment by slava77** [comment]
Here are some notes from RECO tests for this PR, based on CMSSW_7_4_6_patch1, the tests included higher statistics tests compared to just the plain short matrix from the jenkins setup.

- all workflows completed ok (no crashes)
- RECO products didn't change (based on fwlite comparisons and on the standard DQM comparisons)
    - there is a caveat: RECO tier picked up ~50 products from  {egmGsfElectronIDs}: we need to drop these @lgray @rafaellopesdesa  could you please update the event content for RECO to not pick up these indiscriminately. These products are not showing up in AOD data tier.
- the following modules disappeared from the list of running modules: l1GtTriggerMenuLite, dqmGctDigis, initialStepTrackRefsForJetsPreSplitting (either they are actually gone or are just not printed out by the TimeReport is not obvious, I think it's the former and it's probably OK since nobody needed these products)
- my MINIAOD (pseudo)validation looks OK based on the following
    - I checked the MINIAOD file provenance in 25202 and didn't find any relevant differences. This means that at least the tracked config parameters to the modules are the same in MINIAOD
    - the edmEventSize reports differences for the MINIAOD product branches at a few (up to 20) bytes per branch. I picked several variables manually and found that they are the same by value. It looks like the reported size includes the branch name (and maybe some more root internals) which changed from *_PAT to *_RECO
- there is an issue in the Tier0-like workflow 1000.0 : TkAlMinBias/{GeneralProperties,HitProperties,TkAlignmentSpecific} plots are turning empty with this PR

**Comment by deguio** [comment]
cross reference: #9943 to address the dqmAk4PFL1FastL2L3ResidualCorrector problem

**Comment by franzoni** [comment]
This PR has been thoroughly locally tested
tested by the bot
and usef for 3 full-ser relval submission with 7_4_6_patch6

Closing this one and opening another one, resolving the conflicts

**Pull request closed without merging**
