### PR TITLE
transferSystem PSet support and other DAQ updates (74X)

### PR DESCRIPTION
**Pull request by smorovic**
74X PR identical to changes pushed for 73X in https://github.com/cms-sw/cmssw/pull/7990

changes:
-    beginning of lumisection files written locally by FUs to indicate opening new LS from the input source to other DAQ components (introduced to create backpressure in case of delay in LS processing)
-    Each Ini file checksum is verified after writing to disk and before renaming into location where it is taken by hltd
-    transfer system PSet and selected destination support. Selected destination is passed as VarArgs parameter. A parameter is added to control whether exception is thrown when PSet is incomplete or parameter missing. New output json field is added to output module as well as JSON and DQMHistograms modules
-    fixed min. number of run digits in filenames used by TriggerJSONMonitoring (only relevant for test run numbers smaller than 100000).
-    Fake BU and Raw writer improvements:
  -        FED 1024 is handled in Raw writer
  -        closing last LS written when interrupted from shell
  -        updated schema of EoLS and Eor jsd/json
  -        ability to copy menu directory when starting a run by script
  -        fffParameters.jsn file handling

### CODE REVIEW

**Comment by fwyzard** [comment]
...so much for disentangling CMSSW and DAQ with the file-based HLT...

**Comment by Martin-Grunewald** [comment]
please test

**Comment by deguio** [comment]
could you please submit this one to 75 as well?
thanks,
F.

**Comment by smorovic** [comment]
@deguio, rebased and pushed also for 75X in PR #8002
Srecko

**Comment by Martin-Grunewald** [comment]
+1

**Comment by emeschi** [comment]
+1
On 28 Feb 2015, at 11:45, Martin Grunewald <notifications@github.com<mailto:notifications@github.com>> wrote:


please test

**Comment by deguio** [comment]
+1
thanks @smorovic

**Comment by davidlange6** [comment]
+1

**Pull request merged**
