### PR TITLE
Fix `JetHTAnalyzer::fillDescriptions`

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

It was reported by @jusaviin that the declaration of the configuration parameters in the  `fillDescriptions` method of the `JetHTAnalyzer`

https://github.com/cms-sw/cmssw/blob/4dd963864653b12bd06cc29da5fa9dc744ec1901/Alignment/OfflineValidation/plugins/JetHTAnalyzer.cc#L334-L339

plugins doesn't agree with their usage in the all-in-one configuration:

https://github.com/cms-sw/cmssw/blob/4dd963864653b12bd06cc29da5fa9dc744ec1901/Alignment/OfflineValidation/python/TkAlAllInOneTool/JetHT_cfg.py#L272-L276

This results in runtime failures. 
This PR fixes the issue in commit 7cc01f89fe2d5af061bc032856bf3295e206ed77
I profit of this to update the unit tests `testTrackAnalyzers` in order to test that the two do not go out of synch again.

#### PR validation:

Relies on the existing unit tests (`scram b runtests_testTrackAnalysis`)

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

N/A

### CODE REVIEW

**Comment by mmusich** [comment]
type bug-fix

**Comment by mmusich** [comment]
please test

**Comment by tvami** [comment]
+alca

**Comment by perrotta** [comment]
@mmusich a simpler way to be sure that all parameters stay in sinc (and to check that by mistake you did not misspelled any of their names also) is to replace https://github.com/cms-sw/cmssw/blob/4dd963864653b12bd06cc29da5fa9dc744ec1901/Alignment/OfflineValidation/python/TkAlAllInOneTool/JetHT_cfg.py#L272-L276 with:
```PYTHON
from Alignment.OfflineValidation.jetHTAnalyzer_cfi.py import jetHTAnalyzer as _jetHTAnalyzer
process.jetHTAnalyzer = _jetHTAnalyzer.clone(
                                       vtxCollection       = "offlinePrimaryVerticesFromRefittedTrks",
                                       trackCollection	   ="TrackRefitter",
                                       triggerResults      = ("TriggerResults","","HLT"),
                                       printTriggerTable   = printTriggers,
                                       minVertexNdf        = 10.,
                                       minVertexMeanWeight = 0.5,
                                       profilePtBorders    = ptBorders,
                                       iovList             = iovListList
)
```
(which is why the release managers tend to bother the proponents of the PRs to make them remove type specifications from the cloned configs in python...)

**Comment by perrotta** [comment]
+1

**Comment by mmusich** [comment]
@perrotta 

> simpler way to be sure that all parameters stay in sinc (and to check that by mistake you did not misspelled any of their names also) is to replace

Right, let's do it for all the configuration files in this package another time

**Comment by mmusich** [comment]
Also, for the record, in addition to have wrong types declared in the configuration, the plugin had a mismatch between the type expected in the constructor and the one declared in `fillDescriptions`. AFAIU, your solution does not prevent that kind of mistake, while the unit test does.

**Comment by perrotta** [comment]
> Also, for the record, in addition to have wrong types declared in the configuration, the plugin had a mismatch between the type expected in the constructor and the one declared in `fillDescriptions`. AFAIU, your solution does not prevent that kind of mistake, while the unit test does.

I am not against your unit test, which is welcome. I'm just sponsorizing a cleaner way of writing configs, which may prevent quite several possible mistakes, but not all (in particolar, it cannot fix bugs in the c++ code as the one that you are reporting)

**Comment by mmusich** [comment]
> Right, let's do it for all the configuration files in this package another time

for the record, that's done at https://github.com/cms-sw/cmssw/pull/40695

**Pull request merged**
