### PR TITLE
HLT menu development for `12_2_X` + migration to `12_2_0_pre2` template

### PR DESCRIPTION
**Pull request by missirol**
#### PR description:

Development of HLT menus for `CMSSW_12_2_X`.

Includes the migration of all HLT configurations to the `12_2_0_pre2` template, and the integration of the following JIRA ticket:

  - [CMSHLT-2195](https://its.cern.ch/jira/browse/CMSHLT-2195): technical changes to `AlCa_LumiPixelCounts` paths (affects 2 triggers in `GRun` and `PRef` menus)
  - [CMSHLT-2198](https://its.cern.ch/jira/browse/CMSHLT-2198): addition of `GEMGeometryESModule` to HLT configurations

#### PR validation:

TSG tests.

#### If this PR is a backport, please specify the original PR and why you need to backport that PR:

N/A

### CODE REVIEW

**Comment by missirol** [comment]
please test

**Comment by Martin-Grunewald** [comment]
Why is CMSHLT-2198 missing?

**Comment by missirol** [comment]
> Why is CMSHLT-2198 missing?

I haven't integrated (and tested) that yet. I was planning to do that today, and likely make a PR with that tomorrow (or later if other things also need to be integrated).

**Comment by missirol** [comment]
please test

**Comment by missirol** [comment]
+hlt

**Comment by qliphy** [comment]
+1

**Pull request merged**
