### PR TITLE
FastSim: make matched hits aware of order of components (75X, BUGFIX)

### PR DESCRIPTION
**Pull request by lveldere**
Fixes low efficiency for high purity tracks observed in validation of 750pre6, introduced in #9595 

Expected changes:
FullSim: none
FastSim: increased tracking efficiency, especially for high purity

### CODE REVIEW

**Comment by lveldere** [comment]
please test

**Comment by lveldere** [comment]
+1

**Comment by lveldere** [comment]
+1

**Comment by slava77** [comment]
@cmsbuild please test
the IB used for jenkins tests was too old, there are additional commits merged that may interfere with the diffs

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/10079	41e67a1

looking at the additional PRs between CMSSW_7_5_X_2015-07-07-2300 and CMSSW_7_5_X_2015-07-05-1100, it appears that changes here would be only from the fastsim itself.

- only fastsim is affected
- jenkins tests pass and comparisons with the baseline show differences in fastsim workflows
    - there is also a small change in the DQM plot dragged in by jenkins from #10002, but that's not relevant to the code changes here

There are more and better tracks
Here are several plots from ZEE 135.4 workflow based on MTV plots
wf135p4_algo
wf135p4_missingouterl
wf135p4_hits

**Pull request merged**
