### PR TITLE
Revert "DD: Current Namespace is a Singleton, so make it one"

### PR DESCRIPTION
**Pull request by ianna**
Reverts cms-sw/cmssw#24401

Fix for CLANG IBs failures:
```
%MSG-e Specific:  OscarMTProducer:g4SimHits@beginRun 01-Sep-2018 07:18:26 CEST  Run: 1
Could not process q-name of a DDLogicalPart, reason:
DDLogicalPart-name "RT1C" matching regex "RT1C" has been found at least in following namespaces:
rpcf GLOBAL 
Qualify the name with a regexp for the namespace, i.e ".*:name-regexp" !
SpecPar selection is:
//RT1C
```

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by kpedro88** [comment]
+upgrade

**Comment by ianna** [comment]
+1

**Comment by ianna** [comment]
@fabiocos - please take it for pre3 if it's not too late. It should fix the CLANG IBs failures. Thanks.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
