### PR TITLE
Run3-hcx255 Add the dump code for preshower and change the names of some classes

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Add the geometry dump code for preshower cells and change the names of some classes so that they all start with a capital character

#### PR validation:

Done using private cfg's

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please check

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
