### PR TITLE
FastSim: fix trackref in ConversionTrackCollection

### PR DESCRIPTION
**Pull request by lveldere**
- the original ConversionTrackCollection is copied. In the copy, reference to tracks in the before-mixing track collection are replaced with references to the after-mixing track collection
- the before-mixing track collection is dropped from AODSIM, which is justified by the above
- should be considered for backporting to 74X as it reduces the AODSIM event content

### CODE REVIEW

**Comment by lveldere** [comment]
please test

**Comment by lveldere** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Comment by lveldere** [comment]
@davidlange6 
I'm checking how much effect this has on the AODSIM file size.
If it's significant enough, I'll prepare a backport for 74X today.

**Comment by lveldere** [comment]
Pretty obvious this needs to be backported:

TTbar, 13 TeV, no PU, AODSIM 
- FullSim: 136 kB / event (3000 events, RelVal)
-  FastSim before: 210 kB / event ( 100 events, private)
-  FastSim after: 136 kB /event (100 events, private)

The absolute gain (~80 kB / event) is expected to be constant versus PU

**Pull request merged**
