### PR TITLE
Fill time and uncertainties for slimmed primary vertices

### PR DESCRIPTION
**Pull request by lgray**
Fill timing information for miniaod slimmed vertices.

### CODE REVIEW

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
@bendavid

**Comment by perrotta** [comment]
@lgray please apply code checks so that tests can be started

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
> Fill timing information for miniaod slimmed vertices.

@lgray 
please provide estimates for size on disk for current (2017) data or MC.
If it's visibly increasing (e.g. more than 10 bytes per event in ttbar PU35 or similar), the change should be implemented only in context of phase-2 timing workflows.

**Comment by lgray** [comment]
@slava77 The matrix in the vertex class was already larger, just not being filled (so it was likely zeroes). In the case where there is no timing that does not change. Essentially your requested alteration is already there.

**Comment by slava77** [comment]
On 10/17/17 11:39 AM, Lindsey Gray wrote:
> @slava77 <https://github.com/slava77> The matrix in the vertex class was
> already larger, just not being filled (so it was likely zeroes). In the
> case where there is no timing that does not change. Essentially your
> requested alteration is already there.

right, thanks for the reminder that the underlying storage is the same
size suitable for 4D.
OK, assuming we don't fill some random numbers with this PR.

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/20911	d89db92
- complete the assignment of vertex parameters for slimmed vertices to include the time dimension 
- jenkins tests pass and comparisons show no differences (all tested workflows still have offlineSlimmedPrimaryVertices using without time in the fit)

**Comment by slava77** [comment]
assign upgrade

**Comment by kpedro88** [comment]
+1
(no significant change in relval file size, as expected)

**Comment by davidlange6** [comment]
merge

**Pull request merged**
