### PR TITLE
Switch from sprintf to std::to_string in DQM/L1TMonitor

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

This avoids a problem compiling under UBSAN where the compiler gives an error for the sprintf.

#### PR validation:

Compiling using an UBSAN build no longer generates an error.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
ping @cms-sw/dqm-l2

**Comment by jfernan2** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
