### PR TITLE
Run3-hcx352 Try to avoid wrong list of SD names of HCAL while using DD4hep

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

ry to avoid wrong list of SD names of HCAL while using DD4hep

#### PR validation:

Tested using a script in Geometry/HcalCommonData/test/python

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
@bsunanda , how this PR may affect 2022 and 2023 productions?

**Comment by civanch** [comment]
+1

**Comment by bsunanda** [comment]
@civanch I really do not know the consequence. I hope this will avoid the mismatch of SD's from DDD and DD4hep for HCAL

**Pull request merged**
