### PR TITLE
Update TSG tests and Relval Steps to use new run3_[hlt|data]_relval GTs

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
#### PR description:

Update TSG tests and Relval Steps to use new run3_[hlt|data]_relval GTs

#### PR validation:

TSG tests

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by missirol** [comment]
One minor comment: as far as I understand, `138.3` does not need `run3_data_relval`.

```bash
> runTheMatrix.py -nel 138.3 

138.3  RunMinimumBias2021Splash+COPYPASTER3+RECODR3Splash+HARVESTDR3 [1]: input from: /MinimumBias/Commissioning2021-v1/RAW with run [] 
                                           [2]: cmsDriver.py step2  -s NONE --conditions auto:run1_mc --output '[{"t":"RAW","e":"ALL"}]' --customise_commands "process.ALLRAWoutput.fastCloning=cms.untracked.bool(False)" --era Run3 -n 100 
                                           [3]: cmsDriver.py step3  --conditions auto:run3_data_relval -s RAW2DIGI,L1Reco,RECO,PAT,ALCA:SiStripCalZeroBias+SiStripCalMinBias+TkAlMinBias+EcalESAlign,DQM:@standardDQMFakeHLT+@miniAODDQM --datatier RECO,MINIAOD,DQMIO --eventcontent RECO,MINIAOD,DQM --data  --process reRECO --scenario pp --era Run3 --customise Configuration/DataProcessing/RecoTLR.customisePostEra_Run3 -n 2
                                           [4]: cmsDriver.py step4  -s HARVESTING:@standardDQMFakeHLT+@miniAODDQM --conditions auto:run3_data_relval --data  --filetype DQM --scenario pp --era Run3 -n 100 
```

It could be fixed with this patch [1], but I think this is something that could be fixed later on without delaying this PR.

[1]
```diff
diff --git a/Configuration/PyReleaseValidation/python/relval_steps.py b/Configuration/PyReleaseValidation/python/relval_steps.py
index c6e9035e761..c90402fad6b 100644
--- a/Configuration/PyReleaseValidation/python/relval_steps.py
+++ b/Configuration/PyReleaseValidation/python/relval_steps.py
@@ -2246,6 +2246,7 @@ steps['RECODR3']=merge([{'--scenario':'pp',
                          '--customise':'Configuration/DataProcessing/RecoTLR.customisePostEra_Run3'},dataReco])
 
 steps['RECODR3Splash']=merge([{'-n': 2,
+                               '--conditions':'auto:run3_data',
                                '-s': 'RAW2DIGI,L1Reco,RECO,PAT,ALCA:SiStripCalZeroBias+SiStripCalMinBias+TkAlMinBias+EcalESAlign,DQM:@standardDQMFakeHLT+@miniAODDQM'
                               },steps['RECODR3']])
```

**Comment by srimanob** [comment]
@cmsbuild please test

Just re-trigger the test, to get proper bin-by-bin DQM comparison.

**Comment by srimanob** [comment]
@Martin-Grunewald 
What will be the relation between `run3_[hlt|data]` and `run3_[hlt|data]_relval`? Will ones with `_relval` be the last developed menu?
Thx.

**Comment by Martin-Grunewald** [comment]
```run3_[hlt|data]``` contain in the GT the L1T menu used when actually taking the data.
```run3_[hlt|data]_relval``` contain in the GT a more recent L1T menu, used to run relvals with more recent HLT menu in CMSSW in turn using the seeds of the new L1T menu, on older data.

We had the same in Run-2: ```run2_[hlt|data]``` and  ```run2_[hlt|data]_relval``` for Run-2

**Comment by srimanob** [comment]
+Upgrade

**Comment by missirol** [comment]
@cms-sw/pdmv-l2 , could you please review this short PR?

**Comment by kskovpen** [comment]
+pdmv

**Comment by perrotta** [comment]
+1

**Pull request merged**
