### PR TITLE
EMTF: Add/Improve text files with some documentation

### PR DESCRIPTION
**Pull request by jiafulow**
#### PR description:

This PR improves the text files (`.md`) currently in L1Trigger/L1TMuonEndCap and adds an additional text file. Specifically:

- `test/globaltags.md` is updated so that it is rendered better on GitHub.
- `test/tools/README.md` is renamed to `test/primconv.md`. It is also updated so that it is rendered better on GitHub.
- `test/unpacker.md` is added. It contains some basic instructions about the EMTF unpacker.

There are no changes in the codes. Only the text files were added/modified. If anyone wants to include more changes to these text files, please feel free to do so in this PR. The files as rendered on GitHub currently:

- `test/globaltags.md`: [globaltags.md](https://github.com/jiafulow/cmssw/blob/emtf_patch_20200710/L1Trigger/L1TMuonEndCap/test/globaltags.md)
- `test/primconv.md`: [primconv.md](https://github.com/jiafulow/cmssw/blob/emtf_patch_20200710/L1Trigger/L1TMuonEndCap/test/primconv.md)
- `test/unpacker.md`: [unpacker.md](https://github.com/jiafulow/cmssw/blob/emtf_patch_20200710/L1Trigger/L1TMuonEndCap/test/unpacker.md)

The reason to keep these text files in the repo is because they are very easy to lose. Up to now, they have been only circulated in emails. We don't expect to be actively updating these text files, so it won't add more work to the CMSSW maintainers. Though, the unpacker info may be updated in the near future as Jared Sturdy has started working on including GE1/1 in the EMTF unpacker.

#### PR validation:

N/A

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

---
Notifications: @abrinke1 @eyigitba @jsturdy

### CODE REVIEW

**Comment by silviodonato** [comment]
please test

**Comment by silviodonato** [comment]
@rekovic do you have any comments?

**Comment by silviodonato** [comment]
ping @rekovic

**Comment by rekovic** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
