### PR TITLE
Run2-alca111 Make 2 applications up dated

### PR DESCRIPTION
**Pull request by bsunanda**
Two analyzers (1) to study IsoTrack trigger (2) to study and validate isotrack response in data & MC are updated

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@lpernie @arunhep Can you please approve this PR?

**Comment by lpernie** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
