### PR TITLE
Phase2-hgx359XX Modify Three test scripts to test if the bug-fix for HGCalGeometry Works

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Revert the false flag in the appropriate place in HGCalGeometry and has been tested for V17 geometry. Thanks to Andrea Bocci and the HGCal Reco team.

After making this PR,  I see there is already PR #45782 which has made the same change in the HGCalGeometry code. So I am removing the fix in this code, but the test codes can remain

#### PR validation:

Tested using the cfg files in Geometry/HGCalGeometry/test/python

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

To be backported to CMSSW_18_1_X

### CODE REVIEW

**Comment by bsunanda** [comment]
Type BugFix

**Comment by bsunanda** [comment]
Type Urgent

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by bsunanda** [comment]
@srimanob Please approve this PR

**Comment by bsunanda** [comment]
@srimanob Please approve this PR

**Comment by bsunanda** [comment]
@srimanob Please approve this PR

**Comment by srimanob** [comment]
+Upgrade

I think PR description should be updated too as the "Revert the false flag.." part is not for this PR anymore.

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
