### PR TITLE
changing query for AlCa Egamma workflow for Heavy Ions

### PR DESCRIPTION
**Pull request by jmduarte**
@matteosan1 Do you think this change is appropriate. I've checked that it works, but I want to make sure Egamma is ok with it. @diguida @mmusich This is so that the AlCa HLT workflow can run for Heavy Ions runs because the HLT path names in the Heavy Ion runs changed:
e.g.
HLT_HISinglePhoton40_Eta2p1_v1

### CODE REVIEW

**Comment by matteosan1** [comment]
Hi Javier,
thanks for looking into that. I was about to make a similar PR that
essentially was doing what you have done.
I have two comments though:
- have you checked that moving from pathName.find("XXX")==4 to
pathName.find("XXX")!=npos doesn't spoil the logic for the double triggers
in the p-p menu ?
- In my tests in order to get the plots I had to also change line 134 since
most (if not all the modules with saveTags=True doesn't have "Filter" in
their names). We have probably tested different menus but please
cross-check that it works as well without this change.

**Comment by mmusich** [comment]
please test

**Comment by jmduarte** [comment]
@mmusich I just updated the PR based on Matteo's recommendation. Could we re-test? Thanks! 

Javier

**Comment by mmusich** [comment]
please test

**Comment by deguio** [comment]
+1
hey, fine for me. but isn't this something we would like to have in 76 and 80 as well?
I don't find the corresponding PRs.
F.

**Comment by diguida** [comment]
@deguio thanks. It is a hotfix for HI data taking.
@jmduarte can you please forward port this to 76X and 80X?

Thnaks

**Comment by diguida** [comment]
@davidlange6 as discussed at the ORM meeting, please integrate this PR.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
