### PR TITLE
add the L1 2015 v2 menu, without changing the default

### PR DESCRIPTION
**Pull request by fwyzard**
port #6960 to CMSSW 7.4.x
include #6979 
include part of #6920

### CODE REVIEW

**Comment by davidlange6** [comment]
@fwyzard - as an early warning, we may need a python2.6 compatible version of these changes to use in the computing infrastructure… is that doable?

**Comment by davidlange6** [comment]
I meant to add: e.g., without OrderedDict...

**Comment by Martin-Grunewald** [comment]
Presumably we could use:
```
        import FWCore.ParameterSet.DictTypes as DictTypes
        custMap=DictTypes.SortedKeysDict()
```

**Comment by davidlange6** [comment]
good - remind me what workflow is a good test of this new feature?

**Comment by Martin-Grunewald** [comment]
I tested DictTypes sometime back and it worked for me in some specific HLT test.
Since it is generic, simply make up a cmsDriver command with at least
two --customize and check that in the generated py file they are applied in
the order they are given on the cmsDriver cmd line. Without the fix the order may or
may not be the cmdline order, with the fix it must always be in the cmdline order.

eg like this one:
```
cmsDriver.py X --step=RAW2DIGI,L1,DIGI2RAW --conditions=auto:run2_mc --customise=SLHCUpgradeSimulations/Configuration/postLS1Customs.customisePostLS1 --customise=L1Trigger/L1TCalorimeter/L1TCaloStage1_customForHLT.customiseL1EmulatorFromRaw --customise=HLTrigger/Configuration/CustomConfigs.L1REPACK --no_exec --mc --filein=file:RelVal_Raw_Fake_MC.root --number=100 --processName=TEST --python_filename=X_MC.py --customise=L1Trigger/Configuration/L1Trigger_custom.customiseResetPrescalesAndMasks
```
but do not really run it....

**Comment by Martin-Grunewald** [comment]
...in cmsRun :)

**Pull request merged**
