### PR TITLE
updating relval which uses evtgen

### PR DESCRIPTION
**Pull request by alberto-sanchez**
The idea here is to use the latest evt and decay file in evtgen 1.6, test the embed option. and test the ptfilter

### CODE REVIEW

**Comment by efeyazgan** [comment]
please test

**Comment by efeyazgan** [comment]
+1

**Comment by davidlange6** [comment]
hi @alberto-sanchez - which relval # in runTheMatrix does this update?

**Comment by alberto-sanchez** [comment]
hi @davidlange6 , that should be 541 and 545.

**Comment by davidlange6** [comment]
please test workflow 541,545

**Comment by davidlange6** [comment]
please test workflow 541.0,545.0

**Comment by davidlange6** [comment]
merge

**Pull request merged**
