### PR TITLE
Add ActivityRegistry signals for between Events

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

Added a pair of signas that happens when the source is determining what the next transition and another pair when the Event data products are being deleted.

#### PR validation:

Code compiles.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by makortel** [comment]
Comparison differences are related to https://github.com/cms-sw/cmssw/issues/39803

**Comment by makortel** [comment]
+core

**Comment by makortel** [comment]
@cms-sw/orp-l2 Could this PR be merged? Thanks!

**Pull request merged**
