### PR TITLE
Add plotting utilities to generate Tracker maps given user input

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

Title says it all. Useful when debugging conditions and or local reconstruction issues.
Supports two modes:
   * `printPixelTrackerMap detid1 detid2 detid3 ...`
   * `printPixelTrackerMap --input-file input.txt`

#### PR validation:

Run the script with a [user generated list](https://github.com/user-attachments/files/16740445/output3.txt) and obtained the following map:

Phase1PixelSummaryMap

Or:

```console
 cut -d' ' -f1 $CMSSW_RELEASE_BASE/src/CalibTracker/SiStripCommon/data/SiStripDetInfo.dat | shuf -n 5000 | paste -sd ' ' - | xargs printStripTrackerMap
 ```

generates:

SiStripsTkMaps

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

N/A

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by antoniovilela** [comment]
ping (to make bot change milestone)

**Comment by mmusich** [comment]
ping @cms-sw/dqm-l2

**Comment by tjavaid** [comment]
+1

**Comment by smuzaffar** [comment]
@mmusich , unit test `testSiStripPayloadInspector` from `CondCore/SiStripPlugins` package start failing with error [a]. I think change in the PR might be causing it, can you please check ?

[a]
```
## Exercising Threshold plots 
{"version": "1.0","annotations": {"payload_type":"SiStripThreshold","title":"SiStrip High threshold values (checked per APV)","type":"Histo1D","x_label":"SiStrip High threshold values (cheched per APV)","y_label":"entries"},"data": [ { "x":0, "y":5864 }, { "x":1, "y":6328 }, { "x":2, "y":6372 }, { "x":3, "y":6318 }, { "x":4, "y":5924 }, { "x":5, "y":217325 }, { "x":6, "y":4582 }, { "x":7, "y":4393 }, { "x":8, "y":4708 }, { "x":9, "y":5043 }]}
## Exercising SiStripTkMaps plots 

 *** Break *** segmentation violation



===========================================================
There was a crash.
This is the entire stack trace of all threads:
===========================================================
#0  0x000014af79e75e0b in waitpid () from /lib64/libc.so.6
#1  0x000014af79dc9747 in do_system () from /lib64/libc.so.6
#2  0x000014af7e063f3d in TUnixSystem::StackTrace() () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02853/el8_amd64_gcc12/cms/cmssw-patch/CMSSW_14_2_X_2024-09-06-1100/external/el8_amd64_gcc12/lib/libCore.so
#3  0x000014af7e061a14 in TUnixSystem::DispatchSignals(ESignals) () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02853/el8_amd64_gcc12/cms/cmssw-patch/CMSSW_14_2_X_2024-09-06-1100/external/el8_amd64_gcc12/lib/libCore.so
#4  <signal handler called>
#5  0x000014af83e75631 in SiStripTkMaps::drawMap(TCanvas&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02853/el8_amd64_gcc12/cms/cmssw-patch/CMSSW_14_2_X_2024-09-06-1100/lib/el8_amd64_gcc12/libDQMTrackerRemapper.so
```

**Comment by mmusich** [comment]
@smuzaffar 

>  can you please check ?

Not earlier than next week

**Comment by mmusich** [comment]
>   can you please check ?

For the record, https://github.com/cms-sw/cmssw/pull/45954 should fix it.

**Pull request merged**
