### PR TITLE
Updates to Tracksters visualization in Fireworks

### PR DESCRIPTION
**Pull request by chrispap95**
#### PR description:

This PR introduces the following updates:
- The `FWTracksterHitsProxyBuilder` edges visualization now displays edges that connect adjacent layers using a different color. When a single layer is selected, only incoming or outcoming edges to that specific layer are displayed.
- In `FWItemValueGetter`, tracksters will now have their values displayed in the tables.
- A new proxy called 'FWTracksterLayerssProxyBuilder' is introduced that displays the `LayerClusters` as circles. 

#### PR validation:

I have captured cmsShow displays of the new proxy [here](https://cernbox.cern.ch/index.php/s/rFbnFZPOmhdFv8v).

@rovere

### CODE REVIEW

**Comment by rovere** [comment]
@cmsbuild please test

**Comment by rovere** [comment]
ping.

**Comment by alja** [comment]
+1

**Comment by alja** [comment]
@rovere I'm sorry I missed it earlier.

**Comment by qliphy** [comment]
random differences in 11634.911 are a recent known general issue.  But let's trigger another test.

**Comment by qliphy** [comment]
please test

**Comment by qliphy** [comment]
+1

**Comment by rovere** [comment]
@alja No Problem! Thanks a lot for the super-fast approval.

**Pull request merged**
