### PR TITLE
modify L2MuonSeedGeneratorFromL1T to deal with possible L1 zero charge (backport)

### PR DESCRIPTION
**Pull request by sarafiorendi**
Backport of #14135 to 80X

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by Martin-Grunewald** [comment]
@davidlange6
OK, put in if possible (81X PR is #14135)

**Comment by cvuosalo** [comment]
@cmsbuild please test
Comparisons did not complete

**Comment by cvuosalo** [comment]
+1

For #14136 d8d6ffb3efaae252075bf66c9c4e2ffc3905f339

Corrected handling of invalid or zero L1 objects in L2MuonSeedGeneratorFromL1T.

#14135 is the 81X version of this PR, and it has already been approved.

The code changes are satisfactory. Jenkins tests against baseline CMSSW_8_0_X_2016-04-20-1100 show no significant differences, except for workflows 1330.0_ZMM_13 and 	25202.0_TTbar_13, where the DQM plots show numerous small HLT-related changes expected for this PR. An additional test of RelValZMM_13 with #14147 included against baseline CMSSW_8_0_X_2016-04-18-2300 was performed using this file:
`/store/relval/CMSSW_7_1_20_patch2/RelValZMM_13/GEN-SIM/MCRUN2_71_V1_GsRealBS-v1/00000/72F3AF71-C981-E511-87E5-0025905A6088.root`
As seen in #14135, the results show improved HLT muon efficiency, but the effects are even greater because in 80X L1 muon objects have the L1 charge problem in the overlap and endcap regions, while in 81X this problem only occurs in the overlap region. Many HLT-related muon DQM plots are now filled where they were empty in the baseline. Here's an example:
pt

**Comment by davidlange6** [comment]
+1

**Pull request merged**
