### PR TITLE
[RFC] Test clang-tidy --checks performance-inefficient-algorithm

### PR DESCRIPTION
**Pull request by fwyzard**
See the description at https://clang.llvm.org/extra/clang-tidy/checks/performance-inefficient-algorithm.html .

### CODE REVIEW

**Comment by davidlange6** [comment]
does the same thing as #29928?

**Comment by fwyzard** [comment]
Actually, I think both #29927 and #29928 do not flag anything new: these changes should already be flagged by the existing checks.

**Comment by alja** [comment]
+1

**Comment by pohsun** [comment]
+1

**Comment by ggovi** [comment]
+1

**Comment by mrodozov** [comment]
- note
keep it

**Pull request closed without merging**
