### PR TITLE
Bug fixes and adding a Fake2 HLT menu (91X)

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
Adding a Fake2 HLT menu (91X)
Based on CMSSW_9_1_X_2017-03-05-2300

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
eos problem - let's try again

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by Martin-Grunewald** [comment]
type bug-fix

**Comment by davidlange6** [comment]
+1

(but there are certainly more self-documenting names for this new menu than 'fake2'.. perhaps one could be considered in the near future. Thanks )

**Pull request merged**
