### PR TITLE
implementation of number of cluster trend plot in wheel/layer, number…

### PR DESCRIPTION
**Pull request by manoni**
Implementation of several plots in SiStripMonitorCluster package: number of cluster trend in wheel/layer, number of cluster per ring and per layer. Change in apv charge median plot switch in SiStripMonitorDigi package

### CODE REVIEW

**Comment by fioriNTU** [comment]
@manoni can we have this PR merged, you have to port it to 90X

**Comment by boudoul** [comment]
actually this is the other way round, it should go first to 90X, therefore @manoni , could you please make the equivalent PR for 90X first ?

**Comment by boudoul** [comment]
and then once the PR in 90X is fine and merged, then  the backport can be prepared

**Comment by dmitrijus** [comment]
+1

**Comment by fioriNTU** [comment]
can someone merge this, please?

**Comment by dmitrijus** [comment]
will bring it up at the next ORP

**Comment by dmitrijus** [comment]
Actually, this can't be merged, since the target is CMSSW_8_1_X.
If this was merged 90x, please provide a link to the PR. Please make a PR to CMSSW_9_0_X.

**Comment by boudoul** [comment]
Right I request to @manoni  the 90X PR earlier in this thread, 3 weeks ago ... :(

**Comment by fioriNTU** [comment]
The PR for 90X is merged, #17304

**Comment by boudoul** [comment]
oh great  i missed it ! apologies and thanks for the PR

**Comment by dmitrijus** [comment]
Also, what's the point of using it in 81x? 2017 data taking will use 90x.

**Comment by venturia** [comment]
speaking of backporting: is this in 80x? It will be used for the legacy rereco and we agree that DQM development can be backported there.

**Comment by dmitrijus** [comment]
Ping! Please close this and if this is really needed for legacy rereco, open a 80x PR.
I will sign it, but you will need to convince @davidlange6 to merge it (if it isn't too late).

**Comment by boudoul** [comment]
Hi @dmitrijus , thanks for the reminder, I just created the backport in 80X for the legacy re-reco : 
#17592 
Instead there is no real need  for 81X (this PR can therefore be closed) .
Apologies for delays and mix between  the release queues ...

**Comment by boudoul** [comment]
Hi @manoni , please just push the 'close pull request ' button of this PR , I can't do myself and should be done by the original author of the PR

**Pull request closed without merging**
