### PR TITLE
HLT menu development for `12_6_X` (2/N)

### PR DESCRIPTION
**Pull request by missirol**
backport of #40339

#### PR description:

Development of HLT menus for `CMSSW_12_6_X`.

It includes the migration of the HLT menus to the `ConfDB` template for `CMSSW_12_6_0`.

This PR includes the integration of the following JIRA tickets.

  - [CMSHLT-2583](https://its.cern.ch/jira/browse/CMSHLT-2583): [TSG] Review of PS columns in the combined HLT menu
  - [CMSHLT-2586](https://its.cern.ch/jira/browse/CMSHLT-2586): [TSG] Move seed of `DST_HLTMuon_Run3_PFScoutingPixelTracking` before HLT prescale
  - [CMSHLT-2589](https://its.cern.ch/jira/browse/CMSHLT-2589): [JME] Add HLT PFMET collections to `ReleaseValidation` EventContent
  - [CMSHLT-2590](https://its.cern.ch/jira/browse/CMSHLT-2590): [B2G] Removal of AK8Jet+TrimMass and AK8PFHT+TrimMass triggers from the combined menu

In addition, the real-data EDM input of the HLT-HIon tests is updated to use events from HIRun2022A (standard HIon Raw, not RawPrime), see https://github.com/cms-sw/cmssw/pull/40339#issuecomment-1354606056.

#### PR validation:

TSG tests.

#### If this PR is a backport, please specify the original PR and why you need to backport that PR. If this PR will be backported, please specify to which release cycle the backport is meant for:

#40339

Development of HLT menus for 2023 data-taking.

### CODE REVIEW

**Comment by missirol** [comment]
please test

**Comment by missirol** [comment]
please test

**Comment by missirol** [comment]
+hlt

(Only a few differences reported by DQM due to the update in name of the HLT "Fake*" and frozen menus.)

**Comment by perrotta** [comment]
+1

**Pull request merged**
