### PR TITLE
use `@standardDQM` for Run-3 re-HLT workflows

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

Title says it all, in reply to https://github.com/cms-sw/cmssw/pull/40261#discussion_r1109496855.

#### PR validation:

Run successfully `runTheMatrix.py -l 140.043 -t 4 -j 8` and `runTheMatrix.py -l 139.004 -t 4 -j 8`.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Not a backport. I think it might be useful to backport to 13.0.x.

### CODE REVIEW

**Comment by mmusich** [comment]
test parameters:
   * workflows = 140.003, 140.023, 140.043, 140.063

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
> DQMHistoSizes: changed ( 139.004,... ): 39899.932 KiB HLT/JME
DQMHistoSizes: changed ( 139.004,... ): 12323.616 KiB HLT/Tracking
DQMHistoSizes: changed ( 139.004,... ): 12284.354 KiB HLT/EXO
DQMHistoSizes: changed ( 139.004,... ): 11211.193 KiB HLT/BTV
DQMHistoSizes: changed ( 139.004,... ): 10388.740 KiB HLT/SiStrip
DQMHistoSizes: changed ( 139.004,... ): 5333.370 KiB HLT/Pixel
DQMHistoSizes: changed ( 139.004,... ): 4813.427 KiB HLT/TOP
DQMHistoSizes: changed ( 139.004,... ): 4466.368 KiB HLT/HIG
DQMHistoSizes: changed ( 139.004,... ): 3494.898 KiB HLT/EGM
DQMHistoSizes: changed ( 139.004,... ): 3211.306 KiB HLT/SUSY

as expected now there is HLT monitoring

**Comment by srimanob** [comment]
+Upgrade

Clarifying on what DQM should be used Run3-reHLT.

**Comment by mmusich** [comment]
@cms-sw/pdmv-l2 any objections to this changes?

**Comment by kskovpen** [comment]
+pdmv

**Comment by perrotta** [comment]
+1

**Comment by missirol** [comment]
> I think it might be useful to backport to 13.0.x.

Since I agree with this, I opened the 13_0_X backport in #40872.

**Comment by mmusich** [comment]
> Since I agree with this, I opened the 13_0_X backport in https://github.com/cms-sw/cmssw/pull/40872.

thanks. Sorry, I planned to do it, but then forgot about it...

**Pull request merged**
