### PR TITLE
add abs(dxy) plot in tracking DQM

### PR DESCRIPTION
**Pull request by mtosi**
back port PR https://github.com/cms-sw/cmssw/pull/14822

### CODE REVIEW

**Comment by dmitrijus** [comment]
+1

**Comment by VinInn** [comment]
@cmsbuild , please test

**Comment by VinInn** [comment]
would be useful to get this in next 8_0_X patch... (or whatever will run in express and prompt)

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
