### PR TITLE
Phase2-hgx359I: Modify some of the XML files to lead toward V19 Geometry of HGCal

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Modify some of the XML files to lead toward V19 Geometry of HGCal

#### PR validation:

Started testing using the cfg files in Geometry/HGCalCommonData/test/python

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by srimanob** [comment]
+Upgrade

**Comment by bsunanda** [comment]
+geometry

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
