### PR TITLE
Updated Sherpa RelVal files

### PR DESCRIPTION
**Pull request by thuer**
Updated the RelVal samples to be inline with the updates to the Sherpa version

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@thuer , can you please fix the file permission of
```
-rw-r----- 1 cvmfs cvmfs 1450850 Aug 10 11:55 /cvmfs/cms.cern.ch/phys_generator/gridpacks/slc6_amd64_gcc530/13TeV/sherpa/2.2.1/sherpa_ZtoEE_0j_OpenLoops_13TeV_MASTER.tgz
```
it should be world readable

**Comment by thuer** [comment]
I actually changed the permissions right after copying the new packs, I don't know why they do not update on cvmfs (I thought everything is copied/linked from eos)
eos ls -l 
/eos/cms/store/group/phys_generator/cvmfs/gridpacks/slc6_amd64_gcc530/13TeV/sherpa/2.2.1/
-rw-r--r--   2 thuer    zh            1444139 Aug 10 13:09 sherpa_ZtoEE_0j_BlackHat_13TeV_MASTER.tgz
-rw-r--r--   2 thuer    zh            1450850 Aug 10 11:55 sherpa_ZtoEE_0j_OpenLoops_13TeV_MASTER.tgz

**Comment by smuzaffar** [comment]
can you do it again? Right now workflow 534.0 fails because of wrong permissions?

**Comment by thuer** [comment]
I recreated the whole directories on eos and copied the two files again, now the whole directory is empty..
I do not know how to fix this, on eos the directories are there and have the right permissions

**Comment by thuer** [comment]
now they appeared with the right permissions, I guess it takes a couple of hours to sync the changes from eos

**Comment by smuzaffar** [comment]
looks good now. wf 534.0 now runs fine
```
534.0_sherpa_ZtoEE_0j_OpenLoops_13TeV_MASTER+sherpa_ZtoEE_0j_OpenLoops_13TeV_MASTER+HARVESTGEN Step0-PASSED Step1-PASSED  - time date Thu Aug 11 16:47:37 2016-date Thu Aug 11 16:45:34 2016; exit: 0 0
1 1 tests passed, 0 0 failed
```

**Comment by smuzaffar** [comment]
@thuer , we are missing generator signatures here :-)
@davidlange6 , we can merge it as it only contains updates for relval samples

**Comment by thuer** [comment]
+1

**Pull request merged**
