### PR TITLE
Prepare for concurrent IOVs, L1Trigger

### PR DESCRIPTION
**Pull request by wddgit**
Change the return type of ESProducer produce methods
from shared_ptr to unique_ptr.

### CODE REVIEW

**Comment by wddgit** [comment]
please test

**Comment by fabiocos** [comment]
@thomreis @rekovic this looks another round of technical updates, could you please check it?

**Comment by thomreis** [comment]
Hi @fabiocos 
I did and made a comment. Maybe it did not get forwarded in the github hiccup yesterday.

**Comment by wddgit** [comment]
I did not get an email when the comment was originally submitted, but I see your comment now when I look at the webpage on GitHub. Tomorrow I will make the change requested in your comment (I'm on a vacation day today).

**Comment by wddgit** [comment]
please test
I pushed a commit that removes the unused using directives. This should resolve the comment from @thomreis

**Comment by thomreis** [comment]
+1

**Comment by fabiocos** [comment]
+1

differences are in the L1T area, likely due to the non-reproducibility under investigation. @thomreis are there progress on this?

**Pull request merged**
