### PR TITLE
BeamSpot scenario Realistic25ns13TeVEarly2017CollisionVtxSmearingParameters: smallest possible fix

### PR DESCRIPTION
**Pull request by franzoni**
the Realistic25ns13TeVEarly2017CollisionVtxSmearingParameters
was 1-letter misspelled.

test:

` cmsDriver.py TTbar_13TeV_TuneCUETP8M1_cfi  --conditions auto:phase1_2017_realistic -n 10 --era Run2_2017 --eventcontent FEVTDEBUG --relval 9000,50 -s GEN,SIM --datatier GEN-SIM --beamspot Realistic25ns13TeVEarly2017Collision --geometry DB:Extended --no_exec`

@arunhep @rmanzoni 
thanks @fabozzi !

### CODE REVIEW

**Comment by franzoni** [comment]
please test

**Comment by franzoni** [comment]
the tests run by the bot won't exercise the scenario.
The cmsDriver.py of above does.


@civanch , @davidlange6 
can you please sign/bless ?

**Comment by davidlange6** [comment]
merge

**Comment by franzoni** [comment]
thanks davidlange6 !

**Pull request merged**
