### PR TITLE
EcalCondObject container iteration fix

### PR DESCRIPTION
**Pull request by bfonta**
#### PR description:

 - The ```EcalCondObjectContainer``` class currently contains a ```begin()``` and an ```end()``` functions that return ```const_iterator```s. However, these must not be used to iterate over the container. This is because internally the container is made out of two independent ```std::vector```s, and while the ```begin()``` gives back an iterator to the begin of the first vector, the end() gives an iterator to the end of the second vector. Up to recently an iteration over the container was only used in ```CalibCalorimetry/EcalTPGTools/plugins/EcalTPGParamBuilder.cc``` to print debug messages and it was protected by counters that only allowed the first 10 iterations, effectively iterating only on the first internal vector. Only recently, with the addition of the ECAL local reconstruction on GPU, iterations over the full container range were attempted (using ```std::copy```) and this resulted in segmentation violations, together with the incorrect usage of ```std::vector::reserve()``` before ```std::copy()```. In order to prevent this issue from happening again we decided that the best way is to remove the ```begin()``` function from the ```EcalCondObjectContainer``` class (a custom iterator approach was considered but deemed too complex for the problem at hand and potentially less efficient). This PR does this and replaces the existing iterations with iterations over the two internal vectors separately.

- The ```EcalTPGParamBuilder``` was modernised to be a one module and use esConsumes.

#### PR validation:

```
cmsRun RecoLocalCalo/EcalRecProducers/test/testEcalRechitProducer_cfg.py
```

### CODE REVIEW

**Comment by cecilecaillol** [comment]
please test

**Comment by fwyzard** [comment]
please test

**Comment by cecilecaillol** [comment]
+l1

**Comment by slava77** [comment]
+reconstruction

for https://github.com/cms-sw/cmssw/pull/33531	469efd0
- code changes related to reco are just in RecoLocalCalo/EcalRecProducers/test/, they look reasonable
- jenkins tests pass

**Comment by silviodonato** [comment]
kind reminder @cms-sw/alca-l2 @cms-sw/db-l2

**Comment by francescobrivio** [comment]
+alca
 - switch to esConsumes and edm::one
 - change to fix the loop on two internal vectors
 - tests passed

**Comment by silviodonato** [comment]
cc @cms-sw/ecal-dpg-l2

**Comment by thomreis** [comment]
Hi @silviodonato thank you for the heads up. ECAL DPG was involved in this developments. In fact, I am responsible for two of the commits in this PR.

**Comment by ggovi** [comment]
+1

**Comment by silviodonato** [comment]
There are two tiny changes in 10024.0 and 10084.0. Are they expected?
image
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_0_X_2021-04-29-1100+4399b8/42501/dqm-histo-comparison-summary.html
10024.0: https://tinyurl.com/yhsmdffu
10824.0: https://tinyurl.com/yzqmdk9w

**Comment by silviodonato** [comment]
please test
to refresh the comparison

**Comment by thomreis** [comment]
The backport PR #33574 is based on the same branch and does not show this difference.

**Comment by thomreis** [comment]
No differences anymore in this round of tests. Seems to have been a temporary hiccup.

**Comment by qliphy** [comment]
+1

**Pull request merged**
