### PR TITLE
[101X] [L1T][DQMOffline] Fixes for L1T jet DQMOffline

### PR DESCRIPTION
**Pull request by kreczko**
Backport of #23269

### CODE REVIEW

**Comment by thomreis** [comment]
please test

**Comment by thomreis** [comment]
+1

**Comment by dmitrijus** [comment]
+1

**Comment by thomreis** [comment]
Hi @fabiocos 
can this be merged please. We would like to have the improvements available in the offline DQM soon.

**Comment by fabiocos** [comment]
@thomreis after passing test in the master pre-release of course

**Comment by fabiocos** [comment]
+1 

tested in 10_2_0_pre4

**Pull request merged**
