### PR TITLE
[TkAl] Fix EoP Validation plotting macros

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

In response to https://github.com/cms-sw/cmssw/pull/40080#discussion_r1034821298.
   * refurbished `momentumElectronBiasValidation.C` macro;
   * applied code-format to `momentumBiasValidation.C` macro, and modified it in order to compile it together with the electron one;
   * added dedicated EoP validation plotting unit tests;

#### PR validation:

Relies on the unit tests created here, run successfully

```
scram b runtests_testEoPPlotting
```

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

N/A

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
type trk, bug-fix

**Comment by tvami** [comment]
seems like the unit test timed out?
```
/bin/sh: line 1: 28007 Aborted                 timeout 3600 sh -c 'testEoPPlotting '

---> test testEoPPlotting had ERRORS
TestTime:5
^^^^ End Test testEoPPlotting ^^^^
```
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-977702/29340/unitTests/src/Alignment/OfflineValidation/test/testEoPPlotting/testing.log

**Comment by mmusich** [comment]
> seems like the unit test timed out?

I don't think so

> `TestTime:5`

**Comment by ChrisMisan** [comment]
please test

**Comment by mmusich** [comment]
please abort

**Comment by mmusich** [comment]
I am not done with edits, please don't trigger tests yet

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
> ---> test testEoPPlotting had ERRORS

this test doesn't fail when tried in a local checkout. 
Also the [message](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-977702/29429/unitTests/src/Alignment/OfflineValidation/test/testEoPPlotting/testing.log) obtained is rather dry:
```
/bin/sh: line 1: 457766 Segmentation fault      timeout 3600 sh -c 'testEoPPlotting '
```

is there a way to run the test such that it produces the stack trace?

https://github.com/cms-sw/cmssw/blob/36a91636c0097dfd12a3e4f35c3ada86c6c322c4/Alignment/OfflineValidation/test/testEoPPlotting.cpp#L11

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by ChrisMisan** [comment]
@mmusich if this is still wip maybe it should be moved to the draft?

**Comment by mmusich** [comment]
> if this is still wip maybe it should be moved to the draft?

no, I don't see any benefit in doing so.

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
> The relvals timed out after 4 hours.

failure is unrelated, but on the bright side, [the unit test succeeded](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-977702/29616/unitTests/src/Alignment/OfflineValidation/test/testEoPPlotting/testing.log)

**Comment by tvami** [comment]
hi Marco, that's great! Should we squash the commits and test one more time and merge this?

**Comment by mmusich** [comment]
> Should we squash the commits and test one more time and merge this?

@tvami done. Feel free to test

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
+alca

**Comment by rappoccio** [comment]
+1

**Pull request merged**
