### PR TITLE
[12_0_X] Add SiStripCalCosmics ALCANANO

### PR DESCRIPTION
**Pull request by pieterdavid**
#### PR description:

This PR adds a SiStripCalCosmicsNano ALCARECO, which is SiStripCalCosmics in NanoAOD format (also known as ALCANANO); it is a backport for testing during the upcoming CRAFT run, see the discussion in the original PR https://github.com/cms-sw/cmssw/pull/34985#issuecomment-919756131 .

#### PR validation:

Compiles, `scram b runtests` and `runTheMatrix.py -l 138.1` run. The only conflict in the rebase was with the changes from https://github.com/cms-sw/cmssw/pull/35073 and trivial to resolve.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Backport of https://github.com/cms-sw/cmssw/pull/34985

CC: @robervalwalsh @mdelcourt @ataliercio @jandrejk @mmusich @tsusa @mariadalfonso @gouskos

### CODE REVIEW

**Comment by mmusich** [comment]
test parameters:
   * workflows = 7.2, 7.21, 7.22, 7.23, 7.24, 7.3, 7.4, 134.813, 136.733, 138.1, 138.2

**Comment by tvami** [comment]
backport of https://github.com/cms-sw/cmssw/pull/34985

**Comment by tvami** [comment]
+alca

**Comment by tvami** [comment]
urgent

**Comment by tvami** [comment]
> urgent

@kskovpen @srimanob @mariadalfonso we'd like this to be included in the CRAFT, please sign at your earliest convenience

**Comment by mariadalfonso** [comment]
+xpog
changes in PhysicsTools/NanoAOD/test/inspectNanoFile.py inline with master

**Comment by bbilin** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

This is a backport PR.

**Comment by qliphy** [comment]
+1

**Pull request merged**
