### PR TITLE
Custom MUON POG NANO includes default NANO

### PR DESCRIPTION
**Pull request by vlimant**
#### PR description:

since the MUPOG custom nano will always include the standard nano, the definition in the mapping should strictly include the PHYS part, so that they never get separated. (oversight on my account in  #43642 )

#### PR validation:

`runTheMatrix.py --what nano -l       2500.314 --ibeos` to success

I also verified that combining `--step NANO:@EGM+@MUPOG` leads to the inclusion of "only one PHYS"

### CODE REVIEW

**Comment by vlimant** [comment]
enable nano

**Comment by vlimant** [comment]
please test

**Comment by vlimant** [comment]
+1

**Comment by vlimant** [comment]
@cms-sw/pdmv-l2  @cms-sw/upgrade-l2 : can you please sign quickly this trivial PR so that we can get the backport going.

**Comment by subirsarkar** [comment]
+Upgrade

**Comment by AdrianoDee** [comment]
+pdmv

**Comment by antoniovilela** [comment]
@vlimant 
Please resolve conflicts.

**Comment by vlimant** [comment]
please test

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
