### PR TITLE
PPS: global alignment

### PR DESCRIPTION
**Pull request by MatiXOfficial**
#### PR description:

This PR adds alignment code for PPS, following the strategy presented in [AlCaDB meeting on 28 Sep](https://indico.cern.ch/event/959393/). In particular, this PR contains an implementation of the "global" alignment (the "relative" alignment is included in #31629). A follow up of this PR is foreseen, focusing on the inclusion of the global alignment in the PCL.

#### PR validation:

- Tests are included in the test directory.
- More tests can be found in [pps-alignment-data repository](https://github.com/CTPPS/pps-alignment-data).
- Tests for different years, fills, xangles, beta have been run, and the results are compatible with the alignment which is now uploaded to the offline DB and used for reconstruction.

### CODE REVIEW

**Comment by christopheralanwest** [comment]
please test

**Comment by christopheralanwest** [comment]
please test

**Comment by yuanchao** [comment]
@MatiXOfficial There are some build warnings found in the static build tests regarding the access of config data. The use of "get" method without token is deprecated. Could you follow this twiki page and modify accordingly? https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideHowToGetDataFromES Thank you very much.

**Comment by christopheralanwest** [comment]
please test

**Comment by silviodonato** [comment]
@cms-sw/db-l2 @cms-sw/alca-l2 do you have further comments?

**Comment by yuanchao** [comment]
+1

**Comment by ggovi** [comment]
+1

**Comment by silviodonato** [comment]
@mrodozov could you add the new package?

**Comment by mrodozov** [comment]
yes sure

**Comment by mrodozov** [comment]
done in https://github.com/cms-sw/cms-bot/commit/5f0cf581c0268052cc840f08932c2ddbf18503c3
it is again alca only, correct ?

**Comment by silviodonato** [comment]
> done in [cms-sw/cms-bot@5f0cf58](https://github.com/cms-sw/cms-bot/commit/5f0cf581c0268052cc840f08932c2ddbf18503c3)
> it is again alca only, correct ?

Yes, it's correct, thanks. @cms-sw/alca-l2

**Comment by silviodonato** [comment]
@MatiXOfficial @cms-sw/alca-l2 I think it would be good to test this new code automatically with an unit test ( see https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideDevelopersGuide )

**Comment by MatiXOfficial** [comment]
@silviodonato This PR is only the first one for the Global Alignment package. Currently I am not working on this, but hopefully in a few months I will continue my work on the package. Then I will be able to implement unit tests. For now, if it is necessary, I could implement some basic unit tests, but as I am very busy at my university, it would be inconvenient for me.

**Comment by jan-kaspar** [comment]
@silviodonato Let me add a clarification. This PR is a result of summer internship by @MatiXOfficial (which is by far over). We plan to continue this work and deploy this code in a PCL - we foresee that this could thesis work for @MatiXOfficial and a follow up PR. As for the unit tests, if you deem them strictly necessary, I think I can give it a try. On the other hand, here we speak of a package for physics calibration, thus a reasonable test would be applying the code to data - this would take time (at least minutes), we would need to assure the data availability, define acceptance criteria, ... I am not sure this is what we want for a unit test. But may I be I misunderstand the concept.

**Comment by silviodonato** [comment]
+1

**Comment by silviodonato** [comment]
@jan-kaspar Clearly it is not urgent to have some tests (relvals or unit tests) to check that the code works in the future. I think we usually have tests for this kind of alignment code, but I let @cms-sw/alca-l2 comments more on this.

**Comment by jan-kaspar** [comment]
Thanks @silviodonato , we will keep this in mind for the future development. If  @cms-sw/alca-l2 have some concrete guidelines, even better.

**Pull request merged**
