### PR TITLE
Pr80x fix duplicate tracks EMTF on top  l1t-tsg-v9.2-post-O2O-pr

### PR DESCRIPTION
**Pull request by rekovic**
This PR is conglomerate of #15978 + fixes in EMTF emulator to rid of duplicate tracks.

Once #15978 merged, this PR will become simple (the last one commit, 2 files changed).

The fix in EMTF should resolve the problem of higher rates in emulated multi-muon triggers compared to data. The problem appeared after switched to 2nd arriving LCT in the emulator.
- pending blessing in L1T DPG.

### CODE REVIEW

**Comment by rekovic** [comment]
please test

**Comment by rekovic** [comment]
Regarding failing test, they are due to missing data files.
Same comment as https://github.com/cms-sw/cmssw/pull/15978#issuecomment-249444628.

**Comment by davidlange6** [comment]
@rekovic - could you rebase this to the 80x IB? thanks

**Comment by rekovic** [comment]
@davidlange6 There are no conflicts with the already merged L1T PRs, so unless I am missing something, this should not need rebase.   Will test PR in the meantime.

**Comment by rekovic** [comment]
please test

**Comment by rekovic** [comment]
@davidlange6 Sorry, yes, will rebase to get only the two relevant commits (EMTF) remaining.

**Comment by rekovic** [comment]
rebased as #16051.
closing this one now.

**Pull request closed without merging**
