### PR TITLE
add DQM and Validation modules for doublet recovery tracks

### PR DESCRIPTION
**Pull request by mtosi**
#### PR description:
w/ the inclusion of the `hltDoubletRecoveryPFlowTrackSelectionHighPurity` collection to the track reconstruction at HLT,
there is now the need of monitoring and validating it as well

this PR simply extend the already in place DQM and Validation sequences to include this collection as well

not having the HLT menu w/ this extra collection in CMSSW, the expected output is to have empty plots, but the code will run

### CODE REVIEW

**Comment by mtosi** [comment]
please, test

**Comment by emanueleusai** [comment]
+1

**Comment by missirol** [comment]
+hlt

**Comment by perrotta** [comment]
+1

**Pull request merged**
