### PR TITLE
Tracker DB Parameters

### PR DESCRIPTION
**Pull request by ianna**
- Rebase and cleanup

### CODE REVIEW

**Comment by diguida** [comment]
+1
For the alca side, basically no changes: removed commented out includes in `CondFormats/GeometryObjects/interface/CSCRecoDigiParameters.h`, formatting change in `CondFormats/GeometryObjects/interface/PTrackerParameters.h`

**Comment by ggovi** [comment]
+1

**Comment by davidlange6** [comment]
@ianna - if you are happy with your changes, could you +1 them?

**Comment by ianna** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
