### PR TITLE
Implement SiPM nonlinearity, move SiPM parameters to CondDB

### PR DESCRIPTION
**Pull request by pdudero**
Moving SiPM parameters from python config to conditions objects, and implementing SiPM nonlinearity.

### CODE REVIEW

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by abdoulline** [comment]
Just would like to mention - callbacks are (also) activated both for SiPMs and TPs in Sunanda's PR#16056

**Comment by pdudero** [comment]
Should I retract my (only partial) fix from my PR?

**Comment by kpedro88** [comment]
No, otherwise this PR won't work. Just be prepared to rebase if #16072 is merged first.

**Comment by kpedro88** [comment]
@pdudero please rebase on `CMSSW_8_1_X_2016-10-04-2300` or `CMSSW_8_1_X_2016-10-05-1100`

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by pdudero** [comment]
Here are plots of SiPM nonlinearity using the supplied code. The plots were generated by running a single pion gun with energy set to 2 TeV, 250k events, and instrumenting the code immediately around the call to "double HcalSiPMnonlinearity::getPixelsFired(int true_pes)". The inverse function,  "inline double HcalSiPMnonlinearity::getRecoCorrectionFactor(double inpixelsfired)",  was also called purely to test the reco side,
plotnonlinearities

**Comment by civanch** [comment]
@pdudero , @kpedro88 , there are many differences which likely are expected, if not may be restart testing?

**Comment by kpedro88** [comment]
@civanch there should be differences in the 2017 workflow, but it would be best if @pdudero could show that the differences are as expected

**Comment by slava77** [comment]
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_8_1_X_2016-10-05-1100+16070/16215/validateJR/all_OldVSNew_ZMM13TeVwf1330p0/all_OldVSNew_ZMM13TeVwf1330p0c_log10HORecHitsSorted_horeco__RECO_obj_obj_energy.png
all_oldvsnew_zmm13tevwf1330p0c_log10horechitssorted_horeco__reco_obj_obj_energy
there is a 15-fold increase in the number of HO rechits in run2/2016 MC
what's happening here?

There is also a fairly significant change in Run1 MC (did we even have SiPMs back then?)
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_8_1_X_2016-10-05-1100+16070/16215/validateJR/all_OldVSNew_TTbarwf25p0/all_OldVSNew_TTbarwf25p0c_HORecHitsSorted_horeco__RECO_obj_obj_energy.png

**Comment by pdudero** [comment]
Slava,

Am I to understand that this plot came from the code attached to this 
PR? And that code prior to this PR doesn't exhibit the same behavior?

-P

**Comment by slava77** [comment]
Hi Phil

On 10/13/16 12:35 PM, pdudero wrote:
> Slava,
> 
> Am I to understand that this plot came from the code attached to this
> PR? 

yes

> And that code prior to this PR doesn't exhibit the same behavior?

yes, there is a significant change
black lines are for the baseline (CMSSW_8_1_X_2016-10-05-1100)  and red
are for CMSSW_8_1_X_2016-10-05-1100+thisPR

**Comment by kpedro88** [comment]
This PR moves a number of SiPM-related parameters from a python cfg to the database. I am trying to dump the HO conditions for run2_mc and run1_mc to make sure the parameters were translated properly. (in Run1 MC, we had some small set of test SiPMs in HO.)

**Comment by kpedro88** [comment]
Okay, here's the deal. The state of the HO parameters is kind of a mess.

From `81X_mcRun2_asymptotic_v9` (Run2 MC):
```
SiPMCharacteristics:
#     type   pixels         parLin1         parLin2         parLin3       crossTalk    auxi1           auxi2
        1    36000        1.000000        0.000000        0.000000        0.320000        0        0.000000
        2     2500        1.000000        0.000000        0.000000        0.320000        0        0.000000
        3    27370        1.000669        0.000013        0.000000        0.320000        0        0.000000
        4    38018        1.000669        0.000013        0.000000        0.320000        0        0.000000
        5    27370        1.000669        0.000013        0.000000        0.320000        0        0.000000

SiPMParameters:
#             eta             phi             dep             det     type          fcByPE     darkCurrent    auxi1           auxi2		
               -1               1               4              HO        2        4.000000        0.055000        0        0.000000
```

From `81X_mcRun1_realistic_v3` (Run1 MC):
```
SiPMCharacteristics:			   
#     type   pixels         parLin1         parLin2         parLin3       crossTalk    auxi1           auxi2
        1    36000        1.000000        0.000000        0.000000        0.320000        0        0.000000
        2      960        1.000000        0.000000        0.000000        0.320000        0        0.000000
        3    27370        1.000669        0.000013        0.000000        0.320000        0        0.000000
        4    38018        1.000669        0.000013        0.000000        0.320000        0        0.000000
        5    27370        1.000669        0.000013        0.000000        0.320000        0        0.000000

SiPMParameters:
#             eta             phi             dep             det     type          fcByPE     darkCurrent    auxi1           auxi2		
               11              64               4              HO        2        3.000000        0.000000        0        0.000000
```

Compare with: https://github.com/cms-sw/cmssw/blob/CMSSW_8_1_0_pre12/SimCalorimetry/HcalSimProducers/python/hcalSimParameters_cfi.py#L95-L114

There are a number of discrepancies.
1a) hoZecotek and hoHamamatsu PSets, used for Run1 test SiPM simulation, have dark current and cross talk values (for a while now). However, these values were just taken from the HE SiPMs and not tuned to the HO SiPMs. Probably, they should be removed.
1b) Run1 DB values for HO SiPM cells have nonzero crosstalk but zero dark current (causing Slava's observed discrepancy).
2a) ho PSet modified by run2_common for the current HO SiPMs does not have dark current or crosstalk values.
2b) Run2 DB values for HO do have dark current and crosstalk values (causing Slava's other observed discrepancy). This is reflected in the hardcode conditions, which is my fault.

We need to resolve this somehow. My preference would be to remove dark current and crosstalk values from HO everywhere: DB and hardcode. This will still lead to a discrepancy in the Run1 MC, but arguably those values never should have been used for that MC (kind of a collective oversight on our part).

@pdudero, can you update the hardcode conditions in this PR?
https://github.com/cms-sw/cmssw/blob/CMSSW_8_1_X/CalibCalorimetry/HcalPlugins/python/Hcal_Conditions_forGlobalTag_cff.py#L76 (HO dark current, should be 0)
https://github.com/cms-sw/cmssw/blob/CMSSW_8_1_X/CalibCalorimetry/HcalPlugins/python/Hcal_Conditions_forGlobalTag_cff.py#L119-L120 (HO crosstalk, should be 0)

@abdoulline, can you update the Run1 and Run2 MC tags? We might need @mmusich's help with this.

Sorry for the confusion everyone, as usual HO gets too little attention...

**Comment by abdoulline** [comment]
Kevin, do you mean what we've agreed on (Sep.15)

/afs/cern.ch/user/a/abdullin/public/SiPMs_Par_Ch_periods/SiPMs_Par_Ch_periods.txt

wasn't correctly put in DB? Sorry to bug you with this request, but to 
avoid any (stll possible) misunderstanding, could you, please, edit the 
aformentioned txt file to get it right?

NB: Do we care much about Run 1 MC HO ("full compatibility" for a 
handful of test SiPMs channels) in 81X ?

**Comment by mmusich** [comment]
@kpedro88 thanks for heads up.
I understand this might need rather invasive change in autoCond: `run1_mc`, `run2_mc` and "relatives" key will need adjustments. 
For my own understanding can you elaborate on:

> This will still lead to a discrepancy in the Run1 MC, but arguably those values never should have been used for that MC (kind of a collective oversight on our part). 

when including the `HcalSiPMs*` conditions in GT in #16048, with @franzoni, we were indeed wondering the rationale for the change in the run1 MC.

**Comment by kpedro88** [comment]
@abdoulline the contents of that txt file agree with what's in the database right now, but those values don't quite agree with what we had from `hcalSimParameters_cfi`. My other point is that, after some more thought, I think we should disable the new SiPM simulation features (dark current and crosstalk) for HO by setting zero values for the relevant parameters. These parameters were never tuned or checked vs HO data.

Here is my proposed version of the txt file:
/afs/cern.ch/user/p/pedrok/public/SiPMs_Par_Ch_periods.txt
(setting dark current and crosstalk to 0 for all HO objects/IOVs)

@mmusich so far, we have taken SiPM-related parameters (dark current, crosstalk) from `hcalSimParameters_cfi`. Now this PR accesses those conditions from the new condition objects. There are two sources of changes:
1) The values from `hcalSimParameters_cfi` were not identically ported to the DB.
2) When we first introduced the new features in the SiPM simulation, we had duplicated HE parameters for dark current and crosstalk for Run1 HO (but not Run2). I now think we should not have those values for HO at all. This will cause a change in Run1 HO MC, but really it will be reverting back to how things were before 810pre9.

**Comment by abdoulline** [comment]
OK, thank you for modifications, Kevin.
Let's proceed with updating HO parameters.

**Comment by mmusich** [comment]
this needs in any case a rebase now.

@abdoulline let me know if the new tags are coming before Monday. I need to cut new GTs anyway, I'd prefer to do everything together.
Cheers

Marco

**Comment by kpedro88** [comment]
@pdudero action items for this PR:
1) rebase
2) update hardcode conditions to correspond to what @abdoulline will put in the database for HO SiPMs: https://github.com/cms-sw/cmssw/blob/CMSSW_8_1_X/CalibCalorimetry/HcalPlugins/python/Hcal_Conditions_forGlobalTag_cff.py#L76 (HO dark current, should be 0)
https://github.com/cms-sw/cmssw/blob/CMSSW_8_1_X/CalibCalorimetry/HcalPlugins/python/Hcal_Conditions_forGlobalTag_cff.py#L119-L120 (HO crosstalk, should be 0)
3) In `HcalSiPMHitResponse::addPEnoise()`, just skip any cell with dark current <= 0

**Comment by pdudero** [comment]
Rebase to what?

**Comment by kpedro88** [comment]
The latest IB... the conflict must come from #16180, but I think it should be trivial to resolve.

**Comment by kpedro88** [comment]
@pdudero actually, you have to wait for the next IB, @lgray made a few optimizations in #16022 which just got merged

**Comment by abdoulline** [comment]
This depends on the availability of Maxim/Walter over weekend. I'll keep 
you informed.

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by kpedro88** [comment]
@abdoulline @mmusich just had the thought that we should also make sure the HO SiPM values in the 2017 tags are updated to be in sync with the Run2 values.

**Comment by abdoulline** [comment]
Yes, I've sent a request to Maxim/Walter yesterday explictly menationing 
all new tags are needed for MC/data for Run1/2/2017.

**Comment by civanch** [comment]
@pdudero , @kpedro88 , now many WF show a lot of differences, in particular fastsim which should be unrelated?

**Comment by kpedro88** [comment]
@civanch if I look back at the [previous set of comparisons](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-16070/15548/summary.html) (12 days old, so will be deleted soon), I see the same differences in WFs like fastsim.

I think this happens because of the differences in HO parameters between the cfi and the database. Changes in parameters can cause changes in random number calls in the SiPM code, which is used for HO even in fastsim.

**Comment by civanch** [comment]
+1
@ssekmen , this PR concerns Hcal and likely FastSim differences versus baseline are asseptable, however, you may have a look.

**Comment by mmusich** [comment]
@abdoulline @kpedro88 @pdudero @walterjr 

> Yes, I've sent a request to Maxim/Walter yesterday explictly mentioning all new tags are needed for MC/data for Run1/2/2017.

all the recent Hcal conditions updates are collected here: https://github.com/cms-sw/cmssw/pull/16266

You might want to test this PR with the updated conditions

**Comment by abdoulline** [comment]
Thank you, Marko, for prompt update.
   We do want to try it.

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
-1 
superseded by https://github.com/cms-sw/cmssw/issues/16315

**Pull request closed without merging**
