### PR TITLE
Improve runTheMatrix interactive shell

### PR DESCRIPTION
**Pull request by rovere**
#### PR description:

Add the possibility to submit `runTheMatrix` workflows directly from within the `interactive` session.

#### PR validation:

Tested inside an interactive session.

### CODE REVIEW

**Comment by rovere** [comment]
@cmsbuild please test

**Comment by rovere** [comment]
It is not clear to me if the failures could be somehow related to this PR...

**Comment by AdrianoDee** [comment]
Seems not to me. If I understood correctly it's a timeout error to get the data. Let's retry.

**Comment by AdrianoDee** [comment]
please test

**Comment by srimanob** [comment]
+Upgrade

**Comment by AdrianoDee** [comment]
+pdmv

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
