### PR TITLE
Use esConsumes in ParticleGun base classes

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

Base classes now declare esConsumes.

#### PR validation:

Code compiles.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
@makortel FYI

**Comment by Dr15Jones** [comment]
please test

**Comment by SiewYan** [comment]
Hi, Its look good to me.

**Comment by SiewYan** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
