### PR TITLE
Fix to make Herwig use the CMSSW seed

### PR DESCRIPTION
**Pull request by Andrej-CMS**
Dear all,

this is a quick, dirty fix to make Herwig 7 use the random number that is provided by CLHEP RandomNumberGenerator.

I need to have a deeper look into how to make this more elegant, but for now this works.

Kind regards,

Andrej

### CODE REVIEW

**Comment by efeyazgan** [comment]
please test

**Comment by efeyazgan** [comment]
please test

**Comment by qliphy** [comment]
+1

**Comment by Andrej-CMS** [comment]
@all 
can you please have a look at this?

the backport is already merged, but this is not

**Comment by fabiocos** [comment]
@Andrej-CMS how was this really verified?

**Comment by Andrej-CMS** [comment]
@fabiocos 
I ran crab jobs with the old settings, where the seed wasn't changed by CMSSW. All jobs came back with the same  output (number for total XS, events tried etc). Then I ran three task with each 5 jobs each of those 15 jobs gave a different output. I also put a simple print statement confirming that the seed passed to herwig was indeed different for each job

**Comment by fabiocos** [comment]
+1

**Pull request merged**
