### PR TITLE
[CMSSW_13_3_X backport] Add CaloIdL_MW seeded filter and split the legs of CaloIdL_TrackIdL_IsoVL filter on nanoAOD filterBits

### PR DESCRIPTION
**Pull request by ikrommyd**
#### PR description:

Same as PR https://github.com/cms-sw/cmssw/pull/43247

#### Backport:

This PR is a backport of PR https://github.com/cms-sw/cmssw/pull/43247. Backport is required for the production of NanoAODv13 from CMSSW_13.

### CODE REVIEW

**Comment by RSalvatico** [comment]
enable nano

**Comment by RSalvatico** [comment]
please test

**Comment by RSalvatico** [comment]
type egamma

**Comment by simonepigazzini** [comment]
+1

**Comment by rappoccio** [comment]
+1

**Pull request merged**
