### PR TITLE
Phase 2 forwardport FastHisto PR1130

### PR DESCRIPTION
**Pull request by NJManganelli**
This PR is a forward port of the FastHisto update in the Phase2 integration branch
https://github.com/cms-l1t-offline/cmssw/pull/1130

That PR grew overly large. It was refactored from 45 commits to 5, such that this PR can be divided into 3-4 pieces, should that be preferable to review (as separate PRs)

The first two commits are focused on reworking the EDM product workflow to match the GTT firmware. This consists of breaking up the "TrackSelection" into distinct TrackSelection (TS) and TrackVertexAssociation (TVA) modules. The emulation is updated to follow the firmware architecture, such that TS -> VertexFinding (VF) -> TVA -> TrackJets/MET, with separate configurable producers for VF, TrackJets, and MET. The TrackJets current behavior is retained as much as possible by currently making its TS module act in passthrough mode. Future PRs will update these separate TS/TVA modules with optimized selections from the GTT group. These changes are introduced now to focus the workflow-breaking updates into one (set of consecutive) PRs. Additionally, this fixes some naming of InputTags which were broken by the "l1t" naming update in September 2022. To simplify common workflows, common choices are propagated into the VertexProducer configuration, such that most uses can be simplified to ```load``` and add to ```Path/Task```, rather than verbose configuration in all workflows.
* 32ae7bc18023a1de71236937155e801dca00d808 Split TrackSelection and TrackVertexAssociation, Triplicate for GTT, Propagate new workflow to central L1T and GTT configurations, fix l1t broken tags
* 8791748abdd5214e12aff476a2050bff91d45cc9 Propagate the TS and TVA split, new VertexFinder configuration, and updated JetFinding workflow to more L1T workflows

This commit is the core/seed of the PR, which change the FastHisto emulation algorithm to match firmware (HDLS GTT firmware version around June 2023). This involves updating the histogram binning to 256, removing track pt truncation, and introducing histogram bin truncation at a late stage. 
* 4246b050ebddb84aecd9af5c9e5e50a65024dbf4 FastHisto update to match firmware approximately for June 2023

This commit updates the "l1vertices" tag to "L1Vertices," to match the convention followed by most L1T products. L1{X} is the most common, followed by "Level1{X}" for some TrackTrigger products, and then less common ones.
* 57125f0253d8c5b71c4b64d0d679a71661a41b03 Harmonize l1vertices to L1Vertices

This commit adds the new TS and TVA collections to the L1TrackObjectNtupleMaker, and inserts delete calls which have been historically missing. 
* c2e029e9dd53aec5e6a8e3923d2df5b793ed9c9a Update L1TrackObjectNtupleMaker

Validation:
scram b code-checks
scram b code-format
scram b

```runTheMatrix.py -l limited -i all --ibeos``` passes in the cms-l1t-offline Phase2 integration branch. In central CMSSW,t has the same number of passes/fails as master.

Additionally, there was extensive performance testing by GTT, PFL1, and GT experts to ensure changes in performance were as expected.

Please let me know of necessary corrections or if this needs to be broken up into 3-4 distinct PRs.

### CODE REVIEW

**Comment by epalencia** [comment]
Please test

**Comment by emanueleusai** [comment]
+1

- DQM differenced in L1T/L1TPhase2/[TkMET,TkMET_Tracks,Correlator] as expected

**Comment by epalencia** [comment]
+l1

**Comment by srimanob** [comment]
Hi @NJManganelli 
I just realize that L1T has a lot of complains in static checks. Some of them exists before, but is ignored or not realized that it exists. Could you please review the [current log](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-5bbc26/33441/llvm-analysis/runStaticChecks.log), and clarify if some of them comes from this PR.

Maybe open a issue, and follow up is a good to way to track issue, @cms-sw/l1-l2

**Comment by NJManganelli** [comment]
Hi @srimanob , there was one warning tied to this PR, which concerned the config const-ness in an exists check (L1TrackVertexAssociationProducer.cc). That section needed to be revisited, so I took this opportunity to get feedback, and I've updated it according to recommendations from Andrea Bocci and Kevin Pedro (https://mattermost.web.cern.ch/cms-o-and-c/pl/htc3mmhj9jg67bqiz9ni3oxzwh)

The changes are currently in a separate PR at the head of the branch, and if approved of, I'll backport to PR1130 (and can also squash into the main commit concerning the TrackVertexAssociation, if that is highly desirable)

I've addressed the merge conflicts for ```L1Trigger/DemonstratorTools/python/GTTFileWriter_cff.py``` as well by rebasing.

**Comment by emanueleusai** [comment]
please test

**Comment by emanueleusai** [comment]
+1

- resign

**Comment by epalencia** [comment]
+l1

**Comment by NJManganelli** [comment]
> +Upgrade
> 
> 
> 
> There will be a follow up PR as mentioned [here](https://github.com/cms-sw/cmssw/pull/42129#issuecomment-1630105165). Note that, on assignment, I am not sure why `L1Trigger/Phase2L1Taus` is not under upgrade.

Quickly correcting myself, it was a separate commit (not PR as I accidentally wrote) added into this PR at the head (which along with rebase triggered re-signing requests). Since the parallel PR1130 is still open in the integration branch, that commit will be added there (and any addenda from release managers) once this PR is certified okay.

**Comment by rappoccio** [comment]
+1

**Pull request merged**
