### PR TITLE
[HGCal] Shrinking Layer Clustering internal data structures

### PR DESCRIPTION
**Pull request by felicepantaleo**
#### PR description:

The memory footprint of the `HGCalLayerClusterProducer` grows with increasing number of events. This is solved by  `shrink_to_fit()` after `clear()` when resetting these data structures.

### CODE REVIEW

**Comment by felicepantaleo** [comment]
@cmsbuild please test

**Comment by kpedro88** [comment]
+upgrade

**Comment by slava77** [comment]
I'm not sure if this PR does the trick as it was done in #29861
- the CPU time per event in hgcalLayerClusters goes up by about 10%; this is about 0.07% of the reco time, which may be still acceptable if there was gain in memory
- the memory peak in 8-thread job running only hgcalLocalRecoSequence goes down by only 56 MiB, which is quite underwhelming and may be not worth the cost of the increase in the CPU use.

do I understand correctly that 
- before this PR the containers now "shrink_to_fit" in this PR were just growing up to the largest use in an event; 
- and now, since all the shrink_to_fit calls are made after calls to ```clear```, all reserved/allocated memory is released
?

Unlike in the TICL case in #29861 here the ```reset``` is called at the beginning of event, which means that all the memory from the heaviest event sticks around until that event is done.

I think that 
- the reset better be done at the end of the event (assuming there is no hidden interference with the edm::Event data)
- some use of ```edm::RunningAverage``` should help to improve memory use; perhaps calling .reserve based on the average would help reduce the current increase in cost (which I think is coming significantly from reallocations while growing zeroed-out containers).

**Comment by slava77** [comment]
About the time per event, I reran the local reco test on a single thread and there is no visible change in time.
The layerCluster has a parallelFor and Timing service counts just the wallclock time. The increase in time in the 8-thread job may have been artificial (or at least less under control) due to low thread efficiency of the job with hgcalLocalRecoSequence and a significant fraction  allowing layerCluster to run in parallel.
So, no significant effect on the execution time is a good news.

> the memory peak in 8-thread job running only hgcalLocalRecoSequence goes down by only 56 MiB, which is quite underwhelming and may be not worth the cost of the increase in the CPU use.

this number has no direct attribution to the HGCalLayerClusterProducer.
Single-thread profiler report shows no appreciable difference, with this PR
the memory is still the same
- 1st event https://slava77sk.web.cern.ch/slava77sk/reco/cgi-bin/igprof-navigator/CMSSW_11_2_X_2020-07-14-2300-test30753.local-hgcal.23434.21.step3.IgProf.1.MEM_LIVE/102
- 199th event https://slava77sk.web.cern.ch/slava77sk/reco/cgi-bin/igprof-navigator/CMSSW_11_2_X_2020-07-14-2300-test30753.local-hgcal.23434.21.step3.IgProf.199.MEM_LIVE/16

@felicepantaleo please clarify/confirm that you see a memory use decrease in your setup
(before I try to see even more carefully if something is wrong with my tests)

**Comment by felicepantaleo** [comment]
@slava77 I do see a memory reduction as the capacity of `clusters_v_` is now resetted, but maybe this was not the main culprit.
I will investigate more this afternoon and get back to you.

**Comment by slava77** [comment]
> Single-thread profiler report shows no appreciable difference, with this PR
> the memory is still the same

this is for 199th event 
- before 492,251,916: https://slava77sk.web.cern.ch/slava77sk/reco/cgi-bin/igprof-navigator/CMSSW_11_2_X_2020-07-14-2300-orig.local-hgcal.23434.21.step3.IgProf.199.MEM_LIVE/16
    - most changed part before 40,874,544 : https://slava77sk.web.cern.ch/slava77sk/reco/cgi-bin/igprof-navigator/CMSSW_11_2_X_2020-07-14-2300-orig.local-hgcal.23434.21.step3.IgProf.199.MEM_LIVE/188 
- after 489,254,572: https://slava77sk.web.cern.ch/slava77sk/reco/cgi-bin/igprof-navigator/CMSSW_11_2_X_2020-07-14-2300-test30753.local-hgcal.23434.21.step3.IgProf.199.MEM_LIVE/16
    - most changed part after 37,877,200 : https://slava77sk.web.cern.ch/slava77sk/reco/cgi-bin/igprof-navigator/CMSSW_11_2_X_2020-07-14-2300-test30753.local-hgcal.23434.21.step3.IgProf.199.MEM_LIVE/194

One example of a very large piece that did not change is attributed to ::setDensity call, which apparently refers to the ```density_``` data member which is not modified in this PR
- before (and after is the same) https://slava77sk.web.cern.ch/slava77sk/reco/cgi-bin/igprof-navigator/CMSSW_11_2_X_2020-07-14-2300-orig.local-hgcal.23434.21.step3.IgProf.199.MEM_LIVE/56

another goes to ::getDensity call (return by value of ```density_``` data member)
- before (and after is the same) https://slava77sk.web.cern.ch/slava77sk/reco/cgi-bin/igprof-navigator/CMSSW_11_2_X_2020-07-14-2300-orig.local-hgcal.23434.21.step3.IgProf.199.MEM_LIVE/55

The part that changes ever-so-slightly and is related to changes in this PR is in ::populate call
- before 13,916,160 https://slava77sk.web.cern.ch/slava77sk/reco/cgi-bin/igprof-navigator/CMSSW_11_2_X_2020-07-14-2300-orig.local-hgcal.23434.21.step3.IgProf.199.MEM_LIVE/413
- after 15,868,720 (an increase, actually) https://slava77sk.web.cern.ch/slava77sk/reco/cgi-bin/igprof-navigator/CMSSW_11_2_X_2020-07-14-2300-test30753.local-hgcal.23434.21.step3.IgProf.100.MEM_LIVE/391

... OK, after this more detailed look I'm a bit more convinced that I'm not looking at a broken test setup.
Please check the ```density_```  use and perhaps also move the reset call to the end of the event.

**Comment by felicepantaleo** [comment]
I'm currently checking what happens when clearing the `density_` map, which is never cleared actually

**Comment by felicepantaleo** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
running just the local HGCAL sequence in 8 threads I now get the peak RSS dropping from 9.0 GiB to 6.3 GiB. This is a really convincing improvement now.

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/30753	0845af3 
- code changes are in line with the PR description and the follow up review
- jenkins tests pass and comparisons with the baseline show no (relevant) differences
- in a local test with PU200 ttbar wf 23434.21 (D49) running just the local HGCAL sequence significant improvements are observed:
    - runtime RSS measured memory peak (from monitoring the process externally at 0.1 s sampling) goes down by 2.7 GiB on an 8-thread job and by 0.64 GiB on 1-thread job (from 2.64 GiB to 2.00 GiB)
    - CPU time of hgcalLayerClusters is down by 23% in a one-thread test (about 0.1% of total full RECO time) 
    - I'll update the mem profiler report later

**Comment by kpedro88** [comment]
+upgrade

**Comment by silviodonato** [comment]
> runtime RSS measured memory peak (from monitoring the process externally at 0.1 s sampling) goes down by **2.7 GiB** on an **8-thread job** and by 0.64 GiB on 1-thread job (from 2.64 GiB to 2.00 GiB)

@tommasoboccali @fwyzard @srimanob do you want a backport of this PR to 11_1?

**Comment by kpedro88** [comment]
@silviodonato there is already a backport in #30757

**Comment by srimanob** [comment]
@silviodonato 
RECO validation relvals for HLT TDR are running with 11_1_1. I would let it goes as it is for now and start validation call asap.

For additional PRs that affect RECO, we may review at the end for the minimal changes if benefit and see if we need limited validation for specific groups.

**Pull request merged**
