### PR TITLE
Fix numerical precision issue in 2D vertexing and wrong normalization.

### PR DESCRIPTION
**Pull request by lgray**
Wrong normalization was used every where and shouldn't affect the minimum on average of the set of vertices found. Per-event vertex multiplicities can change.

The numerical fix addresses cases where the partition function was becoming arbitrarily small when the track fake rate was large, reorganization of the floating point math mitigates this case.

### CODE REVIEW

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@lgray 
is this PR final?
https://github.com/cms-sw/cmssw/compare/CMSSW_9_0_X...gartung:from-CMSSW_9_0_X_2017-02-22-1100?w=1 has more changes
[ same as https://github.com/cms-sw/cmssw/compare/9c726e5d1a36a0388713369581c3a1d27d860fea...b061093a4212690088b9f4273223da6fcc9991c1 at the time I checked this ]

**Comment by slava77** [comment]
assign upgrade

**Comment by lgray** [comment]
would prefer to have in 90X.

**Comment by kpedro88** [comment]
+1

**Comment by slava77** [comment]
.. in fact, the warning was there since at least since 12-10-1100

**Comment by slava77** [comment]
Using 100 events with PU200 (23034) CPU time in unsortedOfflinePrimaryVertices4D increases from an average of 50 s to 190 s/event (no excessive outliers).

Log-warnings with ```no vertex found with nnn tracks and 1 vertex-candidates ``` are gone.

Can this increase in CPU (+30% of total reco time) be justified?
Can the convergence be improved?

The number of reconstructed 4D vertices is up by 60%; the average number of vertices is up slightly in the bulk; main increase in count is from ~30% events with failed vertexing now showing some non-zero results
all_sign870vsorig_ttbar14tev2023d4timingpuvtxwf23034p0c_recovertexs_offlineprimaryvertices4d__recovtx_objat_size

Typical vertex uncertainties are somewhat similar
all_sign870vsorig_ttbar14tev2023d4timingpuvtxwf23034p0c_log10recovertexs_offlineprimaryvertices4d__recovtx_obj_zerror


@kpedro88 
did your "+1" take into account this significant CPU increase?

**Comment by kpedro88** [comment]
No, I didn't realize this change would have such a large effect on resource usage

**Comment by slava77** [comment]
I'll check if #17622 can help in any way (hope that my resolution of conflicts in merging was correct).

**Comment by slava77** [comment]
The effect of #17622 on top of this PR is a 1% reduction in unsortedOfflinePrimaryVertices4D processing time, consistent with my timing measurements precision.

@kpedro88 
it's up to you to decide on the impact of this on upcoming production.
The options are, I guess:
- hold this PR and keep the buggy 4D vertexting in place
- switching to D4 by default  in production
- reduce production requests in number of events by 30%

@lgray 
I need some feedback to sign, if you will apply any imminent changes to mitigate the problem,
as it seems impractical to merge now.

**Comment by lgray** [comment]
There are no imminent changes, but certainly this version yields a higher quality reconstruction.
The vertex dZ/dT errors are well distributed and pulls look fine.

As for speeding it up, the best thing to do would be to switch to a vectorized reconstruction (as with the 1D vertex finder).

**Comment by slava77** [comment]
On 3/8/17 4:54 AM, Lindsey Gray wrote:
> There are no imminent changes, but certainly this version yields a
> higher quality reconstruction.
> The vertex dZ/dT errors are well distributed and pulls look fine.
> 
> As for speeding it up, the best thing to do would be to switch to a
> vectorized reconstruction (as with the 1D vertex finder).

I'm slightly out of context of what "vectorized reconstruction" means here.
It sounds like there is a way to change it, but not quickly.
What's the ETA for that?

**Comment by slava77** [comment]
@kpedro88 
please clarify if you keep your "+1" based on the recent inputs.

**Comment by lgray** [comment]
There is a template to follow so the implementation would not take too
long.
However, it would still require some concentrated effort to take care of it.
I could probably do it in a week or less if when I find time to concentrate
on it.

**Comment by kpedro88** [comment]
@slava77 tracker TDR production won't include this change, so we still have some time to improve CPU usage. I will keep my +1 since Lindsey has outlined a method of improvement already.

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/17610	8929924
- changes are in line with the description; in PU200 sample this apparently also fixes a problem with ~30% inefficiency of the 4D vertex inefficiency, which is a significant bugfix.
- jenkins tests pass and comparisons show no differences (only TTbar14TeV 2023 D8 wf 23234.0 could have changes, but it has no pileup to show effects)
- local tests with PU200 in D4Timing workflow show increase in CPU of unsortedOfflinePrimaryVertices4D contributing ~25% extra time to total RECO time ( close to iterative tracking time now). I'm signing off given that upgrade is happy with this increase as not (yet?) relevant to mainstream production.

**Comment by kpedro88** [comment]
@lgray this can probably be closed

**Comment by davidlange6** [comment]
Closing PR. CMSSW_9_0_X development has completed (CMSSW_9_2_X is for data taking)

**Pull request closed without merging**
