### PR TITLE
Fastsim tracking refactor, Fix for electron HLT

### PR DESCRIPTION
**Pull request by lveldere**
changes expected, 
- small changes in efficiency pixellless and tobtec step
- electron HLT works again (at least one obstacle is removed)

replaces #13246

### CODE REVIEW

**Comment by lveldere** [comment]
please test

**Comment by lveldere** [comment]
please test

**Comment by lveldere** [comment]
errors in addon tests not related to my pr

**Comment by Martin-Grunewald** [comment]
please test

**Comment by lveldere** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Comment by davidlange6** [comment]
@lveldere looks like this broken fastsim in run2

**Comment by lveldere** [comment]
Hm, did not receive this mail in my inbox.

I wonder how the github tests succeeded...

I'll make a new pr....

Lukas

**Comment by lveldere** [comment]
@davidlange6 

The issue is that I renamed a python config file,
but forgot to edit an import of this file.
Python and cmsRun still finds the file in the path.
Is there not supposed to be a safety against such cases?

**Comment by davidlange6** [comment]
> On Feb 19, 2016, at 3:42 PM, lveldere <notifications@github.com> wrote:
> 
> @davidlange6
> 
> The issue is that I renamed a python config file,
> but forgot to edit an import of this file.
> Python and cmsRun still finds the file in the path.
> Is there not supposed to be a safety against such cases?

there is - its not perfect, however. I guess you also removed all python files from the directory? I’ll have a look at your commit when you fix it.

**Comment by lveldere** [comment]
I removed the complete package in which the python file resided,
may be that's not picked up the way it ideally should.

Anyway, the PR will come on Monday.

Lukas

**Pull request merged**
