### PR TITLE
Run3-sim60 Define the new Totem T2 for Run3

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Define the geometry of the new Totem T2 detector defined for the Run3 period. The dd4hep version is in #29269

#### PR validation:

Tested with cfg files within Geometry/ForwardCommonData/test

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
@bsunanda Could you please change the PR title to name "Totem2" instead of "T2" to help those of us who cannot remember all the latest abbreviated acronyms?

**Comment by cvuosalo** [comment]
@bsunanda Even though this PR is for Run 3, I see it is only for the old DD. What is the plan to migrate Totem2 to DD4hep?

**Comment by cvuosalo** [comment]
@bsunanda I see PR #29269 has the DD4hep version. It would be good to mention it in this PR description.

**Comment by bsunanda** [comment]
@cvuosalo Please look at the next PR #29269

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade

**Comment by silviodonato** [comment]
+1

**Pull request merged**
