### PR TITLE
Fix issues with DTRecHitQuality

### PR DESCRIPTION
**Pull request by Dr15Jones**
Fixed an issue reported by the static analysis
Fixed per Run memory leaks

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
The previous test failures were from a previous violation of the C++ one definition rule. This caused the new `Histograms` destructor to be applied to other `Histograms` with very different memory layouts.

**Comment by fabiocos** [comment]
@jfernan2 @dmitrijus could you please check and sign in case?

**Comment by dmitrijus** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
