### PR TITLE
Migration to 6x6 APE matrix in alignment and RECO on top of new GT

### PR DESCRIPTION
**Pull request by diguida**
This is #6978 rebased on top of #7339

### CODE REVIEW

**Comment by diguida** [comment]
please test

**Comment by slava77** [comment]
uhm, not sure this is better: if there are any comments about this PR Alexey will have to take over by making another PR (or Salvatore will need to implement the fixes).

**Comment by civanch** [comment]
@diguida, @ASvyatkovskiy, in MuonAlignment.cc it seems that lines 214-220 have no effect (may be I misunderstand something).

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/7352	 a4611fb
additionally tested in CMSSW_7_4_X_2015-01-24-1400 /test area sign497/
with longer stat tests.

There are not differences in monitored outputs.
Based on TTBar 25PU@25ns (wf 25202) there is an apparent increase in memory use: +14MB VSIZ,  +3 MB RSS; this is under 1% (similar size increases were reported in past tests by Alexey).

**Comment by ianna** [comment]
+1

**Comment by trocino** [comment]
As a follow up to the last report by @ASvyatkovskiy 
https://indico.cern.ch/event/368007/contribution/0/material/slides/0.pdf
the latest validation results with artificial misalignments are still being inspected. This should be completed in the next few days, so we would like to wait for these last checks before the PR gets merged.

**Comment by trocino** [comment]
@ASvyatkovskiy , can you check the lines pointed by @civanch ?
https://github.com/cms-sw/cmssw/pull/7352#issuecomment-71334451
Indeed it looks like those lines have no effect, or that "matrix6x6new" is not used properly.

**Comment by ASvyatkovskiy** [comment]
@trocino @civanch It should be changed to: 

// this sets APEs at this level and (since 2nd argument is true) all lower levels
alignable->setAlignmentPositionError(AlignmentPositionError(GlobalErrorExtended(matrix6x6new)), true);

but it seems to be not used in the current code. Thanks for pointing that out.

**Comment by civanch** [comment]
+1

**Comment by abbiendi** [comment]
@ASvyatkovskiy : there seems to be an oversight in the LocalErrorBaseExtended definition:
https://github.com/diguida/cmssw/blob/APE66_AlignAndRecoParts_with_new_GT/DataFormats/GeometrySurface/interface/LocalErrorBaseExtended.h#L48  and L52  define two elements of the error matrix with the same input.

Apart from this I find quite misleading to use names as "cphiyphiy" or "cxphix" in this class. The local error matrix in 4x4 and it relates to local x,y,dx/dz,dy/dz. Why don't you use "xslope", "yslope" instead ?
I guess this is also the reason of the recent trouble with the validation, leading to a swap. I do not remember if we have discussed the choice for the names before.

**Comment by battibass** [comment]
@slava77 , @diguida: as there are some comments @ASvyatkovskiy need to address, how do we proceed? Does he open a new PR?

**Comment by slava77** [comment]
either that, or Alexey develops on top of Salvatore's branch and submits a PR to Salvatore's git area on top of that, once that's merged it will show up here

**Comment by davidlange6** [comment]
Hi all
we concluded that we should merge in this PR 
@diguida - could you +1?

**Comment by battibass** [comment]
Hi @ davidlange6 we discussed with @diguida earlier about importing a few fixes from Alexey.
Could you please give us time until tomorrow morning to have a chat with Salvatore and converge on this?

**Comment by diguida** [comment]
@battibass @davidlange6 I am testing the fix by Alexey. Then I will push them (with a rebase on top of pre6)

**Comment by diguida** [comment]
@cmsbuild please notice the changes

**Comment by diguida** [comment]
please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/7352	 902aa1c
checked in CMSSW_7_4_0_pre6 /test area sign497/
no changes in tested workflows, as in the previous pass (APE=0 case for muons)

**Comment by diguida** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
