### PR TITLE
Fed digi occupancy

### PR DESCRIPTION
**Pull request by fioriNTU**
Avoid to have an empty occupancy plot in Offline DQM

### CODE REVIEW

**Comment by deguio** [comment]
please submit to 76 and 75 as well.
thanks,
F.

**Comment by fioriNTU** [comment]
Yes, will do it tomorrow.

**Comment by deguio** [comment]
thanks,
F.

**Comment by deguio** [comment]
+1

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
-1
updates needed. @danduggan

**Pull request closed without merging**
