### PR TITLE
[DD4hep] No Namespace in MuonG4Numbering nor in Tracker SD

### PR DESCRIPTION
**Pull request by ianna**
#### PR description:

* While a proper solution is going to be provided by @ghugo83 this patch will allow to run step1 to completion

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
@civanch and @cvuosalo - this allows step1 run to completion without any errors

**Comment by ianna** [comment]
urgent

**Comment by ianna** [comment]
@civanch - please, consider reviewing this PR for 11 am IB

**Comment by civanch** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
