### PR TITLE
NVProfilerService: improve handling of module prefetching

### PR DESCRIPTION
**Pull request by fwyzard**
The display of module prefetching calls is now optional, controlled by the `showModulePrefetching` parameter.
In the Visual Profile prefetching shows up as light green (or light amber for highlighted modules) to easily distinguish it from the actual event processing.

### CODE REVIEW

**Comment by fwyzard** [comment]
@cmsbuild please test

**Comment by fwyzard** [comment]
Note: this works locally, but it will likely fail to build, since the linker check will fail without CUDA installed.

**Comment by smuzaffar** [comment]
@fwyzard , I noticed that we get this build error (which is then ignored by the edmWriteConfig). 
```
@@@@ Running edmWriteConfigs for HeterogeneousCoreCUDAServicesPlugins
error: edmWriteConfigs caught an exception while loading a plugin library.
The executable will return success (0) so scram will continue,
but no cfi files will be written.
An exception of category 'PluginLibraryLoadError' occurred.
Exception Message:
unable to load /build/cmsbld/jenkins/workspace/ib-any-integration/CMSSW_10_1_X_2018-03-09-2300/tmp/slc6_amd64_gcc630/src/HeterogeneousCore/CUDAServices/plugins/HeterogeneousCoreCUDAServicesPlugins/libHeterogeneousCoreCUDAServicesPlugins.so because libcuda.so.1: cannot open shared object file: No such file or directory

--- Registered EDM Plugin: HeterogeneousCoreCUDAServicesPlugins
```

we missing the cuda/lib/stub in LD_LIBRARY_PATH, was it on purpose?

**Comment by fwyzard** [comment]
Indeed, that's what you need `scram setup nvidia-drivers` for.

The stubs are  used by the link step of the compilation, but are not used at run time, since they do not provide any functionality.

**Comment by Dr15Jones** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
