### PR TITLE
Pr ultra legacy ps weigts

### PR DESCRIPTION
**Pull request by Andrej-CMS**
Hi all,

this is the backport of #26905 for UltraLegacy. 
please test with WF 535

### CODE REVIEW

**Comment by qliphy** [comment]
please test workflow 535

**Comment by qliphy** [comment]
+1

**Comment by fabiocos** [comment]
@qliphy so I understand that this code was explicitly validated in 11_0_X , found to be ok and now it is backported into 10_6_X. Are the differences compared to the original PR just due to the code formatting?

**Comment by qliphy** [comment]
@fabiocos 
"Are the differences compared to the original PR just due to the code formatting?"
@Andrej-CMS  should comment here.

**Comment by Andrej-CMS** [comment]
@fabiocos 
yes, the differences are due to code formatting.

**Comment by srimanob** [comment]
As I see there is a part of using getGenLumiInfoHeader in the file. Could you please confirm that it will still work well along with the PR
https://github.com/cms-sw/cmssw/pull/27446 (see comment)

**Comment by fabiocos** [comment]
@efeyazgan @qliphy @agrohjse this is another question related to the UL setup

**Comment by kpedro88** [comment]
backport of #26905

**Comment by kpedro88** [comment]
@Andrej-CMS @efeyazgan @qliphy @agrohsje can you address the question in https://github.com/cms-sw/cmssw/pull/27496#issuecomment-511877236 ?

**Comment by qliphy** [comment]
@gourangakole has done some checks and will give an update soon.

**Comment by gourangakole** [comment]
This is the details check for #27446 
[July2019_Gouranga_PR27446_v0.pdf](https://github.com/cms-sw/cmssw/files/3452092/July2019_Gouranga_PR27446_v0.pdf)
[after_GS_LHEheader.txt](https://github.com/cms-sw/cmssw/files/3452101/after_GS_LHEheader.txt)
[after_MiniAODSIM.txt](https://github.com/cms-sw/cmssw/files/3452102/after_MiniAODSIM.txt)

**Comment by kpedro88** [comment]
@gourangakole it is not entirely clear to me how this material answers the question. Can you elaborate on your conclusions from your studies?

**Comment by gourangakole** [comment]
@kpedro88 ..I am sorry for the confusion. I am quite new in these checks. 
But my checks are entirely related to the 
https://github.com/cms-sw/cmssw/pull/27446#issuecomment-512212652
@qliphy @fabiocos @efeyazgan do you think my checks https://github.com/cms-sw/cmssw/pull/27496#issuecomment-516854894 are fine for the https://github.com/cms-sw/cmssw/pull/27446#issuecomment-512212652

**Comment by qliphy** [comment]
Chesk from @gourangakole  is mainly on https://github.com/cms-sw/cmssw/pull/27446#issuecomment-510523894  by validating on LHERunInfoProduct.h and GenLumiInfoProduct.h

Here indeed should be further checked on herwig7.  @Andrej-CMS may help here？

**Comment by Andrej-CMS** [comment]
@kpedro88  @fabiocos 
You can find the validation of the PSweights in Herwig7 in the presentation below:
https://indico.cern.ch/event/783798/contributions/3517950/attachments/1890688/3117965/20190806_HerwigUpdate.pdf

You can see that the information gets propagated to MiniAODSIM for example in the sample below which has been produced centrally:

https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fglobal&input=%2FTT_TuneCH3_13TeV-powheg-herwig7%2FRunIIFall17MiniAODv2-PU2017_12Apr2018_94X_mc2017_realistic_v14-v2%2FMINIAODSIM

**Comment by fabiocos** [comment]
+1

**Pull request merged**
