### PR TITLE
Fixes to make DQM Online work for MWGR#3

### PR DESCRIPTION
**Pull request by andrius-k**
#### PR description:

This PR is online only. 

#### PR validation:

PR was validated in the DQM playback system.

### CODE REVIEW

**Comment by boudoul** [comment]
Hi @andrius-k - Even for online DQM, I don't think this is a good idea to use a candidate GT but @christopheralanwest may want to comment

**Comment by andrius-k** [comment]
@boudoul You are absolutely right! I'm just getting ready for the final release. I will update this PR once we know the exact GT for MWGR#3.

**Comment by boudoul** [comment]
Perfect , thanks !

**Comment by christopheralanwest** [comment]
The global tags that will be used in the MWGR are:

- HLT: 106X_dataRun3_HLT_v3
- Express: 106X_dataRun3_Express_v2
- Prompt: 106X_dataRun3_Prompt_v2

Two HCAL geometry payloads still need to be appended to finalize the conditions for the MWGR but the GT names won't change. I will update this thread once the HCAL appends have been performed.

**Comment by christopheralanwest** [comment]
The needed HCAL payloads have been appended (I suppose an announcement will be made on the AlCa hypernews any minute now) and so the global tags mentioned above should be good to go.

**Comment by boudoul** [comment]
thanks @christopheralanwest !

**Comment by andrius-k** [comment]
We are using this PR currently for the MWGR#4 and I'm not sure why it was closed previously. As far as I can see this should be integrated. Does anyone object this being integrated into the master as well?

**Comment by fabiocos** [comment]
@andrius-k it was closed by you, anyway if it is stably used it should enter I agree, but first of all in master

**Comment by fabiocos** [comment]
@andrius-k do we have a corresponding master version? Is this still needed?

**Comment by jfernan2** [comment]
@fabiocos  Sorry for the delay, corresponding master PR
https://github.com/cms-sw/cmssw/pull/28178
To be used in ext MWGR with the corresponding release
Thanks

**Comment by andrius-k** [comment]
@fabiocos @jfernan2 This can be closed. I made a backport of #28208: #28475

**Pull request closed without merging**
