### PR TITLE
Enable HLT tau filtering based on jet-tags (ParticleNet) [13_2_X]

### PR DESCRIPTION
**Pull request by mbluj**
#### PR description:

This PR adds an HLT filter of tau candidates based on jet-tagger scores. This filter, in particular, enables tau filtering based on particle-net.
The PR introduces the following changes:
* Adds `TauTagFilter`: an event filter based on the number of tau candidates that pass a selection which combines kinematic requirements (pt, eta) and requirements on jet-tagging. Optionally it also requires a matching with seeds and applies a pt correction;
* Moves `TauWPThreshold` utility class from `DeepTauId` code to a separate file to be used by both `DeepTauId` and `TauTagFilter` (and possibly others in future);
* Fixes `L2TauTagFilter.cc` to set correct id to output object.

No changes are expected in existing workflows (except correct id of objects returned by `L2TauTagFilter`).

Detailed performance of new HLT paths using newly introduced TauTagFilter and based on particle-net taggers presented at the TSG meeting on 2023-10-25: [link to indico](https://indico.cern.ch/event/1336796/#44-status-update-on-pnet-tau-t).

#### PR validation:

Code tested using CMSSW_13_3_0_pre3 with a custom HLT python configuration (with MC): [hltMC_PNet_tau.py](https://github.com/cms-tau-pog/cmssw/files/12928035/hltMC_PNet_tau.py.txt)

#### If this PR is a backport please specify the original PR and why you need to backport that PR:

Backport of https://github.com/cms-sw/cmssw/pull/43100 to 13_2_X release series for HLT integration.

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
backport of https://github.com/cms-sw/cmssw/pull/43100

**Comment by mmusich** [comment]
type tau

**Comment by mmusich** [comment]
+hlt
   * verbatim backport of https://github.com/cms-sw/cmssw/pull/43100 needed for integration of new tau HLT paths based on PNet

**Comment by mandrenguyen** [comment]
+1

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
