### PR TITLE
Update of data re-miniAOD workflows

### PR DESCRIPTION
**Pull request by fabozzi**
Using Run2_2016_HIPM era in re-miniAOD wf on 2016E. 
Adding a re-miniAOD wf on 2016H which uses Run2_2016 era.
Label shortening in re-miniAOD relval names.

Use of Run2_2016_HIPM proposed in discussion in PR #20612

### CODE REVIEW

**Comment by fabozzi** [comment]
please test workflow 136.7611,136.7721

**Comment by drkovalskyi** [comment]
> Using Run2_2016_HIPM era in re-miniAOD wf on 2016E.
> Adding a re-miniAOD wf on 2016H which uses Run2_2016 era.
> Label shortening in re-miniAOD relval names.
> 
> Use of Run2_2016_HIPM proposed in discussion in PR #20612

It must cover Eras from Run2016B till Run2016F (including it), not just 2016E

**Comment by fabozzi** [comment]
+1

**Comment by fabozzi** [comment]
@kpedro88 ping

**Comment by kpedro88** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
