### PR TITLE
ConcurrentHadronizerFilter

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

Created the ConcurrentHadronizerFilter. This templated class is similar to HadronizerFilter except it is thread-safe and can run the Hadronizer concurrently for different events.

The only hadronizer that has been instantiated is Pythia8 using a dummy decayer class, ConcurrentExternalDecayDriver. 

#### PR validation:

The code was tested using a production workflow snippet where the Pythia8Hadronizer was replaced with the ConcurrentPythia8Hadronizer. In the snippet, no external decayer was begin specified.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
The test used the following

gen_cff.py
```python
import FWCore.ParameterSet.Config as cms

externalLHEProducer = cms.EDProducer("ExternalLHEProducer",
    args = cms.vstring('/cvmfs/cms.cern.ch/phys_generator/gridpacks/2017/13TeV/powheg/V2/TT_hvq/patched/TT_hdamp_NNPDF31_NNLO_inclusive_patched_reducedPDFWeights.tgz'),
    nEvents = cms.untracked.uint32(5000),
    numberOfParameters = cms.uint32(1),
    outputFile = cms.string('cmsgrid_final.lhe'),
    scriptName = cms.FileInPath('GeneratorInterface/LHEInterface/data/run_generic_tarball_cvmfs.sh')
)

#Link to datacards:
#https://github.com/cms-sw/genproductions/blob/master/bin/Powheg/production/2017/13TeV/TT_hvq/TT_hdamp_NNPDF31_NNLO_inclusive.input

import FWCore.ParameterSet.Config as cms
from Configuration.Generator.Pythia8CommonSettings_cfi import *
from Configuration.Generator.MCTunes2017.PythiaCP5Settings_cfi import *
from Configuration.Generator.Pythia8PowhegEmissionVetoSettings_cfi import *
from Configuration.Generator.PSweightsPythia.PythiaPSweightsSettings_cfi import *

#generator = cms.EDFilter("Pythia8HadronizerFilter",
generator = cms.EDFilter("Pythia8ConcurrentHadronizerFilter",
maxEventsToPrint = cms.untracked.int32(1),
pythiaPylistVerbosity = cms.untracked.int32(1),
filterEfficiency = cms.untracked.double(1.0),
pythiaHepMCVerbosity = cms.untracked.bool(False),
comEnergy = cms.double(13000.),
PythiaParameters = cms.PSet(
pythia8CommonSettingsBlock,
pythia8CP5SettingsBlock,
pythia8PowhegEmissionVetoSettingsBlock,
pythia8PSweightsSettingsBlock,
processParameters = cms.vstring(
        'POWHEG:nFinal = 2', ## Number of final state particles
        ## (BEFORE THE DECAYS) in the LHE
        ## other than emitted extra parton
        'TimeShower:mMaxGamma = 1.0',#cutting off lepton-pair production
        ##in the electromagnetic shower
        ##to not overlap with ttZ/gamma* samples
        '6:m0 = 172.5',    # top mass'
),
parameterSets = cms.vstring('pythia8CommonSettings',
'pythia8CP5Settings',
'pythia8PowhegEmissionVetoSettings',
'pythia8PSweightsSettings',
'processParameters'
)
)
)

genParticlesForFilter = cms.EDProducer("GenParticleProducer",
    abortOnUnknownPDGCode = cms.untracked.bool(False),
    saveBarCodes = cms.untracked.bool(True),
    src = cms.InputTag("generator", "unsmeared")
)

genParticlesForjetsForFilter = cms.EDProducer("InputGenJetsParticleSelector",
    excludeFromResonancePids = cms.vuint32(12, 13, 14, 16),
    excludeResonances = cms.bool(False),
    ignoreParticleIDs = cms.vuint32(1000022, 1000012, 1000014, 1000016, 2000012, 
        2000014, 2000016, 1000039, 5100039, 4000012, 
        4000014, 4000016, 9900012, 9900014, 9900016, 
        39),
    partonicFinalState = cms.bool(False),
    src = cms.InputTag("genParticlesForFilter"),
    tausAsJets = cms.bool(False)
)

ak8GenJetsForFilter = cms.EDProducer("FastjetJetProducer",
    Active_Area_Repeats = cms.int32(5),
    GhostArea = cms.double(0.01),
    Ghost_EtaMax = cms.double(6.0),
    Rho_EtaMax = cms.double(4.5),
    doAreaFastjet = cms.bool(False),
    doPUOffsetCorr = cms.bool(False),
    doPVCorrection = cms.bool(False),
    doRhoFastjet = cms.bool(False),
    inputEMin = cms.double(0.0),
    inputEtMin = cms.double(0.0),
    jetAlgorithm = cms.string('AntiKt'),
    jetPtMin = cms.double(3.0),
    jetType = cms.string('GenJet'),
    maxBadEcalCells = cms.uint32(9999999),
    maxBadHcalCells = cms.uint32(9999999),
    maxProblematicEcalCells = cms.uint32(9999999),
    maxProblematicHcalCells = cms.uint32(9999999),
    maxRecoveredEcalCells = cms.uint32(9999999),
    maxRecoveredHcalCells = cms.uint32(9999999),
    minSeed = cms.uint32(14327),
    nSigmaPU = cms.double(1.0),
    rParam = cms.double(0.8),
    radiusPU = cms.double(0.5),
    src = cms.InputTag("genParticlesForjetsForFilter"),
    srcPVs = cms.InputTag(""),
    useDeterministicSeed = cms.bool(True)
)

genHTFilter = cms.EDFilter("GenHTFilter",
    genHTcut = cms.double(649.0),
    jetEtaCut = cms.double(1000.0),
    jetPtCut = cms.double(650.0),
    src = cms.InputTag("ak8GenJetsForFilter")
)

LHEJetFilter = cms.EDFilter("LHEJetFilter",
    jetPtMin = cms.double(350.0),
    jetR = cms.double(0.8),
    src = cms.InputTag("externalLHEProducer")
)

ProductionFilterSequence = cms.Sequence(LHEJetFilter*generator*genParticlesForFilter*genParticlesForjetsForFilter*ak8GenJetsForFilter*genHTFilter)
```

test_cfg.py
```python
import FWCore.ParameterSet.Config as cms

process = cms.Process("GEN")

process.load("gen_cff")
process.load('IOMC.RandomEngine.IOMC_cff')
process.load('SimGeneral.HepPDTESSource.pythiapdt_cfi')

process.source = cms.Source("EmptySource")

process.maxEvents.input = 5000

process.options.wantSummary = True
process.options.numberOfThreads = 4

process.p = cms.Path(process.ProductionFilterSequence, cms.Task(process.externalLHEProducer))
```

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
It would be possible to allow our present Decayers to work with this class. I can see two ways to do it
1. we use the code from FWCore/SharedMemory to run the decayers in a separate process. The down side is we would have to serialize/deserialize all the data needed and created by the decayers. It is quite likely that the overhead of serialization would only be beneficial under very high (say 100+) thread count.
1. We could use the ExternalWork facility to execute the decayers in a separate TBB task where serialization of access to the decayer is handled by the appropriate SerialTaskQueue. (This is how the one:: module HadronizerFilter works internally.)

Of course the absolute best would be to have access to thread-friendly decayers.

**Comment by Dr15Jones** [comment]
@makortel FYI

**Comment by silviodonato** [comment]
We need generators' review  @alberto-sanchez @agrohsje  @efeyazgan @mkirsano @qliphy @SiewYan

**Comment by agrohsje** [comment]
+1 
@Dr15Jones : Do you plan to work on the decays as mentioned above? (Following option 2?)
 Would you mind an extended talk in GEN starting with a more general introduction and then discussing your modifications for parallelizing.

**Comment by Dr15Jones** [comment]
>Do you plan to work on the decays as mentioned above? (Following option 2?)

I am willing to if that is seen as useful. The question I have is which configurations of Pythia8HadronizerFilter are actually used for production?

>Would you mind an extended talk in GEN starting with a more general introduction and then discussing your modifications for parallelizing.

That would be fine as well.

**Comment by silviodonato** [comment]
+1

**Comment by jordan-martins** [comment]
Hi @Dr15Jones , BPH has some low filter efficiency requests that would be great if any gain in time/evt would be achieved. I share one cfg of interest. Currently, this request is producing ~35 events/lumisection in a 8hr condor job. The cfg uses Pythia8 as initialize but then evtGen (not Multi-Process capable) takes over to decay some particular particles. Other thing to notice is that we do not use the Pythia8HadronizerFilter but rather the Pythia8GeneratorFilter. 

Would you think that we could have some gain in here as well!?

Many Thanks in advance,
Jordan.
@alberto-sanchez @qliphy @agrohsje 

[1]
# Auto generated configuration file
# using: 
# Revision: 1.19 
# Source: /local/reps/CMSSW/CMSSW/Configuration/Applications/python/ConfigBuilder.py,v 
# with command line options: Configuration/GenProduction/python/BPH-RunIIFall18GS-00219-fragment.py --f
ileout file:BPH-RunIIFall18GS-00219.root --mc --eventcontent RAWSIM --datatier GEN-SIM --conditions 102
X_upgrade2018_realistic_v11 --beamspot Realistic25ns13TeVEarly2018Collision --step GEN,SIM --nThreads 8
 --geometry DB:Extended --era Run2_2018 --python_filename BPH-RunIIFall18GS-00219_1_cfg.py --no_exec --
customise Configuration/DataProcessing/Utils.addMonitoring -n 16457
import FWCore.ParameterSet.Config as cms

from Configuration.StandardSequences.Eras import eras

process = cms.Process('SIM',eras.Run2_2018)

# import of standard configurations
process.load('Configuration.StandardSequences.Services_cff')
process.load('SimGeneral.HepPDTESSource.pythiapdt_cfi')
process.load('FWCore.MessageService.MessageLogger_cfi')
process.load('Configuration.EventContent.EventContent_cff')
process.load('SimGeneral.MixingModule.mixNoPU_cfi')
process.load('Configuration.StandardSequences.GeometryRecoDB_cff')
process.load('Configuration.StandardSequences.GeometrySimDB_cff')
process.load('Configuration.StandardSequences.MagneticField_cff')
process.load('Configuration.StandardSequences.Generator_cff')
process.load('IOMC.EventVertexGenerators.VtxSmearedRealistic25ns13TeVEarly2018Collision_cfi')
process.load('GeneratorInterface.Core.genFilterSummary_cff')
process.load('Configuration.StandardSequences.SimIdeal_cff')
process.load('Configuration.StandardSequences.EndOfProcess_cff')
process.load('Configuration.StandardSequences.FrontierConditions_GlobalTag_cff')

process.maxEvents = cms.untracked.PSet(
    input = cms.untracked.int32(16457)
)

# Input source
process.source = cms.Source("EmptySource")

process.options = cms.untracked.PSet(

)

# Production Info
process.configurationMetadata = cms.untracked.PSet(
    annotation = cms.untracked.string('Configuration/GenProduction/python/BPH-RunIIFall18GS-00219-fragm
ent.py nevts:16457'),
    name = cms.untracked.string('Applications'),
    version = cms.untracked.string('$Revision: 1.19 $')
)

# Output definition

process.RAWSIMoutput = cms.OutputModule("PoolOutputModule",
    SelectEvents = cms.untracked.PSet(
        SelectEvents = cms.vstring('generation_step')
    ),
    compressionAlgorithm = cms.untracked.string('LZMA'),
    compressionLevel = cms.untracked.int32(1),
    dataset = cms.untracked.PSet(
        dataTier = cms.untracked.string('GEN-SIM'),
        filterName = cms.untracked.string('')
    ),
    eventAutoFlushCompressedSize = cms.untracked.int32(20971520),
    fileName = cms.untracked.string('file:BPH-RunIIFall18GS-00219.root'),
    outputCommands = process.RAWSIMEventContent.outputCommands,
    splitLevel = cms.untracked.int32(0)
)

# Additional output definition

# Other statements
process.XMLFromDBSource.label = cms.string("Extended")
process.genstepfilter.triggerConditions=cms.vstring("generation_step")
from Configuration.AlCa.GlobalTag import GlobalTag
process.GlobalTag = GlobalTag(process.GlobalTag, '102X_upgrade2018_realistic_v11', '')

process.decayfilter = cms.EDFilter("PythiaDauVFilter",
    DaughterIDs = cms.untracked.vint32(3122, -13, 13),
    MaxEta = cms.untracked.vdouble(3.5, 3.0, 3.0),
    MinEta = cms.untracked.vdouble(-3.5, -3.0, -3.0),
    MinPt = cms.untracked.vdouble(0.2, 0.2, 0.2),
    NumberDaughters = cms.untracked.int32(3),
    ParticleID = cms.untracked.int32(5122),
    verbose = cms.untracked.int32(0)
)


process.probefilter = cms.EDFilter("PythiaProbeFilter",
    MaxEta = cms.untracked.double(2.5),
    MinEta = cms.untracked.double(-2.5),
    MinPt = cms.untracked.double(4.0),
    MomID = cms.untracked.int32(5122),
    NumberOfSisters = cms.untracked.int32(2),
    ParticleID = cms.untracked.int32(13),
    SisterIDs = cms.untracked.vint32(3122, -13),
    verbose = cms.untracked.int32(1)
)


process.lbfilter = cms.EDFilter("PythiaFilter",
    ParticleID = cms.untracked.int32(5122)
)


process.generator = cms.EDFilter("Pythia8GeneratorFilter",
    ExternalDecays = cms.PSet(
        EvtGen130 = cms.untracked.PSet(
            convertPythiaCodes = cms.untracked.bool(False),
            decay_table = cms.string('GeneratorInterface/EvtGenInterface/data/DECAY_2014_NOLONGLIFE.DEC'),
            list_forced_decays = cms.vstring(
                'MyLb', 
                'Myanti-Lb'
            ),
            operates_on_particles = cms.vint32(),
            particle_property_file = cms.FileInPath('GeneratorInterface/EvtGenInterface/data/evt_2014.pdl'),
            user_decay_embedded = cms.vstring(
                '#', 
                '# Particles updated from PDG2018 https://journals.aps.org/prd/abstract/10.1103/PhysRevD.98.030001', 
                'Particle   pi+         1.3957061e-01   0.0000000e+00', 
                'Particle   pi-         1.3957061e-01   0.0000000e+00', 
                'Particle   K_S0        4.9761100e-01   0.0000000e+00', 
                'Particle   J/psi       3.0969000e+00   9.2900006e-05', 
                'Particle   Lambda_b0   5.6196000e+00   0.0000000e-04', 
                'Particle anti-Lambda_b0 5.6196000e+00   0.0000000e-04', 
                '#', 
                'Alias      MyLb        Lambda_b0', 
                'Alias      Myanti-Lb   anti-Lambda_b0', 
                'ChargeConj Myanti-Lb   MyLb', 
                '#', 
                'Decay MyLb', 
                '1.000    Lambda0  mu+ mu-  PHOTOS  PHSP;', 
                'Enddecay', 
                'CDecay Myanti-Lb', 
                'End'
            )
        ),
        parameterSets = cms.vstring('EvtGen130')
    ),
    PythiaParameters = cms.PSet(
        parameterSets = cms.vstring(
            'pythia8CommonSettings', 
            'pythia8CP5Settings', 
            'processParameters'
        ),
        processParameters = cms.vstring(
            'SoftQCD:nonDiffractive = on', 
            '5122:m0=5.619600', 
            'PTFilter:filter = on', 
            'PTFilter:quarkToFilter = 5', 
            'PTFilter:scaleToFilter = 1.0'
        ),
        pythia8CP5Settings = cms.vstring(
            'Tune:pp 14', 
            'Tune:ee 7', 
            'MultipartonInteractions:ecmPow=0.03344', 
            'PDF:pSet=20', 
            'MultipartonInteractions:bProfile=2', 
            'MultipartonInteractions:pT0Ref=1.41', 
            'MultipartonInteractions:coreRadius=0.7634', 
            'MultipartonInteractions:coreFraction=0.63', 
            'ColourReconnection:range=5.176', 
            'SigmaTotal:zeroAXB=off', 
            'SpaceShower:alphaSorder=2', 
            'SpaceShower:alphaSvalue=0.118', 
            'SigmaProcess:alphaSvalue=0.118', 
            'SigmaProcess:alphaSorder=2', 
            'MultipartonInteractions:alphaSvalue=0.118', 
            'MultipartonInteractions:alphaSorder=2', 
            'TimeShower:alphaSorder=2', 
            'TimeShower:alphaSvalue=0.118'
        ),
        pythia8CommonSettings = cms.vstring(
            'Tune:preferLHAPDF = 2', 
            'Main:timesAllowErrors = 10000', 
            'Check:epTolErr = 0.01', 
            'Beams:setProductionScalesFromLHEF = off', 
            'SLHA:keepSM = on', 
            'SLHA:minMassSM = 1000.', 
            'ParticleDecays:limitTau0 = on', 
            'ParticleDecays:tau0Max = 10', 
            'ParticleDecays:allowPhotonRadiation = on'
        )
    ),
    comEnergy = cms.double(13000.0),
    crossSection = cms.untracked.double(54000000000),
    filterEfficiency = cms.untracked.double(0.0003),
    maxEventsToPrint = cms.untracked.int32(0),
    pythiaHepMCVerbosity = cms.untracked.bool(False),
    pythiaPylistVerbosity = cms.untracked.int32(0)
)


process.ProductionFilterSequence = cms.Sequence(process.generator+process.lbfilter+process.decayfilter+process.probefilter)

# Path and EndPath definitions
process.generation_step = cms.Path(process.pgen)
process.simulation_step = cms.Path(process.psim)
process.genfiltersummary_step = cms.EndPath(process.genFilterSummary)
process.endjob_step = cms.EndPath(process.endOfProcess)
process.RAWSIMoutput_step = cms.EndPath(process.RAWSIMoutput)

# Schedule definition
process.schedule = cms.Schedule(process.generation_step,process.genfiltersummary_step,process.simulation_step,process.endjob_step,process.RAWSIMoutput_step)
from PhysicsTools.PatAlgos.tools.helpers import associatePatAlgosToolsTask
associatePatAlgosToolsTask(process)

#Setup FWK for multithreaded
process.options.numberOfThreads=cms.untracked.uint32(8)
process.options.numberOfStreams=cms.untracked.uint32(0)
# filter all path with the production filter sequence
for path in process.paths:
	getattr(process,path)._seq = process.ProductionFilterSequence * getattr(process,path)._seq 

# customisation of the process.

# Automatic addition of the customisation function from Configuration.DataProcessing.Utils
from Configuration.DataProcessing.Utils import addMonitoring 

#call to customisation function addMonitoring imported from Configuration.DataProcessing.Utils
process = addMonitoring(process)

# End of customisation functions

# Customisation from command line

# Add early deletion of temporary data products to reduce peak memory need
from Configuration.StandardSequences.earlyDeleteSettings_cff import customiseEarlyDelete
process = customiseEarlyDelete(process)
# End adding early deletion

**Comment by Dr15Jones** [comment]
The problem is EvtGen is not thread safe (as you pointed out) and therefore not ameanable to the code I orginally wrote. To really handle this case would be to write the code I had originally thought would be necessary which was using FWCore/SharedMemory to run all the generator code in a different process. Doing such would probably be about 2-4 weeks of work by me.

**Comment by Dr15Jones** [comment]
@jordan-martins wrote

> BPH has some low filter efficiency requests that would be great if any gain in time/evt would be achieved. I share one cfg of interest. Currently, this request is producing ~35 events/lumisection in a 8hr condor job. The cfg uses Pythia8 as initialize but then evtGen (not Multi-Process capable) takes over to decay some particular particles. Other thing to notice is that we do not use the Pythia8HadronizerFilter but rather the Pythia8GeneratorFilter.

So I tried out the code in pull request #29445 using the configuration to which you pointed. My first observation is that configuration did not seem all that slow, it could do 2.98472 ev/s using 4 threads (although its CPU efficiency was very low). Using #29445 and 4 threads I got a 2.3x speed up (6.93303 ev/s) and very good CPU efficiency (based on results of watching `top`). I was stuck at 4 threads since the VM I am using only has 4 threads. This could should scale well under 8 threads as well.

**Pull request merged**
