### PR TITLE
Widen cluster search region in HGC EM clustering

### PR DESCRIPTION
**Pull request by lgray**
Improves clustering energy containment performance.

@pfs @vandreev11

### CODE REVIEW

**Comment by pfs** [comment]
@vandreev11, @lgray Just for my understanding/organisation is this PR independent of https://github.com/cms-sw/cmssw/pull/6993 or locally i can test it on top of it?

**Comment by lgray** [comment]
@pfs this fix is also in #6993 (which is presently evolving)

**Comment by mark-grimes** [comment]
@lgray, just so I understand: this is a subset of #6993 which is ready to be merged now?

**Comment by lgray** [comment]
@mark-grimes I would merge this and then I will later rebase #6993 on top of whatever the IB is. 
We're trying to arrive at something sensible over there at present, progress so far is promising.

**Comment by mark-grimes** [comment]
merge

Tested privately, all fine.

**Pull request merged**
