### PR TITLE
remove vertex type from PFCandidate (addresses #30895)

### PR DESCRIPTION
**Pull request by veelken**
this commit addressed the GitHub issue https://github.com/cms-sw/cmssw/issues/30895 :

- set vertex position of PFCandidate in PFAlgo, PFEGammaAlgo, and PFMuonAlgo
- remove vertex related member-functions from PFCandidate class (use the member-fuctions defined in the LeafCandidate base-class instead)
- updated ClassDefs in classes_def.xml files accordingly

#### PR description:

This PR adresses the GitHub issue https://github.com/cms-sw/cmssw/issues/30895 .

No changes are expected in the output, except (maybe) for PFCandidates of type electron.
This is because the enum value PFCandidate::kGSFVertex was not used before, causing the function PFCandidate::vertex() to never return the vertex associated with the gsfTrackRef(), which I believe is a (minor) bug. In this PR, the vertex of PFCandidates of type electron is set to the vertex assocciated with the gsfTrackRef() in PFEGammaAlgo, which I believe is the intended behaviour.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by slava77** [comment]
> Code check has found code style and quality issues which could be resolved by applying following patch(s)

these should be addressed before further tests of this PR can proceed

**Comment by slava77** [comment]
@veelken 
please edit the PR title so that it at least includes #30895 in full (a URL can be replaced by #30895 ), 
although something more direct is better, e.g. "remove vertex type from PFCandidate (addresses #20895)"

**Comment by slava77** [comment]
@hatakeyamak @bendavid 
please check this and clarify if the changes are OK for PF.
Thank you.

**Comment by veelken** [comment]
Hi,

I have renamed the title of the PR and applied the patches code-format.patch and code-format.patch .

**Comment by jpata** [comment]
@veelken thanks for preparing a first implementation for the issue #30895, as suggested in https://github.com/cms-sw/cmssw/issues/30895#issuecomment-682711046.

However, if you are planning to hand this over to someone else, they will **not** be able to update your PR.

Hence, if the plan is that the PF group takes over this proposed modification, it would be best to close this PR and simply link your new branch (good to put it with a descriptive branch name, like veelken:issue_30895) in the issue. Then the next person can check out your branch and open a new PR that they can update.

**Comment by veelken** [comment]
Hi Joseep,

here is the link to the branch: https://github.com/veelken/cmssw/tree/CMSSW_11_2_X
(sorry, I did not think about using a more descriptive branch name)

**Comment by jpata** [comment]
Thanks, please close this PR then (if you don't plan to work on this).

**Comment by veelken** [comment]
Hi Joosep,

I propose to keep this PR open until Ken had a chance to look at the changes. From my side, the next step now is the validation. The code itself is fully developed and can be merged provided that no issues show up during the validation.

**Comment by jpata** [comment]
OK - let's run the tests and wait for the PF group input on how they want to proceed.

For all: from the point of view of git workflow, we do not have a concept of handing a PR over from one author to another, hence it is preferable if the same person who starts the PR is able to also commit the effort to validation & follow-up fixes (unless you allow a third party to push to your fork of cmssw). Hence, while I would strongly encourage to open issues for any problems found in the reco packages, I would suggest that PRs be opened by the person who is assigned/committed to the issue.

**Comment by jpata** [comment]
@cmsbuild please test

**Comment by jpata** [comment]
@veelken @hatakeyamak as reported by the test, there are a number of minor differences in the isolation values, at least, see the example below:

image
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_11_2_X_2020-08-31-2300+b9c548/38573/validateJR/all_OldVSNew_RunJetHT2016EreMINIAODwf136p7611/all_OldVSNew_RunJetHT2016EreMINIAODwf136p7611c_patElectrons_slimmedElectrons__PAT_obj___isolations__4_.png

Given that this PR is expected to be technical (no reco change), please let us know how you want to move forward.

**Comment by veelken** [comment]
Hi,

just to clarify: a small change for electrons is ok, I think, resulting from the fact that the code so far took the vertex position for electrons from the KF track and not from the GSF track, due to the issue with the enum value PFCandidate::kGSFVertex not being used before. @hatakeyamak , do you agree that the changes are small enough to be ok ?

**Comment by jpata** [comment]
Note that there are differences also in e.g. muon and photon isolation values:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_11_2_X_2020-08-31-2300+b9c548/38573/validateJR/all_OldVSNew_RunJetHT2018DreMINIAODULwf136p88811/

Let's wait for @hatakeyamak decision on how to proceed. If this PR goes ahead, I will do a code review.

**Comment by hatakeyamak** [comment]
Thank you @veelken and @jpata, and sorry for delays from my side.
To me this looks good, and I don't see the issue with moving forward.
@bendavid ok with you as well?

The use of vertex assocciated with the gsfTrackRef() in PFEGammaAlgo seems like a right thing to do.

**Comment by jpata** [comment]
I've gone through the code and it looks fine to me. Vertex is just a point, which previously was loaded from a referenced collection, but is now saved directly. Since we no longer save the vertex type, the event size decreases. What I don't understand is why it was implemented through the references in the first place, rather than in the straightforward way as this PR does.

Do you know @hatakeyamak?

**Comment by hatakeyamak** [comment]
Nope.

**Comment by jpata** [comment]
@slava77 @perrotta what do you think, can you recall any reason why the vertex location was loaded from a referenced collection, rather than saved in the candidate directly? Otherwise, the code looks fine to me.

**Comment by perrotta** [comment]
> @slava77 @perrotta what do you think, can you recall any reason why the vertex location was loaded from a referenced collection, rather than saved in the candidate directly? Otherwise, the code looks fine to me.

No idea, and looking at the history available doesn't help either

**Comment by jpata** [comment]
Thanks! Before proceeding with this, I just want to check also with EGamma contacts @afiqaize @SohamBhattacharya. Do you have any thoughts on this change to PFCandidate vertex, which has some minor effects on electron and photon isolation?

**Comment by afiqaize** [comment]
We agree that the change for electrons is the intended behavior. For photons, we are wondering if the changes are understood (maybe the changes happen only to converted photons etc)?

**Comment by jpata** [comment]
note: I'm digging through the isolation code to understand **why** the photon, muon and tau isolation changes, but haven't hit the reason yet.

**Comment by veelken** [comment]
Hi Joseep,

the tau isolation takes into account all charged PFCandidates within a dz < 0.2 cm window around the tau production vertex. My hypothesis that using the vertex associated to the GSF track instead of the KF track for electrons causes some electrons to either move into or move out of the dz < 0.2 cm window. I am not an expert for the isolation of photons and muons, but I believe they can be subject to a similar effect (arising from a dz cut that is applied in order to suppress pileup contributions to their isolation pT-sum).

**Comment by slava77** [comment]
@jpata 
in https://user-images.githubusercontent.com/69717/91840145-e61a9380-ec58-11ea-9867-21e6a8f22dae.png
`isolations_[4]` is `PfChargedHadronIso` .
These are filled in https://github.com/cms-sw/cmssw/blob/master/PhysicsTools/PatAlgos/plugins/PATElectronProducer.cc#L894-L909
Depending on the electron being PF or not, it will come from `pfChargedHadrons = cms.InputTag("elPFIsoValueCharged04PFIdPAT")` or `"elPFIsoValueCharged04NoPFIdPAT"`.
It may be useful to check if the diffs are all from PFId or from NoPFId.

**Comment by jpata** [comment]
Thanks Slava! Following the thread for `process.phPFIsoDepositChargedPAT`, it seems that CandViewExtractor in https://github.com/cms-sw/cmssw/blob/e1b6d9656af60378402e6a3bafaa03e64be077cf/PhysicsTools/IsolationAlgos/plugins/CandViewExtractor.icc#L21 is looping over pions which all now have vtx()=(0,0,0), causing incorrect behaviour the dz and rho cuts in workflow 136.7611, thus the isolation is different.

```
this PR                                                                                            | reference
%MSG-d CandViewExtractor:  CandIsoDepositProducer:phPFIsoDepositChargedPAT  14-Sep-2020 15:50:59 EE|  %MSG-d CandViewExtractor:  CandIsoDepositProducer:phPFIsoDepositChargedPAT  14-Sep-2020 15:50:58 EE
cand eta=2.28516 phi=-0.894788 vtx=(0.0601291,0.102278,-1.90386)                                   |  cand eta=2.28516 phi=-0.894788 vtx=(0.0601291,0.102278,-1.90386)
%MSG                                                                                               |  %MSG
%MSG-d CandViewExtractor:  CandIsoDepositProducer:phPFIsoDepositChargedPAT  14-Sep-2020 15:50:59 EE|  %MSG-d CandViewExtractor:  CandIsoDepositProducer:phPFIsoDepositChargedPAT  14-Sep-2020 15:50:58 EE
pdgid=-211 vtx=(0,0,0) dR=4.01993 dvz=1.90386 drho=0.118644                                        |  pdgid=-211 vtx=(0.0555814,0.0833093,-1.9246) dR=4.01993 dvz=-0.0207404 drho=0.0195064              
%MSG                                                                                               |  %MSG
%MSG-d CandViewExtractor:  CandIsoDepositProducer:phPFIsoDepositChargedPAT  14-Sep-2020 15:50:59 EE|  %MSG-d CandViewExtractor:  CandIsoDepositProducer:phPFIsoDepositChargedPAT  14-Sep-2020 15:50:58 EE
pdgid=-211 vtx=(0,0,0) dR=1.74093 dvz=1.90386 drho=0.118644                                        |  pdgid=-211 vtx=(0.0673064,0.0994989,-1.89405) dR=1.74093 dvz=0.00980163 drho=0.00769662            
%MSG                                                                                               |  %MSG
```

I guess this has to do with requiring the vertex being saved in the RECO step that runs PF, which makes later workflows that do not run reconstruction in-place incorrect.
As we need to be able to process old files, I think a check might be needed with fallback to the old behaviour if we want to adopt this new mechanism going forward.

Thoughts?

**Comment by jpata** [comment]
Suggestion from Slava: add IO read rule to the class def XML, such that the old version of the class would be able to load the correct vertex collection in the case of e.g. reMINIAOD jobs.

**Comment by jpata** [comment]
@veelken will you do this, or should we (reco) take over at this point?

**Comment by veelken** [comment]
@jpata It would be great if you (reco) could take over at this point. Thank you!

**Comment by jpata** [comment]
-1

OK. I think the easiest will be that you close this PR, and open a new one with a branch I can change.

**Pull request closed without merging**
