### PR TITLE
Replace inconsistent tabbing with spaces in MatrixInector.py

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

python 3 does not accept mixing spacing and tabbing.

#### PR validation:

Using python3 to parse the file no longer generates an error.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by chayanit** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Pull request merged**
