### PR TITLE
HLT updates on top of the menus merged right after CMSSW_745 - 75X

### PR DESCRIPTION
**Pull request by perrotta**
Title says all...
Most of the updates refer to the preparation of the 50ns menu for the start of data taking with it

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
rebased to 750pre6

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
Need to include #9851 (new L1T menus) here as HLT now uses them.

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
Rebased to 7_5_0

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test
again as Andrea pushed some more ....

**Comment by Martin-Grunewald** [comment]
@perrotta 
Andrea, could you open up new PRs for further developments - I really would like to get this one in asap. Also, the latest push needs a new 76X PR as the previous 76X PR is already integrated.

**Comment by Martin-Grunewald** [comment]
+1
Ready to go now - please sign!

**Comment by civanch** [comment]
+1

**Comment by Martin-Grunewald** [comment]
@mulhearn @mmusich 
Please sign this PR for 75X.
Thanks!

**Comment by mmusich** [comment]
+1

**Comment by Martin-Grunewald** [comment]
@mulhearn
Could you please sign this PR for 75X?
Thanks!

**Comment by mulhearn** [comment]
+1

**Pull request merged**
