### PR TITLE
Run3-gem30 Use edm::Log in the code rather than cout in Geometry/MuonNumbering

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Avoid using out in the debug codes of Geometry/MuonNumbering

#### PR validation:

Passes the standard matrix of tests

#### if this PR is a backport please specify the original PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Pull request merged**
