### PR TITLE
Backport of MkFitCore vectorization PR 37868

### PR DESCRIPTION
**Pull request by gartung**
commit 18abd3a967c4794bd081ef2af94a85f2585b25eb
Author: Patrick Gartung <gartung@fnal.gov>
Date:   Wed May 25 02:12:21 2022 +0200

    Code format

commit f067f254ac785d8cdd2d46112174b3f044f82553
Author: Patrick Gartung <gartung@fnal.gov>
Date:   Wed May 25 02:08:47 2022 +0200

    Fix icc compilation errors

commit b265ce2d97be1f38a882e53aa0f1ad8c6469263e
Author: Patrick Gartung <gartung@fnal.gov>
Date:   Fri May 20 23:22:10 2022 +0200

    Add line to RecoTracker/MkFitCore/standalone/README_buildFromCMSSW.txt

commit 861899759440ffb1e2aedc848014bf2c23765b2b
Author: Patrick Gartung <gartung@fnal.gov>
Date:   Fri May 20 18:18:50 2022 +0200

    Add CMS_UNROLL_LOOP defines for Intel compilers and use with pragme omp simd instructions that cause internal icc error

commit 45977ea512079ea324b009a2edd03df9c3e58e50
Author: Patrick Gartung <gartung@fnal.gov>
Date:   Fri May 20 18:17:54 2022 +0200

    Squashed commit of the following:

    commit a565f528861deb96fb549f12c8ec619dc60fde1d
    Author: Patrick Gartung <gartung@fnal.gov>
    Date:   Thu May 19 15:23:44 2022 +0200

        Remove fast-math flag and attribute needed to prevent segfault when fast-math is used

    commit c3fbce9e16987ce4f152b3ae1197c543f988a363
    Author: Patrick Gartung <gartung@fnal.gov>
    Date:   Mon May 16 17:28:41 2022 +0200

        Code format

    commit c388ab36ccecad460b22042ca882b0f572ce7c6e
    Author: Patrick Gartung <gartung@fnal.gov>
    Date:   Mon May 16 17:27:00 2022 +0200

        Update location of #endif after enabling debug. #pragma omp simd not needed for debug statements. Move debug statements to own loop.

    commit 468b4760a1a6df6bf8545903339b6312e8420c31
    Author: Patrick Gartung <gartung@fnal.gov>
    Date:   Sat May 14 19:51:00 2022 +0200

        No need to link to libmvec. It is called from libm on el8. Always use -ffastmath

    commit 0ef90368b2b7c5345b417d9e99fb37acef9f8685
    Author: Patrick Gartung <gartung@fnal.gov>
    Date:   Fri May 13 20:01:43 2022 +0200

        Only works on el8_amd64 arch

    commit 8866ca64dc913d274f25da401c321cc5d2193790
    Author: Patrick Gartung <gartung@fnal.gov>
    Date:   Fri May 13 16:10:23 2022 +0200

        Update for macro name change

    commit fe4a38fa1fca00e3746b14c1d72a9e35c675360c
    Author: Patrick Gartung <gartung@fnal.gov>
    Date:   Thu May 12 21:43:02 2022 +0200

        code format?

    commit 8326129cd2333b8fcc256880f70a5deb9e5d899f
    Author: Patrick Gartung <gartung@fnal.gov>
    Date:   Thu May 12 21:18:44 2022 +0200

    	    Add CMS_UNROLL_LOOP defines for Intel compilers and use with pragme omp simd instructions that cause internal icc error

    commit 056f7ef4fcc745107ff55365f0a1d9e0a2634349
    Author: Patrick Gartung <gartung@fnal.gov>
    Date:   Thu May 12 03:42:01 2022 +0200

        Add CMS_UNROLL_LOOP_COUNT(Config::Niter) and initialize arrays with += and -= assignment statements to 0. first

    commit 31e2c8351f4f988e97b04ec39eb52547654c3923
    Author: Patrick Gartung <gartung@fnal.gov>
    Date:   Wed May 11 05:16:27 2022 +0200

        Add CMS_UNROLL_LOOP_COUNT(Config::Niter)
        and #include "FWCore/Utilities/interface/CMSUnrollLoop.h"

    commit 8eab5b1ea5f6d29b90d4670ef7aedbec0ff8af72
    Author: Patrick Gartung <gartung@fnal.gov>
    Date:   Wed May 11 04:57:47 2022 +0200

        Change atrribute from no-fast-math to match-errno

    commit 688e905a36b83cf8d5da1313b703098598cd74ae
    Author: Patrick Gartung <gartung@fnal.gov>
    Date:   Tue May 10 17:37:25 2022 +0200

        Code format

    commit ed58228b16f3b86686725556739cc93508d3af14
    Author: Patrick Gartung <gartung@fnal.gov>
    Date:   Tue May 10 17:23:08 2022 +0200

        Change attribute from no-inline to no-fast-math. Back out changes to applyMaterialEffects since it does not vectorize with the conditional on radL.

    commit c19f9c8b6bb718ae110f914177788bb760a5e59a
    Author: Patrick Gartung <gartung@fnal.gov>
    Date:   Mon May 9 19:49:15 2022 +0200

        code format

    commit 373ea0d28c50e3b7d949604eddae5ac0859e0a93
    Author: Patrick Gartung <gartung@fnal.gov>
    Date:   Mon May 9 19:02:48 2022 +0200

        missed a few initialization of variable length arrays

    commit 753934cb32362ecf846b24e726ec4c1b49cf644c
    Author: Patrick Gartung <gartung@fnal.gov>
    Date:   Mon May 9 18:51:13 2022 +0200

        for all el8 archs

    commit 2eb25ef5bf7c45353d4cae9c852d5b75fd848a85
    Author: Patrick Gartung <gartung@fnal.gov>
    Date:   Mon May 9 18:31:35 2022 +0200

        clang does not allow initialization of variable length arrays

    commit 7f237622ef7b3c216e6ed3ce1a0a03f978b03817
    Author: Patrick Gartung <gartung@fnal.gov>
    Date:   Mon May 9 17:41:29 2022 +0200

        Add fast-math and mvec when compiling under el8

    commit 5f6efe223081fe7a17becd39d5f27088c227136b
    Author: Patrick Gartung <gartung@fnal.gov>
    Date:   Mon May 9 16:07:08 2022 +0200

        Comment out changes that are CERN specific

    commit 1ba6e069887f2ca38a3318f292d409a5c19b8406
    Author: Patrick Gartung <gartung@fnal.gov>
    Date:   Thu May 5 21:25:33 2022 +0200

        Try to break loop in applyMaterialEffects into smaller loops
        Combine arithmetic ops into one loop.
        Add -lmvec which is avaiable on RHEL8

    commit dbc748cdd84b82a3faa3d621eb3ea9cb2621bc7c
    Author: Patrick Gartung <gartung@fnal.gov>
    Date:   Wed May 4 20:02:05 2022 +0200

        Incorporate Dan Riley's suggested changes

    commit d6ae2c9c7bb50e03e3e9f187a1413568f5aeb7e0
    Author: Patrick Gartung <gartung@fnal.gov>
    Date:   Tue May 3 20:20:47 2022 +0200

        Update helixAtZ to use small calculation loops

    commit 3d704ba96e6cefc4d7d1959f621c0d47fc57879e
    Author: Patrick Gartung <gartung@fnal.gov>
    Date:   Fri Apr 29 21:43:00 2022 +0200

        Work in progress

    commit 31550b4446669845eb696676f47a257726923532
    Author: Patrick Gartung <gartung@fnal.gov>
    Date:   Fri Apr 29 20:03:09 2022 +0200

        Fixups

    commit f10ef52690510ba9ad9ad00dc9285bc4951e651e
    Author: Patrick Gartung <gartung@fnal.gov>
    Date:   Fri Apr 29 00:57:47 2022 +0200

        WIP

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by clacaputo** [comment]
Hi @gartung, could you please edit the title by removing the URL? Thanks

**Comment by clacaputo** [comment]
+reconstruction

- this PR is a backport of #37868: code changes are in line with the original PR
- reco changes are in some `slimmedMET` `uncertanties_` and `corrections_` quantities. This is related to the MET code, as discussed in https://github.com/cms-sw/cmssw/pull/36954#issuecomment-1056432274

**Comment by gartung** [comment]
@Dr15Jones  can you sign for core?

**Comment by Dr15Jones** [comment]
+1

**Pull request merged**
