### PR TITLE
backport of ttHfgenfilter to 94X

### PR DESCRIPTION
**Pull request by Andrej-CMS**
Dear all,

this is a backport of #21743 to CMSSW 94X. To make the tagging functionality being available in this release.

Kind regards,
Andrej

### CODE REVIEW

**Comment by Andrej-CMS** [comment]
Dear @all,
Please have a look at the PR and let me know if there are any issues with it! It would be very nice to have this in the next CMSSW 94X release.

Kind regards,

Andrej

**Comment by kpedro88** [comment]
please test

**Comment by kpedro88** [comment]
backport of #21743

**Comment by fabiocos** [comment]
+1 

code already merged in master since months, the test configuration provided runs smoothly

**Pull request merged**
