### PR TITLE
Removed vdt dependency on DataFormats/ParticleFlowReco

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

PFCluster.cc had a templated anonymous function using the vdt butthat function was never called.

#### PR validation:

I added the line `static_assert(sizeof(Scalar)==0);` to the function in question and the assert never happened. The only way that occurs is if the templated function was never actually instantiated.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by jpata** [comment]
PF group @bendavid @hatakeyamak any comments?

**Comment by jpata** [comment]
I think this was originally added in https://github.com/cms-sw/cmssw/commit/e1c961bced886fe8e67e414bcccf7784de38fe54#diff-10a9a5bf86277606590ac2723121f0e530b8364d607ae43b9ecbd6aaf55ddbad
I would agree that as this is not used, it can be removed. 

@lgray any comments?

**Comment by jpata** [comment]
+reconstruction

- removes an unused, never-compiled function `Eta_FromRhoZ_fast` that was first introduced in https://github.com/cms-sw/cmssw/commit/e1c961bced886fe8e67e414bcccf7784de38fe54#diff-10a9a5bf86277606590ac2723121f0e530b8364d607ae43b9ecbd6aaf55ddbad
- everything compiles fine
- no changes are expected or observed

**Comment by silviodonato** [comment]
+1

**Comment by hatakeyamak** [comment]
> PF group @bendavid @hatakeyamak any comments?

Sorry that I didn't respond. I don't really know the original intention of this, so I didn't really have a comment. I think the cleanup makes sense.

**Pull request merged**
