### PR TITLE
HLT: Fixes and rationalisation/reuse of cfg files for tests

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
HLT: Rationalisation and reuse of cfg files for tests
Includes the HLT fixes as in #8780 plus additional ones.

Overall list of updates to the 50ns and 25ns HLT menus included in this pull request:

```
Replace HLTIterativeTracking12ForBTagDisplacedJets sequence with HLTIterativeTrackingForBTagIter12, since they are identical
Fix L1 seeds for CMSHLT-318 (50ns only), and rename a few more L1s modules
HLT paths to save muon trigger objects, CMSHLT-322
HLT paths of HIN PAG for the VdM menu, CMSHLT-279
Few prescales to adapt for 50ns menu, CMSHLT-329
Fix another bugs in HLTBtagCSVSequencePF (CMSHLT-327) and switch saveTag=true in B2G Ele+2Jets path (CMSHLT-328)
Fixed prescales (CMSHLT-310)
Fixes to CMSHLT-273 (HLT_FullTrackXX)
```

Latest master table included:

```
/dev/CMSSW_7_4_0/50nsHLT/V61
/dev/CMSSW_7_4_0/HLT/V112
```

The frozen menus correspond to the latest 50ns and 25ns GRun menus:

```
/frozen/2015/50ns_5e33/v1.2/HLT/V2: same as /dev/CMSSW_7_4_0/50nsGRun/V74
/frozen/2015/25ns_14e33/v1.2/HLT/V2: same as /dev/CMSSW_7_4_0/GRun/V41
```

The huge reduction in "numbers of lines in this PR" is due to the fact that we get rid of
half of the cfg dumps in the ../test directory, by using one dump for both real-data
and MC tests of a given menu, as opposed to two virtually identical dumps earlier!

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by lveldere** [comment]
+1

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by lveldere** [comment]
+1

**Comment by fwyzard** [comment]
hi @Martin-Grunewald , as requested t the ORP, could you provide a more detailed list of changes in this PR ?

**Comment by perrotta** [comment]
Overall list of updates to the 50ns and 25ns  HLT menus included in this pull request:

- Replace HLTIterativeTracking12ForBTagDisplacedJets sequence with HLTIterativeTrackingForBTagIter12, since they are identical
- Fix L1 seeds for CMSHLT-318 (50ns only), and rename a few more L1s modules
- HLT paths to save muon trigger objects, CMSHLT-322
- HLT paths of HIN PAG for the VdM menu, CMSHLT-279
- Few prescales to adapt for 50ns menu, CMSHLT-329
- Fix another bugs in HLTBtagCSVSequencePF (CMSHLT-327) and switch saveTag=true in B2G Ele+2Jets path (CMSHLT-328)
- Fixed prescales (CMSHLT-310)
- Fixes to CMSHLT-273 (HLT_FullTrackXX)

Latest master table included:
- /dev/CMSSW_7_4_0/50nsHLT/V61
- /dev/CMSSW_7_4_0/HLT/V112

The frozen menus correspond to the latest 50ns and 25ns GRun menus:
- /frozen/2015/50ns_5e33/v1.2/HLT/V2: same as /dev/CMSSW_7_4_0/50nsGRun/V74
- /frozen/2015/25ns_14e33/v1.2/HLT/V2: same as /dev/CMSSW_7_4_0/GRun/V41

**Comment by perrotta** [comment]
(Since I didn't start this PR I was not able to update the overall description window in it: @Martin-Grunewald , if you want you can copy the description in my previous comment to the overall description, for easier bookkeeping)

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
As usual, I can't access the link with the results of the tests (and as usual this is rather annoying...). Could anybody please point me out which is the failing one, so that I can try to reproduce? I got no failures at all while testing it myself

**Comment by davidlange6** [comment]
What exactly can you not access?

https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-8781/4316/runTheMatrix-results/runall-report-step123-.log

looks like das errors

**Comment by perrotta** [comment]
Thank you @davidlange6. Thus it looks like a fake, right? Should I ask to restart the tests?

In any case, the message I get while trying to access any of those links is the following:

Authorization Failed

Based on the information provided to this application about you, you are not authorized to access the resource at "https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-8781/4316/summary.html"

Please contact the administrator of this service or application if you believe this to be an error at somebody@cern.ch

**Comment by davidlange6** [comment]
strange - the web page is just behind the usual CERN/CMS SSO. Do you have other problems related to this?

**Comment by Dr15Jones** [comment]
I seem to have no trouble accessing the page

**Comment by perrotta** [comment]
I have no problems up to 
https://cmssdt.cern.ch/SDT/
and I have no problems in accessing any of the pages linked from there, but the
https://cmssdt.cern.ch/jenkins/
one. Thus, the only part of it I am not authorized to access is actually jenkins.

**Comment by davidlange6** [comment]
and this?

https://indico.cern.ch/event/384919/

**Comment by perrotta** [comment]
Yes, I can reach it.
Only jenkins...

David Lange <notifications@github.com> ha scritto:

> and this?
>
> https://indico.cern.ch/event/384919/
>

**Comment by perrotta** [comment]
please test
(again, since the failure was due to das, not to this PR)

**Comment by perrotta** [comment]
Hi @davidlange6 

I found the issue with my authorizations for jenkins. I have two cern accounts ("perrotta" and "aperrott"), and while all other services are accessed by "perrotta" (or both), jenkins still requires "aperrott".
Do you know who is the "administrator of this service or application" that I can contact to have it fixed? Or is there a page I can update myself?

Thank you,
Andrea

**Comment by davidlange6** [comment]
Strange. perrotta is not in the ZH group. I’m surprised you can access CMS pages with it. I can ask around, but afaik, its the usual CERN SSO.

**Comment by Martin-Grunewald** [comment]
+1

**Comment by Martin-Grunewald** [comment]
@lveldere 
Lukas, please re-sign...

**Comment by Dr15Jones** [comment]
+1
not sure why core is required

**Pull request merged**
