### PR TITLE
Phase2-gex148 Check overlap testing for geometries with HFNose

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Check overlap testing for geometries with HFNose

#### PR validation:

Use test scripts in Geometry/ForwardCommmonData/test

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by bsunanda** [comment]
@srimanob Please approve this

**Comment by srimanob** [comment]
+Upgrade

**Comment by perrotta** [comment]
+1

**Pull request merged**
