### PR TITLE
Use pixel seed extension for phase1 in initialStep

### PR DESCRIPTION
**Pull request by makortel**
The title says it all. The change was discussed and agreed in May 9 TRK POG meeting
https://indico.cern.ch/event/527844/contributions/2161117/attachments/1269921/1881271/slides_phase1_20160509.pdf

The main point is to exercise regularly the pixel seed extension code from #14356. For 2017 production we may revert this and go back to "quadruplets by triplet propagation" also in initialStep.

Please find below MultiTrackValidator plots with 1000 TTbar+PU35 events showing the effect of this PR on top of 8_1_0_pre5+#14545 (strip alignment as in `run2_asymptotic` GT)
https://mkortela.web.cern.ch/mkortela/tracking/validation/CMSSW_8_1_0_pre5_pse/

Tested in CMSSW_8_1_X_2016-05-24-1100, non-2017 workflows should have no effect. 2017 workflows should have small effect on the level of generalTracks (mainly decrease of duplicate rate), while initialStep and highPtTripletStep have larger changes (mainly migration from highPtTripletStep to initialStep).

@rovere @VinInn

### CODE REVIEW

**Comment by VinInn** [comment]
@cmsbuild , please test

**Comment by slava77** [comment]
in 10224 on 100 events:
fewer and shorter electron seeds
all_sign710-histatvsorig-histat_ttbar13tevpu2017wf10224p0c_recoelectronseeds_electronmergedseeds__reco_obj_nhits

there are a few more gedGsfElectrons and they are apparently with smaller fbrem
all_sign710-histatvsorig-histat_ttbar13tevpu2017wf10224p0c_recogsfelectrons_gedgsfelectrons__reco_obj_fbrem

Charged hadron yield reduces at higher eta (much smaller effect in generalTracks)
all_sign710-histatvsorig-histat_ttbar13tevpu2017wf10224p0c_recopfcandidates_particleflow__reco_obj_eta12


as expected in the PR description: there is a migration from highPtTripletStep to initialStep in generalTracks
all_sign710-histatvsorig-histat_ttbar13tevpu2017wf10224p0c_recotracks_generaltracks__reco_obj_algo

The effect on electron seeds is even larger in ZEE PU35 sample 10225
all_sign710-histatvsorig-histat_zee13tevpu2017wf10225p0c_recoelectronseeds_electronmergedseeds__reco_obj_nhits
It looks like electrons are more effectively made with these shorter seeds, since the effect on ged electrons is somewhat positive.

There is some decrease in fakes+dups in generalTracks 
https://mkortela.web.cern.ch/mkortela/tracking/validation/CMSSW_8_1_0_pre5_pse/ttbar_pu_ootb/effandfake4.pdf
.. these are in line with the presentation in the tracking POG

Before signing, I wanted to check if the large effect on electron seeding is intended.

**Comment by makortel** [comment]
Thanks @slava77 for pointing it out. Electron seeds become shorter because they use `initialStepSeeds` (among others) and those are changed from quadruplets to triplets in this PR. I produced MTV plots for gsfElectrons (1000 events of ttbar+PU)
https://mkortela.web.cern.ch/mkortela/tracking/validation/CMSSW_8_1_0_pre5_pse_ele/ttbar_pu_electronGsf.html
and I don't see any statistically significant effect. So even though the electron seeds change, the downstream effects seem to be negligible. And anyway the (tracking) tuning is not final, but point taken.

**Comment by slava77** [comment]
@makortel remind me, please, what are the selections for TP in the gsf MTV.
Is it primary electrons or something else/more?

**Comment by makortel** [comment]
@slava77 For efficiencies, first only TrackingParticles with `abs(pdgId)==11` are selected
https://github.com/cms-sw/cmssw/blob/CMSSW_8_1_X/Validation/RecoTrack/python/TrackValidation_cff.py#L272
and then the usual plot-specific selections are applied
https://github.com/cms-sw/cmssw/blob/CMSSW_8_1_X/Validation/RecoTrack/python/TrackingParticleSelectionsForEfficiency_cff.py

Fake and duplicate rates are calculated wrt. all (also non-electron) TrackingParticles.

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/14621	48c74d0
- configuration code changes are in line with the description; only phase1 is affected
- jenkins tests pass and show differences only in phase 1 workflow
- local tests with higher stats using 10224 and 10225 with PU and 100{24,25,26} without pileup don't show major changes in final (generalTracks) performance: efficiency is about the same and duplicate rates are smaller as expected; electron seeding is using triplets now and the electron efficiency is about the same (MTV GSF plots are good), there is some reduction in fbrem.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
