### PR TITLE
Utilities/StaticAnalyzer: Add check for func name in DiGraph before calling has_path.

### LINKED ISSUE #56: Report all Modules in IB workflows that call EventSetupRecord::get() and integrate with Jenkins
- [x] Create script to find all Modules in IB's that call EventSetupRecord::get()
- [x] Add script to shell script that generates report from running CMS custom clang static analyzers
- [x] Update cms-bot script that copies reports to include the ESR::get report.
- [x] Add links for ESR::get report to IB dashboard.
- [x] Debug problems with Jenkins job that run static analyzers.
- [x] Fix for eventsetuprecord-get.txt missing for releases that do not generate report.
- [x] Fix networkX exception in various report generation scripts.

### PR DESCRIPTION
**Pull request by gartung**
Resolves https://github.com/makortel/framework/issues/56

Fix for error in generating report from static analyzers:
```
+ ./create_statics_esd_reports.sh
Traceback (most recent call last):
  File "./data-class-funcs.py", line 95, in <module>
    for n,nbrdict in G.adjacency_iter():
AttributeError: 'DiGraph' object has no attribute 'adjacency_iter'
Traceback (most recent call last):
  File "./statics.py", line 43, in <module>
    if nx.has_path(G,tfunc,static): 
  File "/cvmfs/cms-ib.cern.ch/nweek-02669/slc7_amd64_gcc900/external/py2-networkx/2.2-ljfedo/lib/python2.7/site-packages/networkx/algorithms/shortest_paths/generic.py", line 40, in has_path
    nx.shortest_path(G, source, target)
  File "/cvmfs/cms-ib.cern.ch/nweek-02669/slc7_amd64_gcc900/external/py2-networkx/2.2-ljfedo/lib/python2.7/site-packages/networkx/algorithms/shortest_paths/generic.py", line 170, in shortest_path
    paths = nx.bidirectional_shortest_path(G, source, target)
  File "/cvmfs/cms-ib.cern.ch/nweek-02669/slc7_amd64_gcc900/external/py2-networkx/2.2-ljfedo/lib/python2.7/site-packages/networkx/algorithms/shortest_paths/unweighted.py", line 223, in bidirectional_shortest_path
    raise nx.NodeNotFound(msg.format(source, target))
networkx.exception.NodeNotFound: Either source edm::EventProcessor::beginRun(const edm::ProcessHistoryID &, edm::RunNumber_t, _Bool &, _Bool &) or target (anonymous namespace)::ChannelStatus is not in G
Traceback (most recent call last):
  File "/pool/condor/dir_27113/jenkins/workspace/ib-run-static-checks/CMSSW_11_3_X_2021-02-27-1100/bin/slc7_amd64_gcc900/edm-global-class.py", line 99, in <module>
    for n,nbrdict in G.adjacency_iter():
AttributeError: 'DiGraph' object has no attribute 'adjacency_iter'
 ```

### CODE REVIEW

**Comment by gartung** [comment]
@smuzaffar

**Comment by gartung** [comment]
please test

**Comment by gartung** [comment]
Fixes https://github.com/makortel/framework/issues/56

**Comment by gartung** [comment]
Resolves https://github.com/makortel/framework/issues/56

**Comment by makortel** [comment]
> Resolves [makortel/framework#56](https://github.com/makortel/framework/issues/56)

That should be put in the PR description for the automation.

**Comment by gartung** [comment]
@makortel  Thanks!

**Comment by gartung** [comment]
please test

**Comment by gartung** [comment]
please test

**Comment by gartung** [comment]
@makortel

**Comment by makortel** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
