### PR TITLE
Migration of HLT menus to 1100pre13 template (110X)

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
#### PR description:

Migration of HLT menus to 1100pre13 template (110X)

#### PR validation:

TSG tests

#### if this PR is a backport please specify the original PR:

#28519

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
backport of #28519

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
