### PR TITLE
Run3-gem39 Modify the ESProducer for GEM/ME0 to work better for ddd/dd4hep

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Modify the ESProducer for GEM/ME0 to work better for ddd/dd4hep

#### PR validation:

Tested using  runTheMatrix test workflows

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@slomeo @watson-ij I @ianna cleaned up the ESProducers of GEM/ME0 and making 2 cff files available so that switching from ddd to dd4hep can be straightforward and in production job the choice of ERA can help. There are still issues with filtered view of dd4hep which gives wrong #'s of nodes in the Expanded view. Also look at the validation cfg's which do not need all the other producers.

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
@bsunanda Thanks for cleaning this up.

**Comment by cvuosalo** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade

**Comment by silviodonato** [comment]
+1

**Pull request merged**
