### PR TITLE
Strip hit eff update 10_2_x

### PR DESCRIPTION
**Pull request by jlagram**
Update of the CalibTracker/SiStripHitEfficiency package used for measuring hit efficiency.
Mainly new selections added and update of tree format.

### CODE REVIEW

**Comment by mmusich** [comment]
@arunhep @lpernie can tests be started here? 
Fast review is appreciated (we foresee to backport to 10_1 as well)

**Comment by lpernie** [comment]
please test

**Comment by arunhep** [comment]
+1

**Comment by fabiocos** [comment]
@arunhep for my understanding, in which test wf is this supposed to run, if any? Not in the basic ones as far as I can see...

**Comment by mmusich** [comment]
@fabiocos is not run in any relval, if that's what you mean, but I add some time ago a unit test that (among other things) runs this code as well: [testProduceCalibrationTree_cfg.py](https://github.com/cms-sw/cmssw/blob/master/CalibTracker/SiStripCommon/test/testProduceCalibrationTree_cfg.py)

**Comment by fabiocos** [comment]
@mmusich ok, so in practice there has been a standalone test of this PR, right?

**Comment by fabiocos** [comment]
+1

**Comment by mmusich** [comment]
@fabiocos, in practice in the PR tests themselves unfortunately nothing was run, excepted the compilation, because the package in which the test resides was not touched, but we (Tracker DPG) tested it extensively.
This code by the way is sort of "private" in the sense that Tier-0 doesn't run it, but we use it for data monitoring purposes within the DPG.
The code changes proposed here are already running in our calibration tree production since first collisions without hiccups.
Let me attach here two plots from @jlagram to show the effect of the changes by "replaying" the workflow on a 2017 run: 

Old version:
image

New version:
image

**Comment by fabiocos** [comment]
@mmusich thanks for the reference documentation, I merged the code for AlCa use

**Pull request merged**
