### PR TITLE
multithreading fix for 74x: EcalRecalibRecHitProducer

### PR DESCRIPTION
**Pull request by fwyzard**
- change all configuration parameters into const members
- initialise them in the member initializer list
- remove unused methods and member variables
- change into a global::EDProducer
- make the consumes conditional on the data actually being used

### CODE REVIEW

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
tracked at #11317

**Comment by cvuosalo** [comment]
+1

For #11353 01efa5c26d39ce77c2cc4b814d171c14cb321844

Minor code clean-up in EcalRecalibRecHitProducer. There should be no change in monitored quantities.

The code changes are satisfactory, and Jenkins [tests](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-11353/8204/summary.html) against baseline CMSSW_7_4_X_2015-09-18-1100 show no significant differences, as expected.

**Comment by cvuosalo** [comment]
@fwyzard:
Could you please add to the description an explanation of the importance of adding this change to 74X and why you are making it at this late date? David may not want to merge it unless it is essential.

**Comment by fwyzard** [comment]
This is one of a dozen PRs that backport to 74x the changes to run the HLT
with multithreading.

Ciao,
.Andrea

**Comment by fwyzard** [comment]
backport of #10954 / #10966 to 74x

**Comment by fwyzard** [comment]
rebased to merge on top of both CMSSW_7_4_X and CMSSW_7_4_12_patch4

**Comment by fwyzard** [comment]
please test

**Comment by cvuosalo** [comment]
+1

#11353 6f0b7fe14332bdbc1ae944192feed2dc4f8246d6

Second approval after rebasing. New Jenkins tests show no problems.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
