### PR TITLE
Fix for HcalPFCuts_unittest

### PR DESCRIPTION
**Pull request by igv4321**
#### PR description:

A simple fix of HcalPFCuts_unittest in response to #41338

#### PR validation:

The test script now runs without errors

### CODE REVIEW

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by francescobrivio** [comment]
+1

 - the [HcalPFCuts_unittest](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-25dc9a/31974/unitTests/src/CondTools/Hcal/test/HcalPFCuts_unittest/testing.log) finished successfully

**Comment by francescobrivio** [comment]
+1

 - the [HcalPFCuts_unittest](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-25dc9a/31974/unitTests/src/CondTools/Hcal/test/HcalPFCuts_unittest/testing.log) finished successfully

**Comment by perrotta** [comment]
+1

**Pull request merged**
