### PR TITLE
Removed CMS deprecated warnings from  RecoEGamma/Examples

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

- removed unnecessary header includes
- added esConsumes

#### PR validation:

Code compiles.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
@makortel FYI

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
NOTE: I believe all the modules touched by this change are missing Event consumes calls and therefor have not functioned for all of Run 2. It would probably be good to review them for removal from CMSSW.

**Comment by slava77** [comment]
+reconstruction

for https://github.com/cms-sw/cmssw/pull/36577	c53bca2
- code changes are technical in line with the PR description
    - #36590 was added to keep track of a possible cleanup of unused code in the RecoEgamma/Examples package

**Comment by qliphy** [comment]
+1

**Pull request merged**
