### PR TITLE
add MinEta parameter to HLTSinglet

### PR DESCRIPTION
**Pull request by kirschen**
Would like to add MinEta parameter to HLTSinglet in order to be able to use it in path compilation (e.g. for SingleForwardJet path proposed by SMP for 2017 menu).

### CODE REVIEW

**Comment by kirschen** [comment]
@silviodonato @Martin-Grunewald 

Should there be any backports done in order to be able to use this in the 2017 menu?

**Comment by Martin-Grunewald** [comment]
It looks like we'll move to 910pre3 soon, and then there is no need for a backport.

**Comment by Martin-Grunewald** [comment]
please test

**Comment by silviodonato** [comment]
+1

**Comment by silviodonato** [comment]
I'm surprised about the "Reco comparison results: 1630 differences found in the comparisons".
This PR should not change anything in the current reco...

**Comment by silviodonato** [comment]
I see that also PR 18309 gives exactly the same comparison. So I assume everything is fine.
(I tried to run the HLT menu with the two different configurations and I got exactly the same results).

**Comment by davidlange6** [comment]
+1

**Pull request merged**
