### PR TITLE
Transfer the geometry parameters in a separate class so that they can…be accessed from DB as well as XML (PR 12628)

### PR DESCRIPTION
**Pull request by bsunanda**
… be accessed from DB as well as XML (PR 12628)

### CODE REVIEW

**Comment by bsunanda** [comment]
This is bsunanda:Run2-hcx58. The previous PR will be closed

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@ggovi I shall complete the requirement for going to DB once I complete the work for hexagonal cells of HGCAL. Right now this is a place holder in CondFormats and will hold all geometry parameters.

**Comment by civanch** [comment]
+1

**Comment by diguida** [comment]
@bsunanda it is not clear to me your https://github.com/cms-sw/cmssw/pull/12721#issuecomment-163309847. It is not advisable to have a placeholder as an entity class: this from first principles and also from the "no-shape-update" policy for such classes.
I would recommend the following: either you only proceed with the Geometry changes, and, when the work on hexagonal cells of HGCAL is done, you submit the producer code of the new object, or you complete the entity class design now along with its full integration in the Condition framework.
@ggovi can comment further.

**Comment by diguida** [comment]
@bsunanda given that you have expressed the need to include the geometry changes in the upcoming pre-release, may I suggest you to drop the addition of the new condition object and proceed with Geometry changes only?

**Comment by bsunanda** [comment]
This is not a condition object yet. It just happens to be in the right package. I shall complement that with the necessary stuff to become a condition object in the next version. I did not want to touch classes.h or the xml file because I am bound to change that in the next version. However without this I cannot make the geometry dependency correct.
________________________________

**Comment by diguida** [comment]
@bsunanda thanks for the clarification. Indeed now I see that the class is used in many places in the Geometry packages.
One thing not clear to me: in [`Geometry/HGCalCommonData/plugins/HGCalParametersESModule.cc`](https://github.com/cms-sw/cmssw/pull/12721/files#diff-bc11dcd48bfcb3f18f7bc6b0115370cc) you have and `ESProducer` pushing an instance of `HGCalParameters` into the `EventSetup` using `IdealGeometryRecord`. Has actually a brand new record to be used?
@ianna can you comment further?

**Comment by bsunanda** [comment]
We do not need a brand new record for this. IdealGeometryRecord is adequate for this. I am waiting for Yana's comments. She seems to be away
________________________________

**Comment by diguida** [comment]
@bsunanda partially true. I assume you want to follow the same pattern as `HcalParameters`. This entity class is in GT with its own record, namely `HcalParametersRcd` as you know. Indeed, there is an `ESProducer` using it: https://github.com/cms-sw/cmssw/blob/CMSSW_8_0_X/Geometry/HcalCommonData/plugins/HcalParametersESModule.cc

I am not an expert on this, so I hope @ianna can give more insight.

**Comment by bsunanda** [comment]
This PR is superseded by #12845

**Pull request closed without merging**
