### PR TITLE
Fix self-comparison in L1MuGMTExtendedCand

### PR DESCRIPTION
**Pull request by davidlt**
Signed-off-by: David Abdurachmanov <David.Abdurachmanov@cern.ch>

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
@rekovic - any idea if this function is used? This bug can affect any results from it

**Comment by rekovic** [comment]
@davidlt, Thanks. 
 
@davidlange6, This is an old code not in use. It has no affect on Run II.

**Comment by rekovic** [comment]
+1

**Comment by davidlt** [comment]
@rekovic the last time it was modified (meaningful) was in 2007. If it's that old and not used, maybe we can remove it from the release?

**Comment by davidlange6** [comment]
yes, lets get rid of obsolete code. Thanks @rekovic

**Comment by davidlange6** [comment]
+1

**Pull request merged**
