### PR TITLE
Phase2-hgx290 Provide better description of HGCal geometry description

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Provide better description of HGCal geometry description

#### PR validation:

Modify only the documentation. No need for tests

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

This PR updates the readme of Phase-2 geometry.

**Comment by qliphy** [comment]
+1

**Pull request merged**
