### PR TITLE
Add geometry scenarios for Castor

### PR DESCRIPTION
**Pull request by mmusich**
# Changes in GT
## RunII simulation
- **RunII Ideal scenario** : [DESRUN2_71_V2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/DESRUN2_71_V2) as [DESRUN2_71_V1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/DESRUN2_71_V2) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/DESRUN2_71_V2/DESRUN2_71_V1): 
  - Adding the `Extended2015CastorSystPlus`, `Extended2015CastorSystMinus` and `Extended2015CastorMeasured` labels for the `GeometryFileRcd` 
- **RunII Startup scenario** : [MCRUN2_71_V4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/MCRUN2_71_V4) as [MCRUN2_71_V2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/MCRUN2_71_V2) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/MCRUN2_71_V4/MCRUN2_71_V2): 
  - Adding the `Extended2015CastorSystPlus`, `Extended2015CastorSystMinus` and `Extended2015CastorMeasured` labels for the `GeometryFileRcd` 
- **RunII Asymptotic scenario** : [MCRUN2_71_V5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/MCRUN2_71_V5) as [MCRUN2_71_V3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/MCRUN2_71_V3) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/MCRUN2_71_V5/MCRUN2_71_V3): 
  - Adding the `Extended2015CastorSystPlus`, `Extended2015CastorSystMinus` and `Extended2015CastorMeasured` labels for the `GeometryFileRcd`

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
```
--------    -------------   -----------------
stat: cannot stat `dqm_empty.root': No such file or directory
read_missing_file_cfg.py ------------------------------------------------------------
19-Jan-2016 15:43:50 CET  Initiating request to open file file:dqm_missing.root
----- Begin Fatal Exception 19-Jan-2016 15:43:50 CET-----------------------
An exception of category 'FileOpenError' occurred while
   [0] Calling InputSource::readFile_
   [1] Opening DQM Root file
   [2] Calling StorageFactory::open()
   [3] Calling File::sysopen()
Exception Message:
Failed to open the file 'dqm_missing.root'
Input file file:dqm_missing.root was not found, could not be opened, or is corrupted.
   Additional Info:
      [a] open() failed with system error 'No such file or directory' (error code 2)
----- End Fatal Exception -------------------------------------------------
```
doesnt' seem to be related to the PR

**Comment by davidlange6** [comment]
please test

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
please test

**Pull request closed without merging**
