### PR TITLE
[94X][Change GTs] 2016,2017 JES and JER 

### PR DESCRIPTION
**Pull request by lpernie**
## Offline Data
-  https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_mcRun2_design_v2/94X_mcRun2_design_v4
-  https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_dataRun2_relval_v12/94X_dataRun2_relval_v14

## 2016 Simulation 
-  https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_dataRun2_v7/94X_dataRun2_v10
- https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_mcRun2_startup_v2/94X_mcRun2_startup_v3
- https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_mcRun2_asymptotic_v2/94X_mcRun2_asymptotic_v3
- https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_mcRun2cosmics_startup_deco_v2/94X_mcRun2cosmics_startup_deco_v3
-  https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_mcRun2_pA_v2/94X_mcRun2_pA_v3

## 2017 Simulation 
-  https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_mc2017_design_IdealBS_v10/94X_mc2017_design_IdealBS_v11
-  https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_mc2017_realistic_v14/94X_mc2017_realistic_v15
-  https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_mc2017cosmics_realistic_deco_v10/94X_mc2017cosmics_realistic_deco_v11
-  https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_mc2017cosmics_realistic_peak_v10/94X_mc2017cosmics_realistic_peak_v11

### CODE REVIEW

**Comment by lpernie** [comment]
backport of 23212

**Comment by lpernie** [comment]
please test

**Comment by lpernie** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
