### PR TITLE
[13_2_X] Use ZDC digis in uGT DQM

### PR DESCRIPTION
**Pull request by dinyar**
#### PR description:

Add unpacked ZDC digis to uGT DQM. This was overlooked when the ZDC unpacker was added to CMSSW.

Backport of https://github.com/cms-sw/cmssw/pull/43043

### CODE REVIEW

**Comment by tjavaid** [comment]
please test

**Comment by tjavaid** [comment]
backport of #43043

**Comment by syuvivida** [comment]
@dinyar very sorry for our late test, only got a chance to test this PR at playback with DQM streamers of run 375631. It's not clear to me if you could see any difference in DQMGUI plots. DQM clients all ran without problems. Could you take a look of the playback DQMGUI here in case any difference could be seen in L1T workspace?
https://cmsweb.cern.ch/dqm/online-playback
Thanks!!

**Comment by tjavaid** [comment]
> @dinyar very sorry for our late test, only got a chance to test this PR at playback with DQM streamers of run 375631. It's not clear to me if you could see any difference in DQMGUI plots. DQM clients all ran without problems. Could you take a look of the playback DQMGUI here in case any difference could be seen in L1T workspace? https://cmsweb.cern.ch/dqm/online-playback Thanks!!

Hi @dinyar , are you okay with the DQM GUI plots? The rest of the checks are okay to sign this PR.

**Comment by dinyar** [comment]
Hi @syuvivida, @tjavaid,

Thanks for this! The plots indeed look good now, comparing [1] with [2], the mismatches are now gone.

Cheers,
Dinyar

[1] https://cmsweb.cern.ch/dqm/online/start?runnr=375631;dataset=/Global/Online/ALL;sampletype=online_data;filter=all;referencepos=overlay;referenceshow=customise;referencenorm=True;referenceobj1=refobj;referenceobj2=none;referenceobj3=none;referenceobj4=none;search=;striptype=object;stripruns=;stripaxis=run;stripomit=none;workspace=L1TEMU;size=M;root=L1TEMU/L1TdeStage2uGT;focus=;zoom=no;
[2] https://cmsweb.cern.ch/dqm/online-playback/start?runnr=0;dataset=/Global/Online/ALL;sampletype=live;filter=all;referencepos=overlay;referenceshow=customise;referencenorm=True;referenceobj1=refobj;referenceobj2=none;referenceobj3=none;referenceobj4=none;search=;striptype=object;stripruns=;stripaxis=run;stripomit=none;workspace=L1TEMU;size=M;root=L1TEMU/L1TdeStage2uGT;focus=;zoom=no;

**Comment by tjavaid** [comment]
+1

**Comment by rappoccio** [comment]
+1

**Pull request merged**
