### PR TITLE
Add ECal-component modifiers and test workflows

### PR DESCRIPTION
**Pull request by srimanob**
#### PR description:
This PR adds modifiers `ecal_component` and `ecal_component_finely_sampled_waveforms` to avoid long customization, and add test workflows `.631` and `.632`.  

The customization comes from [this link](https://gitlab.cern.ch/-/snippets/2648).

#### PR validation:
Test with `20834.631` and `20834.632`.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:
No need of backport, or we can backport to 13_0 if it makes cmsDriver look more cleaner in production.

### CODE REVIEW

**Comment by srimanob** [comment]
test parameters:
- workflows = 20834.631,20834.632
- relvals_opt = --what cleanedupgrade,standard,highstats,pileup,generator,extendedgen,production,identity,ged,machine,premix,nano,gpu,2017,2026

**Comment by srimanob** [comment]
@cmsbuild please test

**Comment by srimanob** [comment]
type ecal

**Comment by civanch** [comment]
+1

It seems that this PR simplifies configuration.

**Comment by srimanob** [comment]
+Upgrade

The workflow need to be modified in follow-up PR, but this PR can be merged first, so that ECAL will have workflow to test and to develop.

**Comment by srimanob** [comment]
Ping @cms-sw/pdmv-l2

**Comment by jhakala** [comment]
What's the status on this PR?

As an aside, this looks like we are only implementing the workflows for the component method for Phase-II so far. However, it might be worth it to have workflows and simulated samples that have the component method for Phase-I as well, as a validation of the method (as recommended by Sasha Ledovskoy). So if this is stalled awaiting unrelated Phase-II ECAL developments, then maybe things could progress by using the component method for Phase-I insteaad.

**Comment by sunilUIET** [comment]
+pdmv

**Comment by srimanob** [comment]
@cmsbuild please test

Retest after a week before merging.

**Comment by srimanob** [comment]
> What's the status on this PR?
> 
> As an aside, this looks like we are only implementing the workflows for the component method for Phase-II so far. However, it might be worth it to have workflows and simulated samples that have the component method for Phase-I as well, as a validation of the method (as recommended by Sasha Ledovskoy). So if this is stalled awaiting unrelated Phase-II ECAL developments, then maybe things could progress by using the component method for Phase-I instead.

Hi @jhakala 
Thanks for the reminder of trying on Run-3. I agree that we should merge this PR and try to have a test on it. 
@perrotta @rappoccio Do we have a chance to merge this configuration PR to 13_3_0_pre3? Just to note, or if we need to wait for 13_3, it is fine too. Currently, this PR is waiting to refresh the test only. Thanks.

**Comment by perrotta** [comment]
+1

**Pull request merged**
