### PR TITLE
Reorganize Run2_2017 eras, and add matrix workflow for Run2_2017_trackingLowPU

### PR DESCRIPTION
**Pull request by makortel**
This PR reorganizes the phase1 eras using the newly added `ModifierChain.copyAndReplace()` feature (#17612). On the same go, two issues are fixed
- `run2_GEM_2017` was not applied for `Run2_2017_trackingPhase1CA` or `Run2_2017_trackingRun2`
- `run2_HEPlan1_2017` is removed from `Run2_2018` (@kpedro88's intention in #17605)

and a matrix workflow for `Run2_2017_trackingLowPU` is added.

Tested in 9_0_0_pre5 (rebased on top of CMSSW_9_0_X_2017-02-27-2300). No changes expected in standard 2017 workflows (special tracking workflows should show the appearance of `run2_GEM_2017`). IIUC 2018 workflows should show HE plan1->plan36. No changes expected in other (<= 2016, phase2) workflows.

### CODE REVIEW

**Comment by kpedro88** [comment]
@makortel thanks, looks good to me

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
Rebased on top of CMSSW_9_0_X_2017-02-27-2300, included `Run2_2017_trackingLowPU` in the reorganization, and added a workflow using it.

**Comment by kpedro88** [comment]
+1

**Comment by slava77** [comment]
@cmsbuild please test

```
+ grep 'Automatic merge failed' /build/cmsbld/jenkins-workarea/workspace/ib-any-integration/git-merge-result
+ grep 'Couldn'\''t find remote ref' /build/cmsbld/jenkins-workarea/workspace/ib-any-integration/git-merge-result

```
@smuzaffar what may be happening here?

**Pull request merged**
