### PR TITLE
tracking and strip DQM : trigger selection via DB + stage2 L1 handling in GenericTriggerEventFlag + update the trigger bits for Tracker DQM

### PR DESCRIPTION
**Pull request by mtosi**
this PR fix the issue w/ the merging I got w/ https://github.com/cms-sw/cmssw/pull/14786
(thanks a lot @mmusich !!!!! )

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
+1
I don't observe warnings about missing keys anymore

**Comment by mmusich** [comment]
@cvuosalo @dmitrijus @slava77 @vanbesien 
please have a look and approve ASAP, otherwise we'll have stacked dependencies on the GT development.

**Comment by mtosi** [comment]
@mmusich , thanks
the missing warning messages are expected, because of the update of the GT (thanks)

**Comment by dmitrijus** [comment]
+1

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/14820	10da65f
- code changes are in line with the title (and fractional descriptions available in the past ~3 PRs)
- jenkins tests pass and comparisons with baseline show no differences in RECO products or log error/warning messages, there are differences in ```/Pixel/Run summary|/SiStrip/Run summary/MechanicalView|/SiStrip/MechanicalView``` pattern of directories. Changes in DQM tracker plots are typically showing moderate reduction in the number of entries with shape roughly similar (see below)
- technical performance was tested with an earlier PR: there is no significant increase in CPU use.

wf134 902_fpix

wf134 902_tecpw1

**Pull request merged**
