### PR TITLE
guard against no L1T uGT digis in `L1TriggerResultsConverter` [`12_6_X`]

### PR DESCRIPTION
**Pull request by missirol**
backport of #40528

#### PR description:

This PR fixes the edge case reported in #40494. It adds a check on the size of the L1T uGT digis, returning `false` for all L1T algorithms when said input collection has `0` elements for the relevant BX (see https://github.com/cms-sw/cmssw/pull/40528#discussion_r1081662085 for details).

#### PR validation:

None beyond the checks done for #40528.

#### If this PR is a backport, please specify the original PR and why you need to backport that PR. If this PR will be backported, please specify to which release cycle the backport is meant for:

#40528

Bugfix to NanoAOD in release cycle to be used for data-taking.

### CODE REVIEW

**Comment by missirol** [comment]
type bugfix

**Comment by missirol** [comment]
enable nano

Not really necessary for this PR, but I understand XPOG requires this for PRs involving NanoAOD.

**Comment by missirol** [comment]
please test

**Comment by swertz** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
