### PR TITLE
Fix bug in PoolSource when skipping events with a missing file

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

If the configuration has N input files and skipEvents causes us to skip N-1 files and the last file can not be opened, the job would crash.

#### PR validation:

All framework unit tests pass.

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
+1

**Comment by silviodonato** [comment]
please test

**Comment by silviodonato** [comment]
+1

**Pull request merged**
