### PR TITLE
add pileup scenario for 2016 ultra legacy

### PR DESCRIPTION
**Pull request by gkrintir**
#### PR description:

This adds a pileup scenario for the 2016 ultra legacy (periods B-H), generated in the same way as the 2017 and 2018 UL scenaria #26572 and #27201 . The new scenario is named "2016_25ns_UltraLegacy_PoissonOOTPU".

### CODE REVIEW

**Comment by fabiocos** [comment]
please test

**Comment by plujan** [comment]
For more details on this pileup scenario, you can see this talk here:
https://indico.cern.ch/event/870037/contributions/3670166/attachments/1960095/3257291/Pileup20191210.pdf

**Comment by fabiocos** [comment]
+operations

**Comment by fabiocos** [comment]
@civanch comments?

**Comment by fabiocos** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by fabiocos** [comment]
@gkrintir could you please provide the backport to 10_6_X? 

@srimanob this is the bit you need for the additional 10_6_7_patch1, as far as I understand

**Comment by srimanob** [comment]
@fabiocos @gkrintir 
Yes, thanks very much.

**Comment by gkrintir** [comment]
ok sure @fabiocos @srimanob i'm doing that

**Comment by srimanob** [comment]
@gkrintir 
The PU distribution seems strange (==2018), could you please check again?

Thanks to TSG for reporting. @missirol @pgunnell @Sam-Harper @gennai 

Here is the distribution I got from this PR
Screenshot 2020-04-08 17 44 06

FYI @silviodonato

**Comment by gkrintir** [comment]
Hi @srimanob all, very sorry for that, I am checking what happened here and fixing it.

Regards

**Comment by gkrintir** [comment]
Hi @srimanob @ameyer-cern

Fixed in https://github.com/cms-sw/cmssw/pull/29431

**Pull request merged**
