### PR TITLE
Disabling BeamSpot EventDisplay filters

### PR DESCRIPTION
**Pull request by andrius-k**
Including and disabling (commenting out) Event Display and Beam Spot filters used in 2018 high pileup (HPU) run.

### CODE REVIEW

**Comment by andrius-k** [comment]
please test

**Comment by andrius-k** [comment]
+1

**Comment by fabiocos** [comment]
@andrius-k this is affecting only online DQM, right?

**Comment by fabiocos** [comment]
+1

**Comment by andrius-k** [comment]
@fabiocos yes, this is affecting only online DQM.

**Pull request merged**
