### PR TITLE
Output BadFED Channel only for Phase 1

### PR DESCRIPTION
**Pull request by tsusa**
This PR is follow up of the PRs: #25466, #25524, #25748, #26275 and #26606. It outputs the BadFEDChannels only for Phase 1 pixel detector as in the Phase 0 detector error 25 has different meaning. The aliases cfg files in SimGeneral/MixingModule are changed accordingly.
 
runTheMatrix and addOn tests were successfully run.

### CODE REVIEW

**Comment by tsusa** [comment]
@mmusich @veszpv

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
