### PR TITLE
[DD4hep] Expand DDSolidShape and LegacyShape Unit Test

### PR DESCRIPTION
**Pull request by ianna**
#### PR description:

* Make sure any future changes in the `DDSolidShape` enum are caught and propagated accordingly

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Comment by cvuosalo** [comment]
@adewit FYI. Please run this version of the test on #29905.

**Pull request merged**
