### PR TITLE
NanoAOD Update: trigger, nPV, pileup

### PR DESCRIPTION
**Pull request by arizzi**
This includes:
 - tune of trigger objects
 - fix of trigger bits when version number changes
 - n goodPV
 - oot pileup

All changes are in PhysicsTools/NanoAOD

@gpetruc

### CODE REVIEW

**Comment by gpetruc** [comment]
please test

**Comment by arizzi** [comment]
can someone please retrigger the tests?

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
@arizzi @gpetruc in the previous round of tests I see some warning messages in:

https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-22037/25760/runTheMatrix-results/1325.7_TTbar_13_94XNanoAODINPUT+TTbar_13_94XNanoAODINPUT+NANOEDMMC2017/step2_TTbar_13_94XNanoAODINPUT+TTbar_13_94XNanoAODINPUT+NANOEDMMC2017.log

In particular it looks like the LHE information is not correctly accessed...

**Comment by arizzi** [comment]
that's expected because not all samples are made from a LHE.

**Comment by fabiocos** [comment]
@smuzaffar apparently something went wrong with the test, could you please check?

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Pull request merged**
