### PR TITLE
CDC in 80X

### PR DESCRIPTION
**Pull request by aspiezia**
Implemention of cosmic reconstruction during collision. This could be really usuful for the alignment of the tracker. More details can be found in the following slides, presented at the tracking pog:
https://indico.cern.ch/event/527844/contributions/2160782/attachments/1269896/1881218/AnielloSpiezia_090516.pdf

This implementation is the back-porting of the 81X PR: https://github.com/cms-sw/cmssw/pull/14520/

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by lveldere** [comment]
+1

**Comment by slava77** [comment]
hold
do not merge until ready for event content update in data taking

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/14791	3d1e61d
- backport of cosmics during collisions. The same code changes as in https://github.com/cms-sw/cmssw/pull/14520	9773421
- jenkins tests pass and comparisons show no differences (new products are not monitored here)
- relying on tests in 81X and no issues in 810pre6 related to this

**Pull request merged**
