### PR TITLE
Fix usage of sys.argv in cmsRun configs

### PR DESCRIPTION
**Pull request by kpedro88**
#### PR description:

This PR accounts for two changes from #42650 in non-core packages:
1. When invoking `cmsRun config_file.py ...`, inside the Python config file, the contents of `sys.argv` are `["config_file.py",...]` (consistent with the result of `python3 config_file.py ...`). Previously, when using `cmsRun`, the contents of `sys.argv` would be `["cmsRun","config_file.py",...]`.
2. No need to include the `--` separator when calling `cmsRun config_file.py [args]` to pass `args` to Python.

Among other things, these changes allow removing various kludgey ways of handling the previous non-standard approach to passing arguments to Python. They also mean that index-based access to `sys.argv` shifts by 1.

#### PR validation:

Unit tests that were previously failing (https://github.com/cms-sw/cmssw/pull/42650#issuecomment-1721644905) now pass.

(Non-unit tested scripts are fixed on a best effort basis.)

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Unlikely to be backported, see discussion at #42650.

### CODE REVIEW

**Comment by kpedro88** [comment]
please test

**Comment by kpedro88** [comment]
These three unit tests are all failing in the IB, see https://github.com/cms-sw/cmssw/pull/42794#issuecomment-1725629229

**Comment by emanueleusai** [comment]
+1

**Comment by smorovic** [comment]
+1

**Comment by aloeliger** [comment]
+l1

**Comment by Martin-Grunewald** [comment]
+1

**Comment by perrotta** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

**Comment by civanch** [comment]
+1

**Comment by mandrenguyen** [comment]
+1

**Comment by kpedro88** [comment]
@cms-sw/generators-l2 please take a look

**Comment by makortel** [comment]
+core

**Comment by kpedro88** [comment]
hold
should not be merged until #42650 is ready
but @cms-sw/generators-l2 please sign in the meantime

**Comment by kpedro88** [comment]
please test
(for updates in #42650)

**Comment by kpedro88** [comment]
please test

**Comment by makortel** [comment]
+core

(this should be final round of signatures if we get them quickly)

**Comment by smorovic** [comment]
+daq

**Comment by srimanob** [comment]
+Upgrade

**Comment by perrotta** [comment]
+alca

**Comment by perrotta** [comment]
+db

**Comment by aloeliger** [comment]
+l1

**Comment by mmusich** [comment]
+hlt
   * re-sign

**Comment by kpedro88** [comment]
@cms-sw/dqm-l2 @cms-sw/generators-l2 @cms-sw/reconstruction-l2 @cms-sw/simulation-l2 please re-sign

**Comment by kpedro88** [comment]
unhold

**Comment by antoniovilela** [comment]
ping @cms-sw/generators-l2 @cms-sw/dqm-l2 @cms-sw/simulation-l2

**Comment by antoniovilela** [comment]
urgent
   - so this goes before other PRs and together with #42650

**Comment by tjavaid** [comment]
+1

**Comment by rappoccio** [comment]
+1

Requires co-dependency from https://github.com/cms-sw/cmssw/pull/42650 to resolve errors.

**Comment by rappoccio** [comment]
merge

**Pull request merged**
