### PR TITLE
Run3-sim63 Remove reference to DetectorDescription in some packages

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Remove reference to DetectorDescription in some packages

#### PR validation:

Use standard runTheMatrix.py

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
