### PR TITLE
Migrate to CondDB Configuration

### PR DESCRIPTION
**Pull request by ianna**
- Use CondDB configuration
- Skip HGCal test for run1&2

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
@ggovi - ok, I'll update the PR. Thanks.

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
@ggovi - please, review. Thanks.

**Comment by ggovi** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
