### PR TITLE
Reinitializing deleted pointers to nullptr

### PR DESCRIPTION
**Pull request by avetisya**
This is a small fix that sets deleted pointers to nullptr as requested in #14031 .

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test
PR for 80X?

**Comment by avetisya** [comment]
> PR for 80X?
I am trying, but I can't seem to make a pull request which has only this fix. What is the correct way to deal with a change that goes on top of something which has already been merged, but is not in an IB yet?

**Comment by Martin-Grunewald** [comment]
+1

**Comment by Martin-Grunewald** [comment]
Simply update the 80X PR you have already by pushing the additional fix to the same branch
you used to make the non-merged PR.

**Comment by fwyzard** [comment]
>> PR for 80X?

> I am trying, but I can't seem to make a pull request which has only this fix. What is the correct way to deal with a change that goes on top of something which has already been merged, but is not in an IB yet?

Without trying myself, I think you could
  - create an area for the latest IB
  - git checkout CMSSW_8_0_X
  - git pull
  - git cherry-pick 96f6006e549f2bd114dd324bd752416b6e7b7ea9  # this is the 8.1.x commit
  - git push my-cmssw HEAD:nullptr-reinitialization-fix-80x

.A

**Comment by avetisya** [comment]
Thanks. I reused the old branch and it seems to work. I was worried that pushing to this branch would modify the existing pull requests which use it, but it looks like once they're merged, they can no longer be modified.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
