### PR TITLE
back-port workflowsf from 74x

### PR DESCRIPTION
**Pull request by franzoni**
back-port workflows which are pythia8 in 74 and did not exist at the time of 71

### CODE REVIEW

**Comment by franzoni** [comment]
please test

**Comment by bendavid** [comment]
@franzoni I'm a bit confused.  The gen fragment that is being added here is a pythia6 fragment.

**Comment by franzoni** [comment]
hi @bendavid you're right.
For some reason in 74 we're still using that fragment for one of the samples asked by BPH a few weeks back. I'd be more than happy replacing it with a pythia8 one. Let's do that in 75 and (back-port?) to 71.
Since in 74x we have this pythia6 GEN-SIM for JpsiMuMu_Pt-15_forSTEAM_13TeV_cfi, we want to have the same in 71, for the final round of 74 validation.

**Comment by bendavid** [comment]
+1
(for the added fragment, not sure about the failing tests)

**Comment by franzoni** [comment]
the bot reports an error.
What is the error, actually? The output of the test workflows shows no failures (that I could find).

These lines:

Deprecated, please use -l limited
processing  relval_standard
ERROR in Matrix

appear in matrixTests.log , what error in matrix are we talking about ?

**Comment by davidlange6** [comment]
@franzoni,

cmsglimpse answers 

src/Configuration/PyReleaseValidation/python/relval_steps.py:             print "ERROR in Matrix”

where the error is presumably the one that appears on the line after you quote

overwritting 1323 not allowed

which looks to come from your PR changes

**Comment by franzoni** [comment]
thanks @davidlange6 
fixed.

**Comment by franzoni** [comment]
please test

**Comment by bendavid** [comment]
+1

**Comment by franzoni** [comment]
+1

**Comment by franzoni** [comment]
+1

**Comment by bendavid** [comment]
+1

**Pull request merged**
