### PR TITLE
Phase2-hgx308X Avoid compilation warnings in L1Trigger/L1THGCal

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Avoid compilation warnings in L1Trigger/L1THGCal

#### PR validation:

Use the runTheMatrix test workflows 

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cecilecaillol** [comment]
+l1

**Comment by jfernan2** [comment]
+1

**Comment by srimanob** [comment]
Thanks @bsunanda for the PR.

There are warning, reported in the static check, of the package `Validation/HGCalValidation`. The warning is on files that this PR does not touch. Would you mind to check and maybe include the fix.
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-9940b8/23900/llvm-analysis/runStaticChecks.log

**Comment by bsunanda** [comment]
I would not address them. Ideally declaration of objects defined as persistent (use of classes.h and classes_def.xml) should be in some DataFormats - please request this as an action item for some one to shift it in a different package - may be in DataFormats/Validation. It is beyond my action limit.
________________________________

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by srimanob** [comment]
+Upgrade

Technical PR, no change is expected. Thanks @bsunanda to fix the warning in `Validation/HGCalValidation/src/classes.h`.

**Comment by jfernan2** [comment]
+1

**Comment by cecilecaillol** [comment]
+l1

**Comment by perrotta** [comment]
+1

**Pull request merged**
