### PR TITLE
Protect against empty weight container from pythia8

### PR DESCRIPTION
**Pull request by mkirsano**
#### PR description:

Fix GeneratorInterface crash at the upgrade of pythia8 to 303

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by agrohsje** [comment]
Hi @mkirsano . Thanks for preparing this PR. Let me try to understand a little better. What was the example that crashed and why didn't this happen before? I am wondering if just filling the weight vector might cause problems upstream in production, hence my question.

**Comment by mkirsano** [comment]
With pythia8 303 any hadronization crashed if the pythia parameter nAttemps with value > 1 was used because if pythia8 works in the mode with only one weight, the weight container in HepMC record is empty. It was never empty in 302. May be a result of some optimization in pythia8. In principle, if there no multiple weights, this container is not needed, but this was not protected in CMSSW. I will ask the authors if this this a bug or a feature.

**Comment by silviodonato** [comment]
@cms-sw/generators-l2 is this PR ready?

**Comment by silviodonato** [comment]
(to be merged with  cms-sw/cmsdist#6286, #31816)

**Comment by mkirsano** [comment]
For me yes. Steve reproduced the behaviour in a standalone pythia8. If it is fixed we can reconsider this protection for the next version.

**Comment by agrohsje** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
