### PR TITLE
Add hasConversionTracks to nano

### PR DESCRIPTION
**Pull request by JaLuka98**
Description:
- Add the variable "hasConversionTracks" for photons to nanoAOD. It is a boolean indicating whether the photon has associated conversion tracks (either one-legged or two-legged).
- Also updated the DQM histograms with this variable.

Validation:
- Steps detailed under "Before making your pull request" at https://cms-sw.github.io/PRWorkflow.html succeeded.
- Variable adds 0.9 b/evt on average to the size of nanoAOD according to check with `python PhysicsTools/NanoAOD/test/inspectNanoFile.py <my_file.root> -j test.json -s test_size_report.html -d tes_doc.html`
- Validation dataset available ([DAS link](https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fphys03&input=%2FGluGluHtoGG_M-125_TuneCP5_13p6TeV_amcatnloFXFX-pythia8%2Fjspah-crab_HIG-Run3Summer22EE_ggH_MC_test-c8874b882f501f85a5949b2c322432c4%2FUSER))

@lfinco @fcouderc as Hgg conveners
@swagata87 @a-kapoor @RSalvatico as EGamma conveners

### CODE REVIEW

**Comment by RSalvatico** [comment]
type egamma

**Comment by JaLuka98** [comment]
> please test

Do we have to tell the bot "enable nano" to also do the nanoAOD tests before "please test"? Was recommended to me by a colleague. Thanks

**Comment by RSalvatico** [comment]
please abort

**Comment by RSalvatico** [comment]
enable nano

**Comment by RSalvatico** [comment]
please test

**Comment by JaLuka98** [comment]
@simonepigazzini @vlimant
Do we need a backport for this? Maybe for 13_1 and 13_0? For this, it might be relevant which nanoAOD version will use which version of CMSSW.

**Comment by simonepigazzini** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
