### PR TITLE
Port of fixes to set V2 as default db source for the GTs. 

### PR DESCRIPTION
**Pull request by ggovi**
The connection strings pointing to v1 have been replaced to the single V2 connection string.
In addition, the fixes for handling of cfg params in CondCore/ESSources have been ported.

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
-1
@ggovi the tests are failing because you didn't port the state of the art GTs (which are now included in `autoCond_condDBv2.py`) in the `autoCond.py`. Please change them in order to point at what is currently [here](https://github.com/cms-sw/cmssw/blob/CMSSW_7_4_X/Configuration/AlCa/python/autoCond_condDBv2.py)

**Comment by mmusich** [comment]
@diguida: note to ourselves, we are paying here the drift between `autoCond.py` and `autoCond_condDBv2.py`. Once my suggestion is implemented we will close the circle.

**Comment by diguida** [comment]
@mmusich correct, but keep in mind that the GT names are so long now that in V1 they could not be handled...
@ggovi and I worked on this PR before the meeting today. We cherry picked the changes from 76X, but then we had to revert the GTs from the 76X version to the 74X version, and, by mistake, we took them from the default, i.e. `autoCond.py` . They instead should have been taken from the vanilla version of `autoCond_condDBv2.py`.

**Comment by diguida** [comment]
The correct action would have been:
1. copy `autoCond.py` into `autoCond_condDBv1.py`, so we had the file pointing to V1 GT (done)
1. copy `autoCond_condDBv2.py` into `autoCond.py` so that the V2 GT appear the default (and we did not do)
1. cherry pick the other changes (done).

**Comment by ggovi** [comment]
@cmsbuild please acknowledge changes

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
+1 
though it would be nice to have also #11786 merged....

**Comment by mmusich** [comment]
@ggovi @diguida to avoid merging issues a made a new PR for the pending changes to the GTs #12022, cherry-picking from this one. Hope gets merged at some point....

**Comment by diguida** [comment]
-1
suppressed by #12022

**Pull request closed without merging**
