### PR TITLE
barrel vs ladder in roc level in 81x

### PR DESCRIPTION
**Pull request by gouskos**
add DQM plot for the Pixel barrel

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
-1
please fix cosmics configs. the digisrc parameter is needed there.

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
