### PR TITLE
Fixing a BS Issue affecting the Egamma HLT: 92X

### PR DESCRIPTION
**Pull request by Sam-Harper**
This is a backport of https://github.com/cms-sw/cmssw/pull/19884 to 92X which allows E/gamma pixel matching to have greater control over the region in Z it covers.  This is necessary to recover full efficiency of the electron triggers.

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by Sam-Harper** [comment]
@slava77, I've now posted plots on the cms-hlt e-group. Let me know if you want a direct link here although I'm now done for the night (5am start tomorrow)

**Comment by davidlange6** [comment]
please test

**Comment by perrotta** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by perrotta** [comment]
+1
(Same as #19884 in the master)
While adding new possibililities to be used in HLT, the default config does not modify what was in the previous version of the code. Jenkins results show no difference, in fact.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
