### PR TITLE
Cache the mapping from type_info to TypeWithDict for use in ObjectWithDict::dynamicType()

### PR DESCRIPTION
**Pull request by dan131riley**
In "lazy" evaluation mode (which @Dr15Jones wishes people wouldn't use), the expression evaluator calls `ObjectWithDict::dynamicType()` on every evaluation to check for virtual function overrides.  That call creates a new `TypeWithDict` for the real type of the variable using its `std::type_info` and `TClass::GetClass()`.  `GetClass()` traverses the ROOT global class list, taking at least a read lock on the list, leading to stack traces like this:

```
#11 0x00007fefeb52120a in ROOT::TReadLockGuard::TReadLockGuard (this=0x7fefb4738c20, mutex=0x7fefcf9619e0) at include/TVirtualRWMutex.h:107
#12 0x00007fefeacb1efc in TClass::GetClass (typeinfo=..., load=true) at core/meta/src/TClass.cxx:3111
#13 0x00007fefeba1886c in edm::TypeWithDict::TypeWithDict(std::type_info const&, long) () from libFWCoreUtilities.so
#14 0x00007fefeb9f5ee0 in edm::ObjectWithDict::dynamicType() const () from libFWCoreUtilities.so
#15 0x00007fefcc05aa0f in reco::parser::LazyInvoker::invokeLast(edm::ObjectWithDict const&, std::vector<edm::ObjectWithDict, std::allocator<edm::ObjectWithDict> >&) const () from libCommonToolsUtils.so
#16 0x00007fefcc03cfe7 in reco::parser::ExpressionLazyVar::value(edm::ObjectWithDict const&) const () from libCommonToolsUtils.so
#17 0x00007fefcc05dd19 in reco::parser::BinarySelector::operator()(edm::ObjectWithDict const&) const () from libCommonToolsUtils.so
```

In random stack samples and in the profiling tool "vtune", these calls are one of the leading causes of ROOT lock contention in a standard RAW2DIGI,L1Reco,RECO,EI,PAT job.  This PR adds a map from `std::type_index` to `TypeWithDict`, which is used to cache the results of these lookups.  A new function `TypeWithDict::byTypeInfo()` populates and interrogates the map.

Currently only `ObjectWithDict::dynamicType()` has been modified to use this cache.  While other uses of the `TypeWithDict` constructors could be modified to use this, in practice this PR plus #23058 are, in my test workflow, sufficient to eliminate all per-event calls to `GetClass` due to `TypeWithDict` construction.

By removing potential lock contention for "lazy" uses of the cut parser, this PR improves the throughput and efficiency of my 24-core RECO  test job by a modest but consistent 3%.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
@dan131riley Just checking,  this pull request alone will not see a speedup since the speedup also requires a change to the parser to call the new function?

**Comment by dan131riley** [comment]
@Dr15Jones the LazyInvoker calls `ObjectWithDict::dynamicType()`, which now calls the new function, so no change to the parser is necessary.

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
