### PR TITLE
Added new beam spots for pp (2017 5 TeV), XeXe, PbPb 92X

### PR DESCRIPTION
**Pull request by gsfs**
Backport of PR#21021

### CODE REVIEW

**Comment by gsfs** [comment]
Added Configuration/StandardSequences/python/VtxSmeared.py to this PR

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by gsfs** [comment]
By request, I added comment lines with documentation and commented out the old PbPb beam spot so it would not be used by mistake.

**Comment by civanch** [comment]
please test

**Comment by franzoni** [comment]
https://github.com/cms-sw/cmssw/pull/21021#issuecomment-346575901

Comment applies also to the PR already merged in master/10_0

@arunhep @lpernie

**Comment by civanch** [comment]
@gsfs , likely this PR should be closed because all productions are moved to newer releases.

**Comment by gsfs** [comment]
Done.

**Comment by gsfs** [comment]
Closed

**Pull request closed without merging**
