### PR TITLE
Factorize fast timing layer geometry dependent things from RECO algorithms.

### PR DESCRIPTION
**Pull request by lgray**
Allows D*Timing Eras to run as well as D5.

### CODE REVIEW

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by Dr15Jones** [comment]
+1

**Comment by lgray** [comment]
@slava77 Could you check this PR that everything is OK?

**Comment by lgray** [comment]
@slava77 I at least made sure that all the WFs run now and there are no missing products. Otherwise this should have no physics impact.

**Comment by slava77** [comment]
assign reconstruction
... although I think it will not work and someone with right permissions should say that

**Comment by lgray** [comment]
@civanch  @fabozzi  @srimanob @franzoni @hengne Please review and sign.

**Comment by slava77** [comment]
Just to repeat earlier call from Lindsey

@civanch @fabozzi @srimanob @franzoni @hengne Please review and sign.

this is blocking one other PR and is also keeping Timing workflows without the "I2" timing layer broken.

**Comment by davidlange6** [comment]
changes in sim are trivial - will bypass

**Pull request merged**
