### PR TITLE
fix hdr Utilities/XrdAdaptor

### PR DESCRIPTION
**Pull request by mrodozov**
Fix headers related to #15248

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by Dr15Jones** [comment]
What missing definition does this resolve?

**Comment by mrodozov** [comment]
src/Utilities/XrdAdaptor/src/XrdSource.h:52:76: error: 'HostList' in namespace 'XrdCl' does not name a type

**Comment by Dr15Jones** [comment]
Then please remove the include and add `class HostList;` between line 15 and 16. A forward reference is sufficient to solve this problem.

**Comment by mrodozov** [comment]
please test

**Comment by Dr15Jones** [comment]
@mrodozov looks like I was wrong and your first solution is the best (since we are dealing with a typedef and not an actual class).

**Comment by mrodozov** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
