### PR TITLE
Fix to allow concurrent processing of lumisections with ECAL DQM

### PR DESCRIPTION
**Pull request by tanmaymudholkar**
Change DQMOneLumiEDAnalyzer to DQMOneEDAnalyzer to allow concurrent processing of lumisections.

#### PR description:

This PR is meant to allow concurrent processing of lumisections with ECAL included in the workflow. This is done by changing the class from which the tasks inherit from DQMOneLumiEDAnalyzer to DQMOneEDAnalyzer.

No changes are expected in the output.

This PR supersedes earlier ECAL PR 30187 (https://github.com/cms-sw/cmssw/pull/30187).

#### PR validation:

The standard suite of tests was run: `runTheMatrix.py -l limited -i all --ibeos`

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Not a backport.

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
This PR should fix partially https://github.com/cms-sw/cmssw/issues/25090 in what concerns to EcalDQMonitorTask ecalMonitorTask. I am not sure if these changes are concurrent LS compliant, if experts could confirm it would be appreciated

**Comment by kpedro88** [comment]
-1
incorrect merge (do not use `cms-merge-topic` to resolve conflicts in a PR)
please follow instructions at http://cms-sw.github.io/tutorial-resolve-conflicts.html

**Comment by tanmaymudholkar** [comment]
Hi @kpedro88 , sorry for the botched merge attempt, I have followed the instructions and I think the PR should be OK now.

**Comment by jfernan2** [comment]
please test with #31699

**Comment by jfernan2** [comment]
@tanmaymudholkar  Ecal/Trends/LHC status by lumi  is now set to -1

**Comment by jfernan2** [comment]
please test with #31699

**Comment by jfernan2** [comment]
+1

**Comment by silviodonato** [comment]
please test with #31699
I've changed #31699 to use 4 threads

**Comment by tanmaymudholkar** [comment]
Hi @jfernan2 , it seems the tests have failed but due to reasons unrelated to this PR; all failures seem to be due to the `SiPixelCertification` module.

**Comment by silviodonato** [comment]
merge
yes, the errors are related to `SiPixelCertification`.
However, I still see 
```
The following modules require synchronizing on LuminosityBlock boundaries:
ESIntegrityTask ecalPreshowerIntegrityTask
```
@tanmaymudholkar could you migrate that missing module?

**Comment by silviodonato** [comment]
> merge
> yes, the errors are related to `SiPixelCertification`.
> However, I still see
> 
> ```
> The following modules require synchronizing on LuminosityBlock boundaries:
> ESIntegrityTask ecalPreshowerIntegrityTask
> ```
> 
> @tanmaymudholkar could you migrate that missing module?

https://github.com/cms-sw/cmssw/pull/31829 :-D

**Pull request merged**
