### PR TITLE
Fix qBin iteration in PixelCPEFastParamsHost.cc

### PR DESCRIPTION
**Pull request by mroguljic**
#### PR description:

Fix for this issue: https://github.com/cms-sw/cmssw/issues/46383
The loop for filling template info for different `qBins` now checks if any are skipped instead of relying on small fixed increments to prevent this.
If a `qBin` is skipped, fill its content with the value from the neighboring, lower-charged `qBin` 

#### PR validation:

Validation in progress

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Not a backport

Ran checks on: 29634.402
```
29634.402_TTbar_14TeV+2026D110_Patatrack_PixelOnlyAlpaka Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED  - time date Tue Oct 15 17:40:17 2024-date Tue Oct 15 17:26:23 2024; exit: 0 0 0 0
1 1 1 1 tests passed, 0 0 0 0 failed
```

### CODE REVIEW

**Comment by jfernan2** [comment]
fixes https://github.com/cms-sw/cmssw/issues/46383

**Comment by smuzaffar** [comment]
test parameters:
- workflow =29634.402

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test for CMSSW_14_2_UBSAN_X

**Comment by mroguljic** [comment]
> please test for CMSSW_14_2_UBSAN_X

I just ran some local tests for 29634.402 and it seems to hang, will have to do further checks

**Comment by mroguljic** [comment]
@smuzaffar 
I was able to run the wf locally. We can proceed with the tests.

**Comment by smuzaffar** [comment]
please test for CMSSW_14_2_UBSAN_X

**Comment by smuzaffar** [comment]
please test

**Comment by mmusich** [comment]
enable hlt_p2_timing

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by smuzaffar** [comment]
thanks @mroguljic , I confirm that ubsan runtime errors are [fixed now](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-4b6aa4/42212/runTheMatrix-results/29634.402_TTbar_14TeV+2026D110_Patatrack_PixelOnlyAlpaka/)

**Comment by mmusich** [comment]
> HLT P2 Timing: [chart](https://cmssdt.cern.ch/circles/web/piechart.php?data_name=hlt-p2-timing&resource=time_thread&filter=CMSSW_14_2_X_2024-10-15-1400&dataset=CMSSW_14_2_X_2024-10-15-1400-cmssw46392/el8_amd64_gcc12/30/Phase2Timing_resources)

Phase HLT timing is suggestive of a visible increase though.

**Comment by mmusich** [comment]
assign heterogeneous

**Comment by fwyzard** [comment]
@mroguljic could you squash all commits into one ?

**Comment by fwyzard** [comment]
I don't have any comments from the @cms-sw/heterogeneous-l2 side.
If there is a potential impact on the performance, can it be tested on the Run 3 HLT using the usual timing server ?

**Comment by jfernan2** [comment]
+1
Fine from the reco side

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test for CMSSW_14_2_UBSAN_X

**Comment by jfernan2** [comment]
+1
From the reco side

**Comment by fwyzard** [comment]
hold

> If there is a potential impact on the performance, can it be tested on the Run 3 HLT using the usual timing server ?

pending a measurement of the impact on the HLT timing

**Comment by smuzaffar** [comment]
any update on the impact on the HLT timing ?

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@mmusich , though I have restarted the tests to use latest IB but last HLT P2 timing results](https://cmssdt.cern.ch/circles/web/piechart.php?local=false&dataset=CMSSW_14_2_X_2024-10-15-2300-cmssw46392%2Fel8_amd64_gcc12%2F32%2FPhase2Timing_resources&resource=time_thread&colours=default&groups=hlt&filter=CMSSW_14_2_X_2024-10-15-2300&data_name=hlt-p2-timing&show_labels=true&threshold=0) were improved . Idle time was reduced from 644ms to 622ms.

**Comment by mroguljic** [comment]
> > pending a measurement of the impact on the HLT timing
> 
> @mroguljic can you run a quick round of Run3 HLT timing tests, just for peace of mind here?

Sure. I only did it once, a while ago, so it might not be quick though.

**Comment by mroguljic** [comment]
The timing results can be found here:
[CMSSW_14_1_1](https://cmshlttiming.app.cern.ch/display/mrogulji/CMSSW_14_1_1orig.20241104_100659) vs [CMSSW_14_1_1 with this PR cherry-picked](https://cmshlttiming.app.cern.ch/display/mrogulji/CMSSW_14_1_1.20241104_093740). The results are: 566.6 \pm 2.2 vs. 560.5 \pm 8.8

The HLT configuration was obtained with `hltGetConfiguration /dev/CMSSW_14_1_0/GRun/V41 --data --eras Run3 > test_config.py`.

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by smuzaffar** [comment]
please test

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
@fwyzard do you still have concerns about this PR given https://github.com/cms-sw/cmssw/pull/46392#issuecomment-2454215521 or can it be unheld?

**Comment by fwyzard** [comment]
unhold

**Comment by fwyzard** [comment]
If the results are reproducible, a slowdown of 1% is not exactly negligible.

**Comment by fwyzard** [comment]
Looking in more details the variability seems rather large, it's hard to say what the impact actually is.

**Comment by mroguljic** [comment]
> > If the results are reproducible, a slowdown of 1% is not exactly negligible.
> 
> The error on the second measurement is really large: 566.6 +/- 2.2 vs. 560.5+/- 8.8. Is there any way to reduce the uncertainty? Shall we try to run a "hand" measurment @mroguljic ?

I'll try resubmitting the timing jobs with a larger number of events. Timing experts might give better advice on how to reduce the uncertainty.

**Comment by mroguljic** [comment]
> > > If the results are reproducible, a slowdown of 1% is not exactly negligible.
> > 
> > 
> > The error on the second measurement is really large: 566.6 +/- 2.2 vs. 560.5+/- 8.8. Is there any way to reduce the uncertainty? Shall we try to run a "hand" measurment @mroguljic ?
> 
> I'll try resubmitting the timing jobs with a larger number of events. Timing experts might give better advice on how to reduce the uncertainty.

The uncertainty is still relatively large even after repeating with increasing --repeats and --nrevents in the timing submission script.
[Without PR](https://cmshlttiming.app.cern.ch/display/mrogulji/CMSSW_14_1_1central.20241112_130716) (557.9 +/- 9.2 evt/s!)
[With PR](https://cmshlttiming.app.cern.ch/display/mrogulji/CMSSW_14_1_1qbin_fix.20241112_124117) (561 +/- 4.8 evt/s).

I'll ask someone to understand if we can reduce this uncertainty.

**Comment by fwyzard** [comment]
Sorry, I missed that these changes are in

```c++
template <typename TrackerTraits>
void PixelCPEFastParamsHost<TrackerTraits>::fillParamsForDevice() {
  // this code executes only once per job, computation inefficiency is not an issue
  ...
```

So in principle there should not be _any_ impact on the event throughput ?

**Comment by fwyzard** [comment]
+heterogeneous

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
