### PR TITLE
edm::FileInPath: return reference to paths; cleanup code

### PR DESCRIPTION
**Pull request by iarspider**
#### PR description:

As suggested by @makortel in #46181.

#### PR validation:

Bot tests

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
Comparison differences are related to https://github.com/cms-sw/cmssw/issues/39803

**Comment by makortel** [comment]
@cmsbuild, please test

Let's see if that was a fluctuation

**Comment by makortel** [comment]
The peak allocated memory increase seems real. Maybe it would be better for this PR to change only the return types to be const references?

**Comment by makortel** [comment]
> The peak allocated memory increase seems real. Maybe it would be better for this PR to change only the return types to be const references?

Hold off. Comparing to the tests in https://github.com/cms-sw/cmssw/pull/46204 (that should only rename things), the maxmem reports look qualitatively awfully similar
* #46204: https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_14_2_X_2024-10-03-1100+77d206/64902/maxmem-comparison/
* This PR https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_14_2_X_2024-10-03-1100+3996f4/64918/maxmem-comparison/

What is common for both PRs is that they result in rebuilding most of CMSSW. Could this somehow impact the amount of allocated memory?

**Comment by makortel** [comment]
On absolute terms the difference seems to be about 32 MB.

**Comment by makortel** [comment]
+core

We shouldn't keep this PR as a hostage

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
