### PR TITLE
Offline PF hadron cluster calibration

### PR DESCRIPTION
**Pull request by spandeyehep**
Offline PF hadron cluster calibration for phase1 upgrade

Updated eta dependent corrections in the EndCap region.

Summary was presented in RECO/AT meeting on 23 Feb 2018: 
https://indico.cern.ch/event/706643/contributions/2899998/attachments/1606000/2548367/PF_Calibration_upgrade2018_23Feb2018.pdf

Please see slide no. 14 and beyond.

Involves following package:
RecoParticleFlow/PFClusterTools/

### CODE REVIEW

**Comment by slava77** [comment]
@spandeyehep 

It looks like the parameters are hardcoded. I was naively expecting an update that will also need a GT change and will perhaps work differently for 2018 compared to 2016/2017.

please confirm that this code is expected to work OK for 2017 and 2016 as well (this implies the expected behavior based on Run2_2016/2017 eras with 10_1_X release).

The response most likely depends on the origin of the large eta dependence. If it is due to issues in HCAL calibrations, this is perhaps temporary. 
@mariadalfonso @deguio @SeemaSharmaFnal please comment

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@spandeyehep 
please edit the title of this PR to be clear that it is about PF hadron calibrations

**Comment by spandeyehep** [comment]
@slava77 

> please confirm that this code is expected to work OK for 2017 and 2016 as well (this implies the expected behavior based on Run2_2016/2017 eras with 10_1_X release).

Technically, it should work. But performance with Run2_2016/2017 eras with 10_1_X needs to be checked. Don't expect much change though.  I have the old trees (used for 2017 mc-v2), will check closure. 

> The response most likely depends on the origin of the large eta dependence. If it is due to issues in HCAL calibrations, this is perhaps temporary.

We checked the 1D raw response distributions for EH and H hadrons separately. The H hadrons response seems to be okay. The EH hadrons (with ECAL+HCAL contribution) that showed main changes in the EndCap. Please refer to slides from 1 to 9 : https://indico.cern.ch/event/710716/contributions/2919957/attachments/1611180/2562845/1D_responses_6_March_2018.pdf

On slide no. 9, you can see long tails in the response distribution for EH hadrons in the EndCap region(outside tracker part).
We think this is mainly due to increased noise in ECAL in this version - this might be temporary  if ECAL thresholds get updated.

**Comment by spandeyehep** [comment]
By mistake I had clicked the wrong button to comment "close and comment".
Apologies for that.

**Comment by slava77** [comment]
> We checked the 1D raw response distributions for EH and H hadrons separately. The H hadrons response seems to be okay. The EH hadrons (with ECAL+HCAL contribution) that showed main changes in the EndCap. Please refer to slides from 1 to 9 : https://indico.cern.ch/event/710716/contributions/2919957/attachments/1611180/2562845/1D_responses_6_March_2018.pdf

>On slide no. 9, you can see long tails in the response distribution for EH hadrons in the EndCap region(outside tracker part).
We think this is mainly due to increased noise in ECAL in this version - this might be temporary if ECAL thresholds get updated.

OK, in case of ECAL, the change is perhaps more applicable to at least 2017, now that the thresholds are reduced compared to 9X reco.
@amassiro @crovelli 
do you agree that this can be blamed on noise or is it a property of reduced thresholds .. or is there a problem with ECAL calibration of this region?

**Comment by amassiro** [comment]
It is an interplay between removal of SelectiveReadoutAtParticleFlow (SR@PF) and the increased noise in 2018 compared to 2017 MC-v2.

**Comment by slava77** [comment]
On 3/8/18 5:17 AM, Andrea Massironi wrote:
> It is an interplay between removal of SelectiveReadoutAtParticleFlow
> (SR@PF) and the increased noise in 2018 compared to 2017 MC-v2.
> 
> —

Remind me please if the ECAL cluster calibrations are fully in place and
are consistent with the reco thresholds.
I'm trying to understand if we have any coupling to some other
calibrations that may be not complete yet.

IIUC, this is going to be affected by the step
particleFlowClusterECALUncorrected -> particleFlowClusterECAL
(done with PFClusterEMEnergyCorrector)
BTW, shouldn't this be done first, before calibrating at higher level
with PFEnergyCalibration as proposed in this PR

@Sam-Harper @jainshilpi EGM POG have worked on the calibrations done
with  PFClusterEMEnergyCorrector last year
Is it going to happen on 10_1_X time scale as well?

I can imagine that pure noise will not be addressed by the calibrations
in ECAL,
but if there is a large change in response at lower energies, then this
coupling between ECAL and PFHadron calibration is not good.

**Comment by slava77** [comment]
@spandeyehep @seemasharmafnal
I need a reminder of the definition of EH hadrons.
What are the thresholds in ECAL that distinguish H and EH hadrons?

**Comment by Sam-Harper** [comment]
@slava77 , the PF Ecal cluster corrections are the critical path for CMSSW_10_1_X. There have been problems in generation generally for the required samples and they are not yet ready. We are just waiting for them

**Comment by slava77** [comment]
OK, I got a response in the meeting today: the separation of H vs EH is defined by ECAL energy > 0.
So, if anything, this will be noise and PF Ecal cluster corrections are not coupled.
Sorry for the "noise" (of questions) towards ECAL/egamma.

**Comment by slava77** [comment]
@spandeyehep 
I see that the Energy range of the pion gun is  2 - 500 GeV.
May I ask you to show the response vs eta (p14 and p10 of your slides today in PPD) in a few split ranges in the pion gun energy, e.g 2-50, 50-200, 200-500.
Thank you.

**Comment by slava77** [comment]
on a second though, the EH hadron calibration target is the total ECAL+HCAL energy.
It's not just about the threshold separating EH from H hadrons.
So, obviously, the "ECAL+HCAL" calibration done at this level depends on the calibrations of ECAL inputs to this, which are a subject of PFClusterEMEnergyCorrector work.

**Comment by spandeyehep** [comment]
@slava77

I have made response vs eta plots in different true energy bins and also pasted the zoomed version of response vs true energy plots on the same slide for H & EH hadrons separately.
You can find the slides here: https://indico.cern.ch/event/710716/contributions/2919957/attachments/1611180/2564684/Response_vs_eta_in_etrue_bins_09_03_2018.pdf

**Comment by slava77** [comment]
On 3/8/18 11:29 PM, Shubham Pandey wrote:
> @slava77 <https://github.com/slava77>
> 
> I have made response vs eta plots in different true energy bins and also
> pasted the zoomed version of response vs true energy plots on the same
> slide for H & EH hadrons separately.
> You can find the slides here:
> https://indico.cern.ch/event/710716/contributions/2919957/attachments/1611180/2564684/Response_vs_eta_in_etrue_bins_09_03_2018.pdf
> 

Thank you.

Just to be sure, these are all after correction, right?

p3 2.5-2.75 region seems inconsistent in plots vs eta and vs Etrue: the
top plot has all points below the line, while the lower right has all
points slightly above the line.
same on p4
Similar problem is for comparison with p10 of the PPD slides: the
2.5-2.75 range has all points above the red line, while here p2,3,4
apparently have all points below the line.

Is it a feature of the fits in this region?
Somehow, it looks somewhat analogous to "- 1 -1 -1" = "+0.5"

**Comment by spandeyehep** [comment]
Hi @slava77 ,

> Just to be sure, these are all after correction, right?

That is correct.

About your other point:
There was a mistake from my side. I had pasted EH hadron's plots twice (for H hadron as well). Sorry for that, I have updated it now. Please have a look. 
https://indico.cern.ch/event/710716/contributions/2919957/attachments/1611180/2568863/Response_vs_eta_in_etrue_bins_09_03_2018.pdf

I'd also like to clarify the strange behaviour of bottom right most plot on slide no. 6 (response vs Etrue for EH hadron for outside tracker region).
The response points in that region are not to be taken literally, because our assumption that the distribution is gaussian doesn't fit there in the outside tracking region. What we should compare is the corrected response distribution vs raw one but indeed, the way we present these points, need improvements and we are working on it.

I'd also like to add that these Gaussian fits (or to be replaced by median) are not used to derive any calibration factors - we just use them to make these summary plots. But we do check 1D response distribution to make sure that corrections don't create any weird distributions, e.g. plots on slide no. 9.

**Comment by slava77** [comment]
Hi Shubham

On 3/13/18 7:28 AM, Shubham Pandey wrote:
> Hi @slava77 <https://github.com/slava77> ,
> 
>     Just to be sure, these are all after correction, right?
> 
> That is correct.
> 
> About your other point:
> There was a mistake from my side. I had pasted EH hadron's plots twice
> (for H hadron as well). Sorry for that, I have updated it now. Please
> have a look.
> https://indico.cern.ch/event/710716/contributions/2919957/attachments/1611180/2568863/Response_vs_eta_in_etrue_bins_09_03_2018.pdf

Thank you for the update.
The inclusive and binned plots look more consistent.

> 
> I'd also like to clarify the strange behaviour of bottom right most plot
> on slide no. 6 (response vs Etrue for EH hadron for outside tracker region).
> The response points in that region are not to be taken literally,
> because our assumption that the distribution is gaussian doesn't fit
> there in the outside tracking region. What we should compare is the
> corrected response distribution vs raw one but indeed, the way we
> present these points, need improvements and we are working on it.

Please remind me how the current calibration looks like in this region.
Did you have it shown in your plots on Mar 8?

> 
> I'd also like to add that these Gaussian fits (or to be replaced by
> median) are not used to derive any calibration factors - we just use
> them to make these summary plots. But we do check 1D response
> distribution to make sure that corrections don't create any weird
> distributions, e.g. plots on slide no. 9.
> 

I'm finishing up with checks from my side and will post something later
today.

My current understanding is still that the EH calibration nominally
requires ECAL cluster correction to be appropriately updated first.
Perhaps I'm overstating the significance of ECAL here.
May I ask you to plot ECAL_raw/E_raw or ECAL_raw/E_true  for several
slices of E_true
to compare it for this sample and the last year sample.

It could be that now we have much more noise in ECAL.
This will be visible in a low ECAL fraction spike in the distribution I
suggested above.
With significant noise " e> 0" selection just moves E-hadrons into EH
hadrons zone and probably breaks the assumptions of how EH hadron energy
is to be defined. In this case, perhaps "e> 0" is not anymore such a
good choice.

OTOH, if the ECAL calibrations are inconsistent in this area (their
update is in progress, AFAIK), it may make sense to derive these
corrections after the ECAL is done.

**Comment by slava77** [comment]
@spandeyehep 
@lpernie @arunhep 

what is the status of the payloads that for the calibrations that should be consumed with this new updated code?
IIUC, the hardcoded updates made here will not really work for 2016, but will perhaps be similarly applicable for 2017, although even that's not so certain.

We can drop the ball on 2016 for now, but a more appropriate calibration update which can handle the older eta dependence parameterization will eventually be needed for rereco of run2.

**Comment by spandeyehep** [comment]
Hi @slava77

>> Please remind me how the current calibration looks like in this region. Did you have it shown in your plots on Mar 8?

Yes we did point out this in PPD meeting , see the last comment on slide no. 12 here: 
https://indico.cern.ch/event/709771/contributions/2926441/attachments/1613803/2563642/PF_Calibration_upgrade2018_PPD_8_March_2018.pdf

>> May I ask you to plot ECAL_raw/E_raw or ECAL_raw/E_true for several slices of E_true to compare it for this sample and the last year sample.

I'm working on this.

>> what is the status of the payloads that for the calibrations that should be consumed with this new updated code?

We have created the payload and db file is ready and it has been okay'ed by JME AlCa contact (Sanguen). It will be queued in the next GT, tomorrow morning (time zone difference). 
db file: /afs/cern.ch/work/s/spandey/public/PF_cal/payload/CMSSW_10_1_0_pre2/src/PFCalibration.db
Metadata file: /afs/cern.ch/work/s/spandey/public/PF_cal/payload/CMSSW_10_1_0_pre2/src/PFCalibration.txt

@lpernie @arunhep

>> it may make sense to derive these corrections after the ECAL is done

We use raw ECAL energies. So if ECAL rechits are to be changed, definitely the calibrations need to be updated.

**Comment by slava77** [comment]
On 3/13/18 11:01 AM, Shubham Pandey wrote:
> <https://github.com/slava77>
> 
>         Please remind me how the current calibration looks like in this
>         region. Did you have it shown in your plots on Mar 8?
> 
> Yes we did point out this in PPD meeting , see the last comment on slide
> no. 12 here:
> https://indico.cern.ch/event/709771/contributions/2926441/attachments/1613803/2563642/PF_Calibration_upgrade2018_PPD_8_March_2018.pdf
> 

uhm, I interpreted this as updated calibrations based on the new sample.
I wanted to compare this to what we currently have in the release.

The text says "Response & resolution as a function of Etrue
of pions after applying new set of calibrations"

> 
> 
>         what is the status of the payloads that for the calibrations that should be consumed with this new updated code?
> 
> We have created the payload and db file is ready and it has been okay'ed by JME AlCa contact (Sanguen). It will be queued in the next GT, tomorrow morning (time zone difference).
> db file: /afs/cern.ch/work/s/spandey/public/PF_cal/payload/CMSSW_10_1_0_pre2/src/PFCalibration.db
> Metadata file: /afs/cern.ch/work/s/spandey/public/PF_cal/payload/CMSSW_10_1_0_pre2/src/PFCalibration.txt
> 
> @lpernie @arunhep


I'm now looking at comparisons for effects of just this PR to the baseline.
It appears that the changes in the code lead to very small changes in PF
hadron or jet response.
So, I'm going to sign off for the reco so that the rest is handled with
AlCa.


> 
>         it may make sense to derive these corrections after the ECAL is done
> 
> We use raw ECAL energies. So if ECAL rechits are to be changed, definitely the calibrations need to be updated.

your comparisons with MCv2 are suggestive that there can be some
significant changes in ECAL [unless that change is due to the HCAL
response].

**Comment by arunhep** [comment]
@spandeyehep 

> We have created the payload and db file is ready and it has been okay'ed by JME AlCa contact (Sanguen). It will be queued in the next GT, tomorrow morning (time zone difference).
> db file: /afs/cern.ch/work/s/spandey/public/PF_cal/payload/CMSSW_10_1_0_pre2/src/PFCalibration.db
> Metadata file: /afs/cern.ch/work/s/spandey/public/PF_cal/payload/CMSSW_10_1_0_pre2/src/PFCalibration.txt

ok we wait for the announcement on AlCa hn.

>it may make sense to derive these corrections after the ECAL is done

> We use raw ECAL energies. So if ECAL rechits are to be changed, definitely the calibrations need to be updated.

is this update planned also for 10_1_X or 10_2_X ?

**Comment by slava77** [comment]
>>    We use raw ECAL energies. So if ECAL rechits are to be changed, definitely the calibrations need to be updated.

>is this update planned also for 10_1_X or 10_2_X ?

AFAIK, ECAL PF calibrations were meant for 10_1_X. In the past there was no obvious interference between that and the PF hadron calibrations. So, perhaps that's roughly going to work out and we'd just need some re-tuning for 10_2_X.

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/22521 	d89b215
- updated dependence in eta to be able to better handle the region with eta > 2.5. This is just an update to the functional form of the eta-dependent correction. Old correction functions appear to still work OK
- jenkins tests pass and comparisons show differences starting from PF candidates and propagating downstream: changes are dominated in some energy changes of the PF neutral hadrons and a bit less so of pf photons (in jet environment).
- local tests with higher stats on 2016, 2017, and 2018 workflows using dijet and ttbar events show fairly similar impact essentially all in the range of eta about 2.5 to 3.
    - there is some reduction in the number of neutral hadrons (0.1 - 0.2% without PU and in 2016 PU case;  and ~0.6% with PU in 2017/2018). Their overall scale is down at eta > 2.5, in agreement with numerical change in the parameters, e.g. 11024 (2018 ttbar + PU) sumPt of neutral hadrons in this region is about 10% lower
pfdebug_sign1007vsorig_ttbar13tevpu2018wf11024p0c_log10particleflow_pt3
    - there is a slight increase in the number of pf photons (perhaps some rebalancing of the HCAL vs ECAL)
    - jet response is down by maybe 1-2% in the eta range around 2.5 to 3, e.g. in 2018 dijet wf 10871
wf10871_ak4pf_20-40_eta

As discussed earlier in the thread, there will also be a full update to the calibration functions (consumed as a DB payload). This is expected to make changes in the full eta range.

**Comment by arunhep** [comment]
@slava77 @perrotta 
the payloads have been made available https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3523.html
I am wondering whether this update should enter all the workflows (including Run-I, 2015, 2016 and 2017) ? It was like that for the last one. 
If yes, then can you please remind me the logic? 
Thanks.

**Comment by slava77** [comment]
On 3/15/18 3:39 AM, Arun Kumar wrote:
> @slava77 <https://github.com/slava77> @perrotta
> <https://github.com/perrotta>
> the payloads have been made available
> https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3523.html
> I am wondering whether this update should enter all the workflows
> (including Run-I, 2015, 2016 and 2017) ? It was like that for the last one.
> If yes, then can you please remind me the logic?
> Thanks.
> 

The logic in the past to still apply the same payloads to everything was
driven by incompatible changes in the functional form and only one
supported use of the functions.

Moreover, the rough strategy was also somewhat in line with  providing
the best values for the current year/primary campaign and just checking
that the rest doesn't break down beyond reason.

This time the old functions kind of still work (as clarified in my plots
posted earlier).
So, we could break the habit and apply to just 2018. OTOH, I think that
updating everything will still "kind of still work".

 If the inputs (HCAL and ECAL scales) are appropriately calibrated and
not noisy, I'd actually expect that one PF hadron calibration will work
reasonably OK across the board.

**Comment by arunhep** [comment]
@slava77 

> This time the old functions kind of still work (as clarified in my plots
> posted earlier).
> So, we could break the habit and apply to just 2018. OTOH, I think that
> updating everything will still "kind of still work".

can we please try with this approach first? I will open a PR either tonight or tomorrow.
its a lot of work for us if we incorporate the new calibration in all the GT queues and then have to revert it, if there will be inconsistencies.

**Comment by slava77** [comment]
On 3/15/18 8:32 AM, Arun Kumar wrote:
> @slava77 <https://github.com/slava77>
> 
>     This time the old functions kind of still work (as clarified in my plots
>     posted earlier).
>     So, we could break the habit and apply to just 2018. OTOH, I think that
>     updating everything will still "kind of still work".
> 
> can we please try with this approach first? I will open a PR either
> tonight or tomorrow.
> its a lot of work for us if we incorporate the new calibration in all
> the GT queues and then have to revert it, if there will be inconsistencies.
> 

Let's still get a confirmation from JME.

**Comment by arunhep** [comment]
@spandeyehep @seemasharmafnal can you please comment on above discussion?

**Comment by spandeyehep** [comment]
Hi @slava77, @arunhep

@slava - Thanks for the quick checks and we agree with your assessment. We are also trying to explicitly check the effects on 2017 samples but that will take a little more time. 

Applying it to 2018 is fine with us. Also from the PPD general meeting discussions today, we may have to do one more round of calibrations in coming weeks (?). 

In the meantime, we are also exploring if we can disentangle these explicit parametrized eta dependencies from the code (not much progress though yet but we are working on it).

@arunhep we think you can go ahead with Slava's suggestion.

Thanks,
Shubham & Seema

**Comment by arunhep** [comment]
@slava77 @spandeyehep i finally included these new calibrations in this PR #22642  in all the workflows including run-1 and 2015-16-17. Reason being we dont have separate queues for data for these years so to simplify things, I added them everywhere.
if you want to test this PR along with the GT updates then please go ahead.

**Comment by slava77** [comment]
@cmsbuild please test with #22642

**Comment by slava77** [comment]
On 3/16/18 8:10 AM, cmsbuild wrote:
> -1
> 

we'll have to wait for 03-16-1100 IB to be picked up by jenkins.
It didn't happen yet.
Perhaps in a couple of hours.

**Comment by slava77** [comment]
@cmsbuild please test with #22642

**Comment by fabiocos** [comment]
please test with #22642

**Comment by slava77** [comment]
@arunhep 
I see that changes from the new GT are much more pervasive.
Based on recent presentations in JME on the dependence of ECAL PF thresholds, I tend to think that this update is rather unique to the current  PF ECAL hit threshold setup for 2017/2018.
So, reapplying the same conditions update since the beginning of time doesn't look like a good idea.
It would be better if the GT update stays restricted to 2017/2018 in the PFCalibrations payloads.

E.g. 2012B data wf 4.53: 
with just the code update
all_oldvsnew_runphoton2012bwf4p53c_log10recopfcandidates_particleflow__rereco_obj_p75
code+GT update:
all_oldvsnew_runphoton2012bwf4p53c_log10recopfcandidates_particleflow__rereco_obj_p75
this leads to a pretty strong suppression of neutral hadrons.

The changes are similarly large in 2017 WFs as well
e.g. 136.788
with just the code:
all_oldvsnew_runsingleph2017b136p788c_log10recopfcandidates_particleflow__rereco_obj_p75
with code+GT
all_oldvsnew_runsingleph2017b136p788c_log10recopfcandidates_particleflow__rereco_obj_p75


Most likely we will eventually need to have 2017 and 2018 separately as well due to HCAL readout changes.

**Comment by slava77** [comment]
@fabiocos 
If we are going to integrate this in 10_1_X, I think that this PR should go in before the GT PR (if not at the same time)

**Comment by arunhep** [comment]
@slava77 
thanks for your analysis. i think this will require some work.
we will ask JetMET contact to prepare tags for data containing IOVs with different payloads.
Can we just have two payloads, one covering from run-1 until the end of 2017 and one for 2018 ?
similarly, for MC, shall we keep the old version of payload covering 2017 or we keep the new one for 2017 and 2018?

**Comment by slava77** [comment]
On 3/19/18 1:17 PM, Arun Kumar wrote:
> @slava77 <https://github.com/slava77>
> thanks for your analysis. i think this will require some work.
> we will ask JetMET contact to prepare tags for data containing IOVs with
> different payloads.
> Can we just have two payloads, one covering from run-1 until the end of
> 2017 and one for 2018 ?
> similarly, for MC, shall we keep the old version of payload covering
> 2017 or we keep the new one for 2017 and 2018?
> 

I think that now the choice of using old vs new is rather ad hoc and not
based on a detailed analysis.


Let me actually run higher stat tests to see how bad this gets for 2016.

**Comment by fabiocos** [comment]
@slava77 @arunhep I was considering to integrate at the same time both #22521 and #22642, assuming there is agreement at the ORP today. But from the checks and the subsequent discussion I understand that they would not be the end of the story, at least fro what concerns the GT for pre 2017 situation

**Comment by fabiocos** [comment]
+1

**Comment by slava77** [comment]
> Let me actually run higher stat tests to see how bad this gets for 2016.

I looked at changes in response and by the size, the impact varies depending on pt range:
- in 40 to 200: the 2016 case seems to be the worst compared to 2018 or 2017
in 2016 (red is new)
wf1338_ak4pf_40-200_eta
in 2018
wf10871_ak4pf_40-200_eta
- in the 20 to 40 GeV range the picture is mixed and the 2017 behaves differently from the rest showing a change in response everywhere and the 2016 has probably the smallest effect
2016:
wf1338_ak4pf_20-40_eta

2017:
wf10071_ak4pf_20-40_eta
2018:
wf10871_ak4pf_20-40_eta


The high-pt jets should be less affected by the noise, which should be more visible in the 20-40 GeV range.
The plots don't really give me a strong argument towards having to split up the payloads by the year immediately.
However, the differences in behavior among the 3 scenarios suggest that we will eventually need to have separate calibrations for 2016, 2017, and 2018 for the reprocessing during LS2.

**Pull request merged**
