### PR TITLE
Phase2-hgx335I Remove obsolete cfi's used for pre-V16 geometry versions of HGCal

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Remove obsolete cfi's used for pre-V16 geometry versions of HGCal. The test beam application of visualisation will not work at the moment. The TB files are in transition and this will be fixed soon.

#### PR validation:

Use the test script in Geometry/HcalCommonData/test/python

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by alja** [comment]
+1

**Comment by bsunanda** [comment]
+geometry

**Comment by perrotta** [comment]
+1

**Pull request merged**
