### PR TITLE
remove incorrect build dependencies on FWCore/PythonParameterSet

### PR DESCRIPTION
**Pull request by davidlange6**
#### PR description:

remove incorrect build dependencies on FWCore/PythonParameterSet

#### PR validation:

compilation is ok

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Comment by santocch** [comment]
+1

**Pull request merged**
