### PR TITLE
updating razor HLT paths for SUSY DQM in 74X

### PR DESCRIPTION
**Pull request by jmduarte**
updating razor HLT paths for SUSY DQM in 74X @parbol @duanders. Backport of #9020

### CODE REVIEW

**Comment by jmduarte** [comment]
Hi @degano @deguio,

The only error I see in the matrix test (https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-9021/21/runTheMatrix-results/matrixTests.log) is:
4.53_RunPhoton2012B+RunPhoton2012B+HLTD+RECODreHLT+HARVESTDreHLT+MINIAODDreHLT Step0-DAS_ERROR Step1-NOTRUN Step2-NOTRUN Step3-NOTRUN Step4-NOTRUN  - time date Mon May 11 17:20:12 2015-date Mon May 11 17:20:04 2015; exit: 1 0 0 0 0

The corresponding PR #9020 for 75X passed this test (https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-9020/7487/runTheMatrix-results/matrixTests.log):
4.53_RunPhoton2012B+RunPhoton2012B+HLTD+RECODreHLT+HARVESTDreHLT+MINIAODDreHLT Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Sun May 10 17:38:28 2015-date Sun May 10 17:18:46 2015; exit: 0 0 0 0 0

So is this a separate issue?

Thanks

**Comment by jmduarte** [comment]
Hi @degano,

Can we have a re-test? I ran 
timeout 7200 runTheMatrix.py --das-options="--cache das-cache.file --limit 0" --job-reports -j 12 -s -l 4.53
locally and got
10 10 9 7 6 tests passed, 0 0 0 0 0 failed

Thanks

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
