### PR TITLE
Preliminary L1T-HLT Interface for Phase-2 -- redux

### PR DESCRIPTION
**Pull request by trtomei**
This PR adds additional infrastructure for the L1T-HLT interface for Phase2.
It is a sister PR to #32137 and #32150 
We add a set of modules to implement selections on the L1T Phase-2 candidates

We ran scram b runtests with success.

We ran runTheMatrix.py -l limited -i all --ibeos with success.

And the `test/test_Phase2L1THLT.py` that we added runs succesfully!

```
$ cmsRun test_Phase2L1THLT.py
11-Dec-2020 05:46:31 CET  Initiating request to open file root://eoscms.cern.ch//eos/cms/store/mc/Phase2HLTTDRSummer20ReRECOMiniAOD/DYToLL_M-50_TuneCP5_14TeV-pythia8/FEVT/PU200_pilot_111X_mcRun4_realistic_T15_v1-v1/270000/FF7BF0E2-1380-2D48-BB19-F79E6907CD5D.root
%MSG-w XrdAdaptor:  file_open 11-Dec-2020 05:46:33 CET pre-events
Data is served from cern.ch instead of original site eoscms
%MSG
11-Dec-2020 05:46:41 CET  Successfully opened file root://eoscms.cern.ch//eos/cms/store/mc/Phase2HLTTDRSummer20ReRECOMiniAOD/DYToLL_M-50_TuneCP5_14TeV-pythia8/FEVT/PU200_pilot_111X_mcRun4_realistic_T15_v1-v1/270000/FF7BF0E2-1380-2D48-BB19-F79E6907CD5D.root
Begin processing the 1st record. Run 1, Event 194609, LumiSection 1113 on stream 0 at 11-Dec-2020 05:46:51.440 CET
Begin processing the 2nd record. Run 1, Event 194605, LumiSection 1113 on stream 0 at 11-Dec-2020 05:46:54.455 CET
...
TrigReport ---------- Module Summary ------------
TrigReport    Visited   Executed     Passed     Failed      Error Name
TrigReport        175        175        175          0          0 HLT_DoubleMu7_DZ0p33
TrigReport        175        175        175          0          0 HLT_HT90
TrigReport        175        175        175          0          0 HLT_MET90
TrigReport        175        175        175          0          0 HLT_MHT40
TrigReport        175        175        175          0          0 HLT_SingleEle7
TrigReport        175        175        175          0          0 HLT_SingleIsoEle7
TrigReport        175        175        175          0          0 HLT_SingleIsoPhoton7
TrigReport        175        175        175          0          0 HLT_SingleJet64
TrigReport        175        175        175          0          0 HLT_SingleMu7
TrigReport        350        175        175          0          0 L1PFHtMht
TrigReport        175        175        175          0          0 TriggerResults
TrigReport        175        175         20        155          0 l1tDoubleMuon7
TrigReport         20         20         19          1          0 l1tDoubleMuon7DZ0p33
TrigReport        175        175         68        107          0 l1tEle7
TrigReport        175        175         60        115          0 l1tIsoEle7
TrigReport        175        175        107         68          0 l1tIsoPho7
TrigReport        175        175         38        137          0 l1tMuon7
TrigReport        175        175         72        103          0 l1tPFHt90
TrigReport        175        175        117         58          0 l1tPFJet64
TrigReport        175        175         93         82          0 l1tPFMet90
TrigReport        175        175         67        108          0 l1tPFMht40
```

Only missing in the test are the flavours of L1T PFTau (`l1t::PFTau` and `l1t::HPSPFTau`), because we don't have samples with those objects yet.

### CODE REVIEW

**Comment by trtomei** [comment]
This is a second try of #32446

**Comment by silviodonato** [comment]
please test

**Comment by trtomei** [comment]
Hi, since this should be ready to be merged in its present state, I will go ahead and prepare the backport! :)

**Comment by silviodonato** [comment]
kind reminder @cms-sw/hlt-l2

**Comment by Martin-Grunewald** [comment]
+1

**Comment by silviodonato** [comment]
+1
@trtomei @fwyzard @Martin-Grunewald 
I was wondering how can we monitor that these new objects in the future.
Are you going to add an HLT phase-2 menu in the HLT test?
If not, we might add a unit test with `HLTrigger/HLTfilters/test/test_Phase2L1THLT.py`

**Comment by trtomei** [comment]
In the very near future, adding a unit test with `HLTrigger/HLTfilters/test/test_Phase2L1THLT.py` would probably be for the best. I have no idea how to ideal with the fact that it would need to have an input which we can guarantee exists (RelVal?)

In the midterm, the HLT menu of the TDR, which will also serve as a basis for further developments, will be in the release. But, at some point, it will start living in ConfDB together with the rest of the menus, so the situation is less clear to me.

**Pull request merged**
