### PR TITLE
Fixed the PPS alignment relval - 1042

### PR DESCRIPTION
**Pull request by MatiXOfficial**
#### PR description:

Following #35631 (and https://github.com/cms-sw/cmssw/issues/35764), this PR fixes the PPS alignment relval by adding `EDMtoMEConverter` to the 4th, harvesting step. Now, the harvester can read the plots booked by the worker in the 3rd step.

The results of the matrix test still contain corrections set to 0 though. The reason for that is insufficient (100) number of events. So, is there any way to increase the number of events to be more than 100?

#### PR validation:

The 1042 relval behaves as expected.

### CODE REVIEW

**Comment by tvami** [comment]
Screen Shot 2021-10-29 at 23 11 47

Nice, I see non-empty plots, as expected after all!

**Comment by tvami** [comment]
+alca
 * see https://github.com/cms-sw/cmssw/pull/35874#issuecomment-955050990
 * Jenkins tests pass

**Comment by tvami** [comment]
@cms-sw/pdmv-l2 @cms-sw/upgrade-l2 
this PR changes the number of events in this wf, but it still runs very fast, please consider signing

**Comment by srimanob** [comment]
+Upgrade

**Comment by bbilin** [comment]
@MatiXOfficial @tvami I think we would like to drop the -n 1000 option in two places. Otherwise it looks ok.

**Comment by bbilin** [comment]
+1

**Comment by tvami** [comment]
@perrotta @qliphy this is essentially fully signed now

**Comment by qliphy** [comment]
+1

**Pull request merged**
