### PR TITLE
  Level-1 Trigger changes for HI Firmware (76X backport of #12176)

### PR DESCRIPTION
**Pull request by harmonicoscillator**
76X backport of #12176

### CODE REVIEW

**Comment by mulhearn** [comment]
please test

**Comment by mulhearn** [comment]
I dunno about this backport.  Maybe this should wait for a patch of 76X?  But is it just too weird if this is in 75X and 80X but not 76X?

**Comment by mulhearn** [comment]
please test

**Comment by ggovi** [comment]
+1

**Comment by diguida** [comment]
@richard-cms do not forget to forward port https://github.com/cms-sw/cmssw/commit/06da8c1ed9784cf974cc6672cc5bef18b21fa915 here

**Comment by diguida** [comment]
@mulhearn concerning your comment in https://github.com/cms-sw/cmssw/pull/12180#issuecomment-152360423
It is needed if we want to make 76X able to run HI MC with the menu used online for data taking.

**Comment by mulhearn** [comment]
+1

**Comment by mulhearn** [comment]
+1

**Comment by diguida** [comment]
+1

**Comment by ggovi** [comment]
+1

**Comment by davidlange6** [comment]
cmsbuild, please test
(the comparisons are gone)

**Comment by davidlange6** [comment]
+1

**Pull request merged**
