### PR TITLE
DD Base Merge with Core

### PR DESCRIPTION
**Pull request by ianna**
* Move files from Base package to Core
* Remove spurious includes

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by ianna** [comment]
@smuzaffar - FYI, DetectorDescription/Base is obsolete now. However, I have not modified this one yet: http://cmslxr.fnal.gov/source/Utilities/ReleaseScripts/scripts/git-publish#0366

**Comment by civanch** [comment]
+1

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/19093	bdf08d0
- technical; reco packages are minimally affected, only in MagneticField/GeomBuilder
- jenkins tests pass

**Comment by kpedro88** [comment]
+1

**Comment by slava77** [comment]
-1 
superseded by #19106

**Comment by ianna** [comment]
@slava77 - if this one gets merged, rebasing the #19106 would not require any signatures except for Geometry

**Comment by slava77** [comment]
On 6/6/17 9:27 PM, Ianna Osborne wrote:
> @slava77 <https://github.com/slava77> - if this one gets merged,
> rebasing the #19106 <https://github.com/cms-sw/cmssw/pull/19106> would
> not require any signatures except for Geometry

it seemed easier this way.
is this PR needs an update, then it better be done in #19106.

**Pull request merged**
