### PR TITLE
Include branch split level in `edmDumpEventContent --all`

### LINKED ISSUE #946: Include branch split level in `edmDumpEventContent --all`

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

Adding branch split level to the output of `edmDumpEventContent --all` helped to figure out https://github.com/cms-sw/cmssw/issues/43923#issuecomment-2215275010 . 

Resolves https://github.com/cms-sw/framework-team/issues/946

#### PR validation:

The printout of `edmDumpEventContent --all` includes the added information

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
@Dr15Jones please review

**Comment by makortel** [comment]
+core

**Comment by rappoccio** [comment]
+1

**Pull request merged**
