### PR TITLE
Fix the random segfault of RelVal workflow 573

### PR DESCRIPTION
**Pull request by colizz**
#### PR description:

In the 4-thead workflow of 573, a segfault of the sherpa generator can **randomly** occur. The reason is that some thread will probabilistically handle zero events resulting from the first-come-first-serve principle to arrange events to threads. We enlarge the event number from 10 to 50 to fix this issue.

Please see more details in https://github.com/cms-sw/cmssw/pull/34527#issuecomment-907664078.

Besides, the waitTime in this workflow will be set to the default value (reverting e27c1367ab1790b236a38bee7699ea19e9053b3a), given the timeout issue in ExternalGeneratorFilter has been permanently solved in https://github.com/cms-sw/cmssw/pull/34815.

A backport to 12_0_X and 10_6_X is also needed.

#### PR validation:

Workflow 573 runs in the 4-thread mode.

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by qliphy** [comment]
test parameters:
- enable_test = threading
- workflow_threading = 573
- workflows = 573

**Comment by qliphy** [comment]
please test

**Comment by qliphy** [comment]
Looks good now. thanks @colizz

**Comment by agrohsje** [comment]
+generators

**Comment by bbilin** [comment]
+1

**Comment by AdrianoDee** [comment]
+upgrade
As explained in #34527, the fix solve the threading issue in 573.

**Comment by qliphy** [comment]
+1

**Pull request merged**
