### PR TITLE
speedup of some slower modules from miniAOD

### PR DESCRIPTION
**Pull request by slava77**
The update is supposed to be technical.
Tested on 1K events reminiAOD workflows and shows no differences.

Timing tests on 2018 setup miniAOD MC ttbar with PU50 show about 16% total job time reduction.
- PuppiProducer speedup by a factor 2.2
- PhotonIDValueMapProducer by a factor 9
- PFCand_AssoMap by a factor of 3.4

More details in 
- baseline https://slava77sk.web.cern.ch/slava77sk/reco/cgi-bin/igprof-navigator/CMSSW_10_3_0_pre5-miniOpt0_TTbar_13UP18+DIGIPRMX_AVE_50_BX_25ns.step6.200.871f3256d9c.pp/cumulative
- this PR https://slava77sk.web.cern.ch/slava77sk/reco/cgi-bin/igprof-navigator/CMSSW_10_3_0_pre5-miniOpt0_TTbar_13UP18+DIGIPRMX_AVE_50_BX_25ns.step6.200.O0-orig.pp/cumulative

About a half of the code line differences are due to untabifying \*AssoMapAlgos.cc

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/25092	7bb5bcb
- jenkins tests pass and comparisons with the baseline show no [relevant] differences as expected

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

always forgetting this for analysis...

**Pull request merged**
