### PR TITLE
GEM Reco Geometry from DB

### PR DESCRIPTION
**Pull request by ianna**
* Add GEM reco geometry producer from DB
* Allow the producer to run without GEM record present in EventSetup for backward compatibility

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by ianna** [comment]
@mmusich - FYI, a new GT with the new 2017 geometry scenario including GEM slice and the GEM reco geometry payloads (90YV1) will need this PR integrated. 

Note, I did not want to multiply python configurations, so this PR implements a check to avoid an exception thrown when a requested record is not available: the GEM reco geometry ES producer checks if the GEM record is available before asking for it. Please, let me know if there is a different policy to deal with cases like that. Thanks.

**Comment by mmusich** [comment]
adding @franzoni @arunhep as current leaders of the AlCa project

Thanks @ianna for the heads up, though is not totally clear to me what you mean with:

> a new GT with the new 2017 geometry scenario including GEM slice and the GEM reco geometry payloads (90YV1) will need this PR integrated.

since the involved record `GEMRecoGeometryRcd` already exists in release, the Global Tag with your request in https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2790.html can be cut at any moment.

Also what is the motivation to prevent calling the ES producer only if the record is available? Do I understand correctly that this will be needed only for 2017+ workflows? I would rather just let the producer die throwing some appropriate message whenever the record is not found.

**Comment by ianna** [comment]
@mmusich - yes, another option is to make a 2017 version of Configuration/Geometry/python/GeometryRecoDB_cff.py (which would require a cmsDriver update) or add an ES producer in 2017 Era customisation. I think, the final call is up to @slava77 and Reco group.

It is indeed for 2017+ workflows.

**Comment by davidlange6** [comment]
Hi @ianna - I'm also not so happy with the if statement - could this not just be handled via an existing era definition in the python config?

**Comment by ianna** [comment]
@davidlange6 - yes, then, I suppose, GeometryRecoDB_cff should include ​a new ConditionalRun3GeometryRecoDBConfiguration_cff:
```
from Configuration.Geometry.ConditionalRun3GeometryRecoDBConfiguration_cff import *
```
which would be something like:
```
import FWCore.ParameterSet.Config as cms

def _loadGeometryESProducers( processObject ) :
   processObject.load('Geometry.GEMGeometryBuilder.gemGeometryDB_cfi')

from Configuration.Eras.Modifier_run3_GEM_cff import run3_GEM
modifyGeometryConfigurationConditionalRun3GeometryRecoDBConfiguration_cff_ = run3_GEM.makeProcessModifier( _loadGeometryESProducers )
```
would this be acceptable? Note, I have not tested it yet, so any suggestions on names and implementation are welcome.

**Comment by ianna** [comment]
@davidlange6 - as discussed at ORP, @slava77 has no preference how GEM geometry produce is configured. However, it was proposed to integrate this PR to allow https://github.com/cms-sw/cmssw/pull/16900 integration which is on hold for now.

**Comment by slava77** [comment]
run2_GEMSliceTest is introduced in #16900

@ianna 
you mentioned ``` run3_GEM.makeProc ..``` , which should just go to the proper run3, so that we do not confuse what's run2 and what's run3.
I guess you can use the existing run3_GEM modifier here and @calabria will pick up with run2_GEMSliceTest in the other PR. This is all assuming that the addition of the GEM geom builder is generic.
Otherwise, this PR will need to include addition of run2_GEMSliceTest .

**Comment by ianna** [comment]
@slava77 - GEM reco geometry producer is generic, it reads a reco geometry record from a specific GT queue

**Comment by slava77** [comment]
I am curious if this PR is going to advance soon

**Comment by ianna** [comment]
@slava77 - no changes to this PR are expected. I think, any changes to move to era customisation should be done as a separate PR after PR #16900 is integrated.

**Comment by slava77** [comment]
On 1/28/17 1:20 AM, Ianna Osborne wrote:
> @slava77 <https://github.com/slava77> - no changes to this PR are
> expected. I think, any changes to move to era customisation should be
> done as a separate PR after PR #16900
> <https://github.com/cms-sw/cmssw/pull/16900> is integrated.

I was expecting that this PR goes out first.
Does it have to wait for #16900?

**Comment by ianna** [comment]
@slava77 - no it does not need to wait for #16900, I think, it's  waiting for #17198

**Comment by slava77** [comment]
On Jan 28, 2017 11:34 AM, "Ianna Osborne" <notifications@github.com> wrote:

@slava77 <https://github.com/slava77> - no it does not need to wait for
#16900 <https://github.com/cms-sw/cmssw/pull/16900>, I think, it's waiting
for #17198 <https://github.com/cms-sw/cmssw/pull/17198>



Ah OK.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/cms-sw/cmssw/pull/17130#issuecomment-275858256>, or mute
the thread

**Comment by davidlange6** [comment]
Hi @ianna - could you go ahead and implement your suggestion about eras, though I would propose keeping everything in GeometryRecoDB_cff instead of starting a new file. Thanks

**Comment by ianna** [comment]
@davidlange6 - I'd suggest to merge this PR and introduce the following changes when  #16900 is accepted. The latter defines run2_GEMSliceTest Era. Otherwise, I'd need to add this to an existing run3_GEM and then modify it again.

```
git diff
diff --git a/Configuration/Geometry/python/GeometryRecoDB_cff.py b/Configuration/Geometry/python/GeometryRecoDB_cff.py
index 1fa3fc1..f08dbed 100644
--- a/Configuration/Geometry/python/GeometryRecoDB_cff.py
+++ b/Configuration/Geometry/python/GeometryRecoDB_cff.py
@@ -1,5 +1,8 @@
 import FWCore.ParameterSet.Config as cms
 
+def _loadGeometryESProducers( processObject ) :
+   processObject.load('Geometry.GEMGeometryBuilder.gemGeometryDB_cfi')
+   
 #  Tracking Geometry
 from Geometry.CommonDetUnit.globalTrackingGeometryDB_cfi import *
 
@@ -24,4 +27,6 @@ from Geometry.HcalEventSetup.hcalTopologyIdeal_cfi import *
 from Geometry.TrackerGeometryBuilder.idealForDigiTrackerGeometryDB_cff import *
 from Geometry.CSCGeometryBuilder.idealForDigiCscGeometryDB_cff import *
 from Geometry.DTGeometryBuilder.idealForDigiDtGeometryDB_cff import *
-from Geometry.GEMGeometryBuilder.gemGeometryDB_cfi import *
+
+from Configuration.Eras.Modifier_run3_GEM_cff import run3_GEM
+modifyGeometryConfigurationConditionalRun3GeometryRecoDBConfiguration_cff_ = run3_GEM.makeProcessModifier( _loadGeometryESProducers )
```

**Comment by ianna** [comment]
+1

no code changes - just a re-base

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
@davidlange6 - FYI, configuration via Era is implemented in https://github.com/cms-sw/cmssw/pull/17324

**Pull request merged**
