### PR TITLE
Phase2-hgx343 Try to retrieve missing hits in the partial wafers of HGCal for DD4Hep description

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Try to retrieve missing hits in the partial wafers of HGCal for DD4Hep description

#### PR validation:

Use the scripts in SimG4CMS/Calo/test/python

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

we do not expect full regression for phase2 after this fix.

**Comment by civanch** [comment]
type bug-fix

**Comment by rappoccio** [comment]
+1

**Pull request merged**
