### PR TITLE
Adding a DQM module for dEdxHit info (74X)

### PR DESCRIPTION
**Pull request by quertenmont**
This PR add a DQM module to monitor dEdxHit info.
And also fix a small bug in the dEdxHitInfo producer in standard RECO.
Hope this can be included in the release that will be used for both MC and Data reconstruction
Backport of this changes for 75X are also there

### CODE REVIEW

**Comment by quertenmont** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
The bugfix will not make it  to any 74X MC useful for physics, the digi-reco campaign has started already.
Considering a very limited use case of the product, I think we can update it in 74X for data taking.

**Comment by quertenmont** [comment]
@slava77 Beside the DQM monitor, there is an important bug fix in this that absolutely need to be part of the signal samples.  I guess it's too late for the 50ns compaign even for my signals, but any chance to have this in for the 25ns compaign?
do you know who should I contact to get an answer ?  PPD?

**Comment by slava77** [comment]
On 5/19/15 12:59 AM, Loic Quertenmont wrote:
> @slava77 <https://github.com/slava77> Beside the DQM monitor, there is
> an important bug fix in this that absolutely need to be part of the
> signal samples. I guess it's too late for the 50ns compaign even for my
> signals, but any chance to have this in for the 25ns compaign?
> do you know who should I contact to get an answer ? PPD?


I think that all useful 25ns MC digi-reco  will be done in 75X.


> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cms-sw/cmssw/pull/9130#issuecomment-103349116>.
> 

-- 
***********************************************************************
 Vyacheslav (Slava) Krutelyov
 TAMU: Physics Dept Texas A&M MS4242, College Station, TX 77843-4242
 CERN: 42-R-027
 AIM/Skype: siava16              googleTalk: slava77@gmail.com
 (630) 291-5128  Cell (US)       +41 76 275 7116 Cell (CERN)

-----------------------------------------------------------------------

**Comment by deguio** [comment]
-1
ciao @quertenmont 
please see my comments at #9129
thanks,
F.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
The nominal policy is NOT to fix issues that change physics output in a major way in a production release where a major campaign has started.
In the case of 74X, the major MC campaign has started.  
So, if the object is buggy, it will remain buggy consistently between data and MC.

Realistically, 
- for 50 ns data, the  RECO data tier will be available and the newly introduced object is not really necessary
- MC will not be redone, except for private processing

If this product had sense only for data (and not MC), then we could apply the fix.
The story appears to be the opposite: there should be a meaningful solution for 50 ns data (RECO),
while the fix is really needed in MC (made only in AODSIM).

**Comment by quertenmont** [comment]
@slava77 Thanks for summarizing the options.
I would highly push to have the fix done in data.
We can easilly handle private signal samples for the analysis.
However, since we don't have skims anymore it is much more tricky to handle the data.  Even if the RECO is *temporarilly* preserved.  All the background study of the search is data-driven, so what counts the most in the data here.
Given that I am certainly the only user of this, it does not matter if a difference is induced between data and MC.
So please integrate this patch for the data reconstruction.

**Comment by deguio** [comment]
please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/9130	0f96434
- the same code changes as those that went in 75X with #9129 
- jenkins tests are successful and comparison with baseline show no difference (as expected for the setup of the tests).

Final decision to include this in 74X is still up to discussion (RECO meeting and beyond if needed).

**Comment by deguio** [comment]
+1

**Comment by quertenmont** [comment]
Hello,

I believe that it is time to finally merge this PR such that it's not forgotten for the reconstruction of real data.  Any chance to have this used for the 0T data ?

**Comment by davidlange6** [comment]
+1

**Pull request merged**
