### PR TITLE
Use correct python version

### PR DESCRIPTION
**Pull request by wmtan**
If "/usr/bin/python" is hard coded, the version of python used may not match the intended CMS version.
This has been causing problems in /afs.
This PR replaces "/usr/bin/python" with "/usr/bin/env python", so that the intended version of python will be used.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
I think the failure is from afs again since it says it can't find a particular variable name in a python module but when I look at our git repository for CMSSW_8_1_X that variable is there.

**Comment by Dr15Jones** [comment]
please test

**Comment by wmtan** [comment]
@cmsbuild The test failures are a problem in the IB itself and have nothing to do with this PR.

**Comment by fwyzard** [comment]
+1

**Comment by mmusich** [comment]
+1

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
+1

For #13442 347cb96a80ada3d0dcbc18138e14f5886b17fc09

Correcting the path to Python. There should be no change in monitored quantities.

The code changes are satisfactory, and Jenkins tests against baseline CMSSW_8_1_X_2016-02-23-2300 show no significant differences, as expected.

**Comment by Dr15Jones** [comment]
+1

**Pull request merged**
