### PR TITLE
update path of EDM files used in HLT tests [`12_5_X`]

### PR DESCRIPTION
**Pull request by missirol**
backport of #39770
backport of #39794

#### PR description:

In order to avoid issues with EDM files being moved to tape, this PR updates the path of files used in HLT tests (said files have been moved to a TSG area on EOS).

PS. It looks like some of these files were recently moved to tape. This didn't cause any issues centrally (e.g. PR tests), because those same files are saved in the EOS user area of the cmsbot. On the other hand, some of the TSG scripts may now fail locally if only the LFN is specified (as there is no automatic fallback on to the EOS area of the cmsbot when running locally, afaiu).

#### PR validation:

None beyond the validation done for #39770.

#### If this PR is a backport, please specify the original PR and why you need to backport that PR. If this PR will be backported, please specify to which release cycle the backport is meant for:

#39770

### CODE REVIEW

**Comment by missirol** [comment]
please test

**Comment by missirol** [comment]
+hlt

The RelVals-INPUT error is unrelated to this PR (this PR does not touch anything related to RelVals). I let the ORP decide whether or not re-running the tests is useful.

**Comment by missirol** [comment]
hold

See https://github.com/cms-sw/cmssw/pull/39770#discussion_r1000444707. The bugfix will be included in this backport.

**Comment by missirol** [comment]
unhold

This backport now includes the fix in #39794.

**Comment by missirol** [comment]
please test

**Comment by missirol** [comment]
+hlt

 - I claim that diffs in wf `11634.7` must be unrelated to this PR

**Comment by perrotta** [comment]
+1

**Pull request merged**
