### PR TITLE
Modernized TransientTrackBuilderESProducer

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

- added consumes calls
- switched to using ESGetToken
- added fillDescriptions
#### PR validation:

The code compiles.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
part of #26748

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/27002	bece13b
- technical
- jenkins tests pass

**Comment by fabiocos** [comment]
+1

**Pull request merged**
