### PR TITLE
[DQM] Fixed filling for TDCfatal in DT Online DQM Backport123X

### PR DESCRIPTION
**Pull request by jfernan2**
PR description:
Fixed a bug which made that Overflows and hit rejections/error were wrongly considered as TDCFatal too

PR validation:
Tested with private Online DQM client and run 351168

Checked that runTheMatrix.py -l limited works too

backport of https://github.com/cms-sw/cmssw/pull/38078

### CODE REVIEW

**Comment by jfernan2** [comment]
backport of https://github.com/cms-sw/cmssw/pull/38078

**Comment by emanueleusai** [comment]
- contributor tested online client privately

**Comment by emanueleusai** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
