### PR TITLE
Run3-gex50 Match the namespace between ddd and dd4hep for ECAL barrel algo

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Match the namespace between ddd and dd4hep for ECAL barrel algo

#### PR validation:

Tested by comparing the namespace of all volumes created by Ecal barrel algorithm in DDD and DD4Hep

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
@bsunanda In the PR description, please add an explanation of what problems this PR fixes.

**Comment by cvuosalo** [comment]
The code in`dd4hep/DDEcalBarrelNewAlgo.cc` now in some spots uses `ns.prepend(` and in other places `myns +`. Why are they mixed, not just all `myns +`? What is the explanation for why `ns.prepend(` is used for one name while `myns +` is used for another?

**Comment by cvuosalo** [comment]
I tested DD4hep simulation with this PR, and the misplaced volumes still appear:
```
DD4CMS           ERROR +++ Placement FAILED! Parent:eefixed:EECoolIns Child:eregalgo:ECVFE Valid:NO 
DD4CMS           ERROR +++ Placement FAILED! Parent:eefixed:EECoolIns Child:eregalgo:ECVFE Valid:NO 
DD4CMS           ERROR +++ Placement FAILED! Parent:eefixed:EECoolIns Child:eregalgo:ECVFE Valid:NO 
DD4CMS           ERROR +++ Placement FAILED! Parent:eefixed:EECoolQ Child:eregalgo:ECVFE Valid:NO 
DD4CMS           ERROR +++ Placement FAILED! Parent:eefixed:EECoolQ Child:eregalgo:ECVFE Valid:NO 
DD4CMS           ERROR +++ Placement FAILED! Parent:eefixed:EECoolQ Child:eregalgo:ECVFE Valid:NO 
```

**Comment by bsunanda** [comment]
@cvuosalo I just matched the namespace between DDD and DD4Hep. This did not cure that error -I knew that - this still needs investigation. this is just first step.

**Comment by bsunanda** [comment]
At least ECVFE's are now created with namespace eregalgo in the DD4Hep. In earlier version it was done with namespace ebalgo.

**Comment by cvuosalo** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
