### PR TITLE
L1T muon offline DQM config cleaning - 92x

### PR DESCRIPTION
**Pull request by thomreis**
Cleaning up of L1T muon offline DQM configuration

- Renaming of config files to be in line with Egamma naming scheme
- Changing the directory for the DQM output histograms
- Using the common efficiency harvesting module also used by L1TEgamma and dropping the special muon one
- Adding axis titles to efficiency plots
- Renaming the L1T muon offline module since it will not only produce histograms for efficiencies in the future but also resolution histograms and others.

### CODE REVIEW

**Comment by thomreis** [comment]
backport of #19724

**Comment by rekovic** [comment]
please test

**Comment by rekovic** [comment]
+1

**Comment by dmitrijus** [comment]
+1

**Comment by rekovic** [comment]
please test

**Comment by rekovic** [comment]
+1

**Comment by dmitrijus** [comment]
+1

**Comment by thomreis** [comment]
@davidlange6 can this be merged in order to be available at the T0 soon?

**Comment by davidlange6** [comment]
+1

**Comment by thomreis** [comment]
Hi @davidlange6
thanks for signing. Now it still says pending-signatures but everyone has signed already. What needs to be done still?

**Comment by davidlange6** [comment]
hi @smuzaffar - could you look at why this is not merged? must be a race condition in cms-bot?

**Comment by smuzaffar** [comment]
@davidlange6 , it was due to new label backport-ok which was holding the pending-approval label. This is fixed now https://github.com/cms-sw/cms-bot/commit/5ff4962d43eb349e39d504e378fbca1eaa439e6b

**Pull request merged**
