### PR TITLE
backport of small fixes from 81X branch

### PR DESCRIPTION
**Pull request by roger-wolf**
This is a version of backporting small fixes and cleanups from 81X, this time w/o internal merge conflicts. Rest is equivalent to this PR (*) that I would close after this one is integrated. 

Cheers,
Roger

(*)
https://github.com/cms-sw/cmssw/pull/15597

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
the unit test error is (n
```
python encountered the error: <type 'exceptions.ValueError'>
(cms.string(
'tauID("decayModeFinding") > 0.5 
& tauID("byLooseCombinedIsolationDeltaBetaCorr3Hits") > 0.5 
& tauID("againstMuonTight3") > 0.5 
& tauID("againstElectronVLooseMVA6") > 0.5'
),) 
is not a valid <class 'FWCore.ParameterSet.Types.string'>

```

**Comment by slava77** [comment]
Hi Roger,
just for a reference, please provide the PR number in 81X which introduced the feature backported here.

Thank you.

**Comment by roger-wolf** [comment]
Hi Slava, 

the PR this one is related to is this one:
https://github.com/cms-sw/cmssw/pull/14639

Cheers,
Roger

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
backport of #14639 
This is not an identical backport in terms of line edits. It is functionally the same  for the tau cleaning selections.

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/15705 ff31d57
- changes in cleanPatTau selections to be in line with POG recommended selections. The reco/miniaod is not affected: tau cleaning is not running in standard workflows. This is technically analysis-only PR.
- jenkins tests pass and comparisons with baseline show no differences.

**Pull request merged**
