### PR TITLE
Update the Phase-2 L1 vertex tag in the P2GT producer

### PR DESCRIPTION
**Pull request by artlbv**
#### PR description:
The updated collection has a new instance name: `L1VerticesEmulation`

Corresponds to this PR into the L1 offline repo: https://github.com/cms-l1t-offline/cmssw/pull/1169

#### PR validation:

Transparent change, validated in the L1 menu studies for the FastHisto PR.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

NTR

### CODE REVIEW

**Comment by srimanob** [comment]
@cmsbuild please test

**Comment by epalencia** [comment]
+l1

**Comment by artlbv** [comment]
hi, is there anything else missing to get this merged? thanks!

**Comment by srimanob** [comment]
Hi @artlbv 

Could you please clarify few thins:
(1) Is this kind of bug-fix, or both collections exist?
(2) I don't see any change in PR test. Is this because the P2GT is not used in test workflow, right?

**Comment by artlbv** [comment]
> (1) Is this kind of bug-fix, or both collections exist?

The "L1VerticesEmulation" is the new TrackTrigger vertex collection after some major updates on the GTT. 
The "old" collection exists in the 13_1 samples, but should not be reproduced when rerunning the L1 afaik. Maybe @BenjaminRS can precise this?

> (2)  I don't see any change in PR test. Is this because the P2GT is not used in test workflow, right?

Exactly, the P2GT is not in any standard sequence.

**Comment by aloeliger** [comment]
@cms-sw/upgrade-l2 While the L1 team is considering the creation of prototype phase 2 workflows, is there any objection to signing on this?

**Comment by BenjaminRS** [comment]
Hi - yes when running the latest code after [#42129](https://github.com/cms-sw/cmssw/pull/42129) was merged then the new collection name would be `L1VerticesEmulation`

**Comment by srimanob** [comment]
+Upgrade

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
