### PR TITLE
[HGC trigger] Update mapping for V11

### PR DESCRIPTION
**Pull request by jbsauvan**
FYI @kpedro88 @silviodonato @rekovic @bsunanda 

#### PR description:
Updated mapping for V11 after the changes in the cell validity checks implemented in #30323

Depends on external cms-data/L1Trigger-L1THGCal#19
Since PR #30323 has been reverted, it should be tested with #30467 + re-enable of L1T HGCAL in V11 (since it is disabled in #30467).

#### PR validation:
Minimal checks with the V11 geometry including the #30323 updates

### CODE REVIEW

**Comment by mrodozov** [comment]
test parameters:
- pull_request = cms-data/L1Trigger-L1THGCal#19

**Comment by silviodonato** [comment]
please test with https://github.com/cms-sw/cmssw/pull/30473,  cms-data/L1Trigger-L1THGCal#19

**Comment by jbsauvan** [comment]
That's strange, the wafer causing the error seems to be in the mapping file. I have to look in more details

**Comment by jbsauvan** [comment]
@kpedro88 
The V11 mappings are actually not correctly loaded. The V9 mappings are loaded instead.
The customization is done here:
https://github.com/cms-sw/cmssw/blob/b0ddd4e29c3f1b1e04ce77cdb7d49d15098f46b1/L1Trigger/L1THGCal/python/hgcalTriggerPrimitives_cff.py#L25-L26
But adding some printouts in the customization functions I see that first the V11 customization is called, followed by a call to the V9 customization (which erases the V11 customization).
It may be due to the order eras modifiers are called, but I don't know enough about that to conclude exactly what's going on.

**Comment by kpedro88** [comment]
@jbsauvan I'm not sure how the order/precedence works in the case of `makeProcessModifier`. @makortel do you know?

For the meantime, you can change the first line as follows:
```python
modifyHgcalTriggerPrimitivesWithV9Geometry_ = (phase2_hgcalV9 & ~phase2_hgcalV11).makeProcessModifier(custom_geometry_decentralized_V9)
```

**Comment by makortel** [comment]
Order of execution of ProcessModifiers is unspecified, so customizations should be organized such that they would not rely on any particular order.

**Comment by jbsauvan** [comment]
Thanks @kpedro88 I've changed the V9 modifier as suggested and it seems to work now.

**Comment by silviodonato** [comment]
please test with #30473, cms-data/L1Trigger-L1THGCal#19

**Comment by silviodonato** [comment]
merge

**Comment by kpedro88** [comment]
+upgrade

**Pull request merged**
