### PR TITLE
For TESTING CMS-BOT enable profiling command

### PR DESCRIPTION
**Pull request by gartung**
This is a test of the cms-bot scripts in my repo for adding and on demand profiling test

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by gartung** [comment]
enable profiling

**Comment by gartung** [comment]
test
enable profiling

**Comment by gartung** [comment]
abort

**Comment by gartung** [comment]
test enable profiling

**Comment by gartung** [comment]
abort

**Comment by gartung** [comment]
test enable profiling

**Comment by gartung** [comment]
enable profiling

**Comment by gartung** [comment]
test

**Comment by gartung** [comment]
abort

**Comment by gartung** [comment]
please test enable profiling

**Comment by gartung** [comment]
abort

**Comment by gartung** [comment]
enable profiling

**Comment by gartung** [comment]
enable gpu

**Comment by gartung** [comment]
enable_test gpu

**Comment by gartung** [comment]
enable_test profiling

**Comment by gartung** [comment]
enable gpu

**Comment by gartung** [comment]
enable profiling

**Comment by gartung** [comment]
enable profiling test

**Comment by gartung** [comment]
enable profiling, gpu

**Comment by gartung** [comment]
enable profiling, gpu

**Comment by gartung** [comment]
enable profiling, gpu

**Comment by gartung** [comment]
test with https://github.com/cms-sw/cmssw/pull/31318

**Comment by gartung** [comment]
abort

**Comment by gartung** [comment]
test with https://github.com/cms-sw/cms-bot/pull/1372

**Comment by gartung** [comment]
abort

**Comment by gartung** [comment]
The tests are being triggered in jenkins.
Test Parameters:
  - **ENABLE_BOT_TESTS** = PROFILING,GPU

**Comment by slava77** [comment]
-1

just to take if of our review list

**Pull request closed without merging**
