### PR TITLE
`HLTDeDxFilter`: prevent variable length array bound evaluates to non-positive value

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

In partial response to https://github.com/cms-sw/cmssw/issues/35036#issuecomment-1044139169

#### PR validation:

`cmssw` compiles.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by jpata** [comment]
@cmsbuild please test for CMSSW_12_4_UBSAN_X_2022-03-11-1100

**Comment by mmusich** [comment]
@jpata doesn't look https://github.com/cms-sw/cmssw/pull/37229#issuecomment-1066859320 had any effect.
Please clarify the intentions.

**Comment by jpata** [comment]
indeed... not sure why the bot didn't pick this up. I was running UBSAN offline now.

**Comment by jpata** [comment]
+reconstruction
- UBSAN error at `RecoTracker/DeDx/plugins/HLTDeDxFilter.cc:119:35` disappears
- no reco differences

**Comment by perrotta** [comment]
+1

**Pull request merged**
