### PR TITLE
PCC event producer update

### PR DESCRIPTION
**Pull request by samhiggie**
#### PR description:

Continuation of PR https://github.com/cms-sw/cmssw/pull/28807

Changed some of the names of the producers to match the nomenclature by most modules in cmssw. 

Added a fillDescription method so that the new AlCaPCCEventProducer may be added to the HLT configuration 

#### PR validation:

Compiles and Runs with local test files and HLT configuration like:
hltGetConfiguration /users/sharper/2019/alca/alcaLumi --setup /dev/CMSSW_10_6_0/GRun/V3 --globaltag auto:run2_hlt_GRun --unprescale > hlt.py 
(must replace AlcaPCCProducer with AlcaPCCEventProducer) 
FastReport Info:

FastReport     CPU time sched. / depend.    Real time sched. / depend.       Alloc. sched. / depend.     Dealloc. sched. / depend.  Processes and Paths
FastReport         3.4 ms         3.4 ms         6.3 ms         6.3 ms       +3333 kB       +3333 kB       -3081 kB       -3081 kB    Alca_LumiPixelsCounts_ZeroBias_v1
FastReport         0.0 ms         0.0 ms         0.1 ms         0.1 ms          +0 kB          +0 kB          +0 kB          +0 kB    Alca_LumiPixelsCounts_Random_v1

### CODE REVIEW

**Comment by silviodonato** [comment]
@samhiggie I'm afraid you have to rebase your PR using a newer release (the latest is CMSSW_11_1_X_2020-02-18-1100)

**Comment by samhiggie** [comment]
Thanks @silviodonato , I have to make another quick change anyway. I will make a new branch using the release you requested and remake the PR.

**Comment by slava77** [comment]
-1

rebase needed

**Comment by silviodonato** [comment]
Please open a new PR using a branch based on a more recent release

**Pull request closed without merging**
