### PR TITLE
Changed output file format and table layout

### PR DESCRIPTION
**Pull request by dinardo**
I've made changes in the layout of the output file in such a way to be conformal with the BeamMonitor DQM application.
Moreover I've removed the call to offlineBeamSpot since it's not needed.

- Mauro.

### CODE REVIEW

**Comment by dinardo** [comment]
I was wondering whether this PR can move forward.
Many thanks and kind regards.
- Mauro.

**Comment by dmitrijus** [comment]
@rovere Can this go in?
This PR changes the format of Vx3DHLTAnalyzer, will this affect the your developments in any way?

**Comment by rovere** [comment]
It can go, I just pushed this update also in 920patchX

**Comment by dinardo** [comment]
Dear All,
I’m a bit puzzled on how the system works.

I made PR to master because the robot automatically redirected me
to master every time I tried to make a PR NOT to the master branch.

I now see that somehow Rovere was able to make a PR to 920patchX.
Which is fine, but he made some modifications to what I did, so now my
PR to master is yet different to the PR to 920patchX of Rovere.

Can you guys please explain how shall I make future PR ?

Many thanks and kind regards,
- Mauro.

**Pull request closed without merging**
