### PR TITLE
Stub builder fix and new SW

### PR DESCRIPTION
**Pull request by sviret**
This PR contains an important bug fix for the Phase II tracker stub builder

### CODE REVIEW

**Comment by boudoul** [comment]
@delaere FYI

**Comment by kpedro88** [comment]
@sviret please apply code check patch as indicated

**Comment by kpedro88** [comment]
please test

**Comment by kpedro88** [comment]
@sviret the comparisons show a general increase in the number of stubs for all eta. Please confirm this is the expected behavior.

stubs vs eta

**Comment by sviret** [comment]
@kpedro88, yes this is an expected behaviour, thanks for noting it. The new stub window tuning introduced is inducing an increase of the stub rates. The previous tuning was too sharp, so that efficiencies at low pt were not very good.

**Comment by rekovic** [comment]
+1

**Comment by rekovic** [comment]
@sviret 
Can we have a backport of this to 93x, please.

@kpedro88 
This would be needed for a MC production in 93x, which L1 Trigger is trying to piggy back on 
HGCal MC production release.

**Comment by kpedro88** [comment]
+1

**Comment by kpedro88** [comment]
@rekovic the window for new changes in the initial production release closed last week. Maybe this can be put into a followup 93X release for L1-specific samples.

**Comment by davidlange6** [comment]
+1

**Comment by smuzaffar** [comment]
@sviret , @davidlange6 : looks like we have couple of relvals failing in IBs after these changes. Error is <a href='https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc6_amd64_gcc630/CMSSW_9_4_X_2017-09-19-2300/pyRelValMatrixLogs/run/20834.0_TTbar_14TeV+TTbar_14TeV_TuneCUETP8M1_2023D20_GenSimHLBeamSpotFull14+DigiFullTrigger_2023D20+RecoFullGlobal_2023D20+HARVESTFullGlobal_2023D20/step2_TTbar_14TeV+TTbar_14TeV_TuneCUETP8M1_2023D20_GenSimHLBeamSpotFull14+DigiFullTrigger_2023D20+RecoFullGlobal_2023D20+HARVESTFullGlobal_2023D20.log'>here</a>
```
----- Begin Fatal Exception 20-Sep-2017 17:26:46 CEST-----------------------
An exception of category 'StdException' occurred while
   [0] Processing  Event run: 1 lumi: 1 event: 3 stream: 2
   [1] Running path 'L1TrackTrigger_step'
   [2] Calling method for module TTStubBuilder_Phase2TrackerDigi_/'TTStubsFromPhase2TrackerDigis'
Exception Message:
A std::exception was thrown.
vector::_M_range_check: __n (which is 13) >= this->size() (which is 13)
----- End Fatal Exception -------------------------------------------------
```
gdb show this
```
#0  __cxxabiv1::__cxa_throw (obj=obj@entry=0x7fff8a323420, tinfo=0x7ffff6449a78 <typeinfo for std::out_of_range>, dest=0x7ffff6379920 <std::out_of_range::~out_of_range()>)
    at ../../../../libstdc++-v3/libsupc++/eh_throw.cc:62
#1  0x00007ffff638ca7d in std::__throw_out_of_range_fmt (__fmt=__fmt@entry=0x7fffc1461368 "vector::_M_range_check: __n (which is %zu) >= this->size() (which is %zu)")
    at ../../../../../libstdc++-v3/src/c++11/functexcept.cc:104
#2  0x00007fffc145f6fb in std::vector<double, std::allocator<double> >::_M_range_check (__n=<optimized out>, this=<optimized out>)
    at /cvmfs/cms-ib.cern.ch/nweek-02490/slc6_amd64_gcc630/external/gcc/6.3.0/include/c++/6.3.0/bits/stl_vector.h:804
#3  std::vector<double, std::allocator<double> >::at (__n=<optimized out>, this=<optimized out>)
    at /cvmfs/cms-ib.cern.ch/nweek-02490/slc6_amd64_gcc630/external/gcc/6.3.0/include/c++/6.3.0/bits/stl_vector.h:843
#4  TTStubAlgorithm_official<edm::Ref<edm::DetSetVector<Phase2TrackerDigi>, Phase2TrackerDigi, edm::refhelper::FindForDetSetVector<Phase2TrackerDigi> > >::PatternHitCorrelation (this=0x7fffd271ee00,
    aConfirmation=<optimized out>, aDisplacement=<optimized out>, anOffset=<optimized out>, aTTStub=...)
    at /build/muz/gdb/CMSSW_9_4_X_2017-09-22-2300/src/L1Trigger/TrackTrigger/src/TTStubAlgorithm_official.cc:119
#5  0x00007fffc148f20c in TTStubBuilder<edm::Ref<edm::DetSetVector<Phase2TrackerDigi>, Phase2TrackerDigi, edm::refhelper::FindForDetSetVector<Phase2TrackerDigi> > >::produce (this=0x7fffc93fb680, iEvent=...,
    iSetup=...) at /build/muz/gdb/CMSSW_9_4_X_2017-09-22-2300/src/L1Trigger/TrackTrigger/plugins/TTStubBuilder.cc:104
```

**Comment by sviret** [comment]
Very strange error.... Is the tracker geometry of your relval T5, because this is the error appearing when the stub builder is used with obsolete t3 geometry

**Comment by boudoul** [comment]
Hi @sviret , the track trigger group requested to  keep for some time the flat Geometry, and therefore has been kept by the offline team for this request .
And if you look at the IB failure, it's indeed the 2023D20 scenario which is failing (running the flat geometry https://github.com/cms-sw/cmssw/tree/master/Configuration/Geometry  ) .

**Comment by kpedro88** [comment]
@boudoul is the flat geometry still needed?

If so, we have a couple of options:
1. remove track trigger from the D20 workflows
2. add separate Eras to customize the track trigger for the flat geometry (incurs some maintenance burden)

I would prefer option 1 if it's acceptable.

**Comment by sviret** [comment]
@boudoul, I tend to support @kpedro88 fully on that. Keeping flat geometry in the track trigger is purely useless. In any case the stub builder is not maintained in that view anymore, and I heavily suspect that the track trigger reconstruction codes are not either.

**Comment by smuzaffar** [comment]
@boudoul , @sviret  any update/progress on this?

**Comment by boudoul** [comment]
Hi @smuzaffar , gimme <= a day (giving a talk at the CMS Week today) will come back to you after

**Comment by boudoul** [comment]
Addressed here : https://github.com/cms-sw/cmssw/pull/20687 
and backported for 93X here too : https://github.com/cms-sw/cmssw/pull/20688
thanks.

**Pull request merged**
