### PR TITLE
Apply code checks to the CaloOnlineTools packages

### PR DESCRIPTION
**Pull request by fwyzard**
Apply `clang-tidy` automated code changes.
Apply `clang-format` automated code formatting.

### CODE REVIEW

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by christopheralanwest** [comment]
please test

It's not clear that the tests ever started.

**Comment by silviodonato** [comment]
merge
alca:  @pohsun @tlampen @tocheng @christopheralanwest

**Comment by tlampen** [comment]
+1

**Pull request merged**
