### PR TITLE
JME bugfixes port of #23499

### PR DESCRIPTION
**Pull request by rappoccio**
Several JME bugs fixed here:

- AK8 jets needed rawFactor to reapply jet corrections
- AK4 jets needed muon fraction, addressing [this issue](https://github.com/cms-nanoAOD/cmssw/issues/169)
- Trigger objects needed AK8 jets, addressing [this issue](https://github.com/cms-nanoAOD/cmssw/issues/81)

9.4.x version is #23499

### CODE REVIEW

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
@rappoccio do you remind me which is the master version of this PR?

**Comment by rappoccio** [comment]
@fabiocos it's just one file, so I cherry-picked it for both master and 94x branches. I can do the same to any others that are necessary. I did the 94x one first.

**Comment by fabiocos** [comment]
@rappoccio sorry, 10_1_X is not the master branch, could you please have a master version as well?

**Comment by rappoccio** [comment]
Whoops, sorry! Done in #23557.

**Comment by fabiocos** [comment]
@arizzi @gpetruc is this PR ok for you?

**Comment by gpetruc** [comment]
10_1_1 doesn't have a physics-quality nanoAOD anyway since most of what went to 9_4_X was forward-ported only to 10_2_X (IIRC that was requested), so it's not obvious to me whether there's a usecase for the 10_1_X backport of this.

**Comment by fabiocos** [comment]
@rappoccio @gpetruc I think we can safely close this PR, please comment if you disagree

**Pull request closed without merging**
