### PR TITLE
FixedMultiplicity_MoreHistos

### PR DESCRIPTION
**Pull request by ramankhurana**
This PR has multiple (minor) changes or fixes in the JME DQM s/w. The slides were presented in JME-DPG 3 weeks ago. Wil be good for 2018 data taking.  https://indico.cern.ch/event/697045/contributions/2863770/attachments/1586988/2509637/JME-DQM-ReReco2018.pdf

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by boudoul** [comment]
Dear @ramankhurana , as you know the title of a PR is a very important ingredient of a PR , used at many stages . The title "From cmssw 9 2 2 rk multiple changes"  is not explicit at all, and we cannot guess what this PR is about,  could you please add a more descriptive title  ? Thank you

**Comment by ramankhurana** [comment]
Can I get the runMatrix command to do this test locally because, the code seems to work fine when running locally in CMSSW_9_2_2

**Comment by fabiocos** [comment]
@ramankhurana is there any news? if you want to reproduce the test you should just rung the short matrix with something like runThMatrix.py -t 4 -l limited , or expl;ictly specify the wf code that you want to test.

**Comment by ramankhurana** [comment]
@fabiocos I have tried and I could reproduce the error, however, I am still out of clue why the cmsRun is ok and runTheMatix fails with the segmentation fault. I hope to fix in 1-2 day timescale.

**Comment by smuzaffar** [comment]
please test
there were issues with eos earlier

**Comment by dmitrijus** [comment]
A couple of things wrong;
1. Remove commented out code;
2. Remove std::cout and std:cerr usages.

**Comment by fabiocos** [comment]
@ramankhurana what is the situation of this PR?

**Comment by ramankhurana** [comment]
The checked were always failing therefore I started from a different CMSSW version and PR is superseded by JMEDQM_AdditionalPlots (#22672).

**Comment by ramankhurana** [comment]
I am closing this PR because all changes are present in the other PR which is in process of merging.

**Pull request closed without merging**
