### PR TITLE
Provide default value for new parameter in Timing service.

### PR DESCRIPTION
**Pull request by Dr15Jones**

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by Dr15Jones** [comment]
@VinInn

**Comment by gartung** [comment]
Sorry I missed that.

**Comment by Dr15Jones** [comment]
@gartung no worries.

**Comment by davidlange6** [comment]
+1



On 1 Jul 2017, at 18:30, cmsbuild <notifications@github.com<mailto:notifications@github.com>> wrote:


+1
Tested at: 9b93320<https://github.com/cms-sw/cmssw/commit/9b93320cda8a4a9bb48b7c8e06b497feee239a98>
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-19500/21051/summary.html

The following merge commits were also included on top of IB + this PR after doing git cms-merge-topic:
096bdf0<https://github.com/cms-sw/cmssw/commit/096bdf0732c38c7f8b9f6e69ccd5f0a66c22017c>
You can see more details here:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-19500/21051/git-log-recent-commits
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-19500/21051/git-merge-result

**Pull request merged**
