### PR TITLE
[backport 93x] HGCal - bugfix - removing energy of out-of-range hits

### PR DESCRIPTION
**Pull request by felicepantaleo**
This PR is a bug fix and should solve the problem in #20458
Hits which are outside the 10cm radius from the center of gravity are removed by setting their fraction to zero, but their energy was never subtracted from the energy of the cluster.
This is a problem as the final energy of the PFCluster is not computed as the sum of the energy of the hits * their fraction, but it gets assigned the energy of the realistic cluster.
Recalibration is also included

backport of #20479
@rovere @kpedro88

### CODE REVIEW

**Comment by kpedro88** [comment]
backport of #20479

**Comment by kpedro88** [comment]
assign upgrade

**Comment by kpedro88** [comment]
please test

**Comment by felicepantaleo** [comment]
type bugfix

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/20507	353c6d1
- identical to the fix in the master/94X in #20479 . This affects only phase-2 HGCAL-related reco
- jenkins tests pass with expected differences in phase-2 reco monitoring

**Comment by kpedro88** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
