### PR TITLE
Made CSCIndexer const thread-safe

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

Converted delayed creation of fixed value std::vector to be a const static function local.

This problem was identified by the static analyzer.

#### PR validation:

Code compiles.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
@civanch the C++ language guarantees that function local statics are initialized once and only once by the first thread that encounters them. If a second thread arrives at the same time as the initialization is happening, the C++ language guarantees that the later threads will wait until the initialization is finished.

**Comment by civanch** [comment]
+1

Thanks @Dr15Jones !

**Comment by qliphy** [comment]
+1

**Pull request merged**
