### PR TITLE
Fix PR #24501

### PR DESCRIPTION
**Pull request by swozniewski**
#### PR description:

@perrotta This PR is to adress issue #26236. Some config dependecies were revised and VPSet defaults were implemented correctly. Duplicate configs are not yet removed, which would be addressed in a separate PR.

#### PR validation:

- compiles
- limited matrix tests were successful (checked before last commit, which added only some default VPSets)
- unit test PhysicsTools/PatAlgos/test/patTuple_PATandPF2PAT_cfg.py runs successfully

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
The segmentation fault in the "fastsim1" AddOn test looks correlated.
I prepared another possible version of this PR in #26254, in which that AddOn test passes. I don't know exactly why that test fails here, however: let test the other PR just to see what gets out.

**Comment by perrotta** [comment]
please test
(check if the AddOn test error is reproducible, as I don't see a possible culprit in the changes integrated here)

**Comment by swozniewski** [comment]
I currently try to reproduce it locally, but it doesn't seem to be reproducible. Let's see here...

**Comment by perrotta** [comment]
@swozniewski 

If both this one and #26254 succeed the integration tests, I would consider that #26254 may supersede this one, as it contains some additional cleaning. I would then suggest to merge #26254 in that case: do you see any counterindication with it?

(If tests fail, we just decided at the ORP that #24501 will get reverted for pre3).

**Comment by swozniewski** [comment]
Alright, I'm fine with that

**Comment by perrotta** [comment]
-1
- This PR solves the issue reported in #26236, but it is superseeded by #26254

**Comment by fabiocos** [comment]
@swozniewski @perrotta after the merge of #26254 I believe that this PR may be closed

**Comment by fabiocos** [comment]
@swozniewski can we just close this PR?

**Pull request closed without merging**
