### PR TITLE
Default Material Budget for Run1

### PR DESCRIPTION
**Pull request by ianna**
- Make sure Run 1 payloads with realistic material are reproducible from xml

### CODE REVIEW

**Comment by ianna** [comment]
+1

**Comment by ianna** [comment]
@davidlange6 - as just discussed at ORP this PR brings Run 1 xml files up-to-date with DB tags and also allows to reproduce the payloads.

**Comment by ianna** [comment]
@ktf - why do I get this message once an hour?

**Comment by nclopezo** [comment]
Hi @ianna,

@cmsbuild is not being able to do git cms-merge-topic using the pull request number. So we have to manually add the branch name and start the tests again. I just restarted them providing the branch name. 
@cmsbuild checks every hour, and because you approved this PR, it decides that it needs to be tested. I will make it check that the message is already there before posting it.

**Comment by ggovi** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
