### PR TITLE
Electron cut-based ID for Run3 from EGamma PR

### PR DESCRIPTION
**Pull request by DebabrataBhowmik**
#### PR description:

 This PR is to add electron cut-based IDs for Run3 from EGamma POG:
  - This will add Electron cut-based ID decisions for new optimized ID for Run3 from EGamma, ID trained from Run3Winter22 samples
  - The ID optimization and the comparison results can be found at: https://indico.cern.ch/event/1204275/contributions/5064343/attachments/2529616/4355064/Electron_cutbasedID_preliminaryID.pdf

#### PR validation:

runTheMatrix tests has been successfully run for testing :
  - runTheMatrix.py -l 12434.0
  - runTheMatrix.py -l 11834.0
  - runTheMatrix.py -l 10024.0
  - runTheMatrix.py -l 136.874
  Also a validation has been done to cross-check the ID efficiencies from the miniAOD level and compared with run2 ID decisions

#### Backport: 

This PR does not need any backportation 

 @cms-sw/xpog-l2 we would like to keep Fall17V2 ID decision and this new Run3 ID decision , both, in the upcoming nano because several early analysis are using Run2 ID for Run3, and it is working quite well , so they might or might not want to switch

### CODE REVIEW

**Comment by swagata87** [comment]
type egamma

**Comment by swagata87** [comment]
enable profiling

**Comment by swagata87** [comment]
@cmsbuild please test

**Comment by vlimant** [comment]
@DebabrataBhowmik ; can you please edit the description of this PR

**Comment by DebabrataBhowmik** [comment]
> @DebabrataBhowmik ; can you please edit the description of this PR

Hi, Just want to clarify it..
In my very first comment I forgot to remove "<! -" which probably caused null description, and I have mentioned the description and everything in the second comment. 
So, you want me to edit my first comment and add the description there?

**Comment by vlimant** [comment]
you can edit the description of the PR post-facto, instead of adding it in the first comment.

**Comment by DebabrataBhowmik** [comment]
> you can edit the description of the PR post-facto, instead of adding it in the first comment.

Ok editing it then..thanks for letting me know this 

> you can edit the description of the PR post-facto, instead of adding it in the first comment.

Ok edited...hope this is fine now
Thanks for letting me know this

**Comment by swertz** [comment]
@DebabrataBhowmik , could you please add the new Run3 ID also in nanoAOD: https://github.com/cms-sw/cmssw/blob/master/PhysicsTools/NanoAOD/python/electrons_cff.py

The Run3 ID should be disabled for the `run2_nanoAOD_ANY` modifier. If you want to keep both IDs in Run3 nanos, they should have an unambiguous branch name (for now it's only `cutBased`).

Also don't forget to add the new branch to the [nano DQM](https://github.com/cms-sw/cmssw/blob/master/PhysicsTools/NanoAOD/python/nanoDQM_cfi.py), similarly disabling nonexistent branches for the Run2 modifier [here](https://github.com/cms-sw/cmssw/blob/master/PhysicsTools/NanoAOD/python/nanoDQM_cfi.py).

**Comment by DebabrataBhowmik** [comment]
Hi @swertz, Thanks, we are working on the ID implementation in nanoAOD.
By the way, I noticed that the link you mentioned for "disabling nonexistent branches for the Run2 modifier" also points to the nano DQM code, is that correct?

**Comment by swertz** [comment]
> By the way, I noticed that the link you mentioned for "disabling nonexistent branches for the Run2 modifier" also points to the nano DQM code, is that correct?

Indeed, if a branch is not present it is better to also remove it from the DQM for that era.

**Comment by swagata87** [comment]
this PR can be closed, as Reza's new PR contains all modifications in this PR + the nano changes that are asked here.
See [this](https://github.com/cms-sw/cmssw/pull/39839#issuecomment-1290400304).

**Comment by DebabrataBhowmik** [comment]
As the new PR(https://github.com/cms-sw/cmssw/pull/39839) has been made containing all the commits of this PR + the ID implementation in nanoAOD, I am closing this PR.

**Pull request closed without merging**
