### PR TITLE
[10.1.X] [GT Updates] for HCAL Bug fixes and Jet Probability calibration for btagging

### PR DESCRIPTION
**Pull request by arunhep**
# Summary of changes in Global Tags 
 
## 2018_MC
 
   * **PhaseI 2018 cosmics scenario** : [100X_upgrade2018cosmics_realistic_deco_v7](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/100X_upgrade2018cosmics_realistic_deco_v7) as [100X_upgrade2018cosmics_realistic_deco_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/100X_upgrade2018cosmics_realistic_deco_v5) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/100X_upgrade2018cosmics_realistic_deco_v7/100X_upgrade2018cosmics_realistic_deco_v5): 
      * update of jet probability calibrations for b-tagging : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3464.html
      * HCAL bug fixes : https://indico.cern.ch/event/691337/contributions/2866494/attachments/1586921/2509518/ConditionUpdateProposal20180122.pdf
      * update of leftover ECAL TPG threshold tags
      * update of ECAL and CSC bad channel status

   * **PhaseI 2018 design scenario** : [100X_upgrade2018_design_IdealBS_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/100X_upgrade2018_design_IdealBS_v5) as [100X_upgrade2018_design_IdealBS_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/100X_upgrade2018_design_IdealBS_v4) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/100X_upgrade2018_design_IdealBS_v5/100X_upgrade2018_design_IdealBS_v4): 
      * update of jet probability calibrations for b-tagging : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3464.html
      * HCAL bug fixes : https://indico.cern.ch/event/691337/contributions/2866494/attachments/1586921/2509518/ConditionUpdateProposal20180122.pdf

   * **PhaseI 2018 realistic scenario** : [100X_upgrade2018_realistic_v9](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/100X_upgrade2018_realistic_v9) as [100X_upgrade2018_realistic_v7](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/100X_upgrade2018_realistic_v7) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/100X_upgrade2018_realistic_v9/100X_upgrade2018_realistic_v7): 
      * update of jet probability calibrations for b-tagging : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3464.html
      * HCAL bug fixes : https://indico.cern.ch/event/691337/contributions/2866494/attachments/1586921/2509518/ConditionUpdateProposal20180122.pdf
      * update of ECAL and CSC bad channel status

## 2017_MC 
 
   * **PhaseI 2017 cosmics peak scenario** : [100X_mc2017cosmics_realistic_peak_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/100X_mc2017cosmics_realistic_peak_v3) as [100X_mc2017cosmics_realistic_peak_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/100X_mc2017cosmics_realistic_peak_v2) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/100X_mc2017cosmics_realistic_peak_v3/100X_mc2017cosmics_realistic_peak_v2): 
      * update of jet probability calibrations for b-tagging : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3464.html

   * **PhaseI 2017 cosmics scenario** : [100X_mc2017cosmics_realistic_deco_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/100X_mc2017cosmics_realistic_deco_v3) as [100X_mc2017cosmics_realistic_deco_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/100X_mc2017cosmics_realistic_deco_v2) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/100X_mc2017cosmics_realistic_deco_v3/100X_mc2017cosmics_realistic_deco_v2): 
      * update of jet probability calibrations for b-tagging : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3464.html

   * **PhaseI 2017 design scenario** : [100X_mc2017_design_IdealBS_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/100X_mc2017_design_IdealBS_v3) as [100X_mc2017_design_IdealBS_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/100X_mc2017_design_IdealBS_v2) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/100X_mc2017_design_IdealBS_v3/100X_mc2017_design_IdealBS_v2): 
      * update of jet probability calibrations for b-tagging : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3464.html

   * **PhaseI 2017 realistic scenario** : [100X_mc2017_realistic_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/100X_mc2017_realistic_v3) as [100X_mc2017_realistic_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/100X_mc2017_realistic_v2) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/100X_mc2017_realistic_v3/100X_mc2017_realistic_v2): 
      * update of jet probability calibrations for b-tagging : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3464.html

### CODE REVIEW

**Comment by arunhep** [comment]
@cmsbuild please test

**Comment by arunhep** [comment]
please test

**Comment by arunhep** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
