### PR TITLE
Update compareDQMOutput.py

### PR DESCRIPTION
**Pull request by jfernan2**
#### PR description:

Fix for decode from python3

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by jfernan2** [comment]
urgent

**Comment by smuzaffar** [comment]
@jfernan2 , I am re-running the comparison job with this change. Lets see if DQM bin by bin part is fixed or not

**Comment by jfernan2** [comment]
Thank you! As far as my tests can see, it ifxes it.

**Comment by smuzaffar** [comment]
DWM bin by bin comparison result looks good now ( https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_0_X_2021-07-11-0000+94c05d/43999/dqm-histo-comparison-summary.html ).

**Comment by qliphy** [comment]
+1

**Pull request merged**
