### PR TITLE
Run2-TB13 Provide test beam simulation with beam spread

### PR DESCRIPTION
**Pull request by bsunanda**

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
@bsunanda , in the new Producer lines 45-48 are useless, even if they protected via ifdef. After first check these lines may be safely removed.

**Comment by perrozzi** [comment]
hi, does this need to be approved by GEN?

**Comment by civanch** [comment]
+1

**Comment by bsunanda** [comment]
@perrozzi Kindly review and approve this?

**Comment by davidlange6** [comment]
Hi @perrozzi - yes it does.

**Comment by perrozzi** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
