### PR TITLE
Changed the Hadronizer and scripts to work with Sherpa 2.2.0

### PR DESCRIPTION
**Pull request by thuer**
Changed the Interface and Scripts to work with Sherpa 2.2.0

The changes to the Sherpack retrieving method (from frontier to normal cp) https://github.com/cms-sw/cmssw/pull/11985 are not yet merged, should I cherry-pick the commits to this pull request and update the RelVal fragments?

### CODE REVIEW

**Comment by bendavid** [comment]
Yes, sorry, we missed re-signing that one after the last update.  Please include those commits here (since they are no longer needed in 76x)

**Comment by thuer** [comment]
Sorry for the many small commits, they were already in the previous pull request and it was easier to just cherry pick them

**Comment by covarell** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
