### PR TITLE
add workflow to test NANOAOD from 102X MC 2018 input

### PR DESCRIPTION
**Pull request by fabozzi**
Adding a new relval that produces NANOAOD from a 102X MC 2018 input

### CODE REVIEW

**Comment by davidlange6** [comment]
is there still some reason not to do nanoaod for all run2 relvals?

**Comment by fabozzi** [comment]
Currently no groups are validating nanoAOD, so this is mainly to run a test beyond IB.

**Comment by davidlange6** [comment]
validation is one of a number of reasons to run something in relvals... production testing is another. if things are expected to run, it seems like something CMS should be doing routinely now.

**Comment by fabozzi** [comment]
... indeed this workflow was meant for production testing, rather than validation

**Comment by davidlange6** [comment]
so just run it everywhere - simpler, more maintainable and provides more testing data.

**Comment by davidlange6** [comment]
please test

**Comment by fabozzi** [comment]
hold

**Comment by fabozzi** [comment]
@davidlange6 : following your suggestion, I have provided PR #24141 to enable the nano step to all workflows. If tests will be succesfull, we can close this one

**Pull request closed without merging**
