### PR TITLE
Add a cut in the HLTPFJetIDProducer module.

### PR DESCRIPTION
**Pull request by ndaci**
Add a cut on the total charged energy fraction in the HLTPFJetIDProducer module, in agreement with the TSG and the JetMET trigger conveners. The default value for the cut is set to 99.

An 80X backport PR will follow.

### CODE REVIEW

**Comment by ndaci** [comment]
The 80X backport PR is: #14602

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by davidlange6** [comment]
@ndaci - please cache the value of std::abs(eta) to avoid calculating it repeatedly. Thanks

**Comment by ndaci** [comment]
@davidlange6  - good point. I did so in both PRs (the present one, and the 80X backport). Thanks.

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
