### PR TITLE
Fix `StandaloneTrackerTopology` and providing unit tests 

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

In https://github.com/cms-sw/cmssw/pull/43020#issuecomment-1764543700 it was noticed that one of the pixel payload inspector tests was very noisy.
In https://github.com/cms-sw/cmssw/pull/43020#issuecomment-1767264420 is was elucidated that the reason can be traced back to this commit https://github.com/cms-sw/cmssw/commit/5af9d665f48ccbfff7c49a4b6243c9124b37a189, that - while supplying in `TrackerTopology` the provision to distinguish in the Phase-2 IT barrel layer 1 two sensors per module - at the same time (since the change in the meaning of the bit masks was not propagated to `StandaloneTrackerTopology`) it also created a bug in all the clients that at that point started to silently fail correctly parsing the topology from XML.  
This is fixed in commit e165f7fdb65841db88b7e379a410cd793b9884e4.
In this PR I also provide a unit test, to avoid future possible mismatches between the two mechanisms f05c6560eff86696adb378f9d2eff949285dba41, as well as some other miscellaneous improvements in the Pixel Payload Inspector suite that were useful during debugging.

#### PR validation:

Relies on the newly created unit test, `scram b runtests_CalibTrackerStandaloneTrackerTopologyTestDriver` which runs fine with this PR.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Not a backport, but should be backported down to all the releases in which there is active development.

### CODE REVIEW

**Comment by mmusich** [comment]
type bug-fix

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by perrotta** [comment]
+1
- Warning messages are not there any more in the unit test outputs

**Comment by rappoccio** [comment]
+1

**Pull request merged**
