### PR TITLE
[HGCAL] Trackster to SimTrackster associator

### PR DESCRIPTION
**Pull request by lecriste**
#### PR description:

This PR introduces an associator between TICL Tracksters and SimTracksters. Among other usages, it will be used for the final HGCAL validation based on SimTracksters in place of the current CaloParticles. No changes are expected in the output.

#### PR validation:

`runTheMatrix -l limited`

### CODE REVIEW

**Comment by srimanob** [comment]
Please test

**Comment by lecriste** [comment]
@civanch can you please review this PR?

**Comment by civanch** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

**Comment by qliphy** [comment]
+1

**Pull request merged**
