### PR TITLE
updates to Top-HLT sequence in DQMOffline (backport of #26540)

### PR DESCRIPTION
**Pull request by missirol**
#### PR description:

updates to the Top-HLT sequence in DQMOffline/Trigger/ to use the modifiers `Run2_HLTconditions_201*` (introduced in #26355), to select the correct HLT paths (and b-tagging algorithm) in different eras (Run2_2016, Run2_2017, Run2_2018).

It includes one bugfix to the plot `bjetPhi_*` of the TopMonitor plugin (differences in the comparisons are expected only for these histograms).

#### PR validation:

The code has been tested with runTheMatrix.py -l 10024.0 and by running the offline-DQM on 2017, 2018 datasets.

#### if this PR is a backport please specify the original PR:

this is a backport of #26540

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by missirol** [comment]
the only differences I could spot in the comparisons are related to the fix of the `bjetPhi_*` plots in the TopMonitor plugin (e.g. [here](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_10_6_X_2019-05-21-1100+620dea/31815/10824.0_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2018_GenSimFull+DigiFull_2018+RecoFull_2018+HARVESTFull_2018+ALCAFull_2018+NanoFull_2018/HLT_BTV_PFJet_PFJet80.html)), plus some skipped comparisons which seem unrelated to this PR (e.g. [here](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_10_6_X_2019-05-21-1100+620dea/31815/10824.0_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2018_GenSimFull+DigiFull_2018+RecoFull_2018+HARVESTFull_2018+ALCAFull_2018+NanoFull_2018/DT_EventInfo_DCSContents.html))

**Comment by jfernan2** [comment]
@missirol @sscruz This PR is removing ~1250 histograms from TOP/HLT in baseline in some of the workflows, the original PR too. Can you confirm this is expected?
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_10_6_X_2019-05-21-1100+620dea/31815/dqm-histo-comparison-summary.html

**Comment by missirol** [comment]
Hi @jfernan2 , sorry for not having mentioned this.

We expect that with this PR several histograms are removed (wrt baseline) only when running with `--era Run2_2016`; the affected histograms are related to trigger paths that were not in the 2016 HLT menu (without the PR, those plots would just be empty, at least the numerators and efficiency plots); just for reference, the change comes from [here](https://github.com/cms-sw/cmssw/pull/26861/files#diff-148c698ded5b0a43d10260cde15eb620R875)

We checked the affected workflows (136.731, 1306.0, 1330.0, 25202.0) and they all use `--era Run2_2016`, and the DQM plots affected are the ones we expect. @sscruz

**Comment by jfernan2** [comment]
+1

**Comment by missirol** [comment]
Hi, I was just wondering if there are any outstanding issues with this backport, or the review could proceed?

**Comment by fabiocos** [comment]
@missirol backports to production cycles are normally integrated after validation in master, and anyway when a build is planned

**Comment by fabiocos** [comment]
@missirol BTW I understand that this backport is needed for the validation of the UL processing, am I correct?

**Comment by fabiocos** [comment]
+1

**Pull request merged**
