### PR TITLE
Phase2-hgx341G Next step toward the V18 version of HGCal by making mixed module with passive volumes

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Next step toward the V18 version of HGCal by making mixed module with passive volumes

#### PR validation:

Use the scripts for dumping mixed layers in Geometry/HGCalCommonData/test/python 

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

New geometry dev. No change is expected from existing geometry.

**Comment by perrotta** [comment]
+1

**Pull request merged**
