### PR TITLE
Run3-gex83E Update SD class initialization in SimG4CMS/CherenkovAnalysis

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Update SD class initialization in SimG4CMS/CherenkovAnalysis

#### PR validation:

Checked with scripts in SimG4CMS/CherenkovAnalysis/test

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
