### PR TITLE
Fireworks gem 75x

### PR DESCRIPTION
**Pull request by jshlee**
Hi @dildick and @alja,

I've updated fireworks for gem and me0 here.

I've added Configuration/Geometry/python/GeometryExtended2023Muon_cff.py and Geometry/CMSCommonData/python/cmsExtendedGeometry2023MuonXML_cfi.py 
to be able to use Configuration/Geometry/python/GeometryExtended2023MuonReco_cff.py

and corrected geometry dumpers for gem and me0
I'll give a talk on this in the next validation meeting.

Cheers,
Jason.

### CODE REVIEW

**Comment by alja** [comment]
+1

**Comment by jshlee** [comment]
Hi @alja, this seems to be a clang problem.
How can this be resolved.

**Comment by alja** [comment]
@jshlee 
I'm on vacation today. Will look at this tomorrow.

**Comment by alja** [comment]
@jshlee
I don't see errors in Fireworks code. That is not the first time PR was rejected because of errors somewhere else. Please double check if your changes compile in CMSSW_7_5_X and write a comment to this PR.

**Comment by jshlee** [comment]
@alja can you get cmsbuild to please test again
I had to remerge.
It still compiles fine, except in clang.

**Comment by alja** [comment]
@jshlee I think rebuild will be automatic because you have added a change. As I remember you have to wait a couple of hours for robot to do the task... Will follow this too.

**Comment by alja** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
