### PR TITLE
Fix bug in FormulaEvaluator involving parenthesis and precedence order

### PR DESCRIPTION
**Pull request by Dr15Jones**
A sub-expression involving a parenthesis was not using the top node as the representation for the expression. That mixed with precedence order fixing resulted in part of the expression being lost.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by slava77** [comment]
Changes vary somewhat by the type of processing:
- almost no change in 2017 MC re-miniAOD
- somewhat significant changes in 2016 MC re-miniAOD

in 2016 reminiAOD ZEE wf 1325.5
all_sign1031vsorig_zee13reminiaodwf1325p5c_log10patjets_slimmedjets__pat_obj_energy
all_sign1031vsorig_zee13reminiaodwf1325p5c_log10patjets_slimmedjets__pat_obj_et
not much visible effect for pt >~20 GeV
wf1325 5_slimjets_resp_eta_20to40

Changes are a bit mixed in data 
- 136.7611 wf 2016E JetHT
all_sign1031vsorig_runjetht2016ereminiaodwf136p7611c_log10patjets_slimmedjets__pat_obj_et
- 136.8311 wf 2017F JetHT
all_sign1031vsorig_runjetht2017freminiaod136p8311c_log10patjets_slimmedjets__pat_obj_et

So, it's somewhat up and down depending on the JECs.

Anyways, perhaps more interesting illustrations were posted in #24023  e.g. http://uaf-10.t2.ucsd.edu/%7Enamin/dump/issue_24023/plot_unclipped.png

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/24049	611a792
- code change is in line with the description; there are also quite a bit of debug functionality added. The problematic cases were added to the unit tests.
- jenkins tests pass and comparisons with the baseline show changes in miniAOD variables related to jets

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Pull request merged**
