### PR TITLE
Add script to merge the JSON files produced by the FastTimerService [14.0.x]

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Add script to merge the content of multiple "resources.json" files produced by the FastTimerService, and print the result to standard output.

Usage: `mergeResourceJson.py FILE [FILE ...]`

Example:
```bash
mergeResourceJson.py step*/pid*/resources.json > resources.json
```

#### PR validation:

Tested producing 8 JSON files and merging them.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport of #44836 to 14.0.x for timing studies.

### CODE REVIEW

**Comment by fwyzard** [comment]
backport #44836

**Comment by fwyzard** [comment]
please test

Just for the signatures

**Comment by fwyzard** [comment]
@cms-sw/orp-l2 please merge this for the next 14.0.x release at your convenience.

**Comment by mmusich** [comment]
+hlt

**Comment by antoniovilela** [comment]
+1

**Comment by antoniovilela** [comment]
merge
   - added script.

**Pull request merged**
