### PR TITLE
Run3-gex176F Backport the correction to 2024 Geometry to CMSSW_14_0_X due to RPC detector (backport of #44065 and #44093)

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Backport the correction to 2024 Geometry to CMSSW_14_0_X due to RPC detector (backport of #44065 and #44093)

#### PR validation:

Tested using overlap tools

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backports of #44065 and #44093

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
+geometry

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by rappoccio** [comment]
+1

**Pull request merged**
