### PR TITLE
Fixed SimMuon warning

### PR DESCRIPTION
**Pull request by civanch**
Fix of SimMuon warning - CondDB is not needed here.

### CODE REVIEW

**Comment by civanch** [comment]
not working

**Comment by civanch** [comment]
Have been checked by @bapavlov

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
-1
what are the plans for removing the hardwired conditions?

**Comment by bapavlov** [comment]
The conditions are in the DB. Now I'm in contact with AlCaDB in order to include the conditions in the global tag.

**Comment by ianna** [comment]
@davidlange6 and @civanch - the warning is annoying and still persist in 91x. What's the plan to remove it?

**Comment by davidlange6** [comment]
the conditions get into the GT then we can remove the hardwired conditions configuration (it looks like alca just got the conditions a few days ago)

**Comment by bapavlov** [comment]
@ianna @civanch @davidlange6 
The conditions are in DB and are on the queue for the GT. The AlCa team is notified via hypernews:
https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2832.html
As soon as they include the conditions we could remove the hard coded conditions from the code.

**Comment by ianna** [comment]
@civanch and @davidlange6 - the conditions are in GT now. What's the plan for merging this PR? Thanks.

**Comment by davidlange6** [comment]
right, but 90x is obsolete. fixed in newer releases given the large time lag to get and deploy the fix.

**Pull request closed without merging**
