### PR TITLE
[TEST ONLY][Do not merge] New clang tidy checks

### PR DESCRIPTION
**Pull request by mrodozov**
#### PR description:

New clang tidy checks enabling, applied on cmssw, without test directory
The first commit is code-checks-all , the second will be the format. 
PRs it sums up:
https://github.com/cms-sw/cmssw/pull/29934
https://github.com/cms-sw/cmssw/pull/29929
https://github.com/cms-sw/cmssw/pull/29930
https://github.com/cms-sw/cmssw/pull/29926
https://github.com/cms-sw/cmssw/pull/29927
https://github.com/cms-sw/cmssw/pull/29931

### CODE REVIEW

**Comment by smuzaffar** [comment]
@mrodozov , can you please provide the PR ref for each of these checks in the description? Just having the URL for PRs which @fwyzard made should be good enough

**Comment by mrodozov** [comment]
The files sum in the separated PRs is ~850 vs 659 which is probably due to same files having overlaps.

**Comment by fwyzard** [comment]
https://github.com/cms-sw/cmssw/pull/30509 should fix the first two issues.

The third one is one I don't remember seeing before, so I'm not sure what should be done about it.

**Comment by mrodozov** [comment]
Neither DataFormats/Common/interface/Wrapper.h nor FWCore/Framework/interface/Event.h was touched by this, I wonder why is it failing if none of the existing or the new checks are applied to it :/ the code builds (at least FWCore/Framework does)

**Comment by mrodozov** [comment]
@Dr15Jones @makortel could you please advise on whats wrong here, I'm unfamiliar with that templates and can't say if there is a wrong constructor argument ?

**Comment by makortel** [comment]
The change of this PR
```diff
--- a/RecoTracker/MkFit/plugins/MkFitInputConverter.cc
+++ b/RecoTracker/MkFit/plugins/MkFitInputConverter.cc
@@ -123,7 +123,7 @@ void MkFitInputConverter::produce(edm::StreamID iID, edm::Event& iEvent, const e
   // Then import seeds
   auto mkFitSeeds = convertSeeds(iEvent.get(seedToken_), hitIndexMap, ttrhBuilder, iSetup.getData(mfToken_));
 
-  iEvent.emplace(putToken_, std::move(hitIndexMap), std::move(mkFitHits), std::move(mkFitSeeds), std::move(lnc));
+  iEvent.emplace(putToken_, std::move(hitIndexMap), std::move(mkFitHits), std::move(mkFitSeeds), lnc);
 }
 
 bool MkFitInputConverter::passCCC(const SiStripRecHit2D& hit, const DetId hitId) const {
```
is wrong because `MkFitInputWrapper` expects an rvalue
https://github.com/cms-sw/cmssw/blob/dcff25bd7e9de377c5ad64597452a7213b13af26/RecoTracker/MkFit/interface/MkFitInputWrapper.h#L20-L23

On the other hand removing the `std::move` does have point in that `mkfit::LayerNumberConverter` does not benefit from moving. I'll change the last parameter to be taken by value.

**Comment by makortel** [comment]
> On the other hand removing the `std::move` does have point in that `mkfit::LayerNumberConverter` does not benefit from moving. I'll change the last parameter to be taken by value.

Done in https://github.com/cms-sw/cmssw/pull/30530 (in a bit differently than I planned though).

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
abort

**Comment by mrodozov** [comment]
code-checks

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
code-checks

**Comment by mrodozov** [comment]
-note
clang complains for where the type of the iter var was used by name and not with auto
there are other similar changes, but for them auto was used and clang overlooked it
checking if using 'const auto&' will bring the warnings again ...
for 
HLTriggerOffline/Egamma/src/EmDQM.cc
using auto resolves a wrong type for the (have to check it)

**Comment by mrodozov** [comment]
code-checks

**Comment by mrodozov** [comment]
please test

**Pull request closed without merging**
