### PR TITLE
CondTools/L1Trigger: replace auto_ptr deprecated and removed in std=c++17

### PR DESCRIPTION
**Pull request by gartung**

### CODE REVIEW

**Comment by gartung** [comment]
@Dr15Jones please test

**Comment by Dr15Jones** [comment]
Please test

**Comment by gartung** [comment]
More input file access errors.

**Comment by thomreis** [comment]
please test

**Comment by thomreis** [comment]
+1

**Comment by ggovi** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
