### PR TITLE
Run3-Sim153E Cleanup in SimG4CMS/HGCalTestBeam against using codes directly from DD4hep

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Cleanup in SimG4CMS/HGCalTestBeam against using codes directly from DD4hep

#### PR validation:

Use the runTheMatrix test workflows

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
