### PR TITLE
New set of RelVal GT

### PR DESCRIPTION
**Pull request by diguida**
This request contains only the minimal set of global tags for compatibility.
- Added Egamma PF Cluster corrections in all scenarios (so removed the ESPrefer in `RecoParticleFlow/PFClusterProducer/python/particleFlowClusterECAL_cfi.py`);
- Updated hadron PF calibrations for Run2 MC, and new IOV appended to the HLT and re-reco GT.

### CODE REVIEW

**Comment by diguida** [comment]
@cmsbuild please test

**Comment by diguida** [comment]
Local tests are fine:

````
$ runTheMatrix.py -l limited -i all
4.22_RunCosmics2011A+RunCosmics2011A+RECOCOSD+ALCACOSD+SKIMCOSD+HARVESTDC Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Thu Feb 12 13:38:47 2015-date Thu Feb 12 13:33:32 2015; exit: 0 0 0 0 0
4.53_RunPhoton2012B+RunPhoton2012B+HLTD+RECODreHLT+HARVESTDreHLT+MINIAODDreHLT Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Thu Feb 12 13:50:58 2015-date Thu Feb 12 13:33:33 2015; exit: 0 0 0 0 0
5.1_TTbar+TTbarFS+HARVESTFS Step0-PASSED Step1-PASSED  - time date Thu Feb 12 13:37:55 2015-date Thu Feb 12 13:33:38 2015; exit: 0 0
8.0_BeamHalo+BeamHaloINPUT+DIGICOS+RECOCOS+ALCABH+HARVESTCOS Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Thu Feb 12 13:39:01 2015-date Thu Feb 12 13:33:41 2015; exit: 0 0 0 0 0
25.0_TTbar+TTbarINPUT+DIGI+RECO+HARVEST+ALCATT Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Thu Feb 12 13:52:24 2015-date Thu Feb 12 13:38:03 2015; exit: 0 0 0 0 0
135.4_ZEE_13+ZEEFS_13+HARVESTUP15FS+MINIAODMCUP15FS Step0-PASSED Step1-PASSED Step2-PASSED  - time date Thu Feb 12 13:44:34 2015-date Thu Feb 12 13:38:55 2015; exit: 0 0 0
140.53_RunHI2011+RunHI2011+RECOHID11+HARVESTDHI Step0-PASSED Step1-PASSED Step2-PASSED  - time date Thu Feb 12 13:50:35 2015-date Thu Feb 12 13:39:06 2015; exit: 0 0 0
1330.0_ZMM_13+ZMM_13INPUT+DIGIUP15+RECOUP15+HARVESTUP15+MINIAODMCUP15 Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Thu Feb 12 13:53:42 2015-date Thu Feb 12 13:44:39 2015; exit: 0 0 0 0 0
1000.0_RunMinBias2011A+RunMinBias2011A+TIER0+SKIMD+HARVESTDfst2+ALCASPLIT Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Thu Feb 12 14:00:17 2015-date Thu Feb 12 13:50:47 2015; exit: 0 0 0 0 0
1001.0_RunMinBias2011A+RunMinBias2011A+TIER0EXP+ALCAEXP+ALCAHARVD Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED  - time date Thu Feb 12 13:57:56 2015-date Thu Feb 12 13:51:07 2015; exit: 0 0 0 0
10 10 9 7 6 tests passed, 0 0 0 0 0 failed
````

**Comment by slava77** [comment]
Salvatore,
are there any changes in GT other than these cluster calibrations?
This is in anticipation of the comparisons from jenkins (I'd expect them soon, now that the jobs have run)

**Comment by diguida** [comment]
@slava77 that's correct.
This first set of GT is compatibility only, plus one fix to the startup scenario where the HLT JEC are changed to be the ones for 50 ns:
https://cms-conddb-dev.cern.ch/browser/#diff/Prod/gts/MCRUN2_74_V2/MCRUN2_74_V4

**Comment by diguida** [comment]
@slava77 I will document all of this in the twiki page, so for the moment I hope the new GT diff feature is OK

**Comment by slava77** [comment]
.. I'll run local tests as well, just in case

**Comment by diguida** [comment]
@slava77 In the meantime I have also tested the GT with the signed-off conditions for the 74X Run2 MC DIGI-RECO. We were thinking of including them in the pre7. Now, for the integration, let me know if you want me to add a further commit here (so you can have a look to the Run2 wf here) or you prefer a separate PR (but we should wait this to be merged). You will see changes also in the other keys, but the new GT there do not contain the 3x3 APE records.

**Comment by diguida** [comment]
I cannot see the comparisons running with jenkins, the folder does not exist:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_7_4_X_2015-02-12-0200+7692/6029/

**Comment by davidlange6** [comment]
@cmsbuild, please test

(indeed, lets try again)

**Comment by diguida** [comment]
@slava77 @davidlange6 
In the meantime I do another PR with the Run2 MC GT for DIGI-RECO in (so we do not interfere with the tests for this PR).

**Comment by slava77** [comment]
Hi Salvatore, what is the PR number? (or is it still cooking)

**Comment by diguida** [comment]
@slava77 "good" news: one tag is still in the new boost, so the tests fail.
I am migrating it.

**Comment by diguida** [comment]
One day I will try to reply to a question: why do developers need DropBox advanced functionalities for MC tags?????

**Comment by davidlange6** [comment]
Because they can�.

**Comment by diguida** [comment]
@davidlange6 right, only Tier0 PCL should, but then all could... :-(

**Comment by diguida** [comment]
@slava77 the re-migration is done.
Please look at #7707

**Comment by slava77** [comment]
There are pretty large changes in PF neutral hadrons only in run2 mc
Is this from this change in GT:
PFCalibrationRcd	-	PFCalibration_v0_mc	PFCalibration_v1_mc

all_sign517vsorig_qcd13tevpt3ts3t5wf1313p0c_log10recopfcandidates_particleflow__reco_obj_pt50

there are no changes in Run1 MC or data; I'd naively expect all to change in sync.
I will need some confirmation from Michalis that this is an intended change
@bachtis

**Comment by slava77** [comment]
the plot was from the run2 dijet 3 to 3.5TeV MC (no pileup), there are no changes in the upstream quantities, so it's pretty likely all in the PFProducer

**Comment by diguida** [comment]
@slava77 this is consistent with the changes in the GT concerning PF hadron calibrations:
* No changes for Run1 MC
* for the Run2 MC scenarios we introduced the new PF hadron calibrations recently derived by performing the computation on MC samples.
* for Run1/Run2 data+hlt, we append the new calibration with a new IOV driven by the dropbox. Given that the current method does not allow to perform a good quality calibration on data, the new MC payload should be consumed by Run2 data workflows. At the same time, you do not want to use the Run2 calibration on Run1 data. The IOV mechanism guarantees the reproducibility: for Run1 data, the old calibration is loaded, while future Run2 events will consume the new one. This also keeps consistency with what has been done during Run1, where the same MC-based calibration has been used on data.

**Comment by diguida** [comment]
Of course, I let @mmarionncern (who tested and validated the corrections) comment further on this.

**Comment by slava77** [comment]
Salvatore,
I don't quite understand your explanation.
The pf hadron calibration change in this case is a property of the reconstruction, not of the "era" the data or MC was made: if all of them are reconstructed with the same algorithm (they are), they all have to have the same calibration.

**Comment by slava77** [comment]
also, the description of the PR is misleading in this case: nothing was said about the PF hadron calibration in the GT. 
Maybe the details are on the twiki?

**Comment by slava77** [comment]
Looking at the same dijet 3 TeV, the jet absolute response is down by about 10-12%, but the reco/gen is about the same height ==> the resolution is actually better.

I guess this is something that can be handled by the jet corrections for jet analysis; but it seems to be pretty bad at GED/particle level.

wf1313_ak4pf_response
wf1313_ak4pf_responsehist

**Comment by slava77** [comment]
hold
for comments from PF/JME for the hadron response
- is it OK to have the absolute response of pf neutral hadrons so low
- is it OK to have the corrections applied only in Run2 MC (while the same reco is running for run 1 MC, which makes the performance inconsistent for run 1 tests or comparisons)

for https://github.com/cms-sw/cmssw/pull/7692	 1e07cdf
tested in CMSSW_7_4_X_2015-02-12-0200 /test area sign517/

**Comment by slava77** [comment]
Uhm, if the response histogram shifts to the left and the height stays the same,  it's actually corresponding to resolution getting worse.

**Comment by diguida** [comment]
@slava77 I have updated the PR description to make it more clear (sorry, I wrote it in a hurry). The twiki is being updated, too.

**Comment by diguida** [comment]
@slava77 concerning https://github.com/cms-sw/cmssw/pull/7692#issuecomment-74166362
As far as calibrations are concerned, we have to consider both the producers and the consumers. In your case, the change of the calibration is needed not because there is a new and improved product, but because we have to follow the change of the client code (in this case, hadron reconstruction algorithm). If so, given that, as you say, the reconstruction is always the same for both Run1 and Run2, I would have queued this new calibration in all scenarios. However, this would also mean that the Run1 calibration consumed in the Run1 MC workflows is not anymore consistent with the reconstruction algorithm, so I would have expected a degradation of the Run1 physics performance.
On the other side, @mmarionncern asked this calibration to be queued only for Run2 MC and data, as this was derived on Run2 MC samples.
Please let me know if I am still missing something: I admit not to be an expert on this.

**Comment by diguida** [comment]
@slava77 Concerning https://github.com/cms-sw/cmssw/pull/7692#issuecomment-74173343
I can assume this can be due to the fact that the Jet corrections have not yet been re-tuned on the new calibration: the current ones have been produced based on PHYS14 samples.

**Comment by slava77** [comment]
Jet corrections will put the central value back. It will be a constant
scale factor, they will not improve resolution. The high et jet sample here
consists of essentially just eta around 0.

The goal of pf/ ged is to deliver reasonably well calibrated particles.
This is failing here, with a 15%  loss of average response;  it's much
worse per category ... but maybe it's just what happens at 3 TeV ...

**Comment by slava77** [comment]
I don't quite understand the explanation about the consumers. A consumer
asking for a mcrun174_vX tag is supposed to be expecting a payload
corresponding to 74x release reconstruction;  if it was a 72x or 70x
consumer,  it would have to ask for mcrun1_70x_vX or something.

We did this for hcal, didn't we?

**Comment by diguida** [comment]
@slava77 That's why we have Global Tag distinguished per scenario *and* release: in this case, all the 74X Global Tags must provide payloads consistent with the reconstruction, even if the payloads themselves can be different (think of the different misalignment for startup/asymptotic).
I do not remember on top of my head what we did for HCal :-(

**Comment by mmarionncern** [comment]
The PF calibrations are dependent of the HCAL reconstruction used. For runI, we had the Hcal method 0 reconstruction, and old PF calibration were derived with that method. Of course if the new HCAL reco is used for runI starting from now, then the runII calibration will be more appropriate, but I did not understand this would be the case.
 
If run2 calibration are used with runI data/MC, then you get an equivalent inconsistency as using the runI calibration with the runII conditions.


@slava77 , to anwer to your questions :
    is it OK to have the absolute response of pf neutral hadrons so low

The calibration is performed with hadrons with an energy >1 GeV. Looking at your plot the low response is mostly for hadrons at very low energy when an extrapolation is made. 


For jets at 3TeV : the drop of hadron response has nothing to do with the drop of jet response at high pT, as low energy hadrons are the only one impacted. However, the calibration has been performed with a hadron sample with an energy < 200 GeV. We don't have yet higher energy hadron samples to check that the extrapolation is performing as expected. As the runII HCAL reconstruction does not give a saturation regime (or at least not at much higher energy), we may be sub optimal at very high energy. Looking at the hadron energy distribution, there is a drop for energies above 1 TeV. This could be consistent with a lack of closure of the calibration at really high energy, but for the moment I don't have the hadron sample to check that.

**Comment by slava77** [comment]
@mmarionncern 
in each release (from around 6X when post-LS1 came about) we run essentially the same reconstruction (and digitization) for all pp MC and data.
(the only changes made are for actually changed detectors: HO SiPMs is the only thing different for calorimeters; the ECAL has differences for 25ns vs 50 ns, but that's not run1-vs-run2 specific).

@diguida 
I think this so far confirms that for Run1 MC and data we need to consistently use the same PFCalibration payloads, since they match the property of reconstruction (not so much of the center of mass energy or time when SIM or GEN was made or implied origin of the RAW input for data).

**Comment by slava77** [comment]
on the subject of reduced response: I understand that "it is what it is now, and lower ET is supposed to be OK"
I ran the 13 TeV flat-pt dijet, will check the plots shortly.

**Comment by slava77** [comment]
-1

the target is what's in  #7726.
All PF-related payload discussion applies to #7726.

I will use this thread to post a few more plots though, specific to just this incremental step

**Comment by diguida** [comment]
@slava77 I agree with you. In summary:
* the digitisation and reconstruction steps in CMSSW are *always* the same (with a few exceptions on calorimeters), regardless of the data taking era or the simulation/data;
* The PF hadron calibration has been computed on top of 74X HCal reconstruction, even if only Run2 MC samples have been used;
* The new calibration should be applied to all the scenarios currently supported.
[ACTION] I am preparing a new set of GT for Run1 MC, Run1/2 data.

**Comment by slava77** [comment]
From 1338: flat-pt dijet with post-ls2 MC settings (no PU)

The lower pt jets are showing slightly better resolution

wf1338_ak4pf_response_200to600

the response is ok both in barrel and endcap up to just about 200 GeV; above that the barrel side drops, while the endcap part remains at about the same central value.
This is consistent with the incomplete coverage of the calibration samples.

wf1338_ak4pf_response_corr_logpt_b
wf1338_ak4pf_response_corr_logpt_e

In the barrel, 
the reconstructed jet pt (before correction) is actually fairly flat now
wf1338_ak4pf_response_logpt_b
==> the central value to be fixed by jet corrections.

while in the endcap it's about similarly increasing with gen pt.
wf1338_ak4pf_response_reco_logpt_e

**Comment by slava77** [comment]
ok, so, it sounds like one remaining issue of making an update to the GT to also include the run1 PF calibrations is on the way and the currently dangling PRs can move ahead (assuming the updated GT autocond files will not introduce a merge conflict issue).

**Comment by diguida** [comment]
-1
Superseded by #7726 (where a new set of GT for Run1 must be added).

**Pull request closed without merging**
