### PR TITLE
DQM for VBF H to bb triggers

### PR DESCRIPTION
**Pull request by Michael-Krohn**
Added DQM modules for 4 single btag VBF triggers and 4 double btag VBF triggers

### CODE REVIEW

**Comment by mtosi** [comment]
@cmsbuild, please test

**Comment by Michael-Krohn** [comment]
@mtosi The #bins are 1953 for each of the single btag triggers and 2445 for each of the double btag triggers. This gives a total of 17,592 bins

**Comment by mtosi** [comment]
@Michael-Krohn I think you need to rebase

**Comment by mtosi** [comment]
@cmsbuild, please test

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
