### PR TITLE
[10_6_X] Use ONNXRuntime for ParticleNet and update the training for UL

### PR DESCRIPTION
**Pull request by hqucms**
#### PR description:

Backport of https://github.com/cms-sw/cmssw/pull/30599 and https://github.com/cms-sw/cmssw/pull/31036.

This PR updates the ParticleNet tagger to the new training [V01] developed for the UL re-MiniAOD. The training is derived on UL17+UL18 samples and using Puppi tune V14. The new training improves the performance for UL samples and the new Puppi tune. More information can be found in the JME talks [[1](https://indico.cern.ch/event/939494/contributions/3947427/attachments/2081304/3495876/20.07.28_JMAR_ParticleNet_for_UL.pdf), [2](https://indico.cern.ch/event/942994/contributions/3966501/attachments/2083817/3500446/ParticleNET_PUPPItunechecks.pdf)] and the BTV [talk](https://indico.cern.ch/event/916807/contributions/3968324/attachments/2084999/3502626/20.08.05_ParticleNet_BTV.pdf).

Requires: 
 - https://github.com/cms-data/RecoBTag-Combined/pull/34
 - https://github.com/cms-sw/cmsdist/pull/6139

#### PR validation:

The CMSSW implementation is compared to the training framework and consistent results are obtained.

### CODE REVIEW

**Comment by slava77** [comment]
test parameters:
- pull_requests = cms-data/RecoBTag-Combined#34,cms-sw/cmsdist#6139



> Requires:
> 
>     * [cms-data/RecoBTag-Combined#34](https://github.com/cms-data/RecoBTag-Combined/pull/34)
> 
>     * [cms-sw/cmsdist#6139](https://github.com/cms-sw/cmsdist/pull/6139)

apparently it was supposed to be cms-sw/cmsdist#6145 , which is already merged

**Comment by slava77** [comment]
test parameters:
- pull_request = cms-sw/cmsdist#6159

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/31037	dc54bdf 
- the combined backport of #31036 and #30599 is correct (the code differences are the same)
- jenkins tests pass (the ParticleNet tagger is not in the standard workflows at least until #31072 is merged)
- the external cms-sw/cmsdist#6159 was merged, apparently to appear in the -2300 IB

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
> Reco comparison results: 74 differences found in the comparisons

as expected after #31072 , the UL remini backport now shows differences in the UL remini workflow 136.88811 as expected; the differences are in slimmedJetsAK8 jet tag discriminants.

**Comment by slava77** [comment]
backport of #30599
backport of #31036

**Comment by qliphy** [comment]
+1

**Comment by santocch** [comment]
+1

**Pull request merged**
