### PR TITLE
Changed to use track only isolation for PFmuon

### PR DESCRIPTION
**Pull request by gbyu**
This work is to improve the PFmuon quality in coming run2 data taking in which a huge track multiplicity is expected. Because of the good track granularity, many fake muons can be reconstructed as a good muon. In order to reduce the fake muon, a study is performed to use track only isolation in the PF muon algorithm.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by bachtis** [comment]
yes. I hope @slava77 can accept it tomorrow

**Comment by slava77** [comment]
Can "tomorrow morning" be 7AM CERN time?

**Comment by bachtis** [comment]
I am not making the change but I expected that (deadline = Feb 4 ) == (deadline ==midnight of Feb 4 towards Feb 5)

**Comment by slava77** [comment]
The deadline is today

https://twiki.cern.ch/twiki/bin/viewauth/CMS/CMSSW_7_4_0



On 2/3/15 11:13 AM, Michalis Bachtis wrote:
> I am not making the change but I expected that (deadline = Feb 4 ) ==
> (deadline ==midnight of Feb 4 towards Feb 5)
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cms-sw/cmssw/pull/7529#issuecomment-72691684>.
> 

-- 
***********************************************************************
 Vyacheslav (Slava) Krutelyov
 TAMU: Physics Dept Texas A&M MS4242, College Station, TX 77843-4242
 CERN: 42-R-027
 AIM/Skype: siava16              googleTalk: slava77@gmail.com
 (630) 291-5128  Cell (US)       +41 76 275 7116 Cell (CERN)

-----------------------------------------------------------------------

**Comment by bachtis** [comment]
OK then if there is no update by midnight , this is the PR to go in 74X

**Comment by bachtis** [comment]
Hi, we have some indications that this change is spoiling the performance. @battibass  @trocino I am not however sure the plot we are looking is correct.  We can leave this PR to go forward while we are doing the checks and then just decide to not merge it .

**Comment by slava77** [comment]
Is the current PR state good enough or will you be updating the configuration?
If an update is desired, please do so within 1-2 hours, or clarify when.

**Comment by bachtis** [comment]
There will be no change in configuration. But we worried that this change is bad for physics. So in parallel
 with your tests we are looking. Maybe we decide to not merge it at the end

**Comment by slava77** [comment]
ok, thanks for the clarification.

**Comment by slava77** [comment]
I've started reco tests

**Comment by bachtis** [comment]
Here is my latest validation. It seems we see big improvement in MET tails . See attached MET-gen MET vs gen MET and sigma MET vs gen MET. Red is old, points are new
met1
metres

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/7529	7a4b400

technical performance OK (same CPU and memory and size on disk).

Changes in PF and downstream are as expected: there is an increase in the number of PF muon candidates; MET doesn't seem to be affected on the limited stats used in tests; no appropriate signal samples were checked (Z+PU) but these should show an improvement
- about 50% increase in 3 TeV dijet sample (these are mostly fakes though)
- about 5% more PF candidate muons (pt< 10 GeV) in ttbar PU35@25 ns (these may be more b->mu here)

**Pull request merged**
