### PR TITLE
[backport of #36259] Calo-L1 unpacker modified to read 5BX payload format

### PR DESCRIPTION
**Pull request by hftsoi**
#### PR description:

Backport of #36259 (merged to 12_3_X) to 12_2_X. We need this for coming MWGR where online DQM will be using 12_2_1.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by cecilecaillol** [comment]
please test

**Comment by cecilecaillol** [comment]
+l1

**Comment by qliphy** [comment]
@hftsoi  Please sync with the codes in master. 
For example
https://github.com/cms-sw/cmssw/pull/36259/files#r760866849
and several other places

**Comment by perrotta** [comment]
> Thanks for reminder, since master does not have the cleaning incorporated, we will make a separate PR for that to master next time.

Then it is probably time to integrate the cleaning in the master, as you anticipated in https://github.com/cms-sw/cmssw/pull/36259#issuecomment-986206576
No need to backport it afterwards, though

**Pull request merged**
