### PR TITLE
Fix HPTDC timing PCL

### PR DESCRIPTION
**Pull request by ChrisMisan**
#### PR description:
PR aims to fix timing PCL. Current Harvester is unable to receive any data from the workers.
Changes:
-relative paths were changed to absolute
-Incorrect histogram type was corrected
-Incorrect EdmToMeConverter configuration was fixed
#### PR validation:
Relval 1041

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

no

### CODE REVIEW

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
type bug-fix

**Comment by ChrisMisan** [comment]
Sorry, @tvami can you restart the tests after the code-checks?

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
+alca
 * https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-e2cf7a/22446/runTheMatrix-results/1041.0_RunExpressPhy2017F+RunExpressPhy2017F+TIER0EXPPPSCAL+ALCASPLITPPSCAL+ALCAHARVDPPSCAL/DQM_V0001_R000305064__Express__PCLTest__ALCAPROMPT.root looks ok
 * diffs in MsgLogger only

**Comment by tvami** [comment]
urgent
 * @cms-sw/orp-l2 this came after the ORP meeting today, but in principle we need this together with https://github.com/cms-sw/cmssw/pull/36273
 * the code change are simple bugfixes

**Comment by perrotta** [comment]
+1
- Fixing bugs

**Pull request merged**
