### PR TITLE
L1REPACK cleanup in CustomConfig (92X)

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
L1REPACK cleanup in CustomConfig (92X)

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
backport of #19814

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by Martin-Grunewald** [comment]
@davidlange6 
Please integrate for today's 92X release.
Thanks!

**Comment by davidlange6** [comment]
+1

**Pull request merged**
