### PR TITLE
Run3-TB64 Make some simple changes to the classes in SimG4CMS/HcalTestBeam

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Make some simple changes to the classes in SimG4CMS/HcalTestBeam

#### PR validation:

Use test workflows in SimG4CMS/HcalTestBeam/test area

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

because it is tests I would agree to have both Verbatim and #ifdef, in other places I am not sure.

**Comment by perrotta** [comment]
+1
- Simple code changes that do not affect the final outputs

**Pull request merged**
