### PR TITLE
Razor hlt 0t dqm 74x

### PR DESCRIPTION
**Pull request by jmduarte**
Razor HLT DQM changes for 0T menu for 74X, backport of PR #11178

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1

**Comment by jmduarte** [comment]
Hello,

The 76x pull request #11178 has been merged. Will this one and the 75x one #11179 be considered/approved at Tuesday's ORP meeting? This is required for the razor 0T paths to be added to the 0T menu.

Thanks,

Javier

**Comment by davidlange6** [comment]
+1

**Pull request merged**
