### PR TITLE
Modernize exception raising and catching

### PR DESCRIPTION
**Pull request by ericvaandering**
Combination of what was requested in #12019 and #11964 .

The preferred form of both how one raises exceptions and catches them with `except` has changed in python 2.6 and python 3 will not take the old forms.

These changes were all done with futurize, an automated tool.

See See https://www.python.org/dev/peps/pep-3109/ and  https://www.python.org/dev/peps/pep-3110/#compatibility for details

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by Dr15Jones** [comment]
The errors are not related to this pull request and are in the IB.

**Comment by slava77** [comment]
@cmsbuild please test
to get clean comparisons

**Comment by Martin-Grunewald** [comment]
+1

**Comment by mommsen** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by slava77** [comment]
-1
there are conflicts here, need to be resolved

**Comment by ericvaandering** [comment]
Thanks. When some of the others have gone in, I will redo this one. It's probably the biggest one.

**Comment by davidlange6** [comment]
@ericvaandering - I think I just caught up with all of the other requests - so you may try rebasing this (maybe easier after the next IB)

**Comment by ericvaandering** [comment]
Easier just to close this and make a new one based off of current 8_0_X branch.

**Pull request closed without merging**
