### PR TITLE
Let an InputTag use the special value `@currentProcess` to mean the current process name

### PR DESCRIPTION
**Pull request by fwyzard**
This is more reliable than using an empty process name, which indicated an input that can be read from the latest available process.

`@currentProcess` was picked for simmetry with `@skipCurrentProcess`.

### CODE REVIEW

**Comment by fwyzard** [comment]
@cmsbuild please test

**Comment by Dr15Jones** [comment]
This won't work with `fillDescriptions` nor with `ParameterSet::getUntracked` if they are injecting the default value.

**Comment by fwyzard** [comment]
@Dr15Jones I see your point. I based this on your comment last year

> In principal, it would be possible to add such a flag and do it fully within Python. The trick would be when the InputTag is being 'serialized' to its C++ form, if we see that special tag we would lookup the present process name and replace the special tag with the correct name. My only concern with such an implementation would be if someone tried to use the same special tag in C++ it wouldn't work.

If you have a better proposal I'm happy to hear it (and happier if the framework group can implement it!).

**Comment by davidlange6** [comment]
please test

**Comment by Dr15Jones** [comment]
Hold
David Dagenhart is looking into providing a fully consistent way of implementing this feature.

**Comment by fwyzard** [comment]
replaced by #19491

**Pull request closed without merging**
