### PR TITLE
add a unit Test for `OnlineBeamMonitor`

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

Title says it all, prompted by PR https://github.com/cms-sw/cmssw/pull/40716.

#### PR validation:

Run the unit tests: `scram b runtests`
They are currently failing because of the issue detailed at https://github.com/cms-sw/cmssw/issues/39948, but one #40716 is integrated it should solve the issue. 

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

N/A

### CODE REVIEW

**Comment by mmusich** [comment]
please test
  *expected to fail,  just to show it is able to capture the issue

**Comment by francescobrivio** [comment]
@mmusich should we trigger tests here given in #40716 it's working fine?

**Comment by tvami** [comment]
> @mmusich should we trigger tests here given in #40716 it's working fine?

I think we can just sign this based on https://github.com/cms-sw/cmssw/pull/40716

**Comment by mmusich** [comment]
> should we trigger tests here given in https://github.com/cms-sw/cmssw/pull/40716 it's working fine?

actually either you test it together with #40716 or only after that one is merged and an IB with it is available -- otherwise it is expected to fail :sweat:

**Comment by francescobrivio** [comment]
+1

 - for reference - see https://github.com/cms-sw/cmssw/pull/40727#issuecomment-1424179968

**Comment by francescobrivio** [comment]
@cmsbuild please test with #40716 

 - just to have clean tests

**Comment by perrotta** [comment]
> relval timeout is unrelated. Now that #40716 is merged this can be merged as well.

@emanueleusai do you have any objection?

**Comment by emanueleusai** [comment]
no objections

**Comment by emanueleusai** [comment]
+1

**Comment by perrotta** [comment]
+1
- This PR simply adds a unit test, letting all workflows untouched: therefore it can be merged in 13_0_X before switching the master to 13_1_X, to make it already available also in 13_0_X

**Comment by perrotta** [comment]
merge

**Pull request merged**
