### PR TITLE
Migration of HLT to CMSSW_10 code base

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
Migration of HLT to CMSSW_10 code base
Based on CMSSW_10_0_0_pre2

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
@smuzaffar 
Hi - jenkins/github seems stuck, can you please have a look?

**Comment by smuzaffar** [comment]
@Martin-Grunewald , sorry about that. There was a typo in cms-bot code which is fixed now.

**Comment by Martin-Grunewald** [comment]
@smuzaffar 
Thanks!

**Comment by Martin-Grunewald** [comment]
+1

**Comment by davidlange6** [comment]
hi @Martin-Grunewald @fabozzi - whats the plan for moving the relvals to this menu?

**Comment by Martin-Grunewald** [comment]
It is not yet a new menu, but just the "old 2017" menus migrated to work directly with CMSSW_10 without under-the-hood customisation.
But indeed, in the long run (NOT in this PR) we'd like to (i) move @relval2017 to the HLT Fake2 menu, (ii) remove the frozen 2017 menus when we have frozen 2018 menus and use them via @relval2018.

**Comment by davidlange6** [comment]
> On Dec 12, 2017, at 12:07 PM, Martin Grunewald <notifications@github.com> wrote:
> 
> It is not yet a new menu, but just the "old 2017" menus migrated to work directly with CMSSW_10 without under-the-hood customisation.
> But indeed, in the long run (NOT in this PR) we'd like to (i) move @relval2017 to the HLT Fake2 menu, (ii) remove the frozen 2017 menus when we have frozen 2018 menus and use them via @relval2018.
> 

Right - rather there a new key that should get propagated to the 2018 relvals.. wondering about the plan for that? Will there be a PR this week?

**Comment by fabozzi** [comment]
@Martin-Grunewald 
Currently 2018 relvals are using HLT:@relval2017. Is it OK to validate developments in the HLT menu for 2018? Otherwise, I agree to move to HLT:@relval2018 (in this PR or in a new one right after...)

**Comment by Martin-Grunewald** [comment]
@fabozi 
Yes!
This PR leaves HLT:@relval2017 unchanged at 2e34_v40.
This PR ADDs a new key @relval2018 which points to "GRun" ie the development menu.
So for current relvals/workflows everything is unchanged (@relval2018 wasn't available so can not be in use)
I suggest to make a future PR to switch 2018 relvals to use @relval2018.

**Comment by fabozzi** [comment]
@Martin-Grunewald 
OK! I can make the switch as soon as this gets merged

**Comment by davidlange6** [comment]
+1

**Pull request merged**
