### PR TITLE
GEM unpacker FED numbering range bug fix

### PR DESCRIPTION
**Pull request by hyunyong**
Backporting of #24406 for online DQM.

@threus @jshlee

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by perrotta** [comment]
+1
- Same as #24406, merged in master
- Rather trivial and logical fix to a wrong end-of-range in a loop over FED data
- Jenkins tests pass

**Comment by perrotta** [comment]
backport of #24406

**Comment by fabiocos** [comment]
+1

**Pull request merged**
