### PR TITLE
Add put interface using EDPutToken

### PR DESCRIPTION
**Pull request by Dr15Jones**
As a preliminary to improving the performance of the 'put' system, we introduce the use of the EDPutToken.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by davidlange6** [comment]
please test
(are these reco differences real?)

**Comment by Dr15Jones** [comment]
@davidlange6 I do not see any reasonable way this change could cause a difference for reco. Non of the code added changes how any of our present code works. It could shift things in memory a bit, but we hope our results are not dependent upon exact memory addresses used (although anyone sorting by pointer addresses might see a difference).

**Comment by Dr15Jones** [comment]
@davidlange6 @slava77 do either of you know how to determine what the comparison system thought was different?

**Comment by slava77** [comment]
Follow the links for "Comparison is ready" -> "See Comparison Results" -> "validateJR" -> "logRootQA.log"
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_9_4_X_2017-09-19-1100+20595/22620/validateJR/logRootQA.log

JR results differ 9 all_OldVSNew_TTbar14TeV2023D17wf20034p0
step up and look in this directory:
changes are in outputs of hgcalLayerClusters.

HOWEVER, before worrying much about this, go to the summary of the test made
https://github.com/cms-sw/cmssw/pull/20595#issuecomment-330880592
to see that the PR was ahead of any available IBs when submitted.
It's nice to be pedantic about being in sync with the head of master, but the cost of it is inability to test the change until a new IB ahead of that PR appears.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
