### PR TITLE
75X hlt25ns round5 plus updated frozenv4

### PR DESCRIPTION
**Pull request by perrotta**
This pull request is based on #11333, and it simply adds to it the update of the v4 25 frozen HLT menu from V2 to V3 (last commit in this PR). Since that frozen menu is the one which has to be used for the 7.5.3+ release validation campaign and/or MC production, we will update it in the CMSSW dumps only if this pull request can be merged before those productions start (and in such a way they can more conveniently pick the updated HLT menu). If those productions are already started, we will close this ticket.
Based on CMSSW_7_5_3

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
