### PR TITLE
Update the PbPb skims for 2024 data taking

### PR DESCRIPTION
**Pull request by flodamas**
#### PR description:

Update of the configuration of the PbPb skims in view of the 2024 HI run. The `ZMM` skim is replaced by the `ZMu` skimming code to avoid duplicates such that a unique skimmed dataset can be used for both Z boson physics analyses and muon tag-and-probe.

#### PR validation:

Unit tests passed successfully.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

To be backported to 14_1_X for the HI run.

### CODE REVIEW

**Comment by mandrenguyen** [comment]
please test

**Comment by youyingli** [comment]
Hi, I would like to make sure if the update is also available to ReReco 2023 Heavy ion data even in the future.

**Comment by mandrenguyen** [comment]
> Hi, I would like to make sure if the update is also available to ReReco 2023 Heavy ion data even in the future.

Hi @youyingli I'm not sure I understand the comment.  These are prompt skims, we would not run them in a reprocessing.

**Comment by youyingli** [comment]
> > Hi, I would like to make sure if the update is also available to ReReco 2023 Heavy ion data even in the future.
> 
> Hi @youyingli I'm not sure I understand the comment. These are prompt skims, we would not run them in a reprocessing.

OK, thanks. Just make sure if these skims will also join 2023 Heavy ion data reprocessing in the future. Now I understand. 

@cms-sw/pdmv-l2, could you please sign it?

**Comment by mandrenguyen** [comment]
please test

**Comment by mandrenguyen** [comment]
ignore tests-rejected with ib-failure|

**Comment by mandrenguyen** [comment]
ignore tests-rejected with ib-failure

**Comment by mandrenguyen** [comment]
urgent
@cms-sw/pdmv-l2 We will need a release with the prompt skims shortly for PbPb data taking.

**Comment by mandrenguyen** [comment]
[flodamas](https://github.com/flodamas) as we anticipated this one is in conflict after we merged the other two skim PRs.  Please resolve it.

**Comment by AdrianoDee** [comment]
+pdmv

**Comment by AdrianoDee** [comment]
(signed anyway, will sign again after the conflicts are solved)

**Comment by mandrenguyen** [comment]
please test

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
