### PR TITLE
Disabled PCA inputs for deepTau v2 (backport to 10_2_X)

### PR DESCRIPTION
**Pull request by swozniewski**
#### PR description:

Problems have been detected with dxy_PCA input variables to DeepTauID which are inconsistent between data and MC. This PR sets input values to 0 and disables the variables this way.
Issue and fix were discussed in https://indico.cern.ch/event/842796/contributions/3541592/attachments/1897386/3130770/2019-08-26_DeepTau_ID_2017v2_DY_MC_vs_Embedded_and_bug_in_definition_of_PCA_variables.pdf (see slide 7 in particular)

Backport to 10_2_X for legacy analyses intended.

#### PR validation:

compiles

#### if this PR is a backport please specify the original PR:

#27878

### CODE REVIEW

**Comment by mbluj** [comment]
Disabling of usage of dxy_PCA coordinates controlled with a parameter, and new version with the disabling added to the tauID python tool as in PR to master, but deepTauID is not included to any official workflow (as in production 10_2_X releases).

**Comment by perrotta** [comment]
@cmsbuild please test

**Comment by perrotta** [comment]
+1
- "deepTau2017v2p1" id made available for legacy analyses, but not included in any official workflow
- Jenkins tests pass and show no differences, as they should

**Comment by perrotta** [comment]
backport of #27878
(only partial)

**Comment by fabiocos** [comment]
+1

**Pull request merged**
