### PR TITLE
Fix for threadsafety of L1T Phase2 DQM

### PR DESCRIPTION
**Pull request by dsrankin**
#### PR description:

This PR fixes the thread-safety issue noted in #35979 and includes some minor cleanup.

#### PR validation:

Tested locally with `runTheMatrix.py -l 23234.103 --job-reports -t 4 --ibeos` (now runs successfully).

### CODE REVIEW

**Comment by qliphy** [comment]
type bugfix

**Comment by qliphy** [comment]
enable threading

**Comment by qliphy** [comment]
test parameters:

- workflow=23234.103

**Comment by qliphy** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by qliphy** [comment]
@cms-sw/l1-l2   Do you have any comment?  This PR is needed to fix IB issues.

**Comment by qliphy** [comment]
merge

**Comment by qliphy** [comment]
@cms-sw/l1-l2  Merge this first to fix the IB issue. Let;s know if you have any concern.

**Comment by Dr15Jones** [comment]
It looks like this was insufficient to solve the problem as the IBs including this change still show the problem
```
----- Begin Fatal Exception 08-Nov-2021 15:04:55 CET-----------------------
An exception of category 'FatalRootError' occurred while
   [0] Processing global end Run run: 1
   [1] Calling method for module L1TPhase2CorrelatorOffline/'l1tPhase2CorrelatorOfflineDQM'
   Additional Info:
      [a] Fatal Root Error: @SUB=TH1D::ComputeIntegral
Integral = zero

----- End Fatal Exception -------------------------------------------------
```

**Comment by jfernan2** [comment]
@drankincms  can you provide another better fix? Thanks

**Comment by drankincms** [comment]
@Dr15Jones @jfernan2 Is it the same workflow that's producing the error? Is there a way for me to reproduce this locally?

**Comment by Dr15Jones** [comment]
@drankincms thread race conditions can be extremely difficult to reproduce locally.

**Comment by drankincms** [comment]
Ok, this should hopefully be fixed for real this time, I removed all the calls to `QuantilesX()`.

**Pull request merged**
