### PR TITLE
Run2-hcx163 Backport PR # 21033

### PR DESCRIPTION
**Pull request by bsunanda**

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by ianna** [comment]
+1

**Comment by davidlange6** [comment]
please test

**Comment by fabiocos** [comment]
@bsunanda is this PR needed in the scope of 9_4_X? If not as I guess better to just close it.

**Comment by bsunanda** [comment]
@fabiocos I don't know. Some of the accesses to getPosition for Hcal geometry were wrong and this was a fix to that. I have no idea what is the scope of 9_4

**Comment by bsunanda** [comment]
No need for backporting

**Pull request closed without merging**
