### PR TITLE
Fix Frontier connection string in online DQM

### PR DESCRIPTION
**Pull request by diguida**
Use the local squid cache instead of querying directly the frontier servlets.

### CODE REVIEW

**Comment by diguida** [comment]
Same changes in 74X #8264 75X #8265

**Comment by deguio** [comment]
+1
to be tested on the playback.
@danduggan @batinkov

**Comment by danduggan** [comment]
-1
Salvatore, this has to be put on top of 733 in our online cluster. can you rebase it on top of that?

**Comment by danduggan** [comment]
Please close this, it's superseded by #8271.

**Comment by diguida** [comment]
@danduggan I made it on top of the latest IB in 73X.
Rebasing done.

**Comment by diguida** [comment]
Ah, now I see that you did it

**Comment by danduggan** [comment]
@diguida, thanks for closing and sorry for the overlap, just wanted to get everything setup for the weekend.

**Comment by diguida** [comment]
@danduggan 
You were faster than me ;-)
Note to self: start from the online DQM release

**Pull request closed without merging**
