### PR TITLE
Remove Duplicate Materials

### PR DESCRIPTION
**Pull request by ianna**
* Use identical materials from trackermaterial namespace

### CODE REVIEW

**Comment by ianna** [comment]
@veszpv - FYI

**Comment by ianna** [comment]
please test

**Comment by civanch** [comment]
@ianna , I confirm that Geant4 warnings are fixed

**Comment by ianna** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
