### PR TITLE
Deprecating Phase2 Tracker T1 , Replacing it  by T3 in the corresponding scenarios

### PR DESCRIPTION
**Pull request by boudoul**
Greetings, this pull Request is removing the phase2 Tracker T1 (declared deprecated by the TrackerDPG) and replacing it by T3 (phase2 tracker for the TDR) eveywhere T1 was used.
Some comments for the integration process

1) We are waiting for the green light from UPSG to be sure that removing T1 is the scenarios is ok, but it doesn't prevent to start to look to make sure that everything is correct in this PR 

2) Assuming 1) ok : The scenario D3 and D4 are becoming identical - Since this PR is targeting 900pre2, I didn't remove D3 it at this stage, since it will create a complete re-shuffling of the WF numbers, and I don't think that due to the importance of this pre2 it's the right time to do this (i fear the level of confusion of the users - developers  can be high..) - Instead my proposal is to remove D3  for pre3 (quieter time after the Xmas production rush) 

3) This PR will conflict with my open PR #16896 (due to some renaming ) but depending on which one is merged first  I will address the conflicts in this one or or the other one (just need to talk and be consistent with myself..) 

4) More for @kpedro88 : For some reasons , when re-generating the geometries using your script, the file  Configuration/Geometry/python/GeometryExtended2023D5Reco_cff.py  has been updated adding few lines , not sure I understand if it is expected and correct, I invite you to check this particular file in this PR , thanks ... 

Adding usual watchers  :  @delaere , @atricomi , @rovere , @VinInn @makortel @ebrondol @venturia, @ghugo83

### CODE REVIEW

**Comment by kpedro88** [comment]
hold

**Comment by ianna** [comment]
@boudoul - yes, the change is expected. The dictionary has been updated but not the scenario. There is the same correction already from Lindsey (not sure if it's in IBs yet).

**Comment by kpedro88** [comment]
I'm making a unit test for the script to prevent such inconsistencies in the future (per @slava77's advice).

**Comment by boudoul** [comment]
Closing, superseded by #16965

**Pull request closed without merging**
