### PR TITLE
Constrain the TriggerObject template constructors

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Constrain the `TriggerObject` template constructors.

#### PR validation:

Full release builds and unit tests pass.

### CODE REVIEW

**Comment by fwyzard** [comment]
The reason for this is that while looking into #44844 I got some strange compiler errors from GCC (not from clang) related to these template constructors.

Adding the constrains fixes them.

**Comment by fwyzard** [comment]
please test

**Comment by mmusich** [comment]
+hlt
   * failures in reco and DQM comparisons are spurious (associated to known instabilities)

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
