### PR TITLE
Phase2-hgx255 Update dd4hep algorithms to match code conventions

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Update dd4hep algorithms to match code conventions

#### PR validation:

Tested using cfg's in test/python area of Geometry/HGCalCommonData

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
+1

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade

**Comment by silviodonato** [comment]
+1

**Pull request merged**
