### PR TITLE
Soft lepton tagger updates (74X)

### PR DESCRIPTION
**Pull request by ferencek**
Various updates and fixes mostly related to adding the MiniAOD support for the soft lepton taggers in jetTools.py

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

there was a new commit here

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/7959	a1ef592
changes in the reco code are trivial (renamed parameter) or correspond only to the parts of the code running in PAT configurations.
Jenkins tests show no differences in monitored quantities.

Please provide the same change for 75X (no strong reason to rely on auto-forward porting)

**Comment by ferencek** [comment]
@davidlange6 With #8020 merged, don't forget to merge this one as well. Thanks!

**Comment by davidlange6** [comment]
+1

**Pull request merged**
