### PR TITLE
Made MagFieldConfigDBWriter an edm::one::EDAnalyzer

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

This fixes the CMS deprecation warning.

#### PR validation:

Code compiles without issuing a CMS deprecation warning.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by ChrisMisan** [comment]
@Dr15Jones could you explain why there are differences in the JetMET?

**Comment by Dr15Jones** [comment]
@ChrisMisan given that MagFieldConfigDBWriter does not appear in any of the standard configurations, it is pretty safe to say that module is never run in any of the test release validation jobs. So the differences are most likely caused by instability in the reconstruction code itself where it does not always give back the same results when run again.

**Comment by mmusich** [comment]
@ChrisMisan 

> could you explain why there are differences in the JetMET?

you might want to have a look to https://github.com/cms-sw/cmssw/issues/39754

**Comment by tvami** [comment]
+alca
 * technical PR

**Comment by rappoccio** [comment]
+1 

* Technical

**Pull request merged**
