### PR TITLE
Remove obsolete code and configurations in CSC local trigger

### PR DESCRIPTION
**Pull request by dildick**
The aim of this PR is to make the CSC local trigger easier to understand and maintain, especially for new people in the CSC DPG. 

Presently, a dozen functions in the `CSCCathodeLCTProcessor` related to constructing CLCTs have not been used to simulate collision data since 2007 (or earlier). These obsolete functions and associated configurations should not have to be maintained in the future. They also make it hard to navigate a file with with >3000 lines. It is better to remove them. I am also removing a few obsolete test files.

In future PRs I would like to 
- remove an outdated local CSC DQM module
- remove the parameters `isTMB07` and `isMTCC`
- undo the decoupling of CLCTs and LCTs in ME1a and ME1b in upgrade scenarios (an interesting idea ~7 year ago that will not materialize in hardware)
- replace the CSCCLCTPreTriggerBXCollection by CSCCLCTPreTriggerDigiCollection (in trigger and packer)

By the end of the clean-up, the size of `CSCCathodeLCTProcessor.cc` will be reduced by at least 1500 lines.

There should be no changes with respect to the baseline for this PR.

Attention: @ptcox @tahuang1991 @lpernie

### CODE REVIEW

**Comment by thomreis** [comment]
please test

**Comment by thomreis** [comment]
Hi @dildick 
I understand that no data that has been taken will be affected by these changes? This only affects simulation from before the data taking?

**Comment by dildick** [comment]
@thomreis These functions were implemented for very early MC studies, or emulate data from test-beam studies in 2006. According to the comments in the code: "It was used in numerous CSC test beams and MTCC for firmware-emulator comparisons, but due to a number of known limitations it was never used in Monte Carlo studies."

It does not affect data taken for physics studies.

**Comment by thomreis** [comment]
+1
In that case I think this is fine.

**Comment by dildick** [comment]
For a moment I thought that the configuration `CSCTPE_setup_cfi` was used in the online DQM, but in fact it was switched off over 4 years ago because it was not working, see https://github.com/dmitrijus/cmssw/commit/069cc0a00b211ce1bcf8c37600237bfbf9eb0982.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
