### PR TITLE
Mydev

### PR DESCRIPTION
**Pull request by doanhien**

### CODE REVIEW

**Comment by yetkinyilmaz** [comment]
Hi;
This pull-request seems to be difficult to review. Can you not rebase it?
Also, there is no description and no explanatory branch name.
Is it possible that somebody has clicked on the pull-request button unintentionally?

**Comment by doanhien** [comment]
Hi,

I only click on the pull-request for my branches. I don't know why it involves many packages.
And I also describe the branch name.
Do you know how I can change it?

Thanks!

**Comment by Dr15Jones** [comment]
Was this pull request meant for CMSSW_7_6? From the other commits in this pull request it seems it was developed in 7_4?

**Comment by yetkinyilmaz** [comment]
Hi Chris.
We can close this pull-request.
We should make a new one with Hien more carefully.

**Comment by richard-cms** [comment]
@doanhien did not start from a clean CMSSW env, these commits are from our private analysis code. I'll contact her (or adopt this PR) and get just the relevant commits merged.

**Pull request closed without merging**
