### PR TITLE
Check geant4 voxels structure

### PR DESCRIPTION
**Pull request by civanch**
#### PR description:
Added control on voxelization of Geant4 geometry. This may be useful for study and optimisation of voxel structure. Should not affect results of any WF.

#### PR validation:
private

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
test likely stack, we need to redo

**Comment by civanch** [comment]
Please test

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
