### PR TITLE
[12_4_X] Incorporate PiZeroAnalyzer code into ECAL DQM

### PR DESCRIPTION
**Pull request by alejands**
#### PR description:

ECAL DPG requested to have the offline DQM plots ([example offline GUI](https://tinyurl.com/2ykhlsat)) from `PiZeroAnalyzer` in `DQMOffline/EGamma` available in online DQM as well. 
- https://github.com/cms-sw/cmssw/blob/master/DQMOffline/EGamma/plugins/PiZeroAnalyzer.h
- https://github.com/cms-sw/cmssw/blob/master/DQMOffline/EGamma/plugins/PiZeroAnalyzer.cc
- https://github.com/cms-sw/cmssw/blob/master/DQMOffline/EGamma/python/piZeroAnalyzer_cfi.py

In order to do this, we have migrated the code above into a new ECAL DQM module `PiZeroTask` in `DQM/EcalMonitorTasks`, which can then create plots both online and offline.

This new code is functionally the same as the old analyzer but after discussing with DPG, we decided to leave the old analyzer code in to not break anything. Open to discussion.

Complimentary PR to dmwm/deployment:
- https://github.com/dmwm/deployment/pull/1155

#### PR validation:

Online DQM client run on test data. Offline DQM tested on relval WF 11634.511 (`runTheMatrix.py -w upgrade -l 11634.511`). In both cases, the new plots were created successfully and matched the features of the old plots.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport of https://github.com/cms-sw/cmssw/pull/38561 to have for first 13.6 TeV stable collisions

### CODE REVIEW

**Comment by emanueleusai** [comment]
please test

**Comment by emanueleusai** [comment]
type ecal

**Comment by emanueleusai** [comment]
type feature

**Comment by emanueleusai** [comment]
backport of #38561

**Comment by emanueleusai** [comment]
+1

**Comment by perrotta** [comment]
> +1

Since 12_4_X is a production cycle, maybe we can wait to merge this only once its 12_3_X version is tested at P5 and the corresponding backport PR is also signed, see https://github.com/cms-sw/cmssw/pull/38571#issuecomment-1171992187

**Comment by qliphy** [comment]
+1
Tested at PR done: https://github.com/cms-sw/cmssw/pull/38571

**Pull request merged**
