### PR TITLE
Additional Photos options (9_4_X)

### PR DESCRIPTION
**Pull request by mseidel42**
#### PR description:

Backport of https://github.com/cms-sw/cmssw/pull/26853

### CODE REVIEW

**Comment by qliphy** [comment]
@intrepid42   Why 94X instead of 93X?

**Comment by intrepid42** [comment]
I think it's used for 5 TeV and low PU? Will create 93X and 71X* as well!

\* 71X seems to require Photos update...

**Comment by qliphy** [comment]
@intrepid42  ok, I see.

**Comment by qliphy** [comment]
please test

**Comment by efeyazgan** [comment]
+1

**Comment by fabiocos** [comment]
@intrepid42 @efeyazgan do we have production requests in 9_4_X requiring this PR?

**Comment by intrepid42** [comment]
Hi Fabio, not yet, maybe in a couple of months.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
