### PR TITLE
[DQM-GEOMETRY] Various fixes/improvements for unit test

### PR DESCRIPTION
**Pull request by smuzaffar**
Updated unit tests so that they can be run from their own separate directory. Mostly 
- convert `<bin ...>` to `<test....>`
- use full path e.g `CMSSW_BASE/src/...` instead of `./src/`

For now `<flags USE_UNITTEST_DIR="1"/>` is added to use separate unit test directory to avoid duplicate files in same path. Once all tests can use separate unit test dir then we will enable `USE_UNITTEST_DIR="1"` at project level

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by Dr15Jones** [comment]
@smuzaffar thanks!

**Comment by civanch** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
