### PR TITLE
Update of histograms for TauPOG DQM data certification for future data taking

### PR DESCRIPTION
**Pull request by roger-wolf**
This is an update of histograms for TauPOG data certification for future data taking. The pull request is minimal in this sense. We have checked theMatrix and our standard s/w validation sequences to make sure that the changes do not interfere in any way. Our tests were positive. The pull request goes along with a similar request for the DQM GUI that according to our developer (@atanumodak) has already been accepted and integrated.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

@dmitrijus this has been awaiting review for a few days already

**Comment by roger-wolf** [comment]
@dmitrijus

can you let me know what is missing to get this pull request off the table. We are missing your signature since two weeks now. I think it's the last missing piece in the chain. 

Thanx a lot!
Roger

**Comment by dmitrijus** [comment]
please test

Nothing is missing, should be okay.
I must have missed this PR :(

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1
@roger-wolf - if this is really meant for data certification, the heart of the code should move out of Validation/* (MC validation) and into DQM(Offline).

**Pull request merged**
