### PR TITLE
Use GBRForest in PATMuonProducer

### PR DESCRIPTION
**Pull request by wddgit**
This PR was motivated by an igprof performance profile where we were looking for initialization times for modules that were proportional to the number of streams and significant. It was about the fourth highest and the higher ones were recently fixed also. The intent is that this should not change results. I tested by printing the mva values calculated with and without this change in runTheMatrix test 10824.0 and they were identical. I also verified it removes the scaling with number of streams with igprof.

### CODE REVIEW

**Comment by slava77** [comment]
> This PR was motivated by an igprof performance profile

@wddgit  please put this text in the PR description for better self-documentation.

Thank you for this work.
This should address #20700 opened just over 6 months ago.

**Comment by wddgit** [comment]
@slava77 I moved the comment. It's better there.

@drkovalskyi FYI

**Comment by VinInn** [comment]
I think at some point we should move
"CondFormats/EgammaObjects/interface/GBRForest.h"
to a more central place...

**Comment by slava77** [comment]
On 4/14/18 12:54 AM, Vincenzo Innocente wrote:
> I think at some point we should move
> "CondFormats/EgammaObjects/interface/GBRForest.h"
> to a more central place...
> 

makes sense.
Perhaps alca/db software coordinators can suggest or follow up on this move.

**Comment by drkovalskyi** [comment]
@wddgit thanks for taking care of it.

**Comment by perrotta** [comment]
I assume that the move suggested in https://github.com/cms-sw/cmssw/pull/22963#issuecomment-381311496 is meant to a subsequent pull request, not already for this one: is it correct @VinInn ?

**Comment by VinInn** [comment]
Yes

**Comment by perrotta** [comment]
+1
- It addresses issue #20700
- The changes are technical, in line with the PR description
- Jenkins tests pass and comparisons with baseline show no differences

**Comment by fabiocos** [comment]
@arunhep @lpernie @ggovi please see the comment above by Vincenzo

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Pull request merged**
