### PR TITLE
Phase2-gex81 Modify the Phase2 scenarios to work for dd4hep

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Modify the Phase2 scenarios (including the right cff for tracker)  to work for dd4hep
 
#### PR validation:

Tested using runTheMatrix Phase2 workflows

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by srimanob** [comment]
Hi @bsunanda 
As PR test does not include Phast-2 dd4hep workflow, could you please clarify a bit on testing and it is only a known stopper to run dd4hep in Phase-2 until the end (not include validation) ?

**Comment by cvuosalo** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

As presented in the simulation meeting (2 July), https://indico.cern.ch/event/1053571/

**Comment by qliphy** [comment]
+1

**Pull request merged**
