### PR TITLE
Code performance improvements in follow-up to #31722

### PR DESCRIPTION
**Pull request by ericcano**
#### PR description:

CMSSW https://github.com/cms-sw/cmssw/pull/31722 Patatrack integration - Pixel track reconstruction (10/N) was merged with [extra comments to be addressed](https://github.com/cms-sw/cmssw/pull/31722#pullrequestreview-623346747).

This PR addresses the performance related comments.

#### PR validation:

The code was run in workflows (step3 and step4):
- 11634.501 (CPU)
- 11634.502 (GPU)
- 11634.505 (CPU)
- 11634.506 (GPU)

The workflow results where then compared using the plots generated by `makeTrackValidationPlots.py`. The CPU workflows gave results identical to the baseline integration build. The GPU workflows displayed slight variations, but the variations are also present between multiple runs of the same version (baseline or this branch).

Unit tests were fine except one problem not related the this branch and followed up in https://github.com/cms-sw/cmssw/issues/33797

### CODE REVIEW

**Comment by VinInn** [comment]
most of the changes affect Rienman fit that is not default.
1) My understanding is that Rienmann fit has NOTT been tested against original patatrack version after integration
2) Do a wf exists to test it?
3) How we know that the proposed changes are indeed a performance improvements?

**Comment by slava77** [comment]
>     1. My understanding is that Rienmann fit has NOT been tested against original patatrack version after integration.

is it possible to add a test then?

**Comment by slava77** [comment]
This branch has conflicts that must be resolved

Conflicting files
RecoPixelVertexing/PixelTrackFitting/interface/RiemannFit.h

please update, if this is till considered to be an active PR

**Comment by slava77** [comment]
@ericcano 
please clarify on the status of this PR.
Thank you.

**Comment by ericcano** [comment]
@slava77 as the PR is pending testing RiemannFit, I opened an issue in patatrack for creating a test, and will close it. We will re-introduce the changes when tests are available.

**Pull request closed without merging**
