### PR TITLE
[14_0_X] Alpaka Pixel: Write `nTracks=0` When No Track Stored

### PR DESCRIPTION
**Pull request by AdrianoDee**
#### PR description:

Plain backport of https://github.com/cms-sw/cmssw/pull/45876 to `14_0_X`

### CODE REVIEW

**Comment by AdrianoDee** [comment]
test parameters:
- workflow_opts = -w upgrade
- workflows_gpu = 12461.402, 12861.0, 12851.402
- workflows = 12461.402, 12861.0, 12851.402

**Comment by AdrianoDee** [comment]
please test

**Comment by AdrianoDee** [comment]
backport of https://github.com/cms-sw/cmssw/pull/45876

**Comment by AdrianoDee** [comment]
please abort

**Comment by AdrianoDee** [comment]
test parameters:
- workflow_opts = -w upgrade
- workflows_gpu = 12461.402, 12861.0, 12861.402
- workflows = 12461.402, 12861.0, 12861.402

**Comment by AdrianoDee** [comment]
please test

**Comment by AdrianoDee** [comment]
urgent
- backport(s) needed for datataking

**Comment by antoniovilela** [comment]
ping @cms-sw/reconstruction-l2

**Comment by jfernan2** [comment]
+1

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
