### PR TITLE
bsunanda:Run2-gem08 Add the GE21 geometry with pointing strips

### PR DESCRIPTION
**Pull request by bsunanda**
The GE21 geometry in v6 is corrected and the one in v7 is with radial strips pointing to the beam axis

### CODE REVIEW

**Comment by ianna** [comment]
@cmsbuild please test

**Comment by bsunanda** [comment]
Can you start the test after correcting the IB? This is not a fault of the PR but of the IB.
________________________________

**Comment by smuzaffar** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
