### PR TITLE
Add mu beamspot constrained pT. Increase mu eta and phi precision to 16 bits

### PR DESCRIPTION
**Pull request by namapane**
#### PR description:
Following discussions between H4l and Hmumu analysis teams, we would like to put forward a proposal to add the beamspot-constrained muon pT to nanoAOD v13.

Some background:

A BS constraint applied on top of PAT:Muons has been already adopted for the mH measurement in 4l  (HIG-21-019) after discussion/blessing in the muon POG [[talk1](https://indico.cern.ch/event/1012952/contributions/4251427)]. It was shown to significantly improve the mH resolution, especially since 2018 when the BS widths are of the order of ~6 microns, and was preferred for such an high profile analysis to ad-hoc parametrizations (eg GeoFit) as it is a natural step in reconstruction rather than an heuristic a-posteriori correction, that requires tuning. There are also ongoing studies for using this for Hmumu.

At the time of discussion in the muon POG, including this in standard sequences was not considered, as this constrain can be easily applied by the user while running on miniAODs.

However, it is not possible to apply the constraint on top of NanoAODs, and this limitation is becoming apparent now. The statement that for mH4l we may be forced to stay with a miniAOD framework for this reason  sparked some discussion within the ATTF framework surveys [[talk2](https://indico.cern.ch/event/1098320/contributions/4621442) - see last page of the discussion document at the end of the agenda]; there were several suggestions to investigate possible ways to include the required information in nanoAODs. My reply at the time was that the implementation of the "VX+BS" approach used in the H4l analysis includes both a BS constraint and a common vertex constraint among the 4 selected muons; this makes it impossible to define a general-purpose constrained pT variable.
But actually, for 2018 and Run3, the BS width is so small that essentially all improvement comes from the BS constraint, not the common vertex constraint, so constraining each muon individually would be enough.

The present implementation is based on SingleTrackVertexConstraint. It essentially just adds 3 variables: the updated pt, ptError (precision=6) and chi2 (precision=6) We checked that the variation of eta and phi (and of their errors) are negligible so it would not be necessary to store these.

One more small update included is the increase of the precision of Muon_eta and Muon_phi from 12 bits to 16 ([code here](https://github.com/namapane/cmssw/blob/muBSConstraint_124X/PhysicsTools/NanoAOD/python/muons_cff.py#L159-L160)). This is because with the current precision we have a small rounding error on the reconstructed invariant masses, of about ~3.5 MeV (RMS) for H4mu [[talk3](https://indico.cern.ch/event/1253164/contributions/5265017/subcontributions/418422)]. Although this is a very small effect from the statistical point of view, authors feel it is somewhat unsatisfactory for the world's most precise single-channel measurement of mH to add a rounding smearing after they been fighting to reduce the systematic down to 17 MeV ([HIG-21-019](https://cms.cern.ch/iCMS/analysisadmin/cadilines?line=HIG-21-019), expected, 4mu only), especially if that can be avoided by just adding as little as 8 bits per muon.

#### PR validation:

 Both changes have been tested on 2018 (using a backport) and 2022 data/MC.

### CODE REVIEW

**Comment by vlimant** [comment]
enable nano

**Comment by vlimant** [comment]
please test

**Comment by vlimant** [comment]
I wonder if `MuonBeamspotConstraintValueMapProducer` should be declared here or under some RecoMuon packages, given that it can also be ran at MINI level, I'd be in favour of moving it out of a NANO package
Can you please add a ddm plot for the new variables under https://github.com/cms-sw/cmssw/blob/master/PhysicsTools/NanoAOD/python/nanoDQM_cfi.py#L501

**Comment by namapane** [comment]
> I wonder if `MuonBeamspotConstraintValueMapProducer` should be declared here or under some RecoMuon packages, given that it can also be ran at MINI level, I'd be in favour of moving it out of a NANO package 

I have no strong opinion, but from a quick look I'd say that, in case, possible destinations could be RecoMuon/GlobalTrackingTools/plugins or RecoMuon/MuonIdentification/plugins. Both of these already include value map producers. Please let me know if I should move it.

>Can you please add a ddm plot for the new variables under https://github.com/cms-sw/cmssw/blob/master/PhysicsTools/NanoAOD/python/nanoDQM_cfi.py#L501

Done.

**Comment by namapane** [comment]
Given that there is apparently no preference, I opted for RecoMuon/GlobalTrackingTools, which seems somehow more appropriate.

**Comment by mandrenguyen** [comment]
please test

**Comment by vlimant** [comment]
spurious (unrelated) changes to eta/phi of muons, likely to be due to rounding effect

**Comment by vlimant** [comment]
+1

**Comment by namapane** [comment]
> spurious (unrelated) changes to eta/phi of muons, likely to be due to rounding effect

That's actually intended: as mentioned in the PR description, the precision of muon eta/phi is increased to 16 bits instead of 12 ([code here](https://github.com/namapane/cmssw/blob/muBSConstraint_124X/PhysicsTools/NanoAOD/python/muons_cff.py#L159-L160)).

**Comment by mandrenguyen** [comment]
+1

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
