### PR TITLE
Add caloParams v0_0 for 2024 HI run

### PR DESCRIPTION
**Pull request by rohitcms**
PR description:
Add L1T calo configs for heavy ion with updated centrality trigger thresholds for use in the 2024 run, taking into account the HF response corrections. 

PR validation:
These files represent L1 configuration to be stored centrally, and are not involved in any central workflows.

If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:
Not a backport. Will need to backport to CMSSW_14_1_X.

### CODE REVIEW

**Comment by aloeliger** [comment]
please test

**Comment by aloeliger** [comment]
please test

**Comment by aloeliger** [comment]
+l1

**Comment by mandrenguyen** [comment]
@rohitcms this PR has conflicts that need to be resolved

**Comment by mandrenguyen** [comment]
please test

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
