### PR TITLE
Fix MultiTrackValidator efficiency summary and efficiency vs. deltaR plots

### PR DESCRIPTION
**Pull request by makortel**
The recently (#9201) added efficiency summary plot (average efficiency for each input track collection) in MultiTrackValidator has a bug in putting also out-of-time TrackingParticles to the denominator. Also the computation of the DeltaR of minimum distance between any TP pair includes OOT TPs. This PR fixes both with the following developments (superseding #9956)
- Add new `intimeOnly` flag to TrackingParticleSelector (with value False set to everywhere to not to change current behaviour)
- Switch this flag to True for the TP selector used in MTV loop over TPs for efficiency plots to reject OOT TPs there
  - The efficiency denominators themselves are fine already, as all TP selectors used in `MTVHistoProducerAlgoForTracker::fill_recoAssociated_simTrack_histos()` already have `signalOnly=True`
  - This change alone would be enough to fix both of the issues with OOT TPs, but has a knock-on effect on histograms in `Tracking/Track/<iter>/simulation` which have also been filled from OOT TPs, and actually for those keeping more or less the current behaviour would be nice. Therefore, 
- The histograms in `Tracking/Track/<iter>/simulation` are moved to `Tracking/Track/simulation` and filled only once per MTV instance (they are anyway the same for each iteration), and now from the set of all TPs without any selection (previously only those passing the TP selector in bullet 2 were used)
  - `bunchxSIM` is filled from both OOT and in-time TPs, while the others are filled only from IT TPs
- In addition, the same selection as for efficiency vs. DeltaR (same as efficiency vs. eta) is applied for efficiency summary plot, but now in two flavours: one with the pT cut (pT > 0.9 GeV) and other without pT cut.

Tested in 750pre6, expecting changes in `effic_vs_coll`, `num_simul_coll`, `num_assoc(simToReco)_coll`, and `globalEfficiencies` under `Tracking/Track` folder (`num_*_coll` also in other MTV instances), and `effic_vs_dr`, `num_simul_dr`, and `num_assoc(simToReco)_dr` in all MTV instances (in this case there is no change in the corresponding `globalEfficiencies`, as the integrals of numerator and denominator stay the same, only the DeltaR values change).

In noPU samples the efficiency summary plots should change like (black=old, red=new)
image

and in pileup samples like
image

In pileup samples the number of TPs and efficiency vs. DeltaR should change like (no changes expected in noPU samples)
image
image

@rovere @VinInn

### CODE REVIEW

**Comment by makortel** [comment]
I accidentally hit "submit" while still writing the description and running the final tests. All is fine now, so reopening.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by makortel** [comment]
The test should fail with a compilation error, that I catched myself too only now (the added "intimeOnly" parameter was not given to TrackingParticleSelector constructor in RecoMuonValidator; I don't know why my scram didn't fail on it before).

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1
Unsure why this needs a Core signature

**Comment by smuzaffar** [comment]
@Dr15Jones , it does not need core signs but it needs Geometry signatures (you are L2 of Geometry too )

**Comment by makortel** [comment]
ping

**Comment by cvuosalo** [comment]
@cmsbuild please test
Jenkins comparisons are still "Queued", so try test again.

**Comment by slava77** [comment]
@cmsbuild please test
the last attempt failed with
"kinit: Generic preauthentication failure while getting initial credentials"

**Comment by civanch** [comment]
+1

**Comment by smuzaffar** [comment]
this should be fixed now. Due to AFs cache issue on vocms0315, it was 
not able to read keytab file from afs.

**Comment by deguio** [comment]
+1
@makortel please make sure that the validators are aware of these changes.
thanks,
F.

**Comment by cvuosalo** [comment]
+1

For #10014 238a2c7538d15591aada36ed99c46af47362bab4

Bug fixes for MultiTrackValidator efficiency plots.

The code changes are satisfactory, and Jenkins [tests](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-10014/10907/summary.html) against baseline CMSSW_7_6_X_2015-07-04-2300 display only the expected changes as shown in the PR description.

**Pull request merged**
