### PR TITLE
Revert "removal of cfg.exists() checks from tau pog code"

### PR DESCRIPTION
**Pull request by fabiocos**
Reverts cms-sw/cmssw#24501

Temporary revert pending the solution of the problem #26236 (failure in unit tests of PhysicsTools/PatAlgos)

### CODE REVIEW

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
As expected, the unit tests in PhysicsTools/PatAlgos are all successful after the merge of this PR (standalone test)

**Comment by Martin-Grunewald** [comment]
+1

**Comment by santocch** [comment]
+1

**Comment by fabiocos** [comment]
No more needed after the integration of #26254 by @perrotta

**Pull request closed without merging**
