### PR TITLE
remove IN_DICTBUILD with __CLING__ to control the visibility of standard math vs sse

### PR DESCRIPTION
**Pull request by smuzaffar**
backport of #16440

As reported in #16291 , root sees inconsistents sse headers. This PR should avoid the use of internal IN_DICTBUILD and use ```__CLING__```

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by cvuosalo** [comment]
Jenkins results are showing a few odd fluctuations. Does this PR subtly change math behavior?

Workflow 	10024.0_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2017 shows:

tau

Workflow 	25202.0_TTbar_13 shows:
met

**Comment by slava77** [comment]
On 12/7/16 2:44 PM, Carl Vuosalo wrote:
> Jenkins results are showing a few odd fluctuations. Does this PR subtly
> change math behavior?
> 
> Workflow 10024.0_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2017 shows:
> 
> tau
> <https://cloud.githubusercontent.com/assets/5736159/20989935/3ecd7c4a-bc9c-11e6-9322-27191ec3484b.png>
> 
> Workflow 25202.0_TTbar_13 shows:
> met
> <https://cloud.githubusercontent.com/assets/5736159/20989953/4f4c0eec-bc9c-11e6-9c70-1d55d3c5ac04.png>

jenkins used CMSSW_9_0_X_2016-12-07-0000
this PR is based on
CMSSW_9_0_X_2016-12-07-1100
at least a part of the diffs is from
CMSSW_9_0_X_2016-12-07-0000..CMSSW_9_0_X_2016-12-07-1100

rerun the tests maybe?

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
+1

For #16891 5cd67ee0b7fcfa95c40b5954678b33805a5319fb

Replacing preprocessor directive `IN_DICTBUILD` with more standard `__CLING__`. There should be no change in monitored quantities.

The code changes are satisfactory, and Jenkins tests against baseline CMSSW_9_0_X_2016-12-07-2300 show no significant differences, as expected. The Jenkins tests have several problems that are not related to this PR.

**Pull request merged**
