### PR TITLE
Use the latest Express GT as a fallback, and fix http proxy setting in curl for Tier0 DataService query for Event Display applications.

### PR DESCRIPTION
**Pull request by diguida**
The fallback GT for the Event display applications is updated to the latest version used at Tier0.
Back-port of commit https://github.com/cms-sw/cmssw/pull/15296/commits/8b9abb0db5ebed25d5ddd73f2208571609d97986 in #15296 

Fix http proxy setting in `curl` for Tier0 DataService query in `DQM/Integration/python/config/FrontierCondition_GT_autoExpress_cfi.py`: the invalid parameter was causing the event display to always fall back to the default Express GT.
Back-port of commit https://github.com/cms-sw/cmssw/pull/15337/commits/349b25ccbf7f967293f08a599bfffd55e63162e9 in #15337

### CODE REVIEW

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
what is the 81x PR? @diguida

**Comment by diguida** [comment]
@davidlange6 the PR in 81X, namely #15296, includes also the change in the connection string:

* https://github.com/cms-sw/cmssw/pull/15296/commits/d62db6bfd87a1986e520c2535ed34f730c142960 remove the host domain lookup
* https://github.com/cms-sw/cmssw/pull/15296/commits/f568b04cceaebed8c520bbd5fbf3940418f79822 overrides the connection string for the online DQM applications
* https://github.com/cms-sw/cmssw/pull/15296/commits/8b9abb0db5ebed25d5ddd73f2208571609d97986 is the forward port of this one, i.e. changes the GT.

I can split #15296 into two, if you prefer.

**Comment by davidlange6** [comment]
no- its fine as it is - Thanks!

**Comment by diguida** [comment]
Added commit https://github.com/cms-sw/cmssw/pull/15298/commits/13c6adef187b3546b1fcad86f3b8496c8e5a06f0
Fix http proxy setting in `curl` for Tier0 DataService query in `DQM/Integration/python/config/FrontierCondition_GT_autoExpress_cfi.py`: the invalid parameter was causing the event display to always fall back to the default Express GT.
Back-port of commit https://github.com/cms-sw/cmssw/pull/15337/commits/349b25ccbf7f967293f08a599bfffd55e63162e9 in #15337

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
