### PR TITLE
Adding photon and muon leg trigger filters of HLT_Mu17_Photon30_IsoCa…

### PR DESCRIPTION
**Pull request by mrcthiel**
Adding photon and muon leg trigger filters of HLT_Mu17_Photon30_IsoCaloId_v* as requested in https://github.com/cms-sw/cmssw/issues/39069.
To be backported to 12_4_8.

### CODE REVIEW

**Comment by vlimant** [comment]
please test

**Comment by swertz** [comment]
Integration test running: https://gitlab.cern.ch/cms-nanoAOD/nanoAOD-integration/-/issues/191

**Comment by swertz** [comment]
@mrcthiel apologies for the delay.

In #39069 the following filters are also listed for 2016:
```
hltMu17Photon30CaloIdLL1ISOHEFilter
hltMu17Photon30CaloIdLL1ISOORHEFilter
hltL3fL1sL1Mu5IsoEG18L1f5L2f7L3Filtered17
hltL3fL1sL1Mu5IsoEG18ORL1Mu5IsoEG20L1f5L2f7L3Filtered17
```
but I don't see them added here, and indeed 2016 samples don't see any changes in muon and photon trigger objects. Are those not needed?

About this: 
>  To be backported to 12_4_8.

There will be no backports to 12_4_X as NanoV10 is now closed in 12_4_8.

**Comment by mrcthiel** [comment]
I already included 2016 paths by hand in my private area, so I do not need them. I just asked for the other paths (used in 2017 and 2018) thinking in the Run III data.

**Comment by swertz** [comment]
If these filter bits are relevant, other people analyzing 2016 data might want to use them, so I think for completeness it would be good to include them as well, thanks.

**Comment by mrcthiel** [comment]
ok, I can do a new PR in the next few days.

**Comment by swertz** [comment]
Thanks, but feel free to push to this PR, no need for a new one.

**Comment by swertz** [comment]
@mrcthiel will you update the PR with the 2016 filters?

**Comment by mrcthiel** [comment]
Sorry, I didn't update yet, I'm debugging another problem with 2016 filters. It seems there is a problem with the filter on 2016H and for 2016 MC, which uses the same path but is different from 2016B-G.

If you have urgency for the backport I would propose keeping the 2017-2018 filters and I'll keep debugging for 2016, let me know.

**Comment by swertz** [comment]
Ok we can run with what you have here - as I said more work is needed on those objects anyway. Can you just please apply the same changes to https://github.com/cms-sw/cmssw/blob/master/PhysicsTools/NanoAOD/python/V10/triggerObjects_cff.py before you make the backport to 124X?

**Comment by swertz** [comment]
enable nano
please test

**Comment by swertz** [comment]
please test

**Comment by swertz** [comment]
+1

Only differences seen in nanoAOD trigger objects for muons and photons.

**Pull request merged**
