### PR TITLE
Phase2-hgx316 In the path of making a geometry where no cells will be defined in the G4 geometry

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

In the path of making a geometry where no cells will be defined in the G4 geometry

#### PR validation:

Tested using cfg's in Geometry/HGCalCommonData/test/python

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

**Comment by perrotta** [comment]
+1

**Pull request merged**
