### PR TITLE
Few further esConsumes-related updates for CondFormats (RecoMuon and DT) test folders

### PR DESCRIPTION
**Pull request by battibass**
#### PR description:

This PR addresses the migration  to `esConsumes` of a few remaining modules, present in the `test/` folders of `CondFormats/RecoMuonObjects` and `CondFormats/DTObjects`, as reported [here](https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc7_amd64_gcc900/CMSSW_12_2_CMSDEPRECATED_X_2021-11-03-2300/CondFormats/RecoMuonObjects) and [here](https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc7_amd64_gcc900/CMSSW_12_2_CMSDEPRECATED_X_2021-11-03-2300/CondFormats/DTObjects).

#### PR validation:

AFAIK the code does not run in any central workflow.
Code compiles, passes code-checks and code-format, and a few cfgs from the test folders were exercised.

### CODE REVIEW

**Comment by battibass** [comment]
@swagata87

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
Some comments on a future improvement: 
 * under \test the header files should be merged into the .cc file
 * it's good to add unit tests (i.e. run the py config files)

Reading through the code I also notice that they use the legacy modules... this will need to be changed in this PR, in this state the Jenkins tests will have SA errors

**Comment by tvami** [comment]
> Some comments on a future improvement:
> 
> * under \test the header files should be merged into the .cc file
> * it's good to add unit tests (i.e. run the py config files)
> 
> Reading through the code I also notice that they use the legacy modules... this will need to be changed in this PR, in this state the Jenkins tests will have SA errors

Ahh yes, the SA doesnt check the \test directory... @battibass do you prefer to have another PR then for the legacy module fix?

**Comment by ggovi** [comment]
+1

**Comment by battibass** [comment]
> Ahh yes, the SA doesn't check the \test directory... @battibass do you prefer to have another PR then for the legacy module fix?

@tvami , yes, let's deal with that in a second PR please.
In general, do you have further instructions about how to check code compliance with CMSSW standards, beyond running `scram code-checks` and `scram code-format`?
Other than this, do you have a pointer about the implementation of unit tests in CMSSW?

**Comment by tvami** [comment]
@battibass can you please also include RecoMuon and DT in the PR title? It's good to be able to figure out what part of CondFormats you are changing just by reading the title

**Comment by tvami** [comment]
> @tvami , yes, let's deal with that in a second PR please.

Ok, I'll sign it now (but please still rename the PR)

> In general, do you have further instructions about how to check code compliance with CMSSW standards, beyond running `scram code-checks` and `scram code-format`?

Hmm one pointer I can give is this link: https://cms-sw.github.io/cms_coding_rules.html
Let me know if this is what you had in mind.

>  Other than this, do you have a pointer about the implementation of unit tests in CMSSW?

Sure, I've made a new unit test in this ongoing PR
https://github.com/cms-sw/cmssw/pull/36028/files
the relevant files are
 * cpp for testing infrastructure: https://github.com/cms-sw/cmssw/blob/0abc1b19dcba243fcd83cfd7bc904ab5636b7f79/CondFormats/Common/test/testDropboxMetadataDB.cpp
 * BuildFile: https://github.com/cms-sw/cmssw/blob/0abc1b19dcba243fcd83cfd7bc904ab5636b7f79/CondFormats/Common/test/BuildFile.xml#L22-L27
 * script: https://github.com/cms-sw/cmssw/blob/0abc1b19dcba243fcd83cfd7bc904ab5636b7f79/CondFormats/Common/test/createTestDBObjects.sh
 * config to really run: https://github.com/cms-sw/cmssw/blob/0abc1b19dcba243fcd83cfd7bc904ab5636b7f79/CondFormats/Common/test/ProduceDropBoxMetadata.py

Or another example with a lot of unit tests is in
https://github.com/cms-sw/cmssw/blob/master/CondTools/SiPixel/test/createTestDBObjects.sh

**Comment by tvami** [comment]
+alca

**Comment by qliphy** [comment]
+1

**Comment by battibass** [comment]
@tvami, thanks a lot!

For the unit tests, that is all I need.

About:

> Hmm one pointer I can give is this link: https://cms-sw.github.io/cms_coding_rules.html Let me know if this is what you had in mind.

My question was more wether there are additional commands or compilation flag one must use, beyond what I already tested with scam, before submitting the PR.
E.g.: I am not sure that the checks I ran would have spot the lack of esConsumes migration that caused the need for a PR.

**Comment by tvami** [comment]
I'm not fully sure of the details, there is this way to compile with errors and  `libchecker`, this is done every IB, see the latest here
https://cmssdt.cern.ch/SDT/cgi-bin/showBuildLogs.py/slc7_amd64_gcc900/www/wed/12.2.CMSDEPRECATED-wed-23/CMSSW_12_2_CMSDEPRECATED_X_2021-11-10-2300

Maybe @smuzaffar can comment on how the CMSDEPRECATED IBs are built

**Comment by tvami** [comment]
I think the flag is actually -Wdeprecated-declarations

**Comment by smuzaffar** [comment]
@tvami @battibass , for esConsumes you can either use CMSDEPRECATED IB or for normal IBs, you can set `USER_CXXFLAGS=-DUSE_CMS_DEPRECATED` environment

**Pull request merged**
