### PR TITLE
Add extra options to the simulation step

### PR DESCRIPTION
**Pull request by civanch**
#### PR description:
With new Geant4 11.0.7 new options may be activated for simulation. Mainstream MC should not be affected. 

#### PR validation:
private

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by perrotta** [comment]
+1

**Comment by smuzaffar** [comment]
@civanch , looks like this change broke G4/G4 vecgeom IBs

**Comment by civanch** [comment]
@smuzaffar , the fix is in #39376

**Comment by smuzaffar** [comment]
thanks @civanch

**Comment by civanch** [comment]
@smuzaffar , sorry the fix was incomplete.

**Pull request merged**
