### PR TITLE
GTs updated with Tracking, SiStripDQM Trigger Keys, HCAL electronics map, ZeroMaterial Geom

### PR DESCRIPTION
**Pull request by arunhep**
# Summary of changes in Global Tags

## RunI simulation

   * **RunI Heavy Ions scenario** : [91X_mcRun1_HeavyIon_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/91X_mcRun1_HeavyIon_v1) as [90X_mcRun1_HeavyIon_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_mcRun1_HeavyIon_v4) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/91X_mcRun1_HeavyIon_v1/90X_mcRun1_HeavyIon_v4):
      * Update of SiStrip DQM Trigger keys

   * **RunI Ideal scenario** : [91X_mcRun1_design_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/91X_mcRun1_design_v1) as [90X_mcRun1_design_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_mcRun1_design_v4) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/91X_mcRun1_design_v1/90X_mcRun1_design_v4):
      * Update of SiStrip DQM Trigger keys

   * **RunI Proton-Lead scenario** : [91X_mcRun1_pA_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/91X_mcRun1_pA_v1) as [90X_mcRun1_pA_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_mcRun1_pA_v4) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/91X_mcRun1_pA_v1/90X_mcRun1_pA_v4):
      * Update of SiStrip DQM Trigger keys

   * **RunI Realistic scenario** : [91X_mcRun1_realistic_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/91X_mcRun1_realistic_v1) as [90X_mcRun1_realistic_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_mcRun1_realistic_v4) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/91X_mcRun1_realistic_v1/90X_mcRun1_realistic_v4):
      * Update of SiStrip DQM Trigger keys
## RunII simulation

   * **RunII Asymptotic scenario** : [91X_mcRun2_asymptotic_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/91X_mcRun2_asymptotic_v2) as [90X_mcRun2_asymptotic_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_mcRun2_asymptotic_v5) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/91X_mcRun2_asymptotic_v2/90X_mcRun2_asymptotic_v5):
      * Update of SiStrip DQM Trigger keys
      * Addition of L1 Prescales and Vetos in GT

   * **RunII CRAFT scenario** : [91X_mcRun2cosmics_startup_deco_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/91X_mcRun2cosmics_startup_deco_v2) as [90X_mcRun2cosmics_startup_deco_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_mcRun2cosmics_startup_deco_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/91X_mcRun2cosmics_startup_deco_v2/90X_mcRun2cosmics_startup_deco_v1):
      * Update of SiStrip DQM Trigger keys
      * Addition of L1 Prescales and Vetos in GT

   * **RunII Heavy Ions scenario** : [91X_mcRun2_HeavyIon_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/91X_mcRun2_HeavyIon_v2) as [90X_mcRun2_HeavyIon_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_mcRun2_HeavyIon_v4) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/91X_mcRun2_HeavyIon_v2/90X_mcRun2_HeavyIon_v4):
      * Update of SiStrip DQM Trigger keys
      * Addition of L1 Prescales and Vetos in GT

   * **RunII Ideal scenario** : [91X_mcRun2_design_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/91X_mcRun2_design_v2) as [90X_mcRun2_design_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_mcRun2_design_v5) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/91X_mcRun2_design_v2/90X_mcRun2_design_v5):
      * Update of SiStrip DQM Trigger keys
      * Addition of L1 Prescales and Vetos in GT

   * **RunII Proton-Lead scenario** : [91X_mcRun2_pA_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/91X_mcRun2_pA_v2) as [90X_mcRun2_pA_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_mcRun2_pA_v5) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/91X_mcRun2_pA_v2/90X_mcRun2_pA_v5):
      * Update of SiStrip DQM Trigger keys
      * Addition of L1 Prescales and Vetos in GT

   * **RunII Startup scenario** : [91X_mcRun2_startup_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/91X_mcRun2_startup_v2) as [90X_mcRun2_startup_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_mcRun2_startup_v4) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/91X_mcRun2_startup_v2/90X_mcRun2_startup_v4):
      * Update of SiStrip DQM Trigger keys
      * Update of CSC and DT Alignment and APEs for startup scenario
      * Addition of L1 Prescales and Vetos in GT

## RunI data

   * **RunI HLT processing** : [91X_dataRun2_HLT_frozen_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/91X_dataRun2_HLT_frozen_v1) as [90X_dataRun2_HLT_frozen_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_dataRun2_HLT_frozen_v4) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/91X_dataRun2_HLT_frozen_v1/90X_dataRun2_HLT_frozen_v4):
      * Update of Tracking
      * Update of HCAL local reco conditions
      * Update of HCAL reco geometry

   * **RunI Offline processing** : [91X_dataRun2_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/91X_dataRun2_v1) as [90X_dataRun2_v6](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_dataRun2_v6) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/91X_dataRun2_v1/90X_dataRun2_v6):
      * Update of SiStrip DQM Trigger keys
      * Update of Tracking

## RunII data

   * **RunII HLTHI processing** : [91X_dataRun2_HLTHI_frozen_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/91X_dataRun2_HLTHI_frozen_v1) as [90X_dataRun2_HLTHI_frozen_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_dataRun2_HLTHI_frozen_v4) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/91X_dataRun2_HLTHI_frozen_v1/90X_dataRun2_HLTHI_frozen_v4):
      * Update of Tracking
      * Update of HCAL local reco conditions
      * Update of HCAL reco geometry

   * **RunII HLT processing** : [91X_dataRun2_HLT_frozen_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/91X_dataRun2_HLT_frozen_v1) as [90X_dataRun2_HLT_frozen_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_dataRun2_HLT_frozen_v4) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/91X_dataRun2_HLT_frozen_v1/90X_dataRun2_HLT_frozen_v4):
      * Update of Tracking
      * Update of HCAL local reco conditions
      * Update of HCAL reco geometry

   * **RunII HLT relval processing** : [91X_dataRun2_HLT_relval_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/91X_dataRun2_HLT_relval_v1) as [90X_dataRun2_HLT_relval_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_dataRun2_HLT_relval_v4) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/91X_dataRun2_HLT_relval_v1/90X_dataRun2_HLT_relval_v4):
      * Update of Tracking
      * Update of HCAL local reco conditions
      * Update of HCAL reco geometry

   * **RunII Offline processing** : [91X_dataRun2_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/91X_dataRun2_v1) as [90X_dataRun2_v6](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_dataRun2_v6) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/91X_dataRun2_v1/90X_dataRun2_v6):
      * Update of SiStrip DQM Trigger keys
      * Update of Tracking

   * **RunII Offline relval processing** : [91X_dataRun2_relval_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/91X_dataRun2_relval_v1) as [90X_dataRun2_relval_v6](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_dataRun2_relval_v6) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/91X_dataRun2_relval_v1/90X_dataRun2_relval_v6):
      * Update of SiStrip DQM Trigger keys
      * Update of Tracking

   * **RunII Prompt processing** : [91X_dataRun2_PromptLike_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/91X_dataRun2_PromptLike_v1) as [90X_dataRun2_PromptLike_v6](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_dataRun2_PromptLike_v6) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/91X_dataRun2_PromptLike_v1/90X_dataRun2_PromptLike_v6):
      * Update of SiStrip DQM Trigger keys
      * Update of Tracking
      * Update of HCAL local reco conditions
      * Update of HCAL reco geometry
      * Update of L1 Tag

## Upgrade

   * **PhaseII realistic scenario** : [91X_upgrade2023_realistic_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/91X_upgrade2023_realistic_v1) as [90X_upgrade2023_realistic_v9](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_upgrade2023_realistic_v9) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/91X_upgrade2023_realistic_v1/90X_upgrade2023_realistic_v9):
      * Update of SiStrip DQM Trigger keys
      * Update of RPC tags

   * **PhaseI 2017 cosmics peak scenario** : [91X_upgrade2017cosmics_realistic_peak_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/91X_upgrade2017cosmics_realistic_peak_v2) as [90X_upgrade2017cosmics_realistic_peak_v19](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_upgrade2017cosmics_realistic_peak_v19) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/91X_upgrade2017cosmics_realistic_peak_v2/90X_upgrade2017cosmics_realistic_peak_v19):
      * Update of SiStrip DQM Trigger keys
      * Include ZeroMaterial Sim Geometry
      * Cleanup of few redundant geometry tags
      * Addition of L1 Prescales and Vetos in GT

   * **PhaseI 2017 cosmics scenario** : [91X_upgrade2017cosmics_realistic_deco_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/91X_upgrade2017cosmics_realistic_deco_v2) as [90X_upgrade2017cosmics_realistic_deco_v18](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_upgrade2017cosmics_realistic_deco_v18) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/91X_upgrade2017cosmics_realistic_deco_v2/90X_upgrade2017cosmics_realistic_deco_v18):
      * Update of SiStrip DQM Trigger keys
      * Include ZeroMaterial Sim Geometry
      * Cleanup of few redundant geometry tags
      * Addition of L1 Prescales and Vetos in GT

   * **PhaseI 2017 design scenario** : [91X_upgrade2017_design_IdealBS_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/91X_upgrade2017_design_IdealBS_v2) as [90X_upgrade2017_design_IdealBS_v19](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_upgrade2017_design_IdealBS_v19) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/91X_upgrade2017_design_IdealBS_v2/90X_upgrade2017_design_IdealBS_v19):
      * Update of SiStrip DQM Trigger keys
      * Include ZeroMaterial Sim Geometry
      * Update of tracking
      * Addition of L1 Prescales and Vetos in GT

   * **PhaseI 2017 realistic scenario** : [91X_upgrade2017_realistic_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/91X_upgrade2017_realistic_v2) as [90X_upgrade2017_realistic_v20](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_upgrade2017_realistic_v20) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/91X_upgrade2017_realistic_v2/90X_upgrade2017_realistic_v20):
      * Update of SiStrip DQM Trigger keys
      * Include ZeroMaterial Sim Geometry
      * Update of tracking
      * Cleanup of few redundant geometry tags
      * Addition of L1 Prescales and Vetos in GT

   * **PhaseI 2018 cosmics scenario** : [91X_upgrade2018cosmics_realistic_deco_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/91X_upgrade2018cosmics_realistic_deco_v2) as [90X_upgrade2018cosmics_realistic_deco_v17](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_upgrade2018cosmics_realistic_deco_v17) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/91X_upgrade2018cosmics_realistic_deco_v2/90X_upgrade2018cosmics_realistic_deco_v17):
      * Update of SiStrip DQM Trigger keys
      * Cleanup of few redundant geometry tags
      * Update of HCAL electronics map
      * Addition of L1 Prescales and Vetos in GT

   * **PhaseI 2018 design scenario** : [91X_upgrade2018_design_IdealBS_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/91X_upgrade2018_design_IdealBS_v2) as [90X_upgrade2018_design_IdealBS_v15](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_upgrade2018_design_IdealBS_v15) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/91X_upgrade2018_design_IdealBS_v2/90X_upgrade2018_design_IdealBS_v15):
      * Update of SiStrip DQM Trigger keys
      * Update of tracking
      * Update of HCAL electronics map
      * Addition of L1 Prescales and Vetos in GT

   * **PhaseI 2018 realistic scenario** : [91X_upgrade2018_realistic_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/91X_upgrade2018_realistic_v2) as [90X_upgrade2018_realistic_v17](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_upgrade2018_realistic_v17) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/91X_upgrade2018_realistic_v2/90X_upgrade2018_realistic_v17):
      * Update of SiStrip DQM Trigger keys
      * Cleanup of few redundant geometry tags
      * Update of tracking
      * Update of HCAL electronics map
      * Addition of L1 Prescales and Vetos in GT

### CODE REVIEW

**Comment by arunhep** [comment]
please test

**Comment by arunhep** [comment]
@makortel FYI As tracking has been updated in this PR so we see slight increase in tracking efficiency from Sim to RECO https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_9_1_X_2017-03-30-1100+18136/19110/10024.0_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2017_GenSimFull+DigiFull_2017+RecoFull_2017+ALCAFull_2017+HARVESTFull_2017/Tracking_Track_cutsRecoHp_trackingParticleRecoAsssociation.html

@mmusich is this expected? https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_9_1_X_2017-03-30-1100+18136/19110/4.53_RunPhoton2012B+RunPhoton2012B+HLTD+RECODR1reHLT+HARVESTDR1reHLT/AlCaReco.html

**Comment by makortel** [comment]
@slava77 @perrotta This PR contains the updated phase1 initialStep MVA selection. Here are MTV plots for expected changes
https://cms-tracking-validation.web.cern.ch/cms-tracking-validation/PR/CMSSW_9_0_0_pre4_PR18136/
with
* blue = 900pre4 + #17537 
* red = blue + #17511 + #17544 
* black = red + the initialStep MVA as in this PR
and you can see that for highPurity black recovers the efficiency of blue in |eta|>2.4
https://cms-tracking-validation.web.cern.ch/cms-tracking-validation/PR/CMSSW_9_0_0_pre4_PR18136/phase1_ca_ttbar_pu35_highPurity/effandfakePtEtaPhi.pdf

For the record this update was presented in RECO meeting March 24
https://indico.cern.ch/event/624577/contributions/2521425/attachments/1433481/2202965/slides_reco_20170324.pdf

FYI @rovere @VinInn @felicepantaleo @hajohajo

**Comment by makortel** [comment]
I'm not really sure why the improvement does not show up in PR tests, maybe it (and the original efficiency drop in HP) is visible only with pileup?

(I just re-tested in 900 and the tag from CondDB that the improvement is there in ttbar+35PU)

**Comment by mmusich** [comment]
@arunhep 

> @mmusich is this expected? https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_9_1_X_2017-03-30-1100+18136/19110/4.53_RunPhoton2012B+RunPhoton2012B+HLTD+RECODR1reHLT+HARVESTDR1reHLT/AlCaReco.html

No. It is not expected. On the other hand the conditions are instead exactly what one expects.

For instance the Global Tag used  in the `run1_data` and `run_data` is exactly the same:
   * [run2 data GT change](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/91X_dataRun2_v1/90X_dataRun2_v6)

and if I compare the payloads for `AlCaRecoTriggerBits_TrackerDQM_v5_offline` and `AlCaRecoTriggerBits_TrackerDQM_v6_offline` in the different IOVs: 

```
cmsrel CMSSW_9_1_X_2017-03-30-2300
cd CMSSW_9_1_X_2017-03-30-2300/src/
cmsenv
git cms-addpkg CondTools/HLT
cd CondTools/HLT/test/
cmsRun AlCaRecoTriggerBitsRcdRead_TEMPL_cfg.py inputTag=AlCaRecoTriggerBits_TrackerDQM_v6_offline
cmsRun AlCaRecoTriggerBitsRcdRead_TEMPL_cfg.py inputTag=AlCaRecoTriggerBits_TrackerDQM_v5_offline
diff -u triggerBitsAlCaRecoTriggerBits_TrackerDQM_v5_offline.twiki triggerBitsAlCaRecoTriggerBits_TrackerDQM_v6_offline.twiki
```
resulting in:

```bash
--- triggerBitsAlCaRecoTriggerBits_TrackerDQM_v5_offline.twiki	2017-03-31 11:47:00.529893225 +0200
+++ triggerBitsAlCaRecoTriggerBits_TrackerDQM_v6_offline.twiki	2017-03-31 11:44:49.853437522 +0200
@@ -1,6 +1,7 @@
 ---+++++ *IOV*: 1-264291
 | *TriggerBits list key* | *HLT paths* |
-| 'SiStrip_HLT' | 'HLT_ZeroBias_v*', 'HLT_HIZeroBias_v*', 'HLT_BptxAnd_*' |
+| 'SiStrip_HLT' | 'HLT_ZeroBias_v*', 'HLT_HIZeroBias_v*', 'HLT_BptxAnd_*', 'HLT_L1SingleMuOpen_v*', 'HLT_PAL1MinimumBiasHF_OR_SinglePixelTrack_*' |
+| 'SiStrip_IB_HLT' | 'HLT_ZeroBias_FirstCollisionAfterAbortGap_*', 'HLT_ZeroBias_IsolatedBunches_v*' |
 | 'SiStrip_L1' | 'L1_ZeroBias' |
 | 'Tracking_HLT' | 'HLT_ZeroBias_v*', 'HLT_HIZeroBias_v*', 'HLT_BptxAnd_*' |
 | 'Tracking_HLT_HIP_OOT' | 'HLT_ZeroBias_FirstBXAfterTrain_v*' |
@@ -8,7 +9,8 @@
 | 'Tracking_HLT_noHIP_noOOT' | 'HLT_ZeroBias_FirstCollisionAfterAbortGap_v*' |
 ---+++++ *IOV*: 264292-284024
 | *TriggerBits list key* | *HLT paths* |
-| 'SiStrip_HLT' | 'HLT_ZeroBias_v*', 'HLT_HIZeroBias_v*', 'HLT_BptxAnd_*' |
+| 'SiStrip_HLT' | 'HLT_ZeroBias_v*', 'HLT_HIZeroBias_v*', 'HLT_BptxAnd_*', 'HLT_L1SingleMuOpen_v*', 'HLT_PAL1MinimumBiasHF_OR_SinglePixelTrack_*' |
+| 'SiStrip_IB_HLT' | 'HLT_ZeroBias_FirstCollisionAfterAbortGap_*', 'HLT_ZeroBias_IsolatedBunches_v*' |
 | 'SiStrip_L1' | 'L1Tech_BPTX_plus_AND_minus.v0', 'L1_ZeroBias', 'L1_ExtCond_032' |
 | 'Tracking_HLT' | 'HLT_ZeroBias_v*', 'HLT_HIZeroBias_v*', 'HLT_BptxAnd_*' |
 | 'Tracking_HLT_HIP_OOT' | 'HLT_ZeroBias_FirstBXAfterTrain_v*' |
@@ -16,7 +18,8 @@
 | 'Tracking_HLT_noHIP_noOOT' | 'HLT_ZeroBias_FirstCollisionAfterAbortGap_v*' |
 ---+++++ *IOV*: 284025-500000
 | *TriggerBits list key* | *HLT paths* |
-| 'SiStrip_HLT' | 'HLT_ZeroBias_v*', 'HLT_HIZeroBias_v*', 'HLT_BptxAnd_*', 'HLT_L1SingleMuOpen_v*', 'HLT_ZeroBias_FirstCollisionAfterAbortGap_*', 'HLT_ZeroBias_IsolatedBunches_v*', 'HLT_PAL1MinimumBiasHF_OR_SinglePixelTrack_*' |
+| 'SiStrip_HLT' | 'HLT_ZeroBias_v*', 'HLT_HIZeroBias_v*', 'HLT_BptxAnd_*', 'HLT_L1SingleMuOpen_v*', 'HLT_PAL1MinimumBiasHF_OR_SinglePixelTrack_*' |
+| 'SiStrip_IB_HLT' | 'HLT_ZeroBias_FirstCollisionAfterAbortGap_*', 'HLT_ZeroBias_IsolatedBunches_v*' |
 | 'SiStrip_L1' | 'L1Tech_BPTX_plus_AND_minus.v0', 'L1_ZeroBias', 'L1_ExtCond_032', 'L1_MinimumBiasHF0_OR_BptxAND*' |
 | 'Tracking_HLT' | 'HLT_ZeroBias_v*', 'HLT_HIZeroBias_v*', 'HLT_BptxAnd_*', 'HLT_PAL1MinimumBiasHF_OR_SinglePixelTrack_*' |
 | 'Tracking_HLT_HIP_OOT' | 'HLT_ZeroBias_FirstBXAfterTrain_v*' |
```

change in conditions for the IOV for 2012B (the run probed in wf 4.53 is 194533 which falls in the IOV 1-264291) is the same as for the IOV for 2016B (wf 136.731 uses run 274199 which falls in IOV 264292-284024). 

On the other hand as you pointed out there are differences in [4.53](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_9_1_X_2017-03-30-1100+18136/19110/4.53_RunPhoton2012B+RunPhoton2012B+HLTD+RECODR1reHLT+HARVESTDR1reHLT/)
but none in [136.731](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_9_1_X_2017-03-30-1100+18136/19110/136.731_RunSinglePh2016B+RunSinglePh2016B+HLTDR2_2016+RECODR2_2016reHLT_skimSinglePh_HIPM+HARVESTDR2/)....

I am wondering if it is related with the reproducibility issue (to my knowledge not yet solved) detailed in https://its.cern.ch/jira/browse/CMSTRACK-151  (@fioriNTU, @mtosi)

**Comment by franzoni** [comment]
> I am wondering if it is related with the reproducibility issue (to my knowledge not yet solved) 

We've had instability in that folder of plots in all pull requests I've scrutinized this year, irrespective of whether changes effected alcarecos or not.

**Comment by arunhep** [comment]
please test

**Comment by arunhep** [comment]
Description updated with the latest commit for including L1 Prescale and Vetoes for MC.

**Comment by arunhep** [comment]
+1
All the differences observed are expected and has been explained.

**Comment by arunhep** [comment]
@rekovic FYI

**Comment by davidlange6** [comment]
+1

**Pull request merged**
