### PR TITLE
Missing comma after edm::AtomicPtrCache in vector initializer. Adding…

### PR DESCRIPTION
**Pull request by gartung**
… edm::InputTag as safe class

### CODE REVIEW

**Comment by gartung** [comment]
@Dr15Jones @ktf Found the bug that caused edm::AtomicPtrCache to be flagged. On missing comma in list of vector elements.

**Comment by Dr15Jones** [comment]
Please check

**Comment by Dr15Jones** [comment]
Please test

**Comment by Dr15Jones** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
