### PR TITLE
Fix for pixel FED error imbalance in DQM plots

### PR DESCRIPTION
**Pull request by ferencek**
#### PR description:

After recent bug fixes in FED error decoding in the CPU (https://github.com/cms-sw/cmssw/pull/42010) and GPU (https://github.com/cms-sw/cmssw/pull/42618) code, the following imbalance was still present in the `SiPixelHeterogeneous/PixelErrorCompareGPUvsCPU/FEErrorVsFEDIdUnbalance` DQM plot

FEDErrorVsFEDIdImbalance_ref

This imbalance is primarily present because the GPU-based pixel unpacker is not dropping spurious errors assigned to invalid DetIds. Specifically for the timeout error (errorType=29), which consists of two error words, the GPU code was not dropping the 2nd word as is done in the CPU code. This PR therefore additionally synchronizes the FED error handling between the GPU and the legacy CPU code. The same DQM plot with this PR included becomes empty (no imbalance present)

FEDErrorVsFEDIdImbalance_pr

#### PR validation:

The code was tested and the above DQM plots obtained by running the following workflow

`runTheMatrix.py -w gpu -l 141.008583`

recently introduced in https://github.com/cms-sw/cmssw/pull/42674.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Could be backported to 13_2_X if needed.

### CODE REVIEW

**Comment by mmusich** [comment]
test parameters:
   * enable = gpu
   * workflows_gpu = 11634.503, 11634.507, 11634.583, 11634.587, 11634.593
   * relvals_opt_gpu = --what upgrade,standard,highstats,pileup,generator,extendedgen,production,ged,machine,premix,nano
   * addpkg = DQM/Integration

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
@ferencek this looks desireable also for 13.2.X (data-taking release at HLT), would you mind opening a backport?

**Comment by ferencek** [comment]
@mmusich, ok, no problem, I will also make a backport PR.

**Comment by mmusich** [comment]
type bug-fix

**Comment by jfernan2** [comment]
+1

**Comment by rappoccio** [comment]
+1

**Pull request merged**
