### PR TITLE
Phase2-hgx278 Restore back HGCal geometries V11, V12, V13, V14 to its old form 

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Restore back geometries V11,  V12, V13, V14 of HGCal (present in C9, C10, C11, C12, C13, C14 of the calorimeter component and scenarios D49 ... D76) to its old form (orientation of the depleted layer wrt PCB)

#### PR validation:

Use the runTheMatrix test workflows 28234.0, 31834.0, 32634.0

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
The PR description does not sound very good. Why would we want to restore old bugs?

**Comment by cvuosalo** [comment]
I think the comparison differences are explainable. Workflow 140.53 results are just a glitch, 11634.911 has just been added to the tests, and the rest are Phase 2 workflows that are changed as expected by this PR.

**Comment by cvuosalo** [comment]
+1

**Comment by silviodonato** [comment]
@bsunanda this PR is changing `v10/hgcalEE.xml`, `v12/hgcalEE.xml` , `v14/hgcalEE.xml`.
Perhaps you wanted to fix `v13/hgcalEE.xml` instead of `v10/hgcalEE.xml`?

Please note that v10 in the D49 geometry used for the HLT TDR
https://github.com/cms-sw/cmssw/blob/master/Geometry/CMSCommonData/python/cmsExtendedGeometry2026D49XML_cfi.py#L65

**Comment by bsunanda** [comment]
@silviodonato I changed the ones which have been in use. Changing the orientation in #32615 caused some changes and it was felt that it is better not to correct the earlier versions. That is why the corrections are reverted back here. v13 is not a valid directory for hgcalEE.

**Comment by silviodonato** [comment]
Ok, thanks @bsunanda. So you are basically reverting part of https://github.com/cms-sw/cmssw/pull/32932. 
I was confused by the PR title and the PR description quoting `V13`, please fix them

**Comment by bsunanda** [comment]
@silviodonato I made it more explicit

**Comment by srimanob** [comment]
Are we sure to do in this way? It will be difficult to handle changing back and forth, especially on the current baseline detector as a reference. We are now trying to fix the baseline after other changes.

**Comment by bsunanda** [comment]
We discussed about this within HGCal DPG. The results is that we get correct orientation only with newer scenario and do not disturb the legacy ones. That is the reason of making these changes. I hove @rovere can confirm this.

**Comment by rovere** [comment]
Dear all,
I confirm the behaviour restored by this PR is what we would like to have in release for the current production workflows.
FYI @seez

**Comment by srimanob** [comment]
+Upgrade

**Comment by qliphy** [comment]
+1

**Pull request merged**
