### PR TITLE
Backport: Bug fix for multiple detectors in PFRecHitQTestHCALThresholdVsDepth test

### PR DESCRIPTION
**Pull request by hatakeyamak**
#### PR description:

See: https://github.com/cms-sw/cmssw/pull/37219

The PFRecHitQTestHCALThresholdVsDepth test is used for HBHE and HF PFRecHits. It can accept a parameter set vector for threshold cuts, one for each subdetector, but only one set can be saved at a time. This PR extends this class to accommodate parameter sets for multiple detector enums.

#### PR validation:

I haven't done anything specifically for this branch, but https://github.com/cms-sw/cmssw/pull/37219 was merged successfully.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

See discussion on https://github.com/cms-sw/cmssw/pull/37219
The backport was sugggested, so that it will be picked up for Run 3 startup HLT.

@laurenhay @marksan87 @juska @kdlong @silviodonato @missirol

### CODE REVIEW

**Comment by perrotta** [comment]
backport of https://github.com/cms-sw/cmssw/pull/37550

**Comment by perrotta** [comment]
Please notice that this PR changes the reconstruction, by modifying the PF thresholds
Unless it is needed urgently in 12_3_X, and all productions foreseen with that release can wait for it to be merged and a new release cut including it, it should be implemented with a modifier which allows to disable the fix by default

**Comment by hatakeyamak** [comment]
> backport of #37550

Well, backport of See: https://github.com/cms-sw/cmssw/pull/37219, not 37550..

> Please notice that this PR changes the reconstruction, by modifying the PF thresholds Unless it is needed urgently in 12_3_X, and all productions foreseen with that release can wait for it to be merged and a new release cut including it, it should be implemented with a modifier which allows to disable the fix by default

Hmm. I am not sure how to do that.

**Comment by perrotta** [comment]
> > backport of #37550
> 
> Well, backport of See: #37219, not 37550..
> 

Indeed... Thank you
Fixed now

> > Please notice that this PR changes the reconstruction, by modifying the PF thresholds Unless it is needed urgently in 12_3_X, and all productions foreseen with that release can wait for it to be merged and a new release cut including it, it should be implemented with a modifier which allows to disable the fix by default
> 
> Hmm. I am not sure how to do that.

Please arrange it with reco
For sure we cannot merge PRs that change the default reconstruction in a closed release.
We can do so if:
- this can be considered a bug fix (I think so)
- this is considered urgent enough to stop all current productions with 12_3 (none at the moment, I guess) and build a new release after this PR is merged that can be considered the initial CMSSW_12_3_X production release

Of course, everything would have been much smoother if done by the deadline, which was last Friday...

**Comment by hatakeyamak** [comment]
Okay. I will close it. I am sorry that I couldn't act sooner for making a backport PR. It was very busy time for us for a variety of reasons.

**Pull request closed without merging**
