### PR TITLE
[Backport to 130X] Adding Two Secondary Datasets for JME POG

### PR DESCRIPTION
**Pull request by jordan-martins**
Hi, 

Backport of #43534 

Thanks,
Jordan

### CODE REVIEW

**Comment by jordan-martins** [comment]
please test

**Comment by AdrianoDee** [comment]
+pdmv

**Comment by AdrianoDee** [comment]
@jordan-martins could you add a reference to the fact that this is a 13_0_X back port in the title, just for the records.

**Comment by AdrianoDee** [comment]
backport of #43534

**Comment by jordan-martins** [comment]
Ciao @AdrianoDee , like it is now? Please, let me know otherwise. Thanks, Jordan :)

**Pull request merged**
