### PR TITLE
Run2-alca122 Add the method fillDescription to a number of producer classes

### PR DESCRIPTION
**Pull request by bsunanda**
Necessary for future changes in HLT paths

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild please test

**Comment by bsunanda** [comment]
@arunhep @lpernie Can you please approve this PR

**Comment by bsunanda** [comment]
@ghellwig Can you review this PR?

**Comment by lpernie** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
