### PR TITLE
update of HLT-E/Gamma modules to avoid accessing `L1CaloGeometry` unnecessarily

### LINKED ISSUE #36806: Obsolete tags `PCaloGeometry_Castor_v1_hlt` and `L1CaloGeometry_CRAFT09_hlt` still consumed by code
AlCaDB has started the migration of the DD4hep Geometry for the data Global Tags. While doing so, we noticed a couple of very old DDD tags that are included in the online GTs and apparently still consumed. 

The obsolete tags are below:

`PCaloGeometry_Castor_v1_hlt`, from the Castor detector that has been decommissioned.
`L1CaloGeometry_CRAFT09_hlt`, that has not been updated since 2008.

We tried removing them and running on Run-3 data but we observed an unexpected crash because apparently they are still consumed and the code was not updated.

There was a candidate GT prepared with the dd4hep tags and the removal of the tag `PCaloGeometry_Castor_v1_hlt`. This is the diff wrt to the 122X_dataRun3_Prompt_v2 GT where we can see that the Castor tag was removed: https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/122X_dataRun3_Prompt_v2/122X_dataRun3_Prompt_dd4hep_2022_01_25_19_31_04

When running the relval workflow 138.4 (Prompt GT on 2021 PilotBeam data) with the above Candidate GT, we observe the error message below:

```
----- Begin Fatal Exception 25-Jan-2022 20:48:49 CET-----------------------
An exception of category 'NoRecord' occurred while
   [0] Processing global begin Run run: 346512
   [1] Prefetching for module EcalDQMonitorTask/'ecalMonitorTask'
   [2] Prefetching for EventSetup module CaloGeometryBuilder/''
   [3] Calling method for EventSetup module CastorGeometryFromDBEP/''
   [4] While getting dependent Record from Record CastorGeometryRecord
Exception Message:
No "PCastorRcd" record found in the EventSetup.

 Please add an ESSource or ESProducer that delivers such a record.
----- End Fatal Exception -------------------------------------------------
```

A similar thing happens when running on the same workflow with another Candidate GT where the tag `L1CaloGeometry_CRAFT09_hlt` was removed this time: https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/122X_dataRun3_Prompt_v2/122X_dataRun3_Prompt_dd4hep_Candidate_2022_01_25_19_57_39

The error message observed with the above Candidate GT is:

```
----- Begin Fatal Exception 25-Jan-2022 21:06:18 CET-----------------------
An exception of category 'NoRecord' occurred while
   [0] Processing  Event run: 346512 lumi: 250 event: 243042266 stream: 0
   [1] Running path 'L1Reco_step'
   [2] Calling method for module L1ExtraParticlesProd/'l1extraParticles'
Exception Message:
No "L1CaloGeometryRecord" record found in the EventSetup.

 Please add an ESSource or ESProducer that delivers such a record.
----- End Fatal Exception -------------------------------------------------
```

Both error messages indicate that the tags `L1CaloGeometry_CRAFT09_hlt` and `PCaloGeometry_Castor_v1_hlt` are still consumed in the code.

FYI, @tvami @francescobrivio @srimanob

### PR DESCRIPTION
**Pull request by missirol**
resolves https://github.com/cms-sw/cmssw/issues/36806

#### PR description:

This PR updates a couple of HLT-E/Gamma modules in order not to access the `L1CaloGeometry` ES product unnecessarily.

The modules in question come from class templates, and in the original implementation the `L1CaloGeometry` object was created regardless of configuration/template parameters. On the other hand, the `L1CaloGeometry` object is not really needed for configuration/template parameters in use in the Run-3 HLT menu (basically, the `L1CaloGeometry` object is needed when the HLT modules need to use the `l1extra` objects from the Stage-1 L1T, and that is never the case in HLT menus for Run 3).

This update should facilitate the removal of the relevant record from the Run-3 HLT GT (see https://github.com/cms-sw/cmssw/issues/36806 and related issues/PRs).

[ The change in `autoCond` is temporary, and will be removed before integration (I tested wf `139.004` locally w/o the tag `L1CaloGeometry_CRAFT09_hlt`, but this should be tested centrally, and I don't know a better way to do that). ]

Merely technical. No changes expected.

#### PR validation:

`runTheMatrix -l 139.004`, `addOnTests.py`, and verified that all trigger-objects are unchanged for 100 MC events processed with the HLT GRun menu.

#### If this PR is a backport, please specify the original PR and why you need to backport that PR:

N/A

### CODE REVIEW

**Comment by missirol** [comment]
test parameters:

  - workflows = 139.004

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
@missirol can you please update the description by including "resolves https://github.com/cms-sw/cmssw/issues/36806"

**Comment by missirol** [comment]
please test

**Comment by missirol** [comment]
In the first round of tests, the Run-3 HLT GT `123X_dataRun3_HLT_v2` (which does not include any `L1CaloGeometryRecord`) was used, and wf `139.004` passed, confirming that this PR addresses https://github.com/cms-sw/cmssw/pull/36940#issuecomment-1038745243.

The second round of tests confirmed that this PR does not introduce differences in outputs with respect to `master`, and all tested workflows (the default ones + `139.004`) passed.

If this PR is merged, it will automatically close issue https://github.com/cms-sw/cmssw/issues/36806.

**Comment by francescobrivio** [comment]
+alca (for what it's worth)
 - Thanks a lot Marino!
 - I have made an AlCa (self-)reminder here: https://github.com/cms-AlCaDB/AlCaTools/issues/57
 - @missirol do you think we might need this fix for CRAFT and hence a backport to 12_2_X and and new 12_2 release?

**Comment by missirol** [comment]
> do you think we might need this fix for CRAFT and hence a backport to 12_2_X and and new 12_2 release?

Afaiu.. the only problematic situation in `12_2_X` is an HLT menu where (1) one of the modules in this PR is used , _and_ (2) the HLT GT `122X_dataRun3_HLT_v3` is used.

I don't think (1) applies to any of the HLT menus for CRAFT, but we would have to confirm with TSG/FOG. The safest would be to use `122X_dataRun3_HLT_v4` in CRAFT (just like it is being used offline for `12_2_X`) to negate (2). This way one would not need a backport of this PR and a corresponding new release.

**Comment by missirol** [comment]
+hlt

  - see https://github.com/cms-sw/cmssw/pull/36986#issuecomment-1042771094

**Comment by perrotta** [comment]
+1

**Pull request merged**
