### PR TITLE
HLTPrescaler work (92X)

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
HLTPrescaler work (92X)
Implements #19085 and adds useful accessor

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
backport of 19580

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
backport of #19580

**Comment by Martin-Grunewald** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
