### PR TITLE
[DD4hep] Convert production cuts units using DD4hep-invariant method

### PR DESCRIPTION
**Pull request by cvuosalo**
Production cuts are converted to mm for use in Geant4. This PR changes the method of conversion to the DD4hep method so it will work even when the DD4hep units convention changes.

#### PR validation:

Debug output from ` SimG4Core/DD4hepGeometry/test/python/testG4Regions.py` from before and after the PR changes show that the production cuts are unchanged.

A decision on whether to backport to 11_2 will be made later.

### CODE REVIEW

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
@smuzaffar @mrodozov The tests for this PR appear to be stuck. Could you please take a look?

**Comment by smuzaffar** [comment]
the code-checks failed due to disk issues on cmsdev23. I have restarted the code-checks job. Once that is finished successfully then PR tests will start.
[a]
fatal: sha1 file '.git/objects/pack/tmp_pack_BwE8ad' write error: No space left on device

**Comment by civanch** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
