### PR TITLE
remove duplicate of `PropagateToMuon` class

### LINKED ISSUE #37290: Duplication of PropagateToMuon class in MuonAnalysis/MuonAssociators and HLTriggerOffline/Muon
The code to propagate muon tracks from the IP to the second muon station is duplicated in two packages, see https://github.com/cms-sw/cmssw/blob/master/HLTriggerOffline/Muon/interface/PropagateToMuon.h and https://github.com/cms-sw/cmssw/blob/master/MuonAnalysis/MuonAssociators/interface/PropagateToMuon.h 

As they are diverging more and more, with the code in MuonAnalysis/MuonAssociators being developed while the one in HLTriggerOffline/Muon is not, this duplication needs to be resolved. 

This issue is mostly a To-Do for myself, as discussed in #37180

### PR DESCRIPTION
**Pull request by missirol**
resolves #37290

#### PR description:

This PR ~~is an attempt to address issue #37290. It~~ provides an alternative solution to the one in #37348 (FYI: @JanFSchulte).

The idea here is to solve the duplication leaving HLT producers untouched, improving instead the DQM client that uses the ad-hoc duplicate of the `PropagateToMuon` class. Solving the duplication required templating the classes `PropagateToMuonSetup` and `L1MuonMatcherAlgo` in `MuonAnalysis/MuonAssociators`. This avoids changes to all other producers using the latter utilities.

Merely technical. No changes expected.

#### PR validation:

`runTheMatrix.py -l 11634.0`.

#### If this PR is a backport, please specify the original PR and why you need to backport that PR:

N/A

### CODE REVIEW

**Comment by missirol** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by missirol** [comment]
Arbitration with #37348 has been solved in favour of this PR.

**Comment by missirol** [comment]
Kind reminder of this cleanup PR. This is ready for @cms-sw/analysis-l2 and ORP to review.

**Comment by perrotta** [comment]
+1

**Comment by perrotta** [comment]
merge

**Comment by santocch** [comment]
+1

**Pull request merged**
