### PR TITLE
Update DataFormats/DetId package to disable test

### PR DESCRIPTION
**Pull request by mrodozov**
Disable cuda related tests for aarch64 https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc7_aarch64_gcc700/CMSSW_10_2_X_2018-05-31-2300/DataFormats/DetId

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
