### PR TITLE
Use esConsumes in TSGFromL2Muon

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

- Add esConsumes directly in TSGFromL2Muon
- Helper classes used by TSGFromL2Muon expanded to use esConsumes

#### PR validation:

Code compiles.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by jpata** [comment]
+reconstruction
- technical, no relevant reco changes (140.53 is due to DAS differences)
- I only checked the reco-related files

**Comment by sbein** [comment]
Looks like the changes in FastSimulation/* are physics-innocuous. I was a bit surprised by
https://github.com/cms-sw/cmssw/pull/35327/files#diff-54e007ef89d763e4cb77f876b32d85591a51f5a8779a13799a12b6c3c7c8b0dbL367-L374

the fairly large chunk of code just removed. It seems like in the old master, theMeasTracker was not used? I see the same change was made in the FullSim version (RecoMuon/*). Looks fine.

**Comment by sbein** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
