### PR TITLE
[Tk Alignment] Fix validation macro when reading luminosity from external file

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

This PR fixes a logical bug in how the trends vs luminosity are produced by the widely used `MultiRunAndPlotPVValidation` validation macro, when the input luminosity per run are supplied via external file, as reported by @alelek.
I profit of this PR to introduce some better handling of the exceptions and messages.

**N.B.**: the standard way of retrieving the information from the input ROOT file is unaffected.

#### PR validation:

Running the macro with the bug:

image

and without the bug:

image

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Not a backport, might be backported to 11.1.X.

cc:
@connorpa @vbotta

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by yuanchao** [comment]
+alca

**Comment by christopheralanwest** [comment]
+alca

**Comment by silviodonato** [comment]
+1

**Pull request merged**
