### PR TITLE
Run2-alca112 Make a plugin application updated with latest convention

### PR DESCRIPTION
**Pull request by bsunanda**
Also update a few macros for IsoTrack and MIP calibration of HCAL

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@lpernie @arunhep Can you please approve thi

**Comment by lpernie** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
