### PR TITLE
(Backport for 11_1_X) Add plots for displaced muon quantities to uGMT DQM

### PR DESCRIPTION
**Pull request by dinyar**
#### PR description:

In Run-3 displaced muon data are received from BMTF and forwarded to the uGT. This PR adds plots for these quantities to the uGMT DQM.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Backport of #31951 for upcoming MWGR

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
@dinyar  I don't understand why the backport produces empty plots:
https://tinyurl.com/y63ofryc

which the master had with entries:
https://tinyurl.com/y3dnaopm

Another example, backport:
https://tinyurl.com/yxhuo8ho
master:
https://tinyurl.com/yybl8tjv

Any clue?

**Comment by dinyar** [comment]
Hi @jfernan2,

Thanks for the ping! I see that
- the uGMT input plots (named BMTF input) are really not filled for the 11_1_X version (so instead of 1 BMTF muon there's none now)
- the uGMT outputs plots are filled with pT unconstrained of 0 (but 2 muons -- the same as in 11_2_X)

At this point a question to clarify: Is it possible that the data sets are slightly different for 11_1_X and 11_2_X? If so I could imagine that for that 11_1_X wf we just didn't have any muons in the barrel and pT unconstrained only is computed in that area. If not an explanation might be some change in the muon trigger, but from just checking the commit history between 11_1_X and master in the trigger package I can't see anything that would explain it. I'll continue to think about it..

By the way, is there a way to see those plots that match between the PR and base? 

Cheers,
Dinyar

**Comment by jfernan2** [comment]
@dinyar    I don't fully get your last question, you can compare in GUI base vs base+PR, that's what the tiny urls I quoted do, all the comparisons for all the workflows are here:
Master:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_11_2_X_2020-11-02-2300+7a6eb7/39697/dqm-histo-comparison-summary.html
Backport:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_11_1_X_2020-11-05-1100+f7531f/39734/dqm-histo-comparison-summary.html

In principle the workflows are the same in 11_2_X and 11_1_X, i.e. same input files, you can check in the logs:
Master:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-7a6eb7/10469/runTheMatrix-results
Backport:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-f7531f/10533/runTheMatrix-results/

**Comment by dinyar** [comment]
Ah yes, I meant that this DQM only shows those plots that don't match between base and base+PR while I was curious if I could see also those plots that are unchanged. (I could then check if the muon that is missing in the BMTF was now reconstructed e.g. in the OMTF.)

Regarding the workflows, I noticed that for step1 the Pythia version changed between the two releases, but I'm very far from Pythia-competent so I can't tell from the rest of the log if that could have had an effect.

I now ran wf 11634.0 on lxplus with my PR on top of CMSSW_11_1_X_2020-11-05-2300 and looking at the eta-phi map from the uGMT I see the two muons in the overlap/endcap region (|eta| between 1 and 1.4), but nothing in the barrel region so it would make sense that we don't get anything from the BMTF. I then compared this to CMSSW_11_2_X_2020-11-06-1100 where I do see muons in the barrel and corresponding entries for unconstrained pT

So from my side the conclusion is that the plots make sense if the input changed. For reference, I tried to have a look at the plots in the Muon folder and there it to me looks like 11_1_X has two muons reconstructed while 11_2_X has four.

Cheers,
Dinyar

**Comment by jfernan2** [comment]
OK @dinyar thanks for the checks
In the last two links I quoted you also have the DQM root files with all MEs if you want to check, but I see you did yourself recreating the wf.
A change in the Pythia version should not be responsible, but a change in the random seed may lead to a different region where the muons are created, and explain the thing indeed.

**Comment by jfernan2** [comment]
Let me test this PR at Online DQM machines at P5 to see there is not any issue in Online and come back here for approval

**Comment by jfernan2** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
