### PR TITLE
Switch parton flavour in MiniAOD from algorithmic to physics definition 74

### PR DESCRIPTION
**Pull request by ahinzmann**
backport of #10499

Replace in MiniAOD the algorithmic jet flavour by physics jet flavour, that is used for quark/gluon tagging in JetMET.
b-tagging uses the hadron definition which remains untouched in MiniAOD.
Add jetFlavourInfo to ak4 and ak8 jet collections, to be able to identify gluon splitting to bb.
Add lepton matching for identification of hadronic taus.

With this scheme:
b,c can be identified by either j.hadronFlavour() (hadron definition) or j.partonFlavour() (physics definition)
g,u,d,s can be identified by j.partonFlavour() (physics definition)
gluon splitting to bb can be identified roughly by (j.partonFlavour()==21 && len(j.jetFlavourInfo().getbHadrons())==2 )

The size increase (edmEventSize) for MiniAOD (on 1300 ttbar events) when adding JetFlavourInfo and lepton matching is the following:
without JetFlavourInfo:
patJets_slimmedJets__PAT. 32977.1 2663.08
patJets_slimmedJetsAK8__PAT. 1141.85 251.157
with JetFlavourInfo:
patJets_slimmedJets__PAT. 33015.2 2696.82
patJets_slimmedJetsAK8__PAT. 1144.26 252.791
with lepton matching:
patJets_slimmedJets__PAT. 33025.3 2707.15
patJets_slimmedJetsAK8__PAT. 1144.78 253.252

### CODE REVIEW

**Comment by monttj** [comment]
please test

**Comment by monttj** [comment]
+1
b jet definition used for b-tagging is untouched. 
gluon splitting can be identified turning on jet flavor info with small miniAOD size increase.

**Comment by davidlange6** [comment]
closing PRs included in #10649

**Comment by arizzi** [comment]
I do not like very much this, I think people in analysis are used to have
patJet.partonFlavour() returning algorithmic
and
patJet.genParton().pdgId() returning the physics  definition

I think rekeying the genParton, possibly with a white list of matched partons to avoid missing links, would have been a much better solution avoiding a change of meaning for some variables used by many.
Also consider that while official b-tag stuff migrated to hadronDefinition, not everybody using b-tag did migrate and the differences between algoDef and hadronDef are much smaller than phys def vs hadronDef, so this potentially means that people will apply the wrong b-tag SF due to this change

**Comment by ahinzmann** [comment]
Both definitions could be saved if we change here:
https://github.com/ahinzmann/cmssw/blob/partonFlavourMiniAOD/PhysicsTools/PatAlgos/python/mcMatchLayer0/jetMatch_cfi.py#L10
And add status 23 as an option.
I'm personally fine with with.
@ferencek Should we try to save both definitions properly in this way?

**Comment by ahinzmann** [comment]
@gpetruc . I added one more commit which enables (again) keeping algorithmic and physics definition together in MiniAOD:
42c8d8293a9e9bb8b9e5382b6e1ce0ab4c094f1a
Could you include this into #10649 as well?

**Comment by arizzi** [comment]
did you check thay no links are broken? is this directly matching on pruned?
Il 02/set/2015 12:19, "ahinzmann" <notifications@github.com> ha scritto:

**Comment by ahinzmann** [comment]
yes, it is directly matching on pruned and I checked the links.

**Comment by ferencek** [comment]
I think we need to be a bit careful here. Was `genParton()` ever used for JEC purposes or people instead used `partonFlavour()` configured to store the physics definition of the jet flavor? The point is that the two are similar but not identical.

Also, as far as b tagging is concerned, the hadron-based definition should be sufficient. Using the algorithmic definition to distinguish different light-flavor jets is known not to work well and on top of that this is something that cannot be reproduced from MiniAOD (soft partons used in the algorithmic definition are dropped from MiniAOD). Of course, one can say that what is stored in MiniAOD is fine since it was calculated from the full AOD information but because of the two reason mentioned above, one physics-related and the other technical, I don't see a big harm in dropping the parton-based algorithmic definition. Yes, people might be used to using `partonFlavour()` but with a clear set of instructions, problems can be avoided (this type of change is for sure less drastic that the AOD->MiniAOD switch).

**Comment by arizzi** [comment]
since Run1 people use genParton for physics definition and partonFlavour (without reconfiguring) for algorithmic.
I think changing meaning to existing functions is not good habit given that we have the option to keep both.
The point is that the clear set of instruction may not reach the destination.
There are plenty of things we cannot reproduce in miniaod and usually this is a good reason to store them rather than drop them.
The physics definition is ill-defined and more generator dependent and taking it as default is not a good idea.

One thing I do  not understand is if we are really using full AOD inputs or just prunedGenParticles... Andreas seems to say the opposite of what you say...

ciao
andrea

**Comment by ahinzmann** [comment]
In this PR it is configured to used pruned gen particles as input to to genParton and partonFlavor, mainly to have access to the hadrons in the jet flavor info product:
https://github.com/cms-sw/cmssw/pull/10750/files#diff-76dede28e7751d7bb6c5c9542de4155cR239
-> the algorithmic flavor definition is reproducible, but non optimal

**Comment by arizzi** [comment]
ok, thanks for the clarificiation.

About not being optimal, I fail to see how matching a 30 GeV jet to a randomly picked up gluon of 4 GeV could make it "more optimal"

**Comment by ferencek** [comment]
Before this PR JetFlavourInfo (stores references to matched partons/hadrons) was not stored so there was no issue with rekeying, etc. And the full `GenParticles` collection was used as input. Now, with the switch to the `prunedGenParticles` collection, all the references are already properly set but there is some loss of information present (on the other hand, things are now reproducible from MiniAOD which is maybe a good thing).

**Comment by ferencek** [comment]
@arizzi, concerning the "optimal" comment, that was the main point of my initial comment and why I was fine with dropping something that was anyways ill-defined from the physics point of view. It can be "more optimal" only from the technical point of view. From the physics point of view, it remains pretty much as ill defined as before.

**Comment by arizzi** [comment]
well, the "physics definition" is more ill-defined than the "algorithm definition". While the latter let not well defined what is a gluon vs quark vs not-ID, the first one has also the "b jet" definition messed up: b originating from PS are not b... depending on the matching schema needed by a given generator you get a different answer.
So using physics definition should be really limited to people really knowing what they are dealing with and switching the default to that doesn't look too good to me.

**Comment by ferencek** [comment]
Also, for some generators hard partons  are not even in the lab frame which makes the "physics definition" even more problematic. I guess what we have now with the latest updates from Andreas is the best possible compromise given all the existing constraints.

**Comment by arizzi** [comment]
as #10649 was merged can you make a new PR against 76X branch directly?
Il 04/set/2015 07:42, "Dinko Ferencek" <notifications@github.com> ha
scritto:

**Comment by ferencek** [comment]
I think @ahinzmann will take care of that. In fact, I'm not sure if #11076 will be automatically forward ported to 76X.

**Comment by arizzi** [comment]
sorry I meant 74X!
Il 04/set/2015 07:56, "Dinko Ferencek" <notifications@github.com> ha
scritto:

**Comment by ferencek** [comment]
74X PR is already in place. It is #11077.

**Pull request closed without merging**
