### PR TITLE
Remove left over uGMT ZS configuration

### PR DESCRIPTION
**Pull request by dinyar**
#### PR description:

This removes some left over calls to modules that were removed in #38115.

cc @pmandrik and @vukasinmilosevic 

#### PR validation:

None should be required beyond the ones run in this MR.

### CODE REVIEW

**Comment by dinyar** [comment]
Hi @pmandrik,

This should fix the issue in [0] that you reported. Can you let me know if you need a backport too?

Cheers,
Dinyar

[0] https://cmsweb.cern.ch/dqm/dqm-square-k8/api?what=get_logs&id=dqm-source-state-run512714-hostfu-c2f11-15-04-pid026703&db=playback

**Comment by emanueleusai** [comment]
type trigger

**Comment by emanueleusai** [comment]
type l1t

**Comment by emanueleusai** [comment]
please test

**Comment by emanueleusai** [comment]
@dinyar yes, could you please provide 12_5 and 12_4 backports? Thanks!

**Comment by emanueleusai** [comment]
please test

- retest, relvals timed out

**Comment by dinyar** [comment]
> @dinyar yes, could you please provide 12_5 and 12_4 backports? Thanks!

Ok, done in #40163 and #40164.

**Comment by emanueleusai** [comment]
+1

**Comment by rappoccio** [comment]
+1

errors are spurious.

**Pull request merged**
