### PR TITLE
Run3-gem54 Make DT geometry building triggered by same set of parameters to switch between DDD and DD4Hep

### PR DESCRIPTION
**Pull request by bsunanda**
### PR description:

Make DT geometry building triggered by same set of parameters to switch between DDD and DD4Hep

#### PR validation:

Test using runTheMatrix workflows

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@slomeo @cvuosalo @ianna I added this PR so that can change the builder from DDD to DD4Hep with the same procedure as for other detectors. Step2 did not work after Gabrielle's fix. I shall now try with this fix.

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
