### PR TITLE
add protection for rare infinite loop in ecal multifit (75X)

### PR DESCRIPTION
**Pull request by bendavid**
backport of https://github.com/cms-sw/cmssw/pull/11204 to 75x

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
I started tests manually from the jenkins interface

**Comment by cvuosalo** [comment]
+1

For #11207 15ca232cd211415129496dd0a2aff23728f425d7

Bug fix for rare infinite loop in ECAL multifit. There should be no change in monitored quantities. #11205 and #11204 are the 74X and 76X versions of this PR, and they have already been approved by Reco.

The fixed code is satisfactory, and Jenkins tests against baseline CMSSW_7_5_X_2015-09-09-2300 show no significant differences, as expected. The bug fix was verified for #11205.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
