### PR TITLE
Followup of switch to TauId MVA2017v2 for UL

### PR DESCRIPTION
**Pull request by mbluj**
#### PR description:

This PR adds VVLoose working points (WPs) of two species of the MVA2017v2 TauID which were forgotten in #26541; it is backport of #26824.

#### PR validation:
Matrix tests are running, but any surprise is expected as content of the PR is identical to #26824 which was tested with very same conditions.

#### if this PR is a backport please specify the original PR:
It is backport of #26824 to 10_6_X for UL.

### CODE REVIEW

**Comment by perrotta** [comment]
backport of #26824

**Comment by perrotta** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/26859  9e9d485
- the backport from (https://github.com/cms-sw/cmssw/pull/26824	cd5b47f) is correct: the changes in the code are the same
- jenkins tests pass and comparisons show the same changes only reflecting additional tau IDs saved in RECO/AOD and in miniAOD.

**Comment by santocch** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
