### PR TITLE
DQM module fixes for SUSY JetIdCleaned paths (CMSHLT-482:Reopened)

### PR DESCRIPTION
**Pull request by mrcarver**

### CODE REVIEW

**Comment by deguio** [comment]
this doesn't merge apparently. please rebase.

**Comment by mrcarver** [comment]
@deguio In my version control software ineptitude I was unable to rebase properly. However, I've redone the work on a different branch and the comparison done by git before opening a PR says it can be merged automatically. Should I close this PR and open a new one or can you use the new branch 'UpdateFix76' to complete this one? Thanks for your help.

**Comment by deguio** [comment]
ciao @mrcarver 
you can close this one and open a new one.
thanks,
F.

**Comment by deguio** [comment]
-1
waiting for a new PR

**Comment by mrcarver** [comment]
Closing this PR in favor of new one just opened #11533

**Pull request closed without merging**
