### PR TITLE
GEM validation package update

### PR DESCRIPTION
**Pull request by dildick**
#### PR description:

This PR is a big update of the GEM validation packages. Among others it updates old plots, removes redundant ones, introduces validation plots for GEM pad clusters and puts plugins in the correct directories. 

#### PR validation:

This PR was tested with workflow 22021.0.

Validation plots can be found here: 
- https://indico.cern.ch/event/889918/contributions/3752954/attachments/1989496/3316341/GEM_200218_Validation-SW.pdf
- https://indico.cern.ch/event/891703/contributions/3761082/attachments/1993812/3325504/200226_GEM_Validation-SW.pdf

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

@jshlee @seungjin-yang

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by seungjin-yang** [comment]
Additional PR description

1. Correct the definition of pull on the local position of GEMRecHit.
[Official cmssw](https://github.com/cms-sw/cmssw/blob/master/Validation/MuonGEMRecHits/src/GEMRecHitsValidation.cc#L163-L166) use GEMRecHit::localPositionErrorr().xx() as the denominator.
[This PR](https://github.com/dildick/cmssw/blob/GEM-Digi-Matching-v6_CMSSW_11_1_0_pre3/Validation/MuonGEMRecHits/plugins/GEMRecHitValidation.cc#L269-L276) use sqrt(GEMRecHit::localPositionErrorr().xx())

2. Change the definition of efficiency plots from the fraction of the simulated muon tracks that are associated with GEMDigi or GEMRecHit to the fraction of the simulated muon hits (PSimHIt) with an associated GEMDigi or GEMRecHit.

**Comment by jfernan2** [comment]
@dildick you have CMSSW code rule issues:
Search for "using namespace" or "using std::" in header files

/Validation/MuonGEMHits/interface/GEMBaseValidation.h
[19]
/Validation/MuonGEMHits/interface/GEMValidationUtils.h
[14]

**Comment by dildick** [comment]
@jfernan2 Thanks for bringing that to my attention.

**Comment by jfernan2** [comment]
Thanks @dildick  but now it seems you have introduced blank spaces according to cmsbuild. Please apply the patch sugested above. Thanks

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
@dildick most of the aded histograms are empty, I understand that the physics processes tested in these workflows are not suited to GEM. 
I guess WF 22021.0  is the optimal for GEM, but this is not being tested here. I waited ZMM 10042 would have given some hits in GEM, but it seems not.
Nevertheless, given that some plots get entries (at least 1) and the validation you performed on 22021.0, I consider the PR is OK to go.
Please let me know if you spot any further issue:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_11_1_X_2020-02-26-2300+b69bee/35272/dqm-histo-comparison-summary.html

**Comment by jfernan2** [comment]
@dildick most of the added histograms are empty, I understand that the physics processes tested in these workflows are not suited to GEM. 
I guess WF 22021.0  is the optimal for GEM, but this is not being tested here. I waited ZMM 10042 would have given some hits in GEM, but it seems not.
Nevertheless, given that some plots get entries (at least 1) and the validation you performed on 22021.0, I consider the PR is OK to go.
Please let me know if you spot any further issue:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_11_1_X_2020-02-26-2300+b69bee/35272/dqm-histo-comparison-summary.html

**Comment by dildick** [comment]
@seungjin-yang @jshlee Do you have anything to add to this PR?

**Comment by seungjin-yang** [comment]
No. I'm happy with this PR.

**Comment by jfernan2** [comment]
+1

**Comment by silviodonato** [comment]
please test workflow 22021.0

**Comment by silviodonato** [comment]
@dildick do you have a PR to add WF  22021.0? I cannot find it with `runTheMatrix.py -n`

**Comment by dildick** [comment]
@seungjin-yang Could you please comment? WF 22021.0 does not appear to exist.

**Comment by seungjin-yang** [comment]
@silviodonato I used `runTheMatrix.py-w upgrade -l 22021.0` The geometry used is GeometryExtended2026D46.

**Comment by silviodonato** [comment]
right, we cannot test wf in `-w upgrade` (see https://github.com/cms-sw/cmssw/pull/28773#issuecomment-576795773)

**Comment by silviodonato** [comment]
+1

**Comment by silviodonato** [comment]
merge

**Pull request merged**
