### PR TITLE
GEM in DCS HV bits

### PR DESCRIPTION
**Pull request by quark2**
#### PR description:
This PR adds rows for GEM systems in the DCS HV onlineDQM plot. Only inputs from softFED(1022) are equipped, while the input from FED735 is not realized since there are no GEM bits in SCAL system.

#### PR validation:
Test are done and one can check again by `runTheMatrix` workflows

@jshlee @watson-ij

### CODE REVIEW

**Comment by jfernan2** [comment]
@quark2 since we need to test this in Online DQM at P5, could you please make a backport to 12_0_X?
Thanks

**Comment by jfernan2** [comment]
please test

**Comment by quark2** [comment]
Hi @jfernan2, 

Sure, I'll make it soon. Thanks!

Best regards, 
Byeonghak Ko

**Comment by quark2** [comment]
For DAQ & reconstruction people, the change on DataFormats/OnlineMetaData/src/DCSRecord.cc is due to the mismatch with these lines: https://github.com/cms-sw/cmssw/blob/master/DataFormats/OnlineMetaData/interface/DCSRecord.h#L50-L51.

**Comment by quark2** [comment]
For DAQ & reconstruction people, the change on DataFormats/OnlineMetaData/src/DCSRecord.cc is due to the mismatch with these lines: https://github.com/cms-sw/cmssw/blob/master/DataFormats/OnlineMetaData/interface/DCSRecord.h#L50-L51.

**Comment by smorovic** [comment]
+1

**Comment by smorovic** [comment]
@quark2, @jfernan2,
GEM bits are not yet filled by DAQ (RU), however. Plan is to introduce this with the switch to DAQ3, possibly beginning of October. Andrea Petrucci is the person working on this from DAQ event-builder side.

**Comment by jpata** [comment]
+reconstruction
- given the DAQ sig above, reco has nothing to add here (only DataFormats/OnlineMetaData changed)

**Comment by jfernan2** [comment]
+1
Backport in 12_0_X tested in ONline DQM at P5

**Comment by perrotta** [comment]
+1

**Pull request merged**
