### PR TITLE
do not fetch `PixelClusterCountsInEvent` when the handle is not valid

### LINKED ISSUE #37685: ProductNotFound exception in AlcaPCCIntegrator in workflow 1001.2
Workflow 1001.2 step 2 is failing in CMSSW_12_4_X_2022-04-26-1100 with
```
----- Begin Fatal Exception 26-Apr-2022 13:15:01 CEST-----------------------
An exception of category 'ProductNotFound' occurred while
   [0] Processing  Event run: 305064 lumi: 2 event: 1783800 stream: 0
   [1] Running path 'pathALCARECOAlCaPCCRandom'
   [2] Calling method for module AlcaPCCIntegrator/'alcaPCCIntegratorRandom'
Exception Message:
Principal::getByToken: Found zero products matching all criteria
Looking for type: reco::PixelClusterCountsInEvent
Looking for module label: hltAlcaPixelClusterCounts
Looking for productInstanceName: alcaPCCEvent

   Additional Info:
      [a] If you wish to continue processing events after a ProductNotFound exception,
add "SkipEvent = cms.untracked.vstring('ProductNotFound')" to the "options" PSet in the configuration.

----- End Fatal Exception -------------------------------------------------
```
https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc10/CMSSW_12_4_X_2022-04-26-1100/pyRelValMatrixLogs/run/1001.2_RunZeroBias2017F+RunZeroBias2017F+TIER0EXPRUN2+ALCAEXPRUN2+ALCAHARVDSIPIXELCAL+ALCAHARVDSIPIXELCALLA/step2_RunZeroBias2017F+RunZeroBias2017F+TIER0EXPRUN2+ALCAEXPRUN2+ALCAHARVDSIPIXELCAL+ALCAHARVDSIPIXELCALLA.log#/

### PR DESCRIPTION
**Pull request by mmusich**
resolves https://github.com/cms-sw/cmssw/issues/37685

#### PR description:

Trivial fix for  https://github.com/cms-sw/cmssw/issues/37685. Profited to make some clean-up of the class.

#### PR validation:

step2 of 1001.2 runs after the fix

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

### CODE REVIEW

**Comment by tvami** [comment]
test parameters:
  - workflows = 1001.2

**Comment by mmusich** [comment]
do we have a wf to test when the product is avaiable?

**Comment by mmusich** [comment]
e.g. 1020?

**Comment by tvami** [comment]
> e.g. 1020?

Yes, I added that to the wf-s

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
+alca
 * https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-b2b54c/24279/runTheMatrix-results/1001.2_RunZeroBias2017F+RunZeroBias2017F+TIER0EXPRUN2+ALCAEXPRUN2+ALCAHARVDSIPIXELCAL+ALCAHARVDSIPIXELCALLA/ runs
 * https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-b2b54c/24279/runTheMatrix-results/1020.0_AlCaLumiPixels2021+AlCaLumiPixels2021+TIER0EXPLP+ALCAEXPLP+ALCAHARVLP+TIER0PROMPTLP/. runs

**Comment by qliphy** [comment]
+1

**Comment by qliphy** [comment]
thanks @mmusich Please also backport to 12_3_X or include it in https://github.com/cms-sw/cmssw/pull/37671

**Comment by tvami** [comment]
@qliphy to make things quicker, I submitted the backport: https://github.com/cms-sw/cmssw/pull/37720

**Pull request merged**
