### PR TITLE
Combined backport of PR #19205 and #19404: ootPhotons in miniAOD from AOD from either 92X or 80X inputs

### PR DESCRIPTION
**Pull request by kmcdermo**
Backport of both PR #19205 and #19404 for 92X.  Both have been merged into 93X.

19205: ootPhotons in miniAOD from AOD (if ootPhotons produced during RECO step)
19404: ootPhotons in miniAOD from 80X AOD (run a era-specific customized ootPhoton RECO step, then run the PAT step to produce ootPhotons in miniAO)

### CODE REVIEW

**Comment by slava77** [comment]
@kmcdermo 
please edit the title of the PR to be more descriptive
Thank you.

**Comment by kmcdermo** [comment]
@slava77 
can this PR be tested now for the backport?

**Comment by perrotta** [comment]
please test

**Comment by arizzi** [comment]
@kmcdermo @davidlange6 are the 92X relval already containing the ootPhotons at RECO level so this should work out of the box?

**Comment by kmcdermo** [comment]
@arizzi 
yes, indeed, this was included:
https://github.com/cms-sw/cmssw/pull/19448/commits/175981a474887112d3760aac99116047be3e00fb

so it will pick up the relvals from 92X with ootPhotons already at AOD.

**Comment by arizzi** [comment]
mhh... then why recent 93X IB (containing the other PR) fail on 92X relval with
30-Jun-2017 16:48:45 CEST  Successfully opened file root://eoscms.cern.ch//eos/cms/store/relval/CMSSW_9_2_1/RelValTTbar_13/GEN-SIM-RECO/PU25ns_92X_upgrade2017_realistic_v1-v1/10000/0C07A2DB-594A-E711-A1FF-0025905A6134.root
Begin processing the 1st record. Run 1, Event 7607, LumiSection 153 at 30-Jun-2017 16:49:19.603 CEST
----- Begin Fatal Exception 30-Jun-2017 16:49:32 CEST-----------------------
An exception of category 'ProductNotFound' occurred while
   [0] Processing  Event run: 1 lumi: 153 event: 7607 stream: 0
   [1] Running path 'MINIAODSIMoutput_step'
   [2] Prefetching for module PoolOutputModule/'MINIAODSIMoutput'
   [3] Calling method for module ReducedEGProducer/'reducedEgamma'
Exception Message:
Principal::getByToken: Found zero products matching all criteria
Looking for type: std::vector<reco::Photon>
Looking for module label: ootPhotons
Looking for productInstanceName:

**Comment by kmcdermo** [comment]
@arizzi 

Where is this file getting picked up?  ootPhotons at AOD were added into 9_2_2, and this is a 9_2_1 sample, so that test needs to be updated.

**Comment by arizzi** [comment]
that was my test, not something central. so not any 92X is ok, should be >=922 (will try this)

**Comment by slava77** [comment]
as noted in https://github.com/cms-sw/cmssw/pull/19404#issuecomment-312440739
we will need the legacy reminiAOD part combined with this PR for 92X integration.

**Comment by slava77** [comment]
@kmcdermo 
is this backport done, or is it still in the middle of commits and tests?

**Comment by kmcdermo** [comment]
@slava77 
please let me test locally first to make sure I did not break anything, but otherwise these are all the commits that are needed.

**Comment by kmcdermo** [comment]
backport of #19205

**Comment by kmcdermo** [comment]
@slava77 
Okay, tested locally on an 80X AOD file, and it worked (produced ootPhotons) .

Let me know if you want me to squash any of these commits.  I just rebased this branch, then cherry-picked the seven commits from 19404 on top.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by kmcdermo** [comment]
ping on this PR

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/19448	321d0bb
- changes in the code in this PR are identical to the combination of #19205 06ec2b4 and #19404 73da687; both are present in 930pre1 and apparently have not produced any issues there
- jenkins tests pass and comparisons with baseline show differences only in the reducedEgamma reducedEBrechits, where some increment is expected; based on a copy of jenkins outputs in 136.731 I also can confirm that the expected new products are present (slimmedOOTPhotons and reducedEgamma\_\*OOT\*Clusters)

**Comment by davidlange6** [comment]
merge

**Pull request merged**
