### PR TITLE
Update SiPM parameters and fix a few bugs in hardcode conditions

### PR DESCRIPTION
**Pull request by kpedro88**
The major change in this PR is new SiPM parameters (gain, photoelectronsToAnalog, dark current, crosstalk). We were informed about a month ago by the hardware experts that the SiPMs were run with an effective overvoltage of ~4.4V during test beam, but subsequent studies found that an overvoltage of 3V maximized signal to noise. Many SiPM parameters depend on voltage, so they need to be updated from the initial testbeam analysis to get better agreement with expected running conditions.

We were sent some pedestal runs from b904, which I analyzed (with the help of numerous experts) to get an average set of parameters. Slides detailing this analysis can be found here: [sipm_condition_analysis.pdf](https://indico.cern.ch/event/586254/contributions/2361862/attachments/1366614/2073007/sipm_condition_analysis.pdf).

I also fixed a few minor bugs:
1) Way back in #13861, I dumped run2_mc parameters for HCAL and made per-subdetector averages to use as defaults for the hardcode conditions (for development purposes only). At the time, I didn't realize database pedestal values were in ADC, rather than the fC values assumed by the hardcode conditions. This PR adjusts the average values so they're actually in fC (using functionality from #16499). Again, this is for development only, and has no impact on any official workflows or results.
2) Also back in #13861, I didn't account for depths 3 and 4 for HF when assigning gains, leading to a very minor discrepancy (depth 4 has gain=0.14 instead of 0.135). This has been fixed and will be updated in the database.

@abdoulline, I hope we can update all the database conditions at once...

@lihux25, it might be necessary to recheck the ZS thresholds with the new parameters. I would suggest not rerunning the whole study, but just check the existing "best" threshold you found, and then a slightly higher or lower value (to see how things change). To use the hardcode conditions in your config, merge this PR (in any recent IB) and then:
```
from SLHCUpgradeSimulations.Configuration.HCalCustoms import load_HcalHardcode
process = load_HcalHardcode(process)
process.es_hardcode.useHEUpgrade = cms.bool(True)
process.es_hardcode.useHFUpgrade = cms.bool(True)
```

### CODE REVIEW

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
are there any physics signal response plots to go with this PR?

**Comment by abdoulline** [comment]
@mazarkin

   OK, lets proceed with 2017 conditions update...

**Comment by kpedro88** [comment]
@slava77 the hardcode conditions are used directly for Phase2, so to start we can look at those comparisons, e.g. from D5:



This shows the expected decrease in noise. I'll try to make some kind of 2017 single pion scan or something today.

**Comment by slava77** [comment]
On 11/9/16 8:56 AM, Kevin Pedro wrote:
> @slava77 <https://github.com/slava77> the hardcode conditions are used
> directly for Phase2, so to start we can look at those comparisons, e.g.
> from D5:
> 
> <https://camo.githubusercontent.com/7fe1b3ea358b20a9de657baa331eaac04400e45d/687474703a2f2f7777772e6b6a706c616e65742e636f6d2f70722f616c6c5f4f6c6456534e65775f54546261723133546556323032334435776632333232347030635f6c6f6731304842484552656348697473536f727465645f686268657265636f5f5f5245434f5f6f626a5f6f626a5f656e657267792e706e67>
> 

What does this plot say about response to real hits?

**Comment by kpedro88** [comment]
To me the new (red) distribution around 1 GeV looks narrower than the old (black) distribution, which I would expect from reduced noise. But as I said, I'll make more plots.

**Comment by civanch** [comment]
+1

**Comment by kpedro88** [comment]
@mariadalfonso the gain change here may require a retuning of the M2 1pulse/3pulse cut. (Could be worthwhile to make this database-dependent, if we always want to change at 20 GeV, then the corresponding fC value can be calculated automatically.)

**Comment by kpedro88** [comment]
@slava77 I ran 1000 50 GeV pions aimed at the endcap and collected HCAL RecHit energy in a cone of dR < 0.3 around the generated pions (selecting events with ECAL energy < 1 GeV). I observe an improvement in the response and resolution, as expected from the motivation for the new parameters (optimize S/N with lower overvoltage). (Blue fit goes with black histo, magenta fit goes with red histo.)

**Comment by slava77** [comment]
On 11/9/16 1:09 PM, Kevin Pedro wrote:
> @slava77 <https://github.com/slava77> I ran 1000 50 GeV pions aimed at
> the endcap and collected HCAL RecHit energy in a cone of dR < 0.3 around
> the generated pions (selecting events with ECAL energy < 1 GeV). I
> observe an improvement in the response and resolution, as expected from
> the motivation for the new parameters (optimize S/N with lower
> overvoltage). (Blue fit goes with black histo, magenta fit goes with red
> histo.)


Strange
If S/N is better, then there should be less noise hits and the total
energy in the cone should go down.
So, your plot tells me that M2 energy went up by more than 7%
(7% from 49.72/46.5 and "more than" from the reduced noise)

If mean M2 energy is higher by more than 7% then we likely lost the
response quality from
what we had in 15959
http://dalfonso.web.cern.ch/dalfonso/DarkCurrentOnSiPM_PR15959.pdf
slide 5

**Comment by kpedro88** [comment]
Hm, I see your point about the response. It could be due to the point I realized earlier today, which is that the 1pulse-vs-3pulse cut in M2 needs to be adjusted (but I'm not sure where that cut is made in the code: @mariadalfonso, can you point it out?).

Here is M2 vs M0 before this PR:


and after this PR:

**Comment by abdoulline** [comment]
We've briefly discussed it in some thread with Maria yesterday 
("810pre15_2017 relval followup" thread):

ts4Max = (100.,70000.)
http://cmslxr.fnal.gov/source/RecoLocalCalo/HcalRecProducers/python/HBHEMethod2Parameters_cfi.py#0011

ts4Max[1] usage :
http://cmslxr.fnal.gov/source/RecoLocalCalo/HcalRecAlgos/src/PulseShapeFitOOTPileupCorrection.cc#0567

**Comment by kpedro88** [comment]
@abdoulline thanks, I reran with these adjustments in my config file:
```
process.hbheprereco.algorithm.ts4Max = cms.vdouble(100.,44650)
process.hbheprereco.algorithm.pedSigmaSiPM = cms.double(0.000659)
```
(I could add them to this PR also, but they won't make sense for central WFs until we have tags with the new params, so I'll hold off for now.)

The results went the opposite way we wanted...


But M2 vs M0 looks more like before (though there's some spread at the very low end that could throw off the resolution, should be investigated):


And if we look directly at the hcal/(p-ecal) quantity that @mariadalfonso usually shows, the scale looks okay:

so maybe that's a better measure.

**Comment by kpedro88** [comment]
@mmusich please sign when you get back (corresponding changes already present in the database from #16544...)

**Comment by mariadalfonso** [comment]
@slava77 @kpedro88 
I'm making a separate PR with the M2 adjustment to follow up on this and other little things

**Comment by slava77** [comment]
since this one is not approved yet, it may be more practical to have all changes in one go

**Comment by kpedro88** [comment]
@slava77 as I pointed out, the corresponding db conditions are already approved and merged. The changes here are for HCAL development and only directly affect Phase2. I would prefer to get this PR merged and then have a separate PR for M2 tuning.

**Comment by kpedro88** [comment]
@mmusich please sign

**Comment by mmusich** [comment]
+1
apologies for delay

**Comment by davidlange6** [comment]
+1

**Pull request merged**
