### PR TITLE
Update Phase2TrackerDigitizerAlgorithm.cc (LogInfo -> LogTrace)

### PR DESCRIPTION
**Pull request by suchandradutta**
Updated Phase2TrackerDigitizerAlgorithm.cc changing LogInfo to LogTrace as it is suggested 

#### PR description:

<!-- Please replace this text with a description of the feature proposed or problem addressed, specifying:
 Trivial change to suppress  Info messages. Not dependent on other PRs

### CODE REVIEW

**Comment by kpedro88** [comment]
resolves #29001

**Comment by kpedro88** [comment]
please test

**Comment by kpedro88** [comment]
+upgrade
Comparison differences are unrelated to this PR

**Comment by civanch** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
