### PR TITLE
Add index to primary vertex in scouting particle collection

### PR DESCRIPTION
**Pull request by davidsheffield**

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
Please make (backport) PRs for 74X and 75X.

**Comment by Martin-Grunewald** [comment]
+1

**Comment by davidsheffield** [comment]
I was told that I needed to keep the checksum for the previous version of this class. Hence 452de30.

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Pull request merged**
