### PR TITLE
move to 2015_50ns_v1 L1 menu, and use new HLT customisation style

### PR DESCRIPTION
**Pull request by fwyzard**
This PR applies #8411 on top of #8439 .

I left #8439 open, in case the test succeed there but fail here.

### CODE REVIEW

**Comment by davidlange6** [comment]
@cmsbuild, please test

**Comment by fwyzard** [comment]
@davidlange6 : #8411 was already signed by core and fastim, and there are no further changes on top of those, so you might bypass those signatures here

**Comment by Dr15Jones** [comment]
+1

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by fwyzard** [comment]
this should again be in sync with #8439, as
of c014d7d3c7049a89abaeeef701a2af7d6842cebf .

**Comment by fwyzard** [comment]
+1

**Pull request merged**
