### PR TITLE
Replace `trackingMkFit` with `trackingMkFitDevel` modifier

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

The `trackingMkFit` process modifier is of historic origin and it's not actively used in any production code, though it is used in the RelVal workflows `xxxxx.7`.
I remove it here as it can create confusions, as well as updating the documentation and one configuration file that relied on it and replace it with a new modifier called `trackingMkFitDevel` which activates the mkFit replacement for all the tracking iterations (as per suggestion at https://github.com/cms-sw/cmssw/pull/38389#issuecomment-1157568904)
I profit of this PR to introduce a unit test for `testDumpMkFitGeometry`.

#### PR validation:

Run successfully `runTheMatrix.py -l 11634.7`
Also, the added unit test is running.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

### CODE REVIEW

**Comment by mmusich** [comment]
@slava77 @mmasciov @osschar please review.

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
>  a modifier that by defaults enables mkFit in all iters, which can be also tested in the .7 workflow.

ah OK, I see now it's used here:

https://github.com/cms-sw/cmssw/blob/96319c91b5e586ea9fe125136aeea3272c93961d/Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py#L370-L372

so the preference there is to run all iterations in the step3 of the .7 wfs?

**Comment by slava77** [comment]
> so the preference there is to run all iterations in the step3 of the .7 wfs?

it's not a strong preference, but more of a way to make the .7 workflow more useful than just checking the same setup as in step3 of the default .0 already.

**Comment by mmusich** [comment]
> it's not a strong preference, but more of a way to make the .7 workflow more useful than just checking the same setup as in step3 of the default .0 already.

OK, I tried to implement it at [e37315d](https://github.com/cms-sw/cmssw/pull/38389/commits/e37315d4c76a13d0a390d15ba4a56a0afc162751) and tested it with  11634.7. It works.

**Comment by mmusich** [comment]
please test

**Comment by slava77** [comment]
> Reco comparison results: 1734 differences found in the comparisons

all differences are in 11634.7, which was  changed in the implementation; that's expected.

**Comment by srimanob** [comment]
+Upgrade

Mostly technical on name change for `trackingMkFit` modifier. Additional unit test is added.

**Comment by mmusich** [comment]
@cms-sw/pdmv-l2 kind ping.

**Comment by kskovpen** [comment]
+pdmv

**Comment by perrotta** [comment]
+1

**Pull request merged**
