### PR TITLE
backport of solve mg5 /tmp problem from ExternalLHEProducer

### PR DESCRIPTION
**Pull request by perrozzi**
backport of https://github.com/cms-sw/cmssw/pull/23004

### CODE REVIEW

**Comment by perrozzi** [comment]
@kpedro88 this patch is pretty important to restart injecting PhaseII and in general MG5_aMC requests.
If you could kindly merge it at your earliest convenience and prepare a 939p1 asap, we would be really (really) grateful. Let us know if you see any issue

**Comment by kpedro88** [comment]
@perrozzi it would have been easier if I had known about this before making 9_3_9...

**Comment by kpedro88** [comment]
merge

**Comment by perrozzi** [comment]
@kpedro88 really sorry about that, it wasn't clear if the PR would have fit in CMSSW and I wasn't aware of the incoming release

**Pull request merged**
