### PR TITLE
[13_1_X] Add FastTimer and Throughput Services to HLT P2 timing menu.

### PR DESCRIPTION
**Pull request by rovere**
#### PR description:

Backport of #42934

#### PR validation:

Tested locally on top of `13_1_1`.

### CODE REVIEW

**Comment by rovere** [comment]
please test

**Comment by mmusich** [comment]
@rovere please edit the title such that it's clear what's the target branch

**Comment by mmusich** [comment]
backport of #42934

**Comment by mmusich** [comment]
please test
   * let's try again

**Comment by mmusich** [comment]
+hlt
   * see https://github.com/cms-sw/cmssw/pull/42934#issuecomment-1746277664

**Pull request merged**
