### PR TITLE
Adding PUPPI jets and METs to offline DQM - backport to 14_0_X

### PR DESCRIPTION
**Pull request by rseidita**
#### PR description:

Adding the PUPPI collection for both jets and METs to the offline DQM JetMET sequence, as presented [here](https://indico.cern.ch/event/1386418/#3-updates-on-puppi-for-dc).

#### PR validation:

```
echo '{
"369978" : [[1, 800]]
}' > step1_lumiRanges.log  2>&1

(dasgoclient --limit 0 --query 'lumi,file dataset=/JetMET0/Run2023D-v1/RAW run=369978' --format json | das-selected-lumis.py 1,800 ) | sort -u > step1_dasquery.log  2>&1

cmsDriver.py step2  --process reHLT -s L1REPACK:Full,HLT:@relval2023 --conditions auto:run3_hlt_relval --data  --eventcontent FEVTDEBUGHLT --datatier FEVTDEBUGHLT --era Run3_2023 -n 1000 --filein filelist:step1_dasquery.log --lumiToProcess step1_lumiRanges.log --fileout file:step2.root  --nThreads 8

cmsDriver.py step3  --conditions auto:run3_data_prompt_relval -s RAW2DIGI,L1Reco,RECO,PAT,NANO,DQM:@jetmet --datatier RECO,MINIAOD,NANOAOD,DQMIO --eventcontent RECO,MINIAOD,NANOEDMAOD,DQM --data  --process reRECO --scenario pp --era Run3_2023 --customise Configuration/DataProcessing/RecoTLR.customisePostEra_Run3 --hltProcess reHLT -n 1000 --filein  file:step2.root  --fileout file:step3.root  --nThreads 8

cmsDriver.py step4  -s HARVESTING:@jetmet --conditions auto:run3_data --data  --filetype DQM --scenario pp --era Run3_2023 -n 1000 --filein file:step3_inDQM.root --fileout file:step4.root
```

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport of PR#44336

### CODE REVIEW

**Comment by tjavaid** [comment]
backport of #44336

**Comment by tjavaid** [comment]
please test

**Comment by mandrenguyen** [comment]
urgent
Needed for data taking, according to:
https://docs.google.com/document/d/1QXXZiwxU_zbDCqAeCt9vKDDJ3LUjEduK5-mXVO9w1GI/edit
-Matt (ORM)

**Comment by syuvivida** [comment]
+1

**Comment by antoniovilela** [comment]
+1
   - Let's rely on PR tests and fast-track this backport targetting 14_0_6.

**Pull request merged**
