### PR TITLE
MTD geometry: update pixel index definition from RectangularMTDTopology

### PR DESCRIPTION
**Pull request by fabiocos**
#### PR description:

This PR proposes a solution to the issue https://github.com/cms-sw/cmssw/issues/43942 , or at least to the MTD-related part of it. The recent update of ETL digitization in #43762 utilizes also hits outside the active part of the pixel area, and therefore needs the computation of pixel indices also for points very close to the geometrical border of the volume. Due to numerical accuracy, they can exceed the maximum allowed value, producing a chain of problems in the downstream code.

This PR introduces a ```pixelIndex``` method in ```RectangularMTDTopology``` to correctly compute the indices based on the position in the module, introducing a safety check for border situations. The geometry test is instrumented to possibly catch problems, and this new method is used in the rest of the MTD code where applicable.

#### PR validation:

The code appears to solve the reproducible crash in recent ASAN builds within the MTD clustering algorithm, and allows the unit test of ```Geometry/MTDGeometryBuilder``` to pass smoothly.

### CODE REVIEW

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
type bugfix

**Comment by fabiocos** [comment]
urgent

**Comment by bsunanda** [comment]
+geometry

**Comment by srimanob** [comment]
+Upgrade

Does this PR need backport to 14_0?

**Comment by fabiocos** [comment]
@cms-sw/simulation-l2 any comment?

**Comment by fabiocos** [comment]
@cms-sw/orp-l2 this PR is meant to solve the issue of crashes in recent 14_1_X IBs, the sooner it is merged the sooner we may check and verify this

**Comment by rappoccio** [comment]
+1

**Pull request merged**
