### PR TITLE
Phase2-hgx267 Assign part/orient from flat file in the HGCal geometry definition

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Assign part/orient from flat file in the HGCal geometry definition

#### PR validation:

Tested using the runTheMatrix workflows 23234.0 and 32234.0

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by cvuosalo** [comment]
+1

**Comment by bsunanda** [comment]
@kpedro88 Could you sign this?

**Comment by kpedro88** [comment]
+upgrade

**Comment by qliphy** [comment]
+1

**Pull request merged**
