### PR TITLE
Update D5 (D3 + timing layer geometry) to use fine BH

### PR DESCRIPTION
**Pull request by lgray**
This is a minor change that did not make it in with #16022 since that PR predated the existence of D5.

### CODE REVIEW

**Comment by lgray** [comment]
urgent

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
@davidlange6 This just copies the same edit made to D3 and D4 geometries in #16022. Nothing new here.

**Comment by ianna** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Comment by lgray** [comment]
Thanks!

**Pull request merged**
