### PR TITLE
Phase2-hgx358 Modify the silicon part of the V19 version of HGCal geometry using the new flat file information

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Modify the silicon part of the V19 version of HGCal geometry using the new flat file information

#### PR validation:

To be fully tested once the V19 geometry code becomes available

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

**Comment by bsunanda** [comment]
@antoniovilela, @rappoccio Please merge this PR

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
