### PR TITLE
Boost 1.75 - Add missing headers (algorithm and memory) and update include locations

### PR DESCRIPTION
**Pull request by mrodozov**
#### PR description:

This brings the header for the 4 argument lower_bound, coming from algorithm 
It fixes deprecated header warning. There might other warnings

#### PR validation:

CondFormats/EcalObjects builds with boost 1.75

### CODE REVIEW

**Comment by smuzaffar** [comment]
@mrodozov , should this change work for current boost version ?

**Comment by mrodozov** [comment]
yes, <boost/function_output_iterator.hpp> is already deprecated in 1.72 but left for backward compat, 
and it exists also as <boost/iterator/function_output_iterator.hpp>
boost/range/algorithm/lower_bound.hpp is also there.
it compiles, i tried

**Comment by smuzaffar** [comment]
please test

**Comment by thomreis** [comment]
Why boost? EcalMustacheSCParameters.cc and EcalSCDynamicDPhiParameters.cc use `std::lower_bound`. Should it not rather be `#include <algorithm>` that is missing?

**Comment by mrodozov** [comment]
Hm I probably didn't noticed it worked for the file I added <algorithm> to and failed for the next file, and thought they are the same ... 
It works with algorithm, I've changed it

**Comment by perrotta** [comment]
please test

**Comment by mrodozov** [comment]
please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/32943	4d2f73e 
- technical
- compiles and runs without relevant differences
- 
- the PR title and description should be updated to describe what's actually done

**Comment by yuanchao** [comment]
+1
* adds headers for Boost 1.75 and remove warnings
* matrix tests and unit tests passed
* static build warnings are not part of the PR

**Comment by silviodonato** [comment]
merge
@cms-sw/db-l2 @cms-sw/l1-l2 please have a look

**Pull request merged**
