### PR TITLE
Perform premixing reco step customizations with premix_stage2 modifier

### PR DESCRIPTION
**Pull request by makortel**
This PR suggests to use `premix_stage2` modifier to customize validation module input collections instead of `SimGeneral/DataMixingModule/python/customiseForPremixingInput.py` customise function. This transformation will make the introduction of phase2 premixing cleaner.

Tested in CMSSW_10_1_X_2018-03-05-2300 (rebased on top of CMSSW_10_2_X_2018-03-29-2300), no changes expected.

@mdhildreth @kpedro88

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
@cmsbuild, please abort

**Comment by makortel** [comment]
@cmsbuild please test workflow 250202.0,250202.17,250202.18,250402.0

Let's test the affected workflows as well...

**Comment by prebello** [comment]
+1

**Comment by dmitrijus** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Comment by perrotta** [comment]
+1
- In the reco part, customization is applied with a new modifier for premix-stage2
- Jenkins tests pass
- Verified that also for the workflows where premixing is activated (e.g. 250202) there is no difference in outputs when using this PR or not. The only change visible in the step3 config dump is the appearance of the module label "mixData", while the step2 config dump remains identical

**Comment by makortel** [comment]
@cmsbuild, please test

Rebased on top of CMSSW_10_2_X_2018-03-29-2300 fixing a conflict caused by merged #22589.

**Comment by civanch** [comment]
+1

**Comment by perrotta** [comment]
+1
- Already signed by reco in https://github.com/cms-sw/cmssw/pull/22583#issuecomment-373085220, it has just been rebased since then

**Comment by kpedro88** [comment]
+1

**Comment by dmitrijus** [comment]
+1

**Comment by prebello** [comment]
+1

**Comment by makortel** [comment]
@cmsbuild, please test workflow 250202.0,250202.17,250202.18,250402.0

Refreshing tests.

**Comment by makortel** [comment]
@fabiocos Now that 10_2_0_pre1 is out, could this PR be merged some time soon?

**Comment by fabiocos** [comment]
+1

**Comment by makortel** [comment]
I guess this one doesn't get merged automatically because of the missing analysis signature.

**Comment by fabiocos** [comment]
merge

**Pull request merged**
