### PR TITLE
Phase2-hcx341 Add a new Prodcut file Phase2 HCAL and modify the scenarios accordingly

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Add a new Prodcut file Phase2 HCAL and modify the scenarios accordingly

#### PR validation:

Use the runTheMatrix Phase2 test workflows

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
+geometry

**Comment by srimanob** [comment]
+Upgrade

Technical PR, to migrate the ProdCut to be 2026 setting. No change is expected as it is the same as before.

**Comment by perrotta** [comment]
+1

**Pull request merged**
