### PR TITLE
New training for anti-e tau-Id (94X)

### PR DESCRIPTION
**Pull request by mbluj**
This PR adds configuration with payloads of a new training of anti-e tau-Id, backport of #25486 to 94X.

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
This is an almost identical backport of #25486 from the master into 94X: it just misses to backport the two files:
- RecoTauTag/RecoTau/python/tools/runTauIdMVA.py
- RecoTauTag/RecoTau/test/runDeepTauIDsOnMiniAOD.py
This makes sense, because runTauIdMVA.py was not yet updated and moved into the tools folder in 94X.

Even if not including the tool to run and test the new ID in 94X, however this PR sets up for it in that release. Full backport to 94X will be completed when DNN-tauID (and tau tools) will be finally merged to that release.

**Comment by perrotta** [comment]
@mbluj (maybe you already told us, but I forgot it, sorry for that...): is there any plan to update this PR once #25385 will get merged in 94X?

**Comment by perrotta** [comment]
backport of #25486

**Comment by mbluj** [comment]
> @mbluj (maybe you already told us, but I forgot it, sorry for that...): is there any plan to update this PR once #25385 will get merged in 94X?

Yes, the plan is either to update this PR or prepare a new one on top of it depending what is more convenient, i.e. in which order this PR and #25385 are merged.

**Comment by perrotta** [comment]
please test
(now #25621 is in the 94X IBs)

**Comment by perrotta** [comment]
+1
- Identical backport of #25486
- A new anti-e tau-ID defined is added to tau tools for user convenience, but disabled by default: non difference expected in regular workflows and reco sequences
- Jenkins tests pass and show no differences

**Comment by fabiocos** [comment]
code-checks

**Comment by fabiocos** [comment]
+1

**Pull request merged**
