### PR TITLE
PA Common Alignment Producers 80X

### PR DESCRIPTION
**Pull request by jrcastle**
backport of  #16155

### CODE REVIEW

**Comment by ghellwig** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by fabozzi** [comment]
+1

**Comment by jrcastle** [comment]
I see that #16155 has already merged, what's the status for this PR?  Is more discussion needed because it is a backport?

**Comment by mmusich** [comment]
@jrcastle I was hoping to see some study on the expected event size of the added producers + throughput to see how much it is sustainable in terms of disk space at T2. I know @ghellwig was working on this, but he's currently at CHEP.

**Comment by mmusich** [comment]
+1
(@jrcastle and @mandrenguyen  based on our discussion today at the AlCa/DB meeting) the check on the expected output size can come as part of the validation that the HI community is planning on the release being built with all the needed pA ingredients.

**Pull request merged**
