### PR TITLE
Fix undersized buffers.

### PR DESCRIPTION
**Pull request by schneiml**
#### PR description:

Trying to compile large parts of CMSSW with `USER_CXXFLAGS='-g -Og' scram b`, I got compilation errors on these files: `-Werror=format-truncation`.

(Using GCC 8.3.1 20190225, as shipped by a recent IB.)

I simply increased all affected buffer sizes to next power of two.

#### PR validation:

None so far. No changes expected.

### CODE REVIEW

**Comment by smuzaffar** [comment]
@schneiml, it is possible but with simple unit test I am not able to reproduce such warnings.

**Comment by schneiml** [comment]
On lxplus,
```
 mkdir /dev/shm/$USER
 cd /dev/shm/$USER
 cmsrel CMSSW_11_0_X_2019-10-17-2300
 cd CMSSW_11_0_X_2019-10-17-2300/src/
 cmsenv
 git cms-merge-topic schneiml:cmssw-fix-undersized-buffers
 git checkout CMSSW_11_0_X_2019-10-17-2300
 USER_CXXFLAGS='-g -Og' scram b -j10
```

Reproduces the problem:
```
dev/shm/mschneid/CMSSW_11_0_X_2019-10-17-2300/src/DQM/L1TMonitor/src/BxTiming.cc:158:24: error: '%d' directive writing between 1 and 11 bytes into a region of size 10 [-Werror=format-overflow=]
...
/dev/shm/mschneid/CMSSW_11_0_X_2019-10-17-2300/src/DQM/TrigXMonitorClient/src/L1ScalersClient.cc:115:28: error: '%d' directive output may be truncated writing between 1 and 11 bytes into a region of size between 4 and 14 [-Werror=format-truncation=]
```

**Comment by schneiml** [comment]
+1

Nothing to worry about in here.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
