### PR TITLE
Run2-hcx377 Put all 2015 scenarios using the same hcalRecNumbering.xml file

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Put all 2015 scenarios using the same hcalRecNumbering.xml file

#### PR validation:

Use the runTheMatrix test workflows

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
+geometry

**Comment by bsunanda** [comment]
@subirsarkar Please approve this

**Comment by subirsarkar** [comment]
+Upgrade

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
