### PR TITLE
New analysis module StripClusterMCanalysis

### PR DESCRIPTION
**Pull request by wmtford**
EDAnalyzer in the test directories of /Validation/TrackerRecHits.  Produces a flat ntuple with si strip cluster information including that from matched MC truth.  A root macro generates useful plots.
Documentation in https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideStripClusterMCtruth#StripClusterMCanalysis_Ntuple_ma

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
this PR adds an entuplizer which is never run in production workflows but it is included for convenience in cmssw.
@davidlange6 is this acceptable?
F.

**Comment by deguio** [comment]
+1
doesn't hurt in my opinion

**Comment by davidlange6** [comment]
+1

**Pull request merged**
