### PR TITLE
Fix reflection integrity

### PR DESCRIPTION
**Pull request by abhih1**
#### PR description:

An issue with the Integrity quality summary plot was presented here: http://cmsonline.cern.ch/cms-elog/1112563, where the problematic tower mappings were "reflected" relative to the FE Status plot which showed the correct mapping. 

The error appears to be with a wrong binning set up for the filling of the histogram which is done here [6], where it was assumed that for EB+ supermodules there will be a reflection or flip of the tower y binning, when in fact it remains the same as for EB-. The flip only happens when using iphi coordinates to define the y binning, not the tower id which has been used in this case.

We have fixed this by removing the separate condition for EB+, and making it the same as for EB-.

#### PR validation:

We redid the plots with an offline ecal dqm workflow on 2018 runs (T0 turned off for offending run) by introducing integrity errors on EB+. Using a test GUI we found that it now shows the correct tower positions. We also made sure that if the error happened on EB- this still gave the correct tower mapping, and no other plots were affected.

#### This PR is a backport of the original PR here: https://github.com/cms-sw/cmssw/pull/32305
This is done to ensure the changes are available in CMSSW_11_2_X, which would be used in the next MWGR in February 2021.

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by silviodonato** [comment]
please test

**Comment by silviodonato** [comment]
Any objections @cms-sw/dqm-l2 ?

**Comment by jfernan2** [comment]
Hi @silviodonato 
We would like to have tested this PR at DQM Playback at P5 first, but unfortunately we could not do it yet due to disk space reasons: some 10_X_Y releases are installed and there is no space for 11_2_X so, we had to request subsystems to tell us which releases could be removed but with a deadline of a week. Deadline  expires tomorrow, so we hope to test it by then.
I am sorry for the inconvenience

**Comment by silviodonato** [comment]
> Hi @silviodonato
> We would like to have tested this PR at DQM Playback at P5 first, but unfortunately we could not do it yet due to disk space reasons: some 10_X_Y releases are installed and there is no space for 11_2_X so, we had to request subsystems to tell us which releases could be removed but with a deadline of a week. Deadline expires tomorrow, so we hope to test it by then.
> I am sorry for the inconvenience

Ok, no problem

**Comment by jfernan2** [comment]
@abhih1 we need also a forwardport of this PR to 11_3_X (master) to not lose track of these changes in the future. Thanks

**Comment by jfernan2** [comment]
+1

**Comment by silviodonato** [comment]
+1
@jfernan2 https://github.com/cms-sw/cmssw/pull/32305/files is already merged and it is identical to https://github.com/cms-sw/cmssw/pull/32334/files

**Comment by jfernan2** [comment]
Yes, sorry, I totally lost the track of this one in my notes, in the transition of 112X to 113X as master release, everything which was forwardport became backport :-P

**Pull request merged**
