### PR TITLE
MC updates for trancheIV

### PR DESCRIPTION
**Pull request by franzoni**
see: https://indico.cern.ch/event/562065/cntributions/2270369/
# Summary of changes in Global Tags
## RunII simulation
- **RunII Ideal scenario** : [81X_mcRun2_design_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun2_design_v5) as [81X_mcRun2_design_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun2_design_v4) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_mcRun2_design_v5/81X_mcRun2_design_v4): 
  - updated SiPixel dynamic inefficiency for 2016 data (high PU)
- **RunII CRAFT scenario** : [81X_mcRun2cosmics_startup_peak_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun2cosmics_startup_peak_v5) as [81X_mcRun2cosmics_startup_peak_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun2cosmics_startup_peak_v4) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_mcRun2cosmics_startup_peak_v5/81X_mcRun2cosmics_startup_peak_v4): 
  - updated EcalChannelStatus (as in Aug 2016)
  - updated RPC noise and efficiency
  - updated SiPixel dynamic inefficiency for 2016 data (high PU)
  - updated Pixel channel status (as in Aug 2016)
  - updated Strip channel status (as in Aug 2016)
- **RunII Asymptotic scenario** : [81X_mcRun2_asymptotic_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun2_asymptotic_v5) as [81X_mcRun2_asymptotic_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun2_asymptotic_v4) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_mcRun2_asymptotic_v5/81X_mcRun2_asymptotic_v4): 
  - updated EcalChannelStatus (as in Aug 2016)
  - updated RPC noise and efficiency
  - updated SiPixel dynamic inefficiency for 2016 data (high PU)
  - updated Pixel channel status (as in Aug 2016)
  - updated Strip channel status (as in Aug 2016)
  - updated Tracker Alignment fixing z-shrinkage effect 
- **RunII Startup scenario** : [81X_mcRun2_startup_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun2_startup_v5) as [81X_mcRun2_startup_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun2_startup_v4) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_mcRun2_startup_v5/81X_mcRun2_startup_v4): 
  - updated EcalChannelStatus (as in Aug 2016)
  - updated RPC noise and efficiency
  - updated SiPixel dynamic inefficiency for 2016 data (high PU)
  - updated Pixel channel status (as in Aug 2016)
  - updated Strip channel status (as in Aug 2016)
- **RunII Heavy Ions scenario** : [81X_mcRun2_HeavyIon_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun2_HeavyIon_v5) as [81X_mcRun2_HeavyIon_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun2_HeavyIon_v3) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_mcRun2_HeavyIon_v5/81X_mcRun2_HeavyIon_v3): 
  - updated EcalChannelStatus (as in Aug 2016)
  - updated RPC noise and efficiency
  - updated SiPixel dynamic inefficiency for 2016 data (high PU)
  - updated Pixel channel status (as in Aug 2016)
  - updated Strip channel status (as in Aug 2016)
  - updated Tracker Alignment fixing z-shrinkage effect 
## Upgrade
- **PhaseI realistic scenario** : [81X_upgrade2017_realistic_v9](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_upgrade2017_realistic_v9) as [81X_upgrade2017_realistic_v8](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_upgrade2017_realistic_v8) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_upgrade2017_realistic_v9/81X_upgrade2017_realistic_v8): 
  - updated EcalChannelStatus (as in Aug 2016)
  - updated RPC noise and efficiency  
  - updated Strip channel status (as in Aug 2016)

### CODE REVIEW

**Comment by franzoni** [comment]
please test

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
@davidlange6 this is the whole package of updates for the Tranche-IV MC. 
Given the production is going to happen in 80X, are we allowed to backport the same updates in the 80X GTs, even if this changes the physics performance?
Thanks for input,
Marco & Giovanni

**Comment by davidlange6** [comment]
On Aug 11, 2016, at 5:16 PM, Marco Musich <notifications@github.com<mailto:notifications@github.com>> wrote:


@davidlange6<https://github.com/davidlange6> this is the whole package of updates for the Tranche-IV MC.
Given the production is going to happen in 80X, are we allowed to backport the same updates in the 80X GTs, even if this changes the physics performance?

we will do something coherent with the N other changes being discussed, yes. no harm in making a PR as to be prepared.

Thanks for input,
Marco & Giovanni

**Comment by franzoni** [comment]
ok, will go that way.

**Comment by franzoni** [comment]
+1

**Pull request merged**
