### PR TITLE
the canonical type of std::atomic<T*> in template <T> edm::AtomicPtrC…

### PR DESCRIPTION
**Pull request by gartung**
…ache is atomic<parameter-type-0-0 *>

### CODE REVIEW

**Comment by gartung** [comment]
@Dr15Jones

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by gartung** [comment]
@Dr15Jones I fixed the bug in the script and added it to this branch.

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1
This change is needed for the static analyzer to avoid a false positive

**Comment by Dr15Jones** [comment]
This also fixes a bug introduced in the last commit to the static analyzer in CMSSW_7_5_X which now causes some reports to be empty.

**Comment by Dr15Jones** [comment]
@davidlange6 please include to allow the static analyzer reports to fully work again.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
