### PR TITLE
FRDStreamSource Dangling Reference Fix : 12_3_X

### PR DESCRIPTION
**Pull request by Sam-Harper**
#### PR description:

This PR fixes a dangling reference in FRDStreamSource when reading multiple error stream files. The fileNames() function returns std::vectorstd::string which the code sets iterators to which then instantly become invalid as they are dangling.

This keeps an internal copy of the returned std::vector and sets the iterators to that.

#### PR validation:

It now successfully processes events in multiple files rather than spewing random garbage to the terminal.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

backport of https://github.com/cms-sw/cmssw/pull/37677

It would make life easier for FOG to have this in CMSSW_12_3_X as this will simplify our lives when dealing with error stream events during commissioning.

### CODE REVIEW

**Comment by smorovic** [comment]
@cmsbuild please test

**Comment by missirol** [comment]
backport of https://github.com/cms-sw/cmssw/pull/37677

(just adding the label)

**Comment by smorovic** [comment]
+1

**Comment by missirol** [comment]
type bugfix

**Pull request merged**
