### PR TITLE
PixelJetPuId  multi-threading (74X)

### PR DESCRIPTION
**Pull request by silviodonato**
This PR makes the module PixelJetPuId multi-threading friendly.

### CODE REVIEW

**Comment by silviodonato** [comment]
please test

**Comment by Dr15Jones** [comment]
please add the keyword ```override``` to the ```produce``` method.

**Comment by Dr15Jones** [comment]
As a side note, this module would make a great ```global``` module instead of a ```stream``` module. It would just require changing the inheritance to ```edm::global::EDProducer<>``` and changing the signature of the ```produce``` method to

 ```void produce(edm::StreamID, edm::Event&, edm::EventSetup const&) const```

Globals are better than stream modules since they take up less memory.

**Comment by Martin-Grunewald** [comment]
please test

**Comment by silviodonato** [comment]
@Dr15Jones : I've implemented your comments:
- add "override"
- use global instead of stream

Same changes in #9139 .

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by Martin-Grunewald** [comment]
@degano 
The tests seem stuck here... please have a look.

**Comment by nclopezo** [comment]
@Martin-Grunewald, I restarted them.

**Comment by perrotta** [comment]
Hi @davidlange6 .

This PR was first merged in 74X, and as far as I understand it was then reverted before building CMSSW_7_4_4. As a result, its content is not in CMSSW_7_4_4, it is also not in the head of CMSSW_7_4_X, but (since it got apparently merged) it is not even in the queue any more.

Was the author (@silviodonato) informed that his Pull Request was first merged and the reverted (as I don't see mention of it in the "Conversation" fields here)? What should he do then if he still wants this PR queued for 74X, and not let it remain unnoticed and get lost forever? Should he resubmit an identical one, or there will be some central management of the issue?

I think that some comment should remain in the "Conversation" of a Pull Request which gets reverted, and perhaps the same PR should remain in a different state rather than "Merged": all this to avoid confusions, possible mistakes and potential loss of possible updates (see also my correlated comments in #9115 and #9270)


Thank you,
Andrea

**Comment by Martin-Grunewald** [comment]
@perrotta @davidlange6 
Indeed, this PR I do NOT see in 744, the plugin is still a legacy producer  - what has happened?

**Comment by davidlange6** [comment]
as commented 2-3 times already - it needs testing in 75x

**Comment by Martin-Grunewald** [comment]
@davidlange6 
Yes, but that is not the issue. The issue is why this PR is listed as merged in github - see at the top of
#9138.

**Comment by Martin-Grunewald** [comment]
Maybe because github is (too?) smart: it sees that #9138 was part of #9292 which was merged,
so list is as merged - [ but of course in #9292 the change brought in by #9138 was explicitly reverted
lateron]

**Comment by Martin-Grunewald** [comment]
This PR is now redone as #9376

**Comment by davidlange6** [comment]
Right, if there are no commits to merge, nothing is done. To simplify your life, keep your PRs orthogonal and then all will be registered as PRs in the release notes.

**Comment by perrotta** [comment]
David Lange <notifications@github.com> ha scritto:

> Right, if there are no commits to merge, nothing is done. To  
> simplify your life, keep your PRs orthogonal and then all will be  
> registered as PRs in the release notes.

We can try to keep them orthogonal, but it will not be always  
possible. By the way, it was also a previous request of yours to make  
new PR's which include the old ones, instead of keeping updating the  
same PR's in case of successive updates...

In any case, I don't know if it is possible, but it would help life  
(and avoid possible mistakes) if those PR's for which "nothing is  
done" (because there are no commits to merge, for instance) are marked  
something different than "Merged": then the proponents can easily  
identify them and try to understand what happened to them. In this  
case, I only noticed it because I did not see those three PR  
(supposedly merged) listed in the release notes for CMSSW_7_4_4.

Andrea


>> On May 31, 2015, at 5:53 PM, Martin Grunewald

**Pull request merged**
