### PR TITLE
substitute kHGCalEta with kHGCalRadius

### PR DESCRIPTION
**Pull request by mrodozov**
Fix comp errors in IBs https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc6_amd64_gcc700/CMSSW_10_3_X_2018-08-28-2300/L1Trigger/L1THGCal

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by smuzaffar** [comment]
@bsunanda, @kpedro88 , this is need to fix the IBs build failures. Renaming of the variable was done here https://github.com/cms-sw/cmssw/pull/24331

**Comment by kpedro88** [comment]
+1

**Comment by kpedro88** [comment]
merge

**Comment by kpedro88** [comment]
@mrodozov @smuzaffar can we launch an intermediate IB now that this is merged, so other PR tests don't have to wait until 23:00?

**Pull request merged**
