### PR TITLE
fix cmsDriver arguments in testTauEmbeddingProducers

### PR DESCRIPTION
**Pull request by kpedro88**
#### PR description:

The integration of #43042 revealed an error in the unit test for `TauAnalysis/MCEmbeddingTools`. A fairly trivial error in this case, but still another good illustration of why more precise parsing is important for ensuring the correctness of our software.

#### PR validation:

Unit test passes.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Unnecessary.

### CODE REVIEW

**Comment by kpedro88** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by kpedro88** [comment]
@cms-sw/orp-l2 please merge this bug fix, the test has been broken in IBs for several days now.

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
