### PR TITLE
[DD4hep] Allow Assembly Registration in the Namespace

### PR DESCRIPTION
**Pull request by ianna**
#### PR description:

* Assembly can be registered in and accessed from a Namespace
* DDEcalPreshowerAlgorithm is updated to use Assemblies
   * All overlaps removed
   * Numerous complicated Boolean shapes removed
   * Air volumes replaced with Assemblies
   * The algorithm code base reduces by half

**Before:** Overlaps of the sensitive volumes with their mother volume:
Screenshot 2020-06-07 at 15 39 02
The old Boolean shape that is replaced by an Assembly:
Screenshot 2020-06-07 at 16 11 20

**After:** Sensitive detector elements and 0 overlaps:
Screenshot 2020-06-07 at 15 04 26

@bsunanda - please, comment

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
please test

**Comment by slava77** [comment]
@ianna 
this PR apparently includes (or at least overlaps with) #30093.
Do these two still have to go separately or can this PR be reviewed instead as superseding #30093?

**Comment by ianna** [comment]
> @ianna
> this PR apparently includes (or at least overlaps with) #30093.
> Do these two still have to go separately or can this PR be reviewed instead as superseding #30093?

This PR is based on the previous "urgent" one. Please, review #30093.
I'll rebase it when the other one is merged and it should remove the need for reco signature.

**Comment by ianna** [comment]
@smuzaffar - is this something new?
```
----- Begin Fatal Exception 08-Jun-2020 15:27:48 CEST-----------------------
An exception of category 'FatalRootError' occurred while
   [0] Processing  Event run: 1 lumi: 1 event: 1 stream: 0
   [1] Running path 'p'
   [2] Calling method for module DDTestDumpFile/'testDump'
   Additional Info:
      [a] Fatal Root Error: @SUB=TFile::TFile
file cmsDD4HepGeom.root already exists

----- End Fatal Exception -------------------------------------------------

```

**Comment by smuzaffar** [comment]
@ianna , nothing that I know. May be multiple tests try to create same file and system call to create this file fails?

**Comment by ianna** [comment]
> @ianna , nothing that I know. May be multiple tests try to create same file and system call to create this file fails?

Yes, the tests create a file with the same name. It used to be overwritten without an exception.

**Comment by smuzaffar** [comment]
@makortel , has something changed on FW side ?

**Comment by makortel** [comment]
As far as I can tell the file is created with ROOT directly
https://github.com/cms-sw/cmssw/blob/f64440e26cdeb8599aacc4f2ec382aec5e16bfd1/DetectorDescription/DDCMS/plugins/test/DDTestDumpFile.cc#L53

**Comment by ianna** [comment]
please test

**Comment by cvuosalo** [comment]
@ianna What happened to this PR? The description says it replaces preshower algorithms, but there is only a deletion, no replacement.

**Comment by ianna** [comment]
https://github.com/cms-sw/cmssw/pull/30135#issuecomment-641540767

There are a few lines changed and due to that the rest of the code is not needed - hence deleted   😀

**Comment by cvuosalo** [comment]
@ianna OK, I understand now. I saw some of these files in other your other PRs, so I was confused as to which one they belong to.

**Comment by cvuosalo** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
