### PR TITLE
Baseline for Hermetic Timing Demo (SLHCDEV)

### PR DESCRIPTION
**Pull request by lgray**
This PR adds in a number of features for HGC and more importantly some non-invasive additions to the vertexing.

All features are related to fast timing:
- HGC ToT readout ( 60 fC threshold )
- Current work in progress in propagating 4D measurements through the vertexing
  - All the old 3x3 matrix and 3D point accessors are retained, no change expected, achieved by returning the submatrix or subvector of what's in the internal object.
  - 4x4 matrices and 4D points are added though same methods with "4D" at the end
  - Vertices know if they are 4D or not.
  - A new package is added "RecoFTL" (Reco for Fast-Timing-Layer) that right now defines a kludge to associate sim-track timing information to the reconstructed tracks.

It compiles (312 package checkout, as a warning).
It runs on a PU = 10 sample and gives the same results as before for the "3D" stuff (4D is work in progress).

Please double check there are no weird or unexpected regressions.

### CODE REVIEW

**Comment by lgray** [comment]
@mark-grimes @fratnikov wait a bit... not done yet.

**Comment by lgray** [comment]
@mark-grimes @fratnikov done. Please go ahead.

**Comment by fratnikov** [comment]
please test

**Comment by lgray** [comment]
Unit test failures look unrelated to this PR.

-L

(Sent from my Nexus 6)

**Comment by mark-grimes** [comment]
Yes, I'd not worry about the unit tests.  Tracker/ing are using some workflows not in the standard tests, so they need to be checked as well.  I'll look up the workflow numbers later this morning.

**Comment by mark-grimes** [comment]
As far as I can see the tracker workflows are fine.  I'd prefer to see the cout statements as log messages (and particularly not both!), since others are working in this branch too too.

Does changing the size of variables in the DataFormats (e.g. HGCSample::value_) break reading old samples?  I would guess the constructors insulate against that sort of issue.

If this ever goes in to 7XY they'll probably want unit tests, but it's okay for the dev branch.  The package name "FastTimingKludge" would never be accepted either.

**Comment by lgray** [comment]
@mark-grimes 

Much of this stuff (the stuff with couts) is run only in the fast timing customizations.

Part of this branch is already being queued for 76X where I have addressed these issues.

As for FastTimingKludge, it is what it is for now (and it's descriptive!). I can make a nicer name later.

Which parts are necessary for +1 ? Code review may also come with additional changes since I have continued working from making this branch.

**Comment by mark-grimes** [comment]
Okay, ignoring anything in "FastTimingKludge" package (which I assume no one else runs) and things with an `if( debug_ )` (neither of which are ideal, but can be overlooked for dev branch), as far as I can see it's just HGCalUncalibRecHitProducer.cc for the couts.

That would be enough for my approval, @fratnikov may have more comments.

**Comment by fratnikov** [comment]
No objections from my side

**Comment by lgray** [comment]
@mark-grimes @fratnikov couts in HGCalUncalibRecHitProducer addressed.

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by mark-grimes** [comment]
merge

All test failures are unrelated.

**Comment by lgray** [comment]
@mark-grimes IBs show up in the usual way for this branch?

**Comment by lgray** [comment]
@mark-grimes Followup question: is there a cvmfs IB like for 76X?

**Comment by mark-grimes** [comment]
Viewable with `scram list` if SCRAM_ARCH is `slc6_amd64_gcc472`.  As far as I'm aware only afs.

**Pull request merged**
