### PR TITLE
2017 pileup scenario for ultra-legacy using bunch-by-bunch 2017 data

### PR DESCRIPTION
**Pull request by plujan**
This contains the proposed pileup scenario for the 2017 ultra-legacy generation, created using the full 2017 data distribution (with the golden JSON) on a bunch-by-bunch basis. It is currently named "2017_25ns_UltraLegacy_PoissonOOTPU".

For more details see the talk here: https://indico.cern.ch/event/815042/contributions/3406023/attachments/1834447/3004998/PileupPPD20190425.pdf

### CODE REVIEW

**Comment by plujan** [comment]
I've also added an additional contribution to the Indico page which includes some followup plots in response to the questions raised at the meeting: https://indico.cern.ch/event/815042/contributions/3406023/attachments/1834447/3008406/PileupFollowup.pdf

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by fabiocos** [comment]
+operations

the addition of the new scenario to the StandardSequences is correct and works (cmsDriver.py command tested)

**Comment by fabiocos** [comment]
+1

**Pull request merged**
