### PR TITLE
2018 FullSim PU with premix + GENSIM updates

### PR DESCRIPTION
**Pull request by prebello**
This PR :
- fix typo in HI GENSIM acc #21783 ;
- update GENSIM strings for premixing (in 2017 and new 2018 workflows);
- add the new 2018 FullSim PU with premix workflows;

Tests were OK after being performed 

- for 2018 PU pmx:
runTheMatrix.py --what premix -l 250200.18,250202.18,250203.18,250204.18,250205.18,250206.18,250207.18 --noCaf -i all  --wm init

- for 2018 pmx no signal:
runTheMatrix.py --what premix -l 250199.18  --noCaf --wm init

- for HI:
runTheMatrix.py --what pileup -l 300,301,302  -i all --noCaf --wm init

@davidlange6 @fabiocos @fabozzi

### CODE REVIEW

**Comment by prebello** [comment]
please test workflow 250202.18,300,250199.18

**Comment by prebello** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Comment by fabozzi** [comment]
@kpedro88 ping

**Comment by kpedro88** [comment]
+1

**Pull request merged**
