### PR TITLE
xml files containing updated summary plot limits

### PR DESCRIPTION
**Pull request by ckmackay**
Please can you merge the xml files for the qTests for the DQM PixelPhase1 summary plots.

### CODE REVIEW

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Comment by threus** [comment]
@ckmackay  could you please back port this PR to 92X? It is needed for the online DQM, otherwise your changes don't get merged into the current production branch.
Thanks

**Comment by boudoul** [comment]
wait , some of the cosmic Qtests xmls removed here are caasing troubles in cosmic WFs , will reintrocue them   in a PR coming soonish

**Comment by boudoul** [comment]
@threus and @ckmackay , the backport is here : #19821

**Pull request merged**
