### PR TITLE
[14_1_X] Update new timing seeds for HI

### PR DESCRIPTION
**Pull request by JunseokLee3609**
#### PR description:

  - There is an issue with the DQM timing plot not being properly drawn during the HI run ([DQMGUI](https://cmsweb.cern.ch/dqm/online/start?runnr=375703;dataset=/Global/Online/ALL;sampletype=online_data;filter=all;referencepos=overlay;referenceshow=customise;referencenorm=True;referenceobj1=refobj;referenceobj2=none;referenceobj3=none;referenceobj4=none;search=;striptype=object;stripruns=;stripaxis=run;stripomit=none;workspace=Shift;size=M;root=00%20Shift/L1T;focus=;zoom=no), Run 375703, Plots 19-22)
  - Change the L1 seeds used for drawing the timing plot to L1 seeds that correspond to the 50 ns bunch spacing of the HI run

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:
This is a backport of #46462 to be merged into HI target release.

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by antoniovagnerini** [comment]
Please @JunseokLee3609 modify the title description by adding the string `[14.1.X]` at the beginning

**Comment by antoniovagnerini** [comment]
please test

**Comment by JunseokLee3609** [comment]
@antoniovagnerini I just changed the title. Thank you!

**Comment by antoniovagnerini** [comment]
+1

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
