### PR TITLE
Modernized Geometry/CmsTrackerDetIdBuilder

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

-Added consumes to ES modules
-Use references instead of pointers in APIs where pointers were always assumed to be non null

#### PR validation:

The code compiles.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
please test

**Comment by cvuosalo** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
