### PR TITLE
Use .length instead of strlen() in AMPTHadronizer

### PR DESCRIPTION
**Pull request by mrodozov**
#### PR description:

Fix at least one problem in AMPTHadronizer, see 
https://github.com/cms-sw/cmssw/issues/33452 and https://github.com/cms-sw/cmssw/issues/33682
I'd like to test against ARM IB to check wf 280.0

#### PR validation:

None, this is simple enough to work

### CODE REVIEW

**Comment by mrodozov** [comment]
@makortel unfortunately one of the two arm machines is not responsive and on the other there is a release building :/

**Comment by mrodozov** [comment]
please test for slc7_amd64_gcc900

**Comment by SiewYan** [comment]
Thats look good to me

**Comment by SiewYan** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
