### PR TITLE
New Service for Updating online Conditions for HLT

### PR DESCRIPTION
**Pull request by ggovi**
#### PR description:

A new  Service: OnlineDbOutputService has been implemented to serve the use cases of updating conditions during a HLT run.

In addition, the interface and implementation of PoolDbOutputService has been cleaned up. 
#### PR validation:

Unit tests and integration tests ( O2O tests )

### CODE REVIEW

**Comment by ggovi** [comment]
please test

**Comment by ggovi** [comment]
please test

**Comment by ggovi** [comment]
please test

**Comment by ggovi** [comment]
@smuzaffar could you please provide some help on this consistency error? I'm not sure how to solve it...

**Comment by smuzaffar** [comment]
@ggovi , from the logs , you can see that error is  [a]. CommonTools/ConditionDBWriter consists of one single header with ( CommonTools/ConditionDBWriter/interface/ConditionDBWriter.h ) without any BuildFile.xml. CalibTracker/SiStripLorentzAngle depends on CommonTools/ConditionDBWriter. But as there is no CommonTools/ConditionDBWriter/BuildFile.xml so CalibTracker/SiStripLorentzAngle is not getting the dependency of  CommonTools/ConditionDBWriter.  I would suggest to move CommonTools/ConditionDBWriter/interface/ConditionDBWriter.h to some common package and update CalibTracker/SiStripLorentzAngle to get it from new location + add the dependency on new location.

[a]
>> Compiling src/CalibTracker/SiStripQuality/interface/SiStripQualityHistos.h 
In file included from /data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_1_X_2020-03-30-1100/src/CondCore/DBOutputService/interface/PoolDBOutputService.h:5,
                 from /cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc820/cms/cmssw-patch/CMSSW_11_1_X_2020-03-30-1100/src/CommonTools/ConditionDBWriter/interface/ConditionDBWriter.h:140,
                 from src/CalibTracker/SiStripLorentzAngle/interface/SiStripCalibLorentzAngle.h:16:
/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_1_X_2020-03-30-1100/src/CondCore/CondDB/interface/ConnectionPool.h:9:10: fatal error: CoralBase/MessageStream.h: No such file or directory
 #include "CoralBase/MessageStream.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

**Comment by ggovi** [comment]
please test

**Comment by ggovi** [comment]
please test

**Comment by ggovi** [comment]
please test

**Comment by ggovi** [comment]
finally...
+1

**Comment by ggovi** [comment]
+1

**Comment by rekovic** [comment]
+1

**Comment by tlampen** [comment]
+1

**Comment by silviodonato** [comment]
+1
@ggovi could you add a link to some slides in the description, please?

**Pull request merged**
