### PR TITLE
Fixing key comparison in pat::Jet construction for miniAOD

### PR DESCRIPTION
**Pull request by rappoccio**
This address the issue [here](https://github.com/cms-sw/cmssw/issues/20346), where the jet key assignment was wrong for PUPPI jets. To make this more robust (and correct for PUPPI), we now compare the keys of the packed candidates, and rekey the AK8 jet accordingly.

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by rappoccio** [comment]
Anything else needed here? I think it should be good to go for inclusion.

**Comment by rappoccio** [comment]
Are we okay on this for 94x?

**Comment by slava77** [comment]
type bug-fix

**Comment by slava77** [comment]
If I understand correctly the logic of the update and comments in https://github.com/cms-sw/cmssw/issues/20346 to what was happening originally: the slimmedJetsAK8 were supposed to contain subjets as individual daughters, while instead we were getting all individual candidates that contributed to the jet.
Jenkins comparisons show that with this PR the number of jet constituents drops, e.g. in 136.788
wf136 788_ak8_nconstituents

I may have misunderstood the comment during the RECO meeting, from which I expected that there will be no visible change in DQM plots (to explain why this ~50% drop in constituents went unnoticed).

Is there a way to count the "subjet" daughters in a jet?
If so, perhaps it should be added to DQM to see this part even more clearly.

I guess this could have been noticed in 810pre11 validation
https://goo.gl/buoP7i

This was apparently a big "work in progress" for validation then, but was accepted eventually
https://cms-pdmv.cern.ch/valdb/?srch=8_1_0_pre12*&selected=8_1_0_pre11,8_1_0_pre12&Reconstruction=true&RFull=true
https://hypernews.cern.ch/HyperNews/CMS/get/relval/6164/1/1.html

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/20445	9a7ca99
- fixes saved daughters in jets that can have subjects, which was buggy for puppi-based subjets
- jenkins tests pass and comparisons with baseline show differences in AK8 [puppi] miniAOD jets in the distributions of consitituents. The reverse of the change is roughly in line with what can be seen at the time when the bug became evident after integration of #15437  in validation (810pre11  https://goo.gl/buoP7i).

Looking back, it seems like I also have missed to notice it in 
https://github.com/cms-sw/cmssw/pull/15437#issuecomment-240617750
even though there was a plot for the same T1tttt that could have hinted at the problem

wft1tttt_ak8_nconst

**Comment by davidlange6** [comment]
merge

**Comment by davidlange6** [comment]
fwiw - this PR is blamed for missing jets beyond eta2.4. Can you clarify? @rappoccio

**Comment by slava77** [comment]
On 10/19/17 5:29 AM, David Lange wrote:
> fwiw - this PR is blamed for missing jets beyond eta2.4. Can you
> clarify? @rappoccio <https://github.com/rappoccio>

Is there a link to the blame?
Verbal comments in PPD were not particularly clear.

**Comment by rappoccio** [comment]
Not this PR, but another in 940pre2 #19601 

Here is the relevant line. 

https://github.com/cms-sw/cmssw/blob/CMSSW_9_4_0_pre2/PhysicsTools/PatAlgos/python/slimming/applySubstructure_cff.py#L20

**Comment by davidlange6** [comment]
so a "feature" or a "bug" (it was characterized as a bug)

**Comment by rappoccio** [comment]
This is a feature, not a bug. It was intended.

**Comment by davidlange6** [comment]
Ok, Thanks....

**Pull request merged**
