### PR TITLE
Fixing bug in HLTriggerJSONMonitoring L1 and prescale module idenfication : 12_5_X

### PR DESCRIPTION
**Pull request by Sam-Harper**
#### PR description:

HLTriggerJSONMonitoring is how the HLT reports path rates to OMS. It was updated in Jun (https://github.com/cms-sw/cmssw/pull/38418) to better support DatasetPaths.

In doing so a bug was introduced in that if a path is after a dataset path, the wrong L1 and prescale module will be identified.

Additionally the logic was improved to only consider the first seed module and also to disregard ignored modules. This fixes problems in some paths which have additional L1 seed modules which are ignored as they want to use this data later in the path.

Credit goes to Adelina Lintuluoto (@alintulu) for spotting this issue in the hilton tests.

#### PR validation:

validation in : https://github.com/cms-sw/cmssw/pull/39779

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported 
backport of https://github.com/cms-sw/cmssw/pull/39779  as its needed to fix a bug in monitoring at P5

### CODE REVIEW

**Comment by Sam-Harper** [comment]
please test

**Comment by missirol** [comment]
backport of #39779

**Comment by missirol** [comment]
+hlt
 - RelVals-INPUT error is very likely unrelated to this PR
 - differences in wf `11634.7` cannot be caused by this PR, and were seen recently elsewhere (#39803)

**Comment by perrotta** [comment]
+1

**Comment by perrotta** [comment]
merge

**Pull request merged**
