### PR TITLE
Revert TF changes on DEVEL

### PR DESCRIPTION
**Pull request by mrodozov**
#### PR description:

Reverts changes for tensorflow 1.13 

#### PR validation:

Sources on master are the same, in theory should build as master builds
Building locally would require building the external AND the PR so better let the bot do it.

### CODE REVIEW

**Comment by mrodozov** [comment]
needs https://github.com/cms-sw/cmsdist/pull/5141

**Comment by mrodozov** [comment]
please test with cms-sw/cmsdist#5141

**Comment by smuzaffar** [comment]
we need to merge it for DEVEL IBs

**Comment by jfernan2** [comment]
+1

**Pull request merged**
