### PR TITLE
adapt Pythia8Interface to pythia8 240

### PR DESCRIPTION
**Pull request by mkirsano**

### CODE REVIEW

**Comment by mkirsano** [comment]
To be tested together with PR cmsdist #4624

**Comment by alberto-sanchez** [comment]
please test with https://github.com/cms-sw/cmssw/pull/4624

**Comment by alberto-sanchez** [comment]
please abort

**Comment by alberto-sanchez** [comment]
please test with cms-sw/cmsdist#4624

**Comment by alberto-sanchez** [comment]
@fabiocos as discussed some time ago, this release should include all patches made by K. Pedro, we would like to integrate across all production branches.

**Comment by mkirsano** [comment]
Hello, something is still wrong with the tests here? I don't see comparisons, some tests are still marked as "Running"

**Comment by fabiocos** [comment]
please abort

**Comment by fabiocos** [comment]
please test with cms-sw/cmsdist#4624

**Comment by alberto-sanchez** [comment]
please test with cms-sw/cmsdist#4624

**Comment by alberto-sanchez** [comment]
Let's make sure it is not a glitch

**Comment by alberto-sanchez** [comment]
+1

**Comment by fabiocos** [comment]
code-checks

**Comment by fabiocos** [comment]
+1

**Pull request merged**
