### PR TITLE
Cleanup the inclusion of CUDAService and other central services

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Cleanup the conditional inclusion of `CUDAService` and the configuration and comments regarding other central services.

#### PR validation:

None.

### CODE REVIEW

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by fwyzard** [comment]
please test

**Comment by silviodonato** [comment]
+operations

**Comment by silviodonato** [comment]
+1

**Pull request merged**
