### PR TITLE
Phase2-hgx281X Make tests for V15 reconstruction geometry for HGCal

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Make tests for V15 reconstruction geometry for HGCal. 

#### PR validation:

Makes tests for V15 reconstruction geometry for HGCal. Now it is ready to make a scenario using this geometry.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@silviodonato @qliphy @cvuosalo @srimanob Can this be included in the pre6?

**Comment by srimanob** [comment]
Urgent

**Comment by cvuosalo** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

**Comment by silviodonato** [comment]
+1

> The workflows 140.53 have different files in step1_dasquery.log than the ones found in the baseline. You may want to check and retrigger the tests if necessary. You can check it in the "files" directory in the results of the comparisons

**Pull request merged**
