### PR TITLE
Backport STXS Stage 1.1 to 10_2_X

### PR DESCRIPTION
**Pull request by yhaddad**
This PR is a backport from #26724 to 10_2_X.

### CODE REVIEW

**Comment by efeyazgan** [comment]
please test

**Comment by efeyazgan** [comment]
please test

**Comment by efeyazgan** [comment]
+1

**Comment by peruzzim** [comment]
@yhaddad can you please propagate the latest fixes to #26724 also here? thanks

**Comment by qliphy** [comment]
please test

**Comment by fabiocos** [comment]
@efeyazgan @qliphy following the discussion today we should move forward with the integration of this PR as well, unless you have any further comment

**Comment by efeyazgan** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
