### PR TITLE
HLT DQM for 9.3.x - clean up

### PR DESCRIPTION
**Pull request by fwyzard**
Follow up to #19916.

Cleaned up by clang-tidy 4.0.0 modernize checks
    
Enabled checks:
    boost-use-to-string
    cppcoreguidelines-no-malloc
    google-build-explicit-make-pair
    misc-inefficient-algorithm
    misc-string-compare
    modernize-avoid-bind
    modernize-deprecated-headers
    modernize-loop-convert
    modernize-make-shared
    modernize-make-unique
    modernize-pass-by-value
    modernize-redundant-void-arg
    modernize-replace-auto-ptr
    modernize-shrink-to-fit
    modernize-use-auto
    modernize-use-bool-literals
    modernize-use-emplace
    modernize-use-equals-default
    modernize-use-equals-delete
    modernize-use-nullptr
    modernize-use-override
    modernize-use-transparent-functors
    modernize-use-using
    performance-faster-string-find
    performance-for-range-copy
    performance-implicit-cast-in-loop
    performance-inefficient-string-concatenation
    performance-type-promotion-in-math-fn
    performance-unnecessary-copy-initialization
    performance-unnecessary-value-paramnn

See http://releases.llvm.org/4.0.0/tools/clang/tools/extra/docs/clang-tidy/index.html for details.

### CODE REVIEW

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by fwyzard** [comment]
Updated following #19916, and cherry-picking the final cleanup.

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by davidlange6** [comment]
merge

**Pull request merged**
