### PR TITLE
Backport the refactoring of the PropagateToMuon class and add the propagating to some HLT filters

### PR DESCRIPTION
**Pull request by JanFSchulte**
Backport of #37180 to 12_3_X as the improved HLT performance is needed to be available in this release for first data taking as discussed in the PR for the main branch.

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by jfernan2** [comment]
+1
Changes in line with https://github.com/cms-sw/cmssw/pull/37180

**Comment by cecilecaillol** [comment]
+l1

**Comment by missirol** [comment]
+hlt

**Comment by perrotta** [comment]
+1
- Verbatim backport of https://github.com/cms-sw/cmssw/pull/37180

**Comment by perrotta** [comment]
merge

**Comment by santocch** [comment]
+1

**Pull request merged**
