### PR TITLE
specify compression settings in offline output modules used by HLT

### PR DESCRIPTION
**Pull request by missirol**
#### PR description:

Follow-up of #39177 based on comments by @fwyzard:

 - more robust syntax in the replacement of online-to-offline output modules;
 - specify online compression settings (level, algorithm) in offline output modules.

This PR has no direct impact on any IB workflow. No differences are expected in the outputs of PR tests.

#### PR validation:

Private tests.

#### If this PR is a backport, please specify the original PR and why you need to backport that PR. If this PR will be backported, please specify to which release cycle the backport is meant for:

`CMSSW_12_4_X`
`CMSSW_12_5_X`

### CODE REVIEW

**Comment by missirol** [comment]
please test

**Comment by missirol** [comment]
+hlt

**Comment by perrotta** [comment]
+1

**Comment by perrotta** [comment]
merge

**Pull request merged**
