### PR TITLE
rename modifier `run3_2024_L1T` to `stage2L1Trigger_2024`

### PR DESCRIPTION
**Pull request by missirol**
#### PR description:

This PR suggests to rename the modifier introduced in #45352, in order to use a name that's consistent with other existing modifiers specific to the Stage-2 L1 Trigger, see
https://github.com/cms-sw/cmssw/blob/7320a6bb38b604b8c69c7e1ee57539fe71a53b9e/Configuration/Eras/python/Modifier_stage2L1Trigger_2017_cff.py
https://github.com/cms-sw/cmssw/blob/7320a6bb38b604b8c69c7e1ee57539fe71a53b9e/Configuration/Eras/python/Modifier_stage2L1Trigger_2018_cff.py
https://github.com/cms-sw/cmssw/blob/7320a6bb38b604b8c69c7e1ee57539fe71a53b9e/Configuration/Eras/python/Modifier_stage2L1Trigger_2021_cff.py

#### PR validation:

None.

#### If this PR is a backport, please specify the original PR and why you need to backport that PR. If this PR will be backported, please specify to which release cycle the backport is meant for:

Will be backported down to `CMSSW_14_0_X`.

### CODE REVIEW

**Comment by mmusich** [comment]
I would suggest to hold this until (at least) https://github.com/cms-sw/cmssw/pull/45242 gets merged and after that this one is updated accordingly.

**Comment by aloeliger** [comment]
@mmusich I am fine with this change to the quick thing I threw together. Do you want to issue an explicit hold on this one or let it go?

**Comment by aloeliger** [comment]
+l1
- Fine with the rename, and https://github.com/cms-sw/cmssw/pull/45242 has been merged

**Comment by missirol** [comment]
"hold"

I guess I have to rebase in order to include #45242.

Will #45242 be backported to 14_1_X ? I don't have a strong opinion, but I guess it would be clearer to rename this modifier in all affected cycles (14_0_X and higher).

**Comment by mmusich** [comment]
> Will https://github.com/cms-sw/cmssw/pull/45242 be backported to 14_1_X ? 

done at https://github.com/cms-sw/cmssw/pull/45819

> I don't have a strong opinion, but I guess it would be clearer to rename this modifier in all affected cycles (14_0_X and higher).

fwiw, I agree

**Comment by missirol** [comment]
Thanks @mmusich . I'll rebase this one, then open backports once #45805 and #45819 are integrated.

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by aloeliger** [comment]
+l1

**Comment by tjavaid** [comment]
+1

**Pull request merged**
