### PR TITLE
Run4-hgx251 Small update to the code

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Clean up the code with some inputs from Carl and Kevin

#### PR validation:

Tested using runTheMatrix test workflows

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by kpedro88** [comment]
+upgrade

**Comment by cvuosalo** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
