### PR TITLE
Herwig7Interface

### PR DESCRIPTION
**Pull request by mharrend**
Include Herwig7Interface in the CMSSW GeneratorInterface

### CODE REVIEW

**Comment by perrozzi** [comment]
please test

**Comment by smuzaffar** [comment]
please test with cms-sw/cmsdist#2889

**Comment by mharrend** [comment]
@davidlange6 Can you please explain to @Andrej-CMS and myself why this PR was closed?
This PR needs as a dependency the cms-dist #2889 PR and should then be merged.

Thanks, Marco

**Comment by perrozzi** [comment]
@davidlange6 this is the issue that Kenneth was mentioning during the O&C week talk. Can you please give any advice on this PR? If there is no issue, we would like it to be re-opened and integrated to your earliest conveinence. Thanks

**Comment by davidlange6** [comment]
this branch of cmssw is obsolete. the externals require some discussion (esp. form)

**Comment by Andrej-CMS** [comment]
Hello,

I'm open for discussion any time. If you have any suggestions, we could 
have a Skype/Vidyo chat or discuss it during a meeting.

Kind regards,

Andrej

**Comment by perrozzi** [comment]
@Andrej-CMS you just need to port this PR to the newer branch. The obvious one would be CMSSW_9_0_X but maybe direclty to the master branch, @davidlange6 can comment

**Pull request closed without merging**
