### PR TITLE
Checksum parameter cfi export (75X)

### PR DESCRIPTION
**Pull request by smorovic**
CRC32 is checked by default, however parameter to control this is not exported.

We need a way to switch this off in heavy ion test setup, so two changes are provided:
- export of the parameter (for the new template)
- reuse adler32 setting as default (as we replaced adler32 with crc32c, for existing templates).

Also, two other not previously exported parameters were added to cfi files, and input source parameter defaults were changed to defaults used in production.

Backport of #11535

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by mommsen** [comment]
+1

**Comment by cvuosalo** [comment]
+1

For #11536 6a5ad2f8da87b282c0d6e391369ebecf26544c12

For Heavy Ions, exporting checksum parameter so it can be toggled as necessary. There should be no change in monitored quantities. #11535 is the 76X version of this PR, and it has already been approved by Reco.

The code changes are satisfactory, and Jenkins tests against baseline CMSSW_7_5_X_2015-09-27-2300 show no significant differences, as expected.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
