### PR TITLE
Properly set number of threads in CmsRun python module

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

Use the values specified in the options PSet or the default of 1 thread when using the CmsRun python class.

The code used to handle the threading options was refactored into stand alone functions.

#### PR validation:

Code compiles. Ran a simple test configuration using different numbers of threads specified in the configuration within gdb and watch how many threads were created.

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by Dr15Jones** [comment]
The RECO differences are all from the MessageLogger. All but 1 if the histogram differences are also from the MessageLogger.

**Comment by makortel** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
