### PR TITLE
DD4hep: CmsTrackerLevelBuilder Fix Tracker Geometry Navigation

### PR DESCRIPTION
**Pull request by vargasa**
#### PR description:

Progress on https://github.com/cms-sw/cmssw/issues/31143. See https://github.com/cms-sw/cmssw/pull/31307#issuecomment-685423687

#### PR validation:

```
$ cmsRun SimG4Core/Configuration/test/dd4hep_ZMM_Run3_Step1_cfg.py
```

`master` (dd4hep) lead us to:
```
/OCMS_1/CMSE_1/Tracker_1/PixelBarrel_1/pixbarlayer0:PixelBarrelLayer0_1/PixelBarrelLadderFull0_1/PixelBarrelModuleBoxFull_1/PixelBarrelModuleFullMinus_1/PixelBarrelHybridFull_1
/OCMS_1/CMSE_1/Tracker_1/PixelBarrel_1/pixbarlayer0:PixelBarrelLayer0_1/PixelBarrelLadderFull0_1/PixelBarrelModuleBoxFull_1/PixelBarrelModuleFullMinus_1/PixelBarrelCapacitorStripFull_1
/OCMS_1/CMSE_1/Tracker_1/PixelBarrel_1/pixbarlayer0:PixelBarrelLayer0_1/PixelBarrelLadderFull0_1/PixelBarrelModuleBoxFull_1/PixelBarrelModuleFullMinus_1/PixelBarrelCapacitorStripFull_2
/OCMS_1/CMSE_1/Tracker_1/PixelBarrel_1/pixbarlayer0:PixelBarrelLayer0_1/PixelBarrelLadderFull0_1/PixelBarrelModuleBoxFull_1/PixelBarrelModuleFullMinus_1/PixelBarrelMountClipFull_1
```
`DDCMS/Core` (reference) lead us to:
```
CmsTrackerLevelbuilder<DDFilteredView>::build/cms:OCMS[0]/cms:CMSE[1]/tracker:Tracker[1]/pixbar:PixelBarrel[1]/pixbarlayer0:PixelBarrelLayer0[1]/pixbarladderfull0:PixelBarrelLadderFull0[1]/pixbarladderfull0:PixelBarrelModuleBoxFull[1]/pixbarladderfull0:PixelBarrelModuleFullMinus[1]/pixbarladderfull0:PixelBarrelSensorFull[1]/pixbarladderfull0:PixelBarrelActiveFull0[1]
CmsTrackerLevelbuilder<DDFilteredView>::build/cms:OCMS[0]/cms:CMSE[1]/tracker:Tracker[1]/pixbar:PixelBarrel[1]/pixbarlayer0:PixelBarrelLayer0[1]/pixbarladderfull0:PixelBarrelLadderFull0[1]/pixbarladderfull0:PixelBarrelModuleBoxFull[1]/pixbarladderfull0:PixelBarrelModuleFullMinus[2]/pixbarladderfull0:PixelBarrelSensorFull[1]/pixbarladderfull0:PixelBarrelActiveFull0[1]
CmsTrackerLevelbuilder<DDFilteredView>::build/cms:OCMS[0]/cms:CMSE[1]/tracker:Tracker[1]/pixbar:PixelBarrel[1]/pixbarlayer0:PixelBarrelLayer0[1]/pixbarladderfull0:PixelBarrelLadderFull0[1]/pixbarladderfull0:PixelBarrelModuleBoxFull[1]/pixbarladderfull0:PixelBarrelModuleFullMinus[3]/pixbarladderfull0:PixelBarrelSensorFull[1]/pixbarladderfull0:PixelBarrelActiveFull0[1]
CmsTrackerLevelbuilder<DDFilteredView>::build/cms:OCMS[0]/cms:CMSE[1]/tracker:Tracker[1]/pixbar:PixelBarrel[1]/pixbarlayer0:PixelBarrelLayer0[1]/pixbarladderfull0:PixelBarrelLadderFull0[1]/pixbarladderfull0:PixelBarrelModuleBoxFull[1]/pixbarladderfull0:PixelBarrelModuleFullMinus[4]/pixbarladderfull0:PixelBarrelSensorFull[1]/pixbarladderfull0:PixelBarrelActiveFull0[1]
CmsTrackerLevelbuilder<DDFilteredView>::build/cms:OCMS[0]/cms:CMSE[1]/tracker:Tracker[1]/pixbar:PixelBarrel[1]/pixbarlayer0:PixelBarrelLayer0[1]/pixbarladderfull0:PixelBarrelLadderFull0[1]/pixbarladderfull0:PixelBarrelModuleBoxFull[1]/pixbarladderfull0:PixelBarrelModuleFullPlus[1]/pixbarladderfull0:PixelBarrelSensorFull[1]/pixbarladderfull0:PixelBarrelActiveFull0[1]
CmsTrackerLevelbuilder<DDFilteredView>::build/cms:OCMS[0]/cms:CMSE[1]/tracker:Tracker[1]/pixbar:PixelBarrel[1]/pixbarlayer0:PixelBarrelLayer0[1]/pixbarladderfull0:PixelBarrelLadderFull0[1]/pixbarladderfull0:PixelBarrelModuleBoxFull[1]/pixbarladderfull0:PixelBarrelModuleFullPlus[2]/pixbarladderfull0:PixelBarrelSensorFull[1]/pixbarladderfull0:PixelBarrelActiveFull0[1]
CmsTrackerLevelbuilder<DDFilteredView>::build/cms:OCMS[0]/cms:CMSE[1]/tracker:Tracker[1]/pixbar:PixelBarrel[1]/pixbarlayer0:PixelBarrelLayer0[1]/pixbarladderfull0:PixelBarrelLadderFull0[1]/pixbarladderfull0:PixelBarrelModuleBoxFull[1]/pixbarladderfull0:PixelBarrelModuleFullPlus[3]/pixbarladderfull0:PixelBarrelSensorFull[1]/pixbarladderfull0:PixelBarrelActiveFull0[1]
CmsTrackerLevelbuilder<DDFilteredView>::build/cms:OCMS[0]/cms:CMSE[1]/tracker:Tracker[1]/pixbar:PixelBarrel[1]/pixbarlayer0:PixelBarrelLayer0[1]/pixbarladderfull0:PixelBarrelLadderFull0[1]/pixbarladderfull0:PixelBarrelModuleBoxFull[1]/pixbarladderfull0:PixelBarrelModuleFullPlus[4]/pixbarladderfull0:PixelBarrelSensorFull[1]/pixbarladderfull0:PixelBarrelActiveFull0[1]
CmsTrackerLevelbuilder<DDFilteredView>::build/cms:OCMS[0]/cms:CMSE[1]/tracker:Tracker[1]/pixbar:PixelBarrel[1]/pixbarlayer0:PixelBarrelLayer0[1]/pixbarladderfull0:PixelBarrelLadderFull0[1]
...
```

 `thisPR` (dd4hep) lead us to:
```
/OCMS_1/CMSE_1/Tracker_1/PixelBarrel_1/pixbarlayer0:PixelBarrelLayer0_1/PixelBarrelLadderFull0_1/PixelBarrelModuleBoxFull_1/PixelBarrelModuleFullMinus_1/PixelBarrelSensorFull_1/PixelBarrelActiveFull0_1
/OCMS_1/CMSE_1/Tracker_1/PixelBarrel_1/pixbarlayer0:PixelBarrelLayer0_1/PixelBarrelLadderFull0_1/PixelBarrelModuleBoxFull_1/PixelBarrelModuleFullMinus_2/PixelBarrelSensorFull_1/PixelBarrelActiveFull0_1
/OCMS_1/CMSE_1/Tracker_1/PixelBarrel_1/pixbarlayer0:PixelBarrelLayer0_1/PixelBarrelLadderFull0_1/PixelBarrelModuleBoxFull_1/PixelBarrelModuleFullMinus_3/PixelBarrelSensorFull_1/PixelBarrelActiveFull0_1
/OCMS_1/CMSE_1/Tracker_1/PixelBarrel_1/pixbarlayer0:PixelBarrelLayer0_1/PixelBarrelLadderFull0_1/PixelBarrelModuleBoxFull_1/PixelBarrelModuleFullMinus_4/PixelBarrelSensorFull_1/PixelBarrelActiveFull0_1
/OCMS_1/CMSE_1/Tracker_1/PixelBarrel_1/pixbarlayer0:PixelBarrelLayer0_1/PixelBarrelLadderFull0_1/PixelBarrelModuleBoxFull_1/PixelBarrelModuleFullPlus_1/PixelBarrelSensorFull_1/PixelBarrelActiveFull0_1
/OCMS_1/CMSE_1/Tracker_1/PixelBarrel_1/pixbarlayer0:PixelBarrelLayer0_1/PixelBarrelLadderFull0_1/PixelBarrelModuleBoxFull_1/PixelBarrelModuleFullPlus_2/PixelBarrelSensorFull_1/PixelBarrelActiveFull0_1
/OCMS_1/CMSE_1/Tracker_1/PixelBarrel_1/pixbarlayer0:PixelBarrelLayer0_1/PixelBarrelLadderFull0_1/PixelBarrelModuleBoxFull_1/PixelBarrelModuleFullPlus_3/PixelBarrelSensorFull_1/PixelBarrelActiveFull0_1
/OCMS_1/CMSE_1/Tracker_1/PixelBarrel_1/pixbarlayer0:PixelBarrelLayer0_1/PixelBarrelLadderFull0_1/PixelBarrelModuleBoxFull_1/PixelBarrelModuleFullPlus_4/PixelBarrelSensorFull_1/PixelBarrelActiveFull0_1
...
```

### CODE REVIEW

**Comment by vargasa** [comment]
@cvuosalo urgent please

**Comment by civanch** [comment]
please test

**Comment by cvuosalo** [comment]
urgent

**Comment by cvuosalo** [comment]
@vargasa In the PR description, please clarify what "previous navigation" means. Is it old DD or DD4hep? Similarly, what does "ddd" mean?

**Comment by vargasa** [comment]
Hello @civanch, @cvuosalo  if there's no comments can you approve this please?

**Comment by silviodonato** [comment]
please test
the differences were related to #31316

**Comment by cvuosalo** [comment]
+1

**Comment by vargasa** [comment]
@cvuosalo last set of commits are intended to tackle this: https://github.com/cms-sw/cmssw/issues/31143#issuecomment-686556068 and make it a bit easier to make the Comparison. As mentioned here https://github.com/cms-sw/cmssw/issues/31143#issuecomment-686600483 this seems not to be a complete story regarding the navigation but I won't add more commits to this PR 

FYI @ghugo83 new set of logs:
dd: https://drive.google.com/file/d/14UV9pd3H2TVxD-_4ItGAnNtGMjp947fv/view
dd4hep: https://drive.google.com/file/d/1WJD0klTvI4Cq_H6_-9WosQaiwcM6NeIr/view

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
+1

**Comment by silviodonato** [comment]
Kind reminder @cms-sw/simulation-l2

**Comment by civanch** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
