### PR TITLE
Add esConsumes to OmtfPacker and OmtfUnpacker

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

- added esConsumes to modules
- modified helpers to not directly use edm::EventSetup

#### PR validation:

Code compiles.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by qliphy** [comment]
please test with #34638

**Comment by cecilecaillol** [comment]
+l1

**Comment by qliphy** [comment]
+1

**Pull request merged**
