### PR TITLE
Update GEM Offline DQM

### PR DESCRIPTION
**Pull request by seungjin-yang**
#### PR description:

* `bookEfficiencyEtaPartition` is renamed `bookEfficiencyDetector` and the efficiency plot is created for each GEM layer, not station.
* New `bookEfficiencyEtaPartition` creates the 1D efficiency vs ieta plots
* Change the default of `useSkipLayer` to true for the both beam and cosmics scenarios.
* Reduce the number of bins of the phi efficiency plots.
* `buildGEMLayers` make two disks, the odd chambers and the even chambers of GE11.
* Add `TransientTrackBuilder_cfi` in `GEMEfficiencyAnalyzer` cfi files for use standalone.

#### PR validation:
This PR is tested using `/RelValZMM_14/CMSSW_12_0_0_pre1-113X_mcRun3_2021_realistic_v10-v1/GEN-SIM-RECO` (i.e. 11650 (ZMM_14))  

PR validation results can be found at [the local offline DQM GUI server](http://offlinedqm.sscc.uos.ac.kr:50200/dqm/offline). Please look at the GEM workspace.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

This PR is NOT a backport.

This update will be backported to CMSSW_11_3_X through other PR for MWGR#4.

@jshlee, @szaleski

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by jfernan2** [comment]
Backport to 11_3_X needed in view of MWGR4

**Comment by qliphy** [comment]
+1

**Pull request merged**
