### PR TITLE
modernize `SiStripProcessedRawDigiProducer`

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

Title says it all, getting rid of one more deprecation warning in the `AnalysisAlgos/SiStripClusterInfoProducer` subsystem, thanks to the new flagging from core s/w group (see https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-cfc78f/23964/build-logs/)
Technical, part of the migrations in https://github.com/cms-sw/cmssw/issues/36404.
Profited to clean-up headers, use range-based loop and merging plugin header with implementation.

#### PR validation:

`cmssw` compiles

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by perrotta** [comment]
+1

**Comment by perrotta** [comment]
merge

**Comment by santocch** [comment]
+1

**Pull request merged**
