### PR TITLE
Add a test for Alpaka libraries and build rules [14.0.x]

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

The package `HeterogeneousTest/AlpakaDevice` implements a header only library that defines Alpaka device-only functions, and a plugin and test that use them.

The package `HeterogeneousTest/AlpakaKernel` implements a header only library that imports device functions from `HeterogeneousTest/AlpakaDevice` to define Alpaka kernels, and a plugin and test that use them.

The package `HeterogeneousTest/AlpakaWrapper` implements a library that imports kernels from HeterogeneousTest/AlpakaKernel to define and export host-only wrappers around them, usable by non-Alpaka libraries, plugins and applications, and implements a plugin and test that use them.

The package `HeterogeneousTest/AlpakaOpaque` implements a library that imports kernels from `HeterogeneousTest/AlpakaKernel` to define and export host-only wrappers around the whole Alpaka section, usable by libraries, plugins and applications that are not explicitly Alpaka-aware, and implements a plugin and test that use them.

In addition, fix the CUDA and ROCm documentation, and various typos in the ROCm tests.

#### PR validation:

The new unit tests build and pass (on a machine with NVIDIA A10 GPU and an AMD Radeon Pro W7600):
```
Creating test log file logs/el8_amd64_gcc12/testing.log
Pass    0s ... HeterogeneousTest/AlpakaDevice/testAlpakaDeviceAdditionSerialSync
Pass    0s ... HeterogeneousTest/AlpakaOpaque/testAlpakaDeviceAdditionOpaqueSerialSync
Pass    0s ... HeterogeneousTest/AlpakaKernel/testAlpakaDeviceAdditionKernelSerialSync
Pass    0s ... HeterogeneousCore/ROCmUtilities/testHipCheck
Pass    0s ... HeterogeneousTest/AlpakaWrapper/testAlpakaDeviceAdditionWrapperSerialSync
Pass    0s ... HeterogeneousCore/ROCmUtilities/testRequireROCmDevices
Pass    0s ... HeterogeneousTest/ROCmOpaque/testRocmDeviceAdditionOpaque
Pass    0s ... HeterogeneousTest/AlpakaOpaque/testAlpakaDeviceAdditionOpaqueROCmAsync
Pass    0s ... HeterogeneousTest/ROCmWrapper/testRocmDeviceAdditionWrapper
Pass    0s ... HeterogeneousTest/AlpakaWrapper/testAlpakaDeviceAdditionWrapperROCmAsync
Pass    0s ... HeterogeneousTest/ROCmDevice/testRocmDeviceAddition
Pass    0s ... HeterogeneousTest/AlpakaKernel/testAlpakaDeviceAdditionKernelROCmAsync
Pass    0s ... HeterogeneousTest/AlpakaDevice/testAlpakaDeviceAdditionROCmAsync
Pass    0s ... HeterogeneousTest/ROCmKernel/testRocmDeviceAdditionKernel
Pass    1s ... HeterogeneousTest/ROCmOpaque/testROCmTestOpaqueAdditionModule
Pass    1s ... HeterogeneousTest/ROCmDevice/testROCmTestDeviceAdditionModule
Pass    1s ... HeterogeneousTest/ROCmOpaque/testROCmTestAdditionModules
Pass    1s ... HeterogeneousTest/ROCmKernel/testROCmTestKernelAdditionModule
Pass    1s ... HeterogeneousTest/ROCmWrapper/testROCmTestWrapperAdditionModule
Pass    4s ... HeterogeneousTest/AlpakaOpaque/testAlpakaDeviceAdditionOpaqueCudaAsync
Pass    4s ... HeterogeneousTest/CUDAWrapper/testCudaDeviceAdditionWrapper
Pass    4s ... HeterogeneousTest/CUDAKernel/testCudaDeviceAdditionKernel
Pass    4s ... HeterogeneousTest/AlpakaDevice/testAlpakaDeviceAdditionCudaAsync
Pass    5s ... HeterogeneousTest/AlpakaKernel/testAlpakaDeviceAdditionKernelCudaAsync
Pass    5s ... HeterogeneousTest/AlpakaWrapper/testAlpakaDeviceAdditionWrapperCudaAsync
Pass    5s ... HeterogeneousTest/CUDAOpaque/testCudaDeviceAdditionOpaque
Pass    5s ... HeterogeneousTest/CUDADevice/testCudaDeviceAddition
Pass    9s ... HeterogeneousTest/CUDAOpaque/testCUDATestOpaqueAdditionModule
Pass    9s ... HeterogeneousTest/CUDAWrapper/testCUDATestWrapperAdditionModule
Pass    9s ... HeterogeneousTest/CUDAKernel/testCUDATestKernelAdditionModule
Pass    9s ... HeterogeneousTest/CUDADevice/testCUDATestDeviceAdditionModule
Pass    9s ... HeterogeneousTest/AlpakaWrapper/testAlpakaTestWrapperAdditionModule
Pass    9s ... HeterogeneousTest/CUDAOpaque/testCUDATestAdditionModules
Pass    9s ... HeterogeneousTest/AlpakaKernel/testAlpakaTestKernelAdditionModule
Pass    9s ... HeterogeneousTest/AlpakaDevice/testAlpakaTestDeviceAdditionModule
Pass    9s ... HeterogeneousTest/AlpakaOpaque/testAlpakaTestOpaqueAdditionModule
Pass   10s ... HeterogeneousTest/AlpakaOpaque/testAlpakaTestAdditionModules
>> Test sequence completed for CMSSW CMSSW_14_0_4
```

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport of #44622 to CMSSW_14_0_X to ensure the Alpaka build rules are correct.

### CODE REVIEW

**Comment by fwyzard** [comment]
enable gpu

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
backport #44622

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
+heterogeneous

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
