### PR TITLE
Update MuTauSkim_cff with new Tau POG Isolation from Ram (7_4_X)

### PR DESCRIPTION
**Pull request by kfjack**
Update the MuTauSkim_cff.py in the skim matrix with the new config from Ram, with the new Tau POG isolation. Back port from PR #10296.

### CODE REVIEW

**Comment by franzoni** [comment]
please test

**Comment by franzoni** [comment]
please test

**Comment by franzoni** [comment]
please test

**Comment by franzoni** [comment]
+1

CMSSW_7_4_7_patch2:   
cmsDriver.py test --conditions pippo -s SKIM:@SingleMuon --no_exec --dump_python

**Comment by franzoni** [comment]
+1

**Comment by smuzaffar** [comment]
please test

**Comment by davidlange6** [comment]
+1

**Pull request merged**
