### PR TITLE
Fix issue with Strip CalibTree production and improve unit tests

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

After integration of PR https://github.com/cms-sw/cmssw/pull/31002 I noticed that the production of Strip calibTrees was substantially slowed down and identified the motivation in the migration of `ShallowGainCalibration` from a `stream` to `global`. 
I revert in this PR part of the changes (commit 2c77c10) leading to the slow-down.
Additionally:
- I address the comment https://github.com/cms-sw/cmssw/pull/31002#discussion_r495831968 about the content of the `plugins/BuildFile.xml` of that package (commit: 7f83ffc)
- improve the unit test, in order to to run multi-threaded (but not yet using concurrent lumis), setting same compression settings as used in production and removing few missing trigger errors currently present in the IBs (see e.g. [log](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc820/CMSSW_11_2_X_2020-10-01-1100/unitTestLogs/CalibTracker/SiStripCommon#/71)) in commit 3da8316 
- make `ShallowTree` an `edm::one::EDAnalyzer` (commit 4671911)

#### PR validation:

Tested in `CMSSW_11_2_X_2020-09-30-1100` using:
```
 cmsRun testProduceCalibrationTree_cfg.py inputFiles="/store/express/Run2018D/StreamExpress/ALCARECO/SiStripCalMinBias-Express-v1/000/323/492/00000/ED5EFF5C-1B7B-564D-974B-15499A1B7D4E.root" inputCollection="ALCARECOSiStripCalMinBias" conditionGT="101X_dataRun2_Express_v8"
```
I get:

```
TimeReport> Time report complete in 360.07 seconds
 Time Summary: 
 - Min event:   0.444757
 - Max event:   21.3634
 - Avg event:   1.96364
 - Total loop:  330.235
 - Total init:  29.7974
 - Total job:   360.07
 - EventSetup Lock:   0
 - EventSetup Get:   0
 Event Throughput: 2.01372 ev/s
 CPU Summary: 
 - Total loop:  1286.18
 - Total init:  11.6651
 - Total extra: 0
 - Total job:   1297.95
 Processing Summary: 
 - Number of Events:  665
 - Number of Global Begin Lumi Calls:  1
 - Number of Global Begin Run Calls: 1
```

while with this branch:

```
TimeReport> Time report complete in 76.3658 seconds
 Time Summary: 
 - Min event:   0.0435982
 - Max event:   21.6353
 - Avg event:   0.271647
 - Total loop:  50.1936
 - Total init:  26.1378
 - Total job:   76.3658
 - EventSetup Lock:   0
 - EventSetup Get:   0
 Event Throughput: 13.2487 ev/s
 CPU Summary: 
 - Total loop:  144.93
 - Total init:  11.4757
 - Total extra: 0
 - Total job:   156.509
 Processing Summary: 
 - Number of Events:  665
 - Number of Global Begin Lumi Calls:  1
 - Number of Global Begin Run Calls: 1
```

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Not a backport, no backport is needed.

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
@yuanchao, @christopheralanwest, @tocheng, @tlampen, @pohsun

would it be possible to review this bug-fix at earliest convenienve?

**Comment by silviodonato** [comment]
kind reminder @cms-sw/alca-l2

**Comment by christopheralanwest** [comment]
+1

For my education, why does commit 2c77c10c608b844450bd3f015c81304fac785ab9 make such a large impact on the timing?

**Comment by silviodonato** [comment]
+1

**Comment by mmusich** [comment]
@christopheralanwest 

> For my education, why does commit 2c77c10 make such a large impact on the timing?

To be completely honest I am not sure.
I did a bit of profiling in the two versions: `CMSSW_11_2_0_pre7` (without the fix) and `CMSSW_11_2_X_2020-10-21-2300` (with the fix), by running igprof:
```bash
igprof -pp -z -o ig.gz -t cmsRun cmsRun testProduceCalibrationTree_cfg.py inputFiles="/store/express/Run2018D/StreamExpress/ALCARECO/SiStripCalMinBias-Express-v1/000/323/492/00000/ED5EFF5C-1B7B-564D-974B-15499A1B7D4E.root" inputCollection="ALCARECOSiStripCalMinBias" conditionGT="auto:run3_data_express" > & a.log

igprof-analyse --sqlite -v --demangle --gdb ig.gz | sed -e 's/INSERT INTO files VALUES (\([^,]*\), \"[^$]*/INSERT INTO files VALUES (\1, \"ABCD\");/g' | sqlite3 ig.sql3
```

results are here:
* `CMSSW_11_2_0_pre7` :  [link](http://musich.web.cern.ch/musich/cgi-bin/igprof-navigator/ig_calibtree/18)
image


* `CMSSW_11_2_X_2020-10-21-2300`: [link](http://musich.web.cern.ch/musich/cgi-bin/igprof-navigator/ig_calibtreeNew/256)
image

`ShallowGainCalibration::produce()` goes from 92% of the total to 1.14%, apparently because of `std::map` operations (?)

**Pull request merged**
