### PR TITLE
Revert "Workflow 511.1: herwig7+ MG5+Openloops pptoee at NLO QCD"

### PR DESCRIPTION
**Pull request by fabiocos**
Reverts cms-sw/cmssw#24813

The added workflow systematically fails the 2 hours time limit of the IB, it is clearly not suitable for regular test. This may point to different issues:
- recalculation of matrix elements at every generation run instead of pre-computing them (a la gridpack), this looks a questionable structural choice;
- according to @efeyazgan openloops seems here much slower than in association with sherpa. Provided the comparison is on a similar process, this might point to some integration issues;
- according to @davidlange6 checks the code is likely not optimal in terms of performances in several places.
In agreement with @efeyazgan I revert this PR, as it looks pointless. A follow up should be done in view of possible use of this generator configuration in production (it looks quite inefficient).

### CODE REVIEW

**Comment by fabiocos** [comment]
please test

purely academic in this case

**Comment by smuzaffar** [comment]
@fabiocos , @davidlange6 has built openloops with optimization ( https://github.com/cms-sw/cmsdist/pull/4448 ) and workflow 511.1 ran with in 1h15. I would suggest to get the cmsdist PR merged

**Comment by davidlange6** [comment]
please see also https://github.com/cms-sw/cmsdist/pull/4448

**Comment by fabiocos** [comment]
@davidlange6 thank you for the update. @efeyazgan @qliphy confirm my understanding that there is no initial integration providing gridpacks that can be reused, which makes this approach suboptimal in any case. This is still under work by authors. Anyway you work could be useful for future developments as well, regardless of the specific problem of this test. Let's merge your fix and see, In case this PR can be put on hold ot just closed if the GEN conveners see a benefit to keep the test in the sequence (as it was originally proposed..)

**Comment by fabiocos** [comment]
hold

**Comment by efeyazgan** [comment]
"> @davidlange6 thank you for the update. @efeyazgan @qliphy confirm my understanding that there is no initial integration providing gridpacks that can be reused, which makes this approach suboptimal in any case. This is still under work by authors. Anyway you work could be useful for future developments as well, regardless of the specific problem of this test. Let's merge your fix and see, In case this PR can be put on hold ot just closed if the GEN conveners see a benefit to keep the test in the sequence (as it was originally proposed..)"

@fabiocos Yes, there is no "Herpack" yet (@Andrej-CMS can give more info).

**Comment by Andrej-CMS** [comment]
@efeyazgan 
Dear Efe,
This is indeed not yet available, but I'm working on it.

**Comment by fabiocos** [comment]
The updated by @davidlange6 of the external has indeed prevented the TimeOut problem. Still is this the way we want to run? Is the GEN group willing to keep this test waiting for a more production-friendly approach?

**Comment by efeyazgan** [comment]
+1

**Comment by prebello** [comment]
+1

**Comment by fabiocos** [comment]
unhold

**Comment by fabiocos** [comment]
+1

from discussions with the GEN conveners, the workflow needs a revision where LHE files are allowed.
This is still work in progress, and there is no need to exercise at every IB this workflow as it is.

**Comment by fabiocos** [comment]
merge

**Pull request merged**
