### PR TITLE
CMSSW changes for Eigen API changes

### PR DESCRIPTION
**Pull request by iarspider**
#### PR description:

Companion PR to cms-sw/cmsdist#8533

#### PR validation:

Bot tests

### CODE REVIEW

**Comment by smuzaffar** [comment]
@iarspider , isn;t it duplicate of https://github.com/cms-sw/cmssw/pull/40645 ?

**Comment by iarspider** [comment]
Somewhat - the method in question was moved once again since that PR.

**Comment by smuzaffar** [comment]
https://github.com/cms-sw/cmssw/pull/40645 should have worked as there are no git conflicts in change in https://github.com/cms-sw/cmssw/pull/40645 and current state of cmssw master branch. Anyway, I am closing https://github.com/cms-sw/cmssw/pull/40645 in favor of this PR

**Comment by fwyzard** [comment]
+heterogeneous

**Comment by rappoccio** [comment]
+1

**Pull request merged**
