### PR TITLE
Revert "Run4-hgx247 Add some new features for HGCal"

### PR DESCRIPTION
**Pull request by silviodonato**
Reverts cms-sw/cmssw#30323

...for testing with #30363

### CODE REVIEW

**Comment by silviodonato** [comment]
please test

**Comment by silviodonato** [comment]
As discussed in https://github.com/cms-sw/cmssw/pull/30363#issuecomment-651630784, I will merge this PR in order to be able to regenerate the HGCal trigger primitive with D49, as they are needed for the re-L1 of the HLT TDR samples.
cc: @jbsauvan @bsunanda

**Comment by silviodonato** [comment]
merge

**Comment by cvuosalo** [comment]
+1

**Pull request merged**
