### PR TITLE
Converted ObjectSelector system to use edm::stream::EDFilter<>

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

- Looking at all uses of ObjectSelector showed they were all implemented in a thread-friendly manner
- Created a ObjectSelectorLegacy class in case an analysis user has their own code which can't be immediately migrated to be thread-friendly.

NOTE: this includes the commits from #35562. It is OK if that PR is merged first (to get rid of the initial false positives) or this one is merged first.

#### PR validation:

Code compiles.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
The code violation is a false positive. The using namespace happens internally to a member function. The true code violations is when the using namespace happens at global scope within a header as that pollutes the global namespace.

**Comment by tvami** [comment]
+alca

**Comment by slava77** [comment]
+reconstruction

for https://github.com/cms-sw/cmssw/pull/35575	40a49a8
- code changes are essentially technical, in line with the PR description and the follow up review
- jenkins tests pass and comparisons with the baseline show no (relevant) differences

**Comment by perrotta** [comment]
+1
- Technical
- @Dr15Jones could you please update the PR description field and cancel the reference to the `ObjectSelectorLegacy` class (now removed from this PR)?

**Pull request merged**
