### PR TITLE
Update BeamSpot DQM client configurations

### PR DESCRIPTION
**Pull request by francescobrivio**
#### PR description:
- Updated some parameters needed for the DB logging (`jobName` and `saveLogsOnDB`)
- Fixed some parameters in response to comments from DQM team in #31965 

#### PR validation:
Tested privately using fake beamspot values.

#### Backporting:
I will provide a backport to 11_1_X to be used in the upcoming MWGR.

### CODE REVIEW

**Comment by jfernan2** [comment]
please test with #31206

**Comment by jfernan2** [comment]
please abort

**Comment by jfernan2** [comment]
please test

**Comment by francescobrivio** [comment]
I rebased and fixed a minor typo in the BeamSpot monitor names.

**Comment by jfernan2** [comment]
please test

**Comment by francescobrivio** [comment]
The error in the log seems related to DB:
```
----- Begin Fatal Exception 16-Nov-2020 10:06:58 CET-----------------------
An exception of category 'ConditionDatabase' occurred while
   [0] Processing global end LuminosityBlock run: 334393 luminosityBlock: 1
   [1] Calling method for module BeamMonitor/'dqmBeamMonitor'
Exception Message:
Failure while saving log on database:A table named "O2O_RUN" does not exist ( CORAL : "ISchema::ISchema::tableHandle" from "CORAL/RelationalPlugins/sqlite" ) from Logger::saveOnDb 
----- End Fatal Exception -------------------------------------------------
```
@ggovi can you suggest a way to fix this?

**Comment by jfernan2** [comment]
please test

**Comment by francescobrivio** [comment]
I fixed the `saveLogsOnDB` option in case of "not live" running conditions and run the unitTest locally with success.

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+1
Backport sucessfully tested at Online DQM playback

**Comment by silviodonato** [comment]
+1

**Pull request merged**
