### PR TITLE
EcalHaloDataProducer: setting input photon collection to empty string

### PR DESCRIPTION
**Pull request by lathomas**
Fix of the issue raised here: 
https://github.com/cms-sw/cmssw/issues/15781#issuecomment-245909412
This is the 80X equivalent of https://github.com/cms-sw/cmssw/pull/15799

### CODE REVIEW

**Comment by slava77** [comment]
backport of #15799

@lathomas does this change any output produced by this module ```EcalHaloData= cms.EDProducer("EcalHaloDataProducer",``` ?

**Comment by lathomas** [comment]
@slava77 
If the photon collection is anyway produced after this producer is run then it should not change anything. 
If  "photons" exist, then it can affect the superclusters stored in the class EcalHaloData: https://github.com/cms-sw/cmssw/blob/CMSSW_8_1_X/RecoMET/METAlgorithms/src/EcalHaloAlgo.cc#L172
These SC are currently not used anywhere though.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cmsbuild please test
to test just this PR with the more recent IB (CMSSW_8_0_X_2016-09-09-1100)

**Comment by cvuosalo** [comment]
-1

As explained in #15799, the 81X version of this PR, this PR changes RECO and Mini-AOD event content in some cases and so is not acceptable for a release already in production like 80X.

**Pull request closed without merging**
