### PR TITLE
update the 2016 halo filter for the hotline

### PR DESCRIPTION
**Pull request by mariadalfonso**
Updated the beam Halo working point for the hotline skim configuration

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
@mariadalfonso for my undestanding how large is the impact on the rates?

**Comment by mariadalfonso** [comment]
@mmusich is not large as the 2015 and 2016 were already very similar in rate.
Offline now we use this 2016 working point and lwe plan to use the same 2016 wp also for 2017 data taking.

**Comment by mmusich** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
