### PR TITLE
Run3-TB52 Update the geometry of the October TB and correct rotation of beam line

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Update the geometry of the first two October 2018 test beam setups of the high granularity calorimeter and also correct the rotation of the beam line

#### PR validation:

Tested with cfg files in SimG4CMS/HGCalTestBeam/test

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by kpedro88** [comment]
+upgrade

**Comment by cvuosalo** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by agrohsje** [comment]
+1

**Comment by silviodonato** [comment]
+1
@bsunanda I see you removed several ` #ifdef EDM_ML_DEBUG`. Did you do that on purpose?

**Comment by bsunanda** [comment]
Yes - for TB application people often use debugs in the analysis code
________________________________

**Pull request merged**
