### PR TITLE
Small fixes to special DB payload scripts

### PR DESCRIPTION
**Pull request by cvuosalo**
The scripts in this PR are used by experts to create DB payloads and to check their validity. While running these scripts, I noticed some minor issues I decided to fix.

The `create*Payloads.sh` scripts in this PR were issuing an unnecessary warning about a missing optional `txt` file. I added a test to silence it.

For the `runDDDvsDBGeometryValidation.sh` script, I added support for scenarios that have names like "Extended2017Plan1".

More fixes and enhancements could be added to these scripts, but those will have to wait for a later PR.

#### PR validation:

These scripts are only run manually, so they don't affect any workflows. I checked that the fixes in this PR do work.

### CODE REVIEW

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by jfernan2** [comment]
+1

**Comment by cvuosalo** [comment]
+1

**Comment by ggovi** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
