### PR TITLE
TOTEM Timing detectors: DQM backports for 10_1_X

### PR DESCRIPTION
**Pull request by forthommel**
backport of #22915 
and also #23240

This PR backports the TOTEM timing detectors DQM features introduced in the `10_2_X` development branch. It consists in the backports of the following PRs:
* #22915: core developments of the DQM
* #23240: small fix + elastic/diagonal DQM developments

Based on #23352.

### CODE REVIEW

**Comment by forthommel** [comment]
Not sure if you prefer a "lighter" backport PR only including the last ~10-15 commits related to the DQM, or if this format ("directly" mergeable after integration of #23352) is any better?

**Comment by civanch** [comment]
please test

**Comment by perrotta** [comment]
+1
- This is the same as #23352, plus a few DQM related commits: the additions here do not deal with reco, and therefore I sign this PR simply as a consequence of signing #23352 
- Both pull requests must be merged, because in #23352 a new commit has been added which is not (yet) included here
- I verified that the two PRs do not conflict each other and they can be merged in any order without rebasing

**Comment by nminafra** [comment]
@perrotta if you want I can do the same commit as in #23352 so that only one merge is necessary

**Comment by nminafra** [comment]
Thanks @perrotta, I'm ready to do it in case. I'll stand by for the moment.

**Comment by dmitrijus** [comment]
+1

**Comment by arunhep** [comment]
+1

**Comment by ggovi** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
