### PR TITLE
[GCC 11] Fix "this pointer is null" in RecoJets/JetProducers PileupJetIdAlgo

### PR DESCRIPTION
**Pull request by iarspider**
#### PR description:

Log file: https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc7_amd64_gcc11/CMSSW_12_1_X_2021-08-02-1100/RecoJets/JetProducers
Error message:
```
In function 'constexpr decltype (t1.eta()) reco::deltaR2(const T1&, const T2&) [with T1 = reco::Jet; T2 = reco::Candidate]',
    inlined from 'constexpr decltype (t1.eta()) reco::deltaR(const T1&, const T2&) [with T1 = reco::Jet; T2 = reco::Candidate]' at /data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/e3e3f354f3bbc00899d20eeb240b2272/opt/cmssw/slc7_amd64_gcc11/cms/cmssw/CMSSW_12_1_X_2021-08-02-1100/src/DataFormats/Math/interface/deltaR.h:31:21,
    inlined from 'PileupJetIdentifier PileupJetIdAlgo::computeIdVariables(const reco::Jet*, float, const reco::Vertex*, const VertexCollection&, double, bool)' at /data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/e3e3f354f3bbc00899d20eeb240b2272/opt/cmssw/slc7_amd64_gcc11/cms/cmssw/CMSSW_12_1_X_2021-08-02-1100/src/RecoJets/JetProducers/src/PileupJetIdAlgo.cc:668:42:
  /data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/e3e3f354f3bbc00899d20eeb240b2272/opt/cmssw/slc7_amd64_gcc11/cms/cmssw/CMSSW_12_1_X_2021-08-02-1100/src/DataFormats/Math/interface/deltaR.h:19:22: error: 'this' pointer is null [-Werror=nonnull]
    19 |     Float p2 = t2.phi();
      |                ~~~~~~^~
  /data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/e3e3f354f3bbc00899d20eeb240b2272/opt/cmssw/slc7_amd64_gcc11/cms/cmssw/CMSSW_12_1_X_2021-08-02-1100/src/DataFormats/Math/interface/deltaR.h:21:22: error: 'this' pointer is null [-Werror=nonnull]
    21 |     Float e2 = t2.eta();
      |                ~~~~~~^~
```
#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by iarspider** [comment]
@cmsbuild please test for slc7_amd64_gcc11

**Comment by smuzaffar** [comment]
please test

**Comment by slava77** [comment]
@camclean @alefisico 
please take a note of this bugfix in PileupJetIdAlgo.cc

@iarspider 
please mention `PileupJetIdAlgo` in the PR title

**Comment by slava77** [comment]
+reconstruction

for https://github.com/cms-sw/cmssw/pull/34772	5c584d2
- bugfix in  are in  PileupJetIdAlgo.cc `dRLead2nd` variable, which is apparently not used in the final ID; this is a member of the transient `PileupJetIdentifier`. So, no impact is expected on physics results.
- jenkins tests pass and comparisons with the baseline show no (relevant) differences

**Comment by perrotta** [comment]
+1

**Pull request merged**
