### PR TITLE
Full L1T O2O for 81X

### PR DESCRIPTION
**Pull request by kkotov**
This is a newer version that now includes L1T O2O for all trigger systems. The validation is tracked in the following issue: https://github.com/cms-l1t-offline/cmssw/issues/400

### CODE REVIEW

**Comment by mmusich** [comment]
@kkotov from the huge list of packages involved, looks like a rebsase is needed.

**Comment by mmusich** [comment]
please test

**Comment by kkotov** [comment]
@mmusich indeed, I've got several packages in this PR by merging my developments with one of our developer's branch. Nonetheless, in the David's list above, all but three packages under Alignment/* and SimCalorimetry* were updated (so this is indeed a big PR). I'll rebase my branch on CMSSW_8_1_0_pre10 now. Meanwhile, let's see if the tests above succeed.

**Comment by kkotov** [comment]
The the rebased version can be seen here: https://github.com/cms-sw/cmssw/compare/CMSSW_8_1_X...kkotov:rebasedFullL1TO2Ofor81X. If everything goes well, I'll push this rebased version back to the original fullL1TO2Ofor81X branch.

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
@kkotov is this branch still in development? Please let us know when the review can be started.

**Comment by kkotov** [comment]
No, I was actually curious if I could get away with Clang test failing as the code could still be built. But I've got '-1' and I'm addressing it now. Hopefully this will be the last issue. I'll comment on this thread once I'll fix it.

**Comment by mmusich** [comment]
please test

**Comment by kkotov** [comment]
In the last update I addressed the Clang test warnings. It now looks like _our_ L1T O2O  packages should compile just fine now.

**Comment by mmusich** [comment]
@kkotov would it be possible to clean the history of the commits removing the spurious ones?

**Comment by kkotov** [comment]
@mmusich I cleaned a bit the history earlier by rebasing (https://github.com/kkotov/cmssw/compare/rebasedFullL1TO2Ofor81X). Did you mean some specific commits or are you talking about moving to this rebased version?

**Comment by mmusich** [comment]
@mmusich the history of the `rebasedFullL1TO2Ofor81X` branch is certainly cleaner! please close this one and open a PR with the other branch. This will facilitate the review.

**Comment by mmusich** [comment]
please remove also: https://github.com/cms-sw/cmssw/commit/248cc548f2696cbf2e660fa81cfc62ef95414db7

**Pull request closed without merging**
