### PR TITLE
update TimePerEvent parameter of relval workflows

### PR DESCRIPTION
**Pull request by fabozzi**
Updating the default TimePerEvent parameter of relval workflows to avoid large underestimates of its value

### CODE REVIEW

**Comment by fabozzi** [comment]
please test

**Comment by fabozzi** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Comment by fabiocos** [comment]
@fabozzi for my understanding, is this parameter used to pre-allocate resources? Of course it may change wildly from sample to sample and step to step, besides being hardcoded for HARVESTING I see 
```
if len( [step for step in s[3] if "HARVESTGEN" in step] )>0:
                        chainDict['TimePerEvent']=0.01
```

**Comment by fabozzi** [comment]
@fabiocos this parameter is used by computing system to define the job splitting. We have been asked by comp-ops to avoid large underestimates of that number because it decreases performances and hinder delivery time of relvals.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
