### PR TITLE
Fix uploading the EventSetup conditions to multiple CUDA devices [11.3.x]

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

When multiple CUDA devices are available, each CUDA EventSetup object uses a different CUDA event to keep track if the conditions have been uploaded to each device. However, all events were associated to the default device, instead of the correct one, leading to a runtime error when multiple devices were used.

These changes associate to the correct CUDA device the events used to track if the conditions have been transferred.

#### PR validation:

See #34948 .

#### If this PR is a backport please specify the original PR and why you need to backport that PR:

Backport of #34948 .

Would be useful to have, if there are plans to use this release cycle for more online tests.

### CODE REVIEW

**Comment by fwyzard** [comment]
type bugfix

**Comment by fwyzard** [comment]
backport #34948

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
+heterogeneous

**Comment by makortel** [comment]
hold

**Comment by fwyzard** [comment]
please test

**Comment by makortel** [comment]
unhold

**Comment by makortel** [comment]
@cmsbuild, please test workflow 136.885501

Just to make sure

**Comment by makortel** [comment]
+1

**Comment by perrotta** [comment]
+1
- It includes the backport of #34968
- The fix applies when running a GPU-enabled job on a system with multiple GPUs: it doesn't affect standard workflows, and therefore backport to 10_3 for online runs and/or HLT studies is justified

**Pull request merged**
