### PR TITLE
Update 2021 global tags to include new pixel conditions

### PR DESCRIPTION
**Pull request by christopheralanwest**
#### PR description:

As agreed at https://github.com/cms-sw/cmssw/pull/27183#issuecomment-503710449, this PR introduces two global tag updates to autoCond for 2021 conditions. To simplify comparisons, PR #27183 only introduced the 2021 conditions needed for that PR. This PR adds the remaining two 2021 conditions for the following global tags:

106X_upgrade2021_realistic_v8:

Difference with respect to previous auto:phase1_2021_realistic GT:
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_upgrade2021_realistic_v8/106X_upgrade2021_realistic_v7
Difference with respect to candidate GT in PR #27183:
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_upgrade2021_realistic_v8/106X_upgrade2021_realistic_Candidate_2019_06_17_18_50_50
(The difference in GBRDWrapperRcd conditions is irrelevant for 2021 scenarios.)

106X_upgrade2021cosmics_realistic_deco_v3:

Difference with respect to previous auto:phase1_2021_cosmics GT:
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_upgrade2021cosmics_realistic_deco_v3/106X_upgrade2021cosmics_realistic_deco_v2
Difference with respect to candidate GT in PR #27183:
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_upgrade2021cosmics_realistic_deco_v3/106X_upgrade2021cosmics_realistic_deco_Candidate_2019_06_17_19_08_59

The PR first cherry-picks the GT commit from PR #27183 so that this PR can be merged as soon as #27183 is merged without generating conflicts.

A backport PR will be prepared.

#### PR validation:

Tested with `runTheMatrix.py -l 11624.0`.

#### if this PR is a backport please specify the original PR:

A backport PR will be prepared.

### CODE REVIEW

**Comment by christopheralanwest** [comment]
please test

**Comment by christopheralanwest** [comment]
+1

- This PR should be merged after #27183

**Comment by fabiocos** [comment]
@christopheralanwest but after the integration of #27183 there is a conflict to be solved...

**Comment by christopheralanwest** [comment]
The merge was resolved by preferring the content from commit 2a2af628d8380bb07bcebba4f8f41fef94a53450; that is, the new versioned GTs.

**Comment by christopheralanwest** [comment]
Please test

**Comment by christopheralanwest** [comment]
please test

**Comment by fabiocos** [comment]
please test

**Comment by christopheralanwest** [comment]
+1

- Changes introduced only in 2021 workflow 11624.0 and only in pixel or pixel-dependent plots, as expected
- Tags have been validated offline by pixel experts (for example, https://indico.cern.ch/event/824860/#19-tracker-preparation-for-end) and are already in use in production of relvals that use the `106X_mcRun3_2021_realistic_v1` global tag

**Comment by fabiocos** [comment]
+1

**Pull request merged**
