### PR TITLE
Hcal digi validation

### PR DESCRIPTION
**Pull request by kencall**
This address the memory leak in Phase 2 work flows when HcalDigisValidation doesn't proper decode SimHit DetIDs when testNumbering is enabled.

It also fixes a bug in 2017 Work flows where HE and HF digi plots were not being filled, and more cleanly initializes vectors of doubles.

### CODE REVIEW

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by kencall** [comment]
It doesn’t look like the tests have been triggered.

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
@kpedro88 - I see this isn't the first place - but there is really no way to hide the TB dependency here?  I find it rather awkward to have this coming into the mainstream validation codes.

**Comment by kpedro88** [comment]
@davidlange6 I'm not sure what you mean by TB dependency. TestNumbering is a setting for the HCAL Geant4 simulation, where we keep SimHits for all layers separately (instead of ganging together into the reco depths). This uses a non-standard ID which has to be decoded properly.

**Comment by davidlange6** [comment]
interesting - seems that wasn’t the original purpose of the class (given its documentation). Don’t you think we need to fix the name of this stuff?

**Comment by kpedro88** [comment]
well, we could update the comments in the source code, but I think the name "TestNumbering" is fairly generic and not necessarily related to test beam

**Comment by davidlange6** [comment]
I’m certain it was the original purpose of the package…but ok, i’m just newly confused by the strange name..the usage is not new:)

**Comment by davidlange6** [comment]
+1

**Pull request merged**
