### PR TITLE
Fix py files for ConfDB parsing (81X)

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
Fix py file for ConfDB parsing (81X)

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
type bug-fix

**Comment by mmusich** [comment]
+1

**Comment by davidlange6** [comment]
@Martin-Grunewald - do we not need this change in 90x?

**Comment by Martin-Grunewald** [comment]
Yes, both 81X and 90X, as we parse both.

**Comment by Martin-Grunewald** [comment]
please test

**Comment by mmusich** [comment]
+1

**Pull request closed without merging**
