### PR TITLE
Backoport of improvements to seed finding for L3 muon reconstruction at HLT 

### PR DESCRIPTION
**Pull request by JanFSchulte**
backport of #22321 
Needed because TSG developments for the 2018 data taking are done in 100X.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

@JanFSchulte please edit the PR title to match closer the title of #22321

**Comment by slava77** [comment]
assign hlt

code changes look OK for reco, but no substantive tracking of performance changes is done because all changes are in HLT

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/22322	cd4ed20
- the same changes as in the master branch https://github.com/cms-sw/cmssw/pull/22321	9c1eb6e
- jenkins tests pass and comparisons with the baseline show differences only in HLT quantities

**Comment by Martin-Grunewald** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
