### PR TITLE
Add ActivityRegistry signals for writeRun and writeLumi

### PR DESCRIPTION
**Pull request by wddgit**

### CODE REVIEW

**Comment by wddgit** [comment]
please test

**Comment by wddgit** [comment]
@fwyzard This adds new signals. You should be safe to just ignore these signals in FastTimerService, but it allows one to monitor the time for writing LuminosityBlocks and Runs which was not possible before.

**Comment by Dr15Jones** [comment]
+1

**Comment by fwyzard** [comment]
Hi @wddgit , thanks for the update.
But now I'm curious...
1. what is the difference between the global `writeRun` signal and the global `endRun` signal ? does it mean that `wirteRun` is a different phase, after the run is (globally) done ?
2. is there an equivalent phase for the event ?

**Comment by fabiocos** [comment]
+1

**Comment by Dr15Jones** [comment]
@fwyzard 
>   1. what is the difference between the global writeRun signal and the global endRun signal ? does it mean that wirteRun is a different phase, after the run is (globally) done ?

From the very beginning of cmsRun's implementation, writeRun and writeLumi were seperate phases. In fact, that separation is why the DQMOutputModule has worked all along. So the phases of an end transition (either Lumi or Run) is
    all stream end transitions run, then the global transition runs and we finish with the write transition
The comments in the original code say the write transition was added so that it only gets called if the begin transition completes successfully. I've preserved that behavior to avoid possibly breaking some unknown dependency.

>   2. is there an equivalent phase for the event ?

No there is not. This asymmetry is one thing I do not like and is why I'd like to move the DQM to using EDProducers since then the write could be moved into the global end transition.

**Comment by fwyzard** [comment]
Thanks for the explanation.

**Pull request merged**
