### PR TITLE
Revision of HLT for 80X/2016

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
Revision of HLT for 80X/2016.
Removal of 2015 frozen HLT menus.
Inclusion of updated development menus (GRun, HIon, PRef, PIon) aiming toward 2016.
Adjustment of autoHLT.py and autoCondHLT.py files.
RelVals beware: 50ns HLT (removed) is redirected to using the Fake menu.

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
Rebased to CMSSW_8_0_X_2015-12-16-2300 (pre3 lead to conflicts)

**Comment by Martin-Grunewald** [comment]
The issue discussed in https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2180.html
is still not resolved...

**Comment by Martin-Grunewald** [comment]
@hengne 
Please take not of removal of HLT menus (affecting relvals!).

**Comment by Martin-Grunewald** [comment]
@hengne 
The error in 50202.0 step 2 is due to relval using an internal TSG GT which append something
to the offical GT "run2_mc".  This should not happen. I am trying a workaround on the TSG side,
but this should really be fixed on the relval side

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
rebased to 800pre4

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Dr15Jones** [comment]
+1
The replacing of the 50ns workflow with 25ns seems fine.

**Comment by Martin-Grunewald** [comment]
unrelated errors! lets try running tests again!

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by Martin-Grunewald** [comment]
@civanch  @lveldere @ssekmen 
please sign this for FastSim - the fastsim part is pretty trivial.
Thanks!

**Comment by Martin-Grunewald** [comment]
@civanch @lveldere @ssekmen
please sign this for FastSim - the fastsim part is pretty trivial.
Thanks!

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
Hi @Martin-Grunewald 

Two issues
- We need an adjustment from @deguio to remove the famous tracking hlt dqm printouts given the changes to the 50ns menu.
- I'm not clear as to why we see RECO quantity changes. Are you? I will retest just to be sure

**Comment by davidlange6** [comment]
please test

**Comment by Martin-Grunewald** [comment]
@davidlange6 
Indeed, RECO quantities should be unaffected unless:
* the w'flows use TSG-internal GTs as defined in Configuration/HLT's autoCondHLT.py
* or depend directly or indirectly on the L1T or HLT menu (updated wrt baseline)
Maybe the baseline has changed, so the new test will show.

**Comment by slava77** [comment]
@cmsbuild please test
I suspect the differences in 50202 discussed in the ORP were from inconsistent set of minbias inputs in the reference compared to the PR test

**Comment by franzoni** [comment]
@slava77 , w/ @mmusich  we were intrigued by the fact that 25202 does NOT have changes, which would invalidate the  'minbias inputs' explanation. However, the comparator failed ( "Comparison died " ), thus what you say is still a possible explanation.

**Comment by slava77** [comment]
On 1/5/16 8:43 AM, Giovanni Franzoni wrote:
> @slava77 <https://github.com/slava77> , w/ @mmusich
> <https://github.com/mmusich> we were intrigued by the fact that 25202
> does NOT have changes, which would invalidate the 'minbias inputs'
> explanation. 

I meant the case when sometimes DAS serves a fraction of the file list
due to some intermittent problem.
The way to check is to look at the log files.
I've seen it happen before and it is usually resolved by rerunning.

**Comment by davidlange6** [comment]
@slava77 - so yes, a different pileup file is first opened in the baseline and in the PR test. Its not a das feature as it seems the list of PU files is the same in both configurations (unless I miss it). But then what causes the divergence (which can simply be a difference in random number usage).

**Comment by davidlange6** [comment]
@deguio - this PR needs your attention to adapt the DQM to the fake HLT menu in the 50(0)XXX workflows. Thanks!

**Comment by Martin-Grunewald** [comment]
@davidlange6 
Could you please integrate this PR?
Thanks!

**Comment by davidlange6** [comment]
Waiting on DQM - ping @deguio @vanbesien

**Comment by deguio** [comment]
will look into it. does it mean that all the 50ns workflows will be using a fake menu from now on? no 50ns menu maintained anymore?
cia,
F.

**Comment by fwyzard** [comment]
Hi Federico,

On 19 January 2016 at 12:22, Federico De Guio <notifications@github.com>
wrote:

> will look into it. does it mean that all the 50ns workflows will be using
> a fake menu from now on? no 50ns menu maintained anymore?


as we discussed and announced in the past months, none of the 2015 HLT
menus is maintained in CMSSW 8.0.x or later.

For the 25ns samples, we can use the "in development" HLT menu for 2016 -
at least until we migrate to the Stage 2 L1 trigger.

For the 50ns samples, that use a different L1 menu, there is no compatible
HLT menu available.

.Andrea

**Comment by deguio** [comment]
PR #12989 should address the issue.
ciao,
F.

**Comment by Martin-Grunewald** [comment]
Ping (now that #12989 is merged) to integrate this PR for 800pre5.

**Comment by davidlange6** [comment]
need an IB with 12989 to test against since the 2300 one was broken. looks like its almost there

**Comment by davidlange6** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by davidlange6** [comment]
The remaining new message is this 
@deguio 

MSG
%MSG-w Configuration:  TriggerResultsFilter:hltBtagTriggerSelection  21-Jan-2016 13:26:22 CET Run: 1 Event: 1
requested pattern "HLT_PFMET120_NoiseCleaned_BTagCSV0p72_*" does not match any HLT paths - known paths are:
	digitisation_step
	L1simulation_step
	digi2raw_step
	HLTriggerFirstPath
	HLT_Physics_v1
	HLT_Random_v1
	HLT_ZeroBias_v1
	HLTriggerFinalPath
%MSG
%MSG-w Configuration:  TriggerResultsFilter:hltBtagTriggerSelection  21-Jan-2016 13:26:22 CET Run: 1 Event: 1
requested pattern "HLT_CaloMHTNoPU90_PFMET90_PFMHT90_IDTight_*" does not match any HLT paths - known paths are:
	digitisation_step
	L1simulation_step
	digi2raw_step
	HLTriggerFirstPath
	HLT_Physics_v1
	HLT_Random_v1
	HLT_ZeroBias_v1
	HLTriggerFinalPath
%MSG
%MSG-w Configuration:  TriggerResultsFilter:hltBtagTriggerSelection  21-Jan-2016 13:26:22 CET Run: 1 Event: 1
requested pattern "HLT_QuadPFJet_VBF*" does not match any HLT paths - known paths are:
	digitisation_step
	L1simulation_step
	digi2raw_step
	HLTriggerFirstPath
	HLT_Physics_v1
	HLT_Random_v1
	HLT_ZeroBias_v1
	HLTriggerFinalPath
%MSG
%MSG-w Configuration:  TriggerResultsFilter:hltBtagTriggerSelection  21-Jan-2016 13:26:22 CET Run: 1 Event: 1
requested pattern "HLT_Ele32_eta2p1_*" does not match any HLT paths - known paths are:
	digitisation_step
	L1simulation_step
	digi2raw_step
	HLTriggerFirstPath
	HLT_Physics_v1
	HLT_Random_v1
	HLT_ZeroBias_v1
	HLTriggerFinalPath
%MSG

**Pull request merged**
