### PR TITLE
FWCore: Update StallMonitor service to use microsecond timing

### PR DESCRIPTION
**Pull request by gartung**

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
Doesn't line 263 also need to be updated?
https://github.com/cms-sw/cmssw/blob/02d4198c0b6615287fd88e9a8ff650aea994412e/FWCore/Services/plugins/StallMonitor.cc#L263

I think it should become
```C++
stallThreshold_{std::chrono::duration<double>(iPS.getUntrackedParameter<double>("stallThreshold"))}
```
which will automatically handle doing the proper time conversion.

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
