### PR TITLE
First version of a "unit-test" like regression test for conditions

### PR DESCRIPTION
**Pull request by apfeiffer1**
This PR contains the code for a "unit-test" like regression test for conditions. 
The core testing code is in the "test/testReadWritePayloads.cpp" file, while the main/controlling script is "test/condTestRegression.py". The controlling script creates a directory in /tmp/ (which will be re-used by later invocations on the same machine), there sets up development areas for the "reference releases", 
if needed, copies over (from the IB/devArea) and builds the core code, then invokes the core script to write some conditions into a database for each reference release and the actual IB/devArea. Once the (sqlite) DBs are written, the script loops over all releases (reference and actual IB/devArea) and reads all existing DBs. If any error is found, it exits with -1, otherwise with 0.

### CODE REVIEW

**Comment by apfeiffer1** [comment]
one more comment concerning the time the test takes:
if the directory in /tmp is not yet there, so all devAreas for the reference releases have to be set up, at present (with three reference releases), the overall time for the controlling script is about 5-10 min (on cmsdev07). Once all reference releases are set up (i.e. the second time the script is run on the same machine), the overall time goes down to ~15 sec or so, as it only writes and reads the local sqlite DB files.

**Comment by apfeiffer1** [comment]
cmsbot please test

**Comment by apfeiffer1** [comment]
please test

**Comment by apfeiffer1** [comment]
please test

**Comment by ggovi** [comment]
+1

**Pull request merged**
