### PR TITLE
Mini aod substructure pieces overhaul, rebase of #7659

### PR DESCRIPTION
**Pull request by rappoccio**
Rebasing #7659 and adding updates from @gpetruc to add constituents that are groomed away to rerun clusterings of other types. The original PR was mangled somehow so this is a clean rebase on 74x. 

(Note : this needs a git merge and many checked out packages to test correctly). 

Here is the original PR text, modified to add the new content : 

====== EVENT Content =======
The AK8 jet content is therefore :

Add all AK8 jets for pt > 50 GeV
If AK8 jet pt > 200:
Add top-tagging and soft drop tagger info.
Run b-tagging and JECs on subjets
So if the AK8 jet has pt between 50 and 200 GeV, the substructure algorithms are not run. If pt > 200 GeV, The subjets are written along with the "fat" jets in the BoostedJetMerger, and then are rekeyed accordingly with the JetSubstructurePacker. The slimming is done upstream on the pat::Jets made for the substructure algorithms, and so downstream this is no longer necessary to re-slim.

The jet content is (on 9000 events without pileup):

patJets_slimmedJets__PAT 1.00 1.00 1.00 4.8%
patJets_packedPatJetsAK8__PAT 1.00 0.58 0.58 2.8%
recoGenJets_slimmedGenJets__PAT 1.00 0.46 0.46 2.2%
recoGenJets_slimmedGenJetsAK8__PAT 1.00 0.45 0.45 2.2%
patJets_slimmedJetsCMSTopTagCHSPacked_SubJets_PAT 1.00 0.16 0.16 0.8%
patJets_slimmedJetsAK8PFCHSSoftDropPacked_SubJets_PAT 1.00 0.14 0.14 0.7%

So the additional collections (the subjets) are about 1.5% of the total miniAOD size.

====== CPU usage =====
The additional CPU usage here is negligible because the workflow is not running any algorithms, but instead taking the values directly from the RECO collections upstream and rekeying the information :

TimeReport 0.000074 0.000074 0.000074 caTopTagInfos
TimeReport 0.000041 0.000041 0.000041 caTopTagInfosPAT
TimeReport 0.000100 0.000100 0.000100 slimmedGenJets
TimeReport 0.000128 0.000128 0.000128 slimmedGenJetsAK8
TimeReport 0.000131 0.000131 0.000131 slimmedJets
TimeReport 0.000000 0.000000 0.000000 slimmedJetsAK8
TimeReport 0.000041 0.000041 0.000041 slimmedJetsAK8PFCHSSoftDropPacked
TimeReport 0.000051 0.000051 0.000051 slimmedJetsAK8PFCHSSoftDropSubjets
TimeReport 0.000048 0.000048 0.000048 slimmedJetsCMSTopTagCHSPacked
TimeReport 0.000056 0.000056 0.000056 slimmedJetsCMSTopTagCHSSubjets
TimeReport 0.000095 0.000095 0.000095 packedPatJetsAK8

==== Testing ====
Tests are checking out (thanks to @ianna for providing the correct recipe so quickly, I've merged in that PR, and apologies to @ferencek since I had to revert out the genJetsNoNu for the b-tagging sequence, to be discussed at an upcoming JMAR meeting).

==== For posterity, here is the original PR message : ====

With @arizzi and @ferencek : we've added substructure into miniAOD in a slightly more natural way to allow for multiple interpretations of the jet. This will now be accessed through the "subjet" methods. They can take string or integer access similar to the JECs. I have also adjusted pt thresholds so that they are sensible given common user preferences. This makes the total of the AK8 jets (including two subjet collections) 3.8% of the total miniAOD size.

The nice additions are :

Subjets from soft drop and the CMS top tagger are stored as lists of pat::Jets.
Jet corrections are applied to subjets.
Subjet b-tagging is being run.

### CODE REVIEW

**Comment by rappoccio** [comment]
Are we okay here? I'm worried that if we wait much longer it won't merge again.

**Comment by arizzi** [comment]
I guess so ad there were no objections during or after your talk.

Taejeong can you sign or comment?
Il 14/mar/2015 20:29 "rappoccio" <notifications@github.com> ha scritto:

**Comment by monttj** [comment]
+1
thank you for the update.

**Comment by davidlange6** [comment]
+1

**Comment by rappoccio** [comment]
Thanks all!

**Pull request merged**
