### PR TITLE
[DD4hep] Disable DT Geometry Builder unit test that can't work with new DD4hep

### PR DESCRIPTION
**Pull request by cvuosalo**
The new version of DD4hep uses the Geant4 units convention. The `validateDTGeometry_cfg.py` unit test in the `Geometry/DTGeometryBuilder` package compares a reference geometry that may have the ROOT units convention with the current geometry that has the Geant4 units convention. This comparison somehow triggers a ROOT exception complaining about changing the units convention. Discussion with the DD4hep developers indicates there is no easy fix. Rather than block the new version of DD4hep, it was decided to disable this unit test. In the future, we may figure out a way to fix it, but it doesn't seem to be essential.

#### PR validation:

With the changes in this PR, the `Geometry/DTGeometryBuilder` unit tests were run successfully in a special build with the new version of DD4hep.

No backport is needed.

### CODE REVIEW

**Comment by cvuosalo** [comment]
type bug-fix

**Comment by mrodozov** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
