### PR TITLE
CTPPS: miniAOD (resubmitted)

### PR DESCRIPTION
**Pull request by jan-kaspar**
This PR is a follow up of #17162 after it has been reverted (#17265). It contains the same commits, plus an additional one inserting `ctppsLocalTrackLiteProducer` in the `miniAOD_customizeData` section in `PhysicsTools/PatAlgos/python/slimming/miniAOD_tools.py` - as proposed in #17282.

`runTheMatrix -l limited` gives
```
16 16 15 13 8 1 1 1 tests passed, 0 0 0 0 0 0 0 0 failed
```

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

this PR will be stuck until #17288 is resolved

**Comment by davidlange6** [comment]
Right - very likely the title of #17288 is unfortunate. It should take two poorly formulated Xerces usages to interfere. Very likely ctpps is the second one. @ianna was looking at it, but I think she is away for a week or so

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/17265	1041d9a
- the same change as in https://github.com/cms-sw/cmssw/pull/17424 bdf8ef9 with an extra load of ctppsLocalTrackLiteProducer_cfi in miniAOD_tools (missing element found while integrating 80X)
- jenkins tests pass and comparisons with baseline show no differences

I'll put this on hold

**Comment by slava77** [comment]
hold

until https://github.com/cms-sw/cmssw/issues/17288
is resolved

**Comment by ianna** [comment]
CTPPS needs to parse xml, but does it in unsafe manner. The code should use DDLParser
http://cmslxr.fnal.gov/source/GeometryReaders/XMLIdealGeometryESSource/src/XMLIdealMagneticFieldGeometryESProducer.cc#0069
rather then modifying the DDCompactView

**Comment by jan-kaspar** [comment]
@ianna First let me understand as I don't think we ever modify the DDCompactView. There are two use cases. First, simply get DDCompactView from EventSetup, e.g.
  https://github.com/cms-sw/cmssw/blob/CMSSW_9_0_X/Geometry/VeryForwardGeometryBuilder/plugins/TotemRPGeometryESModule.cc#L460
Is this unsafe? The second use case is to create a new DDCompactView object and save it to EventSetup:
https://github.com/cms-sw/cmssw/blob/CMSSW_9_0_X/Geometry/VeryForwardGeometryBuilder/plugins/TotemRPGeometryESModule.cc#L423
Is this unsafe?

Then, looking at the link you sent, the code seems to be parsing DDL files. CTPPS code never parses DDL files directly - the standard `XMLIdealGeometryESSource` is used for it:
https://github.com/cms-sw/cmssw/blob/CMSSW_9_0_X/Geometry/VeryForwardGeometry/python/geometryRP_cfi.py#L84
Therefore I can't quite see how your suggestion applies to us. Could you please explain it?

**Comment by ianna** [comment]
@jan-kaspar - yes, you retrieve a record and then modify it here:
https://github.com/cms-sw/cmssw/blob/CMSSW_9_0_X/Geometry/VeryForwardGeometryBuilder/plugins/TotemRPGeometryESModule.cc#L464
by constructing DetGeomDescr:
http://cmslxr.fnal.gov/source/Geometry/VeryForwardGeometryBuilder/src/DetGeomDesc.cc#0022

It has to be done within a lock, e.g. before DDLParser is destructed.

**Comment by jan-kaspar** [comment]
I'm sorry I still fail to understand. @ianna, are you at CERN, could we meet in person?

Technical issue: yes, we modify the ES record, but I still think we don't modify the DDCompactView as you wrote. The only use of DDCompactView in DDDTotemRPContruction is to build DDFilteredView
  https://github.com/cms-sw/cmssw/blob/CMSSW_9_0_X/Geometry/VeryForwardGeometryBuilder/src/DDDTotemRPConstruction.cc#L31
which I presume does not modify the input DDCompactView.

Conceptual issue: our code is NOT parsing DDL files, it only depends on DDCompactView - which may come from a source completely independent of DDL files. Thus, shouldn't the problem be rather addressed in the module parsing DDL files (XMLIdealGeometryESSource) or the mechanism how DDCompactView is supplied to our code?

**Comment by dmitrijus** [comment]
+1

**Comment by dan131riley** [comment]
@davidlange6 RPCTrigger closing Xerces could interfere with proper usage, I don't think it takes two misuses.  It's probably just luck (pick the sign of your choice) that we haven't had it collide before.

**Comment by monttj** [comment]
+1

**Comment by slava77** [comment]
@davidlange6 
#17450 meant to resolve issues with CTPPS use of xerces
Can this PR be merged or do you expect some other changes?

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by jan-kaspar** [comment]
In  fc9b28c I've fixed merge conflicts appearing meanwhile.

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/17424	fc9b28c
- (post-merge) confirmation that the conflict resolution/update looks good: DataFormats/CTPPSReco/src/classes.h, DataFormats/CTPPSReco/src/classes_def.xml, and RecoCTPPS/Configuration/python/RecoCTPPS_EventContent_cff.py were updated appropriately since introduction of diamond rechits

**Comment by davidlange6** [comment]
Hi @jan-kaspar @slava77 - looks like this is causing lots of problems on old data.

https://cms-sw.github.io/relvalLogDetail.html#slc6_amd64_gcc620;CMSSW_9_0_X_2017-02-26-0000

will revert for now. Please resubmit when fixed.

**Comment by slava77** [comment]
On 2/26/17 4:25 AM, David Lange wrote:
> Hi @jan-kaspar <https://github.com/jan-kaspar> @slava77
> <https://github.com/slava77> - looks like this is causing lots of
> problems on old data.
> 
> https://cms-sw.github.io/relvalLogDetail.html#slc6_amd64_gcc620;CMSSW_9_0_X_2017-02-26-0000
> 
> will revert for now. Please resubmit when fixed.

This might be a good reason to update the list of short matrix workflows
to have at least one with PAT on data.

https://github.com/cms-sw/cmssw/pull/17633

**Comment by slava77** [comment]
@jan-kaspar 
looks like we need to have the track lite producer modified.
I'd like to suggest to add a flag "doNothing" and if it's set, skip all activity in the constructor and in the ::produce method.
The "doNothing" flag can be set to false for ctpps_2016 era

**Comment by slava77** [comment]
The "doNothing" flag can be set to true for ctpps_2016 era

**Comment by davidlange6** [comment]
I think you mean PAT data + no CTPPS in the run..Right.

I guess that an alternative is that the CTPPS modules in the chain makes an empty collection instead of no collection when it finds that CTPPS is not in the run. (it looks like the unpackers and the RECO do this). Also things need to work on top of existing AOD(SIM), which is something I think we don't test very much (but probably should)

**Comment by slava77** [comment]
unpackers and reco are still enabled by  ctpps_2016 era

**Comment by davidlange6** [comment]
Ok, so not in <=2015. Then the miniAOD setup needs to be consistent as you suggested..

**Comment by jan-kaspar** [comment]
> I'd like to suggest to add a flag "doNothing" and if it's set, skip all activity in the constructor and in the ::produce method.

OK

> The "doNothing" flag can be set to true for ctpps_2016 era

Is the "true" a typo? We actually want to produce lite tracks for 2016 data.

**Comment by slava77** [comment]
On 2/26/17 2:50 PM, jan-kaspar wrote:
>     I'd like to suggest to add a flag "doNothing" and if it's set, skip
>     all activity in the constructor and in the ::produce method.
> 
> OK
> 
>     The "doNothing" flag can be set to true for ctpps_2016 era
> 
> Is the "true" a typo? We actually want to produce lite tracks for 2016 data.

sorry, indeed it's a typo; I wrote it correctly the first time around.

**Comment by jan-kaspar** [comment]
The update has been resubmitted as #17650 .

**Pull request merged**
