### PR TITLE
Tau customization for Phase2 (91X)

### PR DESCRIPTION
**Pull request by mbluj**
Tau customization for Phase2 studies: backport of #19788 to CMSSW_9_1_X release series. Please check original PR for details.

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
assign upgrade

**Comment by kpedro88** [comment]
backport of #19788

**Comment by kpedro88** [comment]
+1

**Comment by perrotta** [comment]
+1
Same as #19788 in the master
Changes show up only in reco tau quantities for Phase2 workflows, and they are what expected by Tau POG

**Comment by kpedro88** [comment]
hold
(currently this isn't desired to go in the next bugfix patch release; will update if that changes)

**Comment by slava77** [comment]
@kpedro88 
@mbluj 
should we close this PR?

**Comment by mbluj** [comment]
The sibling PR is already integrated into the 93X release series, so as for me the decision depends on plans on new MC production for phase-2 studies, i.e. if 91X will be used for it. If not (what I guess will be the case), the PR can be closed, but it will be good to have a confirmation.

**Comment by kpedro88** [comment]
91X will no longer be used, so we can close this PR.

**Comment by slava77** [comment]
-1

based on https://github.com/cms-sw/cmssw/pull/19790#issuecomment-330245048

**Comment by kpedro88** [comment]
@mbluj please close this

**Comment by mbluj** [comment]
OK, closing

**Pull request closed without merging**
