### PR TITLE
fix dump of nano + add modifier for 122 mini

### PR DESCRIPTION
**Pull request by mariadalfonso**
1) fix issue https://github.com/cms-sw/cmssw/issues/386862
2) add modifier to run nano from 122 mini

### CODE REVIEW

**Comment by mariadalfonso** [comment]
please test

**Comment by mariadalfonso** [comment]
please test

**Comment by mariadalfonso** [comment]
please test

**Comment by srimanob** [comment]
Should this PR be closed as the issue is fixed in https://github.com/cms-sw/cmssw/pull/39127 ?
Do we still need modifier for 12_2 part?

**Pull request closed without merging**
