### PR TITLE
Particle level backports for 80X

### PR DESCRIPTION
**Pull request by mseidel42**
Fixes to run with Herwig and non-standard samples without beam information

### CODE REVIEW

**Comment by intrepid42** [comment]
Hi Alberto, the original PRs are https://github.com/cms-sw/cmssw/pull/21467 and https://github.com/cms-sw/cmssw/pull/22441

I forgot to include one commit, PR is updated.

**Comment by alberto-sanchez** [comment]
please test

**Comment by alberto-sanchez** [comment]
+1

**Comment by fabiocos** [comment]
@alberto-sanchez which is the target of this backport?

**Comment by alberto-sanchez** [comment]
This is basically for 2016 data-like analysis.

**Comment by intrepid42** [comment]
Hi, yes, people are using this for 2016 analysis and encountered errors with the ttbar Powheg+Herwig++ sample (which has a different event record compared to Pythia), so we decided to backport all the fixes from master.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
