### PR TITLE
Minor Framework speed improvements

### PR DESCRIPTION
**Pull request by Dr15Jones**
While testing the limits of the framework's event throughput using a 'hyper fast' configuration, a few performance bottlenecks were found. With these changes, and running cmsRun on moderate hardware, one can get 33,000 event/sec with one thread and get a max throughput of 180,000 events/sec using 9 threads.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
@fwyzard here are some further improvements to drive the hyper fast configurations.

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
Please test

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by Dr15Jones** [comment]
These most recent changes allow for a throughput of 203,000 events/sec for 9 threads.

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
@smuzaffar is there a time limit on how long the tests can run? I can not see why the tests for this fail in a step4 job running single threaded since the harvesting step never calls the code I changed!

**Comment by smuzaffar** [comment]
@Dr15Jones , although we do run with timeout 10800 for full runTheMatrix but I see that this was OOM-KILL. For PR testing we are running 8 workflows in parallel on a 8 core machine with 15GB memory. May be we should run cpu-1 workflows in parallel for PR testing.

**Comment by davidlange6** [comment]
please test
(or is there some reason to think this PR increases RSS by some significant amount?

**Comment by Dr15Jones** [comment]
@davidlange6 I can't think of any reason why this pull request would increase RSS in any noticable way.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
