### PR TITLE
Update MuTauSkim_cff with new Tau POG Isolation from Ram

### PR DESCRIPTION
**Pull request by kfjack**
Update the MuTauSkim_cff.py in the skim matrix with the new config from Ram, with the new Tau POG isolation.

### CODE REVIEW

**Comment by franzoni** [comment]
please test

**Comment by franzoni** [comment]
please test

**Comment by franzoni** [comment]
please test

**Comment by franzoni** [comment]
+1

**Comment by davidlange6** [comment]
cmsbuild, please test

**Comment by davidlange6** [comment]
cmsbuild, please test

**Comment by davidlange6** [comment]
cmsbuild, please test

**Comment by davidlange6** [comment]
+1

**Pull request merged**
