### PR TITLE
Method 2 Updates 

### PR DESCRIPTION
**Pull request by sabrandt**
1. Totally removed the single-pulse fit and go directly to three-pulse fit to save time, since almost all cases end up using three-pulse fit. 
2. Pick pulse with time closest to 0.
3. Minor updates to configuration file.

### CODE REVIEW

**Comment by fratnikov** [comment]
merge

**Comment by fratnikov** [comment]
This PR is tested and may be merged, however it refuses to because of merge conflict. Could the conflict be resolved?

**Comment by sabrandt** [comment]
This was OK last night. I will try to resolve it now.

**Comment by sabrandt** [comment]
Something strange happened when I tried to fix the merge issue. It can be automatically merged, but I think I accidentally pushed several files that aren't mine.

**Comment by davidlange6** [comment]
@sabrandt - did this issue get resolved? (if not, I would suggest just starting a new branch and pull request as sometimes a PR gets corrupted for one reason or another)

**Comment by sabrandt** [comment]
@davidlange6 I will try starting over with the new branch & pull request

**Comment by mark-grimes** [comment]
@sabrandt, make sure you start from the current head because there are changes that have gone into that area in the last few hours that won't be in the Integration Build.  I.e.

    git checkout CMSSW_6_2_X_SLHC
    git pull
    git checkout -b my_new_branch

I think part of the problem is a clash with some of your commits being included in #7146 which has already been merged.  So once you have the head check what changes are already there.

**Comment by mark-grimes** [comment]
In fact, looking at the file differences in #7146 I think your changes are already in, but double check.

**Comment by sabrandt** [comment]
Hi I guess they are already included in Hengne's pull request & this pull request is redundant.

**Pull request closed without merging**
