### PR TITLE
EGM smearer for 81X

### PR DESCRIPTION
**Pull request by fcouderc**
same as PR 14447

https://github.com/cms-sw/cmssw/pull/14447

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by fcouderc** [comment]
So what is happening with this PR?

**Comment by fcouderc** [comment]
Hi guys,

this request has been there for ages now… we really need that, and we also would like it integrated in 80X, I ll submit a PR for that but once this one gets approved.
Is there anything additional needed from me.

Thanks

Fabrice



Le 25 mai 2016 à 20:35, cmsbuild <notifications@github.com<mailto:notifications@github.com>> a écrit :


Comparison is ready
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-14620/13199/summary.html

**Comment by slava77** [comment]
@fcouderc 
this PR can not be integrated now due to merge conflicts

**Comment by davidlange6** [comment]
yes, apologies - this PR is at least partly already integrated via the last heppy PR. I had intended to check if it was complete or not, but have not found the time.

https://github.com/cms-sw/cmssw/pull/14236

**Comment by fcouderc** [comment]
so what shall I do now?

Le 22 juin 2016 à 14:28, David Lange <notifications@github.com<mailto:notifications@github.com>> a écrit :

yes, apologies - this PR is at least partly already integrated via the last heppy PR. I had intended to check if it was complete or not, but have not found the time.

https://github.com/cms-sw/cmssw/pull/14236

**Comment by davidlange6** [comment]
if you have a moment to see if your PR is already fully captured in CMSSW_8_1_0_pre7 (via the PR I reference), that would be very helpful. Maybe the issue is already closed.

**Pull request closed without merging**
