### PR TITLE
adding Prod2017 wfs

### PR DESCRIPTION
**Pull request by prebello**
This PR adds Prod2017 wfs 1301.17,1302.17,1303.17 in the standard matrix.

FYI @fabozzi

### CODE REVIEW

**Comment by prebello** [comment]
please test workflow 1301.17,1302.17,1303.17

**Comment by fabozzi** [comment]
Before doing a backport to 10_0_X, let's first deploy a PR for master branch

**Comment by fabozzi** [comment]
Also, here you are overlapping with backport in #22383 
Maybe it is also good to wait that backport to go in first.
In the meanwhile, you can add this to master branch.

**Comment by prebello** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Comment by prebello** [comment]
@fabiocos  please consider to merge with the update (removing DQM step) as backport from master (acc #22393)

**Comment by prebello** [comment]
please test

**Comment by fabozzi** [comment]
backport of #22393

**Comment by fabozzi** [comment]
@prebello 

> Also, here you are overlapping with #22383 

Please, clarify if this PR supercedes #22383

**Comment by prebello** [comment]
@fabiocos it does not supercede. 
you can notice that I have (tried!!) used different branch names  from-CMSSW_10_0_X_2018-02-27-2300_prod2017 and  from-CMSSW_10_0_X_2018-02-27-2300 for the commits, betting that it would separate them but I was wrong. 
22388, is dedicated only for adding Prod 2017.  Is it possible to merge only the commit related to it, since GENSIM is merged already in 22383, or do you prefer to close 22388 and I start from scratch in a new IB?

**Comment by kpedro88** [comment]
what is the status of this PR?

**Comment by prebello** [comment]
waiting for validation in the development release cycle CMSSW_10_1_X ...
could it be already merged in 10_0_4 though ?

**Comment by fabiocos** [comment]
@prebello if you want it in 10_0_4 it needs to be merged in the branch. If you want to wait for a validation in 10_1_X (pre3 relvals ?) it should wait, and it can enter into a patch. But why is it relevant to have this back-port?

**Comment by prebello** [comment]
It is not relevant but to add 2017 Production wfs as we have been doing for 2016 ones in previous releases.   It can wait for pre3 validation though. Thank you.

Sent from my iPhone

On 10 Mar 2018, at 14:10, Fabio Cossutti <notifications@github.com<mailto:notifications@github.com>> wrote:


@prebello<https://github.com/prebello> if you want it in 10_0_4 it needs to be merged in the branch. If you want to wait for a validation in 10_1_X (pre3 relvals ?) it should wait, and it can enter into a patch. But why is it relevant to have this back-port?

**Comment by kpedro88** [comment]
+1

**Comment by prebello** [comment]
+1

**Comment by fabiocos** [comment]
@prebello after the move to 10_1_X this PR can be closed

**Pull request closed without merging**
