### PR TITLE
Fixed generator/Geant4 interface for PPS 

### PR DESCRIPTION
**Pull request by civanch**
#### PR description:
Generator/Geant4 interface is fixed:
   1) for non-central particles (cosmic and protons after Hector transport) filter is not applied. As a results of Hector
       transport scattered protons moved to from IR to PPS station and Geant4 get these protons in front of PPS or ZDC. Actual       implementation of Hector transport is outside this PR, here only interface is provided
   2) n, nbar, gamma with direction along beam pipe eta cut is not applied in order to allow them fly forward to ZDC
   3) code format and printout format
These modifications are needed for PPS simulation. Due to change in very forward direction simulation histories are affected, so no regression is expected

#### PR validation:
private

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
@mundim , please, try this out.

**Comment by civanch** [comment]
+1

differences are expected

**Comment by qliphy** [comment]
+1

**Comment by silviodonato** [comment]
> +1
> 
> differences are expected

@civanch could you spend some words about the expected differences (it might be useful also for the future validation of 11_2_0_pre6 @cms-sw/pdmv-l2 )? Are they expected only at large eta? I see many plots changed. Thank you

**Comment by civanch** [comment]
@silviodonato , I have extended the description. plots changed due to change of histories.

**Comment by silviodonato** [comment]
Thanks @civanch. If I understand correctly, we expect changes only in simulated objects because the simulation is extended up to PPS/ZDC and the history changes.  
So why do we see changes even in central reconstructed objects (eg. eta distribution or reco tracks [1]) ?
I suspect I'm missing some points...

image

[1] https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_11_2_X_2020-08-27-1100+83a51e/38518/validateJR/all_OldVSNew_Higgs200ChargedTauswf9p0/all_OldVSNew_Higgs200ChargedTauswf9p0c_recoTracks_generalTracks__RECO_obj_eta.png

**Comment by civanch** [comment]
@silviodonato , unfortunately when we spend few or less random numbers in some event, then the history in the next event may be completely different. I see statistical agreement in this plot but no regression.

**Pull request merged**
