### PR TITLE
Phase2-hgx319D Modify the muon tomography script which now generates the hit file and uses it to create the histograms

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Modify the muon tomography script which now generates the hit file and uses it to create the histograms

#### PR validation:

Tested the script after adding the 2 csv files temporarily in Validation/HGCalValidataion/data and waiting for the PR for cms_data to be integrated

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by emanueleusai** [comment]
type hgcal

**Comment by emanueleusai** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
