### PR TITLE
HCAL DQM Updates in Preparation for 2016 Collisions

### PR DESCRIPTION
**Pull request by vkhristenko**
This is a copy of https://github.com/cms-sw/cmssw/pull/13561

This is the 2nd iteration of updates for HCAL DQM. We need that by the time collisions arrive...

Things that are majorly updated:
1) previously, I used std::vector<> to hold the MonitorElements, however now it is boost::unordered_map It's integrated with the use of DataFormats/HcalDetId classes. 
2) DQM/HcalCommon adds some additional classes for Electronics <-> Detector Conversions - all of that is again heavily based on DataFormats/HcalDetId classes
3) DQM Harvesting is added + reportSummaryMap to show up for the Summary Workspace in DQM GUI
4) 2 new Monitioring Tasks are added: TPComparisonTask and DigiComparisonTask. These 2 modules are for VME vs uTCA (HBHE) comparison. because of doing reco twice makes workflow very slow... 
These guys are suppposed to be used in Online DQM only - not in Offline Workflows. That will require a special config for them and will be discussed with Central DQM people...

A few things that have partially been accommodated from David Lange's comments:
1) Constants - FED Constants have been replaced by the central values (from FEDNumbering...) reassigned...
Other constants will have to be migrated later...
2) const refs, in Utilities.h I fixed places where there were no const refs - I've tried to put them everywhere where it was neccessary - I realize that it's a performance problem
3) Templating is not done at the moment - but that should be done for 810

I realize that this PR is quite big once again... but I think it should be the last one of such size....
I've tested 3 runTheMatrix tests - all successful.

VK

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by vkhristenko** [comment]
I updated the branch with:

1) calibration sequence harvestor + reportsummarymap generation
2) some cleaning to have things more compatible with overall HCAL api.

VK

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
please decrease memory as much as possible by enabling only the needed monitorElements.
thanks,
F.

**Comment by deguio** [comment]
please test

**Comment by smuzaffar** [comment]
@vkhristenko , new package DQM/HcalHarvesting just holds couple of source file and python configuration files. Can these be move to some existing DQM/Hcal* package e.g. DQM/HcalTasks?

**Comment by vkhristenko** [comment]
@smuzaffar 
I can move it no problem if that is absolutely neccessary.
It's just that from DQM point of view (functionality wise...) Tasks and Harvestors are 2 different things + inheritance is slightly different... but I don't care personally... I can just document that....

VK

**Comment by vkhristenko** [comment]
Old folders like HcalMonitor *** will be git rmed at some point later.... 

VK

**Comment by smuzaffar** [comment]
basically having a package with few files (specially with only plugin(s) and no shared library) is overkilled.

**Comment by vkhristenko** [comment]
I understand... I will move that then to HcalTasks

VK

**Comment by vkhristenko** [comment]
@smuzaffar , done as requested...

VK

**Comment by deguio** [comment]
-1
superseded by #13805

**Pull request closed without merging**
