### PR TITLE
add DQM monitoring for HLT_L1SingleMu18

### PR DESCRIPTION
**Pull request by sarafiorendi**

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
@sarafiorendi : please provide also the 81X version of this (very simple) PR

**Comment by battibass** [comment]
@perrotta : we asked Sara to avoid doing that because we have a change (monitoring of paths by filter: https://github.com/cms-sw/cmssw/pull/14720) that would make the monitoring of L1_SingleMu18 implicit for the HLT paths that use it.

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
@dmitrijus @sarafiorendi - to close the loop - what is the 81x version?

**Comment by fwyzard** [comment]
@battibass pointed out that this is not needed in 8.1.x, because it is superseded by #14720 .

**Comment by davidlange6** [comment]
+1

**Pull request merged**
