### PR TITLE
updated relval gridpacks for gcc630 

### PR DESCRIPTION
**Pull request by alberto-sanchez**
backport #20515

### CODE REVIEW

**Comment by alberto-sanchez** [comment]
please test workflow 534.0 with #4385

**Comment by alberto-sanchez** [comment]
please abort

**Comment by alberto-sanchez** [comment]
please test workflow 534.0 with cms-sw/cmsdist#4385

**Comment by alberto-sanchez** [comment]
+1

**Comment by GurpreetSinghChahal** [comment]
Hi @fabiocos and @smuzaffar,  is it possible to merge this PR and eventually get a new release/patch release in 9.3.x soon? We need the new cmssw release to perform the studies in sherpa 2.2.5 + opensloops beta [PR: 4385](https://github.com/cms-sw/cmsdist/pull/4385) for the [Sherpa Day](https://indico.cern.ch/event/746831/) on the 25/10. Thanks!

**Comment by fabiocos** [comment]
+1

**Pull request merged**
