### PR TITLE
[12_4_X] Fix the parameter set of the AlcaPCCIntegrator module

### PR DESCRIPTION
**Pull request by radla118**
#### PR description:
Backport of the PR https://github.com/cms-sw/cmssw/pull/38077

#### PR validation:
Validated by running runTheMatrix.py -l 1020.0 --ibeos

#### if this PR is a backport please specify the original PR and why you need to backport that PR:
The modified AlcaPCCIntegrator module is intended to be used in the next data-taking period.

### CODE REVIEW

**Comment by tvami** [comment]
test parameters:
  - workflows = 1020.0

**Comment by tvami** [comment]
type bugfix

**Comment by tvami** [comment]
type lumi

**Comment by tvami** [comment]
backport of https://github.com/cms-sw/cmssw/pull/38077

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
+alca
 * tests pass, master PR is tested in IBs already

**Comment by qliphy** [comment]
+1

**Pull request merged**
