### PR TITLE
Merge ShallowGainCalibration logic in SiStripGainsPCLWorker and a minor bugfix

### PR DESCRIPTION
**Pull request by pieterdavid**
#### PR description:

To minimise the risk of diverging during data-taking, the SiStrip gains PCL reused the flat tree maker (ShallowGainCalibration), and read the branches it produced. We are reorganising the calibration tree code for run 3 (moving to the NanoAOD framework / ALCANANO, see [this presentation](https://indico.cern.ch/event/992962/contributions/4293256/attachments/2218359/3756083/NANOAOD_like_Strip_calibration_trees.pdf), which will replace ShallowGainCalibration), so now it seems cleaner to remove the intermediate step (that brings the track and cluster selection logic together in the PCL worker, where most of it already was).
In the process, I found a bug in the [old code](https://github.com/cms-sw/cmssw/blob/master/CalibTracker/SiStripCommon/plugins/ShallowGainCalibration.cc#L138-L173) that checks if a cluster crosses or touches an APV boundary (group of 128 strips), and fixed that (the cut removed a bit too many clusters, so the only effect is a small increase, of about 1%, in the number of clusters considered - all distributions should be compatible).

#### PR validation:

Compared workflow 1001.2, which contains the SiStrip gain calibration PCL. No changes before the last commit; with that change included a small increase in cluster statistics.

CC: @ataliercio @mdelcourt @robervalwalsh @mmusich

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by pieterdavid** [comment]
@mmusich noticed a difference in the histograms that was not expected (cluster count in AlCaReco/SiStripGainsAAG/EventStats for 1001.0), but after some discussion we find it more logical to fill the actual number of clusters that are used for the calibration than the total number of clusters on all tracks - so with the last commit the difference in that bin is larger but expected (this histogram is not used downstream, the harvester takes everything from the 2D Charge_Vs_Index histogram); sorry for the extra noise.

**Comment by mmusich** [comment]
test parameters:
   * workflow = 1001.2

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by yuanchao** [comment]
+1
* ShallowGainCalibration replaced; fixed a bug on APV boundary
* workflow 1001.0 statistics changed for the fix
* build warnings are irrelevant; all tests passed

**Comment by silviodonato** [comment]
+1

**Comment by silviodonato** [comment]
cc @cms-sw/trk-dpg

**Comment by silviodonato** [comment]
cc @cms-sw/trk-dpg-l2

**Pull request merged**
