### PR TITLE
Add HcalCalIsoTrk AlCaReco in the correct RelVal steps

### PR DESCRIPTION
**Pull request by diguida**
`HcalCalIsoTrk` AlCaReco requires L1T information (`L1SingleJet68` seed) to select events. This product is not available in RECO, but only in RAW data tier.

With this PR, the AlCaReco is run in the reco sequence, so that the collection is available in the input file.

As a side note, the RelVal were not failing because the HLT menu in use either did not contain `HLT_IsoTrk*` paths, or no events passed that selection. As a consequence, the trigger bit filter was exiting without any events.

### CODE REVIEW

**Comment by diguida** [comment]
@mmusich @bsunanda this is something you want to watch as well.

**Comment by mmusich** [comment]
@diguida thanks! I think we should take care also of the other HCAL AlCa producer never tested in RelVals, after changing the 'eventSetupPathKey'.

**Comment by diguida** [comment]
@mmusich you are reading into my mind.
Please expect news about the following producers:
`HcalCalNoise`, `HcalCalGammaJet`, `HcalCalDijets`.

**Comment by diguida** [comment]
please test

**Comment by diguida** [comment]
@cmsbuild are you still there?

**Comment by smuzaffar** [comment]
please test

**Comment by franzoni** [comment]
same eos-related problem as other PR

**Comment by franzoni** [comment]
please test

**Comment by mmusich** [comment]
+1

**Pull request merged**
