### PR TITLE
Fix range in recHitsEndcapsPosXY [`12_3_X`]

### PR DESCRIPTION
**Pull request by missirol**
backport of #38326

#### PR description:

See description of original PR (#38326) by @silviodonato.

FYI: @elfontan @swagata87 @mzarucki

#### PR validation:

None.

#### If this PR is a backport, please specify the original PR and why you need to backport that PR:

#38326

DQM bugfix needed by HLT.

### CODE REVIEW

**Comment by missirol** [comment]
type bugfix

**Comment by missirol** [comment]
enable gpu

**Comment by missirol** [comment]
please test

**Comment by emanueleusai** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
