### PR TITLE
Utilities/StaticAnalyzers: update

### PR DESCRIPTION
**Pull request by gartung**
ConstCastAway, ConstCast and MutableMember checks moved to new catagory ConstThreadSafety and the filter isDataClass removed. This will allow the global producer check to work when any of these problem appear in the class.

### CODE REVIEW

**Comment by gartung** [comment]
@Dr15Jones

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1
We will have to watch to see how this affects the report

**Comment by Dr15Jones** [comment]
-1
there is an extra log

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
please test

**Comment by davidlange6** [comment]
hi @Dr15Jones - what is the status of this PR?

**Comment by Dr15Jones** [comment]
@gartung did you finish all the changes you wanted to do?

**Comment by gartung** [comment]
yes

**Comment by Dr15Jones** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
