### PR TITLE
MC GTs updated with JP BTag, minor HCAL updates,SiPixelQuality,CSC APEs and Phase2 updates for Geometry

### PR DESCRIPTION
**Pull request by arunhep**
# Summary of changes in Global Tags

## Upgrade

   * **PhaseII realistic scenario** : [91X_upgrade2023_realistic_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/91X_upgrade2023_realistic_v2) as [91X_upgrade2023_realistic_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/91X_upgrade2023_realistic_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/91X_upgrade2023_realistic_v2/91X_upgrade2023_realistic_v1):
      * Jet Probability Btagger update
      * ECAL alpha values updated : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2913.html
      * Geometry updates : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2895.html

   * **PhaseI 2017 cosmics peak scenario** : [91X_upgrade2017cosmics_realistic_peak_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/91X_upgrade2017cosmics_realistic_peak_v4) as [91X_upgrade2017cosmics_realistic_peak_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/91X_upgrade2017cosmics_realistic_peak_v3) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/91X_upgrade2017cosmics_realistic_peak_v4/91X_upgrade2017cosmics_realistic_peak_v3):
      * Jet Probability Btagger corresponds to Phase1 geometry
      * ZDC reco geometry update : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2841/1.html
      * HCAL updates : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2912.html
      * CSC alignment and APE update : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2919.html
      * SiPixel Quality updated : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2922.html

   * **PhaseI 2017 cosmics scenario** : [91X_upgrade2017cosmics_realistic_deco_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/91X_upgrade2017cosmics_realistic_deco_v4) as [91X_upgrade2017cosmics_realistic_deco_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/91X_upgrade2017cosmics_realistic_deco_v3) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/91X_upgrade2017cosmics_realistic_deco_v4/91X_upgrade2017cosmics_realistic_deco_v3):
      * Jet Probability Btagger corresponds to Phase1 geometry
      * ZDC reco geometry update : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2841/1.html
      * HCAL updates : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2912.html
      * CSC alignment and APE update : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2919.html
      * SiPixel Quality updated : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2922.html

   * **PhaseI 2017 design scenario** : [91X_upgrade2017_design_IdealBS_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/91X_upgrade2017_design_IdealBS_v4) as [91X_upgrade2017_design_IdealBS_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/91X_upgrade2017_design_IdealBS_v3) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/91X_upgrade2017_design_IdealBS_v4/91X_upgrade2017_design_IdealBS_v3):
      * Jet Probability Btagger corresponds to Phase1 geometry
      * ZDC reco geometry update : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2841/1.html
      * HCAL updates : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2912.html

   * **PhaseI 2017 realistic scenario** : [91X_upgrade2017_realistic_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/91X_upgrade2017_realistic_v4) as [91X_upgrade2017_realistic_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/91X_upgrade2017_realistic_v3) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/91X_upgrade2017_realistic_v4/91X_upgrade2017_realistic_v3):
      * Jet Probability Btagger corresponds to Phase1 geometry
      * ZDC reco geometry update : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2841/1.html
      * HCAL updates : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2912.html
      * CSC alignment and APE update : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2919.html
      * SiPixel Quality updated : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2922.html
   * **PhaseI 2018 cosmics scenario** : [91X_upgrade2018cosmics_realistic_deco_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/91X_upgrade2018cosmics_realistic_deco_v4) as [91X_upgrade2018cosmics_realistic_deco_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/91X_upgrade2018cosmics_realistic_deco_v3) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/91X_upgrade2018cosmics_realistic_deco_v4/91X_upgrade2018cosmics_realistic_deco_v3):
      * Jet Probability Btagger corresponds to Phase1 geometry
      * SiPixel Quality updated : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2922.html
      * CSC alignment and APE update : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2919.html

   * **PhaseI 2018 design scenario** : [91X_upgrade2018_design_IdealBS_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/91X_upgrade2018_design_IdealBS_v4) as [91X_upgrade2018_design_IdealBS_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/91X_upgrade2018_design_IdealBS_v3) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/91X_upgrade2018_design_IdealBS_v4/91X_upgrade2018_design_IdealBS_v3):
      * Jet Probability Btagger corresponds to Phase1 geometry

   * **PhaseI 2018 realistic scenario** : [91X_upgrade2018_realistic_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/91X_upgrade2018_realistic_v4) as [91X_upgrade2018_realistic_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/91X_upgrade2018_realistic_v3) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/91X_upgrade2018_realistic_v4/91X_upgrade2018_realistic_v3):
      * Jet Probability Btagger corresponds to Phase1 geometry
      * SiPixel Quality updated : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2922.html
      * CSC alignment and APE update : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2919.html

### CODE REVIEW

**Comment by arunhep** [comment]
please test

**Comment by franzoni** [comment]
+ 2017 TTbar realistic
  . specific regions of pixel detector where hits disappear (the plot below)
  . tracks disappearing in tracking-related plots in tracking, egamma and jet-met related histograms
  . no clear indication of impact from HCAL l1, csc, ZDC geometry, btag prob

2017-pixelphase1__fed_readout_pxbarrel_occupancy_per_channel_fed_1221

+ 2018
   . same observation as 2017
   . no plots available to assess the ECAL alpha changes; 

2018-pixelphase1__fed_readout_pxbarrel_occupancy_per_channel_fed_1221

+ 2016B data, runI MC
  no unexpected changes

**Comment by franzoni** [comment]
+1

**Comment by davidlange6** [comment]
Hi @arunhep @ianna - two questions
 1) I'm surprised to see no changes in CSC plots. Was the lack of change expected in spite of the CSC updates?
 2) Are the ZDC updated discussed/validated somewhere? I guess they are not covered by the usual tests.

**Comment by davidlange6** [comment]
(or maybe we only test 2017 design scenario, which is a mistake)?

**Comment by franzoni** [comment]
hello @davidlange6 

1) the short matrix run by the bot probes phase1_2017_realistic, which has received the CSC update => good; see below the details of workflows 10024 and 10024 . 
The update to the CSC alignment position error (the geometry itself is not touched)
is a refinement ( see entity of the modification and tests at the sign off talk here: https://indico.cern.ch/event/631393/contributions/2579524/  ) and , given the statistics of 10 events and the fact that plots are ported only of markedly different ( the chi2 relmont thresholds don't identify bit-wise differences ), I am not surprised we can't identify the effect.

2) we have not received documentation about ZDCRECO_Geometry_91YV1 . @ianna might comment further 



```

[18:27:56 - 17-05-11] /afs/cern.ch/user/f/franzoni/CMSSW_9_1_X_2017-05-08-2300/src % runTheMatrix.py -l 10024 -ne | grep cmsDriver
10024.0 TTbar_13TeV_TuneCUETP8M1_2017_GenSimFull+DigiFull_2017+RecoFull_2017+ALCAFull_2017+HARVESTFull_2017 [1]: cmsDriver.py TTbar_13TeV_TuneCUETP8M1_cfi  --conditions auto:phase1_2017_realistic -n 10 --era Run2_2017 --eventcontent FEVTDEBUG --relval 9000,50 -s GEN,SIM --datatier GEN-SIM --beamspot Realistic50ns13TeVCollision --geometry DB:Extended
                                           [2]: cmsDriver.py step2  --conditions auto:phase1_2017_realistic -s DIGI:pdigi_valid,L1,DIGI2RAW,HLT:@relval2017 --datatier GEN-SIM-DIGI-RAW -n 10 --geometry DB:Extended --era Run2_2017 --eventcontent FEVTDEBUGHLT
                                           [3]: cmsDriver.py step3  --conditions auto:phase1_2017_realistic -n 10 --era Run2_2017 --eventcontent RECOSIM,MINIAODSIM,DQM --runUnscheduled  -s RAW2DIGI,L1Reco,RECO,EI,PAT,VALIDATION:@standardValidation+@miniAODValidation,DQM:@standardDQM+@miniAODDQM --datatier GEN-SIM-RECO,MINIAODSIM,DQMIO --geometry DB:Extended
                                           [4]: cmsDriver.py step4  --conditions auto:phase1_2017_realistic -s ALCA:TkAlMuonIsolated+TkAlMinBias+MuAlOverlaps+EcalESAlign+TkAlZMuMu+HcalCalHBHEMuonFilter+TkAlUpsilonMuMu+TkAlJpsiMuMu --datatier ALCARECO -n 10 --geometry DB:Extended --era Run2_2017 --eventcontent ALCARECO
                                           [5]: cmsDriver.py step5  --conditions auto:phase1_2017_realistic -s HARVESTING:@standardValidation+@standardDQM+@miniAODValidation+@miniAODDQM --era Run2_2017 --filein file:step3_inDQM.root --scenario pp --filetype DQM --geometry DB:Extended --mc  -n 100
[18:28:09 - 17-05-11] /afs/cern.ch/user/f/franzoni/CMSSW_9_1_X_2017-05-08-2300/src % runTheMatrix.py -l 10042 -ne | grep cmsDriver
10042.0 ZMM_13TeV_TuneCUETP8M1_2017_GenSimFull+DigiFull_2017+RecoFull_2017+ALCAFull_2017+HARVESTFull_2017 [1]: cmsDriver.py ZMM_13TeV_TuneCUETP8M1_cfi  --conditions auto:phase1_2017_realistic -n 10 --era Run2_2017 --eventcontent FEVTDEBUG --relval 18000,100 -s GEN,SIM --datatier GEN-SIM --beamspot Realistic50ns13TeVCollision --geometry DB:Extended
                                           [2]: cmsDriver.py step2  --conditions auto:phase1_2017_realistic -s DIGI:pdigi_valid,L1,DIGI2RAW,HLT:@relval2017 --datatier GEN-SIM-DIGI-RAW -n 10 --geometry DB:Extended --era Run2_2017 --eventcontent FEVTDEBUGHLT
                                           [3]: cmsDriver.py step3  --conditions auto:phase1_2017_realistic -n 10 --era Run2_2017 --eventcontent RECOSIM,MINIAODSIM,DQM --runUnscheduled  -s RAW2DIGI,L1Reco,RECO,EI,PAT,VALIDATION:@standardValidation+@miniAODValidation,DQM:@standardDQM+@miniAODDQM --datatier GEN-SIM-RECO,MINIAODSIM,DQMIO --geometry DB:Extended
                                           [4]: cmsDriver.py step4  --conditions auto:phase1_2017_realistic -s ALCA:TkAlMuonIsolated+TkAlMinBias+MuAlOverlaps+EcalESAlign+TkAlZMuMu+HcalCalHBHEMuonFilter+TkAlUpsilonMuMu+TkAlJpsiMuMu --datatier ALCARECO -n 10 --geometry DB:Extended --era Run2_2017 --eventcontent ALCARECO
                                           [5]: cmsDriver.py step5  --conditions auto:phase1_2017_realistic -s HARVESTING:@standardValidation+@standardDQM+@miniAODValidation+@miniAODDQM --era Run2_2017 --filein file:step3_inDQM.root --scenario pp --filetype DQM --geometry DB:Extended --mc  -n 100
```

**Comment by ianna** [comment]
@davidlange6 - IMHO, the ZDC reco geometry tag update is purely technical. It seems that ZDCGeometry is not used in CMSSW:
http://cmslxr.fnal.gov/search?_filestring=&_string=ZDCGeometry
However, its payload exists in a GT and it differs from the ZDCGeometry (as CaloGeometry) built from XML. The new tag is to fix this discrepancy. 
Note, there is also a ZdcHardcodeGeometry producer (also not used).

**Comment by davidlange6** [comment]
actually the relmon settings should flag anything with a difference in the plot (so movements within bins are indeed not noticed, but other changes are). will look more closely

**Comment by franzoni** [comment]
hi @davidlange6, in any of the relmon reports produced by the bot
you can read "BinToBin (0.1)". 
How such comparison and threshold work: 
https://twiki.cern.ch/twiki/bin/view/CMSPublic/RelMon#Statistical_Tests
I conclude that plots are displayed if at least, in the setup we have for the bot,
90% or more of the bins differ, between target and reference.
More details below.

The fraction of bins with a different content
between target and reference instance of the same plot 
( ahttps://github.com/cms-sw/cmssw/blob/09c3fce6626f70fd04223e7dacebf0b485f73f54/Utilities/RelMon/python/utils.py#L345 ) is compared against the threshold ( https://github.com/cms-sw/cmssw/blob/09c3fce6626f70fd04223e7dacebf0b485f73f54/Utilities/RelMon/python/utils.py#L157 )

**Comment by davidlange6** [comment]
> On May 12, 2017, at 11:43 AM, Giovanni Franzoni <notifications@github.com> wrote:
> 
> hi @davidlange6, in any of the relmon reports produced by the bot
> you can read "BinToBin (0.1)".

ah - indeed, I didn't realize we had a context dependent switch between P(chi2)>0.99999999 and P(chi2)>0.1 - not sure thats a good thing. But indeed, this particular comparison was done with P(chi2)>0.1. 

That said, the reco tests show no changes (at the numerical level even in muons).

looking into it.

**Comment by franzoni** [comment]
hello, 
I've re-run the ttbar 2017 workflow  [1] over 100 events, in CMSSW_9_2_X_2017-05-08-2300 w/ and w/o the changes of this PR (files available: `/afs/cern.ch/user/f/franzoni/public/4davidl` ) 
Differences are present in muon-RECO related variables, see for instance chi2/dnf increase) 

csc-ali-ape-update

consistent with what  found by Luca in his study ( slide 7 of https://indico.cern.ch/event/631393/contributions/2579524/attachments/1455696/2246500/17_05_08_CSCasymptotic.pdf , green bs black).

[1] ` runTheMatrix.py  -l 10024  --command='-n 100'  >& mod.1.log &`

**Comment by franzoni** [comment]
feel free to ask more questions, as suits.
We have the replacement of https://github.com/cms-sw/cmssw/pull/18630 ready, as well as the pixel mapping update, it would help if we could have this PR integrated.

**Comment by davidlange6** [comment]
+1
that was the study i had planned to do..

**Comment by franzoni** [comment]
> that was the study i had planned to do..

good. 
Thanks @davidlange6

**Pull request merged**
