### PR TITLE
changes included from 10.1.X devel IB for oracle occi test

### PR DESCRIPTION
**Pull request by smuzaffar**
- getString -> getOraString
- getMessage -> getOraMessage
- added back the unit tests which were dropped by https://github.com/cms-sw/cmssw/pull/22346

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@ggovi , I am tring to backport the occi related changes from DEVEL IB in to normal IB but I see two unit tests are failing. My guess is this is because of #22346. Can you please check and provide a fix for these unit tests?

**Comment by fabiocos** [comment]
@smuzaffar @ggovi I agree with Shahzad, the sooner we integrate this the sooner we avoid further addition of incompatible code

**Comment by ggovi** [comment]
sorry I sent already the fix yesterday: #22400

**Comment by fabiocos** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
lets get this in IB to be used by new C++ abi

**Comment by fabiocos** [comment]
@ggovi @smuzaffar when I retriggered the test #22400 was already merged. Anyway now things are in the IB, so it will be easier to catch possible residual problems.

**Pull request merged**
