### PR TITLE
Run3-sim79 Enable the showerlibrary producer to work in the new CMSSW version

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Enable the showerlibrary producer for HF to work in the new CMSSW version

#### PR validation:

Tested using the test cfg file in SimG4CMS/ShowerLibraryProducer/test/python

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by abdoulline** [comment]
@bsunanda   Thanks a lot, Sunanda!  👍

**Comment by cvuosalo** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade

**Comment by civanch** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
