### PR TITLE
Fix for heavyIon object in both embedded and non-emb. HI samples

### PR DESCRIPTION
**Pull request by yetkinyilmaz**
Running pdigi_hi for Hydjet samples so that the input for the heavyIon object is produced which is (CrossingFrame<HepMCProduct>) by the same module in both embedded and non-embedded HI workflows.

pdigi_hi is added, and the relval workflows adjusted accordingly.

Tested workflows: 140, 145, 300, 140.53, in addition to those in runTheMatrix.py -s

Needed for RelVals, and especially needed for the release for MC DIGI campaign.

### CODE REVIEW

**Comment by diguida** [comment]
please test

**Comment by hengne** [comment]
please test  , DAS error can be temporary.

**Comment by hengne** [comment]
please test

**Comment by hengne** [comment]
OK, all matrix tests passed this time, but changed to addon test errors. 
I have tested by myself interactively using CMSSW_7_5_X_2015-12-03-1100 + this PR, all these addon tests commands and they actually all passed. Very strange. 
let me trigger the test again.

**Comment by hengne** [comment]
please test

**Comment by diguida** [comment]
@hengne @yetkinyilmaz I am launching a test with HI MC RelVals on top of this PR + #12644 Yesterday some of them were killed by my network... But they were running step 3. You can check my branch here:
https://github.com/cms-sw/cmssw/compare/CMSSW_7_5_X...diguida:includeHImenuIn75X_mix_75X_05

**Comment by diguida** [comment]
Almost there:

````
$ runTheMatrix.py -i all -l 140.0,140.1,140.2,140.3,140.4,145.0,300.0,301.0,302.0
140.0_HydjetQ_MinBias_2760GeV+HydjetQ_MinBias_2760GeVINPUT+DIGIHI2011+RECOHI2011+HARVESTHI2011 Step0-DAS_ERROR Step1-NOTRUN Step2-NOTRUN Step3-NOTRUN  - time date Fri Dec  4 12:01:06 2015-date Fri Dec  4 12:00:58 2015; exit: 1 0 0 0
140.1_QCD_Pt_80_120_13_HI+QCD_Pt_80_120_13_HIINPUT+DIGIHI+RECOHI+HARVESTHI Step0-PASSED Step1-PASSED Step2-FAILED Step3-NOTRUN  - time date Fri Dec  4 12:06:46 2015-date Fri Dec  4 12:01:02 2015; exit: 0 0 35584 0
140.2_PhotonJets_Pt_10_13_HI+PhotonJets_Pt_10_13_HIINPUT+DIGIHI+RECOHI+HARVESTHI Step0-DAS_ERROR Step1-NOTRUN Step2-NOTRUN Step3-NOTRUN  - time date Fri Dec  4 12:01:13 2015-date Fri Dec  4 12:01:04 2015; exit: 1 0 0 0
140.3_ZMM_13_HI+ZMM_13_HIINPUT+DIGIHI+RECOHI+HARVESTHI Step0-DAS_ERROR Step1-NOTRUN Step2-NOTRUN Step3-NOTRUN  - time date Fri Dec  4 12:01:25 2015-date Fri Dec  4 12:01:07 2015; exit: 1 0 0 0
140.4_ZEEMM_13_HI+ZEEMM_13_HIINPUT+DIGIHI+RECOHI+HARVESTHI Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED  - time date Fri Dec  4 12:06:14 2015-date Fri Dec  4 12:01:12 2015; exit: 0 0 0 0
145.0_HydjetQ_MinBias_5020GeV+HydjetQ_MinBias_5020GeVINPUT+DIGIHI+RECOHI+HARVESTHI Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED  - time date Fri Dec  4 12:10:50 2015-date Fri Dec  4 12:01:16 2015; exit: 0 0 0 0
300.0_Pyquen_GammaJet_pt20_2760GeV+Pyquen_GammaJet_pt20_2760GeV+DIGIHIMIX+RECOHIMIX+HARVESTHI Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED  - time date Fri Dec  4 12:17:10 2015-date Fri Dec  4 12:01:31 2015; exit: 0 0 0 0
301.0_Pyquen_DiJet_pt80to120_2760GeV+Pyquen_DiJet_pt80to120_2760GeV+DIGIHIMIX+RECOHIMIX+HARVESTHI Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED  - time date Fri Dec  4 12:23:14 2015-date Fri Dec  4 12:06:22 2015; exit: 0 0 0 0
302.0_Pyquen_ZeemumuJets_pt10_2760GeV+Pyquen_ZeemumuJets_pt10_2760GeV+DIGIHIMIX+RECOHIMIX+HARVESTHI Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED  - time date Fri Dec  4 12:21:22 2015-date Fri Dec  4 12:06:53 2015; exit: 0 0 0 0
6 6 5 5 tests passed, 3 0 1 0 failed
````

The failure in wf `140.1` is in the validation step, where it throws SEGV (!!!) due to wrong filling of the `DQMStore`:

````
#0  0x0000003a46e0f2ee in waitpid () from /lib64/libpthread.so.0
#1  0x00007fc0bd74ff48 in sig_dostack_then_abort () from /afs/cern.ch/cms/sw/ReleaseCandidates/vol1/slc6_amd64_gcc491/cms/cmssw/CMSSW_7_5_X_2015-11-29-1100/lib/slc6_amd64_gcc491/libFWCoreServices.so
#2  <signal handler called>
#3  0x00007fc0bbb309c4 in MonitorElement::Fill(double, double) () from /afs/cern.ch/cms/sw/ReleaseCandidates/vol1/slc6_amd64_gcc491/cms/cmssw/CMSSW_7_5_X_2015-11-29-1100/lib/slc6_amd64_gcc491/libDQMServicesCore.so
#4  0x00007fc08c32b007 in JetTester_HeavyIons::analyze(edm::Event const&, edm::EventSetup const&) () from /afs/cern.ch/cms/sw/ReleaseCandidates/vol1/slc6_amd64_gcc491/cms/cmssw/CMSSW_7_5_X_2015-11-29-1100/lib/slc6_amd64_gcc491/pluginValidationRecoJetsPlugins.so
#5  0x00007fc0cbf07011 in edm::stream::EDAnalyzerAdaptorBase::doEvent(edm::EventPrincipal&, edm::EventSetup const&, edm::ActivityRegistry*, edm::ModuleCallingContext const*) () from /afs/cern.ch/cms/sw/ReleaseCandidates/vol1/slc6_amd64_gcc491/cms/cmssw/CMSSW_7_5_X_2015-11-29-1100/lib/slc6_amd64_gcc491/libFWCoreFramework.so
#6  0x00007fc0cbefc9bf in edm::WorkerT<edm::stream::EDAnalyzerAdaptorBase>::implDo(edm::EventPrincipal&, edm::EventSetup const&, edm::ModuleCallingContext const*) () from /afs/cern.ch/cms/sw/ReleaseCandidates/vol1/slc6_amd64_gcc491/cms/cmssw/CMSSW_7_5_X_2015-11-29-1100/lib/slc6_amd64_gcc491/libFWCoreFramework.so
#7  0x00007fc0cbe3795c in decltype ({parm#1}()) edm::convertException::wrap<bool edm::Worker::doWork<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::MyPrincipal&, edm::EventSetup const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*)::{lambda()#1}>(bool edm::Worker::doWork<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::MyPrincipal&, edm::EventSetup const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*)::{lambda()#1}) () from /afs/cern.ch/cms/sw/ReleaseCandidates/vol1/slc6_amd64_gcc491/cms/cmssw/CMSSW_7_5_X_2015-11-29-1100/lib/slc6_amd64_gcc491/libFWCoreFramework.so
#8  0x00007fc0cbe37bb5 in bool edm::Worker::doWork<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::MyPrincipal&, edm::EventSetup const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*) () from /afs/cern.ch/cms/sw/ReleaseCandidates/vol1/slc6_amd64_gcc491/cms/cmssw/CMSSW_7_5_X_2015-11-29-1100/lib/slc6_amd64_gcc491/libFWCoreFramework.so
#9  0x00007fc0cbe3dcde in decltype ({parm#1}()) edm::convertException::wrap<void edm::Path::processOneOccurrence<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::MyPrincipal&, edm::EventSetup const&, edm::StreamID const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*)::{lambda()#1}>(void edm::Path::processOneOccurrence<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::MyPrincipal&, edm::EventSetup const&, edm::StreamID const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*)::{lambda()#1}) () from /afs/cern.ch/cms/sw/ReleaseCandidates/vol1/slc6_amd64_gcc491/cms/cmssw/CMSSW_7_5_X_2015-11-29-1100/lib/slc6_amd64_gcc491/libFWCoreFramework.so
#10 0x00007fc0cbe3dfa2 in void edm::Path::processOneOccurrence<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::MyPrincipal&, edm::EventSetup const&, edm::StreamID const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*) () from /afs/cern.ch/cms/sw/ReleaseCandidates/vol1/slc6_amd64_gcc491/cms/cmssw/CMSSW_7_5_X_2015-11-29-1100/lib/slc6_amd64_gcc491/libFWCoreFramework.so
#11 0x00007fc0cbe3e4ac in void edm::StreamSchedule::processOneEvent<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::MyPrincipal&, edm::EventSetup const&, bool)::{lambda()#1}::operator()() const () from /afs/cern.ch/cms/sw/ReleaseCandidates/vol1/slc6_amd64_gcc491/cms/cmssw/CMSSW_7_5_X_2015-11-29-1100/lib/slc6_amd64_gcc491/libFWCoreFramework.so
#12 0x00007fc0cbe3e68b in decltype ({parm#1}()) edm::convertException::wrap<void edm::StreamSchedule::processOneEvent<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::MyPrincipal&, edm::EventSetup const&, bool)::{lambda()#1}>(void edm::StreamSchedule::processOneEvent<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::MyPrincipal&, edm::EventSetup const&, bool)::{lambda()#1}) () from /afs/cern.ch/cms/sw/ReleaseCandidates/vol1/slc6_amd64_gcc491/cms/cmssw/CMSSW_7_5_X_2015-11-29-1100/lib/slc6_amd64_gcc491/libFWCoreFramework.so
#13 0x00007fc0cbe3e8e8 in void edm::StreamSchedule::processOneEvent<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::MyPrincipal&, edm::EventSetup const&, bool) () from /afs/cern.ch/cms/sw/ReleaseCandidates/vol1/slc6_amd64_gcc491/cms/cmssw/CMSSW_7_5_X_2015-11-29-1100/lib/slc6_amd64_gcc491/libFWCoreFramework.so
#14 0x00007fc0cbe3334c in edm::EventProcessor::processEvent(unsigned int) () from /afs/cern.ch/cms/sw/ReleaseCandidates/vol1/slc6_amd64_gcc491/cms/cmssw/CMSSW_7_5_X_2015-11-29-1100/lib/slc6_amd64_gcc491/libFWCoreFramework.so
#15 0x00007fc0cbe33b72 in edm::EventProcessor::processEventsForStreamAsync(unsigned int, std::atomic<bool>*) () from /afs/cern.ch/cms/sw/ReleaseCandidates/vol1/slc6_amd64_gcc491/cms/cmssw/CMSSW_7_5_X_2015-11-29-1100/lib/slc6_amd64_gcc491/libFWCoreFramework.so
#16 0x00007fc0cbe42e84 in edm::StreamProcessingTask::execute() () from /afs/cern.ch/cms/sw/ReleaseCandidates/vol1/slc6_amd64_gcc491/cms/cmssw/CMSSW_7_5_X_2015-11-29-1100/lib/slc6_amd64_gcc491/libFWCoreFramework.so
#17 0x00007fc0cac09c8a in tbb::internal::custom_scheduler<tbb::internal::IntelSchedulerTraits>::local_wait_for_all (this=0x7fc0c99e7d00, parent=..., child=<optimized out>) at ../../src/tbb/custom_scheduler.h:474
#18 0x00007fc0cbe33898 in edm::EventProcessor::readAndProcessEvent() () from /afs/cern.ch/cms/sw/ReleaseCandidates/vol1/slc6_amd64_gcc491/cms/cmssw/CMSSW_7_5_X_2015-11-29-1100/lib/slc6_amd64_gcc491/libFWCoreFramework.so
#19 0x00007fc0cbe107ad in statemachine::HandleEvent::readAndProcessEvent() () from /afs/cern.ch/cms/sw/ReleaseCandidates/vol1/slc6_amd64_gcc491/cms/cmssw/CMSSW_7_5_X_2015-11-29-1100/lib/slc6_amd64_gcc491/libFWCoreFramework.so
#20 0x00007fc0cbe12348 in statemachine::HandleEvent::HandleEvent(boost::statechart::state<statemachine::HandleEvent, statemachine::HandleLumis, boost::mpl::list<mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na>, (boost::statechart::history_mode)0>::my_context) () from /afs/cern.ch/cms/sw/ReleaseCandidates/vol1/slc6_amd64_gcc491/cms/cmssw/CMSSW_7_5_X_2015-11-29-1100/lib/slc6_amd64_gcc491/libFWCoreFramework.so
#21 0x00007fc0cbe1ac57 in boost::statechart::state<statemachine::HandleEvent, statemachine::HandleLumis, boost::mpl::list<mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na>, (boost::statechart::history_mode)0>::deep_construct(boost::intrusive_ptr<statemachine::HandleLumis> const&, boost::statechart::state_machine<statemachine::Machine, statemachine::Starting, std::allocator<void>, boost::statechart::null_exception_translator>&) () from /afs/cern.ch/cms/sw/ReleaseCandidates/vol1/slc6_amd64_gcc491/cms/cmssw/CMSSW_7_5_X_2015-11-29-1100/lib/slc6_amd64_gcc491/libFWCoreFramework.so
#22 0x00007fc0cbe1ae4c in boost::statechart::simple_state<statemachine::FirstLumi, statemachine::HandleLumis, boost::mpl::list<mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na>, (boost::statechart::history_mode)0>::react_impl(boost::statechart::event_base const&, void const*) () from /afs/cern.ch/cms/sw/ReleaseCandidates/vol1/slc6_amd64_gcc491/cms/cmssw/CMSSW_7_5_X_2015-11-29-1100/lib/slc6_amd64_gcc491/libFWCoreFramework.so
#23 0x00007fc0cbe2a7bc in edm::EventProcessor::runToCompletion() () from /afs/cern.ch/cms/sw/ReleaseCandidates/vol1/slc6_amd64_gcc491/cms/cmssw/CMSSW_7_5_X_2015-11-29-1100/lib/slc6_amd64_gcc491/libFWCoreFramework.so
#24 0x000000000040d09a in main::{lambda()#1}::operator()() const ()
#25 0x000000000040b486 in main ()

A fatal system signal has occurred: segmentation violation
````

The offender instruction is executed in `Validation/RecoJets/plugins/JetTester_HeavyIons.cc`.

@rkunnawa this is something you might want to watch.

**Comment by davidlt** [comment]
@diguida this was already reported a long time ago, IIRC, MonitorElement is 0x0, thus nullptr dereference.

**Comment by hengne** [comment]
+1

**Comment by hengne** [comment]
"operations" and "simulation", please help to verify and approve this PR, this is to fix some urgent HI workflows that are urgently needed for validation of the L1 trigger emulator, and corresponding GT and HLT. Thanks in advance!

**Comment by davidlange6** [comment]
seems we should get a fix to the problem @diguida found (which is already fixed in various places but apparently not here) before going further.

**Comment by yetkinyilmaz** [comment]
Hi David;
how can we do that?
Can you point to the fixes elsewhere that you're referring to?
If it's simple enough I can push it here promptly.
Thanks.

**Comment by davidlange6** [comment]
https://github.com/cms-sw/cmssw/pull/12452

**Comment by diguida** [comment]
@yetkinyilmaz do the following on top of the tip of this branch:

````
$ git cms-addpkg Validation/RecoJets
$ git cherry-pick 6214ba5d0abf112a7205f14712401aff27e00dbd
$ scram b -r -j 32
$ runTheMatrix.py -i all -l 140.1
$ git push my-cmssw mix_75X_05
````

**Comment by yetkinyilmaz** [comment]
Thanks Salvatore, but I had already tried this, and it gives me 
conflicts. The commit you mentioned was for 8_0_X. I think there was 
never a 75X-compatible version of this commit.
The actual author of the module will be around in 2-3 hours, I think I 
will wait for him to comment on properly fixing this.

**Comment by rkunnawa** [comment]
hi @diguida and @davidlange6, i fixed the necessary bugs in the module and they are available here https://github.com/rkunnawa/cmssw/commit/9bc34773d9903b1e540b79511c95492dac1ce390. Yetkin, since this is built on top of your code, please cherry pick this commit and it should be fixed. 
thanks! 
Raghav

**Comment by yetkinyilmaz** [comment]
I have merged @rkunnawa's fixes for the segfault in jet validation.

**Comment by diguida** [comment]
please test

**Comment by hengne** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by deguio** [comment]
changes are fine for DQM, but are there corresponding PR for 76 and 80?

**Comment by yetkinyilmaz** [comment]
@deguio , this PR is only relevant for CMSSW_7_5_X, because the mixing workflows in the other releases are different. Those releases do need updates as well, however it is not this bugfix, there will have to be more work for those.

**Comment by yetkinyilmaz** [comment]
Hi. Can the remaining signatures comment? We need this in CMSSW_7_5_7_patch4.

**Comment by deguio** [comment]
+1

**Pull request merged**
