### PR TITLE
Tracker Parameters Schema Update for 74x

### PR DESCRIPTION
**Pull request by ianna**
- Back-ported from 75x as requested by ORP

### CODE REVIEW

**Comment by ianna** [comment]
@davidlange6 - this one replaces #7903

**Comment by ianna** [comment]
+1

**Comment by ianna** [comment]
@cerminar, @ggovi,  @diguida, @mmusich, @apfeiffer1 - the schema is good to go. Does it make any difference which CMSSW version should be used for producing tags? Please, expect a GT update request shortly.

**Comment by ggovi** [comment]
+1

**Comment by diguida** [comment]
+1

**Comment by ianna** [comment]
@davidlange6 - I forgot to mention this one at ORP. It should go in to keep DropBox consistent with 75x.

**Comment by diguida** [comment]
@davidlange6 can you please approve it? As mentioned at the latest ORP, this is needed for Geometry payloads to be included in GT.

**Comment by davidlange6** [comment]
hum, at the last ORP we concluded 750pre1 was sufficient.. can discuss again Tuesday.

**Comment by ianna** [comment]
@davidlange6 - please, see Marco's comment on #7966

**Comment by davidlange6** [comment]
i’m hoping the dropbox can switch to pre1… (we want it to also to get the right boost into 740)

**Comment by ianna** [comment]
@davidlange6 - I see no harm in updating so far unused schema in 74x. Just in case and if we might want to back-port it in the future

**Pull request closed without merging**
