### PR TITLE
Xerces Leaked Memory Clean Up

### PR DESCRIPTION
**Pull request by ianna**
* Significant Xerces leaks were detected by @Dr15Jones in response to the following post about failing jobs at T0:
https://hypernews.cern.ch/HyperNews/CMS/get/recoDevelopment/1525.html

* Fixed and tested in CMSSW_9_2_X_2017-05-28-2300 environment with step3 of 10024.0_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2017_GenSimFull+DigiFull_2017+RecoFull_2017+ALCAFull_2017+HARVESTFull_2017

Note: Many improvements were introduced in L1Trigger/L1TCommon/src/XmlConfigReader.cc which was declared obsolete in the meanwhile.

@kkotov - FYI, please transfer the changes to a new parser or let me know which one is used

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
please test

**Comment by Dr15Jones** [comment]
Thanks

**Comment by ianna** [comment]
+1

**Comment by ianna** [comment]
+1

**Comment by kkotov** [comment]
@ianna to my best knowledge, there are only a couple of leaks from incorrect use of transcode:
https://github.com/ianna/cmssw/blob/xerces-memory-leak-cleanup-t0/L1Trigger/L1TCommon/src/XmlConfigParser.cc#L341
https://github.com/ianna/cmssw/blob/xerces-memory-leak-cleanup-t0/L1Trigger/L1TCommon/src/XmlConfigParser.cc#L361
I'll correct it in one of my future PRs. Just to explain the context:
1) this code is not running recurring; normally it is executed only once
2) this code I inherited from one of our developers

**Comment by ianna** [comment]
@kkotov - thanks!

**Comment by ianna** [comment]
@ghellwig, @arunhep, @cerminar, @cmsbuild, @rekovic, @franzoni, @ggovi, @mulhearn, @davidlange6 can you please review it and eventually sign? Thanks.

**Comment by ianna** [comment]
@ghellwig, @arunhep, @cerminar, @cmsbuild, @rekovic, @franzoni, @ggovi, @mulhearn, @davidlange6 can you please review it and eventually sign? Thanks.

**Comment by davidlange6** [comment]
merge

**Comment by slava77** [comment]
it seems like this PR broke CTPPS reconstruction
can this be reverted until that problem is fixed?

**Comment by ianna** [comment]
@slava77 - how can I reproduce the problem with CTPPS?

**Comment by slava77** [comment]
run jenkins tests and look at reco or DQM comparisons

incidentally this PR was tested together with #19148  and I noticed the problem
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_9_2_X_2017-06-12-2300+19148/20588/136.731_RunSinglePh2016B+RunSinglePh2016B+HLTDR2_2016+RECODR2_2016reHLT_skimSinglePh_HIPM+HARVESTDR2/CTPPS_TrackingStrip_sector%2045_station%20210_fr_hr_plane%2001.html

**Pull request merged**
