### PR TITLE
re-introduce IORawData/CSCCommissioning module for CSC data files conversion

### PR DESCRIPTION
**Pull request by barvic**
#### PR description:
Re-introduce IORawData/CSCCommissioning CSC-specific utilities module, which was originally used to convert CSC Local DAQ raw data format files to/from CMSSW ROOT raw data files format.
- convert CSC local DAQ raw data files to CMSSW root data files
- extract CSC raw data from CMSSW root data files and convert it to CSC local DAQ raw data format files

This module was removed from the IORawData back in 2013 because of failed dependencies (it was depending on obsolete DaqSource), which were not fixed at that time.

This module is still used by members of CSC group for various commissioning and development tasks, when CSC Local DAQ raw data files are produced and which needs to be converted to CMSSW-compatible data format for further processing with CMSSW-based analysises.
Also it provides extraction and conversion of CMSSW format raw data to CSC Local DAQ raw data format files to use with CSC standalone tools outside of CMSSW framework.

#### PR validation:
It compiles and was tested with recently produced CSC Local DAQ files.

### CODE REVIEW

**Comment by silviodonato** [comment]
cc @cms-sw/muon-dpg-l2

**Comment by dildick** [comment]
It appears this PR has stalled. This code would be useful for data-vs-emulator studies of Run-3 CSC trigger data with cosmics at the B904 test-stand.

**Comment by silviodonato** [comment]
assign daq

**Comment by silviodonato** [comment]
> It appears this PR has stalled. This code would be useful for data-vs-emulator studies of Run-3 CSC trigger data with cosmics at the B904 test-stand.

I'm sorry I didn't realize that it was not assigned to anybody

**Comment by silviodonato** [comment]
@mrodozov could you add this new packaged and assign it to alca?
@cms-sw/alca-l2 could you confirm that it should be assigned to you ?

**Comment by smorovic** [comment]
+1
fully CSC specific

**Comment by silviodonato** [comment]
```
IORawData/CSCCommissioning/src/FileReaderDCC.cc
/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_12_0_X_2021-04-27-1100/src/IORawData/CSCCommissioning/src/FileReaderDCC.cc:20:27: warning: 'bzero' call operates on objects of type 'unsigned short' while the size is based on a different type 'unsigned short *' [-Wsizeof-pointer-memaccess]
```

**Comment by christopheralanwest** [comment]
> @mrodozov could you add this new packaged and assign it to alca?
> @cms-sw/alca-l2 could you confirm that it should be assigned to you ?

@mrodozov @silviodonato I don't understand the reasoning behind the category assignments for the `IORawData` packages in general. Several of them are assigned only to `alca` and not to `daq`. In addition, none of the changes in this PR involve an `ESSource` or an `ESProducer`. I don't see any reason for an assignment to `alca`. Is there some additional consideration of which I am not aware?

**Comment by silviodonato** [comment]
I'm sorry for the confusion. I wanted to say
@mrodozov could you add this new packaged and assign it to daq?
@cms-sw/daq-l2 could you confirm that it should be assigned to you ?

Indeed I've assigned this PR to DAQ

**Comment by davidlange6** [comment]
There isn’t much here related to daq - its basically csc analysis codes (eg, like DPGAnalysis packages)

**Comment by mrodozov** [comment]
oops.

**Comment by mrodozov** [comment]
ok it's in daq

**Comment by smorovic** [comment]
Hi @silviodonato,
I don't see this package belonging to DAQ (i.e. central DAQ), it is CSC-specific code (except the mention of Run-1 DAQ input source module that is long gone).
There is no problem signing it now from my side, though.

**Comment by smorovic** [comment]
+1

**Comment by silviodonato** [comment]
+1
@barvic please consider to add a unit test to check that this package works in the future (see https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideDevelopersGuide#Add_tests_to_your_package or other packages as an example)

**Pull request merged**
