### PR TITLE
Remove QuadrupletSeedMerger as obsolete

### PR DESCRIPTION
**Pull request by makortel**
This PR removes the obsolete QuadrupletSeedMerger algorithm (which created pixel quadruplet seeds by merging pixel triplets), and moves the quadruplet layer set configuration `quadrupletseedmerging_cff` under `RecoTracker/TkSeedingLayers` with the name `PixelLayerQuadruplets_cff` following the existing convention for pairs and triplets.

Tested in 9_3_0_pre3, no changes expected.

@rovere @VinInn @ebrondol @felicepantaleo

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by perrotta** [comment]
It looks like PixelLayerTriplets are still needed in HI reco...

@makortel : while you are fixing it, you could also consider fixing what found by the code checker in https://github.com/cms-sw/cmssw/pull/20127#issuecomment-321763731

**Comment by makortel** [comment]
@cmsbuild, please test

@perrotta, done both

**Comment by dmitrijus** [comment]
+1

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/20127	caa4f5b
- cleanup is done, as described
- jenkins tests pass and comparisons show no differences

**Comment by davidlange6** [comment]
+1

**Pull request merged**
