### PR TITLE
[9.4.X] Update GT: Update all L1T tags (except L1TMuonEndCapForestRcd) + adding GT used for MC v2 production

### PR DESCRIPTION
**Pull request by lpernie**
# Summary of changes in Global Tags
This PR update all the GT with the latest  L1T TAGs, except the TAG L1TMuonEndCapForestRcd that is currently pointed by a static file.
Also the GT used for the MC v2 production (94X_mc2017_realistic_v10) is included.
## RunII simulation

   * **RunII Asymptotic scenario** : [94X_mcRun2_asymptotic_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_mcRun2_asymptotic_v2) as [94X_mcRun2_asymptotic_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_mcRun2_asymptotic_v0) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_mcRun2_asymptotic_v2/94X_mcRun2_asymptotic_v0):
      * Add L1T TAG, but not L1TMuonEndcapParamsRcd

   * **RunII CRAFT scenario** : [94X_mcRun2cosmics_startup_deco_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_mcRun2cosmics_startup_deco_v2) as [94X_mcRun2cosmics_startup_deco_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_mcRun2cosmics_startup_deco_v0) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_mcRun2cosmics_startup_deco_v2/94X_mcRun2cosmics_startup_deco_v0):
      * Add L1T TAG, but not L1TMuonEndcapParamsRcd

   * **RunII Ideal scenario** : [94X_mcRun2_design_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_mcRun2_design_v2) as [94X_mcRun2_design_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_mcRun2_design_v0) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_mcRun2_design_v2/94X_mcRun2_design_v0):
      * Add L1T TAG, but not L1TMuonEndcapParamsRcd

   * **RunII Proton-Lead scenario** : [94X_mcRun2_pA_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_mcRun2_pA_v2) as [94X_mcRun2_pA_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_mcRun2_pA_v0) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_mcRun2_pA_v2/94X_mcRun2_pA_v0):
      * Add L1T TAG, but not L1TMuonEndcapParamsRcd

   * **RunII Startup scenario** : [94X_mcRun2_startup_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_mcRun2_startup_v2) as [94X_mcRun2_startup_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_mcRun2_startup_v0) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_mcRun2_startup_v2/94X_mcRun2_startup_v0):
      * Add L1T TAG, but not L1TMuonEndcapParamsRcd

## RunI data

   * **RunI HLT processing** : [94X_dataRun2_HLT_frozen_v6](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_dataRun2_HLT_frozen_v6) as [94X_dataRun2_HLT_frozen_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_dataRun2_HLT_frozen_v3) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_dataRun2_HLT_frozen_v6/94X_dataRun2_HLT_frozen_v3):
      * Add L1T TAG, but not L1TMuonEndcapParamsRcd

   * **RunI Offline processing** : [94X_dataRun2_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_dataRun2_v4) as [94X_dataRun2_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_dataRun2_v2) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_dataRun2_v4/94X_dataRun2_v2):
      * Add L1T TAG, but not L1TMuonEndcapParamsRcd

## RunII data

   * **RunII HLTHI processing** : [94X_dataRun2_HLTHI_frozen_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_dataRun2_HLTHI_frozen_v5) as [94X_dataRun2_HLTHI_frozen_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_dataRun2_HLTHI_frozen_v2) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_dataRun2_HLTHI_frozen_v5/94X_dataRun2_HLTHI_frozen_v2):
      * Add L1T TAG, but not L1TMuonEndcapParamsRcd

   * **RunII HLT relval processing** : [94X_dataRun2_HLT_relval_v8](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_dataRun2_HLT_relval_v8) as [94X_dataRun2_HLT_relval_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_dataRun2_HLT_relval_v5) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_dataRun2_HLT_relval_v8/94X_dataRun2_HLT_relval_v5):
      * Add L1T TAG, but not L1TMuonEndcapParamsRcd

   * **RunII Offline processing** : [94X_dataRun2_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_dataRun2_v4) as [94X_dataRun2_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_dataRun2_v2) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_dataRun2_v4/94X_dataRun2_v2):
      * Add L1T TAG, but not L1TMuonEndcapParamsRcd

   * **RunII Offline relval processing** : [94X_dataRun2_relval_v10](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_dataRun2_relval_v10) as [94X_dataRun2_relval_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_dataRun2_relval_v5) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_dataRun2_relval_v10/94X_dataRun2_relval_v5):
      * Add L1T TAG, but not L1TMuonEndcapParamsRcd

   * **RunII Prompt processing** : [94X_dataRun2_PromptLike_v9](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_dataRun2_PromptLike_v9) as [94X_dataRun2_PromptLike_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_dataRun2_PromptLike_v5) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_dataRun2_PromptLike_v9/94X_dataRun2_PromptLike_v5):
      * Add L1T TAG, but not L1TMuonEndcapParamsRcd

   * **RunI HLT processing** : [94X_dataRun2_HLT_frozen_v6](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_dataRun2_HLT_frozen_v6) as [94X_dataRun2_HLT_frozen_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_dataRun2_HLT_frozen_v3) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_dataRun2_HLT_frozen_v6/94X_dataRun2_HLT_frozen_v3):
      * Add L1T TAG, but not L1TMuonEndcapParamsRcd

## Upgrade

   * **PhaseII realistic scenario** : [94X_upgrade2023_realistic_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_upgrade2023_realistic_v5) as [94X_upgrade2023_realistic_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_upgrade2023_realistic_v2) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_upgrade2023_realistic_v5/94X_upgrade2023_realistic_v2):
      * Add L1T TAG, but not L1TMuonEndcapParamsRcd

   * **PhaseI 2018 cosmics scenario** : [94X_upgrade2018cosmics_realistic_deco_v6](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_upgrade2018cosmics_realistic_deco_v6) as [94X_upgrade2018cosmics_realistic_deco_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_upgrade2018cosmics_realistic_deco_v4) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_upgrade2018cosmics_realistic_deco_v6/94X_upgrade2018cosmics_realistic_deco_v4):
      * Add L1T TAG, but not L1TMuonEndcapParamsRcd

   * **PhaseI 2018 design scenario** : [94X_upgrade2018_design_IdealBS_v7](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_upgrade2018_design_IdealBS_v7) as [94X_upgrade2018_design_IdealBS_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_upgrade2018_design_IdealBS_v5) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_upgrade2018_design_IdealBS_v7/94X_upgrade2018_design_IdealBS_v5):
      * Add L1T TAG, but not L1TMuonEndcapParamsRcd

   * **PhaseI 2018 realistic scenario** : [94X_upgrade2018_realistic_v7](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_upgrade2018_realistic_v7) as [94X_upgrade2018_realistic_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_upgrade2018_realistic_v5) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_upgrade2018_realistic_v7/94X_upgrade2018_realistic_v5):
      * Add L1T TAG, but not L1TMuonEndcapParamsRcd

## 2017_MC

   * **PhaseI 2017 cosmics peak scenario** : [94X_mc2017cosmics_realistic_peak_v6](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_mc2017cosmics_realistic_peak_v6) as [94X_mc2017cosmics_realistic_peak_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_mc2017cosmics_realistic_peak_v4) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_mc2017cosmics_realistic_peak_v6/94X_mc2017cosmics_realistic_peak_v4):
      * Add L1T TAG, but not L1TMuonEndcapParamsRcd

   * **PhaseI 2017 cosmics scenario** : [94X_mc2017cosmics_realistic_deco_v6](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_mc2017cosmics_realistic_deco_v6) as [94X_mc2017cosmics_realistic_deco_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_mc2017cosmics_realistic_deco_v4) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_mc2017cosmics_realistic_deco_v6/94X_mc2017cosmics_realistic_deco_v4):
      * Add L1T TAG, but not L1TMuonEndcapParamsRcd

   * **PhaseI 2017 design scenario** : [94X_mc2017_design_IdealBS_v7](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_mc2017_design_IdealBS_v7) as [94X_mc2017_design_IdealBS_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_mc2017_design_IdealBS_v5) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_mc2017_design_IdealBS_v7/94X_mc2017_design_IdealBS_v5):
      * Add L1T TAG, but not L1TMuonEndcapParamsRcd

   * **PhaseI 2017 realistic scenario** : [94X_mc2017_realistic_v10](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_mc2017_realistic_v10) as [94X_mc2017_realistic_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_mc2017_realistic_v5) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_mc2017_realistic_v10/94X_mc2017_realistic_v5):
      * Add L1T TAG, but not L1TMuonEndcapParamsRcd

### CODE REVIEW

**Comment by lpernie** [comment]
please test

**Comment by lpernie** [comment]
backport of #21137

**Comment by arunhep** [comment]
@lpernie I think the description of this PR is outdated. Can you please update it? 
Thanks.

**Comment by lpernie** [comment]
please test

**Comment by lpernie** [comment]
please test

**Comment by lpernie** [comment]
@davidlange6 this PR is now consistent with the GT used for MCv2.

**Comment by arunhep** [comment]
@lpernie please update the description of this PR. The GTs you mentioned are not according to what actually are present in autoCond.

**Comment by arunhep** [comment]
@lpernie more comments 
- with the update of offline GTs in this PR : 
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_dataRun2_v4/94X_dataRun2_v2
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_dataRun2_relval_v8/94X_dataRun2_relval_v5
we are trying to deploy rereco 2017 conditions in release (even before they are validated).
i dont think this is the aim of this PR.
ideally we should do it only after full validation and rereco injection.
this PR should only update L1T tags and possibly V2 MC conditions.

**Comment by lpernie** [comment]
please test

**Comment by lpernie** [comment]
Hi @arunhep you are right.
Please check now:
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/94X_dataRun2_relval_v5/94X_dataRun2_relval_v9

Also, I updated the PR description

**Comment by lpernie** [comment]
please test

**Comment by lpernie** [comment]
We have the first SingleMuon data relvals with new GT:
https://hypernews.cern.ch/HyperNews/CMS/get/relval/9123.html
https://hypernews.cern.ch/HyperNews/CMS/get/relval/9124.html

This should further support this PR.

**Comment by rekovic** [comment]
Hi @davidlange6,
2017 data RelVal samples with this updated GT look fine for L1T.   So L1T gives green light for this GT to be used for MC production and 2017 data reprocessing.

For 2016 data reprocessing, the GT would have to be updated, but I guess this should not be a show stopper.

**Comment by davidlange6** [comment]
i think its best that we just skip to a PR with the actual GTs used for the rereco and v2 digi-reco...

**Comment by arunhep** [comment]
+1

**Comment by arunhep** [comment]
@davidlange6 this PR already contains GT which are being used for MC V2.
For re-reco, once the conditions will be validated through central campaign (which are open from last week)  https://cms-pdmv.cern.ch/valdb/?srch=AlCa-EOY_RR-2017&selected=AlCa-EOY_RR-2017B,AlCa-EOY_RR-2017Cv1,AlCa-EOY_RR-2017Cv2,AlCa-EOY_RR-2017D,AlCa-EOY_RR-2017E&Reconstruction=true&RData=true
we will make another PR to propagate those ones to offline queues.

**Comment by lpernie** [comment]
Hi @davidlange6 why this PR is not merged yet?

**Comment by davidlange6** [comment]
hi- indeed, I didn't come back to this pr to understand that it now contains more than just the L1 changes. It looks like we miss
1) a title that describes what is actually changing
2) a short summary of the changes
3) and I realize that perhaps the 100x GT does not yet have these changes? Please confirm.

**Comment by lpernie** [comment]
Hi @davidlange6  
. I changed the PR title.
. The description now offers an extensive and more short summary of the changes.
. In 10X the PR is already merged: https://github.com/cms-sw/cmssw/pull/21137
Initially these 2 PR were identical. Following you suggestion to make this PR compatible with the GT used for MC v2 production, we removed from all GT the TAG L1TMuonEndCapForestRcd and we kept the static file that load this TAG. Also, we added the GT for the MC v2 production.

**Comment by lpernie** [comment]
Hi @davidlange6, can this PR be merged now?

**Comment by davidlange6** [comment]
merge

**Pull request merged**
