### PR TITLE
pileup profile for RunIII2024Summer24 MC compaign

### PR DESCRIPTION
**Pull request by romeof**
#### PR description:
pileup profile for RunIII2024Summer24 MC compaign

#### PR validation:
Tested on cmssw

##### Notes
backport to 140X

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by DickyChant** [comment]
Hi all, just wonder what's the timeline for merging this PR so that we can initiate a back-port for 2024 MC production.

Thanks

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
