### PR TITLE
Start conversion to using user-defined literals for Geometry

### PR DESCRIPTION
**Pull request by cvuosalo**
It is hoped that replacing constants from CLHEP/Units/GlobalSystemOfUnits.h with user-defined literals from DetectorDescription/Core/interface/DDUnits.h will improve performance by eliminating unnecessary floating point operations and conversions. This PR is a preliminary step in a campaign to convert the Geometry code to employ user-defined literals.

The changes in this PR do not appreciably change performance since the affected code is run only once at the start of simulation, but it does show the sort of changes entailed in the conversion to user-defined literals.

### CODE REVIEW

**Comment by cvuosalo** [comment]
Note that two small changes in program behavior have been implemented. First, the old code was truncating fractional values in degrees of rotations, so values of n.0 to n.899999 were truncated to n.0 degrees (where n could be positive or negative). On the advice of @ianna, this truncation has been eliminated, but it might cause a very small change in the value of rotations.
Second, a test for a non-zero rotation in the DDMuonAngular code was changed from requiring std::abs(rotation) >= 0.9_deg to std::abs(rotation) >= 1.0_deg, so rotations of 0.9 degrees in the old code will be skipped by the new code.

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by ianna** [comment]
@cvuosalo - Has GEM geometry changed?
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_10_3_X_2018-09-11-2300+24509/28403/21234.0_TTbar_14TeV+TTbar_14TeV_TuneCUETP8M1_2023D21_GenSimHLBeamSpotFull14+DigiFullTrigger_2023D21+RecoFullGlobal_2023D21+HARVESTFullGlobal_2023D21/MuonGEMHitsV_GEMHitsTask.html
It seems, all workflows which have GEM included show differences in Reco:
 * https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_10_3_X_2018-09-11-2300+24509/28403/11624.0_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2019_GenSimFull+DigiFull_2019+RecoFull_2019+HARVESTFull_2019+ALCAFull_2019/
 * https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_10_3_X_2018-09-11-2300+24509/28403/20034.0_TTbar_14TeV+TTbar_14TeV_TuneCUETP8M1_2023D17_GenSimHLBeamSpotFull14+DigiFullTrigger_2023D17+RecoFullGlobal_2023D17+HARVESTFullGlobal_2023D17/
 * https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_10_3_X_2018-09-11-2300+24509/28403/20434.0_TTbar_14TeV+TTbar_14TeV_TuneCUETP8M1_2023D19_GenSimHLBeamSpotFull14+DigiFullTrigger_2023D19+RecoFullGlobal_2023D19+HARVESTFullGlobal_2023D19/

**Comment by ianna** [comment]
hold

**Comment by cvuosalo** [comment]
@ianna: I will restore the truncation of rotation angle to the nearest degree for the GEM code and test to see if the discrepancies disappear.

**Comment by ianna** [comment]
@cvuosalo - there is a bug in the algorithm placing GEM chambers in -Z, -Y, +X - see the snapshot:
screenshot 2018-09-18 11 29 13

```
cmsRun $CMSSW_RELEASE_BASE/src/Fireworks/Geometry/python/dumpSimGeometry_cfg.py tag=2019
cmsShow -c geo.fwc --sim-geom-file cmsSimGeom-2019.root
```

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
@ianna: I cannot see how any of my code changes could be rotating some of the GEM chambers incorrectly. Can you think of any way my new code could cause these problems?

**Comment by ianna** [comment]
@cvuosalo - a new rotation is created only when there is no other rotation present with the same name in the Store. It is done for memory consumption optimization. Could the rotation name be truncated?

**Comment by cvuosalo** [comment]
@ianna: Thanks. Your suggestion helped me find the bug. I hadn't considered negative, three-digit rotation angle values, and they were not being formatted correctly as strings. I hope my fix eliminates the discrepancies.

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
There are still differences. This current version did change the format of the rotation name string slightly. The baseline has rotation names in this format:
RG005.000000
RG0-330.000000

The current version added a 0 for the positive values:
RG0005.000000
RG-330.000000

I was hoping that consistent rotation names would be good enough, but if these names are parsed somewhere in the code, then that could be the cause of the discrepancies.

**Comment by cvuosalo** [comment]
The GEM chambers appear to now be correctly placed:

gemsok

I don't know what is causing the differences in the comparison test.

**Comment by ianna** [comment]
@cvuosalo - yes, it looks like both the RPC and GEM geometries are correct (e.g. both look exactly the same as before this PR).

@jshlee and @hyunyong - could you, please, run some validation on this PR? It looks like the 2019 workflow does not show any differences in GEM data, but the 2013 ones do. Thanks.

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
@cvuosalo - geometry validation seems to be fine for the RPC geometry. DTs do show superficial differences in a norm vector, for example:
```
normVect  (-1,5.17598e-16,1.33963e-16)
```
vs
```
normVect  (-1,5.17598e-16,1.8941e-16)
```
To reproduce the results, please:
```
git cms-addpkg Validation/Geometry
./Validation/Geometry/test/dddvsdb/runDDDvsDBGeometryValidation.sh  auto:upgrade2019 GeometryExtended2019
```
Please, see:
https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideDDDversusDataBaseValidation

**Comment by ianna** [comment]
The DT reconstruction geometry has not been updated since CMSSW 5.0. It differs from the currently built from 10.3.x pre-release:
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/tags/DTRECO_Geometry_103YV1/DTRECO_Geometry_50YV3
These differences are unrelated to this PR.

**Comment by ianna** [comment]
+1

There are no differences in either 2019 or 2023D17. The other 2023D* scenario differences could be due to low statistics.

**Comment by fabiocos** [comment]
@ianna 2018 and older setups use the DB snapshot, so you rely on upgrade scenarios for direct DD validation, am I correct?

**Comment by ianna** [comment]
@fabiocos - no, DD validation is done by comparison XML vs DB vs local DB with a script:
```
git cms-addpkg Validation/Geometry
./Validation/Geometry/test/dddvsdb/runDDDvsDBGeometryValidation.sh  auto:upgrade2019 GeometryExtended2019

```

**Comment by fabiocos** [comment]
+1

**Pull request merged**
