### PR TITLE
Make order of canDeleteEarly, and LogErrorHarvester includeModules and excludeModules deterministic

### LINKED ISSUE #183: Make order in canDeleteEarly and LogErrorHarvester includeModules and excludeModules deterministic
See https://github.com/cms-sw/cmssw/pull/34409 and https://github.com/cms-sw/cmsdist/pull/7112#issuecomment-876589924

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

This PR makes the order of lists for `canDeleteEarly` parameter set in `customiseEarlyDelete()`, and the `LogErrorHarvester` `includeModules` and `excludeModules` parameters deterministic. This should make diffs of `edmConfigDump` outputs easier to interpret. These were spotted by @slava77 in https://github.com/cms-sw/cmssw/pull/34409.

Resolves https://github.com/makortel/framework/issues/183

#### PR validation:

Tested repeating `edmConfigDump` for RECO configuration of 4.53 that these configuration parameters did not change.

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
@cmsbuild, please test

For cleaner comparisons

**Comment by makortel** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
