### PR TITLE
bTag validation for PhaseII reco

### PR DESCRIPTION
**Pull request by swertz**
Add Phase2 validation of b-tagging (FullSim only, so not the DQM part). We're using the same temporary trick as #15407.

Successfully tested on workflow nr. 10424.0.

### CODE REVIEW

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
+1

For #15494 fd8ad9cb4ad4871a69d4b483b7dcaa66d3a9cfc9

Temporary b tagging validation for Phase 2 without DQM. Similar to the Phase 2 Jet-MET validation in #15466, which has already been merged.

The code changes are satisfactory, and Jenkins tests against baseline CMSSW_8_1_X_2016-08-17-1100 show no significant differences.

**Comment by swertz** [comment]
PR updated to fix conflict due to merging of #15466.

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by civanch** [comment]
+1

**Comment by cvuosalo** [comment]
+1

For #15494 11386be6e4279ffb7e2e5e0d5648c861cd569135

Second approval, after re-base. New Jenkins tests are still OK.

**Comment by kpedro88** [comment]
@swertz merge conflicts again

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
+1

For #15494 ef608f2b11df7ba8576a1a0770da6506d3817514

Third approval, after another re-base. New Jenkins tests are still OK.

**Comment by dmitrijus** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
