### PR TITLE
Enable HCAL DPG HO filter modules in autoSkim.py

### PR DESCRIPTION
**Pull request by kfjack**
Enable the following two skim modules proposed by HCAL DPG to autoSkim.py
JetHTJetPlusHOFilter => JetHT PD
SinglePhotonJetPlusHOFilter => SinglePhoton PD

### CODE REVIEW

**Comment by fabozzi** [comment]
please test

**Comment by fabozzi** [comment]
+1

**Comment by fabozzi** [comment]
@davidlange6 
when merged and tested in IB we want to ask for a test at T0

**Comment by davidlange6** [comment]
+1

**Pull request merged**
