### PR TITLE
DAQ - adding DCS validity bitfield for high voltage in FED 1022

### PR DESCRIPTION
**Pull request by smorovic**
DCS HV validity field added to the DCSRecord for discerning if information was available to the data reader.

#### PR validation:

Added a unittest with the FED dump containing the new format. Test was set to require status seen in the application creating the payload, and it passes.
The whole chain (input source, unpacker) was also tested on the raw file from a cosmic run (with DCS v1 only).

### CODE REVIEW

**Comment by smorovic** [comment]
@cmsbuild please test

**Comment by smorovic** [comment]
@cmsbuild please test

**Comment by smorovic** [comment]
+1

**Comment by jpata** [comment]
+reconstruction
- DAQ only, no reco-relevant code changes (the code was reviewed by visual inspection)
- no reco changes expected/observed

**Comment by perrotta** [comment]
@smorovic  DataFormats/OnlineMetaData/test/dump_run000001_event1350583585_fed1022.txt seems like an output file from some test that sneaked in the PR by mistake: if so, please remove

**Comment by smorovic** [comment]
@perotta, It is needed by the unit test:
https://github.com/cms-sw/cmssw/pull/36294/files#diff-7aa942529fe0564733b0e59e94a6d58177fe3112321c0647bc2c74ba512eba97R115

Similar to another already present file (dump of raw payload of the FED):
https://github.com/cms-sw/cmssw/blob/master/DataFormats/OnlineMetaData/test/dump_run000001_event00013761_fed1022.txt

**Comment by perrotta** [comment]
+1

**Pull request merged**
