### PR TITLE
[RFC] Test clang-tidy --checks modernize-use-emplace

### PR DESCRIPTION
**Pull request by fwyzard**
See the description at https://clang.llvm.org/extra/clang-tidy/checks/modernize-use-emplace.html .

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by Dr15Jones** [comment]
looks good to me

**Comment by cvuosalo** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade

**Comment by jfernan2** [comment]
May I ask why the CMSSW Code Rules errors are not relevant in this PR?

**Comment by fwyzard** [comment]
Which ones ?

**Comment by jfernan2** [comment]
These ones:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-2df5f8/6476/codeRules
Thanks

**Comment by makortel** [comment]
All those exist already. I didn't check the full diff of this PR, but I'm pretty confident this PR does not add any new `catch(...)`.

**Comment by jfernan2** [comment]
+1

**Comment by qliphy** [comment]
+1

**Comment by santocch** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by mommsen** [comment]
+1

**Comment by slava77** [comment]
```IgnoreImplicitConstructors=1``` may be better to reduce the number of somewhat unnecessary changes.
IMHO, it may be a bit burdensome to write code like in Alignment/MuonAlignmentAlgorithms/src/MuonResidualsAngleFitter.cc
```c++
  std::vector<std::string> parName;
  std::vector<double> step;
  parName.emplace_back("angle");
  step.push_back(0.1);
```
I guess the alternative is to make everything that compiles to use ```emplace_back```, then the above will also need to have ```step.emplace_back(0.1);```

**Comment by fwyzard** [comment]
> `IgnoreImplicitConstructors=1` may be better to reduce the number of somewhat unnecessary changes.
> IMHO, it may be a bit burdensome to write code like in Alignment/MuonAlignmentAlgorithms/src/MuonResidualsAngleFitter.cc
> 
> ```c++
>   std::vector<std::string> parName;
>   std::vector<double> step;
>   parName.emplace_back("angle");
>   step.push_back(0.1);
> ```
> 
> I guess the alternative is to make everything that compiles to use `emplace_back`, then the above will also need to have `step.emplace_back(0.1);`

Can you elaborate ?

The current code is something like
```
  std::vector<std::string> parName;
  std::vector<double> step;
  parName.push_back(std::string("angle"));
  step.push_back(0.1);
```
so setting `IgnoreImplicitConstructors=1` shouldn't make any difference, since the constructor is explicit.

**Comment by slava77** [comment]
My reading of ```IgnoreImplicitConstructors=1``` in the docs was that the following will be kept unchanged
```c++
  std::vector<std::string> parName;
  std::vector<double> step;
  parName.push_back("angle");
  step.push_back(0.1);
```
instead of the current case where we get ```parName.emplace_back("angle");```, while the next line stays with push_back

**Comment by fwyzard** [comment]
I understood the same as you - but in the present code we have
```
  std::vector<std::string> parName;
  std::vector<double> step;
  parName.push_back(std::string("angle"));
  step.push_back(0.1);
```
which is not an implicit constructor - so I would expect that it will be changed to `emplace_back()` anyway ?

**Comment by fwyzard** [comment]
I did a simple test, starting with
```c++
#include <iostream>
#include <string>
#include <vector>

int main(void) {

  std::vector<int> ints;
  std::vector<std::string> strings;

  ints.push_back(42);
  ints.push_back(int{42});

  strings.push_back("Hello world");
  strings.push_back(std::string{"Hello world"});

  std::cout << ints.size() << " vs " << strings.size() << std::endl;

  return 0;
}
```

Running `clang-tidy` with `modernize-use-emplace.IgnoreImplicitConstructors = 0` complains about
```
/home/fwyzard/test/emplace_back/test.cc:13:11: warning: use emplace_back instead of push_back [modernize-use-emplace]
  strings.push_back("Hello world");
          ^~~~~~~~~~
          emplace_back(
/home/fwyzard/test/emplace_back/test.cc:14:11: warning: use emplace_back instead of push_back [modernize-use-emplace]
  strings.push_back(std::string{"Hello world"});
          ^~~~~~~~~~~~~~~~~~~~~~             ~
          emplace_back(
```

Running `clang-tidy` with `modernize-use-emplace.IgnoreImplicitConstructors = 1` complains only about
```
/home/fwyzard/test/emplace_back/test.cc:14:11: warning: use emplace_back instead of push_back [modernize-use-emplace]
  strings.push_back(std::string{"Hello world"});
          ^~~~~~~~~~~~~~~~~~~~~~             ~
          emplace_back(
```

So, using `IgnoreImplicitConstructors = 1` does allow using `strings.push_back("Hello world")` .

**Comment by fwyzard** [comment]
As a separate test, it looks like `emplace_back()` is never turned back into `puch_back()`.

**Comment by alja** [comment]
+1

**Pull request closed without merging**
