### PR TITLE
Run3-sim113 Take care of deprecated codes in FastSimulation/Validation

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Take care of deprecated codes in FastSimulation/Validation

#### PR validation:

Use the runTheMatrix test workflows 

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@sbein Please approve

**Comment by bsunanda** [comment]
@civanch Please approve this

**Comment by civanch** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
