### PR TITLE
[12_4_X] [TsosGaussianStateConversions] proposal fix for Gsf Tracking segmentation fault when no states are passing selection criteria

### PR DESCRIPTION
**Pull request by swagata87**
#### PR description:

Backport of https://github.com/cms-sw/cmssw/pull/40017, to address https://github.com/cms-sw/cmssw/issues/39987.

#### PR validation:

`runTheMatrix.py -l 12434.0` ran fine.

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
backport of https://github.com/cms-sw/cmssw/pull/40017

**Comment by perrotta** [comment]
@smuzaffar apparently tests are not able to start here: can anything be done for it?

**Comment by rappoccio** [comment]
@cms-sw/reconstruction-l2 can you sign this today? We'd like to cut the next 12_4 ASAP.

**Comment by francescobrivio** [comment]
> We'd like to cut the next 12_4 ASAP.

Please Sal see the discussion in https://github.com/cms-sw/cmssw/issues/39987#issuecomment-1316832648 befor cutting a new 12_4_X

**Comment by swagata87** [comment]
> wouldn't a backport of #40084 be needed as well

yes it is here now: https://github.com/cms-sw/cmssw/pull/40085

**Comment by mmusich** [comment]
> yes it is here now: https://github.com/cms-sw/cmssw/pull/40085

Given the long latencies if reco signatures lately, isn't perhaps more straightforward to cherry pick that commit directly here?

**Comment by perrotta** [comment]
@mandrenguyen @clacaputo  could you please review, and possibly sign for @cms-sw/reconstruction-l2, at your earliest convenience this and the other PRs which were marked as "urgent" for 12_4_X? Thank you!

**Comment by mandrenguyen** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
