### PR TITLE
Fastsim 74X: fix truth matching for recoTracks from PU events

### PR DESCRIPTION
**Pull request by lveldere**
required to validation digi-reco PU mixing

### CODE REVIEW

**Comment by lveldere** [comment]
please test

**Comment by lveldere** [comment]
-1

FullSim test succeed, but the original issue with FastSim is only partially fixed

**Comment by slava77** [comment]
Lukas, if you "-1" your own PR, you could more effectively close it instead and then reopen when the issue is fixed.
From your comment it sounds like the PR is broken.

**Comment by lveldere** [comment]
please test

**Comment by cvuosalo** [comment]
+1

For #8653 4ac1e5f47d80d1a65482d08e25bc894fff51f21c

Fixing truth matching for PU tracks. Correcting MC truth values would not be expected to alter reco quantities. This PR is the same as #8654 for 75X, which has already been approved by Reco.

The code changes are satisfactory, and Jenkins tests against baseline CMSSW_7_4_X_2015-04-07-1100 show no significant differences. The validateJR test for workflow 140.53_RunHI2011 erroneously shows differences in most quantities, but these results are due to some problem unrelated to this PR.

**Comment by civanch** [comment]
+1

**Comment by lveldere** [comment]
@davidlange6, @degano, @ktf, @smuzaffar

Can you merge this one?
It's a bug fix that only hits FastSim, and we really don't want a new 74 release without it.

**Comment by lveldere** [comment]
@davidlange6, @degano, @ktf, @smuzaffar

Can you merge this one?
It's a bug fix that only hits FastSim, and we really don't want a new 74 release without it.

**Comment by davidlange6** [comment]
@lveldere - is this code _only_ used in fastsim?

Also - please remove the printouts..

**Comment by lveldere** [comment]
@davidlange6 
The dataformat classes are only used in FastSim
The code touched in the mixingmodule is of course shared with FullSim
Removing the couts...

**Comment by slava77** [comment]
rebase, maybe?

**Comment by lveldere** [comment]
you're quick :-)
rebased

**Comment by lveldere** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by lveldere** [comment]
@slava77 @cvuosalo

could you sign this one again?
only change since your previous signatures: 2 couts removed.
Thanks

**Comment by cvuosalo** [comment]
+1

For #8653 7c7868018a98d206fdbbfb3e243ee85a2bf3aeac

A very minor change to non-reco code gives no cause to alter the previous Reco approval of this PR.

The most recent Jenkins tests show differences not related to this PR, maybe because of changes that went into 74X since this PR was created 20 days ago.

**Comment by slava77** [comment]
@cvuosalo 
this PR starts from CMSSW_7_4_X_2015-04-22-2300
while the jenkins tests are made with CMSSW_7_4_X_2015-04-22-1100
It's not the 20 day age.

You can see in jenkins logs that instead of checking the effect of the +42/-10 changes in 7 files, we are given a test of " 56 files changed, 52281 insertions(+), 287570 deletions(-)"
https://cmssdt.cern.ch/jenkins/job/ib-any-integration/4342/consoleFull

**Comment by davidlange6** [comment]
+1

**Comment by davidlange6** [comment]
@lveldere - seems that this PR does not merge now - likely a conflict with a different fastsim request that I just accepted. Could you provide a fix?

**Comment by lveldere** [comment]
please test

**Comment by cvuosalo** [comment]
+1

For #8653 cfcaad47e0d2e7f234570dee74121721f82d80e4

This PR has already been approved twice by Reco. The most recent changes are very minor and cause no problems. The Jenkins test results are contaminated by a dozen other PRs that were included.

**Comment by lveldere** [comment]
@civanch @mdhildreth 
Hi Mike, Vladimir

Could you sign this one once more?

Thanks

Lukas

**Pull request merged**
