### PR TITLE
New L1REPACK workflow for DATA with simulation of TPs 

### PR DESCRIPTION
**Pull request by rekovic**
This is a test.

A new L1T workflow defined as step `L1REPACK:FullSimTP` for running on DATA is introduced.
It is designed for the needs of AlCa group for tests at RelVal where most of Trigger Primitives are re-simulated and used as inputs to L1T.  

In this workflow L1T emulation uses the following TPs:
-- sim DT TPs
-- unpacked CSC TPs 
-- sim Ecal TPs
-- sim Hcal TPs  

Note: Unpacked CSC TPs are used because the simCSC TPs have offset of BX=2.  Till this is fixed, 
prefer to use unpacked CSC TPs than to individually configure muon track finders (EMTF, OMTF) emulators to do internal BX shifting of its input TPs.

An example command using the step `L1REPACK:FullSimTP` on a RAW 2016 data file:

<pre>
cmsDriver.py L1TEST --python_filename=l1t_test.py -s L1REPACK:FullSimTP  --era=Run2_2016 --conditions=80X_dataRun2_HLT_v12 -n 10 --data --filein=/store/data/Run2016B/ZeroBias/RAW/v2/000/274/442/00000/F08D3D87-762C-E611-BBB8-02163E014160.root --eventcontent  FEVTDEBUGHLT  
</pre>

### CODE REVIEW

**Comment by franzoni** [comment]
hi @rekovic moving here the technical part of this thread:
https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2471/1/1/1.html
Thanks a lot for setting this up.

This one (CMSSW_8_0_13_patch1 + this PR merged):

`cmsDriver.py step2  --datatier FEVTDEBUGHLT --conditions auto:run2_hlt_relval -s L1REPACK:FullSimTP,HLT:@relval2016 --process reHLT --data  --era Run2_2016 --eventcontent FEVTDEBUGHLT -n 100`

runs ok  on the first 100 events. This serves the purpose of 1) logging anew the L1 results into the output and 2) running HLT seeded by the re-emulated TP's + L1

Because we'll need to feed  re-emulated TP's + L1 + HLT results to the DQM which in relvals has to run in a subsequent step, I ought to run L1REPACK:FullSimTP also in the subsequent cmsDriver, which would look like this : 

`cmsDriver.py step3  --conditions auto:run2_data_relval -s L1REPACK:FullSimTP,RAW2DIGI,L1Reco,RECO,SKIM:HighMET,EI,PAT,ALCA:SiStripCalZeroBias+SiStripCalMinBias+TkAlMinBias+EcalESAlign,DQM:@standardDQM+@miniAODDQM --runUnscheduled  --process reRECO --data  --era Run2_2016 --eventcontent RECO,MINIAOD,DQM --hltProcess reHLT --scenario pp --datatier RECO,MINIAOD,DQMIO --customise Configuration/DataProcessing/RecoTLR.customisePostEra_Run2_2016 -n 100`

that runs into problems: 

`ValueError: Trying to override definition of simEcalTriggerPrimitiveDigis while it is used by the sequence SimL1Emulator
 new object defined in: /afs/cern.ch/cms/slc6_amd64_gcc530/cms/cmssw-patch/CMSSW_8_0_13_patch1/python/SimCalorimetry/EcalTrigPrimProducers/ecalTriggerPrimitiveDigis_cfi.py
 existing object defined in: /afs/cern.ch/cms/slc6_amd64_gcc530/cms/cmssw-patch/CMSSW_8_0_13_patch1/python/SimCalorimetry/EcalTrigPrimProducers/ecalTriggerPrimitiveDigis_with_suppressed_cfi.py`

possibly stemming from https://github.com/cms-sw/cmssw/pull/15117/files#diff-4107c235caff1d8f224757e1938390f8R50 ? 

Before I dig further, do you see flaws in the logic I put forward ?
How do you suggest we address this ?

**Comment by franzoni** [comment]
@mmusich 
(see previous post)

**Comment by mmusich** [comment]
@franzoni thanks for tagging. 
@rekovic is this meant for merging? Shall we trigger the tests? 
To all: would it make sense to add this new step in one wf of the relval matrix?

**Comment by franzoni** [comment]
@mmusich 
we might as well trigger tests. Yet this new step won't be exercised. Only assessing the minimal change to ConfigBuilder

**Comment by franzoni** [comment]
@cmsbuild  please test

**Comment by mmusich** [comment]
@franzoni my proposal to add this step in the matrix would be exactly to be able to see the problem you report in https://github.com/cms-sw/cmssw/pull/15117#issuecomment-230691508

**Comment by franzoni** [comment]
the error stems from DAS and does not relate to the commits in this PR

**Comment by franzoni** [comment]
@cmsbuild please test

**Comment by rekovic** [comment]
@franzoni  Thanks!

The problem was arising in the steps of  ```L1REPACK:FullSimTP, RAW2DIGI```.
Namely, in case of ```L1REPACK:FullSimTP``` the Ecal TP Producer was loaded [here](https://github.com/cms-sw/cmssw/blob/CMSSW_8_0_X/L1Trigger/Configuration/python/CaloTriggerPrimitives_cff.py#L4)
```from SimCalorimetry.EcalTrigPrimProducers.ecalTriggerPrimitiveDigis_with_suppressed_cfi import *```

while in case of ```RAW2DIGI``` [here](https://github.com/cms-sw/cmssw/blob/CMSSW_8_0_X/Configuration/StandardSequences/python/RawToDigi_cff.py#L14)
```from SimCalorimetry.EcalTrigPrimProducers.ecalTriggerPrimitiveDigis_cff import *```
 
I am not sure why the Ecal TP Producer is loaded in the ```RAW2DIGI``` step (I did not run Matrix Tests without it).  Naively speaking it seamed like a rather strange place for it to be loaded. Is this intended?
In any case, the problem of conflicting ```load``` statements was solved by syncing the statement in ```L1REPACK:FullSimTP``` to that one in ```RAW2DIGI```.

The step ```L1REPACK,RAW2DIGI``` is successfully tested with:

```cmsDriver.py L1TEST --python_filename=l1t_test_L1REPACKFullSimTP-RAW2DIGI.py -s L1REPACK:FullSimTP,RAW2DIGI --era=Run2_2016 --conditions=80X_dataRun2_HLT_v12 -n 10 --data --filein=/store/data/Run2016B/ZeroBias/RAW/v2/000/274/442/00000/F08D3D87-762C-E611-BBB8-02163E014160.root --eventcontent FEVTDEBUGHLT```

Your test from above successfully writes out the output python file: 

```cmsDriver.py step3 --conditions auto:run2_data_relval -s L1REPACK:FullSimTP,RAW2DIGI,L1Reco,RECO,SKIM:HighMET,EI,PAT,ALCA:SiStripCalZeroBias+SiStripCalMinBias+TkAlMinBias+EcalESAlign,DQM:@standardDQM+@miniAODDQM --runUnscheduled --process reRECO --data --era Run2_2016 --eventcontent RECO,MINIAOD,DQM --hltProcess reHLT --scenario pp --datatier RECO,MINIAOD,DQMIO --customise Configuration/DataProcessing/RecoTLR.customisePostEra_Run2_2016 -n 10```

**Comment by rekovic** [comment]
@mmusich  @franzoni 
> @franzoni my proposal to add this step in the matrix would be exactly to be able to see the problem you report in #15117 (comment) (by @mmusich )

It would indeed be useful if we added the above mentioned step in the matrix, and repeat the tests.

**Comment by mmusich** [comment]
@hengne @fabozzi @srimanob please see https://github.com/cms-sw/cmssw/pull/15117#issuecomment-231034401, maybe you can help in setting it up.

**Comment by fabozzi** [comment]
@mmusich @franzoni 
I have made an additional ZeroBias relval including L1REPACK:FullSimTP as in the example above, 
see branch 
https://github.com/fabozzi/cmssw/tree/from-CMSSW_8_0_14_newl1repack
Local test is fine. How should we proceed?

**Comment by mmusich** [comment]
thanks @fabozzi, I would suggest @rekovic cherry-picks in this one https://github.com/fabozzi/cmssw/commit/0165be35d27946b3bb4cb1a6e35360d57ef20f17

**Comment by rekovic** [comment]
@mmusich  Done.

**Comment by mmusich** [comment]
@rekovic thanks!

**Comment by mmusich** [comment]
please test

**Comment by franzoni** [comment]
@rekovic 

In https://github.com/cms-sw/cmssw/pull/15117#issuecomment-230809613 , good question:

<< I am not sure why the Ecal TP Producer is loaded in the RAW2DIGI step (I did not run Matrix Tests without it). Naively speaking it seamed like a rather strange place for it to be loaded. Is this intended? >>

It's possible @slava77 might know the history there.

I am running over a sisable set of events the concerned workflow, to verify that all collections are fed as we expect and we can pick up differences in DQM. I'll update when read.

@fabozzi 
Francesco, why shouldn't this new scheme of L1 emulation be run on all 2016 data relvals? As long as the GT offers the same L1 configuration as was run at P5, the emulated content should (approximately) be the same as the L1 logged in RAW. Whenever updates ought to be validated in the TP or L1 configuration, it's natural that a mixture of event topologies be offered to the DPG and L1 validators. Just a thought.

**Comment by fabozzi** [comment]
@franzoni 
I understood from the discussion that it was necessary to make a test on one relval before making it the default for all 2016B (I cannot submit a test relval until the new L1REPACK is not in a release). If we are confident that the local test is sufficient, then I have no objection to migrate all the relvals (and drop the test one.)

**Comment by franzoni** [comment]
ciao Francesco @fabozzi 

> I understood from the discussion that it was necessary to make a test on one relval before making it the > default for all 2016B

sounds more than plausible!

**Comment by fabozzi** [comment]
+1

**Comment by franzoni** [comment]
Dear colleagues, we took the relval inserted by @fabozzi in this PR, run it using RAW from JetHT.

We have verified that:

- both 
   step1: L1REPACK:FullSimTP+HLT and
   step2: L1REPACK:FullSimTP+RECO+DQM
   run ok over 100 events

- taking an update to the TP configuration of the HCAL L1 object to see an actual effect (see details https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2440.html), we've checked that the TP's as emulated in step2 by L1REPACK:FullSimTP reproduce the same TP's as already emulated in the HCAL DQM sequence.

The changes induced by the updated HCAL L1 object adds primitives in the high |eta| region (see map basebase-EtCutEmul-map.png and the extra TP's in vlad-updatedL1Object-EtCutEmul-map.png).

image

image

image

**Comment by franzoni** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
