### PR TITLE
Add and fix example configurations in the /test directories of Pythia8Interface and EvtGenInterface

### PR DESCRIPTION
**Pull request by mkirsano**

### CODE REVIEW

**Comment by mkirsano** [comment]
There is something wrong in this test because this PR concerns only examples (example configurations in the /test subdirectories). Can you please check?

**Comment by davidlange6** [comment]
yes, there was a problem with the tests (the GT).
but meanwhile, please give this PR a meaningful title for the release notes. Thanks

**Comment by bendavid** [comment]
+1

**Comment by davidlange6** [comment]
@cmsbuild, please test

**Comment by davidlange6** [comment]
+1

**Pull request merged**
