### PR TITLE
HLT menu development for `12_3_X`

### PR DESCRIPTION
**Pull request by missirol**
backport of #37474

#### PR description:

Development of HLT menus for `CMSSW_12_3_X`.

Includes the integration of the following JIRA tickets.

  - [CMSHLT-2244](https://its.cern.ch/jira/browse/CMSHLT-2244): [TSG] Replace `PFJetsMatchedToFilteredCaloJetsProducer` by `HLTPFJetsMatchedToFilteredCaloJetsProducer`.
  - [CMSHLT-2252](https://its.cern.ch/jira/browse/CMSHLT-2252): [MUO] Update of muon isolation for Run 3.
  - [CMSHLT-2259](https://its.cern.ch/jira/browse/CMSHLT-2259): [TAU,EXO] Bugfix for dxy cut in displaced-tau trigger.

#### PR validation:

TSG tests.

#### If this PR is a backport, please specify the original PR and why you need to backport that PR:

#37474

Development of HLT menus for Run-3 startup.

### CODE REVIEW

**Comment by missirol** [comment]
please test

**Comment by missirol** [comment]
+hlt

 - the RelVals-INPUT error must be unrelated to this PR
 - differences in outputs of Run-3 wfs are compatible with the changes to the GRun HLT menu

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
urgent

**Comment by Martin-Grunewald** [comment]
relval input tests now pass

**Comment by Martin-Grunewald** [comment]
@perrotta @qliphy 
Please merge for 12_3_0

**Comment by perrotta** [comment]
+1
- Same HLT menu as the one already merged in master

**Pull request merged**
