### PR TITLE
Phase2 Tracker Digitizer updated to have the possibility to used planer pixel algorithm in 3D pixel

### PR DESCRIPTION
**Pull request by suchandradutta**
#### PR description:
Update to include the possibility to use planer-pixel digitization algorithm (PixelDigitizerAlgorithm) for 3D-pixel modules. A configuration parameter  usePseudoPixel3DAlgo is introduced to activate/dis-activate this possibility. 

  - what changes are expected in the output if any : None
  - what other PRs or externals it depends upon if any : None
  
#### PR validation:

Used FourMuon events  (runTheMatrix option 20800.0) and compared the histograms 

@emiglior @tvami @duartej

### CODE REVIEW

**Comment by suchandradutta** [comment]
@tvami I did both code-checks and code-format before doing the 'push' . I have tried to do that again now but there is no further update.  You can see there are two commits :
   -  [e411402](https://github.com/cms-sw/cmssw/pull/41010/commits/e411402e4b10f38b25759c244a011d55b30ba6e5)
   -  [118498a](https://github.com/cms-sw/cmssw/pull/41010/commits/118498a600557eff9b8a80ac29e887799cdd3407)

Looking at the [patch ](https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-41010/34531/code-format.patch) it looks like the code-checks was performed on the first commit. 

I do not understand why the second commit is not considered

**Comment by mmusich** [comment]
code-checks

**Comment by mmusich** [comment]
@suchandradutta 

> I do not understand why the second commit is not considered

It looks like your second commit predates the timestamp of the first code-checks, which is why the bot did not re-run it.
Now all is cleared up and we can run tests.

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by suchandradutta** [comment]
> @suchandradutta
> 
> > I do not understand why the second commit is not considered
> 
> It looks like your second commit predates the timestamp of the first code-checks, which is why the bot did not re-run it. Now all is cleared up and we can run tests.

I do not know either! I created the PR after the 2nd commit.

**Comment by mmusich** [comment]
test parameters
   * workflow = 20800.0
   * relvals_opt= -w upgrade

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by civanch** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

**Comment by rappoccio** [comment]
+1

**Pull request merged**
