### PR TITLE
Remove depreciated DNN-based tau-Ids

### PR DESCRIPTION
**Pull request by mbluj**
#### PR description:

This PR is to remove depreciated DNN-based tau-Ids: DPFIsolation (a dedicated module) and DeepTauID v1 (a v1-related part of the deepTauId module). These tau-Ids was superseded by deepTauID v2 and are not present in official workflows.

In addition two outdated and unused modules are also removed.

No changes are expected.

This PR will be accompanied by another PR to cms-data removing model files of removed DNN-based tau-Ids (https://github.com/cms-data/RecoTauTag-TrainingFiles/pull/9)

#### PR validation:

Limited matrix tests successful.

### CODE REVIEW

**Comment by kandrosov** [comment]
@mbluj thank you for removing the old deeptau and DPF code!
One small comment: for consistency, `deepTau2017v1` should also be removed from `runTauIdMVA.py`.

**Comment by mbluj** [comment]
> @mbluj thank you for removing the old deeptau and DPF code! One small comment: for consistency, `deepTau2017v1` should also be removed from `runTauIdMVA.py`.

Yes, indeed it should be removed, it was forgotten. I will fix it shortly.

**Comment by jpata** [comment]
@cmsbuild please test

**Comment by jpata** [comment]
type tau

**Comment by clacaputo** [comment]
+reconstruction

- removing deprecated tau-ids
- no reco changes expected or observed

**Comment by perrotta** [comment]
please test with https://github.com/cms-data/RecoTauTag-TrainingFiles/pull/9/files

**Comment by perrotta** [comment]
> please test with https://github.com/cms-data/RecoTauTag-TrainingFiles/pull/9/files

If there are no issues with the combined test, we can remove also the data files at the same time

**Comment by perrotta** [comment]
ping bot

**Comment by perrotta** [comment]
> please test with https://github.com/cms-data/RecoTauTag-TrainingFiles/pull/9/files

Ok, I deleted that comment: I wouldn't like bot suddenly wakes up and start the tests.
But maybe the problem was simply that I added "/files" at the end of the link...
Anyhow, I'm testing the other way around, i.e. the data file together with this PR in  https://github.com/cms-data/RecoTauTag-TrainingFiles/pull/9

**Comment by perrotta** [comment]
+1
- This can be merged independently of https://github.com/cms-data/RecoTauTag-TrainingFiles/pull/9: that removal of the not used any more data files will be considered an independent clean up, once this PR is merged

**Pull request merged**
