### PR TITLE
Remove HE rechits from noise filter consideration, backport of PR22337

### PR DESCRIPTION
**Pull request by jaehyeok**
Backport of https://github.com/cms-sw/cmssw/pull/22337

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
> Reco comparison results: 14 differences found in the comparisons

this is not good in the scope of 10_0_X: the content of reco products should remain unchanged in a production release.
Perhaps it's easier to make this change configurable.

**Comment by slava77** [comment]
@deguio @jaehyeok 

are any of the modified flags ever used in hbhereco or anything similar?

The tests done in jenkins show changes only in hcalnoise flags, but the number of events tested is low and may not pick up some corner cases in case there is a dependency.
If no other downstream objects depend on these hcalnoise flags, we could still have this PR accepted as is based on the limited scope and otherwise effectively broken variable.
Otherwise we'll at least need to wait for 10_1_0_pre3 relval to become available first.

Still, if this is needed just for TSG studies, a configurable variant would be much more acceptable.

**Comment by mariadalfonso** [comment]
@slava77 
These flags are not used in the process.hbhereco and also particle flow doesn't look at these flags.

These flags are used
1) offline via the HcalNoiseSummary, usually recommented by jetMET at miniAOD level 
2) online via recHit cleaning with the METtriggers such as HLT_MET120_HBHENoiseCleaned

So as now the siPM flags are broken, so any studies for the 2) will not be correct.

**Comment by mariadalfonso** [comment]
@slava77 
some note here after discussing with @jaehyeok

HLT run the post-recHit collapser in the 10_0_X (still), the collapser makes the noise flags also similar between the new HE and the OLD, the inefficiency in the HE should then not arise in this scenario (this is why this was not noted in the HEP17 last year)

Up to the time HLT run "collapsed" there is no need to merge this PR
If there is the desire to study the removal of this post-recHit collapser the HLT_MET120_HBHENoiseCleaned should not be looked (HLT_MET120 or similar are there)

**Comment by slava77** [comment]
>  some note here after discussing with @jaehyeok

@jaehyeok @mariadalfonso 
thanks for the clarifications.
IIUC, this PR is a palliative and apparently can even do some (perhaps negligible) harm in the collapsed scenario.
I think that this gives a strong argument to make this removal configurable and also have it in the master.

**Comment by slava77** [comment]
actually, perhaps no configuration is needed.
HBHERecHitAuxSetter::OFF_COMBINED should tell if the hit is merged depths or not.

**Comment by slava77** [comment]
So, if this PR is made in sync with the master (as of https://github.com/cms-sw/cmssw/pull/22337	0b3598e), there will be no effect on default HLT setup and there will be some effect only on RECO quantities.
In such a state, this still does not qualify as a backport useful for TSG studies.

If you agree, I suggest to close this PR.

**Comment by jaehyeok** [comment]
@slava77 

I agree that this PR can be closed.

**Comment by slava77** [comment]
> I agree that this PR can be closed.

OK. You are in control of the "close" button.

**Comment by jaehyeok** [comment]
Closed this PR.

**Pull request closed without merging**
