### PR TITLE
Update global tags to include new EGamma regression

### PR DESCRIPTION
**Pull request by christopheralanwest**
#### PR description:

This PR adds test GTs needed to test PR #26892 and should be merged simultaneously with that PR. I created a separate PR so that I could launch the PR tests myself now but the two PRs could be merged if that's more convenient. The naming of the GTs will be fixed with the autoCond update that finalizes the 2017 UL data and MC GTs. The diffs of the changed GTs with respect to the current autoCond GTs are below:

106X_mcRun1_design_forPR26892_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_mcRun1_design_forPR26892_v1/106X_mcRun1_design_v1
106X_mcRun1_realistic_forPR26892_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_mcRun1_realistic_forPR26892_v1/106X_mcRun1_realistic_v1
106X_mcRun1_HeavyIon_forPR26892_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_mcRun1_HeavyIon_forPR26892_v1/106X_mcRun1_HeavyIon_v1
106X_mcRun1_pA_forPR26892_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_mcRun1_pA_forPR26892_v1/106X_mcRun1_pA_v1
106X_mcRun2_startup_forPR26892_v2
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_mcRun2_startup_forPR26892_v2/106X_mcRun2_startup_v2
106X_mcRun2_asymptotic_l1stage1_forPR26892_v2
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_mcRun2_asymptotic_l1stage1_forPR26892_v2/106X_mcRun2_asymptotic_l1stage1_v2
106X_mcRun2_design_forPR26892_v3
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_mcRun2_design_forPR26892_v3/106X_mcRun2_design_v3
106X_mcRun2_asymptotic_forPR26892_v3
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_mcRun2_asymptotic_forPR26892_v3/106X_mcRun2_asymptotic_v3
106X_mcRun2_HeavyIon_forPR26892_v2
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_mcRun2_HeavyIon_forPR26892_v2/106X_mcRun2_HeavyIon_v2
106X_mcRun2_pA_forPR26892_v2
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_mcRun2_pA_forPR26892_v2/106X_mcRun2_pA_v2
106X_dataRun2_forPR26892_v11
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_dataRun2_forPR26892_v11/106X_dataRun2_v11
106X_dataRun2_relval_forPR26892_v10
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_dataRun2_relval_forPR26892_v10/106X_dataRun2_relval_v10
106X_dataRun2_PromptLike_HEfail_forPR26892_v6
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_dataRun2_PromptLike_HEfail_forPR26892_v6/106X_dataRun2_PromptLike_HEfail_v6
106X_dataRun2_PromptLike_forPR26892_v7
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_dataRun2_PromptLike_forPR26892_v7/106X_dataRun2_PromptLike_v7
106X_dataRun2_PromptLike_HI_forPR26892_v7
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_dataRun2_PromptLike_HI_forPR26892_v7/106X_dataRun2_PromptLike_HI_v7
106X_mc2017_design_IdealBS_forPR26892_v4
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_mc2017_design_IdealBS_forPR26892_v4/106X_mc2017_design_IdealBS_v4
106X_mc2017_realistic_forPR26892_v3
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_mc2017_realistic_forPR26892_v3/106X_mc2017_realistic_v3
106X_upgrade2018_design_forPR26892_v3
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_upgrade2018_design_forPR26892_v3/106X_upgrade2018_design_v3
106X_upgrade2018_realistic_forPR26892_v4
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_upgrade2018_realistic_forPR26892_v4/106X_upgrade2018_realistic_v4
106X_upgrade2018_realistic_HI_forPR26892_v2
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_upgrade2018_realistic_HI_forPR26892_v2/106X_upgrade2018_realistic_HI_v2
106X_upgrade2018_realistic_HEfail_forPR26892_v4
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_upgrade2018_realistic_HEfail_forPR26892_v4/106X_upgrade2018_realistic_HEfail_v4
106X_upgrade2021_design_forPR26892_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_upgrade2021_design_forPR26892_v1/106X_upgrade2021_design_v1
106X_upgrade2021_realistic_forPR26892_v5
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_upgrade2021_realistic_forPR26892_v5/106X_upgrade2021_realistic_v5
106X_upgrade2023_realistic_forPR26892_v3
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_upgrade2023_realistic_forPR26892_v3/106X_upgrade2023_realistic_v3

#### PR validation:

Tested with PR #26892 on workflow 27434.0.

#### if this PR is a backport please specify the original PR:

This PR will need to be backported to 10_6_X.

### CODE REVIEW

**Comment by christopheralanwest** [comment]
please test with #26892

**Comment by christopheralanwest** [comment]
The latest commit is a pure renaming of GTs; see the diffs at the bottom of this comment.

This PR was designed to change only the tags needed for PR #26892. The autoCond GT currently in master for auto:phase1_2017_realistic is 106X_mc2017_realistic_v3 but a 106X_mc2017_realistic_v4 already exists. Therefore, creating a 106X_mc2017_realistic_v5 directly from 106X_mc2017_realistic_v3 + EGamma regression tags will remove the following tags:

https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_mc2017_realistic_v4/106X_mc2017_realistic_v3

This poses no problem for release validation as 106X_mc2017_realistic_v4 has never been included in autoCond. It does represent a step sideways towards our goal of finalizing the 2017 MC UL GT. I will create a separate PR including this commit that in addition includes the changes from v3 -> v4. This additional PR is not necessary for a consistent release but could be included if desired.

106X_mcRun1_design_v2
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_mcRun1_design_v2/106X_mcRun1_design_forPR26892_v1
106X_mcRun1_realistic_v2
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_mcRun1_realistic_v2/106X_mcRun1_realistic_forPR26892_v1
106X_mcRun1_HeavyIon_v2
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_mcRun1_HeavyIon_v2/106X_mcRun1_HeavyIon_forPR26892_v1
106X_mcRun1_pA_v2
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_mcRun1_pA_v2/106X_mcRun1_pA_forPR26892_v1
106X_mcRun2_startup_v3
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_mcRun2_startup_v3/106X_mcRun2_startup_forPR26892_v2
106X_mcRun2_asymptotic_l1stage1_v3
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_mcRun2_asymptotic_l1stage1_v3/106X_mcRun2_asymptotic_l1stage1_forPR26892_v2
106X_mcRun2_design_v4
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_mcRun2_design_v4/106X_mcRun2_design_forPR26892_v3
106X_mcRun2_asymptotic_v4
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_mcRun2_asymptotic_v4/106X_mcRun2_asymptotic_forPR26892_v3
106X_mcRun2_HeavyIon_v3
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_mcRun2_HeavyIon_v3/106X_mcRun2_HeavyIon_forPR26892_v2
106X_mcRun2_pA_v3
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_mcRun2_pA_v3/106X_mcRun2_pA_forPR26892_v2
106X_dataRun2_v12
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_dataRun2_v12/106X_dataRun2_forPR26892_v11
106X_dataRun2_relval_v11
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_dataRun2_relval_v11/106X_dataRun2_relval_forPR26892_v10
106X_dataRun2_PromptLike_HEfail_v7
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_dataRun2_PromptLike_HEfail_v7/106X_dataRun2_PromptLike_HEfail_forPR26892_v6
106X_dataRun2_PromptLike_v8
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_dataRun2_PromptLike_v8/106X_dataRun2_PromptLike_forPR26892_v7
106X_dataRun2_PromptLike_HI_v8
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_dataRun2_PromptLike_HI_v8/106X_dataRun2_PromptLike_HI_forPR26892_v7
106X_mc2017_design_IdealBS_v5
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_mc2017_design_IdealBS_v5/106X_mc2017_design_IdealBS_forPR26892_v4
106X_mc2017_realistic_v5
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_mc2017_realistic_v5/106X_mc2017_realistic_forPR26892_v3
106X_upgrade2018_design_v4
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_upgrade2018_design_v4/106X_upgrade2018_design_forPR26892_v3
106X_upgrade2018_realistic_v5
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_upgrade2018_realistic_v5/106X_upgrade2018_realistic_forPR26892_v4
106X_upgrade2018_realistic_HI_v3
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_upgrade2018_realistic_HI_v3/106X_upgrade2018_realistic_HI_forPR26892_v2
106X_upgrade2018_realistic_HEfail_v5
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_upgrade2018_realistic_HEfail_v5/106X_upgrade2018_realistic_HEfail_forPR26892_v4
106X_upgrade2021_design_v2
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_upgrade2021_design_v2/106X_upgrade2021_design_forPR26892_v1
106X_upgrade2021_realistic_v6
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_upgrade2021_realistic_v6/106X_upgrade2021_realistic_forPR26892_v5
106X_upgrade2023_realistic_forPR26892_v3
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_upgrade2023_realistic_v4/106X_upgrade2023_realistic_forPR26892_v3

**Comment by christopheralanwest** [comment]
please test with #26892

**Comment by slava77** [comment]
it looks like the 2017 MC GT was not updated correctly
https://cms-conddb-prod.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_mc2017_realistic_v3/106X_mc2017_realistic_v4

**Comment by christopheralanwest** [comment]
Indeed, as explained in my previous message, the correct GT is 106X_mc2017_realistic_v5:

https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_mc2017_realistic_v5/106X_mc2017_realistic_forPR26892_v3

**Comment by christopheralanwest** [comment]
please test with #26892

**Comment by christopheralanwest** [comment]
The latest commit:

- Keeps the GTs from the 106X_mc2017_design and 106X_mc2017_realistic queues unchanged
- Reverts the mistaken changes to the tags beginning with "pfscecal" and "ecalPFClusterCor2017V2" in GTs from all queues except those for 2017 MC (106X_mc2017_design and 106X_mc2017_realistic) 
- In GTs corresponding to 106X data queues (106X_dataRun2_2017_2018, 106X_dataRun2_relval, 106X_dataRun2_PromptLike_HEfail, 106X_dataRun2_PromptLike and 106X_dataRun2_PromptLike_HI) replaces the 2017 data tags beginning with "pfscecal" and "ecalPFClusterCor2017V2" with an IOV-independent tag with the same payload as the corresponding 2017 MC. The payload has been requested to be made IOV-independent because the code will be changed to only use the new regression in 2017.
- For the new tags with names beginning with "electron" and "photon" in the 106X data queues, uses the same payloads (there is a technical change to allow for different synchronization requirements for the data and MC queues; the new tags have the postfix "_offline_v1")

I will let the currently running PR tests complete before triggering new tests, as the differences between the comparison tests before and after this GT update may be of interest.

Diffs of the new GTs with respect to the current autoCond GTs are given below.

https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_mcRun1_design_v3/106X_mcRun1_design_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_mcRun1_realistic_v3/106X_mcRun1_realistic_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_mcRun1_HeavyIon_v3/106X_mcRun1_HeavyIon_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_mcRun1_pA_v3/106X_mcRun1_pA_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_mcRun2_startup_v4/106X_mcRun2_startup_v2
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_mcRun2_asymptotic_l1stage1_v4/106X_mcRun2_asymptotic_l1stage1_v2
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_mcRun2_design_v5/106X_mcRun2_design_v3
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_mcRun2_asymptotic_v5/106X_mcRun2_asymptotic_v3
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_mcRun2_HeavyIon_v4/106X_mcRun2_HeavyIon_v2
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_mcRun2_pA_v4/106X_mcRun2_pA_v2

https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_dataRun2_v13/106X_dataRun2_v11
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_dataRun2_relval_v12/106X_dataRun2_relval_v10
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_dataRun2_PromptLike_HEfail_v8/106X_dataRun2_PromptLike_HEfail_v6
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_dataRun2_PromptLike_v9/106X_dataRun2_PromptLike_v7
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_dataRun2_PromptLike_HI_v9/106X_dataRun2_PromptLike_HI_v7

https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_upgrade2018_design_v5/106X_upgrade2018_design_v3
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_upgrade2018_realistic_v6/106X_upgrade2018_realistic_v4
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_upgrade2018_realistic_HEfail_v6/106X_upgrade2018_realistic_HEfail_v4
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_upgrade2021_design_v3/106X_upgrade2021_design_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_upgrade2021_realistic_v7/106X_upgrade2021_realistic_v5
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_upgrade2023_realistic_v5/106X_upgrade2023_realistic_v3

**Comment by christopheralanwest** [comment]
please test with #26892

The previous round of tests was triggered just before the last commit to this PR

**Comment by slava77** [comment]
@cmsbuild please test

to check how this works by itself.
IIUC, the old egamma payloads are still available and this PR can be merged by itself.

**Comment by slava77** [comment]
From https://github.com/cms-sw/cmssw/pull/27089#issuecomment-500050600 corresponding to the tests done with this PR alone 
> DQMHistoTests: Total failures: 1689

it looks like I was wrong about full compatibility of the new payloads with the code in CMSSW baseline.

Looking at one case with a diff in 2018:
https://cms-conddb-prod.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_upgrade2018_realistic_HI_v2/106X_upgrade2018_realistic_HI_v3
- e.g. for GBRDWrapperRcd label pfscecal_EBCorrection_offline_v2 the tag changed from pfscecal_EBCorrection_offline_v2 to pfscecal_EBCorrection_offline_v2_2017UL

While in the pp 2018 MC there is no change in results and the GT diff https://cms-conddb-prod.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_upgrade2018_realistic_v4/106X_upgrade2018_realistic_v6 shows no differences in the SC payloads:
- e.g. for the same GBRDWrapperRcd label pfscecal_EBCorrection_offline_v2 the same pfscecal_EBCorrection_offline_v2 tag is present in both GTs

@christopheralanwest is this expected?

**Comment by slava77** [comment]
@Sam-Harper 
please take a look at 
https://github.com/cms-sw/cmssw/pull/27089#issuecomment-500064319

Additionally, I'd like to understand the recent discussion about deploying calibrations for different years. The recent era-based reorganization in #26892 was done assuming only 2017 gets consistently updated because only for 2017 there is a consistent set of GTs.
I notice that the data GT EGamma GBR payloads have only one IOV. Is there a plan to add per-year IOVs?

**Comment by christopheralanwest** [comment]
> 
> Looking at one case with a diff in 2018:
> https://cms-conddb-prod.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_upgrade2018_realistic_HI_v2/106X_upgrade2018_realistic_HI_v3
> 
>     * e.g. for GBRDWrapperRcd label pfscecal_EBCorrection_offline_v2 the tag changed from pfscecal_EBCorrection_offline_v2 to pfscecal_EBCorrection_offline_v2_2017UL
> 
> 
> @christopheralanwest is this expected?

No. Except for the 2017 scenarios the changes to the tags starting with "ecalPF" and "pfscecal" was not desired. The second-to-last commit (3256cf62650908f84d4174daaea8e84d5a616b57) undid the changes to these tags, but the updated GT for the 106X_upgrade2018_realistic_HI queue was inadvertently left out of the autoCond update.

**Comment by christopheralanwest** [comment]
please test with #26892

**Comment by Sam-Harper** [comment]
> @Sam-Harper
> please take a look at
> [#27089 (comment)](https://github.com/cms-sw/cmssw/pull/27089#issuecomment-500064319)
> 
> Additionally, I'd like to understand the recent discussion about deploying calibrations for different years. The recent era-based reorganization in #26892 was done assuming only 2017 gets consistently updated because only for 2017 there is a consistent set of GTs.
> I notice that the data GT EGamma GBR payloads have only one IOV. Is there a plan to add per-year IOVs?

So our end goal is this:

1) a single data GT which does 2016, 2017, 2018. 
2) separate MC tags for 2016, 2017, 2018

I have to admit, I wasnt aware of the the single data GT originally but fine, its merely a technical detail.

Now this simple picture is rather complicated by the fact that 2016, 2018 does not exist right now. And also you cant pre-prend iovs so at somepoint we'll need a new GT for data.  

This plan was agreed in PPD coordination. Get the conditions ready for 2017, get that running and then get 2018, then 2016, there being little point in waiting another month to start 2017. 

At this point, none of this is specific to e/gamma, and hopefully should not be news to anybody. 

Now on to E/gamma. For the PF cluster and mustache SC, they can share the same code so they are simply  a conditions update. There was some confusion and they were orignally applied for all tags. But that should be reverted now. They should be no different to any other conditions prep for 2017. 

Now we get to the electron/photon regressions. These are not backwards compatible changes. This was made even more tedious by oversights in the original conf format which is just the payload of the GBRForest but the meta data needed to interpret it, such as the response range and the variables used.

Therefore we are in the lovely situation where the payload is controlled by the GT but the meta data is in the release. This normally wouldn't be a huge issue except for the fact in this unique situation we're sending out the release before finishing the conditions.  

In time, new conditions will be deployed for 2016, 2018 which will mean updating the release at that point in time as well. Its not as if the conditions they currently get are in any way right or correct btw. 2016/2018 are currently in an intermediate undefined and non-physics quality state. This is simply unavoidable and is a chicken and egg scenario (which I want to see if we can do something about in the future). 

Also in time, I'll probably update the default conditions as well to the new ele/pho regressions. Its not as if the regression RunI or HION currently gets is in anyway tuned to it, however it should probably have the conditions matched to its PF rec-hit thresholds which as far as I can tell is the  2018 PF rec-hit thresholds tuned on an overly pessimistic  ecal noise model.

**Comment by christopheralanwest** [comment]
+1

The sole purpose of this PR is to support PR #26892. Given the reco signature for that PR, I am signing off here.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
