### PR TITLE
HLT menu development for `13_0_X` (4/N)

### PR DESCRIPTION
**Pull request by missirol**
backport of #41016

#### PR description:

Development of HLT menus for `CMSSW_13_0_X`.

This PR includes the integration of the JIRA tickets in [1], and has the following implications.

 - The GRun menu in this PR is compatible with the L1T menu [`L1Menu_Collisions2023_v1_0_0`](https://htmlpreview.github.io/?https://github.com/cms-l1-dpg/L1MenuRun3/blob/57fcce7ecf26366084813755f769f47be58bbf5f/development/L1Menu_Collisions2023_v1_0_0/L1Menu_Collisions2023_v1_0_0.html) [[tag]](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/tags/L1Menu_Collisions2023_v1_0_0_xml) (see [CMSLITDPG-1102](https://its.cern.ch/jira/browse/CMSLITDPG-1102)).

 - This 2023 L1T menu will be included by AlCa in the 2023/24 MC and Run-3 'data relval' GTs (https://github.com/cms-sw/cmssw/pull/41007), while the 2022 MC GTs continue to use the last L1T menu of 2022. To comply with this, the alias `(HLT:)@relval2023` is introduced to run the GRun menu in the 2023/24 MC and Run-3 data RelVals. To pick up the appropriate HLT menu in all relevant wfs, changes in `Configuration/PyReleaseValidation` were needed.

[1]
  - [CMSHLT-2678](https://its.cern.ch/jira/browse/CMSHLT-2678): [HCAL] removed `L1_SingleMuOpen` seed from `HLT_HcalPhiSym_v` trigger
  - [CMSHLT-2687](https://its.cern.ch/jira/browse/CMSHLT-2687): [BPH] update of `Tau3Mu` triggers (2023 L1T seeds)
  - [CMSHLT-2688](https://its.cern.ch/jira/browse/CMSHLT-2688): [BPH] removed `L1_DoubleMu3er2p0_SQ_OS_dR_Max1p4` seed from BPH dimuon triggers
  - [CMSHLT-2689](https://its.cern.ch/jira/browse/CMSHLT-2689): [JME] use L1T-Jet-FWD2p5 seeds in `PFJetFwd` and `DiPFJetAve` triggers (2023 L1T seeds)
  - [CMSHLT-2690](https://its.cern.ch/jira/browse/CMSHLT-2690): [BTV] update of `BTagMu*DiJet` triggers (2023 L1T seeds)
  - [CMSHLT-2699](https://its.cern.ch/jira/browse/CMSHLT-2699): [HIG] added backup L1T VBFDiJetIsoTau seed (2023 L1T seed)

#### PR validation:

TSG tests.

#### If this PR is a backport, please specify the original PR and why you need to backport that PR. If this PR will be backported, please specify to which release cycle the backport is meant for:

#41016

Development of HLT menus for 2023 data-taking and Run-3 MC.

### CODE REVIEW

**Comment by missirol** [comment]
test parameters:
  - pull_requests = #41007
  - workflows = 139.004,140.003,140.023,140.043,140.063,12634.0,12634.99,12834.0,13034.0,13034.99
  - enable = gpu

**Comment by missirol** [comment]
The 'test parameters' above is tentative (and hopefully valid). If somebody has additional wfs in mind to test this PR, feel free to add them.

FYI: @cms-sw/alca-l2

**Comment by tvami** [comment]
looks reasonable to me! thanks @missirol

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by missirol** [comment]
+hlt

 - The changes in the outputs of PR tests are in line with the updates to the HLT menus used in 20(22|23|24) MC RelVals and Run-3 data RelVals.

**Comment by srimanob** [comment]
+Upgrade

**Comment by kskovpen** [comment]
+pdmv

**Comment by missirol** [comment]
No issues seen in `CMSSW_13_1_X_2023-03-10-2300` in relation to the parent PR of this backport.

Reminder: this PR and #41007 need to be integrated in the same IB.

**Comment by missirol** [comment]
> No issues seen in `CMSSW_13_1_X_2023-03-10-2300` in relation to the parent PR of this backport.
> 
> Reminder: this PR and #41007 need to be integrated in the same IB.

@cms-sw/orp-l2 , kind ping to review this backport PR (and #41007).

**Pull request merged**
