### PR TITLE
skims: definition, matrix, configBuilder - retry

### PR DESCRIPTION
**Pull request by franzoni**
update of #9970 (closed now), forward port of #9897 

++ SUMMARY
Validation and rate measuremetns on the skim producers were carried out by Alexis @alkaloge based on 7_5_0_preX

++ DETAILS
- skims DEFINITIONS of 75
- fw port of 9897; superseeds 9868 which can be closed
- rationalization of the skim matrix, intended to pass to T0 the PD => "skims to run" correspondence, in light of 2015 PD's , see https://hypernews.cern.ch/HyperNews/CMS/get/physics-announcements/3385.html
- collection of skims requirements by DPG/POG/PAGs : https://docs.google.com/spreadsheets/d/1OicL4b3jFUXalsk92GM9qLbNNAVklAGb7bf1T5BwZrY/edit#gid=0
- configBuilder modified to preserve output modules set by --eventcontent when SKIM is in the sequence

### CODE REVIEW

**Comment by alkaloge** [comment]
@franzoni We have a new request for skim - @emanueledimarco requested the last one here https://docs.google.com/spreadsheets/d/1OicL4b3jFUXalsk92GM9qLbNNAVklAGb7bf1T5BwZrY/edit#gid=0 to be running on Commissioning PD - Do we have time to include in this PR and backport it to 74x as well ? Of course, the matrix has to be modified as well

**Comment by franzoni** [comment]
@alkaloge 
Jack is working on that aspect. We'll intregrate when ready.
Thanks.

**Comment by franzoni** [comment]
please test

**Comment by franzoni** [comment]
+1

local tests including ALCA and all skims run fine over 5 events
The issue encountered with unscheduled https://hypernews.cern.ch/HyperNews/CMS/get/swDevelopment/3229.html (which also describes the local tests)  being addressed

**Comment by davidlange6** [comment]
+1

**Pull request merged**
