### PR TITLE
Dependency cleanup for big simulation plugin

### PR DESCRIPTION
**Pull request by smuzaffar**
This PR proposes to 
- If cuda is not available for cmssw then
  - `CondFormats/EcalObjects CondFormats/HcalObjects`: Do not build `*GPU.cc`
  - `CondFormats/HGCalObjects: Do not build `HeterogeneousHGCalHEFCellPositionsConditions.cc`
- Remove used `geant4core` dependency from `Validation/HGCalValidation`
- Drop  `Validation/HGCalValidation` (which now does not depend on `geant4`) from `Simulation` big plugin

These changes should allow to build buig Simulation plugin for Riscv 64

### CODE REVIEW

**Comment by smuzaffar** [comment]
Please test

**Comment by civanch** [comment]
@bsunanda , FYI , for me this PR is fine.

**Comment by srimanob** [comment]
+Upgrade

**Comment by makortel** [comment]
+core

**Comment by smuzaffar** [comment]
@cms-sw/alca-l2 @cms-sw/db-l2 can you please review this change? This change practically do not change any thing. It only avoids compilation of `*GPU.cc` files is cuda is not available ( e.g. on riscv64 arch).

@cms-sw/dqm-l2 , this Pr only removed the unused `geant4` dependency from `Validation/HGCalValidation`

**Comment by perrotta** [comment]
+1

**Comment by smuzaffar** [comment]
@cms-sw/dqm-l2 , can you please review this? for DQM the change is really trivial i.e. remove unnecessary geant4 dependency

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
