### PR TITLE
DD4hep: Allow References in a Vector

### PR DESCRIPTION
**Pull request by ianna**
#### PR description:

* Vector can contain references. Check if it's a reference and strip the square brackets before passing a string to an evaluator.

#### if this PR is a backport please specify the original PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by fabiocos** [comment]
DQM differences look clearly unrelated to this PR. @ianna the change looks simple, I understand you have tested it in a standalone way

**Comment by fabiocos** [comment]
+1

**Pull request merged**
