### PR TITLE
Add GEM recHits and segments to AlCaRecos

### PR DESCRIPTION
**Pull request by hyunyong**
#### PR description:

Add GEM recHits and segments in ALCARECOMuAlCalIsolatedMu, ALCARECOMuAlGlobalCosmics, and ALCARECOMuAlGlobalCosmicsInCollisions.

Need to backport to 12_4_X.

### CODE REVIEW

**Comment by tvami** [comment]
test parameters:
 * workflows = 1001.3,1002.3

**Comment by tvami** [comment]
@hyunyong you dont have the numbers on the size increase, do you?

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
Please also modify the PR title

**Comment by hyunyong** [comment]
> @hyunyong you dont have the numbers on the size increase, do you?

No, I don't know but I will ask it at the GEM DPG meeting tomorrow.

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by hyunyong** [comment]
I have checked the output and the MuAlCalIsolated skim contains GEM recHits and segments now.

**Comment by hyunyong** [comment]
> That's great, can we please have a the numbers for the increase of size before merging the PR?

Yes, I processed 1,000 events and the size difference is 77894 bytes. So, average size of GEM recHits and segments is 78 bytes/event.

**Comment by tvami** [comment]
So I believe that's a 2% increase, for an ALCARECO, that's probably fine. Ok, I'll sign it now, and please prepare the backport

**Comment by tvami** [comment]
+alca
 * tests pass and produce the ALCARECO, which now contains the new collections
 * size increase is acceptable

**Comment by hyunyong** [comment]
> So I believe that's a 2% increase, for an ALCARECO, that's probably fine. Ok, I'll sign it now, and please prepare the backport

Yes, I made the backport https://github.com/cms-sw/cmssw/pull/38876

**Comment by qliphy** [comment]
+1

**Pull request merged**
