### PR TITLE
Extending E/gamma HLT Debug to phaseII and adding rec-hit counts: 11_3_X

### PR DESCRIPTION
**Pull request by Sam-Harper**
#### PR description:

This PR adds the phase-II HLT E/gamma debug producer by introducing a new class EgammaHLTPhaseIIExtraProducer which handles the Phase-II specific things such as HGCAL and L1 tracks so it doesnt have to be exposed to the standard EgammaHLTExtraProducer. 

It also introduces a new track trigger dataformat, L1TrackExtra which so far allows tracking of the refererences to the L1Track and its tracking particle. In this format it is significantly easier to use, particularly in fwlite.  The name could probably be better and I'm happy to rename it to anything else. L1TrackTruthPair for example. 

It also adds the rec-hit counts to the e/gamma HLT debug format as these are used in the regressions and thus need to be stored. 

Once https://github.com/cms-sw/cmssw/pull/32910 is merged, then I'll submit the 11_1_X flavour

#### PR validation:

Used extensively for E/g HLT phase-II development. Test shows this produces the expected output

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by silviodonato** [comment]
The error is not related to this PR
```
----- Begin Fatal Exception 15-Feb-2021 13:15:41 CET-----------------------
An exception of category 'FileOpenError' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing input source of type PoolSource
   [2] Calling RootInputFileSequence::initTheFile()
   [3] Calling StorageFactory::open()
   [4] Calling XrdFile::open()
Exception Message:
Failed to open the file 'root://cms-xrd-global.cern.ch//store/data/Run2012D/SingleMu/RAW-RECO/ZMu-15Apr2014-v1/00000/007A3BD1-02CD-E311-853B-002590D0AFC8.root'
   Additional Info:
      [a] Calling RootInputFileSequence::initTheFile(): fail to open the file with name root://eoscms.cern.ch//eos/cms/store/user/cmsbuild/store/data/Run2012D/SingleMu/RAW-RECO/ZMu-15Apr2014-v1/00000/007A3BD1-02CD-E311-853B-002590D0AFC8.root
      [b] Input file root://cms-xrd-global.cern.ch//store/data/Run2012D/SingleMu/RAW-RECO/ZMu-15Apr2014-v1/00000/007A3BD1-02CD-E311-853B-002590D0AFC8.root could not be opened.
      [c] XrdCl::File::Open(name='root://cms-xrd-global.cern.ch//store/data/Run2012D/SingleMu/RAW-RECO/ZMu-15Apr2014-v1/00000/007A3BD1-02CD-E311-853B-002590D0AFC8.root', flags=0x10, permissions=0660) => error '[ERROR] Server responded with an error: [3011] No servers are available to read the file.�
' (errno=3011, code=400). No additional data servers were found.
      [d] Last URL tried: root://cms-xrd-global.cern.ch:1094//store/data/Run2012D/SingleMu/RAW-RECO/ZMu-15Apr2014-v1/00000/007A3BD1-02CD-E311-853B-002590D0AFC8.root?tried=&xrdcl.requuid=6bf4650c-fe39-4d9b-b4d0-51868268f097
      [e] Problematic data server: cms-xrd-global.cern.ch:1094
      [f] Disabled source: cms-xrd-global.cern.ch:1094
----- End Fatal Exception -------------------------------------------------
```

**Comment by Martin-Grunewald** [comment]
+1

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Sam-Harper** [comment]
@rekovic , a ping on this. It would be good to move forward and it's been waiting for a week with no comment.

**Comment by Sam-Harper** [comment]
I changed my mind on the name, this is more L1TrackTruthPair is more approprate

**Comment by rekovic** [comment]
Two thumbs up fo `TTrackTruthPair`. Thanks @Sam-Harper.

**Comment by rekovic** [comment]
+1

**Comment by Martin-Grunewald** [comment]
+1

**Comment by Sam-Harper** [comment]
@cms-sw/upgrade-l2, please can you review asap

**Comment by srimanob** [comment]
+Upgrade

The original commit came with the name L1TrackExtra which made confusion a bit with what produced in L1Reco step (which is considered to be obsolete). The new name, L1TrackTruthPair, is better in my idea. However, I think if we would like to have additional L1 objects with extra information produced in the HLT step, we may need to define the naming scheme.

**Comment by silviodonato** [comment]
+1

**Pull request merged**
