### PR TITLE
Adding Run 334393 as test Run for LS2

### PR DESCRIPTION
**Pull request by boudoul**
#### PR description:

Updating RunTheMatrix in order to use  Run 334393 taken in January 2020 as test Run for LS2 

#### PR validation:

runTheMatrix.py -l 138.1 --command "-n 100"  is running fine

### CODE REVIEW

**Comment by kpedro88** [comment]
please test workflow 138.1

**Comment by chayanit** [comment]
+1

**Comment by silviodonato** [comment]
urgent

**Comment by silviodonato** [comment]
Kind reminder @kpedro88

**Comment by kpedro88** [comment]
+upgrade

**Comment by silviodonato** [comment]
+1

**Pull request merged**
