### PR TITLE
update input dataset and fix step

### PR DESCRIPTION
**Pull request by vlimant**
#### PR description:

master version of #40184

### CODE REVIEW

**Comment by vlimant** [comment]
please test

**Comment by AdrianoDee** [comment]
+upgrade

**Comment by AdrianoDee** [comment]
please abort
(at the moment the IB is broken see #40206)

**Comment by AdrianoDee** [comment]
test parameters:
- pull_request = https://github.com/cms-sw/cmssw/pull/40206

**Comment by vlimant** [comment]
@cms-sw/pdmv-l2  please sign this in master

**Comment by kskovpen** [comment]
+pdmv

**Comment by perrotta** [comment]
+1
- Bacport PR  #40184 already merged, let merge it also in master

**Pull request merged**
