### PR TITLE
GEM online DQM bug fix - full GE1/1, backport to 11_1_X

### PR DESCRIPTION
**Pull request by quark2**
#### PR description:
This PR fixes a bug on the part of onlineDQM for GEM. The era is not specified on the run script for GEM onlineDQM, which caused a crash on the GEM onlineDQM in the MWGR #3 (especially run 337234, run 337235). This is a backport version of https://github.com/cms-sw/cmssw/pull/31390.

Also, there is a minor change of some status plots; to display bins for good status.

#### PR validation:
Test are done and one can check again by `runTheMatrix` workflows

@jshlee @watson-ij @hyunyong

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by silviodonato** [comment]
backport of #31390

**Comment by silviodonato** [comment]
@cms-sw/dqm-l2 I think we can merge this backport

**Comment by boudoul** [comment]
Hello @silviodonato @kmaeshima, @andrius-k, @jfernan2, @fioriNTU  : maybe having the results of a DQM playback performed on the run taken at P5 which was crashing would help to underatnd whether this PR is good to be merged ?

**Comment by jfernan2** [comment]
Yes, this is what we are still testing in Online DQM with run 337234, but we get a strange crash, trying to debug...

**Comment by boudoul** [comment]
ok thanks @jfernan2. Do not hesitate to share the log of the crash , it usually helps to understand it when more eyes are watching thanks.

**Comment by jfernan2** [comment]
The error is quite similar to this just reported by @mrodozov  here:
https://github.com/cms-sw/cmssw/pull/30686#issuecomment-693002938
A simple exit with error code -11 when switching the input file ... :-(

**Comment by jfernan2** [comment]
Hi, 
@andrius-k found the source of the crash/problem at Online DQM, which actually is not related to the changes introduced in this PR but incidentally this PR make this problem patent at Online DQM:
a file touched by this PR, GEMDQMStatusDigi.cc has MEs which are too large in memory size.

This ME has more than 60k bins: https://github.com/cms-sw/cmssw/blob/977130e0ea138f56b2ff99da1e0425830e41acf2/DQM/GEM/plugins/GEMDQMStatusDigi.cc#L540     -> 10MB uncompressed
And this other more than 3k bins: https://github.com/cms-sw/cmssw/blob/977130e0ea138f56b2ff99da1e0425830e41acf2/DQM/GEM/plugins/GEMDQMStatusDigi.cc#L536     -> 5MB uncompressed

@quark2 can you fix this in this same PR? Or in the contrary, can you justify on this Friday DQM General meeting presentation the need for such a large binninng instead? 

Same problem is in master branch since https://github.com/cms-sw/cmssw/pull/31390 was merged with the same bining version of the MEs.

**Comment by quark2** [comment]
Hi @jfernan2, 

I think it's because of some special histograms which is used in the monitoring system for GEM QC8. It was useful in the monitoring system so I thought it would be good to remain them for the central DQM, but now I found it doesn't. I'll remove them and push it soon, and explain about this tomorrow.

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
please test
Crash looks unrelated....

**Comment by quark2** [comment]
Hi @jfernan2, 

FYI, according to [1], the test run cannot read some source files, and even we cannot access to the files everywhere (e.g., [2]).

[1] https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-e79b6c/9454/addOnTests/logs/cmsDriver-pat1_cmsRun__cvmfs_cms-ib.cern.ch_week1_slc7_amd64_gcc820_cms_cmssw-patch_CMSSW_11_1_X_2020-09-21-1100_src_PhysicsTools_PatAlgos_test_IntegrationTest_cfg.p.log
[2] root://cms-xrd-global.cern.ch//store/data/Run2018D/HIMinimumBias0/RAW/v1/000/325/112/00000/660F62BB-9932-D645-A4A4-0BBBDA3963E8.root

**Comment by jfernan2** [comment]
@quark2 can you propagate the last changes/commit (removed plots) to master branch please?

**Comment by jfernan2** [comment]
please test
Last trial to have UnitTests

**Comment by quark2** [comment]
Hi @jfernan2, 

Yep sure, I'll make it soon.

**Comment by jfernan2** [comment]
+1
Tested also sucessfully at Online DQM playback

**Comment by qliphy** [comment]
+1

**Pull request merged**
