### PR TITLE
[CPP20][ALCA, DB] Remove deprecated enum arithmetic

### PR DESCRIPTION
**Pull request by iarspider**
#### PR description:

Some arithmetic and logic operations on `enum`s are deprecated in C++20. This PR aims to fix these.

#### PR validation:

Bot tests

### CODE REVIEW

**Comment by iarspider** [comment]
please test for CMSSW_14_1_CPP20_X

**Comment by perrotta** [comment]
There are other such cases, e.g.:
- https://github.com/cms-sw/cmssw/blob/2716a9c4ef76006ed671283dad4a9c4caf7253e3/Alignment/Geners/interface/GenericIO.hh#L315
- https://github.com/cms-sw/cmssw/blob/2716a9c4ef76006ed671283dad4a9c4caf7253e3/Alignment/Geners/interface/GenericIO.hh#L337
- https://github.com/cms-sw/cmssw/blob/2716a9c4ef76006ed671283dad4a9c4caf7253e3/Alignment/Geners/interface/GenericIO.hh#L406
- https://github.com/cms-sw/cmssw/blob/2716a9c4ef76006ed671283dad4a9c4caf7253e3/Alignment/Geners/interface/GenericIO.hh#L417
- https://github.com/cms-sw/cmssw/blob/2716a9c4ef76006ed671283dad4a9c4caf7253e3/Alignment/Geners/interface/GenericIO.hh#L612-L613
- https://github.com/cms-sw/cmssw/blob/2716a9c4ef76006ed671283dad4a9c4caf7253e3/Alignment/Geners/interface/ProcessItem.hh#L338-L339
- https://github.com/cms-sw/cmssw/blob/2716a9c4ef76006ed671283dad4a9c4caf7253e3/CalibFormats/SiStripObjects/interface/SiStripRegionCabling.h#L165
- https://github.com/cms-sw/cmssw/blob/2716a9c4ef76006ed671283dad4a9c4caf7253e3/CalibFormats/SiStripObjects/interface/SiStripRegionCabling.h#L168
- (etc.)

**Comment by iarspider** [comment]
@perrotta thanks, I have somehow missed these.

**Comment by iarspider** [comment]
please test for CMSSW_14_1_CPP20_X

**Comment by perrotta** [comment]
Also here, I think that constexpr would suit better, as suggested by Matti in https://github.com/cms-sw/cmssw/pull/44488#issuecomment-2010078785
At least, the could would look nicer reading...
@iarspider please let us know if you intend to pursue that route here

**Pull request closed without merging**
