### PR TITLE
Edm pick events crab3 updates from cmssw 7 4 0

### PR DESCRIPTION
**Pull request by ramankhurana**
We added the functionality so that edmPickEvents work with CRAB3 and interactively for > 20 Events.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
Please also make pull requests to 7_5 and 7_6.

**Comment by Dr15Jones** [comment]
Please test

**Comment by monttj** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
