### PR TITLE
Added check to ensure simhit collection in pixel rechit validation exists

### PR DESCRIPTION
**Pull request by davidcarbonis**
Following the issue raised in the PR thread introducing the validation code for the phase 1 pixel detector (https://github.com/cms-sw/cmssw/pull/19403#issuecomment-316188809), this commit introduces a simple check to ensure that the simhit associated with the rechit being analysed actually exists and so fixes the segmentation fault observed in the comment above.

The only change is the introduction of an if statement in the relevant place in the relevant analyser module,i `if ( !associateSimHit.empty() )`.

@Dr15Jones you might be interested in this.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
Thanks for the quick fix.

**Comment by Dr15Jones** [comment]
please test

**Comment by davidlange6** [comment]
merge

**Comment by slava77** [comment]
It looks like either this PR or its earlier version already introduce random differences in "PixelPhase1V/Run summary/TrackingParticle"
Tests of PRs with unrelated changes show differences in this folder
e.g. 
- in #19813 in wf 10824 https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_9_3_X_2017-07-19-1100+19813/21447/10824.0_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2018_GenSimFull+DigiFull_2018+RecoFull_2018+ALCAFull_2018+HARVESTFull_2018/PixelPhase1V_TrackingParticle.html 
- in #19672 in wf 10824 https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_9_3_X_2017-07-19-2300+19672/21451/10824.0_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2018_GenSimFull+DigiFull_2018+RecoFull_2018+ALCAFull_2018+HARVESTFull_2018/PixelPhase1V_TrackingParticle.html

**Comment by davidcarbonis** [comment]
@slava77 Will look into ASAP

**Comment by kpedro88** [comment]
@davidcarbonis I noticed a segfault in `SiPixelPhase1HitsV` when trying to test a new Run3 workflow; I think it is related to these issues. Here is the segfault:
```
#5  0x00007fcb91840ddd in reco::TrackToTrackingParticleAssociator::associateRecoToSim (tPCH=..., tCH=..., this=0x7fcbad493f78) at /cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc630/cms/cmssw-patch/CMSSW_9_3_X_2017-07-24-1100/src/SimDataFormats/Associations/interface/TrackToTrackingParticleAssociator.h:65
#6  SiPixelPhase1HitsV::analyze (this=0x7fcbad493c80, iEvent=..., iSetup=...) at /uscms_data/d3/pedrok/phase2/run3/v4/CMSSW_9_3_X_2017-07-24-1100/src/Validation/SiPixelPhase1HitsV/src/SiPixelPhase1HitsV.cc:233
```
and what I learned from gdb:
```
(gdb) frame 0
#0  0x00007fffacc5cddd in reco::TrackToTrackingParticleAssociator::associateRecoToSim (tPCH=..., tCH=..., this=0x7fffc88e7f78)
    at /cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc630/cms/cmssw-patch/CMSSW_9_3_X_2017-07-24-1100/src/SimDataFormats/Associations/interface/TrackToTrackingParticleAssociator.h:65
65            return m_impl->associateRecoToSim(tCH,tPCH);
(gdb) print m_impl
$1 = (reco::TrackToTrackingParticleAssociatorBaseImpl *) 0x300000002
(gdb) print *m_impl
Cannot access memory at address 0x300000002
```

So it looks like `m_impl` is somehow uninitialized. I'm not sure how to trace back further where it comes from originally, but this needs to be fixed.

**Comment by davidcarbonis** [comment]
@kpedro88 Looking into it asap!

**Comment by kpedro88** [comment]
@davidcarbonis see the newly-submitted #19889; to run the workflow:
```
runTheMatrix.py -l 11624.0
```

**Comment by kpedro88** [comment]
(best to use the latest 93X IB)

**Comment by kpedro88** [comment]
@davidcarbonis any progress?

**Comment by davidcarbonis** [comment]
@kpedro88 Not too much yet - I've been away at a conference since Tuesday. I have a few ideas as to the cause which I'm currently testing.

**Comment by davidcarbonis** [comment]
It appears that the _associatorByHits_ is not initialised when running the Run 3 workflow - thus causing the memory leak you saw ...
I will be committing a change shortly which checks that the _associatorByHits_ does exist, and if not, throws an exception and error message, safely terminating the program rather than experiencing a memory leak.

**Comment by kpedro88** [comment]
@davidcarbonis should some module be added to a sequence for Run3 so the `associatorByHits` does get initialized? Otherwise the workflow still won't run...

**Comment by davidcarbonis** [comment]
Yes, some module does need to be added to a sequence for Run3 so the associatorByHits does get initialised in Run3. Is this something you can do given that you are looking after Run 3, whose workflows are altering the _current_ setup?

**Comment by kpedro88** [comment]
@davidcarbonis please tell me what module to add and I'll update the Run3 PR

**Comment by kpedro88** [comment]
Figured it out - the `trackAssociatorByHits` comes into play in the [muon validation sequence](https://github.com/cms-sw/cmssw/blob/master/Validation/RecoMuon/python/muonValidation_cff.py), but that sequence had been reduced for Phase2, and the reduction got put in Run3 also. (You may want to think about the organization, if tracking validation also depends on this module now.)

**Comment by davidcarbonis** [comment]
I hadn't considered looking in Phase 2 - I was trying to find where it was reduced for Run 3, but it seems you found it before me. Thanks for looking - it is much appreciated!

I shall raise this in my meeting with a tracking validation expert tomorrow morning over our chat re. a PR with several commits that will be opened tomorrow. Naturally I'll copy you into the PR comments so you are kept informed.

**Pull request merged**
