### PR TITLE
Improvements to stall-monitoring service and script.

### PR DESCRIPTION
**Pull request by knoepfel**
Script now takes advantage of information emitted at the `preSourceEvent` and `postSourceEvent` signals.  In addition the script is significantly faster for creating the PDF image, and it also includes capabilities for creating a stack plot.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by knoepfel** [comment]
Most recent improvements include:

- Checking that the supplied extension for pdf file is supported.
- Improving the ordering of colors in the stacked plot.
- Clearer y-axis labels.

The accounting error I thought I had encountered before no longer seems to be present.  I will adjust the script if it arises again.

**Comment by Dr15Jones** [comment]
Please test

**Comment by Dr15Jones** [comment]
please test

**Comment by knoepfel** [comment]
Assuming the tests pass, this PR is complete.

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
