### PR TITLE
bsunanda:Run2-hcx66 Changes to Simulation for 2016++ scenario

### PR DESCRIPTION
**Pull request by bsunanda**
Some fixes to HcalTopology and HcalDDDRecConstants
Fix Full and Fast Sim for multianode readout of HF

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@civanch @ianna @mdhildreth @ssekmen Could you kindly look into the changes and approve this. We would like to have this in 8_0_0 release

**Comment by bsunanda** [comment]
@cmsbuild Please test
@civanch @ianna @mdhildreth @ssekmen Sorry I asked prematuredly. Could you kindly look into the changes and approve this. We would like to have this in 8_0_0 release

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@civanch @ianna @mdhildreth @ssekmen We would like to have this in 8_0_0 release and approved by tomorrow. Could you kindly to review this and have it approved

**Comment by lveldere** [comment]
+1

thanks Sunanda

**Comment by ianna** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
