### PR TITLE
EGamma Scale & Smearing For Re-miniAOD (No ReducedEG changes)

### PR DESCRIPTION
**Pull request by Sam-Harper**
Dear All,

This is an identical PR to https://github.com/cms-sw/cmssw/pull/22531 except that it doesnt allow any modification to ReducedEGProducer and therefore the energies of the electrons/photon objects are not changed. All the energies are still stored in the userFloats but the user will have to manually apply them in their analysis. 

This was made in the interests of allowing at least something to proceed into the re-miniAOD. At this point the PR reduces to 2 new producers which make ValueMaps which then get loaded into the pat::Electron and pat::Photon by existing mechanisms, vastly simplifying the implications of the PR

We can decide which of these two PRs goes through, obviously they are mutually exclusive.

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by gpetruc** [comment]
Personally, I think that we should put in the re-miniAOD the version where the e/gamma objects have the corrected 4-vectors (and smeared, for the MC).
This way, the majority of the analyses will use it and have a better data/mc agreement for the scale and resolution: even if it's not critical in most of the analyses, still there's lots of cases where people use the Z peak, e.g. to build control regions, where this will at least make the plots better.... 
There might be few analyses that look in odd corners of the phase space where this default correction may be worse than doing nothing, but in that case the analysers anyway already need to take care of their analysis-specific scales and resolutions (and interact withthe POG for this), so they can just revert these corrections before that step.

If we don't put in corrected 4-vectors, since correcting them is a non-negligible overhead (IDs need to be recomputed since they have pT dependent cuts or MVAs, need to re-sort in pT, has to be done before skimming, ...), it will be done only by the few analyses which really care for precise e/gamma scale and resolution. 
In the latter case, there's no real need to put anything in miniAOD production - though we would still want to integrate all the code so that people can take it from the release, and that we may use it for nanoAOD.

**Comment by slava77** [comment]
I'll reassess about this PR after the review of #22531 is done.

**Comment by Sam-Harper** [comment]
Okay, this one is now synced with #22531. The two should have identical output now (in fact just testing that), except that #22531 has the option to modify the energy at the reduced EG level. 

@gpetruc ,  we're going to recommend that IDs are calculated on the energy in the object although one should redo any Et cuts. The changes are small and (most) of the time, it just effects cut scaling. This just means we have a slightly different cut to what we thought we had by a small amount. Maybe introduces a very small data/MC scale factor at worst.  In the future I'm going to see if we can make VID cuts agnostic of this which would solve (or at least greatly simplify) the problem. 

There will be some edge cases of very large corrections being applied, due to the Ep combination giving effectively random results in this case. 

So if they want good data/MC agreement, we will request they scale their p4 by the values in the pat::Electron. Its easier to have it in the object, rather than people trying to follow a recipe to recalculate it.

**Comment by perrotta** [comment]
please test

**Comment by slava77** [comment]
On 3/14/18 3:46 AM, Sam-Harper wrote:
> Okay, this one is now synced with #22531
> <https://github.com/cms-sw/cmssw/pull/22531>. The two should have
> identical output now (in fact just testing that), except that #22531
> <https://github.com/cms-sw/cmssw/pull/22531> has the option to modify
> the energy at the reduced EG level.
> 

is it an enabled option?
If not, unless that option is questionable in some way, this PR is
perhaps not necessary.

**Comment by Sam-Harper** [comment]
They are not enabled. The modification was just slightly messy and inelegant (I realized a better way after writing it).  Also the whole packing the valuemaps through reduced e/gamma is no longer necessary as the value maps can be made directly using the reducedEG electrons/photons.  Again it doesnt bother me which one we use.  When my jobs finish, I'll be able to confirm they do give exactly the same output

**Comment by slava77** [comment]
On 3/14/18 5:37 AM, Sam-Harper wrote:
> They are not enabled. The modification was just slightly messy and
> inelegant (I realized a better way after writing it). Also the whole
> packing the valuemaps through reduced e/gamma is no longer necessary as
> the value maps can be made directly using the reducedEG
> electrons/photons. Again it doesnt bother me which one we use. When my
> jobs finish, I'll be able to confirm they do give exactly the same output
> 

OK, then.
It sounds like I should continue with the other PR.

**Comment by Sam-Harper** [comment]
Okay, I'll leave this one here as backup but yes we can focus on the new one. 

Also I've spent the last 30mins trying to figure out why I was getting differences in output between the two PRs. 

So it turns out my random seeding is not as good as I thought it was. It uses the number of crystals in a  supercluster. However when reduced E/gamma does its thing, when it slims electrons/photons it makes a new supercluster with just the seed cluster which messes up the rec-hits and fractions giving me a different seed for post and pre reduced eg objects. This is only for Et<5 electrons and photons which fail the preselection.  Thinking

**Comment by slava77** [comment]
-1

this fall-back solution is apparently not needed.
The features from #22531  are apparently almost good to go

**Comment by davidlange6** [comment]
Your PR is unmergeable. Please have a look and possibly rebase it.

**Comment by Sam-Harper** [comment]
Okay this PR is redundant, will close

**Pull request closed without merging**
