### PR TITLE
SiPM pulse shape fixes

### PR DESCRIPTION
**Pull request by kpedro88**
Some arbitrary cutoffs on the ranges of the Y11 and SiPM pulse shapes used in the digi simulation had been present in the code for several years. These cutoffs caused unphysical dropoffs in the output pulses, so they are now removed. Correspondingly, the RECO shape used for M2 is updated to be a full 250ns convolution.

Extensive investigation of these issues can be found in these slides: [sipm_pulse_study_4.pdf](https://indico.cern.ch/event/591614/contributions/2387530/attachments/1379109/2095655/sipm_pulse_study_4.pdf). Plots of M2 performance are included. Additionally, here is a 50 GeV pion response/resolution plot ("ref" corresponds to 810pre16 + #16569, "new" is ref + this PR):
pion plot

NB: Changing `Y11RANGE` globally will also change HO simulation output for Run1 and Run2. Theoretically this is more accurate, so I think the change should be allowed. If it is not acceptable, as a hack I can reset `Y11RANGE` on a per-channel basis, but I would prefer not to do this.

Planned items for followup PRs:
* Further cleanup of SiPM code (remove some unnecessary vars, hardcoded values, reduce duplication, etc.)
* Move Y11 functions into `HcalSiPMShape`
* Move `HcalSiPMShape` into `CalibCalorimetry/HcalAlgos`
* Use `HcalSiPMShape` to calculate numerical convolution for RECO shape on demand (replacing array of values)
* Option to store `vector<CaloSamples>` as event product for easier debugging

This PR will be backported to 81X.

### CODE REVIEW

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by kpedro88** [comment]
The changes in the comparisons for 2017 (and 2023) look reasonable to me. Other MC workflows show apparently-unrelated minor changes due to random number shifting. (The SiPM simulation is rather complex, with random number calls dependent on other random number calls that depend on parameters, so any parameter change can shift the whole chain.)

**Comment by slava77** [comment]
in 10024 I see
wf10024_m2_log10chi2_he

Maria's plot moved in the opposite direction 
maria_m2_log10chi2_he

Am I just comparing different phase space or other kind of apples to oranges?

**Comment by kpedro88** [comment]
@slava77 the major differences are sample type (500 GeV pion vs ttbar) and size (1000 events vs 10 events).

I made the set of M2 plots using baseline and this PR from 10024 step3.root. The performance overall agrees with what I expect: reduced chi2 at high energy (low energy has a larger spread in the baseline, which is not surprising - this PR mostly serves to improve self-consistency) and less spread in the time distribution.

**Comment by civanch** [comment]
+1
I would think that the fix is OK for 9_0 but am not sure about needs of backport

**Comment by kpedro88** [comment]
I'm not sure about the current plans for 81X vs 90X for 2017 tuning. If we no longer need to have the best local reco in 81X, the backport is unnecessary. But the POGs/DPGs still seem to be focusing on 81X as the standard for 2017...

**Comment by kpedro88** [comment]
@mmusich @davidlange6 I would like to get this into pre2 if possible

**Comment by mmusich** [comment]
+1

**Pull request merged**
