### PR TITLE
Phase2-hgx210 Make many of the cfi files uptodate

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Update the cfi and cfg files with correct positions of the files and ERAs

#### PR validation:

Passes standard matrix tests

#### if this PR is a backport please specify the original PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
+1

**Comment by fioriNTU** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

@kpedro88 these configurations are mostly for test and looks ok

**Comment by kpedro88** [comment]
+upgrade

**Pull request merged**
