### PR TITLE
Migration of HLT menus to 103X code base

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
Migration of HLT menus to 103X code base
Based on CMSSW_10_3_0_pre5

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by davidlange6** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by fabiocos** [comment]
please test

the comparison label looks stuck...

**Comment by fabiocos** [comment]
+1

**Pull request merged**
