### PR TITLE
Phase2-hgx341I Modify the correct conversion code in some of the debug statements of the dd4hep version of HGCal geometry involving cassettes

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Modify the correct conversion code in some of the debug statements of the dd4hep version of HGCal geometry involving cassettes

#### PR validation:

Use the existing test codes inside Geometry/HGCalCommonData

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

Improvement of test code.

**Comment by srimanob** [comment]
+Upgrade

Changes are in debug statement only, no change is expected from the DQM comparison.

**Comment by bsunanda** [comment]
@perrotta Please merge this

**Comment by rappoccio** [comment]
+1

**Pull request merged**
