### PR TITLE
Remove unused headers of Calib- packages

### PR DESCRIPTION
**Pull request by yuanchao**
Remove unused headers for ALCA packages #2

#### PR description:

Following the issue #31505, the following headers are unused in Calib* package:

- CalibCalorimetry/EcalLaserAnalyzer/interface/TMCORLin.h
- CalibCalorimetry/EcalLaserAnalyzer/interface/TMCORSat.h
- CalibCalorimetry/EcalLaserAnalyzer/interface/TMCReader.h
- CalibCalorimetry/EcalLaserAnalyzer/interface/TMConfig.h
- CalibCalorimetry/EcalLaserAnalyzer/interface/TMEGeom.h
- CalibCalorimetry/EcalLaserAnalyzer/interface/TPEDestalAnalysis.h
- CalibCalorimetry/HcalAlgos/interface/DoublePadeDelay.h
- CalibCalorimetry/HcalAlgos/interface/equalADCSignalTime.h
- CalibFormats/SiPixelObjects/interface/PixelAliasList.h
- CalibFormats/SiPixelObjects/interface/PixelConfig.h
- CalibFormats/SiPixelObjects/interface/PixelConfigAlias.h
- CalibFormats/SiPixelObjects/interface/PixelConfigFile.h
- CalibFormats/SiPixelObjects/interface/PixelConfigList.h
- CalibFormats/SiPixelObjects/interface/PixelMaskOverride.h
- CalibFormats/SiPixelObjects/interface/PixelTrimOverride.h
- CalibFormats/SiPixelObjects/interface/PixelVersionAlias.h
- CalibMuon/CSCCalibration/interface/CSCFakeCrosstalkMap.h
- CalibMuon/CSCCalibration/interface/CSCFakeDBCrosstalkPopCon.h
- CalibMuon/CSCCalibration/interface/CSCFakeDBGainsPopCon.h
- CalibTracker/SiStripCommon/interface/SiStripBFieldFilter.h   (does not exist in 12_1_x)
- Calibration/IsolatedParticles/interface/CaloSimInfoExtra.h
- Calibration/IsolatedParticles/interface/eECALMatrixExtra.h
- Calibration/Tools/interface/TrackDetMatchInfoCollection.h
- Calibration/Tools/interface/smartSelector.h

This is the second batch of the removal.

#### PR validation:

Code compiles. Run local limited runTheMatrix.py tests.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Not a backport and no backport forseen

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by mmusich** [comment]
@tvami @ferencek
are we positive these files

```
CalibFormats/SiPixelObjects/interface/PixelAliasList.h
CalibFormats/SiPixelObjects/interface/PixelConfig.h
CalibFormats/SiPixelObjects/interface/PixelConfigAlias.h
CalibFormats/SiPixelObjects/interface/PixelConfigFile.h
CalibFormats/SiPixelObjects/interface/PixelConfigList.h
CalibFormats/SiPixelObjects/interface/PixelMaskOverride.h
CalibFormats/SiPixelObjects/interface/PixelTrimOverride.h
CalibFormats/SiPixelObjects/interface/PixelVersionAlias.h
```

are not used by any of the commissioning activity s/w?

**Comment by tvami** [comment]
> @tvami @ferencek
> are we positive these files
> are not used by any of the commissioning activity s/w?

Yes, I just followed up with this and learned that those files are kept in a a separate repository.

**Comment by tvami** [comment]
@cmsbuild , please test
* hopefully the input errors are gone now

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
+alca
 * technical PR

**Comment by perrotta** [comment]
+1

**Pull request merged**
