### PR TITLE
LL exo relvals

### PR DESCRIPTION
**Pull request by srimanob**
New exo relvals.

### CODE REVIEW

**Comment by degano** [comment]
@cmsbuild please test

**Comment by srimanob** [comment]
@franzoni 
Do we have a fix for ttbar relval that I'm not aware of?

**Comment by davidlange6** [comment]
looks like a das glitch.

**Comment by degano** [comment]
@cmsbuild please test

**Comment by franzoni** [comment]
Hello, both the recent errors are unrelated to the PR as placed by @srimanob

**Comment by franzoni** [comment]
Hi @srimanob , 
the 3 workflows you've added work fine on top of pre5 => they're ok cmssw-wise.
For what concerns the injection to production, SGravitonToGammaGamma_kMpl01_M_3000_13TeV is a very long name which up in the RequestString and makes it too long (request are refused by reqmgr when the rest of the processing string is added).
Can you please modify this PR and add an explicit name to the 3 new workflows, shortened, to circumvent this problem ? 
It's very straightforward to do, I put here /afs/cern.ch/user/f/franzoni/public/4phat/relval_standard.py a suggestion on how to do it.
In the meantime, I submit the 3 wf's on top of pre5, with the naming I suggest locally modified, so we get a reference for the validators.
Cheers,
g.

**Comment by davidlange6** [comment]
please test

**Comment by degano** [comment]
@cmsbuild please test

**Comment by srimanob** [comment]
@franzoni 
Thanks. I've fixed the issue.

**Comment by degano** [comment]
@cmsbuild please test

**Comment by franzoni** [comment]
+1 
tested ok on top of pre6

**Pull request merged**
