### PR TITLE
Make CentralityProducer a global module

### PR DESCRIPTION
**Pull request by perrotta**
#### PR description:

As reported in the github issue #25090 (see https://github.com/cms-sw/cmssw/issues/25090#issuecomment-652605531) the CentralityProducer used in HI and pA runs is still a legacy module

This PR makes it a global module.

I profited also to add a fillDescription method to that producer, and a few member variables and configuration parameters were renamed to follow the CMS standards for them

#### PR validation:

A few HI workflows run without error

### CODE REVIEW

**Comment by perrotta** [comment]
@mandrenguyen @makortel @kpedro88

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
+1
- Technical: CentralityProducer made a global producer + some code cleaning
- Jenkins tests pass

**Comment by qliphy** [comment]
+1

**Pull request merged**
