### PR TITLE
Enforce ESInputTag label separation

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

When constructing an ESInputTag using only one non empty string, that string must now contain a ':' to denote the separation between the module and data labels. 

This is meant to catch a common error where the single string was meant to only specify the data label, but was instead specifying the module label.

As part of the change, I corrected the incorrect use of ESInputTags in various geometry modules.
#### PR validation:

The code compiles and all unit tests I could find which use ESInputTag pass.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
please test

**Comment by slava77** [comment]
```ESInputTag ESInputTag combinedSecondaryVertexSoftLeptonComputer must contain a ':' to separate the module and data labels.```
looks like some downstream changes are missing

**Comment by Dr15Jones** [comment]
@slava77 the most recent problem is from regenerating ESInputTags from stored ParameterSets. I'm thinking about how I want to handle that case without breaking old ParameterSet IDs.

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+core

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+core

**Comment by Dr15Jones** [comment]
The RelVal test failures are all from xrootd time outs.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/26780	5a55b09
- changes in reco are pretty minimal, in line with the PR description
- jenkins tests pass

**Comment by Dr15Jones** [comment]
@cvuosalo @ianna please review

**Comment by cvuosalo** [comment]
+1

**Comment by fabiocos** [comment]
@kpedro88 updates look technical and straightforward, could you please have a look and sign it or comment?

**Comment by kpedro88** [comment]
+upgrade

**Comment by fabiocos** [comment]
+1

**Pull request merged**
