### PR TITLE
Change default radii for HGCAL layer and multi clustering

### PR DESCRIPTION
**Pull request by edjtscott**
Would like to change the default values for two sets of radii in the HGCAL clustering:
1. the delta_c values in the layer clustering (from 2,2,2 to 2,2,5)
2. the multiclustering radii (from 2,2,2 to 2,5,5)

This makes more sense for hadronic objects (eg in the BH the cell sizes can be more than 2cm so the 2cm delta_c is silly) but is expected to have almost no effect on EM objects. 

See plots [here](https://escott.web.cern.ch/escott/HGCclustering/Pass24/Default_2cm/Photon_Pt25/Unconverted/?match=best) and [here](https://escott.web.cern.ch/escott/HGCclustering/Pass24/NewRadii_2cm/Photon_Pt25/Unconverted/?match=best) for the default and updated values respectively for unconverted pT 25 photons.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

@felicepantaleo @rovere 
please comment on relevance of this for pre4/TDR production.

**Comment by slava77** [comment]
assign upgrade

**Comment by rovere** [comment]
@slava77 this will only affect objects derived from multi-clustering within HGCal, namely the ones activated by #20045 
In fact, the changes are mostly for the BH part of HGCal, while we only build em objects that will be confined in EE. So, to summarize, it's nice to have, will have negligible effects on the objects produced in #20045 but would be better for hadronic objects that, at some point, will come too.

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/20131	cd9607d
- increased clustering size in BH and multiclustering size in FH and BH parts of HGCAL so that the hadronic part is accumulated in larger volume
- jenkins tests pass and reco comparisons with the (5 days old) baseline show changes only in 2023 workflows in hgcalLayerClusters
- local tests with PU200 on top of #20045 show somewhat expected behavior: changes in the hgcalLayerClusters propagate downstream to the newly added FromMultiCl collections
    - number of multiclusters is down by 7% mostly due to migration and accumulation in hadron parts of HGCAL
all_sign955-2023pu200vssign951-pass-10c3208-2023pu200_ttbar14tev2023d17putimingwf20234p2c_log10recohgcalmulticlusters_hgcallayerclusters__reco_obj_energy
    - this is seen as a 15% drop in the number of PF clusters "FromMultiCl"
all_sign955-2023pu200vssign951-pass-10c3208-2023pu200_ttbar14tev2023d17putimingwf20234p2c_log10recopfclusters_particleflowclusterhgcalfrommulticl__reco_obj_energy
    - and given higher thresholds, there is a 27% increase in the number of PF superclusters
all_sign955-2023pu200vssign951-pass-10c3208-2023pu200_ttbar14tev2023d17putimingwf20234p2c_log10recosuperclusters_particleflowsuperclusterhgcalfrommulticl__reco_obj_energy
    - more energy in hadron part is apparently picked up in electron seeding as larger h/e and we get less gsfTracks and less gsfElectrons (still, less by only 7%)
all_sign955-2023pu200vssign951-pass-10c3208-2023pu200_ttbar14tev2023d17putimingwf20234p2c_recogsfelectrons_ecaldrivengsfelectronsfrommulticl__reco_obj_pt
.. oddly enough this turns around as a slight increase in the number of photons
all_sign955-2023pu200vssign951-pass-10c3208-2023pu200_ttbar14tev2023d17putimingwf20234p2c_recophotons_photonsfrommulticl__reco_obj_caloposition_eta

**Comment by davidlange6** [comment]
+1

**Comment by slava77** [comment]
@davidlange6 
you will need to "merge" to get this in. "+1" is not enough.

**Comment by davidlange6** [comment]
merge

**Pull request merged**
