### PR TITLE
Better exception messages from ROOT delayed reading

### LINKED ISSUE #385: Reduce length of exception messages from delayed reader
See https://github.com/cms-sw/cmssw/issues/37579

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

- For the most common case, have RootDelayedReader copy the held exception type to avoid having all requesting tasks add additional context to the exception.
- Modified test for throwing an exception during delayed reading to have exception handling similar to RootDelayedReader.
 
#### PR validation:

- code compiles
- all framework unit tests pass
- a simple modification to ThrowingDelayedReader reproduced the same over reporting behavior seen by @slava77 . The change here avoided the problem and was applied to RootDelayedReader.

fixes makortel/framework#385

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
Please test

**Comment by makortel** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
