### PR TITLE
Provide easier to use ::get and ::getHandle methods for Event, Run and LuminosityBlock

### PR DESCRIPTION
**Pull request by Dr15Jones**
By using an `edm::EDGetTokenT<T>` one can now do
```C++
auto const& tracks = event.get(tracksToken);
```
or if one needs the `edm::Handle`
```C++
auto hTracks = event.getHandle(tracksToken);
```

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1
The unit test failure is not related to this code
The comparison differences are all from Taus coming from L1 or HLT. If this pull request caused a problem it should have caused problems across all ranges of the code.

**Comment by civanch** [comment]
+1
hope, that the unit test will be fixed

**Comment by Dr15Jones** [comment]
@fabiocos what is your thoughts on integrating this? The test failure was not from this change.

**Comment by fabiocos** [comment]
@Dr15Jones I'll integrate it in next IB, so we may see

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Comment by smuzaffar** [comment]
@Dr15Jones , look like this change has caused 3 compilation warnings in IBs.

**Comment by Dr15Jones** [comment]
> @Dr15Jones , look like this change has caused 3 compilation warnings in IBs.

@smuzaffar I actually saw those warnings before this change when I build FWCore/Integration as part of my usual build. I have yet to figure out what the compiler is complaining about.

**Comment by Dr15Jones** [comment]
@smuzaffar I just tracked down what caused that compilation warning. [It is not this pull request.]

**Comment by Dr15Jones** [comment]
@smuzaffar the fix is in #25764

**Pull request merged**
