### PR TITLE
[GEOMETRY-UPGRADE] Changes suggested by new llvm18 clang-format

### PR DESCRIPTION
**Pull request by smuzaffar**
This PR applies clang-format changes suggested by new llvm18 ( see https://github.com/cms-sw/cmssw/issues/45870 )

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by srimanob** [comment]
+Upgrade

Technical PR.

**Comment by bsunanda** [comment]
+geometry

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
