### PR TITLE
Improve code and event setup usage in HCAL calib

### PR DESCRIPTION
**Pull request by kpedro88**
Inspired by changes in #22538, as well as some basic code improvements in HcalHardcodeCalibrations.

attn: @christopheralanwest, this ended up touching some TPG classes - I think it simplifies things.

### CODE REVIEW

**Comment by kpedro88** [comment]
please test

**Comment by perrotta** [comment]
+1
- Kind of technical; changes in the reco area just take into account that the method HcalPulseContainmentManager::endRun() is removed here
- jenkins tests pass

**Comment by christopheralanwest** [comment]
@rekovic @nsmith- @thomreis In case you're waiting for my input: these changes do not modify any HCAL trigger primitive quantities, but substantially simplify the code.

**Comment by nsmith-** [comment]
+1
Just refactoring, no comparison changes

**Comment by arunhep** [comment]
+1

**Comment by slava77** [comment]
@fabiocos

this PR is rather technical and perhaps doesn't need to wait for 10_2_X to be open

**Comment by fabiocos** [comment]
@slava77 I agree, although it does not really look a fix

**Comment by fabiocos** [comment]
+1

**Pull request merged**
