### PR TITLE
Add LHE filter to cut on VpT

### PR DESCRIPTION
**Pull request by perrozzi**
important filter to launch the production on MG5_aMC NLO V+jets

### CODE REVIEW

**Comment by perrozzi** [comment]
please test

**Comment by perrozzi** [comment]
+1

**Review by fabiocos — COMMENTED** [review]
Why not using just std::abs?

**Comment by fabiocos** [comment]
@perrozzi the code in itself looks simple, anyway, being a new filter not previously used, I assume that the test performed here is totally dummy and it does not really test this new class. Was a standalone test done showing that it does what is it supposed to do? Sorry for the trivial question but...

**Comment by perrozzi** [comment]
no special reason to use the TMath version, if you suggest I will change to std.
Concerning validation, indeed @adewit posted some plots on the 93x PR, cfr https://github.com/cms-sw/cmssw/pull/21999#issuecomment-361202038

**Comment by perrozzi** [comment]
please test

**Comment by perrozzi** [comment]
+1

**Comment by fabiocos** [comment]
@perrozzi thanks for pointing me to the real validation

**Comment by fabiocos** [comment]
+1

**Pull request merged**
