### PR TITLE
Disabled looper reconstruction in HI Era for Run 3

### PR DESCRIPTION
**Pull request by sayanchatterjee38**
#### PR description:

Title: Disabled looper reconstruction in HI Era for Run 3

Description: This PR has disabled looper reconstruction from HI Era after checking timing and CPU usage, tracking efficiency, fake, multiple, non-primary reconstructions fractions for peripheral and central events. Also, the same checks were performed in the MinimumBias dataset produced for 1000 events. Please, see slides 1-9 from here [1].

No significant changes were observed in event and track variables while removing the No-Looper condition except the Hit count distribution. 

An issue had been raised already regarding disabling looper reconstruction for HeavyIons. Please look here [2] for detail. 

 
Link for the HI Trackin POG: 
[1] https://indico.cern.ch/event/1153062/contributions/4841907/attachments/2429416/4159748/NoLooper_HITracking.pdf 

Link for the issue:
[2] https://github.com/cms-sw/cmssw/issues/35758

#### PR validation:

Run time observations and a detailed study of each track variable have been performed with enabling and disabling trackingNoLoopers. We have also performed a detailed comparison of tracking efficiency, fake, multiple, and nonprimary reconstruction fractions for central, peripheral, and minimum bias events with enabling and disabling trackingNoLoopers.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

cc: @mandrenguyen, @abaty, @CesarBernardes

### CODE REVIEW

**Comment by mmusich** [comment]
@sayanchatterjee38, please rename the PR title to something like "Disabled looper tracks reconstruction in HI Era for Run 3", thanks.

**Comment by mmusich** [comment]
What about other HI-specific eras, such as `Run2_2018_pp_on_AA`?

**Comment by sayanchatterjee38** [comment]
> What about other HI-specific eras, such as `Run2_2018_pp_on_AA`?

Dear @mmusich, We have also checked in Run2_2018_pp_on_AA HI-specific eras. It is already mentioned here [1]. You can find datailed study for HI-specific eras Run2_2018_pp_on_AA from slides 36-58. Please have a look!

[1] https://indico.cern.ch/event/1153062/contributions/4841907/attachments/2429416/4159748/NoLooper_HITracking.pdf

**Comment by mmusich** [comment]
> We have also checked in Run2_2018_pp_on_AA HI-specific eras.

So, would it be appropriate to disable the loopers reconstruction also there?

**Comment by perrotta** [comment]
assign reconstruction

**Comment by jpata** [comment]
@cmsbuild please test

**Comment by jpata** [comment]
type hin

**Comment by jpata** [comment]
> What about other HI-specific eras, such as Run2_2018_pp_on_AA?

@sayanchatterjee38 I have the same question. If the reconstruction works better without loopers, it should also be disabled for Run2 (for a future rereco), as I understand.

**Comment by sayanchatterjee38** [comment]
> Hi @mmusich, @jpata For Run2_2018_pp_on_AA, we have checked timing and CPU usage and have done detail study of each track variables with enabling and disabling trackingNoLoopers. You can see slides [1] 36-58. Where we did not see anything suspicious. Yeah we can go ahead with disabling the trackingNoLoopers for Run2_2018_pp_on_AA with a new commit in this same PR.
> 
> [1] https://indico.cern.ch/event/1153062/contributions/4841907/attachments/2429416/4159748/NoLooper_HITracking.pdf

Hi @mmusich, Hi @jpata I have added a new commit regarding disabling trackingNoLoopers for Run2_2018_pp_on_AA.

**Comment by jpata** [comment]
@cmsbuild please test

**Comment by mmusich** [comment]
Hi @sayanchatterjee38 

> I have added a new commit regarding disabling trackingNoLoopers for Run2_2018_pp_on_AA.

in my original PR introducing the `trackingNoLoopers` modifier (https://github.com/cms-sw/cmssw/pull/35721) I made a series of exemptions for several other HI specific eras:
   * `Run2_2016_pA`
   https://github.com/cms-sw/cmssw/blob/c81c0f78cabc24cdefc09b1e1d4e21a8c25dfa6a/Configuration/Eras/python/Era_Run2_2016_pA_cff.py#L7
   * `Run2_2017_ppRef`
   https://github.com/cms-sw/cmssw/blob/c81c0f78cabc24cdefc09b1e1d4e21a8c25dfa6a/Configuration/Eras/python/Era_Run2_2017_ppRef_cff.py#L8
   * `Run2_2017_pp_on_XeXe`
   https://github.com/cms-sw/cmssw/blob/c81c0f78cabc24cdefc09b1e1d4e21a8c25dfa6a/Configuration/Eras/python/Era_Run2_2017_pp_on_XeXe_cff.py#L8
   
If I understand correctly from your [deck of slides](https://indico.cern.ch/event/1153062/contributions/4841907/attachments/2429416/4159748/NoLooper_HITracking.pdf)  you did not check explicitly those cases, but would it make sense to check and possibly disable the loopers reconstruction also there?

**Comment by jpata** [comment]
@sayanchatterjee38 any update? do you want to push this in pre4?

**Comment by jpata** [comment]
@sayanchatterjee38 a kind ping here

**Comment by jpata** [comment]
just to check what's the plan on this @sayanchatterjee38

**Comment by sayanchatterjee38** [comment]
> just to check what's the plan on this @sayanchatterjee38

Hi Joosep, Hi Marco, 
Very sorry for the delay! Here are a few comments.

**Comment by sayanchatterjee38** [comment]
> Hi @sayanchatterjee38
> 
> > I have added a new commit regarding disabling trackingNoLoopers for Run2_2018_pp_on_AA.
> 
> in my original PR introducing the `trackingNoLoopers` modifier (#35721) I made a series of exemptions for several other HI specific eras:
> 
>     * `Run2_2016_pA`
>       https://github.com/cms-sw/cmssw/blob/c81c0f78cabc24cdefc09b1e1d4e21a8c25dfa6a/Configuration/Eras/python/Era_Run2_2016_pA_cff.py#L7
> 
>     * `Run2_2017_ppRef`
>       https://github.com/cms-sw/cmssw/blob/c81c0f78cabc24cdefc09b1e1d4e21a8c25dfa6a/Configuration/Eras/python/Era_Run2_2017_ppRef_cff.py#L8
> 
>     * `Run2_2017_pp_on_XeXe`
>       https://github.com/cms-sw/cmssw/blob/c81c0f78cabc24cdefc09b1e1d4e21a8c25dfa6a/Configuration/Eras/python/Era_Run2_2017_pp_on_XeXe_cff.py#L8
> 
> 
> If I understand correctly from your [deck of slides](https://indico.cern.ch/event/1153062/contributions/4841907/attachments/2429416/4159748/NoLooper_HITracking.pdf) you did not check explicitly those cases, but would it make sense to check and possibly disable the loopers reconstruction also there?

Hi Marco, We are not sure if we want to disable it for iterations we haven't tested personally for previous eras (2016, 2017). So it would be better to prioritize only Run3 and Run2_2018 eras for this PR.

**Comment by jpata** [comment]
@sayanchatterjee38 was this closed intentionally?

if not, you should be able to reopen it

**Comment by sayanchatterjee38** [comment]
> @sayanchatterjee38 was this closed intentionally?
> 
> if not, you should be able to reopen it

Thanks, Joosep. No, it was by mistake. I reopened it.

**Comment by sayanchatterjee38** [comment]
Hi @jpata, We were using too old release CMSSW for this PR before. We discussed this internally and moved to a new one, which has no conflict with the master branch. So Now could we close this current PR and create a new one with the new release? Is this fine for you? Please let us know your opinion on it!

**Comment by jpata** [comment]
Sure, please close this one and open a new one if that's most convenient for you.

**Pull request closed without merging**
