### PR TITLE
[Urgent] Update CPX tune to 13.6 TeV

### PR DESCRIPTION
**Pull request by SanghyunKo**
#### PR description:

Update CPX tune to 13.6 TeV, see https://indico.cern.ch/event/1169048/#30-sample-normalization-for-cp

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

This PR is meant to be backported to 12_4_X & 12_2_X for Run 3 MC production

### CODE REVIEW

**Comment by SanghyunKo** [comment]
@Saptaparna @GurpreetSinghChahal @menglu21 @agrohsje @qliphy @sensrcn FYI

**Comment by qliphy** [comment]
please test

**Comment by Saptaparna** [comment]
Hi @SanghyunKo, based on the discussion with Sercan, it could be useful to have 2 sets of settings one for 13TeV and the other for 13.6 TeV in the event that someone uses this campaign for Run II

**Comment by SanghyunKo** [comment]
@Saptaparna I was thinking about this, but I guess one should use 10_6 for Run 2. Of course we can generate either of 13/13.6 TeV samples with a single release in the GEN point of view, however consecutive SIM-DIGI-RECO step is entirely specialized for the specific run for each release, no?

**Comment by Saptaparna** [comment]
Indeed, actually now that I think about it a bit more, we have a genchecking script level check to make sure that the c.o.m is 13.6 TeV. So, this should be fine. +1

**Comment by Saptaparna** [comment]
+1

**Comment by qliphy** [comment]
@SanghyunKo @Saptaparna  Surely for Run3 production only these updated CPX tune files will be used.   However, please check the comparison differences are as expected:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_5_X_2022-06-13-1100+08e0d6/50968/validateJR.html

**Comment by qliphy** [comment]
@SanghyunKo @Saptaparna Please already make a backport PR

**Comment by SanghyunKo** [comment]
Hi @qliphy, I've checked the failed comparisons, however it seems that most of them are SIM/HLT/RECO plots filled with only a few entries. I wouldn't expect any significant change but since this PR will affect any random number involved in CPX tunes, that might be the cause.

**Comment by qliphy** [comment]
@SanghyunKo @davidlange6 @Saptaparna 
Probably we can add new CPX files for 13.6TeV into a new directory, e.g.
Configuration/Generator/python/MCTunesRun3?

**Comment by agrohsje** [comment]
I agree with @qliphy  and @davidlange6 . We should distinguish the two files. I think @SanghyunKo is generally right, that 12_5 and above cannot easily be used for 13 TeV MC production (e.g. need to suppress the compatibility checks) but in generally what we are committing here is a file that is valid for 13.6 TeV, so also other runs might not use it. E.g. in the past 14 TeV runs used the 13 TeV value. Of course impact is minor and the upgrade studies so rough that it is irrelevant but generally I think it is good to distinguish and avoid implicit assumptions.With different names/folder we allow people to realize this and get back to us in case of questions. If we just sneak in the info is lost.

**Comment by SanghyunKo** [comment]
Note that since we now choose to separate 13.6 TeV settings from 13 TeV, we need to propagate the name & path change to all relevant CPX hadronizer templates for the productions @agrohsje @sihyunjeon

Please let me know if there is any other comment, otherwise I'll commit this to #38362 #38363 as well.

**Comment by agrohsje** [comment]
Thanks @SanghyunKo for the heads-up. We will store in a single place the import command for all the tunes in a given campaign. So it is easy for us to consider your PR. Thanks so much!

**Comment by qliphy** [comment]
please test

**Comment by qliphy** [comment]
please test

**Comment by qliphy** [comment]
@cms-sw/generators-l2   Please consider signing this PR thus we can include the backported one in 12_4_0.

**Comment by Saptaparna** [comment]
+1

**Comment by agrohsje** [comment]
Dear @cms-sw/generators-l2, @SanghyunKo 
there is small "steering" problem with this PR for our automatic background production. The files are named e.g. PythiaCP1Settings13p6TeV_cfi.py, so CP1 and 13p6TeV are pulled apart and split by Settings, similar inside the file we have, e.g.:
pythia8CP1Settings13p6TeVBlock and pythia8CP1Settings13p6TeV.
In the first case: Settings and Block are even pulled apart, although they belong together.
The handling is a bit ugly as we would need to have two parameters to get the name right. To simplify, can we just leave the old names and call the folder MCTunes_Run3_13p6TeV or something like this? That would simplify steering a lot. Also for users who can easily update from UL fragments by just changing one line instead of having all the time 13p6TeV to add somewhere. 
Cheers, Alexander.

**Comment by SanghyunKo** [comment]
@agrohsje seems like it's going back to the initial commit but with a separate folder. Is it okay-ish to make two different `PSet` coexist with the same name? (which why I put `13p6TeV`) Otherwise, I don't have any strong opinion on the naming convention frankly - I volunteered for this PR simply because no one else could do this before the 12_4_0 deadline. Unfortunately, 12_4_0 is already there and I don't have any good picture of the next release & MC production schedule (or how the new automatized steering handles the `PSet` name). So maybe it'd be more efficient to discuss with someone who has a better picture than me. Perhaps L2 knows whether @agrohsje still has a chance for another PR? @Saptaparna @GurpreetSinghChahal @menglu21

**Comment by Saptaparna** [comment]
I agree with @SanghyunKo. Thanks to @qliphy for helping us with the inclusion of this PR into 12_4. @agrohsje will it be possible for you to read these files in their current format or is that a no-go?

**Comment by agrohsje** [comment]
And let me add. My comment was not against what was done. I know that Sanghyun just stepped up and helped out. So that was really great. I just realized that the current solution is not ideal from a generic computing perspective.

**Comment by sihyunjeon** [comment]
Just throwing random stuffs, I saw PPD slides and looks like 12_4_1 is going to be used in the end, and do we still have time for that?

**Comment by qliphy** [comment]
@agrohsje @SanghyunKo @cms-sw/generators-l2   12_4_1 will be cut by next Tuesday (June 28th).   So please make relevant PRs the sooner the better to include the comments as mentioned above by @agrohsje  if agreed by everyone: 
"To simplify, can we just leave the old names and call the folder MCTunes_Run3_13p6TeV or something like this? That would simplify steering a lot. Also for users who can easily update from UL fragments by just changing one line instead of having all the time 13p6TeV to add somewhere."

**Comment by sihyunjeon** [comment]
@qliphy Thanks for the confirmation!

**Pull request merged**
