### PR TITLE
Remove deprecation warnings from `TrackingTools`

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

Part of the migration in #31061
Went systematically through all of the `CMSDEPRECATED_X` warnings in the  `TrackingTools` subsystem from [CMSSW_12_2_CMSDEPRECATED_X_2021-12-03-2300](https://cmssdt.cern.ch/SDT/cgi-bin/showBuildLogs.py/slc7_amd64_gcc900/www/fri/12.2.CMSDEPRECATED-fri-23/CMSSW_12_2_CMSDEPRECATED_X_2021-12-03-2300)
and removed deprecated API calls.

#### PR validation:

`cmssw` compiles after having retrieved dependencies with `git cms-checkdeps -a`.
.
#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
@cmsbuild please abort.

In the past 7 hours nothing happened.

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by jpata** [comment]
+reconstruction
- technical
- no reco changes

**Comment by perrotta** [comment]
+1

**Pull request merged**
