### PR TITLE
add PU=0 at the start of vectors (master)

### PR DESCRIPTION
**Pull request by capalmer85**
Same as #21285 but in master

### CODE REVIEW

**Comment by capalmer85** [comment]
@davidlange6, @franzoni

**Comment by civanch** [comment]
please test

**Comment by davidlange6** [comment]
hi @capalmer85 @civanch - so how do you suggest to prevent these issues next time?

**Comment by civanch** [comment]
+1

**Comment by civanch** [comment]
@davidlange6 , potentially, a warning may be added in the constructor of the class. May it be an exception for me not clear.

**Comment by capalmer85** [comment]
For me, I have to remember that indices start at 0. :-)

I'm not sure what else one can do given that there is no single macro to
produce these PU distributions.

**Comment by davidlange6** [comment]
humans are involved - no surprise - but maybe there is or should be a macro that _tests_ the distributions?

**Comment by capalmer85** [comment]
What test do you suggest though?  That the first PU index is 0?  I'm not
sure that will always be true for all scenarios.

**Comment by franzoni** [comment]
hello @capalmer85 @davidlange6 

a fair amount of test on the input histogram are actually carried out here:

https://github.com/cms-sw/cmssw/blob/09c3fce6626f70fd04223e7dacebf0b485f73f54/Mixing/Base/src/BMixingModule.cc#L99

, and this is loaded any time the mixing takes place needing a target distribution.
Can the bot be instructed to customise one of the PU standard test with the option:

`   --pileup 2017_25ns_WinterMC_PUScenarioV1_PoissonOOTPU`

That would be the easiest, imho.

**Comment by davidlange6** [comment]
the bot can pick up any change in runTheMatrix. indeed, probably for the best that future pu distributions come with a corresponding runTheMatrix entry

but that doesn't easily confirm the PU distribution itself. That could be more easily accomplished via a unit test.. maybe @civanch can discuss with the sim group and propose something?

**Comment by civanch** [comment]
Yes, we can discuss this. For me not clear where check should be. Unit test is intended to test something stable but in this case after each new scenario we have to change unit test. This may not work. The extra sanity checks inside class constructor may be implemented and/or addition of an extra entry to the runMatrix may be needed.

**Comment by davidlange6** [comment]
> On Nov 15, 2017, at 11:04 AM, Vladimir Ivantchenko <notifications@github.com> wrote:
> 
> Yes, we can discuss this. For me not clear where check should be. Unit test is intended to test something stable but in this case after each new scenario we have to change unit test. This may not work. The extra sanity checks inside class constructor may be implemented and/or addition of an extra entry to the runMatrix may be needed.

or the unit test looks for all scenarios within the standard directory and does something useful with each one...

**Comment by davidlange6** [comment]
+1
(I guess there is not much interest in unit tests)

**Pull request merged**
