### PR TITLE
Adding HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_DZ_Mass3p8 to offline DQM 

### PR DESCRIPTION
**Pull request by lathomas**
Very basic PR to add  HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_DZ_Mass3p8 to the list of paths monitored by the TOP DQM monitoring tools. 
The two files are copied from https://github.com/cms-sw/cmssw/pull/19119  and I simply added an extra line for HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_DZ_Mass3p8 

Hope it's all right... 

Let me know if this is the right way to proceed and I'll make the same for 93X. 
Thanks, 

Laurent

### CODE REVIEW

**Comment by mtosi** [comment]
how do you do mass and dz monitoring ?

**Comment by mtosi** [comment]
tracked by https://github.com/cms-sw/cmssw/issues/19142

**Comment by lathomas** [comment]
Well since HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_DZ_Mass8 was already in that PR, I assumed DZ and the mass were already fully monitored... Sounds true for DZ, less clear for the mass.

**Comment by mtosi** [comment]
maybe you want to add a di-lepton mass plot ?
w/ a switch/flag (w/ default value = false) for enabling this plot only for
a sub-set of triggers (like yours :P )

thanks

**Comment by fwyzard** [comment]
hi Mia, the documentation is linked where it says "cms-bot commands are listed here" .

You can ask "@cmsbuild, please test with #xxxxx"

**Comment by mtosi** [comment]
@cmsbuild, please test with #19119

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by fwyzard** [comment]
@lathomas, should I expect any updates to this PR ?

**Comment by fwyzard** [comment]
@dmitrijus, @davidlange6, since this PR extends the existing DQM via python only, I assume you have no objections ?

**Comment by fwyzard** [comment]
sigh... @lathomas can you fix the problem ?
it should be enough to merge this locally and run any of the "matrix" workflows to see it.

**Comment by fwyzard** [comment]
wait, delay that... let's fix all the 9.3.x PRs first

**Comment by fwyzard** [comment]
sorry, I've re-read the thread from the start now... so
  - @mtosi , are you satisfied with the monitoring strategy ?
  - @lathomas , can you make a PR for 9.3.x based on the latest IB ?

**Comment by lathomas** [comment]
@fwyzard  : I think Mia was also requesting an effcy vs mass plot. That will require a bit of work (i.e. more than a change in a config file). 
I'm realizing that this path should rather use the Muon monitoring: 
https://github.com/cms-sw/cmssw/pull/19512
I'll talk to Sergio anbd see how we can efficiently progress on this.

**Comment by fwyzard** [comment]
Understood.
Can you close this PR, and make a new one for 9.3.x once the new approach is in place ?

**Comment by mtosi** [comment]
ciao
@lathomas and @fwyzard 
I probably missed it (sorry)
but, can you please point me to the "new one for 9.3.x once the new approach is in place" ?
thanks !

**Comment by fwyzard** [comment]
Two weeks is a lot to remember what the intent was... I guess I was asking about a 9.3.x version of #19512 ?

**Pull request closed without merging**
