### PR TITLE
protect DAClusterizerInZ_vect.cc from a too small value backport  #16761

### PR DESCRIPTION
**Pull request by VinInn**

### CODE REVIEW

**Comment by slava77** [comment]
@VinInn please edit the name of the PR to be more descriptive. simply "backport" is not acceptable

... this one will not hold 810 release

**Comment by VinInn** [comment]
@cmsbuild , please test

**Comment by VinInn** [comment]
type backport

**Comment by VinInn** [comment]
type bugfix

**Comment by cvuosalo** [comment]
+1

For #16762 a03803e8eb1a432840c9105f726f32f609c65f43

Fixing a bug by not processing NAN values in the PrimaryVertexProducer.

#16761 and #16764 are the 90X and 80X versions of this PR.

The code changes are satisfactory. Jenkins tests against baseline CMSSW_8_1_X_2016-11-25-1100 show a large number of differences in values related to hits, tracks, jets, and MET, but these differences are very tiny and insignificant. More extensive testing for #16761 also shows the presence of these tiny differences, but none are significant.

**Comment by slava77** [comment]
as usual, this should go in only after 90X version (which is not signed yet) is merged.
Given that the fixed bug was "validated" for more than 5 years and the fix seems to be really needed for pA, this can't be urgent  enough for 81X to violate the policy.

**Comment by cvuosalo** [comment]
#16761, the 90X version of this PR, has now been approved.

**Pull request merged**
