### PR TITLE
adding entry to DQM matrix for HLT monitoring @T0

### PR DESCRIPTION
**Pull request by deguio**
@puigh 
submitting as it is. once PR #10017 will be ready, we will update.
going to ask for a release at tomorrow's ORP.

contact me over skype if needed.
F.

### CODE REVIEW

**Comment by puigh** [comment]
Thanks for the information and keeping me in the loop, @deguio

**Comment by deguio** [comment]
+1

**Comment by deguio** [comment]
please test

**Comment by davidlange6** [comment]
+1

**Pull request merged**
