### PR TITLE
use new method of disabling EDAliases

### PR DESCRIPTION
**Pull request by kpedro88**
Followup to #15909 to use the new method of disabling EDAliases. Tested with 20000.0 (2023D1 FourMu).

### CODE REVIEW

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by kpedro88** [comment]
attn: @Dr15Jones

**Comment by Dr15Jones** [comment]
Thanks for getting read of the `isChosen` calls.

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
