### PR TITLE
 backport in 14_1_X of PR#45993: bug-fix: remove DoubleSensGeomDet (ph-2 InnerTracker)

### PR DESCRIPTION
**Pull request by emiglior**
#### PR description:

type bug-fix: this PR fixes the CMSSW issues https://github.com/cms-sw/cmssw/issues/43097 and https://github.com/cms-sw/cmssw/issues/45792 removing the DoubleSensGeomDet introduced for phase-2 Inner Tracker modules (T33 tracker geometry and following T35, T36, T37, T38 and T39) but actually not used in the code (and unlikely to be used in future).

No changes expected for the output.

#### PR validation:

Tested on:
-  issue #43097
   cmsRun Fireworks/Geometry/python/dumpRecoGeometry_cfg.py  tag=2026 version=D110
   (up to version D113)
- issue #45792 
   cmsRun Alignment/TrackerAlignment/test/Misalignments/createRandomlyMisalignedGeometry_Phase2_cfg.py
- D110: runTheMatrix.py --what upgrade -l 29607.0

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

This PR is a backport in 14_1_X of the bug-fix https://github.com/cms-sw/cmssw/pull/45993
Needed to test TkAlignment on MC samples produced in 14_1_X with 2026D110/T35 geometry

@henriettepetersen @Raffaella07 @bartosik-hep @sroychow @mdelcourt @srimanob FYI

### CODE REVIEW

**Comment by mmusich** [comment]
backport of #45993

**Comment by mmusich** [comment]
type bug-fix

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by jfernan2** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by perrotta** [comment]
In the master version of this PR you modify [Fireworks/Geometry/src/FWRecoGeometryESProducer.cc](https://github.com/cms-sw/cmssw/pull/45993/files#diff-bd1c3d52e282e0f96c1298c86905564c1cde0bc0841828d9406510cae0494de3) and you don't modify it here: ok, in the master you had to revert #45784.

In this 14_1_X backport you modify [Fireworks/Geometry/python/dumpRecoGeometry_cfg.py](https://github.com/cms-sw/cmssw/pull/45996/files#diff-441adcaaca2b81a7aa670baa2a7d2db0fb7bdfb3207cacc386bcba57048c9c7a) : ok, you are backporting the corresponding update previously merged in master with #45328. You did not add the unit test, but ok: it is tested in the master nonetheless

Adding some explanation of what above in the PR description would have simplified the review...

**Comment by perrotta** [comment]
+alca

**Comment by alja** [comment]
+1

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
