### PR TITLE
[12_4_X] Updating EGM regression tags and conditions for the L1 EMTF and CALO tags for Run-3 MCs

### PR DESCRIPTION
**Pull request by tvami**
#### PR description:

See https://github.com/cms-sw/cmssw/pull/38324

#### PR validation:

```
test parameters:
  - workflows = 12034.0,11634.0,7.23,159.0,12434.0,12834.0
```

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Backport of https://github.com/cms-sw/cmssw/pull/38324

### CODE REVIEW

**Comment by tvami** [comment]
test parameters:
  - workflows = 12034.0,11634.0,7.23,159.0,12434.0,12834.0

**Comment by tvami** [comment]
Backport of https://github.com/cms-sw/cmssw/pull/38324

**Comment by tvami** [comment]
type l1t,egamma

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by malbouis** [comment]
+alca

**Comment by qliphy** [comment]
+1

**Pull request merged**
