### PR TITLE
Introduce fast conversion of SIPixelQuality into SiPixelFEDChannelContainer payloads

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

This PR introduces a module to perform fast conversion from `SiPixelQuality` payload to `SiPixelFEDChannelContainer` via direct query of the Database (without passing from Event Setup).
This speeds up significantly the workflow for creating conditions for so-called Stuck-TBM simulation.

#### PR validation:

This is a standalone module, and has been tested by running the example configuration file in 
`CondFormats/SiPixelObjects/test/FastSiPixelFEDChannelContainerFromQuality_cfg.py` 

#### if this PR is a backport please specify the original PR:

This is not a backport.

### CODE REVIEW

**Comment by tocheng** [comment]
@cmsbuild please test

**Comment by tocheng** [comment]
+1

**Comment by tocheng** [comment]
@ggovi please sign off the PR when you have time. Thanks.

**Comment by ggovi** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
