### PR TITLE
L1T offine DQM changes for pp reference run - part2 - 92x

### PR DESCRIPTION
**Pull request by thomreis**
Backport of #21228 

To make the L1T offline DQM work for the pp reference run the trigger paths used must be adapted for the pp reference run HLT menu.

Part 2: L1T EG and L1T Jets

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by stahlleiton** [comment]
@davidlange6  : This PR is needed for the pp 5 TeV run

**Comment by rekovic** [comment]
please test

**Comment by rekovic** [comment]
+1

**Comment by thomreis** [comment]
Hi @jfernan2 could you sign this backport too please?

**Comment by jfernan2** [comment]
+1

**Comment by thomreis** [comment]
Data taking with 92 releases is over.

**Pull request closed without merging**
