### PR TITLE
Removed unused code related to OwnVector

### PR DESCRIPTION
**Pull request by wddgit**
#### PR description:

Remove unused code related to OwnVector. This is in preparation for a possible move to RNTuple from TTree as a persistence mechanism. RNTuple does not support OwnVector because it allows polymorphism.

This PR is just dealing with some of the easiest cases. Code that isn't used anymore (some was maybe never used). Matti initially identified this list in Issue #42734 and this issue also contains more information related to this. These are the "Clearly unused" cases on Matti's list. I spent some time with grep and git grep and double checking that they were not used. I tried to delete anything directly related OwnVector or there only to support OwnVector. There probably is more cleanup that could be done in this part of the code. For example, the class FastTrackerCluster appears to be completely unused. I'll delete it also if anyone asks.

An example of a typical class in this set of changes, ```edm::OwnVector<SiPixelRecHit>``` was initially committed in 2006 and then replaced by edmNew::DetSetVector in 2007, except the dictionaries were left in the code (maybe for backward compatibility at that time, I don't know) and never cleaned up.

#### PR validation:

As a temporary test I added the following to OwnVector.h, then ran checkdeps, and then ran "scram b". It succeeded. This shows nothing uses OwnVector<T> for these types. I did this for CMSSW_14_1_X_2024-02-08-1100 and CMSSW_10_6_39. This should eliminate the possibility anything could produce objects of these types or use them in any way. I guess the only possible weakness of this test is something might read an old file using a View or the code might be different in other releases, but that does not seem likely. 

I removed this after running the test. It is not in the PR.
```
   class OwnVector {
+    static_assert(!std::is_same_v<T, SiPixelRecHit>,
+        "foo does not support Bar1");
+    static_assert(!std::is_same_v<T, SiStripRecHit1D>,
+        "foo does not support Bar2");
+    static_assert(!std::is_same_v<T, SiStripRecHit2D>,
+        "foo does not support Bar3");
+    static_assert(!std::is_same_v<T, SiTrackerMultiRecHit>,
+        "foo does not support Bar4");
+    static_assert(!std::is_same_v<T, MTDTrackingRecHit>,
+        "foo does not support Bar5");
+    static_assert(!std::is_same_v<T, FastTrackerCluster>,
+        "foo does not support Bar6");
+    static_assert(!std::is_same_v<T, CSCStripHit>,
+        "foo does not support Bar7");
```

### CODE REVIEW

**Comment by wddgit** [comment]
please test

FYI @makortel

**Comment by mandrenguyen** [comment]
+reconstruction
code cleanup

**Comment by civanch** [comment]
+1

@sbein , it is technical code clean-up, I do think it affect any result

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
