### PR TITLE
[14.1.X] Update 2023 and 2024 Heavy Ion relval workflows for 2024 HLT menu

### PR DESCRIPTION
**Pull request by mmusich**
backport of https://github.com/cms-sw/cmssw/pull/46418
backport of https://github.com/cms-sw/cmssw/pull/46398

#### PR description:

PR https://github.com/cms-sw/cmssw/pull/46376 updates the `HIon` HLT menu such that it requires a L1T menu ([`L1Menu_CollisionsHeavyIons2024_v1_0_5_xml`](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/tags/L1Menu_CollisionsHeavyIons2024_v1_0_5_xml) ) different from the one used in 2023 (more L1T seeds are required by trigger paths introduced in the meanwhile, see [link to payload inspector](https://cern.ch/526sr) [1]).
The goal of this PR is to update the 2023 Heavy Ion relval workflows to use the `@fake2` menu and to update the 2024 Heavy Ion workflows to use the updated `HIon` menu (consequently the DQM and validation steps are updated to run the HLT sequences).

#### PR validation:

Tested successfully
```
runTheMatrix.py -l 160,160.02,160.03,160.1,160.2,160.3,160.4,160.501,161,161.02,161.03,161.1,161.2,161.3,161.4,180.0,180.1,181,181.1 --ibeos
```

also:

```
runTheMatrix.py -l 330.0, 331.0, 332.0 --ibeos
```

runs fine.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Verbatim backport of https://github.com/cms-sw/cmssw/pull/46398 and https://github.com/cms-sw/cmssw/pull/46418 to  `CMSSW_14_1_X` for 2024 HIon operations.

---
[1]

<details>
  <summary>L1T menu comparison</summary>

image

</details>

### CODE REVIEW

**Comment by mmusich** [comment]
test parameters:
   * workflows = 160, 160.02, 160.03, 160.1, 160.2, 160.3, 160.4, 160.501, 161, 161.02, 161.03, 161.1, 161.2, 161.3, 161.4, 180.0, 180.1, 181, 181.1

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mandrenguyen** [comment]
urgent

**Comment by Moanwar** [comment]
+Upgrade

**Comment by mmusich** [comment]
test parameters:
   * workflows = 160, 161, 330.0

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
@cms-sw/pdmv-l2 @cms-sw/upgrade-l2 your signature is requited again here as I included the commit from https://github.com/cms-sw/cmssw/pull/46418

**Comment by Moanwar** [comment]
+Upgrade

**Comment by AdrianoDee** [comment]
+pdmv

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
