### PR TITLE
Run3-gex17 Remove CASTOR geometry from Run3 scenario

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Remove CASTOR geometry from Run3 scenario

#### PR validation:

Tested using the runTheMatrix test workflow 11634.0

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade

**Comment by qliphy** [comment]
+1

**Pull request merged**
