### PR TITLE
L1T lowPU menu v3

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
L1T lowPU menu v3
The L1 xml file is provided by Takashi MATSUSHITA takashi.matsushita@cern.ch

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by mulhearn** [comment]
+1

**Comment by davidlange6** [comment]
can we remove v2 of the menu? I guess its used for nothing (prod or data taking wise)

**Comment by Martin-Grunewald** [comment]
@davidlange6 
Hmm, it was/is used for TSG tests, so prefer to keep it.

**Comment by Martin-Grunewald** [comment]
@davidlange6 
But we could and should clean it up once the lowPU is done and dusted in real data taking.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
