### PR TITLE
[14_1_X] New Tests PR Tests for HIN 2023 and 2024

### PR DESCRIPTION
**Pull request by AdrianoDee**
#### PR description:

Plain backport of #46419.

### CODE REVIEW

**Comment by AdrianoDee** [comment]
backport of #46425

**Comment by AdrianoDee** [comment]
please test

**Comment by AdrianoDee** [comment]
@cms-sw/upgrade-l2 any comment on this? Thanks!

**Comment by Moanwar** [comment]
+Upgrade

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
