### PR TITLE
[RECONSTRUCTION-UPGRADE] Various fixes/improvements for unit test

### PR DESCRIPTION
**Pull request by smuzaffar**
use full `$CMSSW_BASE/src/RecoMTD/DetLayers/test` path which will allow us to run this tests from any directory

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by AdrianoDee** [comment]
+1
(purely technical)

**Comment by mandrenguyen** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
