### PR TITLE
Run3-gex74Z Take care of the preshower numbering scheme in view of changes in preshower algorithm for dd4hep

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Take care of the preshower numbering scheme in view of changes in preshower algorithm for dd4hep

#### PR validation:

Tested for ddd as well as dd4hep way of defining Run3 geometry

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
@cmsbuild please test workflow 11634.911

**Comment by cvuosalo** [comment]
DD4hep workflow crashes in step 2.

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
@cmsbuild please test workflow 11634.911

**Comment by cvuosalo** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
