### PR TITLE
more iteritems and integer division cleanups (python3 unit tests)

### PR DESCRIPTION
**Pull request by davidlange6**
Fixes unit test failures in devel build. One occurrence of iteritems and one integer division (which behaves differently)

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/26443	768b222
- technical
- jenkins tests pass

**Comment by andrius-k** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
