### PR TITLE
Soft muon MVA id for run3

### PR DESCRIPTION
**Pull request by drkovalskyi**
#### PR description:

The PR introduces a new MVA discriminator, optimized for muons with transverse momentum less than 10 GeV, for Run3 data  analysis. 

The new model is trained using the XGBoost algorithm. The code uses the XGBoost C API for inference. A utility class, `XGBooster`, is introduced to avoid mistakes caused by incorrect usage of the model. Some of the inputs require additional processing of the muon matching information, which is implemented in `SoftMuonMvaRun3Estimator` files along with the model-specific inputs.

This PR adds one more float to the `pat::Muon` class, which alters the class check sum and necessitates a new version of the dictionary. It also adds one more branch to NanoAOD, deriving its value from the pat::Muon object as created in MiniAOD.

This new muon discriminator will be utilized for the reference soft muon selection in Run3 by MUO POG and BPH PAG. It is expected to be available in PromptReco in Run2024 and beyond. The latest presentation on the subject can be found at:
https://indico.cern.ch/event/1351304/#6-update-on-the-soft-muon-mva

==WARNING==
The model is stored in `cms-data` and it needs to be integrated into CMSSW release for the code to work. The relevant PR can be found at https://github.com/cms-data/RecoMuon-MuonIdentification/pull/10.

#### PR validation:

The code is copied from a private NanoAOD setup where it was extensively tested on hundreds of MC and Data samples. Modifications related to integration into PAT are minimal. A small RelVal test has been performed to confirm that results are identical to the private production.

FYI @JanFSchulte, @z4027163

### CODE REVIEW

**Comment by mandrenguyen** [comment]
please test

**Comment by drkovalskyi** [comment]
For unit and relval tests to succeed the following PR needs to be merged and integrated in CMSSW: 
https://github.com/cms-data/RecoMuon-MuonIdentification/pull/10

**Comment by mandrenguyen** [comment]
please test with https://github.com/cms-data/RecoMuon-MuonIdentification/pull/10

**Comment by mandrenguyen** [comment]
@drkovalskyi So only changes at the level of nano are expected?

**Comment by drkovalskyi** [comment]
No, both Mini and Nano have changed. Majority of the changes are in Mini including the data format change (one extra variable). Nano just copies the value of the new variable.

**Comment by mandrenguyen** [comment]
+reconstruction

**Comment by vlimant** [comment]
I don't see a nano dqm plot for the new variable, please add one

**Comment by drkovalskyi** [comment]
@vlimant was not aware of this requirement. Could you please point me to the instructions or example how it should be implemented.

**Comment by vlimant** [comment]
the relevant plots should be added here https://github.com/cms-sw/cmssw/blob/master/PhysicsTools/NanoAOD/python/nanoDQM_cfi.py#L523

**Comment by drkovalskyi** [comment]
@vlimant I have added necessary DQM plot. Let me know if anything else is missing.

**Comment by vlimant** [comment]
Hi @drkovalskyi looks all good. But then now I am confused while about to approve this ; why adding `softMvaRun3 ` instead of replacing 'softMva` (to have both in MC maybe) ? 
if we really want to keep two around (at the risk of proliferation), would `softMvaRun2` and `softMvaRun3` be better to avoid the people pick up `softMva` thinking it is still the reference one

**Comment by drkovalskyi** [comment]
Run2 and Run3 data were collected with different pixel detectors and different conditions. We are likely going to keep using softMva for Run2 analyses. It also seems to be working reasonably well for Run3. Maybe in the future we will be able to establish that one replaces the other, but this needs to be studied. So at the moment we need both.

**Comment by vlimant** [comment]
how about renaming `softMva` to `softMvaRun2` in this PR to avoid confusion ?

**Comment by drkovalskyi** [comment]
I agree it looks more appealing, but it will break code for existing analyses and I don't think it's worth it.

**Comment by vlimant** [comment]
uh, existing analysis will anyway have to touch up their code to use `softMvaRun3` ...

**Comment by drkovalskyi** [comment]
Ok, will make the change.

**Comment by drkovalskyi** [comment]
@JanFSchulte The change is more involved than I thought and it's not a "safer" option as far as I can see.  We are not adding new working points for Run3, only the MVA value. We cannot really define a new working point for Run3 at this point and it will be different for different analyses, i.e. I suspect we will have have fixed working points. So if I make the change we will go from one set:

- softMva
- softMvaId
- softMvaRun3

to 

- softMvaRu2
- softMvaId
- softMvaRun3

I find second set more confusing. I would leave it as is. If you really want to clean all the names, then we should review other MVA entries. What is mvaLowPt? Is it EWK "low" pt? It's not really meant to be used for low pt, since it's trained for 10GeV and above, i.e. EWK muons, not heavy flavor.

**Comment by JanFSchulte** [comment]
@drkovalskyi Point taken, we should review this a bit more general and can leave it for now.

**Comment by drkovalskyi** [comment]
This PR is aiming to the last open pre-release for Run2024, i.e. DataFormat changes shouldn't really happen after that for this release cycle. I think a proper review and renaming can wait till next release (next year basically). By that time we will have a better idea of what we can recommend for Run2 and Run3 analyses. At this point we just need to add the new MVA value to start using it in new Run3 analyses.
@JanFSchulte, @vlimant is Ok for you?

**Comment by JanFSchulte** [comment]
Yes, works for me.

**Comment by vlimant** [comment]
+1

**Comment by vlimant** [comment]
please test

**Comment by drkovalskyi** [comment]
The tests failed since they require external data as was mentioned earlier.

**Comment by JanFSchulte** [comment]
@antoniovilela @rappoccio @sextonkennedy 

Since we would like this new classifier to be present in prompt data for 2024, it would be great if this could be integrated in time for pre3, which IIRC closes tomorrow.

**Comment by mandrenguyen** [comment]
please test with https://github.com/cms-data/RecoMuon-MuonIdentification/pull/10

**Comment by JanFSchulte** [comment]
Is this timeout related to these changes, or just a hickup with the test system? The logs don't seem to tell me anything about specific problems.

**Comment by mandrenguyen** [comment]
please test with https://github.com/cms-data/RecoMuon-MuonIdentification/pull/10

**Comment by rappoccio** [comment]
+1

**Pull request merged**
