### PR TITLE
make DetStatus a stream module

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

Somewhat inspired by issue https://github.com/cms-sw/cmssw/issues/25090 I realize this module can become a `edm::stream::EDFilter`. 
Profited to add also `fillDescriptions` method and to move everything into the cc file.

#### PR validation:

Tested in `CMSSW_11_2_X_2020-06-04-1100` with concurrent lumisection workflows:
```
runTheMatrix.py -l 136.8861,136.8862 -j 8 -t 4 --ibeos
```
it passes the tests and in the step3 log the message:
``` 
The following modules require synchronizing on LuminosityBlock boundaries:
  DetStatus ALCARECOTkAlMinBiasDCSFilter
```
is gone.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

This PR is not a backport.

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild please test

**Comment by mmusich** [comment]
@chayanit, @wajidalikhan, @pgunnell

do you have comments on this PR?

**Comment by chayanit** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
