### PR TITLE
drop Alignment/CocoaAnalysis package which is sub-set of Alignment/CocoaFit

### PR DESCRIPTION
**Pull request by smuzaffar**
No other package depends on Alignment/CocoaAnalysis

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by mmusich** [comment]
please test

**Comment by diguida** [comment]
+1
unused package

**Comment by diguida** [comment]
@smuzaffar we need to ask the Muon HW alignment team about it.

**Comment by smuzaffar** [comment]
@diguida , yes if you think that they might be using it. In that case they can move to Alignment/CocoaFit which is superset of Alignment/CocoaAnalysis

**Comment by davidlange6** [comment]
will remove lots of duplicate dictionaries - Thanks @smuzaffar

**Pull request merged**
