### PR TITLE
EMTF emulate directly from unpacked CPPF digis - 10_1_X backport

### PR DESCRIPTION
**Pull request by abrinke1**
Backport of https://github.com/cms-sw/cmssw/pull/23747 for DQM

### CODE REVIEW

**Comment by thomreis** [comment]
please test

**Comment by thomreis** [comment]
Hi @abrinke1 
the commit 6682afc1fc49fb0a75eaab9f71feaeb87b3a9493 does not seem to be in the master PR. Is this already merged in master?

**Comment by thomreis** [comment]
+1

**Comment by thomreis** [comment]
backport of #23747

**Comment by thomreis** [comment]
Hi @abrinke1 
the last commit needs to be forward ported to the master branch and also to a 10_2_X PR. Both PRs need to be made since the initial master PR has been merged already and a 10_2_X PR has not been made yet.

**Comment by thomreis** [comment]
please test

**Comment by thomreis** [comment]
+1

**Comment by andrius-k** [comment]
+1

**Comment by abrinke1** [comment]
10_2_X back-port created: https://github.com/cms-sw/cmssw/pull/24106

**Comment by fabiocos** [comment]
@rekovic @thomreis @abrinke1 @jfernan2 @andrius-k as DQM has moved to 10_2_X, could we just close this PR?

**Comment by abrinke1** [comment]
Yes, presumably.

**Comment by fabiocos** [comment]
@abrinke1 ok, let's close it, in case we will reopen it

**Pull request closed without merging**
