### PR TITLE
[JetMETCorrections][clang-tidy] make deleted function public

### PR DESCRIPTION
**Pull request by smuzaffar**
Cleanup for clang-tidy warning `deleted member function should be public [modernize-use-equals-delete]`

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by slava77** [comment]
+reconstruction

for https://github.com/cms-sw/cmssw/pull/34687	f291edd
- technical

**Comment by perrotta** [comment]
+1
- Technical, no changes in outputs
- This is simple and can be merged, but please @cms-sw/analysis-l2 comment if you have comments

**Comment by perrotta** [comment]
merge

**Comment by santocch** [comment]
+1

**Pull request merged**
