### PR TITLE
Backport of assorted fixes: process-prune-method and TriggerSummaryProducerAOD

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
Backport of Chris's https://github.com/cms-sw/cmssw/pull/8828,
additional improvements in Config.py,
and improved error handling in TriggerSummaryProducerAOD

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by Martin-Grunewald** [comment]
+1

**Comment by davidlange6** [comment]
@cmsbuild, please test

**Comment by davidlange6** [comment]
test failures seem unrelated - likely from massive checkdeps that this PR has.. merging and will hope no knock on problems

**Pull request merged**
