### PR TITLE
Electron validation 81X preshower

### PR DESCRIPTION
**Pull request by archiron**
The quantity superCluster()->preshowerEnergy() / superCluster()->rawEnergy() is used in the electron ID and tracking changes would be useful.

This new histo was added for validation in the case of endcaps only.
The files used for this implementation are : 
Validation/RecoEgamma/plugins/ElectronMcFakeValidator.cc (h)
Validation/RecoEgamma/plugins/ElectronMcSignalValidator.cc (h)

The files :+1: Validation/RecoEgamma/test/ElectronMcSignalHistos.txt and Validation/RecoEgamma/test/ElectronMcFakeHistos.txt are used for web page creation and include the new histo.

Others minors correction : 
Validation/RecoEgamma/test/ElectronMcFakePostValidation_cfg.py
Validation/RecoEgamma/test/ElectronMcFakeValidation_gedGsfElectrons_cfg.py
in which a small Global Tag use is corrected

Validation/RecoEgamma/test/electronCompare.C
for these file, there is a small correction in web page creation due to gcc530.

@beaudett @matteosan1 @fcouderc @pigard

### CODE REVIEW

**Comment by dmitrijus** [comment]
please test

**Comment by dmitrijus** [comment]
+1
Code looks okay 

One comment:
It's okay and advisable to split your work into multiple commits. But this is too ridiculous...
A commit should mean a single piece of work, spanning multiple files (not per file).
In other words - if I check out a commit - it should represent a consistent state of code,
at a certain point in history.
Please, for the future, either use git commit --amend or squash/rebase ( https://www.atlassian.com/git/tutorials/rewriting-history/ )

**Comment by archiron** [comment]
OK.
In fact I tried to follow the davidlt comment in https://github.com/cms-sw/cmssw/pull/12895, but perhaps there is something I misunderstand.
So I have to give one commit explaining the work, and eventually give a more detailed (per file) into the PR abstract.
Please, sorry for this wrong way to work.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
