### PR TITLE
Backport of Factory for adding UserHooks to PythiaHadronizer and SUEP decay pythia Hook

### PR DESCRIPTION
**Pull request by cericeci**
Backport of https://github.com/cms-sw/cmssw/pull/36238, intended for UL signal production. I did include both changes from the PR for simplicity (the factory and the SUEP plugin itself), but I can take the former out of the code if deemed more appropriate as it is just a backport.

## Original PR description

This PR includes two main changes:
- A mechanism to add UserHooks to Pythia8Hadronizer through the usage of a PluginFactory (thanks to @kpedro88 for the idea and pointers on how to), so the source code of the main pythia plugin does not need to be modified when adding user modifications. This idea can be used in the future to migrate the current implementation of several UserHooks that are currently hard-coded.
- A module dedicated to soft unclustered energy pattern (SUEP or soft-bombs)-like decays, following the description of 1612.00850. It can be used to decay an SM particle through a soft-bomb shower.
   - The suep shower code (header and source) is taken directly from Simon Knapen's implementation and adapted to cmssw's code standards.
   - The module uses the previously discussed PluginFactory to be included inside the Pythia8Hadronizer and can be used for decays of ME obtained from either pythia or a LHE producer such as madgraph. An example of its usage can be found here. It's usage is based on the inclusion of the following lines inside the process.generator inside the fragment:

>
        UserCustomization = cms.VPSet(
           cms.PSet(
             pluginName = cms.string("SuepDecay"),
             idDark = cms.int32(999999), # pdgId of the dark meson
             idMediator = cms.int32(25), # pdgId of the mediator
             temperature = cms.double(2) # Temperature of the thermal distribution
           )

## PR validation

Unit tests passed.
Tests using a local config file show that the SUEP module properly decays the Higgs boson.

## Backporting:

Backport of https://github.com/cms-sw/cmssw/pull/36238

### CODE REVIEW

**Comment by kpedro88** [comment]
please test

**Comment by cericeci** [comment]
That's quite unexpected, I didn't got any segfaults when running the local tests. I'll investigate a bit farther on it

**Comment by cericeci** [comment]
Sorry for the noise, I made a very dumb mistake on the initialization of the added userhooks vector. Can I get the tests redone on this one?

**Comment by perrotta** [comment]
please test

**Comment by agrohsje** [comment]
+generators

**Comment by perrotta** [comment]
backport of #36238

**Comment by perrotta** [comment]
The method added to GeneratorInterface/Pythia8Interface/interface/MultiUserHook.h is not from #36238: could you please tell from which development or PR is it coming from?

GeneratorInterface/Pythia8Interface/plugins/BuildFile.xml looks rater different here in 10_6 and in the master release: can you explain?

The implementation in GeneratorInterface/Pythia8Interface/plugins/Pythia8Hadronizer.cc is rather different with respect to the one in the master: could you please summarize the differences?

**Comment by cericeci** [comment]
@perrotta thanks for reviewing (and sorry for the amount of your time I'm taking lately on pushing backports)

The treatment of collections of UserHooks changed in https://github.com/cms-sw/cmssw/pull/29995 (11_2, my understanding is that this was to adapt the code to ran on pythia 3.02,  but maybe @agrohsje knows a bit more on the gen side?). Then, the cms class MultiUserHook was replaced by pythia's UserHooksVector. Unfortunately the functionality to loop over the items in the vector doesn't seem to be there for the former so I added a getter to get them. Would it be better if I just define my fCustomHooksVector as an std::vector directly and avoid modifying MultiUserHook.h? I can also check whether with UserHooksVector runs under pythia 2.40 if you want (then the changes would be minimal).

For the BuildFile there were several changes between 10_6 and master (https://github.com/cms-sw/cmssw/pull/31329, https://github.com/cms-sw/cmssw/pull/31405) that were never part of a backport. I only added the minimal changes needed for the plugin to work, but I'm not sure whether anything else should be ported as well (at least scram is not complaining to me). Any suggestions?

The differences on Pythia8Hadronizer.cc arise from the first point above, I went backwards from the UserHooksVector syntax to the MultiUserHook one, so to get the same functionality I need to arrange it for the old class syntax.

**Comment by perrotta** [comment]
@cericeci thank you for your answers. In a backport, maintaining the changes and the number of ported features to the minimum is a welcome plus. Of course it cannot go at the expenses of the functionality, computing performance, and also effort needed to adapt the new addition into the new code. I am not expert enough in this code to judge whether you can, with a limited effort, backport only the new functionalities without the need of bringing together other developments integrated since then. I'll let you and @agrohsje to decide about it.
Therefore, either propose a simpler backport, or just confirm that it must remain in the present form. By the way, the getter in MultiUserHook.h seems to me a clean enough solution to get the hooks, and I wouldn't add more complicate gymnastic. I give for granted that you already checked carefully the comptibility with the pythia version available in 10_6

**Comment by cericeci** [comment]
@perrotta From my side I'm ok with the current implementation, but if anybody from gen wants me to adapt it farther I have no problem in doing so

**Comment by perrotta** [comment]
+1

**Pull request merged**
