### PR TITLE
Initialize id variable to silence warning

### PR DESCRIPTION
**Pull request by mrodozov**
#### PR description:

Initializes an unsigned to 0 to silence warning

#### PR validation:

no warning after the init

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by smorovic** [comment]
+1

**Comment by perrotta** [comment]
+1
- Trivial fix, only meant to silence the warning but with no practical effect
- Jenkins tests pass

**Comment by qliphy** [comment]
+1

**Pull request merged**
