### PR TITLE
L1T Fix try/catch improper use in Omtf->Rpc mapping (PR 10_1_X)

### PR DESCRIPTION
**Pull request by rekovic**
(PR 10_1_X) . L1T Fix try/catch improper use in Omtf->Rpc mapping.

### CODE REVIEW

**Comment by rekovic** [comment]
please test

**Comment by thomreis** [comment]
please test

again

**Comment by rekovic** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Comment by kpedro88** [comment]
resolves #21465

**Pull request merged**
