### PR TITLE
Adding test configuration files for New L3 Algorithms

### PR DESCRIPTION
**Pull request by BenjaminRS**
Here are two files to allow one to run and test the New L3 Algorithms presented in the Muon HLT meeting [1].

The newL3.py is a customiser - which modifies the HLT menu. This means someone can get a menu and add the following two lines to the end of it to switch on the New L3 algorithms:
from newL3 import addL3ToHLT
process = addL3ToHLT(process)

hltTestNewL3.py is simply a frozen 25ns menu dumped with a selection of interesting muon paths to look at along with the two lines mentioned above at the end of it.

This means someone could either get a menu and customise it with the customiser file (newL3.py) or simply run the stand alone menu.

[1] https://indico.cern.ch/event/402284/

### CODE REVIEW

**Comment by slava77** [comment]
@BenjaminRS if hltTestNewL3 is auto-generated, we should not keep it in the source distribution.
Even newL3 looks very temporary: visually,  it's not really maintainable.

**Comment by BenjaminRS** [comment]
Hi @slava77 this is just for testing purposes, and hence why in a test directory. There is an alternative to hltTestNewL3, which is to attempt to make a shell script to run the command used to get the menu and adjust it for the new L3.

newL3.py is still a testing configuration it would likely have to be adjusted with testing. Eventually we would then remove the file once testing was complete and the main L3 sequence in the HLT is changed.

**Comment by slava77** [comment]
Hi Benjamin,

I'm not much against the newL3.py.
Although, I'd prefer something less flat (not a plain dump).

On the other hand, aren't you developing in confDB?
If so, I guess even the newL3.py can be generated with a script.

What kind of testing do you have in mind?
If we put something in relval/add-on/unit tests,
a dump of such kind is probably still practical.
(but there is no such test added in this PR)

Maybe you are going to request some centrally produced datasets ...
Is that the case?
(then --customise  RecoMuon/L3MuonProducer/test/newL3.addL3ToHLT
may work as a part of the request, but I'm not sure if the /test/ path
is valid
)

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by BenjaminRS** [comment]
Hi Slava,

To clarify what the intention of this test files are for; we would like interested PAGs to test the new L3 Configuration so we can tune the configuration parameters and ensure that all groups get the performance they require from the new algorithms.

The files are not intended to be used for RelVal or anything else of that sort.

I have also added a readme which now explains this.

Thanks,
Benjamin

**Comment by slava77** [comment]
Hi Benjamin,

I  don't quite understand why we need yet another full dump of the HLT
table.
Can we derive it from what's in the release in the HLTrigger/Configuration?

At this point, if it's not going to any central production,
anyone who needs to test can just do "git cms-merge-topic 11200" and get
the files.

Since there is no massive multi-package compilation involved, the
central distribution
doesn't seem to be the right place for something this large which will
likely
become obsolete in a few pre-releases.

The ~10K lines of python don't appear to be needed in the release for that.
(They will  stay in the git history pickle file forever if they are added)

**Comment by BenjaminRS** [comment]
Hi Sava, then would it be ok to only have the customiser file: newL3.py inside the test directory?

**Comment by slava77** [comment]
yes, even though it would be nicer if newL3 was instead less flat and reused the same sub-psets; currently it looks bloated by copy-pastes.

**Comment by BenjaminRS** [comment]
Hi Slava, ok I removed the full menu dump and I tidied up newL3.py a bit. It is still a bit flat for example I had tried to define a master PSet on line 120 [https://github.com/cms-sw/cmssw/pull/11200/files#diff-13f64ab060cee75a2d4ff324f179f6c1R120] and then use it on line 881 [https://github.com/cms-sw/cmssw/pull/11200/files#diff-13f64ab060cee75a2d4ff324f179f6c1R881] but it does not work* and instead I needed to copy and paste the PSet as is done on line 852 [https://github.com/cms-sw/cmssw/pull/11200/files#diff-13f64ab060cee75a2d4ff324f179f6c1R852].

*The error that comes up when trying the method on line 881:
Illegal parameter found in configuration.  The parameter is named:
 'ComponentName'
When I do dumps of process.BRSIterL3Muons.L3TrajBuilderParameters.MuonTrackingRegionBuilder I do indeed see a new parameter called:
ComponentName = cms.string('MuonTrackingRegionBuilder')
Which is not present if I copy and paste the PSet as is done on line 852. I looked at the fillDescription of L3MuonProducer but I cannot see the definition of ComponentName [https://github.com/cms-sw/cmssw/blob/CMSSW_7_6_X/RecoMuon/L3MuonProducer/src/L3MuonProducer.cc#L236]

**Comment by slava77** [comment]
@cmsbuild please test
[not that there is something to test from the standard jenkins setup]

**Comment by slava77** [comment]
@BenjaminRS I can't say off-hand anything about the ComponentName.
If it's not in the fillDescription maybe it's something brought in by HLTrigger/Configuration/python/customizeHLTforCMSSW.py ? (I'm not sure if you are calling it though; just a guess of another place that could modify the full PSet)

**Comment by BenjaminRS** [comment]
Hi Slava, just to say that I updated that customiser previously for PR 8356, but did not define this ComponentName: https://github.com/cms-sw/cmssw/blob/CMSSW_7_6_X/HLTrigger/Configuration/python/customizeHLTforCMSSW.py#L27

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/11200	8b25644
- new L3Muon-specific test configuration is provided for testing
- only /test area files are added, standard workflows are no affected; jenkins tests passed.

**Comment by BenjaminRS** [comment]
Hi - is anything more needed from my side to finish this PR?
Thanks,
Benjamin

**Comment by slava77** [comment]
@BenjaminRS 
No inputs expected by me from you for now.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
