### PR TITLE
EMTF PR for DQM - August 2017

### PR DESCRIPTION
**Pull request by abrinke1**
Back-port of PR #19741 , #19743 , and #20006 into CMSSW_9_2_X.  Intended for deployment in Online DQM as soon as feasible.  Includes changed EMTF data formats and unpacking code for RPC hits, consequent changes to class names in the EMTF emulator, and new EMTF DQM plots.

### CODE REVIEW

**Comment by rekovic** [comment]
please test

**Comment by stahlleiton** [comment]
Hi @abrinke1 

Since I see that you renamed some of the Quality Tests for the EMTF, could you also update the L1T Summary Plot with the new QT names, in order to avoid an error due to missing QTs when running the DQM step. The lines are here:
https://github.com/abrinke1/cmssw/blob/de498087281a87d7586216f0e43536c4d9a8c522/DQM/L1TMonitorClient/python/L1TStage2EventInfoClient_cfi.py#L144

**Comment by thomreis** [comment]
Hi @abrinke1 
are the changes in your latest commit https://github.com/cms-sw/cmssw/pull/20206/commits/c37ffc21b03a58536dbc3da2b4b8bbac4d89b44f also in the master branch already?

**Comment by abrinke1** [comment]
@thomreis No, but I'll get them into 93X before the Online DQM moves to 93X

**Comment by thomreis** [comment]
@abrinke1 But if this PR has code that is not in 93x already it will not be merged.
Is this just for the tag collector of the online DQM?

**Comment by abrinke1** [comment]
@thomreis this is just for the tag collector - at least that's my understanding.

**Comment by dmitrijus** [comment]
@abrinke1 @thomreis We don't accept pull requests 'just for online DQM'.
If the pull request is not on its way to be officially merged, it should not be added to the tag collector.

**Comment by thomreis** [comment]
In that case could you make a PR with just the missing last commit to the master branch please @abrinke1 ? #19743 and #20006 are already merged and #19741 is contained in #19743 .

**Comment by abrinke1** [comment]
@dmitrijus @thomreis The latest fixes are included in the next EMTF PR to 93X:
https://github.com/cms-sw/cmssw/pull/20286/

In particular, see the "EMTF DQM fixed histogram names" commit:
https://github.com/abrinke1/cmssw/commits/EMTF_PR_2017_93X_part8c

Once this is in, and 93X is running at P5, we can just remove the above commits from the tag collector entirely.

**Comment by thomreis** [comment]
Hi @abrinke1 I think this can be closed since it is also contained in #20936 and deployed at P5 with that one.

**Pull request closed without merging**
