### PR TITLE
Improved GenHFHadronMatcher test configuration 7_4_X

### PR DESCRIPTION
**Pull request by bartosik-hep**
AOD/miniAOD can switched via command line parameter.
Changed jet cone size from 0.5 to 0.4 in the test configuration.
Added a dedicated analyzer for the test configuration which produces output trees with some performance information. Has clear code example of how to use output of the tool.
By default all hadrons injected by the JetFlavour tool are analysed, including bbbar resonances.

### CODE REVIEW

**Comment by davidlange6** [comment]
please rename genHFHadronMatcher as there is already a GenHFHadronMatcher plugin.

**Comment by bartosik-desy** [comment]
@davidlange6 Done.

**Comment by monttj** [comment]
+1

Hello Nazar,

I found this really useful for endusers.
Will we have this example for previous releases?

Regards,
Taejeong

**Comment by bartosik-desy** [comment]
@monttj Hello Tae Jeong, yes the pull request for 7_3_X and 7_2_X are pending.

In addition I have submitted a pull request with a backport for 5_3_X so that 7/8 TeV analyses are covered.

**Pull request merged**
