### PR TITLE
Added pileup scenario for 2023 simulation

### PR DESCRIPTION
**Pull request by romeof**
#### PR description:

This PR includes the information to simulate the pileup scenario for the 2023 simulation samples. We rely on part of RunC data (fills 8807 to 8901) to generate such pileup distribution. More details have been discussed in the PPD General Meeting (see link https://indico.cern.ch/event/1299290/).

#### PR validation:

The added code has been tested with CMSSW_13_2_0_pre2, using the root file /store/relval/CMSSW_13_0_0_pre4/RelValMinBias_13p6TeV/GEN-SIM/130X_mcRun3_2022_realistic_withNewBSFromEOY2022Data_v1_RV186-v1/00000/18441d91-eeb9-46a9-bc4a-f5c388ef5e27.root

### CODE REVIEW

**Comment by malbouis** [comment]
Hi Francesco, thank you for the PR! 
Would you please also include a description of this PR, for future reference?
Thanks!

**Comment by romeof** [comment]
This PR includes the information to simulate the pileup scenario for the 2023 simulation samples. 
We rely on part of RunC data (fills 8807 to 8901) to generate such pileup distribution.
More details have been discussed in the PPD General Meeting (see link https://indico.cern.ch/event/1299290/).

**Comment by malbouis** [comment]
> This PR includes the information to simulate the pileup scenario for the 2023 simulation samples. We rely on part of RunC data (fills 8807 to 8901) to generate such pileup distribution. More details have been discussed in the PPD General Meeting (see link https://indico.cern.ch/event/1299290/).

Thanks a lot! Would you also please edit the very first comment on top of this PR, to include the description there?

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
@romeof , you may edit a description and/or a title of any PR at any time. So, for this particular case, you simply copy your comment and insert into the description.

**Comment by romeof** [comment]
thanks for comments. let me know if anything else is left to do.

**Comment by civanch** [comment]
please test

the problem is in timeout not relevant to this PR but let us repeat the test.
We should likely backport this PR to 13_1_X and 13_0_X for any case, even if DIGI step will not run at these releases

**Comment by civanch** [comment]
+1

**Comment by perrotta** [comment]
@romeof could you please remove the extra spaces added at the end of [line 133](https://github.com/cms-sw/cmssw/pull/42213/files#diff-5d0e38000f59e03651966b3238dc5b4413f6249e4134d5d90ad279c009e49cc5R133), and if possible squash all commits into a single one?

**Comment by romeof** [comment]
I have removed the extra space in line 133.
For the squas, is it possible for you to do it (it seems so from here https://stackoverflow.com/questions/35948131/github-squash-commits-from-web-interface-on-pull-request-after-review-comments, but please let me know).
I have not found an easy way to do it from LUM online git page.

**Comment by romeof** [comment]
I have tested it and it works

**Comment by mmusich** [comment]
> I have not found an easy way to do it from LUM online git page.

@romeof this PR proposes 8 commits changing 2 files, this clearly not acceptable.
Please find a detailed recipe to perform the squash here (from an `lxplus8` node):

```
cmsrel CMSSW_13_2_X_2023-07-09-2300
cd CMSSW_13_2_X_2023-07-09-2300/src/
cmsenv
git cms-merge-topic 42213
git rebase -i CMSSW_13_2_X_2023-07-09-2300
```

from the interactive prompt git window set the commits as in here:

Screenshot from 2023-07-10 11-53-49


then push:

```
git push git@github.com:CMS-LUMI-POG/cmssw.git +HEAD:master
```

**Comment by romeof** [comment]
thanks Andrea and Marco!
I have tested Marco's comment and it seems to have worked.
Kindly let me know if this is the case.

**Comment by perrotta** [comment]
> thanks Andrea and Marco! I have tested Marco's comment and it seems to have worked. Kindly let me know if this is the case.

Ah, yes. Indeed it worked: thank you!
I see now only one commit, while for some reason I still saw 9 of them when I started writing my alternative instructions.

**Comment by perrotta** [comment]
please test

**Comment by mmusich** [comment]
> Kindly let me know if this is the case.

Hi Francesco, yes it did work

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by civanch** [comment]
please test

again timeout not related to this PR

**Comment by perrotta** [comment]
> again timeout not related to this PR

If you know that it is not related, why do you care?

**Comment by civanch** [comment]
+1

what we should do in this case?

**Comment by perrotta** [comment]
+1

**Comment by mmusich** [comment]
@romeof do we expect also backports of this PR?
@malbouis @jordan-martins

**Comment by malbouis** [comment]
> @romeof do we expect also backports of this PR? @malbouis @jordan-martins

Hi @mmusich , yes, we would like to have backports, specially to 13_0_X
@romeof , would you please go ahead with the backports?

**Comment by mmusich** [comment]
> would you please go ahead with the backports

Since I would like this to be integrated urgently for [this ticket](https://its.cern.ch/jira/browse/PDMVRELVALS-201), I've taken the liberty of opening them:
    * 13.1.X: https://github.com/cms-sw/cmssw/pull/42230
    * 13.0.X: https://github.com/cms-sw/cmssw/pull/42231

**Comment by romeof** [comment]
Marco, do I have to do anything at this point? It seems like you went ahead with the backporting.

**Comment by mmusich** [comment]
> Marco, do I have to do anything at this point?

no, assuming the backport integration goes smoothly, there should not be anything else to do on your side. Thanks!

**Pull request merged**
