### PR TITLE
Simplify definition of `PortableMultiCollection<TDev, ...>`, and allow it to be used outside of `ALPAKA_ACCELERATOR_NAMESPACE`

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

I.e. repeat #43310 on PortableMultiCollection (that was added in https://github.com/cms-sw/cmssw/pull/40285).

#### PR validation:

Unit tests run.

### CODE REVIEW

**Comment by makortel** [comment]
enable gpu

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
@fwyzard @ericcano Any objections? (this PR follows the same pattern as https://github.com/cms-sw/cmssw/pull/43310 did for `PortableCollection` and `PortableObject`)

I suppose this PR should be backported to 14_0_X as well?

**Comment by makortel** [comment]
Comparisons show the usual
* https://github.com/cms-sw/cmssw/issues/39803
* https://github.com/cms-sw/cmssw/issues/43293
* https://github.com/cms-sw/cmssw/issues/43790

**Comment by fwyzard** [comment]
> @fwyzard @ericcano Any objections? (this PR follows the same pattern as #43310 did for `PortableCollection` and `PortableObject`)

No objections from me: I just skimmed through the changes, and I trust you on the design :-) 

> I suppose this PR should be backported to 14_0_X as well?

Yes, please.

(btw, I guess we have already given up on trying to use a single branch for 14.0.x and 14.1.x developments)

**Comment by fwyzard** [comment]
+hetrerogeneous

**Comment by fwyzard** [comment]
+heterogeneous

**Comment by makortel** [comment]
> > I suppose this PR should be backported to 14_0_X as well?
> 
> Yes, please.

Done in https://github.com/cms-sw/cmssw/pull/44014

> (btw, I guess we have already given up on trying to use a single branch for 14.0.x and 14.1.x developments)

I'd assume so too.

**Comment by rappoccio** [comment]
+1

**Pull request merged**
