### PR TITLE
Monitor conversion tracks in tracking validation

### PR DESCRIPTION
**Pull request by makortel**
This PR adds MultiTrackValidator instance to monitor conversion tracks: currently `convStepTracks`, `conversionStepTracks`, `ckfInOutTracksFromConversions`, and `ckfOutInTracksFromConversions` collections.  Tracks from these collections are matched against "conversion TrackingParticles", i.e. electron/positron TrackingParticles (`abs(pdgId) == 11`) that have photon TrackingParticles as their parents (similar to  `PhotonValidator` and `PhotonMCTruthFinder`). A consequence is that a track that is matched to a non-conversion TrackingParticle is classified as a fake.

Plot script will be updated separately (to not to conflict with #12893).

On the same go I modified the seeding+building MTV instances (introduced in #12747) to be harvested only in the tracingOnly mode (where they are present) to silence printouts

```
%MSG-e DQMGenericClient:  DQMGenericClient:postProcessorTrack@endJob  11-Jan-2016 15:49:48 CET PostEndRun
 DQMGenericClient::findAllSubdirectories ==> Missing folder Tracking/TrackSeeding !!!
%MSG
%MSG-e DQMGenericClient:  DQMGenericClient:postProcessorTrack@endJob  11-Jan-2016 15:49:48 CET PostEndRun
 DQMGenericClient::findAllSubdirectories ==> Missing folder Tracking/TrackBuilding !!!
%MSG
```

Tested in CMSSW_8_0_X_2016-01-11-1100, no changes expected in existing plots.

@rovere @VinInn @slava77 @matteosan1

### CODE REVIEW

**Comment by VinInn** [comment]
@cmsbuild, please test

**Comment by cvuosalo** [comment]
@makortel: There are numerous very tiny differences in some Jenkins DQM plots related to `cutsRecoFromPVHp_trackingParticleRecoAsssociation`, in workflow 50202.0 for example.

You said no changes are expected. Might these differences indicate a problem?

**Comment by makortel** [comment]
@cvuosalo All the differences (in 50202.0 and 25202.0) are in `_Mean` and `_Sigma` plots produced by DQMGenericClient in the harvesting step, i.e. numerical differences in fits. The histograms used as an input to the fits show no differences.

@slava77 Since we encounter these every now and then, would it make sense to add an option to `compareValHists.C` to ignore diffBins changes in `X_Mean` and `X_Sigma` if `X` are equal (and e.g. P(KS)=1) and use that in PR tests?

**Comment by slava77** [comment]
On 1/12/16 12:01 PM, Matti Kortelainen wrote:
> @cvuosalo <https://github.com/cvuosalo> All the differences (in 50202.0
> and 25202.0) are in |_Mean| and |_Sigma| plots produced by
> DQMGenericClient in the harvesting step, i.e. numerical differences in
> fits. The histograms used as an input to the fits show no differences.
> 
> @slava77 <https://github.com/slava77> Since we encounter these every now
> and then, would it make sense to add an option to |compareValHists.C| to
> ignore diffBins changes in |X_Mean| and |X_Sigma| if |X| are equal (and
> e.g. P(KS)=1) and use that in PR tests?

The script is not meant to be so smart.

Technically, all fits can change within numerical precision if the
fitter has a memory of the past fits.
So, it can spread beyond MTV plots.

**Comment by cvuosalo** [comment]
+1

For #12909 e8aba6ac53b32b827c9e876f565f282925a7a7c6

Adding monitoring of conversion tracks in tracking validation.

The code changes are satisfactory, and Jenkins [tests](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-12909/10460/summary.html) against baseline CMSSW_8_0_X_2016-01-11-1100 show no significant differences, as expected. The Jenkins DQM plots do show tiny, insignificant differences that are probably due to minor numerical differences in fits, as discussed above.

**Comment by civanch** [comment]
+1

**Comment by makortel** [comment]
Could DQM (@deguio, @vanbesien) please review and sign? Thanks.

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
