### PR TITLE
xml files containing updated summary plot limit + fix for cosmic [Backport combining #19447 and #19713] 

### PR DESCRIPTION
**Pull request by boudoul**
Greetings 
 xml files for the qTests for the DQM PixelPhase1 summary plots and fix for cosmic sequence 

this is the backport of #19447 and #19713 

I combined the two since #19713  is fixing #19447 - Those are already merged in 93X (and even part of 930_pre2) 
 @ckmackay FYI

### CODE REVIEW

**Comment by ckmackay** [comment]
Many thanks, I have unfortunately been away and not caught up with this.
Cheers, Kate
________________________________

**Comment by perrotta** [comment]
please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/19821	13ebe3b
- reco changes are only in RecoTracker/Configuration/python/RecoTrackerP5_cff.py , where a module siPixelClusterShapeCache is added to tracksP5. This is a pre-emptive bugfix to 92X PR #19629 (backport of #19618 which introduced problems in cosmics workflows)
- jenkins tests pass
    - there are no changes in RECO [as expected]
    - there are some changes in "PixelPhase1/Run summary/Summary" and a related summary plot in /EventInfo folder

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
