### PR TITLE
Removed unnecessary deprecated header from L3MuonProducer.cc

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

Part of campaign to remove deprecated headers.

#### PR validation:

Code compiles.

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by missirol** [comment]
+hlt

**Comment by missirol** [comment]
Ping @cms-sw/reconstruction-l2

**Comment by clacaputo** [comment]
+reconstruction

**Comment by perrotta** [comment]
+1

**Pull request merged**
