### PR TITLE
62 slhcdev phase2 tracker digitizer new df

### PR DESCRIPTION
**Pull request by suchandradutta**
Updating TrackerGeometry in Geometry/TrackerGeometryBuilder package adding a feature that given a DetId one can access a ModuleType enumerator  which is defined directly from the name in the geometry xml file 

Updating Phase2TrackerDigitizer with following features
- new data format Phase2TrackerDigi used for the outer tracker detectors (inner PixelDigi is still used for the inner Pixel detectors) 
- removed dependency on StackedTrackerGeometry and the new feature of TrackerGeometry is used instead to identify different types of detectors (PSP, PSS, 2S)

Note : to use this Digitizer in official workflow one needs to update 
- PoolOuputModule definition to include Phase2TrackerDigiedmDetSetVector
- EDAlias definition in SimGeneral/MixingModule/python/aliases_cfi.py should be updated for the Phase2TrackerDigi  as done for PixeDigi

### CODE REVIEW

**Comment by mark-grimes** [comment]
please test

**Comment by suchandradutta** [comment]
I am not  authorized to check error of the test. Please let me know what is the error message.
In my local test I could run the reconstruction up to Digitization level

**Comment by mark-grimes** [comment]
You should be able to see the logs if you have your Cern certificate installed in your browser, but the test output is copied below.  I'm fairly sure this is not because of your PR but need to look into it a bit more.

```
Package Geometry/CommonTopologies: Running test GeometryCommonTopologiesTestDriver
 
===== Test "GeometryCommonTopologiesTestDriver" ====
argument 0: GeometryCommonTopologiesTestDriver
argument 1: /bin/bash
argument 2: Geometry/CommonTopologies/test
argument 3: runTest.sh
shell is: /bin/bash
Current directory is: /tmp/cmsbuild/workspace/ib-any-integration/CMSSW_6_2_SLHCDEV_X_2015-10-18-2300
topdir is: /tmp/cmsbuild/workspace/ib-any-integration/CMSSW_6_2_SLHCDEV_X_2015-10-18-2300
testdir is: /tmp/cmsbuild/workspace/ib-any-integration/CMSSW_6_2_SLHCDEV_X_2015-10-18-2300/src/Geometry/CommonTopologies/test
tmpdir is: /tmp/cmsbuild/workspace/ib-any-integration/CMSSW_6_2_SLHCDEV_X_2015-10-18-2300/tmp/slc6_amd64_gcc472
testbin is: /tmp/cmsbuild/workspace/ib-any-integration/CMSSW_6_2_SLHCDEV_X_2015-10-18-2300/test/slc6_amd64_gcc472
Running script: /tmp/cmsbuild/workspace/ib-any-integration/CMSSW_6_2_SLHCDEV_X_2015-10-18-2300/src/Geometry/CommonTopologies/test/runTest.sh
 testing Geometry/CommonTopologies
----- Begin Fatal Exception 19-Oct-2015 08:44:35 CEST-----------------------
An exception of category 'ConfigFileReadError' occurred while
   [0] Processing the python configuration file named /tmp/cmsbuild/workspace/ib-any-integration/CMSSW_6_2_SLHCDEV_X_2015-10-18-2300/src/Geometry/CommonTopologies/test/python/ValidateRadial_cfg.py
Exception Message:
python encountered the error: <type 'exceptions.Exception'>
no correspondence for startup
available keys are
upgrade2017,upgradePLS3,upgrade2019
----- End Fatal Exception -------------------------------------------------
Vin test tricks do not work
status = 5120

---> test GeometryCommonTopologiesTestDriver had ERRORS
 
^^^^ End Test GeometryCommonTopologiesTestDriver ^^^^
```

**Comment by suchandradutta** [comment]
yes I do not think it is related to my PR. Thank you for sharing the error here

**Comment by mark-grimes** [comment]
The test failure is now understood and not a result of this pull request (see #11984).  I'll run some private checks on this PR.

**Comment by mark-grimes** [comment]
merge

Sorry for delay, only just had time to read through the code.  Happy to overlook `cout` for things in the test directory.

**Pull request merged**
