### PR TITLE
DD4hep:Simulation - DDDWorld Defines Regions and Sets G4 Production Cuts

### PR DESCRIPTION
**Pull request by ianna**
#### PR description:

* DD4hep specific constructor for ```DDG4ProductionCuts```
* During its initialization filter geometry on a key word region and fill in a  ```std::vector<std::pair<G4LogicalVolume*, const cms::DDSpecPar*>>``` 
* Use this to create or retrieve a ```G4Region``` and assign to it ```G4ProductionCuts``` (if they are not already set!). Beware, the cuts defined only once per region. There is no check if they should be overwritten from an extra definition in the xml files.

@civanch - FYI, as discussed during Sim meeting.

#### PR validation:

```
cmsRun SimG4Core/DD4hepGeometry/test/python/testZMM_13TeV_TuneCUETP8M1_cfi_GEN_SIM.py
```
The output is written to simG4test.log

#### if this PR is a backport please specify the original PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by ianna** [comment]
@civanch - please, let me know if I should open a separate PR for the changes (included here) in the ```DetectorDescription/DDCMS``` package. IMHO, they would be useful elsewhere and it would be nice to have them in the IBs asap. Thanks.

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by ianna** [comment]
@civanch - please, let me know when will you be able to review this PR. Thanks.

**Comment by civanch** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
