### PR TITLE
Calo Cell Geometry Migration to Data Formats

### PR DESCRIPTION
**Pull request by ianna**
- Migrate CaloCellGeometry to DataFormats
- Use CaloCellGeometry from DataFormats
- Remove spurious includes

@Dr15Jones and @smuzaffar - Please, review

### CODE REVIEW

**Comment by VinInn** [comment]
I am not sure it does make sense.
Geometry should stay in Geometry.
we can split data from algo, still I would keep them under Geometry
(DataFormats is already plenty of things that Data are not and at most I would start an opposite migration)

**Comment by ianna** [comment]
@VinInn - BTW, it was your PR which pulled in CaloCellGeometry to DataFormats :-)

**Comment by VinInn** [comment]
It pulled in a dependency of few headers.

**Comment by ianna** [comment]
Now these headers reside in DataFormats.

**Comment by Dr15Jones** [comment]
@VinInn the plan is to have a discussion at next week's Core meeting about how to handle the dependencies of DataFormats on specific Geometry classes (and therefore Geometry packages).

**Comment by Dr15Jones** [comment]
@ianna Were the header files you removed just unnecessary includes because those classes were not used in the .cc file or because you could get the class indirectly through another include? I ask since removing unneeded dependencies is great, but we should not be reliant on getting necessary headers via indirect methods.

**Comment by davidlt** [comment]
In the DEVEL IBs one can do `COMPILER=iwyu-cxxcompiler` and it will analyse header dependencies and will suggest what to remove or/and add (of course use your judgement).

**Comment by ianna** [comment]
@Dr15Jones - these were mostly spurious includes. There are many more that can be easily dropped, but I did not want to mix the issues. It looks like many sections of geometry includes were just copy-pasted. I'm  looking into an automated tool to detect these. We used to have something like that a while ago.

**Comment by ianna** [comment]
@davidlt - yes, thanks! That is exactly what I'm looking at :-)

**Comment by ianna** [comment]
@davidlt - are you sure it's set in DEVEL IBs? I get:
```
scram b COMPILER=iwyu-cxxcompiler
****WARNING: You have selected iwyu-cxxcompiler as compiler but there is no iwyu-cxxcompiler-cxxcompiler tool setup. Default compiler gcc-cxxcompiler will be used to comple CXX files
****WARNING: You have selected iwyu-cxxcompiler as compiler but there is no iwyu-cxxcompiler-ccompiler tool setup. Default compiler gcc-ccompiler will be used to comple C files
****WARNING: You have selected iwyu-cxxcompiler as compiler but there is no iwyu-cxxcompiler-f77compiler tool setup. Default compiler gcc-f77compiler will be used to comple F77 files
```

**Comment by ianna** [comment]
@Dr15Jones - FYI, the iwyu results for Geometry are in cmsdev03:/build/yana/test/CMSSW_8_1_DEVEL_X_2016-05-03-1100/src/log.log file
Definitely, some cleanup is needed. I think, it is better to do it centrally rather then passing it to developers.

**Pull request closed without merging**
