### PR TITLE
v17 Partial wafer implementation

### PR DESCRIPTION
**Pull request by Pruthvi-ch**
PR description:

    There will no changes in the output.
    It depends on PR: https://github.com/cms-sw/cmssw/pull/37664
    This is related to partial wafer implementation in v17 for HGCAL, using same placement index notation as full wafers

PR validation:

    Use runTheMatrix test workflows 'runTheMatrix.py -l limited -i all --ibeos'
    Specific cfg's in Geometry/HGCalCommonData/test/python/dumpHGCalWaferPRDDD_cfi.py to dump geometry view using fireworks

if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by AdrianoDee** [comment]
+upgrade

**Comment by perrotta** [comment]
+1

**Pull request merged**
