### PR TITLE
Update stripClusterMCanalysis_cfg.py to run in 8.1.0

### PR DESCRIPTION
**Pull request by wmtford**
Update (to CMSSW_8_1_0) config file for test module stripClusterMCanalysis.  No effect on production.

### CODE REVIEW

**Comment by dmitrijus** [comment]
90x: https://github.com/cms-sw/cmssw/pull/17109

Changes in this PR are slightly different from the upstream one, please align them.

**Comment by wmtford** [comment]
Perhaps you can tell me if what I'm trying to do here conflicts with policy.  The affected file in this PR is a _cfg.py, target of a cmsRun command.  The changes are to catch up with other changes already in 8X (tested specifically in 8_1_0).  My other PR 17109 incorporates a further update needed to run in 9X that is incompatible with 8X.  So the two PRs apply to different releases.

**Comment by dmitrijus** [comment]
> Perhaps you can tell me if what I'm trying to do here conflicts with policy. 
Not really. I will sign it, because you explained the difference and it was something intentional.

In particular, this line is missing from this PR. Usually such difference is a sign of a bug, so I asked for a solution or an explanation.
https://github.com/cms-sw/cmssw/pull/17109/files#diff-c10b7c5bfcc48119da2367ba405eac56R101

**Comment by dmitrijus** [comment]
+1

**Pull request closed without merging**
