### PR TITLE
Use improvements and fixes from 76X

### PR DESCRIPTION
**Pull request by mkirsano**

### CODE REVIEW

**Comment by mkirsano** [comment]
Incompatible with pythia8 205. To be done together with pythia8 upgrade to 212

**Comment by mkirsano** [comment]
To be used together with cmsdist #1896

**Comment by covarell** [comment]
+1

**Comment by mkirsano** [comment]
Should be tested with pythia8 212, cmsdist #1896

**Comment by degano** [comment]
@mkirsano I'm testing this locally against pythia8 212. I don't know why the tests triggered...

**Comment by degano** [comment]
+1
Tested locally against cms-sw/cmsdist#1896, all usual relval passed: 
```
4.22_RunCosmics2011A+RunCosmics2011A+RECOCOSD+ALCACOSD+SKIMCOSD+HARVESTDC Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Wed Oct 14 11:11:35 2015-date Wed Oct 14 11:06:05 2015; exit: 0 0 0 0 0
4.53_RunPhoton2012B+RunPhoton2012B+HLTD+RECODreHLT+HARVESTDreHLT Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED  - time date Wed Oct 14 11:28:18 2015-date Wed Oct 14 11:06:07 2015; exit: 0 0 0 0
5.1_TTbar+TTbarFS+HARVESTFS Step0-PASSED Step1-PASSED  - time date Wed Oct 14 11:10:13 2015-date Wed Oct 14 11:06:11 2015; exit: 0 0
8.0_BeamHalo+BeamHalo+DIGICOS+RECOCOS+ALCABH+HARVESTCOS Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Wed Oct 14 11:12:33 2015-date Wed Oct 14 11:06:12 2015; exit: 0 0 0 0 0
9.0_Higgs200ChargedTaus+Higgs200ChargedTaus+DIGI+RECO+HARVEST Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED  - time date Wed Oct 14 11:26:24 2015-date Wed Oct 14 11:10:23 2015; exit: 0 0 0 0
25.0_TTbar+TTbar+DIGI+RECO+HARVEST+ALCATT Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Wed Oct 14 11:28:18 2015-date Wed Oct 14 11:11:38 2015; exit: 0 0 0 0 0
1306.0_SingleMuPt1_UP15+SingleMuPt1_UP15+DIGIUP15+RECOUP15+HARVESTUP15 Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED  - time date Wed Oct 14 11:20:52 2015-date Wed Oct 14 11:12:40 2015; exit: 0 0 0 0
101.0_SingleElectronE120EHCAL+SingleElectronE120EHCAL Step0-PASSED  - time date Wed Oct 14 11:23:22 2015-date Wed Oct 14 11:21:02 2015; exit: 0
25202.0_TTbar_13+TTbar_13+DIGIUP15_PU25+RECOUP15_PU25+HARVEST+MINIAODMC Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Wed Oct 14 11:45:00 2015-date Wed Oct 14 11:23:27 2015; exit: 0 0 0 0 0
50202.0_TTbar_13+TTbar_13+DIGIUP15_PU50+RECOUP15_PU50+HARVEST+MINIAODMC50 Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Wed Oct 14 11:51:38 2015-date Wed Oct 14 11:26:31 2015; exit: 0 0 0 0 0
1000.0_RunMinBias2011A+RunMinBias2011A+TIER0+SKIMD+HARVESTDfst2+ALCASPLIT Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Wed Oct 14 11:38:59 2015-date Wed Oct 14 11:28:23 2015; exit: 0 0 0 0 0
1001.0_RunMinBias2011A+RunMinBias2011A+TIER0EXP+ALCAEXP+ALCAHARVD Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED  - time date Wed Oct 14 11:35:42 2015-date Wed Oct 14 11:28:26 2015; exit: 0 0 0 0
1003.0_RunMinBias2012A+RunMinBias2012A+RECODDQM+HARVESTDDQM Step0-PASSED Step1-PASSED Step2-PASSED  - time date Wed Oct 14 11:45:32 2015-date Wed Oct 14 11:35:48 2015; exit: 0 0 0
13 12 11 10 6 tests passed, 0 0 0 0 0 failed
```

**Pull request merged**
