### PR TITLE
NanoAOD for 2016 94X re-miniAOD (94X branch)

### PR DESCRIPTION
**Pull request by gpetruc**
Defines a new era `run2_nanoAOD_94X2016` and configures the nanoAOD appropriately:
 * same object IDs as for 2017 94X miniAOD v2 for jets, b-tag, taus
 * E/&gamma; scale and smearing for 2016 legacy re-reco, and storing of both the 2016 and 2017 IDs

### CODE REVIEW

**Comment by gpetruc** [comment]
backport of #24214

**Comment by gpetruc** [comment]
please test

**Comment by gpetruc** [comment]
+1

**Comment by gpetruc** [comment]
please test

**Comment by gpetruc** [comment]
+1
already tested in the nanoAOD integration workflows, but I was waiting for jenkins to conclude before putting the signature.

**Comment by fabiocos** [comment]
+operations

copy of the approved master version, new Era coherent with the purpose of the PR

**Comment by fabiocos** [comment]
+1

**Pull request merged**
