### PR TITLE
Use presamples and sample variables correctly for HF TP

### PR DESCRIPTION
**Pull request by matz-e**
Backport of #18169.

### CODE REVIEW

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by abdoulline** [comment]
@matz-e 
I presume this fix is indispensable for 901 MC production(s)?

**Comment by matz-e** [comment]
@abdoulline This is more for configuring the TP emulation for the DQM following the recent (pre)sample changes online. If we want to keep MC prod completely in sync than this + adjustment of configuration is needed. But I'm not sure that the online parameters are stable now?

**Comment by abdoulline** [comment]
OK, so it's not indispensible for MC (other than to keep all the 
parameters in sync) to deliver correct results at the end, but at some 
point in the future we need to bring all in sync?

**Comment by matz-e** [comment]
@abdoulline Yes, it should be in sync in the future. Currently, we would have to take care of using different parameters when running on MC and reemulating 2017 data, still.

**Comment by davidlange6** [comment]
Closing PR. CMSSW_9_0_X development has completed (CMSSW_9_2_X is for data taking)

**Pull request closed without merging**
