### PR TITLE
bsunanda:Run2-hcx111 Correct CaloTower code to account for merged RecHits due to Plan1

### PR DESCRIPTION
**Pull request by bsunanda**
RecHit for Plan 1 could be a combination of several DetID's and while accessing any condition information it is better be done with the first of the DetId's being used. This is being done in the AssignHit class for HCAL.

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by slava77** [comment]
@bsunanda 
please provide some more details for self-documentation

**Comment by bsunanda** [comment]
@slava77 HBHE RecHit for Plan 1 could be a combination of several DetID's and while accessing any condition information it is better be done with the first of the DetId's being used. This is being done in the AssignHit class for HCAL.

**Comment by bsunanda** [comment]
@slava77 Shall I put it in the code as comment?

**Comment by slava77** [comment]
On 2/17/17 2:00 PM, bsunanda wrote:
> @slava77 <https://github.com/slava77> Shall I put it in the code as comment?

I had in mind the PR description.

"Correct code for plan1" is a bit too cryptic
although we may be in the steps of plan-1 development where it's all
like that ;)

**Comment by davidlange6** [comment]
please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/17555	d07d7e6
- implemented as described for the modified parts (the front deitd is picked for a merged detid tower); relevant only for plan 1 and will not affect other workflows
- jenkins tests pass and comparisons with baseline show no differences

**Comment by davidlange6** [comment]
+1

**Pull request merged**
