### PR TITLE
76x new discriminators

### PR DESCRIPTION
**Pull request by andrewj314**
Updated tau ID discriminators for 13 TeV & MiniAODv2: updated anti-electron ID from MVA5 to MVA6, added new ID discriminators for 13TeV, removed obsolete discriminators, and updated the db used from CMS_COND_PAT_000 to CMS_CONDITIONS

### CODE REVIEW

**Comment by cvuosalo** [comment]
@andrewj314: This PR already has merge conflicts. Can you fix them, or maybe just start over?

**Comment by andrewj314** [comment]
@cvuosalo I started from a clean branch and it seems there are still merge conflicts. Do you know how I can see where the conflicts are?

**Comment by cvuosalo** [comment]
@andrewj314: I think it is in RecoTauTag/Configuration/python/loadRecoTauTagMVAsFromPrepDB_cfi.py.
You can check the conflicts by doing:
```
cmsrel CMSSW_7_6_X_2015-11-05-1100
cd CMSSW_7_6_X_2015-11-05-1100/src
cmsenv
git cms-merge-topic --unsafe 12298
```
Git should issue a message about the conflict.

**Comment by isobelojalvo** [comment]
Hi Carl @cvuosalo ,
I tried cmsrel CMSSW_7_6_X_2015-11-05-1100 on lxplus and our own Wisconsin machines and it states:
"WARNING: Release CMSSW_7_6_X_2015-11-05-1100 is not available for architecture slc6_amd64_gcc472.
         Developer's area is created for available architecture slc6_amd64_gcc493."

Any idea why? I would like to see what is causing the conflict.
Thanks!
Isobel

**Comment by cvuosalo** [comment]
@isobelojalvo: The message seems to say your SCRAM_ARCH is slc6_amd64_gcc472, while it is has to be slc6_amd64_gcc493 for this IB. Also, Wisconsin probably won't have this IB, so you have to get it out of CVMFS or just work from a CERN machine.

**Comment by isobelojalvo** [comment]
@cvuosalo : Yes, thanks that worked! And you're right about where the merge conflict occurred. It's a simple fix; AJ is looking into it.

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by isobelojalvo** [comment]
@andrewj314 this failure seems to be coming from the same portion of code that had the merge issue. I would like to understand why that particular line was added to the config file.

**Comment by cvuosalo** [comment]
@andrewj314: There are merge conflicts now. Please fix them.

**Comment by andrewj314** [comment]
I accidentally pushed before committing and the branch closed - sorry about that. I committed the merge fix and then pushed again which allowed me to reopen the branch - hopefully this did not break anything.

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
@andrewj314: Please add some more detail to the PR description to cover the ~2000 lines of code you're changing.

**Comment by slava77** [comment]
If this changes MINIAOD, the approach is similar to #12216: this should go only to 80X,
unless you can get an approval from physics coordination to have these changes in 76X.

**Comment by andrewj314** [comment]
@cvuosalo Sorry about that! I updated the description
@slava77 Okay, I'll rebase to 8_0_X

**Comment by slava77** [comment]
@andrewj314 
it's not just a rebase: you can't change the target branch in a PR.
So, this one will need to be closed and reopened for 80X.

**Comment by andrewj314** [comment]
@slava77 Okay, sorry about that. I'll start over for 80X

**Pull request closed without merging**
