### PR TITLE
adding customise_reco to recoTR

### PR DESCRIPTION
**Pull request by davidlange6**
to include a call to customise_RECO in postls1customs

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by davidlange6** [comment]
now included in #8218

**Comment by slava77** [comment]
maybe close this one then?

**Comment by davidlange6** [comment]
whoops, I clicked the wrong button before...

**Comment by slava77** [comment]
this postLS1 custom "as is" needs to go to pp part only (not sure about HCAL NZS; cosmics doesn't have PF configured in the same way as pp)

**Pull request closed without merging**
