### PR TITLE
CTPPS pixel: changing clusterizer thresholds

### PR DESCRIPTION
**Pull request by fabferro**
Changing the thresholds for the clusterizer with more appropriate default values

### CODE REVIEW

**Comment by fabferro** [comment]
@fravera @robutti FYI

**Comment by perrotta** [comment]
The effect of the new thresholds is visible in the 2017B data (from jenkins)

- Some 2% increase in the number of clusters:
image

- Cluster energy:
image

**Comment by perrotta** [comment]
+1
- Lower ADC thresholds result in a 2% increase in the number of CTPPS pixel clusters, as it can be expected

**Comment by davidlange6** [comment]
merge

**Pull request merged**
