### PR TITLE
change L1 DQM configuration for stage1

### PR DESCRIPTION
**Pull request by jingyucms**
Due to unsuccessfully rebase of #11293, make a new one to replace #11293.

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by deguio** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by mulhearn** [comment]
+1

**Comment by deguio** [comment]
ciao @davidlange6 @franzoni 
could we have this one signed and merged please?
thanks in advance,
F.

**Pull request merged**
