### PR TITLE
Added likelihood fit to BeamPixel DQM application

### PR DESCRIPTION
**Pull request by dinardo**
I've added a likelihood fit for histograms fitted with a Gaussian.
Before they were fitted with a chi2 method but since there might be empty bins, likelihood is more appropriate.

### CODE REVIEW

**Comment by dmitrijus** [comment]
+1

**Comment by boudoul** [comment]
Hello @dinardo , may I kindly ask you to have a more explicit title ? It will be impossible to understand in the release notes (extensively used by any validators for example) if you are talking about hcal or tracker or GEM or BeamSpot or ..? etc...  maybe you may want to also expand the description as well - Thank you very much.

**Comment by dinardo** [comment]
Hi,
ok it's done.
Please let me know if need to be more explicit.

Cheers,
- Mauro.

**Comment by boudoul** [comment]
Thanks @dinardo for the title & explanations , appreciated.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
