### PR TITLE
ECAL - Remove obsolete classes and modules

### LINKED ISSUE #36: Deprecated ES get function and legacy modules in `Calibration/Tools`
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-5a659a/18900/llvm-analysis/

```
Deprecated API	EventSetupRecord::get function called	/Calibration/Tools/src/TrackAssociator.cc	unknown	104	1	View Report
Deprecated API	EventSetupRecord::get function called	/Calibration/Tools/src/TrackAssociator.cc	unknown	554	1	View Report
Deprecated API	EventSetupRecord::get function called	/Calibration/Tools/src/TrackAssociator.cc	unknown	572	1	View Report
Deprecated API	EventSetupRecord::get function called	/Calibration/Tools/src/TrackAssociator.cc	unknown	97	1	View Report
```

Use of legacy modules: 
```
Deprecated API | inherits from edm::EDProducer,edm::EDFilter,edm::EDAnalyzer, or edm::OutputModule | /Calibration/Tools/plugins/ElectronSqPtTkIsolationProducer.h | ElectronSqPtTkIsolationProducer | 12 | 1 | View Report
Deprecated API | inherits from edm::EDProducer,edm::EDFilter,edm::EDAnalyzer, or edm::OutputModule | /Calibration/Tools/plugins/ElectronSqPtTkIsolationProducer.h | ElectronSqPtTkIsolationProducer | 12 | 1 | View Report

```

### PR DESCRIPTION
**Pull request by thomreis**
#### PR description:

This PR removes obsolete classes and modules that were used in Run 1 for E/p calibration. In Run 2 this work is done by ECALELF instead and therefore the code can be removed.

resolves https://github.com/cms-AlCaDB/AlCaTools/issues/36

#### PR validation:

Passes limited matrix tests.

### CODE REVIEW

**Comment by tvami** [comment]
@thomreis thanks for this! I was wondering, should the content of the SealModule go into the .cc files of the remaining plugins? I think recently it's preferred to get rid of the SealModule.cc

**Comment by tvami** [comment]
@thomreis can you please also include `resolves https://github.com/cms-AlCaDB/AlCaTools/issues/36` in the PR description? Thanks!

**Comment by tvami** [comment]
@cmsbuild , please test
 * let's retest also after SealModule are removed

**Comment by thomreis** [comment]
> @thomreis thanks for this! I was wondering, should the content of the SealModule go into the .cc files of the remaining plugins? I think recently it's preferred to get rid of the SealModule.cc

I would not make a SealModule anymore for a new package but I will leave it for this one since it works as it is now.

**Comment by tvami** [comment]
+alca

**Comment by qliphy** [comment]
+1

**Pull request merged**
