### PR TITLE
HBHEGPU: protection when detector is out

### PR DESCRIPTION
**Pull request by mariadalfonso**
fix issue reported in https://github.com/cms-sw/cmssw/issues/34197

backport of https://github.com/cms-sw/cmssw/pull/34429

### CODE REVIEW

**Comment by mariadalfonso** [comment]
type bugfix

**Comment by mariadalfonso** [comment]
enable gpu

**Comment by mariadalfonso** [comment]
please test

**Comment by perrotta** [comment]
backport of #34429

**Comment by perrotta** [comment]
+reconstruction
- Verified in the master version of this PR that it fixes the HCAL and ECAL local reconstruction eon a GPU when any of those detectors is out
- The fix has no effect on the "normal" workflows when all detectors are present
- Possibly relevant for the release for the MWGR

**Comment by qliphy** [comment]
+1

**Pull request merged**
