### PR TITLE
Fix signed muon tagger

### PR DESCRIPTION
**Pull request by ghost**
Backport of https://github.com/cms-sw/cmssw/pull/12937

Fix in the muon tagger signed discriminators, which were filled always and not only when the signed lepton selection was actually fulfilled.

### CODE REVIEW

**Comment by slava77** [comment]
@imarches 
Will the selector fail only if the sip sign is checked? There seem to be more parameters going into the selector. If this other logic in the selector is included in reco or miniAOD, then this PR is not good for 76X.
Please clarify.

**Comment by imarches** [comment]
@slava77 

Yes, potentially other parameters may enter the selector but with the current set up we always return true here:

https://github.com/cms-btv-pog/cmssw/blob/FixSignedMuonTagger_from-CMSSW_7_6_3/RecoBTag/SoftLepton/src/LeptonSelector.cc#L38

so only the sign is effectively used.

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
+1

For #12956 58019fbe85ee6a3ec5fabb8dfe69168f6edc89e1

Small bug fix to stop the signed muon tagger from being filled unless a signed lepton was actually selected. #12937 is the 80X version of this PR, and it has already been merged.

The code fix is satisfactory, and Jenkins tests against baseline CMSSW_7_6_X_2016-01-15-1100 show no significant differences.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
