### PR TITLE
Improve the memory usage in the alpaka pixel reconstruction [14.0.x]

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

  * Fix the `TrackingRecHitsDevice` constructor:
Fix the `hitsModuleStart` copy to use the correct source (device-to-device instead of host-to-device).
Improve the `offsetBPIX2` copy and use the data member as source, to guarantee the lifetime of the source.
Remove the queue synchronisation.

  * Remove an unused variable from `SiPixelRawToCluster::acquire()`.

  * Improve memory usage in `SiPixelRawToCluster::acquire()`:    
Allocate device memory only when actually used.

  * Use cached memory buffers in `WordFedAppender`.

#### PR validation:

Run the HLT 2024 v1.0 menu with the changes.

#### Backport status

Backported of #44458 to CMSSW 14.0.x for data taking.

### CODE REVIEW

**Comment by fwyzard** [comment]
type bugfix

**Comment by fwyzard** [comment]
enable gpu

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
These changes improve the throughput of the HLT 2024 v1.0 menu with the Pixel alpaka customisation from `587 ev/s` (-3%) to `594 ev/s` (-2%), compared with the CUDA version that achieves `606 ev/s`.

**Comment by mandrenguyen** [comment]
backport of https://github.com/cms-sw/cmssw/pull/44458

**Comment by mandrenguyen** [comment]
+1

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
+heterogeneous

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
