### PR TITLE
Phase2-hgx340X Add a new scenario for a v17-like HGCal layout without the gaps

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Add a new scenario for a v17-like HGCal layout without the gaps

#### PR validation:

Tested this using runTheMatrix.py with the new workflow 26034.0

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by bsunanda** [comment]
@srimanob Please approve this

**Comment by bsunanda** [comment]
@sunilUIET @srimanob Please approve this

**Comment by srimanob** [comment]
test parameters:
- workflow = 26034.0

**Comment by srimanob** [comment]
@cmsbuild please test

When new geometry is added. We should trigger the test of that geometry, to avoid failure in IB.

**Comment by srimanob** [comment]
+Upgrade

Workflow `26034.0_TTbar_14TeV+2026D101` runs fine.

**Comment by perrotta** [comment]
+1

**Pull request merged**
