### PR TITLE
Backport of transient vector fix to CMSSW_7_2_X

### PR DESCRIPTION
**Pull request by andrewj314**
Backport of 7_4_X bugfix: adding ioread rules clearing transient vectors to DataFormats/TauReco/classes_def_2.xml

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/8204	70fa716
the same change was tested and signed off in 74X #8061

**Comment by jpavel** [comment]
Thanks Slava @andrewj314, can you prepare in similar fashion the PR's for 73x and 75x ?

**Comment by slava77** [comment]
Please provide a version for 73X as well

**Comment by slava77** [comment]
The 75X was auto-forward ported already
https://github.com/cms-sw/cmssw/blob/CMSSW_7_5_X/DataFormats/TauReco/src/classes_def_2.xml

@cmsbuild @ktf are the auto-forward-ports active in 73X?

**Comment by jpavel** [comment]
good - I forgot that  auto-forward is active until the 740 release is built :)

**Comment by ktf** [comment]
@slava77 nope.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
