### PR TITLE
Run3-ft24 Bug fix to remove overlap

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Bug fix to remove overlap between beam pipe and BSC2

#### PR validation:

Checked with overlap tool

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
urgent

**Comment by cvuosalo** [comment]
Looks like this one now needs to be backported to 11_1.

**Comment by cvuosalo** [comment]
+1

**Comment by civanch** [comment]
@bsunanda , you need now to backport this PR to 11_1

**Comment by bsunanda** [comment]
@cvuosalo @civanch I have made a back port request in #29963

**Comment by civanch** [comment]
@kpedro88 , please, have a look in this PR and #29963

**Comment by kpedro88** [comment]
+upgrade

**Comment by silviodonato** [comment]
+1

**Pull request merged**
