### PR TITLE
Integration of MvaMET code and tools for miniAOD, cleaning of RecoMET/METPUSubtraction package

### PR DESCRIPTION
**Pull request by ktf**
This PR modifies the mva mitigated MET code in order to make it able to run in top of miniAODs. Cleaning and restructuration of the associated code is also done.

Packages involved :
-DataFormats/METReco : auxiliary structure for the pileup mitigated MET algorithm restructuresd for a common approach

RecoJets/JetProducers : pileup mva jet id now able to work in top of miniAOD, mandatory for the mva MET
RecoMET/METPUSubtraction : rewriting of the NoPU and Mva MET code -> clarity and structure improved, mvaMET able to work in top of miniAOD. NoPU will not due to the limited information available on miniAOD, and it is not planned to go further in that direction.
Changes expected :

reco sequence : no change expected so far, plugin of default mva/nopu algorithm at the RECO/AOD or miniAOD level for a next PR
event content : transparent
difference between the mva MET at AOD and miniAOD level : 1% of events slightly different due to the difference of pfCandidate-vertex matching between both format
difference between previous version and new version : slight difference of the mvaMET results compared to the current version in the release, due to how JEC are handled in the pileup Jet Id mva algorithm for the mvaMET (before was internal, now pileup Jet ID mva is independent, and in sync with other use of the pileup mva jet id)
matrix tests are successfull

Same as #6922 but rebased on top of CMSSW_7_4_X.

### CODE REVIEW

**Comment by slava77** [comment]
the name/subject of the PR should be updated.
In fact, it would be better for Matthieu to just resubmit a new PR
based on this or after merging on top of 74X (an IB >=01-07-1000  should work)just as this one was done.

The reason is that the code review may be not a done deal yet, then fixes will span one more PR

**Comment by mmarionncern** [comment]
Ok, will do it

**Comment by mmarionncern** [comment]
New PR https://github.com/cms-sw/cmssw/pull/7085 , this PR can be closed

**Comment by slava77** [comment]
-1

see #7085

**Pull request closed without merging**
