### PR TITLE
New memory option in runTheMatrix

### PR DESCRIPTION
**Pull request by fabozzi**
Memory option "-m" to set up the Memory parameter of the workflow to a different value than the default. Needed for instance for HI data workflow which requires "-m 12000"

### CODE REVIEW

**Comment by fabozzi** [comment]
please test

**Comment by smuzaffar** [comment]
sorry, in order to get the IB pages recognize latest IBs I had to amend the https://github.com/cms-sw/cmssw/pull/15149/commits/e495908ec8dc510772f0b34865d530bee39cf4cd commit to have message like "Merge CMSSW_8_0_X into CMSSW_8_1_X.". Due to that now to old commit is shows as part of this PR. either ignore it (it is already part of IB) or please rebase based on CMSSW_8_1_X head.

**Comment by fabozzi** [comment]
please test

**Comment by fabozzi** [comment]
@smuzaffar 
rebasing (hope did it right)

**Comment by smuzaffar** [comment]
looks like it did not work. Can you do this
```
git clone --reference /afs/cern.ch/cms/git-cmssw-mirror/cmssw.git  git@github.com:cms-sw/cmssw
cd cmssw
git remote add myrepo git@github.com:fabozzi/cmssw
git fetch myrepo from-CMSSW_8_1_X_2016-07-07-2300_memopt:mychanges
git checkout CMSSW_8_1_X
git checkout -b new-mychanges
git cherry-pick 2491b508f0c5bafb09f02387f6d9f08638547763
git cherry-pick d8c5ca08744f3f151a9da6435f47b38f1d6a41b2
git push -f myrepo new-mychanges: from-CMSSW_8_1_X_2016-07-07-2300_memopt
```

**Comment by fabozzi** [comment]
@smuzaffar 
followed your instructions, thanks!

**Comment by fabozzi** [comment]
please test

**Comment by fabozzi** [comment]
+1

**Comment by davidlange6** [comment]
Hi @fabozzi - could you move the old hard wired default memory value to be part of this new implementation? Eg to give the new flag a valid default

**Comment by fabozzi** [comment]
Hi @davidlange6 - the idea was to have exactly the same hardwired memory when no memory option is specified, i.e.: 3000 for single core, and n-core dependent for multicore (7500 for 4-core).  
We could use as default a dummy "0" value to get this (as it is now in the code). Otherwise, if we want to use a meaningful value as default, we could setup 7500 as default (that will be then valid for single core and multicore).

**Comment by fabozzi** [comment]
please test

**Comment by fabozzi** [comment]
@davidlange6 
implemented the default=0 option

**Comment by fabozzi** [comment]
please test

**Comment by fabozzi** [comment]
please test

**Comment by fabozzi** [comment]
these are DAS errors, not related to this PR

**Comment by fabozzi** [comment]
+1

**Comment by fabozzi** [comment]
please test

**Comment by davidlange6** [comment]
Hi @fabozzi - I really meant to make "3000" the default - but I see its really that two new parameters are needed to do this right --memory (default 3000 ) and (for example) --memPerCore (default 500) - then the code is quite simple. Can you try that?

**Comment by fabozzi** [comment]
please test

**Comment by fabozzi** [comment]
@davidlange6 
thanks for the hint! Now using two parameters.

**Comment by fabozzi** [comment]
+1

**Pull request merged**
