### PR TITLE
[DQM] Apply code-checks/format

### PR DESCRIPTION
**Pull request by smuzaffar**
code-checks/format applied on full cmssw with extra misc-definitions-in-headers clang-tidy check

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by jfernan2** [comment]
I believe all the changes seen in the bin by bin tool are due to #34103 and not to this PR which is technical
However, to be 100% sure I would like to trigger the tests again to decouple

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
