### PR TITLE
add non-empty checks in DAClusterizer to avoid reading null refs

### PR DESCRIPTION
**Pull request by slava77**
to address #44277

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by slava77** [comment]
@cmsbuild please test workflow 11602.0 for CMSSW_14_1_UBSAN_X

**Comment by slava77** [comment]
@cmsbuild please test workflow 11602.0 for CMSSW_14_1_UBSAN_X

**Comment by slava77** [comment]
[step3 log of wf 11602.0](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-2ad74e/37914/runTheMatrix-results/11602.0_SingleElectronPt35+2021/step3_SingleElectronPt35+2021.log) is now clean of the `DAClusterizerInZ`-related issues

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cmsbuild please test workflow 11602.0

**Comment by slava77** [comment]
> * [Reco comparison results: 48 differences found in the comparisons](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_14_1_X_2024-03-05-2300+2ad74e/61544/validateJR.html)
> * DQMHistoTests: [Total failures: 6](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_14_1_X_2024-03-05-2300+2ad74e/61544/validateJR.html)
> 

these are apparently unrelated.

IIUC, the UBSAN issue in this case is mostly false-positive: while the null reference is technically used for a transient value ptr assignment, the values are never used.

**Comment by jfernan2** [comment]
+1

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
