### PR TITLE
2018 HIon HLT menu (103X)

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
2018 HIon HLT menu (103X)
Based on CMSSW_10_3_0_pre6

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
backport #25029

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
abort test

**Comment by Martin-Grunewald** [comment]
please abort test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by Martin-Grunewald** [comment]
@Dr15Jones 
Also sign this backport. Thanks!

**Comment by Dr15Jones** [comment]
+1

**Pull request closed without merging**
