### PR TITLE
[93X] Improvements to L1 Offline DQM - part 3 (issue #19593)

### PR DESCRIPTION
**Pull request by kreczko**
This PR implements the improvements requested in issue #19593 by the L1T team.

@tapperad et all, please have a look

### CODE REVIEW

**Comment by dmitrijus** [comment]
+1

**Comment by kreczko** [comment]
@rekovic @mulhearn please review & sign for L1T

**Comment by rekovic** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Comment by rekovic** [comment]
@kreczko 
Please change title to "[92X] Improvements to L1 Offline DQM - part 3 - backport"

**Pull request merged**
