### PR TITLE
Better handle LS based histos during LS transitions at HLT

### PR DESCRIPTION
**Pull request by danduggan**
Needed to improve performance for LS based histogram handling at the HLT during LS transitions.

### CODE REVIEW

**Comment by danduggan** [comment]
please test

**Comment by danduggan** [comment]
please test

**Comment by davidlange6** [comment]
@danduggan - lets also add this fix in 75x.

**Comment by danduggan** [comment]
+1
thanks @davidlange6 for the suggestion - it's now pushed to both 75x (#11039) and 76x (#11040)

**Comment by davidlange6** [comment]
+1

**Comment by danduggan** [comment]
@davidlange6, just spoke with HLT after their coordination meeting, and ultimately they will not need a patch on top of CMSSW_7_4_8 with this PR. Thanks in any case for being willing to do this.

**Pull request merged**
