### PR TITLE
Make BadHcalMitigation enabled by default

### PR DESCRIPTION
**Pull request by laurenhay**
#### PR description:

Changes have been implemented to make BadHcalMitigation on by default, as requested in issue #30426 and switch the modifier to disable the mitigation.
This deprecates the workflow 136.8643 which is a duplicate of 136.8642 with only hcal mitigation added.
It also deprecates any relval step containing "BadHcalMitig", as this is now automatically on and an extra step to add it is unnecessary. HcalMitigation for the photon and electron are also enabled by default and the corresponding PF modifier is redefined to allow the mitigation to be turned off.

#### PR validation:

These updates were validated through building in CMSSW_11_3_X and by running
``` 
runTheMatrix.py -l limited -i all --ibeos
```

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

@hatakeyamak @rappoccio @bendavid @marksan87

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Review by slava77 — COMMENTED** [review]
RecoParticleFlow/PFClusterProducer/particleFlowBadHcalPseudoCluster_cff.py is empty: is this added by mistake?

**Comment by slava77** [comment]
there is also a conflict in Configuration/StandardSequences/python/Eras.py

**Comment by srimanob** [comment]
I confuse on the description that it should be "on by default", but we have dedicated workflows for it, instead of the general 2018 workflow. In legacy, pf_mitigation is on for all eras,
https://twiki.cern.ch/twiki/bin/view/CMS/PdmVDataReprocessingUL2018#cmsdrivers

**Comment by hatakeyamak** [comment]
@srimanob It was on for all eras of 2018, but not for other years I believe.
The proposal from RECO (@slava77) on #30426 was to enable this globally because in principle this should help for any HCAL dead cells in present and future scenarios.

**Comment by srimanob** [comment]
Ah, OK. I think I read coding so quick and miss the point. Yes, the code makes the PF mitigation on by default and remove extra workflows.

**Comment by srimanob** [comment]
By the way @hatakeyamak @laurenhay 
Will you expect to fix the warning of
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-2e3c12/14201/llvm-analysis/cmsclangtidy.txt
in the later PR, or should it be done here?

**Comment by hatakeyamak** [comment]
Probably @laurenhay can comment on this for this particular code.
I understand @marksan87/@laurenhay will kindly address this for the entire RecoParticleFlow package systematically soon.

**Comment by rappoccio** [comment]
I would handle this as a dedicated migration.

**Comment by laurenhay** [comment]
@slava77 thanks for pointing out the blank replica of PFBadHcalPseudoClusterProducer.cc, it has been deleted and the conflict in Eras.py has been resolved
@srimanob, as @rappoccio and @hatakeyamak mentioned, mark and I were discussing this yesterday as it also came up in his last PR and we plan to address it for the whole package in a future PR

**Comment by srimanob** [comment]
Please test

**Comment by slava77** [comment]
+reconstruction

for https://github.com/cms-sw/cmssw/pull/33413	bbb75f1
- code changes are in line with the PR description and the follow up review
- jenkins tests pass and comparisons with the baseline show differences in PF reco and downstream 
    - there is no change in HI 2018 wf 140.56 as expected (this was apparently the only wf with the mitigation already enabled)

as an example, in RunEGamma2018C wf 136.874 we can see HEM15-16 as the largest effect in a combination of eta and phi for neutral hadrons:
all_OldVSNew_RunEGamma2018Cwf136p874c_recoPFCandidates_particleFlow__reRECO_obj_phi72
all_OldVSNew_RunEGamma2018Cwf136p874c_recoPFCandidates_particleFlow__reRECO_obj_phi79

**Comment by srimanob** [comment]
+Upgrade

Using BadHcalMitigation as default has been discussed since Run-2 UL.

**Comment by chayanit** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
