### PR TITLE
Phase1 (2017) Workflows : Updating Phase1 Tracking Configuration

### PR DESCRIPTION
**Pull request by boudoul**
Keeping the phase1 tracking configuration synchronized with PR #8353  and PR #8393 (CCC and associated HLT changes)
@rovere @VinInn @atricomi @venturia @makortel : FYI

### CODE REVIEW

**Comment by boudoul** [comment]
Please hold on for this PR - I will update it following the comments made in PR#8464 (will do after asap meetings)

**Comment by degano** [comment]
please test

**Comment by boudoul** [comment]
I updated this PR to be synchronized with the PR #8464  (@mtosi, @makortel FYI )

**Comment by makortel** [comment]
@boudoul Looks good, thanks!

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
Gaelle,
do we have already a working Phase-1 matrix workflow?

**Comment by boudoul** [comment]
Hi @slava77 
The Phase1 (2017) Workflows are defined in runthematrix and can be called thanks to the following command;
runTheMatrix.py --what upgrade -l 100xx
The 2017 WFs are still not completely running, (crashing at step3) but getting there.
Once it will work, the goal is to integrate one WF in the IB test, so that the automatic test will run it too.

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/8469	15a829d
all changes are in Phase1 configuration files and do not affect Run1/Run2 worflows.

I checked 10007.0 SingleMuPt10_2017: before the fix it was failing in the config file parsing; after the fix it fails after starting with the 1st event. This is expected and is the part of the work in progress.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
