### PR TITLE
Added monopole ionisation classes

### PR DESCRIPTION
**Pull request by civanch**
In the Geant4 model of monopole ionisation a problem was identified, which is fixed and included into Geant4 development branch. This PR is a backport of the fix, which will be further to SIM production releases. No effect on mainstream simulation is expected.

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by fabiocos** [comment]
@civanch if I understand it correctly, this PR imports a fix to a forthcoming version of Geant4 as CMSSW code, as a temporary workaround. Of course I assume this new model was tested within the Geant4 collaboration, the PR test does not probe anything here, am I correct? Is there a test with this implmenetation?

**Comment by civanch** [comment]
@fabiocos , yes, it is a temporary workaround. The fix is checked and already integrated to the development branch of Geant4. This fix was tested using official Geant4 example "monopole", I personally compare cross sections of delta-electron production for protons and monopoles. It does not change formulas for dEdx and delta-electron x-section (coming from published theoretical papers) but defines safe low-energy limit of delta-electron x-section. CMS classes are renamed copies, which we need to propagate to SIM production releases for Run-2. Current analysis is carried out for 2016 data, so this means we will add back-port to 7_1.

**Comment by fabiocos** [comment]
@civanch so is this the setup that will be available for the UL production? I guess there is no further short term patch foreseen by Geant4

**Comment by fabiocos** [comment]
+1

**Comment by civanch** [comment]
@fabiocos , a patch for exotics may appears at any moment. Just now I am looking into the SIMP generation, which Steven Lowette provided during the weekend. I would guess, we peak it up only for 10_6 if the code is OK?

**Comment by fabiocos** [comment]
@civanch ideally we would like not to touch any more Geant4 after the ongoing validation. But if we speak about specific models for new physics, we might likely be more relaxed. For the time being I integrate this code, if it works we may simply decide to freeze this situation

**Pull request merged**
