### PR TITLE
 Fix unit test in PhysicsTools/UtilAlgos (11_3_X)

### PR DESCRIPTION
**Pull request by silviodonato**
#### PR description:

Backport of #33464

This PR fixes a unit test failure due to a missing input file.

### CODE REVIEW

**Comment by silviodonato** [comment]
please test

**Comment by qliphy** [comment]
+1

**Comment by qliphy** [comment]
to fix the IB issue

**Comment by qliphy** [comment]
merge

**Comment by santocch** [comment]
+1

**Pull request merged**
