### PR TITLE
L1T DQM timing plot upgrades - 102x

### PR DESCRIPTION
**Pull request by thomreis**
Some improvements for the L1T DQM timing plots.

### CODE REVIEW

**Comment by thomreis** [comment]
please test

**Comment by thomreis** [comment]
please abort test

**Comment by thomreis** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by thomreis** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
