### PR TITLE
Phase2-gex70 Add a new scenario D84 same as D70 but with updated tracker T24

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Add a new scenario D84 same as D70 but with updated tracker T24 - to be used for testing Phase2 dd4hep.  D83 is modified to use T24 instead of T21. T24 is identical to T21 but can be used for dd4hep as well as in ddd.

#### PR validation:

Use the runTheMatrix test workflows 37434.0 and 37834.0

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by srimanob** [comment]
test parameters:
- workflows = 37434.0, 37834.0

**Comment by srimanob** [comment]
Please test

**Comment by srimanob** [comment]
Hi @bsunanda 
This PR is not to introduce D84 only, but also modify D83. Could you please update PR title and description? 
- IIUC, you need to see evolution of geometries with the same sub-detectors (work with dd4hep also) except HGCAL
- Do you need also new detector with C15 + T24?

**Comment by bsunanda** [comment]
T21 and T24 are identical except that T24 works for dd4hep while T21 does not. Since D83 is just introduced and there is no usage yet. I like to introduce the change as a bug fix. I am working on the validation package for D83 right now.

**Comment by bsunanda** [comment]
We expect a new tracker version soon. Then we can introduce a new scenario - not before that.

**Comment by bsunanda** [comment]
@srimanob Please look at the comments in this page. I have updated the description. T21 and T24 are identical except that T24 works for dd4hep while T21 does not. Since D83 is just introduced and there is no usage yet. I like to introduce the change as a bug fix. I am working on the validation package for D83 right now. We expect a new tracker version soon. Then we can introduce a new scenario.

**Comment by srimanob** [comment]
+Upgrade

This PR is to
- add new D84 geometry,
- modify D83 to use T24, tracker geometry which works with DD4hep.
Short matrix runs fine with workflows of D83 and D84.

**Comment by chayanit** [comment]
+1

**Comment by silviodonato** [comment]
+operations

**Comment by cvuosalo** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
