### PR TITLE
Dqm hlt object monitor met path update

### PR DESCRIPTION
**Pull request by slehti**
#### PR description:
Solution to JIRA ticket CMSHLT-2764
https://its.cern.ch/jira/browse/CMSHLT-2764

DQM plots empty due to hlt paths not existing any more in the hlt menu. Replaced paths in
HLTObjectMonitor
    HLT_PFMET110_PFMHT110_IDTight -> HLT_PFMET120_PFMHT120_IDTight
HLTObjectsMonitor_EXO
    HLT_PFMET110_PFMHT110_IDTight -> HLT_PFMET120_PFMHT120_IDTight
    HLT_PFMETNoMu110_PFMHTNoMu110_IDTight -> HLT_PFMETNoMu120_PFMHTNoMu120_IDTight
to existing ones.

scram b runtests: pass

Not yet tested.

### CODE REVIEW

**Comment by mmusich** [comment]
type jetmet

**Comment by mmusich** [comment]
test parameters:
   * addpkg = DQM/Integration

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
@slehti 
based on the output of the [tests results](https://github.com/cms-sw/cmssw/pull/43372#issuecomment-1824498614), I see that we have now filed plots (see e.g. https://tinyurl.com/ynk9g9xk).
On the other hand the dedicated ones for HEM/HEP17 are empty, but as far as I can tell, after HCal completed their upgrade in 2018 we don't need to monitor that region specifically. Could you profit of this PR by setting in the JME HLT monitoring configuration the variables `displayInPrimary_pt_HEP17` and `displayInPrimary_pt_HEM17` to false?

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by slehti** [comment]
Setting HEP17/HEM17 booleans to false resulted in runtests to fail. Logs:

Fatal system signal has occurred during exit
/afs/cern.ch/work/s/slehti/Validation/JME/CMSSW_14_0_X_2023-11-21-1100/src/DQM/HLTEvF/test/testTriggerMonitors.sh: line 11: 375341 Abort\
ed                 (core dumped) cmsRun "${SCRAM_TEST_PATH}"/testTriggerMonitors_dqm_cfg.py

Failure running testTriggerMonitors_dqm_cfg.py: status 134

---> test testTriggerMonitors had ERRORS
TestTime:38
^^^^ End Test testTriggerMonitors ^^^^

**Comment by slehti** [comment]
Logged out, logged in, rerun runtests: pass.

**Comment by mmusich** [comment]
@slehti 

> Setting HEP17/HEM17 booleans to false resulted in runtests to fail. Logs:

```
cmsrel CMSSW_14_0_X_2023-11-23-2300/
cd CMSSW_14_0_X_2023-11-23-2300/src/
cmsenv
git cms-merge-topic 43372
scramv1 b -j 20
scram b runtests use-ibeos
```

runs fine for me. I assume it was a glitch in your setup.

**Comment by syuvivida** [comment]
Hi @slehti 
 do you also need to modify these [two lines](https://github.com/cms-sw/cmssw/blob/86b353f585348b883d6b2cca19f1f1e29e11a30d/DQM/HLTEvF/python/HLTObjectsMonitor_EXO_cfi.py#L83-L84)?

**Comment by mmusich** [comment]
> The path names are identical including IDTight, but module names differ. Is this intentional, or should they be the same?

that's intentional as far as I can tell:

https://github.com/cms-sw/cmssw/blob/86b353f585348b883d6b2cca19f1f1e29e11a30d/DQM/HLTEvF/python/HLTObjectsMonitor_EXO_cfi.py#L83-L86

is about PF HT while

https://github.com/cms-sw/cmssw/blob/86b353f585348b883d6b2cca19f1f1e29e11a30d/DQM/HLTEvF/python/HLTObjectsMonitor_EXO_cfi.py#L122-L125

is about PF MET

**Comment by mmusich** [comment]
@slehti 

this relatively simple PR has 6 commits, please consider squashing.

**Comment by slehti** [comment]
Do i need to make a new PR with everything in one commit?

**Comment by mmusich** [comment]
> Do i need to make a new PR with everything in one commit?

no, just force-push on the same branch (after squashing).

**Comment by mmusich** [comment]
@slehti please take a look to http://cms-sw.github.io/tutorial-resolve-conflicts.html

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by slehti** [comment]
Closing this one because of the -1, starting from a fresh table. New PR #43395 where everything is in one commit.

**Comment by mmusich** [comment]
@slehti 

> Closing this one because of the -1

that's not a sufficient reason to close this PR, please reopen this one and close the new one!

**Comment by mmusich** [comment]
+hlt
   * PR in line with the description and the follow-up review

**Comment by mmusich** [comment]
@cms-sw/dqm-l2 your signature is required here. Thank you.

**Comment by syuvivida** [comment]
+1

**Pull request merged**
