### PR TITLE
[DQM] Fix for DQMStore setting assertLegacySafe to false 12_4_X

### PR DESCRIPTION
**Pull request by jfernan2**
#### PR description:

backport of https://github.com/cms-sw/cmssw/pull/38821

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
urgent

**Comment by tvami** [comment]
urgent
 * needed for datataking

**Comment by tvami** [comment]
backport of https://github.com/cms-sw/cmssw/pull/38821

**Comment by emanueleusai** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
