### PR TITLE
Remove ParameterSet usage from CondFormats/L1Trigger

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

The dependency on edm::ParameterSet by L1MuCSCTFConfiguration was not needed. The only piece of code that wants an edm::ParameterSet based on the info stored in that class is CSCTFSectorProcessor.

Removing the dependency fixes problems see in the ROOT module's build plus it is in general a good idea to keep dependencies for CondFormats to a bare minimum.

In addition, *Rcd.h files were found in the /src directory which are duplicates of what is already in CondFormats/Records.

#### PR validation:

The code compiles fine in the regular build and now in the _CXXMODULE_ build.

solves makortel/framework#155

### CODE REVIEW

**Comment by Dr15Jones** [comment]
@davidlange6 FYI

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
please test with #33870

**Comment by makortel** [comment]
> please test with #33870

@Dr15Jones Did you mean #33875?

**Comment by Dr15Jones** [comment]
>Did you mean #33875?

Ops, yes.

**Comment by Dr15Jones** [comment]
please test with #33875

**Comment by Dr15Jones** [comment]
DAS failures are not from this pull request.

**Comment by Dr15Jones** [comment]
please test

**Comment by cecilecaillol** [comment]
+l1

**Comment by ggovi** [comment]
+1

**Comment by Dr15Jones** [comment]
@cms-sw/alca-l2 ping

**Comment by yuanchao** [comment]
+1
* remove edm::ParameterSet dependency.
* matrix tests and unite tests passed
* build warnings not from the modification of the PR

**Comment by qliphy** [comment]
+1

**Pull request merged**
