### PR TITLE
[SIMULATION-UPGRADE] py2/3 compatibility:drop use of __future__

### PR DESCRIPTION
**Pull request by smuzaffar**
see https://github.com/cms-sw/cmssw/issues/46762

### CODE REVIEW

**Comment by civanch** [comment]
+1

**Comment by civanch** [comment]
please test

**Comment by smuzaffar** [comment]
@cms-sw/upgrade-l2 , can you please review this?

**Comment by Moanwar** [comment]
+Upgrade

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
