### PR TITLE
PCL new workflow for High Perf Beamspot, 2017B relval, 2017B HPBS relval (backport)

### PR DESCRIPTION
**Pull request by franzoni**
backport of #19427 
and superseeds #19432

### CODE REVIEW

**Comment by franzoni** [comment]
please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/19669	da371be
- changes are the same as in https://github.com/cms-sw/cmssw/pull/19427	28e30ac; the existing standard matrix workflows are not affected
- jenkins tests pass and comparisons show no differences

**Comment by franzoni** [comment]
+1

**Comment by fabozzi** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
