### PR TITLE
[HGCal] Correcting x-axis in some HGCalValidator plots and layer numbering in V10

### PR DESCRIPTION
**Pull request by apsallid**
#### PR description:

We spotted (@felicepantaleo , @rovere ) two issues in the HGCalValidator and try to address them in this PR: 

1. Efficiency/Duplicates/Fakes/Merges vs eta,phi per layer plots had wrong x-axis labels. 
2. A modifier is introduced to correctly set the total number of layers in case of the HGCal V10 geometry which has two layers less that V9. 

#### PR validation:

To test the changes we created plots for 24005.0 workflow in this [link](http://apsallid.web.cern.ch/apsallid/HGCValidlayerclusters/)

#### if this PR is a backport please specify the original PR:

This is not a backport.

### CODE REVIEW

**Comment by jfernan2** [comment]
Hi @apsallid 
We don't have you identifed as DQM developer in:
https://twiki.cern.ch/twiki/bin/viewauth/CMS/DQMContacts#HGCAL
Could you please add yourself in the corresponding e-group for future references?
Thanks

**Comment by apsallid** [comment]
Hi @jfernan2 
Ok, I just add myself to the e-group.
Thanks.

**Comment by jfernan2** [comment]
please test

**Comment by felicepantaleo** [comment]
@apsallid many thanks for the PR. 
Could you profit from this PR to move `makeHGCalValidationPlots.py` from `python` to `scripts` folder and check that it works out of the box with v10?

**Comment by apsallid** [comment]
@felicepantaleo 
Unfortunately, the `makeHGCalValidationPlots.py` won't work out of the box. In `hgcalPlots.py` I deliberately put these lines [here](https://github.com/cms-sw/cmssw/blob/master/Validation/HGCalValidation/python/hgcalPlots.py#L32-L52) as @kpedro88 suggested, in order to avoid accidental use of the code for one geometry but different layerscheme geometry values. As Kevin said, when this info will be in CMSSW then it will automatically fill the GeneralInfo directory. I hope I haven't miss any development there.

**Comment by felicepantaleo** [comment]
@apsallid I don't understand. Instead of getting the layer scheme for a default named DQM file, you can simply get it from the first DQM file passed to the python script.
If I had to choose if I wanted to make it work with the latest geometry or for the old one, I would choose the new geometry.

**Comment by apsallid** [comment]
@felicepantaleo OK, if I can get a confirmation from reviewers and @kpedro88 I can use the latest V10 values and put the script under scripts.

**Comment by kpedro88** [comment]
Yes, better to move to the newest geometry, since that is being used in the next TDR production (starting very soon)

**Comment by apsallid** [comment]
@kpedro88 @felicepantaleo , 
Thanks a lot, I applied the changes.

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
@apsallid do we understand why for some 14TeV workflows only 104 histograms change while for 29034.0 wf almost 2k are modified?
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_11_0_X_2019-05-26-0000+12ddb4/31917/dqm-histo-comparison-summary.html
Is this expected?

**Comment by apsallid** [comment]
@jfernan2 
Yes, this is because for 29034.0 wf the V10 modifier is activated and the total number of layers changes.

**Comment by jfernan2** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
