### PR TITLE
support global::OutputModule<ExternalWork>

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

Extend the framework to allow edm::global::OutputModule<edm::ExternalWork> to function.

#### PR validation:

Newly added unit test passes. Also tested with a not-yet-committed OutputModule which uses the facility.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by makortel** [comment]
@cmsbuild, please test

Let's try again if results would be cleaner

**Comment by makortel** [comment]
Maybe it is better to wait for next IB to get at least the matrix tests to run...

**Comment by smuzaffar** [comment]
`CMSSW_12_0_X_2021-07-22-1700` IB with the fix should be available in 30 mins . Its `Comparison Baseline`  is currently running, once baseline is available then you can start the tests

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
@cmsbuild, please test

How about now picking a newer IB?

**Comment by makortel** [comment]
+1

The failing unit tests fail in the IBs.

**Comment by Dr15Jones** [comment]
please test

**Comment by makortel** [comment]
The unit tests fail already in the IBs (I would not hold this PR for those)

**Comment by qliphy** [comment]
+1

**Comment by qliphy** [comment]
merge

**Pull request merged**
