### PR TITLE
Allow SoftKiller to run on packed candidates

### PR DESCRIPTION
**Pull request by ahinzmann**
Backport of #7649
SoftKiller is a general pileup removal algorithm.
This pull request enables using packedCandidates instead of PFCandidates as input, such that it can be run on MiniAOD.
The same strategy to handle both inputs as in the PUPPI pileup algorithm is used.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
+1

for [#7667] df6ee3be008019516aa9c8680a719abeef2fdde1

Same change as #7649, except targeted for 7_3_X instead of 7_4_X. This PR involves a very small code change. It is not expected to show any differences from the baseline.

Code changes are satisfactory.

Jenkins tests [CMSSW_7_3_X_2015-02-11-0200] (https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-7667/2516/summary.html):
compilation, unit tests, matrix tests, static checks are all OK.

As expected, there are no significant differences compared to the baseline in the
following:

[alternative-comparisons] (https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_7_3_X_2015-02-11-0200+7667/6017/alternative-comparisons/)
(after stripping false positives like timer data)

and

[validateJR] (https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_7_3_X_2015-02-11-0200+7667/6017/validateJR/)

**Comment by monttj** [comment]
@ahinzmann Do you have the PR for 74X as well?

Thank you,
Taejeong

**Comment by ahinzmann** [comment]
yes, it is linked in the description: #7649

**Comment by monttj** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
