### PR TITLE
New GTs for 75X: adding V4 stage1 L1 menu + rolling back 75X BTV training

### PR DESCRIPTION
**Pull request by mmusich**
# List of Changes
- Run1 Ideal Simulation `75X_mcRun1_design_v2`: as [75X_mcRun1_design_v3](https://cms-conddb.cern.ch/browser/#diff/gts/75X_mcRun1_design_v3/75X_mcRun1_design_v2) with:
  - updated training of b-tagging discriminators.
- Run1 Realistic Simulation `75X_mcRun1_realistic_v2` as: [75X_mcRun1_realistic_v3](https://cms-conddb.cern.ch/browser/#diff/gts/75X_mcRun1_realistic_v3/75X_mcRun1_realistic_v2) with:
  - updated training of b-tagging discriminators.
- Run1 Heavy Simulation `75X_mcRun1_HeavyIon_v2` as: [75X_mcRun1_HeavyIon_v3](https://cms-conddb.cern.ch/browser/#diff/gts/75X_mcRun1_HeavyIon_v3/75X_mcRun1_HeavyIon_v2) with:
  - updated training of b-tagging discriminators.
- Run1 proton-Lead Simulation `75X_mcRun1_pA_v2`: as [75X_mcRun1_pA_v3](https://cms-conddb.cern.ch/browser/#diff/gts/75X_mcRun1_pA_v3/75X_mcRun1_pA_v2) with:
  - updated training of b-tagging discriminators.
- Run2 startup Simulation `75X_mcRun2_startup_v2`: as  [75X_mcRun1_startup_v3](https://cms-conddb.cern.ch/browser/#diff/gts/75X_mcRun2_startup_v2/75X_mcRun2_startup_v3) with:
  - updated training of b-tagging discriminators.
- Run2 Ideal Simulation `75X_mcRun2_design_v4`: as [75X_mcRun2_design_v3](https://cms-conddb.cern.ch/browser/#diff/gts/75X_mcRun2_design_v4/75X_mcRun2_design_v3) with:
  - updated training of b-tagging discriminators;
  - updated v4 version of  25ns stage1 L1 menu.
- Run2 asymptotic Simulation `75X_mcRun2_asymptotic_v4`: as [75X_mcRun1_asymptotic_v3](https://cms-conddb.cern.ch/browser/#diff/gts/75X_mcRun2_asymptotic_v4/75X_mcRun2_asymptotic_v3) with:
  - updated training of b-tagging discriminators;
  - updated v4 version of  25ns stage1 L1 menu.
- Run2 Heavy Ion Simulation `75X_mcRun2_HeavyIon_v2`: as [75X_mcRun1_HeavyIon_v3](https://cms-conddb.cern.ch/browser/#diff/gts/75X_mcRun2_HeavyIon_v3/75X_mcRun2_HeavyIon_v2) with: 
  - updated training of b-tagging discriminators.
- Run2 data HLT processing `75X_dataRun2_HLT_frozen_v2`: as [75X_dataRun2_HLT_v1](https://cms-conddb.cern.ch/browser/#diff/gts/75X_dataRun2_HLT_frozen_v2/75X_dataRun2_HLT_v1) with:
  - updated training of b-tagging discriminators.
  - **features closed snapshot time** (as is meant for relvals)
- Run1 data HLT processing `75X_dataRun1_HLT_frozen_v2`: as [75X_dataRun1_HLT_v1](https://cms-conddb.cern.ch/browser/#diff/gts/75X_dataRun1_HLT_frozen_v2/75X_dataRun1_HLT_v1) with:
  - updated training of b-tagging discriminators;
  - **features closed snapshot time** (as is meant for relvals)
- Run2 data offline processing `75X_dataRun2_v4`: as [75X_dataRun2_v2](https://cms-conddb.cern.ch/browser/#diff/gts/75X_dataRun2_v4/75X_dataRun2_v2) with:
  - updated training of b-tagging discriminators.
  - taxonomy change of the SiPixelGenErrorDBObject for 3.8T tag;
  - different snapshot time to make changes to CSC conditions to be visible.
- Run1 data offline processing `75X_dataRun1_v4`: as [75X_dataRun1_v2](https://cms-conddb.cern.ch/browser/#diff/gts/75X_dataRun1_v4/75X_dataRun1_v2) with:
  - updated training of b-tagging discriminators;
  - taxonomy change of the SiPixelGenErrorDBObject for 3.8T tag;
  - different snapshot time to make changes to CSC conditions to be visible.
- Phase-I 2017 simulation scenario `75X_upgrade2017_design_v1`: as [75X_upgrade2017_design_v0](https://cms-conddb.cern.ch/browser/#diff/gts/75X_upgrade2017_design_v1/75X_upgrade2017_design_v0)
  - updated training of b-tagging discriminators.`

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by Martin-Grunewald** [comment]
I do not see the startup GT with the v4 L1T menu in the above description... ?

**Comment by Martin-Grunewald** [comment]
Also, what about 76X?

**Comment by mmusich** [comment]
was v4 meant for startup?

**Comment by mmusich** [comment]
76X is coming

**Comment by Martin-Grunewald** [comment]
Ah, sorry, if startup == 50ns, then no!

**Comment by mmusich** [comment]
@Martin-Grunewald startup == 50ns in autocond. Currently you have there: `L1Menu_Collisions2015_50nsGct_v4`. Should be good right?

**Comment by mmusich** [comment]
hmmm in local test I get this error in the run2_mc workflow (`runTheMatrix.py -l 1330.0`):
```
Begin processing the 1st record. Run 1, Event 1, LumiSection 1 at 11-Aug-2015 14:34:48.708 CEST
----- Begin Fatal Exception 11-Aug-2015 14:34:59 CEST-----------------------
An exception of category 'FailModule' occurred while
   [0] Processing run: 1 lumi: 1 event: 1
   [1] Running path 'HLT_L2Mu10_NoVertex_NoBPTX3BX_NoHalo_v2'
   [2] Calling event method for module HLTLevel1GTSeed/'hltL1sMuOpenNotBptxOR'
Exception Message:

Algorithm  L1_SingleMu6_NotBptxOR, requested as seed by a HLT path, not found in the L1 trigger menu
   L1Menu_Collisions2015_25nsStage1_v4/L1T_Scales_20141121/Imp0
Incompatible L1 and HLT menus.

----- End Fatal Exception -------------------------------------------------
Another exception was caught while trying to clean up files after the primary fatal exception.
11-Aug-2015 14:34:59 CEST  Closed file file:step1.root
```

**Comment by Martin-Grunewald** [comment]
Yes, for 50ns!

Now, the jenkins tests fail because the HLT menus currently in the release work with the old L1T menu,
but we will update them with the new HLT menus needing the new L1T menus. IOW, we need a combined PR. I can add your/this PR (as it is only 1 file) to mine (and you promise
you'll sign for the additional signature :)

**Comment by mmusich** [comment]
@Martin-Grunewald, sure just cherry-pick my commit, I'll sign it.

**Comment by Martin-Grunewald** [comment]
Hi Marco, 
I have put this (by hand as cherry pick did not recongize the commit) into the big HLT PR for 75X, https://github.com/cms-sw/cmssw/pull/10534
What is the status for 76X?
Thanks

**Comment by diguida** [comment]
@Martin-Grunewald working on 76X queues...

**Comment by mmusich** [comment]
@Martin-Grunewald for what concerns the cherry-pick:
```
git cms-addpkg Configuration/AlCa
git remote add mmusich https://github.com/mmusich/cmssw.git
git fetch mmusich
git cherry-pick 6110521283a69aa0ccc097b0f44325b5b74156e7
```
should have worked

**Comment by Martin-Grunewald** [comment]
Ah, I only tried the last command.

**Comment by mmusich** [comment]
superseded by  #10534. Going to close it

**Pull request closed without merging**
