### PR TITLE
DD ExprAlgo Merge with Core

### PR DESCRIPTION
**Pull request by ianna**
* DD ExprAlgo package cleanup
* Move remaining class to DD Core package

Note: it is based on https://github.com/cms-sw/cmssw/pull/19093 PR

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/19106	3ba21e2
- technical; for reco category packages this PR is the same as https://github.com/cms-sw/cmssw/pull/19093 bdf08d0 (and contains the #19093 commit)
- jenkins tests pass

**Comment by civanch** [comment]
+1

**Pull request merged**
