### PR TITLE
Add variables to StoppedParticles 75X

### PR DESCRIPTION
**Pull request by jalimena**
Add pdgId, mass, and charge to StoppedParticles, remove an extraneous mDebug parameter, and add the additional variables to RHStopDump.

### CODE REVIEW

**Comment by jalimena** [comment]
These additional variables will be helpful for the two long-lived exotica searches that use the StoppedParticles, and it will make it easier to debug possible problems in the future. This PR is in addition to the bug fix of #8282, which was the minimum needed to fix the problem.

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
