### PR TITLE
Add bx skim and corresponding RelVal

### PR DESCRIPTION
**Pull request by kfjack**
#### PR description:

This PR includes the proposal of BunchCrossingSkim PR #26419 and the corresponding updates for RelVal. This is for the master branch.

#### PR validation:

RelVal workflows are added to 2018E HLTPhy and ZeroBias. Given the special situation of the BunchCrossingSkim the RelVal has only SKIM part, without RECO and other steps. 
The corresponding workflows are
136.899
136.900

### CODE REVIEW

**Comment by fabiocos** [comment]
please test workflow 136.899,136.900

**Comment by kfjack** [comment]
Hi all, it seems that I cannot remove RECO steps from the relval (the comparison cannot be performed), even it is not really needed for this special skim. Will try to add them back and see if it is functioning...

**Comment by kfjack** [comment]
Hi all, I added RECO steps back. Need to recheck the two workflows again: 
136.899
136.900

**Comment by fabiocos** [comment]
@kfjack what is the status of this PR?

**Comment by kfjack** [comment]
Hi @fabiocos I think this PR is not really functioning. No idea how to move ahead.

i) The bunch crossing skim itself does not require RECO steps, so my first attempt in the RelVal did not include RECO steps. Although the test can be run locally, but the standard RelVal tests cannot be fully established without RECO information.

ii) I tried to add the RECO steps back, but the process failed. I'm not able to figure out exactly the reason why the RECO steps cannot be run with this RelVal. Probably due to the special condition of 2018E or so.

**Comment by kpedro88** [comment]
please test
(since old comparisons were deleted and I've forgotten the exact error message)

**Comment by kpedro88** [comment]
please test workflow 136.899,136.900

**Comment by kpedro88** [comment]
For future reference, the error is:
```
----- Begin Fatal Exception 22-May-2019 15:37:54 CEST-----------------------
An exception of category 'NoProxyException' occurred while
   [0] Processing  Event run: 325594 lumi: 1 event: 16371 stream: 0
   [1] Running path 'Flag_METFilters'
   [2] Prefetching for module BooleanFlagFilter/'HBHENoiseFilter'
   [3] Prefetching for module HBHENoiseFilterResultProducer/'HBHENoiseFilterResultProducer'
   [4] Prefetching for module HcalNoiseInfoProducer/'hcalnoise'
   [5] Prefetching for module FastjetJetProducer/'ak4PFJets'
   [6] Prefetching for module PFLinker/'particleFlow'
   [7] Prefetching for module PFProducer/'particleFlowTmp'
   [8] Prefetching for module PFBlockProducer/'particleFlowBlock'
   [9] Prefetching for module PFElecTkProducer/'pfTrackElec'
   [10] Prefetching for module GsfTrackProducer/'electronGsfTracks'
   [11] Prefetching for module MeasurementTrackerEventProducer/'MeasurementTrackerEvent'
   [12] Prefetching for module JetCoreClusterSplitter/'siPixelClusters'
   [13] Prefetching for module PrimaryVertexProducer/'firstStepPrimaryVerticesPreSplitting'
   [14] Calling method for module TrackProducer/'initialStepTracksPreSplitting'
   [15] Using EventSetup component TkTransientTrackingRecHitBuilderESProducer/'TTRHBuilderAngleAndTemplate' to make data TransientTrackingRecHitBuilder/'WithAngleAndTemplate' in record TransientRecHitRecord
   [16] Using EventSetup component PixelCPEClusterRepairESProducer/'templates2' to make data PixelClusterParameterEstimator/'PixelCPEClusterRepair' in record TkPixelCPERecord
   [17] Using EventSetup component SiPixel2DTemplateDBObjectESProducer/'siPixel2DTemplateDBObjectESProducer' to make data SiPixel2DTemplateDBObject/'' in record SiPixel2DTemplateDBObjectESProducerRcd
Exception Message:
No data of type "SiPixel2DTemplateDBObject" with label "0T" in record "SiPixel2DTemplateDBObjectRcd"
 Please add an ESSource or ESProducer to your job which can deliver this data.
----- End Fatal Exception -------------------------------------------------
```

It could take significant work to make the full RECO step cooperate with this special scenario. To make comparison plots, really it's the DQM step that is needed, but I doubt this can run easily without the preceding RECO step.

If there is sufficient interest in studying the data from these runs, we can try to introduce a specific Modifier like run2_2018_highPU, in order to remove/modify pieces of the RECO step that don't work. But I am not sure exactly how much work this would take.

**Comment by fabiocos** [comment]
@kfjack what is the plan about this PR? Is there activity, or it can be just closed for the time being?

**Comment by kfjack** [comment]
Hi @fabiocos I think we shall close this PR for the time being as well. If all agree I'll close it.

**Pull request closed without merging**
