### PR TITLE
sync OMTF code (as in tag omtfdev_mk20).

### PR DESCRIPTION
**Pull request by rekovic**
PR 10_3_X
Changes includes:
 - fix for missing CSC offset in raw to digi in (in packer and unpacker)
 - fixed mem leaks
 - emulator: allow for emulator reconstruction in bx other than 0.
 - emulator: new omtf algorithm (sc-called v5, compatible with the one prepared for P5 running);
   the new algo is planned to be enabled by o2o with omtf algo key 'omtf_algo_base/v4';
   until then old algorithm is enabled.  
 - emulator: new omtf algorithm v6 which improves eta assignment w.r.t. v5
The above changes in packer/unpacker and algorithm in emulator is only affecting re-emulation of data (DQM offline/online) and not effecting MC production.  Change in emulator does not effect MC production since the MC Global Tag is not updated.

### CODE REVIEW

**Comment by rekovic** [comment]
please test

**Comment by rekovic** [comment]
please test

**Comment by rekovic** [comment]
+1

**Comment by fabiocos** [comment]
@rekovic I see that not only 2018 workflows are affected (136.85) but also 2017 ones (136.788). Is this intended?

**Comment by fabiocos** [comment]
@rekovic could you please answer my question? I would like to merge this PR, but I would like to be sure that the DQM checks are understood

**Comment by rekovic** [comment]
@fabiocos Yes, this will affect re-emulation of both 2017 and 2018 data.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
