### PR TITLE
Trigger Filter Bit fixes for Run 3 (Tau Trigger Objects)

### PR DESCRIPTION
**Pull request by Ksavva1021**
PR description:
This PR fixes the trigger filter bits for Run 3 to allow proper matching between online and offline tau trigger objects.

PR validation:
All filter bits were checked to ensure all the correct filters are selected. Code was checked to make sure, filter bits were not altered for Run 2 by these modifications as expected. Checked that the code stored the filter bits for Run 3 samples.

If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:
This PR is a backport of https://github.com/cms-sw/cmssw/pull/43453

@mbluj @cardinia @danielwinterbottom

### CODE REVIEW

**Comment by vlimant** [comment]
please test

**Comment by vlimant** [comment]
+1

**Comment by danielwinterbottom** [comment]
Hello @rappoccio, @sextonkennedy, @antoniovilela can you please check this PR so it can be merged? - the deadline to have it merged for the nano v13 production is today. I understand that the backports are usually discussed in the release meeting but I think this is cancelled today due to CMS week.

**Comment by jordan-martins** [comment]
Hi guys,

In the scope of the nanov13 (133X) closure, we would like to have this merged. Could you kindly consider this PR asap, please? We need to close the nanov13 dev for (initially) the H->GG analysis.

Thanks,
PPD

**Comment by rappoccio** [comment]
+1

**Pull request merged**
