### PR TITLE
fix LHERunInfoProduct duplication (backport)

### PR DESCRIPTION
**Pull request by perrozzi**
backport of https://github.com/cms-sw/cmssw/pull/18846

### CODE REVIEW

**Comment by perrozzi** [comment]
please test

**Comment by perrozzi** [comment]
+1

**Comment by alberto-sanchez** [comment]
@davidlange6 can this be merged?

**Comment by davidlange6** [comment]
hi @alberto-sanchez - is this one tested in one of the GEN relvals of 9_2_1?

**Comment by perrozzi** [comment]
this is the 71x backport and it has been tested heavily

**Pull request merged**
