### PR TITLE
Remove obsolete customiseForRunI

### PR DESCRIPTION
**Pull request by makortel**
With the introduction of `trackingLowPU` sub-era in #13988 the old (currently non-functional) `customiseForRunI` became obsolete. This PR removes all files related to `customiseForRunI` as well as all uses of those files. There were couple of places where a simple removal of the use was clearly not correct behaviour. Those places throw now an exception asking to use `trackingLowPU` (they would anyway need some refurbishing to get them to working state).

Tested in CMSSW_8_1_X_2016-04-24-0000, no changes expected in standard workflows.

@rovere @VinInn @slava77

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by makortel** [comment]
I was a bit afraid of that failure (and was surprised that I didn't observe it in my local tests first, I can reproduce it now though).

@slava77 Please advise what to do. Naively I would think to replace "ppRun2B0T" with "ppEra_Run2_2016_trackingLowPU" in https://github.com/cms-sw/cmssw/blob/CMSSW_8_1_X/Configuration/DataProcessing/test/run_CfgTest.sh. Which reminds me, is the DataProcessing part of #13945 (introducing "ppEra_Run2_2016_trackingLowPU" scenario) already in 81X?

**Comment by slava77** [comment]
@makortel 
the DataProcessing was not updated yet
So, this PR will have to wait (can be a few days).
If this cleanup is urgent, I can suggest you edit run_CfgTest.sh and remove ppRun2B0T

**Comment by makortel** [comment]
@slava77 It's not urgent. I just got reminded of these while grepping something else and I thought to do the cleanup now so that eventually the obsolete stuff would get away (from my greps).

**Comment by slava77** [comment]
#14350 was just merged 
It triggered conflicts due to overlapping changes in RecoTLR.
@makortel please rebase.

**Comment by makortel** [comment]
@slava77 IIUC it should be enough that I drop the changes in RecoTLR from this PR, right? (I'm trying to avoid waiting for the next IB, i.e. essentially until Monday in this case)

**Comment by slava77** [comment]
@makortel 
if all the conflicts are with #14350, then yes, just drop RecoTLR changes.
This will probably not need a rebase then.

**Comment by makortel** [comment]
@slava77 I removed the RecoTLR changes from the first commit (the three subsequent ones are exactly the same as before, sorry for taking the history-editing route but I think it was the clearest in this case).

**Comment by slava77** [comment]
@cmsbuild please test

@makortel 
your modifications worked out. No merge conflicts now.

**Comment by slava77** [comment]
uhm, I guess I asked for the jenkins test too early. It will not include #14350 yet and the DP unit test will still fail

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/14267	a003f68
- code changes are as described
- jenkins tests pass and comparisons with baseline show no differences

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
