### PR TITLE
Updating HLT DQM and validation for Hgg paths

### PR DESCRIPTION
**Pull request by mplaner**
This is the 92X version of PR #19023

### CODE REVIEW

**Comment by mtosi** [comment]
@cmsbuild, please test

**Comment by dmitrijus** [comment]
How can this be a backport if it contains three times as much as there are changes in https://github.com/cms-sw/cmssw/pull/19023 ?

**Comment by mplaner** [comment]
@dmitrijus As far as I can tell, the issue is that several other PRs which are currently in 93X don't exist in 92X.  So, for instance, we have to add in the "new" DQMOffline/Trigger/plugins/PhotonMonitor.cc and DQMOffline/Trigger/plugins/PhotonMonitor.h.  

But for the 93X PR, those files already existed and I simply had to add a few lines.

I'm not sure what the correct procedure should be.  I opted to keep the changes as minimal as possible, but I included what I needed from the PR.  So, they should only need to add in some python configs to run their DQM in 92X.

**Comment by dmitrijus** [comment]
The correct and desirable procedure would be to find the PR (in 93x) which extracted those extra files. Once you find this PR, you backport that PR either together or separately from this. Maybe there is already a pull request which backports it too.

Copying files around is the worst you can do. This way you destroy the integrity of the PR which introduced them.

**Comment by mplaner** [comment]
Okay, do we have some official documentation for this?  My main hesitation is that the PRs contain code for DQM plots which I can't properly validate.  If I submit the backport for PRs from others, I can't guarantee the code I didn't write is working correctly.  

Is there a reasonable way to search through the pending PRs to see if these changes have been requested already?

**Comment by mplaner** [comment]
@dmitrijus, I have found the only relevant PR and rebased with it (#19520).  It wasn't in last night's integration build, but I think my rebasing should allow things to work smoothly.  

Let me know if this doesn't follow best practices.

**Comment by dmitrijus** [comment]
How did you rebase? should have been "git-cms-merge topic 19520" followed by your commits.
Ideally, maybe the best solution is to wait until #19520 is merged and then do the proper rebase.

**Pull request closed without merging**
