### PR TITLE
New muon validation fixes

### PR DESCRIPTION
**Pull request by abbiendi**
These are fixes to the New muon validation, determined after checks of few relevant workflows.
Comparison plots of New vs production validation are visible here:
https://cmsdoc.cern.ch/cms/Physics/muon/CMSSW/Performance/RecoMuon/Validation/val/test_NewValidation/
All the visible features are expected, due to the new validation.
In addition it synchronizes the New validation with concurrent changes in the production version.

### CODE REVIEW

**Comment by abbiendi** [comment]
Few more details.
The tested workflows should cover all the possible cases. They are:
- ZMM 13 TeV no PU (1330.0)
- ZMM 13 TeV with PU25ns (25206.0)
- ZEEMM_13 Heavy Ions (140.4)
- TTbar 13 TeV FastSim (135.1)
- Phase2 Single Mu pt100 "2023D4Timing" (22808.0)
To produce them with the New validation activated (in place of the current one):
runTheMatrix.py -l 1330.0,25206.0,140.4,135.1 --command="--customise=Validation/RecoMuon/customiseForNewMuonValidation.enableNewMuonVal"
runTheMatrix.py -w upgrade -l 22808.0 --command="--customise=Validation/RecoMuon/customiseForNewMuonValidation.enableNewMuonVal"
These is the minimal set of workflows that should be tested before switching to the New validation. Probably a few more could be added (as a single muon gun in Run2 configuration).

**Comment by dmitrijus** [comment]
+1

**Comment by abbiendi** [comment]
just to make it clear: this PR is necessary to move on with the agreed plan towards the transition to the New validation.
After it is merged in 91X we will ask for backport in 90X to finalize the benchmark comparisons in a stable release. 
The comparison with the Old (current) will need to activate the New validation in a few RelVal workflows (min set >= those tested here).

**Comment by abbiendi** [comment]
Hi, about the above comparison summary: there cannot be any sensible difference if (as I assume) the tested workflows are all standard ones, given that my changes here concern only the New muon validation, which has to be enabled by a customization.

**Comment by davidlange6** [comment]
+1
(though no plans to back port this in its current form)

**Pull request merged**
