### PR TITLE
Fix bug in TICLLayerTileProducer.

### PR DESCRIPTION
**Pull request by wddgit**
#### PR description:

Fix bug in TICLLayerTileProducer. The LogDebug statement could access the object pointed to by results when results is not filled. This potentially could cause a seg fault. Issue #42470 reports a seg fault in that part of the code. This bug might or might not be the cause of that seg fault. I did not verify the connection, but the bug should be fixed irregardless. We can monitor the IBs after this PR is merged to see if that failure stops occurring.

This also modifies the module to only call consumes and construct the results object corresponding to the chosen option, a minor optimization.

#### PR validation:

Relies on existing tests.

### CODE REVIEW

**Comment by wddgit** [comment]
please test

**Comment by mandrenguyen** [comment]
type bug-fix, hgcal

**Comment by felicepantaleo** [comment]
Thanks a lot, David.
Symbolic +1 from hgcal reco.

**Comment by srimanob** [comment]
+Upgrade

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
