### PR TITLE
clang check readability-delete-null-pointer

### PR DESCRIPTION
**Pull request by davidlange6**
for comment about what clang-tidy does to CMSSW (and likely big and not mergeable - this is what clang-tidy check readability-delete-null-pointer does on the tip of CMSSW_9_3_X as of a few days ago

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
please test

**Comment by VinInn** [comment]
something went really wrong with the script that made the cleanup...

**Comment by davidlange6** [comment]
it looks like this  clang-tidy test gets confused by a comparison of a pointer to an int. Those are all incorrectly done.

**Comment by slava77** [comment]
-1

looks mostly OK, but the editing script is apparently buggy

**Pull request closed without merging**
