### PR TITLE
Castor online dqm updated config 73x

### PR DESCRIPTION
**Pull request by iik1997**
Changes introduced (and already tested on an online machine) in order to re-enable Castor online DQM

### CODE REVIEW

**Comment by iik1997** [comment]
@popovvp

**Comment by deguio** [comment]
+1

**Comment by danduggan** [comment]
@iik1997. this needs a rebase to be consistent with the changes from #7601.

**Comment by danduggan** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
