### PR TITLE
TeV jet RAW-RECO skim (backport) 

### PR DESCRIPTION
**Pull request by lathomas**
Backport of https://github.com/cms-sw/cmssw/pull/43581
FYI @jordan-martins @malbouis

### CODE REVIEW

**Comment by malbouis** [comment]
Hi @lathomas , thanks a lot for this backport! I think it is a backport from PR #43581, right?

**Comment by lathomas** [comment]
Indeed ! Corrected.

**Comment by AdrianoDee** [comment]
please test

**Comment by AdrianoDee** [comment]
+1

**Comment by rappoccio** [comment]
+1

**Pull request merged**
