### PR TITLE
[GT Updates] for HCAL MCParams, RecoParams and SiPM Params for 2018 and fix of 2019 HCAL Electronics maps

### PR DESCRIPTION
**Pull request by arunhep**
# Summary of changes in Global Tags 
 
## Upgrade 
 
   * **PhaseI 2018 cosmics scenario** : [100X_upgrade2018cosmics_realistic_deco_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/100X_upgrade2018cosmics_realistic_deco_v3) as [100X_upgrade2018cosmics_realistic_deco_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/100X_upgrade2018cosmics_realistic_deco_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/100X_upgrade2018cosmics_realistic_deco_v3/100X_upgrade2018cosmics_realistic_deco_v1): 
      * update of HCAL MC, reco parameters and SiPM charachaterstics to update the parameters with new pulse shapes from PR #21168
      * update of HCAL LUTs : https://indico.cern.ch/event/681303/contributions/2814276/attachments/1570886/2478122/HCAL_Alca_20171206.pdf too support PR #21657

   * **PhaseI 2018 design scenario** : [100X_upgrade2018_design_IdealBS_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/100X_upgrade2018_design_IdealBS_v3) as [100X_upgrade2018_design_IdealBS_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/100X_upgrade2018_design_IdealBS_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/100X_upgrade2018_design_IdealBS_v3/100X_upgrade2018_design_IdealBS_v1): 
      * update of HCAL MC, reco parameters and SiPM charachaterstics to update the parameters with new pulse shapes from PR #21168
      * update of HCAL LUTs : https://indico.cern.ch/event/681303/contributions/2814276/attachments/1570886/2478122/HCAL_Alca_20171206.pdf too support PR #21657

   * **PhaseI 2018 realistic scenario** : [100X_upgrade2018_realistic_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/100X_upgrade2018_realistic_v3) as [100X_upgrade2018_realistic_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/100X_upgrade2018_realistic_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/100X_upgrade2018_realistic_v3/100X_upgrade2018_realistic_v1): 
      * update of HCAL MC, reco parameters and SiPM charachaterstics to update the parameters with new pulse shapes from PR #21168
      * update of HCAL LUTs : https://indico.cern.ch/event/681303/contributions/2814276/attachments/1570886/2478122/HCAL_Alca_20171206.pdf too support PR #21657

   * **PostLS2 design scenario** : [100X_postLS2_design_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/100X_postLS2_design_v2) as [100X_postLS2_design_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/100X_postLS2_design_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/100X_postLS2_design_v2/100X_postLS2_design_v1): 
      * update of HCAL electronics map to fix PR #21475

   * **PostLS2 realistic scenario** : [100X_postLS2_realistic_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/100X_postLS2_realistic_v2) as [100X_postLS2_realistic_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/100X_postLS2_realistic_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/100X_postLS2_realistic_v2/100X_postLS2_realistic_v1): 
      * update of HCAL electronics map to fix PR #21475

### CODE REVIEW

**Comment by arunhep** [comment]
attn @abdoulline @kpedro88 @hatakeyamak @deguio

**Comment by arunhep** [comment]
please test

**Comment by arunhep** [comment]
not sure about the changes observed in ECAL 
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_10_0_X_2017-12-11-2300+21689/24272/10824.0_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2018_GenSimFull+DigiFull_2018+RecoFull_2018+ALCAFull_2018+HARVESTFull_2018/RelMonSummary.html

@abdoulline @kpedro88 @hatakeyamak @deguio
any idea?

for changes in Muon seeded Tracking, I think this commit  https://github.com/cms-sw/cmssw/commit/ef598b6d86051da3187d1fe68fdec21f800d5d40 is responsible.

**Comment by abdoulline** [comment]
Arun, I think ECAL changes come as a result of Digitization rndm seeds 
change due to HCAL shape.

When I've been testing PR #21168 for 2019 wf (where the new shape 206 is 
taken from hardcoded conditions) 
https://cms-cpt-software.web.cern.ch/cms-cpt-software/General/Validation/SVSuite/HCAL/calo_scan_single_pi/PR21168/10_0_X_2019_PR21168upd_vs_10_0_X_2019_default_SinglePi/

there was some small difference in ECAL...

**Comment by arunhep** [comment]
@davidlange6 can this be merged please?
thanks.

**Comment by davidlange6** [comment]
+1

**Comment by franzoni** [comment]
https://github.com/cms-sw/cmssw/pull/21657#issuecomment-352559263

**Pull request merged**
