### PR TITLE
DQM tau miniaod validation CMSSW_106X

### PR DESCRIPTION
**Pull request by aspiezia**
#### PR description:
Backport of https://github.com/cms-sw/cmssw/pull/27925
As in the previous pull request:
This PR has been done in order to add some histograms for the tau validation. The histograms are meant to validate the miniAOD part, in particolar for what it concern the DeepTau discriminators that can be checked only at miniAOD level. @rmanzoni @roger-wolf

#### PR validation:

First the changes have been tested with some RelVal samples in order to check that the histograms are created and filled in a sensible way.
Then, the instructions of https://cms-sw.github.io/PRWorkflow.html (see [*]) have been followed.

[*]
cd src
scram b distclean
git cms-checkdeps -a -A
scram b -j 8
scram b runtests
runTheMatrix.py -l limited -i all --ibeos

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by fabiocos** [comment]
+operations

the backport of the configurations updates in this PR is correct

**Comment by fabiocos** [comment]
+1

**Pull request merged**
