### PR TITLE
edmCheckMultithreading: check for non multithreading-compliant modules

### PR DESCRIPTION
**Pull request by fwyzard**
Check if the modules used by the CONFIG python file are `legacy`,
`global`, `stream` or `one` modules, and if they implement the
`fillDescriptions()` method.

### CODE REVIEW

**Comment by fwyzard** [comment]
@Martin-Grunewald , @perrotta , here is the script to check if any modules used by a CMSSW python configuration are multithreading-friendly or not.

**Comment by Martin-Grunewald** [comment]
Great, but what is the difference to CMSSW/​HLTrigger/​Tools/​scripts/​cmsCheckMultithreading ?
Will it now run for each PR automatically? With a warning for fillDescription, and an error
for non-MT?

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
though it just adds a new script, so it's very unlikely to break anything...

**Comment by fwyzard** [comment]
> Great, but what is the difference to CMSSW/​HLTrigger/​Tools/​scripts/​cmsCheckMultithreading ?
> Will it now run for each PR automatically? With a warning for fillDescription, and an error
for non-MT?

That's something I forgot putting there... and it's likely an older version, which was breaking when looking for the package where each module is defined.

And the new one has colours, too :-)

Anyway, no, it's not automatically run, it's something we should add to hltIntegrationTest, but I would do that only after this PR is merged.

**Comment by Dr15Jones** [comment]
Why was a backport needed?

**Comment by fwyzard** [comment]
because HLT will stay with CMSSW 7.4.x for the rest of the year (at least for pp collisions), and I would like to add this to the standard checks that we request from the developers

**Comment by Dr15Jones** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
