### PR TITLE
ETL v5 (D73) units of measurement moved to constant section

### PR DESCRIPTION
**Pull request by martatornago**
#### PR description:

All the units of measurement have been moved to the constant section.
Numeric values previously hard coded have been associated to new constants, which have been added to the constant section.  

#### PR validation:

The modules positions have been checked with the dump of the geometry using both testMTDinDDD.py and testMTDinDD4hep.py and compared with the output of the previous xml version, verifying they are identical.
Overlaps have been checked with g4OverlapCheck_cfg.py.
Visual check performed with Fireworks.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

@fabiocos FYI

### CODE REVIEW

**Comment by srimanob** [comment]
Please test

**Comment by fabiocos** [comment]
the running tests cannot show any effect of this PR, but the standalone checks show that the D73 geometry description is unchanged, while addressing the style comments by @cvuosalo

**Comment by cvuosalo** [comment]
+1

**Comment by srimanob** [comment]
+upgrade

**Comment by qliphy** [comment]
+1

**Pull request merged**
