### PR TITLE
DQM for Mjj paths (81X)

### PR DESCRIPTION
**Pull request by jruizvar**
Include Dijet scouting paths into EXO DQM. Requested by @deguio

### CODE REVIEW

**Comment by dmitrijus** [comment]
+1

**Comment by dmitrijus** [comment]
80x: https://github.com/cms-sw/cmssw/pull/14864

**Comment by davidlange6** [comment]
+1

**Comment by dmitrijus** [comment]
@davidlange6 can you revert this PR? 
https://github.com/cms-sw/cmssw/pull/14864#issuecomment-226436037

**Comment by davidlange6** [comment]
Done

**Pull request merged**
