### PR TITLE
Muon dqm mini aod 81 backport

### PR DESCRIPTION
**Pull request by sscruz**
Backport from PR [1] to 80_X
[1] https://github.com/cms-sw/cmssw/pull/14059

### CODE REVIEW

**Comment by dmitrijus** [comment]
This backport is slightly different from the 81x. You can see it in "lines added / removed' counter.

For example, DQMOffline_SecondStep_cff.py has the same content,
but DQMHarvestJetMET and DQMHarvestEGamma are defined in a different order than in 81x

For the sake of maintainability, please make sure those files match (if possible).
(Just add/amend a commit to this PR, don't touch 81x)

**Comment by goni** [comment]
Hi @sscruz @dmitrijus ,
Could you let me know, when this PR is done?
Actually, we changed #16288 due to get conflict regarding [diMuonHistos_cfi.py](https://github.com/sscruz/cmssw/blob/1a3afe39bf9ff87942ce67a927e6579474c9f404/DQMOffline/Muon/python/diMuonHistograms_cfi.py) in #14059 
Because, we found that #14059 made conflict with #16288 yesterday so we had to modify our PR to make it work based on #14059. 
We are expecting same problem can happen on this PR, so either you can 1) merge this PR as soon as possible or 2) do not merge this PR until 2016 pPb run finishes. 
This update is not necessary for pPb run monitoring, so we can use our PR #16289  without updates. Please note that pPb run will start from next week, so this is quite urgent. 
Could you please comment on this?

**Comment by HuguesBrun** [comment]
@goni , the MUO POG point of view it is fine with us to wait for the bunch of pPb PRs is integrated  (maybe not until the end of the pPb run: we hope that things will become stable before)

**Comment by dmitrijus** [comment]
+1

**Comment by dmitrijus** [comment]
+1
I don't think this will make it into 80x (or needed in 80x).
If I am wrong, please contact me to discuss the details.

**Comment by HuguesBrun** [comment]
Hello @dmitrijus , 

From muon POG perspective we still think that it is worth to include this PR. It aims at miniAOD validation and dedicated miniAOD campaigns are still possible with this release. For now we have to handle these validations ‘manually’ which is a non negligible additional work for us (knowing that the initial PR to include this code is here since January) 
Thanks,
Hugues for the MUO POG

**Comment by dmitrijus** [comment]
Ok, thanks, I will push it at the ORP tomorrow.

**Pull request closed without merging**
