### PR TITLE
Update premixing

### PR DESCRIPTION
**Pull request by srimanob**

### CODE REVIEW

**Comment by franzoni** [comment]
please test

**Comment by davidlange6** [comment]
this was the error:

+ timeout 9000 runTheMatrix.py '--das-options=--cache das-cache.file --limit 0' --job-reports -j 24 -s -l 1306.0,101.0,1003.0,50202.0,9.0,25202.0
Deprecated, please use -l limited
processing relval_standard
processing relval_highstats
processing relval_pileup
ERROR reading file: relval_pileup 'FS_SMS-T1tttt_mGl-1500_mLSP-100_13_UP15_PU25'
Traceback (most recent call last):
  File "/build/cmsbuild/jenkins-workarea/workspace/ib-any-integration/CMSSW_7_4_X_2015-07-05-1100/bin/slc6_amd64_gcc491/runTheMatrix.py", line 263, in <module>
    ret = runSelected(opt)
  File "/build/cmsbuild/jenkins-workarea/workspace/ib-any-integration/CMSSW_7_4_X_2015-07-05-1100/bin/slc6_amd64_gcc491/runTheMatrix.py", line 22, in runSelected
    mrd.prepare(opt.useInput, opt.refRel, opt.fromScratch)
  File "/build/cmsbuild/jenkins-workarea/workspace/ib-any-integration/CMSSW_7_4_X_2015-07-05-1100/python/Configuration/PyReleaseValidation/MatrixReader.py", line 470, in prepare
    self.readMatrix(matrixFile, useInput, refRel, fromScratch)
  File "/build/cmsbuild/jenkins-workarea/workspace/ib-any-integration/CMSSW_7_4_X_2015-07-05-1100/python/Configuration/PyReleaseValidation/MatrixReader.py", line 256, in readMatrix
    cfg, input, opts = self.makeCmd(self.makeStep(self.relvalModule.steps[stepName],stepOverrides))
KeyError: 'FS_SMS-T1tttt_mGl-1500_mLSP-100_13_UP15_PU25’

**Comment by franzoni** [comment]
@srimanob
Can you please put the process string of the input datssets as part of the dictionary where we collect them for all input datasets?
Thanks

**Comment by srimanob** [comment]
please test

**Comment by franzoni** [comment]
Hi phat @srimanob is this pull request still actual?

**Comment by srimanob** [comment]
No. Sorry I should close it.

**Pull request closed without merging**
