### PR TITLE
HcalTopologyMode - remove duplicate class  

### PR DESCRIPTION
**Pull request by davidlange6**
I picked the one that looks unused (but who knows with the linker..) and that looks like the obsolete version of the duplciate class (the other being Geometry/HcalCommonData)

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by cvuosalo** [comment]
@bsunanda Could you please check this PR?

**Comment by bsunanda** [comment]
These are indeed duplicate and obsolete files. Hope it is not used anywhere

**Comment by cvuosalo** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
