### PR TITLE
Change default DDBvL model to 94X

### PR DESCRIPTION
**Pull request by andrzejnovak**
Updating default DeepDoubleBvL model to phase-1 94X training

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test with cms-sw/cmsdist#4540

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/25376	1e830ff
- code changes are in line with the PR description
- jenkins tests pass and comparisons with the baseline show changes in expected places. The test were made with cms-sw/cmsdist#4540 which changes the training files for all of the deepDoubleX taggers ==> all 12 taging variables in slimmedJetsAK8 are changing.

**Comment by mrodozov** [comment]
please test with cms-sw/cmsdist#4551

**Comment by slava77** [comment]
tests with the updated/rebased cms-sw/cmsdist#4551 completed OK and comparisons show differences in expected places/variables.
Let's go ahead with merging.

**Comment by fabiocos** [comment]
+1

thanks @slava77 and @mrodozov

**Pull request merged**
