### PR TITLE
Updates towards enabling deepTauID at HLT

### PR DESCRIPTION
**Pull request by mbluj**
#### PR description:
This PR contains a set of changes needed to enable deepTauID at HLT:
* Producer of PFTaus matched to L1 seeds (`L1THLTTauMatching`) updated to produce (depending on a python configuration argument) either PFTaus with all data members filled for further processing or "empty" PFTaus with only p4 and vertex information filled which is minimal information needed for filtering;
* Added simpler (a more user-friendly) approach to define working points in `deepTauBase`;
* Define default output values if a preselection in the deepTauID producer fails;
* PFTauSelectorDefinition updated to handle outputs from the DeepTauID module and thus allow for filtering on deepTauID output;
* The `deepTauAtHLT.py` customisation file updated to simulate a full di-tau paths with deepTauID for measurements needed before integration with an actual HLT menu. Module names in the customisation file adapted to not cause unwanted overlap with other paths/sequences; Implemented proper deepTauID working points for HLT which are a function of tau pt.

The PR is targeting 12_1_0 to allow tests and then integration with HLT for Run3.

#### PR validation:

The PR has been validated on top of 12_1_0_pre4:

* DeepTauID modules have been run both for offline and online (with the two customisation functions) and run smoothly without unexpected surprises in the output. Results with standard workflows containing deepTauID (miniAOD) are expected to not change.

* The following command has been run to perform tests, which all succeeded:

```
scram b distclean 
git cms-checkdeps -a -A
scram b -j 8
scram b runtests
runTheMatrix.py -l limited -i all --ibeos
```

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by missirol** [comment]
@mbluj I left a couple of style suggestions inline.
I would suggest to squash the commits into one, to tidy up the history.

**Comment by mbluj** [comment]
@missirol - thank you for comments - I plan to work on them today. Concerning squashing the commits into one - I am not fan of this as tiding history means loosing history. I can try to clear the history a bit, but I do not see big advantage of it.

**Comment by missirol** [comment]
Thanks, @mbluj.

About the history, I don't disagree; it's just about trying to make the history meaningful/compact. It's maybe a bit subjective, and I don't see an explicit guideline on this in the ["coding rules"](https://cms-sw.github.io/cms_coding_rules.html) (so it is not a requirement).

**Comment by slava77** [comment]
+reconstruction

for https://github.com/cms-sw/cmssw/pull/35619	5644094
- code changes are somewhat technical for reco workflows, in line with the PR description
- jenkins tests pass and comparisons with the baseline show no (relevant) differences

**Comment by missirol** [comment]
+hlt

**Pull request merged**
