### PR TITLE
Changed output file format and table layout

### PR DESCRIPTION
**Pull request by dinardo**
I've made changes in the layout of the output file in such a way to be conformal with the BeamMonitor DQM application.
Moreover I've removed the call to offlineBeamSpot since it's not needed.

- Mauro.

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
This PR has merge conflicts which need to be fixed.

**Comment by Martin-Grunewald** [comment]
Also it seems it includes other commits.

**Comment by Martin-Grunewald** [comment]
-1

**Comment by fwyzard** [comment]
This seems to be based on the wrong branch, i.e. starting from 9.2.0-pre4.
If the aim is to include this in the regular 9.2.x release cycle, please create a new branch starting from 9.2.0 or a recent IB, and either update this PR or close this and create a new one.
If the aim is an urgent 9.2.0-patch5 for data taking, please change the target breach from master to the 920 patch branch.

**Pull request closed without merging**
