### PR TITLE
Backport extention of GEN-G4 interfaces extension from 8_1_X

### PR DESCRIPTION
**Pull request by civanch**
This is a back port of #16366 - the extension of primary generation interface between GEN production of exotics and Geant4. This is need to study long lived decay/interactions of such objects like dark photons.

### CODE REVIEW

**Comment by civanch** [comment]
@wulsin , please check this PR
@sushilchauhan , this PR is needed for your PR for dark photons

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by wulsin** [comment]
This looks great @civanch.  Thanks for doing this!

**Comment by davidlange6** [comment]
+1

**Pull request merged**
