### PR TITLE
Revert "Restore the original behaviour of PR 22131, revert PR 22239"

### PR DESCRIPTION
**Pull request by slava77**
Reverts cms-sw/cmssw#22338

in order to restore meaningful timing performance on data

https://github.com/cms-sw/cmssw/pull/22338#issuecomment-369021969

e.g. in 136.7611 the time per event for patTrigger module has increased by a factor of about 20E3.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by fabiocos** [comment]
@slava77 I agree this needs to be fixed, so we will revert the revert...

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/22379	d9db5e1
- naturally, the time to process 136.7611 step2 is back to about 2 minutes

we'll have to revert this eventually, but currently not having it in place prevents meaningful integration of features needed for 80XLegacy reminiAOD

**Comment by slava77** [comment]
@fabiocos 
I see that 10_1_0_pre2 build has started, but this PR is not merged.
Was there a reason to leave the 80XLegacy validation effectively broken?
Please clarify.

Thank you.

**Comment by fabiocos** [comment]
@slava77 I preferred not to further change things in the master at the very last moment, although this was effectively tested earlier. The wf is broken in the sense that it is eccessivly slow and must be optimised.
I would not consider this as a show-stopper for pre2 validation.

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Comment by slava77** [comment]
On 3/1/18 1:27 AM, Fabio Cossutti wrote:
> @slava77 <https://github.com/slava77> I preferred not to further change
> things in the master at the very last moment, although this was
> effectively tested earlier. The wf is broken in the sense that it is
> eccessivly slow and must be optimised.
> I would not consider this as a show-stopper for pre2 validation.
> 


this wf is required for the upcoming 80XLegacy feature integration.
Being able to do it in a pre-release is much more convenient.

The broken part [the prescales in patTrigger] was broken in miniAOD for
a year (if not forever since phase-1 trigger upgrades).
Making this break the full workflow is a showstopper, IMHO.

Thanks for merging it now.

**Pull request merged**
