### PR TITLE
HLT L1T interface updates - trhow exceptions and L1GlobalDecision  80x

### PR DESCRIPTION
**Pull request by rekovic**
Update to HLTL1TSeed.
- Now throw exception (instead of error) in case of empty or unknown algo is in seeds logical expression.
- Add functionality of passing seeding filter without seeds if L1GlobalDecision specified as seeds logical expression.

### CODE REVIEW

**Comment by rekovic** [comment]
please test

**Comment by Martin-Grunewald** [comment]
@rekovic 
Nice, thanks!

**Comment by Martin-Grunewald** [comment]
+1
(but only after both #13863 and #13892 are in)

**Comment by davidlange6** [comment]
+1

**Pull request merged**
