### PR TITLE
update eventSetupPathsKey for Strip/Pixel AlCas

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

This is a follow-up to PRs https://github.com/cms-sw/cmssw/pull/28535 and https://github.com/cms-sw/cmssw/pull/26032. 
The trigger bit selection for the three AlCaRecos `SiPixelCalSingleMuon`,`SiPixelCalCosmics` and `SiStripCalCosmics` is taken from DB tag instead of being hard-coded into the configuration file.
Three new tags are introduced:
   * MC workflows: `AlCaRecoHLTpaths_2017_MC_v4`, [diff w.r.t previous tag](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/tags/AlCaRecoHLTpaths_2017_MC_v2/AlCaRecoHLTpaths_2017_MC_v4)

image

   * Data offline workflows: `AlCaRecoHLTpaths_2017_offline_v4`, [diff w.r.t. previous tag](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/tags/AlCaRecoHLTpaths_2017_offline_v2/AlCaRecoHLTpaths_2017_offline_v4)

image

   * Prompt-reco workflow: `AlCaRecoHLTpaths8e29_5e33_v7_prompt`, [diff w.r.t. previous tag](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/tags/AlCaRecoHLTpaths8e29_5e33_v6_prompt/AlCaRecoHLTpaths8e29_5e33_v7_prompt)

image

#### PR validation: 

PR validation relies on the limited matrix integration tests. Worklfows which have been run:
   * `runTheMatrix.py -l limited -t 4 -j 8 --ibeos`
   * `runTheMatrix.py -l 7.22,7.21,7.4,7.3 -t 4 -j 8`
   * `runTheMatrix.py -l 138.1 -t 4 -j 8 --ibeos`

**N.B.: no difference to any workflow is expected  from this PR**

#### if this PR is a backport please specify the original PR:

This PR is not a backport, and no backport is meant.
cc: @tvami

### CODE REVIEW

**Comment by christopheralanwest** [comment]
please test

**Comment by mmusich** [comment]
> Reco comparison results: 2955 differences found in the comparisons
> DQMHistoTests: Total files compared: 34
> DQMHistoTests: Total histograms compared: 2697090
> DQMHistoTests: Total failures: 4976

the differences found in the run2 MC workflows are spurious and due to a missing update of the starting GT queue. The new candidates provided in https://github.com/cms-sw/cmssw/pull/28762/commits/0b425ecd1fc8061d37476edba4bb7d129cc652f0 should solve the issue.

**Comment by tlampen** [comment]
please test

**Comment by pohsun** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Comment by silviodonato** [comment]
@mmusich @christopheralanwest this PR is breaking step-3 of workflow 136.891.
Could you check/fix it, please? Thanks!
https://cmssdt.cern.ch/SDT/html/cmssdt-ib/#/relVal/CMSSW_11_1/2020-01-27-2300?selectedArchs=slc7_amd64_gcc820&selectedFlavors=X&selectedStatus=failed

```
----- Begin Fatal Exception 28-Jan-2020 08:38:22 CET-----------------------
An exception of category 'Configuration' occurred while
   [0] Processing  Event run: 320822 lumi: 75 event: 126696592 stream: 1
   [1] Running path 'pathALCARECOSiPixelCalSingleMuon'
   [2] Calling method for module HLTHighLevel/'ALCARECOSiPixelCalSingleMuonHLTFilter'
Exception Message:
 HLTHighLevel [instance: ALCARECOSiPixelCalSingleMuonHLTFilter - path: pathALCARECOSiPixelCalSingleMuon]: No triggerList with key SiPixelCalSingleMuon in AlCaRecoTriggerBitsRcd
----- End Fatal Exception -------------------------------------------------
```

It seems you need to update the global tag auto:run2_data_promptlike(110X_dataRun2_PromptLike_v9)

**Comment by mmusich** [comment]
@silviodonato see please exact same comment at https://github.com/cms-sw/cmssw/pull/28804#issuecomment-579134296

**Pull request merged**
