### PR TITLE
Cell correction

### PR DESCRIPTION
**Pull request by Pruthvi-ch**
PR description:

Update the hgcalcell xml and plugin files in view of corrections for cell dimension. The new code will take care of the V17 cells but is not expected to modify cells for earlier version.
Depends on PR #37448
Discussed in : https://indico.cern.ch/event/1136462/

PR validation:

Use the runTheMatrix test workflows

if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
cmsbuild please test with #37511

**Comment by bsunanda** [comment]
cmsbuild please test with #37511

**Comment by Pruthvi-ch** [comment]
@cmsbuild please test

**Comment by rovere** [comment]
Please add a link to slides/documentation to explain what this PR is about.

**Comment by Pruthvi-ch** [comment]
Added the link in the description

**Comment by cvuosalo** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

This PR handles the transformation of (x,y) to (u,v) of HGCAL rotated wafer. No change is expected from this PR as it only update the plugin and trivial update on XML. 

@Pruthvi-ch Could you please update the PR title to me more clear. The current `Cell correction` is somehow to general.

**Comment by perrotta** [comment]
+1

**Pull request merged**
