### PR TITLE
 Adding dedicated CaloLayer2 shifter plots

### PR DESCRIPTION
**Pull request by vukasinmilosevic**
Backport of PR #23046.

Change requested in: https://its.cern.ch/jira/browse/CMSLITDPG-480
The online shifter plots 02-07 needed some work to make them more comprehensible for shifters and other non-experts (the old/expert plots are saved in the same location, while the new plots are placed under a new "shifter" folder).

### CODE REVIEW

**Comment by thomreis** [comment]
backport of #23046

**Comment by thomreis** [comment]
please test

**Comment by thomreis** [comment]
please test

**Comment by thomreis** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
