### PR TITLE
rework python import tests to test each package separately

### PR DESCRIPTION
**Pull request by davidlange6**
Fixes temporarily (not 100% reproducible I believe) unit test error in PhysicsTools/PythonAnalysis. We'll try to do something smarter in a followup PR.

Edit: "smarter" turned out to be straightforward, so I updated this PR.

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
@davidlange6 this basically becomes a dummy test for the time being, right?

**Comment by fabiocos** [comment]
merge

**Pull request merged**
