### PR TITLE
[125X][GSF tracking] Add full Sylvester criterion for positive definite check

### PR DESCRIPTION
**Pull request by swagata87**
#### PR description:

Backport of https://github.com/cms-sw/cmssw/pull/39656 to address https://github.com/cms-sw/cmssw/issues/39570

### CODE REVIEW

**Comment by swagata87** [comment]
@cmsbuild please test

**Comment by mandrenguyen** [comment]
backport of #39656

**Comment by mandrenguyen** [comment]
type egamma

**Comment by mandrenguyen** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
