### PR TITLE
Moved FileInPath to  FWCore/Utilities

### LINKED ISSUE #157: Move edm::FileInPath to FWCore/Utilities
Useful for ROOT module's build in order to avoid unnecessary TBB parsing.

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

Moved the class `edm::FileInPath` from FWCore/ParameterSet to FWCore/Utilities. The class only depends on code from FWCore/Utilities.

The move was also meant to reduce `*Formats` packages dependencies on FWCore/ParameterSet which will make transitioning to ROOT's module system easier.

#### PR validation:

Code compiles.

fixes makortel/framework#157

### CODE REVIEW

**Comment by Dr15Jones** [comment]
NOTE: transitioning away from old includes used in the rest of CMSSW will happen in future pull requests.

**Comment by Dr15Jones** [comment]
@davidlange6 FYI

**Comment by Dr15Jones** [comment]
please test

**Comment by makortel** [comment]
+1

Failing tests are in CondTools and are failing in IBs as well.

**Comment by qliphy** [comment]
merge

**Pull request merged**
