### PR TITLE
HCALDQM: Monitor bad capid rotation, uHTR/L1T mismatches (10_1_X)

### PR DESCRIPTION
**Pull request by DryRun**
Backport of https://github.com/cms-sw/cmssw/pull/23140.

Adds the following, mostly related to the issues seen so far in 2018:
- Monitor bad capid rotation. (BX - capid) % 4 should be a constant.
- Monitor uHTR-L1T mismatches. This is copied straight from the L1T DQM code, but it's extremely useful for HCAL.

Minor additions:
- Add LED pin diode plots to local DQM.
- UMNioTask now handles LED events correctly, instead of labeling them HF.
- Implement code rule check as suggested by Fabio. These were all "using namespace * in header" violations, which were fairly ubiquitous in the HcalCommon infrastructure.

### CODE REVIEW

**Comment by dmitrijus** [comment]
+1

**Comment by DryRun** [comment]
Sorry for the noise - the RelVals error should be fixed now, and I'll stop touching the PR.

**Comment by dmitrijus** [comment]
Once again, this PR has some extra commits which are not merged in master... :(

**Comment by DryRun** [comment]
Hi @dmitrijus - are you referring to the last two commits? These were merged in master this morning in https://github.com/cms-sw/cmssw/pull/23221. Sorry if this was confusing, I can try to make a new backport PR next time.

**Comment by dmitrijus** [comment]
Yes,  I was. You really need to mention them once you add them :)

**Comment by dmitrijus** [comment]
+1

**Comment by jfernan2** [comment]
Successfully tested and integrated in the Online DQM at P5. https://twiki.cern.ch/twiki/bin/viewauth/CMS/DQMP5TagCollector
Merged in master

**Pull request merged**
