### PR TITLE
Hf shower library update

### PR DESCRIPTION
**Pull request by davidlange6**
primary change is to reformat the HF shower library itself. Now each "event" is formatted as a vector of floats and the basket size is 1 - this means events can be read one at a time so much less time is spent reading the data (which is essentially randomly read).

needs https://github.com/cms-sw/cmsdist/pull/2543

### CODE REVIEW

**Comment by davidlange6** [comment]
please test with cms-sw/cmsdist#2543

**Comment by smuzaffar** [comment]
@davidlange6 , should be keep v3 also in the external? Looks like cmssw code still has ref to it
```
FastSimulation/Calorimetry/python/Calorimetry_cff.py:run2_common.toModify(FamosCalorimetryBlock.Calorimetry.HFShowerLibrary, FileName = 'SimG4CMS/Calo/data/HFShowerLibrary_npmt_noatt_eta4_16en_v3.root' )
SLHCUpgradeSimulations/Configuration/python/fastSimCustoms.py:    process.famosSimHits.Calorimetry.HFShowerLibrary.FileName = cms.FileInPath('SimG4CMS/Calo/data/HFShowerLibrary_npmt_noatt_eta4_16en_v3.root
SLHCUpgradeSimulations/Configuration/python/postLS1Customs.py:    process.g4SimHits.HFShowerLibrary.FileName = 'SimG4CMS/Calo/data/HFShowerLibrary_npmt_noatt_eta4_16en_v3.root'
Validation/CaloTowers/test/CaloScan/template.py:process.g4SimHits.HFShowerLibrary.FileName = 'SimG4CMS/Calo/data/HFShowerLibrary_npmt_noatt_eta4_16en_v3.root'
Validation/CaloTowers/test/CaloScan/template.py_since760pre6:process.g4SimHits.HFShowerLibrary.FileName = 'SimG4CMS/Calo/data/HFShowerLibrary_npmt_noatt_eta4_16en_v3.root'
Validation/CaloTowers/test/CaloScan/template.py_since760pre6_forGEN_760pre6:process.g4SimHits.HFShowerLibrary.FileName = 'SimG4CMS/Calo/data/HFShowerLibrary_npmt_noatt_eta4_16en_v3.root'
```

**Comment by davidlange6** [comment]
No - we should clean up the v3 usages (wondering why I didn’t noticed the first one of these..)

**Comment by Dr15Jones** [comment]
This appears to have caused many of the RelVals to fail with 
```
----- Begin Fatal Exception 01-Oct-2016 10:35:37 CEST-----------------------
An exception of category 'ConfigFileReadError' occurred while
   [0] Processing the python configuration file named TTbar_13TeV_TuneCUETP8M1_cfi_GEN_SIM_RECOBEFMIX_DIGI_L1_DIGI2RAW_L1Reco_RECO_EI_HLT_VALIDATION_DQM.py
Exception Message:
python encountered the error: <type 'exceptions.RuntimeError'>
edm::FileInPath unable to find file SimG4CMS/Calo/data/HFShowerLibrary_npmt_noatt_eta4_16en_v3.root anywhere in the search path.
The search path is defined by: CMSSW_SEARCH_PATH
${CMSSW_SEARCH_PATH} is: /build/cmsbld/jenkins-workarea/workspace/ib-run-relvals/CMSSW_8_1_X_2016-09-30-2300/src:/build/cmsbld/jenkins-workarea/workspace/ib-run-relvals/CMSSW_8_1_X_2016-09-30-2300/external/slc6_amd64_gcc530/data:/cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_X_2016-09-30-2300/src:/cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_X_2016-09-30-2300/external/slc6_amd64_gcc530/data
Current directory is: /build/cmsbld/jenkins-workarea/workspace/ib-run-relvals/CMSSW_8_1_X_2016-09-30-2300/pyRelval/135.1/135.1_TTbar_13+TTbarFS_13+HARVESTUP15FS+MINIAODMCUP15FS

----- End Fatal Exception -------------------------------------------------
```

**Comment by smuzaffar** [comment]
https://github.com/cms-sw/cmssw/pull/16066 should fix it

**Pull request merged**
