### PR TITLE
2017 Geometry: Add Detailed Cavern Description

### PR DESCRIPTION
**Pull request by ianna**
* Use detailed cavern description

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by kpedro88** [comment]
@ianna why are we changing the 2017 geometry after the fact?

**Comment by ianna** [comment]
@kpedro88 - good point. I'll create a separate 2017DetailedCavern scenario. It is needed to launch a neutrino study samples production.

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
+1

The differences reported in the comparison are unrelated to this PR - the new geometry scenarios are not used anywhere yet.

**Comment by kpedro88** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
