### PR TITLE
Skip invalid channels in the GPU HCAL RecHit producer [12.4.x]

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

This PR consistes of two parts:
  - the GPU code now marks as invalid (setting chi² = -9999.) the HCAL channels for which it cannot determine the SOI;
  - the CPU code that converts from SoA to legacy format now skips all invalid channels.

See h#39693 for a discussion on the underlying issues.

#### PR validation:

Tested on top of CMSSW_12_4_10 over the events that caused the HLT to crash in runs 357898, 359998, and 360295.
Without these changes the original crash can be reproduced in multiple files:
```
----- Begin Fatal Exception 14-Oct-2022 20:27:30 CEST-----------------------
An exception of category 'Conditions not found' occurred while
   [0] Processing  Event run: 360295 lumi: 174 event: 264575349 stream: 7
   [1] Running path 'Path'
   [2] Calling method for module CaloTowersCreator/'hltTowerMakerForAll'
Exception Message:
Unavailable Conditions of type HcalChannelQuality for cell (0x0) 
----- End Fatal Exception -------------------------------------------------
```

With these changes the HLT jobs run to completion on almost all those files (barring one that is affected by a different, ECAL-related crash).

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport of #39738 for data taking.

### CODE REVIEW

**Comment by fwyzard** [comment]
type bugfix

**Comment by fwyzard** [comment]
backport #39738

**Comment by fwyzard** [comment]
please test

**Comment by clacaputo** [comment]
test parameters:

- enable_tests = gpu
- workflows_gpu = 11634.523

**Comment by clacaputo** [comment]
please test

**Comment by missirol** [comment]
@silviodonato @fwyzard 

Is the plan to ask for a new (patch) release as soon as this bug-fix is merged?

**Comment by silviodonato** [comment]
> @silviodonato @fwyzard
> 
> Is the plan to ask for a new (patch) release as soon as this bug-fix is merged?

yes, we would like to ask another patch release (if possible) to include this bug-fix. This PR should solve the last remaining "common" crash that we see in the HLT farm (@rappoccio @perrotta)

**Comment by clacaputo** [comment]
+reconstruction

- backport of #39738
- GPUvsCPU diffs for wf `11634.523` are in line with what is stated in https://github.com/cms-sw/cmssw/pull/39738#issuecomment-1282052826

**Comment by clacaputo** [comment]
+reconstruction

- backport of #39738
- GPUvsCPU diffs for wf `11634.523` are in line with what is stated in https://github.com/cms-sw/cmssw/pull/39738#issuecomment-1282052826

**Pull request merged**
