### PR TITLE
optimized CPU timing of ECAL Pi0 stream

### PR DESCRIPTION
**Pull request by cippy**
See comments on 80X pull request #14358

@emanueledimarco @shervin86 @crovelli

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by VinInn** [comment]
This is only half of the work.
There is similar code in doSelection lines 642 -

**Comment by davidlange6** [comment]
+1
(probably better if this used XYZPoint to match the implementation in BasicCluster)
@cippy

**Pull request merged**
