### PR TITLE
Print function migration for IOMC_EventVertexGenerators

### PR DESCRIPTION
**Pull request by davidlange6**
Using futurize -n -w --no-diffs -j 4 -f libfuturize.fixes.fix_print_with_import

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by perrotta** [comment]
@davidlange6 : this and (supposedly) all PRs of this kind that you are submitting today require the reco signature because in all them it is oddly included also the commit that updates ```RecoParticleFlow/PFProducer/python/tools/pfClusteringCustoms.py``` (which is already correctly taken into account by #23868)
While it is not a big issue signing all them at once on that basis (which is probably faster that letting you modify all them one by one), please be sure to remove that commit from your next submissions.

**Comment by davidlange6** [comment]
ah - i didn't notice that - I'll fix that for future prs..

**Comment by perrotta** [comment]
+1
- Reco content identical to the already signed #23868

**Comment by fabiocos** [comment]
+1

failures are unrelated

**Comment by fabiocos** [comment]
merge

@civanch changes look technical and simple enough

**Pull request merged**
