### PR TITLE
Phase2-hgx296 Make use of ESGetToken in SimProducer class of Validation/HGCalValidation

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Make use of ESGetToken in SimProducer class of Validation/HGCalValidation

#### PR validation:

Use test script in Validation/HGCalValidation/test 

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
