### PR TITLE
Update L1T DQM clients to 2018 era

### PR DESCRIPTION
**Pull request by nsmith-**
backport of #22350 
For use in online DQM at P5 for commissioning running.

### CODE REVIEW

**Comment by nsmith-** [comment]
please test

**Comment by thomreis** [comment]
@dmitrijus @jfernan2 please sign

**Comment by thomreis** [comment]
@dmitrijus @jfernan2 please sign.

**Comment by dmitrijus** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
