### PR TITLE
Add protection against 0-element uGtAlgoBlocks in HLTL1TSeed module

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
Add protection against 0-element uGtAlgoBlocks in HLTL1TSeed module
Fix formatting
From @rekovic

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
