### PR TITLE
Run3 era for 2024 pp reference and UPC reco

### PR DESCRIPTION
**Pull request by stahlleiton**
#### PR description:

This PR implements a first version of the Run 3 eras for the 2024 pp reference (at 5.36 TeV) and PbPb UPC reconstruction.

@mandrenguyen 

#### PR validation:

Validated using a minbias sample.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

### CODE REVIEW

**Comment by mandrenguyen** [comment]
@stahlleiton  Normally we add a relVal workflow for testing.  Do you want to give it a shot? 
Can you list the cmsDriver commands you used for testing?
I recall that conditions were required for the low pT photon code. 
Which GT were you using?

**Comment by stahlleiton** [comment]
For the UPC, the only change was to modify the base era from Run3_2023 to Run3, and I tested it on 13_2_X. To test it in 14_1_X, a new GT will be needed (I can try to request one and add a MC relval for 14_1_X)

**Comment by stahlleiton** [comment]
Implemented 4 relval MC workflows:
- 149.1: 2024 pp ref
- 180: 2023 Pythia8 gamma-nucleus
- 180.1: 2023 Starlight double diffraction
- 181: 2024 Pythia8 gamma-nucleus

**Comment by AdrianoDee** [comment]
test parameters:
- workflows = 149.1, 180, 180.1, 181

**Comment by AdrianoDee** [comment]
please test

**Comment by stahlleiton** [comment]
@AdrianoDee : please include PR https://github.com/cms-sw/cmssw/pull/44264 when submitting the tests with relvals 180 and 181.

**Comment by mandrenguyen** [comment]
@stahlleiton I think I'm missing the logic on the wf 181.  
Do I understand correctly that this is UPC reco for 2024 with light-by-light settings enabled, but it currently uses the standard pp GT?
Shouldn't that crash due to the lack of photon regression tags in the GT?  What am I missing here?

**Comment by mandrenguyen** [comment]
+reconstruction
2024 UPC will have to be updated when a proper GT is available.

**Comment by srimanob** [comment]
See noisy on GEN particle validation in both 2023 and 2024. Warning of index mismatch in all events. Should something be update later for validation with gamma-nucleaus generator? Note to @cms-sw/generators-l2 

```
Begin processing the 2nd record. Run 1, Event 2, LumiSection 1 on stream 0 at 06-Mar-2024 11:57:41.246 CET
%MSG-w IncorrectMatching:   BasicGenParticleValidation:basicGenParticleValidation 06-Mar-2024 11:57:41 CET  Run: 1 Event: 2
Incorrect number of matched indexes: GenParticle = 70 matched indexes = 69
%MSG
Begin processing the 3rd record. Run 1, Event 3, LumiSection 1 on stream 0 at 06-Mar-2024 11:57:42.124 CET
%MSG-w IncorrectMatching:   BasicGenParticleValidation:basicGenParticleValidation 06-Mar-2024 11:57:42 CET  Run: 1 Event: 3
Incorrect number of matched indexes: GenParticle = 88 matched indexes = 87
%MSG
```

**Comment by stahlleiton** [comment]
> @stahlleiton Just my curiosity, why don't you add also 2024 Starlight double diffraction ?

Was planning to eventually update the Starlight gridpack with a more recent one in the near future, so thought of just adding it for 2023 conditions (to test it overall) and then do a follow up PR when the first 2024 HI GTs are available.

**Comment by vlimant** [comment]
+1

**Comment by stahlleiton** [comment]
@cms-sw/pdmv-l2 , @cms-sw/generators-l2 , @cms-sw/upgrade-l2 : please review/sign this PR

**Comment by AdrianoDee** [comment]
please test
(let me refresh 2 weeks old tests)

**Comment by stahlleiton** [comment]
@AdrianoDee : thanks for re-triggering the tests.
@cms-sw/pdmv-l2 , @cms-sw/generators-l2 , @cms-sw/upgrade-l2 : would be appreciated if you could review/sign this PR, thanks

**Comment by AdrianoDee** [comment]
+pdmv

**Comment by stahlleiton** [comment]
@bbilin and @menglu21 : please review/sign this PR

**Comment by menglu21** [comment]
+1

**Comment by antoniovilela** [comment]
+1

**Comment by makortel** [comment]
Workflow 180.1 fails in IBs, see https://github.com/cms-sw/cmssw/issues/44536

**Comment by stahlleiton** [comment]
> Workflow 180.1 fails in IBs, see #44536



> Workflow 180.1 fails in IBs, see #44536

workflow disabled in https://github.com/cms-sw/cmssw/pull/44540

**Pull request merged**
