### PR TITLE
CTPPS: TotemTimingDigi, totemTimingRawToDigi and mapping for the new Timing detector in Vertical RPs, backport of #22796

### PR DESCRIPTION
**Pull request by nminafra**
This PR is a backport of #22796 **needed for the DQM during the alignment run.**

This PR introduces support for the new timing detectors (TOTEM) in the vertical roman pots (RPs).

NOTE: the digital part of this detector is completely different from the CTPPS diamond detector. Here we use a sampler (SAMPIC) instead of a TDC. Therefore, even if we can share part of the unpacker (for the OptoRx frames), the dataformat is substantially different.

This PR introduces many modifications because an effective test is only possible using the TotemTimingDIGIs.

Suggested test:
EventFilter/CTPPSRawToDigi/test/test_standard_sequence_cfg.py

Data with this detector are available in:
/store/group/dpg_ctpps/comm_ctpps/TotemTiming/Minidaq/519/

Thanks!

### CODE REVIEW

**Comment by perrotta** [comment]
backport of #22796

**Comment by perrotta** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by perrotta** [comment]
-1
- Fully contained in (and therefore superseeded by) #22931: no need to backport both them

**Comment by arunhep** [comment]
-1
understood from reco that the changes in this PR are already merged in another one.
https://github.com/cms-sw/cmssw/pull/22930#issuecomment-380922279

**Pull request closed without merging**
