### PR TITLE
Herwigpp: Updated configuration settings

### PR DESCRIPTION
**Pull request by mharrend**
- Cleaned and updated configuration settings
- Splitted default settings in further parts to improve structure and to minimize code duplication
- Main features of new release
  *\* Simple hadronizer allows to use a different PDF for the hard subprocess as for the subsequent parton shower if a Powheg LHE file is showered.
  Advantage: Shower PDF could be set according to the tune

*\* Simple hadronizer for showering MadGraph5_aMC@NLO LHE files

*\* Simple Generator config for Dummy process

### CODE REVIEW

**Comment by bendavid** [comment]
So if I understand correctly, one has to keep in sync the pdf and tune by hand.  (Given the different combinations of pdfs which are possible, I guess we'll have to live with that).

One final request for this pull request.  Can you add a fragment for the new CUETHS1 tune as below? (this is based on EE5C and should also be used with CTEQ6L1)

  CUETHS1EnergyExtrapol = cms.vstring(
    'set /Herwig/UnderlyingEvent/MPIHandler:EnergyExtrapolation Power',
    'set /Herwig/UnderlyingEvent/MPIHandler:ReferenceScale 7000.*GeV',
    'set /Herwig/UnderlyingEvent/MPIHandler:Power 3.705288e-01',
    'set /Herwig/UnderlyingEvent/MPIHandler:pTmin0 3.91*GeV',
  ),

  CUETHS1 = cms.vstring(
    '+CUETHS1EnergyExtrapol',
    # Colour reconnection settings
    'set /Herwig/Hadronization/ColourReconnector:ColourReconnection Yes',
    'set /Herwig/Hadronization/ColourReconnector:ReconnectionProbability 5.278926e-01',
    # Colour Disrupt settings
    'set /Herwig/Partons/RemnantDecayer:colourDisrupt 6.284222e-01',
    # inverse hadron radius
    'set /Herwig/UnderlyingEvent/MPIHandler:InvRadius 2.254998e+00',
    # MPI model settings
    'set /Herwig/UnderlyingEvent/MPIHandler:softInt Yes',
    'set /Herwig/UnderlyingEvent/MPIHandler:twoComp Yes',
    'set /Herwig/UnderlyingEvent/MPIHandler:DLmode 2', 
  ),

**Comment by mharrend** [comment]
I have added the CUETHS1 tune and updated the CTEQ6L1 config accordingly.

In regards to the alphaS values and the PDFs I already bugged the ThePEG authors that it would be nice to directly get the alphaS value from the LHAPDF interface, so that we could easily set it and do not have to do this manually.
I will bug them further and hope this helps.

**Comment by bendavid** [comment]
Thanks.
I think the name "HerwigppUE_EE_5C_CUETHS1_cfi.py" is confusing.  Since even if CUETHS1 is based on ee5c, it's a separate tune.
So maybe just "HerwigppUE_CUETHS1_cfi.py" would be better.  Can you rename it?

For the alphaS values, I actually have no problem if they're set separately from the pdf's.  This is how it works in pythia, and it may be desirable to be able to tune/set this value independent from the pdfs anyways.
Do the current configs use the correct values for alphas in the shower and underlying event?  ("Correct" would be whatever corresponds to the tune and/or herwig default I suppose)

**Comment by mharrend** [comment]
I have renamed the CUETHS1 tune

At the moment the default values of Herwig++ are used for all alphaS values, so there should be no problem with the shower or UE tune.

As soon as I get the information from Simon I would only change the alphaS value of the shower, so that the alphaS value corresponds with the shower PDF. And in analogous way the alphaS value of the hard subprocess and the hard subprocess PDF.
This also should not affect the UE tune.

**Comment by bendavid** [comment]
Ok, what are the herwig++ default values just to know?
CTEQ6L1 uses 0.130 at least.

**Comment by mharrend** [comment]
I cannot tell you the Herwig++ alphaS values since there exist more than five different alphaS values. As I told you it is quite a challenge to understand which alphaS value is used what for and to find their default values in Herwig++ 2.7.
I really hope that it will be better in Herwig++ 3. 

We should ask Simon in this regard if you really need this information. I can give you at the moment only the alphaS value of the DipoleShower:

LO     0.1283827
NLO   0.1271103

Sorry!

**Comment by bendavid** [comment]
Ok, can you at least confirm that the default values for alphaS are what are intended to be used with tune EE5C?

**Comment by bendavid** [comment]
(and assuming CTEQ6L1 is used for the shower and underlying event)

**Comment by mharrend** [comment]
Yes, the default value for alphaS is intended to be used with the tune EE5C and the CTEQ6L1 PDF is used for both the shower and the UE event if one uses the provided HerwigppPDF_CTEQ6L1 file.

**Comment by bendavid** [comment]
Ok thanks.  In that case I agree that things are fine for now, and sufficient for use with 2.7.1.

**Comment by bendavid** [comment]
+1

**Comment by davidlange6** [comment]
@cmsbuild please test

**Comment by davidlange6** [comment]
+1

**Pull request merged**
