### PR TITLE
Avoid type punning in L1Trigger/CSCTrackFinder

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

Found using gcc -O3 -g.

#### PR validation:

After the change, the code compiles fine with the options.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
The errors in the testers were from X509 proxy failures.

**Comment by Dr15Jones** [comment]
Please test

**Comment by cecilecaillol** [comment]
+l1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
