### PR TITLE
change selector to stream for multithreading

### PR DESCRIPTION
**Pull request by kirschen**
backport of #13451

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test
@kirschen 
I guess you also need this in 76X

**Comment by kirschen** [comment]
Hi Slava,

the JIRA-ticket this has to do with is https://its.cern.ch/jira/browse/CMSHLT-586
@Martin-Grunewald suggested to do it in 80X/81X for now.

Cheers,
Henning

**Comment by slava77** [comment]
Hi Henning,

The selector looks generic enough that it may be useful in analysis.
I guess we can just keep it in mind for now and stay with just 8X.

Slava

**Comment by cvuosalo** [comment]
@cmsbuild please test
DAS error -- trying again

**Comment by cvuosalo** [comment]
+1

For #13452 1f97dd7c05c92c1b28ca6800926a1ccdbc6896c5

Small fix to GenericPFCandidateSelector to support multi-threading for possible use by HLT. There should be no change in monitored quantities. #13451 is the 81X version of this PR, and it has already been approved by Reco.

The code change is satisfactory, and Jenkins tests against baseline CMSSW_8_0_X_2016-02-23-2300 show no significant differences, as expected.

**Pull request merged**
