### PR TITLE
Dedicated Timing Plots - New Settings for uGT and Eta/Phi Map - L1T & Online DQM - CMSSW - 100X

### PR DESCRIPTION
**Pull request by ghost**
My task in JIRA is : ([https://its.cern.ch/jira/browse/CMSLITDPG-165]).

First of all, I would like to mention that I added a new and more convenient way to implement the necessary algorithm trigger bits (L1_FirstCollisionInTrain, L1_LastCollisionInTrain) for producing pre- post- firing plots using them as parameters for the first bunch, last bunch and isolated bunch. After that, I produced a new module for producing pre- post- firing plots with a second way using eta/phi map for L1T objects (muon, jet, tau, egamma, MET) for every BX as well as for the first bunch, last bunch and isolated bunch.

### CODE REVIEW

**Comment by dtsitson** [comment]
backport of  #21793

**Comment by thomreis** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
