### PR TITLE
Fix HCAL TP validation & packing w/ premixing

### PR DESCRIPTION
**Pull request by kpedro88**
Followup to #20221 with a more complete solution.
1. TPs from premixing are now included in the packer for both current and old workflows.
2. TPs from premixing are now included in the event content.
3. The HCAL validation sequences that use the simulated TPs are customized to use the proper tag for premixing workflows.

attn: @deguio @hatakeyamak @abdoulline @christopheralanwest @matz-e

### CODE REVIEW

**Comment by kpedro88** [comment]
please test

**Comment by kpedro88** [comment]
abort

**Comment by kpedro88** [comment]
please test workflow 250207.17

**Comment by kpedro88** [comment]
@civanch @mdhildreth please sign

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
merge

**Pull request merged**
