### PR TITLE
Added more ZDC functionality to DQM

### PR DESCRIPTION
**Pull request by JoshPBR2**
#### PR description:

This PR adds additional DQM tools for the ZDC including

- Timing plots
- TDC plots
- Sum plots
- Emulator plots to be added

#### PR validation:

To test this PR a number of workarounds are needed as this PR is dependent on the ZDC geometry. [see issue](https://github.com/cms-sw/cmssw/issues/45530)

To test

`cmsrel CMSSW_14_1_0_pre5
cd CMSSW_14_1_0_pre5/src
cmsenv
git cms-merge-topic matt2275:Test_ZDCRecHit
scram b -j8 `

Grab conditions [here](https://github.com/matt2275/ZDCRecHit-Associated-Files)

This PR will not require any back ports and is intended for heavy-ion data taking.

@salimcerci

### CODE REVIEW

**Comment by abdoulline** [comment]
@JoshPBR2 
just wonder if you need (so) high precision conversion [ADC -> fC](https://github.com/cms-sw/cmssw/pull/45544/files#diff-8bf26c67ffbb9f73354d5b91513804ce9b35120894c4c12846b8a83ec8608f21R96)  ?
as there is already QIE10 generic/simplified table used for HF:  
  https://cmssdt.cern.ch/lxr/source/DQM/HcalCommon/interface/Constants.h#0258

**Comment by JoshPBR2** [comment]
@abdoulline 
I pushed a new version now using the already implemented table. Don't think having the high precision one is of much use.

**Comment by tjavaid** [comment]
please test

**Comment by tjavaid** [comment]
please test

**Comment by tjavaid** [comment]
please test

- getting fresh results

**Comment by tjavaid** [comment]
please test

**Comment by tjavaid** [comment]
@JoshPBR2 , It seems to be based on a different fork from `cmssw` called `CmsHI/cmssw` :
''
This branch is 51041 commits ahead of, 586 commits behind CmsHI/cmssw:forest_CMSSW_10_3_1
''
Would you prefer to take a recent  cmssw ? (just for smooth merging)

**Comment by abdoulline** [comment]
FYI  @denizsun

**Comment by abdoulline** [comment]
@salimcerci 
now see that you were [included in the PR notifications](https://github.com/cms-sw/cmssw/pull/45544#issue-2427787546) at the very beginning by Joshua.

**Comment by antoniovilela** [comment]
ping (to make bot change milestone)

**Comment by hjbossi** [comment]
For all following this PR, it is now moved to: https://github.com/cms-sw/cmssw/pull/45948

**Pull request closed without merging**
