### PR TITLE
HLT menu development for `13_2_X` (5/N) [`14_0_X`]

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

Development of HLT menus for CMSSW_13_2_X.
   * This is the final integration of the development in 13_2_X before moving to the new production cycle

This is the PR for the master branch, which will then be backported down to 13_2_X (the latter is the release cycle currently used for Run-3 HLT-menu development).

This version of the HIon HLT menu corresponds to the latest online updates performed by TSG/FOG to the "V1.1" menu for the 2023 heavy-ion data-taking period (the corresponding frozen menu is not added to the release, as not included in any central releae validation workflow).

In addition, the following changes are included:
   * 86106cf87f7c7815742e3de40eff5ef5879f2a45: Update of L1T HIon menu to `v1_1_5` in `autoCondHLT.py`
   * 4d81e1e20ad95fbea2510aba2ec1adff246b629c: revert customization of `FEVTDEBUGHLTEventContent` introduced in PR  https://github.com/cms-sw/cmssw/pull/43141  

This update includes the integration of the following JIRA tickets:
- [CMSHLT-2970](https://its.cern.ch/jira/browse/CMSHLT-2970) [TSG]: Online changes on 2023 HION menu v1.1
- [CMSHLT-2790](https://its.cern.ch/jira/browse/CMSHLT-2790) [TSG]: Remove prescalers from `RatesMonitoring` and `HLTAnalyzerEndpath`
- [CMSHLT-2964](https://its.cern.ch/jira/browse/CMSHLT-2964) [TSG]: Update of ReleaseValidation EventContent for HIon DQM
- [CMSHLT-2963](https://its.cern.ch/jira/browse/CMSHLT-2963) [HIN]: Add `HIZeroBias` PDs and pass-throughs for randoms and new L1T-Jet(UPC) seeds to "V1.1" HIon menu
- [CMSHLT-2898](https://its.cern.ch/jira/browse/CMSHLT-2898) [HIN]: Compression settings of HLT `OutputModules` in 2023 HIon menu
- [CMSHLT-2958](https://its.cern.ch/jira/browse/CMSHLT-2958) [HIN]: Increase prescale by factor of 5 for `Dataset_HIOnlineMonitor`
- [CMSHLT-2947](https://its.cern.ch/jira/browse/CMSHLT-2947) [HIN]: Add (12) UPC HLT paths with corresponding L1 seeds for ZDC asymmetry
- [CMSHLT-2887](https://its.cern.ch/jira/browse/CMSHLT-2887) [HIG]: Technical: rationalise VBF-parking triggers
- [CMSHLT-2956](https://its.cern.ch/jira/browse/CMSHLT-2956) [HIN]: Add ZDC1n seeded trigger paths on top of V1.1
- [CMSHLT-2955](https://its.cern.ch/jira/browse/CMSHLT-2955) [HIN]: Change version number of `HLT_HI*_HighRate_v` to "3"

#### PR validation:

TSG integration tests.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Not a backport, but it will be backported to CMSSW_13_2_X.

### CODE REVIEW

**Comment by mmusich** [comment]
enable gpu

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
> DQMHistoSizes: Histogram memory added: -37.752 KiB( 49 files compared)
DQMHistoSizes: changed ( 12434.0,... ): -9.438 KiB HLT/Filters
Checked 214 log files, 167 edm output root files, 50 DQM output files
[TriggerResults](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_14_0_X_2023-11-16-1100+2f5df3/59797/triggerResults): found differences in 4 / 48 workflows

changes look compatible with the removal of certain VBF paths (implemented in [CMSHLT-2887](https://its.cern.ch/jira/browse/CMSHLT-2887) [HIG]: Technical: rationalise VBF-parking triggers )

**Comment by mmusich** [comment]
+hlt
   * see https://github.com/cms-sw/cmssw/pull/43300#issuecomment-1815038315

**Comment by antoniovilela** [comment]
+1

**Comment by mmusich** [comment]
it looks like this update is causing now crashes in several Run2023 relval workflows (see [relval log](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_amd64_gcc12/CMSSW_14_0_X_2023-11-17-2300/pyRelValMatrixLogs/run/141.11_RunHcalNZS2023C/step2_RunHcalNZS2023C.log#/633)). I am having a look. Pity that we don't have enough 2023 real data workflows running in the short matrix.

**Comment by mmusich** [comment]
so also thanks to the @missirol we diagnosed the problem here:

https://github.com/cms-sw/cmssw/blob/9e9d289e9d02ac5302347670783e608f8d12179e/HLTrigger/JetMET/plugins/HLTL1TMatchedJetsVBFFilter.h#L174

that was introduced back in PR https://github.com/cms-sw/cmssw/pull/42543.
When `jetIndices` is equal to `0` , `jetIndices.size() - 1` is not `-1` as the latter is always converted to `unsigned int` and hence the loop never ends.

**Comment by missirol** [comment]
Thanks @mmusich , the bugfix is in #43324 (14_0_X), #43325 (13_3_X) and #43326 (13_2_X).

**Pull request merged**
