### PR TITLE
updating missing pythia6->pythia8 conversions in RelVal workflow

### PR DESCRIPTION
**Pull request by inugent**
This is a patch to fix the missing pythia6->pythia8 noticed in the 7_1_X RelVal which have been reported.

### CODE REVIEW

**Comment by franzoni** [comment]
hello @inugent, would you be willing to rebase this PR ? 
Thanks, g

**Comment by franzoni** [comment]
This PR has been rebased in #9182 
(Ian temporarily out of office)
Once 9182 will be tested and signed, this PR could be closed.

**Comment by boudoul** [comment]
Hi @franzoni and @inugent , I assume this PR can be closed now : #9182 has been merged ~1 week ago ?

**Comment by inugent** [comment]
I do not see why this was not closed if it was merged. I will close it since it is merged.

**Pull request closed without merging**
