### PR TITLE
fix crash in case Limit on the number of clusters is really exceeded.

### PR DESCRIPTION
**Pull request by VinInn**
back port of #14661

@fwyzard

### CODE REVIEW

**Comment by VinInn** [comment]
@cmsbuild , please test

**Comment by fwyzard** [comment]
@VinInn thanks for the quick fix and for the backport.

@cvuosalo, @slava77, could you quickly review and sign ?

@davidlange6 , once all tests and signatures are OK, could you build an 8.0.8 patch release with this fix ?

Thank you,
.Andrea

**Comment by slava77** [comment]
this looks simple enough.
I'd wait for jenkins results and then sign.

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/14662	7ed8ff9
- limits the lifetime of ``` FastFiller spc ``` to avoid overwrites 
- jenkins tests pass and comparisons with baseline show no difference (none expected in single-thread "normal" inputs)

**Comment by davidlange6** [comment]
+1



On 27 May 2016, at 19:51, cmsbuild <notifications@github.com<mailto:notifications@github.com>> wrote:


This pull request is fully signed and it will be integrated in one of the next CMSSW_8_0_X IBs (tests are also fine). This pull request requires discussion in the ORP meeting before it's merged. @slava77<https://github.com/slava77>, @davidlange6<https://github.com/davidlange6>, @degano<https://github.com/degano>, @smuzaffar<https://github.com/smuzaffar>

**Pull request merged**
