### PR TITLE
SubProcess bug fix, updateLookup called too early

### PR DESCRIPTION
**Pull request by wddgit**
#### PR description:

This is a bug fix that should only affect jobs using SubProcess. For ESProducers, the updateLookup function was being called too early. For SubProcesses, there is a late step where sharing of ESProducers is checked and new ESProducers might be created at that point. We have been calling ESProducer::updateLookup just before that so ESProducers constructed at that late time would have missed the call to updateLookup.

This only affects jobs with SubProcess and none of the CMS production jobs use that feature. It is also somewhat of an unusual corner case even in a job with SubProcess. As far as I know, the Core unit tests are the only tests using SubProcess. 

#### PR validation:

Existing unit tests pass.

I noticed this while developing a separate PR. I will submit the other PR in the near future and it contains code modifications that cause existing unit tests to fail because of this bug (that is how I noticed the bug in the first place, it has been lurking there for years).

### CODE REVIEW

**Comment by wddgit** [comment]
please test

**Comment by wddgit** [comment]
please test

Try again. Bunch of DAS Errors.  I don't this could be related to the PR. I see them in one of the IBs also.

**Comment by makortel** [comment]
Looks good to me. @Dr15Jones could you also take a look?

**Comment by wddgit** [comment]
Comparison failures are very similar to those seen in the completely unrelated PR #46859 from about the same time period. So I don't think they are related to this PR.

**Comment by wddgit** [comment]
I added two comments to the code in EventSetupsController.cc as we discussed verbally earlier today. Let me know if there are any more review comments.

**Comment by makortel** [comment]
Comparison differences are related to https://github.com/cms-sw/cmssw/issues/39803 and https://github.com/cms-sw/cmssw/issues/46416

**Comment by makortel** [comment]
+core

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
