### PR TITLE
Made CSCDigiToRawModule a global module

### PR DESCRIPTION
**Pull request by Dr15Jones**
The CSCDigiToRawModule is showing up as a time consuming legacy module in the DIGI workflow and was affecting the CPU efficiency.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
Please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/24052	9fd8aa0
- technical update, as described
- jenkins tests pass and comparisons with the baseline show no differences

**Comment by fabiocos** [comment]
+1

**Pull request merged**
