### PR TITLE
[DD4hep] Fix Compilation Error

### PR DESCRIPTION
**Pull request by ianna**
#### PR description:

* Stream ```string_view``` directly in lambda function to avoid `operator+` on it

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by ianna** [comment]
@mrodozov - FYI

**Comment by ianna** [comment]
please test

**Comment by mrodozov** [comment]
yes that's it, but there are other places with similar dumps, I'll update in 10 mins . At least in one other place in either this file or another file, similar "dumps"

**Comment by mrodozov** [comment]
here is the other file https://github.com/ianna/cmssw/pull/12

**Comment by ianna** [comment]
please test

**Comment by kpedro88** [comment]
+upgrade

**Comment by ianna** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Comment by fabiocos** [comment]
@ianna thanks

**Pull request merged**
