### PR TITLE
another apptainer workaround [13_2_X]

### PR DESCRIPTION
**Pull request by kpedro88**
backport of #45652

### CODE REVIEW

**Comment by kpedro88** [comment]
test parameters
workflows = 10804.31

**Comment by kpedro88** [comment]
please test

**Comment by makortel** [comment]
Thanks @kpedro88. I see we'd need the backport also in
* 13_3_X
* 13_1_X
* 13_0_X
* 12_6_X
* 12_4_X

Although we could discuss if some of these earlier release cycles, e.g. those below, could be dropped
* 13_3_X: latest release 13_3_3 built on 2024-02-21 (although there are commits in 13_3_X branch after that release)
* 12_6_X: latest release 12_6_5 built on 2023-06-07 (although there are commits in 12_6_X branch after that release)

Assuming 13_2_X and 13_1_X release cycles would still need to be kept, maybe we could consider stopping slc7 builds for them? At this point I'd expect the probability to have do IgProf memory profiling on them to be negligible.

Maybe something we could discuss in the ORP next week? @cms-sw/orp-l2 @smuzaffar

**Comment by smuzaffar** [comment]
> Maybe something we could discuss in the ORP next week? @cms-sw/orp-l2 @smuzaffar

sounds good.
@kpedro88 , isn't this already fixed for apptainer 1.3.2  https://github.com/apptainer/apptainer/pull/2220 , https://github.com/apptainer/apptainer/pull/2234 ?

**Comment by kpedro88** [comment]
It's supposed to be fixed, but we are still encountering problems with it. Apptainer no longer wants to support sl7, so I think we just have to rely on ourselves at this point. I am preparing all of the possible backports and will submit them (before going on vacation for several weeks), and then core/ORP can decide which ones to merge.

**Comment by kpedro88** [comment]
#45719
#45720
#45721
#45722
#45723

**Comment by makortel** [comment]
+heterogeneous

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
