### PR TITLE
resolve some issues from static analyzer (mostly in RECO)

### PR DESCRIPTION
**Pull request by slava77**
- clear "using namespace" cases
- nonconst static in a test code in InterpolationDebug (since I didn't find any use cases where it's changing run time)
- MagneticFieldGrid assert the valid range of input grid types to clear reports of possible uninitialized or values used
- mem leak in EndcapPiZeroDiscriminatorAlgo
- some cleanup in Multi5x5BremRecoveryClusterAlgo:
  - assert temp array sizes are above zero (static analyzer can't tell that from a vector::empty() call)
  - const arguments where relevant
  - for auto loops
- some cleanup in ClusterShapeAlgo
  - reduce vector copying 
  - for auto loops
- assert valid range in Basic2DGenericPFlowPositionCalc 

tested in CMSSW_8_0_X_2015-11-30-1100: no differences in comparisons

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by deguio** [comment]
+1

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/12676		5f2128f
- jenkins tests confirmed no changes in monitored quantities

**Comment by davidlange6** [comment]
+1

**Pull request merged**
