### PR TITLE
adding DQM Offline histograms for BTV at HLT

### PR DESCRIPTION
**Pull request by XavierAtCERN**
Adding few histograms for a better monitoring of b-tagging sequences at HLT.
New histograms include:
- difference in the value of the discriminant between online and offline
- offline value of the CSV before and after filter
- CSV of jets passing filters / CSV of all jets
  Few improvements still foreseen

### CODE REVIEW

**Comment by XavierAtCERN** [comment]
Is there any particular reason why this Pull Request hasn't been integrated so far?

**Comment by dmitrijus** [comment]
+1

**Comment by dmitrijus** [comment]
But please, configuration your text editor to emit spaces when you press a tab.

**Comment by davidlange6** [comment]
Hi- @dmitrijus @XavierAtCERN - i second the request for spaces instead of tabs. Please revert the white space changes in this PR. Thanks.

**Pull request closed without merging**
