### PR TITLE
bsunanda:Phase2-hgx73 Add a new scenario with TDR version for HGCal

### PR DESCRIPTION
**Pull request by bsunanda**

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by boudoul** [comment]
Dear @bsunanda , @kpedro88  presumably this file 
https://github.com/cms-sw/cmssw/blob/master/Configuration/Geometry/python/dict2023Geometry.py , should be updated (and used) ?

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by ianna** [comment]
+1

**Comment by kpedro88** [comment]
@bsunanda should there also be a matrix workflow defined for the D13 scenario?

NB, this PR will have to be rebased/updated if #17970 is merged first, due to a change in the M2 geometry.

**Comment by kpedro88** [comment]
@bsunanda I sent you https://github.com/bsunanda/cmssw/pull/11 with the workflow. I tested 10 events of ttbar (24834.0) and it runs fine, no unexpected errors or warnings.

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by ianna** [comment]
+1

**Comment by fabozzi** [comment]
+1

**Comment by kpedro88** [comment]
+1
(since this one seems ready to go and #17970 is not, we can merge this one first and that one will have to update accordingly)

**Comment by Dr15Jones** [comment]
The newly added workflows are failing with the exception 

```
----- Begin Fatal Exception 23-Mar-2017 21:19:18 CET-----------------------
An exception of category 'ProductNotFound' occurred while
   [0] Processing  Event run: 1 lumi: 1 event: 4 stream: 2
   [1] Running path 'digi2raw_step'
   [2] Calling method for module HcalDigiToRaw/'hcalRawDataVME'
Exception Message:
Principal::getByToken: Found zero products matching all criteria
Looking for type: edm::SortedCollection<HcalTriggerPrimitiveDigi,edm::StrictWeakOrdering<HcalTriggerPrimitiveDigi> >
Looking for module label: simHcalTriggerPrimitiveDigis
Looking for productInstanceName: 

   Additional Info:
      [a] If you wish to continue processing events after a ProductNotFound exception,
add "SkipEvent = cms.untracked.vstring('ProductNotFound')" to the "options" PSet in the configuration.

----- End Fatal Exception -------------------------------------------------
```

**Comment by kpedro88** [comment]
@Dr15Jones where are you seeing that? The relval log for 24834.0 in CMSSW_9_1_X_2017-03-23-1100 looks fine to me. (I had also tested it privately before adding it in this PR...)

**Pull request merged**
