### PR TITLE
Changes to implement the new CTagger retraining for PhaseI

### PR DESCRIPTION
**Pull request by smoortga**
This PR changes the c-tagger training files to the new re-trainings for phase I, which were added here: https://github.com/cms-data/RecoBTag-CTagging/pull/5, https://github.com/cms-sw/cmsdist/pull/2939 (currently still testing)

On top of that the training now uses the corrected secondary vertex mass (explaining the switch from False to True in charmTagsComputerCvsL.slComputerCfg.correctVertexMass)

Also jets without any tracks passing the BTV track selection are given a default discriminator value of -2, similarly to what happens for other Taggers.

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by smuzaffar** [comment]
please test with cms-sw/cmsdist#2939
this needs to be tested with external

**Comment by perrotta** [comment]
image
image

Do these plots (from jenkins 25.0_TTbar, taken as an example) mean that with the modified CTagger for a given C efficiency the light-q and b efficiencies are lower? It is a bit hard to understand the content of those validation plots, but if it is so that's good... 
Otherwise, which other differences in these plots should we look at in order to understand whether the update went in the expected direction?

**Comment by slava77** [comment]
On 4/7/17 1:02 PM, perrotta wrote:
> Otherwise, which other differences in these plots should we look at in
> order to understand whether the update went in the expected direction?

"FlavEff" histograms corresponding to ROCs in ttbar and dijet events
should show.

**Comment by smoortga** [comment]
This update should improve the performance of the c-tagger when validated on Phase I samples (are these tests all on Phase I samples?). I am not sure whether red or blue is the new setup.

But yes these plots are indeed ROC curves and they should show a slightly increased performance when evaluated on Phase I samples.

**Comment by smoortga** [comment]
I had to update the PR since I was asked to keep the old trainings available (since potentially v2 legacy miniAODs may happen in 91X) and switch to the Phase I re-training xml files only when Phase I is used.

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
With the latest commit, the discriminator gets reweighted in phase1, as expected, see e.g. for wf 10824.0_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2018_GenSimFull+DigiFull_2018+RecoFull_2018+ALCAFull_2018+HARVESTFull_2018:
immagine

However, also all distributions for non phase1 discriminators gets modified. This must be the effect of setting the tag at -2 if there are less than two tracks. Looking at the several samples produced in the jenkins tests (all low stat, but the behaviour is the same in all them) it looks like that in the current baseline the discriminant in jets with less than two tracks is set at 0.3 in the CvsUDSG comparisons ans at -0.3 in the CvsB comparisons, see e.g. in wf 25.0_TTbar+TTbar+DIGI+RECOAlCaCalo+HARVEST+ALCATT:
immagine
and
immagine
(ok, it is just one entry here... but it is the same in all available non-phase1 samples)

Could you please confirm that the changes observed in the non-phase1 workflows are all expected? Does it makes sense my deduction that discriminants are set to +-0.3 in the current baseline when the number of tracks is less than 2 (which would explain all differences observed in tests)?

**Comment by smoortga** [comment]
@perrotta,
Indeed what we see here is due to the -2 default value (which used to be at around -0.3 for CvsB and +0.3 for CvsL.).

I discussed with the conveners and we would like to keep the Phase 0 tagger as it was before. So it is good that you noticed this because on non Phase I samples indeed the peak should remain at -0.3, 0.3 and not -2,-2.

I will update this PR again. So this time we expect all non-Pahse I tests to be exactly the same as before and all the Phase I tests to be different (both the peak should be shifted to -2,-2 but also the shapes will be different because of the new training xml file).

Cheers
Seth

**Comment by perrotta** [comment]
Uhm... you are going to use the value -2 if there are no tracks for phase one, but also for other future productions (e,g, phase two). Naming the bool "is Phase1" can become misleading then, at some time. 

Why not to name that variable in some "phase independent" way. For example, the first name that comes to my mind is
bool checkForNoTracks
but you will likely be able to find something better.

Just to avoid to set the flag isPhase1=true for phase2 productions...

**Comment by perrotta** [comment]
By the way: could you please post here some perfomance plot with the new settings, compared with the previous ones, made on some large enough stat sample? Even better if you can link the presentation at the BTV meeting in which they were shown and approved.
Thx

**Comment by smoortga** [comment]
Yes I agree that's a good point. I changed the name to "defaultValueNoTracks".

Here is a link to the presentation in which these changes were presented/approved:
https://indico.cern.ch/event/623749/contributions/2517158/attachments/1428063/2192008/BTV_WG_meeting-15-03-2017_ctagger_PhaseI_retraining.pdf
They were also shown during the Physics Plenary (BTV talk) during the CMS week (slide 14):
https://indico.cern.ch/event/627896/contributions/2536030/attachments/1441327/2219114/BTVCMSWeekApr2017.pdf

For your convenience I paste them also inline:
Color code: 
red = Phase 0 training validated on a Phase 0 ttbar sample
green = Phase 0 training validated on a Phase 1 ttbar sample
blue = new Phase 1 re-training validated on a Phase 1 ttbar sample

CvsB ROC curve:
afbeelding

CvsL ROC curve:
afbeelding

I also add the discriminator distributions of the new training for a Phase 1 ttbar sample. (now the color code represents different jet flavours as indicated on the legend)
CvsB:
afbeelding

CvsL:
afbeelding

I will update the PR. Thanks!

**Comment by perrotta** [comment]
please test

**Comment by smoortga** [comment]
I am sorry, I did not spot this typo (cmss.bool instead of cms.bool)

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
+1
Changes as expected in the phase1 workflows 
No effect on non-phase1 wfs, after the last commit

**Comment by davidlange6** [comment]
+1

**Pull request merged**
