### PR TITLE
Phase2 tracker: Bug-fix for clashes in TBPX L2 in T25 and T32

### PR DESCRIPTION
**Pull request by adewit**
#### PR description:

This fixes overlaps between module dead areas in TBPX L2 in T25 and T32 by correcting the positions of the modules in that layer (to align them with the positions as used in T24).

FYI @emiglior @sroychow 

#### PR validation:

- Verified the positions of TBPXL2 modules are the same as in T24 (previous reference)
- Checked a standard workflow with T25 (ie D97) runs 

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Not a backport

### CODE REVIEW

**Comment by sroychow** [comment]
please test

**Comment by mmusich** [comment]
@cms-sw/geometry-l2 @cms-sw/upgrade-l2 out of curiosity, isn't there a way to run automatic tests for overlaps during integration? There is this open issue about it: https://github.com/cms-sw/cmssw/issues/31010, but it doesn't seem it has converged in the desired way.

**Comment by civanch** [comment]
@mmusich , we discussed the issue several times with no final opinion. I think that implementation of this request will require a lot of efforts but the outcome may be less useful. It is difficult to predict what we want to test in advance for each system.

Geometry is a specific area - normally it frozen but for Phase-2 is modified very fast. Just now there is D99 configuration. From my point of view, having unit test running for each PR will increase difficulties - it should be changed for Phase-2 very frequently. In contrary, we are providing  SimG4Core/PrintGeomInfo sub-library, which includes many scripts allowing test as old and very new geometry configurations. It is possible to perform overlap checks, to obtain other geometry information, and also add a new type of checks.

**Comment by mmusich** [comment]
@civanch 
thanks for the reply, perhaps it is worth pursuing the discussion elsewhere

>  It is difficult to predict what we want to test in advance for each system.

I thought it would be sufficient to check for each new geometry that it included in `cmssw` that there are no overlapping volumes with a pre-set level of tolerance. For instance, how was determined the issue at hand here? 
Perhaps I am underestimating the technical complications of this task.

**Comment by civanch** [comment]
+1

**Comment by rappoccio** [comment]
+1

* Regardless of the long-term plan, this one can go in now.

**Pull request merged**
