### PR TITLE
add missing Tc updates before cluster merging

### PR DESCRIPTION
**Pull request by werdmann**
#### PR description:

implement the missing updates of Tc discussed in the context of PR #32764.
This is technically a bug-fix, it removes an unwanted behavior. It was intentionally not included in PR #32764 and scheduled for a separate PR (this one). 

#### PR validation:

Results already discussed in the context of the previous PR #32764 where a version equivalent to this code has been tested.
It was retested on relvals. Small differences observable in a fraction of the events.

### CODE REVIEW

**Comment by silviodonato** [comment]
@werdmann please change the pull request title

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
@werdmann please make a more meaningful title for this PR

**Comment by perrotta** [comment]
+1
- Missing Tc updates before cluser merging were noticed while cleaning the DA clusterizer code in #32764 (it always brings some advantage cleaning the code and maintaining it clean...): the fix for that bug was descoped to a different PR because it may generate some (tiny) difference in outputs, and it was considered easier for bookeping to clearly distinguish it from the bare code cleaning. This PR implements such a fix.
- Jenkins tests pass, and the small differences in outputs of wfs 136.874 and 23234 were already discussed in https://github.com/cms-sw/cmssw/pull/32764#issuecomment-777596405: the small changes are only expected in "a few cases where the estimated Tc is close to the limit" (that's probably why differences in tests only show up in two workflows)

**Comment by qliphy** [comment]
+1

**Pull request merged**
