### PR TITLE
RU CSC segment builder update

### PR DESCRIPTION
**Pull request by nvoytish**
Some bugs omitted and optimization done.
The RU algo switched as the default CSC segment building algorithm.

### CODE REVIEW

**Comment by nvoytish** [comment]
The talk related to this PR can be found here https://indico.cern.ch/event/611671/contributions/2472825/attachments/1411147/2158403/17_02_10-Voytishin_Palichik-CSCSegBuilder_status_before_updating_the_code-RECO_Meeting.pdf

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/17543	66a843a
- implementation in line with the description; the main feature is RU algo switched as the default CSC segment building algorithm
- jenkins tests pass and comparisons with the baseline show differences that start from cscSegments (reduction in number of segments per event mainly in short segments) and propagate downstream to muons, tracks (via muon iterations) and higher level objects.
- local tests with higher statistics and more targeted samples confirm behavior expected as presented in slides in the RECO and CSC meting(s) https://github.com/cms-sw/cmssw/pull/17543#issuecomment-280602736. Some summary and details follow below.

In PU35 ttbar events (wf 10224)
- about 16% fewer cscSegments , mostly the shorter ones are gone
all_sign862vsorig_ttbar13tevpu2017wf10224p0c_cscdetidcscsegmentsownedrangemap_cscsegments__reco_obj_collection__data__degreesoffreedom
- about 16% less pf muons, a reduction mainly in the endcaps as expected (this reduction is balanced out by a matching increase in pf charged hadrons)
all_sign862vsorig_ttbar13tevpu2017wf10224p0c_recopfcandidates_particleflow__reco_obj_eta57

Muon 1TeV gun:
- a factor of 1.5 fewer CSC segments, with reduction mainly in worse quality and shorter segments
wf10009_cscseg_chi2

Multi-track validation plots show roughly unchanged performance for signal muons and some reduction in the muon fake rate. 
- efficiency in 10 GeV muon gun sample (using 2K muons) is apparently down by o(0.1%)
- efficiency in 1 TeV muon gun sample is roughly unchanged (to within o(0.1%) )
- track parameter pulls look roughly the same in the core with some reduction in the tails (as expected from presented slides)

On the technical side, based on PU35 ttbar (10224)
- cscSegments time is up from 1 ms to 3ms per event, still rather negligible
- downstream muon-related module times are down (e.g. cosmics or displaced muons CPU is down by ~10%) for a total of about 0.5% reduction in total reco time

**Comment by ptcox** [comment]
Thanks, Slava. Your summaries are excellent - very useful and informative.  Is it OK to report them to a CSC Meeting?

Tim
________________________________

**Comment by slava77** [comment]
On 2/20/17 12:22 PM, ptcox wrote:
> Thanks, Slava. Your summaries are excellent - very useful and
> informative. Is it OK to report them to a CSC Meeting?

Hi Tim,

Sure, you can pass them along to the CSC community.

		--slava

**Comment by davidlange6** [comment]
+1

**Pull request merged**
