### PR TITLE
enable CSVv2 in combinedMVA instead of CSV

### PR DESCRIPTION
**Pull request by pvmulder**
- CSVv2 is outperforming CSV tagger and should be used as input for combinedMVA tagger
- are we allowed to backport this to 74X? it has an impact on the RECO sequence...

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cmsbuild please test
new IB CMSSW_7_5_X_2015-05-23-1100 is in and seems ok at least on the build side
the last comparison round was affected by the GT inconsistency issue

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/9208	2fb8ec5
- changes in the code are as advertised
- jenkins tests passed, but comparisons were affected by temporary GT inconsistencies
- tested locally in CMSSW_7_5_X_2015-05-19-2300 /test area sign557/: comparisons with the baseline show differences only in b-tagging related variables in fwlite-based comparisons [apparently there are no plots in DQM/validation for the combined MVA]
e.g pfCombinedMVABJetTags in ttbar events the bump in high values is a more visible (likely b-jets)
all_sign557vsorig_ttbarpuwf202p0c_recojetedmreftobaseprodtofloatsassociationvector_pfcombinedmvabjettags__reco_obj_data_97
and in QCD dijets (15 to 3 TeV flat) 
all_sign557vsorig_qcd13tevflatpt15s3000wf1338p0c_recojetedmreftobaseprodtofloatsassociationvector_pfcombinedmvabjettags__reco_obj_data_97

**Comment by davidlange6** [comment]
+1

**Pull request merged**
