### PR TITLE
rename jettoolbox_cfg.py to testJettools_cfg.py to avoid confusion

### PR DESCRIPTION
**Pull request by alefisico**
New version is a stand-alone package here: https://github.com/cms-jet/JetToolbox

### CODE REVIEW

**Comment by slava77** [comment]
this was a good test file to check  jet-related algorithms not included in standard workflows.
What can we use now during integration?

**Comment by ahinzmann** [comment]
The motivation to remove it from the release it is that it is outdated and causes confusion, while a better version is in the works.
It is indeed useful for tests. How about just renaming it to testJetTools_cfg.py

**Comment by slava77** [comment]
What prevents you from having this file more up to date with the release?
Unless the file goes out of date on a 1-week time scale all the time, the release schedule is typically frequent enough to be up-to-date.

**Comment by ahinzmann** [comment]
It is up-to-date in terms of algorithms and code in CMSSW and we should be keep it like this for test.
However, the user interface (using python functions rather than a simple config) develops.

**Comment by slava77** [comment]
OK, so this PR should be updated then, renaming the file to testJetTools_cfg.py, right?

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
+1

For #9291 05acff6ad184ee34bcd98719b88912e9f46cb238

Renaming file to reflect that its package has become stand-alone. No changes to standard workflows should occur.

Jenkins [tests](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-9291/5063/summary.html) against baseline CMSSW_7_5_X_2015-05-26-2300 show no significant differences, as expected.

**Comment by cvuosalo** [comment]
@alefisico: Please revise the title of this PR to reflect the fact that the file is being renamed, not removed.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
