### PR TITLE
HCALDQM: Monitor bad capid rotation, uHTR/L1T mismatches (10_2_X)

### PR DESCRIPTION
**Pull request by DryRun**
Adds the following, mostly related to the issues seen so far in 2018:
- Monitor bad capid rotation. (BX - capid) % 4 should be a constant.
- Monitor uHTR-L1T mismatches. This is copied straight from the L1T DQM code, but it's extremely useful for HCAL.

Minor additions:
- Add LED pin diode plots to local DQM.
- UMNioTask now handles LED events correctly, instead of labeling them HF.
- Implement code rule check as suggested by Fabio. These were all "using namespace * in header" violations, which were fairly ubiquitous in the HcalCommon infrastructure.

### CODE REVIEW

**Comment by dmitrijus** [comment]
+1

**Comment by DryRun** [comment]
Sorry for the noise - the RelVals error should be fixed now, and I'll stop touching the PR.

**Comment by dmitrijus** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
