### PR TITLE
[13_2_X] Fix for pixel FED error imbalance in DQM plots

### PR DESCRIPTION
**Pull request by ferencek**
#### PR description:

Backport of https://github.com/cms-sw/cmssw/pull/42872

### CODE REVIEW

**Comment by mmusich** [comment]
test parameters:
   * enable = gpu
   * workflows_gpu = 11634.503, 11634.507, 11634.583, 11634.587, 11634.593
   * relvals_opt_gpu = --what upgrade,standard,highstats,pileup,generator,extendedgen,production,ged,machine,premix,nano
   * addpkg = DQM/Integration

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
type bug-fix

**Comment by jfernan2** [comment]
+1

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
