### PR TITLE
Use C++ concepts to deduce data product attributes

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

- Use concepts for attributes used by Wrapper
- Use concepts to discover post_insert method

#### PR validation:

Code compiles and framework unit tests pass.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
This does the same sort of refactoring as #45753 but uses C++ 20 concepts instead.

**Comment by makortel** [comment]
Comparison failures are related to https://github.com/cms-sw/cmssw/issues/39803

**Comment by makortel** [comment]
Since this PR worked fine with e.g. `rootcling`, I'd proceed with it and close the https://github.com/cms-sw/cmssw/pull/45753

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
