### PR TITLE
Recover 2016 Hcal Trigger Primitives

### PR DESCRIPTION
**Pull request by matz-e**
Partially reverts a commit that caused us to loose 2016 Hcal trigger primitives while solving a collision with the 2017 TP geometry.

This re-instates the code that was in place up to `CMSSW_8_1_0_pre6`, and which is able to re-emulate 2016 TP. It solves collisions in dense ID for 2017 by marking Hcal trigger towers with `abs(ieta) == 29 && version == 0` as invalid. HCAL HE in 2017 will not include a tower at `ieta` 29, and neither will HCAL HF.

@bsunanda, can you have a look at this?

### CODE REVIEW

**Comment by abdoulline** [comment]
@civanch 
could you, please, start test(s)

**Comment by civanch** [comment]
please test

**Comment by abdoulline** [comment]
@bsunanda
I forgot to ask you in person yesterday at Phase1 TF -  to look at Topology changes in this PR. 
Could you, please, do it at your convenience?

**Comment by bsunanda** [comment]
@civanch @abdoulline @davidlange6 The important parts are validHT and dense indexing which are corrected. Please do accept the PR

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
