### PR TITLE
Migrate HitPattern to use TrackerTopology (62X_SLHCDEV)

### PR DESCRIPTION
**Pull request by makortel**
Backport of #9959: This PR migrates HitPattern to use TrackerTopology instead of the tracker DetId classes. In contrast to 76X/#9959, here in 62X HitPattern is always filled from DetIds from hits, so it was enough to percolate TrackerTopology to all places where HitPattern is filled.

Tested in CMSSW_6_2_SLHCDEV_X_2015-06-23-2300 with wfs 10000, 10200, 10400, 11200, 11400, 11600, 12000, 13000. I have the alternative-comparisons' results here (black=old, red=new)
- https://mkortela.web.cern.ch/mkortela/tracking/trackerTopologyHitPattern_slhcdev_result_10000.pdf
- https://mkortela.web.cern.ch/mkortela/tracking/trackerTopologyHitPattern_slhcdev_result_10200.pdf
- https://mkortela.web.cern.ch/mkortela/tracking/trackerTopologyHitPattern_slhcdev_result_10400.pdf
- https://mkortela.web.cern.ch/mkortela/tracking/trackerTopologyHitPattern_slhcdev_result_11200.pdf
- https://mkortela.web.cern.ch/mkortela/tracking/trackerTopologyHitPattern_slhcdev_result_11400.pdf
- https://mkortela.web.cern.ch/mkortela/tracking/trackerTopologyHitPattern_slhcdev_result_11600.pdf
- https://mkortela.web.cern.ch/mkortela/tracking/trackerTopologyHitPattern_slhcdev_result_12000.pdf
- https://mkortela.web.cern.ch/mkortela/tracking/trackerTopologyHitPattern_slhcdev_result_13000.pdf

Of these, 10000, 10200, 11200, 11600 give equal results, and 10400, 11400, 12000, 13000 show differences. I haven't taken too deep look on the geometry differences between the workflows, but maybe in the latter 4 the changes are expected?

@rovere @VinInn @boudoul @venturia

### CODE REVIEW

**Comment by mark-grimes** [comment]
Does the templated constructor at [HitPattern.h#L146](https://github.com/makortel/cmssw/blob/trackerTopologyHitPattern_slhcdev/DataFormats/TrackReco/interface/HitPattern.h#L146) also need ttopo?  I guess it's never used otherwise the inline `set(c);` would cause a compiler error.  Can we either remove the constructor or add ttopo if it's going to be used in future?

(couldn't seem to add this as a line comment since the line is not part of the diff)

**Comment by makortel** [comment]
Good catch. I think it should be removed, as there was/is no single-argument overload of `set()` (and such a constructor does not exist anymore in 76X in the redesigned HitPattern).

**Comment by mark-grimes** [comment]
Okay, whichever you think best.  Other than that it all looks good but I'll run a few tests.

**Comment by makortel** [comment]
And here is the commit.

**Comment by mark-grimes** [comment]
merge

This pulls in 309 packages so it's too much test privately, and the automatic tests need updating.  Stick it in the IB and then test, if there's a problem we'll roll back.

**Pull request merged**
