### PR TITLE
BeamSpotOnline updates

### PR DESCRIPTION
**Pull request by francescobrivio**
#### PR description:
Implementing few updates to the BeamSpotOnline to fix some bugs spotted during last MWGR.
In `BeamMonitor/FakeBeamMonitor`:
- Improved the information logged to condDB
- Set meaningful exit codes in case of errors

In the beasmpot clients:
- Made the BeamSpotOnline tag and jobName options configurable so that they are automatically set when running in the playback system
- Removed the `noDB` option and aligned the `beam_` and `beamhlt_` clients to the fake clients
- Implemented `omsServiceUrl` in all clients
- In `beam_dqm_sourceclient-live_cfg.py` the parameter `DBParameters.authenticationPath` from the GT module was set to an empty string (`''`) and was conflicting with the same parameter in the OnlineDBOutputService module (set to `'.'`). Now they are both set to `'.'` so there should not be any conflict.

#### PR validation:
Some of these updates were already successfully tested during last MWGR (e.g. tag/jobName in playback). The others have been tested running the unitTest on lxplus.

#### Backport
#32415

### CODE REVIEW

**Comment by francescobrivio** [comment]
FYI @gennai

**Comment by jfernan2** [comment]
please test

**Comment by silviodonato** [comment]
@francescobrivio @gennai we see some random failure in the unit test of the BeamSpotOnline (see https://github.com/cms-sw/cmssw/issues/31896). Do you think this PR might solve the issue?

**Comment by francescobrivio** [comment]
> @francescobrivio @gennai we see some random failure in the unit test of the BeamSpotOnline (see #31896). Do you think this PR might solve the issue?

Hi @silviodonato no this PR does not address that issue. 
However we are working with @ggovi to address these failures reported in #31896 .

**Comment by silviodonato** [comment]
kind reminder @cms-sw/dqm-l2

**Comment by jfernan2** [comment]
@silviodonato  this PR is a forwardport of https://github.com/cms-sw/cmssw/pull/32415 which has just been tested at P5 with some errors, so we should wait for some fix

**Comment by francescobrivio** [comment]
Rebased and fixed one of the errors reported in https://github.com/cms-sw/cmssw/pull/32408#issuecomment-744542551

**Comment by qliphy** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
