### PR TITLE
[HLT] [CLANG] Fix warnings reported by llvm16 in CLANG IBs

### PR DESCRIPTION
**Pull request by smuzaffar**
Fixed set but unused warnings from clang-16 in CLANG IBs

### CODE REVIEW

**Comment by missirol** [comment]
please test

**Comment by missirol** [comment]
@smuzaffar , I don't know if you think it's useful to test this for "CLANG_X" or other non-standard builds.

If so, feel free to start those tests. (I didn't do it because the fixes seem straightforward)

**Comment by smuzaffar** [comment]
> @smuzaffar , I don't know if you think it's useful to test this for "CLANG_X" or other non-standard builds.
> 
> If so, feel free to start those tests. (I didn't do it because the fixes seem straightforward)

No, there is no need to test these PR against CLANG_X IBs. If chanegs look reasonable then test for default/master IBs should be enough

**Comment by missirol** [comment]
+hlt

**Comment by missirol** [comment]
please test

47459 unexpected (?) DQM differences in wf `23634.911`. I don't think this PR can explain it (so I'm not holding it), but I'd be curious to see what happens rerunning the tests.

**Comment by perrotta** [comment]
+1

**Comment by perrotta** [comment]
+1

**Comment by missirol** [comment]
> 47459 unexpected (?) DQM differences in wf `23634.911`. I don't think this PR can explain it (so I'm not holding it), but I'd be curious to see what happens rerunning the tests.

Same discrepancies after running the tests a 2nd time. I can only guess that the non-reproducibility hit the baseline (?).

**Pull request merged**
