### PR TITLE
Phase2-hgx329B Remove reference to FastTimeGeometry from Fireworks - this is an obsolete reference, never used and never will be

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Remove reference to FastTimeGeometry from Fireworks - this is an obsolete reference, never used and never will be. A few variables and methods are left for future implementation of BTL and ETL geometries

#### PR validation:

No reference was found which uses the deleted code

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@fabiocos I have removed reference to FastTimeGeometry from Firework. I see BTL and ETL are not included in it as yet. Please make use of the existing hooks there

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by fabiocos** [comment]
@bsunanda thanks, I will follow up on this for BTL/ETL

**Comment by alja** [comment]
@bsunanda
I don't know who added FastTimeGeometry in reco geometry producer. Perhaps someone will miss that information.
How do we know it is obsolete for the case of event display?

**Comment by bsunanda** [comment]
@alja I introduced FastTimeGeometry long ago before MTD was a project. Now all geometry routines for mTD are different and FastTimeGeometry is in the process of removal. It is really obsolete and will never be used. I informed MTD convenor @fabiocos to introduce the relevant parts for MTD (the new name for FastTime detector) to introduce the relevant parts there. The first step is the removal of FastTimeGeometryy reference. I shall remove all FastTimeGeometry class in the next step. So kindly approve this PR

**Comment by fabiocos** [comment]
@bsunanda @alja since all the MTD sensors are ultimately boxes, it should be relatively simple to fill the ```FWRecoGeometry``` with the vertices of the corresponding ```GeomDet```. They have indeed an internal structure treated through a topology class (individual crystals in a module for BTL and pixels within LGAD for ETL), but I am not sure we need to take this into account within Fireworks

**Comment by alja** [comment]
+1

Thanks Sunanda and Fabio for the information.

**Comment by perrotta** [comment]
+1

**Pull request merged**
