### PR TITLE
Modernized dictionary generation in DataFormats

### PR DESCRIPTION
**Pull request by Dr15Jones**
-removed the use of the `struct dictionary`
-removed usage of pattern from classes_def.xml

This should aid in transitioning to ROOT's new module system.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by mommsen** [comment]
+1

**Comment by andrius-k** [comment]
+1

**Comment by Dr15Jones** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/25826	bdf5035
- code changes are in line with the PR description. 
- jenkins tests pass and comparisons with the baseline show no differences

**Comment by Martin-Grunewald** [comment]
+1

**Comment by Dr15Jones** [comment]
@nsmith- @rekovic @franzoni @pohsun @tocheng @ santocch @fgolf @peruzzim please review

**Comment by fabiocos** [comment]
@santocch @peruzzim @fgolf @rekovic @tocheng could you please check? This looks a simple technical move parallel to others we are doing

**Comment by santocch** [comment]
+1

**Comment by rekovic** [comment]
Needs rebase.

**Comment by rekovic** [comment]
otherwise 
+1

**Comment by fabiocos** [comment]
@Dr15Jones after the merge of #25616 DataFormats/CTPPSAlignment there is a conflict induced by the removal of the DataFormats/CTPPSAlignment package. Sorry for this, could you please just rebase your PR? At this point I think it should just move forward

**Comment by peruzzim** [comment]
+xpog

It's ok from xpog as long as it's just technical changes in DataFormats (but I guess signatures will be reset once the conflict is fixed).

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
@fabiocos I did the rebase which was just removing the classes.h file from the package that was removed. Everything else is the same.

**Comment by Dr15Jones** [comment]
+1

**Comment by slava77** [comment]
@cmsbuild please test

to get cleaner comparisons

**Comment by pohsun** [comment]
+1

**Comment by Dr15Jones** [comment]
@fabiocos what is your thoughts on integrating this? Do you want all new signatures now that the merge conflict has been fixed or just accept the original signatures?

**Comment by kpedro88** [comment]
+1

**Comment by kpedro88** [comment]
merge

**Comment by andrius-k** [comment]
+1

**Comment by santocch** [comment]
+1

**Comment by jfernan2** [comment]
+1

**Pull request merged**
