### PR TITLE
[14_0_X] Monopole SKIM updates for Run 3

### PR DESCRIPTION
**Pull request by ThOliveira23**
PR description:

Provide an update to the trigger paths to be employed in the MONOPOLE SKIM file for the Run 3. The additional inclusion of trigger paths associated with MET can be mentioned.
Additionally, the inclusion of the EXOMONOPOLE SKIM file to be executed in the MET and JetMET datasets for the Run 3.

PR validation: The PR was validated through the the basic test procedure available in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

This PR is a backport of https://github.com/cms-sw/cmssw/pull/45134 for the release 14_0_X.

### CODE REVIEW

**Comment by ThOliveira23** [comment]
FYI: @malbouis, @srimanob, @CarstenHensel

**Comment by AdrianoDee** [comment]
@ThOliveira23 which is the runTheMatrix wf using this skim (if any)?

**Comment by srimanob** [comment]
Should PR go to master first?

**Comment by ThOliveira23** [comment]
> @ThOliveira23 which is the runTheMatrix wf using this skim (if any)?

Dear @AdrianoDee, I'm not sure if I understood the question.

**Comment by malbouis** [comment]
> @ThOliveira23 which is the runTheMatrix wf using this skim (if any)?

Hi @AdrianoDee , for the DATA workflows, I think any workflow running the `SKIM:EGamma* ` or `SKIM:JetMET* ` datasets will run it due to the autoSkim matrix.

**Comment by AdrianoDee** [comment]
> Dear @AdrianoDee, I'm not sure if I understood the question.

Yes sorry I was a bit obscure, I was "jargony" referring to the workflows we could use to test this setup in the release Helena kindly pointed to them. Anyway as @srimanob was mentioning, would be better if you can open the corresponding PR to `master`. And also make it clear in the title this PR is to `14_0_X` (few examples: you can simply prepend `[14_0_X]` to it as in, e.g., https://github.com/cms-sw/cmssw/pull/45115)

**Comment by ThOliveira23** [comment]
> Hi @ThOliveira23 , just make sure if the update is for full Run3 or just 2024. And from your skim config, you mention that the updating aims at 2024, but there is no MET dataset in 2024 as it's merged into JetMET.
> 
> On the other hand, I also roughly check your HLT Paths but it seems that `HLT_PFMET170_HBHECleaned_v*`, `HLT_PFMET300_v*` are only for 2016 data taking and `HLT_PFMET250_HBHECleaned_v*` and `HLT_PFMET200_HBHE_BeamHaloCleaned_v*` are only for 2017 and 2018 data taking. Could you please check if the paths are what you expect in 2024 (or full Run3 I could say)?


Dear @youyingli, these updates are meant to cover all the Run 3, not only 2024. If I understood and implemented correctly, there is MET and JetMET for 2022 and only JetMET for 2023 (and 2024). In that sense, the idea is execute the Monopole SKIM in all the MET datasets of the Run 3. 

Concerning the trigger paths: The expected trigger paths for the Run 3 `HLT_PFMET200_BeamHaloCleaned_v*` and the `HLT_Photon200_v*`. If the trigger paths concerning the Run 2 (2016 and 2017, 2018) aren't necessary, I think that they can be removed from the skim config file.

**Comment by srimanob** [comment]
@cmsbuild please test

**Comment by youyingli** [comment]
Hi @cms-sw/pdmv-l2, could you please sign this PR?

**Comment by sunilUIET** [comment]
+pdmv

**Comment by antoniovilela** [comment]
Please add a link to the master PR in the description, and indicate this is a backport.

**Comment by ThOliveira23** [comment]
The PR description was updated. The backport indication and the link of the PR for the master were added.

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
