### PR TITLE
[BeamSpot] fit 1D projections of PV distribution to get initial values for 3D fit parameters

### PR DESCRIPTION
**Pull request by rmanzoni**
back porting https://github.com/cms-sw/cmssw/pull/10780

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
+1

For #10781 4d421deec7cf90028adfa35815731357ea4f8b71

Changing the initial values of the primary vertex fit. The 76X version of this PR, #10780, has already been approved by Reco.

The code changes are satisfactory. Jenkins tests against baseline CMSSW_7_5_X_2015-08-14-1100 show very small changes in PV fit results, but none of these differences are significant. See #10780 for an example plot of the small changes in the fit results.

**Comment by diguida** [comment]
+1
for https://github.com/cms-sw/cmssw/commit/4d421deec7cf90028adfa35815731357ea4f8b71

The correspondent version in 76X #10780 has already been approved by AlCa.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
