### PR TITLE
[HLT] add tau3mu trigger DQM

### PR DESCRIPTION
**Pull request by rmanzoni**
back port of #20026

### CODE REVIEW

**Comment by mtosi** [comment]
tracked by https://github.com/cms-sw/cmssw/issues/19142

**Comment by fwyzard** [comment]
hold

**Comment by fwyzard** [comment]
please merge #19961 before merging any other HLT DQM PR on 9.2.x, and then rebase them

**Comment by rmanzoni** [comment]
@fwyzard just to make sure: this is a message to @davidlange6, not to me, correct?
Or do you want me to merge topic #19961 and then push again?

**Comment by davidlange6** [comment]
Your PR is unmergeable. Please have a look and possibly rebase it.

**Comment by davidlange6** [comment]
CMSSW_9_2_X developement work is completed. Closing remaining PRs

**Pull request closed without merging**
