### PR TITLE
Fastsim prepare datamixer for fastsim

### PR DESCRIPTION
**Pull request by lveldere**
prepare DataMixingModule to mix tracks, required for PU mixing in FastSim.
The old and incomplete DataMixingGeneralTrackWorker is replaced with the RecoTrackAccumulator,
already in use to mix tracks for FastSim inside the MixingModule.

This change is required in 74X.

### CODE REVIEW

**Comment by lveldere** [comment]
please test

**Comment by lveldere** [comment]
@mdhildreth 

Hi Mike
To verify that my changes have no impact on FullSim,
I'd like to do a 10 event FullSim production before and after my pr,
and check there is no change at all.
Could you tell me which runTheMatrix wfs

**Comment by lveldere** [comment]
@mdhildreth @civanch 

I'm verifying that this has 0 impact on FullSim by running
runTheMatrix -l 250200.0
before and after changes, and looking at some track and rechit observables.

**Comment by lveldere** [comment]
+1

I ran the FullSim premix worflow 250200.0 before and after changes.

I compared track collections (pt, eta, nhits)
and all calo rechit collections (energy, time)
and found not a single difference.

**Comment by lveldere** [comment]
@mdhildreth @civanch this pr is ready for your review

**Comment by mdhildreth** [comment]
+1

**Comment by lveldere** [comment]
@davidlange6 

Hi David

Did you decide whether this can go in 74 at this moment?

Lukas

**Comment by lveldere** [comment]
superseded by #8490
backport to 74 after validation in 75

**Pull request closed without merging**
