### PR TITLE
bugfix - xml tag in PPS strips mapping

### PR DESCRIPTION
**Pull request by ChrisMisan**
#### PR description:
PR adds a missing closing tag to the strips xml mapping.

#### PR validation:
relvals 136.793, 136.874

#### if this PR is a backport please specify the original PR and why you need to backport that PR:
no

### CODE REVIEW

**Comment by francescobrivio** [comment]
type bugfix

**Comment by francescobrivio** [comment]
test parameters:

 - workflows = 136.793, 136.874

**Comment by francescobrivio** [comment]
@cmsbuild please test

**Comment by francescobrivio** [comment]
@ChrisMisan please open a backport to 12_3_X also! thanks!

**Comment by tvami** [comment]
@cmsbuild , please test

 > The relvals timed out after 4 hours.

**Comment by francescobrivio** [comment]
+alca

 - tests are clean except the usual known differences in MTD comparisons (unrelated to this PR)

**Comment by perrotta** [comment]
+1

**Pull request merged**
