### PR TITLE
Switch to TICLv4 for offline HGCAL electrons and photons

### PR DESCRIPTION
**Pull request by SohamBhattacharya**
#### PR description:

This PR switches to TICLv4 for offline HGCAL electrons and photons.

The following plots were obtained using these samples:
- `SingleElectron_Pt-2To200-gun/PhaseIISpring22DRMiniAOD-PU200_123X_mcRun4_realistic_v11-v1/GEN-SIM-DIGI-RAW-MINIAOD`
- `SinglePhoton_Pt-2To200-gun/PhaseIISpring22DRMiniAOD-PU200_123X_mcRun4_realistic_v11-v1/GEN-SIM-DIGI-RAW-MINIAOD`

Expected consequences:
* The electron reco efficiency should increase:
   

* The photon reco efficiency should increase:
   

* The electron mis-reco (i.e. reco electrons not $\Delta R$ matched to any gen-electron) efficiency should not change much:
  

* The photon mis-reco (i.e. reco-photons not $\Delta R$ matched to any gen-photons) efficiency should not change much:
  

* The electron and photon energy responses (recoE/genE) should remain fairly the same.

@swagata87 @rovere @felicepantaleo

### CODE REVIEW

**Comment by rovere** [comment]
@cmsbuild please test

**Comment by AdrianoDee** [comment]
assign upgrade
(to have the tag)

**Comment by AdrianoDee** [comment]
@cmsbuild enable profiling

**Comment by rovere** [comment]
@cmsbuild please test

**Comment by rovere** [comment]
@SohamBhattacharya thanks! the timing went down considerably as well with this PR.

**Comment by swagata87** [comment]
indeed, I am looking at [WF 21034.21](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-d82430/28425/profiling/21034.21/RES_CPU_compare_21034.21.txt), and there are some timing reductions for electron related modules. For example: 
```
Rank			Total%	 		Cumulative					Delta						Symbol name
[1    -> 23  ] [5.9    -> 0.7   ]  [102.23    -> 10.03    ]         [ 10.03    /1456.79   - 102.23   /1732.13   *100% ] = [-5.21 % ]         ElectronSeedProducer::produce    
                 
[0    -> 0   ] [14.2   -> 13.1  ]  [246.21    -> 190.39   ]         [ 190.39   /1456.79   - 246.21   /1732.13   *100% ] = [-1.15 % ]         cms::CkfTrackCandidateMakerBase::produceBase      
```

**Comment by clacaputo** [comment]
+reconstruction

- clear reduction in cpu timing for `21034.21` https://github.com/cms-sw/cmssw/pull/39810#issuecomment-1288053860
- some minor differences in reco `slimmedElectronsHGC` mostly due to changes in the number of entries

**Comment by AdrianoDee** [comment]
+upgrade
- addressing https://github.com/cms-sw/cmssw/issues/39482

**Comment by perrotta** [comment]
+1

**Pull request merged**
