### PR TITLE
[HeaderCheck][ANA][RECO] Remove obsolete headers

### PR DESCRIPTION
**Pull request by smuzaffar**
Deleted obsolete header.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/26808	b12337a
- cleanup of not very useful (CommonTools/UtilAlgos/interface/TFileDirectory.h ) or unusable/broken headers (ChargeSelector.h)
- jenkins tests pass

**Comment by santocch** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
