### PR TITLE
Run3-sim77 Update the checking code for dd4hep vs ddd

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

 Update the checking code for dd4hep vs ddd

#### PR validation:

Used in checking the SimHit production for ECAL and HCAL

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
@bsunanda , do you have an explanation for regression. I would not expect change of results if it is only extension of geometry checks.

**Comment by silviodonato** [comment]
urgent
(see https://github.com/cms-sw/cmssw/pull/32201#issuecomment-733162813)

**Comment by silviodonato** [comment]
please test 
I saw fake changes in other PR as well

**Comment by silviodonato** [comment]
> please test
> I saw fake changes in other PR as well

eg. https://github.com/cms-sw/cmssw/pull/32258#issuecomment-733152085

**Comment by bsunanda** [comment]
@civanch I cannot think of any reason why this PR can affect regression results. The only changed code which appears in the workflows is ECalSD and the change refers to the change in the test code which does not affect regular workflows; ddd or dd4hep. So the changes if seen are due to other PR's

**Comment by silviodonato** [comment]
@bsunanda @civanch see https://github.com/cms-sw/cmssw/issues/32283

**Comment by bsunanda** [comment]
@silviodonato @civanch Any difference in dd4hep workflow should be ignored as of now. Once dd4hep workflows are studied in detail differences in those workflows should be taken seriously.

**Comment by civanch** [comment]
@bsunanda , it is true for any other DD4Hep PR but for this one I am confused.

**Comment by civanch** [comment]
+1

I do not see how EcalSD modification can affect results, so let us ignore DD4Hep comparisons

**Comment by silviodonato** [comment]
+1

**Pull request merged**
