### PR TITLE
Updates to DT, PF hadron, HCAL, PPS and pixel calibrations for 2018 UL

### PR DESCRIPTION
**Pull request by christopheralanwest**
#### PR description:

This PR updates most of the conditions for the 2018 UL that are not dependent on the tracker alignment. For 2018 data, this includes the DT, PF hadron, HCAL, PPS and pixel calibrations. For 2018 MC, only the PF hadron calibration and pixel bad components are updated. ECAL conditions are not included because the ECAL intercalibration is not ready.

GT candidates are used rather than versioned GTs because it is not clear whether this PR or #27644 would be merged first and I would like to avoid the confusion of out-of-order GT versions.

For data, only 2018 IOVs are modified. Consequently, only 2018 data and MC should be affected by this PR.

GT diffs (data):
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/110X_dataRun2_v2/110X_dataRun2_2017_2018_Candidate_2019_08_03_03_51_45
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/110X_dataRun2_relval_v2/110X_dataRun2_relval_Candidate_2019_08_03_03_55_32
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/110X_dataRun2_PromptLike_HEfail_v1/110X_dataRun2_PromptLike_HEfail_Candidate_2019_08_02_16_55_52
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/110X_dataRun2_PromptLike_v1/110X_dataRun2_PromptLike_Candidate_2019_08_02_16_53_14
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/110X_dataRun2_PromptLike_HI_v1/110X_dataRun2_PromptLike_HI_Candidate_2019_08_02_16_55_18

GT diffs (MC):

https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/110X_upgrade2018_realistic_v1/110X_upgrade2018_realistic_Candidate_2019_08_03_11_37_17
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/110X_upgrade2018_realistic_HEfail_v1/110X_upgrade2018_realistic_HEfail_Candidate_2019_08_03_11_39_50

#### PR validation:

The payload validation has been described in sign-off talks at AlCa meetings:

DT: https://indico.cern.ch/event/832785/contributions/3489416/attachments/1876295/3097194/20190626_DTCalib_AlCaDBmeeting_SGhosh_v2.pdf
PF hadron: https://indico.cern.ch/event/834090/contributions/3495432/attachments/1880854/3098893/PFHadronCalibration_Alca_DB_15_July_2019.pdf 
HCAL: https://indico.cern.ch/event/832785/contributions/3489397/attachments/1876358/3089810/Hcal_UL_2016_2018_July8_v1.pdf
PPS: https://indico.cern.ch/event/835589/#27-pps-calibration-sign-off-fo
Pixel: https://indico.cern.ch/event/834561/#25-tracker-sign-off-for-2018-u , https://indico.cern.ch/event/835589/contributions/3513525/attachments/1887574/3112176/20190729_AlCaDB_UL18FollowUp.pdf 

In addition, a technical validation of the autoCond modifications has been performed: `runTheMatrix.py -l limited -i all --ibeos`

#### if this PR is a backport please specify the original PR:

This is not a backport, though a 10_6_X backport will be needed.

### CODE REVIEW

**Comment by christopheralanwest** [comment]
please test

**Comment by mmusich** [comment]
@christopheralanwest 
> This PR updates most of the conditions for the 2018 UL that are not dependent on the tracker or tracker alignment

Why?

**Comment by christopheralanwest** [comment]
@mmusich Are you asking why I am updating these conditions or why I am currently excluding the tracker+tracker alignment?

The updates contained are independent of any forthcoming updates for the 2018 UL and so there's no reason not to introduce them now.

As for the reason that tracker conditions are excluded: I would have included them but I was told at the tracker sign-off talk (I don't remember by whom) that it didn't make sense to update the tracker conditions without the updated tracker alignment. I can't include the tracker alignment tags here because the 2018 tracker alignment tags that also include the full history are not available. Since the tags include only 2018 IOVs, their inclusion would crash RelVals that run on earlier years.

If I have misunderstood something, please feel free to correct me.

**Comment by mmusich** [comment]
The Pixel bad components are independent from the Tracker Alignment, and the 2D Template tag that has been requested (3 months ago) is coupled to the 1D template tag already in GT (it would actually solve an inconsistency currently present in the GT).

**Comment by christopheralanwest** [comment]
> The Pixel bad components are independent from the Tracker Alignment, and the 2D Template tag that has been requested (3 months ago) is coupled to the 1D template tag already in GT (it would actually solve an inconsistency currently present in the GT).

I hadn't appreciated that the offline GT had already been updated with _new_ conditions for the 2018 UL. For the 2017 UL validation campaign there was a comparison between the UL and both the EOY re-reco and reconstruction in 10_6_X with "pre-UL" conditions. For the 2018 UL validation, we will likely want to do the same, and so we need a consistent 2018 GT.

To construct a consistent "pre-UL 2018" GT for the comparisons with a 10_6_X baseline, ideally we would use tags that had the same 2018 history has those prior to the 2017 UL preparation. Do such tags exist? If not, what is the _minimal_ consistent 10_6_X GT? Would that be `102X_dataRun2_v18` +  `SiPixel2DTemplateDBObject_38T_v3_offline` (label=`numerator`)? Or is the pixel quality tag `SiPixelQuality_v07_offline` necessary for a consistent GT as well?

I've updated the PR to include the also the following two tags:

`SiPixel2DTemplateDBObject_38T_v3_offline` (label=`numerator`)
`SiPixelQuality_v07_offline`

for `auto:run1_data` and `auto:run2_data`. The diffs relative to the candidates previously used in this PR are:

https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/110X_dataRun2_2017_2018_Candidate_2019_08_02_16_26_41/110X_dataRun2_2017_2018_Candidate_2019_08_03_03_51_45 
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/110X_dataRun2_relval_Candidate_2019_08_02_16_31_52/110X_dataRun2_relval_Candidate_2019_08_03_03_55_32 

For the MC GTs, I've added:

`SiPixelStatusScenarios_UltraLegacy2018_v0_mc`
`SiPixelQualityProbabilities_UltraLegacy2018_v0_mc`

to the `auto:phase1_2018_realistic` and `auto:phase1_2018_realistic_HEfail` GTs. The diffs relative to the candidates previously used in this PR are:

https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/110X_upgrade2018_realistic_Candidate_2019_08_02_16_44_50/110X_upgrade2018_realistic_Candidate_2019_08_03_04_00_02
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/110X_upgrade2018_realistic_HEfail_Candidate_2019_08_02_16_45_22/110X_upgrade2018_realistic_HEfail_Candidate_2019_08_03_04_03_44

**Comment by christopheralanwest** [comment]
please test

**Comment by mmusich** [comment]
> I hadn't appreciated that the offline GT had already been updated with _new_ conditions for the 2018 UL. For the 2017 UL validation campaign there was a comparison between the UL and both the EOY re-reco and reconstruction in 10_6_X with "pre-UL" conditions. For the 2018 UL validation, we will likely want to do the same, and so we need a consistent 2018 GT.

I tend to think the only sensible comparison for UL validation is against 9_4_X code **and** conditions, as much of 10_6_X has been a work in progress in terms of both ingredients.
If you want to do a pre-2018UL GT in 10_6_X it may require the creation of a certain number of new tags removing updates done within 10_6_X (and validated with the regular release validation procedure). 

> To construct a consistent "pre-UL 2018" GT for the comparisons with a 10_6_X baseline, ideally we would use tags that had the same 2018 history has those prior to the 2017 UL preparation. Do such tags exist? If not, what is the _minimal_ consistent 10_6_X GT? Would that be `102X_dataRun2_v18` + `SiPixel2DTemplateDBObject_38T_v3_offline` (label=`numerator`)? Or is the pixel quality tag `SiPixelQuality_v07_offline` necessary for a consistent GT as well?
> 
> I've updated the PR to include the also the following two tags:
> 
> `SiPixel2DTemplateDBObject_38T_v3_offline` (label=`numerator`)
> `SiPixelQuality_v07_offline`
> 
> for `auto:run1_data` and `auto:run2_data`. The diffs relative to the candidates previously used in this PR are:

This is fine. Thanks.

> 
> For the MC GTs, I've added:
> 
> `SiPixelStatusScenarios_UltraLegacy2018_v0_mc`
> `SiPixelQualityProbabilities_UltraLegacy2018_v0_mc`
> 
> to the `auto:phase1_2018_realistic` and `auto:phase1_2018_realistic_HEfail` GTs. The diffs relative to the candidates previously used in this PR are:
> 

This update is incomplete.
Please add:
`SiPixelQuality_phase1_2018_permanentlyBad` 
and
`SiPixelQuality_forDigitizer_phase1_2018_permanentlyBad` with label `forDigitizer`
as was specified in this set of slides shown at the AlCa/DB meeting of this week  [link](https://indico.cern.ch/event/835589/contributions/3513525/attachments/1887574/3112176/20190729_AlCaDB_UL18FollowUp.pdf), slide n. 2

**Comment by christopheralanwest** [comment]
Thanks for queuing the remaining pixel tags. I've updated the PR. The differences with respect to the previous candidates are:

https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/110X_upgrade2018_realistic_Candidate_2019_08_03_04_00_02/110X_upgrade2018_realistic_Candidate_2019_08_03_11_37_17
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/110X_upgrade2018_realistic_HEfail_Candidate_2019_08_03_04_03_44/110X_upgrade2018_realistic_HEfail_Candidate_2019_08_03_11_39_50

**Comment by christopheralanwest** [comment]
please test

**Comment by christopheralanwest** [comment]
+1

- Payloads have validated individually as described in the references at the opening of this PR
- Comparison tests show that only 2018 data and MC scenarios are affected, as expected.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
