### PR TITLE
sync with 80X and cleanup of obsolete T0 processing scenarios

### PR DESCRIPTION
**Pull request by slava77**
- 80X changes to DataProcessing configs are updated to what's been actively used in 80X already
- pre-era scenarios are removed: ppRun2 (use ppEra_Run2_2016), ppRun2at50ns (use ppEra_Run2_50ns), ppRun2B0T (use ppEra_Run2_trackingLowPU), cosmicsRun2 (use cosmicsEra_Run2_2016), HeavyIonsRun2 (use HeavyIonsEra_Run2_HI), hcalnzsRun2 (use hcalnzsEra_Run2_2016)
- customisations in RecoTLR corresponding to the pre-era scenarios (customise*Deprecated* methods) are removed. The customisation functions are left to be removed later.

Most of the changes here were assumed for auto-forward-port of #13945 but were locked out due to conflicts in other areas.
This PR is needed to get #14267 going. @makortel 

Configuration/DataProcessing/python/Modifiers.py and RecoVertex/BeamSpotProducer/python/Modifiers.py are not fully used at this point. More extensive use is pending Eras.py refactoring.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by rovere** [comment]
@slava77 I assume I can "port" the beamspot+PV fix for the lowPU era on top of this PR, right?

**Comment by slava77** [comment]
@rovere 
there is no strict connection to this PR in the beamspot+PV fix.
That fix needs trackingLowPU era to be present, which is available since #13988 was merged (11 days ago, but missed 801pre3)

**Comment by rovere** [comment]
@slava77 not really, since #13988 does not update Configuration/DataProcessing....

**Comment by slava77** [comment]
right, but changes in #14150 (which, I suppose are the target for the forward port)
only need the trackingLowPU era from #13988 , the tests can be done with cmsDriver.

Anyways, the port of #14150 could wait for this PR to be integrated, if it's more convenient to you.

**Comment by slava77** [comment]
uhm,
in https://cmssdt.cern.ch/jenkins/job/ib-any-integration/12789/console
``` Aborted by degano ```

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/14350	112ef0c
- jenkins tests pass (including package unit tests) and comparisons with baseline show no relevant differences

**Comment by deguio** [comment]
+1

**Pull request merged**
