### PR TITLE
Add centrality bin in 75X and Jet DQM update

### PR DESCRIPTION
**Pull request by rkunnawa**
Backporting to 75X for the HIN-Jet DQM #12194 module and the centrality bin information #12002 . When checking this, i ran the matrix after merging with the #12259 and the workflows completed without any errors. We would like this to be in the latest 75X release by the next week since we have to run several tests. thanks a lot! 

Cheers
Raghav

### CODE REVIEW

**Comment by rkunnawa** [comment]
@degano Since, we are trying to get this into our heavy ion data taking release asap I would very much appreciate your help in moving this forward.

**Comment by BetterWang** [comment]
Hi @deguio , can you trigger the test?
Thanks,

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@rkunnawa 
please make a PR for 76X and 80X

**Comment by rkunnawa** [comment]
@slava77 the PR for 76X is here #12194. I will prepare a new one for 80X later today. 
thanks!

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/12310	6c2b9b4
- reco-related changes look OK (centralityBin added to globalRecoPbPb sequence), this change was added to 76X already in #12002 (and to 80X in #12151 ). The rest, DQM and Validation changes, didn't trigger any major concern at a quick glance.
- jenkins tests pass and comparisons with baseline show expected differences only in HI workflow (140.53):
    - monitored reco products are unchanged in fwlite comparisons
    - DQM plots show differences in Centrality/EventPlane and HIJetValidation plots
here is a somewhat randomly picked plot from this category
wf140 53_akvs5pfjets_hivalidation_40gev

**Comment by deguio** [comment]
to be submitted to 80x as well

**Comment by rkunnawa** [comment]
Hi @deguio, Im testing the PR for 80X at the moment with the matrix. In the meanwhile, I can remove the commented out statements in this PR (mostly in the Validation/JetTester_HeavyIon module) and we can test this again if its necessary. just checking since the timing is quite crucial for the HI datataking. Please let me know. cheers!

**Comment by rkunnawa** [comment]
@deguio and @slava77 ive created a new PR for 80X with the same Jet DQM code (with removing some of the commented out code) #12353.

**Comment by rkunnawa** [comment]
apologies for the multiple emails, do we have a chance of this going 755? I heard that 755 is getting built as we speak for release tomorrow. thanks a lot!

**Comment by deguio** [comment]
+1
I doubt it will make it for 755, but who knows..
corresponding PR approved in 76 and 80.

**Pull request merged**
