### PR TITLE
improve protection for not defined workflows

### PR DESCRIPTION
**Pull request by kpedro88**
#### PR description:

Following up on my own suggestion in https://github.com/cms-sw/cmssw/pull/27713#discussion_r315266650

#### PR validation:

Tested runTheMatrix.py with both known and unknown WF numbers, saw expected behavior.

### CODE REVIEW

**Comment by kpedro88** [comment]
please test

**Comment by chayanit** [comment]
please test

**Comment by kpedro88** [comment]
+upgrade

**Comment by kpedro88** [comment]
@prebello, @chayanit, @pgunnell, @zhenhu please sign

**Comment by chayanit** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Pull request merged**
