### PR TITLE
re-enable HLTMon sequence everywhere

### PR DESCRIPTION
**Pull request by deguio**
I tested successfully the reduced matrix and the T0 config.
@fabozzi @rovere

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
I guess I will have to wait for the tests to start using today's IB

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1
this goes together with #11811 
@fabozzi

**Comment by davidlange6** [comment]
@deguio - seems to add a bunch of printouts - is that still expected? 
(I will retest after an IB with a bunch of others turned off so I can see them...

**Comment by davidlange6** [comment]
@cmsbuild, please test

**Comment by davidlange6** [comment]
cmsbuild, please test

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
shouldn't add printouts on top of #11811 
will see.

**Comment by davidlange6** [comment]
@deguio - I think most of this log comes from this PR (as before...)

https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-11629/9298/runTheMatrix-results/4.53_RunPhoton2012B+RunPhoton2012B+HLTD+RECODreHLT+HARVESTDreHLT/step3_RunPhoton2012B+RunPhoton2012B+HLTD+RECODreHLT+HARVESTDreHLT.log

**Comment by deguio** [comment]
@davidlange6 you are right. the FEVTDEBUGHLT is saved but the needed collections are not there.
will look into it

**Comment by deguio** [comment]
@davidlange6 @fabozzi 
the reason for the logs being full is that for the WF 4.53 and in general for all the WFs running on 2012 data, a fake HLT menu is run. only few collections are produced and not the ones needed by those modules.
the 2012 WF are now retired (apart from one running on 2012D I think) and the 134.X series, on 2015 data, runs just fine producing a clean(er) log.
I would consider using one of these new WFs in jenkins,

what do you think?
ciao and thanks,
F.

**Comment by deguio** [comment]
(closed by mistake and re-opened)

**Comment by davidlange6** [comment]
so how can we avoid making a mess of the run 1 logs? Perhaps a once per job message is tolerable (even if not desirable)

**Comment by deguio** [comment]
that can be done. on your side are you going to update the tests run by jenkins to a more recent series?
ciao,
F.

**Comment by deguio** [comment]
btw.. for the track refitter (under reco responsibility) I'm not sure that silent/reduce the loggging could be dangerous.

**Comment by davidlange6** [comment]
Hi Federico

There are already several 2015 data tests in runTheMatrix. What is left is to promote one to the short matrix. That should be easy to do (but that doesn’t change the need to support old data)

david

**Comment by deguio** [comment]
ok, maybe something for @fabozzi .
actually old data are supported, but when running with a fake HLT menu you get tons of warning/errors.
maybe I can just lower the threshold to logInfo.
F.

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
@davidlange6 
I've lowered the log threshold for the hlt monitoring module. some complaint will still come from the refitter. in that case I don't think it is a good idea to lower the logging. I believe that the situation is reasonable for the <2012 datasets with a fake HLT menu

**Comment by deguio** [comment]
please test
@mtosi

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
@deguio - maybe it's time for a run1 dam sequence to avoid having I run no functioning checks on it?

**Comment by davidlange6** [comment]
Dam is really dqm (plus autocorrection...)

**Comment by deguio** [comment]
here it's more a problem of fake HLT menu rather than a specific DQM sequence.

**Comment by diguida** [comment]
@deguio maybe you should rebase...

**Pull request closed without merging**
