### PR TITLE
Run4-hgx247 Add some new features for HGCal

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

 Add some new features for HGCal and replaces PR #30294

#### PR validation:

Tested against workflows of runTheMatrix.py

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
+1

**Comment by bsunanda** [comment]
@rekovic @kpedro88 Could you approve this PR?

**Comment by kpedro88** [comment]
+upgrade

**Comment by bsunanda** [comment]
@rekovic Please approve this PR

**Comment by bsunanda** [comment]
@silviodonato Can this PR be integrated soon? That will help to move on for the next HGCal verson

**Comment by silviodonato** [comment]
merge
@rekovic

**Pull request merged**
