### PR TITLE
Phase2-sim141 Small changes to the scripts to test all Phase2 geometry scenarios

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Small changes to the scripts to test all Phase2 geometry scenarios

#### PR validation:

Use the modified scripts to understand all Phase2 geometry scenarios

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
