### PR TITLE
Run3-gem51 Add a tool to compare DDD vs DD4HEP for CSC geometry

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Add a tool to compare DDD vs DD4HEP for CSC geometry

#### PR validation:

Use cfg's in the test/python area of Geometry/CSCGeometryBuilder

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by cvuosalo** [comment]
@bsunanda Thanks for this PR. I was just running into a related issue with the muon XML, and this PR showed me how to make a fix.

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
