### PR TITLE
Add dictionary for AbsHcalAlgoData

### LINKED ISSUE #963: Add dictionary for AbsHcalAlgoData

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

Dictionary for `AbsHcalAlgoData` is required to get the version and checksum of HFPhase1PMTParams. I also cleaned up `classes.h`. Found with https://github.com/cms-sw/cmssw/pull/45423#issuecomment-2226416814

Resolves https://github.com/cms-sw/framework-team/issues/963

#### PR validation:

Code compiles, and the to-be-added `edmDumpClassVersion` succeeds to process the `classes_def.xml` files.

### CODE REVIEW

**Comment by makortel** [comment]
@cmabuild, please test

**Comment by makortel** [comment]
type -changes-dataformats

**Comment by perrotta** [comment]
@cmsbuild please test

**Comment by makortel** [comment]
Comparison differences are related to https://github.com/cms-sw/cmssw/issues/45505

**Comment by perrotta** [comment]
@igv4321 @bsunanda @kpedro88 (adding a few names from the latest developers of this file): do you foresee any possible usage of the `namespace CondFormats_HcalObjects` which is cleaned up here? As far as I can see it can be removed, but please confirm.

**Comment by makortel** [comment]
> do you foresee any possible usage of the `namespace CondFormats_HcalObjects` which is cleaned up here

Just to note that this part in the `classes.h` was needed at the time (ROOT5 era or something), but has been unnecessary for a long time now (for the purposes of ROOT dictionary generation).

**Comment by perrotta** [comment]
> > do you foresee any possible usage of the `namespace CondFormats_HcalObjects` which is cleaned up here
> 
> Just to note that this part in the `classes.h` was needed at the time (ROOT5 era or something), but has been unnecessary for a long time now (for the purposes of ROOT dictionary generation).

Thank you @makortel, that's fine with me.
Then, does it mean that all [those namespace's](https://cmssdt.cern.ch/lxr/search?%21v=CMSSW_14_1_X_2024-08-01-2300&_filestring=classes.h&_string=namespace&_casesensitive=1) should also better get cleaned up now?

**Comment by perrotta** [comment]
+1

**Comment by makortel** [comment]
> Then, does it mean that all [those namespace's](https://cmssdt.cern.ch/lxr/search?%21v=CMSSW_14_1_X_2024-08-01-2300&_filestring=classes.h&_string=namespace&_casesensitive=1) should also better get cleaned up now?

Yes, all of those can be cleaned up (I'm somewhat surprised there are that many left)

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
