### PR TITLE
Fix printed text in Payload Inspector plots for DropBoxMetaData

### PR DESCRIPTION
**Pull request by tlampen**
#### PR description:

As a continuation to PRs #36520 and #36927, this PR corrects the text printed in case a record exists in target but not in reference. 

#### PR validation:

The correct behaviour is illustrated at the end of the attached plot, a comparison of first and last payloads of DropBoxMetadata_v5.1_express.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A
DropBoxMetadata_Compare

attn: @mmusich

### CODE REVIEW

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
type bug-fix

**Comment by mmusich** [comment]
thanks @tlampen. 
One thing I did want to do and didn't get around to clean up in my PR https://github.com/cms-sw/cmssw/pull/36934 is the `std::endl` at the end of `LogPrint` statements e.g. in :

https://github.com/cms-sw/cmssw/blob/b379b8527d8779cf48f10d4a1a333b3564a023ab/CondCore/PhysicsToolsPlugins/interface/DropBoxMetaDataPayloadInspectorHelper.h#L83-L90

as these are not needed (see [manual](https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideMessageLogger#Functions_to_issue_messages)).
Perhaps you can profit of this PR to implement it.

**Comment by tlampen** [comment]
> Perhaps you can profit of this PR to implement it

Thanks for pointing this out @mmusich . I clean the std::endl's and will also rearrange the \n's a bit.

**Comment by francescobrivio** [comment]
> Thanks for pointing this out @mmusich . I clean the std::endl's and will also rearrange the \n's a bit.

Thanks @tlampen! just for my understanding: does the output plot changes with this rearrangement?

**Comment by mmusich** [comment]
> does the output plot changes with this rearrangement?

nope. That involves only the messages printed on screen at runtime.

**Comment by francescobrivio** [comment]
@cmsbuild please test

**Comment by francescobrivio** [comment]
> > does the output plot changes with this rearrangement?
> 
> nope. That involves only the messages printed on screen at runtime.

right, sorry for the stupid question...I should've looked at the code first 😅

**Comment by tvami** [comment]
+db

**Comment by perrotta** [comment]
+1

**Pull request merged**
