### PR TITLE
Minor CLUE3D optimization

### PR DESCRIPTION
**Pull request by bfonta**
Minor optimization of CLUE3D:
- remove a redundant ```if...else``` statement (the ```else``` reflects what was previously done in the initialization)
- move the same layer check before calculating distances with ```isReachable()```; this saves a few instructions in each cluster iteration

### CODE REVIEW

**Comment by srimanob** [comment]
@cmsbuild please test

**Comment by jfernan2** [comment]
+1

**Comment by felicepantaleo** [comment]
enable profiling

**Comment by felicepantaleo** [comment]
@cmsbuild please test

**Comment by jfernan2** [comment]
+1
It would be nice to have checked timing in this PR but igprof test is broken: https://github.com/cms-sw/cmssw/issues/43166

**Comment by smuzaffar** [comment]
Milestone for this pull request has been moved to CMSSW_14_0_X.Please open a backport if it should also go in to CMSSW_13_3_X.

**Comment by srimanob** [comment]
@cmsbuild please test

Re-trigger the test after 3 weeks.

**Comment by srimanob** [comment]
+Upgrade

**Comment by jfernan2** [comment]
+1

**Comment by felicepantaleo** [comment]
+1

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
