### PR TITLE
added esConsumes to modules in RecoMuon/MuonIdentification

### PR DESCRIPTION
**Pull request by JamminJones**
#### PR description:

added esConsumes to 5 modules
#### PR validation:

the code compiles

### CODE REVIEW

**Comment by Dr15Jones** [comment]
This change was made under my supervision.

**Comment by JamminJones** [comment]
the following modules were skipped due to the complexity of the changes required: MuonIDProducer, MuonShowerInformationProducer, and MuonTimingProducer.

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
please test

**Comment by perrotta** [comment]
+1
- Technical 
- Jenkins tests pass

**Comment by silviodonato** [comment]
+1

**Pull request merged**
