### PR TITLE
adding the info for the y-coordinate and the precise timing from iRPCs

### PR DESCRIPTION
**Pull request by bapavlov**
Adding up Y coordinate and precise timing for iRPCs in MuonRPCHitMatch

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by bapavlov** [comment]
@slava77 
I closed the previous PR #18007. It was done on a wrong base release, but #18009 should be OK

**Comment by perrotta** [comment]
@bapavlov : this PR just adds two floats data members to the MuonRPCHitMatch class. They are not yet filled or accessed anywhere in CMSSW, and therefore there are no changes in the test outputs.

You can profit of this PR to include the comments in doxygen compliant style, which is fulfilled if you put !< in front of them, for example:
          float x;                        //!< X position of the matched segment
          unsigned int mask;    //!< arbitration mask
etc.
Please do so for all data members in this class: this PR can be signed off right after

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
+1
This PR just adds two float data members to the MuonRPCHitMatch class. They are not yet filled or accessed anywhere in CMSSW, and therefore there are no changes in the test outputs.

**Comment by davidlange6** [comment]
Hi @bapavlov @perrotta - without the variables being filled its not possible to measure the impact of this change on the muon data format. Have you tested also the changes including the code needed to fill these variables? (

**Comment by davidlange6** [comment]
-1
waiting for answers to comments

**Comment by bapavlov** [comment]
The Y coordinate and precise time are implemented  in the RPC local reconstruction:

The Y coordinate is implemented here:
https://github.com/cms-sw/cmssw/blob/master/RecoLocalMuon/RPCRecHit/src/RPCRecHitStandardAlgo.cc#L29

While the precise timing is implemented here:
https://github.com/cms-sw/cmssw/blob/master/RecoLocalMuon/RPCRecHit/src/RPCRecHitStandardAlgo.cc#L58

We have tested the residuals (Sim hit vs Rec hit) and they are within the expectations:
https://indico.cern.ch/event/614702/contributions/2519763/attachments/1432969/2202032/Requirements_MuonUpgrade_23032017_v7.pdf

Y-coordinate and precise timing should be "copied" to MuonRPCHitMatch here:
https://github.com/cms-sw/cmssw/blob/master/RecoMuon/MuonIdentification/plugins/MuonIdProducer.cc#L950
and then used here:
https://github.com/cms-sw/cmssw/blob/master/DataFormats/MuonReco/src/MuonSelectors.cc#L550

We are working on the implementation.

**Comment by perrotta** [comment]
@davidlange6 : was the answer from @bapavlov enough for you, or do you need something more in order to remove your "-1" ?

**Comment by slava77** [comment]
@davidlange6 
there was a question to you about two weeks ago https://github.com/cms-sw/cmssw/pull/18009#issuecomment-292956909 
Please respond when you have a chance.
Thank you.

**Comment by davidlange6** [comment]
whoops - missed that. I'd prefer to consider for integration with some of the implementation that makes use of the new variables..

**Comment by jhgoh** [comment]
@davidlange6 would it be OK to be merged if we add implementations to fill the information? we can ask one more PR or append commits to this one. Which one do you prefer? (if it is acceptable)

**Comment by perrotta** [comment]
@jhgoh please add it here

**Comment by calabria** [comment]
@jhgoh please proceed with the development but we can not further delay 910_pre3,so if this takes too long we have to postpone this item

**Comment by slava77** [comment]
On 4/28/17 6:11 AM, Cesare Calabria wrote:
> @jhgoh <https://github.com/jhgoh> please proceed with the development
> but we can not further delay 910_pre3,so if this takes too long we have
> to postpone this item
> 

pre3 is built already
if this change is required, it should be communicated up to abort and delay.

**Comment by davidlange6** [comment]
yes, please add the developments here if possible. Thanks!

**Comment by perrotta** [comment]
-1
This is stuck since a while, already.
If a new PR will be prepared, which actually fills the relevant infos added to the class, at this point it could better restart from scratch

**Comment by davidlange6** [comment]
or we can just reopen the PR

**Pull request closed without merging**
