### PR TITLE
Run3-alca188 Add one AlCa to HLTPhysics stream

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Add one AlCa (HcalCalIterativePhyiSym) to HLTPhysics stream

#### PR validation:

Use standard Workflows

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by malbouis** [comment]
please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by yuanchao** [comment]
+1

* Add one HcalCalIterativePhyiSym to HLTPhysics stream
* WF tests passed

**Comment by qliphy** [comment]
+1

**Pull request merged**
