### PR TITLE
Added a per lumisection LHC and CMS status DQM plot

### PR DESCRIPTION
**Pull request by andrius-k**
Added a per lumisection LHC and CMS plot showing DCS information. Plot is added to the offline sequence. We already have such plot but this one shows intermediate values (TProfile colz) when a subsystem was on/off not for the entire duration of the lumisection.

### CODE REVIEW

**Comment by andrius-k** [comment]
please test

**Comment by fabiocos** [comment]
@andrius-k do we really need a brand new package for one class only? Logically I see its motivation, it is unclear where else this class might go within DQMOffline. But do you foresee to expand further this package, or this is its final configuration? You say that you already have such plots, where?

**Comment by andrius-k** [comment]
@fabiocos Yes, I think you are right, the new package is not necessary as there are no concrete means to expand it. [This is an example](https://cmsweb.cern.ch/dqm/online/start?runnr=327802;dataset=/Global/Online/ALL;sampletype=online_data;filter=all;referencepos=overlay;referenceshow=customise;referencenorm=True;referenceobj1=refobj;referenceobj2=none;referenceobj3=none;referenceobj4=none;search=;striptype=object;stripruns=;stripaxis=run;stripomit=none;workspace=Info;size=M;root=Quick%20collection;focus=Info/EventInfo/reportSummaryMap;zoom=yes;) of a plot that already exists but doesn't show intermediate results within a lumisection.
I will update this PR by adding my plot to an existing package.

**Comment by fabiocos** [comment]
@andrius-k any news about this?

**Comment by fabiocos** [comment]
@andrius-k any news about this?

**Comment by schneiml** [comment]
@andrius-k is on vacation atm, this will probably be picked up at some point but is not very urgent for now.

**Comment by andrius-k** [comment]
@fabiocos Yes, this is not on the top of our priority list at the moment. Closing this for now but will get back to this in the future.

**Pull request closed without merging**
