### PR TITLE
Adding tracking efficiencies w.r.t. offline to HLT monitoring client [124X]

### PR DESCRIPTION
**Pull request by kjpena**
#### PR description:

Backport of [#38959](https://github.com/cms-sw/cmssw/pull/38959)

> This PR adds the sequence producing HLT tracking efficiencies and fake rates w.r.t. offline tracks to the HLT monitoring client

#### PR validation:

> Efficiency and fake rate plots are now produced when running the harvesting step with @HLTMon

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport of [#38959](https://github.com/cms-sw/cmssw/pull/38959) for data taking

### CODE REVIEW

**Comment by kjpena** [comment]
backport [#38959](https://github.com/cms-sw/cmssw/pull/38959)

**Comment by mmusich** [comment]
backport of #38959

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
urgent 
   * needed for data-taking

**Comment by emanueleusai** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
