### PR TITLE
Update Hydjet_Quenched_MinBias_XeXe_5442GeV_cfi.py (Cymbal5F)

### PR DESCRIPTION
**Pull request by wouf**
New 5 TeV tune update (Cymbal5F)

### CODE REVIEW

**Comment by efeyazgan** [comment]
please test

**Comment by perrozzi** [comment]
+1

**Comment by wouf** [comment]
We need it in CMSSW_9_3_X as well, could it be reviewed at the same time? (I mean backport)

**Comment by perrozzi** [comment]
yes please prepare the PR

**Comment by wouf** [comment]
Is it (backport) possible to do only after this one would be merged?

**Comment by perrozzi** [comment]
no, they are completely independent.
the merging of the backport is instead done after the integration into master

**Comment by fabiocos** [comment]
@perrozzi @efeyazgan was this cfg used in production already, or is it just for test?

**Comment by wouf** [comment]
Yes, it was. For 9_3_X.
9 апр. 2018 г. 10:25 ПП | От: Fabio Cossutti <notifications@github.com> | Сообщение:

@perrozzi<https://github.com/perrozzi> @efeyazgan<https://github.com/efeyazgan> was this cfg used in production already, or is it just for test?

**Comment by fabiocos** [comment]
@wouf @perrozzi let me explain better myself: if the original version that you modify here was already used, I think it would be better to have a new version. But may be it was from the external repository of configurations and not from the release, that is most for validation?

**Comment by wouf** [comment]
The original version is not usable. We have to replace it with a new one, for validation as well.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
