### PR TITLE
Migration to multithread safe producers

### PR DESCRIPTION
**Pull request by matteosan1**
Migration of RecoEgamma/EgammaHLTProducers for multithreading.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by slava77** [comment]
i'm checking it

**Comment by slava77** [comment]
unrelated to this PR, still.
To get a better coverage of HLT tests, I ran addOnTests in CMSSW_7_4_X_2015-01-18-0200
There is an error in  addOnTests/hlt_mc_HIon/cmsDriver.py_TTbar_Tauola_13TeV_cfi_*

```
   [1] Running path 'generation_step'
   [2] Calling event method for module GenParticleProducer/'hiGenParticles'
Exception Message:
Principal::getByToken: Found zero products matching all criteria
Looking for type: CrossingFrame<edm::HepMCProduct>
Looking for module label: mix
Looking for productInstanceName: generator

```

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/7260	e69d727
code looks as expected
jenkins tests ok (runs and no diffs)

**Pull request merged**
