### PR TITLE
Run2-TB36 Create the two remaining setups for HGCal October TB runs

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Now complete declaration of all 3 setups of the HGCal October TB runs

#### PR validation:

Ran with specific tests for the TB simulation

#### if this PR is a backport please specify the original PR:

No back porting is needed

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@civanch @cvuosalo @kpedro88 Please approve this

**Comment by kpedro88** [comment]
+upgrade

**Comment by cvuosalo** [comment]
+1

**Comment by bsunanda** [comment]
@civanch Please approve this PR

**Comment by civanch** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
