### PR TITLE
Use likelihood fit instead of chi-square fit in PVValidation

### PR DESCRIPTION
**Pull request by smuzaffar**
This should fix the unit test failure for slc7 IB (see https://github.com/cms-sw/cmssw/pull/43106 and https://github.com/cms-sw/cmssw/issues/43577 )

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test for slc7_amd64_gcc12

**Comment by smuzaffar** [comment]
please test

**Comment by perrotta** [comment]
@mmusich you are the author of this code: it seems perfectly fine to me using likelihood instead of chisquare (likelihood is also already used in the second fit at [L245](https://github.com/cms-sw/cmssw/blob/7cd352e2ba552a24c6de49f5da97d5b0e31afd79/Alignment/OfflineValidation/src/PVValidationHelpers.cc#L245)), but if you have any issue please speak up. Otherwise this PR can be signed.

**Comment by mmusich** [comment]
@perrotta no objections.

**Comment by perrotta** [comment]
+alca

**Comment by rappoccio** [comment]
+1

**Pull request merged**
