### PR TITLE
Avoid nan from dzError() in track PV assignment (solves #21780)

### PR DESCRIPTION
**Pull request by arizzi**
This PR protects PV assignment from nan replacing the nan with a fixed value (1 meter) for the dZerror

Should solve issue
#21780

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by slava77** [comment]
-1

superseded by #21935

**Comment by slava77** [comment]
> @slava77 @perrotta @arizzi I understand that this PR could be just closed, please confirm

yes, it can be closed

**Comment by fabiocos** [comment]
@slava77 thanks

**Pull request closed without merging**
