### PR TITLE
Phase-hgx315 Add a new scenario 2026D92 using V17 version of HGCal geometry

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Add a new scenario 2026D92 using V17 version of HGCal geometry

#### PR validation:

Use  runTheMatrix test workflow 41034.0

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by srimanob** [comment]
@cmsbuild please test workflow 41034.0

This is to test D92 workflow on top of short matrix (which no change is expected from the short matrix workflow).

**Comment by srimanob** [comment]
+Upgrade

This PR adds new geometry, D92. It is based on D88 with new HGCal C18 (V17).

**Comment by cvuosalo** [comment]
+1

**Comment by bsunanda** [comment]
@kskovpen @bbilin Please approve this PR

**Comment by kskovpen** [comment]
+pdmv

**Comment by qliphy** [comment]
+1

**Pull request merged**
