### PR TITLE
add unit test to check availability of EDM files used in HLT tests

### LINKED ISSUE #40013: HLT-Validation tests failing in IBs of `CMSSW <= 12_1_X`
The HLT-Validation tests are failing in IBs of `CMSSW_12_1_X` and lower release cycles, e.g.
https://cmssdt.cern.ch/SDT/html/cmssdt-ib/#/ib/CMSSW_12_1_X

The main [*] reason of these failures is access to EDM files used by these tests (these files were removed from the CERN Tier-2, some days or weeks ago) [**].

TSG has copies of these files in its EOS area, so the fix is simple: we can replace the path to these files.

Questions to @cms-sw/orp-l2.

 - Do we want to fix this? Are PRs still accepted in release cycles as low as `5_3_X`?

 - If yes, should we also make PRs to release cycles that do not appear on the IB dashboard (e.g. `12_2_X`)?

[*] In `10_6_X` (and likely some other cycle), these tests will continue to fail (even after fixing the file-access issue) due to other issues.

[**] It might be useful to know from experts if there are ways to cache these files similarly to what is done for the EDM files used in RelVal wfs and `addOnTests`.

### PR DESCRIPTION
**Pull request by missirol**
#### PR description:

The PRs to fix #40013 updated the HLT tests to use the standard LFNs of their EDM input files. This failed to cover one use case of TSG: running locally an extended version of the HLT tests which requires access to EDM files not used in IBs of any release cycles. Since these files are not used in IBs, they might eventually be removed from the IB-EOS cache, causing said local tests to fail if the EDM files are not available at any other T2/T3.

This PR adds a unit test which accesses each of the EDM files needed for (the extended version of the) HLT tests. In practise, this serves as a trick to ensure that the cmsbot keeps these files cached in the IB-EOS area. The list of relevant EDM files is maintained in a text file, which can be updated by locally executing a script (the unit test does not modify the text file with the list of EDM files, it only uses it). A readme with further details is added under `test/`.

#### PR validation:

The new unit test passes.

#### If this PR is a backport, please specify the original PR and why you need to backport that PR. If this PR will be backported, please specify to which release cycle the backport is meant for:

N/A

### CODE REVIEW

**Comment by missirol** [comment]
please test

**Comment by missirol** [comment]
please test

**Comment by missirol** [comment]
please test

**Comment by missirol** [comment]
+hlt

New unit test passes, its implementation might be improved in the future.

**Comment by missirol** [comment]
please test

> its implementation might be improved in the future.

The latest push includes some improvements to the `update_filelist` script (mainly, formatting changes). This latest update won't have any impact on PR tests (which will be repeated nonetheless). I don't plan to make further changes to this PR.

**Comment by missirol** [comment]
+hlt

The new unit test passes. The RelVals-INPUT error can't be related to this PR (by construction).

PS. Only a few RelVal-input wfs were missing when the 4h-timeout hit. I wonder if increasing this timeout limit a bit could decrease significantly the rate of these spurious errors.

**Comment by perrotta** [comment]
+1

**Comment by perrotta** [comment]
merge

**Pull request merged**
