### PR TITLE
Fixes related to beamspot DIP server for pilot run [12.0.X]

### PR DESCRIPTION
**Pull request by sikler**
#### PR description:

- fixing warning related to missing log4cplus.properties file
- solved by performing a local copy to the working directory

### CODE REVIEW

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by sikler** [comment]
@pmandrik requested line added in the client config. On the "Connection timed out" problem I have contacted dip-support@cern.ch.

**Comment by pmandrik** [comment]
(just would like to put here the link to the JIRA ticket not to forget https://its.cern.ch/jira/browse/CMSONS-13415)

**Comment by francescobrivio** [comment]
From the JIRA it seems that the DIP servers are now accessible.
Should we schedule another try with the DIP client?
@pmandrik @ahmad3213 maybe a playback?

**Comment by sikler** [comment]
I have just pushed in a small update fixing DIP name servers.

**Comment by pmandrik** [comment]
Hello, @sikler , with this PR we still have following error at the playback:

20-Oct-2021 14:13:15 CEST  DQMStreamerReader initialised.
10/20/21 12:13:19 [140650386695488] ERROR system.dimerror %% - DIM message: Server Connecting to DIM_DNS@dipns1: Connection timed out
10/20/21 12:13:20 [140650386695488] ERROR system.dimerror %% - DIM message: Server Connecting to DIM_DNS@dipns2: Connection timed out
Begin processing the 1st record. Run 345922, Event 1, LumiSection 1 on stream 0 at 20-Oct-2021 14:13:20.432 CEST

I also tried with dip->setDNSNode("dipns1.cern.ch,dipns2.cern.ch"); but the result us similare:

20-Oct-2021 14:37:24 CEST  DQMStreamerReader initialised.
10/20/21 12:37:27 [140361061516608] ERROR system.dimerror %% - DIM message: Server Connecting to DIM_DNS@dipns1.cern.ch: Connection timed out
10/20/21 12:37:28 [140361061516608] ERROR system.dimerror %% - DIM message: Server Connecting to DIM_DNS@dipns2.cern.ch: Connection timed out
Begin processing the 1st record. Run 345922, Event 1, LumiSection 1 on stream 0 at 20-Oct-2021 14:37:28.391 CEST

**Comment by jfernan2** [comment]
+1
Tested in Online DQM at P5

**Comment by sikler** [comment]
> @sikler could we have a forwardport to master to keep releases in sync? Thanks!
Yes, very soon. I am still waiting for the solution of the NXCALS/TIMBER issue.

**Comment by sikler** [comment]
@francescobrivio If you could help out with the forward port to master, that would be great!

**Comment by francescobrivio** [comment]
> @francescobrivio If you could help out with the forward port to master, that would be great!

ok sure I will open the forward port in few minutes!

**Comment by sikler** [comment]
> Hello, @francescobrivio , please find following logs: [DIP_content_parser_playbackPARSER_run502088PARSER_job2.log](https://github.com/cms-sw/cmssw/files/7388468/DIP_content_parser_playbackPARSER_run502088PARSER_job2.log)

Hi, how can I force the client to be (much) more verbose? There are couple of LogInfo messages in the code. Need to include MessageLogger?

**Pull request merged**
