### PR TITLE
Backport of the PR #24613 and #24902: RPC digi merger and test new readouts

### PR DESCRIPTION
**Pull request by slezki**
This is essentially two requests for two backports of PRs:
Firstly, need to backport the PR: #24613
Secondly, need to backport the PR: #24902

the second PR (#24902) is to test new readouts by using new RPC digi merger in PR: #24613.

### CODE REVIEW

**Comment by andrius-k** [comment]
please test

**Comment by andrius-k** [comment]
Hi, @slezki could you please add your Github username to the [DQM contacts list](https://twiki.cern.ch/twiki/bin/viewauth/CMS/DQMContacts)? You can do so by clicking manage button above your subgroup and by entering `git: <your username>` in the comments field.

**Comment by thomreis** [comment]
please test

**Comment by andrius-k** [comment]
please test

**Comment by andrius-k** [comment]
please test

**Comment by perrotta** [comment]
backport of #24902
(Well, also of #24613... But #24613 had been merged already, and with the above command the github flag will warn us when #24902 will also get merged)

**Comment by andrius-k** [comment]
+1

**Comment by perrotta** [comment]
+1
- DQM updates and fixes seem to have settled down, and #24902 is now fully signed
- The reco part of this PR is a faithful reproduction of the backported #24613   
  -  Producer which merges the unpacked RPC digis from TwinMux, OMTF and CPPF as needed for DQM
  -  New products are not requested in outputs, and therefore the corresponding producers are not run
  -  Default expected to be switched after 2018 data taking is over, and the legacy system decommissioned: the muonRPCDigis can then be replaced with an appropriate era modifier for Run3
- Jenkins tests pass

**Comment by rekovic** [comment]
+1

**Comment by fabiocos** [comment]
+operations

the StandardSequences are updated according to the master version

**Comment by fabiocos** [comment]
+1

backport requested by RECO for tests during the final data taking period

**Pull request merged**
