### PR TITLE
Scouting NANO in autonano

### PR DESCRIPTION
**Pull request by vlimant**
#### PR description:

The original implementation used a customise : this PR makes the scouting nano use the `NANO:@Scout` syntax.
The two files solution originally used is also removed (#43847)

#### PR validation:

nano matrix ran

tagging @alintulu

### CODE REVIEW

**Comment by vlimant** [comment]
enable nano

**Comment by vlimant** [comment]
please test

**Comment by vlimant** [comment]
this error cannot be related to the changes in the PR

**Comment by vlimant** [comment]
please test

**Comment by vlimant** [comment]
change in 2500.4 are expected as I changed the input dataset

**Comment by vlimant** [comment]
+1

**Comment by vlimant** [comment]
@alintulu  could you please have a 14.0 backport PR started ?

**Comment by vlimant** [comment]
@cms-sw/pdmv-l2 @cms-sw/operations-l2 @cms-sw/upgrade-l2 : can you please sign quickly this trivial PR so that we can get the backport going.

**Comment by subirsarkar** [comment]
+Upgrade

**Comment by AdrianoDee** [comment]
+pdmv

**Comment by vlimant** [comment]
who's signing for @cms-sw/operations-l2 ? can this be bypassed ? or can I be given the signature of that category please

**Comment by antoniovilela** [comment]
please test

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
