### PR TITLE
Cms l1t last minute 740

### PR DESCRIPTION
**Pull request by mulhearn**
Last minute updates to L1T algorithms needed for bitwise agreement in emulation and hardware.
This PR includes data files: the PRs to put these data files in the data area have already been made, but they are included now for the Jenkin's test.

### CODE REVIEW

**Comment by mulhearn** [comment]
The ALCA/DB changes are only to the non-persistent format of the data class (an enum that deals with interpretation of the payload).

**Comment by davidlange6** [comment]
@cmsbuild, please test

**Comment by davidlange6** [comment]
@nclopezo - seems that these tests are stuck - could you restart them?

**Comment by davidlange6** [comment]
@nclopezo, @degano  - could you add the 4 big txt files to the already existing data area for L1Trigger-L1TCalorimeter? It looks like they are all new and there is a PR for it...

https://github.com/cms-data/L1Trigger-L1TCalorimeter/pull/2

**Comment by mulhearn** [comment]
Now that the tests passed I can update the PR with the data files removed...

**Comment by mulhearn** [comment]
The PR was updated to remove the data files (the corresponding PR already exists in cms-data).  Note this change will cause additional tests to fail now until the next IB that includes these data files.

**Comment by mulhearn** [comment]
+1

**Comment by mulhearn** [comment]
Note that these failures are due to removing the data files.  The test prior to removing these files passed.  We are just waiting on this PR cms-data/L1Trigger-L1TCalorimeter#2

**Comment by nclopezo** [comment]
I merged the pull request and created this [tag](https://github.com/cms-data/L1Trigger-L1TCalorimeter/tree/V01-00-03), I updated the externals in this PR: https://github.com/cms-sw/cmsdist/pull/1468 The files should be available in the next 1100 IB

**Comment by davidlange6** [comment]
@cmsbuild, please test

**Comment by mulhearn** [comment]
Thank you!

**Pull request merged**
