### PR TITLE
bsunanda:Phase2-hgx64 Update in view of earlier incompatible changes

### PR DESCRIPTION
**Pull request by bsunanda**
Viewing individual wafer requires to update xml files in test area and the corresponding cfi file. Also hgcalwafer.xml is simplified: same solid can be placed in multiple logical volumes.

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by ianna** [comment]
+1

**Comment by bsunanda** [comment]
@dmitrijus Please review and approve

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
