### PR TITLE
Remove HLTriggerOffline/Egamma/test/testPatRecoElectrons.py

### PR DESCRIPTION
**Pull request by silviodonato**
In view of the cleaning of obsolete Analysis modules - in particular `ElectroWeakAnalysis/WENu` - I'm trying to remove the dependencies from these packages.
`HLTriggerOffline/Egamma/test/testPatRecoElectrons.py` contains `process.load("ElectroWeakAnalysis.WENu.simpleEleIdSequence_cff")`.
We might try to copy `simpleEleIdSequence_cff` somewhere, but I see that `testPatRecoElectrons.py` is currently broken, so I think we can simply remove this test file.

This PR is related to the cleaning of the Analysis packages (#32917)

### CODE REVIEW

**Comment by silviodonato** [comment]
please test

**Comment by silviodonato** [comment]
@cms-sw/hlt-l2 please add in cc the EGM experts.
Please let me know if we should keep this file.
cc @Sam-Harper

**Comment by silviodonato** [comment]
cc @jainshilpi

**Comment by jfernan2** [comment]
> @cms-sw/hlt-l2 @cms-sw/dqm-l2 please add in cc the EGM experts.
> Please let me know if we should keep this file.
> cc @Sam-Harper

cc  @nancymarinelli

**Comment by Sam-Harper** [comment]
looks to me that it can be removed

**Comment by silviodonato** [comment]
The error is not related to this PR
```
----- Begin Fatal Exception 15-Feb-2021 13:15:41 CET-----------------------
An exception of category 'FileOpenError' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing input source of type PoolSource
   [2] Calling RootInputFileSequence::initTheFile()
   [3] Calling StorageFactory::open()
   [4] Calling XrdFile::open()
Exception Message:
Failed to open the file 'root://cms-xrd-global.cern.ch//store/data/Run2012D/SingleMu/RAW-RECO/ZMu-15Apr2014-v1/00000/007A3BD1-02CD-E311-853B-002590D0AFC8.root'
   Additional Info:
      [a] Calling RootInputFileSequence::initTheFile(): fail to open the file with name root://eoscms.cern.ch//eos/cms/store/user/cmsbuild/store/data/Run2012D/SingleMu/RAW-RECO/ZMu-15Apr2014-v1/00000/007A3BD1-02CD-E311-853B-002590D0AFC8.root
      [b] Input file root://cms-xrd-global.cern.ch//store/data/Run2012D/SingleMu/RAW-RECO/ZMu-15Apr2014-v1/00000/007A3BD1-02CD-E311-853B-002590D0AFC8.root could not be opened.
      [c] XrdCl::File::Open(name='root://cms-xrd-global.cern.ch//store/data/Run2012D/SingleMu/RAW-RECO/ZMu-15Apr2014-v1/00000/007A3BD1-02CD-E311-853B-002590D0AFC8.root', flags=0x10, permissions=0660) => error '[ERROR] Server responded with an error: [3011] No servers are available to read the file.�
' (errno=3011, code=400). No additional data servers were found.
      [d] Last URL tried: root://cms-xrd-global.cern.ch:1094//store/data/Run2012D/SingleMu/RAW-RECO/ZMu-15Apr2014-v1/00000/007A3BD1-02CD-E311-853B-002590D0AFC8.root?tried=&xrdcl.requuid=6bf4650c-fe39-4d9b-b4d0-51868268f097
      [e] Problematic data server: cms-xrd-global.cern.ch:1094
      [f] Disabled source: cms-xrd-global.cern.ch:1094
----- End Fatal Exception -------------------------------------------------
```

**Comment by jfernan2** [comment]
+1

**Comment by silviodonato** [comment]
merge
the error is not related to this PR

**Pull request merged**
