### PR TITLE
[124X] Rename PPS Diamond Sampic PCL path and task

### PR DESCRIPTION
**Pull request by malbouis**
#### PR description:

Backport of PR #38673 

This is PR is a suggested fix for the crash observed in [this Tier0 replay](https://github.com/dmwm/T0/pull/4686#issuecomment-1176745201) when introducing the PPS Diamond Sampic PCL workflow.

It does a renaming of the path and task related to the `PromptCalibProdPPSDiamondSampic` workflow.

#### PR validation:

The crash was reproduced with the following steps:

`python3 Configuration/DataProcessing/test/RunRepack.py --lfn file:/eos/cms/store/t0streamer/Data/ALCAPPS/000/352/929/run352929_ls0006_streamALCAPPS_StorageManager.dat`

`python3 Configuration/DataProcessing/test/RunExpressProcessing.py --scenario AlCaPPS_Run3 --global-tag 123X_dataRun3_Express_v10 --lfn file:write_PrimDS1_RAW.root --alcareco PPSCalMaxTracks`

`python3 Configuration/DataProcessing/test/RunAlcaSkimming.py --scenario AlCaPPS_Run3 --global-tag 123X_dataRun3_Prompt_v12 --lfn=file:output.root --skims PromptCalibProdPPSDiamondSampic `

After the renaming, the last step (`RunAlcaSkimming.py `) was run again, successfully.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

backport of PR #38673 to include PPS Diamond Sampic PCL workflow in upcoming 124X data taking release.

### CODE REVIEW

**Comment by malbouis** [comment]
please test

**Comment by malbouis** [comment]
type ctpps

**Comment by malbouis** [comment]
type bug-fix

**Comment by malbouis** [comment]
backport of #38673

**Comment by tvami** [comment]
+alca

**Comment by tvami** [comment]
urgent

**Comment by qliphy** [comment]
+1

**Pull request merged**
