### PR TITLE
bsunanda:Run2-hcx48 Expand Hcal DetId replacing bsunanda:Run2-hcx29 (11427)

### PR DESCRIPTION
**Pull request by bsunanda**
Added special protection in HcalTopology to overcome situation in PFlow

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@davidlange6 I have closed PR 11427 in view of this (it is relevant for 7_6_X). The corresponding PR for 8_0_X (PR 11942) needs to be closed as well.
@ianna @civanch Please take this PR quickly so that we can have the expanded HcalDetId
________________________________

**Comment by ianna** [comment]
@bsunanda - have you look at comparison results? For example:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_8_0_X_2015-11-12-1100+12406/11312/25202.0_TTbar_13+TTbar_13+DIGIUP15_PU25+RECOUP15_PU25+HARVESTUP15_PU25/GlobalRecHitsV__HCals_hHcalRes_HF.png

**Comment by bsunanda** [comment]
@kpedro88 Can you see if there is any further issue with Pflow

**Comment by kpedro88** [comment]
@bsunanda - The comparison to which @ianna pointed seems to indicate some change in the HF SimHits and/or RecHits. That histogram is created by this analyzer: https://github.com/cms-sw/cmssw/blob/CMSSW_8_0_X/Validation/GlobalRecHits/src/GlobalRecHitsAnalyzer.cc

The ParticleFlow section of the comparison looks okay, but I think this difference in the HF hits propagates into other comparisons (jets, MET, btag, etc.).

I'll look into it and see if I can find anything over the next few days. Can you also look from your end?

**Comment by bsunanda** [comment]
@kpedro88 I think difference in simulation results could be random # issue. I looked at some of the codes which use rawId and I could not find anything odd. I shall keep looking
________________________________

**Comment by civanch** [comment]
@bsunanda , observed differences are similar to what we have in 11427. For example, in wfs 140.53 and 1003.0 - these two usually agree well if physics is not changed. May be they involve HF more than others?

**Comment by kpedro88** [comment]
@civanch - in #11427, it was pointed out (I think by @slava77) that the discrepancy began in the HCAL PF clusters. This PR includes a fix for that problem. I think this must be something else that we didn't see before...

@bsunanda, @ianna - I figured out the cause of the specific problem that @ianna pointed out with the HF SimHit vs RecHit comparison. It looks like the SimHit DetIds have the new format, while the RecHit DetIds have the old format, so the rawId comparison in the validation code fails. @bsunanda, can you check in the simulation code to make sure this is handled correctly for HF?

I'm not sure if fixing this will also fix the other problems we see at higher-level reco, but let's give it a shot...

**Comment by kpedro88** [comment]
@bsunanda - Update: it looks like this difference in formats in SimHits vs RecHits happens for all subdetectors, but the discrepancy in the validation plot is only visible for HF. I think this is because the HF SimHits "energy" value is actually a number of PEs, so subtracting it from the RecHit energy is a more obvious change.

**Comment by kpedro88** [comment]
@bsunanda - I think I found the problem for the RECO changes. It's unrelated to the SimHit DetId thing (unsurprisingly).

http://cmslxr.fnal.gov/source/RecoParticleFlow/PFClusterProducer/interface/PFHFRecHitCreator.h#0151

Here, the PFHFRecHitCreator is trying to match up the short and long fibers, and failing because of the default value in the HcalDetId constructor: `bool oldFormat = false`. At the least, we should edit this code to include the format when constructing a temporary HcalDetId. I worry that this same thing might happen elsewhere in CMSSW, but I'm not sure how to find those instances...

**Comment by slava77** [comment]
@kpedro88 
It looks like all HCalDetId use cases need to be updated with oldFormat() in the last argument.
Can the interface be broken instead (no default value in the format argument)?
It's a more straightforward way to find out problematic places at compile time.

**Comment by slava77** [comment]
... maybe all direct use of HcalDetId constructor with non-trivial arguments should be fully deferred to HcalTopology so that the format doesn't have to be encoded in the detid itself.

**Comment by slava77** [comment]
assign reconstruction

**Comment by slava77** [comment]
@smuzaffar is the "assign category" feature working or am I not allowed by some logic?

**Comment by davidlt** [comment]
@slava77 you are not L2 for these packages, only they can assign additional categories.

**Comment by slava77** [comment]
hold
@davidlt thanks for the explanation

**Comment by slava77** [comment]
well, "hold" didn't work either
@davidlt @degano @smuzaffar  is the bot asleep or something?

**Comment by smuzaffar** [comment]
For now only L1 and L2's of the packages effected by the this PR can issue assign and hold.

**Comment by slava77** [comment]
On 11/15/15 2:28 PM, Malik Shahzad Muzaffar wrote:
> For now only L1 and L2's of the packages effected by the this PR can
> issue assign and hold.

Uhm, OK.
I expected the hold to be covering any package.

A hold is somewhat redundant if it can only be applied on top of the
signature for a default category.

**Comment by smuzaffar** [comment]
you are right about the hold, I will change it back to non-category based and any L2 should be able to request for it

**Comment by ianna** [comment]
hold

**Comment by smuzaffar** [comment]
@slava77, I have restore the `hold` state functionality. Now L1, any L2 and release manager can ask to put a PR on hold. Each person who has requested `hold` has to `unhold`. L1 can `unhold` for all.

**Comment by bsunanda** [comment]
@kpedro88 I wonder again why this is needed unless there is explicit usage of rawId which needs to be protected
________________________________

**Comment by kpedro88** [comment]
@bsunanda - Yes, there is more usage of the rawId in PFHFRecHitCreator, e.g. here:
http://cmslxr.fnal.gov/source/RecoParticleFlow/PFClusterProducer/interface/PFHFRecHitCreator.h#0157

It's the same type of search that is used in the PF navigation.

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by slava77** [comment]
@smuzaffar 
is the "hold" getting reset after the PR is updated?
Maybe it shouldn't.

**Comment by smuzaffar** [comment]
yes hold is reset after PR update. I thought to keep it but then kept the old implementation.
I agree that hold should not be reset after the update of PR. I will update the cms-bot

**Comment by bsunanda** [comment]
@slava77  In principle HcalDetId constructor could be called with any format type as long as one does not use rawId in the code for == or < operators. This is somehow not used in many parts and that was causing the problem.
________________________________

**Comment by slava77** [comment]
@bsunanda,  I suppose you will start the jenkins tests when you are done with changes in this PR.

**Comment by slava77** [comment]
unhold
now that there is a reco signature required

**Comment by ianna** [comment]
unhold

**Comment by civanch** [comment]
@bsunanda , results are much more clean. The only problem (on different level) left is in the HI workflow, for example, in https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_8_0_X_2015-11-15-2300+12406/11364/140.53_RunHI2011+RunHI2011+RECOHID11+HARVESTDHI/JetMET__HIJetValidation_akPu4PFJets_DeltaRMatched_akVs4PFJets_ChargedHadEnergyFraction_Jet2_unmatched.png

**Comment by slava77** [comment]
Changes in HI are indeed the largest
e.g. https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_8_0_X_2015-11-15-2300+12406/11364/140.53_RunHI2011+RunHI2011+RECOHID11+HARVESTDHI/JetMET__HIJetValidation_akPu3PFJets_PFDeltaR.png

There are also changes in MC workflows in GlobalRecHitsV plots, e.g. 
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_8_0_X_2015-11-15-2300+12406/11364/1330.0_ZMM_13+ZMM_13+DIGIUP15+RECOUP15+HARVESTUP15/GlobalRecHitsV_HCals.html

**Comment by kpedro88** [comment]
@civanch, @slava77 - Some HI reco algorithm must also be using the rawId in an unsafe way (similar to the instances we have already corrected in PFlow). I will try to figure it out, but I am not very familiar with the HI code.

The MC validation plots change because the [validation code](https://github.com/cms-sw/cmssw/blob/CMSSW_8_0_X/Validation/GlobalRecHits/src/GlobalRecHitsAnalyzer.cc) uses the rawId, which has the new format for SimHits and the old format for RecHits. @bsunanda, can you fix that analyzer? I think you just need to add a different HcalMapType for the SimHit maps and tweak things accordingly: `typedef std::map<HcalDetId,float> HcalMapType`

**Comment by kpedro88** [comment]
@bsunanda, @civanch, @slava77 - I am pretty sure this producer is the culprit:
https://github.com/cms-sw/cmssw/blob/CMSSW_8_0_X/RecoHI/HiJetAlgos/plugins/ParticleTowerProducer.cc

According to this config: https://github.com/cms-sw/cmssw/blob/CMSSW_8_0_X/RecoHI/HiJetAlgos/python/HiRecoPFJets_cff.py, the PFTowers (I never knew about such an object until today) are used for the "akPu" jets, but not for the "akVs" jets. I think that matches what we see in the validation code.

On this line, it uses the subdet,eta,phi,depth HcalDetId constructor:
https://github.com/cms-sw/cmssw/blob/CMSSW_8_0_X/RecoHI/HiJetAlgos/plugins/ParticleTowerProducer.cc#L137

Then it tries to construct a CaloTowerDetId from the HcalDetId rawId, I'm really not sure what that will actually do:
https://github.com/cms-sw/cmssw/blob/CMSSW_8_0_X/RecoHI/HiJetAlgos/plugins/ParticleTowerProducer.cc#L168

It also has a lot of hardcoded geometry information that is probably out of date:
https://github.com/cms-sw/cmssw/blob/CMSSW_8_0_X/RecoHI/HiJetAlgos/plugins/ParticleTowerProducer.cc#L213

It seems like this producer needs significant work. Are there HI developers who can take responsibility for this?

**Comment by bsunanda** [comment]
@kpedro88 Which package is finding the mismatch - is it GlobalHits or GlobalRecHits?
________________________________
________________________________

**Comment by kpedro88** [comment]
@bsunanda - the problem in the validation code is in GlobalRecHits: https://github.com/cms-sw/cmssw/blob/CMSSW_8_0_X/Validation/GlobalRecHits/src/GlobalRecHitsAnalyzer.cc

**Comment by slava77** [comment]
@mandrenguyen please take a look at the issues noted by @kpedro88 in https://github.com/cms-sw/cmssw/pull/12406#issuecomment-157414484
(you appear to be the main developer of the code)

**Comment by bsunanda** [comment]
@cmsbuild please test

**Comment by bsunanda** [comment]
@slava77 @kpedro88 Only changed the building of the CaloTowerDetId - the way to define DetId from rawId is strictly true for the same DetId class. The geometry changes need to be transmitted - they will be soon obsolete. I can touch them if needed later.

**Comment by mandrenguyen** [comment]
@slava77 
I can certainly look into this at some point, but I've got my hands full with the HI run for the short term. 
If this PR is urgent for some other reason, and you have a solution that doesn't crash, it's not crucial that this producer behaves correctly for the time being in 8XY.  This release won't be used for HI for a while, so we have some time to fix this.

**Comment by kpedro88** [comment]
@bsunanda - that should be fine for Run2. Eventually we'll want to switch to using CaloTowerTopology for the CaloTowerDetIds here (to handle changes in HCAL eta/phi segmentation for the upgrades), but that is not very urgent.

**Comment by civanch** [comment]
+1

**Comment by deguio** [comment]
+1

**Comment by bsunanda** [comment]
@slava77 Do you think if it can be integrated

**Comment by slava77** [comment]
I'll look later today or over the weekend

**Comment by slava77** [comment]
@bsunanda 
sorry for the delay.
In jenkins tests there are small differences in HIJetValidation
e.g. 
wf140 53_ak4pu4pfjet

In local tests (I used CMSSW_8_0_0_pre2 as a baseline) I see also:
- in 4.37 (ZMuSkim2011B)  there are small differences in DeadCellMonitor_Hcal plots vs LS
wf4 37_deadcell_vsls
- all pp MC workflows (tested with recycled GEN-SIM) have essentially empty GlobalDigisV HF plots,
which looks like coming from 
https://github.com/cms-sw/cmssw/blob/CMSSW_8_0_0_pre2/Validation/GlobalDigis/src/GlobalDigisAnalyzer.cc#L1096
wf50202_hf_aeeoshe
wf50202_hf_shevsaee


I suspect that this default parameter in HcalDetId introduces more latent problems to be found out later. 
A more reliable solution to the code change would be better (even if it takes more effort to code)

**Comment by bsunanda** [comment]
@slava77 This is all due to bad use of DetId in the respective code. We need to adjust these codes.
@kpedro88 Could you figure out this
________________________________

**Comment by kpedro88** [comment]
@bsunanda - I won't have much time to work on this for a while. Analysis approval in 2 weeks and HF single anode readout implementation are taking priority. You could try one of @slava77's suggestions: remove the default value oldFormat=false in the HcalDetId constructor, and see what breaks...

@slava77, @davidlange6 - aren't we allowed to break things a little in the early prereleases?

**Comment by slava77** [comment]
On 11/23/15 6:47 PM, Kevin Pedro wrote:
> @bsunanda <https://github.com/bsunanda> - I won't have much time to work
> on this for a while. Analysis approval in 2 weeks and HF single anode
> readout implementation are taking priority. You could try one of
> @slava77 <https://github.com/slava77>'s suggestions: remove the default
> value oldFormat=false in the HcalDetId constructor, and see what breaks...
> 
> @slava77 <https://github.com/slava77>, @davidlange6
> <https://github.com/davidlange6> - aren't we allowed to break things a
> little in the early prereleases?

Hi Kevin,

my 2c on this.

Having something broken better be avoided.

The problem is the phase space of the broken pieces due to this PR.
If the issue was with a known set of non-essential workflows or algorithms,
it may be OK.
However, this PR effectively hides the problems.

Can you come up with a list of things to fix (to be possibly done in
follow up PRs)?

		--slava

**Comment by civanch** [comment]
@bsunanda , following Kevin proposal I locally have tried to take out default value of the parameter. Problems do exist but it seems not in huge number of classes. Also usage of DetId may be check...

**Comment by bsunanda** [comment]
It is always the usage which causes the problem. Casting rawId or comparisons on the basis of rawId is the issue. I shall go back to this in a couple of days time.
________________________________

**Comment by bsunanda** [comment]
One possibility to accept this PR is to change the default as OldFormat and then we handle other codes and switch back the default at that time. I need suggestion from Vladimir, Slava and David for this approach.
________________________________
From: Sunanda Banerjee
Sent: 25 November 2015 00:42
To: cms-sw/cmssw; cms-sw/cmssw
Subject: RE: [cmssw] bsunanda:Run2-hcx48 Expand Hcal DetId replacing bsunanda:Run2-hcx29 (11427) (#12406)

It is always the usage which causes the problem. Casting rawId or comparisons on the basis of rawId is the issue. I shall go back to this in a couple of days time.
________________________________

**Comment by slava77** [comment]
I don't know how much new code there is that relies on the new format to be the default.
It sounds safer for all the available code though to have the default to the old format.

Still, detid versions don't seem like a very good idea to me.

Here are some thoughts on the current situation:
It seems like there are two problems:
- This PR attempts to make up schema evolution in situ. In the long run what makes sense is to have only the new format. Only data written on "disk" in the past needs conversion from old to new. This should preferably be done during data streaming (maybe one can add a check function to relevant methods to trigger conversion). 
- latest fixes deal with a problem that there are dependent formats (HcalTrigTowerDetId, CaloTowerDetId) and an assumption in some code that the eta/phi/zside encoding is the same. If these are the only places, asserts can (should?) be added in corresponding constructors from raw ID
((rawID & kHcalIdMask) && (rawID & kHcalIdFormat2)) to detect all bad code.

With this in place, I'm not sure the format argument or access method should even be exposed in public methods.

.... did I miss anything?

**Comment by civanch** [comment]
@bsunanda , I have full list of classes which instantiate HcalDetId. If you need I can provide the list. However, likely problem not in creation of HcalDetId object but in use of it. In this sense, your implementation of the default parameter may be acceptable, also it is possible to keep old constructor without extra parameter but assign "false" to the flag. Only in few places the flag should be "true" and instead of extended constructor you may add a set method for this purpose. However, if the problem is in usage of DetId downstream and not in construction of it, then these two solutions are equivalent. In that case, addressing concrete concerns of Slava would be a practical solution - you fix only what does not work properly in tests used for validation.

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild  Please test

**Comment by slava77** [comment]
@bsunanda please cleanup the history of this PR.
It now shows up with 6K lines of changes in 300 files.

**Comment by slava77** [comment]
-1
superseded by #12726

**Comment by bsunanda** [comment]
This is obsolete and superseded by a new PR

**Pull request closed without merging**
