### PR TITLE
Update two variables of electron MVA to match the training definition (74X)

### PR DESCRIPTION
**Pull request by lgray**
Backport of #11260.

### CODE REVIEW

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
@gpetruc

**Comment by lgray** [comment]
@ikrav FYI

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/11262	f6dc8e7
- the same change in variables used to compute ele ID variable in miniAOD as introduced in 75X and 76X (no changes in RECO part)
- jenkins tests pass and comparisons with baseline show no difference

**Comment by lgray** [comment]
@davidlange6 Not merged into 74X somehow?

**Comment by lgray** [comment]
@davidlange6 Did this make it into 7_4_13? Why was it never merged?

**Comment by lgray** [comment]
@davidlange6 Nope... it did not make it into 7_4_13 despite being in 7_4_12 patches. Luckily we need a patch release anyway.

@gpetruc

**Comment by lgray** [comment]
@davidlange6 sorry, false alarm. Can't, in an easy way, tell that this PR is a noop due to different commit hash.

**Comment by lgray** [comment]
@davidlange6 Actually, I don't see any automatic merge or indication otherwise in ShowIB that 7_4_12_patchX was merged into the main 7_4_X. What's going on here?

**Comment by slava77** [comment]
On 9/28/15 3:56 PM, Lindsey Gray wrote:
> @davidlange6 <https://github.com/davidlange6> sorry, false alarm. Can't,
> in an easy way, tell that this PR is a noop due to different commit hash.

Lindsey, would you mind checking merge of this and other PRs you think
are missing
and close them if they are no-ops
and if not, we should get an update.

**Comment by lgray** [comment]
@davidlange6 @slava77 

https://github.com/cms-sw/cmssw/compare/CMSSW_7_4_13...cms-sw:CMSSW_7_4_12_patch4

As you can see there are some missing merges in 7_4_13... Unless this is part of some master plan?

**Comment by lgray** [comment]
@davidlange6 @slava77 @ikrav Correction - not merges but Ilya's fix *specifically is missing from 7_4_13. Please fix.

**Comment by davidlange6** [comment]
@lgray - yes, seems I lost this one. the other two PRs are consistent between patchX and 7_4_13

**Comment by lgray** [comment]
@gpetruc @davidlange6 Just for completeness.

**Comment by lgray** [comment]
@davidlange6 ping please include this one too

**Comment by davidlange6** [comment]
+1

**Pull request merged**
