### PR TITLE
[13_0_X] Update 2023 MC GT, VtxSmearing, PU library and fix RPC geometry in 2022/2023 MC GTs

### PR DESCRIPTION
**Pull request by saumyaphor4252**
#### PR description:

Backport of https://github.com/cms-sw/cmssw/pull/42265 and https://github.com/cms-sw/cmssw/pull/42139

This PR updates:

- The 2023 MC realistic GTs
  - See this [CMSTalk post](https://cms-talk.web.cern.ch/t/mc-call-for-conditions-for-2023-mc/24376/21) for a full list of updates
- New VtxSmearing for 2023 (`Realistic25ns13p6TeVEarly2023Collision`) included in https://github.com/cms-sw/cmssw/pull/41721
- The 2023 GEN-SIM PU library compatible with the 2023 BeamSpot
    - The samples have been produced by PdmV in [PDMVRELVALS-203](https://its.cern.ch/jira/browse/PDMVRELVALS-203)

In addition
- All the 2022 and 2023 MC GTs with the RPC geometry fix for the issue in the RPC chambers requested in [this CMS Talk post](https://cms-talk.web.cern.ch/t/fix-for-rpc-geometry-for-run3-data-and-mc/25678) [1]. 

[1] https://cms-talk.web.cern.ch/t/fix-for-rpc-geometry-for-run3-data-and-mc/25678

**GT Differences**:
 - **Phase1 2022 design**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/130X_mcRun3_2022_design_v2/130X_mcRun3_2022_design_v3

- **Phase1 2022 realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/130X_mcRun3_2022_realistic_v3/130X_mcRun3_2022_realistic_v4

- **Phase1 2022 realistic postEE**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/130X_mcRun3_2022_realistic_postEE_v3/130X_mcRun3_2022_realistic_postEE_v4

- **Phase1 2022 cosmics**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/130X_mcRun3_2022cosmics_realistic_deco_v3/130X_mcRun3_2022cosmics_realistic_deco_v4

- **Phase1 2022 cosmics design**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/130X_mcRun3_2022cosmics_design_deco_v2/130X_mcRun3_2022cosmics_design_deco_v3

- **Phase1 2022 realistic hi**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/130X_mcRun3_2022_realistic_HI_v6/130X_mcRun3_2022_realistic_HI_v7

- **Phase1 2023 design**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/130X_mcRun3_2023_design_v7/130X_mcRun3_2023_design_v8

- **Phase1 2023 realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/130X_mcRun3_2023_realistic_v9/130X_mcRun3_2023_realistic_v11

- **Phase1 2023 cosmics**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/130X_mcRun3_2023cosmics_realistic_deco_v8/130X_mcRun3_2023cosmics_realistic_deco_v10

- **Phase1 2023 cosmics design**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/130X_mcRun3_2023cosmics_design_deco_v7/130X_mcRun3_2023cosmics_design_deco_v8

- **Phase1 2023 realistic hi**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/130X_mcRun3_2023_realistic_HI_v14/130X_mcRun3_2023_realistic_HI_v15

#### PR validation:
GTs tested locally with `runTheMatrix.py -l 12034.0,11634.0,7.23,7.24,159.0,159.1,12434.0,12834.0  -j 8 --ibeos` and `runTheMatrix.py -l 13734.0 --what upgrade`

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

backport of https://github.com/cms-sw/cmssw/pull/42265 and https://github.com/cms-sw/cmssw/pull/42139

### CODE REVIEW

**Comment by saumyaphor4252** [comment]
test parameters:

- workflows = 12034.0,11634.0,7.23,7.24,159.0,159.1,12434.0,12834.0

**Comment by saumyaphor4252** [comment]
@cmsbuild, please test

**Comment by saumyaphor4252** [comment]
backport of https://github.com/cms-sw/cmssw/pull/42265

**Comment by saumyaphor4252** [comment]
@cmsbuild, please test

**Comment by tvami** [comment]
+alca

**Comment by sunilUIET** [comment]
+pdmv

**Comment by srimanob** [comment]
+Upgrade

**Comment by rappoccio** [comment]
+1

**Pull request merged**
