### PR TITLE
remove photoelectronsToAnalog python parameter (now taken from DB)

### PR DESCRIPTION
**Pull request by kpedro88**
After #17530, the `photoelectronsToAnalog` parameter for HB, HE, and HO is always taken from the database. This makes the corresponding Python parameter in the simulation redundant and possibly confusing, so it has been removed.

@bsunanda is it okay for the HcalTestBeam simulation to get these values only from the database as well? Please check the changes I made in this PR.

attn: @abdoulline @mariadalfonso

### CODE REVIEW

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by kpedro88** [comment]
No changes in the comparison, as expected

**Comment by civanch** [comment]
+1

**Comment by kpedro88** [comment]
@davidlange6 will this also be merged in 90X or should this PR be closed? (It's just code cleanup, not a new feature)

**Comment by davidlange6** [comment]
Hi @kpedro88 - i was expecting an answer to your questions -they are all ok now?

**Comment by kpedro88** [comment]
@bsunanda I guess this is fine for the test beam sim? (I hope so since it's already merged in 91X...)

**Comment by bsunanda** [comment]
Yes Kevin this is fine for TB
________________________________

**Comment by kpedro88** [comment]
@davidlange6 ping

**Comment by kpedro88** [comment]
@davidlange6 ping again

**Comment by davidlange6** [comment]
+1

**Pull request merged**
