### PR TITLE
[HGCAL] TiclDebugger Analyzer

### PR DESCRIPTION
**Pull request by ebrondol**
#### PR description:

This PR introduce the TiclDebugger which prints out information about HGCal Tracksters and their matching with the best CaloParticle. Compile with `scram b -v USER_CXXFLAGS="-D=EDM_ML_DEBUG"` to obtain `TICLDebugger.log`.
Example of printout here: https://cernbox.cern.ch/index.php/s/vjJ3ig5RZOIYz7n

#### PR validation:

No impact on workflows expected.

@rovere @lecriste @felicepantaleo

### CODE REVIEW

**Comment by rovere** [comment]
@cmsbuild please test

**Comment by perrotta** [comment]
+1
- A new analyzer added in \tests for debug purposes
- Tested to run without errors

**Comment by srimanob** [comment]
+Upgrade

Just to add analyzer code.

**Comment by silviodonato** [comment]
+1

**Pull request merged**
