### PR TITLE
Cmssw 8 1 x 2016 12 14 1100 clus trend

### PR DESCRIPTION
**Pull request by cecchcms**

### CODE REVIEW

**Comment by cecchcms** [comment]
Added plots for cluster trends in DQM/SiStripMonitorCluster plus switch changed for APV plots

**Comment by Martin-Grunewald** [comment]
-1
looks like wrong branch, or a rebase needed

**Comment by mmusich** [comment]
-1

**Comment by slava77** [comment]
-1

**Comment by ianna** [comment]
-1

**Pull request closed without merging**
