### PR TITLE
Read SLHA from TTree [9_4_X]

### PR DESCRIPTION
**Pull request by kpedro88**
backport of #31733

This backport was actually successful with `cms-rebase-topic` (starting from #32018).

### CODE REVIEW

**Comment by kpedro88** [comment]
please test

**Comment by silviodonato** [comment]
@kpedro88 could you add in the description the reason of the backport? (I guess it is for the production with fast sim)

**Comment by agrohsje** [comment]
+1

**Comment by silviodonato** [comment]
+1
@kpedro88 I assume we need this backport for fastsim

**Comment by kpedro88** [comment]
@silviodonato yes, this is for pMSSM production.

**Pull request merged**
