### PR TITLE
kCanRebin is replaced with SetCanExtend in online beamspot code for dqm

### PR DESCRIPTION
**Pull request by sushilchauhan**
kCanRebin is replaced with SetCanExtend in online BeamSpot code for DQM to work properly in 74x

### CODE REVIEW

**Comment by deguio** [comment]
+1
this one will be tested in the online DQM playback

**Comment by deguio** [comment]
@danduggan

**Comment by deguio** [comment]
@sushilchauhan
please submit to 75 as well otherwise the change is lost.
thanks,
F.

**Comment by davidlange6** [comment]
+1

**Comment by wmtan** [comment]
This PR should not have been merged into 7_4_ROOT5_X.  It is ROOT6 specific.  It breaks 7_4_ROOT5_X.

**Pull request merged**
