### PR TITLE
2017 HCAL Trigger Primitives

### PR DESCRIPTION
**Pull request by matz-e**
Rough implementation of 2017 HCAL Trigger Primitives using QIE10/11.

Adding:
- Linearization LUTs for QIE10/11
- HF TP with QIE10 dual-anode read-out and energy recovery
- HE TP with QIE11

Finegrain bits will come with a later pull request.

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by abdoulline** [comment]
@ghellwig, @rekovic  @mmusich, @mulhearn
Could you, please, revise/approve it?

**Comment by abdoulline** [comment]
@ghellwig, @rekovic @mmusich, @mulhearn

Could you, please, revise/approve it??  - We do need to move on towards 2017...

**Comment by matz-e** [comment]
Any comments? I'd like to get this in to build on top of it…

**Comment by kpedro88** [comment]
@davidlange6 @ghellwig, @rekovic, @mmusich, @mulhearn we need to make progress, please sign/merge

**Comment by mulhearn** [comment]
+1

**Comment by mulhearn** [comment]
Sorry!

**Comment by mmusich** [comment]
+1

**Comment by davidlange6** [comment]
Hi @matz-e - are there dqm plots that include monitoring of these primitives (trying to avoid breaking the 2016 primitives as done already once)?

**Comment by matz-e** [comment]
@davidlange6 the regular DQM should capture the 2017 HE/HF TPs. There are no geometry changes in this PR, which was the root of the 2016 TP breakage.

I wanted to go back and check the comparisons of the old TPs that broke and restored the 2016 TPs, but they've already been deleted.  Is there a way to run these comparisons on lxplus/cmsdev? I can see if I can check that TP breakage will be noticed in the future.

**Comment by davidlange6** [comment]
+1
ok - seems there should not be a problem then - as no histograms changed in the 2016 comparisons - @matz-e - i'm not sure which recipe you are looking for. in the end if you run two workflows you end up with two dqm files from which you can compare histograms directory (there is a script to compare everything in the dqm if that is what you are asking for - I can did that up if you wish)

**Comment by matz-e** [comment]
@davidlange6 Thanks! If it's just that, I can quickly roll my own script. Just thought there may be a "push-one-button" version.

**Pull request merged**
