### PR TITLE
Run3-Sim152Y Enable the code to handle DD4hep and DDD inputs simultaneously in SimTracker

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Enable the code to handle DD4hep and DDD inputs simultaneously in SimTracker

#### PR validation:

Use the runTheMatrix test workflows

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
@bsunanda , DD4hep covert physics volume name using  copy number, for example "CMSE" -> "CMSE_1". Is this fact considered in the fix you propose in this and other PRs?

**Comment by bsunanda** [comment]
Many parts of the codes make use of the changes imposed by dd4hep. For logical volume only the namespace is added. For physical volume in addition the copy number is added, We make use of them in some parts of the code. We can have some stripping functions within Sim. I shall do that sometime.

**Comment by bsunanda** [comment]
Close this PR in favour of #43546

**Comment by bsunanda** [comment]
I wrongly closed this PR

**Comment by bsunanda** [comment]
@civanch Please sign this PR. I shall correct dd4hep dependence after it is merged

**Comment by civanch** [comment]
+1

**Comment by rappoccio** [comment]
+1

**Pull request merged**
