### PR TITLE
[Backport] A fix for importing dependencies in DQM bin by bin tool

### PR DESCRIPTION
**Pull request by andrius-k**
#### PR description:

A fix for importing dependencies in DQM bin by bin tool

#### PR validation:

PR was validated locally.

#### if this PR is a backport please specify the original PR:

A backport of #28494.

### CODE REVIEW

**Comment by andrius-k** [comment]
please test

**Comment by andrius-k** [comment]
please test

**Comment by andrius-k** [comment]
+1

**Comment by smuzaffar** [comment]
please ignore the last comment by bot

**Comment by andrius-k** [comment]
Hello @fabiocos, is there something else that needs to be provided for this PR to be merged?

**Comment by fabiocos** [comment]
+1

not urgent for a build, but may be usable for private studies

**Pull request merged**
