### PR TITLE
Run2-sim22 Make pure EM physics lists

### PR DESCRIPTION
**Pull request by bsunanda**
In view of tests with GeantV. One has to choose Physics.type = "SImG4Core/Physics/EMPhysics" and with Physics.EMPhysics set to true|false one chooses the EMStandard and EML lists

### CODE REVIEW

**Comment by civanch** [comment]
-1

**Comment by civanch** [comment]
@bsunanda , there is already DummyPhysics, because it is not used anywhere it can be considered for such test. We do not need extra plugin. At the same time, DummyEMPhysics class should be modified in a way that it is compatible with GeantV physics. What you included as a variant of EM physics is not compatible with GeantV - it has much more physics.

**Comment by davidlange6** [comment]
please test

**Comment by civanch** [comment]
@bsunanda , to be more clear: GeantV physics is limited to gamma, e+, e- and only for limited set of basic processes. There is no sense instantiating CMS EM physics alone - no sense making Physics List as you did, because if, for example, one want to check current EM physics for gamma, e-, e+ he/she should use FTFP_BERT_EMM directly - no difference with what you propose. If we need reduced Physics List fully equivalent to GeantV, then it can be created on base of DummyEMPhysics.cc.

**Comment by bsunanda** [comment]
This is superseded by PR #22357 submitted by Vladimir.

**Pull request closed without merging**
