### PR TITLE
HCALDQM: Improve LED monitoring (10_3_X)

### PR DESCRIPTION
**Pull request by DryRun**
Improves monitoring of the HCAL calibration LEDs:

- Detector coordinates of LED calibration channels are configurable in python.
- Misfires (from high ADC signal in CUs) are counted vs. LS.
- LED monitoring is done in both online and offline DQM, to help certification in the event of misfires.
- HF LED monitoring added (previously only HE).

### CODE REVIEW

**Comment by andrius-k** [comment]
please test

**Comment by DryRun** [comment]
Sorry, I realized that I should combine this with some other non-factorizable changes, so I added two more commits. It should be set now.

**Comment by andrius-k** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
