### PR TITLE
trivial V10 customize (12_4)

### PR DESCRIPTION
**Pull request by mariadalfonso**
Next central production for Run3 should be procured with the following options with the cmsdriver command

cmsDriver.py step5  -s NANO  --era Run3 --customise=PhysicsTools/NanoAOD/V10/nano_cff.nanoAOD_customizeV10

### CODE REVIEW

**Comment by qliphy** [comment]
backport of #38668

**Comment by mariadalfonso** [comment]
please test

**Comment by mariadalfonso** [comment]
+xpog

initial customisation for V10nano

**Comment by qliphy** [comment]
+1

**Pull request merged**
