### PR TITLE
[DD4hep] Start Core Code Cleanup

### PR DESCRIPTION
**Pull request by ianna**
#### PR description:

* Remove unused clases
* Clean up unused API
* Tidy up header guards

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
@smuzaffar - this is strange...
```diff
===== Test "cmsRun /data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_2_X_2020-09-14-1100/src/DetectorDescription/DDCMS/test/python/testDDDetectorESProducer.py " ====
----- Begin Fatal Exception 14-Sep-2020 15:07:13 CEST-----------------------
An exception of category 'PluginLibraryLoadError' occurred while
   [0] Constructing the EventProcessor
   [1] While attempting to load plugin DDTestNavigateGeometry
Exception Message:
unable to load /data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_2_X_2020-09-14-1100/lib/slc7_amd64_gcc820/poisoned/plugin-poisoned-DetectorDescriptionTestPlugins.so because /data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_2_X_2020-09-14-1100/lib/slc7_amd64_gcc820/poisoned/plugin-poisoned-DetectorDescriptionTestPlugins.so: cannot open shared object file: No such file or directory
----- End Fatal Exception -------------------------------------------------
Failure using cmsRun /data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_2_X_2020-09-14-1100/src/DetectorDescription/DDCMS/test/python/testDDDetectorESProducer.py: status 65
status = 16640

---> test DetectorDescriptionDDCMSTestDriver had ERRORS
 
^^^^ End Test DetectorDescriptionDDCMSTestDriver ^^^^
Package SimG4Core/Geometry: Running test Tubs_

```

**Comment by ianna** [comment]
please test

**Comment by cvuosalo** [comment]
+1

**Comment by cvuosalo** [comment]
hold

**Comment by cvuosalo** [comment]
Please fix the unit test. I thought the PR had passed all tests when I approved it, but then the unit test failure was reported after my approval.

**Comment by ianna** [comment]
```diff
----- Begin Fatal Exception 14-Sep-2020 16:54:42 CEST-----------------------
An exception of category 'FileInPathError' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing ESSource: class=XMLIdealGeometryESSource label=''
Exception Message:
Path /data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_2_X_2020-09-14-1100/test-data-file-deletion/src/Geometry/CMSCommonData/data/materials.xml is a directory, not a file
----- End Fatal Exception -------------------------------------------------

```

**Comment by ianna** [comment]
please test

**Comment by cvuosalo** [comment]
unhold

**Comment by cvuosalo** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
