### PR TITLE
fix clang static analyzer warning using namespace in header

### PR DESCRIPTION
**Pull request by gartung**

### CODE REVIEW

**Comment by gartung** [comment]
@Dr15Jones

**Comment by Dr15Jones** [comment]
please test

**Comment by slava77** [comment]
a  combined PR with other similar ones (at least by L2 area) would be nicer.
Less load on jenkins and faster to approve.

**Comment by cvuosalo** [comment]
+1

For #11020 2447b598f5023bd19bd6925ec099c6fe35ef978d

Fixing namespace warnings in jet pile-up header file. There should be no change in run-time behavior.

The code changes are satisfactory, and Jenkins tests against baseline CMSSW_7_6_X_2015-08-28-1100 show no significant differences, as expected.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
