### PR TITLE
Evt gen mixing bs patch 2015 02 19

### PR DESCRIPTION
**Pull request by inugent**
New pull request to replace pull #7862 (includes patch for problem with filter efficiency)

### CODE REVIEW

**Comment by covarell** [comment]
+1

**Comment by inugent** [comment]
Hello, 
What is the timeline for this to be integrated into CMSSW. This is a critical patch for the EvtGen 1.30 required for the B-Physics group and should be back ported to 7_1_X for production? What is the timeline for adding it to a release so it can be validated? Please advise?
Thank you and best regards,
Ian

**Comment by franzoni** [comment]
+1
@inugent  fine with what you've added here.
Note that there's no agreement on running these relvals as part of the release validation production (do you have a proposal for replacing some of the 25 gen relvals which are run in production)

**Comment by davidlange6** [comment]
+1

**Pull request merged**
