### PR TITLE
Backport CsHepFilter

### PR DESCRIPTION
**Pull request by Andrej-CMS**
this is the backport of https://github.com/cms-sw/cmssw/pull/25479

@panwarlsweet do you need backports to other CMSSW versions?

### CODE REVIEW

**Comment by alberto-sanchez** [comment]
please test

**Comment by panwarlsweet** [comment]
@Andrej, yes, for Fall 17 sample I need it for CMSSW_9_3_X and for Fall18 sample, I need it for CMSSW_10_2_X.

**Comment by alberto-sanchez** [comment]
+1

**Comment by kpedro88** [comment]
backport of #25479

**Comment by kpedro88** [comment]
+1

**Pull request merged**
