### PR TITLE
[14_0_X] Backports of 46543 and 46451 to fix memory leak

### PR DESCRIPTION
**Pull request by srimanob**
#### PR description:
Try to fix memory leak issue, mentionedin https://github.com/cms-sw/cmssw/issues/46901, for ReReco 2024 with CMSSW_14_0.

Backports of 

- https://github.com/cms-sw/cmssw/pull/46451 
- https://github.com/cms-sw/cmssw/pull/46543

#### PR validation:
- CMSSW with this PR can run.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:
-

### CODE REVIEW

**Comment by srimanob** [comment]
@cmsbuild please test

**Comment by srimanob** [comment]
This is an effort to handle https://github.com/cms-sw/cmssw/issues/46901

**Comment by antoniovagnerini** [comment]
+dqm

**Comment by perrotta** [comment]
+db

**Comment by srimanob** [comment]
Kindly ping @cms-sw/l1-l2 in case we need to build the new release for reprocessing. Thanks.

**Comment by srimanob** [comment]
@cms-sw/orp-l2 Could you please consider this backport? We will need a new release for ReReco.

FYI @vlimant @malbouis

**Comment by srimanob** [comment]
The comparison between with and without this PR can be found at https://github.com/cms-sw/cmssw/issues/46901#issuecomment-2533068164

**Comment by aloeliger** [comment]
+l1

**Comment by mandrenguyen** [comment]
@srimanob should we consider backporting to intermediate releases?

**Comment by srimanob** [comment]
> @srimanob should we consider backporting to intermediate releases?

Hi Matt, Do you mean 14_1? Yes, I can do it. Thx.

**Comment by mandrenguyen** [comment]
> > @srimanob should we consider backporting to intermediate releases?
> 
> Hi Matt, Do you mean 14_1? Yes, I can do it. Thx. I first need it for 14_0 used for ReReco.

Yes, please make the PRs to the intermediate release(s) and then we'll merge this.

**Comment by srimanob** [comment]
Hi @mandrenguyen 
Both backport PRs were merged in 14_1:
https://github.com/cms-sw/cmssw/pull/46465 ([14.1.X] make AlcaBeamMonitor hoard less memory)
https://github.com/cms-sw/cmssw/pull/46567 ([14_1] Fix memory leak issues in Calo Layer 1 UCT Infrastructure)

**Comment by mandrenguyen** [comment]
backport of https://github.com/cms-sw/cmssw/pull/46451

**Comment by mandrenguyen** [comment]
+1

**Comment by mandrenguyen** [comment]
merge

**Comment by iarspider** [comment]
@srimanob could you please resolve conflicts? Thanks!

**Comment by srimanob** [comment]
Hi @iarspider 
How do show which conflicts? I just see the warning shows up.

**Comment by smuzaffar** [comment]
bot can see that this has been merged. It is visible as merged in IB page https://cmssdt.cern.ch/SDT/html/cmssdt-ib/#/ib/CMSSW_14_0_X

**Pull request closed without merging**
