### PR TITLE
consistent implementation of nano step for Run 3

### LINKED ISSUE #35966: Run3 production-like workflow contains duplicated NANO step since 12_1_0_pre5
We noticed that in 12_1_0_pre5, when running

```
runTheMatrix.py -w upgrade -l 11834.21 --dryRun
```

the output contains a new "step6", which is a duplicate of the previous NANO step, without some PU flags. Is this expected?

```
Preparing to run 11834.21 TTbar_14TeV+2021PU_ProdLike+TTbar_14TeV_TuneCP5_GenSim+DigiPU+RecoPU+MiniAODPU+NanoPU+Nano

# in: /afs/cern.ch/work/j/jpata/CMSSW_12_1_0_pre5 dryRun for 'cd 11834.21_TTbar_14TeV+2021PU_ProdLike+TTbar_14TeV_TuneCP5_GenSim+DigiPU+RecoPU+MiniAODPU+NanoPU+Nano
 cmsDriver.py TTbar_14TeV_TuneCP5_cfi  -s GEN,SIM -n 10 --conditions auto:phase1_2021_realistic --beamspot Run3RoundOptics25ns13TeVLowSigmaZ --datatier GEN-SIM --eventcontent FEVTDEBUG --geometry DB:Extended --era Run3 --relval 9000,100 --fileout file:step1.root  > step1_TTbar_14TeV+2021PU_ProdLike+TTbar_14TeV_TuneCP5_GenSim+DigiPU+RecoPU+MiniAODPU+NanoPU+Nano.log  2>&1
 

# in: /afs/cern.ch/work/j/jpata/CMSSW_12_1_0_pre5 dryRun for 'cd 11834.21_TTbar_14TeV+2021PU_ProdLike+TTbar_14TeV_TuneCP5_GenSim+DigiPU+RecoPU+MiniAODPU+NanoPU+Nano
 cmsDriver.py step2  -s DIGI,L1,DIGI2RAW,HLT:@relval2021 --conditions auto:phase1_2021_realistic --datatier GEN-SIM-RAW -n 10 --eventcontent RAWSIM --geometry DB:Extended --era Run3 --pileup Run3_Flat55To75_PoissonOOTPU --pileup_input das:/RelValMinBias_14TeV/CMSSW_12_0_0_pre4-120X_mcRun3_2021_realistic_v2-v1/GEN-SIM --filein  file:step1.root  --fileout file:step2.root  > step2_TTbar_14TeV+2021PU_ProdLike+TTbar_14TeV_TuneCP5_GenSim+DigiPU+RecoPU+MiniAODPU+NanoPU+Nano.log  2>&1
 

# in: /afs/cern.ch/work/j/jpata/CMSSW_12_1_0_pre5 dryRun for 'cd 11834.21_TTbar_14TeV+2021PU_ProdLike+TTbar_14TeV_TuneCP5_GenSim+DigiPU+RecoPU+MiniAODPU+NanoPU+Nano
 cmsDriver.py step3  -s RAW2DIGI,L1Reco,RECO,RECOSIM --conditions auto:phase1_2021_realistic --datatier AODSIM -n 10 --eventcontent AODSIM --geometry DB:Extended --era Run3 --pileup Run3_Flat55To75_PoissonOOTPU --pileup_input das:/RelValMinBias_14TeV/CMSSW_12_0_0_pre4-120X_mcRun3_2021_realistic_v2-v1/GEN-SIM --filein  file:step2.root  --fileout file:step3.root  > step3_TTbar_14TeV+2021PU_ProdLike+TTbar_14TeV_TuneCP5_GenSim+DigiPU+RecoPU+MiniAODPU+NanoPU+Nano.log  2>&1
 

# in: /afs/cern.ch/work/j/jpata/CMSSW_12_1_0_pre5 dryRun for 'cd 11834.21_TTbar_14TeV+2021PU_ProdLike+TTbar_14TeV_TuneCP5_GenSim+DigiPU+RecoPU+MiniAODPU+NanoPU+Nano
 cmsDriver.py step4  -s PAT --conditions auto:phase1_2021_realistic --datatier MINIAODSIM -n 10 --eventcontent MINIAODSIM --geometry DB:Extended --era Run3 --pileup Run3_Flat55To75_PoissonOOTPU --pileup_input das:/RelValMinBias_14TeV/CMSSW_12_0_0_pre4-120X_mcRun3_2021_realistic_v2-v1/GEN-SIM --filein  file:step3.root  --fileout file:step4.root  > step4_TTbar_14TeV+2021PU_ProdLike+TTbar_14TeV_TuneCP5_GenSim+DigiPU+RecoPU+MiniAODPU+NanoPU+Nano.log  2>&1
 

# in: /afs/cern.ch/work/j/jpata/CMSSW_12_1_0_pre5 dryRun for 'cd 11834.21_TTbar_14TeV+2021PU_ProdLike+TTbar_14TeV_TuneCP5_GenSim+DigiPU+RecoPU+MiniAODPU+NanoPU+Nano
 cmsDriver.py step5  -s NANO --conditions auto:phase1_2021_realistic --datatier NANOAODSIM -n 10 --eventcontent NANOEDMAODSIM --filein file:step4.root --geometry DB:Extended --era Run3 --pileup Run3_Flat55To75_PoissonOOTPU --pileup_input das:/RelValMinBias_14TeV/CMSSW_12_0_0_pre4-120X_mcRun3_2021_realistic_v2-v1/GEN-SIM --fileout file:step5.root  > step5_TTbar_14TeV+2021PU_ProdLike+TTbar_14TeV_TuneCP5_GenSim+DigiPU+RecoPU+MiniAODPU+NanoPU+Nano.log  2>&1
 

# in: /afs/cern.ch/work/j/jpata/CMSSW_12_1_0_pre5 dryRun for 'cd 11834.21_TTbar_14TeV+2021PU_ProdLike+TTbar_14TeV_TuneCP5_GenSim+DigiPU+RecoPU+MiniAODPU+NanoPU+Nano
 cmsDriver.py step6  -s NANO --conditions auto:phase1_2021_realistic --datatier NANOAODSIM -n 10 --eventcontent NANOEDMAODSIM --filein file:step4.root --geometry DB:Extended --era Run3 --fileout file:step6.root  > step6_TTbar_14TeV+2021PU_ProdLike+TTbar_14TeV_TuneCP5_GenSim+DigiPU+RecoPU+MiniAODPU+NanoPU+Nano.log  2>&1
 
11834.21_TTbar_14TeV+2021PU_ProdLike+TTbar_14TeV_TuneCP5_GenSim+DigiPU+RecoPU+MiniAODPU+NanoPU+Nano Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED Step5-PASSED  - time date Wed Nov  3 14:40:52 2021-date Wed Nov  3 14:40:52 2021; exit: 0 0 0 0 0 0
1 1 1 1 1 1 tests passed, 0 0 0 0 0 0 failed
```

cc @cms-sw/xpog-l2 @cms-sw/pdmv-l2

### PR DESCRIPTION
**Pull request by kpedro88**
#### PR description:

Supersedes #36050 to fix #35966 by redoing #35412 in a consistent way. All special workflows that target Run 3 scenarios are updated to handle the new Nano-related steps.

#### PR validation:

Checked both relval and production-like workflows to see that the desired steps are created.

### CODE REVIEW

**Comment by kpedro88** [comment]
test parameters:
workflow = 11834.21
relvals_opt = -w upgrade

**Comment by kpedro88** [comment]
please test

**Comment by kpedro88** [comment]
@smuzaffar it seems like adding `-w upgrade` prevented it from running the normal matrix tests. I thought this had worked in the past. Is there a different setting needed?

**Comment by smuzaffar** [comment]
@kpedro88 , I don't think it ever worked. The only way is to explicitly pass `-w <comma,separated,list,of,other,works,>upgrade` . Note that there are some sets which define the same workflow number. So it is bit tricky to get the correct list

**Comment by kpedro88** [comment]
okay, i'm just going to add it to the regular matrix.

**Comment by kpedro88** [comment]
test parameters:
workflow = 11834.21

**Comment by kpedro88** [comment]
please test

**Comment by mariadalfonso** [comment]
@kpedro88 
Thanks for this, it's timely.

The errors rings a bell
https://github.com/cms-sw/cmssw/pull/36167#issuecomment-974208403
I had (temporarily) to use the run3_nanoAOD_devel to switch off some sequence for photons and electrons.
https://github.com/cms-sw/cmssw/pull/34714
The ideas was that once we finalise the Run3 configuration this is not needed anymore.
(run3_nanoAOD_devel  instead of Run3 because it's easily searchable)

How do we proceed ?

**Comment by kpedro88** [comment]
@mariadalfonso thanks for pointing out that this issue had been seen before. I was initially puzzled as to why it only affected the .914 special workflow, but this helped me realize that workflow in particular was dropping the `run3_nanoAOD_devel` modifier. This should be fixed now (in my latest commit).

**Comment by kpedro88** [comment]
please test

**Comment by mariadalfonso** [comment]
would be nice to have this PR soon, so that next integrations of the nano in view of Run3 are validated in the runTheMatrix
@cms-sw/upgrade-l2 @cms-sw/pdmv-l2 : is there something more to check ?

**Comment by kskovpen** [comment]
+1

**Comment by qliphy** [comment]
+1

**Comment by slava77** [comment]
apparently this broke GPU workflows
`runTheMatrix.py -w gpu -n -e -l 11634.506` had 4 steps in CMSSW_12_2_X_2021-11-29-1100 and only 2 steps in CMSSW_12_2_X_2021-11-29-2300 and the only relevant change seems to be from this PR.

@cms-sw/heterogeneous-l2

**Comment by kpedro88** [comment]
@slava77 thanks for spotting this, see #36309

**Pull request merged**
