### PR TITLE
bugfix for ConversionTools

### PR DESCRIPTION
**Pull request by matteosan1**
Bug fix in ConversionTools; one function call was missing a parameter.

On line 313 the call:
hasMatchedConversion(*it,convCol,beamspot,lxyMin,probMin,nHitsBeforeVtxMax)
When *it is a reco::GsfElectron (L305), the called function is 
defined in line 51-52 of the header.
The function prototype for this version, expects the 4th argument to be 
"bool allowCkfMatch" but in the function call this parameter is missing 
(or, rather, the value of lxyMin is passed in this spot). 
Since "float" can be cast to "bool" and "unsigned int" can be cast to "float", 
it will compile but the behavior will not be what is expected.

After the fix we expect to see slightly more photons not passing the electron veto i.e. passElectronVeto()==0
(in gamma+Jet sample I see the percentage going from 7.7% to 8.0%).

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
@degano, @nclopezo: Like 7918, the Jenkins "Comparison with the baseline" for this PR is stuck in Queued state.

**Comment by cvuosalo** [comment]
+1
For #7917 e883053cc65e9dac81ad4b76481f38eef65d39c3

A very small code change of adding an optional parameter to a function call. It should not cause any differences. Same as #7918, which is targeted for 74X.

The code change is satisfactory. Jenkins tests against baseline [CMSSW_7_5_X_2015-02-25-1400] (https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-7917/2937/summary.html) show no significant differences, as expected.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
