### PR TITLE
Remove occupancy-based flagging of merged clusters

### PR DESCRIPTION
**Pull request by wmtford**
This just cleans up SiStripClusterizer removing the code that calculates sensor occupancy and flags a cluster as merged if that occupancy is above a threshold.  This approach didn't prove effective in a pileup environment, and instead we implemented the chargePerCM cut in stripCPEfromTrackAngle.  I have left a null refineCluster member function that can be overwritten in a derived class to facilitate studies.
This PR obviates the need to address three of the four parameters cited in this JIRA ticket:
https://its.cern.ch/jira/browse/CMSTRACK-120
since doRefineCluster, occupancyThreshold, and widthThreshold have been removed.
This PR has no effect on production with the default parameters.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cmsbuild please test
the last iteration appears to be file access or das error, not relevant to this code

**Comment by cvuosalo** [comment]
Under review by Reco...

**Comment by cvuosalo** [comment]
+1

For #7894 70610c12424c1194e7d39b082e7abe59f34de58c

Clean-up of the SiStripClusterizer to remove provisional code that is not used in standard production. The change is not expected to produce differences with the standard tests.

Code changes are satisfactory, and the Jenkins tests against [CMSSW_7_4_X_2015-02-21-1400] (https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-7894/2812/summary.html) show no significant differences, as expected.

**Comment by wmtford** [comment]
When testing a derived class I realized that the (null) function refineCluster needs to be declared virtual.

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
@degano, @nclopezo: Jenkins "Comparison with baseline" never completed and is stuck in the Queued state. Could you please take a look?

**Comment by wmtford** [comment]
I decided after all it's cleaner not to include the (null) clusterRefiner method at this time.  (Implementing code based on it in a useful way would require further changes.)  So now this PR simply backs out the sensor-occupancy-based flagging of merged clusters.

**Comment by nclopezo** [comment]
@cvuosalo I started the comparison again.

**Comment by cvuosalo** [comment]
+1

For #7894 b94cacd41598ca9f9accbf4648c7e56814be8fa5

A very tiny code change was made after this PR was approved by Reco. The code change is OK, and Jenkins and matrix tests after the change are also OK.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
