### PR TITLE
GEMDQMStatusDigi bug fix

### PR DESCRIPTION
**Pull request by hyunyong**
The current GEMStatusDigi module has 2 bugs.
1. incorrect geb status module label
2. ME title has a dot

I will make backport for 10_6_X soon. 

@jshlee

### CODE REVIEW

**Comment by jfernan2** [comment]
@hyunyong this PR is doing the same as the last commit of #27419  and in the same target release

**Comment by hyunyong** [comment]
> @hyunyong this PR is doing the same as the last commit of #27419 and in the same target release

DQM group wants this fix as soon as possible. So, I made it.

**Comment by fabiocos** [comment]
@hyunyong whatever backport must correspond to a code in master, this is a basic practice.
Could you please clarify the reason and target of the urgency?

**Comment by fabiocos** [comment]
please test

**Comment by jfernan2** [comment]
@fabiocos  the backport of this PR is #27487  which is needed (locally) in Online DQM for MWGR
The point is that THIS current PR in 11_0_X is already included in #27419  already signed by DQM, so I understand THIS current PR is not actually needed
Thanks

**Comment by boudoul** [comment]
Hello @jfernan2  Why this is needed on the online DQM for this MWGR ?

**Comment by jfernan2** [comment]
@boudul It was crashing DQM Online GUI due to a dot in a histo name, it does not imply a new IB, just the PR will be included in the DQM Online GUI Machine at P5, no need to merge the PR, the backport one #27487  , no this one we are writing on.

**Comment by fioriNTU** [comment]
@jfernan2 I think we are not going to include this PR in Online, the GEM detector is not in MWGR#3. I guess that some confusion has been created since Andrius reported this bug after testing the Online system.

**Comment by boudoul** [comment]
[Yes I undertand this is the other PR but that's fine to continue here]
I'm surprised that this is crashing the online and not the offline - I'm also surprised that we are actullay running a GEM client but why not, and finally I hope that we are not running this : https://github.com/cms-sw/cmssw/blob/master/DQM/Integration/python/clients/gem_dqm_sourceclient-live_cfg.py   which is obviously not uptodate

**Comment by jfernan2** [comment]
@boudoul   we are runing that one yes, which produces empty plots as expected, that's what GEM developers provide us for Online DQM GUI. 

Just have a look at Online DQM GUI, you will see there is a GEM workspace. there is no GEM workspace in Offline DQM GUI yet, so no crash there

**Comment by boudoul** [comment]
Presumably it would be much more important at this point to get a GEM workspace in the offline to validate carefully the already existing and running  GEM software rather than having an empty online workspace for a a detector which is not delivering data . Good topic to discuss with your PdmV colleagues...

**Comment by jfernan2** [comment]
@boudoul   Note taken. Thanks

**Comment by schneiml** [comment]
@boudoul @jfernan2  note that the `.` in the ME name will unconditionally crash the process. So, even for offline, this module is either not used anywhere or won't work.

**Comment by hyunyong** [comment]
GEM doesn't have an offline DQM yet. During 2018, GEM had the demonstration running with few chambers and it wasn't used for physic.

**Comment by jfernan2** [comment]
+1

**Comment by fabiocos** [comment]
@hyunyong this fix has been already merged in the context of #27419 , so this PR may be simply closed

**Comment by hyunyong** [comment]
@fabiocos ok Thank you!

**Pull request closed without merging**
