### PR TITLE
Tracker alignment validation das client

### PR DESCRIPTION
**Pull request by hroskes**
Make the dataset class compatible with the new das go client.

Some sections are there temporarily to revert to the old das_client until the dasgoclient is updated in cvmfs.  Once it's updated, those sections can be removed without any effect on the code.

The dasgoclient makes `validateAlignments.py -c testValidate.ini -N testValidate -n` a factor of 3 faster.  I checked that we get equivalent behavior with either the new or the old clients.

https://hypernews.cern.ch/HyperNews/CMS/get/sw-develtools/2504.html

### CODE REVIEW

**Comment by arunhep** [comment]
please test

**Comment by mmusich** [comment]
the failing unit test is there already in the baseline CMSSW IB (CMSSW_9_3_X_2017-07-03-1100) used for tests (see [logs](https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc6_amd64_gcc530/CMSSW_9_3_X_2017-07-03-1100/unitTestLogs/Alignment/OfflineValidation)).
It has been fixed since CMSSW_9_3_0_pre1 via: https://github.com/cms-sw/cmssw/pull/19507

**Comment by arunhep** [comment]
@hroskes 
here is the unit test [crash](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-19539/21130/unitTests.log) 

Genexception1: An exception of category 'WrongTrackerSubDet' occurred.
Exception Message:
Invalid DetID: no GeomDetUnit associated with raw ID 303087628 of subdet ID 1
%MSG
%MSG-e TrackProducer:  TrackRefitter:FinalTrackRefitter  04-Jul-2017 15:23:51 CEST Run: 1 Event: 1851
cms::Exception caught during theAlgo.runWithTrack.
An exception of category 'WrongTrackerSubDet' occurred.
Exception Message:
Invalid DetID: no GeomDetUnit associated with raw ID 303087628 of subdet ID 1
%MSG
----- Begin Fatal Exception 04-Jul-2017 15:23:51 CEST-----------------------
An exception of category 'WrongTrackerSubDet' occurred while
   [0] Processing  Event run: 1 lumi: 38 event: 1851 stream: 0
   [1] Running path 'p'
   [2] Calling method for module TrackRefitter/'FinalTrackRefitter'
Exception Message:
Invalid DetID: no GeomDetUnit associated with raw ID 303087628 of subdet ID 1
----- End Fatal Exception -------------------------------------------------

**Comment by arunhep** [comment]
@mmusich then this PR needs a rebase.

**Comment by mmusich** [comment]
@arunhep, no - we need tests against a more release.
@smuzaffar when will a release younger than CMSSW_9_3_0_pre1 be used for PR tests? Thanks

**Comment by davidlange6** [comment]
> On Jul 4, 2017, at 4:33 PM, Marco Musich <notifications@github.com> wrote:
> 
> @arunhep, no - we need tests against a more release.
> @smuzaffar when will a release younger than CMSSW_9_3_0_pre1 be used for PR tests? Thanks

likely in a few hours.

**Comment by smuzaffar** [comment]
@mmusich , CMSSW_9_3_X_2017-07-04-1100 is still building (https://cmssdt.cern.ch/jenkins/job/build-any-ib/41586/) and hopefully should be available for PR tests in couple of hours.

**Comment by mmusich** [comment]
thanks @smuzaffar and @davidlange6. 
I suppose @arunhep can then re-trigger the tests later today / tomorrow.

**Comment by arunhep** [comment]
please test

**Comment by arunhep** [comment]
+1

**Pull request merged**
