### PR TITLE
bsunanda:Run2-alca7 Correct the destructors and a few constructors and a few python scripts ...

### PR DESCRIPTION
**Pull request by bsunanda**
Changes to satisfy some of the coding conventions and to match AlCa requirements for getting the right conditions

### CODE REVIEW

**Comment by bsunanda** [comment]
I rebased all the changes in previous PR (#8347) to CMSSW_7_5_X_2015-04-02-1100 and made this PR and I checked that it gives 0 errors for "runTheMatrix.py -s --useInput all"
________________________________

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by bsunanda** [comment]
Hi

I ran the following relvals using "runTheMatrix.py -s --useInput all"
1000.0_RunMinBias2011A+RunMinBias2011A+TIER0+SKIMD+HARVESTDfst2+ALCASPLIT
1001.0_RunMinBias2011A+RunMinBias2011A+TIER0EXP+ALCAEXP+ALCAHARVD
1330.0_ZMM_13+ZMM_13INPUT+DIGIUP15+RECOUP15+HARVESTUP15+MINIAODMCUP15
135.4_ZEE_13+ZEEFS_13+HARVESTUP15FS+MINIAODMCUP15FS
140.53_RunHI2011+RunHI2011+RECOHID11+HARVESTDHI
25.0_TTbar+TTbarINPUT+DIGI+RECO+HARVEST+ALCATT
4.22_RunCosmics2011A+RunCosmics2011A+RECOCOSD+ALCACOSD+SKIMCOSD+HARVESTDC
4.53_RunPhoton2012B+RunPhoton2012B+HLTD+RECODreHLT+HARVESTDreHLT+MINIAODDreHLT
5.1_TTbar+TTbarFS+HARVESTFS
8.0_BeamHalo+BeamHaloINPUT+DIGICOS+RECOCOS+ALCABH+HARVESTCOS
It gave
10 10 9 7 6 tests passed, 0 0 0 0 0 failed

I am surprised what command is to be used.

Sunanda

________________________________

**Comment by slava77** [comment]
Sunanda,

Which release did you use for testing?
Jenkins is using CMSSW_7_5_X_2015-04-02-1100 and it  fails in harvesting step 
```
%MSG-e FatalSystemSignal:  QualityTester:qTesterJet@endRun  03-Apr-2015 02:22:06 CEST End Run: 194533
A fatal system signal has occurred: segmentation violation
%MSG

```

Could you please check in this IB (CMSSW_7_5_X_2015-04-02-1100).
The command that you used should work.

**Comment by bsunanda** [comment]
I started with CMSSW_7_5_X_2015-04-02-1100 then added the following packages:
Calibration:
HcalAlCaRecoProducers  HcalCalibAlgos  HcalIsolatedTrackReco  IsolatedParticles

DQMOffline:
CalibCalo

DataFormats:
HcalIsolatedTrack

I did not check out the dependent codes. That may be the only difference. Let me try them out. But it is crashing in some harvesting job for tracker related AlCa step which I did not touch. Let me try this out.

Sunanda
________________________________

**Comment by bsunanda** [comment]
There were a few files which were not put in the PR before (an oversight). But these should not affect. I did now "git cms-checkdeps -a" and "scram b" and then run "runTheMatrix.py -s --useInput all" which gave me "10 10 9 7 6 tests passed, 0 0 0 0 0 failed"

________________________________

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by bsunanda** [comment]
Hi

I tried the following:

  cmsrel CMSSW_7_5_X_2015-04-02-1100
  cd CMSSW_7_5_X_2015-04-02-1100/src
  cmsenv
  cd ..
  mkdir relval
  cd relval/
  runTheMatrix.py -s --useInput all
---> 10 10 9 7 6 tests passed, 0 0 0 0 0 failed
  cd ..
  mkdir relval2
 cd src
 git cms-merge-topic 8649
 ls *
 scram b -j 10
 cd ../relval2
 runTheMatrix.py -s --useInput all
--> 10 10 9 7 6 tests passed, 0 0 0 0 0 failed
So without and with the pull request 8649, I got no error in running the matrix
________________________________

**Comment by bsunanda** [comment]
I did the test where the automatic test system had an issue. I could not reproduce the error. I tried it a few times and it was successful in all times.

**Comment by deguio** [comment]
I tested WF 4.53 in a recent pre-release (CMSSW_7_5_X_2015-04-05-2300) and it worked

**Comment by deguio** [comment]
+1

**Comment by slava77** [comment]
@cmsbuild please test
maybe the last error was a transient thing

**Comment by cvuosalo** [comment]
+1

For #8649 693ada34aa22b770038429df9ac5dd214a9d21da

This PR is a follow-up of previous PRs (#8131) to clean up some remaining issues, mostly to match AlCa requirements to get the right conditions. The Reco portion consists of very minor code clean-up.

The code changes are satisfactory, and Jenkins tests against baseline CMSSW_7_5_X_2015-04-08-2300 show no significant differences. The test for workflow 4.53_RunPhoton2012B erroneously shows differences in most quantities, but these results are due to a Jenkins problem seen today in other PRs.

**Comment by bsunanda** [comment]
Hi

I have rebased these codes twice before. I wonder why it takes such a long time to get this integrated - it is still waiting from AlCa and ORP. We need these code urgently to be backported to 7_4 so that we can do Hcal calibration work at Tier0.

Sunanda
________________________________

**Comment by mmusich** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
