### PR TITLE
add 2018 HI MC wf 150.0 to the short matrix

### PR DESCRIPTION
**Pull request by slava77**
One large mission for sw developments of 2018 is the preparation for HI data taking.
This PR is to add a 2018 HI MC test to the standard tests.

I thought that a heavier event may be a better choice, but then maybe we should instead have more lighter events instead.

### CODE REVIEW

**Comment by prebello** [comment]
please test

**Comment by prebello** [comment]
please test workflow 150.0

**Comment by slava77** [comment]
> please test workflow 150.0

the goal of the PR is to make jenkins run 150.0 by default.
So, this last test request defeats the purpose.

**Comment by prebello** [comment]
+1

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
@slava77 indeed the wf is run without explicitly invoking it

https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-22250/26160/runTheMatrix-results/150.0_HydjetQ_B12_5020GeV_2018+HydjetQ_B12_5020GeV_2018+DIGIHI2018+RECOHI2018+HARVESTHI2018/

@kpedro88 could you please check and sign or comment?

**Comment by kpedro88** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
