### PR TITLE
CSC RU builder widened roads and narrower anode time window switched to default

### PR DESCRIPTION
**Pull request by nvoytish**
#### PR description:
This is a PR that omitts the customisation files and confirable parameter used for validation of the proposed changes in https://github.com/cms-sw/cmssw/pull/25684 and https://github.com/cms-sw/cmssw/pull/17772

Related presentation can be found here https://indico.cern.ch/event/784929/contributions/3265299/attachments/1777781/2890942/19_01_11-Voytishin_Palichik-CSCSegBuilder_proposal_RECO_meeting.pdf
The results of the validation can be found here:
https://hypernews.cern.ch/HyperNews/CMS/get/muon-object-validation/1287/1.html

### CODE REVIEW

**Comment by nvoytish** [comment]
@ptcox, you might be interested

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by jpata** [comment]
@nvoytish I ran the workflow 136.875_RunDoubleMuon2018C+RunDoubleMuon2018C+HLTDR2_2018+RECODR2_2018reHLT_Offline+HARVEST2018 with 100 events and two configurations to validate that the migration from the customisation functions is complete (separately of the physics validation you have linked above).

- **reference**, adding the customization functions at the end of `step3_RAW2DIGI_L1Reco_RECO_EI_PAT_ALCA_DQM.py`:
```python
from RecoLocalMuon.CSCRecHitD.customRecHitBuilder import tightenAnodeTimes
from RecoLocalMuon.CSCSegment.customSegmentBuilder import widenRoads

process = tightenAnodeTimes(process)
process = widenRoads(process)

# Add early deletion of temporary data products to reduce peak memory need
from Configuration.StandardSequences.earlyDeleteSettings_cff import customiseEarlyDelete
process = customiseEarlyDelete(process)
```

- **new**, including this PR, not using any customization functions.

I observe don't observe any differences in the reco outputs that are monitored. The code changes also look OK to me. I will sign in a separate post.

**Comment by jpata** [comment]
+reconstruction
- removes customization functions from the muon code, new CSC configs are now enabled by default
- per https://github.com/cms-sw/cmssw/pull/32948#issuecomment-785040758, it looks like this is technically OK, no changes detected between the case of using the customization functions and this PR
- physics validation has been reported in the description, we expect more reconstructed muons, especially tracker and soft muons in data
- consequently, the reco outputs are expected to change in this PR (changes downstream from muons look minor)
- @cms-sw/operations-l2 this could be a good target for the next prerelease

**Comment by silviodonato** [comment]
+1
@cms-sw/pdmv-l2 the effect of this PR will be visible in the next pre-release campaign

**Pull request merged**
