### PR TITLE
[RFC] Test clang-tidy --checks performance-faster-string-find

### PR DESCRIPTION
**Pull request by fwyzard**
See the description at https://clang.llvm.org/extra/clang-tidy/checks/performance-faster-string-find.html .

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by Dr15Jones** [comment]
looks good to me.

**Comment by alja** [comment]
+1

**Comment by cvuosalo** [comment]
+1

**Comment by kpedro88** [comment]
@ianna @cvuosalo it looks like the unit test fails because it tries to run an executable from a different package: https://github.com/cms-sw/cmssw/tree/master/DetectorDescription/RegressionTest/test. Can the test be updated to work reliably, or otherwise removed?

**Comment by kpedro88** [comment]
+upgrade

**Comment by cvuosalo** [comment]
@kpedro88 I'll submit a PR to revise that test.

**Comment by cvuosalo** [comment]
@kpedro88 Unit test fix is in PR #29947.

**Comment by kpedro88** [comment]
thanks @cvuosalo !

**Comment by jfernan2** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by perrotta** [comment]
+reconstruction

**Comment by chayanit** [comment]
+1

**Comment by pohsun** [comment]
+1

**Comment by mommsen** [comment]
+1

**Comment by santocch** [comment]
+1

**Comment by mrodozov** [comment]
-note
keep it

**Comment by Martin-Grunewald** [comment]
+1

**Pull request closed without merging**
