### PR TITLE
Remove files that use non-existent config fragment MixingNoPileUp_cff

### PR DESCRIPTION
**Pull request by wmtan**
The config fragment Configuration/StandardSequences/MixingNoPileUp_cff was removed in January 2011, after release CMSSW_3_9_9.  It has been non-existent for more than four years, but there are still config files that use it even after I removed many obsolete config files in two previous pull requests.
This PR removes the remaining config files that use this fragment, because none of these files could have ever worked in CMSSW_4_0_0 or later.
I am doing this because I am working on a feature that needs to modify a lot of config files, and I don't want to waste time looking at long obsolete config files.
This removes another 5000 lines of code that has been non-functional for years.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by lveldere** [comment]
+1

**Comment by deguio** [comment]
+1

**Comment by wmtan** [comment]
@cmsbuild The build problem is in the base IB and has nothing to do with this PR.

**Pull request merged**
