### PR TITLE
[14_0_X] Updates for 2024 Wfs (PR Testing, IBs, Patatrack, inputs)

### PR DESCRIPTION
**Pull request by AdrianoDee**
This PR updates the wfs used in PR testing, IB test (standard and GPU).  It includes https://github.com/cms-sw/cmssw/commit/f77b3b3bd417e0ce73302d519b8ca1dfb8aa5078 from @mmusich. 

For the moment the 2023 wfs are kept as they are with the idea of reducing them later this year.

The default input GEN-SIM datasets for 2024 conditions are updated to `14_0_0_pre3` RelVals.

backport of https://github.com/cms-sw/cmssw/pull/44075

### CODE REVIEW

**Comment by AdrianoDee** [comment]
enable gpu

**Comment by AdrianoDee** [comment]
please test

**Comment by AdrianoDee** [comment]
backport of https://github.com/cms-sw/cmssw/pull/44075

**Comment by AdrianoDee** [comment]
please test

**Comment by AdrianoDee** [comment]
code-checks

**Comment by AdrianoDee** [comment]
please test

**Comment by AdrianoDee** [comment]
+pdmv

**Comment by srimanob** [comment]
+Upgrade

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
