### PR TITLE
Add more Phase2/Run3 GEN fragments and update with TuneCP5

### PR DESCRIPTION
**Pull request by chayanit**
#### PR description:
 
This PR is a replacement of PR #28932 due to slow progress and more clean up. 

PR includes

1. Updated generator fragments (e.g. TTbar, MinBias at 14TeV) with CP5 tune, intended to use for Phase2 and Run3 RelVal production in CMSSW release validation
2. Added new generator fragments needed for Phase2 RelVal production in CMSSW release validation
3. Added corresponding entries for 1) and 2) in the RelVa submission macros (upgradeWorkflowComponents.py, relval_steps.py)
4. MatrixInjector.py: wmsplit set to 1 for high PU RelVal submission for recent detector configurations (D35, D49 etc). It is needed to run highPU phase2 workflows smoothly in the computing system

#### PR validation:

Test locally with related workflows added : 

`runTheMatrix.py --what upgrade -l 23240.0,23234.0,23302.0,23303.0,23304.0,23305.0,23306.0,23307.0,23308.0,23309.0,23310.0,23311.0,23312.0,23313.0,23314.0,23315.0,23316.0,23317.0,23319.0,23261.0,23236.0,23250.0,23246.0,23252.0,23249.0,23251.0,23294.0,23295.0,23296.0,23297.0,23298.0,23299.0,23300.0,23301.0,23207.0,23208.0,23209.0,23287.0 -t 4 --command='--customise SLHCUpgradeSimulations/Configuration/aging.customise_aging_1000 -n 5' &>run5evt.log`

### CODE REVIEW

**Comment by chayanit** [comment]
please test workflow 23240.0,23234.0,23302.0,23303.0,23304.0,23305.0,23306.0,23307.0,23308.0,23309.0,23310.0,23311.0,23312.0,23313.0,23261.0,23236.0,23250.0,23246.0,23252.0,23249.0,23251.0,23316.0,23317.0,23318.0,23319.0,23315.0,23294.0,23295.0,23296.0,23297.0,23298.0,23299.0,23300.0,23301.0

**Comment by chayanit** [comment]
please test

**Comment by chayanit** [comment]
+1

**Comment by chayanit** [comment]
Hi @qliphy, @agrohsje, could you check and sign if no issue? Thanks in advance.

**Comment by kpedro88** [comment]
+upgrade

**Comment by agrohsje** [comment]
Hi @chayanit . You might want to consider  'SoftQCD:inelastic = on' (instead of the 3 separate specifications), for the minbias sample.
In CP5 we have SigmaTotal:zeroAXB=off, so different from previous min bias we can also consider SoftQCD:centralDiffractive.  You could do the same for tau->3mu if you want.

**Comment by chayanit** [comment]
> Hi @chayanit . You might want to consider 'SoftQCD:inelastic = on' (instead of the 3 separate specifications), for the minbias sample.
> In CP5 we have SigmaTotal:zeroAXB=off, so different from previous min bias we can also consider SoftQCD:centralDiffractive. You could do the same for tau->3mu if you want.

@agrohsje thanks! I have updated the fragments. Let me know if anything missing.

**Comment by chayanit** [comment]
please test

**Comment by chayanit** [comment]
+1

**Comment by chayanit** [comment]
@silviodonato just a kind reminder that I would like to have this PR merged before 11_1_0_pre4 arrives.

**Comment by agrohsje** [comment]
+1

**Comment by chayanit** [comment]
+1

**Comment by chayanit** [comment]
@kpedro88 could you please review and sign again? Thanks in advance.

**Comment by chayanit** [comment]
please test

**Comment by kpedro88** [comment]
+upgrade

**Comment by chayanit** [comment]
+1

**Comment by silviodonato** [comment]
merge
generators signed before the last commit @alberto-sanchez  @agrohsje @efeyazgan @mkirsano @qliphy @SiewYan

**Pull request merged**
