### PR TITLE
(13_0_X) streamer format padding backport

### PR DESCRIPTION
**Pull request by smorovic**
#### PR description:
Adding support for padding in the Streamer format. Padding bytes (0xff) can be appended after the end of each event or INIT message. Intention is to add them at the end of the file (4096-byte blocks) to round the file size so it is compatible with O_DIRECT copy from DAQ RUBUs to Lustre system in hope this will reduce deadtime issues seen recently.

Streamer Input sources will automatically detect padding which will (typically) be appended to streams transferred to Tier-0. Also an option was added to generate files which contain padding after each event or INI object.

Update: DQM and EcalCalibration unit tests were extended with the padded format test as well.

#### PR validation:
Unit tests added to generate and read padded streamer file. Patch tested with 13_1_X (PR #41125) with production streamer files without padding and padded files produced in a test system.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. =
Backport of #41125 for 13_0_X
Adding support for padded files for this release cycle so format can be used Online for the HLT output merging and parsed by Tier-0 and other streamer clients.

### CODE REVIEW

**Comment by smorovic** [comment]
please test

**Comment by francescobrivio** [comment]
backport of #41125

**Comment by francescobrivio** [comment]
@smorovic in the tests I see a failure in [HLT/SiStrips for wf 11634.911](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_13_0_X_2023-03-25-1100+e7589d/56255/11634.911_TTbar_14TeV+2021_DD4hep/HLT_SiStrip_ControlView.html). 
I don't think it's related to this PR, but I just wanted to check with you?

**Comment by smorovic** [comment]
I don't think this is related. I'm not familiar how this test is implemented, but I'd be surprised if it used streamer files in any way.

**Comment by francescobrivio** [comment]
+1

**Comment by emanueleusai** [comment]
+1

**Comment by perrotta** [comment]
+1
- Differences in the test scripts with respect to the ones merged in master are due to the updates in those test implemented centrally and independently from this PR in the master

**Pull request merged**
