### PR TITLE
Fc fix ecal al ca reco producer

### PR DESCRIPTION
**Pull request by fabiocos**
Replace FileInPath with string in the configuration built at compilation time to avoid problems with the build system (see #21955)

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by Dr15Jones** [comment]
I'm not very happy with this change since it takes away the purpose of FileInPath. We want more use of FileInPath to help with configurations, not less of them.

**Comment by fabiocos** [comment]
@Dr15Jones this is the only case that I see in which FileInPath is used in a dynamic build of a configuration. I agree this is undoing the good of FileInPath, but unless we want to modify the build procedure is to avoid to create dynamically the configuration. Or do you suggest other solutions?

**Comment by fabiocos** [comment]
No more needed after the fix of FilInPath in #21966

**Pull request closed without merging**
