### PR TITLE
Fixing horrible typo. Also add a Log message for force decay and clea…

### PR DESCRIPTION
**Pull request by alberto-sanchez**
…n when a decay is rejected

### CODE REVIEW

**Comment by covarell** [comment]
Of course this needs to be fixed, but is it at the origin of the observed problems with the current version of EvtGen? I do not think so, because the operate_on_particle functionality is almost never used. Can you do the tests on several B decay modes and update the commit later?

**Comment by alberto-sanchez** [comment]
@covarell. I have tested Bs/Bd -> mumu. As well as several b->J/psi decays and all seems consistent.
The original patch only affect the decays where a secondary decay is forced, like b->J/psi->mumu, since the problem was the re-decaying of the daughters. Decays like Bs/Bd->mumu should be unaffected. 
Forcing decays of several decays I get 
Bd 34 out of 50 
Bp 31 out of 50
Bs 13 out of 50
Lb  3 out of 50

forcing j/psi  2 out 100 e.g. just forcing j/psi->mumu, but forcing all B+/B0/Bs/Lb to decay to J/psi->mumu
(via all contributions of s and p states, e.g using incl_BtoJpsi_mumu.dec)
i got 100 out 100.

The interface force the decay of one particle per event. So, from this I would said the numbers are
consistent.

**Comment by covarell** [comment]
OK. I will approve this, please prepare also a backport for 71X

**Comment by covarell** [comment]
+1

**Comment by davidlange6** [comment]
@cmsbuild, please test

**Comment by davidlange6** [comment]
+1

**Pull request merged**
