### PR TITLE
removed assert

### PR DESCRIPTION
**Pull request by shervin86**
Assert on PIXEL FED removed. With the assert the code is crashing with new upgrade geometry

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by franzoni** [comment]
hanks @shervin86
Should the check rather be updated, instead of removed?

Some comments at the opening of a pr are always welcome 😀

**Comment by ghellwig** [comment]
@shervin86 
possible inspiration for an update instead of removal are here:
https://github.com/cms-sw/cmssw/blob/master/EventFilter/SiPixelRawToDigi/src/PixelUnpackingRegions.cc#L94-L108
https://github.com/cms-sw/cmssw/blob/master/EventFilter/SiPixelRawToDigi/src/PixelUnpackingRegions.cc#L138

**Comment by shervin86** [comment]
Dear Giovanni, I did not put any comment because I consider that removal of asserts should always be a good thing. In my modest opinion asserts can be only used at development stage, like in this case, but should be removed when put in production. This plugin has been used for 1 year as part of the AlCaElectron Stream run by the HLT and hence it's evident that the assert is completely useless. I suspect it was copied from some test analyzer of the tracker/pixel group and included in this pluging when developing.
Regards,

**Comment by shervin86** [comment]
@ghellwig I'm wondering why there are those asserts. Has ever the code crashed? Is it ever suppose to crash? Shouldn't those be at least exceptions?

**Comment by davidlange6** [comment]
hi all - is there some insight about why this has not caused a problem in the 2017 relvals? (eg, how should the relvals be altered to exercise this code?)

**Comment by silviodonato** [comment]
Hi David, SelectedElectronFEDListProducerGsf was used in the ALCAELECTRONOutput EndPath (see https://raw.githubusercontent.com/cms-sw/cmssw/CMSSW_8_4_X/HLTrigger/Configuration/test/OnLine_HLT_GRun.py).
As we don't run this special AlCa stream in RelVals we didn't get any error.

Please note that ALCAELECTRONOutput is in HLTrigger/Configuration/test/OnLine_HLT_GRun.py but not in HLTrigger/Configuration/python/HLT_GRun_cff.py (the latter is what is actually use in RelVals)

**Comment by davidlange6** [comment]
> On Mar 16, 2017, at 3:17 PM, Silvio Donato <notifications@github.com> wrote:
> 
> Hi David, SelectedElectronFEDListProducerGsf was used in the ALCAELECTRONOutput EndPath (see https://raw.githubusercontent.com/cms-sw/cmssw/CMSSW_8_4_X/HLTrigger/Configuration/test/OnLine_HLT_GRun.py).
> As we don't run this special AlCa stream in RelVals we didn't get any error.
> 
> Please note that ALCAELECTRONOutput is in HLTrigger/Configuration/test/OnLine_HLT_GRun.py but not in HLTrigger/Configuration/python/HLT_GRun_cff.py (the latter is what is actually use in RelVals)
> 

I would have expected OnLine_HLT_GRun to be running in add on tests. It looks like it is running ok.

https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc6_amd64_gcc530/CMSSW_9_1_X_2017-03-10-2300/addOnTests/logs/cmsDriver-hlt_mc_GRun_cmsRun__cvmfs_cms-ib.cern.ch_week0_slc6_amd64_gcc530_cms_cmssw-patch_CMSSW_9_1_X_2017-03-10-2300_src_HLTrigger_Configuration_test_OnLine_HLT_GRun.py_r.log

but maybe just running over enough events?

**Comment by Martin-Grunewald** [comment]
Well, we removed the offending path containing the failing module in the PR which updated the addOn tests to the 2017 era. Thus it is not triggered.

**Comment by davidlange6** [comment]
excellent - whats the plan for undoing that? Seems its an important module (or maybe it runs elsewhere too)

**Comment by Martin-Grunewald** [comment]
We'll put the path back once this PR (or any other), which addresses the problem, is integrated.
(We can not hold up everything else due to this assert).

**Comment by ghellwig** [comment]
> @ghellwig I'm wondering why there are those asserts. Has ever the code crashed? Is it ever suppose to crash? Shouldn't those be at least exceptions? 

@shervin86 I did not put the check there, but I can imagine that the author wanted to ensure correctness. Incorrect code can easily happen if different people modify code without knowing original intentions of legacy code.
Anyways, I think an exception would be fine with the added value of a cleaner exit of the program.
Or is this code time critical? It does not look like this.

**Comment by davidlange6** [comment]
ah got it.. thanks for the clarificaiton

**Comment by franzoni** [comment]
hello @shervin86 are you planning on taking @ghellwig 's [inspiration](https://github.com/cms-sw/cmssw/pull/17955#issuecomment-287049802) advice ?

**Comment by shervin86** [comment]
@franzoni, I have looked carefully at the suggestion, but I think there is no real reason for having an assert or any check of this kind.

**Comment by franzoni** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
