### PR TITLE
plugin for muon FSR recovery

### PR DESCRIPTION
**Pull request by NTrevisani**
#### PR description:

This plugin will be used to include in nanoAOD the relevant pieces of information needed to compute final state recovery, as currently implemented in the H->mumu analysis.
A pull request has been opened also on the dedicated cms-nanoAOD repository. In order to check the code formatting and quality, the c++ part of the pull request is additionaly presented on the cms-sw repository.

#### PR validation:

The plugin has been tested on nanoAOD production, together with related changes in the configuration files.

### CODE REVIEW

**Comment by peruzzim** [comment]
This should rather go in a MUO software area, not to PhysicsTools/NanoAOD.

**Comment by fabiocos** [comment]
@NTrevisani @peruzzim is there any clarification about this PR? I tend to agree with @peruzzim that this does not seem specifically a nanoAOD component. Furthermore I do not see a description of the module configuration

**Comment by fabiocos** [comment]
@NTrevisani any news?

**Comment by fabiocos** [comment]
@NTrevisani @arizzi @peruzzim this looks like superseded by #28118 , I believe we might close this PR, do you agree?

**Comment by peruzzim** [comment]
agreed, please close

**Pull request closed without merging**
