### PR TITLE
IsoPhotonEB skim (13_0_X)

### PR DESCRIPTION
**Pull request by lathomas**
#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport of https://github.com/cms-sw/cmssw/pull/42150

### CODE REVIEW

**Comment by perrotta** [comment]
backport of https://github.com/cms-sw/cmssw/pull/42150

**Comment by perrotta** [comment]
please test

**Comment by youyingli** [comment]
@cms-sw/pdmv-l2 , please test again

**Comment by perrotta** [comment]
please test

**Comment by youyingli** [comment]
@sunilUIET please sign

**Comment by sunilUIET** [comment]
+pdmv

**Comment by perrotta** [comment]
> * You potentially added 261 lines to the logs

(Please notice that in the previous tests of this PR the message was

> * You potentially removed 243 lines from the logs

)

Indeed, the LogMessages of wf 136.793_RunDoubleEG2017C are not reproduced exactly. For example, in the baseline there is
```
%MSG
%MSG-w BasicTrajectoryState:   ConversionTrackCandidateProducer:conversionTrackCandidates  10-Jul-2023 17:25:14 CEST Run: 301998 Event: 9374081
BasicTrajectoryState: attempt to access errors when none available  accessing local error..
freestate pointer: parameters
x =      -70.2412      8.01227     -140.869
p =     -0.232484     0.311155     -1.43099
no error defined.

local error valid/values :0
[  -9.9999e+14 1.59609e-09 1.42874e-19           0   -0.689964
   1.59609e-09 -5.8279e-17  0.00619125-2.45158e-18  6.953e-310
   1.42874e-19  0.00619125           0 6.01018e-21           0
             0-2.45158e-18 6.01018e-21-3.95124e-188  6.953e-310
     -0.689964  6.953e-310           0  6.953e-310  6.953e-310 ]
```

which is duplicated in these tests as

```
%MSG
%MSG-w BasicTrajectoryState:   ConversionTrackCandidateProducer:conversionTrackCandidates  10-Jul-2023 17:19:58 CEST Run: 301998 Event: 9374081
BasicTrajectoryState: attempt to access errors when none available  accessing local error..
freestate pointer: parameters
x =      -70.2412      8.01227     -140.869
p =     -0.232484     0.311155     -1.43099
no error defined.

local error valid/values :0
[  -9.9999e+14 1.59609e-09 1.42874e-19           0   -0.689964
   1.59609e-09 -5.8279e-17  0.00619125-2.45158e-186.95297e-310
   1.42874e-19  0.00619125           0 6.01018e-21           0
             0-2.45158e-18 6.01018e-214.50717e+2136.95297e-310
     -0.6899646.95297e-310           06.95297e-3106.95297e-310 ]
%MSG
%MSG-w BasicTrajectoryState:   ConversionTrackCandidateProducer:conversionTrackCandidates  10-Jul-2023 17:19:58 CEST Run: 301998 Event: 9374081
BasicTrajectoryState: attempt to access errors when none available  accessing local error..
freestate pointer: parameters
x =      -70.2412      8.01227     -140.869
p =     -0.232484     0.311155     -1.43099
no error defined.

local error valid/values :0
[  -9.9999e+14 1.59609e-09 1.42874e-19           0   -0.689964
   1.59609e-09 -5.8279e-17  0.00619125-2.45158e-186.95297e-310
   1.42874e-19  0.00619125           0 6.01018e-21           0
             0-2.45158e-18 6.01018e-214.50717e+2136.95297e-310
     -0.6899646.95297e-310           06.95297e-3106.95297e-310 ]
```

This is not present/visible in the 13_1_X and 13_2_X versions of this PR because that large amount of LogMessages from BasicTrajectoryStat do not show up any more.

Clearly this has nothing to do with this PR which can be merged nonetheless.
And whatever it is, it got fixed in newer releases that 13_0_X

**Comment by perrotta** [comment]
+1

**Pull request merged**
