### PR TITLE
FWCore/Framework: Add cmsRunGP which links against Google perftools profiler library.

### PR DESCRIPTION
**Pull request by gartung**
Requires https://github.com/cms-sw/cmsdist/pull/6854

### CODE REVIEW

**Comment by gartung** [comment]
please test with cms-sw/cmsdist#6854

**Comment by gartung** [comment]
abort

**Comment by gartung** [comment]
enable profiling

**Comment by gartung** [comment]
test parameters:
workflows_profiling=11834.21

**Comment by gartung** [comment]
please test

**Comment by smuzaffar** [comment]
enable profiling

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
+core

**Comment by qliphy** [comment]
+1

**Comment by mrodozov** [comment]
@gartung after some time fighting the libunwind lib dir on PPC I noticed it's excluded from the PPC arch
https://github.com/cms-sw/cmsdist/pull/5105
and so is igprof 
https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_12_0_X/master/cmssw-tool-conf.spec#L180
gperf requires it but since there is no toolfile to it there nothing in the path. so gperf will build, but then whatever else uses it or in this case cmssw piece that searches for symbols from this lib will fail
In case we can't use libunwind on PPC (probably was removed because of an issue) I'll have to wrap this binary build in a arch condition

**Pull request merged**
