### PR TITLE
Add 2023 Geometry Scenario Version

### PR DESCRIPTION
**Pull request by ianna**
* Try to avoid constant modification of the script with evolving 2023 geometry scenarios by adding a version (Dxxx) defined in dict2023Geometry.py

For example:
```
cmsRun Fireworks/Geometry/python/dumpSimGeometry_cfg.py tag=2023 version=D10
```

@kpedro88 - BTW, dict2023Geometry.py is out-of-date with available scenarios

### CODE REVIEW

**Comment by kpedro88** [comment]
@ianna please clarify?

**Comment by alja** [comment]
+1

**Comment by ianna** [comment]
@kpedro88 - when I run the following, I get an out-of-date 2023 dictionary:
```
cmsRun Fireworks/Geometry/python/dumpSimGeometry_cfg.py tag=2023
Loading configuration for scenario 2023  ...

Please, specify 2023 scenario version

[(('O1', 'T2', 'C1', 'M1', 'F1', 'I1'), 'D2'),
 (('O1', 'T3', 'C2', 'M1', 'F1', 'I1'), 'D4'),
 (('O1', 'T3', 'C1', 'M1', 'F1', 'I1'), 'D7'),
 (('O1', 'T3', 'C2', 'M1', 'F1', 'I2'), 'D8'),
 (('O1', 'T3', 'C1', 'M2', 'F1', 'I1'), 'D9')]
Usage: cmsRun dumpSimGeometry_cfg.py  tag=TAG version=VERSION 
   tag=tagname
       indentify geometry scenario 
       ['Run1', '2015', '2015dev', '2017', '2017Muon', '2019', '2023']

   version=versionNumber
       scenario version from 2023 dictionary:

   out=outputFileName
       default is cmsSimGeom<tag><version>.root

```

**Comment by kpedro88** [comment]
@ianna maybe you are in an old IB? https://github.com/cms-sw/cmssw/blob/CMSSW_9_0_X/Configuration/Geometry/scripts/dict2023Geometry.py is up to date.

**Comment by ianna** [comment]
@kpedro88 - surprisingly enough, if I check it out I see an up-to-date version, but do not get it at runtime.

**Comment by kpedro88** [comment]
@ianna I can reproduce this behavior merging your branch into the latest IB CMSSW_9_0_X_2016-12-19-1100.

To understand this problem, I used the following commands:
```
python
import dict2023Geometry
dict2023Geometry.__file__
'/cvmfs/cms-ib.cern.ch/2016-52/slc6_amd64_gcc530/cms/cmssw/CMSSW_9_0_X_2016-12-18-0000/bin/slc6_amd64_gcc530/dict2023Geometry.py'
```
The 12-18-0000 IB comes from before #16971 was merged, so I think this is the cause of the problem. @smuzaffar how do the patch builds handle updating this kind of python file? (I am concerned that `git cms-addpkg Configuration/Geometry` does not update the version of the file found by python. Maybe this is because it is in the `scripts` rather than `python` directory?)

**Comment by kpedro88** [comment]
I think there's no problem with moving the dict file into `Configuration/Geometry/python`. @ianna, can you do this (and update the import in `generate2023Geometry.py` if necessary)?

**Comment by ianna** [comment]
@davidlange6 - checking the package out did not make any difference. 
@kpedro88 - I'll move the scripts to python directory. However, it looks like there is a circular dependency between Configuration/StandardSequences and Configuration/Geometry due to these scripts and its unit test. I'll see if there is a better place for them - any suggestions?

**Comment by kpedro88** [comment]
@ianna I think generate2023Geometry can remain in the scripts directory, only dict2023Geometry needs to be moved. How does the circular dependency arise?

**Comment by ianna** [comment]
@davidlange6 - this PR is unrelated to the discussion where the scripts should resign. Please, merge it. Thanks.

**Pull request merged**
