### PR TITLE
Fixed typo in Mixing names

### PR DESCRIPTION
**Pull request by gsfs**

### CODE REVIEW

**Comment by fabiocos** [comment]
+operations

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
@smuzaffar There is a simple fix that I checked myself aside, is there a problem with the cms-bot machinery checks (which i doubt will see any difference)?

**Comment by smuzaffar** [comment]
Yesterday , jenkins test failed due to the jenkins server rebooted ( https://hypernews.cern.ch/HyperNews/CMS/get/sw-develtools/2533.html ). I have restarted the tests now

**Pull request merged**
