### PR TITLE
Updated flavor parton selection for Pythia8

### PR DESCRIPTION
**Pull request by ferencek**
This is a follow up to #10751, #11076, and #11501 where the hadron- and parton-based jet flavors were decoupled. This led to the realization that the parton selection for Pythia8 was not inclusive enough and in particular was failing to pick up some of the b and c quarks, resulting in spoiled b-tag performance curves in the b-tag DQM.

In addition, the selection of b and c quarks for MiniAOD was updated by dropping any selection based on the particle status code. The increase in the MiniAOD size resulting from this PR was tested by making MiniAOD from /RelValTTbar_13/CMSSW_7_6_0_pre5-76X_mcRun2_asymptotic_v1-v1/GEN-SIM-RECO and was found to be small (~0.9%).

**Update (Oct. 5, 2015):** More details in the following presentation https://indico.cern.ch/event/449888/contribution/5/attachments/1164881/1679186/FlavourValidation.pdf shown in the b-tag meeting on Oct. 5

### CODE REVIEW

**Comment by ferencek** [comment]
@monttj, could you please sign this PR. Thanks

**Comment by ferencek** [comment]
@monttj, @davidlange6 ping

**Comment by arizzi** [comment]
@davidlange6  why this was not integrated in 76X? did you already cut 760patch1 ?

**Comment by davidlange6** [comment]
> On Nov 10, 2015, at 9:43 AM, arizzi <notifications@github.com> wrote:
> 
> @davidlange6 why this was not integrated in 76X? did you already cut 760patch1 ?

lack of a AT group and that I had missed it - it would now be part of a patch1 (waiting on a GT)

**Comment by arizzi** [comment]
ok great

**Pull request merged**
