### PR TITLE
Update PPS HPTDC PCL for additional station

### PR DESCRIPTION
**Pull request by ChrisMisan**
#### PR description:
Remove conditions restricting PCL to one station.

#### PR validation:
wfs 1041,1044 

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

not a backport

### CODE REVIEW

**Comment by ChrisMisan** [comment]
type ctpps

**Comment by ChrisMisan** [comment]
test parameters:
- workflows=1041, 1044

**Comment by ChrisMisan** [comment]
please test

**Comment by tvami** [comment]
@ChrisMisan I'm confused to not see differences in 1041, 1044. Is that bc the input data only had one station enabled? If yes, is there any data that would be more relevant to be used in testing?

**Comment by ChrisMisan** [comment]
> @ChrisMisan I'm confused to not see differences in 1041, 1044. Is that bc the input data only had one station enabled? If yes, is there any data that would be more relevant to be used in testing?

We have input only for one station, this is the reason we can't see any changes in 1041 and 1044. At this point I don't think we have any suitabe data to do the test but I believe current wfs proved that this change didn't cause any difference in the one station workflow.

**Comment by tvami** [comment]
+alca
 * tests pass, no diffs, explonation here https://github.com/cms-sw/cmssw/pull/40696#issuecomment-1420598341

**Comment by perrotta** [comment]
+1

**Pull request merged**
