### PR TITLE
[ASAN] fix unit tests by setting NO_TEST_PREFIX flag for ASAN IB

### PR DESCRIPTION
**Pull request by iarspider**
#### PR description:

Attempt to fix failing unit tests in ASAN builds, similar to #36249 .

### CODE REVIEW

**Comment by iarspider** [comment]
please test for CMSSW_12_2_ASAN_X

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
please test for CMSSW_12_2_ASAN_X

**Comment by tvami** [comment]
Here https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-d85e64/21004/unitTests/src/CondCore/Utilities/test/testGetPayloadData/testing.log

I see "==21987==ASan runtime does not come first in initial library list; you should either link runtime to your application or manually preload it with LD_PRELOAD."

**Comment by iarspider** [comment]
@tvami I think this is an expected message

**Comment by tvami** [comment]
> @tvami I think this is an expected message

Ah ok, so we are good then, right?

**Comment by tvami** [comment]
+db
 * bugfix PR

**Comment by qliphy** [comment]
+1
unit test errors already in IB CMSSW_12_2_ASAN_X_2021-12-03-2300

**Comment by qliphy** [comment]
merge

**Pull request merged**
