### PR TITLE
Run3-gex126A Try to resolve compilation warnings in RecoParticleFlow/PFProducer

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Try to resolve compilation warnings in RecoParticleFlow/PFProducer

#### PR validation:

Use the runTheMatrix test workflows

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@jpata I came across this compilation warning while I was editing a Geometry package and did checkdeps and build. It is annoying to see compilation warning. So I fixed it so that the warning goes away. I did not bother to test its functionality. Just ran the standard tests which may or may not cover this. If you think these corrections are redundant I can delete those classes. But I thought it is safer to remove the warnings and let others decide about the future of these classes

**Comment by laurenhay** [comment]
When you say runTheMatrix tests do you mean:
`runTheMatrix.py -l limited -i all --ibeos`
or something custom? Do you have what the warnings were when compiling?
Like Joosep said I don't see anything actually calling these test classes other than the build file. Asking around now about whether they're deprecated.

**Comment by jpata** [comment]
@laurenhay did you get any feedback from the groups if this code is still used?

**Comment by laurenhay** [comment]
@jpata Yes I asked around and as far as anyone knows in PF it is not being used. We think it's safe to remove these from the repository (of course they'll still exist in version control in the event a user of the code materializes).

**Comment by hatakeyamak** [comment]
Just adding that I haven't seen these being used either.

**Comment by bsunanda** [comment]
@jpata @laurenhay @hatakeyamak So instead of fixing the two classes, let me then delete them in this PR. Hope you agree

**Comment by kdlong** [comment]
Agreed

**Comment by bsunanda** [comment]
@jpata @laurenhay @hatakeyamak Deleted the files from the repository. Hope this is OK. I shall do similar action on the files in #37400 - is it OK?

**Comment by bsunanda** [comment]
@cmsbuild Please check

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by jpata** [comment]
+reconstruction
- clean up unused test code in PF

**Comment by perrotta** [comment]
@bsunanda there are references of the removed modules in
- "PFEGCandidateTreeMaker" inside RecoParticleFlow/Configuration/test/RecoToDisplay_batch_cfg.py
- "PFEGammaCandidateChecker" inside RecoParticleFlow/PFProducer/test/particleFlowCandidateChecker_cfi.py

If the test code is removed, also its references in the two test config above must be cleaned from it

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by perrotta** [comment]
Thank you @bsunanda for having taken my [comment](https://github.com/cms-sw/cmssw/pull/37399#issuecomment-1099173017) into account.

However, I don't think that removing those two test config as a whole is correct here. Within a general cleaning of the PF test configs now in CMSSW those removals can be taken into account (and they would be also welcome, indeed). In the limited scope of this PR, originally meant just to remove only a few compilation warnings, I think that some more limited and dedicated cleaning should be preferred, instead

- "particleFlowCandidateChecker_cfi.py" is loaded inside RecoParticleFlow/Configuration/test/RecoToDisplay_NoTracking_cfg.py (and also cited in several other test configs, even if commented out). Instead of removing it as a whole, just remove the configuration for the `particleFlowEGammaCandidateChecker` in it

- "RecoToDisplay_batch_cfg.py" is not referenced anywhere else in CMSSW. Therefore, with the consensus of the PF contacts it could also removed as a whole. A safer way to proceed here that does not require any third party approval could be to remove just the configuration of `pfEGAlgoNewSCTree` in it, and its inclusion in the sequence `pfReReco` (L123)

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by jpata** [comment]
+reconstruction
- on top of https://github.com/cms-sw/cmssw/pull/37399#issuecomment-1099148655, some additional cleanup
- I'm not sure if `RecoToDisplay_*.py` are really used, so we'll engage the PF group to further clean up the test code in a follow-up

**Comment by jpata** [comment]
type pf

**Comment by perrotta** [comment]
+1

**Pull request merged**
