### PR TITLE
[14.1.X] Generalize warp size in pixel clustering kernel

### PR DESCRIPTION
**Pull request by AuroraPerego**
#### PR description:

In the `FindClus` kernel there was an assumption on the warp size being equal to 32, which is true for NVIDIA GPUs, but not always for AMD GPUs. Now the warp size is taken from the `__AMDGCN_WAVEFRONT_SIZE` macro for HIP and uses 32 for CUDA.
Note that `alpaka::warp::getSize(acc)` cannot be used because it's evaluated at runtime.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

backport of #46426 

FYI @fwyzard

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by mandrenguyen** [comment]
backport of https://github.com/cms-sw/cmssw/pull/46426

**Comment by mandrenguyen** [comment]
what's the motivation to backport this PR to 14_1_X?

**Comment by fwyzard** [comment]
We need it in 14.0.x to test and measure the performance of the HLT on AMD GPUs.

Usually when making a backport for a given release (_e.g._ 14.0), we were asked to make it also for the more recent release (so 14.1).

It might also be useful if we later decide to test the Heavy Ions HLT on AMD GPUs.

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
