### PR TITLE
add pixel and strip clusters vs good pv and lumi

### PR DESCRIPTION
**Pull request by mtosi**
add 4 new plots for monitoring pixel and strip clusters multiplicity vs PU and LUMI
it is useful for the HLT monitoring as well
@rovere @VinInn @fwyzard @JanFSchulte

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by dmitrijus** [comment]
+1

**Comment by Martin-Grunewald** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
