### PR TITLE
getPayloadData unit test, if no plugins are found, look in the `CMSSW_RELEASE_BASE`

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

Solves issue reported at https://github.com/cms-sw/cmssw/pull/34199#issuecomment-868960458

#### PR validation:

Run the unit test without compiling the package and found all the registered plugins in the release.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Not a backport, no backport is needed.

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
type bug-fix

**Comment by mmusich** [comment]
@cmsbuild please test

**Comment by mmusich** [comment]
urgent

**Comment by smuzaffar** [comment]
@silviodonato , @qliphy , I am merging this to fix the unit test for IBs. This should not break any thing else

**Pull request merged**
