### PR TITLE
DQM plots for jet triggers in lowPU runs

### PR DESCRIPTION
**Pull request by fruboes**
Configuratuion updated to have DQM plots for jet triggers in lowPU runs

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
ciao @fruboes 
the changes you submitted are triggering a number of errors in the logs. have a look at:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-8151/3248/DQMTestsResults/DQMTestsResults/3/p3.4.log

is there a way/don't you want to avoid that when the searched paths are not in the menu?
thanks,
F.

**Comment by fruboes** [comment]
Dear @deguio ,

 sure, no problem. Currently those messages are written to LogError. I will change this to lower level, not sure to which one though - is there any preference between LogDebug/LogInfo/LogWarning? Please let me know.

 BTW I expect to add another trigger path to our DQM today or tommorrow (depending if the root file with trigger results/products from path developer contains everything thats needed). I will reuse this branch/PR (along with LogError fix) in order to avoid unnecessary traffic

 cheers,
    Tomasz

**Comment by deguio** [comment]
-1
ok, then I am rejecting this for now. feel free to reuse this branch and update the PR.
btw. are these messages supposed to go away with the new HLT menu?
ciao,
F.

**Comment by fruboes** [comment]
Not sure actually. These paths are fow lowPU menu for May, so they would likely persist when running with standard one.

 Should I make a new PR then?

**Comment by fruboes** [comment]
Hi @deguio ,

 the output was changed from LogError to LogInfo which should suppress  the messages. I wasnt able to test it though, while runTheMatrix was crashing on some other error (my configuration didnt print any errors also previously). BTW the last DQM test results from the other PR (8152) seems to be done without that commit applied (error messages still from LogError)

 Thanks,
  Tomasz

**Comment by deguio** [comment]
+1

**Comment by fruboes** [comment]
Dears,

 sorry, if the last commit created some mess - I saw that this PR did not yet made into the release and assumed (perhaps wrongly) this was forgotten anyway. Last commit follows the changes in the trigger names, if this is problematic please let me know, I'll revert this branch to previuos state (if needed) and make another PR with new changes.

 Cheers,
  Tomasz

**Comment by degano** [comment]
please test

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
