### PR TITLE
set data processing bunch spacing configs to 50ns for HI

### PR DESCRIPTION
**Pull request by slava77**
- backport of #11576 to 75X
- force data processing setup for HI Run2 to 50 ns via bunch-spacing override [this is the important bug fix, the rest of the changes are mostly technical]
- use bunchSpacingProducer override for 50 ns for pp run2 data processing setup "50nsRunsAfter253000" aka ppRun2at50ns scenario
- add bunchSpacingProducer to the event content

The new pieces here will be propagated to 76X imminently.

Tests done in 7_5_4:
- short matrix: to check that backport of  bunchSpacingProducer code is done correctly (comparisons show no differences ==> OK)
- run2 2015B and 2015C (134.70\* and 134.80*) workflows to check that setup for these was correct already (comparisons show no differences ==> OK)
- T0 setup processing with ppRun2at50ns of 2015B run to confirm that overrides act correctly (comparisons show no differences ==> OK)
- T0 setup processing with HeavyIonsRun2 of 2015B run (50 ns) to confirm that overrides act correctly (comparisons show no differences ==> OK)
- T0 setup processing with HeavyIonsRun2 of 2015C run (25 ns) to confirm that there are changes in ecal hits and downstream objects (comparisons show  differences ==> OK)

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/12246	 b127331
- jenkins confirmed no changes (as observed in local tests)

**Comment by davidlange6** [comment]
Slava- to be clear, you are adding the bunchSpacingProducer not only to the output, but to the release. Should be fine..

**Comment by slava77** [comment]
@davidlange6 
I'm not sure if your comment is about this PR (75X) or what's not fully done in 76X.
If about this PR, I may be missing a point of the comment (yes, the bunchSpacingProducer code was not in this release; the change is beyond just DP config changes)

**Comment by davidlange6** [comment]
this PR - its adding the feature to 75x..

**Comment by civanch** [comment]
+1

**Comment by richard-cms** [comment]
@slava77 
@ttrk and I have a stupid question - where can we find RecoLuminosity.LumiProducer.bunchSpacingProducer_cfi ? It does not appear to exist, even though the master reconstruction cff imports it... : https://github.com/cms-sw/cmssw/blob/CMSSW_7_5_X/Configuration/StandardSequences/python/Reconstruction_cff.py#L4

We're trying to test this PR on PbPb data and we're getting errors related to that python file.

**Comment by slava77** [comment]
@richard-cms 
It's auto-generated
see  $CMSSW_RELEASE_BASE/cfipython/$SCRAM_ARCH/RecoLuminosity/LumiProducer/bunchSpacingProducer_cfi.py

**Comment by richard-cms** [comment]
@slava77 (please let me know if you'd like to discuss this via email or another place)

After some discussion with @matteosan1 and doing some checking ourselves, we really think that we would prefer to use the legacy Global ecal rechit reconstruction since we are not affected by OOT PU during PbPb running. We see that the configuration still exists here: https://github.com/cms-sw/cmssw/blob/CMSSW_7_5_X/RecoLocalCalo/EcalRecProducers/python/ecalGlobalUncalibRecHit_cfi.py

Can you describe the best way for us to use that method instead? Thanks as always for your assistance.

@yenjie @ttrk @dgulhan

**Pull request merged**
