### PR TITLE
HLT Tau DQM updated to stage2 L1

### PR DESCRIPTION
**Pull request by slehti**
Offline HLT Tau DQM updated to stage2 L1

### CODE REVIEW

**Comment by perrotta** [comment]
Please @slehti : prepare also a 80X backport of this PR

**Comment by slehti** [comment]
Backported to 80X, PR #14427

**Comment by perrotta** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Comment by dan131riley** [comment]
Hi @slehti 

This PR removed the initialization of HLTTauDQML1Plotter::l1JetMinEt_

-  l1JetMinEt_       = ps.getUntrackedParameter<double>("L1JetMinEt");

but that variable is still used, uninitialized:

https://github.com/cms-sw/cmssw/blob/CMSSW_8_1_X/DQMOffline/Trigger/src/HLTTauDQML1Plotter.cc#L65

which leads to a bunch of "use of uninitialised value" complaints from valgrind memcheck.  Please make a new PR that either initializes or removes l1JetMinEt_.  Thanks.

**Pull request merged**
