### PR TITLE
[14_0_X] [DQM DT] Changes to put back DT Noise plot in Online DQM

### PR DESCRIPTION
**Pull request by jfernan2**
#### PR description:

Verbatim backport of https://github.com/cms-sw/cmssw/pull/43569

### CODE REVIEW

**Comment by tjavaid** [comment]
backport of #43569

**Comment by tjavaid** [comment]
please test

**Comment by syuvivida** [comment]
Hi @jfernan2 
 Do you want to deploy this PR in 13_3_X (for CRAFT/CRUZET runs)? If yes, we also need a backport in 13_3_X.

**Comment by jfernan2** [comment]
Hi @syuvivida 
Thanks, I have created https://github.com/cms-sw/cmssw/pull/43938

**Comment by tjavaid** [comment]
+1

- spurious differences seen from unstable WF `12434.7` (open issue #39803 )

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
