### PR TITLE
FastSim: use fastsim era to define customs to mixing (part2), includes fix to L1 emulator

### PR DESCRIPTION
**Pull request by lveldere**
this takes #12403 one step further

Using the fastsim era, all fastsim modifications to the standard MC configurations for mixing and digitization are applied inside the standard configuration files.

In this process a bug in the fastsim configuration for the L1 emulator:
In the case of premixing, ConfigBuilder loaded the standard L1 emulator,
instead of the one dedicated to premixing.

### CODE REVIEW

**Comment by lveldere** [comment]
please test

**Comment by lveldere** [comment]
please test

**Comment by lveldere** [comment]
please test

**Comment by lveldere** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by mulhearn** [comment]
+1

**Pull request merged**
