### PR TITLE
rivet with lhe weights

### PR DESCRIPTION
**Pull request by perrozzi**
use different lhe weights stored in the input file

### CODE REVIEW

**Comment by bendavid** [comment]
+1

**Comment by davidlange6** [comment]
@cmsbuild, please test

**Comment by davidlange6** [comment]
+1

**Comment by jhgoh** [comment]
Could this be backported to 75X?

**Comment by perrozzi** [comment]
yes it shouldn't be too difficult. is there a standard procedure to start from this commit or shall I do it "by hand"?

**Comment by jhgoh** [comment]
@perrozzi git-cherry-pick will make life easier.

**Comment by perrozzi** [comment]
shall I use the branch CMSSW_7_5_X ?

**Comment by bendavid** [comment]
yes

**Comment by perrozzi** [comment]
done

**Pull request merged**
