### PR TITLE
CosmicRateAnalyzer Updates: added PIXEL Hit Rate + improved Plots layout 

### PR DESCRIPTION
**Pull request by saumyaphor4252**
##### PR Description #####

Updated the Cosmic Rate Analyzer:
1) added Cosmic Hit Rate by PIXEL layers evaluation: 
       a) plugins/CosmicRateAnalyzer.cc
       b) macros/CosmicRateTool_PIXEL_HitRates.C
2) Improved the layout of output plots (labels, titles, marker size, frame)
       a) macros/CosmicRateTool_Kinematics.C
       b) macros/CosmicRateTool_CosmicRates.C
3) Updated the paths in 
       a) scripts/runPlotter.sh 
       b) scripts/runListId.sh

### CODE REVIEW

**Comment by mmusich** [comment]
@saumyaphor4252 thanks for this.
Can you apply the mandatory code-format as explained in https://github.com/cms-sw/cmssw/pull/34345#issuecomment-874525453 ? 
You can run `scram b code-format` in your local checkout and then push the resulting changes.

**Comment by mmusich** [comment]
@cmsbuild please test

I am expecting them to fail though, because of https://github.com/cms-sw/cmssw/issues/34223

**Comment by tvami** [comment]
@cmsbuild, please test with #34363

**Comment by qliphy** [comment]
please test

**Comment by tvami** [comment]
+alca

**Comment by qliphy** [comment]
+1

**Pull request merged**
