### PR TITLE
CPPFDigis emulator V2 @maseguracern

### PR DESCRIPTION
**Pull request by maseguracern**
@camilocarrillo @abrinke1
This is the first version of the CPPF emulator. we use the RPC Digitization and
reconstruction as intermedate steps.
Under test you can find two examples, one unpacking 2017F RAW Data (cppf_emulator_RAW.py)
and another one using generated MC events (cppf_emulator_MC.py).
The output of the unpacker is an edm branch named emulatorCppfDigis, following
the CPPFDigi dataformat already committed in CMSSW_10_1_X.

### CODE REVIEW

**Comment by abrinke1** [comment]
Hi @maseguracern , @camilocarrillo ,
From the meeting, I thought that you now only use RPCDigis as inputs to the emulator.  But I see now that you also use the RPCRecHit collection.  Even if it is only an intermediate step, this is improper for an emulator - reconstructed objects belong in the offline sequences, not online.  The RPCDigi object has all the information you need for a complete emulation of the CPPFDigi.  Please let me know if I'm missing something, or if there's a good reason the RPCRecHits should be there - otherwise they should be removed.
Best regards, Andrew

**Comment by camilocarrillo** [comment]
Hi @abrinke1,
You are right the RPCRecHitProducer is added to the sequence just as a temporary safe shortcut to produce the clusterization and the transformation of coordinates. This later would have to be replaced for the emulation of the clusterization done in CPPF. Let me suggest to go ahead with the emulator as it is. In this way, we could make progress in parallel in the CPPF commissioning and DQM development. All this should be transparent when the replacement of the clusterization is done. 
Cheers
Camilo

**Comment by thomreis** [comment]
please test

**Comment by abrinke1** [comment]
Hi @camilocarrillo ,
Thanks for the response.  This sounds like a good plan, as long as it does not get forgotten.  Also, be aware that major updates to emulators in CMSSW often come with extra scrutiny, as we found with EMTF :)
Cheers, Andrew

**Comment by rekovic** [comment]
+1

**Comment by fabiocos** [comment]
@maseguracern @rekovic I understand that this new package does not affect for the time being any central workflow, but it has been tested successfully in standalone with the test configuration provided here. Am I correct?

**Comment by fabiocos** [comment]
@maseguracern @rekovic sorry I would like to move forward here: at the moment this emulator is running only in the test configuration provided, which I assume has been tested, am I correct?

**Comment by fabiocos** [comment]
+1

**Pull request merged**
