### PR TITLE
TkAl validation - automatically read APEs from the MillePede output if present

### PR DESCRIPTION
**Pull request by hroskes**
The APEs are not aligned in MP.  They are just set to the input values.  This helps us use consistent APEs in alignment and validation.

It's still possible to load one component individually.

@connorpa 

This doesn't affect any workflows except our internal validations, and the purpose is just for convenience.  We've already used it in the config for the most recent set of plots:
https://indico.cern.ch/event/688851/#27-rerecoabcd

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by mrodozov** [comment]
please test

**Comment by pohsun** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
