### PR TITLE
Avoid including `RooNLLVar.h` in CMSSW

### PR DESCRIPTION
**Pull request by guitargeek**
The direct inclusion of the `RooNLLVar.h` header will soon result in a warning with ROOT `master`.

Users will be encouraged to always use `RooAbsPdf::createNLL()` instead of instantiating the NLL-representing objects themselves.

Fortunately, the `RooNLLVar` was not used directly in CMSSW, so I'll suggest to get rid of some spurious includes now such that we don't get warnings in the ROOT `master` build soon.

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by guitargeek** [comment]
> @cmsbuild can you please review it and eventually sign? Thanks.

It looks like the `analysis` area has no code owner anymore :(

**Comment by perrotta** [comment]
+1

**Comment by perrotta** [comment]
merge

**Pull request merged**
