### PR TITLE
Bugfix after "Adapting MVAVariableHelper to new E/gamma UL format and removal of MultiToken"

### PR DESCRIPTION
**Pull request by guitargeek**
#### PR description:

PR https://github.com/cms-sw/cmssw/pull/26814 caused some workflows in the IB to crash, see issue https://github.com/cms-sw/cmssw/issues/27219.

There was a usage of the `photonIDValueMapProducer` which was not tested in the bot tests and that requires the gedPhotons collection instead of the slimmedPhotons, which I made the new default instead of auto-detecting the right collection:

https://github.com/cms-sw/cmssw/blob/master/DQMOffline/Trigger/python/HLTEGTnPMonitor_cfi.py#L992

I propose to just fix it in the same way as the `egmPhotonIDs` were treated a few lines below: cloning the object and then resetting the input collection. This  should  be the safest way, as I can't run the matrix tests due to not being able to access the necessary files right now...

__Note:__ needs to be tested with workflows 136.7801, 136.7803, 1040.0 explicitly, as these are the ones that were crashing and they are not covered by the limited matrix tests performed by the bot.

#### PR validation:

```
python  DQMOffline/Trigger/python/EgammaMonitoring_cff.py
```

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by guitargeek** [comment]
Hi @jfernan2, sorry I forgot to mention this originally, but it seems the standard bot tests don't cover the crashing workflows. I wrote more in the PR description now. So please can you test the 3 crashing workflows after the standard tests are done? Thank you!

**Comment by jfernan2** [comment]
please abort

**Comment by jfernan2** [comment]
please test workflow 136.7801,136.7803,1040.0

**Comment by jfernan2** [comment]
@guitargeek slimmedPhotons are not available:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-2e8516/981/runTheMatrix-results/136.7801_RunHLTPhy2017B_AOD+RunHLTPhy2017B_AOD+DQMHLTonAOD_2017+HARVESTDQMHLTonAOD_2017/step2_RunHLTPhy2017B_AOD+RunHLTPhy2017B_AOD+DQMHLTonAOD_2017+HARVESTDQMHLTonAOD_2017.log
I suggest testing your PR off-topic, you should be able to do it yourself with this kind of commands:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-2e8516/981/runTheMatrix-results/136.7801_RunHLTPhy2017B_AOD+RunHLTPhy2017B_AOD+DQMHLTonAOD_2017+HARVESTDQMHLTonAOD_2017/cmdLog

**Comment by guitargeek** [comment]
Yep I will do that now, I was a bit overconfident that this commit here would fix it already. I will test locally and push anew when my solution works locally.

**Comment by guitargeek** [comment]
Okay with this update it works now locally. I was mislead by the line `egmPhotonIDsForDQM.physicsObjectSrc == cms.InputTag('gedPhotons')` in the existing code which I copy pasted, but it actually does not seem to work. For `egmPhotonIDsForDQM` that was not a problem because the default collection was `gedPhotons` anyway. I figured out that I need to pass the parameters I want to change directly in the `clone()` method.

**Comment by jfernan2** [comment]
please test workflow 136.7801,136.7803,1040.0

**Comment by fabiocos** [comment]
@jfernan2 according to the test this PR looks to solve the failures in the IB. Do you have comments? Or may we move forward with it?

**Comment by jfernan2** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
