### PR TITLE
Revert Phase1 conversion configuration files

### PR DESCRIPTION
**Pull request by makortel**
This PR reverts the changes in the Phase1 conversion configuration files done in #7794. The aim was primarily to restore the format of the files to what they are in 62X_SLHC for e.g. easier git diffing, but it revealed also some unintended changes in the conversion configuration that are undone in this PR. For the record, the changes were (introduced in #7794, reverted here)
- Seeding layers
  - Pixel TTRH was changed from `TTRHBuilderWithoutAngle4PixelPairs` to `WithTrackAngle`
  - Strip cluster charge cut was enabled
- `convStepTracks` TTRH was changed from `WithTrackAngle` to `WithAngleAndTemplate`
- `photonConvTrajSeedFromSingleLeg`
  - Maximum numbers for clusters were changed
  - `RegionFactoryPSet.RegionPSet.ptMin` was changed from 0.3 to 0.2

@rovere @VinInn @boudoul @venturia

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by civanch** [comment]
+1

**Comment by cvuosalo** [comment]
+1

For #8096 d0dee1442a59e577a10479536108bc9cc9b6d353

This PR reverts unintended changes introduced in #7794 related to Pixel Phase 1 and tracking.

The reverted code looks correct. Jenkins tests show no significant differences, and matrix tests against baseline CMSSW_7_5_X_2015-03-04-0200 also show no significant differences, indicating that the reversion appears  not to have introduced any new problems in reconstruction.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
