### PR TITLE
NanoAOD developments, 29Nov2018 version [102X]

### PR DESCRIPTION
**Pull request by peruzzim**
This pull request contains the latest set of NanoAOD developments.
The content of virtually all physics objects has changed.

The only change outside PhysicsTools/NanoAOD is setting a dedicated sequence name when running NanoAOD on FastSim.

The following combinations of era modifiers should be used:
`--era Run2_2016,run2_miniAOD_80XLegacy`: for 2016 80X data (07Aug17) and RunIISummer16MiniAODv2 MC
`--era Run2_2016,run2_nanoAOD_94X2016`: for 2016 94X data (17Jul2018) and RunIISummer16MiniAODv3 MC
`--era Run2_2017,run2_nanoAOD_94XMiniAODv1`: for 2017 94X MiniAODv1 samples
`--era Run2_2017,run2_nanoAOD_94XMiniAODv2`: for 2017 94X MiniAODv2 samples (including 31Mar2018 data)
`--era Run2_2018,run2_nanoAOD_102Xv1`: for all 2018 10XY samples

### CODE REVIEW

**Comment by peruzzim** [comment]
The corresponding version of this pull request for the master branch is coming.

Should the tests in runtests.sh be updated to check all supported datasets, as listed above?
Currently they only test 94X V1 and V2.

**Comment by fabiocos** [comment]
please test

**Comment by peruzzim** [comment]
@fabiocos please see the note above on the needed testing environment in 10_2_X

**Comment by peruzzim** [comment]
@cmsbuild please test with #25347 cms-sw/cmsdist#4518

let me give it a try (#25347 has already been tested so I assume there is no problem in doing this)

**Comment by peruzzim** [comment]
backport of #25373

**Comment by peruzzim** [comment]
It's difficult to interpret the differences as they also include the effect of #25347 (or equivalent functionality as in #25372) that changes the content of photon ID, but it seems consistent with expectation (differences appearing in WF 1325.7).

**Comment by peruzzim** [comment]
should be tested again as soon as #25372 is merged

**Comment by peruzzim** [comment]
please test with #25372 cms-sw/cmsdist#4518

updated to address #25409 by backporting #25423

**Comment by peruzzim** [comment]
will rebase once #25372 is merged

**Comment by prebello** [comment]
@fabiocos  shall PdmV approve it even with rebasing needs?

**Comment by peruzzim** [comment]
I expressed myself imprecisely, I will merge 10_2_X here fixing the conflict

**Comment by peruzzim** [comment]
The PR has been updated to store the new ecalBadCalibFilter bit, and corrected in EGM IDs and scales&smearings.
The merging conflict with #25372 is not yet fixed, it will be when that PR is merged.
No further modifications are expected.

Depends on #25372 and #25459.

**Comment by fabiocos** [comment]
@peruzzim you may now rebase this PR

**Comment by peruzzim** [comment]
please test with cms-sw/cmsdist#4518

Merged CMSSW_10_2_X fixing a minor conflict, will test with external needed for #25372 (not sure if really needed).

**Comment by fabiocos** [comment]
+operations

the change to ConfigBuilder is consistent with the master version

**Comment by fabiocos** [comment]
@peruzzim @fgolf is it really worthwhile to keep this infinite list of commits in the history, or could this be squashed into the final result?

**Comment by fabiocos** [comment]
@kpedro88 there is nothing upgrade specific, but please have a look and sign ti in case

@prebello @zhenhu the PyReleaseValidation part is the backport of #25423 , I would like to integrate it to get ready for NanoAOD production release

**Comment by peruzzim** [comment]
@fabiocos we actually need the commit history to cleanly merge back in the other repository where other developments are ongoing already, please don't squash

**Comment by peruzzim** [comment]
For the future we will try to squash in blocks  each PR during integration, if this can help

**Comment by fabiocos** [comment]
please abort

**Comment by fabiocos** [comment]
please test workflow 1325.6,1325.7,1325.8,1329.1,136.7722,136.7952,136.8521 with #25368

**Comment by fabiocos** [comment]
please abort

wrong tag

**Comment by fabiocos** [comment]
please test workflow 1325.6,1325.7,1325.8,1329.1,136.7722,136.7952,136.8521 with #25372

**Comment by fabiocos** [comment]
+1

nanoAOD tests successful in master
@prebello @zhenhu @kpedro88 please sign it at your earliest convenience for reference

**Comment by kpedro88** [comment]
> You potentially added 56366 lines to the logs

Is this a real problem, or spurious?

**Comment by prebello** [comment]
+1

**Pull request merged**
