### PR TITLE
Report CPU time spent in child processes of ExternalLHEProducer

### PR DESCRIPTION
**Pull request by Dr15Jones**
When accounting for CPU time used by a cmsRun job, we need to also include the CPU time of the child processes launched by ExternalLHEProducer.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by perrozzi** [comment]
+1

**Comment by fabiocos** [comment]
@Dr15Jones this will enter in the regular TimingService report?

**Comment by fabiocos** [comment]
+1

**Comment by Dr15Jones** [comment]
@fabiocos it gets summed into the normal CPU report plus in the log it will also be shown as a separate item.

**Pull request merged**
