### PR TITLE
Update the TTTrack_TrackWord DataFormat

### PR DESCRIPTION
**Pull request by aperloff**
#### PR description:

This PR will update the TTTrack and TTTrack_TrackWord classes to correspond to the latest definitions in the corresponding [Phase 2 L1Trigger interface document](https://www.overleaf.com/read/ddsnkprgjmnp). The specifications have been agreed upon by the track trigger and the L1Trigger project leads. 

#### PR validation:

After forming a branch with just the changes we want (see backport specifications for more details), the ability to compile the code was checked by doing:
```bash
cmsrel CMSSW_12_0_X_2021-07-19-1100
cd CMSSW_12_0_X_2021-07-19-1100/src
cmsenv
git-cms-init
git-cms-checkout-topic aperloff:CMSSW_12_0_X-TrackWordUpdate
scram b -j 8
```

I also re-ran the code checks and code format checks using:
```bash
scram build code-checks
scram build code-format
```

To confirm that the code runs I used:
```bash
scram b runtests
runTheMatrix.py -l limited -i all --ibeos
```

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

These changes were previously integrated into the cms-l1t-offline fork of CMSSW and are being ported over to this repo. This PR includes portions of https://github.com/cms-l1t-offline/cmssw/pull/896 and https://github.com/cms-l1t-offline/cmssw/pull/902. The backport was created manually due to the complexity of the Git history in cms-l1t-offline.

@tomalin @skinnari @emacdonald16 @rekovic @cecilecaillol

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by aperloff** [comment]
Sorry @jfernan2 I was encouraged to update some of the comments in a private email. The only changes were to some comments, no code has changed. Could you please trigger the tests again?

**Comment by cecilecaillol** [comment]
please test

**Comment by cecilecaillol** [comment]
+l1

**Comment by jfernan2** [comment]
@aperloff I see changes in EGammaV folder, I do not know if they are expected from the inclusion of TrackingTools/TrajectoryState in DQMOffline/EGamma/plugins/BuildFile.xml  or to TTTrack changes itself. Is it understood?
https://tinyurl.com/yzzq3ny9
https://tinyurl.com/yzbhj4tw
The changes in the  cms-l1t-offline repos only inlcude DataFormats packages so I don't know if the EGamma change is needed
Thanks

**Comment by tvami** [comment]
+alca

**Comment by aperloff** [comment]
> @aperloff I see changes in EGammaV folder, I do not know if they are expected from the inclusion of TrackingTools/TrajectoryState in DQMOffline/EGamma/plugins/BuildFile.xml or to TTTrack changes itself. Is it understood?
> https://tinyurl.com/yzzq3ny9
> https://tinyurl.com/yzbhj4tw
> The changes in the cms-l1t-offline repos only inlcude DataFormats packages so I don't know if the EGamma change is needed

Hi @jfernan2, none of the changes I made should affect anything outside of the TTTracks. I don't know why you're seeing these differences. The change to the BuildFiles.xml outside of DataFormats/L1TrackTrigger were needed in order to compile after running `git-cms-checkdeps -a`. From what I can tell, the changes to the BuildFiles should have been there before, but because these packages were only linking to CMSSW libraries they were able to get away without the lines I've added. Now that they link to an external package (`hls`), even in a very roundabout fashion, the linking needs to be correct. At least, that is how it was explained to me.

**Comment by Martin-Grunewald** [comment]
+1

**Comment by jfernan2** [comment]
Well, indeed the changes are not present in every workflow. For example they appear in 11634.9* but not in 11634.0

https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_0_X_2021-07-19-1100+188356/44233/dqm-histo-comparison-summary.html

so DD4hep Geom may be involved...

wf 25202.0 has only changes in EG and not in Tracking.
They are all small changes though

**Comment by aperloff** [comment]
> so DD4hep Geom may be involved...

@jfernan2 I'm not sure what to do at this point. I have no experience with DD4hep or DQM tools. None of my changes should have affected any EGamma objects or anything outside of the track trigger. What should be done next?

**Comment by jfernan2** [comment]
@aperloff could you try to perform your validation without the line in DQMOffline/EGamma/plugins/BuildFile.xml ? I am still confused why this line is needed in your PR since you are not modifying directly TrackingTools/TrajectoryState, are you? It is the only link to EG in this PR, so I have no other clue

@nancymarinelli  as EG DQM expert, could you please comment?

**Comment by nancymarinelli** [comment]
I am not responsible of this PR. Who submitted it ?
PLease take into account that in DQMOffline/EGamma there are bits of 
software who look specifically at electrons. Maybe they need the 
TrackingTools. And since a long time I do not know who's taking care of 
those bits of code

On 26/07/21 10:15, jfernan2 wrote:
> @aperloff could you try to perform your validation without the line in DQMOffline/EGamma/plugins/BuildFile.xml ? I am still confused why this line is needed in your PR since you are not modifying directly TrackingTools/TrajectoryState, are you? It is the only link to EG in this PR, so I have no other clue
>
> @nancymarinelli  as EG DQM expert, could you please comment?
>
>

-- 
________________________________________
Nancy Marinelli
Research Professor
University of Notre Dame, IN, US
CERN, Bdg 40/3-A01, 1211 Geneva
SWITZERLAND
Phone +41-22-76-70809
fax +41-22-76-78940

**Comment by jfernan2** [comment]
@nancymarinelli according to https://twiki.cern.ch/twiki/bin/viewauth/CMS/DQMContacts#E_Gamma
you are the only EG DQM developer, who can know about the code then?
Thanks

**Comment by nancymarinelli** [comment]
I am the developer for Photons. I have not made any update recently,
and least of all of the TTTrack mentioned in the subject of this email.
Who submitted the PR 34550 mentioned in the subject ?


________________________________________
Nancy Marinelli
Research Professor
University of Notre Dame, IN, US
CERN, Bdg 40/3-A01, 1211 Geneva
SWITZERLAND
Phone +41-22-76-70809
fax +41-22-76-78940

**Comment by jfernan2** [comment]
Alexx Perloff, please go to github to see the full thread:
https://github.com/cms-sw/cmssw/pull/34550

**Comment by aperloff** [comment]
@nancymarinelli , I submitted the PR 34550.
@jfernan2 , the code will not compile without that line. The recipe to replicate that is:
```bash
cmsrel CMSSW_12_0_X_2021-07-19-1100
cd CMSSW_12_0_X_2021-07-19-1100/src
cmsenv
git-cms-init
git-cms-checkout-topic aperloff:CMSSW_12_0_X-TrackWordUpdate #this will checkout ~106 packages
<remove the line from DQMOffline/EGamma/plugins/BuildFile.xml>
scram b -j 8
```
I just tried it, again. Without that line you get the error:
```
In file included from /uscms_data/d2/aperloff/YOURWORKINGAREA/GTT/slc7/tmp3/CMSSW_12_0_X_2021-07-19-1100/src/DataFormats/L1TrackTrigger/interface/TTTrack.h:18,
                 from /uscms_data/d2/aperloff/YOURWORKINGAREA/GTT/slc7/tmp3/CMSSW_12_0_X_2021-07-19-1100/src/TrackingTools/TrajectoryState/interface/TrajectoryStateTransform.h:6,
                 from /uscms_data/d2/aperloff/YOURWORKINGAREA/GTT/slc7/tmp3/CMSSW_12_0_X_2021-07-19-1100/src/DQMOffline/EGamma/plugins/ElectronAnalyzer.h:8,
                 from /uscms_data/d2/aperloff/YOURWORKINGAREA/GTT/slc7/tmp3/CMSSW_12_0_X_2021-07-19-1100/src/DQMOffline/EGamma/plugins/ElectronAnalyzer.cc:1:
/uscms_data/d2/aperloff/YOURWORKINGAREA/GTT/slc7/tmp3/CMSSW_12_0_X_2021-07-19-1100/src/DataFormats/L1TrackTrigger/interface/TTTrack_TrackWord.h:19:10: fatal error: ap_int.h: No such file or directory
   19 | #include <ap_int.h>
      |          ^~~~~~~~~~
compilation terminated.
```
With the new line in the BuildFile.xml that error goes away.

I'm sorry, but clearly that line should have always been there, before my PR. I'm no expert in library linking, but there are headers in `DQMOffline/EGamma` which include headers from the `TrackingTools/TrajectoryState` package. That means there should have been a corresponding line in the `BuildFile.xml`. I don't know why people were able to get away with not having that line until now.

**Comment by kpedro88** [comment]
please test
(just to confirm these changes are real, since there were some IB issues last week)

**Comment by kpedro88** [comment]
@smuzaffar is the IB broken? the bot says it's a DAS error, but actually looking at the relval output shows a crash at the beginning of step 2:
```
A fatal system signal has occurred: external termination request
The following is the call stack containing the origin of the signal.



Waiting for stacktrace completion failed: timed out waiting for GDB to complete.

Current Modules:

Module: none (crashed)

A fatal system signal has occurred: external termination request
```

**Comment by smuzaffar** [comment]
@kpedro88 , no bot does not say that it is DAS error. It just run an extra relval test for making sure inputs are available. step1 of all of these tests passed and it failed on step2. Looks like a network/EOS glictch to me. I am restarting the RelVal-INPUT test for this PR now

**Comment by smuzaffar** [comment]
@kpedro88 , issue is related to #34633 . For Relval-INPUT tests we timeout the job after 15mins and looks like these failed wf are taking more than 15 mins to start and then killed by timeout

**Comment by aperloff** [comment]
@jfernan2 are you still seeing the differences that worried you before? All of the plots look really close to me, but I'm not really sure what I'm supposed to look for.

**Comment by jfernan2** [comment]
@aperloff most of the changes are gone now in the last test :-|
Only wf 4.53 and 23234.0 present tiny changes in photons... so it is weird.
Since you have created #34639 (thanks!!), if you don't mind, let's see what the results bring there

**Comment by jfernan2** [comment]
+1
As discussed on https://github.com/cms-sw/cmssw/pull/34639

**Comment by srimanob** [comment]
+Upgrade

This PR is to update the definition of TTTrack and TTTrack_TrackWord as agreed with offline L1T. PR runs fine, and in addition, the PR test is discussed in https://github.com/cms-sw/cmssw/pull/34639 on an issue with include(s).

**Comment by qliphy** [comment]
+1

**Pull request merged**
