### PR TITLE
Fix for conddb edit tool

### PR DESCRIPTION
**Pull request by ggovi**
In this PR:
- IOV schema fixed in the sqlalchemy model to remove the payload hash from the primary keys
- edit tag fixed to support sqlite manipulations

### CODE REVIEW

**Comment by ggovi** [comment]
please test

**Comment by mmusich** [comment]
Ciao Giacomo, @ggovi.

```
cmsrel CMSSW_9_0_X_2017-02-10-1100
cd CMSSW_9_0_X_2017-02-10-1100/src/
cmsenv
git cms-merge-topic 17486
scramv1 b -j 8
conddb_import -c sqlite_file:SiStripBadComponents_FailureScenario_PS1.db -f frontier://FrontierProd/CMS_CONDITIONS -i SiStripBadComponents_FailureScenario_PS1 -t SiStripBadComponents_FailureScenario_PS1
conddb --force --db SiStripBadComponents_FailureScenario_PS1.db edit --type tag SiStripBadComponents_FailureScenario_PS1
[2017-02-10 16:34:08,147] INFO: Connecting to SiStripBadComponents_FailureScenario_PS1.db [sqlite:///SiStripBadComponents_FailureScenario_PS1.db]
   Since  Insertion Time              Payload                                   
   -----  --------------------------  ----------------------------------------  
-  1      2017-02-10 15:32:49.506626  6ba6116331f89962932db238c4f354e1963b6b55  
+  100    2017-02-10 15:32:49.506626  6ba6116331f89962932db238c4f354e1963b6b55  

Confirm changes? [n] y
Please provide an editing note:  change the IOV from 1 to 100
```

results in:

```
[2017-02-10 16:34:24,159] ERROR: (exceptions.TypeError) SQLite DateTime type only accepts Python datetime and date objects as input. [SQL: u'SELECT "IOV".insertion_time AS "IOV_insertion_time", "IOV".tag_name AS "IOV_tag_name", "IOV".since AS "IOV_since", "IOV".payload_hash AS "IOV_payload_hash" \nFROM "IOV" \nWHERE "IOV".insertion_time = ? AND "IOV".tag_name = ? AND "IOV".since = ?'] [parameters: [{'%(139804670777616 param)s': 1, '%(139804670777552 param)s': 'SiStripBadComponents_FailureScenario_PS1', '%(139804670366032 param)s': datetime.datetime(2017, 2, 10, 15, 32, 49, 506626)}]]
```

**Comment by ggovi** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
