### PR TITLE
Fix a memory leak in DQMGenericClient

### PR DESCRIPTION
**Pull request by dmitrijus**
Fixes https://its.cern.ch/jira/browse/CMSCOMPPR-1606

### CODE REVIEW

**Comment by dmitrijus** [comment]
please test with 10024.0

**Comment by dmitrijus** [comment]
please test with workflow 10024.0

**Comment by dmitrijus** [comment]
please test workflow 10024.0

**Comment by fabozzi** [comment]
@dmitrijus 
Can you please make a backport also for 92X? Recent relvals for HLT in 9_2_14 were affected by the harvesting failure as well

**Comment by dmitrijus** [comment]
+1

**Comment by dmitrijus** [comment]
I will, I was just waiting for the tests to finish.

**Comment by davidlange6** [comment]
merge

**Pull request merged**
