### PR TITLE
Move DTDriftTimeParameters.icc

### PR DESCRIPTION
**Pull request by davidlange6**
move .icc into interface as its used by other packages. Move from nearly empty package into DT package. Adjust BuildFiles accordingly.

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by slava77** [comment]
@cmsbuild please test

it seems like the last attempt got stuck

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/33049	d02de12
- technical
- jenkins tests pass without differences (ignoring the repeatedly non-reproducible DD4HEP workflow results 11634.911)

**Comment by civanch** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
