### PR TITLE
Remove unused variable in SiPixelModuleStatus

### PR DESCRIPTION
**Pull request by Dr15Jones**

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
The AddOnTests failures are not from this pull request and are seen, periodically, in the IB RelVal tests

```
----- Begin Fatal Exception 17-Apr-2018 17:02:15 CEST-----------------------
An exception of category 'fastsim::ParticleManager' occurred while
   [0] Processing  Event run: 1 lumi: 1 event: 61 stream: 2
   [1] Running path 'simulation_step'
   [2] Calling method for module FastSimProducer/'fastSimProducer'
Exception Message:
unknown pdg id: 9010221
----- End Fatal Exception -------------------------------------------------
```

**Comment by Dr15Jones** [comment]
please test

**Comment by fabiocos** [comment]
@arunhep @lpernie this  just fixes a warning recently introduced by an unused variable, could you please sign?

**Comment by arunhep** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
