### PR TITLE
Pcc_event_producer_11_1_x_2020_02_18_1100

### PR DESCRIPTION
**Pull request by samhiggie**
PR description:
Continuation of PR #28807 https://github.com/cms-sw/cmssw/pull/28807
and rebase of PR #28980 https://github.com/cms-sw/cmssw/pull/28980 - will close after verification 

Changed some of the names of the producers to match the nomenclature by most modules in cmssw.

Added a fillDescription method so that the new AlCaPCCEventProducer may be added to the HLT configuration

Removed a PSet formatting  

PR validation:
Compiles and Runs with local test files and HLT configuration like:
hltGetConfiguration /users/sharper/2019/alca/alcaLumi --setup /dev/CMSSW_10_6_0/GRun/V3 --globaltag auto:run2_hlt_GRun --unprescale > hlt.py
(must replace AlcaPCCProducer with AlcaPCCEventProducer)
FastReport Info:

FastReport CPU time sched. / depend. Real time sched. / depend. Alloc. sched. / depend. Dealloc. sched. / depend. Processes and Paths
FastReport 3.4 ms 3.4 ms 6.3 ms 6.3 ms +3333 kB +3333 kB -3081 kB -3081 kB Alca_LumiPixelsCounts_ZeroBias_v1
FastReport 0.0 ms 0.0 ms 0.1 ms 0.1 ms +0 kB +0 kB +0 kB +0 kB Alca_LumiPixelsCounts_Random_v1

### CODE REVIEW

**Comment by slava77** [comment]
-1

due to merge conflicts

**Comment by samhiggie** [comment]
Greetings @slava77 , can you please be more specific? 
I needed to update the classes_def.xml for a successful build. 
For the AlcaPCCProducerEvent: I changed the naming scheme to match what current producer are called "XXXProducer" so I named it AlcaPCCEventProducer. In addition, I removed a useless cms Parameter Set from the module. 
I'm happy to address other issues.

**Comment by slava77** [comment]
> Greetings @slava77 , can you please be more specific?

I mean the status of this PR is unmergeable, as can be seen at the bottom of the page, screen-shot is below

Screen Shot 2020-02-20 at 4 44 19 AM

http://cms-sw.github.io/tutorial-resolve-conflicts.html or eve a web search for "git resolve merge conflicts" can help

**Comment by silviodonato** [comment]
Please open a new PR using a branch based on a more recent release

**Comment by samhiggie** [comment]
Greetings @silviodonato, I just did a re-base to a more recent release(from 11_1_X to 11_1_X_2020_02_18_1100 ) at your request https://github.com/cms-sw/cmssw/pull/28980#issuecomment-587510933. 
If this isn't the right version, can you please tell me which version I should make the PR to?

**Comment by samhiggie** [comment]
Hello, @silviodonato and @slava77. Do I need to rebase? or try a new release? or is this fine? 

I haven't done a rebase in a while. If I need to do so, could you provide the branch you'd like me to rebase to? 

As mentioned previously, the merge conflicts are producer names and class versions in the buildfile.xml. Every works locally just fine. Please let me know how this can be resolved. Thank you.

**Comment by slava77** [comment]
Based on https://github.com/cms-sw/cmssw/compare/master...samhiggie:PCCEventProducer_11_1_X_2020-02-18-1100?expand=1, you can see that this is still not mergeable.

rebase instructions are available in http://cms-sw.github.io/tutorial-resolve-conflicts.html 
(you may even try to skip to "I need a quick recipe" if the intro material seems too long)

**Comment by samhiggie** [comment]
Hello @slava77 , I've successfully rebased on #29069 

This was frustrating though, as all the commits that I had posted I needed to go through and many contained changes that were not necessary or I changed in order to forget them. In the future, is there a way I can just drop commits that are useless so I don't need to go through each one?
OR  if the state of the branch is in good condition is it possible to just sign off on the conflicts? 

Cheers,
Thanks

**Pull request closed without merging**
