### PR TITLE
Unpacker and DataFormat for L1 Trigger Scouting BMTF source

### PR DESCRIPTION
**Pull request by Mmiglio**
#### PR description:

This PR introduces the unpacker and data format needed to process muon stubs collected with the L1 Scouting system from the BMTF Trigger processors. 

New test file have been added to cms-data in this PR:
* https://github.com/cms-data/DataFormats-L1Scouting/pull/3

#### PR validation:

PR unpacker has been validated with data collected at p5 with the L1 scouting system, running in local, and comparing data results with L1 Trigger objects reconstructed starting from the cdaq Raw data

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

To be discussed: We would like this PR to be backported in a data-taking release in order to collect data from pp collisions during 2024.

### CODE REVIEW

**Comment by smorovic** [comment]
@cmsbuild please test with https://github.com/cms-data/DataFormats-L1Scouting/pull/3

**Comment by smorovic** [comment]
please test

**Comment by smorovic** [comment]
@cmsbuild abort tests

**Comment by smorovic** [comment]
@cmsbuild abort test

**Comment by smorovic** [comment]
@cmsbuild please abort

**Comment by smorovic** [comment]
@cmsbuild please test with https://github.com/cms-data/DataFormats-L1Scouting/pull/3

**Comment by dinyar** [comment]
Adding @aloeliger and @epalencia for the L1T. This would be good to have in a backport for P5 so we can take data from the BMTF. Matteo mentioned he will join the L1T OffSW meeting today to discuss the next steps in more detail if needed.

**Comment by smorovic** [comment]
+1

**Comment by antoniovilela** [comment]
https://github.com/cms-data/DataFormats-L1Scouting/pull/3 merged.
cmsdist tag PR: https://github.com/cms-sw/cmsdist/pull/9260

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
