### PR TITLE
bsunanda:Phase2-hgx66 Extend virtual wafer to valid list of DetIds

### PR DESCRIPTION
**Pull request by bsunanda**
This is a step toward having the complete cells in the reconstruction step.

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by ianna** [comment]
+1

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/16419 3f96ac8
- reco is minimally affected: only in RecoLocalCalo/HGCalRecProducers/test/testHGCalRecoLocal_cfg.py
- jenkins tests pass and comparisons show no differences, including the tested 2023 workflows

**Comment by bsunanda** [comment]
@rekovic @mulhearn Please approve this. There is only a small correction in the BuildFile in one L1 package.

**Pull request merged**
