### PR TITLE
Bring HLT Phase2 simplified timing menu variant up to date.

### PR DESCRIPTION
**Pull request by rovere**
#### PR description:

Sibling of #44025 to circumvent the bot's caching limits.

Tests with this PR alone will fail. This PR should always be tested together with its sister #44025.

#### PR validation:

See #44025

### CODE REVIEW

**Comment by rovere** [comment]
@cmsbuild please test with #44025

**Comment by rovere** [comment]
* The failure seems to be independent from this PR.
* All plots/variables referring to `hfprereco`, `hfreco`, and `horeco` are responsible for differences since those collections have been renamed with `hlt` in front, trying to adopt the same convention everywhere in the menu.
* The differences in `triggerResults` are difficult to judge/understand.

**Comment by mmusich** [comment]
test parameters:
   * pull_request = https://github.com/cms-sw/cmssw/pull/44025

**Comment by rovere** [comment]
@mmusich I'm not sure what the effect or your last command to the bot should be ...?

**Comment by mmusich** [comment]
>  I'm not sure what the effect or your last command to the bot should be ...?

none, but if we re-test, we don't need to specify "with 44025".

**Comment by rovere** [comment]
@cmsbuild please test

**Comment by mmusich** [comment]
@cmsbuild, please test
    * to refresh comparisons (spurious differences coming from https://github.com/cms-sw/cmssw/pull/44025 should be gone now).

**Comment by mmusich** [comment]
+hlt

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
