### PR TITLE
Add track-to-track monitoring of HLT GSF electron tracks with respect to offline

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

Title says it all, supports track-to-track monitoring of HLT GSF electron tracks with respect to offline for both Run 3 (`hltEgammaGsfTracks`) and Phase 2 (`hltEgammaGsfTracksL1Seeded`).
In addition:
   * add  regular GSF tracking monitoring at HLT also in Phase-2;
   * fix a bug in the vertex collection used for `egmTrackingMonHLT`

#### PR validation:

Run successfully both  `runTheMatrix.py -l 13034.0 -t 4 -j 8` (Run 3) and `runTheMatrix.py -l 24834.0 -t 4 -j 8 ` (Phase 2) and observed the corresponding monitoring elements filled.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Not a backport, but it will be backported to CMSSW_14_0_X for data-taking purposes.

### CODE REVIEW

**Comment by mmusich** [comment]
cc:

@RSalvatico @swagata87

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by swagata87** [comment]
type egamma, tracking

**Comment by mmusich** [comment]
@cms-sw/dqm-l2 this PR has been sitting idle for a week. Can you clarify plans for review and integration?
Thank you.

**Comment by tjavaid** [comment]
+1

**Comment by mmusich** [comment]
@cms-sw/orp-l2 is there is anything outstanding with this PR, can it be merged?
We'd like to have the backport (https://github.com/cms-sw/cmssw/pull/44917) at Tier0 soon for HLT monitoring purposes.

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
