### PR TITLE
Fix off by 1 error in Multi5x5ClusterAlgo

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

This fixes an off by one error introduced in #46756

#### PR validation:

Added printout of Clusters in the changed module both before and after #46756 and found differences with hits in cluster. With this change the printouts now match the results of before the PR.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
@makortel FYI

**Comment by Dr15Jones** [comment]
differences are expected

**Comment by Dr15Jones** [comment]
type bugfix

**Comment by jfernan2** [comment]
+1

**Comment by makortel** [comment]
Since https://github.com/cms-sw/cmssw/pull/46756 was merged in 14_2_X (just before branching off 15_0_X or something),  this PR needs to be backported to 14_2_X.

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
