### PR TITLE
Add code/configs for monitoring the new HLT_Photon35_TwoProngs35_v* paths

### PR DESCRIPTION
**Pull request by covarell**
Tested in CMSSW_10_2_0_pre5.
@ndaci @pellicci @heppye @davignon @mtosi

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by covarell** [comment]
please test

**Comment by heppye** [comment]
Dear STEAM@nadir, Dear DQM@Dmitrijus, here is a gentle reminder for you further attention to this pending PR. As this is the only DQM for a new pilot trigger path, we would like to push the integration of this PR asap. Many thanks, Ye for HIG.

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
@jfernan2 @dmitrijus is this addition ok to be integrated?

**Comment by dmitrijus** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
