### PR TITLE
Dedicated data members for Run-3 CSC trigger primitives

### PR DESCRIPTION
**Pull request by dildick**
#### PR description:

In previous PRs (#29456, #29205, #32880) I defined the Run-3 CSC TP formats based on a detector note DN-20-016. In the CLCT and LCT I extended the definition of existing data members with bit masks and bit shifts. It was pointed out to me that although this method is economical, it does not prevent data formats from being misinterpreted, should the bit masks or shifts change in the future. CMSSW would not record changes in bit masks and shifts as changes in the data formats, as opposed to changes in data members. 

Bottom line: 1/4-strip bit, 1/8-strip bit, Run-3 pattern and slope now have corresponding data members in CLCT and LCT. In-time bits and out-of-time bits are separated in the CSCShowerDigi.

#### PR validation:

Tested with WF 11634.0. There should be no changes in any workflow.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by dildick** [comment]
@jiafulow Do you know why compilation of the test module is not working? `CSCCorrelatedLCTDigi::getPattern() const` is defined and returns `pattern`.

**Comment by dildick** [comment]
With the addition of ```<use name="DataFormats/CSCDigi"/>``` the XML environment for the unit tests, they seem to compile fine for me. @civanch want to give it another try?

**Comment by civanch** [comment]
please test

**Comment by dildick** [comment]
@jiafulow @eyigitba Can you help solve this issue with the EMTF unit tests?

**Comment by eyigitba** [comment]
@dildick , I don't know why adding `<use name="DataFormats/CSCDigi"/>` fixed the issue for you. I didn't think that it would be necessary to add that line.

The compilation error points to `libL1TriggerL1TMuon.so` so maybe it's something to do with `L1Trigger/L1TMuon` and not EMTF. 

Maybe @jiafulow will have more insight.

**Comment by jiafulow** [comment]
Sorry for the late response. As Efe pointed out, the error was thrown by `libL1TriggerL1TMuon.so` and the reason EMTF showed up was because the tests were run on these four packages: DataFormats/CSCDigi, DataFormats/L1CSCTrackFinder, L1Trigger/CSCTriggerPrimitives, L1Trigger/L1TMuonEndCap . The EMTF tests do not actually use `CSCCorrelatedLCTDigi::getPattern()`. I suspect other packages that have a dependency on L1Trigger/L1TMuon would also fail if tested.

**Comment by dildick** [comment]
Ok. I'll revert the last commit. But I'm not sure what needs to be done to fix this.

**Comment by dildick** [comment]
@civanch The single commit compiles just fine with `CMSSW_12_0_X_2021-05-17-1100`. Do you know what is going on?

**Comment by civanch** [comment]
Should PR be tested after the last commit?

**Comment by dildick** [comment]
No. It will not compile as before. But maybe  you know what to do about it before we test again.

**Comment by civanch** [comment]
Is it OK that L1TriggerL1TMuon depends on CSCCorrelatedLCTDigi ? I am not familiar with L1 code but naively think that this is a problem. If I am wrong and this dependence is OK, then the dependence should be added to the Build file.

**Comment by dildick** [comment]
There is an internal data object https://github.com/cms-sw/cmssw/blob/master/L1Trigger/L1TMuon/interface/MuonTriggerPrimitive.h that depends on the CSCCorrelatedLCTDigi.

**Comment by jiafulow** [comment]
From the [build.log](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-24836c/15123/build.log):

```
...
>> Entering Package DataFormats/CSCDigi
>> Entering Package DataFormats/L1CSCTrackFinder
>> Entering Package DataFormats/HLTReco
>> Entering Package DataFormats/L1TCorrelator
>> Entering Package DataFormats/L1TMuon
>> Entering Package L1Trigger/CSCTriggerPrimitives
>> Entering Package L1Trigger/L1TMuonEndCap
>> Entering Package L1Trigger/CSCTrackFinder
>> Entering Package L1Trigger/DTTrackFinder
>> Entering Package L1Trigger/HardwareValidation
>> Entering Package L1Trigger/L1TMuonBarrel
>> Entering Package L1Trigger/L1TMuonCPPF
>> Entering Package L1Trigger/L1TMuonOverlap
>> Entering Package L1Trigger/L1TNtuples
...
```

Somehow, L1Trigger/L1TMuon was not re-built, but almost everything else that depends on DataFormats/L1TMuon, which depends on DataFormats/CSCDigi, were re-built. I'm not sure why.

**Comment by dildick** [comment]
@civanch Perhaps before we change a buildfile we should find out why `L1Trigger/L1TMuon` was not built in the first place.

**Comment by dildick** [comment]
This should check out and build the package ```L1Trigger/L1TMuon```

**Comment by dildick** [comment]
@cecilecaillol Can you restart the tests, please?

**Comment by cecilecaillol** [comment]
please test

**Comment by dildick** [comment]
Several workflows from messagelogger. Looking into the logs,

Screen Shot 2021-05-19 at 3 26 46 PM

it appears I need to extend the constructor to instantiate the Run-3 variables too. This message appears in several workflows. There is no bug in the emulator; slope just needs to be instantiated to 0 for all CLCTs and LCTs.

```
%MSG-e LCTQualityControl:   CSCTriggerPrimitivesProducer:simCscTriggerPrimitiveDigis  19-May-2021 19:14:02 CEST Run: 1 Event: 10
CSCCLCTDigi with invalid slope: 14840; allowed [-10, 10]
%MSG
```

I'll fix that at once.

**Comment by cecilecaillol** [comment]
+l1

**Comment by dildick** [comment]
This should do it. Runs with WF 11634.0
```
11634.0_TTbar_14TeV+2021+TTbar_14TeV_TuneCP5_GenSim+Digi+Reco+HARVEST+ALCA Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Thu May 20 10:33:50 2021-date Thu May 20 10:05:04 2021; exit: 0 0 0 0 0
1 1 1 1 1 tests passed, 0 0 0 0 0 failed
```
And I don't see any logwarnings in step 2.

@barvic This commit should also fix the crash we observed when running on B904 data https://github.com/cms-sw/cmssw/pull/33727/commits/b5b66e3c871ead91f96eafc1f21948747b6656b3

**Comment by civanch** [comment]
please test

**Comment by dildick** [comment]
```
scram b runtests
****WARNING: Invalid tool py2-sympy. Please fix professor2 file.
>> Local Products Rules ..... started
>> Local Products Rules ..... done
>> Entering Package EventFilter/CSCRawToDigi
>> Creating project symlinks
>> Entering Package DataFormats/L1CSCTrackFinder
>> Entering Package DataFormats/CSCDigi
>> Leaving Package EventFilter/CSCRawToDigi
>> Package EventFilter/CSCRawToDigi built
Creating test log file logs/slc7_amd64_gcc900/testing.log
Package EventFilter/CSCRawToDigi: Running test cscRawToDigiTest
 
===== Test "cscRawToDigiTest" ====

---> test cscRawToDigiTest succeeded
 
^^^^ End Test cscRawToDigiTest ^^^^
>> Tests for package EventFilter/CSCRawToDigi ran.
```

**Comment by dildick** [comment]
@civanch Can you restart the tests, please?

**Comment by civanch** [comment]
please test

**Comment by dildick** [comment]
Only 1 failed comparison, from pixel in WF 8.0.

@civanch @cecilecaillol Can you sign, please?

**Comment by civanch** [comment]
+1

**Comment by dildick** [comment]
@cecilecaillol Can this be merged as well?

**Comment by cecilecaillol** [comment]
+l1

**Comment by dildick** [comment]
@qliphy Can this PR be merged? Thanks.

**Comment by qliphy** [comment]
+1

**Pull request merged**
