### PR TITLE
Final cleanup of new muon validation

### PR DESCRIPTION
**Pull request by abbiendi**
This is the final cleanup for the new muon track validation.
It removes the code duplication and promotes the new code and configurations to default, while the old ones are deleted.

The next RelVals shall be compared with the special RelVals produced in CMSSW_10_0_0 to avoid discontinuity. For the same reason this PR should enter in time for the next round of RelVals production.

Obviously large differences are expected on the direct comparison of the new validation plots w.r.t. the old versions, due to the different setting of the parameters. This has been already tested and reported in:
https://indico.cern.ch/event/693825/contributions/2846510/attachments/1582881/2501491/NewMuonValidation.pdf

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by abbiendi** [comment]
In case anybody is willing to see results of the new validation vs the old one, I have been producing a lot of them in the last few days.

Comparisons using the special RelVals produced in CMSSW_10_0_0 vs the current (old) validation, 

for FullSim:
https://cms-muonpog.web.cern.ch/cms-muonpog/test_NewValidation/plots_FullSim-2018-CMSSW_10_0_0_NewVal_vs_OldVal/

for FastSim and HIN:
https://cms-muonpog.web.cern.ch/cms-muonpog/test_NewValidation/plots_FastSim-HI-CMSSW_10_0_0_NewVal_vs_OldVal/

Given that 10_0_0 is a development release (and muon HLT has an obvious problem) one can see results for a stable release by going back to validation plots obtained in CMSSW_9_4_0, from private RelVals:
https://cms-muonpog.web.cern.ch/cms-muonpog/test_NewValidation/plots_CMSSW_9_4_0_NewVal_vs_OldVal/

There are also other comparisons obtained with the New muon validation, of 10_0_0 with 9_4_0, for FullSim:
https://cms-muonpog.web.cern.ch/cms-muonpog/test_NewValidation/plots_FullSim-2017-NewVal_CMSSW_10_0_0_vs_CMSSW_9_4_0/

and FastSim and HIN:
https://cms-muonpog.web.cern.ch/cms-muonpog/test_NewValidation/plots_FastSim-HI-NewVal_CMSSW_10_0_0_vs_CMSSW_9_4_0/

finally 2018 vs 2017 in 10_0_0:
https://cms-muonpog.web.cern.ch/cms-muonpog/test_NewValidation/plots_FullSim-NewVal-CMSSW_10_0_0_2018_vs_2017/

Obviously the results of this PR have been tested w.r.t. the customized validation and they give as expected the exactly same outputs. 
Hence everything has been validated from the point of view of the validation code.

Since all this is a lot of work I hope it will converge soon, to avoid having to repeat it at yet another release. Also we need to avoid holes in the standard validation of the Muon POG, which is now guaranteed to proceed smoothly.
Thanks to the PPD (in particular to Francesco and Nadeesha) for having taken care of the many special RelVals that were necessary.

**Comment by perrotta** [comment]
+1
- This is mostly DQM, reco only marginally affected
- Anyhow I verified that this PR replaces exactly the "default" muon validation stuffs with what is called with the prefix "New" in the current code. The "New" classes and configs which were in the release are therefore removed here, so that the muon validation when this PR will be merged will be the "New" one (already tested in the current pre-release). This is indeed the expected behavior for this PR

**Comment by fabiocos** [comment]
@dmitrijus @jfernan2 could you please check? This is the conclusion of a migration discussed at length, it would be good if we can get it in pre1

**Comment by parbol** [comment]
In the Muon POG we are strongly interested in getting this PR integrated in pre1. The motivation is simple: for pre1 we have requested special samples to do the validation that won't be produced again. If we miss pre1 we won't be able to validate the release afterwards. Giovanni has done an extensive validation and comparison (see links in this comment) and we are reasonably sure that no major issues are present. So in conclusion, we would really like to push for not missing pre1.

Please let me know in case you have any question or comments.

Thank you very much,

**Comment by jfernan2** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
