### PR TITLE
fix eta range plots for pixel Phase1

### PR DESCRIPTION
**Pull request by mtosi**
bug-fix

### CODE REVIEW

**Comment by mtosi** [comment]
during recent condition validation, 
I realized there are some tracking plots vs eta which have the wrong range (still phase0)
for instance : [https://goo.gl/nnX1Qv](https://goo.gl/nnX1Qv)

**Comment by mtosi** [comment]
@cmsbuild, please test

**Comment by mtosi** [comment]
@davidlange6, @slava77, @fabiocos why I do not see the "bug fix" tag in the list ?

**Comment by andrius-k** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
