### PR TITLE
Cummulative 80X PRs for 81X: (#13558 #13572 #13588 #13596 #13602 #13607 #13621)

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
Cummulative PRs for 81X: 
This PR contains the 80X PRs (#13558 #13572 #13588 #13596 #13602 #13607 #13621)
but for 81X so that they get integrated here first and then their 80X counterparts can be
integrated in 80X.

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by mulhearn** [comment]
+1

**Comment by mmusich** [comment]
+1

**Pull request merged**
