### PR TITLE
modernize `MuonAnalysis/MomentumScaleCalibration`

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

Part of the migration in #31061 and https://github.com/cms-sw/cmssw/issues/36404
Went systematically through all of the CMSDEPRECATED_X warnings in the `MuonAnalysis/MomentumScaleCalibration`  subsystem from `CMSSW_12_3_CMSDEPRECATED_X_2021-12-10-2300` and removed deprecated API calls.
Bonus:
   * merged header files in plugins implementations

#### PR validation:

`cmssw` compiles

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
@cms-sw/orp-l2 is the release broken? 
I don't see how my changes can cause the compilation errors at https://github.com/cms-sw/cmssw/pull/36485#issuecomment-993519196
Also I see the same at: https://github.com/cms-sw/cmssw/pull/36484

**Comment by perrotta** [comment]
@mmusich #36343 and https://github.com/cms-sw/cmsdist/pull/7441 may have broken it: investigating...

**Comment by qliphy** [comment]
> @cms-sw/orp-l2 is the release broken? I don't see how my changes can cause the compilation errors at [#36485 (comment)](https://github.com/cms-sw/cmssw/pull/36485#issuecomment-993519196) Also I see the same at: #36484

As shown above,  #36343 was also included on top of IB + this PR after doing git cms-merge-topic ,
and we need also https://github.com/cms-sw/cmsdist/pull/7441 which has been included in next IB: CMSSW_12_3_X_2021-12-13-2300 which includes

**Comment by mmusich** [comment]
@qliphy @perrotta thanks! 
So it's just a matter of waiting for the next IB to appear?

**Comment by qliphy** [comment]
> @qliphy @perrotta thanks! So it's just a matter of waiting for the next IB to appear?

Yes, I think so.  We need to wait for next IB with cms-sw/cmsdist#7441

**Comment by perrotta** [comment]
It seems to be there now: https://cmssdt.cern.ch/SDT/html/cmssdt-ib/#/ib/CMSSW_12_3_X (I don't know if it was already there when you tested first 2 hours ago)
To stay on the safe side, we can even test with the missing piece...

**Comment by perrotta** [comment]
please test with cms-sw/cmsdist#7441

**Comment by qliphy** [comment]
please test

**Comment by qliphy** [comment]
merge

**Comment by santocch** [comment]
+1

**Pull request merged**
