### PR TITLE
Fix TEfficiency::ClopperPearson in DQMGenericClient (93x)

### PR DESCRIPTION
**Pull request by fwyzard**
Starting from ROOT 6.06, `TEfficiency` methods support `double` parameters for computing efficiencies and errors for weighted histograms.
Thus, we no longer need to downcast the numerator and denominator from `double` to `int`.

I've also updated the check on the arguments to reject negative values.

### CODE REVIEW

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by fwyzard** [comment]
@rovere FYI

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
merge

**Comment by slava77** [comment]
a fix to div by zero is highly desired.
This has contributed to the numerous failures in cms-bot comparisons jobs today.

**Comment by fwyzard** [comment]
It can wait a day for me to come back from holidays.

Or, anybody else can submit the fix earlier if they cannot wait for another
2-3 hours.

.A

**Comment by fwyzard** [comment]
fixed by #20017 .

**Comment by slava77** [comment]
On 8/2/17 1:56 AM, Andrea Bocci wrote:
> fixed by #20017 <https://github.com/cms-sw/cmssw/pull/20017> .

Nice.
Thank you.

**Pull request merged**
