### PR TITLE
Set HCAL method 3 respons to 1.0 for data and MC.

### PR DESCRIPTION
**Pull request by fwyzard**
Assume that retuning the pulse shapes will give the same response for Method 2 and Method 3, both for data and MC.

### CODE REVIEW

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
backport of #17872

**Comment by fwyzard** [comment]
Note that this does not change the value used in the HLT menus.
Those should be changed independently, via [CMSHLT-1212](https://its.cern.ch/jira/browse/CMSHLT-1212), and the merged in the release.

**Comment by Martin-Grunewald** [comment]
+1

**Comment by fwyzard** [comment]
Please merge !

**Comment by perrotta** [comment]
+1
Same as #17872

**Comment by davidlange6** [comment]
+1

**Comment by Martin-Grunewald** [comment]
@fwyzard 
#17908 now merged removes the file HLTrigger/Configuration/python/customizeHLTforHCALPhaseI.py
This this PR has now a merge conflict since you changed it...

**Comment by fwyzard** [comment]
rebsed, removing the file that was already removed

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
@davidlange6 , if the tests pass, can you merge ?

**Comment by Martin-Grunewald** [comment]
+1

**Comment by perrotta** [comment]
+1
(again...)

**Comment by davidlange6** [comment]
+1

**Pull request merged**
