### PR TITLE
Followup of switch to TauId MVA2017v2

### PR DESCRIPTION
**Pull request by mbluj**
#### PR description:

This PR adds VVLoose working points (WPs) of two species of the MVA2017v2 TauID which were forgotten in #26541. 

Supposed to be backported to 10_6_X for UL.

#### PR validation:

PR tested successfully with a "Tau re-reco + MiniAOD" workflow on top of AOD input file. 

The PR causes that the MiniAOD sequence run on old RECO/AOD samples, i.e. with old tau collections w/o the two new WPs, fails. 

#### if this PR is a backport please specify the original PR:

N/A

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by mbluj** [comment]
As far I can see the tests which fail are due to running PAT/MiniAOD on old AOD inputs which do not contain new WPs. In my understanding it is kind of workflow which is not expected with 10_6_X/11_0_X releases.

**Comment by slava77** [comment]
> As far I can see the tests which fail are due to running PAT/MiniAOD on old AOD inputs which do not contain new WPs. In my understanding it is kind of workflow which is not expected with 10_6_X/11_0_X releases.

we should support reading old AOD or miniAOD inputs until some time after everyone has switched to the 10_6_X outputs.

**Comment by mbluj** [comment]
First of the two recent comments adds the new WPs to RECO/AOD event content and other adds the full set of tauIDs with the 2017v2 training to the `miniAOD_94XFall17` workflow. Those additions fix broken matrix tests.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/26824	cd5b47f
- code changes are in line with the PR description
- jenkins tests pass and comparisons with the baseline show differences in expected places:
    - in the miniAOD taus in ```"slimmedTaus_[^$]*_tauIDs\|slimmedTausBoosted_[^$]*_tauIDs"``` variables there are more IDs saved (the comparison tool does not handle well the addition of variables and shows more changes than there are really; just two IDs added)
    - checks of saved products show that two more PFTauDiscriminator products are showing up in the reco outputs in line with the changes made in RecoTauTag_EventContent_cff.py

**Comment by slava77** [comment]
@mbluj 
I think that you can proceed with making a backport to 106X. 
Perhaps it's safer to make a separate topic branch.

**Comment by mbluj** [comment]
OK, I will prepare a separate branch which will be an exact clone of one integrated in this PR.

**Comment by santocch** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
