### PR TITLE
HLtriggerOffline/Higgs path update (74X)

### PR DESCRIPTION
**Pull request by jasperlauwers**
Backport of #11206 and #10533

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
-1
please rebase on top of #11103
another commit came.

**Comment by jasperlauwers** [comment]
done

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1

**Comment by jasperlauwers** [comment]
Also this one is a backport that was merged in 76X 8 days ago

**Comment by deguio** [comment]
-1
superseded by #11344

**Pull request closed without merging**
