### PR TITLE
Update displacedRegional baseline workflow .701

### PR DESCRIPTION
**Pull request by slava77**
useful to make a baseline in connection with #43336

### CODE REVIEW

**Comment by slava77** [comment]
test parameters:
- workflow = 12434.701
- relvals_opt= -w upgrade

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by AdrianoDee** [comment]
+pdmv

**Comment by srimanob** [comment]
+Upgrade

New defined workflow runs fine.

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
