### PR TITLE
Changed FailPath/SkipEvent to TryToContinue [Generator]

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

The former options were replaced with the latter some time ago.

#### PR validation:

The configurations are not used anywhere.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by makortel** [comment]
@cms-sw/generators-l2 Gentle ping

**Comment by makortel** [comment]
@cms-sw/generators-l2 Gentle ping

**Comment by makortel** [comment]
@cmsbuild, please test

Refresh

**Comment by makortel** [comment]
https://github.com/orgs/cms-sw/teams/generators-l2 Ping

**Comment by makortel** [comment]
@cms-sw/generators-l2 Ping

**Pull request merged**
