### PR TITLE
bsunanda:Run2-hcx38 Validation package for HGCal

### PR DESCRIPTION
**Pull request by bsunanda**
Requesting for a a new package Validation/HGCalValidation for valiating SimHits, Digis, RecHits
@lgray Could you look into this new addition

### CODE REVIEW

**Comment by lgray** [comment]
@bsunanda I'll take care of it momentarily.

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
@bsunanda @smuzzafar This is the cmssw PR corresponding to the cms-bot update in: https://github.com/cms-sw/cms-bot/pull/546

**Comment by lgray** [comment]
@cmsbuild check me out! (trying to get it to update the labels here)

**Comment by lgray** [comment]
@danduggan, @vanbesien This is a new validation package for HGCal, could you please review this PR and sign off? Thanks!

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by deguio** [comment]
ciao @bsunanda,
I have the following comments/questions:
- for my education, what V6 stands for?
- the C++ classes have similar structure and for all of them I would:
   - move whatever is not pure booking in the dqmBeginRun. see for example: https://github.com/bsunanda/cmssw/blob/Run2-hcx38/Validation/HGCalValidation/plugins/HGCalDigiValidation.cc#L240
more details at: https://twiki.cern.ch/twiki/bin/view/CMS/DQMOfflineThreadedMigration
   - remove the endRun from the analyzers and move the operation in the clients. when running step1 in parallel it would give wrong results.
   - reduce the number of bins where possible as discussed at the DQM meeting

thanks,
F.

**Comment by bsunanda** [comment]
@deguio @danduggan @vanbesien Taken care of the suggestions. HGCAL geometry was implemented in successive designs. Many of the studies was done using the description as in Geometry/HGCalCommonData/data/v5 which is called V5 geometry. Similarly the one described in the TP is better defined in Geometry/HGCalCommonData/data/v6 which is called V6 geometry.
________________________________

**Comment by bsunanda** [comment]
@cmsbuild Please test
________________________________
From: Sunanda Banerjee
Sent: 15 October 2015 21:38
To: cms-sw/cmssw; cms-sw/cmssw
Subject: RE: [cmssw] bsunanda:Run2-hcx38 Validation package for HGCal (#11649)

@deguio @danduggan @vanbesien Taken care of the suggestions. HGCAL geometry was implemented in successive designs. Many of the studies was done using the description as in Geometry/HGCalCommonData/data/v5 which is called V5 geometry. Similarly the one described in the TP is better defined in Geometry/HGCalCommonData/data/v6 which is called V6 geometry.
________________________________

**Comment by slava77** [comment]
-1

needs a rebase

**Comment by bsunanda** [comment]
@slava77 I tried against CMSSW_7_6_X_2015-10-16-1100 and could not see any conflict
________________________________

**Comment by slava77** [comment]
Sunanda, it's not about a conflict, it's about the commit history of this PR including hundreds of commits with 3.5K files changed.
It should be only with  relevant changes.

**Pull request closed without merging**
