### PR TITLE
HeavyFlavor DQM fixes

### PR DESCRIPTION
**Pull request by elusian**
#### PR description:

This is a collection of small fixes for the recently merged HeavyFlavorDQM. 
It also adds a customiser to allow running the DQM module from miniAOD instead of AOD

#### PR validation:

Fixes tested on the workflow 1366.0 which uses this module. Customisation tested on Early Run3 miniAOD data

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

This PR will be backported to 12_4

### CODE REVIEW

**Comment by emanueleusai** [comment]
please test

**Comment by mmusich** [comment]
type bug-fix

**Comment by mmusich** [comment]
test parameters:
   * workflows = 1347, 1349, 1350, 1364, 1365, 1366, 136.884, 136.896, 136.860, 136.898
   * relvals_opt= -w standard,highstats,pileup,generator,extendedgen,production,cleanedupgrade,ged

**Comment by emanueleusai** [comment]
+1

- ME comparison changes induced by label and range changes in the plots

**Comment by perrotta** [comment]
+1

**Pull request merged**
