### PR TITLE
GEMGeometryAnalyzer - added first and last strip global position

### PR DESCRIPTION
**Pull request by jshlee**
#### PR description:

Added first and last strip global position in the GEMGeometryAnalyzer to help debug/validate the geometry.

#### PR validation:

GEMGeometryAnalyzer doesn't run in any of the workflows but tested with 34611.0 anyways.

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by cvuosalo** [comment]
+1

**Comment by jshlee** [comment]
can this be merged?

**Comment by perrotta** [comment]
@cms-sw/upgrade-l2 this looks like a rather simple update of a private (\test) GME analyzer: do you have any comment on it?

**Comment by srimanob** [comment]
+Upgrade

Adding information on GEMGeometryAnalyzer, no change is expected.

**Comment by perrotta** [comment]
+1

**Pull request merged**
