### PR TITLE
[12_2_X] Inclusion of new ECAL PF cluster corrections in Run-3 MC GTs

### PR DESCRIPTION
**Pull request by tvami**
#### PR description:

See https://github.com/cms-sw/cmssw/pull/36377

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

This was never meant to be in 12_3_X....
Backport of https://github.com/cms-sw/cmssw/pull/36377

### CODE REVIEW

**Comment by tvami** [comment]
backport of https://github.com/cms-sw/cmssw/pull/36377

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
+alca
 * master is already signed

**Comment by qliphy** [comment]
+1

**Pull request merged**
