### PR TITLE
[102X][Change Metadata]Book-keeping for AlCa/DB 

### PR DESCRIPTION
**Pull request by lpernie**
Input tag changed to: SiStripApvGainAAG_pcl
in:
CondFormats/Common/test/SiStripApvGainRcdAAG_multirun_prep.json
CondFormats/Common/test/SiStripApvGainRcdAAG_multirun_prod.json

### CODE REVIEW

**Comment by lpernie** [comment]
please test

**Comment by mmusich** [comment]
@lpernie since you are at it, may I ask you to change also this in the usertexts of the single run harvestng uploads:

https://github.com/lpernie/cmssw/blob/eead3d1ef38cce67fd403aed88873857a663ff81/CondFormats/Common/test/SiStripApvGainRcd_prod.json#L9

https://github.com/lpernie/cmssw/blob/eead3d1ef38cce67fd403aed88873857a663ff81/CondFormats/Common/test/SiStripApvGainRcd_prep.json#L9

it says: ```PCL MultiRun Upload for SiStrip Gains calib. (prep)```
but it is actually for the single run harvesting, so it's a bit misleading.
Needless to say, this needs to be propagated also in the tag in DB.
Thanks,

Marco

**Comment by lpernie** [comment]
Hi @mmusich, we have to make another change to the metadata for tracker alignment anyway, I will fix the usertexts then.
Thanks,
Luca

**Comment by fabiocos** [comment]
@ggovi could you please check and sign in case?

**Comment by ggovi** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
