### PR TITLE
Properly find test executable for MonitorThread signal test

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

The directory holding test executables is added by scram to the PATH during runtests processing.

#### PR validation:

The modified test succeeds.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
This should fix the unit test failure in the IB for FWCore/SharedMemory.

**Comment by Dr15Jones** [comment]
please test

**Comment by makortel** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
