### PR TITLE
Phase2-hgx282X Change the use of ESHandle to ESGetToken

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Change the use of ESHandle to ESGetToken in some of the validation codes of HGCal

#### PR validation:

Use the runTheMatrix test workflows 35034.0 and 37434.0

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by rovere** [comment]
Ciao @bsunanda 
thanks for taking care of this! Since we are touching files related to tokens (from ES) and geometry, would it make sense to get rid of the `hcal` handling in `HGCAL` code that is there just as an ancient relic from the past?
That would tremendously simplify and clean the code.

**Comment by bsunanda** [comment]
@rovere I shall do that (remove reference to HCAL) once this PR gets merged

**Comment by jfernan2** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
