### PR TITLE
fix binning in muon->innerTrack DQM

### PR DESCRIPTION
**Pull request by mtosi**
looking at the offline GUI,
I've just realized few histograms have larger binning than needed

### CODE REVIEW

**Comment by mtosi** [comment]
@VinInn @makortel 
I'm going to prepare the backport for 92x

but,
I realized the hit efficiency plots have x-axis up to PU = 50
while doing this update in 94x I see that it is fixed here

shall I move to PU = 150 in 92x ?
or, in order to squeeze as much as possible the #bins, at least 60 ?

thanks

**Comment by mtosi** [comment]
@cmsbuild, please test

**Comment by VinInn** [comment]
The problem with muon is that statistics is not very high: maybe we can go to 120 and use 60 bins?
this is how it looks in express for recent runs
image

**Comment by mtosi** [comment]
@cmsbuild, please test

**Comment by mtosi** [comment]
@VinInn 
I updated the code in order to configure this axis as well,
the main module, used by tracking, is kept to the default values (`150, 0.5, 150.5`),
while I adjusted the module for the muon->innerTrack monitor to have `40, 0.5, 120.5`

**Comment by davidlange6** [comment]
please test

**Comment by mtosi** [comment]
@cmsbuild, please test

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
