### PR TITLE
[93X] fix configuration of Strip hit efficiency tree and add tree producer to unit tests

### PR DESCRIPTION
**Pull request by mmusich**
Fixes a mistake in the Strip Hit efficiency tree configuration introduced in #20052 and adds a unit test to avoid such mistakes to happen again unnoticed.

### CODE REVIEW

**Comment by mmusich** [comment]
type bugfix

**Comment by davidlange6** [comment]
please test

**Comment by mmusich** [comment]
@arunhep @lpernie please re-trigger the tests -  DAS failure is unrelated

**Comment by lpernie** [comment]
@cmsbuild  please test

**Comment by lpernie** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
