### PR TITLE
Bump TObject versions for ROOT  master

### PR DESCRIPTION
**Pull request by mrodozov**
Copy of https://github.com/cms-sw/cmssw/pull/26464
for testing against root master: https://github.com/cms-sw/cmsdist/pull/4908
to be closed on merging #26464

### CODE REVIEW

**Comment by mrodozov** [comment]
please test with https://github.com/cms-sw/cmsdist/pull/4908

**Comment by mrodozov** [comment]
please test with https://github.com/cms-sw/cmsdist/pull/4945

**Comment by fabiocos** [comment]
@mrodozov @smuzaffar this looks ok in CMSSW_10_6_ROOT614_X_2019-05-08-1400 am I correct?

**Comment by mrodozov** [comment]
yes we can keep it to be merged on master. This failing tests looks unrelated to ROOT.

**Comment by fabiocos** [comment]
please test with cms-sw/cmsdist#4945

**Comment by fabiocos** [comment]
please abort

**Comment by smuzaffar** [comment]
please test withcms-sw/cmsdist#4952

**Comment by fabiocos** [comment]
@andrius-k @schneiml @fioriNTU this setup has been tested already in the IB, so as soon as this test is finished I would like to integrate it into the master branch

**Comment by fabiocos** [comment]
@smuzaffar @andrius-k @schneiml the unit test failure has nothing to do with this PR, see #26741, and the DQM differences are also independent (and to be understood)

**Comment by fioriNTU** [comment]
> @smuzaffar @andrius-k @schneiml the unit test failure has nothing to do with this PR, see #26741, and the DQM differences are also independent (and to be understood)

Dear @fabiocos, what DQM differences are you referring to? I see only differences in the Timer Service plots. Can you please clarify?

**Comment by fabiocos** [comment]
@fioriNTU interesting, you look at the bin-to-bin comparison recently added, i look at the usual RelMon report above (132 histograms, all in DT DCS information with nan)... I am testing whether my recent update, that removes lots of spurious warnings, is the cause for this new report

**Comment by fabiocos** [comment]
Anyway I would like to move forward and merge this PR and the corresponding ROOT 6.14 update tonight

**Comment by fabiocos** [comment]
+1

as in the ROOT614_X queue this is working since several IBs, I move forward with its integration, as it is useful for further developments

**Comment by fabiocos** [comment]
merge

**Comment by jfernan2** [comment]
+1
For the records

**Pull request merged**
