### PR TITLE
Fix issue #23475 in the hlTPixel plugin (LogError from SiPixelPhase1 DQM)

### PR DESCRIPTION
**Pull request by arossi83**
https://github.com/cms-sw/cmssw/issues/23475

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by fabiocos** [comment]
@arossi83 the problem that I reported looks gone, now anyway I see

%MSG-w SiPixelPhase1TrackClusters:   SiPixelPhase1TrackClusters:hltSiPixelPhase1TrackClustersAnalyzer  13-Jun-2018 11:56:20 CEST Run: 315489 Event: 47697292
PixelClusterShapeCache collection is not valid
%MSG

that does not sound healthy as well, although less critical in terms of filling LogError skims. The problem is here
https://cmssdt.cern.ch/lxr/source/DQM/SiPixelPhase1Track/plugins/SiPixelPhase1TrackClusters.cc#0141
and it implies that the module is never run anyway.

**Comment by mtosi** [comment]
I've just seen this PR and --as you know-- I was offline in the last period,
therefore apologies for the low level questions

which workflow is triggering the warning message ?
the module for the pixel monitoring @HLT is configured as
(https://github.com/arossi83/cmssw/blob/5b39d28bb0da731aa7ddddaa29871b1617006a1d/DQMOffline/Trigger/python/SiPixel_OfflineMonitoring_TrackCluster_cff.py#L373
=>  it seems properly configured
which is the input file ?
if it is a standard RAW file, this module does not have to be run
=> there is an error in the main DQM  sequence

**Comment by fabiocos** [comment]
@mtosi wf 136.85 step3:

https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-23575/28666/runTheMatrix-results/136.85_RunEGamma2018A+RunEGamma2018A+HLTDR2_2018+RECODR2_2018reHLT_skimEGamma_Prompt_L1TEgDQM+HARVEST2018_L1TEgDQM/step3_RunEGamma2018A+RunEGamma2018A+HLTDR2_2018+RECODR2_2018reHLT_skimEGamma_Prompt_L1TEgDQM+HARVEST2018_L1TEgDQM.log

**Comment by dmitrijus** [comment]
+1

**Comment by fioriNTU** [comment]
@fabiocos @arossi83 @mtosi the warning comes from here https://github.com/cms-sw/cmssw/blob/master/DQM/SiPixelPhase1Track/plugins/SiPixelPhase1TrackClusters.cc#L141 it looks like in hlt the ClusterShapeCache collection is not valid, while this is a fundamental ingredient for Offline monitoring. Again this issue would be solved creating a separate plugin, esplicitly designed to run on hlt quantity and especially on hlt tracking. It would make also the configurations of the modules more flexible.

**Comment by fabiocos** [comment]
+1

this PR removes the LogError message, and this is already good in view of skims. The residual problem will be tackled in a separated development, and for this reason I keep open the issue #23475 that started this work.

**Pull request merged**
