### PR TITLE
Merge 9_4_MAOD_X into 9_4_AN_X

### PR DESCRIPTION
**Pull request by gpetruc**
Apparently now there's no auto-fwd-port from MAOD to AN sub-branches, so as a workaround I'm doing it by hand as a PR.

`CMSSW_9_4_MAOD_X` is identical to `CMSSW_9_4_5_cand1` except for the fwd-port of #22671 (that should be also in `CMSSW_9_4_AN_X`), according to the diffs https://github.com/cms-sw/cmssw/compare/CMSSW_9_4_5_cand1...CMSSW_9_4_MAOD_X

This merge is needed since upcoming analysis updates will be based on the code for the miniAOD v2 that is in the MAOD branch, and putting everything in a single PR would make the diff unreadable.

### CODE REVIEW

**Comment by gpetruc** [comment]
please test

**Comment by arizzi** [comment]
@fabiocos  this is a trivial fwd port, should we really get signatures ? (I assume not)

**Comment by fabiocos** [comment]
@gpetruc @arizzi to be clear, the lack of automatic forward port from 9_4_MAOD_X was discussed to make cleaner the synchronization. With this PR I understand that now you are just making an explicit one shot  synchronization of the AN branch with the candidate 9_4_5 without explicitly waiting for its validation

**Comment by gpetruc** [comment]
yes, the rationale is that at this point there's no use of making a 9_4_AN release that does not contain what is currently in 9_4_MAOD_X.

**Comment by fabiocos** [comment]
@gpetruc apparently this was not needed up today, we said that we want to keep MAOD and AN as distinct in scope. Anyway this is going to be merged.

**Comment by prebello** [comment]
+1
(based on sucessfull jenkings test)

**Comment by fabiocos** [comment]
+1

synchronize 9_4_AN_X with 9_4_MAOD_X

**Comment by fabiocos** [comment]
merge

**Pull request merged**
