### PR TITLE
Cleanup pixel tracking configurations

### PR DESCRIPTION
**Pull request by makortel**
This PR merges `PixelTracks_2017_cff` to `PixelTracks_cff` as mentioned in RECO meeting on June 16
https://indico.cern.ch/event/645986/contributions/2623365/attachments/1478282/2290968/slides_reco_20170616.pdf
I also had to do additional cleanup in initialStep to make the CA quadruplets the default `initialStepHitQuadruplets` module as otherwise workflows not having `trackingPhase1` or `trackingPhase2PU140` would crash because of the clone in `PixelTracks_cff` that assumes the original module to be CA quadruplets. Ok, this cleanup should have been done anyway as the CA quadruplets is the default for both phase1 and phase2.

Tested in CMSSW_9_3_X_2017-07-13-1100, should have no physics impact.

@rovere @VinInn

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by dmitrijus** [comment]
+1

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/19738	965db8d
- configuration changes only; in line with the description
- jenkins tests pass and comparisons show no differences

**Comment by davidlange6** [comment]
+1

**Comment by Dr15Jones** [comment]
I think this pull request maybe causing the IB failures
https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc6_amd64_gcc630/CMSSW_9_3_X_2017-07-19-2300/pyRelValMatrixLogs/run/10024.4_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2017_GenSimFullINPUT+DigiFull_2017+RecoFull_trackingPhase1QuadProp_2017+HARVESTFull_2017/step3_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2017_GenSimFullINPUT+DigiFull_2017+RecoFull_trackingPhase1QuadProp_2017+HARVESTFull_2017.log

**Comment by slava77** [comment]
the err looks related, indeed.

**Comment by davidlange6** [comment]
@vininn - can you have a look at this?

**Comment by VinInn** [comment]
is a PR from a TRK-POG convener...

**Comment by davidlange6** [comment]
who is on vacation as I understand it?

**Comment by VinInn** [comment]
> On 20 Jul, 2017, at 11:31 AM, David Lange <notifications@github.com> wrote:
> 
> who is on vacation as I understand it? 
yes, so wait 3 weeks, does not seems urgent
v.

> 
> > On Jul 20, 2017, at 11:23 AM, Vincenzo Innocente <notifications@github.com> wrote: 
> > 
> > is a PR from a TRK-POG convener... 
> > 
> > — 
> > You are receiving this because you were mentioned. 
> > Reply to this email directly, view it on GitHub, or mute the thread. 
> > 
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

--
Il est bon de suivre sa pente, pourvu que ce soit en montant. 
A.G.
http://www.flickr.com/photos/vin60/1320965757/

**Comment by davidlange6** [comment]
ok, we can revert and come back. thought i'd see if we can avoid that.

**Comment by VinInn** [comment]
removing trackingPhase1QuadProp from the RelVal for instance?

**Comment by makortel** [comment]
Hi, 

I can take a look today evening and provide a fix in a way or another (disabling workflow if nothing else works out). 

On 20 July 2017 12:33:35 EEST, Vincenzo Innocente <notifications@github.com> wrote:
>
>> On 20 Jul, 2017, at 11:31 AM, David Lange <notifications@github.com>
>wrote:
>> 
>> who is on vacation as I understand it? 
>yes, so wait 3 weeks, does not seems urgent
>v.
>
>> 
>> > On Jul 20, 2017, at 11:23 AM, Vincenzo Innocente
><notifications@github.com> wrote: 
>> > 
>> > is a PR from a TRK-POG convener... 
>> > 
>> > — 
>> > You are receiving this because you were mentioned. 
>> > Reply to this email directly, view it on GitHub, or mute the
>thread. 
>> > 
>> 
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly, view it on GitHub, or mute the thread.
>> 
>
>--
>Il est bon de suivre sa pente, pourvu que ce soit en montant. 
>A.G.
>http://www.flickr.com/photos/vin60/1320965757/

-- 
Sent from my mobile.

**Comment by makortel** [comment]
I have a fix in #19844. Thanks @Dr15Jones for reporting the problem.

**Pull request merged**
