### PR TITLE
ThePEG interface: Removed it since it is deprecated due to new Herwig…

### PR DESCRIPTION
**Pull request by mharrend**
…7 version, will be replaced by Herwig7 interface soon

### CODE REVIEW

**Comment by perrozzi** [comment]
please test

**Comment by smuzaffar** [comment]
please test with cms-sw/cmsdist#2477

**Comment by mharrend** [comment]
Since the error is not related to ThePEG / Herwig7 can you please restart the test?

**Comment by smuzaffar** [comment]
please test with cms-sw/cmsdist#2477

**Comment by mharrend** [comment]
The one failing matrix test is not due to Herwig7 or ThePEG. Instead it seems that Pythia8 or the GenSim step does not provide a necessary CMSSW product, see below

Since this error is not related to this PR. Can you please accept and merge the PRs? It would be nice to finally have Herwig7 in CMSSW and I do not see why an unrelated error should delay its implementation further.

If you want to fix the error, here I tracked down the error message:
`%MSG-w L3Absolute not found:  PATJetUpdater:updatedPatJetsBTAG  02-Sep-2016 20:39:19 CEST Run: 1 Event: 1
L2L3Residual and L3Absolute are not part of the jetCorrFactors
of module patJetCorrFactorsBTAG. Jets will remain uncorrected.
%MSG
----- Begin Fatal Exception 02-Sep-2016 20:39:19 CEST-----------------------
An exception of category 'ProductNotFound' occurred while
   [0] Processing run: 1 lumi: 1 event: 1
   [1] Running path 'dqmofflineOnPAT_2_step'
   [2] Calling event method for module PFCandidateAnalyzer/'packedCandidateDQMAnalyzerMiniAOD'
   [3] Calling method for unscheduled module HBHENoiseFilterResultProducer/'HBHENoiseFilterResultProducer'
Exception Message:
 could not find HcalNoiseSummary.
   Additional Info:
      [a] If you wish to continue processing events after a ProductNotFound exception,
add "SkipEvent = cms.untracked.vstring('ProductNotFound')" to the "options" PSet in the configuration.

----- End Fatal Exception -------------------------------------------------
Another exception was caught while trying to clean up files after the primary fatal exception.
02-Sep-2016 20:39:20 CEST  Closed file file:step2.root`

**Comment by smuzaffar** [comment]
@davidlange6 , we accidentally included herwig7 changes without this and now IBs are broken. @covarell, @perrozzi, @thuer , can you please sign this PR?  OR should we revert the herwig external?

**Comment by davidlange6** [comment]
I'm just merge this pr.  Please complain if not ok.

**Pull request merged**
