### PR TITLE
[14.0.X] move `pat::XGBooster` out of `PhysicsTools/PatAlgos` into its own package and use it for `PhotonXGBoostEstimator`

### PR DESCRIPTION
**Pull request by mmusich**
backport of https://github.com/cms-sw/cmssw/pull/45085

#### PR description:

Title says it all, implements https://github.com/cms-sw/cmssw/issues/45040#issuecomment-2136128879:

> There seems to exist a `pat::XGBooster` abstraction already in `PhysicsTools/PatAlgos`, that does the proper `XGBoosterSetParam(..., "nthread", "1")` call
>    * The abstraction should really be moved to its own package, do decouple it and `PhysicsTools/PatAlgos` dependencies
>    * One option for `PhotonXGBoostEstimator` would be to use this `XGBooste`r abstraction

#### PR validation:

`scram b runtests_RecoEgammaPhotonIdentificationTest` runs.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

verbatim backport of #45085 for data-taking purposes.

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mandrenguyen** [comment]
+`

**Comment by mandrenguyen** [comment]
+1

**Comment by vlimant** [comment]
+1

**Comment by valsdav** [comment]
+ml

**Comment by rappoccio** [comment]
+1

**Comment by mmusich** [comment]
see https://github.com/cms-sw/cmssw/pull/45085#issuecomment-2167579713

**Pull request merged**
