### PR TITLE
[12_3_X] Make sure all dictionaries in CUDADataFormats are transient

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

Backport of https://github.com/cms-sw/cmssw/pull/37218, in order to prevent further trouble like https://github.com/cms-sw/cmssw/issues/37215 also in 12_3_X.

#### PR validation:

None (topic branch is the same as in #37218).

### CODE REVIEW

**Comment by makortel** [comment]
backport of #37215

**Comment by perrotta** [comment]
backport of https://github.com/cms-sw/cmssw/pull/37218

**Comment by jpata** [comment]
test parameters:
  - enable_tests = gpu

**Comment by jpata** [comment]
@cmsbuild please test

**Comment by makortel** [comment]
+heterogeneous

**Comment by jpata** [comment]
+reconstruction
- exact backport of #37218, intended as a bugfix for 12_3
- no issues with the tests

**Comment by qliphy** [comment]
+1

**Pull request merged**
