### PR TITLE
for neutral exotic WIMPs - send their daughters to Geant4 instead of …

### PR DESCRIPTION
**Pull request by zhangzc11**
…the exotic itself

### CODE REVIEW

**Comment by civanch** [comment]
@zhangzc11 , I do not fully understand the logic. Some time ago W.Wulsin has introduced in this code a possibility to simulate long-lived exotica (much longer than use cases described in Zach talk). You need to take into account, that normally no exotic particle is defined in Geant4. Exotic particles are configured on top of normal physics list via python configuration and come as an addition. So, there is no need to remove any exotic from Geant4 simulation but only the problem how to add one properly. For exotic search of Wulsin, it was necessary to allow exotic object decay within detector. At that time, we think only on possibility to allow all possible exotic objects be tracked and decay. If we allow some invisible particle to be tracked but it would not be possible identify  and register by the detector - it is not a big problem. Like neutrino, such particles will went out of the world without visible CPU penalty. In this respect, I do not understand why you trying to forbid Geant4 tracking of zero changed exotic particles in this PR. 

If we would speak about Zach talk, I do not know how ATLAS make this simulation but in CMS we have electromagnetic processes, tracking in magnetic field, decays, and to R-hadrons nuclear interactions (implemented in weird manner but existing).  If there are requirements we should discuss how to improve CMS mechanism.

**Comment by zhangzc11** [comment]
@civanch the reason is not on the exotic particle itself, it is about its daughter particles. Let's say we have a neutralino decay to photon and gravitino; and the lifetime is lone enough that the decay happens outside the beampipe. If we only send the neutralino to Geant4 (which is what the old code is doing), the Geant4 can't deal with the decay process properly and as a result we can't see the decayed photons in ECAL(which is actually a problem we are facing in samples made after Wulsin's PR). The purpose of my PR is to send the daughter particles to Geant4 and allow us to see them. In my PR, I only do this for those neutral non-detectable exotic particles, because they can't be detected by the detector anyways so no need to send them to Geant4.

**Comment by civanch** [comment]
@zhangzc11 , have you example job which for few events demonstrate how it is working now? I may be miss something...

**Comment by zhangzc11** [comment]
examples on page 3: https://indico.cern.ch/event/656603/contributions/2683410/attachments/1505427/2346454/issue_CMSSW_delayed_SimHits_08Aug2017.pdf

**Comment by zhangzc11** [comment]
@civanch maybe it is worth to emphasize that i only touch neutral SUSY particles in my PR: (charge==0) && (pdgid >= 1000000 && pdgid <  1000040). For charged exotic and also R-hadrons which can be detected by the detector and might be simulated by Geant4, i didn't touch them.

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
@zhangzc11 , it seems that you make a correct fix. Additionally to 9_3_X you will need to make the same PR for 7_1_X. You may do it in any time, it will be validated and merged after 9_3_X is fully tested.

**Comment by zhangzc11** [comment]
@civanch OK thanks! I will make a PR to 7_1_X as well. (7_1_25_patch1/2 are still OK, jut need to fix 7_1_25_patch3 and newer ones for 2016 MC production)

**Comment by kmcdermo** [comment]
@civanch since 2017 MC will use 92X, this should be backported to 92X, correct?

**Comment by civanch** [comment]
@kmcdermo , GEN-SIM normally are produced using 7_1_X, 9_2_X should be used for DIGI-RECO.

**Comment by kmcdermo** [comment]
I see, okay.  Then definitely will need the backport to 7_1_X.  thanks!

**Comment by zhangzc11** [comment]
@civanch correct me if i'm wrong, i see that the RunIISummer17GS campaign is using 92X, no?  https://cms-pdmv.cern.ch/mcm/campaigns?prepid=RunIISummer17GS&page=0&shown=524287

**Comment by davidlange6** [comment]
that is not correct... (unless one is talking of 2016 MC)

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
