### PR TITLE
Use new primary vertex filter in hotline and high MET skim

### PR DESCRIPTION
**Pull request by duanders**
Switch to the new primary vertex filter introduced in https://github.com/cms-sw/cmssw/pull/10609.

@schoef

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by duanders** [comment]
@mmusich  Can we please have a re-test?

**Comment by mmusich** [comment]
please test
@duanders sorry, slipped out of my attention

**Comment by mmusich** [comment]
+1
for https://github.com/duanders/cmssw/commit/4602c0aa6665ef83e0c54a1d68871db3005a6b59 
Introducing new primary vertex filter in hotline

**Comment by mariadalfonso** [comment]
@srimanob please have a look at this PR. 
The equivalent 74 is already fully signed #11220, 
would like to have this asap in the 3.8 T runs

**Comment by fabozzi** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
