### PR TITLE
saving the collections of ECAL selective readout flags in pi0/eta stream output

### PR DESCRIPTION
**Pull request by cippy**
We are adding the collection of ECAL Selective Readout (SR) flags in the output  of the pi0/eta stream.
These flags are needed to study the impact of the SR thresholds on the pi0/eta reconstruction from low energy photons.

The change affects
- HLTrigger/special/src/HLTRechitsToDigis.cc
- HLTrigger/special/BuildFile.xml
(the HLT configuration for the pi0/eta stream paths will have to be modified as well adding some parameters)

The source file implements the producer that saves the digis collection in the stream output (only those digis matched to rechits used to build pi0/eta are saved). Similarly, the change we implemented takes the SrFlags collection and produce a new collections storing only the flags matched to digis that are finally kept in the stream output.

The BuildFile.xml must have a new line to include a header used by the source.

Tested from release CMSSW_9_4_0_pre2 running the (updated) HLT configuration on HLTPhysics dataset. The new collections are created and stored in the output dataset.
The event size changes by 2% from 1.96 kB/event to 1.99 kB/event

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
Please change the title of the PR to something meaningful.

Also, in case the label of the new InputTag is empty, revert to the old behavior.
The default in fillDescriptions for the new InputTag should thus be an empty InputTag.
This way the PR will not crash when running on current HLT py configs.

**Comment by cippy** [comment]
@emanueledimarco 

@Martin-Grunewald
I changed the name of the issue 

However,I'm not sure I understand the second point. 
Should I change
- desc.add<edm::InputTag>("srFlagsIn",edm::InputTag("ecalDigis"))
with
- desc.add<edm::InputTag>("srFlagsIn",edm::InputTag())
?
Note that the input collection has always existed, it is produced by the ECALRawToDigi producer called as the first step of the stream, but was not saved.
What is new in this development is the fact the the (pruned) collection is also stored in the stream output (we could have just used a 'keep' in the outputModule, but we wanted to prune the collection because we only need the flags in some regions)

**Comment by Martin-Grunewald** [comment]
My comment is about th e(technical) backward compatibility of the code changes to deal with exisiting py configs but where the code base includes this PR. The fillDescriptions value provided is then inserted/used, and that should tell the module to behave in the old way.
This way we can integrate the code already now, and do the py config update of the HLT menu later (after parsing into ConfDB) without having to do both at the same time.

**Comment by Martin-Grunewald** [comment]
And yes, "ecalDigis" does not exist at HLT where all module labels start with hlt.

**Comment by cippy** [comment]
I see, so would it be ok to have instead
desc.addedm::InputTag("srFlagsIn",edm::InputTag("hltEcalDigis"))
?
Indeed in my HLT configuration I see "hltEcalDigis" is the name used also in other producers to get the same collection. I used ecalDigis before because that was appearing in the fillDescriptions for other parameters.
If this is enough I will commit the new change

**Comment by Martin-Grunewald** [comment]
No, Empty and test in the code!

**Comment by cippy** [comment]
Hi,
If I use 
desc.add<edm::InputTag>("srFlagsIn",edm::InputTag())
and run the old configuration, where the new parameters are not yet defined,
I get this error [0]

On the other hand, if I use 
desc.add<edm::InputTag>("srFlagsIn",edm::InputTag("hltEcalDigis"))
the old configuration runs fine and the output will have the new collection, with the caveat that the label for the new output is always the same one (as in the fillDescriptions), while at some point the new parameter will assign different names depending on the module name (see here [1] extracted from edmDumpEventContent)

[0]
----- Begin Fatal Exception 20-Oct-2017 16:49:46 CEST-----------------------
An exception of category 'ProductNotFound' occurred while
   [0] Processing  Event run: 297113 lumi: 236 event: 440179434 stream: 1
   [1] Running path 'AlCa_EcalPi0EBonly_v11'
   [2] Calling method for module HLTRechitsToDigis/'hltAlCaPi0EBRechitsToDigis'
Exception Message:
Principal::getByToken: Found zero products matching all criteria
Looking for type: edm::SortedCollection<EBSrFlag,edm::StrictWeakOrdering<EBSrFlag> >
Looking for module label: @EmptyLabel@
Looking for productInstanceName:


[1]
Type                                  Module                      Label             Process
----------------------------------------------------------------------------------------------
edm::SortedCollection<EBSrFlag,edm::StrictWeakOrdering<EBSrFlag> >    "hltAlCaEtaEBRechitsToDigis"   "pi0EBSrFlags"    "MYHLT"   
edm::SortedCollection<EBSrFlag,edm::StrictWeakOrdering<EBSrFlag> >    "hltAlCaPi0EBRechitsToDigis"   "pi0EBSrFlags"    "MYHLT"   
edm::SortedCollection<EESrFlag,edm::StrictWeakOrdering<EESrFlag> >    "hltAlCaEtaEERechitsToDigis"   "pi0EBSrFlags"    "MYHLT"   
edm::SortedCollection<EESrFlag,edm::StrictWeakOrdering<EESrFlag> >    "hltAlCaPi0EERechitsToDigis"   "pi0EBSrFlags"    "MYHLT"   
e

**Comment by cippy** [comment]
The solution [0] would probably work if in the product() method I added something like,
if (not inputTag is empy) {
do not read the new input, do not fill the new
}

**Comment by emanueledimarco** [comment]
@Martin-Grunewald what is the need of integrating the C++ before the update of the HLT menu? 
If the menu is updated consistently it will run w/o the need of checking wether the inputtag is filled or not.

**Comment by Martin-Grunewald** [comment]
@cippy Yes, exactly, that's what I mean the code should reproduce the old behaviour (ie, does not do the new stuff at all).
@emanueledimarco Flexibility in integration and deployment of the new features while keeping all old configs working properly with the new code.

**Comment by Martin-Grunewald** [comment]
https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideGlobalHLT#Trigger_development_for_Run_2

especially
```
Specifically note that the current trigger development release is 92X. Thus, for any new C++ code needed for your development, you need to provide a pull request for 93X first and then a backport PR for 92X. For added module parameters and functionality, you must use either a fillDescriptions(.) method (preferred) or existsAs (deprecated) to take care of older py configs not yet containing the new parameters. The new parameters' default values must be set in such a way so that the old behaviour of the module is reproduced! Also, the result of the code must not depend on whether any parameter is present in the py config or not, only on its default value (in fillDescriptions) or its value in the py config! This allows us to integrate code developments independently (and earlier) than updating the HLT menu (python config) itself with your changes: the python update requires ConfDB parsing to discover the new parameters, followed by a migration of the HLT menu within ConfDB to the newly parsed code template. 
```

**Comment by cippy** [comment]
I pushed a commit where I add a protection against empty InputTag for the new parameter. This should allow for backward compatibility, as requested.
I tested the code running the configuration twice, once with the new parameters and once without them: in the former case the new collection is saved in the output, while in the latter it is not

I'm going to add the same commit to the PR to 92X.

@Martin-Grunewald this PR is made from 94X, but in your previosu message you mention 93X. Should I also reopen a PR in 93X as well?

**Comment by Martin-Grunewald** [comment]
We only need 92X and 94X.

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
