### PR TITLE
Report CPU time spent in child processes of ExternalLHEProducer [9_3]

### PR DESCRIPTION
**Pull request by Dr15Jones**
When accounting for CPU time used by a cmsRun job, we need to also include the CPU time of the child processes launched by ExternalLHEProducer.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
backport #22100

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by perrozzi** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
