### PR TITLE
Remove dead header TrackingDataPrint.h

### PR DESCRIPTION
**Pull request by Teemperor**
This header doesn't compile anymore because it references non-existing
functions in ROOT/CMS. It is never included in CMS, seems to be only
here for debug purposes and it is also not updated since it was imported to
git in 2013, so I think we can remove this.

### CODE REVIEW

**Comment by Teemperor** [comment]
Part of the work going on regarding issue https://github.com/cms-sw/cmssw/issues/15248 (because we can't compile this header into a module when it's broken).

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
@Teemperor , the class is used in unit test(s), may be optimal rename it.

**Comment by davidlange6** [comment]
Hi @civanch - which unit test?

**Comment by civanch** [comment]
please test
@davidlange6 , I likely was wrong - the reason of failing is not this header

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
