### PR TITLE
HCAL online laser monitoring revision

### PR DESCRIPTION
**Pull request by deguio**
needed in the online to monitor laser at p5. already merged in 81x (#15261).
@vkhristenko @Spudmeister

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
@deguio: Could you please provide a more descriptive PR title? Maybe something like "HCAL online laser monitoring revision"? 
Also, please list in the description the 81X version of this PR. 
Thanks.

**Comment by cvuosalo** [comment]
@cmsbuild please test
@smuzaffar says 80X Jenkins tests are working again

**Comment by slava77** [comment]
@cmsbuild please test

@smuzaffar 
please check why did the information about the build failure not propagate to github https://cmssdt.cern.ch/jenkins/job/ib-any-integration/14427/console

**Comment by slava77** [comment]
the errors are related to release/infrastructure:

das_client.py now fails with ``` HTTP Error 403: Forbidden ```
changes to use das_client should be applied.
@davidlange6 @smuzaffar 
 is this a known issue in the works already?

**Comment by smuzaffar** [comment]
@degano was taking care of it.

**Comment by smuzaffar** [comment]
please test
for now I created a symlink for das_client.py to das_client wrapper to avoid this issue for Pr testing. We should revert this change once all release cycles start using das_client wrapper

**Comment by degano** [comment]
@smuzaffar @slava77 I've created the PR that should fix this issue in #15398.

**Comment by smuzaffar** [comment]
looks like 
```
dataset=/HIMinBiasUPC/HIRun2011-v1/RAW run=182124
```
 is not available at CERN. We will request to get it back at cern

**Comment by slava77** [comment]
On 8/9/16 11:50 AM, Malik Shahzad Muzaffar wrote:
> looks like
> 
> |dataset=/HIMinBiasUPC/HIRun2011-v1/RAW run=182124 |
> 
> is not available at CERN. We will request to get it back at cern

Maybe you will have better luck.
I made  a request a week ago
https://cmsweb.cern.ch/phedex/prod/Request::View?request=756137
but nobody acted on it.

**Comment by smuzaffar** [comment]
I have contacted Daniel to approve the request you made.

**Comment by slava77** [comment]
On 8/9/16 1:46 PM, Malik Shahzad Muzaffar wrote:
> I have contacted Daniel to approve the request you made.

Thank you.

This is my third phedex request in a row where the operators or managers
had to be contacted directly after the request is made.

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/15384 21a9ad2
- backport of #15261: all changes from the 81X origin PR are in this PR; there is also a technical edit from #14223  removing "using namespace std;" in   EventFilter/HcalRawToDigi/plugins/HcalRawToDigi.cc 
- jenkins tests pass
- tested locally with a set similar to jenkins: there are no changes as expected. Some notes about testing with uMNIO board in readout can be found in #15261.

**Comment by smuzaffar** [comment]
please test

missing dataset for 140.53 should be at cern now

**Comment by deguio** [comment]
@cvuosalo 
I updated title and description.
cheers,
F.

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
