### PR TITLE
Run2-gex129 A step to make a 2018 scenario working for dd4hep

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

A step to make a 2018 scenario working for dd4hep. The naming of the scenarios were discussed in the SIM meeting dated April 22 and these will be implemented in the subsequent PR for 2018 scenarios.

#### PR validation:

Use the runTheMatrix test workflows and workflows in the test/python area

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
+1

**Comment by bsunanda** [comment]
@srimanob Please sign this PR

**Comment by srimanob** [comment]
Same comment as https://github.com/cms-sw/cmssw/pull/37593
I don't see the urgency as we don't do Run-2 MC with 12_4 at this moment, and would like to discuss widely in the SIM meeting first.

**Comment by bsunanda** [comment]
@srimanob Please sign it now

**Comment by srimanob** [comment]
+Upgrade

@bsunanda, please update the PR description, maybe point to the SIM meeting and conclusion.

**Comment by qliphy** [comment]
@bsunanda  Please see https://github.com/cms-sw/cmssw/pull/37597#issuecomment-1107353232

**Comment by bsunanda** [comment]
@qliphy @perrotta We discussed about this and #37593 in the SIM meeting last Friday. We came to a conclusion how we should rename all the 2017 and 2018 scenarios - legacy as well as the new ones. We shall proceed after this PR is merhed

**Comment by bsunanda** [comment]
@qliphy @perrotta I have updated the PR description. Please merge this PR so that we can proceed with the next step

**Comment by qliphy** [comment]
+1

**Pull request merged**
