### PR TITLE
Hcal backwards compatible version of hcal scale and digitizer changes

### PR DESCRIPTION
**Pull request by davidlange6**
backwards compatible version of #11107 and #11087

### CODE REVIEW

**Comment by davidlange6** [comment]
please test



On Sep 8, 2015, at 3:11 PM, cmsbuild <notifications@github.com<mailto:notifications@github.com>> wrote:


A new Pull Request was created by @davidlange6<https://github.com/davidlange6> (David Lange) for CMSSW_7_5_X.

Hcal backwards compatible version of hcal scale and digitizer changes

It involves the following packages:

SLHCUpgradeSimulations/Configuration
SimCalorimetry/HcalSimAlgos
SimCalorimetry/HcalSimProducers

@cmsbuild<https://github.com/cmsbuild>, @civanch<https://github.com/civanch>, @mdhildreth<https://github.com/mdhildreth> can you please review it and eventually sign? Thanks.
@makortel<https://github.com/makortel>, @Martin-Grunewald<https://github.com/Martin-Grunewald> this is something you requested to watch as well.
You can sign-off by replying to this message having '+1' in the first line of your reply.
You can reject by replying to this message having '-1' in the first line of your reply.
If you are a L2 or a release manager you can ask for tests by saying 'please test' in the first line of a comment.
@degano<https://github.com/degano> you are the release manager for this.
You can merge this pull request by typing 'merge' in the first line of your comment.

**Comment by abdoulline** [comment]
I presume: 

https://github.com/davidlange6/cmssw/blob/hcalBackwards/SimCalorimetry/HcalSimProducers/python/hcalUnsuppressedDigis_cfi.py#L45

should be - 
minFCToDelay = cms.double(-9999.)  # old TC model! set to 5 for the new one

**Comment by davidlange6** [comment]
Whoops- I forgot my last change. Will fix when I have a network

**Comment by civanch** [comment]
please test

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
seems I got it right this time. 
@abdoulline  - I will merge (as sim already approved).

**Pull request merged**
