### PR TITLE
bsunanda:Run2-TB01 Test beam analysis code

### PR DESCRIPTION
**Pull request by bsunanda**
Beam line counter information is needed to compare detailed distribution of TB06 data with MC. The changes are toward that and an optional ROOT tree is provided for this.

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
@bsunanda , verbose_ variable is not needed if one uses LogInfo or LogDebug. You do not bring new functionality but make code less readable and one should remember how to set this verbosity level.

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
@bsunanda , there are few minor comments to this PR before I can test it:
1. verbose_ variable is not needed, at least in line 84 HcalTB06Analysis.cc it should be removed
 2. Inside run time method HcalTB06Analysis.cc ideally I would left old analysis unchanged and add n-tuple filling in a separate part under boolen variable. Now two type of analysis are mixed and code is less transparent.
3. in modified python files I would avoid redefinition of many parameters from g4SimHits.py - we need perform testing as we do in real production, so only few parameters should be changed, while the majority should be taken from  g4SimHits.py. In particular, RussianRoulette parameters - no sense to rewrite them.

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@civanch I have removed verbose and simplified the examples. The only thing which is mixed is summing up the energies is done in common while filling the tree is rather independent

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
