### PR TITLE
Deal with exception in EventProcessor constructor

### LINKED ISSUE #407: See if exceptions in EventProcessor constructor could be handled better
For an actual case that occurred see https://github.com/cms-sw/cmssw/issues/38125#issuecomment-1142156004

Done in 

- [x] master: https://github.com/cms-sw/cmssw/pull/38144
- [x] 12_4_X: https://github.com/cms-sw/cmssw/pull/38153
- [x] 12_3_X: https://github.com/cms-sw/cmssw/pull/38206

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

If an exception happens in the constructor, delete the object in the order done explicitly in the destructor while the Services are active.

### PR validation:

Code compiles and all framework unit tests pass.

fixes makortel/framework#407

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by wddgit** [comment]
When do we need "CMS_SA_ALLOW" on the try statement? Is it when there is a "catch (...)"? Some places we do this and some places we don't. I had thought it was for the code rule checker, but I am not sure that is correct. One reason I am asking is other code I am working also has "catch(...)". @gartung

**Comment by makortel** [comment]
Good catch @wddgit, indeed the static analyzer should complain on `try` with `catch (...)` without `CMS_SA_ALLOW`.

**Comment by makortel** [comment]
@cmsbuild, please test

For cleaner comparisons

**Comment by makortel** [comment]
+1

**Comment by qliphy** [comment]
merge
RelVals-INPUT error not related

**Pull request merged**
