### PR TITLE
Validation/RecoEgamma Code simplification v1

### PR DESCRIPTION
**Pull request by archiron**
#### PR description:

Here we made some simplification especially with the nimber of "if" tests. We rewite the tests in order to reduce the number but in order to keep the physical presentation into the .CC files.

Some additional update for theconfig test script into the test folder have been made.
there are no expected changes.

#### PR validation:
 compilation is OK, basics tests (scram b runtests or local tests) are OK too.
runTheMatrix.py -l limited -i all --ibeos tests are fine (39 38 37 28 18 4 1 1 1 tests passed, 0 0 0 0 0 0 0 0 0 failed).

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch -> OK.
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html) -> OK.
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html) -> OK.

@beaudett

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
@archiron there are some small changes in some workflows:
https://tinyurl.com/y3jz73hn
https://tinyurl.com/y5lhd4bj
Entries are reduced w.r.t. old (blue), is it expected?
All changes here:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_3_X_2021-12-07-1100+fc1cc4/47318/dqm-histo-comparison-summary.html

**Comment by archiron** [comment]
there was a small bug : 
the `h1_ele_ecalEnergyError_barrel->Fill(bestGsfElectron.correctedEcalEnergyError());` line which was in isEEflag test instead of isEBflag test.
I think there is no pbm now.

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
