### PR TITLE
Cleanup DD Utilities

### PR DESCRIPTION
**Pull request by ianna**
- Use range for vector conversion
- Use std for string conversion

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
@cmsbuild - the errors are unrelated to this PR: DAS Error.

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
