### PR TITLE
updated FastSim treatment of long-lived charginos in the muon system

### PR DESCRIPTION
**Pull request by sbein**
#### PR description:

A few lines in FastSimulation have been updated to allow muon sim tracks to arise from long-lived charginos. The calorimeters and muon system now generate hits and energy depositions as if it the chargino were a muon instead of not at all.

#### if this PR is a backport please specify the original PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
@ssekmen could you please review this PR?

**Comment by ssekmen** [comment]
@fabiocos we still need to do some tests regarding this PR, which is why we are keeping it on hold.
By the way, @sbein is formally the FastSim convener now.  How can we add him to the review chain?  Thanks.

**Comment by fabiocos** [comment]
@ssekmen @sbein I will update cms-bot

**Comment by fabiocos** [comment]
@ssekmen @sbein do we have a conclusion about this PR?

**Comment by sbein** [comment]
The intended change seems fine but there is some lingering issue with how
MET appears in the samples. Hoping to conclude about that in the next days.

**Comment by sbein** [comment]
@fabiocos @ssekmen The issue looks like a problem with the LL recipe using FullSim in CMSSW_11, and not with FastSim. Validation with CMSSW_10 looks ok. This PR is good to go.

**Comment by fabiocos** [comment]
@sbein could you please expand about your conclusions? What is wrong with CMSSW_11? And in any case if this PR is ok for you could you and/or @ssekmen please sign it?

**Comment by sbein** [comment]
@fabiocos the issue was with the FullSim recipe I was using, but not with something internal in CMSSW_11. The mass of the neutralino was a negative number in the slha file and Geant4's call of  pythia was getting confused and setting this to 0. This caused very different kinematics in the final state, which took a while to track down because the recipe doesn't allow you to synchronize the GEN events with FastSim (GEN-SIM HSCP handoff).

**Comment by sbein** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Comment by sbein** [comment]
Hi Sezen,

So we will want these changes to be in the central production of our signal
samples. (I am currently doing private productions so we have something).

I assume this will need to be backported. Will it be best to wait until
Scarlet and Luca confirm which CMSSW version we'll be using before we do
the backport?

Thanks,
Sam

**Pull request merged**
