### PR TITLE
Fix trivial bugs in test (VertexFinder_t.h)

### PR DESCRIPTION
**Pull request by VinInn**
found by ASAN #36057

### CODE REVIEW

**Comment by VinInn** [comment]
@cmsbuild , please test

**Comment by VinInn** [comment]
enable gpu

**Comment by VinInn** [comment]
@cmsbuild , please test

**Comment by slava77** [comment]
+reconstruction

for https://github.com/cms-sw/cmssw/pull/36058	71bc27d
- code changes are following the issue #36057, affecting only RecoPixelVertexing/PixelVertexFinding/test/VertexFinder_t.h
- jenkins tests pass

**Comment by qliphy** [comment]
+1

**Pull request merged**
