### PR TITLE
Better configurations for the DAQ status plots of GEM onlineDQM

### PR DESCRIPTION
**Pull request by quark2**
#### PR description:
I've found that an update on the configurations on some plots is needed to avoid unexpected issues.

It contains updates in #38499 and #38500, which are backports of #38398.

#### PR validation:
Test are done and one can check again by `runTheMatrix` workflows

@jshlee @watson-ij @seungjin-yang

### CODE REVIEW

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by emanueleusai** [comment]
type gem

**Comment by emanueleusai** [comment]
+1

**Comment by perrotta** [comment]
+1
- Bug fix
- Nice to see that the warning below does not show up in RelVal any more:

**Pull request merged**
