### PR TITLE
Extend `convertToRaw` to support different input collection names [13.2.x]

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

The Heavy Ions data use a different collection name for the RAW data, because of the repacking done at HLT.

This PR extends the `convertToRaw` script and its underlying CMSSW configuration to support different input collection names.

#### PR validation:

Tested converting to raw format a Heavy Ions data file from 2018.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport of #42457 to 13.2.x to support the studies for the Heavy Ions data taking.

### CODE REVIEW

**Comment by fwyzard** [comment]
backport #42457

**Comment by fwyzard** [comment]
please test

**Comment by missirol** [comment]
+hlt

**Comment by perrotta** [comment]
+1

**Pull request merged**
