### PR TITLE
Run3 ele ID is added to the cleaned 126 nanoAOD electron module + DQM (Run3 EffArea is applied only to the EGamma supported variables)

### PR DESCRIPTION
**Pull request by rgoldouz**
Hello Experts,

Following my previous PR, 
https://github.com/cms-sw/cmssw/pull/39839 
I have added new run3 electron cutbased ID to the electron module.
The code works like the following,
-Run2ID and Run3ID should be properly saved in the default cutbased variable;
-For Run3 samples, Run2IDs and Iso variables are also added as a backup solution.
-For Run2, only run2ID is saved as default and no extra variable related to the run3 is saved.  

Please let me know your comments.

Thanks,
Reza

@swagata87 @a-kapoor  @DebabrataBhowmik @swertz

### CODE REVIEW

**Comment by swertz** [comment]
Thanks @rgoldouz , on first sight things look good, but can I just ask you to add the new variables to the DQM before I trigger the tests? https://github.com/cms-sw/cmssw/blob/master/PhysicsTools/NanoAOD/python/nanoDQM_cfi.py

**Comment by swertz** [comment]
enable nano

**Comment by swagata87** [comment]
type egamma

**Comment by rgoldouz** [comment]
Hi @swertz ,

I did not add these new Fall17 variables to the DQM code since they are absent when running on run2 samples. Is it OK to add them as default? if no, how should I add them?

Thanks,
Reza

**Comment by swertz** [comment]
> I did not add these new Fall17 variables to the DQM code since they are absent when running on run2 samples. Is it OK to add them as default? if no, how should I add them?


You can customize the DQM content here: https://github.com/cms-sw/cmssw/blob/master/PhysicsTools/NanoAOD/python/nanoDQM_cff.py
E.g. adding the new variables in the DQM by default but removing them for Run2 by doing sth like
```python
_Electron_Run2_plots = cms.VPSet()
for plot in nanoDQM.vplots.Electron.plots:
    if plot.name.value() != ...:
        _Electron_Run2_plots.append(plot)
run2_nanoAOD_ANY.toModify(nanoDQM.vplots.Electron, plots = _Electron_Run2_plots)
```

**Comment by rgoldouz** [comment]
Thanks @swertz ,

I made a new commit including the DQM code and small modification to the new variable names.

Thanks,
Reza

**Comment by swertz** [comment]
please test

**Comment by swertz** [comment]
Thanks for the update @rgoldouz . I'm fine with signing this now, but I'd just like to clarify one last thing: from the DQM I've noticed  changes in those variables in Run3: `miniPFRelIso_chg`, `miniPFRelIso_all`, `jetRelIso`, `mvaTTH` (that uses as input the mini-iso and the `PFIsoAll04`) - which is expected since they now use the Winter22 EA constants.

While for the other isolation and ID variables (`cutBased`, `pfRelIso03`) you made sure to provide both the Fall17V2 and the Winter22V1 versions, it means that those variables will only be provided for Winter22V1 in Run3. 

Also, it means that the TTH MVA uses different inputs from the ones used in the training (but I'm told the electron TTH MVA in nano is not used anymore since more recent trainings are available, so probably this isn't an issue...).

If this indeed is fine from your point of view, we can go ahead with the proposed changes.

**Comment by rgoldouz** [comment]
Hello Sebastien,

Thanks for raising the point.
We just discussed this issue in the EGamma meeting. We think it is better not to touch the user defined variables and only fix the EGamma supported variables.
We think they may also need to use the run3 effArea for run3 isolation calculation. But it should be discussed with them first. Egamma people are writing to them but for not missing the deadline, I just updated the code for not changing the non-Egamma variables.

Thanks,
Reza

**Comment by swertz** [comment]
please test

Ok, thanks for clarifying that. I agree this can be settled later. I note that with your latest changes, the mini-isolation variables (which are not a user-defined variable, are they?) now always use the Fall17 constants, I hope that is desired.

**Comment by swertz** [comment]
please test

**Comment by mandrenguyen** [comment]
@rgoldouz would you mind fixing the PR title, which got a bit mangled, and making it a bit more descriptive?

**Comment by swertz** [comment]
please test

Retrying because of timeouts

**Comment by swertz** [comment]
+1

- Run2 and nanoV10 workflows are not affected
- Run3 workflows have expected differences in electron cutBased and pfRelIso03_all variables; the fallback Fall17V2 variables are present

As previously discussed this is not consistent with what is being done for Run3 photon IDs in nano, but this can be resolved later.

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
