### PR TITLE
TrackingRecHitSoA Classes Clean Up

### PR DESCRIPTION
**Pull request by AdrianoDee**
#### PR description:

Prompted by https://github.com/cms-sw/cmssw/pull/40465#issuecomment-1396326656 fixes the issue. Took the chance to do a minor cleanup of the `TrackingRecHitSoA*` classes. 

Technical PR. No change expected.

### CODE REVIEW

**Comment by AdrianoDee** [comment]
please test

**Comment by fwyzard** [comment]
@AdrianoDee I have mixed feelings about these changes:
  - the removal of `nHits_` replaced by `view().metadata().size()` makes sense
  - the removal of `phiBinnerStorage_` and `cpeParams_` that were unused makes sense
  - I would suggest to keep `offsetBPIX2_` also in the Host class, because I think we should have it there for the Alpaka migration

**Comment by AdrianoDee** [comment]
>I would suggest to keep offsetBPIX2_ also in the Host class, because I think we should have it there for the Alpaka migration

I see your point here, let me restore it.

**Comment by AdrianoDee** [comment]
please abort

**Comment by AdrianoDee** [comment]
please test

**Comment by makortel** [comment]
Commenting here on https://github.com/cms-sw/cmssw/pull/40465#issuecomment-1398160368
> I'm saying _should_ because I don't know if there's something to do to turn on the printouts for those warnings. Is it there?

You can `please test for CMSSW_13_0_LTO_X` or add it to the tests with `- release = CMSSW_13_0_LTO_X` (and since compilation is enough, GPU or special workflows are not needed for that test)

**Comment by AdrianoDee** [comment]
test parameters:
- release = CMSSW_13_0_LTO_X

**Comment by AdrianoDee** [comment]
please test

**Comment by AdrianoDee** [comment]
> You can `please test for CMSSW_13_0_LTO_X` or add it to the tests with `- release = CMSSW_13_0_LTO_X` (and since compilation is enough, GPU or special workflows are not needed for that test)

Thanks!

**Comment by AdrianoDee** [comment]
please test for CMSSW_13_0_LTO_X

**Comment by AdrianoDee** [comment]
It seems it's not working as expected or I'm misspelling something.

**Comment by smuzaffar** [comment]
please test for CMSSW_13_0_LTO_X/el8_amd64_gcc11

**Comment by smuzaffar** [comment]
> It seems it's not working as expected or I'm misspelling something.

ah as we have multiple archs for LTO builds that is why bot was confused which one to use. I will update the configuration to use amd64 arch as default . For now I have triggered the tests by explicitly telling bot to use el8_amd64_gcc11

**Comment by AdrianoDee** [comment]
> > It seems it's not working as expected or I'm misspelling something.
> 
> ah as we have multiple archs for LTO builds that is why bot was confused which one to use. I will update the configuration to use amd64 arch as default . For now I have triggered the tests by explicitly telling bot to use el8_amd64_gcc11

I see, thanks @smuzaffar.

**Comment by clacaputo** [comment]
`Reco comparison results: 65047 differences found in the comparisons`, but just because the baseline used for the comparison hasn't been built with `LTO`. @smuzaffar , is there a way to make the bot compare the results with an `LTO` IB?

**Comment by smuzaffar** [comment]
> `Reco comparison results: 65047 differences found in the comparisons`, but just because the baseline used for the comparison hasn't been built with `LTO`. @smuzaffar , is there a way to make the bot compare the results with an `LTO` IB?

there is nothing which works out of the box but I can force re-build the comparison job to use LTO baseline. I will start it now

**Comment by smuzaffar** [comment]
please test for CMSSW_13_0_LTO_X/el8_amd64_gcc11

lets rerun with latest LTO IB

**Comment by smuzaffar** [comment]
pleae test for CMSSW_13_0_X/el8_amd64_gcc11

lets test it for default/production IB too

**Comment by clacaputo** [comment]
+reconstruction

**Comment by makortel** [comment]
+heterogeneous

**Comment by perrotta** [comment]
+1

**Pull request merged**
