### PR TITLE
gcc7 compilation warning fix in RecoMuon/MuonIsolation package

### PR DESCRIPTION
**Pull request by mrodozov**
Fining compiler warning listed here
https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc6_amd64_gcc700/CMSSW_9_3_X_2017-07-31-1200/RecoMuon/MuonIsolation

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
abort test

**Comment by mrodozov** [comment]
please test

**Comment by perrotta** [comment]
+1
- Technical
- No differences expected in jenkins tests, no differences observed

**Comment by davidlange6** [comment]
+1

**Pull request merged**
