### PR TITLE
L1T Phase2 PFJet a la Phase1 (11_1_X)

### PR DESCRIPTION
**Pull request by rekovic**
#### PR description:

11_1_X: L1T Phase2 PFJets a la Phase1 ("sliding window) reconstruction based on PF (backport of #31606)

- Producer and calibrator (producer of calibrated jets) stored in `reco::CaloJet>` DataFormat
- configurations
- included in L1T Phase2 sequence
- included in FEVTDEBUG Phase2 EventContent
``` 
      'keep *_Phase1L1TJetProducer_*_*',
      'keep *_Phase1L1TJetCalibrator_*_*',
```

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by rekovic** [comment]
backport of #31606

**Comment by rekovic** [comment]
please test

**Comment by silviodonato** [comment]
@rekovic @jmduarte See #31606. Closing this PR.

**Comment by rekovic** [comment]
all comments from the #31606 are ported here

**Comment by rekovic** [comment]
please test

**Comment by rekovic** [comment]
+1

**Comment by silviodonato** [comment]
urgent
for the HLT TDR release (11_1_X)

**Comment by kpedro88** [comment]
+upgrade

**Comment by qliphy** [comment]
+1

**Pull request merged**
