### PR TITLE
HI O2O update: add new parameters and tidy up

### PR DESCRIPTION
**Pull request by bundocka**
- Add required parameters for Heavy Ion running to CaloParamsHelperO2O.h
- Add required functions to L1TCaloParamsOnlineProd.cc
- Add demux LUTs to convertParamsToOnlineFormat.py (not specific to HI)
- Tidy up code so that parameter comparison between files is clearer

### CODE REVIEW

**Comment by rekovic** [comment]
please test

**Comment by rekovic** [comment]
@bundocka 
Please also provide a backport PR to 10_3_X.

**Comment by rekovic** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
