### PR TITLE
Add another excluded era for displaced muons

### PR DESCRIPTION
**Pull request by perrotta**
This is an attempt to solve the unit test failure in `testTauEmbeddingProducers` that showed up after the merging of #37805, as notified in https://github.com/cms-sw/cmssw/pull/37805#issuecomment-1126923256

Disclaimer: I am not able to test it now (sunday afternoon, etc.), but to speed up I let bot doing it, something which is not very efficient during working days when I have all computing facilities available, but it could speed up things now that we are otherwise ready to build CMSSW_12_4_0_pre4

### CODE REVIEW

**Comment by perrotta** [comment]
test parameters:
- TauAnalysis/MCEmbeddingTools

**Comment by perrotta** [comment]
test parameters:
- cms-addpkg TauAnalysis/MCEmbeddingTools

**Comment by perrotta** [comment]
test parameters:
- cms-addpkg = TauAnalysis/MCEmbeddingTools

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
`testTauEmbeddingProducers` succeeds now!
@cms-sw/reconstruction-l2 do you see any issue with the proposed solution?

**Comment by perrotta** [comment]
urgent

**Comment by perrotta** [comment]
+1
- This fixes the error in the `testTauEmbeddingProducers` unit test reported in https://github.com/cms-sw/cmssw/pull/37805#issuecomment-1126923256
- Let merge it, and have a clean pre-release
- If a more convenient solution will be found, it will be merged as "bug fix" after pre4

**Comment by perrotta** [comment]
merge

**Comment by jfernan2** [comment]
+1 (for the records)

**Pull request merged**
