### PR TITLE
Update PUPPI configuration parameters.

### PR DESCRIPTION
**Pull request by hsatoshi**
PUPPI configuration parameter has been updated.
The PT threshold on neutral particles in the region |eta|=3-10 is now set to the same value as 76x tuning.

Mentioned at a meeting : 
https://indico.cern.ch/event/537458/

@nhanvtran @violatingcp

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
simple updates don't need to be rebased to the head of a development branch.
this PR tests will have to wait until a new IB comes out.

**Comment by hsatoshi** [comment]
I am sorry for naive questions.
What I have been supposed to do,
 and what can I do this time ?

**Comment by slava77** [comment]
On 6/16/16 6:47 AM, hsatoshi wrote:
> I am sorry for naive questions.
> What I have been supposed to do,
> and what can I do this time ?
> 

nothing to do now.

Just use an existing release , git checkout -b , git push

from the context it looks like you added git checkout CMSSW_8_1_X or
something like
http://cms-sw.github.io/faq.html#how-do-i-make-sure-my-topic-branch-is-updated-with-the-latest-developments

**Comment by hsatoshi** [comment]
Thank you.

Shall we withdraw this PR and send another PR based on some release (is CMSSW_8_1_0_pre7  a good one ?)
 or will this PR be taken into account (semi)automatically at some point?

**Comment by slava77** [comment]
On 6/16/16 7:16 AM, hsatoshi wrote:
> Thank you.
> 
> Shall we withdraw this PR and send another PR based on some release (is
> CMSSW_8_1_0_pre7 a good one ?)
> or will this PR be taken into account (semi)automatically at some point?
> 

as I said already, do nothing this time.

**Comment by slava77** [comment]
@cmsbuild please test
new IB is out, although in other PRs there were build errors due to cvmfs. So, chances are the tests can fail for another reason.

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/14901	43d4909
- changes are only in the configuration, in line with the description
- jenkins tests pass and show differences only in PUPPI-related quantities
- Looking at wf 25202 (ttbar with PU35, using 810pre6 relval RECO as input) with ~3K events processed to get better stats, changes are roughly as expected.

fairly significant change in puppi jets up to pt 40 GeV, expected from the increased thresholds
all_test14901-patvsorig-pat_ttbarpuwf25202p0c_log10patjets_slimmedjetspuppi__dqm_obj_et
mostly in the HF region
all_test14901-patvsorig-pat_ttbarpuwf25202p0c_patjets_slimmedjetspuppi__dqm_obj_eta

jet response is down, but this will be corrected back
wf25202_pupj_ptcorovergen_eta

jet mass is down as well in the forward by apparently  a bit more than the jet response. This may need a follow up.
wf25202_pupj_f_mrecovergen


puppi MET is almost unchanged by value; sumET decreases and non-HF fractions increase due to decrease of the HF contribution (expected)

**Pull request merged**
