### PR TITLE
DQM: Remove concurrent-lumi blocking DQM Modules.

### PR DESCRIPTION
**Pull request by schneiml**
#### PR description:

This PR removes (some?) of the remaining modules blocking concurrent lumisections in production jobs.

I ran a random 136 relval with concurrent lumis enabled and got these modules reported:

```
  RPCDcsInfo rpcDcsInfo
  DetStatus ALCARECOTkAlMinBiasDCSFilter
  EcalDQMonitorTask ecalMonitorTask
  ESIntegrityTask ecalPreshowerIntegrityTask
  L1TStage2CaloLayer1 l1tStage2CaloLayer1
  AlcaBeamMonitor AlcaBeamMonitor
```

(Update: `DetStatus` is gone (thanks @mmusich !), and after #30187, `EcalDQMonitorTask` is gone as well. `ESIntegrityTask` remains, however.)

`DetStatus` is not DQM related, I removed the others from the sequences. There might be more modules that are not used in this specific workflow.

Overall, some of these modules are quite important and we don't want to merge this PR. But it gives an idea of what these modules do and allows to try actually enabling concurrent lumis.

(@silviodonato update: 
`RPCDcsInfo rpcDcsInfo ` updated with #31056 
`ALCARECOTkAlMinBiasDCSFilter` -> updated with #30124
)

#### PR validation:

None, so far; not supposed to be merged for now.

### CODE REVIEW

**Comment by schneiml** [comment]
please test

**Comment by silviodonato** [comment]
@schneiml shall we include this in CMSSW_11_2_0_pre1?

**Comment by schneiml** [comment]
@silviodonato no, we need at least Ecal properly fixed before this can go in (@tanmaymudholkar ?)

Then, we also need a proper fix or removal for `  DetStatus ALCARECOTkAlMinBiasDCSFilter` before this can even be used for experiments with concurrent lumis.

**Comment by schneiml** [comment]
hold

**Comment by mmusich** [comment]
@schneiml 

> Then, we also need a proper fix or removal for DetStatus ALCARECOTkAlMinBiasDCSFilter before this can even be used for experiments with concurrent lumis.

I took care of that here: https://github.com/cms-sw/cmssw/pull/30124

**Comment by schneiml** [comment]
@mmusich great, thanks!

**Comment by tanmaymudholkar** [comment]
Hi @schneiml , @silviodonato  thanks for the patience... I am currently running the test matrix workflow on a fix that should solve this, I plan to make a PR within a few hours.

**Comment by tanmaymudholkar** [comment]
FYI I just made a new PR that I hope fixes the issue for ECAL: https://github.com/cms-sw/cmssw/pull/30187

**Comment by schneiml** [comment]
Rebased to recent IB, with #30187 below. I can now run DQM with concurrent lumis! Not sure if EDM does in fact use them though, on the tiny `runTheMatrix` samples.

I added a commit to force-on concurrent lumis in the PR test. Then, we can check how many WFs could actually use concurrent lumis and if anything serious changes in the output already (I hope not). This is not a very strong test though, given that the PR tests rarely process more than one lumi.

**Comment by schneiml** [comment]
please test

**Comment by gennai** [comment]
Hi, I have started to look at the AlCaBeamMonitor. In order to see how the histograms are filled in the present code, could somebody share the recipe on how to run the DQM step for this module? I have tried with some python file in the test directory but I am not sure about the results and I would like to double check ...

Thanks,
S.

**Comment by jfernan2** [comment]
Hi, I guess you are using something similar to DQM/BeamMonitor/test/Alca_BeamMonitor_DQM.py which looks quite old, but only runs what you want.
For a standard workflow, anyone running @common or @standardDQM is making use of BeamMonitor, like 140.56 or 136.874
You can compare the output before and after your changes with (e.g.) https://github.com/cms-sw/cmssw/blob/master/DQMServices/FileIO/scripts/compareDQMOutput.py  to see if you get the desired output.

HTH

**Comment by gennai** [comment]
I think I have kind of understood how to modify the code for the AlcaBeamMonitor (it is not going to be simple ...) but I have one more question which may imply even further changes:
Is
DQMStore::IBooker::UseLumiScope

supposed to work with DQMOneEDAnalyzer?
I would need an histogram to be filled per each LS not just the last one and in the DQMEDAnalyzer the UseLumiScope was used. Now if I used it I got a crash with the error message that the ME has no backed data ...

Thanks again for the help,
S.

**Comment by silviodonato** [comment]
Status: waiting for  #30187

> Rebased to recent IB, with #30187 below. I can now run DQM with concurrent lumis! Not sure if EDM does in fact use them though, on the tiny `runTheMatrix` samples.
> 
> I added a commit to force-on concurrent lumis in the PR test. Then, we can check how many WFs could actually use concurrent lumis and if anything serious changes in the output already (I hope not). This is not a very strong test though, given that the PR tests rarely process more than one lumi.

**Comment by silviodonato** [comment]
please test
to update the list of https://github.com/cms-sw/cmssw/issues/25090#issuecomment-665681777

**Comment by silviodonato** [comment]
please test

**Comment by silviodonato** [comment]
If I understand correctly,
`RPCDcsInfo rpcDcsInfo` has been updated with #31056
`ALCARECOTkAlMinBiasDCSFilter` has been updated with #30124
`AlcaBeamMonitor` will be updated with #31354.

This means that after having merged #31354 the list of the offending modules will be
```
  EcalDQMonitorTask ecalMonitorTask
  ESIntegrityTask ecalPreshowerIntegrityTask
  L1TStage2CaloLayer1 l1tStage2CaloLayer1
```

After having merged #31354, I would suggest @cms-sw/dqm-l2 to update this PR, re-adding the modules that have been migrated.

**Comment by makortel** [comment]
> `AlcaBeamMonitor` will be updated with #31354.

It seems to me that wrt. concurrent lumis `AlcaBeamMonitor` was updated in https://github.com/cms-sw/cmssw/pull/31267 (#31354 only fixes a crash in case no lumis were processed).

**Comment by gennai** [comment]
yes, at least I think I have fixed it (well I have followed the guidelines maybe I made something wrong?)

**Comment by silviodonato** [comment]
> > `AlcaBeamMonitor` will be updated with #31354.
> 
> It seems to me that wrt. concurrent lumis `AlcaBeamMonitor` was updated in #31267 (#31354 only fixes a crash in case no lumis were processed).

yes, thanks.
@cms-sw/dqm-l2 could you update this pull request removing *only* 
```
  EcalDQMonitorTask ecalMonitorTask
  ESIntegrityTask ecalPreshowerIntegrityTask
  L1TStage2CaloLayer1 l1tStage2CaloLayer1
```
?

**Comment by jfernan2** [comment]
@silviodonato the owner of this PR is no longer in CMS (@schneiml ), so I understand I cannot modify this PR. I may create a new equivalent on Monday once I come back from Holidays if it is still on time. Thanks

**Comment by silviodonato** [comment]
> @silviodonato the owner of this PR is no longer in CMS (@schneiml ), so I understand I cannot modify this PR. I may create a new equivalent on Monday once I come back from Holidays if it is still on time. Thanks

Yes, sure. Thanks @jfernan2 !

**Comment by jfernan2** [comment]
@silviodonato I managed to get a stable connection and made the PR, so you can close this one.
https://github.com/cms-sw/cmssw/pull/31369

**Comment by silviodonato** [comment]
@jfernan2 thank you!

**Pull request closed without merging**
