### PR TITLE
Address undefined behavior as reported by UBSAN in CSC and GEM L1T producers

### PR DESCRIPTION
**Pull request by dildick**
#### PR description:

In response to https://github.com/cms-sw/cmssw/issues/35010

#### PR validation:

Ran WF 136.751 that was reporting the issue.

Also tested it on 10k cosmic muons from a July run with the B904 ME1/1 test-stand. Results look very good (and unchanged).
[CSC_dataVsEmul_B904_Cosmic_Run_210701_135109_10k.pdf](https://github.com/cms-sw/cmssw/files/7108030/CSC_dataVsEmul_B904_Cosmic_Run_210701_135109_10k.pdf)

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by qliphy** [comment]
test parameters:
-     workflow = 136.751
-     release = CMSSW_12_1_UBSAN_X

**Comment by qliphy** [comment]
please test

**Comment by smuzaffar** [comment]
please test
run default PR tests too

**Comment by smuzaffar** [comment]
please test for CMSSW_12_1_X

**Comment by dildick** [comment]
5 failures from messagelogger in WF 312.0. Remaining failures from 11634.911

**Comment by qliphy** [comment]
please test

**Comment by dildick** [comment]
@qliphy Can you rerun the tests, please?

**Comment by perrotta** [comment]
@cmsbuild please test

**Comment by dildick** [comment]
hold (until behavior of TeV muons in CMSSW_12_0_0_pre6 is understood)

**Pull request closed without merging**
