### PR TITLE
HLT tools: improve support for ConfDB v2

### PR DESCRIPTION
**Pull request by fwyzard**
- update documentation
- fix choice of ConfDB v2 by default
- add support for the schema and database to hltIntegrationTest --setup

### CODE REVIEW

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
+1

**Comment by fwyzard** [comment]
+1

**Comment by fwyzard** [comment]
please test

**Comment by davidlange6** [comment]
+1

**Pull request merged**
