### PR TITLE
Enhance PixelTrack SoA DQM monitoring

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

Follow-up to https://github.com/cms-sw/cmssw/pull/36392:
   * 74a2a3701c6b48fb926b024b34ad9914ed2eff13 adds n. layers histogram to `SiPixelPhase1MonitorTrackSoA` (as suggested at https://github.com/cms-sw/cmssw/pull/36392#issuecomment-988678177);
   * ff1be40103a04aecfca15dba1fec37d49a5438a4 adds profiles of # hits, # layers and chi2 vs track eta/phi;

#### PR validation:

Run `runTheMatrix.py --what gpu -l 11634.506` on a lxplus-gpu node.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Not a backport, but it will be backported to 12_2_X together with https://github.com/cms-sw/cmssw/pull/36392

### CODE REVIEW

**Comment by mmusich** [comment]
enable gpu

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by jfernan2** [comment]
+1
Plots added and filled as expected

**Comment by qliphy** [comment]
+1

**Pull request merged**
