### PR TITLE
Phase2-hgx171 Streamline one function in HGCal geometry

### PR DESCRIPTION
**Pull request by bsunanda**
Avoids repeating the same code

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild please test

**Comment by kpedro88** [comment]
please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
Close this PR and the bug fix part is transferred to #25264. Shall investigate the issues of missing hits later

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by ianna** [comment]
+1

**Comment by bsunanda** [comment]
@kpedro88 Can you approve this - after this is integrated I shall take a look at the bug fix issue

**Comment by kpedro88** [comment]
+upgrade

**Comment by fabiocos** [comment]
please test

**Comment by bsunanda** [comment]
@fabiocos Could you please merge this - there is a bug fix PR waiting after this PR

**Comment by bsunanda** [comment]
@fabiocos COuld you please merge this PR to the master?

**Comment by fabiocos** [comment]
+1

HGCal geometry v9 should not be affected by this code update

**Pull request merged**
