### PR TITLE
update relval recycle strings of 10_3_0_pre5

### PR DESCRIPTION
**Pull request by zhenhu**
including the strings to recycle with the new PREMIX datatier
/RelValFS_PREMIXUP15_PU25/CMSSW_10_3_0_pre5-PU25ns_103X_mcRun2_asymptotic_v1_FastSim-v1/PREMIX
/RelValPREMIXUP18_PU25/CMSSW_10_3_0_pre5-PU25ns_103X_upgrade2018_realistic_v7-v1/PREMIX

https://github.com/cms-sw/cmssw/pull/24184#issuecomment-424652006

### CODE REVIEW

**Comment by zhenhu** [comment]
please test

**Comment by zhenhu** [comment]
please test

**Comment by fabiocos** [comment]
@zhenhu @prebello this PR is supposed to fix the failing workflows due to the new PREMIX format, am I correct?

**Comment by fabiocos** [comment]
please test workflow 250200.0,250202.118,500200.0

**Comment by zhenhu** [comment]
> @zhenhu @prebello this PR is supposed to fix the failing workflows due to the new PREMIX format, am I correct?

Yes, it is.

**Comment by zhenhu** [comment]
> @zhenhu it looks like this PR is fixing just part of the old input files. Are you expecting the erst to be provided in a separate PR? Are they still being produced?

250200.0 requires an 90X version of premix input /RelValPREMIXUP15_PU25/CMSSW_9_0_0_pre4-PU25ns_90X_mcRun2_asymptotic_v1-v1/PREMIX, which we haven't produced. 

250202.118 works fine because the premix input has been produced in 10_3_0_pre5

**Comment by zhenhu** [comment]
Hi @fabiocos , do we really want to change these premix inputs even for the old releases? 
https://github.com/cms-sw/cmssw/pull/24184/files#diff-819af2ec677272fddf1fef50e788a88bR1389
https://github.com/cms-sw/cmssw/pull/24184/files#diff-819af2ec677272fddf1fef50e788a88bL1410
If so, we may have to reproduce these files in 90X and 81X

**Comment by makortel** [comment]
Would producing the MinBias GEN-SIM and the premix library for 2015 50 ns, 2016, and 2017 in 10_3_0_pre5 be a viable option? I suppose the workflows do not specifically want a 81X/90X/100X sample, but those weer just the last (pre)releases where a pileup library was produced.

**Comment by fabiocos** [comment]
@makortel @zhenhu I would expect that we are capable to produce relval samples for older years in the latest release, at least for Run2, as Matti proposes. Otherwise I do not understand the meaning of these tests. Conditions might not be the optimal ones from the physics point of view, but we want to ensure that at least we are capable of technically run them. As of now these workflows are just not functional, and therefore totally useless.

**Comment by zhenhu** [comment]
Premix library for 2015, 2016, and 2017 produced:
/RelValPREMIXUP15_PU25/CMSSW_10_3_0_pre5-PU25ns_103X_mcRun2_asymptotic_v1-v1/PREMIX
/RelValPREMIXUP15_PU50/CMSSW_10_3_0_pre5-PU50ns_103X_mcRun2_startup_v1-v1/PREMIX
/RelValPREMIXUP17_PU25/CMSSW_10_3_0_pre5-PU25ns_103X_mc2017_realistic_v1-v1/PREMIX

**Comment by zhenhu** [comment]
please test workflow 250200.0,500200.0,250202.17

**Comment by zhenhu** [comment]
+1

**Comment by fabiocos** [comment]
@kpedro88 could you please check and sign it?

**Comment by kpedro88** [comment]
+upgrade

**Comment by fabiocos** [comment]
+1

**Pull request merged**
