### PR TITLE
HGCal EGamma Fake Control - Cluster Hadronic Energy Fraction Cut

### PR DESCRIPTION
**Pull request by lgray**
Adds a cut for ECAL driven electron seeds that requires the fraction of the seed cluster energy that's in the hadron sections of the HGCal to not exceed 0.15.

This causes a significant reduction in the number of GSF tracks that are seeded by the HGCal.
Timing measurements are in progress.

### CODE REVIEW

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
Looking at PU200 D4 ttbar
ecalDrivenElectronSeeds time goes down by a factor of about 5, allConversions by about 2.4, and pfTrackElec by about 2.
```
delta/moduleMean  delta/jobMean   baseline           PR       module
   -1.341217     -21.94%   3230 s/ev ->    637 s/ev ecalDrivenElectronSeeds
   -0.830923     -11.56%   2328 s/ev ->    961 s/ev allConversions
   -0.659140      -3.30%    787 s/ev ->    397 s/ev pfTrackElec
```
the total of these three modules alone is still twice the total budget estimates for the production needs.
To appropriately fit the budget another factor of 4 on these modules in total will be needed.

**Comment by lgray** [comment]
@slava77 OK there are more loose background rejection cuts that can be used. I will make additions to this PR.

**Comment by slava77** [comment]
Given the kinds of operations that dominate a few of these, savings may be just in better code
For ecalDrivenElectronSeeds
https://slava77sk.web.cern.ch/slava77sk/reco/cgi-bin/igprof-navigator/CMSSW_8_1_X_2016-11-03-1100-sign792-2023D4PU200-21224.0.step3.mt1.pp/46

For pfTrackElec
https://slava77sk.web.cern.ch/slava77sk/reco/cgi-bin/igprof-navigator/CMSSW_8_1_X_2016-11-03-1100-sign792-2023D4PU200-21224.0.step3.mt1.pp/86

For the allConversions the solution may be less simple to implement:
https://slava77sk.web.cern.ch/slava77sk/reco/cgi-bin/igprof-navigator/CMSSW_8_1_X_2016-11-03-1100-sign792-2023D4PU200-21224.0.step3.mt1.pp/36
probably a specialization of 
KinematicConstrainedVertexFitterT<2, 2>:: .. and maybe even more simple given the constraint applied there should have simpler math (IIRC CDF's CTVMFT had no iterations for this problem)

**Comment by lgray** [comment]
@slava77 do you have a plot of the electron multiplicity vs eta, could you post one here? (before/after patch, 200PU if possible)

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by VinInn** [comment]
one can try to reimplement  ```KinematicConstrainedVertexFitterT``` using eigen
Often a new compiler version made factor 2 difference with SMatrix...

**Comment by VinInn** [comment]
Let's ger rid of ```edm::reftobase``` from ElectronSeedGenerator!

**Comment by lgray** [comment]
@VinInn I think the major driver is still the electron seeding in HGCal producing too many fakes. This then causes the conversions to go wild. I think the stopgap I will do for now is to turn off the electron override for conversions while we implement better preselection cuts for electrons (there are better than cluster hadronic fraction). Will check soon that this helps.

**Comment by lgray** [comment]
@VinInn Fixing the pass-by-value in reco::ElectronSeed will probably help most of the slow down (according to IgProf).

**Comment by VinInn** [comment]
adding ```const &``` to ``` CaloClusterRef caloCluster() const { return caloCluster_ ; }```?
good idea!
still, would be even better to return just the reference or even use a plain pointer....

**Comment by VinInn** [comment]
there is also some sort of reftobase to ```TrajectorySeed``` going around by value...

**Comment by lgray** [comment]
@VinInn yes - already fixed

**Comment by davidlange6** [comment]
yes - noted previously to the experts..

**Comment by lgray** [comment]
@cmsbuild please test

This last addition removes the issue of ```allConversions``` as a stop gap, by removing the pass-thru for electrons in that producer.

Per-events times should be much more reasonable now.

**Comment by slava77** [comment]
in the diffs:
ecalDrivenGsfElectrons:
previous ver
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_9_0_X_2016-11-29-1100+16800/17240/validateJR/all_OldVSNew_TTbar14TeV2023D4wf21234p0/all_OldVSNew_TTbar14TeV2023D4wf21234p0c_recoGsfElectrons_ecalDrivenGsfElectrons__RECO_obj_hcalOverEcal.png
this version
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_9_0_X_2016-11-30-1100+16800/17260/validateJR/all_OldVSNew_TTbar14TeV2023D4wf21234p0/all_OldVSNew_TTbar14TeV2023D4wf21234p0c_recoGsfElectrons_ecalDrivenGsfElectrons__RECO_obj_hcalOverEcal.png

with more stats in the seeds
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_9_0_X_2016-11-29-1100+16800/17240/validateJR/all_OldVSNew_TTbar14TeV2023D4wf21234p0/all_OldVSNew_TTbar14TeV2023D4wf21234p0c_recoElectronSeeds_electronMergedSeeds__RECO_obj_hoe1.png
vs now
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_9_0_X_2016-11-30-1100+16800/17260/validateJR/all_OldVSNew_TTbar14TeV2023D4wf21234p0/all_OldVSNew_TTbar14TeV2023D4wf21234p0c_recoElectronSeeds_electronMergedSeeds__RECO_obj_hoe1.png

the fraction of h/e~0 is apparently much larger now (can't exclude a fluctuation though)
the only physics change was in allConversions. Did it cause it or is more likely a fluc?

**Comment by lgray** [comment]
Fraction of h/e ~0 should be smaller now by definition....

**Comment by lgray** [comment]
Hmm, indeed this looks more like a fluctuations. Given the errors.

**Comment by slava77** [comment]
On 11/30/16 1:19 PM, Lindsey Gray wrote:
> Fraction of h/e ~0 should be smaller now by definition....

Just to clarify, in case.
I was looking at the red in both cases.
(black/baseline is clearly at 0 by old construction)

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
Just to summarize from skype chats:

```ecalDrivenElectronSeeds``` is now down ~10x compared to the beginning
```allConversions``` without the gsf override is down 40-60x compared to the beginning
```pfTrackElec``` was missed on the first round but should go down another factor 2 or better.

**Comment by lgray** [comment]
@VinInn The other major time sink in ```PFElecTkProducer``` is the MultiTrajectoryStateTransform which spends a rather large fraction of its time evaluating gaussian pdfs and finding modes. The gaussian PDF should be something we can optimize.... Think it is advisable to try vdt here instead of ROOT::Math stuff?

If so I will make separate PR.

**Comment by VinInn** [comment]
@lgray, yes MultiTrajectoryState can be "further" optimized....
it is all double precision, using vdt should help. in some cases going to float may also advisable....
If you wish to try please do so.

**Comment by VinInn** [comment]
In any case, comparing Slava's igprof vs Erica's tracking-only one, I am more and more convinced that problems originate in the "new" forward disks.
I suspect we should separate the two (three?) regions and use very different cuts (algorithms) in the barrel, endcap and very-forward

**Comment by slava77** [comment]
On 12/1/16 1:15 AM, Lindsey Gray wrote:
> @VinInn <https://github.com/VinInn> The other major time sink in
> |PFElecTkProducer| is the MultiTrajectoryStateTransform which spends a
> rather large fraction of its time evaluating gaussian pdfs and finding
> modes. The gaussian PDF should be something we can optimize.... Think it
> is advisable to try vdt here instead of ROOT::Math stuff?
> 
> If so I will make separate PR.


Note that the logic of the code is N*N loop which contains inside the
same computation for the same N tracks
done N times.
Speeding up the code that does the computation is one thing, but maybe
not repeating the same N times is easier.

**Comment by slava77** [comment]
after the last updates, on 50 PU200 events in D4 I see that allConversions is now small enough to be invisible in the total.
The ecalDrivenElectronSeeds (280 s) + pfTrackElec (390 s) are now just under 50% of the total budget.
Maybe another igprof run for them will clarify what's up.

I'll wrap up with the diffs in plots and if nothing bad shows up, this PR can move on as is.

**Comment by slava77** [comment]
just to compare with 2016 PU35: ecalDrivenElectronSeeds (34 ms) + pfTrackElec (26 ms) add up to just 0.35% of reco time. So, the slope vs PU is pretty steep.

**Comment by VinInn** [comment]
@slava, is not necessarely  only PU, it  is also new Pixels for eta>2.5....

**Comment by lgray** [comment]
@cmsbuild please test

the igprof was a little confusing. I've found the pass-by-value that was causing that function to explode. However, checks out 300 packages (had to touch reco::Track).

**Comment by slava77** [comment]
some plots with PU200 as of 4c91c95

all_sign803-local-pass-4c91c95vsorig-local_2023d4pu200mt10wf21224p0c_recogsftracks_electrongsftracks__reco_obj_eta

all_sign803-local-pass-4c91c95vsorig-local_2023d4pu200mt10wf21224p0c_recogsfelectrons_ecaldrivengsfelectrons__reco_obj_eta
the barrel is clearly cleaner. What are the chances this gets ~ flat?

gedGsfElectrons as well as particleFlowEGamma and particleFlow essentially do not change because non-barrel PF is derived from MC truth (simPFProducer).

**Comment by lgray** [comment]
@slava77 Chances are that we can make the endcaps more under control on a week timescale, it needs a quick dedicated study.

**Comment by lgray** [comment]
@slava77 However, if we are moderately under control in terms of time with these newer additions I suggest we cut a release and move forward.

**Comment by slava77** [comment]
On 12/1/16 2:09 PM, Lindsey Gray wrote:
> @slava77 <https://github.com/slava77> However, if we are moderately
> under control in terms of time with these newer additions I suggest we
> cut a release and move forward.

I think we are, at least on the egamma side.

Based on the first few events pfTrackElec time is down by another x3.

**Comment by slava77** [comment]
In ZEE sample, no PU

all_sign803-pass-4c91c95-histatvsorig-histat_zee14tev2023d4wf21246p0c_recogsfelectrons_ecaldrivengsfelectrons__reco_obj_pt
looks like the drop is in the right place
efficiency is confirmed with MTV
wf21246_elegsf_eff_pt

In QCD600to800 D4 (wf 21253)
the efficiency is roughly OK as well
wf21253_elegsf_eff_pt

**Comment by slava77** [comment]
Combined  (full PR) reduction in PU200 D4 on 50 events:

```
delta/mean     delta/meanJob   baseline               PR
   -1.973903     -19.57%   2328 s/ev ->     15 s/ev allConversions
   -1.664710     -24.83%   3230 s/ev ->    296 s/ev ecalDrivenElectronSeeds
   -1.399018      -5.48%    787 s/ev ->    139 s/ev pfTrackElec
   -1.227078      -0.19%     30 s/ev ->      7 s/ev pfTrack
   -0.601380      -0.35%     89 s/ev ->     48 s/ev electronCkfTrackCandidates
   -0.581438      -0.12%     31 s/ev ->     17 s/ev gsfGeneralInOutOutInConversionTrackMerger
   -0.448080      -0.18%     60 s/ev ->     38 s/ev electronGsfTracks
```
The total reduction is about 6E3 s/ev

- Memory goes down by about 0.4 GB/thread
- FEVT event size, the current step3 output is down by 25%.

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/16800 8a315d6
- update selections and improve code to speedup phase-2 PU200 workflows with HGCAL
- jenkins tests pass and comparisons with baseline show differences only in 2023 workflows with HGCAL
- local tests show 
    - a significant reduction in CPU, down to somewhat acceptable level, although further improvements would be nice by pre2
    - changes in physics observables look consistent with mostly fake rejection

**Comment by lgray** [comment]
FYI The unit test failure is due to a missing file. Nothing related to this PR.

@davidlange6 Please merge ASAP.

**Comment by davidlange6** [comment]
its one of our favorite unit tests...

**Pull request merged**
