### PR TITLE
HLT menu development for `12_4_X` (1/N)

### PR DESCRIPTION
**Pull request by missirol**
backport of #38107

#### PR description:

Development of HLT menus for `CMSSW_12_4_X`.

Includes the integration of the following JIRA tickets.

  - [CMSHLT-2275](https://its.cern.ch/jira/browse/CMSHLT-2275): [TAU] Update of thresholds in TAU triggers for Run 3 
  - [CMSHLT-2280](https://its.cern.ch/jira/browse/CMSHLT-2280): [EXO] New triggers for LLP searches (L1SingleJetLLP, soft di-electrons) 
  - [CMSHLT-2301](https://its.cern.ch/jira/browse/CMSHLT-2301): [MUO,EXO] Triggers with new displaced-muon reconstruction.
  - [CMSHLT-2302](https://its.cern.ch/jira/browse/CMSHLT-2302): [TSG] Updates to reduce per-event size of Scouting stream 
  - [CMSHLT-2305](https://its.cern.ch/jira/browse/CMSHLT-2305): [B2G] Update of DeepJet WP in HT+5Jet+2BTag triggers 
  - [CMSHLT-2308](https://its.cern.ch/jira/browse/CMSHLT-2308): [BPH] Update of triggers for Tau->3Mu search (new L1T seed for Run 3)
  - [CMSHLT-2319](https://its.cern.ch/jira/browse/CMSHLT-2319): [TSG] Re-align STORM menus with updates introduced online by FOG (includes [CMSHLT-2322](https://its.cern.ch/jira/browse/CMSHLT-2322))

#### PR validation:

TSG tests.

#### If this PR is a backport, please specify the original PR and why you need to backport that PR:

#38107

Development of HLT menus for 2022 pp data-taking.

### CODE REVIEW

**Comment by missirol** [comment]
enable gpu

**Comment by missirol** [comment]
please test

**Comment by missirol** [comment]
+hlt
  - generally no differences in PR-tests outputs, as expected (the HLT menu used in RelVals was recently changed to the "2022 V1.1" frozen HLT menu, which is not modified by this PR)
  - some residual differences in GPU wfs are attributed to non-reproducibility of outputs on GPU

**Comment by qliphy** [comment]
+1

**Pull request merged**
