### PR TITLE
Enable services in concurrent endJob processing

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

The service system was not being enabled in the new concurrent tasks.

#### PR validation:

Code compiles.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
Please test

**Comment by qliphy** [comment]
Thanks @Dr15Jones   
I have tested with CMSSW_12_1_X_2021-09-01-2300 + this PR
and it works well with "runTheMatrix.py -l 200 --job-reports -t 4 --ibeos"

**Comment by qliphy** [comment]
type bugfix

**Comment by qliphy** [comment]
urgent

**Comment by smuzaffar** [comment]
@qliphy if this fixes the massive relvals errors then I would suggest to ignore the INPUT error and merge it before 11AM

**Comment by smuzaffar** [comment]
ah there are "DQMHistoTests: Total failures: 1334" comparison failure,

**Comment by qliphy** [comment]
> ah there are "DQMHistoTests: Total failures: 1334" comparison failure,

It seems to be from https://github.com/cms-sw/cmssw/pull/34805
and are as expected.

**Comment by makortel** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
