### PR TITLE
Moved PFClusterProducer from beginLuminosityBlock to beginRun

### PR DESCRIPTION
**Pull request by jsamudio**
#### PR description:

This is a follow-up to #33652. Functions in PFClusterProducer were sectioned by luminosity block, but this was unnecessary so a change was made to section by run.

#### PR validation:

`runTheMatrix.py -l limited -i all --ibeos` performed and passed

Additionally performed PF specific [validation](https://hep.baylor.edu/jsamudio/beginRunPFVal/plots/)

@hatakeyamak @juska @kdlong

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by mandrenguyen** [comment]
type pf

**Comment by mandrenguyen** [comment]
+reconstruction
Simply calls an ESProducer less frequently. 
No changes to comparisons, as expected.

**Comment by rappoccio** [comment]
+1

**Pull request merged**
