### PR TITLE
adding option to preserve the order of the direct dependences : 120X

### PR DESCRIPTION
**Pull request by Sam-Harper**
#### PR description:

In PR https://github.com/cms-sw/cmssw/pull/32754, the output of directDependences was changed such that it was grouped by type (ie module, sequence). 

It is useful for my code that I get the order they occur on the sequence. Therefore I propose the simplest solution of adding an option to the function such that this old behaviour can be supported. 

#### PR validation:

directDependences output is unchanged by default. The previous ordering is recovered when the bool is set false.

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
FYI @fwyzard (since you developed the functionality)

If I'm not mistaken this functionality is still missing tests. (but I won't require them in this PR)

**Comment by makortel** [comment]
+1

Differences are fixed by #34409

**Comment by qliphy** [comment]
+1

**Pull request merged**
