### PR TITLE
Run2-hcx140 Backport PR's #19574 and #20049 which provides two HLT filters (1) for selecting multiple L1 objects; (2) Laser firing in HCAL

### PR DESCRIPTION
**Pull request by bsunanda**
Add two filters (1) for selection on multiple types of L1 objects; (2) Laser fire in HCAL. Back port the two PR's #19574 and #20049

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by davidlange6** [comment]
hi @bsunanda - please change the title of this PR to be descriptive of the changes included. thanks

**Comment by davidlange6** [comment]
ping

**Comment by Martin-Grunewald** [comment]
@bsunanda 
Sunanda, can you please address the comment above?
Thanks!

**Comment by bsunanda** [comment]
@Martin-Grunewald @davidlange6 modified title and description

**Comment by davidlange6** [comment]
+1

**Pull request merged**
