### PR TITLE
Fixing Default Values of EgammaHLTGsfTrackVarProducer to be only used if there is a track found : 101X

### PR DESCRIPTION
**Pull request by Sam-Harper**
10_1_X flavour of https://github.com/cms-sw/cmssw/pull/22987

This is an rather urgently needed fix for data taking and TSG would like it as a patch release.

### CODE REVIEW

**Comment by silviodonato** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by Martin-Grunewald** [comment]
backport of #22987

**Comment by silviodonato** [comment]
type bugfix

**Pull request merged**
