### PR TITLE
[DQM] Updated the client for MuonMonitor in online DQM

### PR DESCRIPTION
**Pull request by calderona**
#### PR description:

There were some missing piece in the muon monitor client for the muon DQM that crashed at the online DQM. Now it has been fixed, and it is expected to be included on next MWGR.

### CODE REVIEW

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
@calderona @jfernan2 of course this test will prove nothing, I understand that you checked it in the online environment

**Comment by fioriNTU** [comment]
@calderona (@jfernan2 ) this PR is to be backported to 10_6_X in order to be used in Online. Please do it as soon as possible

**Comment by jfernan2** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
