### PR TITLE
Use standard file names in DQM/HcalTasks config files [14_0]

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

Added cfi or cff extensions.

#### PR validation:

Code compiles.

backport of #44408 on request of DQM l2s.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by tjavaid** [comment]
backport of #44408

**Comment by tjavaid** [comment]
+1

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
