### PR TITLE
Fix SiPixel Layer 1 efficiency calculation

### PR DESCRIPTION
**Pull request by tsusa**
#### PR description:

Following https://github.com/cms-sw/cmssw/pull/35058 a few fixes/changes in L1 efficiency calculation/hit classification are introduced:  reject TrajectoryMeasurements w/o pixel hit, fix min.distance calculation and filling of the inactive hits, initialize valid/missing/passcuts_hit for each loop iteration.

Changes expected in L1 efficiency and hit classification.  

#### PR validation:
Matrix run, no issue.

### CODE REVIEW

**Comment by tsusa** [comment]
please test

**Comment by mmusich** [comment]
@tsusa can you change the title to reflect this targets SiPixel?

**Comment by emanueleusai** [comment]
+1

**Comment by perrotta** [comment]
Thank you @tsusa  for having taken care of the issues that were pointed out originally in #35058 for the SiPixelPhase1TrackEfficiency code. Since you made the effort, could you please further clean up the code, to make it more easily readable, and thus avoid such flaws in possible future updates (which are foreseen, as expected at least from the commented out parts of the code)?

- `passcuts` is reset at every iteration inside the loop that starts at L202 and ends at L576: for clarity, and to avoid mistakes I would define it at L222, rather than outside that loop al L189. For the same reason, I think it would be safer and cleaner to define all integers initialized at 0 in L214-221 only inside the loop; the same for `isBpixtrack` and `isFpixtrack`.

- `passcuts_hit` is used inside two loops, first the recHits (between L289 and L394) and then for the expTrajMeasurements (between L439 and L557). Then, still for clarity and to avoid mistakes, I would define passcuts_hit locally inside those loops, i.e. at L290 and L442, instead of outside them at L190.

- To improve readability, I would replace the separate if's with some if - else if structure whenever the options are exclusive by construction. For example:
  - L237-L256 (and therein)
  - L259-L266 (even better if you put all checks in OR)
  - L303-L311
  - L324-L357 (and therein)

- Could you also please make (static) constexpr all upper-case cut values defined between L163 and L178?

**Comment by tsusa** [comment]
please test

**Comment by perrotta** [comment]
please test
(log for failing 1002.0 got truncated: try once more to see if it is transient)

**Comment by perrotta** [comment]
@tsusa could you please confirm that the differences reported in the PR tests after the last changes are still the ones expected?
e.g. in https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_4_X_2022-05-05-2300+d01c91/50085/11634.911_TTbar_14TeV+2021_DD4hep+TTbar_14TeV_TuneCP5_GenSim+Digi+RecoNano+HARVESTNano+ALCA/PixelPhase1_Tracks_PXBarrel_Shell_pO_PXLayer_1.html

**Comment by tsusa** [comment]
@perrotta  the changes in pixel plots are the same as before the last commit (see for example the changes in the plots that you pointed out https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_4_X_2022-05-03-1100+d01c91/50016/11634.911_TTbar_14TeV+2021_DD4hep+TTbar_14TeV_TuneCP5_GenSim+Digi+RecoNano+HARVESTNano+ALCA/PixelPhase1_Tracks_PXBarrel_Shell_pO_PXLayer_1.html) 

There are two additional failed wf  (10224.0  and 312.0) after the last commit (not present before) but the differences come from the MessageLogger.

**Comment by perrotta** [comment]
+1

**Comment by emanueleusai** [comment]
+1

**Comment by perrotta** [comment]
+1

**Comment by mmusich** [comment]
type trk

**Comment by mmusich** [comment]
type bug-fix

**Comment by mmusich** [comment]
@tsusa @perrotta is a backport to 12.3.X in order here, as it's essentially a bug-fix?

**Comment by perrotta** [comment]
> @tsusa @perrotta is a backport to 12.3.X in order here, as it's essentially a bug-fix?

@mmusich @tsusa this is DQM, and therefore I see no counterindication in backporting it in 12_3. If you think that it can be useful to monitor the first part of this year data taking, feel free to prepare a backport PR

**Comment by mmusich** [comment]
here it is: https://github.com/cms-sw/cmssw/pull/37859

**Pull request merged**
