### PR TITLE
Fix crash in Online Tracking for Pixels

### PR DESCRIPTION
**Pull request by fioriNTU**
This PR fixes a crash in the online pixel client, it is based on 10_0_3 as requested by the DQM team. 
It will be submitted later in 10_1_X

### CODE REVIEW

**Comment by dmitrijus** [comment]
Why is it so different from 10_1_X?

**Comment by fioriNTU** [comment]
@dmitrijus, because in 10_0_X another PR was already merged in the IB (#22336), so I had to workaround it.

**Comment by dmitrijus** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
