### PR TITLE
 HeavyIon: Add E/p cut to electrons and extend event content for electron collections. (75X backport of #11223)

### PR DESCRIPTION
**Pull request by harmonicoscillator**
This is a backport of #11223 to CMSSW_7_5_X.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
+1

For #11224 a79ad0891070d590a200b254e3cb72f184229e7f

For Heavy Ions, adding E/p cut to electrons. #11223 is the 76X version of this PR, and it has already been approved by Reco.

The code changes are satisfactory, and Jenkins tests against baseline CMSSW_7_5_X_2015-09-09-2300 show no significant differences. A test for #11223 with workflow 140.53_RunHI2011 showed no significant differences, timing changes, or product size changes.

**Comment by slava77** [comment]
@davidlange6 
was there a reason to not include this in 753?

**Comment by mandrenguyen** [comment]
@slava77 @davidlange6 
This was the last requested addition to the HI reco.
It's a shame this wasn't included in 753.  What's the timescale for the next 75X release?

**Comment by davidlange6** [comment]
+1

**Pull request merged**
