### PR TITLE
Run3-gex121 Take care of deprecrated codes in GeneratorInterface/EvtGenInterface

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Take care of deprecrated codes in GeneratorInterface/EvtGenInterface

#### PR validation:

Use the runTheMatrix test workflows

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by Saptaparna** [comment]
Let me also add @colizz as a potential reviewer.

**Comment by SiewYan** [comment]
The code looks ok to me.

**Comment by bsunanda** [comment]
@SiewYan Here again use of plain EDAnalyzer is avoided,

**Comment by SiewYan** [comment]
+1

@bsunanda , thank you, Its look all good to me though.

**Comment by perrotta** [comment]
+1

**Pull request merged**
