### PR TITLE
[14_0_X] Backport of 44507+44726 (Add ParticleNet legacy discriminator scores and mass regression to MINIAOD)

### PR DESCRIPTION
**Pull request by hqucms**
#### PR description:

Backport of: 
- https://github.com/cms-sw/cmssw/pull/44507
- https://github.com/cms-sw/cmssw/pull/44726

> #### PR description:
> Add back the ParticleNet legacy discriminator scores and mass regression for AK8 Jets. This allows a comparison with newer version of ParticleNet and may be useful in scenarios that fall out of the phase space of the newer ParticleNet training.
> 
> * Changes expected in the miniAOD and nanoAOD output. Added the following branches to nanoAOD:
> 
> ```
>  FatJet_particleNetLegacy_QCD
>  FatJet_particleNetLegacy_Xbb
>  FatJet_particleNetLegacy_Xcc 
>  FatJet_particleNetLegacy_Xqq 
>  FatJet_particleNetLegacy_mass 
> ```
> 
>  * Discussion took place at XPOG meeting on March 14th: https://indico.cern.ch/event/1382063/#10-pnet-legacy-in-v14
>

### CODE REVIEW

**Comment by hqucms** [comment]
enable nano

**Comment by hqucms** [comment]
please test

**Comment by hqucms** [comment]
Backport of https://github.com/cms-sw/cmssw/pull/44507

**Comment by hqucms** [comment]
backport of https://github.com/cms-sw/cmssw/pull/44507

**Comment by hqucms** [comment]
please test

**Comment by hqucms** [comment]
+1

**Comment by mandrenguyen** [comment]
+1
Only changes see are to discriminator scores in mini/nana, as expected

**Comment by rappoccio** [comment]
+1

**Pull request merged**
