### PR TITLE
ALCARECO HLT-selection streamlining AND shorten AfterAbortGap=>AGG

### PR DESCRIPTION
**Pull request by franzoni**
+ **names longer than Tier0 can handle** (see: https://hypernews.cern.ch/HyperNews/CMS/get/tier0-Ops/1439/2/1/1/1/1/2/1/1/1/1/1/2/1/1.html ) of two Alcarecos have been **shortened**:
. SiStripCalMinBiasAfterAbortGap=>SiStripCalMinBiasAAG 
. and SiStripCalMinBiasAfterAbortGapHI=>SiStripCalMinBiasAAGHI

+ **HTL-results filtering**
   HLTrigger.HLTfilters.triggerResultsFilter_cfi
   included in the sequence of all alcareco, streamlining the name of the corresponding alcareco trigger bits key, and setting to "*" the bits wherever there was no selection. This will ease operation by allowing update of inputs to AlCARECO w/o needing a patch release

+ **AlCaRecoTriggerBitsRcd of all MC GT's** has been updated to AlCaRecoHLTpaths_2017_MC_v1 ( was: AlCaRecoHLTpaths5e32_v19_mc ), to to modify the existing keys (AAG) and including keys wherever HLT filtering introduced anew

+ **AlCaRecoTriggerBitsRcd of all data GT's** has been updated to AlCaRecoHLTpaths_2017_v4 (was: AlCaRecoHLTpaths8e29_1e31_v24_offline) to to modify the existing keys (AAG) and including keys wherever HLT filtering introduced anew . Only the prompt-like GT was originally set to a different tag ( AlCaRecoHLTpaths8e29_5e33_v2_prompt i.e. the tag consumed in prompt), which will be updated with a new IOV before we'll deploy this PR at T0

Work done by @trtomei @ghellwig @tocheng, and @mmusich 

Local tests completed successfully:
```
runTheMatrix.py -l 1001.0 --command='-n 1' >& 1001.a.log  &
runTheMatrix.py -l 1000.0 --command='-n 1' >& 1000.a.log  &
runTheMatrix.py   -l 25,10024,10042,10824 -j 2 --command='-n 1' >& thiagos-updates.2.log &
runTheMatrix.py  --what standard -l 134.813,136.733,136.769,136.77,136.772 -j 2 --command='-n 1' >& tonngguang-updates.1.log &

```

### CODE REVIEW

**Comment by franzoni** [comment]
please test

**Comment by trtomei** [comment]
Hi,

The errors have nothing to with our PR... from the logs:
`----- Begin Fatal Exception 15-May-2017 23:08:35 CEST-----------------------
An exception of category 'FileInPathError' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing module: class=FamosProducer label='famosSimHits'
Exception Message:
edm::FileInPath unable to find file FastSimulation/MaterialEffects/data/NuclearInteractions.root anywhere in the search path.
The search path is defined by: CMSSW_SEARCH_PATH
${CMSSW_SEARCH_PATH} is: /build/cmsbld/jenkins-workarea/workspace/ib-any-integration/CMSSW_9_2_X_2017-05-15-1100/src:/build/cmsbld/jenkins-workarea/workspace/ib-any-integration/CMSSW_9_2_X_2017-05-15-1100/external/slc6_amd64_gcc530/data:/cvmfs/cms-ib.cern.ch/nweek-02472/slc6_amd64_gcc530/cms/cmssw/CMSSW_9_2_X_2017-05-15-1100/src:/cvmfs/cms-ib.cern.ch/nweek-02472/slc6_amd64_gcc530/cms/cmssw/CMSSW_9_2_X_2017-05-15-1100/external/slc6_amd64_gcc530/data
Current directory is: /build/cmsbld/jenkins-workarea/workspace/ib-any-integration/runTheMatrix-results/135.4_ZEE_13+ZEEFS_13+HARVESTUP15FS+MINIAODMCUP15FS
----- End Fatal Exception -------------------------------------------------`

**Comment by franzoni** [comment]
The 3 failing relval PR tests:
+ wf: 5.1, 135.4

as well as 3 failing add on tests:
+ (fastsim, fastsim1 and fastsim2 )

are all fast sim workflows all failing with the error reported above by @trtomei .

It seems to originate from this PR https://github.com/cms-sw/cmssw/pull/18700/files#diff-f4ac5f674aab449c0ccbd686807f24e2R100 ,
possibly due to the fact that this https://github.com/cms-sw/cmsdist/pull/3038/files is missing ?

**Comment by franzoni** [comment]
please test with cms-sw/cmsdist#3038

**Comment by franzoni** [comment]
@smuzaffar
can you help us getting the file FastSimulation/MaterialEffects/data/NuclearInteractions.root 
available to the fast sim ?

**Comment by smuzaffar** [comment]
@franzoni , FastSimulation/MaterialEffects/data/NuclearInteractions.root is available in CMSSW_9_2_X_2017-05-15-2300 IB. It should be available to fastsim tests in jenkins now.

**Comment by franzoni** [comment]
Thanks a lot
Will run tests again

**Comment by franzoni** [comment]
please test

**Comment by dmitrijus** [comment]
+1
DQM changes are minimal

**Comment by fabozzi** [comment]
+1

**Comment by franzoni** [comment]
no unexpected changes in relval tests: 
+ express: 1001.0_RunMinBias2011A missing relmon
+ prompt: 1000.0_RunMinBias2011A 
+ 13A6.731_RunSinglePh2016B
+ 10042.0_ZMM_13 10024.0_TTbar_13

**Comment by franzoni** [comment]
+1

**Comment by franzoni** [comment]
hello @kpedro88 
would you have a moment to take a look at this ?
( for my education, why is upgraded signature needed here ? )

Thanks !

**Comment by kpedro88** [comment]
@franzoni upgrade category is automatically assigned to any PR touching `Configuration/PyReleaseValidation` (among others) due to frequency of upgrade changes in that package

**Comment by kpedro88** [comment]
+1

**Comment by franzoni** [comment]
Thanks @kpedro88

**Comment by davidlange6** [comment]
+1

**Comment by davidlange6** [comment]
hi @franzoni - looks like this is causing a number of problems in the IB for cosmics workflows. Can you fix in the next hour(s)?

cosmic: along momentum... 
----- Begin Fatal Exception 17-May-2017 11:11:34 CEST-----------------------
An exception of category 'Configuration' occurred while
   [0] Processing  Event run: 1 lumi: 1 event: 188 stream: 1
   [1] Running path 'pathALCARECOMuAlGlobalCosmics'
   [2] Calling method for module HLTHighLevel/'ALCARECOMuAlGlobalCosmicsHLT'
Exception Message:
 HLTHighLevel [instance: ALCARECOMuAlGlobalCosmicsHLT - path: pathALCARECOMuAlGlobalCosmics]: No triggerList with key MuAlGlobalCosmics in AlCaRecoTriggerBitsRcd

**Comment by franzoni** [comment]
thanks @davidlange6 
addressing

**Comment by franzoni** [comment]
we see 3 WF's  runTheMatrix.py --what standard -l 7.2,7.3,7.4
failing because of a mismatch between the alcarecotrigger bits and the key used to retrieve it mismatch;

( eventSetupPathsKey 
 : https://github.com/cms-sw/cmssw/blob/09c3fce6626f70fd04223e7dacebf0b485f73f54/Alignment/CommonAlignmentProducer/python/ALCARECOMuAlGlobalCosmics_cff.py#L7 ) 

The problem affects only MC 2017, and can be fixed with a 1 line change.

@trtomei and @tocheng working to a change + tests.
a corretting PR can be available by ~1-2h.

**Comment by trtomei** [comment]
The PR #18812 makes a one-line change to the MuAlGlobalCosmics AlCaReco, to allow it to also read the "MuAlGlobalCosmicsInCollisions" key. This fixes the 3 crashing workflows.

**Pull request merged**
