### PR TITLE
Run4-hgx275 Fourth step of making V15 geometry for HGCal

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Fourth step of making V15 geometry for HGCal

#### PR validation:

Tested by dumping the geometry and checking using fireworks

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
+1

**Comment by bsunanda** [comment]
@kpedro88 @srimanob Please review and approve this PR

**Comment by srimanob** [comment]
+Upgrade

**Comment by qliphy** [comment]
+1

**Pull request merged**
