### PR TITLE
New JEC for 2018 HI re-miniAOD

### PR DESCRIPTION
**Pull request by christopheralanwest**
#### PR description:

This PR updates the HI JEC for the re-miniAOD of the 2018 HI run. The 2018 HI MC as well as the 2018 HI IOVs of the prompt-like data JEC tags are updated. The GT diffs are as follows:

**Prompt-like data**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_dataRun2_PromptLike_HI_v3/112X_dataRun2_PromptLike_HI_v5

**2018 heavy ion**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_upgrade2018_realistic_HI_v5/112X_upgrade2018_realistic_HI_v6

#### PR validation:

See the [HN thread for details](https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/4356.html). In addition, a technical test was performed: `runTheMatrix.py -l limited --ibeos`

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

This PR is not a backport but will be backported to 11_2_X as it is intended for use in 11_2_X.

### CODE REVIEW

**Comment by christopheralanwest** [comment]
please test

**Comment by christopheralanwest** [comment]
please test

**Comment by christopheralanwest** [comment]
+1

**Comment by qliphy** [comment]
+1

**Comment by mandrenguyen** [comment]
Hi @christopheralanwest 
Can you backport this to 11_2_X?

**Comment by christopheralanwest** [comment]
> Hi @christopheralanwest
> Can you backport this to 11_2_X?

I've created the backport PR #32453.

**Pull request merged**
