### PR TITLE
HerwigPP: Added two processes

### PR DESCRIPTION
**Pull request by mharrend**
ttbar with ME Corrections switched on and off and
ggH with ME Corrections switched on and off

### CODE REVIEW

**Comment by mharrend** [comment]
I have now added the reshuffling options needed by the Top Group.

**Comment by mharrend** [comment]
Dear all,

I provided two further bug fixes in this pull request. 
The work on the Herwig++ / ThePEG interface configuration should be now finished or at least until I implement the new Herwig++ 3 version. 

So please accept the pull request for now. Thanks, Marco

**Comment by bendavid** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
