### PR TITLE
Backport of Candidate Seeding fix to 100X

### PR DESCRIPTION
**Pull request by JanFSchulte**
Fixes bug in new candidate seeding doublet recovery, Backport of PR #22310

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
backport of #22310

**Comment by perrotta** [comment]
+1
- Identical to #22310 in the master
- The code acts as planned and fixes the candidate Seeded option for automated doublet recovery (not used in offline reco, but proposed for HLT tracking) when there are zero candidates
- Backport to 10_0 is justified because of possible use for HLT studies and developments

**Comment by fabiocos** [comment]
+1

**Pull request merged**
