### PR TITLE
CTPPS: detector id update (back-port of #16010 to 8_0_X)

### PR DESCRIPTION
**Pull request by jan-kaspar**
This is a back-port of #16010.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by ianna** [comment]
+1

**Comment by cvuosalo** [comment]
backport #16010

**Comment by cvuosalo** [comment]
+1

For #16581 3905d110d9a5a481a05a9ee5b6e53b1132b8fd25

For CT-PPS, updating the DetID numbering scheme.

#16010 is the 81X version of this PR, and it has already been merged.

The code changes are satisfactory, and Jenkins tests against baseline CMSSW_8_0_X_2016-11-14-2300 show no significant differences. A further test performed for #16010 also showed no problems.

**Comment by dmitrijus** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by franzoni** [comment]
+1

**Comment by ggovi** [comment]
+1

**Comment by jan-kaspar** [comment]
Is there a reason why this PR has not been merged yet? Thanks!

**Comment by jan-kaspar** [comment]
Backport of #16616 depends on this PR.

**Comment by slava77** [comment]
@davidlange6 
please clarify on the status of this PR to be merged.

**Comment by jan-kaspar** [comment]
This pull request will be replaced by a "cumulative" PR with all changes needed for the legacy re-reco.

**Pull request closed without merging**
