### PR TITLE
Added new categories (DSTJets,DSTMuons) for scouting triggers.

### PR DESCRIPTION
**Pull request by ryonamin**
Backport of 76X (#11694)

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1
provided it passes the tests

**Comment by deguio** [comment]
-1
this PR is buggy. the corresponding one is #11694

**Comment by ryonamin** [comment]
I see the problem. There is missing changes that are expected to be merged in https://github.com/cms-sw/cmssw/pull/11616.
I will remove those problematic parts.

**Comment by ryonamin** [comment]
I have noticed that I just missed some commits. I will close this PR and make another PR.

**Pull request closed without merging**
