### PR TITLE
Run2-TB39 Add CERN HGCAL TB configuration of June 2018 (Shilpi)

### PR DESCRIPTION
**Pull request by bsunanda**
Also add hooks to make a ROOT tree to study some special  effects

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by ianna** [comment]
+1

**Comment by bsunanda** [comment]
@civanch Can you please approve this PR?

**Comment by civanch** [comment]
+1

**Comment by fabiocos** [comment]
@bsunanda I see in this PR also a change to the Hcal TB code of 2006 that seems unrelated to the main scope of this PR, but ok, it looks mostly technical

**Comment by fabiocos** [comment]
+1

**Pull request merged**
