### PR TITLE
Fix lostTracks producer not setting lostInnerHits

### PR DESCRIPTION
**Pull request by elusian**
#### PR description:

The lostTracks producer has a bug that leaves the `lostInnerHits` of the `PackedCandidate` unset (and thus at its default value of `validHitInFirstPixelBarrelLayer`). Other than in `lostInnerHits` the bug propagates in the number of valid pixel hits and the number of pixel and tracker layers with measurements in the `HitPattern` of the `bestTrack` of the candidate.

This PR fixes the bug by adding the call to `setLostInnerHits` as the code from the `packedPFCandidates` producer does. This fix has been checked running the workflow 136.8311 and the issue was solved (see attached figures in the PR on master).

#### PR validation:

This PR has been validated with `runTheMatrix.py -l limited -i all --ibeos` and all checks are ok.
The final output is
```
35 34 33 25 12 2 1 1 1 tests passed, 0 0 0 0 0 0 0 0 0 failed
```
In particular the DQM output of 136.8311 shows the differences which are expected: inside `Tracking/PackedCandidate/lostTracks`, in `diffLostInnerHits`, `diffHitPatternNumberOfLostPixelHits`, `diffHitPatternHasValidHitInFirstPixelBarrel`, `diffHitPatternNumberOfValidPixelHits`, `diffHitPatternPixelLayersWithMeasurement`, `diffHitPatternTrackerLayersWithMeasurement`, see the attached plots in the PR on master.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

This PR is a backport of #32814, needed for BParking reprocessing.

### CODE REVIEW

**Comment by perrotta** [comment]
backport of #32814

**Comment by perrotta** [comment]
please test

**Comment by slava77** [comment]
my interpretation of the no-change policy is that this PR should provide a configurable way to apply the bugfix and we can include it in a relevant production (re)processing with a configuration switch.
From the description it sounds like the switch would enable the feature with the `bParking` modifier.

**Comment by mtosi** [comment]
ciao, sorry, but just for understanding
even if it is a bugfix, one needs to add a switch in order to enable the bugfix ?

so, @elusian should add a flag in the config in order to run his code, while being still back-compatible ?
thanks

**Comment by slava77** [comment]
> ciao, sorry, but just for understanding
> even if it is a bugfix, one needs to add a switch in order to enable the bugfix ?

if the bug is not significant enough to invalidate the current production, then it essentially becomes a feature.

In the past we left exceptions to the no-change requirement for variables that were known to be not used or if they were fairly localized (e.g. one variable not used anywhere else downstream).

Here the way how the lostInnerHits is used and saved is too convoluted. So, it seems more appropriate to have this fix on demand.

**Comment by mtosi** [comment]
@cmsbuild, please test

**Review by mtosi — APPROVED** [review]

**Comment by elusian** [comment]
The new changes were tested on 10824.8 workflow, which enables the bParking modifier. The fix was confirmed to be working with this workflow, while it is not applied on the 136.8311 workflow. Removing the bParking era modifier from the cmsDriver invocation for step3 in the 10824.8 workflow also disabled the bugfix.

**Comment by jpata** [comment]
+reconstruction
- backport of #32814, enabled only with the `bParking` modifier
- backport looks correct wrt. the original
- no changes observed in the matrix workflows, as expected

**Comment by qliphy** [comment]
+1

**Pull request merged**
