### PR TITLE
Updates to Resonance Decay Filter

### PR DESCRIPTION
**Pull request by DavidMorse**
Backporting pull request #15285 to 80X

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by DavidMorse** [comment]
Hi, I'm not an expert in debugging this, but looking through the tests the only error I can find is:

IOError: [Errno 2] No such file or directory: 'das-cache.file'

and it only happens on data workflows. It seems unlikely that any of the changes could have caused this, particularly since they should only be accessed during GEN-SIM. But maybe I am missing something...

**Comment by perrozzi** [comment]
Hi @DavidMorse, I agree that the error seems unrelated, the PR should be ready to be merged, re-approving

**Comment by perrozzi** [comment]
+1

**Comment by perrozzi** [comment]
please test

**Comment by perrozzi** [comment]
@DavidMorse this can be incorporated, right?

**Comment by DavidMorse** [comment]
@perrozzi Yes, good to go.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
