### PR TITLE
Add clones for CSC trigger primitives for Run-3 and Phase-2 with CCLUT on (CCLUT-19)

### PR DESCRIPTION
**Pull request by dildick**
#### PR description:

Vladimir Rekovic requested in the L1T Offline Software meeting that clones are added for the CSC Trigger Primitives when the comparator code lookup table algorithm (CCLUT) is on for the optical TMBs (in MEX/1 for Run-3) and also for the old "copper" TMBs (ME1/3, MEX/2 for Phase-2). That will allow us to study the interface between Phase-2 EMTF and Phase-2 CSC TPs with CCLUT on in all chambers.

#### PR validation:

Code compiles. I'll check a few WFs for Run-3 and Phase-2.

In WF 11634.0 I see the updated SimL1Emulator configuration
```
In [4]: print(process.SimL1Emulator)
simCaloStage2Layer1Digis,simCaloStage2Digis,simMuonGEMPadDigis,simMuonGEMPadDigiClusters, \
simDtTriggerPrimitiveDigis,simCscTriggerPrimitiveDigis,simTwinMuxDigis,simBmtfDigis,simKBmtfStubs, \
simKBmtfDigis,simEmtfDigis,simOmtfDigis,simGmtCaloSumDigis,simGmtStage2Digis,simEmtfShowers, \
simGmtShowerDigis,simCscTriggerPrimitiveDigisRun3,simGtExtFakeStage2Digis,simGtStage2Digis
```

The update is not going to change any WF because ```simCscTriggerPrimitiveDigisRun3``` or ```simCscTriggerPrimitiveDigisPhase2``` are not use by any producer/analyzer.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

@jiafulow @eyigitba @tahuang1991

### CODE REVIEW

**Comment by dildick** [comment]
Can someone initiate the tests, please?

**Comment by rekovic** [comment]
please test

**Comment by dildick** [comment]
fyi @rathjd

**Comment by dildick** [comment]
A few errors from messagelogger. Results look fine.

**Comment by dildick** [comment]
FYI @giovanni-mocellin

**Comment by rekovic** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
