### PR TITLE
Phase 2 HLT menu targetting 7.5×10³⁴ cm⁻²s⁻¹

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Implement the Phase-2 HLT menu used for the HLT TDR.

HLT_75e33_cfg.py implements a self-contained configuration:
  - selects the required input collections for running on a re-emulated L1 sample;
  - uses the global tag 111X_mcRun4_realistic_T15_v5;
  - configures the MessageLogger, DQMStore, FastTimerService and ThroughputService.

HLT_75e33_cff.py implements a configuration fragment for use wih cmsDriver. To avoid redefinition errors, most of the L1T modules and the offline beamspot module are dropped from this configuration.

The HLT configuration is based on
  - `CMSSW_11_1_8`, forward-ported as-is to `CMSSW_12_1_0_pre3
  - global tag [`111X_mcRun4_realistic_T15_v5`](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/111X_mcRun4_realistic_T15_v5)
  - the Tracking v6.1 baseline configuration
  - the TICL v3 configuration

and implement the baseline Phase-2 configuration for Jets/MET, b-tagging, Muons and E/Gamma.
Taus are not included.

It includes "open" or "MC" HLT paths for running the reconstruction without any (pre)selection applied, and a partial re-emulation of the Level-1 Trigger, which simulates a simplified L1T menu using EDFilters and Paths.

Barring the changes in release and conditions, for Jets/MET and B-tagging the results obtained for the TDR correspond to the commit 38d7327 (and likely also with a6692af, which is just a technical fix), which still use "offline" muons for the Particle Flow reconstruction.
The following commits implement the use of HLT muons in the Particle Flow reconstruction, affecting the Jets/MET (and likely B-tagging) performance in a non-negligible way; for more details see [this presentation](https://indico.cern.ch/event/1035816/contributions/4350085/subcontributions/337175/attachments/2242877/3803185/210511_hltupg_val32903.pdf).

For Muons, E/Gamma, and overall timing measurements, the results obtained in the TDR correspond to the full PR.

#### PR validation:

To be done.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Forward port of #32903.

### CODE REVIEW

**Comment by fwyzard** [comment]
please test

**Comment by Martin-Grunewald** [comment]
Hmm, I see a maintenance issue in migrating forward - this time and in the future.

The specific module now has this config:
```
process.CSCGeometryESModule = cms.ESProducer( "CSCGeometryESModule",
  fromDDD = cms.bool( False ),
  fromDD4hep = cms.bool( False ),
  alignmentsLabel = cms.string( "" ),
  appendToDataLabel = cms.string( "" ),
  useRealWireGeometry = cms.bool( True ),
  useOnlyWiresInME1a = cms.bool( False ),
  useGangedStripsInME1a = cms.bool( False ),
  useCentreTIOffsets = cms.bool( False ),
  applyAlignment = cms.bool( True ),
  debugV = cms.untracked.bool( False )
)
```
One could take such modules and their config from the combined table, but some (other) changes may be intentional for Phase-II!

**Comment by fwyzard** [comment]
My idea was to simplify the HLT configurations by taking the default configuration of each module from its cfi file, and apply only the HLT-specific changes in the HLT menu itself.

I didn't do it so far; I can try doing it for this PR, or I can just fix the modules that need fixing and postpone the issue.
Any preference ?

**Comment by Martin-Grunewald** [comment]
Hmm, either way is fine, if you commit to it.

But I am worried about long-term maintenance/migrations going forward, now we need to do so in ConfDB and in here. The combined table in ConfDb was to avoid such duplication. We have not settled on a ConfDb-repalcement and/or how to handle Phase-II in there.

**Comment by fwyzard** [comment]
I think this discussion is better handled in a meeting (TSG tomorrow ?) rather than on GitHub.

**Comment by Martin-Grunewald** [comment]
Sure, I am just raising the issue.

**Comment by qliphy** [comment]
Any news or should this be closed for the moment? @fwyzard

**Comment by fwyzard** [comment]
@trtomei is working on a new version of the HLT menu; if he agrees, I can close this PR and let him open a new one.

**Comment by trtomei** [comment]
@fwyzard I agree, please proceed.

**Pull request closed without merging**
