### PR TITLE
Fix gcc 12 error: result of pointer addition is never NULL

### PR DESCRIPTION
**Pull request by smuzaffar**
GCC 12 IBs have [build errors](https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/el8_amd64_gcc12/CMSSW_13_2_X_2023-05-27-1100/EventFilter/HGCalRawToDigi) like [a]. GCC 12 suggest to avoid the comparison of pointer addition with NULL as the result will never be null. This PR avoids the comparison of ptr with NULL and adds the check that code does not access out of bound memory e.g. when `fed_data` is not modulo of 4

[a]
```
  EventFilter/HGCalRawToDigi/plugins/HGCalRawToDigi.cc:68:37: error: comparing the result of pointer addition '(ptr + ((sizetype)i))' and NULL [-Werror=address]
    68 |       data_32bit.emplace_back(((ptr + i) ? ((*(ptr + i) & 0xff) << 0) : 0) +
      |                                ~~~~~^~~~
  EventFilter/HGCalRawToDigi/plugins/HGCalRawToDigi.cc:69:41: error: comparing the result of pointer addition '(ptr + (((sizetype)i) + 1))' and NULL [-Werror=address]
    69 |                               ((ptr + i + 1) ? ((*(ptr + i + 1) & 0xff) << 8) : 0) +
      |                                ~~~~~~~~~^~~~
  EventFilter/HGCalRawToDigi/plugins/HGCalRawToDigi.cc:70:41: error: comparing the result of pointer addition '(ptr + (((sizetype)i) + 2))' and NULL [-Werror=address]
    70 |                               ((ptr + i + 2) ? ((*(ptr + i + 2) & 0xff) << 16) : 0) +
      |                                ~~~~~~~~~^~~~
  EventFilter/HGCalRawToDigi/plugins/HGCalRawToDigi.cc:71:41: error: comparing the result of pointer addition '(ptr + (((sizetype)i) + 3))' and NULL [-Werror=address]
    71 |                               ((ptr + i + 3) ? ((*(ptr + i + 3) & 0xff) << 24) : 0));

```

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test for el8_amd64_gcc12

though tests will fail due to cuda 12/gcc12 issues but at least `EventFilter/HGCalRawToDigi` should compile

**Comment by perrotta** [comment]
@cms-sw/reconstruction-l2 @cms-sw/upgrade-l2 this rather simple bug fix can prevent build failures with gcc12
Could you please sign it, if you agree with it, or comment otherwise?

**Comment by AdrianoDee** [comment]
+upgrade

**Comment by mandrenguyen** [comment]
+reconstruction

**Comment by perrotta** [comment]
+1

**Pull request merged**
