### PR TITLE
[14_0_X] pileup profile for RunIII2024Summer24 MC compaign (backport)

### PR DESCRIPTION
**Pull request by DickyChant**
#### PR description:

Backport of https://github.com/cms-sw/cmssw/pull/45474

Introducing pileup profiles for RunIII2024Summer24 MC compaigns 

#### PR validation:

Tested with CMSSW runtests

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Since this PR will be used for 2024 MC campaigns, it is intended to be packported to 14_0_X (as described in [recent PPD news](https://indico.cern.ch/event/1441706/contributions/6067243/attachments/2909148/5103743/24-08-08_News_PPD.pdf)

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by iarspider** [comment]
@DickyChant please remove merge marks

**Comment by DickyChant** [comment]
> @DickyChant please remove merge marks

Jesus my bad........

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by antoniovilela** [comment]
+1

**Comment by antoniovilela** [comment]
@DickyChant
It seems this got a conflict after #45686 was merged.

**Comment by DickyChant** [comment]
> @DickyChant It seems this got a conflict after #45686 was merged.

I see, I guess it was related to the fact that the original PR https://github.com/cms-sw/cmssw/pull/45474 is going after the original PR of https://github.com/cms-sw/cmssw/pull/45686 ...

**Comment by DickyChant** [comment]
> @DickyChant It seems this got a conflict after #45686 was merged.

I just resolved the conflict... apologize for the mess!

**Comment by civanch** [comment]
please test

**Comment by mmusich** [comment]
is it possible to avoid the nasty merge commit by rebasing?

**Comment by DickyChant** [comment]
> is it possible to avoid the nasty merge commit by rebasing?

Did my exercise in the afternoon, not seems to work (since I cannot find a proper `old-release` to based on...)

**Comment by mmusich** [comment]
```bash
cmsrel CMSSW_14_0_X_2024-08-20-1100
cd CMSSW_14_0_X_2024-08-20-1100/src/
cmsenv
git cms-merge-topic 45687
git rebase -i CMSSW_14_0_X
# fix conflicts by hand
git rebase --contine
git cms-init
git push my-cmssw +HEAD:backport_2024_PU
```

seems to work for me: [link](https://github.com/cms-sw/cmssw/compare/CMSSW_14_0_X...mmusich:cmssw:backport_2024_PU)

**Comment by DickyChant** [comment]
> [link](https://github.com/cms-sw/cmssw/compare/CMSSW_14_0_X...mmusich:cmssw:backport_2024_PU)

agh you mean improve this one? Sure I'll do it

**Comment by mandrenguyen** [comment]
please test

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
