### PR TITLE
Update GEM offline DQM sequences

### PR DESCRIPTION
**Pull request by seungjin-yang**
#### PR description:
- Add a GEM offline DQM source sequence for cosmics scenario.
- Move GEM offline DQM source and client sequences from POG to DPG.

@jshlee @watson-ij @szaleski

#### PR validation:
Tested with the workflow 11611.0 (2021, TenMu).

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
@seungjin-yang I don't see plots added to wf11634.0 2021+TTbar_14TeV_TuneCP5_GenSim+Digi+Reco+HARVEST+ALCA
 which should be a similar one to the one you tested 11611.0 (I don't find its definition in  runTheMatrix.py --show | grep 11611.0
 sorry), I believe this is not expected

**Comment by seungjin-yang** [comment]
@jfernan2 Era should be later than Run3. Could you try the following one?
```bash
runTheMatrix.py -w upgrade -l 11611.0
```

**Comment by jfernan2** [comment]
OK @seungjin-yang I understand what is going on: since your plots were already in, you just corrected the DQMOffline config file to run them (from POG to DPG, as it should be), the system does not see any change (plots remain in the same folder GEM/* )

Your backport PR DOES see the plots:
https://github.com/cms-sw/cmssw/pull/31819#issuecomment-710028209

**Comment by jfernan2** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
