### PR TITLE
Faster provenance handling

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

The ProductProvenanceRetriever used to hold the parentage information for the Event data products now uses a faster data structure and avoids resetting itself every Event.

#### PR validation:

The framework unit tests all pass.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1
The comparison failures are the same as seen in #28474 which was included by the bot in the testing.

**Comment by fabiocos** [comment]
@smuzaffar here I see another case of tests run against 11_0_X for a 11_1_X PR

**Comment by fabiocos** [comment]
@qliphy @agrohsje this looks a technical update, I am performing a quick cross check on LHE provenance, please have a look, i will integrate this PR ass soon as I have finished

**Comment by smuzaffar** [comment]
correct, This issue has been identified and fixed. The ib baseline generation job was using your old branch for 11.0.X [a]. This was done to test your changes but it was never reverted. This only effected the generation of baseline job to use an old cms-bot. Note that https://github.com/cms-sw/cms-bot/blob/master/run-ib-comparison-baseline in your branch and cms-bot master is identical, so this did not break any thing till now. 

Problem is that in your branch has DEV release set to CMSSW_11_0_X while now we move to CMSSW_11_1_X. Anyway, feel free to re-tests if case you want to get clean

[a]
```
if [ $(echo $RELEASE_FORMAT | grep 'CMSSW_11_0_X_' | wc -l) -gt 0 ] ; then
  git clone -b fc-IBperf https://github.com/fabiocos/cms-bot
else
  git clone https://github.com/cms-sw/cms-bot
fi
```

**Comment by fabiocos** [comment]
@smuzaffar thanks, good that it is understood, I'll check and clean my branch

**Comment by fabiocos** [comment]
@qliphy @agrohsje please check, I will integrate this PR in next IB

**Comment by qliphy** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
