### PR TITLE
Remove circular dependency and fix checksum for class reco::CATopJetTagInfo.

### PR DESCRIPTION
**Pull request by wmtan**
In ROOT 5.34, and ROOT 6, class checksums depend on the base class. 
Because of a missing link dependency,  edmCheckClassVersion calculated the wrong checksum for class reco::CATopJetTagInfo.
Unfortunately, adding the missing link dependency would create an explicit mutual dependency between packages DataFormats/JetReco and DataFormats/BTauReco.
This pull request moves the definition of this class from DataFormats/JetReco to DataFormats/BTauReco, breaking the cyclic dependency, and also fixes the checksum.
The problem with edmClassVersion needs to be fixed separately, because the checksum it calculates can depend on build order of the packages.
This pull request also adds missing link dependecies on DataFormats/BTauReco, which, while not technically necessary due to the fact that all member functions of CATopJetTagInfo are in-lined.
Nonetheless, it is bad practice to omit package link dependencies for this reason.
Please expedite this critical pull request, bypassing signatures if not signed in a timely manner.
However, do not bypass testing, comparisons, and all that!!

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by deguio** [comment]
+1

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/7298	53f3aa2
jenkins compiles and runs OK .. (CATopJetTagInfo appear only in the PAT/miniAOD step)

**Pull request merged**
