### PR TITLE
DetectorDescription Clang Check modernize-use-emplace

### PR DESCRIPTION
**Pull request by ianna**
Replaces https://github.com/cms-sw/cmssw/pull/19976 after merge of https://github.com/cms-sw/cmssw/pull/19974

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
@smuzaffar - is there a problem with CLANG IB?

**Comment by ianna** [comment]
please test

**Comment by smuzaffar** [comment]
@ianna , looks like https://github.com/cms-sw/cmssw/blob/master/Utilities/General/src/FileInPath.cc#L2 needs boost while BuildFile.xml does not include it. I wonder how this is not causng any issues in ibs

**Comment by smuzaffar** [comment]
abort

**Comment by smuzaffar** [comment]
test with #20033

**Comment by ianna** [comment]
+1

**Comment by perrotta** [comment]
@ianna : your PRs #20020 and #20030 interfere each other. Since they act on the same files they will not be mergeable any more as soon as one of the two gets  merged first, (Checked just now on CMSSW_9_3_X_2017-08-03-140)

Why not combine yourself those two (and possibly also #19978) into a single PR, that can be merged all at once?

**Comment by ianna** [comment]
@perrotta - smaller PRs tend to be faster to integrate, even with if there are merging conflict fixes.

**Comment by slava77** [comment]
On 8/3/17 10:06 AM, Ianna Osborne wrote:
> @perrotta <https://github.com/perrotta> - smaller PRs tend to be faster
> to integrate, even with if there are merging conflict fixes.

not when they edit the same files.
please factor out the DataFormats/Math, which is the only reco category
file into one PR.

**Comment by ianna** [comment]
@slava77 - ok, I'll merge all of the PRs in one.

**Pull request closed without merging**
