### PR TITLE
Transition from sigcpp-2 to sigcpp-3

### PR DESCRIPTION
**Pull request by smuzaffar**
These changes are needed by sigc++ version 3

### CODE REVIEW

**Comment by smuzaffar** [comment]
test parameters:
- pull_request = cms-sw/cmsdist#7441

**Comment by smuzaffar** [comment]
code-checks with cms.week0.PR_cddbe267/52.0-a6892e1bac283099e8d8790601b27c6d

**Comment by smuzaffar** [comment]
@alja , can you please apply https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-36343/27180/code-format.patch patch to your branch `sigcpp3`

**Comment by smuzaffar** [comment]
@alja , can you please apply the patch  https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-36343/27180/code-format.patch

**Comment by alja** [comment]
@smuzaffar I applied the patch. I'm sorry I have missed the previous message 3 days ago.

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@alja this looks good now, can you please sign it for visualization
@qliphy @perrotta , this should be merged with cms-sw/cmsdist#7441

**Comment by alja** [comment]
+1

**Comment by perrotta** [comment]
+1
- It adapts Firework to sigc++-3.0 , as implemented in https://github.com/cms-sw/cmsdist/pull/7441 (which has to get merged together with this PR)

**Pull request merged**
