### PR TITLE
L1T EMTF O2O 2018

### PR DESCRIPTION
**Pull request by rekovic**
PR 10_2_X  version of 10_1_X #23288.

This PR fixes the params needed for successful O2O of L1T EMTF:
 - Remove unused "Endcap", now use "EndCap"
 - Change "EMTF-1" to "EMTFp1"

This has been tested offline and has been running centrally at P5 as local installation on condb machines as fix to L1T O2O.

### CODE REVIEW

**Comment by rekovic** [comment]
please teste

**Comment by davidlange6** [comment]
please test

**Comment by rekovic** [comment]
+1

**Comment by fabiocos** [comment]
@rekovic do I understand correctly that this PR does not affect standard workflows, but it is used only in O2O operations?

@arunhep @lpernie @ggovi could you please check it?

**Comment by ggovi** [comment]
+1

**Comment by lpernie** [comment]
+1

**Comment by lpernie** [comment]
@rekovic this will got to 10_3, you still need a PR for 10_2

**Comment by rekovic** [comment]
>this will got to 10_3, you still need a PR for 10_2

@lpernie OK. Will make back port pr for 10_2.


> do I understand correctly that this update does not affect regular production workflows?

@fabiocos That is correct.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
