### PR TITLE
RPC DQM updates for Run3

### PR DESCRIPTION
**Pull request by minerva1993**
#### PR description:

Update of RPC DQM
- remove histograms (ClusterSize 1D MEs / from summary folders, RPCChamberQuality, ClusterSizeIn1Bin and some other 1D distributions) - reducing DQM root file size by ~ 0.7 MB.
- Change of plot format: ClusterSize 1D ME (cluster size vs entries) to 2D (cluster size vs roll, z axis to be entries) ME
- Refine report summary map to present dead channel fraction correctly (instructions will be updated once related DQM GUI codes are updated)
- Added 'Noise summary map' for shifters (GUI will be modified as well)
- Bug fixes
- Delete unused and duplicated file
- Presented at RPC weekly meeting: https://indico.cern.ch/event/1156425/#5-rpc-status-for-the-dqm-shift

#### PR validation:

- Passed `runTheMatrix.py -l limited -i all --ibeos` ( May 11 13:05:11 2022-date Wed May 11 12:43:48 2022; exit: 0 0 0 0 0 // 48 47 46 35 18 4 1 1 1 1 tests passed, 0 0 0 0 0 0 0 0 0 0 failed)
- Passed `scram b runtests`, `code-checks`, `code-format`
- In addition, tested with Cosmic22 data (Run350561, 347945 with CMSSW_12_3_0 and 12_2_1_patch1 respectively, eg. [1])

#### if this PR is a backport please specify the original PR and why you need to backport that PR:
N/A

[1] Commands: cmsDriver.py step1  --conditions 123X_dataRun3_Prompt_v6 -s RAW2DIGI,L1Reco,RECO,DQM --datatier RECO,DQMIO --eventcontent RECO,DQM --data  --process reRECO --scenario cosmics --customise Configuration/DataProcessing/RecoTLR.customiseCosmicData --era Run3 -n -1 --filein="root://eoscms.cern.ch//eos/cms/tier0/store/data/Commissioning2022/Cosmics/RAW/v1/000/350/561/00000/438297ee-bc1f-4a5c-9a6c-bf4e6a427f8b.root"

cmsDriver.py step2 -s HARVESTING:@standardDQM --conditions 123X_dataRun3_Prompt_v6 --data  --geometry DB:Extended --scenario cosmics --filetype DQM --era Run3 -n -1 --filein=file:step1_RAW2DIGI_L1Reco_RECO_DQM_inDQM.root

### CODE REVIEW

**Comment by minerva1993** [comment]
@ahmad3213 @emanueleusai @jfernan2 @pmandrik @micsucmed @rvenditti
Dear DQM experts, I would kindly ask you to start test and review for this PR on RPC DQM. Thanks in advance.

**Comment by pmandrik** [comment]
Hi,  to test DQM RPC client at P5 a backport to CMSSW_12_3_X is needed

**Comment by minerva1993** [comment]
> Hi, to test DQM RPC client at P5 a backport to CMSSW_12_3_X is needed

Thanks @pmandrik , I created another PR (#37917 ).

**Comment by emanueleusai** [comment]
testing backport at P5

**Comment by minerva1993** [comment]
> testing backport at P5

Hello, any news here? Thanks in advance, J.

**Comment by emanueleusai** [comment]
+1

**Comment by emanueleusai** [comment]
tests completed successfully

**Comment by minerva1993** [comment]
I understand deadline of pre-release is closed already. I just wonder if this PR can be backported to 12_4_X later, as it does not change any physics quantities but only DQM updates?

**Comment by qliphy** [comment]
> I understand deadline of pre-release is closed already. I just wonder if this PR can be backported to 12_4_X later, as it does not change any physics quantities but only DQM updates?

@minerva1993  Such a DQM PR could be allowed. Please make a backport PR to 12_4_X then.

**Comment by qliphy** [comment]
+1

**Pull request merged**
