### PR TITLE
Moved to global modules in SimMuon

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

- removed need to do work on Run transitions
- use modern framework syntax

This is part of the framework change which will require stream modules to register use of Run/LuminosityBlock callbacks.

#### PR validation:

Code compiles.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
@makortel FYI

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by Dr15Jones** [comment]
ping @cms-sw/upgrade-l2

**Comment by srimanob** [comment]
+Upgrade

**Comment by rappoccio** [comment]
+1

**Pull request merged**
