### PR TITLE
Make some HLT modules into global modules

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

Changed the following modules to be global modules
- ScalersRawToDigi
- TriggerSummaryAnalyzerAOD
- TriggerSummaryAnalyzerRAW
- TriggerSummaryProducerAOD
- TriggerSummaryProducerRAW

#### PR validation:

The code compiles. I did do `scram b runtests` and no error was reported.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
I noticed these modules when looking at Tracer output from #29209. These modules were being called on stream Lumi and Run transitions even though they did not care about them (because they were stream modules). Making them global reduces the number of modules called on those transitions.

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
I restarted the tests to see if the number of failures will decrease now that other pull requests have been used in the IBs.

**Comment by Martin-Grunewald** [comment]
+1

**Comment by santocch** [comment]
+1

**Comment by perrotta** [comment]
+1
- Technical
- Jenkins tests pass

**Comment by silviodonato** [comment]
+1

**Pull request merged**
