### PR TITLE
Relval updates

### PR DESCRIPTION
**Pull request by fabozzi**
- new TenE relval 2017 
- increase statistics of BuMixing relval 2017
- update gensim recycling 2017
- removing duplicate ALCARECO in BeanHalo wf

### CODE REVIEW

**Comment by fabozzi** [comment]
@franzoni @arunhep

**Comment by fabozzi** [comment]
please test

**Comment by fabozzi** [comment]
+1

**Comment by smuzaffar** [comment]
@fabozzi , looks like this PR changed the dataset used for workflow 10021.0. It was merged in CMSSW_9_0_X_2017-03-03-2300 IB and step1 now is looking for 
```
 dataset=/RelValTenMuE_0_200/CMSSW_9_0_0_pre5-90X_upgrade2017_realistic_v15-v1/GEN-SIM
```
which is not available (at least DAS and DBS does not show any record of it).
Previously, the dataset used for this workflow was using
```
dataset=/RelValTenMuE_0_200/CMSSW_9_0_0_pre4-90X_upgrade2017_realistic_v6-v1/GEN-SIM
```
any idea why new dataset is not available and what can be done to get this workflow working again?

**Comment by fabozzi** [comment]
Hi, Thank you for notifying. We removed from the relval list we are submitting. We can restore it and fix this.

**Comment by davidlange6** [comment]
or just remove the workflow and cff if its obsolete..

**Comment by fabozzi** [comment]
I have made PR #17858 to fix this. I can make same PR for 91X.

**Pull request merged**
