### PR TITLE
Improve memory handling in CmsDetConstruction

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

static analyzer identified a code path that would leak memory. Changing to std::unique_ptr solves the issue.

#### PR validation:

Code compiles.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
@makortel FYI

**Comment by civanch** [comment]
+1

Regression problem due to MkFit - not related to this PR.

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
