### PR TITLE
Run3-gex115A Tune CaloGeometryBuilder for changing CMS configuration - backport #36814

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Tune CaloGeometryBuilder for changing CMS configuration - backport #36814

#### PR validation:

The original PR is tested using the runTheMatrix test workflows

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Backport PR #36814

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
+1

**Comment by tvami** [comment]
urgent
 * we need this for DD4HEP data tests

**Comment by tvami** [comment]
type bugfix

**Comment by perrotta** [comment]
+1
- Following discussion at today's ORP

**Comment by tvami** [comment]
@bsunanda can you please change the title so it says that it removes Castor from Run3? Also please include [12_2_X] in the title so it's obvious that the backport is for that release

**Comment by tvami** [comment]
@perrotta I think you merged the backport first and not the master PR

**Comment by tvami** [comment]
backport of https://github.com/cms-sw/cmssw/pull/36814

**Comment by perrotta** [comment]
> @perrotta I think you merged the backport first and not the master PR first

Yes, you are right, sorry for that... I did not suppose that the "urgent" flag was for the backport PR, as all PRs to be backported are kind of urgent...
Ok, since it is already merged, let have the two (master and 12_2) merged at the same time: in case of issues, not expected anyhow, we will revert this one.

**Comment by tvami** [comment]
> I did not suppose that the "urgent" flag was for the backport PR,

Sorry about that!

**Pull request merged**
