### PR TITLE
Fix typo in handling exclusion of CALOL2 in online DQM (93x backport)

### PR DESCRIPTION
**Pull request by ashtipliyski**
This is a 93x back-port of PR #20743.

### CODE REVIEW

**Comment by dmitrijus** [comment]
Why is this a backport 93x? Online DQM runs 92x.

**Comment by ashtipliyski** [comment]
Hi @dmitrijus,

This backport was made in anticipation of the eventual migration of production DQM to 93X. 

When the original PR (to which this is a patch) was created, I was asked by Tomas Hreus to submit it against 94X with backport for 93X. Hence, for this update, I assumed that the same requirement still applies.

Please let me know if you see things differently.

Thanks

**Comment by dmitrijus** [comment]
I don't think online DQM will ever run 93x - we will move to 94x (or higher) next year.
93x had specific goals, so there is no need to merge this PR into 93x.

**Comment by ashtipliyski** [comment]
That sounds good to me. The only purpose of this PR was to meet the operational constraints of DQM. If you are confident that this will not be necessary, I am perfectly happy with closing it.

**Comment by thomreis** [comment]
Hi @ashtipliyski 
this one can be closed?

**Pull request closed without merging**
