### PR TITLE
Run3-TB50 Update geometry of the EE section (Shilpi)

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Correct thickness of absorbers in the EE compartment of 2018 October test beam setups for high granularity calorimeter tests at CERN

#### PR validation:

Tested using cfg files in SimG4CMS/HGCalTestBeam/test

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
+1

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
+1

**Comment by silviodonato** [comment]
Do you have any comments? @kpedro88

**Comment by kpedro88** [comment]
+upgrade

**Comment by silviodonato** [comment]
+1

**Pull request merged**
