### PR TITLE
MTD geometry: add final proposed scenario (flat bars along phi) D38, fix the BTLDetId ieta navigation method

### PR DESCRIPTION
**Pull request by fabiocos**
The final choice for the MTD geometry in view of TDR is a flat bars layout with the long side along phi: [https://indico.cern.ch/event/777879/contributions/3237688/attachments/1771743/2879703/MTD_ASIC_PRR_20181214.pdf](url) . This PR provides an implementation of this setup as upgrade scenario D38. The module layout is shown in the picture:

crystalbarphiflat_1

This scenario is based on 48 modules (3 groups of 16 with changing thickness).

In this PR there is also a fix for the ieta navigation method in BTLDetId, not used so far in digitization and reconstruction but only for analysis. The behaviour was correct for the positive side, but for the negative side it inverted the ordering wrt the intended one, i.e. (... -8 -1 -2 -3 -4 1 2 3 ..) in the transition between negative and positive modules instead of (... -5 -4 -3 -2 -1 1 2 3). The problem is related to the fact that the crystal number 1 for negative side modules is the farthest and not the closest one to the MTD midwall. The fix is extended to the hashedIndex (not used for the time being). 

Test workflows are provided, and the digitization is updated to account for the new scenario.

### CODE REVIEW

**Comment by fabiocos** [comment]
please test workflow 27834.0

**Comment by kpedro88** [comment]
@fabiocos @pmeridian @lgray does this mean all the D35 samples generated so far for the TDR will be discarded?

Please update `Configuration/Geometry/README.md` with the details of the new geometry.

**Comment by fabiocos** [comment]
@kpedro88 I let @pmeridian and @lgray to better comment on the overall plan, this is the final scenario to be described in the TDR. There are two noticeable differences: the bar orientation (that was finally agreed after the GEN-SIM production had started) and the thickness of part of the crystals.
In my understanding the centrally produced samples may still be useful for general physics studies, but they will need to be complemented with dedicated samples with this updated geometry for local observables definition. Some studies with this geometry have been already produced by @abenagli .
We need to agree also on an intermediate scenario to disentangle the effect of LYSO thickness from the effect of bar orientation.

**Comment by kpedro88** [comment]
please test workflow 27834.0

**Comment by cvuosalo** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade

**Comment by civanch** [comment]
+1

**Comment by fabiocos** [comment]
@prebello @zhenhu any comment?

**Comment by fabiocos** [comment]
+operations

**Comment by prebello** [comment]
+1

 @fabiocos looks fine

**Comment by fabiocos** [comment]
+1

**Pull request merged**
