### PR TITLE
DD Element Registry Cleanup

### PR DESCRIPTION
**Pull request by ianna**
* Use shared pointers for proper memory management
* Remove complicated cleanup
* Remove commented out lines

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
@slava77 - I do not understand why 25202.0 and 50202.0 comparison tests fail while all others are not affected. Could it really be due to this PR or is there an out-of date reference? Please, have a look and let me know if I need to debug the DD code. Thanks.

**Comment by slava77** [comment]
On 4/26/17 6:04 AM, Ianna Osborne wrote:
> @slava77 <https://github.com/slava77> - I do not understand why 25202.0
> and 50202.0 comparison tests fail while all others are not affected.
> Could it really be due to this PR or is there an out-of date reference?
> Please, have a look and let me know if I need to debug the DD code. Thanks.

There are apparently some memory or related problems in the digi step
with mixing included.
Someone should run a valgrind check of step2 to see what's happening.
Maybe it can even show up in no-PU with some mem randomization effort,
to finish in under a week of CPU time.

**Comment by ianna** [comment]
+1

**Pull request merged**
