### PR TITLE
Multi run harvesting for 8 0 x

### PR DESCRIPTION
**Pull request by dimattia**
Greetings,

this PR implements the correct setting of the IOV of the gain calibration payload produced with the multi run harvesting procedure in PCL. Currently the IOV is set to the "oldest" run analyzed in the harvesting step.

It also include a fix delivered by Marco Musich in #14949

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
+1

**Comment by ggovi** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
