### PR TITLE
Allow selection of subdetector for track splitting

### PR DESCRIPTION
**Pull request by hroskes**
Focus track splitting validation on any subdetector by requiring 2 hits there.  The default is still BPIX (which was hardcoded before).

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by hroskes** [comment]
Is something wrong?  The tests are taking longer than usual...

**Comment by mmusich** [comment]
@hroskes seems the tests are stuck (at least I cannot access the details)
@cmsbuild could the tests be restarted?

**Comment by Dr15Jones** [comment]
please test

**Comment by hroskes** [comment]
@mmusich @cmsbuild
I added 2 more (trivial but useful) commits, hopefully @cmsbuild will reset and be happier this time

**Comment by mmusich** [comment]
@cmsbuild  please test

**Comment by mmusich** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
