### PR TITLE
Restoring egamma DQM sequence for allForPrompt  (100X)

### PR DESCRIPTION
**Pull request by fabozzi**
Fix to restore the egamma folder that is found to be missing in data certification of data re-reco

### CODE REVIEW

**Comment by fabozzi** [comment]
backport of PR #22013

**Comment by dmitrijus** [comment]
This needs that one additional commit from the #22013

**Comment by fabozzi** [comment]
now added

**Comment by dmitrijus** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
