### PR TITLE
Herwig7 jet partonFlavour (10_6_X)

### PR DESCRIPTION
**Pull request by mseidel42**
#### PR description:

Backport of https://github.com/cms-sw/cmssw/pull/26885

Needed for jet flavor correction / uncertainty studies to distinguish light quark and gluon jets. Will ask for new 10_6 release and reprocessing of Herwig7 JMENanos afterwards.

Note that will also fix the issue for any newly produced MiniAods.

#### PR validation:

`Jet_partonFlavour` becomes available in `TT_TuneCH3_13TeV-powheg-herwig7` JMENano after applying patches:
```
 Jet_hadronFlavour = 0,                                                                                                                                                                                     
                  4, 5, 5, 0, 0, 0, 0, 0, 0, 0,                                                                                                                                                             
                  0, 0, 0, 0, 0, 0, 0, 0, 0                                                                                                                                                                 
 Jet_partonFlavour = -2,                                                                                                                                                                                    
                  4, 5, -5, 21, -3, 0, 1, 21, 0, -2,                                                                                                                                                        
                  0, 0, 21, 0, 21, 21, 0, 0, 2
```

@cms-sw/jetmet-pog-l2 FYI

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
assign generators
Please @cms-sw/generators-l2  confirm with your signature that this PR, originally merged in master more that three years ago, is now also needed in 10_6_X

**Comment by perrotta** [comment]
please test
(to refresh the comparisons, as it is not clear to me why there should be differences in the HI workflows)

**Comment by Saptaparna** [comment]
Let me add our HERWIG experts @Dominic-Stafford and @theofil to this thread.

**Comment by Saptaparna** [comment]
@mseidel42 this is what is expected right (reference to Andrea's message)? I am fine with merging, but let's double check just in case.

**Comment by Dominic-Stafford** [comment]
@perrotta do you have a link to the ORP meeting, please?

**Comment by Dominic-Stafford** [comment]
But in general I agree with Sapta, I don't see an issue with changing the parton content here since it's just adding information that wasn't there before

**Comment by Saptaparna** [comment]
here it is: https://indico.cern.ch/event/1208161/

**Comment by mseidel42** [comment]
Hi all, I need to have a closer look at the HydJet event record.

If blue=old and red=new then things would make sense: previously missed gluons are now taken into account for the jet flavor.

**Comment by perrotta** [comment]
As discussed at the ORP meeting right now, the issue is not whether the change makes sense or not, but rather whether we can modify GenJets in some frozen produced release. It was agreed with @Dominic-Stafford that the update will be ruled by a modifyer, so that only the dedicately produced MC samples will have it included

**Comment by mseidel42** [comment]
Hi, that's an overengineered and error-prone (because it requires manual intervention) solution to a non-problem. We are just fixing partonFlavour for samples where it was broken and completely unusable before. If anybody was actually using those 0 values they need to repeat their study with a fixed sample.

If you prefer I can revert e16c4214a30d268213ede910a3e7af8c01370b24 and just leave the minimally invasive bbfc5d1990532c737374aa1ce4088084b2e048ff, fixing the issue for Herwig7 samples (that we are interested in for jet flavor studies that can just not be done with the buggy samples) but leaving other "exotic" samples with the bug.

**Comment by mseidel42** [comment]
For a non-code solution we could just close this PR and run the specific requests with `--customise PhysicsTools/NanoAOD/custom_jme_cff.PrepJMECustomNanoAOD_MC --customise_commands process.patJetPartons.partonMode=\"Herwig++\"`. The JME modifier is needed in any case as we need JMENano, which overwrites the flavor information from MiniAod.

**Comment by rappoccio** [comment]
+1 

Per discussion at ORP, PDMV agrees to document future workflows appropriately with the bug fix, agreed at the meeting to merge.

**Comment by perrotta** [comment]
Should this get closed in favor of #39971? Once [fixed](https://github.com/cms-sw/cmssw/pull/39971#pullrequestreview-1193061099) that PR would be the cleaner solution.

Still I don't know whether any different decisione was decided at the [ORP on nov 15](https://indico.cern.ch/event/1208167/) , at which I was unable to participate. 

@rappoccio @cms-sw/pdmv-l2 could you please summarize it here, so that we can close the unneeded PR?

**Comment by mseidel42** [comment]
Hi Andrea,

On 15 Nov we agreed that this PR would be merged and new samples with the bugfix marked by PdmV.

This would have the advantage that all new samples with Herwig7 (which was missed) and non-standard generators will finally have a meaningful partonFlavour for the jets. We would also have agreement again with the default behavior in both Run 1 and Run 3 production.

As long as 10_6 is relevant for Run 2 analysis I really don't see any value in producing new samples without the proper flavor information. The information is also usually not used in analysis, so it should not break anyone's workflow, while enabling us to do precision studies on jet flavor response.

Best,
Markus

**Comment by perrotta** [comment]
Dear Markus, thank you for your message.
Unfortunately I could not be present at the ORP meeting of nov 15. However, I read in the minutes that the agreement was exactly the one that you are reporting here, therefore we will likely merge this PR and cut the release with it.

However; I think this is a wrong decision, and I would like to ask explicitely the confirmation by @cms-sw/pdmv-l2 .
It is wrong exactly because of what you say: samples with correct and wrong hervig should be made easily distinguishable, and the modifier (which can be applied to all productions in 10_6 from now on) has exactly that purpose.

In any case, I don't want to revert any decision taken. Therefore, if  @cms-sw/pdmv-l2 confirms that this is really what they plan for the 10_6 cycle, I'll merge this PR and make a new release with it. (Otherwise, we will merge https://github.com/cms-sw/cmssw/pull/39971 and make a release with it: therefore, the release with the fix will become available anyhow in the next few days).

**Comment by bbilin** [comment]
Dear Andrea,

Given that we need a new chained campaign for Herwig samples anyways to be able to do JMENano, and provided these will affect only few samples and not affecting anything else, we can handle it internally in PdmV management to add a bugfix tag to the new Herwig samples.

Best,

B.

**Comment by perrotta** [comment]
please test
(to refresh the more than one month old tests)

**Comment by perrotta** [comment]
+1
- As deemed acceptable by PPD

**Pull request merged**
