### PR TITLE
Add all direct deps to BuildFile for RecoTracker/TkTrackingRegions

### PR DESCRIPTION
**Pull request by davidlange6**
for all packages that still should be made into cxx modules (well, current list of them). Additions made by looking for packages directly included in interface or src.

### CODE REVIEW

**Comment by vgvassilev** [comment]
The meta issue #15248 tracks the C++ modules-related work.

**Comment by davidlange6** [comment]
please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/30414	1092b25 
- technical

**Comment by silviodonato** [comment]
+1

**Pull request merged**
