### PR TITLE
alignment (asy and real) Consistent with Fpix updated Thickness (290 instead of 300 mum)

### PR DESCRIPTION
**Pull request by franzoni**
# Summary of changes in Global Tags
This PR address the discussion originating from this comment : https://github.com/cms-sw/cmssw/pull/17319#issuecomment-276076558 

## RunII simulation

   * **PhaseI 2017 cosmics scenario** : [90X_upgrade2017cosmics_realistic_peak_v6](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_upgrade2017cosmics_realistic_peak_v6) as [90X_upgrade2017cosmics_realistic_peak_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_upgrade2017cosmics_realistic_peak_v5) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/90X_upgrade2017cosmics_realistic_peak_v6/90X_upgrade2017cosmics_realistic_peak_v5):
      * updated tracker alignment to be consistent with the FPIX updated sensor thickness measurement (290 mum instead of 300, see https://github.com/cms-sw/cmssw/pull/17245 )

   * **PhaseI 2017 design scenario** : [90X_upgrade2017_design_IdealBS_v6](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_upgrade2017_design_IdealBS_v6) as [90X_upgrade2017_design_IdealBS_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_upgrade2017_design_IdealBS_v5) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/90X_upgrade2017_design_IdealBS_v6/90X_upgrade2017_design_IdealBS_v5):
      * updated tracker alignment to be consistent with the FPIX updated sensor thickness measurement (290 mum instead of 300, see https://github.com/cms-sw/cmssw/pull/17245 )

   * **PhaseI 2017 realistic scenario** : [90X_upgrade2017_realistic_v6](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_upgrade2017_realistic_v6) as [90X_upgrade2017_realistic_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_upgrade2017_realistic_v5) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/90X_upgrade2017_realistic_v6/90X_upgrade2017_realistic_v5):
      * updated tracker alignment to be consistent with the FPIX updated sensor thickness measurement (290 mum instead of 300, see https://github.com/cms-sw/cmssw/pull/17245 )

   * **PhaseI 2018 cosmics scenario** : [90X_upgrade2018cosmics_realistic_peak_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_upgrade2018cosmics_realistic_peak_v4) as [90X_upgrade2018cosmics_realistic_peak_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_upgrade2018cosmics_realistic_peak_v3) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/90X_upgrade2018cosmics_realistic_peak_v4/90X_upgrade2018cosmics_realistic_peak_v3):
      * updated tracker alignment to be consistent with the FPIX updated sensor thickness measurement (290 mum instead of 300, see https://github.com/cms-sw/cmssw/pull/17245 )

   * **PhaseI 2018 design scenario** : [90X_upgrade2018_design_IdealBS_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_upgrade2018_design_IdealBS_v4) as [90X_upgrade2018_design_IdealBS_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_upgrade2018_design_IdealBS_v3) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/90X_upgrade2018_design_IdealBS_v4/90X_upgrade2018_design_IdealBS_v3):
      * updated tracker alignment to be consistent with the FPIX updated sensor thickness measurement (290 mum instead of 300, see https://github.com/cms-sw/cmssw/pull/17245 )

   * **PhaseI 2018 realistic scenario** : [90X_upgrade2018_realistic_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_upgrade2018_realistic_v4) as [90X_upgrade2018_realistic_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_upgrade2018_realistic_v3) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/90X_upgrade2018_realistic_v4/90X_upgrade2018_realistic_v3):
      * updated tracker alignment to be consistent with the FPIX updated sensor thickness measurement (290 mum instead of 300, see https://github.com/cms-sw/cmssw/pull/17245 )

### CODE REVIEW

**Comment by franzoni** [comment]
thanks @ghellwig @arunhep

**Comment by franzoni** [comment]
please test

**Comment by franzoni** [comment]
@makortel @rovere @VinInn
please take note of this

**Comment by makortel** [comment]
Thanks @franzoni

**Comment by franzoni** [comment]
Thanks @davidlange6

**Pull request merged**
