### PR TITLE
[14_0_X] Simplify definition of `PortableMultiCollection<TDev, ...>`, and allow it to be used outside of `ALPAKA_ACCELERATOR_NAMESPACE`

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

Backport of https://github.com/cms-sw/cmssw/pull/43983. Description of the original PR:

> I.e. repeat #43310 on PortableMultiCollection (that was added in https://github.com/cms-sw/cmssw/pull/40285).

#### PR validation:

None beyond the tests of https://github.com/cms-sw/cmssw/pull/43983

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport of https://github.com/cms-sw/cmssw/pull/43983

### CODE REVIEW

**Comment by makortel** [comment]
enable gpu

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
+heterogeneous

**Comment by makortel** [comment]
Comparisons show the usual
* https://github.com/cms-sw/cmssw/issues/43293
* https://github.com/cms-sw/cmssw/issues/43790

**Comment by antoniovilela** [comment]
backport of https://github.com/cms-sw/cmssw/pull/43983

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
