### PR TITLE
DD4hep: Allow Multiple EventSetup Records

### PR DESCRIPTION
**Pull request by ianna**
* Add a product label to allow multiple producers 
* Update configuration files

### CODE REVIEW

**Comment by ianna** [comment]
+1

@fabiocos - FYI, the differences in comparison results are not related to this PR

**Comment by ianna** [comment]
+1

**Comment by fabiocos** [comment]
@ianna just one minor thing: do we want to keep all the "cout"s? For test plugins is likely not so important, but in case would not be better to move to MessageLogger?

**Comment by ianna** [comment]
@fabiocos - I agree, I use cout for a quick feedback and will move to a MessageLogger for a production version of the ES producers. I find it's a bit of an overhead to have a MessageLogger configuration included for the tests.

**Pull request merged**
