### PR TITLE
[124X] Change LG and HG Tk PCL output tags

### PR DESCRIPTION
**Pull request by tvami**
#### PR description:

See https://github.com/cms-sw/cmssw/pull/39553/

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport of https://github.com/cms-sw/cmssw/pull/39553/

### CODE REVIEW

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by ChrisMisan** [comment]
backport of #39553

**Comment by ChrisMisan** [comment]
+alca

- differences only in MTD and msgLogger
- backport ok

**Comment by tvami** [comment]
+db

**Comment by perrotta** [comment]
+1

**Pull request merged**
