### PR TITLE
Monopole skim 80

### PR DESCRIPTION
**Pull request by srimanob**
PR for rereco+skim 2016 Data, for monopole analysis

### CODE REVIEW

**Comment by fabozzi** [comment]
backport of #19567

**Comment by fabozzi** [comment]
please test

**Comment by fabozzi** [comment]
please test

**Comment by srimanob** [comment]
@fabozzi @kfjack @davidlange6 
Here is for 80X, could you please check and test?

**Comment by kpedro88** [comment]
which workflow number needs to be tested here?

**Comment by kfjack** [comment]
If we take the workflow for 2016B, the numbers are 136.725 and 136.731.

**Comment by kpedro88** [comment]
please test workflow 136.725

**Comment by fabozzi** [comment]
+1

**Comment by srimanob** [comment]
Tested the output, EXOMONOPOLE.root, in https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-19530/21260/runTheMatrix-results/136.731_RunSinglePh2016B+RunSinglePh2016B+HLTDR2_2016+RECODR2_2016reHLT_skimSinglePh+HARVESTDR2/
It looks OK, all collections we need are in. We can run our analysis framework on it.

**Comment by kpedro88** [comment]
+1

**Comment by davidlange6** [comment]
merge

**Pull request merged**
