### PR TITLE
clang check boost-use-to-string

### PR DESCRIPTION
**Pull request by davidlange6**
for comment about what clang-tidy does to CMSSW (and likely big and not mergeable - this is what clang-tidy check boost-use-to-string does on the tip of CMSSW_9_3_X as of a few days ago

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
please test

**Comment by slava77** [comment]
-1

this technically looks OK, but it should compile

**Comment by ianna** [comment]
+1

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
please test

the compilation error seems unrelated - i wonder if it reproduces

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
merge

**Pull request merged**
