### PR TITLE
Fix HF TP Scale.

### PR DESCRIPTION
**Pull request by akhukhun**
Fixing new HF TP scale in the emulator and (un)-compression LUTs.

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by jimbrooke** [comment]
Does this PR have an impact on L1 trigger jet energy scales?

**Comment by akhukhun** [comment]
This PR should not change anything for the RCT 3x2 TPs.
It uses correct scale for new 1x1 TPs in the emulator (so that it's not off by a factor of 4 if based on the RCTlsb value) and, respectively, sets the corresponding scale for TP uncompression tables in the "Transcoder".

**Comment by jimbrooke** [comment]
Thanks.  I am asking about the 2016 jet trigger, which uses 1x1 TPs.  We already see reasonable energy scale (definitely not off by factor 4!) and we used 800pre6 TPs to derive jet energy correction factors.  But we will try running with this PR.

**Comment by akhukhun** [comment]
I see. I guess as long as the scales are consistent in the TP emulator and de-compression tables, to first order you should get the same result, up-to granularity/rounding effects. So in your setup I believe you were using RCT scale in both. 
Now, I suspect, depending on what gets used for TP decompression in the L1 emulation, CaloTPGTranscoder or pre-generated tables, (which unfortunately I do not know), you may or may not get factor of 4 different results. In the latter case, I think the tables should be re-generated.

**Comment by abdoulline** [comment]
Dear colleagues
 @franzoni, @mmusich, @mulhearn 
 can you please review it and eventually sign? Thanks.

We need to have it in 80X for _correct_ HF TPs scale...

**Comment by mulhearn** [comment]
+1

**Comment by mmusich** [comment]
+1

**Comment by davidlange6** [comment]
@akhukhun @abdoulline -so what happens with 2015 MC after this PR?

**Comment by abdoulline** [comment]
My understanding is - it only affects 1x1 HF TPs (2016 era).

**Comment by kpedro88** [comment]
@davidlange6 - I didn't realize this wasn't merged yet or I would have put it on the ORP list yesterday. Is there any holdup?

**Comment by davidlange6** [comment]
+1
seems not.

**Pull request merged**
