### PR TITLE
Fix trigger matching issues in L1Trigger DQMOffline

### PR DESCRIPTION
**Pull request by abrinke1**
#### PR description:

Fixed issue in L1T Offline DQM preventing HLT objects from being found, which leads to empty Muon and EGamma efficiency plots.  Tested in l1t-integration here:
https://github.com/cms-l1t-offline/cmssw/pull/1051

#### PR validation:

cmsDriver.py step2 --conditions 124X_dataRun3_Prompt_v4 --data --datatier RECO,DQMIO --era Run3 --eventcontent RECO,DQM --filein file:/eos/cms/store/data/Run2022C/Muon/RAW/v1/000/356/570/00000/a76e1b83-d169-4db6-8009-96d7b76ee22c.root --fileout file:step2.root --nStreams 2 --nThreads 8 --no_exec --number 10 --process RECO --python_filename step_2L1T_cfg.py --scenario pp --step RAW2DIGI,L1Reco,RECO,DQM:@L1TMuon

cmsDriver.py step3 --conditions 124X_dataRun3_Prompt_v4 --data --era Run3 --filein file:step2_inDQM.root --fileout file:step3.root --filetype DQM --nStreams 2 --no_exec --number 10 --python_filename step_3_cfg.py --scenario pp --step HARVESTING:DQMHarvestL1TMuon

Also can run the above replacing "L1TMuon" with "L1TEgamma", and with the following input file:
/eos/cms/store/data/Run2022C/EGamma/RAW/v1/000/356/570/00000/aa8267bc-e993-4ed2-920e-6349cc460523.root

### CODE REVIEW

**Comment by abrinke1** [comment]
Please take a look @epalencia , @cecilecaillol , and @vukasinmilosevic .

**Comment by cecilecaillol** [comment]
@abrinke1 Thanks! Could you run "scram build code-checks" and "scram build code-format"? Could you please also replace all the couts with edmLogError/Warning/... ?

**Comment by abrinke1** [comment]
Hi @cecilecaillol , thanks for the instructions: all code-checks should be implemented.  All of the new "cout" statements are connected with the "m_verbose" flag, which is only used for developer testing and debugging, and is set here:
https://github.com/cms-sw/cmssw/blob/master/DQMOffline/L1Trigger/python/L1TMuonDQMOffline_cfi.py#L76

These "cout" statements are not really warnings at all, and this follows the existing code approach:
https://github.com/cms-sw/cmssw/blob/master/DQMOffline/L1Trigger/src/L1TMuonDQMOffline.cc#L178

**Comment by epalencia** [comment]
Please test

**Comment by cecilecaillol** [comment]
@abrinke1 I understand these couts are related to the verbose mode and are not errors or warnings, but couts are not allowed in CMSSW code anymore. You could use edmLogInfo (all possibilities detailed in https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideMessageLogger)

**Comment by abrinke1** [comment]
Hi @cecilecaillol , should be all set - just need the jenkins test.

**Comment by epalencia** [comment]
Please test

**Comment by cecilecaillol** [comment]
please test

**Comment by cecilecaillol** [comment]
+l1

**Comment by emanueleusai** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
