### PR TITLE
Binning fixes, calibration patch, cosmics false alarm fix, noise tolerance (for CMSSW master)

### PR DESCRIPTION
**Pull request by tanmaymudholkar**
This PR reintroduces a few changes that were merged with the production CMSSW version last year but were not integrated with CMSSW master. In addition, there are a couple of new commits implementing some changes requested by ECAL experts. Here is a summary of the changes:

---> From 2017:

(1) Fixed bug in binning that led to incorrect bin numbers while filling many 2D histograms by supercrystal based on the electronics ID.

(2) Using beam status information from TCDS Digis, implemented a mask on the usual false alarms on TP occupancy during cosmics for ECAL.

---> New commits:

(3) Improved patch to ignore events causing ECAL DQM Calibration application crashes. This was what caused the delay in merging my commits into CMSSW master last year -- at the time, the code used a try-catch block which was not good from the efficiency point of view. This try-catch block has now been replaced with a much simpler if condition.

(4) Modified noise tolerance in presample plots to range (175, 240) ADC counts instead of the current (175, 225) ADC counts, because the pedestal value in some towers has been drifting higher especially in the endcaps causing the presample plots to be liberally peppered with RED channels.

Link to the corresponding PR to CMSSW P5 production version: https://github.com/cms-sw/cmssw/pull/22688

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
@tanmaymudholkar I see that the differences reported above are all in the wf 136.788 for EcalEndcap, are they consistent with the expectation from the code change?

**Review by fabiocos — COMMENTED** [review]
What is the reason for this code change?

**Comment by tanmaymudholkar** [comment]
@fabiocos : I looked into the differences.

I assume you are referring to the differences in this [log](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_10_2_X_2018-04-01-1100+22689/25947/136.788_RunSinglePh2017B+RunSinglePh2017B+HLTDR2_2017+RECODR2_2017reHLT_skimSinglePh_Prompt+HARVEST2017RelMonComp-136.788.log
) ; there are several difference in the main body and summarized towards the end.

These changes are indeed quite expected (and, in fact, welcome); they are due to [this commit](https://github.com/cms-sw/cmssw/pull/22689/commits/023865908790852da0e5570b2c3070f358f83c3b).

The reason behind this commit was that over the last few years, we have seen an upward creep of the pedestal values in ECAL, especially in the high eta regions in the endcaps. These pedestals, at one point, were set by hardware to a value of 200 ADCs, but some of them now have a mean pedestal of 230 ADC or even higher. This is understood to be due to several factors including radiation damage, and is well-known to the experts. Earlier, DQM used to trigger quality RED when the pedestal value was more than 25 ADC away from the nominal value of 200 ADCs (i.e. quality RED outside the range 175-->225 ADC). This meant that the DQM shifter saw several RED channels; especially for new shifters, they could not decide whether this behavior was nominal, and we had a few false alarms.

With this fix we have increased the tolerance to 175-->240 ADCs, and the quality checks are propagated forward, thus making those plots different that I would expect to be different.

As for why this isn't seen in other workflows, I am not quite sure. Perhaps some collection tags were changed and the noise plots were not populated at all?

**Comment by fabiocos** [comment]
@tanmaymudholkar thanks for the confirmation

**Comment by fabiocos** [comment]
+1

**Pull request merged**
