### PR TITLE
add plots of wire group and strip numbers for all chambers

### PR DESCRIPTION
**Pull request by rjwang**
add plots of wire group and strip numbers for all chambers, debug csctflcts with endcap swapped, clean some blanks

### CODE REVIEW

**Comment by rjwang** [comment]
Does this error related with this PR? I cannot see where is the problem, it works for me locally.

**Comment by deguio** [comment]
error not related.

**Comment by danduggan** [comment]
i rebased this guy (in #8191) to easily be added on top of 732patch5. this can be closed.

**Comment by rjwang** [comment]
Thanks, Dan !

**Comment by deguio** [comment]
-1

**Pull request closed without merging**
