### PR TITLE
[92X] L1 no Hack Conditions

### PR DESCRIPTION
**Pull request by rekovic**
Removing Hack Conditions from L1Trigger package, 
and start using configurations from DB, via GTs.

Ajdustements to AddOn workflows with 2015 data have been made. 

Backport of  #20577.

### CODE REVIEW

**Comment by rekovic** [comment]
backport of #20577.

**Comment by rekovic** [comment]
please test

**Comment by kkotov** [comment]
@rekovic, @Martin-Grunewald , I bet for this backport we also need something like
https://github.com/cms-sw/cmssw/commit/3c48dba224002cfb7883bde77748c2c09ce29a22#diff-5b29e53ee0c1d396908444c2711d39f6
but for this PR.

**Comment by arunhep** [comment]
@kkotov @rekovic 

There are two kind of errors.

1. no presence of L1TMuonOverlapParamsRcd. And the log file is below.

https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-20644/23205/runTheMatrix-results/135.4_ZEE_13+ZEEFS_13+HARVESTUP15FS+MINIAODMCUP15FS/step1_ZEE_13+ZEEFS_13+HARVESTUP15FS+MINIAODMCUP15FS.log

For this you need a GT update to include L1TMuonOverlapParams_static_2016_mc tag for run2MC key.
Do you confirm that this is the tag you want to add? I will provide the commit in that case.

2. https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-20644/23205/runTheMatrix-results/10024.0_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2017_GenSimFull+DigiFull_2017+RecoFull_2017+ALCAFull_2017+HARVESTFull_2017/step2_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2017_GenSimFull+DigiFull_2017+RecoFull_2017+ALCAFull_2017+HARVESTFull_2017.log

which I don't know may be related to the customization you mentioned above.

**Comment by kkotov** [comment]
@arunhep , I've missed the problem of the first type. Indeed, we need L1TMuonOverlapParams_static_2016 in the 92X GTs used in the tests.

**Comment by Martin-Grunewald** [comment]
@kkotov - why does this PR need that 94X custom part? Can it be separated out?

**Comment by kkotov** [comment]
@Martin-Grunewald, @rekovic 
I think in order for this backporting PR to work we need to also backport the "supporting" PRs that we've introduced to 94X in order for the noHackConditions to pass the tests there. This, as far as I remember, includes #19989 that had customizeHLT, but also few more  things in it.

**Comment by arunhep** [comment]
@rekovic this commit https://github.com/arunhep/cmssw/commit/e5ed47261b06196279903538c56b2a10356dd3ec
should address the following issue : https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-20644/23205/runTheMatrix-results/135.4_ZEE_13+ZEEFS_13+HARVESTUP15FS+MINIAODMCUP15FS/step1_ZEE_13+ZEEFS_13+HARVESTUP15FS+MINIAODMCUP15FS.log

**Comment by arunhep** [comment]
this should be closed as #20689 overwrites it.

**Comment by arunhep** [comment]
-1
just to remove from the list

**Comment by dmitrijus** [comment]
@rekovic please close this

**Comment by Martin-Grunewald** [comment]
-1
superseeded by #20689

**Pull request closed without merging**
