### PR TITLE
Phase2-hgx335F Update the test scripts in Geometry/HGCalCommonData and Geometry/HGCalGeometry in view of using Eras

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Update the test scripts in Geometry/HGCalCommonData and Geometry/HGCalGeometry in view of using Eras

#### PR validation:

Test the scripts used for testing various aspects of HGCal geometry

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

Update test scripts, no change is expected from this PR.

**Comment by perrotta** [comment]
+1

**Pull request merged**
