### PR TITLE
Adding first version of electronics id class for HGCAL

### PR DESCRIPTION
**Pull request by pfs**
#### PR description:

When decoding or emulating realistic DIGI it may beneficial to include an intermediate Electronics ID. 
This PR introduces such class to enable the developments on the logical mapping of HGCAL and on the raw data unpacker which are on-going. The class is a simple wrapper of a 32b word. The contents of which correspond to the following table/counting of entities.

image

#### PR validation:

A test unit is included in the PR and has been used to check the class holds and decodes the required values.
It can be run with 
```
$CMSSW_BASE/test/$SCRAM_ARCH/HGCalElectronicsId [#repetitions] [verbosity level]
```

### CODE REVIEW

**Comment by pfs** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

Note to @cms-sw/hcal-dpg-l2 in case you have a comment.

**Comment by perrotta** [comment]
+1

**Pull request merged**
