### PR TITLE
Added include of cassert to Migration.h

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

This is needed for the ROOT modules build.

#### PR validation:

The code compiles.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by makortel** [comment]
> * Reco comparison results: 8 differences found in the comparisons

One of these is in workflow 1325.81 in `nanoaodFlatTable_tauTable__DQM_obj_floats__rawDeepTau2017v2p1VSmu`. https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_11_3_X_2021-01-08-1100+aa6c04/40755/validateJR/all_OldVSNew_TTbar13nanoEDM106Xv1in2017wf1325p81/all_OldVSNew_TTbar13nanoEDM106Xv1in2017wf1325p81c_nanoaodFlatTable_tauTable__DQM_obj_floats__rawDeepTau2017v2p1VSmu_442.png
image


I can not imagine how the change of this PR could cause that. @cms-sw/reconstruction-l2 @cms-sw/xpog-l2 is there perhaps a known non-reproducibility in DeepTau? (I did not quickly find an open issue about such)

**Comment by Dr15Jones** [comment]
please test

**Comment by mariadalfonso** [comment]
@makortel 

indeed we have already seen some sign of reproducibility issue
https://github.com/cms-sw/cms-bot/pull/1456#issuecomment-750900565

**Comment by slava77** [comment]
> One of these is in workflow 1325.81 in `nanoaodFlatTable_tauTable__DQM_obj_floats__rawDeepTau2017v2p1VSmu`. https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_11_3_X_2021-01-08-1100+aa6c04/40755/validateJR/all_OldVSNew_TTbar13nanoEDM106Xv1in2017wf1325p81/all_OldVSNew_TTbar13nanoEDM106Xv1in2017wf1325p81c_nanoaodFlatTable_tauTable__DQM_obj_floats__rawDeepTau2017v2p1VSmu_442.png

I've seen this before in the tests of cms-sw/cms-bot#1456

it's perhaps time to make an issue

**Comment by makortel** [comment]
@mariadalfonso @slava77 


> indeed we have already seen some sign of reproducibility issue
> [cms-sw/cms-bot#1456 (comment)](https://github.com/cms-sw/cms-bot/pull/1456#issuecomment-750900565)

Thanks, I had a vague recollection of something like that but was not able to find anything.

> it's perhaps time to make an issue

Done in https://github.com/cms-sw/cmssw/issues/32628.

**Comment by makortel** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
