### PR TITLE
Add option to cut H<a+bE+cE*E

### PR DESCRIPTION
**Pull request by bennettgberg**
#### PR description:

Adds an option to change the H/E cut to take the form H<a+bE+cE^2 for constants a, b, c. 
  This will be needed for Egamma objects in upcoming changes to the Scouting trigger.
  Default behavior stays unchanged.
  - No changes in output 
  - No external dependencies
  - slides presented to TSG on the change in Scouting: https://indico.cern.ch/event/1186562/contributions/4992593/attachments/2489115/4274414/electronScouting_22-08-03.pdf 
  In particular, slide 10 shows the physics motivation--large increase in low-pT scouting electron signal reconstruction efficiency resulting from changing this cut.

#### PR validation:

Tested with scram b code-checks and scram b code-format. Further tests performed locally showing expected behavior of the code changes--namely, when doAnd is set to true with non-zero values for cut and cutOverE specified, all resulting scouting electrons in the collection obey H < cutOverE*E + cut and the number of these electrons is reasonable.

### CODE REVIEW

**Comment by missirol** [comment]
please test

**Comment by missirol** [comment]
+hlt

> This will be needed for Egamma objects in upcoming changes to the Scouting trigger.

@bennettgberg , what is the ETA of this update to the HLT menu (cc: @silviodonato)? If it is for 2022 data-taking, this PR will need to be backported to `12_5_X` and `12_4_X`.

**Comment by bennettgberg** [comment]
> +hlt
> 
> > This will be needed for Egamma objects in upcoming changes to the Scouting trigger.
> 
> @bennettgberg , what is the ETA of this update to the HLT menu (cc: @silviodonato)? If it is for 2022 data-taking, this PR will need to be backported to `12_5_X` and `12_4_X`.

It should be in full operation for 2023 data taking, but we may want to test at the end of 2022 so I will make the backport PR. Thank you!

**Comment by perrotta** [comment]
+1

**Pull request merged**
