### PR TITLE
Add 132X data and MC GTs

### PR DESCRIPTION
**Pull request by francescobrivio**
#### PR description:
This PR adds to the release the 132X GTs for data and for Run 3 MC.
There are a few conditions updated, namely:
- Added the new LHCInfoPerLS and LHCInfoPerLS tags (see this [CMSTalk post](https://cms-talk.web.cern.ch/t/online-prompt-new-lhcinfoper-tags-for-run3/28208)) required by the PPS reco changes in PR #42515
  - Tags for Prompt:
     - `LHCInfoPerLS_endFill_Run3_v1`
     - `LHCInfoPerFill_endFill_Run3_v1`
   - Tags for MC:
     - `LHCInfoPerLS_endFill_Run3_mc_v1`
     - `LHCInfoPerFill_endFill_Run3_mc_v1`
   - Tags for HLT/Express (single-IOV "null" tags for the moment, in view of future developments):
     - `LHCInfoPerLS_hlt_forPPS`
     - `LHCInfoPerFill_hlt_forPPS`
- Updated the ZDC reco geometry tags requested in this [CMSTalk post](https://cms-talk.web.cern.ch/t/update-zdc-geometry-for-run3-data-and-mc/24637)
   - For 2022 MC: `ZDCRECO_Geometry_132DD4hepV2`
   - For 2023 MC: `ZDCRECO_Geometry_132DD4hepV3`
- Updated SiPixelDynIneff tag to `SiPixelDynamicInefficiency_phase1_2023_v2_fix3` requested:
  - for 2022 MC in this [CMStalk post](https://cms-talk.web.cern.ch/t/mc-gt-pixel-bad-components-and-dynamic-inefficiency-payloads-for-the-upcoming-2022-mc-campaign/26670)
  - for 2023 MC in this [CMSTalk post](https://cms-talk.web.cern.ch/t/pixel-conditions-for-2023-mc/24971)
- Updated SiPixel BadComponents tags for 2022 MC as requested in this [CMSTalkPost](https://cms-talk.web.cern.ch/t/mc-gt-pixel-bad-components-and-dynamic-inefficiency-payloads-for-the-upcoming-2022-mc-campaign/26670):
  - pre-EE leak:
    - `SiPixelQuality_phase1_2022_v2b_mc`
    - `SiPixelQuality_forDigitizer_phase1_2022_v2b_mc`
  - post-EE leak:
    - `SiPixelQuality_phase1_2022_v5_mc`
    - `SiPixelQuality_forDigitizer_phase1_2022_v5_mc`

Additionally, the 132X online GTs contain the updates detailed in this [CMSTalk post](https://cms-talk.web.cern.ch/t/queue-132x-data-queues-for-pp-ref-and-hi-data-taking/28067):
- Addition of `HcalPFCuts_v1.0_hlt` tag  for all three HLT/Express/Prompt GTs
- Cleanup of unused MVA tracking tags from Express/Prompt GTs (see https://github.com/cms-AlCaDB/AlCaTools/issues/81)

**GT Differences**
- *run3_hlt*:
  - Diff wrt last GT: https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/130X_dataRun3_HLT_v2/132X_dataRun3_HLT_v2
  - Diff with frozen GT: https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/132X_dataRun3_HLT_v2/132X_dataRun3_HLT_frozen_v1
- *run3_data_express*:
  - Diff wrt last GT: https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/130X_dataRun3_Express_v3/132X_dataRun3_Express_v2
  - Diff with frozen GT: https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/132X_dataRun3_Express_v2/132X_dataRun3_Express_frozen_v1
- *run3_data_prompt*:
  - Diff wrt last GT: https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/130X_dataRun3_Prompt_v4/132X_dataRun3_Prompt_v2
  - Diff with frozen GT: https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/132X_dataRun3_Prompt_v2/132X_dataRun3_Prompt_frozen_v1
- *run3_data*:
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/130X_dataRun3_v2/132X_dataRun3_v1
- *phase1_2022_design*: 
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/131X_mcRun3_2022_design_v3/132X_mcRun3_2022_design_v1
- *phase1_2022_realistic*: 
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/131X_mcRun3_2022_realistic_v4/132X_mcRun3_2022_realistic_v1
- *phase1_2022_realistic_postEE*: 
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/131X_mcRun3_2022_realistic_postEE_v4/132X_mcRun3_2022_realistic_postEE_v1
- *phase1_2022_cosmics*: 
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/131X_mcRun3_2022cosmics_realistic_deco_v4/132X_mcRun3_2022cosmics_realistic_deco_v1
- *phase1_2022_cosmics_design*: 
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/131X_mcRun3_2022cosmics_design_deco_v3/132X_mcRun3_2022cosmics_design_deco_v1
- *phase1_2022_realistic_hi*: 
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/131X_mcRun3_2022_realistic_HI_v8/132X_mcRun3_2022_realistic_HI_v1
- *phase1_2023_design*: 
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/131X_mcRun3_2023_design_v7/132X_mcRun3_2023_design_v1
- *phase1_2023_realistic*: 
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/131X_mcRun3_2023_realistic_v9/132X_mcRun3_2023_realistic_v1
- *phase1_2023_cosmics*: 
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/131X_mcRun3_2023cosmics_realistic_deco_v9/132X_mcRun3_2023cosmics_realistic_deco_v1
- *phase1_2023_cosmics_design*: 
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/131X_mcRun3_2023cosmics_design_deco_v7/132X_mcRun3_2023cosmics_design_deco_v1
- *phase1_2023_realistic_hi*: 
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/131X_mcRun3_2023_realistic_HI_v12/132X_mcRun3_2023_realistic_HI_v1
- *phase1_2024_realistic*: 
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/131X_mcRun3_2024_realistic_v4/132X_mcRun3_2024_realistic_v1

#### PR validation:
Validated running:
```
runTheMatrix.py -l 159.0,160.0,12034.0,12434.0,12834.0,11601.0,138.4,138.5,139.001 -j 8 --ibeos
```
on top of PR #42515. Workflows crash without the updated GTs, while the finish successfully with the new 132X GTs.

#### Backport:
Not a backport, but a 13_2_X backport will be opened soon

### CODE REVIEW

**Comment by francescobrivio** [comment]
@cmsbuild please test

**Comment by francescobrivio** [comment]
I think the many differences are expected from the redigitization using new SiPixelDynEff payload.

**Comment by tvami** [comment]
+alca
 * tests pass
 * PR in line with description
 * lot of diff in plots but that's expected from the GT change

**Comment by perrotta** [comment]
+1

**Comment by slava77** [comment]
> * _phase1_2024_realistic_:
>       https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/131X_mcRun3_2024_realistic_v4/132X_mcRun3_2024_realistic_v1

looking at [postBpix vs 2024 GT](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/132X_mcRun3_2023_realistic_postBPix_v1/132X_mcRun3_2024_realistic_v1), it looks like the 2024 is a bit "old". Is there a plan perhaps to update 2024 to look more like the end of 2023?

**Comment by saumyaphor4252** [comment]
> looking at [postBpix vs 2024 GT](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/132X_mcRun3_2023_realistic_postBPix_v1/132X_mcRun3_2024_realistic_v1), it looks like the 2024 is a bit "old". Is there a plan perhaps to update 2024 to look more like the end of 2023?

@slava77 
The 2024(and the 2023 too) GT keys were originally created back in 2019 for projections for the last two years of Run2. So the origin of this huge diff in the 2024 GT can be traced back to that.

The 2024 GT in principle will mainly become important for next year when we will have a corresponding MC campaign, and the plan is to update this GT then after review and official sign-off for the conditions from all the subsystems, similar to 2023.

Just to mention, there was also a similar discussion for these differences in the 2022-2023 GTs last year in [1].

[1] https://cms-talk.web.cern.ch/t/question-about-mcrun3-2023-2024-conditions/21268

**Comment by mmusich** [comment]
@saumyaphor4252 

> The 2024 GT in principle will mainly become important for next year when we will have a corresponding MC campaign, and the plan is to update this GT then after review and official sign-off for the conditions from all the subsystems, similar to 2023.

there are certain applications in which you want the "2019" pessimistic projection for radiation damage, but you still want to have realistic bad components. I think an update of the 2024 GT key to reflect at least the current status of the detector at P5.

**Pull request merged**
