### PR TITLE
Migrate Geometry/HGCalGeometry to EventSetup consumes

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

This PR migrates all ES and ED modules in Geometry/HGCalGeometry to EventSetup consumes (#26584).

In addition removed some dead code.

#### PR validation:

Limited matrix runs.

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
Errors are from opening files (occurring also in other PRs)

**Comment by smuzaffar** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade

**Comment by fabiocos** [comment]
+1

**Pull request merged**
