### PR TITLE
<update of #19694> using "trackingForDisplacedJetMonitorClientHLT" for Displaced Jet DQM 

### PR DESCRIPTION
**Pull request by jingyuluo**
This PR is an update of #19694 , which merged #19916 , and changed "trackingforDisplacedJetEffFromHitPatternHLT" to "trackingForDisplacedJetMonitorClientHLT" in DQMOffline_SecondStep_cff.py

### CODE REVIEW

**Comment by fwyzard** [comment]
It looks like you changes the name of the sequence only where it is used, but not where it is defined, which clearly will never work.

Please do test the PRs locally before submitting them.

**Comment by jingyuluo** [comment]
Hi @fwyzard , the definition was already there https://github.com/cms-sw/cmssw/pull/19923/files#diff-68ba562036cb5e61cce8f8fd577f1165R211 , sorry I just forgot to use it earlier...

**Comment by fwyzard** [comment]
I see.

OK, I will cherry-pick your commit directly into #19916, so we keep one less PR around to be merged.

**Comment by jingyuluo** [comment]
Okay, thanks!

**Pull request closed without merging**
