### PR TITLE
Fixing track HT for phase2

### PR DESCRIPTION
**Pull request by gkaratha**
Hello,

During the review we saw a bug in the HT calculation for the phase 2 l1t  gtt. We fixed it in the l1t offline and now I am propagating it to the central. Is just a flag to take displaced tracks when we want the displaced HT

Best,
George

### CODE REVIEW

**Comment by epalencia** [comment]
Please test

**Comment by gkaratha** [comment]
As far as I can tell the test failed because the file could not be retreived:
Exception Message:
Failed to open the file 'root://xrootd-cms.infn.it//store/data/Run2024F/TestEnablesEcalHcal/RAW/Express-v1/000/383/173/00000/1088fbe0-c256-4752-992c-0e535b804bef.root'
   Additional Info:

Can we try with another one?

**Comment by smuzaffar** [comment]
ignore tests-rejected with external-failure

missing file is now available in ibeos ( see https://github.com/cms-sw/cmssw/pull/45419#issuecomment-2249606052 ).

**Comment by epalencia** [comment]
Please test

**Comment by srimanob** [comment]
+Upgrade

**Comment by aloeliger** [comment]
+l1

**Pull request merged**
