### PR TITLE
Phase2-hgx331 Transfer HGCal TB related stuff to Geometry/HGCalTestBeam and modify these accordingly

### PR DESCRIPTION
**Pull request by bsunanda**
### PR description:

Transfer HGCal TB related stuff to Geometry/HGCalTestBeam and modify these accordingly

#### PR validation:

To be tested after all transfers are complete

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
+geometry

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by AdrianoDee** [comment]
please test
(`CMSSW_13_0_X_2022-12-01-1100` is out)

**Comment by civanch** [comment]
+1

**Comment by bsunanda** [comment]
@srimanob Please sign this

**Comment by rappoccio** [comment]
+1

**Pull request merged**
