### PR TITLE
Jetid muon fraction fix

### PR DESCRIPTION
**Pull request by knash**
#### PR description:
Upon investigation into the issue reported here:
https://hypernews.cern.ch/HyperNews/CMS/get/physTools/3669.html

It seems that the muon fraction was not properly implemented for all jet types.  This PR fixes the issue.   
This affects the "lepveto" jetid value stored in NanoAOD.

### CODE REVIEW

**Comment by perrotta** [comment]
@knash , you need to apply the code-checks in order to have this PR tested, and the review can start.
Please do so, or just let us know which are the plans for this PR

**Comment by perrotta** [comment]
By the way, is there any intention to backport to any other release?

**Comment by perrotta** [comment]
please test

**Comment by intrepid42** [comment]
Hi, I guess it included #27610 but not cms-sw/cmsdist#5107

**Comment by perrotta** [comment]
@intrepid42 the error seems to point to something else: ```ConstGenParticlePtr``` is not defined in the merged #27610, and for what I can see not even ```ConstGenVertexPtr```.
This has nothing to do with the external cms-sw/cmsdist#5107, which was also merged anyhow,

**Comment by intrepid42** [comment]
I made both PRs, so I know that they are very related: `ConstGenParticlePtr` and  `ConstGenVertexPtr` are both defined in `include/Rivet/Tools/RivetHepMC.hh` of Rivet 3.x, which comes with cms-sw/cmsdist#5107

The PRs were merged today, so they are not included in yesterday's IB `CMSSW_11_0_X_2019-08-12-2300`.
When the test runs on `CMSSW_11_0_X_2019-08-12-2300` (which it does according to the logs) and fetches #27610 (which it does) but does not fetch cms-sw/cmsdist#5107 (which it does not mention at all), it must crash.

**Comment by intrepid42** [comment]
P.S.: Things should be back to normal with next IB CMSSW_11_0_X_2019-08-**13**-2300

Otherwise, I assume it should work with `please test with cms-sw/cmsdist#5107`?

**Comment by perrotta** [comment]
please test with cms-sw/cmsdist#5107

**Comment by perrotta** [comment]
assign xpog
(Since this is going to modify the "lepveto" jetid value stored in nanoAOD)

**Comment by perrotta** [comment]
+1
- The implementation of the fix looks quite logical, and adds the missing muon fractions to the jet id's whenever missing
- Jenkins tests pass and reco output is unafffected
- The only visible difference is in the nanoAOD JetID outputs, which is expected: xpog will evaluate about it

**Comment by perrotta** [comment]
By the way (@fabiocos @smuzaffar): no external is really needed here. It was just added for the tests in order to allow the PR build on top of the latest IB

**Comment by fabiocos** [comment]
@perrotta yes, it was a temporary workaround waiting for next IB, thank you anyway for reminding

**Comment by perrotta** [comment]
@fgolf,@peruzzim please have a look and sign, if you think so.
(I asked for your signature because the fix applies on nanoAOD output and I wanted to be sure that you were aware of it; on the other hand this is a real fix, and I suppose you can approve it rather easily)

**Comment by peruzzim** [comment]
+xpog

As said, this is a real bugfix. Do we have plans for backport?

**Comment by santocch** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Comment by ahinzmann** [comment]
@peruzzim @knash Let's get this fix into the next Run2 MiniAOD starting soon?

**Comment by knash** [comment]
@ahinzmann Right! let me start the backport now -- 106, 102?

**Comment by srimanob** [comment]
@ahinzmann 
What will be your target? 2016, and reminiaod of 2017 and 2018?

@fabiocos

**Comment by ahinzmann** [comment]
Well every NanoAOD production is affected, though the number of analyses is likely very small, and there is a way to work around it matching e.g. ak4 and ak8 jets. So this is a small improvement. Up to you what campaign shall take it into account.

**Comment by peruzzim** [comment]
Do I understand correctly that this only affects variables stored in NanoAOD? If so, I think we should prepare the backports and hold them until we update the rest of NanoAOD code for the next round of production. It is not far away in time, in this way we can update both things at the same time and avoid inconsistencies until then.

**Pull request merged**
