### PR TITLE
Changes for LHCInfo O2O

### PR DESCRIPTION
**Pull request by ggovi**
Modified implementation according to the main user feedback on the prototype:
 CTPPS:  
- implemented sampling to catch changes at lumi-section granularity
- beta* and xing-angle extracted from CTPPS table

ECAL:
- Fixed BEAM bunches queries
- implemented sampling for on-going fills

### CODE REVIEW

**Comment by ggovi** [comment]
please test

**Comment by ggovi** [comment]
@fabiocos 
the PR includes the configurations for the two O2Os, startFill and endFill. The PR changes have been checked out in our development node to deploy both O2Os. They are currently running with the corresponding code. However, we need to wait to restart of the beam for the full validation.

**Comment by ggovi** [comment]
+1

**Comment by arunhep** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
