### PR TITLE
Implement HCAL SiPM nonlinearity in LUTs

### PR DESCRIPTION
**Pull request by christopheralanwest**
This PR propagates the correction for nonlinearity of the SiPMs in the upgraded HE to the linearization LUTs used in the generation of trigger primitives. This PR should only affect MC samples that use an upgraded HE.

The effect of these changes is quite small as the nonlinearity is important only at high energy. The nonlinearity corrections are only relevant below the L1 saturation E_T of 128 GeV. As multiple depths contribute to each trigger tower, this E_T of < 128 GeV is spread among multiple channels. Consequently, none of the tower constituents have an energy for which nonlinearity is important.

At today's L1 trigger primitives meeting, it was demonstrated that [1] this PR:

- Has a negligible effect on trigger rates
- Has a negligible effect on any L1 quantities
- Improves the agreement between the TP E_T and the Method 2 reconstruction

The last point, from slide 6 of [1], most clearly demonstrates the effect of this PR and is reproduced below.

screen shot 2017-11-07 at 12 26 23 pm

[1] https://indico.cern.ch/event/678785/contributions/2780378/attachments/1553502/2442798/07NOV2017_cawest.pdf

### CODE REVIEW

**Comment by arunhep** [comment]
please test

**Comment by arunhep** [comment]
@christopheralanwest do we need a condition update to take into account this change in MC 2018 scenarios?

**Comment by christopheralanwest** [comment]
@arunhep The changes in this PR use the same conditions for SiPM nonlinearity as those used by the reconstruction. No separate conditions update is needed. The plot below shows the TP multiplicity for relval 10824.0, a 2018 MC scenario. There are changes in the region 16 < abs(ieta) < 28, corresponding to HE.

image

**Comment by christopheralanwest** [comment]
@rekovic @arunhep This PR has been idle for about two weeks now. Could you have a look at it?

**Comment by arunhep** [comment]
+1

**Comment by rekovic** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
