### PR TITLE
Using DB:Extended also in cosmic WF for 2017

### PR DESCRIPTION
**Pull request by boudoul**
Greetings 
I realized that the workflows for  2017 are using the geometry option DB:Extended   except the cosmic 2017 workflows.
This PR is fixing this.

### CODE REVIEW

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by boudoul** [comment]
Adding @franzoni ,  @arunhep , @ianna  FYI

**Comment by fabozzi** [comment]
+1

**Comment by mmusich** [comment]
@boudoul @ianna I naively thought that not specifying any `--geometry` option in the cmsDriver sequence is completely equivalent to fetch it via `DB:Extended` (as this is supposedly the default). Am I mistaken? Thanks for clarifications.

**Comment by boudoul** [comment]
Hi @mmusich , my PR is just aiming to be completely in synch with what is used also for phase1 pp Workflows (for reference it was introdcued in pp  by @franzoni here : https://github.com/cms-sw/cmssw/commit/b069469a36cffa92a2ce2bed7a5f33608fbe1f67 ) 

Now looking at the diff with or without using this option 
Adding the option DB:Extended  is adding in the config file this line : 
process.XMLFromDBSource.label = cms.string("Extended")

(not present if we are not giving the option) - Not sure it has any impact though ...

**Comment by mmusich** [comment]
Hi @boudoul,  

> what is used also for phase1 pp Workflows (for reference it was introdcued in pp by @franzoni here : b069469 )

yes the pp wfs went to and fro from XML to DB in the past few months (initial commit from myself https://github.com/cms-sw/cmssw/commit/3f8b5b40e416e3d665c86a1a8ed2505831e6155a, then reverted here https://github.com/cms-sw/cmssw/commit/856a5b08697fec72112a7e9ec5ec2bc6b05b4336 and then back again in the commit you point out).
If possible, I would have avoided to specify the geometry at all but the current structure of `Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py` didn't allow to leave the `Geom` parameter in `upgradeProperties` empty, so I settled to used `DB:Extended` (assuming it was generating the same configuration as if not specified...)

**Comment by ianna** [comment]
@boudoul - I agree with @mmusich. The default without geometry specification should be 'DB:Extended'. The default label is set here:
http://cmslxr.fnal.gov/source/GeometryReaders/XMLIdealGeometryESSource/python/cmsGeometryDB_cff.py#0003

**Comment by boudoul** [comment]
I just x-checked  , so even if adding the option is changing the cfg as I was mentioning earlier, I made a full config dump of the two cfgs  and I confirm what @ianna is saying: there is in the end *no difference* 
Therefore, either we keep this PR , but the reason would be *just* 'cosmetics' to be in synch with the pp Wfs , or we close it - I'm happy with both cases, since we are now convinced that it doesn't make any changes - maybe the final word should come from PdmV/Alca ?

**Comment by franzoni** [comment]
@gaelle thanks for including us
as I mentioned verbally, and reported above DB:Extended is where cmsDriver lands w/o specs

as such, imho, the cmsDriver commands of the relvas are better all cleaned up and not specify explicitly its defaults.
The last word should be from PdmV @fabozzi

One word of caution: the PR form HCAL / @kpedro88 soon expected to integrate the plan1 2017 HCAL is likely going to touch those same lines again... caution with conflicts.

**Comment by kpedro88** [comment]
In general it seems like it would be better to reuse as much as possible of the standard 2017 workflow info in the cosmic 2017 workflows, rather than specifying everything repeatedly.

**Comment by davidlange6** [comment]
-1
I think its better to fix the pp workflow so that everything is consistently using the geometry with no label from the DB.

**Pull request closed without merging**
