### PR TITLE
ME0 pseudo digitizer: Fix the BX mixing window + enable bkg scaling with lumi

### PR DESCRIPTION
**Pull request by dildick**
It appears that in the ME0 pseudo digitizer module the TOF distribution corresponding to BX=0 in the BX window [-5,3] is centered at -7.5 ns. It should be at 18.5 ns (distance from ME0 to beam-spot). This pull request fixes that. The effect is visible when comparing the TOF from hits at PU200. See plots below.

screen shot 2016-10-19 at 16 29 58
screen shot 2016-10-19 at 16 30 08

The second part of this pull request enables to scale up/down the electron/neutron background for desired instantaneous lumi (reference is 5E34, double from config is in units of 1E34).

@nickmccoll @pietverwilligen

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
Hi @dildick - better to take minbunch, maxbunch from the mixing module (or maybe their meaning is different) and to derive the lumi from the pileup as done in other digitizers. 

also, please add a comment about the manipulations done to minbunch/maxbunch - its not obvious why 2*maxbunch*bunchspace/2 would be an relevant number

**Comment by dildick** [comment]
@davidlange6 : the manipulations are (2*minBunch_+1)*bxwidth/2. and (2*maxBunch_+3)*bxwidth/2. this is to ensure that the peaks lie in the correct window. I'm not sure what else to write than the information that's already provided. 

About the "minbunch, maxbunch from the mixing module" -- could you show me where this is done in other digitizers?

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
Hi @dildick 

for lumi, here is one example
https://github.com/cms-sw/cmssw/blob/CMSSW_8_1_X/SimTracker/SiPixelDigitizer/plugins/SiPixelDigitizerAlgorithm.cc#L633

for min/max bunches - its actually confusing that a digitizer would decide what window to digitize in independently of the rest of the mixing framework. I guess it really means that the electronics are only sensitive to some time window so anything outside of that window is just ignored? [probably the names of things are sub-optimal in that case - eg, it would be more clear to think in time units, as the physical unit, rather than bunch crossings]

**Comment by dildick** [comment]
@davidlange6 The minBunch, maxBunch in the GEM/ME0 digitizers define indeed the time window that we are interested in. We could change the names of those parameters if that is required.

**Comment by pietverwilligen** [comment]
@davidlange6 I introduced those minBunch and maxBunch in the past because the default values were wrong. Probably they are set somewhere systemwide for all detectors. Could you point me to this place such that I can change it there, we then can omit those cuts here in the Dgitizer.
Thanks
Piet

**Comment by pietverwilligen** [comment]
@davidlange6 Thanks David, but I meant the values for each of the detectors separately, not the envelope of it for all detectors. The real detectors do not have all the same readout, therefore MC should reflect that somehow. If i look for instance at RPC digis they are all in [-2,+3], both in data and MC. My question is, where is this window defined in MC? This should be defined for each detector individually (not for all detectors together).
Thanks
Piet

**Comment by slava77** [comment]
On 10/26/16 11:03 AM, Piet Verwilligen wrote:
> @davidlange6 <https://github.com/davidlange6> Thanks David, but I meant
> the values for each of the detectors separately, not the envelope of it
> for all detectors. The real detectors do not have all the same readout,
> therefore MC should reflect that somehow. If i look for instance at RPC
> digis they are all in [-2,+3], both in data and MC. My question is,
> where is this window defined in MC? This should be defined for each
> detector individually (not for all detectors together).

For "existing" detectors the range is usually set in the packer/unpacker.
This is the right place to put the DAQ readout configuration to match
what can be read out.

Digitizers are not in general producing signal 1-to-1 per BX given
simHit inputs.
E.g. in DT, a simHit at BX=N can show up in digi outputs in BX=N+16 on
the extreme end.

**Comment by pietverwilligen** [comment]
@slava77 Thanks, indeed for ME0 and GEM we do not have packer/unpacker. So I would propose that we leave the definition of the min/maxBX to be digitized in the configuration file of the digitizer. In due time (with definition of the electronic data format and the development of the packer/unpacker) we will update this.

**Comment by pietverwilligen** [comment]
@slava77 @davidlange6 @mdhildreth 
I have been looking at the SiPixelDigitizer @davidlange6 pointed out to me to access the instantaneous luminosity, but it is not as trivial as i thought. At first I just tried to access the PileupSummaryInfo collection, but this was empty, I would think that is because it is created after the digitizers are run? 

SiPixel and SiStrip Digitizer are inheritting from SimGeneral/MixingModule/interface/DigiAccumulatorMixMod.h to have the function StorePileupInformation working properly:

https://github.com/cms-sw/cmssw/blob/86088d61d757bad0e55addda14859c5ea6108d84/SimTracker/SiPixelDigitizer/plugins/SiPixelDigitizer.h#L63-L68

However letting ME0DigiPreRecoProducer inherit from DigiAccumulatorMixMod would require a total rework of the ME0Digitizer, since now it inherits only from public edm::stream::EDProducer<>and my trials so far to let them inherit from both failed and I would like to have some advice here. Is it really necessary that our Digitizer inherits from the DigiAccumulatorMixMod to access to the PileupMixingContent? Or is there a simpler solution?

https://github.com/cms-sw/cmssw/blob/86088d61d757bad0e55addda14859c5ea6108d84/SimGeneral/MixingModule/plugins/MixingModule.cc#L425-L431

Thanks a lot
greets
PIet

Is there a possibility to access

**Comment by pietverwilligen** [comment]
I would propose to integrate the PR as it is now. Does somebody have objections?
Thanks
Piet

**Comment by mdhildreth** [comment]
Just a comment in response - sorry didn't see the question earlier.  The digitizers that are run as "accumulators" do have access to the luminosity information because they are run inside the Mixing Module.   In a perfect world, we would put the muon digitizers into the Mixing Module too.  We didn't do that earlier because the size of the data products wasn't very large and we were short on manpower.   We will need to do this at some future time.  CSC has already made a pilot attempt, but it wasn't included in a release.

**Comment by dildick** [comment]
@mdhildreth Could you point us to the new CSC digitizer code (which is not included in the release), so we understand the changes we would need to make in the future?

**Comment by dildick** [comment]
@mdhildreth Could you point us to the new CSC digitizer code (which is not included in the release), so we understand the changes we would need to make in the future?

**Comment by calabria** [comment]
apart for the future developments/refinements, can we have this PR merged? it is open since one month already...

**Pull request merged**
