### PR TITLE
Cleanup pixel tracking code (10.2.x)

### PR DESCRIPTION
**Pull request by fwyzard**
Clean up some non-GPU-related pixel tracking code: clean up whitespaces and indenttion, plugin definitions, includes, and file names.

Add a customize function to provide a minimal pixel-tracking only configuration for profiling, removing validation, DQM, and output modules. Can be included in the configuration with
```python
from RecoPixelVertexing.Configuration.customizePixelTracksForProfiling import customizePixelTracksForProfiling
process = customizePixelTracksForProfiling(process)
```

Backport from the Patatrack fork: cms-patatrack#49, cms-patatrack#122, cms-patatrack#134.

### CODE REVIEW

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by slava77** [comment]
@fwyzard 
please make a PR for 10_3_X/master branch.
Thank you.

**Comment by fwyzard** [comment]
Will do tomorrow, needs a rebase.

**Comment by fwyzard** [comment]
backport #24288

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by perrotta** [comment]
+1
- Correct backport of #24288
- Technical adjustments and clean up of pixel tracking code
- Jenkins tests pass, with no effect on outputs

**Comment by fabiocos** [comment]
@perrotta @fwyzard in my understanding almost all the changes in this PR are technical code cleaning, with some readjustment of the needed include files, but no change in the RECO physics output is neither expected nor observed, right?

**Comment by fabiocos** [comment]
+1

**Pull request merged**
