### PR TITLE
Fix obvious bug in particle boosting - backport of PR #25412 in 10.2.X for actual MC generation

### PR DESCRIPTION
**Pull request by covarell**

### CODE REVIEW

**Comment by covarell** [comment]
Backport of #25412

**Comment by alberto-sanchez** [comment]
please test

**Comment by alberto-sanchez** [comment]
+1

**Comment by fabiocos** [comment]
@alberto-sanchez could you please provide a bit more informative title?

**Comment by alberto-sanchez** [comment]
@covarell , can you edit the title, I do not have access to it
"Fix obvious bug in particle boosting - backport of #25412"
or something similar

**Comment by fabiocos** [comment]
+1

**Pull request merged**
