### PR TITLE
[14_1_X] Allow using fake pixels from the digi morphing algorithm as cluster seeds but drop them from final clusters

### PR DESCRIPTION
**Pull request by ferencek**
#### PR description:

Backport of https://github.com/cms-sw/cmssw/pull/46813 to CMSSW_14_1_X

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
type bug-fix

**Comment by jfernan2** [comment]
+1

**Comment by mandrenguyen** [comment]
hold
The master must have changed, since this was merged in 15_0_X.  We should have a 14_2_X backport.

**Comment by mandrenguyen** [comment]
unhold
14_2_X PR made now, thanks!

**Comment by mandrenguyen** [comment]
Backport of https://github.com/cms-sw/cmssw/pull/46813

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
