### PR TITLE
bsunanda:Phase2-gem17 Avoid overlap seen for ME0

### PR DESCRIPTION
**Pull request by bsunanda**
There was an issue of ME not fully contained in its mother MUON. Affects only some shielding material definition (~4mm polyethylene)

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@ianna Could you approve this?

**Comment by ianna** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
