### PR TITLE
Phase2-hgx352C Fix the unit test in Configuration/Geometry

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Fix the unit test in Configuration/Geometry

#### PR validation:

Tested that the unit test passes

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
type Bug fix

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
type BugFix

**Comment by bsunanda** [comment]
+geometry

**Comment by bsunanda** [comment]
@rappoccio, @antoniovilela Please integrate this

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
