### PR TITLE
Phase2-hgx359U Modify the testing code in Validation/Geometry and SimG4CMS/Calo in view of changes made in the Configuration/Geometry area for Phase2 scenarios

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Modify the testing code in Validation/Geometry and SimG4CMS/Calo in view of changes made in the Configuration/Geometry area for Phase2 scenarios

#### PR validation:

Tested the scripts

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

regression problem - MkFit WF

**Comment by bsunanda** [comment]
@antoniovagnerini, @nothingface0, @rvenditti, @syuvivida, @tjavaid Please approve this PR

**Comment by tjavaid** [comment]
+1

- spurious differences seen from unstable WF `12834.7` (open issue #39803 )

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
