### PR TITLE
Fireworks 11_1_X: Fix crash on use of non-default palette (forward port)

### PR DESCRIPTION
**Pull request by alja**
This PR is forward port of #29540.

### CODE REVIEW

**Comment by alja** [comment]
+1

**Comment by silviodonato** [comment]
> -code-checks
> 
> Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-29542/14824
> 
>     * This PR adds an extra 24KB to repository
> 
> 
> Code check has found code style and quality issues which could be resolved by applying following patch(s)
> 
>     * **code-format**:
>       https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-29542/14824/code-format.patch
>       e.g. `curl https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-29542/14824/code-format.patch | patch -p1`
>       You can also run `scram build code-format` to apply code format directly

You need to apply the code-checks fixes in order to proceed with the PR tests

**Comment by silviodonato** [comment]
@alja

**Comment by alja** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
