### PR TITLE
PPS: crash prevention in proton reconstruction

### PR DESCRIPTION
**Pull request by jan-kaspar**
#### PR description:

This is a technical PR aiming at improved stability of PPS proton reconstruction. The code currently in master could possibly pass NaN to TSpline3::Eval which would throw an exception (cf. this report https://github.com/CTPPS/cmssw/issues/38). The proposed fix ensures that NaN are not passed to the Eval method.

#### PR validation:

Below a comparison of several proton-reconstruction quantities and for several periods. Blue: with this PR, red dashed: before this PR. There is no difference.

make_cmp

### CODE REVIEW

**Comment by jan-kaspar** [comment]
I've run the AddOn tests, yielding `47 tests passed, 0 failed`. Could someone trigger tests, please?

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/26530	a100bf8
- code changes are in line with the PR description (changes include reasonable protections against divisions by 0 , sqrt of negative values and alike).
- jenkins tests pass and comparisons with the baseline show no differences, indicating that the issue is not widespread.

**Comment by kpedro88** [comment]
+1

**Pull request merged**
