### PR TITLE
Add track cluster impact angle plot

### PR DESCRIPTION
**Pull request by ssilvado**
Added the track cluster impact angle plot

### CODE REVIEW

**Comment by dmitrijus** [comment]
@ssilvado Please introduce yourself.
@fioriNTU

**Comment by fioriNTU** [comment]
@dmitrijus I asked Sheila to introduce herself, she is a brand new developer of TkDQM, both Online and Offline

**Comment by ssilvado** [comment]
@dmitrijus I had introduced myself to the DQM core team. I am Sheila Amaral post-doc at Purdue University Northwest and I am starting to work as a developer for Tracker DQM (Online and Offline).

As Francesco asked me, I am working on the implementation of the Impact angle on DQM. So, I have it done on my GitHub area, and my username is @ssilvado.

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
hi @ssilvado - this adds about 100k histogram bins. Is that what you expect?

**Comment by davidlange6** [comment]
plus it adds
%MSG-e SiPixelPhase1TrackClusters:   SiPixelPhase1TrackClusters:hltSiPixelPhase1TrackClustersAnalyzer  03-Nov-2017 09:15:50 CET Run: 1 Event
: 7
incompatible configuration 25!=26
%MSG

which is a problem that hopefully I won't have to point out to the pixel group a third time in the future...

**Comment by fioriNTU** [comment]
@davidlange6 (and @ssilvado ) this PR should add:
10 * 4(layers) + 10*6(disks)= 100 bins

plus 500*4 + 500*6 = 5000 bins in Offline
(in Online this number will be 50.000 since we have trends for single lumi and not each 10 lumis)
now the last bins are from A TProfile, I don't know if they are counted differently. If you find something more than in the above there is something unexpected going on.

For the %MSG-e SiPixelPhase1TrackClusters: SiPixelPhase1TrackClusters:hltSiPixelPhase1TrackClustersAnalyzer 03-Nov-2017 09:15:50 CET Run: 1 Event
: 7
incompatible configuration 25!=26
%MSG

the Pixel group is not responsible, the easiest solution would be to create an ad-hoc (simple) Phase1 plugin to monitor Pixel clusters at HLT, @mtosi can we go in this direction? Otherwise each time we add a plot in the track cluster package we have to propagate the change also to the hlt package, which makes no much sense. What is to be done is to simply copy and paste one of the last implementation of the TrackCluster plugin in a TrackClusterHLT plugin, which at this point can be edited independently without creating this annoying bug.

**Comment by fioriNTU** [comment]
@ssilvado @davidlange6 , looking better there is something to change:

here:
https://github.com/cms-sw/cmssw/pull/21023/files#diff-07f1540db61f6b3425442b10e7610b3dR202

and few lines below:
https://github.com/cms-sw/cmssw/pull/21023/files#diff-07f1540db61f6b3425442b10e7610b3dR207

Sheila have to add "IsOffline" in the specifications (Specification(IsOffline).groupBy(...) ), sorry I didn't catch it before. Whitout this switch, in the ONLINE DQM the trend plots will be produced twice, in the per single lumisection version and in the per 10 lumisection one. So this is to be fixed, however it should not change the number of bins in Offline.

**Comment by mtosi** [comment]
as said many times, I do not agree
in principle, the offline and online monitoring should be really in synch

**Comment by davidlange6** [comment]
so it seems one should understand why the DQM tool suggests there is a substantial increase (200kB) in bins (and how pixel offline dqm should work with pixel hlt dqm) before this PR gets integrated.

**Comment by mtosi** [comment]
for the pixel DQM @HLT (as for the other 2 updates) 
one should update https://github.com/ssilvado/cmssw/blob/fa7e4e646680e1e5e33c430662dee3db740dc17d/DQMOffline/Trigger/python/SiPixel_OfflineMonitoring_TrackCluster_cff.py

**Comment by fioriNTU** [comment]
@mtosi I still do not understand why you are so contrary to this solution. You have not to write new code, just to copy a minimal vesion of the existing Phase1TrackCluster plugin and make it completely independent by what is used Offline. I will not ask my contributors to add a line in your code each time we add an histogram that most of the times is not relevant for the hlt monitoring. Let's make the plugins independent, so everybody modify its hown configuration at will. It is easy, may take few hours of work, included the testing.

**Comment by davidlange6** [comment]
it would be much easier just to implement something robust - instead of changing the same thing in 3 spots (by two people), it gets changed in one.

**Comment by mtosi** [comment]
on top of my head, that was the plan @fioriNTU @davidlange6 @VinInn

**Comment by VinInn** [comment]
can we understand what are we expected to learn from monitoring this angle?
Is there any study that shows its usefulness (or even just its is meaningful)?
Can we at least see examples of the DQM plots proposed (in data/MC)?

**Comment by ssilvado** [comment]
@fioriNTU I will add Specification(IsOffline).groupBy(...)
@VinInn I am preparing plots from era C, D and E and MC

**Comment by fioriNTU** [comment]
@VinInn even if in the latest fill this trend is reverted, we used to see a decrease of cluster charge (on track) in Pixel layers during the run, the trend is there also in the ADC values, so for sure a component comes somehow from the electronic, however we would like also to monitor if there is any change on the average track impact angle, for wich we correct the charge value ... it is possible that we do not learn anything, but I believe is a quantity that should be monitored for DPG purposes. Said that, if this two plots make the Phase 1 DQM unusable for the excessive number of bins, I surrend.

**Comment by fioriNTU** [comment]
@davidlange6 @VinInn @mtosi how do we proceed here? I can ask my technical student to make the Pixel DQM @ HLT completely independent by what used in Tracker DPG monitoring. Of course the code will stay as "property" of the Trigger group, other (more direct) solution would be to switch off the monitoring at HLT (who is looking to those plots?)

**Comment by davidlange6** [comment]
I think doing these three things will make for a robust solution

1) remove unused or duplicated monitoring

2) replace copied configs with an import statement to share code if they need to remain in sync

3) Fix the fundamentally wrong design: separate the [make the c++ list  (link 1) the set of possible monitored quantities and the python list (example is link 2) the set of selected monitored quantities for the individual module

link 1 https://github.com/ssilvado/cmssw/blob/d9fb686e4ffdce72512a70ec72b67cc6a6d5c1e7/DQM/SiPixelPhase1TrackClusters/src/SiPixelPhase1TrackClusters.cc#L33

link 2 
https://github.com/ssilvado/cmssw/blob/d9fb686e4ffdce72512a70ec72b67cc6a6d5c1e7/DQM/SiPixelPhase1TrackClusters/python/SiPixelPhase1TrackClusters_cfi.py#L389

**Comment by mtosi** [comment]
the tracker-TSG contact checks those plots ~daily !

as said/written many times
I'mnot in favour of having dedicated code, it does not make any sense at all

**Comment by fioriNTU** [comment]
@davidlange6 these are my thoughts about your points:

1) This is more a matter of optimization, and we are working on it (with lower priority), however if HLT uses our plugin it is impossible to remove the many plots instantiated in the c++ code and not used in HLT monitoring ... we have to go to a separate plugin, let me say again that this is a super easy implementation

2) I think anything is to stay in sync if we decide to go for a separate plugin (the risk that bugs are propagated to the HLT plugin are close to zero)

3) This is in the TkDQM plans, @VinInn changed the structure of the code to add few plots which could have been added in a more natural way. With this PR https://github.com/cms-sw/cmssw/pull/21048 we are able to add inner and outer ladders histograms without adding a single line in c++ and maintaning the basic structure of Phase 1 DQM

@mtosi, again I do not understand why you are against this? Having the code like it is, is a problem, for both of us, so what better solution you propose?

**Comment by davidlange6** [comment]
> On Nov 7, 2017, at 10:45 AM, fioriNTU <notifications@github.com> wrote:
> 
> @davidlange6 these are my thoughts about your points:
> 
> 	• This is more a matter of optimization, and we are working on it (with lower priority), however if HLT uses our plugin it is impossible to remove the many plots instantiated in the c++ code and not used in HLT monitoring ... we have to go to a separate plugin, let me say again that this is a super easy implementation
> 

nominally the offline and online parts of the tracker ought to agree on whats important to monitor for their detector (even if the two groups might look at different things as high or low priority..)

 but thats my third point. just because the code _can_ make a plot, doesn't mean that it should be _required_ to make that plot for all modules instances (but that is basically the current design)

> 	• I think anything is to stay in sync if we decide to go for a separate plugin (the risk that bugs are propagated to the HLT plugin are close to zero)
> 

I disagree.

> 	• This is in the TkDQM plans, @VinInn changed the structure of the code to add few plots which could have been added in a more natural way. With this PR #21048 we are able to add inner and outer ladders histograms without adding a single line in c++ and maintaning the basic structure of Phase 1 DQM
> 

its nothing to do with changing or not changing c++... its having to change c++ and python in sync. Break that dependency and your life will be better.

**Comment by davidlange6** [comment]
> On Nov 7, 2017, at 11:04 AM, fioriNTU <notifications@github.com> wrote:
> 
> @davidlange6
> 
> " but thats my third point. just because the code can make a plot, doesn't mean that it should be required to make that plot for all modules instances (but that is basically the current design)"
> 
> this is not true, with a "enabled=False" in the cfg histograms are not booked. I think the design of the code is "smart" compared to what we use in Strip and/or Tracking DQM, it reduces a lot the code needed to monitor the different parts of the detector (Layers, Shells, Ladders, Blades, Modules, FEDs, ROCs ... etc). For sure we have to pay a prize for it, and having the c++ and python dependent (only on the order of PSets) is a fairly low price to pay in my opinion. The code is still clean and super readable (even if many, many newcomers have edited it), I would prefer to keep as it is.
> '

regardless, having a set of things in c++ and and set of things in python that _must_be the same is a big design problem. I doubt its a complicated change

**Comment by fioriNTU** [comment]
@davidlange6 just a small clarification, then maybe we should meet (informally) to close this thread.
You are perfectly right about this:
"and set of things in python that _must_be the same is a big design problem"
but the original design was slightly better, please have a look to another random Phase 1 plugin, let's take the Clusters as an example, in the .h we have an enum with all the quantities the plugin is supposed to monitor https://github.com/cms-sw/cmssw/blob/master/DQM/SiPixelPhase1Clusters/interface/SiPixelPhase1Clusters.h#L16

then the python has only to respect the order (not really to contain the same strings), so in the cfi we have at first the PSet for charge, then size ... etc. This is what usually we pay.

Then let me point out that this kind of issue happens ONLY if we add a new quantity to monitor (if we want to add or remove plots with existing quantities it requires only deleting or adding one line of python), since this has been the first year with this new detector I believe that cases in which we want to add new quantities to the monitoring will be really rare.

Said that, I would be more than happy to discuss with you how to improve the code if you already have ideas.

**Comment by davidlange6** [comment]
hi @fioriNTU -my suggestion is to expand on this

https://github.com/cms-sw/cmssw/commit/eb3733375dc97f1be49d85c3846b8c738b0915a3

[not so well tested, but in theory one just has to fill more if-else statements in the constructor to cover all of the possible cases]

this will break any strong ordering requirement between c++ and python as well as any requirement that all possible psets are needed in each module instance. The cost is a set of string->int lookups in the constructor and ifs to check against the validity of each histogram (which likely can be done better)

**Comment by fioriNTU** [comment]
@davidlange6 thanks for the feedback, however I would like to think about it more. In this way you remove the order dependency but, as you point out, we have to add a lot more if statements, and we have to change the each plugin ... who knows how many bugs we can introduce in this. I am not 100% sure if this will make our life better. I plan to work on this after the run is over, will be back to you in few weeks.

**Comment by davidlange6** [comment]
> On Nov 8, 2017, at 3:58 PM, fioriNTU <notifications@github.com> wrote:
> 
> @davidlange6 thanks for the feedback, however I would like to think about it more. In this way you remove the order dependency but, as you point out, we have to add a lot more if statements, and we have to change the each plugin ... who knows how many bugs we can introduce in this. I am not 100% sure if this will make our life better. I plan to work on this after the run is over, will be back to you in few weeks.

indeed, this functionality could all be moved into one spot if things were hidden a bit more in the base class. Given the number of consumers that is probably a good idea.

**Comment by davidlange6** [comment]
Your PR is unmergeable. Please have a look and possibly rebase it.

**Comment by fabiocos** [comment]
@ssilvado what should we do with this PR, that in any case should be as a minimum be rebased?

**Comment by ssilvado** [comment]
@fabiocos I believe that this PR should be in standby, am I right @fioriNTU ?

**Comment by boudoul** [comment]
Hi @ssilvado , just this PR for the moment to remove it from the github list - We should think and discuss  all those issues calmy (maybe first remember them ) in a tkDQM meeting - Thanks

**Comment by fioriNTU** [comment]
@ssilvado please close this PR, at this point for sure is not merge-able anymore. We will cook a new one, actually these plots have been mentioned in one of the last DPG meetings, so it is worth to add them.

**Pull request closed without merging**
