### PR TITLE
Move relval2023 to point to HLT frozen menu 2023v12

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
#### PR description:

Move relval2023 to point to HLT frozen menu 2023v12

#### PR validation:

TSG tests

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Not a backport but 13_3 specific!

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by mmusich** [comment]
> DQMHistoTests: [Total failures: 13586](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_13_3_X_2023-11-25-1100+d3cf1e/59943/validateJR.html)

just pointing out for the record that since this PR has effectively downgraded the menu from the current state of the art to the last version used online in 2023 (intentionally!), for example it removes the tracking double recovery iteration and hence all the plots introduced in https://github.com/cms-sw/cmssw/pull/42266 are now empty (see e.g https://tinyurl.com/ywyh8f8g).

**Comment by rappoccio** [comment]
+1

**Pull request merged**
