### PR TITLE
Tell RNTuple not to split some classes

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

RNTuple is unable to do its normal split of a class if that class contains certain C++ constructs. This change marks those classes stored in production workflows that cannot be split.

#### PR validation:

Code compiles. Test with prototype RNTuple code successfully wrote MiniAOD, AOD and RECO formats.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by hqucms** [comment]
+1

**Comment by makortel** [comment]
+core

**Comment by srimanob** [comment]
+Upgrade

**Comment by Dr15Jones** [comment]
@cms-sw/dqm-l2 @cms-sw/generators-l2 please sign. This change has no impact on our present code and is only needed for work on ROOT's RNTuple.

**Comment by lviliani** [comment]
+1

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
