### PR TITLE
Added edtoken to EcalDumpRaw

### PR DESCRIPTION
**Pull request by argiro**
Conform EcalDumpRaw to getByToken

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
@argiro:  `EcalDumpRaw.h` still has inheritance from EDAnalyzer:
 `class EcalDumpRaw : public edm::EDAnalyzer {`
Doesn't the base class need to be changed to a thread-safe version like `edm::stream::EDAnalyzer<>`?

**Comment by argiro** [comment]
it's sort of a technical tool used by experts, does not go into production sequences,  but I can change the inheritance

**Comment by cvuosalo** [comment]
@argiro: Since you're cleaning up the code, you might as well fix the EDAnalyzer inheritance so the issue is no longer flagged by the static analyzer.

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
+1

For #13876 fd3780f85cf1dd5edc5c8a0c3692f43cff1589e8

Revising EcalDumpRaw to use getByToken. There should be no change in monitored quantities.

The code changes are satisfactory, and Jenkins tests against baseline CMSSW_8_1_X_2016-04-04-2300 show no significant differences, as expected.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
