### PR TITLE
Reenable relval wfs 310, 311 and 312

### PR DESCRIPTION
**Pull request by mandrenguyen**
#### PR description:

Reenable Run 3 heavy-ion relval workflows that were waiting for a pileup dataset to produced.
They were disabled in #29218
The input is set to GEN-SIM produced in 11_1_0_pre5 

#### PR validation:

Test on wfs 310,311,312

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by smuzaffar** [comment]
test parameters
  - workflows = 310,311,312

**Comment by kpedro88** [comment]
please test

**Comment by chayanit** [comment]
please test

**Comment by kpedro88** [comment]
+upgrade

**Comment by chayanit** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
