### PR TITLE
Forward-port Premixing Validation modifications to 76X

### PR DESCRIPTION
**Pull request by mdhildreth**
simple forward port

### CODE REVIEW

**Comment by mdhildreth** [comment]
git cms-merge-topic and checkdeps show no conflicts.  How do I find them?

**Comment by civanch** [comment]
may be rebase even if files are the same?

**Comment by mdhildreth** [comment]
Rebased.  Seems to have fixed whatever was wrong...

**Comment by mdhildreth** [comment]
+1

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1

**Pull request merged**
