### PR TITLE
Update anti-e tau discriminant (94X)

### PR DESCRIPTION
**Pull request by mbluj**
This PR is to update an MVA anti-e tau discriminant as preparation to introduction of discriminants with a new training with current data, it is backport of #24800 to 94X.

### CODE REVIEW

**Comment by perrotta** [comment]
backport of #24800

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
+1
- This backport includes some code cleaning and a fix to a configuration file never used in the current productions, and therefore it does not violate the "no change" policy for the backports
- Jenkins tests pass

**Comment by fabiocos** [comment]
+1

**Pull request merged**
