### PR TITLE
Conddb v2 remove v1 deps 2

### PR DESCRIPTION
**Pull request by ggovi**
- Clean up from conddb v1: removed dependencies from packages:
  CondCore/DBCommon 
  CondCore/ORA
  CondCore/MetaDataService
  CondCore/TagCollection
- Added TagLog functionality

### CODE REVIEW

**Comment by ggovi** [comment]
please test

**Comment by mmusich** [comment]
please test

**Comment by diguida** [comment]
@ggovi https://github.com/diguida/cmssw/commit/38eb9d14215c6ea632ddc3040e94d179cff8222b is the fix

**Comment by ggovi** [comment]
please test

**Comment by ggovi** [comment]
@mmusich @franzoni @mulhearn 
any objection? I'd like to have this signed for the ORP...

**Comment by davidlange6** [comment]
@ggovi - you should also sign it...

**Comment by ggovi** [comment]
+1

**Comment by mmusich** [comment]
+1

**Comment by mulhearn** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Comment by davidlange6** [comment]
@ggovi - looks like one was missed (or came in just recently) - i will revert this for now, until a fix is available
https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc6_amd64_gcc493/CMSSW_8_0_X_2016-01-19-2300/Geometry/HcalCommonData

**Comment by diguida** [comment]
@davidlange6 IIUC it looks like the `BuildFile` of `Geometry/HcalCommonData` is missing a reference to `CoralBase`. This was included indirectly from some of the DB core packages now removed (most likely `CondCore/DBCommon`.
I assume the fix is to add

````
<use   name="CoralBase"/>
````

for the failing tests.

**Comment by diguida** [comment]
@davidlange6 giving a quick look with @ggovi the header file `CoralBase/Exception.h` is a spurious included, as the classes defined therein are not used at all in the test.

**Comment by diguida** [comment]
@davidlange6 the fix is in https://github.com/cms-sw/diguida/commit/a17e26f7a956bf21848a1bb0ab8b9c40d4a214a3.
Now, I have prepared two branches:
* `conddbV2-remove-V1-deps-2`: https://github.com/cms-sw/cmssw/compare/CMSSW_8_0_X...diguida:conddbV2-remove-V1-deps-2 done by cherry-picking https://github.com/cms-sw/diguida/commit/a17e26f7a956bf21848a1bb0ab8b9c40d4a214a3 and rebasing this one on top of `CMSSW_8_0_X_2016-01-19-1100`:

````
$ git checkout -b conddbV2-remove-V1-deps-2 ggovi/conddbV2-remove-V1-deps-2
$ git cherry-pick a17e26f
$ git rebase -i CMSSW_8_0_X_2016-01-19-1100
````

* `conddbV2-remove-V1-deps-3`: https://github.com/cms-sw/cmssw/compare/CMSSW_8_0_X...diguida:conddbV2-remove-V1-deps-3 done by reverting https://github.com/cms-sw/cmssw/commit/a88c79ce2f25d5f105f56f4ba7bf67d6b48d35ff merged in #13005 and then cherry-picking https://github.com/cms-sw/diguida/commit/a17e26f7a956bf21848a1bb0ab8b9c40d4a214a3

````
$ git checkout -b conddbV2-remove-V1-deps-3 official-cmssw/CMSSW_8_0_X
$ git revert -m 1 a88c79c
$ git cherry-pick a17e26f
````

Please let us know which one you would like to become a PR

**Comment by diguida** [comment]
As a further check, both branches `conddbV2-remove-V1-deps-2` and `conddbV2-remove-V1-deps-3` have the same modifications, as seen by `git`:

````
$ git diff --stat official-cmssw/CMSSW_8_0_X...conddbV2-remove-V1-deps-2 | tail -1
 361 files changed, 5141 insertions(+), 19711 deletions(-)
$ git diff --stat official-cmssw/CMSSW_8_0_X...conddbV2-remove-V1-deps-3 | tail -1
 361 files changed, 5141 insertions(+), 19711 deletions(-)
````

**Pull request merged**
