### PR TITLE
Reduce boost pointers

### PR DESCRIPTION
**Pull request by camolezi**
#### PR description:
Replacing some cases where boost pointers are not needed.

#### PR validation:
Passed on runTheMatrix test.

@vgvassilev @davidlange6

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by silviodonato** [comment]
Shall we merge this? alca:  @pohsun @tlampen @tocheng @christopheralanwest

**Comment by christopheralanwest** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
