### PR TITLE
Run3-gex176X Backport #43978 of the modification of the sub-scenario of the RPC section for the 2024 scenario

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Backport #43978 of the modification of the sub-scenario of the RPC section for the 2024 scenario

#### PR validation:

Use the runTheMatrix test workflows

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport of #43978

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by jordan-martins** [comment]
+1

**Comment by bsunanda** [comment]
@antoniovilela, @rappoccio Please merge this. I need to use the IB to backport the next version (scenario definition)

**Comment by rappoccio** [comment]
+1

**Comment by mileva** [comment]
ping RPC and muon people
@jhgoh @mrcthiel  @slomeo @bapavlov @archiesharma @cms-sw/muon-dpg-l2 
If I correctly understood from the email of @bsunanda there is a problem with the RPC Numbering schema in this PR (#44006 as well). 
The relevant people were notified just a few hours ago.
So, I would propose to have this issue resolved before merging these changes.
Roumyana

**Pull request merged**
