### PR TITLE
Print function migration for PhysicsTools_NanoAOD

### PR DESCRIPTION
**Pull request by davidlange6**
Using futurize -n -w --no-diffs -j 4 -f libfuturize.fixes.fix_print_with_import

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by kpedro88** [comment]
please test

**Comment by kpedro88** [comment]
+1

**Comment by kpedro88** [comment]
merge

**Comment by gpetruc** [comment]
Are there any objections if I backport this to10_2_X (as part of another PR), in order to keep the 10_2_X and 10_3_X branches aligned for PhysicsTools/NanoAOD?

**Pull request merged**
