### PR TITLE
Include reduced material DD4HEP geometry scenarios in Run-3 MC GTs

### LINKED ISSUE #47: Add reduced material scenarios to Run-3 MC GTs
See request in
https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/4510.html

### PR DESCRIPTION
**Pull request by tvami**
#### PR description:

Include reduced material DD4hep geometry scenarios in Run-3 MC GTs as requested in [1]

I've created new GTs

* 121X_mcRun3_2021_design_v16
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mcRun3_2021_design_v15/121X_mcRun3_2021_design_v16
* 121X_mcRun3_2021_realistic_v18
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mcRun3_2021_realistic_v17/121X_mcRun3_2021_realistic_v18
* 121X_mcRun3_2021cosmics_realistic_deco_v18
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mcRun3_2021cosmics_realistic_deco_v17/121X_mcRun3_2021cosmics_realistic_deco_v18
* 121X_mcRun3_2021_realistic_HI_v18
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mcRun3_2021_realistic_HI_v17/121X_mcRun3_2021_realistic_HI_v18
* 121X_mcRun3_2023_realistic_v17
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mcRun3_2023_realistic_v16/121X_mcRun3_2023_realistic_v17
* 121X_mcRun3_2024_realistic_v17
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mcRun3_2024_realistic_v16/121X_mcRun3_2024_realistic_v17

The diffs are only in the requested tags of 
```
XMLFILE_Geometry_121DD4hepV2_Extended2021ZeroMaterial_mc, label: ZeroMaterial

XMLFILE_Geometry_121DD4hepV2_Extended2021FlatMinus05Percent_mc, label: FlatMinus05Percent

XMLFILE_Geometry_121DD4hepV2_Extended2021FlatMinus10Percent_mc, label: FlatMinus10Percent

XMLFILE_Geometry_121DD4hepV2_Extended2021FlatPlus05Percent_mc, label: FlatPlus05Percent

XMLFILE_Geometry_121DD4hepV2_Extended2021FlatPlus10Percent_mc, label: FlatPlus10Percent
```

[1] https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/4510.html

#### PR validation:

The tags are not consumed by default but only in special campaigns. 

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

cc @cvuosalo 

resolves https://github.com/cms-AlCaDB/AlCaTools/issues/47

### CODE REVIEW

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by francescobrivio** [comment]
@tvami although for `mcRun3` GTs the DD4HEP geometry is the de fault one, maybe it's worth specifying it also in the PR title/description that you added the dd4hep zero material tags. What do you think?

(The GT diffs look very clean BTW 😄)

**Comment by tvami** [comment]
> @tvami although for `mcRun3` GTs the DD4HEP geometry is the de fault one, maybe it's worth specifying it also in the PR title/description that you added the dd4hep zero material tags. What do you think?

Sure, done!

**Comment by tvami** [comment]
@cmsbuild , please test with #35766

**Comment by tvami** [comment]
+alca
 * test results as expected
 * @francescobrivio already agreed to the GT changes

**Comment by perrotta** [comment]
please test with #35941,#35921
(in order to have some meaningful test and comparison)

**Comment by perrotta** [comment]
+1
- The DD4hep Run 3 12_1 reduced material geometry scenarios are only used for calibrations and special studies: therefore, it is normal that there are no differences in test outputs while just adding them to the GT

**Pull request merged**
