### PR TITLE
Update nano modifiers 

### PR DESCRIPTION
**Pull request by mariadalfonso**
preparation for nanoV9 post reminiUL

* add new modifier nanoAOD_106Xv2
* add wf for data 136.8523
* cleanup the repetition in using modifier
* those nanoAOD_106Xv1 and nanoAOD_106Xv2 added in the runTheMatrix to run by default in the "please test"

TO DO:
* add MC wf (pending this https://github.com/cms-sw/cmssw/pull/32463#issuecomment-748108721)

### CODE REVIEW

**Comment by mariadalfonso** [comment]
please test workflow 136.8523

**Comment by mariadalfonso** [comment]
please test workflow 136.8523

**Comment by chayanit** [comment]
+1

**Comment by mariadalfonso** [comment]
please test

**Comment by mariadalfonso** [comment]
+xpog

**Comment by chayanit** [comment]
+1

**Comment by santocch** [comment]
+1

**Comment by santocch** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade

**Comment by silviodonato** [comment]
@mariadalfonso what do you think to keep only `136.8523` in `please test`? How long should we support the NanoAOD based on 94X and 106Xv1?

**Comment by mariadalfonso** [comment]
> @mariadalfonso what do you think to keep only `136.8523` in `please test`? How long should we support the NanoAOD based on 94X and 106Xv1?

@silviodonato 
we can indeed remove the 94X and keep the two UL production.
New 136.8523 that will have the input the new reMiniAOD;  the 106Xv1 (wf 1325.81) is the ongoing campaign, will continues as long as the Summer20 and Summer19 continue.
Is this ok ?

**Comment by silviodonato** [comment]
> > @mariadalfonso what do you think to keep only `136.8523` in `please test`? How long should we support the NanoAOD based on 94X and 106Xv1?
> 
> @silviodonato
> we can indeed remove the 94X and keep the two UL production.
> New 136.8523 that will have the input the new reMiniAOD; the 106Xv1 (wf 1325.81) is the ongoing campaign, will continues as long as the Summer20 and Summer19 continue.
> Is this ok ?

Ok, I agree we should keep also `1325.81` as 106Xv1 is an ongoing campaign

**Comment by mariadalfonso** [comment]
please test

**Comment by mariadalfonso** [comment]
+xpog

**Comment by mariadalfonso** [comment]
For the record:

I wanted to add the wf for MC but
runTheMatrix make this query
`dasgoclient --limit 0 --query 'file dataset=/RelValTTbar_13/CMSSW_10_6_20-106X_mc2017_realistic_v9-v1/MINIAODSIM site=T2_CH_CERN'`

while only this that explicitly request rucio works
`dasgoclient --limit 0 --query 'file dataset=/RelValTTbar_13/CMSSW_10_6_20-106X_mc2017_realistic_v9-v1/MINIAODSIM site=T2_CH_CERN system=rucio'`

**Comment by kpedro88** [comment]
+upgrade

**Comment by santocch** [comment]
+1

**Comment by chayanit** [comment]
+1

**Comment by qliphy** [comment]
+operations

**Comment by qliphy** [comment]
+1

**Pull request merged**
