### PR TITLE
Moving GBRForestWriter to CommonTools/Utils: 74X

### PR DESCRIPTION
**Pull request by ferencek**
Backport of #10575

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
+1

For #10755 fd951579f0d05c3b4c15e31c40edee300b4c5fe9

Moving GBRForestWriter, a fairly general utility, to a more common and more appropriate location. There should be no change in run-time behavior. The 76X version of this PR, #10575, has already been merged, and the 75X version, #10754, has already been approved by Reco.

The code changes are satisfactory, and Jenkins [tests](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-10755/7297/summary.html) against baseline CMSSW_7_4_X_2015-08-14-1100 show no significant differences, as expected.

**Comment by monttj** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
