### PR TITLE
Revert "Electron MVA V2 and general code changes"

### PR DESCRIPTION
**Pull request by fabiocos**
Reverts cms-sw/cmssw#23473

After its merge several crashes that appear related to this code are observed, namely workflows
10001.0 10003.0 1325.7 1325.9 1329.1 134.707 136.7722 136.844

### CODE REVIEW

**Comment by fabiocos** [comment]
please test workflow 134.707,136.7722,1325.9 with cms-sw/cmsdist#4157

**Comment by fabiocos** [comment]
please test workflow 134.707,136.7722,1325.9 with cms-sw/cmsdist#4157

**Comment by guitargeek** [comment]
Ouch! That's a nightmare. @lsoffi @michelif @Sam-Harper.

I guess the only good thing is it doesn't seem to affect the photons, which almost got the same rationalizing treatment than the electrons in my PR. All the failed workflows are related to electrons.

We should discuss how we proceed... I guess one option is to continue debugging after a new IB with the infamous https://github.com/cms-sw/cmssw/pull/23473 reverted is available, but I don't know what would be best to hit 10_2_X if this is even still possible at this point.

**Comment by fabiocos** [comment]
@guitargeek @Sam-Harper of course, reverting this PR implies reverting also the corresponding external, right? Otherwise I see it does not even run

**Comment by guitargeek** [comment]
Yes...

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Comment by jfernan2** [comment]
+1

**Pull request merged**
