### PR TITLE
TTStub fixes for 11_0

### PR DESCRIPTION
**Pull request by mdhildreth**
#### PR description:

TTStub cleanup for 11_0 HLT Sample production with correct L1 Tracking

#### PR validation:

Produces correct TTStubs

#### if this PR is a backport please specify the original PR:

Backport of 28435

### CODE REVIEW

**Comment by mdhildreth** [comment]
@fabiocos sorry for the delay!  Ready to go...

**Comment by kpedro88** [comment]
@fabiocos already made and merged this backport in #28661

**Comment by fabiocos** [comment]
@mdhildreth in order to speed up things I already made the backport

**Comment by kpedro88** [comment]
please close

**Pull request closed without merging**
