### PR TITLE
Nano gen dqm

### PR DESCRIPTION
**Pull request by kdlong**
#### PR description:

This PR adds runTheMatrix support and DQM for the NanoGen workflow, addressing the first item of #31393. A few changes to the NanoGen configs are also made to fix small issues and to simplify the setup.

Only one validation workflow is added currently, starting with a GEN step. In principle a step with MiniAOD input would also be relevant.

As discussed previously, the inputs should be modified based on if the input event content is MiniAOD-like or GEN-like. In the cmsDriver implementation, this is just decided by seeing if the GEN step is run in the cmsDriver command. If a GEN file is input and only one step is run, it expects Mini. Maybe there is a better way to detect this, but for now I just called the customize command for GEN input explicitly.

#### PR validation:

I checked that ./runTheMatrix.py -l 595 runs and gives sensible output. The DQM workflow also runs, but I didn't actually check that the plots are produced correctly. Is there an easy tool to see all the plots it creates?

### CODE REVIEW

**Comment by mariadalfonso** [comment]
please test workflow 595

**Comment by chayanit** [comment]
Why is the workflow ID 595? just my curiosity as I have never understood the rule of numbering here

**Comment by kdlong** [comment]
@chayanit I didn't see any explanation of the numbers or a clear pattern, so I just picked 595 to be similar to the others around it but different. If there is a better system for this, please let me know...

@mariadalfonso How do I see the DQM plots for this workflow?

**Comment by chayanit** [comment]
@kdlong , I also don't know the pattern or rules for these numbers, they are set before my time but I think they are somehow set in order starting from 501-562 for GEN & extendedGEN. Some numbers are not being used yet i.e.
537-540 not used 
546-550 not used
556-559 not used
Shall we try to fill up with these numbers first? 595 is a bit big jump IMO.

**Comment by qliphy** [comment]
> #### PR description:
> 
> This PR adds runTheMatrix support and DQM for the NanoGen workflow, addressing the first item of #31090. A few changes to the NanoGen configs are also made to fix small issues and to simplify the setup.

@kdlong  I think you meant for #31393 instead of #31390.

**Comment by kdlong** [comment]
Thanks @qliphy, indeed you're right. @chayanit sure, I'm happy with any number you or others want to suggest.

**Comment by jfernan2** [comment]
> Is there an easy tool to see all the plots it creates?

@kdlong you can check the DQM root file against base DQM root file using this tool:
https://github.com/cms-sw/cmssw/blob/7bf830bbb5f57be6673227056342a5adf8c88567/DQMServices/FileIO/scripts/compareDQMOutput.py
which will upload the differences to Development DQM GUI

If you just have the DQM PR output, simply inspect the ROOT file with bare ROOT.
From the WFs tested in Jenkins, there are several running NANOAOD 
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-aa1f5e/9594/runTheMatrix-results/
but I see no new plots in output:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_11_2_X_2020-09-26-1100+aa1f5e/39027/dqm-histo-comparison-summary.html

**Comment by chayanit** [comment]
@kdlong let's update to 546 instead. Thanks!

**Comment by kpedro88** [comment]
@kdlong please update the PR description to refer to #31393

**Comment by kdlong** [comment]
@chayanit @kpedro88 done.

I also added a new workflow (547) that starts from a MadGraph gridpack rather than Pythia gen to have LHE weights. I added plots for the LHE weights and PS weights. @mariadalfonso @gouskos maybe these should be added to the regular Nano dqm as well?

@agrohsje: it would be useful to have a gen workflow that with scale/pdf weights and PS weights corresponding to the latest generator setup to test with this as well.

I also decided to set the default NanoGEN precision to be the same as the RECO default. For production, this should probably be studied together with deciding how to slim the genparticle collection. By default it is currently not slimmed.

**Comment by kdlong** [comment]
> > Is there an easy tool to see all the plots it creates?
> 
> @kdlong you can check the DQM root file against base DQM root file using this tool:
> https://github.com/cms-sw/cmssw/blob/7bf830bbb5f57be6673227056342a5adf8c88567/DQMServices/FileIO/scripts/compareDQMOutput.py
> which will upload the differences to Development DQM GUI
> 
> If you just have the DQM PR output, simply inspect the ROOT file with bare ROOT.
> From the WFs tested in Jenkins, there are several running NANOAOD
> https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-aa1f5e/9594/runTheMatrix-results/
> but I see no new plots in output:
> https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_11_2_X_2020-09-26-1100+aa1f5e/39027/dqm-histo-comparison-summary.html

Thanks @jfernan2. I've just been looking at the root output after running runTheMatrix myself.  Should I expect to see plots output from Jenkins testing this PR anywhere?

**Comment by jfernan2** [comment]
@kdlong  at least wf 1325.7 is running @nanoAODDQM  and wf 595.0 @nanogenDQM but your PR seems to not modify the output according to Jenkins in the last test: 
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_11_2_X_2020-09-26-1100+aa1f5e/39027/dqm-histo-comparison-summary.html

Lets's see with your last commit

**Comment by jfernan2** [comment]
please test

**Comment by mariadalfonso** [comment]
> @chayanit @kpedro88 done.
> 
> I also added a new workflow (547) that starts from a MadGraph gridpack rather than Pythia gen to have LHE weights. I added plots for the LHE weights and PS weights. @mariadalfonso @gouskos maybe these should be added to the regular Nano dqm as well?

yes I agree fully with you

for PS we already added
https://github.com/cms-sw/cmssw/pull/31276/files#diff-7146a00294cb1f815c6b4b9b99641de3

for LHE you can add here 
https://github.com/cms-sw/cmssw/pull/31680

for PDF you can add when you are going to make the PR that update the PDF LHAPDF --> NNPDF3.1 ;)

**Comment by agrohsje** [comment]
We could update the gridpack and the fragment of workflows [512]. Workflow[556] would allow testing powheg. @kdlong Should I provide fragments and then we update with this PR?

**Comment by agrohsje** [comment]
@kdlong what about using this fragment for 
[Hadronizer_TuneCP5_PSweights_13TeV_MLM_5f_max4j_LHE_pythia8_cff.log](https://github.com/cms-sw/cmssw/files/5343575/Hadronizer_TuneCP5_PSweights_13TeV_MLM_5f_max4j_LHE_pythia8_cff.log)
workflow [547] ?  Note that I called it log instead of py to be able to upload.

**Comment by agrohsje** [comment]
workflows[556]=['TTbar_NLO_Pow_13TeV_py8',['TTbar_Pow_LHE_13TeV','Hadronizer_TuneCP5_13TeV_powhegEmissionVeto2p_pythia8','HARVESTGEN2']] 
has already proper PDF and scale weights, but Hadronizer_TuneCP5_13TeV_powhegEmissionVeto2p_pythia8 could be replaced with : 
[Hadronizer_TuneCP5_PSweights_13TeV_powhegEmissionVeto2p_pythia8_cff.log](https://github.com/cms-sw/cmssw/files/5343729/Hadronizer_TuneCP5_PSweights_13TeV_powhegEmissionVeto2p_pythia8_cff.log)
to get psweights.

**Comment by kdlong** [comment]
Thanks @agrohsje. I overwrote the configs with the ones with the PS weights added. If you want them in addition, let me know.

**Comment by mariadalfonso** [comment]
@kdlong 
can you rebase on top of one latest release ?
the one you use is very old : I see that thee PhysicsTools/NanoAOD/python/nanoDQM_cfi.py in master advanced a lot

**Comment by kdlong** [comment]
> @kdlong
> can you rebase on top of one more recent release ?
> the one you use is very old : I see that the PhysicsTools/NanoAOD/python/nanoDQM_cfi.py in master advanced a lot

I at least updated the additions so they don't conflict, namely the PSWeights aren't added twice. When I tried pulling the master version and applying my changes I saw a larger diff in the PR. If there are conflicts I'm not aware of with this, I'll resolve them when they come up.

**Comment by mariadalfonso** [comment]
please test workflow 546,547,548

**Comment by jfernan2** [comment]
@kdlong  only wf 1325.7 gets new plots but it seems that Physics/NanoAODDQM/LHEPart  gets 1k particles though histograms do not get filled, is it expected?
https://tinyurl.com/yy5j5lc9

**Comment by agrohsje** [comment]
@chayanit : Kenneth added the psweights to the fragment. This will not affect the outcome of other workflows, but might lead to an increase in computing time. Should we have a separate fragment, one with and the other without PS weights, so that the behaviour of the others stays the same?

**Comment by chayanit** [comment]
@agrohsje, from my understanding, PSweight doesn't make any physics effect in terms of validation among release right? If so, I don't think we need separate fragment :)

**Comment by kdlong** [comment]
> @kdlong only wf 1325.7 gets new plots but it seems that Physics/NanoAODDQM/LHEPart gets 1k particles though histograms do not get filled, is it expected?
> https://tinyurl.com/yy5j5lc9

@jfernan2 it looks like 1325.7 starts with /RelValTTbar_13/CMSSW_9_4_5_cand1-94X_mc2017_realistic_v14_PU_RelVal_rmaod-v1/MINIAODSIM, which I guess is a Pythia-only workflow. Then it makes sense that LHEPart is empty. In my tests of 548, it is filled correctly.

**Comment by jfernan2** [comment]
+1

**Comment by kdlong** [comment]
By the way, should I backport to 10_6?

**Comment by agrohsje** [comment]
@chayanit indeed, the comparisons shouldn't be affected but it will increase cpu time.

**Comment by mariadalfonso** [comment]
> By the way, should I backport to 10_6?

we keep the 10_6 for the production of the UL nano.

note the previous cms-sw#30306 regarding the nanoGen was not backported.
I would suggest to keep the nanoGen in 11_2 for now and we might do a mega backport what you complete the full rewriting of the weights when we will use for nano-central production.

For the time being we backport to the 10_6 only the bug fixes of LHE/PS/PDF needed before we have the full rewriting.
Those are needed asap :)

**Comment by mariadalfonso** [comment]
+xpog

changes in nanoGen inline with description
centralNano DQM updated

**Comment by chayanit** [comment]
+1

**Comment by agrohsje** [comment]
+1

**Comment by santocch** [comment]
+1

**Comment by silviodonato** [comment]
@kpedro88 ?

**Comment by silviodonato** [comment]
urgent

**Comment by kpedro88** [comment]
+upgrade

**Comment by silviodonato** [comment]
+1

**Pull request merged**
