### PR TITLE
Run4-hgx276 Change CMSUnits/GeantUnits to angle_units

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Change CMSUnits/GeantUnits to angle_units in algorithms for HGCal geometry

#### PR validation:

Tested using a few workflows from standard runTheMatrix.py

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
@cvuosalo , @srimanob, can you , please, review this PR - modifications are straightforward.

**Comment by srimanob** [comment]
+Upgrade

Technical update, no change is expected.

**Comment by cvuosalo** [comment]
Thanks for the clean-up.

**Comment by cvuosalo** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
