### PR TITLE
this fixes clang warning/errors in pull request 7683

### PR DESCRIPTION
**Pull request by gartung**

### CODE REVIEW

**Comment by davidlt** [comment]
I fixed `Utilities/StaticAnalyzers/src/ClassChecker.cpp` yesterday https://github.com/cms-sw/cmssw/commit/fad1e6da5b196117172e1c0a4a3ceb83f2e855f6#diff-c72806330f92ba0af7d2875c7a9e177f

Not sure why GitHub shows it in a diff :/

**Comment by gartung** [comment]
@davidlt Did your change only go into the CLANG_X branch?

**Comment by gartung** [comment]
I rebased to the latest CMSSW_7_4_X so there should not be a merge conflict with 
https://github.com/cms-sw/cmssw/commit/fad1e6da5b196117172e1c0a4a3ceb83f2e855f6#diff-c72806330f92ba0af7d2875c7a9e177f

**Comment by davidlt** [comment]
There is no CLANG_X branch anymore. The standard CMSSW now compiles with Clang, we just name the IB as _CLANG_X.

david

**Comment by gartung** [comment]
@Dr15Jones @davidlt

**Comment by Dr15Jones** [comment]
@ktf @davidlange6 Should we just put this in 7_5?

**Comment by ktf** [comment]
At this point, I would say yes.

**Comment by gartung** [comment]
OK. Moving to CMSSW_7_5_X.

**Pull request closed without merging**
