### PR TITLE
Phase2 HLT pixel modules duplicate removal (13_1_X backport)

### PR DESCRIPTION
**Pull request by lguzzi**
this is a backport of https://github.com/cms-sw/cmssw/pull/42491.

#### PR description:

This PR removes some duplicated pixel modules from the phase2 menu and renames pixel[...] to hltPhase2Pixel[...]. More details in the master PR.
No change is expected. Some automated tests may fails because the pixelTracks and pixelVertices collections have been renamed to hltPhase2PixelTracks and hltPhase2PixelVertices as discussed in https://github.com/cms-sw/cmssw/pull/42491#issuecomment-1669127408. 

#### PR validation:

tested privately running 

```bash
cmsDriver.py Phase2 -s HLT:75e33 --processName=HLTX \
  --conditions auto:phase2_realistic_T21 \
  --geometry Extended2026D95 \
  --era Phase2C17I13M9 \
  --customise SLHCUpgradeSimulations/Configuration/aging.customise_aging_1000 \
  --eventcontent FEVTDEBUGHLT \
  --filein=/store/mc/Phase2Spring23DIGIRECOMiniAOD/TT_TuneCP5_14TeV-powheg-pythia8/GEN-SIM-DIGI-RAW-MINIAOD/PU200_Trk1GeV_131X_mcRun4_realistic_v5-v1/30000/01607282-0427-4687-a122-ef0a41220590.root \
  -n 10 --nThreads 4
```

on 13_1_X. Output: [results](https://lguzzi.web.cern.ch/lguzzi/Tracking/Phase2/duplicates/PR_test/duplicates_test_131X.txt) ([baseline results](https://lguzzi.web.cern.ch/lguzzi/Tracking/Phase2/duplicates/PR_test/duplicates_test_131X_baseline.txt) as run on d7d5f11d2201aad0d3331bb8ef4fa55332a36eeb)

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

This is a backport of https://github.com/cms-sw/cmssw/pull/42491, needed for the integration in the phase2 HLT.

### CODE REVIEW

**Comment by missirol** [comment]
backport of https://github.com/cms-sw/cmssw/pull/42491

**Comment by missirol** [comment]
please test

**Comment by missirol** [comment]
These errors seem related to the fact that https://github.com/cms-sw/cmssw/pull/41749 was not backported to `CMSSW_13_1_X`.

@SohamBhattacharya , is the plan to backport to 13_1_X all the HLT-Phase2-menu PRs of the last weeks (or only some PRs, like this one) ?

**Comment by SohamBhattacharya** [comment]
> These errors seem related to the fact that #41749 was not backported to `CMSSW_13_1_X`.
> 
> @SohamBhattacharya , is the plan to backport to 13_1_X all the HLT-Phase2-menu PRs of the last weeks (or only some PRs, like this one) ?

All the duplicate removal PRs need to be backported to 13_1_X as the plan is to run the timing measurement with a 13_1_X release.
I had missed at #41749 was not in 13_1.
@wonpoint4 can you please make a backport of the PR to 13_1_X?

**Comment by missirol** [comment]
FYI, #42351 and #42352 were not backported either.

**Comment by missirol** [comment]
please test with https://github.com/cms-sw/cmssw/pull/42555

**Comment by missirol** [comment]
please test

https://github.com/cms-sw/cmssw/pull/42555 should now be in the IB.

**Comment by missirol** [comment]
+hlt

**Comment by perrotta** [comment]
+1

**Pull request merged**
