### PR TITLE
Revert "Merge pull request #17175 from pietverwilligen/90X_NewME0GeometryBuilder_ForPR_v1" (only for L1 TDR production) [90X]

### PR DESCRIPTION
**Pull request by kpedro88**
`CMSSW_9_0_0` is planned to be used for the Phase2 L1Trigger TDR MC production. For expediency, we prefer to reuse existing GEN-SIM from the Phase2 Tracker TDR production, rerunning only the DIGI step. In order to have a compatible release, a change in the ME0 geometry (PR #17175) must be reverted. (The new improved ME0 geometry will be retained in CMSSW_9_1_X for further development and other future TDR productions.)

attn: @rekovic, @calabria, @jshlee, @pietverwilligen, @davidlange6, @mdhildreth

### CODE REVIEW

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by kpedro88** [comment]
Apparently the D11 detector was added after #17175 was merged, so reverting it did not fix that XML config. Good thing I added the unit test...

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by ianna** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Comment by kpedro88** [comment]
@davidlange6 is 90X still being merged into 91X? I would like to avoid a "revert revert" PR to 91X...

**Comment by ianna** [comment]
@kpedro88 - no, it was a clean 91x PR merger, reverted and merged again ;-)

**Comment by davidlange6** [comment]
we have never merged 90x into 91x

**Comment by davidlange6** [comment]
+1

**Pull request merged**
