### PR TITLE
First round of fixes to static analyzer warnings in Alignment

### PR DESCRIPTION
**Pull request by ghellwig**
Fixes warnings detected by

```
scram build -f compile COMPILER=llvm-analyzer SCRAM_IGNORE_MISSING_COMPILERS=yes
```

Not all warnings are fixed in this PR because they are either false alarms or require quite some redesign as , e.g., in the Cocoa-related packages.

### CODE REVIEW

**Comment by ghellwig** [comment]
please test

**Comment by mmusich** [comment]
+1 
@ghellwig since you are at it, you might want to remove in one of those files you touch, a coding rule violation:

`/Alignment/MuonAlignment/src/MuonAlignmentInputXML.cc` [L289] there is a `catch(...)` with no explicit exception.

**Comment by ghellwig** [comment]
@mmusich I have seen this, but I wasn't sure which types of exception should be handled here.
That's why I left it there for the time being, but I'll have a look and try to fix it soon.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
