### PR TITLE
Tracking validation updates/improvements

### PR DESCRIPTION
**Pull request by mmasciov**
### PR description:

This PR is aimed at updating/improving Multi-Track Validation in terms of style/readability and content.
In particular:
- Line colors are set to the same colors as markers (instead of black), and labels are increased for timing plots.
- Resolution plots are added per iteration, only for tracks `byOriginalAlgo`, to allow for more detailed studies.
- For phase-2, default pseudorapidity range for efficiency plot is increased to |η|<3.5.
- Cut on transverse impact parameter (TIP) is set to the same value for all efficiency plots (but efficiency vs TIP); previously, TIP cut was only updated for efficiency vs  η.

FYI, @kskovpen

### CODE REVIEW

**Comment by mmasciov** [comment]
type tracking

**Comment by mmasciov** [comment]
@cmsbuild please test

**Comment by mmasciov** [comment]
@cmsbuild please test

**Comment by mmasciov** [comment]
Ping to @cms-sw/dqm-l2

**Comment by mmasciov** [comment]
> `DQMHistoSizes: Histogram memory added: 756203.3350000001 KiB( 44 files compared)`
> 
> The DQMHIstoSize memory is increased considerably by 756MB. I suppose this effect comes from extending the pseudorapidity range increase to |η|<3.5 in Phase-2 from |η|<3.0. Still, I would feel more confident if you could cross-check and confirm this.

Thanks, @antoniovagnerini.
I believe that the increase in memory is actually mainly arising from the explicit addition in ad73592 - this commit is adding resolution plots for additional track collections.

>  In addition there is a large fraction of failures for most of the workflows, around 15% , is this also expected?

This is fully expected: failures appear (to me) all under Tracking, and this PR introduces changes (and what I would call a fix) in 8668222, that affects tracking comparisons.

**Comment by antoniovagnerini** [comment]
+1

**Comment by AdrianoDee** [comment]
Hi, unrequested question: do we need to have all these extra MTV plots enable by default? Meaning: can't these be restricted to specific workflows? I'm asking since these seem to have a pretty important impact on the memory usage and for Phase2 we are already fighting against a huge jumpy in memory usage (see https://github.com/cms-sw/cmssw/issues/45854) that could come from VALIDATION/DQM.

**Comment by mandrenguyen** [comment]
hold
Given the ongoing issues with memory consumption, it seems relevant before merging to respond to https://github.com/cms-sw/cmssw/pull/46324#issuecomment-2412201775

**Comment by mmasciov** [comment]
@cmsbuild please test

**Comment by mmasciov** [comment]
> Hi, unrequested question: do we need to have all these extra MTV plots enabled by default? Meaning: can't these be restricted to specific workflows? I'm asking since these seem to have a pretty important impact on the memory usage and for Phase2 we are already fighting against a huge jump in memory usage (see #45854) that could come from VALIDATION/DQM.

@AdrianoDee, I have modified this PR to only add the resolution plots for `trackingOnly` workflows.
FYI, @mandrenguyen

**Comment by AdrianoDee** [comment]
> @AdrianoDee, I have modified this PR to only add the resolution plots for `trackingOnly` workflows. FYI, @mandrenguyen

Very much appreciated @mmasciov.

**Comment by mmasciov** [comment]
Of course, @cms-sw/dqm-l2 shall also resign eventually. Thanks in advance!

**Comment by mmasciov** [comment]
@mandrenguyen, @cms-sw/dqm-l2 (FYI: @AdrianoDee): the error seems to be fully unrelated with this PR, and the comment about the increase in memory was addressed. Can this PR be signed again by DQM, unhold (by Matthew) and eventually merged?
Thanks!

**Comment by mmasciov** [comment]
@cmsbuild please test

**Comment by mmasciov** [comment]
Gentle ping to @cms-sw/dqm-l2 and @cms-sw/orp-l2

**Comment by antoniovagnerini** [comment]
+1

**Comment by antoniovilela** [comment]
unhold

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
