### PR TITLE
Fix HLT Validation tests [71X]

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
#### PR description:

Fix HLT Validation tests [71X]

#### PR validation:

TSG tests and HLT Validation tests

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A (71X specific)

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
type bug-fix

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
@qliphy @silviodonato 
Unrelated failures in the tests (not affected/touched by this PR)

**Comment by Martin-Grunewald** [comment]
+1

**Comment by qliphy** [comment]
@Martin-Grunewald  issue is known as reported in #32769 (comment)

**Comment by qliphy** [comment]
merge

**Pull request merged**
