### PR TITLE
bsunanda:Run2-alca53 Change output part for HcalIsolatedBunchFilter

### PR DESCRIPTION
**Pull request by bsunanda**
Change output command of HcalIsolatedBunchFilter and include them in some configuration file

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by mmusich** [comment]
```
Step: RAW2DIGI Spec: 
L1TRawToDigi Sequence configured for Run1 (Legacy) trigger. 
Step: L1Reco Spec: 
L1TReco Sequence configured for Run1 (Legacy) trigger. 
Step: RECO Spec: 
Step: ALCA Spec: ['SiStripCalZeroBias', 'SiStripCalMinBias', 'TkAlMinBiasHI', 'TkAlUpsilonMuMuHI', 'TkAlZMuMuHI', 'TkAlMuonIsolatedHI', 'TkAlJpsiMuMuHI', 'HcalCalMinBias']
DL enriching full SiStripCalZeroBias+SiStripCalMinBias+TkAlMinBiasHI+TkAlUpsilonMuMuHI+TkAlZMuMuHI+TkAlMuonIsolatedHI+TkAlJpsiMuMuHI+HcalCalMinBias
Traceback (most recent call last):
  File "/cvmfs/cms-ib.cern.ch/week1/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_X_2016-07-26-1300/bin/slc6_amd64_gcc530/cmsDriver.py", line 55, in <module>
    run()
  File "/cvmfs/cms-ib.cern.ch/week1/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_X_2016-07-26-1300/bin/slc6_amd64_gcc530/cmsDriver.py", line 27, in run
    configBuilder.prepare()
  File "/cvmfs/cms-ib.cern.ch/week1/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_X_2016-07-26-1300/python/Configuration/Applications/ConfigBuilder.py", line 2058, in prepare
    self.addStandardSequences()
  File "/cvmfs/cms-ib.cern.ch/week1/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_X_2016-07-26-1300/python/Configuration/Applications/ConfigBuilder.py", line 743, in addStandardSequences
    getattr(self,"prepare_"+stepName)(sequence = '+'.join(stepSpec))
  File "/cvmfs/cms-ib.cern.ch/week1/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_X_2016-07-26-1300/python/Configuration/Applications/ConfigBuilder.py", line 1236, in prepare_ALCA
    alcaConfig=self.loadDefaultOrSpecifiedCFF(sequence,self.ALCADefaultCFF)
  File "/cvmfs/cms-ib.cern.ch/week1/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_X_2016-07-26-1300/python/Configuration/Applications/ConfigBuilder.py", line 1188, in loadDefaultOrSpecifiedCFF
    l=self.loadAndRemember(defaultCFF,unsch)
  File "/cvmfs/cms-ib.cern.ch/week1/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_X_2016-07-26-1300/python/Configuration/Applications/ConfigBuilder.py", line 323, in loadAndRemember
    self.process.load(includeFile)
  File "/cvmfs/cms-ib.cern.ch/week1/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_X_2016-07-26-1300/python/FWCore/ParameterSet/Config.py", line 511, in load
    module = __import__(moduleName)
  File "/build/cmsbuild/jenkins-workarea/workspace/ib-any-integration/CMSSW_8_1_X_2016-07-26-1300/python/Configuration/StandardSequences/AlCaRecoStreamsHeavyIons_cff.py", line 60, in <module>
    from Calibration.HcalAlCaRecoProducers.ALCARECOHcalCalIsolatedBunchSelector_cff import *
ImportError: No module named ALCARECOHcalCalIsolatedBunchSelector_cff
```

**Comment by mmusich** [comment]
@bsunanda the backport doesn't seem complete

**Comment by bsunanda** [comment]
@mmusich This has to happen after merging PR#15258

**Comment by bsunanda** [comment]
@mmusich I shall ask the test only after merging of that PR

**Comment by mmusich** [comment]
why cannot be the two merged?

**Comment by mmusich** [comment]
Sorry I have overlooked this is not a backport... too many PRs.

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@mmusich Could you please approve this?

**Comment by mmusich** [comment]
+1

**Comment by franzoni** [comment]
+1

Tests show the filter is technically ok.
This filter is by construction low rate, therefore the extra content is manageable.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
