### PR TITLE
Run3-hcx331 Cleanup some of the codes in Validation/HcalRecHits

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Cleanup some of the codes in Validation/HcalRecHits

#### PR validation:

Use runTheMatrix test workflows

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
For some reason I don't understand, the results of this PR and https://github.com/cms-sw/cmssw/pull/37165 do not show the bin by bin results for all WFs but 1000.0
However, since RelMon is not showing any difference I am signing  the PR

**Comment by jfernan2** [comment]
+1

**Comment by qliphy** [comment]
please test
https://github.com/cms-sw/cmssw/pull/37172#issuecomment-1063114668

**Comment by jfernan2** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
