### PR TITLE
use `std::vector<T>::operator[]` in `edm::HLTGlobalStatus::operator[]`

### PR DESCRIPTION
**Pull request by missirol**
#### PR description:

This PR modifies the implementation of the methods `edm::HLTGlobalStatus::operator[]`, to use `std::vector<T>::operator[]` rather than `std::vector<T>::at` (the methods `edm::HLTGlobalStatus::at` remain available, and use `std::vector<T>::at`).

Arguably, the DataFormat should allow access to the faster `std::vector<T>::operator[]`, leaving it to users to choose the method (`at` or `[]`) most appropriate to their use case.

Reminder: `edm::HLTGlobalStatus` is a base class of `edm::TriggerResults`.

FYI: @cms-sw/hlt-l2

#### PR validation:

None.

#### If this PR is a backport, please specify the original PR and why you need to backport that PR. If this PR will be backported, please specify to which release cycle the backport is meant for:

N/A

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
> > an, in principle, result in undefined behavior
> 
> To see if I understand: what is currently tested centrally, or used in production, doesn't run this risk (otherwise it would be crashing already due to `vector::at` throwing an exception), whereas there is a potential problem with untested code/cases in CMSSW, and client code outside of it.

Correct, and with "untested cases" I'd (possibly too cautiously) include any future data we'll collect (depending if any of the callers actually depend on `operator[]` throwing an exception).

I'd hope there would not be much use of this class outside of CMSSW repository, but those are by construction outside of our direct control, so we can't do much else than noting the change in release notes.

> > So I wonder if all the callers should be checked
> 
> I would check it, but I couldn't see the list from the link you shared above (I'm not very familiar with DXR). The complication is, of course, that one needs to check also usage of `edm::TriggerResults::operator[]` (not just of `edm::HLTGlobalStatus::operator[]`): is there a way to get a list of all calls to those operators?

Right, my link was confusing, sorry about that (it pointed to the lines where `HLTGlobalStatus::operator[]` are defined, and there one would have had to left-click the function name and select the "Find callers"). To be more clear, here are the callers of

non-`const` overload ([link](https://cmssdt.cern.ch/dxr/CMSSW/search?q=%2Bcallers%3A%22edm%3A%3AHLTGlobalStatus%3A%3Aoperator%5B%5D%28const+unsigned+int%29%22), numbers refer to the line in code where the function in question is defined)
```
DQMServices/StreamerIO/plugins/TriggerSelector.cc
105: bool TriggerSelector::acceptEvent(unsigned char const* array_of_trigger_results, int number_of_trigger_paths) const {

FWCore/Framework/src/EventSelector.cc
286: bool EventSelector::acceptEvent(unsigned char const* array_of_trigger_results, int number_of_trigger_paths) const {
405: bool EventSelector::selectionIsValid(Strings const& pathspecs, Strings const& fullPathList) {
678: std::shared_ptr<TriggerResults> EventSelector::maskTriggerResults(TriggerResults const& inputResults) {

FWCore/Framework/src/Path.cc
175: void Path::recordStatus(int nwrwue, hlt::HLTState state) {

FWCore/Framework/test/EventSelExc_t.cpp
175: void evSelTest(PathSpecifiers const& ps, TrigResults const& tr, bool ans) {

FWCore/Framework/test/EventSelOverlap_t.cpp
165: void maskTest(PathSpecifiers const& ps, TrigResults const& tr, TrigResults const& ans) {

FWCore/Framework/test/EventSelWildcard_t.cpp
51: void testone(const Strings& paths, const Strings& pattern, const Bools& mask, bool answer, int jmask) {

FWCore/Framework/test/EventSelector_t.cpp
43: void testone(const Strings& paths, const Strings& pattern, const Bools& mask, bool answer, int jmask) {

PhysicsTools/NanoAOD/plugins/L1TriggerResultsConverter.cc
127: void L1TriggerResultsConverter::produce(edm::Event& iEvent, const edm::EventSetup& iSetup) {
```

`const` overload ([link](https://cmssdt.cern.ch/dxr/CMSSW/search?q=%2Bcallers%3A%22edm%3A%3AHLTGlobalStatus%3A%3Aoperator%5B%5D%28const+unsigned+int%29+const%22))
```
DQM/HLTEvF/plugins/TriggerRatesMonitor.cc
349: void TriggerRatesMonitor::dqmAnalyze(edm::Event const &event,

DQMOffline/Trigger/plugins/HigPhotonJetHLTOfflineSource.cc
344: bool HigPhotonJetHLTOfflineSource::isMonitoredTriggerAccepted(const edm::TriggerNames& triggerNames,

DQMServices/StreamerIO/plugins/TriggerSelector.cc
349: bool TriggerSelector::TreeElement::returnStatus(edm::HLTGlobalStatus const& trStatus) const {

FWCore/Framework/src/EventSelector.cc
369: bool EventSelector::acceptOneBit(Bits const& b, HLTGlobalStatus const& tr, hlt::HLTState const& s) const {
381: bool EventSelector::acceptAllBits(Bits const& b, HLTGlobalStatus const& tr) const {
678: std::shared_ptr<TriggerResults> EventSelector::maskTriggerResults(TriggerResults const& inputResults) {
835: bool EventSelector::containsExceptions(HLTGlobalStatus const& tr) const {

FWCore/Framework/test/stubs/TestTriggerNames.cc
83: void TestTriggerNames::analyze(edm::Event const& e, edm::EventSetup const&) {

HLTrigger/JSONMonitoring/plugins/HLTriggerJSONMonitoring.cc
275: void HLTriggerJSONMonitoring::analyze(edm::StreamID sid, edm::Event const& event, edm::EventSetup const&) const {
```

**Comment by missirol** [comment]
Thanks for clarifying, @makortel . I will have a look to try and address your review comments.

**Comment by missirol** [comment]
Part 1 of reply to https://github.com/cms-sw/cmssw/pull/40458#issuecomment-1376164555.

> non-`const` overload ([link](https://cmssdt.cern.ch/dxr/CMSSW/search?q=%2Bcallers%3A%22edm%3A%3AHLTGlobalStatus%3A%3Aoperator%5B%5D%28const+unsigned+int%29%22), numbers refer to the line in code where the function in question is defined)

---
```
DQMServices/StreamerIO/plugins/TriggerSelector.cc
105: bool TriggerSelector::acceptEvent(unsigned char const* array_of_trigger_results, int number_of_trigger_paths) const {
```
Keep `[]`.

Index `pathIndex` goes up to `number_of_trigger_paths - 1`, and `number_of_trigger_paths` defines the size of the `HLTGlobalStatus` object.
https://github.com/cms-sw/cmssw/blob/df24460a422a36e623e3ac5c0d4a4672ebff1773/DQMServices/StreamerIO/plugins/TriggerSelector.cc#L120
https://github.com/cms-sw/cmssw/blob/df24460a422a36e623e3ac5c0d4a4672ebff1773/DQMServices/StreamerIO/plugins/TriggerSelector.cc#L113

---
```
FWCore/Framework/src/EventSelector.cc
286: bool EventSelector::acceptEvent(unsigned char const* array_of_trigger_results, int number_of_trigger_paths) const {
```
Keep `[]`.

Index `pathIndex` goes up to `number_of_trigger_paths - 1`, and `number_of_trigger_paths` defines the size of the `HLTGlobalStatus` object.
https://github.com/cms-sw/cmssw/blob/df24460a422a36e623e3ac5c0d4a4672ebff1773/FWCore/Framework/src/EventSelector.cc#L307

---
```
FWCore/Framework/src/EventSelector.cc
405: bool EventSelector::selectionIsValid(Strings const& pathspecs, Strings const& fullPathList) {
```
Keep `[]`.

`hltGS` is a `HLTGlobalStatus` of size `fullPathCount` used to initialise a `TriggerResults` objected named `sampleResults`. The call is `sampleResults[iPath]`, where `iPath` is the index in a loop of length `fullPathCount`.
https://github.com/cms-sw/cmssw/blob/df24460a422a36e623e3ac5c0d4a4672ebff1773/FWCore/Framework/src/EventSelector.cc#L436

---
```
FWCore/Framework/src/EventSelector.cc
678: std::shared_ptr<TriggerResults> EventSelector::maskTriggerResults(TriggerResults const& inputResults) {
```
Keep `[]`.

`mask` (`HLTGlobalStatus`) has size `fullPathCount`.
All the `[]` calls use index `ipath`, which is always in loops of length `N`, where `N == fullPathCount`.
https://github.com/cms-sw/cmssw/blob/df24460a422a36e623e3ac5c0d4a4672ebff1773/FWCore/Framework/src/EventSelector.cc#L681

---
```
FWCore/Framework/src/Path.cc
175: void Path::recordStatus(int nwrwue, hlt::HLTState state) {
```
Change to `at`.

I don't see a guarantee that the class member `bitpos_` be within range of `*trptr_`.
https://github.com/cms-sw/cmssw/blob/df24460a422a36e623e3ac5c0d4a4672ebff1773/FWCore/Framework/src/Path.cc#L177

---
```
FWCore/Framework/test/EventSelExc_t.cpp
175: void evSelTest(PathSpecifiers const& ps, TrigResults const& tr, bool ans) {
```
Keep `[]`.

`bm[]` (`HLTGlobalStatus`) is only used in a standard loop over the size of `bm`:
https://github.com/cms-sw/cmssw/blob/df24460a422a36e623e3ac5c0d4a4672ebff1773/FWCore/Framework/test/EventSelExc_t.cpp#L189
(There are also `TriggerResults` objects in this function, but `[]` is not called on them.)

---
```
FWCore/Framework/test/EventSelOverlap_t.cpp
165: void maskTest(PathSpecifiers const& ps, TrigResults const& tr, TrigResults const& ans) {
```
Keep `[]`.

`bm[]` (`HLTGlobalStatus`) is only used in a standard loop over the size of `bm`:
https://github.com/cms-sw/cmssw/blob/df24460a422a36e623e3ac5c0d4a4672ebff1773/FWCore/Framework/test/EventSelOverlap_t.cpp#L170
Also, `sptr` (`TriggerResults`) comes from `EventSelector::maskTriggerResults`, and this boils down to `sptr->size() == TrigResults::bit.size() == 8` (`8` is hard-coded in this unit test),
so the following calls could stay with `[]`
https://github.com/cms-sw/cmssw/blob/df24460a422a36e623e3ac5c0d4a4672ebff1773/FWCore/Framework/test/EventSelOverlap_t.cpp#L184

---
```
FWCore/Framework/test/EventSelWildcard_t.cpp
51: void testone(const Strings& paths, const Strings& pattern, const Bools& mask, bool answer, int jmask) {
```
Keep `[]`.

`bm` (`HLTGlobalStatus`) has size `mask.size()`, and is always accessed within bounds (e.g. loop over its size, or `bm[4]` after `if (mask.size() > 4)`).
https://github.com/cms-sw/cmssw/blob/df24460a422a36e623e3ac5c0d4a4672ebff1773/FWCore/Framework/test/EventSelWildcard_t.cpp#L73
https://github.com/cms-sw/cmssw/blob/df24460a422a36e623e3ac5c0d4a4672ebff1773/FWCore/Framework/test/EventSelWildcard_t.cpp#L87-L89
(There are also `TriggerResults` objects in this function, but `[]` is not called on them.)

---
```
FWCore/Framework/test/EventSelector_t.cpp
43: void testone(const Strings& paths, const Strings& pattern, const Bools& mask, bool answer, int jmask) {
```
Keep `[]`.

`bm` (`HLTGlobalStatus`) has size `mask.size()`, and is always accessed within bounds (e.g. loop over its size, or `bm[4]` after `if (mask.size() > 4)`).
https://github.com/cms-sw/cmssw/blob/7d5358ff0e31e78fbcb737c05d218a55f5d82104/FWCore/Framework/test/EventSelector_t.cpp#L64
https://github.com/cms-sw/cmssw/blob/7d5358ff0e31e78fbcb737c05d218a55f5d82104/FWCore/Framework/test/EventSelector_t.cpp#L78-L80
(There are also `TriggerResults` objects in this function, but `[]` is not called on them.)

---
```
PhysicsTools/NanoAOD/plugins/L1TriggerResultsConverter.cc
127: void L1TriggerResultsConverter::produce(edm::Event& iEvent, const edm::EventSetup& iSetup) {
```
Keep `[]`.

`l1bitsAsHLTStatus` (`HLTGlobalStatus`) has size `names_.size()`, and `names_.size() == indices_.size()` or `names_.size() ==	indices_.size() + 1` based on
https://github.com/cms-sw/cmssw/blob/df24460a422a36e623e3ac5c0d4a4672ebff1773/PhysicsTools/NanoAOD/plugins/L1TriggerResultsConverter.cc#L103
On that premise, calls to `l1bitsAsHLTStatus[]` are within bounds
https://github.com/cms-sw/cmssw/blob/df24460a422a36e623e3ac5c0d4a4672ebff1773/PhysicsTools/NanoAOD/plugins/L1TriggerResultsConverter.cc#L149

**Comment by missirol** [comment]
Part 2 of reply to https://github.com/cms-sw/cmssw/pull/40458#issuecomment-1376164555.

> `const` overload ([link](https://cmssdt.cern.ch/dxr/CMSSW/search?q=%2Bcallers%3A%22edm%3A%3AHLTGlobalStatus%3A%3Aoperator%5B%5D%28const+unsigned+int%29+const%22))

---
```
DQM/HLTEvF/plugins/TriggerRatesMonitor.cc
349: void TriggerRatesMonitor::dqmAnalyze(edm::Event const &event,
```
Keep `[]` (modified recently in #40439, which is what led me to this PR).

The object is `hltResults` (`TriggerResults`), and the calls are here
https://github.com/cms-sw/cmssw/blob/master/DQM/HLTEvF/plugins/TriggerRatesMonitor.cc#L380-L410
For any (valid) value of `i`, `histograms.datasets[i]` and `histograms.streams[i]` are vectors of integers, and each of those integers is smaller than `histograms.hltConfig.size()`
https://github.com/cms-sw/cmssw/blob/df24460a422a36e623e3ac5c0d4a4672ebff1773/DQM/HLTEvF/plugins/TriggerRatesMonitor.cc#L192
https://github.com/cms-sw/cmssw/blob/df24460a422a36e623e3ac5c0d4a4672ebff1773/DQM/HLTEvF/plugins/TriggerRatesMonitor.cc#L211
then `histograms.hltConfig.size() == histograms.hltIndices.size()`
https://github.com/cms-sw/cmssw/blob/df24460a422a36e623e3ac5c0d4a4672ebff1773/DQM/HLTEvF/plugins/TriggerRatesMonitor.cc#L178
and `histograms.hltIndices.size() == hltResults.size()` when the `[]` calls occur
https://github.com/cms-sw/cmssw/blob/df24460a422a36e623e3ac5c0d4a4672ebff1773/DQM/HLTEvF/plugins/TriggerRatesMonitor.cc#L372
so every `histograms.{datasets,streams}[i][j]` integer is smaller than `hltResults.size()`.

---
```
DQMOffline/Trigger/plugins/HigPhotonJetHLTOfflineSource.cc
344: bool HigPhotonJetHLTOfflineSource::isMonitoredTriggerAccepted(const edm::TriggerNames& triggerNames,
```
Keep `[]`.

Call to `[]` happens in a standard loop over the size of a `TriggerResults`:
https://github.com/cms-sw/cmssw/blob/df24460a422a36e623e3ac5c0d4a4672ebff1773/DQMOffline/Trigger/plugins/HigPhotonJetHLTOfflineSource.cc#L348

---
```
DQMServices/StreamerIO/plugins/TriggerSelector.cc
349: bool TriggerSelector::TreeElement::returnStatus(edm::HLTGlobalStatus const& trStatus) const {
```
Keep `[]`.

Guaranteed within bounds thanks to exception-throwing condition a few lines above:
https://github.com/cms-sw/cmssw/blob/df24460a422a36e623e3ac5c0d4a4672ebff1773/DQMServices/StreamerIO/plugins/TriggerSelector.cc#L359

---
```
FWCore/Framework/src/EventSelector.cc
369: bool EventSelector::acceptOneBit(Bits const& b, HLTGlobalStatus const& tr, hlt::HLTState const& s) const {
```
Change to `at`.

No obvious guarantee that `bit.pos_ < tr.size()`: 
https://github.com/cms-sw/cmssw/blob/df24460a422a36e623e3ac5c0d4a4672ebff1773/FWCore/Framework/src/EventSelector.cc#L373

---
```
FWCore/Framework/src/EventSelector.cc
381: bool EventSelector::acceptAllBits(Bits const& b, HLTGlobalStatus const& tr) const {
```
Change to `at`.

No obvious guarantee that `bit.pos_ < tr.size()`:
https://github.com/cms-sw/cmssw/blob/df24460a422a36e623e3ac5c0d4a4672ebff1773/FWCore/Framework/src/EventSelector.cc#L384

---
```
FWCore/Framework/src/EventSelector.cc
678: std::shared_ptr<TriggerResults> EventSelector::maskTriggerResults(TriggerResults const& inputResults) {
```
Keep `[]`.

`inputResults` (`TriggerResults`) has size `fullPathCount` (an exception is thrown if `inputResults` is not of size `fullPathCount`). All the `[]` calls use index `ipath`, which is always in loops of length `N`, where `N == fullPathCount`.
https://github.com/cms-sw/cmssw/blob/df24460a422a36e623e3ac5c0d4a4672ebff1773/FWCore/Framework/src/EventSelector.cc#L681

---
```
FWCore/Framework/src/EventSelector.cc
835: bool EventSelector::containsExceptions(HLTGlobalStatus const& tr) const {
```
Keep `[]`.

Call to `[]` happens in a standard loop over the size of a `HLTGlobalStatus`:
https://github.com/cms-sw/cmssw/blob/df24460a422a36e623e3ac5c0d4a4672ebff1773/FWCore/Framework/src/EventSelector.cc#L838

---
```
FWCore/Framework/test/stubs/TestTriggerNames.cc
83: void TestTriggerNames::analyze(edm::Event const& e, edm::EventSetup const&) {
```
Keep `[]`, but add check throwing an exception.

Afaics, the `[]` calls are only
https://github.com/cms-sw/cmssw/blob/61cf0c713ec68f4dc3f4b5cbbb964a5d14fa671a/FWCore/Framework/test/stubs/TestTriggerNames.cc#L250-L251
https://github.com/cms-sw/cmssw/blob/61cf0c713ec68f4dc3f4b5cbbb964a5d14fa671a/FWCore/Framework/test/stubs/TestTriggerNames.cc#L259-L260
I don't see a guarantee that `hTriggerResults->size() > 0` (there is only a guarantee that `expectedTriggerResultsHLT_.size() > 0`). On the other hand, here the use of `TriggerResults::operator[]` appears to be deliberate, as it is done in parallel to calls to `TriggerResults::at`, so I doubt this should change. I tentatively added an exception-throwing condition.

---
```
HLTrigger/JSONMonitoring/plugins/HLTriggerJSONMonitoring.cc
275: void HLTriggerJSONMonitoring::analyze(edm::StreamID sid, edm::Event const& event, edm::EventSetup const&) const {
```
Keep `[]`.

`results` (`TriggerResults`) is accessed using the elements of `indicesOfTriggerPaths`
https://github.com/cms-sw/cmssw/blob/61cf0c713ec68f4dc3f4b5cbbb964a5d14fa671a/HLTrigger/JSONMonitoring/plugins/HLTriggerJSONMonitoring.cc#L297-L298
Every element of `indicesOfTriggerPaths` is guaranteed to be smaller than `triggerNamesSize == rundata->hltConfig.triggerNames().size()`
https://github.com/cms-sw/cmssw/blob/61cf0c713ec68f4dc3f4b5cbbb964a5d14fa671a/HLTrigger/JSONMonitoring/plugins/HLTriggerJSONMonitoring.cc#L204-L209
and `rundata.hltConfig.triggerNames().size() == results.size()` is enforced via `assert`
https://github.com/cms-sw/cmssw/blob/61cf0c713ec68f4dc3f4b5cbbb964a5d14fa671a/HLTrigger/JSONMonitoring/plugins/HLTriggerJSONMonitoring.cc#L293
so every `results[]` call is with index smaller than `results.size()`.

**Comment by missirol** [comment]
453dd74869c is an attempt to address https://github.com/cms-sw/cmssw/pull/40458#issuecomment-1375920382. Details are in https://github.com/cms-sw/cmssw/pull/40458#issuecomment-1377063697 and https://github.com/cms-sw/cmssw/pull/40458#issuecomment-1377066129.

**Comment by makortel** [comment]
Thanks @missirol for the extensive checks!

**Comment by makortel** [comment]
Header consistency check is failing because https://github.com/cms-sw/cmssw/pull/40474 was not included in the test.

**Comment by makortel** [comment]
release-note: This means that `edm::HLTGlobalStatus::operator[]()` and `edm::TriggerResults::operator[]()` no longer throw an exception in case the argument index is out of bounds. If the bounds-check is needed, please replace `operator[]()` call with `at()`.

**Comment by makortel** [comment]
+1

**Comment by rappoccio** [comment]
please test

* I would like to test this once more now that #40474 is included in the IBs just to be sure.

**Pull request merged**
