### PR TITLE
Hcal Code Integration Step 1

### PR DESCRIPTION
**Pull request by ianna**
- An attempt to pull minimum code required to integrate a new GT

### CODE REVIEW

**Comment by ianna** [comment]
@cmsbuild please test

**Comment by lveldere** [comment]
+1

**Comment by mmusich** [comment]
+1
for https://github.com/ianna/cmssw/commit/59259683c20ef123b1e6b2d9e324f7634ce6bec0

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
So what causes all of the tracker changes?

**Comment by ianna** [comment]
@davidlange6 - Tracker support and tracker cables were included with xml file migration: https://github.com/cms-sw/cmssw/commit/de8287825ac2385aa645c8ea086300e94a983c9b#diff-2fd59d68347d633d7f6daafd83b12c66
Shall I roll it back?

**Comment by davidlange6** [comment]
Yes. Changing the default geometries should be both discussed and done separately from a big technical change

**Comment by ianna** [comment]
@davidlange6 - ok

**Comment by ianna** [comment]
@cmsbuild please test

**Comment by civanch** [comment]
@ianna , seems that the number of differences is reduced only for tiny amount

**Comment by ianna** [comment]
@civanch - yes, I'm still debugging.

**Pull request closed without merging**
