### PR TITLE
Add scenario D51, move materials out of etl.xml

### PR DESCRIPTION
**Pull request by icosivi**
#### if this PR is a backport please specify the original PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by kpedro88** [comment]
@fabiocos does this really need to be separate from D50?

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by fabiocos** [comment]
@icosivi PR erroneously submitted

**Comment by fabiocos** [comment]
@kpedro88 this was created by mistake. Anyway scenario D50 was meant to be a technical migration point, D51 will have a completely different ETL. After validation we may even drop D50 as far as I am concerned (physics should be that of D46 in all respects).

**Pull request closed without merging**
