### PR TITLE
FastSim bugfix for gtDigis (7_4_X)

### PR DESCRIPTION
**Pull request by lveldere**
make the emulated gtDigis available under the label 'gtDigis' with an EDAlias to 'simGtDigis', required by HLT

### CODE REVIEW

**Comment by lveldere** [comment]
please test

**Comment by lveldere** [comment]
+1

**Comment by davidlange6** [comment]
@lveldere - could you check the reason for these fastsim failures?

**Comment by davidlange6** [comment]
@cmsbuild, please test

**Comment by lveldere** [comment]
the tests may crash unless
#8586 is included

**Comment by lveldere** [comment]
I'll rebase this one...

**Comment by lveldere** [comment]
note: changes to HLTriggerOffline package are already approved and merged here #8586

**Comment by lveldere** [comment]
please test

**Comment by lveldere** [comment]
+1

note, the changes that affect DQM are already merged here #8586

**Comment by lveldere** [comment]
gentle reminder,
please sign and merge this pr

**Comment by danduggan** [comment]
+1

**Comment by danduggan** [comment]
@lveldere, please be sure to submit a corresponding PR to the 75X release cycle

**Comment by lveldere** [comment]
it's taken care of

https://github.com/cms-sw/cmssw/pull/8489 takes care of the hlt btag
validator
https://github.com/cms-sw/cmssw/pull/8455 includes the fix to the gtDigis
label

**Comment by davidlange6** [comment]
+1

**Pull request merged**
