### PR TITLE
Clean up Phase 2 workflows (2020, 11_2_X)

### PR DESCRIPTION
**Pull request by kpedro88**
#### PR description:

Pursuant to #30512:

Remove outdated subdetectors:
* Tracker: T5, T6, T14, T16
* HGCal: C4, C6, C8
* Muon: M2, M3
* MTD: I5, I7, I9
* Common: O2, O3

Remove corresponding detector versions & workflows: D35, D41, D43, D44, D45, D46, D48

Replace some detector versions: D47 → D60 (keep C10, M3,F3 → M4,F4), D55 → D61 (keep M5, T19 → T17)

Remove unneeded eras: Phase2C4, Phase2C6, Phase2C8, phase2_trackerV14 (& corresponding dd4hep versions)

Currently, workflow numbers are preserved, to ensure consistency between 11_1_X and 11_2_X. The workflow number reset will be targeted for 12_0_X.

A subsequent PR (on top of this one) will try to consolidate HGCal eras.

Fascinatingly, this PR arrives exactly one year after the last cleanup in #27449 (and also contains a very similar amount of additions and deletions.)

#### PR validation:

Successfully ran workflows 23234.1001, 23234.103, 28234.0.

### CODE REVIEW

**Comment by kpedro88** [comment]
please test

**Comment by mmusich** [comment]
As D41 is removed, I think this unit test https://github.com/cms-sw/cmssw/blob/master/SLHCUpgradeSimulations/Geometry/test/phase2_digi_reco_pixelntuple.sh#L6 is going to fail. I suppose it could be migrated to use D49 (T15).

**Comment by kpedro88** [comment]
@mmusich thanks for pointing out the unit test. I have fixed it now. (Most files in test/ directories are not actually tested or maintained...)

**Comment by kpedro88** [comment]
please test

**Comment by kpedro88** [comment]
+upgrade

**Comment by chayanit** [comment]
+1

**Comment by cvuosalo** [comment]
+1

**Comment by kpedro88** [comment]
@rekovic @silviodonato please check and sign

**Comment by silviodonato** [comment]
merge

**Pull request merged**
