### PR TITLE
[94X] Fix static analyzer warnings in Alignment

### PR DESCRIPTION
**Pull request by ghellwig**
Fixes in total 82 static analyzer warnings in the `Alignment` package.

### CODE REVIEW

**Comment by ghellwig** [comment]
please test

**Comment by ghellwig** [comment]
@lpernie @arunhep I recommend to review this PR by [ignoring the whitespace changes](https://github.com/cms-sw/cmssw/pull/20433/files?w=1).
I had to convert some of the files first from DOS to unix format as this is the preferred format in CMSSW.

**Comment by ghellwig** [comment]
please test

**Comment by ghellwig** [comment]
@smuzaffar I applied the automatic code checks, but in one case they introduced a compilation error (see my last two commits).

**Comment by arunhep** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
