### PR TITLE
 Splitted HT category into CaloHT and PFHT categories (Backport from 76X #11150).

### PR DESCRIPTION
**Pull request by ryonamin**
(2015/09/24) Added changes of #11453.

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1

**Comment by deguio** [comment]
ciao @ryonamin 
you can update this one with the new scouting trigger names given that it is not yet merged.
thanks,
F.

**Comment by ryonamin** [comment]
Thank you! I didn't know this way and I noticed this is very convenient.
I have already modified the corresponding parts.

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1

**Comment by ryonamin** [comment]
I have made a new PR (#11620) instead of this PR because this PR can not be merged.

**Pull request closed without merging**
