### PR TITLE
Removed unused variable in TStorageFactoryFile

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

Fix warning from clang analyzer.

#### PR validation:

Code compiles.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by makortel** [comment]
@cmsbuild, please test

For cleaner comparisons.

**Comment by makortel** [comment]
Comparison differences are related to https://github.com/cms-sw/cmssw/issues/39803

**Comment by makortel** [comment]
+core

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
