### PR TITLE
Updated HI config

### PR DESCRIPTION
**Pull request by dinardo**
I've updated the HI configurazione for the incoming run

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1

**Comment by slava77** [comment]
@cmsbuild please test
[other 75X PRs from today didn't have DAS errors]

**Comment by slava77** [comment]
Is there an 80X version of this (and 76X)?

**Comment by dinardo** [comment]
Hi Slava77,
yes PR #12456 and PR #12455.
Cheers,
- Mauro.

**Comment by slava77** [comment]
merge

the only non-trivial change is in the online client config
DQM/Integration/python/clients/beampixel_dqm_sourceclient-live_cfg.py
.. and 80X  PR #12456 went in OK

**Pull request merged**
