### PR TITLE
Apply code checks to the Utilities packages

### PR DESCRIPTION
**Pull request by fwyzard**
Apply `clang-tidy` automated code changes.
Apply `clang-format` automated code formatting.

### CODE REVIEW

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by silviodonato** [comment]
please test

**Comment by silviodonato** [comment]
merge
I want this PR in the next IB
cc: 
core:  @Dr15Jones @makortel @smuzaffar
analysis:  @santocch

**Comment by silviodonato** [comment]
@cmsbuild merge

**Comment by silviodonato** [comment]
@cmsbuild code-checks

**Comment by silviodonato** [comment]
abort

**Comment by smuzaffar** [comment]
code-checks

**Comment by santocch** [comment]
+1

**Comment by makortel** [comment]
+1

**Pull request merged**
