### PR TITLE
Read generic slha file format.  

### PR DESCRIPTION
**Pull request by wulsin**
This module used to require that the input slha file use "Blo" with that capitalization, but not all slha files follow that convention.  This commit removes that assumption, and looks for the string "block" with an arbitrary capitalization.  Also, commented lines (beginning with "#") are now skipped.    

Other changes:  
    \* fix bug in specification of antiparticle width
    \* add LogInfo statements

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by civanch** [comment]
please test

**Comment by davidlange6** [comment]
this is good for 71x and 75x, but no need for 74x

**Pull request closed without merging**
