### PR TITLE
DD4Hep: DDTrackerRingAlgo Remove redundant matrices

### PR DESCRIPTION
**Pull request by vargasa**
#### PR description:

Remove redundant matrices https://github.com/cms-sw/cmssw/pull/26386#issuecomment-480884080

#### PR validation:

ScreenshotX

```
cmsRun Geometry/MTDGeometryBuilder/test/python/testMTDGeometry.py
./cmsShow -c simGeo.fwc --sim-geom-file cmsDD4HepGeom.root --tgeo-name=MTD
```
#### if this PR is a backport please specify the original PR:

No backport required

### CODE REVIEW

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
+1

**Comment by kpedro88** [comment]
@vargasa this PR includes the commit from #26472. It does not seem that two separate PRs are really necessary for small code review changes.

**Comment by vargasa** [comment]
@kpedro88 I have closed #26472 so we can proceed here if everything is fine

**Comment by kpedro88** [comment]
+upgrade

**Comment by kpedro88** [comment]
+1

**Pull request merged**
