### PR TITLE
[HGCAL] Updates due to V16 geometry

### PR DESCRIPTION
**Pull request by apsallid**
#### PR description:

Due to specific changes in V16 (D88) HGCAL geometry we make the following updates: 

1. We update the material budget code since three new materials are added (`Polystyrene`,`HGC_EEConnector` and `HGC_HEConnector`, essentially scintillator, Air and Air at the moment) while Cables are renamed to `HGC_Cables`. 
2. We update the dEdx weights script since the longitudinal structure of the detector is changed  with 3 layers removed apart from the addition/renaming of the materials mentioned above. 
3. We extend the basic scripts responsible for the webpage creation for the same reasons. 
4. Given the opportunity we correct my mistake on naming the `html.py` with the same name as a basic module,  a bad practice which I learned the hard way. So, we rename the `html.py` script to `hgcalHtml.py`. 

#### PR validation:

All the above have been tested/used on the latest `12_2_0_pre3_Phase2_D88` RelVal campaign for the creation of the validation report. 

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

This is not a backport.

@rovere @felicepantaleo @pfs @lecriste @ebrondol

### CODE REVIEW

**Comment by jfernan2** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by perrotta** [comment]
Is it an accepted practice to add large python notebooks as SimTracker/TrackerMaterialAnalysis/test/dEdxWeights.ipynb to CMSSW? @civanch

**Comment by pfs** [comment]
> Is it an accepted practice to add large python notebooks as SimTracker/TrackerMaterialAnalysis/test/dEdxWeights.ipynb to CMSSW? @civanch

@apsallid @all it's maybe better to commit the notebook clearing all the evaluated cells. github does not track evaluated notebooks very well once there are substantial changes, and it will also reduce substantially the size of the code in git

**Comment by apsallid** [comment]
@pfs Thanks a lot. I hope it is better now.

**Comment by perrotta** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by makortel** [comment]
Note that for a "PR size reduction" it would be better to remove the file from the history altogether (i.e. drop commits 8ff7c866e5f393bf8d50aec6e4211a5f6bc4ec45 and f26259997a0eb459c9ad2e5fe334a4b4ad4bdf25), because otherwise the file would be stored.

Although I'm now a bit confused of the last "This PR adds an extra 16KB to repository" compared to the earlier "120KB". @smuzaffar Can you tell why the added size became smaller even if the file is still in the history?

**Comment by smuzaffar** [comment]
@makortel , size calculation (https://github.com/cms-sw/cms-bot/blob/master/run-pr-code-checks#L57-L60 ) is based on current state of repository + pr. I really do not know what actually git does when it merges the PR but my guess is that resulted compressed `.git` directory will always have different size if upstream is changed

**Comment by apsallid** [comment]
@makortel @smuzaffar 

Really sorry but should I delete the commit [8ff7c86](https://github.com/cms-sw/cmssw/commit/8ff7c866e5f393bf8d50aec6e4211a5f6bc4ec45)? Because the last one, the [f262599](https://github.com/cms-sw/cmssw/pull/36645/commits/f26259997a0eb459c9ad2e5fe334a4b4ad4bdf25) contains the last file that we would like to merge to CMSSW. Am I understanding something wrong?

**Comment by makortel** [comment]
> Really sorry but should I delete the commit [8ff7c86](https://github.com/cms-sw/cmssw/commit/8ff7c866e5f393bf8d50aec6e4211a5f6bc4ec45)? Because the last one, the [f262599](https://github.com/cms-sw/cmssw/pull/36645/commits/f26259997a0eb459c9ad2e5fe334a4b4ad4bdf25) contains the last file that we would like to merge to CMSSW. Am I understanding something wrong?

As far as I can tell commit 8ff7c866e5f393bf8d50aec6e4211a5f6bc4ec45 only adds the file `SimTracker/TrackerMaterialAnalysis/test/dEdxWeights.ipynb`, and commit f26259997a0eb459c9ad2e5fe334a4b4ad4bdf25 only removes it (the two commits in between do not touch the file). Therefore dropping both commits should not change the net result of this PR for code changes, but allows the file to be never stored in the `cmssw` repository.

@smuzaffar Adding to my confusion, wasn't the bot supposed to report files that have been added and removed in a PR?

**Comment by apsallid** [comment]
@makortel 

Forgive me but do you mean to completely remove the file from repository? Like never be pushed and stored in CMSSW? I am sorry this is not what we want. The second commit meant to remove the output in the cells of the file, not the file itself. Sorry if I misunderstood.

**Comment by makortel** [comment]
I'm terribly sorry, I did not look the commit f262599 carefully enough. Right, the commit removes a lot of content of the file, but the file itself stays. Then, it would be better to squash f262599 into 8ff7c86 so that the larger version of the file would never need to be stored in the repository.

**Comment by cvuosalo** [comment]
+1

**Comment by jfernan2** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
