### PR TITLE
Fixed channel decoding for the timeout error in SiPixelRawToClusterGPUKernel

### PR DESCRIPTION
**Pull request by sroychow**
#### PR description:
Follow up of #42010 and addresses #41715 .

#### PR validation:
Done test in 13_0_X release with config and input file mentioned in #41715. Results from running GPU and CPU versions are same.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:
Not a backport.

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild ping?

**Comment by mmusich** [comment]
enable gpu

**Comment by mmusich** [comment]
test parameters:
   * enable = gpu
   * workflows_gpu = 11634.503, 11634.507, 11634.583, 11634.587, 11634.593
   * relvals_opt_gpu = --what upgrade,standard,highstats,pileup,generator,extendedgen,production,ged,machine,premix,nano

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mandrenguyen** [comment]
+reconstruction
Small diffs observed only in GPU workflow, for pixel tracking plots.  In line with expectation.

**Comment by perrotta** [comment]
+1

**Comment by mmusich** [comment]
@sroychow please prepare a backport for 13.2.x. 
@cms-sw/orp-l2 the backport of this will be needed for data-taking (it still needs to be validated somehow though)

**Pull request merged**
