### PR TITLE
Rekovic hlt 802 seed unpacked gt

### PR DESCRIPTION
**Pull request by rekovic**
```
// Two GT objects are obtained from the Event: (1) the unpacked GT and (2) the emulated GT.
// Return value of the filter is the score of seeding logical expression, evaluated using (1).
// Seeding is performed (per l1_algo) if ACCEPT both in (1) and (2). Seed objects are identified 
// and only available from ObjectMaps created in (2).
```

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by fwyzard** [comment]
@rekovic , can you check if using this change on top of CMSSW_8_0_1 (which has the uGT unpacker bug) the HLTL1TSeed module fails for all bits > 127 ?

**Comment by fwyzard** [comment]
@rekovic, since it looks like they are no longer used, do you think it would make sense to remove
  - the `seedsAll` method
 -  the `m_utml1GtMenu` and `m_l1GtMenuCacheID` data members
?

**Comment by rekovic** [comment]
@fwyzard 
> can you check if using this change on top of CMSSW_8_0_1 (which has the uGT unpacker bug) the HLTL1TSeed module fails for all bits > 127 ?

This, effectively the same, check was done in CMSSW_8_0_2 by re-introducing the bug (to extreme) 
<pre>maxPhysicsTriggers = 512 --> 1</pre>
in which case HLTL1TSeed modules that seed with l1algos bits > 1 all FAIL, which originally PASS.

**Comment by Martin-Grunewald** [comment]
+1

**Comment by rekovic** [comment]
@fwyzard 
> since it looks like they are no longer used, do you think it would make sense to remove the seedsAll method the m_utml1GtMenu and m_l1GtMenuCacheID data members ?

I would still keep them.  In the new version, the method seedsAll would be useable and configurable. Storing the information about the menu in m_utml1GtMenu and m_l1GtMenuCacheID is intended to be in use when re-running an HLT menu.

**Comment by fwyzard** [comment]
> In the new version, the method seedsAll would be usable and configurable. 

But what would be the use case for it ?

> Storing the information about the menu in m_utml1GtMenu and m_l1GtMenuCacheID is intended to be in use when re-running an HLT menu.

Ehm, what for, exactly ?
Do you foresee a third configurable "mode", which would run without any object map ?

**Comment by rekovic** [comment]
> But what would be the use case for it ?

An example would be some type of testing where any l1 object makes into the seeds of any HLT path.
This functionality is simply not there with the method seedsL1TriggerObjectMap which seeds only if
the L1T algos in the logical expression pass.

>Ehm, what for, exactly ?
>Do you foresee a third configurable "mode", which would run without any object map ?

In a hopefully short future, L1TMenu ID information will be stored in the unpacked uGT and the emulator AlgBlock.  Some of this information might be handy to store in the class. But if there is a strong preference to remove the variables at this point, we can do it.

**Comment by fwyzard** [comment]
please test

**Comment by rekovic** [comment]
please test

**Comment by perrotta** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
