### PR TITLE
[CMSSW_13_3_X backport] Add Correct EGM Run3 electron NonIso MVA ID for EB

### PR DESCRIPTION
**Pull request by Prasant1993**
#### PR description:
Same as PR #43275

#### PR validation:
Same as PR #43275 

Please test this PR with https://github.com/cms-data/RecoEgamma-ElectronIdentification/pull/29

#### Backport
This PR is backport of PR #43275. Backport is required for the production of Mini and V13 Nano from CMSSW_13.

### CODE REVIEW

**Comment by a-kapoor** [comment]
enable nano

**Comment by a-kapoor** [comment]
please test with https://github.com/cms-data/RecoEgamma-ElectronIdentification/pull/29

**Comment by a-kapoor** [comment]
@mandrenguyen @jfernan2 This PR fixes a bugged ID for electrons and we would like to make it in time for Nanov13. Is it possible to approve this as is? 
I see @jfernan2 comment in the same PR in master, regarding moving the text file to cms-data and indeed that's a possibility. But could we go ahead with this backport already? We can continue the discussion on moving the text file to cms-data for the master, if its ok.

**Comment by antoniovilela** [comment]
> @mandrenguyen @jfernan2 This PR fixes a bugged ID for electrons and we would like to make it in time for Nanov13. Is it possible to approve this as is? I see @jfernan2 comment in the same PR in master, regarding moving the text file to cms-data and indeed that's a possibility. But could we go ahead with this backport already? We can continue the discussion on moving the text file to cms-data for the master, if its ok.

Let's discuss in the master PR. We first approve and merge the master, then the backport.

**Comment by a-kapoor** [comment]
> > @mandrenguyen @jfernan2 This PR fixes a bugged ID for electrons and we would like to make it in time for Nanov13. Is it possible to approve this as is? I see @jfernan2 comment in the same PR in master, regarding moving the text file to cms-data and indeed that's a possibility. But could we go ahead with this backport already? We can continue the discussion on moving the text file to cms-data for the master, if its ok.
> 
> Let's discuss in the master PR. We first approve and merge the master, then the backport.

Ok. Thanks for the prompt response.

**Comment by antoniovilela** [comment]
backport of #43275

**Comment by antoniovilela** [comment]
+1

**Comment by antoniovilela** [comment]
-orp

**Comment by antoniovilela** [comment]
Please make the backport of the external PR in cmsdist (backport of https://github.com/cms-sw/cmsdist/pull/8824).

**Comment by Prasant1993** [comment]
> Please make the backport of the external PR in cmsdist (backport of [cms-sw/cmsdist#8824](https://github.com/cms-sw/cmsdist/pull/8824)).

Hi @antoniovilela, Sorry I don't quite fully understand the message of backport of external PR. The external PR, you meant this one : https://github.com/cms-data/RecoEgamma-ElectronIdentification/pull/29#event-10992699627. This is already merged to master.

**Comment by antoniovilela** [comment]
> > Please make the backport of the external PR in cmsdist (backport of [cms-sw/cmsdist#8824](https://github.com/cms-sw/cmsdist/pull/8824)).
> 
> Hi @antoniovilela, Sorry I don't quite fully understand the message of backport of external PR. The external PR, you meant this one : [cms-data/RecoEgamma-ElectronIdentification#29 (comment)](https://github.com/cms-data/RecoEgamma-ElectronIdentification/pull/29#event-10992699627). This is already merged to master.

When merging in cms-data, a new tag is created in the repository (RecoEgamma-ElectronIdentification). This tag needs to be propagated in cmsdist. A PR is created automatically for the master (here https://github.com/cms-sw/cmsdist/pull/8824). You need to backport the tag change to 13_3_X, otherwise 13_3_X will use the old tag and not see the cms-data update.

**Comment by Prasant1993** [comment]
> > > Please make the backport of the external PR in cmsdist (backport of [cms-sw/cmsdist#8824](https://github.com/cms-sw/cmsdist/pull/8824)).
> > 
> > 
> > Hi @antoniovilela, Sorry I don't quite fully understand the message of backport of external PR. The external PR, you meant this one : [cms-data/RecoEgamma-ElectronIdentification#29 (comment)](https://github.com/cms-data/RecoEgamma-ElectronIdentification/pull/29#event-10992699627). This is already merged to master.
> 
> When merging in cms-data, a new tag is created in the repository (RecoEgamma-ElectronIdentification). This tag needs to be propagated in cmsdist. A PR is created automatically for the master (here [cms-sw/cmsdist#8824](https://github.com/cms-sw/cmsdist/pull/8824)). You need to backport the tag change to 13_3_X, otherwise 13_3_X will use the old tag and not see the cms-data update.

Thanks for the clarification. If I understand correctly, do you mean this file https://github.com/Prasant1993/cmsdist/commit/21f835d3e48475f6f2c7a12453e2b478ecb97bb3 to be propagated to IB/CMSSW_13_3_X/master  by a pull request ?

**Comment by antoniovilela** [comment]
> > > > Please make the backport of the external PR in cmsdist (backport of [cms-sw/cmsdist#8824](https://github.com/cms-sw/cmsdist/pull/8824)).
> > > 
> > > 
> > > Hi @antoniovilela, Sorry I don't quite fully understand the message of backport of external PR. The external PR, you meant this one : [cms-data/RecoEgamma-ElectronIdentification#29 (comment)](https://github.com/cms-data/RecoEgamma-ElectronIdentification/pull/29#event-10992699627). This is already merged to master.
> > 
> > 
> > When merging in cms-data, a new tag is created in the repository (RecoEgamma-ElectronIdentification). This tag needs to be propagated in cmsdist. A PR is created automatically for the master (here [cms-sw/cmsdist#8824](https://github.com/cms-sw/cmsdist/pull/8824)). You need to backport the tag change to 13_3_X, otherwise 13_3_X will use the old tag and not see the cms-data update.
> 
> Thanks for the clarification. If I understand correctly, do you mean this file [Prasant1993/cmsdist@21f835d](https://github.com/Prasant1993/cmsdist/commit/21f835d3e48475f6f2c7a12453e2b478ecb97bb3) to be propagated to IB/CMSSW_13_3_X/master by a pull request ?

Yes, open a PR in cmsdist with https://github.com/cms-sw/cmsdist/pull/8824/commits/21f835d3e48475f6f2c7a12453e2b478ecb97bb3 backported to 13_3_X/master.
Thanks.

**Comment by Prasant1993** [comment]
> > > > > Please make the backport of the external PR in cmsdist (backport of [cms-sw/cmsdist#8824](https://github.com/cms-sw/cmsdist/pull/8824)).
> > > > 
> > > > 
> > > > Hi @antoniovilela, Sorry I don't quite fully understand the message of backport of external PR. The external PR, you meant this one : [cms-data/RecoEgamma-ElectronIdentification#29 (comment)](https://github.com/cms-data/RecoEgamma-ElectronIdentification/pull/29#event-10992699627). This is already merged to master.
> > > 
> > > 
> > > When merging in cms-data, a new tag is created in the repository (RecoEgamma-ElectronIdentification). This tag needs to be propagated in cmsdist. A PR is created automatically for the master (here [cms-sw/cmsdist#8824](https://github.com/cms-sw/cmsdist/pull/8824)). You need to backport the tag change to 13_3_X, otherwise 13_3_X will use the old tag and not see the cms-data update.
> > 
> > 
> > Thanks for the clarification. If I understand correctly, do you mean this file [Prasant1993/cmsdist@21f835d](https://github.com/Prasant1993/cmsdist/commit/21f835d3e48475f6f2c7a12453e2b478ecb97bb3) to be propagated to IB/CMSSW_13_3_X/master by a pull request ?
> 
> Yes, open a PR in cmsdist with [cms-sw/cmsdist@21f835d](https://github.com/cms-sw/cmsdist/commit/21f835d3e48475f6f2c7a12453e2b478ecb97bb3) backported to 13_3_X/master. Thanks.

Thanks. I opened a backport PR: https://github.com/cms-sw/cmsdist/pull/8825. Can you please check if this is fine ?

**Comment by antoniovilela** [comment]
+1

**Comment by antoniovilela** [comment]
@cms-sw/reconstruction-l2 
Please check and sign if all ok.

**Comment by antoniovilela** [comment]
merge
   - Merging since we need to get this in the IB.

**Comment by jfernan2** [comment]
+1

**Comment by vlimant** [comment]
assign xpog

**Comment by vlimant** [comment]
+1

**Pull request merged**
