### PR TITLE
Add PythiaMomDauFilter filter 20151218

### PR DESCRIPTION
**Pull request by taweiXcms**
Add and fix PythiaMomDauFilter from 80X

@mandrenguyen, @yenjie, @ginnocen

### CODE REVIEW

**Comment by taweiXcms** [comment]
Dear contacts/managers, 
This is a PR of a filter that is needed for the D0/D* PbPb MC generation.
pp group are using the same filter.
Could you have a look and let us know if we are missing anything?
Thank you for your help.

**Comment by govoni** [comment]
+1

**Comment by taweiXcms** [comment]
Dear contacts.

Could you please have a quick at this PR and see what's needed to get into next stage?
It's been pending for a few weeks.
We really appreciate your help.
Thank you.

 @yenjie, @ginnocen

**Comment by davidlange6** [comment]
+1

**Pull request merged**
