### PR TITLE
[14_0_X] Phase2 Fast CPE Template Error Fix

### PR DESCRIPTION
**Pull request by AdrianoDee**
Plain backport of #44916.

### CODE REVIEW

**Comment by AdrianoDee** [comment]
backport of #44916

**Comment by mmusich** [comment]
type bug-fix

**Comment by AdrianoDee** [comment]
please test

**Comment by AdrianoDee** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by antoniovilela** [comment]
+1

**Comment by rappoccio** [comment]
+1

**Pull request merged**
