### PR TITLE
Set MaxADC0 threshold to 9999

### PR DESCRIPTION
**Pull request by dertexaner**

### CODE REVIEW

**Comment by abdoulline** [comment]
Slava, David,
 we need this fix asap in the data taking (74X) to avoid excessive events rejection caused by just a handful of (malfunctioning) channels...

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/10371	dc61c57
- config level change effectively disables a flag in the noise summary flag
- jenkins tests pass and comparisons with the baseline show no differences (MC and run1 data don't have this flag contributing frequently)
- local tests in CMSSW_7_4_X_2015-07-24-2300 /test area test10371/ using run 2 run 251721 doublemu data in /store/data/Run2015B/DoubleMuon/RAW/v1/000/251/721/00000/44C77595-412A-E511-930E-02163E012A2C.root show expected changes:
    - monitored reco products are not changing except for the noise flag itself (fwlite based plots)
    - DQM plots show differences only in jet/met plots that require some noise cleaning. There is a very large number of events that pass and enter the plots now
251721_pfmet_dijet_sumet

**Comment by davidlange6** [comment]
+1

**Pull request merged**
