### PR TITLE
relval scripts update after 760pre7 validation

### PR DESCRIPTION
**Pull request by hengne**
relval scripts update after 760pre7 validation
1.) update mixing/premixing inputs
2.) fix extended generator job splitting issue
3.) add '_' in front of '25ns' and '50ns', such as "HLTDR225ns" to "HLTDR2_25ns",  to have the separation better visible. As suggested by David @davidlange6

### CODE REVIEW

**Comment by fabozzi** [comment]
please test

**Comment by fabozzi** [comment]
+1

**Comment by davidlange6** [comment]
@hengne - this doesn't merge - could you rebase it?

**Comment by hengne** [comment]
@davidlange6  rebased.

**Comment by fabozzi** [comment]
please test

**Comment by fabozzi** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
