### PR TITLE
 CTPPS: tracking of the numberOfClusters field sent by VFAT - backport of #14615

### PR DESCRIPTION
**Pull request by grzanka**
Backport of #14615 from CMSSW 81X

Also includes a module for printing VFAT frames (debugging tool).

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test
IIRC this one is independent from the CTPPS eras PR

**Comment by slava77** [comment]
errors are IB infrastructure problems

**Comment by slava77** [comment]
@cmsbuild please test
... not sure it leads to something working in IB

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/14758	eadacf3
- backport of https://github.com/cms-sw/cmssw/pull/14615	3acf13a; changes are the same as in 81X. The code modified is not running yet in standard sequences. So, no changes expected
- jenkins tests pass and comparisons show no differences.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
