### PR TITLE
[93X] GT Updates for L1T conditions needed for emulator

### PR DESCRIPTION
**Pull request by arunhep**
# Summary of changes in Global Tags 
 
## RunII simulation 
 
   * **RunII Asymptotic scenario** : [93X_mcRun2_asymptotic_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/93X_mcRun2_asymptotic_v2) as [93X_mcRun2_asymptotic_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/93X_mcRun2_asymptotic_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/93X_mcRun2_asymptotic_v2/93X_mcRun2_asymptotic_v1): 
      * update of L1T conditions for emulator : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3188/4/1.html

   * **RunII CRAFT scenario** : [93X_mcRun2cosmics_startup_deco_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/93X_mcRun2cosmics_startup_deco_v1) as [93X_mcRun2cosmics_startup_deco_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/93X_mcRun2cosmics_startup_deco_v0) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/93X_mcRun2cosmics_startup_deco_v1/93X_mcRun2cosmics_startup_deco_v0): 
      * update of L1T conditions for emulator : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3188/4/1.html

   * **RunII Heavy Ions scenario** : [93X_mcRun2_HeavyIon_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/93X_mcRun2_HeavyIon_v1) as [93X_mcRun2_HeavyIon_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/93X_mcRun2_HeavyIon_v0) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/93X_mcRun2_HeavyIon_v1/93X_mcRun2_HeavyIon_v0): 
      * update of L1T conditions for emulator : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3188/4/1.html

   * **RunII Ideal scenario** : [93X_mcRun2_design_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/93X_mcRun2_design_v1) as [93X_mcRun2_design_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/93X_mcRun2_design_v0) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/93X_mcRun2_design_v1/93X_mcRun2_design_v0): 
      * update of L1T conditions for emulator : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3188/4/1.html

   * **RunII Proton-Lead scenario** : [93X_mcRun2_pA_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/93X_mcRun2_pA_v1) as [93X_mcRun2_pA_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/93X_mcRun2_pA_v0) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/93X_mcRun2_pA_v1/93X_mcRun2_pA_v0): 
      * update of L1T conditions for emulator : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3188/4/1.html

   * **RunII Startup scenario** : [93X_mcRun2_startup_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/93X_mcRun2_startup_v1) as [93X_mcRun2_startup_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/93X_mcRun2_startup_v0) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/93X_mcRun2_startup_v1/93X_mcRun2_startup_v0): 
      * update of L1T conditions for emulator : https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3188/4/1.html

### CODE REVIEW

**Comment by arunhep** [comment]
attn. @kkotov @rekovic this is for 93X. so please backport your PR to 93X as well once you think its fine for master.

**Comment by arunhep** [comment]
please test

**Comment by arunhep** [comment]
backport of #20494

**Comment by arunhep** [comment]
add-on errors come from here https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-20495/22940/addOnTests/hlt_mc_Fake1/cmsDriver.py_TTbar_Tauola_13TeV_TuneCUETP8M1_cfi_-s_GEN,SIM,DIGI,L1,DIGI2RAW_--mc_--scenario=pp_-n_10_--conditions_auto:run2_mc_Fake1_--relval_9000,50.log

with the error message mainly says : 

----- Begin Fatal Exception 13-Sep-2017 13:31:15 CEST-----------------------
An exception of category 'OutOfRange' occurred while
   [0] Processing  Event run: 1 lumi: 1 event: 3 stream: 0
   [1] Running path 'L1simulation_step'
   [2] Calling method for module L1TPhysicalEtAdder/'simCaloStage1FinalDigis'
Exception Message:
Index out of range in L1CaloEtScale::et(rank)
----- End Fatal Exception -------------------------------------------------
----- Begin Fatal Exception 13-Sep-2017 13:31:16 CEST-----------------------
An exception of category 'OutOfRange' occurred while
   [0] Processing  Event run: 1 lumi: 1 event: 2 stream: 3
   [1] Running path 'L1simulation_step'
   [2] Calling method for module L1TPhysicalEtAdder/'simCaloStage1FinalDigis'
Exception Message:
Index out of range in L1CaloEtScale::et(rank)
----- End Fatal Exception -------------------------------------------------
----- Begin Fatal Exception 13-Sep-2017 13:31:22 CEST-----------------------
An exception of category 'OutOfRange' occurred while
   [0] Processing  Event run: 1 lumi: 1 event: 1 stream: 1
   [1] Running path 'L1simulation_step'
   [2] Calling method for module L1TPhysicalEtAdder/'simCaloStage1FinalDigis'
Exception Message:
Index out of range in L1CaloEtScale::et(rank)
----- End Fatal Exception -------------------------------------------------
----- Begin Fatal Exception 13-Sep-2017 13:31:53 CEST-----------------------
An exception of category 'OutOfRange' occurred while
   [0] Processing  Event run: 1 lumi: 1 event: 4 stream: 2
   [1] Running path 'L1simulation_step'
   [2] Calling method for module L1TPhysicalEtAdder/'simCaloStage1FinalDigis'
Exception Message:
Index out of range in L1CaloEtScale::et(rank)
----- End Fatal Exception -------------------------------------------------

@kkotov @rekovic @Martin-Grunewald any idea what is missing or to be updated?

**Comment by rekovic** [comment]
It is interesting that in 94x PR (#20494), shows the same Exceptions, 
but in **different** AddOn tests: 
- "fastsim" ([log](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-20494/22935/addOnTests/fastsim/cmsDriver.py_TTbar_8TeV_TuneCUETP8M1_cfi__--conditions_auto:run1_mc_--fast__-n_100_--eventcontent_AODSIM,DQM_--relval_100000,1000_-s_GEN,SIM,RECOBEFMI.log)) 
- "fastsim1" ([log](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-20494/22935/addOnTests/fastsim1/TTbar_13TeV_TuneCUETP8M1_cfi_GEN_SIM_RECOBEFMIX_DIGI_L1_DIGI2RAW_L1Reco_RECO_EI_VALIDATION.py))
- and not the "hlt_mcFake1", as it is the case here in 93x.

I am confused.

**Comment by rekovic** [comment]
@arunhep This is strange. 
I suggest we test for reproducibility, and test again.

**Comment by arunhep** [comment]
please test

**Comment by rekovic** [comment]
@arunhep  The things are understood.

The AddOn tests that are failing are the ones using `--era Run2_25ns` ( invoking Stage1 L1T emulator) with  `--conditions auto:run2_mc_Fake1`, which up to now was identical to `auto:run2_mc`
'run2_mc_Fake1'          : ('run2_mc'              ,l1Menus['Fake1']),

Prior to this PR, the alias 'run2_mc` was pointing to
```'run2_mc'           :   '93X_mcRun2_asymptotic_v1',```
which had the right conditions for Stage1 emulator.

With your PR, the ```'run2_mc'```was updated to ```'93X_mcRun2_asymptotic_**v2**',``` which is what we want for Stage2.

For Stage1, we still want to keep ```'93X_mcRun2_asymptotic**_v1**'``` as it have conditions relevant for 2015.  So I am going to introduce  a new alias 
```'run2_mc_**Stage1**'           :   '93X_mcRun2_asymptotic_v1',``` 
and have the relevant AddOn test use that alias.

I will now provide a PR, so this PR can be tested with it.

**Comment by arunhep** [comment]
may not be needed anymore. closing it for now. will reopen if needed.

**Pull request closed without merging**
