### PR TITLE
Speedup PixelLess seeding

### PR DESCRIPTION
**Pull request by VinInn**
Major code re-engineering of MultiHitGeneratorFromChi2:
half of the speedup comes from improvements in the Strip part of ClusterShapeHitFilter.
took the opportunity to address few more minor improvements.

Negligible regression is expected due to numerics and small changes in the logic.
Physics is not expected to change.
MTV for PU50 ttbar in
http://innocent.home.cern.ch/innocent/RelVal/pu50_opt91/plots_summary.html

following comments will address speed improvements.

### CODE REVIEW

**Comment by VinInn** [comment]
910_pre2 perfomance graph (cycles)
```
   - 4.37% MultiHitGeneratorFromChi2::hitSets                                                                                                                                    ▒
      - 2.01% MultiHitGeneratorFromChi2::refit2Hits                                                                                                                              ▒
         + 1.50% SiStripMatchedRecHit2D::clone                                                                                                                                   ▒
           0.15% _ZN10FastCircleC1ERK11Point3DBaseIf9GlobalTagES4_S4_@plt                                                                                                        ▒
         - 0.12% GlobalTrajectoryParameters::GlobalTrajectoryParameters                                                                                                          ▒
              VolumeBasedMagneticField::inTesla                                                                                                                                  ▒
      - 0.47% ClusterShapeHitFilter::isCompatible                                                                                                                                ▒
         - 0.43% ClusterShapeHitFilter::getSizes                                                                                                                                 ▒
            - 0.21% ClusterShapeHitFilter::getDrift                                                                                                                              ▒
                 0.11% VolumeBasedMagneticField::inTesla                                                                                                                         ▒
      + 0.31% SiStripRecHit2D::clone                                                                                                                                             ▒
      - 0.18% ClusterShapeHitFilter::isCompatible                                                                                                                                ▒
         - 0.13% ClusterShapeHitFilter::isCompatible                                                                                                                             ▒
              0.12% ClusterShapeHitFilter::getSizes                                                                                                                              ▒
        0.18% _ZNK28ThirdHitPredictionFromCircle3phiEff@plt                                                                                                                      ▒
      + 0.18% SiStripMatchedRecHit2D::clone                                                                                                                                      ▒
        0.17% KDTreeLinkerAlgo<__gnu_cxx::__normal_iterator<RecHitsSortedInPhi::HitWithPhi const*, std::vector<RecHitsSortedInPhi::HitWithPhi, std::allocator<RecHitsSortedInPhi:▒
        0.13% _ZN10FastCircleC1ERK11Point3DBaseIf9GlobalTagES4_S4_@plt                                                                                                           ▒

```

**Comment by VinInn** [comment]
performance graph for this PR
```
   - 3.22% MultiHitGeneratorFromChi2::hitSets                                                                                                                                                                                       ▒
      - 1.17% SiStripMatchedRecHit2D::clone                                                                                                                                                                                         ▒
         + TkClonerImpl::operator()                                                                                                                                                                                                 ▒
      - 0.40% MultiHitGeneratorFromChi2::hitSets(TrackingRegion const&, OrderedMultiHits&, edm::EventSetup const&, HitDoublets const&, RecHitsSortedInPhi const**, std::vector<DetLayer const*, std::allocator<DetLayer const*> > co▒
         - 0.29% ClusterShapeHitFilter::isCompatible                                                                                                                                                                                ▒
            - 0.13% ClusterShapeHitFilter::isCompatible                                                                                                                                                                             ▒
                 0.10% ClusterShapeHitFilter::getSizes                                                                                                                                                                              ▒
      - 0.40% MultiHitGeneratorFromChi2::refit2Hits                                                                                                                                                                                 ▒
           0.15% _ZN10FastCircleC1ERK11Point3DBaseIf9GlobalTagES4_S4_@plt                                                                                                                                                           ▒
      + 0.27% SiStripRecHit2D::clone                                                                                                                                                                                                ▒
        0.21% _ZNK28ThirdHitPredictionFromCircle3phiEff@plt                                                                                                                                                                         ▒
        0.19% KDTreeLinkerAlgo<__gnu_cxx::__normal_iterator<RecHitsSortedInPhi::HitWithPhi const*, std::vector<RecHitsSortedInPhi::HitWithPhi, std::allocator<RecHitsSortedInPhi::HitWithPhi> > > >::recSearch                      ▒
        0.14% _ZN10FastCircleC1ERK11Point3DBaseIf9GlobalTagES4_S4_@plt                                                                                                                                                              ▒
 
```

**Comment by VinInn** [comment]
@cmsbuild, please test

**Comment by VinInn** [comment]
910pre2
TimeReport   0.267741     0.267741  pixelLessStepHitTriplets
this PR
TimeReport   0.179674     0.179674  pixelLessStepHitTriplets

**Comment by VinInn** [comment]
@cmsbuild, please test

**Comment by perrotta** [comment]
+1
Checks with wfs 10224 (TTbar) and 10059 (QCD high pt) confirm what reported in the summary plots attached in the description of this PR; also verified that there is no significant effect on other high level observables in the event.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
