### PR TITLE
puppi bug fix for low PU case

### PR DESCRIPTION
**Pull request by nhanvtran**
Hi, a small bug fix for PUPPI in the case of very low PU (< 5 nPU) that was not included in the first PR for 75X. 

Thanks

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
@nhanvtran: Is there any simple way to verify if your bug fix is working? What test procedure would show its effectiveness? The Jenkins tests show no differences.
Also, in the PR description, please give the PR number of other PR you mention.

**Comment by cvuosalo** [comment]
+1

For #9338 35a35c3c9abcca6af727fe0405ef11d51c0e00cd

A PUPPI bug fix to cover the case of very low pile-up.

The code changes are satisfactory, and Jenkins tests showed no significant differences before they were mysteriously deleted. Tests of the Mini-AOD step of workflow 25202.0_TTbar_13 against baseline CMSSW_7_5_X_2015-05-28-2300 show little change in product size and some improvements in CPU time:
```
Product size
-------------------------------------------------------------
 or, B       new, B      delta, B   delta, %   deltaJ, %    branch 
-------------------------------------------------------------
    20096 ->       20102          6      0.0   0.01     patPackedCandidates_packedPFCandidates__PAT.
     3333 ->        3342          9      0.3   0.01     patJets_slimmedJetsPuppi__PAT.
     2676 ->        2676          0      0.0   0.00     patTaus_slimmedTaus__PAT.
     7873 ->        7874          0      0.0   0.00     patMuons_slimmedMuons__PAT.
     1061 ->        1061         -0     -0.0  -0.00     recoSuperClusters_reducedEgamma_reducedSuperClusters_PAT.
     1059 ->        1059          0      0.0   0.00     patMETs_slimmedMETsPuppi__PAT.
     4316 ->        4317          0      0.0   0.00     patPackedGenParticles_packedGenParticles__PAT.
      594 ->         594          0      0.0   0.00     patPackedCandidates_lostTracks__PAT.
     6212 ->        6213          0      0.0   0.00     patElectrons_slimmedElectrons__PAT.
-------------------------------------------------------------
    80852 ->       80868         16             0.0     ALL BRANCHES

CPU timing
  delta/mean delta/orJob     original                   new       module name
 ---------- ------------     --------                  ----       ------------
   -0.197677      -0.20%        17.98 ms/ev ->        14.74 ms/ev prunedGenParticles
   -0.165684      -1.10%       113.47 ms/ev ->        96.11 ms/ev pfImpactParameterTagInfos
   -0.148244      -0.34%        39.00 ms/ev ->        33.61 ms/ev pfImpactParameterTagInfosPuppi
   -0.143759      -0.13%        15.02 ms/ev ->        13.01 ms/ev pfImpactParameterTagInfosAK8
   -0.109312      -0.54%        82.18 ms/ev ->        73.66 ms/ev prunedGenParticlesWithStatusOne
   -0.093345      -0.11%        19.85 ms/ev ->        18.08 ms/ev patJets
   -0.072463      -0.18%        40.11 ms/ev ->        37.31 ms/ev pfCandsNotInJetsPtrForMetCorr
   +0.072287      +0.71%       148.82 ms/ev ->       159.98 ms/ev primaryVertexAssociation
   -0.067441      -0.02%         5.61 ms/ev ->         5.24 ms/ev patPFJetMETtype1p2CorrEnDown
   +0.064363      +0.03%         6.13 ms/ev ->         6.54 ms/ev patJetCorrFactors
   -0.059031      -0.02%         5.83 ms/ev ->         5.49 ms/ev patPFJetMETtype1p2CorrEnUp
   -0.055614      -0.09%        26.21 ms/ev ->        24.79 ms/ev tauIsoDepositPFCandidates
   +0.055359      +0.03%         7.29 ms/ev ->         7.70 ms/ev patJetCorrFactorsAK4PFForMetUnc
---------- ------------     --------                  ----       ------------
Job total:  1.57837 s/ev ==> 1.53356 s/ev
```

**Comment by nhanvtran** [comment]
@cvuosalo 
the other PR was #9142  

So it basically only changes the behavior of the algorithm for < 5 PU so you won't see many differences, not sure of an obvious workflow to test it...

**Pull request merged**
