### PR TITLE
updates needed for tensorflow 1.5.0

### PR DESCRIPTION
**Pull request by smuzaffar**
Migrating to tensorflow 1.5.0:
We have to update bazel ( see the cmsdist Pr here https://github.com/cms-sw/cmsdist/pull/3717 ). This means we have to move to bit newer tensorflow too (1.5.0). 
@pablodecm  and @riga can you please check this? Is there any runTheMatrix workflow which uses code?

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test with cms-sw/cmsdist#3717

**Comment by riga** [comment]
Hi @smuzaffar ,
as far as I can see, version 1.5 does not introduce any API breaking change that would affect the code in PhysicsTools/TensorFlow.

**Comment by slava77** [comment]
it looks like more changes are necessary

the crash is in (stripped)
```
#5   in std::_Function_handler<tensorflow::Status , NTSession::GetOrCreateExecutors(ArraySlice<std::string> ...
#6  tensorflow::(anonymous namespace)::ExecutorImpl::Initialize()
```

**Comment by riga** [comment]
I'll check the diffs that affect our custom Session implementations and let you know what is causing the crash.

**Comment by riga** [comment]
The required changes are not that trivial.

@smuzaffar I'm currently working on a local checkout and submit a PR to your tensorflow-1.5.0 branch, ok?

**Comment by smuzaffar** [comment]
@riga, either a PR to my tensorflow-1.5.0 branch or a fresh PR for cms-sw/cmssw is fine with me.

**Comment by riga** [comment]
I created a PR (smuzaffar/cmssw#2) for this branch that adjusts the NTSession files. When cmsbuild is successful I'll add the TBBSession files again.

**Comment by smuzaffar** [comment]
please test with cms-sw/cmsdist#3717

**Comment by riga** [comment]
@smuzaffar Could you give me push access to your tensorflow-1.5.0 branch? There seems to be a wrong include which I can quickly fix.

**Comment by smuzaffar** [comment]
@riga, I think push rights to a branch can be given by an organization. I can not do it for my repo. Please feel free to open a fresh PR in cms-sw/cmssw (including these changes and any others you need).

**Comment by riga** [comment]
Ok, will do.

**Comment by slava77** [comment]
@riga @Dr15Jones 
is there a real problem with the TBBSession or is it just a temporary workaround.
Chris, you mentioned in the past some "tension" between TBB and TF from the development perspective.

**Comment by riga** [comment]
@slava77 It's just a temporary workaround since the NTSession is somewhat easier to debug. I will add it again once the NTSession is working.

**Comment by slava77** [comment]
@riga @smuzaffar 
I just wanted to check if this is waiting for some fix outside of cms-sw/cmssw 
Please clarify.

**Comment by riga** [comment]
@slava77 We moved the changes to another PR (#22260) which passed the tests. If @smuzaffar agrees, this PR can be closed.

**Comment by slava77** [comment]
-1

superseded by #22260

**Comment by smuzaffar** [comment]
closing in favor of #22260

**Pull request closed without merging**
