### PR TITLE
Switch to emplace to put data products

### PR DESCRIPTION
**Pull request by Dr15Jones**
Changed many of the modules used in the Framework or for tests to use emplace instead of put when putting a data product into the Event, LuminosityBlock or Run.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
hold
This should wait for CMSSW_10_3

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
@slava77 I've looked through the comparison information and can't seem to find the '31' failures.

**Comment by slava77** [comment]
here is a random one from the failed comparisons
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_10_2_X_2018-07-13-2300+23791/27420/136.85_RunEGamma2018A+RunEGamma2018A+HLTDR2_2018+RECODR2_2018reHLT_skimEGamma_Prompt_L1TEgDQM+HARVEST2018_L1TEgDQM/HLT_EGM_Source_Histos_hltEle15Ele8CaloIdLTrackIdLIsoVLEtLeg1Filter.html

AFAIK, these are random, and perhaps not reproducible.

**Comment by Dr15Jones** [comment]
@slava77 thanks. How did you figure out which links to check to find the differences?

**Comment by Dr15Jones** [comment]
+1

**Comment by slava77** [comment]
On 7/15/18 1:03 PM, Chris Jones wrote:
> thanks. How did you figure out which links to check to find the differences?

In this case I just random-walked.

**Comment by Dr15Jones** [comment]
unhold

**Comment by fabiocos** [comment]
@Dr15Jones @slava77 I do not recall such a large number of DQM failures recently, one or two at most in recent times, just to have a final check let me rerun once more the test

**Comment by fabiocos** [comment]
please test

**Comment by slava77** [comment]
On 7/18/18 10:06 AM, Fabio Cossutti wrote:
> @Dr15Jones @slava77 I do not recall such a large number of DQM failures recently, one or two at most in recent times, just to have a final check let me rerun once more the test
> 

the number of changes often depends on the fractional volume of the full
release build in the tests.
The larger it is, the more changes can happen due to more possible
differences in the memory mapping

**Comment by fabiocos** [comment]
@slava77 @Dr15Jones as far as I can see, the 2 changes in 136.85 are those randomly appearing in recent times (I should open an issue to keep memory of them), but those in 136.788 are new to me. The differences are small, so it could be some memory reshuffling effect as Slava says?

**Comment by Dr15Jones** [comment]
@fabiocos the L1 tau results have no code connection to this pull request. Therefore it must be as Slava suggested, the memory addresses were changes (becuase I now do fewer calls to `new`) and the L1 code is sensitive to exactly where in memory it writes its values.

**Comment by Dr15Jones** [comment]
@fabiocos what do you want done to allow this pull request to be merged?

**Comment by fabiocos** [comment]
+1

**Pull request merged**
