### PR TITLE
Optimize SiStripMonitorTrack to perform less string operations.

### PR DESCRIPTION
**Pull request by dmitrijus**
Optimize SiStripMonitorTrack to perform less string operations.

https://hypernews.cern.ch/HyperNews/CMS/get/swDevelopment/3171.html

before: http://micius.web.cern.ch/micius/cgi-bin/igprof-navigator/sistrip_original/76
after: http://micius.web.cern.ch/micius/cgi-bin/igprof-navigator/sistrip_modified/80

Please review and test.

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
thanks @dmitrijus

**Comment by dmitrijus** [comment]
This was *originally* written for 7_4_X (#8266),
I will rebase it after the tests for 7_4_X pass.

**Pull request closed without merging**
