### PR TITLE
Trigger dqm validation

### PR DESCRIPTION
**Pull request by deguio**

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/13794	1f01946
- DQM auto sequence triggerValidation added ( Validation/Configuration/python/autoValidation.py  is the only file that triggers reco signature in this PR); 
    - also in this PR (the main feature in a sense) is 801330 workflow with reHLT workflow suitable for relvals and including DQM and validation sequences
- jenkins tests pass (compilation only)
- tested in 7_6_4 to see that the workflow runs: 
    - RECO in step3 runs OK (there is a warning in CSCHaloDataProducer:CSCHaloData about missing HLT; this is expected)
    - miniAOD in step5 runs OK without PAT-related warning; there are warnings from hltTauVal\* "unable to read L1 met collection l1extraParticles:MET" every event

**Comment by civanch** [comment]
+1

**Comment by hengne** [comment]
+1

**Comment by hengne** [comment]
hold

**Comment by hengne** [comment]
let's temporarily wait a little bit for some more tests and studies.

**Comment by hengne** [comment]
unhold

**Comment by hengne** [comment]
+1

**Comment by hengne** [comment]
things are understood, and this is a right approach to go.

**Comment by dmitrijus** [comment]
Is this still needed, in 76x? 
Please close the PR, @deguio

**Pull request closed without merging**
