### PR TITLE
SiPixelQuality : fix tagging of the stuckTBM channels

### PR DESCRIPTION
**Pull request by tocheng**
Hello,

  this PR is to fix the way to check whether the ROCs (in the same channel) are effected by stuckTBM in a given lumi section.

  The previous way is to tag the channel effected by stuckTBM so long **as at least one event** in the lumi section produces FEDerror25. But this way **overestimates** the stuckTBM channels because it ignores the cases where channels are effected by stuckTBM on the halfway of the lumi section, or the "flickers" where soft recoveries are triggered during the lumi section and manage/fail to rescue the channels in the rest events.
  The overestimation of the stuckTBM channels will lead to **underestimation** of the bad components used for **prompt reconstruction** (stuckTBM channels are expected to be tagged by FEDerror25 per-event, hence they are not included in the bad components for prompt reco)

   So now we turn to tag "stuckTBM" to channels producing FEDerror25 for **ALL events** in the lumi section (passing ALCARECO trigger bit). Although the bad components for the prompt reco may have overlaps with the channels producing FEDerror25 (per-event), we will not miss any bad components for track reconstruction :
https://github.com/cms-sw/cmssw/blob/master/RecoTracker/MeasurementDet/plugins/TkPixelMeasurementDet.cc#L153

The comparison between option2 and option1 can be found at
https://indico.cern.ch/event/688845/contributions/3022626/attachments/1658161/2655466/PixelQualityPCL_StuckTBM_Opt2_May29.pdf
I am not sure it is self-explained enough. Please let me know if anything is not clear.

### CODE REVIEW

**Comment by tocheng** [comment]
Hello, @tvami, @tsusa, @veszpv, this is something you want to follow.

**Comment by lpernie** [comment]
please test

**Comment by arunhep** [comment]
@tocheng do you have any local validation for this change?

**Comment by tocheng** [comment]
@arunhep The summary of the current release, a.k.a, option 1 is explained in the tracker DPG meeting at https://indico.cern.ch/event/688844/contributions/3009266/attachments/1651594/2641844/PixelCablingMapWebInterface_May17th_2018_TkDQM.pdf.

The comparison between option2 and option1 can be found at 
https://www.dropbox.com/s/qdidgh66yc3r5qh/PixelQualityPCL_StuckTBM_Opt2.pptx?dl=0
I am not sure it is self-explained enough. Please let me know if anything is not clear.

I will also give a report in the pixel offline meeting tomorrow
https://indico.cern.ch/event/688845/?showDate=all&showSession=8

**Comment by lpernie** [comment]
please test workflow 1001.2, 1040

**Comment by lpernie** [comment]
+1

**Comment by prebello** [comment]
+1

relval 136.8391 removed properly checked and test approved

**Comment by tocheng** [comment]
@prebello, @kpedro88, @fabozzi, @cmsbuild, @fabiocos, @davidlange6 could you please review it and eventually sign? Thanks.

**Comment by kpedro88** [comment]
+1

**Comment by fabiocos** [comment]
@tocheng @prebello why do you remove two test workflows, namely 136.8391 and 1040.1? How are they related with the main purpose of this PR?

**Comment by prebello** [comment]
Hi @fabiocos  , both are related to RunExpressPhy2017F therefore remove one and not other wouldn't be consistent. BTW both are not listed to be produced by PdmV either.
Why RunExpressPhy2017F is not needed anymore maybe @tocheng  can explain better, although I see  that he has removed steps['TIER0EXPSIPIXELCAL'] (used by it).  
Technically in face of relvals, this is the explanation. 
About the motivation to exclude them, maybe @tocheng  can give more details based on few SiPixelQuality deletion performed in this PR.

**Comment by tocheng** [comment]
Hello @fabiocos @prebello,
the workflows we have in the current release are 1001.2, 1040 using ZeroBias raw data,
and 10401.1 and 136.8391 using Express FEVT sample.
I would like to have them included in the matrix for jenkins test. Currently they are not.

But the Express FEVT samples will not be always available, it will be removed after sometime if I remember correctly. And I don't see any other relval workflows in either production or standard type use Express data as input.
So I think it would be good to remove them and it is enough to have two workflows 1040 and 1001.2 to test the SiPixelQuality ALCARECO/PCL using ZeroBias raw data.

So I take the chance of this PR to remove the workflows which are not good to be included in the jenkins test.
I suggest include 1040 and 1001.2 into the matrix for jenkins test.

Please let me know if any action is needed on my side to make this happen.

Thanks.

**Comment by fabiocos** [comment]
@tocheng sorry but having wfs that mimics the T0 express workflows is something that we do want, and the corresponding data are kept for this purpose (since 2011 as you may see).  We are having parallel discussion about this in different context with Tracker and DQM people for instance. So please remove that part from this PR. 

The short test matrix run in Jenkins tests already contains a T0 EXP-like workflow, 1001.0 We should likely add a 2018 version of it and review the content of the test matrix. But this is a different story.

**Comment by prebello** [comment]
please test workflow 136.8391, 1040.1

**Comment by prebello** [comment]
+1

as tests approved

**Comment by lpernie** [comment]
+1

**Comment by fabiocos** [comment]
+operations

the update to the StandardSequences looks consistent with the purpose of the PR

**Comment by fabiocos** [comment]
+1

**Pull request merged**
