### PR TITLE
Run3-alca193 Add DQM for HcalIterativePhiSymAlCaReco

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Add DQM for HcalIterativePhiSymAlCaReco

#### PR validation:

Use the runTheMatrix test workflows 

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by tvami** [comment]
resolves https://github.com/cms-sw/cmssw/issues/34777

**Comment by bsunanda** [comment]
@jfernan2 Can you sign off this PR?

**Comment by Dr15Jones** [comment]
Ping @cms-sw/dqm-l2

**Comment by jfernan2** [comment]
+1

**Comment by perrotta** [comment]
+operations

**Comment by perrotta** [comment]
+1

**Pull request merged**
