### PR TITLE
Attempt to remove LTO compilation warning

### LINKED ISSUE #38684: [LTO - SimCalorimetry/HGCalAssociatorProducers] Compiler warnings -Wodr in simulation category
Hello,

We have seen some compiler warnings of the type `-Wodr` in LTO_X IBs ([CMSSW_12_5_LTO_X_2022-07-07-1100](https://cmssdt.cern.ch/SDT/cgi-bin/showBuildLogs.py/el8_amd64_gcc10/www/thu/12.5.LTO-thu-11/CMSSW_12_5_LTO_X_2022-07-07-1100) and [CMSSW_12_5_LTO_X_2022-07-06-1100](https://cmssdt.cern.ch/SDT/cgi-bin/showBuildLogs.py/el8_amd64_gcc10/www/wed/12.5.LTO-wed-11/CMSSW_12_5_LTO_X_2022-07-06-1100), for example) in `SimCalorimetry/HGCalAssociatorProducers`. See sample stack trace:

```
>> Building edm plugin tmp/el8_amd64_gcc10/src/SimCalorimetry/HGCalAssociatorProducers/plugins/SimCalorimetryHGCalAssociatorProducersAuto/libSimCalorimetryHGCalAssociatorProducersAuto.so
/data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc10/external/gcc/10.3.0-84898dea653199466402e67d73657f10/bin/c++ -O2 -pthread -pipe -Werror=main -Werror=pointer-arith -Werror=overlength-strings -Wno-vla -Werror=overflow -std=c++1z -ftree-vectorize -Wstrict-overflow -Werror=array-bounds -Werror=format-contains-nul -Werror=type-limits -fvisibility-inlines-hidden -fno-math-errno --param vect-max-version-for-alias-checks=50 -Xassembler --compress-debug-sections -msse3 -felide-constructors -fmessage-length=0 -Wall -Wno-non-template-friend -Wno-long-long -Wreturn-type -Wextra -Wpessimizing-move -Wclass-memaccess -Wno-cast-function-type -Wno-unused-but-set-parameter -Wno-ignored-qualifiers -Wno-deprecated-copy -Wno-unused-parameter -Wunused -Wparentheses -Wno-deprecated -Werror=return-type -Werror=missing-braces -Werror=unused-value -Werror=unused-label -Werror=address -Werror=format -Werror=sign-compare -Werror=write-strings -Werror=delete-non-virtual-dtor -Werror=strict-aliasing -Werror=narrowing -Werror=unused-but-set-variable -Werror=reorder -Werror=unused-variable -Werror=conversion-null -Werror=return-local-addr -Wnon-virtual-dtor -Werror=switch -fdiagnostics-show-option -Wno-unused-local-typedefs -Wno-attributes -Wno-psabi -Wno-error=unused-variable -DBOOST_DISABLE_ASSERTS -flto -fipa-icf -flto-odr-type-merging -fno-fat-lto-objects -Wodr -shared -Wl,-E -Wl,-z,defs tmp/el8_amd64_gcc10/src/SimCalorimetry/HGCalAssociatorProducers/plugins/SimCalorimetryHGCalAssociatorProducersAuto/LCToCPAssociatorByEnergyScoreImpl.cc.o tmp/el8_amd64_gcc10/src/SimCalorimetry/HGCalAssociatorProducers/plugins/SimCalorimetryHGCalAssociatorProducersAuto/LCToCPAssociatorByEnergyScoreProducer.cc.o tmp/el8_amd64_gcc10/src/SimCalorimetry/HGCalAssociatorProducers/plugins/SimCalorimetryHGCalAssociatorProducersAuto/LCToCPAssociatorEDProducer.cc.o tmp/el8_amd64_gcc10/src/SimCalorimetry/HGCalAssociatorProducers/plugins/SimCalorimetryHGCalAssociatorProducersAuto/LCToSCAssociatorByEnergyScoreImpl.cc.o tmp/el8_amd64_gcc10/src/SimCalorimetry/HGCalAssociatorProducers/plugins/SimCalorimetryHGCalAssociatorProducersAuto/LCToSCAssociatorByEnergyScoreProducer.cc.o tmp/el8_amd64_gcc10/src/SimCalorimetry/HGCalAssociatorProducers/plugins/SimCalorimetryHGCalAssociatorProducersAuto/LCToSCAssociatorEDProducer.cc.o tmp/el8_amd64_gcc10/src/SimCalorimetry/HGCalAssociatorProducers/plugins/SimCalorimetryHGCalAssociatorProducersAuto/LCToSimTSAssociatorByEnergyScoreImpl.cc.o tmp/el8_amd64_gcc10/src/SimCalorimetry/HGCalAssociatorProducers/plugins/SimCalorimetryHGCalAssociatorProducersAuto/LCToSimTSAssociatorByEnergyScoreProducer.cc.o tmp/el8_amd64_gcc10/src/SimCalorimetry/HGCalAssociatorProducers/plugins/SimCalorimetryHGCalAssociatorProducersAuto/LCToSimTSAssociatorEDProducer.cc.o tmp/el8_amd64_gcc10/src/SimCalorimetry/HGCalAssociatorProducers/plugins/SimCalorimetryHGCalAssociatorProducersAuto/MCToCPAssociatorEDProducer.cc.o tmp/el8_amd64_gcc10/src/SimCalorimetry/HGCalAssociatorProducers/plugins/SimCalorimetryHGCalAssociatorProducersAuto/MultiClusterAssociatorByEnergyScoreImpl.cc.o tmp/el8_amd64_gcc10/src/SimCalorimetry/HGCalAssociatorProducers/plugins/SimCalorimetryHGCalAssociatorProducersAuto/MultiClusterAssociatorByEnergyScoreProducer.cc.o tmp/el8_amd64_gcc10/src/SimCalorimetry/HGCalAssociatorProducers/plugins/SimCalorimetryHGCalAssociatorProducersAuto/TSToSCAssociatorByEnergyScoreImpl.cc.o tmp/el8_amd64_gcc10/src/SimCalorimetry/HGCalAssociatorProducers/plugins/SimCalorimetryHGCalAssociatorProducersAuto/TSToSCAssociatorByEnergyScoreProducer.cc.o tmp/el8_amd64_gcc10/src/SimCalorimetry/HGCalAssociatorProducers/plugins/SimCalorimetryHGCalAssociatorProducersAuto/TSToSCAssociatorEDProducer.cc.o tmp/el8_amd64_gcc10/src/SimCalorimetry/HGCalAssociatorProducers/plugins/SimCalorimetryHGCalAssociatorProducersAuto/TSToSimTSAssociatorByEnergyScoreImpl.cc.o tmp/el8_amd64_gcc10/src/SimCalorimetry/HGCalAssociatorProducers/plugins/SimCalorimetryHGCalAssociatorProducersAuto/TSToSimTSAssociatorByEnergyScoreProducer.cc.o tmp/el8_amd64_gcc10/src/SimCalorimetry/HGCalAssociatorProducers/plugins/SimCalorimetryHGCalAssociatorProducersAuto/TSToSimTSAssociatorEDProducer.cc.o -o tmp/el8_amd64_gcc10/src/SimCalorimetry/HGCalAssociatorProducers/plugins/SimCalorimetryHGCalAssociatorProducersAuto/libSimCalorimetryHGCalAssociatorProducersAuto.so -Wl,-E -Wl,--hash-style=gnu -L/data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/9802c30fc48bdc09db9c7193cb951860/opt/cmssw/el8_amd64_gcc10/cms/cmssw/CMSSW_12_5_LTO_X_2022-07-07-2300/biglib/el8_amd64_gcc10 -L/data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/9802c30fc48bdc09db9c7193cb951860/opt/cmssw/el8_amd64_gcc10/cms/cmssw/CMSSW_12_5_LTO_X_2022-07-07-2300/lib/el8_amd64_gcc10 -L/data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/9802c30fc48bdc09db9c7193cb951860/opt/cmssw/el8_amd64_gcc10/cms/cmssw/CMSSW_12_5_LTO_X_2022-07-07-2300/external/el8_amd64_gcc10/lib -lRecoLocalCaloHGCalRecAlgos -lSimDataFormatsAssociations -lDataFormatsParticleFlowReco -lDataFormatsEgammaCandidates -lDataFormatsMuonReco -lGeometryHGCalGeometry -lDataFormatsRecoCandidate -lTrackingToolsGeomPropagators -lDataFormatsEgammaReco -lDataFormatsGsfTrackReco -lDataFormatsHGCalReco -lDataFormatsVertexReco -lSimDataFormatsTrackingAnalysis -lTrackingToolsTrajectoryState -lDataFormatsTrackReco -lDataFormatsGEMRecHit -lDataFormatsTrackCandidate -lDataFormatsTrackerRecHit2D -lDataFormatsCSCRecHit -lDataFormatsDTRecHit -lDataFormatsFTLRecHit -lDataFormatsTrajectorySeed -lGeometryHcalTowerAlgo -lDataFormatsTrackingRecHit -lGeometryCaloTopology -lDataFormatsL1TrackTrigger -lGeometryHcalCommonData -lDataFormatsTrackerCommon -lDetectorDescriptionRegressionTest -lGeometryCaloGeometry -lGeometryCommonTopologies -lSimDataFormatsCaloAnalysis -lCondFormatsAlignment -lDataFormatsBeamSpot -lDataFormatsCaloTowers -lDataFormatsEcalRecHit -lDataFormatsGeometryCommonDetAlgo -lDataFormatsHepMCCandidate -lDataFormatsSiStripCluster -lDetectorDescriptionParser -lGeometryHGCalCommonData -lGeometryRecords -lTrackingToolsAnalyticalJacobians -lCondFormatsAlignmentRecord -lDataFormatsCandidate -lDataFormatsDTDigi -lDataFormatsEcalDigi -lDataFormatsGeometrySurface -lDataFormatsHGCRecHit -lDataFormatsTrajectoryState -lDetectorDescriptionCore -lDetectorDescriptionDDCMS -lMagneticFieldEngine -lCondFormatsGeometryObjects -lDataFormatsCLHEP -lDataFormatsCaloRecHit -lDataFormatsEcalDetId -lDataFormatsForwardDetId -lDataFormatsGeometryVector -lDataFormatsHcalDetId -lDataFormatsL1GlobalTrigger -lDataFormatsMuonDetId -lDataFormatsPhase2TrackerCluster -lDataFormatsSiPixelDetId -lDataFormatsSiStripDetId -lFWCoreFramework -lSimDataFormatsCaloHit -lSimDataFormatsTrack -lSimDataFormatsVertex -lDataFormatsDetId -lDataFormatsFEDRawData -lDataFormatsL1GlobalMuonTrigger -lDataFormatsMath -lDataFormatsPhase2TrackerDigi -lDataFormatsScouting -lDataFormatsSiPixelCluster -lDataFormatsSiStripDigi -lFWCoreCommon -lFWCoreServiceRegistry -lSimDataFormatsGeneratorProducts -lDataFormatsCommon -lFWCoreParameterSet -lFWCoreMessageLogger -lDataFormatsProvenance -lFWCorePluginManager -lFWCoreReflection -lTrackingToolsTrajectoryParametrization -lCondFormatsSerialization -lFWCoreConcurrency -lFWCoreUtilities -lFWCoreVersion -lSimDataFormatsEncodedEventId -lUtilitiesXerces -lDDAlign -lDDCond -lDDCore -lDDParsers -lMinuit -lGpad -lGraf -lPhysics -lHist -lMatrix -lGenVector -lMathMore -lTree -lNet -lGeom -lThread -lMathCore -lRIO -lSmatrix -lboost_serialization -lCore -lboost_thread -lboost_date_time -lCLHEP -lHepMCfio -lHepMC -lpcre -lbz2 -lgsl -luuid -ltbb -lxerces-c -llzma -lz -lfmt -lHepMC3 -lHepMC3search -lcms-md5 -lopenblas -lcrypt -ldl -lrt -lstdc++fs -ltinyxml2
  /data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/9802c30fc48bdc09db9c7193cb951860/opt/cmssw/el8_amd64_gcc10/cms/cmssw/CMSSW_12_5_LTO_X_2022-07-07-2300/src/SimCalorimetry/HGCalAssociatorProducers/plugins/LCToCPAssociatorByEnergyScoreImpl.h:44:10: warning: type 'struct caloParticleOnLayer' violates the C++ One Definition Rule [-Wodr]
    44 |   struct caloParticleOnLayer {
      |          ^
/data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/9802c30fc48bdc09db9c7193cb951860/opt/cmssw/el8_amd64_gcc10/cms/cmssw/CMSSW_12_5_LTO_X_2022-07-07-2300/src/SimCalorimetry/HGCalAssociatorProducers/plugins/MultiClusterAssociatorByEnergyScoreImpl.h:35:10: note: a different type is defined in another translation unit
   35 |   struct caloParticleOnLayer {
      |          ^
/data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/9802c30fc48bdc09db9c7193cb951860/opt/cmssw/el8_amd64_gcc10/cms/cmssw/CMSSW_12_5_LTO_X_2022-07-07-2300/src/SimCalorimetry/HGCalAssociatorProducers/plugins/LCToCPAssociatorByEnergyScoreImpl.h:48:54: note: the first difference of corresponding definitions is field 'layerClusterIdToEnergyAndScore'
   48 |     std::unordered_map<int, std::pair<float, float>> layerClusterIdToEnergyAndScore;
      |                                                      ^
/data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/9802c30fc48bdc09db9c7193cb951860/opt/cmssw/el8_amd64_gcc10/cms/cmssw/CMSSW_12_5_LTO_X_2022-07-07-2300/src/SimCalorimetry/HGCalAssociatorProducers/plugins/MultiClusterAssociatorByEnergyScoreImpl.h:39:54: note: a field with different name is defined in another translation unit
   39 |     std::unordered_map<int, std::pair<float, float>> multiClusterIdToEnergyAndScore;
      |                                                      ^
  /data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/9802c30fc48bdc09db9c7193cb951860/opt/cmssw/el8_amd64_gcc10/cms/cmssw/CMSSW_12_5_LTO_X_2022-07-07-2300/src/SimCalorimetry/HGCalAssociatorProducers/plugins/LCToSCAssociatorByEnergyScoreImpl.h:42:10: warning: type 'struct simClusterOnLayer' violates the C++ One Definition Rule [-Wodr]
    42 |   struct simClusterOnLayer {
      |          ^
/data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/9802c30fc48bdc09db9c7193cb951860/opt/cmssw/el8_amd64_gcc10/cms/cmssw/CMSSW_12_5_LTO_X_2022-07-07-2300/src/SimCalorimetry/HGCalAssociatorProducers/plugins/TSToSCAssociatorByEnergyScoreImpl.h:28:10: note: a different type is defined in another translation unit
   28 |   struct simClusterOnLayer {
      |          ^
/data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/9802c30fc48bdc09db9c7193cb951860/opt/cmssw/el8_amd64_gcc10/cms/cmssw/CMSSW_12_5_LTO_X_2022-07-07-2300/src/SimCalorimetry/HGCalAssociatorProducers/plugins/LCToSCAssociatorByEnergyScoreImpl.h:46:54: note: the first difference of corresponding definitions is field 'layerClusterIdToEnergyAndScore'
   46 |     std::unordered_map<int, std::pair<float, float>> layerClusterIdToEnergyAndScore;
      |                                                      ^
/data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/9802c30fc48bdc09db9c7193cb951860/opt/cmssw/el8_amd64_gcc10/cms/cmssw/CMSSW_12_5_LTO_X_2022-07-07-2300/src/SimCalorimetry/HGCalAssociatorProducers/plugins/TSToSCAssociatorByEnergyScoreImpl.h:32:54: note: a field with different name is defined in another translation unit
   32 |     std::unordered_map<int, std::pair<float, float>> tracksterIdToEnergyAndScore;
      |                                                      ^
Leaving library rule at src/SimCalorimetry/HGCalAssociatorProducers/plugins
```

This warning is also shown in other packages, such as reported in https://github.com/cms-sw/cmssw/issues/38650 and https://github.com/cms-sw/cmssw/issues/38656. It seems there are some elements defined multiple times within the same namespace leading to violation of the C++ One Definition Rule. Could you please have a look at it?

Many thanks,
Andrea.

### PR DESCRIPTION
**Pull request by civanch**
#### PR description:
Attempt to fix #38684  if will work, other SIM LTO warnings will be fixed in the same way.

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by smuzaffar** [comment]
please test for CMSSW_12_5_LTO_X

lets test it for LTO build too

**Comment by rovere** [comment]
Thanks, @civanch for this.
I guess it will work. There's work ongoing to restructure a bit all the associators and it is not excluded that some of them will be dropped in the near future. Nevertheless, if the proposed solution works, I'm fine having that integrated into the release.

**Comment by smuzaffar** [comment]
thanks @civanch , this indeed has [fixed](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-21154b/26937/build-logs/SimCalorimetry/HGCalAssociatorProducers/log.html) the one of the warning coming from `SimCalorimetry/HGCalAssociatorProducers` package

**Comment by srimanob** [comment]
Thanks @civanch 
Is the failure shown in DQM expected, from this technical fix?

**Comment by smuzaffar** [comment]
@srimanob , no the dqm failure in https://github.com/cms-sw/cmssw/pull/39118#issuecomment-1221076272 are due to comparing LTO relvals with non-LTO baseline

**Comment by srimanob** [comment]
+Upgrade

Technical PR. 

Thanks @smuzaffar

**Comment by civanch** [comment]
+1

**Comment by perrotta** [comment]
`struct caloParticleOnLayer` was defined absolutely identically in
- _SimCalorimetry/HGCalAssociatorProducers/plugins/LCToCPAssociatorByEnergyScoreImpl.h_ (renamed in this PR)
- _SimCalorimetry/HGCalAssociatorProducers/plugins/MultiClusterAssociatorByEnergyScoreImpl.h_
- _Validation/HGCalValidation/interface/HGVHistoProducerAlgo.h_

This PR doesn't fix the duplication with the definition in Validation/HGCalValidation: but probably it is not needed as long as Simulation and Validation are not run in the same step.

On the other hand, I wonder why it was not chosen as a fix to define that (or those...) struct(s) in one single header file, and include it in the other ones. It would look to me as the more intuitive fix, and it does not require any copy-paste of the same structure in different packages, with all possible errors and mistakes associated with it in the long run. What was wrong with such a possible fix?

**Comment by civanch** [comment]
@perrota, I agree with you that the current code seems to be heavy and likely include duplication. Rethinking on sub-library optimization requires much more efforts than LTO warning fix. Optimal would be to create a new issue but merge this PR.

**Comment by perrotta** [comment]
> @Perrota, I agree with you that the current code seems to be heavy and likely include duplication. Rethinking on sub-library optimization requires much more efforts than LTO warning fix. Optimal would be to create a new issue but merge this PR.

Uhm... Looking at the code, I suspect that after this fix the same issue could reappear with `struct detIdInfoInCluster`, also defined identically in the three files above as well as in several other ones. I still believe that extracting all those structures in a single header file, and including that header wherever needed can be a more stable solution, and even simpler than going file by file to rename those structures one by one...

**Comment by civanch** [comment]
@perrotta , I am not sure why LTO complains and not sure if the same header included in several plugin modules will resolve the warning.

**Comment by smuzaffar** [comment]
@civanch @perrotta , LTO complains if it find more classes with same name but different functions/data members. For `caloParticleOnLayer` lto complained as these classes/struct have different data members
```
std::unordered_map<int, std::pair<float, float>> layerClusterIdToEnergyAndScore;
```
vs
```
std::unordered_map<int, std::pair<float, float>> multiClusterIdToEnergyAndScore;
```

For `detIdInfoInCluster` LTo does not complain as all these instances of this struct are identical

**Comment by perrotta** [comment]
Ah, ok: thank you @smuzaffar 
Therefore, if I understand it correctly, the fix proposed in this PR by @civanch is actually better than what I suggested [above](https://github.com/cms-sw/cmssw/pull/39118#issuecomment-1222046142) (which was actually wrong, given the different data members that I overlooked)

**Comment by smuzaffar** [comment]
@civanch , can you provide a fix for `struct simClusterOnLayer` too? 
- https://github.com/cms-sw/cmssw/blob/master/SimCalorimetry/HGCalAssociatorProducers/plugins/LCToSCAssociatorByEnergyScoreImpl.h#L42-L47
- https://github.com/cms-sw/cmssw/blob/master/SimCalorimetry/HGCalAssociatorProducers/plugins/TSToSCAssociatorByEnergyScoreImpl.h#L28-L33

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
please test for CMSSW_12_5_LTO_X

**Comment by perrotta** [comment]
Thank you @civanch . I think that both you and @srimanob can re-sign now

**Comment by srimanob** [comment]
+Upgrade

Re-sign.

**Comment by civanch** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
