### PR TITLE
[DB-DQM] [CLANG] Fix warnings reported by llvm16 in CLANG IBs

### PR DESCRIPTION
**Pull request by smuzaffar**
Fixed set but unused warnings from clang-16 in CLANG IBs

### CODE REVIEW

**Comment by francescobrivio** [comment]
@cmsbuild please test

 - even though the "FakeBeamMonitor" is currently not used anywhere

**Comment by tvami** [comment]
@cmsbuild , please test for CMSSW_13_1_CLANG_X
 * we should test it for CLANG IB too

**Comment by smuzaffar** [comment]
> @cmsbuild , please test for CMSSW_13_1_CLANG_X
> 
>     * we should test it for CLANG IB too

though there is no need to test against clang IB but if you really want then please wait for 13.2.CLANG.X IB (tonight after 23h00)

**Comment by tvami** [comment]
@cmsbuild , please test for CMSSW_13_2_CLANG_X

**Comment by tvami** [comment]
+db

**Comment by emanueleusai** [comment]
+1

**Comment by rappoccio** [comment]
+1

**Pull request merged**
