### PR TITLE
Replace call to Modifier.isChosen() with toModify() in rpcChamberMasker_cff

### PR DESCRIPTION
**Pull request by makortel**
Title says it all. I'm assuming these customize functions are still relevant (if not, they could be removed).

Tested in 10_4_0_pre4, no changes expected.

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
@kpedro88 FYI (this PR touches phase2 customization function)

**Comment by kpedro88** [comment]
@makortel thanks; does it actually work to call a customization function on the process using `toModify`?
@battibass FYI, I think you introduced this code

**Comment by kpedro88** [comment]
assign upgrade

**Comment by makortel** [comment]
@kpedro88 It works (at least currently) if one passes the `process` as the object-to-be-modified to the `toModify()`.

**Comment by civanch** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade

**Comment by fabiocos** [comment]
+1

**Pull request merged**
