### PR TITLE
Updates to NANOAOD workflows in the matrix

### PR DESCRIPTION
**Pull request by fabozzi**
These updates to NANOAOD workflows reflect the last setup after submission tests to prod infrastructure.

- removed NANOMERGE task from the workflows. The merge is handled now by computing.
- the NANOEDM task produces nano-edm files and a dataset declared as NANOAOD(SIM). This requires a change in ConfigBuilder to setup output module according to eventcontent (and cloning NANOAOD eventcontent into an identical NANOEDMAOD)
- introduced a NANOAOD workflow on data

### CODE REVIEW

**Comment by fabozzi** [comment]
FYI: @arizzi @gpetruc

**Comment by fabozzi** [comment]
please test workflow 136.7722,1329.1

**Comment by fabozzi** [comment]
+1

**Comment by davidlange6** [comment]
merge

**Comment by arizzi** [comment]
should we backport in 94X too?

**Comment by fabozzi** [comment]
@arizzi 
I can make a backport to 94x

**Pull request merged**
