### PR TITLE
Revert decrease of precision introduced in ea3f693d

### PR DESCRIPTION
**Pull request by maxgalli**
The decrease of precision for shower shape variables, introduced in [this PR](https://github.com/cms-sw/cmssw/pull/36526), seems to introduce unwanted features in the shapes.
A comparison of Run2 samples with precision 8 and 10 can be found at the following links:
- precision 10, no unwanted features ([S4 plot](https://gallim.web.cern.ch/gallim/plots/Hgg/NormFlowsCorrections/From231027/preprocess/Run2UL17/probe_s4_eb_pipe1_test_transformed_back_data.pdf))
- precision 8, unwanted features in the tail ([S4 plot](https://gallim.web.cern.ch/gallim/plots/Hgg/NormFlowsCorrections/From231027/preprocess/Run2UL17_lowprecision/probe_s4_eb_pipe1_test_transformed_back_data.pdf))
- precision 10, no unwanted features ([R9 plot](https://gallim.web.cern.ch/gallim/plots/Hgg/NormFlowsCorrections/From231027/preprocess/Run2UL17/probe_r9_eb_pipe1_test_transformed_back_data.pdf))
- precision 8, unwanted features in the tail ([R9 plot](https://gallim.web.cern.ch/gallim/plots/Hgg/NormFlowsCorrections/From231027/preprocess/Run2UL17_lowprecision/probe_r9_eb_pipe1_test_transformed_back_data.pdf))

### CODE REVIEW

**Comment by simonepigazzini** [comment]
enable nano

**Comment by simonepigazzini** [comment]
please test

**Comment by simonepigazzini** [comment]
+1

**Comment by antoniovilela** [comment]
+1

**Comment by JaLuka98** [comment]
> Wouldn't another solution here be to bin the relevant variables in powers of two? e.g. if `s4` were binned with 128 bins between 0-1 I would expect the bumps to go away.

Hi @nsmith-, nice idea, although I am not completely following. To what extent is this a "solution"? People would like to work with the variables as inputs to MVA algorithms, which usually benefit from smooth input distributions (continuous, differentiable). We had cases of almost catastrophic failure as especially density estimation methods seem to have problems with such "pathological" cases. Rebinning might make bumps go away but it does not help for training a model, right? Or did I misunderstand your suggestion?

**Comment by davidlange6** [comment]
in either case, variables have a finite precision, so nothing is continuous if you bin finely enough.... (eg, use more bins, you will see the same effect in the "correct" plots)

**Comment by maxgalli** [comment]
> Wouldn't another solution here be to bin the relevant variables in powers of two? e.g. if `s4` were binned with 128 bins between 0-1 I would expect the bumps to go away.

Hi Nick, thanks. Adding to what @JaLuka98 already correctly said: the binning used in the plots is just a way to show the difference in behaviour between Run2 (precision 10, where we did not see any problem with the training) and Run3 (where the precision was decreased to 8). We already saw that if we choose a finer binning the bumps "go away" (as one would expect), but that does not solve the underlying problem unfortunately.
Concerning the reason why this is a problem for the flows, I have hypotheses but no definitive answers. I saw in other trainings that the flows are not particularly good at simulating "deltas" (see for instance the peak at 0 in the isolation variables, which has to be smeared in preprocessing for the flow to be able to learn it) and by decreasing the precision we are sort of "making more deltas" in the distribution, so maybe that's the reason why the performance decreases.

**Pull request merged**
