### PR TITLE
Added class versioning for tau IP update

### PR DESCRIPTION
**Pull request by andrewj314**
I used "scram build updateclassversion" to generate a new classes_def_3.xml.generated file, which I copied to classes_def_3.xml

### CODE REVIEW

**Comment by slava77** [comment]
AJ, it seems to me that what you committed is not what was intended
(only *generated file appears).
Also, this will likely break #9160 . Could you make an update in cms-tau-pog:TauIPUpdates_v3 branch instead?

**Comment by andrewj314** [comment]
Hi Slava,

Sorry about that. I'm on branch TauIPUpdates_v3 now, and I successfully
updated the class version in DataFormats/TauReco/src/classes_def_3.xml. For
some reason, git is not tracking this file. After I modified it, it didn't
show up as modified when I ran git status, and running git add <path to
file>, nothing changed. I'm googling around but I think I'm stuck on this
one - do you know how to get git to recognize that I've changed a file so I
can add it to my staging area?

Thanks!
AJ

**Comment by slava77** [comment]
Hi AJ,

Specific to v3 branch, https://github.com/cms-tau-pog/cmssw/blob/TauIPUpdates_v3/DataFormats/TauReco/src/classes_def_3.xml I see that branch is older than what's in the latest release
as well as in the IB tag that you started from
https://github.com/cms-sw/cmssw/blob/CMSSW_7_5_X/DataFormats/TauReco/src/classes_def_3.xml

Could it be that when you were merging TauIPUpdates_v3 something went off?

**Comment by andrewj314** [comment]
Hmm, I think my workflow may be incorrect. I've been following the
guidelines laid out by the tau POG here:

https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuidePFTauID#Guidelines_for_developing_the_ta

So for every fix, I check out a new branch, develop in that branch, and
submit it as a PR to the cms-tau-pog repository.
In my attempt to return to TauIPUpdates_v3, I noticed that git clone put
the entire repository in my release area, which takes several hours to
compile and which I assume is the wrong thing to do. Simply doing "git
checkout TauIPUpdates_v3" didn't work as git was unable to find the branch.
All I could think to do was "git branch TauIPUpdates_v3", creating a new
branch, and then switch to that, but that doesn't seem like the right thing
to do either. I'm not sure where I'm supposed to merge the existing
TauIPUpdates_v3 branch to/from.

Thanks so much for your help with this!
AJ

**Comment by slava77** [comment]
something like this should work, making it the least invasive to the original PR.
You will need to test code changes in a separate area though.
```
... doing this as early as in 750pre5 would make sense
git cms-addpkg RecoTauTag/RecoTau
git cms-addpkg RecoTauTag/Configuration
git remote add tau-pog git@github.com:cms-tau-pog/cmssw.git
git fetch tau-pog TauIPUpdates_v3:TauIPUpdates_v3
git checkout TauIPUpdates_v3
.. edit, commit
.. don't do git cms-check-deps
git push tau-pog TauIPUpdates_v3
```

A more kosher way is to rebase the v3 branch to an existing release
```
... again, say, in 750pre6
git cms-addpkg RecoTauTag/RecoTau
git cms-addpkg RecoTauTag/Configuration
git remote add tau-pog git@github.com:cms-tau-pog/cmssw.git
git fetch tau-pog TauIPUpdates_v3:TauIPUpdates_v3
git rebase CMSSW_7_5_0_pre6 TauIPUpdates_v3
.. edit edit
git cms-checkdeps -a
scram b
test
git commit
git push tau-pog TauIPUpdates_v3:TauIPUpdates_v3
.. the last one may need a --force

```

**Comment by slava77** [comment]
-1
(as discussed in this thread, the current change is not what is expected; the resolution will come either through an update of #9160 or with a new change including what was in #9160 )

**Pull request closed without merging**
