### PR TITLE
Timing, Laser and Hot cell quality plots adjustments [12_5_X]

### PR DESCRIPTION
**Pull request by abhih1**
#### PR description:

This PR does the following in ECAL DQM plots:
 1. Changes the threshold in Timing quality summary to reduce the false positives in Ecal Endcaps
 2. Changes the amplitude threshold in laser quality for the forward region of Ecal Endcaps
 3. Disables the condition for setting entire FED to RED in Hot Cell quality as it's creating false alarms in the presence of single hot towers.
 
#### PR validation:
Validated by running the standard online Ecal DQM configuration and checking the output on a test DQM GUI. 

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

This is a backport of master PR: https://github.com/cms-sw/cmssw/pull/39161. Backport is done to have the changes available in 12_5_X which will be used next in production.
Backport to 12_4_X: https://github.com/cms-sw/cmssw/pull/39162

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
backport of https://github.com/cms-sw/cmssw/pull/39161

**Comment by emanueleusai** [comment]
+1

- differences in Ecal Endcap Timing DQM plots as expected

**Comment by perrotta** [comment]
+1

**Pull request merged**
