### PR TITLE
Update JetID Functor to new recommendations

### PR DESCRIPTION
**Pull request by gkasieczka**
Current JetID recommendations are available at: [1]

This PR brings the PFJetIDSelectionFunctor up to date with them.

Verified on ~1k jets: all jets for which the JetID changes are in 2.7 < abs(eta) <= 3.0 and the new JetID 
agrees with the requirements in the table.

There are still a few places in DQM where the old RUNIISTARTUP version is used (see [2]). Who is responsible to update these? Or can I just go ahead?

[1] https://twiki.cern.ch/twiki/bin/view/CMS/JetID13TeVRun2016
[2] https://github.com/cms-sw/cmssw/search?utf8=%E2%9C%93&q=RUNIISTARTUP

### CODE REVIEW

**Comment by slava77** [comment]
On 2/7/17 1:58 AM, gkasieczka wrote:
> There are still a few places in DQM where the old RUNIISTARTUP version
> is used (see [2]). Who is responsible to update these? Or can I just go
> ahead?

If you know what to change, please change.
Thank you.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by gkasieczka** [comment]
Also updated the DQM uses of JetID now.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by dmitrijus** [comment]
+1

**Comment by monttj** [comment]
+1
thank you for the update.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
