### PR TITLE
DQM: Syncing MEData with DQMNet MEData before asserting

### PR DESCRIPTION
**Pull request by andrius-k**
#### PR description:

Syncing MEData with DQMNet MEData before asserting.

#### PR validation:

PR was validated locally.

### CODE REVIEW

**Comment by andrius-k** [comment]
please test

**Comment by silviodonato** [comment]
Kind reminder @andrius-k @jfernan2 @kmaeshima @fioriNTU @schneiml (this is a one-line change)

**Comment by jfernan2** [comment]
+1

**Comment by schneiml** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
