### PR TITLE
Introduce remaining 11_0_X global tags

### PR DESCRIPTION
**Pull request by christopheralanwest**
#### PR description:

This PR introduces the 11_0_X global tags that have not yet been migrated to 11_0_X, aside from frozen GTs. Some cleanup is also performed. The changes vary from queue to queue but involve:

- removal of obsolete pixel tags [1]
- introduction of a labeled SiPixelLorentzAngleRcd tag for Phase-I MC that with simplify queue maintenance [2] 
- Replace a PF calibration tag with a tag that has the same payload but different tag synchronization. The existing tag had wrong synchronization assigned.

None of these changes will have any impact on any reconstructed quantities but we would like to implement these purely technical changes all at once rather than mixing them with changes that involve physics content.

We also renamed the "mc2017_design_IdealBS" GT to remove the "_IdealBS" string as there is no other "mc2017_design" GT. This is purely a renaming, with no change in content.

[1] https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/4159/1/1.html
[2] https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/4168.html

Diffs with respect to current autoCond:
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_dataRun2_v17/110X_dataRun2_v1 
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_dataRun2_PromptLike_HEfail_v9/110X_dataRun2_PromptLike_HEfail_v1 
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_dataRun2_PromptLike_HI_v10/110X_dataRun2_PromptLike_HI_v1  
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_dataRun2_PromptLike_v10/110X_dataRun2_PromptLike_v1 
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_dataRun2_relval_v16/110X_dataRun2_relval_v1  
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_mc2017_design_IdealBS_v5/110X_mc2017_design_v1  
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_mc2017_realistic_v7/110X_mc2017_realistic_v1  
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_mc2017cosmics_realistic_deco_v2/110X_mc2017cosmics_realistic_deco_v1  
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_mc2017cosmics_realistic_peak_v2/110X_mc2017cosmics_realistic_peak_v1  
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_mcRun1_HeavyIon_v3/110X_mcRun1_HeavyIon_v1  
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_mcRun1_design_v3/110X_mcRun1_design_v1  
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_mcRun1_pA_v3/110X_mcRun1_pA_v1  
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_mcRun1_realistic_v3/110X_mcRun1_realistic_v1  
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_mcRun2_HeavyIon_v4/110X_mcRun2_HeavyIon_v1  
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_mcRun2_asymptotic_v5/110X_mcRun2_asymptotic_v1  
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_mcRun2_asymptotic_l1stage1_Queue/110X_mcRun2_asymptotic_l1stage1_v1   
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_mcRun2_design_v5/110X_mcRun2_design_v1  
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_mcRun2_pA_v4/110X_mcRun2_pA_v1  
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_mcRun2_startup_v4/110X_mcRun2_startup_v1  
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_mcRun2cosmics_startup_deco_v2/110X_mcRun2cosmics_startup_deco_v1 
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_upgrade2018_design_v5/110X_upgrade2018_design_v1 
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_upgrade2018_realistic_HEfail_v6/110X_upgrade2018_realistic_HEfail_v1  
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_upgrade2018_realistic_HI_v4/110X_upgrade2018_realistic_HI_v1  
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_upgrade2018_realistic_v6/110X_upgrade2018_realistic_v1  
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_upgrade2018cosmics_realistic_deco_v3/110X_upgrade2018cosmics_realistic_deco_v1  
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/106X_upgrade2018cosmics_realistic_peak_v3/110X_upgrade2018cosmics_realistic_peak_v1 

#### PR validation:

`runTheMatrix.py -l limited -i all --ibeos`

#### if this PR is a backport please specify the original PR:

This PR should not be backported.

### CODE REVIEW

**Comment by christopheralanwest** [comment]
please test

**Comment by christopheralanwest** [comment]
+1

As expected, there are no changes in any RECO quantity in the comparison tests. Even though this PR does not change any reconstructed quantity, I prefer to keep autoCond synchronized with the contents of the GT queues.

**Comment by fabiocos** [comment]
there should be no real conflict with #27341 as far as I can see

**Comment by fabiocos** [comment]
+1

**Pull request merged**
