### PR TITLE
Branch HLT menu for 50ns

### PR DESCRIPTION
**Pull request by perrotta**
- HLT config fix for TrackerTopologyEP (formerly in #7630)
- Higgs PAG Diphoton path replacements for the signal triggers 34/18_Mass95 and 44/28, CMSHLT-199, in master table
- Branch a HLT menu for the 50 ns runs (still quite preliminary)

### CODE REVIEW

**Comment by fwyzard** [comment]
@perrotta , starting from CMSSW_7_4_0_pre7, for the 50ns menu you should load a different customisation function:

```
from SLHCUpgradeSimulations.Configuration.postLS1Customs import customisePostLS1
process = customisePostLS1(process)
```

should become

```
from SLHCUpgradeSimulations.Configuration.postLS1Customs import customisePostLS1_50ns
process = customisePostLS1_50ns(process)
```

Similarly, the HI menu should use `customisePostLS1_Hi` .

.A

**Comment by Martin-Grunewald** [comment]
@fwyzard 
For now these do the same as the std. PostLS1, so I assume this is to be prepared
when the 50ns/HI paths actually do use a different L1 and then the specific PostLS1
customs are changed to load that internally, right?

**Comment by fwyzard** [comment]
Hi Martin,
the customisations are already somewhat different: the digitisation step uses different parameters, and the L1 emulator is different.
In particular, `customisePostLS1_50ns(process)` should use the Legacy emulator in place of the Stage 1 emulator.

However, the L1 menu itself is set to the 25ns v2 menu for all cases, as the HLT is not ready for the dedicated menus yet.
As soon as the 50ns HLT menu is compliant with the 50ns v0 L1 menu, we can switch to it in the customisation.

Ditto for the HI menu.

.A

**Comment by Martin-Grunewald** [comment]
@fwyzard 
OK, specific customisations are now used...

**Comment by Martin-Grunewald** [comment]
please test

**Comment by perrotta** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by diguida** [comment]
+1
This is a partial back-port of #7916

**Comment by davidlange6** [comment]
+1 
(I confirmed no changes seen in our 25202 test as expected from the ORP)

**Pull request merged**
