### PR TITLE
Update of HLT menus (91X)

### PR DESCRIPTION
**Pull request by silviodonato**
Update of HLT menus. 
Sync with /dev/CMSSW_9_0_1/HLT/V28.

### CODE REVIEW

**Comment by silviodonato** [comment]
please test

**Comment by Martin-Grunewald** [comment]
What IB is this based on?

**Comment by silviodonato** [comment]
hold

**Comment by silviodonato** [comment]
It's based on CMSSW_9_1_X_2017-04-24-1100
(I've found an error in hltIntegrationTests)

**Comment by silviodonato** [comment]
unhold

**Comment by silviodonato** [comment]
please abort

**Comment by silviodonato** [comment]
please test

**Comment by silviodonato** [comment]
+1

**Comment by silviodonato** [comment]
Updated to /dev/CMSSW_9_0_1/HLT/V29 and ready to be merged.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
