### PR TITLE
backport CSCCLCTPreTriggerDigi to 94X for UL

### PR DESCRIPTION
**Pull request by srimanob**
As discussion in 
https://hypernews.cern.ch/HyperNews/CMS/get/edmFramework/3854.html

This is a PR in case we would like to make a backport.

The local test run fine, FEVTDEBUGHLT can be stored at the HLT step. Reco+Validation+DQM steps run fine.

@dildick @ptcox  Is this backport OK?
@fabiocos In case, we will need another 9_4X to allow HLT validation to happen.
@franzoni @pgunnell @prebello @zhenhu

### CODE REVIEW

**Comment by ptcox** [comment]
Sven is the expert so you need his OK for this. But I don't think it interferes in any way with other CSC code.

**Comment by Dr15Jones** [comment]
please test

**Comment by dildick** [comment]
@srimanob CSCCLCTPreTriggerDigi is a type of digi that is used only to analyze 3-layer coincidences and to help understand the finer details of pre-trigger formation in CSCs. It is not used by any CMSSW module in the standard simulation-reconstuction-validation sequence. So this is fine by me. @tahuang1991 FYI

**Comment by fabiocos** [comment]
please test

**Comment by srimanob** [comment]
@dildick 

This module is used in validation step in normal validation sequence used by PdmV, without it I found

> ----- Begin Fatal Exception 10-Mar-2019 08:17:15 CET-----------------------
> An exception of category 'ProductNotFound' occurred while
>    [0] Processing  Event run: 1 lumi: 1 event: 3 stream: 2
>    [1] Calling method for module CSCDigiValidation/'cscDigiValidation'
> Exception Message:
> Principal::getByToken: Found zero products matching all criteria
> Looking for type: MuonDigiCollection<CSCDetId,CSCALCTDigi>
> Looking for module label: simCscTriggerPrimitiveDigis
> Looking for productInstanceName: 

so we need this backport.

**Comment by srimanob** [comment]
@civanch , @mdhildreth Could you please review? We will need this to allow validation in HLT step to happen. See above discussion or
https://hypernews.cern.ch/HyperNews/CMS/get/edmFramework/3854.html
https://hypernews.cern.ch/HyperNews/CMS/get/comp-ops/4413/1/2/1/1/1/1/1.html

Thanks.

**Comment by civanch** [comment]
+1

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
hold

under test in dedicated build

**Comment by fabiocos** [comment]
@srimanob this is now in #26399

**Comment by fabiocos** [comment]
@srimanob this may be closed now

**Comment by srimanob** [comment]
The PR can be closed, as it is merged under https://github.com/cms-sw/cmssw/pull/26399

**Pull request closed without merging**
