### PR TITLE
L1T offline DQM - Run L1T emulator sequences before the DQM modules

### PR DESCRIPTION
**Pull request by thomreis**
The L1T emulators should run before the offline L1T DQM modules that use them.
This PR places the required sequences in front of the modules.

### CODE REVIEW

**Comment by thomreis** [comment]
WFs with eras that are not "stage2L1Trigger" are crashing because the cfi that defines the module is loaded behind an stage2L1Trigger.isChosen() only.

**Comment by thomreis** [comment]
please test

**Comment by thomreis** [comment]
+1

**Comment by andrius-k** [comment]
+1

**Comment by thomreis** [comment]
Hi @fabiocos 
please merge this before 10_3 closes.

**Comment by fabiocos** [comment]
@thomreis @andrius-k I have verified that this PR solves the original problem. I just used wf 136.891 dropping on input of step3 the simGmtStage2Digis collection. Without this PR one may reproduce the crash observed in the prompt reco at T0, while adding this PR the workflow completes smoothly. Anyway there is a side effect of adding several warning messages

%MSG-w L1CSCTPEmulatorNoInputCollection:   CSCTriggerPrimitivesProducer:simCscTriggerPrimitiveDigis  25-Sep-2018 13:48:36 CEST Run: 320822 Event: 127378579
+++ Warning: Collection of wire digis with label simMuonCSCDigis requested in configuration, but not found in the event... Skipping production of CSC TP digis +++

%MSG
%MSG-w L1CSCTPEmulatorNoInputCollection:   CSCTriggerPrimitivesProducer:simCscTriggerPrimitiveDigis  25-Sep-2018 13:48:36 CEST Run: 320822 Event: 127378579
+++ Warning: Collection of comparator digis with label simMuonCSCDigis requested in configuration, but not found in the event... Skipping production of CSC TP digis +++

%MSG

**Comment by thomreis** [comment]
please test

**Comment by thomreis** [comment]
+1

**Comment by thomreis** [comment]
@andrius-k please sign again.
The last commit just deals with removing warning messages.

**Comment by fabiocos** [comment]
@andrius-k I confirm that the last update solves the problem of the missing input collection, and of course the original crash. I would like to integrate this fix asap, could you please check?

**Comment by fabiocos** [comment]
merge

**Comment by Dr15Jones** [comment]
I think this pull request broke workflow: 136.7321 in the IB:
https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc700/CMSSW_10_3_X_2018-09-26-1100/pyRelValMatrixLogs/run/136.7321_RunZeroBias2016BnewL1repack+RunZeroBias2016BnewL1repack+HLTDR2newL1repack_2016+RECODR2newL1repack_2016reHLT_HIPM+HARVESTDR2/step3_RunZeroBias2016BnewL1repack+RunZeroBias2016BnewL1repack+HLTDR2newL1repack_2016+RECODR2newL1repack_2016reHLT_HIPM+HARVESTDR2.log#/

the error is
```
----- Begin Fatal Exception 26-Sep-2018 17:33:19 CEST-----------------------
An exception of category 'ScheduleExecutionFailure' occurred while
   [0] Calling beginJob
Exception Message:
Unrunnable schedule
Module run order problem found: 
rawDataCollector consumes packCaloStage2, packCaloStage2 consumes simCaloStage2Digis, simCaloStage2Digis consumes simCaloStage2Layer1Digis, simCaloStage2Layer1Digis consumes ecalDigis, ecalDigis consumes rawDataCollector
 Running in the threaded framework would lead to indeterminate results.
 Please change order of modules in mentioned Path(s) to avoid inconsistent module ordering.
----- End Fatal Exception -------------------------------------------------
```

This pull request made simCaloStage2Layer1Digis consume a data product from ecalDigis.

**Comment by thomreis** [comment]
I guess that WF did not run for the standard tests.
I'll have a look. I can see that there seems to be a circular dependency but when looking closer i would say that this is not the case since different FED numbers will be accessed in the raw data.

**Comment by fabiocos** [comment]
@thomreis no, only the short matrix runs in the PR tests. The problem is likely due to the fact that there is a special combination of steps in PyReleaseValidation for that workflow:

https://cmssdt.cern.ch/lxr/source/Configuration/PyReleaseValidation/python/relval_steps.py#1864

where the emulator is already called in the RECO workflow

**Comment by fabiocos** [comment]
@thomreis BTW, the output of that workflow 136.7321 is anyway flooded by warning messages

**Comment by fabiocos** [comment]
@davidlange6 @thomreis @rekovic @prebello @pgunnell could you please clarify the use and need of wf 136.7321? It looks to be the only test workflow that runs the L1 emulation in the RECO step so far, and this is conflicting with the recent addition of this emulation in the regular DQM sequence. I can imagine that this had some historical reason, but is it still needed?

**Comment by rekovic** [comment]
Hi @fabiocos 
I don't remember this wf.  So if deprecated, we should remove it. 
Now regarding the L1REPACK step failing when ran two times, we need to look at it.  Most likely fix will not
come today.  I can look at it tomorrow.

**Comment by andrius-k** [comment]
+1

Signing for the sake of completeness.

**Pull request merged**
