### PR TITLE
Make time report sane for threading

### PR DESCRIPTION
**Pull request by Dr15Jones**
The tools for measuring CPU time actually measure CPU time for all cores being used by the process. Therefore recording such information per Event, Path, and Module makes no sense when multiple threads are running. We now only record CPU time for the event loop as a whole and report only wall clock time for all other measurements. We also now report both the wall clock time for the entire event loop but also the sum of the time for each all Streams. The former allows throughput to be measured while the later is useful for determining the average time it takes one Event to be processed.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by Dr15Jones** [comment]
hold
I want to improve the format of the output

**Comment by Dr15Jones** [comment]
+1

**Comment by slava77** [comment]
Chris, please put back the CPU timing for single-thread applications.

**Comment by cvuosalo** [comment]
@Dr15Jones:
I agree with Slava. Please restore this functionality. We reco conveners depend on it.

**Comment by Dr15Jones** [comment]
It would help if you could state what problem you are trying to solve with the use of CPU time.

**Comment by slava77** [comment]
Hi Chris,

basic resource use monitoring by module is much more reliable with CPU time,
it is not significantly affected by database fetch latencies or
filesystem file open times.

To the first order, a wall-clock summary based on events excluding the
first one would do,
but it's not always covering  and is not as clean as the CPU time.



On 2/13/15 9:08 AM, Chris Jones wrote:
> It would help if you could state what problem you are trying to solve
> with the use of CPU time.
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cms-sw/cmssw/pull/7599#issuecomment-74267410>.
> 

-- 
***********************************************************************
 Vyacheslav (Slava) Krutelyov
 TAMU: Physics Dept Texas A&M MS4242, College Station, TX 77843-4242
 CERN: 42-R-027
 AIM/Skype: siava16              googleTalk: slava77@gmail.com
 (630) 291-5128  Cell (US)       +41 76 275 7116 Cell (CERN)

-----------------------------------------------------------------------

**Comment by Dr15Jones** [comment]
The time reading from the edm::Source is actually already removed from the per module timing. This was a side effect of removing the time spent in 'getBy*' in order to not overcount when doing unscheduled execution.
As for DB latencies, the HLT folk get around this in their timing measurements by running ```EventSetupRecordDataGetter``` as the first module in their jobs. I've started to think about how we might exclude the cost of 'get' from the EventSetup but its harder than the event case since in the event we pass to the module the transient 'edm::Event' which is a wrapper around the actual class which manages the event data products.

**Pull request merged**
