### PR TITLE
FastSim : HLT SUSYBSM validation : remove dependence on non-existing collection 'conversions'

### PR DESCRIPTION
**Pull request by lveldere**
gets rid of a whole list of warnings when running the validation sequence on FastSim

remove some obsolete configuration from SUSYBSM_HLT_VBF_Mu_cff.py

### CODE REVIEW

**Comment by lveldere** [comment]
please test

**Comment by lveldere** [comment]
please test

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
please test

**Comment by lveldere** [comment]
please test

**Comment by lveldere** [comment]
@deguio 
tests finally ran properly, ready for review

**Comment by deguio** [comment]
+1

**Comment by lveldere** [comment]
@davidlange6 

would you mind merging this one in 80X?
Consider it a bug fix: it removes non-sensical warning messages when running physicsDQM on FastSim.
If not, I'll close this one, as it has no impact on production.

**Pull request merged**
