### PR TITLE
[13_2_X] Additional fix for pixel FED error imbalance in DQM plots

### PR DESCRIPTION
**Pull request by ferencek**
#### PR description:

Backport of https://github.com/cms-sw/cmssw/pull/42977

### CODE REVIEW

**Comment by mmusich** [comment]
test parameters:
   * enable = gpu
   * workflows_gpu = 11634.503, 11634.507, 11634.583, 11634.587, 11634.593
   * relvals_opt_gpu = --what upgrade,standard,highstats,pileup,generator,extendedgen,production,ged,machine,premix,nano
   * addpkg = DQM/Integration

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
urgent
   * I am flagging this, because it would be great to have online to validate the (hopefully perfect at this point) closure of CPU vs GPU unpacking of pixel FED errors, and proceed to close https://github.com/cms-sw/cmssw/issues/41715 if that turn out positive

**Comment by antoniovilela** [comment]
ping @cms-sw/reconstruction-l2

**Comment by mandrenguyen** [comment]
backport of https://github.com/cms-sw/cmssw/pull/42977

**Comment by mandrenguyen** [comment]
+1

**Comment by antoniovilela** [comment]
+1

**Comment by gparida** [comment]
Hi everyone, These are studies to check the impact of this PR on CPU-GPU differences. 
For this, the reference and target area are as follows:
1. reference: CMSSW_13_2_5_patch3, /dev/CMSSW_13_2_0/GRun/V68
2. target: reference + [cms-sw/cmssw#42978](https://github.com/cms-sw/cmssw/pull/42978)

With respect to the reference, there is a reduction in the discrepancy upon including [cms-sw/cmssw#42978](https://github.com/cms-sw/cmssw/pull/42978).
For example 
Reference:

| Total | Reference CPU | Reference GPU | Gained | Lost | Change | Percentage Change | trigger |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |

| 1583141 | 43 | 57 | 14 | 0 | 14 | 32.56 | HLT\_AK8PFJet250\_SoftDropMass40\_PNetTauTau0p05\_v3 |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |

| 1583141 | 133 | 152 | 21 | \-2 | 23 | 17.29 | HLT\_PFHT800\_PFMET75\_PFMHT75\_IDTight\_v18 |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |

Target:

| 1568131 | 41 | 44 | 3 | 0 | 3 | 7.32 | HLT\_AK8PFJet250\_SoftDropMass40\_PNetTauTau0p05\_v3 |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |

| 1568131 | 133 | 138 | 6 | \-1 | 7 | 5.26 | HLT\_PFHT800\_PFMET75\_PFMHT75\_IDTight\_v18 |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |


Details can be found in this [spreadsheet](https://docs.google.com/spreadsheets/d/1OmPsSxmUJaNO59x6L-PhQD4-JSfCc9G7e-bqpjTq7-8/edit?usp=sharing)

**Pull request merged**
