### PR TITLE
[Phase 2 L1T] fixing ASAN errors in Phase2L1CaloJetEmulator

### PR DESCRIPTION
**Pull request by pallabidas**
#### PR description:

Fixing the error discussed in https://github.com/cms-sw/cmssw/pull/45540

#### PR validation:

Ran local checks using the following instructions:
```
scram p CMSSW_14_2_ASAN_X_2024-09-04-2300
cd CMSSW_14_2_ASAN_X_2024-09-04-2300
cmsenv
runTheMatrix.py -i all -l 25634.0 -t 4 --ibeos
```
#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Not a backport

### CODE REVIEW

**Comment by smuzaffar** [comment]
test parameters:
- workflows = 23634.0, 25634.0, 29634.501

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test for CMSW_14_2_ASAN_X

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test for CMSSW_14_2_ASAN_X

**Comment by smuzaffar** [comment]
@cms-sw/l1-l2 @cms-sw/upgrade-l2 can you please review this? This should fix the failing workflows for ASAN IB

**Comment by aloeliger** [comment]
+l1

**Comment by srimanob** [comment]
+Upgrade

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
