### PR TITLE
[132X] Update PdmV website links after SSO change

### PR DESCRIPTION
**Pull request by tvami**
#### PR description:

See https://github.com/cms-sw/cmssw/pull/43093

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Combined backport of https://github.com/cms-sw/cmssw/pull/43093 and https://github.com/cms-sw/cmssw/pull/43089 (in a single commit so it's easier to backport)

### CODE REVIEW

**Comment by tvami** [comment]
type bugfix

**Comment by tvami** [comment]
backport of https://github.com/cms-sw/cmssw/pull/43093

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
@cmsbuild , please abort
 * unit test has permission issues

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by menglu21** [comment]
+1

**Comment by tjavaid** [comment]
+1

**Comment by rappoccio** [comment]
+1

**Pull request merged**
