### PR TITLE
add ppRef workflows and update pbpb workflows for HI validation

### PR DESCRIPTION
**Pull request by hengne**
add ppRef workflows and update pbpb workflows for HI validation
These HI relval workflows are used to prepare the HI MC production.

### CODE REVIEW

**Comment by hengne** [comment]
please test

**Comment by srimanob** [comment]
+1

**Comment by davidlange6** [comment]
@hengne - are these changes already in 80x?

**Comment by hengne** [comment]
@davidlange6 Hi David, no, not yet, because 75x is the release for HIN MC production and data rereco, so we need to first deploy everything here in 75x, and then port to 80x to maintain them.

**Comment by hengne** [comment]
@davidlange6 and there are some specifics such as the Pb embedding module used in these HI workflows only included in 75x, and they are still under experimental stage, the porting to 80x is not very realistic...

**Comment by davidlange6** [comment]
75x isn't really the experimental release... lets get them ported and tested in 80x as that is where the IBs are most closely watched. Everything from the sim and reco side should be there for use in these workflows.

**Pull request closed without merging**
