### PR TITLE
[JMENano] Backport of #45167 (Add customize functions to recompute Puppi weights and PuppiMET, add new autoNano option) to 14_0_X

### PR DESCRIPTION
**Pull request by nurfikri89**
Backport of #45167

#### Original PR description:

This PR adds three wrapper functions which 

- set the PuppiProducer instances (`packedpuppi` & `packedpuppiNoLep`) to recompute puppi weights.
- setup the recalculation of PuppiMET.
- wraps over the two functions above.

The three functions can be set up in cmsRun config files  using `--customise` or `-customize_commands` arguments of cmsDriver.py. This would be useful if a (official or private) JMENano production needs updated Puppi weights. An `autoNano` option called `jmeNANOrePuppi` is added which sets up JMENano production with recomputation of Puppi weights and Puppi MET. Added two new test workflows (`2500.319,2500.406`) using the new `autoNano` option.

#### PR validation:

passes the usual runTheMatrix test: `runTheMatrix.py -l limited -i all --ibeos`
passes the new JMENano wokflows runTheMatrix: `runTheMatrix.py -i all --ibeos -l 2500.319,2500.406`

### CODE REVIEW

**Comment by vlimant** [comment]
enable nano

**Comment by vlimant** [comment]
please test

**Comment by vlimant** [comment]
please test

**Comment by nurfikri89** [comment]
My apologies. It is a typo. I will fix this now.

**Comment by vlimant** [comment]
please test

**Comment by vlimant** [comment]
+1
as for the master's PR #45167

**Comment by srimanob** [comment]
+Upgrade

**Comment by AdrianoDee** [comment]
+pdmv
(plain backport)

**Comment by rappoccio** [comment]
+1

**Pull request merged**
