### PR TITLE
Simplify usage of constants in HGCalCellUV

### PR DESCRIPTION
**Pull request by perrotta**
#### PR description:

As a follow up of https://github.com/cms-sw/cmssw/pull/37361#pullrequestreview-939397453 I think that some simplification of the usage of constants in HGCalCellUV is possible
This PR represents a possible implementation, based on the suggestion reported in that comment

#### PR validation:

It builds
No changes are expected anywhere

@Pruthvi-ch

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by cvuosalo** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

Technical PR.

**Comment by perrotta** [comment]
+1

**Pull request merged**
