### PR TITLE
Remove code related to legacy modules and SharedResources

### PR DESCRIPTION
**Pull request by wddgit**
#### PR description:

Remove code related to SharedResources and legacy type modules. We don't need this anymore as there aren't any legacy modules anymore. It simplifies the code and makes maintenance easier.

This also removes the overload of the usesResource function with no arguments. It was possible to call this from a "one" type module and then it would behave like a legacy module.  We don't want to preserve that ability. Nothing in CMSSW is currently using it. With this change, you will be required to supply a name for usesResource as an argument.

In a couple places, there is an if-else block and only one conditional path remains after the change. That block remains identical except for indentation.

#### PR validation:

Mostly this is deletions. It builds successfully even after checkdeps is run. Framework unit tests pass.

### CODE REVIEW

**Comment by wddgit** [comment]
please test

**Comment by makortel** [comment]
Comparisons show the usual
* https://github.com/cms-sw/cmssw/issues/43415
* https://github.com/cms-sw/cmssw/issues/43293
* https://github.com/cms-sw/cmssw/issues/43790

**Comment by makortel** [comment]
@cmsbuild, please test

I want to see if the behavior on 9.0 reproduces (likely not)

**Comment by wddgit** [comment]
Looks like the 9.0 behavior did reproduce. Although I can't see how it could be related the changes in the PR.

**Comment by makortel** [comment]
The baseline IB was the same. IIRC that was the situation also earlier when this rare non-reproducibility was observed (https://github.com/cms-sw/cmssw/issues/34448). Let's try once more.

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
Interesting, the differences in 9.0 continued to reproduce

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by wddgit** [comment]
please test

Try again. I don't think the failure could be related to the PR.

**Comment by makortel** [comment]
The comparison failures in 9.0 are surprisingly persistent

**Comment by Dr15Jones** [comment]
Code seems fine to me

**Comment by makortel** [comment]
I ran 9.0 on CMSSW_14_1_X_2024-03-04-1100, and again on CMSSW_14_1_X_2024-03-04-1100 with this PR recompiled locally (on slc7).

- I can reproduce the comparison differences (didn't check in detail, just that the DQM files have many differences)
- Sime printouts of about e.g. `GenVertex` show differences in the step1 (GEN-SIM)
- Tracer output is the same for for the step1
- `strace` shows many differences in the order of opened shared object files (too many to really comprehend)
- `LD_DEBUG=libs cmsRun` showed the library load order differences in an easier-to-digest format:

```diff
 library=libDetectorDescriptionCore.so
+library=libDataFormatsCLHEP.so
 library=libDetectorDescriptionDDCMS.so
 library=libCondFormatsGeometryObjects.so
-library=libDataFormatsCLHEP.so
 library=libDataFormatsEcalDetId.so
 ...
 library=libCondCorePopCon.so
+library=libGeometryVeryForwardGeometryBuilder.so
 library=libCalibPPSESProducers.so
 library=libCondCoreDBOutputService.so
-library=libGeometryVeryForwardGeometryBuilder.so
 library=libCondFormatsPPSObjects.so
-library=libDataFormatsCTPPSDetId.so
 library=libCalibPPSAlignmentGlobal.so
+library=libDataFormatsCTPPSDetId.so
 library=libUtilitiesXerces.so
  ...
 library=libDataFormatsTrajectoryState.so
+library=libSimDataFormatsCaloHit.so
 library=libDataFormatsForwardDetId.so
 library=libDataFormatsHcalDetId.so
 library=libDataFormatsSiPixelDetId.so
 library=libDataFormatsSiStripDetId.so
-library=libSimDataFormatsCaloHit.so
 library=libDataFormatsPhase2TrackerDigi.so
  ...
 library=libCommonToolsUtilAlgos.so
-library=libCondFormatsCastorObjects.so
+library=libCommonToolsUtils.so
 library=libDataFormatsHcalDigi.so
+library=libCondFormatsCastorObjects.so
 library=libCalibFormatsCaloObjects.so
-library=libCommonToolsUtils.so
 library=libboost_regex.so.1.80.0
  ...
 library=libCondFormatsSiStripObjects.so
-library=libDataFormatsSiPixelDigi.so
-library=libDataFormatsSiStripCommon.so
 library=libHeterogeneousCoreAlpakaCore.so
-library=libDataFormatsFEDRawData.so
 library=libCondFormatsPhysicsToolsObjects.so
+library=libDataFormatsSiStripCommon.so
+library=libDataFormatsSiPixelDigi.so
+library=libDataFormatsFEDRawData.so
 library=libCalibFormatsSiPixelObjects.so
  ...
 library=libGeneratorInterfaceExternalDecays.so
-library=libGeneratorInterfacePythia6Interface.so
 library=libGeneratorInterfaceTauolaInterface.so
-library=libGeneratorInterfaceCore.so
 library=libGeneratorInterfacePartonShowerVeto.so
+library=libGeneratorInterfacePythia6Interface.so
+library=libGeneratorInterfaceAlpgenInterface.so
+library=libGeneratorInterfaceCore.so
 library=libGeneratorInterfaceEvtGenInterface.so
-library=libGeneratorInterfaceLHEInterface.so
 library=libGeneratorInterfacePhotosInterface.so
-library=libGeneratorInterfaceAlpgenInterface.so
+library=libGeneratorInterfaceLHEInterface.so
 library=libSimDataFormatsGeneratorProducts.so
  ...
 library=libIOPoolStreamer.so
-library=libDataFormatsL1ScoutingRawData.so
 library=libDataFormatsLuminosity.so
+library=libDataFormatsL1ScoutingRawData.so
 library=libDataFormatsTCDS.so
  ...
   library=libDataFormatsHGCRecHit.so
-library=libPhysicsToolsTensorFlow.so
 library=libSimDataFormatsCaloTest.so
-library=libSimDataFormatsEcalTestBeam.so
 library=libSimDataFormatsTrackingHit.so
 library=libSimDataFormatsValidationFormats.so
+library=libPhysicsToolsTensorFlow.so
 library=libSimG4CoreWatcher.so
+library=libSimDataFormatsEcalTestBeam.so
 library=libTBDataFormatsEcalTBObjects.so
```

**Comment by makortel** [comment]
> * Sime printouts of about e.g. `GenVertex` show differences in the step1 (GEN-SIM)

Already the first event shows a difference
```diff
 GenVertex:       -7 ID:    0 (X,cT):0
- I: 1         9       37 -5.65e+01,-8.86e+00,+1.31e+02,+2.59e+02   3        -7
- O: 3        12      -15 +2.20e+01,-2.10e+01,-5.18e+01,+6.01e+01   3        -9
-             13       16 -7.85e+01,+1.21e+01,+1.83e+02,+1.99e+02   3       -10
-             16       37 -5.65e+01,-8.86e+00,+1.31e+02,+2.59e+02   2
+ I: 1         9      -37 -3.08e+02,+1.62e+02,+2.63e+02,+4.87e+02   3        -7
+ O: 3        12       15 -3.43e+00,+7.10e+01,-5.04e+00,+7.12e+01   3        -9
+             13      -16 -3.04e+02,+9.12e+01,+2.68e+02,+4.16e+02   3       -10
+             16      -37 -3.08e+02,+1.62e+02,+2.63e+02,+4.87e+02   2
```

**Comment by Dr15Jones** [comment]
So if you run the job again (either with or without the PR) do you get the same GenVertex results or does it change yet again?

**Comment by makortel** [comment]
I recompiled my developer area with the IB tag (i.e. the same packages as checked out with `git cms-merge-topic 44271`, but without the changes of the PR). That gave the same GenVertex printouts and DQM output as the IB baseline.

Also the library load order is the same (with the exception of `libFWCoreFramework.so` and one occurrence of`libc.so.6` being the other way) as in the IB baseline.

**Comment by makortel** [comment]
The GenVertex printout comes from
```
#0  0x00007fffbe9b5270 in HepMC::GenVertex::print(std::ostream&) const ()
   from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02827/slc7_amd64_gcc12/cms/cmssw/CMSSW_14_1_X_2024-03-03-0000/lib/slc7_amd64_gcc12/libSimDataFormatsGeneratorProducts.so
#1  0x00007fffbdd4d581 in Tauolapp::TauolaHepMCParticle::checkMomentumConservation() ()
   from /cvmfs/cms-ib.cern.ch/sw/x86_64/week1/slc7_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-03-04-1100/external/slc7_amd64_gcc12/lib/libTauolaHepMC.so.0
#2  0x00007fffbe1ddab2 in Tauolapp::TauolaParticlePair::checkMomentumConservation() ()
   from /cvmfs/cms-ib.cern.ch/sw/x86_64/week1/slc7_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-03-04-1100/external/slc7_amd64_gcc12/lib/libTauolaCxxInterface.so.0
#3  0x00007fffbe1e4b4b in Tauolapp::TauolaEvent::decayTaus() ()
   from /cvmfs/cms-ib.cern.ch/sw/x86_64/week1/slc7_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-03-04-1100/external/slc7_amd64_gcc12/lib/libTauolaCxxInterface.so.0
#4  0x00007fffbc3a747f in gen::TauolappInterface::decay(HepMC::GenEvent*) ()
   from /cvmfs/cms-ib.cern.ch/sw/x86_64/week1/slc7_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-03-04-1100/lib/slc7_amd64_gcc12/pluginTauolappInterface.so
#5  0x00007fffbf49ebaf in gen::ExternalDecayDriver::decay(HepMC::GenEvent*) ()
   from /cvmfs/cms-ib.cern.ch/sw/x86_64/week1/slc7_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-03-04-1100/lib/slc7_amd64_gcc12/libGeneratorInterfaceExternalDecays.so
#6  0x00007fffbf4c1b61 in edm::GeneratorFilter<gen::Pythia6Hadronizer, gen::ExternalDecayDriver>::filter(edm::Event&, edm::EventSetup const&) ()
   from /cvmfs/cms-ib.cern.ch/sw/x86_64/week1/slc7_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-03-04-1100/lib/slc7_amd64_gcc12/pluginGeneratorInterfacePythia6Filters.so
#7  0x00007ffff7ce32fe in edm::one::EDFilterBase::doEvent(edm::EventTransitionInfo const&, edm::ActivityRegistry*, edm::ModuleCallingContext const*) ()
   from /cvmfs/cms-ib.cern.ch/sw/x86_64/week1/slc7_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-03-04-1100/lib/slc7_amd64_gcc12/libFWCoreFramework.so
#8  0x00007ffff7cce63e in edm::WorkerT<edm::one::EDFilterBase>::implDo(edm::EventTransitionInfo const&, edm::ModuleCallingContext const*) ()
   from /cvmfs/cms-ib.cern.ch/sw/x86_64/week1/slc7_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-03-04-1100/lib/slc7_amd64_gcc12/libFWCoreFramework.so
```

**Comment by makortel** [comment]
@cmsbuild, please test

Let's do one more time

**Comment by makortel** [comment]
Now the 9.0 differences are gone here too. What remains are the usual
*  https://github.com/cms-sw/cmssw/issues/43293
* https://github.com/cms-sw/cmssw/issues/43790

**Comment by makortel** [comment]
+core

**Comment by makortel** [comment]
This goes totally off-topic, but running valgrind on the GEN-SIM step of the 9.0 shows many
```
==4984== Invalid read of size 8
==4984==    at 0x426BC33C: LHAPDF::LogBicubicInterpolator::_interpolateXQ2(LHAPDF::KnotArray const&, double, unsigned long, double, unsigned long, int) const (in /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02827/slc7_amd64_gcc12/external/lhapdf/6.4.0-5969784ee06af968580d5197ca83d374/lib/libLHAPDF.so)
==4984==    by 0x426A82E9: LHAPDF::PDF::xfxQ2(int, double, double) const (in /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02827/slc7_amd64_gcc12/external/lhapdf/6.4.0-5969784ee06af968580d5197ca83d374/lib/libLHAPDF.so)
==4984==    by 0x4272B0EB: structm_ (in /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02827/slc7_amd64_gcc12/external/lhapdf/6.4.0-5969784ee06af968580d5197ca83d374/lib/libLHAPDF.so)
==4984==    by 0x404581CE: pypdfu_ (pypdfu.f:356)
==4984==    by 0x404A053B: pysigh_ (pysigh.f:420)
==4984==    by 0x40439FF7: pymign_ (pymign.f:80)
==4984==    by 0x404267E3: pyinit_ (pyinit.f:287)
==4984==    by 0x4025A94E: gen::Pythia6Hadronizer::initializeForInternalPartons() (in /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02827/slc7_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-03-04-1100/lib/slc7_amd64_gcc12/pluginGeneratorInterfacePythia6Filters.so)
==4984==    by 0x4025B92E: edm::GeneratorFilter<gen::Pythia6Hadronizer, gen::ExternalDecayDriver>::beginLuminosityBlockProduce(edm::LuminosityBlock&, edm::EventSetup const&) (in /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02827/slc7_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-03-04-1100/lib/slc7_amd64_gcc12/pluginGeneratorInterfacePythia6Filters.so)
==4984==    by 0x4C62378: edm::one::EDFilterBase::doBeginLuminosityBlock(edm::LumiTransitionInfo const&, edm::ModuleCallingContext const*) (in /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02827/slc7_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-03-04-1100/lib/slc7_amd64_gcc12/libFWCoreFramework.so)
==4984==    by 0x4C4C8CF: edm::WorkerT<edm::one::EDFilterBase>::implDoBegin(edm::LumiTransitionInfo const&, edm::ModuleCallingContext const*) (in /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02827/slc7_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-03-04-1100/lib/slc7_amd64_gcc12/libFWCoreFramework.so)
==4984==    by 0x4B9F95E: std::__exception_ptr::exception_ptr edm::Worker::runModuleAfterAsyncPrefetch<edm::OccurrenceTraits<edm::LuminosityBlockPrincipal, (edm::BranchActionType)0> >(std::__exception_ptr::exception_ptr, edm::OccurrenceTraits<edm::LuminosityBlockPrincipal, (edm::BranchActionType)0>::TransitionInfoType const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::LuminosityBlockPrincipal, (edm::BranchActionType)0>::Context const*) (in /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02827/slc7_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-03-04-1100/lib/slc7_amd64_gcc12/libFWCoreFramework.so)
==4984==    by 0x4BA36ED: edm::SerialTaskQueue::QueuedTask<edm::SerialTaskQueueChain::push<edm::Worker::RunModuleTask<edm::OccurrenceTraits<edm::LuminosityBlockPrincipal, (edm::BranchActionType)0> >::execute()::{lambda()#1}&>(tbb::detail::d1::task_group&, edm::Worker::RunModuleTask<edm::OccurrenceTraits<edm::LuminosityBlockPrincipal, (edm::BranchActionType)0> >::execute()::{lambda()#1}&)::{lambda()#1}>::execute() (in /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02827/slc7_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-03-04-1100/lib/slc7_amd64_gcc12/libFWCoreFramework.so)
==4984==    by 0x42131CF: tbb::detail::d1::function_task<edm::SerialTaskQueue::spawn(edm::SerialTaskQueue::TaskBase&)::{lambda()#1}>::execute(tbb::detail::d1::execution_data&) (in /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02827/slc7_amd64_gcc12/cms/cmssw/CMSSW_14_1_X_2024-03-03-0000/lib/slc7_amd64_gcc12/libFWCoreConcurrency.so)
==4984==    by 0x63F9290: UnknownInlinedFun (task_dispatcher.h:322)
==4984==    by 0x63F9290: UnknownInlinedFun (task_dispatcher.h:458)
==4984==    by 0x63F9290: tbb::detail::r1::task_dispatcher::execute_and_wait(tbb::detail::d1::task*, tbb::detail::d1::wait_context&, tbb::detail::d1::task_group_context&) (task_dispatcher.cpp:168)
==4984==    by 0x4B61CBA: edm::FinalWaitingTask::wait() (in /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02827/slc7_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-03-04-1100/lib/slc7_amd64_gcc12/libFWCoreFramework.so)
==4984==    by 0x4B6B629: edm::EventProcessor::processRuns() (in /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02827/slc7_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-03-04-1100/lib/slc7_amd64_gcc12/libFWCoreFramework.so)
==4984==    by 0x4B6BB80: edm::EventProcessor::runToCompletion() (in /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02827/slc7_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-03-04-1100/lib/slc7_amd64_gcc12/libFWCoreFramework.so)
==4984==    by 0x4074EE: tbb::detail::d1::task_arena_function<main::{lambda()#1}::operator()() const::{lambda()#1}, void>::operator()() const (in /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02827/slc7_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-03-04-1100/bin/slc7_amd64_gcc12/cmsRun)
==4984==    by 0x63E59BC: tbb::detail::r1::task_arena_impl::execute(tbb::detail::d1::task_arena_base&, tbb::detail::d1::delegate_base&) (arena.cpp:688)
==4984==  Address 0x7b6e53f8 is 8 bytes before a block of size 400 alloc'd
==4984==    at 0x402EEE1: operator new(unsigned long) (in /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02827/slc7_amd64_gcc12/external/valgrind/3.22.0-e989c977f8949fc48f1bc1206f1f87c8/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==4984==    by 0x5285FFE: std::vector<double, std::allocator<double> >::_M_default_append(unsigned long) (in /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02827/slc7_amd64_gcc12/lcg/root/6.30.05-09dd1c56883e4f434d3cfa5dffc18d6e/lib/libMathCore.so)
==4984==    by 0x426BA5C2: LHAPDF::KnotArray::fillLogKnots() (in /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02827/slc7_amd64_gcc12/external/lhapdf/6.4.0-5969784ee06af968580d5197ca83d374/lib/libLHAPDF.so)
==4984==    by 0x426B68EC: LHAPDF::GridPDF::_loadData(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (in /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02827/slc7_amd64_gcc12/external/lhapdf/6.4.0-5969784ee06af968580d5197ca83d374/lib/libLHAPDF.so)
==4984==    by 0x426CACDE: LHAPDF::mkPDF(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int) (in /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02827/slc7_amd64_gcc12/external/lhapdf/6.4.0-5969784ee06af968580d5197ca83d374/lib/libLHAPDF.so)
==4984==    by 0x427287EB: (anonymous namespace)::PDFSetHandler::loadMember(int) (in /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02827/slc7_amd64_gcc12/external/lhapdf/6.4.0-5969784ee06af968580d5197ca83d374/lib/libLHAPDF.so)
==4984==    by 0x4272E0F4: pdfset_ (in /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02827/slc7_amd64_gcc12/external/lhapdf/6.4.0-5969784ee06af968580d5197ca83d374/lib/libLHAPDF.so)
==4984==    by 0x404264A5: pyinit_ (pyinit.f:115)
==4984==    by 0x4025A94E: gen::Pythia6Hadronizer::initializeForInternalPartons() (in /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02827/slc7_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-03-04-1100/lib/slc7_amd64_gcc12/pluginGeneratorInterfacePythia6Filters.so)
==4984==    by 0x4025B92E: edm::GeneratorFilter<gen::Pythia6Hadronizer, gen::ExternalDecayDriver>::beginLuminosityBlockProduce(edm::LuminosityBlock&, edm::EventSetup const&) (in /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02827/slc7_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-03-04-1100/lib/slc7_amd64_gcc12/pluginGeneratorInterfacePythia6Filters.so)
==4984==    by 0x4C62378: edm::one::EDFilterBase::doBeginLuminosityBlock(edm::LumiTransitionInfo const&, edm::ModuleCallingContext const*) (in /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02827/slc7_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-03-04-1100/lib/slc7_amd64_gcc12/libFWCoreFramework.so)
==4984==    by 0x4C4C8CF: edm::WorkerT<edm::one::EDFilterBase>::implDoBegin(edm::LumiTransitionInfo const&, edm::ModuleCallingContext const*) (in /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02827/slc7_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-03-04-1100/lib/slc7_amd64_gcc12/libFWCoreFramework.so)
==4984==    by 0x4B9F95E: std::__exception_ptr::exception_ptr edm::Worker::runModuleAfterAsyncPrefetch<edm::OccurrenceTraits<edm::LuminosityBlockPrincipal, (edm::BranchActionType)0> >(std::__exception_ptr::exception_ptr, edm::OccurrenceTraits<edm::LuminosityBlockPrincipal, (edm::BranchActionType)0>::TransitionInfoType const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::LuminosityBlockPrincipal, (edm::BranchActionType)0>::Context const*) (in /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02827/slc7_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-03-04-1100/lib/slc7_amd64_gcc12/libFWCoreFramework.so)
==4984==    by 0x4BA36ED: edm::SerialTaskQueue::QueuedTask<edm::SerialTaskQueueChain::push<edm::Worker::RunModuleTask<edm::OccurrenceTraits<edm::LuminosityBlockPrincipal, (edm::BranchActionType)0> >::execute()::{lambda()#1}&>(tbb::detail::d1::task_group&, edm::Worker::RunModuleTask<edm::OccurrenceTraits<edm::LuminosityBlockPrincipal, (edm::BranchActionType)0> >::execute()::{lambda()#1}&)::{lambda()#1}>::execute() (in /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02827/slc7_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-03-04-1100/lib/slc7_amd64_gcc12/libFWCoreFramework.so)
==4984==    by 0x42131CF: tbb::detail::d1::function_task<edm::SerialTaskQueue::spawn(edm::SerialTaskQueue::TaskBase&)::{lambda()#1}>::execute(tbb::detail::d1::execution_data&) (in /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02827/slc7_amd64_gcc12/cms/cmssw/CMSSW_14_1_X_2024-03-03-0000/lib/slc7_amd64_gcc12/libFWCoreConcurrency.so)
==4984==    by 0x63F9290: UnknownInlinedFun (task_dispatcher.h:322)
==4984==    by 0x63F9290: UnknownInlinedFun (task_dispatcher.h:458)
==4984==    by 0x63F9290: tbb::detail::r1::task_dispatcher::execute_and_wait(tbb::detail::d1::task*, tbb::detail::d1::wait_context&, tbb::detail::d1::task_group_context&) (task_dispatcher.cpp:168)
==4984==    by 0x4B61CBA: edm::FinalWaitingTask::wait() (in /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02827/slc7_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-03-04-1100/lib/slc7_amd64_gcc12/libFWCoreFramework.so)
==4984==    by 0x4B6B629: edm::EventProcessor::processRuns() (in /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02827/slc7_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-03-04-1100/lib/slc7_amd64_gcc12/libFWCoreFramework.so)
==4984==    by 0x4B6BB80: edm::EventProcessor::runToCompletion() (in /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02827/slc7_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-03-04-1100/lib/slc7_amd64_gcc12/libFWCoreFramework
.so)
==4984==    by 0x4074EE: tbb::detail::d1::task_arena_function<main::{
```

and
```
==4984== Conditional jump or move depends on uninitialised value(s)
==4984==    at 0x404C0CED: pystrf_ (pystrf.f:145)
==4984==    by 0x4041C539: pyexec_ (pyexec.f:134)
==4984==    by 0x40419BB3: pyevnw_ (pyevnw.f:431)
==4984==    by 0x40259FB9: gen::Pythia6Hadronizer::generatePartonsAndHadronize() (in /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02827/slc7_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-03-04-1100/lib/slc7_amd64_gcc12/pluginGeneratorInterfacePythia6Filters.so)
==4984==    by 0x4025D950: edm::GeneratorFilter<gen::Pythia6Hadronizer, gen::ExternalDecayDriver>::filter(edm::Event&, edm::EventSetup const&) (in /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02827/slc7_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-03-04-1100/lib/slc7_amd64_gcc12/pluginGeneratorInterfacePythia6Filters.so)
==4984==    by 0x4C612FD: edm::one::EDFilterBase::doEvent(edm::EventTransitionInfo const&, edm::ActivityRegistry*, edm::ModuleCallingContext const*) (in /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02827/slc7_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-03-04-1100/lib/slc7_amd64_gcc12/libFWCoreFramework.so)
==4984==    by 0x4C4C63D: edm::WorkerT<edm::one::EDFilterBase>::implDo(edm::EventTransitionInfo const&, edm::ModuleCallingContext const*) (in /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02827/slc7_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-03-04-1100/lib/slc7_amd64_gcc12/libFWCoreFramework.so)
==4984==    by 0x4BDE3D8: std::__exception_ptr::exception_ptr edm::Worker::runModuleAfterAsyncPrefetch<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(std::__exception_ptr::exception_ptr, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::TransitionInfoType const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*) (in /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02827/slc7_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-03-04-1100/lib/slc7_amd64_gcc12/libFWCoreFramework.so)
==4984==    by 0x4BDF4AE: edm::SerialTaskQueue::QueuedTask<edm::SerialTaskQueueChain::push<edm::Worker::RunModuleTask<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >::execute()::{lambda()#1}&>(tbb::detail::d1::task_group&, edm::Worker::RunModuleTask<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >::execute()::{lambda()#1}&)::{lambda()#1}>::execute() (in /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02827/slc7_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-03-04-1100/lib/slc7_amd64_gcc12/libFWCoreFramework.so)
==4984==    by 0x42131CF: tbb::detail::d1::function_task<edm::SerialTaskQueue::spawn(edm::SerialTaskQueue::TaskBase&)::{lambda()#1}>::execute(tbb::detail::d1::execution_data&) (in /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02827/slc7_amd64_gcc12/cms/cmssw/CMSSW_14_1_X_2024-03-03-0000/lib/slc7_amd64_gcc12/libFWCoreConcurrency.so)
==4984==    by 0x63F9290: UnknownInlinedFun (task_dispatcher.h:322)
==4984==    by 0x63F9290: UnknownInlinedFun (task_dispatcher.h:458)
==4984==    by 0x63F9290: tbb::detail::r1::task_dispatcher::execute_and_wait(tbb::detail::d1::task*, tbb::detail::d1::wait_context&, tbb::detail::d1::task_group_context&) (task_dispatcher.cpp:168)
==4984==    by 0x4B61CBA: edm::FinalWaitingTask::wait() (in /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02827/slc7_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-03-04-1100/lib/slc7_amd64_gcc12/libFWCoreFramework.so)
==4984==    by 0x4B6B629: edm::EventProcessor::processRuns() (in /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02827/slc7_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-03-04-1100/lib/slc7_amd64_gcc12/libFWCoreFramework.so)
==4984==    by 0x4B6BB80: edm::EventProcessor::runToCompletion() (in /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02827/slc7_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-03-04-1100/lib/slc7_amd64_gcc12/libFWCoreFramework.so)
==4984==    by 0x4074EE: tbb::detail::d1::task_arena_function<main::{lambda()#1}::operator()() const::{lambda()#1}, void>::operator()() const (in /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02827/slc7_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-03-04-1100/bin/slc7_amd64_gcc12/cmsRun)
==4984==    by 0x63E59BC: tbb::detail::r1::task_arena_impl::execute(tbb::detail::d1::task_arena_base&, tbb::detail::d1::delegate_base&) (arena.cpp:688)
==4984==    by 0x408ED1: main::{lambda()#1}::operator()() const (in /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02827/slc7_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-03-04-1100/bin/slc7_amd64_gcc12/cmsRun)
==4984==    by 0x40518B: main (in /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02827/slc7_amd64_gcc12/cms/cmssw-patch/CMSSW_14_1_X_2024-03-04-1100/bin/slc7_amd64_gcc12/cmsRun)
==4984==
```

so random behavior is not really surprising (maybe the surprise is that it doesn't happen more often). This could be related to the discussions in https://github.com/cms-sw/cmssw/issues/35082, https://github.com/cms-sw/cmssw/issues/35251, https://github.com/cms-sw/cmssw/issues/43526 (maybe we should finally address https://github.com/cms-sw/cmssw/issues/43526#issuecomment-1850493690)

**Comment by makortel** [comment]
> This goes totally off-topic, but running valgrind on the GEN-SIM step of the 9.0 shows many

Now reported in https://github.com/cms-sw/cmssw/issues/44371

**Comment by rappoccio** [comment]
+1

**Pull request merged**
