### PR TITLE
add variants to the phase-2 relval workflow running the HLT timing menu, up to step2

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

This is a follow-up to https://github.com/cms-sw/cmssw/pull/45776 and adds a variant to the phase-2 HLT timing menu worklow using the `alpaka` and `ticl_v5` modifiers. This should help in spotting issues such as https://github.com/cms-sw/cmssw/pull/46060.

#### PR validation:

```console
runTheMatrix.py --what upgrade -l 29634.750,29634.751,29634.752
```

runs fine.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

N/A

### CODE REVIEW

**Comment by mmusich** [comment]
test parameters:
   * relvals_opt = --what upgrade
   * workflows = 29634.751

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
I am expecting this round of tests to fail.

**Comment by mmusich** [comment]
test parameters:
   * relvals_opt = --what upgrade
   * workflows = 29634.751, 29634.752

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by Moanwar** [comment]
+Upgrade

**Comment by AdrianoDee** [comment]
+pdmv

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
