### PR TITLE
Electron stream 74 x

### PR DESCRIPTION
**Pull request by rgerosa**
Update of electron stream code :
1) work with electrons selected from more than one HLT path
2) dump more than one electron for each event in order to commission it also with Zee events

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild please test

**Comment by diguida** [comment]
@rgerosa it this a back port form 75X?
If not, please open a PR in that cycle, and then we can look at this

**Comment by rgerosa** [comment]
@diguida : yes you are right, this is not a back port from 75X. 
I am going to open another PR in 75X.

**Comment by diguida** [comment]
@rgerosa please close this one. You can re-open it once the corresponding 75X is integrated.

**Pull request closed without merging**
