### PR TITLE
Removed GBRForestFileName, prepare for new era 2018, 10_0_X

### PR DESCRIPTION
**Pull request by sikler**
There was a crush running on current P5 data, related to GBRForestFileName ￼
seen in CMSSW_10_0_X and 10_1_X
problem seen for beam_dqm_sourceclient-live_cfg.py
reason: GBRForestFileName should have been removed, but did not happen (back in September last year)
thanks to Matti, problem fixed, and in addition era is now properly set to eras.Run2_2018

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by dmitrijus** [comment]
backport of https://github.com/cms-sw/cmssw/pull/22708

**Comment by fabiocos** [comment]
@sikler after the move to 10_1_X this PR can be closed

**Pull request closed without merging**
