### PR TITLE
relocate HcalCaloFlagLabels from RecoLocalCalo/HcalRecAlgos to DataFormats/METReco (as #8113)

### PR DESCRIPTION
**Pull request by slava77**
- HcalCaloFlagLabels are moved to DataFormats/METReco
- HcalCaloFlagTool is split off into DataFormats/METReco/interface/HcalCaloFlagTool, since it's rarely used

This removes dependence of DF on Reco

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cmsbuild did jenkins get stuck or is it busy working on other PR tests?

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/8114	8eafdb8
tested in CMSSW_7_4_X_2015-03-06-0200 /test area fix-DFMet-dep/
short matrix run completes and shows no  differences in monitored quantities (DQM or FW lite)

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
@nclopezo - seems the tests are stuck. could you restart them?

**Comment by nclopezo** [comment]
Ok, I queued them.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
