### PR TITLE
re-miniAOD workflows on 94X input datasets (94MAOD)

### PR DESCRIPTION
**Pull request by fabozzi**
Adding re-miniAOD workflows on 94X MINIAOD inputs (data and MC).

### CODE REVIEW

**Comment by fabozzi** [comment]
backport of #22200

**Comment by fabozzi** [comment]
please test workflow 1325.51

**Comment by fabozzi** [comment]
Exception: 'run2_miniAOD_94XFall17' is not a valid option for '--era'

@fabiocos @slava77 : is the era needed for reminiAOD not yet merged in this branch?

**Comment by slava77** [comment]
On 2/26/18 8:01 AM, fabozzi wrote:
> Exception: 'run2_miniAOD_94XFall17' is not a valid option for '--era'
> 
> @fabiocos <https://github.com/fabiocos> @slava77
> <https://github.com/slava77> : is the era needed for reminiAOD not yet
> merged in this branch?
> 

right,
it is in #21977

**Comment by slava77** [comment]
@cmsbuild please test workflow 1325.51

#21977 is now merged and the tests should work.

**Comment by slava77** [comment]
the IB is broken.
and the working CMSSW_9_4_MAOD_X_2018-03-06-1100 didn't show up in jenkins yet.
I'll try again in a few hours.

**Comment by slava77** [comment]
@cmsbuild please test workflow 1325.51

a working IB should be available now

**Comment by fabozzi** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
