### PR TITLE
Remove unsupported chars from PPSAlignmentWorker

### PR DESCRIPTION
**Pull request by tvami**
#### PR description:

Quick fix to https://github.com/cms-sw/cmssw/issues/38885
PPS experts will follow up when we are less constrained in time with possible optimization (like refactoring the loop) 

#### PR validation:

Ran wf 1042

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Not a backport, but needs to backport to 12_4_X

### CODE REVIEW

**Comment by tvami** [comment]
urgent
 * backport needed for datataking

**Comment by tvami** [comment]
type ctpss,bugfix

**Comment by tvami** [comment]
test parameters:
  - workflows = 1042

**Comment by MatiXOfficial** [comment]
Weird that 1042 passed. You should also update PPSAlignmentHarvester and PPSAlignmentConfigurationESSource.

**Comment by tvami** [comment]
> Weird that 1042 passed. 

Sorry I dont follow, why is that weird?

**Comment by MatiXOfficial** [comment]
Because you changed the paths of the plots which are used by the harvester. If there is no error, then I assume that the results are empty.

**Comment by MatiXOfficial** [comment]
The worker decodes some numbers in the paths, that's why there were points in the first place. If they are replaced by 'p', the harvester cannot properly decode them as doubles.

**Comment by tvami** [comment]
So I learned @MatiXOfficial actually have made his own version of the solution, thus I'm closing this PR

**Comment by tvami** [comment]
-alca

**Pull request closed without merging**
