### PR TITLE
Run2-hcx173 Backport #22835

### PR DESCRIPTION
**Pull request by bsunanda**
Fix AlCaReco sequence and also change the M0 parameter syntax

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by perrotta** [comment]
backport of #22835

**Comment by abdoulline** [comment]
NB: we need this ALCARECOHcal fix for early data taking. Highly desirable for 10_1_1...

**Comment by lpernie** [comment]
+1

**Comment by perrotta** [comment]
+1
- Identical to #22835, now merged in the master
- Changes in reco configs are just cosmetics, and there is no effect on reco outputs according to the jenkins tests

**Comment by fabiocos** [comment]
+1

**Pull request merged**
