### PR TITLE
Pr l1tmuon emulator 80x

### PR DESCRIPTION
**Pull request by mulhearn**
This adds the 2016 Muon Emulation and related data formats.

The dependence on Alca/DB should clear once PR #13064 is approved.

### CODE REVIEW

**Comment by mulhearn** [comment]
please test

**Comment by mulhearn** [comment]
+1

**Comment by Martin-Grunewald** [comment]
please test
(HIon problem should be solved)

**Comment by davidlt** [comment]
Why 334 files modified/added, thousands modified and we still end up with only 2 commits? Is there are better way logically split changes into separate commits? Now it's one big monolithic block doing who knows what. Commits are the way to split things into logical smaller independent (as possible) pieces and provide documentation why and then how it works. This will not help anyone who will be looking at those files, git history, doing review, etc.

**Comment by davidlt** [comment]
I looked at the function and I don't see there any format string. Could you replace it `fprintf` to `fwrite` or `fputs` ?

**Comment by mulhearn** [comment]
please test

**Comment by mulhearn** [comment]
OK, I'll get the rest... I thought I could ignore the warnings.

**Comment by mulhearn** [comment]
please test

**Comment by mulhearn** [comment]
+1

**Comment by mulhearn** [comment]
I'm cleaning up the EndCap includes and namespace.

**Comment by mulhearn** [comment]
Actually, David, I have downstream commits that will go into conflict if I make extensive changes here, can we make minimal code cleanup here, and you can hold me to my word on the downstream update #13160 ?

**Comment by mulhearn** [comment]
@davidlange6 OK, I am still learning git workflows!   I was able to cherry-pick all the downstream changes just affecting muons.  So I can work on this PR for cleanup purposes if necessary.  I removed the header file you requested, let me know if more is needed...

**Comment by mulhearn** [comment]
please test

**Comment by mulhearn** [comment]
+1

**Comment by davidlange6** [comment]
@mulhearn - looks good aside from stuff going into a deprecate subdirectory. Is this run1/2015 trigger stuff or stuff never used?

**Comment by mulhearn** [comment]
That is stuff I really want the developers to get rid of our at least substantially clean up for v2.0.  I can move it out if you like, but I prefer to keep it there as it makes easy to spot the dependent code.

**Comment by mulhearn** [comment]
In short, its an idiom that made sense during studies, but its code with no real hardware analog.  Its sort of the complete opposite of the Calo code that has a very tight relationship between firmware and software blocks.

**Comment by mulhearn** [comment]
Unfortunately, due to schedule, we are essentially putting in code while cleanup is still underway.  We have to do things adiabatically, because we do already have decent agreement between firmware and emulation.  But my suspicion is that cleanup will be needed to reach 100% agreement and ease the long term maintenance costs.

**Comment by davidlange6** [comment]
Ok, so it's not the legacy trigger. Then ok, but let's clean up asasp

**Pull request merged**
