### PR TITLE
Hcal validation update 10_0_X ieta shift fix (backport)

### PR DESCRIPTION
**Pull request by bcmcms**
Backport of https://github.com/cms-sw/cmssw/pull/22034

@abdoulline, @hatakeyamak, @mariadalfonso @deguio

### CODE REVIEW

**Comment by abdoulline** [comment]
@dmitrijus, @fabiocos 
It would be good to have it in 10_0_2. It doesn't change physics, after all.
Just improves/fixes some validation aspects...

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
@dmitrijus @jfernan2 this PR has been signed and integrated in 10_1_X, do you see problems in integrating it in 10_0_X?

**Comment by dmitrijus** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
