### PR TITLE
[13_0_X] Fix uGT shower unpacking

### PR DESCRIPTION
**Pull request by dinyar**
#### PR description:

Fixed the uGT shower (un)packing logic.

Also use named constants for the uG(M)T firmware versions and FED IDs used by the (un)packers.

Backport of #40822 and #40841 for 13_0_X, required so shower (un)packing works as expected.

attn: @elfontan and @eyigitba

### CODE REVIEW

**Comment by epalencia** [comment]
Please test

**Comment by aloeliger** [comment]
please test

**Comment by aloeliger** [comment]
backport of #40841,#40822

**Comment by aloeliger** [comment]
backport of #40841

**Comment by aloeliger** [comment]
+l1

**Comment by perrotta** [comment]
+1

**Pull request merged**
