### PR TITLE
Compatibility with pythia8 212 and features from 76X

### PR DESCRIPTION
**Pull request by mkirsano**

### CODE REVIEW

**Comment by mkirsano** [comment]
To be built with cmsdist #1946

**Comment by degano** [comment]
@mkirsano FYI this has been tested with a new script that takes also the CMSDIST PR. Therefore I think the error found is legitimate.

**Comment by degano** [comment]
@mkirsano (writing again) After a manual double check I confirm that's a legitimate error found by the new script that tests this cmssw PR against the cmsdist one.

**Comment by mkirsano** [comment]
Somehow this was not needed in other branches.

**Comment by degano** [comment]
@mkirsano I'll trigger the (custom) tests again.

**Comment by smuzaffar** [comment]
please test with cms-sw/cmsdist#1946

**Comment by lveldere** [comment]
+1

**Comment by covarell** [comment]
+1

**Comment by degano** [comment]
@davidlange6 should we proceed with the merging of this one along its cmsdist part?

**Pull request merged**
