### PR TITLE
More BuildFiles cleaning

### PR DESCRIPTION
**Pull request by guitargeek**
#### PR description:

Another quick BuildFile cleaning PR in the style of many before (for example https://github.com/cms-sw/cmssw/pull/32714).

As always, only the dependencies which are **not included in any of the sources** are removed, so these changes are orthogonal and complementary to the recent PRs which added all packages that are **actually included**.

I also made sure that all of the removed library dependencies that are actually a dependency of the corresponding plugins were transferred to `plugins/BuildFile.xml`.

#### PR validation:

CMSSW compiles. It was checked that all newly added dependencies are actually required by the package with `git grep`.

### CODE REVIEW

**Comment by srimanob** [comment]
Please test

**Comment by jfernan2** [comment]
+1

**Comment by perrotta** [comment]
+1
- Technical
- Jenkins tests pass

**Comment by Martin-Grunewald** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

**Comment by ggovi** [comment]
+1

**Comment by yuanchao** [comment]
+1
* only buildfile.xml is modified
* WF tests and unit tests all passed
* python compiled normally; static build check warnings are not part of the modifications

**Comment by qliphy** [comment]
+1

**Pull request merged**
