### PR TITLE
HLT menu development for `13_0_X` (7/N) [`13_1_X`]

### PR DESCRIPTION
**Pull request by missirol**
#### PR description:

Development of HLT menus for `CMSSW_13_0_X`.

This is the PR for the `master` branch, which will then be backported to `13_0_X` (the latter is the release cycle currently used for Run-3 HLT-menu development).

This update includes the integration of the following JIRA tickets.

 - [CMSHLT-2720](https://its.cern.ch/jira/browse/CMSHLT-2720): [TSG] seed `DQMGPUvsCPU` triggers of GRun with all L1A-Physics events
 - [CMSHLT-2733](https://its.cern.ch/jira/browse/CMSHLT-2733): [HCAL] increased HLT PSs of `IsoTrack(HB,HE)` triggers by 3
 - [CMSHLT-2736](https://its.cern.ch/jira/browse/CMSHLT-2736): [TSG] remove SCAL unpacker from Run-3 HLT menus
 - [CMSHLT-2737](https://its.cern.ch/jira/browse/CMSHLT-2737): [TSG] add `L1_SingleEG4*` seeds to single-EG Scouting trigger
 - [CMSHLT-2741](https://its.cern.ch/jira/browse/CMSHLT-2741): [ECAL] removal of `Ele36*_noEoP*` trigger
 - [CMSHLT-2746](https://its.cern.ch/jira/browse/CMSHLT-2746): [TSG] separate Scouting triggers seeded by `L1_DoubleMu` and `L1_(HTT,*Jet)`
 - [CMSHLT-2751](https://its.cern.ch/jira/browse/CMSHLT-2751): [HIG] remove MSSM-Hbb triggers using DeepCSV
 - [CMSHLT-2752](https://its.cern.ch/jira/browse/CMSHLT-2752): [TSG] updated HLT PSs of `*PFJet(140,200)` in low-lumi columns
 - [CMSHLT-2753](https://its.cern.ch/jira/browse/CMSHLT-2753): [HIG] remove `HLT_SingleJet30_Mu12_SinglePFJet40_v` trigger
 - [CMSHLT-2755](https://its.cern.ch/jira/browse/CMSHLT-2755): [TSG] added `L1_DoubleJet30er2p5_Mass_Min250_dEta_Max1p5` seed to Scouting
 - [CMSHLT-2758](https://its.cern.ch/jira/browse/CMSHLT-2758): [ECAL] remove `*LowPU` products from EventContent of ALCAP0 stream

#### PR validation:

TSG tests.

#### If this PR is a backport, please specify the original PR and why you need to backport that PR. If this PR will be backported, please specify to which release cycle the backport is meant for:

`CMSSW_13_0_X`

### CODE REVIEW

**Comment by missirol** [comment]
test parameters:
  - enable = gpu
  - workflows_gpu = 12434.506,12434.512,12434.522,140.065506,140.065512,140.065522

**Comment by missirol** [comment]
please test

**Comment by missirol** [comment]
Maybe it's just me, but I cannot see the DQM bin-by-bin comparisons in `cmsweb.cern.ch/dqm`. The symptoms are similar to #38980.

I see the issue in other PRs as well. It looks like it started yesterday: I can see plots as usual up to https://github.com/cms-sw/cmssw/pull/41384#issuecomment-1518485890 (Apr 22, 05:08), while they do not appear for me starting from https://github.com/cms-sw/cmssw/pull/41385#issuecomment-1518676833 (Apr 22, 16:45).

@cms-sw/dqm-l2, could you please have a look ?

**Comment by missirol** [comment]
+hlt
 - Changes in the outputs of PR tests are in line with the updates to the HLT GRun menu.
 - DQM bin-by-bin comparisons could not be inspected because of https://github.com/cms-sw/cmssw/pull/41387#issuecomment-1519099032.

**Comment by perrotta** [comment]
+1

**Pull request merged**
