### PR TITLE
Tests for enum use in cutParser using ROOT6

### PR DESCRIPTION
**Pull request by Dr15Jones**
The ROOT 6 version of this test has to be different than the ROOT 5 becuase Cintex is gone.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
The failure is from the release being used, not this pull request.

**Comment by Dr15Jones** [comment]
Please test

**Comment by Dr15Jones** [comment]
@ktf this fixes the build failure

**Comment by slava77** [comment]
This can probably be merged already

**Pull request merged**
