### PR TITLE
convert to unit test in FWCore/PythonFramework to pybind11

### PR DESCRIPTION
**Pull request by davidlange6**

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@davidlange6 thanks for porting it to pybind11. I think this will still fail in DEVEL and PY3 IBs as `PythonTestProducer` is using `python2` while `cmsRun` needs `python3`. Should we conditionaly use `python3` e.g.
```
  <ifrelease name="_DEVEL_|_PY3_">
    <use name="python3"/>
  <else/>
    <use name="python"/>
  </ifrelease>
```

**Comment by davidlange6** [comment]
yes, I think so - I'll make that change

**Comment by davidlange6** [comment]
please test

**Comment by smuzaffar** [comment]
please test for CMSSW_12_0_DEVEL_X
just to make sure that it works for DEVEL too

**Comment by smuzaffar** [comment]
+core
unit test for DEVEL IB also ran successfully ( https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-ca36a1/16188/unitTests/src/FWCore/PythonFramework/test/TestFWCorePythonFrameworkDriver/testing.log )

**Comment by qliphy** [comment]
+1

**Pull request merged**
