### PR TITLE
Fill time and uncertainties for slimmed primary vertices (93X)

### PR DESCRIPTION
**Pull request by lgray**
93X backport of #20911

### CODE REVIEW

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
@bendavid

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
backport of #20911

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/20912	0e2793e
- completes assignment of upstream vertex parameters to the slimmed vertex; incidentally safe backport (standard workflows still do not use 4D vertex)
- jenkins tests pass and comparisons show no differences

**Comment by slava77** [comment]
assign upgrade

**Comment by kpedro88** [comment]
+1

**Comment by kpedro88** [comment]
@lgray @bendavid is this desired for MTD miniAOD campaign?

**Comment by bendavid** [comment]
Yes.

**Comment by kpedro88** [comment]
@monttj please sign
@davidlange6 please merge

**Comment by lgray** [comment]
Can this please get merged? This has been waiting for the analysis sign off for a while and really should be in 93X....

**Comment by lgray** [comment]
@monttj please sign
@davidlange6 please merge

**Comment by davidlange6** [comment]
merge

**Pull request merged**
