### PR TITLE
[nT2] cleanup of geometry and rechits producer

### PR DESCRIPTION
**Pull request by forthommel**
#### PR description:

Implementation of the final PR https://github.com/cms-sw/cmssw/pull/38986 comments by @perrotta for the cleanup of both the geometry definition and the rechits producer plugin.

#### PR validation:

Code compiles and runs

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for: N/A

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by bsunanda** [comment]
+geometry

**Comment by jpata** [comment]
+reconstruction
- trivial removal of unused header on the reco side.

**Comment by perrotta** [comment]
+1

**Pull request merged**
