### PR TITLE
81X HLT update after-MD3 train

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
81X HLT update after-MD3 train

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
@mmusich 
Marco, this HLT PR now requires new L1T menus in GTs, namely ```L1Menu_Collisions2016_v9_m2_xml``` for the run2 pp GTs (such as run2_mc etc.), and
```L1Menu_HeavyIons2016_v0_xml``` for the run2 pPb GTs (such as run2_mc_pa etc.).
Could you please prepare those and update autoCond.py?
Thanks and best regards
Martin

**Comment by Martin-Grunewald** [comment]
@mmusich 
136.731 fails in L1REPACK using ```auto:run2_hlt_relval```

**Comment by mmusich** [comment]
@Martin-Grunewald indeed. 
I am waiting to see if the changes in most MC Global Tags needed by #16070 can come in time to be included in the update for the L1 menu today. If not, I'll do it in steps and deliver GTs for this PR first.

**Comment by Martin-Grunewald** [comment]
@mmusich 

Marco, any idea on the timeline?

Thanks and best regards

Martin

**Comment by mmusich** [comment]
@Martin-Grunewald we received the ingredients yesterday night. I'll work on that later today/tomorrow

**Comment by mmusich** [comment]
@Martin-Grunewald you can find the updated Global Tags here: https://github.com/cms-sw/cmssw/pull/16278

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
@mmusich 
Thanks for the PR, cherry picked and included here to see how the tests now run.

**Comment by Martin-Grunewald** [comment]
+1

**Comment by mmusich** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
