### PR TITLE
Fix to topHLTOfflineDQM package by removing warning message in 81X

### PR DESCRIPTION
**Pull request by soureek**
Commenting out warning message corresponding to presence of TriggerSummary collection. 
Corresponding PR in 80X #15530

### CODE REVIEW

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
please test

**Comment by Soureek89** [comment]
Is it necessary that the changes made has to pass 2011 Cosmics or 2011 Min. Bias workflows? 
The detector and trigger conditions has changed quite a bit after 2011 runs. 
Anyway to my opinion, these errors are there because some files/samples could not be located by das client and there's nothing to do from developer side. Please test again if necessary.

**Comment by davidlange6** [comment]
please test
maybe das is doing better today

**Comment by davidlange6** [comment]
+1

**Pull request merged**
