### PR TITLE
Track "Patatrack" developments as of CMSSW_10_4_0_pre4

### PR DESCRIPTION
**Pull request by fwyzard**
This commit includes all the changes in the CMSSW_10_4_X_Patatrack branch, as of the
CMSSW_10_4_0_pre3_Patatrack, on top of the regular CMSSW_10_4_0_pre3 release.

### CODE REVIEW

**Comment by fwyzard** [comment]
This PR should is currently identical to #25353 , but it will not be automatically updated with further Patatrack developments.
On the other hand, this branch can be rebased to fix conflicts with the master, and to show which individual PRs have already been merged.

**Comment by fwyzard** [comment]
hold

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
Your PR is unmergeable. Please have a look and possibly rebase it.

**Comment by fwyzard** [comment]
@makortel, can I ask your help to fix the conflict in `Validation/RecoTrack/python/TrackValidation_cff.py` ?

**Comment by makortel** [comment]
I'll take a look.

**Comment by makortel** [comment]
@fwyzard The conflict is caused by #25346 that was merged after 10_4_0_pre3. The same was included in patatrack side on https://github.com/cms-patatrack/cmssw/pull/199, but required a bit different treatment because of some earlier differences in `TrackValidation_cff.py`. I'm not sure if there is much else to do than rebase on top of CMSSW_10_4_X_2018-12-02-0000 or later, or wait for 10_4_0_pre4.

The rebase itself is straightforward (for all conflicts pick patatrack version), I put it here for completeness
https://github.com/makortel/cmssw/commit/7b1df19bbb7281bb0749884eddc781cec122b05b
(on top of CMSSW_10_4_X_2018-12-11-1100)

**Comment by fwyzard** [comment]
Thanks, I will merge with pre4 and take the Patatrack version for `Validation/RecoTrack/python/TrackValidation_cff.py`.

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by davidlange6** [comment]
Your PR is unmergeable. Please have a look and possibly rebase it.

**Comment by fwyzard** [comment]
Will open a new PR for 10.5.x once the Patatrack branch has stabilised.

**Pull request closed without merging**
