### PR TITLE
Update GEM Offline DQM, backport to CMSSW_11_2_X

### PR DESCRIPTION
**Pull request by seungjin-yang**
#### if this PR is a backport please specify the original PR and why you need to backport that PR:
Backport of https://github.com/cms-sw/cmssw/pull/33031 to CMSSW_11_2_X. This backport is needed for MWGR#3.

@jshlee @szaleski

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by seungjin-yang** [comment]
The variable name change was incomplete. phase2_GEM.toModify was taking the old variable name (etaHigh) as an named argument. The new commit fixed it and is tested with workflow 33811.0, which is `TenMuExtendedE_0_200+2026D74`.

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
There seems to be Clang warnigns to fix:
DQMOffline/Muon/src/GEMEfficiencyAnalyzer.cc
/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_2_X_2021-03-02-1100/src/DQMOffline/Muon/src/GEMEfficiencyAnalyzer.cc:583:26: warning: moving a temporary object prevents copy elision [-Wpessimizing-move]
/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_2_X_2021-03-02-1100/src/DQMOffline/Muon/src/GEMEfficiencyAnalyzer.cc:585:26: warning: moving a temporary object prevents copy elision [-Wpessimizing-move]
/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_2_X_2021-03-02-1100/src/DQMOffline/Muon/src/GEMEfficiencyAnalyzer.cc:622:22: warning: moving a temporary object prevents copy elision [-Wpessimizing-move]

**Comment by seungjin-yang** [comment]
@jfernan2 I removed abused move semantics as I did in PR to master https://github.com/cms-sw/cmssw/pull/33031. By the way, I have a question about the code quality check. When I ran `scram build code-checks`, it threw one `-Wpessimizing-move` warning. However, `scram build COMPILER='llvm compile'` threw more same warnings. Is the latter command is more strict? If not, do I need to run both commands? Thanks In Advance.

**Comment by jfernan2** [comment]
I do not know the answer to your question, I let the experts to comment.
Triggering the tests again to see if your update works

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
please test
It looks fine but triggering tests again to see if Failed Tests: RelVals-INPUT is overcome

**Comment by jfernan2** [comment]
+1

**Comment by seungjin-yang** [comment]
> I do not know the answer to your question, I let the experts to comment.
> Triggering the tests again to see if your update works

@jfernan2 Thank you so much!

**Comment by qliphy** [comment]
+1

**Pull request merged**
