### PR TITLE
Miscellaneous graphical payload inspector fixes

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

Miscellaneous graphical improvements for the plots displayed by the Payload Inspector

#### PR validation:

Private

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A
cc: @tvami

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by tvami** [comment]
+db

**Comment by qliphy** [comment]
+1

**Pull request merged**
