### PR TITLE
ECAL skip GPU unpacking of the rest of the block if a bad block is detected - 132x

### PR DESCRIPTION
**Pull request by thomreis**
#### PR description:

Skip the GPU unpacking of the rest of the block if a bad block is detected in one thread. This behaviour matches the one of the CPU unpacker.

Backport of #42301

#### PR validation:

No crashes with integrity errors observed in runs 367771, 368547, and 368724 in https://github.com/cms-sw/cmssw/issues/39568. Passes WF 12434.512

### CODE REVIEW

**Comment by thomreis** [comment]
type ecal

**Comment by thomreis** [comment]
enable gpu

**Comment by thomreis** [comment]
backport of #42301

**Comment by thomreis** [comment]
please test

**Comment by perrotta** [comment]
+1

**Pull request merged**
