### PR TITLE
[Backport 14.1.X] Refine RPCDigis Validation histograms

### PR DESCRIPTION
**Pull request by jhgoh**
#### PR description:
This is a backport of #45702 to 14.1.X release cycle, which is also a follow-up PR of #45029.

#### PR validation:

- `runTheMatrix.py -l 12434.0` OK
- `scram b code-checks` OK
- `scram b code-format` OK

(already tested with the CMSSW_14_1_0_pre6, wf 13034.0, 12434.0 and 29634.0  in the original PR)

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

This is a backport of #45702, which was originally proposed for 14.1.X but it eventually went to 14.2.X cycle.
We'd like to have the same set of validation plots across the releases in the further relval campaigns.

@mileva @mrcthiel

### CODE REVIEW

**Comment by tjavaid** [comment]
backport of #45702

**Comment by tjavaid** [comment]
please test

**Comment by tjavaid** [comment]
+1

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
