### PR TITLE
HCALDQM: Run3 era, add compatibility for new uTCA HO (10_6_X)

### PR DESCRIPTION
**Pull request by DryRun**
#### PR description:
Some mandatory updates for HCAL DQM to run on the upgraded detector (HB and HO). 
- Move online DQM cfgs to use Run3 era.
- More importantly, add crate-FED mapping for HO. Without this, the new HO electronics channels correspond to unknown crates, and HCAL DQM crashes.

#### PR validation:

Ran `runTheMatrix.py -l limited -i all --ibeos` with no problems. Ran online DQM over run 328676.

#### if this PR is a backport please specify the original PR:
https://github.com/cms-sw/cmssw/pull/28484

### CODE REVIEW

**Comment by fioriNTU** [comment]
please test

**Comment by jfernan2** [comment]
@DryRun why do we see changes in Hcal/DigiTask for the Offline Workflows too? Is it due to the modification in Constants.h ?

**Comment by DryRun** [comment]
Hi @jfernan2 - yes, indeed. HCAL has a couple more crates now, so after this update, plots with crate number on the axis will change.

**Comment by jfernan2** [comment]
Thanks @DryRun I understand. However the plots are empty everywhere:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_10_6_X_2019-11-26-2300+59f058/34346/dqm-histo-comparison-summary.html
Please, we need that review in HCAL DQM as we discussed at the last meeting on Friday

**Comment by DryRun** [comment]
@jfernan2 Right, I see that the plots are created for online/offline, but only filled for online... I'll fix that (besides the general HCAL DQM review) in a separate PR, to avoid holding this one up.

**Comment by jfernan2** [comment]
+1

**Comment by silviodonato** [comment]
please test

**Comment by silviodonato** [comment]
+1

**Pull request merged**
