### PR TITLE
Removal of the unused class of SiPixelCPEGenericDBErrorParametrization

### LINKED ISSUE #33: Deprecated EDAnalyzer & esGet in `CalibTracker/SiPixelESProducers`
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-55142a/18684/llvm-analysis/

shows
```
Deprecated API	EventSetupRecord::get function called	/CalibTracker/SiPixelESProducers/src/SiPixelCPEGenericDBErrorParametrization.cc	unknown	53	1	View Report
Deprecated API	inherits from edm::EDProducer,edm::EDFilter,edm::EDAnalyzer, or edm::OutputModule	/CalibTracker/SiPixelESProducers/interface/SiPixelDetInfoFileWriter.h	SiPixelDetInfoFileWriter	28	1	View Report
Deprecated API	inherits from edm::EDProducer,edm::EDFilter,edm::EDAnalyzer, or edm::OutputModule	/CalibTracker/SiPixelESProducers/interface/SiPixelDetInfoFileWriter.h	SiPixelDetInfoFileWriter	28	1	View Report
```

### PR DESCRIPTION
**Pull request by tvami**
#### PR description:

Removal of the unused class of SiPixelCPEGenericDBErrorParametrization. It's been taken over by the PixelCPEGeneric algorithm years ago (about 2008). Please note that the corresponding tag from the GTs have been removed in the past already, this is just the code cleaning part of it.

Edit: 
 * SiPixelDBTest_cfg.py is removed, an improved version of this can be found under `CondTools/SiPixel` 

#### PR validation:

Tested with 
```
runTheMatrix.py -l 11634.0 -j 8
```

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Not a backport and no backport is needed

resolves https://github.com/cms-AlCaDB/AlCaTools/issues/33

### CODE REVIEW

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by ferencek** [comment]
Thanks, @tvami, for going ahead with the cleanup. What about the related CondFormat `SiPixelCPEGenericErrorParm` (https://cmssdt.cern.ch/dxr/CMSSW/search?q=SiPixelCPEGenericErrorParm&case=true)? I guess that one is also no longer actively used and can be removed.

**Comment by tvami** [comment]
Hi @ferencek I remove some of what you are referring to. However there is an AlCa policy not to remove the record definition and registration. I'm not sure what to do with a record that has really never been used in production, we'll discuss this inside AlCa and I'll come back to this tomorrow

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
@ferencek the files under `CondFormats/SiPixelObjects` and `CondFormats/DataRecord/` need to be kept due to the CMS policy about the records in the database. If you prefer I can remove them from ESProducer. Otherwise, I'd keep the PR as it is. Please let me know.

**Comment by tvami** [comment]
> > need to be kept due to the CMS policy about the records in the database
> 
> Is there actually any payload of that type in the database?

Yeah... there is a single tag from 2009: https://cms-conddb.cern.ch/cmsDbBrowser/search/Prod/SiPixelCPEGenericErrorParm
Maybe we should not care about this?

**Comment by mmusich** [comment]
> Maybe we should not care about this?

Is it in any GlobalTag?

**Comment by tvami** [comment]
> > Maybe we should not care about this?
> 
> Is it in any GlobalTag?

Yes, upto CMSSW_7_4_1

**Comment by ferencek** [comment]
> @ferencek the files under `CondFormats/SiPixelObjects` and `CondFormats/DataRecord/` need to be kept due to the CMS policy about the records in the database. If you prefer I can remove them from ESProducer. Otherwise, I'd keep the PR as it is. Please let me know.

Looking at https://cmssdt.cern.ch/dxr/CMSSW/search?q=SiPixelFakeCPEGenericErrorParmESSource&case=true it looks like the `SiPixelFakeCPEGenericErrorParmESSource` .h, .cc, and cfi files can be removed.

**Comment by tvami** [comment]
> > @ferencek the files under `CondFormats/SiPixelObjects` and `CondFormats/DataRecord/` need to be kept due to the CMS policy about the records in the database. If you prefer I can remove them from ESProducer. Otherwise, I'd keep the PR as it is. Please let me know.
> 
> Looking at https://cmssdt.cern.ch/dxr/CMSSW/search?q=SiPixelFakeCPEGenericErrorParmESSource&case=true it looks like the `SiPixelFakeCPEGenericErrorParmESSource` .h, .cc, and cfi files can be removed.

Done

**Comment by tvami** [comment]
Jenkins test pass nicely, no diff found, the SA only has a single warning for the bricked design

**Comment by malbouis** [comment]
+alca

**Comment by tvami** [comment]
> (although some note about it would be nice in the PR description)

I updated the PR description now @slava77

**Pull request merged**
