### PR TITLE
Protection for invalid TSOS in MuonTrajectoryUpdator

### PR DESCRIPTION
**Pull request by 24LopezR**
#### PR description:

This PR addresses https://github.com/cms-sw/cmssw/issues/45035 
Attempts to fix a crash observed when KFUpdator returns an invalid trajectory state on surface.
Whenever this happens, muon trajectory updator skips that recHit.

FYI @francescobrivio @mmusich @mandrenguyen @jfernan2 @rbhattacharya04 

#### PR validation:

Tested successfully in conditions detailed in issue https://github.com/cms-sw/cmssw/issues/45035.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

This PR needs to be backported to 14_0_X.

### CODE REVIEW

**Comment by mmusich** [comment]
@24LopezR can you apply the code-formatting at https://github.com/cms-sw/cmssw/pull/45053#issuecomment-2133266925 ?

**Comment by jfernan2** [comment]
Thanks @24LopezR

**Comment by jfernan2** [comment]
+1

**Comment by mandrenguyen** [comment]
@24LopezR can you prepare a 14_0_X backport please?

**Comment by rappoccio** [comment]
+1

**Pull request merged**
