### PR TITLE
[HGCAL] TICL SimTracksters - backport 11_3_X

### PR DESCRIPTION
**Pull request by felicepantaleo**
#### PR description:
This is a backport of #33318 to 11_3_X
This PR introduces SimTracksters. 
SimTracksters are Tracksters objects containing layerclusters that are associated to the same SimClusters. 
They are run in the HGCal Validation Sequence and kept only in FEVT. 
They will be useful for benchmarking the pattern recognition as they will produce the best possible tracksters directly from simulation. 

#### PR validation:
used wf `23290.0`

### CODE REVIEW

**Comment by felicepantaleo** [comment]
@cmsbuild please test

**Comment by jfernan2** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by felicepantaleo** [comment]
@jpata @srimanob a kind reminder. It's exactly the same branch I used in #33318

**Comment by perrotta** [comment]
backport of #33318

**Comment by jpata** [comment]
+reconstruction
- direct backport of #33318
- no unexpected reco differences (DeepTau nonreproducibility is known, new validation outputs are observed)

**Comment by srimanob** [comment]
+Upgrade

**Comment by silviodonato** [comment]
+1

**Pull request merged**
