### PR TITLE
Enbale TrackTriggerAssociatorClustersStubs in L1TrackTrigger sequence. 

### PR DESCRIPTION
**Pull request by rekovic**
PR 93x.  
Add `TrackTriggerAssociatorClustersStubs` in `L1TrackTrigger` sequence, as done in 
master branch (#22261)

Use:
Needed for L1Trigger studies
With PU 200 it takes ~20sec/ev.  
Too long, prefer not to run offline in post-production,

Note:
*Not* adding products to the EventContent (additional total of 1MB/ev at PU 200).

```

'keep *_TTClusterAssociatorFromPixelDigis_*_*',
'keep *_TTStubAssociatorFromPixelDigis_*_*' 
```

### CODE REVIEW

**Comment by rekovic** [comment]
please test

**Comment by rekovic** [comment]
Atn @sviret, @boudoul, @kpedro88

**Comment by kpedro88** [comment]
assign upgrade

**Comment by kpedro88** [comment]
@rekovic should this change also be made in master (10_1_X)?

**Comment by kpedro88** [comment]
backport of #22261

**Comment by kpedro88** [comment]
+1

**Comment by fabiocos** [comment]
please test

**Comment by rekovic** [comment]
Now, adding to  `SimTrackerFEVTDEBUG` EventContent:

```
outputCommands.extend(cms.untracked.vstring(
'keep *_TTClusterAssociatorFromPixelDigis_*_*',
'keep *_TTStubAssociatorFromPixelDigis_*_*'))
```

**Comment by rekovic** [comment]
please test

**Comment by rekovic** [comment]
Reverted adding products to the EventContent till sorted out in the master branch.
PR is now at what was already passing and approved.  Test again.

**Comment by rekovic** [comment]
please test

**Comment by kpedro88** [comment]
@rekovic PR title change should be reverted also

**Comment by kpedro88** [comment]
+1

**Comment by kpedro88** [comment]
merge

**Pull request merged**
