### PR TITLE
Removed begin/endRun method from AlCaHBHEMuonProducer

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

Part of framework change which will require stream modules to explicitly register to use Run/LuminosityBlock transitions.

#### PR validation:

Code compiles.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
@makortel FYI

**Comment by Dr15Jones** [comment]
please test

**Comment by perrotta** [comment]
+1
- It just removes the possibility to count how many runs had been processed, quite likely not a necessary feature of this code

**Comment by rappoccio** [comment]
+1

**Pull request merged**
