### PR TITLE
dedicated DQM on displacedStandAlone muons

### PR DESCRIPTION
**Pull request by phylsix**
This is a DQM for EXO Double L2 muon trigger reported in JIRA:
https://its.cern.ch/jira/browse/CMSHLT-1727

It's monitoring on **displacedStandAlone** collections instead of **muons**, which serves better for this trigger.

It's monitoring on leading muon's pt(w/ and w/o dxy cut), ptVSLs, pt_variable, eta, phi, dxy,
and subleading muon's pt (w/ dxy cut), pt_variable, eta, phi, dxy.

It's also creating efficiency plots on leading muon's monitorables with DQMEDHarvester.

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by phylsix** [comment]
Hello,

I have tested this commit with `runTheMatrix.py -l 10024.2`, and all tests passed.

Looking at the logs of tests by cmsbuild, it seems the error is showing here:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-22888/27375/runTheMatrix-results/20434.0_TTbar_14TeV+TTbar_14TeV_TuneCUETP8M1_2023D19_GenSimHLBeamSpotFull14+DigiFullTrigger_2023D19+RecoFullGlobal_2023D19+HARVESTFullGlobal_2023D19/step4_TTbar_14TeV+TTbar_14TeV_TuneCUETP8M1_2023D19_GenSimHLBeamSpotFull14+DigiFullTrigger_2023D19+RecoFullGlobal_2023D19+HARVESTFullGlobal_2023D19.log

The error looks pretty complicated to me, I couldn't find any hints traced back to this commit. Can you please take a look at this log file and provide some help? Thanks!


Cheers,
Weinan

**Comment by dmitrijus** [comment]
please test

**Comment by fabiocos** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
