### PR TITLE
Update Vcal Calibration (backport of PR #19181 in 92X)

### PR DESCRIPTION
**Pull request by boudoul**
Contents of this PR:

    Update VCal to electron unit for the phase 1 detector using eras (gains and offsets)
    Allow separate values for layer 1
    Lower the cluster threshold for Layer 1
(see full description in the original PR merged in 93X PR #19181 )
Work done by  @jkarancs 
Adding @veszpv  @tsusa

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
merge

**Comment by Martin-Grunewald** [comment]
Why was this merged so quickly without HLT signing for it?
What emergency does this address?

**Comment by davidlange6** [comment]
You've already approved this weeks ago (in 92x). It was reverted while conditions were being derived

Cheers,
David


On 9 Jul 2017, at 15:25, Martin Grunewald <notifications@github.com<mailto:notifications@github.com>> wrote:


Why was this merged so quickly without HLT signing for it?
What emergency does this address?

**Comment by fwyzard** [comment]
-1

**Comment by fwyzard** [comment]
phase0 vs phase1 should be based on the Era, non on the menu name

**Comment by boudoul** [comment]
Hi Martin-Grunewald , this is to provide the correct calibration (together with the appropriate conditions) for the data taking , discussed at the last ops meeting 
Hi @fwyzard , this PR (as it is ) has been  signed by HLT , even merged in 93x...

**Comment by Martin-Grunewald** [comment]
@davidlange6 
That was then (more than 3 weeks ago). You do know that HLT-menu customisations for the data-taking release are never used online thus have to be inside the HLT menu which needs preparations from my side, so I need some heads-up and coordination of HLT menu update in ConfDb with next 92X release: eg, you could not make a 92X release with this now for online and without changes on the ConfDB side.
Sorry, but I do not understand why #19468 which is signed but does not get integrated, but this one gets integrated without signature. This is not making my job any easier!

**Comment by Martin-Grunewald** [comment]
@fwyzard 
We'll import the phase1 custom changes of this PR into the HLT menu in ConfDB and would then indeed need the customisation only for the GRun2016 menu (as for all the other customisations, as GRun2016 is a 90X menu and no longer updated and thankfully not run online).

**Comment by davidlange6** [comment]
the syntax used in the HLT was either suggested by HLT experts or stated to be "ok" at the time. It sounds like there is now a better way that can be suggested to the pixel team. Maybe it can be made available in the next hours?

As for @19468 - created a mess (thanks to the L1 menu) in 93x - so I want to get data taking going with 926 before taking that risk in 92x (even if I believe all is fine now)

**Comment by fwyzard** [comment]
Hi Martin,
understood, thanks.

OK, as long as we don't need a customisation for the 2017 data taking !

**Comment by Martin-Grunewald** [comment]
David, it is not about the ```customise``` syntax/idea but about having (the time) to coordinate ConfDB and the (next) release; I could have prepared those changes in advance:

Eventually we need a release, as we can not move on the ConfDB to include this but then have no release to go with it (this PR's changes are not backward compatible as far as the python config side is concerned). The timeline for a new release, including possibly (waiting for) other changes (??), is not clear to me.

Anyway, at this stage I have not received communications that this is an emergency and that it needs to be online within the next few hours, so I'll get to the ConfDB side tomorrow, for sure not in the "next few hours".

**Comment by Martin-Grunewald** [comment]
@davidlange6 
Concerning your statement:
```
As for @19468 - created a mess (thanks to the L1 menu) in 93x - so I want to get data taking going with 926 before taking that risk in 92x (even if I believe all is fine now)
```
do you think that there are any issues still left to be sorted out? L1_ZeroBias was fixed and the crashing AlCa module was fixed as well, both in 92X and 93X those PRs have been merged.

**Comment by davidlange6** [comment]
> On Jul 9, 2017, at 4:16 PM, Martin Grunewald <notifications@github.com> wrote:
> 
> David, it is not about the customise syntax/idea but about having (the time) to coordinate ConfDB and the (next) release; I could have prepared those changes in advance:
> 
> Eventually we need a release, as we can not move on the ConfDB to include this but then have no release to go with it (this PR's changes are not backward compatible as far as the python config side is concerned). The timeline for a new release, including possibly (waiting for) other changes (??), is not clear to me.
> 
> Anyway, at this stage I have not received communications that this is an emergency and that it needs to be online within the next few hours, so I'll get to the ConfDB side tomorrow, for sure not in the "next few hours".
> 

ok, sounds like the code as it is now is ok - next step is a release, which should be soon.. Then the fun starts, as both conditions and menu will need to be in sync with the release (as already discussed in ops meetings).  It is not something to push online (or offline) in the next hours as there are too many pieces to fit together

**Pull request merged**
