### PR TITLE
[13_0_X] Use singularity for gridpack generation

### PR DESCRIPTION
**Pull request by stahlleiton**
#### PR description:

Backport of https://github.com/cms-sw/cmssw/pull/44900

### CODE REVIEW

**Comment by bbilin** [comment]
test parameters:

- workflow = 180.1,181.1

**Comment by bbilin** [comment]
please test

**Comment by bbilin** [comment]
different scram arch for gridpack was already tested in the initial branch, triggered the tests in native archs for these CMSSW versions.

**Comment by bbilin** [comment]
@stahlleiton just warned me that these two relvals do not exist in this CMSSW version. We need to revert the test with parameter. Sorry for missing this.

**Comment by mandrenguyen** [comment]
backport of https://github.com/cms-sw/cmssw/pull/44900

**Comment by mandrenguyen** [comment]
test parameters

**Comment by mandrenguyen** [comment]
please test

**Comment by smuzaffar** [comment]
please test relval 514.0

**Pull request closed without merging**
