### PR TITLE
Phase2-hgx155 Get correct geometry for new HGCal IDs

### PR DESCRIPTION
**Pull request by bsunanda**

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by ianna** [comment]
+1

**Comment by fabiocos** [comment]
@bsunanda @kpedro88 could you please clarify?

**Comment by bsunanda** [comment]
subdetId() does not work for the new HGCal geometries because of change in DetId format. This one takes care of using subdetId() method only for other calorimeter objects. Otherwise it was giving wrong (may be null pointer) to geometry objects

**Comment by kpedro88** [comment]
@bsunanda does this solve a different problem than the change in the actual `subdetId()` method in #24609? The modification there seems like it makes the change here unnecessary.

**Comment by bsunanda** [comment]
Yes the subdetId() method change makes this redundant. That change did not occur to me first. But I am stuck with that PR. I do not know how to make that PR pass the test - should one change the constexpr to const? Once that PR can pass and approve I can close this PR

**Comment by bsunanda** [comment]
The change in subdetId() method in PR #24917 is sufficient for this. The changes suggested here is redundant

**Pull request closed without merging**
