### PR TITLE
MET Filter update (port of #10604)

### PR DESCRIPTION
**Pull request by schoef**
Please see #10604

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by schoef** [comment]
Is this error related to this PR?

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/10609	1d4c2b9
- same code as in 74X  and in 75X version (74X was tested additionally with run2 prompt reco setup)
- jenkins tests passed; the diffs are lost though
- relying on 75X/74X: jenkins comparisons there  show no differences in products except for logErrors which are expected to change due to  changes in the running modules

**Comment by slava77** [comment]
@cmsbuild please test
it appears that the filter setup may have gotten broken

**Comment by slava77** [comment]
I removed my +1
this PR needs an update.
The GoodVertexFilter code uses getByLabel without a matching consumes call.
@schoef  Robert, please let me know if you'd be able to take care of this issue.

**Comment by Dr15Jones** [comment]
@slava77 I have a fix for GoodVertexFitter coming in a few minutes.

**Comment by Dr15Jones** [comment]
@slava77 see #10794

**Comment by slava77** [comment]
Thank you, Chris.
I'll wait for the next IB with that PR merged, rerun the tests and put back my +1.

**Comment by slava77** [comment]
hold
I recovered my +1, but we need #10794 to merge before this can go in.

@monttj @mmusich @diguida 
Please take a look, your signatures are needed here.
For the tests, I suggest to rely on the report in https://github.com/cms-sw/cmssw/pull/10609#issuecomment-128682278

**Comment by slava77** [comment]
@cmsbuild please test
CMSSW_7_6_X_2015-08-15-1100 should be OK now

**Comment by schoef** [comment]
@slava77 The 'ProductNotFound' seems not related to the PR.
Let me know if smth is needed from my side.

**Comment by slava77** [comment]
Robert,
no requests from me (RECO).
AlCa and AT signatures are still pending

**Comment by slava77** [comment]
@monttj @mmusich @diguida
please check this one as well
Thank you

**Comment by monttj** [comment]
+1
This is 76X version for #10604 which is already approved.

**Comment by mmusich** [comment]
+1
clean up of `ALCARECODtCalibHI` and `ALCARECODtCalib` configurations.
76X version for #10604 which is already approved.

**Comment by mmusich** [comment]
please test
let's see if the error disappears on a more recent IB

**Pull request merged**
