### PR TITLE
[HCAL] Make sure that trigger towers with abs(ieta)=16 are processed with QIE8 settings in 2018.

### PR DESCRIPTION
**Pull request by matz-e**
Fixes a crash when only the last depth of tower 16 is present.

### CODE REVIEW

**Comment by thomreis** [comment]
please test

**Comment by deguio** [comment]
Hi @matz-e 
is this relevant for 10_0_X and MC production?
thanks.

@christopheralanwest @hatakeyamak  @mariadalfonso

**Comment by matz-e** [comment]
in principle, I think, yes. But I also think that the likelihood of triggering the bug being fixed is quite small.

The bug requires energy deposits/data frames in depth 4 of tower 16 and no energy/data frames for depths 1-3. My guess is that this would mainly occur (with a very small probability — basically energy leaking from 17 -> 16) when using the emulation from RAW with zero-suppression, and as such the  the regular simulation chain should not really be impacted.

Do you want me to file a backport PR for 10_0_X?

**Comment by deguio** [comment]
Hi,
maybe electronic noise in simulation can also trigger the problem?

to be on the safe side I would backport to 10_0_X. we don't want to have unexpected crashes when the MC is submitted.

thanks,
F.

@fabiocos

**Comment by christopheralanwest** [comment]
@deguio Another motivation for the backport is the online and offline DQM. The crash could be triggered by tests in which the laser is fired into the HEM or HEP megatiles in a global run. Such tests are often done to validate the latency of TPs sent to L1.

**Comment by fabiocos** [comment]
@thomreis @rekovic could you please check?

**Comment by fabiocos** [comment]
@thomreis @rekovic could you please check? If we need this in 10_0_X it should be integrated asap. For what I can see the code looks reasonable, but I would like an expert to cross check.

**Comment by nsmith-** [comment]
IMHO these packages could be under HCAL signature and not L1: the interface between calorimeter and trigger responsibility is at the trigger primitive level, both in hardware and software.  This change won't affect that interface.  As the expert on the downstream consumer of these trigger primitives,
+1

**Comment by thomreis** [comment]
+1

The right way around.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
