### PR TITLE
Add a set_prescale() HLT customisation tool

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Add a `set_prescale(...)` HLT customisation tool.

#### PR validation:

None.

### CODE REVIEW

**Comment by fwyzard** [comment]
@missirol @Martin-Grunewald I though we already had something like this somewhere, but I couldn't find it anywhere under `HLTrigger/Configuration`.

**Comment by fwyzard** [comment]
please test

**Comment by missirol** [comment]
+hlt

Differences in outputs of various wfs are due to other PRs tested with this one and not yet in the baseline (e.g. #40464 and #40445). PR tests are not sensitive to this PR, except for checking python syntax.

In the future, we could improve this function adding checks (e.g. on existence of PrescaleService in the process), and supporting wildcards/regex for path names.

**Comment by perrotta** [comment]
+1

**Pull request merged**
