### PR TITLE
[11_0_X] TTStub revision: modernize/update

### PR DESCRIPTION
**Pull request by fabiocos**
#### PR description:

Verbatim backport of #28435 into 11_0_X (cherry-pick of original commits by @mdhildreth )

#### PR validation:

See discussion in #28435

### CODE REVIEW

**Comment by fabiocos** [comment]
backport #28435

**Comment by fabiocos** [comment]
please test

**Comment by jfernan2** [comment]
@fabiocos  do we know why the master version of this PR made no DQM plots changes while this backport has a sensible number of modifications in Phase2 and Run3 samples?

**Comment by fabiocos** [comment]
@jfernan2 because it has included unrelated PRs, see above

**Comment by fabiocos** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

identical to the master version already integrated, by-pass signatures to speed up integration for release build and test

**Comment by kpedro88** [comment]
+upgrade

**Comment by cvuosalo** [comment]
+1

**Comment by rekovic** [comment]
+1

**Pull request merged**
