### PR TITLE
[RFC] remove dependency on afs for getPayloadData script

### PR DESCRIPTION
**Pull request by mmusich**
As requested in https://github.com/cms-sw/cmssw/pull/21417#discussion_r153776820 and https://github.com/cms-sw/cmssw/pull/21266#discussion_r152192952, this PR is meant to distribute the `getPayloadData` script with the release rather than calling it from an afs location. It's a request for comments as I am not completely sure how having the script callable without local checkout is going to affect the client code in `cmsDbBrowser`. 
The script is almost the same as in `/afs/cern.ch/user/c/condbpro/public/BROWSER_PI/getPayloadData.py`, the only modification I made is to provide the functionality to inspect also other DB types other than oracle (e.g. local sqlite files):

```diff
diff --git a/afs/cern.ch/user/c/condbpro/public/BROWSER_PI/getPayloadData.py b/getPayloadData.py
index 96aad99dab8..1ef9ed6fcb5 100755
--- a/afs/cern.ch/user/c/condbpro/public/BROWSER_PI/getPayloadData.py
+++ b/getPayloadData.py
@@ -81,9 +81,14 @@ def deserialize_iovs(db, plugin_name, plot_name, tag, time_type, iovs):
     plot = getattr(plugin_obj, plot_name)()
     output('plot object: ', plot)
 
-    db_name = 'oracle://cms_orcon_adg/CMS_CONDITIONS' if db == 'Prod' else 'oracle://cms_orcoff_prep/CMS_CONDITIONS'
+    if db == "Prod":
+        db_name = 'oracle://cms_orcon_adg/CMS_CONDITIONS'
+    elif db == 'Prep' :
+        db_name = 'oracle://cms_orcoff_prep/CMS_CONDITIONS'
+    else:
+        db_name = db
     output('full DB name: ', db_name)
```
Attn: @ggovi, if you are working on some more sophisticated solution, just let me know and I'll close this PR. 
Thanks

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
please test

**Comment by ggovi** [comment]
Sorry for the late reaction, I'm a bit lost in understanding the use cases of this thing. You should take into account that the password for the direct oracle access is in general not distributed...

**Comment by mmusich** [comment]
Ciao Giacomo @ggovi , see please https://github.com/cms-sw/cmssw/pull/21417#discussion_r154973315

**Comment by mmusich** [comment]
Dear all, as recommended by @ggovi we've changed the connection string to point from oracle to frontier, allowing to use the testing scripts without any special password. In order to do so, I changed `PayloadInspector.cc` by adding the configuration of Frontier Nodes as done in https://github.com/cms-sw/cmssw/blob/master/CondCore/CondDB/test/testFrontier.cpp

**Comment by davidlange6** [comment]
please test

**Comment by ggovi** [comment]
+1

**Comment by davidlange6** [comment]
merge

**Pull request merged**
