### PR TITLE
Enable GEM-CSC and CSC-RPC local trigger with eras

### PR DESCRIPTION
**Pull request by dildick**
This pull request is a clean-up of the CSC trigger customizations:
- Old cscTriggerPrimitiveDigisPostLS1_cfi has been deleted. This may cause incorrectly configured integration tests to crash
- CSC Run2 customizations are rewritten in the form of eras. The performance should not change in Run2
- GEM-CSC triggers enabled in Run3 and Phase2
- CSC-RPC trigger enabled in Phase2

@calabria @jshlee

### CODE REVIEW

**Comment by mulhearn** [comment]
please test

**Comment by dildick** [comment]
I just noticed that I mistakenly dropped certain things in the config. Errors are related to incorrect usage of certain era functions. Will fix it asap

**Comment by dildick** [comment]
A typo was creating all the tests to fail. This is fixed now.

**Comment by dildick** [comment]
@mulhearn Could you run the matrix tests again please?

**Comment by mulhearn** [comment]
please test

**Comment by dildick** [comment]
Comparison with the baseline looks good.

**Comment by mulhearn** [comment]
OK looks good.  @rekovic or I should just quickly check that this does not effect run2 with our L1T integration tests, then I will sign off.

**Comment by dildick** [comment]
@mulhearn @rekovic did you spot any changes in the Run2 L1T integration tests?

**Comment by dildick** [comment]
@mulhearn @rekovic did you spot any changes in the Run2 L1T integration tests?

**Comment by mulhearn** [comment]
Sorry for delay.  No changes.  I'm OK with this.

**Comment by mulhearn** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
