### PR TITLE
[Backport] Make stop/sbottom R-hadrons use the cloud model

### PR DESCRIPTION
**Pull request by tvami**
#### PR description:
See description in https://github.com/cms-sw/cmssw/pull/34459

#### if this PR is a backport please specify the original PR and why you need to backport that PR:
This is a backport of https://github.com/cms-sw/cmssw/pull/34459
and needed for MC production for HSCP particle simulations in UL

cc @tadams16 @carolinecollard

### CODE REVIEW

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by civanch** [comment]
+1

**Comment by qliphy** [comment]
type bugfix

**Comment by qliphy** [comment]
+1

**Comment by tvami** [comment]
Hi @qliphy is there a plan for a patch in 10_6_X in which this can go to?

**Comment by qliphy** [comment]
@tvami   How urgent is that?

@cms-sw/xpog-l2 @rappoccio

**Comment by tvami** [comment]
> @tvami How urgent is that?
It's not super urgent, we'd just like to understand what the plans are, if there is some time when it would be best to plug this in.

**Comment by rappoccio** [comment]
We should probably discuss at the ORP meeting Tuesday. Are there plans for imminent papers that require this? If so we would need some kind of discussion / request / approval w/ Physics Coordination @arizzi.

**Comment by tvami** [comment]
Hi @qliphy @perrotta I wanted to wait for (the backport of) #34640 to get merged, but since it's going very slowly, maybe it's time for having a new 10_6_X release now that we are after a month of this PR? Is there anything else that's forseen to enter 10_6_X soon?

**Comment by qliphy** [comment]
@tvami   Yes, we will make a 10_6_X this week, which will also include several features from GEN (will report at PPD general this Thursday) and PdmV.

**Pull request merged**
