### PR TITLE
Update input of nanoULremini wf

### PR DESCRIPTION
**Pull request by srimanob**
#### PR description:
Update the input of nanoULremini wf to use real datasets, not a pilot.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:
No need of backporting, as it was done in
https://github.com/cms-sw/cmssw/pull/32618

### CODE REVIEW

**Comment by srimanob** [comment]
test parameters:
[  - ]workflow = 136.8523

**Comment by srimanob** [comment]
Please test

**Comment by mariadalfonso** [comment]
thanks

**Comment by srimanob** [comment]
+upgrade

As we switch the input file, so the note on "different files in step1_dasquery.log" can be ignored.

**Comment by chayanit** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
