### PR TITLE
Added consumes to SiStripBadModuleConfigurableFakeESSource

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

Also use the ESGetToken to which it is associated.

#### PR validation:

Code compiles.
This is a minor technical change.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
Ping. This is the last pull request needed before I can commit a framework change.

**Comment by tlampen** [comment]
+1

**Comment by Dr15Jones** [comment]
@fabiocos if you can get a chance to merge this to master I can restart the test for  #28223 before I leave for CHEP.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
