### PR TITLE
new plots for ECAL DQM

### PR DESCRIPTION
**Pull request by mengleisun**
Add new plots for Ecal calibration status, trigger tower masking status and trigger digi occupancy.

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
I am cleaning up the 76x queue aside from things for analysis workflows. I'm closing this pull request, please make sure the PR is in 80x. Thanks!

**Pull request closed without merging**
