### PR TITLE
L1T - wide window cancel-out parameters in uGMT - 80x

### PR DESCRIPTION
**Pull request by rekovic**
Revert to wide window parameters for uGMT to cancel-out duplicate tracks,
This solves the problem in L1T emulation of high rates of DoubleMu triggers, 
affecting MC production as well. 
The wide window is what is currently being used in data taking.

This reverts commit b387463fb37d52934af8b466a8e0feae14e3d254, 
which had too narrow cancel-out window, and was derived before the EMTF 
neighbouring sector analysis was in place. 

This PR is to be tested and prepared for merging, but will not be signed 
till L1 DPG gives the green light.

### CODE REVIEW

**Comment by rekovic** [comment]
please test

**Comment by rekovic** [comment]
+1

**Comment by fwyzard** [comment]
@davidlange6 this should be the L1 fix we need to start the MC production.

**Comment by davidlange6** [comment]
Yes - its “a” L1 fix needed. As discussed in the XC lets get confirmation that its “the” fix

**Comment by fwyzard** [comment]
As far as I know it's also "the" fix.

**Comment by davidlange6** [comment]
that was not the understanding 5 hours ago.. i’ll start a thread later to confirm as the lack of information flow is a bit annoying

**Comment by rekovic** [comment]
@davidlange6 
This indeed is the fix that we solved the remaining issue with DoubleMuon triggers.
The MC production can start as far as L1T Offline Software is concerned.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
