### PR TITLE
Backport of new pileup jet ID for MiniAOD re-processing

### PR DESCRIPTION
**Pull request by ahinzmann**
Backport of the following PRs:
#10398 jbrands:newOfflinePuID_new
#10730 ahinzmann:fixpuid
#10625 ahinzmann:PUjetIDcleanup76
#10923 ahinzmann:pileupjetiddqm76

They contain a new training of the pileup jet ID with 74 MC.
This is not the final/optimal training, but already better than the 53 training on 74 MC (ROC curves are in #10625). Optimization of a working point for MVAmet is also not yet done, thus it is not configured to be used in MVAmet.

runTheMatrix -l limited works in CMSSW_7_5_X_2015-08-27-2300

@gpetruc this can be included in the MiniAOD processing

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by gpetruc** [comment]
Thanks, I have added it to the table in https://twiki.cern.ch/twiki/bin/view/CMS/MiniAODSpring15pass2 and I'll add the 74X one as soon as I get it.

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/11002	f42c90c
- backport of the listed PRs from 76X is done correctly
- jenkins tests pass and comparisons with baseline show expected behavior:
    - monitored reco products are unchanged
    - DQM plots show differences in cleanedJets distributions (includes ID) and in PU ID distributions of uncleaned jets
- tested locally in CMSSW_7_5_X_2015-08-27-2300 /test area sign583/ on run2 2015B data in 251721 DoubleEG 200 events promptReco with " @standardDQM+@miniAODDQM+@common" DQM pieces included
    - monitored reco products are unchanged; DQM plots show changes in cleaned jet distributions and in PU jet ID variables for uncleaned jets
    - timing of the modules reduces
```
   -1.726185      -0.62%        77.63 ms/ev ->         5.70 ms/ev pileupJetIdEvaluatorDQM
   -0.756911      -0.11%        22.48 ms/ev ->        10.13 ms/ev hwwAnalyzer
   -0.537214      -0.02%         6.72 ms/ev ->         3.87 ms/ev pileupJetIdEvaluatorCHSDQM
   -0.536477      -0.03%         9.38 ms/ev ->         5.41 ms/ev pileupJetId

```
    - memory RSS peak goes down by 58 MB
    - allocated MEM_LIVE after 10 events goes down by 26 MB (from  TMVA::Reader::BookMVA)
    - RECO and AOD outputs are unchanged.     MINIAOD has tiny variation in size of patJets_slimmedJets, which should be from changes in stored values (PU IDs in this case)

**Comment by slava77** [comment]
@monttj @deguio @danduggan please check this PR
Thank you.

**Comment by deguio** [comment]
+1

**Comment by monttj** [comment]
+1

**Comment by slava77** [comment]
@davidlange6 please check this one.
Both 74X and 76X versions are in the release already

**Comment by davidlange6** [comment]
+1

**Pull request merged**
