### PR TITLE
Run3-gex162 Use edm::LogVerbatim instead of cout in Geometry/RPCGeometry

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Use edm::LogVerbatim instead of cout in Geometry/RPCGeometry

#### PR validation:

Use the runTheMatrix test workflows

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by civanch** [comment]
There are many modification in MkFit WF. This cannot be connected with this PR but let us re-test.

**Comment by makortel** [comment]
> There are many modification in MkFit WF. This cannot be connected with this PR but let us re-test.

Likely a symptom of #39803

**Comment by civanch** [comment]
+1

In MkFit WF there is non-reproducibility

**Comment by perrotta** [comment]
+1

**Pull request merged**
