### PR TITLE
rivet with lhe weights

### PR DESCRIPTION
**Pull request by perrozzi**
cherry-picked from https://github.com/cms-sw/cmssw/pull/9899
since the original pr was developed and tested for 74X and succesfully merged to 76X 
I expect to work out of the box also for 75X (I checked and compiles)

### CODE REVIEW

**Comment by perrozzi** [comment]
gentle reminder to check this PR, cherry-picked from #9899

**Comment by covarell** [comment]
+1

**Comment by davidlange6** [comment]
why do we need this for 75x?

**Comment by bendavid** [comment]
This is an analysis-level feature.

**Comment by davidlange6** [comment]
@cmsbuild, please test

**Comment by davidlange6** [comment]
+1

**Pull request merged**
