### PR TITLE
Changes needed for SUSY parameter scans (80x)

### PR DESCRIPTION
**Pull request by bendavid**
Backport of https://github.com/cms-sw/cmssw/pull/13530 for SUSY fastsim production in CMSSW 80x.
(With a strong desire to run some test workflows through mcm+central production sooner than later to discover any unexpected issues with the workflow.)

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by covarell** [comment]
+1

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/13684	06c3c39
- changes in reco-related parts are only to add GenLumiInfoHeader_generator_ to miniAOD outputs; the same as in #13530 
- jenkins tests pass

**Comment by covarell** [comment]
Can this be merged? We have another 81X/80X development which should be re-based after this change. Thanks

**Pull request merged**
