### PR TITLE
Add option to cut H<a+bE+cE*E backport to 12_4_X

### PR DESCRIPTION
**Pull request by bennettgberg**
#### PR description:
Backport to 12_4_X for: https://github.com/cms-sw/cmssw/pull/39762

Adds an option to change the H/E cut to take the form H<a+bE+cE^2 for constants a, b, c.
This will be needed for Egamma objects in upcoming changes to the Scouting trigger.
Default behavior stays unchanged.
- No changes in output
- No external dependencies
- slides presented to TSG on the change in Scouting: https://indico.cern.ch/event/1186562/contributions/4992593/attachments/2489115/4274414/electronScouting_22-08-03.pdf
In particular, slide 10 shows the physics motivation--large increase in low-pT scouting electron signal reconstruction efficiency resulting from changing this cut.

#### PR validation:

Tested with scram b code-checks and scram b code-format. Further tests performed locally showing expected behavior of the code changes--namely, when doAnd is set to true with non-zero values for cut and cutOverE specified, all resulting scouting electrons in the collection obey H < cutOverE*E + cut and the number of these electrons is reasonable.

Tested in CMSSW_12_4_10_patch2 successfully with new 'doAnd' variable set to both True and False.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport to 12_4_X for: https://github.com/cms-sw/cmssw/pull/39762 
Needed for possible testing of new Scouting menu at end of 2022 data-taking.

### CODE REVIEW

**Comment by missirol** [comment]
please test

@bennettgberg , we also need a backport to `12_5_X`, please.

**Comment by missirol** [comment]
backport of #39762

**Comment by missirol** [comment]
+hlt

**Comment by rappoccio** [comment]
+1

backport looks okay.

**Pull request merged**
