### PR TITLE
Modification of the gem21 validation plots' names

### PR DESCRIPTION
**Pull request by gechen**
Modification of the x-axis of global z position plots and the names for all the gem21 plots.

### CODE REVIEW

**Comment by calabria** [comment]
@kpedro88 @jshlee

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by dildick** [comment]
@gechen There are still references to a 3-station GEM system. Can you please fix them? Thanks.

**Comment by gechen** [comment]
@dildick   The validation code is updated, the references to 3-station are corrected, please have a look, thanks.

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
