### PR TITLE
Phase2-hgx355 Provision for the passive layers of HGCal in the V19 version

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Provision for the passive layers of HGCal in the V19 version

#### PR validation:

Tested against overlaps

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by bsunanda** [comment]
@srimanob Please approve this PR

**Comment by srimanob** [comment]
+Upgrade

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
