### PR TITLE
Gkaratha/dqm 3ple muon sos

### PR DESCRIPTION
**Pull request by gkaratha**
Dear experts,

Please find here the new PR with the commends of @davidlange6 . Thanks

### CODE REVIEW

**Comment by mtosi** [comment]
I think you need a PR for the master as well

**Comment by mtosi** [comment]
@cmsbuild , please test

**Comment by gkaratha** [comment]
Dear @mtosi ,

Thanks for the comment. Can I do it from this PR? or should i create anew CMSSW, copy the files and do another PR?

**Comment by mtosi** [comment]
try ;)
if it does not work, then you will need a new branch

**Comment by gkaratha** [comment]
Dear @mtosi @davidlange6 ,
i tried also to pr in master which is cmssw 9_4_X and of course i can not merge. For dqm we need cmssw 9_3_X or 9_4_X? if it the latter i will try to checkout a recent 9_4_X version, copy everything and then pr. thanks

**Comment by davidlange6** [comment]
Closing PR as it is not needed for this release cycle. CMSSW_9_3_X is planned for use only for 2017 GEN-SIM production and HGCal TDR production.

**Comment by mtosi** [comment]
@gkaratha do you have a PR for the master (94x) ?

**Comment by gkaratha** [comment]
Dear @mtosi ,
Yes  here is it: https://github.com/cms-sw/cmssw/pull/20635 . I wrote in the PR a message referring to you and David. Sorry if you did not receive it. Thanks.


Best,
George

**Pull request closed without merging**
