### PR TITLE
reimplement Candidate iterator

### PR DESCRIPTION
**Pull request by VinInn**
Simplify implementation of Candidate's (component) iterator.
There is still a virtual call for each deference (and invocation of Candidate::end)
at least no memory-churn and no requirements on derived classes

No regression observed

### CODE REVIEW

**Comment by davidlange6** [comment]
@cmsbuild, please test

**Comment by VinInn** [comment]
```
An exception of category 'DDException' occurred while
   [0] Processing run: 1 lumi: 2 event: 101
   [1] Running path 'outpath'
   [2] Calling event method for module PoolOutputModule/'out'
   [3] Calling produce method for unscheduled module TtSemiLepHitFitProducerMuon/'hitFitTtSemiLepEvent'
   [4] Calling produce method for unscheduled module PATMuonSelector/'selectedPatMuons'
   [5] Calling produce method for unscheduled module PATMuonProducer/'patMuons'
   [6] Using EventSetup component TransientTrackBuilderESProducer/'' to make data TransientTrackBuilder/'TransientTrackBuilder' in record TransientTrackRecord
   [7] Using EventSetup component GlobalTrackingGeometryESProducer/'' to make data GlobalTrackingGeometry/'' in record GlobalTrackingGeometryRecord
   [8] Using EventSetup component TrackerDigiGeometryESModule/'trackerGeometry' to make data TrackerGeometry/'' in record TrackerDigiGeometryRecord
   [9] Using EventSetup component TrackerGeometricDetESModule/'trackerNumberingGeometry' to make data GeometricDet/'' in record IdealGeometryRecord
Exception Message:
DDVectorGetter: vectors are empty, cannot get array detIdShifts
```

I suggest to freeze tests till this issue is solved (or roll back the offender)

**Comment by slava77** [comment]
@cmsbuild please test

IBs seem healthy now

**Comment by cvuosalo** [comment]
The Jenkins test error seems to be from a missing Python file:

No module named correctionTermsCaloMet_cff
----- End Fatal Exception -------------------------------------------------
Failure using ttSemiLepJetCombMVAComputer_cfg.py: status 90
status = 23040
---> test runtestTqafTopJetCombination had ERRORS

Might there still be a problem in the IB?

**Comment by davidlange6** [comment]
@cmsbuild - please test
That test ran fine in the IB it seems - maybe was a glitch?

**Comment by cvuosalo** [comment]
+1

for [#7617] c43314b15d6150afa6612a4012eb639a8b047d3e

This PR involves minor code simplification of Candidate iterators.
It should not cause observable differences.

Code changes are satisfactory.

Jenkins tests [CMSSW_7_4_X_2015-02-10-0200]
(https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-7617/2492/summary.html):
compilation, unit tests, matrix tests, static checks are all OK.

As expected, there are no significant differences compared to the baseline in the
following:

[alternative-comparisons]
(https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_7_4_X_2015-02-10-0200+7617/5995/alternative-comparisons/)
(after stripping false positives like timer data)

and

[validateJR]
(https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_7_4_X_2015-02-10-0200+7617/5995/validateJR/)

**Comment by monttj** [comment]
Do you have any clues why I am having this kind of error message (*) while compiling?
But the test is approved?

It is being tested at CMSSW_7_4_X_2015-02-11-0200. 

(*)
Traceback (most recent call last):
  File "/afs/cern.ch/cms/sw/ReleaseCandidates/vol1/slc6_amd64_gcc491/cms/cmssw-patch/CMSSW_7_4_X_2015-02-10-0200/src/FWCore/Utilities/scripts/edmCheckClassVersion", line 175, in <module>
    raise RuntimeError("failed to load library '"+options.library+"'")
RuntimeError: failed to load library 'libDataFormatsPatCandidatesCapabilities.so'
Suggestion: You can run 'scram build updateclassversion' to generate src/DataFormats/PatCandidates/src/classes_def_objects.xml.generated with updated ClassVersion
gmake: *** [tmp/slc6_amd64_gcc491/src/DataFormats/PatCandidates/src/DataFormatsPatCandidates/libDataFormatsPatCandidatesCapabilities.so] Error 1
gmake: *** [There are compilation/build errors. Please see the detail log above.] Error 2

**Comment by slava77** [comment]
was the test build complete in your case? Jenkins completed tests including running PAT OK
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-7617/2492/unitTests.log
so, I can only guess a problem with the local (re)build

**Comment by monttj** [comment]
Thank you for the feedback. Yes, it must be a local build problem that I could not understand so far.

**Pull request merged**
