### PR TITLE
Fix DataFormats/Scouting tests on PowerPC

### PR DESCRIPTION
**Pull request by iarspider**
Redo of #41189

### CODE REVIEW

**Comment by iarspider** [comment]
please test for el8_ppc64le_gcc11

**Comment by iarspider** [comment]
please test

**Comment by VinInn** [comment]
adding to the compiler options ```-mfloat128``` It shall compile.
adding  ```-mcpu=power9``` (if our target is power9) will even emit the hardware instructions.
see
https://godbolt.org/z/Mqfh33xs7

**Comment by smuzaffar** [comment]
> adding to the compiler options -mfloat128 It shall compile.

@VinInn , this is coming from `rootcling` . Issue is in root build of llvm see https://sft.its.cern.ch/jira/browse/ROOT-10879  and https://github.com/cms-sw/cmssw/issues/31156 .

**Comment by smuzaffar** [comment]
+core

technical change which fixes unit tests for ppc64le

**Comment by perrotta** [comment]
+1

**Pull request merged**
