### PR TITLE
Run2-hcx150 Correct access to Hcal geometry

### PR DESCRIPTION
**Pull request by bsunanda**
Accessing geometry for Hcal should invoke HcalGeometry rather than CaloCellGeometry

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@ssekmen, @civanch, @mdhildreth, @lveldere Could you review this PR and approve this

**Comment by bsunanda** [comment]
@ssekmen, @civanch, @mdhildreth, @lveldere Could you review this PR and approve this

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
