### PR TITLE
PR 100X l1To2o fixes in EMTF and BMTF

### PR DESCRIPTION
**Pull request by gekobs**
**PR 100X**
This PR contains:
   - PR #20929 
   - PR #22669
   - A small change in fakeEmtfParams_cff.py that allows running on conddb machines at P5.

### CODE REVIEW

**Comment by thomreis** [comment]
please test

**Comment by thomreis** [comment]
@gekobs the PRs linked in the description seem to be the wrong ones.
Is there also a PR to the master branch for this PR?

**Comment by rekovic** [comment]
please test

**Comment by rekovic** [comment]
@gekobs
Thanks.  
(It turns out that this time) You can use the same branch to make a pull request to  10_1_X branch.  
Also, make a change in the introduction 22699 --> 22669.

**Comment by rekovic** [comment]
@gekobs 
We should move the left-over relevant code from fakeEmtfParams_cfi.py into 
L1TriggerConfig/L1TConfigProducers/python/L1TMuonEndCapForestOnline_cfi.py

But let's first have the tests complete.

**Comment by thomreis** [comment]
backport of #22716

**Comment by rekovic** [comment]
This is now tested on top of CMSSW_10_0_0, on the CondDB machines running L1T O2O (in `directory /data/O2O/L1T/v12.1/`) in the offline mode writing to sqlite file. The results are as expected:

- BMTF and OMTF tags are updated to Stage2v1
- Proper masking of DT channels done in BMTF depending if key is cosmics or p-p.

We plan to move `/data/O2O/L1T/v12.1/` into production tomorrow.

**Comment by ggovi** [comment]
+1

**Comment by rekovic** [comment]
+1

**Comment by fabiocos** [comment]
@gekobs after the move to 10_1_X this PR can be closed

**Pull request closed without merging**
