### PR TITLE
Workaround for extra empty bins in MultiTrackValidator histograms with bin labels

### PR DESCRIPTION
**Pull request by makortel**
This PR addresses a problem described in
https://hypernews.cern.ch/HyperNews/CMS/get/dqmDevel/2401.html
i.e. with `ConcurrentMonitorElement` histograms with all bins having a label, additional empty bins appear in a multiple of the number of bins that should exist. As a workaround (I won't call it a fix as the actual origin is not really understood)
* `disableAlphanumeric()` method is added to `ConcurrentMonitorElement()`
  * Calling `TAxis::SetNoAlphanumeric()`
* the `ConcurrentMonitorElement::disableAlphanumeric()` is called in MultiTrackValidator for all histograms with bin labels

following
https://hypernews.cern.ch/HyperNews/CMS/get/dqmDevel/2401/2/1/2/1/1/1/1.html

Tested in CMSSW_10_1_0_pre2, expecting non-labeled empty bins to disappear from MTV histograms with bin labels.

@hajohajo @VinInn

### CODE REVIEW

**Comment by makortel** [comment]
Somehow I would have thought that part of code to have the code checks already applied...

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by dmitrijus** [comment]
+1

**Comment by fabiocos** [comment]
@makortel @dmitrijus I understand that the bunch of null comparisons, concentrated mostly in tracking, comes from histograms with identical content but different treatment of labelling induced by the alphanumeric option switch, right?

**Comment by makortel** [comment]
I don't know the exact definition of "Null Comparisons" of RelMon, but taking a look in random MTV folder
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_10_2_X_2018-04-11-1100+22934/26117/10024.0_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2017_GenSimFull+DigiFull_2017+RecoFull_2017+ALCAFull_2017+HARVESTFull_2017/Tracking_Track_cutsRecoAK4PFJets_trackingParticleRecoAsssociation.html
highlights indeed exactly the histograms whose alphanumeric option was changed (the effect being that the extra empty bins disappear).

**Comment by fwyzard** [comment]
@makortel @dmitrijus why not add the same method to the `MonitorElement` class as well ?

**Comment by makortel** [comment]
@fwyzard I don't object, but with `MonitorElement` one can get the TH1 and operate that. And the particular problem being worked around is (IIUC) somehow specific to `DQMGlobalEDAnalyzer`+`ConcurrentMonitorElement`.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
