### PR TITLE
Change DQM modules to use stage-2 L1T

### LINKED ISSUE #37016: Old L1T tags consumed in DQM modules
This is the main CMSSW version of 
https://github.com/cms-l1t-offline/cmssw/issues/958
now focusing on the DQM packages.

As of now the following packages were identified to use (very possibly) deprecated L1T records. The list might be updated in the future.

Possible Group | Module | Record | Removed Tag
-- | -- | -- | --
DQM/JetMET | METAnalyzer | L1GtTriggerMenuRcd | L1GtTriggerMenu_CRAFT09_hlt
DQM/JetMET | JetAnalyzer | L1GtTriggerMenuRcd | L1GtTriggerMenu_CRAFT09_hlt
DQM/BPH | BPHMonitor | L1GtStableParametersRcd | L1GtStableParameters_CRAFT09_hlt
DQM/Strips | SiStripMonitorCluster | L1GtStableParametersRcd | L1GtStableParameters_CRAFT09_hlt
DQM/Muons | MuonMonitor | L1GtStableParametersRcd | L1GtStableParameters_CRAFT09_hlt

### PR DESCRIPTION
**Pull request by tvami**
#### PR description:

Based on https://github.com/cms-sw/cmssw/issues/37016#issuecomment-1047933761
this PR moves different DQM modules to use stage-2 L1T

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

Resolves https://github.com/cms-sw/cmssw/issues/37016

### CODE REVIEW

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by mmusich** [comment]
seems this is still failing test: https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-9a15df/22589/summary.html

**Comment by tvami** [comment]
@cmsbuild , please abort

**Comment by tvami** [comment]
@mmusich I dont really know what to do with this, ` scram b runtests` ran fine for me. 

The whole TestDQMOfflineConfiguration looks a bit complicated, for example I see 
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-9a15df/22589/unitTests/src/DQMOffline/Configuration/test/TestDQMOfflineConfiguration_10/testing.log
using
```
 auto:run2_data -s DQM --process DUMMY --data --era Run3
```
I dont really understand why we are using a run2 GT with Run-3 era

I cant reproduce this locally either since
```
Failed to open the file '///pool/condor/dir_217322/jenkins/workspace/ib-run-pr-tests/CMSSW_12_3_X_2022-02-22-1100/tmp/004D960A-EA4C-E811-A908-FA163ED1F481.root'
```

**Comment by tvami** [comment]
Furthermore, the same test is saying "We have determined that this is simulation " while using the data GT

**Comment by mmusich** [comment]
> dont really know what to do with this, scram b runtests ran fine for me.

Have you checked out locally `DQMOffline/Configuration` ? Otherwise the test in question won't run. 

> I dont really understand why we are using a run2 GT with Run-3 era

Well, that's up for @cms-sw/dqm-l2 to judge, though let me point out that w/o this PR the test runs fine in IBs.

**Comment by tvami** [comment]
> > dont really know what to do with this, scram b runtests ran fine for me.
> 
> Have you checked out locally `DQMOffline/Configuration` ? Otherwise the test in question won't run.

Ahh I see, I indeed have not checked out the Configuration subfolder.

**Comment by tvami** [comment]
I'll need advice from @cms-sw/dqm-l2 on how to proceed. Even adding the subfolder and running the tests locally I get
```
Config file cmssw_cfg.py created
Task failed.
Traceback (most recent call last):
  File "/afs/cern.ch/user/t/tvami/public/PRsToCMSSW/l1Stage1DQMmodule/CMSSW_12_3_X_2022-02-22-1100/bin/slc7_amd64_gcc10/cmsswSequenceInfo.py", line 532, in <module>
    processseqs(seqset)
  File "/afs/cern.ch/user/t/tvami/public/PRsToCMSSW/l1Stage1DQMmodule/CMSSW_12_3_X_2022-02-22-1100/bin/slc7_amd64_gcc10/cmsswSequenceInfo.py", line 288, in processseqs
    for it in t.get(): # should only be one
  File "/cvmfs/cms-ib.cern.ch/week1/slc7_amd64_gcc10/external/python3/3.9.6-67e5cf5b4952101922f1d4c8474baa39/lib/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/cvmfs/cms-ib.cern.ch/week1/slc7_amd64_gcc10/external/python3/3.9.6-67e5cf5b4952101922f1d4c8474baa39/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/cvmfs/cms-ib.cern.ch/week1/slc7_amd64_gcc10/external/python3/3.9.6-67e5cf5b4952101922f1d4c8474baa39/lib/python3.9/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/afs/cern.ch/user/t/tvami/public/PRsToCMSSW/l1Stage1DQMmodule/CMSSW_12_3_X_2022-02-22-1100/bin/slc7_amd64_gcc10/cmsswSequenceInfo.py", line 272, in <lambda>
    tasks = [stp.map_async(lambda seq: (seq, inspectsequence(seq)), [seq]) for seq in seqs]
  File "/afs/cern.ch/user/t/tvami/public/PRsToCMSSW/l1Stage1DQMmodule/CMSSW_12_3_X_2022-02-22-1100/bin/slc7_amd64_gcc10/cmsswSequenceInfo.py", line 73, in inspectsequence
    raise Exception("cmsRun failed for cmsDriver command %s" % driverargs)
Exception: cmsRun failed for cmsDriver command ['cmsDriver.py', 'step3', '--conditions', 'auto:run2_data', '-s', 'DQM:@ExtraHLT', '--process', 'DUMMY', '--era', 'Run3', '--eventcontent', 'DQM', '--datatier', 'DQMIO', '--customise_commands', 'process.Tracer = cms.Service("Tracer")', '--filein', '/store/data/Run2018A/EGamma/RAW/v1/000/315/489/00000/004D960A-EA4C-E811-A908-FA163ED1F481.root', '-n', '0', '--python_filename', 'cmssw_cfg.py', '--no_exec']
[tvami@lxplus776 test]$ DQM:@miniAODDQM
We have determined that this is real data (if not, rerun cmsDriver.py with --mc)
Traceback (most recent call last):
  File "/cvmfs/cms-ib.cern.ch/nweek-02721/slc7_amd64_gcc10/cms/cmssw/CMSSW_12_3_X_2022-02-21-1100/bin/slc7_amd64_gcc10/edmConfigDump", line 31, in <module>
    print(cmsProcess.dumpPython())
BrokenPipeError: [Errno 32] Broken pipe
entry /store/data/Run2018A/EGamma/RAW/v1/000/315/489/00000/004D960A-EA4C-E811-A908-FA163ED1F481.root
Step: DQM Spec: ['@miniAODDQM']
Config file cmssw_cfg.py created
Traceback (most recent call last):
  File "/cvmfs/cms-ib.cern.ch/nweek-02721/slc7_amd64_gcc10/cms/cmssw/CMSSW_12_3_X_2022-02-21-1100/bin/slc7_amd64_gcc10/edmConfigDump", line 31, in <module>
    print(cmsProcess.dumpPython())
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by mmusich** [comment]
@tvami I think the problem is that once you create the `dict` for changing the `stage2` parameter in the configuration, it expects all the other ones to be defined as well.
e.g.:
```console
cmsrel CMSSW_12_3_X_2022-02-22-2300/src/
cd CMSSW_12_3_X_2022-02-22-2300
cmsenv
git-fetch-user tvami
git checkout l1Stage1DQMmodule
git cms-addpkg DQM/SiStripMonitorClient DQMOffline/Trigger
scramv1 b -j 20
voms-proxy-init -voms cms
runTheMatrix.py -l 138.4
more138.4_PromptCollisions+RunMinimumBias2021+ALCARECOPROMPTR3+HARVESTDPROMPTR3/step2_PromptCollisions+RunMinimumBias2021+ALCARECOPROMPTR3+HARVESTDPROMPTR3.log
```

gives:

```
----- Begin Fatal Exception 23-Feb-2022 09:00:15 CET-----------------------
An exception of category 'Configuration' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing module: class=MuonMonitor label='TrkMu12_DoubleTrkMu5NoFiltersNoVtx_monitoring'
Exception Message:
MissingParameter: Parameter 'l1tAlgBlkInputTag' not found.
----- End Fatal Exception -------------------------------------------------
```

if you add the parameter in the configuration, likely also the `fillDescriptions` needs to be updated....

**Comment by mmusich** [comment]
https://github.com/tvami/cmssw/pull/5 this seems to make it go through.

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
Yay, diffs show no changes, that's great I guess that means these tags were not really used anywhere indeed, otherwise I'd have expected at least some changes in the plots.

**Comment by jfernan2** [comment]
+1

**Comment by tvami** [comment]
@cms-sw/orp-l2 can we please merge this in the 2300 IB? Just so I can remove the tag from the GT in that IB

**Comment by perrotta** [comment]
+1

**Pull request merged**
