### PR TITLE
Bug fixes in TICL

### PR DESCRIPTION
**Pull request by rovere**
#### PR description:

During the review process, 2 bugs were introduced. This PR fixes them.

#### PR validation:

runTheMatrix.py -l limited -i all -j 4 -t 12
(still running)

### CODE REVIEW

**Comment by rovere** [comment]
type bug-fix

**Comment by slava77** [comment]
@cmsbuild please test

A case like this is perhaps a motivation to put TICL in the standard workflow soon.

**Comment by rovere** [comment]
@slava77 I cannot agree more. I'll put that on top of my todo list.
Apologies.

**Comment by kpedro88** [comment]
+upgrade

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/27382	dd28059
- code changes are in line with being bugfixes for the changes made in  #27160
- jenkins tests pass and comparisons with the baseline show no differences in the standard set of tests where TICL is not included in the running workflows
- a test with #27392, which introduces wf 29093.52 with TICL enables passed OK.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
