### PR TITLE
Fix warnings for gcc9 IB for HeterogeneousCore/CUDAServices

### PR DESCRIPTION
**Pull request by mrodozov**
#### PR description:

Fixes warnings for gcc9 IB in HeterogeneousCore/CUDAServices package

#### PR validation:

Builds without warnings

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test

**Comment by Dr15Jones** [comment]
@makortel please review

**Comment by makortel** [comment]
@fwyzard Could you please take a look?

I'm not a huge fan of using `memset` like this. It looks to me that the earlier `nvtxEventAttributes_t eventAttrib = {0};` comes directly from examples by NVIDIA. I wonder if just `nvtxEventAttributes_t eventAttrib = {};` could be sufficient? Or would it be better to explicitly specify all the fields? Or is the `memset` the least-bad compromise?

**Comment by fwyzard** [comment]
What are the original warnings ?

**Comment by mrodozov** [comment]
https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc7_amd64_gcc900/CMSSW_11_0_X_2019-08-18-0000/HeterogeneousCore/CUDAServices

**Comment by Dr15Jones** [comment]
From my reading of https://en.cppreference.com/w/cpp/language/list_initialization, the use of 
`eventAttrib = {0};` will set all other member data to be 0 initialized. So this warning isn't that the values are not set, it is that the values are not explictly set. `eventAttrib = {};' will generate the exact same code and may avoid the extra warning.

**Comment by fwyzard** [comment]
This seems like a recurrent GCC bug (see for example (bugzilla#53119)[https://gcc.gnu.org/bugzilla/show_bug.cgi?id=53119] and (bugzilla#80454)[https://gcc.gnu.org/bugzilla/show_bug.cgi?id=80454]).

The C++ solution should be to use `nvtxEventAttributes_t eventAttrib = {};` instead of `... = {0};`.

**Comment by mrodozov** [comment]
I checked it and it doesn't have the warnings with the {} initializer, lets go with it ?

**Comment by mrodozov** [comment]
please test for slc7_amd64_gcc900

**Comment by smuzaffar** [comment]
@Dr15Jones this looks good to go

**Comment by Dr15Jones** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
