### PR TITLE
RelValMatrix fix mc for Ecal Alcareco

### PR DESCRIPTION
**Pull request by shervin86**
adding AlCaEle to 2015 RECO step for MC:
ZEE, WE and TTbar samples have a RECOAlCaEle step instead of RECO, where the AlCa paths have been added.
The same for the corresponding 13TeV samples.
Ecal electron AlCa paths have been removed from the step4.
@franzoni @mmusich @diguida please double check eventual mistakes.

The following runTheMatrix have been tested:
runTheMatrix.py -j 5 -t 2 -l 25,26,29,1325,1326,1329

The results is:
25.0_TTbar+TTbar+DIGI+RECOAlCaEle+HARVEST+ALCATT Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Wed May 27 18:33:36 2015-date Wed May 27 18:16:48 2015; exit: 0 0 0 0 0
26.0_WE+WE+DIGI+RECOAlCaEle+HARVEST Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED  - time date Wed May 27 18:32:42 2015-date Wed May 27 18:16:48 2015; exit: 0 0 0 0
29.0_ZEE+ZEE+DIGI+RECOAlCaEle+HARVEST Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED  - time date Wed May 27 18:32:37 2015-date Wed May 27 18:16:53 2015; exit: 0 0 0 0
1325.0_TTbar_13+TTbar_13+DIGIUP15+RECOUP15AlCaEle+HARVESTUP15+ALCATT+MINIAODMCUP15 Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-FAILED Step5-NOTRUN  - time date Wed May 27 18:37:59 2015-date Wed May 27 18:16:56 2015; exit: 0 0 0 0 16640 0
1326.0_WE_13+WE_13+DIGIUP15+RECOUP15AlCaEle+HARVESTUP15+MINIAODMCUP15 Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Wed May 27 18:35:27 2015-date Wed May 27 18:16:58 2015; exit: 0 0 0 0 0
1329.0_ZEE_13+ZEE_13+DIGIUP15+RECOUP15AlCaEle+HARVESTUP15+MINIAODMCUP15 Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Wed May 27 18:47:49 2015-date Wed May 27 18:32:40 2015; exit: 0 0 0 0 0
6 6 6 6 3 0 tests passed, 0 0 0 0 1 0 failed

The AlCaTT is failing as you can see:

----- Begin Fatal Exception 27-May-2015 18:37:38 CEST-----------------------
An exception of category 'ProductNotFound' occurred while
   [0] Processing run: 1 lumi: 1 event: 8
   [1] Running path 'pathALCARECOHcalCalIsoTrk'
   [2] Calling event method for module AlCaIsoTracksProducer/'IsoProd'
Exception Message:
Principal::getByToken: Found zero products matching all criteria
Looking for type: trigger::TriggerFilterObjectWithRefs
Looking for module label: hltL1sL1SingleJet68
Looking for productInstanceName: 

   Additional Info:
      [a] If you wish to continue processing events after a ProductNotFound exception,
add "SkipEvent = cms.untracked.vstring('ProductNotFound')" to the "options" PSet in the configuration.

The issue is not solved. Looking at the RelVal I spotted an error that I corrected in the last commit:
I have added an ALCATT for 13TeV and replaced in TTbarUp15 the ALCATT with the newly created ALCATTUp15 (I don't know who are the consumer of that and why this has not been spotted before)

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by franzoni** [comment]
+ step3DefaultsAlCaEle
  do we need to run those alca producers also in the runI relvals ? What do we get out of that
  (keep in mind: no 8 TeV relvals MC are produced as of ~1 y ago)

+ step3Up2015DefaultsAlCaEle50ns
  it's used nowhere that I can find. Why adding it ?

+ ALCATT => ALCATTUp15
  what you've done restores consistency between the ALCA step and the RECO step
  I don't know the full logic behind the failure caused by the HCAL missing product.
  Note that, whenever an ALCA path is introduced, all all run: the one which is introduced is in addition given an output module
  (hence no surprise that HCAL iso track comes about even though not specifically part of the cmsDriver)

  Assuming that you / ECAL DPG will look at the content of the alcarecos relevant for you, solving a crash restoring consistency is good enough.

  Note (this is a note to self for PdmV): it makes no sense to have ALCARECO produce parly in the RECO step (as we want them to be)
  partly in a separate step. And, also the other ALCA steps need be sanitized as you did with ALCATT.

**Comment by shervin86** [comment]
- step3DefaultsAlCaEle
    is used in 25.0 TTbar that is used by cmsbuild to in the checks for accepting PRs
 - step3Up2015DefaultsAlCaEle50ns I can check, but I put that for consistency with step3Up2015Defaults50ns

**Comment by franzoni** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Comment by shervin86** [comment]
Dear all,
should I prepare a PR for 74X to backport this one?

**Pull request merged**
