### PR TITLE
integrate the fast multifit for HLT in 740pre5, yet not using the DB inp...

### PR DESCRIPTION
**Pull request by emanueledimarco**
...uts.

The default behavior is the same as before, so no change is expected. The fast version of the local reconstruction will be triggered by changing the parameters doPrefitEB and doPrefitEE via the HLT menu.

### CODE REVIEW

**Comment by emanueledimarco** [comment]
@argiro @bendavid @fwyzard @gennai @matteosan1 @cerminar This is an intermediate PR in 7.4.X branch integrating the fast multifit version for the HLT, in order to have it in an earlier IB of 7.4.X than the last open pre7. 

It still uses the inputs from python, not being dependent on the new payloads containing ECAL templates, that will be pushed when the GT will be ready.

**Comment by fwyzard** [comment]
@cvuosalo, @slava77, apologies, but I have to ask you if you could test and sign this as quickly as possible: we need to have it in an IB to migrate the HLT 25ns menu to the fast multifit method .

**Comment by fwyzard** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
I don't see any differences in DQM or direct-fwlite comparisons in the short tests done by jenkins.
Is this expected?
If so, please update the description of the PR to mention that the added feature is not enabled and no changes are expected.

**Comment by emanueledimarco** [comment]
@slava77 Yes, it is expected. The PR contains the code and the necessary switches to enable the "fast version" for the HLT: the default parameters correspond to the pre-PR configuration and will be changed directly via the HLT menu. I am updating the description of the PR.

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/7441	10a9446
jenkins confirms no differences as expected
the code looks OK, the technical performance evaluation will happen when it is enabled

**Pull request merged**
