### PR TITLE
Override split level in miniaod 92X version

### PR DESCRIPTION
**Pull request by arizzi**
This is the same of  #19680, but for 92X

### CODE REVIEW

**Comment by slava77** [comment]
this has no utility for 92X: there are no new features useful for physics studies etc.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
backport of #19680

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/20037	2312220
- somewhat trivial backport: the same topic branch/same commit is used as the recently signed off (not yet merged as of Aug 3) version in 93X
- jenkins tests pass

this PR only changes the stream out settings and should be straightforward to apply in the MCv1 and the prompt reco.

**Comment by davidlange6** [comment]
merge

**Pull request merged**
