### PR TITLE
Add combMVA to bTag DQM

### PR DESCRIPTION
**Pull request by pablodecm**
combMVA will be one of the POG supported taggers for Run 2 possible changes
between releases have to be monitored. Because the bTagGenericAnalysisBlock config
is used only a python configuration has to be modified.

I run several tests (FullSim, Data and FastSim) with the runTheMatrix.py script and everything
seem to work as expected.

This changes have to be backported to 75X and 74X as soon as possible.

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1

**Comment by deguio** [comment]
please test

**Comment by davidlange6** [comment]
+1

**Pull request merged**
