### PR TITLE
Pr l1t tsg v5 alg data cond 81x

### PR DESCRIPTION
**Pull request by mulhearn**
Updates for CondFormats, DataFormats, and Algorithm updates that bring L1T up-to-date with L1T TSG v5.

Will not pass tests until the data PRs are merged:
- cms-data/L1Trigger-L1TCalorimeter#9
- cms-data/L1Trigger-L1TGlobal#3

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by mulhearn** [comment]
(Will not past tests until the data PRs are merged)

**Comment by Martin-Grunewald** [comment]
Well, they are merged....

**Comment by mulhearn** [comment]
please test with cms-sw/cmsdist#2238

**Comment by mulhearn** [comment]
Can someone help me with syntax here.  I don't see problem.  ("Cannot find <working link>") !?

**Comment by davidlange6** [comment]
i guess it looks for open prs - so now we wait for the IB to come available to test instead.

**Comment by mulhearn** [comment]
please test

**Comment by mulhearn** [comment]
This one is superseded.

**Pull request closed without merging**
