### PR TITLE
"Update disp mu mu producer (11.1.x)"

### PR DESCRIPTION
**Pull request by jsalfeld**
…ducer in sequence optional

#### PR description:

This is a back port of PR  #32044 
https://github.com/cms-sw/cmssw/pull/32044

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by fwyzard** [comment]
Can you change the PR title to "Update disp mu mu producer (11.1.x)" ?

**Comment by Martin-Grunewald** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Comment by jsalfeld** [comment]
The latest commits introduce Run3 scouting dataformats and the legacy dataformats are left unchanged. The Scouting producers are changed to produce the Run3 scouting dataformats. The latter means, that the HLT configurations using these producers will by default produce Run3 scouting dataformats in the releases where these changes are applied.

In addition there are 3 small improvements to the Egamma scouting part as was suggested by the EGamma team:
1.) HoverE is now actually H/E rather that H only, and the cut inside the producer is removed
2.) instead of Deta, we store DetaSeed
3.) we add the detId for the cluster seed

**Pull request merged**
