### PR TITLE
fix for Beam Spot txt file mess-up

### PR DESCRIPTION
**Pull request by rmanzoni**
fwd port of https://github.com/cms-sw/cmssw/pull/20102

### CODE REVIEW

**Comment by arunhep** [comment]
please test

**Comment by slava77** [comment]
@rmanzoni 
please clarify how the earlier version was tested, just to be sure that this update is the final fix for this.
Was this PR tested already in the online environment where the beam spot jobs run? (assuming we do not need a release first to make the test).

**Comment by rmanzoni** [comment]
hi @slava77 
it was certainly tested in a number of different scenarios, but clearly not all.
We need to recollect and see whether the validation procedure that we followed does not cover all possible cases.
This may take a moment, as I need input from Giovanni too.

**Comment by arunhep** [comment]
@slava77 just to let you know the fix provided here has been integrated in online DQM as a PR on the top of 9.2.8 and it has fixed the issue in Run 300785 around LS 782 :  see this : https://cmsweb.cern.ch/dqm/online/start?runnr=300785;dataset=/Global/Online/ALL;sampletype=online_data;filter=all;referencepos=overlay;referenceshow=customise;referencenorm=True;referenceobj1=refobj;referenceobj2=none;referenceobj3=none;referenceobj4=none;search=;striptype=object;stripruns=;stripaxis=run;stripomit=none;workspace=Everything;size=M;root=BeamMonitor/BeamSpotProblemMonitor/FitFromScalars;focus=BeamMonitor/BeamSpotProblemMonitor/FitFromScalars/BeamSpotStatus_lumi_all;zoom=yes;

**Comment by arunhep** [comment]
+1

**Comment by perrotta** [comment]
please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/20103	7ef3a00
- removes sequential call of file open -> [write] -> function call {open -> write} for the same file; the issue is present in special beam spot monitoring/calibration workflows online.
- jenkins tests pass

**Comment by lpernie** [comment]
+1

**Comment by davidlange6** [comment]
merge

**Pull request merged**
