### PR TITLE
HLT menu development for `12_4_X` (7/N) [`12_5_X`]

### PR DESCRIPTION
**Pull request by missirol**
#### PR description:

Development of HLT menus for `CMSSW_12_4_X`.

This is the PR for the `master` branch, which will then be backported to `12_4_X` (the latter is the release cycle currently used for HLT-menu development for Run 3).

Includes the integration of the following JIRA tickets.

  - [CMSHLT-2312](https://its.cern.ch/jira/browse/CMSHLT-2312) (part 2): [MUO] renaming of muon-isolation modules
  - [CMSHLT-2418](https://its.cern.ch/jira/browse/CMSHLT-2418) (part 2): [EXO] added backup seeds to L1T-MET-seeds module
  - [CMSHLT-2420](https://its.cern.ch/jira/browse/CMSHLT-2420): [EXO] set PS=100 for two `HLT_DiPhoton10sminlt` triggers
  - [CMSHLT-2426](https://its.cern.ch/jira/browse/CMSHLT-2426): [TSG] updated list of backup L1T-MET seeds (e.g. `L1_ETMHF{130,140}`)
  - [CMSHLT-2427](https://its.cern.ch/jira/browse/CMSHLT-2427): [HIG] fix for PNET-AK8 outputs in EventContent of HLTMonitor stream
  - [CMSHLT-2408](https://its.cern.ch/jira/browse/CMSHLT-2408): [BTV] removal of disabled DeepJet triggers from HLTMonitor PD
  - [CMSHLT-2428](https://its.cern.ch/jira/browse/CMSHLT-2428): [TSG] addition of Scouting Path seeded by Muon PD
  - [CMSHLT-2431](https://its.cern.ch/jira/browse/CMSHLT-2431): [TSG] reorganisation of Streams for `Muon`, `JetMET` and `ReservedDoubleMuonLowMass` PDs
  - [CMSHLT-2434](https://its.cern.ch/jira/browse/CMSHLT-2434): [TSG] updated settings of `FedRawDataInputSource`
  - [CMSHLT-2435](https://its.cern.ch/jira/browse/CMSHLT-2435): [TSG] removal of the "1.7 to 0.6e34 No Parking" PS column
  - [CMSHLT-2373](https://its.cern.ch/jira/browse/CMSHLT-2373): [MUO] added new `Mu50_L1SingleMuShower` trigger with PS=0
  - [CMSHLT-2440](https://its.cern.ch/jira/browse/CMSHLT-2440): [TSG] halved HLT PS of 4 `HLT_Mu` control triggers
  - [CMSHLT-2442](https://its.cern.ch/jira/browse/CMSHLT-2442): [TSG] set PS=0 for `HLT_Ele28_WPTight_Gsf`

#### PR validation:

TSG tests.

#### If this PR is a backport, please specify the original PR and why you need to backport that PR. If this PR will be backported, please specify to which release cycle the backport is meant for:

`CMSSW_12_4_X`

### CODE REVIEW

**Comment by missirol** [comment]
enable gpu

**Comment by missirol** [comment]
please test

**Comment by missirol** [comment]
The GPU tests weren't able to start in the last 2 days.

@smuzaffar , could you please check if this is expected, or if something is stuck?

**Comment by smuzaffar** [comment]
@missirol , no idea what had happened to previous gpu relval job. I have restarted the gpu tests now

**Comment by missirol** [comment]
> I have restarted the gpu tests now

thanks, @smuzaffar !

**Comment by missirol** [comment]
+hlt

 - differences in outputs of PR tests are in line with updates to the HLT GRun menu

**Comment by perrotta** [comment]
+1

**Pull request merged**
