### PR TITLE
Add new configuration options to CloseByParticleGun (backport)

### PR DESCRIPTION
**Pull request by OzAmram**
Backport of #45515 and older #44008 to 14_0_X release cycle 

Functionality needed for upcoming MC production that we do not wish to delay for 14_1_0 release 

Description from #45515 

> This PR adds new functionality to the CloseByParticleGun, specifically the ability to logarithmically space the energy distribution and to specify the particle location based on R and eta. These developments are done in support of upcoming sample generation of HGCal simulations for ML4Sim R&D

> Also promoted previous LogErrors related to inconsistencies of the configuration parameters into exceptions

@kpedro88

### CODE REVIEW

**Comment by kpedro88** [comment]
please test

**Comment by OzAmram** [comment]
Sorry forgot to update the configuration of matrix commands in in the first commit

**Comment by kpedro88** [comment]
please test

**Comment by kpedro88** [comment]
@cms-sw/generators-l2 please check

**Comment by bbilin** [comment]
+1

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
