### PR TITLE
DQM HLT path fixes (SUSYBSM)

### PR DESCRIPTION
**Pull request by jolange**
During development of #13148 we realized that no efficiencies were calculated/stored for most SUSYBSM HLT DQM modules, though this was included in the postprocessing/harvesting steps.

In most cases this was a simple mismatch of path specifications: in one place with and in the other without the `_v` suffix.

@olivito: FYI

### CODE REVIEW

**Comment by jolange** [comment]
I have rebased these changes, since some of the paths were changed in 0e79219. This introduced two other mismatches that I fixed.

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
