### PR TITLE
HLT development incl. use of v4 of L1T (81X)

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
HLT development incl. use of v4 of L1T (81X)
This PR includes #13701 as that one is still not integrated!

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by perrotta** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by Martin-Grunewald** [comment]
@Dr15Jones, @fabozzi, @rekovic, @srimanob, @hengne, @mulhearn  
This PR is replacing #13701 already signed by you, so please re-sign this one!

**Comment by Dr15Jones** [comment]
+1

**Comment by fabozzi** [comment]
+1

**Comment by davidlange6** [comment]
@Martin-Grunewald @mulhearn @fwyzard - so in hopes of actually using the new menus, I tried about the relval2016 HLT menu on top of the last IB plus the L1 PR that is now integrated - it seems that we miss also some unpackers for the L1 that the HLT relies on? is there another PR/commit that I can pick up, or do I need an updated GT with an appropriate L1 menu?

%MSG-e L1T:  L1TRawToDigi:hltGtStage2Digis 01-Apr-2016 13:37:28 CEST  Run: 1 Event: 1
Cannot unpack: no FEDRawDataCollection found
%MSG
%MSG-e L1T:  L1TRawToDigi:hltCaloStage2Digis 01-Apr-2016 13:37:28 CEST  Run: 1 Event: 1
Cannot unpack: no FEDRawDataCollection found
%MSG
%MSG-e L1T:  L1TRawToDigi:hltGmtStage2Digis 01-Apr-2016 13:37:28 CEST  Run: 1 Event: 1
Cannot unpack: no FEDRawDataCollection found
%MSG
%MSG-w HLTL1TSeed:  HLTL1TSeed:hltL1sSingleJet180IorSingleJet200  01-Apr-2016 13:37:28 CEST Run: 1 Event: 1
 Warning: GlobalAlgBlkBxCollection with input tag InputTag:  label = hltGtStage2Digis, instance =  is empty.
%MSG
%MSG-w HLTL1TSeed:  HLTL1TSeed:hltL1sHTT255IorHTT300 01-Apr-2016 13:37:28 CEST  Run: 1 Event: 1
 Warning: GlobalAlgBlkBxCollection with input tag InputTag:  label = hltGtStage2Digis, instance =  is empty.

followed by a crash retrieving the L1..

**Comment by Martin-Grunewald** [comment]
@davidlange6 
I am using the L1T PR in my tests since many days, together with this PR, and they run without problems. What exactly did you do?

**Comment by davidlange6** [comment]
@Martin-Grunewald - maybe it was fastsim - I just changed all relval25ns to relval2016..

**Comment by davidlange6** [comment]
@Martin-Grunewald - now I checked - its both fast and full sim I did essentially this:

CMSSW_8_1_X_2016-03-31-2300 + 13768 + 13863 

edit Configuration/PyReleaseValidation/python/relval_steps.py 

to replace all "@relval25ns" with "@relval2016" 

then in the short matrix, both 1330 and 135.4 have problems.

**Comment by Martin-Grunewald** [comment]
@davidlange6 
Just changing ```relval25ns``` to ```relval2016``` is not sufficient, you also need to change ```era``` from ```Run2_25ns``` to ```Run2_2106``` This fixes the crash in 1330.
The Fastsim workflow 135.4 does not work because one also needs to insert a ```DIGI2RAW``` in the cmsDriver ```step``` command like this:
```-s GEN,SIM,RECOBEFMIX,DIGI:pdigi_valid,L1,DIGI2RAW,L1Reco,RECO,EI,HLT:@relval2016,VALIDATION:@standardValidation,DQM:@standardDQM```.

The workflows then run without crashing. What remains are error messages due to DQM/VALIDATION not yet updated to stage-2 L1T, and the L1T menu v4 not yet part of the GT. For the L1T menu v4, you can work around that by using GT ```auto:run2_mc_GRun``` instead of auto:run2_mc```.

**Comment by davidlange6** [comment]
Ah right! Thanks. But it sounds like we are missing some pieces to really make this or testable. Will look into that.

Sent from my iPad

On Apr 2, 2016, at 11:40 AM, Martin Grunewald <notifications@github.com<mailto:notifications@github.com>> wrote:


@davidlange6<https://github.com/davidlange6>
Just changing relval25ns to relval2016 is not sufficient, you also need to change era from Run2_25ns to Run2_2106 This fixes the crash in 1330.
The Fastsim workflow 135.4 does not work because one also needs to insert a DIGI2RAW in the cmsDriver step command like this:
-s GEN,SIM,RECOBEFMIX,DIGI:pdigi_valid,L1,DIGI2RAW,L1Reco,RECO,EI,HLT:@relval2016,VALIDATION:@standardValidation,DQM:@standardDQM.

The workflows then run without crashing. What remains are error messages due to DQM/VALIDATION not yet updated to stage-2 L1T, and the L1T menu v4 not yet part of the GT. For the L1T menu v4, you can work around that by using GT auto:run2_mc_GRun instead of auto:run2_mc```.

**Comment by Martin-Grunewald** [comment]
@davidlange6 
Marco's https://github.com/cms-sw/cmssw/pull/13892 should take care of the L1T menu v4 in the GTs!

**Comment by davidlange6** [comment]
ok- have something that at least runs full sim now - thanks - i'll try to clean things up in the (US) day tomorrow and make a PR - but a few things

in step2 - this seems bad?

Begin processing the 2nd record. Run 1, Event 2, LumiSection 1 at 03-Apr-2016 01:57:35.168 CEST
%MSG-w L1T:  L1TRawToDigi:hltCaloStage2Digis 03-Apr-2016 01:57:37 CEST  Run: 1 Event: 2
Cannot unpack: empty L1T raw data (size = 0) for ID 1360. Returning empty collections!
%MSG

in step3 - its just this - which seems like a module we don't want in any case (it should be in raw2digi and then consumed)

%MSG-e L1GlobalTriggerRawToDigi:  L1GlobalTriggerRawToDigi:dqmGtDigis  03-Apr-2016 02:04:05 CEST Run: 1 Event: 10

Error: Pointer after header greater than end pointer.
 Put empty products in the event!
 Quit unpacking this event.
%MSG

**Comment by Martin-Grunewald** [comment]
@davidlange6 

Concerning: ```Cannot unpack: empty L1T raw data (size = 0) for ID 1360. Returning empty collections!``` -- this is fine according to L1T: there is a 2nd calo FED which is filled, and the error message can be ignored in case of size=0 (verbosity had been reduced to at most five times).

Concerning ```L1GlobalTriggerRawToDigi: L1GlobalTriggerRawToDigi:dqmGtDigis``` -- this is running the old stage1 GT unpacker plugin ```L1GlobalTriggerRawToDigi``` which is incorrect to do in the stage-2 world, where one should run the new generic unpacker plugin ```L1TRawToDigi``` configured to unpack GT - ie, an update to DQM/VLIDATION sequence definition is needed.

**Comment by mulhearn** [comment]
This is indeed annoying... putting cleaning up the unpackers to only complain if they are missing essential payloads in the current era on the TODO list for this week.  But no need to wait.

**Comment by mulhearn** [comment]
+1

**Pull request merged**
