### PR TITLE
Add tau pog tags to GTs

### PR DESCRIPTION
**Pull request by tocheng**
#### PR description:

The PR is to PR [28063](https://github.com/cms-sw/cmssw/pull/28063) support tau ID at nanoAOD level. 75 labeled tags are added to data/MC tags to support tau ID calculation. 
No effect on physics performance is expect when testing this PR alone.

GT diffs:
**Data offline GTs**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/110X_dataRun2_v8/110X_dataRun2_v7
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/110X_dataRun2_relval_v8/110X_dataRun2_relval_v7

**Data prompt-like GTs**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/110X_dataRun2_PromptLike_v7/110X_dataRun2_PromptLike_v6
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/110X_dataRun2_PromptLike_HEfail_v7/110X_dataRun2_PromptLike_HEfail_v8
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/110X_dataRun2_PromptLike_HI_v7/110X_dataRun2_PromptLike_HI_v6

**Run-1 MC GTs**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/110X_mcRun1_design_v2/110X_mcRun1_design_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/110X_mcRun1_realistic_v2/110X_mcRun1_realistic_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/110X_mcRun1_HeavyIon_v2/110X_mcRun1_HeavyIon_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/110X_mcRun1_pA_v2/110X_mcRun1_pA_v1

**2015 MC GTs**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/110X_mcRun2_startup_v2/110X_mcRun2_startup_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/110X_mcRun2_asymptotic_l1stage1_v2/110X_mcRun2_asymptotic_l1stage1_v1

**2016 MC GTs**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/110X_mcRun2_design_v3/110X_mcRun2_design_v2
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/110X_mcRun2_asymptotic_v3/110X_mcRun2_asymptotic_v2
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/110X_mcRun2_HeavyIon_v2/110X_mcRun2_HeavyIon_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/110X_mcRun2_pA_v3/110X_mcRun2_pA_v2

**2017 MC GTs**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/110X_mc2017_design_v2/110X_mc2017_design_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/110X_mc2017_realistic_v2/110X_mc2017_realistic_v1

**2018 MC GTs**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/110X_upgrade2018_design_v2/110X_upgrade2018_design_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/110X_upgrade2018_realistic_v6/110X_upgrade2018_realistic_v5
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/110X_upgrade2018_realistic_HI_v5/110X_upgrade2018_realistic_HI_v4

**Run 3 MC GTs**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/110X_mcRun3_2021_design_v4/110X_mcRun3_2021_design_v3
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/110X_mcRun3_2021_realistic_v4/110X_mcRun3_2021_realistic_v3
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/110X_mcRun3_2023_realistic_v4/110X_mcRun3_2023_realistic_v3
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/110X_mcRun3_2024_realistic_v4/110X_mcRun3_2024_realistic_v3

**Run 4 MC GTs**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/110X_mcRun4_realistic_v2/110X_mcRun4_realistic_v1

#### PR validation:
See the description above for the physics validation of the tags. 

In addition, a technical test was performed: runTheMatrix.py -l limited -i all --ibeos

#### if this PR is a backport please specify the original PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by tocheng** [comment]
@cmsbuild please test

**Comment by tocheng** [comment]
@cmsbuild please test

**Comment by tocheng** [comment]
@fabiocos I rebased the commit to the lastest IB 2019-10-15-2300 yesterday. And now there is a unit test error due to alignment which should not be relevant to this PR. Do you have any suggestions? Thanks.

**Comment by christopheralanwest** [comment]
please test with #28063

**Comment by christopheralanwest** [comment]
+1

**Comment by fabiocos** [comment]
@tocheng @christopheralanwest I understand that #28063 is dependent on this PR, but is the opposite true? Do I understand correctly that in this PR new tags are added? And why do we see changes in old run1 tests? What does change in conditions for this old runs?

**Comment by tocheng** [comment]
@fabiocos I don't think this PR depends on #28063 .
The change in run1 is because the deprecated MVA IDs are removed.
See the comments in the PR:
https://github.com/cms-sw/cmssw/pull/28063#issuecomment-543161815

**Comment by fabiocos** [comment]
+1

**Pull request merged**
