### PR TITLE
FastSim: enable noise and beamhalo info

### PR DESCRIPTION
**Pull request by lveldere**
removing some unnecessary fastsim modes

### CODE REVIEW

**Comment by lveldere** [comment]
please test

**Comment by lveldere** [comment]
some issues left,
closing for now

**Comment by lveldere** [comment]
please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/13179	98d9d6a
- changes in the code are in line with the description; the changes affect only FastSim
- jenkins tests pass and comparisons with baseline show no differences in monitored physics objects
- looking at local copies of the jenkins jobs shows no difference in data  workflow output (134.911 checked) and that beam halo and jet association products now show up in the outputs of the fastsim step1 (135.4 checked), consistent with the code changes. The following are added in 
135.4 (ZEE FS) step1
```
recoHcalHaloData_HcalHaloData__HLT.
recoHcalNoiseRBXs_hcalnoise__HLT.
HcalNoiseSummary_hcalnoise__HLT.
recoJet%TorecoTrack%AssociationVector_ak4JetTracksAssociatorExplicit__HLT.
recoEcalHaloData_EcalHaloData__HLT.
```

**Comment by lveldere** [comment]
+1

**Comment by lveldere** [comment]
ping @analysis
thanks

**Pull request merged**
