### PR TITLE
[DO NOT MERGE] Fake change to BuildFile.xml to trigger compilation in cms-bot for LogDebug issue

### PR DESCRIPTION
**Pull request by fabiocos**
#### PR description:

Fake change to test cms-bot behaviour in connection with the issue #29250 

#### PR validation:

It forces the recompilation of all packages where LogDebug issues appear.

### CODE REVIEW

**Comment by fabiocos** [comment]
please test

**Comment by slava77** [comment]
-1

to take it off our review list

**Comment by fabiocos** [comment]
@smuzaffar @silviodonato  ok, in https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-b9c7a8/5321/llvm-analysis/runStaticChecks.log (not directly visible from the links) the list of errors is visible, it is enough to have an addition to https://github.com/cms-sw/cms-bot/blob/master/pr_testing/test_multiple_prs.sh#L702 that parses runStaticChecks.log with something like ```grep "error:"``` and counts the number of instances, showing a warning in the output

**Comment by fabiocos** [comment]
please test with #29283

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
The problem looks gone, as tested independently.

**Pull request closed without merging**
