### PR TITLE
74x Fireworks: fix problem with muon global  track propagation 

### PR DESCRIPTION
**Pull request by alja**
d58e30e2-629e-11e5-8654-fe4bb7c1f970

Path marks from moun inner/outer track position and the last two path mark from muon->globalTrack():
 innerTrack()->innerPosition() (-3.77266,-1.91869,5.69689)https://github.com/cms-sw/cmssw/blob/CMSSW_7_5_X/Fireworks/Muons/src/FWMuonBuilder.cc#L266
 moun innerTrack()->outerPosition() (-87.8516,-1.73888,263.885) https://github.com/cms-sw/cmssw/blob/CMSSW_7_5_X/Fireworks/Muons/src/FWMuonBuilder.cc#L269
 moun outerTrack()->innerPosition() (-112.689,29.4957,585.348)https://github.com/cms-sw/cmssw/blob/CMSSW_7_5_X/Fireworks/Muons/src/FWMuonBuilder.cc#L275
 moun outerTrack()->outerPosition() (-149.12,45.3741,839.739)https://github.com/cms-sw/cmssw/blob/CMSSW_7_5_X/Fireworks/Muons/src/FWMuonBuilder.cc#L279

 fireworks::prepareTrack track.innerOk (-3.77311,-1.9179,5.69697) https://github.com/cms-sw/cmssw/blob/CMSSW_7_5_X/Fireworks/Tracks/interface/TrackUtils.h#L54
 fireworks::prepareTrack track.outerOk (-129.255,35.7668,614.673)https://github.com/cms-sw/cmssw/blob/CMSSW_7_5_X/Fireworks/Tracks/interface/TrackUtils.h#L95

Yuu can see that there 4 reference path from muon inner and outer track position. Before that the globalMuon extra points are added, which resolves in the following path mark order:
TEveTrack 'TEveRecTrackT<float>', number of path marks 6, label -1
  Reference  p: -0.696788 -0.354075 2.260245 Vertex: -3.773114e+00 -1.917895e+00 5.696975e+00 0 Extra:0.000000 0.000000 0.000000
  Reference  p: -0.058421 0.029470 0.185701 Vertex: -1.292555e+02 3.576676e+01 6.146726e+02 0 Extra:0.000000 0.000000 0.000000
  Daughter   p: 0.000000 0.000000 0.000000 Vertex: -3.772659e+00 -1.918688e+00 5.696890e+00 0 Extra:0.000000 0.000000 0.000000
  Daughter   p: 0.000000 0.000000 0.000000 Vertex: -8.785159e+01 -1.738879e+00 2.638853e+02 0 Extra:0.000000 0.000000 0.000000
  Daughter   p: 0.000000 0.000000 0.000000 Vertex: -1.126888e+02 2.949574e+01 5.853483e+02 0 Extra:0.000000 0.000000 0.000000
  Decay      p: 0.000000 0.000000 0.000000 Vertex: -1.491195e+02 4.537413e+01 8.397385e+02 0 Extra:0.000000 0.000000 0.000000

### CODE REVIEW

**Comment by alja** [comment]
The solution for this bug is that we don't add reference points from muon globalTrack if there are already ordered 4 references points from existing inner and outer track position.

Note: Filter muon.pt > 1 GeV does  not help in this case because ordering of path marks is triggered at muon's track pt  threshold > 1GeV which is not reached in this observed case even if muon.pt is more than 1GeV.

**Comment by alja** [comment]
### sorting of path marks in fireworks::prepareTrack
https://github.com/cms-sw/cmssw/blob/CMSSW_7_5_X/Fireworks/Tracks/interface/TrackUtils.h#L54

This sorting is triggered only for pt > 1. Even in this case I see a problem where charge is negative and in case of muon filed change.

I think merging od path marks is impossible and would try to define cases where it has to be used.

**Comment by alja** [comment]
### possible problem with Tracker muon
### similar problem with trackrt muon


This is the second case where path marks are merged from different sources. Here muon specific path marks come from matched muon chambers. I'm concered sorting in case pf pt > 1 with track extra points might not work in some cases.

https://github.com/cms-sw/cmssw/blob/CMSSW_7_5_X/Fireworks/Muons/src/FWMuonBuilder.cc#L275

**Comment by alja** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
