### PR TITLE
[Forwardport] OnlineDQM: uGMT DQM plot improvements CMSLITDPG-466

### PR DESCRIPTION
**Pull request by stahlleiton**
Forwardport of the recent commits done in https://github.com/cms-sw/cmssw/pull/22272

### CODE REVIEW

**Comment by thomreis** [comment]
please test

**Comment by thomreis** [comment]
@dmitrijus @jfernan2 please sign

**Comment by thomreis** [comment]
@dmitrijus @jfernan2 please sign.

**Comment by thomreis** [comment]
@dmitrijus @jfernan2 please sign. We would like to get the open PRs into 10_1.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
