### PR TITLE
[JME, Nano] Add eta and phi of muon-subtracted raw jet for MET type-1 correction consistency

### PR DESCRIPTION
**Pull request by nurfikri89**
#### PR description:

This PR adds the `eta` and `phi` of the muon-subtracted raw jets. These are needed so that the MET type-1 (re-)calculation with NanoAOD will be more consistent with the type-1 calculation done at the `PAT` step.

#### PR validation:

- passes the usual runTheMatrix test: `runTheMatrix.py -l limited -i all --ibeos` with the exception of a few workflows which failed because of missing relval input files.
- passes MiniAOD workflows: `runTheMatrix.py -i all --ibeos  -l 2500.021,2500.022,2500.023,2500.024,2500.031,2500.032,2500.033,2500.034`

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by hqucms** [comment]
please abort

**Comment by hqucms** [comment]
enable nano

**Comment by hqucms** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by hqucms** [comment]
+1

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
