### PR TITLE
bsunanda:Run2-hcx99 Interface change in view of handling special RBX

### PR DESCRIPTION
**Pull request by bsunanda**
Added 2 new functions to HcalTopology class:
bool  withSpecialRBXHBHE() const; True if there are special RBX in the setup for HB/HE
HcalDetId mergedDepthDetId(HcalDetId& id) const; returns the DetId after merging several depths into a new one.

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by slava77** [comment]
@ianna @davidlange6 
this was mentioned as an important step towards plan-1 HCAL implementation

**Comment by ianna** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
