### PR TITLE
[13_2_X] Add 2023 HI scenarios

### PR DESCRIPTION
**Pull request by francescobrivio**
#### PR description:
Verbatim backport of #42493 
This PR adds the scenarios needed in Tier0 for 2023 HI data-taking.
| Era | Scenario | 
| --- | --- |
| `Run3_pp_on_PbPb_2023` | `ppEra_Run3_pp_on_PbPb_2023` |
| `Run3_pp_on_PbPb_approxSiStripClusters_2023` | `ppEra_Run3_pp_on_PbPb_approxSiStripClusters_2023` |

#### PR validation:
See master PR.

#### Backport:
Backport of #42493

### CODE REVIEW

**Comment by francescobrivio** [comment]
backport of #42493

**Comment by francescobrivio** [comment]
urgent

 - supposed to be included in the next 13_2_X release and to be tested in Tier0 with a replay

**Comment by francescobrivio** [comment]
@cmsbuild please test

**Comment by perrotta** [comment]
+1

**Pull request merged**
