### PR TITLE
[101X][L1T][DQMOffline] Normalizing L1 vs offline histograms to bin area (Jets & Energy Sums) 

### PR DESCRIPTION
**Pull request by kreczko**
Backport of #23669

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by kreczko** [comment]
OK, the tests are failing, since I worked off a branch that includes #23478 and #23494.
If it is OK, could we leave this PR until the other two are merged?

**Comment by thomreis** [comment]
+1

**Comment by thomreis** [comment]
please test with #23478,#23494

**Comment by thomreis** [comment]
please test with #23478,#23494

Let's try again.

**Comment by thomreis** [comment]
please test with #23478

**Comment by thomreis** [comment]
please abort test

**Comment by thomreis** [comment]
please test with #23478

**Comment by thomreis** [comment]
Hi @jfernan2 @dmitrijus 
can you please sign this backport PR?

**Comment by andrius-k** [comment]
+1

**Comment by thomreis** [comment]
Hi @kreczko 
since the T0 has moved to the 10_2 release now this PR can be closed.

**Pull request closed without merging**
