### PR TITLE
update of the XML conversion in C++ 

### PR DESCRIPTION
**Pull request by apfeiffer1**
Update of the XML conversion in C++ with an improved, more flexible version.
The C++ module is now using a template function to do the work, which makes writing new converters simpler.
By convention the function name to convert should be "<ObjectTypeName>2xml" so that the dump subcommand of the conddb tool will find the correct function in the plugin of the module.

### CODE REVIEW

**Comment by ggovi** [comment]
+1

**Comment by ggovi** [comment]
@cmsbuild please test

**Comment by apfeiffer1** [comment]
please test again
the missing header file was added.

**Comment by Dr15Jones** [comment]
Please test

**Comment by ggovi** [comment]
+1

**Pull request merged**
