### PR TITLE
reimplement Modifier.toReplaceWith outside of Eras (plus cleanup)

### PR DESCRIPTION
**Pull request by fwyzard**
This includes all the changes from #17410 plus some further cleanup of HLTrigger/Configuration/python/customizeHLTTrackingForPhaseI2017.py .

### CODE REVIEW

**Comment by fwyzard** [comment]
please test

**Comment by silviodonato** [comment]
I tested this PR ~one week ago, and everything was fine. @fwyzard , if you did not plan any other change, you/we can sign it.

**Comment by fwyzard** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
