### PR TITLE
Added DeepCSV path in OnlineDQM for JIRA CMSHLT-1496

### PR DESCRIPTION
**Pull request by JyothsnaKomaragiri**
Added recently approved DeepCSV Pilot path:
https://its.cern.ch/jira/browse/CMSHLT-1496

in OnlineDQM.

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
@JyothsnaKomaragiri 
The backport PR for 92X still needs to be fixed!

**Comment by JyothsnaKomaragiri** [comment]
@Martin-Grunewald, submitting the backport in 92X in few mins.
The conflicts were due to submission of two PRs (by Ye & me) around the same time.

**Comment by Martin-Grunewald** [comment]
tests stuck?

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Comment by mtosi** [comment]
do we have the backport for 92x ?

**Comment by Martin-Grunewald** [comment]
yes, it is called #19836

**Pull request merged**
