### PR TITLE
Phase2-hgx325C Clean the remaining scripts in Validation/HGCalValidation by removing all scenarios except D88, D92, D93

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Clean the remaining scripts in Validation/HGCalValidation by removing all scenarios except D88, D92, D93

#### PR validation:

Tested the modified scenarios

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by emanueleusai** [comment]
type hgcal

**Comment by emanueleusai** [comment]
please test

**Comment by bsunanda** [comment]
The failure is not connected to this PR. The PR only affects a few phase2 scripts and cannot affect file opening error in Run3 scenario

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by rovere** [comment]
Ciao @bsunanda 
the same comments made on #39415 apply here as well.

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by emanueleusai** [comment]
+1

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by emanueleusai** [comment]
+1

- resign

**Comment by perrotta** [comment]
+1

**Pull request merged**
