### PR TITLE
Fix ordering of egamma HLT modules

### PR DESCRIPTION
**Pull request by swagata87**
#### PR description:

Recently phase2 HLT menu abandoned `ConditionalTask` and adopted a fully Sequence-based approach (via  https://github.com/cms-sw/cmssw/pull/44025). It was noticed that, in this process, ordering of some egamma modules got shuffled unintentionally. That was partly fixed by https://github.com/cms-sw/cmssw/pull/44523.
This is a followup PR to further fix the remaining issues, and implement a proper ordering of modules in egamma paths. The ordering is important to keep timing under control. The idea is to run less expensive sequences in the beginning, followed by relevant filters and then then move on to run more expensive sequences. This is what has always been done in egamma, in phase1 and also in phase2 HLT.  

As an example, in HLT_Ele32 path (which has the highest rate among all egamma paths), the following ordering is reintroduced via this PR:  

```
Run L1 sequence
L1 filter    
ECAL and HGCAL local reco + clustering + superclustering
Cut on supercluster ET
Produce ECAL sigmaIEtaIEta, and cut on it 
Produce HGCAL ID variables,  and cut on them  
HCAL local reco
FastJet Sequence (needed for rho correction)
Produce H/E in barrel, cut on that
Produce ECAL isolation, cut on that
Produce HGCAL isolation, cut on that
Run PF clustering in HCAL
Produce HCAL PF cluster based isolation, and cut on that
Run Pixel Match Sequence
Pixel matching related filters
GsfElectron Sequence
Cut on GSF related variables
Produce Track isolation using L1 tracks, and cut on that
Run general tracking
Produce track isolation using HLT tracks, and cut on that
```
#### PR validation:

Phase2 menu runs.

### CODE REVIEW

**Comment by mmusich** [comment]
> The ordering is important to keep timing under control

@swagata87 do you have timing measurements before / after ?

**Comment by mmusich** [comment]
type egamma, bug-fix

**Comment by swagata87** [comment]
no I haven't done any explicit measurement for timing.

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by swagata87** [comment]
About timing measurements, it's difficult to do a meaningful measurement using the RelVal MC samples of Phase2. I found only PU=0 relVal samples. Anyways, I still ran it before and after this PR and got following results. I ran the timing menu in `lxplus809` machine. I ran on 10K events, which were a mix of MinBias, TTBar-inclusive and WtoLNu, and they were all PU=0 samples. 
Before PR: EGamma 3 ms
After PR: EGamma 2.9 ms
Total time for full menu was in the ballpark of 210-211 ms, so things run quite fast with 0 PU sample, and it's not a useful way to draw conclusion about phase2 menu where the main timing challenge comes from high PU.

**Comment by Sam-Harper** [comment]
Swagata. thank you for doing this!

On the timing, it probably wont change anything when the Ele5 open path is being run but it should dramatically decrease the timing for the actual paths. So important to have if we do timing studies.

**Comment by swagata87** [comment]
Thank you for looking into this PR, Sam. 
So, although I fixed the ordering of Ele5 open path also, while doing timing study I did not run any open path. In fact, we now have a realistic menu for timing study, which is this: https://github.com/cms-sw/cmssw/blob/master/HLTrigger/Configuration/python/HLT_75e33_timing_cff.py, this is what I ran.
So, it seems that timing remain unchanged before/after this PR, mainly because of 0 PU sample. After all, the expensive sequences like pixel-matching are expensive when there is atleast some PU. W/o any PU, its just too clean an environment to see the gain coming from proper ordering.

**Comment by Martin-Grunewald** [comment]
+1

**Pull request merged**
