### PR TITLE
Run3-gex124C Try to avoid compilation warnings in L1Trigger/L1CaloTrigger

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Try to avoid compilation warnings in L1Trigger/L1CaloTrigger

#### PR validation:

Use the runTheMatrix test workflows

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cecilecaillol** [comment]
+l1

**Comment by srimanob** [comment]
@cmsbuild please test

Just clean up the unexpected failure, then I will sign the PR.

**Comment by srimanob** [comment]
+Upgrade

Technical PR, no change is expected. Failure in comparison comes from Phase-2 DD4hep which is known issue.

**Pull request merged**
