### PR TITLE
Update 2018 HI MC to latest GT and HLT menu (103X)

### PR DESCRIPTION
**Pull request by mandrenguyen**
backport of #25480

### CODE REVIEW

**Comment by pohsun** [comment]
please test

**Comment by Martin-Grunewald** [comment]
Hi,

I think the error in ```150.0``` is due to the fact that it uses conditions ```auto:phase1_2018_realistic``` instead of ```auto:phase1_2018_realistic_hi```

**Comment by Martin-Grunewald** [comment]
@mandrenguyen 
Sorry, please do NOT revert to FAKE. Put the proper auto GT for HIon!

**Comment by mandrenguyen** [comment]
@Martin-Grunewald 
Thanks Martin, I had noticed that same issue and reverted to the fake2 menu.
However, there is no HI GT that will run for wf 150. 
wf 150 is the deprecated HeavyIons scenario, which is only compatible with pp conditions. 
It will crash with the HI GT, as the track selection calibrations are incompatible. 
This could be fixed by uploading yet another GT, but I don't think this is worth the effort. 
While it's convenient to keep  deprecated wf around just a bit longer, but I don't we want to go through a lot of extra effort to maintain it.

**Comment by Martin-Grunewald** [comment]
Ah, OK - as long as HLT:HIon is used otherwise ie in the proper 2018 workflows...

**Comment by mandrenguyen** [comment]
@Martin-Grunewald Yeah, wf 158 corresponds to the upcoming MC campaign and uses HIon.

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
test results look similar to those in master #25480 , they are concentrated in HI 2018 workflows and the increase in DQM size output is in the HLT sector (change of menu)

**Comment by tocheng** [comment]
+1

**Comment by fabiocos** [comment]
@prebello @zhenhu do you agree with the proposed changes? If yes please sign, or comment

**Comment by prebello** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

@kpedro88 this is not upgrade specific, please sign it anyway for reference

**Comment by kpedro88** [comment]
+upgrade

**Pull request merged**
