### PR TITLE
Integration of the Tracker Clusterizer for Phase2

### PR DESCRIPTION
**Pull request by thomaslenzi**
This commit integrates the new Tracker Clusterizer for Phase2 in CMSSW_6_2_X_SLHC.

### CODE REVIEW

**Comment by davidlange6** [comment]
A few code issues to address:

Separate data formats from other stuff (e.g., no classes.def in SimTracker*)

Anything with a completely generic name (e.g., HitArray) has a high potential for name clash. Best to prepend something to identify the classes (e.g., Trk…) or to put them in a namespace

Move the plugin headers to the plugins directory

**Comment by thomaslenzi** [comment]
I addressed the issues previously listed:

The new data format has been removed for now and will be added in the correct location in a next commit

The name of the class has been changed PixelClusterizerHitArray

I modified the files I am in charge

**Comment by mark-grimes** [comment]
Superseded by #7204.

**Comment by mark-grimes** [comment]
This didn't close automatically when #7204 was merged because I rebased first.  @thomaslenzi, could you close this? All commits were merged with #7204.

**Pull request closed without merging**
