### PR TITLE
Remove unused package DQM/PhysicsHWW

### PR DESCRIPTION
**Pull request by dmitrijus**
Forward port of https://github.com/cms-sw/cmssw/pull/11815

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
DQMOffline_cff.py needs to be updated accordingly

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
DQMOffline_cff.py needs to be updated in addition to DQMOfflineCosmics_cff.py
thanks,
F.

**Comment by smuzaffar** [comment]
@cmsbuild, please test
CMSSW_7_6_X_2015-10-16-2300 is marked as bad release now

**Comment by dmitrijus** [comment]
Please don't test this one yet, it will fail.

This is a forward port of https://github.com/cms-sw/cmssw/pull/11815
(and it should be tested first)
I will merge changes from there as soon as the tests pass.

**Comment by dmitrijus** [comment]
Superseded by https://github.com/cms-sw/cmssw/pull/12020

**Pull request closed without merging**
