### PR TITLE
adding Heavy Ion and pp ref run specific plots

### PR DESCRIPTION
**Pull request by muell149**
Additions to HLT online DQM for pp ref run and HI run.

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1

**Comment by deguio** [comment]
ciao charlie,
I'm not sure this one can be merged. it is basically a complete duplication of an existing class.
we can run it online, but it will need some reorganization if you want it to be merged in release.
F.

**Comment by muell149** [comment]
@deguio Hey Fede, no problem. I had my doubts about this, but incorrectly decided a second (duplicate) class might be better than doubling the plots in the existing class. These changes only need to go online, but I'll work on the needed reorganization.

Thanks,
Charlie

**Comment by deguio** [comment]
in my mind the c++ code should stay the same and the module can be configured and cloned from the python config. we can have a look together and find what is the best.

**Comment by deguio** [comment]
-1
as we discussed in person some improvements are needed here

**Pull request closed without merging**
