### PR TITLE
Fixed path names. Removed pt2 and pt3 in unnecessary cases. Added debug print (dump # of HLT passed events). Replace "cout" to DebugLog. Updated PhotonMET, PureMET, DiPhoton and HighPtPhoton paths.

### PR DESCRIPTION
**Pull request by ryonamin**
Backport from 76X (#10907,#10974, #11219).
New PR instead of #11048 (same change but rebased).

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1
should be ok to go in. this is plain backport of something merged in 76 sometime ago.

**Comment by davidlange6** [comment]
@ryonamin @deguio 
what is the PR # that #11046 ended up getting merged in 76x?

**Comment by ryonamin** [comment]
Sorry, it should be replaced to  #11219.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
