### PR TITLE
Run3-hgx378XX Provide the missing file to avoid the failure in Unit Test for merging of #46468

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Provide the missing file to avoid the failure in the Unit Test due to merging of the PR #46468

#### PR validation:

Avoid the unit test failure

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Avoid unit test failure

### CODE REVIEW

**Comment by bsunanda** [comment]
urgent

**Comment by bsunanda** [comment]
type BugFix

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
+geometry

**Comment by mmusich** [comment]
hold

**Comment by mmusich** [comment]
@cmsbuild, please abort

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
@bsunanda why are you backporting a single file? In https://github.com/cms-sw/cmssw/pull/46351 you did add more scenarios.

**Comment by bsunanda** [comment]
This file was the missing one in the unit tests.
________________________________

**Comment by mmusich** [comment]
unhold

**Comment by mandrenguyen** [comment]
@bsunanda It passes tests, but it seems better to take the complete backport:  https://github.com/cms-sw/cmssw/pull/46547

Do you want to pre-sign that one as well and i'll merge it instead of this one?

**Comment by bsunanda** [comment]
It is up to you to decide. The other files are meant for  changes in Geometry/CMSCommonData for changes in 2016, 2017, 2018 geometries and appropriate changes in HcalTopology. If you do not backport them, backporting only hcalRecNumbering will not help. Please suggest what should be done
________________________________

**Comment by mandrenguyen** [comment]
> It is up to you to decide. The other files are meant for changes in Geometry/CMSCommonData for changes in 2016, 2017, 2018 geometries and appropriate changes in HcalTopology. If you do not backport them, backporting only hcalRecNumbering will not help. Please suggest what should be done

I must admit I cannot really parse this.  Do you confirm that it's ok to merge that PR instead of this one?

**Comment by bsunanda** [comment]
This is the minimum addition that can cure the unit test failure. The other PR also cures the unit test failure but some of the extra files which are added are not strictly necessary. They were required for 14_2_X for updating several Run2 scenarios and the corresponding changes in the HcalTopology code. Since those changes will not be backported to 14_1_X, I am not sure if backporting the entire 46531 is necessary. Both the PRs will be fixing the unit test. If you integrate #46544 I shall close this. Otherwise please integrate this one and ask Marco to close #46544
________________________________

**Comment by mandrenguyen** [comment]
@bsunanda [#46544](https://github.com/cms-sw/cmssw/pull/46544) is something else entirely, no?

**Comment by mandrenguyen** [comment]
+1
After discussing with @mmusich we merge this one for simplicity

**Pull request merged**
