### PR TITLE
Disable private unit tests in LumiProducer

### PR DESCRIPTION
**Pull request by plujan**
Took some unit tests in LumiProducer which were intended for only private tests and disabled them in test/BuildFile.xml.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

Paul, please make a PR for 75X as well (there are no auto-ports to 75X at this point from 74X)

**Comment by plujan** [comment]
OK, I've created PR #9848 for 7_5_X.

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/9847	48b67f4
- jenkins tests confirm that the (unsupported or experts-only) unit tests are not running anymore, as intended with this code change

**Comment by davidlange6** [comment]
+1

**Pull request merged**
