### PR TITLE
Separate vertex truth matching from vertex validation EDAnalyzer

### PR DESCRIPTION
**Pull request by makortel**
This PR separates the vertex truth matching part of PrimaryVertexAnalyzer4PUSlimmed to a separate associator (following the mechanism introduced in #9223). Also the features of #8852 are forward-ported here by adding
- a possibility to require minimum fraction of tracks shared by reco::Vertex and TrackingVertex (by default off, to keep the current behaviour)
- monitoring histograms for the shared track fraction with various denominators (extending what was done in #8852)

The VertexAssociatorByPositionAndTracks is added to a sequence intentionally in TrackValidation_cff.py, because I intend to use it later also in track validation.

In addition, the following modifications to VertexAssociatorByTracksProducer, that would in principle have belonged to #9223, are included here
- Migrate to fillDescriptions
- Replace couts with LogDebug/LogTrace
- Pass EDProductGetter to AssociationMap constructor
- Add dictionary for VertexToTrackingVertexAssociator

Tested in CMSSW_7_5_X_2015-05-25-2300 and rebased to CMSSW_7_5_X_2015-05-27-1100 (due to dependence on #9223). No changes expected in existing histograms.

@rovere @VinInn

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by makortel** [comment]
I guess the failure is caused by broken IB (as in other PRs).

**Comment by civanch** [comment]
please test

**Comment by makortel** [comment]
That should fix the segfault (although now I wonder a bit why it hasn't failed before...).

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
