### PR TITLE
Initialize all member data of L1MuDTTrackSegPhi

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

The missing members were found the the UBSAN report.

#### PR validation:

The code compiles.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
Please test

**Comment by Dr15Jones** [comment]
ping @cms-sw/l1-l2

**Comment by Dr15Jones** [comment]
ping @cms-sw/l1-l2

**Comment by silviodonato** [comment]
ping @cms-sw/l1-l2 (@jmduarte @rekovic )

**Comment by Dr15Jones** [comment]
ping @cms-sw/l1-l2

**Comment by Dr15Jones** [comment]
please sign @cms-sw/l1-l2

**Comment by silviodonato** [comment]
merge

**Pull request merged**
