### PR TITLE
[Do Not Merge] Testing a PR for master to see if we have unit tests failures

### PR DESCRIPTION
**Pull request by smuzaffar**

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by makortel** [comment]
runtestRecoEgammaPhotonIdentification failed with
```
A fatal system signal has occurred: segmentation violation
The following is the call stack containing the origin of the signal.
...
#4  <signal handler called>
#5  0x00007fd8d7b7c6e0 in check_match () from /lib64/ld-linux-x86-64.so.2
#6  0x00007fd8d7b7cf2b in do_lookup_x () from /lib64/ld-linux-x86-64.so.2
#7  0x00007fd8d7b7d20f in _dl_lookup_symbol_x () from /lib64/ld-linux-x86-64.so.2
#8  0x00007fd8d7b7ed96 in _dl_relocate_object () from /lib64/ld-linux-x86-64.so.2
#9  0x00007fd8d7b877ac in dl_open_worker () from /lib64/ld-linux-x86-64.so.2
#10 0x00007fd8d7b82914 in _dl_catch_error () from /lib64/ld-linux-x86-64.so.2
#11 0x00007fd8d7b86ccb in _dl_open () from /lib64/ld-linux-x86-64.so.2
#12 0x00007fd8d5865fbb in dlopen_doit () from /lib64/libdl.so.2
#13 0x00007fd8d7b82914 in _dl_catch_error () from /lib64/ld-linux-x86-64.so.2
#14 0x00007fd8d58665bd in _dlerror_run () from /lib64/libdl.so.2
#15 0x00007fd8d5866051 in dlopen@@GLIBC_2.2.5 () from /lib64/libdl.so.2
#16 0x00007fd8d770b9c9 in edmplugin::SharedLibrary::SharedLibrary(boost::filesystem::path const&) () from /cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_6_X_2019-02-21-1500/lib/slc7_amd64_gcc700/libFWCorePluginManager.so
#17 0x00007fd8d770e4a1 in edmplugin::PluginManager::load(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) () from /cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_6_X_2019-02-21-1500/lib/slc7_amd64_gcc700/libFWCorePluginManager.so
#18 0x00007fd8d7713e13 in edmplugin::PluginFactoryBase::findPMaker(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const () from /cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_6_X_2019-02-21-1500/lib/slc7_amd64_gcc700/libFWCorePluginManager.so
#19 0x00007fd8be917210 in CondDBESSource::CondDBESSource(edm::ParameterSet const&) () from /cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_6_X_2019-02-21-1500/lib/slc7_amd64_gcc700/pluginCondCoreESSourcesPlugins.so
```

runtestPhysicsToolsPatAlgos failed with
```
#4  <signal handler called>
#5  0x0000000000000000 in ?? ()
#6  0x00007ff9f85e06a5 in edm::eventsetup::DataProxyProvider::keyedProxies(edm::eventsetup::EventSetupRecordKey const&) const () from /build/cmsbld/jenkins/workspace/ib-any-integration/CMSSW_10_6_X_2019-02-21-1500/lib/slc7_amd64_gcc700/libFWCoreFramework.so
#7  0x00007ff9f85f5f28 in edm::eventsetup::EventSetupRecordProvider::addProxiesToRecord(std::shared_ptr<edm::eventsetup::DataProxyProvider>, std::map<edm::eventsetup::DataKey, edm::eventsetup::ComponentDescription, std::less<edm::eventsetup::DataKey>, std::allocator<std::pair<edm::eventsetup::DataKey const, edm::eventsetup::ComponentDescription> > > const&) () from /build/cmsbld/jenkins/workspace/ib-any-integration/CMSSW_10_6_X_2019-02-21-1500/lib/slc7_amd64_gcc700/libFWCoreFramework.so
#8  0x00007ff9f85f8c00 in edm::eventsetup::EventSetupRecordProvider::addProxiesToRecordHelper(edm::propagate_const<std::shared_ptr<edm::eventsetup::DataProxyProvider> >&, std::map<edm::eventsetup::DataKey, edm::eventsetup::ComponentDescription, std::less<edm::eventsetup::DataKey>, std::allocator<std::pair<edm::eventsetup::DataKey const, edm::eventsetup::ComponentDescription> > > const&) () from /build/cmsbld/jenkins/workspace/ib-any-integration/CMSSW_10_6_X_2019-02-21-1500/lib/slc7_amd64_gcc700/libFWCoreFramework.so
#9  0x00007ff9f85f7ecc in edm::eventsetup::EventSetupRecordProvider::usePreferred(std::map<edm::eventsetup::DataKey, edm::eventsetup::ComponentDescription, std::less<edm::eventsetup::DataKey>, std::allocator<std::pair<edm::eventsetup::DataKey const, edm::eventsetup::ComponentDescription> > > const&) () from /build/cmsbld/jenkins/workspace/ib-any-integration/CMSSW_10_6_X_2019-02-21-1500/lib/slc7_amd64_gcc700/libFWCoreFramework.so
```

testTauEmbeddingProducers failed with
```
#4  <signal handler called>
#5  0x00000000001085f0 in ?? ()
#6  0x00007fbf609bd150 in edm::Factory::findMaker(edm::MakeModuleParams const&) const () from /build/cmsbld/jenkins/workspace/ib-any-integration/CMSSW_10_6_X_2019-02-21-1500/lib/slc7_amd64_gcc700/libFWCoreFramework.so
#7  0x00007fbf609bd3e1 in edm::Factory::makeModule(edm::MakeModuleParams const&, edm::signalslot::Signal<void (edm::ModuleDescription const&)>&, edm::signalslot::Signal<void (edm::ModuleDescription const&)>&) const () from /build/cmsbld/jenkins/workspace/ib-any-integration/CMSSW_10_6_X_2019-02-21-1500/lib/slc7_amd64_gcc700/libFWCoreFramework.so
#8  0x00007fbf60a393ad in edm::ModuleRegistry::getModule(edm::MakeModuleParams const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, edm::signalslot::Signal<void (edm::ModuleDescription const&)>&, edm::signalslot::Signal<void (edm::ModuleDescription const&)>&) () from /build/cmsbld/jenkins/workspace/ib-any-integration/CMSSW_10_6_X_2019-02-21-1500/lib/slc7_amd64_gcc700/libFWCoreFramework.so
#9  0x00007fbf6092c725 in edm::WorkerRegistry::getWorker(edm::WorkerParams const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) () from /build/cmsbld/jenkins/workspace/ib-any-integration/CMSSW_10_6_X_2019-02-21-1500/lib/slc7_amd64_gcc700/libFWCoreFramework.so
#10 0x00007fbf609ba9e6 in edm::WorkerManager::getWorker(edm::ParameterSet&, edm::ProductRegistry&, edm::PreallocationConfiguration const*, std::shared_ptr<edm::ProcessConfiguration const>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) () from /build/cmsbld/jenkins/workspace/ib-any-integration/CMSSW_10_6_X_2019-02-21-1500/lib/slc7_amd64_gcc700/libFWCoreFramework.so
```

**Comment by Dr15Jones** [comment]
As a first guess, it looks like the failures could be caused by something being wrong in a shared library.

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test with cms-sw/cmsdist#4731

**Comment by smuzaffar** [comment]
please test with cms-sw/cmsdist#4738

**Pull request closed without merging**
