### PR TITLE
RazorHbb HLT DQM for 76X

### PR DESCRIPTION
**Pull request by jmduarte**
Changes for Razor Hbb HLT DQM for 76X

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by jmduarte** [comment]
Hi all,

I've looked at the logs from the failed tests and I only see the exception:

----- Begin Fatal Exception 07-Oct-2015 12:12:44 CEST-----------------------
An exception of category 'FormulaEvaluatorParseError' occurred while
   [0] Processing run: 191718 lumi: 109 event: 128717928
   [1] Running path 'reconstruction_step'
   [2] Calling event method for module LXXXCorrectorProducer/'ak4PFCHSResidualCorrector'
Exception Message:
While parsing '[2]*([3]+[4]*TMath::Log(max([0],min([1],x))))*1./([5]+[6]*100./3.*(TMath::Max(0.,1.03091-0.051154*pow(x,-0.154227))-TMath::Max(0.,1.03091-0.051154*TMath::Power(208.,-0.154227)))+[7]*((-2.36997+0.413917*TMath::Log(x))/x-(-2.36997+0.413917*TMath::Log(208))/208))' could not parse beyond '[2]*([3]+[4]*'
----- End Fatal Exception -------------------------------------------------

which doesn't seem to have anything to do with this PR

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1
provided it passes the tests

**Comment by smuzaffar** [comment]
please test

**Comment by davidlange6** [comment]
+1

**Pull request merged**
