### PR TITLE
[MuonHLT]: BugFix for TSGforOI

### PR DESCRIPTION
**Pull request by folguera**
This fixes a couple of bugs discovered that were affecting the efficiency specially in the overlap region:

- Added error-rescaling for hit-based seeds.
- Correct reseting of the number of made seeds (affecting the overlap region)
- Add a configuration parameter to chose the name of the propagator in the config file (it was previously hard-coded)

This only affects the outside-in component of the Muon HLT reconstruction. This is  a back port to 93X of #20396.

### CODE REVIEW

**Comment by slava77** [comment]
@Martin-Grunewald @fwyzard 
is there a plan for HLT to switch to 93X?

current targets for 93X that I'm aware of are the HGCAL phase-2 TDR and MC_V2 GEN-SIM.

**Comment by fwyzard** [comment]
>  is there a plan for HLT to switch to 93X?

Not that I know of.

**Comment by fwyzard** [comment]
We do want a backport to 9.2.x, though :-)

**Comment by folguera** [comment]
A backport on 92X is already created:  #20393, if there are no plans for running the HLT on 93X, we can probably close this.

**Comment by slava77** [comment]
so, it sounds like 93X is not needed
@folguera please close this PR.

**Pull request closed without merging**
