### PR TITLE
EMTF configures from Global Tag conditions in MC for 2016 only

### PR DESCRIPTION
**Pull request by abrinke1**
We have unfortunately uncovered another error in the EMTF emulation for 2016, which had been masked by the previous one. [1]  As it turns out the emulator was not accessing the 2016 Global Tag conditions for most of the algorithm settings, creating a mix of 2016 and 2018 logic which is internally inconsistent.  Efe measured the efficiency in the latest RelVal samples (see attached slides), and due to this bug it is 10% lower in the negative endcap than in the positive.

Thankfully the fix is quite simple, as you can see in this pull request.  Efe's plots confirm that the efficiency looks good when re-running the newest RelVals with this patch applied, and is consistent with the efficiency in 2016 data. [2]

For historical background on the likely cause for this bug, between 2016 and 2017 we completely overhauled the EMTF emulator, in part to handle the new RPC inputs.  Unfortunately both the CondDB code and payloads for EMTF at that point were in disarray (very long story), and accessing the conditions payload was crashing the MC RelVals.  At that point (if my hazy memory serves) we decided to configure by firmware version only for data, and by "fake conditions" for MC, with 3 different "fake conditions" python config files.  Sometime subsequently the "fake conditions" for each year went away, so the MC emulation (again, for some but not all of the algorithm settings) used the default settings, instead of the time-dependent firmware version settings.  This worked fine when the "default" settings were also the "current" settings (which was true when the 2017 and 2018 MC were produced), but fails for 2016. re-emulation.  Long story short, our workflows had never been fully validated for legacy MC, and now we're finding the bugs - for which we apologize.

Let us know if you have any other questions.
Best regards,Andrew, Efe, Olivier, and Benjamin

[1] https://github.com/cms-sw/cmssw/pull/29080
[2] https://twiki.cern.ch/twiki/bin/view/CMSPublic/L1TMuonPerformanceICHEP16

[EMTF_UL16MC_validation_19.03.2020.pdf](https://github.com/cms-sw/cmssw/files/4359945/EMTF_UL16MC_validation_19.03.2020.pdf)

### CODE REVIEW

**Comment by abrinke1** [comment]
Pull request for "master" version (fixing the bug for all eras) has been made here:
https://github.com/cms-sw/cmssw/pull/29260

**Comment by rekovic** [comment]
please test

**Comment by silviodonato** [comment]
backport of https://github.com/cms-sw/cmssw/pull/29260

**Comment by silviodonato** [comment]
urgent
this PR is needed to start the UL 2016 MC production

**Comment by silviodonato** [comment]
merge
in order to have this PR in the CMSSW_10_6_X_2020-03-23-1100 tests
This PR will be validated with a special release CMSSW_10_6_11_CANDIDATE2

**Comment by silviodonato** [comment]
> Comparison is ready
> https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-365d1a/5300/summary.html
> 
> Comparison Summary:
> 
>     * No significant changes to the logs found
> 
>     * Reco comparison results: 15 differences found in the comparisons
> 
>     * DQMHistoTests: Total files compared: 33
> 
>     * DQMHistoTests: Total histograms compared: 3212324
> 
>     * DQMHistoTests: Total failures: 1722
> 
>     * DQMHistoTests: Total nulls: 0
> 
>     * DQMHistoTests: Total successes: 3210268
> 
>     * DQMHistoTests: Total skipped: 334
> 
>     * DQMHistoTests: Total Missing objects: 0
> 
>     * DQMHistoSizes: Histogram memory added: 0.0 KiB( 32 files compared)
> 
>     * Checked 137 log files, 14 edm output root files, 33 DQM output files

@abrinke1 could you have a look at https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-365d1a/5300/summary.html, especially in "Comparison failed" and "DQM bin by bin comparison" ? I see changes in many workflows:

```
136.788 RunSinglePh2017B+HLTDR2_2017+RECODR2_2017reHLT_skimSinglePh_Prompt+HARVEST2017 
136.85 RunEGamma2018A+HLTDR2_2018+RECODR2_2018reHLT_skimEGamma_Offline_L1TEgDQM+HARVEST2018_L1TEgDQM 
140.56 RunHI2018+RECOHID18+HARVESTDHI18    
1330.0 ZMM_13+DIGIUP15+RECOUP15_L1TMuDQM+HARVESTUP15_L1TMuDQM+NANOUP15 
25202.0 TTbar_13+DIGIUP15_PU25+RECOUP15_PU25+HARVESTUP15_PU25+NANOUP15_PU25 
10024.0 TTbar_13TeV_TuneCUETP8M1_2017_GenSimFull+DigiFull_2017+RecoFull_2017+HARVESTFull_2017+ALCAFull_2017+NanoFull_2017 
10042.0 ZMM_13TeV_TuneCUETP8M1_2017_GenSimFull+DigiFull_2017+RecoFull_2017+HARVESTFull_2017+ALCAFull_2017+NanoFull_2017 
10224.0 TTbar_13TeV_TuneCUETP8M1_2017PU_GenSimFull+DigiFullPU_2017PU+RecoFullPU_2017PU+HARVESTFullPU_2017PU+NanoFull_2017PU 
10824.0 TTbar_13TeV_TuneCUETP8M1_2018_GenSimFull+DigiFull_2018+RecoFull_2018+HARVESTFull_2018+ALCAFull_2018+NanoFull_2018 
250202.181 TTbar_13UP18+PREMIXUP18_PU25+DIGIPRMXLOCALUP18_PU25+RECOPRMXUP18_PU25+HARVESTUP18_PU25 
```

Are they expected?

**Comment by abrinke1** [comment]
Hi @silviodonato ,
From what I can see, all these changes are to the L1T muon plots, and the distributions change only slightly.  This is expected, as the EMTF algorithm has changed, but it is not a dramatic change.
Best regards,
Andrew

**Comment by srimanob** [comment]
Hi @abrinke1 @silviodonato 
It seems that the issue comes from https://github.com/cms-sw/cmssw/pull/29080/
as these lines,
https://github.com/cms-sw/cmssw/pull/29080/files#diff-4625c6244dda6924f159cd114907cd31R139-R140
are triggered anyways, not only when Era 2016 is used.

I dump the configuration of workflow 136.85 from 10_6_10 and 10_6_11_CANDIDATE2 (local make), and this is the difference I see. Dump config files can be found in
/afs/cern.ch/user/s/srimanob/public/L1EMTF

```
(136) ~/public/L1EMTF: diff HLTDR2_2018_10611Cand2.py HLTDR2_2018_10610.py 
65912c65912
<     Era = cms.string('Run2_2016'),
---
>     Era = cms.string('Run2_2018'),
65919c65919
<     RPCEnable = cms.bool(False),
---
>     RPCEnable = cms.bool(True),
```

**Comment by silviodonato** [comment]
> If my conclusion is correct, we will need:
> 
>     * 10_6: fix of #29156 to 2016 era only.
> 
>     * master: fix of #29080 to make sure that when 2018 era is used, 2016 condition will not be triggered.

@abrinke1 could you take care of these two fixes? We need these fixes to make the next 10_6_X release in order to avoid any change 2017 and 2018 MC production.

**Comment by srimanob** [comment]
@silviodonato @abrinke1 
Here is the proposed fix,
https://github.com/cms-sw/cmssw/pull/29287

I found that stage2L1Trigger modifier is used for all years, and stage2L1Trigger_2017 is set up on top (not replace), so we cannot just detach stage2L1Trigger from 2017. What I do is introduce a new modifier to EMTF which will be trigger on 2016 only. Then when Era of 2017 is called, it will be removed, so no propagation to 2017, and also for 2018 (as clone of 2017).

**Pull request merged**
