### PR TITLE
temporarily disable trigger for hgcal V9 (again)

### PR DESCRIPTION
**Pull request by kpedro88**
To fix issue noted here: https://github.com/cms-sw/cmssw/pull/24256#issuecomment-417331900

### CODE REVIEW

**Comment by kpedro88** [comment]
please test workflow 24034.0

**Comment by kpedro88** [comment]
Uh, not sure what that's about. Let's try again.

**Comment by kpedro88** [comment]
please test workflow 24034.0

**Comment by kpedro88** [comment]
@smuzaffar @mrodozov can you check this? it works fine locally

**Comment by smuzaffar** [comment]
@kpedro88 , this could be related to the changes here cms-sw/cms-git-tools#99
For now I disabled the sourcing of /cvmfs/cms-ib.cern.ch/nweek-02539/cmsset_default.sh and restarted the tests.

**Comment by kpedro88** [comment]
@nsmith-, @rekovic, @thomreis please sign, this is needed to fix the IBs for 2023D28 workflows before pre3

**Comment by kpedro88** [comment]
@nsmith-, @rekovic, @thomreis ping

**Comment by fabiocos** [comment]
@nsmith-, @rekovic, @thomreis as we have a broken workflow and we need to converge for 10_3_0_pre3 asap, I will merge this PR, please comment in case

**Comment by fabiocos** [comment]
merge

**Pull request merged**
