### PR TITLE
Fastsim new default mix scheme

### PR DESCRIPTION
**Pull request by lveldere**
Fastsim: digi-reco mixing becomes default

### CODE REVIEW

**Comment by degano** [comment]
@cmsbuild please test

**Comment by lveldere** [comment]
+1

**Comment by lveldere** [comment]
@franzoni 

would you mind signing this one?
I'd like to have this merged asap.
Zero regression expected and observed on the wfs included in the tests.

files under your supervision have trivial changes:

Configuration/Applications/python/ConfigBuilder.py
- remove customisation that was specific for old mixing scheme

Configuration/StandardSequences/python/Mixing.py
- renamed (and edited) default pu mixing cfg

**Comment by lveldere** [comment]
ping

to the responsibles for 'operations', 

please review the files under your supervision
zero regression expected, zero regression observed

**Comment by lveldere** [comment]
@degano @davidlange6 

can you merge? operations has had enough time to review.
this pr is purely technical, no regression expected, no regression observed.

**Comment by davidlange6** [comment]
@lveldere  - 1 day is not generally enough time to for people to always review. You'll need to reduce your expectations in this regard by a bit.

**Comment by davidlange6** [comment]
+1

**Comment by Martin-Grunewald** [comment]
@lveldere 

Hi Lukas, 

this PR breaks FastSim tests, eg, IntegrationTestWithHLT_cfg.py 

```
# Conditions read from  CMS_CONDITIONS  via FrontierProd 
----- Begin Fatal Exception 24-Jan-2015 08:53:06 CET-----------------------
An exception of category 'ConfigFileReadError' occurred while
   [0] Processing the python configuration file named IntegrationTestWithHLT_cfg.py
Exception Message:
python encountered the error: <type 'exceptions.NameError'>
name 'trackAccumulator' is not defined
----- End Fatal Exception -------------------------------------------------
```

**Comment by lveldere** [comment]
@Martin-Grunewald 

Hi Martin

I did not adapt the unit tests to the new situation.
I'll do so after #7306 gets merged.

Cheers

Lukas

**Comment by lveldere** [comment]
Hi Martin

Will be fixed after #7306 and #7358 are merged

Cheers

Lukas

**Pull request merged**
