### PR TITLE
Run3-TB58 Correcting the beam line description of October 18 HGCal TB setup

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Correcting the beam line description of October 18 HGCal TB setup

#### PR validation:

Tested using cfg files in the test area of Geometry/HGCalCommonData and SimG4CMS/HGCalTestBeam

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade

**Comment by silviodonato** [comment]
+1

**Pull request merged**
