### PR TITLE
Added paths that are removde JetIdCleaned suffix (MonoJet, PhotonMET,and PureMET). Optimized binning of sumEt plot in MonoJet category.

### PR DESCRIPTION
**Pull request by ryonamin**
Backport from #11596 to 75X.

This PR has been already merged with #11456 and #11151 which PRs are currently pending, so that this PR can be merged without conflicting even after #11456 and #11151 being merged. This is why we see many changes.
Please let me know if this doesn't work.

Also added the changes of #11619.

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
to simplify my job could you please list all the correspondent PR in 76 and close the pending PR superseded by this one?
thanks in advance,
F.

**Comment by ryonamin** [comment]
Here is the list 
(corresponding 76X-PRs of 11456 and 11151)
10907
10974
11219
11150
11453

(newly added)
11596
11619

**Comment by ryonamin** [comment]
I closed 11456 and 11151.

**Comment by deguio** [comment]
+1
this should restore the consistency with 76x

**Comment by davidlange6** [comment]
Hi - I'm cleaning up the 75x CMSSW release queue, so closing issues not directly related to analysis or finalizing the HI MC production. Please make sure these requests are included in the 80x release already. Thanks!

**Pull request closed without merging**
