### PR TITLE
[12_4_X] L1T DQM: Adding the uGT timing sequence back and updating the relevant algo list - backport 

### PR DESCRIPTION
**Pull request by vukasinmilosevic**
L1T DQM update:

Putting the uGT timing sequence back into the workflow
Updating relevant triggers to match the Run 3 menu (L1Menu_Collisions2022_v1_0_1)

Backport of #38840 to be included in the online L1T DQM workflow

### CODE REVIEW

**Comment by emanueleusai** [comment]
please test

**Comment by emanueleusai** [comment]
testing at p5

**Comment by emanueleusai** [comment]
+1

- tested and deployed at p5

**Comment by perrotta** [comment]
backport of https://github.com/cms-sw/cmssw/pull/38840

**Comment by perrotta** [comment]
@vukasinmilosevic the 12_5_X backport is still missing: please don't forget it!
I'd suggest to hold the merging of this PR until the 12_5_X backport is also made available, in order not to forget it.

**Comment by rappoccio** [comment]
please hold

* Will hold until the 12_5 backport is available, otherwise this looks ready.

**Comment by perrotta** [comment]
unhold

**Comment by perrotta** [comment]
+1

**Pull request merged**
