### PR TITLE
Removed framework plugins from libDQMSiStripMonitorClient

### PR DESCRIPTION
**Pull request by Dr15Jones**
Framework plugins are not allowed in shared libraries. The plugins
have been moved to the plugins directory.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
ping
This is needed to fix problems with the arm builds.

**Comment by Dr15Jones** [comment]
ping

**Comment by smuzaffar** [comment]
@fabiocos , can we get this in to fix the aarch64 IBs?

**Comment by Dr15Jones** [comment]
ping

**Comment by fabiocos** [comment]
@Dr15Jones @smuzaffar yes, let's merge it, it is a pity that it was not signed by DQM so far

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Pull request merged**
