### PR TITLE
2017 and 2018 GTs updated with HCAL LUTs Bug fix and Resp Corr Update for Plan1

### PR DESCRIPTION
**Pull request by arunhep**
# Summary of changes in Global Tags

## Upgrade

   * **PhaseI 2017 cosmics peak scenario** : [90X_upgrade2017cosmics_realistic_peak_v19](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_upgrade2017cosmics_realistic_peak_v19) as [90X_upgrade2017cosmics_realistic_peak_v18](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_upgrade2017cosmics_realistic_peak_v18) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/90X_upgrade2017cosmics_realistic_peak_v19/90X_upgrade2017cosmics_realistic_peak_v18):
      * Bug Fix in HCAL LUTs described here https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2860.html
      * HCAL Response Correction Update

   * **PhaseI 2017 cosmics scenario** : [90X_upgrade2017cosmics_realistic_deco_v18](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_upgrade2017cosmics_realistic_deco_v18) as [90X_upgrade2017cosmics_realistic_deco_v17](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_upgrade2017cosmics_realistic_deco_v17) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/90X_upgrade2017cosmics_realistic_deco_v18/90X_upgrade2017cosmics_realistic_deco_v17):
      * Bug Fix in HCAL LUTs described here https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2860.html
      * HCAL Response Correction Update

   * **PhaseI 2017 design scenario** : [90X_upgrade2017_design_IdealBS_v19](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_upgrade2017_design_IdealBS_v19) as [90X_upgrade2017_design_IdealBS_v18](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_upgrade2017_design_IdealBS_v18) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/90X_upgrade2017_design_IdealBS_v19/90X_upgrade2017_design_IdealBS_v18):
      * Bug Fix in HCAL LUTs described here https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2860.html
      * HCAL Response Correction Update

   * **PhaseI 2017 realistic scenario** : [90X_upgrade2017_realistic_v20](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_upgrade2017_realistic_v20) as [90X_upgrade2017_realistic_v19](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_upgrade2017_realistic_v19) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/90X_upgrade2017_realistic_v20/90X_upgrade2017_realistic_v19):
      * Bug Fix in HCAL LUTs described here https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2860.html
      * HCAL Response Correction Update

   * **PhaseI 2018 cosmics scenario** : [90X_upgrade2018cosmics_realistic_deco_v17](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_upgrade2018cosmics_realistic_deco_v17) as [90X_upgrade2018cosmics_realistic_deco_v16](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_upgrade2018cosmics_realistic_deco_v16) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/90X_upgrade2018cosmics_realistic_deco_v17/90X_upgrade2018cosmics_realistic_deco_v16):
      * Bug Fix in HCAL LUTs described here https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2860.html

   * **PhaseI 2018 design scenario** : [90X_upgrade2018_design_IdealBS_v15](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_upgrade2018_design_IdealBS_v15) as [90X_upgrade2018_design_IdealBS_v14](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_upgrade2018_design_IdealBS_v14) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/90X_upgrade2018_design_IdealBS_v15/90X_upgrade2018_design_IdealBS_v14):
      * Bug Fix in HCAL LUTs described here https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2860.html

   * **PhaseI 2018 realistic scenario** : [90X_upgrade2018_realistic_v17](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_upgrade2018_realistic_v17) as [90X_upgrade2018_realistic_v16](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_upgrade2018_realistic_v16) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/90X_upgrade2018_realistic_v17/90X_upgrade2018_realistic_v16):
      * Bug Fix in HCAL LUTs described here https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2860.html

### CODE REVIEW

**Comment by arunhep** [comment]
please test

**Comment by franzoni** [comment]
outcome of the tests:
    * no impact in data 2012B nor 2016B, nor phase0 MC

   * **2017 full sim TTbar**: eta-dependent change in average [energy and occupancy of trigger primitives](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_9_1_X_2017-03-17-1100+17975/18873/10024.0_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2017_GenSimFull+DigiFull_2017+RecoFull_2017+ALCAFull_2017+HARVESTFull_2017/HcalDigisV.html) , with [impact on L1 jet and met related trigger objects](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_9_1_X_2017-03-17-1100+17975/18873/10024.0_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2017_GenSimFull+DigiFull_2017+RecoFull_2017+ALCAFull_2017+HARVESTFull_2017/L1TEMU_L1TStage2CaloLayer2.html).             @abdoulline @deguio @hatakeyamak may you please confirm if the pattern is expected ? 

hcaldigisv__hcaldigitask_hcaldigitask_tp_ave_et_ieta
hcaldigisv__hcaldigitask_hcaldigitask_tp_ntp_ieta


   * **2018 full sim TTbar**:qualitatively [similar outcome as 2017]\

hcaldigisv__hcaldigitask_hcaldigitask_tp_ave_et_ieta-1
hcaldigisv__hcaldigitask_hcaldigitask_tp_ntp_ieta-1

**Comment by franzoni** [comment]
https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2860/1/1/1/2/1/1/1/1.html

**Comment by abdoulline** [comment]
HCAL  Trigger group members:  @matz-e, @christopheralanwest, @akhukhun - could you, please, take a look?

**Comment by christopheralanwest** [comment]
These changes are expected (assuming the red histogram is the one that includes this PR). The most important change is in the energy scale of the HE trigger primitives (TPs), which in turn change the [L1 jet ET](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_9_1_X_2017-03-17-1100+17975/18873/10024.0_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2017_GenSimFull+DigiFull_2017+RecoFull_2017+ALCAFull_2017+HARVESTFull_2017/L1TEMU__L1TStage2CaloLayer2_resolutionJetET_HE.png)

The other change, which has more impact on the DQM plots than the physics, is the reinstatement of the threshold cut to exclude TPs arising from noise. You can see the effect of the change in the [trigger primitive ET plot](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_9_1_X_2017-03-17-1100+17975/18873/10024.0_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2017_GenSimFull+DigiFull_2017+RecoFull_2017+ALCAFull_2017+HARVESTFull_2017/HcalDigisV__HcalDigiTask_HcalDigiTask_tp_et.png) or the ET versus eta plot. In the latter plot, the average TP ET was smoother because it was dominated by low energy TPs.

Since the distributions immediately before this PR do not represent intended behavior, an [8_X_Y](https://goo.gl/QbVutS) release is more reasonable baseline.

**Comment by franzoni** [comment]
hello @christopheralanwest
red is indeed "this PR" , while blue is the "baseline".

By "In the latter plot" are you referring to [these (search for HcalDigiTask_tp_ave_et_ieta)](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_9_1_X_2017-03-17-1100+17975/18873/10024.0_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2017_GenSimFull+DigiFull_2017+RecoFull_2017+ALCAFull_2017+HARVESTFull_2017/HcalDigisV_HcalDigiTask.html), two of which are also reported in the [previous post](https://github.com/cms-sw/cmssw/pull/17975#issuecomment-287520324) (the "ET versus eta plot" link is somehow broken ) ?

**Comment by christopheralanwest** [comment]
Yes, when I said "in the latter plot", I was referring to the plots that were referred to in the previous post.

**Comment by franzoni** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
