### PR TITLE
Decay tables for long lived chargino decays

### PR DESCRIPTION
**Pull request by scodella**
I am adding to Configuration/Generator/data/download.url the decay tables for the long lived charginos needed for disappearing track analysis (SUS-19-005).

### CODE REVIEW

**Comment by efeyazgan** [comment]
please test

**Comment by fabiocos** [comment]
@scodella please try to figure a more informative title for this PR, the present version looks "a bit generic"...

**Comment by scodella** [comment]
Is any test still need for this or can be signed off? thanks

**Comment by qliphy** [comment]
+1

**Comment by fabiocos** [comment]
@scodella @qliphy unfortunately the download.url mechanism is no more active even for older releases (thanks to @davidlange6 for drawing my attention, I looked at the title but did not notice this point in the first round). Effectively we are nowadays using external data files in https://github.com/cms-data/Configuration-Generator so the new files should be put there

**Comment by efeyazgan** [comment]
OK, so @scodella should add the files to https://github.com/cms-data/Configuration-Generator (preferably in a separate folder there).

**Comment by scodella** [comment]
just made a pull request for adding the files to https://github.com/cms-data/Configuration-Generator:
https://github.com/cms-data/Configuration-Generator/pull/5

**Comment by scodella** [comment]
Ciao Fabio,

 >[...] Effectively we are nowadays using external data files in https://github.com/cms-data/Configuration-Generator so the new files should be put there


grazie per avvertirci di questo. Sai dove posso trovare un esempio di come usare i file una volta che la pull request é accettata?


grazie,

Luca

**Comment by fabiocos** [comment]
@scodella this PR can be closed, we will update the external part for this need

**Comment by fabiocos** [comment]
@scodella now that the data have been updated this PR is no more needed.

**Pull request closed without merging**
