### PR TITLE
Run2 HBHE noise filter

### PR DESCRIPTION
**Pull request by FHead**
Run 2 HBHE baseline noise filters.  Changes are
- A few more variables in the summary hcal noise objects
- A new flag can be configured to run from config files during HBHE reconstruction which uses the same OOTPU correction code as the official reconstruction

### CODE REVIEW

**Comment by nclopezo** [comment]
please test

**Comment by nclopezo** [comment]
The tests are being triggered in jenkins.

**Comment by nclopezo** [comment]
please test

**Comment by nclopezo** [comment]
please test

**Comment by nclopezo** [comment]
please test

**Comment by nclopezo** [comment]
please test

**Comment by nclopezo** [comment]
please test

**Comment by abdoulline** [comment]
Why should this long-time ago closed PR be "resurrected"?  
It  has been re-implemented as improved version  
 https://github.com/cms-sw/cmssw/pull/5168 for 72X, 
which in turn has been closed and ported to 73X as
https://github.com/cms-sw/cmssw/pull/5389 
and the latter has been merged into 73X?

**Comment by nclopezo** [comment]
Hi @abdoulline,
I was testing a script. Sorry for the confusion. Next time I will use an older PR.

**Comment by abdoulline** [comment]
OK David. Thank you.

Salavat

**Pull request closed without merging**
