### PR TITLE
Technical fixes to L1T code from 24242

### PR DESCRIPTION
**Pull request by fabiocos**
The integration of #24242 has caused a couple of issues:
1) in some new python scripts the print syntax was not synchronized with the migration to the python3 compatible standard;
2) there was a clang error reported https://github.com/cms-sw/cmssw/pull/24242#issuecomment-412341978

This PR addresses both issues, corresponding fixes should be backported to the version for 10_2_X.

### CODE REVIEW

**Comment by fabiocos** [comment]
please test

**Comment by rekovic** [comment]
Thanks @fabiocos.  I saw this just now as I am with limited access. 

+1

**Comment by rekovic** [comment]
+1

**Comment by fabiocos** [comment]
@davidlange6 I guess that at present we have no other way to detect python print statements not migrated to the new syntax than by visual inspection, am I correct?

**Comment by davidlange6** [comment]
Right. There is an open issue against that.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
