### PR TITLE
[90X] Add Phase-I Cosmics 

### PR DESCRIPTION
**Pull request by mmusich**
This PR attempts to add a new cosmics simulation workflow using phase-I 2017 detector.
In order to consume cosmics reconstruction-tailored conditions a new autoCond Global Tag is added. 
To address comments occurring during the review, appropriate commits were included to handle Hcal 2017 reconstruction with cosmics data and propagate to this wf the new phase-I pixel DQM.  
On Hcal side (thanks @kpedro88):
   * Increased flexibility of HCAL cosmic setup by applying cosmic-specific settings to cloned modules and then assembling sequences for 2017 and pre-2017 separately
   * Updated HCAL NZS sequence for 2017 HF and HE changes (can be used in cosmic runs)
   * Modified size of simulated QIE10DigiCollection to be 4 samples instead of default 10, by accessing sim parameter `readoutFrameSize` and forwarding through ZS algos accordingly

On DQM side (thanks @schneiml):
   * Add a special cosmics sequence to the PixelPhase1 DQM config
   * Enable it for the phase1pixel era in the general Pixel offline DQM config
   * Add a special cosmics sequence for harvesting to the Pixel offline DQM
config, since it is needed for Phase1.

Fwd-port of #16343

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
+1

**Comment by cvuosalo** [comment]
@mmusich: This PR needs to be re-based.

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
```
MessageLogger Summary

Severity    # Occurrences   Total Occurrences
--------    -------------   -----------------

Failure cmsRun streamGrapher_stallMonitor_cfg.py: status 84
status = 21504

---> test TestFWCoreConcurrencyDriver had ERRORS
```
I am not sure it has anything to do with the proposed changes

**Comment by davidlange6** [comment]
hi all - changes here look straightforward - please complain about any further issues during the ORP today. thanks

**Comment by slava77** [comment]
why does "add phase-1 cosmics" affect regular pp workflows in 2017 and 2023 setups?

**Comment by slava77** [comment]
ah, looks like the tests included other PRs

**Pull request merged**
