### PR TITLE
Improvements in the CondDB interface

### PR DESCRIPTION
**Pull request by ggovi**
#### PR description:

The interface of some of the CondDB services have been improved:

IOVProxy: IOV iterators moved in a specific class ( IOVArray )
IOVEditor: added eraseIov method 
Session :   adapted for new IOVProxy + added getCurrentRun method
Tag_t, TagInfo_t : improved field names

All the dependencies have been fixed in various packages

#### PR validation:

unit tests in CondCore/CondDB run

### CODE REVIEW

**Comment by ggovi** [comment]
please test

**Comment by ggovi** [comment]
please test

**Comment by ggovi** [comment]
please test

**Comment by jfernan2** [comment]
+1
No changes as expected

**Comment by tlampen** [comment]
+1

**Comment by ggovi** [comment]
@rekovic 
can you please have a look? For L1T there are only easy adaptations...

**Comment by silviodonato** [comment]
Kind reminder to @benkrikler @rekovic

**Comment by rekovic** [comment]
+1

**Comment by ggovi** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
