### PR TITLE
Revert "DD4Hep Shapes Validation"

### PR DESCRIPTION
**Pull request by fabiocos**
Reverts cms-sw/cmssw#23393

A number of crashes are observed in CMSSW_10_2_DEVEL_X_2018-05-31-2000 after the merge of #23393, there is a huge number of lines added to the output (sorry for missing it during the tests), checking whether the crashes are related to #23393

### CODE REVIEW

**Comment by ianna** [comment]
@fabiocos - can you point to the log with problems, please.

**Comment by ianna** [comment]
@fabiocos - please, use https://github.com/cms-sw/cmssw/pull/23412 instead. It does not look like other changes in #23393 should cause problems. Thanks.

**Comment by fabiocos** [comment]
@ianna the crashes are in DEVEL, they might be unrelated (I do not reproduce them in the regular IB build, central tests are still ongoing). The cout problem is real though. Please also check the printed messages about the Magnetic Field, for instance

https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc700/CMSSW_10_2_X_2018-05-31-2300/pyRelValMatrixLogs/run/11623.0_MinBias_13+MinBias_13TeV_pythia8_TuneCUETP8M1_2019_GenSimFull+DigiFull_2019+RecoFull_2019+HARVESTFull_2019+ALCAFull_2019/step5_MinBias_13+MinBias_13TeV_pythia8_TuneCUETP8M1_2019_GenSimFull+DigiFull_2019+RecoFull_2019+HARVESTFull_2019+ALCAFull_2019.log#/

**Comment by fabiocos** [comment]
I close this for the time being

**Comment by ianna** [comment]
@fabiocos - thanks and sorry for missing the cout :-(

**Pull request closed without merging**
