### PR TITLE
Remove DeepTauID v2.1 from mini- and nanoAOD

### PR DESCRIPTION
**Pull request by mbluj**
#### PR description:

As title says, this PR removes DeepTauID v2.1 from mini and nanoAOD as it is superseded by v2.5 and v2.1 is not supported by Tau POG for Run-3 (and Run-2+3) analyses. 

#### PR validation:

Tested with wf. 13034.21 (`TTbar_14TeV+2024PU_ProdLike`) which is a good representative of mini+nano workflows involving DeepTauID production.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backports are not expected.

### CODE REVIEW

**Comment by jfernan2** [comment]
enable nano

**Comment by jfernan2** [comment]
please test

**Comment by hqucms** [comment]
+1

**Comment by jfernan2** [comment]
Is it understood why the diff rate increases despite removing this TauID?

**Comment by mbluj** [comment]
> Is it understood why the diff rate increases despite removing this TauID?

Hello, most of observed differences are caused by the DeepTauID v2.1 removal and is as expected; these differences are:
* changes in tauIDs embedded in slimmedTaus in miniAOD: removal of DeepTauID v2.1 results in reduced number of tauIDs and difference in their order,
* changes in Tau tables in nanoADO: removal of DeepTauID v2.1 related branches and some change in multiplicity of tau candidates as candidates which used to be selected uniquely with loosest WP of DeepTauID v2.1 are now rejected.

There are also some unrelated tracking differences (which then propagate to packed particles and flavour taggers) in mkFit wfs, e.g. 12834.7 - I do not know if these are expected, but are not related to this PR.

**Comment by hqucms** [comment]
> Is it understood why the diff rate increases despite removing this TauID?

The rate is `ev/s` so increasing means faster :)

**Comment by jfernan2** [comment]
+1

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
