### PR TITLE
Improvements and fixes for the BPH-trigger offline DQM code

### PR DESCRIPTION
**Pull request by aboletti**
In this pull-request many features of the offline DQM code used for BPH triggers have been fixed and optimised, and few more functionalities have been added.
Here a list of the major changes:

- **New general structure** of the code: for each efficiency type (defined as the "cases" in the big "switch") the numerator histos are filled in a nested environment just after the denominator filling, instead of defining two separate environments with specific selection criteria for each of them.
- **Fixed trigger matching** feature: the `bool BPHMonitor::matchToTrigger` function is now using the HLTConfigProvider method to access the trigger-object collections.
- **New correction for prescaled triggers**: while using the reference method to produce efficiencies, if the numerator path is prescaled it would flatly decrease the resulting efficiency by that prescale value. By filling the numerator histograms with weighted events, according to that prescale, the reduction effect is corrected.
- **Better tuning of the offline selections** (especially the dimuon invariant masses), to select the correct regions where to compute the efficiency. This helps in some modules to select a pure region for the signal, in other modules (based on background events) to select the appropriate kinematic region.
- **Customised and optimised binning**: to reduce the global number of bins, especially where they are not needed, the binning of the histograms has been refined
- **Removal of few meaningless efficiencies**: some modules defined in the list of the cff file (devoted to the L1 efficiency of dR(MuMu) cut in 2mu+trk triggers) have been removed, since their efficiency definition is not correct (using at denominator a 2mu trigger, they will always be biased by the inefficiency of the track reconstruction at HLT)

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
@aboletti Your PR does not run[1], please test your changes producing a valid root file and uploading it on a DQM test GUI before proceed. Thanks.

[1] An exception of category 'Configuration' occurred while
   [0] Constructing the EventProcessor
   [1] Validating configuration of module: class=BPHMonitor label='DM2_Jpsi_addTkMuTkMu_Phi'
Exception Message:
Illegal parameter found in configuration.  The parameter is named:
 'verbosityLevel'
You could be trying to use a parameter name that is not
allowed for this plugin or it could be misspelled.

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by jfernan2** [comment]
@anigamova Please create a backport if you need it to be included into Online DQM, following instructions on https://twiki.cern.ch/twiki/bin/viewauth/CMS/DQMP5TagCollector

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
@smuzaffar I think the bot got stuck on this test...

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
+1

**Comment by Dr15Jones** [comment]
I believe this pull request is causing the crash reported here #23787

**Comment by fabiocos** [comment]
@Dr15Jones yes, it is, verified with a merge of this PR only on top of yesterday's IB. I am reverting it

**Pull request merged**
