### PR TITLE
Updating xmls Material Budget for Phase2 reco

### PR DESCRIPTION
**Pull request by ebrondol**
In this PR, I just merged 4 files created by @ghugo83 and they partly fix the path to pick up the correct material in tracking for phase2. @ianna please confirm it.
This is a work which is evolving now in order to produce a good tracking for phase2, so another PR will follow soon to fix the values of the Xi in the Outer Tracker and there we expect the real step in a good direction. In this moment, some changes are expected for phase2 reco, but the real analysis should be done after the second PR, @VinInn can also comment in case of performance changes.
No changes are expected for other phases. 

@rovere @kpedro88 @boudoul

### CODE REVIEW

**Comment by VinInn** [comment]
@cmsbuild , please test

**Comment by ghugo83** [comment]
Heee please wait :)
I have done these XMLs in a quick unformal 'hack' style to test an idea.
I am not sure of it yet, notably the names in trackerProdCuts.xml

**Comment by slava77** [comment]
On 9/21/16 6:02 AM, cmsbuild wrote:
> Comparison is ready
> https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-15927/15300/summary.html
> 
> @slava77 <https://github.com/slava77> comparisons for the following
> workflows were not done due to missing matrix map:
> 
>   * 10424.0_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2017NewFPix_GenSimFull+DigiFull_2017NewFPix+RecoFull_2017NewFPix+HARVESTFull_2017NewFPix

Given that we expect almost zero lifetime of this workflow, I will not
be immediately updating the map

@boudoul @schneiml
if I understand correctly, 10424 was hacked into the short matrix only
to make the bot test the new workflow
as a part of standard PR tests.
Now that the FPIX PR is merged, it's probably time to lighten up the
short matrix and remove 10424.0 from it.

**Comment by schneiml** [comment]
@slava77 yes, this is correct. The main point was to get the code from #15805 actually run once.

**Comment by slava77** [comment]
I was curious about the diffs in 2023 here.
Looks like the meaning of hits has changed or they are just lost.


wf20024_nhits
wf20024_strips2d_vseta
wf20024_tob_vseta
wf20024_hiteff_v_layer

It looks like this PR is a work in progress,
however, I wanted to point out the naming scheme should change for the phase-2 tracker.
TOB and TID will look more and more awkward the closer we get to phase-2.

**Comment by ebrondol** [comment]
@ghugo83 yes, I know, but these files were the most close to the reality that we have in this moment. In the next set of files that will go in the next PR you can confirm the validity. 
@slava77 yes, the OT now it is completely awkward and we know that - at least for this PR, this is expected.

**Comment by ghugo83** [comment]
Guyssss please wait a bit we are gonna provide updated XMLs we are working on it
By the end of the day maximum

**Comment by ianna** [comment]
hold

@ghugo83 - awaiting your confirmation if this can go in or if you have a proper version

**Comment by ebrondol** [comment]
Sure. Sorry. But if this is going to happen so soon (I did not know when I open this PR) I can also update this PR in the case, we do not need to open another one.

**Comment by ghugo83** [comment]
Dear @ianna,
This cannot go, we have a proper version. Sorry things are taking slightly longer than expected though, by tomorrow evening we are finished.
Cheers

**Comment by ianna** [comment]
@ghugo83 - ok. Are you planning to open a new PR or patch this one?

**Comment by ghugo83** [comment]
good news i am finished with the fixes in the XMLs for 81X
For the PR I totalli don't mind.
Having a new PR is slightly easier for me but totally doesn't matter.
Opening sth right now, maybe let's keep this one as long as the tests are not approved ?

**Comment by ebrondol** [comment]
I would be in favor to close this.

**Comment by ianna** [comment]
@ebrondol - please, close this PR

**Pull request closed without merging**
