### PR TITLE
remove global re-director from `eopTreeWriter` unit test input files

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

Title says it all, fix the [failures in IB unit tests](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_amd64_gcc10/CMSSW_12_5_X_2022-12-20-2300/unitTestLogs/Alignment/OfflineValidation#/150) 

#### PR validation:

Run successfully `scram b runtests use-ibeos`.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Not a backport, no need of PRs in subsequent release cycles.

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
type trk, bug-fix

**Comment by tvami** [comment]
+alca
 * unit test testing this already passed

**Comment by perrotta** [comment]
+1

**Pull request merged**
