### PR TITLE
Simplify CSCCFEBStatusDigi::ShiftSel

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

This also fixes a static analysis warning.

#### PR validation:

Code compiles

Running both the old and new version of the code through compiler explorer results in identical assembler code using -O2.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
@makortel FYI

**Comment by Dr15Jones** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
