### PR TITLE
ECALbyLumi+Timing

### PR DESCRIPTION
**Pull request by mbandrews**
Fixed bugs in:
- setting hasLumiPlots_ flag of client MEs
- preventing unintended reset of Trend client MEs

Added features:
- by lumi reportSummaryContents for offline dqm (presample check temporary disabled pending better understanding of persistent kBad values)
- timing for offline dqm
- timing mean & rms trend plots

Removed Test Pulse from activeSources of calibration quality summary

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
@mbandrews 
please change the title of this PR to something meaningful for the release notes.
thanks,
F.

**Comment by deguio** [comment]
+1
please update the title at:
https://github.com/cms-sw/cmssw/pull/13358

it won't be merged otherwise.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
