### PR TITLE
TkDQM: backport of PR 33430

### PR DESCRIPTION
**Pull request by sroychow**
This is a backport of #33430. 

#### PR validation:
Passes relval tests.
#### if this PR is a backport please specify the original PR and why you need to backport that PR:
Backport of #33430. Significant reduction in timing of the TrackingMonitor. 
https://github.com/cms-sw/cmssw/pull/33430#issuecomment-819539087

bug-fix

### CODE REVIEW

**Comment by sroychow** [comment]
bug-fix

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
type bug-fix

**Comment by mmusich** [comment]
@cmsbuild, please test

let's try again

**Comment by jfernan2** [comment]
+1

**Comment by silviodonato** [comment]
please test workflows 2017.13, 2018.13

**Comment by silviodonato** [comment]
@sroychow I suspect that #33430 caused two failures in the IB test of CMSSW_12_0_X_2021-04-19-1100 (see https://cmssdt.cern.ch/SDT/html/cmssdt-ib/#/ib/CMSSW_12_0_X)

https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc900/CMSSW_12_0_X_2021-04-19-1100/pyRelValMatrixLogs/run/2017.13_TTbar_13_UP17+TTbarFS_13_trackingOnlyValidation_UP17+HARVESTUP17FS_trackingOnly/step2_TTbar_13_UP17+TTbarFS_13_trackingOnlyValidation_UP17+HARVESTUP17FS_trackingOnly.log#/

```

A fatal system signal has occurred: segmentation violation
The following is the call stack containing the origin of the signal.

Mon Apr 19 17:58:48 CEST 2021
Thread 2 (Thread 0x2b17b0555700 (LWP 24061)):
#0  0x00002b178e9321d9 in waitpid () from /lib64/libpthread.so.0
#1  0x00002b1797b7e8d7 in edm::service::cmssw_stacktrace_fork() () from /cvmfs/cms-ib.cern.ch/nweek-02677/slc7_amd64_gcc900/cms/cmssw/CMSSW_12_0_X_2021-04-18-0000/lib/slc7_amd64_gcc900/pluginFWCoreServicesPlugins.so
#2  0x00002b1797b7f49a in edm::service::InitRootHandlers::stacktraceHelperThread() () from /cvmfs/cms-ib.cern.ch/nweek-02677/slc7_amd64_gcc900/cms/cmssw/CMSSW_12_0_X_2021-04-18-0000/lib/slc7_amd64_gcc900/pluginFWCoreServicesPlugins.so
#3  0x00002b178e4fcaf0 in std::execute_native_thread_routine (__p=0x2b17a9e9d520) at ../../../../../libstdc++-v3/src/c++11/thread.cc:80
#4  0x00002b178e92aea5 in start_thread () from /lib64/libpthread.so.0
#5  0x00002b178ec3d9fd in clone () from /lib64/libc.so.6
Thread 1 (Thread 0x2b179083a180 (LWP 23849)):
#0  0x00002b178ec32ccd in poll () from /lib64/libc.so.6
#1  0x00002b1797b7ecd7 in full_read.constprop () from /cvmfs/cms-ib.cern.ch/nweek-02677/slc7_amd64_gcc900/cms/cmssw/CMSSW_12_0_X_2021-04-18-0000/lib/slc7_amd64_gcc900/pluginFWCoreServicesPlugins.so
#2  0x00002b1797b7f56c in edm::service::InitRootHandlers::stacktraceFromThread() () from /cvmfs/cms-ib.cern.ch/nweek-02677/slc7_amd64_gcc900/cms/cmssw/CMSSW_12_0_X_2021-04-18-0000/lib/slc7_amd64_gcc900/pluginFWCoreServicesPlugins.so
#3  0x00002b1797b80922 in sig_dostack_then_abort () from /cvmfs/cms-ib.cern.ch/nweek-02677/slc7_amd64_gcc900/cms/cmssw/CMSSW_12_0_X_2021-04-18-0000/lib/slc7_amd64_gcc900/pluginFWCoreServicesPlugins.so
#4  <signal handler called>
#5  0x00002b17968987c9 in dqm::impl::MonitorElement::divide(dqm::impl::MonitorElement const*, dqm::impl::MonitorElement const*, double, double, char const*) () from /cvmfs/cms-ib.cern.ch/nweek-02677/slc7_amd64_gcc900/cms/cmssw/CMSSW_12_0_X_2021-04-18-0000/lib/slc7_amd64_gcc900/libDQMServicesCore.so
#6  0x00002b17c10ace48 in TrackFoldedOccupancyClient::dqmEndJob(dqm::implementation::IBooker&, dqm::implementation::IGetter&) () from /cvmfs/cms-ib.cern.ch/week1/slc7_amd64_gcc900/cms/cmssw-patch/CMSSW_12_0_X_2021-04-19-1100/lib/slc7_amd64_gcc900/pluginDQMTrackingMonitor.so
#7  0x00002b17c1093e84 in non-virtual thunk to DQMEDHarvester::endProcessBlockProduce(edm::ProcessBlock&) () from /cvmfs/cms-ib.cern.ch/week1/slc7_amd64_gcc900/cms/cmssw-patch/CMSSW_12_0_X_2021-04-19-1100/lib/slc7_amd64_gcc900/pluginDQMTrackingMonitor.so
#8  0x00002b178c47a518 in edm::one::EDProducerBase::doEndProcessBlock(edm::ProcessBlockPrincipal const&, edm::ModuleCallingContext const*) () from /cvmfs/cms-ib.cern.ch/nweek-02677/slc7_amd64_gcc900/cms/cmssw/CMSSW_12_0_X_2021-04-18-0000/lib/slc7_amd64_gcc900/libFWCoreFramework.so
#9  0x00002b178c457b90 in edm::WorkerT<edm::one::EDProducerBase>::implDoEndProcessBlock(edm::ProcessBlockPrincipal const&, edm::ModuleCallingContext const*) () from /cvmfs/cms-ib.cern.ch/nweek-02677/slc7_amd64_gcc900/cms/cmssw/CMSSW_12_0_X_2021-04-18-0000/lib/slc7_amd64_gcc900/libFWCoreFramework.so
#10 0x00002b178c364a67 in decltype ({parm#1}()) edm::convertException::wrap<edm::Worker::runModule<edm::OccurrenceTraits<edm::ProcessBlockPrincipal, (edm::BranchActionType)3> >(edm::OccurrenceTraits<edm::ProcessBlockPrincipal, (edm::BranchActionType)3>::TransitionInfoType const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::ProcessBlockPrincipal, (edm::BranchActionType)3>::Context const*)::{lambda()#1}>(edm::Worker::runModule<edm::OccurrenceTraits<edm::ProcessBlockPrincipal, (edm::BranchActionType)3> >(edm::OccurrenceTraits<edm::ProcessBlockPrincipal, (edm::BranchActionType)3>::TransitionInfoType const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::ProcessBlockPrincipal, (edm::BranchActionType)3>::Context const*)::{lambda()#1}) () from /cvmfs/cms-ib.cern.ch/nweek-02677/slc7_amd64_gcc900/cms/cmssw/CMSSW_12_0_X_2021-04-18-0000/lib/slc7_amd64_gcc900/libFWCoreFramework.so
#11 0x00002b178c364c6d in bool edm::Worker::runModule<edm::OccurrenceTraits<edm::ProcessBlockPrincipal, (edm::BranchActionType)3> >(edm::OccurrenceTraits<edm::ProcessBlockPrincipal, (edm::BranchActionType)3>::TransitionInfoType const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::ProcessBlockPrincipal, (edm::BranchActionType)3>::Context const*) () from /cvmfs/cms-ib.cern.ch/nweek-02677/slc7_amd64_gcc900/cms/cmssw/CMSSW_12_0_X_2021-04-18-0000/lib/slc7_amd64_gcc900/libFWCoreFramework.so
#12 0x00002b178c364f16 in std::__exception_ptr::exception_ptr edm::Worker::runModuleAfterAsyncPrefetch<edm::OccurrenceTraits<edm::ProcessBlockPrincipal, (edm::BranchActionType)3> >(std::__exception_ptr::exception_ptr const*, edm::OccurrenceTraits<edm::ProcessBlockPrincipal, (edm::BranchActionType)3>::TransitionInfoType const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::ProcessBlockPrincipal, (edm::BranchActionType)3>::Context const*) () from /cvmfs/cms-ib.cern.ch/nweek-02677/slc7_amd64_gcc900/cms/cmssw/CMSSW_12_0_X_2021-04-18-0000/lib/slc7_amd64_gcc900/libFWCoreFramework.so
#13 0x00002b178c365330 in void edm::SerialTaskQueueChain::actionToRun<edm::Worker::RunModuleTask<edm::OccurrenceTraits<edm::ProcessBlockPrincipal, (edm::BranchActionType)3> >::execute()::{lambda()#1}&>(edm::Worker::RunModuleTask<edm::OccurrenceTraits<edm::ProcessBlockPrincipal, (edm::BranchActionType)3> >::execute()::{lambda()#1}&) () from /cvmfs/cms-ib.cern.ch/nweek-02677/slc7_amd64_gcc900/cms/cmssw/CMSSW_12_0_X_2021-04-18-0000/lib/slc7_amd64_gcc900/libFWCoreFramework.so
#14 0x00002b178c3654e1 in edm::SerialTaskQueue::QueuedTask<edm::SerialTaskQueueChain::push<edm::Worker::RunModuleTask<edm::OccurrenceTraits<edm::ProcessBlockPrincipal, (edm::BranchActionType)3> >::execute()::{lambda()#1}&>(tbb::task_group&, edm::Worker::RunModuleTask<edm::OccurrenceTraits<edm::ProcessBlockPrincipal, (edm::BranchActionType)3> >::execute()::{lambda()#1}&)::{lambda()#1}>::execute() () from /cvmfs/cms-ib.cern.ch/nweek-02677/slc7_amd64_gcc900/cms/cmssw/CMSSW_12_0_X_2021-04-18-0000/lib/slc7_amd64_gcc900/libFWCoreFramework.so
#15 0x00002b178c0f8f49 in tbb::internal::function_task<edm::SerialTaskQueue::spawn(edm::SerialTaskQueue::TaskBase&)::{lambda()#1}>::execute() () from /cvmfs/cms-ib.cern.ch/nweek-02677/slc7_amd64_gcc900/cms/cmssw/CMSSW_12_0_X_2021-04-18-0000/lib/slc7_amd64_gcc900/libFWCoreConcurrency.so
#16 0x00002b178db2226d in tbb::internal::custom_scheduler<tbb::internal::IntelSchedulerTraits>::process_bypass_loop (this=this@entry=0x2b17915e7200, context_guard=..., t=0x2b17915df140, isolation=isolation@entry=0) at ../../include/tbb/task.h:1003
#17 0x00002b178db22756 in tbb::internal::custom_scheduler<tbb::internal::IntelSchedulerTraits>::local_wait_for_all (this=0x2b17915e7200, parent=..., child=<optimized out>) at ../../src/tbb/scheduler.h:650
#18 0x00002b178c332618 in edm::EventProcessor::endProcessBlock(bool, bool) () from /cvmfs/cms-ib.cern.ch/nweek-02677/slc7_amd64_gcc900/cms/cmssw/CMSSW_12_0_X_2021-04-18-0000/lib/slc7_amd64_gcc900/libFWCoreFramework.so
#19 0x00002b178c338451 in edm::EventProcessor::runToCompletion() () from /cvmfs/cms-ib.cern.ch/nweek-02677/slc7_amd64_gcc900/cms/cmssw/CMSSW_12_0_X_2021-04-18-0000/lib/slc7_amd64_gcc900/libFWCoreFramework.so
#20 0x000000000040bae6 in tbb::interface7::internal::delegated_function<main::{lambda()#1}::operator()() const::{lambda()#1} const, void>::operator()() const ()
#21 0x00002b178db1b552 in tbb::interface7::internal::task_arena_base::internal_execute (this=0x7ffc41205fc0, d=...) at ../../src/tbb/arena.cpp:1105
#22 0x000000000040ca13 in main::{lambda()#1}::operator()() const ()
#23 0x000000000040b62c in main ()

Current Modules:

Module: TrackFoldedOccupancyClient:TrackerMapFoldedClient (crashed)

A fatal system signal has occurred: segmentation violation
```

**Comment by silviodonato** [comment]
@sroychow please include the bugfix https://github.com/cms-sw/cmssw/pull/33472

**Comment by mmusich** [comment]
test parameters:
   * workflow = 2017.13, 2018.13, 135.13

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by jfernan2** [comment]
+1

**Comment by mmusich** [comment]
backport of #33430

**Comment by qliphy** [comment]
+1

**Pull request merged**
