### PR TITLE
Made the static fnSigmaRZ const

### PR DESCRIPTION
**Pull request by Dr15Jones**
Problem was found by the static analyzer

### CODE REVIEW

**Comment by davidlange6** [comment]
@cmsbuild, please test

**Comment by Dr15Jones** [comment]
The failure was due to DAS

**Comment by Dr15Jones** [comment]
Please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/7684	4a4daa1
the change is trivial, compilation by jenkins was enough

**Comment by davidlange6** [comment]
+1

**Pull request merged**
