### PR TITLE
Introducing SiPixelCalSingleMuon ALCARECO

### PR DESCRIPTION
**Pull request by tvami**
#### PR description:

This PR introduces a new ALCARECO (`SiPixelCalSingleMuon`) to ease the monitoring work of the Pixel Offline group. Size of the ALCARECO dataset is 0.017 MB/event. 

#### PR validation:

The PR was validated with 
`cmsDriver.py -s RAW2DIGI,RECO,ALCA:SiPixelCalSingleMuon --conditions 110X_dataRun2_2017_2018_Candidate_2019_11_21_04_11_05 --eventcontent=ALCARECO --datatier ALCARECO -n 100 --no_exec --era Run2_2018 --python_filename=SingleMuon_2018_v1.py --nThreads=8 --filein=root://cms-xrd-global.cern.ch//store/data/Run2018C/SingleMuon/RAW/v1/000/320/191/00000/FEC2-FC5C-FE8D-E811-B559-FA163EF38B4B.root`

where the Candidate GT `110X_dataRun2_2017_2018_Candidate_2019_11_21_04_11_05` contains the tag `AlCaRecoTriggerBits_TestForPixelALCARECO_v2` that has the trigger bit that enables this ALCARECO. AlCaDB agreed to provide a proper GT later.

The usual pixel offline trees were produced with it and compared to the results based on RECO files. The outcome is identical and was presented at the AlCaDB meeting yesterday:
[https://indico.cern.ch/event/866816/#4-new-alcareco-for-pixel-offli](https://indico.cern.ch/event/866816/#4-new-alcareco-for-pixel-offli)

#### if this PR is a backport please specify the original PR:

This is not a backport

cc:
@mmusich @tsusa @tocheng

### CODE REVIEW

**Comment by fabiocos** [comment]
please test workflow 136.855

**Comment by mmusich** [comment]
Hi @fabiocos 

> please test workflow 136.855

this is expected to fail, an update to GT is needed for this PR to run.

**Comment by fabiocos** [comment]
@mmusich thank you for the clarification, this anyway means that this PR is not self-contained. @tvami @christopheralanwest what is the plan to have the GT available so as this PR is functional?

**Comment by fabiocos** [comment]
hold

**Comment by tvami** [comment]
> @tvami @christopheralanwest what is the plan to have the GT available so as this PR is functional?

AlCaDB can answer this. What I can do is to modify the auto GT to be this Candidate GT in the description. Is that a preferred way?

**Comment by christopheralanwest** [comment]
@tvami Is this intended to be included for the 2016 UL reprocessing? If not, it will need to wait until PR #28524 is merged, as #28524 modifies the same line in autoCond as this PR.

That said, your candidate `110X_dataRun2_2017_2018_Candidate_2019_11_21_04_11_05` is not suitable for inclusion in autoCond. It replaces the existing multi-IOV tag `AlCaRecoHLTpaths_2017_offline_v2` with a single IOV tag`AlCaRecoTriggerBits_TestForPixelALCARECO_v2`. For changes to the offline `AlCaRecoTriggerBitsRcd`, changes are needed for each IOV in which the ALCARECO should be run.

**Comment by tocheng** [comment]
I am preparing AlCaReco trigger bit for offline data GT to include the new AlCaReco.
Then GT candidate can be made to test the PR and the AlCaReco trigger bit before making GTs.

**Comment by mmusich** [comment]
@tocheng I already prepared a a new multi-IOV tag for that: `AlCaRecoHLTpaths_2017_offline_v3`
in addition all the 11_0_X_phase1_* GTs need to be updated with this tag: `AlCaRecoHLTpaths_2017_MC_v2`

**Comment by tocheng** [comment]
@mmusich Thanks.
Please exercise with the GT candidate.
We will update GT after PR #28524 is merged.

**Comment by mmusich** [comment]
I suggest @tvami to update the branch with  https://github.com/tvami/cmssw/pull/1.
For the record:
```
cmsrel CMSSW_11_0_0_pre13
cd CMSSW_11_0_0_pre13/src/
cmsenv
git cms-addpkg CondTools/HLT
scramv1 b -j 8
cmsRun CondTools/HLT/test/AlCaRecoTriggerBitsRcdRead_TEMPL_cfg.py inputTag=AlCaRecoHLTpaths_2017_offline_v3
cmsRun CondTools/HLT/test/AlCaRecoTriggerBitsRcdRead_TEMPL_cfg.py inputTag=AlCaRecoHLTpaths_2017_offline_v2
cmsRun CondTools/HLT/test/AlCaRecoTriggerBitsRcdRead_TEMPL_cfg.py inputTag=AlCaRecoHLTpaths_2017_MC_v2
cmsRun CondTools/HLT/test/AlCaRecoTriggerBitsRcdRead_TEMPL_cfg.py inputTag=AlCaRecoHLTpaths_2017_MC_v3
```

and then:

```diff
$ diff -u triggerBitsAlCaRecoHLTpaths_2017_MC_v2.twiki triggerBitsAlCaRecoHLTpaths_2017_MC_v3.twiki
--- triggerBitsAlCaRecoHLTpaths_2017_MC_v2.twiki	2019-12-06 18:03:57.065490912 +0100
+++ triggerBitsAlCaRecoHLTpaths_2017_MC_v3.twiki	2019-12-06 18:06:12.962469174 +0100
@@ -37,6 +37,7 @@
 | 'MuAlZMuMu' | 'HLT_Mu*', 'HLT_IsoMu*', 'HLT_DoubleMu*' |
 | 'PromptCalibProdForBS' | 'HLT_*' |
 | 'PromptCalibProdSiStrip' | '*' |
+| 'SiPixelCalSingleMuon' | 'HLT_*' |
 | 'SiPixelLorentzAngle' | '*' |
 | 'SiStripCalMinBias' | 'HLT_*ZeroBias_*' |
 | 'SiStripCalMinBiasHI' | 'HLT_HICentralityVeto_v*' |

```

```diff
$ diff triggerBitsAlCaRecoHLTpaths_2017_offline_v2.twiki triggerBitsAlCaRecoHLTpaths_2017_offline_v3.twiki
53a54
> | 'SiPixelCalSingleMuon' | 'HLT_*' |
137a139
> | 'SiPixelCalSingleMuon' | 'HLT_*' |
221a224
> | 'SiPixelCalSingleMuon' | 'HLT_*' |
305a309
> | 'SiPixelCalSingleMuon' | 'HLT_*' |
389a394
> | 'SiPixelCalSingleMuon' | 'HLT_*' |
473a479
> | 'SiPixelCalSingleMuon' | 'HLT_*' |
557a564
> | 'SiPixelCalSingleMuon' | 'HLT_*' |
641a649
> | 'SiPixelCalSingleMuon' | 'HLT_*' |
725a734
> | 'SiPixelCalSingleMuon' | 'HLT_*' |
809a819
> | 'SiPixelCalSingleMuon' | 'HLT_*' |
893a904
> | 'SiPixelCalSingleMuon' | 'HLT_*' |
977a989
> | 'SiPixelCalSingleMuon' | 'HLT_*' |
1061a1074
> | 'SiPixelCalSingleMuon' | 'HLT_*' |
1145a1159
> | 'SiPixelCalSingleMuon' | 'HLT_*' |
1229a1244
> | 'SiPixelCalSingleMuon' | 'HLT_*' |
1313a1329
> | 'SiPixelCalSingleMuon' | 'HLT_*' |
1397a1414
> | 'SiPixelCalSingleMuon' | 'HLT_*' |
1481a1499
> | 'SiPixelCalSingleMuon' | 'HLT_*' |
1565a1584
> | 'SiPixelCalSingleMuon' | 'HLT_*' |
1649a1669
> | 'SiPixelCalSingleMuon' | 'HLT_*' |
1733a1754
> | 'SiPixelCalSingleMuon' | 'HLT_*' |
1817a1839
> | 'SiPixelCalSingleMuon' | 'HLT_*' |
1901a1924
> | 'SiPixelCalSingleMuon' | 'HLT_*' |
1985a2009
> | 'SiPixelCalSingleMuon' | 'HLT_*' |
2069a2094
> | 'SiPixelCalSingleMuon' | 'HLT_*' |
2153a2179
> | 'SiPixelCalSingleMuon' | 'HLT_*' |
2237a2264
> | 'SiPixelCalSingleMuon' | 'HLT_*' |
2321a2349
> | 'SiPixelCalSingleMuon' | 'HLT_*' |
2405a2434
> | 'SiPixelCalSingleMuon' | 'HLT_*' |
2489a2519
> | 'SiPixelCalSingleMuon' | 'HLT_*' |
2573a2604
> | 'SiPixelCalSingleMuon' | 'HLT_*' |
2657a2689
> | 'SiPixelCalSingleMuon' | 'HLT_*' |
2741a2774
> | 'SiPixelCalSingleMuon' | 'HLT_*' |
2825a2859
> | 'SiPixelCalSingleMuon' | 'HLT_*' |
2909a2944
> | 'SiPixelCalSingleMuon' | 'HLT_*' |
2993a3029
> | 'SiPixelCalSingleMuon' | 'HLT_*' |
3077a3114
> | 'SiPixelCalSingleMuon' | 'HLT_*' |
3161a3199
> | 'SiPixelCalSingleMuon' | 'HLT_*' |
3245a3284
> | 'SiPixelCalSingleMuon' | 'HLT_*' |
3329a3369
> | 'SiPixelCalSingleMuon' | 'HLT_*' |
3413a3454
> | 'SiPixelCalSingleMuon' | 'HLT_*' |
3497a3539
> | 'SiPixelCalSingleMuon' | 'HLT_*' |
3581a3624
> | 'SiPixelCalSingleMuon' | 'HLT_*' |
3665a3709
> | 'SiPixelCalSingleMuon' | 'HLT_*' |
3749a3794
> | 'SiPixelCalSingleMuon' | 'HLT_*' |
3833a3879
> | 'SiPixelCalSingleMuon' | 'HLT_*' |
3917a3964
> | 'SiPixelCalSingleMuon' | 'HLT_*' |
4001a4049
> | 'SiPixelCalSingleMuon' | 'HLT_*' |
4085a4134
> | 'SiPixelCalSingleMuon' | 'HLT_*' |
4169a4219
> | 'SiPixelCalSingleMuon' | 'HLT_*' |
4253a4304
> | 'SiPixelCalSingleMuon' | 'HLT_*' |

```

**Comment by mmusich** [comment]
@tocheng @christopheralanwest 

>  Please exercise with the GT candidate.

unfortunately the candidates for the data run2 key don't work as I believe the autoCond as evolved with respect to the queue:

from https://github.com/cms-sw/cmssw/blob/master/Configuration/AlCa/python/autoCond.py#L29
```python
    'run2_data'         :   '110X_dataRun2_v8',
```

and:

```
 conddb diff 110X_dataRun2_v8 110X_dataRun2_2017_2018_Queue
[2019-12-06 18:55:02,824] INFO: Connecting to pro [frontier://PromptProd/CMS_CONDITIONS]
Record            Label   pro::110X_dataRun2_v8 Tag   pro::110X_dataRun2_2017_2018_Queue Tag   
----------------  ------  --------------------------  --------------------------------------   
HcalRespCorrsRcd  bugged  HcalRespCorrs_v6.3_offline  -                   
```

can the queue be updated ?

**Comment by mmusich** [comment]
@tvami this now requires a new rebase.

**Comment by mmusich** [comment]
as #28524 is merged, I think this PR can be tested meaningfully (at least on a technical side). For moving on we'll need updated Global Tags.

**Comment by fabiocos** [comment]
please test workflow 136.855

**Comment by christopheralanwest** [comment]
please test workflow 136.855

**Comment by tvami** [comment]
I've removed the dependencies from the GTs to make integration faster. Anyway, changing the trigger bit might be relevant for Run3 only, so regarding the past having the trigger bit in GT is not essential. Any changes for Run3 will be addressed later in another PR.  @fabiocos @christopheralanwest @tocheng can you please initiate a test and remove the hold? Thanks!

**Comment by fabiocos** [comment]
please test workflow 136.855

**Comment by mmusich** [comment]
As in the last bunch of commits a new ALCARECO acting on the cosmics processing scenario is added, I am wondering if appropriate tests can be invoked here.
I tested privately with `runTheMatrix.py -l 7.22,7.21,7.4,7.3, 138.1 -t 4 -j 8`

**Comment by christopheralanwest** [comment]
please test workflow 7.22,7.21,7.4,7.3,138.1

**Comment by mmusich** [comment]
@fabiocos please remove the lift from this PR or clarify remaining concerns.
Thanks

**Comment by fabiocos** [comment]
unhold

the pending issues preventing the validation of this PR looks solved. @christopheralanwest @tlampen could you please proceed with another round of review?
@chayanit @kpedro88 please have a look

**Comment by kpedro88** [comment]
+upgrade

**Comment by chayanit** [comment]
+1

**Comment by fabiocos** [comment]
+operations

the update of central configurations is coherent with the purpose of the PR

**Comment by fabiocos** [comment]
@christopheralanwest @tocheng @tlampen could you please check and comment or sign it? Thanks

**Comment by tocheng** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Comment by silviodonato** [comment]
@tvami This PR is not working with Python3. 
See https://cmssdt.cern.ch/SDT/html/cmssdt-ib/#/relVal/CMSSW_11_1/2020-01-08-2300?selectedArchs=slc7_amd64_gcc820&selectedFlavors=PY3_X&selectedStatus=failed

In python3 we get errors like
` [...]
  File "/cvmfs/cms-ib.cern.ch/nweek-02610/slc7_amd64_gcc820/cms/cmssw-patch/CMSSW_11_1_PY3_X_2020-01-08-2300/python/Configuration/StandardSequences/AlCaRecoStreams_cff.py", line 38, in &lt;module&gt;
    from Calibration.TkAlCaRecoProducers.ALCARECOSiPixelCalCosmics_cff import *
  File "/cvmfs/cms-ib.cern.ch/nweek-02610/slc7_amd64_gcc820/cms/cmssw-patch/CMSSW_11_1_PY3_X_2020-01-08-2300/python/Calibration/TkAlCaRecoProducers/ALCARECOSiPixelCalCosmics_cff.py", line 16, in &lt;module&gt;
    from ALCARECOSiPixelCalSingleMuon_cff import ALCARECOSiPixelCalSingleMuonHLTFilter 
ModuleNotFoundError: No module named 'ALCARECOSiPixelCalSingleMuon_cff'`

Could you test it again and fix using our latest working PY3 IB ( CMSSW_11_1_PY3_X_2020-01-07-2300 ) ? Thanks!

**Comment by mmusich** [comment]
@silviodonato 

> Could you test it again and fix using our latest working PY3 IB ( CMSSW_11_1_PY3_X_2020-01-07-2300 )

Fixed at https://github.com/cms-sw/cmssw/pull/28722

**Comment by silviodonato** [comment]
> @silviodonato
> 
> > Could you test it again and fix using our latest working PY3 IB ( CMSSW_11_1_PY3_X_2020-01-07-2300 )
> 
> Fixed at #28722

Thanks!

**Pull request merged**
