### PR TITLE
condTestRegression: Use correct singularity container for old cmssw release

### PR DESCRIPTION
**Pull request by smuzaffar**
This fixes the condTestRegression unit test
- use python3 instead of python. On `el9`, this tests fails as we do not install system python(2)
- Use the correct singularity ciontainers for old releases e.g. slc6 based cmssw releases. Unit test fails under `el9` with error [a]. This is because we tryto run `slc6` base cmssw binaries under `el9`. This PR should now run the old releases binaries under corrent cms env.

[a]
```
===== Test "condTestRegression" ====
/cvmfs/cms.cern.ch/slc6_amd64_gcc630/cms/cmssw/CMSSW_9_0_1/test/slc6_amd64_gcc630/testReadWritePayloads: error while loading shared libraries: libcrypt.so.1: cannot open shared object file: No such file or directory

__init__() took 0.559 ms

================================================================================
going to write DBs ...

runSelf(write) took 3659.459 ms

Traceback (most recent call last):
  File "CMSSW_12_5_X_2022-06-06-2300/src/CondCore/CondDB/test/condTestRegression.py", line 254, in <module>
    crt.runAll()
  File "CMSSW_12_5_X_2022-06-06-2300/src/CondCore/CondDB/test/condTestRegression.py", line 58, in wrapper
    res = func(*arg)
  File "CMSSW_12_5_X_2022-06-06-2300/src/CondCore/CondDB/test/condTestRegression.py", line 215, in runAll
    self.run(rel, arch, 'write', dbName)
  File "CMSSW_12_5_X_2022-06-06-2300/src/CondCore/CondDB/test/condTestRegression.py", line 58, in wrapper
    res = func(*arg)
  File "CMSSW_12_5_X_2022-06-06-2300/src/CondCore/CondDB/test/condTestRegression.py", line 160, in run
    raise e
  File "CMSSW_12_5_X_2022-06-06-2300/src/CondCore/CondDB/test/condTestRegression.py", line 157, in run
    res = check_output(cmd, shell=True, universal_newlines=True, env={}, stdin=subprocess.PIPE, stdout=subprocess.PIPE)
  File "CMSSW_12_5_X_2022-06-06-2300/src/CondCore/CondDB/test/condTestRegression.py", line 48, in check_output
    raise subprocess.CalledProcessError(returnCode, cmd+msg)
```

### CODE REVIEW

**Comment by smuzaffar** [comment]
@ggovi , cmssw releases/archs list [here](https://github.com/cms-sw/cmssw/pull/38269/files#diff-a63a0192b888a8ed22ba21db3f459ad380f1a9d7cd8a5559a1043214b43b157dR28-R31) is very old. Should we update it to include new cmssw releases/archs?

**Comment by iarspider** [comment]
@smuzaffar I see that [many other scripts](https://gist.github.com/iarspider/501fc74e2951ef17b73d45a98fa8e170) use `#!/usr/bin/env python` hashbang, should these be updated as well?

**Comment by smuzaffar** [comment]
> @smuzaffar I see that [many other scripts](https://gist.github.com/iarspider/501fc74e2951ef17b73d45a98fa8e170) use `#!/usr/bin/env python` hashbang, should these be updated as well?

@iarspider I guess we are not running these script during IBs tests (otherwise `el9` tests should fail as there is no `python` command available it). So there is no point fixing these as we can not test these :-( may be at some porint we can drop these

**Comment by tvami** [comment]
>  Should we update it to include new cmssw releases/archs?

I think we should. Do you plan to do that in this PR or a follow-up (by @ggovi )?

**Comment by smuzaffar** [comment]
> > Should we update it to include new cmssw releases/archs?
> 
> I think we should. Do you plan to do that in this PR or a follow-up (by @ggovi )?

new releases/archs can go in separate PR

**Comment by tvami** [comment]
+db
 * both tests pass
 * further changins coming up in a next PR, see https://github.com/cms-sw/cmssw/pull/38269#issuecomment-1149003763

**Comment by qliphy** [comment]
+1

**Pull request merged**
