### PR TITLE
Run3-sim96 Make use of one/EDAnalyzer in a few analysis codes of SimG4CMS

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Make use of one/EDAnalyzer in a few analysis codes of SimG4CMS

#### PR validation:

Use runTheMatrix test workflows

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
