### PR TITLE
optimize `SiPixelCompareRecHits`

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

This PR is a light optimization of the module `SiPixelCompareRecHits` that needs to run in the HLT menu because of issue https://github.com/cms-sw/cmssw/issues/44700. 
The optimization mainly lies in grouping the hits in `rhsoaTar` by their `detectorIndex()` in a hash map. 
This way, for each hit in `rhsoaRef`, it is only needed to search for matching hits in `rhsoaTar` with the same `detectorIndex`. This reduces the number of unnecessary comparisons.
Additionally replaced `std::ceil` with integer division to avoid costly floating-point operations for calculating `sizeX` and `sizeY`.

#### PR validation:

I've run the following script on `lxplus-gpu`:

```bash
#!/bin/bash -ex

startDir=$PWD

mkdir vanilla
cd vanilla
scram p CMSSW CMSSW_14_2_X_2024-11-04-2300
cd CMSSW_14_2_X_2024-11-04-2300/src
eval `scramv1 runtime -sh`
addOnTests.py -t hlt_data_GRun
sleep 10
cd $startDir
mkdir mods
cd mods
scram p CMSSW CMSSW_14_2_X_2024-11-04-2300
cd CMSSW_14_2_X_2024-11-04-2300/src
eval `scramv1 runtime -sh`
git cms-addpkg DQM/SiPixelHeterogeneous
git cherry-pick e54723e43f097869c94beb6f06aaae7e599ae305
scram b -j 20
addOnTests.py -t hlt_data_GRun
```

The timing advantage is not measured precisely, but roughly speaking it's a factor 40.

```bash
$ more testing/vanilla/CMSSW_14_2_X_2024-11-04-2300/src/addOnTests/hlt_data_GRun/step2.log | grep hltSiPixelRecHitsSoACompareGPUvsCPU | grep TimeReport
TimeReport   0.353061     0.353061  hltSiPixelRecHitsSoACompareGPUvsCPU
TimeReport   0.353061     0.353061     0.353061  hltSiPixelRecHitsSoACompareGPUvsCPU
$ more testing/mods/CMSSW_14_2_X_2024-11-04-2300/src/addOnTests/hlt_data_GRun/step2.log | grep hltSiPixelRecHitsSoACompareGPUvsCPU | grep TimeReport
TimeReport   0.008550     0.008550  hltSiPixelRecHitsSoACompareGPUvsCPU
TimeReport   0.008550     0.008550     0.008550  hltSiPixelRecHitsSoACompareGPUvsCPU
```

Then harvested the resulting `DQMIO.root` output files with the file in [1] and finally compared the results with the macro in [2].

I have put the resulting outputs at [this link](https://marcomusich.web.cern.ch/TSG/optimizeCompareRechits/).

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Not a backport, might be backported to CMSSW_14_1_X if accepted.

----

[1]
<details>
  <summary>Click me</summary>

```python
import FWCore.ParameterSet.Config as cms

## CLI parser
import argparse
import sys

parser = argparse.ArgumentParser(
    prog = 'cmsRun '+sys.argv[0]+' --',
    description = 'Configuration file to run the DQMFileSaver on DQMIO input files.',
    formatter_class = argparse.ArgumentDefaultsHelpFormatter
)

parser.add_argument('-t', '--nThreads', type = int, help = 'Number of threads',
                    default = 4)

parser.add_argument('-s', '--nStreams', type = int, help = 'Number of EDM streams',
                    default = 0)

parser.add_argument('-i', '--inputFiles', nargs = '+', help = 'List of DQMIO input files',
                    default = ['file:testHLTFiltersDQMonitor_DQMIO.root'])

args = parser.parse_args()

# Process
process = cms.Process('HARVESTING')

process.options.numberOfThreads = args.nThreads
process.options.numberOfStreams = args.nStreams
process.options.numberOfConcurrentLuminosityBlocks = 1

# Source (DQM input)
process.source = cms.Source('DQMRootSource',
  fileNames = cms.untracked.vstring(sorted(list(set([f'file:{foo}' for foo in args.inputFiles]))))
)

# DQMStore (Service)
process.load('DQMServices.Core.DQMStore_cfi')

# MessageLogger (Service)
process.load('FWCore.MessageLogger.MessageLogger_cfi')

# Output module (file in ROOT format)
from DQMServices.Components.DQMFileSaver_cfi import dqmSaver as _dqmSaver
process.dqmSaver = _dqmSaver.clone(
  workflow = '/DQMOffline/Trigger/'+process.name_()
)

# EndPath
process.endp = cms.EndPath(
    process.dqmSaver
)
```
</details>

[2]

<details>
  <summary>Click me</summary>

```C++
#include <TFile.h>
#include <TH1.h>
#include <TH2.h>
#include <TCanvas.h>
#include <TKey.h>
#include <TDirectory.h>
#include <TSystem.h>
#include <string>

void comparePlots(const char* file1 = "DQM_vanilla.root", const char* file2 = "DQM_mod.root") {
    // Open the ROOT files
    TFile *f1 = TFile::Open(file1);
    TFile *f2 = TFile::Open(file2);
    if (!f1 || !f2 || f1->IsZombie() || f2->IsZombie()) {
        printf("Error opening files.\n");
        return;
    }

    // Define the target directory path
    const char* targetDir = "DQMData/Run 386071/SiPixelHeterogeneous/Run summary/PixelRecHitsCompareGPUvsCPU";

    // Navigate to the target directory in each file
    TDirectory *dir1 = (TDirectory*)f1->Get(targetDir);
    TDirectory *dir2 = (TDirectory*)f2->Get(targetDir);
    if (!dir1 || !dir2) {
        printf("Directory %s not found in one or both files.\n", targetDir);
        return;
    }

    // Create an output folder for the saved images if it doesn't exist
    gSystem->Exec("mkdir -p output_images");

    // Loop over all keys (objects) in the directory
    TIter next(dir1->GetListOfKeys());
    TKey *key;
    while ((key = (TKey*)next())) {
        TObject *obj1 = key->ReadObj();
        std::string objName = obj1->GetName();

        // Check if the same object exists in the second file directory
        TObject *obj2 = dir2->Get(objName.c_str());
        if (!obj2) {
            printf("Object %s not found in both files.\n", objName.c_str());
            continue;
        }

        // Create a canvas for each comparison
        TCanvas *canvas = new TCanvas((objName + "_canvas").c_str(), objName.c_str(), 1600, 800);

	if (obj1->InheritsFrom("TH2") && obj2->InheritsFrom("TH2")) {
	  // Juxtapose 2D histograms
	  TH2 *hist1 = (TH2*)obj1;
	  TH2 *hist2 = (TH2*)obj2;
	  
	  canvas->Divide(2, 1);
	  canvas->cd(1);
	  hist1->Draw("COLZ");
	  canvas->cd(2);
	  hist2->Draw("COLZ");
        } else if (obj1->InheritsFrom("TH1") && obj2->InheritsFrom("TH1")) {
            // Overlay 1D histograms
	  TH1 *hist1 = (TH1*)obj1;
	  TH1 *hist2 = (TH1*)obj2;
	  
	  hist1->SetLineColor(kBlue);
	  hist1->Draw("HIST");
	  hist2->SetLineColor(kRed);
	  hist2->Draw("HIST SAME");
	  
	  // Add a legend
	  TLegend *legend = new TLegend(0.7, 0.8, 0.9, 0.9);
	  legend->AddEntry(hist1, "DQM_vanilla", "l");
	  legend->AddEntry(hist2, "DQM_mod", "l");
	  legend->Draw();
        } else {
	  printf("Skipping non-histogram or mismatched object types: %s\n", objName.c_str());
	  delete canvas;
	  continue;
        }

        // Save the canvas as a PNG file
        std::string savePath = "output_images/" + objName + ".png";
        canvas->SaveAs(savePath.c_str());
        delete canvas;  // Clean up canvas to avoid memory leaks
    }

    // Close the files
    f1->Close();
    f2->Close();
    delete f1;
    delete f2;

    printf("Comparison plots saved in the output_images directory.\n");
}
```
</details>

### CODE REVIEW

**Comment by mmusich** [comment]
enable gpu

**Comment by mmusich** [comment]
test parameters:
   * workflow_opts_gpu= -w upgrade
   * workflows_gpu= 12434.403, 12434.503, 12634.403

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by antoniovagnerini** [comment]
+1
- spurious differences from HGCal DQM test (open issue  #46416)

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
