### PR TITLE
 Set default HI Stage1 parameters, disable override

### PR DESCRIPTION
**Pull request by harmonicoscillator**
@mulhearn @mandrenguyen 
This PR is meant to go on top of #12364 , and disables the manual override of the HI Stage1 Level-1 trigger parameters since we expect to get the real information from the GT.

@mulhearn suggests that we wait for the GT to actually be made before merging this, but I am of the opinion that we should just go ahead and do it so that we don't need to wait for a PR merge and new release when the new GT is made. Comments welcome.

### CODE REVIEW

**Comment by mulhearn** [comment]
Alca/DB has clear preference for waiting for new GT.  I guess the main point is that once #12366 is merged, all future updates should have no effect on the actual output of emulation...

**Comment by davidlange6** [comment]
@mulhearn - i'm not sure how to interpret your last message? We should not merge this?

**Comment by mulhearn** [comment]
This PR removes the HI customizations which set CaloParams to HI payloads (instead of taking them from GT).  There are at the moment no HI payloads in GT, even for e.g. HI MC tags.  That means, if this is merged at the moment, the configuration will come from GT, meaning it will be a PP payload, even for HI, and the result for HI workflows will be garbage.  Therefore, I prefer to wait to merge this until the new GT for HI is available which includes the HI payloads, at which point, the combined operation of this PR plus adding the new GT will have zero impact.  Does that sound reasonable?

**Comment by mulhearn** [comment]
Note that DQM for HI should simply merge this locally, once Khristian gets the HI O2O up and running.

**Comment by slava77** [comment]
@richard-cms is this PR still relevant?
The part that went to 75X already (with #12364) should probably be removed

**Pull request merged**
