### PR TITLE
Remove Duplicate RelVals from `relval_highstats.py` and Smaller Queries for `das-up-to-nevents.py`

### PR DESCRIPTION
**Pull request by AdrianoDee**
#### PR description:

This PR proposes few things:

1. to remove the duplicate RelVals in `relval_highstats.py` already added in `relval_data_highstats.py` by https://github.com/cms-sw/cmssw/pull/45055. Without this `runTheMatrix.py -w data,highstats -n`  complains about duplicates:

```
==> duplicate name found for  2024.4141_RunZeroBias2024F_1M
    keeping  :  (2024.4141, 'RunZeroBias2024F_1M', [<Configuration.PyReleaseValidation.MatrixUtil.InputInfo object at 0x7f2bcc55d700>, 'cmsDriver.py step2  --process reHLT -s L1REPACK:Full,HLT:@relval2024 --conditions auto:run3_hlt_relval --data  --eventcontent FEVTDEBUGHLT --datatier FEVTDEBUGHLT --era Run3_2024', 'cmsDriver.py step3  --conditions auto:run3_data_prompt_relval -s RAW2DIGI,L1Reco,RECO,PAT,NANO,DQM:@standardDQM+@miniAODDQM+@nanoAODDQM --datatier AOD,MINIAOD,NANOAOD,DQMIO --eventcontent AOD,MINIAOD,NANOEDMAOD,DQM --data  --process reRECO --scenario pp --era Run3 --customise Configuration/DataProcessing/RecoTLR.customisePostEra_Run3 --hltProcess reHLT', 'cmsDriver.py step4  -s HARVESTING:@standardDQM+@miniAODDQM+@nanoAODDQM --conditions auto:run3_data --data  --filetype DQM --scenario pp --era Run3'], ['RunZeroBias2024F_1M', 'HLTDR3_2024', 'AODNANORUN3_reHLT_2024', 'HARVESTRUN3_2024'])
    ignoring :  (2024.4141, 'RunZeroBias2024F_1M', [<Configuration.PyReleaseValidation.MatrixUtil.InputInfo object at 0x7f2bcc55d700>, 'cmsDriver.py step2  --process reHLT -s L1REPACK:Full,HLT:@relval2024 --conditions auto:run3_hlt_relval --data  --eventcontent FEVTDEBUGHLT --datatier FEVTDEBUGHLT --era Run3_2024', 'cmsDriver.py step3  --conditions auto:run3_data_prompt_relval -s RAW2DIGI,L1Reco,RECO,PAT,NANO,DQM:@standardDQM+@miniAODDQM+@nanoAODDQM --datatier AOD,MINIAOD,NANOAOD,DQMIO --eventcontent AOD,MINIAOD,NANOEDMAOD,DQM --data  --process reRECO --scenario pp --era Run3 --customise Configuration/DataProcessing/RecoTLR.customisePostEra_Run3 --hltProcess reHLT', 'cmsDriver.py step4  -s HARVESTING:@standardDQM+@miniAODDQM+@nanoAODDQM --conditions auto:run3_data --data  --filetype DQM --scenario pp --era Run3'], ['RunZeroBias2024F_1M', 'HLTDR3_2024', 'AODNANORUN3_reHLT_2024', 'HARVESTRUN3_2024'])
````

2. adjusted `das-up-to-nevents.py` to run DAS queries run per run up to the number of events requested in order to have smaller queries to be cached by cms-bot. This should fix the DAS query failures observed in latest tests.
 
3. moving most of the 2024 data wfs from `relval_standard.py` to `relval_data_highstats.py` so that they don't get run in the IBs (since it's not really needed). This reduce the 2024 wfs to be run in an IB from 75 to 4.
#### PR validation:

`runTheMatrix.py -w data,highstats -n` 

does not complain about duplicates anymore.

### CODE REVIEW

**Comment by AdrianoDee** [comment]
type bug-fix

**Comment by AdrianoDee** [comment]
please test

**Comment by AdrianoDee** [comment]
please test

**Comment by AdrianoDee** [comment]
please test

**Comment by smuzaffar** [comment]
@AdrianoDee , how about reducing the number of events  for `2024.*` workflows?

**Comment by smuzaffar** [comment]
you might have noticed that many `2024.*` workflows are timing out for IBs. These new workflows also has double the relval test time for IBs. If we do not keep this in control then I am afraid we can only one one IB per day ( instead of every 12 hours)

**Comment by smuzaffar** [comment]
you can find all relvals/step3 which are taking over 2.5 hours [here](https://cern.ch/xjuet)

**Comment by AdrianoDee** [comment]
> you can find all relvals/step3 which are taking over 2.5 hours [here](https://cern.ch/xjuet)

Thanks @smuzaffar, apparently I can't access the link (I get "Unauthorized to log in").

**Comment by smuzaffar** [comment]
link should be accessible after SSO login

**Comment by AdrianoDee** [comment]
> link should be accessible after SSO login

Seems not for me :-/

Screenshot 2024-08-24 alle 18 23 26

**Comment by AdrianoDee** [comment]
> 3. moving most of the 2024 data wfs from `relval_standard.py` to `relval_data_highstats.py` so that they don't get run in the IBs (since it's not really needed). This reduce the 2024 wfs to be run in an IB from 75 to 4.

For the moment I've reduced the workflows to be run (they were way too many).

**Comment by AdrianoDee** [comment]
please test

**Comment by AdrianoDee** [comment]
please test

It seems to me the unit test failure is unrelated and I can't reproduce it offline (not even using the cms-bot DAS client).

**Comment by mmusich** [comment]
urgent
  * to remove IB and PR tests failures

**Comment by srimanob** [comment]
+Upgrade

**Comment by AdrianoDee** [comment]
+pdmv

**Pull request merged**
