### PR TITLE
adding MINIAODSIM in RECODBG and RECOPUDBG steps

### PR DESCRIPTION
**Pull request by mrodozov**
Adding MINIAODSIM to RECODBG and RECOPUDBG to resolve the issue mentioned here https://github.com/cms-sw/cmssw/pull/20568#issuecomment-331879776

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please abort

**Comment by mrodozov** [comment]
please test workflow 4000.0,4001.0,4007.0,4008.0

**Comment by smuzaffar** [comment]
@davidlange6 , I am merging it to get the 4 failing work flows fixed.

**Pull request merged**
