### PR TITLE
[PY3] updated CondTools/SiStrip scripts to use python3

### PR DESCRIPTION
**Pull request by smuzaffar**

### CODE REVIEW

**Comment by smuzaffar** [comment]
test parameters:
- addpkg = CondTools,CondFormats

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by qliphy** [comment]
@smuzaffar   This can be closed after https://github.com/cms-sw/cmssw/pull/34474 is merged, right?

**Comment by smuzaffar** [comment]
correct, closing it now

**Pull request closed without merging**
