### PR TITLE
[TRK Validation] add chi2 and chi2prob plots, and pT-eta plane for efficiency and fake in slices

### PR DESCRIPTION
**Pull request by mtosi**
#### PR description:

during the validation of the Phase2 tracker layout in D42 (vs D41)
we realized the <chi2/ndof> vs eta plot is available only for all the tracks,
so polluted / diluted by fakes and duplicate tracks,
@emiglior and I think the <chi2/ndof> for just the reconstructed tracks matched to a tracking particle would help in understanding the effect of the material

in addition, I realized we were missing the chi2prob distributions, ans I added them as well

last, in the current MTV version 2D plots w/ the efficiency and fake in the (pT-eta) planes are missing,
and they could be useful for checking the performance in different eta ranges

#### PR validation:
cd $CMSSW_BASE/src
scram b distclean 
git cms-checkdeps -a -A
scram b -j 24
scram b runtests

cd /tmp/tosi/
runTheMatrix.py -l limited -i all --ibeos

#### if this PR is a backport please specify the original PR:
it is not, but I think it would be great if we could have a backport in each of the still opened cycles

### CODE REVIEW

**Comment by mtosi** [comment]
while checking the PR, I got an error in the HARVESTING step [1]
which is triggered by
[https://cmssdt.cern.ch/dxr/CMSSW/source/DQMServices/ClientConfig/plugins/DQMGenericClient.cc#619](https://cmssdt.cern.ch/dxr/CMSSW/source/DQMServices/ClientConfig/plugins/DQMGenericClient.cc#619)
if the ME is not TH1F (!)

I'm bypassing the problem by adding an extra module with the untracked parameter `makeGlobalEffienciesPlot = cms.untracked.bool(False)`

but I think the core DQM should fix that part of the central code @fioriNTU @jmduarte

**Comment by mtosi** [comment]
@cmsbuild, please test

**Comment by jfernan2** [comment]
+1

**Comment by mtosi** [comment]
ciao
@fabiocos , sorry for bothering you,
could you please remind me which are the open cycles (a part the CMSSW_10_6_X), now ?
I would like to make the backport for all of them
thanks

**Comment by fabiocos** [comment]
@mtosi master is now 11_0_X. 10_6_X is the UL release. 10_2_X is used for ongoing analysis, but I wonder why you would like to bring this there.

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
@mtosi @jfernan2 the memory increase implied by this PR is quite substantial. Is there any possible optimization?

**Comment by mtosi** [comment]
ciao
I’m on holidays, now
I can give a look at this next week

**Pull request merged**
