### PR TITLE
MSSM Hbb trigger dqm updates for 2024 triggers [14_1_X]

### PR DESCRIPTION
**Pull request by robervalwalsh**
#### PR description:

This PR contains updates to the trigger DQM for the modified MSSM Hbb triggers for 2024.

- https://its.cern.ch/jira/browse/CMSHLT-3024
- https://its.cern.ch/jira/browse/CMSHLT-3080

It mainly consists in updating the following:

- trigger paths and trigger objects names
- offline btagging for the relative efficiencies
- moving from HIG → SUS

#### PR validation:

Release: CMSSW_14_1_X_2024-02-29-2300

`runTheMatrix.py -l limited -i all --ibeos`
- All 2024 tests passed. Only one 2011 test failed (see below), which is not related to the updates requested here.
- `48 47 45 35 18 1 1 1 1 1 1 tests passed, 0 0 1 0 0 0 0 0 0 0 0 failed`
```
1000.0_RunMinBias2011A Step0-PASSED Step1-PASSED Step2-FAILED Step3-NOTRUN Step4-NOTRUN  - time date Fri Mar  1 10:42:17 2024-date Fri Mar  1 10:36:06 2024; exit: 0 0 22016 0 0

%MSG-w SiStripRawToDigi:  SiStripRawToDigiModule:siStripDigis@endStream  01-Mar-2024 10:40:46 CET PostEndProcessBlock
[sistrip::RawToDigiUnpacker::createDigis] warnings:
NULL pointer to FEDRawData for FED (100)
```

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Not a backport, but it should be backported to CMSSW_14_0_X

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
@robervalwalsh thanks for this. We'll need also a 14.0.X backport for the data-taking release.

**Comment by tjavaid** [comment]
+1

**Comment by rappoccio** [comment]
+1

**Comment by mmusich** [comment]
> We'll need also a 14.0.X backport for the data-taking release.

to speed up integration I took the liberty of opening a backport https://github.com/cms-sw/cmssw/pull/44366 (@robervalwalsh FYI)

**Pull request merged**
