### PR TITLE
DQM: Switch to `edm::stream` for `DQMEDAnalyzer`

### PR DESCRIPTION
**Pull request by schneiml**
#### PR description:
This PR cashes in on the work in #28622 and all the previous PRs, by changing the module type of `DQMEDAnalyzer` back to `edm::stream`. This should significantly reduce the number of modules blocking concurrent lumisections on production sequences.

This PR depends on #28622 *and includes it*, it should be merged once the other one is in. For now, this is to allow some validation of this change. [Edit: #28622 is in! Rebased on top of it. Validation will still take a while.] [Edit2: #28916 brought in some of the changes that used to be here/are required here, that makes this one a bit cleaner.]

`DQMEDAnalyzer` used to be `edm::stream` based from 2015 to 2018, so *basically* not much should break. However, over the last two years DQM has changed, and some modules grew dependencies on `edm::one` behaviour, while others where migrated from legacy `edm::EDAnalyzer` to `DQMEDAnalyzer` as this became possible. This PR includes a lot of changes to these modules to remove their usage of `beginJob`/`endJob` methods: While we could provide it (and call it e.g. from `beginStream`/`endStream`), it does not make much sense, and most of the modules don't do anything important there anyways. So, I rather banned and removed those methods.

In a few cases, there was non-trivial logic that I'd rather keep, those where migrated to `DQMOneEDAnalyzer` which still provides those methods. However, it still does not make much sense to do anything in `endJob` in a `DQMEDAnalyzer`, since by the time it is called, the DQM output is typically already written to file.

A large number of `DQMOneEDAnalyzer`s remain, so we won't get concurrent LS immediately. These modules need to be either reviewed and rewritten in a concurrent-lumi save way (e.g. by using `LuminosityBlockCache`s), or removed from the production sequences.

Back in 2018, we moved to `edm::one` to reduce memory usage. This change gets us the best of both worlds: concurrent processing while the memory usage stays within O(#concurrentLS), compared to the O(#streams) in 2015, thanks to the new `DQMStore` logic added in #28622.

#### PR validation:

Not much so far, and it is going to be hard. The PR/IB tests barely use multi-threaded execution, leave alone concurrent LS. The big risk are race conditions, which are notoriously hard to spot, even when the right code paths are executed. A clean, bit-by-bit comparison on a larger sample might be a good idea.

### CODE REVIEW

**Comment by schneiml** [comment]
please test

let's see what happens. So local tests looked ok'ish.

**Comment by slava77** [comment]
> This PR depends on #28622 _and includes it_, it should be merged once the other one is in. For now, this is to allow some validation of this change.

this is rather confusing, esp considering a bunch of comments apparently pending in the other PR

**Comment by schneiml** [comment]
@slava77 yes, but there is no other way (I know of) to get PR tests, and waiting for each previous PR to be merged is way too slow if we want to make it into 11_1. The "test with" trick probably only works if things merge cleanly, which these two surely don't.

For your purposes, just ignore it (feel free to -1), the new stuff is in the last two commits and should not affect reco.

**Comment by schneiml** [comment]
The comparison looks very similar to #28622, as expected.

The unit test crash however is more worrying: It looks like a race in the multi-threaded load test, where a stream tries to fill a histogram that is not yet prepared for the new lumisection. To be investigated.

**Comment by schneiml** [comment]
please test

The new commits fix a bug in the `DQMStore` (that could be back-ported into #28622, though it does not change much) and a bug in the `DQMEDAnalyzer`, so now the unit test passes. It turns out the problem was not a real race (as I feared), but just the problem that the different `edm::stream` instances where not using independent local MEs. (It was a race in the end, but caused by this much more fundamental problem). Now things should work much better, though the PR tests probably won't pick up the difference.

**Comment by schneiml** [comment]
The changes I just pushed are unrelated to `edm::stream` (mostly), I'll probably rebase them into #28622 on the next occasion, but for now they are on this branch.

**Comment by schneiml** [comment]
please test

Now, the last few commits should fix the crashes in the add-on tests. However, these do point out a bigger problem: `Sumw2` in ROOT fails when called more than once (which EDM translates into a crash).

I fixed the few validation modules affected in the FastSim tests, but this will blow up in many places when we actually run the prod sequences multi-threaded. We *really* need a "normal" (say, 136-style data relval) running multi-threaded in the PR tests.

**Comment by makortel** [comment]
> `Sumw2` in ROOT fails when called more than once (which EDM translates into a crash).

IIRC that has been the case for a long time.

**Comment by schneiml** [comment]
@makortel yes probably, but now since we have `edm::stream` modules *and* hand out the same histogram in each of the `nstreams` booking calls, it will blow up wherever it is used.

I think the best is to make our `ME::setSumw2` check and ignore additional calls, and migrate the remaining code, though ignoring this error/warning(?) on EDM level would also be an option. 

In the longer term, all the booking-customization code should move into callbacks (@Dr15Jones offered core team help for that, is the offer still on? After #28622 the work could begin), but for this PR it is not really required, since *all* of the booking code is still run while holding the single booking lock. Releasing that is now quite possible on DQM framework side, but then `getTH1` becomes racy and illegal even in booking and there are still 100's (probably) of usages to be cleaned up first.

**Comment by makortel** [comment]
> (@Dr15Jones offered core team help for that, is the offer still on? After #28622 the work could begin)

The offer is still on.

**Comment by slava77** [comment]
-1

merge conflicts

**Comment by schneiml** [comment]
This one now needs rebase to new #28622, but I'll wait a bit until that one is converged. We shall keep in mind the trouble related to `sumw2`.

**Comment by schneiml** [comment]
please test

Rebased onto `CMSSW_11_1_X_2020-02-10-2300`, which cleans up the diff *a lot*. The output comparison should also be pretty clean now (though, it is also rather meaningless, since there are no (?) multi-threaded jobs in the short matrix).

**Comment by schneiml** [comment]
Comparison is reassuringly clean, but this will need another rebase after #28916 and also might still need further fixes.

**Comment by Dr15Jones** [comment]
@schneiml do you want the tests to start?

**Comment by schneiml** [comment]
please test

@Dr15Jones probably yes. I was waiting for some local tests first, but got distracted.

**Comment by schneiml** [comment]
I ran a private comparison using 16 streams/threads on wf 136.8862 (with concurrent lumis) with 1000 events. Results here: https://tinyurl.com/qre37mb
The baseline took almost twice as long as the job with this PR in, but this might be due to load on the shared machine.

Observed changes are:
- `AlCaBeamMonitor`: numerical.
- `CSC/Summary/All_DDUs_L1A_Increment`: significant changes.
- `*/EventInfo/processedEvents`: seems to show only a single stream? 
- `EcalPreshower/ESOccupancyTask` significantly higher stats with `edm::stream`?
- `JetMET/PFCandidates/particleFlow`: multiplicity plots show much (~16x) lower means (but same number of entries) in `edm::stream` mode. In the baseline, most entries are out of binning range.
- `Muons`: looks numerical.
- `Physics/Top/*/*/EventLogger`: significant differences. What is this even supposed to show?
- `SiStrip/MechanicalView`: minor changes in `TkHMap` histograms. Looks numerical.
- `SiStrip/ControlView`: minor changes, looks numerical.
- `Tracking/PackedCandidate/diffCovPhiDxy`: numerical.

This looks much better than I feared. We'll probably explicitly `edm::one` the modules that are causing trouble here and we should be good to go.

**Comment by schneiml** [comment]
please test

No changes expected. I am currently running a single-threaded vs. multi-threaded comparison as well.

**Comment by Dr15Jones** [comment]
> */EventInfo/processedEvents: seems to show only a single stream?

A quick look shows that processedEvents are all `bookInt` so maybe the DQMStore is not properly merging the ints across the streams?

**Comment by schneiml** [comment]
@Dr15Jones no, it counts in a local variable, then writes to the ME in the end, the basic problem of local state.

Would be easy to fix, but i see not too much problem in having it `edm::one` either (it does ~nothing).

**Comment by Dr15Jones** [comment]
> Would be easy to fix, but i see not too much problem in having it edm::one either (it does ~nothing).

That isn't completely accurate. The framework will do its best to schedule around a one but that isn't always possible (especially if the one is on a Path or EndPath).

**Comment by schneiml** [comment]
> (especially if the one is on a Path or EndPath).

Wait -- slightly off-topic question here: All of the DQM modules (except legacy) are now `EDProducer`s. That means they should typically be Tasks, and the Path vs. EndPath vs. whatever story does not really apply any more?

And yes, I assume these one-modules will put a bit of load on the scheduling, but the total CPU time for all the `EventInfo`s should be marginal and as usual, I don't want to pollute these PRs doing rather intricate framework changes with unrelated module-level refactoring.

I am much more worried about `CSCMonitorModule` and `ESOccupancyTask`, these produce a majority of CSC and ECAL Preshower DQM. But then, running some of DQM on `one` modules is sure better than running _all_ of it `one` modules...

**Comment by schneiml** [comment]
New private comparision for this PR here: https://tinyurl.com/tlawl2r
This time baseline and test are using the same code (this PR) but I changed between 1 and 16 threads. 

I see the following non-trivial changes:
- `JetMET / PFCandidates / particleFlow`: different data in some bins, ±20%. Need to check this one in the baseline, I don't think it is related to this PR.
-  `Physics / Top / TopDiElectronDQM / step* / DiElecLogger`: might need to convert another module here.

The other changes look numerical or technical.

**Comment by schneiml** [comment]
I ran another comparison, this time only 100 events and 4 threads vs. 16 threads because I didn't want to wait forever: https://tinyurl.com/qmvrrtc

- There is a significant difference in `CSC/Summary/All_DDUs_L1A_Increment`.
- There are significant changes in `JetMET / PFCandidates / particleFlow`.

Now running a comparison between more/less threads on the baseline IB to see if these changes are unrelated.

**Comment by schneiml** [comment]
Comparison of 2 vs. 10 threads/streams on the baseline IB: https://tinyurl.com/t78r8q5

The remaining CSC and JetMET differences also appear there, so they are unrelated to this PR.

**Comment by Dr15Jones** [comment]
@schneiml is your conclusion then that underlying data products for CSC and JetMET are not reproducible when using threads or do you think there is a long standing problem with how the DQM for those areas is being done? When doing your test, have you tried writing all the data products out and then running DQM only on the data in a file?

**Comment by schneiml** [comment]
@Dr15Jones 
>  is your conclusion then that underlying data products for CSC and JetMET are not reproducible when using threads or do you think there is a long standing problem with how the DQM for those areas is being done?

Not sure what to say here, apart from, I am not too surprised given that some DQM output tended to be hard to reproduce in the past. I have no idea why exactly that happens; the DQM code now is a one module, so it might indeed be in the products, or it might be a matter of event order (I assume EDM never guaranteed that events are processed in a fixed order, right?)

As far as I know, we very rarely do comparisons with varying number of threads, and don't really keep an eye on such problems.

> When doing your test, have you tried writing all the data products out and then running DQM only on the data in a file?

No, and I'd consider that out of scope for this PR, but it might be interesting. I have no idea how to do it, though.

**Comment by Dr15Jones** [comment]
@slava77 @perrotta FYI the inconsistencies in results seen when running multiple threads may be something the reconstruction group may want to follow up on.

**Comment by schneiml** [comment]
+1

Seems to work as expected, though more extensive validation to make sure all subsystem code works correctly will be required. This will be performed by a special set of RelVals.

**Comment by silviodonato** [comment]
Kind reminder to 
alca:  @franzoni @pohsun @tlampen @tocheng @christopheralanwest
fastsim:  @civanch @lveldere @mdhildreth @sbein @ssekmen
l1:  @benkrikler @rekovic

**Comment by silviodonato** [comment]
@schneiml just to summarize and for the benefit of the reviewers. With the current configuration, we get significant differences between multi-threading and single-threding only in CSC and JetMET. However, these differences are visible also in CMSSW_11_1_X_2020-03-02-1100 and then they are not related to this PR. 
There were also other differences between multi/single threaded DQM, but they have been "fixed" by using DQMOneEDAnalyzer instead of DQMEDAnalyzer (ie. the version based on edm::one::EDProducer instead of edm::stream::EDProducer ).
The plan is to merge this PR as soon as possible in order to have it in CMSSW_11_0_pre4 and eventually compare the RelVal DQM plots produced by using single and multi -threading.

**Comment by christopheralanwest** [comment]
+1

**Comment by silviodonato** [comment]
> DQMHistoTests: Total failures: 44

This is related to the issue #29076

**Comment by silviodonato** [comment]
merge

fastsim: @civanch @lveldere @mdhildreth @sbein @ssekmen
l1: @benkrikler @rekovic
please have a look and let me know if you have comments

**Pull request merged**
