### PR TITLE
[81X] Add payloads for several new Hcal records in all Global Tags and update Hcal 2017dev tags

### PR DESCRIPTION
**Pull request by mmusich**
# Summary of changes in Global Tags
## RunI simulation
- **RunI Ideal scenario** : [81X_mcRun1_design_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun1_design_v3) as [81X_mcRun1_design_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun1_design_v2) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_mcRun1_design_v3/81X_mcRun1_design_v2): 
  - added payload for `HcalSiPMsCharacteristics` 
  - added payload for `HcalSiPMParameters`
  - added payload for `HcalTPChannelParameters`
  - added payload for `HcalTPParameters` 
- **RunI Heavy Ions scenario** : [81X_mcRun1_HeavyIon_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun1_HeavyIon_v3) as [81X_mcRun1_HeavyIon_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun1_HeavyIon_v2) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_mcRun1_HeavyIon_v3/81X_mcRun1_HeavyIon_v2): 
  - added payload for `HcalSiPMsCharacteristics` 
  - added payload for `HcalSiPMParameters`
  - added payload for `HcalTPChannelParameters`
  - added payload for `HcalTPParameters` 
- **RunI Realistic scenario** : [81X_mcRun1_realistic_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun1_realistic_v3) as [81X_mcRun1_realistic_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun1_realistic_v2) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_mcRun1_realistic_v3/81X_mcRun1_realistic_v2): 
  - added payload for `HcalSiPMsCharacteristics` 
  - added payload for `HcalSiPMParameters`
  - added payload for `HcalTPChannelParameters`
  - added payload for `HcalTPParameters` 
- **RunI Proton-Lead scenario** : [81X_mcRun1_pA_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun1_pA_v3) as [81X_mcRun1_pA_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun1_pA_v2) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_mcRun1_pA_v3/81X_mcRun1_pA_v2): 
  - added payload for `HcalSiPMsCharacteristics` 
  - added payload for `HcalSiPMParameters`
  - added payload for `HcalTPChannelParameters`
  - added payload for `HcalTPParameters` 
## RunII simulation
- **RunII Ideal scenario** : [81X_mcRun2_design_v8](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun2_design_v8) as [81X_mcRun2_design_v7](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun2_design_v7) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_mcRun2_design_v8/81X_mcRun2_design_v7): 
  - added payload for `HcalSiPMsCharacteristics` 
  - added payload for `HcalSiPMParameters`
  - added payload for `HcalTPChannelParameters`
  - added payload for `HcalTPParameters` 
  - added payload for `HFPhase1PMTParams`
- **RunII Asymptotic scenario** : [81X_mcRun2_asymptotic_v9](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun2_asymptotic_v9) as [81X_mcRun2_asymptotic_v8](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun2_asymptotic_v8) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_mcRun2_asymptotic_v9/81X_mcRun2_asymptotic_v8): 
  - added payload for `HcalSiPMsCharacteristics` 
  - added payload for `HcalSiPMParameters`
  - added payload for `HcalTPChannelParameters`
  - added payload for `HcalTPParameters` 
  - added payload for `HFPhase1PMTParams`
- **RunII Startup scenario** : [81X_mcRun2_startup_v10](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun2_startup_v10) as [81X_mcRun2_startup_v9](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun2_startup_v9) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_mcRun2_startup_v10/81X_mcRun2_startup_v9): 
  - added payload for `HcalSiPMsCharacteristics` 
  - added payload for `HcalSiPMParameters`
  - added payload for `HcalTPChannelParameters`
  - added payload for `HcalTPParameters` 
  - added payload for `HFPhase1PMTParams`
- **RunII Proton-Lead scenario** : [81X_mcRun2_pA_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun2_pA_v3) as [81X_mcRun2_pA_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun2_pA_v2) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_mcRun2_pA_v3/81X_mcRun2_pA_v2): 
  - added payload for `HcalSiPMsCharacteristics` 
  - added payload for `HcalSiPMParameters`
  - added payload for `HcalTPChannelParameters`
  - added payload for `HcalTPParameters` 
  - added payload for `HFPhase1PMTParams`
- **RunII CRAFT scenario** : [81X_mcRun2cosmics_startup_peak_v8](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun2cosmics_startup_peak_v8) as [81X_mcRun2cosmics_startup_peak_v7](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun2cosmics_startup_peak_v7) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_mcRun2cosmics_startup_peak_v8/81X_mcRun2cosmics_startup_peak_v7): 
  - added payload for `HcalSiPMsCharacteristics` 
  - added payload for `HcalSiPMParameters`
  - added payload for `HcalTPChannelParameters`
  - added payload for `HcalTPParameters` 
  - added payload for `HFPhase1PMTParams`
- **RunII Heavy Ions scenario** : [81X_mcRun2_HeavyIon_v9](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun2_HeavyIon_v9) as [81X_mcRun2_HeavyIon_v8](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_mcRun2_HeavyIon_v8) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_mcRun2_HeavyIon_v9/81X_mcRun2_HeavyIon_v8): 
  - added payload for `HcalSiPMsCharacteristics` 
  - added payload for `HcalSiPMParameters`
  - added payload for `HcalTPChannelParameters`
  - added payload for `HcalTPParameters` 
  - added payload for `HFPhase1PMTParams`
## RunII data
- **RunII Offline processing** : [81X_dataRun2_v8](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_dataRun2_v8) as [81X_dataRun2_v7](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_dataRun2_v7) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_dataRun2_v8/81X_dataRun2_v7): 
  - added payload for `HcalSiPMsCharacteristics` 
  - added payload for `HcalSiPMParameters`
  - added payload for `HcalTPChannelParameters`
  - added payload for `HcalTPParameters` 
  - added payload for `HFPhase1PMTParams`
- **RunII HLTHI processing** : [81X_dataRun2_HLTHI_frozen_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_dataRun2_HLTHI_frozen_v2) as [81X_dataRun2_HLTHI_frozen_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_dataRun2_HLTHI_frozen_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_dataRun2_HLTHI_frozen_v2/81X_dataRun2_HLTHI_frozen_v1): 
  - added payload for `HcalSiPMsCharacteristics` 
  - added payload for `HcalSiPMParameters`
  - added payload for `HcalTPChannelParameters`
  - added payload for `HcalTPParameters` 
  - added payload for `HFPhase1PMTParams`
- **RunII HLT relval processing** : [81X_dataRun2_HLT_relval_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_dataRun2_HLT_relval_v4) as [81X_dataRun2_HLT_relval_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_dataRun2_HLT_relval_v3) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_dataRun2_HLT_relval_v4/81X_dataRun2_HLT_relval_v3): 
  - added payload for `HcalSiPMsCharacteristics` 
  - added payload for `HcalSiPMParameters`
  - added payload for `HcalTPChannelParameters`
  - added payload for `HcalTPParameters` 
  - added payload for `HFPhase1PMTParams`
- **RunII HLT processing** : [81X_dataRun2_HLT_frozen_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_dataRun2_HLT_frozen_v2) as [81X_dataRun2_HLT_frozen_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_dataRun2_HLT_frozen_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_dataRun2_HLT_frozen_v2/81X_dataRun2_HLT_frozen_v1): 
  - added payload for `HcalSiPMsCharacteristics` 
  - added payload for `HcalSiPMParameters`
  - added payload for `HcalTPChannelParameters`
  - added payload for `HcalTPParameters` 
  - added payload for `HFPhase1PMTParams`
- **RunII Offline relval processing** : [81X_dataRun2_relval_v10](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_dataRun2_relval_v10) as [81X_dataRun2_relval_v9](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_dataRun2_relval_v9) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_dataRun2_relval_v10/81X_dataRun2_relval_v9): 
  - added payload for `HcalSiPMsCharacteristics` 
  - added payload for `HcalSiPMParameters`
  - added payload for `HcalTPChannelParameters`
  - added payload for `HcalTPParameters` 
  - added payload for `HFPhase1PMTParams`
## Upgrade
- **PhaseI realistic scenario** : [81X_upgrade2017_realistic_v14](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_upgrade2017_realistic_v14) as [81X_upgrade2017_realistic_v13](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_upgrade2017_realistic_v13) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_upgrade2017_realistic_v14/81X_upgrade2017_realistic_v13): 
  - added payload for `HcalSiPMsCharacteristics` 
  - added payload for `HcalSiPMParameters`
  - added payload for `HcalTPChannelParameters`
  - added payload for `HcalTPParameters` 
  - added payload for `HFPhase1PMTParams`
- **PhaseI design scenario** : [81X_upgrade2017_design_v12](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_upgrade2017_design_v12) as [81X_upgrade2017_design_v11](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_upgrade2017_design_v11) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_upgrade2017_design_v12/81X_upgrade2017_design_v11): 
  - added payload for `HcalSiPMsCharacteristics` 
  - added payload for `HcalSiPMParameters`
  - added payload for `HcalTPChannelParameters`
  - added payload for `HcalTPParameters` 
  - added payload for `HFPhase1PMTParams`
- **PhaseI Hcal development scenario** : [81X_upgrade2017_HCALdev_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_upgrade2017_HCALdev_v3) as [81X_upgrade2017_HCALdev_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_upgrade2017_HCALdev_v2) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_upgrade2017_HCALdev_v3/81X_upgrade2017_HCALdev_v2): 
  - updated version of `HcalLutMetadata`
  - updated version of `HcalSiPMCharacteristics`
  - updated version of `HcalSiPMParameters`

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
@abdoulline @walterjr @kpedro88 @igv4321 @bsunanda, you might want to follow this PR.

**Comment by abdoulline** [comment]
Great, thanks a lot!

**Comment by mmusich** [comment]
+1

**Comment by kpedro88** [comment]
@davidlange6 please merge ASAP so HCAL can continue Phase1 development

**Comment by davidlange6** [comment]
i'm I correct to expect physics changed in this PR? @mmusich @kpedro88

**Comment by mmusich** [comment]
@davidlange6 naively I would say no (the new records are not yet consumed), excepted in wf 10624 (judging from https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2648.html)

**Comment by davidlange6** [comment]
Interesting i asked as I saw some..

https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_8_1_X_2016-09-29-2300+16048/16136/10624.0_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2017HCALdev_GenSimFull+DigiFull_2017HCALdev+RecoFull_2017HCALdev+HARVESTFull_2017HCALdev/

**Comment by kpedro88** [comment]
Physics changes should only be observed in HCALdev 2017 workflows (10624, 10824) due to the update to HcalLutMetadata. The SiPM and TP objects are not used anywhere currently, because they can't be activated until this PR is merged. @abdoulline and @matz-e can confirm the LUT changes are expected/desired.

**Comment by mmusich** [comment]
@davidlange6 and indeed it's wf 10624 where we expect them. Am I missing something?

**Comment by abdoulline** [comment]
I was about to type my comments very much the same as 
Kevin did. Matthias @matz-e did change 2017dev HcalLutMetadata on purpose.

**Comment by davidlange6** [comment]
+1
right thanks

**Pull request merged**
