### PR TITLE
PPS direct simulation: optional efficiency effects

### PR DESCRIPTION
**Pull request by jan-kaspar**
#### PR description:

This PR extends the PPS direct simulation with an optional feature to simulate efficiency effects. Either per RP (~ local-track level) or per sensor plane (~ rec hit level). These features aim at facilitating various POG and DPG oriented studies, respectively. The efficiencies are applied to tracking and timing RPs in an uniform manner.

#### PR validation:

Technical validation - comparisons before-after this PR:
  * [reco_cmp.pdf](https://github.com/cms-sw/cmssw/files/5909831/reco_cmp.pdf): Run2 data reco workflows - no difference, as expected
  * [dirsim_cmp.pdf](https://github.com/cms-sw/cmssw/files/5909830/dirsim_cmp.pdf): direct simulation workflows - no difference, as expected - the new features are not enabled by default.

Functional validation kindly done by @AndreaBellora . The direct simulation is run with the following efficiency map (artificial):
input
The efficiency extracted from the simulation output:
output
is well compatible with the input.

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by yuanchao** [comment]
+1
* all wf tests and unit tests passed
* though some build warnings about the use of deprecated esRecord<> get(). They are not part of the PR.

**Comment by qliphy** [comment]
+1

**Pull request merged**
