### PR TITLE
SiStrip Paylod Inspector: add `SiStripFedCablingComparisonTrackerMapBase` template and concrete implementations

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

Title says it all, allows to compare different SiStrip FED cabling payloads by computing the difference in the number of connected APVs in each module.

#### PR validation:

Run
```bash
getPayloadData.py \
    --plugin pluginSiStripFedCabling_PayloadInspector \
    --plot plot_SiStripFedCablingComparisonTrackerMapSingleTag \
    --tag SiStripFedCabling_GR10_v1_hlt \
    --time_type Run \
    --iovs '{"start_iov": "1", "end_iov": "400000"}' \
    --db Prod \
    --test ;
```

and obtained the following plot

image

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

N/A

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by perrotta** [comment]
+1
- Unit tests pass

**Comment by rappoccio** [comment]
+1

**Pull request merged**
