### PR TITLE
HcalDQM: Enabling hcalcalib to work under #31206

### PR DESCRIPTION
**Pull request by lwang046**
Putting hcalcalib client into the list of modified clients in #31206 in preparation for the MWGR

#### PR validation:
local test shows hcalcalib client correctly saves the output DQM root using run338628.

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by qliphy** [comment]
+1

**Comment by jfernan2** [comment]
@lwang046  since for next MWGR in February 2021 we will be using CMSSW_11_2_X, could you please forward port this PR to that branch so that changes tested over last MWGR do not get lost on the way?
Thank you very much

**Pull request merged**
