### PR TITLE
Change RPCDigisValidation default input collection

### PR DESCRIPTION
**Pull request by jhgoh**
This PR is to change default input collection to the RPCDigis validaiton.
RPC validation team have been running validation module privately with this change to do the premixing vs classic mixing validation.

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1

**Comment by jhgoh** [comment]
Updated to run both on with and without PU configuration, the validation module first tries with hltMuonRPCDigis and fall back to simMuonRPCDigis in case of failure.

**Comment by jhgoh** [comment]
@deguio could you retrigger the test?

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
I am cleaning up the 76x queue aside from things for analysis workflows. I'm closing this pull request, please make sure the PR is in 80x. Thanks!

**Pull request closed without merging**
