### PR TITLE
L1t updates 74x

### PR DESCRIPTION
**Pull request by mulhearn**
This is the main updates for L1T software aimed at release 74X.  In includes updates to algorithms, unpackers, and parameters.

### CODE REVIEW

**Comment by mulhearn** [comment]
I'll remove the data files in an update, but wanted to get this on the books...

**Comment by mulhearn** [comment]
I'm aware this is late.  Last week I had to devote most free time to O2O transition for the midweek global run, and could only turn to this over the weekend...

**Comment by mulhearn** [comment]
The L1Trigger/L1TCalorimeter/data PR was sent.  Checking if other data files are needed in release.

**Comment by mulhearn** [comment]
It seems the files in EventFilter/L1TRawToDigi/data are still needed.  I believe I need someone else to prepare the repo, since it hasn't been used before...

**Comment by davidlange6** [comment]
@ktf, @nclopezo @degano - could you take care of putting the three large data files in L1Trigger/L1TCalorimeter into the data externals. Mike will remove them from the pr after that.
Thx!

**Comment by mulhearn** [comment]
There's already a PR for those file in cms-data for L1Trigger-L1TCalorimeter.  The other data files are reportedly not needed in the release:  I can just delete them and retest...

**Comment by nclopezo** [comment]
Hi @davidlange6 and @mulhearn, 
I merged the PR for L1Trigger-L1TCalorimeter (https://github.com/cms-data/L1Trigger-L1TCalorimeter/pull/1 )  And updated the version in the spec file (https://github.com/cms-sw/cmsdist/pull/1350). Do you want me to trigger a new IB Before 2015-02-04-1400 starts?

**Comment by davidlange6** [comment]
Hi David
no need to trigger a IB before 1400 - in any case, we also have 

https://github.com/cms-data/RecoHI-HiJetAlgos/pull/1

to update

**Comment by nclopezo** [comment]
Ok, I see that Alessandro updated it here: https://github.com/cms-sw/cmsdist/pull/1353

**Comment by diguida** [comment]
+1
In `CondFormats/L1TObjects/interface/CaloParams.h` new getter and setter methods have been added to the `CaloParams` class:
````
l1t::LUT* jetCalibrationLUT()
void setJetCalibrationLUT(const l1t::LUT & lut)
````

**Comment by mulhearn** [comment]
@cmsbuild please retest

**Comment by mulhearn** [comment]
PR updated to remove all data files (some unneeded, some have been moved to cms-data).

**Comment by mulhearn** [comment]
+1

**Comment by diguida** [comment]
+1
In `CondFormats/L1TObjects/interface/CaloParams.h` new getter and setter methods have been added to the `CaloParams` class:
````
l1t::LUT* jetCalibrationLUT()
void setJetCalibrationLUT(const l1t::LUT & lut)
````

**Comment by davidlange6** [comment]
@mulhearn - just to confirm - the packer/unpacker changes are compatible with the run 1 system?

**Comment by mulhearn** [comment]
@davidlange6   Yes, they are still only turned on by the --postLS1 customization switch.  This just mainly moves them to the correct FED ID number and I believe some other minor tweaks to make it more in agreement with the (developing) firmware.

**Comment by davidlange6** [comment]
@mulhearn - seems you need to rebase this PR. Please have a look.

**Comment by mulhearn** [comment]
This is now superceded by #7644 which fixes the conflict.

**Pull request closed without merging**
