### PR TITLE
HLT release validation for new EXO-LLP Run 3 paths

### PR DESCRIPTION
**Pull request by jalimena**
#### PR description:

This PR updates the exotica HLT release validation (in HLTriggerOffline/Exotica) to include the validation of the new long-lived particle (LLP) paths that went into v1 of the Run 3 HLT menu [1]. Complying with the request from STEAM to limit the number of histograms produced, the general philosophy going into these changes was to monitor only the signal paths, and not the backup or control paths. So, these paths have been added to the monitoring:

```
HLT_HT430_DelayedJet40_SingleDelay1nsTrackless_v
HLT_HT430_DelayedJet40_SingleDelay2nsInclusive_v
HLT_DoubleL2Mu23NoVtx_2Cha_CosmicSeed_v
HLT_DoubleL2Mu23NoVtx_2Cha_v
HLT_DoubleL2Mu10NoVtx_2Cha_PromptL3Mu0Veto_v
HLT_DoubleL3Mu10NoVtx_Displaced_v
HLT_HT430_DisplacedDijet30_Inclusive1PtrkShortSig5_v
HLT_Mu6HT240_DisplacedDijet30_Inclusive1PtrkShortSig5_DisplacedLoose_v
HLT_Mu20NoFiltersNoVtxDisplaced_Photon20_CaloCustomId_v
HLT_PFMET105_IsoTrk50_v
HLT_PFMET110_PFJet100_v
HLT_L1MET_DTClusterNoMB1S50_v
```

And these have been removed:
```
HLT_DoubleMu33NoFiltersNoVtxDisplaced_v
HLT_DoubleMu48NoFiltersNoVtx_v
HLT_Mu48NoFiltersNoVtx_Photon48_CaloIdL_v
HLT_Mu43NoFiltersNoVtxDisplaced_Photon43_CaloIdL_v
HLT_UncorrectedJetE30_NoBPTX_v
HLT_UncorrectedJetE30_NoBPTX3BX_v
HLT_UncorrectedJetE70_NoBPTX3BX_v
HLT_L2Mu10_NoVertex_NoBPTX_v
HLT_L2Mu10_NoVertex_NoBPTX3BX_v
HLT_L2Mu45_NoVertex_3Sta_NoBPTX3BX_v
HLT_HT400_DisplacedDijet40_DisplacedTrack_v
HLT_HT430_DisplacedDijet60_DisplacedTrack_v
HLT_HT550_DisplacedDijet60_Inclusive_v
```

#### PR validation:

Using a TTbar relval [2], I have checked that the correct histograms are produced when running
```
cmsRun HLTriggerOffline/Exotica/test/hltExoticaValidator_cfg.py
cmsRun HLTriggerOffline/Exotica/test/hltExoticaPostProcessor_cfg.py
```

I have also successfully tested this PR with 
```
runTheMatrix.py -l limited -i all --ibeos
```

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Not a backport

[1] https://its.cern.ch/jira/browse/CMSHLT-2211
[2] /RelValTTbar_14TeV/CMSSW_12_3_0_pre6-123X_mcRun4_realistic_v8_2026D88noPU-v1/GEN-SIM-RECO

### CODE REVIEW

**Comment by jalimena** [comment]
hi, can we please run the tests, at least? thanks!

**Comment by perrotta** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by jfernan2** [comment]
@jalimena I wonder if there is some duplication in the monitoring implemented in this PR w.r.t. the one in https://github.com/cms-sw/cmssw/pull/37298
Could you please clarify?
Thanks

**Comment by jalimena** [comment]
Hi @jfernan2 . This PR is https://github.com/cms-sw/cmssw/pull/37298, the other one is https://github.com/cms-sw/cmssw/pull/37342 . I kept them separate on purpose, in case there were any issues. There should be no duplication.
This PR handles the release validation, and all files I touched are in HLTriggerOffline/Exotica. The other PR handles the offline DQM, and all files that I touched in that PR are in DQMOffline/Trigger.

**Comment by jfernan2** [comment]
Yes @jalimena I understand that, I mistyped the other PR, sorry. My question is if there is duplication in the monitoring, since those paths are being monitoried in both DQM and Validation, which are usually run simultaneously
Thanks

**Comment by jalimena** [comment]
Hi @jfernan2  ah ok now I get it. No, the plots produced in the two packages are different.

**Comment by jfernan2** [comment]
I see, thank you very much

**Comment by perrotta** [comment]
+1

**Pull request merged**
