### PR TITLE
Faster CSCALCTDigi::clear()

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

All the digis now share an immutable empty hits container until the individual digis have their hits set.

This was a stand out timing for the IB RelVal's igprof report for workflow 136.731 for step2.

#### PR validation:

Code compiles.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
From the report
```


 Rank | % total | Counts | Paths | Symbol name

      | 0.23 | 0.10 | 0.12 | 1 | 1 | CSCAnodeLCTProcessor::clear()
      | 0.34 | 0.15 | 0.18 | 3 | 3 | CSCALCTDigi::CSCALCTDigi()
      | 1.35 | 0.61 | 0.79 | 2 | 2 | CSCCorrelatedLCTDigi::clear()
[288] | 1.92 | 0.72 | 0.15 | 6 | 6 | CSCALCTDigi::clear()
      | 0.21 | 0.10 | 0.10 | 3 | 5 | std::vector<unsigned short, std::allocator<unsigned short> >::_M_default_append(unsigned long)
      | 0.12 | 0.06 | 0.12 | 2 | 4 | std::vector<std::vector<unsigned short, std::allocator<unsigned short> >, std::allocator<std::vector<unsigned short, std::allocator<unsigned short> > > >::_M_default_append(unsigned long)

```

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
