### PR TITLE
Phase2-hgx294X Update the scripts to validate HGCal geometry

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Update the scripts to validate HGCal geometry

#### PR validation:

Use the modified scripts to examine HGCal geometry versions V15 and V16

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by srimanob** [comment]
+Upgrade

This PR is to update scripts for HGCAL geometry test with no change in physics.

**Comment by cvuosalo** [comment]
+1

**Comment by emanueleusai** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
