### PR TITLE
Fixed path names. Removed pt2 and pt3 in unnecessary cases. Added debug print (dump # of HLT passed events). Replace "cout" to DebugLog. Updated paths (PhotonMET, PureMET, DiPhoton, HighPtPhoton).)

### PR DESCRIPTION
**Pull request by ryonamin**
Backport from 76X (#10907,#10974,#11046) for 75X.

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1
provided it passes the tests

**Comment by davidlange6** [comment]
@ryonamin - could you update the title of this PR to describe its changes for the release notes. Also it no longer merges, so will need to be rebased.

**Comment by deguio** [comment]
-1

**Pull request closed without merging**
