### PR TITLE
[L1T] fix asan runtime errors in DTTrigger Phase-2

### PR DESCRIPTION
**Pull request by cecilecaillol**
#### PR description:

Addressing issue https://github.com/cms-sw/cmssw/issues/39246 (ASAN runtime errors in DTTriggerPhase2)

### CODE REVIEW

**Comment by cecilecaillol** [comment]
please test

**Comment by missirol** [comment]
Shouldn't this be tested with an ASAN build? e.g.

"please test for CMSSW_12_6_ASAN_X"

**Comment by smuzaffar** [comment]
please test workflow 23234.0,37434.0 for CMSSW_12_6_ASAN_X

lets run the tests for couple of failing workflows in ASAN build too

**Comment by perrotta** [comment]
type bugfix

**Comment by perrotta** [comment]
please test
(The previously failing workflows complete without errors now in ASN. Try to refresh tjhe "normal" tests, to recover from the pending tests staus in bot.)

**Comment by cecilecaillol** [comment]
+l1

**Comment by perrotta** [comment]
@cms-sw/upgrade-l2 we are trying to fix as many errors as possible in the IBs
This fix looks quite logic, and simple enough to be evaluated quickly: do you have anything to comment, or can we merge it (after your "+1")?

**Comment by srimanob** [comment]
+Upgrade

**Comment by perrotta** [comment]
+1

**Comment by perrotta** [comment]
> Hi @perrotta Is the error on` cms/39263/ASAN/el8_amd64_gcc10/unittest` expected? I assume not related to this PR.

Hi @srimanob 
ASAN builds normally signal quite several errors. The ones that were supposed to be fixed by this PR are not there any more. And the "regular" build shows no errors, not even in the unit tests. This PR looks like having fixed https://github.com/cms-sw/cmssw/issues/39246

**Comment by smuzaffar** [comment]
> Hi @perrotta Is the error on` cms/39263/ASAN/el8_amd64_gcc10/unittest` expected? I assume not related to this PR.

yes unit tests here is not related to this change. unit tests fails in ASAN IBs too. basically system "cp" command fails when run under ` LD_PRELOAD=/cvmfs/cms-ib.cern.ch/nweek-02748/el8_amd64_gcc10/external/gcc/10.3.0-84898dea653199466402e67d73657f10/lib64/libasan.so` . I guess we can disable this test for ASAN IBs

**Pull request merged**
