### PR TITLE
small update of specifying event contents modules 81X

### PR DESCRIPTION
**Pull request by jeongeun**
Fix PR#13612
Event Content Module Cleanup from unneeded wildcards

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by slava77** [comment]
@cmsbuild please test
maybe no DAS errors this time

**Comment by mmusich** [comment]
+1

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/13948	852ef2e
- replacement of module instance wildcards with actually running module names looks correct
- jenkins tests pass and comparisons with baseline show no difference
    - event product comparison of jenkins outputs in HI and pp workflows with RECO shows the same content

**Comment by davidlange6** [comment]
+1

**Pull request merged**
