### PR TITLE
Fixes for online beamspot, heavy-ion run in 2018

### PR DESCRIPTION
**Pull request by sikler**
The HI reconstruction now uses the same labels as pp, changes are inherited via eras.
The code for the legacy client (beam_*) was cleaned and straigthened out, better readability and similar or same cuts for pp and HI running
The code for HLT-based client (beamhlt_*) still needs a proper track and vertex collection for the HI run.
Documentation and background is at
https://twiki.cern.ch/twiki/bin/viewauth/CMS/OnlineBeamSpot#Sep_2018_legacy_and_or_HLT_based

### CODE REVIEW

**Comment by andrius-k** [comment]
please test

**Comment by sikler** [comment]
Hi @andrius-k: title changed, and have asked Tomas to edit the contact list.

**Comment by sikler** [comment]
Updating labels and collection names for the heavy-ion HLT-based (beamhlt) with fresh heavy-ion related infos, as
process.source.streamLabel = cms.untracked.string('streamHIDQMOnlineBeamspot')
...
process.dqmBeamMonitor.BeamFitter.TrackCollection = 'hltPFMuonMergingPPOnAA'
process.dqmBeamMonitor.primaryVertex = 'hltVerticesPFFilterPPOnAA'
process.dqmBeamMonitor.PVFitter.VertexCollection = 'hltVerticesPFFilterPPOnAA'

**Comment by andrius-k** [comment]
please test

**Comment by andrius-k** [comment]
please test

**Comment by andrius-k** [comment]
@fabiocos the back-port of this PR (#24888) keeps staying in awaiting green-light from developer state in playback tests.
@sikler any updates on the playback test status?

**Comment by andrius-k** [comment]
Hi @sikler, this apparently this PR has conflicts. Could you please take a look?

**Comment by sikler** [comment]
Hi @andrius-k, well that's strange since I haven't touched beam_dqm_sourceclient-live_cfg.py recently. Looks like some older piece of code reappeared. Do you have some idea how that could happen?

**Comment by threus** [comment]
@sikler @andrius-k it's probably clashing with #25024 that was merged recently for the HPU fill.

**Comment by andrius-k** [comment]
@sikler yes, it's probably because of my recently merged PR as I modified `beam_dqm_sourceclient-live_cfg.py`.

**Comment by fabiocos** [comment]
@sikler if this is needed for operations please rebase it asap

**Comment by sikler** [comment]
@fabiocos @andrius-k Hi, is there an easy (one-click) solution to resolve the conflict in favor or the original commit? I mean without editing/merging? Sorry, I am not expert in github.

**Comment by andrius-k** [comment]
Hi @sikler, I will do the rebase and create a new PR for you. @threus what is the situation with the back-port (#24888)? I see that it was recently updated. Is the playback running the most recent version?

**Comment by threus** [comment]
@andrius-k yes, the playback is running the most recent commit of #24888 and looks fine, but there are of course limitations when testing beamspot client on HI dry runs without real events.

**Comment by andrius-k** [comment]
@sikler, I rebased this PR: #25073. This one could be closed now.
@threus cool! As soon as tests will finish I will approve both PRs.

**Comment by boudoul** [comment]
Hi @andrius-k , you may want to  tell @sikler how you  did rebase, so that the knowledge is spread- Rebasing a PR  is a routine operation - It's important that developers know about it .

**Comment by andrius-k** [comment]
@boudoul @sikler the instructions on how to do a rebase are available here: http://cms-sw.github.io/tutorial-resolve-conflicts.html
I did a manual rebase but following these instructions should be a bit easier.

**Comment by fabiocos** [comment]
@sikler @andrius-k after the integration of #25073 this PR can be closed I would say

**Comment by andrius-k** [comment]
@sikler @fabiocos yes indeed, this PR should be closed as my rebased version #25073 is merged.

**Pull request closed without merging**
