### PR TITLE
DQM/Validation: Remove remaining usages of Comp2Ref

### PR DESCRIPTION
**Pull request by schneiml**
#### PR description:

These were forgotten in #28038, since the build system does not know
about the dependences via QTests.

The xml files only use simple comparison-to-reference QTests, so I
removed them, along with the Python configs that use them, since these
seem to target validation of CMSSW_2 series releases and are probably
useless today.

#### PR validation:
None, code should be non-functional and unused anyways.

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by schneiml** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
