### PR TITLE
Backport of #14247: Small improvements in Pixel track reconstruction

### PR DESCRIPTION
**Pull request by makortel**
This PR backports PR #14247 from CMSSW_8_1_X to CMSSW_8_0_X. Original description by @VinInn 

> relevant almost exclusively for HLT.
> No regression expected 
> (in reco notably as little of the modified code run offline)

The first commit (7cf0c3b) is actually from #13831, but is needed here because of dependence. The commit is already included in #15240.

Tested in 8_0_14 (rebased on top of 8_0_16), no changes observed in RECO quantities. Tiny changes (level of 1e-14) are observed in HLT pixel track "point of closest approach wrt. BeamSpot" as shown in https://github.com/cms-sw/cmssw/issues/15151#issuecomment-234061713.

@fwyzard @gennai @slava77 @VinInn

### CODE REVIEW

**Comment by makortel** [comment]
tracked at #15151

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@makortel 
could you please rebase to remove the commit which is already in 80X (DynArray edits in 7cf0c3b40aca06f7148dcc6f7a90004bcece4906)

This PR gives little gain for HLT timing, on the other hand it looks pretty safe, since there are no changes in RECO and only tiny numerical changes in HLT. So, even the ~0.4% gain may be worth the effort.

**Comment by makortel** [comment]
@slava rebased on top of 8_0_16 omitting the DynArray commit.

**Comment by slava77** [comment]
@cmsbuild please test
... despite that I expect jenkins tests to fail in 140.53

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/15288 a9c2ea0
- backport matches changes made in #14247, less the 81X-specific diffs (pixel quadruplets are only in 81X). Detailed validation in 81X showed only tiny changes in HLT {x,y}PointOfClosestApproachVsZ0wrtBS_GenTk and related plots
- jenkins tests passed for 1371e8d and comparisons with baseline show no difference; a9c2ea0 is just a rebase and the jenkins tests passed up to the point of failure due to missing HI workflow files
- local timing tests (using Run276935_LS80-220 /online/collisions/2016/25ns15e33/v3.0/HLT/V3) confirm small, about 3-4% individual improvements in HLT in hltIter\*Pixel and in other \*Pixel\* modules. The net effect from the selected modules is about 0.6 ms out of ~290 ms counting running modules or out of 360 ms including all remaining framework overhead. This is about 0.2%. Event totals show ~0.3% improvement, but this estimate has a much larger uncertainty from job time reproducibility.
```
   -0.058033      -0.02%         0.83 ms/ev ->         0.78 ms/ev hltPixelTracksReg
   -0.044447      -0.01%         0.86 ms/ev ->         0.82 ms/ev hltPixelTracksForNoPU
   -0.043411      -0.01%         0.85 ms/ev ->         0.82 ms/ev hltFastPVPixelTracks
   -0.042202      -0.01%         0.69 ms/ev ->         0.66 ms/ev hltIter2PFlowPixelSeedsForBTag
   -0.041873      -0.06%         4.59 ms/ev ->         4.41 ms/ev hltIter2PFlowPixelSeeds
   -0.034901      -0.14%        12.22 ms/ev ->        11.80 ms/ev hltIter1PFlowPixelSeeds
```

**Pull request merged**
