### PR TITLE
GEM DQM updates - full GE1/1, backport to 11_0_X

### PR DESCRIPTION
**Pull request by quark2**
#### PR description:
This backport PR to 11_0_X (from #28769) updates and extends the part of onlineDQM for GEM. The details are following: 

 - The existing parts are fixed to match the VFAT version which is used in CMSSW currently
 - Summary plot is added
 - Histograms which displays the status of devices (AMCs, GEBs, VFATs) by time are added

Please see [this](https://indico.cern.ch/event/881121/contributions/3712072/attachments/1972921/3282493/20200120_DQM_Online_PR.pdf) to check more details, especially the visualization with [DQM GUI](https://github.com/dmwm/deployment) (there is also an update for GEM part for onlineDQM GUI, which will be PRed soon)

#### PR validation:
Test are done and one can check again by `runTheMatrix` workflows

@jshlee @watson-ij

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by jfernan2** [comment]
hold 
Testing it in Online DQM playback

**Comment by silviodonato** [comment]
@quark2 Could you quote the number of the CMSSW_11_1_X PR in the description?

**Comment by fioriNTU** [comment]
@quark2 @silviodonato this PR has been tested in the playback on top of CMSS_11_0_0_patch1, and it fixes the crash in the gem client. So, I think we can unhold this PR. 

Even if there are no actual data to process, empty GEM plots can be seen in the playback GUI:

https://cmsweb.cern.ch/dqm/online-playback/start?runnr=0;dataset=/Global/Online/ALL;sampletype=live;filter=all;referencepos=overlay;referenceshow=customise;referencenorm=True;referenceobj1=refobj;referenceobj2=none;referenceobj3=none;referenceobj4=none;search=;striptype=object;stripruns=;stripaxis=run;stripomit=none;workspace=GEM;size=M;root=GEM/recHit;focus=;zoom=no;

**Comment by quark2** [comment]
@silviodonato okay, I added

**Comment by silviodonato** [comment]
backport #28769
@quark2 thanks

**Comment by jfernan2** [comment]
unhold
Tested succesfully in DQM Online playback

**Comment by silviodonato** [comment]
+1

**Pull request merged**
