### PR TITLE
Hide framework classes from ROOT in SiStripTools

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

- separate classes that do the calculation from those that hold the results
- Use ROOT dictionaries only for results to avoid causing additional auto parsing.

#### PR validation:

Code compiles.

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by Dr15Jones** [comment]
please test

**Comment by perrotta** [comment]
+1

**Comment by perrotta** [comment]
merge

**Pull request merged**
