### PR TITLE
Minor typos fix on Validation/Geometry files

### PR DESCRIPTION
**Pull request by vargasa**
As the title suggests minor typos have been fixed

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by boudoul** [comment]
Hello @vargasa , thanks . minor comment:  Could you please edit the tiltle to say that the fixes are for the geometry validation files? It's important for the release notes - thank you .

**Comment by civanch** [comment]
+1

**Comment by fabiocos** [comment]
please test

just for technical check of test, the PR in itself look ok to go

**Comment by jfernan2** [comment]
+1
________________________________________

**Comment by fabiocos** [comment]
+1

**Pull request merged**
