### PR TITLE
re-enable HLT DQM, Validation and Harvesting sequences

### PR DESCRIPTION
**Pull request by mtosi**
this PR is needed to have the plots needed for the validation of the HLT menu in phase1 workflows
please, sign it as soon as possible

I tested w/ 10224.0 workflow, the corresponding DQM output is [1]

unfortunately, we realized this fix was not done yet only this afternoon :(
thanks !

[1]
/afs/cern.ch/work/t/tosi/public/STEAM/validation/2017_workflow/CMSSW_8_1_0_pre16/src/10224.0_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2017PU_GenSimFull+DigiFullPU_2017PU+RecoFullPU_2017PU+HARVESTFullPU_2017PU/DQM_V0001_R000000001__Global__CMSSW_X_Y_Z__RECO.root

### CODE REVIEW

**Comment by mtosi** [comment]
@Martin-Grunewald @silviodonato @dmitrijus @vanbesien @fwyzard @gennai @hengne @fabozzi

**Comment by hengne** [comment]
please test

**Comment by makortel** [comment]
Please remove the lines instead of commenting them out.

Also note that there are still additional places where DQM/VALIDATION modules are turned off because HLT not being part of 2017 workflows in the past (all can be found with `git grep phase1Pixel.*FIXME`).

**Comment by hengne** [comment]
@mtosi have you done all the cleanups?

**Comment by hengne** [comment]
please test

**Comment by hengne** [comment]
+1

**Comment by hengne** [comment]
not sure if my signature works here... according to the labels, it is responsible by dqm group

**Comment by hengne** [comment]
otherwise computing/offline can sign it anyway, i guess.

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Comment by mtosi** [comment]
thanks !
  mia

**Pull request merged**
