### PR TITLE
Backport to 9_4_X of DeepFlavour and TF API

### PR DESCRIPTION
**Pull request by pablodecm**
This PR includes all the changes done in https://github.com/cms-sw/cmssw/pull/19893 so they can be used within 9_4_X. This was asked and discussed in the following issue https://github.com/cms-sw/cmssw/issues/21864.

Rebased and locally tested over `CMSSW_9_4_X_2018-01-28-0000`.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cmsbuild please test

to get an updated comparison script for the diffs

**Comment by pablodecm** [comment]
@slava77 what are the next steps regarding the backport, should we do any additional checks/tests?

**Comment by slava77** [comment]
On 2/1/18 6:21 AM, Pablo de Castro wrote:
> @slava77 <https://github.com/slava77> what are the next steps regarding
> the backport, should we do any additional checks/tests?
> 

not yet, there was some undergoing discussion about the
scope/requirements for the "remini v2" cycle.
So I was holding on this PR review until that is clear.

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/22042	0f7f2c8
- Addition of b-tag discriminants based on DeepFlavor. This only adds new entries in pairDiscriVector of the pat::Jets saved in miniAOD.
- backport of #19893 (merged Jan 25) is made correctly: the same changes are proposed in this PR as already merged in the master.
- jenkins tests pass and comparisons with the baseline show differences only in slimmedJets pairDiscriVector as expected (the size of the vector has increased, six new discriminants show up and nothing else is changed).

**Comment by fabiocos** [comment]
integrated in 10_1_0_pre1 already

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Pull request merged**
