### PR TITLE
HI 2023 relval wfs + realistic 2022 vtx smearing

### PR DESCRIPTION
**Pull request by mandrenguyen**
#### PR description:

- Existing 2022 heavy-ion workflows (159.*) are duplicated for 2023 detector conditions (160.*).
- The center-of-mass energy is updated to 5.362 TeV, the energy expected for the 2023 Pb-Pb data.
- The Hydjet generator parameters are slightly modified to correspond to what will be used for 2023 MC production. 
- The vertex smearing for both 2022 and 2023 workflows are updated to realistic beam conditions derived from the 2022 data.
- The autoconditions are updated to global tags containing the corresponding reco BS.  See [here](https://cms-talk.web.cern.ch/t/request-for-new-run3-hi-mc-gt-realistic-bs-for-12-5-x/21522/5)
- The GT change includes the tag `BeamSpotObjects_Realistic2022PbPbCollision_v5_mc` as can be seen in the diffs:
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/131X_mcRun3_2022_realistic_HI_v1/131X_mcRun3_2022_realistic_HI_v2
and
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/131X_mcRun3_2023_realistic_HI_v1/131X_mcRun3_2023_realistic_HI_v2

- Relval wfs (322-324, 161.01) that use an input dataset are also added but commented out until input samples can be produced
- For 2022 workflows, cleaned up outdated nomenclature by fully changing `2021` to `2022`

#### PR validation:

wfs 160.0, 160.02, 160.03, 160.1, 160.2, 160.3 were tested with the option -j0.  The cmsDriver commands run successfully, but the cmsRun commands are left for the jenkins tests.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

No backport will be needed.

### CODE REVIEW

**Comment by mandrenguyen** [comment]
@cmsbuild please test workflow 159, 159.01, 159.02, 159.03, 159.1, 159.2, 159.3, 310, 160, 160.02, 160.03, 160.1, 160.2, 160.3

**Comment by tvami** [comment]
312.0_Pyquen_ZeemumuJets_pt10_2760GeV_2022 is giving this error
```
----- Begin Fatal Exception 18-Mar-2023 11:15:11 CET-----------------------
An exception of category 'NoSecondaryFiles' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing module: class=MixingModule label='mix'
Exception Message:
RootEmbeddedFileSequence no input files specified for secondary input source.
----- End Fatal Exception -------------------------------------------------
```

**Comment by mandrenguyen** [comment]
please test

**Comment by tvami** [comment]
+alca
 * @mandrenguyen please include the following text in the PR desc:
 ```
The GT change includes the tag `BeamSpotObjects_Realistic2022PbPbCollision_v5_mc` as can be seen in the diffs:
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/131X_mcRun3_2022_realistic_HI_v1/131X_mcRun3_2022_realistic_HI_v2
and
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/131X_mcRun3_2023_realistic_HI_v1/131X_mcRun3_2023_realistic_HI_v2
 ```

**Comment by menglu21** [comment]
please test

**Comment by mandrenguyen** [comment]
@menglu21  The tests had just passed, you didn't need to relaunch them

**Comment by menglu21** [comment]
please abort

**Comment by menglu21** [comment]
sorry, seems the status will not go back to "approved", so i need to start the test again, right?

**Comment by mandrenguyen** [comment]
Yes, I think the test has to be restarted for posterity, but you can already inspect the comparisons produced by the previous test.

**Comment by menglu21** [comment]
please test

**Comment by menglu21** [comment]
+1

**Comment by sunilUIET** [comment]
+pdmv

**Comment by perrotta** [comment]
@cms-sw/upgrade-l2 it is not clear to me why your signature is requested here... In any case, I think it could be useful to have these modified HI workflow available for testing in the 13_1_0_pre2 RelVals. Since we plan to cut that pre-release today, we would like to include this PR in it, if you don't have anything against it.

**Comment by srimanob** [comment]
+Upgrade

**Comment by perrotta** [comment]
+1

**Pull request merged**
