### PR TITLE
DD4hep: Process Muon Yoke

### PR DESCRIPTION
**Pull request by ianna**
* Make sure namespace is assigned correctly to children in DD algorithm and PosParts
* Note: PseudoTrap bug is fixed in updated dd4hep external

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by fabiocos** [comment]
@ianna there is quite an overlap between this PR and #25252

**Comment by ianna** [comment]
@fabiocos - yes, it is based on #25252

**Comment by davidlange6** [comment]
Your PR is unmergeable. Please have a look and possibly rebase it.

**Comment by ianna** [comment]
+1

**Pull request merged**
