### PR TITLE
recover particleFlowClusterHF in event content

### PR DESCRIPTION
**Pull request by slava77**
Fix PF event content to keep HF PFClusters and "Cleaned" rechits.
- particleFlowClusterHF previously (before 72X) were split in  HFEM and HFHAD collections. RECO and FEVT was never updated to keep  recoPFClusters_particleFlowClusterHF. 
  - this at some point affected  running recoMET_pfClusterMet_cfg.py in RecoMET/METProducers unit tests which was first mitigated in #10818  in the test itself (instead of adding clusters to RECO). The METProducers kept running thanks to rather inclusive fastsim event content "keep *_particleFlow*_*_*", until the fastsim event content was cleaned up in 80X in #13090 . 
  - A more appropriate fix is to keep HF PFClusters and not attempt to remake them in recoMET_pfClusterMet_cfg.py
- Missing  recoPFClusters_particleFlowClusterHF in RECO was also reported by FSQ.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cmsbuild please test
maybe no DAS error next time

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/13309	6721bd4
- restores particleFlowClusterHF in RECO/FEVT event content
- jenkins tests pass and comparisons with baseline show no differences
- checks in local tests confirm that the RECO output files now have recoPFClusters_particleFlowClusterHF included in the output (about 3%); AOD is unchanged.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
