### PR TITLE
GE21-ME21 segment reconstruction (backport of #39441, 12_5_X) 

### PR DESCRIPTION
**Pull request by slowmoyang**
#### PR description:
Backport of #39441. This PR introduces the GE21-ME21 segment reconstruction.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:
This PR is a backport of #39441. This update is required for the GEM online DQM.

@jshlee @watson-ij

### CODE REVIEW

**Comment by mandrenguyen** [comment]
please test

**Comment by aandvalenzuela** [comment]
please test

- Tests need to be restarted due to an issue when publishing to cvmfs. Sorry for the inconvenience!

**Comment by mandrenguyen** [comment]
@cms-sw/dqm-l2 or @slowmoyang  Do you have an idea why the unit tests are failing here?

**Comment by emanueleusai** [comment]
@mandrenguyen see https://github.com/cms-sw/cmssw/issues/39669

**Comment by mandrenguyen** [comment]
@emanueleusai I believe the conclusion from the ORP was that we should simply ignore the unit tests, right?

**Comment by emanueleusai** [comment]
+1

- test at p5 completed successfully for 12_4 backport

**Comment by mandrenguyen** [comment]
+1

**Comment by srimanob** [comment]
@cmsbuild please test

Retrigger the test after 3 weeks.

**Comment by srimanob** [comment]
+Upgrade

**Comment by perrotta** [comment]
Backport not needed any more (it was merged in the online DQM release, anyhow)

**Pull request closed without merging**
