### PR TITLE
Bug fix in Geant4 stepping and stacking actions

### PR DESCRIPTION
**Pull request by civanch**
#### PR description:
In an attempt to optimize Run-3 simulation and fix minor problem in Geant4 user actions a logical bug was introduced, which affect calorimeter responses. The problem was reported first by @abdoulline . In this PR the logic of filters at each step (SteppingAction) has been fixed. A minor problem is also fixed in StackingAction, which is called for each new secondary particle.

The level of the problem, identified by @abdoulline is 2-3% reduction of energy deposition in calorimeters. With the test-beam 2006 the effect is even more and may illustrated for pi- projectile: 
image

In the proposed fix the situation return back to normal: 
image

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
@bsunanda , FYI

**Comment by abdoulline** [comment]
@civanch  thank you for the fix.
My private 2021 pion gun test confirms your TB 2006 results  (within stat. errors) 
 https://cms-cpt-software.web.cern.ch/cms-cpt-software/General/Validation/SVSuite/HCAL/calo_scan_single_pi/12_X/12_0_0_pre2_run3_PR33923_vs_12_0_0_pre1_run3_SinglePi/SimHitsTask_emean_vs_ieta_EH.gif

**Comment by civanch** [comment]
+1

the problem was that all stopping particles (e+, pi-,.. ) were killed before reaction at rest is happens. The effect is in calorimeters and this confirms, that stopping processes have to be simulated.

**Comment by silviodonato** [comment]
+1

**Pull request merged**
