### PR TITLE
Added DTCalibration FEB Path Correction

### PR DESCRIPTION
**Pull request by olschewski**
Added a correction module to account for FEB path lengths.
It can run on t0 db files and outputs a corrected t0 db file.

### CODE REVIEW

**Comment by olschewski** [comment]
@cmsbuild This pull request is stuck in open for some time. Is there anything I can do about it?

**Comment by olschewski** [comment]
Unfortunatley, the last 3 weeks didn't happen anything again. What can we do about this?

**Comment by diguida** [comment]
@olschewski is this a back port from 74X?

**Comment by olschewski** [comment]
I started this request back in October, so at that time it was supposed to be included in 73.

**Comment by diguida** [comment]
I see, it was stuck and the bot did not notice it.
Ok, let's do this: forward it to 74X. If you want it in 73X, keep it open, otherwise close it.
Sorry for that.

**Comment by olschewski** [comment]
What do you mean with forward? Checking out 74X, applying the changes there, and starting a new pull request? Or is there an easier way?

**Comment by diguida** [comment]
Exactly.
You can use the `git rebase --onto` feature as described [here](http://git-scm.com/docs/git-rebase)

**Comment by diguida** [comment]
Suggested way:

````
$ cmsrel CMSSW_7_4_0_pre6
$ cd CMSSW_7_4_0_pre6/src
$ cmsenv
$ git cms-addpkg CalibMuon/DTCalibration
$ git checkout -b dtcalib-t0febpathcorrection my-cmssw/dtcalib-t0febpathcorrection
$ git checkout -b dtcalib-t0febpathcorrection_74X
$ git rebase --onto from-CMSSW_7_4_0_pre6 dtcalib-t0febpathcorrection_74X
````

With this, we make ` dtcalib-t0febpathcorrection_74X` forked from branch `from-CMSSW_7_4_0_pre6` (non-remote tracking branch whose tip is at the tag `CMSSW_7_4_0_pre6`).

**Comment by olschewski** [comment]
Thanks, I will give it a go.

**Comment by olschewski** [comment]
Thanks again, One remark: Your recipe did not completely work out of the box. I guess the last line must read 
git rebase from-CMSSW_7_4_0_pre6

**Comment by diguida** [comment]
@olschewski 
you are right: the correct command is:

````
git rebase --onto from-CMSSW_7_4_0_pre6 official-cmssw/CMSSW_7_3_X
````

as you can see in the examples [here](http://git-scm.com/docs/git-rebase)

**Comment by mmusich** [comment]
@cmsbuild please test

**Comment by diguida** [comment]
please test
the frontier issue is gone now

**Comment by diguida** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
