### PR TITLE
Switch phase2 pixelPair tracking regions to first 5 firstStepPrimaryVertices

### PR DESCRIPTION
**Pull request by makortel**
As for phase1 in #19051, and as mentioned in RECO meeting on June 16
https://indico.cern.ch/event/645986/contributions/2623365/attachments/1478282/2290968/slides_reco_20170616.pdf

Here is an MTV for 1000 single muon events (thanks to @ebrondol!)
https://cms-tracking-validation.web.cern.ch/cms-tracking-validation/PR/CMSSW_9_3_0_pre1_PR19739/
More tests with ttbar (and pileup) will come after we get RelVal samples in 93X (they should be in the making).

Tested in 9_3_0_pre1, expecting changes only in phase2. Based on the phase1 experience, I'd expect the (signal) efficiency to stay the same, and the overall fake rate to decrease (especially in pixelPairStep).

@rovere @VinInn @ebrondol

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by perrotta** [comment]
assign upgrade

**Comment by kpedro88** [comment]
@makortel I don't see any changes in the phase2 comparisons. Maybe 10 events is not enough to see anything?

**Comment by slava77** [comment]
On 7/18/17 8:20 AM, Kevin Pedro wrote:
> @makortel <https://github.com/makortel> I don't see any changes in the
> phase2 comparisons. Maybe 10 events is not enough to see anything?

tests should be done on a sample with PU.
As the title suggests, the effect will be visible in events with more
than 5 PVs

**Comment by VinInn** [comment]
here is it 930_pre2 pu200 1200 events
http://innocent.home.cern.ch/innocent/RelVal/pu200D17_newPP/plots_summary.html

**Comment by kpedro88** [comment]
thanks @VinInn 
looks reasonable to me: increased efficiency, decreased fake/dup/PU rates (primarily for pixel pairs)

**Comment by kpedro88** [comment]
+1

**Comment by slava77** [comment]
On 7/18/17 10:30 AM, Vincenzo Innocente wrote:
> here is it 930_pre2 pu200 1200 events
> http://innocent.home.cern.ch/innocent/RelVal/pu200D17_newPP/plots_summary.html
> 

http://innocent.home.cern.ch/innocent/RelVal/pu200D17_newPP/plots_ootb/effandfake4.pdf

there is a large drop in efficiency around r of 10 cm.
Is this unavoidable now?
Will this be picked up in the future OT-seeded iterations?

**Comment by VinInn** [comment]
and above all 
```
pu200_newPP.log:TimeReport   0.001052     0.001052     0.001052  pixelPairStepClusters
pu200_newPP.log:TimeReport   0.055855     0.055855     0.055855  pixelPairStepHitDoublets
pu200_newPP.log:TimeReport   0.000000     0.000000     0.000000  pixelPairStepSeedClusterMask
pu200_newPP.log:TimeReport   0.000865     0.000865     0.000865  pixelPairStepSeedLayers
pu200_newPP.log:TimeReport   0.031643     0.031643     0.031643  pixelPairStepSeeds
pu200_newPP.log:TimeReport   0.000615     0.000615     0.000615  pixelPairStepSelector
pu200_newPP.log:TimeReport   0.142556     0.142556     0.142556  pixelPairStepTrackCandidates
pu200_newPP.log:TimeReport   0.000018     0.000018     0.000018  pixelPairStepTrackingRegions
pu200_newPP.log:TimeReport   0.034647     0.034647     0.034647  pixelPairStepTracks
pu200_ori.log:TimeReport   0.001031     0.001031     0.001031  pixelPairStepClusters
pu200_ori.log:TimeReport   1.166913     1.166913     1.166913  pixelPairStepHitDoublets
pu200_ori.log:TimeReport   0.000000     0.000000     0.000000  pixelPairStepSeedClusterMask
pu200_ori.log:TimeReport   0.000836     0.000836     0.000836  pixelPairStepSeedLayers
pu200_ori.log:TimeReport   0.644899     0.644899     0.644899  pixelPairStepSeeds
pu200_ori.log:TimeReport   0.001733     0.001733     0.001733  pixelPairStepSelector
pu200_ori.log:TimeReport   2.810353     2.810353     2.810353  pixelPairStepTrackCandidates
pu200_ori.log:TimeReport   0.000029     0.000029     0.000029  pixelPairStepTrackingRegions
pu200_ori.log:TimeReport   0.175214     0.175214     0.175214  pixelPairStepTracks
```

**Comment by VinInn** [comment]
PixelPair is not supposed to pick detached tracks. It is bound to strict vertex region.
Of course with 150 vertices in 10 cm it is not bound much anymore....
So picking detached tracks is indeed the side effect this PR is supposed to cure.
OT seeding is what should target large radius decay.
This is a more general comment: we welcome "volunteers"  in early iterations: still they are not intended and we shall fight them together with the fakes they bring along...

**Comment by perrotta** [comment]
@VinInn @makortel 
Could you please remind me what is plotted in plots_allTPEffic_ootb, from where the following reduced efficiency for low pt tracks at |eta| about1.2 is visible?
tps

See http://innocent.home.cern.ch/innocent/RelVal/pu200D17_newPP/plots_allTPEffic_ootb/effandfake1.pdf

All other distributions show slightly improved efficiency and nicely reduced fakerate...

**Comment by VinInn** [comment]
according to the footnote in
http://innocent.home.cern.ch/innocent/RelVal/pu200D17_newPP/plots_summary.html
All tracks, efficiency denominator contains all TrackingParticles

**Comment by perrotta** [comment]
Ok, I read it, but thank you anyhow...
Let me reformulate the question more explicitely: why in those plots there are such larger inefficiencies with this PR? Is that expected?

**Comment by VinInn** [comment]
This pot includes pileup as well. So yes is expected. It is impossible to cover with doublets all 200 PU vertices as it will be equivalent to have no vertex constrain at all.
As you noticed it costs a factor 20 in time and introduces a large number of fake "detached" tracks.

**Comment by perrotta** [comment]
+1
- General slight increase of signal efficiencies, and lower fakerate.
- The localized lower efficiencies when normalizing on all TPs (as in https://github.com/cms-sw/cmssw/pull/19739#issuecomment-317175463) is expected in high PU environment (see https://github.com/cms-sw/cmssw/pull/19739#issuecomment-317184504)
- CPU time largely improves  on high PU, see https://github.com/cms-sw/cmssw/pull/19739#issuecomment-316166148

**Comment by davidlange6** [comment]
+1

**Pull request merged**
