### PR TITLE
add low pt photons (10-14 GeV) to miniAOD for 75x

### PR DESCRIPTION
**Pull request by cmkuo**
add photons with pt between 10 and 14 GeV with H/E < 0.15 and charged hadron isolation < 10 GeV

### CODE REVIEW

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
@cmkuo Just make the same changes you did in 74X here and for the 76X PR instead.

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
+1

For #10666 ae617a768d0d9da1d2cfb1e4e026ebfe7d06ccac

Adding low-pT photons to Mini-AOD. There should be no changes except in Mini-AOD. #10665 is the 76X version of this PR, and it has already been approved by Reco.

The code changes are satisfactory, and Jenkins tests against baseline CMSSW_7_5_X_2015-08-10-2300 show no significant differences, as expected. The addition of the low-pT photons to Mini-AOD was verified for #10665.

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
+1

For #10666 ebbdea027d13a88c5860fe8c7962b4d88a85fc72

Second approval after code revision.
#10665 is the 76X version of this PR, and it has already been approved by Reco.

The code changes are satisfactory, and Jenkins tests against baseline CMSSW_7_5_X_2015-08-13-1100 show no significant differences, as expected. The addition of the low-pT photons to Mini-AOD was verified for #10665.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
