### PR TITLE
[12.4.X] Move Phase2L1GMT private headers in to plugins dir

### PR DESCRIPTION
**Pull request by smuzaffar**
This is follow up of #39396 . It is not complete backport of #39396 as 12.4.X does not include all changes for these package. This PR just proposes to move the private headers of `L1Trigger/Phase2L1GMT` in to its plugin directory and cleanup of some unused include statements

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by rovere** [comment]
@smuzaffar @perrotta
Recently triggered tests in `12_4` branch all failed on some `unittest`.
From the log of the test, it is not clear which test failed and why.
Do you have any suggestions?

**Comment by perrotta** [comment]
@rovere unit tests in the IB do not show errors, see https://cmssdt.cern.ch/SDT/html/cmssdt-ib/#/ib/CMSSW_12_4_X
I am not able to understand which test does fail here: let wait for the test results becoming avaiable, and then we'll see

**Comment by smuzaffar** [comment]
Here is log of failing unit test https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-c9f2d3/27597/unitTests/src/Configuration/PyReleaseValidation/test/test-das-selected-lumis/testing.log . Looks like some das client failed and complained about `wrong fileLumi record`

**Comment by perrotta** [comment]
Thank you @smuzaffar : nothing to worry about, then

**Comment by rovere** [comment]
Thanks @smuzaffar 
Just for my education for the next time: how did you manage to find the failing unit-test?

**Comment by smuzaffar** [comment]
@rovere , you can either wait for bot to add the test result summary (something like [this](https://github.com/cms-sw/cmssw/pull/39412#issuecomment-1249373275) ) or you click on the `Details` link after `cms/PR_NUM/SCRAM_ARCH` check which should take you to test results area e.g. in this case https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-c9f2d3/27597/ and then click on the `unitTests`

**Comment by rovere** [comment]
Thanks  @smuzaffar 
Would it make more sense to use that link also for the `Details` after the `unittest` entry, the one marked as failing.
That's the one I was naively checking.

**Comment by perrotta** [comment]
please test

**Comment by smuzaffar** [comment]
> Thanks @smuzaffar Would it make more sense to use that link also for the `Details` after the `unittest` entry, the one marked as failing? That's the one I was naively checking.

We also need to provide link for actual jenkins job, so for most of the tests the `Details` link points back to jenkins job. To provide access to partially available test results we use `cms/PR/ARCH` link

**Comment by perrotta** [comment]
backport of https://github.com/cms-sw/cmssw/pull/39396
(partial)

**Comment by perrotta** [comment]
@smuzaffar while this PR is certainly "nice to have", does it really fix anything in 12_4_X at the end? Does the cleanup of the unused include statements actually help the building anyhow?
For now I am not bypassing the @cms-sw/l1-l2 signature and merge it in the near to come 12_4_X release for the resume of the data taking: however, if this is a real bugfix, we can do it before the next IB.

**Comment by smuzaffar** [comment]
@perrotta , this does not fix any visible build issues for 12.4.X though it does cleanup the plugin by moving private headers in to plugin directory. So it is not really required for 12.4.X.

**Comment by cecilecaillol** [comment]
+l1

**Comment by perrotta** [comment]
+1

**Pull request merged**
