### PR TITLE
update the list of paths monitored by Higgs HLT DQM

### PR DESCRIPTION
**Pull request by HuguesBrun**
Update the list of the paths according to the HTL JIRA ticket 213 and 199

### CODE REVIEW

**Comment by degano** [comment]
@cmsbuild please test

**Comment by HuguesBrun** [comment]
Hello, 
I am not sure to understand what went wrong with the test, it seems that the error comes from the fact the folder HLT/Muon is missing but my configuration change does not affect it.

**Comment by deguio** [comment]
+1
hello @HuguesBrun 
one error I see is the following:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-7364/2122/DQMTestsResults/DQMTestsResults/8/p8.a.1.1.log
and it is not related.

**Comment by deguio** [comment]
please test

**Pull request merged**
