### PR TITLE
HCALDQM: Add new ZDC electronics constants[13_2_X]

### PR DESCRIPTION
**Pull request by lwang046**
#### PR description:
Backport of #42894, add new ZDC FED/crate information to HCAL DQM packages.

### CODE REVIEW

**Comment by tjavaid** [comment]
please test

**Comment by tjavaid** [comment]
type hcal

**Comment by tjavaid** [comment]
backport of #42894

**Comment by perrotta** [comment]
code-checks

**Comment by perrotta** [comment]
@lwang046 please add [13_2_X] to the PR title, so that it is clear from it that it is a backport

**Comment by syuvivida** [comment]
Tested at p5 with both default HLT GT "132X_dataRun3_HLT_v2" and the GT candidate that includes a new ZDC electronics map as described in this [JIRA ticket](https://its.cern.ch/jira/browse/CMSALCAFAST-42). In both cases hcal, hcalreco, hcalcalib clients ran without crashing and most plots are consistent with the one without this PR.

**Comment by saumyaphor4252** [comment]
urgent
- Needed for ongoing data-taking

**Comment by tjavaid** [comment]
+1

**Comment by lwang046** [comment]
The DQM histogram change in HCAL reflects the newly added EID as expected

**Comment by perrotta** [comment]
@tjavaid please take care of signing also the master version of this PR https://github.com/cms-sw/cmssw/pull/42894, as soon as tests finish for it (I launched them right now)

**Comment by antoniovilela** [comment]
+1

**Comment by perrotta** [comment]
@lwang046  @abdoulline there are several paused jobs for StreamExpressCosmics, see https://cms-talk.web.cern.ch/t/paused-jobs-for-streamexpresscosmics-cannot-initialize-hcaldetid/30096. They came after switching HLT to CMSSW_13_2_5_patch1, and I suspect the culprit could be the inclusion of this PR. 

The error message says
```
An exception of category 'Invalid DetId' occurred while
   [0] Processing global end LuminosityBlock run: 374577 luminosityBlock: 1
   [1] Calling method for module HcalOfflineHarvesting/'hcalOfflineHarvesting'
Exception Message:
Cannot initialize HcalDetId from 54000011
```
and it is issued by https://github.com/cms-sw/cmssw/blob/CMSSW_13_2_X/DataFormats/HcalDetId/interface/HcalDetId.h#L62

Do you have any suggestion?

**Comment by abdoulline** [comment]
Hi @perrotta 

apparently in the HCAL Offline DQM harvesting there is an illegal cast of HcalZDCDetId (new entries in the new emap)  to HcalDetId (no protection in DQM code?)  
And the issue comes as a surprise after JIRA validation:
https://its.cern.ch/jira/browse/CMSALCAFAST-42

Long is investigating, in the meantime, HCAL emap in DB conditions (production tag) is being reverted back to old/incorrect but "harmless" one   
https://cms-talk.web.cern.ch/t/fast-track-validation-hlt-express-new-hcal-electronicsmap-condition/29957/7

**Comment by mandrenguyen** [comment]
Hi @lwang046, all
Heavy ions really needs a short term fix that will allow to use the new emap, with or without the relevant offline DQM.
Without this we do not have any ZDC information in the reconstructed data tiers. 
Does this PR accomplish this, and if not, can such a fix be provided quickly?

**Comment by lwang046** [comment]
Hi @mandrenguyen , this PR allows the new emap to be included with no issues from the **online** DQM, while PR 42919 allows the new emap to be included with no issues from the **offline** DQM.

**Pull request merged**
