### PR TITLE
[12_0_X] Add CMSSW version to StatisticsSenderService

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

Backport of https://github.com/cms-sw/cmssw/pull/37220.

#### PR validation:

Unit tests pass

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
Unit test failure was timeout
```
An exception of category 'ExternalFailed' occurred while
   [0] Processing global begin LuminosityBlock run: 1 luminosityBlock: 1
   [1] Calling method for module ExternalGeneratorFilter/'gen2'
Exception Message:
failed waiting for external process. Timed out after 300 seconds.
----- End Fatal Exception -------------------------------------------------
```

**Comment by makortel** [comment]
@cmsbuild, please test

Let's try one more time nevertheless

**Comment by makortel** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
