### PR TITLE
DT Geometry: Update validation test

### PR DESCRIPTION
**Pull request by ianna**
#### PR description:

* Remove the need to skip a part of the output file for comparison
* Cleanup

@smuzaffar and @fabiocos - I left the normal vector output as is since the gcc numeric limits in ```CMSSW_11_0_DEVEL_X_2019-10-16-2300``` for ```float``` are ```-3.40282e+38``` for lowest, ```1.17549e-38``` for min and ```3.40282e+38``` for max. If the test will report any difference, I check it and update the reference file if needed.

#### if this PR is a backport please specify the original PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by fabiocos** [comment]
code-checks

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
please test

**Comment by ianna** [comment]
replaced by https://github.com/cms-sw/cmssw/pull/28224

**Pull request closed without merging**
