### PR TITLE
update photon path names for SMP HLT DQM 

### PR DESCRIPTION
**Pull request by olivito**
Updating the photon path names in the SMP HLT DQM config, to correspond to changes in this JIRA ticket:
https://its.cern.ch/jira/browse/CMSHLT-230

### CODE REVIEW

**Comment by degano** [comment]
@cmsbuild please test

**Comment by degano** [comment]
@cmsbuild please test

**Comment by davidlange6** [comment]
could we add this package to dqm and trigger their review.

**Comment by davidlange6** [comment]
ping @degano

**Comment by degano** [comment]
@davidlange6 I added the package some day ago, but a comment (whatever comment) was needed for the bot to update the labels, yours did just that :)

**Comment by davidlange6** [comment]
ah… thanks

**Comment by deguio** [comment]
+1

**Pull request merged**
