### PR TITLE
migrate to python3 compatible syntax for local imports

### PR DESCRIPTION
**Pull request by davidlange6**
For packages with multiple python files, they must use 

from . import Options 
instead of
import Options

or

from .Options import myFunc
instead of
from Options import myFunc

as python3 does not allow relative imports. This was missed from my previous migrations as the futurize tool needed a correct python path to be set up before working for this tool. There maybe some others in this seme category - this was the first thing I stumbled on.

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
hum - it seems the unit test that tries to run FWCore/ParameterSet/python/*.py from a random directory needs some work. (not sure how to change it yet)

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
test failure is not related.

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
please test

**Comment by smuzaffar** [comment]
@davidlange6 , we can ignore these unit tests errors. We have noticed that when PR include too many packages (e.g. in this case over 700) then unit tests misbehave and are mostly killed by `timeout`. Kibana monitoring shows that VM (where tests were running) was doing nothing much during 2h30 and 7h50 when unit tests were running. I guess this unit test `SiStripDAQ_O2O_test` was just waiting to connect to some DB. 

[a] 
https://meter.cern.ch/public/_plugin/kibana/#dashboard/temp/AWkBJH1PH1Ba-9C9l6aW

Jenkins Logs:
```
01:49:09 + echo CMS_PATH=/cvmfs/cms-ib.cern.ch/week0 timeout 21920 scram b -k -j 8 runtests
....
...
07:54:29 + echo 'END OF UNIT TESTS'
```

**Comment by makortel** [comment]
@smuzaffar The crash in `testTauEmbeddingProducers` in https://github.com/cms-sw/cmssw/pull/25917#issuecomment-464513289 was

```
Begin processing the 5th record. Run 274199, Event 246083879, LumiSection 125 on stream 0 at 17-Feb-2019 19:23:28.386 CET


A fatal system signal has occurred: segmentation violation
The following is the call stack containing the origin of the signal.

Sun Feb 17 19:23:34 CET 2019
Thread 2 (LWP 18264):
#0  0x00007fee68b74279 in ?? ()
#1  0x00007fee532b214c in ?? ()
#2  0x0000000000006847 in ?? ()
#3  0x000000000000000a in ?? ()
#4  0x00007fee610728c7 in ?? ()
#5  0x0000000000000000 in ?? ()
Thread 1 (LWP 16794):
#0  0x00007fee6888bf0d in ?? ()
#1  0x0000000000000000 in ?? ()

Current Modules:

Module: BunchSpacingProducer:bunchSpacingProducer (crashed)

A fatal system signal has occurred: segmentation violation
/build/cmsbld/jenkins/workspace/ib-any-integration/CMSSW_10_5_X_2019-02-16-1100/src/TauAnalysis/MCEmbeddingTools/test/runtests.sh: line 34: 16794 Segmentation fault      cmsDriver.py LHEembeddingCLEAN --filein file:selected.root --runUnscheduled --fileout file:lhe_and_cleaned.root --data --scenario pp --conditions auto:run2_data --era Run2_2016_HIPM --eventcontent RAWRECO --datatier RAWRECO --step RAW2DIGI,RECO --customise Configuration/DataProcessing/RecoTLR.customisePostEra_Run2_2016,TauAnalysis/MCEmbeddingTools/customisers.customiseLHEandCleaning -n -1 python_filename lheprodandcleaning.py
+ die 'Failure during LHE and Cleaning step' 139
+ echo Failure during LHE and Cleaning step: status 139
Failure during LHE and Cleaning step: status 139
+ exit 139
status = 35584

---> test testTauEmbeddingProducers had ERRORS
```

Could you clarify if this (segfault) is really the expected symptom of "unit tests misbehaving and getting killed"? I.e. the system does not send a signal that the framework would catch?

I'm asking because there are other PRs (most notably #25907) that observe randomly crashing unit tests with similarly weird stack traces.

**Comment by Dr15Jones** [comment]
+1

**Comment by davidlange6** [comment]
Thanks... the issue is however that PRs tend to get ignored when their test status is failed...

**Comment by andrius-k** [comment]
+1

**Comment by smuzaffar** [comment]
@makortel , yes I think it is misbehavior. Although it was not killed due to timeout but we have seen this unit test randomly failing during ROOT PR tests

https://github.com/cms-sw/cmsdist/pull/4674#issuecomment-460603870
https://github.com/cms-sw/cmsdist/pull/4674#issuecomment-461962223

**Comment by makortel** [comment]
@smuzaffar Thanks (the set of failing unit tests in cms-sw/cmsdist#4674 is indeed very close to those in #25907). Do you have any idea what is causing the crashes then?

**Comment by kpedro88** [comment]
+upgrade

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
as usual the unit tests failures are not related. It would be great to get this set of simple changes merged before it had to be rebased again..

**Comment by andrius-k** [comment]
+1

**Comment by Dr15Jones** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade

**Comment by prebello** [comment]
checks have failed : Target 'check-headers' not remade because of errors.
please, should PdmV approve it?

**Comment by Dr15Jones** [comment]
@prebello the header inconsistencies are not due to this pull request and happen to all pull requests which cause those headers to be checked.

**Comment by prebello** [comment]
+1

Thank you @Dr15Jones .. approved

**Comment by Martin-Grunewald** [comment]
+1

**Comment by ggovi** [comment]
+1

**Comment by santocch** [comment]
+1

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/25917	599ae2f
- the technical configuration code changes are in line with the PR description
- jenkins tests pass and comparisons with the baseline show no (relevant) differences

**Comment by fabiocos** [comment]
@tocheng @civanch @rekovic @cmsdoxy could you please check and comment or sign it? I would like to avoid possibility of conflicts with future PRs and move forward with this PR, the update looks transparent

**Comment by civanch** [comment]
+1

**Comment by fabiocos** [comment]
+1

technical code update

**Comment by fabiocos** [comment]
merge

@tocheng @rekovic @cmsdoxy please check and sign it for reference in case

**Pull request merged**
