### PR TITLE
Changed default HI vertex smearing parameter to 2018 PbPb

### PR DESCRIPTION
**Pull request by ColeLindsey**
I missed this addition on my last PR https://github.com/cms-sw/cmssw/pull/25390 and so this is just updating the default HI smearing parameter.

### CODE REVIEW

**Comment by smuzaffar** [comment]
@ColeLindsey , we did a cleanup of some large data files which were merge in cmssw repo few days ago. Due to this cleanup this PR is now in a bad state (includes all the commits which we rewrite to avoid the large data files), Can you please rebase this PR based on new head?

**Comment by perrotta** [comment]
-1
(Not for reco, rebase needed)

**Comment by kpedro88** [comment]
FYI, how to rebase: http://cms-sw.github.io/tutorial-resolve-conflicts.html

**Comment by davidlange6** [comment]
Your PR is unmergeable. Please have a look and possibly rebase it.

**Comment by fabiocos** [comment]
@ColeLindsey we may close this PR, as it was replaced by #25474

**Pull request closed without merging**
