### PR TITLE
Update GEMRECO geometry in online GTs [11_3_X]

### PR DESCRIPTION
**Pull request by francescobrivio**
#### PR description:
Backport of https://github.com/cms-sw/cmssw/pull/34165.
- Update online GTs with a new GEMRECO geometry  tag used in MWGR#4 (June 2021), as detailed in https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/4408.html and https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/4410.html. The new GEMRECO geometry tag ([`GEMRECO_Geometry_v2_hlt`](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/tags/GEMRECO_Geometry_v2_hlt)) contains a payload valid from 11_3_X which has been appended with since 341787.
- Reverting the change in `ecalPedestalPCLworker_cfi.py` introduced in https://github.com/cms-sw/cmssw/pull/33765 to test the ECAL Pedestal PCL workflow during MWGR.

GT diffs:
**Run 3 data HLT**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/113X_dataRun3_HLT_v1/113X_dataRun3_HLT_v2

**Run 2 HLT RelVals**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/113X_dataRun2_HLT_relval_v1/113X_dataRun2_HLT_relval_v2

**Run 3 data (express)**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/113X_dataRun3_Express_v1/113X_dataRun3_Express_v3

**Run 3 data (prompt)**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/113X_dataRun3_Prompt_v1/113X_dataRun3_Prompt_v3

#### PR validation:
Tested with:
```
runTheMatrix.py -l 1010.0,138.1,138.2 --ibeos -j4
addOnTests.py -j8
```

#### Backport:
This is the backport of https://github.com/cms-sw/cmssw/pull/34165.

### CODE REVIEW

**Comment by francescobrivio** [comment]
test parameters:
 - workflow = 1010.0,138.1,138.2

**Comment by francescobrivio** [comment]
backport

**Comment by francescobrivio** [comment]
@cmsbuild please test

**Comment by malbouis** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
