### PR TITLE
Update dimuon L3 filter, for 2017 online muon reconstruction. 92X Version

### PR DESCRIPTION
**Pull request by BenjaminRS**
This is a 92X backport of PR #19466 
Updating the dimuon L3 filter to:
- handle muons reconstructed by the full (L3FromL2 + L3FromL1) iterL3 sequence, and perform the matching with the candidate from the previous step
- introduce the possibility of disabling the matching of the L3 to the previous candidate (L2 or L1)

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by BenjaminRS** [comment]
Hi @davidlange6 - you signed off on the PR #19466, can you also sign off on this backport please?
Thanks! Benjamin

**Comment by davidlange6** [comment]
+1

**Pull request merged**
