### PR TITLE
Run2-alca136 Update the macros needed for IsoTrack Calibration of HCAL

### PR DESCRIPTION
**Pull request by bsunanda**
Utilize a  chain rather than a single input file for calibration or monitoring. Include selection on # primary vertex. Include fitting for the muon signal

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by lpernie** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
