### PR TITLE
[14_0_X] Protect against null `VertexRef` in `deep_helpers.cc`

### PR DESCRIPTION
**Pull request by mandrenguyen**
backport of #45296

### CODE REVIEW

**Comment by mandrenguyen** [comment]
type btv

**Comment by mandrenguyen** [comment]
please test

**Comment by mandrenguyen** [comment]
+1

**Comment by mandrenguyen** [comment]
urgent
At joint ops the ORM shifter (David Lange) suggested that this PR could be patch-compatible.  Otherwise, it might be a while before this is included in the release.
We could discuss this at the Offline Release Planning meeting tomorrow.

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
