### PR TITLE
Phase2-hgx135 Update the validation code with correct reference of layers

### PR DESCRIPTION
**Pull request by bsunanda**
The earlier ad-hoc fix was not correct for Digi/RecHit's.

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by kpedro88** [comment]
@bsunanda this seems to have affected the old HGCal geometries as well. Is that expected?

**Comment by bsunanda** [comment]
The histogram titles were wrong before. There was also some bug in filling the histograms

**Comment by andrius-k** [comment]
+1

**Comment by fabiocos** [comment]
please test workflow 24032.0

**Comment by fabiocos** [comment]
please test workflow 24034.0

**Comment by fabiocos** [comment]
+1

**Pull request merged**
