### PR TITLE
Phase2-hgx264 Try to resolve the issue of Rmax for the HE section of HGCal

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Try to resolve the issue of Rmax for the HE section of HGCal

#### PR validation:

Tested using the runTheMatrix workflows: 23234.0, 28234.0, 31434.0, 32234.0, 32634.0

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by kpedro88** [comment]
please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade

**Comment by qliphy** [comment]
+1

**Pull request merged**
