### PR TITLE
Extended checks on geometry

### PR DESCRIPTION
**Pull request by civanch**
Modification for Geant4 10.1p02: slightly different interface to gdml writer and introduced usage of G4EmParameters.

Fix on one static analyser warning

Extended geometry overlap checks to sub-regions, added possibility to make gdml dump of sub-detectors.

Should not have any effect on production.

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by civanch** [comment]
please test
forgotten file is added

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
