### PR TITLE
Update muon shower (HMT) emulator [12_4_X] 

### PR DESCRIPTION
**Pull request by kakwok**
#### PR description:

Backport of https://github.com/cms-sw/cmssw/pull/38941

Including emulator update in 12_5_X will help DQM comparison between data/emulator in P5 for HMT trigger.

DQM plots have already been enabled in: https://github.com/cms-sw/cmssw/pull/38639

### CODE REVIEW

**Comment by mandrenguyen** [comment]
please test

**Comment by mandrenguyen** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by cecilecaillol** [comment]
+l1

**Comment by rappoccio** [comment]
This is a very large PR that changes dataformats. As such, I don't think it should be backported to 12_4. We will discuss at the next ORP.

**Comment by rappoccio** [comment]
hold

**Comment by rappoccio** [comment]
As discussed in ORP yesterday, we request DQM and DAQ to sign off on this large PR to backport for 12.4 since it may affect datataking and operations. Once these are okay'd we will remove the hold.

**Comment by perrotta** [comment]
@kakwok @cms-sw/l1-l2 is the purpose of this PR really only meant to help DQM comparison between data/emulator for HMT trigger, as stated in the PR description?

If so, we would suggest not to backport it in a stable data-taking release, as it touches quite several other delicate parts of the code and its dataformats, as explained by @rappoccio here [above](https://github.com/cms-sw/cmssw/pull/39260#issuecomment-1234218016)

The 12_5_X backport can still be taken into account, instead, since there will be the possibility to validate it further before the start of the HI data taking.

Please let us know,

**Comment by cecilecaillol** [comment]
I think we can indeed discard this backport to avoid large modifications to 12_4. But it would be great if @kakwok can confirm

**Comment by kakwok** [comment]
We discussed among the HMT team, we agreed we can avoid this big back-port.

**Comment by rappoccio** [comment]
Thanks @kakwok we will close this then.

**Pull request closed without merging**
