### PR TITLE
HLtriggerOffline/Higgs path update

### PR DESCRIPTION
**Pull request by jasperlauwers**
This PR contains an update of the paths that have to be monitored in the HLT Higgs dqm.

More specifically:
- The paths from the frozen menu are added back as was requested by the TSG
- Old paths that were not used any more are removed
- Paths are updated for the Htaunu analysis and a fix is included in the code which was causing an error for these paths
- A new path for WHToENuBB is included
- The summary plots are added for MSSMHbb

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1
provided it passes the tests

**Comment by deguio** [comment]
@jasperlauwers see my comments for the 74 version of this PR (#11209)

**Comment by davidlange6** [comment]
+1

**Pull request merged**
