### PR TITLE
Hcal spring cleaning

### PR DESCRIPTION
**Pull request by kpedro88**
(Closer to summer now, but oh well...)

A large number of unfinished and/or unused features have accumulated in the HcalDigitizer code over many years. This PR removes them to make the code easier to understand and maintain. The removal of these features was discussed on the HCAL hypernews: https://hypernews.cern.ch/HyperNews/CMS/get/hcal-cmssw/194.html

Coming in subsequent PRs:
- removal of HcalUpgradeDataFrames (once reco for QIE10 and QIE11 is finished, to keep Phase2 local reco alive)
- reorganization of HcalDigitizer (and maybe CaloTDigitizer) to be more object-oriented

attn: @abdoulline, @bsunanda

### CODE REVIEW

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by kpedro88** [comment]
Appears to be something wrong in the comparison, I'm investigating.

**Comment by abdoulline** [comment]
Juts would like to add: 
from my simple pion gun scan it looks like SIM is OK,  while only HE reco exists (no HB/HO/HF)
NB: Problem is observed in Digis (HE has meaningful ones,  while HB/HO/HF - only pedestals/noise ones), when looking more closely at _all_ available histos via TBrowser (and not only at those "published" below)

https://cms-cpt-software.web.cern.ch/cms-cpt-software/General/Validation/SVSuite/HCAL/calo_scan_single_pi/810pre7_PR14856_vs_810pre7_SinglePi/

**Comment by kpedro88** [comment]
@abdoulline - yes, I've also seen that the problem is in the digis somewhere. I plan to run `git bisect` to isolate the source of the problem, just haven't had time yet.

**Comment by kpedro88** [comment]
@abdoulline it looks like the HO Zecotek vs Hamamatsu SiPM setting actually is used in the run1_mc GT. Do we want to keep this around to preserve run1 results? It seems like a lot of extra stuff in the SimParameters to me, but I can revert the removal if necessary.

(It also causes minor fluctuations in the HB/HE/HF results, because of fewer random number calls without the HO SipmHitResponse.)

**Comment by abdoulline** [comment]
Mea culpa... I forgot that the fact we were using different shapes Id 
specifically for HO Zekotec and Hamamatsu both in HcalMCParams and 
HcalRecoParams (the latter means - for data as well with appropriately set 
IOVs ...) may affect HO types removal. And intorducing some tricks in 
the code to cope with it might not be an elegant option at all...

I'm not sure we can (= will be allowed to do so by AlCa)
remove this stuff from DB by making new tags for Run 1 with 
"unified" SiPMs HO shapes (as we have it for Run 2), even if we know HO 
didn't really matter during Run 1...

**Comment by kpedro88** [comment]
Ah, I hadn't considered the RecoParams, that complicates things further.

It seems unfortunate to keep a bunch of unnecessary code in `HcalSimParameterMap` and `HcalDigitizer` just to somehow preserve Run1 features that will never actually be used in 81X... but maybe we should at least push that issue to a future PR (like the few things I mentioned in the first message, as well as the possible deletion of `HcalCholeskyMatrices` from the database) so this one can be merged.

**Comment by abdoulline** [comment]
Let us try to clarify with AlCa/Offline if CMS is still going to use 
81X for Run 1 MC (I presume not) or data processing (I hope not, but even 
if yes, HO role was really minimal, if any even in late Run 1)...
If not, then we can remove those items (including access to 
HcalCholeskyMatrices in DBService, which then would allow us to clean up 
DB).

**Comment by kpedro88** [comment]
That sounds good. I'm going to rebase the HO commit out of this PR so we can get a clean comparison, and then we can discuss with AlCa another PR that would hopefully eliminate both the unnecessary HO stuff and the HcalCholeskyMatrix DB object.

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by davidlange6** [comment]
@kpedro88

by “Run 1”… if you mean features needed for run 1 hardware, then they are needed. If you mean features used in the simulation during 2010-2012 that are now replaced by something better (for run1 and run2 simulation) then lets try to remove them

**Comment by kpedro88** [comment]
@davidlange6 my primary concern is cleaning up unused things in the simulation. For a fully accurate Run1 simulation, we would need to have these different types of SiPMs in various channels of HO... but it's not clear to me why we need or expect a fully accurate Run1 simulation in 81X and beyond. (Especially since HO was not really used for physics in Run1, and I don't think anyone expects to be able to go back to this intermediate hardware installation/development case.)

**Comment by davidlange6** [comment]
> On Jun 19, 2016, at 9:25 PM, Kevin Pedro <notifications@github.com> wrote:
> 
> @davidlange6 my primary concern is cleaning up unused things in the simulation. For a fully accurate Run1 simulation, we would need to have these different types of SiPMs in various channels of HO... but it's not clear to me why we need or expect a fully accurate Run1 simulation in 81X and beyond. (Especially since HO was not really used for physics in Run1, and I don't think anyone expects to be able to go back to this intermediate hardware installation/development case.)
> 

we still support run1 in 81x… that can of course change in time, but not it hasn’t been proposed yet (just the opposite was desired a year ago, but things change)

All for cleaning up unused things!

**Comment by kpedro88** [comment]
Okay, I guess we'll leave it for now. We can potentially revisit this as the HE SiPM code development continues. Some of the parameters for SiPMs currently in HcalSimParameters from Python may be put into the database.

**Comment by kpedro88** [comment]
@civanch the comparison looks good to me now.

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
