### PR TITLE
Create a trigger pre-fire veto bit using trigger rules 

### PR DESCRIPTION
**Pull request by apana**

### CODE REVIEW

**Comment by rekovic** [comment]
please test

**Comment by rekovic** [comment]
@peruzzim 
> What data format can this producer run on? XPOG would really like to add it to MINIAOD for UL

On `TCDSRecord`.
Yes, this development is indeed meant to be used for UL.  This can be done by running L1:REPACK.

**Comment by rekovic** [comment]
@apana 
Can you please add the development also in 
`Configuration/StandardSequences/python/SimL1EmulatorRepack_uGT_cff.py`

**Comment by Martin-Grunewald** [comment]
-1
I think a rebase is needed

**Comment by kpedro88** [comment]
please follow http://cms-sw.github.io/tutorial-resolve-conflicts.html and do not use `cms-merge-topic` to update PRs in the future

**Comment by slava77** [comment]
-1

**Comment by fabiocos** [comment]
@apana could you please rebase correctly your branch on the most recent IBs? And add a suitable description of the PR and of the performed tests?

**Comment by peruzzim** [comment]
@apana do you have an estimate of the timescale to move forward with this PR? Thanks

**Comment by apana** [comment]
Dear @fabiocos and @peruzzim,

This PR has been superseded by #26461.  Sorry I forget to mention it to you.

**Pull request closed without merging**
