### PR TITLE
Enable forceGeneration for L1 O2O online producers

### PR DESCRIPTION
**Pull request by panoskatsoulis**
#### PR description:

This PR is complementary to #37602 for fixing several issues of the L1o2o in 12_3 onward.
One of the main problems was that since the producers for the requested ES Rcds are now run in construction time, several exceptions that where handled in the `produce()` method of the L1 `L1CondDBPayloadWriterExt` module now are impossible to be handled properly.

After the P5 deployment of the changes included in 37602, one last case has been found where an exception was thrown when the key of a single subsystem was already included in the db and in this case the o2o procedure was stopped for this subsystem (with an exception to be handled by the code block in `produce()`).
https://github.com/panoskatsoulis/cmssw/blob/0e675061b02ec7636f1a7f726647b7f6dcac2834/CondTools/L1Trigger/interface/L1ConfigOnlineProdBase.h#L123-L157

This PR includes cfg modifications needed for forcing the L1 online producers to run no matter if the resulting object exist in the db (however will not be uploaded if it already exist)
It's required for cases where the following happens
- L1system 1 **exists**
- L1system 2 **exists**
- L1system 3 **new key**

#### PR validation:
This modification is tested in Prep and also is used atm as local custom patch for the L1 O2O Jobs at P5 (without problems)
The unit tests implemented in 37602 didn't catch this problem because the local sqlite file from the data repo was not prepared for this "real-case" scenario that occurred when we tested with more keys.
So, the file in https://github.com/cms-data/L1TriggerConfig-L1TConfigProducers is meant to be updated too for better future testing.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:
Not sure if a backport is needed
Atm these mods are implemented in a custom patch on the `conddb-1` machine.
In case more 12_3 releases are going to be deployed for the o2o machines at P5 a backport is also required.

### CODE REVIEW

**Comment by epalencia** [comment]
Please test

**Comment by tvami** [comment]
+db
 * unit tests pass: https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-66ce46/24542/unitTests/success.html

**Comment by tvami** [comment]
@panoskatsoulis I believe this should be backported to 12_3_X

**Comment by cecilecaillol** [comment]
+l1

**Comment by panoskatsoulis** [comment]
backported here https://github.com/cms-sw/cmssw/pull/37886

**Comment by perrotta** [comment]
> So, the file in https://github.com/cms-data/L1TriggerConfig-L1TConfigProducers is meant to be updated too for better future testing.

@panoskatsoulis would it be possible to update it, as you are also proposing, so that the unit tests can actually be used to catch these kind of issues?

**Comment by perrotta** [comment]
+1
- Maybe the data file with the updated scenarios to be tested could be made available before we merge also the backport PR...

**Comment by panoskatsoulis** [comment]
> +1
> 
>     * Maybe the data file with the updated scenarios to be tested could be made available before we merge also the backport PR...

Hi @perrotta, 
yes I will also follow up with the updated sqlite file by tomorrow
(it needs some local testing)

**Comment by panoskatsoulis** [comment]
> +1
> 
>     * Maybe the data file with the updated scenarios to be tested could be made available before we merge also the backport PR...

sorry for delaying it that much
https://github.com/cms-data/L1TriggerConfig-L1TConfigProducers/pull/2

**Pull request merged**
