### PR TITLE
Remove redefinition of EDM_ML_DEBUG in HcalDigitizer.cc

### PR DESCRIPTION
**Pull request by iarspider**
#### PR description:

Title says it all.

#### PR validation:

Bot tests

### CODE REVIEW

**Comment by iarspider** [comment]
please test for CMSSW_14_2_DBG_X

**Comment by civanch** [comment]
+1

the fix is obvious, should not affect any test

**Comment by civanch** [comment]
urgent

**Comment by civanch** [comment]
Do not know what happens in testing but not related to this PR.

**Comment by civanch** [comment]
please test

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
