### PR TITLE
MTD geometry: update tests to scenario D88, update DDFilteredView::parameters() accordingly

### PR DESCRIPTION
**Pull request by fabiocos**
#### PR description:

This PR addresses the issue https://github.com/cms-sw/cmssw/issues/36837#issuecomment-1038860482 reported at the simulation meeting https://indico.cern.ch/event/1127757/contributions/4733494/attachments/2389568/4085879/20220211-Phase2SWPlan.pdf slide 12 by @srimanob . 

All the MTD standalone geometry tests are moved to the latest D88 scenario, and in order to cope with boolean solids, the ```DetectorDescription/DDCMS``` package is update in the ```DDFilteredView::parameters()``` method, to accomodate also polycones as possible components of a boolean solid.

The unit tests need the appropriate reference https://github.com/cms-data/Geometry-TestReference/pull/10 to correctly run.

#### PR validation:

MTD geometry unit tests run smoothly and provide the expected geometry dump (as in scenario D77 with only a z shift in ETL sensors position).

### CODE REVIEW

**Comment by fabiocos** [comment]
please test with https://github.com/cms-data/Geometry-TestReference/pull/10

**Comment by fabiocos** [comment]
@srimanob the external is needed just to get the final comparison in the MTD unit tests correct, I run the configuration and use its output as the new reference. For any other purpose the external is useless. After this PR step2 still crashes anyway:

```
----- Begin Fatal Exception 15-Feb-2022 11:51:46 CET-----------------------
An exception of category 'InvalidReference' occurred while
   [0] Processing global begin Run run: 1
   [1] Prefetching for module L1FPGATrackProducer/'TTTracksFromExtendedTrackletEmulation'
   [2] Calling method for EventSetup module trackerDTC::ProducerES/'TrackTriggerSetup'
Exception Message:
NullPointer 
----- End Fatal Exception -------------------------------------------------
Another exception was caught while trying to clean up files after the primary fatal exception.
```

**Comment by srimanob** [comment]
Hi @fabiocos 
The issue of MTD found in step-3 when I run (i) GEN-SIM with DD4hep ==> (ii) DIGI-HLT with DDD.
So I would like to test with step-3 for the next issue.

**Comment by srimanob** [comment]
Page 11-12 of https://indico.cern.ch/event/1127757/contributions/4733494/attachments/2389568/4085879/20220211-Phase2SWPlan.pdf includes the testing of running DD4hep GEN-SIM ⇒ DDD DIGI-HLT ⇒ DD4hep RECO. I will try to turn DT-alignment off and the this fixed MTD to see what is the next :)

**Comment by fabiocos** [comment]
@srimanob merging this PR should be enough, you need the external just when you issue a ```scram b runtests``` command. In principle for that it should be enough to point to the correct external copy in the ```cmsswdata.xml``` in the config section of the working area, although I did not find the correct replacement syntax for time being.

**Comment by fabiocos** [comment]
@srimanob in any case the simplest way to test also the external is to redefine ```CMSSW_SEARCH_PATH``` by prepending the directory where the new reference data files sit

**Comment by srimanob** [comment]
I've tested this PR in RECO step, we can pass issue of MTD reco geometry construction now. I've updated the doc https://docs.google.com/document/d/1es0C2gH8KVt87iDoPRpdq8VVDjuEKtdd4kPjTsfW_RU/edit?usp=sharing

**Comment by srimanob** [comment]
+Upgrade

This PR can't be tested with DD4hep workflow because we have several issues to run. To test, I've done the local test using `cmsDriver.py step3 -s RAW2DIGI,L1Reco,RECO,RECOSIM,PAT --conditions auto:phase2_realistic_T21 --datatier GEN-SIM-RECO,MINIAODSIM -n 10 --eventcontent FEVTDEBUGHLT,MINIAODSIM --geometry DD4hepExtended2026D88 --era Phase2C17I13M9 --procModifiers dd4hep --python RecoGlobal_DD4hep_2026D88.py --no_exec --filein file:step2.root --fileout file:step3.root`
With this PR, the job can run through reco geometry construction. 

The following doc is updated,
https://docs.google.com/document/d/1es0C2gH8KVt87iDoPRpdq8VVDjuEKtdd4kPjTsfW_RU/edit?usp=sharing

**Comment by cvuosalo** [comment]
How should we interpret the test results? Why were additional merge-commits included?

**Comment by perrotta** [comment]
please test
(After the troubles with previous IB, which couldn't build, since CMSSW_12_3_X_2022-02-15-2300 the situation should have returned to normal: let retest, with hopefully no other PRs added on top)

**Comment by fabiocos** [comment]
@perrotta without the external update included any MTD unit test will fail, but this does not mean it did not work, just that the final output comparison included in it was done with the incorrect (D76) reference

**Comment by perrotta** [comment]
please test with https://github.com/cms-data/Geometry-TestReference/pull/10

**Comment by cvuosalo** [comment]
+1

**Comment by clacaputo** [comment]
+reconstruction

**Comment by perrotta** [comment]
+1

**Pull request merged**
