### PR TITLE
TrackingTools/MaterialEffects: Remove class member that is not needed.

### PR DESCRIPTION
**Pull request by gartung**
Remove class member that is not needed.
Return shared_ptr directly from make_shared.

### CODE REVIEW

**Comment by gartung** [comment]
@Dr15Jones

**Comment by Dr15Jones** [comment]
looks good

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
please test

**Comment by slava77** [comment]
@cmsbuild please test

it looks like the failures are gone based on the recent jenkins tests

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/21984	af345ee
- technical 
- jenkins tests pass

**Comment by fabiocos** [comment]
+1

**Pull request merged**
