### PR TITLE
add PV monitoring @HLT

### PR DESCRIPTION
**Pull request by mtosi**
it was https://github.com/cms-sw/cmssw/pull/17996
for some reason a fix I made got lost in the rebase of the first branch
now, all ingredients should be in

I tested this branch by running
runTheMatrix.py -l limited

and I got 
16 15 14 12 7 1 1 1 tests passed, 1 1 0 0 0 0 0 0 failed

the 2 offending workflows are
**4.22**_RunCosmics2011A+RunCosmics2011A+RECOCOSD+ALCACOSD+SKIMCOSD+HARVESTDC Step0-DAS_ERROR Step1-NOTRUN Step2-NOTRUN Step3-NOTRUN Step4-NOTRUN  - time date Fri Mar 24 14:54:38 2017-date Fri Mar 24 14:54
:01 2017; exit: 1 0 0 0 0
**4.53**_RunPhoton2012B+RunPhoton2012B+HLTD+RECODR1reHLT+HARVESTDR1reHLT Step0-PASSED Step1-FAILED Step2-NOTRUN Step3-NOTRUN  - time date Fri Mar 24 14:56:02 2017-date Fri Mar 24 14:54:03 2017; exit: 0 235
52 0 0

both cases have nothing to do w/ this PR

hope it is fine, now

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
HLT test failure in a workflow looking at the PIon menu:

```
----- Begin Fatal Exception 24-Mar-2017 20:54:23 CET-----------------------
An exception of category 'ProductNotFound' occurred while
   [0] Processing  Event run: 1 lumi: 3 event: 102 stream: 3
   [1] Running path 'prevalidation_step'
   [2] Prefetching for module PrimaryVertexAnalyzer4PUSlimmed/'hltPVanalysis'
   [3] Calling method for module VertexAssociatorByPositionAndTracksProducer/'v\
ertexAssociatorByPositionAndTracks4pixelTracks'
Exception Message:
Principal::getByToken: Found zero products matching all criteria
Looking for type: edm::AssociationMap<edm::OneToManyWithQualityGeneric<std::vec\
tor<TrackingParticle>,edm::View<reco::Track>,double,unsigned int,edm::RefProd<s\
td::vector<TrackingParticle> >,edm::RefToBaseProd<reco::Track>,edm::Ref<std::ve\
ctor<TrackingParticle>,TrackingParticle,edm::refhelper::FindUsingAdvance<std::v\
ector<TrackingParticle>,TrackingParticle> >,edm::RefToBase<reco::Track> > >
Looking for module label: tpToHLTpixelTrackAssociation
Looking for productInstanceName:

   Additional Info:
      [a] If you wish to continue processing events after a ProductNotFound exc\
eption,
add "SkipEvent = cms.untracked.vstring('ProductNotFound')" to the "options" PSe\
t in the configuration.

----- End Fatal Exception -------------------------------------------------
```

**Comment by Martin-Grunewald** [comment]
Just change the code that the module does not crash on a missing input collection!

**Comment by Martin-Grunewald** [comment]
-1
until the code(!) is fixed

**Comment by mtosi** [comment]
which is the workflow you ran ?
runTheMatrix.py -l limited did not spot it
thanks

**Comment by Martin-Grunewald** [comment]
Please run STORM's TSG tests:
```
cd HLTrigger/Configuration/test
./runAll.csh all                # runs a series of test jobs - see the log files for your favorite trigger
```
see also here:
https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideGlobalHLT#Preparing_a_90X_CMSSW_developer 

Beware that those tests (run by the above script) run for a few hours depending on your machine,
but cycle through all HLT menus and various cmsRun configs incl. DQm and VALDIATION.

You could also try to find workflows exercising the PIon, PRef and Fake, Fake1, Fake2, HLT menus.

But as I said, I would consider it by now hopeless to try to fix the workflows; rather, fix the C++ code 
so that the module does not crash when the input collection is missing, but just books/leaves empty histograms or whatever.

**Comment by mtosi** [comment]
this is what I tried and still trying to fix
and it would be useful to exercise the code updates on a workflow which show the problem
I'll run the STORM test, thanks

**Comment by mtosi** [comment]
I ran runAll.csh
but I do not see this message in the available log files

I do not understand why for some tests I miss the corresponding log files
for instance `ls -ltr *PIon*` gives only the python configuration

I'm now re-running it becasue I found some exit code 90 and 1

**Comment by Martin-Grunewald** [comment]
You should run ```./runAll.csh all``` - note the parameter "all" given to the script!
The output of the script gives you the exit code for each step in each workflow.

**Comment by silviodonato** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by perrotta** [comment]
+1
Mostly identical to the already signed off #17996 (already merged and then reverted because it needed fixes)
Changes applied to the following files with respect to that previous PR are not of concern for reco:
  - DQMOffline/RecoB/plugins/PrimaryVertexMonitor.cc
  - DQMOffline/Trigger/python/METMonitor_cfi.py
  - SimTracker/VertexAssociation/plugins/VertexAssociatorByPositionAndTracksProducer.cc
  - Validation/RecoVertex/src/PrimaryVertexAnalyzer4PUSlimmed.cc

**Comment by dmitrijus** [comment]
+1
What does "foca d'ovatta!" mean? :)

**Comment by kpedro88** [comment]
+1

**Comment by fwyzard** [comment]
>  What does "foca d'ovatta!" mean? :)

that's Mia's gentle approach to swearing: 
image

**Comment by vanbesien** [comment]
I learned something today.

**Pull request merged**
