### PR TITLE
[DQM] Remove DQM reference histogram Rcd

### PR DESCRIPTION
**Pull request by jfernan2**
#### PR description:

We are removing this old servie not used any longer as request of AlCaDb

#### PR validation:

Unit Test in DQM/Integration passed
runTheMatrix -l limited passed

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by tvami** [comment]
@jfernan2 

> +code-checks
> 
> Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-35491/25659
> 
> * This PR adds an extra 92KB to repository
> * Found files with invalid states:
>   
>   * CondTools/DQM/test/DQMReferenceHistogramRootFileEventSetupAnalyzer_OrcoffOnly_cfg.py:
>     
>     * Deleted: [422d8d1](https://github.com/cms-sw/cmssw/commit/422d8d1ea9969ba446254d7824d23df7ee31b080), [8f37387](https://github.com/cms-sw/cmssw/commit/8f37387d8ebed2b1907c0f4029e55d7e8c0c80f3)
>     * Added: [eac1749](https://github.com/cms-sw/cmssw/commit/eac1749466cd9cffd47ed1ff14294a63fe00bfb3)
>   * CondTools/DQM/test/DQMXMLFileEventSetupAnalyzer_cfg.py:
>     
>     * Deleted: [422d8d1](https://github.com/cms-sw/cmssw/commit/422d8d1ea9969ba446254d7824d23df7ee31b080), [8f37387](https://github.com/cms-sw/cmssw/commit/8f37387d8ebed2b1907c0f4029e55d7e8c0c80f3)
>     * Added: [eac1749](https://github.com/cms-sw/cmssw/commit/eac1749466cd9cffd47ed1ff14294a63fe00bfb3)
>   * CondTools/DQM/python/DQMReferenceHistogramRootFileEventSetupAnalyzer_OrcoffOnly_cfi.py:
>     
>     * Deleted: [422d8d1](https://github.com/cms-sw/cmssw/commit/422d8d1ea9969ba446254d7824d23df7ee31b080), [8f37387](https://github.com/cms-sw/cmssw/commit/8f37387d8ebed2b1907c0f4029e55d7e8c0c80f3)
>     * Added: [eac1749](https://github.com/cms-sw/cmssw/commit/eac1749466cd9cffd47ed1ff14294a63fe00bfb3)
>   * CondTools/DQM/python/DQMReferenceHistogramRootFileEventSetupAnalyzer_cfi.py:
>     
>     * Deleted: [422d8d1](https://github.com/cms-sw/cmssw/commit/422d8d1ea9969ba446254d7824d23df7ee31b080), [8f37387](https://github.com/cms-sw/cmssw/commit/8f37387d8ebed2b1907c0f4029e55d7e8c0c80f3)
>     * Added: [eac1749](https://github.com/cms-sw/cmssw/commit/eac1749466cd9cffd47ed1ff14294a63fe00bfb3)
>   * CondTools/DQM/plugins/DQMReferenceHistogramRootFileEventSetupAnalyzer.cc:
>     
>     * Deleted: [422d8d1](https://github.com/cms-sw/cmssw/commit/422d8d1ea9969ba446254d7824d23df7ee31b080), [8f37387](https://github.com/cms-sw/cmssw/commit/8f37387d8ebed2b1907c0f4029e55d7e8c0c80f3)
>     * Added: [eac1749](https://github.com/cms-sw/cmssw/commit/eac1749466cd9cffd47ed1ff14294a63fe00bfb3)
>   * CondTools/DQM/plugins/DQMReferenceHistogramRootFilePopConAnalyzer.cc:
>     
>     * Deleted: [422d8d1](https://github.com/cms-sw/cmssw/commit/422d8d1ea9969ba446254d7824d23df7ee31b080), [8f37387](https://github.com/cms-sw/cmssw/commit/8f37387d8ebed2b1907c0f4029e55d7e8c0c80f3)
>     * Added: [eac1749](https://github.com/cms-sw/cmssw/commit/eac1749466cd9cffd47ed1ff14294a63fe00bfb3)
>   * CondTools/DQM/src/DQMReferenceHistogramRootFileSourceHandler.cc:
>     
>     * Deleted: [422d8d1](https://github.com/cms-sw/cmssw/commit/422d8d1ea9969ba446254d7824d23df7ee31b080)
>     * Added: [eac1749](https://github.com/cms-sw/cmssw/commit/eac1749466cd9cffd47ed1ff14294a63fe00bfb3)
>   * CondFormats/DataRecord/interface/DQMReferenceHistogramRootFileRcd.h:
>     
>     * Deleted: [422d8d1](https://github.com/cms-sw/cmssw/commit/422d8d1ea9969ba446254d7824d23df7ee31b080)
>     * Added: [eac1749](https://github.com/cms-sw/cmssw/commit/eac1749466cd9cffd47ed1ff14294a63fe00bfb3)
>   * CondTools/DQM/interface/DQMReferenceHistogramRootFileSourceHandler.h:
>     
>     * Deleted: [422d8d1](https://github.com/cms-sw/cmssw/commit/422d8d1ea9969ba446254d7824d23df7ee31b080), [8f37387](https://github.com/cms-sw/cmssw/commit/8f37387d8ebed2b1907c0f4029e55d7e8c0c80f3)
>     * Added: [eac1749](https://github.com/cms-sw/cmssw/commit/eac1749466cd9cffd47ed1ff14294a63fe00bfb3)
>   * CondFormats/DataRecord/src/DQMReferenceHistogramRootFileRcd.cc:
>     
>     * Deleted: [422d8d1](https://github.com/cms-sw/cmssw/commit/422d8d1ea9969ba446254d7824d23df7ee31b080)
>     * Added: [eac1749](https://github.com/cms-sw/cmssw/commit/eac1749466cd9cffd47ed1ff14294a63fe00bfb3)
>   * CondTools/DQM/python/DQMReferenceHistogramRootFileEventSetupAnalyzer_SQLiteOnly_cfi.py:
>     
>     * Deleted: [422d8d1](https://github.com/cms-sw/cmssw/commit/422d8d1ea9969ba446254d7824d23df7ee31b080), [8f37387](https://github.com/cms-sw/cmssw/commit/8f37387d8ebed2b1907c0f4029e55d7e8c0c80f3)
>     * Added: [eac1749](https://github.com/cms-sw/cmssw/commit/eac1749466cd9cffd47ed1ff14294a63fe00bfb3)

@jfernan2 would you please consider squashing the commits that delete and add these files? Just to get rid of these "virtual" change msg-s above.

**Comment by tvami** [comment]
I think `CondTools/DQM/src/DQMReferenceHistogramRootFileSourceHandler.cc` can be removed too

**Comment by jfernan2** [comment]
please test

**Comment by tvami** [comment]
Error msg is saying
```
src/CondTools/DQM/test/DQMXMLFileEventSetupAnalyzer_cfg.py" could not be opened!
```
which is expected since that file got removed. I guess this unit test should be removed as well

**Comment by mmusich** [comment]
> which is expected since that file got removed. I guess this unit test should be removed as well

well... I am not sure who gave you the idea that's not used, since there's a recently implemented unit test protecting it: https://github.com/cms-sw/cmssw/pull/31108.
The plan was to restart using `DQMXMLFileRcd` in Database to store Pixel / Strip / Tracking DQM `QTests` configurations.

**Comment by mmusich** [comment]
assign trk-dpg

**Comment by mmusich** [comment]
-1

AlCa is too proactive in removing used records

**Comment by jfernan2** [comment]
Hi @mmusich 
In this case it is dqm (me) to blame, I accidentally removed DQMXMLFileEventSetupAnalyzer_cfg.py while cleaning DQMReferenceHistogram
My apologies, the UnitTest got this mistake

**Comment by jfernan2** [comment]
please test

**Comment by mmusich** [comment]
unassign trk-dpg

thanks @jfernan2

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by jfernan2** [comment]
+1

**Comment by ggovi** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
