### PR TITLE
silence CPP20 warnings about `maybe-uninitialized` variables in `momentumBiasValidation.C`

### LINKED ISSUE #43775: Maybe-uninitialized variables in Alignment/OfflineValidation/macros/momentumBiasValidation.C
In [CMSSW_14_0_CPP20_X_2024-01-22-1100](https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/el8_amd64_gcc12/CMSSW_14_0_CPP20_X_2024-01-22-1100/Alignment/OfflineValidation) IB, the following warnings about potentially uninitialized variables are emitted:

```
  <...>: warning: 'lowLim' may be used uninitialized [-Wmaybe-uninitialized]
    97 |     { return ::new((void*)__location) _Tp(std::forward<_Args>(__args)...); }
      |              ^
<...>/Alignment/OfflineValidation/macros/momentumBiasValidation.C: In function 'extractgausparams':
<...>/Alignment/OfflineValidation/macros/momentumBiasValidation.C:43:12: note: 'lowLim' was declared here
   43 |     double lowLim;
      |            ^
```

```
  <...>: warning: 'upLim' may be used uninitialized [-Wmaybe-uninitialized]
    97 |     { return ::new((void*)__location) _Tp(std::forward<_Args>(__args)...); }
      |              ^
<...>/Alignment/OfflineValidation/macros/momentumBiasValidation.C: In function 'extractgausparams':
<...>/Alignment/OfflineValidation/macros/momentumBiasValidation.C:44:12: note: 'upLim' was declared here
   44 |     double upLim;
      |            ^
```

### PR DESCRIPTION
**Pull request by mmusich**
resolves https://github.com/cms-sw/cmssw/issues/43775

#### PR description:

As per https://github.com/cms-sw/cmssw/issues/43775#issuecomment-1906439896, technically no-op (for reasons explained at https://github.com/cms-sw/cmssw/issues/43775#issuecomment-1906374470).

#### PR validation:

`cmssw` compiles.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

N/A

### CODE REVIEW

**Comment by mmusich** [comment]
please test for CMSSW_14_0_CPP20_X

**Comment by smuzaffar** [comment]
please test

warnings are gine for CPP20 builds  (https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-53b0ac/37055/build-logs/Alignment/OfflineValidation/log.html)

**Comment by perrotta** [comment]
+1

**Comment by rappoccio** [comment]
+1

* This seems unrelated but will discuss at ORP in case there are issues.

**Pull request merged**
