### PR TITLE
Run3-alca247C Modify CalibFitPlots to provide multiple depth plots to individual plots with single depths

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Modify CalibFitPlots to provide multiple depth plots to individual plots with single depths

#### PR validation:

Used in providing studies of IsoTrack corrections with Run3 data

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:
 
Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by perrotta** [comment]
+alca

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by perrotta** [comment]
+alca

**Comment by rappoccio** [comment]
+1

**Pull request merged**
