### PR TITLE
Backport of lhe xml blob memory improvements to 53x

### PR DESCRIPTION
**Pull request by bendavid**

### CODE REVIEW

**Comment by franzoni** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by bendavid** [comment]
@Dr15Jones can you look at the related hypernews thread
https://hypernews.cern.ch/HyperNews/CMS/get/edmFramework/3464.html
and comment whether it makes sense that I had to explicitly add the vector instances in this pull request, but not in 71x or 75x?

**Comment by bendavid** [comment]
+1

**Comment by franzoni** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
