### PR TITLE
Add AlCaReco producers in phase-2 workflows [12.5.X]

### PR DESCRIPTION
**Pull request by mmusich**
backport of https://github.com/cms-sw/cmssw/pull/39858 and https://github.com/cms-sw/cmssw/pull/39917

#### PR description:

The goal of this PR is to start exercising Tracker alcareco producers in the phase-2 workflows, as there is interest in trying a preliminary alignment with the phase-2 geometry.
A minimal set of changes if proposed in order to achieve that goal, including the necessary update of the `phase2_realistic` autoCond key in order to get most updated trigger bits from the run-3 global tag (see also [cmsTalk](https://cms-talk.web.cern.ch/t/outdated-alcarecotriggerbitsrcd-payload-in-the-phase-2-simulation-global-tag/16749)):
   * Global Tag difference: https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/125X_mcRun4_realistic_v2/125X_mcRun4_realistic_v3

In addition the pseudo-rapidity range of the alignment alcarecos is modified in the case of the phase-2 tracker to allow full coverage (up to |η|<4).

#### PR validation:

Run successfully `runTheMatrix.py -l 20834.0 -t 4 -j 8`

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

backport of https://github.com/cms-sw/cmssw/pull/39858 and https://github.com/cms-sw/cmssw/pull/39917 (excepted changes in [upgradeWorkflowComponents.py](https://github.com/cms-sw/cmssw/pull/39858/files#diff-8c163203cbaa64f0e0e6aa2b16346cfab3eaf84a57a008c7fa37193e8b9b2adb) concerning D95 and D96 that dont't exist in this cycle). 
Needed to run the ALCARECO skimming on top the phase-2 samples production from L1T group ([Phase2Fall22DRMiniAOD](https://cms-pdmv.cern.ch/mcm/campaigns?prepid=Phase2Fall22DRMiniAOD))

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
please test

**Comment by francescobrivio** [comment]
+alca

 - I see some differences (not present in the master PR) in 11634.7 which is not Phase-II and does not run any ALCA sequence (as far as i can see), so the PR is ok from the `alca` point of view

**Comment by francescobrivio** [comment]
> +alca
> 
>     * I see some differences (not present in the master PR) in 11634.7 which is not Phase-II and does not run any ALCA sequence (as far as i can see), so the PR is ok from the `alca` point of view

I just realized this is a know issue: https://github.com/cms-sw/cmssw/issues/39803

**Comment by srimanob** [comment]
+Upgrade

This PR will allow us to run ALCAReco step with L1T campaign. It does not touch the main RECO sequence, so it should be to be backported.

**Comment by mandrenguyen** [comment]
backport of #39858
checking if the backport label wasn't triggered b/c two PRs were specified

**Comment by mandrenguyen** [comment]
+reconstruction

**Comment by sunilUIET** [comment]
+pdmv

**Comment by rappoccio** [comment]
+1

* Near verbatim backport, needed for phase 2 MC production

**Pull request merged**
