### PR TITLE
Update tracking ntuple

### PR DESCRIPTION
**Pull request by makortel**
This PR provides the following updates to `TrackingNtuple`
- add link from seeds to tracks
- add link from vertex to tracks (for tracks used in the vertex fit)
- add track invalid hits
- add all SimHits
  - add TrackingParticle <-> SimHit links
  - add SimHit <-> RecHit links
  - remove TrackingParticle <-> RecHit links
  - Notes
    - SimHits with `particleType()` electron from non-electron TrackingParticles are filtered out (delta rays, to make the interpretation of sim information a bit easier)
    - SimHits for pileup events require running `MixingModule` in "playback mode" to access SimHits from pileup events
- new branches for tracks
  - track parameters
  - track reference point
- new branches for TrackingParticles
  - parameters at PCA as in MTV
- add subdetector part of DetId also to pixel hits
- add a flag whether a pixel/strip hit is from signal/in-time pileup/out-of-time pileup/noise

In addition, code for analysis of fake tracks (by Jyri Maanpää, summer student) is added as an additional example.

Tested in 8_1_0_pre12, expecting no effect on standard workflows.

@rovere @VinInn

### CODE REVIEW

**Comment by VinInn** [comment]
@cmsbuild, please test

**Comment by VinInn** [comment]
Hi @makortel , could you please verify if all quantities needed in current MVA
http://cmslxr.fnal.gov/source/RecoTracker/FinalTrackSelectors/plugins/DefaultTrackMVAClassifier.cc
are in the tuple?

**Comment by makortel** [comment]
@VinInn They are not, but adding them is in the todo list. But I'd leave them to a subsequent PR (as this one already includes structural changes) given that our plan is to do the first retraining with the old ntuple (and move to this one later).

**Comment by makortel** [comment]
ping

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
