### PR TITLE
Fix invalid PF jet collection for L1T offline jets and sums DQM

### PR DESCRIPTION
**Pull request by thomreis**
This PR fixes the empty efficiency and resolution plots for L1T jets and ET sums in the offline DQM.
The plots were empty since the move to the 10_2 release.

### CODE REVIEW

**Comment by thomreis** [comment]
please test

**Comment by thomreis** [comment]
+1

**Comment by andrius-k** [comment]
+1

**Comment by thomreis** [comment]
type bugfix

**Comment by thomreis** [comment]
urgent
Marking this as urgent since it prevents L1T certification of jets and sums using the offline DQM.

**Comment by thomreis** [comment]
please test

**Comment by thomreis** [comment]
+1

**Comment by andrius-k** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Pull request merged**
