### PR TITLE
Fixed bug in tracking sequence

### PR DESCRIPTION
**Pull request by dinardo**
I've fixed a bug in the tracking sequence, I've simply added the lines
`process.load("RecoVertex.BeamSpotProducer.BeamSpot_cfi)`
and then
`process.offlineBeamSpot*`
in the sequence.

### CODE REVIEW

**Comment by dinardo** [comment]
Dear Experts,
I was wondering whether this PR can move forward.
Cheers,
- Mauro.

**Comment by dmitrijus** [comment]
+1

**Comment by dinardo** [comment]
Hi,
I'm not sure I can pin point the error source.
Can you please tell me whether the error is due to my appplication not ?
Many thanks,
- Mauro.

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by davidlange6** [comment]
+1

**Pull request merged**
