### PR TITLE
Speedup fullJacobian

### PR DESCRIPTION
**Pull request by VinInn**
Workaround some compiler (gcc) inefficiency
(see https://gcc.gnu.org/bugzilla/show_bug.cgi?id=114943  and https://godbolt.org/z/fMqEbTfe6 )
and improve some code to make it vectorize.
This makes the the ExtVec version even faster than the SSE one.

Purely technical, no regression expected.

### CODE REVIEW

**Comment by VinInn** [comment]
@cmsbuild , please test

**Comment by mandrenguyen** [comment]
+1

**Comment by civanch** [comment]
@VinInn , why we have some number of differences in old WFs? Results are not identical, is it due to the last bits or any double/float conversion?

**Comment by VinInn** [comment]
@civanch It could be that the order of some operation is changed

**Comment by civanch** [comment]
+1

**Comment by mmusich** [comment]
type performance-improvements

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
