### PR TITLE
VarParsing: prevent TypeError for default of int/float/bool list

### PR DESCRIPTION
**Pull request by IzaakWN**
## PR description:

This PR patches the handling of defaults in `FWCore.ParameterSet.VarParsing` to prevent a `TypeError` for the case of an int/float/bool type in combination with `VarParsing.multiplicity.list`, where the default is a single int/float/bool value. This bug was described in https://github.com/cms-sw/cmssw/issues/44630:

Note:
* In order to prevent interfering with any workflows that might rely on the behavior of "list of list" defaults, this PR only prevents the `TypeError` with an if statement:
https://github.com/IzaakWN/cmssw/blob/dbd4367723a9bcc29fcf308f2902896c2aabbc6e/FWCore/ParameterSet/python/VarParsing.py#L413-L418
* This means that if a user wants to use as default a list of multiple int/float/bool values, they will still get a list of lists of those values, same as for strings... E.g., `[0,1]` → `[[0,1]]`.

```python
opts = VarParsing('standard')

opts.register('myInts0`,  0,  VarParsing.multiplicity.list, VarParsing.varType.int) 
# before this PR: causes TypeError because len(int)
# after this PR: yields list of (single) integer [0] as default

opts.register('myInts1`, [0],  VarParsing.multiplicity.list, VarParsing.varType.int)
# works because len(list)
# yields list of list [[0]] as default

opts.register('myInts2', [0,1],  VarParsing.multiplicity.list, VarParsing.varType.int)
# works because len(list)
# yields list of list [[0,1]] as default
```

Tagging: @makortel

## PR validation:

I setup CMSSW as follows:
```bash
source $VO_CMS_SW_DIR/cmsset_default.sh
export SCRAM_ARCH="el9_amd64_gcc12"
CMSSW="CMSSW_14_1_0_pre6"
cmsrel $CMSSW -n ${CMSSW}_varpars
cd ${CMSSW}_varpars/src && cmsenv
git cms-addpkg FWCore/ParameterSet
```

To test the behavior, I used this reproducible snippet in the `python3` command line:
```python
import sys
from FWCore.ParameterSet.VarParsing import VarParsing

def parse(argv):
  print(f">>> Parsing {argv!r}...")
  sys.argv = ['test.py','maxEvents=100']+argv
  opts = VarParsing('standard')
  print(">>> Register...")
  def add(*args,**kwargs):
    try:
      print(f">>>   {args!r}, {kwargs!r}...")
      opts.register(*args,**kwargs)
    except Exception as err:
      print(f">>>   => {err!r}")
  add('myInts0',  '',      VarParsing.multiplicity.list, VarParsing.varType.int) # works because len(str)
  add('myInts1',  0,       VarParsing.multiplicity.list, VarParsing.varType.int) # ERROR because len(int)
  add('myInts2',  [0],     VarParsing.multiplicity.list, VarParsing.varType.int) # works because len(list)
  add('myBools0', '',      VarParsing.multiplicity.list, VarParsing.varType.bool) # works because len(str)
  add('myBools1', True,    VarParsing.multiplicity.list, VarParsing.varType.bool) # ERROR because len(bool)
  add('myBools2', [True],  VarParsing.multiplicity.list, VarParsing.varType.bool) # works because len(list)
  add('myStrs0',  '',      VarParsing.multiplicity.list, VarParsing.varType.string) # works because len(str)
  add('myStrs1',  'foo',   VarParsing.multiplicity.list, VarParsing.varType.string) # works because len(str)
  add('myStrs2',  ['foo'], VarParsing.multiplicity.list, VarParsing.varType.string) # works because len(list)
  opts.parseArguments()
  print(f">>> Parsed:")
  for var in opts._lists:
    if var.startswith('my'):
      print(f">>>   {var:6s} = {getattr(opts,var)!r}")

parse([ ])
parse(['myInts1=0,1','myBools1=True,False','myStrs1=foo,bar','myStrs2=foo,bar'])
```

Before the changes, there are `TypeErrors`:
```python
>>> parse([ ])
>>> Parsing []...
>>> Register...
>>>   ('myInts0', '', 'multiplicity_list', '_int'), {}...
>>>   ('myInts1', 0, 'multiplicity_list', '_int'), {}...
>>>   => TypeError("object of type 'int' has no len()")
>>>   ('myInts2', [0], 'multiplicity_list', '_int'), {}...
>>>   ('myBools0', '', 'multiplicity_list', '_bool'), {}...
>>>   ('myBools1', True, 'multiplicity_list', '_bool'), {}...
>>>   => TypeError("object of type 'bool' has no len()")
>>>   ('myBools2', [True], 'multiplicity_list', '_bool'), {}...
>>>   ('myStrs0', '', 'multiplicity_list', '_string'), {}...
>>>   ('myStrs1', 'foo', 'multiplicity_list', '_string'), {}...
>>>   ('myStrs2', ['foo'], 'multiplicity_list', '_string'), {}...
>>> Parsed:
>>>   myInts0 = []
>>>   myInts1 = []
>>>   myInts2 = [[0]]
>>>   myBools0 = []
>>>   myBools1 = []
>>>   myBools2 = [[True]]
>>>   myStrs0 = []
>>>   myStrs1 = ['foo']
>>>   myStrs2 = [['foo']]
>>> parse(['myInts1=0,1','myBools1=True,False','myStrs1=foo,bar','myStrs2=foo,bar'])
>>> Parsing ['myInts1=0,1', 'myBools1=True,False', 'myStrs1=foo,bar', 'myStrs2=foo,bar']...
>>> Register...
>>>   ('myInts0', '', 'multiplicity_list', '_int'), {}...
>>>   ('myInts1', 0, 'multiplicity_list', '_int'), {}...
>>>   => TypeError("object of type 'int' has no len()")
>>>   ('myInts2', [0], 'multiplicity_list', '_int'), {}...
>>>   ('myBools0', '', 'multiplicity_list', '_bool'), {}...
>>>   ('myBools1', True, 'multiplicity_list', '_bool'), {}...
>>>   => TypeError("object of type 'bool' has no len()")
>>>   ('myBools2', [True], 'multiplicity_list', '_bool'), {}...
>>>   ('myStrs0', '', 'multiplicity_list', '_string'), {}...
>>>   ('myStrs1', 'foo', 'multiplicity_list', '_string'), {}...
>>>   ('myStrs2', ['foo'], 'multiplicity_list', '_string'), {}...
>>> Parsed:
>>>   myInts0 = []
>>>   myInts1 = [0, 1]
>>>   myInts2 = [[0]]
>>>   myBools0 = []
>>>   myBools1 = [True, False]
>>>   myBools2 = [[True]]
>>>   myStrs0 = []
>>>   myStrs1 = ['foo', 'bar']
>>>   myStrs2 = ['foo', 'bar']
```

After the changes, the `TypeErrors` are gone, and the single defaults are stored as a list of int/float/bool:
```python
>>> parse([ ])
>>> Parsing []...
>>> Register...
>>>   ('myInts0', '', 'multiplicity_list', '_int'), {}...
>>>   ('myInts1', 0, 'multiplicity_list', '_int'), {}...
>>>   ('myInts2', [0], 'multiplicity_list', '_int'), {}...
>>>   ('myBools0', '', 'multiplicity_list', '_bool'), {}...
>>>   ('myBools1', True, 'multiplicity_list', '_bool'), {}...
>>>   ('myBools2', [True], 'multiplicity_list', '_bool'), {}...
>>>   ('myStrs0', '', 'multiplicity_list', '_string'), {}...
>>>   ('myStrs1', 'foo', 'multiplicity_list', '_string'), {}...
>>>   ('myStrs2', ['foo'], 'multiplicity_list', '_string'), {}...
>>> Parsed:
>>>   myInts0 = []
>>>   myInts1 = [0]
>>>   myInts2 = [[0]]
>>>   myBools0 = []
>>>   myBools1 = [True]
>>>   myBools2 = [[True]]
>>>   myStrs0 = []
>>>   myStrs1 = ['foo']
>>>   myStrs2 = [['foo']]
>>> parse(['myInts1=0,1','myBools1=True,False','myStrs1=foo,bar','myStrs2=foo,bar'])
>>> Parsing ['myInts1=0,1', 'myBools1=True,False', 'myStrs1=foo,bar', 'myStrs2=foo,bar']...
>>> Register...
>>>   ('myInts0', '', 'multiplicity_list', '_int'), {}...
>>>   ('myInts1', 0, 'multiplicity_list', '_int'), {}...
>>>   ('myInts2', [0], 'multiplicity_list', '_int'), {}...
>>>   ('myBools0', '', 'multiplicity_list', '_bool'), {}...
>>>   ('myBools1', True, 'multiplicity_list', '_bool'), {}...
>>>   ('myBools2', [True], 'multiplicity_list', '_bool'), {}...
>>>   ('myStrs0', '', 'multiplicity_list', '_string'), {}...
>>>   ('myStrs1', 'foo', 'multiplicity_list', '_string'), {}...
>>>   ('myStrs2', ['foo'], 'multiplicity_list', '_string'), {}...
>>> Parsed:
>>>   myInts0 = []
>>>   myInts1 = [0, 1]
>>>   myInts2 = [[0]]
>>>   myBools0 = []
>>>   myBools1 = [True, False]
>>>   myBools2 = [[True]]
>>>   myStrs0 = []
>>>   myStrs1 = ['foo', 'bar']
>>>   myStrs2 = ['foo', 'bar']
```

## PR tests

Following https://cms-sw.github.io/PRWorkflow.html, I did:
```
scram b distclean 
git cms-checkdeps -a -A # adds 17 other packages..
scram b -j 8
scram b runtests
```
As `VarParsing` is used by many python configuration scripts, `git cms-checkdeps -a -A ` will add 17 additional packages. Not all test are successful, but I checked the same tests fail in a CMSSW project without any changes. As far as I can tell the failures do not come from my side. I assume no workflow contains an exception for the `TypeError` above.

### CODE REVIEW

**Comment by makortel** [comment]
Thanks @IzaakWN! Would you be able to add your test snippet as a unit test? E.g. something along
* Place the code in e.g. `FWCore/ParameterSet/test/test_varparsing_list.py`
* Add `<test name="TestFWCoreParameterSetVarParsingList" command="python3 ${LOCALTOP}/src/FWCore/ParameterSet/test/test_varparsing_list.py"/>`

should do the job. You can run the test locally with `scram b runtests_TestFWCoreParameterSetVarParsingList`.

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by IzaakWN** [comment]
Looks like the failed jobs comes from the case where the default list for ints is an empty list:
https://github.com/cms-sw/cmssw/blob/e0cb38ff7b31f3981865b10c7f707b7ef5af9048/CondTools/SiStrip/test/SiStripBadChannelPatcher_cfg.py#L20-L42

which passes the new first term in the condition, but not the old second one...
https://github.com/cms-sw/cmssw/blob/5089cc19ff62fa05a5b76e871dcb438933d47f09/FWCore/ParameterSet/python/VarParsing.py#L416-L418

I can change the condition to ignore empty lists? Something like
```python
            if (mytype in [VarParsing.varType.bool, VarParsing.varType.int, VarParsing.varType.float] and \
               default not in ["", []]) or len (default): # check type to prevent TypeError for bool/int/float defaults
                self._lists[name].append (default) # known bug: default can be list
```

**Comment by IzaakWN** [comment]
Commit https://github.com/cms-sw/cmssw/pull/45640/commits/db50eede364f8cbc223cd1823f9e383c94b6afcd handles the case where the user's default is an empty list as in the job failure above:
https://github.com/cms-sw/cmssw/blob/db50eede364f8cbc223cd1823f9e383c94b6afcd/FWCore/ParameterSet/python/VarParsing.py#L416-L418

However, a more general solution to prevent the TypeError in `len (default)`, while keeping the old behavior, might be something like the following?
```python
if (mytype in [VarParsing.varType.bool, VarParsing.varType.int, VarParsing.varType.float] and \
   not hasattr(default,'__len__')) or len (default): # check type to prevent TypeError for bool/int/float defaults
    self._lists[name].append (default) # known bug: default can be list
```
where any default for int/float/bool lists that has the `__len__` method (like strings and lists) will be evaluated by the `len (default)` condition, as before this PR. Let me know if you prefer this solution.

Validating the last commit with empty list defaults:
```python
import sys
from FWCore.ParameterSet.VarParsing import VarParsing

def parse(argv):
  sys.argv = ['test_varparsing_list.py','maxEvents=100']+argv # emulate user arguments
  opts = VarParsing('standard')
  print(">>> Registering...")
  def add(n, d, m, t):
    sargs = (repr(n)+',').ljust(13)+(repr(d)+',').ljust(9) +\
            f"VarParsing.multiplicity.{m.split('_')[-1]}, " +\
            f"VarParsing.multiplicity.{t.split('_')[-1]}".ljust(30)
    print(f">>>   opts.register({sargs})")
    try:
      opts.register(n, d, m, t)
    except Exception as err:
      print(f">>>   => {err!r}")
  add('myInts0',   '',      VarParsing.multiplicity.list, VarParsing.varType.int)
  add('myInts1',   [],      VarParsing.multiplicity.list, VarParsing.varType.int)
  add('myInts2',   0,       VarParsing.multiplicity.list, VarParsing.varType.int)
  add('myInts3',   [0],     VarParsing.multiplicity.list, VarParsing.varType.int)
  add('myFloats0', '',      VarParsing.multiplicity.list, VarParsing.varType.float)
  add('myFloats1', [],      VarParsing.multiplicity.list, VarParsing.varType.float)
  add('myFloats2', 0,       VarParsing.multiplicity.list, VarParsing.varType.float)
  add('myFloats3', [0],     VarParsing.multiplicity.list, VarParsing.varType.float)
  add('myBools0',  '',      VarParsing.multiplicity.list, VarParsing.varType.bool)
  add('myBools1',  [],      VarParsing.multiplicity.list, VarParsing.varType.bool)
  add('myBools2',  True,    VarParsing.multiplicity.list, VarParsing.varType.bool)
  add('myBools3',  [True],  VarParsing.multiplicity.list, VarParsing.varType.bool)
  add('myStrs0',   '',      VarParsing.multiplicity.list, VarParsing.varType.string)
  add('myStrs1',   [],      VarParsing.multiplicity.list, VarParsing.varType.string)
  add('myStrs2',   'foo',   VarParsing.multiplicity.list, VarParsing.varType.string)
  add('myStrs3',   ['foo'], VarParsing.multiplicity.list, VarParsing.varType.string)
  print(f">>> Parsing user arguments...")
  print(f">>>   sys.argv={sys.argv!r}")
  opts.parseArguments()
  print(f">>> Parsed:")
  for var in opts._lists:
    if var.startswith('my'):
      print(f">>>   opts.{var:<9s} = {getattr(opts,var)!r}")

# parse without user arguments
parse([ ])

# parse with user arguments
print(">>>")
parse(['myInts1=0,1,-1','myFloats1=3.14,0,0.0,-1.0','myBools1=True,False','myStrs1=foo,bar'])
```
yields:
```python
>>> # parse without user arguments
>>> parse([ ])
>>> Registering...
>>>   opts.register('myInts0',   '',      VarParsing.multiplicity.list, VarParsing.multiplicity.int   )
>>>   opts.register('myInts1',   [],      VarParsing.multiplicity.list, VarParsing.multiplicity.int   )
>>>   opts.register('myInts2',   0,       VarParsing.multiplicity.list, VarParsing.multiplicity.int   )
>>>   opts.register('myInts3',   [0],     VarParsing.multiplicity.list, VarParsing.multiplicity.int   )
>>>   opts.register('myFloats0', '',      VarParsing.multiplicity.list, VarParsing.multiplicity.float )
>>>   opts.register('myFloats1', [],      VarParsing.multiplicity.list, VarParsing.multiplicity.float )
>>>   opts.register('myFloats2', 0,       VarParsing.multiplicity.list, VarParsing.multiplicity.float )
>>>   opts.register('myFloats3', [0],     VarParsing.multiplicity.list, VarParsing.multiplicity.float )
>>>   opts.register('myBools0',  '',      VarParsing.multiplicity.list, VarParsing.multiplicity.bool  )
>>>   opts.register('myBools1',  [],      VarParsing.multiplicity.list, VarParsing.multiplicity.bool  )
>>>   opts.register('myBools2',  True,    VarParsing.multiplicity.list, VarParsing.multiplicity.bool  )
>>>   opts.register('myBools3',  [True],  VarParsing.multiplicity.list, VarParsing.multiplicity.bool  )
>>>   opts.register('myStrs0',   '',      VarParsing.multiplicity.list, VarParsing.multiplicity.string)
>>>   opts.register('myStrs1',   [],      VarParsing.multiplicity.list, VarParsing.multiplicity.string)
>>>   opts.register('myStrs2',   'foo',   VarParsing.multiplicity.list, VarParsing.multiplicity.string)
>>>   opts.register('myStrs3',   ['foo'], VarParsing.multiplicity.list, VarParsing.multiplicity.string)
>>> Parsing user arguments...
>>>   sys.argv=['test_varparsing_list.py', 'maxEvents=100']
>>> Parsed:
>>>   opts.myInts0   = []
>>>   opts.myInts1   = []
>>>   opts.myInts2   = [0]
>>>   opts.myInts3   = [[0]]
>>>   opts.myFloats0 = []
>>>   opts.myFloats1 = []
>>>   opts.myFloats2 = [0]
>>>   opts.myFloats3 = [[0]]
>>>   opts.myBools0  = []
>>>   opts.myBools1  = []
>>>   opts.myBools2  = [True]
>>>   opts.myBools3  = [[True]]
>>>   opts.myStrs0   = []
>>>   opts.myStrs1   = []
>>>   opts.myStrs2   = ['foo']
>>>   opts.myStrs3   = [['foo']]
>>> 
>>> # parse with user arguments
>>> print(">>>")
>>>
>>> parse(['myInts1=0,1,-1','myFloats1=3.14,0,0.0,-1.0','myBools1=True,False','myStrs1=foo,bar'])
>>> Registering...
>>>   opts.register('myInts0',   '',      VarParsing.multiplicity.list, VarParsing.multiplicity.int   )
>>>   opts.register('myInts1',   [],      VarParsing.multiplicity.list, VarParsing.multiplicity.int   )
>>>   opts.register('myInts2',   0,       VarParsing.multiplicity.list, VarParsing.multiplicity.int   )
>>>   opts.register('myInts3',   [0],     VarParsing.multiplicity.list, VarParsing.multiplicity.int   )
>>>   opts.register('myFloats0', '',      VarParsing.multiplicity.list, VarParsing.multiplicity.float )
>>>   opts.register('myFloats1', [],      VarParsing.multiplicity.list, VarParsing.multiplicity.float )
>>>   opts.register('myFloats2', 0,       VarParsing.multiplicity.list, VarParsing.multiplicity.float )
>>>   opts.register('myFloats3', [0],     VarParsing.multiplicity.list, VarParsing.multiplicity.float )
>>>   opts.register('myBools0',  '',      VarParsing.multiplicity.list, VarParsing.multiplicity.bool  )
>>>   opts.register('myBools1',  [],      VarParsing.multiplicity.list, VarParsing.multiplicity.bool  )
>>>   opts.register('myBools2',  True,    VarParsing.multiplicity.list, VarParsing.multiplicity.bool  )
>>>   opts.register('myBools3',  [True],  VarParsing.multiplicity.list, VarParsing.multiplicity.bool  )
>>>   opts.register('myStrs0',   '',      VarParsing.multiplicity.list, VarParsing.multiplicity.string)
>>>   opts.register('myStrs1',   [],      VarParsing.multiplicity.list, VarParsing.multiplicity.string)
>>>   opts.register('myStrs2',   'foo',   VarParsing.multiplicity.list, VarParsing.multiplicity.string)
>>>   opts.register('myStrs3',   ['foo'], VarParsing.multiplicity.list, VarParsing.multiplicity.string)
>>> Parsing user arguments...
>>>   sys.argv=['test_varparsing_list.py', 'maxEvents=100', 'myInts1=0,1,-1', 'myFloats1=3.14,0,0.0,-1.0', 'myBools1=True,False', 'myStrs1=foo,bar']
>>> Parsed:
>>>   opts.myInts0   = []
>>>   opts.myInts1   = [0, 1, -1]
>>>   opts.myInts2   = [0]
>>>   opts.myInts3   = [[0]]
>>>   opts.myFloats0 = []
>>>   opts.myFloats1 = [3.14, 0.0, 0.0, -1.0]
>>>   opts.myFloats2 = [0]
>>>   opts.myFloats3 = [[0]]
>>>   opts.myBools0  = []
>>>   opts.myBools1  = [True, False]
>>>   opts.myBools2  = [True]
>>>   opts.myBools3  = [[True]]
>>>   opts.myStrs0   = []
>>>   opts.myStrs1   = ['foo', 'bar']
>>>   opts.myStrs2   = ['foo']
>>>   opts.myStrs3   = [['foo']]
```

**Comment by makortel** [comment]
Hmh. Taking a look of all uses of `multiplicity.list` in CMSSW, I came across
https://github.com/cms-sw/cmssw/blob/ff2f0758f6044c493442941b5c96bb7787cc65f4/EventFilter/GEMRawToDigi/test/runGEMUnpacker_cfg.py#L67-L69
that is used in a way that expects `options.feds` to be a list, rather than list of lists.

Then there is
https://github.com/cms-sw/cmssw/blob/ff2f0758f6044c493442941b5c96bb7787cc65f4/CondTools/L1Trigger/test/L1ConfigWriteSinglePayload_cfg.py#L84-L86
https://github.com/cms-sw/cmssw/blob/ff2f0758f6044c493442941b5c96bb7787cc65f4/CondTools/L1Trigger/test/L1ConfigWriteSinglePayload_cfg.py#L89-L91
where the behavior of the default being `[[-999]]` is relied on (but would be easy to change, the use of non-default expects a list in any case).

Then there is
https://github.com/cms-sw/cmssw/blob/ff2f0758f6044c493442941b5c96bb7787cc65f4/CalibTracker/SiStripCommon/test/testProduceCalibrationTree_cfg.py#L44-L46
that uses a `cms.vstring()` (!) as the default value, leading to a list of `vstring` (of one element), and I'd expect its use later in the configuration to fail.

Otherwise the defaults were either strings (empty or non-empty), or empty lists.

----

I find it unfortunate the singular default was allowed at the time (and is used for strings). But, given where we are, I continue to be ok with adding the singular defaults for int/float/bool. But I'm now leaning towards fixing the use case 1 you mentioned in https://github.com/cms-sw/cmssw/issues/44630, even if it might break some user code (the `L1ConfigWriteSinglePayload_cfg.py` in CMSSW itself can and should be fixed).

@IzaakWN Would you be willing to update this PR along this way?

**Comment by antoniovilela** [comment]
ping (to make bot change milestone)

**Comment by makortel** [comment]
> to be honest I prefer not to make any changes that will break an unkown large number of scripts, and unit tests that I don't want to be responsible for breaking or fixing. Like you point out, many users implemented workarounds that rely on this behavior, even if it's inconsistent between default and command line (use case (1) in #44630).

Fair enough. Then the cases that do not work with the "list of lists" I listed in https://github.com/cms-sw/cmssw/pull/45640#issuecomment-2278663797 should, in principle, be fixed, but I'll open separate issues for them.

> I propose to merge this PR with the current fix that only prevents a `TypeError`:

At this stage let's proceed with minimal effort and continue with this PR as it is. I'll launch last round of tests.

**Comment by makortel** [comment]
test parameters:
  - full_cmssw = true

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
> Then there is
> 
> https://github.com/cms-sw/cmssw/blob/ff2f0758f6044c493442941b5c96bb7787cc65f4/CalibTracker/SiStripCommon/test/testProduceCalibrationTree_cfg.py#L44-L46
> 
> 
> that uses a `cms.vstring()` (!) as the default value, leading to a list of `vstring` (of one element), and I'd expect its use later in the configuration to fail.

Playing around it seems I was wrong, this case appears to work (at least with some definition of "work").

**Comment by makortel** [comment]
Comparison differences are related to https://github.com/cms-sw/cmssw/issues/39803 and https://github.com/cms-sw/cmssw/issues/43415

**Comment by makortel** [comment]
This PR looks ok then. I'll leave signing it to early next week though in order to be around in case something would go bad in IBs (even if the tests here should have included all packages that depend on `VarParsing`).

**Comment by makortel** [comment]
+core

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
