### PR TITLE
Make one test wf for scenario D24 visible for PR/IB tests

### PR DESCRIPTION
**Pull request by fabiocos**
Addition of a Phase2 D24 scenario test (new MTD fullsim implementation) for tests of PRs and in IB

### CODE REVIEW

**Comment by fabiocos** [comment]
please test workflow 22434.0

**Comment by kpedro88** [comment]
+1

**Comment by fabiocos** [comment]
@fabozzi @prebello any objection to this addition?

**Comment by fabozzi** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
