### PR TITLE
use ofast-flag tool instead of directly CXXFLAGS=-Ofast

### PR DESCRIPTION
**Pull request by smuzaffar**
-Ofast flag with clang on slc6 failed to compile due to missing `__[exp|log|pow]_finite` symbols (  https://github.com/cms-sw/cmssw/issues/24935 ) . This PR now make use of new tool ofast-flag which adds `--no-builtin` flag for  llvm/slc6  ( https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_10_4_X/gcc700/gcc-toolfile.spec#L132 ).

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by slava77** [comment]
@smuzaffar 
please clarify why about a half of all ```-Ofast``` use cases is left unchanged.
Were they not necessary to be updated or is there another PR coming?

Here is the list (with "OK" note for what's updated in this PR already) based on git grep in CMSSW_10_4_X_2018-10-24-2300

```
OK DataFormats/Math/test/BuildFile.xml:  <flags CXXFLAGS="-Ofast"/>
OK DataFormats/Math/test/BuildFile.xml:<flags CXXFLAGS="-Ofast"/>
OK RecoEgamma/EgammaElectronAlgos/BuildFile.xml:<flags   CXXFLAGS="-Ofast"/>
OK RecoEgamma/EgammaPhotonAlgos/BuildFile.xml:<flags   CXXFLAGS="-Ofast"/>
RecoPixelVertexing/PixelTriplets/BuildFile.xml:<flags   CXXFLAGS="-Ofast -fno-math-errno"/>
RecoPixelVertexing/PixelTriplets/plugins/BuildFile.xml:<flags   CXXFLAGS="-Ofast -fno-math-errno"/>
RecoTracker/FinalTrackSelectors/BuildFile.xml:<flags   CXXFLAGS="-Ofast"/>
OK RecoTracker/FinalTrackSelectors/plugins/BuildFile.xml:<flags   CXXFLAGS="-Ofast"/>
RecoTracker/TkDetLayers/BuildFile.xml:<flags   CXXFLAGS="-Ofast"/>
RecoTracker/TkHitPairs/BuildFile.xml:<flags   CXXFLAGS="-Ofast"/>
OK RecoVertex/PrimaryVertexProducer/BuildFile.xml:<flags   CXXFLAGS="-Ofast"/>
OK TrackingTools/GsfTools/BuildFile.xml:<flags   CXXFLAGS="-Ofast"/>
TrackingTools/GsfTools/plugins/BuildFile.xml:<flags   CXXFLAGS="-Ofast"/>
TrackingTools/GsfTools/test/BuildFile.xml:<flags   CXXFLAGS="-Ofast"/>
OK TrackingTools/GsfTracking/BuildFile.xml:<flags   CXXFLAGS="-Ofast"/>
TrackingTools/KalmanUpdators/BuildFile.xml:<flags   CXXFLAGS="-Ofast -funroll-all-loops"/>
OK TrackingTools/MaterialEffects/BuildFile.xml:<flags   CXXFLAGS="-Ofast"/>
TrackingTools/MaterialEffects/plugins/BuildFile.xml:<flags   CXXFLAGS="-Ofast"/>
TrackingTools/TrackFitters/BuildFile.xml:<flags   CXXFLAGS="-Ofast -ffp-contract=off"/>
TrackingTools/TrajectoryState/BuildFile.xml:<flags   CXXFLAGS="-Ofast"/>

```

**Comment by smuzaffar** [comment]
The one I fixed were the one which are causing the undefined symbol errors for CLANG IBs. Looks like in the rest we are not calling log, exp or pow math functions that is why linker did not complain about those.

**Comment by slava77** [comment]
On 10/25/18 4:22 PM, Malik Shahzad Muzaffar wrote:
> The one I fixed were the one which are causing the undefined symbol
> errors for CLANG IBs. Looks like in the rest we are not calling log, exp
> or pow math functions that is why linker did not complain about those.
> 
> —

is it safe to update all use cases?

**Comment by smuzaffar** [comment]
Yes, it should be safe to update all. The new ofast-flag is only going to effect slc6/CLANG IBs. Let me know if you want all of these to be replaced in this PR or if you prefer to have a new one.

**Comment by perrotta** [comment]
@smuzaffar : if you fit all them in the same PR, review and approval of the whole set can go faster

**Comment by slava77** [comment]
On 10/25/18 5:03 PM, Malik Shahzad Muzaffar wrote:
> Yes, it should be safe to update all. The new ofast-flag is only going
> to effect slc6/CLANG IBs. Let me know if you want all of these to be
> replaced in this PR or if you prefer to have a new one.
> 
> —

they are all in reco category. So, an update here is probably simpler

**Comment by smuzaffar** [comment]
please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/24969	5c5a108
- technical; now covers all cases of using ```-Ofast```
- jenkins tests pass

**Comment by smuzaffar** [comment]
@fabiocos , can we merge this? this should fix CLANG IBs build errors.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
