### PR TITLE
HI workflows input dataset update

### PR DESCRIPTION
**Pull request by yetkinyilmaz**
The input dataset for mixing workflows changed to Hydjet at 5 TeV.

### CODE REVIEW

**Comment by yetkinyilmaz** [comment]
anybody know why tests are not triggered automatically?

**Comment by davidlange6** [comment]
they aren’t designed to be.

**Comment by davidlange6** [comment]
@cmsbuild, please test

**Comment by srimanob** [comment]
Add this PR together with fixing of FS dictionary
#10101

**Comment by srimanob** [comment]
+1

**Pull request merged**
