### PR TITLE
Run3-gex137 Change getByLabel to getByHandle in CalibMuon/DTCalibration

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Change getByLabel to getByHandle in CalibMuon/DTCalibration

#### PR validation:

Use the runTheMatrix test workflows

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by tvami** [comment]
@cmsbuild , please test

**Review by ChrisMisan — COMMENTED** [review]
All of the files contain a lot of dead code, please consider cleaning this up in the feature.

**Comment by tvami** [comment]
@bsunanda when you do the code checks, please squash the commits

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
type bug-fix

**Comment by ChrisMisan** [comment]
@bsunanda I have some more doubts found by static checks, which should be addressed outside of this PR:

- can you explain the use of try-catch mechanism in this file? It doesn't do any fail-recovery, it just ignores the issue and it does not follow the guidelines for exception handling.
https://github.com/cms-sw/cmssw/blob/db0be675cc3df05de73c903d594e859ac8ecbeba/CalibMuon/DTCalibration/interface/DTCalibDBUtils.h#L44
- memory leak, new-ed variable never free-ed, please consider using smart pointers
https://github.com/cms-sw/cmssw/blob/db0be675cc3df05de73c903d594e859ac8ecbeba/CalibMuon/DTCalibration/plugins/DTT0CalibrationRMS.cc#L289

**Comment by ChrisMisan** [comment]
+alca

- PR according to the description
- differences only in MTD and msgLogger
- recommendations outside of this PR's scope

**Comment by perrotta** [comment]
+1
. Please notice https://github.com/cms-sw/cmssw/pull/39172#issuecomment-1227106832, for a possible follow up PR

**Pull request merged**
