### PR TITLE
Updates on TrackerMaps scripts (backport of #25600)

### PR DESCRIPTION
**Pull request by arossi83**
This changes affects only scripts used by Tracker shifters. No changes on production code!

### CODE REVIEW

**Comment by andrius-k** [comment]
please test

**Comment by fabiocos** [comment]
@arossi83 sorry why this backport? At this point 10_4_X is for MTD production, I doubt this PR is relevant there, could you please clarify?

**Comment by arossi83** [comment]
@fabiocos As I already mentioned this PR affects only a tool used by shifters. It has no effect on any production workflows. I did the backport to 10_4_X just to keep tracks of the changes made to the scripts and because this changes has been used for HI certification. In any case you know much better than me what is better to do and for a future use of the scripts the PR #25600 if enough. Let me know and in case I will close this backport.

**Comment by fabiocos** [comment]
@arossi83 thank you for the clarification, given the very specific purpose of 10_4_X there is no reason to merge this backport to my mind, and the PR could be closed.

**Pull request closed without merging**
