### PR TITLE
expand tracker-driven coverage for electron seeds; jetCore mitigation

### PR DESCRIPTION
**Pull request by slava77**
Changes in this PR were motivated to mitigate the situation with tracks reconstructed multiple times, one of them jet core after introduction of mkFit to the non-jetCore iterations. Such tracks are more predominantly assigned to jetCore algorithm.

EGM/electron reco has some dependence on this:
- jetCore is not counted in PFEgammaAlgo as isGoodForEGMPrimary : to address this the same check is extended to track's `originalAlgo` to take into account also the other iteration that may have reconstructed the same track
- jetCore seeds are not included in the definition of ecalDrivenElectronSeeds and in the subsequent step where ecalDrivenElectronSeeds are merged with the trackerDrivenElectronSeeds (including jetCore) the check by seed hits alone is failing to assign a matching track to the ecal-driven seeds. To address this, the loop to match the hits is extended to include all of the track hits.

This was presented in TRK POG on Nov 1: https://indico.cern.ch/event/1092090/#3-interplay-in-high-pt-electro

Illustrations of the issue:
 in pre4 Z'->ee https://tinyurl.com/yfd22fxr  the track algorithm is more dominantly the jetCore (starts at 100 GeV)
image

the reconstructed electron provenance https://tinyurl.com/yg4rfp7c is showing a drop in the tracker-driven electrons { provenance: +1 ecal; -1 tracker; 0 either; +2 ecal-only; -2 tracker-only}
image

After this PR, on the same sample, only 100 events
default tracking with mkFit (red is new, black is pre4)
wfZpEEec070801a56_ele2all_provenance

even in the CKF tracking (reco with `Run3_noMkFit`) there is a noticeable increase in the tracker-driven categorization and decrease in the ecal-only
wfZpEEec070801a56-ckf_ele2all_provenance

### CODE REVIEW

**Comment by slava77** [comment]
I added updates for deepCore.
The tests will have to be started only after the next IB shows up (the last IB is broken), so that there is a proper reference for comparisons.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
In the PR tests for the previous commit https://github.com/cms-sw/cmssw/pull/35892#issuecomment-954706261 (which I expect to be repeated in the latest version) there were some changes in the PF CH vs ele assignments, e.g. in 136.793 DoubleEG2017C (100 events) there is one more electron vs 92 in the baseline (well, there is one more gedGsfElectron there as well; so it's not a pure reassignment inside PF).
So, the changes are not particularly alarming.

@cms-sw/pf-l2  @laurenhay @marksan87 
please clarify if you would like to make some standalone validation with a bit more focus on the less pure electrons like in jets before this PR is merged or if it's OK to merge and wait for the relvals.
Thank you.

**Comment by slava77** [comment]
a link to the TRK POG presentation(s) is added in the PR description 
https://indico.cern.ch/event/1092090/#3-interplay-in-high-pt-electro

**Comment by slava77** [comment]
+reconstruction

for https://github.com/cms-sw/cmssw/pull/35892	76ceb8e 
- code changes are in line with the PR description and the follow up review
- jenkins tests pass and comparisons with the baseline show small differences in egamma-related objects (there are not enough high-pt electrons in these samples to notice more than a few particle change)
- additional checks on signal were posted in the PR description and also presented in https://indico.cern.ch/event/1092090/#3-interplay-in-high-pt-electro and show a recovery in the ecal-and-tracker driven electrons
- standalone tests by PF experts show about 1% increase of electrons in the QCD sample (mostly fakes) and essentially no changes in the lower-pt signal (e.g. Z->EE) https://mattermost.web.cern.ch/cms-exp/pl/simkjfrh1png7y6cebini4e8rc The \~1% increase in fakes is considered acceptable.

**Comment by perrotta** [comment]
+1
- Small differences in egamma related objects look as expected
- About 1% increase of fake electrons in the QCD sample was considered acceptable
- Igprof comparisons do not show significant differences in performance

**Pull request merged**
