### PR TITLE
L1T CaloL2 O2O Fixes for HI

### PR DESCRIPTION
**Pull request by bundocka**
Fixes a number of bugs in the L1T CaloL2 O2O
Tested O2O code produces payload that matches HI static config caloParams v1_4

### CODE REVIEW

**Comment by rekovic** [comment]
please test

**Comment by thomreis** [comment]
please test

**Comment by fabiocos** [comment]
@bundocka it looks like there is a problem with this PR, running 136.85 I see in step2:

#0  0x00000035236accbd in nanosleep () from /lib64/libc.so.6
#1  0x00000035236acb30 in sleep () from /lib64/libc.so.6
#2  0x00007f19b2c2c491 in sig_pause_for_stacktrace () from /cvmfs/cms-ib.cern.ch/nweek-02548/slc6_amd64_gcc700/cms/cmssw/CMSSW_10_4_X_2018-10-28-1100/lib/slc6_amd64_gcc700/pluginFWCoreServicesPlugins.so
#3  <signal handler called>
#4  0x0000003523a0c97c in pthread_kill () from /lib64/libpthread.so.0
#5  0x00007f19b2c2e238 in sig_dostack_then_abort () from /cvmfs/cms-ib.cern.ch/nweek-02548/slc6_amd64_gcc700/cms/cmssw/CMSSW_10_4_X_2018-10-28-1100/lib/slc6_amd64_gcc700/pluginFWCoreServicesPlugins.so
#6  <signal handler called>
#7  0x00007f1984687eaa in l1t::Stage2Layer2JetAlgorithmFirmwareImp1::create(std::vector<l1t::CaloTower, std::allocator<l1t::CaloTower> > const&, std::vector<l1t::Jet, std::allocator<l1t::Jet> >&, std::vector<l1t::Jet, std::allocator<l1t::Jet> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) () from /build/fabiocos/104X/25012/CMSSW_10_4_X_2018-10-28-2300/lib/slc6_amd64_gcc700/libL1TriggerL1TCalorimeter.so
#8  0x00007f1984688468 in l1t::Stage2Layer2JetAlgorithmFirmwareImp1::processEvent(std::vector<l1t::CaloTower, std::allocator<l1t::CaloTower> > const&, std::vector<l1t::Jet, std::allocator<l1t::Jet> >&, std::vector<l1t::Jet, std::allocator<l1t::Jet> >&) () from /build/fabiocos/104X/25012/CMSSW_10_4_X_2018-10-28-2300/lib/slc6_amd64_gcc700/libL1TriggerL1TCalorimeter.so
#9  0x00007f198468b576 in l1t::Stage2MainProcessorFirmwareImp1::processEvent(std::vector<l1t::CaloTower, std::allocator<l1t::CaloTower> > const&, std::vector<l1t::CaloTower, std::allocator<l1t::CaloTower> >&, std::vector<l1t::CaloCluster, std::allocator<l1t::CaloCluster> >&, std::vector<l1t::EGamma, std::allocator<l1t::EGamma> >&, std::vector<l1t::Tau, std::allocator<l1t::Tau> >&, std::vector<l1t::Jet, std::allocator<l1t::Jet> >&, std::vector<l1t::EtSum, std::allocator<l1t::EtSum> >&, std::vector<l1t::EGamma, std::allocator<l1t::EGamma> >&, std::vector<l1t::Tau, std::allocator<l1t::Tau> >&, std::vector<l1t::Jet, std::allocator<l1t::Jet> >&, std::vector<l1t::EtSum, std::allocator<l1t::EtSum> >&) () from /build/fabiocos/104X/25012/CMSSW_10_4_X_2018-10-28-2300/lib/slc6_amd64_gcc700/libL1TriggerL1TCalorimeter.so
#10 0x00007f1983691d0a in L1TStage2Layer2Producer::produce(edm::Event&, edm::EventSetup const&) () from /build/fabiocos/104X/25012/CMSSW_10_4_X_2018-10-28-2300/lib/slc6_amd64_gcc700/pluginL1TriggerL1TCalorimeterPlugins.so

**Comment by bundocka** [comment]
Hi Fabio,
Ok I'll look this afternoon and hopefully provide a fix by the end of the day.

**Comment by fabiocos** [comment]
please test

**Comment by rekovic** [comment]
Hi @bundocka 
The failing job log is available [here](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-25012/31353/addOnTests/fastsim1/cmsDriver.py_TTbar_13TeV_TuneCUETP8M1_cfi_--conditions_auto:run2_mc_l1stage1_--fast__-n_100_--eventcontent_AODSIM,DQM_--relval_100000,1000_-s_GEN,SIM,.log).

**Comment by rekovic** [comment]
@bundocka 
You should be able to reproduce it is with the above command already reported
```
cmsDriver.py TTbar_13TeV_TuneCUETP8M1_cfi --conditions auto:run2_mc_l1stage1 --fast -n 100 --eventcontent AODSIM,DQM --relval 100000,1000 -s GEN,SIM,RECOBEFMIX,DIGI:pdigi_valid,L1,DIGI2RAW,L1Reco,RECO,EI,VALIDATION --customise=HLTrigger/Configuration/CustomConfigs.L1THLT --datatier GEN-SIM-DIGI-RECO,DQMIO --beamspot NominalCollision2015 --era Run2_25ns
```

**Comment by Martin-Grunewald** [comment]
Hi,

The failing addOntest is a FastSim test (fastsim1), unrelated to HLT, so not affected by it
```
Module: FastSimProducer:fastSimProducer (crashed)
Module: GsfTrackProducer:electronGsfTracks
Module: MuonAssociatorEDProducer:tpToTkMuonAssociation
Module: TrackMVAClassifierPrompt:initialStepClassifier1
```

**Comment by rekovic** [comment]
why doesn't this fail for 10_3_X PR https://github.com/cms-sw/cmssw/pull/25010 ?

**Comment by fabiocos** [comment]
@rekovic might be a transient failure? It would not be the first time, let's see whether it is reproducible

**Comment by rekovic** [comment]
+1

**Comment by fabiocos** [comment]
+1

DQM differences are concentrated in the L1T sector

**Pull request merged**
