### PR TITLE
Update L1T GT/Calo/GMT unpackers to have non-null product instances

### PR DESCRIPTION
**Pull request by mulhearn**
The unpacker code for L1T GT/Calo/GMT unpackers are updated to set the product instance to the object type.

This allows downstream HLT code to use edm::View in order to access the four-vectors of L1T objects.

The L1T downstream code required updates to adapt to this change, which has been completed, for all but some test code in L1Trigger/L1TGlobal which can be adapted separately.

### CODE REVIEW

**Comment by mulhearn** [comment]
I'm not signing this one until I better understand where it should go (i.e. into MWGR#3).

**Comment by mulhearn** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by mulhearn** [comment]
+1

**Pull request merged**
