### PR TITLE
Backport of PR #19404 (ootPhotons for legacy 80X reminiAOD)

### PR DESCRIPTION
**Pull request by kmcdermo**
backport of PR #19404 for 92X, as that PR was just moved to 93X (still not merged). no changes w.r.t. to 19404 (from the same branch)

### CODE REVIEW

**Comment by kpedro88** [comment]
-1
never merge, only rebase
http://cms-sw.github.io/tutorial-resolve-conflicts.html

**Comment by kmcdermo** [comment]
hmm. I did actually do a rebase for 19404... but maybe I cannot do it here
for the backport?

**Comment by kpedro88** [comment]
ah, I see - you have to make a new branch for the backport, because the master and 92X branches have now diverged.

**Comment by slava77** [comment]
it should have been a rebase -i or an equivalent staying the topic branch on a 92X commit common with the master

**Comment by slava77** [comment]
-1
needs a rebase or remake

**Comment by kmcdermo** [comment]
Okay, well given the pain of fixing this, I will just open another PR once 19404 is merged, and cherry pick the commits on top of 92X.

**Pull request closed without merging**
