### PR TITLE
Add UL PU scenario (backport of #27035)

### PR DESCRIPTION
**Pull request by fabiocos**
#### PR description:

Pileup scenario for 2018 UL reprocessing by @plujan 

#### PR validation:

trivial backport of code already successfully integrated in master

### CODE REVIEW

**Comment by fabiocos** [comment]
@franzoni @srimanob @plujan as discussed at the PPD general meeting, in view of 10_6_1

**Comment by fabiocos** [comment]
please test

testing really nothing here...

**Comment by plujan** [comment]
ah whoops, looks like we both did this at the same time...shall I just delete mine (#27200 ) then?

**Comment by fabiocos** [comment]
please abort

@plujan no, let's go on with yours

**Pull request closed without merging**
