### PR TITLE
Remove unneeded begin/endLumi methods

### PR DESCRIPTION
**Pull request by schneiml**
Many DQM plugins contain code to watch begin/end lumi transitions, but don't do anything useful there (often just printing a log message, probably because that is part of the sample code). Looking towards concurrent lumisections, watching these transitions is a problem.

- As a first step, this PR removes the unneded code. It should not functionally change anything, except reducing the log output a bit.
- Then, we can evaluate which plugins actually need per-lumi transitions, and enable them only selectively for these plugins in `DQMEDAnalyzer`.
- Finally, since *any* one module watching lumi transitions currently blocks concurrent lumisections, we might want to migrate them to some different implementation that allows concurrent lumis.

@Dr15Jones @knoepfel FYI

### CODE REVIEW

**Comment by Dr15Jones** [comment]
@schneiml Thanks!

**Comment by thomreis** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by dmitrijus** [comment]
+1

**Comment by fabiocos** [comment]
+1

technical cleaning of a large block of code

**Pull request merged**
