### PR TITLE
Remove PoolDBESSource for QGL from cfi file and update Global Tags for RelVals

### PR DESCRIPTION
**Pull request by mmusich**
Removing the PoolDBESSource from the QGTagger_cfi file (originally in #9412).
## Changes in Global Tags:
- Run1 ideal simulation:  as DESRUN1_75_V2 ([browser](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/DESRUN1_75_V2/75X_mcRun1_design_v1)) with:
  - addition of HCAL geometry parameters for Run1; 
  - addition of QG likelihood payloads with 4 labels (removed the ESPrefer from release); 
  - updated ECAL dead channels to be all with status 0, i.e. OK.
- Run1 realistic simulation: as MCRUN1_75_V2 ([browser](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/MCRUN1_75_V2/75X_mcRun1_realistic_v1)) with:
  - addition of HCAL geometry parameters for Run1; 
  - addition of QG likelihood payloads with 4 labels (removed the ESPrefer from release);  
- Run1 Heavy Ion Simulation: as MCHI1_75_V2  ([browser](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/MCHI1_75_V2/75X_mcRun1_HeavyIon_v1)) with:
  - addition of HCAL geometry parameters for Run1; 
  - addition of QG likelihood payloads with 4 labels (removed the ESPrefer from release);  
- Run1 proton lead Simulation: as MCPA1_75_V2  ([browser](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/MCPA1_75_V2/75X_mcRun1_pA_v1)) with:
  - addition of HCAL geometry parameters for Run1; 
  - addition of QG likelihood payloads with 4 labels (removed the ESPrefer from release);  
- Run2 design Simulation: as DESRUN2_75_V2 ([browser](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/DESRUN2_75_V2/75X_mcRun1_design_v1))  with:
  - addition of HCAL geometry parameters for Run2; 
  - addition of QG likelihood payloads with 4 labels (removed the ESPrefer from release); 
  - updated L1T menu to the Collision 2015 version for Stage1; 
  - updated ECAL channel status with all channels having status = 0, i.e. OK.
- Run2 startup simulation: as MCRUN2_75_V4  ([browser](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/MCRUN2_75_V4/75X_mcRun2_startup_v1)) with: 
  - addition of HCAL geometry parameters for Run1 (Run2 is supposed to be identical); 
  - addition of QG likelihood payloads with 4 labels (removed the ESPrefer from release); 
  - updated L1T menu to the Collision 2015 version for GCT at 50 ns; 
  - updated L1T GCT Jet seed threshold for 50 ns run;  
  - updated ECAL channel status with values measured in first collisions.
- Run2 asymptotic simulation: as MCRUN2_75_V5  ([browser](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/MCRUN2_75_V5/75X_mcRun2_asymptotic_v1)) with: 
  - addition of HCAL geometry parameters for Run1 (Run2 is supposed to be identical); 
  - addition of QG likelihood payloads with 4 labels (removed the ESPrefer from release); 
  - updated L1T menu to the Collision 2015 version for Stage1 at 25 ns;  
  - updated ECAL channel status with values measured in first collisions.
- Run2 Heavy Ion simulation: as MCHI2_75_V2  ([browser](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/MCHI2_75_V2/75X_mcRun2_HeavyIon_v1)) with: 
  - addition of HCAL geometry parameters for Run1 (Run2 is supposed to be identical); 
  - addition of QG likelihood payloads with 4 labels (removed the ESPrefer from release); 
  - updated L1T menu to the Collision 2015 version for Stage1 at 25 ns; 
  - updated ECAL channel status with values measured in first collisions.
- Run1 Data processing: as GR_R_75_V4  ([browser](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/GR_R_75_V4/75X_dataRun1_v2)) with: 
  - addition of HCAL geometry parameters with two IOVs for Run1 and Run2 
  - addition of QG likelihood payloads with 4 labels (removed the ESPrefer from release) 
  - updated correction for FED test pulse path length in the last IOV for the DT t0 calibration 
  - updated Tracker Geometry Parameters with two IOVs for Run1 and Run2.
- Run1 HLT processing: as GR_H_V61  ([browser](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/GR_H_V61/75X_dataRun1_HLT_v1)) with 
  - introducing unique tag with Run-1 history and Run-2 conditions for EcalClusterLocalContCorrParametersRcd
  - updated Tracker Geometry Parameters with two IOVs for Run1 and Run2.
- Run2 Data processing: as GR_R_75_V5  ([browser](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/GR_R_75_V5/75X_dataRun2_v2)) with: 
  - addition of HCAL geometry parameters with two IOVs for Run1 and Run2 
  - addition of QG likelihood payloads with 4 labels (removed the ESPrefer from release) 
  - updated correction for FED test pulse path length in the last IOV for the DT t0 calibration 
  - updated Tracker Geometry Parameters with two IOVs for Run1 and Run2.
- Run2 HLT processing: as GR_H_V62  ([browser](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/GR_H_V62/75X_dataRun2_HLT_v1)) with 
  - introducing unique tag with Run-1 history and Run-2 conditions for EcalClusterLocalContCorrParametersRcd
  - updated Tracker Geometry Parameters with two IOVs for Run1 and Run2.

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild please test

**Comment by mmusich** [comment]
@UAEDF-tomc @slava77 this supersedes #9412

**Comment by mmusich** [comment]
this doesnt' seem related to the proposed changes. I've seen this error in other PRs

**Comment by diguida** [comment]
@mmusich agreed, this is not related. Tests done locally on `CMSSW_7_5_X_2015-06-17-2300` looked ok.

**Comment by davidlange6** [comment]
Is a failure of das.

**Comment by slava77** [comment]
I created  an issue for these specific failures

https://github.com/dmwm/DAS/issues/4236

**Comment by diguida** [comment]
please test

**Comment by diguida** [comment]
@slava77 let's see if thew glitches are over now :-(

**Comment by slava77** [comment]
tests in CMSSW_7_5_X_2015-06-19-1100 /test area test9679/

The effects related to ecal status changes are pretty small (they are, as expected, visible only in run 2 MC workflows)
looking at single-electron 35 GeV (run2 setup): [left is baseline; right is with new GT] there are empty spots now
wf1317_ebm14
wf1317_eep04

Common to all the tested workflows (run 1 and run 2  pp  MC  and run 1 pp data, and run 1 HI data) is the change in the neutral hadrons or related to neutral hadrons
Looking at run2 3.5 TeV dijets:
- low-energy photons have a much larger population now (below 0.3 GeV )
all_test9679vsorig_qcd13tevpt3ts3t5wf1313p0c_log10recopfcandidates_particleflow__reco_obj_p42
(particleFlowClusterECAL changes are pretty small, just single bin variations, but the neutral hadrons change a lot on the low end [below] I suspect that this increase in photons is from the PF hadron calibration payloads changes)

- neutral hadrons have a pretty large distortion in the distribution
all_test9679vsorig_qcd13tevpt3ts3t5wf1313p0c_log10recopfcandidates_particleflow__reco_obj_pt50
p (momentum) is looks more significantly modified than the pt
all_test9679vsorig_qcd13tevpt3ts3t5wf1313p0c_log10recopfcandidates_particleflow__reco_obj_p52

(recoPFClusters_particleFlowClusterHCAL collections are unchanged)
... compare this to the effect of the HCAL local reco changes from #9481 on the same objects
all_sign563-pass-3dbaa7bvsorig_qcd13tevpt3ts3t5wf1313p0c_log10recopfcandidates_particleflow__reco_obj_pt50

- the high-et jet response goes down by about 2-3% 
wf1313_ak4pf_corovergen_b
wf1313_ak4pf_recoovergen_b_hist

this is a factor of about 2-3 bigger than the effect of the #9481:
wf1313_ak4pf_recoovergen_b

the lower and middle range of the pt spectrum is essentially unchanged
confirmed on the flat-pt dijet sample
wf1338_ak4pf_corovergen_b
the original (black histo) jet response appears to be better based on the proximity to 1.

- The changes in the pf neutral hadrons distributions at low-pt are unclear and hard to validate from the DQM plots (at jet level, charged hadrons and photons probably take over)
- the high-pt response changes are visible in the jets and appear to go to a wrong direction ... but maybe there are plots that convince otherwise.



@bachtis @mmarionncern @kfiekas

**Comment by slava77** [comment]
hold 
+1

for https://github.com/cms-sw/cmssw/pull/9679	787a9fb
- the change in the reco code itself is technical: replacement of the payload source in the QG tagger. It runs fine in step5 (hence the "+1")
- the changes in the PF hadron calibration payloads appear to be outside of the expected range regarding the change in HCAL or PF reco between pre5 and now, all in #9481  (hence the hold).
If payloads are confirmed as good from other sources, the hold will be removed (or can be bypassed)

**Comment by diguida** [comment]
@slava77 thanks for your review.
The new PF hadron calibration we included in the GT was provided by @mmarionncern 
Can the original developers check that the tag contains the correct payload?

**Comment by mmusich** [comment]
@mmarionncern any update on this issue? We just included in GT the tag: `PFCalibration_v4_mc`.

**Comment by mmarionncern** [comment]
@mmusich @diguida, after investigation and cross check on/of the calibration performed by the HCAL people that I put in the PFCalibration_v4_mc tag, it seems the encap pseudorapidity dependency was slightly sub-optimal and one calibration parameter gave a somehow small unexpected behavior.
After few extra checks, the previous PF calibration tag PFCalibration_v3_mc will perform at a level close to the nominal (validated on pions), making an update of the calibration not necessary. Following some discussion with @kfiekas et al., we propose to stay with the PFCalibration_v3_mc tag.

**Comment by mmusich** [comment]
@mmarionncern ok, we'll need to rollback the GT content to the v3 version of the PFCalibration. @slava77 @davidlange6 we are on it, expect some update soon.

**Comment by diguida** [comment]
commit amended.

**Comment by mmusich** [comment]
@cmsbuild please acknowledge changes

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by mmusich** [comment]
+1

**Comment by davidlange6** [comment]
@slava77 - please post here your comments. I will merge in parallel.

**Comment by diguida** [comment]
@slava77 the documentation of the new Global Tags is also available [here](https://twiki.cern.ch/twiki/bin/view/CMS/RelValGT#CMSSW_7_5_0_pre6).

**Comment by slava77** [comment]
+1
(post factum)
for https://github.com/cms-sw/cmssw/pull/9679	d0828e4
- changes in PF hadrons and related are gone; remaining differences are in line with the GT documentation
    - run 1 pp MC is unchanged
    - run 2 pp MC has small changes starting from ecal 
    - run 1 pp and HI data has small changes in DT (and smaller changes downstream)

**Comment by davidlange6** [comment]
Thanks @slava77

**Pull request merged**
