### PR TITLE
relval fix typos dataset names and port T1tttt workflows from 75x

### PR DESCRIPTION
**Pull request by hengne**
1.) Fix typos in three workflows gen-sim recycle dataset names.
2.) Port T1tttt workflows from 75x to 74x.

### CODE REVIEW

**Comment by franzoni** [comment]
please test

**Comment by franzoni** [comment]
+1
thanks @hengne

**Comment by hengne** [comment]
@boudoul, @franzoni , I updated the mixing and premixing sample names, please trigger a test. 
Thanks 
 Hengne

**Comment by boudoul** [comment]
@cmsbuild please test

**Comment by franzoni** [comment]
+1

**Comment by franzoni** [comment]
@hengne 
can you please confirm that this PR is not needed in 7_5 because the workflows for susy were imported there directly, with their own 7_5-based GEN-SIM ?
For the other commits, wihch relate to input datasets, it's obvious they need be 7_4 specific.

**Comment by davidlange6** [comment]
+1

**Comment by hengne** [comment]
@franzoni yes, I can comfirm this.

On Wed, Jul 8, 2015 at 12:17 AM, Giovanni Franzoni <notifications@github.com

**Pull request merged**
