### PR TITLE
Phase1 Pixel Forward Changes for pre12  (RFC)

### PR DESCRIPTION
**Pull request by schneiml**
This pull request has all the changes regarding Phase1 FPIX geometry.
- It adds a completly new geometry description that aims to describe the actual FPIX detector. The current 2017 geometry is based on the TDR and incrorrect in many ways. Sensor positions should be correct (according to the CAD files) to a few microns. (Thanks @veszpv )
- The material budget is most likely not correct, but at least most relavant volumes should be there. (See Issues, thanks @veszpv). The support rings approximate the actual shape better. (My work)
- It adds new workflows to use the new geometry.  (Thanks @boudoul )
- This means that the old TDR geometry should remain untouched, which is not fully true, see below.

Issues:
- **UPDATE: fixed already** but we should be aware that TDR breakage might be hidden by using the DB geometry. Some C++ code changes do affect the old (TDR/2017) geometry. This should not cause immediate problems, since the old geometry is usually fetched from database where it reains unchanged.
- Some changes affect DetId assignment/Tracker numbering. This will immediatly affect code using the old geometry, but it should not break too many things. We are looking into fixing this by detecting the geometry and changing behaviour. In the long term, this is not needed since only the new geometry should be used. (@venturia) **Update:** Phase2 fixed by  d427f4d, everything else is fine at least according to the automatic tests.
- The support ring description uses the new CutTubs solid which causes problems in Geant.  (Thanks @civanch for providing a workaround for the first issue, more might appear) (Without the workaround, the new workflows _will_ crash in GEN-SIM.)
- The new volumes in the modules cause a lot of new overlaps (but they are not _involved_ in them; they just cause envelopes to grow): All overlaps are air envelope volumes overlapping other things, often also air envelopes; we are looking for a solution by making the blade envelope more precise using unions. This could cause a lot of work, we hope to get a solution tody. (also @ianna)

We would like to get this version tested to know about potential further issues. The final PR will likely have a few more changes to fix some of the issues.

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by rovere** [comment]
Is it possible to also trigger (at bot level) additional, ad-hoc workflows that actually consume the new geometry payload from files? @slava77  @smuzaffar

**Comment by boudoul** [comment]
we just discuss this with Viktor, I can make this happen (I probably won't look before this afternoon due to my shift duties) but I did the same exercise for phase2

**Comment by rovere** [comment]
Thanks @boudoul

**Comment by schneiml** [comment]
I just pushed one more commit which will make this work with an unpatched Geant4. This is not meant for release; just in case somebody wants to test this. To run it, use `runTheMatrix.py --what upgrade -l 11624` etc.

**Comment by ianna** [comment]
@schneiml - there are 161 overlaps and 8 extrusions in the tracker. Quite a few of these can be eliminated by making an Inner Ring slightly thinner in Z (overall by 0.078174 cm and 0.170516 cm for the tip bit).

The outer layer is still in-side-out. Clockwise vs counterclockwise definition? Matrix transformation?

screenshot 2016-09-09 11 34 18

**Comment by rovere** [comment]
I'm not sure I understand the comment: if it's not meant for release it should not enter in the first place, no? If the commit is the one affecting Geometry/TrackerCommonData/data/PhaseI/pixfwd/pixfwdSupportRingParameters.xml my naive question is whether the file now contains the final geometry or a first approximation.
Also, do I understand correctly that we will need a patched Geant4? If so, how long will it take to have it pushed and included?
I do remember that in order to speed up things, it was proposed to simplify, at the beginning, the geometry of the support ring.
Do we have also timing on the impact of such a complex geometry?

**Comment by schneiml** [comment]
@rovere  Regarding commit 05a13b7: Without this, you cannot run the workflows on pre11. So you probably want it.
With this commit, the Support Ring shape is different, and this might cause visible changes. That why this should not get merged. In pre12, a Geant patch should make the real description work (that, however, is untested, as far as I know).

We will either have a new PR to be merged or force-push some changes. This PR is not supposed to be merged right now.

@ianna : regarding the Inner Disk-Outer Ring overlaps, we did already shrink the modules in  0a7ea78. This removed the overlaps *before* adding bf61b66, which massively grows the envelopes and therefore causes loads of new overlaps. We are unwilling to change the support ring in r since it should leave a shadow on the outer disk modules, which would be off be several pixels if we change it.

With bf61b66, it is no longer possible to wrap the blades in an trapezoid. It would be way to big in many critical areas. We are trying to replace the envelope with a more complicated union, but this will take some time and we don't know how far we get there.

I'd favor removing the envelope entirely, but this is virtually impossible due to all the dependencies on it. I'd again like to have a way to group things without constraining them into a volume, which I fear does not exist.

Regarding the inside-out: I vaguely understand what you say, but I have no idea what could cause this problem or how to fix it. Which volume are you talking about (name?). Does it affect skin and core or only one? One copy or both? +Z, -Z, or both?

**Comment by veszpv** [comment]
@schneiml @ianna Do I understand correctly that Yana is suggesting shrinking the support ring in "Z". I think that should be ok considering that here the tracks are very close to parallel to Z. Would this solve the overlap produced by the new passive components on the modules?

**Comment by schneiml** [comment]
@rovere regarding other points: the *old* pixfwdSupportRingParameters.xml is pretty accurate and true to the CAD data. This is what we want to use for now.

The *new* pixfwdSupportRingParameters.xml is slightly simplified to avoid triggering the Geant problem. I did not take any care that these changes keep the shape or the volume,  just that it runs. 

We might come up with a true, simplified shape in the future. For the moment, however, it is safer to stick to the real world.

Timing impacts are unknown. (From my perception, it is a least not a factor of two slower or sth.)

**Comment by schneiml** [comment]
@ianna sorry, you were talking about a different issue than what I was thinking. The ID-OR vs. OD blade overlap can be fixed in the support ring (though it is still true that is caused by the larger envelope due to  bf61b66). 

The long standig issue we discussed some time ago is fixed in 0a7ea78.

**Comment by civanch** [comment]
Just a comment about overlaps: even if we have an overlap of air to air volumes better to avoid this because it may trigger rare run time problems (like stack tracks) for Geant4 tracking, which may be very difficult to debug. This will provide lost jobs in production. I would agree with a small violation of eta/phi mass distribution than not robust geometry. 

Also factor 2 in CPU for tracking is a huge value, hope that this is not full CPU for a QCD event?

**Comment by schneiml** [comment]
@civanch the 2x is an upper bound; I did not notice any change (but I also did not measure), and if it were 2x ore more, I would hae noticed.

**Comment by veszpv** [comment]
Even if we are unsatisfied with performance, I would still suggest to have this in pre12 so that we have something integrated and can ask Pixel Offline, and POGs to run some studies on the new geometry.

**Comment by ianna** [comment]
@veszpv - shrinking the support ring in Z will not solve all overlaps. One has to go for a UnionSolid for a PixelForwardBlade AND PixelForwardModule (a union of two Boxes). Something like that (actual numbers has to be checked!):
screenshot 2016-09-09 13 09 18


```
  <Box name="PixelForwardModule_a"      dx="[ModuleW]/2"     dy="[ModuleL]/2" 
                                        dz="[ModuleT]/4" />
  <Box name="PixelForwardModule_b"      dx="[ModuleW]/2"     dy="[ModuleL]/4" 
                                        dz="[ModuleT]/4" />
  <UnionSolid name="PixelForwardModule">
    <rSolid name="PixelForwardModule_a"/>
    <rSolid name="PixelForwardModule_b"/>
    <Translation x="0.*fm"  y="[ModuleL]/4"  z="[ModuleT]/2" />
  </UnionSolid>
  <UnionSolid name="PixelForwardBlade_a">
    <rSolid name="PixelForwardBladeBase"/>
    <rSolid name="PixelForwardModule"/>
    <Translation x="[ModuleX]+[DetectorShiftX]"  y="[ModuleY]"  z="[BladeBaseT]/2+[ModuleT]/4" />
    <rRotation name="pixfwdbladeInnerZminus:RFacingIP"/>
  </UnionSolid>
  <UnionSolid name="PixelForwardBlade">
    <rSolid name="PixelForwardBlade_a"/>
    <rSolid name="PixelForwardModule"/>
    <Translation x="-[ModuleX]+[DetectorShiftX]" y="[ModuleY]" z="-[BladeBaseT]/2-[ModuleT]/4" />
    <rRotation name="pixfwdbladeInnerZminus:RAwayIP"/>
  </UnionSolid>
```

**Comment by veszpv** [comment]
@ianna I presume a PosPart is not needed in this way, right? We were thinking to do pretty much what you are suggesting, thank you for the example.

**Comment by schneiml** [comment]
@rovere  Very very very preliminary tracking efficieny plots: https://vgy.me/4Xt0nT.png
The issue seems to be the cluster shape filtering as we discussed earlier... can you point me to how to turn this off?

**Comment by ianna** [comment]
@veszpv - Correct, some PosParts will have to be removed.

**Comment by ianna** [comment]
It looks like a legitimate rejection due to crash in CmsTrackerPhase1DiskBuilder. Would it be better to create a different plugin?
```
#5  0x00007efc8f830691 in CmsTrackerPhase1DiskBuilder::sortNS(DDFilteredView&, GeometricDet*) () from /build/cmsbuild/jenkins-workarea/workspace/ib-any-integration/CMSSW_8_1_X_2016-09-08-2300/lib/slc6_amd64_gcc530/pluginGeometryTrackerNumberingBuilderPlugins.so
#6  0x00007efc8f81df48 in CmsTrackerLevelBuilder::build(DDFilteredView&, GeometricDet*, std::string) () from /build/cmsbuild/jenkins-workarea/workspace/ib-any-integration/CMSSW_8_1_X_2016-09-08-2300/lib/slc6_amd64_gcc530/pluginGeometryTrackerNumberingBuilderPlugins.so
#7  0x00007efc8f81c874 in CmsTrackerPixelPhase2EndcapBuilder::buildComponent(DDFilteredView&, GeometricDet*, std::string) () from /build/cmsbuild/jenkins-workarea/workspace/ib-any-integration/CMSSW_8_1_X_2016-09-08-2300/lib/slc6_amd64_gcc530/pluginGeometryTrackerNumberingBuilderPlugins.so
#8  0x00007efc8f81debe in CmsTrackerLevelBuilder::build(DDFilteredView&, GeometricDet*, std::string) () from /build/cmsbuild/jenkins-workarea/workspace/ib-any-integration/CMSSW_8_1_X_2016-09-08-2300/lib/slc6_amd64_gcc530/pluginGeometryTrackerNumberingBuilderPlugins.so
#9  0x00007efc8f83b648 in CmsTrackerBuilder::buildComponent(DDFilteredView&, GeometricDet*, std::string) () from /build/cmsbuild/jenkins-workarea/workspace/ib-any-integration/CMSSW_8_1_X_2016-09-08-2300/lib/slc6_amd64_gcc530/pluginGeometryTrackerNumberingBuilderPlugins.so
#10 0x00007efc8f81debe in CmsTrackerLevelBuilder::build(DDFilteredView&, GeometricDet*, std::string) () from /build/cmsbuild/jenkins-workarea/workspace/ib-any-integration/CMSSW_8_1_X_2016-09-08-2300/lib/slc6_amd64_gcc530/pluginGeometryTrackerNumberingBuilderPlugins.so
#11 0x00007efc8f82f401 in DDDCmsTrackerContruction::construct(DDCompactView const*, std::vector<int, std::allocator<int> >) () from /build/cmsbuild/jenkins-workarea/workspace/ib-any-integration/CMSSW_8_1_X_2016-09-08-2300/lib/slc6_amd64_gcc530/pluginGeometryTrackerNumberingBuilderPlugins.so
#12 0x00007efc8f8361b4 in TrackerGeometricDetESModule::produce(IdealGeometryRecord const&) () from /build/cmsbuild/jenkins-workarea/workspace/ib-any-integration/CMSSW_8_1_X_2016-09-08-2300/lib/slc6_amd64_gcc530/pluginGeometryTrackerNumberingBuilderPlugins.so
#13 0x00007efc8f837668 in edm::eventsetup::CallbackProxy<edm::eventsetup::Callback<TrackerGeometricDetESModule, std::unique_ptr<GeometricDet, std::default_delete<GeometricDet> >, IdealGeometryRecord, edm::eventsetup::CallbackSimpleDecorator<IdealGeometryRecord> >, IdealGeometryRecord, std::unique_ptr<GeometricDet, std::default_delete<GeometricDet> > >::getImpl(edm::eventsetup::EventSetupRecord const&, edm::eventsetup::DataKey const&) () from /build/cmsbuild/jenkins-workarea/workspace/ib-any-integration/CMSSW_8_1_X_2016-09-08-2300/lib/slc6_amd64_gcc530/pluginGeometryTrackerNumberingBuilderPlugins.so
#14 0x00007efca445b72f in edm::eventsetup::DataProxy::get(edm::eventsetup::EventSetupRecord const&, edm::eventsetup::DataKey const&, bool) const () from /cvmfs/cms-ib.cern.ch/week1/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_X_2016-09-08-2300/lib/slc6_amd64_gcc530/libFWCoreFramework.so
#15 0x00007efca4408adb in edm::eventsetup::EventSetupRecord::getFromProxy(edm::eventsetup::DataKey const&, edm::eventsetup::ComponentDescription const*&, bool) const () from /cvmfs/cms-ib.cern.ch/week1/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_X_2016-09-08-2300/lib/slc6_amd64_gcc530/libFWCoreFramework.so
#16 0x00007efc864da0c4 in TkAccumulatingSensitiveDetector::update(BeginOfJob const*) () from /cvmfs/cms-ib.cern.ch/week1/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_X_2016-09-08-2300/biglib/slc6_amd64_gcc530/pluginSimulation.so
```

**Comment by veszpv** [comment]
@ianna AFAIK it is Phase2 workflow. So two solutions are possible: 1) Phase2 creates a plugin specifically for Phase2; 2) I can "hack" this one to decide run-time if it is running on Phase1 or Phase2 geometry and apply changes accordingly. But I think 1) is favored by Gaelle

**Comment by ianna** [comment]
@veszpv - It's up to you to sort it out. Usual CMSSW integration policy is that new code does not break already integrated code.

**Comment by slava77** [comment]
On 9/9/16 2:23 AM, Marco Rovere wrote:
> Is it possible to also trigger (at bot level) additional, ad-hoc
> workflows that actually consume the new geometry payload from files?
> @slava77 <https://github.com/slava77> @smuzaffar
> <https://github.com/smuzaffar>

workflows known to runTheMatrix.py (no -w upgrade)
can be added to the jenkins tests easily by starting a PR test build
manually.
If you want these to become standard, then modify the release code in
the PR.

**Comment by boudoul** [comment]
I am thinking that (but a guess at thi spoint) that this open PR that I made for phase2 :  PR #15662 may help, since I was introducing a phase2 disc builder distinct form pahse1 - I will try to test on top of it (but will take a while many packages to compile I fear ...)

**Comment by venturia** [comment]
The new phase2DiskBuilder will be used only if with the geometry associated to the enumerator PixelPhase2TDRDisk. The geometry associated to PixelPhase2FullDisk and to PixelPhase2ReducedDisk will continue to use the builder CmsTrackerPhase1DiskBuilder. What you can do, and it will be clean, is to create a new class and call it CmsTrackerPhase2TPDiskBuilder by using the code which presently, before Viktor's PR, is in CmsTrackerPhase1DiskBuilder and then modify CmsTrackerPixelPhase2EndcapBuilder to use this new (actually old!) builder for the "phase1 geometry used for phase 2 geometries" (it looks complicated but it is not!)

**Comment by venturia** [comment]
I would say that what I have just suggested is THE solution. There is no way out!

**Comment by schneiml** [comment]
And this should happen in this PR (potentially conflicting the changes that Gaelle pointed to?) If so, I can try to add this.

**Comment by boudoul** [comment]
no worry for 'my' PR, I can update it accordingly afterwards

**Comment by venturia** [comment]
There will be no conflict, at least for what concern the structure of the builder tree. Look at the picture which is available in the Geometry/TrackerNumbering... package. You will see that what you have to do is to decouple the phase 2 branch from the phase 1 branch (not git branch!) by using different builders.

**Comment by ianna** [comment]
@boudoul - I think, it is possible to test both PRs from this one as long as PR #15662 does not conflict with this one. @smuzaffar - what is a command to use?

**Comment by schneiml** [comment]
The Phase2 relvals should be fixed now as @venturia suggested (at least 10424 ran for me).

Another commit removed some of the overlaps by shrinking the support ring, though that should be re-checked with the new disk envelope (might not be needed then).

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by schneiml** [comment]
I added the commit to disable the Cluster Shape Filter (thanks @rovere ), and changes suggessted by @boudoul to get the new geometry actually tested.

As far as I see, the tracking change will disable the filter for all of phase1 (so also the old TDR geometry), but this should not totally break things, so it is probably fine.

**Comment by rovere** [comment]
The other possibility would have been to create a new sub-era, but that would have been definitely more complex to achieve.
As I said, I do not want to have this hackish tracking for longer then necessary: the goal is to fix the cluster shape and revert back these changes. The aim is to have something to compare to pre11 and, also, pre2+old_geometry(and no cluster shape, so even a more apple-to-apple comparison).

**Comment by ianna** [comment]
please test

**Comment by schneiml** [comment]
@ianna I still don't understand the inside-out issue. Which volumes are affected? How can I check for this?

On the overlap front, we now have a solution using unions that gets the -Z side completly free of overlaps and extrusions (with some support ring cuts). This needs to be propagated to +Z, then this PR should be final.

**Comment by schneiml** [comment]
The new envelope volumes, which fix all overlaps, along with all other fixes accumulated here are no in the new PR #15805. The new PR should be merged, unless there are any additional complaints.

**Pull request closed without merging**
