### PR TITLE
[106X] Fix double counting in HepMC to G4 handoff

### PR DESCRIPTION
**Pull request by tvami**
#### PR description:

See https://github.com/cms-sw/cmssw/pull/39427

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport of https://github.com/cms-sw/cmssw/pull/39427

### CODE REVIEW

**Comment by tvami** [comment]
type bugfix

**Comment by tvami** [comment]
backport of https://github.com/cms-sw/cmssw/pull/39427

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by civanch** [comment]
+1

**Comment by perrotta** [comment]
hold
- Pending the validation campaign in master described in https://its.cern.ch/jira/browse/PDMVRELVALS-165

**Comment by shedprog** [comment]
dear all,

Since the following ticket on validation was closed: https://its.cern.ch/jira/browse/PDMVRELVALS-165
Is there anything else that should be done to merge this PR? Thank you for the help.

**Comment by perrotta** [comment]
unhold

**Comment by perrotta** [comment]
hold
(A modifier is needed to steer the modification in a closed release already used for productions)

**Comment by perrotta** [comment]
@civanch no, the default should remain what had been used so far for all productions with this legacy release. The modifier can be used to swith all future productions, if this is what is wanted

**Comment by tvami** [comment]
Closing this PR in favor of https://github.com/cms-sw/cmssw/pull/39942

**Pull request closed without merging**
