### PR TITLE
APE tool implemented, PR 10601 backported

### PR DESCRIPTION
**Pull request by cschomak**
PR #10601 backported to 75X
APE tool implemented into the release
TrackerTreeGenerator (necessary for the APE tool, but might also used for other purposes) included in Alignment/TrackerAlignment
Fixes for ApeSettingAlgorithm in CommonAlignmentAlgorithm and AlignmentProducer in CommonAlignmentProducer

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by cschomak** [comment]
Same here as in PR 10893, I suppose

**Comment by mmusich** [comment]
@cmsbuild please test

**Comment by mmusich** [comment]
+1

**Pull request merged**
