### PR TITLE
Fix PSWeights in LumiHeader to work w diff pythia format

### PR DESCRIPTION
**Pull request by dteague**
#### PR description:

For UL, a new format for PartonShower weights is used in the LumiHeader (`isr:murfac=0.5` instead of `isrDefLo`), so this PR is primarily aimed at fixing this for creating the Gen weight table. Further code is added to avoid edge cases where weight names are missing in the header (possibly caused by these names being put in by hand). 

For more discussion, look [at this discussion](https://github.com/cms-nanoAOD/cmssw/issues/546) as well as the comments from [this PR on a different branch](https://github.com/kdlong/cmssw/pull/35)

#### PR validation:

[Here is a list](https://docs.google.com/spreadsheets/d/1Qlg1c6qrMGY0q111Va2Vl0fJQUz15ZTjKEvRaV8rHaQ/edit#gid=0) of files that were tested on. The code was tested in two different modes: `keepAllPSWeights=True` and `keepAllPSWeights=False` (ie only store 4 main variations).

### CODE REVIEW

**Comment by mariadalfonso** [comment]
assign generators

**Comment by mariadalfonso** [comment]
@dteague
please resolve the code-checks committing the result of `scram build code-checks` so that we can start the test

**Comment by mariadalfonso** [comment]
please test

**Comment by agrohsje** [comment]
Hi @dteague . Please let me know if and when there is more to come for this PR?

**Comment by dteague** [comment]
> Hi @dteague From this discussion: [cms-nanoAOD#546 (comment)](https://github.com/cms-nanoAOD/cmssw/issues/546#issuecomment-718568361)
> I understand the PR addresses all cases (spaces in pre UL, as well as differences between P8.230 and P8.240) ?
> Did you test?

For my tests, I tested the old and new P8 weight format, files that had no lumiheader (possibly has weights or not), and files with the errors in the lumi header (only with P8.230, though the code should work for the p8.240 as long as there is at least one weight name in the header). For specific files I tested on that are exemplars of the types of files I was testing for:

- Old Format: ` /DYJetsToLL_M-5to50_TuneCP5_13TeV-madgraphMLM-pythia8/RunIIAutumn18MiniAOD-102X_upgrade2018_realistic_v15-v2/MINIAODSIM`
- Old Format/Handmade: `/TTWJetsToLNu_TuneCP5_PSweights_13TeV-amcatnloFXFX-madspin-pythia8/RunIIFall17MiniAODv2-PU2017_12Apr2018_94X_mc2017_realistic_v14-v1/MINIAODSIM`
- New Format: `/TTJets_TuneCP5_13TeV-amcatnloFXFX-pythia8/RunIISummer19UL18MiniAOD-106X_upgrade2018_realistic_v11_L1v1-v2/MINIAODSIM`
- New Format/Handmade: None found
- No Header: `/NMSSM_XToYHTo4b_MX-1200_TuneCP5_13TeV-madgraph-pythia8/RunIIFall17MiniAODv2-PU2017_12Apr2018_RP_94X_mc2017_realistic_v14-v1/MINIAODSIM`

I think that should be exhaustive of the types of files one might find, at least from my understanding of the discussion in that issue thread, but if there are other sample that should be tested on, point me to them and I can test them out.

**Comment by mariadalfonso** [comment]
@agrohsje
the list provided by @dteague is enough ? or you envisage more testing ?

**Comment by agrohsje** [comment]
+1

**Comment by mariadalfonso** [comment]
+xpog

testing shows no difference as expected for the MC that are not interested by this fix

**Comment by silviodonato** [comment]
merge

**Pull request merged**
