### PR TITLE
Add ParticleNet info to taus in NanoAOD [13_0_X]

### PR DESCRIPTION
**Pull request by mbluj**
#### PR description:
This PR adds ParticleNet info (extended in https://github.com/cms-sw/cmssw/pull/40745) to taus stored in NanoAOD. The additional information are as follows:
 * ParticleNet discriminators vs jets, electrons and muons,
 * decay mode corresponding with the ParticleNet tau node with the highest score,
 * correction for tau pt,
 * charge assignment confidence (signed),
 * ParticleNet scores for individual decay-modes (normalised to the sum of the scores for all tau nodes).

In addition to adding the above information to already existing taus reconstructed with the HPS algorithm (and passing the loosest WP of at least one of its discriminants vs jets) "recovery" taus are added which correspond with CHSAK4 jets with ParticleNet discriminant vs jets passing WP (>0.05) with an efficiency of ~97% for genuine taus. Also HPS taus passing this WP of ParticleNet vs jet discriminant and not passing other discriminants vs jets are stored (however their fraction is at permille level).

The PanrticleNet information and "recovery" taus are added with a new "hybrid tau" producer which matches CHSAK4 jets with ParticleNet taggers with HPS-taus. The producer can be in principle used also as part of miniAOD sequences.

This is backport of #41333 to CMSSW_13_0 series.

#### PR validation:
Validated with custom nano-AOD workflows with 13_0_X, more detailed validation performed for original PR.

#### PR backport
This is backport of #41333 to CMSSW_13_0 series for production of nanoAOD v12.

### CODE REVIEW

**Comment by mbluj** [comment]
FYI, @simonepigazzini.
This is verbatim backport of https://github.com/cms-sw/cmssw/pull/41333, but I guess that the new features should be enabled for a specific era for nanoAOD v12 and disabled for historical ears. Could you please guide me for which eras switch them on/off, please?

**Comment by simonepigazzini** [comment]
Hi @mbluj, v12 is the version produced with 13_0_X without modifiers, therefore for that we are good. Concerning Run2 processing, the only problem I see is that the training you have included is suboptimal, since is performed on Run3. You can switch off the PNet computation for `run2_nanoAOD_ANY` around these lines: https://github.com/cms-sw/cmssw/blob/388e6f5ab08c8aa9a39f26be8d82e8ef3689f5c7/PhysicsTools/NanoAOD/python/nano_cff.py#L235

**Comment by mbluj** [comment]
> Hi @mbluj, v12 is the version produced with 13_0_X without modifiers, therefore for that we are good. Concerning Run2 processing, the only problem I see is that the training you have included is suboptimal, since is performed on Run3. You can switch off the PNet computation for `run2_nanoAOD_ANY` around these lines:
> 
> https://github.com/cms-sw/cmssw/blob/388e6f5ab08c8aa9a39f26be8d82e8ef3689f5c7/PhysicsTools/NanoAOD/python/nano_cff.py#L235

Yes, I know that the PNet model used is trained for Run3 conditions and that it is (probably) sub-optimal for Run2 conditions, but there is not alternative as Run-2 training is not present. Therefore, it is fine to have it also for v12 production with Run2 samples (if it will happen). However, my question was different: should the PNet-related updates for taus be switched off for historical eras, e.g.  `run2_nanoAOD_106Xv2` or  `run3_nanoAOD_122`, to preserve their backward compatibility or it is fine to keep the configuration as it is.

**Comment by swertz** [comment]
> Therefore, it is fine to have it also for v12 production with Run2 samples (if it will happen).

I think that makes sense, in any case there won't be a central production campaign of Run2 in V12.

What we need to make sure is that it's still possible to produce NanoV12 on Run2 UL miniAOD inputs. But since the Run2 UL test workflows ran fine in https://github.com/cms-sw/cmssw/pull/41333 it looks like that's OK...

**Comment by swertz** [comment]
enable nano

**Comment by swertz** [comment]
please test

**Comment by simonepigazzini** [comment]
please test

**Comment by simonepigazzini** [comment]
MINI/NANO AOD appears to be in order, I restarted the tests, if they fail again on the same (unrelated to this PR) wf we will approve anyway

**Comment by perrotta** [comment]
backport of https://github.com/cms-sw/cmssw/pull/41333

**Comment by mandrenguyen** [comment]
type tau

**Comment by rappoccio** [comment]
@simonepigazzini can you sign this? We can then merge in time for the next 13_0_X.

**Comment by simonepigazzini** [comment]
+1

**Comment by perrotta** [comment]
+1
- All updates are related to nanoAOD

**Pull request merged**
