### PR TITLE
Reconstruction for the Scope Document

### PR DESCRIPTION
**Pull request by lgray**
Masked-layer reconstruction for scope document studies.
Smoothed out all issues in PandoraPFA and homebrew reconstruction, response distributions look sane and degrade as expected when layers are dropped.

@boudoul You can find all the new customizations in customizeHGCalPandora_cff.py, there are three, labelled according to associated descope scenario.

@vandreev11 @pfs @kpedro88 @amagnan

Please note that the set of masked layers is not yet final and there may be a further commit after tomorrow's HGC Steering Group meeting to update the dropped layers.

### CODE REVIEW

**Comment by boudoul** [comment]
Hi @lgray , could you please change in customizeHGCalPandora_cff.py (three places : lines 182 - 201 - 220) 
    process = propagate_layerdropping(process,layer_mask)
by 
    if hasattr(process,'reconstruction_step'):
        process = propagate_layerdropping(process,layer_mask)

it will help to keep the same customize for all steps in RunTheMatrix, thanks

**Comment by boudoul** [comment]
Hi @lgray , @mark-grimes 
Assuming the changes I have requested in my previous comment are  taken into account , I have prepared a branch with runthematrix updated :  boudoul:hgcaldescope  [ https://github.com/boudoul/cmssw/tree/hgcaldescope ]
You can test it by running (for the three scenarios 126XX,140XX,144XX)
runTheMatrix.py --what upgrade -l 12600,14000,14400

Few items before an actual PR
1) please check the three WFs to be sure that I have properly include the customization
2) I can PR once PR #9932 is merged to avoid merge conflict
3) I can also add the case of PileUp, but better to check first if the noPU are ok as requested in 1)

**Comment by lgray** [comment]
@boudoul I have just confirmed that all of the dropped rechit configs are propagated correctly in your PR. It looks good to me.

**Comment by boudoul** [comment]
ok good, thanks @lgray - I will update my branch with the PU scenarios and make a PR once done

**Comment by mark-grimes** [comment]
@lgray, any news from the HGC Steering Group or is this good to go (pending testing and workflow integration)?

**Comment by lgray** [comment]
@mark-grimes go ahead with testing and integration. I double checked the layer-dropping scenarios and there don't seem to be any typos.

**Comment by mark-grimes** [comment]
Please test.

Going to test privately with #9958, but I'll use Jenkins to check for any obvious problems first.

**Comment by lgray** [comment]
@mark-grimes I need to revert the hadron calibration to an older version. Let me add this commit.

**Comment by lgray** [comment]
@mark-grimes just FYI we are checking a possible issue with the pandora hadron calibration. That should not stop the integration of this PR, but we should pause cutting a release until we follow this up (later today).

**Comment by mark-grimes** [comment]
merge

Tested privately with #9966, more details on the testing will be posted there.

@lgray - Okay, put anything else in a new PR.  By the way, every event has e.g.

    %MSG-e ArborInfo:  PFClusterProducer:particleFlowClusterHGCHEF  30-Jun-2015 14:26:48 CEST Run: 1 Event: 9
    Made 5 clusters!
    %MSG

I'm going to change this from error to info unless you have any objections.

**Pull request merged**
