### PR TITLE
Make Geant4 geometry exception to be just a warning

### PR DESCRIPTION
**Pull request by civanch**
#### PR description:
This is a backport of #35572. Should reduce number of crashes in Geant4 massive production.

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
problem not connected with this PR.

**Comment by srimanob** [comment]
@cmsbuild please test

Let's try again. The input failure should not relate to this PR.

**Comment by srimanob** [comment]
Maybe when this PR is merged, we should request the new CMSSW_12_0, for the production test again.

**Pull request merged**
