### PR TITLE
protect HGCDigitizer from crashing when simHitAccumulator is empty

### LINKED ISSUE #29274: Crash in workflow  20634.99
There is a crash during the step3 (digitization after using pre-mixed sample) of the workflow
20610.99. The crash occurs after processing a couple of events with the following exception:

---- Begin Fatal Exception 23-Mar-2020 12:16:28 CET-----------------------
An exception of category 'NullPointerError' occurred while
   [0] Processing  Event run: 1 lumi: 1 event: 2 stream: 0
   [1] Running path 'HLTAnalyzerEndpath'
   [2] Prefetching for module L1TRawToDigi/'hltGtStage2Digis'
   [3] Prefetching for module RawDataCollectorByLabel/'rawDataCollector'
   [4] Prefetching for module CSCDigiToRawModule/'cscpacker'
   [5] Prefetching for module CSCDigiProducer/'simMuonCSCDigis'
   [6] Prefetching for module PreMixingModule/'mixData'
   [7] Calling method for module MixingModule/'mix'
Exception Message:
Event::put: A null unique_ptr was passed to 'put'.
The pointer is of type PHGCSimAccumulator.
The specified productInstanceName was 'HGCDigisHEback'.
----- End Fatal Exception -------------------------------------------------

CMSSW release: CMSSW_11_1_0_pre2
runTheMatrix.py --what upgrade -l 20610.99 -ne

@emiglior, @skinnari, @tsusa, @mmusich, @subirsarkar

### PR DESCRIPTION
**Pull request by mmusich**
resolves https://github.com/cms-sw/cmssw/issues/29274

#### PR description:

Solves the problem reported at: https://github.com/cms-sw/cmssw/issues/29274 by implementing the suggestion from @makortel at https://github.com/cms-sw/cmssw/issues/29274#issuecomment-602727215.

#### PR validation:

Tested the code changes with `runTheMatrix.py --what upgrade -l 20610.99` in `CMSSW_11_1_X_2020-03-23-2300`, which now runs to completion.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Not a backport.

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test workflow 20661.97, 20634.99

**Comment by civanch** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade

**Comment by silviodonato** [comment]
+1

**Pull request merged**
