### PR TITLE
HLT menu development for `14_1_X` (1/N) [`14_2_X`]

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

Development of HLT menus for `CMSSW_14_1_X` (branch `CMSSW_14_2_X`): 
   * This is the PR for the master branch, which will then be backported down to 14_1_X (the latter is the release cycle currently used for Run-3 HLT-menu development).
  
This update includes the integration of the following changes (094abc75f9821ea40087374dcd2b0050082487ee):
- migration of the combined HLT table and related subtables to the CMSSW_14_1_0 confDB template;
- removal of now useless customization functions related to CMSSW_14_1_X developments;

#### PR validation:

TSG Integration tests.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Not a backport, but it will be backported to `CMSSW_14_1_X`.

### CODE REVIEW

**Comment by mmusich** [comment]
type hlt-integration

**Comment by mmusich** [comment]
enable gpu

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
+hlt

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
