### PR TITLE
pixel DQM@HLT

### PR DESCRIPTION
**Pull request by mtosi**
--finally--
we have the pixel@HLT DQM
this PR add the pixel@HLT DQM on both online and offline workflow

@fioriNTU 
while testing this w/ runTheMatrix.py --limited
I saw that SiPixelPhase1TrackCluster was not checking the validity of the input collections,
not it is fixed

I also add the lumiMonitoring to the HLT offline DQM
(even if this module makes use of the lumi measurement from the scaler)

in addition, I fixed the strip DQM in the HLT online DQM as well
and add the monitoring of the HLT_ZeroBias_FirstCollisionAfterAbortGap
which is one of the calibration triggers for the tracker DPG (used for the strip APV gain)

finally, I add the client in the online DQM,
as now for both the tracking (iterative and GSF) and pixel

### CODE REVIEW

**Comment by threus** [comment]
@mtosi @fioriNTU I added this PR to https://twiki.cern.ch/twiki/bin/view/CMS/DQMP5TagCollector

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
Hi, you need to make a 91X PR which gets integrated first (in 91X)

**Comment by mtosi** [comment]
yes, thanks Martin
I'm working on it
but the pixel and strip DQM in 91x is different (I've just realized)
and I have to patch some files
I'm doing it, now

  mia

**Comment by mtosi** [comment]
thanks !
  mia

**Comment by Martin-Grunewald** [comment]
+1

**Comment by mtosi** [comment]
while testing this PR on the DQM playback
by running on MC phase1 sample and CRUZET data (w/o pixel),
@threus found the error [1]
not sure which input sample has been used, 
but most probably it is not the DQMOutput which is generally produced by HLT
=> the needed collections are missing 
and the MeasurementTrackerEventProducer is not safe w.r.t. missing input collections

I need to update this PR

[1]
=======
Begin processing the 1st record. Run 500150, Event 1, LumiSection 1 at 10-Apr-2017 10:00:34.241 CEST
%MSG-w SiPixelPhase1TrackClusters:   SiPixelPhase1TrackClusters:hltSiPixelPhase1TrackClustersAnalyzer  10-Apr-2017 10:00:34 CEST Run: 500150 Event: 1
track collection is not valid
%MSG
----- Begin Fatal Exception 10-Apr-2017 10:00:35 CEST-----------------------
An exception of category 'ProductNotFound' occurred while
   [0] Processing run: 500150 lumi: 1 event: 1
   [1] Running path 'hlt4vector'
   [2] Calling method for module MeasurementTrackerEventProducer/'hltMeasurementTrackerEvent'
Exception Message:
Principal::getByToken: Found zero products matching all criteria
Looking for type: edmNew::DetSetVector<SiStripCluster>
Looking for module label: hltSiStripRawToClustersFacility
Looking for productInstanceName:
=======

**Comment by dmitrijus** [comment]
please test

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by perrotta** [comment]
+1
Reco only affected by a few protections added in MeasurementTrackerEventProducer.cc

**Comment by mtosi** [comment]
is there anything preventing this PR to be integrated ?
thanks for your help !

**Comment by Martin-Grunewald** [comment]
For example, the DQM signature is missing.

**Comment by mtosi** [comment]
@dmitrijus @vanbesien 
are there still issues w/ this PR ?

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
Hi @mtosi - please add the commit(s) generated during the 91x review also to this PR. Thanks

**Comment by mtosi** [comment]
ciao
if I'm not wrong, PR https://github.com/cms-sw/cmssw/pull/18252 (90x) and PR https://github.com/cms-sw/cmssw/pull/18264 (91x) differs for
19 files changed vs 23 files
the 4 extra files are
1. DQM/SiStripMonitorTrack/src/SiStripMonitorTrack.cc
2. DQM/SiStripMonitorTrack/interface/SiStripMonitorTrack.h
3. DQM/SiStripMonitorTrack/python/SiStripMonitorTrack_cfi.py
4. DQM/SiPixelPhase1Summary/src/SiPixelPhase1Summary.cc

file 4. has the LogWarning (plus some comments I have on the code), and I'm adding it
while file 1., 2. and 3. have been changed in order to handle plots for strip digis
(actually I would have add a dedicated DQM code specific to the Digis, 
but ok I'm no longer the tracker DQM ;) )
which are not always needed / necessary
(@HLT we do not produce them)
such plots have been introduced and integrated only in 91x
=> there is no need of touching those files in 90x

the other files should be in synch

**Comment by Martin-Grunewald** [comment]
please test

**Comment by perrotta** [comment]
@mtosi : there are indeed a handful of other differences between this PR and the one merged in the master. First of all, the ones I don't care about (just for your info):
- DQM/Integration/python/clients/hlt_dqm_sourceclient-live_cfg.py: maxEvents not set in #18252
- DQM/Integration/python/config/inputsource_cfi.py only in #18264
- Differences in DQMOffline/Trigger/python/SiPixel_OfflineMonitoring_Cluster_cff.py

Then, in the following I notice that L192 was removed in #18264 and not here: 
- DQM/SiPixelPhase1Summary/src/SiPixelPhase1Summary.cc

Are you sure that it had to be removed from #18264? (It doesn't look so to me; but then, if it is correct you would like to remove that line also from here)

Finally, about what mostly refers to reco in this PR: the protections added to
- RecoTracker/MeasurementDet/plugins/MeasurementTrackerEventProducer.cc

are all quite reasonable, but I don't see them in your 91X PR, and not even merged in the master with some other pull request. Is there any reason why they should only stay here and not in the master? (Or perhaps they are already queued with some other PR and I just did not spot them)?

**Comment by mtosi** [comment]
opsi
thanks @perrotta 

ok, let me check

1. DQM/Integration/python/clients/hlt_dqm_sourceclient-live_cfg.py: maxEvents not set in #18252 
2. DQM/Integration/python/config/inputsource_cfi.py only in #18264
3. Differences in DQMOffline/Trigger/python/SiPixel_OfflineMonitoring_Cluster_cff.py

point 1. and 2. probably should not be in any PR :(
=> they should be fixed in the master :( and I'll do a PR (sorry)

the differences in point 3. should simply reflect the differences between the 2 releases of the main SiPixelPhase1 DQM code (there are some updates / new features only available in the master)

4. DQM/SiPixelPhase1Summary/src/SiPixelPhase1Summary.cc
for point 4. I do not see L192 :(

5. RecoTracker/MeasurementDet/plugins/MeasurementTrackerEventProducer.cc
this indeed I'm afraid has been spotted only w/in the test of this PR
and when I asked if it would have made sense to have it in the PR for 91x
I think I did not receive any comment and then I forgot ! (sorry)

=> if you agree, I would leave this PR as it is now
and add a new PR for the master in order to address points 1,2, and 5

thanks again for your help/support (and patience !)

**Comment by perrotta** [comment]
4. DQM/SiPixelPhase1Summary/src/SiPixelPhase1Summary.cc
for point 4. I do not see L192 :(

It was L162, in fact (not wearing my glasess...):

immagine_mtosi

**Comment by perrotta** [comment]
Fine with me if you integrate in this PR the "best possible" version, and propagate it to the master with another dedicated PR.

If you keep the codes in the different releases synchronized (unless needed otherwise) it then becomes easier for you to propagate the possible fixes... and for us to review!

Ciao,
A.

**Comment by mtosi** [comment]
ehehe ;)
thanks !
I prepared the branch for fixing the master 
and opened PR https://github.com/cms-sw/cmssw/pull/18520

**Comment by Martin-Grunewald** [comment]
+1

**Comment by perrotta** [comment]
+1
RecoTracker/MeasurementDet/plugins/MeasurementTrackerEventProducer.cc is now identical to what already merged in 91X
About my previous comments in https://github.com/cms-sw/cmssw/pull/18252#issuecomment-298033905: - the issue with DQM/SiPixelPhase1Summary/src/SiPixelPhase1Summary.cc had been fixed in 91X (and it was already correct here)
- the aesthetic differences between the files in the DQM area are annoying, but of no concern for reco

**Comment by Martin-Grunewald** [comment]
@dmitrijus 
Please sign this PR.
Thanks!

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
