### PR TITLE
Refined hltDiff output for automatisation [8_1_X]

### PR DESCRIPTION
**Pull request by bartosik-hep**
Implemented several improvements of the hltDiff output:
- recovered missing summary printout with the list of affected triggers
- always creating all requested output files, even if no affected events were found
- minor bug fixes

### CODE REVIEW

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by fwyzard** [comment]
+1

**Comment by fwyzard** [comment]
@bartosik-hep , thank you for the changes.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
