### PR TITLE
Updates for CSC L1T DQM following B904 tests on cosmic data

### PR DESCRIPTION
**Pull request by dildick**
#### PR description:

Updates for CSC L1T DQM following B904 tests on cosmic data. DQM modules in L1TMonitor and L1TMonitorClient were given an option so that we can analyze data from the B904 test-stand. Data-vs-emulation is a 5-step procedure. The last step produces a single postscript containing histograms with data-vs-emulator comparisons.

```
## step 1: get the .raw file from the CSC DAQ computer. Contact B904 experts

## step 2: convert the .raw file to EDM ROOT. Set firstRun high enough so that the GEM geometry is recognized in Run-3 eras in step 3.
cmsRun IORawData/CSCCommissioning/test/readFile_b904_Run3.py firstRun=341761 \
inputFiles=csc_00000001_EmuRUI01_Local_000_210519_162820_UTC.raw maxEvents=80000

## step 3: unpack, emulate, and run the DQM
cmsRun L1Trigger/CSCTriggerPrimitives/test/runCSCTriggerPrimitiveProducer_cfg.py unpack=True l1=True dqm=True \
runCCLUT=True runME11ILT=False useB904Data=True maxEvents=-1 \
inputFiles= csc_00000001_EmuRUI01_Local_000_210519_162820_UTC.root 

## step 4: run the DQM client (produces histograms of differences)
cmsRun L1Trigger/CSCTriggerPrimitives/test/runCSCL1TDQMClient_cfg.py mc=False run3=True useB904Data=True

## step 5: run the L1 CSC analyzer (run number 341761 is set in step 2). Produces a postscript file.
cmsRun L1Trigger/CSCTriggerPrimitives/test/runCSCTriggerPrimitiveAnalyzer_cfg.py dataVsEmulation=True \
dataVsEmulationFile=file:DQM_V0001_R000341761__Global__CMSSW_X_Y_Z__RECO.root runNumber=341761
```

Note that the CSC unpacker in CMSSW for Run-3 data is not yet updated. That is expected to happen in the next few weeks/months. The validation plots were made with the Run-3 unpacker in a private branch.

#### PR validation:

Tested with 
```
scram b -k -j 16 runtests
runTheMatrix.py -l limited
```

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

No backport needed I think. Most of our CSC trigger primitive tests are being conducted with the B904 test-stand. Depending on the timeline when the CSC firmware will be updated at P5 (before or during CRUZET, before or during CRAFT?) it may need to be backported. Perhaps by then we will have switched to CMSSW_12_0_0 at P5.

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

@barvic @tahuang1991

### CODE REVIEW

**Comment by dildick** [comment]
A few plots from the postscript file with just 1000 events from the May 19 B904 cosmic run below. (There are actually 80,000 events in total). There are discrepancies, but at least the procedure works as expected.
* ALCT properties look in general very good.
* Many discrepancies for CLCT and LCT due to (1) wrong parity of the OTMB firmware version loaded onto FPGA and (2) private version of CSC unpacker needs updates for Run-3 CSC TPs. We understand the issues and are planning a new cosmic run next week.
 
Screen Shot 2021-05-27 at 10 54 28 PM
Screen Shot 2021-05-27 at 10 54 50 PM
Screen Shot 2021-05-27 at 10 54 56 PM
Screen Shot 2021-05-27 at 10 55 03 PM
Screen Shot 2021-05-27 at 10 55 19 PM
Screen Shot 2021-05-27 at 10 55 26 PM
Screen Shot 2021-05-27 at 10 55 42 PM
Screen Shot 2021-05-27 at 10 56 11 PM

**Comment by jfernan2** [comment]
please test

**Comment by dildick** [comment]
Not sure what is going on. The missing CaloTopologyRecord is unrelated to this PR.

**Comment by dildick** [comment]
@jfernan2 Can you restart the tests, please? These commands worked for me
```
cmsrel CMSSW_12_0_X_2021-06-01-1100
cd CMSSW_12_0_X_2021-06-01-1100/src
cmsenv
git cms-rebase-topic --unsafe dildick:from-CMSSW_12_0_X_2021-05-27-1100-DQM-B904
scram b -j 4
scram b code-format
scram b code-checks
```

**Comment by qliphy** [comment]
> Not sure what is going on. The missing CaloTopologyRecord is unrelated to this PR.

Should be fixed by https://github.com/cms-sw/cmssw/pull/33875

**Comment by qliphy** [comment]
please test

**Comment by smorovic** [comment]
+1

**Comment by jfernan2** [comment]
@dildick I have a question: this changes should affect current L1T/CSC data or future, but not old workflows like Run1 where the plots are produced empty, right?

https://tinyurl.com/y4qlf3pu
https://tinyurl.com/y5h4eprw
https://tinyurl.com/yxdt2qca

Would it be possible to restrict the output to the needed workflows only?  All the wf comparisons here:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_0_X_2021-06-01-1100+68600a/43134/dqm-histo-comparison-summary.html

Thanks

**Comment by dildick** [comment]
@jfernan2 The CSC TPG data vs emulator should only be running in Run-3 workflows. Could this be the problem https://github.com/cms-sw/cmssw/blob/master/DQM/L1TMonitor/python/L1TEmulatorMonitor_cff.py#L84? 
Screen Shot 2021-06-02 at 9 04 21 AM 
Maybe this needs to be deleted.


l1tdeCSCTPG is included here https://github.com/cms-sw/cmssw/blob/master/DQM/L1TMonitor/python/L1TStage2Emulator_cff.py#L169
Screen Shot 2021-06-02 at 9 05 18 AM
But perhaps l1tdeCSCTPG needs to be included only when Run-3 is active, like GEM.

**Comment by jfernan2** [comment]
yes @dildick if you want only Run3 wfs, you need to set so with Eras logic, like GEM is doing

**Comment by dildick** [comment]
@jfernan2 This commit should address that https://github.com/cms-sw/cmssw/pull/33876/commits/066969c3dc9296dbeb8a3d92e6b4bfd6ca38c095

**Comment by jfernan2** [comment]
Thank you!!
Running tests as cross-check

**Comment by jfernan2** [comment]
please test

**Comment by dildick** [comment]
@jfernan2 Can you stop the tests? Sorry. It was pointed out to me in private conversation that we do need to keep it for Run-2. Those plots are being filled, e.g. WF 136.713. What I need to do however, is turn-off the Run-3 comparisons in Run-2 eras.

**Comment by jfernan2** [comment]
please abort

**Comment by dildick** [comment]
Let me revert the last commit.

**Comment by dildick** [comment]
I think that the real problem is here: https://github.com/cms-sw/cmssw/blob/master/DQM/L1TMonitor/python/L1TEmulatorMonitor_cff.py#L111-L118. CSCTPG should be added to `l1ExpertDataVsEmulatorStage1`. 

Screen Shot 2021-06-02 at 10 56 15 AM


It was added to `l1ExpertDataVsEmulator`, but I guess that sequence is not doing anything.

**Comment by dildick** [comment]
Even if I did add it to `l1ExpertDataVsEmulatorStage1`, it does not do anything in WF 4.53. The module `valCscTriggerPrimitiveDigis` is loaded but not attached to any path. It's probably better to remove it for Run-1 and and `Stage1` (which I think means Run-2 2015).

**Comment by dildick** [comment]
@jfernan2 I removed the CSCTPG modules from Run-1 and Stage-1. I ran local tests ```runTheMatrix -l limited```

```
4.22_RunCosmics2011A+RunCosmics2011A+RECOCOSD+ALCACOSD+SKIMCOSD+HARVESTDC Step0-DAS_ERROR Step1-NOTRUN Step2-NOTRUN Step3-NOTRUN Step4-NOTRUN  - time date Wed Jun  2 12:10:11 2021-date Wed Jun  2 12:09:31 2021; exit: 1 0 0 0 0
4.53_RunPhoton2012B+RunPhoton2012B+HLTD+RECODR1reHLT+HARVESTDR1reHLT Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED  - time date Wed Jun  2 12:34:28 2021-date Wed Jun  2 12:09:31 2021; exit: 0 0 0 0
5.1_TTbar+TTbarFS+HARVESTFS Step0-PASSED Step1-PASSED  - time date Wed Jun  2 12:15:48 2021-date Wed Jun  2 12:09:32 2021; exit: 0 0
7.3_CosmicsSPLoose_UP18+CosmicsSPLoose_UP18+DIGICOS_UP18+RECOCOS_UP18+ALCACOS_UP18+HARVESTCOS_UP18 Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Wed Jun  2 12:19:52 2021-date Wed Jun  2 12:09:32 2021; exit: 0 0 0 0 0
8.0_BeamHalo+BeamHalo+DIGICOS+RECOCOS+ALCABH+HARVESTCOS Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Wed Jun  2 12:18:53 2021-date Wed Jun  2 12:10:12 2021; exit: 0 0 0 0 0
9.0_Higgs200ChargedTaus+Higgs200ChargedTaus+DIGI+RECO+HARVEST Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED  - time date Wed Jun  2 12:31:47 2021-date Wed Jun  2 12:15:48 2021; exit: 0 0 0 0
25.0_TTbar+TTbar+DIGI+RECOAlCaCalo+HARVEST+ALCATT Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Wed Jun  2 12:38:33 2021-date Wed Jun  2 12:18:53 2021; exit: 0 0 0 0 0
135.4_ZEE_13+ZEEFS_13+HARVESTUP15FS+MINIAODMCUP15FS Step0-PASSED Step1-PASSED Step2-PASSED  - time date Wed Jun  2 12:28:25 2021-date Wed Jun  2 12:19:52 2021; exit: 0 0 0
136.731_RunSinglePh2016B+RunSinglePh2016B+HLTDR2_2016+RECODR2_2016reHLT_skimSinglePh_HIPM+HARVESTDR2 Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED  - time date Wed Jun  2 12:59:41 2021-date Wed Jun  2 12:28:25 2021; exit: 0 0 0 0
136.7611_RunJetHT2016E_reminiaod+RunJetHT2016E_reminiaod+REMINIAOD_data2016_HIPM+HARVESTDR2_REMINIAOD_data2016_HIPM Step0-PASSED Step1-PASSED Step2-PASSED  - time date Wed Jun  2 12:41:48 2021-date Wed Jun  2 12:31:48 2021; exit: 0 0 0
136.793_RunDoubleEG2017C+RunDoubleEG2017C+HLTDR2_2017+RECODR2_2017reHLT_skimDoubleEG_Prompt+HARVEST2017 Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED  - time date Wed Jun  2 13:10:33 2021-date Wed Jun  2 12:34:29 2021; exit: 0 0 0 0
136.8311_RunJetHT2017F_reminiaod+RunJetHT2017F_reminiaod+REMINIAOD_data2017+HARVEST2017_REMINIAOD_data2017 Step0-PASSED Step1-PASSED Step2-PASSED  - time date Wed Jun  2 12:47:19 2021-date Wed Jun  2 12:38:33 2021; exit: 0 0 0
136.8523_RunJetHT2018C_nanoULremini+RunJetHT2018C_nanoULremini+NANOEDM2018_106Xv2+HARVESTNANOAOD2018_106Xv2 Step0-PASSED Step1-PASSED Step2-PASSED  - time date Wed Jun  2 12:51:04 2021-date Wed Jun  2 12:41:49 2021; exit: 0 0 0
136.874_RunEGamma2018C+RunEGamma2018C+HLTDR2_2018+RECODR2_2018reHLT_skimEGamma_Offline_L1TEgDQM+HARVEST2018_L1TEgDQM Step0-PASSED Step1-FAILED Step2-NOTRUN Step3-NOTRUN  - time date Wed Jun  2 12:51:16 2021-date Wed Jun  2 12:47:19 2021; exit: 0 21504 0 0
136.88811_RunJetHT2018D_reminiaodUL+RunJetHT2018D_reminiaodUL+REMINIAOD_data2018UL+HARVEST2018_REMINIAOD_data2018UL Step0-PASSED Step1-FAILED Step2-NOTRUN  - time date Wed Jun  2 12:57:56 2021-date Wed Jun  2 12:51:05 2021; exit: 0 21504 0
140.53_RunHI2011+RunHI2011+RECOHID11+HARVESTDHI Step0-PASSED Step1-PASSED Step2-PASSED  - time date Wed Jun  2 13:06:11 2021-date Wed Jun  2 12:51:16 2021; exit: 0 0 0
140.56_RunHI2018+RunHI2018+RECOHID18+HARVESTDHI18 Step0-PASSED Step1-FAILED Step2-NOTRUN  - time date Wed Jun  2 13:09:00 2021-date Wed Jun  2 12:57:57 2021; exit: 0 21504 0
158.01_HydjetQ_reminiaodPbPb2018_INPUT+HydjetQ_reminiaodPbPb2018_INPUT+REMINIAODHI2018PPRECOMB+HARVESTHI2018PPRECOMINIAOD Step0-DAS_ERROR Step1-NOTRUN Step2-NOTRUN  - time date Wed Jun  2 12:59:44 2021-date Wed Jun  2 12:59:41 2021; exit: 1 0 0
1306.0_SingleMuPt1_UP15+SingleMuPt1_UP15+DIGIUP15+RECOUP15+HARVESTUP15 Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED  - time date Wed Jun  2 13:12:47 2021-date Wed Jun  2 12:59:44 2021; exit: 0 0 0 0
1325.81_TTbar_13_106Xv1NanoAODINPUT+TTbar_13_106Xv1NanoAODINPUT+NANOEDMMC2017_106XMiniAODv1+HARVESTNANOAODMC2017_106XMiniAODv1 Step0-DAS_ERROR Step1-NOTRUN Step2-NOTRUN  - time date Wed Jun  2 13:06:15 2021-date Wed Jun  2 13:06:11 2021; exit: 1 0 0
1330.0_ZMM_13+ZMM_13+DIGIUP15+RECOUP15_L1TMuDQM+HARVESTUP15_L1TMuDQM+NANOUP15 Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Wed Jun  2 13:23:12 2021-date Wed Jun  2 13:06:15 2021; exit: 0 0 0 0 0
101.0_SingleElectronE120EHCAL+SingleElectronE120EHCAL Step0-PASSED  - time date Wed Jun  2 13:11:24 2021-date Wed Jun  2 13:09:00 2021; exit: 0
312.0_Pyquen_ZeemumuJets_pt10_2760GeV_2021+Pyquen_ZeemumuJets_pt10_2760GeV_2021+DIGIHI2021MIX+RECOHI2021MIX+HARVESTHI2021PPRECO Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED  - time date Wed Jun  2 13:46:40 2021-date Wed Jun  2 13:10:34 2021; exit: 0 0 0 0
25202.0_TTbar_13+TTbar_13+DIGIUP15_PU25+RECOUP15_PU25+HARVESTUP15_PU25+NANOUP15_PU25 Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Wed Jun  2 13:40:39 2021-date Wed Jun  2 13:11:25 2021; exit: 0 0 0 0 0
1000.0_RunMinBias2011A+RunMinBias2011A+TIER0+SKIMD+HARVESTDfst2+ALCASPLIT Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Wed Jun  2 13:36:54 2021-date Wed Jun  2 13:12:47 2021; exit: 0 0 0 0 0
1001.0_RunMinBias2011A+RunMinBias2011A+TIER0EXP+ALCAEXP+ALCAHARVDSIPIXELCALRUN1+ALCAHARVD1+ALCAHARVD2+ALCAHARVD3+ALCAHARVD4+ALCAHARVD5 Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED Step5-PASSED Step6-PASSED Step7-PASSED Step8-PASSED  - time date Wed Jun  2 13:41:00 2021-date Wed Jun  2 13:23:12 2021; exit: 0 0 0 0 0 0 0 0 0
10024.0_TTbar_13+2017+TTbar_13TeV_TuneCUETP8M1_GenSim+Digi+RecoFakeHLT+HARVESTFakeHLT+ALCA+Nano Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED Step5-PASSED  - time date Wed Jun  2 14:02:21 2021-date Wed Jun  2 13:36:55 2021; exit: 0 0 0 0 0 0
10042.0_ZMM_13+2017+ZMM_13TeV_TuneCUETP8M1_GenSim+Digi+RecoFakeHLT+HARVESTFakeHLT+ALCA+Nano Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED Step5-PASSED  - time date Wed Jun  2 14:03:15 2021-date Wed Jun  2 13:40:39 2021; exit: 0 0 0 0 0 0
10224.0_TTbar_13+2017PU+TTbar_13TeV_TuneCUETP8M1_GenSim+DigiPU+RecoFakeHLTPU+HARVESTFakeHLTPU+Nano Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Wed Jun  2 14:37:04 2021-date Wed Jun  2 13:41:01 2021; exit: 0 0 0 0 0
10824.0_TTbar_13+2018+TTbar_13TeV_TuneCUETP8M1_GenSim+Digi+RecoFakeHLT+HARVESTFakeHLT+ALCA+Nano Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED Step5-PASSED  - time date Wed Jun  2 14:11:18 2021-date Wed Jun  2 13:46:40 2021; exit: 0 0 0 0 0 0
11634.0_TTbar_14TeV+2021+TTbar_14TeV_TuneCP5_GenSim+Digi+Reco+HARVEST+ALCA Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Wed Jun  2 14:36:16 2021-date Wed Jun  2 14:02:22 2021; exit: 0 0 0 0 0
12434.0_TTbar_14TeV+2023+TTbar_14TeV_TuneCP5_GenSim+Digi+Reco+HARVEST+ALCA Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Wed Jun  2 14:46:04 2021-date Wed Jun  2 14:03:15 2021; exit: 0 0 0 0 0
23234.0_TTbar_14TeV+2026D49+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14+DigiTrigger+RecoGlobal+HARVESTGlobal Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED  - time date Wed Jun  2 14:43:44 2021-date Wed Jun  2 14:11:18 2021; exit: 0 0 0 0
28234.0_TTbar_14TeV+2026D60+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14+DigiTrigger+RecoGlobal+HARVESTGlobal Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED  - time date Wed Jun  2 15:08:12 2021-date Wed Jun  2 14:36:17 2021; exit: 0 0 0 0
34634.0_TTbar_14TeV+2026D76+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14+DigiTrigger+RecoGlobal+HARVESTGlobal Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED  - time date Wed Jun  2 15:04:12 2021-date Wed Jun  2 14:37:05 2021; exit: 0 0 0 0
34834.999_TTbar_14TeV+2026D76PU_PMXS1S2PR+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14+PREMIX_PremixHLBeamSpot14PU+DigiTriggerPU+RecoGlobalPU+HARVESTGlobalPU Step0-PASSED Step1-FAILED Step2-NOTRUN Step3-NOTRUN Step4-NOTRUN  - time date Wed Jun  2 15:00:51 2021-date Wed Jun  2 14:43:45 2021; exit: 0 21504 0 0 0
250202.181_TTbar_13UP18+TTbar_13UP18+PREMIXUP18_PU25+DIGIPRMXLOCALUP18_PU25+RECOPRMXUP18_PU25+HARVESTUP18_PU25 Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Wed Jun  2 15:19:36 2021-date Wed Jun  2 14:46:04 2021; exit: 0 0 0 0 0
34 29 28 23 14 4 1 1 1 tests passed, 3 4 0 0 0 0 0 0 0 failed
```

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by dildick** [comment]
A few plots from a cosmic run on May 31st at B904. Agreement is better (as expected since we loaded the correct firmware). The CLCT slope is still wrong. Could be a problem in a LUT, in the firmware, unpacker or emulator. We're looking into it.

Screen Shot 2021-06-02 at 10 11 33 PM
Screen Shot 2021-06-02 at 10 11 45 PM
Screen Shot 2021-06-02 at 10 11 52 PM
Screen Shot 2021-06-02 at 10 12 00 PM
Screen Shot 2021-06-02 at 10 12 10 PM
Screen Shot 2021-06-02 at 10 12 16 PM
Screen Shot 2021-06-02 at 10 12 25 PM
Screen Shot 2021-06-02 at 10 12 32 PM
Screen Shot 2021-06-02 at 10 12 57 PM
Screen Shot 2021-06-02 at 10 13 05 PM
Screen Shot 2021-06-02 at 10 13 11 PM

**Comment by dildick** [comment]
Full file: 
[CSC_dataVsEmul_B904_Cosmic_Run_210531_170620.pdf](https://github.com/cms-sw/cmssw/files/6588688/CSC_dataVsEmul_B904_Cosmic_Run_210531_170620.pdf)

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
Thanks a lot @dildick 
Just a question: is GEM crew aware of these changes? Despite they are small, they seem to be moving the entries from one ME to another:
https://tinyurl.com/yy7ww7jq
https://tinyurl.com/y5qb4vkr
https://tinyurl.com/y6dqm2nw
Do you understand this? (Blue is base, black is your PR, as usual)

**Comment by dildick** [comment]
Most of the failed comparisons come from a single WF 
Screen Shot 2021-06-03 at 11 20 38 AM

The differences in the other WFs can be attributed to (1) change of CSC histograms names and (2) enabling the GEM unpacked data from the EMTF DAQ path in the GEM data vs emulator module. 

(1) is expected, since certain histograms cannot be found in this transition (e.g. I changed `quartstrip` to `quartstripbit`)

(2) ideally, the GEM trigger data is unpacked correctly by the EMTF unpacker, and the GEM DAQ data is unpacked correctly by the GEM unpacker. In this module I now compare the re-emulated GEM trigger data (from GEM DAQ data) with the GEM trigger data from the EMTF DAQ path. Previously I had two times the same label (`valMuonGEMPadDigiClusters`) I switched the data label to `emtfStage2Digis` because I was informed that the EMTF unpacker is working now. So the "diff" histograms should ideally be empty. They are not. Not quite sure what is happening. Also, the "emul" histograms are missing (which I don't understand).

**Comment by dildick** [comment]
@jfernan2 So there is no EMTF packer yet, which would explain why we don't see clusters from `emtfStage2Digis`. Those differences will show up in the standard tests. The "emul" histograms are always filled, so we don't see any differences there.

**Comment by dildick** [comment]
@jfernan2 Until the EMTF packer is not in place yet, the data and emul label for the GEMs clusters should read `valMuonGEMPadDigiClusters`. However, at P5 in online DQM we could change it to `emtfStage2Digis` where GEMs are in the process of becoming available. But perhaps we should wait that a few more weeks.

**Comment by civanch** [comment]
please test

**Comment by cecilecaillol** [comment]
+l1

**Comment by smorovic** [comment]
+1

**Comment by jfernan2** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by slava77** [comment]
+reconstruction

for https://github.com/cms-sw/cmssw/pull/33876	093bbf1
- code changes in reco are limited to a test config in EventFilter/CSCRawToDigi/test/testCSCDigi2Raw_cfg.py
- jenkins tests pass and comparisons with the baseline show no relevant differences in reco quantities (there are some diffs in L1TEMU)

**Comment by qliphy** [comment]
+1

**Pull request merged**
