### PR TITLE
[10_2_X] OfflineDQM: Offline L1T muon DQM bugfix for muon resolution plots CMSLITDPG-763

### PR DESCRIPTION
**Pull request by stahlleiton**
Backport of https://github.com/cms-sw/cmssw/pull/24870

### CODE REVIEW

**Comment by thomreis** [comment]
+1

**Comment by thomreis** [comment]
please test

error looks unrelated to the code changes.

**Comment by andrius-k** [comment]
+1

**Comment by andrius-k** [comment]
Hi @stahlleiton, as 10_2 is no longer being used maybe this PR should be closed?

**Comment by fabiocos** [comment]
@rekovic @thomreis ping

**Comment by thomreis** [comment]
Hi @fabiocos 
If no data is processed anymore with 10_2 this PR is not needed anymore. @stahlleiton please close it.

**Comment by fabiocos** [comment]
@thomreis pp data taking is over and for HI 10_3_X is used. Of course MC production is ongoign as well as analysis, but you do not need this for those activities, right? So I would just close it.

**Comment by thomreis** [comment]
Agreed.

**Pull request closed without merging**
