### PR TITLE
CTPPS: pixels geometry + geometry refactoring (9_2_X)

### PR DESCRIPTION
**Pull request by forthommel**
backport of #19922 

This PR introduces the CTPPS pixel detector geometry description, along with several improvements in the overall CTPPS geometry definition code:
*  the `TotemRPGeometry` object is now renamed `CTPPSGeometry` to fit the new naming of all objects used in RP info reconstruction
    a major cleanup of -now- outdated and unused geometry/alignment objects
    no differences expected in the standard processing outputs
    pixels geometry central in the foreseen reconstruction algorithms

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
+1
- Identical to #19922 in the master
- Reco part of this PR is rather technical
- No difference in the results of the jenkins tests, as expected

**Comment by ianna** [comment]
+1

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by perrotta** [comment]
+1
- Identical to #19922 in the master: also here reco is fine with the latest changes
- Reco part of this PR is rather technical
- No difference in the results of the jenkins tests, as expected

**Comment by forthommel** [comment]
@dmitrijus

**Comment by dmitrijus** [comment]
+1

**Comment by forthommel** [comment]
Cherry-picked all recent developments introduced in #19922 after review.

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by perrotta** [comment]
+1
- Latest additions look correct, although, for some reason, a couple of code-checker related adjustments in RecoCTPPS/TotemRPLocal/plugins/TotemRPLocalTrackFitter.cc and RecoCTPPS/TotemRPLocal/plugins/TotemRPUVPatternFinder.cc were not picked up in the 92X backport. This is not an issue here, but the fact that the CTPPS code in the master and in 92X diverges can give difficulties in possible  forthcoming different backports.
- Same comments as in https://github.com/cms-sw/cmssw/pull/20018#issuecomment-320437655 still hold

**Comment by forthommel** [comment]
An extra rebase was apparently needed to have all the `fillDescriptions` static methods integrated in #19831 (but did not raise any conflict, hence I guess the github API did not complain at the PR level)... Strange indeed!

**Comment by perrotta** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by perrotta** [comment]
+1
Same as https://github.com/cms-sw/cmssw/pull/20018#issuecomment-322798091

**Comment by perrotta** [comment]
hold
(Until at least everything is tested in 930pre4 RelVals, and the developments allowed by this code are also ready for 92X, since there are massive changes in the prodiction code)

**Comment by ianna** [comment]
@perrotta - any news on this PR?

**Comment by perrotta** [comment]
unhold

**Comment by slava77** [comment]
it seems too early for unhold considering that the primary local reco PR was merged in master only less than a day ago.
The earlier discussion was that the backport will be made in one go/one PR including the pixel reco.

**Comment by perrotta** [comment]
Yes, that was also my understanding. There is not even a backport for  
the recHits yet.
(Well, the equivalent this PR was merged in pre4 already: yesterday it  
was merged the pixel recHit PR, instead)

I simply un-holded because I think that it is fine for reco as such,  
and the discussion about whether and when to backport has to be moved  
to the ORP now.

If you think that reco should hold it itself till the local reco is  
digested in 93X (and the backport submitted in 92X), please feel free  
of holding it back.

Slava Krutelyov <notifications@github.com> ha scritto:

**Comment by slava77** [comment]
hold

there is no need for this PR by itself in 92X without the pixel local reco.
It was OK to stage into multiple PRs in the master branch.

**Comment by forthommel** [comment]
Hello @slava77,
Are you suggesting us to cherry-pick the developments merged in `master` through #20216 into this PR?

**Comment by slava77** [comment]
@forthommel 
perhaps it's time to close this PR

**Pull request closed without merging**
