### PR TITLE
Microstate monitoring update (DAQ) 80X

### PR DESCRIPTION
**Pull request by smorovic**
Fixes to microstate monitoring in DAQ EvF:
- Global EoL microstate state should not be set in initialization stage.
- GlobalEoL should only be set for thread/stream after postStreamEndLumi
- Per thread/stream breakdown of some states for input state monitoring (to analyze the effective impact of limitations imposed by the multithreading model).
- Two states removed, two new input states added

PR also includes new test mode for FedRawDataSource used to fill ramdisk in fakeBU mode looping over events from raw files.

Backport of #15955

### CODE REVIEW

**Comment by cvuosalo** [comment]
backport #15955

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
+1

For #15956 806b470659135ecf141d86f742959d34ef86643a

For the DAQ, fixes for microstate monitoring. There should be no change in offline monitored quantities.

#15955 is the 81X version of this PR, and it has already been approved by Reco.

The code changes are satisfactory, and Jenkins tests against baseline CMSSW_8_0_X_2016-09-21-2300 show no significant differences, as expected.

**Comment by emeschi** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
