### PR TITLE
Speed up b and c jet energy regression in NanoAOD with ONNXRuntime

### PR DESCRIPTION
**Pull request by hqucms**
Requires: https://github.com/cms-data/PhysicsTools-NanoAOD/pull/13

---

#### PR description:

This PR changes the b and c jet energy regression in NanoAOD from TF to ONNXRuntime. Batch evaluation is also implemented to run inference on all jets in an event together instead of jet-by-jet. Overall speed-up is 3-4x.

On a TTBar hadronic sample:

[before]
```
TimeReport   0.006052     0.006052     0.006052  bjetNN
TimeReport   0.005448     0.005448     0.005448  cjetNN
```

[after]
```
TimeReport   0.001650     0.001650     0.001650  bjetNN
TimeReport   0.001485     0.001485     0.001485  cjetNN
```

#### PR validation:

Tested on UL NanoAODv9 workflows and obtained identical output values for b and c jet energy regression.

### CODE REVIEW

**Comment by gouskos** [comment]
please test

**Comment by mariadalfonso** [comment]
test parameters:

pull_request = cms-data/PhysicsTools-NanoAOD#13

**Comment by mariadalfonso** [comment]
enable profiling

**Comment by mariadalfonso** [comment]
please test

**Comment by hqucms** [comment]
@mariadalfonso Yes, forgot again to check if the collection is empty for batch eval. Now fixed in https://github.com/cms-sw/cmssw/pull/35698/commits/b287a26399f409ccb381e6fea5ac9efb45e912e3.

**Comment by mariadalfonso** [comment]
please test

**Comment by mariadalfonso** [comment]
Looking at the CPU time there is an (small) improvement

total  581.4 --> 556.0 (-5%)
"others" 285.9 --> 314.6 (+10%)
"phyToo" 222.5 --> 166.7  (-25%)

IB_16oct
IB_16oct+PR

**Pull request merged**
