### PR TITLE
Avoid NaNs in SimClustering [91X]

### PR DESCRIPTION
**Pull request by kpedro88**
Backport of #19997

### CODE REVIEW

**Comment by kpedro88** [comment]
assign upgrade

**Comment by kpedro88** [comment]
please test

**Comment by kpedro88** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Comment by kpedro88** [comment]
@slava77 @perrotta please sign
@davidlange6 this is needed very urgently for TDR production

**Comment by kpedro88** [comment]
please test

**Comment by kpedro88** [comment]
+1

**Comment by perrotta** [comment]
+1
- Identical to #19997 in master
- Rather technical: the code reflects what it is intended to do
- No difference expected in standard outputs (only once in a while on a very large stats, according to the description notes): the only ones observed in jenkins outputs are for simulated events with PU, where a different sequence of PU files was used wrt baseline

**Comment by perrotta** [comment]
+1
- Technical
- No differences expected in jenkins tests, no differences observed

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
