### PR TITLE
modernize `SiStripPayloadMapTableCreator`

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

Technical, part of the migrations in https://github.com/cms-sw/cmssw/issues/36404.
Profited to clean-up headers, unused methods and d'tor. 

#### PR validation:

`cmssw` compiles

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

### CODE REVIEW

**Comment by mmusich** [comment]
test parameters:
   * addpkg = CondTools/SiStrip

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by tvami** [comment]
+db

**Comment by qliphy** [comment]
+1

**Pull request merged**
