### PR TITLE
Utilities/StaticAnalyzers: Update generation of EventSetupRecord::get report.

### PR DESCRIPTION
**Pull request by gartung**
Update script for generating ESR::get report.
Update regex used for finding top level functions and ESR::get function calls.
Update module_to_package.yaml with mapping used in circles graph
Check if the module is in modules_in_ib.txt

Verified that report generated by the script has expected modules in it.

### CODE REVIEW

**Comment by gartung** [comment]
please test

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
