### PR TITLE
update tracking dqm@hlt

### PR DESCRIPTION
**Pull request by mtosi**
this PR (as PR #12481 ) is meant for synchronising the tracking HLT DQM to the offline one

### CODE REVIEW

**Comment by VinInn** [comment]
@cmsbuild, please test

**Comment by VinInn** [comment]
@mtosi,  I think that PR in 7_6 are automatically ported to 8_0_0

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
@mtosi 
this one doesn't merge anymore as expected after the merging of  #11889 
could you please rebase it?
thanks,
F.

**Comment by deguio** [comment]
-1

**Comment by davidlange6** [comment]
Seems obsolete. Closing. Reopen if important after rebasing

**Pull request closed without merging**
