### PR TITLE
backport of EM enrichment filters parameters tracking PR #24754

### PR DESCRIPTION
**Pull request by andreh7**
This is essentially a request for a backport of #24754 to CMSSW_10_2_X.

This pull request has the same commits as #24754 has on top of master but applied to CMSSW_10_2_X  as of this morning (07d0979a6e7).

### CODE REVIEW

**Comment by efeyazgan** [comment]
please test

**Comment by andreh7** [comment]
I will fix the unused variable error (https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-24865/31069/clang-new-warnings.log)
but I can't fix problems with accessing RAW data files on EOS such as this one: https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-24865/31069/runTheMatrix-results/4.22_RunCosmics2011A+RunCosmics2011A+RECOCOSD+ALCACOSD+SKIMCOSD+HARVESTDC/step2_RunCosmics2011A+RunCosmics2011A+RECOCOSD+ALCACOSD+SKIMCOSD+HARVESTDC.log

**Comment by alberto-sanchez** [comment]
please test

**Comment by efeyazgan** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
