### PR TITLE
Fixing 81X relval alcareco in express test

### PR DESCRIPTION
**Pull request by mmusich**
Putting back in the matrix `SiStripCalZeroBias+TkAlMinBias+DtCalib+Hotline+LumiPixelsMinBias` that are otherwise not tested anywhere.

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
@hengne do you foresee to port #13516 also in 81X? otherwise can you please sign this one?

**Comment by hengne** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
