### PR TITLE
Switch to Geant4 thermal neutron physics

### PR DESCRIPTION
**Pull request by civanch**
#### PR description:
Historically in CMSSW thermal neutron physics was constructed by custom class. With Geant4 10.6 and beyond similar physics constructor exist in Geant4 library. In this PR a switch to the Geant4 class is done, which fix problem of adaptation of the new Geant4 version 10.6ref10.

This PR fixes #6356 

#### PR validation:
private

#### if this PR is a backport please specify the original PR and why you need to backport 
no

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by civanch** [comment]
urgent

**Comment by qliphy** [comment]
+1

**Comment by slomeo** [comment]
@civanch : just a curiosity, are there physical diferences (i.e different models for neutrons, etc etc) between CMSThermalNeutrons and G4ThermalNeutrons?

**Pull request merged**
