### PR TITLE
Fixes in L1T Calo packers - useful for data taking - 81x

### PR DESCRIPTION
**Pull request by rekovic**
Fixed EG Unpacker and EtSums Unpacker and Emulation to agree with packer. 
Now Unpacked and Re-emulated L1T decisions in HLT are in agreement.
Should use this in data taking immediately.

### CODE REVIEW

**Comment by rekovic** [comment]
please test

**Comment by rekovic** [comment]
Can somebody ping jenkins for me, please.

**Comment by Martin-Grunewald** [comment]
please test

**Comment by fwyzard** [comment]
please test

**Comment by rekovic** [comment]
@davidlange6   Looking at the log
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-13787/11987/runTheMatrix-results/matrixTests.log 
the failing test seem to be
<pre>
(das_client.py --cache das-cache.file --limit 0 --query 'file dataset=/Cosmics/Run2011A-v1/RAW run=160960 site=T2_CH_CERN') | sort -u > step1_dasquery.log  2>&1
</pre>
 Running it locally simply creates a list of files.   What am I missing?

**Comment by davidlange6** [comment]
please test

das failed. It happens. not much jenkins can do about it - so lets rerun the tests.

**Comment by rekovic** [comment]
ok. thanks.

**Comment by Martin-Grunewald** [comment]
please test

**Pull request merged**
