### PR TITLE
Added overflow bin to all the plots (muon validation)

### PR DESCRIPTION
**Pull request by cedricpri**
Overflow bin added to all the validation plots.

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
please test
Another time out unrelated to the PR itself

**Comment by boudoul** [comment]
Dear @cedricpri , could you please make the title more explicit ? We can't guess from this title  if you are talking about Hcal, Tracker, Muons (CMSSW is shared among many subsystems...)

@vazzolini, @kmaeshima, @schneiml, @dmitrijus, @jfernan2 : In general, could you please pay attention to the title when reviewing a PR ? Thank you

**Comment by cedricpri** [comment]
Sorry about that, next time I will choose a better title. It only concerns the muon validation code. I have just updated the title.

**Comment by boudoul** [comment]
thanks @cedricpri ! appreciated

**Comment by andrius-k** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
