### PR TITLE
CTPPS: empty alignment fix - backport of #15675

### PR DESCRIPTION
**Pull request by grzanka**
Backport of #15675 from 810X version

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
backport of #15675

@smuzaffar does the bot require a separate message to apply the "backport" label?

**Comment by smuzaffar** [comment]
@slava77 , no just saying "backport of #PR" is enough (in first line)

**Comment by ianna** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
