### PR TITLE
[RFC] Removal of 'evtgenlhc' external (EvtGenLHC91, EvtGenLHCInterface)

### PR DESCRIPTION
**Pull request by davidlt**
The 'evtgenlhc' external is considered old according to Roberto
Covarelli and we should remove it.

Signed-off-by: David Abdurachmanov David.Abdurachmanov@cern.ch

### CODE REVIEW

**Comment by davidlt** [comment]
Note, it's plugin removal. The only way to test this is to add this to IB.

**Comment by smuzaffar** [comment]
@cmsbuild, please test 

@davidlt, we should be able to test plugin removal in dev area ..... that is why we have poisoned plugin concept.

**Comment by davidlt** [comment]
@smuzaffar wasn't it always getting plugin from AFS even if you delete it?

**Comment by smuzaffar** [comment]
No, for each checked out package (in dev area) scram creates poisoned plugin cache. so if a plugin is removed then plugin manager should complain if someone tries to load it

**Comment by covarell** [comment]
+1

**Comment by davidlt** [comment]
Apparently 521.0 workflow is now working (something changed in a month), but still tested on machine with access to CVMFS, all fine: `1 1 1 tests passed, 0 0 0 failed`. Removal of `evtgenlhc` does not create problems to 521.0 workflow.

**Comment by davidlange6** [comment]
+1

**Comment by degano** [comment]
@davidlt done in cms-sw/cmsdist#1871

**Pull request merged**
