### PR TITLE
Backport from 76X (#10907,#10974,#11046)

### PR DESCRIPTION
**Pull request by ryonamin**
For 74X.

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1
provided it passes the tests

**Comment by davidlange6** [comment]
@ryonamin  - this PR no longer merges - could you rebase and also change the title to be more meaningful. Thanks!

**Comment by ryonamin** [comment]
I have made a new PR (#11395) for these changes.
Thank you in advance for your checking!

**Pull request closed without merging**
