### PR TITLE
New E/gamma pat::Electron and pat::Photon modifiers

### PR DESCRIPTION
**Pull request by Sam-Harper**
I wish to embed VID & HEEP V7.0 information into pat::Electrons (and by extension pat::Photons). 

This information is stored as a set of ValueMaps. Currently there is 
EGExtraInfoModifierFromFloatValueMaps 
EGExtraInfoModifierFromIntValueMaps 

in RecoEgamma/EgammaTools which do exactly what I need for floats and ints, however I need it for other data types. I diffed EGExtraInfoModifierFromIntValueMaps and EGExtraInfoModifierFromFloatValueMaps to ensure that the only differences were due to types. 

As such I propose replacing EGExtraInfoModifierFromIntValueMaps and EGExtraInfoModifierFromFloatValueMaps with a templated class EGExtraInfoModifierFromValueMaps which can read an arbitrary type of ValueMap and write that value as another arbitrary type to the pat::Electron,pat::Photon. The option to write it as an arbitrary type is necessary to for the bool and uints as pat::PATObject has no way to store these values. I could have forced them to always store as an int but I dislike that as it violates the principle of least surprise and also if in the future pat::PATObject gains the ability to store bools and uints, this makes it easy to adapt to that case while retaining backwards compatibility. 

Note, EGExtraInfoModifierFromIntValueMaps and EGExtraInfoModifierFromIntValueMaps are part  of the miniAOD sequence however I see no changes when the new class. As it simply stores the value in pat::PATObject::userFloat and pat::PATObject::userInt, it should either clearly work or not. 

Now I hope I have named the files correctly and they are both in the correct location, I wasnt sure exactly what CMS filenaming policy is here for templates classes. 

So far E/gamma has been informed about my request but as its the start of the year, I havent heard back from them yet.

### CODE REVIEW

**Comment by slava77** [comment]
``` however I need it for other data types ```
which other data types will you need and why can't they instead be the float and int which are already supported?
I doubt we will extend the userInt/userFloat to have also userBool,userShort,userUint etc.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by Sam-Harper** [comment]
Hi Slava,

I need to be able to read value maps of uint, bool and vid::CutFlowResult. 

The class by default attempts to add the object to userData however when its writing an int or float, it uses userFloat or userInt through specialisations for those types.

Thus I can store my bool as a userInt, I read the edm::ValueMap<bool> and then write it to the pat::Electron as a userInt.

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/17138 8ce0049
- code changes are in line with the description
- jenkins tests pass and comparisons with baseline show no differences as expected 
- paranoia check: copy of jenkins outputs for 136.731 and branch-to-branch comparison shows no changes in values based on compressed size

**Pull request merged**
