### PR TITLE
`SiStripHitEfficiency` PCL workflow, take into account modules with `FEDErrors`

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

When using the DQM files produced by the `SiStripHitEfficiency` PCL in 2022 data, it was noticed that not all the modules that should be masked with the `SiStripQuality` are effectively masked within the DQM workflow, when comparing with the traditional calibrations-tree based workflow.
The issue has been traced down on the usage of the modules affected by `FEDErrors` in the  computation of the efficiency.
In PR https://github.com/cms-sw/cmssw/pull/38592 a mechanism to count the `FEDErrors` per module (via commit https://github.com/cms-sw/cmssw/pull/38592/commits/44999ca0086ab0a28320bc9c815c68bfa94c5aef ) was introduced since at the harvesting step level it's not possible to access directly at the per-event `FEDErrors` edm collection. This entailed populating a `TkHistoMap` with the occupancy of modules in FEDError per event, but this approach had two problems:
   * the filling of the map occurred in the `endJob` transition of `StripHitEfficiencyWorker` (that in a `DQMEDAnalyzer` is not run by the framework, resulting in empty maps cf https://tinyurl.com/2p5tdgqs)
   * secondly the information was never propagated to the `SiStripHitEfficiencyHarvester` such that those modules could be excluded from the list of inefficient ones.
   
This PR solves the issue by changing the `SiStripHitEffData` ancillary `struct` and its usage in the classes of the `SiStripHitEfficiency` PCL workflow. A somewhat arbitrary threshold of 75% of the events is used to flag modules that have problems with FEDErrors, permanently excluding them from the computation.

Finally I profit of this to transform a relic thread-unsafe `cout` to the message logging system in commit c044bae8d9a0fc3c2f586b88b07cb0206ef30f79.

#### PR validation:

Run the following commands:

```console
cmsDriver.py stepReAlCa -s ALCA:PromptCalibProdSiStripHitEff --conditions 124X_dataRun3_Express_v5 --scenario pp --data --era Run3 --datatier ALCARECO --eventcontent ALCARECO --processName=ReAlCa -n 100000 --dasquery='file dataset=/StreamExpress/Run2022D-SiStripCalMinBias-Express-v2/ALCARECO run=357898' --nThreads=4
``` 

followed by:

```console
cmsDriver.py stepHarvest -s ALCAHARVEST:SiStripHitEff --conditions 124X_dataRun3_Express_v5 --scenario pp --data --era Run3 --filein file:PromptCalibProdSiStripHitEff.root -n -1
```

with this branch and without it and observed the following features:
   - the `FEDErrorTkDetMaps` folder now contains full plots (as can be checked at https://tinyurl.com/2z7nrg9a after logging with ` ssh -NL 8060:localhost:8060 <USER>@lxplus724.cern.ch`)
   - some regions in TEC that were contributing to the inefficiency (because in FED Error) are now correctly excluded:
   
| Name     | Pre-fix | Post-fix |
| ---           | ---       |  ---       |
| Efficiency Map |  image | image |
| Inefficient Modules       |   image | image |
  
#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Not a backport, but will need to be backported to CMSSW_12_5_X and CMSSW_12_4_X (for data-taking purposes)

attn:
@jlagram @mdelcourt @robervalwalsh

### CODE REVIEW

**Comment by mmusich** [comment]
type bug-fix

**Comment by mmusich** [comment]
test parameters:
   * workflows = 1001.2, 1001.3

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by francescobrivio** [comment]
+alca

 - PR in line with description
 - differences in the tests (a part from usual MTD and MessageLogger) are only in the `AlCaReco/SiStripHitEfficiency/FEDErrorTkDetMaps` directory as expected from this PR

**Comment by perrotta** [comment]
+1

**Pull request merged**
