### PR TITLE
Modernize GEMGeometryESModule and ME0GeometryESModule

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

- Move header contents to source file
- Use ESGetToken (part of #26584)
- Use consistent member variable naming following the code rules

#### PR validation:

Code compiles.

### CODE REVIEW

**Comment by makortel** [comment]
@Dr15Jones The ES-consumes migration was indeed more pleasant with #26862.

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
The failure is
```
23-May-2019 18:01:55 CEST  Initiating request to open file grep: /store/hidata/HIRun2011/HIMinBiasUPC/RAW/v1/000/182/124/0011F55A-8F13-E111-A987-003048F118C6.root
----- Begin Fatal Exception 23-May-2019 18:01:55 CEST-----------------------
An exception of category 'FileOpenError' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing input source of type PoolSource
   [2] Calling RootFileSequenceBase::initTheFile()
Exception Message:
Cannot open file 'grep: /store/hidata/HIRun2011/HIMinBiasUPC/RAW/v1/000/182/124/0011F55A-8F13-E111-A987-003048F118C6.root'
   Additional Info:
      [a] Input file grep: /store/hidata/HIRun2011/HIMinBiasUPC/RAW/v1/000/182/124/0011F55A-8F13-E111-A987-003048F118C6.root could not be opened.
----- End Fatal Exception -------------------------------------------------
```

step1_dasquery.log has
```
grep: /store/hidata/HIRun2011/HIMinBiasUPC/RAW/v1/000/182/124/0011F55A-8F13-E111-A987-003048F118C6.root
/store/hidata/HIRun2011/HIMinBiasUPC/RAW/v1/000/182/124/0227BDCE-8B13-E111-86E2-003048F117F6.root
/store/hidata/HIRun2011/HIMinBiasUPC/RAW/v1/000/182/124/0229B820-9713-E111-A59F-0025B32035A2.root
...
/store/hidata/HIRun2011/HIMinBiasUPC/RAW/v1/000/182/124/129A5F0E-9013-E111-A0CA-002481E0CC00.root
write error
```

So some sort of transient error?

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by kpedro88** [comment]
@makortel there's a conflict, can you rebase? (might need to wait for the next IB)

**Comment by makortel** [comment]
Thanks @kpedro88, I'll rebase after the next IB.

**Comment by dildick** [comment]
@makortel Are you planning to modernize the similar module ME0GeometryESModule? Thanks!

**Comment by makortel** [comment]
@dildick Thanks for pointing out that module, somehow I missed it. So my answer is yes, I'll do the same for ME0GeometryESModule as well.

**Comment by makortel** [comment]
Rebased and modernized ME0GeometryESModule.

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by kpedro88** [comment]
+upgrade

**Comment by ianna** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Pull request merged**
