### PR TITLE
Update and fix of DQM plots for PPS timing detectors

### PR DESCRIPTION
**Pull request by grzanka**
#### PR description:

This PR provides fix for the wrongly produced plot of correlation between tracks in PPS timing detectors (for 220cyl and 220nr_hr). Fixed plot looks like this:
image

Previous code contained bug related to assignment of a track to given pot.

The code as well includes several cosmetic adjustment of the plot binning and titles.

Moreover leading and trailing edge plots were added to "per place" plot group.

#### PR validation:

Manually running script which produced DQM plot from the PromptReco ZeroBias files sample `/store/data/Run2024B/ZeroBias/AOD/PromptReco-v1` for run for run 379154 :

```python
from Configuration.Eras.Era_Run3_cff import Run3

process = cms.Process('RECODQM', Run3)

# command  line options
import FWCore.ParameterSet.VarParsing as VarParsing
options = VarParsing.VarParsing ('analysis')
options.inputFiles= 'file:input.root'
options.maxEvents = -1 
options.parseArguments()

process.maxEvents = cms.untracked.PSet(
    input = cms.untracked.int32(options.maxEvents)
)

process.verbosity = cms.untracked.PSet( input = cms.untracked.int32(-1) )

# minimum of logs
process.MessageLogger = cms.Service("MessageLogger",
    cerr = cms.untracked.PSet(
        threshold = cms.untracked.string('INFO')
    )
)

# import of standard configurations
process.load('Configuration.StandardSequences.Services_cff')
process.load('FWCore.MessageService.MessageLogger_cfi')
process.load('Configuration.EventContent.EventContent_cff')
process.load('Configuration.StandardSequences.FrontierConditions_GlobalTag_cff')

# load DQM framework
process.load("DQM.Integration.config.environment_cfi")
process.dqmEnv.subSystemFolder = "CTPPS"
process.dqmEnv.eventInfoFolder = "EventInfo"
process.dqmSaver.path = ""
process.dqmSaver.tag = "CTPPS"

# raw data source
process.source = cms.Source("PoolSource",
    fileNames = cms.untracked.vstring(cms.untracked.vstring(options.inputFiles)),
)

from Configuration.AlCa.GlobalTag import GlobalTag
process.GlobalTag = GlobalTag(process.GlobalTag, 'auto:run3_data', '')

# local RP reconstruction chain with standard settings
process.load("RecoPPS.Configuration.recoCTPPS_cff")

process.load("DQM.Integration.config.FrontierCondition_GT_cfi")

# CTPPS DQM modules
process.load("DQM.CTPPS.ctppsDQM_cff")
process.ctppsDiamondDQMSource.excludeMultipleHits = cms.bool(True)
process.ctppsDiamondDQMSource.plotOnline = cms.untracked.bool(True)
process.ctppsDiamondDQMSource.plotOffline = cms.untracked.bool(True)
process.path = cms.Path(
    process.ctppsDQMCalibrationSource*
    process.ctppsDQMCalibrationHarvest
)

process.end_path = cms.EndPath(
    process.dqmEnv +
    process.dqmSaver
)

process.schedule = cms.Schedule(
    process.path,
    process.end_path
)
```

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by grzanka** [comment]
I've created a backport to 14_0_X here https://github.com/cms-sw/cmssw/pull/44856

**Comment by mmusich** [comment]
type ctpps, bugfix

**Comment by antoniovilela** [comment]
@cms-sw/dqm-l2 
Please sign the master PR before the backport.

**Comment by antoniovilela** [comment]
> @cms-sw/dqm-l2
> Please sign the master PR before the backport.

ping @cms-sw/dqm-l2

**Comment by tjavaid** [comment]
+1

- P5 tests OK with its `14_0_X` backport #44856
- @grzanka could you please fix the description for "PSS timing detectors" -> "PPS timing detectors". Thanks!

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
