### PR TITLE
premixing : digi step : replace postls1 customisation functions with run2 era

### PR DESCRIPTION
**Pull request by lveldere**
rebase of #13072 

postLS1 customisation functions are no longer necessary for premixing:
Indeed, the customisation function in

```
SLHCUpgradeSimulations/Configuration/python/postLS1CustomsPreMixing.py
```

takes the following actions
- the deprecated customisePostLS1 function is called. 
  This is now replaced by adding the appropriate era option to the digi step in relval_steps.py
- the customisation function in Configuration/python/muonCustomsPreMixing.py is called
  This function has actually zero effect
  - line 5 is taken care of by the eras
  - line 8 and 9 are redundant (the correct settings are loaded in the premix digi step anyway)
  - line 13,14,17 and 18 have no effect on the digi step

Tests: workflows 250200,500200 run properly.

@mdhildreth

### CODE REVIEW

**Comment by lveldere** [comment]
please test

**Comment by fabozzi** [comment]
shouldn't be "--era" at line 887?
https://github.com/lveldere/cmssw/blob/premix-noPostLS1/Configuration/PyReleaseValidation/python/relval_steps.py#L887

**Comment by davidlange6** [comment]
@lveldere - @fabozzi makes a correct inquiry. Could you update the PR? Thanks!

**Comment by fabozzi** [comment]
please test

**Comment by lveldere** [comment]
the typo reported by @fabozzi is fixed.

**Comment by lveldere** [comment]
please test

**Comment by fabozzi** [comment]
+1

**Pull request merged**
