### PR TITLE
Add displacedJet PD relval

### PR DESCRIPTION
**Pull request by kfjack**
Add displacedJet PD 2017C relval, enabled EXODisplacedJet Skim.

### CODE REVIEW

**Comment by fabozzi** [comment]
please test workflow 136.804

**Comment by fabozzi** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Comment by davidlange6** [comment]
hi @kfjack - what fraction of the displaced jet dataset should this skim select? 50%?

**Comment by kfjack** [comment]
Hi @davidlange6, according to @jingyuluo, this skim rate is 1-2 Hz.

**Comment by davidlange6** [comment]
could you double check? I ask because the skim output is close to the reco output file size in the test run for the PR.

**Comment by kfjack** [comment]
Sure. Will double check this and get back to this thread!

**Comment by fabozzi** [comment]
Hello, @kfjack @jingyuluo: any update on this? 
Do you plan to move to RAW-AOD output as suggested in PPD meeting?

**Comment by kfjack** [comment]
@fabozzi I noticed there is no pre-defined RAW-AOD event content. I'm restarting a new setup on a newer IB + this PR + addon to the event content definition. Will create another PR soon.

**Comment by jingyuluo** [comment]
Hi @fabozzi  Yes, RAW-AOD is good for us.   
@kfjack Many thanks for helping with this!

**Comment by fabozzi** [comment]
@kfjack Can you please close this? Since it is superceded by PR #20948

**Comment by kfjack** [comment]
Done! Many thanks for the reminder!

Jack

**Pull request closed without merging**
