### PR TITLE
Fix L1T Phase2 EG scale

### PR DESCRIPTION
**Pull request by cerminar**
#### PR description:

The PR fixes the scale problems of L1 EG objects in HGC reported in:

https://hypernews.cern.ch/HyperNews/CMS/get/L1TriggerUpgrades/385/1/1/1/1/1/1/1/1.html

#### PR validation:

canvas(165)
canvas(164)
c_42257b_2
c_42257b_1

### CODE REVIEW

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by kpedro88** [comment]
+upgrade

**Comment by rekovic** [comment]
Thanks @cerminar

**Comment by rekovic** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
