### PR TITLE
Herwig7 2 2 settings update 10 6

### PR DESCRIPTION
**Pull request by Dominic-Stafford**
#### PR description:

Update the Herwig settings blocks so these work with the current version of Herwig. Also update the Powheg+Herwig test to use these blocks, and add tests/examples for Madgraph+Herwig with both mlm and FxFx merging. Will add documentation on how to use these on the Herwig interface twiki: https://twiki.cern.ch/twiki/bin/viewauth/CMS/Herwig7Interface

#### PR validation:

Checked that all three examples work (Powheg example is runTheMatrix workflow 535)

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Backport of #33227 for use in UL production

### CODE REVIEW

**Comment by SiewYan** [comment]
please test

**Comment by qliphy** [comment]
ping @cms-sw/generators-l2

**Comment by SiewYan** [comment]
+1

**Comment by silviodonato** [comment]
Backport of #33227

**Comment by qliphy** [comment]
+1

**Pull request merged**
