### PR TITLE
Add a script to split a CMSSW configuration into individual cfi files

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

This PR adds the necessary hooks under `FWCore/ParameterSet/python`, and a script under `FWCore/ParameterSet/scripts`, to split a CMSSW python configuration into individual *_cfi.py files.

Missing features
  - `SwitchProducer` and `Subprocess` are not supported;
  - `refToPSet`, `SequencePlaceholder` and `TaskPlaceholder` are not handled specifically, but that is probably the correct approach.

#### PR validation:

As a validation, the latest HLT menu has been split into individual modules with `edmConfigSplit`, and combined back together with `edmConfigDump`; the resulting configuration was identical.

### CODE REVIEW

**Comment by fwyzard** [comment]
@Dr15Jones @makortel @wddgit comments are welcome

**Comment by fabiocos** [comment]
please test

**Comment by Dr15Jones** [comment]
@fwyzard my first comment would be to please add tests to the bottom of Config.py. That way you'd also be sure `Tasks` function :) .

**Comment by Dr15Jones** [comment]
@fwyzard I'm unclear as to the use case you are wanting to solve?

**Comment by fwyzard** [comment]
> @fwyzard my first comment would be to please add tests to the bottom of Config.py. That way you'd also be sure `Tasks` function :) .

Sure, I'll see how to add those.


> @fwyzard I'm unclear as to the use case you are wanting to solve?

In multiple occasions in the past years, and recently working on the GPU reconstruction and on the Phase 2 HLT, I had the need to break a configuration into its component pieces: modules, esmodules, paths & sequences, etc.

For example, keeping a separate set of cfi fiiles in a git repository could be an alternative to ConfDB...

I plat to add few options to the script:
  - generate the main cfg as a file instead of to standard output
  - generate all cfi files in a subdirectory
  - generate the cfi files in a different subdirectory per type (modules vs esmodules vs sequences etc.) if I can get the resulting python fragments to work

Once caveat so far: parsing the lot of cfi files is much slower than parsing the original configuration; eventually I will try to have a look at where the extra time gets spent.

**Comment by fwyzard** [comment]
@fabiocos, why did you close this PR ?

**Comment by fabiocos** [comment]
@fwyzard strange, I did not do explicitly that I recall. There was an overlap with #27399 which I merged , but it was not more than one hour ago, and I do not see why it should have closed the PR (at most caused a conflict).

**Comment by fabiocos** [comment]
not even a conflict...

**Comment by kpedro88** [comment]
@fwyzard what is the status of this PR?

**Comment by fwyzard** [comment]
It's open and targeting the current development branch.

**Comment by fabiocos** [comment]
@fwyzard I guess the latest update was just a rebase, as it is the code does not seem functional yet:

```
13:32 cmsdev25 7647> cmsDriver.py step3  --conditions auto:phase1_2018_realistic -n 10 --era Run2_2018 --eventcontent RECOSIM,MINIAODSIM,DQM --runUnscheduled  -s RAW2DIGI,L1Reco,RECO,RECOSIM,EI,PAT,VALIDATION:@standardValidation+@miniAODValidation,DQM:@standardDQM+@ExtraHLT+@miniAODDQM --datatier GEN-SIM-RECO,MINIAODSIM,DQMIO --geometry DB:Extended --filein  file:step2.root  --fileout file:step3.root --no_exec
RAW2DIGI,L1Reco,RECO,RECOSIM,EI,PAT,VALIDATION:@standardValidation+@miniAODValidation,DQM:@standardDQM+@ExtraHLT+@miniAODDQM
We have determined that this is simulation (if not, rerun cmsDriver.py with --data)
with DB:
entry file:step2.root
Step: RAW2DIGI Spec: 
Step: L1Reco Spec: 
Step: RECO Spec: 
Step: RECOSIM Spec: 
Step: EI Spec: 
Step: PAT Spec: 
Step: VALIDATION Spec: ['@standardValidation', '@miniAODValidation']
@standardValidation+@miniAODValidation in preparing validation
Step: DQM Spec: ['@standardDQM', '@ExtraHLT', '@miniAODDQM']
Traceback (most recent call last):
  File "/build/fabiocos/110X/27305/CMSSW_11_0_X_2019-10-10-2300/bin/slc7_amd64_gcc820/cmsDriver.py", line 56, in <module>
    run()
  File "/build/fabiocos/110X/27305/CMSSW_11_0_X_2019-10-10-2300/bin/slc7_amd64_gcc820/cmsDriver.py", line 28, in run
    configBuilder.prepare()
  File "/build/fabiocos/110X/27305/CMSSW_11_0_X_2019-10-10-2300/python/Configuration/Applications/ConfigBuilder.py", line 2188, in prepare
    self.pythonCfgCode += dumpPython(self.process,path)
  File "/build/fabiocos/110X/27305/CMSSW_11_0_X_2019-10-10-2300/python/Configuration/Applications/ConfigBuilder.py", line 95, in dumpPython
    return "process."+name+" = " + theObject.dumpPython("process")
  File "/build/fabiocos/110X/27305/CMSSW_11_0_X_2019-10-10-2300/python/FWCore/ParameterSet/SequenceTypes.py", line 280, in dumpPython
    s = self.dumpPythonNoNewline(options)
  File "/build/fabiocos/110X/27305/CMSSW_11_0_X_2019-10-10-2300/python/FWCore/ParameterSet/SequenceTypes.py", line 286, in dumpPythonNoNewline
    s =self._seq.dumpSequencePython(options)
  File "/build/fabiocos/110X/27305/CMSSW_11_0_X_2019-10-10-2300/python/FWCore/ParameterSet/SequenceTypes.py", line 168, in dumpSequencePython
    itemDump = item.dumpSequencePython(options)
  File "/build/fabiocos/110X/27305/CMSSW_11_0_X_2019-10-10-2300/python/FWCore/ParameterSet/SequenceTypes.py", line 305, in dumpSequencePython
    return _Labelable.dumpSequencePython(self, options)
  File "/build/fabiocos/110X/27305/CMSSW_11_0_X_2019-10-10-2300/python/FWCore/ParameterSet/Mixins.py", line 541, in dumpSequencePython
    if options.isCfg:
AttributeError: 'str' object has no attribute 'isCfg'
```

**Comment by fwyzard** [comment]
Yes, I'm still working on the tool.

**Comment by fwyzard** [comment]
@cmsbuild please test

**Comment by fwyzard** [comment]
> @fwyzard my first comment would be to please add tests to the bottom of Config.py. That way you'd also be sure `Tasks` function :) .

@Dr15Jones , I have been looking into this, but it's not clear to me how I could do that, since the functionality I am working on is to create N files starting from a single python configuration.
If I add the tests inside `Config.py`, how / where do I end up creating the fragments ?

**Comment by fwyzard** [comment]
Ah, I see.

Yes, I think I could put in `FWCore/ParameterSet/python/Config.py` a function that returns a `dict(filename, content)`, and then in the `edmConfigSplit` script use that to create the actual files.

Do you think this would be reasonable ?

**Comment by fwyzard** [comment]
P.S. with the latest changes I am able to "split" 30 out of 33 workflow from the limited runTheMatrix.py... I'll work on the last 3 and then move on to the unit tests.

**Comment by Dr15Jones** [comment]
> Do you think this would be reasonable ?
Sounds like that would work. Thanks.

**Comment by fwyzard** [comment]
About the last three failing cases:
  - one seems due to a real problem in the configuration, that ends up with `process.None` in one of its Tasks; I've opened #28172 about it;
  - the other is about `_SequenceCollection._collection` being itself a `_SequenceCollection`; I can easily support it, but I am wondering if it is supposed to happen or not ?

**Comment by fabiocos** [comment]
please test

**Comment by fwyzard** [comment]
@cmsbuild please test

**Comment by fwyzard** [comment]
@cmsbuild please test with 28184

**Comment by fabiocos** [comment]
@fwyzard all the O2O tests are failing in the IB as well for unrelated reasons

**Comment by fwyzard** [comment]
@cmsbuild please test with #28184

**Comment by fabiocos** [comment]
@fwyzard from https://github.com/cms-sw/cmssw/pull/27305#issuecomment-542553824 I would say that you are likely conflicting with yourself

**Comment by fwyzard** [comment]
Indeed... I'll fix this after the other is merged!

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by fabiocos** [comment]
code-checks

**Comment by fabiocos** [comment]
please test

**Comment by fwyzard** [comment]
Unfortunately I will not be able to add the unit tests before the end of November (CHEP + holidays...).
Can this be merged as is ?

**Comment by fabiocos** [comment]
@fwyzard fine for me, I will integrate it today, they you may further update it later on

**Comment by fabiocos** [comment]
+1

**Pull request merged**
