### PR TITLE
Phase2-hgx335K The default topology builder file for HGCal is modified and correspondingly all scenarios now use this builder

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Effect of renaming the default topology builder file for HGCal. All phase2 scenaarios now use this builder. 

#### PR validation:

Use the runTheMatrix test workflows 

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

@bsunanda , may be it is possible to have better title of this PR: "Effect of topology" difficult to understand.

**Comment by bsunanda** [comment]
@srimanob Please approve this PR

**Comment by srimanob** [comment]
+Upgrade

**Comment by perrotta** [comment]
+1
- @bsunanda should we also remove the file Geometry/CaloEventSetup/python/HGCalV9Topology_cfi.py as a whole now?

**Pull request merged**
