### PR TITLE
Update autoSkim for 2023 data taking [13_1_X]

### PR DESCRIPTION
**Pull request by youyingli**
#### PR description:

Update new PDs to support the skim for 2023 data taking. The update follows the following:

- [CMSHLT-2596](https://its.cern.ch/jira/browse/CMSHLT-2596) : Split ```JetMET```, ```EGamma``` and ```Muon``` into 2 stream
- [CMSHLT-2707](https://its.cern.ch/jira/browse/CMSHLT-2707) : Move ```HLT_CscCluster``` and ```HLT_L1CSCShower_*``` triggers from ```DisplacedJet``` PD to ```Muon``` PD
- Disappearing Muon skim is added : https://github.com/cms-sw/cmssw/pull/40666
- **Still waiting for LLP Jet skim added and its backport** 

Update the skim workflow to fit the 2023 skim config

#### PR validation:

N/A

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

N/A

### CODE REVIEW

**Comment by kskovpen** [comment]
please test

**Comment by perrotta** [comment]
@kskovpen  @srimanob is there any reason why you only signed the [13_0_X backport](https://github.com/cms-sw/cmssw/pull/41146), and not this PR submitted for master? Can I give your signature for granted also here?

**Comment by kskovpen** [comment]
+pdmv

**Comment by kskovpen** [comment]
> @kskovpen @srimanob is there any reason why you only signed the [13_0_X backport](https://github.com/cms-sw/cmssw/pull/41146), and not this PR submitted for master? Can I give your signature for granted also here?

signed :)

**Comment by perrotta** [comment]
+operations

**Comment by perrotta** [comment]
+1
- @srimanob I take [your signature in the backport PR](https://github.com/cms-sw/cmssw/pull/41146#issuecomment-1502850309) good as well for the identical master version of the same PR

**Comment by perrotta** [comment]
merge

**Pull request merged**
