### PR TITLE
migrate away from deprecated APIs in the DQM subsystem

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

Title says it all, part of the migrations in https://github.com/cms-sw/cmssw/issues/31061 and https://github.com/cms-sw/cmssw/issues/36404.
Removed most of the CMSDEPRECATED_X warnings in the `DQM/Si*` and all in `DQM/Track*` and `DQMOffline/CalibTracker` subsystems from [CMSSW_12_3_CMSDEPRECATED_X_2022-02-21-2300](https://cmssdt.cern.ch/SDT/cgi-bin/showBuildLogs.py/slc7_amd64_gcc10/www/mon/12.3.CMSDEPRECATED-mon-23/CMSSW_12_3_CMSDEPRECATED_X_2022-02-21-2300)

#### PR validation:

`cmssw` compiles

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

### CODE REVIEW

**Comment by jfernan2** [comment]
@mmusich I don't understand the reason but the compiler is throwing now this warning in a line that you have not modified:
/pool/condor/dir_143890/jenkins/workspace/ib-run-pr-tests/CMSSW_12_3_X_2022-02-22-2300/src/DQM/SiStripCommissioningSources/plugins/tracking/SiStripFineDelayHit.h:41:1: warning: SiStripFineDelayHit inherits from edm::EDProducer,edm::EDFilter,edm::EDAnalyzer, or edm::OutputModule [deprecated.edmChecker]

https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-4bf529/22614/llvm-analysis/legacy-mod-sa.txt

**Comment by mmusich** [comment]
@jfernan2 the compiler is not throwing *now* a new warning, that exists already in the IBs, please check: [this log]( https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc7_amd64_gcc10/CMSSW_12_3_CMSDEPRECATED_X_2022-02-21-2300/DQM/SiStripCommissioningSources). 
The reason why you see it there is precisely because I didn't touch that class.

**Comment by jfernan2** [comment]
Well, actually you touched the headers of class SiStripFineDelayHit but not the class itself, but ok. I was just wondering why this warning is still present depsite your changes. Thanks

**Comment by mmusich** [comment]
> I was just wondering why this warning is still present depsite your changes.

well, because it is *still* inherits from edm::EDProducer,edm::EDFilter,edm::EDAnalyzer, or edm::OutputModule (as the message says) :)

**Comment by jfernan2** [comment]
Yes, I understand, indeed in your case EDProducer, but this should still be a valid class to inherit from...
Anyway, thanks for this PR, as usual

**Comment by jfernan2** [comment]
+1

**Comment by mmusich** [comment]
> Yes, I understand, indeed in your case EDProducer, but this should still be a valid class to inherit from...

It should be migrated to one of the thread-efficient types described here: [FWMultithreadedFrameworkModuleTypes](https://twiki.cern.ch/twiki/bin/view/CMSPublic/FWMultithreadedFrameworkModuleTypes)
Coming in the next commit...

**Comment by mmusich** [comment]
@cmsbuild please test.

@jfernan2 now the warning should be gone.

**Comment by jfernan2** [comment]
Thanks a lot!!

**Comment by jfernan2** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
