### PR TITLE
Trim FastjetJetProducer memory (forward port #9203 to 74X)

### PR DESCRIPTION
**Pull request by mark-grimes**
This forward ports some memory improvements in FastjetJetProducer from 6_2_X_SLHC; there are some plots on #9203 with the memory saving.  The 75X port is #9206, I was also advised to port to 74X.
This bit below is just the description copied from the 75X PR:

This forward ports some memory improvements found in 6_2_X_SLHC. At 200 pileup it saved ~70Mb memory, there are plots on #9203. Presumably at lower pileup the savings aren't as good.

Note that this is from empirically checking where the memory was being used - there could be other subclasses of `VirtualJetProducer` that would benefit from a similar fix. I didn't want to touch the `fjClusterSeq_` object in the base class because I didn't know how the other subclasses use it - for `FastjetJetProducer` I can see that it's recreated anew with every event.

At 200 pileup 1/7th of the memory saving was from swapping out the work vectors, and 6/7th was from freeing the `fjClusterSeq_` object.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
@mark-grimes: Is it possible the memory your new code is deleting is still in use? The Jenkins tests are showing widespread differences, for example: https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_7_4_X_2015-05-20-2300+9210/7771/validateJR/all_OldVSNew_TTbarPUwf25202p0/

For #9206 the Jenkins tests showed no differences, but when I ran a test against the same IB, I found a lot of differences. There may be some error in some of the Jenkins tests, and I am still checking my tests to see if I made a mistake, but it is starting to look like your PR might be introducing inconsistent runtime behavior.

**Comment by slava77** [comment]
I wonder if the differences are a result of a change in the GT payloads
(the MVA overwrite is a suspect)

On 5/22/15 12:19 PM, Carl Vuosalo wrote:
> @mark-grimes <https://github.com/mark-grimes>: Is it possible the memory
> your new code is deleting is still in use? The Jenkins tests are showing
> widespread differences, for example:
> https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_7_4_X_2015-05-20-2300+9210/7771/validateJR/all_OldVSNew_TTbarPUwf25202p0/
> 
> For #9206 <https://github.com/cms-sw/cmssw/pull/9206> the Jenkins tests
> showed no differences, but when I ran a test against the same IB, I
> found a lot of differences. There may be some error in some of the
> Jenkins tests, and I am still checking my tests to see if I made a
> mistake, but it is starting to look like your PR might be introducing
> inconsistent runtime behavior.
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cms-sw/cmssw/pull/9210#issuecomment-104719105>.
> 

-- 
***********************************************************************
 Vyacheslav (Slava) Krutelyov
 TAMU: Physics Dept Texas A&M MS4242, College Station, TX 77843-4242
 CERN: 42-R-027
 AIM/Skype: siava16              googleTalk: slava77@gmail.com
 (630) 291-5128  Cell (US)       +41 76 275 7116 Cell (CERN)

-----------------------------------------------------------------------

**Comment by mark-grimes** [comment]
Made static a const as requested on #9206.

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cmsbuild please test
the last round of comparisons got stuck and the last iteration baseline was apparently affected by the temporary GT inconsistency

**Comment by cvuosalo** [comment]
+1

For #9210 780e3107a4ec0a08f76d35783979bd05a7a8d5da

Reduces memory usage by clearing some FastJetProducer objects after they are no longer needed. No change in monitored quantities should occur. #9206 is the 75X version of this PR.

The code changes are satisfactory. Jenkins tests did not work due to temporary problems with global tags. These problems were unrelated to this PR. After the global tags were fixed, tests with workflow 25202.0_TTbar_13 against baseline CMSSW_7_4_X_2015-05-20-2300 using 50 events show no significant differences. Similar tests for #9206 show the same. Memory usage seems to go down very slightly:

CMSSW_7_4_X_2015-05-20-2300
Summary for 50 events (memory in kB)
Max VSIZ 3591.73 on evt 34 ; max RSS 3018.29 on evt 45
Time av 106.819 s/evt   max 143.956 s on evt 18

#9210 
Summary for 50 events
Max VSIZ 3563.73 on evt 34 ; max RSS 2967.52 on evt 45
Time av 96.2555 s/evt   max 152.626 s on evt 13

**Comment by slava77** [comment]
On 5/23/15 1:58 PM, Carl Vuosalo wrote:
> Memory usage seems to go down very slightly

30-50 MB reduction is a lot, actually

**Comment by davidlange6** [comment]
+1

**Pull request merged**
