### PR TITLE
Code to process phase2 version of deepTauID v2p5 [12_6_X]

### PR DESCRIPTION
**Pull request by mbluj**
#### PR description:

This PR adds code for a phase-2 version of DeepTau discriminator; it is a backport of https://github.com/cms-sw/cmssw/pull/40622.
The neural network structure of the new phase-2 version is identical to that of Run-2/3 DeepTau v2p5, therefore code modifications are small. The changes include:
* Adding scaling parameters and working points for the new training;
* A new "year" identifier introduced to separate this new phase-2 training and current Run-2/3 v2p5 (2026 vs 2018);
* The electron input collection used for the new phase2 deepTauID is sum of two collections: `slimmedElectrons` (gsfElectrons in EB) and `slimmedElectronsHGC` (HGCal electrons in endcaps). Notes: 1. The latter collection is called `slimmedElectronsFromMultiCl` in older CMSSW release series (and samples produced with them) which can cause some problems with running on old samples; 2. The same merged electron collection is used by old-style anti-electron tau discriminant for phase-2;

The performance of this new phase-2 DeepTau discriminator is documented in [AN-22-090](https://icms.cern.ch/tools-api/restplus/relay/piggyback/notes/AN/2022/90/files/3/download).

The new data-model was merged to cms-data in the following PR: https://github.com/cms-data/RecoTauTag-TrainingFiles/pull/11

This PR allows to run the new version of DeepTau discriminator in private workflows (to analyse phase-2 samples with 12_5_X), but **it does not enable the new version of DeepTau in official workflows**.  Therefore, differences in outputs are not expected.

To run standalone test, one can run the configuration file `RecoTauTag/RecoTau/test/runDeepTauIDsOnMiniAOD.py` after setting the flag `phase2 = True` in that file.

#### PR validation:

Validated with the standalone test mentioned above and with miniAOD workflows.

#### Backport PR

This is backport of https://github.com/cms-sw/cmssw/pull/40622 to 12_6_X to facilitate tau studies for phase-2 with 12_5_X samples.

### CODE REVIEW

**Comment by swertz** [comment]
please test

**Comment by swertz** [comment]
I'm surprised to not see any of the differences in TauID products for Phase2 MiniAOD workflow comparisons, that were visible (and expected) in the original PR https://github.com/cms-sw/cmssw/pull/40622

Do you have an explanation for that @mbluj ?

**Comment by mbluj** [comment]
> I'm surprised to not see any of the differences in TauID products for Phase2 MiniAOD workflow comparisons, that were visible (and expected) in the original PR #40622
> 
> Do you have an explanation for that @mbluj ?

Yes, it is expected. In backported versions of the #40622 all code changes (includes C++ code and python tool to generate configurations for tauIDs) are on the place, but the new tauID is not enabled in official workflows. It is to not break "non-changing" policy in production releases. Therefore, the backports allow users to run the new tauID in their private workflows, e.g. private re-miniAOD or nanoAOD/ntuple production on top of miniAOD, but official workflows are not affected.

**Comment by swertz** [comment]
Thanks for clarifying! Out of curiosity, where do I see that the tauID is not enabled? They are clearly enabled in master since we saw the changes in the tests of https://github.com/cms-sw/cmssw/pull/40622 And since the code of the backport is the same and enables the new ID for the `phase2_common` modifer, I don't understand how it is disabled...

**Comment by mbluj** [comment]
> Thanks for clarifying! Out of curiosity, where do I see that the tauID is not enabled? They are clearly enabled in master since we saw the changes in the tests of #40622 And since the code of the backport is the same and enables the new ID for the `phase2_common` modifer, I don't understand how it is disabled...

In the original and this backport PR a way in which phase-2 tauIDs are enabled in `PhysicsTools/PatAlgos/python/slimming/miniAOD_tools.py` is slightly changed: previously each of them was added separately, now a list of phase-2 tauIDs is defined and then it is passed to `phase2_common.toModify`, see here: https://github.com/cms-sw/cmssw/pull/40724/files#diff-c1409af99a0dfee10534eb0c4e985d3b4dd669b5c81cd302efdf760ee0ce5c41L391-L392
The difference between the backport and original PRs comes from definition of the list - in case of the original it contains new the phase-2 deepTauID, while in the backport the list contains older tauIDs, thus no change (=disabled). This disabling is introduced in this commit: https://github.com/cms-sw/cmssw/pull/40724/commits/46cd11a9fc363b5be371ca794e5d8ad316337548

**Comment by mandrenguyen** [comment]
+1

**Comment by swertz** [comment]
+1

Thanks @mbluj I'd overlooked that bit!

**Comment by mbluj** [comment]
Just a comment: to make this PR useful also cms-dist of 12_6_X should be updated to contain cms-data state with data-model of the new phase-2 integrated in, i.e. with PR https://github.com/cms-data/RecoTauTag-TrainingFiles/pull/11

**Comment by perrotta** [comment]
please test with https://github.com/cms-sw/cmsdist/pull/8309

**Comment by perrotta** [comment]
+1

**Comment by perrotta** [comment]
merge

**Pull request merged**
