### PR TITLE
Use 2018 GTs/Eras for TSG HLT development menus

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
Use 2018 GTs/Eras for HLT development menus
Based on CMSSW_10_0_X_2017-12-12-2300

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
The test failure is not reproducible offline. So let's try again later.

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by Martin-Grunewald** [comment]
@Dr15Jones 
Please sign for core.
Thanks

**Comment by Dr15Jones** [comment]
+1
for addOnTests.py

**Comment by davidlange6** [comment]
+1

**Pull request merged**
