### PR TITLE
Fix to a customize python script in Phase2 Tracker Digizer  

### PR DESCRIPTION
**Pull request by suchandradutta**
#### PR description:
Fixing  customizeForOTInefficiency.py to have updated value of configuration parameter for Bias Rail Inefficiency,

@emiglior

### CODE REVIEW

**Comment by mmusich** [comment]
test parameters:
   * worklfows = 21034.112, 21034.113, 21034.114
   * relvals_opt= -w upgrade

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
why was https://github.com/cms-sw/cmssw/pull/40880#issuecomment-1444412182 thumbed down?
`runTheMatrix.py --what upgrade -nel 21034.112,21034.113,21034.114` is a fully valid command in `CMSSW_13_1_X_2023-02-24-1100`

**Comment by civanch** [comment]
+1

**Comment by srimanob** [comment]
Hi @suchandradutta @emiglior 
Do we need 0T workflow for Phase-2? I don't see it in upgrade.

**Comment by mmusich** [comment]
>  Do we need 0T workflow for Phase-2? I don't see it in upgrade.

what does this have to do with this PR?

**Comment by srimanob** [comment]
I just see that the update is on customizeForOTInefficiency, so I ask do we have a workflow to test?

**Comment by mmusich** [comment]
>  so I ask do we have a workflow to test?

see https://github.com/cms-sw/cmssw/pull/40880#issuecomment-1444412182

**Comment by srimanob** [comment]
OK, then I know why I can't find it. These lines (wf .112, .113, .114 use OT (not 0T as .24)
https://github.com/cms-sw/cmssw/blob/master/Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py#L1784-L1821

**Comment by srimanob** [comment]
OK, thanks.

**Comment by srimanob** [comment]
+Upgrade

**Comment by perrotta** [comment]
+1

**Pull request merged**
