### PR TITLE
PixDQM summary fix in 7_3_X

### PR DESCRIPTION
**Pull request by fioriNTU**
Making changes for summary histos and HLT filering for Online DQM

### CODE REVIEW

**Comment by danduggan** [comment]
please test

**Comment by deguio** [comment]
+1
@danduggan this one should be tested on the playback first.

**Comment by danduggan** [comment]
@deguio one step ahead of you - running since yesterday ;)

**Comment by deguio** [comment]
+1000

**Comment by davidlange6** [comment]
+1

after a +1000, how can we say no....

**Pull request merged**
