### PR TITLE
Fix of OI muon customisation in HLT (103X)

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
Fix of OI muon customisation in HLT (103X)
Based on CMSSW_10_3_0_pre2
Fixes missing customisation in #24267 and thus a crash (see discussion there)

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
type bugfix

**Comment by Martin-Grunewald** [comment]
+1

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
