### PR TITLE
updating the E/gamma HLT TnP DQM to have muon tags

### PR DESCRIPTION
**Pull request by Sam-Harper**
Dear All,

This update of the E/gamma HLT TnP DQM package now allows triggers to be monitored by muon tags, adding further cross trigger monitoring. It is also enabled for a few select electron triggers to be able to monitor e/gamma problems that may impact the tag & probe in a correlated way (online beamspot issues immediately jump to mind there)

As well as adding DQM plots where the tag is a muon, this update also fixes the newly introduced for V3 HLT_Ele32_WPTight_Gsf filters which were slightly miss named. 

The new filters have been tested on ttbar lepton relval sample and the  results are below, showing the filters run and are filled. The full listing is at
https://sharper.web.cern.ch/sharper/cms/trig/2017/Aug14th_muDQM/

HLT_Ele32_WPTight_Gsf:
ele tag:
https://sharper.web.cern.ch/sharper/cms/trig/2017/Aug14th_muDQM/eleWPTightTag_HLT_Ele32_WPTight_Gsf_hltEle32WPTightGsfTrackIsoFilter.gif
muon tag:
https://sharper.web.cern.ch/sharper/cms/trig/2017/Aug14th_muDQM/muonIsoMuTagEleProbe_HLT_Ele32_WPTight_Gsf_hltEle32WPTightGsfTrackIsoFilter.gif

HLT_Ele32_WPTight_Gsf_L1DoubleEG:
https://sharper.web.cern.ch/sharper/cms/trig/2017/Aug14th_muDQM/muonIsoMuTagEleProbe_HLT_Ele32_WPTight_Gsf_L1DoubleEG_hltEle32L1DoubleEGWPTightGsfTrackIsoFilter.gif

HLT_DoubleEle33_CaloIdL_MW:
https://sharper.web.cern.ch/sharper/cms/trig/2017/Aug14th_muDQM/muonIsoMuTagEleProbe_HLT_DoubleEle33_CaloIdL_MW_hltEle33CaloIdLMWPMS2Filter.gif

HLT_Mu12_DoublePhoton20:
with photon probe:
https://sharper.web.cern.ch/sharper/cms/trig/2017/Aug14th_muDQM/muonIsoMuTagPhoProbe_HLT_Mu12_DoublePhoton20_hltMu12DiEG20HEUnseededFilter.gif
with electron probe
https://sharper.web.cern.ch/sharper/cms/trig/2017/Aug14th_muDQM/muonIsoMuTagEleProbe_HLT_Mu12_DoublePhoton20_hltMu12DiEG20HEUnseededFilter.gif

HLT_Mu27_Ele37_CaloIdL_MW:
https://sharper.web.cern.ch/sharper/cms/trig/2017/Aug14th_muDQM/muonIsoMuTagEleProbe_HLT_Mu27_Ele37_CaloIdL_MW_hltEle37CaloIdLMWPMS2UnseededFilter.gif

HLT_Mu37_Ele27_CaloIdL_MW:
https://sharper.web.cern.ch/sharper/cms/trig/2017/Aug14th_muDQM/muonIsoMuTagEleProbe_HLT_Mu37_Ele27_CaloIdL_MW_hltEle27CaloIdLMWPMS2UnseededFilter.gif

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by mtosi** [comment]
thanks !
may I ask you the amount of bins added by this PR ?
do you think we can decrease (in the upcoming weeks) the binning, above all in the 2D plots ?
thanks !

ah, do you have the backport for 92x ?

**Comment by Sam-Harper** [comment]
Hi @mtosi 

I'll do the backport once its generally accepted that this is done. 

As for binning, well I could dump all HEM17 and HEP17 plots for this package. That would save 2/3rds of the histograms. They so far have not been that useful.  The 2D plots are reasonably sensibility binned

**Comment by mtosi** [comment]
in the root file I even find plots for 
HLT_Ele27_Ele37_CaloIdL_MW ;)

**Comment by mtosi** [comment]
tracked by https://github.com/cms-sw/cmssw/issues/19142

**Comment by Sam-Harper** [comment]
so I have a plan to re-visit how I do HEP17 and HEM17. Should cut the number of bins by ~1/3. Will submit soon

**Comment by mtosi** [comment]
thanks !
 mia

**Comment by Sam-Harper** [comment]
Hi Mia, here is the new update, I re-worked the HEP/HEM17 hists given on practical experience so far. 

Before these changes (but including the first changes in this PR)
nr hists 1D 3206
nr hists 2D 639
#1D bins 82486
#2D bins 570114
# total bins 652600

With the HEP/HEM17 changes
nr hists 1D 2378
nr hists 2D 225
#1D bins 49760
#2D bins 192546
# total bins 242306

so this package has about ~1mb of histograms down from around 2.2mb or so before. 

The area at https://sharper.web.cern.ch/sharper/cms/trig/2017/Aug14th_muDQM/ has been updated.

**Comment by Sam-Harper** [comment]
Just released I over estimated those changes (I was including the harvested histogram (ie the ratio of pass/tot to get eff) So its off by a 3rd. 

So about 1.5mb -> 0.6mb  in histograms.

**Comment by mtosi** [comment]
thanks @Sam-Harper !!!!
ah, if you think you do not need the numerator and denominator histograms,
there is the way to clean/delete them in the harvesting step
please, let me know, and I'll cross check how to do it

**Comment by mtosi** [comment]
@cmsbuild , please test

**Comment by Sam-Harper** [comment]
I think its nice to have the numerator and denominator histograms kept as well. Its not really costing us much is it? I was debating about putting them into a separate directory though.

**Comment by mtosi** [comment]
not sure the ratio and the other 2 plots can be store in 2 different
directories w/ current code :(
but either DQM core or I can give a look on it, I would say ...
  mia

**Comment by Sam-Harper** [comment]
Oh I would write some code to do it. I'm not super keen on how the harvesting is done right now anyways. Anyways it doesnt bother me enough to fix it, low priority.

Anyways I just realised a small oversight on my muon ID producer, I should add an option to disable the muon selection in it. Which I've now done, sorry about that.

**Comment by mtosi** [comment]
@cmsbuild, please test

**Comment by Sam-Harper** [comment]
@kmaeshima @vanbesien, @vazzolini, @dmitrijus 

just a ping on the status of approval of this. This PR adds more useful DQM plots for EGM while reducing the total bin count by ~50% so is a clear improvement.

**Comment by Sam-Harper** [comment]
@kmaeshima @vanbesien, @vazzolini, @dmitrijus

another ping on the status of approval of this. 

This PR adds more useful DQM plots for EGM while reducing the total bin count by ~50% so is a clear improvement

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
