### PR TITLE
[12.4.X] fix compilation errors in MomentumScaleCalibration macros

### PR DESCRIPTION
**Pull request by mmusich**
backport of https://github.com/cms-sw/cmssw/pull/39065

#### PR description:

This PR fixes a couple of compilation errors preventing the Zµµ alignment validation to run, due to failures in the merge step.
The errors spotted are:

```
Info in <TUnixSystem::ACLiC>: creating shared library /pool/condor/dir_18690/TkAllInOneTool/./CompareBiasZValidation_cc.so
In file included from CompareBiasZValidation_cc_ACLiC_dict dictionary payload:8:
In file included from ././CompareBiasZValidation.cc:9:
In file included from /pool/condor/dir_18690/TkAllInOneTool/FitMassSlices.cc:4:
In file included from /pool/condor/dir_18690/TkAllInOneTool/FitSlices.cc:4:
/pool/condor/dir_18690/TkAllInOneTool/FitXslices.cc:108:48: error: use of overloaded operator '+' is ambiguous (with operand types 'TString' and 'std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::__string_type' (aka 'basic_string<char, std::char_traits<char>, std::allocator<char> >'))
      TH1* sliceHisto = histo->ProjectionY(name+ss.str(), x, x);
                                           ~~~~^~~~~~~~~
/cvmfs/cms.cern.ch/slc7_amd64_gcc10/lcg/root/6.24.07-bf41b0420bc269850b74e23486e2953a/include/TString.h:49:9: note: candidate function
TString operator+(const TString &s1, const TString &s2);
        ^
/cvmfs/cms.cern.ch/slc7_amd64_gcc10/lcg/root/6.24.07-bf41b0420bc269850b74e23486e2953a/include/TEveUtil.h:116:15: note: candidate function
TEveException operator+(const TEveException &s1, const std::string  &s2);
              ^
/cvmfs/cms.cern.ch/slc7_amd64_gcc10/lcg/root/6.24.07-bf41b0420bc269850b74e23486e2953a/include/TString.h:51:9: note: candidate function
TString operator+(const char *cs, const TString &s);
        ^
/cvmfs/cms.cern.ch/slc7_amd64_gcc10/lcg/root/6.24.07-bf41b0420bc269850b74e23486e2953a/include/TEveUtil.h:117:15: note: candidate function
TEveException operator+(const TEveException &s1, const TString &s2);
              ^
In file included from CompareBiasZValidation_cc_ACLiC_dict dictionary payload:8:
In file included from ././CompareBiasZValidation.cc:9:
In file included from /pool/condor/dir_18690/TkAllInOneTool/FitMassSlices.cc:4:
In file included from /pool/condor/dir_18690/TkAllInOneTool/FitSlices.cc:4:
/pool/condor/dir_18690/TkAllInOneTool/FitXslices.cc:262:50: error: use of overloaded operator '+' is ambiguous (with operand types 'TString' and 'std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::__string_type' (aka 'basic_string<char, std::char_traits<char>, std::allocator<char> >'))
        TH1* sliceHisto = histo->ProjectionZ(name+ss.str(), x, x, y, y);
                                             ~~~~^~~~~~~~~
/cvmfs/cms.cern.ch/slc7_amd64_gcc10/lcg/root/6.24.07-bf41b0420bc269850b74e23486e2953a/include/TString.h:49:9: note: candidate function
TString operator+(const TString &s1, const TString &s2);
        ^
/cvmfs/cms.cern.ch/slc7_amd64_gcc10/lcg/root/6.24.07-bf41b0420bc269850b74e23486e2953a/include/TEveUtil.h:116:15: note: candidate function
TEveException operator+(const TEveException &s1, const std::string  &s2);
              ^
/cvmfs/cms.cern.ch/slc7_amd64_gcc10/lcg/root/6.24.07-bf41b0420bc269850b74e23486e2953a/include/TString.h:51:9: note: candidate function
TString operator+(const char *cs, const TString &s);
        ^
/cvmfs/cms.cern.ch/slc7_amd64_gcc10/lcg/root/6.24.07-bf41b0420bc269850b74e23486e2953a/include/TEveUtil.h:117:15: note: candidate function
TEveException operator+(const TEveException &s1, const TString &s2);
              ^
In file included from CompareBiasZValidation_cc_ACLiC_dict dictionary payload:8:
In file included from ././CompareBiasZValidation.cc:9:
In file included from /pool/condor/dir_18690/TkAllInOneTool/FitMassSlices.cc:4:
/pool/condor/dir_18690/TkAllInOneTool/FitSlices.cc:115:55: error: use of overloaded operator '+' is ambiguous (with operand types 'TString' and 'std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::__string_type' (aka 'basic_string<char, std::char_traits<char>, std::allocator<char> >'))
      tempHisto->SetName(TString(tempHisto->GetName())+ss.str());
                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~
/cvmfs/cms.cern.ch/slc7_amd64_gcc10/lcg/root/6.24.07-bf41b0420bc269850b74e23486e2953a/include/TString.h:49:9: note: candidate function
TString operator+(const TString &s1, const TString &s2);
        ^
/cvmfs/cms.cern.ch/slc7_amd64_gcc10/lcg/root/6.24.07-bf41b0420bc269850b74e23486e2953a/include/TEveUtil.h:116:15: note: candidate function
TEveException operator+(const TEveException &s1, const std::string  &s2);
              ^
/cvmfs/cms.cern.ch/slc7_amd64_gcc10/lcg/root/6.24.07-bf41b0420bc269850b74e23486e2953a/include/TString.h:51:9: note: candidate function
TString operator+(const char *cs, const TString &s);
        ^
/cvmfs/cms.cern.ch/slc7_amd64_gcc10/lcg/root/6.24.07-bf41b0420bc269850b74e23486e2953a/include/TEveUtil.h:117:15: note: candidate function
TEveException operator+(const TEveException &s1, const TString &s2);
              ^
Warning in <TInterpreter::TCling::RegisterModule>: Problems declaring payload for module CompareBiasZValidation_cc_ACLiC_dict.
IncrementalExecutor::executeFunction: symbol '_ZStL19__constant_string_pIcEbPKT_' unresolved while linking [cling interface function]!
You are probably missing the definition of bool std::__constant_string_p<char>(char const*)
Maybe you need to load the corresponding shared library?
```

#### PR validation:

Run successfully with the fix.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Verbatim backport of https://github.com/cms-sw/cmssw/pull/39065, needed for tracker alignment purposes.

### CODE REVIEW

**Comment by mmusich** [comment]
type trk, bug-fix

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
+alca

**Comment by tvami** [comment]
urgent
 * this should go into the next 12_4_X

**Comment by perrotta** [comment]
+1

**Pull request merged**
