### PR TITLE
Add rhoCorr and energy-binned cuts (91X)

### PR DESCRIPTION
**Pull request by afiqaize**
This is a clone of #18559  but for 91X milestone.

Let's hope I get it right this time.

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
@afiqaize 
There are now merge conflicts, please fix this PR!

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by Martin-Grunewald** [comment]
@afiqaize 
Same duplication here - please fix asap.

**Comment by afiqaize** [comment]
Ugh, definitely NOT what I intended. Wait, let me figure out how to fix this...

**Comment by perrotta** [comment]
-1
Rebase needed

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by Martin-Grunewald** [comment]
@davidlange6 
Please integrate this PR in 91X now that it works in 92X.

**Comment by Martin-Grunewald** [comment]
@davidlange6 
What is holding up integration of this PR?

**Comment by ggovi** [comment]
+1

**Comment by ggovi** [comment]
HTH, not sure why this one requires the db signature...

**Comment by Martin-Grunewald** [comment]
...it doesn't -??

**Comment by Martin-Grunewald** [comment]
@davidlange6 
PING

**Pull request merged**
