### PR TITLE
Generalize DetId parsing in TrackingNtuple

### PR DESCRIPTION
**Pull request by makortel**
This PR makes the DetId parsing in TrackingNtuple more agnostic on the detector geometry by parsing the fields in the ntuplizer with TrackerTopology, and storing all the fields in separate branches. Straightforward implementation would have lead to some amount of copy-paste because `pix_*` branches have BPix/FPix hits, `str_*` and `ph2_*` TIB/TID/TOB/TEC hits, and `inv_*` and `simhit_*` hits from all subdetectors, so I went a bit creative.

This PR is a successor of #18403 (which attempted to serialize the TrackerTopology constants and do the parsing on the ntuple analysis code).

I also included a small fix in the ntuple python library by @ebrondol (da8d834)

Tested in 9_1_0_pre2, no changes expected.

@rovere @VinInn @ebrondol

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
Removed one bogus import that didn't give errors on my local area (thanks @ebrondol!)

**Comment by makortel** [comment]
Added another commit, to show the phase2 OT barrel tilted side as part the layer string in the default hit list printouts (thanks to @ebrondol for the suggestion and testing it).

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
