### PR TITLE
TriggerRatesMonitor: migrate to Stage 2 (81x)

### PR DESCRIPTION
**Pull request by fwyzard**
TriggerRatesMonitor
- migrate to Stage 2 L1 trigger
- add test

### CODE REVIEW

**Comment by fwyzard** [comment]
+1

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
@dmitrijus, @vanbesien, could you check and sign this ?

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
