### PR TITLE
Backporting DQM for VBF+MET triggers to 92X

### PR DESCRIPTION
**Pull request by amagnan**

### CODE REVIEW

**Comment by mtosi** [comment]
tracked by https://github.com/cms-sw/cmssw/issues/19142

**Comment by mtosi** [comment]
@cmsbuild, please test

**Comment by dmitrijus** [comment]
backport of https://github.com/cms-sw/cmssw/pull/19294
Please, next time, provide the link to the upstream yourself. Saves a lot of time.

**Comment by dmitrijus** [comment]
+1

**Comment by tankit** [comment]
Hi @dmitrijus, @amagnan, @fwyzard , I am trying to make a separate PR to backport (#19637), but @dmitrijus gave a comment that it may be in conflict due to TriggerDQMBase. So, I wonder if it is possible to combine the two (#19561 and #19673) in a single PR for 9.2.x. This is initially suggested by Andrea.

**Comment by dmitrijus** [comment]
@tankit It is something you and @fwyzard  have to coordinate between backports.
I don't know what is the best strategy, personally I liked Andrea's backport PR with all the relevant backports, for example, https://github.com/cms-sw/cmssw/pull/19685

**Comment by fwyzard** [comment]
Hi,
given the amount of stuff that needs to be backported, I plan to do it in a single PR as soon as the DQM for the HLT menu v2.1 is fully integrated in 9.3.x.
If the 9.3.x equivalent of this PR has already been merged, or is listed as "Open" at #19412, can you close this PR ?

**Comment by amagnan** [comment]
I think you meant #19142.... I cannot see another PR with backport for the SUSY and VBF+tau paths. I think the latest for 93X was the VBF+tau #19794, so I wonder if this one should be used for the backporting of everything....

**Comment by tankit** [comment]
There is another back port #19673 that uses TriggerDQMBase.
Will you do it in a single PR?

**Comment by fwyzard** [comment]
Hi,
for all HLT DQM backports, please start from
https://github.com/cms-sw/cmssw/pull/19961 .

.A

**Comment by amagnan** [comment]
All changes are in #19961 already, closing this PR.

**Pull request closed without merging**
