### PR TITLE
Initial commit of Atlas CheckerGccPlugin with Buildfile

### PR DESCRIPTION
**Pull request by gartung**
Depends on https://github.com/cms-sw/cmsdist/pull/4187

### CODE REVIEW

**Comment by gartung** [comment]
@Dr15Jones @smuzaffar

**Comment by gartung** [comment]
The missing symbol check fails because the compiler loads this with base plugin libraries. I tried removing the symbol checks using the package BuildFile.xml. I can only get the build to work if I edit config/Buildfile.xml and remove the -E flags.

**Comment by smuzaffar** [comment]
@gartung , why not add this as  an external?

**Comment by Dr15Jones** [comment]
I agree, this should be an external. However, first, I'd like to evaluate it 'standalone' to see how well it behaves.

**Comment by gartung** [comment]
OK. I will add a spec instead.

**Pull request closed without merging**
