### PR TITLE
Bug fix for compatible mode in UETableProducer. (Same as #12227)

### PR DESCRIPTION
**Pull request by mverwe**
Does not have impact on reconstruction. Bug fix for DB generation.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
@mverwe: The static analyzer has flagged a thread-safety problem in UETableProducer.cc. Please fix this problem:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-12239/9427/llvm-analysis/report-651349.html#EndPath

**Comment by mverwe** [comment]
Fixed the multi-threading safety and added necessary description. edmCheckMultithreading does not complain anymore.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
+1

For #12239 8550b00fa56a7a284b2597b20d0905511bcecdd6

Bug fix in Heavy Ion UETableProducer for DB generation. There should be no change in monitored quantities. #12227 is the 75X version of this PR, and it has already been merged.

The code change is satisfactory. Jenkins tests against baseline CMSSW_7_6_X_2015-11-04-1100 show no significant differences, as expected.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
