### PR TITLE
[DD4Hep] Make sure the test runs on dd4hep-based geometry

### PR DESCRIPTION
**Pull request by ianna**
#### PR description:

Make sure the test configuration uses DD4Hep Era.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by ianna** [comment]
@cvuosalo - FYI

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
@ianna , you need rebase

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

this PR is fine now

**Comment by qliphy** [comment]
+1

**Pull request merged**
