### PR TITLE
80x dpg analysis si strip tools updates

### PR DESCRIPTION
**Pull request by venturia**
small fix in OccupancyPlots plugin to avoid problem when endRun is called more than once in a run
Update of the documentation
Update of the configurations

### CODE REVIEW

**Comment by venturia** [comment]
@fioriNTU @idebruyn I have modified the configuration of OccupancyPlots_cfg.py and fixed a possible bug in OccupancyPlots plugin

**Comment by boudoul** [comment]
backport #16399

**Comment by monttj** [comment]
@cmsbuild please test

**Comment by monttj** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
