### PR TITLE
Updating Data GT for 2015 Run2 EOY Re-Reco, RunII Simulation with new SIM geometries, and Upgrade GT with Pixel conditions

### PR DESCRIPTION
**Pull request by diguida**
# Summary of Global Tag Changes
## RunII Simulation
- **Ideal scenario**: [76X_mcRun2_design_v13](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/76X_mcRun2_design_v13): As [76X_mcRun2_design_v12](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/76X_mcRun2_design_v12) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/76X_mcRun2_design_v13/76X_mcRun2_design_v12):
  - added further labels for Castor SIM geometry
- **Asymptotic scenario**: [76X_mcRun2_asymptotic_v13](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/76X_mcRun2_asymptotic_v13): As [76X_mcRun2_asymptotic_v12](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/76X_mcRun2_asymptotic_v12) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/):
  - added further labels for Castor SIM geometry
- **Startup scenario**: [76X_mcRun2_startup_v12](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/76X_mcRun2_startup_v12): As [76X_mcRun2_startup_v11](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/76X_mcRun2_startup_v11) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/76X_mcRun2_startup_v12/76X_mcRun2_startup_v11):
  - added further labels for Castor SIM geometry
## RunI Data
- **HLT processing**: [76X_dataRun1_HLT_frozen_v10](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/76X_dataRun1_HLT_frozen_v10): As [76X_dataRun1_HLT_frozen_v9](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/76X_dataRun1_HLT_frozen_v9) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/76X_dataRun1_HLT_frozen_v10/76X_dataRun1_HLT_frozen_v9):
  - added Record for HCAL negative energy filter
- **Offline processing**: [76X_dataRun1_v15](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/76X_dataRun1_v15): As [76X_dataRun1_v11](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/76X_dataRun1_v11) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/76X_dataRun1_v15/76X_dataRun1_v11):
  - explicit tag differences:
    - updated Tracker alignment, surface deformations and APE for the full range of 2015 data taking
    - updated Lumi Section based beamspot for 2015B,C,D taking into account new Tracker alignment
    - updated DT,CSC and muon GPR alignment due to updated Tracker alignment
    - updated DT vdrift and tTrig constants
    - updated CSC timing constants
    - updated SiStrip bad channel and particle APV gain corrections
    - updated Hcal gains and response correction (taking into account HE radiation damage and HO calibration)
    - updated Castor local reco calibrations (Channel quality,Electronic map, Gains, GainWidths, Pedestals, PedestalWidths, QIEData, RecoParams, Saturation corrections)
    - updated Ecal channel status, IC, AdcToGeV, time calibrations
    - updated Ecal Barrel and Endcap alignment due to updated Tracker alignment
    - updated ES IC
    - updated centrality table with HFtowers label
    - updated JEC with AK4Calo label for pp reference run at 5TeV
  - differences introduced by append IOVs:
    - new IOVs for L1T O2O
    - new IOVs for ECAL O2O
    - new IOVs for HCAL LUT (alternating tables for 0T and 3.8T)
    - new IOVs for SiStrip O2O pointing to prompt tags
    - new IOVs for RunInfo (up to run 263284)
    - new IOVs for CSC Crosstalk, Gains, Noise and Pedestals
    - new IOVs for Ecal bad channels, laser corrections, pedestals, and pulse shapes
    - new IOVs for Preshower alignment (alternating 0T and 3.8T geometries)
    - new IOVs for HCal channel quality
    - new IOVs for Pixel templates at 0T.
## RunII Data
- **HLT processing**: [76X_dataRun2_HLT_frozen_v10](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/76X_dataRun2_HLT_frozen_v10): As [76X_dataRun2_HLT_frozen_v9](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/76X_dataRun2_HLT_frozen_v9) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/76X_dataRun2_HLT_frozen_v10/76X_dataRun2_HLT_frozen_v9):
  - added Record for HCAL negative energy filter
- **HLT HI processing**: [76X_dataRun2_HLTHI_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/76X_dataRun2_HLTHI_v1): As [76X_dataRun2_HLT_frozen_v10](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/76X_dataRun2_HLT_frozen_v10) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/76X_dataRun2_HLTHI_v1/76X_dataRun2_HLT_frozen_v10):
  - added Tracking MVA selection for HI
  - updated SiStrip pedestals with full fledged values for SiStrip Zero Suppression at HLT
  - updated AK4Calo JEC for HLT with values for HI
- **Offline processing**: [76X_dataRun2_v15](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/76X_dataRun2_v15): As [76X_dataRun2_v11](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/76X_dataRun2_v11) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/76X_dataRun2_v15/76X_dataRun2_v11):
  - explicit tag differences:
    - updated Tracker alignment, surface deformations and APE for the full range of 2015 data taking
    - updated Lumi Section based beamspot for 2015B,C,D taking into account new Tracker alignment
    - updated DT,CSC and muon GPR alignment due to updated Tracker alignment
    - updated DT vdrift and tTrig constants
    - updated CSC timing constants
    - updated SiStrip bad channel and particle APV gain corrections
    - updated Hcal gains and response correction (taking into account HE radiation damage and HO calibration)
    - updated Castor local reco calibrations (Channel quality,Electronic map, Gains, GainWidths, Pedestals, PedestalWidths, QIEData, RecoParams, Saturation corrections)
    - updated Ecal channel status, IC, AdcToGeV, time calibrations
    - updated Ecal Barrel and Endcap alignment due to updated Tracker alignment
    - updated ES IC
    - updated centrality table with HFtowers label
    - updated JEC with AK4Calo label for pp reference run at 5TeV
  - differences introduced by append IOVs:
    - new IOVs for L1T O2O
    - new IOVs for ECAL O2O
    - new IOVs for HCAL LUT (alternating tables for 0T and 3.8T)
    - new IOVs for SiStrip O2O pointing to prompt tags
    - new IOVs for RunInfo (up to run 263284)
    - new IOVs for CSC Crosstalk, Gains, Noise and Pedestals
    - new IOVs for Ecal bad channels, laser corrections, pedestals, and pulse shapes
    - new IOVs for Preshower alignment (alternating 0T and 3.8T geometries)
    - new IOVs for HCal channel quality
    - new IOVs for Pixel templates at 0T.
## Upgrade simulation
- **2017 ideal scenario**: [76X_upgrade2017_design_v8](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/): As [76X_upgrade2017_design_v7](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/76X_upgrade2017_design_v8/76X_upgrade2017_design_v7):
  - New Pixel SIM LA for Phase-I
  - New Pixel LA for Phase-I
  - New Pixel templates for Phase-I
  - New Pixel SIM gains for Phase-I
  - New Pixel GenErrors for Phase-I
  - New Pixel gains for Phase-I
  - New Pixel quality for Phase-I.

### CODE REVIEW

**Comment by diguida** [comment]
please test

**Comment by diguida** [comment]
please test

**Comment by franzoni** [comment]
please test

**Comment by davidlange6** [comment]
please test

**Comment by diguida** [comment]
please test

**Comment by diguida** [comment]
please test

**Comment by diguida** [comment]
please test

**Comment by slava77** [comment]
@diguida please send a message when this PR is worth looking at.
I wanted to run some more comparisons locally.

**Comment by diguida** [comment]
@slava77 now it is done, I looked at all the GT one by one and amended the commits every time I was finding something non correct.
You can now look at the plots. I am doing the same checks on the bot results.

**Comment by diguida** [comment]
@slava77 BTW, if you can share the tools for plot comparison, I'd like to run some 2015 RelVal with the new GT and compare the results w.r.t. the clean IB.

**Comment by slava77** [comment]
On 12/5/15 12:29 AM, Salvatore Di Guida wrote:
> @slava77 <https://github.com/slava77> BTW, if you can share the tools
> for plot comparison, I'd like to run some 2015 RelVal with the new GT
> and compare the results w.r.t. the clean IB.
> 

instructions are available at
https://twiki.cern.ch/twiki/bin/viewauth/CMS/RecoIntegration#Running_matrix_tests
and the following several bullets.
jenkins runs the same comparisons with a bit different wrapper
and with some automation in place where it sets thresholds in relmon and
"alternative-comparisons"
(also a DQM diff).

**Comment by slava77** [comment]
here are some notes based on a test in CMSSW_7_6_2.
All changes of physics objects are in data workflows. (no changes in MC).
Compared to the summary of the PR, I don't really see any numerical changes in run1 other than in the castor reco (maybe the updates were made to IOVs not covered by the tests).

- run 1 data changes are only in castor  reco (in 2010 and 2011 HI and in 2011 pp; no change in 2012 tests since castor was not in that data)
e.g. 2011A pp (wf 1000)
all_sign646vsorig_runminbias2011awf1000p0c_log10recocastortowers_castortowerreco__reco_obj_energy

- run2 data changes are in a similar set of places in 2015B, C, and D. A somewhat superficial summary of differences is:
    - in HO energy (significantly higher, mainly in the outer wheels)
    - in ES energy (noticeably higher)
    - in ECAL hit time (smallish shuffle, probably better peak in EB)
    - is CSC  time (better centered around 0)
    - in DT time (better centered around 0)
    - in the offline PV constrained to BS: x and y errors  (smaller by ~10-20%, there is also a small shift of about 10 microns in y in all B, C, and D tested workflows)
    - generalTracks chi2 is a bit larger (chi2prob more flat closer to 1 but has a bigger bump at 0)

**Comment by diguida** [comment]
@slava77 thanks a lot for your detailed review. They all make sense to me, even if I would like to see in closest details the tracking changes (in principle they should improve the chi2). I will approve this and then post other plots I have started to look at (weekend taken by online operations and crappy home network).

**Comment by diguida** [comment]
+1

**Comment by davidlange6** [comment]
+1
(but did we get an answer about castor corrections for run1 given the large change?)

**Comment by mmusich** [comment]
@davidlange6 https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2130/1/1.html

**Comment by boudoul** [comment]
Hi @diguida , just a small request on my side :  Could you make the tiltle of such PRs more explicit in the future ? I noticed that the upgrade simulation GT was also changed in this 'Updating Data GT for 2015 Run2 EOY Re-Reco" , I had hard time to find it ...(and you are also changing run1data and run2 simulation btw ... so the tiltle is really not explicit...)  Thanks a lot.

**Comment by mmusich** [comment]
@boudoul a separate PR existed for a while: https://github.com/cms-sw/cmssw/pull/12371, we decided to include that commit in this PR not to leave the upgrade GT behind. General comment: since we are trying to minimize the number of PRs for each release it's bound to happen again to have all the scenarios updated. Given the limited amount of characters available for the title we generally choose the most meaningful update. We can use (unless there are specific cases) a neutral "Updated Global Tags for all scenarios"

**Comment by diguida** [comment]
@boudoul @mmusich cutting and playing with the limit of characters I was able to provide a more meaningful title.
Hope you like it.

**Comment by boudoul** [comment]
I do, Thanks!

**Pull request merged**
