### PR TITLE
EMTF new LCT coordinate conversion LUTs

### PR DESCRIPTION
**Pull request by abrinke1**
As detailed here [1], the phi coordinates computed in EMTF via the Primitive Conversion Look-Up Tables ("PC LUTs") are significantly displaced from the true coordinates, due to detector mis-alignment effects.  EMTF will be loading new PC LUTs reflecting the real CMS geometry, and thus new LUTs and modifications to the emulator are needed to preserve data-emulator agreement.

The new LUTs are being PR-ed separately here:

This update is urgently needed for the DQM.

Best regards,
Andrew for the EMTF team

[1] https://indico.cern.ch/event/758694/contributions/3146645/subcontributions/263903/attachments/1719883/2776101/2018_09_20_EMTF_alignment.pdf

### CODE REVIEW

**Comment by abrinke1** [comment]
For *central* cms-data, the LUT PR is actually here: https://github.com/cms-data/L1Trigger-L1TMuon/pull/16

**Comment by thomreis** [comment]
please test with cms-data/L1Trigger-L1TMuon#16

**Comment by threus** [comment]
@thomreis if this is only a temporary PR until cms-data/L1Trigger-L1TMuon#16 gets merged, maybe there is no need to run these tests. Just make sure the links work (see my email response) and if all is fine, @abrinke1 can close this PR, we'll take it to online DQM. Once L1TMuon#16 is merged, we'll switch to #24617

**Comment by thomreis** [comment]
Hi @threus 
The data PR got merged now.

**Comment by threus** [comment]
@thomreis great. But we'll need a patch release with the data PR, only then we can use #24617 in online DQM. Until then, we'll use this PR (once it works). Apologies, I was not clear in my previous comment.

**Comment by thomreis** [comment]
please test with cms-sw/cmsdist#4356

**Comment by thomreis** [comment]
please abort test

**Comment by thomreis** [comment]
please test with cms-sw/cmsdist#4365

**Comment by smuzaffar** [comment]
@thomreis , this PR is for 10.2.X  while cmsdist PR is for 10.3.X. Please first the cmsdist PR for 10.3.X and then we can backport it to 10.2.

**Comment by smuzaffar** [comment]
please test with cms-sw/cmsdist#4378

**Comment by fabiocos** [comment]
@abrinke1 is this the backport of something? Otherwise please propose it first in master

**Comment by abrinke1** [comment]
@fabiocos , @rekovic ,
PR to 10_3_X can be found here: https://github.com/cms-sw/cmssw/pull/24766
Cheers,
Andrew

**Comment by thomreis** [comment]
backport of #24766

**Comment by thomreis** [comment]
+1

**Comment by thomreis** [comment]
Hi @abrinke1 
since 10_2 is not used anymore this PR can probably be closed.

**Pull request closed without merging**
