### PR TITLE
 hltDiff: fix comparison of trigger candidates with different process name

### PR DESCRIPTION
**Pull request by fwyzard**
fix the comparison of the trigger candidates when the old and new collections have a different process name

### CODE REVIEW

**Comment by fwyzard** [comment]
+1

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
@davidlange6 , could you pick this up for the next 8.0.x release as well ?

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
hltDiff is not used in any workflow (yet), please disregard the failures

**Comment by davidlange6** [comment]
+1

**Pull request merged**
