### PR TITLE
New offline ID

### PR DESCRIPTION
**Pull request by jbrands**

### CODE REVIEW

**Comment by cvuosalo** [comment]
@jbrands: Please provide a description for this PR. What is the ID for, and why is it going into 74 at such a late date?

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
xml files should be updated in https://github.com/cms-data/RecoJets-JetProducers
not in cms-sw/cmssw

**Comment by jbrands** [comment]
I will integrate the code in the open CMSSW_7_6_0 release, do the checking and open a new pull request

**Pull request closed without merging**
