### PR TITLE
Fix clang tidy mistakes

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Fix a couple of instances where the newly proposed clang-tidy checks would generate the wrong code.

### CODE REVIEW

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/30509	042ab15 
- technical

**Comment by jfernan2** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
