### PR TITLE
change offline dqm to stage1 and change online dqm layout

### PR DESCRIPTION
**Pull request by jingyucms**
76x version of #10568 
Trying to:
1) change online dqm layout
2) switch offline dqm to stage1

### CODE REVIEW

**Comment by deguio** [comment]
+1

**Comment by deguio** [comment]
@jingyucms 
please rebase this one.
thanks,
F.

**Comment by deguio** [comment]
also see my comment in the correspondent 74 release.
thanks,
F.

**Comment by jingyucms** [comment]
Close

**Pull request closed without merging**
