### PR TITLE
Ecal Payload Inspector : plots display, exhaustive treatment

### PR DESCRIPTION
**Pull request by depasse**
To complete the actual Plot Display in Payload Inspector for Ecal

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by depasse** [comment]
What can I do to correct this error (timeout) ???

**Comment by fabiocos** [comment]
please test

let's repeat it

**Comment by arunhep** [comment]
@depasse this is too big a PR to be checked in one go.
can this be factorized ?

**Comment by depasse** [comment]
I don't understand : all the comparisons are OK.  
Is it a software limitation ?  
All the files.cc have the same scheme.  So (human) checking one of them is enough.
And how to factorize ?

**Comment by davidlange6** [comment]
a few obvious things come to mind given the massive code duplication (its 10k lines to make ~50 plots if I understand)
 - helper functions instead of repeating stanzas of code N times
 - templating when you are doing the same thing with multiple different data types

**Comment by civanch** [comment]
+1

**Comment by depasse** [comment]
This PR is closed and replaced by #23517.  The author H. Sayed has grouped several functions that were repeated.

**Pull request closed without merging**
