### PR TITLE
EDProducer/EDAnalyzer and consumes migration for some DT classes

### LINKED ISSUE #25: Deprecated EDAnalyzer in DTCalibration
As discussed here
https://github.com/cms-sw/cmssw/pull/35184#issuecomment-917138455
there are some deprecated EDAnalyzer in DTCalibration
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-422427/18493/llvm-analysis/legacy-mod-sa.txt

Will be follow-up by @swagata87 @namapane

### PR DESCRIPTION
**Pull request by namapane**
Migrate some DT classes according to issue https://github.com/cms-AlCaDB/AlCaTools/issues/25 and comment to #35208
https://github.com/cms-sw/cmssw/pull/35208#discussion_r705303803

fixes https://github.com/cms-AlCaDB/AlCaTools/issues/25

### CODE REVIEW

**Comment by tvami** [comment]
@namapane thanks for taking care of this. Can you please add `fixes https://github.com/cms-AlCaDB/AlCaTools/issues/25` to the description? This is a github hook that will automatically close the issue when this PR is merged. Thanks!

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
> **CMS StaticAnalyzer warnings**: There are 1 EventSetupRecord::get warnings. See https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-a0c9c1/18561/llvm-analysis/esrget-sa.txt for details.

/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_12_1_X_2021-09-13-1100/src/CalibMuon/DTCalibration/plugins/DTTPAnalyzer.cc:91:3: warning: function 'DTTPAnalyzer::beginRun' calls function 'edm::eventsetup::EventSetupRecord::get<edm::ESHandle<DTGeometry> >' with argument of type 'edm::ESHandle<DTGeometry>'. Direct call of function EventSetupRecord::get(ESHandle&) is deprecated and should be replaced with a call to EventSetup::getHandle(ESGetToken&). To use ESGetToken see https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideHowToGetDataFromES#In_ED_module To get data with the token see https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideHowToGetDataFromES#Getting_data_from_EventSetup_wit [deprecated.ESRecordGetChecker]

**Comment by namapane** [comment]
> 
> 
> > **CMS StaticAnalyzer warnings**: There are 1 EventSetupRecord::get warnings. See https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-a0c9c1/18561/llvm-analysis/esrget-sa.txt for details.
> 
> /data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_12_1_X_2021-09-13-1100/src/CalibMuon/DTCalibration/plugins/DTTPAnalyzer.cc:91:3: warning: function 'DTTPAnalyzer::beginRun' calls function 'edm::eventsetup::EventSetupRecord::get<edm::ESHandle >' with argument of type 'edm::ESHandle'. Direct call of function EventSetupRecord::get(ESHandle&) is deprecated and should be replaced with a call to EventSetup::getHandle(ESGetToken&). To use ESGetToken see https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideHowToGetDataFromES#In_ED_module To get data with the token see https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideHowToGetDataFromES#Getting_data_from_EventSetup_wit [deprecated.ESRecordGetChecker]

This one is being migrated in  #35184

**Comment by namapane** [comment]
Ops, I made the merge but now that has to be tested on top of  #35184...

**Comment by tvami** [comment]
> -code-checks
> 
> Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-35255/25257
> 
> ERROR: Build errors found during clang-tidy run.
> 
> ```
> CalibMuon/DTCalibration/plugins/DTTPAnalyzer.cc:77:52: error: too many arguments to function call, expected 2, have 3 [clang-diagnostic-error]
>                                                    consumesCollector());
>                                                    ^
> /cvmfs/cms-ib.cern.ch/nweek-02698/slc7_amd64_gcc900/cms/cmssw-patch/CMSSW_12_1_X_2021-09-13-2300/src/FWCore/PluginManager/interface/PluginFactory.h:63:24: note: 'create' declared here
> --
> gmake: *** [config/SCRAM/GMake/Makefile.coderules:129: code-checks] Error 2
> gmake: *** [There are compilation/build errors. Please see the detail log above.] Error 2
> ```

Hi @namapane have you seen this code check failure above?

**Comment by namapane** [comment]
> Hi @namapane have you seen this code check failure above?

That's what I was referring to in the comment above:
The merge of  #35184 caused a conflict in this file, which I tried to resolve with the latest commit (merge+resolve conflict)
I do not understand what went wrong as the error message refers to modifications of #35184

I wil try to rebase my branch from scratch...

**Comment by namapane** [comment]
It did not work. It compiles in my local area if I simply check out  CalibMuon/DTDigiSync and  RecoLocalMuon/DTRecHit/ which were modified upsteram. 
Unless anyone has a suggestion on how to handle this, the only solution I see is to close this PR and open a new one.

**Comment by tvami** [comment]
Hi @namapane can you please rebase to the latest IB? 
i.e. something like 
```
cmsrel CMSSW_12_1_X_2021-09-15-1100
cd CMSSW_12_1_X_2021-09-15-1100/src
cmsenv
git cms-init
git checkout DT_migrations01
git add-pkg CalibMuon/DTCalibration
git add-pkg RecoLocalMuon/DTSegment
git rebase -i CMSSW_12_1_X_2021-09-15-1100
```
....
there might be conflicts to be merged by hand
```
git rebase --continue
git push my-cmssw +HEAD:DT_migrations01
```

I hope this will resolve this issue

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
+alca

 * comparison diffs are only in the msg logger
 * there is still a lot of SA warnings, but that's for another PR: 
 https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-a0c9c1/18662/llvm-analysis/

**Comment by slava77** [comment]
+reconstruction

for https://github.com/cms-sw/cmssw/pull/35255	44e249b 
- code changes in reco are somewhat unrelated to the main topic of the PR; here only `RecoLocalMuon/DTSegment/src/DTRecSegment2DExtendedProducer.h` is updated to use `edm::stream`, which is OK
- jenkins tests pass

**Pull request merged**
