### PR TITLE
[HGCAL] make makeHGCalValidationPlots.py executable again

### PR DESCRIPTION
**Pull request by apsallid**
#### PR description:

PR [#34702](https://github.com/cms-sw/cmssw/pull/34702) accidentally changed the permissions on `makeHGCalValidationPlots.py`, so the command `makeHGCalValidationPlots.py` doesn't work. This PR should correct this mistake and make `makeHGCalValidationPlots.py` executable again. 

#### PR validation:

I have tested locally that the command works now as usual. 

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

This is not a backport. 

@rovere @felicepantaleo @ebrondol @lecriste @mrodozov @waredjeb

### CODE REVIEW

**Comment by perrotta** [comment]
If this only changes the permissions of a script, it can be probably merged as such, even without testing...
One should just certify that the permissions were actually modified as wanted

**Comment by mrodozov** [comment]
@perrotta it's evident from just seeing the file in files:
https://github.com/cms-sw/cmssw/pull/34909/files

**Comment by perrotta** [comment]
> @perrotta it's evident from just seeing the file in files:
> https://github.com/cms-sw/cmssw/pull/34909/files

Thank you @mrodozov 
How can I verify which are the permissions from there? I would have naively imported this PR in an IB locally and looked at the permissions there... But if it can be done faster it's even better!

**Comment by smuzaffar** [comment]
@perrotta , it shows the permission there e.g.
```
 Validation/HGCalValidation/scripts/makeHGCalValidationPlots.py  100644 → 100755
```
so looks good.

**Comment by perrotta** [comment]
Uhm, I'm learning.

Therefore, the key is
- `100644` means `-rw-r--r--`  where:
```
4 == r--
4 == r--
6 == rw-
100 == -
```
- `100755` means `-rwxr-xr-x`  where:
```
5 == r-x
5 == r-x
7 == rwx
100 == -
```

Cool, I didn't know...

**Comment by perrotta** [comment]
merge

**Comment by jfernan2** [comment]
+1
for the records

**Pull request merged**
