### PR TITLE
Displaced tracking validation for Run 3 and Phase 2

### PR DESCRIPTION
**Pull request by jalimena**
#### PR description:

This PR adds a collection to the tracking validation to validate displaced tracks. In particular, the usual tip and lip cuts on the tracking particles are relaxed. The collection is turned on only by use of a procModifier as shown below.

#### PR validation:

I've run the RECO, validation, and DQM steps (standard and trackingOnly) for ttbar and DisplacedSUSY samples, with Run 3 and Phase 2 conditions. 

For example:
`cmsDriver.py step3 --conditions auto:phase1_2021_realistic -s RAW2DIGI,L1Reco,RECO,RECOSIM,EI,PAT,VALIDATION:@standardValidation+@miniAODValidation,DQM:@standardDQM+@ExtraHLT+@miniAODDQM --datatier GEN-SIM-RECO,MINIAODSIM,DQMIO -n 200 --geometry DB:Extended --era Run3 --eventcontent RECOSIM,MINIAODSIM,DQM --procModifiers displacedTrackValidation --no_exec`
run over the displaced SUSY sample in Run 3 conditions (0 PU), and then harvesting the DQM, produces these plots as output: 
https://jalimena.web.cern.ch/jalimena/plots/track_validation_plots_dispSUSY_2021PU0_11_3_0_pre2_ProcModifier/

and
`cmsDriver.py step3_trackingOnly --conditions auto:phase2_realistic_T15 -s RAW2DIGI,RECO:reconstruction_trackingOnly,VALIDATION:@trackingOnlyValidation,DQM:@trackingOnlyDQM --datatier GEN-SIM-RECO,DQMIO -n 200 --geometry Extended2026D49 --era Phase2C9 --eventcontent RECOSIM,DQM --procModifiers displacedTrackValidation --no_exec`
run over a ttbar sample in phase 2 conditions with the trackingOnly sequence (0 PU), and then harvesting the DQM, produces these plots as output: 
https://jalimena.web.cern.ch/jalimena/plots/track_validation_plots_ttbar_phase2PU0_trackingOnly_11_3_0_pre2_ProcModifier/

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

not a backport

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
@jalimena this PR is adding around 20k new MEs, I wonder if such a huge number of plots and possibilities is actually needed for Validation, I can imagine what a handicap can be to check all of them with releases and samples.

On the other hand the configuration is creating the new plots for every MC workflow, could you please reduce it to just Phase2 and Run3 samples?

Thanks
All details about the changes introduced in the workflows and samples here:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_11_2_X_2020-11-16-2300+57113f/39929/dqm-histo-comparison-summary.html

**Comment by jalimena** [comment]
> @jalimena this PR is adding around 20k new MEs, I wonder if such a huge number of plots and possibilities is actually needed for Validation, I can imagine what a handicap can be to check all of them with releases and samples.
> 
> On the other hand the configuration is creating the new plots for every MC workflow, could you please reduce it to just Phase2 and Run3 samples?
> 
> Thanks
> All details about the changes introduced in the workflows and samples here:
> https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_11_2_X_2020-11-16-2300+57113f/39929/dqm-histo-comparison-summary.html

Hi @jfernan2 indeed I don't want to add (or look at) 20k new plots! One thing I see I can do is to remove them for fastsim, but maybe that's not a great idea, given that fastsim is beginning to be used for long-lived particle signals? I also see in the code how I can add the collection just for phase 2 (i.e. with things like `phase2_tracker.toModify()` in `Validation/RecoTrack/python/TrackValidation_cff.py`), but I'm unsure how to do it for just Run 3 here - maybe with `phase1Pixel.toModify()` as I see elsewhere in the package? @mtosi  or other tracking experts, can you help me? What do you recommend I do, in practice, to redo the number of plots?

**Comment by mmusich** [comment]
@jalimena 

> , but I'm unsure how to do it for just Run 3 here - maybe with phase1Pixel.toModify() as I see elsewhere in the package?

there is a run3 specific modifier:

https://github.com/cms-sw/cmssw/blob/master/Configuration/Eras/python/Modifier_run3_common_cff.py

**Comment by jalimena** [comment]
thanks a lot, @mmusich ! I've tested that the new commit works for Run 3 as I expect, will do the same for phase 2 now.

**Comment by jalimena** [comment]
And I can confirm that the latest commit also works as I expect for phase2. If I have satisfied the request, can an authorised user (maybe @jfernan2 ?) ping the bot for the PR tests again?

**Comment by jfernan2** [comment]
please test

**Comment by jalimena** [comment]
If I understand correctly, the some runTheMatrix tests failed because they couldn't open the input file. I assume that does not indicate a problem with my PR, and I shouldn't worry?

**Comment by jfernan2** [comment]
You are right @jalimena 
It seems a temporary problem with AAA
I am triggering the tests again

**Comment by jfernan2** [comment]
please test

**Comment by jalimena** [comment]
ok thanks @jfernan2

**Comment by jfernan2** [comment]
Thanks @jalimena for reducing the number of datasets to Phase2 and Run3. Beyond the number of MEs added on top of the already existing 25k plots in Tracking folder for RelVal samples which may produce at some point memory problems in production, may I ask you to do a final revision of the plots to see if this is what you want?

https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_11_2_X_2020-11-17-2300+57113f/39960/dqm-histo-comparison-summary.html

For example, I have found the following ones which I am not sure if it is simply low stats or something else:

Empty (or almost) plots (too tight cuts or low stats in RelVal samples provided by Jenkins tests?):
cutsRecoMuonSeededStepInOutByOriginalAlgo_trackingParticleRecoAsssociation
cutsRecoJetCoreRegionalStepByOriginalAlgoHp_trackingParticleRecoAsssociation
cutsRecoMuonSeededStepInOutByOriginalAlgoHp_trackingParticleRecoAsssociation
cutsRecoJetCoreRegionalStepHp_trackingParticleRecoAsssociation
cutsRecoMuonSeededStepInOutHp_trackingParticleRecoAsssociation
cutsRecoJetCoreRegionalStep_trackingParticleRecoAsssociation

Plots with entries but zero values (right binning?):
chargeMisId*
duplicatesRate*
effic_vs_dz*
fakerate_vs_*
num_*
chi2mean_vs_phi

Thank you!

**Comment by jalimena** [comment]
Thanks, @jfernan2 . @mtosi  and @mmusich , I think I need help answering @jfernan2 's questions above :/ 
I'm not sure
- if we really need all the plots in the cutsReco* list above, or if I need to loosen some cuts for them? I know at least some of them will be useful, for example to look at the muon-seeded steps.
- why there would be so many plots with entries but zero values. Are the entries getting to the overflow or underflow? Why? Sorry I don't understand how to figure this out. Of course I know that this doesn't happen for every instance of say effic_vs_dz, but it's confusing that it's happening for some

**Comment by jfernan2** [comment]
Hi, a quick question: has this PR been privately tested with its related one https://github.com/cms-sw/cmssw/pull/32036  ?
Thanks

**Comment by jalimena** [comment]
> Hi, a quick question: has this PR been privately tested with its related one #32036 ?
> Thanks

I have not done that yet, but could do so ~tomorrow if @doujadarej has not done it.

**Comment by silviodonato** [comment]
> > Hi, a quick question: has this PR been privately tested with its related one #32036 ?
> > Thanks
> 
> I have not done that yet, but could do so ~tomorrow if @doujadarej has not done it.

@jalimena do you have any news?

**Comment by jalimena** [comment]
> #32036

Hi @silviodonato , @doujadarej commented in PR #32036  that she had tested the two PRs together, yes.

**Comment by silviodonato** [comment]
> > #32036
> 
> Hi @silviodonato , @doujadarej commented in PR #32036 that she had tested the two PRs together, yes.

ok, thanks. @cms-sw/dqm-l2 do you have further comments?

**Comment by jfernan2** [comment]
Yes, my comment above https://github.com/cms-sw/cmssw/pull/32157#issuecomment-730271137  still holds, and also Juliette had questions in her comment https://github.com/cms-sw/cmssw/pull/32157#issuecomment-730286363

This PR is adding 20k extra plots, I am afraid it needs some reduction unless something that it missed had changed in between...

**Comment by jalimena** [comment]
I am waiting for more feedback from the tracking experts, and to be honest I have also been preoccupied with other issues that are more pressing for the end of the year, so I haven't been able to push. Haven't forgotten about this PR, though!

**Comment by jalimena** [comment]
hi all,

I have modified this PR so that now, instead of running the displaced tracking validation for every run 3 and phase 2 workflow, I have enabled it only with a procModifier, so that we can in principle turn it on only as needed. I am currently finishing some tests, and then I will update the PR description at the top to explain. Furthermore, I have asked by email, in parallel, for help with modifying Configuration/PyReleaseValidation appropriately to turn this validation sequence on for the processes we are interested in. @mtosi asked PPD by email about our proposed solution and workflow.

**Comment by jalimena** [comment]
Ok, my tests have finished, and I have updated the PR description to reflect them and my recent changes.

Still to do:
- modify Configuration/PyReleaseValidation appropriately to turn this validation sequence on for the processes we are interested in (I have asked for help by email)
- confirm with PPD/PDMV and DQM conveners that this validation plan is reasonable (awaiting a response to Mia's email)

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
please abort

**Comment by jfernan2** [comment]
please test with #32036

**Comment by jalimena** [comment]
I believe a test failed only because an input file couldn't be opened, is that correct? Please let me know if there is anything I need to do.

**Comment by jfernan2** [comment]
please test with #32036

**Comment by jfernan2** [comment]
There are a lot of changes in 140.53 unrelated to this PR.... has somebody seen it before?
Thanks

**Comment by makortel** [comment]
> There are a lot of changes in 140.53 unrelated to this PR.... has somebody seen it before?
> Thanks

Note

> The workflows 140.53 have different files in step1_dasquery.log than the ones found in the baseline. You may want to check and retrigger the tests if necessary.

in the comparison summary message.

**Comment by jfernan2** [comment]
please test with #32036

**Comment by jfernan2** [comment]
> > There are a lot of changes in 140.53 unrelated to this PR.... has somebody seen it before?
> > Thanks
> 
> Note
> 
> > The workflows 140.53 have different files in step1_dasquery.log than the ones found in the baseline. You may want to check and retrigger the tests if necessary.
> 
> in the comparison summary message.

Thanks @makortel I hadn't noticed it

**Comment by makortel** [comment]
There is some more information in https://github.com/cms-sw/cmssw/issues/32755

**Comment by jfernan2** [comment]
> Still to do:
> 
> * modify Configuration/PyReleaseValidation appropriately to turn this validation sequence on for the processes we are interested in (I have asked for help by email)
> * confirm with PPD/PDMV and DQM conveners that this validation plan is reasonable (awaiting a response to Mia's email)

@jalimena do you plan to include those in this PR or in an independent one?

**Comment by jalimena** [comment]
> > Still to do:
> > 
> > * modify Configuration/PyReleaseValidation appropriately to turn this validation sequence on for the processes we are interested in (I have asked for help by email)
> > * confirm with PPD/PDMV and DQM conveners that this validation plan is reasonable (awaiting a response to Mia's email)
> 
> @jalimena do you plan to include those in this PR or in an independent one?

@jfernan2 If I get some advice from anyone soon (perhaps @mtosi ?) about how to modify Configuration/PyReleaseValidation, I will happily include it promptly in this PR. However, I guess it is not strictly necessary and I can open a new one for it. If you all are ready to sign and merge it like ~now, then I can for sure open a new PR for the small additions needed.

**Comment by jfernan2** [comment]
Ok, so let's decouple the plots from their actual enabling. Thanks

**Comment by jfernan2** [comment]
+1

**Comment by jalimena** [comment]
thanks to you!

**Comment by silviodonato** [comment]
+1

**Pull request merged**
