### PR TITLE
Add max mass option to HLT singlet

### PR DESCRIPTION
**Pull request by rmanzoni**
will create the back port to 92X once this PR is good to go

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please make a 92X PR as well.

**Comment by rmanzoni** [comment]
@Martin-Grunewald I just realised it might be useful: what if we take the chance and also add the possibility to cut on the absolute charge?

**Comment by Martin-Grunewald** [comment]
Why? Typically these "sidebands" are used to get the combinatorial background.

**Comment by rmanzoni** [comment]
it's true in general, but perhaps not always.

For example, for my 3-muon path, I am considering to explicitly require the correct charge already at HLT as a fallback in case rates are too high.

I think it's a nice addition but it's certainly not critical (after all nobody asked for it for the past N years...), if you think it's not so useful in general I can always find another way to do it.

**Comment by Martin-Grunewald** [comment]
Given three muons yields 8 charge combinations, two of which have +++ or ----, so a reduction in (background) rate of 25% cutting on |Q|<=1, and loosing the sidebands to determine the bg from data...

**Comment by Martin-Grunewald** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Comment by rmanzoni** [comment]
@Martin-Grunewald 

just to conclude the discussion, I don't mean to reopen the PR now that is merged: it's not always true that one estimates backgrounds from 'wrong-sign' events. 
For instance it only rarely happens in BPH where you might have resonances in 'correct-sign' events that you wouldn't have otherwise. The many opposite-sign di-muon L1 seeds are a statement to this.
Staying on this specific case, for our tau3mu preliminary analysis we didn't use charge-3 events and probably we won't in the future either.

However, this isn't the best place to discuss analysis strategies, I simply thought this is a minor additional feature to an ubiquitous module that wouldn't do no harm, but it might be useful in some cases. We can reiterate later with a new PR if we'll agree to do so.

**Pull request merged**
