### PR TITLE
Updating e/gamma Mustache SuperCluster regressions for 80X

### PR DESCRIPTION
**Pull request by mmusich**
# Summary of changes in Global Tags
## RunI simulation
- **RunI Ideal scenario** : [80X_mcRun1_design_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_mcRun1_design_v4) as [80X_mcRun1_design_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_mcRun1_design_v3) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/80X_mcRun1_design_v4/80X_mcRun1_design_v3): 
  - Updated Mustache SuperCluster Regressions for 80X
- **RunI Heavy Ions scenario** : [80X_mcRun1_HeavyIon_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_mcRun1_HeavyIon_v4) as [80X_mcRun1_HeavyIon_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_mcRun1_HeavyIon_v3) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/80X_mcRun1_HeavyIon_v4/80X_mcRun1_HeavyIon_v3): 
  - Updated Mustache SuperCluster Regressions for 80X
- **RunI Realistic scenario** : [80X_mcRun1_realistic_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_mcRun1_realistic_v4) as [80X_mcRun1_realistic_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_mcRun1_realistic_v3) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/80X_mcRun1_realistic_v4/80X_mcRun1_realistic_v3): 
  - Updated Mustache SuperCluster Regressions for 80X
- **RunI Proton-Lead scenario** : [80X_mcRun1_pA_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_mcRun1_pA_v4) as [80X_mcRun1_pA_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_mcRun1_pA_v3) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/80X_mcRun1_pA_v4/80X_mcRun1_pA_v3): 
  - Updated Mustache SuperCluster Regressions for 80X
## RunII simulation
- **RunII Ideal scenario** : [80X_mcRun2_design_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_mcRun2_design_v4) as [80X_mcRun2_design_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_mcRun2_design_v2) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/80X_mcRun2_design_v4/80X_mcRun2_design_v2): 
  - Updated Mustache SuperCluster Regressions for 80X
  - additions of 8 labels for `JetResolutionRcd` and 4 labels for `JetResolutionScaleFactorRcd`
- **RunII CRAFT scenario** : [80X_mcRun2cosmics_startup_peak_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_mcRun2cosmics_startup_peak_v2) as [80X_mcRun2cosmics_startup_peak_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_mcRun2cosmics_startup_peak_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/80X_mcRun2cosmics_startup_peak_v2/80X_mcRun2cosmics_startup_peak_v1): 
  - Updated Mustache SuperCluster Regressions for 80X
- **RunII Asymptotic scenario** : [80X_mcRun2_asymptotic_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_mcRun2_asymptotic_v4) as [80X_mcRun2_asymptotic_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_mcRun2_asymptotic_v2) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/80X_mcRun2_asymptotic_v4/80X_mcRun2_asymptotic_v2): 
  - Updated Mustache SuperCluster Regressions for 80X
  - additions of 8 labels for `JetResolutionRcd` and 4 labels for `JetResolutionScaleFactorRcd`
- **RunII Startup scenario** : [80X_mcRun2_startup_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_mcRun2_startup_v4) as [80X_mcRun2_startup_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_mcRun2_startup_v2) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/80X_mcRun2_startup_v4/80X_mcRun2_startup_v2): 
  - Updated Mustache SuperCluster Regressions for 80X
  - additions of 8 labels for `JetResolutionRcd` and 4 labels for `JetResolutionScaleFactorRcd`
- **RunII Heavy Ions scenario** : [80X_mcRun2_HeavyIon_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_mcRun2_HeavyIon_v3) as [80X_mcRun2_HeavyIon_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_mcRun2_HeavyIon_v2) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/80X_mcRun2_HeavyIon_v3/80X_mcRun2_HeavyIon_v2): 
  - Updated Mustache SuperCluster Regressions for 80X
  - Updated L1T Calo Parameters configuration changing the thresholds for the stage-1 MB bits. 
## RunII data
- **RunII Offline processing** : [80X_dataRun2_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_dataRun2_v4) as [80X_dataRun2_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_dataRun2_v3) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/80X_dataRun2_v4/80X_dataRun2_v3): 
  - Updated Mustache SuperCluster Regressions for 80X
## Upgrade
- **PhaseI design scenario** : [80X_upgrade2017_design_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_upgrade2017_design_v3) as [80X_upgrade2017_design_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/80X_upgrade2017_design_v2) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/80X_upgrade2017_design_v3/80X_upgrade2017_design_v2): 
  - Updated Mustache SuperCluster Regressions for 80X
# 

This combines the needs in terms of conditions of #13000 and #13115

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
+1

**Comment by slava77** [comment]
@mmusich 
is run1_data update real (80X_dataRun2_v3 -> 80X_dataRun2_v4) or are all the IOVs in reality for run2?

**Comment by mmusich** [comment]
@slava77 there are no new IOVs. We are just adding entirely new labels.

**Comment by slava77** [comment]
uhm, but then there is no update in run1 mc.

**Comment by mmusich** [comment]
@slava77 indeed there is not. No update was queued for that workflow.

**Comment by matteosan1** [comment]
The code is crashing in runTheMatrix -l limited in workflow 5.1 and 25.0 both using --conditions auto:run1_mc  since it is not finding the new payloads.

**Comment by mmusich** [comment]
@matteo1 in relation to PR https://github.com/cms-sw/cmssw/pull/13000 we need to update run-1 MC as well.

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
