### PR TITLE
Switch by default to new flavour tool based on Hadrons. Update of exampl...

### PR DESCRIPTION
**Pull request by acaudron**
...e scripts.
Same as PR#8049 for 75x:
Switch for the Btag DQM to the new jet flavour tool described here:
https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideBTagMCTools#Hadron_based_jet_flavour_definit
and already default in PAT.
Examples scripts are also updated accordingly.
Possibility to use the old flavour tool is conserved, especially as the new tool, targeting PFJets, cannot be applied on some jet collections as CaloJets.

### CODE REVIEW

**Comment by deguio** [comment]
+1

**Comment by acaudron** [comment]
As PR#8049 was merged in 75x, perhaps this can be also merged in 74x?
Thanks!

**Comment by deguio** [comment]
+1

**Comment by ferencek** [comment]
@davidlange6, can you please merge this PR (it's been fully approved for more than a week and its 75X equivalent #8049  has already been merged)

**Comment by ferencek** [comment]
What's the hold up here?

**Comment by ferencek** [comment]
This PR got left out of the final 740 release. Was there a specific reason for that and can this PR be included in a later 74X release?

**Comment by davidlange6** [comment]
@ferencek - pushing new features back to 74x needs some validation first in 75x (so pre1) - we can back port these changes to 74x in the coming weeks.

**Comment by ferencek** [comment]
@davidlange6, thank you for clarifying.

**Comment by ferencek** [comment]
Based on the previous discussion, I assume this PR can now be merged.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
