### PR TITLE
Monitor duplicateMerge track algo in MultiTrackValidator

### PR DESCRIPTION
**Pull request by makortel**
This PR is a follow-up to #12577 by adding the monitoring of duplicateMerge to tracking validation.

Tested in CMSSW_8_0_X_2015-12-03-2300, expecting addition of "duplicateMerge" algorithm in MTV summary plots and corresponding subfolders for the plots.

@rovere @VinInn

### CODE REVIEW

**Comment by makortel** [comment]
It would be nice to get this in the same pre-release as #12577.

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
