### PR TITLE
Backport of #6030. Add features offline validation for71 x

### PR DESCRIPTION
**Pull request by tlampen**
In offline validation: two bugfixes and lots of improvements to automatize
plotting.

### CODE REVIEW

**Comment by davidlange6** [comment]
I don't think this is needed in 71x. Is there any reason?

**Comment by frmeier** [comment]
@davidlange6 : If you can guarantee that there will never be a need or request to run alignment on any data/MC on 71x, then I agree. If you cannot give this guarantee, please merge in.

**Comment by davidlange6** [comment]
Given the lack of such data I guess we can wait and expend effort when such data exists.



On Jan 24, 2015, at 11:19 AM, Frank Meier <notifications@github.com<mailto:notifications@github.com>> wrote:


@davidlange6<https://github.com/davidlange6> : If you can guarantee that there will never be a need or request to run alignment on any data/MC on 71x, then I agree. If you cannot give this guarantee, please merge in.

**Comment by frmeier** [comment]
@davidlange6 Such data indeed exists:
https://cmsweb.cern.ch/das/request?view=list&limit=10&instance=prod%2Fglobal&input=dataset%3D%2F*%2FCMSSW_7_1*TkAl*%2F*ALCARECO*
and we are using it. Sorry for my rhetoric question before, I knew that answer already ;).
Bottomline: the PR is needed and we alignment conveners asked for it.

**Comment by davidlange6** [comment]
+1
thanks for the reminder about this unique sample..

**Pull request merged**
