### PR TITLE
Adjust clang-format after CMSSW_11_0_X_2019-06-21-1100

### PR DESCRIPTION
**Pull request by fabiocos**
#### PR description:

Manual adjustments of comments after clang-format cleaning up to CMSSW_11_0_X_2019-06-21-1100.
In some cases the proposal by clang has been left untouched, as the fixed version looks to me more ugly.

#### PR validation:

Code compiles.

### CODE REVIEW

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
this PR is overlapping with #27297:
```
Testing PR #  27303  for branch  master
File  CommonTools/RecoAlgos/interface/CosmicTrackingParticleSelector.h  modified in PRs #  ['27303', '27297']
File  CommonTools/RecoAlgos/interface/RecoTrackSelectorBase.h  modified in PRs #  ['27303', '27297']
File  RecoEgamma/ElectronIdentification/interface/EBEECutValues.h  modified in PRs #  ['27303', '27297']
File  RecoEgamma/ElectronIdentification/test/VIDUsageExample.cc  modified in PRs #  ['27303', '27297']
File  RecoEgamma/PhotonIdentification/src/PhotonMIPHaloTagger.cc  modified in PRs #  ['27303', '27297']
```
I will merge that one first, and update this accordingly

**Comment by fabiocos** [comment]
please test

DQM changes are related to #27235, let's repeat the test for a clean comparison

**Comment by perrotta** [comment]
+1
- Technical, and fine for reco, in case you want to merge it now that #27297 is also merged

**Comment by jfernan2** [comment]
+1

**Comment by fabiocos** [comment]
@ggovi @cvuosalo @christopheralanwest @tocheng the updates are merely technical and formal, I will integrate this PR in next IB, please have a look

**Comment by cvuosalo** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Comment by christopheralanwest** [comment]
+1

**Pull request merged**
