### PR TITLE
Single Strip Noise bug-fix

### PR DESCRIPTION
**Pull request by prolaymal**
Single strip Noise bug fix. See the presentation here: https://indico.cern.ch/event/368008/session/4/contribution/9/material/slides/0.pdf

### CODE REVIEW

**Comment by civanch** [comment]
@prolaymal , please, comment out or remove std::cout

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Comment by VinInn** [comment]
How this PR was tested?

**Comment by davidlange6** [comment]
that is a loaded question... we looked at (and got confirmation from both sim and tracker) the IB comparison plots (I think the discussion was in the 75x PR)

#7776

**Pull request merged**
