### PR TITLE
Porting code for GEM Local reconstruction in 75X

### PR DESCRIPTION
**Pull request by archiesharma**
Changes done in the files for local reconstruction of GEMs while moving the code from 62X_SLHC releases to 75X

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by ianna** [comment]
+1

@cmsbuild - this may eventually conflict with #8327. Both introduce the same change in Geometry/TrackerCommonData/plugins/DDPixFwdDiskAlgo.cc

**Comment by civanch** [comment]
+1

**Comment by cvuosalo** [comment]
+1

For #8407 6bd9a9972a135e7fd4ae908bd43c7a198e28beef

Porting code from 62X_SLHC for GEMs.

The code changes are satisfactory, and Jenkins test [results] (https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-8407/3634/summary.html) against baseline CMSSW_7_5_X_2015-03-18-2300 show no significant differences.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
