### PR TITLE
Remove RCSingleGaussianState.h

### PR DESCRIPTION
**Pull request by Teemperor**
This header isn't valid C++ code as SingleGaussianState is a template
but we use it as a non-templated class in this header. It seems this
code is broken since a while and not used - beside the other orphaned
header GaussianStateLessWeight.h which hangs out in /src/. As we
anyway also have a copy GaussianStateLessWeight.h in /interface/ and no
one seems to use the /src/ header, we just remove this too.

### CODE REVIEW

**Comment by Teemperor** [comment]
Part of the work going on regarding the C++ modules migration of CMSSW (tracked as issue https://github.com/cms-sw/cmssw/issues/15248). This PR is not meant to refactor things, but just to make these headers compile.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/19365	4216a92
- technical; TrackingTools/GsfTools/src/GaussianStateLessWeight.h  was replaced by TrackingTools/GsfTools/interface/GaussianStateLessWeight.h  by functionality about 10 years ago but the old file was never removed
- jenkins tests pass

**Comment by davidlange6** [comment]
merge

**Pull request merged**
