### PR TITLE
Merge surface deformations changes from May 2017 tracker alignment campaign for pixel alignment

### PR DESCRIPTION
**Pull request by usarica**
Motivation:
- Surface deformations were not propagated to the geometry after alignment.
- If the database does not contain a surface deformation record previously, alignment did not place one.
- We also observed precision issues during comparison of ySplit in TwoBowedSurfaceDeformation
- We also include here changes to trackselectionRefitting.py, which
1) Adds support for a wider range of dimuon constraints
2) Applies the constraint only to the track refitter with the common source (constaint was previously assigned to all track refitter regardless of common source)
3) Fixes process path in the presence of a constraint
4) Includes basic J/psi->mumu common selection support

Checks:
- Checks were done running different alignments with the pixel and strips at module, module unit or higher level alignments as part of the (ongoing) tracker alignment campaign.
- See these slides for a quick overview of items implemented and checks done: 
https://indico.cern.ch/event/624094/contributions/2627981/attachments/1476471/2287406/20170614.pdf
https://indico.cern.ch/event/624094/contributions/2627967/attachments/1476540/2287679/hpvalidation.pdf

Notes:
- Rebased on top of the commits in PR #19541, which fixes KF fitter and smoother classes to allow TwoBodyDecay trackParameter constraint to work again.
- A separate PR is being prepared for the follow-up changes in the HIPAlignmentAlgorithm (re-applying most of the commits reverted by the last commit in this PR)

### CODE REVIEW

**Comment by usarica** [comment]
Tagging @hroskes, who also co-authors the changes

**Comment by perrotta** [comment]
please test

**Comment by slava77** [comment]
-1

@usarica 
this PR is apparently superseded by #19583

please close this PR, unless there is a compelling reason for having the PRs reviewed separately.

**Comment by usarica** [comment]
I was asked to make separate PRs for alignment conveners to review separately. I would still suggest though that this PR be merged before the other two because it was due to a separate discussion with the Tracking group.

**Comment by usarica** [comment]
The PR was updated based on update in #19541

**Comment by ianna** [comment]
please test

**Comment by slava77** [comment]
-1

superseded by #19584

**Pull request closed without merging**
