### PR TITLE
fix configuration of GPU Pixel unpacker in Run-3 HLT menus post-#41632 [`13_2_X`]

### PR DESCRIPTION
**Pull request by missirol**
backport of #42410

#### PR description:

From the description of #42410:

>#41632 made the VCal-to-NumberOfElectrons conversion factors of the GPU pixel unpacker configurable from the python interface. Since their [default values for Phase-1](https://github.com/cms-sw/cmssw/blob/193041033d0c1947b0f942d8c086a73d6954b3c6/RecoLocalTracker/SiPixelClusterizer/plugins/SiPixelRawToClusterCUDA.cc#L129-L132) are valid for Run 2 (and not for Run 3), the Run-3 HLT menus became silently misconfigured as a result. This PR fixes that with a customisation function. The HLT menus will eventually be configured correctly in `ConfDB`, once HLT-menu development moves to the `13_2_X` cycle.
>
>In addition, the configuration parameter `isRun2` is removed from the plugin template `SiPixelRawToClusterCUDAT`, as #41632 made it unnecessary.

#### PR validation:

`addOnTests.py` passed.

#### If this PR is a backport, please specify the original PR and why you need to backport that PR. If this PR will be backported, please specify to which release cycle the backport is meant for:

#42410

Development of HLT menus for 2023 and beyond.

### CODE REVIEW

**Comment by missirol** [comment]
type bugfix

**Comment by missirol** [comment]
urgent

This fix should be included in `CMSSW_13_2_0`.

**Comment by missirol** [comment]
enable gpu

**Comment by missirol** [comment]
please test

**Comment by missirol** [comment]
+hlt

**Comment by clacaputo** [comment]
+reconstruction

**Comment by perrotta** [comment]
+1

**Comment by Martin-Grunewald** [comment]
Sorry to come back to this, but what about 
[process](https://cmssdt.cern.ch/lxr/ident?_i=process).hltCTPPSPixelClusters = [cms](https://cmssdt.cern.ch/lxr/ident?_i=cms).[EDProducer](https://cmssdt.cern.ch/lxr/ident?_i=EDProducer)( "CTPPSPixelClusterProducer",

**Comment by mmusich** [comment]
> Sorry to come back to this, but what about

this is CT-PPS, *not* SIPixel...

**Comment by Martin-Grunewald** [comment]
OK, so RP pixels, not SiPixels (for use with CTPPS activity)...

**Pull request merged**
