### PR TITLE
Updates to `TkAlV0sAnalyzer` and `V0Monitor`

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

This PR updates `TkAlV0sAnalyzer`: an analyzer that was introduced in https://github.com/cms-sw/cmssw/pull/43757 to monitor a new ALCARECO data-tier called `TkAlV0s` which contains the tracks and associated clusters, etc. from $K^0_s$→ππ and Λ→pπ decays. In order to test the analyzer the unit test `Miscellanea` is updated.
In the process I provide into 16913123210652c0e3829c213de9eda32ee9c6a3 some basic improvement to the existing V0 monitoring DQM module `V0Monitor`, mostly a `fillDescriptions` method.

#### PR validation:

`scram b runtests_Miscellanea` runs fine with this PR.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Not a backport, will be backported to CMSSW_14_0_X for 2024 data-taking validation purposes.

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by perrotta** [comment]
+alca

**Comment by mmusich** [comment]
ping @cms-sw/dqm-l2

**Comment by tjavaid** [comment]
+1

**Comment by mmusich** [comment]
@cms-sw/orp-l2 kind ping on this PR

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
