### PR TITLE
Remove Obsolete Geometry Scenarios

### PR DESCRIPTION
**Pull request by ianna**
Note: if any of the removed scenarios is indeed needed it should be restarted from either run 1 or run 2 default scenario.

### CODE REVIEW

**Comment by ianna** [comment]
+1

**Comment by ianna** [comment]
@cmsbuild - it's unrelated. There is no FastSimulation/​PileUpProducer package in the IB. That's the reason for failing relvals.

**Comment by ianna** [comment]
@cmsbuild - please, test again

**Comment by ianna** [comment]
@cmsbuild - ping!

**Comment by ianna** [comment]
@cmsbuild - please, re-trigger the tests. The errors were unrelated to this PR. Thanks.

**Comment by degano** [comment]
@cmsbuild please test
@ianna the key phrase is just the above, in the first line of a comment.

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
@cmsbuild please test

**Pull request merged**
