### PR TITLE
[TkAl] remove "old" all-in-one metatool from cmssw

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

Since when https://github.com/cms-sw/cmssw/pull/38304 is merged, the old "all-in-one"  tracker alignment offline validation meta-tool is orphaned, and the corresponding files remaining in `cmssw` serve no purpose.
I remove them here (~~PR still as a draft, so that Tk alignment people @TomasKello @henriettepetersen have a chance to have a look~~). 

#### PR validation:

`scram b runtests` runs fine.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

N/A

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by perrotta** [comment]
@mmusich you removed the "draft" flag: should we assume that that the Tk Alignment people has greenlighted these file removals, then? If so, this PR can be signed, as evidently no workflow is affected by it.

**Comment by perrotta** [comment]
+1
- Tested workflows not affected, and TkAl agrees on the removal, see https://github.com/cms-sw/cmssw/pull/43386#issuecomment-1829474279

**Comment by rappoccio** [comment]
+1

**Pull request merged**
