### PR TITLE
Cluster position plots per ring instead of per wheel

### PR DESCRIPTION
**Pull request by lmoreels**
In response to JIRA CMSTRACK-148, cluster position plots are made per ring instead of per wheel for the relevant partitions.

### CODE REVIEW

**Comment by idebruyn** [comment]
@dmitrijus could you please start the test?
PR for 80X is #15701

**Comment by dmitrijus** [comment]
+1

**Comment by idebruyn** [comment]
if all is fine with this PR, could it be merged? thanks.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
