### PR TITLE
CMSSW_14_0_X:Update HSCParticle object to be compatible with MiniAOD

### PR DESCRIPTION
**Pull request by enibigir**
#### PR description:

This PR is a backport of [PR#46840](https://github.com/cms-sw/cmssw/pull/46840) already merged.

### CODE REVIEW

**Comment by tvami** [comment]
backport of https://github.com/cms-sw/cmssw/pull/46840

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
I think it's ok to have the data format change, since we didnt produce any MC that would actually use this object

**Comment by tvami** [comment]
+analysis
 * see my comment in https://github.com/cms-sw/cmssw/pull/46867#issuecomment-2517970873

**Comment by tvami** [comment]
@cmsbuild ping

**Comment by mandrenguyen** [comment]
hold 
Will there be PRs to 14_1_X and 14_2_X?  I don't see them.

**Comment by tvami** [comment]
14_1_X was for HI, right? This is not relevant for that. 
14_2_X, hmm yeah maybe there it should be there

**Comment by enibigir** [comment]
I have prepared backports for both [14_1_X](https://github.com/cms-sw/cmssw/pull/46899) and [14_2_X](https://github.com/cms-sw/cmssw/pull/46900)

**Comment by enibigir** [comment]
@mandrenguyen @tvami

**Comment by mandrenguyen** [comment]
unhold
Thank you @enibigir

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
