### PR TITLE
Fix for GLOBAL_TAG table names in sqlite files

### PR DESCRIPTION
**Pull request by ggovi**
Workaround for the support of GTs in sqlite files.
The prefix 'GLOBAL_' is a keyword for sqlalchemy, which makes the tables starting with 'GLOBAL_' unreadable in sqlite.
The tables are created with lower case names to make the model happy, and then re-named.

### CODE REVIEW

**Comment by ggovi** [comment]
please test

**Comment by ggovi** [comment]
@smuzaffar
anything hanging here?

**Comment by smuzaffar** [comment]
CMSSW_9_0_X IB  was not available went the tests were requested. As IB is available now, so I have retsrated the test

**Comment by ggovi** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
