### PR TITLE
HLT VBF + Tau trigger modules for 2018

### PR DESCRIPTION
**Pull request by albertdow**
UPDATED:
This PR concerns two modules in `RecoTauTag/HLTProducers`. They are:

`src/PFJetsTauOverlapRemoval.cc` (edited)
This has been changed to loop over the full input jet collection and push_back all cross-cleaned jets.

`src/PFJetsMaxInvMassModule.cc` (new)
`interface/PFJetsMaxInvMassModule.h` 
This module looks at a PF jet collection and finds the max invariant mass pair. No cuts are applied on mjj at this stage. An additional feature allows the user to select whether the produced jet collection contains the found max invariant dijet mass pair only or drops these from the input collection. This is for a specific case of the VBF+Taus trigger.

The three triggers that will benefit from these modules are:
`HLT_(VBF_DoubleJet115_40)_DiTau_20`
`HLT_(VBF_DoubleJet40)_DiTau_115_20`
`HLT_(VBF_DoubleJet40)+SingleJet115_DiTau_20`
seeded by VBF L1 seeds.

These are currently under development/testing. They are based on the existing `HLT_VBF_DoubleLooseChargedIsoPFTau20_Trk1_eta2p1_Reg_v` triggers and should replace them. 

The PR will therefore be required asap to finalise the trigger configs.

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
Why do you have to add a module which compared to an existing module has reduced functionality,
according to your description above? The logic should become clear by the configuration of the new instance you need, setting the cut values appropriately so that the added selection does not really
reject events.

**Comment by albertdow** [comment]
You are right, the matching module may not be needed and has been removed. The only reason for having used it is that the existing module produces a collection of two or three jets only, whereas here it was set up such that all jets matched to L1 would be saved.

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1
If it is needed urgently, consider a backport PR for 10_0.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
