### PR TITLE
Add support for the gpu modifier at HLT [12.0.x]

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

When the `gpu` modifier is enabled, make the Pixel, ECAL and HCAL reconstruction running at HLT offloadable to a GPU.

#### PR validation:

Tested with
```bash
cmsDriver.py reHLT \
    --processName reHLT \
    -s HLT:@relval2021 \
    --conditions 120X_mcRun3_2021_realistic_v4 \
    --datatier GEN-SIM-DIGI-RAW \
    -n 10 \
    --eventcontent FEVTDEBUGHLT \
    --geometry DB:Extended \
    --era Run3 \
    --procModifiers gpu \
    --filein /store/relval/CMSSW_12_0_0_pre6/RelValTTbar_14TeV/GEN-SIM-DIGI-RAW/PU_120X_mcRun3_2021_realistic_v4_JIRA_129-v1/00000/79c06ed5-929b-4a57-a4f2-1ae90e6b38c5.root
```

With this change, the `customizeHLTforPatatrack()` customisation will be tested as part of the `.502`, `.512` and `.522` GPU workflows, and `customizeHLTforPatatrackTriplets()` with the `.506` workflow.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Backport to 12.0.0 of #34978.

### CODE REVIEW

**Comment by fwyzard** [comment]
enable gpu

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
Rebased on top of CMSSW_12_0_0, and added support for running the HLT step on GPU in runTheMatrix.

**Comment by fwyzard** [comment]
enable gpu

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by qliphy** [comment]
@cms-sw/pdmv-l2  Any comment?

**Comment by bbilin** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
