### PR TITLE
Pr940 RPCTwinMux in L1TRawToDigi Sequence

### PR DESCRIPTION
**Pull request by rekovic**
Fix: put dropped RPCTwinMux unpacker back into L1T unpacker sequence.

### CODE REVIEW

**Comment by rekovic** [comment]
please test

**Comment by rekovic** [comment]
backport of #21353

**Comment by rekovic** [comment]
+1

**Comment by fabiocos** [comment]
@rekovic is this PR still needed in 94X or can just be closed?

**Comment by rekovic** [comment]
@fabiocos 
Yes, please merge this.

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
@rekovic sorry, for which studies is this needed?

**Comment by fabiocos** [comment]
hold

pendign a clarification

**Pull request closed without merging**
