### PR TITLE
Replaced DQM histogram booking macro to regular methods inside IBooker

### PR DESCRIPTION
**Pull request by andrius-k**
#### PR description:

Changed a macro that would generate histogram booking calls to regular methods inside `IBooker`.

Previous implementation was using a macro to generate a facade monitor element booking methods for DQMStore. Such approach saves some lines of code but code navigation becomes impossible and readability decreases. 

Due to the fact that argument forwarding (`std::forward<Args>(args)...`) somehow caries out the type information of literal value arguments, different overloads are chosen after the update. Such cases were identified and fixed in this PR.

The problematic methods are [these two](https://github.com/cms-sw/cmssw/blob/cca5eecc3fa46fcae943c7dad1a2c37668261579/DQMServices/Core/interface/DQMStore.h#L212-L220). When `0` literal value is passed to the fourth argument, the pointer overload is (incorrectly) selected because of two reasons:

- `0` is a valid null pointer literal value, and
- it takes an implicit conversion (from int to double) for a double overload to be called

Previously the double version of the overload would be selected and the new behaviour is incorrect. 

The fix is simple: finding all the cases where one of these two overloads are called and replacing zero literal values (i.e. `0`) with double literal values (i.e. `0.0` or '0.').

#### PR validation:

The calls mentioned above were found by temporarily changing the type of first overload from `double` to `int` and compiling with `-k` (keep going in case of errors) option. This resulted in an ambiguity (compiler error with a corresponding message) because `0` literal value could be used for both methods without any implicit conversions.

### CODE REVIEW

**Comment by andrius-k** [comment]
Closing because work is still on progress.

**Comment by andrius-k** [comment]
please test

**Comment by andrius-k** [comment]
hold

Can't update when PR is closed, therefore putting it on hold.

**Comment by andrius-k** [comment]
please test

**Comment by andrius-k** [comment]
please test

**Comment by andrius-k** [comment]
please test

**Comment by andrius-k** [comment]
This PR is planned to be merged to CMSSW 11. Until then it will remain on hold.

**Comment by schneiml** [comment]
unhold

**Comment by schneiml** [comment]
please test

**Comment by andrius-k** [comment]
unhold

**Comment by andrius-k** [comment]
+1

**Comment by schneiml** [comment]
@fabiocos can we get this merged, and also the code-format PR for `DQMServices/Core` (or all of `DQMServices`) as soon as possible?

My work depends on this PR and touches many files in `DQMServices/Core`, I don't want to spent more time constantly rebasing than actually working. So I'd like to get all pending changes for DQM core in in the next days.

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
+1

**Pull request merged**
