### PR TITLE
Adding a mode of operations in which all time slices are combined

### PR DESCRIPTION
**Pull request by igv4321**
Introducing Phase 1 HF reco mode in which all time slices are combined. This is equivalent to what we did in Run 2 for cosmic runs. The timing information will be ignored.

This change is not supposed to modify any previous relvals.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by kpedro88** [comment]
@cvuosalo, @slava77, @davidlange6 ping for pre13

**Comment by cvuosalo** [comment]
urgent

**Comment by cvuosalo** [comment]
+1

For #16097 fecc4a3e1c7b1693618af885e5ef338d84c19a37

Adding optional new 2017 HF reco mode where all times slices are combined. By default, this new mode is disabled. There should be no change in monitored quantities.

The code changes are satisfactory, and Jenkins tests against baseline CMSSW_8_1_X_2016-10-04-2300 show no significant differences, as expected.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
