### PR TITLE
[DD4hep] Increase tiny rotation by 1% so it will be recognized by ROOT

### PR DESCRIPTION
**Pull request by cvuosalo**
In the ECal endcap, the physical volumes `eregalgo:EFRY_100`, `eregalgo:EFRY_200`, and `eregalgo:EFRY_300` are intended to be placed in mother volumes `eregalgo:EESCAlv1`, `eregalgo:EESCAlv2`, and `eregalgo:EESCAlv3`, respectively, with rotations of x = -7.045281e-07 radians and y = 7.045385e-07 radians. The rotation is named `eealgo:EECrRoC1R1`. However, this rotation is too small, and an internal ROOT check in the method `TGeoRotation::CheckMatrix()` causes this rotation to be ignored. For as long as we've used DD4hep, these three physical volumes have been placed with no rotation. This placement occurs in the algorithm and affects both DD4hep from XML and DD4hep from the DB. We haven't noticed the lack of rotation since our tests are not sensitive enough to catch a missing 1e-6 radian rotation.  DDD does not use ROOT to place volumes, so it placed the volumes correctly.

This PR enables this rotation by increasing it by 1%. That amount is all that is needed to allow the rotation to be recognized by ROOT as valid. Increasing a 7e-7 radian rotation by 1% is not expected to have any noticeable effect on the geometry.

A scan of all the rotations used in the geometry shows this rotation is the only one that is so small as to be ignored by ROOT.

#### PR validation:

With the PR, the rotation is recognized by ROOT and the volumes are placed with the slightly increased rotation.

The changes in this PR will be backported to 12_0.

### CODE REVIEW

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by civanch** [comment]
+1

regression is broken in 11634.911, which is expected.
Carl, please, make backport to 12_0

**Comment by civanch** [comment]
urgent

**Comment by perrotta** [comment]
@cvuosalo the net effect of this PR is to add a 7e-7 rad rotation to the ECAL endcap DD4Hep geometry, with respect to the previous situation where such a rotation was practically not there (because of root).
- Is there any visible sizeable effect we can see in the output (e.g. of  wf 11634.911) because of it?
- Can this improve somehow any value in the comparision between DDD and DD4Hep results?
- Changes in Strips (for example) as the ones below shouldn't be originated by this additional tiny rotation in the ECAL endcap, correct? Are they do to some different MC seed, that changed because of some different flow in the code after that rotation?
image

**Comment by cvuosalo** [comment]
@perrotta This PR enables the slight rotation of three sensitive ECal volumes. It is not a significant change, but it is enough to prevent regression since there is a numerical change in volume positions. Once the random seeds change, the results show the full range of statistical fluctuations. The EFRY volume affected by this rotation is an ECal endcap crystal roughly 11 cm x 1 cm x 1 cm in size. By my quick figuring, a 1e-6 radian rotation would shift it roughly by 0.1 micron. I don't think such a tiny shift could be detected in any physics results. In debug print-outs, I have checked that these volumes are actually rotated the correct amounts with this PR, and that is probably the only way to verify the rotation is occurring.

**Comment by perrotta** [comment]
+1
- Effect of the tiny rotation (mostly fluctuations due to different MC seed ending up in the same events) are as expected in the dedicated DD4Hep workflow
- It was [checked](https://github.com/cms-sw/cmssw/pull/35414#issuecomment-927152858) using debug printouts that  these volumes are actually rotated by the correct amounts

**Comment by civanch** [comment]
@perrotta , any tiny change in geometry changes simulation history for all sub-detectors. 
At the recent Simulation meeting (https://indico.cern.ch/event/1079127/ ) it was shown that current DDD (tiny matrices applied) is in a good agreement with DD4Hep (tiny matrices are vanished). The results of material budget tests and overlap tests show very good agreement.

The reasons why we indeed want to have the this tine rotations in this PR:
   - to be fully compatible DDD/DD4Hep
   - this tiny rotation was introduced for purpose
We cannot know why these rotations where added many years ago. One possible idea - an ideal geometry may provide situation when high energy gamma pass between crystals.

**Comment by perrotta** [comment]
Thank you @cvuosalo and @civanch for the explanations

**Pull request merged**
