### PR TITLE
Disabling l1tRate_Offline and l1tGt from Offline DQM

### PR DESCRIPTION
**Pull request by jfernan2**
As agreed on
https://github.com/cms-sw/cmssw/issues/25090#issuecomment-789016559

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by srimanob** [comment]
@cms-sw/l1-l2 
We understand that this offline step is not needed at the moment, so we disable it for now until it is fixed. This will allow us to test RECO+Validation+DQM in offline sequence for concurrent lumi.

@qliphy @silviodonato 
Please consider to include this PR into _pre4. Sorry for the -1 minute request. Thanks.

**Comment by qliphy** [comment]
urgent

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
FYI @benkrikler

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+1
Consequent L1T plots removed.
Anomaly changes in wf 11634.911 due to different random seed

**Comment by rekovic** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
