### PR TITLE
Add another PbPb central skim for the muon POG (103X)

### PR DESCRIPTION
**Pull request by mandrenguyen**
Backport of #25172 

@rvenditti

### CODE REVIEW

**Comment by prebello** [comment]
please test workflow 140.56,140.57 with #25210

**Comment by fabiocos** [comment]
please test workflow 140.56,140.57

**Comment by fabiocos** [comment]
@prebello @zhenhu after last fixes do you have any objection to merge this PR? I think it is needed for operations

**Comment by prebello** [comment]
+1

no objection @fabiocos

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Comment by kpedro88** [comment]
+upgrade

**Pull request merged**
