### PR TITLE
fix QIE10 shape: bins start at -0.5

### PR DESCRIPTION
**Pull request by kpedro88**
@dnoonan08 found that the QIE10 shape in CMSSW was not consistent with the calibration procedure that will be used for the QIE10. Starting the bins at -0.5 instead of -1 produces a consistent conversion between fC and ADC. This PR was backported from 81X.

### CODE REVIEW

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by kpedro88** [comment]
@mmusich can you also sign this one?

**Comment by mmusich** [comment]
+1

**Comment by kpedro88** [comment]
@davidlange6 - can you merge this one too?

**Comment by davidlange6** [comment]
we'll see that this all works in 81x (yes, it should be no problem..)

**Pull request merged**
