### PR TITLE
MiniAOD: PackedCandidate::setP4 preserve track kinematic

### PR DESCRIPTION
**Pull request by arizzi**
update the delta pt,eta,phi when calling setP4 and setPz so that track momentum is unchanged as discussed in XPOG meeting on sept 4th.

Seems to do the right thing (similar unit test added)
root [0] pat::PackedCandidate a;
root [1] a.eta()
(double) 0.000000
root [2] a.etaAtVtx()
(float) 0.00000f
root [3] a.pt()
(double) 0.000000
root [7] a.ptTrk()
(double) 0.000000
root [8] a.setP4(reco::Candidate::PolarLorentzVector(10,2,3,5))
root [9] a.ptTrk()
(double) 0.000000
root [10] a.pt()
(double) 10.000000
root [11] a.eta()
(double) 1.999939
root [12] a.etaAtVtx()
(float) -0.00006f
root [13] a.setPz(10)
root [14] a.eta()
(double) 0.881314
root [15] a.etaAtVtx()
(float) -0.00003f

### CODE REVIEW

**Comment by arizzi** [comment]
@gpetruc

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
@arizzi : is there any sample in which one can see the effect of this fix? Does it also apply to standard workflows or just to some analysis code?

**Comment by arizzi** [comment]
only analysis code, no effect expected but the just added unit test would
fail without the fix

**Comment by perrotta** [comment]
+1
- As pointed out by the non-failure of the unit tests, this fix allows returning the expected track parameters even if puppi (or anyone else) modifies the candidate ones
- Only analysis code: no difference expected in jenkins tests, none expected

**Comment by davidlange6** [comment]
merge

**Pull request merged**
