### PR TITLE
DQM online config

### PR DESCRIPTION
**Pull request by jingyucms**

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
@jingyucms could you please change the title of this PR and add a description for it?
thanks,
F.

**Comment by deguio** [comment]
@jingyucms something to be fixed here.

**Comment by deguio** [comment]
-1
as discussed this one is not yet ready to be merged. it should be runnable in the online, but it doesn't support the offline.

**Comment by vanbesien** [comment]
We replace this PR by #11296.
This PR in its current form seems to reveal some bugs that have been there for a while.
Namely, it creates 3 empty histograms in the root folder of the histogram hierarchy, which looks quite strange in the GUI and are very visible.
This is caused by booking histograms before setting the folder.
The primary case was [L1TGT.cc#L42](https://github.com/cms-sw/cmssw/blob/CMSSW_7_4_X/DQM/L1TMonitor/src/L1TGT.cc#L42)
But we found out that many of the modules contain monitor elements:
* runId_
* eventId_
* runStartTimeStamp_
* lumisecId_

that are
* either booked before folder was chosen
* or otherwise booked correctly, but never filled
* or just variables declared, but never used

We cleaned this up and added a commit for this in #11296.

**Pull request closed without merging**
