### PR TITLE
More general form of valid hit in pixel function (81X)

### PR DESCRIPTION
**Pull request by dildick**
Functions that check if there are valid hits in the second and third pixel (barrel/endcap) layer.

In response to https://github.com/cms-sw/cmssw/pull/13744#issuecomment-208675696

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by dildick** [comment]
The unit test error was also seen here  
https://github.com/cms-sw/cmssw/pull/13744#issuecomment-202683777. It is not related to this PR.

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/14027	db43178
- the same code as earlier signed in 80X
https://github.com/cms-sw/cmssw/pull/13744#issuecomment-203062675
- jenkins tests pass (the unit test failing in IB is ignored) and comparisons show no differences

**Comment by deguio** [comment]
+1

**Pull request merged**
