### PR TITLE
DD4Hep: Tracker DDPixPhase1FwdDiskAlgo Migration

### PR DESCRIPTION
**Pull request by vargasa**
##### PR validation:

```
cmsRun DetectorDescription/DDCMS/test/python/testDDPixPhase1FwdDiskAlgorithm.py
```
FYI: @ianna

### CODE REVIEW

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by ianna** [comment]
+1

**Comment by ianna** [comment]
@fabiocos - please, review

**Comment by ianna** [comment]
urgent

**Comment by kpedro88** [comment]
+1

**Pull request merged**
