### PR TITLE
Add noise plot and change thresholds [12_4_X]

### PR DESCRIPTION
**Pull request by abhih1**
#### PR description:

In response to the Run 3 collision conditions, this PR makes some adjustments in the Ecal DQM:
1. Adds a plot to see the 2D distribution of the mean of presample noise.
2. Increases x range and nbins of the 1D distribution of the noise mean.
3. Adjusts the energy threshold for the timing plot in the forward region of Ecal endcaps.

#### PR validation:

This was validated by running the online DQM workflow and testing the plots on a test DQM GUI. 

This is a backport. Master PR: https://github.com/cms-sw/cmssw/pull/38703

### CODE REVIEW

**Comment by emanueleusai** [comment]
please test

**Comment by emanueleusai** [comment]
testing at p5

**Comment by emanueleusai** [comment]
+1

**Comment by perrotta** [comment]
backport of https://github.com/cms-sw/cmssw/pull/38703

**Comment by qliphy** [comment]
+1

**Pull request merged**
