### PR TITLE
Phase2-hgx153C Modify some of the test scripts in Validation/HGCalValidation for each of calorimeter scenarios

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Modify some of the test scripts in Validation/HGCalValidation for each of calorimeter scenarios

#### PR validation:

Use the runTheMatrix test workflows

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by tjavaid** [comment]
+1

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
