### PR TITLE
L1TEMUDev_DQM_test_config

### PR DESCRIPTION
**Pull request by akhter-towsifa**
#### PR description: 

This is a test configuration file to create plots similar to the ones in [url](https://indico.cern.ch/event/1015460/contributions/4272289/attachments/2206731/3733812/Akhter_03112021_GEM_CSC_DQM_GUI_lxplus711.pdf)
This code can be checked on DQMOffline code to see if Data vs emulator (comparison) plots can be created.

#### PR validation: 

Tested this code on an lxplus machine using MWGR#2 (2021) data.

### CODE REVIEW

**Comment by silviodonato** [comment]
@akhter-towsifa please fill out the pull request title and description

**Comment by jfernan2** [comment]
@akhter-towsifa 
Please change the name of the PR to something meaningful including subsystem (e.g. [L1T] blah blah) and add a description and a validation.
Finally, add yourself along with your github username in the corresponding e-group in:
https://twiki.cern.ch/twiki/bin/viewauth/CMS/DQMContacts#L1T

Thanks

**Comment by dildick** [comment]
This is a duplicate of https://github.com/cms-sw/cmssw/pull/33085, which is already being reviewed. Let me know where the configuration can be found; I'll append it to https://github.com/cms-sw/cmssw/pull/33085

**Comment by akhter-towsifa** [comment]
> This is a duplicate of #33085, which is already being reviewed. Let me know where the configuration can be found; I'll append it to #33085

https://github.com/cms-sw/cmssw/pull/33085/commits/21d44b1434d01502d873f12e9cf7325770ca8bfb

**Comment by silviodonato** [comment]
@dildick @akhter-towsifa  if you have included this PR in https://github.com/cms-sw/cmssw/pull/33085, I think we can close this PR

**Comment by dildick** [comment]
@silviodonato Let's close this one. 

I did not include the test config yet. I had a look at existing test configurations in https://github.com/cms-sw/cmssw/tree/master/DQM/L1TMonitor/test. There are already two, both seem very outdated. I was considering merging the existing two and Towsifa's into a single one, for Run-3.

**Comment by dildick** [comment]
For testing L1TEMU DQM, please use `DQM/Integration/python/clients/l1tstage2emulator_dqm_sourceclient-live_cfg.py`

**Pull request closed without merging**
