### PR TITLE
reverting back to run3_data_relval for making rereco GT default in relval [13_1_X]

### PR DESCRIPTION
**Pull request by sunilUIET**
#### PR description:

This PR is to make rereco GT (run3_data_relval) a default for the data WFs. This is a partial reverting back of PR https://github.com/cms-sw/cmssw/pull/40692

#### PR validation:

Locally validated with WF 140.064

@tvami @bbilin @kskovpen

### CODE REVIEW

**Comment by tvami** [comment]
@cmsbuild , please test workflow 140.064

**Comment by sunilUIET** [comment]
+pdmv

**Comment by srimanob** [comment]
+Upgrade

@sunilUIET Could you please make more clear PR description, or mention if this PR agrees with Alca (or any parties) from which meeting? Thanks.

**Comment by perrotta** [comment]
+1

**Pull request merged**
