### PR TITLE
possibility of configuring the OMTF emulator directly from XMLs (14_0_X)

### PR DESCRIPTION
**Pull request by kbunkow**
#### PR description:

This PR adds the possibility of configuring the OMTF emulator directly from the config XML, without using the L1TMuonOverlapPhase1ParamsESProducer.

#### PR validation:

The PR was validated by running the L1T DQM on one file from run 385422. 

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

This PR is a backport of https://github.com/cms-sw/cmssw/pull/45032 
Only the files from the L1TMuonOverlapPhase1 folder are backported, as L1TMuonOverlapPhase2 is not included in the CMSSW_14_0_X.
This PR will be followed by the backport of https://github.com/cms-sw/cmssw/pull/45984

This PR and the backport of https://github.com/cms-sw/cmssw/pull/45984 will ensure that the OMTF emulator will be configured from the XML files corresponding to the 2024 OMTF algorithm version that was deployed at CSM on 19th March 2024, provided the Era Run3_2024 is defined for the job.
This will fix the data-emulator mismatches present in the DQM since the beginning of the 2024 pp run. Besides, will ensure the upcoming 2024 MC production will use the 2024 OMTF algorithm version.

#### Details of changes:

OMTFReconstruction.h and OMTFReconstruction.cc
The possibility of configuring the OMTF emulator directly from the config XML is added. When both patternsXMLFile and configXMLFile are given from the python config of the simOmtfDigis or simOmtfPhase2Digis, the L1TMuonOverlapParams are read directly from these files, and the L1TMuonOverlapPhase1ParamsESProducer is not needed. Otherwise, the L1TMuonOverlapParams are obtained from the eventSetup (so from the DB, or from the L1TMuonOverlapPhase1ParamsESProducer - if it is defined).

L1Trigger/L1TMuonOverlapPhase1/src/Omtf/OMTFProcessor.cc line
trackAddr[3] = myCand->getGpResultUnconstr().getPdfSumUnconstr(); is removed, as uGMT expects 3 entries in the TrackAddress (when there were 4, uGMT was generating a warning).

### CODE REVIEW

**Comment by kbunkow** [comment]
@aloeliger: maybe I should add the backport of https://github.com/cms-sw/cmssw/pull/45984 to this PR? https://github.com/cms-sw/cmssw/pull/45984 changes only one file [L1Trigger/L1TMuonOverlapPhase1/python/simOmtfDigis_cfi.py](https://github.com/cms-sw/cmssw/pull/45984/files#diff-7c6ae00b8cd7a50b627af4cea8c127af6633f189b4067b405a2066f4d2970a96)

**Comment by kbunkow** [comment]
@aloeliger: maybe I should add the backport of https://github.com/cms-sw/cmssw/pull/45984 to this PR? The PR https://github.com/cms-sw/cmssw/pull/45984 changes only one file [L1Trigger/L1TMuonOverlapPhase1/python/simOmtfDigis_cfi.py](https://github.com/cms-sw/cmssw/pull/45984/files#diff-7c6ae00b8cd7a50b627af4cea8c127af6633f189b4067b405a2066f4d2970a96)

**Comment by aloeliger** [comment]
@kbunkow I would keep them separate.

**Comment by aloeliger** [comment]
please test

**Comment by aloeliger** [comment]
Weird error attempting to merge in the PR:

```
++ git ls-remote -t git@github.com:cms-sw/cmssw.git 'refs/pull/45988/head^{}'
++ cut -c -40
kex_exchange_identification: Connection closed by remote host
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
+ COMMIT=
+ '[' -z '' ']'
+ COMMIT=refs/pull/45988/head
+ git fetch -n git@github.com:cms-sw/cmssw.git +refs/pull/45988/head:cms-sw/refs/pull/45988/head
kex_exchange_identification: Connection closed by remote host
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by aloeliger** [comment]
Hopefully it's temporary?

**Comment by aloeliger** [comment]
please test

**Comment by vlimant** [comment]
urgent

**Comment by mmusich** [comment]
backport of https://github.com/cms-sw/cmssw/pull/45032

**Comment by aloeliger** [comment]
+l1
- @kbunkow have you already made a backport of https://github.com/cms-sw/cmssw/pull/45984? If not, please do so

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
