### PR TITLE
[GEM] bugfix - BC and OrbitCounter in AMC13 - backport

### PR DESCRIPTION
**Pull request by jshlee**
backport of https://github.com/cms-sw/cmssw/pull/37340

### CODE REVIEW

**Comment by jshlee** [comment]
please test

**Comment by srimanob** [comment]
+Upgrade

Backport.

**Comment by civanch** [comment]
+1

**Comment by perrotta** [comment]
+1
- Verbatim backport of https://github.com/cms-sw/cmssw/pull/37340

**Pull request merged**
