### PR TITLE
Backport of the HCAL negative energy filter code

### PR DESCRIPTION
**Pull request by igv4321**
Backporting PR #8447, #8923, and #9105

The implementation of the negative energy filter was confirmed to be correct by the HCAL Noise WG using a configuration from a private database.

The filter is still not enabled, pending the GT (requested).

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/9137	bee9abc
- confirmed manually that this PR /commit merged on top of 75X returns no difference in the code
- jenkins tests complete OK and comparisons with baseline show no difference as expected (new functionality is disabled until there is an update in GT)

**Comment by mmusich** [comment]
@slava77 @igv4321 we acknowledge the request as reported in the [AlCa HN](https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/1719.html). Is this needed for HLT too?

**Comment by igv4321** [comment]
Definitely not in the HLT for the 50 ns run. I guess, the 25 ns situation can still be discussed.

**Comment by mmusich** [comment]
+1 
backports of PR #8447, #8923, and #9105

**Comment by ggovi** [comment]
+1

**Comment by igv4321** [comment]
Please merge this

**Comment by davidlange6** [comment]
+1

**Pull request merged**
