### PR TITLE
Validation/RecoEGamma  Removing Histos  V1

### PR DESCRIPTION
**Pull request by archiron**
#### PR description:
This PR follows one of the previous (3856, 394049) where we had added a few histos, promising that we would remove other one later. In the PR 38569 we remove some unusued histos and in this one we are removing some new ones :
- h_mc_Eta_matched
- h_ele_PoPtrueVsEta_pfx
- h_ele_EoPVsEta_pfx
- h_ele_foundHitsVsEta_pfx
- h_ele_absetaEff
- h_ele_etaEff
Those histos are redundant in PHASE2 and we kept the "Extended" ones into RECO validation which have a longer range (-3<|eta|<3 instead of 2.5<|eta|<2.5).

#### PR validation:
scram build code-checks → OK
scram build code-format → OK

compilation is OK, basics tests (scram b runtests or local tests) are OK too.
runTheMatrix.py -l limited -i all --ibeos tests are fine (50 49 48 35 18 4 1 1 1 1 1 tests passed, 0 0 0 0 0 0 0 0 0 0 0 failed).
here is the run-log : [runall-report-step123-.log](https://github.com/cms-sw/cmssw/files/9654051/runall-report-step123-.log)

This PR must be added after the last one i.e. : 39404
@beaudett @swagata87 

[runall-report-step123-.log](https://github.com/cms-sw/cmssw/files/9654051/runall-report-step123-.log)

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by swagata87** [comment]
type egamma

**Comment by emanueleusai** [comment]
+1

**Comment by perrotta** [comment]
@archiron this PR apparently also adds quite several new hostos, not only removies some old one, see for example [these lines](https://github.com/cms-sw/cmssw/pull/39504/files#diff-678eba654ae5e2c94ccd5cba31811bd4536c8bc8924cda7404d8a179c3be7256R565-R572)

However I realized that those histos were already added with #39404, and they only appear in the file differences here because this PR was not correctly rebased on top of an IB which already contains #39404.

In this case it is simple, and what was imported from some other already merged commit is clear: this PR can be merged as such, then.

In the future, in order to facilitate the review of the PR please rebase what you submit on top of all already merged changes to the same files, so that in the file differences only what actually implemented with the PR gets displayed.

**Comment by perrotta** [comment]
+1

**Pull request merged**
