### PR TITLE
L1Trigger DQM combo PR for 81X

### PR DESCRIPTION
**Pull request by nsmith-**
81X version of #13763

### CODE REVIEW

**Comment by nsmith-** [comment]
Merge conflicts caused by #13691
Will forward-merge that PR into this, resolve them

**Comment by deguio** [comment]
+1
for DQM. inspected and tested in online. at the moment it doesn't affect offline WFs

**Comment by rekovic** [comment]
Checked that the emulation L1T is not affected by the PR.  That is fine.
However, this PR has merge conflicts with #13768.
L1T will have to resolve conflicts and make a new PR once #13768 is finalised.

**Comment by davidlange6** [comment]
@rekovic -as you suggested this PR does not merge now.

**Comment by rekovic** [comment]
@davidlange6 OK. Will solve conflicts on top of #13768 and submit a new PR.

**Comment by nsmith-** [comment]
Superceded by #13891

**Pull request closed without merging**
