### PR TITLE
Clean BuildFiles in Cond subsystems

### PR DESCRIPTION
**Pull request by guitargeek**
#### PR description:

Another quick partially automatic BuildFile cleaning PR in the style of many before (for example #29805), this time covering all Cond subsystems.

I checked that all the BuildFiles are still well formatted, to not undo any work done by the formatting PRs a few days ago.

#### PR validation:

CMSSW compiles. It was checked that all newly added dependencies are actually required by the package with `git grep`.

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by guitargeek** [comment]
It's strange that this one unit test failed, here is the error message:
```
----- Begin Fatal Exception 19-May-2020 17:23:43 CEST-----------------------
An exception of category 'ScheduleExecutionFailure' occurred while
   [0] Calling beginJob
Exception Message:
Unrunnable schedule
Module run order problem found: 
rawDataCollector consumes gmtStage2Raw, gmtStage2Raw consumes simEmtfDigis, simEmtfDigis consumes rpcRecHits, rpcRecHits consumes muonRPCDigis, muonRPCDigis consumes rawDataCollector
 Running in the threaded framework would lead to indeterminate results.
 Please change order of modules in mentioned Path(s) to avoid inconsistent module ordering.
----- End Fatal Exception -------------------------------------------------
```
At first glance I don't see how this can possible relate to cleaning up the BuildFiles....

**Comment by slava77** [comment]
@cmsbuild please test

the unit test issue was fixed in CMSSW_11_1_X_2020-05-19-1100

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/29906  aab6923 
- code changes are rather technical; in line with the PR description 
- jenkins tests pass  (previous iter passed where needed)

**Comment by jfernan2** [comment]
+1

**Comment by cvuosalo** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade

**Comment by pohsun** [comment]
+1

**Comment by santocch** [comment]
+1

**Comment by Martin-Grunewald** [comment]
+1

**Comment by silviodonato** [comment]
Do you have any comments?
db:  @ggovi
l1:  @benkrikler @rekovic
I would merge it in the next IB

**Comment by rekovic** [comment]
+1

**Comment by ggovi** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
