### PR TITLE
Change locations of DQM modules as requested in CMSLITDPG-318

### PR DESCRIPTION
**Pull request by vukasinmilosevic**
Back-port to the 10_0_X PR: https://github.com/cms-sw/cmssw/pull/21182

### CODE REVIEW

**Comment by vukasinmilosevic** [comment]
I needed to add this PR https://github.com/cms-sw/cmssw/pull/20947 before other changes were applied. The PR is merged in 10_0_x, but not in 9_2_x

**Comment by jfernan2** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by thomreis** [comment]
backport of #21182

**Comment by thomreis** [comment]
Hi @vukasinmilosevic 
Data taking with 92x has finished. This can be closed.

**Comment by davidlange6** [comment]
CMSSW_9_2_X developement work is completed. Closing remaining PRs

**Pull request closed without merging**
