### PR TITLE
Fix collapsed status in HCAL topology [100X]

### PR DESCRIPTION
**Pull request by kpedro88**
Backport of #22001

### CODE REVIEW

**Comment by kpedro88** [comment]
please test

**Comment by prebello** [comment]
+1

**Comment by prebello** [comment]
Hi @kpedro88, so 2018 MC in 10_0_0 relval campaign focused on collapsed scenario will be affected. Would you expect changes in all distributions?

**Comment by kpedro88** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Comment by prebello** [comment]
+1

**Comment by Martin-Grunewald** [comment]
+1

**Comment by jfernan2** [comment]
+1

**Comment by perrotta** [comment]
+1
- Just in case the backport to 10_0_1 is needed, this is identical to #22001

**Comment by deguio** [comment]
Hi @fabiocos 
I was hoping to have this one considered for 10_0_1
what's the plan for integrating it? it would be good to have it in the release which is going to be used for the MC prod.

@abdoulline @mariadalfonso @hatakeyamak

**Comment by fabiocos** [comment]
@deguio 10_0_1 was built to quickly start GEN-SIM, this PR is not affecting GEN-SIM as far as I can see, am I correct? For next steps we will need to collect whatever is needed, at the end of the validation

**Comment by deguio** [comment]
ok, sounds good then.  :)
thanks,
F.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
