### PR TITLE
Add Phase 2 Trackers T21 + T22 + T23 (Mechanical Update in Outer Tracker + Sensors studies in Inner Tracker)

### PR DESCRIPTION
**Pull request by ghugo83**
**PR description:**

This PR:
- Introduces a Tracker baseline, called T21. It has a Phase 2 Outer Tracker with updated TBPS (changes in Layer 1 to facilitate IT insertion) and TEDD (update sensors Z inter-spacing in all TEDD).
- Introduces T22, a Tracker based on T21, but with 50x50 um2 pixels everywhere in Inner Tracker.
- Introduces T23, a Tracker based on T21, but with 3D sensors in TBPX L1 + TBPX L2 + TFPX R1.

**T21:**
tkLayout description: http://ghugo.web.cern.ch/ghugo/layouts/T21/OT800_IT615/layoutpixel.html  
Geometry scenario: 2026D63.
Workflows: 294xx (no PU), 296xx (PU).

**T22:**
tkLayout description: http://ghugo.web.cern.ch/ghugo/layouts/T22/OT800_IT621/layoutpixel.html 
Geometry scenario: 2026D64.
Workflows: 298xx (no PU), 300xx (PU).

**T23:**
tkLayout description: http://ghugo.web.cern.ch/ghugo/layouts/T23/OT800_IT700/layoutpixel.html
Geometry scenario: 2026D65.
Workflows: 302xx (no PU), 304xx (PU).

Following comparisons should be made:
### **Validate new Outer Tracker:** 
_Compare T21 versus T20 (_2026D63 versus 2026D56_)._
Should not expect any meaningful change in the tracking performance (maybe an extremely tiny degradation).

### **Inner Tracker sensors studies:** 
Now have a common base to compare different sensors options.
Only bricked pixels sensors option is missing (I included that geometry in another private branch).

**25x100 -> 50x50:** 
_Compare T22 (50x50, planar) versus T21 (25x100, planar) (_2026D64 versus 2026D63_)._
An interesting fast sim estimate is available at:
25x100: http://ghugo.web.cern.ch/ghugo/layouts/T21/OT800_IT615/errorstracker.html 
50x50: http://ghugo.web.cern.ch/ghugo/layouts/T22/OT800_IT621/errorstracker.html 
With obviously, especially visible here at high pT, a significant degradation of pT and transverse impact parameter resolution, and an improvement of longitudinal impact parameter resolution. Of course less visible at low pT (multiple scattering).

**planar -> 3D:** 
Compare T23 (3D) versus T21 (planar) (_2026D65 versus 2026D63_).
tkLayout track parameters code fully debugged and operational in the case of 3D sensors. 
Though, would need to fix 3D local resolution parametrization used as input in tkLayout, to get meaningful fast sim results on that front as well.

**PR validation:**
Following was done for CMSSW validation:
- Checked XMLs make sense from Tracker design point of view, in concordance with Mechanics.
- Checked overlaps with Fireworks + Geant4 tools.
- Checked workflow numbering.
- Checked that workflows with D63, D64, D65 scenarios run smoothly with no extra error / warning.

FYI: @dpiparo @VinInn @cvuosalo @civanch @ianna @emiglior @skinnari @mmusich  @jalimena @fabiocos @kpedro88

### CODE REVIEW

**Comment by kpedro88** [comment]
@ghugo83 please note, this will need to be rebased (and detector numbers incremented accordingly) after #30891 is merged

**Comment by ghugo83** [comment]
@kpedro88 Ha shall I rebase it now? I could put it on top of #30891 now

**Comment by ghugo83** [comment]
@kpedro88 Yep will wait for #30891 to be merged.

**Comment by fabiocos** [comment]
@ghugo83 do I understand correctly that this is not affecting in any way the BarrelTimingLayer envelope?

**Comment by ghugo83** [comment]
> @ghugo83 do I understand correctly that this is not affecting in any way the BarrelTimingLayer envelope?

@fabiocos Yes independent from BTL, I did not have to update the outermost OT envelopes.

**Comment by ghugo83** [comment]
Ha please wait, I am rebasing this branch but not done yet.

**Comment by ghugo83** [comment]
Reopened it at https://github.com/cms-sw/cmssw/pull/30976 .
Sorry, but for some mysterious reason, the github comparison is being made here to the 'old' master branch from yesterday.

**Comment by alja** [comment]
+1

**Comment by kpedro88** [comment]
please close

**Comment by kpedro88** [comment]
@smuzaffar @mrodozov can we prevent the bot from starting tests for closed PRs?

**Comment by smuzaffar** [comment]
sure, bot should not test closed PR. I will  fix it.

**Comment by silviodonato** [comment]
move to #31673

**Pull request closed without merging**
