### PR TITLE
Backport Trigger Primitive Upgrades in CMSW_11_2_X

### PR DESCRIPTION
**Pull request by TaeunKwon**
#### PR description:

This PR backports recent 2 upgrades on the Trigger Primitive algorithm in CMSSW_11_2_X, where 1TS Trigger Primitive scheme(PFA1') is widely used.  The two upgrades on TP are the fix on TP saturation effect(#34252) and correction on the timePhase definition in Pulse Containment Corrector(PCC)(#34572, #34805) each. The effect of changes of this PR are described in each PR and also presented in [presentation by Taeun Kwon](https://indico.cern.ch/event/1061449/contributions/4460835/attachments/2286772/3886949/Comissioning_1TS_Scheme_21Jul23.pdf) from slide 3 to 18.

#### PR validation:

A basic technical test was performed: `runTheMatrix.py -l limited -i all --ibeos`

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

This is a backport of 3 PRs, #34252, #34572, and #34805

### CODE REVIEW

**Comment by tvami** [comment]
backport of #34252

**Comment by tvami** [comment]
backport of #34572

**Comment by tvami** [comment]
backport of #34805

**Comment by tvami** [comment]
Hi @TaeunKwon can you please tidy up the commit history with a git squash? Thanks!

**Comment by tvami** [comment]
Hi @rappoccio are there plans to create Run-3 MCs with CMSW_11_2_X ?  Just to know where this backport will lead to.

**Comment by tvami** [comment]
Also cc @kmaeshima

**Comment by TaeunKwon** [comment]
> Hi @TaeunKwon can you please tidy up the commit history with a git squash? Thanks!

All commits are squashed to 2 different commits. Thanks!

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
Hi @smuzaffar there is an error msg saying "Unable to find CMSSW IB for CMSSW_11_2_X."

**Comment by smuzaffar** [comment]
yes, 11.2.X has been closed and there are no IBs for it

**Comment by tvami** [comment]
> yes, 11.2.X has been closed and there are no IBs for it

Thanks Shahzad! So then my question to @rappoccio and @kmaeshima is more urgent than I thought

**Comment by rappoccio** [comment]
We aren't planning any submissions to 11.2 any longer. Trigger studies should be done in >=12.0 from now forward.

**Comment by tvami** [comment]
Hi @TaeunKwon please close this PR and if the backport is really needed open one in a 12_0_X. Please note that 12_0_0 is closed as well, so if you for some reason need that, you need to go through PPD /  the release managers first. So before opening a backport there I'd make sure that they agree first.

**Comment by tvami** [comment]
-alca
* this release has been closed

**Comment by TaeunKwon** [comment]
> Hi @TaeunKwon please close this PR and if the backport is really needed open one in a 12_0_X. Please note that 12_0_0 is closed as well, so if you for some reason need that, you need to go through PPD / the release managers first. So before opening a backport there I'd make sure that they agree first.

Okay, thanks for the clarification! I think we don't need backporting to 12_0_X, because some changes was already merged to the release and others can be applied by adjusting parameters, but I will discuss with others and consider whether we need backporting or not.

**Pull request closed without merging**
