### PR TITLE
bug fix for HLT DQM

### PR DESCRIPTION
**Pull request by mtosi**
addressing issue reported by @silviodonato 
https://github.com/cms-sw/cmssw/pull/18879#issuecomment-307399494

### CODE REVIEW

**Comment by mtosi** [comment]
Done                          cmsRun RelVal_RECO_GRun_MC.py >& output.log

**Comment by silviodonato** [comment]
please test

**Comment by davidlange6** [comment]
please test

**Comment by mtosi** [comment]
if it is urgent, could we please start the integration test ?
thanks

**Comment by silviodonato** [comment]
+1

**Comment by davidlange6** [comment]
much better to rework the pset to avoid string parsing (which I guess is source of the issue)..

**Comment by davidlange6** [comment]
merge

**Pull request merged**
