### PR TITLE
Create PythiaCP5TuneDownSettings_cfi.py

### PR DESCRIPTION
**Pull request by efeyazgan**

### CODE REVIEW

**Comment by efeyazgan** [comment]
please test

**Comment by alberto-sanchez** [comment]
Looks like jenkins is stuck

**Comment by fabiocos** [comment]
please test

@smuzaffar is this suffering from issues for cms-bot ?

**Comment by smuzaffar** [comment]
code-checks

**Comment by smuzaffar** [comment]
@fabiocos , yes it was stuck and waiting for code checks results. I have forced restarted the code-checks and after that normal Pr tests should start

**Comment by efeyazgan** [comment]
please check

**Comment by efeyazgan** [comment]
please test

**Comment by efeyazgan** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
