### PR TITLE
[14.2.X]Class version update unit test fix

### PR DESCRIPTION
**Pull request by smuzaffar**
backport of #46870

### CODE REVIEW

**Comment by smuzaffar** [comment]
type bugfix

**Comment by smuzaffar** [comment]
urgent

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
+core

**Comment by smuzaffar** [comment]
relval failures are due to das issue and are not related to this change. This change only touches  a bash script for running class version unit test

**Comment by smuzaffar** [comment]
ignore tests-rejected with external-failure

**Comment by smuzaffar** [comment]
@cms-sw/orp-l2 , can you please review this? This should fix the build/unit test issue for 14.2.x IBs

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
