### PR TITLE
Phase2-hgx237 Validation of Cell paprameters for HGCal in DDD vs DD4Hep

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Introduce an analyzer which prints out cell parameters of high granularity calorimeter and can be used to compare geometries created by DDD and DD4Hep

#### PR validation:

Tested using the cfg files in Geometry/HGCalGeometry/test/python

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
+1

**Comment by kpedro88** [comment]
ping @cmsbuild

**Comment by silviodonato** [comment]
+1

**Pull request merged**
