### PR TITLE
PUPPI v15 bug/crash fix for NANOAOD

### PR DESCRIPTION
**Pull request by lathomas**
#### PR description:
This is a fix to https://github.com/cms-sw/cmssw/pull/31927 that introduced a crash in NANOAOD workflows. 
For the record, the crash only happens when running the NANO step alone, but is not visible when both NANO and DQM:@nanoAODDQM steps are run (hence why it wasn't spotted earlier).
In addition, it was noticed that some booleans were not properly set for MC when recreating the jet PUPPI collection. This is now corrected.

#### PR validation:
The following command ran succesfully (and is crashing before this PR): 
`cmsDriver.py  --python_filename PPD-RunIISummer20UL17NanoAODv2-00001_1_cfg.py --eventcontent NANOAODSIM --customise Configuration/DataProcessing/Utils.addMonitoring --datatier NANOAODSIM --fileout file:nanoformat10kDY.root --conditions 112X_upgrade2018_realistic_v6 --step NANO --filein "dbs:/DYJetsToLL_M-50_TuneCP5_13TeV-amcatnloFXFX-pythia8/RunIISummer20UL18MiniAOD-Pilot_106X_upgrade2018_realistic_v11_L1v1-v2/MINIAODSIM" --era Run2_2018,run2_nanoAOD_106Xv1  --mc -n 1000
`

### CODE REVIEW

**Comment by gouskos** [comment]
please test

**Comment by gouskos** [comment]
please test workflow 136.8522,1325.61,1325.81

**Comment by silviodonato** [comment]
urgent

**Comment by silviodonato** [comment]
```
Updating process to run ParticleNet before it's included in MiniAOD
Updating process to run DeepDoubleXv2 on datasets before 11X
Will recalculate the following discriminators on AK8 jets: pfParticleNetJetTags:probTbcq, pfParticleNetJetTags:probTbqq, pfParticleNetJetTags:probTbc, pfParticleNetJetTags:probTbq, pfParticleNetJetTags:probTbel, pfParticleNetJetTags:probTbmu, pfParticleNetJetTags:probTbta, pfParticleNetJetTags:probWcq, pfParticleNetJetTags:probWqq, pfParticleNetJetTags:probZbb, pfParticleNetJetTags:probZcc, pfParticleNetJetTags:probZqq, pfParticleNetJetTags:probHbb, pfParticleNetJetTags:probHcc, pfParticleNetJetTags:probHqqqq, pfParticleNetJetTags:probQCDbb, pfParticleNetJetTags:probQCDcc, pfParticleNetJetTags:probQCDb, pfParticleNetJetTags:probQCDc, pfParticleNetJetTags:probQCDothers, pfParticleNetDiscriminatorsJetTags:TvsQCD, pfParticleNetDiscriminatorsJetTags:WvsQCD, pfParticleNetDiscriminatorsJetTags:ZvsQCD, pfParticleNetDiscriminatorsJetTags:ZbbvsQCD, pfParticleNetDiscriminatorsJetTags:HbbvsQCD, pfParticleNetDiscriminatorsJetTags:HccvsQCD, pfParticleNetDiscriminatorsJetTags:H4qvsQCD, pfMassDecorrelatedParticleNetJetTags:probXbb, pfMassDecorrelatedParticleNetJetTags:probXcc, pfMassDecorrelatedParticleNetJetTags:probXqq, pfMassDecorrelatedParticleNetJetTags:probQCDbb, pfMassDecorrelatedParticleNetJetTags:probQCDcc, pfMassDecorrelatedParticleNetJetTags:probQCDb, pfMassDecorrelatedParticleNetJetTags:probQCDc, pfMassDecorrelatedParticleNetJetTags:probQCDothers, pfMassDecorrelatedParticleNetDiscriminatorsJetTags:XbbvsQCD, pfMassDecorrelatedParticleNetDiscriminatorsJetTags:XccvsQCD, pfMassDecorrelatedParticleNetDiscriminatorsJetTags:XqqvsQCD, pfMassIndependentDeepDoubleBvLV2JetTags:probHbb, pfMassIndependentDeepDoubleCvLV2JetTags:probHcc, pfMassIndependentDeepDoubleCvBV2JetTags:probHcc
add DeepMET Producers
30-Nov-2020 14:02:38 CET  Initiating request to open file root://eoscms.cern.ch//eos/cms/store/user/cmsbuild/store/relval/CMSSW_10_6_14/RelValTTbar_13/MINIAODSIM/PU25ns_106X_mc2017_realistic_v7-v1/10000/D4CC593C-E3A1-F544-9D06-95168FEF6F7C.root
%MSG-w XrdAdaptor:  file_open 30-Nov-2020 14:02:40 CET pre-events
Data is served from cern.ch instead of original site eoscms
%MSG
30-Nov-2020 14:02:41 CET  Successfully opened file root://eoscms.cern.ch//eos/cms/store/user/cmsbuild/store/relval/CMSSW_10_6_14/RelValTTbar_13/MINIAODSIM/PU25ns_106X_mc2017_realistic_v7-v1/10000/D4CC593C-E3A1-F544-9D06-95168FEF6F7C.root
2020-11-30 14:02:52.356814: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
                         : Booking "muonMVATTH" of type "BDT" from /cvmfs/cms-ib.cern.ch/nweek-02657/slc7_amd64_gcc900/cms/cmssw-patch/CMSSW_11_3_X_2020-11-29-2300/external/slc7_amd64_gcc900/data/PhysicsTools/NanoAOD/data/mu_BDTG_2017.weights.xml.
                         : Reading weight file: /cvmfs/cms-ib.cern.ch/nweek-02657/slc7_amd64_gcc900/cms/cmssw-patch/CMSSW_11_3_X_2020-11-29-2300/external/slc7_amd64_gcc900/data/PhysicsTools/NanoAOD/data/mu_BDTG_2017.weights.xml
<HEADER> DataSetInfo              : [Default] : Added class "Signal"
<HEADER> DataSetInfo              : [Default] : Added class "Background"
                         : Booked classifier "BDTG" of type: "BDT"
                         : Booking "muonMVALowPt" of type "BDT" from /cvmfs/cms-ib.cern.ch/nweek-02657/slc7_amd64_gcc900/cms/cmssw-patch/CMSSW_11_3_X_2020-11-29-2300/external/slc7_amd64_gcc900/data/PhysicsTools/NanoAOD/data/mu_BDTG_lowpt.weights.xml.
                         : Reading weight file: /cvmfs/cms-ib.cern.ch/nweek-02657/slc7_amd64_gcc900/cms/cmssw-patch/CMSSW_11_3_X_2020-11-29-2300/external/slc7_amd64_gcc900/data/PhysicsTools/NanoAOD/data/mu_BDTG_lowpt.weights.xml
<HEADER> DataSetInfo              : [Default] : Added class "Signal"
<HEADER> DataSetInfo              : [Default] : Added class "Background"
                         : Booked classifier "BDTG" of type: "BDT"
                         : Booking "electronMVATTH" of type "BDT" from /cvmfs/cms-ib.cern.ch/nweek-02657/slc7_amd64_gcc900/cms/cmssw-patch/CMSSW_11_3_X_2020-11-29-2300/external/slc7_amd64_gcc900/data/PhysicsTools/NanoAOD/data/el_BDTG_2017.weights.xml.
                         : Reading weight file: /cvmfs/cms-ib.cern.ch/nweek-02657/slc7_amd64_gcc900/cms/cmssw-patch/CMSSW_11_3_X_2020-11-29-2300/external/slc7_amd64_gcc900/data/PhysicsTools/NanoAOD/data/el_BDTG_2017.weights.xml
<HEADER> DataSetInfo              : [Default] : Added class "Signal"
<HEADER> DataSetInfo              : [Default] : Added class "Background"
                         : Booked classifier "BDTG" of type: "BDT"
%MSG-w BTagSFProducer:  BTagSFProducer:btagWeightTable@ctor  30-Nov-2020 14:03:15 CET pre-events
Skipped loading BTagCalibration for CMVA as it was marked as unavailable in the configuration file. Event weights will not be stored.

%MSG
----- Begin Fatal Exception 30-Nov-2020 14:03:22 CET-----------------------
An exception of category 'ScheduleExecutionFailure' occurred while
   [0] Calling beginJob
Exception Message:
Unrunnable schedule
Module run order problem found: 
patJetPartons after genJetTable [path nanoAOD_step], genJetTable after jetMCTable [path nanoAOD_step], jetMCTable after l1bits [path nanoAOD_step], l1bits after triggerObjectTable [path nanoAOD_step], triggerObjectTable after l1PreFiringEventWeightTable [path nanoAOD_step], l1PreFiringEventWeightTable after prefiringweight [path nanoAOD_step], prefiringweight after unpackedPatTrigger [path nanoAOD_step], unpackedPatTrigger after isoTrackTable [path nanoAOD_step], isoTrackTable after simpleCleanerTable [path nanoAOD_step], simpleCleanerTable after corrT1METJetTable [path nanoAOD_step], corrT1METJetTable after deepMetResponseTuneTable [path nanoAOD_step], deepMetResponseTuneTable after deepMetResolutionTuneTable [path nanoAOD_step], deepMetResolutionTuneTable after chsMetTable [path nanoAOD_step], chsMetTable after tkMetTable [path nanoAOD_step], tkMetTable after rawPuppiMetTable [path nanoAOD_step], rawPuppiMetTable after puppiMetTable [path nanoAOD_step], puppiMetTable after caloMetTable [path nanoAOD_step], caloMetTable after rawMetTable [path nanoAOD_step], rawMetTable after metTable [path nanoAOD_step], metTable after svCandidateTable [path nanoAOD_step], svCandidateTable after vertexTable [path nanoAOD_step], vertexTable after rhoTable [path nanoAOD_step], rhoTable after photonTable [path nanoAOD_step], photonTable after electronTable [path nanoAOD_step], electronTable after electronMVATTH [path nanoAOD_step], electronMVATTH after tauTable [path nanoAOD_step], tauTable after fsrTable [path nanoAOD_step], fsrTable after muonTable [path nanoAOD_step], muonTable after muonMVALowPt [path nanoAOD_step], muonMVALowPt after muonMVATTH [path nanoAOD_step], muonMVATTH after muonFSRassociation [path nanoAOD_step], muonFSRassociation after muonFSRphotons [path nanoAOD_step], muonFSRphotons after saTable [path nanoAOD_step], saTable after saJetTable [path nanoAOD_step], saJetTable after subJetTable [path nanoAOD_step], subJetTable after fatJetTable [path nanoAOD_step], fatJetTable after jetTable [path nanoAOD_step], jetTable after cjetNN [path nanoAOD_step], cjetNN after bjetNN [path nanoAOD_step], bjetNN after linkedObjects [path nanoAOD_step], linkedObjects after lepInJetVars [path nanoAOD_step], lepInJetVars after isFromLostTrackForIsoTk [path nanoAOD_step], isFromLostTrackForIsoTk after isoForIsoTk [path nanoAOD_step], isoForIsoTk after finalIsolatedTracks [path nanoAOD_step], finalIsolatedTracks after finalPhotons [path nanoAOD_step], finalPhotons after slimmedPhotonsWithUserData [path nanoAOD_step], slimmedPhotonsWithUserData after calibratedPatPhotonsUL17 [path nanoAOD_step], calibratedPatPhotonsUL17 after seedGainPho [path nanoAOD_step], seedGainPho after isoForPho [path nanoAOD_step], isoForPho after bitmapVIDForPhoSpring16V2p2 [path nanoAOD_step], bitmapVIDForPhoSpring16V2p2 after bitmapVIDForPho [path nanoAOD_step], bitmapVIDForPho after finalElectrons [path nanoAOD_step], finalElectrons after slimmedElectronsWithUserData [path nanoAOD_step], slimmedElectronsWithUserData after calibratedPatElectronsUL17 [path nanoAOD_step], calibratedPatElectronsUL17 after seedGainEle [path nanoAOD_step], seedGainEle after ptRatioRelForEle [path nanoAOD_step], ptRatioRelForEle after isoForEle [path nanoAOD_step], isoForEle after bitmapVIDForEleHEEP [path nanoAOD_step], bitmapVIDForEleHEEP after bitmapVIDForEle [path nanoAOD_step], bitmapVIDForEle after slimmedElectronsUpdated [path nanoAOD_step], slimmedElectronsUpdated after finalTaus [path nanoAOD_step], finalTaus after slimmedTausUpdated [path nanoAOD_step], slimmedTausUpdated after deepTau2017v2p1 [path nanoAOD_step], deepTau2017v2p1 after patTauDiscriminationAgainstElectronDeadECALForNano [path nanoAOD_step], patTauDiscriminationAgainstElectronDeadECALForNano after patTauDiscriminationByIsolationMVArun2v1DBoldDMwLT2015 [path nanoAOD_step], patTauDiscriminationByIsolationMVArun2v1DBoldDMwLT2015 after patTauDiscriminationByIsolationMVArun2v1DBoldDMwLTraw2015 [path nanoAOD_step], patTauDiscriminationByIsolationMVArun2v1DBoldDMwLTraw2015 after patTauDiscriminationByElectronRejectionMVA62018 [path nanoAOD_step], patTauDiscriminationByElectronRejectionMVA62018 after patTauDiscriminationByElectronRejectionMVA62018Raw [path nanoAOD_step], patTauDiscriminationByElectronRejectionMVA62018Raw after patTauDiscriminationByIsolationMVArun2v1DBoldDMdR0p3wLT [path nanoAOD_step], patTauDiscriminationByIsolationMVArun2v1DBoldDMdR0p3wLT after patTauDiscriminationByIsolationMVArun2v1DBoldDMdR0p3wLTraw [path nanoAOD_step], patTauDiscriminationByIsolationMVArun2v1DBoldDMdR0p3wLTraw after patTauDiscriminationByIsolationMVArun2v1DBnewDMwLT [path nanoAOD_step], patTauDiscriminationByIsolationMVArun2v1DBnewDMwLT after patTauDiscriminationByIsolationMVArun2v1DBnewDMwLTraw [path nanoAOD_step], patTauDiscriminationByIsolationMVArun2v1DBnewDMwLTraw after patTauDiscriminationByIsolationMVArun2v1DBoldDMwLT [path nanoAOD_step], patTauDiscriminationByIsolationMVArun2v1DBoldDMwLT after patTauDiscriminationByIsolationMVArun2v1DBoldDMwLTraw [path nanoAOD_step], patTauDiscriminationByIsolationMVArun2v1DBoldDMwLTraw after finalLooseMuons [path nanoAOD_step], finalLooseMuons after finalMuons [path nanoAOD_step], finalMuons after slimmedMuonsWithUserData [path nanoAOD_step], slimmedMuonsWithUserData after ptRatioRelForMu [path nanoAOD_step], ptRatioRelForMu after isoForMu [path nanoAOD_step], isoForMu after slimmedMuonsUpdated [path nanoAOD_step], slimmedMuonsUpdated after finalJetsAK8 [path nanoAOD_step], finalJetsAK8 after finalJets [path nanoAOD_step], finalJets after softActivityJets10 [path nanoAOD_step], softActivityJets10 after softActivityJets5 [path nanoAOD_step], softActivityJets5 after softActivityJets2 [path nanoAOD_step], softActivityJets2 after softActivityJets [path nanoAOD_step], softActivityJets after chsForSATkJets [path nanoAOD_step], chsForSATkJets after updatedJetsAK8WithUserData [path nanoAOD_step], updatedJetsAK8WithUserData after tightJetIdLepVetoAK8 [path nanoAOD_step], tightJetIdLepVetoAK8 after tightJetIdAK8 [path nanoAOD_step], tightJetIdAK8 after updatedJetsAK8 [path nanoAOD_step], updatedJetsAK8 after jetCorrFactorsAK8 [path nanoAOD_step], jetCorrFactorsAK8 after updatedJetsWithUserData [path nanoAOD_step], updatedJetsWithUserData after basicJetsForMetForT1METNano [path nanoAOD_step], basicJetsForMetForT1METNano after hfJetShowerShapeforNanoAOD [path nanoAOD_step], hfJetShowerShapeforNanoAOD after pileupJetId106XUL17 [path nanoAOD_step], pileupJetId106XUL17 after pileupJetId102X [path nanoAOD_step], pileupJetId102X after pileupJetId94X [path nanoAOD_step], pileupJetId94X after jercVars [path nanoAOD_step], jercVars after qgtagger [path nanoAOD_step], qgtagger after bJetVars [path nanoAOD_step], bJetVars after tightJetIdLepVeto [path nanoAOD_step], tightJetIdLepVeto after tightJetId [path nanoAOD_step], tightJetId after updatedJets [path nanoAOD_step], updatedJets after jetCorrFactorsNano [path nanoAOD_step], jetCorrFactorsNano after slimmedMETsPuppi [path nanoAOD_step], slimmedMETsPuppi after patPFMetT1SmearUnclusteredEnDownPuppi [path nanoAOD_step], patPFMetT1SmearUnclusteredEnDownPuppi after patPFMetT1SmearUnclusteredEnUpPuppi [path nanoAOD_step], patPFMetT1SmearUnclusteredEnUpPuppi after patPFMetT1SmearElectronEnUpPuppi [path nanoAOD_step], patPFMetT1SmearElectronEnUpPuppi after patPFMetT1SmearElectronEnDownPuppi [path nanoAOD_step], patPFMetT1SmearElectronEnDownPuppi after patPFMetT1SmearPhotonEnDownPuppi [path nanoAOD_step], patPFMetT1SmearPhotonEnDownPuppi after patPFMetT1SmearPhotonEnUpPuppi [path nanoAOD_step], patPFMetT1SmearPhotonEnUpPuppi after patPFMetT1SmearTauEnUpPuppi [path nanoAOD_step], patPFMetT1SmearTauEnUpPuppi after patPFMetT1SmearTauEnDownPuppi [path nanoAOD_step], patPFMetT1SmearTauEnDownPuppi after patPFMetT1SmearJetEnDownPuppi [path nanoAOD_step], patPFMetT1SmearJetEnDownPuppi after patPFMetT1SmearJetEnUpPuppi [path nanoAOD_step], patPFMetT1SmearJetEnUpPuppi after patPFMetT1SmearMuonEnDownPuppi [path nanoAOD_step], patPFMetT1SmearMuonEnDownPuppi after patPFMetT1SmearMuonEnUpPuppi [path nanoAOD_step], patPFMetT1SmearMuonEnUpPuppi after patPFMetT1SmearJetResUpPuppi [path nanoAOD_step], patPFMetT1SmearJetResUpPuppi after patPFMetT1SmearJetResDownPuppi [path nanoAOD_step], patPFMetT1SmearJetResDownPuppi after patPFMetT1UnclusteredEnDownPuppi [path nanoAOD_step], patPFMetT1UnclusteredEnDownPuppi after patPFMetT1UnclusteredEnUpPuppi [path nanoAOD_step], patPFMetT1UnclusteredEnUpPuppi after patPFMetT1ElectronEnDownPuppi [path nanoAOD_step], patPFMetT1ElectronEnDownPuppi after patPFMetT1ElectronEnUpPuppi [path nanoAOD_step], patPFMetT1ElectronEnUpPuppi after patPFMetT1PhotonEnUpPuppi [path nanoAOD_step], patPFMetT1PhotonEnUpPuppi after patPFMetT1PhotonEnDownPuppi [path nanoAOD_step], patPFMetT1PhotonEnDownPuppi after patPFMetT1TauEnUpPuppi [path nanoAOD_step], patPFMetT1TauEnUpPuppi after patPFMetT1TauEnDownPuppi [path nanoAOD_step], patPFMetT1TauEnDownPuppi after patPFMetT1JetEnDownPuppi [path nanoAOD_step], patPFMetT1JetEnDownPuppi after patPFMetT1JetEnUpPuppi [path nanoAOD_step], patPFMetT1JetEnUpPuppi after patPFMetT1MuonEnDownPuppi [path nanoAOD_step], patPFMetT1MuonEnDownPuppi after patPFMetT1MuonEnUpPuppi [path nanoAOD_step], patPFMetT1MuonEnUpPuppi after patPFMetT1JetResUpPuppi [path nanoAOD_step], patPFMetT1JetResUpPuppi after patPFMetT1JetResDownPuppi [path nanoAOD_step], patPFMetT1JetResDownPuppi after shiftedPatMETCorrSmearedJetResUpPuppi [path nanoAOD_step], shiftedPatMETCorrSmearedJetResUpPuppi after shiftedPatSmearedJetResUpPuppi [path nanoAOD_step], shiftedPatSmearedJetResUpPuppi after shiftedPatMETCorrSmearedJetResDownPuppi [path nanoAOD_step], shiftedPatMETCorrSmearedJetResDownPuppi after shiftedPatSmearedJetResDownPuppi [path nanoAOD_step], shiftedPatSmearedJetResDownPuppi after shiftedPatMETCorrUnclusteredEnUpPuppi [path nanoAOD_step], shiftedPatMETCorrUnclusteredEnUpPuppi after shiftedPatUnclusteredEnUpPuppi [path nanoAOD_step], shiftedPatUnclusteredEnUpPuppi after shiftedPatMETCorrUnclusteredEnDownPuppi [path nanoAOD_step], shiftedPatMETCorrUnclusteredEnDownPuppi after shiftedPatUnclusteredEnDownPuppi [path nanoAOD_step], shiftedPatUnclusteredEnDownPuppi after shiftedPatMETCorrElectronEnUpPuppi [path nanoAOD_step], shiftedPatMETCorrElectronEnUpPuppi after shiftedPatElectronEnUpPuppi [path nanoAOD_step], shiftedPatElectronEnUpPuppi after shiftedPatMETCorrElectronEnDownPuppi [path nanoAOD_step], shiftedPatMETCorrElectronEnDownPuppi after shiftedPatElectronEnDownPuppi [path nanoAOD_step], shiftedPatElectronEnDownPuppi after shiftedPatMETCorrPhotonEnUpPuppi [path nanoAOD_step], shiftedPatMETCorrPhotonEnUpPuppi after shiftedPatPhotonEnUpPuppi [path nanoAOD_step], shiftedPatPhotonEnUpPuppi after shiftedPatMETCorrPhotonEnDownPuppi [path nanoAOD_step], shiftedPatMETCorrPhotonEnDownPuppi after shiftedPatPhotonEnDownPuppi [path nanoAOD_step], shiftedPatPhotonEnDownPuppi after shiftedPatMETCorrTauEnUpPuppi [path nanoAOD_step], shiftedPatMETCorrTauEnUpPuppi after shiftedPatTauEnUpPuppi [path nanoAOD_step], shiftedPatTauEnUpPuppi after shiftedPatMETCorrTauEnDownPuppi [path nanoAOD_step], shiftedPatMETCorrTauEnDownPuppi after shiftedPatTauEnDownPuppi [path nanoAOD_step], shiftedPatTauEnDownPuppi after shiftedPatMETCorrJetEnUpPuppi [path nanoAOD_step], shiftedPatMETCorrJetEnUpPuppi after shiftedPatJetEnUpPuppi [path nanoAOD_step], shiftedPatJetEnUpPuppi after shiftedPatMETCorrJetEnDownPuppi [path nanoAOD_step], shiftedPatMETCorrJetEnDownPuppi after shiftedPatJetEnDownPuppi [path nanoAOD_step], shiftedPatJetEnDownPuppi after shiftedPatMETCorrMuonEnUpPuppi [path nanoAOD_step], shiftedPatMETCorrMuonEnUpPuppi after shiftedPatMuonEnUpPuppi [path nanoAOD_step], shiftedPatMuonEnUpPuppi after shiftedPatMETCorrMuonEnDownPuppi [path nanoAOD_step], shiftedPatMETCorrMuonEnDownPuppi after shiftedPatMuonEnDownPuppi [path nanoAOD_step], shiftedPatMuonEnDownPuppi after pfPhotonsPuppi [path nanoAOD_step], pfPhotonsPuppi after pfNoPileUpPuppi [path nanoAOD_step], pfNoPileUpPuppi after pfMuonsPuppi [path nanoAOD_step], pfMuonsPuppi after pfTausPuppi [path nanoAOD_step], pfTausPuppi after pfElectronsPuppi [path nanoAOD_step], pfElectronsPuppi after pfCandsForUnclusteredUncPuppi [path nanoAOD_step], pfCandsForUnclusteredUncPuppi after pfCandsNoJetsNoEleNoMuNoTauPuppi [path nanoAOD_step], pfCandsNoJetsNoEleNoMuNoTauPuppi after pfCandsNoJetsNoEleNoMuPuppi [path nanoAOD_step], pfCandsNoJetsNoEleNoMuPuppi after pfCandsNoJetsNoElePuppi [path nanoAOD_step], pfCandsNoJetsNoElePuppi after pfCandsNoJetsPuppi [path nanoAOD_step], pfCandsNoJetsPuppi after shiftedPatMETCorrJetResUpPuppi [path nanoAOD_step], shiftedPatMETCorrJetResUpPuppi after shiftedPatJetResUpPuppi [path nanoAOD_step], shiftedPatJetResUpPuppi after shiftedPatMETCorrJetResDownPuppi [path nanoAOD_step], shiftedPatMETCorrJetResDownPuppi after shiftedPatJetResDownPuppi [path nanoAOD_step], shiftedPatJetResDownPuppi after patPFMetT1SmearPuppi [path nanoAOD_step], patPFMetT1SmearPuppi after patPFMetT1T2SmearCorrPuppi [path nanoAOD_step], patPFMetT1T2SmearCorrPuppi after selectedPatJetsForMetT1T2SmearCorrPuppi [path nanoAOD_step], selectedPatJetsForMetT1T2SmearCorrPuppi after patSmearedJetsPuppi [path nanoAOD_step], patSmearedJetsPuppi after patPFMetTxyPuppi [path nanoAOD_step], patPFMetTxyPuppi after patPFMetT1TxyPuppi [path nanoAOD_step], patPFMetT1TxyPuppi after patPFMetTxyCorrPuppi [path nanoAOD_step], patPFMetTxyCorrPuppi after patPFMetT1Puppi [path nanoAOD_step], patPFMetT1Puppi after patPFMetT1T2CorrPuppi [path nanoAOD_step], patPFMetT1T2CorrPuppi after patPFMetPuppi [path nanoAOD_step], patPFMetPuppi after genMetExtractorPuppi [path nanoAOD_step], genMetExtractorPuppi after metrawCaloPuppi [path nanoAOD_step], metrawCaloPuppi after cleanedPatJetsPuppi [path nanoAOD_step], cleanedPatJetsPuppi after jetSelectorForMetPuppi [path nanoAOD_step], jetSelectorForMetPuppi after basicJetsForMetPuppi [path nanoAOD_step], basicJetsForMetPuppi consumes patJetsPuppi, patJetsPuppi consumes patJetFlavourAssociationPuppi, patJetFlavourAssociationPuppi consumes patJetPartons
 Running in the threaded framework would lead to indeterminate results.
 Please change order of modules in mentioned Path(s) to avoid inconsistent module ordering.
----- End Fatal Exception -------------------------------------------------
30-Nov-2020 14:03:22 CET  Closed file root://eoscms.cern.ch//eos/cms/store/user/cmsbuild/store/relval/CMSSW_10_6_14/RelValTTbar_13/MINIAODSIM/PU25ns_106X_mc2017_realistic_v7-v1/10000/D4CC593C-E3A1-F544-9D06-95168FEF6F7C.root
```
@lathomas

**Comment by lathomas** [comment]
Yes currently investigating... Looks like patJetPartons is set multiple times: 
here: 
https://github.com/cms-sw/cmssw/blob/master/PhysicsTools/NanoAOD/python/jets_cff.py#L609-L614
https://github.com/cms-sw/cmssw/blob/master/PhysicsTools/NanoAOD/python/jets_cff.py#L752
and via this function as well: 
https://github.com/cms-sw/cmssw/blob/master/PhysicsTools/NanoAOD/python/nano_cff.py#L233-L249

Dropping the producer in jets_cff.py fix the issue apparently...

**Comment by silviodonato** [comment]
test parameters:
- workflows = 136.8522,1325.61,1325.81

**Comment by silviodonato** [comment]
> test parameters:
> 
>     * workflows = 136.8522,1325.61,1325.81

Just to avoid forgetting to run 1325.61 and 1325.81

**Comment by mariadalfonso** [comment]
please test workflow 136.8522,1325.61,1325.81

**Comment by gouskos** [comment]
+xpog

**Comment by santocch** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
