### PR TITLE
Run3-gex94A Backport reduced tracker material xmls done in #35332 and #35384

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Backport reduced tracker material xmls done in #35332 and #35384

#### PR validation:

Tested using cfg's in Geometry/TrackerCommonData/test/python

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Backporting from #35332 and #35384

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by civanch** [comment]
urgent

**Comment by perrotta** [comment]
backport of #35332 and #35384

**Comment by perrotta** [comment]
+1
- It backports updated xml files and test scripts from #35332 and #35384
- It doesn't backport the run3 related modifications to Geometry/TrackerCommonData/python/cmsExtendedGeometry2021FlatMinus05PercentXML_cfi.py and Geometry/TrackerCommonData/python/cmsExtendedGeometry2021ZeroMaterialXML_cfi.py, which would take those updated xml files into account
- Outputs get untouched as such

**Pull request merged**
