### PR TITLE
HBHE: avoid double counting of correlated term

### PR DESCRIPTION
**Pull request by mariadalfonso**
backport of #32394 

needed in case Run3 aged samples are requested

@intrepid42 @jainshilpi

### CODE REVIEW

**Comment by silviodonato** [comment]
please test

**Comment by jpata** [comment]
Backport looks good, we see similar changes in the workflow outputs in jenkins as for #32394.

The only question that arises is if the no-change policy applies, as the default output changes, but I'm not immediately able to confirm if 11_2_X has been used for production yet. Using a quick DAS query I don't find anything:
```
dasgoclient --query="dataset release=CMSSW_11_2_*" --limit=0 | grep -v -i relval | wc -l
```

but maybe @cms-sw/pdmv-l2 can help confirm if there are considerations for changing reco output in 11_2_X right now.

**Comment by chayanit** [comment]
Hello @jpata , are you looking for RelVals produced in 11_2_X? There should be plenty of them. Which reco output are you referring to?

**Comment by jpata** [comment]
I was trying to understand if there's a problem if reco output changes now due to a bugfix in 11_2_X given the already ongoing validation campaign.

Release managers (@silviodonato @qliphy) do you see any problem with that?
@chayanit: my apologies, I meant to tag PPD, but perhaps you can help me answer the above question as well

**Comment by silviodonato** [comment]
@jpata The production of CMSSW_11_2_0 has not start yet as far as I know (part of the validation is still ongoing). So I think we can merge this bugfix

**Comment by jpata** [comment]
+reconstruction
- exact backport of #32394
- fixes a bug in HCAL reco
- no-change rule suppressed here, as production has not yet started

**Comment by silviodonato** [comment]
+1

**Pull request merged**
