### PR TITLE
Particle gain calibration (backport of #10043)

### PR DESCRIPTION
**Pull request by quertenmont**
Several bug fix and script automation,
but also some developments like:
- multi-run harvesting of PCL files
- tracker map plots
- pixel response monitoring
  Backport of #10043

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by quertenmont** [comment]
Is there a way to test the PCL workflow too ?
I think those commands should do (they were used previously by @mmusich to test #9104).
But can we run them in jenkins (or similar) ?

cmsDriver.py step1 --conditions auto:com10 -s RAW2DIGI,L1Reco,RECO,ALCAPRODUCER:@allForExpress+SiStripCalMinBias+SiStripPCLHistos,DQM,ENDJOB --process RECO --data --eventcontent ALCARECO,DQM --scenario pp --datatier ALCARECO,DQM --customise Configuration/DataProcessing/RecoTLR.customiseExpress -n 100 --dasquery="file dataset = /MinimumBias/Run2012C-v1/RAW run=200190" --fileout file:step1.root

cmsDriver.py step2 --datatier ALCARECO --conditions auto:com10 -s ALCA:PromptCalibProdSiStripGains --eventcontent ALCARECO -n 100 --filein file:step1.root

**Comment by mmusich** [comment]
@quertenmont  yes, but we need to change the relvalsteps. I have already a branch for that (https://hypernews.cern.ch/HyperNews/CMS/get/tier0-Ops/1025/1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/1.html), but I was waiting for the insertion of the Alignment PCL as well from @cerminar.

**Comment by quertenmont** [comment]
Ok.  There is no really any hurry with this PR.  So I was just curious to make sure that the PCL workflow is also going to be tested.  Since I made some changes there I prefer to make sure not to be the cause of any T0 crash ;-)
Thanks Marco!

**Comment by quertenmont** [comment]
I am done with my changes, so it would be nice to proceed with this PR

**Comment by mmusich** [comment]
please test

**Comment by quertenmont** [comment]
OK, so this one it should really be the last commit for this PR.
Could you please try to process it and integrated it ASAP.
Some important bugs have been fixed and it would be good to have these in the release for the 25ns runs to come (or not too much later... since I am aware of the tight schedule)

**Comment by mmusich** [comment]
please test

**Comment by quertenmont** [comment]
DAS issue :-/

**Comment by mmusich** [comment]
let's try again...

**Comment by mmusich** [comment]
please test

**Comment by quertenmont** [comment]
After the DAS issue (clearly unrelated to this PR), I see that the test are pending since 4days.
what's going on here?  Can we move on ?

**Comment by mmusich** [comment]
@quertenmont looks like your comment unblocked the tests :)

**Comment by quertenmont** [comment]
not sure... it had the label "tests-rejected" which would have the opposite meaning to me ;-)

**Comment by mmusich** [comment]
@quertenmont yes because it failed the first time. If you have a better look you'll see that @cmsbuild commented 3 mintues ago: "the tests are being triggered in jenkins"....

**Comment by quertenmont** [comment]
ok, thanks!

**Comment by smuzaffar** [comment]
@quertenmont and @mmusich , looks like it is a bug in cms-bot. It should have started the tests 4 days ago. I am looking in to it.

**Comment by quertenmont** [comment]
This is the back-port of #10680 (that is now fully-signed)
Can you sign this one too, so we close this chapter?
Thanks

**Comment by mmusich** [comment]
+1 
for https://github.com/quertenmont/cmssw/commit/b8e721e556b9da39a8a1cc8a3587e9937140bc52
backport of #10680

**Comment by mmusich** [comment]
@ggovi please sign

**Comment by ggovi** [comment]
+1

**Comment by quertenmont** [comment]
After discussion with @mmusich, we understood that one more bug fix is needed to have the proper IOV start at the PCL. These are just cff changes.

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
+1

**Comment by ggovi** [comment]
+1

**Comment by davidlange6** [comment]
@mmusich @diguida - could you add the later commits 

(I think its this:)
https://github.com/mmusich/cmssw/commit/8f0e74e04ae268806fef2d169891345fe0affec8

**Comment by mmusich** [comment]
@quertenmont would you mind cherry-picking from mmusich@8f0e74e ? We might get this in shape to test it for HI.

**Comment by quertenmont** [comment]
I just did...

**Comment by mmusich** [comment]
@quertenmont thanks!

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
step 3 of 1001.0 doesn't seem to have an error:
```
%MSG-w Alignment:   PCLTrackerAlProducer:SiPixelAliMilleAlignmentProducer@beginRun  AlignmentParameterStore() 09-Nov-2015 15:20:35 CET Run: 165121
Using approximate implementation of averaging constraints
%MSG
```

**Comment by davidlange6** [comment]
cmsbuild, please test
lets try again..

**Comment by davidlange6** [comment]
Hi - I'm cleaning up the 75x CMSSW release queue, so closing issues not directly related to analysis or finalizing the HI MC production. Please make sure these requests are included in the 80x release already. Thanks!

**Pull request closed without merging**
