### PR TITLE
Modernized L1TCaloRCTToUpgradeConverter

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

- Made into a global module
- Used EDPutToken
- Filled in fillDescriptions
- Changed to modern C++ constructs
- Consolidated into one file

#### PR validation:

Code compiles

### CODE REVIEW

**Comment by Dr15Jones** [comment]
prompted by #25090

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
ping

**Comment by silviodonato** [comment]
This is a technical PR. @benkrikler @rekovic Do you have any objections?

**Comment by silviodonato** [comment]
merge
In case you have any comments, please let me know

**Pull request merged**
