### PR TITLE
Backport features and 212 compatibility from 71X

### PR DESCRIPTION
**Pull request by mkirsano**

### CODE REVIEW

**Comment by mkirsano** [comment]
To be used with PR cmsdist #1926

**Comment by mkirsano** [comment]
I did not backport JetMatchingHooks, this requires updates in GeneratorInterface/PartonShowerVeto

**Comment by covarell** [comment]
+1

**Comment by covarell** [comment]
Automatic testing will not work, it also needs:
https://github.com/cms-sw/cmsdist/pull/1926
to be compiled

**Comment by davidlange6** [comment]
ok - seems cms-sw/cmsdist#1926 isn't ready yet - but I'll let things fail for a bit.

**Comment by covarell** [comment]
Now cms-sw/cmsdist#1926 has the evtgen build turned off

please test

**Pull request merged**
