### PR TITLE
add QIE11 support in hcal digitization

### PR DESCRIPTION
**Pull request by kpedro88**
This PR duplicates all QIE10 functionality for QIE11 (to be used with HE in 2017, and later with HB). Most of the changes are just a straight extension of the changes already made for QIE10. A few other notable changes:

1) Removed `run2_HF_2016` sub-era: `HcalDigitizer` now automatically assigns a cell to a digi collection based on `QIEType` in the database, no other need for this sub-era.

2) Cleanup: Removed some unused code in HcalDigitizer and reduced code duplication in a few classes.

3) Added `run2_HE_2017` sub-era for necessary customizations for the SiPM simulation.

4) Rearranged HcalCustoms slightly, following the idea that these customization functions will continue to be used for (temporary) development work with hardcode conditions. Now available: 
a) `customise_Hcal2016` (turns on `testHFQIE10` option)
b) `customise_Hcal2017` (turns on QIE10s throughout HF, uses QIE8/HPD for HE, but allows for extra depths if 2017dev geometry is used)
c) `customise_Hcal2017Full` (as previous, but with QIE11/SiPM conditions for HE; to use this, also enable `run2_HE_2017` sub-era)

5) Made some changes to the `HitFilter` classes so they are more uniform and more efficient:
a) Take a vector of subdet ids to handle HBHE case
b) Use `std::binary_search()` instead of `std::find()` when checking a list of DetIds

A few validations:

i) Premixing:

ii) QIE11 digis with 2017dev geometry:

Script for testing with 2017dev geometry:

```
#!/bin/bash

 cmsDriver.py SinglePiE50HCAL_pythia8_cfi  --conditions auto:phase1_2017_design -n 10 --era Run2_2017 --geometry "Configuration.Geometry.GeometryExtended2017dev_cff,Configuration.Geometry.GeometryExtended2017devReco_cff" --eventcontent FEVTDEBUG -s GEN,SIM --datatier GEN-SIM --beamspot Realistic50ns13TeVCollision --fileout file:step1.root --customise SLHCUpgradeSimulations/Configuration/HCalCustoms.customise_Hcal2017Full > step1_SinglePiE50_UP15+SinglePiE50_UP15+DIGIUP15+RECOUP15+HARVESTUP15.log  2>&1


 cmsDriver.py step2  --conditions auto:phase1_2017_design -s DIGI:pdigi_valid,L1,DIGI2RAW,HLT:@relval25ns --datatier GEN-SIM-DIGI-RAW-HLTDEBUG -n 10 --era Run2_2017 --geometry "Configuration.Geometry.GeometryExtended2017dev_cff,Configuration.Geometry.GeometryExtended2017devReco_cff" --eventcontent FEVTDEBUGHLT --filein file:step1.root  --fileout file:step2.root --customise SLHCUpgradeSimulations/Configuration/HCalCustoms.customise_Hcal2017Full > step2_SinglePiE50_UP15+SinglePiE50_UP15+DIGIUP15+RECOUP15+HARVESTUP15.log  2>&1


 cmsDriver.py step3  --runUnscheduled  --conditions auto:phase1_2017_design -s RAW2DIGI,L1Reco,RECO,EI,PAT --datatier GEN-SIM-RECO,MINIAODSIM -n 10 --era Run2_2017 --geometry "Configuration.Geometry.GeometryExtended2017dev_cff,Configuration.Geometry.GeometryExtended2017devReco_cff" --eventcontent RECOSIM,MINIAODSIM --filein file:step2.root  --fileout file:step3.root --customise SLHCUpgradeSimulations/Configuration/HCalCustoms.customise_Hcal2017Full > step3_SinglePiE50_UP15+SinglePiE50_UP15+DIGIUP15+RECOUP15+HARVESTUP15.log  2>&1
```

### CODE REVIEW

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by ianna** [comment]
+1

**Comment by mdhildreth** [comment]
+1

**Comment by kpedro88** [comment]
@mmusich @cerminar @franzoni please take a look

**Comment by mmusich** [comment]
+1

**Pull request merged**
