### PR TITLE
[14_0_X] Add context for exceptions being thrown via RootOutputFile::finishEndFile()

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

Backport of https://github.com/cms-sw/cmssw/pull/45141 . Adds context information to exception shown in https://github.com/cms-sw/cmssw/issues/45089#issue-2322763515 .

#### PR validation:

See https://github.com/cms-sw/cmssw/pull/45141

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport of https://github.com/cms-sw/cmssw/pull/45141

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
backport of https://github.com/cms-sw/cmssw/pull/45141

**Comment by Dr15Jones** [comment]
+1

**Comment by rappoccio** [comment]
+1

**Pull request merged**
