### PR TITLE
TriggerBxMonitor: migrate to Stage 2 (81x)

### PR DESCRIPTION
**Pull request by fwyzard**
TriggerBxMonitor
- migrate to Stage 2 L1 Trigger
- correct the number of bx to 3564
- add 2D plots, remove plots for unused L1 triggers
- update test

### CODE REVIEW

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
+1

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
+1

**Comment by fwyzard** [comment]
@vanbesien @dmitrijus could you sign this ?

**Comment by dmitrijus** [comment]
+1
forward port of https://github.com/cms-sw/cmssw/pull/14349

**Comment by davidlange6** [comment]
+1

**Pull request merged**
