### PR TITLE
Add 2 new GenFilters for use by HI photon team

### PR DESCRIPTION
**Pull request by harmonicoscillator**
backport of #12510 

These two gen filters for Pythia8 are meant to mimic the older ones used with Pyquen, which can be found here:
https://github.com/cms-sw/cmssw/blob/CMSSW_7_5_X/GeneratorInterface/HiGenCommon/src/EcalGenEvtSelector.cc
https://github.com/cms-sw/cmssw/blob/CMSSW_7_5_X/GeneratorInterface/HiGenCommon/src/EcalGenEvtSelectorFrag.cc

@bi-ran has done some sanity checking between the old filters and new filters which can be found here:
https://twiki.cern.ch/twiki/pub/CMS/MITHIGAnalysis2015/MCFilters.pdf

We would like to include these filters in the 75X series to be used for HI MC production.

### CODE REVIEW

**Comment by bendavid** [comment]
I don't think this is needed for 76x.

**Comment by richard-cms** [comment]
@bendavid Yeah I think as long it ends up in 80X and 75X I'm happy.

**Comment by covarell** [comment]
-1

**Comment by richard-cms** [comment]
Okay, not needed for 76X, will close.

**Pull request closed without merging**
