### PR TITLE
Fix `PostDQMOffline*` sequences in cmsDriver.py

### PR DESCRIPTION
**Pull request by elusian**
#### PR description:

When adding a DQM sequence to the command line options (e.g. `DQM:@miniAODDQM`), cmsDriver.py is supposed to add the relative `PostDQMOffline` sequence as selected in autoDQM.py. 
However, due to [this commit](https://github.com/cms-sw/cmssw/commit/fa26238b3adb5eec7c8576add915200d4169a281#diff-cdb26c43130acb8faa9c94529dd55a55671d2621695d7c5a2a47aa20a62e62dfL1979-R1979) in CMSSW_12_6_0_pre3, this does not happen anymore. 

After the commit `sequenceList` and `postSequenceList` are the same object at the same address and filling `sequenceList` inhibits the fill of `postSequenceList` (since `expandMapping` sees no "@" in the array). Since the sequences are the same, no dqmofflineOnPAT_step is produced in the output.

This PR splits the assigment into two lines, which makes `sequenceList` and `postSequenceList` distinct again.

#### PR validation:

Created a simple config file passing `DQM:@miniAODDQM` to cmsDriver.py, requested `PostDQMOffline*` sequences are back in the `process.schedule` as they were in CMSSW_12_6_0_pre2

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Not a backport

### CODE REVIEW

**Comment by mmusich** [comment]
type bug-fix

**Comment by mmusich** [comment]
@vlimant FYI

**Comment by perrotta** [comment]
code-checks

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by elusian** [comment]
It seems that all `JetAnalyzer` plugins share that plot (https://github.com/cms-sw/cmssw/blob/master/DQMOffline/JetMET/src/JetAnalyzer.cc#L1684-L1698). 
4 of those plugins are contained in the DQMOffline sequence so you see them both in reference and target, while 4 are in the PostDQMOfflineMiniAOD, which we are adding back with this PR. Twice more plugins filling the same plot leads to twice the entries.
Whether _that_ is intended I do not know, but the difference is expected in this PR.

The comparisons are not available anymore, but I would expect https://github.com/cms-sw/cmssw/pull/39337 to have shown the opposite change.

**Comment by perrotta** [comment]
Thank you @elusian 
Not crystal clear to me... Maybe @cms-sw/dqm-l2 can have a look and suggest us how to deal with it.

**Comment by perrotta** [comment]
assign dqm

**Comment by perrotta** [comment]
urgent

**Comment by mmusich** [comment]
> Not crystal clear to me... Maybe https://github.com/orgs/cms-sw/teams/dqm-l2 can have a look and suggest us how to deal with it.

In my opinion, instead of assign DQM signature here, opening a gitHub issue and assigning JME POG conveners would be more appropriate. The duplication of JME plots filling looks like a bug (or at least a funny feature), but this is only tangentially related to the issue at hand. 
This PR is necessary to restore the correct production of miniAOD monitoring histograms (e.g. without this there is no tracking packed candidate monitoring at all, see e.g. 

> DQMHistoSizes: changed ( 10024.0,... ): 24.309 KiB Tracking/PackedCandidate

at https://github.com/cms-sw/cmssw/pull/40293#issuecomment-1347818588), and it's lack is already causing delays (see e.g. https://its.cern.ch/jira/browse/PDMVRELVALS-172 )

**Comment by perrotta** [comment]
> at [#40293 (comment)](https://github.com/cms-sw/cmssw/pull/40293#issuecomment-1347818588)), and it's lack is already causing delays (see e.g. https://its.cern.ch/jira/browse/PDMVRELVALS-172 )

Ciao @mmusich 

I agree about the need of speeding up the integration of this fix. In any case, the integration in the release is quantizied by the time of the IBs: whatever is merged between now and 11pm will end up in the 2300 master IB. And when the results of that IB tests will become available, likely tomorrow morning, we can merge the backport ones, which are the ones you are mostly aiming at.

We have an orp meeting in a few hours from now. Hopefully all the stakeholders (@vlimant @cms-sw/dqm-l2 @cms-sw/jetmet-pog-l2) will be there to address the issue reported. In particular, I look forward earing something from Jean-Roch, whose original PR implemented the modification which is reverted here. If anyone of them is missing there, we will proceed without, as we always do in case of need for the PRs flagged as "urgent".

Therefore, please be reassured that asking for the opinion of the supposedy relevant experts will not delay the integration of this PR.

**Comment by emanueleusai** [comment]
Hello, yes, I'd say something fishiy is going on here, but it's a separate issue to be addressed by JME DQM developers. 
On the other hand I recognize the urgency to have this fix in asap, so I am ok merging this as it is

**Comment by emanueleusai** [comment]
+1

**Comment by perrotta** [comment]
+1
- Let merge it, and we'll see the effect on nanoAOD v10 and v11 in the master IBs
- @vlimant and @cms-sw/xpog-l2 please have a look anyhow that this is not jeopardizing the updates you made with https://github.com/cms-sw/cmssw/pull/39337

**Comment by perrotta** [comment]
merge

**Comment by vlimant** [comment]
I don't see how anything here could create any of the plot difference you've observed, or would harm nano

**Pull request merged**
