### PR TITLE
changing strips from 192 to 96

### PR DESCRIPTION
**Pull request by bapavlov**
Changing the number of iRPC strips from 192 to 96. The number 192 has been used for studies, while 96 is the number included in the TDR  (page 165 , table 5.2) :  https://cds.cern.ch/record/2283189/files/CMS-TDR-016.pdf

### CODE REVIEW

**Comment by cvuosalo** [comment]
please test

**Comment by davidlange6** [comment]
what backwards compatibility would this request break?

**Comment by bapavlov** [comment]
I do not expect backward compatibility issues. This value is for the future chmabers only. During the detailed studies done for the Upgrade TDR we have tried with different number of strips (32, 64, 96 and 192) and all the changes are transparent fro the RECO step. Hardware experts have fixed the number of strips to 96 and this is the final value in the TDR. Now some trigger studies are under way and the RPC trigger experts would like to have 96 as a default value, because the iRPCs are expected to be with 96 strips.

**Comment by cvuosalo** [comment]
@bapavlov: Are the differences in the comparison tests expected and understood?

**Comment by ianna** [comment]
@cvuosalo - FYI, CMS policy is to keep the XML files versioned. We have agreed to keep different versions of the files in the structured directories ```<file name>/<year>/<version>/<file name>.xml```
This is one of the examples, where the policy is not followed.

**Comment by bapavlov** [comment]
> @bapavlov: Are the differences in the comparison tests expected and understood?

Looking on the comparisons I do not see significant changes - for instance in samples with muons in final state, where RPCs are expected to contribute. For instance Z->mumu  https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_10_5_X_2019-01-18-1100+25701/30113/1330.0_ZMM_13+ZMM_13+DIGIUP15+RECOUP15_L1TMuDQM+HARVESTUP15_L1TMuDQM/

The changes in "DQMHistoSizes: changed ( 21234.0,... ): -270.000 KiB RPC/RPCEfficiency". It's OK that  the strip efficiency histogram are reduced in size by reducing the number of strips.

**Comment by bapavlov** [comment]
> @cvuosalo - FYI, CMS policy is to keep the XML files versioned. We have agreed to keep different versions of the files in the structured directories `<file name>/<year>/<version>/<file name>.xml`
> This is one of the examples, where the policy is not followed.

Well, I missed somehow the convention. Should I make changes ?

**Comment by cvuosalo** [comment]
@bapavlov: Yes, please follow the versioning policy, if there is no strong justification for violating it in this case.

**Comment by fabiocos** [comment]
@bapavlov any news on this PR?

**Comment by bapavlov** [comment]
I returned the original file in Geometry/RPCGeometryBuilder/data/PhaseII/RPCSpecs.xml
and created a new one, following the naming conversion:
Geometry/RPCGeometryBuilder/data/2023/v1/RPCSpecs.xml
However, checking in the repository seems that 46 files are using PhaseII/RPCSpecs.xml file.
Seems that some of the files follow some naming conversion.
Should I update also them or there is another conversion to follow ?
The files using  PhaseII/RPCSpecs.xml file are:
Configuration/Geometry/python/dict2023Geometry.py
Geometry/CMSCommonData/python/cmsExtendedGeometry2015MuonGEMDevXML_cfi.py
Geometry/CMSCommonData/python/cmsExtendedGeometry2017Plan1XML_cfi.py
Geometry/CMSCommonData/python/cmsExtendedGeometry2017Plan1ZeroMaterialXML_cfi.py
Geometry/CMSCommonData/python/cmsExtendedGeometry2017XML_cfi.py
Geometry/CMSCommonData/python/cmsExtendedGeometry2018NoSDXML_cfi.py
Geometry/CMSCommonData/python/cmsExtendedGeometry2018Plan36XML_cfi.py
Geometry/CMSCommonData/python/cmsExtendedGeometry2018XML_cfi.py
Geometry/CMSCommonData/python/cmsExtendedGeometry2018ZeroMaterialXML_cfi.py
Geometry/CMSCommonData/python/cmsExtendedGeometry2019XML_cfi.py
Geometry/CMSCommonData/python/cmsExtendedGeometry2023D17XML_cfi.py
Geometry/CMSCommonData/python/cmsExtendedGeometry2023D19XML_cfi.py
Geometry/CMSCommonData/python/cmsExtendedGeometry2023D21XML_cfi.py
Geometry/CMSCommonData/python/cmsExtendedGeometry2023D22XML_cfi.py
Geometry/CMSCommonData/python/cmsExtendedGeometry2023D23XML_cfi.py
Geometry/CMSCommonData/python/cmsExtendedGeometry2023D24XML_cfi.py
Geometry/CMSCommonData/python/cmsExtendedGeometry2023D25XML_cfi.py
Geometry/CMSCommonData/python/cmsExtendedGeometry2023D28XML_cfi.py
Geometry/CMSCommonData/python/cmsExtendedGeometry2023D29XML_cfi.py
Geometry/CMSCommonData/python/cmsExtendedGeometry2023D30XML_cfi.py
Geometry/CMSCommonData/python/cmsExtendedGeometry2023D31XML_cfi.py
Geometry/CMSCommonData/python/cmsExtendedGeometry2023D32XML_cfi.py
Geometry/CMSCommonData/python/cmsExtendedGeometry2023D33XML_cfi.py
Geometry/CMSCommonData/python/cmsExtendedGeometry2023D34XML_cfi.py
Geometry/CMSCommonData/python/cmsExtendedGeometry2023D35XML_cfi.py
Geometry/CMSCommonData/python/cmsExtendedGeometry2023D36XML_cfi.py
Geometry/CMSCommonData/python/cmsExtendedGeometry2023D37XML_cfi.py
Geometry/CMSCommonData/python/cmsExtendedGeometry2023D38XML_cfi.py
Geometry/CMSCommonData/python/cmsExtendedGeometry2023D39XML_cfi.py
Geometry/CMSCommonData/python/cmsExtendedGeometryDetailedCavern2017Plan1XML_cfi.py
Geometry/CMSCommonData/python/cmsExtendedGeometryDetailedCavern2017Plan1ZeroMaterialXML_cfi.py
Geometry/CMSCommonData/python/cmsExtendedGeometryDetailedCavern2017XML_cfi.py
Geometry/CMSCommonData/python/cmsExtendedGeometryDetailedCavern2018XML_cfi.py
Geometry/ForwardCommonData/python/testHFNoseXML_cfi.py
Geometry/ForwardCommonData/python/totemTest2015XML_cfi.py
Geometry/ForwardCommonData/python/totemTest2019XML_cfi.py
Geometry/HcalCommonData/python/testGeometry17aXML_cfi.py
Geometry/HcalCommonData/python/testGeometry17bXML_cfi.py
Geometry/HcalCommonData/python/testPhase1GeometryXML_cfi.py
Geometry/HcalCommonData/python/testPhase2GeometryFineXML_cfi.py
Geometry/HcalCommonData/python/testPhase2GeometryXML_cfi.py
Geometry/HGCalCommonData/python/testFastTimeXML_cfi.py
Geometry/HGCalCommonData/python/testHGCalXML_cfi.py
Geometry/HGCalCommonData/python/testHGCV7XML_cfi.py
Geometry/HGCalCommonData/python/testHGCV8XML_cfi.py
Geometry/MuonCommonData/python/testMFXML_cfi.py

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
assign upgrade

as we discuss of upgrade geometry

**Comment by fabiocos** [comment]
@bapavlov as a general policy we should not modify older geometry versions, but provide new scenarios where the update is applied. The file updated here has now a reasonable name. In case you might integrate the PR adding a geometry scenario where it is effectively used, if you want to practically test it in a production workflow. I let @kpedro88 comment further

**Comment by kpedro88** [comment]
To follow the policy, we should add a muon detector version M3 with this file and then make a workflow that incorporates it. Currently we have a large proliferation of Phase 2 workflows that are using M2 (with the apparently old number of strips), see https://github.com/cms-sw/cmssw/tree/master/Configuration/Geometry. I don't really think it is feasible to update all of them to new versions; some of them have been used in production. But we can build on this change for subsequent Phase 2 geometry updates.

In the list from https://github.com/cms-sw/cmssw/pull/25701#issuecomment-467468862, I'm surprised to see that Run 2 workflows are using the PhaseII RPC spec file. Is this intentional?

**Comment by bapavlov** [comment]
> To follow the policy, we should add a muon detector version M3 with this file and then make a workflow that incorporates it. Currently we have a large proliferation of Phase 2 workflows that are using M2 (with the apparently old number of strips), see https://github.com/cms-sw/cmssw/tree/master/Configuration/Geometry. I don't really think it is feasible to update all of them to new versions; some of them have been used in production. But we can build on this change for subsequent Phase 2 geometry updates.
> 

OK. It sounds good.

> In the list from [#25701 (comment)](https://github.com/cms-sw/cmssw/pull/25701#issuecomment-467468862), I'm surprised to see that Run 2 workflows are using the PhaseII RPC spec file. Is this intentional?

Well, I'm also surprised ...I just search github repository for string "PhaseII/RPCSpecs.xml" and contrary to my initial expectations a lot of files seems to use it.

**Comment by bsunanda** [comment]
@bapavlov Is this file RPCSpecs the only file which changes M2 to M3. We are in the process of making a new scenario D41. We plan to include this in that case.

**Comment by bapavlov** [comment]
> @bapavlov Is this file RPCSpecs the only file which changes M2 to M3. We are in the process of making a new scenario D41. We plan to include this in that case.

@bsunanda Yes, it's the only change.

**Comment by kpedro88** [comment]
+upgrade
@ianna @cvuosalo please sign, this will be tested in the context of the new D41 geometry and workflow currently in development

**Comment by cvuosalo** [comment]
+1

**Comment by fabiocos** [comment]
+1

this PR in itself does not change any workflow, but will be used to define a new one (D41)

**Pull request merged**
