### PR TITLE
add `commissioning_run` as `runType` and use it in SiStrip online DQM client [12.0.X]

### PR DESCRIPTION
**Pull request by mmusich**
backport of https://github.com/cms-sw/cmssw/pull/34832 and https://github.com/cms-sw/cmssw/pull/35691

#### PR description:

This PR adds a new DQM `runType` `commissioning_run` in order to define a new clause in the SiStrip online client to be used when there are no physics triggers.

#### PR validation:

At the moment none. to be further tested

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Original PR: https://github.com/cms-sw/cmssw/pull/34832, to be tested in 2021 Commissioning data-taking

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by qliphy** [comment]
please test

**Comment by jfernan2** [comment]
@qliphy we need to test this PR at P5, however for a full test, a Global Run of data taking where the DAQ shifter declares commissioning_run would be really desired, if I got it right

**Comment by francescobrivio** [comment]
@mmusich is this urgent for the beam test in October?
I believe this is currently the only missing PR in 12_0_X before building the new release (FYI @perrotta @qliphy )

**Comment by mmusich** [comment]
@francescobrivio it's not urgent for the beam test. 
It's urgent for debugging some issues in the Strip APV emulation s/w that can be done at any time when the Strip is taking data during one of this "commissioning" runs. 
At any rate the mechanism needs to be validated by requiring one of this runs at P5 and frankly I don't know where we stand with that... 
@tsusa

**Comment by francescobrivio** [comment]
> @francescobrivio it's not urgent for the beam test. It's urgent for debugging some issues in the Strip APV emulation s/w that can be done at any time when the Strip is taking data during one of this "commissioning" runs. At any rate the mechanism needs to be validated by requiring one of these runs at P5 and frankly I don't know where we stand with that... @tsusa

ok I understand! thanks for the explanation @mmusich!

**Comment by tsusa** [comment]
> > @francescobrivio it's not urgent for the beam test. It's urgent for debugging some issues in the Strip APV emulation s/w that can be done at any time when the Strip is taking data during one of this "commissioning" runs. At any rate the mechanism needs to be validated by requiring one of these runs at P5 and frankly I don't know where we stand with that... @tsusa
> 
> ok I understand! thanks for the explanation @mmusich!



> @francescobrivio it's not urgent for the beam test. It's urgent for debugging some issues in the Strip APV emulation s/w that can be done at any time when the Strip is taking data during one of this "commissioning" runs. At any rate the mechanism needs to be validated by requiring one of these runs at P5 and frankly I don't know where we stand with that... @tsusa

the validation can be done when Strip detector is switched on (planned for Wednesday/Thursday this week)

**Comment by tvami** [comment]
@tsusa how was DQM supposed to validate this, is it ok to replay a cosmics run? @cms-sw/dqm-l2

**Comment by mmusich** [comment]
@tvami the test needs a special DAQ configuration in oder to fall into the new run Type proposed here. That's why it can't be done with past data

**Comment by tvami** [comment]
ok, Tanja modified the message, earlier it said "but we need the PR merged (and 12_0_3)".

ok so we wait until Wednesday/Thursday this week, validate and then merge? Is that the plan?

**Comment by francescobrivio** [comment]
> @francescobrivio thanks, but I don't see that run in the online DQM GUI. Was the release used to collect the data at P5 patched? If not - can we have a playback?

I'm not sure if the release was patched, this is more a question for DQM I think. @cms-sw/dqm-l2 can you help?

**Comment by francescobrivio** [comment]
> Thanks @ahmad3213 your information appears to be correct, while the one reported above from @francescobrivio seems not. 

Yea you are right, I just copy/paster the Tracker elog message assuming it was correct, but I did not double checked. Sorry about that!

**Comment by mmusich** [comment]
@cmsbuild please test

**Pull request merged**
