### PR TITLE
Ecal Payload Inspector : plots display, exhaustive treatment

### PR DESCRIPTION
**Pull request by depasse**
Compared to PR #23341, several functions that were repeated are now grouped. 
Author : Houssein Sayed (Lebanese American  University)
AlcaDB meeting : https://indico.cern.ch/event/732855/

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by arunhep** [comment]
this code has been deployed already for testing in the infrastructure of cmsDbBrowser : https://cms-conddb.cern.ch/cmsDbBrowser/payload_inspector/Prod/DEMO
it will be good to have some example plots posted here to have the feeling of change.

**Comment by HousseinSayed** [comment]
A special development version that includes these classes has been added to cmsDbBrowser. It was added for testing purposes. The plots are being tested by Francesca and I, and until now the plots seems great.

**Comment by HousseinSayed** [comment]
As an example of some of the plots;
plot_ecaltimecaliberrorsplot
plot_ecalclusterenergycorrectionobjectspecificparametersplot
plot_ecaldqmchannelstatusebmap
plot_ecalpedestalssummaryplot

**Comment by civanch** [comment]
+1

**Comment by ggovi** [comment]
please test

**Comment by ggovi** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by fabiocos** [comment]
@arunhep is this PR finally ready?

**Comment by depasse** [comment]
Yes it was the last update.  Thanks.

**Comment by arunhep** [comment]
+1

**Comment by fabiocos** [comment]
+1

@depasse thanks for the code update

**Pull request merged**
