### PR TITLE
[MiniAOD] Backport of #43965 (Increase AK4 CHS pt cut and remove unsupported taggers for AK4 CHS and AK8 Puppi jets) to 14_0_X

### PR DESCRIPTION
**Pull request by nurfikri89**
Backport of #43965

Original PR description:

This PR is  the long awaited follow up of Issue #37167. The following changes to MiniAOD content are introduced:

- AK4 CHS jets (`slimmedJets`) pT threshold increase from `10 GeV` to `15 GeV`.
- Remove PileupJetID and Quark-Gluon Likelihood taggers for AK4 CHS jets.
- Remove unsupported taggers for AK4 CHS jets.
- Remove unsupported taggers for AK8 Puppi jets (`slimmedJetsAK8`).

Event size decreases by about 2.6%. The size comparison test was performed with 5000 events from a Run3Summer23 TTTo4Q AODSIM file.

List of tagger outputs stored for AK4CHS jets:

```
pfJetBProbabilityBJetTags
pfJetProbabilityBJetTags
pfTrackCountingHighEffBJetTags
pfDeepCSVJetTags:probb
pfDeepCSVJetTags:probc
pfDeepCSVJetTags:probudsg
pfDeepCSVJetTags:probbb
pfParticleNetFromMiniAODAK4CHSCentralJetTags:probb
pfParticleNetFromMiniAODAK4CHSCentralJetTags:probc
pfParticleNetFromMiniAODAK4CHSCentralJetTags:probele
pfParticleNetFromMiniAODAK4CHSCentralJetTags:probg
pfParticleNetFromMiniAODAK4CHSCentralJetTags:probmu
pfParticleNetFromMiniAODAK4CHSCentralJetTags:probtaum1h0p
pfParticleNetFromMiniAODAK4CHSCentralJetTags:probtaum1h1p
pfParticleNetFromMiniAODAK4CHSCentralJetTags:probtaum1h2p
pfParticleNetFromMiniAODAK4CHSCentralJetTags:probtaum3h0p
pfParticleNetFromMiniAODAK4CHSCentralJetTags:probtaum3h1p
pfParticleNetFromMiniAODAK4CHSCentralJetTags:probtaup1h0p
pfParticleNetFromMiniAODAK4CHSCentralJetTags:probtaup1h1p
pfParticleNetFromMiniAODAK4CHSCentralJetTags:probtaup1h2p
pfParticleNetFromMiniAODAK4CHSCentralJetTags:probtaup3h0p
pfParticleNetFromMiniAODAK4CHSCentralJetTags:probtaup3h1p
pfParticleNetFromMiniAODAK4CHSCentralJetTags:probuds
pfParticleNetFromMiniAODAK4CHSCentralJetTags:ptcorr
pfParticleNetFromMiniAODAK4CHSCentralJetTags:ptnu
pfParticleNetFromMiniAODAK4CHSCentralJetTags:ptreshigh
pfParticleNetFromMiniAODAK4CHSCentralJetTags:ptreslow
pfParticleNetFromMiniAODAK4CHSCentralDiscriminatorsJetTags:BvsAll
pfParticleNetFromMiniAODAK4CHSCentralDiscriminatorsJetTags:CvsB
pfParticleNetFromMiniAODAK4CHSCentralDiscriminatorsJetTags:CvsL
pfParticleNetFromMiniAODAK4CHSCentralDiscriminatorsJetTags:QvsG
pfParticleNetFromMiniAODAK4CHSCentralDiscriminatorsJetTags:TauVsEle
pfParticleNetFromMiniAODAK4CHSCentralDiscriminatorsJetTags:TauVsJet
pfParticleNetFromMiniAODAK4CHSCentralDiscriminatorsJetTags:TauVsMu
```

List of tagger outputs stored for AK4Puppi jets:

```
pfDeepCSVJetTags:probb
pfDeepCSVJetTags:probbb
pfDeepCSVJetTags:probc
pfDeepCSVJetTags:probudsg
pfJetBProbabilityBJetTags
pfJetProbabilityBJetTags
pfTrackCountingHighEffBJetTags
pfDeepFlavourJetTags:probb
pfDeepFlavourJetTags:probbb
pfDeepFlavourJetTags:probc
pfDeepFlavourJetTags:probg
pfDeepFlavourJetTags:problepb
pfDeepFlavourJetTags:probuds
pfParticleNetFromMiniAODAK4PuppiCentralJetTags:probb
pfParticleNetFromMiniAODAK4PuppiCentralJetTags:probc
pfParticleNetFromMiniAODAK4PuppiCentralJetTags:probele
pfParticleNetFromMiniAODAK4PuppiCentralJetTags:probg
pfParticleNetFromMiniAODAK4PuppiCentralJetTags:probmu
pfParticleNetFromMiniAODAK4PuppiCentralJetTags:probtaum1h0p
pfParticleNetFromMiniAODAK4PuppiCentralJetTags:probtaum1h1p
pfParticleNetFromMiniAODAK4PuppiCentralJetTags:probtaum1h2p
pfParticleNetFromMiniAODAK4PuppiCentralJetTags:probtaum3h0p
pfParticleNetFromMiniAODAK4PuppiCentralJetTags:probtaum3h1p
pfParticleNetFromMiniAODAK4PuppiCentralJetTags:probtaup1h0p
pfParticleNetFromMiniAODAK4PuppiCentralJetTags:probtaup1h1p
pfParticleNetFromMiniAODAK4PuppiCentralJetTags:probtaup1h2p
pfParticleNetFromMiniAODAK4PuppiCentralJetTags:probtaup3h0p
pfParticleNetFromMiniAODAK4PuppiCentralJetTags:probtaup3h1p
pfParticleNetFromMiniAODAK4PuppiCentralJetTags:probuds
pfParticleNetFromMiniAODAK4PuppiCentralJetTags:ptcorr
pfParticleNetFromMiniAODAK4PuppiCentralJetTags:ptnu
pfParticleNetFromMiniAODAK4PuppiCentralJetTags:ptreshigh
pfParticleNetFromMiniAODAK4PuppiCentralJetTags:ptreslow
pfParticleNetFromMiniAODAK4PuppiForwardJetTags:probg
pfParticleNetFromMiniAODAK4PuppiForwardJetTags:probq
pfParticleNetFromMiniAODAK4PuppiForwardJetTags:ptcorr
pfParticleNetFromMiniAODAK4PuppiForwardJetTags:ptnu
pfParticleNetFromMiniAODAK4PuppiForwardJetTags:ptreshigh
pfParticleNetFromMiniAODAK4PuppiForwardJetTags:ptreslow
pfParticleTransformerAK4JetTags:probb
pfParticleTransformerAK4JetTags:probbb
pfParticleTransformerAK4JetTags:probc
pfParticleTransformerAK4JetTags:probg
pfParticleTransformerAK4JetTags:problepb
pfParticleTransformerAK4JetTags:probuds
pfParticleNetFromMiniAODAK4PuppiCentralDiscriminatorsJetTags:BvsAll
pfParticleNetFromMiniAODAK4PuppiCentralDiscriminatorsJetTags:CvsB
pfParticleNetFromMiniAODAK4PuppiCentralDiscriminatorsJetTags:CvsL
pfParticleNetFromMiniAODAK4PuppiCentralDiscriminatorsJetTags:QvsG
pfParticleNetFromMiniAODAK4PuppiCentralDiscriminatorsJetTags:TauVsEle
pfParticleNetFromMiniAODAK4PuppiCentralDiscriminatorsJetTags:TauVsJet
pfParticleNetFromMiniAODAK4PuppiCentralDiscriminatorsJetTags:TauVsMu
pfParticleNetFromMiniAODAK4PuppiForwardDiscriminatorsJetTags:QvsG
pfParticleTransformerAK4DiscriminatorsJetTags:BvsAll
pfParticleTransformerAK4DiscriminatorsJetTags:BvsL
pfParticleTransformerAK4DiscriminatorsJetTags:CvsB
pfParticleTransformerAK4DiscriminatorsJetTags:CvsL
pfParticleTransformerAK4DiscriminatorsJetTags:QvsG
```

List of tagger outputs stored for AK8Puppi jets:

```
pfParticleNetFromMiniAODAK8JetTags:masscorr
pfParticleNetFromMiniAODAK8JetTags:probHbb
pfParticleNetFromMiniAODAK8JetTags:probHcc
pfParticleNetFromMiniAODAK8JetTags:probHgg
pfParticleNetFromMiniAODAK8JetTags:probHqq
pfParticleNetFromMiniAODAK8JetTags:probHte
pfParticleNetFromMiniAODAK8JetTags:probHtm
pfParticleNetFromMiniAODAK8JetTags:probHtt
pfParticleNetFromMiniAODAK8JetTags:probQCD0hf
pfParticleNetFromMiniAODAK8JetTags:probQCD1hf
pfParticleNetFromMiniAODAK8JetTags:probQCD2hf
pfParticleNetJetTags:probHbb
pfParticleNetJetTags:probHcc
pfParticleNetJetTags:probHqqqq
pfParticleNetJetTags:probQCDb
pfParticleNetJetTags:probQCDbb
pfParticleNetJetTags:probQCDc
pfParticleNetJetTags:probQCDcc
pfParticleNetJetTags:probQCDothers
pfParticleNetJetTags:probTbc
pfParticleNetJetTags:probTbcq
pfParticleNetJetTags:probTbel
pfParticleNetJetTags:probTbmu
pfParticleNetJetTags:probTbq
pfParticleNetJetTags:probTbqq
pfParticleNetJetTags:probTbta
pfParticleNetJetTags:probWcq
pfParticleNetJetTags:probWqq
pfParticleNetJetTags:probZbb
pfParticleNetJetTags:probZcc
pfParticleNetJetTags:probZqq
pfParticleNetDiscriminatorsJetTags:H4qvsQCD
pfParticleNetDiscriminatorsJetTags:HbbvsQCD
pfParticleNetDiscriminatorsJetTags:HccvsQCD
pfParticleNetDiscriminatorsJetTags:TvsQCD
pfParticleNetDiscriminatorsJetTags:WvsQCD
pfParticleNetDiscriminatorsJetTags:ZbbvsQCD
pfParticleNetDiscriminatorsJetTags:ZccvsQCD
pfParticleNetDiscriminatorsJetTags:ZvsQCD
pfParticleNetFromMiniAODAK8DiscriminatorsJetTags:HbbvsQCD
pfParticleNetFromMiniAODAK8DiscriminatorsJetTags:HccvsQCD
pfParticleNetFromMiniAODAK8DiscriminatorsJetTags:HggvsQCD
pfParticleNetFromMiniAODAK8DiscriminatorsJetTags:HqqvsQCD
pfParticleNetFromMiniAODAK8DiscriminatorsJetTags:HtevsQCD
pfParticleNetFromMiniAODAK8DiscriminatorsJetTags:HtmvsQCD
pfParticleNetFromMiniAODAK8DiscriminatorsJetTags:HttvsQCD
```

FYI JME L2 (@abenecke @alkaloge), BTV L2 (@SWuchterl @mondalspandan) and XPOG (@vlimant @hqucms)

#### PR validation:

passes the usual runTheMatrix test: `runTheMatrix.py -l limited -i all --ibeos`

### CODE REVIEW

**Comment by vlimant** [comment]
enable nano

**Comment by vlimant** [comment]
please test

**Comment by mandrenguyen** [comment]
type btv, jetmet

**Comment by mandrenguyen** [comment]
+1

**Comment by vlimant** [comment]
+1

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
