### PR TITLE
93x L1T uGT fix disagreement fw/emul OOT correlations algorithms

### PR DESCRIPTION
**Pull request by rekovic**
PR 93x L1T

- fix disagreement fw/emul OOT correlations algorithms (CDC algos in the L1T menu).
The fix is to have emulator correctly check BX for conditions.

Without this fix, the event are not accepted by L1T CDC algo when fw/emul disagree (large percentage).
Please merge for next data taking release if possible.

### CODE REVIEW

**Comment by rekovic** [comment]
please test

**Comment by rekovic** [comment]
+1

**Comment by rekovic** [comment]
please test

**Comment by rekovic** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
