### PR TITLE
Remove vestigial (and huge) GBRForest when running with PFEGAlgo (75X)

### PR DESCRIPTION
**Pull request by lgray**
Backport of #10315

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
@slava77 I think the cmsbuild job died here. Probably need to start a new one.

**Comment by davidlange6** [comment]
@cmsbuild, please test

**Comment by lgray** [comment]
Guess the poor robot died :(

**Comment by lgray** [comment]
beep boop?

**Comment by slava77** [comment]
b -> p

**Comment by slava77** [comment]
I restarted the build.
Hopefully it goes better this time.
Last time it got stuck on unit tests.

**Comment by slava77** [comment]
... looks like it's running the matrix now

**Comment by lgray** [comment]
yep, I'm watching it too :-)

**Comment by lgray** [comment]
I can post igprof reports here if you think it would help speed things along.

**Comment by lgray** [comment]
Oh, right there's already an igprof report in the 76X PR. :-)

**Comment by cvuosalo** [comment]
+1

For #10317 3a675d084d66cd02917a87148d330bd300ca75a6

Removing unneeded GBRForest when running with PFEGAlgo. There should be no change in monitored quantities.

The code changes are satisfactory, and Jenkins tests against baseline CMSSW_7_5_X_2015-07-24-1100 show no significant differences, as expected. Memory use reduction was verified in the 74X version of this PR, #10319, which has already been approved by RECO. The 76X version of this PR, #10315, has also been approved by RECO.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
