### PR TITLE
Adding DigiSimLinks configurations

### PR DESCRIPTION
**Pull request by ghost**
Backport of https://github.com/cms-sw/cmssw/pull/12729

Propagating to SimTracker/TrackHistory/python/TrackQuality_cff.py
the commit mdhildreth@302f97a, from the PR #10569

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by ferencek** [comment]
@davidlange6, can you merge this one as well so we don't have to carry it around in analysis-level recipes. Thanks

**Comment by davidlange6** [comment]
+1

**Pull request merged**
