### PR TITLE
Add EGM HLT tags to data GTs and introduce fixed snapshot in online GTs

### PR DESCRIPTION
**Pull request by malbouis**
#### PR description:

This PR is a follow-up of PR #37557. As agreed [here](https://github.com/cms-sw/cmssw/pull/37557#issuecomment-1104028810), the EGM supercluster regression for HLT was included also in the Run3 offline GTs (`auto:run3_data` and `auto:run3_data_relval`) and to the Prompt GT.

The tags included in the GTs are:

Label: `pfscecal_EBCorrection_online`,	Tag: `pfscecal_EBCorrection_hlt_v1`
Label: `pfscecal_EBUncertainty_online`,	Tag: `pfscecal_EBUncertainty_hlt_v1`
Label: `pfscecal_EECorrection_online`,	        Tag: `pfscecal_EECorrection_hlt_v1`
Label: `pfscecal_EEUncertainty_online`,	Tag: `pfscecal_EEUncertainty_hlt_v1`

We also take the chance to do a forward port of PR #37670 on what concerns the revival of an AlCaDB policy of not having any GT with an infinite snapshot in autoCond.py. The new GTs with fixed snapshot are: `123X_dataRun3_HLT_frozen_v2`, `123X_dataRun3_Express_frozen_v1` and `123X_dataRun3_Prompt_frozen_v1`.

The difference in GTs are shown below. We expect to see as differences only the EGM tags listed above for the offline and Prompt GTs and no differences for the HLT and Express _frozen_ GTs.

**run3_hlt**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts//123X_dataRun3_HLT_frozen_v2/123X_dataRun3_HLT_v7

**run3_data_express**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts//123X_dataRun3_Express_frozen_v1/123X_dataRun3_Express_v5

**run3_data_prompt**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts//123X_dataRun3_Prompt_frozen_v1/123X_dataRun3_Prompt_v7

**run3_data**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts//123X_dataRun3_v5/123X_dataRun3_v4

**run3_data_relval**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts//123X_dataRun3_relval_v4/123X_dataRun3_relval_v3

FYI @Martin-Grunewald , @missirol , @cms-sw/egamma-pog-l2 

#### PR validation:

nohup runTheMatrix.py -l 138.4,138.3,136.897 --ibeos -j16

#### if this PR is a backport please specify the original PR and why you need to backport that PR:
forward port of PR #37670 
there will be a backport to 123X.

### CODE REVIEW

**Comment by missirol** [comment]
@malbouis , thanks for this follow-up.

One question: would it make sense to also update `run3_hlt_relval`, so that it matches what is in `123X_dataRun3_HLT_frozen_v1` (except for the L1T menu)?

IIuc, with this PR we would have `123X_dataRun3_HLT_frozen_v1` (`run3_hlt`) and `123X_dataRun3_HLT_relval_v4` (`run3_hlt_relval`), and those have IOV differences:
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_dataRun3_HLT_frozen_v1/123X_dataRun3_HLT_relval_v4

It seems like it would make things clearer (I don't think it would make much of a difference in the actual tests).

**Comment by malbouis** [comment]
> @malbouis , thanks for this follow-up.
> 
> One question: would it make sense to also update `run3_hlt_relval`, so that it matches what is in `123X_dataRun3_HLT_frozen_v1` (except for the L1T menu)?
> 
> IIuc, with this PR we would have `123X_dataRun3_HLT_frozen_v1` (`run3_hlt`) and `123X_dataRun3_HLT_relval_v4` (`run3_hlt_relval`), and those have IOV differences: https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_dataRun3_HLT_frozen_v1/123X_dataRun3_HLT_relval_v4
> 
> It seems like it would make things clearer (I don't think it would make much of a difference in the actual tests).

@missirol , good point! I have created a new GT `123X_dataRun3_HLT_relval_v5`  and `123X_dataRun3_HLT_frozen_v2` so that the IOV differences are kept to a minimal: https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts//123X_dataRun3_HLT_frozen_v2/123X_dataRun3_HLT_relval_v5

**Comment by malbouis** [comment]
please test

**Comment by francescobrivio** [comment]
+alca

 - PR in line with description
 - tests are clean
 - @malbouis please fix the Prompt GT diff link in the PR description (it has 123X_dataRun3_Prompt_frozen_v**2** instead of 123X_dataRun3_Prompt_frozen_v**1**)

**Comment by perrotta** [comment]
+1

**Pull request merged**
