### PR TITLE
tracking and strip DQM : trigger selection via DB + stage2 L1 handling in GenericTriggerEventFlag + update the trigger bits for Tracker DQM

### PR DESCRIPTION
**Pull request by mtosi**
it was PR https://github.com/cms-sw/cmssw/pull/14659

I've just run 
runTheMatrix.py -l limited -i all
10 10 9 7 5 1 1 1 tests passed, 0 0 0 0 0 0 0 0 failed

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by slava77** [comment]
@cmsbuild please test
the last attempt failed with 
```
error: unable to write sha1 filename
```

**Comment by mmusich** [comment]
@mtosi 
   * Strip residual plots in data that went empty are now filled:
      * In #14659 used to be: 
        134 911_in14659

      * Now is: 
        134 911_in_14786
   * Strip residual plots in MC keep being empty:
     * In #14659 used to be: [link](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_8_1_X_2016-05-31-2300+14659/14257/1330.0_ZMM_13+ZMM_13+DIGIUP15+RECOUP15+HARVESTUP15/SiStrip__MechanicalView_TIB_layer_1_.png) 
       1330 0_in14786

     * Now:  [link](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_8_1_X_2016-06-06-1100+14786/14335/1330.0_ZMM_13+ZMM_13+DIGIUP15+RECOUP15+HARVESTUP15/SiStrip__MechanicalView_TIB_layer_1_HitResiduals_TIB__Layer__1.png) 
       1330 0_in14659

**Comment by mmusich** [comment]
Is:
```
#
trigger list key: 'SiStripDQM_L1'
paths: 'NOT L1Tech_BSC_halo_beam2_inner.v0', 'NOT L1Tech_BSC_halo_beam2_outer.v0', 'NOT L1Tech_BSC_halo_beam1_inner.v0', 'NOT L1Tech_BSC_halo_beam1_outer.v0',
'NOT (L1Tech_BSC_splash_beam1.v0 AND NOT L1Tech_BSC_splash_beam2.v0)', 'NOT (L1Tech_BSC_splash_beam2.v0 AND NOT L1Tech_BSC_splash_beam1.v0)'
#
trigger list key: 'SiStrip_HLT'
paths: 'HLT_ZeroBias_v', 'HLT_HIZeroBias_v'
#
trigger list key: 'SiStrip_L1'
paths: 'L1Tech_BPTX_plus_AND_minus.v0', 'L1_ZeroBias'
#
trigger list key: 'Tracking_HLT'
paths: 'HLT_ZeroBias_v*'
#
```
OK for MC selection as well?

**Comment by mtosi** [comment]
thanks @mmusich 

MC workflow (1330.0) is making use of the HLT menu HLTrigger/Configuration/python/HLT_GRun_cff.py
this menu has HLT_ZeroBias_v3 
=> it should be ok ....

in the mean time, @mmusich realized we need an additional fix
1. update run2 mc GT
2. fix Configuration/AlCa/python/autoCond.py for the auto:run1_mc_pa

fix 2. is coming by a new commit to this branch

**Comment by mmusich** [comment]
before resubmitting tests let me fix the `auto:run2mc` key

**Comment by mmusich** [comment]
The `auto:run2mc` key has been updated (in the shadow):
```
$ conddb diff 81X_mcRun2_asymptotic_v0 80X_mcRun2_asymptotic_v14
----------------------  -----------------  ------------------------------------  ------------------------------------  
AlCaRecoTriggerBitsRcd  SiStripDQMTrigger  AlCaRecoTriggerBits_TrackerDQM_v1_mc  AlCaRecoTriggerBits_SiStripDQM_v2_mc  
```

**Comment by mmusich** [comment]
please test

**Comment by slava77** [comment]
@cmsbuild please test
curiously, in CMSSW_8_1_X_2016-06-07-1100 I get 
``` 
No logical expressions found under key SiStrip_L1 in 'AlCaRecoTriggerBitsRcd'
```
only in 2017 workflows.
In the latest jenkins tests (from CMSSW_8_1_X_2016-06-06-2300) this warning shows up in run2/current workflows.

**Comment by slava77** [comment]
@mmusich 
should we expect no change of GT for 2017 for this PR purpose?

**Comment by mmusich** [comment]
@slava77, I confirm that:
```	
cmsrel CMSSW_8_1_X_2016-06-07-2300
cd CMSSW_8_1_X_2016-06-07-2300/src/
git cms-merge-topic 14786
scramv1 b -j 8
cmsenv
runTheMatrix.py -l 1330.0
less 1330.0_ZMM_13+ZMM_13+DIGIUP15+RECOUP15+HARVESTUP15/step3_ZMM_13+ZMM_13+DIGIUP15+RECOUP15+HARVESTUP15.log | grep 'No logical' | wc -l
$ 0
```

it must have been a delay in the FronTier cache (up to 6h depending on the node, when using the standard connection string `FrontierProd`).

Regarding the phase-I GTs, yes we need to include it there as well, but I didn't want to create a dependency on the changes in https://github.com/cms-sw/cmssw/pull/14748 (now merged).
I am going to provide the new GTs for phase-I right away.

**Comment by mmusich** [comment]
@mtosi:
please update the phase-I GTs as well:
```
+    'phase1_2017_design' :  '81X_upgrade2017_design_v2',
+    'phase1_2017_realistic': '81X_upgrade2017_realistic_v2',
```
thanks,
M.

**Comment by mtosi** [comment]
thanks @mmusich , I've just updated them as well
hope it is fine

**Comment by mmusich** [comment]
@mtosi, the branch has now conflicts (likely because of #14748), can you try to rebase it?

**Comment by mmusich** [comment]
now is ok!

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
talked too early...

**Comment by mtosi** [comment]
I think I did the rebase (thanks @mmusich for the help)

1. 
git rebase -i HEAD
Successfully rebased and updated refs/heads/fgit branch -u official-cmssw/CMSSW_8_1_X

Branch fixGenericTriggerEventFlag81x set up to track remote branch CMSSW_8_1_X from official-cmssw.

2.
git branch -u official-cmssw/CMSSW_8_1_X

Branch fixGenericTriggerEventFlag81x set up to track remote branch CMSSW_8_1_X from official-cmssw.

3.
git push my-cmssw HEAD:fixGenericTriggerEventFlag81x

4.
git log fixGenericTriggerEventFlag81x..CMSSW_8_1_X
is empty

but still the branch seems to be not mergable :(


I think I'll do a new PR ...... but, let me stress that (of course many errors come from my side) I feel not really comfortable in having developed code ~1 month ago and it is still not merged because of such kind of issues ...... a lot of time has been lost because of this :(

**Comment by makortel** [comment]
@mtosi I don't really follow what exactly you did (partly because of the formatting), but `git rebase -i HEAD` is a no-op by definition (it tries to do an interactive rebase of HEAD wrt. itself, which shouldn't do anything).

**Comment by mtosi** [comment]
opened PR https://github.com/cms-sw/cmssw/pull/14820
closing this one

**Pull request closed without merging**
