### PR TITLE
merging PRs 16513(rebased on 8_0_X) and 15748

### PR DESCRIPTION
**Pull request by EsmaeelEskandari**

### CODE REVIEW

**Comment by EsmaeelEskandari** [comment]
@rekovic @abrinke1 
I am trying to merge PR #15748.
Would you please take a look at this PR and  confirm its changes?
Maybe this PR accidentally reverse some emulator changes that where made by you after PR #15748.

**Comment by abrinke1** [comment]
Thanks for checking.  The one file in  L1Trigger/L1TMuonEndCap/ that is changed by PR #16591 is plugins/L1TMuonEndCapTrackProducer.cc.  In the most up-to-date L1T emulator branch, l1t-integration-CMSSW_8_0_22, the last commit to this file is "EMTF cancel tracks by LCT, as in firmware."  The same is true in CMSSW_8_0_X, so the central CMSSW code is already up-to-date.  In your commit branch, there are a large number of changes after "EMTF cancel tracks" in the commit titled "merging PRs 16513 and 15748."  These changes should not go into central CMSSW - the last commit to this file should remain "EMTF cancel tracks by LCT, as in firmware."

**Comment by thomreis** [comment]
With the emulator changes that are introduced here the code does not compile on CMSSW_8_0_23 with PRs 15388, 16537, and 16513 merged before.

I have checked out the original emulator code from official-cmssw/CMSSW_8_0_X to replace the changed one in this PR and then it compiles for me.

```
git checkout official-cmssw/CMSSW_8_0_X -- L1Trigger/L1TMuonEndCap/plugins/L1TMuonEndCapTrackProducer.cc
```

**Comment by davidlange6** [comment]
Hi @EsmaeelEskandari all

you are starting to make a big mess of the 80x release queue - please follow the usual procedure: get your code to work in your own area, make a PR for the development release, get it approved, then worry about the production release. If you need to share code between your development team, just put it into your github fork of CMSSW and then everyone else can to 

git cms-merge-topic esmaeeleskandari:<branchname>

http://cms-sw.github.io/tutorial-collaborating-with-peers.html

Thanks

**Pull request closed without merging**
