### PR TITLE
Fix HLT Phase2 timing script.

### PR DESCRIPTION
**Pull request by rovere**
#### PR description:

This should fix the script and profit of the new features added to the underlying `benchmark` script.

#### PR validation:

Successfully tested locally.

### CODE REVIEW

**Comment by rovere** [comment]
enable hlt_p2_timing

**Comment by rovere** [comment]
FYI @mmusich @VourMa

**Comment by mmusich** [comment]
type bug-fix

**Comment by mmusich** [comment]
+hlt
   * HLT P2 Timing [chart](https://cmssdt.cern.ch/circles/web/piechart.php?data_name=hlt-p2-timing&resource=time_thread&filter=CMSSW_14_2_X_2024-10-01-1100&dataset=CMSSW_14_2_X_2024-10-01-1100-cmssw46185/el8_amd64_gcc12/26/Phase2Timing_resources) is now available

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
