### PR TITLE
Phase2-hgx288 Read all parameters needed for V16 geometry of HGCal

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Read all parameters needed for V16 geometry of HGCal

#### PR validation:

Use the runTheMatrix test workflows

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please check

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cvuosalo @srimanob @qliphy @silviodonato Can you sign this quickly - hoping it goes to pre4. Like to add the new scenario with HGCal V16 by pre5.

**Comment by cvuosalo** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

**Comment by srimanob** [comment]
Urgent

**Comment by srimanob** [comment]
FYI @qliphy 
Plan to have this PR by _pre4. However, we may need to wait until the test is done. I think tomorrow is a possible time-scale.

**Comment by bsunanda** [comment]
@srimanob @qliphy Please merge this PR

**Comment by srimanob** [comment]
+Upgrade

**Comment by qliphy** [comment]
+1

**Pull request merged**
