### PR TITLE
Fix the `ThroughputService` and `FastTimerService` DQM folders

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Include the information about whether Simultaneous Multi Threading (SMT) is enabled or disabled after the processor model name.

Fix the DQM folder used by the `ThroughputService` to take into account the processor model name (and the SMT status) if the corresponding flag is enabled.

#### PR validation:

The processor model name and the SMT status not appear correctly in the DQM folder names for the `FastTimerService` and `ThroughputService`:

image

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

To be backported to CMSSW 12.4.x and 12.5.x for data taking.

### CODE REVIEW

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
@smuzaffar somethin's weird is going on with the tests ?
https://cmssdt.cern.ch/jenkins/job/ib-run-pr-tests/28998/console says "success", but the bot still list the test as "Pending" ?

**Comment by fwyzard** [comment]
please test

**Comment by missirol** [comment]
+hlt

**Comment by perrotta** [comment]
+1

**Pull request merged**
