### PR TITLE
Updates to L1T packer needed to simultaneously pack GT inputs and GMT/Calo ouputs

### PR DESCRIPTION
**Pull request by mulhearn**
A bug in the Stage2 unpacker for L1T made it impossible to pack GT inputs Calo/GMT outputs using the same code as designed. This led to crashes being untested until an early MW GR. The GT input unpacking was disabled.

This PR is the proper fix, which allows GT unpacker to be turned back on. This PR includes updates to our integration tests which check the unity of GT packing + unpacking. (As for Calo and GMT).

This PR supersedes #14291.

### CODE REVIEW

**Comment by mulhearn** [comment]
This PR passes internal L1T integration tests and bitwise reproduces L1T in CMSSW_806 (i.e. makes no change to L1T algorithms).

**Comment by mulhearn** [comment]
+1

**Comment by mulhearn** [comment]
The 81x version is under development.  (Unfortunately this branch will not work as is in 81x)

**Comment by davidlange6** [comment]
+1

**Pull request merged**
