### PR TITLE
bug fix in the linearizer ...

### PR DESCRIPTION
**Pull request by nancymarinelli**
.. used for the single crystal TP (phase 2)

### CODE REVIEW

**Comment by thomreis** [comment]
please test

**Comment by thomreis** [comment]
+1

**Comment by fabiocos** [comment]
@nancymarinelli @kpedro88 in which workflow is this PR really tested?

**Comment by nancymarinelli** [comment]
Hi,
it's for the upgrade. Not sure exactly in which workflow it's tested. 
Probably in all workflows, since often I make test plots on single 
electron relvals.

Nancy

On 11/10/18 22:48, Fabio Cossutti wrote:
> @nancymarinelli @kpedro88 in which workflow is this PR really tested?
>

-- 
________________________________________
Nancy Marinelli
Research Associate Professor
University of Notre Dame, IN, US
CERN, Bdg 40/3-A01, 1211 Geneva
SWITZERLAND
Phone +41-22-76-70809
fax +41-22-76-78940

**Comment by fabiocos** [comment]
@nancymarinelli my point is where are we supposed to see an effect. Not in regular IB tests I would say, judging from the output of the DQM tests

**Comment by nancymarinelli** [comment]
Hello
this software is part of the trigger primitive generation phase II. If  
that collection is monitored by your tests, one can see what/if changes.
You should know better than me regarding tests.

   Nancy

On 15/10/18 10:51, Fabio Cossutti wrote:
> @nancymarinelli my point is where are we supposed to see an effect. Not in regular IB tests I would say, judging from the output of the DQM tests
>

-- 
________________________________________
Nancy Marinelli
Research Associate Professor
University of Notre Dame, IN, US
CERN, Bdg 40/3-A01, 1211 Geneva
SWITZERLAND
Phone +41-22-76-70809
fax +41-22-76-78940

**Comment by nancymarinelli** [comment]
Hi, has the fix been put in the  last IB ? It is important that the fix go in for the release

**Comment by kpedro88** [comment]
@nancymarinelli the PR has not been merged yet. You will get a notification when it is.

I am not sure how much (if any) DQM we have for trigger emulation. If you have a plot from a private test of the fix, that would be a useful input.

**Comment by fabiocos** [comment]
@nancymarinelli @kpedro88 it looks a bit curious that the effect of a fix that is claimed to be so important and urgent seems to be invisible to any test. How do we know it is doing the right thing sorry? Was this verified somewhere? Or are we just trusting something that looks reasonable at first sight?

**Comment by nancymarinelli** [comment]
Fabio, please.
I have checked the effect privately. Tha was a bug I introduced. And 
those lines remove the use of high gains in the ECAl aplifier.
The bug fix is needed.


On 20/10/18 04:14, Fabio Cossutti wrote:
> @nancymarinelli @kpedro88 it looks a bit curious that the effect of a fix that is claimed to be so important and urgent seems to be invisible to any test. How do we know it is doing the right thing sorry? Was this verified somewhere? Or are we just trusting something that looks reasonable at first sight?
>

-- 
________________________________________
Nancy Marinelli
Research Associate Professor
University of Notre Dame, IN, US
CERN, Bdg 40/3-A01, 1211 Geneva
SWITZERLAND
Phone +41-22-76-70809
fax +41-22-76-78940

**Comment by nancymarinelli** [comment]
Hello
This is for upgraded trigger primitives. As of today, they are only a 
product and they are not used anywhere down the chain (L1) where any 
effect might be seen. The tests are private, on a sample of 
sSingleElectron at 1 TeV.
All this is part of a long term development. It's not used  in today's 
applications and it's used to produce upgrade samples for further develpment

On 22/10/18 20:21, Fabio Cossutti wrote:
> @nancymarinelli I am just asking which kind of test has been done and where is this fix supposed to show an effect, as in the PR tests no effect is visible.
>

-- 
________________________________________
Nancy Marinelli
Research Associate Professor
University of Notre Dame, IN, US
CERN, Bdg 40/3-A01, 1211 Geneva
SWITZERLAND
Phone +41-22-76-70809
fax +41-22-76-78940

**Pull request merged**
