### PR TITLE
Factory for adding UserHooks to PythiaHadronizer and SUEP decay pythia Hook

### PR DESCRIPTION
**Pull request by cericeci**
#### PR description:

This PR includes two main changes:

- A mechanism to add UserHooks to [Pythia8Hadronizer](https://github.com/cericeci/cmssw/blob/64c2e3bd86870980489be736d4600a6d36ed8206/GeneratorInterface/Pythia8Interface/plugins/Pythia8Hadronizer.cc) through the usage of a PluginFactory (thanks to @kpedro88  for the idea and pointers on how to), so the source code of the main pythia plugin does not need to be modified when adding user modifications. This idea can be used in the future to migrate the current implementation of several UserHooks that are currently hard-coded.

- A module dedicated to soft unclustered energy pattern (SUEP or soft-bombs)-like decays, following the description of [1612.00850](https://arxiv.org/abs/1612.00850). It can be used to decay an SM particle through a soft-bomb shower. 
  - The suep shower code ([header](https://github.com/cericeci/cmssw/blob/SUEPpythia_dev/GeneratorInterface/Pythia8Interface/interface/suep_shower.h) and [source](https://github.com/cericeci/cmssw/blob/SUEPpythia_dev/GeneratorInterface/Pythia8Interface/src/suep_shower.cc)) is taken directly from [Simon Knapen's implementation](https://gitlab.com/simonknapen/suep_generator). As a consequence it does not follow cms' code standards. Should it be adapted as well?
  - The module uses the previously discussed PluginFactory to be included inside the Pythia8Hadronizer and can be used for decays of ME obtained from either pythia or a LHE producer such as madgraph. An example of its usage can be found [here](https://github.com/cericeci/cmssw/blob/SUEPpythia_devtests/GeneratorInterface/Pythia8Interface/test/suep_decay.py). It's usage is based on the inclusion of the following lines inside the process.generator inside the fragment:
```
        UserCustomization = cms.VPSet(
           cms.PSet(
             pluginName = cms.string("SuepDecay"),
             idDark = cms.int32(999999), # pdgId of the dark meson
             idMediator = cms.int32(25), # pdgId of the mediator
             temperature = cms.double(2) # Temperature of the thermal distribution
           )
``` 

#### PR validation:

Code-checks passed, unit tests passed. 
Tests using a [local config file](https://github.com/cericeci/cmssw/blob/SUEPpythia_devtests/GeneratorInterface/Pythia8Interface/test/suep_decay.py) show that the SUEP module properly decays the Higgs boson.

#### Backporting:

Once this is merged we aim for a backport to 10_6_X for UL MC production.

### CODE REVIEW

**Comment by kpedro88** [comment]
please test

**Comment by agrohsje** [comment]
@qliphy @perrotta should we apply the cms coding rules to the code that is based on external input?  please let us know.

**Comment by perrotta** [comment]
> @qliphy @perrotta should we apply the cms coding rules to the code that is based on external input? please let us know.

Well, for the part that sits on CMSSW why not?
Unless you are copying code from (e.g.) pythia, and I understand that for the sake of maintainability it would be advisable to limit the changes wrt the original code to the minimum

**Comment by agrohsje** [comment]
Hi @cericeci. The code by Simon is still private and not planned to be part of P8 or whatever? If not, @perrotta suggested to adjust. Let me know.

**Comment by cericeci** [comment]
Hey @agrohsje @perrotta, my understanding is that there was no intention of having it merged with P8 (the public gitlab of the code has been around for a year or so without any discussion that I see). I got it second-hand from @kpedro88, though, maybe he is aware of an ongoing effort that I don't know about and can comment.
If that's the case (and the policy) I'll update the proper files to follow CMS' conventions

**Comment by kpedro88** [comment]
I am also not aware of any plan to include the SUEP code in Pythia8.

**Comment by agrohsje** [comment]
So @cericeci will you adapt as you proposed and as recommended by @perrotta ?

**Comment by cericeci** [comment]
@agrohsje I modified the code to make it more cmssw-compliant as recommended by @perrotta, including some more cleanup and commenting so what the showering module does is more clear. I'd like for this one to be reviewed

**Comment by agrohsje** [comment]
please test

**Comment by agrohsje** [comment]
+generators

**Comment by qliphy** [comment]
+1

**Pull request merged**
