### PR TITLE
Zdc task

### PR DESCRIPTION
**Pull request by deguio**
this PR supersedes #16408 and implements for online DQM:

- adds ZDCTask to monitor ZDC during HI
- extend the hcal2 app to process FEDs 1119, 1121, 1123
- add Qie11Task for pedestal runs

for full support of dual fed readout in dqm one additional PR should come.

### CODE REVIEW

**Comment by BetterWang** [comment]
ZDC will switch to QIE8 using CASTOR partition to read out.

**Comment by dmitrijus** [comment]
please forwards these changes to 81x if you want them integrated today :)

**Comment by deguio** [comment]
will do it soon

**Comment by deguio** [comment]
here it is: #16476

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
