### PR TITLE
Run3-gex136C Try to take care of compilation warning issues in FastSimulation/MaterialEffects

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Try to take care of compilation warning issues in FastSimulation/MaterialEffects

#### PR validation:

Use the runTheMatrix test workflows

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
@bsunanda , in this case SimTrack and SimVertex containers are produced in the same way as in FullSim, at least, for primary particles?

**Comment by civanch** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
