### PR TITLE
Hcal validation update 10_0_X ieta shift fix

### PR DESCRIPTION
**Pull request by bcmcms**
Updates include:

(1) fix a few plots in which ieta was shifted

(2) fix error bars for some plots

(3) clean up some obsolete files

(4) fix era setting for digi validation plots

(5) make the digi time sample analysis less hard-coded (uses soi from tool.presamples() everywhere)

(6) For some of energy mean vs ieta plots, we moved from “s” (RMS spread error) to ” ” (error on the mean)

(7) use a separate ME for HO’s “emap”, as HO being plotted at depth=7 caused confusions (plotting at depth=4 can collide with HB depth=4 after HB phase1 upgrade)

### CODE REVIEW

**Comment by dmitrijus** [comment]
+1

**Comment by hatakeyamak** [comment]
We will have to make a couple of additional fixes. We will update this PR today.

This is not a requirement, but if this can make pre4, it will make the pre4 validation a little easier.

**Comment by deguio** [comment]
@mariadalfonso @abdoulline

**Comment by deguio** [comment]
Hi @fabiocos 
this one is a bug fix PR for validation and it is fully signed. it came only recently and it is not included in the spreadsheet from what I see, but having that in pre4 would help the validation. otherwise it can go in as a bugfix PR right after.

thanks.

**Comment by dmitrijus** [comment]
+1

**Comment by hatakeyamak** [comment]
@dmitrijus thanks. @bcmcms added a few additional bug fixes yesterday, but now we think this PR should be really ready to merged from our point of view.

**Comment by fabiocos** [comment]
@bcmcms @deguio This PR is not mergeable, could you please fix it so as we consider it?

**Comment by bcmcms** [comment]
I am not sure why, but it seems this PR has gone a little out of control. Apologies, but it is being closed; the changes are instead available in https://github.com/cms-sw/cmssw/pull/22034

**Pull request closed without merging**
