### PR TITLE
Egm smearer 76 x

### PR DESCRIPTION
**Pull request by fcouderc**
Add to CMSSW the electron/photon energy scale and resolution modifier. This is used at analysis level to  for data/MC discrepancy between energy scale and resolution for EM objects. This also equalizes the energy scale vs time for data.
Below are the plots of the Zee before (top) and after (bottom) applying the corrections. Left plots refer to EB-EB pairs and right plots to EE-EE pairs.

[Zee_uncalib.pdf](https://github.com/cms-sw/cmssw/files/258984/Zee_uncalib.pdf)
[Zee_calib.pdf](https://github.com/cms-sw/cmssw/files/258983/Zee_calib.pdf)

### CODE REVIEW

**Comment by fcouderc** [comment]
please test

**Comment by fcouderc** [comment]
@cmsbuild 
what happens with this PR? We would like to push that also in 80X and 81X but I would first like to have this done for 76X
Thanks

**Comment by davidlange6** [comment]
@fcouderc - please instead start with a 81x request. It is where all new development goes before being integrated into production releases. Thanks!

**Comment by fcouderc** [comment]
but this is not really development, this is a tool that is already used at analysis level but not yet committed (so taken from personal branches which is not very good). The numbers in there only make sense for 76X.  Do you still want me to commit first 81X ?

**Comment by fcouderc** [comment]
@davidlange6 but this is not really development, this is a tool that is already used at analysis level but not yet committed (so taken from personal branches which is not very good). The numbers in there only make sense for 76X. Do you still want me to commit first 81X ?

**Comment by fcouderc** [comment]
so what happens with this PR? As said this is already in use except that people can use most recent version of 76X because the private fix is not compatible.

**Comment by davidlange6** [comment]
@fcouderc - apologies, 76x usually falls behind the more active releases - but, yes, we need a 81x version of the tool for review. Its the policy for all cmssw contributions.

**Pull request closed without merging**
