### PR TITLE
Run3-hcx376 Get rid of the obsolete constructor of the HcalTopology class

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Get rid of the obsolete constructor of the HcalTopology class

#### PR validation:

Use the runTheMatrix test workflows

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by perrotta** [comment]
Thank you @bsunanda !
This follows a suggestion proposed by @Dr15Jones in https://github.com/cms-sw/cmssw/pull/46308#issuecomment-2405519457

**Comment by bsunanda** [comment]
+geometry

**Comment by perrotta** [comment]
ping bot

**Comment by perrotta** [comment]
urgent
(to be backported in CMSSW_14_1_X together with #46308)

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
