### PR TITLE
Corrections for HGCal v17 geometry

### PR DESCRIPTION
**Pull request by Pruthvi-ch**
PR description:

Correction for cassettes and partial wafers for v17 version of HGCal geometry. 

PR validation:

Tested using overlap checking tool and fireworks for V17 versions of HGCal geometry

if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
+1

**Comment by bsunanda** [comment]
@srimanob Could you please approve this PR. Needed for V17 version of HGCal Geometry

**Comment by srimanob** [comment]
+Upgrade

The V17 HGCal (should correspond to C18 in Geometry conf) is new and not yet in detector description. Fixing/modifying it should not effect existing geometry. Maybe @bsunanda and @Pruthvi-ch can confirm that changes in this PR will not effect others.

**Comment by Pruthvi-ch** [comment]
@srimanob This does not affect the existing geometry. These functions are only used in the v17 geometry.

**Comment by qliphy** [comment]
+1

**Pull request merged**
