### PR TITLE
Phase2-hgx312A Add the v17 version for mixed layer of HGCal

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Add the v17 version for mixed layer of HGCal

#### PR validation:

Use cfg's in Geometry/HGCalCommonData/test/python

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
+1

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cvuosalo @civanch @srimanob Please approve this PR

**Comment by srimanob** [comment]
+Upgrade

**Comment by bsunanda** [comment]
@perrotta @qliphy Could you please merge this?

**Comment by perrotta** [comment]
> @perrotta @qliphy Could you please merge this?

@bsunanda not before it gets (re)-signed by @cms-sw/geometry-l2

**Comment by bsunanda** [comment]
@cvuosalo Could you sign this for pre4

**Comment by cvuosalo** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
