### PR TITLE
adapt Pythia8Interface to pythia8 302 (PR cmsdist #5869, to be tested together)

### PR DESCRIPTION
**Pull request by mkirsano**
#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by mkirsano** [comment]
To be tested together with PR cmsdist #5869 (including code-checks)

**Comment by silviodonato** [comment]
code-checks

**Comment by silviodonato** [comment]
@mkirsano  please update the pull request in order to pass the code checks above

**Comment by smuzaffar** [comment]
test parameters
- pull_requests = cms-sw/cmsdist#5869

**Comment by smuzaffar** [comment]
please test

**Comment by silviodonato** [comment]
what is the status of this PR and cms-sw/cmsdist#5869?
@mkirsano, @SiewYan, @mkirsano, @cmsbuild, @GurpreetSinghChahal, @agrohsje, @alberto-sanchez, @qliphy

**Comment by mkirsano** [comment]
Discussed yesterday at the GEN meeting. Decision to be taken.

**Comment by silviodonato** [comment]
+1

**Comment by smuzaffar** [comment]
@mkirsano , looks like this broke at least one relval ( 1361.181 )

[a]
https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc820/CMSSW_11_2_X_2020-06-11-1100/pyRelValMatrixLogs/run/1361.181_GluGluHToZZTo4L_M125_Pow_py8_Evt_13UP18ml+GluGluHToZZTo4L_M125_Pow_py8_Evt_13UP18ml+DIGIUP18ml+RECOUP18ml+HARVESTUP18+NANOUP18ml/step1_GluGluHToZZTo4L_M125_Pow_py8_Evt_13UP18ml+GluGluHToZZTo4L_M125_Pow_py8_Evt_13UP18ml+DIGIUP18ml+RECOUP18ml+HARVESTUP18+NANOUP18ml.log#/9302-9310

```
#5  0x00002ba9f8fdcb7c in Pythia8::PhysicsBase::beginEvent() [clone .localalias.28] () from /cvmfs/cms-ib.cern.ch/nweek-02632/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_X_2020-06-11-1100/external/slc7_amd64_gcc820/lib/libpythia8.so
#6  0x00002ba9f9014dac in Pythia8::Pythia::beginEvent() () from /cvmfs/cms-ib.cern.ch/nweek-02632/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_X_2020-06-11-1100/external/slc7_amd64_gcc820/lib/libpythia8.so
#7  0x00002ba9f901d9d9 in Pythia8::Pythia::next() () from /cvmfs/cms-ib.cern.ch/nweek-02632/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_X_2020-06-11-1100/external/slc7_amd64_gcc820/lib/libpythia8.so
#8  0x00002ba9f792486b in Pythia8Hadronizer::hadronize() () from /cvmfs/cms-ib.cern.ch/nweek-02632/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_X_2020-06-11-1100/lib/slc7_amd64_gcc820/pluginGeneratorInterfacePythia8Filters.so
```

**Pull request merged**
