### PR TITLE
Apply code format to Geometry/HcalCommonData

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

This PR applies the code format to Geometry/HcalCommonData package (in preparation to the EventSetup consumes migration #26584)

#### PR validation:

The code compiles.

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
I think this PR should be held until #26535 gets merged.

**Comment by cvuosalo** [comment]
+1

**Comment by makortel** [comment]
Closing in order to not create conflicts with #26535.

**Pull request closed without merging**
