### PR TITLE
fix sequences for HE plan1

### PR DESCRIPTION
**Pull request by kpedro88**
The "final" set of HCAL RecHits produced needs to be named `hbhereco` in order for downstream modules to pick up the right collection. This means that, in sequences where `HBHEIsolatedNoiseReflagger` is not run, the `hbheplan1` module needs to be renamed to `hbhereco`. Therefore, where the `HBHEPhase1Reconstructor` would normally be named `hbhereco` in these sequences, it needs to be `hbheprereco` instead.

This change is made for NZS and Cosmic sequences. It should hopefully fix the crash at the Tier0. This PR will be backported to 90X and 84X (once the fix is agreed to work).

@bsunanda: at some later date we need to make AlCa sequences aware of Phase1 changes:
https://github.com/cms-sw/cmssw/blob/master/Calibration/HcalAlCaRecoProducers/python/ALCARECOHcalCalMinBias_cff.py
https://github.com/cms-sw/cmssw/blob/master/Calibration/HcalAlCaRecoProducers/python/ALCARECOHcalCalPedestal_cff.py
(I just noticed today that these exist.)

attn: @deguio, @hatakeyamak, @abdoulline

### CODE REVIEW

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@kpedro88 
please make a 90X PR

**Comment by slava77** [comment]
from visual inspection, the changes make sense

**Comment by kpedro88** [comment]
@slava77 I also inspected the sequences from workflow 7.2 using `edmConfigDump` and things look right

**Comment by davidlange6** [comment]
and a 84x PR. Thanks

**Comment by slava77** [comment]
Looks like I'm not alone about the frontier problem

**Comment by deguio** [comment]
I was finally able to test this.
I reproduced the problem with 2000 events of WF 7.2 and I confirm that this PR fixes it.

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/17751	9cd33f1
- code changes are in line with the description (the description may better be extended to include the NZS changes as well)
- jenkins tests pass and comparisons with baseline show no differences (the affected cosmics workflow is not checked by default)
- Confirmed to work as mentioned in https://github.com/cms-sw/cmssw/pull/17751#issuecomment-283804709
- Tested additionally with jenkins and enough events in the cosmics workflows in
https://cmssdt.cern.ch/jenkins/job/ib-any-integration/18128/console  with the 7.2 wf included. See more details in https://github.com/cms-sw/cmssw/pull/17758#issuecomment-284024412

**Pull request merged**
