### PR TITLE
Fix some code checks warnings in FWCore

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

While trying to reproduce code-checks failure in https://github.com/cms-sw/cmssw/pull/32373#issuecomment-737414067 `scram b code-checks` complained a few explicitly deleted function being in `private:` section rather than in `public:` section. This PR moves those functions to `public:`.

Motivated by https://github.com/cms-sw/cmssw/pull/32373#issuecomment-737414067 itself this PR removes the offending (even if I wasn't able to reproduce the code-checks failure locally) default value of a parameter in an overridden member function. I suppose it should have never been added as I can't see any purpose for it now.

#### PR validation:

Framework unit tests run.

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
@Dr15Jones please review

**Comment by Dr15Jones** [comment]
+1

**Comment by makortel** [comment]
(the differences are related to MessageLogger messages)

**Comment by silviodonato** [comment]
+1

**Pull request merged**
