### PR TITLE
Add unit tests for SiStrip DAQ and DCS O2O.

### PR DESCRIPTION
**Pull request by hqucms**

### CODE REVIEW

**Comment by ggovi** [comment]
please test

**Comment by hqucms** [comment]
@ggovi 
The failure should be due to missing credentials for DB access. We will need the following for the two added O2O tests to run:

 - in .netrc:
    `machine cms_omds_tunnel/cms_trk_r login cms_trk_r password xxxxxx`
 - in .cms_cond/db.key:
    need the STRIP key to access "cms_omds_adg/CMS_TRK_R"

**Comment by ggovi** [comment]
@hqucms 
Done on my side ( the db key ). On the IB side, they have received the new line for the .netrc.

**Comment by hqucms** [comment]
@ggovi 
Thank you very much! Could you please trigger the test again?

**Comment by smuzaffar** [comment]
please test

**Comment by ggovi** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
