### PR TITLE
Dynamic strip reco 74 x

### PR DESCRIPTION
**Pull request by andrewj314**
Rebase of PR #10805 to 7_4_X

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@gpetruc are you going to integrate this for re-miniAOD?
If so, if I understand correctly, we need a non-trivial tau sequence for miniAOD workflow to run the needed modules.

**Comment by gpetruc** [comment]
Hi,

Yes, this is the plan, and so the miniAOD_tools should be told to re-run
tau reco.

Giovanni

**Comment by slava77** [comment]
@andrewj314 @veelken @isobelojalvo 
if we are backporting such a large feature, why is the smaller one (pixel hits cut) from #8095 is left out?

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/10943	09467ef
- specific to the "dynamic tau strip reco" feature, the backport from 75X/76X is made correctly
- jenkins tests pass and comparisons with baseline show differences in tau-related products or plots
- additionally tested locally in CMSSW_7_4_10_patch1 /test area sign573/
    - CPU changes are very similar to what was observed in 75X/76X
    - the same set of products has changes in the outputs in AOD (added 8 new products; removed 3 old ones)

However,
--------
This backport is not very meaningful in the context of 74X, due to lack of modification functions needed to rerun needed reco modules at the miniAOD level.

The most straightforward way would be to use AOD from 74X MC or from the current prompt reco and come up with the right set of modifications so that the following actually runs on a given file
and executes new needed tau reco modules
```
cmsDriver.py step5  --conditions GTname  --data  -n -1\
 --eventcontent MINIAOD --runUnscheduled  -s PAT --datatier MINIAOD\
 --customise SLHCUpgradeSimulations/Configuration/postLS1Customs.customisePostLS1\
 --filein file:a.root  --no_exec
```
(or use some "standard" pat py config file.

**Comment by veelken** [comment]
Hi Slava,

I am not sure I understand the comment that you make after "However" above:
the use case that we have in mind is to rerun the tau reconstruction (PFTau sequence defined in RecoTauTag/Configuration/python/RecoPFTauTag_cff.py) right at the beginning of the miniAOD production sequence, i.e. using AOD inputs.

Can you be a bit more explicite concerning where you see a problem/what still needs to be done ?

I agree with you that PR #8095 should be included in this branch. 
AJ, can you take care of that, please ?

Thank you,


Christian

**Comment by andrewj314** [comment]
@slava77 @veelken PR #8095 has been added to this branch. Thanks!
AJ

**Comment by slava77** [comment]
Hi Christian,

On 8/27/15 3:26 AM, Christian Veelken wrote:
> Hi Slava,
> 
> I am not sure I understand the comment that you make after "However" above:
> the use case that we have in mind is to rerun the tau reconstruction
> (PFTau sequence defined in
> RecoTauTag/Configuration/python/RecoPFTauTag_cff.py) right at the
> beginning of the miniAOD production sequence, i.e. using AOD inputs.

miniAOD  configuration should be aware of it.
Maybe it's a one-liner, but it still should be added someplace.
Giovanni should make a suggestion where (since I don't think that all
tau reco should be rerun
in front of miniAOD by default).

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by gpetruc** [comment]
I'd make it a customize for running on pre-existing AODs.
It could either be called remakeTausFromAOD or be a generic runOn74Xv1AOD
in case we need it.
I'll try code it later today both for 74X and for 75X (in case we do the
re-MiniAOD in 75X)

Giovanni

**Comment by veelken** [comment]
Hi Giovanni,

please rerun the complete PFTau sequence defined in RecoTauTag/Configuration/python/RecoPFTauTag_cff.py at the beginning of miniAOD production. The dynamic strip reconstruction changes the way how the reco::PFTau objects are built, which is one of the first steps in the tau reconstruction. It is not enough to rerun part of the tau reconstruction sequence only.

Thank you,


Christian

**Comment by gpetruc** [comment]
This would be my proposal: https://github.com/cms-tau-pog/cmssw/pull/10
Testing it now.

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/10943	a95733f
- this correctly picks up the feature from  #8095 
- jenkins tests pass and show differences only in tau distributions
- tested locally in CMSSW_7_4_10_patch1 /test area sign573/ comparing the previous commit results with the latest one (09467ef  to a95733f): changes are small, as expected from tests of #8095

**Comment by gpetruc** [comment]
I tested on some MC and Data, including this PR. Timing increases by a bit,
as expected, but within reason: I see about +10% in data when also
rerunning the taus ( before the cleanup of
https://github.com/gpetruc/cmssw/pull/5 )

**Comment by monttj** [comment]
+1
This was already approved in 76X.

**Comment by slava77** [comment]
@davidlange6 this one is in #10649 now
and can be closed

**Pull request closed without merging**
