### PR TITLE
TnP code for GEM muon efficiency measurement for backport

### PR DESCRIPTION
**Pull request by qyguo**
It is a backport and links to the PR 41057
https://github.com/cms-sw/cmssw/pull/41057

### CODE REVIEW

**Comment by watson-ij** [comment]
please test

**Comment by emanueleusai** [comment]
type gem

**Comment by emanueleusai** [comment]
backport of https://github.com/cms-sw/cmssw/pull/41057

**Comment by emanueleusai** [comment]
please test

**Comment by emanueleusai** [comment]
+1

**Comment by perrotta** [comment]
+1

**Comment by perrotta** [comment]
merge

**Pull request merged**
