### PR TITLE
bsunanda:Phase2-Fast01 Add a layer of 4 mm thick LYSO to test FastTiming in barrel

### PR DESCRIPTION
**Pull request by bsunanda**
Done with the context of Run 1 tracker - use the 1 cm space between tracker outer cylinder and calorimeter barrel

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by lgray** [comment]
@bsunanda Run 1 tracker appears to be a typo? I only edits to phase 2 tracking information in the files. It may also be useful to already figure out a scheme by which to put this into @kpedro88's naming and auto-generated geometry scheme.

**Comment by kpedro88** [comment]
NB: my intention for the 2023 geometry generation (not yet implemented) was to use the letter "I" for the timing layer variations, since "T" is already used for the tracker. We should probably consider "I1" to be "no timing layer" (for the existing D1,2,3,4 geometries) and then "I2" can be this version of the timing layer.

**Comment by lgray** [comment]
Followed up in mail, this is with run 1 tracker. Need to pursue with @boudoul or others to figure out how to do this for phase 2.

**Comment by ianna** [comment]
+1

**Comment by davidlange6** [comment]
@bsunanda @ianna -since we have multiple material.xml files - why should we also update the materials in all of them for scenarios affecting only phase 2 (potentially)?

**Comment by ianna** [comment]
@davidlange6 - adding a new material does not affect geometry, but changing properties of an existing one does. I think, comparison is easier if all of them are kept in sync. Besides, dev version should become prod for 810. If you think, it is better to keep Geometry/CMSCommonData/data/materials.xml unchanged, I'd suggest to move dev version to Geometry/CMSCommonData/data/PhaseI/materials.xml and update 2017 and 2019 scenarios accordingly

**Comment by bsunanda** [comment]
@ianna @davidlange6 This was some ommission of element and a well known compound. It is better to be defined everywhere. If for some reason you do not want in materials.xml in the base area it is better to be kept for all future versions.

**Comment by davidlange6** [comment]
can we just have one materials.xml then? that would simply things..

**Comment by bsunanda** [comment]
@davidlange6 I think it should be better. I wonder why we have multiple

**Comment by civanch** [comment]
Normally having only one material.xml file is OK, addition of an extra material inside will not add overhead. However, there is a use-case when a sub-detector developer start to play with density of a particular volume. In this particular case, for the material with the same name a different density is needed, which require a new file, which may be not synchronized with entire developments.

So, ideally we should be based on one material.xml but if for the time being we have several we need to modify all of them trying to be in synk.

**Comment by davidlange6** [comment]
so is it easy or hard to make this change now while we are thinking about it?

**Comment by ianna** [comment]
@davidlange6 - it is easy and it's on my todo list. It will be in for pre13 for sure or earlier if you want it for pre12.

**Comment by davidlange6** [comment]
+1

pre13 sounds good- thanks

**Pull request merged**
