### PR TITLE
Check for valid pointers in GetJetConstituentsQuick (Port of PR#7525 from 72X)

### PR DESCRIPTION
**Pull request by heilman**
This was not ported forward from CMSSW_7_2_X.  This change adds pointer checking to GetJetConstituentsQuick().  This prevents errors when looping over genJet constituents that have been dropped from miniAOD.

### CODE REVIEW

**Comment by slava77** [comment]
@heilman please make a change without reformatting the full file, just modify what you need to modify.

**Comment by heilman** [comment]
I reverted to the old formatting.  Hopefully that is ok.

**Comment by slava77** [comment]
Hi Jesse,
this looks much better
Please change the PR subject (the top line to be more descriptive, e.g. "Check for valid pointers in Jet Constituents (port of PR#7525 from 72X).
Also, please make a pull request for 75X as well.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
From the Jenkins results, it appears this change is making akPu3PFJets disappear. In workflow 	140.53_RunHI2011 there are significant changes in the DQM plots, as shown below (black is old, and red is new). Other workflows do not show any problems.
This problem needs to be understood and fixed before this PR can go forward.

jetenergy
pujets

**Comment by cvuosalo** [comment]
+1

For #9539 f1842687f4f3b5e67421f7abc6215ec441c6cca7

Adding a check for a valid pointer to Jet::GetJetConstituentsQuick. No change in monitored quantities would be expected.

The code changes are satisfactory. Jenkins [tests](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-9539/2699/summary.html) against baseline CMSSW_7_4_X_2015-06-10-1100 show no significant differences, except those mentioned above. However, repeated tests of workflow 140.53_RunHI2011 (the same that shows differences above) against baseline CMSSW_7_4_2  fails to consistently reproduce the problem. A test of 10 events showed a few missing akPu3PFJets in different patterns to those above, but tests with 30 and 100 events showed no differences, and event content was identical to baseline. Also, workflow 140.0_HydjetQ_MinBias with 30 events showed no differences. The missing jets problem appears to be an intermittent issue not related to this PR.

**Comment by heilman** [comment]
Uh oh.  I used didn't check that this was resolved before making the 75X commit on the same dev branch.  Is this a problem or can the last in the commit chain be removed for this PR?

**Comment by slava77** [comment]
@heilman you can revert the commit and push, it will be picked up here.
You will need to remake the other PR

**Comment by heilman** [comment]
Commit reverted, I think.  Sorry for all the confusion.  I'm not 100% sure what I'm doing with version control here.  I have closed the other PR and will make another with a separate dev branch.

**Comment by slava77** [comment]
nope, it didn't work

**Comment by heilman** [comment]
I'm not sure what to do then.  Is this PR broken and I should remake it?

**Comment by slava77** [comment]
On 6/16/15 7:14 AM, heilman wrote:
> I'm not sure what to do then. Is this PR broken and I should remake it?
> 

this may be the easiest

**Comment by heilman** [comment]
Closed due to devbranch confusion.

**Pull request closed without merging**
