### PR TITLE
Clang SA fixes for clang compile errors and report generation errors.

### PR DESCRIPTION
**Pull request by gartung**

### CODE REVIEW

**Comment by gartung** [comment]
@ktf @Dr15Jones Why is this orp-pending? I thought moving to the CMSSW_7_5_X queue would remove that.

**Comment by ktf** [comment]
We have not opened 75X to everyone yet.

**Comment by gartung** [comment]
This fixes the clang compiler error in 
https://github.com/cms-sw/cmssw/pull/7683

**Comment by gartung** [comment]
This also fixes the data class report being emplty.

**Comment by nclopezo** [comment]
This pull request has conflicts. I think it is because part of the changes were already merged in https://github.com/cms-sw/cmssw/pull/7780
https://cmssdt.cern.ch/SDT/html/showIB.html and is going to be included in the next IB.

**Comment by gartung** [comment]
Should I rebase to the newest CMSSW_7_5_X?

**Comment by Dr15Jones** [comment]
yes please

**Comment by gartung** [comment]
Rebase is done. Merge should have no conflicts.

**Comment by ktf** [comment]
@cmsbuild please test

**Comment by Dr15Jones** [comment]
The failure was a DAS error

**Comment by Dr15Jones** [comment]
Please test

**Comment by ktf** [comment]
Bypassing ORP.

**Pull request merged**
