### PR TITLE
Remove unused deps from TrackingTools and TrackPropagation subsystems

### PR DESCRIPTION
**Pull request by guitargeek**
#### PR description:

Another quick round of automatic BuildFile.xml cleaning to improve the modularity of CMSSW.

After I made sure all of the Reco* Build files don't use dependencies anymore which are not included in the source files, I'm giving the same treatment to some other widely used subsystems.

#### PR validation:

CMSSW compiles. It was checked that all newly added dependencies are actually required by the package with `git grep`.

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by santocch** [comment]
+1

**Comment by silviodonato** [comment]
@perrotta @slava77 this is a technical cleaning. Do you have any comments?

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/29170	d5ce8bc
- technical
- jenkins tests pass

**Comment by silviodonato** [comment]
+1

**Pull request merged**
