### PR TITLE
Use consumes interface for TrackerHitAssociator(ALCA)

### PR DESCRIPTION
**Pull request by wmtan**
This PR modifies uses of TrackerHitAssocator to use the consumes interface needed for multithreading.  This PR is for packages in the ALCA L2 category.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by wmtan** [comment]
This test failure has nothing whatever to do with this PR.  Please fix your problem on jenkins and retest.

**Comment by davidlange6** [comment]
Hi @wmtan

there is no problem on jenkins..

David

**Comment by wmtan** [comment]
Hi @davidlange6 
There *was* a problem on Jenkins for about 3 hours (19 hours ago) where tests failed for all PRs due to a problem causing an empty list of pileup files to be written to the config file for step 2 in test 25202.0, and perhaps other tests.  The problem no longer seems to occur, so you are correct that there is no (known) current problem on Jenkins.

**Comment by diguida** [comment]
@cmsbuild please test

**Comment by diguida** [comment]
@wmtan @davidlange6 
Maybe now the bot is happy ;-)

**Comment by diguida** [comment]
+1

**Comment by davidlange6** [comment]
there was a problem yes. where it was is much more likely not on jenkins and rather on some other service that the IBs depend on.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
