### PR TITLE
Backport of #25189 (raising cluster checker threshold for HI events) for 10_3_X

### PR DESCRIPTION
**Pull request by abaty**
We would like this PR for the current HI data-taking in 10_3_X.

More documentation and some events for testing can be found in the description for #25189.

@mandrenguyen

### CODE REVIEW

**Comment by perrotta** [comment]
backport of #25189

**Comment by perrotta** [comment]
please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/25190	8db6d41
- code changes are in line with the PR description. The backport of #25189 is correct (changes are the same).
- jenkins tests pass and comparisons with the baseline show no differences (only very high occupancy events in pp_on_AA processing for HI can be affected; they are not in the standard tests).

considering that there is no option for a rereco, it is best for this change to be added to the prompt at the earliest possibility.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
