### PR TITLE
Bugfix for cosmic track splitting alignment validation

### PR DESCRIPTION
**Pull request by hroskes**
These fixes are needed for the validation to run, because of 7X and other recent improvements.

Backport of #6244

### CODE REVIEW

**Comment by davidlange6** [comment]
obsolete release queue. closing

**Comment by diguida** [comment]
This fix is needed because Tracker Alignment group has Cosmic MC AlCaRECO dataset only in 70X release cycle. @mmusich to confirm
So, it would be better to have this in.

**Comment by mmusich** [comment]
+1
@diguida, yes, your analysis is correct.

**Comment by frmeier** [comment]
The alternative would be to have the samples quickly reprocessed in a more recent release. Any ETA on this option?

**Pull request closed without merging**
