### PR TITLE
[ALCA] Fixes needed for GCC 10

### PR DESCRIPTION
**Pull request by smuzaffar**
#### PR description:

Added the missing header to fix the GCC 10 build errors.

#### PR validation:

Local build with GCC 10 and normal IB look good

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@silviodonato , this is techinical fix (only added a missing header here), please merge it for next IB

**Comment by silviodonato** [comment]
merge

**Comment by tlampen** [comment]
+1

**Pull request merged**
