### PR TITLE
Join Opt Meeting 2017.10.20 action item : rollback HLTDQM

### PR DESCRIPTION
**Pull request by mtosi**
as it is done in #20620,
rollback HLTDQM, in order to make tier0 jobs safe while keeping the plots in the workflows run for the validation (as requested at the Join Opt Meeting 2017.10.20 [1])

[1]
https://docs.google.com/document/d/1lG7r2OCBWz7dVl7aaUczNT4DvGQJlmOy-ciS2lBhZvw/edit#heading=h.7oamqr4y3fpf

### CODE REVIEW

**Comment by mtosi** [comment]
@davidlange6 @fwyzard @dmitrijus

**Comment by mtosi** [comment]
@cmsbuild, please test

**Comment by mtosi** [comment]
@cmsbuild, please test

**Comment by mtosi** [comment]
@cmsbuild, please test

**Comment by davidlange6** [comment]
seems unlikely this will succeed given the results of the last test - did you forget to commit something

----- Begin Fatal Exception 20-Oct-2017 18:45:01 CEST-----------------------
An exception of category 'LogicError' occurred while
   [0] Calling endJob for module HLTBTagHarvestingAnalyzer/'HltBTagPostValidation'
Exception Message:
Plots not found:
HLT/BTag/Discriminator/HLT_PFMET120_PFMHT120_IDTight_v/hltCombinedSecondaryVertexBJetTagsCalo__b
HLT/BTag/Discriminator/HLT_PFMET120_PFMHT120_IDTight_v/hltCombinedSecondaryVertexBJetTagsCalo__b
----- End Fatal Exception -------------------------------------------------

**Comment by mtosi** [comment]
@cmsbuild, please test

**Comment by dmitrijus** [comment]
hi @mtosi, please fix the conflict.

@davidlange6 
DQM Memory change from 9_2_13 to CMSSW_9_4_X_2017-10-23-1200 is for tier0 (allForPrompt):
Before this PR: 32.60 MiB
After this PR: -1564.17 MiB (less than 92x!)

So, with this PR, 94x could proceed...

The difference between 92x and 94x:

```
-5237.01 KiB     Tracking
1.40 MiB         OfflinePV
1.07 MiB         SiStrip
632.93 KiB       Hcal
315.40 KiB       Muons
271.87 KiB       HLT
-109.10 KiB      DT
40.56 KiB        Physics
-4.87 KiB        MessageLogger
0.05 KiB         L1T
0.03 KiB         Ecal
0.03 KiB         Pixel
0.03 KiB         RPC
0.03 KiB         RecoTauV
Total bytes: -1564.17 KiB
```
Now I do wonder what RecoTauV is doing here...

**Comment by mtosi** [comment]
thanks @dmitrijus (I did not realize there was a conflict)
it should be fixed, now

**Comment by mtosi** [comment]
@cmsbuild, please test

**Comment by dmitrijus** [comment]
+1

**Comment by Martin-Grunewald** [comment]
@mtosi 
Please fix merge conflicts in this PR!

**Comment by mtosi** [comment]
thanks @Martin-Grunewald

**Comment by mtosi** [comment]
@davidlange6 
is it possible to add the feature to send an automatic email when a PR starts to show conflicts ?

**Comment by kpedro88** [comment]
@mtosi it's on the todo list...

**Comment by davidlange6** [comment]
It's even mostly working. But created some noise

David


On 30 Oct 2017, at 15:13, Kevin Pedro <notifications@github.com<mailto:notifications@github.com>> wrote:


@mtosi<https://github.com/mtosi> it's on the todo list...

**Comment by Martin-Grunewald** [comment]
please test

**Comment by mtosi** [comment]
thanks !

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
included in #21231

**Pull request closed without merging**
