### PR TITLE
Phase2-hgx359S Modify the testing code in RecoLocalCalo/HGCalRecAlgos in view of changes made in the Configuration/Geometry area for Phase2 scenarios

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Modify the testing code in RecoLocalCalo/HGCalRecAlgos in view of changes made in the Configuration/Geometry area for Phase2 scenarios

#### PR validation:

Tested the scripts

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by jfernan2** [comment]
+1

**Comment by bsunanda** [comment]
@srimanob Please approve this PR

**Comment by srimanob** [comment]
+Upgrade

**Comment by mandrenguyen** [comment]
+1

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
