### PR TITLE
Move conditions code to use oneapi/tbb headers

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

The old header declarations are deprecated in TBB

#### PR validation:

Code compiles.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by yuanchao** [comment]
+1
* move to oneapi/tbb headers; header compiles ok
* WF matrix tests and unit tests passed
* SA warnings not due to this PR modification

**Comment by tvami** [comment]
+db
 * technical

**Comment by qliphy** [comment]
+1

**Pull request merged**
