### PR TITLE
[10.3][Change GT] Add ZDC, Castor geometry to 2018 MC Gts

### PR DESCRIPTION
**Pull request by lpernie**
Add ZDC, Castor geometry to 2018 MC Gts

### CODE REVIEW

**Comment by lpernie** [comment]
+1

**Comment by lpernie** [comment]
@davidlange6 In this way we have a new Queue which differ from std GT for the geometry.

**Comment by lpernie** [comment]
please test

**Comment by lpernie** [comment]
+1

**Comment by lpernie** [comment]
Hi, @fabiocos can this be merged?

**Comment by lpernie** [comment]
Ah, I see I must resolve conflict now... will do it soon

**Comment by lpernie** [comment]
please test

**Comment by lpernie** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
