### PR TITLE
Added allowedValues for ParameterSetDescription

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

The allowedValues makes it easier to use the ifValue ability of ParameterSetDescription where only the values are needed to be constrained.

#### PR validation:

Code compiles and relevant framework unit test passes.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by makortel** [comment]
+1

**Comment by makortel** [comment]
@Dr15Jones could you also update the documentation in https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideConfigurationValidationAndHelp#A_Switch ?

**Comment by Dr15Jones** [comment]
> could you also update the documentation

done.

**Comment by silviodonato** [comment]
+1

**Pull request merged**
