### PR TITLE
Run3-gex140 Remove 2 obsolete classes from RecoEgamma/EgammaTools

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Remove two obsolete  classes om RecoEgamma/EgammaTools

#### PR validation:

Checked that they were obsolete and not used anywhere

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by swagata87** [comment]
type egamma

for the record, this is the cmsTalk link where we had announced the code deletion, https://cms-talk.web.cern.ch/t/deletion-of-obsolete-code-in-recoegamma-egammatools/16133 , and we had not received any objection about it.

**Comment by clacaputo** [comment]
+reconstruction

- deleting obsolete code  https://cms-talk.web.cern.ch/t/deletion-of-obsolete-code-in-recoegamma-egammatools/16133
- no reco changes

**Comment by perrotta** [comment]
+1

**Pull request merged**
