### PR TITLE
PPS diamond mapping fix for 2023 run (backport) [13_0_X]

### PR DESCRIPTION
**Pull request by grzanka**
#### PR description:

Backport of https://github.com/cms-sw/cmssw/pull/41187

### CODE REVIEW

**Comment by francescobrivio** [comment]
type ctpps

**Comment by francescobrivio** [comment]
backport of #41187

**Comment by francescobrivio** [comment]
test parameters:
 - workflows = 136.793,1043,1044

**Comment by francescobrivio** [comment]
@cmsbuild please test

**Comment by emanueleusai** [comment]
@grzanka this seems to be touching online DQM code. Can you confirm you need this deployed in DQM machines at P5?

**Comment by vavati** [comment]
@emanueleusai  Yes , the bug in DQM is preventing DQM -for strips to work; also the new xml for timing detector will be important online at least we can debug the detectors. So the deployment in P5 before the first stable beam (in fact before the alignment run) would be mandatory. Thanks

**Comment by vavati** [comment]
@emanueleusai  Yes , the bug in DQM is preventing DQM -for strips to work; also the new xml for timing detector will be important online at least we can debug the detectors. So the deployment in P5 before the first stable beam (in fact before the alignment run) would be mandatory. Thanks

**Comment by tvami** [comment]
+alca

**Comment by tvami** [comment]
@cmsbuild ping

**Comment by perrotta** [comment]
type bug-fix

**Comment by tvami** [comment]
urgent
 * as discussed at ORP this should go to 13_0_2

**Comment by emanueleusai** [comment]
+1

**Comment by vavati** [comment]
@emanueleusai  1) for the xml part you can test it with any recent global run done with CTPPS_TOT partition included
2) for the bug fix in DQM: it is affecting Totem Strip which are rarely in run, that's why the bug was not spotted before. Recent global runs (test) are 365241 365244 with the DQM sequence "ctppsDQMCalibrationSource" active (otherwise these detectors are not reconstructed). Without the bugfix you should get error.
These detectors will be in data taking in the PPS alignment run in less than 2 weeks.

**Comment by rappoccio** [comment]
Hi @emanueleusai, can the tests be done in parallel with the merge? We need to cut 13_0_2 ASAP (tomorrow would be ideal).

**Comment by emanueleusai** [comment]
alright

**Comment by emanueleusai** [comment]
+1

**Comment by perrotta** [comment]
+1
- @emanueleusai in any case the fix to totemRPDQMSource_cfi.py is quite obvious, and I don't expect bad surprises from a possible test at P5

**Comment by perrotta** [comment]
> * @emanueleusai in any case the fix to totemRPDQMSource_cfi.py is quite obvious, and I don't expect bad surprises from a possible test at P5

... and with a fillDescriptions method in the TotemRPDQMSource plugin the bug would have been detected immediately, without even the need to fix it afterwards: please think about implementing it @grzanka (or someone else from @cms-sw/ctpps-dpg-l2)

**Comment by perrotta** [comment]
@micsucmed this PR has evidently nothing to do with the issue you are encountering in the online DQM runs

**Comment by grzanka** [comment]
> testROCmService

To me this also has nothing in common with this PR.

After quick look it seems the closest PR related to this error is following commit:
https://github.com/cms-sw/cmssw/commit/5ebe8d8bac6d9eef759b0e991c2d67d870e716c2
and PR: https://github.com/cms-sw/cmssw/pull/40832

This is however far from my knowledge of the framework

**Comment by syuvivida** [comment]
Hello, just to note that our deployment by default is using `git cms-merge-topic 41188`. With git cms-merge-topic, even though this PR has only 2 changes of files, we actually checkout 92 additional packages, including HeterogeneousCore. 
If we use git cherry-pick, this pick up of other packages could be avoided. But this requires more work, since for the online DQM production, we need to deploy 4 PRs in total, and each cherry-pick would require us to find out which files are updated and checkout those packages one by one. 

To avoid human-prone errors, we would like to propose NOT to deploy this PR, but wait until CMSSW_13_0_3 is deployed (which automatically merge this PR and other PRs we already included).

**Comment by fabferro** [comment]
> Hello, just to note that our deployment by default is using `git cms-merge-topic 41188`. With git cms-merge-topic, even though this PR #41188 has only 2 changes of files, we actually checkout 92 additional packages, including HeterogeneousCore. If we use git cherry-pick, this pick up of other packages could be avoided. But this requires more work, since for the online DQM production, we need to deploy 4 PRs in total, and each cherry-pick would require us to find out which files are updated and checkout those packages one by one.
> 
> To avoid human-prone errors, we would like to propose NOT to deploy this PR, but wait until CMSSW_13_0_3 is deployed (which automatically merge this PR and other PRs we already included).

I see the point. Fine to me. Provided that 13_0_3 comes out in a few days as discussed in last (emergency) ORP meeting.

**Comment by syuvivida** [comment]
Dear CTPPS experts (@grzanka @fabferro @vavati ), 
  Thanks to the help of @francescobrivio , we built a playback release using cherry-pick to include this PR 41188, it's probably hard to check the output with the playback run files we have 365045 (since this run has CTPPS included in DAQ but standby). But just in case, could you please take a look of this DQMGUI and see if everything is as what you expected? 
  Thanks!!
  https://cmsweb.cern.ch/dqm/online-playback/session/5dHDFL

**Pull request merged**
