### PR TITLE
Switch modules in RecoTBCalo to thread-friendly types

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:
- Improved const correctness of helper algorithm
- Switched to thread-friendly module types

#### PR validation:

Code compiles without issuing a CMS deprecation warning.

### CODE REVIEW

**Comment by mandrenguyen** [comment]
+1 
technical

**Comment by rappoccio** [comment]
+1

**Comment by perrotta** [comment]
@Dr15Jones out of curiosity (and having nothing to do with your PR).

According to you, is it correct the following syntax, that I never saw before?

https://github.com/cms-sw/cmssw/blob/4648b593142aff08fe19876df5bdbd8b88a468a5/RecoTBCalo/EcalTBHodoscopeReconstructor/src/EcalTBHodoscopeRecInfoAlgo.cc#L101-L102

followed by

https://github.com/cms-sw/cmssw/blob/4648b593142aff08fe19876df5bdbd8b88a468a5/RecoTBCalo/EcalTBHodoscopeReconstructor/src/EcalTBHodoscopeRecInfoAlgo.cc#L130-L131

The first one looks like a `reserve(4)`, but what about using `push_back` as such?

**Comment by Dr15Jones** [comment]
@perrotta the first one `std::vector<int> xclus[4];` is actually an array containing 4 `std::vector<int>`. The `push_back` is fine as it will grow the appropriate `std::vector<int>`.

**Comment by perrotta** [comment]
> @perrotta the first one `std::vector<int> xclus[4];` is actually an array containing 4 `std::vector<int>`. The `push_back` is fine as it will grow the appropriate `std::vector<int>`.

Indeed...
Thank you Chris, and excuse me for the silly question

**Pull request merged**
