### PR TITLE
[TRK POG Validation] add fakes for monitoring w/ |eta| > 2.7

### PR DESCRIPTION
**Pull request by mtosi**
#### PR description:

it turned out that we were missing the --most important-- plots about the fakes in this phase-space

this PR fixes the issue, adding fakes for monitoring w/ |eta| > 2.7 
in addition, it adds this monitoring to the trackingOnly sequence as well

### CODE REVIEW

**Comment by mtosi** [comment]
@cmsbuild , please test

**Comment by jfernan2** [comment]
@mtosi Please add subsystem name to the PR title for easier identification

**Comment by mtosi** [comment]
thanks @jfernan2 for the comment (and sorry for not having done it before)

**Comment by jfernan2** [comment]
Thanks @mtosi
However, this PR goes in the opposite direction to what we discussed on the Tracking DQM Sequence review, around 5k plots are being added, some of them (1500) are empty[1]. Can we expect some DQM Tracking clean up at some point?

[1]
cutsRecoMuonSeededStepInOutHp_trackingParticleRecoAsssociation
cutsRecoMuonSeededStepInOut_trackingParticleRecoAsssociation
cutsRecoMuonSeededStepOutInHp_trackingParticleRecoAsssociation
cutsRecoMuonSeededStepOutIn_trackingParticleRecoAsssociation
cutsRecoPixelPairStepHp_trackingParticleRecoAsssociation
cutsRecoPixelPairStep_trackingParticleRecoAsssociation

**Comment by mtosi** [comment]
this PR is a bug fix

**Comment by fabiocos** [comment]
@mtosi adding several MBs of plots look something strong for a bug fix... Adding MBs of empty plot is something to be clarified IMHO

**Comment by mtosi** [comment]
well, among the quoted list of directories

> cutsRecoMuonSeededStepInOutHp_trackingParticleRecoAsssociation
> cutsRecoMuonSeededStepInOut_trackingParticleRecoAsssociation
> cutsRecoMuonSeededStepOutInHp_trackingParticleRecoAsssociation
> cutsRecoMuonSeededStepOutIn_trackingParticleRecoAsssociation
> cutsRecoPixelPairStepHp_trackingParticleRecoAsssociation
> cutsRecoPixelPairStep_trackingParticleRecoAsssociation

they are not empty if you are on enough statistics, even just 1k events w/o PU on available relval sample in 11_0_0_pre13, for instance

the added plots, are the one related to the fakes and duplicates which were missing

this plots are particularly important in this phase of validation of the tracker layout and material budget in the high pseudorapidity

@emiglior @mmusich

**Comment by jfernan2** [comment]
@mtosi Nobody is saying these plots are not important but, can you share your validation of the PR where the plots in those folders get some entries beyond more than 10 events per workflow as the cmsbuild does?
Nevertheless, my question still holds: Can we expect some DQM Tracking clean up at some point? 
And the following comment goes beyond the scope of this PR but I take the opportunity so here it goes anyway: We need also some words on how Tracking is performing validation, or if you prefer who and how is looking at 35k (+5k introduced by this PR) plots for Validation? 
The twiki presented at the meeting seems not up to date in this respect: https://twiki.cern.ch/twiki/bin/viewauth/CMS/TrackingValidationMC

**Comment by mmusich** [comment]
Hello, out of curiosity, what is the plan for integration of this PR? 
Is it subject to further discussion on the amount of plots in the tracking workspace?
As for: 
> can you share your validation of the PR where the plots in those folders get some entries beyond more than 10 events per workflow as the cmsbuild does?

@mtosi can you post here the plots you circulated in private thread demonstrating their utility?
As pointed out by Mia, this PR has implications on the Phase2 Tracker layout decisions, though these plots can be run by hand it would be useful to include them in regular release validation.

**Comment by mtosi** [comment]
apologies for the delay
looking at the summary plot w/ the statistics of reconstructed tracks in the different categories (which are the sub-directories) you clearly see that plots should not be empty
image

**Comment by jfernan2** [comment]
@mtosi  sorry but the plot you link is very similar to the one produced by cmsbuild in the PR test for wf23234 (ttbar): https://tinyurl.com/rz5eqaz
image
with indeed two orders of magnitude less events and some population in the *MuonSeeded* collections but still having most of the plots with no entries in the folders from the directories quoted above in previous comments. Or in some cases with a few entries but all lying in under or overflow bins, so I suggest considering a binning check in this new set of 5k plots to make them actually useful.

Nevertheless, I understand this is a matter of muon tracks but there is no RelValZMM sample checked in this test for Phase2.

So. I am signing the PR since I understand this is needed, however with this addition the total Tracking account of MEs in RelVal samples is ~40k. Hence I urge you to reconsider a revision of the Tracking Validation procedure for the next year which, as I said before, was not presented in the DQM Sequence review. Thank you

**Comment by jfernan2** [comment]
+1

**Comment by mtosi** [comment]
@jfernan2 thanks !

**Comment by fabiocos** [comment]
+1

**Pull request merged**
