### PR TITLE
Change code to not stop on SRP block error and proceed with FE -  80X  base

### PR DESCRIPTION
**Pull request by argiro**
data unpacking.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
the same code changes as in  81X version #14712

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/14771	871cd7f
- the same change (the same topic branch and commit id) as #14712
- jenkins tests pass and comparisons show no differences
- tests done in 81X in problematic run should apply here as well (see https://github.com/cms-sw/cmssw/pull/14712#issuecomment-223714084 )

**Comment by davidlange6** [comment]
+1

**Pull request merged**
