### PR TITLE
Drop support for the old alpaka accelerator framework

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Remove support for the initial alpaka-based accelerator framework, that was a straight porting of the CUDA approach.
An improved version of the accelerator framework is already available and used by all the tests in CMSSW 13.0.x and 13.1.x.

#### PR validation:

Unit tests pass.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

To be backported to CMSSW_13_0_x for eventual deployment in data taking.

### CODE REVIEW

**Comment by fwyzard** [comment]
enable gpu

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
OK, looks good on my side.

@makortel, do you see any issues with this ?

**Comment by makortel** [comment]
+heterogneous

Looks good to me too, thanks!

**Comment by perrotta** [comment]
+1

**Pull request merged**
