### PR TITLE
Remove CondCore/PluginSystem package and BuildFile.xml in ReleaseScripts

### PR DESCRIPTION
**Pull request by guitargeek**
#### PR description:

By chance I noticed that the CondCore/PluginSystem package does not contain anything besides a header file which only includes a header file from another package. The current build configuration I use does not like it if there is a `BuildFile.xml` in a package without any sources in `src`:

https://github.com/cms-sw/cmssw/tree/master/CondCore/PluginSystem

I also removed `Utilities/ReleaseScripts/BuildFile.xml` for the same reason. Am I assuming correctly that empty BuildFiles serve no purpose at this point?

#### PR validation:

CMSSW compiles and local matrix tests pass.

#### if this PR is a backport please specify the original PR:

No backport intended.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
@smuzaffar Please review the need for BigProducts/Simulation/BuildFile.xml and Utilities/ReleaseScripts/BuildFile.xml.

**Comment by smuzaffar** [comment]
@guitargeek , please do not remove `BigProducts/Simulation/BuildFile.xml`. This is needed to build big Simulation plugin using sources of packages listed in it.

**Comment by guitargeek** [comment]
Interesting, thanks for the quick answer! I'll put if back quickly of course.

**Comment by tlampen** [comment]
please test

**Comment by slava77** [comment]
this PR affects mostly alca.
Some comments or/and a signature would be nice (so that e.g. the reco signature can later be \~trivially applied)

**Comment by silviodonato** [comment]
> this PR affects mostly alca.
> Some comments or/and a signature would be nice (so that e.g. the reco signature can later be ~trivially applied)
  @christopheralanwest  @franzoni  @tlampen  @pohsun  @tocheng

**Comment by tlampen** [comment]
+1

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/28652	35904a0 
- technical
- jenkins tests pass

**Comment by santocch** [comment]
+1

**Comment by silviodonato** [comment]
Kind reminder to
core:   @Dr15Jones  @smuzaffar  @makortel 
db:   @ggovi 
l1:   @benkrikler  @rekovic

**Comment by makortel** [comment]
@smuzaffar Could you double-check that the changes in `Utilities/ReleaseScripts` are ok?

**Comment by smuzaffar** [comment]
@makortel , yes changes in `Utilities/ReleaseScripts` look good

**Comment by makortel** [comment]
+1

Thanks

**Comment by slava77** [comment]
ping

db: @ggovi
l1: @benkrikler @rekovic

we need your signature here.
Please check.
Thank you.

**Comment by silviodonato** [comment]
It would be great if you can sign this PR by today in order to have it in CMSSW_11_1_0_pre2
db: @ggovi
l1: @benkrikler @rekovic

**Comment by ggovi** [comment]
+1

**Pull request merged**
