### PR TITLE
Factorise PreSplitting configuration from InitialStep

### PR DESCRIPTION
**Pull request by rovere**
Completely factorise PreSplitting from InitialStep configuration, so  that they can be tuned independently. Fix order of python import logic. No regression expected.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cmsbuild please test
Last time the comparisons never completed

**Comment by cvuosalo** [comment]
@cmsbuild please test
Hope the DAS errors are transient

**Comment by cvuosalo** [comment]
+1

For #10580 8c920bc9be17e48110b68d233b119c94f973b554

For Tracking, factorizing PreSplitting configuration from the InitialStep. This code improvement to facilitate tuning should have no effect on monitored quantities.

The code changes are satisfactory, and Jenkins [tests]() against baseline CMSSW_7_6_X_2015-08-07-1100 show no significant differences, as expected. A check of the expanded RECO config of workflow 25202.0 confirms the new pre-splitting is included.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
