### PR TITLE
Hybrid zero suppression fixes

### PR DESCRIPTION
**Pull request by pieterdavid**
This PR collects a few fixes related to the hybrid zero-suppression (and emulation):
- a configuration error: the "Hybrid" inspection method of the APV restorer should be used for hybrid data (this needs to be propagated to the HLT menu for HI; there was also a check to enfoce "BaselineFollower" as inspect method when it was used as restore method, that has been relaxed accordingly).
- hybrid emulation needs the complete pedestals, but the global tag used in the relval to test it did not include these, so changed "auto:run2_data" to "auto:run2_hlt_hi" there
- for the hybrid emulation, the "x->(x+1024)/2" transformation is applied to the `MeanCM` parameter (as it is to the VR digis), to align the interpretation with its online equivalent

@icali @CesarBernardes @erikbutz @mmusich

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test workflow 140.55

**Comment by kpedro88** [comment]
+upgrade

**Comment by slava77** [comment]
@pieterdavid 
please clarify which changes are expected from these fixes.
IIUC, there will be no change in HI MC, but some differences are expected in the data repacked processing like in wf 140.55.
Adding some slides/plots to the PR description would be nice if the changes are significant.

**Comment by CesarBernardes** [comment]
@slava77 
in fact, we expect some changes in data. We expect some differences mainly because of one [commit](https://github.com/cms-sw/cmssw/pull/24597/commits/16656ccc1b8b91666f337e5be22cfabc38723efe) of the three commits in this PR. This is because this new GT uses full pedestals and this is important for the creation of the hybrid format data. In the slides attached we use 2015 PbPb data and we have tested the effect of each commit ([C1](https://github.com/cms-sw/cmssw/pull/24597/commits/16656ccc1b8b91666f337e5be22cfabc38723efe), [C2](https://github.com/cms-sw/cmssw/pull/24597/commits/493255289bbb116eb76e79f985ab3c6b2ee7f6ea), and [C3](https://github.com/cms-sw/cmssw/pull/24597/commits/dd1e28eece2d7444673751ecefa7460be2768a8f)).
[Clusters_Tracks_PR24597_20Sept2018.pdf](https://github.com/cms-sw/cmssw/files/2403605/Clusters_Tracks_PR24597_20Sept2018.pdf)

**Comment by pieterdavid** [comment]
@slava77 after doing more debugging and comparisons, we discovered that the factor two also needs to be applied to the DeltaCMThreshold (with the last commit I put it in the code as well for consistency; the value that is used online in the end is still being discussed). After this, the standard ZS and hybrid emulation + hybrid ZS should be closer than before.
I asked @CesarBernardes to also upload some comparison plots (he has already studied the dependence on the value of this parameter, so probably he has them somewhere).
The clusters will still not be 100% identical, but the two differences in configuration (IteratedMedian versus Median CMN subtractor, and one bit less precision in the hybrid case) are understood, and should be small enough for most practical purposes.

**Comment by davidlange6** [comment]
please test

**Comment by slava77** [comment]
@cmsbuild please test workflow 140.55

**Comment by pieterdavid** [comment]
I'm adding a few more comparison plots between the hybrid scenario (in red; settings as in this PR) and the standard zero-suppression (in black; with CommonModeNoiseSubtractionMode set to "Median" to be as close as possible to the hybrid case). I produced the histograms with [this config](https://github.com/pieterdavid/SiStripLocalRecoDebugging/blob/master/test/check_HybridvsNormalRepack.py) and the plugins in the same package.
Independent tests by @CesarBernardes show the same overall picture: only small changes, and a slightly modified cluster charge distribution (towards smaller average cluster charges).
plotdigistatdiff_ndigis
plotclusterstatdiff_nclus
plotclusterstatdiff_cluswidth
plotclusterstatdiff_cluscharge

**Comment by CesarBernardes** [comment]
Hi All, I also attach some plots for tracking, doing same comparison as Pieter did, i.e., standard ZS vs Hybrid ZS with Median method. I check the tracks with no selection and with a simple selection (High-purity, as defined in 2015 PbPb data-taking and pTerror/pT<0.3). Thanks!
[trackingPlots_StandardZS_vs_Hybrid_24Sept2018.pdf](https://github.com/cms-sw/cmssw/files/2411158/trackingPlots_StandardZS_vs_Hybrid_24Sept2018.pdf)

**Comment by kpedro88** [comment]
+upgrade

**Comment by slava77** [comment]
I'm comparing 200 events using 
1. 140.55 out of the box: in the baseline IB (a), a version with baseline+GT update (b), and IB+this PR (c)
2. "old ZS" version using ```step3  --step RAW2DIGI,REPACK:DigiToRawRepack --conditions auto:run2_hlt_hi --data --era Run2_HI --processName REHLT --scenario HeavyIons --datatier RAW --eventcontent RAW  -n 200  --customise_command "process.load(\"RecoLocalTracker.SiStripZeroSuppression.SiStripZeroSuppression_cfi\")\nprocess.DigiToRawRepack.insert(0, process.siStripZeroSuppression)\n"``` with the same variations in the baseline IB (a), a version with baseline+GT update (b), and IB+this PR (c).
    - @pieterdavid please confirm that this is a correct way of getting the reference to match your plots

- 2(b) is the same as 2(c): this is expected because the code changes are affecting only the hybrid mode. OK.
- 1(c) vs 2(c) are now closer, but we still have more short clusters and \~1.4% fewer tracks
[1(c) is in red and 2(c) is in black]
all_sign1045vsorig-gt-hlthi-oldzs_runhi2015repackvrwf140p55c_log10max0_1 sistripclusteredmnewdetsetvector_sistripclusters__rereco_obj_m_data_amplitudes_at_size
all_sign1045vsorig-gt-hlthi-oldzs_runhi2015repackvrwf140p55c_log10recotracks_higeneraltracks__rereco_obj_pt
all_sign1045vsorig-gt-hlthi-oldzs_runhi2015repackvrwf140p55c_recotracks_higeneraltracks__rereco_obj_eta

IIUC, the last plot is supposed to match the upper middle plot in https://github.com/cms-sw/cmssw/files/2411158/trackingPlots_StandardZS_vs_Hybrid_24Sept2018.pdf
@CesarBernardes your plots are in log scale and it's unclear if what I see appears also in your plots.

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/24597	77d2eda
- code changes are in line with the PR description; changes are expected only in workflow(s) emulating/applying hybrid ZS in siStrips (e.g. wf 140.55, not a part of jenkins tests)
- jenkins tests pass 
- local tests show moderate changes in HI tracking in line with the slides provided with this PR (see https://github.com/cms-sw/cmssw/pull/24597#issuecomment-424072387). This achieves a better agreement between the two zero suppression schemes.

**Comment by zhenhu** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Comment by pieterdavid** [comment]
@slava77 for the reference in my plots I also set `process.siStripZeroSuppression.Algorithms.CommonModeNoiseSubtractionMode = "Median"` (which is the setting for the emulation because that is what the firmware does, so I took the same for the reference to isolate the difference due to the hybrid scheme).
On another point: while investigating the difference in the cluster charge distribution I found another bug. With that fixed the low-level distributions are again nearly identical, I posted the details and comparison plots in the PR with the fix, https://github.com/cms-sw/cmssw/pull/24654 .

**Comment by slava77** [comment]
On 9/25/18 5:09 AM, Pieter David wrote:
> @slava77
> for the reference in my plots I also set
> |process.siStripZeroSuppression.Algorithms.CommonModeNoiseSubtractionMode =
> "Median"| (which is the setting for the emulation because that is what
> the firmware does, so I took the same for the reference to isolate the
> difference due to the hybrid scheme).
> On another point: while investigating the difference in the cluster
> charge distribution I found another bug. With that fixed the low-level
> distributions are again nearly identical, I posted the details and
> comparison plots in the PR with the fix, #24654
> .
> 

OK. I see that the default in the 103X is otherwise
siStripZeroSuppression.Algorithms.CommonModeNoiseSubtractionMode =
'IteratedMedian'

I was looking at /cdaq/physics/Run2015HI/HeavyIon/500Bunches/v9.0/HLT/V1
the table used for run 263400 in wf 140.55.
there in the HLTHIDoStripZeroSuppression sequence we also have
hltSiStripZeroSuppression.Algorithms.CommonModeNoiseSubtractionMode =
'IteratedMedian'

So far, I was considering this as the "old ZS".

Similarly, for 304906 in
/cdaq/physics/Run2017XeXe/HeavyIon/v1.2/HLT/V3
the same IteratedMedian is used.


What is the reason for using Median?

**Pull request merged**
