### PR TITLE
[12_4_X] Update L1T menu tag in MC and relval GTs

### PR DESCRIPTION
**Pull request by francescobrivio**
#### PR description:
Backport of #38438 
This PR updates the L1T menu tag for the 12_4_X MC prouduction campaign, as requested in [this CMSTalk post](https://cms-talk.web.cern.ch/t/run-3-gt-update-of-the-l1-menu-tag-v1-2-0-in-run-3-mc-gts-and-run-3-data-relvals-gts/11830) for Run3 MC GTs and the Run3 relval GTs used for TSG tests.
The new L1T tag is `L1Menu_Collisions2022_v1_2_0_xml`.

*Note:* The GTs `run3_data_relval` and `run3_data` also contain the `SiPixelAliThresholdsHG_offline_v0` tag that was introduced in #38273, but never propagated to `autoCond`.

*Note2:* Both `run3_hlt` and `run3_data` GTs have been updated to have the same snapshot time of `run3_hlt_relval` and `run3_data_relval`, as suggested in https://github.com/cms-sw/cmssw/pull/38438#issuecomment-1160443211.

See master PR for GT diffs.

#### PR validation:
Tested with:
`runTheMatrix.py -l 7.23,159.0,11634.0,12034.0,12434.0,12834.0 --ibeos -j16`

#### Backport:
Backport of #38438

### CODE REVIEW

**Comment by francescobrivio** [comment]
backport of #38438

**Comment by francescobrivio** [comment]
test parameters:

 - workflows = 7.23,159.0,11634.0,12034.0,12434.0,12834.0

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
type l1t

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by francescobrivio** [comment]
@cmsbuild please test

 - last commit is now ok

**Comment by tvami** [comment]
+alca
 * no diffs are seen
 * master PR merged yesterday

**Comment by francescobrivio** [comment]
urgent

 - we have more GT updates coming very soon (possibly also today)

**Comment by tvami** [comment]
hi @perrotta @qliphy we agreed at ORP that this should go in for the next IB, can we merge it before 2300?

**Comment by perrotta** [comment]
+1

**Pull request merged**
