### PR TITLE
[10.0.X] Fix arrow plots in geometry comparison tool

### PR DESCRIPTION
**Pull request by ghellwig**
Main focus is on resurrecting arrow plots.
Few minor fixes/changes:
 - remove remaining usage of 'eos' command
 - change default to produce only global plots which contain already all information
   - saves disk space
 - allow special characters in alignment names

### CODE REVIEW

**Comment by ghellwig** [comment]
type bugfix

**Comment by ghellwig** [comment]
please test

**Comment by ghellwig** [comment]
@lpernie @arunhep could you please have a look?
This PR is rather trivial and mainly fixes a bug and moves a macro from the `scripts` to the `macros` folder where it actually belongs.

**Comment by arunhep** [comment]
+1

**Comment by ghellwig** [comment]
@arunhep thanks!

**Comment by davidlange6** [comment]
+1

**Pull request merged**
