### PR TITLE
Run3-alca156 Add studies relevant for tuning tracker cuts to go to forward regions

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Tune selection of good tracks in view of forward tracks using mostly the new pixel detector

#### PR validation:

Tested using private code and during calibration of Run3 MC sample

#### if this PR is a backport please specify the original PR:

No back porting is needed

### CODE REVIEW

**Comment by christopheralanwest** [comment]
please test

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
@tocheng @christopheralanwest @pohsun could you please have a look?

**Comment by christopheralanwest** [comment]
The error in workflow 140.53 is not related to this PR; there is a spurious string "grep: " in the filename, clearly caused by some buggy script:
```
Cannot open file 'grep: /store/hidata/HIRun2011/HIMinBiasUPC/RAW/v1/000/182/124/0011F55A-8F13-E111-A987-003048F118C6.root'
```
Is this under investigation elsewhere?

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by pohsun** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
