### PR TITLE
BugFix for TwinMux unpacker - change of logic involved

### PR DESCRIPTION
**Pull request by jpazzini**
- check beginning/end of AMC stream using HEX of header/trailer -> moved to 4 bit [was 6 for header, 8 for trailer]

```
-  int BOEevTy  = ( dataWord >> 56 ) & 0xFf;  // positions 60 -> 63
+  int BOEevTy  = ( dataWord >> 60 ) & 0xF;  // positions 60 -> 63
```

```
-  if ( (BOEevTy != 0x51) || ( TM7fedId != twinMuxFed ) ) {
+  if ( (BOEevTy != 0x5) || ( TM7fedId != twinMuxFed ) ) {
```

```
+  int chkEOE = (dataWord >> 60 ) & 0xF;  // positions 60 -> 63
+  if ( chkEOE != 0xA ) {
+      edm::LogWarning("TwinMux_unpacker") << "AMC block closing line " << std::hex << dataWord 
+                                          << std::dec << " does not start with 0xA";
+      return;
+  }
```
- range of AMC blocks to be read -> changed to 1-12 [was 0-11]

```
-    if ( AMCno < 12 ) {
-      AMCsizes[AMCno] = ( dataWord >> 32 ) & 0xFFFFFF;  // positions 32 -> 55
+    if ( (AMCno < 1) || (AMCno > 12) ) {
+        edm::LogWarning("TwinMux_unpacker") << "AMCnumber " << std::dec << AMCno 
+                                            << " out of range (1-12)";
+        return;
+    }    
```
- TM payload -> payload stored according to the expected size from the headers [was until the stream start with the trailer HEX (0xA) ]

```
-  while ( chkEOE != 0xA0 ) { 
[...] (store TM payloads)
-}
```

```
+  ///--> Store payloads
+  std::map<int,int>::iterator AMCiterator = AMCsizes.begin();
+  std::map<int,int>::iterator AMCitend = AMCsizes.end();  
+  for ( ; AMCiterator != AMCitend; ++AMCiterator ) {
+      
+    for ( int k=0; k<AMCiterator->second; ++k) {
+        
+       readline( nline, dataWord );
+       calcCRC( dataWord, newCRC);
+       DTTM7WordContainer.push_back( dataWord );
+     }
+  }  
```

### CODE REVIEW

**Comment by mulhearn** [comment]
please test

**Comment by mulhearn** [comment]
+1

**Comment by mulhearn** [comment]
@jpazzini:  please add a summary to help this sail through.

**Comment by mulhearn** [comment]
This will be needed during MWGR in order to unpack correctly the TwinMux for DQM.

**Comment by jpazzini** [comment]
@mulhearn - added some details about the commit in the first comment

**Pull request merged**
