### PR TITLE
Remove dead assignments and clean up a bit GenFilters

### PR DESCRIPTION
**Pull request by perrotta**
#### PR description:

Remove dead assignments pointed out by the SA
Further sparse cleaning of the two touched files.

#### PR validation:

It builds
No changes expected whatsoever

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
@cms-sw/generators-l2 relval inputs timed out is not an issue that should need waste resouces by retriggering the tests: please evaluate this PR as if the tests were passed

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
@cms-sw/generators-l2 is there anything that prevents you reviewing this PR? Could you please comment in any case, telling what you are waiting for, or when do you plan to review?

**Comment by menglu21** [comment]
+1

**Comment by menglu21** [comment]
> @cms-sw/generators-l2 is there anything that prevents you reviewing this PR? Could you please comment in any case, telling what you are waiting for, or when do you plan to review?

sorry, i missed this pr

**Comment by perrotta** [comment]
+1
- Tests are three weeks old, but still available. And the affected files were not touched in CMSSW since then.

**Pull request merged**
