### PR TITLE
Restored the ShieldingME4 and fixed all the MUON overlaps in muonYoke.xml

### PR DESCRIPTION
**Pull request by slomeo**
**PR description:**

Restored the ShieldingME4 and fixed all the MUON overlaps in muonYoke.xml
A new version of muonYoke.xml is created (i.e 2026/v2/muonYoke.xml)  

@bsunanda @ianna @cvuosalo @civanch  @etcherniaev : FYI 

**PR validation:**

1) validation by "cmsShow.exe -c overlaps.fwc --sim-geom-file cmsSimGeom-2026.root"

2) validation by "nohup cmsRun SimG4Core/PrintGeomInfo/test/python/g4OverlapCheck2026_cfg.py >& overlaps.out &" 
Muon's volumes are not present in the overlaps.out file.
 

**if this PR is a backport please specify the original PR and why you need to backport that PR:**

nothing special

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by srimanob** [comment]
Thanks very much @slomeo 

By the way, why do you touch only
`Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2026D86.xml
`
but not the definition of M10 (of D86)?
https://github.com/cms-sw/cmssw/blob/master/Configuration/Geometry/python/dict2026Geometry.py#L1280

**Comment by slomeo** [comment]
Hi @srimanob

> but not the definition of M10 (of D86)? https://github.com/cms-sw/cmssw/blob/master/Configuration/Geometry/python/dict2026Geometry.py#L1280

because if I understood well, I think that @bsunanda wants to do this job.

@bsunanda , please let me know

**Comment by bsunanda** [comment]
Please do not change Configuration/Geometry/python/dict,, and also please restore the old cmsExtendedGeometry2026D26XML_cfi.py. I am preparing the next version of scenario.

**Comment by srimanob** [comment]
OK, then I think we should do it in a cleaner way. For example,
- This PR adds only XML, and we touch all D86 XMLs in a separate PR.
- Or this PR includes all changes needed for D86

**Comment by srimanob** [comment]
Our comments cross @bsunanda 
It seems we agree that this PR adds XML. 
@slomeo Would you mind updating also the PR title and description to reflect the change. Thanks again.

**Comment by slomeo** [comment]
do I have to make a new "commit" without msExtendedGeometry2026D86.xml? I'm sorry but I don't understand because I never edited cmsExtendedGeometry2026D86XML_cfi.py as @bsunanda wrote.

**Comment by srimanob** [comment]
You can change back this file,
`Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2026D86.xml `
and commit & push again. The PR test will stop when you push the new one.
Then change the title and description of the PR.

**Comment by slomeo** [comment]
ok

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by slomeo** [comment]
@srimanob @bsunanda cmsExtendedGeometry2026D86.xml restored and PR title changed

**Comment by civanch** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
