### PR TITLE
Update NanoAOD for MiniAOD v2 - part 3 (94X main branch version)

### PR DESCRIPTION
**Pull request by arizzi**
- Use updated jecs for lepton-jets variables
- update tau mva ids
- minor fix in ttH lepton MVA 

same as #22840 

@fabiocos  This PR on the AN branch is mostly to test it without pulling in the whole #22828

We could close this and go directly to CMSSW_9_4_X once #22828 is merged but only if @slava77  @perrotta  are ok with it (there is a reco signature needed), otherwise we go via AN release (perhaps made as a patch on to of 945 given that differences are minimal)

### CODE REVIEW

**Comment by arizzi** [comment]
please test

**Comment by arizzi** [comment]
+1

**Comment by arizzi** [comment]
please test

**Comment by arizzi** [comment]
+1

**Comment by arizzi** [comment]
@fabiocos as agreed with @slava77 it is ok for reco to go to 94X main branch. I changed base on github

**Comment by arizzi** [comment]
please test

**Comment by arizzi** [comment]
is the failure due to cern  instabilities? I don not understand where it is failing

**Comment by slava77** [comment]
in addOnTests/hlt_data_PRef
> Module: HLTDisplacedtktkVtxProducer:hltTktkVtxForDmesonDpt20 (crashed)

**Comment by arizzi** [comment]
I couldn't find the error but I do not see how can it be related to the
commit I added.

Il gio 5 apr 2018, 22:32 Slava Krutelyov <notifications@github.com> ha
scritto:

**Comment by slava77** [comment]
@arizzi 
I do not see any changes in 1325.7 DQM plots (there are quite a few in the comparisons of the master version #22841). Is this expected?

**Comment by slava77** [comment]
>  I do not see any changes in 1325.7 DQM plots (there are quite a few in the comparisons of the master version #22841). Is this expected?

answer to self: it is expected. The 94X workflow setup does not include nanoAOD
- in 94X: ```  -s NANO --datatier NANOAODSIM,DQMIO```
- in 102X: ```-s NANO,DQM:@nanoAODDQM --datatier NANOAODSIM,DQMIO```

**Comment by slava77** [comment]
.. actually, step2_inDQM.root is still produced in 94X with about the same size as in 102X.
Is the monitoring code lagging behind in the 94X version?

**Comment by slava77** [comment]
... except that DQM_V0001_R000000001__Global__CMSSW_X_Y_Z__RECO.root is apparently empty in 94X.

OK. So, this is a feature of nanoAOD workflow in 94X, not related to this PR.

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/22841	98974b0
- the same changes as in the master; reco is only tangentially affected via RecoTauTag/Configuration/python/loadRecoTauTagMVAsFromPrepDB_cfi.py which now holds additional setup for the calibration payloads used in the nanoAOD
- jenkins tests pass and comparisons with the baseline show no differences 
    - it appears that the nanoAOD workflow setup does not include any DQM plots in this release. So, the only place where changes are expected is not monitored.

**Comment by slava77** [comment]
backport of #22840

**Comment by fabiocos** [comment]
please test workflow 1325.6,1325.7,1325.8,1325.9

**Comment by fabiocos** [comment]
+1

**Pull request merged**
