### PR TITLE
Take frozen HLT menu from /frozen ConfDB location (93X)

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
Take frozen HLT menu from /frozen ConfDB location (93X)
Based on CMSSW_9_3_X_2017-08-02-2300

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please abort

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
