### PR TITLE
Fix boosting software in 80X for HI MC

### PR DESCRIPTION
**Pull request by kurtejung**
Repeat of PR #15548 for 80X

### CODE REVIEW

**Comment by kurtejung** [comment]
Also tagging @mandrenguyen @dgulhan @yetkinyilmaz

**Comment by perrozzi** [comment]
please test

**Comment by perrozzi** [comment]
+1

**Comment by dgulhan** [comment]
@davidlange6 The corresponding PR was merged in 81X:
https://github.com/cms-sw/cmssw/pull/15548
Is there a reason why this is not? I wanted to send a reminder message in case this got forgotten. Thanks.

**Comment by kurtejung** [comment]
Hello - just pinging this thread again to resolve the hold-up in merging this PR

**Comment by mandrenguyen** [comment]
@davidlange6  Is there a reason this didn't go in 8_0_20?   This PR is fully signed and the 81X version went in forever ago.  Can you merge it please?

**Comment by davidlange6** [comment]
+1

**Pull request merged**
