### PR TITLE
move TreeWriterForEcalCorrection in to a plugin directory

### PR DESCRIPTION
**Pull request by smuzaffar**
#### PR description:

Currectly TreeWriterForEcalCorrection edmplugin is defined in src directory  which means it becomes part of the FastSimulationCalorimetry shared library. Any plugin which depneds on `FastSimulation/Calorimetry` then register `TreeWriterForEcalCorrection` which can result in duplicate plugin definition e.g.

https://cmssdt.cern.ch/SDT/cgi-bin/showDupDict.py//slc7_amd64_gcc700/www/sat/11.0-sat-11/CMSSW_11_0_X_2019-08-31-1100/testLogs/dupDict-edmPD.log

- TreeWriterForEcalCorrection:
  - pluginFastSimulationEventProducer.so
  - pluginFastSimulationSimplifiedGeometryPropagatorAuto.so

#### PR validation:

Loval build show no error.

### CODE REVIEW

**Comment by ssekmen** [comment]
please test

**Comment by fabiocos** [comment]
@ssekmen @sbein could you please have a look? It is a simple technical fix

**Comment by ssekmen** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
@smuzaffar I am confused, after the integration of this PR and of #27915 we now do see a duplictae definition reported in the CMSSW_11_0_X_2019-09-03-2300 IB tests

**Comment by fabiocos** [comment]
may be because this was just a patch and old stuff was not properly cleaned? The problem does not appear for Full builds

**Comment by smuzaffar** [comment]
todat's 11h IB should fix this as we need to have a full IB to avoid this duplications.

**Pull request merged**
