### PR TITLE
Adding L1REPACK:FullMC workflow to run on RAW of MC.

### PR DESCRIPTION
**Pull request by rekovic**
Adding L1REPACK:FullMC workflow to run on RAW of MC. 
(Also fixed Csc InputTag for Omtf emuator in REPACK:Full, and clean REPACK:uGT.

Available L1REPACK workflows of re-emulation of Stage2 L1T available now: 
- FullMC (for 2016 RAWAODSIM MC)
- Full  (for 2016 data)
- uGT (for 2016 data) 
- Full2015Data (for 2015Data)

L1REPACK:FullMC workflow starts from unpacking RPC, DT, CSC, ECAL, and HCAL. 
It uses unpacked TriggerPrimitives for ECAL and simulates TriggerPrimitives DT TPs, CSC TPs, and HCAL TPs. It then emulates TwinMux, muon track finders (BMTF, OMTF, EMTF) uGMT, Calo Layer1, Calo Layer2, and uGT at the end of the sequence. 
It re-packs re-emulated uGMT, CaloLayer2 and uGT in RAW data collection. 

In a MC-production-like workflow, use it as:

<pre>
cmsDriver.py reHLT --conditions auto:run2_mc -s L1REPACK:FullMC,HLT:@fake --datatier GEN-SIM-RAW,AODSIM -n 10 --era=Run2_2016 --eventcontent RAWSIM,AODSIM --filein "root://eoscms.cern.ch//eos/cms/store/mc/RunIISpring16DR80/TTJets_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8/RAWAODSIM/PUSpring16RAWAODSIM_80X_mcRun2_asymptotic_2016_v3-v2/30000/040AFBF1-8E0B-E611-9C22-001E67E95A58.root" --processName HLT2 --python_filename reHLT.py 
</pre>

Add a flag to see printouts of L1 menu `--customise=HLTrigger/Configuration/CustomConfigs.L1T`

L1REPACK:Full workflow starts from unpacked TriggerPrimitives and re-emulates muon track finders, uGMT, Calo Layer1 and Layer2, and uGT at the end of the sequence. It re-packs re-emulated uGMT, CaloLayer2 and uGT in RAW data collection.  In a typical HLT test use it as:

<pre>
cmsDriver.py RelVal --step=L1REPACK:Full --conditions=auto:run2_hlt_GRun --filein=/store/data/Run2016A/ZeroBias1/RAW/v1/000/271/336/00000/00963A5A-BF0A-E611-A657-02163E0141FB.root --custom_conditions= --fileout=RelVal_L1RePack_GRun_DATA.root --number=10 --data --datatier GEN-SIM-DIGI-RAW --eventcontent=RAW --customise=HLTrigger/Configuration/CustomConfigs.L1T --era=Run2_2016 --customise= --scenario=pp --python_filename=RelVal_L1RePack_Full_GRun_DATA.py --customise=L1Trigger/Configuration/L1Trigger_custom.customiseResetPrescalesAndMasks 
</pre>

L1REPACK:uGT workflow starts from unpacked uGMT and CaloLayer2 outputs, re-emulates uGT, and packs the re-emulated uGT in RAW data collection.  In a typcal HLT test us it as:

<pre>
cmsDriver.py RelVal --step=L1REPACK:uGT --conditions=auto:run2_hlt_GRun --filein=/store/data/Run2016A/ZeroBias1/RAW/v1/000/271/336/00000/00963A5A-BF0A-E611-A657-02163E0141FB.root --custom_conditions= --fileout=RelVal_L1RePack_GRun_DATA.root --number=10 --data --datatier GEN-SIM-DIGI-RAW --eventcontent=RAW --customise=HLTrigger/Configuration/CustomConfigs.L1T --era=Run2_2016 --customise= --scenario=pp --python_filename=RelVal_L1RePack_uGT_GRun_DATA.py --customise=L1Trigger/Configuration/L1Trigger_custom.customiseResetPrescalesAndMasks 
</pre>

For L1REPACK:Full2015Data workflow is intended for 205 data, starts from unpacked TriggerPrimitives and re-emulates muon track finders, uGMT, Calo Layer1 and Layer2, and uGT at the end of the sequence. It re-packs re-emulated uGMT, CaloLayer2 and uGT in RAW data collection.  
Configuration for the HFTPs (1x1) which is different in 2016 wrt 2015 has already been included in the above workflow via setting ESProducer preference.  However, the geometry for 2016 needs to be loaded via a cmsDriver flag _--geometry_ flag.
For a typical HLT test use it as:

<pre>
cmsDriver.py RelVal --step=L1REPACK:Full2015Data --conditions=auto:run2_hlt_GRun --filein=/store/data/Run2015D/MuonEG/RAW/v1/000/256/677/00000/80950A90-745D-E511-92FD-02163E011C5D.root --custom_conditions= --fileout=RelVal_L1RePack_GRun_DATA.root --number=10 --data --datatier GEN-SIM-DIGI-RAW --eventcontent=RAW --customise=HLTrigger/Configuration/CustomConfigs.L1T --era=Run2_2016 --customise= --scenario=pp --python_filename=RelVal_L1RePackFull2015Data_GRun_DATA.py --customise=L1Trigger/Configuration/L1Trigger_custom.customiseResetPrescalesAndMasks --geometry=Extended2016,Extended2016Reco
</pre>

### CODE REVIEW

**Comment by davidlange6** [comment]
Hi

We need to continue with the db geometry. What is missing?


On 25 May 2016, at 16:40, rekovic <notifications@github.com<mailto:notifications@github.com>> wrote:


Adding L1REPACK:FullMC workflow to run on RAW of MC.
(Also fixed Csc InputTag for Omtf emuator in REPACK:Full, and clean REPACK:uGT.

Available L1REPACK workflows of re-emulation of Stage2 L1T available now:

  *   FullMC (for 2016 RAWAODSIM MC)
  *   Full (for 2016 data)
  *   uGT (for 2016 data)
  *   Full2015Data (for 2015Data)

L1REPACK:FullMC workflow starts from unpacking RPC, DT, CSC, ECAL, and HCAL.
It uses unpacked TriggerPrimitives for ECAL and simulates TriggerPrimitives DT TPs, CSC TPs, and HCAL TPs. It then emulates TwinMux, muon track finders (BMTF, OMTF, EMTF) uGMT, Calo Layer1, Calo Layer2, and uGT at the end of the sequence.
It re-packs re-emulated uGMT, CaloLayer2 and uGT in RAW data collection.

In a MC-production-like workflow, use it as:

cmsDriver.py reHLT --conditions auto:run2_mc -s L1REPACK:FullMC,HLT:@fake --datatier GEN-SIM-RAW,AODSIM -n 10 --era=Run2_2016 --eventcontent RAWSIM,AODSIM --filein "root://eoscms.cern.ch//eos/cms/store/mc/RunIISpring16DR80/TTJets_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8/RAWAODSIM/PUSpring16RAWAODSIM_80X_mcRun2_asymptotic_2016_v3-v2/30000/040AFBF1-8E0B-E611-9C22-001E67E95A58.root" --processName HLT2 --python_filename reHLT.py


Add a flag to see printouts of L1 menu --customise=HLTrigger/Configuration/CustomConfigs.L1T

L1REPACK:Full workflow starts from unpacked TriggerPrimitives and re-emulates muon track finders, uGMT, Calo Layer1 and Layer2, and uGT at the end of the sequence. It re-packs re-emulated uGMT, CaloLayer2 and uGT in RAW data collection. In a typical HLT test use it as:

cmsDriver.py RelVal --step=L1REPACK:Full --conditions=auto:run2_hlt_GRun --filein=/store/data/Run2016A/ZeroBias1/RAW/v1/000/271/336/00000/00963A5A-BF0A-E611-A657-02163E0141FB.root --custom_conditions= --fileout=RelVal_L1RePack_GRun_DATA.root --number=10 --data --datatier GEN-SIM-DIGI-RAW --eventcontent=RAW --customise=HLTrigger/Configuration/CustomConfigs.L1T --era=Run2_2016 --customise= --scenario=pp --python_filename=RelVal_L1RePack_Full_GRun_DATA.py --customise=L1Trigger/Configuration/L1Trigger_custom.customiseResetPrescalesAndMasks


L1REPACK:uGT workflow starts from unpacked uGMT and CaloLayer2 outputs, re-emulates uGT, and packs the re-emulated uGT in RAW data collection. In a typcal HLT test us it as:

cmsDriver.py RelVal --step=L1REPACK:uGT --conditions=auto:run2_hlt_GRun --filein=/store/data/Run2016A/ZeroBias1/RAW/v1/000/271/336/00000/00963A5A-BF0A-E611-A657-02163E0141FB.root --custom_conditions= --fileout=RelVal_L1RePack_GRun_DATA.root --number=10 --data --datatier GEN-SIM-DIGI-RAW --eventcontent=RAW --customise=HLTrigger/Configuration/CustomConfigs.L1T --era=Run2_2016 --customise= --scenario=pp --python_filename=RelVal_L1RePack_uGT_GRun_DATA.py --customise=L1Trigger/Configuration/L1Trigger_custom.customiseResetPrescalesAndMasks


For L1REPACK:Full2015Data workflow is intended for 205 data, starts from unpacked TriggerPrimitives and re-emulates muon track finders, uGMT, Calo Layer1 and Layer2, and uGT at the end of the sequence. It re-packs re-emulated uGMT, CaloLayer2 and uGT in RAW data collection.

Configuration for the HFTPs (1x1) which is different in 2016 wrt 2015 has already been included in the above workflow via setting ESProducer preference. However, the geometry for 2016 needs to be loaded via a cmsDriver flag --geometry flag.
For a typical HLT test use it as:

cmsDriver.py RelVal --step=L1REPACK:Full2015Data --conditions=auto:run2_hlt_GRun --filein=/store/data/Run2015D/MuonEG/RAW/v1/000/256/677/00000/80950A90-745D-E511-92FD-02163E011C5D.root --custom_conditions= --fileout=RelVal_L1RePack_GRun_DATA.root --number=10 --data --datatier GEN-SIM-DIGI-RAW --eventcontent=RAW --customise=HLTrigger/Configuration/CustomConfigs.L1T --era=Run2_2016 --customise= --scenario=pp --python_filename=RelVal_L1RePackFull2015Data_GRun_DATA.py --customise=L1Trigger/Configuration/L1Trigger_custom.customiseResetPrescalesAndMasks --geometry=Extended2016,Extended2016Reco


________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/cms-sw/cmssw/pull/14635

Commit Summary

  *   Adding L1REPACK FullMC to run on RAW of MC. Fix Csc tag for Omtf emulator in REPACK:Full, and clean REPACK:uGT

File Changes

  *   M Configuration/Applications/python/ConfigBuilder.py<https://github.com/cms-sw/cmssw/pull/14635/files#diff-0> (2)
  *   A Configuration/StandardSequences/python/SimL1EmulatorRepack_FullMC_cff.py<https://github.com/cms-sw/cmssw/pull/14635/files#diff-1> (109)
  *   M Configuration/StandardSequences/python/SimL1EmulatorRepack_Full_cff.py<https://github.com/cms-sw/cmssw/pull/14635/files#diff-2> (2)
  *   M Configuration/StandardSequences/python/SimL1EmulatorRepack_uGT_cff.py<https://github.com/cms-sw/cmssw/pull/14635/files#diff-3> (8)

Patch Links:

  *   https://github.com/cms-sw/cmssw/pull/14635.patch
  *   https://github.com/cms-sw/cmssw/pull/14635.diff

**Comment by Martin-Grunewald** [comment]
Hmm, why is MC different from data for 2016?
The underlying part/difference should be fixed, rather than inflating the number of REPACK scenarios!

**Comment by rekovic** [comment]
@Martin-Grunewald  In workflow "FullMC" we are re-emulating TPs and then the L1T.
In workflow "Full", intended to be equivalent to ReEmul workflows used at L1T to check data/emul agreement, TPs are not re-emulated but unpacked from TrackFinders due to some disagreements unpacked/sim TPs.  Progress has been made and we are getting close to the point where emulating L1T from either unpacked or sim TPs gives consistent results.

**Comment by rekovic** [comment]
@davidlange6  We need to make sure that the geometry used for HCAL TPs, loaded by --geometry=Extended2016,Extended2016Reco, is used.

**Comment by davidlange6** [comment]
it should already be there in the GT for MC. Is it not?

**Comment by mulhearn** [comment]
please test

**Comment by mulhearn** [comment]
Explicitly confirmed that our customizations `--geometry=Extended2016,Extended2016Reco --customise=L1Trigger/Configuration/customiseReEmul.L1TEventSetupForHF1x1TPs` is no longer needed (has no effect) for MC and re-emulation of 2016 data.  It is still needed for re-emulation of 2015 data, where the data tags is not consistent with 2016 re-emulation.

**Pull request merged**
