### PR TITLE
[13_2_X] Add use of unsubtracted jets in RecoBTag info producers

### PR DESCRIPTION
**Pull request by stahlleiton**
#### PR description:

backport of https://github.com/cms-sw/cmssw/pull/44422

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

@mandrenguyen

### CODE REVIEW

**Comment by mandrenguyen** [comment]
@stahlleiton  Was there a 13_3_X PR too?

**Comment by stahlleiton** [comment]
No, I only made one for 140 and 132. Should I make one for 133?

**Comment by stahlleiton** [comment]
> @stahlleiton Was there a 13_3_X PR too?

https://github.com/cms-sw/cmssw/pull/44579

**Comment by mandrenguyen** [comment]
type btv

**Comment by antoniovilela** [comment]
Need to apply fix from https://github.com/cms-sw/cmssw/pull/44591.

**Comment by mmusich** [comment]
@stahlleiton it is possible to avoid the "merge" in the commit history of this PR?

**Comment by mandrenguyen** [comment]
backport of https://github.com/cms-sw/cmssw/pull/44422

**Comment by stahlleiton** [comment]
> @stahlleiton it is possible to avoid the "merge" in the commit history of this PR?

The release I was working on was deleted. So I had to start with a new IB release. I can try to squash the commits if you prefer.

**Comment by mmusich** [comment]
>  I can try to squash the commits if you prefer.

yes, rebasing against the latest 13.2.X IB (thus removing the merge) is the preferred option.

**Comment by stahlleiton** [comment]
> > I can try to squash the commits if you prefer.
> 
> yes, rebasing against the latest 13.2.X IB (thus removing the merge) is the preferred option.

done, I rebased against latest IB

**Comment by mmusich** [comment]
+hlt
   * in this cycle the new parameter `unsubjet_map` of `DeepBoostedJetTagInfoProducer` has never been defined as `untracked`.

**Comment by mandrenguyen** [comment]
+1

**Comment by rappoccio** [comment]
+1

**Pull request merged**
