### PR TITLE
[BeamSpot]: update script to condDB v2 commands

### PR DESCRIPTION
**Pull request by rmanzoni**
backward porting of https://github.com/cms-sw/cmssw/pull/15844

### CODE REVIEW

**Comment by slava77** [comment]
if this is needed in 80X very soon online, another PR is needed for the patch release.
@davidlange6  should we have CMSSW_8_0_19_patchesX branch available? (I only see 0_18)

**Comment by slava77** [comment]
backport of #15844

to get the cms-bot add a "backport" label

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by rmanzoni** [comment]
@slava77 no it's not critical, it's simply right and just to have, but no rush needed

**Comment by mmusich** [comment]
+1

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/15845 3e887ab
- backport of #15844, as intended. Reco is minimally affected (the modified script is not a part of reco workflows)
- jenkins tests failed due to broken IB; the modified script is not a part of the workflows tested in jenkins. 81X tests pass.

**Comment by ghellwig** [comment]
please test

**Comment by davidlange6** [comment]
+1

**Pull request merged**
