### PR TITLE
Adding e/gamma regression from Ecal Multifit in Run1/Run2 GTs (74X)

### PR DESCRIPTION
**Pull request by mmusich**
# Summary of changes
## Run1 simulation
- Ideal: [74X_mcRun1_design_v1](https://cms-conddb.cern.ch/browser/#list/Prod/gts/74X_mcRun1_design_v1) : As [DESRUN1_74_V7](https://cms-conddb.cern.ch/browser/#list/Prod/gts/DESRUN1_74_V7) with the following [changes](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/74X_mcRun1_design_v1/DESRUN1_74_V7):
  - New Egamma regressions based on ECAL multifit reconstruction.
- Realistic: [74X_mcRun1_realistic_v1](https://cms-conddb.cern.ch/browser/#list/Prod/gts/74X_mcRun1_realistic_v1): As [MCRUN1_74_V7](https://cms-conddb.cern.ch/browser/#list/Prod/gts/MCRUN1_74_V7) with the following [changes](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/74X_mcRun1_realistic_v4/MCRUN1_74_V7):
  - New Egamma regressions based on ECAL multifit reconstruction.
- Heavy Ion: [74X_mcRun1_HeavyIon_v1](https://cms-conddb.cern.ch/browser/#list/Prod/gts/74X_mcRun1_HeavyIon_v1): As [MCHI1_74_V7](https://cms-conddb.cern.ch/browser/#list/Prod/gts/MCHI1_74_V7) with the following [changes](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/74X_mcRun1_HeavyIon_v1/MCHI1_74_V7):
  - New Egamma regressions based on ECAL multifit reconstruction.
- Proton Lead: [74X_mcRun1_pA_v1](https://cms-conddb.cern.ch/browser/#list/Prod/gts/74X_mcRun1_pA_v1): As [MCPA1_74_V7](https://cms-conddb.cern.ch/browser/#list/Prod/gts/MCPA1_74_V7) with the following [changes](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/74X_mcRun1_pA_v1/MCPA1_74_V7):
  - New Egamma regressions based on ECAL multifit reconstruction.
## Run1 data
- Offline: [74X_dataRun1_v1](https://cms-conddb.cern.ch/browser/#list/Prod/gts/74X_dataRun1_v1): As [GR_R_74_V14A](https://cms-conddb.cern.ch/browser/#list/Prod/gts/GR_R_74_V14A) with the following [changes](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/74X_dataRun1_v1/GR_R_74_V14A):
  - New Egamma regressions based on ECAL multifit reconstruction;
  - removing RelVal customized tags for L1; 
  - taxonomy change of `SiPixelGenErrorDBObjectRcd` tag.
- HLT: [74X_dataRun1_HLT_frozen_v1](https://cms-conddb.cern.ch/browser/#list/Prod/gts/74X_dataRun1_HLT_frozen_v1): As [GR_H_V57A](https://cms-conddb.cern.ch/browser/#list/Prod/gts/GR_H_V57A) with the following [changes](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/74X_dataRun1_HLT_frozen_v1/GR_H_V57A):
  - Removing customized tags for L1;
  - a snapshot time: 2015-08-20 12:10:16,000000.
## Run2 simulation
- Ideal: [74X_mcRun2_design_v1](https://cms-conddb.cern.ch/browser/#list/Prod/gts/74X_mcRun2_design_v1): As [DESRUN2_74_V5](https://cms-conddb.cern.ch/browser/#list/Prod/gts/DESRUN2_74_V5) with the following [changes](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/74X_mcRun2_design_v1/DESRUN2_74_V5):
  - New Egamma regressions based on ECAL multifit reconstruction;
  - fixing the `PFCalibration` version from v0 to v2.
- Startup: [74X_mcRun2_startup_v1](https://cms-conddb.cern.ch/browser/#list/Prod/gts/74X_mcRun2_startup_v1): As [MCRUN2_74_V10](https://cms-conddb.cern.ch/browser/#list/Prod/gts/MCRUN2_74_V10) with the following [changes](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/74X_mcRun2_startup_v1/MCRUN2_74_V10):
  - New Egamma regressions based on ECAL multifit reconstruction.
- Asymptotic: [74X_mcRun2_asymptotic_v1](https://cms-conddb.cern.ch/browser/#list/Prod/gts/74X_mcRun2_asymptotic_v1): As [MCRUN2_74_V11](https://cms-conddb.cern.ch/browser/#list/Prod/gts/MCRUN2_74_V11) with the following [changes](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/74X_mcRun2_asymptotic_v1/MCRUN2_74_V11):
  - New Egamma regressions based on ECAL multifit reconstruction.
- Heavy Ion: [74X_mcRun2_HeavyIon_v1](https://cms-conddb.cern.ch/browser/#list/Prod/gts/74X_mcRun2_HeavyIon_v1): As [MCHI2_74_V6](https://cms-conddb.cern.ch/browser/#list/Prod/gts/MCHI2_74_V6) with the following [changes](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/74X_mcRun2_HeavyIon_v1/MCHI2_74_V6):
  - New Egamma regressions based on ECAL multifit reconstruction.
## Run2 data
- Offline: [74X_dataRun2_v1](https://cms-conddb.cern.ch/browser/#list/Prod/gts/74X_dataRun2_v1): As [GR_R_74_V15A](https://cms-conddb.cern.ch/browser/#list/Prod/gts/74X_dataRun2_v4) with the following [changes](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/74X_dataRun2_v1/GR_R_74_V15A):
  - New Egamma regressions based on ECAL multifit reconstruction;
  - taxonomy change of `SiPixelGenErrorDBObjectRcd` tag;
  - removing RelVal customized tags for L1.
- HLT: [74X_dataRun2_HLT_frozen_v1](https://cms-conddb.cern.ch/browser/#list/Prod/gts/74X_dataRun2_HLT_frozen_v1): As [GR_H_V58A](https://cms-conddb.cern.ch/browser/#list/Prod/gts/GR_H_V58A) with the following [changes](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/74X_dataRun2_HLT_frozen_v1/GR_H_V58A):
  - Removing customized tags for L1;
  - taxonomy change of `EcalClusterLocalContCorrParametersRcd` tag;
  - adding label full for `HcalElectronicsMapRcd`;
  - adding negative energy filter payload; 
  - a snapshot time: 2015-08-20 12:10:16,000000.

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
@cmsbuild  please test
let's try it again

**Comment by mmusich** [comment]
please test

**Comment by slava77** [comment]
@mmusich @diguida 
I see in the browser https://cms-conddb.cern.ch/browser/#diff/Prod/gts/74X_dataRun2_v1/GR_R_74_V15A that a bunch of L1 and SiPixelGenErrorDBObjectRcd are updated for the run2_data. Your PR description suggests it's just the GBR. Please clarify

**Comment by slava77** [comment]
@mmusich @diguida 
also, is there a Prompt GT as well with the egamma regression payloads?

**Comment by mmusich** [comment]
@slava77 so in order:
  * the Prompt GT with the new e/gamma regression is not yet ready, but can be by today
  * the SiPixelGenErrorDB change is pure taxonomy. We just removed  the [account_name] from the tag name to make it less ugly, but the conditions are the very same.
  * the change in the L1 were customization that I think we don't require anymore. At least we removed them also in 75X, see this commit by @diguida  [https://github.com/cms-sw/cmssw/commit/d0828e4dd5385f4eb24b8ca8ea9ea2d017001501](git), [https://cms-conddb.cern.ch/browser/#diff/Prod/gts/75X_dataRun2_v2/GR_R_75_V5A](browser)

**Comment by mmusich** [comment]
please test

**Comment by slava77** [comment]
Looking at jenkins (alternative-comparisons) I see some oddity in 140.53 (HI data workflow):
[red is with this PR]
it looks like the bit assignment flipped somehow: the "ECAL triggered"  plots are now empty and "CSC exclusive triggered" are now filled.
wf140 53_eb_csctriggered
wf140 53_eb_ecaltriggered
Somehow these HI Ecal plots are not showing up in the relmon diffs (the same files are analyzed in both; maybe the histograms with special characters and spaces in the title confuse the relmon)

There are more plots with L1-related changes, in run1 data (4.53 and 140.53 included), but those appear to make sense:
like these emulator/data comparisons now showing no failures
wf4 53_cenjet
wf4 53_taujeterr

RECO products are not affected

**Comment by mmusich** [comment]
+1

**Comment by mmusich** [comment]
The GT for Prompt with the inclusion of the new egamma regressions is available: 74X_dataRun2_Prompt_v2, ([diff with previous](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/74X_dataRun2_Prompt_v1/74X_dataRun2_Prompt_v2)). I suppose I'll need to create a new one for express too, right?

**Comment by mmusich** [comment]
@davidlange6 what should we do here? I need to integrate the JEC for miniAOD asap. Shall I start from those in this PR or again (sic!) from scratch. @gpetruc

**Comment by davidlange6** [comment]
@mmusich - I was starting to look - presumably I can merge this and you can start from the GTs in this PR

**Comment by davidlange6** [comment]
@mmusich - do we have the GTs with the new JECs?

**Comment by mmusich** [comment]
@davidlange6 we were missing the payloads for 25ns. This has been fixed in the meanwhile, will come soon(ish)

**Comment by mmusich** [comment]
@davidlange6 new JECs are included in https://github.com/cms-sw/cmssw/pull/11172

**Pull request merged**
