### PR TITLE
nbOfDaughters_electrons_correction_Histos_90X_V2

### PR DESCRIPTION
**Pull request by archiron**
It is a modification of the validation code (ElectronMcMiniAODSignalValidator.cc & ElectronMcSignalValidator.cc) in order to avoid nbOfDaughters >2 (i.e. 3 or 4). This lead to difference in the entries for miniAOD if nbOfDaughters is >2.

in addition, a few files were cleaned to take into account the SingleElectronPtxx with SingleElectronPtxx_UP15 with xx = 10, 35, 1000.

@beaudett @fcouderc

### CODE REVIEW

**Comment by beaudett** [comment]
Hi,
adding some information: this PR solves a long standing issue that we had in the miniAOD validation: the number of reco-electrons matched to gen electrons was sometimes different by 1 or 2 (more) in the validation of ttbar samples. 
It should be mentioned that the gen electrons are coming from W's. 

We found out that due to the pruning of the GenParticle in the miniAOD. Indeed, one has 
W+->W+ + (gamma -> e+ + e-) 
the intermediate particles (e.g. the gamma) are dropped and the W+ is set as parent of the e+ and of the e-. In that case, the W+ has 3 or 4 daughters and that's how we detect the problem.
In RECO/AOD, the intermediate particles are kept, so there is no problem. 

[That said, I am surprised that the gamma->e+ + e- gets recorded in the original GenParticle collection, but that's off topic]

For consistency, we applied the same check on the number of daughters in the RECO validation

**Comment by archiron** [comment]
any update or pbm ?

**Comment by dmitrijus** [comment]
+1
I somehow missed this PR :(

**Comment by davidlange6** [comment]
+1

**Pull request merged**
