### PR TITLE
Update DQM onlinebeammonitor [11_3_X]

### LINKED ISSUE #34717: Update to DQM onlinebeammonitor
In order to properly monitor the updates of the BeamSpotOnline tags at lumisection level the configuration of the client
[onlinebeammonitor_dqm_sourceclient-live_cfg.py](https://github.com/cms-sw/cmssw/blob/master/DQM/Integration/python/clients/onlinebeammonitor_dqm_sourceclient-live_cfg.py) needs to be updated to include the `refreshTime` parameter.
This change only affects the **monitoring** of the BeamSpotOnline updates on the DQM side. 

The fix is rather simple (just adding a `toGet` to customize the process.GlobalTag is enough) and it has been tested already in the HLT menu live at P5 (see http://cmsonline.cern.ch/cms-elog/1121707).
I will prepare PRs for 11_3, 12_0 and 12_1 by today. 

@perrotta @qliphy @silviodonato This is just to let you know that it would be nice to include this in the new build for CRUZET (not sure whether is this already planned or if the issues with HCAL GPU code still do not have a solution).

FYI
@gennai @ggovi 
@amassiro @boudoul 
@cms-sw/dqm-l2

### PR DESCRIPTION
**Pull request by francescobrivio**
#### PR description:
Backport of #34719, fixes #34717
To be included in the next build for CRUZET 2021.

#### PR validation:
Compiles.
Also tested online and deployed the same configuration change in the HLT cosmics menu running in P5 (see http://cmsonline.cern.ch/cms-elog/1121707).

#### Backport:
Backport of #34719

### CODE REVIEW

**Comment by francescobrivio** [comment]
backport of #34719

**Comment by francescobrivio** [comment]
@jfernan2 @cms-sw/dqm-l2 could you please test this online at P5?

**Comment by francescobrivio** [comment]
@cmsbuild please test

**Comment by rvenditti** [comment]
This PR has been successfully tested in playback system in P5 online DQM with run 343082.

**Comment by rvenditti** [comment]
+1

**Comment by perrotta** [comment]
@rvenditti could you please sign also the master version of this PR, which must be merged first?

**Comment by perrotta** [comment]
+1
Now also successfully merged in master

**Pull request merged**
