### PR TITLE
[MagneticField] Move public headers to interface directory

### PR DESCRIPTION
**Pull request by smuzaffar**
As reported in #34718 , this PR moves headers in interface directory for `MagneticField`
```
      2 src/MagneticField/Layers/src/MagBinFinders.h
```
cleanup unnecessary include of
```
      1 src/MagneticField/ParametrizedEngine/src/OAEParametrizedMagneticField.h
```

### CODE REVIEW

**Comment by namapane** [comment]
@smuzaffar, I was not aware of #34762. I actually disagree with moving them to interface as they are not inteded to be public headers; they are part of their package's implementation. Why should they become part of the package public interface if they are not intended to be public at all? What is the alternative?
Incidentally, I notice that Configuration/Skimming/interface/LeptonSkimming.h is using directly MagneticField/ParametrizedEngine/src/OAEParametrizedMagneticField.h. This should NOT be allowed since it's getting around conditions (e.g. configuration of the MF for different IOVs, eras, etc) and it's precisely why the interface should remain private.
That class was really meant to be in src to prevent such occurences of incorrect use.

**Comment by namapane** [comment]
oops I realize I misunderstood the PR, forget my previous comment (now deleted)

**Comment by smuzaffar** [comment]
@namapane , sorry the PR discription was wrong . I have updated it, yes `MagneticField/ParametrizedEngine/src/OAEParametrizedMagneticField.h` remains in the `src` directory. There was an unnecessary include of it which I can cleaned up. The MagneticField/Layers/src/MagBinFinders.h is actually used by other package so that shoudl go in to interface directory.

**Comment by namapane** [comment]
Perfect, thanks @smuzaffar for the clarification!

**Comment by smuzaffar** [comment]
please test

**Comment by slava77** [comment]
+reconstruction

for https://github.com/cms-sw/cmssw/pull/34763	c287453 
- code changes are technical, in line with the PR description 
- jenkins tests pass and comparisons with the baseline show no (relevant) differences

**Comment by bbilin** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
