### PR TITLE
Ecal Bad calib filter adding a new problematic crystal

### PR DESCRIPTION
**Pull request by eioannou**
Pull Request to add the new crystal to the list of baddetEcal in the ECAL bad calib filter.

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/24878	953f3e6
- somewhat trivial addition of a bad ECAL det ID to be checked for flagging with ecalBadCalibFilter
- jenkins tests pass and comparisons with the baseline show no differences (either due to low stats or due to lack of monitoring of the MET flags).

@eioannou 
are you OK with just having this in the master/10_4_X release or do you have plans for backports?
The backports will be complicated by the requirement to preserve behavior of existing defaults.

**Comment by eioannou** [comment]
We are planning to backport it too.

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
@perrotta concerning the backport issue, that looks similar to a new condition, right?

**Comment by fabiocos** [comment]
merge

**Comment by perrotta** [comment]
In practice, yes: one more crystal is added to the list of problematic  
crystals for that ​EcalBadCalibFilter, which removes events with  
anomalous energy intercalibrations in those specific ECAL channels.

Fabio Cossutti <notifications@github.com> ha scritto:

**Pull request merged**
