### PR TITLE
Use Hcal Trigger Tower Geometry from Event Setup

### PR DESCRIPTION
**Pull request by ianna**
- Use Hcal trigger tower geometry from Event setup

### CODE REVIEW

**Comment by ianna** [comment]
@mulhearn - please, review this proposal.

**Comment by mmusich** [comment]
please test

**Comment by mulhearn** [comment]
So I guess the HCalScales producer relies on the L1CaloGeometry for O2O.   In the past you just setup the L1CaloGeometry via config file parameters, and used that when producing L1CaloGeometry, but now you want to take it from the database.  This means the HCalScales will depend on L1CaloGeometry.  Do I understand correctly?

**Comment by mulhearn** [comment]
I doubt standard relvals are enough of a test here, we will have to test that this still works in our O2O...

**Comment by ianna** [comment]
@mmusich - ideally, one can avoid the dependency by putting hard-coded hcal trigger tower geometry to a DB record, but this will require touching much more code. Please, let me know about O2O test results.

**Comment by mulhearn** [comment]
What timescale is this needed?

**Comment by ianna** [comment]
@mulhearn - 7_6_0

**Comment by diguida** [comment]
@ianna I am preparing a branch with the new GT. Please cherry pick here.

**Comment by ianna** [comment]
@mulhearn - any news on test results? Thanks.

**Comment by mulhearn** [comment]
Not yet, I'm afraid.  We have very limited coverage for L1 O2O and at the
moment it is full dedicated to preparing the O2O of Stage 1 Calo...  I'll
try to get to this test this week.  Unfortunately, its not as easy as just
merging this PR since we run in an environment without git and on 74X...

**Comment by kkotov** [comment]
Regarding the L1T O2O, we may need a small modification on top of this PR addressing this error message:
"
No "CaloGeometryRecord" record found in the dependent record "L1CaloHcalScaleRcd".
Please add an ESSource or ESProducer that delivers the "CaloGeometryRecord" record.
"
What ESSource/ESProduced should we include for this record?

**Comment by davidlange6** [comment]
Is this or now obsolete?

**Comment by kkotov** [comment]
Let Mike correct me if I'm wrong, but I believe we still take care of the L1CaloHcalScaleRcd in the L1T O2O, although this my be a legacy payload. Hence, as long as this record is changed in this PR to depend on CaloGeometryRecord, we need to make sure the CaloGeometryRecord will be available in Event Setup, otherwise L1T O2O fails.

**Comment by ianna** [comment]
@kkotov - unfortunately, there is no other access to HcalTrigTowerGeometry available, but via EventSetup. Could you, please, test it?

**Comment by ianna** [comment]
@kkotov - the EventSetup producer for HcalTrigTowerGeometry is:
```
HcalTrigTowerGeometryESProducer = cms.ESProducer("HcalTrigTowerGeometryESProducer")
```
which configuration file should be updated?

**Comment by kkotov** [comment]
But we don't seem to need HcalTrigTowerGeometry. We only need CaloGeometryRecord to be present in Event Setup.

**Comment by kkotov** [comment]
Correction: it turned out that we do need it. But I could only make the L1T O2O running after I added 
------------------------
from Configuration.Geometry.GeometryExtended2015Reco_cff import *
HcalTrigTowerGeometryESProducer = cms.ESProducer("HcalTrigTowerGeometryESProducer")
------------------------
So, on our side everything seems to work with this PR given we add the two lines above to a local version of L1TriggerConfig/L1ScalesProducers/python/L1CaloHcalScaleConfigOnline_cfi.py

**Comment by ianna** [comment]
@kkotov - I've updated the PR as suggested. Thanks.

**Comment by ianna** [comment]
@cmsbuild please test

**Comment by ianna** [comment]
@cmsbuild please test

**Comment by smuzaffar** [comment]
please test

**Comment by ianna** [comment]
@smuzaffar - I did not see this one forward ported to 80x.

**Comment by smuzaffar** [comment]
@Ianna, @davidlange6 asked to only forward port PR which were made on/after 1st of SEP that is why it was not forward ported

**Comment by ianna** [comment]
@mulhearn, @mmusich, @diguida and @ggovi - the PR is pending your approval since 76x queue was opened. It's about to be closed. Could you, please, have a look and sign before 760 is out? Thanks.

**Comment by mulhearn** [comment]
+1

**Comment by mulhearn** [comment]
Sorry did not notice this converged!

**Comment by ianna** [comment]
@davidlange6 - could you, please, take it for 760? Thanks.

**Comment by mmusich** [comment]
+1

**Comment by ianna** [comment]
@ggovi - ping

**Comment by ggovi** [comment]
+1

**Comment by davidlange6** [comment]
@cmsbuild, please test
(the old tests are gone)

**Comment by davidlange6** [comment]
+1

**Pull request merged**
