### PR TITLE
Be able to use merged magnetic field interpolation files

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

- Provide a utility to create an interpolation file which is a merger of all files for a given table set. This also creates a separate index file which says where in the merge file each individual file is located.
- Extend DD4Hep_MagGeoBuilder to be able to use either the merged file (if present) or the individual files
- Use of the merged file decreased the setup time from 9 seconds to less than 2 seconds on my test machine.

#### PR validation:

- Running the unit tests in MagneticField/Engine pass both with and without the index file being present
- Used GridFileReader to dump the contents of the interpolation file with and without the index. The two files chosen gave identical dumped information.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by namapane** [comment]
Hi Chris, nice job. A couple of comments:
-If I understand correctly there is currently no way to force reading tables instead than the merged file? Once the merged file will be in the release there will be no way for  to remove it, which may be needed for development.
-could you please add some comment on how mergeFieldTable is supposed to be called, possibly both in as comments in the cc and in [the SWGuide](https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideMagneticField)? 
By the time we will need to update the map the next time, we may have forgotten about this step otherwise...

**Comment by Dr15Jones** [comment]
> If I understand correctly there is currently no way to force reading tables instead than the merged file? Once the merged file will be in the release there will be no way for to remove it, which may be needed for development.

If you want, I could add a configuration parameter to override the default behavior and use the individual files.

**Comment by namapane** [comment]
> > If I understand correctly there is currently no way to force reading tables instead than the merged file? Once the merged file will be in the release there will be no way for to remove it, which may be needed for development.
> 
> If you want, I could add a configuration parameter to override the default behavior and use the individual files.

From a quick look it seems to me that percolating such a parameter would require an annoying number of changes, so my preference would be just to set a flag in the code for the purpose, that can be changed at compile time - as this would be used only for development, having to recompile one file would not be an issue in that case. Of course the developer may hack the code as well, but having flag ready will make the task more obvious and straightforward.

**Comment by Dr15Jones** [comment]
please test

**Comment by namapane** [comment]
> The twiki documentation was updated with how to create the merged files.

Cool, thanks Chris!

**Comment by clacaputo** [comment]
Hi @Dr15Jones , out of curiosity, in order to use the merged file, one should run `mergeFieldTable.cc` producing the two files `.merge` and `.index`, right? What's the plan for using them in `DD4hep_VolumeBasedMagneticFieldESProducer` or `DD4hep_VolumeBasedMagneticFieldESProducerFromDB`?
Are this file gonna be produced and stored in the release?

**Comment by Dr15Jones** [comment]
> in order to use the merged file, one should run mergeFieldTable.cc producing the two files .merge and .index, right?

Correct. Those files need to be in the same directory as holds (or would hold) the present 9000+ files.

>  What's the plan for using them in DD4hep_VolumeBasedMagneticFieldESProducer or DD4hep_VolumeBasedMagneticFieldESProducerFromDB?

That would be up to the maintainers of those packages.

> Are this file gonna be produced and stored in the release?

They are not in the release, per-se. They would go into the external data area same as where the non merged files live now.

**Comment by qliphy** [comment]
+1

**Comment by namapane** [comment]
> > in order to use the merged file, one should run mergeFieldTable.cc producing the two files .merge and .index, right?
> 
> Correct. Those files need to be in the same directory as holds (or would hold) the present 9000+ files.
> 
> > What's the plan for using them in DD4hep_VolumeBasedMagneticFieldESProducer or DD4hep_VolumeBasedMagneticFieldESProducerFromDB?
> 
> That would be up to the maintainers of those packages.
> 
> > Are this file gonna be produced and stored in the release?
> 
> They are not in the release, per-se. They would go into the external data area same as where the non merged files live now.

Hi @Dr15Jones, 
Publishing data files is done by a PR to https://github.com/cms-data/MagneticField-Interpolation . I can do this myself at some point, but given that you already have the files and done all the tests, maybe it's safer if you make the PR directly?

**Comment by Dr15Jones** [comment]
Hi @namapane 
>  I can do this myself at some point, but given that you already have the files and done all the tests, maybe it's safer if you make the PR directly?

Turns out, I've already deleted that development area (I do that frequently) so I don't have the files any longer.

**Pull request merged**
