### PR TITLE
Replace XercesString

### PR DESCRIPTION
**Pull request by ianna**
* Replace XercesString with safer implementation which does not leak
* Set and release locks
* Initialize and cleanup Xerces
* Forbid member function access without Xerces initialization
* Cleanup spurious includes

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by Dr15Jones** [comment]
+1

**Comment by dmitrijus** [comment]
+1

**Comment by ggovi** [comment]
+1

**Comment by davidlange6** [comment]
for 90x

**Pull request closed without merging**
