### PR TITLE
Phase2-hgx359K Include HD200 wafers along with HD120, LD200, LD300 ones for HGCal Geometry

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Include HD200 wafers along with HD120, LD200, LD300 ones for HGCal Geometry

#### PR validation:

To be included with other V19 geometry components to be tested

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by bsunanda** [comment]
@srimanob Could you please approve this PR?

**Comment by bsunanda** [comment]
@srimanob Could you please approve this PR?

**Comment by srimanob** [comment]
+Upgrade

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
