### PR TITLE
Migrate HcalTPGCoderULUT to EventSetup consumes

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

This PR migrates HcalTPGCoderULUT to EventSetup consumes (and compacts the code a tiny bit) as part of #26748.

#### PR validation:

Code compiles, no changes expected.

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
Merging the code formatting in #26948 introduced a merge conflict here, I'll resolve that tomorrow on top a fresh IB.

**Comment by makortel** [comment]
Rebased to fix a conflict.

**Comment by pohsun** [comment]
please test

**Comment by pohsun** [comment]
+1

**Comment by fabiocos** [comment]
@rekovic the code looks ok to me, I would like to move forward with it. Could you please have a look?

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Pull request merged**
