### PR TITLE
add dedx harmonic2 for pixel hits

### PR DESCRIPTION
**Pull request by slava77**
~Lowering of pt from 15 GeV to 10 GeV increases signal yields by 10% for short (pixel-only) heavy high pt tracks.~

Addition of the pixel-only harmonic2 enables calibration from AOD (it has to be done on low pt tracks; hence full addition)

the cost to AOD is under 1% (3kB/evt from the pixel-only harmonic2) based on checks in ttbar and Run2016H JetHT  data.

this is only useful, if it can be added to the legacy rereco.

I have updated this PR to be more safe for the legacy reprocessing to simply add a new product.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
backport of #18773

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
I have updated this PR to be more safe for the legacy reprocessing to simply add a new product.
This is in case it is decided to still apply this to a fraction of PDs.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/18771	7fbca7e
- adds a new product ``` ecoDeDxDataedmValueMap_dedxPixelHarmonic2__ ``` to AOD. 
- jenkins tests pass and the summary looks as expected:
    - No significant changes to the logs found
    - ROOTFileChecks: Some differences in event products or their sizes found
    - Reco comparison results: 0 differences found in the comparisons

This PR is valid only if existing legacy rereco pilots are to be redone for other reasons.
To be closed once actual production is clearly in progress.

**Comment by slava77** [comment]
the full 80X LR campaign has started. 
So, I'm closing this.

**Comment by slava77** [comment]
Apparently this is a valid request again

**Comment by davidlange6** [comment]
merge

**Pull request merged**
