### PR TITLE
Use EventSetup consumes in TrackerDigiGeometryESModule

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

Call consumes for TrackerDigiGeometryESModule and use tokens to get data products.

#### PR validation:

Compiles.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
Part of #26584

**Comment by Dr15Jones** [comment]
please test

**Comment by cvuosalo** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
