### PR TITLE
Cleanup Geant4 user actions 2

### PR DESCRIPTION
**Pull request by civanch**
This PR includes modifications from #15709 with the fix of a rare problem on top. The problem happens when a primary particle from PYTHIA has initial position outside CMS world volume.

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by civanch** [comment]
@davidlange6 , in this PR the fix is in one line 207 of StackingAction.cc, the rest is #15709 unchanged.

**Comment by davidlange6** [comment]
+1

**Comment by lgray** [comment]
@davidlange6 FYI - This pull request somehow disables particle information tracking for anything but photons (or things related to them, the behavior is strange) and in so destroys the functionality of SimClusters in HGCal. Simclusters are critical to the developments ongoing in HGCal software right now and I suggest we revert this PR until the fix is found.

@civanch

**Comment by slava77** [comment]
@lgray 
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_8_1_X_2016-09-20-2300+15926/15984/validateJR/all_OldVSNew_TTbar13TeV2023D3wf20824p0/all_OldVSNew_TTbar13TeV2023D3wf20824p0c_log10recoPFClusters_particleFlowClusterHGCal__RECO_obj_energy.png
shows fairly large changes
So, maybe it's a matter of looking at the right place

**Comment by slava77** [comment]
@lgray 
pre12 is broken for HGCAL due to this, right?

**Comment by civanch** [comment]
hi all, it can be reverted if needed urgently. If it is possible to wait few days a simple fix will be provided on top.

**Comment by lgray** [comment]
@slava77 yes, pre12 is broken for HGCal because of this. However it is easy to revert for private studies.
@civanch If you can tell me what the fix is, I can probably submit it myself while you are away.

**Comment by rovere** [comment]
Not only HGCAL, also all the scripts to compute/derive material budget are totally broken.
It took me 1.5 days to "understand" why the hell the watchers were not triggering.
I confirm neutrino gun is totally broken, while, e.g. muons are still tracked, at least that's what I see locally.
I managed to survive with this broken pre12 using:
process.trackingMaterialProducer.StackingAction.TrackNeutrino = True
which I manage to keep on using for the time being.
I'm wondering how this could have been passed totally un-noticed....

**Comment by lgray** [comment]
@slava77 @davidlange6 To me, given the much more expansive effects, it makes sense to revert and possibly cut an emergency pre-release. Then introduce a correct and more-or-less technical version of this PR.

@rovere Concur?

**Comment by rovere** [comment]
+1 to @lgray

**Comment by davidlange6** [comment]
we’ll see what else is wrong with pre12 (up to at least one more thing already)

**Comment by rovere** [comment]
the fix for my use case is as easy as getting rid of this line:
https://github.com/cms-sw/cmssw/pull/15709/files#diff-d74dcda36fb6c5179867008f990be245R205
and similar ones.
Or, if you do not want to revert it, I can anyway force it to happen.

**Pull request merged**
