### PR TITLE
Updated GEMGeometryBuilder to allow GE2/1 demonstrator to be built - Alternative Method

### PR DESCRIPTION
**Pull request by watson-ij**
#### PR description:

To be able to build the GE2/1 demonstrator into the GEMGeometry, need to change a check which creates the superchamber. 
In this case, we do an initial scan of the geometry and check if only 1 GE2/1 chamber exists, and if so, set a flag which tells the superchamber builder to build off layer 2 for GE2/1 (since only a single layer 2 chamber is present in the demonstrator).

This is an alternative to #36482, only one of these two PRs should be added.

@cvuosalo Do you think this approach is better than the previous?

#### PR validation:

I have checked the geometry builder with a run3 DDD geometry and a phase2 geometry, and they build correctly. Would need to test with Sunanda's changes also.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by watson-ij** [comment]
[phase2.alternate.changes.log](https://github.com/cms-sw/cmssw/files/7874060/phase2.alternate.changes.log)
[run3.alternate.changes.log](https://github.com/cms-sw/cmssw/files/7874061/run3.alternate.changes.log)
[phase2.no.changes.log](https://github.com/cms-sw/cmssw/files/7874062/phase2.no.changes.log)
[run3.no.changes.log](https://github.com/cms-sw/cmssw/files/7874063/run3.no.changes.log)

debug logs for the GEMGeometryBuilder for the alternate builder (this pr), and the no changes (before either of the PRs)

**Comment by watson-ij** [comment]
I tried with Sunanda's changes in #36654 and #36679, and 11634.911 runs successfully as for the other PR, though 11634.0 fails at CSC rechit validation (though I guess the run3 non-dd4hep is not updated, but is it expected to run with the changes?).

**Comment by watson-ij** [comment]
please test

**Comment by watson-ij** [comment]
40221.0 also completes and I get GEM simhits from all stations. 40221.911 doesn't but its an issue with the tracker geometry, so I don't think I can test it.

**Comment by jfernan2** [comment]
+1

**Comment by civanch** [comment]
@cvuosalo , for me this PR is better than #36482 and what about you?

**Comment by cvuosalo** [comment]
+1

**Comment by cvuosalo** [comment]
Yes, I prefer this PR over #36842.

**Comment by civanch** [comment]
@srimanob, please, have a look into this PR.

**Comment by srimanob** [comment]
Hi @watson-ij 
Sorry for my late review. Should we not expect any changes shown in PR test?

**Comment by civanch** [comment]
@srimanob , I do not know about Phase-2 (demonstrator chambers should not be there but code for GEM geometry building can be used).  For Run-3 this PR itself change nothing until new DB record is prepared.

**Comment by watson-ij** [comment]
@srimanob No, the changes should only happen with the demonstrator geometry, which are included in a different PR. For all the current geometries, it should build the same reco geometry as before.

**Comment by civanch** [comment]
urgent

**Comment by srimanob** [comment]
+Upgrade

Thanks @civanch @watson-ij for clarification.

**Comment by perrotta** [comment]
The suggested fixes above are very minor.
Given the urgency of this PR, they can be deferred to some later update

**Comment by perrotta** [comment]
+1

**Pull request merged**
