### PR TITLE
HLT menu development for `12_3_X` [`12_4_X`]

### PR DESCRIPTION
**Pull request by missirol**
#### PR description:

Development of HLT menus for `CMSSW_12_3_X`.

This is the PR for the `master` branch, which will then be backported to `12_3_X` (which is currently the release used for HLT-menu development for Run 3).

Includes the integration of the following JIRA tickets.

  - Part of [CMSHLT-2261](https://its.cern.ch/jira/browse/CMSHLT-2261): [BPH] Update of low-mass dimuon triggers for Run 3.
  - [CMSHLT-2286](https://its.cern.ch/jira/browse/CMSHLT-2286): [EGM] Removal of "caloTowers" from E/Gamma reconstruction at HLT.
  - [CMSHLT-2293](https://its.cern.ch/jira/browse/CMSHLT-2293): [EGM] Update for Run-3 E/Gamma supercluster energy regression.

The configurations were created with [`V03-03-00` of ConfDB](https://github.com/cms-sw/hlt-confdb/releases/tag/V03-03-00), which introduces support for `ProcessAcceleratorCUDA`.

#### PR validation:

TSG tests.

#### If this PR is a backport, please specify the original PR and why you need to backport that PR:

N/A

### CODE REVIEW

**Comment by missirol** [comment]
please test

**Comment by missirol** [comment]
The large reduction of DQM outputs in `HLT/HLTEgammaValidation` is related to the changes in this PR to E/Gamma triggers.

One of the ED producers used in those triggers is changed by this PR (`EgammaHLTBcHcalIsolationProducersRegional` replaced by `EgammaHLTHcalVarProducerFromRecHit`), and the DQM/Validation client does not recognize the new modules, because it hard-codes the types of the acceptable ED producers (see [here](https://github.com/cms-sw/cmssw/blob/3dc8128db71e920b3bcfdfc9e98dac8316e578bc/HLTriggerOffline/Egamma/src/EmDQM.cc#L1437-L1449), for example).

This patch [*] is a starting point to fix the issue, but this task is left to EGM and/or DQM experts.

In my opinion, this should not delay this PR.

Attn: @cms-sw/dqm-l2 @cms-sw/egamma-pog-l2

[*]
```diff
diff --git a/HLTriggerOffline/Egamma/src/EmDQM.cc b/HLTriggerOffline/Egamma/src/EmDQM.cc
index 0a1fb605a98..43c0e8f9f17 100644
--- a/HLTriggerOffline/Egamma/src/EmDQM.cc
+++ b/HLTriggerOffline/Egamma/src/EmDQM.cc
@@ -1442,6 +1442,7 @@ edm::ParameterSet EmDQM::makePSetForEgammaGenericFilter(const std::string &modul
       inputType == "EgammaHLTGsfTrackVarProducer" ||               // GSF track deta and dphi filter
       inputType == "EgammaHLTBcHcalIsolationProducersRegional" ||  // HCAL isolation and
                                                                    // HE
+      inputType == "EgammaHLTHcalVarProducerFromRecHit" ||         // HCAL isolation (H/E) from RecHits
       inputType == "EgammaHLTEcalPFClusterIsolationProducer" ||    // ECAL PF isolation
                                                                    // filter
       inputType == "EgammaHLTHcalPFClusterIsolationProducer" ||    // HCAL PF isolation
@@ -1530,6 +1531,7 @@ edm::ParameterSet EmDQM::makePSetForEgammaGenericQuadraticFilter(const std::stri
       inputType == "EgammaHLTHcalIsolationProducersRegional" ||      // HCAL isolation and HE
       inputType == "EgammaHLTBcHcalIsolationProducersRegional" ||    // HCAL isolation and
                                                                      // HE
+      inputType == "EgammaHLTHcalVarProducerFromRecHit" ||           // HCAL isolation (H/E) from RecHits
       inputType == "EgammaHLTEcalPFClusterIsolationProducer" ||      // ECAL PF isolation
                                                                      // filter
       inputType == "EgammaHLTHcalPFClusterIsolationProducer" ||      // HCAL PF isolation
```

**Comment by missirol** [comment]
+hlt

 - differences in outputs of Run-3 wfs are in line with changes to the HLT GRun menu.
 - https://github.com/cms-sw/cmssw/pull/37754#issuecomment-1114186404 requires a follow-up related to the HLT-EGM Validation sequences.

**Comment by perrotta** [comment]
> The large reduction of DQM outputs in `HLT/HLTEgammaValidation` is related to the changes in this PR to E/Gamma triggers.
> 
> One of the ED producers used in those triggers is changed by this PR (`EgammaHLTBcHcalIsolationProducersRegional` replaced by `EgammaHLTHcalVarProducerFromRecHit`), and the DQM/Validation client does not recognize the new modules, because it hard-codes the types of the acceptable ED producers (see [here](https://github.com/cms-sw/cmssw/blob/3dc8128db71e920b3bcfdfc9e98dac8316e578bc/HLTriggerOffline/Egamma/src/EmDQM.cc#L1437-L1449), for example).
> 
> This patch [*] is a starting point to fix the issue, but this task is left to EGM and/or DQM experts.
> 
> In my opinion, this should not delay this PR.
> 
> Attn: @cms-sw/dqm-l2 @cms-sw/egamma-pog-l2
> 
> [*]
> 
> ```diff
> diff --git a/HLTriggerOffline/Egamma/src/EmDQM.cc b/HLTriggerOffline/Egamma/src/EmDQM.cc
> index 0a1fb605a98..43c0e8f9f17 100644
> --- a/HLTriggerOffline/Egamma/src/EmDQM.cc
> +++ b/HLTriggerOffline/Egamma/src/EmDQM.cc
> @@ -1442,6 +1442,7 @@ edm::ParameterSet EmDQM::makePSetForEgammaGenericFilter(const std::string &modul
>        inputType == "EgammaHLTGsfTrackVarProducer" ||               // GSF track deta and dphi filter
>        inputType == "EgammaHLTBcHcalIsolationProducersRegional" ||  // HCAL isolation and
>                                                                     // HE
> +      inputType == "EgammaHLTHcalVarProducerFromRecHit" ||         // HCAL isolation (H/E) from RecHits
>        inputType == "EgammaHLTEcalPFClusterIsolationProducer" ||    // ECAL PF isolation
>                                                                     // filter
>        inputType == "EgammaHLTHcalPFClusterIsolationProducer" ||    // HCAL PF isolation
> @@ -1530,6 +1531,7 @@ edm::ParameterSet EmDQM::makePSetForEgammaGenericQuadraticFilter(const std::stri
>        inputType == "EgammaHLTHcalIsolationProducersRegional" ||      // HCAL isolation and HE
>        inputType == "EgammaHLTBcHcalIsolationProducersRegional" ||    // HCAL isolation and
>                                                                       // HE
> +      inputType == "EgammaHLTHcalVarProducerFromRecHit" ||           // HCAL isolation (H/E) from RecHits
>        inputType == "EgammaHLTEcalPFClusterIsolationProducer" ||      // ECAL PF isolation
>                                                                       // filter
>        inputType == "EgammaHLTHcalPFClusterIsolationProducer" ||      // HCAL PF isolation
> ```

@missirol the fix that you propose is quite logical and straightforward.

I would be in favour to **include it here**, and in the backport PR as well, so that (1) the new menu and the needed dqm update can go on together, and (2) the comparisons in the PR tests remain meaningful.

(By the way, since you are there please also move up the commented "HE" and "filter" in the lines above and below, for a better reading; if the code-format checks split the line again, you can replace "isolation" with "isol" (e.g.), which is still a nicer read than having the last word of the line split)

**Comment by missirol** [comment]
> I would rather be in favour to **include it here** [..]

Okay, done. References in the DQM module to plugin types that don't exist anymore have been removed as well.

**Comment by missirol** [comment]
please test

**Comment by missirol** [comment]
Based on the outputs of the PR tests, the update of the DQM module worked as expected (no unexpected differences).

@cms-sw/dqm-l2 , this PR now requires your signature.

**Comment by missirol** [comment]
+hlt

 - differences in outputs of Run-3 wfs are in line with changes to the HLT GRun menu.
 - includes a related update to a DQM/Validation plugin.

**Comment by missirol** [comment]
@cms-sw/dqm-l2 , please consider reviewing this PR (it contains a simple update to 1 DQM module).

There are more updates to the HLT menu in the pipeline, so it would be good to integrate this PR and test it in IBs sooner rather than later.

**Comment by emanueleusai** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
