### PR TITLE
back port of pixel lumi dqm from 76X to 74X

### PR DESCRIPTION
**Pull request by rpatkennyiii**
this is a back port of this pull request: https://github.com/cms-sw/cmssw/pull/10007

### CODE REVIEW

**Comment by deguio** [comment]
status:
this PR is being tested on the playback and will be deployed in production soon (later today/tomorrow) given the fact that it is urgent.
however there are a couple of things to be fixed before we go with a merge:
- please update the PixelLumiDQM to take the list of deadModules from DB (the current hardcoded list is out of date)
- please replace the filter ZeroBiasSelector_cfi.py with an option at the source directly in the pixellumi_dqm_sourceclient-live_cfg.py config [1]



[1]
add one line like this:
process.source.SelectEvents = cms.untracked.vstring('HLT_*Mu*')

if you want to be more specific, you can OR things:
process.source.SelectEvents = cms.untracked.vstring('HLT_*SingleMu*', 'HLT_*DoubleMu*')

**Comment by deguio** [comment]
-1
rejecting for now to make sure we don't forget

**Comment by davidlange6** [comment]
@cmsbuild please test

**Comment by mojoe137** [comment]
@cmsbuild please test

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
@mojoe137
please rename this PR specifying a meaningful title.
thanks,
F.

**Comment by deguio** [comment]
+1
online only

**Pull request merged**
