### PR TITLE
remove all uses of -p, --parameter-set with cmsRun

### PR DESCRIPTION
**Pull request by kpedro88**
#### PR description:

This PR fixes all tests/scripts outside of the core framework for the update proposed in #42650.

#### PR validation:

`scram b runtests` passes with the affected packages checked out.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

see discussion at  #42650

### CODE REVIEW

**Comment by kpedro88** [comment]
test parameters:
pull_requests = #42650

**Comment by makortel** [comment]
+core

(RelVal-INPUT tests timing out is not critical, as the changes are in unit tests and documentation)

**Comment by jfernan2** [comment]
+1

**Comment by kpedro88** [comment]
hold

**Comment by emanueleusai** [comment]
+1

**Comment by Dr15Jones** [comment]
@perrotta there is no reason to wait for #42650 as the use of `-p` hasn't been necessary for more than a decade.

**Comment by perrotta** [comment]
> @perrotta there is no reason to wait for #42650 as the use of `-p` hasn't been necessary for more than a decade.

Ah, great. Thank you @Dr15Jones 
Then I wonder why @kpedro88 has put this on hold... In any case, this PR was only tested together with #42650: to unhold it I imagine tests should be also run standalone

**Comment by kpedro88** [comment]
I was planning to update this PR with other unit test changes, but @Dr15Jones makes a good point that this PR could actually be merged standalone. Let's run the standalone tests to make sure.

**Comment by kpedro88** [comment]
test parameters:

**Comment by kpedro88** [comment]
unhold

**Comment by rappoccio** [comment]
+1

* Will merge this as discussed in ORP on 19-Sep

**Pull request merged**
