### PR TITLE
Move contents of beginJob() to endJob() in APVValidationPlots

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

Following the discussion in https://github.com/cms-sw/cmssw/pull/28920, this PR removes the `TH1*` pointer member variables by moving the contents of `beginJob()` to `endJob()`. Now it is crystal clear that this module accesses DQMStore only in `endJob()`, and does not need anything elsewhere in CMSSW.

#### PR validation:

Code compiles. I tried to run the two configuration files in `DQMOffline/CalibTracker/test` that use `APVValidationPlots` module, but they are nonfunctional for other reasons.

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
I also wonder if this code is really used anywhere.

**Comment by jfernan2** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
