### PR TITLE
Data Formats Migration to std::shared_ptr<GeomDet>

### PR DESCRIPTION
**Pull request by ianna**
DataFormats need to be adjusted to use std::shared_ptr<GeomDet>

This PR is based on https://github.com/cms-sw/cmssw/pull/20692
The full CMSSW will not compile, though. The PR is open for discussion.

### CODE REVIEW

**Comment by ianna** [comment]
The target is CMSSW_9_5_X

**Comment by Dr15Jones** [comment]
-1 The changes remove the `const` access to the `GeomDet` items and therefore break thread safety.

**Comment by ianna** [comment]
@Dr15Jones - good point, thanks. It looks like const shared_ptr& as a parameter should be fine.

**Comment by Dr15Jones** [comment]
I'm afraid a `const shared_ptr&` will not work since it is like a `T * const` not a `T const *`. It really has to be a `shared_ptr<const GeomDet>`.

**Comment by ianna** [comment]
yes, you are right. Also, TrakingRecHit has a copy of GeomDet and owns it.

**Comment by ianna** [comment]
@Dr15Jones - DataFormats have been updated.

**Comment by VinInn** [comment]
Sorry, TrakingRecHit has just a reference to GeomDet.
Saaid that  -1.

Please prove that memory and timing does not increase.

The reason why GeomDet was using such a model was neither random nor old-fashoned:
was intentional!
Please justify your choices and do not touch GeomDet.

**Comment by VinInn** [comment]
There is no reason of shared pointers fo GeomDet, the ownership model is well defined and strict.
There is ONE owner and many clients. There is no way clients lifetime can spam beyond the owner.
We took a great deal of effort to optimize all that.

**Comment by VinInn** [comment]
AND next time core software decide to waste time in chaning something the facto owned by TRACKING, please come first to discuss with us.

**Comment by makortel** [comment]
I concur with Vincenzo, what exactly do the `shared_ptr`s try to solve? From client side they look pure overhead (reference counting and interfaces forcing a certain ownership model).

If the reason is geometry-internal memory management (only), please don't expose that to clients if it is not really needed (and even then I'd imagine `unique_ptr`+bare pointer could do the job, at least if it is simple to understand that the `unique_ptr`s outlive the bare pointers)

**Pull request closed without merging**
