### PR TITLE
GEM online DQM modification - full GE1/1

### PR DESCRIPTION
**Pull request by quark2**
#### PR description:
This PR is for a reduction of some histograms to avoid a crash from the part of onlineDQM for GEM. According to [1], a crash due to some too big histograms, which are not useful for P5 operation, is reported on the test. This PR is a forward-port of the fix which is done on [1] (to CMSSW_11_1_X).

Also, there is a correction of the AMC IDs.

[1] https://github.com/cms-sw/cmssw/pull/31447

#### PR validation:
Test are done and one can check again by `runTheMatrix` workflows

@jshlee @watson-ij @hyunyong

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
Tested in ARM, crash reported here:
https://github.com/cms-sw/cmssw/issues/31539
disappears with this PR

**Comment by jfernan2** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
