### PR TITLE
DataFormat for DT Phase-2 Trigger Primitives

### PR DESCRIPTION
**Pull request by battibass**
#### PR description:

This PR adds a DataFormat for the DT Trigger Primitives for Phase-2. The inclusion of the format in CMSSW is a preliminary step to simplify the development of emulators, as well as the one of the DQM and unpacker programs for the DT Slice Test.

#### PR validation:

No real testing was made, apart from trying to fill the collection using preliminary versions of the emulator code, that are presently only available in private branches.

### CODE REVIEW

**Comment by rekovic** [comment]
please test

**Comment by fabiocos** [comment]
@rekovic could you please scrutinize this PR?

**Comment by rekovic** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
