### PR TITLE
moved ParticleTowerProducer_cff.py to cfi for inclusion in confdb an…

### PR DESCRIPTION
**Pull request by cfmcginn**
Moved RecoHI/HiJetAlgos/python/ParticleTowerProducer_cff.py to cfi for inclusion in confdb and hlt dev.
See HLT Dev. Hypernews for relevant conversation (a search of my username I think is enough to find).

@kkrajczar

### CODE REVIEW

**Comment by slava77** [comment]
Please remove the cff file or change it to include the cfi file.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cmsbuild please test
these were DAS errors
[what a waste of resources to recover from these]

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/9089	 5f4ed12
purely technical change
jenkins tests completed and comparisons with the baseline show no difference

**Comment by davidlange6** [comment]
+1

**Pull request merged**
