### PR TITLE
Add BPHParking skim module and the relval steps

### PR DESCRIPTION
**Pull request by kfjack**
- Merging the updates from PR #25757
- Add the corresponding relval steps for 2018B, using RAW data for run 317661 and lumi 301-400
- The workflow number is 136.898

@gkaratha @fabiocos @prebello Please follow this one. Many thanks.

### CODE REVIEW

**Comment by prebello** [comment]
please test workflow 136.898

**Comment by kfjack** [comment]
@gkaratha could you help to verify the skim output? Many thanks!

**Comment by gkaratha** [comment]
Dear @kfjack ,

Thanks, of course i will do it. Can I ask what exactly you want me to check? sorry for my ignorance, it is the first time that I am pushing a skim file. Also please note that as soon as new low pT e will be ready the code will be update it.  Thanks again.

Best regards,
George

**Comment by kfjack** [comment]
Hi @gkaratha, sure, could you verify the outputs under:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-25892/33065/runTheMatrix-results/136.898_RunParkingBPH2018B+RunParkingBPH2018B+HLTDR2_2018+RECODR2_2018reHLT_skimParkingBPH_Prompt+HARVEST2018/

**Comment by kpedro88** [comment]
@kfjack @gkaratha what is the status of this PR?

**Comment by kfjack** [comment]
Hi @kpedro88 the test seems correct to me. Just need the confirmation from @gkaratha for the skim itself.

**Comment by gkaratha** [comment]
Hi all,
Could you please clarify, what you want me to check? I looked at the ouputs there are some warnings but are unrelated to the skimming. I checked all logs, but I did not find any "pass/fail" as i see when I run locally. Thanks in advance.

Best regards,
George Karathanasis

**Comment by kfjack** [comment]
@gkaratha you can find the skim output SkimBPark.root under the directory I mentioned above. Could you check the contents are okay?

**Comment by bainbrid** [comment]
> @gkaratha you can find the skim output SkimBPark.root under the directory I mentioned above. Could you check the contents are okay?

@kfjack please can you specify what checks @gkaratha should perform? Is it as simple as checking that all relevant collections are present in the subset of events that pass the skim?

**Comment by kfjack** [comment]
Hi @bainbrid and @gkaratha, yes, I think one can simply check all of the relevant collections are present, as well as the skimmed events were correctly selected by the designed criteria. This does require @gkaratha (as the author of the skim) to verify. From my side I think everything looks technically okay.

**Comment by gkaratha** [comment]
Dear all, @kfjack ,

Thanks for the clarification!  I checked that the file is healthy. It looks complete all collections seem to be there. I ran the file you proposed the result is here [*]. So it compiles and runs with no issues. In terms of rate the cfg as it is now is made for ~85%  rate reduction. But this is because the cuts are loose. Of course we can (and will) put tighter, depending on what the study show. Thanks.

Best regards,
George



[*] TrigReport Events total = 21 passed = 20 failed = 1

**Comment by kpedro88** [comment]
+upgrade

**Comment by zhenhu** [comment]
+1

**Comment by fabiocos** [comment]
+1

@kfjack thanks for providing a test, at this point #25757 may be closed, as it is embedded here

**Pull request merged**
