### PR TITLE
Update L1T menu tag in MC and relval GTs

### PR DESCRIPTION
**Pull request by francescobrivio**
#### PR description:
This PR updates the L1T menu tag for the 12_4_X MC prouduction campaign, as requested in [this CMSTalk post](https://cms-talk.web.cern.ch/t/run-3-gt-update-of-the-l1-menu-tag-v1-2-0-in-run-3-mc-gts-and-run-3-data-relvals-gts/11830) for Run3 MC GTs and the Run3 relval GTs used for TSG tests.
The new L1T tag is `L1Menu_Collisions2022_v1_2_0_xml`.

*Note:* The GTs `run3_data_relval` and `run3_data` also contain the `SiPixelAliThresholdsHG_offline_v0` tag that was introduced in #38273, but never propagated to `autoCond`.

*Note2:* Both `run3_hlt` and `run3_data` GTs have been updated to have the same snapshot time of `run3_hlt_relval` and `run3_data_relval`, as suggested in https://github.com/cms-sw/cmssw/pull/38438#issuecomment-1160443211.

GT differences:

**Run 3 HLT**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/124X_dataRun3_HLT_frozen_v1/124X_dataRun3_HLT_frozen_v2

**Run 3 HLT RelVals**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/124X_dataRun3_HLT_relval_v2/124X_dataRun3_HLT_relval_v3

**Run 3 data**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/124X_dataRun3_v2/124X_dataRun3_v4

**Run 3 data RelVals**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/124X_dataRun3_relval_v2/124X_dataRun3_relval_v4

**2022 design**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/124X_mcRun3_2022_design_v5/124X_mcRun3_2022_design_v6

**2022 realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/124X_mcRun3_2022_realistic_v5/124X_mcRun3_2022_realistic_v6

**2022 cosmics realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/124X_mcRun3_2022cosmics_realistic_deco_v6/124X_mcRun3_2022cosmics_realistic_deco_v7

**2022 cosmics design**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/124X_mcRun3_2022cosmics_design_deco_v5/124X_mcRun3_2022cosmics_design_deco_v6

**2022 heavy ion**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/124X_mcRun3_2022_realistic_HI_v5/124X_mcRun3_2022_realistic_HI_v6

**2023 realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/124X_mcRun3_2023_realistic_v5/124X_mcRun3_2023_realistic_v6

**2024 realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/124X_mcRun3_2024_realistic_v5/124X_mcRun3_2024_realistic_v6

**Phase 2 realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/124X_mcRun4_realistic_v6/124X_mcRun4_realistic_v7

#### PR validation:
Tested with:
`runTheMatrix.py -l 7.23,159.0,11634.0,12034.0,12434.0,12834.0 --ibeos -j16`

#### Backport:
Not a backport, but a backport to 12_4_X will be provided

FYI: @elfontan @missirol

### CODE REVIEW

**Comment by francescobrivio** [comment]
test parameters:

 - workflows = 7.23,159.0,11634.0,12034.0,12434.0,12834.0

**Comment by tvami** [comment]
urgent

**Comment by tvami** [comment]
type l1t

**Comment by missirol** [comment]
@francescobrivio , thanks for the update. I have one question.

The original idea of the `run3_{hlt,data}_relval` (as far as I understand it) was that that be identical to `run3_{hlt,data}` with the only exception of the L1T-menu tag; with this PR, this wouldn't be the case b/c of IOV differences (and for `run3_data`, also the 1 Pixel tag you mentioned in the PR description).

https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/124X_dataRun3_HLT_frozen_v1/124X_dataRun3_HLT_relval_v3
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/124X_dataRun3_v2/124X_dataRun3_relval_v4

Would it make sense to update (the snapshots of) the `run3_hlt` and `run3_data` GTs every time the `_relval` GTs need to be updated with a new L1T menu?

**Comment by mmusich** [comment]
> Note: The GT 'run3_data_relval' also contains the SiPixelAliThresholdsHG_offline_v0 tag that was introduced in https://github.com/cms-sw/cmssw/pull/38273, but never propagated to autoCond.

would you mind updating also the `run3_data` key? thx

**Comment by francescobrivio** [comment]
@missirol @mmusich thanks for your comments, I'll implement both by the end of today.

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by francescobrivio** [comment]
@cmsbuild please test

  - last commit is now fixed

**Comment by missirol** [comment]
Looks good, thanks @francescobrivio !

https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/124X_dataRun3_HLT_frozen_v2/124X_dataRun3_HLT_relval_v3
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/124X_dataRun3_v4/124X_dataRun3_relval_v4

**Comment by malbouis** [comment]
+alca

- PR according to description
- tests results are clean (apart from the known failures not related to the changes introduced here, MessageLogger and MTD).

**Comment by qliphy** [comment]
+1

**Pull request merged**
