### PR TITLE
[Backport] GEM dataformat - fix classversion

### PR DESCRIPTION
**Pull request by jshlee**
#### PR description:
 - fix classverions for GEMAMC13Status, GEMAMCStatus, GEMOHStatus and GEMVFATStatus 
 - requested from #34585 
 - removed cout from GEMPackingTester 

#### PR validation:
wf 11634.0 and 34611.0

#### Backport
#34713

### CODE REVIEW

**Comment by perrotta** [comment]
backport of #34713

**Comment by jpata** [comment]
@cmsbuild please test

**Comment by civanch** [comment]
+1

**Comment by perrotta** [comment]
@jpata @srimanob the master version of this PR was merged since yesterday. We would like to build pre6 by tomorrow, as all other needed ingredients are there: do you see any further issue, or do you agree signing this PR for pre6 instead?

**Comment by srimanob** [comment]
+Upgrade

Sorry, I missed the backport to 12_0.

**Comment by perrotta** [comment]
+reconstruction
- It just fixes the class version
- Already merged in the master, already signed by reco (and merged) in 11_3: this is the intermediate release and it must stay on synchro

**Comment by perrotta** [comment]
+1

**Comment by perrotta** [comment]
merge

**Pull request merged**
