### PR TITLE
fix det search tollerances for Cosmics

### PR DESCRIPTION
**Pull request by VinInn**
title says all.
CRITICAL FIX.
we are loosing 50% of comics for alignment because of this oversight

### CODE REVIEW

**Comment by VinInn** [comment]
@cmsbuild, please test

**Comment by slava77** [comment]
@VinInn 
Is there a good example run to see that this fixes the reco as desired?

I tried 272932 (this is from May 10, with B=3.8 T) and didn't see as significant effect as you suggest (50%) on 10K events:
- CosmicTP yield changed from 1037 to 1040 events
- CosmicSP yield changed from 59 to 57 events

I see in the inclusive sample about 25% increase in regionalCosmicTracks
all_sign700vsorig_cosmics272932c_log10recotracks_regionalcosmictracks__reco_obj_pt
all_sign700vsorig_cosmics272932c_recotracks_regionalcosmictracks__reco_obj_dxy
all_sign700vsorig_cosmics272932c_recotracks_regionalcosmictracks__reco_obj_dz

The same from SP output:
all_sign700vsorig_cosmics272932spc_log10recotracks_regionalcosmictracks__reco_obj_pt
all_sign700vsorig_cosmics272932spc_recotracks_regionalcosmictracks__reco_objat_size

And in TP:
all_sign700vsorig_cosmics272932tpc_recotracks_regionalcosmictracks__reco_objat_size


The sizeable increase is only in 2-track event yields; the 1-track events haven't increased that much.

Is this roughly the expected improvement?

**Comment by VinInn** [comment]
expected
here for 0T
http://mrovere-dqmgui-slc6.cern.ch:8060/dqm/dev/start?runnr=256259;dataset=/Cosmici/CMSSW_8_0_7/RECO;sampletype=offline_data;filter=all;referencepos=ratiooverlay;referenceshow=all;referenceobj1=other%3A256259%3A/Cosmici/CMSSW_7_6_7/RECO%3A;referenceobj2=other%3A%3A/Cosmici/CMSSW_8_0_X/RECO%3A;referenceobj3=other%3A%3A/Cosmici/CMSSW_8_1_X/RECO%3A;referenceobj4=none;search=;striptype=object;stripruns=;stripaxis=run;stripomit=none;workspace=Everything;size=M;root=Tracking/TrackParameters/GeneralProperties;focus=Tracking/TrackParameters/GeneralProperties/NumberOfValidRecHitsPerTrackVsPhi_CosmicTk;zoom=no;

**Comment by slava77** [comment]
Here are a few more plots from a 0T run Cosmics PD in 269805.
Inclusive first
all_sign700vsorig_cosmics269805c_log10recotracks_regionalcosmictracks__reco_obj_pt

Here is from what passes SP skim
all_sign700vsorig_cosmics269805spc_log10recotracks_regionalcosmictracks__reco_obj_pt

Muons have a much better increase
all_sign700vsorig_cosmics269805c_recomuons_muons__reco_obj_p5

all_sign700vsorig_cosmics269805c_log10recotracks_tevmuons_dyt_reco_obj_pt

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/14467	0c85e7e
- configuration change is in line with the needed fix
- jenkins tests pass and comparisons with baseline show small differences in the cosmics processing workflow 4.22 and also in cosmics-related variables (only in 10021, probably just a rare value to change)
- local tests in CRAFT and CRUZET data confirm expected improvements to a reasonable extent

**Comment by VinInn** [comment]
@boudoul @mmusich 
once integrated we may ask CRUZET rerun

**Comment by boudoul** [comment]
@VinInn : I agree, point taken, I will follow up once integrated

**Comment by mmusich** [comment]
@VinInn thanks a lot.
Two naive questions:
- why do we see that in CRUZET only?
- why haven't we seen it already last year?
Thanks,
Marco

**Comment by VinInn** [comment]
why do we see that in CRUZET only?
  because in CRAFT seeds are triplets and therefore better defined
  (apparently at 0T cosmics are seeded with doublets that are very badly defined)
why haven't we seen it already last year?
   because the affected code is new

**Comment by davidlange6** [comment]
+1

**Pull request merged**
