### PR TITLE
METfilters: fix forth bad EE supercluster

### PR DESCRIPTION
**Pull request by mariadalfonso**
This PR refine one MET filter adding one bad SC to the list. See finding / validation in 
https://hypernews.cern.ch/HyperNews/CMS/get/ecal-performance/839/2/1.html
We aim to have in the 76 re-reco of the data
@schoef

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
Maria,
if I understand correctly, the MET filter decisions are not monitored in DQM/Validation.
If that's correct, why not?

**Comment by mariadalfonso** [comment]
@slava77 @webebermat
Hi Slava. For now in the DQM we have two histograms of pfMET (with the filters applied and not), matthias knows the details. This should be enough for the data quality monitors of the runs. For the release integration do you desire to have histograms to monitor the pass fails for each of the standard filters (HBHE, HBHEIso, EESC, CSCTigh2015)?

**Comment by slava77** [comment]
I think that ta a histogram with filter pass/fail count would be useful
(it could be just one histogram for all filters with pass counts filled; could be separate histograms with 2-bin pass/fail).
Memory-wise, one histogram with a bin per filter would be better.

**Comment by mariadalfonso** [comment]
@slava77 @webermat
ok, the DQM modification you propose can be added in the pending DQM update
https://github.com/cms-sw/cmssw/pull/11539
and in the meanwhile I propose to go with the merging of this PR

**Comment by slava77** [comment]
I checked jenkins outputs and observe no difference.
This just says the problematic cell shows up rarely enough.
This PR has no RECO signature requirement (maybe it eventually should, since this code is a part of RECO+miniAOD workflow).
It looks fine for me.

@davidlange6

**Pull request merged**
