### PR TITLE
L1T offine DQM changes for pp reference run - 92x

### PR DESCRIPTION
**Pull request by thomreis**
Backport of #21188 

To make the L1T offline DQM work for the pp reference run the trigger paths used must be adapted for the pp reference run HLT menu.

This PR includes commit https://github.com/cms-sw/cmssw/pull/21070/commits/d5ae3a6bcd2884185aa5fdd359bf5519d7b20a21 from PR #21070 to get the era "Run2_2017_ppRef".

### CODE REVIEW

**Comment by rekovic** [comment]
please test

**Comment by rekovic** [comment]
please test

**Comment by rekovic** [comment]
+1

**Comment by dmitrijus** [comment]
+1

**Comment by fabozzi** [comment]
+1

**Comment by rekovic** [comment]
please test

**Comment by davidlange6** [comment]
merge

**Pull request merged**
