### PR TITLE
make code pick up HI and PA EGM paths as well 80X

### PR DESCRIPTION
**Pull request by afiqaize**
80X sister PR of #16551.

Cheers,
Afiq

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by franzoni** [comment]
hello @afiqaize

the tests run by @cmsbuild prove your PR is technically sane,
but of course can't include running on pA data from this year. 

Can you run on the collision run from last night :

https://cmswbm.web.cern.ch/cmswbm/cmsdb/servlet/LumiSections?RUN=285090

and check than indeed events pass into the egamma offline dqm ?

Thanks!

**Comment by afiqaize** [comment]
Hi @franzoni 

Can you please point me to instructions running the DQM starting from a RAW file? I tried with the available alcareco samples and while the histograms were properly created, they were not filled, perhaps because the events used to make them had no passing PAEG events.

Cheers,
Afiq

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
