### PR TITLE
pull request subject 

### PR DESCRIPTION
**Pull request by doanhien**
@slava77 
This is the description of pull request:
Adding variable of sigma_ieta_ieta at seeding level for electron in HI reconstruction. The link to describe sigma_ieta_ieta cut is powerful to kill fake electron (which screw up the jet resolution in jet analysis) can be found here: https://twiki.cern.ch/twiki/pub/CMS/PhotonAnalyses2015/20150616.pdf. This variable was added and got PR successfully for 7_6_X. However, we would like to make a back port for 7_5_X since we will use 7_5_X for data taking in heavy ion
the number of the PR in 76X: #10194

Do I need to change the PR subject?

### CODE REVIEW

**Comment by doanhien** [comment]
@lgray 
@slava77 

Is this branch name more sensible than "My" in PR of #10331?

**Comment by slava77** [comment]
Hi Hien,
you should enter something more sensible in the top first line when you submit the PR (you don't need to change the actual name of the branch in the github repo).
Go to the top of the pull request web page, click an "edit" button in the upper right and edit the top like that now says "Backport dev".
After that, please also edit the description of the PR (the block right below the subject line)
There should be a brief description of the change and a link to some slides or some pictures if this change introduces differences in the physics output.
If the changes are for some specialized analysis setup, it needs to be mentioned.

Thank you.

**Comment by slava77** [comment]
BTW, at this point the branch has merge conflicts.

**Comment by slava77** [comment]
So, I was asking for something really brief in the top one-line "pull request subject" and a longer description in the larger available block right below it (the latter still has a somewhat non-descript "backport to 7_5_X", while the former contains more than about a line of text.
Please correct.

... beyond this cosmetics, the pull request was submitted to a wrong branch (76X as it stands now).
This one should be closed and the 75X version created. [I'm deriving that this is actually for 75X from the message "backport to 7_5_X")

**Comment by doanhien** [comment]
@slava77 
Hi,

I put the description here. Is it correct?
Adding variable of sigma_ieta_ieta at seeding level for electron in HI reconstruction. The link to describe sigma_ieta_ieta cut is powerful to kill fake electron (which screw up the jet resolution in jet analysis) can be found here: https://twiki.cern.ch/twiki/pub/CMS/PhotonAnalyses2015/20150616.pdf. This variable was added and got PR successfully for 7_6_X. However, we would like to make a back port for 7_5_X since we will use 7_5_X for data taking in heavy ion

**Comment by slava77** [comment]
Hi Hien,

Thank you for the details. It's a start.
Please provide the number of the PR in 76X as well.

The PR subject (the top line) is now " pull request subject ". It should be changed.
The longer description should go right below it (it now says "backport to 7_5_X"). There is a pen-like edit button in every post that you make on github.

**Comment by slava77** [comment]
-1

Thank you for updating the PR description.

now, what remains is
- change the PR subject from "pull request subject" to something descriptive
- submit this PR appropriately to 75X (it was made to 76X, which is the reason for the merge conflicts)

**Comment by davidlange6** [comment]
i agree with @slava77's plan - so I'll close this

**Comment by doanhien** [comment]
@slava77 

Hi Slava,

Can I change this PR to 75X here or I have to resubmit this with 75X?

Thanks,

**Comment by slava77** [comment]
@doanhien
target branch reassignment is not possible. Please update #10331 or create a new PR

**Comment by lgray** [comment]
@doanhien Can you please click the "close pull request" button at the bottom of the webpage? :-)

**Pull request closed without merging**
