### PR TITLE
Thread safe piliup histogram for mixing

### PR DESCRIPTION
**Pull request by civanch**
Addressing issue #21972 , implemented as suggested by @Dr15Jones .
Magically, it peaks up already merged #21967 but it seems that this is correct.

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by Dr15Jones** [comment]
+1
For the already merged piece from the framework

**Comment by civanch** [comment]
+1

**Comment by fabiocos** [comment]
@civanch I suspect you picked unrelated stuff with a merge. Could you please clean the PR so as we avoid duplicated additions?

**Comment by civanch** [comment]
#22000 is created, this one will be closed.
@fabiocos , do we need a copy for 10_0_X?

**Comment by fabiocos** [comment]
@civanch I would say so

**Pull request closed without merging**
