### PR TITLE
[121X] include GTs for Pilot Beam Test

### PR DESCRIPTION
**Pull request by malbouis**
#### PR description:

This PR is a forward port of PR #35561 that includes the online GTs for datataking and updates the DQM unit tests to use a 2021 CRUZET run. 

As it was suggested at the AlCaDB workshop (https://indico.cern.ch/event/1069946/contributions/4511740/attachments/2313276/3937722/Condition%20Database_%20Approaching%20Run3.pdf), we are planning to replace the most populated tags (> 50k) with a new tag in the Run 3 Prompt GT, due to better performance and manageability. In this PR, the newly introduced 120X Run 3 Prompt GT has a new such tag, EcalLaserAPDPNRatiosRcd, that is only valid starting from Run3 data. It was discussed and agreed upon also with the Ecal group.

In summary, the Run 3 Prompt GTs introduced in this PR are only valid for Run 3 data.

GT differences wrt CRUZET ones:
HLT:
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/113X_dataRun3_HLT_v3/120X_dataRun3_HLT_v3
Express:
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/113X_dataRun3_Express_v4/120X_dataRun3_Express_v2
Prompt:
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/113X_dataRun3_Prompt_v3/120X_dataRun3_Prompt_v2

The hypernews with the announcement of the Pilot Test Beam GTs is here: https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/4488.html

#### PR validation:

Just as a sanity check as we do not expect to catch the errors that showed up in DQM online:

runTheMatrix.py -l 138.1,138.2 --ibeos -j8 

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

It is a forward port of #35561.

### CODE REVIEW

**Comment by malbouis** [comment]
@cmsbuild , please test with #35550

**Comment by tvami** [comment]
test parameters:
  - pull_request  = https://github.com/cms-sw/cmssw/pull/35600

**Comment by tvami** [comment]
test parameters:
  - pull_request  = https://github.com/cms-sw/cmssw/pull/35600, https://github.com/cms-sw/cmssw/pull/35550

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
+alca

**Comment by perrotta** [comment]
> > @malbouis @tvami should this really get merged together with #35550, as you are [requesting](https://github.com/cms-sw/cmssw/pull/35561#issuecomment-939304592) for the 12_0_X version of this PR? I notice that the last tests run without #35550 ended up succesfully, while the previous ones made together with that PR showed several errors instead...
> 
> Hi @perrotta the last tests run with #35593, #35600 and #35550 as fas as I can tell from https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-5be715/19525/summary.html

Ah, ok, correct: I overlooked https://github.com/cms-sw/cmssw/pull/35593#issuecomment-939324336

Still I would like to know about correlations with the other PRs, and get a guidance about the needed order of mergings (or an indication about which ones must be merged together)ones

**Comment by missirol** [comment]
To make the HLT tests pass, I think #35600 (or something equivalent) should be merged before this PR.

**Comment by francescobrivio** [comment]
> Just noting here for the casual future reader: the update in `EcalLaserAPDPNRatiosRcd` (and others) proposed in the Prompt Reco Global Tag update here, squarely breaks the fairly convenient feature of having a Prompt Reco Global Tag in `autoCond` which is "guaranteed" to work for whatever real data past run.
> 
>     * Would it be possible to document in the PR description that you are introducing such a breaking point so that it is immediately visibile?

Hi @mmusich is this "guarantee" an actual policy? _i.e._ is it stated explicitely somewhere and people are counting on it? The breaking of these tags was proposed by @ggovi during the AlCaDB workshop ([indico contribution](https://indico.cern.ch/event/1069946/#28-conditions-db)).

> On a related note, I read in [#35600 (comment)](https://github.com/cms-sw/cmssw/pull/35600#issuecomment-939865508) that having more 50k IOVs the tag `EcalLaserAPDPNRatios_prompt_v2` had become hardly manageable. As far as I know there are other tags in the Prompt Reco Global Tag with similar sizes of IoV lists (e.g. `SiStripDetVOff_v6_prompt` has 48842 IoVs, `BeamSpotObjects_PCL_byLumi_v0_prompt` has 103220 IoVs, etc. ).
> 
>     * Could you elaborate more on the issue? Shall one expect similar "cuts" for other records?

Indeed we have a list of tags which have >50k IOVs, it's around 10 tags and some of them are for the UL offline reco, so they won't see any new append. The plan was to split the other ones (used in "online" GTs) after the Pilot Beam test in Novemeber in preparation for Run3.

**Pull request merged**
