### PR TITLE
Fix for FastSim: HltBtagValidation: make the InPutTag for SimVertices configurable.

### PR DESCRIPTION
**Pull request by lveldere**
Make the InPutTag for SimVertices configurable.
Implement correct cfg for SimVertices for FastSim and FullSim

Same changes to HLTriggerOffline as in  #8455

### CODE REVIEW

**Comment by lveldere** [comment]
please test

**Comment by lveldere** [comment]
I believe this error is not related to my pr

**Comment by lveldere** [comment]
please test

**Comment by lveldere** [comment]
@danduggan, @nclopezo, @deguio

Hi All

Could you have a look and let me know if any changes are required?
This PR is rather urgent for FastSim.

Lukas

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
