### PR TITLE
TOoLLiP integration

### PR DESCRIPTION
**Pull request by ddiaz006**
#### PR description:
* Add ML-based LLP Jet tagger to Phase-2 Level-1 trigger emulator; codenamed TOoLLiP
* Requires TOoLLiP external integrated here: https://github.com/cms-sw/cmsdist/pull/8906
* Compiled object file added under L1Trigger/Phase2L1ParticleFlow/test until above PR is approved
* Presented at L1 Tau-Jets-MET meetings, e.g. 
  * https://indico.cern.ch/event/1288096/#9-llp-jet-tagging-status-and-p
  * https://indico.cern.ch/event/1350143/contributions/5683985/
* This model represents a v1 baseline with post-training quantization. We expect to update it with a more realistic firmware implementation.
* Model and expected performance plots shown here: https://github.com/cms-hls4ml/TOoLLiP/blob/main/README.md
* L1T Offline PR: https://github.com/cms-l1t-offline/cmssw/pull/1195
* TOoLLiP in cms-hls4ml : https://github.com/cms-hls4ml/TOoLLiP

#### PR validation:

In progress

### CODE REVIEW

**Comment by epalencia** [comment]
Please test with https://github.com/cms-sw/cmsdist/pull/8906

**Comment by smuzaffar** [comment]
@ddiaz006 , https://github.com/cms-sw/cmsdist/pull/8906 is merged and new library will be available in 12-23-2300 IB. 
Please cleanup this PR and remove the `L1Trigger/Phase2L1ParticleFlow/test/TOoLLip_emulator_v1.so` shared library from history. You need to delete it and squash the changes to get rid of this library

**Comment by aloeliger** [comment]
@ddiaz006 You made a commit deleting the `.so`, however it is still in the history (i.e. there is some commit I could checkout where the `.so` still exists). You will need to squash all these changes together to fully remove it (A quick google comes up with this: https://www.git-tower.com/learn/git/faq/git-squash, I usually do some soft reset thing but this seems more reliable).

On a picky note, I see you have added the TOoLLiP model to https://github.com/cms-hls4ml, could you just quickly edit the description to provide a quick link to that for everyone?

Has the addition of this emulator been discussed beyond the L1 Tau-Jet-MET group?

**Comment by aloeliger** [comment]
@ddiaz006 Just a ping on any developments here.

**Comment by ddiaz006** [comment]
> @ddiaz006 Just a ping on any developments here.

Hi @aloeliger I have attempted the rebase, however the commits do not appear merged in the PR. They do appear merged in when I check git reblog however, I am trying to solve this.

```
369332658f7 (HEAD -> TOoLLip-integration, my-cmssw/TOoLLip-integration) HEAD@{0}: pull my-cmssw TOoLLip-integration: Merge made by the 'ort' strategy.
fcfe4639108 HEAD@{1}: rebase (finish): returning to refs/heads/TOoLLip-integration
fcfe4639108 HEAD@{2}: rebase (squash): Modify L1BJetProducer.cc to use JetID, change BJetID to JetID
7e532ba801d HEAD@{3}: rebase (squash): # This is a combination of 4 commits.
5c955633955 HEAD@{4}: rebase (squash): # This is a combination of 3 commits.
2adff285f28 HEAD@{5}: rebase (squash): # This is a combination of 2 commits.
fb7be8f1b79 HEAD@{6}: rebase (start): checkout HEAD~5
13e5fe96c36 HEAD@{7}: pull my-cmssw TOoLLip-integration: Fast-forward
3c1d656af86 HEAD@{8}: commit: code check updates
b415b1cb3bd HEAD@{9}: commit: adding producer, everything compiles
fb7be8f1b79 HEAD@{10}: commit: Modify L1BJetProducer.cc to use JetID, change BJetID to JetID
dc08b703a1c HEAD@{11}: commit: add JetID
deaac86743f (tag: CMSSW_14_0_X_2023-12-21-1100, tag: CMSSW_14_0_X_2023-12-20-2300, tag: CMSSW_14_0_X_2023-12-20-1100, tag: CMSSW_14_0_X_2023-12-19-2300, tag: CMSSW_14_0_UBSAN_X_2023-12-20-2300, tag: CMSSW_14_0_ROOT6_X_2023-12-20-2300, tag: CMSSW_14_0_ROOT6_X_2023-12-19-2300, tag: CMSSW_14_0_ROOT628_X_2023-12-20-2300, tag: CMSSW_14_0_ROOT628_X_2023-12-19-2300, tag: CMSSW_14_0_ROOT626_X_2023-12-21-1100, tag: CMSSW_14_0_ROOT626_X_2023-12-20-2300, tag: CMSSW_14_0_ROOT626_X_2023-12-20-1100, tag: CMSSW_14_0_ROOT626_X_2023-12-19-2300, tag: CMSSW_14_0_NONLTO_X_2023-12-21-1100, tag: CMSSW_14_0_NONLTO_X_2023-12-20-2300, tag: CMSSW_14_0_NONLTO_X_2023-12-20-1100, tag: CMSSW_14_0_NONLTO_X_2023-12-19-2300, tag: CMSSW_14_0_GPU_X_2023-12-20-2300, tag: CMSSW_14_0_GPU_X_2023-12-19-2300, tag: CMSSW_14_0_GEANT4_X_2023-12-20-2300, tag: CMSSW_14_0_G4VECGEOM_X_2023-12-20-2300, tag: CMSSW_14_0_DEVEL_X_2023-12-20-2300, tag: CMSSW_14_0_DEVEL_X_2023-12-19-2300, tag: CMSSW_14_0_CUDART_X_2023-12-20-2300, tag: CMSSW_14_0_CLANG_X_2023-12-20-2300, tag: CMSSW_14_0_CLANG_X_2023-12-19-2300, tag: CMSSW_14_0_ASAN_X_2023-12-20-2300, from-CMSSW_14_0_X_2023-12-20-2300) HEAD@{12}: checkout: moving from from-CMSSW_14_0_X_2023-12-20-2300 to TOoLLip-integration
deaac86743f (tag: CMSSW_14_0_X_2023-12-21-1100, tag: CMSSW_14_0_X_2023-12-20-2300, tag: CMSSW_14_0_X_2023-12-20-1100, tag: CMSSW_14_0_X_2023-12-19-2300, tag: CMSSW_14_0_UBSAN_X_2023-12-20-2300, tag: CMSSW_14_0_ROOT6_X_2023-12-20-2300, tag: CMSSW_14_0_ROOT6_X_2023-12-19-2300, tag: CMSSW_14_0_ROOT628_X_2023-12-20-2300, tag: CMSSW_14_0_ROOT628_X_2023-12-19-2300, tag: CMSSW_14_0_ROOT626_X_2023-12-21-1100, tag: CMSSW_14_0_ROOT626_X_2023-12-20-2300, tag: CMSSW_14_0_ROOT626_X_2023-12-20-1100, tag: CMSSW_14_0_ROOT626_X_2023-12-19-2300, tag: CMSSW_14_0_NONLTO_X_2023-12-21-1100, tag: CMSSW_14_0_NONLTO_X_2023-12-20-2300, tag: CMSSW_14_0_NONLTO_X_2023-12-20-1100, tag: CMSSW_14_0_NONLTO_X_2023-12-19-2300, tag: CMSSW_14_0_GPU_X_2023-12-20-2300, tag: CMSSW_14_0_GPU_X_2023-12-19-2300, tag: CMSSW_14_0_GEANT4_X_2023-12-20-2300, tag: CMSSW_14_0_G4VECGEOM_X_2023-12-20-2300, tag: CMSSW_14_0_DEVEL_X_2023-12-20-2300, tag: CMSSW_14_0_DEVEL_X_2023-12-19-2300, tag: CMSSW_14_0_CUDART_X_2023-12-20-2300, tag: CMSSW_14_0_CLANG_X_2023-12-20-2300, tag: CMSSW_14_0_CLANG_X_2023-12-19-2300, tag: CMSSW_14_0_ASAN_X_2023-12-20-2300, from-CMSSW_14_0_X_2023-12-20-2300) HEAD@{13}: checkout: moving from CMSSW_14_0_X to from-CMSSW_14_0_X_2023-12-20-2300
9fca027cd9b (tag: CMSSW_14_0_X_2023-12-22-1100, tag: CMSSW_14_0_X_2023-12-21-2300, tag: CMSSW_14_0_SKYLAKEAVX512_X_2023-12-21-2300, tag: CMSSW_14_0_ROOT6_X_2023-12-21-2300, tag: CMSSW_14_0_ROOT628_X_2023-12-21-2300, tag: CMSSW_14_0_ROOT626_X_2023-12-22-1100, tag: CMSSW_14_0_ROOT626_X_2023-12-21-2300, tag: CMSSW_14_0_NONLTO_X_2023-12-22-1100, tag: CMSSW_14_0_NONLTO_X_2023-12-21-2300, tag: CMSSW_14_0_GPU_X_2023-12-21-2300, tag: CMSSW_14_0_DEVEL_X_2023-12-21-2300, tag: CMSSW_14_0_DBG_X_2023-12-21-2300, tag: CMSSW_14_0_CPP20_X_2023-12-22-1100, tag: CMSSW_14_0_CLANG_X_2023-12-21-2300, tag: CMSSW_14_0_0_pre2, official-cmssw/master, official-cmssw/HEAD, official-cmssw/CMSSW_14_0_X, CMSSW_14_0_X) HEAD@{14}: clone: from https://github.com/cms-sw/cmssw.git
```

**Comment by epalencia** [comment]
Please test

**Comment by aloeliger** [comment]
@ddiaz006 Has this PR received all the upgrades that went into https://github.com/cms-l1t-offline/cmssw/pull/1213? If not, please ensure those commits end up here.

**Comment by ddiaz006** [comment]
Hello, I attempted to sync this PR with the one that I have open for the l1tOffline-cmssw: https://github.com/cms-l1t-offline/cmssw/pull/1213. However, it appears that I pulled in some additional changes. Please let me know how to proceed. Should I rebase this with respect to a new target?

**Comment by aloeliger** [comment]
@ddiaz006 please take a look at https://cms-sw.github.io/tutorial-resolve-conflicts.html under "Recovering from a bad rebase (or merge)". You may need to rebase to a more current IB, or just cherry-pick commits.

**Comment by ddiaz006** [comment]
Ok, I have synced this branch with the changes made in the l1toffline CMSSW. The PR in l1toffline was approved and merged yesterday:https://github.com/cms-l1t-offline/cmssw/pull/1213

**Comment by epalencia** [comment]
Please test

**Comment by ddiaz006** [comment]
Is this to be merged in the next IB? Please let me know if I need to complete any further checks.

**Comment by aloeliger** [comment]
+l1

**Comment by subirsarkar** [comment]
+Upgrade

**Comment by rappoccio** [comment]
+1

**Pull request merged**
