### PR TITLE
Fastsim: remove gen mixing from famosproducer

### PR DESCRIPTION
**Pull request by lveldere**
gen-mixing is no longer supported

### CODE REVIEW

**Comment by lveldere** [comment]
please test

**Comment by lveldere** [comment]
please test

**Comment by lveldere** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Comment by davidlt** [comment]
This caused CMSSW breakage in a number of tests/RelVals.
```
Traceback (most recent call last):
  File "/build/cmsbuild/jenkins-workarea/workspace/validate-any-ib/cms/slc6_amd64_gcc491/cms/cmssw/CMSSW_7_6_DEVEL_X_2015-06-26-1100/bin/slc6_amd64_gcc491/cmsDriver.py", line 43, in 
    run()
  File "/build/cmsbuild/jenkins-workarea/workspace/validate-any-ib/cms/slc6_amd64_gcc491/cms/cmssw/CMSSW_7_6_DEVEL_X_2015-06-26-1100/bin/slc6_amd64_gcc491/cmsDriver.py", line 15, in run
    configBuilder.prepare()
  File "/build/cmsbuild/jenkins-workarea/workspace/validate-any-ib/cms/slc6_amd64_gcc491/cms/cmssw/CMSSW_7_6_DEVEL_X_2015-06-26-1100/python/Configuration/Applications/ConfigBuilder.py", line 2171, in prepare
    self.pythonCfgCode += self.addCustomise()
  File "/build/cmsbuild/jenkins-workarea/workspace/validate-any-ib/cms/slc6_amd64_gcc491/cms/cmssw/CMSSW_7_6_DEVEL_X_2015-06-26-1100/python/Configuration/Applications/ConfigBuilder.py", line 858, in addCustomise
    self.process=getattr(package,fcn)(self.process)
  File "/build/cmsbuild/jenkins-workarea/workspace/validate-any-ib/cms/slc6_amd64_gcc491/cms/cmssw/CMSSW_7_6_DEVEL_X_2015-06-26-1100/python/SLHCUpgradeSimulations/Configuration/postLS1Customs.py", line 49, in customisePostLS1
    process = customisePostLS1_Common(process)
  File "/build/cmsbuild/jenkins-workarea/workspace/validate-any-ib/cms/slc6_amd64_gcc491/cms/cmssw/CMSSW_7_6_DEVEL_X_2015-06-26-1100/python/SLHCUpgradeSimulations/Configuration/postLS1Customs.py", line 13, in customisePostLS1_Common
    process = customise_fastSimPostLS1(process)
  File "/build/cmsbuild/jenkins-workarea/workspace/validate-any-ib/cms/slc6_amd64_gcc491/cms/cmssw/CMSSW_7_6_DEVEL_X_2015-06-26-1100/python/SLHCUpgradeSimulations/Configuration/fastSimCustoms.py", line 8, in customise_fastSimPostLS1
    from FastSimulation.PileUpProducer.PileUpFiles_cff import puFileNames_13TeV
ImportError: No module named PileUpProducer.PileUpFiles_cff
```

CMSSW wasn't fully cleaned.
```
$ git grep PileUpFiles_cff
FastSimulation/Configuration/python/MixingModule_Full2Fast.py:    from FastSimulation.PileUpProducer.PileUpFiles_cff import puFileNames
FastSimulation/PileUpProducer/python/PileUpProducer_cff.py:from FastSimulation.PileUpProducer.PileUpFiles_cff import puFileNames
SLHCUpgradeSimulations/Configuration/python/fastSimCustoms.py:    from FastSimulation.PileUpProducer.PileUpFiles_cff import puFileNames_13TeV
```

**Comment by lveldere** [comment]
Thanks David

I cleaned SLHCUpgradeSimulations/Configuration/python/fastSimCustoms.py.
See #9948

The other things listed by =git grep PileUpFiles_cff= were already taken
care of by the original pr.

Cheers

Lukas

**Pull request merged**
