### PR TITLE
wide Z and remove offline bs

### PR DESCRIPTION
**Pull request by sushilchauhan**
added protection with wide z window for seeding in case of bad input beam spot and removed use of offline beam spot in dqm beammonitor code.

### CODE REVIEW

**Comment by deguio** [comment]
@sushilchauhan 
please submit this PR to 75x, 76x and 80x as well.
if you plan to add commits on top of this you can do that in one go at the end.

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
@sushilchauhan please let us know if you can submit to 75, 76 and 80 or if you want to add updates.
thanks,
F.

**Comment by sushilchauhan** [comment]
I am testing for heavy ions so there could be updates in next few days.
Thanks,-sushil

**Comment by deguio** [comment]
ciao @sushilchauhan 
are there news here? thanks in advance,
F.

**Comment by sushilchauhan** [comment]
I am discussing it with HI group and should be able to submit it by tomorrow evening after finalizing few parameters in configuration file

**Comment by deguio** [comment]
ok, thanks.
F.

**Comment by sushilchauhan** [comment]
We are still testing PbPb update in 74X and it may take some more time. As I understand for PbPb 75X(?) will be used so we have already submitted a request #12410 along with these change in 75X. I am not sure if you want to wait for a new pr for 74X before approving this one(?).

**Comment by deguio** [comment]
+1

**Pull request closed without merging**
