### PR TITLE
MTD geometry: remove thermal screen from ETL D53

### PR DESCRIPTION
**Pull request by fabiocos**
#### PR description:

This PR, based on the work by @icosivi as discussed and agreed with @bsunanda and N. Koss, removes from the ETL TDR description as implemented in scenario D53 the front thermal screen, which is already included in the volume outside ```EndcapTimingLayer```.

I have taken the opportunity to move the main volume from a polycone to a tubs (i.e. a cyclindrical shell), which is simpler for the geometry navigation.

This PR fully embeds #29647, it may be rebased after the integration of that.

#### PR validation:

@icosivi has verified the positions and checked that no overlap is present after this update. I have checked that the volume paths and DetIds are identical after the update (as they should), just longitudinal positions are shifted along z (as expected). The initial part of the dump differences is:

```
6815271a6815272
>  - OCMS[0]/CMSE[1]/CALO[1]/CALOEC[1]/CALOECTSFront[1]/CALOECFront[1]/EndcapTimingLayer[1]/ThermalScreen[1]/
6815298c6815299
< Translation vector components:   -1121.500000      22.925000    2994.325000 
---
> Translation vector components:   -1121.500000      22.925000    3011.325000 
6815300c6815301
< Center global   =   -1121.500000     22.925000   2994.325000 r =    1121.734285 phi =     178.828959
---
> Center global   =   -1121.500000     22.925000   3011.325000 r =    1121.734285 phi =     178.828959
6815302c6815303
< Corner 1 global =   -1110.900000     43.925000   2994.350000 DeltaR =      23.523618
---
> Corner 1 global =   -1110.900000     43.925000   3011.350000 DeltaR =      23.523618
```

### CODE REVIEW

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
abort

**Comment by fabiocos** [comment]
hold

**Comment by fabiocos** [comment]
The latest fix is needed to avoid an overlap with the mother volume, not present in the version with the polycone by @icosivi . The g4OverlapsCheck shows no issue.

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
rebased on latest version of #29647

**Comment by fabiocos** [comment]
unhold

**Comment by fabiocos** [comment]
please test

**Comment by kpedro88** [comment]
+upgrade

**Comment by cvuosalo** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
