### PR TITLE
Update and cleaning of BPH trigger DQM/RelVal code and plots

### PR DESCRIPTION
**Pull request by vjmastra**
**PR description:**

Update DQM and RelVal code for BPH Trigger plots to take into account new triggers (eg inclusive dimuon trigger HLT_DoubleMuon4_3_LowMass_v), few changes in path names and cleaning of empty plots and corresponding code

Code has been cleaned after discussion in [#39768](https://github.com/cms-sw/cmssw/pull/39768)

Short report in STEAM meeting: https://indico.cern.ch/event/1180797/#17-b-physics-quarkonia-pag

**PR validation:**

Code has been tested following [twiki](https://twiki.cern.ch/twiki/bin/viewauth/CMS/HLTValidationAndDQM#CMSSW_12_4_X_on_Run3_MC) in CMSSW 12_6_0_pre3 on a BuMixing RelVal [file](https://cmsweb.cern.ch/das/request?input=file%3D%2Fstore%2Frelval%2FCMSSW_12_6_0_pre2%2FRelValBuMixing_14%2FGEN-SIM-DIGI-RAW%2F125X_mcRun3_2022_realistic_v3-v1%2F2580000%2F0a16f6be-0412-493b-b8ee-ca62d9e6da98.root&instance=prod/global)

Recent output file: https://cernbox.cern.ch/s/NdDOJBWrwBwznzT
Previous output file: /afs/cern.ch/user/v/vmastrap/public/bph-dqm-12_6_0_pre3/DQM_V0001_R000000001__Global__CMSSW_X_Y_Z__RECO.root

**If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:**

Previously asking for backporting in [12_4](https://github.com/cms-sw/cmssw/pull/39979) and [12_5](https://github.com/cms-sw/cmssw/pull/39980), 
but not needed anymore

### CODE REVIEW

**Comment by emanueleusai** [comment]
please test

**Comment by emanueleusai** [comment]
+1

**Comment by vjmastra** [comment]
> @vjmastra I understood that this PR should have just removed unneeded commented out lines. I see a few additional lines, i.e. a few additionas histos added with respect to what was run lastly in the online DQM: was it done on purpose? What are those extra histos intended to?

Hi, the added plots are "resurrected" from some commented code. The histograms are trigger efficiencies for muons and dimuons wrt rapidity, which are useful as there are triggers that include selection with a cut in rapidity of the muon pair (rather than on the muons' pseudorapidity individually - monitored with already available plots)

**Comment by perrotta** [comment]
+1

**Pull request merged**
