### PR TITLE
Run2-gex132A Restore the names GeometryExtended2017 to let the unit tests to succeed

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Restore the names GeometryExtended2017 to let the unit tests to succeed..  2017 is a copy of 2017Plan1. Also changed 2018 to 2018Plan0 and copy 2018Plan36 as 2018. These actions came after discussion at the SIM meeting on April 22,2022\

### PR validation:

Use the runTheMatrix test workflows 

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@civanch @cvuosalo @srimanob @perrotta @qliphy This will resolve the unit test issue

**Comment by qliphy** [comment]
type bugfix

**Comment by srimanob** [comment]
I think the PR makes confusion:
+ Restoring happen only for 2017 (bring back GeometryExtended2017_cff.py)
+ Following the plan presented in SIM meeting (https://indico.cern.ch/event/1153217/contributions/4842354/attachments/2429679/4163061/Sim-Talk146.pdf), slide 5, we should have  `GeometryExtended2017_cff` anyways from 2017Plan1. If this is the case, will this PR is just temporary until the new one will be available?
+ If nothing to do with 2018 for `bug-fix` type, e.g. fix unit test, I propose we remove 2018 out from the PR.

**Comment by bsunanda** [comment]
In the meeting we decided to have 2017(Reco)_cff and 2018(Reco)_cff to reflect the default seetings of the year which are copies of Plan1 and Plan36 respectively. The new PR's which will match the dd4hep version will be called 201XY(Reco)_cff with X = 7 or 8 and Y = DDD for DDD version and DD4hep for the other version. Accordingly 2 PR's are submittied.

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by srimanob** [comment]
Hi @bsunanda 
I mean this PR fixes the unit test issue by bring back only GeometryExtended2017_cff. The PR title and description makes it sound like we are missing both 2017 and 2018.

**Comment by civanch** [comment]
+1

**Comment by bsunanda** [comment]
@srimanob Please approve this

**Comment by srimanob** [comment]
+Upgrade

This PR fixes the unit test issue on Run-2 2017 geometry. It also includes an update on 2018 XML. We should not see any changes in PR test as Run-2 wf runs with geometry in DB, not in XML.

**Comment by qliphy** [comment]
+1

**Pull request merged**
