### PR TITLE
Fix EvtGenInterface report instruction to comply with evtgen 1.4.

### PR DESCRIPTION
**Pull request by ghost**
Must go in with cms-sw/cmsdist#1777
@mkirsano @smuzaffar @davidlt @davidlange6

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by mkirsano** [comment]
@degano thanks for taking care of this

**Comment by degano** [comment]
@davidlange6 @bendavid Do we care about this update?

**Comment by davidlange6** [comment]
also note that we have this EvtGen related failure in the IBs

https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc6_amd64_gcc493/CMSSW_7_6_X_2015-09-02-1100/pyRelValMatrixLogs/run/521.0_TT_13TeV_pythia8-evtgen+TT_13TeV_pythia8-evtgen+HARVESTGEN/step1_TT_13TeV_pythia8-evtgen+TT_13TeV_pythia8-evtgen+HARVESTGEN.log

**Comment by covarell** [comment]
+1

**Comment by covarell** [comment]
@davidlange6 , RelVal workflow 521 will be removed after merging #11004 (presented at last ORP, but still marked as orp-pending). This should fix the problem, new EvtGen workflows have been tested locally

**Pull request merged**
