### PR TITLE
Fireworks/Core : Changes needed to compile with macOS clang and libc++

### PR DESCRIPTION
**Pull request by gartung**

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
@smuzaffar are you OK with these BuildFile.xml changes?

**Comment by alja** [comment]
+1

**Comment by smuzaffar** [comment]
@Dr15Jones , for now, these changes are fine but we should add a rootgx11 toolfile instead of directly linking against the library here.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
