### PR TITLE
Fixed YE3 problem

### PR DESCRIPTION
**Pull request by slomeo**
#### PR description:

Fixed YE3 (muonYoke.xml) inaccuracy for Scenario 2021
(see https://indico.cern.ch/event/894617/ )

From 22.28 cm to 23.2 cm as indicated in https://indico.cern.ch/event/61929/contributions/2053825/attachments/1002771/1426455/diskampchamber_data.pdf by @ptcox

### CODE REVIEW

**Comment by fabiocos** [comment]
please test

**Comment by cvuosalo** [comment]
@namapane Please note magnetic field changes in this PR.

**Comment by cvuosalo** [comment]
+1

**Comment by namapane** [comment]
> 
> 
> @namapane Please note magnetic field changes in this PR.

Actually not... I guess you refer to  Geometry/MuonCommonData/data/mf/2021/v2/mf.xml ?
I don't know what this is intended to be, but definitely it is not used for the magnetic field.

**Comment by civanch** [comment]
@kpedro88 , this PR was approved in the today general muon meeting.

**Comment by cvuosalo** [comment]
@namapane I understand you and Sergio are discussing the magnetic field, so that's all I wanted.

**Comment by slomeo** [comment]
@kpedro88 @civanch : For Phase II which Scenario2026 do I have to modify to add the new value of the YE3 thickness? My next step will be to fix the "Hidden Overlaps" for the Muon System (Scenario2021) but after that I'll start again with dd4hep and Phase II.

**Comment by kpedro88** [comment]
@sergio Phase 2 geometries that have already been used for production cannot be modified. These are: D35 (M2), D41 (M3), and D49 (M4). https://github.com/cms-sw/cmssw/tree/master/Configuration/Geometry

Therefore, there are not any Phase 2 muon geometries that are still considered "in development" and open for editing. This would have to be added as a new M5 with a corresponding new detector scenario to test it. I recommend combining this small change with any other developments from the muon system (e.g. GEM/ME0 merger).

**Comment by silviodonato** [comment]
+1

**Pull request merged**
