### PR TITLE
[12.4.X] fix GeometryProducer and G4e examples

### PR DESCRIPTION
**Pull request by mmusich**
resolves https://github.com/cms-sw/cmssw/issues/38739

#### PR description:

Should work for all Eras and geometry models.
The propagator "old" test needs a "refresh": it was based on the early use of Geane for Muon reconstruction that has been obsoleted years ago. It cannot even work at the moment as current propagator is limited to 2m

#### PR validation:

Relies on the unit tests implemented in this PR.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

   * Almost verbatim backport of https://github.com/cms-sw/cmssw/pull/38864 (unit test input file needs to be from 12.4.X) .
   * Needed for Tracker Alignment purposes.

### CODE REVIEW

**Comment by mmusich** [comment]
backport of https://github.com/cms-sw/cmssw/pull/38864

**Comment by mmusich** [comment]
type tracking

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
