### PR TITLE
Add Pythia8 UserHook for Resonance decay filtering (71x)

### PR DESCRIPTION
**Pull request by bendavid**
Backport of https://github.com/cms-sw/cmssw/pull/12901

### CODE REVIEW

**Comment by bendavid** [comment]
Fix is still needed here as well.

**Comment by bendavid** [comment]
Ok, now fixed here as well.

**Comment by covarell** [comment]
+1

**Comment by bendavid** [comment]
Added deletion of pointer as for 80x

**Comment by govoni** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
