### PR TITLE
Phase2-329C Remove all obsolete files relevant to FastTimerGeoemtry from HGCal related projects

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Remove all obsolete files relevant to FastTimerGeoemtry from HGCal related projects. The relevant files for fast Tim detectors are in the MTD package

#### PR validation:

Use the runTheMatrix test workflows

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
+geometry

**Comment by bsunanda** [comment]
@srimanob Please approve this

**Comment by rappoccio** [comment]
+1

technical PR.

**Pull request merged**
