### PR TITLE
Don't use uninitialized edm::Handle in TrackstersProducer

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

Dereferencing an uninitialized edm::Handle leads to dereference of a nullptr which is undefined behavior. Rearranged code to avoid using edm::Handles at all.

This was found by #30928.
#### PR validation:

Built together with #30928 and then ran workflow 23234.0. Previously that pull request failed that workflow but now it succeeds.

### CODE REVIEW

**Comment by silviodonato** [comment]
Some differences in the comparison test are expected from https://github.com/cms-sw/cmssw/pull/30999#issuecomment-667611395

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/31035	bd0cf42 
- technical
- jenkins tests pass

**Comment by Dr15Jones** [comment]
ping @kpedro88

**Comment by kpedro88** [comment]
+upgrade

**Pull request merged**
