### PR TITLE
Utilities/StaticAnalyzers: Add CMS_SA_ALLOW exceptions on Static Analyzer checks involving Decls.

### PR DESCRIPTION
**Pull request by gartung**
Allows the user of cms threads safety macro CMS_SA_ALLOW in declarations that should be allowed to suppress the warning associated with the static analyzer check. This is done to reduce the volume of warnings in the static analyzer reports.

### CODE REVIEW

**Comment by gartung** [comment]
@Dr15Jones

**Comment by Dr15Jones** [comment]
@gartung could you give an example, as a comment in this pull request, on what new declarations can be marked?

**Comment by gartung** [comment]
```

class Foo
{
public:
    // will produce a warning by MutableMemberChecker
    mutable int evilMutableMember;
    int goodMember;
};


class Foo
{
public:
    // will produce a warning by MutableMemberChecker
    mutable int evilMutableMember;
    int goodMember;
};

// results in a warning by GlobalStaticChecker
static int g_static;
static int * g_ptr_static = &g_static;


int main()
...


```

**Comment by gartung** [comment]
CMS_SA_ALLOW can be used before  these declarations

Stand alone checkers
- Before any  non-const static local variable declaration
- Before any  non-const static member declaration
- Before any mutable member declaration
- Before any  extern C declaration

CatchAll checker:
- Before a function body declaration that uses catch(...)

Function checker:
Before a function or function template body declaration where
- a non-const static local variable is accessed or modified
- a COMMONBLOCK variable accessed or modified
- non-const global static variable is accessed or modified


In a CMS data class:

Before a const member function declaration where  
- a non-const static local variable is accessed
- a non-const static member variable accessed
- a non-const global static variable accessed
- member data is modified
- returns or has return type  pointer to a non-const member variable
- returns  or has return type object of type const std::vector<*> or const td::vector<*>&

Before a mutable member declaration.

**Comment by fabiocos** [comment]
please test

**Comment by Dr15Jones** [comment]
@gartung instead of having the attribute be part of the function declaration, is it feasible to just have the attribute associated with the piece of code with the problem? E.g.
```C++
CMS_SA_ALLOW try { doSomethingThatCanThrow() } catch(...) {}
```
or
```C++
try{ doSomethingThatCanThrow() } CMS_SA_ALLOW catch(...) {}
```

**Comment by gartung** [comment]
The way the attribute is currently implemented , it can only be attached to Decl
https://github.com/cms-externals/llvm-project/blob/378e9188b54c407546d3cc1e448b82be7c7a9861/clang/lib/Sema/SemaDeclAttr.cpp#L6332

**Comment by gartung** [comment]
It can be attached to a AST Stmt object. I will need to add more to clang to make that work.

**Comment by gartung** [comment]
Test with https://github.com/cms-externals/llvm-project/pull/5

**Comment by gartung** [comment]
Test with https://github.com/cms-sw/cmsdist/pull/5437

**Comment by gartung** [comment]
Trial and mostly error
```
/build/gartung/CMSSW_11_1_X_2019-12-19-2300/src/FWCore/Services/plugins/CondorStatusUpdater.cc:255:9: error: an attribute list cannot appear here
      } CMS_SA_ALLOW catch (...) {
        ^~~~~~~~~~~~
/cvmfs/cms-ib.cern.ch/week1/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_1_X_2019-12-19-2300/src/FWCore/Utilities/interface/thread_safety_macros.h:5:22: note: expanded from macro 'CMS_SA_ALLOW'
#define CMS_SA_ALLOW [[cms::sa_allow]]
                     ^~~~~~~~~~~~~~~~~
```

**Comment by gartung** [comment]
Apparently cxx0x attributes cannot appear in front of a catch statement as shown by the test  case
```
 test/Parser/cxx0x-attributes.cpp:  } [[]] catch (...) { // expected-error {{an attribute list cannot appear here}}
```

**Comment by gartung** [comment]
The attribute can appear in front of a try block as long as there is a statement attribute handler for it.

**Comment by gartung** [comment]
Test with cms-externals/llvm-project#6

**Comment by gartung** [comment]
The attribute is attached but to the parent AttributedStmt and a sibling of the try statement. 

```
|       `-CompoundStmt 0x7fda96b5e9f8 <col:66, line:259:5>
|         `-AttributedStmt 0x7fda96b5e9e0 </cvmfs/cms-ib.cern.ch/week1/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_1_X_2019-12-19-2300/src/FWCore/Utilities/interface/thread_safety_macros.h:5:22, /build/gartung/CMSSW_11_1_X_2019-12-19-2300/src/FWCore/Services/plugins/CondorStatusUpdater.cc:258:7>
|           |-CMSSaAllowAttr 0x7fda96b5e9d0 </cvmfs/cms-ib.cern.ch/week1/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_1_X_2019-12-19-2300/src/FWCore/Utilities/interface/thread_safety_macros.h:5:24, col:29>
|           `-CXXTryStmt 0x7fda96b5e9b0 </build/gartung/CMSSW_11_1_X_2019-12-19-2300/src/FWCore/Services/plugins/CondorStatusUpdater.cc:250:21, line:258:7>
|             |-CompoundStmt 0x7fda96b5e7e0 <line:250:25, line:255:7>
```

The test is far more complicated than Decl->hasAttr<>(). It will involve finding the parent try statement and the parent attributed statement of that.  Clang does not provide direct links to parent statements.

**Comment by gartung** [comment]
abort

**Comment by gartung** [comment]
Test with cms-externals/llvm-project#6

**Comment by gartung** [comment]
test with https://github.com/cms-sw/cmsdist/pull/5445

**Comment by Dr15Jones** [comment]
@gartung what is the state of this? Were you able to get the annotation of `try {} catch(...)` to work?

**Comment by gartung** [comment]
Yes the putting CMS_SA_ALLOW in front of the try statement will suppress the warning about catch (...) I tested it on the try catch in FWCore/Services and it works.

**Comment by gartung** [comment]
Making vetos for the other checkers can be in another pull request.

**Comment by Dr15Jones** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
