### PR TITLE
Fixing FastTimerClient Hist Remaking Issue : 12_3_X

### PR DESCRIPTION
**Pull request by Sam-Harper**
#### PR description:

This is the bug fix backport of https://github.com/cms-sw/cmssw/pull/37402

Before the path of the histogram was not specified when checking it exists leading to the histogram being remade over and over which is a very expensive operation. 

It also adds an option to disable making the histograms every lumisection which is the desired behaviour for everything expect online workflows. 

#### PR validation:

see: https://github.com/cms-sw/cmssw/pull/37402

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

https://github.com/cms-sw/cmssw/pull/37402

This fix is necessary to be able to harvest timing jobs running on multiple lumisections (which is our current workflow when reemulating the L1 running on ZB). Otherwise the job will take hours rather than seconds.

### CODE REVIEW

**Comment by missirol** [comment]
backport of https://github.com/cms-sw/cmssw/pull/37402

**Comment by missirol** [comment]
type bugfix

**Comment by missirol** [comment]
please test

**Comment by perrotta** [comment]
+1

**Pull request merged**
