### PR TITLE
[UBSAN] Properly initialize data members , fixes UBSAN unit test

### LINKED ISSUE #35463: [UBSAN][ALCA] unit tests failed due to uninitialization
A unit test `EcnaCalculationsExample` in package `CalibCalorimetry/EcalCorrelatedNoiseAnalysisAlgos` failed with error [a]. Looks like the data meber `fCnaParCout` used https://github.com/cms-sw/cmssw/blob/master/CalibCalorimetry/EcalCorrelatedNoiseAnalysisAlgos/src/TEcnaRun.cc#L249 is only initialized after the `Init()` call https://github.com/cms-sw/cmssw/blob/master/CalibCalorimetry/EcalCorrelatedNoiseAnalysisAlgos/src/TEcnaRun.cc#L30 and https://github.com/cms-sw/cmssw/blob/master/CalibCalorimetry/EcalCorrelatedNoiseAnalysisAlgos/src/TEcnaRun.cc#L82 . 

@cms-sw/alca-l2 , can you please look in to this?

[a] https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc10/CMSSW_12_1_UBSAN_X_2021-09-27-2300/unitTestLogs/CalibCalorimetry/EcalCorrelatedNoiseAnalysisAlgos#/
```
===== Test "EcnaCalculationsExample" ====
!EcnaCalculationsExample> CONTROLE 1
/data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/000ce895d6cafe30c0cf258dda5bc45a/opt/cmssw/slc7_amd64_gcc10/cms/cmssw/CMSSW_12_1_UBSAN_X_2021-09-27-2300/src/CalibCalorimetry/EcalCorrelatedNoiseAnalysisAlgos/src/TEcnaRun.cc:249:50: runtime error: member call on misaligned address 0x9999999999999999 for type 'struct TEcnaParCout', which requires 8 byte alignment
0x9999999999999999: note: pointer points here
<memory cannot be printed>

 *** Break *** segmentation violation
```

### PR DESCRIPTION
**Pull request by smuzaffar**
This change should fix the failing unit test in UBSAN IBs.
- TEcnaRun.cc : Common initialization code for `TEcnaRun` class is moved to `TEcnaRun::Init()`
- TEcnaWrite.cc: Fix initialization of fCodePrintAllComments

fixes #35463

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test for CMSSW_12_1_UBSAN_X

**Comment by smuzaffar** [comment]
unit test now runs for UBSAN ( https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-51a8ef/19236/unitTests/success.html )

**Comment by tvami** [comment]
type bug-fix

**Comment by tvami** [comment]
> * DQMHistoTests: Total failures: 352850

Is this coming from some other PR?

**Comment by smuzaffar** [comment]
@tvami , this is comparison of UBSAN (GCC10) vs normal IB (GCC9) IB, so there will be differences there. You should check the comparison results here https://github.com/cms-sw/cmssw/pull/35470#issuecomment-930164106  ( for normal tests)

**Comment by tvami** [comment]
+alca
 * normal tests are clean
 * USBAN code compiles

**Comment by perrotta** [comment]
+1

**Pull request merged**
