### PR TITLE
[12.3.X] DQM modules to monitor Pixel RecHits & remove assert in SiPixelRecHitSoAFromLegacy plugin

### PR DESCRIPTION
**Pull request by sroychow**
#### PR description:
Backport of #37193 and #37174.

#### PR validation:
Code compiles.

### CODE REVIEW

**Comment by sroychow** [comment]
test parameters

- please test workflow 11634.501, 11634.502, 11634.505

**Comment by sroychow** [comment]
enable gpu

**Comment by sroychow** [comment]
@cmsbuild please test

**Comment by qliphy** [comment]
backport of #37193
backport of #37174.

**Comment by qliphy** [comment]
test parameters:
- enable_test = threading
- workflows = 11634.501, 11634.505
- workflow_threading = 11634.501, 11634.505

**Comment by perrotta** [comment]
backport of #37174
(To allow bot considering the one which is not yer merged: the status will switch to "backport-ok" as soon as also #37174 is merged in master)

**Comment by jfernan2** [comment]
+1

**Comment by sroychow** [comment]
test parameters

- workflows = 11634.501, 11634.502, 11634.505

**Comment by sroychow** [comment]
@cmsbuild  please test

**Comment by jfernan2** [comment]
Undefined workflow: 11634.502

**Comment by perrotta** [comment]
test parameters:

**Comment by perrotta** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by jpata** [comment]
+reconstruction
- no relevant changes since https://github.com/cms-sw/cmssw/pull/37242#issuecomment-1068167360

**Comment by perrotta** [comment]
+1

**Pull request merged**
