### PR TITLE
global chi2/ndf cut removed from isLooseTriggerMuon

### PR DESCRIPTION
**Pull request by schhibra**
Back-port of PR #23898

### CODE REVIEW

**Comment by drkovalskyi** [comment]
It's needed since TSG is not committed to start using 10_2_X in near future. For now they will continue with 10_1. That's why it's needed.

**Comment by kpedro88** [comment]
backport of #23898

**Comment by kpedro88** [comment]
please test

**Comment by Martin-Grunewald** [comment]
@kpedro88 
OK, now that the PR is indeed made, please add it to the 10_1 release.

**Comment by kpedro88** [comment]
@slava77 @perrotta please check and sign this backport so we can make a new 10_1 release

**Comment by slava77** [comment]
assign hlt
similar to the 10_2_X PR #23973

**Comment by Martin-Grunewald** [comment]
+1

**Comment by slava77** [comment]
this PR will change value of flags saved in reco::Muons in the standard production outputs.
Nominal policy is that this is not allowed.
Given the current state of 10_1_X, an exception should probably be transparent:
- the affected variable has a limited use scope in offline analysis
- an updated code will probably not make it to T0, considering the planned change to 10_2_X
- most of the MC made with 10_1_X is ~disposable

@kpedro88 @fabiocos 
this effect was not explicitly discussed on Tuesday in the ORP.

**Comment by slava77** [comment]
an "alternative" (normal resolution to this production release consistency violation) is to make the code configurable so that the default behavior is unchanged and enable the change where it's needed in HLT only.

**Comment by drkovalskyi** [comment]
Can we just get it done. No one really has time right now to explore "alternatives".

**Comment by kpedro88** [comment]
@slava77 indeed, at the ORP the only known input for 10_1 was the DAQ PR. But now there is the desire to include these HLT updates in 10_1 as well as 10_2. 

There isn't an obvious (to me, anyway) approach to make this change configurable. Trying to do something more elaborate may introduce other regressions, given the short timescale to have a 10_1 release prepared for post-MD operations.

With these considerations, I think the minor change can be accepted in this case.

**Comment by slava77** [comment]
> @slava77 indeed, at the ORP the only known input for 10_1 was the DAQ PR. But now there is the desire to include these HLT updates in 10_1 as well as 10_2.
> 
> There isn't an obvious (to me, anyway) approach to make this change configurable. Trying to do something more elaborate may introduce other regressions, given the short timescale to have a 10_1 release prepared for post-MD operations.
> 
> With these considerations, I think the minor change can be accepted in this case.


please remind me where this isLooseTriggerMuon used in the standard HLT
menu.
From the discussion on Tuesday I understood that the menu used so far
was not relying on this flag.

**Comment by drkovalskyi** [comment]
It's used in MuonIDFilterProducerForHLT.

**Comment by slava77** [comment]
On 7/26/18 1:56 PM, drkovalskyi wrote:
> It's used in MuonIDFilterProducerForHLT.
> 
> —


I picked /cdaq/physics/Run2018/2e34/v2.2.3/HLT/V2
from 318876
and I did not find this module there.

**Comment by drkovalskyi** [comment]
It's not in the current menu. We are waiting for the change to propagate offline. It was not in the old menu with chi2 problem by mistake.

**Comment by slava77** [comment]
On 7/26/18 11:35 PM, drkovalskyi wrote:
> It's not in the current menu. We are waiting for the change to propagate
> offline. It was not in the old menu with chi2 problem by mistake.
> 

I'm trying to understand the use case more explicitly, esp if it's
possible to maintain the default unchanged in 10_1_X to still satisfy
the policy

**Comment by drkovalskyi** [comment]
We are trying to avoid using the string parser online to guarantee that the offline muon selection is used online. It's not possible to proceed without changing offline content, but it's Ok for the end user, because this selector is designed to be used online. Offline we store it to simplify checks for the most recent data. It's expected that this id will freeze and stay as is for many years as it normally happens with simple cut-based muon selectors. I suspect that it's last time we touch that code for long time.

**Comment by jfernan2** [comment]
+1

**Pull request merged**
