### PR TITLE
L1T Phase2 NN Tau (11_1_X)

### PR DESCRIPTION
**Pull request by rekovic**
#### PR description:
11_1_X:  L1T Phase2 NNTau reconstruction based on PF and Puppi
 - producers (PF and Puppi) and configurations
 - included in L1T Phase2 sequence
 - included in FEVTDEBUG Phase2 EventContent

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by rekovic** [comment]
please test

**Comment by rekovic** [comment]
backport of #31601

**Comment by silviodonato** [comment]
@rekovic @jmduarte  See #31601. Closing this PR.

**Comment by rekovic** [comment]
@silviodonato and @qliphy
Please reopen the PR.  This branch is now fully in sync with 11_3_X merged #31601.

**Comment by kpedro88** [comment]
@rekovic it would be preferable to address #32460 first, rather than backporting a known bug

**Comment by rekovic** [comment]
@kpedro88 
Thanks.  As discussed in the ORP, will make a fix in master and include it in the 11_1_X backport.

**Comment by rekovic** [comment]
By the way, the git will not re-open this PR cannot be reopened due to forced push to the branch.
This PR is replaced by  https://github.com/cms-sw/cmssw/pull/32493

**Pull request closed without merging**
