### PR TITLE
Utilities/StaticAnalyzers: Remove postprocess-scan-build.py script no longer needed.

### PR DESCRIPTION
**Pull request by gartung**
Starting with llvm/clang 16, the static analyzer removes bug reports for duplicate locations. The postprocess-scan-build.py script is no longer needed to do this.

addresses #41828

### CODE REVIEW

**Comment by makortel** [comment]
Given that this PR only removes a script, is a corresponding change to remove calling the script (only for 13_2_X onwards) needed somewhere? Or is the calling side "smart" enough to call the script only if it exists?

**Comment by gartung** [comment]
The calling script checks if the file exists and runs it.

**Comment by makortel** [comment]
+core

**Comment by perrotta** [comment]
+1

**Comment by gartung** [comment]
@makortel can this be back-ported to CMSSW_13_1_X?

**Comment by makortel** [comment]
I'd be fine with the backport.

**Comment by gartung** [comment]
I think a level 1 or level 2 has to issue the backport command.

**Pull request merged**
