### PR TITLE
Add enforceGUIDInFileName option to PoolSource and EmbeddedRootSource (11_0_X)

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

Quoting original PR

> This PR adds an option to `PoolSource` and `EmbeddedRootSource` to enforce that the file name (without extension) corresponds the GUID of the file. The added configuration parameter is `enforceGUIDInFileName = cms.untracked.bool`, and is set to `false` by default to preserve the current behavior. In case of a mismatch a new error code 8034 (`FileNameInconsistentWithGUID`) is returned.
> 
> The motivation for such an option comes from https://github.com/dmwm/WMCore/issues/9432.

#### PR validation:

(Relevant) tests in #28561 worked, no problems in IBs.

#### if this PR is a backport please specify the original PR:

Backport of  #28561 (using ~~exactly the same branch~~ otherwise exactly the same branch but adding a commit cleaning up `FWCore/Utilities/test/BuildFile.xml`).

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
@cmsbuild, please abort

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by smuzaffar** [comment]
please ignore the last comment by bot

**Comment by Dr15Jones** [comment]
+1

**Comment by Dr15Jones** [comment]
backport  #28561

**Comment by fabiocos** [comment]
+1

**Pull request merged**
