### PR TITLE
Import additions for UL from CMSSW_9_4_13_UL1 (#26168) and #26211

### PR DESCRIPTION
**Pull request by fabiocos**
#### PR description:

This PR is meant to import into the main CMSSW_9_4_X branch the additions for UL tested separately in the test build CMSSW_9_4_13_UL1 (based on #26168) and on the further addition #26211 .

#### PR validation:

This code has been used in tests and running without issues in CMSSW_9_4_MAOD_X IBs for a while.

### CODE REVIEW

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
@franzoni @srimanob FYI

**Comment by civanch** [comment]
+1

**Comment by alberto-sanchez** [comment]
+1

**Comment by fabiocos** [comment]
+operations

**Comment by fabiocos** [comment]
+1

**Pull request merged**
