### PR TITLE
HCALDQM: Add monitoring for HF TP TDC cut (10_0_X)

### PR DESCRIPTION
**Pull request by DryRun**
Adds monitoring plots for HF TP TDC cut: efficiency of cut vs. ieta vs iphi and ieta. Also adds the numerator and denominator of the efficiency calculation (i.e. data TP occupancy / emulated TP occupancy with no TDC cut).

10_0_X version of https://github.com/cms-sw/cmssw/pull/22435.

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by thomreis** [comment]
please test

**Comment by DryRun** [comment]
Hi all - the 10_1_X version of this PR, #22435, passed the tests. Is there a chance this one could make 10_0_4? Thanks.

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
Your PR is unmergeable. Please have a look and possibly rebase it.

**Comment by DryRun** [comment]
Hi, I didn't expect https://github.com/cms-sw/cmssw/pull/22553 to get merged first (this one was made a week earlier) -- that PR was based off this PR, so all of the commits here are merged. I'll close this PR.

**Pull request closed without merging**
