### PR TITLE
Add Run 3 beam pipe + Minor update of Phase 2 beam pipe

### PR DESCRIPTION
**Pull request by ghugo83**
Also includes minor fix in Phase 2 BP.

### CODE REVIEW

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by civanch** [comment]
Differences are expected in Phase-2 WFs.

**Comment by cvuosalo** [comment]
+1

**Comment by civanch** [comment]
@kpedro88 , one radius is increased from 4 cm to 4.1 cm, all sim histories in Phase-2 become different. 2021 file is a copy of 2026 one.

**Comment by kpedro88** [comment]
typically we don't allow changes in phase 2 production geometries. To follow the policy, the updated 2026 beampipe should be a new file (i.e. v2/beampipe.xml) included in a new "common" subdetector geometry (O5) which would be used in new phase 2 geometry versions.

**Comment by civanch** [comment]
@ghugo83 , please, clone 2026 file into 2026/v2/beampipe.xml and revert the fix in 2026/v1/beampipe.xml

**Comment by civanch** [comment]
please test

**Comment by silviodonato** [comment]
Shall we merge this in 11_1_0_pre7?
geometry:  @Dr15Jones @civanch @cvuosalo @ianna @makortel @mdhildreth
upgrade:  @kpedro88

**Comment by boudoul** [comment]
Hi - Could @ghugo83  add  in the title that the Phase2 BP is also modified ?  Thanks

**Comment by civanch** [comment]
@silviodonato , yes, we need this asap for Run-3. This PR is an addition of two files, which are not used so far in any testing WF, so it is absolutely safe.

**Comment by kpedro88** [comment]
+upgrade
the new phase 2 beampipe should be included in a new phase 2 "common" subdetector in a future PR

**Comment by civanch** [comment]
+1

@cvuosalo already approved this PR

**Comment by silviodonato** [comment]
+1

**Pull request merged**
