### PR TITLE
Add Single-Iov Tracker Alignment Barycenter dump to Payload Inspector

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

There might be cases in which instead  of looking at the evolution of the Pixel barycenter over time one would just need to know the values for a single IOV. 
This is addressed in this PR in which the (x,y,z) coordinate of the barycenters of all Tracker Sub-detectors are printed (corrected or uncorrected for the Tracker GPR - this is revelant in the case of MC in which the GPR is set to 0).
 
#### PR validation:

Testing locally with:
```
 getPayloadData.py --plugin pluginTrackerAlignment_PayloadInspector --plot plot_TrackerAlignmentBarycenters --tag TrackerAlignment_Upgrade2017_realistic_v3 --time_type Run --iovs '{"start_iov": "1", "end_iov": "1"}' --db Prod --test ;
```

returns the desired plot:

a5ede121-d103-45fb-80a5-bfec60b2987c

#### if this PR is a backport please specify the original PR:

This PR is not a backport

### CODE REVIEW

**Comment by mmusich** [comment]
@sarafiorendi @francescobrivio FYI

**Comment by ggovi** [comment]
please test

**Comment by ggovi** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
