### PR TITLE
add track hit eff monitoring vs BX

### PR DESCRIPTION
**Pull request by mtosi**
back port of PR https://github.com/cms-sw/cmssw/pull/14413
@rovere @VinInn @deguio

### CODE REVIEW

**Comment by VinInn** [comment]
@cmsbuild , please test

**Comment by mtosi** [comment]
sorry
there was also DQM/TrackingMonitor/python/MonitorTrackGLBMuons_cfi.py to be modified

**Comment by dmitrijus** [comment]
Then backporting, the easiest way to do it:
scram p <cmssw_release>
git-cms-addpkg ...
and then, if pull has been merged, do:
git cherry-pick -x <commit id> for every pull commit in pull request

for your PR, that would be:
`git cherry-pick -x  cbd338fef81c03ba5b1f20fae31c968eb83ee564
git cherry-pick -x  f7de06e42add53c2977e75941614a59738aaef91
git cherry-pick -x  7b3e7d87529be1f4c302d6aa1c74dad206ab6505`

This way I know that changes in this 'backport' are exactly the same as in the merged PR. 
And it avoid mistakes such as above :)

It is also possible to create commits, which can be merged into both 80x and 81x at the same  time (using merge-base), but it's a bit too complicated to explain.

**Comment by VinInn** [comment]
@cmsbuild , please test

**Comment by VinInn** [comment]
@cmsbuild , please test

**Comment by VinInn** [comment]
@cmsbuild , please test

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
