### PR TITLE
Phase2-hgx334A Try to align cassette shifts of silicon and scintillator parts of HGCal

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Try to align cassette shifts of silicon and scintillator parts of HGCal. For non-zero shifts of cassettes, the silicon wafers and scintillator tiles used to move in opposite directions. Also, the direction of the shift did not match the value provided in the xml file. Both these effects are corrected in the construction of G4 geometry for DDD as well as DD4hep implementations.

#### PR validation:

Use the dump geometry option to check this

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by bsunanda** [comment]
@srimanob Please sign this PR

**Comment by bsunanda** [comment]
@srimanob Please sign this PR

**Comment by srimanob** [comment]
Hi @bsunanda 

The current PR description does not tell what do we expect from this PR? Is this PR consider to be technical, i.e. no change is expected or it is a PR that effects the SIM/RECO (and to which geometry)? Could you please update the PR description to be more clear? Thx.

**Comment by bsunanda** [comment]
[](https://user-images.githubusercontent.com/5033146/209455918-43b5415d-527e-4674-9d61-227db4b717e2.pngl)

**Comment by bsunanda** [comment]
Screenshot%20from%202022-12-23%2015-19-25

**Comment by bsunanda** [comment]
Screenshot%20from%202022-12-23%2015-19-25

**Comment by bsunanda** [comment]
Screenshot%20from%202022-12-23%2015-15-35

**Comment by bsunanda** [comment]
@srimanob Please approve the PR now

**Comment by srimanob** [comment]
Hi @bsunanda 
Could you please cover the question ask above if you expect this PR to change result. Because I don't see failure comparison, so I ask this question.

**Comment by bsunanda** [comment]
Since default cassette shifts are 0 for the current v17 definition, this PR will not change anything. However future versions with non-zero cassette shifts will be affected

**Comment by srimanob** [comment]
+Upgrade

Following the comment https://github.com/cms-sw/cmssw/pull/40358#issuecomment-1364626406, there is no expected change with this PR. The PR test show no difference as expected.

**Comment by perrotta** [comment]
+1

**Pull request merged**
