### PR TITLE
Change of VBF Hbb HLT path names in DQM code (online,offline,relval)

### PR DESCRIPTION
**Pull request by silviodonato**
Hi all,
with JIRA-717 [1] we are changing the name of a few trigger paths, related to the VBF H->bb.
This PR fix the HLT path names in the DQM code (online,offline,relval).
Silvio.
[1] https://its.cern.ch/jira/browse/CMSHLT-717

### CODE REVIEW

**Comment by perrotta** [comment]
Please @silviodonato foresee also a backport to 80X of this PR
Thank you.

**Comment by silviodonato** [comment]
backport in 80X: #13971

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
@silviodonato - please change the title of this PR and its back port to be descriptive of what changes are being made. Thanks (which is to say, which part of DQM)

**Comment by davidlange6** [comment]
+1

**Pull request merged**
