### PR TITLE
[DD4hep] Migrate geometry DB payload tester to DD4hep

### PR DESCRIPTION
**Pull request by cvuosalo**
The geometry DB payload tester is a tool for an expert to compare newly created geometry DB payloads with the XML geometry and with the geometry in the DB to make sure that the new payloads are correct. It has only existed as a DDD version, and this PR provides a DD4hep version.

Included in this PR is a change to turn off the INFO and WARNING messages from inside of DD4hep. With DD4hep running in production, it is not needed to have these messages appearing in every log of simulation. In future, a configurable option can be considered to enable or disable these messages at run time.

Note that the design of the DB payload tester script is very brittle. It depends on many other scripts, which it copies and edits. Changes in these scripts could cause the main script to fail. This design is carried over from the original DDD DB payload tester script. It would be good to re-design the main script in this PR to remove the copy-and-edit mechanism, but I'm not sure what new design would work.

This PR makes several improvements over the original DDD script. It adds a test for the GEM reco geometry payload. It updates the CALO reco geometry test to compare with Run 3 CALO reco geometry reference values instead of values from 2009. It removes false positives from several tests, where the tests were indicating geometry differences even though there were no real differences. It standardizes the output of several tests to make comparisons easier and more reliable.

In a few files, unnecessary dependence on DDD was removed.

#### PR validation:

The script was tested with sample Run 3 geometry DB payloads that were compared with the current Run 3 geometry in XML and in the DB.

Note that this PR should have no effect on any workflow.

### CODE REVIEW

**Comment by cvuosalo** [comment]
Don't trigger the PR tests yet. There is a unit test that needs a fix.

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by civanch** [comment]
@cvuosalo , in this PR several gzipped files are added. They should be controlled by git?

**Comment by tvami** [comment]
+db
 * unit tests testing geom DB creation pass

**Comment by civanch** [comment]
+1

**Comment by cvuosalo** [comment]
@civanch @tvami Sorry, I noticed that the `runDD4hepvsDBGeometryValidation.sh`script was copying scripts from the working directory rather than from the release directory. That setting was necessary for development, but once this PR goes into the master, the release directories need to be the source of the scripts. I changed the source directories from `$CMMSW_BASE` to `$CMMSW_RELEASE_BASE` in the script. Please approve this PR again.

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by tvami** [comment]
+db 
 * resign

**Comment by cvuosalo** [comment]
+1

**Comment by emanueleusai** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

**Comment by qliphy** [comment]
+1

**Pull request merged**
