### PR TITLE
Phase2-hgx286X Changes made to accommodate V16 Geometry

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Changes made to accommodate V16 Geometry

#### PR validation:

Use the runTheMatrix test workflows 35034.0 and 37434.0

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

**Comment by qliphy** [comment]
+1

**Pull request merged**
