### PR TITLE
Run3-ft30 Cleanup a few buildfiles with duplicate use

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Cleanup a few buildfiles with duplicate use

#### PR validation:

Tested privately

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
+1
- Technical, trivial: remove duplicate or unused ("boost") lines
- Jenkins tests pass

**Comment by civanch** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
