### PR TITLE
HLT menu "Luna" V3.1 (94X)

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
HLT menu "Luna" V3.1 (94X)
Based on CMSSW_9_3_0_pre5

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by Martin-Grunewald** [comment]
@Dr15Jones 
please sign for addOnTests

**Comment by Dr15Jones** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
