### PR TITLE
Remove files made useless from AfterAbortGap -> AAG transition

### PR DESCRIPTION
**Pull request by mmusich**
It was already https://github.com/cms-sw/cmssw/pull/18776/commits/30037acdd50f002572160292a21ef2394c12761f,  this PR remove two files that were left over in the #18753, but have no reason to remain at this point.

### CODE REVIEW

**Comment by franzoni** [comment]
please test

**Comment by mmusich** [comment]
@franzoni, actually having a look to the output file of the step8 of the wf 1001.0 
[here](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-19075/20296/runTheMatrix-results/1001.0_RunMinBias2011A+RunMinBias2011A+TIER0EXP+ALCAEXP+ALCAHARVD1+ALCAHARVD2+ALCAHARVD3+ALCAHARVD4+ALCAHARVD5/step8_RunMinBias2011A+RunMinBias2011A+TIER0EXP+ALCAEXP+ALCAHARVD1+ALCAHARVD2+ALCAHARVD3+ALCAHARVD4+ALCAHARVD5.log)

I saw something worrying, i.e.:

```
%MSG-w SiStripGainFromCalibTree:   SiStripGainFromCalibTree:alcaSiStripGainsAAGHarvester@endJob  02-Jun-2017 09:08:58 CEST PostGlobalEndRun
calibrationMode  -> AagBunch
produceTagFilter -> Return false: Statistics is too low : 4977
%MSG
%MSG-w SiStripGainFromCalibTree:   SiStripGainFromCalibTree:alcaSiStripGainsAAGHarvester@endJob  02-Jun-2017 09:08:58 CEST PostGlobalEndRun
getNewObject -> will not produce a paylaod because produceTagFilter returned false 
```

This means that the `SiStripGainFromCalibTree` in the sequence as harvester (!) while it should not.
I think that https://github.com/cms-sw/cmssw/pull/18753 partially unmade my previous commit: https://github.com/cms-sw/cmssw/commit/efdd57403ce6ace836e4f71bdf0d0bd0b5af78d3, (i.e. the merging of the conflicts was not done correctly in #18753). 
The last push here should restore the correct behaviour. Please restart tests.

**Comment by franzoni** [comment]
please test

**Comment by franzoni** [comment]
please test

**Comment by franzoni** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
