### PR TITLE
MiniAOD reprocessing (74X, BTV): Whitelist IVF cands in packing + BugFix on SharedTracks helpers

### PR DESCRIPTION
**Pull request by ferencek**
Backport of #10088

This PR is part of preparations for possible MiniAOD reprocessing of the Spring15 MC and 50ns Run2012B Data in 74X. More info at the following links:
- https://hypernews.cern.ch/HyperNews/CMS/get/physics-validation/2445.html
- https://twiki.cern.ch/twiki/bin/view/CMS/MiniAODSpring15pass2#BTV

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by ferencek** [comment]
The failed tests appear to be ALCA-related and the fatal exceptions are unrelated to the changes proposed by this PR. The same for #10362, #10363, and #10364. Is there a problem with the IB used for tests?

**Comment by slava77** [comment]
@cmsbuild please test

@ferencek 
This PR also affects the standard RECO.
If we stay with 74X for data taking, and will move to a new acquisition era, it should be OK.
However, the MC and data will become inconsistent and implies that the affected taggers will have to be rerun in MC to be useful.
Please clarify if this issue is addressed already on the analysis side with appropriate recipes on miniAOD or with plans on updates to data/mc scale factors.

**Comment by pvmulder** [comment]
@slava77 
This and other PR #10362 #10363 # 10364 are intended for the miniAOD reprocessing of the Spring15 samples and 50ns data (as well as the 25ns prompt-reco to come). 
It is not yet decided if this miniAOD reprocessing will happen in 74X or 75X, but we were asked to prepare the PR for 74X:
https://twiki.cern.ch/twiki/bin/view/CMS/MiniAODSpring15pass2

**Comment by davidlange6** [comment]
I would rather see consistently than to open up changes to RECO in 74x. What changes under consideration can not simply be off by default and then be changed via configuration/conditions?

**Comment by slava77** [comment]
Petra,
things would remain transparent for PRs that do not change the reconstruction step.
You can either take out the bugfix in the sharedTracks or make it run only in miniAOD as suggested by David.

**Comment by slava77** [comment]
modulo the performance consistency problem this is +1

for https://github.com/cms-sw/cmssw/pull/10361	8df5f3e
- The code changes are affecting the regular/underlying pp reco (the implementation does not really allow a switch from one version to another, although some minor modifications can make it feasible). This introduces inconsistency with the mainstream 74X reconstruction. This is a topic for discussion in a separate meeting (not this PR thread)
- I confirmed by visual inspection that the code changes in  this PR are the same as in #10088 
- jenkins tests pass and comparisons with baseline show differences in a range of b-tagging variables, consistent with observations in #10088

**Comment by ferencek** [comment]
@slava77, it seems that your '+1' was not recognized by the bot. Same for #10362 and #10363

**Comment by slava77** [comment]
@ferencek it wasn't a real +1
I wanted to make a summary of the review and left it until the discussion earlier today to make an actual +1

**Comment by slava77** [comment]
+1

based on review above and the re-miniAOD discussion.

**Comment by ferencek** [comment]
@slava77, my apologies, I thought that was an actual '+1' :) All clear now

**Comment by monttj** [comment]
+1

**Comment by davidlange6** [comment]
closing PRs included in #10649

**Pull request closed without merging**
