### PR TITLE
DD Regression Test for All Scenarios

### PR DESCRIPTION
**Pull request by ianna**
- Add all scenarios
- Remove obsolete one

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
@Dr15Jones and @smuzaffar - as discussed yesterday this PR fixes DOMCount test

**Comment by Dr15Jones** [comment]
thanks

**Comment by ianna** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
