### PR TITLE
First attempt to remove DQM HLT warnings from logs caused by HLT Fake menus

### PR DESCRIPTION
**Pull request by jfernan2**
#### PR description:
This PR is a First attempt to remove DQM HLT warnings from logs caused by HLT Fake menus, flooding logs from RelVals not using GRun HLT menu (currently only Upgrade menus)

Basically I replaced every instance of @standardDQM+@ExtraHLT    by   @standardDQMFakeHLT in all Run1+Run2 relvals defined in Configuration/PyReleaseValidation/python/relval_steps.py

I left untouched "mother" steps definitions like *FullHEfail, HARVESTD or dataReco which may be used in the future as usual templates, and are in principle not used in current Relvals.

I am not sure if there exists a more clever way to do this.

I also removed a resilient HLT sequence in @standardDQMFakeHLT   which was still causing messages in logs despite being warned a Fake HLT menu was being used.

This PR is connected to the recent change to Fake menus in 2018 Relvals #27331 and #21815
Besides issue https://github.com/cms-sw/cmssw/issues/27372 should move PR tests to 2021 wf in CMSSW_11

#### if this PR is a backport please specify the original PR:

It is NOT a backport, though I am not sure if it needs a backport

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by fabiocos** [comment]
@jfernan2 thank you for this attempt as discussed at last meeting. We have too many parallel developments pending on PyRelVal, this PR needs to be rebased after the integration of #27415

**Comment by jfernan2** [comment]
@fabiocos I have rebased to #27415 

The PR is doing its work removing HLT warnings and many plots from HLT which were mostly empty.
There are still some warnings in:
-   10824.0  from PrimaryVertexAnalyzer4PUSlimmed TrackRefitter SiPixelPhase1TrackClusters PrimaryVertexMonitor 

- 136.85 from EcalDQM

and some other, so I will make a second cleaning round before proceeding ahead

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
please test
Second round of Error/Warning cleanup

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
please test

**Comment by fabiocos** [comment]
please test

**Comment by jfernan2** [comment]
@fabiocos There are still messages from Validation procedures which I had not been able to remove yet but I am working on them. If you want to merge this I can create another PR for them. They are mainly:

- EcalDQM: contacted ECAL DPG if they are fine with removal, not related to HLT
- HLT PV: this is nasty but I believe I can get rid of it too within some extra days of work...
Thanks

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
@fabiocos  this PR is almost done. Still pending:
- ecalDQM: ECAL team has promised to give an answer on it
- HLTTauDQM: it is "hidden" somewhere into some deep validation which I was not able trace back
- PV HLT: same as Tau
- Some AlCaDQM in AlCa workflows.

I can dedicate some time next week to the last three ones and include them here or in another PR as you prefer.
Thanks

**Comment by fabiocos** [comment]
@jfernan2 as said at the meeting, I believe that this PR as it is is already a good step forward, and fixes the part of the issues deriving from the change in the HLT menu. I would as to @prebello @zhenhu @kpedro88 to check it, and possibly merge it, adding further cleaning in a subsequent PR, which will probably need to address a different kind of issue.

**Comment by kpedro88** [comment]
+upgrade

**Comment by prebello** [comment]
+1

**Comment by fabiocos** [comment]
@jfernan2 do you agree to merge this PR as it is?

**Comment by jfernan2** [comment]
+1
yes of course

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
@jfernan2 from the ongoing IB CMSSW_11_0_X_2019-07-16-2300 where this PR is merged it looks like it works properly for most workflows, but it causes a failure in HARVESTING where the @rerecoZeroBiasFakeHLT sequence is invoked. This is the recent update in #27415 by @mmusich .

**Comment by mmusich** [comment]
@fabiocos I did not introduce any `@rerecoZeroBiasFakeHLT` in  #27415

**Comment by mmusich** [comment]
@jfernan2 failed to update the file `DQMOffline/Configuration/python/DQMOffline_Certification_cff.py` in order to apply this instruction https://github.com/cms-sw/cmssw/blob/master/DQMOffline/Configuration/python/DQMOffline_Certification_cff.py#L34
```
phase1Pixel.toReplaceWith(DQMCertCommon, DQMCertCommon.copyAndExclude([ # FIXME
    sipixelCertification # segfaults when included
]))
```

also to the newly created `DQMCertCommonFakeHLT` sequence.
It is somehow disappointing these changes were not fully tested. 
Having said this I can provide a fix in a few minutes...

**Comment by fabiocos** [comment]
@mmusich sorry, I was not clear, what I mean is that the failing histograms are those recently introduced in #27415 using @rerecoZeroBias , that were updated by @jfernan2 to the FakeHLT version

**Comment by mmusich** [comment]
>  Having said this I can provide a fix in a few minutes...

@fabiocos @jfernan2 I offer a quick fix in https://github.com/cms-sw/cmssw/pull/27540.

**Pull request merged**
