### PR TITLE
[12.4.X] fix run-by-run TkAlignment PV Validation submission script in case of extra conditions

### PR DESCRIPTION
**Pull request by mmusich**
backport of #39091

#### PR description:

Title says it all, discovered during the 13.6TeV alignment campaign when using updated pixel templates (cf [here](https://cms-talk.web.cern.ch/t/new-1d-and-2d-templates/13982) )

#### PR validation:

Private

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

verbatim backport of #39091

### CODE REVIEW

**Comment by mmusich** [comment]
type bugfix, trk

**Comment by mmusich** [comment]
please test

**Comment by tvami** [comment]
+alca

**Comment by qliphy** [comment]
+1

**Pull request merged**
