### PR TITLE
fix SingleTrackVertexConstraint class for the B=0T case

### PR DESCRIPTION
**Pull request by HuguesBrun**
In case magnet is off, the `SingleTrackVertexConstraint` always returns a dummy transient track which makes the update at vertex of STA/L2 muons to fail.
This PR add a protection against that, in case the magnet is on, the code behavior is unchanged

Will be backported in 75X, is it still possible to backport in 74X ?

### CODE REVIEW

**Comment by slava77** [comment]
Hugues, please make a PR for 75X and 74X.
Thank you.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by VinInn** [comment]
-1
to test BOff use nominalValue.
for instance
http://cmslxr.fnal.gov/lxr/source/RecoTracker/TkSeedGenerator/plugins/SeedFromConsecutiveHitsCreator.cc?v=CMSSW_7_5_0_pre5#0040

**Comment by HuguesBrun** [comment]
hello @VinInn , 

I updated the code following your comment

Hugues

**Comment by VinInn** [comment]
@HuguesBrun 
thanks.
In principle we should check some sort of geometric bound and not use the Magnetic field as an indication that we are far away...

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@HuguesBrun 
I suppose 75X and 74X updates are coming any moment, right?

**Comment by HuguesBrun** [comment]
hello @slava77,
I am doing this right now

**Comment by HuguesBrun** [comment]
@VinInn , 
I agree, this PR is more a fix in order to have update at vertex working at 0T in a rather short timescale, it is particularly useful at HLT where L2muonUpdatedAtVertex are used.

**Comment by cvuosalo** [comment]
+1

For #9971 6bba9248464cb87f57aaa07cc257511ce9f743f5

Bug fix to correctly handle SingleTrackVertexConstraint when magnet is off.

The code change is satisfactory, and Jenkins [tests](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-9971/187626/summary.html) against baseline CMSSW_7_6_X_2015-06-30-2300 show no significant differences.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
