### PR TITLE
updated pixel cabling (2017 & 2018) and EGM regressions

### PR DESCRIPTION
**Pull request by franzoni**
In this PR we'll take care of
+ updated pixel cabling (2017 & 2018):
. see: https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2815/1/1.html
+ and EGM regressions
. see: https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2806.html

The first commit only takes are of pixel cabling. I'll put in the regressions after the first round of tests (full documentation will follow), updating this PR with a new commit

### CODE REVIEW

**Comment by franzoni** [comment]
please test

**Comment by franzoni** [comment]
hello @veszpv @tvami 

can you please educate me on how the is used in the MC digi-reco sequence ?
I was expecting that the same payload would be used in packing the RAW as well as in unpacking them, which gave me the expectation identity would be observed between:
SiPixelFedCablingMap_phase1_v6
and
SiPixelFedCablingMap_phase1_v4
instead there are changes localize in a certain region of the pixel detector for the 2017 workflow:

https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_9_0_X_2017-02-09-2300+17479/18269/10021.0_TenMuE_0_200+TenMuE_0_200_pythia8_2017_GenSimFull+DigiFull_2017+RecoFull_2017+ALCAFull_2017+HARVESTFull_2017/
=>
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_9_0_X_2017-02-09-2300+17479/18269/10024.0_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2017_GenSimFull+DigiFull_2017+RecoFull_2017+ALCAFull_2017+HARVESTFull_2017/PixelPhase1_FED_Readout.html

can you please comment on wether these changes are expected and desired, or not ?

@slava77 you may want to keep an eye on this too

**Comment by franzoni** [comment]
given this explanations:
https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2815/1/1.html
and the fact that the only plots that changes are "occupancy_per_Channel_FED_XXX" type plots,

could it be that the same physical hits in the same geometric volumes in space
are simply assigned to a permutation of FED numbers ?

That would explain the fact that tracking is in no way affected.

**Comment by franzoni** [comment]
# Summary of changes in Global Tags

## RunI simulation

   * **RunI Heavy Ions scenario** : [90X_mcRun1_HeavyIon_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_mcRun1_HeavyIon_v2) as [90X_mcRun1_HeavyIon_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_mcRun1_HeavyIon_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/90X_mcRun1_HeavyIon_v2/90X_mcRun1_HeavyIon_v1):
      * update electron and photon regression for Moriond17, see https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2806.html
      * pappa

   * **RunI Ideal scenario** : [90X_mcRun1_design_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_mcRun1_design_v2) as [90X_mcRun1_design_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_mcRun1_design_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/90X_mcRun1_design_v2/90X_mcRun1_design_v1):
      * update electron and photon regression for Moriond17, see https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2806.html

   * **RunI Proton-Lead scenario** : [90X_mcRun1_pA_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_mcRun1_pA_v2) as [90X_mcRun1_pA_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_mcRun1_pA_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/90X_mcRun1_pA_v2/90X_mcRun1_pA_v1):
      * update electron and photon regression for Moriond17, see https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2806.html

   * **RunI Realistic scenario** : [90X_mcRun1_realistic_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_mcRun1_realistic_v2) as [90X_mcRun1_realistic_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_mcRun1_realistic_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/90X_mcRun1_realistic_v2/90X_mcRun1_realistic_v1):
      * update electron and photon regression for Moriond17, see https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2806.html

## RunII simulation

   * **RunII Asymptotic scenario** : [90X_mcRun2_asymptotic_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_mcRun2_asymptotic_v2) as [90X_mcRun2_asymptotic_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_mcRun2_asymptotic_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/90X_mcRun2_asymptotic_v2/90X_mcRun2_asymptotic_v1):
      * update electron and photon regression for Moriond17, see https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2806.html

   * **RunII CRAFT scenario** : [90X_mcRun2cosmics_startup_peak_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_mcRun2cosmics_startup_peak_v2) as [90X_mcRun2cosmics_startup_peak_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_mcRun2cosmics_startup_peak_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/90X_mcRun2cosmics_startup_peak_v2/90X_mcRun2cosmics_startup_peak_v1):
      * update electron and photon regression for Moriond17, see https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2806.html

   * **RunII Heavy Ions scenario** : [90X_mcRun2_HeavyIon_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_mcRun2_HeavyIon_v2) as [90X_mcRun2_HeavyIon_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_mcRun2_HeavyIon_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/90X_mcRun2_HeavyIon_v2/90X_mcRun2_HeavyIon_v1):
      * update electron and photon regression for Moriond17, see https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2806.html

   * **RunII Ideal scenario** : [90X_mcRun2_design_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_mcRun2_design_v2) as [90X_mcRun2_design_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_mcRun2_design_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/90X_mcRun2_design_v2/90X_mcRun2_design_v1):
      * update electron and photon regression for Moriond17, see https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2806.html

   * **RunII Proton-Lead scenario** : [90X_mcRun2_pA_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_mcRun2_pA_v3) as [90X_mcRun2_pA_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_mcRun2_pA_v2) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/90X_mcRun2_pA_v3/90X_mcRun2_pA_v2):
      * update electron and photon regression for Moriond17, see https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2806.html

   * **RunII Startup scenario** : [90X_mcRun2_startup_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_mcRun2_startup_v2) as [90X_mcRun2_startup_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_mcRun2_startup_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/90X_mcRun2_startup_v2/90X_mcRun2_startup_v1):
      * update electron and photon regression for Moriond17, see https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2806.html

## RunI data

   * **RunI Offline processing** : [90X_dataRun2_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_dataRun2_v2) as [90X_dataRun2_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_dataRun2_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/90X_dataRun2_v2/90X_dataRun2_v1):
      * update electron and photon regression for Moriond17, see https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2806.html

## RunII data

   * **RunII Offline processing** : [90X_dataRun2_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_dataRun2_v2) as [90X_dataRun2_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_dataRun2_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/90X_dataRun2_v2/90X_dataRun2_v1):
      * update electron and photon regression for Moriond17, see https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2806.html

   * **RunII Offline relval processing** : [90X_dataRun2_relval_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_dataRun2_relval_v2) as [90X_dataRun2_relval_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_dataRun2_relval_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/90X_dataRun2_relval_v2/90X_dataRun2_relval_v1):
      * update electron and photon regression for Moriond17, see https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2806.html

   * **RunII Prompt processing** : [90X_dataRun2_PromptLike_v2](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_dataRun2_PromptLike_v2) as [90X_dataRun2_PromptLike_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_dataRun2_PromptLike_v1) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/90X_dataRun2_PromptLike_v2/90X_dataRun2_PromptLike_v1):
      * update electron and photon regression for Moriond17, see https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2806.html

## Upgrade

   * **PhaseII realistic scenario** : [90X_upgrade2023_realistic_v4](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_upgrade2023_realistic_v4) as [90X_upgrade2023_realistic_v3](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_upgrade2023_realistic_v3) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/90X_upgrade2023_realistic_v4/90X_upgrade2023_realistic_v3):
      * update electron and photon regression for Moriond17, see https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2806.html

   * **PhaseI 2017 cosmics scenario** : [90X_upgrade2017cosmics_realistic_peak_v9](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_upgrade2017cosmics_realistic_peak_v9) as [90X_upgrade2017cosmics_realistic_peak_v7](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_upgrade2017cosmics_realistic_peak_v7) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/90X_upgrade2017cosmics_realistic_peak_v9/90X_upgrade2017cosmics_realistic_peak_v7):
      * update electron and photon regression for Moriond17, see https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2806.html
      * update of Phase1 Pixel Cabling Map, see https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2815/1/1.html

   * **PhaseI 2017 design scenario** : [90X_upgrade2017_design_IdealBS_v9](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_upgrade2017_design_IdealBS_v9) as [90X_upgrade2017_design_IdealBS_v7](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_upgrade2017_design_IdealBS_v7) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/90X_upgrade2017_design_IdealBS_v9/90X_upgrade2017_design_IdealBS_v7):
      * update electron and photon regression for Moriond17, see https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2806.html
      * update of Phase1 Pixel Cabling Map, see https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2815/1/1.html

   * **PhaseI 2017 realistic scenario** : [90X_upgrade2017_realistic_v9](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_upgrade2017_realistic_v9) as [90X_upgrade2017_realistic_v7](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_upgrade2017_realistic_v7) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/90X_upgrade2017_realistic_v9/90X_upgrade2017_realistic_v7):
      * update electron and photon regression for Moriond17, see https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2806.html
      * update of Phase1 Pixel Cabling Map, see https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2815/1/1.html

   * **PhaseI 2018 cosmics scenario** : [90X_upgrade2018cosmics_realistic_peak_v10](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_upgrade2018cosmics_realistic_peak_v10) as [90X_upgrade2018cosmics_realistic_peak_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_upgrade2018cosmics_realistic_peak_v5) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/90X_upgrade2018cosmics_realistic_peak_v10/90X_upgrade2018cosmics_realistic_peak_v5):
      * update electron and photon regression for Moriond17, see https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2806.html
      * update of Phase1 Pixel Cabling Map, see https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2815/1/1.html

   * **PhaseI 2018 design scenario** : [90X_upgrade2018_design_IdealBS_v10](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_upgrade2018_design_IdealBS_v10) as [90X_upgrade2018_design_IdealBS_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_upgrade2018_design_IdealBS_v5) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/90X_upgrade2018_design_IdealBS_v10/90X_upgrade2018_design_IdealBS_v5):
      * update electron and photon regression for Moriond17, see https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2806.html
      * update of Phase1 Pixel Cabling Map, see https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2815/1/1.html

   * **PhaseI 2018 realistic scenario** : [90X_upgrade2018_realistic_v10](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_upgrade2018_realistic_v10) as [90X_upgrade2018_realistic_v5](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/90X_upgrade2018_realistic_v5) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/90X_upgrade2018_realistic_v10/90X_upgrade2018_realistic_v5):
      * update electron and photon regression for Moriond17, see https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2806.html
      * update of Phase1 Pixel Cabling Map, see https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2815/1/1.html

**Comment by franzoni** [comment]
please test

**Comment by franzoni** [comment]
@rafaellopesdesa 
the GT updates introduced by this PR will enable the changes you want to deploy
in order to have the V4 egamma regressions consumed with the new lablels

**Comment by franzoni** [comment]
please test

**Comment by franzoni** [comment]
hello @davidlange6 @smuzaffar 
the urls pointing to the jenkin sessions don't show anything.
Can you help to address  "not able to find a release to test this PR" ? Thanks!

**Comment by franzoni** [comment]
please test

**Comment by smuzaffar** [comment]
@franzoni , test should run now. Last time they failed because the weekly IBs area was cleaned up and scram DB was missing. I will fix this in next days so that weekly cleanup does not break PR tests

**Comment by franzoni** [comment]
thanks @smuzaffar !

**Comment by franzoni** [comment]
as expected the introduction of the egamma regressions
(not consumed _right now_ in any CMSSW standard sequence)
has not changed the picture introduced by the picture already described here https://github.com/cms-sw/cmssw/pull/17479#issuecomment-278925268 as a result of the pixel cabling map.

@veszpv @tvami,
if you can  please give input on the FED numbering differences at earliest convenience,
we can integrate this PR and move on to add in other AlCa changes needed.
Thanks!

**Comment by veszpv** [comment]
@franzoni Your explanation is correct: the new cabling map associates a different FED+channel number for the same DetId. Since this mapping is done consistently in both digitization (digi2raw) and reconstruction (raw2digi), it is transparent in terms of high level reco. However, the content of RAW, the intermediate step, will be different. So the differences in validation are expected, as those plots are meant to display information from the RAW content.

**Comment by franzoni** [comment]
+1

**Comment by franzoni** [comment]
@davidlange6
Having this pr merged before tomorrow's orp, if possible,
would help the integration of more conditions in the pipeline

Thanks, @veszpv

**Comment by slava77** [comment]
@davidlange6 
we need this PR to integrate #17506 
Please clarify if this can be merged today
Thank you.

**Comment by davidlange6** [comment]
+1
yes, i missed it

**Comment by franzoni** [comment]
np!
I'll proceed with integrating another amount by tomorrow afternoon.

**Pull request merged**
