### PR TITLE
Change HitPixelLayersTPSelection to use ObjectSelectorStream

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

This converts it from a legacy module to a stream module.
This module is used in the integration build release validation jobs.

#### PR validation:

The code compiles.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
This is in response to #25090

**Comment by jfernan2** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
