### PR TITLE
Prevent pLHE workflows to start from input files 

### PR DESCRIPTION
**Pull request by fabiocos**
#### PR description:

PR #26875 has added 6 new test workflows based on pLHE input to GEN-SIM. Although the basic workflows run smoothly, when the ```-i all``` is used for runTheMatrix.py in IB , 1370.0,1370.17 and 1370.18 fail due to the fact that the generator part is split in two, and the standard logic of PyReleaseValidation fail, see issue #27248. A simple workaround is to force these workflows to be always fully executed, regardless of the input option (to be verified the possible impact on resources). 

#### PR validation:

All the pLHE workflows have been verified to pass the first two steps both with and without the ```-i all``` option of runTheMatrix.py.

### CODE REVIEW

**Comment by fabiocos** [comment]
please test workflow 1370.0,25215.0

**Comment by fabiocos** [comment]
please abort

**Comment by fabiocos** [comment]
please test workflow 1370.0,1370.17,1370.18,25215.0,25215.17,25215.18

**Comment by prebello** [comment]
@fabiocos could you please let me know it this PR supersedes the https://github.com/cms-sw/cmssw/issues/27248 ? Do you still need a fix for missing strp2?

**Comment by fabiocos** [comment]
@prebello sorry #27248 is an issue for discussion, not a PR, may be I misinterpret your question? In any case here I suggest a solution for that issue. It is not the only possible solution, but supposedly the simplest/fastest one.

**Comment by fabiocos** [comment]
@prebello @zhenhu @kpedro88 the test looks ok, any suggestion? Otherwise I would like to fix the IB asap...

**Comment by kpedro88** [comment]
+upgrade

**Comment by prebello** [comment]
hi @fabiocos  if it is running then please go ahead. Thank you. (sorry I have written PR instead of "issue" above. I was checking github in mobile)

**Comment by prebello** [comment]
+1

**Comment by fabiocos** [comment]
@prebello @chayanit one question: the LHE and GEN,SIM steps are using 100 events, which are quite heavy for Geant4 in a single threaded job, see the performances of step2 for 1370.0:
```
<PerformanceReport>
<PerformanceSummary Metric="Timing">
<Metric Name="AvgEventTime" Value="27.4588"/>
<Metric Name="EventSetup Get" Value="41.5036"/>
<Metric Name="EventSetup Lock" Value="1.33514e-05"/>
<Metric Name="EventThroughput" Value="0.0352632"/>
<Metric Name="MaxEventTime" Value="86.1217"/>
<Metric Name="MinEventTime" Value="7.13928"/>
<Metric Name="NumberOfStreams" Value="1"/>
<Metric Name="NumberOfThreads" Value="1"/>
<Metric Name="TotalInitCPU" Value="15.8924"/>
<Metric Name="TotalInitTime" Value="46.5579"/>
<Metric Name="TotalJobCPU" Value="2102.62"/>
<Metric Name="TotalJobTime" Value="2883.19"/>
<Metric Name="TotalLoopCPU" Value="2086.07"/>
<Metric Name="TotalLoopTime" Value="2835.81"/>
</PerformanceSummary>
</PerformanceReport>
```
that is lasting about 50 minutes in the test above. This statistics is then not used for any DQM check, as the RECO step runs anyway only on 10 events. Could we just bring the whole statistics down at 10 events starting from step1? It just means updating https://github.com/cms-sw/cmssw/blob/master/Configuration/PyReleaseValidation/python/relval_steps.py#L1434 as far as I can see

**Comment by fabiocos** [comment]
please test workflow 1370.0,1370.17,1370.18,25215.0,25215.17,25215.18

**Comment by smuzaffar** [comment]
@fabiocos , for workflows where step1 is GEN-SIM we normally have something like this
```
runTheMatrix.py -i all -l 1.0,2.0,1370.17,1370.18 -n -e
1.0    ProdMinBias+DIGIPROD1+RECOPROD1     [1]: cmsDriver.py MinBias_8TeV_pythia8_TuneCUETP8M1_cff  --conditions auto:run1_mc -n 10 --eventcontent RAWSIM --relval 9000,300 -s GEN,SIM --datatier GEN-SIM --beamspot Realistic8TeVCollision 
                                           [2]: cmsDriver.py step2  --datatier GEN-SIM-RAW --conditions auto:run1_mc -s DIGI,L1,DIGI2RAW,HLT:@fake --eventcontent RAWSIM -n 100 
                                           [3]: cmsDriver.py step3  --runUnscheduled  --conditions auto:run1_mc -s RAW2DIGI,L1Reco,RECO,RECOSIM,EI,PAT --datatier AODSIM,MINIAODSIM --eventcontent AODSIM,MINIAODSIM -n 100 
```
i.e
```
[1] cmsDriver.py <configuration> ....
[2] cmsDriver.py step2 ...
[3] cmsDriver.py step3 ...
```
but in case of these new workflows `1370.*` I get this
```
1370.17 GluGluHToGG_M125_Pow_MINLO_NNLOPS_py8_13UP17+Hadronizer_TuneCUETP8M1_13TeV_powhegEmissionVeto_2p_HToGG_M125_13UP17+DIGIUP17+RECOUP17+HARVESTUP17 
                                           [1]: cmsDriver.py step1  --conditions auto:phase1_2017_realistic -n 10 --era Run2_2017 --eventcontent LHE --relval 10000,50 --filein lhe:18334 -s NONE --datatier LHE --beamspot Realistic25ns13TeVEarly2017Collision --geometry DB:Extended --mc  
                                           [2]: cmsDriver.py Hadronizer_TuneCUETP8M1_13TeV_powhegEmissionVeto_2p_HToGG_M125_LHE_py8_cff  --conditions auto:phase1_2017_realistic --era Run2_2017 --eventcontent FEVTDEBUG --relval 10000,50 -s GEN,SIM --datatier GEN-SIM --beamspot Realistic25ns13TeVEarly2017Collision --geometry DB:Extended -n 100 
                                           [3]: cmsDriver.py step3  --conditions auto:phase1_2017_realistic -s DIGI:pdigi_valid,L1,DIGI2RAW,HLT:@relval2017 --datatier GEN-SIM-DIGI-RAW-HLTDEBUG -n 10 --geometry DB:Extended --era Run2_2017 --eventcontent FEVTDEBUGHLT
                                           [4]: cmsDriver.py step4  --conditions auto:phase1_2017_realistic -n 10 --era Run2_2017 --eventcontent RECOSIM,MINIAODSIM,DQM --runUnscheduled  -s RAW2DIGI,L1Reco,RECO,RECOSIM,EI,PAT,VALIDATION:@standardValidation+@miniAODValidation,DQM:@standardDQM+@ExtraHLT+@miniAODDQM --datatier GEN-SIM-RECO,MINIAODSIM,DQMIO --geometry DB:Extended
                                           [5]: cmsDriver.py step5  --conditions auto:phase1_2017_realistic -s HARVESTING:@standardValidation+@standardDQM+@ExtraHLT+@miniAODValidation+@miniAODDQM --filetype DQM --geometry DB:Extended --era Run2_2017 --mc  -n 100 

```
i.e. 
```
[1] cmsDriver.py step1 ...
[2] cmsDriver.py <configuration> ....
[3] cmsDriver.py step3 ...
```
is this the right configuration?

**Comment by fabiocos** [comment]
@smuzaffar yes, it is, the first step reads external LHE ascii files and converts them into ROOT format, the second runs the usual hadronizer+Geant4. The LHE keyword for step seems reserved so far for the internal production of these files, i.e. the more recent mechanism used in the various 5xx tests with Madgraph or Powheg, while here the test is about the legacy mechanism of importing externally produced files in the original LHE ascii format. I would imagine that the pure pLHE mechanism could be tested just at GEN-only level, but PdmV proposes to have a complete workflow chain for these samples, which is not harming provided the number of events is not overwhelming.

**Comment by fabiocos** [comment]
obviously much faster...

**Comment by fabiocos** [comment]
@prebello @zhenhu @kpedro88 I take the previous signature as valid, the only change is the number of events processed in the LHE and GEN,SIM steps (irrelevant for the final DQM result, but important for the performance impact on the tests).

Please check and sign or comment otherwise, I want to give this PR a try in next IB, before the big Sunday rebuild

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Comment by zhenhu** [comment]
+1

**Pull request merged**
