### PR TITLE
Clean up a few dead assignments from CalibCalorimetry/HcalAlgos and RecoMuon/TrackingTools

### PR DESCRIPTION
**Pull request by perrotta**
#### PR description:

Following some finding of the static analyzer, a few dead assignments are removed from the mentioned packages
I also took the opportunitiy to get rid of one extra sqrt computation in `MuonErrorMatrix::Term(const AlgebraicSymMatrix55 &curv, int i, int j)`

#### PR validation:

It builds correctly

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
+1
- Trivial clean up
- Jenkins tests pass

**Comment by yuanchao** [comment]
For 'CalibCalorimetry/HcalAlgos/src/HcalLogicalMapGenerator.cc' the modification is just commended out the dead assignment. Would it be better just remove the whole line? or 'mytype = 3' is still meaningful somewhere?

**Comment by perrotta** [comment]
> For 'CalibCalorimetry/HcalAlgos/src/HcalLogicalMapGenerator.cc' the modification is just commended out the dead assignment. Would it be better just remove the whole line? or 'mytype = 3' is still meaningful somewhere?

It was done on purpose, since I don't know if such an assignment was left as such with the intention of possibly reusing it in further developments. Of course, if the responsible of the code agrees that there is no reason to let such a "promemoria" in the code I will remove that line as a whole.

**Comment by abdoulline** [comment]
Not remembering all the details of the HcalLogicalMapGenerator 
(history), I'd suggest to keep the commeted line.

**Comment by silviodonato** [comment]
Kind reminder @cms-sw/alca-l2

**Comment by silviodonato** [comment]
urgent
can we merge this PR in pre8?
@cms-sw/alca-l2

**Comment by christopheralanwest** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
