### PR TITLE
L1 tkclasses cleaning

### PR DESCRIPTION
**Pull request by delaere**
This PR removes three outdated classes: L1TkCluster, L1TkStub, L1TkTrack. Theses classes are superseeded by TT\* classes. 

After discussing with Louise, we agreed to clean them to ease the development of new features.
The code in SLHCUpgradeSimulations/L1TrackTrigger that uses these classes hasn't been touched for several years. These are old versions of what now lives in L1Trigger/TrackTrigger, so we think it is safe to remove it.

The modified code was tested with runTheMatrix.py --what upgrade -l 10800 and runTheMatrix.py --what upgrade -l 12200. Let's hope it was not picking deleted files from the release area.

@boudoul, @skinnari, FYI.

### CODE REVIEW

**Comment by skinnari** [comment]
Some files were deleted in this PR that should be kept - I will fix it in the morning, so please hold off on the merge until then. Thanks, Louise.

**Comment by delaere** [comment]
I just merged in the changes by Louise. The PR should now be fine to proceed.

**Comment by davidlange6** [comment]
please test

**Comment by delaere** [comment]
Could this be merged? The errors are expected as L1tracking is not functional in SLHCDEV.

**Comment by boudoul** [comment]
Post Scriptum : I'm preparing today a PR to fix the error in the tests (to avoid what is expecting to fail, but keeping the relvance if the tests)

**Comment by delaere** [comment]
#13112 was merged... tests should now work better.

**Comment by davidlange6** [comment]
please test

**Pull request merged**
