### PR TITLE
Hotline skim AlCaReco workflows (74X)

### PR DESCRIPTION
**Pull request by duanders**
Backport of https://github.com/cms-sw/cmssw/pull/9627 to 74X.

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by davidlange6** [comment]
@duanders - 
 -- i worry about the keep * - what is the cost in memory size from these (eg, relative to RECO)? 
 -- I had thought that these were very low rate alcas-  if so - could they be combined into one? That would be much better logistically.

**Comment by duanders** [comment]
@davidlange6 

-What we would have ideally is FEVTEventContent (some POGs/DPGs have stated that the RAW needs to be included so that they can use these events for debugging).  Is there a way to specify this without creating a circular dependency in the code?  (i.e. Configuration/EventContent/python/EventContent_cff.py imports Calibration/Hotline/python/hotlineSkims_Output_cff.py, and vice versa)

-We have this as two separate AlCas because the MET group requested its own skim for their studies.  If possible, we would prefer to keep them separate so that the event rates and cuts can be tuned individually.  If you are strongly against it, it is possible to merge them.

**Comment by davidlange6** [comment]
@duanders - I don't see a problem with FEVT. But thats not keep *.

What are the skim rates? If its still 10 events a day, I would argue for a combined AlCa - but this does not mean that the two groups can not tune their event rates individually - you should just add something that makes it easy to decide which path selected the event.

**Comment by duanders** [comment]
@davidlange6 
My solution to avoid circular imports was to re-build the RAWRECO output commands within  Calibration/Hotline/python/hotlineMETSkims_Output_cff.py and  Calibration/Hotline/python/hotlineSkims_Output_cff.py.  Please let me know how it looks.

**Comment by davidlange6** [comment]
@duanders - that is not maintainable - which circular import did you run into when just doing

from Configuration.EventContent.EventContent_cff import FEVTEventContent

(modulo typos)?

**Comment by duanders** [comment]
@davidlange6 
 Calibration.Hotline.hotlineSkims_Output_cff 
---> Configuration.EventContent.EventContent_cff
---> Configuration.EventContent.AlCaRecoOutput_cff
---> Calibration.Hotline.hotlineSkims_Output_cff

**Comment by davidlange6** [comment]
@duanders - I see now. Will propose something later.

**Comment by cerminar** [comment]
@davidlange6 what is the motivation to split the two streams? Can you point us to the limitations of the system (both framework and computing aspects) for low rate AlCaStreams so that we can understand better the boundary conditions?
Thanks,
G

**Comment by davidlange6** [comment]
I want to join the two streams, not split them. Reasons I can think of

- today there are two  - will there be 4 next month? We can future proof this system a bit at a small cost
- the output buffers for writing raw+reco (or keep * as proposed originally) are big (and I guess will need tuning for this unique usecase)
- the merging process of streams that produce a small number of events/day is going cause some overhead in Tier0. Having 1 stream instead of 2 will reduce that
- the files are full of lumi section products, which I guess will dominate the size. So output size will be essentially unchanged by combining the streams (so 50% savings - but is peanuts anyway aside from the merging/filesize issue)

**Comment by davidlange6** [comment]
@duanders - please have a look at davidlange6:hotline_eventcontent (its based on 75x) and see if that works for you

**Comment by cerminar** [comment]
@davidlange6 thanks for the explanation. In principle being "path-based" there should be a "TriggerResults" product that would allow to split the events downstream (i.e. at analysis level). Is this what you have in mind? Shall this "TriggerResults" obect be explicitly added to the EventContent? 
One would need to check what happens in the AlCaSkimming step @ Tier0....

Did you have in mind another mechanism?

**Comment by davidlange6** [comment]
good point - the TriggerResults would contain the information I was thinking about for free (and even provide more details as the two hotlines so far are made a numerous paths). It should be part of the RAW-RECO event content but it should be confirmed

**Comment by duanders** [comment]
@davidlange6  From my perspective, the changes in davidlange6:hotline_eventcontent will fix the problem.  How do we proceed?

**Comment by davidlange6** [comment]
@duanders - i would suggest pulling my changes into your PRs (lets start with the 75x one) - need to confirm about ease of event selection in fireworks to settle the remaining question here

**Comment by duanders** [comment]
@davidlange6 I added your commit to https://github.com/cms-sw/cmssw/pull/9627.  

I tested the workflows with runTheMatrix, and can confirm that the FEVTEventContent includes the TriggerResults object that @cerminar mentioned (containing the skim decisions).  Assuming it works the same way at the Tier0, then this part is taken care of.

**Comment by duanders** [comment]
@davidlange6 
I pulled the changes into this PR too.  Merge conflict appears to be related to the line 
`ALCARECOEventContent.outputCommands.extend(OutALCARECOHcalCalIterativePhiSym_noDrop.outputCommands)`

**Comment by duanders** [comment]
@davidlange6 @cerminar I confirm that it is straightforward to use TriggerResults to filter events in Fireworks.  Therefore it's no problem to merge the two hotline workflows.  I made the changes here and in https://github.com/cms-sw/cmssw/pull/9627.

**Comment by mmusich** [comment]
please rebase on top of latest IB

**Comment by duanders** [comment]
Hi @mmusich, I tried to do this, but for some reason it pulled in a large number of other commits as well.  How do I fix this?  Sorry.

**Comment by slava77** [comment]
-1
needs a rebase

**Comment by duanders** [comment]
Rebased on CMSSW_7_4_X_2015-06-26-2300.

**Comment by mmusich** [comment]
please test

**Comment by diguida** [comment]
+1
Backport of #9627 
* new package `Calibration/Hotline` containing hotline skim code
* new AlCaReco implementing the hotline skim: sequences are in the client code, and paths are  implemented in `Configuration/StandardSequences/python/AlCaRecoStreams_cff.py`;
* hotline skim is included in the AlCaRecoMatrix under `StreamExpress`;
* hotline skim is included in `dataReco` definition for data RelVals;
* re-shaping of the definition of AlCaReco EventContent, in order to avoid python circular dependencies.

To be implemented: AlCa prompt implementation for AlCa harvesting step.

**Comment by duanders** [comment]
@franzoni , can PdmV please sign this, if it looks ok?  

Are any other signatures needed before tomorrow's ORP?

**Comment by duanders** [comment]
Hi @davidlange6, @franzoni, is there any chance of merging this today?  The hotline workflows will be most useful at the start of the 50ns data taking.  (Sorry for the spam.)

**Comment by davidlange6** [comment]
Hi Dustin
nominally we need pdmv to sign and a test in some development release. I realize the pdmv related change is trivial, so I propose that we merge in 75x and see if there are problems in the next IB. Then can consider something for 74x, but likely some relval testing is needed first.

**Comment by duanders** [comment]
Hi @davidlange6 , 
the PR from 76X was merged a week ago (https://github.com/cms-sw/cmssw/pull/9802), so there are already some IBs (ex: CMSSW_7_6_X_2015-07-04-2300) that we could look at.  Can we test there?

**Comment by davidlange6** [comment]
Hi Dustin
Good point - do you know which workflows run this alca?

**Comment by mmusich** [comment]
@davidlange6 @duanders should be run wherever the RECOD step is invoked, e.g.4.53 in the short matrix

**Comment by franzoni** [comment]
+1
for PdmV and Validaiton
run this whole PR on top of CMSSW_7_4_X_2015-07-07-2300
10 events of wf 4.53 run fine all the way to miniaod

**Pull request merged**
