### PR TITLE
Switch Geant4 physics list

### PR DESCRIPTION
**Pull request by civanch**
As a result of test-beam study with Geant4 10.2 a new Physics List FTFP_BERT_EMM seems providing the best results. This PR is applied just for the DEVEL brunch.

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by civanch** [comment]
@smuzaffar , may be I should not request testing of this PR? The branch seems to be correct...

**Comment by civanch** [comment]
@smuzaffar , this PR does not require an update of cmsdist - it should work fine on to of existing DEVEL branch or THREAD branch. It seems that for today there is no automatic test procedure - it like should be started manually, so I am not trying enable testing.

**Comment by smuzaffar** [comment]
please test

**Comment by davidlange6** [comment]
@civanch - I merged it - could you go ahead and prepare all the PRs needed for 81x (cmsdist and cmssw). Thanks

**Comment by civanch** [comment]
PR for cmsdist is created:  https://github.com/cms-sw/cmsdist/pull/2404

**Comment by davidlange6** [comment]
argh- I had understood this was all in the release already

On Jul 21, 2016, at 11:10 AM, Vladimir Ivantchenko <notifications@github.com<mailto:notifications@github.com>> wrote:


PR for cmsdist is created: cms-sw/cmsdist#2404<https://github.com/cms-sw/cmsdist/pull/2404>

**Pull request merged**
