### PR TITLE
added esConsumes to modules in L1Trigger/GlobalTrigger

### PR DESCRIPTION
**Pull request by JamminJones**
#### PR description:

added esConsumes to 1 module
#### PR validation:

the code compiles

### CODE REVIEW

**Comment by Dr15Jones** [comment]
This change was done under my supervision.

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
ping

**Comment by rekovic** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
