### PR TITLE
Run3 gex92: Backport some of the geometry diagnostic tools to study ddd/dd4hep geometries in XML and Big XML versions

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Backport some of the geometry diagnostic tools to study ddd/dd4hep geometries in XML and Big XML versions

#### PR validation:

Ran the scripts to verify the DDD version

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Backported from earlier 12_1_X versions

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by cvuosalo** [comment]
@bsunanda Thanks for the backport. I need it to check for overlaps with the new version of the DDD geometry.

**Comment by cvuosalo** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by jfernan2** [comment]
+1

**Comment by perrotta** [comment]
+1
- Backporting updates to test scripts and geometry xml files

**Pull request merged**
