### PR TITLE
[L1Trigger] Move public headers in to interface directory

### PR DESCRIPTION
**Pull request by smuzaffar**
This PR proposes to make private headers public as the public interface of these packages use them
This is part of cleanup discussed https://github.com/cms-sw/cmssw/issues/34718

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@rekovic, @cecilecaillol can you please review this?

**Comment by smuzaffar** [comment]
@rekovic, @cecilecaillol can you please review this?

**Comment by smuzaffar** [comment]
@cms-sw/l1-l2 , this is blocking the integration of build rules to enforce the private header usage check. Can you please review this?

**Comment by perrotta** [comment]
please test
(let update the 15 days old tests before merging)

**Comment by smuzaffar** [comment]
please test

**Comment by perrotta** [comment]
+1

**Pull request merged**
