### PR TITLE
Sim: Add a Production Cut on Proton equal to the one on Electron

### PR DESCRIPTION
**Pull request by ianna**
#### PR description:

*ProdCutsForProtons* is added to all xml fragments defining production cuts. The value is set to be equal to *ProdCutsForElectrons* - as it's done in its initialisation here: https://cmssdt.cern.ch/lxr/source/SimG4Core/Geometry/src/DDG4ProductionCuts.cc#0138

As discussed with @civanch and @cvuosalo 

#### if this PR is a backport please specify the original PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
assign simulation

**Comment by civanch** [comment]
+1
I would confirm, that it is an optimal solution to set "cut in range for proton" to be the same as "cut in range for electrons".

**Comment by ianna** [comment]
@smuzaffar - would it be possible to extend the clang-format to do the xml files formatting?

**Comment by ianna** [comment]
@kpedro88 - please, review

**Comment by ianna** [comment]
@civanch - Here is a complete list of the GT tag queues in CMSSW_11_0_X and the geometry tags that will have to be updated to deploy this change.

**run1_design**  :  106X_mcRun1_design_v3
**run1_mc**   :  106X_mcRun1_realistic_v3
**run1_mc_hi**  :  106X_mcRun1_HeavyIon_v3
**run1_mc_pa**  :  106X_mcRun1_pA_v3


Record | Label | Tag | Last Visible IOV
-- | -- | -- | --
GeometryFileRcd | ExtendedZeroMaterial | XMLFILE_Geometry_Run1_76YV2_ExtendedZeroMaterial_mc | 1 |   |  
GeometryFileRcd | Extended | XMLFILE_Geometry_Run1_76YV2_Extended_mc | 1 |   |  
GeometryFileRcd | Ideal | XMLFILE_Geometry_Run1_76YV2_Ideal_mc | 1


**'run2_mc_50ns'**  :  '106X_mcRun2_startup_v4'
**'run2_mc_l1stage1'**  :   '106X_mcRun2_asymptotic_l1stage1_v4'
**'run2_design'**       :   '106X_mcRun2_design_v5'
**'run2_mc'**           :   '106X_mcRun2_asymptotic_v5'
**'run2_mc_cosmics'**   :   '106X_mcRun2cosmics_startup_deco_v2'
**'run2_mc_hi'**        :   '106X_mcRun2_HeavyIon_v4'
**'run2_mc_pa'**        :   '106X_mcRun2_pA_v4'


Record | Label | Tag | Last Visible IOV
-- | -- | -- | --
GeometryFileRcd | CTPPS | XMLFILE_CTPPS_Geometry_2016_922V1 | 1 |   |  
GeometryFileRcd | Extended | XMLFILE_Geometry_2016_81YV1_Extended2016_mc | 1 |   |  
GeometryFileRcd | Extended2015CastorMeasured | XMLFILE_Geometry_80YV1_Extended2015CastorMeasured_mc | 1 |   |  
GeometryFileRcd | Extended2015CastorSystMinus | XMLFILE_Geometry_80YV1_Extended2015CastorSystMinus_mc | 1 |   |  
GeometryFileRcd | Extended2015CastorSystPlus | XMLFILE_Geometry_80YV1_Extended2015CastorSystPlus_mc | 1 |   |  
GeometryFileRcd | Extended2015ZeroMaterial | XMLFILE_Geometry_Run2_76YV2_Extended2015ZeroMaterial_mc | 1 |   |  
GeometryFileRcd | Extended2015dev | XMLFILE_Geometry_Run2_76YV2_Extended2015dev_mc | 1 |   |  
GeometryFileRcd | Ideal | XMLFILE_Geometry_Run2_76YV2_Ideal2015_mc | 1 |   |  
GeometryFileRcd | Ideal2015dev | XMLFILE_Geometry_Run2_76YV2_Ideal2015dev_mc

**'phase1_2017_design'**       :  '106X_mc2017_design_IdealBS_v5',
**'phase1_2017_realistic'**    :  '106X_mc2017_realistic_v5',
**'phase1_2017_cosmics'**      :  '106X_mc2017cosmics_realistic_deco_v2',
**'phase1_2017_cosmics_peak'** :  '106X_mc2017cosmics_realistic_peak_v2'


Record | Label | Tag | Last Visible IOV
-- | -- | -- | --
GeometryFileRcd | CTPPS | XMLFILE_CTPPS_Geometry_2017_101YV3 | 1 |   |  
GeometryFileRcd | ExtendedDetailedCavern | XMLFILE_Geometry_102YV2_ExtendedDetailedCavern2017Plan1_mc | 1 |   |  
GeometryFileRcd | ExtendedZeroMaterial | XMLFILE_Geometry_92YV5_Extended2017Plan1ZeroMaterial_mc | 1 |   |  
GeometryFileRcd | Extended | XMLFILE_Geometry_92YV5_Extended2017Plan1_mc | 1 |   |  
GeometryFileRcd | Ideal | XMLFILE_Geometry_Run2_76YV2_Ideal2015_mc

**'phase1_2018_design'**       :  '106X_upgrade2018_design_v5'
**'phase1_2018_realistic'**    :  '106X_upgrade2018_realistic_v6'


Record | Label | Tag | Last Visible IOV
-- | -- | -- | --
GeometryFileRcd | CTPPS | XMLFILE_CTPPS_Geometry_2018_102YV1 | 1 |   |  
GeometryFileRcd | ExtendedZeroMaterial | XMLFILE_Geometry_101YV4_Extended2018ZeroMaterial_mc | 1 |   |  
GeometryFileRcd | Extended | XMLFILE_Geometry_101YV4_Extended2018_mc | 1 |   |  
GeometryFileRcd | ExtendedDetailedCavern | XMLFILE_Geometry_103YV4_ExtendedDetailedCavern2018_mc | 1

**'phase1_2018_realistic_hi'** :  '106X_upgrade2018_realistic_HI_v4'


Record | Label | Tag | Last Visible IOV
-- | -- | -- | --
GeometryFileRcd | CTPPS | XMLFILE_CTPPS_Geometry_2018_102YV1 | 1 |   |  
GeometryFileRcd | ExtendedZeroMaterial | XMLFILE_Geometry_103YV1_Extended2018ZeroMaterial_mc | 1 |   |  
GeometryFileRcd | Extended | XMLFILE_Geometry_103YV1_Extended2018_mc | 1 |   |  
GeometryFileRcd | ExtndedDetailedCavern | XMLFILE_Geometry_103YV4_ExtendedDetailedCavern2018_mc | 1

**'phase1_2018_realistic_HEfail'** :  '106X_upgrade2018_realistic_HEfail_v6'


Record | Label | Tag | Last Visible IOV
-- | -- | -- | --
GeometryFileRcd | CTPPS | XMLFILE_CTPPS_Geometry_2018_102YV1 | 1 |   |  
GeometryFileRcd | ExtendedZeroMaterial | XMLFILE_Geometry_101YV4_Extended2018ZeroMaterial_mc | 1 |   |  
GeometryFileRcd | Extended | XMLFILE_Geometry_101YV4_Extended2018_mc | 1 |   |  
GeometryFileRcd | ExtendedDetailedCavern | XMLFILE_Geometry_103YV4_ExtendedDetailedCavern2018_mc | 1

**'phase1_2018_cosmics'**      :   '106X_upgrade2018cosmics_realistic_deco_v3'
**'phase1_2018_cosmics_peak'** :   '106X_upgrade2018cosmics_realistic_peak_v3'


Record | Label | Tag | Last Visible IOV
-- | -- | -- | --
GeometryFileRcd | CTPPS | XMLFILE_CTPPS_Geometry_2018_102YV1 | 1 |   |  
GeometryFileRcd | ExtendedZeroMaterial | XMLFILE_Geometry_101YV4_Extended2018ZeroMaterial_mc | 1 |   |  
GeometryFileRcd | Extended | XMLFILE_Geometry_101YV4_Extended2018_mc | 1 |   |  
GeometryFileRcd | ExtendedDetailedCavern | XMLFILE_Geometry_103YV4_ExtendedDetailedCavern2018_mc | 1

**'phase1_2021_design'**       : '106X_upgrade2021_design_v3'


Record | Label | Tag | Last Visible IOV
-- | -- | -- | --
GeometryFileRcd | CTPPS | XMLFILE_CTPPS_Geometry_2018_101YV6 | 1 |   |  
GeometryFileRcd | Extended | XMLFILE_Geometry_103YV5_Extended2019_mc | 1 |   |  
GeometryFileRcd | Ideal | XMLFILE_Geometry_Run2_76YV2_Ideal2015_mc | 1

**'phase1_2021_realistic'**    : '106X_upgrade2021_realistic_v7'
**'phase1_2021_cosmics'**      : '106X_upgrade2021cosmics_realistic_deco_v2'


Record | Label | Tag | Last Visible IOV
-- | -- | -- | --
GeometryFileRcd | CTPPS | XMLFILE_CTPPS_Geometry_2018_101YV6 | 1 |   |  
GeometryFileRcd | Extended | XMLFILE_Geometry_103YV5_Extended2019_mc

**'phase2_realistic'**         : '106X_upgrade2023_realistic_v5'

Record | Label | Tag | Last Visible IOV
-- | -- | -- | --
GeometryFileRcd | CTPPS | XMLFILE_CTPPS_Geometry_2018_102YV1 | 1 |   |  
GeometryFileRcd | Extended2023D1 | XMLFILE_Geometry_81YV023_Extended2023D1_mc | 1 |   |  
GeometryFileRcd | Extended2023D2 | XMLFILE_Geometry_81YV023_Extended2023D2_mc | 1 |   |  
GeometryFileRcd | Extended2023D3 | XMLFILE_Geometry_81YV023_Extended2023D3_mc | 1 |   |  
GeometryFileRcd | Extended2023D4 | XMLFILE_Geometry_81YV023_Extended2023D4_mc | 1 |   |  
GeometryFileRcd | Extended2023D5 | XMLFILE_Geometry_81YV023_Extended2023D5_mc | 1 |   |  
GeometryFileRcd | Extended2023D6 | XMLFILE_Geometry_81YV023_Extended2023D6_mc | 1 |   |  
GeometryFileRcd | Extended | XMLFILE_Geometry_91YV5_Extended2023D11_mc | 1

**Comment by civanch** [comment]
@ianna , if additionally to this PR we need to change all GTs, then may be we should step back and left all things as it was before? It was not not elegant but working solution.

**Comment by ianna** [comment]
> @ianna , if additionally to this PR we need to change all GTs, then may be we should step back and left all things as it was before? It was not not elegant but working solution.

@civanch - it's up to you to decide what Simulation needs are

**Comment by fabiocos** [comment]
@ianna @civanch if we have a good reason to split the production cut I think we just need to coordinate with @christopheralanwest @tocheng to produce the desired DB update in parallel to this xml addition.
Still I would like to understand: do we really have the need to have a separate cut for protons? So far apparently it was not needed. Of course this does not mean we should not update the existing situation, but I would like to better understand the real need.

**Comment by civanch** [comment]
@ianna , let us step back. Sorry, I underestimate amount of work and number of files to make modifications. Let us left this DDG4ProductionCuts class unchanged.

**Comment by ianna** [comment]
hold

**Comment by ianna** [comment]
unhold

**Comment by ianna** [comment]
@civanch - the PR creates a new version of an XML file which can be used in a new scenario if desired. I omitted any changes for Tracker, MTD, and CTPPS.

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by ianna** [comment]
@civanch , @kpedro88 - please review

**Comment by kpedro88** [comment]
+upgrade
an issue should be posted to notify responsible people for tracker, MTD, HGCal, CTPPS that this option is available if they want to implement it

**Comment by civanch** [comment]
+1

**Comment by ianna** [comment]
FYI https://github.com/cms-sw/cmssw/issues/27343

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
@ianna this PR looks to have broken a unit test 
```
run_DOMCount.py Geometry/CMSCommonData/cmsIdealGeometryAPD1XML_cfi
Failure run_DOMCount.py Geometry/CMSCommonData/cmsIdealGeometryAPD1XML_cfi: status 1
status = 256

--&gt; test DetectorDescriptionRegressionTestDOMCount had ERRORS
```

The problem looks to have origin here:
https://cmssdt.cern.ch/lxr/source/DetectorDescription/RegressionTest/test/run_DOMCount.sh#0015

**Comment by ianna** [comment]
@fabiocos I’ll submit a PR to fix it.

**Comment by ianna** [comment]
@fabiocos - FYI https://github.com/cms-sw/cmssw/pull/27391 fixes it.

**Pull request merged**
