### PR TITLE
81X update phase-I with Hcal geometry fix

### PR DESCRIPTION
**Pull request by mmusich**
# Summary of changes in Global Tags
## Upgrade
- **PhaseI realistic scenario** : [81X_upgrade2017_realistic_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_upgrade2017_realistic_v1) as [81X_upgrade2017_realistic_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_upgrade2017_realistic_v0) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_upgrade2017_realistic_v1/81X_upgrade2017_realistic_v0): 
  - updates to the Hcal geometry from 2015 Hcal to 2016a Hcal to fix the issue reported in https://github.com/cms-sw/cmssw/pull/14545#issuecomment-220594312
- **PhaseI design scenario** : [81X_upgrade2017_design_v1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_upgrade2017_design_v1) as [81X_upgrade2017_design_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_upgrade2017_design_v0) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_upgrade2017_design_v1/81X_upgrade2017_design_v0): 
  - updates to the Hcal geometry from 2015 Hcal to 2016a Hcal to fix the issue reported in https://github.com/cms-sw/cmssw/pull/14545#issuecomment-220594312

attn: @makortel @ianna @boudoul @veszpv.

@boudoul @hengne, please let me know if there is any smarter way of consuming the geometry from DB without destroying the loop logic in `Configuration/PyReleaseValidation/python/relval_steps.py`.

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by makortel** [comment]
Thanks @mmusich! So if I understand correctly, the 2017 geometry from DB with this PR should correspond the XML geometry in CMSSW_8_1_X_2016-06-01-1100 and earlier (i.e. before #14700 was merged), at least as far as pixel is concerned?

**Comment by mmusich** [comment]
@makortel at the best of my understanding, based also on https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideDataBaseGeometry#Payloads_In_the_Production_Datab that's correct. For sure the pixel reco geometry and the alignment are now guaranteed to be in synch.

**Comment by mmusich** [comment]
+1

**Comment by fabozzi** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
