### PR TITLE
Code quality fix for DNN TauID (94X)

### PR DESCRIPTION
**Pull request by mbluj**
Code quality fix as requested in https://github.com/cms-sw/cmssw/pull/25621#issuecomment-453123348.
Backport of #25649 to CMSSW 9_4_X release series.

### CODE REVIEW

**Comment by perrotta** [comment]
backport of #25649

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
+1
- Technical (apply code checks)
- Jenkins tests pass

**Comment by fabiocos** [comment]
+1

**Pull request merged**
