### PR TITLE
Allow running PUPPI v14 customizer on data

### PR DESCRIPTION
**Pull request by ahinzmann**
#### PR description:

Add separate customize for data and MC for production of UL JME-extended-Nano.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

To 10_6 for UL JME-extended-Nano

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by santocch** [comment]
+1

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/30017	b3a83d8
- somewhat technical; 
- this is used for private production/processing and does not affect the standard workflows

**Comment by silviodonato** [comment]
+1

**Pull request merged**
