### PR TITLE
CTPPS: updated diamond unpacker for post-TS1 conditions (9_2_5_patch2)

### PR DESCRIPTION
**Pull request by forthommel**

### CODE REVIEW

**Comment by threus** [comment]
@forthommel nope, it has 92 commits.. did you base it on 925patch2?

**Comment by forthommel** [comment]
Yes, unfortunately... I am investigating!

**Comment by forthommel** [comment]
@threus better? :)

**Comment by threus** [comment]
@forthommel looks much better, indeed. Don't forget to close it right now.

**Pull request closed without merging**
