### PR TITLE
Protect ProductResolvers from unlucky thread pause

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

Changed the order of two thread safe operations in order to guarantee that if a thread is paused for a long time between the two operations, it will never cause a task running problem.

#### PR validation:

Code compiles and all framework unit tests pass.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by makortel** [comment]
What about these?
https://github.com/cms-sw/cmssw/blob/0884d51ab694c3d62946aa6c07230e40fb84a38e/FWCore/Framework/src/ProductResolvers.cc#L419-L430
https://github.com/cms-sw/cmssw/blob/0884d51ab694c3d62946aa6c07230e40fb84a38e/FWCore/Framework/src/ProductResolvers.cc#L687-L702
https://github.com/cms-sw/cmssw/blob/0884d51ab694c3d62946aa6c07230e40fb84a38e/FWCore/Framework/src/ProductResolvers.cc#L757-L769
https://github.com/cms-sw/cmssw/blob/0884d51ab694c3d62946aa6c07230e40fb84a38e/FWCore/Framework/src/ProductResolvers.cc#L910-L926

**Comment by Dr15Jones** [comment]
That's what I get for doing `grep m_waitingTasks` to find the items :)

**Comment by Dr15Jones** [comment]
please test

**Comment by makortel** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
