### PR TITLE
DQM plots for elastic scattering in 900 GeV run (backport of #21158)

### PR DESCRIPTION
**Pull request by jan-kaspar**
This PR is a backport of #21158 and introduces new DQM plots essential for monitoring of elastic scattering in the 900 GeV run foreseen at the end of November. Since elastic scattering is used for CTPPS calibration (alignment, optics), many of the new plots are of general interest for CTPPS.

We would like to test the code in online DQM on 8 Nov 2017 when the machine plans a test run at 900 GeV. That's why this backport has been prepared. Some code refinements may occur after the test run.

The code has been prepared such that the new plots can be easily disabled - by removing this python config line:
https://github.com/jan-kaspar/cmssw/blob/dqm_rp_elastics/DQM/CTPPS/python/ctppsDQM_cff.py#L19

This PR can be tested with
https://github.com/jan-kaspar/cmssw/blob/dqm_rp_elastics/DQM/CTPPS/test/elastic_dqm_test_cfg.py
which uses data from a CTPPS alignment run (July 2017) where also vertical RPs were inserted. A similar Roman Pot configuration is expected for the 900 GeV data.

Beyond the new DQM modules, this PR makes a minor change to the RP geometry: verticals in unit 220-fr are placed in a similar distance from beam as other vertical RPs.

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by jan-kaspar** [comment]
5d2a6ce implements a suggestion by Tomas Hreus how to enable/disable the online creation of the new plots without issuing further PRs.

**Comment by dmitrijus** [comment]
+1

**Comment by ianna** [comment]
+1

**Comment by davidlange6** [comment]
CMSSW_9_2_X developement work is completed. Closing remaining PRs

**Pull request closed without merging**
