### PR TITLE
Alca packages: cleanup use of GCC11Compatibility.h

### PR DESCRIPTION
**Pull request by gartung**
#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by gartung** [comment]
please test

**Comment by tlampen** [comment]
+1

**Comment by silviodonato** [comment]
Kind reminder to @ggovi

**Comment by makortel** [comment]
@gartung Could you check the error above? Maybe something needing an explicit `#include "FWCore/Utilities/interface/Likely.h"` now crept in.

**Comment by gartung** [comment]
@makortel It should not be tested with pull request  #29124 which is where the missing header error comes from

**Comment by gartung** [comment]
please test

**Comment by gartung** [comment]
please test

**Comment by ggovi** [comment]
+1

**Comment by perrotta** [comment]
please test
(to possibly clean up the comparison)

**Comment by silviodonato** [comment]
merge

**Pull request merged**
