### PR TITLE
DD4Hep: Tracker DDPixFwdDisk Algorithm

### PR DESCRIPTION
**Pull request by vargasa**
#### PR validation:

```
cmsRun DetectorDescription/DDCMS/test/python/testDDPixFwdDiskAlgo.py
cmsShow -c simGeo.fwc --sim-geom-file cmsDD4HepGeom.root --tgeo-name=testDDPixFwdDiskAlgo
```

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by cvuosalo** [comment]
+1

**Comment by ianna** [comment]
urgent

**Comment by kpedro88** [comment]
+1

**Pull request merged**
