### PR TITLE
added check to avoid seg-fault in HLTScoutingPFProducer

### PR DESCRIPTION
**Pull request by missirol**
#### PR description:

This PR simply adds a check (throwing an exception upon failure) in `HLTScoutingPFProducer`, to prevent a crash due to an invalid reference to a `reco::PFCandidate`. This could occur, for example, if the input jet and PF-candidate collections fed to the producer are inconsistent (and the constituents of the input jets are not available anymore).

This type of crash was observed in a recent IB build (see [this comment](https://github.com/cms-sw/cmssw/pull/35863#issuecomment-953519150)); the underlying misconfiguration related to that crash is to be fixed in `ConfDB`, and is under investigation.

#### PR validation:

Private tests.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

### CODE REVIEW

**Comment by missirol** [comment]
please abort

**Comment by missirol** [comment]
test parameters:
  - pull_request = #35890

**Comment by missirol** [comment]
please test

**Comment by missirol** [comment]
+hlt

 * related to the crash observed in [`CMSSW_12_1_X_2021-10-27-2300`](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc900/CMSSW_12_1_X_2021-10-27-2300/unitTestLogs/RecoTauTag/HLTProducers#/); see [CMSHLT-2150](https://its.cern.ch/jira/browse/CMSHLT-2150) for more information
 * despite the label, this PR did not require any externals (and the other PR, which fixed one of the tests, is already merged)

**Comment by qliphy** [comment]
+1

**Pull request merged**
