### PR TITLE
FastSim: clean up track fitter cfg, enable tracking to run standalone

### PR DESCRIPTION
**Pull request by lveldere**
- remove no longer used configuration for track fitters
- enable tracking to run standalone

### CODE REVIEW

**Comment by lveldere** [comment]
please test

**Comment by lveldere** [comment]
@ANSH0712 
after this pr gets merged, fastsim tracking should again run standalone,
w/o needing to load Configuration/StandarSequences/python/Reconstruction_cff.py

**Comment by lveldere** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
