### PR TITLE
[L1T] Add PF developments for L1T phase-2 (new)

### PR DESCRIPTION
**Pull request by cecilecaillol**
#### PR description:

Same as https://github.com/cms-sw/cmssw/pull/38045, https://github.com/cms-sw/cmssw/pull/38047, https://github.com/cms-sw/cmssw/pull/37536

Original description: "This is another PR to port all L1T Phase-2 developments to cms-sw. This PR targets the particle flow code. It includes several PRs made locally, the details of which can be found in the twiki https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideL1TPhase2Instructions and in the cms-l1t-offline branch."

This version of the PR has the reorganization of the code to have a structure more CMS friendly, and has the previous commits squashed into one for clarity. It also fixes the DQM problem mentionned in the previous PRs.

### CODE REVIEW

**Comment by cecilecaillol** [comment]
please test

**Comment by cecilecaillol** [comment]
please test

**Comment by cecilecaillol** [comment]
+l1

**Comment by cecilecaillol** [comment]
@AdrianoDee Sorry this is still the same big PR :) But I think this time it can be merged! Can you please sign again?

**Comment by AdrianoDee** [comment]
Hi @cecilecaillol, just two minor comments about something I may had overlooked:

- there is a bunch of changes in the DQM plots (mainly in the L1T Correlator) for few workflows. I imagine these are mostly expected. Just checking since not all of them are "obvious" improvements. Just an example from `39634.999`

image

- there are some `existsAs` methods that could be cleaned in a further PR (that is something I have understood will anyway come given some of this code need to be cleaned or deleted).
 
this is good to go for me.

**Comment by cecilecaillol** [comment]
> Hi @cecilecaillol, just two minor comments about something I may had overlooked:
> 
>     * there is a bunch of changes in the DQM plots (mainly in the L1T Correlator) for few workflows. I imagine these are mostly expected. Just checking since not all of them are "obvious" improvements. Just an example from `39634.999`
> 
> 
> image
> 
>     * there are some `existsAs` methods that could be cleaned in a further PR (that is something I have understood will anyway come given some of this code need to be cleaned or deleted).
> 
> 
> Anyway this PR is good to go for me.

Thanks @AdrianoDee ! We will follow-up on both points in next PRs (we have a few DQM changes to make, and we will clean some files and check if there are some existsAs left)

**Comment by cecilecaillol** [comment]
@AdrianoDee If the PR is good to go from your side, could you please add the upgrade signature?

**Comment by drankincms** [comment]
@cecilecaillol @AdrianoDee Thanks for flagging. These all look expected to me. The PF results should be and are unchanged, and there should be some PUPPI differences as we see. This brings them more in line with what I would have expected.

**Comment by cecilecaillol** [comment]
@perrotta, @dpiparo, @qliphy Can this be merged please? We need this PR backported to 12_4 for our MC production, as well as other PRs depending on this one, and it is getting tight for us to get everything ready before 12_4 closes.

**Comment by perrotta** [comment]
@drankincms dqm comparisons for Puppi plots are the same as for previous versions of this PR, e.g.:
image

In https://github.com/cms-sw/cmssw/pull/38047#issuecomment-1142070206 you were claiming that "It looks like the switch from l1pfCandidates to l1ctLayer1 hasn't been propagated here if I am reading things correctly. This change is in the l1t-offline branch, @cecilecaillol could you add that change to this PR to fix perhaps?"

As far as I understand this change was not propagated here, and these plots witness an error in the implementation. But you comment of yesterday in https://github.com/cms-sw/cmssw/pull/38230#issuecomment-1149880528 actually contradicts it.

Maybe I am missing some intermediate info (sorry, but I'm curently in vacation and I can hardly follow the whole thread) but could you please make clear:
- Is that an error, or not?
- If it is an error, and it can be fixed by adding some already prepared code, why don't you do it now? As @AdrianoDee also pointed out, if some wrong distribution remains in the reference plots, it will be more difficult to fix them in the future.

For what concerns all other comments of mine I made in https://github.com/cms-sw/cmssw/pull/38047#pullrequestreview-984743893, I see that they were all taken into accont, even if some further cleaning has to be expected. I would have preferred cleaning in this PR already, thus avoiding having to review and maintain some code which is already known to be obsolete, but if it is easier for you doing it in two steps, please proceed as you believe it is more practical: ok for me to let them in for the moment.

**Comment by drankincms** [comment]
Maybe just to add: sorry for the confusion here, perhaps my use of "expected" was a bit ambiguous. I meant that indeed I think it is expected that these look as they do given that the DQM has not been updated to take the new correct emulation.

**Comment by perrotta** [comment]
+1
- Meant to be an intermediate step.
- Further fixes and cleanings expected in subsequent PRs

**Pull request merged**
