### PR TITLE
74X 25ns HLT round three

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
74X 25ns HLT round three of 25ns HLT menu updates
Based on 7410patch1
Includes previous PR #10834

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by Martin-Grunewald** [comment]
@perrotta 
I would have preferred you'd make new PRs for 74 and 75, so as to keep the "rounds" in sync...

**Comment by Martin-Grunewald** [comment]
please test

**Comment by perrotta** [comment]
Well, we could re-title the other two PR's as "round three and four"  
(which is sort of thing I had already in mind).
A.


Martin Grunewald <notifications@github.com> ha scritto:

**Comment by fwyzard** [comment]
Andrea, Martin,
could you change *relval25ns* to point *25ns14e33_v4* in
Configuration/HLT/python/autoHLT.py ?

For all of 74x / 75x / 76x .

Ciao,
.Andrea

**Comment by Martin-Grunewald** [comment]
@fwyzard 
NO, because HLT v4 requires v5 of the L1T menu.
We can not change until/unless v5 L1T is part of the standard GT.
But we can not do so for 74X because that is supposed to remain frozen for MC production.
For 75X and 76X we could change (no production made yet) but the standard GTs containing the v5
L1T do not exist (yet).

**Comment by fwyzard** [comment]
Understood.

However we need to setup a set of relvals in 74x and 75x (and 76x) with the
same L1 and HLT menus to validate those releases (because up to now most
HLT relvals were broken), and I would prefer to use the v4 menu rather than
the older ones.

For 74x I'll (ask STEAM to) check with PdmV if they can use a non-standard
global tag and menus for the relvals.
For 75x and 76x we should switch, also in view of the next MC production
(whenever it starts).

Ciao,
.Andrea

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by davidlange6** [comment]
@Martin-Grunewald - do you see why this changes the default workflows? (at least thats what the PR tests say)

**Comment by Martin-Grunewald** [comment]
@davidlange6 
The frozen MC menus were not changed, but the development menus are changed, of course.
Also, we fixed some event-content bugs to recover DQM, so it may be related to that.
What workflow specifically?

**Comment by davidlange6** [comment]
I looked at 25202 and 50202



On Sep 16, 2015, at 12:46 PM, Martin Grunewald <notifications@github.com<mailto:notifications@github.com>> wrote:


@davidlange6<https://github.com/davidlange6>
The frozen MC menus were not changed, but the development menus are changed, of course.
Also, we fixed some event-content bugs to recover DQM, so it may be related to that.
What workflow specifically?

**Comment by Martin-Grunewald** [comment]
These 2 are fullsim MC worklfows which run the frozen HLT menus '25ns14e33_v1' or '50ns_5e33_v1', and those HLT menus are not changed in this PR. So I can only assume there is a non-reproducability issue here somewhere in CMSSW.

**Comment by Martin-Grunewald** [comment]
Hmm, I see in the comparison GUI lots of changes unrelated to HLT (eg, JETs), and since this
PR does not change anything outside HLT, I am afraid it must be something else
such as the reproducability issue.

**Comment by davidlange6** [comment]
@cmsbuild, please test
indeed, there are hlt and jet changes, so lets try again

**Comment by Martin-Grunewald** [comment]
@davidlange6 
I reran by hand base and base+PR in CMSSW_7_4_X_2015-09-20-2300
and for the HLT detailed log of events passing thru modules, there
is no difference for 50202. So at this stage I do not understand the jenkins report.

**Pull request merged**
