### PR TITLE
Have cmsRun return the proper value when an exception is raised

### PR DESCRIPTION
**Pull request by Dr15Jones**
cmsRun was sometimes not returning the proper exit code when an exception was thrown. This pull request fixes the cases seen.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by Dr15Jones** [comment]
hold
I have a unit test to add

**Comment by Dr15Jones** [comment]
untold

**Comment by Dr15Jones** [comment]
unhold

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
