### PR TITLE
Limit `SiPixelLA` and `SiSiStripHitEff` PCL DB uploads to avoid opening spurious IoVs

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

It was noticed by shifters that in the [pclSpy](https://cms-conddb-prod.cern.ch/pclSpy/app/workflow?runClass=Collisions22) the `SiPixelLA_pcl` and `SiStripBadStripRcdHitEff_pcl` keep being updated even if other tracker worfklows are not (e.g. because the tracker is not in Global DAQ or the HV is not ON). This happens because in both cases, even if either the payload is identical to the one on the last open IOV (in the Lorentz Angle case) or if there are no valid counts to extract a hit efficiency measurement, some "null" payloads are uploaded anyway (see e.g. [LA tag](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/tags/SiPixelLorentzAngle_byPCL_v0_prompt) and [BadComponents from hit efficiency tag](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/tags/SiStripBadChannel_FromHitEfficiency_v0_prompt)). This can cause some confusion to non-expert eyes. This PR solves the issue - as well as removing the minimal DB overhead of dealing with unnecessary uploads.

#### PR validation:

`cmssw` compiles, run successfully unit tests as well as `runTheMatrix.py -l 1001.0,1001.2 -t 4 -j 8`

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

### CODE REVIEW

**Comment by tvami** [comment]
@mmusich should we aim to have this backported to 12_4_X as well?

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
@cmsbuild , please abort

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
+alca

**Comment by mmusich** [comment]
>  If you think it's useful I can do it once this is merged.

done at https://github.com/cms-sw/cmssw/pull/38491

**Pull request merged**
