### PR TITLE
Adding PPSCalTrackBasedSel AlCa Reco to autoAlca.py

### PR DESCRIPTION
**Pull request by grzanka**
#### PR description:

This PR adds PPSCalTrackBasedSel AlCa Reco to `autoAlca.py` as requested by @malbouis 
We believe this is needed for successful Trie0 replay

This work is part of ongoing campaign to have PPS included in Tier0 replay, see i.e. https://github.com/cms-AlCaDB/AlCaTools/issues/53

#### PR validation:

We are not aware of any method to test this PR. Most probably running Tier0 replay may reveal some problems.

### CODE REVIEW

**Comment by malbouis** [comment]
test parameters:

- workflows = 1041

**Comment by malbouis** [comment]
please test

**Comment by grzanka** [comment]
I see that the results of the tests seems to be unrelated to this PR.

Looking at https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-d74cb7/21781/runTheMatrixINPUT-results/4.76_ZMuSkim2012D+ZMuSkim2012D+HLTDSKIM2+RECODR1reHLT2+HARVESTDR1reHLT/step2_ZMuSkim2012D+ZMuSkim2012D+HLTDSKIM2+RECODR1reHLT2+HARVESTDR1reHLT.log
```
18-Jan-2022 19:12:47 CET  Initiating request to open file root://eoscms.cern.ch//eos/cms/store/user/cmsbuild/store/data/Run2012D/SingleMu/RAW-RECO/ZMu-15Apr2014-v1/00000/0C402854-EECC-E311-AE34-E0CB4E553656.root
%MSG-w XrdAdaptorInternal:  file_open 18-Jan-2022 19:12:48 CET pre-events
Failed to open file at URL root://eoscms.cern.ch:1094//eos/cms/store/user/cmsbuild/store/data/Run2012D/SingleMu/RAW-RECO/ZMu-15Apr2014-v1/00000/0C402854-EECC-E311-AE34-E0CB4E553656.root?xrdcl.requuid=5d95294c-96b1-4065-8a91-8997ab53be3f.
%MSG
%MSG-w XrdAdaptorInternal:  file_open 18-Jan-2022 19:12:48 CET pre-events
Failed to open file at URL root://eoscms.cern.ch:1094//eos/cms/store/user/cmsbuild/store/data/Run2012D/SingleMu/RAW-RECO/ZMu-15Apr2014-v1/00000/0C402854-EECC-E311-AE34-E0CB4E553656.root?tried=&xrdcl.requuid=40390822-f1be-49f2-9fae-57cdae4709dc.
%MSG
18-Jan-2022 19:12:48 CET  Initiating request to open file root://cms-xrd-global.cern.ch//store/data/Run2012D/SingleMu/RAW-RECO/ZMu-15Apr2014-v1/00000/0C402854-EECC-E311-AE34-E0CB4E553656.root
%MSG-w XrdAdaptorInternal:  file_open 18-Jan-2022 19:12:49 CET pre-events
Failed to open file at URL root://cms-xrd-global.cern.ch:1094//store/data/Run2012D/SingleMu/RAW-RECO/ZMu-15Apr2014-v1/00000/0C402854-EECC-E311-AE34-E0CB4E553656.root?tried=+1098cms-xrd-global011098cms-xrd-global02.cern.ch&xrdcl.requuid=7169c92b-24db-4094-91a7-7e8372734288.
%MSG
%MSG-w XrdAdaptorInternal:  file_open 18-Jan-2022 19:12:49 CET pre-events
Failed to open file at URL root://cms-xrd-global.cern.ch:1094//store/data/Run2012D/SingleMu/RAW-RECO/ZMu-15Apr2014-v1/00000/0C402854-EECC-E311-AE34-E0CB4E553656.root?tried=&xrdcl.requuid=fea25a48-6a96-458a-8ef2-b57841a47a0c.
%MSG
----- Begin Fatal Exception 18-Jan-2022 19:12:49 CET-----------------------
An exception of category 'FileOpenError' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing input source of type PoolSource
   [2] Calling RootInputFileSequence::initTheFile()
   [3] Calling StorageFactory::open()
   [4] Calling XrdFile::open()
Exception Message:
Failed to open the file 'root://cms-xrd-global.cern.ch//store/data/Run2012D/SingleMu/RAW-RECO/ZMu-15Apr2014-v1/00000/0C402854-EECC-E311-AE34-E0CB4E553656.root'
   Additional Info:
      [a] Calling RootInputFileSequence::initTheFile(): fail to open the file with name root://eoscms.cern.ch//eos/cms/store/user/cmsbuild/store/data/Run2012D/SingleMu/RAW-RECO/ZMu-15Apr2014-v1/00000/0C402854-EECC-E311-AE34-E0CB4E553656.root
      [b] Input file root://cms-xrd-global.cern.ch//store/data/Run2012D/SingleMu/RAW-RECO/ZMu-15Apr2014-v1/00000/0C402854-EECC-E311-AE34-E0CB4E553656.root could not be opened.
      [c] XrdCl::File::Open(name='root://cms-xrd-global.cern.ch//store/data/Run2012D/SingleMu/RAW-RECO/ZMu-15Apr2014-v1/00000/0C402854-EECC-E311-AE34-E0CB4E553656.root', flags=0x10, permissions=0660) => error '[ERROR] Server responded with an error: [3011] No servers are available to read the file.
' (errno=3011, code=400). No additional data servers were found.
      [d] Last URL tried: root://cms-xrd-global.cern.ch:1094//store/data/Run2012D/SingleMu/RAW-RECO/ZMu-15Apr2014-v1/00000/0C402854-EECC-E311-AE34-E0CB4E553656.root?tried=&xrdcl.requuid=fea25a48-6a96-458a-8ef2-b57841a47a0c
      [e] Problematic data server: cms-xrd-global.cern.ch:1094
      [f] Disabled source: cms-xrd-global.cern.ch:1094
----- End Fatal Exception -------------------------------------------------
```

**Comment by francescobrivio** [comment]
@perrotta @qliphy @smuzaffar before re-triggering the tests again do we know if the issue with `wf 4.76` is solved?

**Comment by perrotta** [comment]
> @perrotta @qliphy @smuzaffar before re-triggering the tests again do we know if the issue with `wf 4.76` is solved?

I think it is not yet solved, at least tests keep failing because of it
I'd simply ignore that test for now, and consider the tests as passed if there are no issues in all other workflows.
(However, at some point one should either make available somewhere else the now unreachable input file, or remove that workflow from the list of those used for PR tests)

**Comment by smuzaffar** [comment]
Workflow 4.76/step2 is failing in all release cycles. Previously workflow 4.76/step2 was using `/store/data/Run2012D/SingleMu/RAW-RECO/ZMu-15Apr2014-v1/00000/0A3C1F91-2ECD-E311-8E64-90E6BA442F3F.root` file ( [see details of used files here](https://es-cmssdt.cern.ch/kibana/app/kibana#/discover?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-15d,to:now))&_a=(columns:!(lfn,release),filters:!(('$state':(store:appState),exists:(field:lfn),meta:(alias:!n,disabled:!f,index:'3fc29390-88a1-11ea-8096-bf2a4db063ef',key:lfn,negate:!f,type:exists,value:exists)),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'3fc29390-88a1-11ea-8096-bf2a4db063ef',key:name,negate:!f,params:(query:'4.76%2Fstep2'),type:phrase,value:'4.76%2Fstep2'),query:(match:(name:(query:'4.76%2Fstep2',type:phrase))))),index:'3fc29390-88a1-11ea-8096-bf2a4db063ef',interval:auto,query:(language:kuery,query:''),sort:!('@timestamp',desc)))) . Three days ago dasgoclient results were changes for `dasgoclient --limit 0 --query 'file dataset=/SingleMu/Run2012D-ZMu-15Apr2014-v1/RAW-RECO run=208307` were [changed](https://github.com/cms-sw/cms-sw.github.io/commit/370d51219cf2265c9206ae71ada7a3314d0a7239#diff-156a34b6c5a066b5e9f6bf06e4af83d6bb185278b83754d3a1891cae49d338d3) and now the first file is returns is `/store/data/Run2012D/SingleMu/RAW-RECO/ZMu-15Apr2014-v1/00000/0C402854-EECC-E311-AE34-E0CB4E553656.root` ( which is not in our cache and is also not available anywhere. 

I think we need to change the input data for this relval. Currently this worklow asks for folloiwng
```
echo '{
"208307":[[1,268435455]]
,"207454":[[1,268435455]]
}' > step1_lumiRanges.log 2>&1
(dasgoclient --limit 0 --query 'file dataset=/SingleMu/Run2012D-ZMu-15Apr2014-v1/RAW-RECO run=208307 site=T2_CH_CERN'
dasgoclient --limit 0 --query 'file dataset=/SingleMu/Run2012D-ZMu-15Apr2014-v1/RAW-RECO run=207454 site=T2_CH_CERN') | ibeos-lfn-sort -u > step1_dasquery.log
```

**Comment by malbouis** [comment]
+alca

- very simple change according to PR description.

**Comment by francescobrivio** [comment]
> I think we need to change the input data for this relval. Currently this worklow asks for folloiwng
> 

maybe @cms-sw/pdmv-l2?

**Comment by mmusich** [comment]
randomly asking here, since it has been already touched upon:

> I think we need to change the input data for this relval. Currently this worklow asks for folloiwng

@cms-sw/orp-l2 is there already a solution to the persistent wf 4.76 problem in PRs or anyone working on it? Should it be temporarily removed from the matrix?

**Comment by qliphy** [comment]
> randomly asking here, since it has been already touched upon:
> 
> > I think we need to change the input data for this relval. Currently this worklow asks for folloiwng
> 
> @cms-sw/orp-l2 is there already a solution to the persistent wf 4.76 problem in PRs or anyone working on it? Should it be temporarily removed from the matrix?

An issue has been opened and we can follow up there.  https://github.com/cms-sw/cmssw/issues/36771

**Comment by tvami** [comment]
urgent

**Comment by grzanka** [comment]
Closing in favour of https://github.com/cms-sw/cmssw/pull/36702 as suggested in https://github.com/cms-sw/cmssw/pull/36702#issuecomment-1018693912

**Pull request closed without merging**
