### PR TITLE
Large speed improvement for HGCal Hex Sim.

### PR DESCRIPTION
**Pull request by lgray**
HGCSD sped up by factor of 1000 in case of Hex geometry.

Remove unnecessary expensive function inside loop within HGCal detector constants description.

### CODE REVIEW

**Comment by lgray** [comment]
@cmsbuild please test

You can test this speed up yourself by taking one of the HGCal unit tests and using the "2023Dev" geometry.

**Comment by lgray** [comment]
@vandreev11 @cseez @bsunanda @kpedro88 @sethzenz

**Comment by lgray** [comment]
Can post igprof results if desired.

**Comment by lgray** [comment]
There are actually a few places in the HGCalDDDConstants that could be sped up significantly, which will ve important since it will get used in reco code.. I'll try to review this code more thoroughly, but address in a separate PR.

**Comment by lgray** [comment]
@Dr15Jones This is a limitation in clang itself. Should I just use ```0.5773502693``` instead?

**Comment by Dr15Jones** [comment]
Sure.

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by davidlt** [comment]
@lgray Clang is correct here as according to C++ Standard `std::sqrt` is not `constexpr` and actually C++14 explicitly forbids to declare any standard library function as `constexpr` unless it's specified in the standard.

There was a long discussions for years regarding this. I believe GCC treats any compiler built-in intrinsic as `constexpr` and `std::sqrt` is lowered to `__builtin_sqrt `.

**Comment by ianna** [comment]
+1

**Comment by lgray** [comment]
@civanch @mdhildreth Please take a look at this soon. Thanks!

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
