### PR TITLE
[HGCAL] CaloParticleSelector selects non-converted CP

### PR DESCRIPTION
**Pull request by ebrondol**
#### PR description:

This PR correctly identify the CaloParticle which have converted in the Tracker using the `getPositionAtBoundary` and `getMomentumAtBoundary` methods from the SimTrack associated. Before this was done looking at the number of SimClusters associated, but this method was not fully correct: in the specific case of the single photons, they always had 2 SimClusters because of pair production but not always was in the Tracker. 
An exception is introduced for the electrons which most of the time undergo bremsstrahlung and therefore are always converting in the Tracker. 

It would be great if this PR manage to get into 11_3_0.

#### PR validation:

- Efficiency on single photons before the PR: 
image
- Efficiency on single photons after the PR: 
image

@apsallid @lecriste @rovere @felicepantaleo

### CODE REVIEW

**Comment by rovere** [comment]
@cmsbuild please test

**Comment by jfernan2** [comment]
@ebrondol apart from the clang-tidy warnings, the PR is introducing a lot of changes in HGCAL folder for phase2 samples, could you please have a look and see if there are not any unexpected changes?
Thanks

**Comment by ebrondol** [comment]
Hi @jfernan2 , unfortunately when I access the link to the GUI I have '500 Internal Error'. It have double checked and it seems it's not a problem from my side. Could you please let me know when the link/the GUI is fixed?

**Comment by jfernan2** [comment]
do this link work for you?
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_11_3_X_2021-03-30-2300+0a6364/41973/dqm-histo-comparison-summary.html
Down there you have all the differences for every wf tested

**Comment by jfernan2** [comment]
I can see all plots, e.g.
https://tinyurl.com/ydl5or4m
Can you clarify what you mean by not clickable?
Since the folder names are very large, you should select size=large in the top left menu of the GUI

**Comment by ebrondol** [comment]
We are currently running further test. We will update the PR shortly.

**Comment by ebrondol** [comment]
@jfernan2 
@apsallid and I checked the differences and we can confirmed that they are all expected.

**Comment by jfernan2** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
