### PR TITLE
Run3-gex79 Take P4 as the default PPS for Run3 scenario

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Take P4 (removing multiple definition of the same material) as the default PPS for Run3 scenario

#### PR validation:

Use theMatrix test workflows and specific Run1 scenarios

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
@fabferro , FYI

**Comment by cvuosalo** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

**Comment by qliphy** [comment]
+1

**Pull request merged**
