### PR TITLE
Added Service callbacks for Run and Lumi writing

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

The new signals are used to announce when starting and ending of the OutputModule write phases occur for Runs and LuminosityBlocks.

#### PR validation:

All framework unit tests pass.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1
the unit test failure happens also in the IB.

**Comment by fabiocos** [comment]
please test

the failure is unrelated to this PR, a fix has just been merged

**Comment by Dr15Jones** [comment]
@fabiocos the unit test fix evidently was not picked up.

**Comment by fabiocos** [comment]
+1

the failure is unrelated to this PR

**Comment by fabiocos** [comment]
merge

**Pull request merged**
