### PR TITLE
Particle gain calibration 

### PR DESCRIPTION
**Pull request by quertenmont**
Several bug fix and script automation,
but also some developments like:
- multi-run harvesting of PCL files
- tracker map plots
- pixel response monitoring
  To be back-ported to 75X too

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
@quertenmont this branch needs now to be rebased. Can you take care?

**Comment by quertenmont** [comment]
yes Marco, I can rebase it.
But to avoid doing the job twice, i'd prefer that we converge on the "cloned" PR before rebasing this one.

**Comment by mmusich** [comment]
in principle we should first allow the 76X version, examine the relvals and then approve the backport. Sorry for that, I didn't notice in the first place that discussion was going on in the 75X version. I have no objections to sign #10044 once this one is ok.

**Comment by quertenmont** [comment]
ok, I'll do it this afternoon then

2015-08-11 10:40 GMT+02:00 Marco Musich <notifications@github.com>:

> in principle we should first allow the 76X version, examine the relvals
> and then approve the backport. Sorry for that, I didn't notice in the first
> place that discussion was going on in the 75X version. I have no objections
> to sign #10044 <https://github.com/cms-sw/cmssw/pull/10044> once this one
> is ok.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cms-sw/cmssw/pull/10043#issuecomment-129771717>.
>



-- 
---------------------------------------------------------
Loic Quertenmont - European Organization for Nuclear Research (CERN) - CMS
experiment
Office CERN   : bldg.40, RB-08
Phone CERN    : +41 2276 71548
Mobile BE     : +32 474 831531
WWW           : http://www.fynu.ucl.ac.be/users/l.quertenmont/

**Comment by quertenmont** [comment]
For rebasing I had to create a new branch and therefore a new PR
See #10680 from now on.

**Pull request closed without merging**
