### PR TITLE
PR for HLT online DQM monitoring code for HI run in 80X

### PR DESCRIPTION
**Pull request by varuns23**
The PR is made using CMSSW_8_0_20.

@mtosi @vanbesien @diguida @dmitrijus @silviodonato

### CODE REVIEW

**Comment by silviodonato** [comment]
please test

**Comment by diguida** [comment]
@varuns23 two comments:

* Please make a PR against the vanilla `CMSSW_8_0_X` branch
* In order this to be scrutinised and accepted, please make a corresponding PR in the development branch, namely `CMSSW_8_1_X`

**Comment by diguida** [comment]
Comment to self: the PR in 8.1.X is #16346

**Comment by fwyzard** [comment]
-1

please make a PR for the standard 8.0.x branch, and close this one.

**Comment by varuns23** [comment]
Already made new one: https://github.com/cms-sw/cmssw/pull/16355

Closing this PR.

**Pull request closed without merging**
