### PR TITLE
add plots of wire group and strip numbers for all chambers in 73x (rebased)

### PR DESCRIPTION
**Pull request by danduggan**
a whole bunch of l1 plots for csc track finder chamber monitoring in l1dqm. rebased #8121 to merge it into cmssw732patch5.

### CODE REVIEW

**Comment by deguio** [comment]
@rjwang 
could all these MEs be booked as TH2F instead of TH2D?
ciao and thanks,
F.

**Comment by rjwang** [comment]
Hi Dan, 

I double checked the DQMStore Class:
https://cmssdt.cern.ch/SDT/doxygen/CMSSW_7_3_2/doc/html/d5/df7/classDQMStore.html
the recent method I am using is TH2F (see DQMStore::book2D)
the DQMStore::book2DD will call TH2D.

**Comment by deguio** [comment]
+1
right, don't know why I was convinced it was booking double.
I think at this point the PR can be integrated. a report at the dqm meeting will be needed as we agreed.
thanks,
F.

**Comment by rjwang** [comment]
No problem, we will prepare the slides for the meetings on Mar. 31.

**Comment by deguio** [comment]
@davidlange6 
this can also be merged for the coming 734_p1
it has been tested online the past week.

thanks,
F.

**Comment by davidlange6** [comment]
@deguio-
I can if there is an agreement to address my comment in 74x/75x (which there is not yet afaik)

**Comment by rjwang** [comment]
@davidlange6 
sorry, I totally miss the comment for 74x/75x, I will address those comments.

**Comment by deguio** [comment]
thanks

**Comment by rjwang** [comment]
two commits for 74X and 75X with nesting if statement are made:
https://github.com/rjwang/cmssw/commit/9ae93d8a9c341b23212f6f2f2f1a85bba29c0c4f
https://github.com/rjwang/cmssw/commit/321fa34faa9499bf2d6e3f8a3799003d3a92cfd9

**Comment by davidlange6** [comment]
+1

**Pull request merged**
