### PR TITLE
bsunanda:Run2-hcx126 Correct the name of collection in 3 cfi files of HCAL AlCaReco's

### PR DESCRIPTION
**Pull request by bsunanda**

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by franzoni** [comment]
documentation of the purpose of this PR:
https://github.com/cms-sw/cmssw/pull/18892#issue-230512055
( we close that one since it developed conflicts and aims at doing the same as here )

please @bsunanda 
never place PR's with no description

**Comment by franzoni** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
