### PR TITLE
 expand tracker-driven coverage for electron seeds; jetCore mitigation (bp of #35892)

### PR DESCRIPTION
**Pull request by slava77**
Changes in this PR were motivated to mitigate the situation with tracks reconstructed multiple times, one of them jet core after introduction of mkFit to the non-jetCore iterations. 

This was presented in TRK POG on Nov 1: https://indico.cern.ch/event/1092090/#3-interplay-in-high-pt-electro

see more details in #35892

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by perrotta** [comment]
backport of #35892

**Comment by slava77** [comment]
@swagata87 
I made this backport as a follow up to the discussion in the TRK POG.
Will this actually be used for EGM ID training in 12_1_X?
I thought that the training was expected in time for Nov 9 deadline ("12_2" last open).
Will there be enough time to do it if 12_1 with this PR is built this Friday?

**Comment by swagata87** [comment]
> @swagata87 I made this backport as a follow up to the discussion in the TRK POG. Will this actually be used for EGM ID training in 12_1_X? I thought that the training was expected in time for Nov 9 deadline ("12_2" last open). Will there be enough time to do it if 12_1 with this PR is built this Friday?

Hi Slava, 
let me explain EGM's plan and my understanding.

1) Currently we are training PF Egamma ID using samples produced with 12_0 release. It is almost complete and we expect to make a PR by the end of this week (5th Nov), to make it to 12_2_0_pre2. There is no possibility to include this PR is our current PF Egamma ID training. 

2) But, another re-training of PF Egamma ID is planned. That is to be done using samples produced with 12_1 in next months. We informed PPD that we will request O(100M) events to be produced with 12_1 for this retraining. The original reason of this retraining was to include eta-extended-electrons(EEE) in the training of PF Egamma ID. Recall that EEEs went into release in 12_1. I thought that it will be good to have your PR included as well.

I am a bit lost in new and old plans of 12_1 and 12_2 of the next campaign of sample production. 
It looks like 12_1 will be used only to produce GEN-SIM. And 12_2 will be used to run RECO and PAT step.
If that is the case, then this backport is not necessary as it concerns RECO step. 
Apologies for the confusion. 
But if the RECO step is to be run using 12_1 then having this backport is a good idea.

**Comment by slava77** [comment]
Hi Swagata,

Thank you for the clarification on the short term plans

>     2\. But, another re-training of PF Egamma ID is planned. That is to be done using samples produced with 12_1 in next months. We informed PPD that we will request O(100M) events ...

the description for this sounds like the plan for what's currently called 12_2 release (recall that the indexing/naming of the releases changed about a week ago).

@rappoccio please check/confirm about large physics reco samples in 12_2 (vs not in 12_1).

**Comment by swagata87** [comment]
tagging Linda 
@lfinco

**Comment by slava77** [comment]
+reconstruction

for https://github.com/cms-sw/cmssw/pull/35958  76ceb8e 
- code changes are the same as #35892 (it's the same topic branch)
- see more details on the master version signoff in https://github.com/cms-sw/cmssw/pull/35892#issuecomment-960902350
- based on the messages above, it seems like this backport is not really going to be used for high-stats, but I think that it's still a "nice to have".

**Comment by perrotta** [comment]
Thank you @slava77 
This "nice to have" PR could delay 12_1_0, which is otherwise ready to be cut even now, by about 1 day. Such a short delay doesn't seem a big issue to me:  but please @rappoccio let us know which is the preferred plan for PPD

**Comment by perrotta** [comment]
The master version of this PR, #35892, was just merged. Unless unexpected issues will show up from the nightly builds, tomorrow we can merge this PR in 12_1_X and start building 12_1_0

From the discussions in the github thread of #35892 it must be clear that this PR will bring
- small differences in egamma related objects
- about 1% increase of fake electrons in the QCD sample

and the full extent of what above can only be assessed with a complete validation.

According to the declared purposed of 12_1_0 I see no issue in merging it, even if the exact impact on egamma objects cannot be quantified yet. I'm just pointing it out here in case it was not evident to anybody.

**Comment by perrotta** [comment]
+1
- Let merge this PR so that it can be tested with the nightly 12_1_X IB
- The master version wasn't fully tested in the IBs yet, but I don't expect problems with it: at worst, we will revert this tomorrow morning and build 12_1_0 as well.

**Pull request merged**
