### PR TITLE
Issue exception for ROOT file forward incompatiblity problem

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

Throw an exception if the ParameterSet parsing finds an unknown entry type. This problem is occurring presently in older releases if they try to read files which contain the new string encoding for ParameterSets.

#### PR validation:

This same code was tested in CMSSW_12_6 and properly throws the proper exception type containing the proper information when reading a file generated in CMSSW_13_3.

#### Backporting
This is meant to be back ported to all active releases before CMSSW_13_3:  13_2, 13_1, 13_0, 12_6, 12_4 and 10_6.

part of makortel/framework#804

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by makortel** [comment]
Comparisons show the usual
* https://github.com/cms-sw/cmssw/issues/39803
* https://github.com/cms-sw/cmssw/issues/43293
* https://github.com/cms-sw/cmssw/issues/43790

**Comment by makortel** [comment]
+core

**Comment by rappoccio** [comment]
+1

**Pull request merged**
