### PR TITLE
Rp digi producer esConsumes

### PR DESCRIPTION
**Pull request by clemencia**
This introduces the appropriate event setup handling for esConsumes migration in the PPS silicon strip digitization. Solves #35094 

Validated using a adhoc PPS full simulation with 2017 conditions (since PPS strips were present in 2016 and 2017 only).

### CODE REVIEW

**Comment by clemencia** [comment]
style patch applied

**Comment by civanch** [comment]
@clemencia , what is the status of this PR?

**Comment by clemencia** [comment]
@mundim  @fabferro  coming back to this PR, can we justify to NOT use modifiers but save the copies specific for 2016/2017 for legacy? We expect this to never be used centrally, correct?

**Comment by mundim** [comment]
> @clemencia , what is the progress for this PR?

Hi @civanch. This code is related to the strip sensor that was used only for Run 2 data. Given the lack of person power and the fact that it (likely) will never be executed, can we think about skipping this task? In case we go towards the back porting of PPS to run 2 data, this should be a top priority. I'm speaking "we" but as I said, I'm not in PPS anymore, just adding by thought about it. Cheers.

**Comment by civanch** [comment]
please test

Situation with this PR is unclear, at least, let us test it first.

**Comment by civanch** [comment]
@perrotta , can you close this PR, which seems to stack forever.

**Comment by perrotta** [comment]
Closing
See also https://github.com/cms-sw/cmssw/pull/35684#issuecomment-1033961657

**Pull request closed without merging**
