### PR TITLE
[12_3_X]Restore sampicSubDetId backward compatibility

### PR DESCRIPTION
**Pull request by ChrisMisan**
#### PR description:
This is a backport of #38338 and #38366

#### PR validation:
PR was tested with 136.8562 which was previously failing.

### CODE REVIEW

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
@cmsbuild , please abort

**Comment by tvami** [comment]
test parameters:
  - workflows = 136.8562

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by yuanchao** [comment]
A backport of https://github.com/cms-sw/cmssw/pull/38338 and https://github.com/cms-sw/cmssw/pull/38366 by adding back sampicSubDetId.
* SA checks and matrix wf tests passed
* no significant difference seen in DQM

**Comment by clacaputo** [comment]
+reconstruction

**Pull request merged**
