### PR TITLE
Fix MuEGCleaning input collections

### PR DESCRIPTION
**Pull request by mmarionncern**
Fix the input EGamma collections used to compute the EG fix for the re-miniAOD campaign. 
One can still derive the fully corrected MET from what is inside the miniAODs, but that would fix the MuEG collection

### CODE REVIEW

**Comment by gpetruc** [comment]
Should we make a patch?
It can also be fixed in --customize_commands, though it's not a good approach.
The other option is to ignore this, and tell people to do it right at analysis level.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
How incorrect is it now? 100℅, 10℅?

**Comment by slava77** [comment]
On 2/2/17 6:56 PM, Giovanni Petrucciani wrote:
> Should we make a patch?
> It can also be fixed in --customize_commands, though it's not a good
> approach.
> The other option is to ignore this, and tell people to do it right at
> analysis level.

I suppose, if we find something bad from the pilot injection and some
fix will be needed anyways, this can go in.

**Comment by davidlange6** [comment]
a new record for the time between a talk announcing all was done and the first bug?

**Comment by davidlange6** [comment]
can make a patch tomorrow once @slava77 approves if its useful..

**Comment by slava77** [comment]
On 2/2/17 9:23 PM, David Lange wrote:
> can make a patch tomorrow once @slava77 <https://github.com/slava77>
> approves if its useful..

To elaborate on my earlier message about how wrong this bug makes things,
I'd like to understand the cost to analysts to fix this bug at miniAOD
level.
(I'm just not at all convinced that this will be the last bug fix)

Do we have all the products in place in miniAOD (we stored various
alternatives)
and is there a setup to redo it from miniAOD already?

**Comment by slava77** [comment]
local test with /DoubleEG/sharper-Run2016E-23Sep2016-v1_AOD_DiHEEPWOSS_GainSwitch shows differences only in slimmedMETsMuEGClean (From slides yesterday: slimmedMETsMuEGClean is supposed to be corrected for muons and for the ecal gain switch on e/γobjects [ this is likely to be the recommended one to use ]). ).

slimmedMETsMuEGClean.pt is much smaller in some events
patmets_slimmedmetsmuegclean__pat obj pt delta
patmets_slimmedmetsmuegclean__pat obj pt

which is suggestive of an improvement

Still, there is something odd:
 slimmedMETsMuEGClean.sumEt is now smaller 
patmets_slimmedmetsmuegclean__pat obj sumet delta

 
Looking at the changes in more detail: the old version was using identical inputs to corMETElectronMuEGClean and corMETEPhotonsMuEGClean which would mean they were 0; the fix now, apparently, makes these corrections equal to the correction size of the egm objects.
However, the puzzling part is the reduction in sumET. Shouldn't it be going up?
Is there a bug in https://github.com/cms-sw/cmssw/blob/CMSSW_9_0_X/PhysicsTools/PatUtils/plugins/ShiftedParticleMETcorrInputProducer.cc or am I missing something?
[if the sumEt in the shifted is buggy, I guess we are supposed to live with it in 80X because the code is 5 years old]

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/17395	56f062b
- pick appropriate base egamma collections to compute corrections for slimmedMETsMuEGClean
- jenkins tests pass and comparisons with baseline show no differences (none expected given that this change affects only the customized PAT)
- local checks show changes only in slimmedMETsMuEGClean, see details in https://github.com/cms-sw/cmssw/pull/17395#issuecomment-277175471 [the effect of the fix as seen in expanded config appears to be logically correct]

**Comment by mmarionncern** [comment]
@slava77 Without that fi the MuEG MET does nto receive the EGamma corrections, and one would have to extract it from the other METs and reapply it on top of the Mu corrected MET. So it is not vital, but preferable

**Comment by gpetruc** [comment]
Hi,

Sorry in my tests i had checked the jets and the muon corrections to the
met but not the eg ones.


If making a patch is not that expensive, and the patch can be available by
end of the day, i think it would be beneficial (there may indeed be other
bugs in less used items like met uncertainties or significance, but that
has very often been the case, while having the nominal met value bugged in
some events is more annoying)
Alca is checking that the GT with the JECs is okay so things have not
started yet.

Looking at some events, the correction to the met vector seems to have the
correct sign, which is good.
From the code, sumEt looks indeed computed with the wrong sign but i agree
that we can live with it, it's the px and py that really matter.

Giovanni


Il 03 Feb 2017 7:42 AM, "Slava Krutelyov" <notifications@github.com> ha
scritto:

+1

for #17395 <https://github.com/cms-sw/cmssw/pull/17395> 56f062b
<https://github.com/cms-sw/cmssw/commit/56f062b07eae803568c989333e3aa49e0c0ebf0b>

   - pick appropriate base egamma collections to compute corrections for
   slimmedMETsMuEGClean
   - jenkins tests pass and comparisons with baseline show no differences
   (none expected given that this change affects only the customized PAT)
   - local checks show changes only in slimmedMETsMuEGClean, see
details in #17395
   (comment)
   <https://github.com/cms-sw/cmssw/pull/17395#issuecomment-277175471> [the
   effect of the fix as seen in expanded config appears to be logically
   correct]

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/cms-sw/cmssw/pull/17395#issuecomment-277176249>, or mute
the thread

**Comment by slava77** [comment]
On 2/3/17 8:35 AM, Giovanni Petrucciani wrote:
> Looking at some events, the correction to the met vector seems to have the
> correct sign, which is good.
>>From the code, sumEt looks indeed computed with the wrong sign but i agree
> that we can live with it, it's the px and py that really matter.

@mmarionncern , please submit a fix for ShiftedParticleMETcorrInputProducer.cc to 90X or direct to someone
else to follow it @zdemirag @gouskos 
it may be worth to check that it hasn't propagated to other similar MET correction algorithms

**Comment by slava77** [comment]
On 2/3/17 8:35 AM, Giovanni Petrucciani wrote:
> 
> If making a patch is not that expensive, and the patch can be available by
> end of the day, i think it would be beneficial (there may indeed be other
> bugs in less used items like met uncertainties or significance, but that
> has very often been the case, while having the nominal met value bugged in
> some events is more annoying)
> Alca is checking that the GT with the JECs is okay so things have not
> started yet.

a light patch should take about 4 hours to show up from build start to
upload end

**Comment by mmarionncern** [comment]
@slava77 
the ShiftedParticleMETcorrInputProducer class is corrected for 90X in :
#17405

**Comment by davidlange6** [comment]
(or should we wait a while longer?)

**Comment by slava77** [comment]
On 2/3/17 10:11 AM, David Lange wrote:
> I guess its <4 hours - but should we go ahead now and then re-declare
> that all is done and ready for production with the patch in place?

maybe ask on HN about the progress of the pilot injection

**Comment by davidlange6** [comment]
the pilot is injected and completely processed

**Comment by gpetruc** [comment]
Ok so we should go for it.

Giovanni

Il 03 Feb 2017 8:52 AM, "Slava Krutelyov" <notifications@github.com> ha
scritto:

**Pull request merged**
