### PR TITLE
Cleaning of several Analysis packages

### PR DESCRIPTION
**Pull request by silviodonato**
#### PR description:

This PR removes several obsolete Analysis packages. The cleaning has been already discussed with PAG/POG, but it will be further discussed with Physics Coordination.
The list of the obsolete modules is here https://docs.google.com/spreadsheets/d/10jq3dyvypt0axQ_l_ZL3GQQxkkyKek3VDQM2DrowhNI/edit#gid=0

This PR requires #32916, #32914, and it is also related to #32915.

The packages which are removed are
```
DiffractiveForwardAnalysis/Configuration
DiffractiveForwardAnalysis/Skimming
ElectroWeakAnalysis/Configuration
ElectroWeakAnalysis/Skimming
ElectroWeakAnalysis/Utilities
ElectroWeakAnalysis/WENu
ElectroWeakAnalysis/WMuNu
ElectroWeakAnalysis/ZEE
ElectroWeakAnalysis/ZMuMu
QCDAnalysis/ChargedHadronSpectra
QCDAnalysis/Configuration
QCDAnalysis/Skimming
QCDAnalysis/UEAnalysis
HeavyFlavorAnalysis/Configuration
HeavyFlavorAnalysis/Skimming
HiggsAnalysis/HiggsToGammaGamma
HiggsAnalysis/Configuration
HiggsAnalysis/Skimming
TopQuarkAnalysis/Examples
TopQuarkAnalysis/TopPairBSM
SUSYBSMAnalysis/HSCP
MuonAnalysis/Configuration
```

In `SUSYBSMAnalysis/HSCP/plugins/Skim_HSCPFilter.cc`
there is the definition of `HSCPFilter` that is used in
`Configuration/Skimming/python/PDWG_EXOHSCP_cff.py`
which is eventually used in
`Configuration/Skimming/python/Skims_PDWG_cff.py`

So this PR removes also `Configuration/Skimming/python/PDWG_EXOHSCP_cff.py` and few lines in `Configuration/Skimming/python/Skims_PDWG_cff.py` (see commit https://github.com/cms-sw/cmssw/pull/32917/commits/1c7415908df0457a3611f08e2235803b699e41fa)
The last PR changing `Configuration/Skimming/python/PDWG_EXOHSCP_cff.py` was done in 2015 (https://github.com/cms-sw/cmssw/pull/7518)
`Configuration/Skimming/python/Skims_PDWG_cff.py` is not changed since we moved to github (CMSSW_6_2_0_pre8, 8 years ago) - at least.

#### PR validation:

I checked the dependencies of these packages in the rest of CMSSW code
(https://github.com/silviodonato/usercode/blob/master/checkDependencies.py)

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

No backport expected.

### CODE REVIEW

**Comment by silviodonato** [comment]
test parameters:
- pull_requests: #32916, #32914

**Comment by silviodonato** [comment]
hold
(this needs to be discussed a bit further with PC)

**Comment by silviodonato** [comment]
test parameters:
- pull_requests = #32916, #32914

**Comment by silviodonato** [comment]
please test

**Comment by silviodonato** [comment]
@cms-sw/core-l2 
- `ElectroWeakAnalysis/Utilities` appears in `Utilities/ReleaseScripts/scripts/CMSSWReleaseDependency.rules`, shall I remove that line?
- all packages appear in `Utilities/ReleaseScripts/scripts/git-publish` should I modify it? (I'd say no... it sounds something related to https://github.com/cms-sw/cms-bot/blob/master/categories_map.py)

**Comment by silviodonato** [comment]
The error is not related to this PR
```
----- Begin Fatal Exception 15-Feb-2021 13:15:41 CET-----------------------
An exception of category 'FileOpenError' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing input source of type PoolSource
   [2] Calling RootInputFileSequence::initTheFile()
   [3] Calling StorageFactory::open()
   [4] Calling XrdFile::open()
Exception Message:
Failed to open the file 'root://cms-xrd-global.cern.ch//store/data/Run2012D/SingleMu/RAW-RECO/ZMu-15Apr2014-v1/00000/007A3BD1-02CD-E311-853B-002590D0AFC8.root'
   Additional Info:
      [a] Calling RootInputFileSequence::initTheFile(): fail to open the file with name root://eoscms.cern.ch//eos/cms/store/user/cmsbuild/store/data/Run2012D/SingleMu/RAW-RECO/ZMu-15Apr2014-v1/00000/007A3BD1-02CD-E311-853B-002590D0AFC8.root
      [b] Input file root://cms-xrd-global.cern.ch//store/data/Run2012D/SingleMu/RAW-RECO/ZMu-15Apr2014-v1/00000/007A3BD1-02CD-E311-853B-002590D0AFC8.root could not be opened.
      [c] XrdCl::File::Open(name='root://cms-xrd-global.cern.ch//store/data/Run2012D/SingleMu/RAW-RECO/ZMu-15Apr2014-v1/00000/007A3BD1-02CD-E311-853B-002590D0AFC8.root', flags=0x10, permissions=0660) => error '[ERROR] Server responded with an error: [3011] No servers are available to read the file.�
' (errno=3011, code=400). No additional data servers were found.
      [d] Last URL tried: root://cms-xrd-global.cern.ch:1094//store/data/Run2012D/SingleMu/RAW-RECO/ZMu-15Apr2014-v1/00000/007A3BD1-02CD-E311-853B-002590D0AFC8.root?tried=&xrdcl.requuid=6bf4650c-fe39-4d9b-b4d0-51868268f097
      [e] Problematic data server: cms-xrd-global.cern.ch:1094
      [f] Disabled source: cms-xrd-global.cern.ch:1094
----- End Fatal Exception -------------------------------------------------
```

**Comment by silviodonato** [comment]
please test

**Comment by silviodonato** [comment]
please test

**Comment by makortel** [comment]
> @cms-sw/core-l2
> 
> * `ElectroWeakAnalysis/Utilities` appears in `Utilities/ReleaseScripts/scripts/CMSSWReleaseDependency.rules`, shall I remove that line?
> * all packages appear in `Utilities/ReleaseScripts/scripts/git-publish` should I modify it? (I'd say no... it sounds something related to https://github.com/cms-sw/cms-bot/blob/master/categories_map.py)

@smuzaffar Could you comment?

**Comment by smuzaffar** [comment]
> * `ElectroWeakAnalysis/Utilities` appears in `Utilities/ReleaseScripts/scripts/CMSSWReleaseDependency.rules`, shall I remove that line?
> * all packages appear in `Utilities/ReleaseScripts/scripts/git-publish` should I modify it? (I'd say no... it sounds something related to https://github.com/cms-sw/cms-bot/blob/master/categories_map.py)

I think Utilities/ReleaseScripts/scripts/git-publish is not used and can be dropped. It has the old categories name (CVS era). Most of this is now part of git-cms-tools.
Yes, cleanup `Utilities/ReleaseScripts/scripts/CMSSWReleaseDependency.rules`  too but that can be done in e separate PR (once this PR is merged)

**Comment by silviodonato** [comment]
please test

**Comment by silviodonato** [comment]
unhold

**Comment by silviodonato** [comment]
It requires https://github.com/cms-sw/cmssw/pull/32916

**Comment by silviodonato** [comment]
@cms-sw/pdmv-l2 I've added some lines in the PR description about the changes in `Configuration/Skimming`. Please let me know if you have further comments

**Comment by chayanit** [comment]
Let me include @kfjack to double check on skimming. Thanks in advance.

**Comment by silviodonato** [comment]
@chayanit  @kfjack I wrote to Todd Adams about a week ago who forwarded the request to the HSCP group, and he did not get any objection about the deletion of PDWG_EXOHSCP and the removal of it from Skims_PDWG_cff

**Comment by silviodonato** [comment]
@cms-sw/pdmv-l2  @kfjack do you have any comment/objection on this PR?

**Comment by chayanit** [comment]
+1
I think it is OK.

**Comment by kfjack** [comment]
+1 
Ok too. These skims are not active now.

**Comment by silviodonato** [comment]
merge

**Comment by santocch** [comment]
+1

**Pull request merged**
