### PR TITLE
BuildFiles cleaning

### PR DESCRIPTION
**Pull request by guitargeek**
#### PR description:

Another quick BuildFile cleaning PR in the style of many before (for example https://github.com/cms-sw/cmssw/pull/33858).

This PR cleans unnecessary includes from CMSSW BuildFiles that were recently added for 12_0_0_pre3

#### PR validation:

CMSSW compiles.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

No backport intended.

### CODE REVIEW

**Comment by qliphy** [comment]
please test

**Comment by cecilecaillol** [comment]
+l1

**Comment by jfernan2** [comment]
+1

**Comment by perrotta** [comment]
+reconstruction
- Technical cleaning
- Jenkins tests pass

**Comment by yuanchao** [comment]
+1

* buildfile cleaning (technical)
* compiles and unit tests passed

**Comment by civanch** [comment]
+1

**Comment by guitargeek** [comment]
@ggovi, is this okay for db?

**Comment by qliphy** [comment]
merge
@cms-sw/db-l2  Let's know if you have any comment.

**Pull request merged**
