### PR TITLE
Test ROOT Schema Evolution on TH*

### PR DESCRIPTION
**Pull request by rovere**
When an update on the ROOT external brings in schema evolution for any
object that has to be handled also by DQMGUI, trigger a test failure.
The fix of the test is trivial. This will serve as a check-and-trigger
to update the root.spec file on the comp side of cmsdist.

In the past years, it happened rarely (< 1/year). If DQM-Core/Fwk/whoever
feels like this is not an acceptable solution, I can think of something
different.

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by franzoni** [comment]
Very helpful, thanks @rovere

@klute

**Comment by dmitrijus** [comment]
+1

**Comment by rovere** [comment]
I'd like to have this PR included in 10_1_0, if possible.

**Comment by fabiocos** [comment]
@rovere I am not sure to understand the description of this PR.  In this PR I understand you are proposing a new test code to check a possible schema evolution. What might not be acceptable for Core software?

**Comment by rovere** [comment]
@fabiocos 
Ciao Fabio, when there's schema evolution this unit-test will fail even it, technically speaking, the CMSSW release could handle the schema evolution. IT's the interplay between CMSSW and DQMGUI that would be broken. Fixing the test is a no-brainer and core-dqm team can take care of it in a timely fashion. So, if this is ok (having maybe this unit-test failing for 1 IB soon after updating the ROOT external) then this PR is perfectly fine.
If you or FWK-Core is not fine with this side effect, I should think of something different.
From my personal point of view, I find this solution to be ok.

**Comment by fabiocos** [comment]
@rovere @Dr15Jones @smuzaffar @davidlange6 I am not sure whether we have similar examples in the distribution, personally I do not see it as particularly harmful, but I would like to hear possible objections

**Comment by davidlange6** [comment]
from me +1 - good to know about inconsistencies sooner rather than later.

**Comment by franzoni** [comment]
Concrete example: earlier in March the needed of evolving cmsweb to accommodate CMSSW_10_0_3 became widely known only when such release was installed at p5  ( the resolution  https://hypernews.cern.ch/HyperNews/CMS/get/cernCompAnnounce/1279.html took almost a  week, also due to extra complications ) ; having this test already in the IB would have triggered actions to reconcile root versions during the ORP, ahead of the urgency.

**Comment by smuzaffar** [comment]
I agree with @davidlange6 to catch such cases as soon as possible. 
@rovere,  Only one concern, what will happen with root6.12 and root6 master IBs, These IBs use different root version.

**Comment by rovere** [comment]
@smuzaffar 
Ciao Shahzad, when deciding how to proceed I thought of different branches being linked to different externals so that the point you raised would have been solved naturally: keep a proper test on the proper branch. Apparently, that's not the case.
But then the question is: what is the likelihood of having schema evolution on histograms on special ROOT-IBs not propagated also to the master branch? The problem here is, I guess, the timeline.
Is there a possibility to "programmatically" or "manually" turn on/off unit testing?

**Comment by davidlange6** [comment]
> On Mar 25, 2018, at 9:55 AM, Marco Rovere <notifications@github.com> wrote:
> 
> @smuzaffar
> Ciao Shahzad, when deciding how to proceed I thought of different branches being linked to different externals so that the point you raised would have been solved naturally: keep a proper test on the proper branch. Apparently, that's not the case.
> But then the question is: what is the likelihood of having schema evolution on histograms on special ROOT-IBs not propagated also to the master branch? The problem here is, I guess, the timeline.
> Is there a possibility to "programmatically" or "manually" turn on/off unit testing?

Close to 100% - but with potentially months of delay. 

Could these tests be expressed instead as a list of known versions or a highest known version (so that versions can get added once identified as  being an evolution)?

**Comment by rovere** [comment]
@davidlange6 I'd rather trigger an upgrade in ROOT when the *master* branch of CMSSW release uses it, not months before (if I correctly understood your proposal).
In any case, I'll think about it or other alternatives in the coming days. Please keep the PR open until then.

**Comment by davidlange6** [comment]
Sure definitely. But it could be preceded by a unit test update (a rare occurrence) that then flags the problem.

 Otherwise there is likely some compiler time flags to trigger on, but part of the point of the root builds is to know when all of CMSSW is ready to merge the root update , so disabling on the devel branches will lead to unwelcome surprises (also rarely)


On 25 Mar 2018, at 17:04, Marco Rovere <notifications@github.com<mailto:notifications@github.com>> wrote:


@davidlange6<https://github.com/davidlange6> I'd rather trigger an upgrade in ROOT when the master branch of CMSSW release uses it, not months before (if I correctly understood your proposal).
In any case, I'll think about it or other alternatives in the coming days. Please keep the PR open until then.

**Comment by davidlange6** [comment]
> On Mar 25, 2018, at 6:09 PM, David Lange <notifications@github.com> wrote:
> 
> Sure definitely. But it could be preceded by a unit test update (a rare occurrence) that then flags the problem.

what I called a "problem" is not a problem of course - rather just signaling the need to update things before that version of ROOT gets used in production...

> 
> Otherwise there is likely some compiler time flags to trigger on, but part of the point of the root builds is to know when all of CMSSW is ready to merge the root update , so disabling on the devel branches will lead to unwelcome surprises (also rarely)
> 
>

**Comment by davidlange6** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
