### PR TITLE
Remove `edmAddClassVersion` script as obsolete

### LINKED ISSUE #972: Remove `edmAddClassVersion` script as obsolete

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

I was starting to look into moving `edmAddClassVersion` to `FWCore/Reflection`, adding tests, and updating it to use the common facilities as a follow-up to https://github.com/cms-sw/cmssw/pull/45423. Then I noticed the script tries to use `gccxml`, via `scram tool info gccxml`. Scram does not provide such a tool, and therefore the script can not function. (digging from history it was removed in https://github.com/cms-sw/cmsdist/pull/1581, so maybe the script has been obsolete since we moved to ROOT6?)

Given the present situation I'd just remove the script.

Resolves https://github.com/cms-sw/framework-team/issues/972

#### PR validation:

I checked with `git grep` that nothing in CMSSW itself refers to `edmAddClassVersion`. I search in the `cms-sw` GitHub organization and found nothing referring to it (beyond the code itself in three copies of the framework), whereas search for `edmCheckClassVersion` shows many hits.

Twiki search shows a reference in https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideCreatingNewProducts#Class_versioning, which I'll update.

### CODE REVIEW

**Comment by makortel** [comment]
@smuzaffar @Dr15Jones Any objections?

**Comment by makortel** [comment]
@cmsbuild, please test

(a bit pointless, but anyway)

**Comment by Dr15Jones** [comment]
What does `edmAddClassVersion` do that is markedly different from `edmCheckClassVersion`?

**Comment by makortel** [comment]
On a quick look the main difference seems to be that `edmAddClassVersion` operates on classes defined in `classes_def.xml` that are not templates and do not have `ClassVersion` attribute in the `<class>` element. It generates a new `classes_def.xml` file with the class versions added to the `<class>` elements (starting with class version 10).

I think we should add similar check (non-template-instantiations to have a class version) to our tests. I was first thinking to make this "new non-template class added, should start version number from 3" as part of the policy checks done by the `checkDictionaryUpdate.py` script (that operates on the JSON output of `edmDumpClassVersion`), but I'm now thinking if the check could be added to `edmCheckClassVersion` directly (in which case already `scram b` on a developer area would catch it).

**Comment by Dr15Jones** [comment]
So maybe the `edmAddClassVersion` was there to fixup old code. So I'm OK with removing it.

**Comment by smuzaffar** [comment]
> @smuzaffar @Dr15Jones Any objections?

@makortel , no objections on dropping `edmAddClassVersion`.

**Comment by makortel** [comment]
> So maybe the `edmAddClassVersion` was there to fixup old code.

This is my impression as well

**Comment by makortel** [comment]
Comparison differences are related to https://github.com/cms-sw/cmssw/issues/45505

**Comment by makortel** [comment]
+core

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
