### PR TITLE
[DD4hep] Header changed from BasicGrammar to Grammar

### PR DESCRIPTION
**Pull request by mrodozov**
change in header name, needed for external update

### CODE REVIEW

**Comment by mrodozov** [comment]
test parameters:
- pull_request = https://github.com/cms-sw/cmsdist/pull/5604

**Comment by mrodozov** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Comment by mrodozov** [comment]
@fwyzard get this pr in https://github.com/cms-patatrack/cmssw, the IB is failing because it has the cmsdist change but not this one. 
also for the others , sorry for the spam but I have to use this PR to fix the builds from last night.

**Comment by fwyzard** [comment]
> @fwyzard get this pr in https://github.com/cms-patatrack/cmssw, the IB is failing because it has the cmsdist change but not this one.

Thanks for the suggestion, will do.

**Pull request merged**
