### PR TITLE
Add DQM module to make uGT data/emulator comparisons (backport)

### PR DESCRIPTION
**Pull request by apana**
Backport of #22907 and #22961 

This PR add a new DQM module to make uGT data/emulator comparisons and also add option to use prescale column from unpacked GlobalAlgBlk in emulator (#22907). Also adds a check that the GlobalAlgBlk is not empty when trying to get the prescale column number from the unpacked data (#22961).

### CODE REVIEW

**Comment by rekovic** [comment]
please test

**Comment by thomreis** [comment]
+1

**Comment by thomreis** [comment]
backport of #22907 

with an additional fix: #22961

**Comment by dmitrijus** [comment]
+1

**Comment by fabiocos** [comment]
@apana @thomreis is this PR effectively changing the behaviour of the emulator? There is no just DQM changes here...

**Comment by fabiocos** [comment]
+1

for CMSSW_10_1_5

**Pull request merged**
