### PR TITLE
Phase2-hgx318A Use the correct ERA for 2026D94 scenario

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Use the correct ERA for 2026D94 scenario

#### PR validation:

Use the runTheMatrix test workflow 41834 to check if Digi's and RecHit's for HFNose are there

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by srimanob** [comment]
test parameters:
- workflow = 41834.0

**Comment by srimanob** [comment]
@cmsbuild please test

**Comment by srimanob** [comment]
I've confused a bit on @cmsbuild report, 41834.0 is reported as comparison was not done due to missing matrix map. However, the failure histogram comes from this workflow. Do I remember correctly that if there is no workflow for comparison, the reference is built now.

**Comment by srimanob** [comment]
+Upgrade

D94 workflow runs.

**Comment by makortel** [comment]
> 41834.0 is reported as comparison was not done due to missing matrix map

IIUC the message

> comparisons for the following workflows were not done due to missing matrix map:
> 
> * /data/cmsbld/jenkins/workspace/compare-root-files-short-matrix/data/PR-6f0a9d/41834.0_TTbar_14TeV+2026D94+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14+DigiTrigger+RecoGlobal+HARVESTGlobal

means that the 41834.0 is not used for the RECO comparisons (validateJR). It is used for everything else (like RelMon from DQM histograms).

> Do I remember correctly that if there is no workflow for comparison, the reference is built now.

Correct.

**Comment by kskovpen** [comment]
+pdmv

**Comment by perrotta** [comment]
+1

**Pull request merged**
