### PR TITLE
Convert PFEGAlgo to use GlobalCache + GBRForest

### PR DESCRIPTION
**Pull request by lgray**
Meanwhile at the Legion of Doom Headquarters...

Same thing as for GsfElectronAlgo (#10327), except this time for PFEGAlgo.
Expect modest memory improvements, no changes to physics output other than possible jitter.

Note, once all of these are integrated we should see a rather healthy decrease in the amount of time it takes for multicore jobs to start. May be something to look at later.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by Dr15Jones** [comment]
Please test

**Comment by Dr15Jones** [comment]
I now have the old Justice League of America theme song running through my head

**Comment by lgray** [comment]
@Dr15Jones I do what I can to bring enjoyment to your day. :-)

**Comment by cvuosalo** [comment]
Memory usage measurement in progress...

**Comment by cvuosalo** [comment]
+1

For #10410 ea54aac76901c7a1bf2cfb889e1e1700b094c522

Converting PFEGAlgo to use GlobalCache + GBRForest to reduce memory use. There should be no significant change in monitored quantities.

The code changes are satisfactory, and Jenkins [tests](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-10410/6762/summary.html) against baseline CMSSW_7_6_X_2015-07-27-2300 show no significant differences, as expected. 
RECO for workflow 25202.0_TTbar_13 with 70 events and no DQM or Validation against baseline  CMSSW_7_6_0_pre2 shows about a 45 MB reduction in RSS:


Baseline
Max VSIZ 1859.43 on evt 57 ; max RSS 1616.96 on evt 57
Time av 15.111 s/evt   max 37.8596 s on evt 57
M1 Time av 14.7895 s/evt   max 37.8596 s on evt 57

PR 10410
Max VSIZ 1849.94 on evt 57 ; max RSS 1571.54 on evt 57
Time av 15.0332 s/evt   max 37.2437 s on evt 57
M1 Time av 14.7164 s/evt   max 37.2437 s on evt 57

**Comment by davidlange6** [comment]
+1

**Pull request merged**
