### PR TITLE
BuildFile cleanup: removed unnecessary dependencies

### PR DESCRIPTION
**Pull request by smuzaffar**
#### PR description:

Remove unnecessary dependencies from BuildFiles. This also help CXX Module IBs dependency issue.
FYI @davidlange6 , @vgvassilev 

#### PR validation:

Local build was successful

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/29608	b46953d 
- technical
- jenkins tests pass

**Comment by civanch** [comment]
+1

**Comment by smuzaffar** [comment]
@silviodonato , can we get this merged. It is mostly dependency cleanup. This should allow us to build CXXMODULE IBs

**Comment by silviodonato** [comment]
merge

**Pull request merged**
