### PR TITLE
[backport] HCAL Fb DQM monitoring at layer1

### PR DESCRIPTION
**Pull request by hftsoi**
#### PR description:

This PR includes additional calolayer1 DQM monitoring elements for HCAL LLP trigger feature bits. Added elements are the 6 fine grain bits occupancy readout at uHTR/layer1 and their comparison, and the single LLP feature bit output expected vs emulated.

#### PR validation:

Validated by running offline DQM on past commissioning runs, expected plots are produced. It has also been included in the online DQM production release based on 12_6_3 (https://github.com/cms-sw/cmssw/pull/40737 to 12_6_X) and tested online during MWGR on 9 Feb. Test went fine and PR has been made and merged to master (13_1_X) to make it permanent.

This is a backport of https://github.com/cms-sw/cmssw/pull/40751 to 13_0_X in order to be used during this year's data taking.

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
backport of https://github.com/cms-sw/cmssw/pull/40751

**Comment by perrotta** [comment]
+1
- Identical to both the master version (#40751) and to the backport in the MWGR release 12_6_X (#40737)
- Merging also in this intermediate cycle, intended for the 2023 pp data taking, in order to keep all cycles in synchro
- I assume @cms-sw/dqm-l2 has no objections, but please complain here if it is not the case

**Comment by perrotta** [comment]
merge

**Comment by emanueleusai** [comment]
+1

**Pull request merged**
