### PR TITLE
NanoAOD for 2016 94X re-miniAOD (master branch)

### PR DESCRIPTION
**Pull request by gpetruc**
Defines a new era `run2_nanoAOD_94X2016` and configures the nanoAOD appropriately:
 * same object IDs as for 2017 94X miniAOD v2 for jets, b-tag, taus
 * E/&gamma; scale and smearing for 2016 legacy re-reco, and storing of both the 2016 and 2017 IDs

### CODE REVIEW

**Comment by gpetruc** [comment]
please test

**Comment by fabiocos** [comment]
please test workflow 136.7722,136.8521,,1325.6,1325.8,1325.9,1329.1

**Comment by gpetruc** [comment]
I've just received an unrelated nanoAOD on-line bugfix (https://github.com/cms-nanoAOD/cmssw/pull/188) that I'm testing, and I will add it to this PR soon.

**Comment by gpetruc** [comment]
please test workflow 136.7722,136.8521,1325.6,1325.8,1325.9,1329.1

**Comment by gpetruc** [comment]
+1
Already tested in the nanoAOD integration workflows, but I was waiting for jenkins to conclude before putting the signature.
I'll make a 10_2_X backport PR too, in order to keep all the physics production releases aligned, but for the NanoAOD production on the 94X 2016 re-miniAOD I believe the plan is in any case to use 94X + #24215

**Comment by fabiocos** [comment]
+operations

the addition of the new Era is coherent with the purpose of the release

**Comment by fabiocos** [comment]
+1

**Pull request merged**
