### PR TITLE
Move string operations to get module labels to bookHistograms method

### PR DESCRIPTION
**Pull request by puigh**
Removed moduleLabels call from HLTConfigProvider in fillHltMatrix method, which is called for every event. List of modules per path set in bookHistograms method done at the beginRun as HLT configuration is guaranteed not to change during a run.

### CODE REVIEW

**Comment by deguio** [comment]
ciao @puigh 
the initialization of the HLTConfigProvider should be done inside the dqmBeginRun method. everything which is runBased and differs from the actual histo booking should be moved there as explained in:
https://twiki.cern.ch/twiki/bin/viewauth/CMS/ThreadedDQM

could you please take care of fixing this?
ciao and thanks,
F.

**Comment by puigh** [comment]
Hi @deguio,
To be clear, do you mean only the initialization of the HLTConfigProvider (and surrounding code), or do you also mean pushing the dataset names into a vector (i.e. really anything that is not strictly the histogram booking)?
~ Darren

**Comment by puigh** [comment]
Hi @deguio 
The latest commit [1] includes moving all run based operations to dqmBeginRun. Please let me know if that addresses your concern.
~ Darren
[1]
https://github.com/puigh/cmssw/commit/51112085d106448df843b847b0f7ce7e16ee2898

**Comment by deguio** [comment]
+1
@puigh yes it does.
thanks,
F.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
