### PR TITLE
Add a workaround for AlCa paths to the Patatrack customisation

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

The AlCa LumiPixelsCounts paths use the pixel cluster modules directly, without any Sequence or Task.
After applying the Patatrack customisation, this leaves those modules both "scheduled" (on the AlCa paths) and "unscheduled" (on every other path), breaking the latter.

To work around this issue, the Patatrack customisation now redefines the AlCa LumiPixelsCounts using the `HLTDoLocalPixelSequence` and the `HLTDoLocalPixelTask`, making the pixel modules unscheduled.

#### PR validation:

Applying the Patatrack customisation to the latest HLT menu and running over 2018 data now works.

### CODE REVIEW

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
type bug-fix

**Comment by missirol** [comment]
Okay, thanks. Then, I guess I'll need to follow up with the group(s) responsible for the paths, and make this change via JIRA.

**Comment by missirol** [comment]
+hlt

* workaround for the Patatrack customisation function, to be removed once the HLT configs are centrally moved to Tasks (and modules running scheduled inside paths are avoided)
* noted that the order of filters in `AlCa_LumiPixelsCounts_Random_v` and `AlCa_LumiPixelsCounts_ZeroBias_v` should be corrected

**Pull request merged**
