### PR TITLE
DropBox Metadata: fix SiStripApvGain and add SiStripApvGainRcdAAG_multirun

### PR DESCRIPTION
**Pull request by franzoni**
+ the tags SiStripApvGain now writes in the correct tags (was: multirun). Thanks @mmusich 
+ SiStripApvGainRcdAAG multirun: key added (we already had  SiStripApvGainRcd_multirun)

These changes don't affect any of the standard sequences.
More info about DropBox Metadata in : https://twiki.cern.ch/twiki/bin/viewauth/CMS/AlCaDBPCL#Drop_box_metadata_management

### CODE REVIEW

**Comment by franzoni** [comment]
please test

**Comment by mmusich** [comment]
Thanks @franzoni!
dumping the payload announced at [https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3016.html](https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3016.html) I see the expected target tags for both the single-run harvested and multi-run harvested workflows:

```json
--- record: SiStripApvGainRcd
           key: FileClass value: ALCA
           key: Source value: AlcaHarvesting
           key: prepMetaData value: {&quot;destinationTags&quot;: {&quot;SiStripApvGain_PCL_v0_hlt&quot;: {}, &quot;SiStripApvGain_PCL_v0_prompt&quot;: {}}, &quot;since&quot;: null, &quot;destinationDatabase&quot;: &quot;oracle://cms_orcoff_prep/CMS_CONDITIONS&quot;, &quot;inputTag&quot;: &quot;SiStripApvGain_pcl&quot;, &quot;userText&quot;: &quot;PCL MultiRun Upload for SiStrip Gains calib. (prep)&quot;}
           key: prepMetaDataMultiRun value: {&quot;destinationTags&quot;: {&quot;SiStripApvGain_PCL_multirun_v0_hlt&quot;: {}, &quot;SiStripApvGain_PCL_multirun_v0_prompt&quot;: {}}, &quot;since&quot;: null, &quot;destinationDatabase&quot;: &quot;oracle://cms_orcoff_prep/CMS_CONDITIONS&quot;, &quot;inputTag&quot;: &quot;SiStripApvGain_pcl&quot;, &quot;userText&quot;: &quot;PCL MultiRun Upload for SiStrip Gains calib. (prep)&quot;}
           key: prodMetaData value: {&quot;destinationTags&quot;: {&quot;SiStripApvGain_PCL_v0_hlt&quot;: {}, &quot;SiStripApvGain_PCL_v0_prompt&quot;: {}}, &quot;since&quot;: null, &quot;destinationDatabase&quot;: &quot;oracle://cms_orcoff_prep/CMS_CONDITIONS&quot;, &quot;inputTag&quot;: &quot;SiStripApvGain_pcl&quot;, &quot;userText&quot;: &quot;PCL MultiRun Upload for SiStrip Gains calib. (prod)&quot;}
           key: prodMetaDataMultiRun value: {&quot;destinationTags&quot;: {&quot;SiStripApvGain_PCL_multirun_v0_hlt&quot;: {}, &quot;SiStripApvGain_PCL_multirun_v0_prompt&quot;: {}}, &quot;since&quot;: null, &quot;destinationDatabase&quot;: &quot;oracle://cms_orcoff_prep/CMS_CONDITIONS&quot;, &quot;inputTag&quot;: &quot;SiStripApvGain_pcl&quot;, &quot;userText&quot;: &quot;PCL MultiRun Upload for SiStrip Gains calib. (prod)&quot;}

--- record: SiStripApvGainRcdAAG
           key: FileClass value: ALCA
           key: Source value: AlcaHarvesting
           key: prepMetaData value: {&quot;destinationTags&quot;: {&quot;SiStripApvGainAfterAbortGap_PCL_v0_prompt&quot;: {}, &quot;SiStripApvGainAfterAbortGap_PCL_v0_hlt&quot;: {}}, &quot;since&quot;: null, &quot;destinationDatabase&quot;: &quot;oracle://cms_orcoff_prep/CMS_CONDITIONS&quot;, &quot;inputTag&quot;: &quot;SiStripApvGainAAG_pcl&quot;, &quot;userText&quot;: &quot;T0 PCL Upload for SiStrip Gains AfterAbortGap calib. (prep)&quot;}
           key: prepMetaDataMultiRun value: {&quot;destinationTags&quot;: {&quot;SiStripApvGainAfterAbortGap_PCL_multirun_v0_prompt&quot;: {}}, &quot;since&quot;: null, &quot;destinationDatabase&quot;: &quot;oracle://cms_orcoff_prep/CMS_CONDITIONS&quot;, &quot;inputTag&quot;: &quot;SiStripApvGain_pcl&quot;, &quot;userText&quot;: &quot;PCL MultiRun Upload for SiStrip Gains calib. AAG (prep)&quot;}
           key: prodMetaData value: {&quot;destinationTags&quot;: {&quot;SiStripApvGainAfterAbortGap_PCL_v0_prompt&quot;: {}, &quot;SiStripApvGainAfterAbortGap_PCL_v0_hlt&quot;: {}}, &quot;since&quot;: null, &quot;destinationDatabase&quot;: &quot;oracle://cms_orcoff_prep/CMS_CONDITIONS&quot;, &quot;inputTag&quot;: &quot;SiStripApvGainAAG_pcl&quot;, &quot;userText&quot;: &quot;T0 PCL Upload for SiStrip Gains AfterAbortGap calib. (prod)&quot;}
           key: prodMetaDataMultiRun value: {&quot;destinationTags&quot;: {&quot;SiStripApvGainAfterAbortGap_PCL_multirun_v0_prompt&quot;: {}}, &quot;since&quot;: null, &quot;destinationDatabase&quot;: &quot;oracle://cms_orcoff_prep/CMS_CONDITIONS&quot;, &quot;inputTag&quot;: &quot;SiStripApvGain_pcl&quot;, &quot;userText&quot;: &quot;PCL MultiRun Upload for SiStrip Gains calib. AAG (prod)&quot;}
```

**Comment by arunhep** [comment]
+1

**Comment by franzoni** [comment]
+1

**Comment by ggovi** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
