### PR TITLE
GBRForest in TMVAEvaluator + SoftLepton taggers using GBRForest: 75X

### PR DESCRIPTION
**Pull request by ferencek**
Backport of #10543

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cmsbuild please test
[looks like old test results are gone]

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/10756	cd0dc64
- backport is applied correctly (the same changes are applied as in 76X version merged about a week ago https://github.com/cms-sw/cmssw/pull/10543	 0d350a8
    - expecting here that the same memory gains happen, without rerunning test jobs
- jenkins tests pass and comparisons with the baseline show no differences

**Comment by slava77** [comment]
@monttj please check this PR, your signature is needed here.
Thank you.

**Comment by monttj** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
