### PR TITLE
New Scenario 2021 with Updated Cavern, MB4Shields for Neutrons (top S…

### PR DESCRIPTION
**Pull request by slomeo**
@ptcox  FYI …4 S13) and all overlpas for Muon System fixed

#### PR description:

New Scenario 2021 with Updated Cavern, MB4Shields for Neutrons (top S4 S13) and all overlpas for Muon System fixed 

#### PR validation:

I perfomed a MC test with few events (20 events Z -> Mu Mu) and it was fine (i.e no errors, no warnings, no crash) in CMSSW_10_5_0 

#### if this PR is a backport please specify the original PR: It is needed for data comparison. I think CMSSW_10_2_2

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by kpedro88** [comment]
+upgrade

**Comment by cvuosalo** [comment]
+1

**Comment by fabiocos** [comment]
@slomeo I was naively expecting the new geometry to be an extension of that https://github.com/cms-sw/cmssw/blob/master/Geometry/CMSCommonData/python/cmsExtendedGeometry2021XML_cfi.py
introduced recently by @boudoul while it does not seem to be the case in the muon part at least (and also for cms.xml for instance). Could you please comment?

**Comment by slomeo** [comment]
> @slomeo I was naively expecting the new geometry to be an extension of that https://github.com/cms-sw/cmssw/blob/master/Geometry/CMSCommonData/python/cmsExtendedGeometry2021XML_cfi.py
> introduced recently by @boudoul while it does not seem to be the case in the muon part at least (and also for cms.xml for instance). Could you please comment?

My job was to fix the overlaps in the Muon System (see PR: 25869 by @ianna ) and in the last Simulation Meeting @ CMS week (April 2019) we talked about 2021 Scenario. I didn't kwow about the job of  @boudoul. A good idea could be to integrate all in one 2021 scenario.

**Comment by slomeo** [comment]
Hi @fabiocos, I think it's better I will make a cross-check by using 2021 Scenario made by @boudoul in order to verify that my modifications could be integrated without problems

**Comment by fabiocos** [comment]
hold

pending a clarification by @slomeo

**Comment by slomeo** [comment]
@ianna   @fabiocos: I made the test using cmsExtendedGeometry2021XML_cfi.py edited by @boudoul and adding the lines related to all xml files I modified to solve all overlaps inside the Muon System. I also add the directory (and file) Geometry/MuonSimData/data/muonProdCuts/2021/v1/muonProdCuts.xml taken by @boudoul. I created cmsExtendedGeometry2021TestXML_cfi.py that for me it's the "candidate" for Scenario 2021. In attach the picture by cmsShow that shows only Overlaps (188) for TRACKER, CALO and FORWARDSHIELD
overlaps

**Comment by slomeo** [comment]
After a skype meeting with @fabiocos I close this PR and asap I'll submit a new PR chianging only 2021 Scenario

**Pull request closed without merging**
