### PR TITLE
Run3-hcx219 Transform one more DDD algorithm to DD4Hep type

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

The algorithm to define the crystal matrix of Hcal Test Beam to the style of DD4Hep

#### PR validation:

It has been tested using a test script in Geometry/HcalAlgo/test. In the process of testing it, it was discovered that DD4Hep has some inadequacy which needs to be addressed before moving to the new code style

#### if this PR is a backport please specify the original PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
Should this PR be put on hold until the DD4hep issue is resolved?

**Comment by bsunanda** [comment]
@cvuosalo @ianna There is no need to hold this. I tested the PR by changing the xml file which I have not put in this PR. If this PR goes it helps me to handle the altos for HB and HE

**Comment by cvuosalo** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Pull request merged**
