### PR TITLE
Run3-Sim101C Avoid compilation warnings in SimMuon/GEMDigitizer and SimMuon/RPCDigitizer

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Avoid compilation warnings in SimMuon/GEMDigitizer and SimMuon/RPCDigitizer

#### PR validation:

Use the runTheMatrix test workflows 

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

pure technical

**Comment by srimanob** [comment]
+Upgrade

Technical PR to avoid compilation warnings. No change is expected from this PR. PR test runs fine.

**Comment by perrotta** [comment]
+1

**Pull request merged**
