### PR TITLE
backport of #13448: small performance improvement in Tracking, and #14344: avoid redundant computations in StripCPE

### PR DESCRIPTION
**Pull request by fwyzard**
backport to 8.0.x:
- #13448: Small performance improvement in Tracking
- #14344: avoid redundant computations in StripCPE

### CODE REVIEW

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
tracked at #15151

**Comment by fwyzard** [comment]
I have included #13448 because #14344 seems strongly coupled with it.

**Comment by slava77** [comment]
@fwyzard please use more readable title for this PR.

**Comment by fwyzard** [comment]
please test

**Comment by slava77** [comment]
@fwyzard at least  	73923eb is already in 80X since yesterday 26-2300 IB, but it shows up as a diff in this PR on github. This can be cleaned up.

**Comment by fwyzard** [comment]
it shouldn't make any difference, just not do anything when merged

**Comment by civanch** [comment]
+1

**Comment by cvuosalo** [comment]
@fwyzard: Four file versions in this PR are already in 80X (as of CMSSW_8_0_X_2016-07-29-2300). Could you please clean up the unnecessary commits so this PR reflects only the changes not yet in 80X?
Thanks.

**Comment by fwyzard** [comment]
rebased on top of CMSSW_8_0_16

**Comment by fwyzard** [comment]
please test

**Comment by cvuosalo** [comment]
Extended tests of workflows 134.705_RunMET2015B and 25202.0_TTbar_13 with 200 and 150 events, respectively, against baseline CMSSW_8_0_X_2016-07-24-2300 show numerous, tiny, insignificant differences, more jitter and fluctuation than real differences.

**Comment by cvuosalo** [comment]
Tests were performed to check the new compiler option "-Ofast" that this PR adds to BuildFile.xml in two places under TrackingTools/MaterialEffects. For the HLT step, the test found that eliminating  the "-Ofast" option reduced CPU time, the opposite of what one would naively expect. The test involved step2 of workflow 25202, as described above. The results for affected modules are shown below, with the value with no Ofast on top of each pair of measurements:
```
  delta/mean delta/orJob     original                   new       module name
  ---------- ------------     --------                  ----       ------------
   -0.162478      -0.02%        46.20 ms/ev ->        39.26 ms/ev hltIter2ElectronsCkfTrackCandidates
   -0.080138      -0.01%        46.20 ms/ev ->        42.64 ms/ev hltIter2ElectronsCkfTrackCandidates

   -0.144075      -0.01%        19.75 ms/ev ->        17.09 ms/ev hltIter2PFlowCkfTrackCandidates
   -0.082170      -0.00%        19.75 ms/ev ->        18.19 ms/ev hltIter2PFlowCkfTrackCandidates

   -0.141738      -0.01%        23.78 ms/ev ->        20.63 ms/ev hltIter1PFlowCkfTrackCandidates
   -0.074843      -0.00%        23.78 ms/ev ->        22.07 ms/ev hltIter1PFlowCkfTrackCandidates

   -0.135460      -0.20%       566.75 ms/ev ->       494.85 ms/ev hltPAIter3CkfTrackCandidates
   -0.089068      -0.14%       566.75 ms/ev ->       518.42 ms/ev hltPAIter3CkfTrackCandidates

   -0.127179      -0.01%        21.98 ms/ev ->        19.35 ms/ev hltIter0PFlowCkfTrackCandidates
   -0.050290      -0.00%        21.98 ms/ev ->        20.90 ms/ev hltIter0PFlowCkfTrackCandidates

   -0.125311      -0.00%        10.87 ms/ev ->         9.58 ms/ev hltIter2PFlowCkfTrackCandidatesForPhotons
   -0.071924      -0.00%        10.87 ms/ev ->        10.11 ms/ev hltIter2PFlowCkfTrackCandidatesForPhotons

   -0.124571      -0.00%         9.91 ms/ev ->         8.75 ms/ev hltIter2PFlowCkfTrackCandidatesForTau
   -0.081960      -0.00%         9.91 ms/ev ->         9.13 ms/ev hltIter2PFlowCkfTrackCandidatesForTau

   -0.113409      -0.08%       273.44 ms/ev ->       244.09 ms/ev hltPAIter2CkfTrackCandidates
   -0.086792      -0.06%       273.44 ms/ev ->       250.69 ms/ev hltPAIter2CkfTrackCandidates
	 
   -0.109973      -0.01%        23.70 ms/ev ->        21.23 ms/ev hltEgammaCkfTrackCandidatesForGSFUnseeded
   -0.050158      -0.00%        23.70 ms/ev ->        22.54 ms/ev hltEgammaCkfTrackCandidatesForGSFUnseeded

   -0.107685      -0.00%         5.84 ms/ev ->         5.25 ms/ev hltIter1PFlowCkfTrackCandidatesForBTag
   -0.083750      -0.00%         5.84 ms/ev ->         5.37 ms/ev hltIter1PFlowCkfTrackCandidatesForBTag

   -0.107680      -0.10%       359.10 ms/ev ->       322.40 ms/ev hltPAIter1CkfTrackCandidates
   -0.076071      -0.07%       359.10 ms/ev ->       332.78 ms/ev hltPAIter1CkfTrackCandidates

   -0.107473      -0.00%        12.37 ms/ev ->        11.11 ms/ev hltIter1PFlowCkfTrackCandidatesForTau
   -0.067354      -0.00%        12.37 ms/ev ->        11.56 ms/ev hltIter1PFlowCkfTrackCandidatesForTau

   -0.077056      -0.00%         8.08 ms/ev ->         7.48 ms/ev hltIter0ElectronsCkfTrackCandidates
   -0.067000      -0.00%         8.08 ms/ev ->         7.56 ms/ev hltIter0ElectronsCkfTrackCandidates
```

**Comment by cvuosalo** [comment]
Further test results checking the Ofast compiler option. These measurements are from workflow 134.705 as described above. The Ofast option appears to provide a small improvement of about 0.4-1.0%. As before, the measurement with no Ofast is on top.
```
  delta/mean delta/orJob     original                   new       module name
  ---------- ------------     --------                  ----       ------------
-0.039012      -0.05%        38.78 ms/ev ->        37.30 ms/ev jetCoreRegionalStepTrackCandidates
-0.049499      -0.06%        38.78 ms/ev ->        36.91 ms/ev jetCoreRegionalStepTrackCandidates

-0.016238      -0.03%        58.40 ms/ev ->        57.46 ms/ev lowPtTripletStepTrackCandidates
-0.021397      -0.04%        58.40 ms/ev ->        57.16 ms/ev lowPtTripletStepTrackCandidates

-0.007176      -0.02%        76.99 ms/ev ->        76.44 ms/ev detachedTripletStepTrackCandidates
-0.017112      -0.04%        76.99 ms/ev ->        75.69 ms/ev detachedTripletStepTrackCandidates

-0.004690      -0.01%        66.25 ms/ev ->        65.94 ms/ev pixelPairStepTrackCandidates
-0.007419      -0.02%        66.25 ms/ev ->        65.76 ms/ev pixelPairStepTrackCandidates
```

**Comment by Dr15Jones** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by cvuosalo** [comment]
Should the "-Ofast" compiler option be eliminated from this PR as was done for #15280? It produces marginal timing improvements, and it creates some unnecessary differences, though they are tiny. From the tests described above, the number of difference plots for 25202.0 are as follows.
```
                  Validation      DQM
No Ofast             506          21121
With Ofast           567          21822
```

**Comment by slava77** [comment]
@cvuosalo 
considering some visible benefits from Ofast in terms of time, and essentially the same count of histogram with differences, I think that we can keep this PR as is.

**Comment by cvuosalo** [comment]
@cmsbuild please test
Previous Jenkins tests were incomplete

**Comment by cvuosalo** [comment]
+1

For #15295 ba6640b42d0d52b272b52ca1eb6d4247562d2875

Performance improvements in tracking and strip CPE.

The code changes match those put into 81X by #13448 and #14344. Jenkins tests show no problems, but they are incomplete. Extended tests described above show numerous, tiny, insignificant differences, more jitter and fluctuation than real differences. CPU timing tests indicate a speed up of around 5% for affected modules.

**Comment by cvuosalo** [comment]
New Jenkins tests show the numerous, tiny, insignificant differences that are expected for this PR; otherwise, they show no problems.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
