### PR TITLE
MTD geometry: separate BTL and ETL sensitive volume prod cuts

### PR DESCRIPTION
**Pull request by fabiocos**
#### PR description:

Since BTL and ETL are using quite different sensor technologies and materials (LYSO crystals vs 50 micron thick LGAD silicon sensors) it makes sense to separate production cuts for the sensitive volumes. The values for ETL are lowered by a factor of 10, following what si done for tracker pixel in Phase II, but this may be further tuned afterwards.

At the same time obsolete fasttime files are removed from the HGCal areas (@bsunanda FYI, please comment in case).

#### PR validation:

Test wf 23234 and 24434 run, the LogVerbatim output of ```DDG4ProductionCuts``` shows the desired splitting:

```
  num  1 regionName: FastTimerRegion, the store of size 16
DDG4ProductionCuts : regionName FastTimerRegion, the store of size 16
DDG4ProductionCuts : region FastTimerRegion
DDG4ProductionCuts : new G4Region EndcapTimingLayer
DDG4ProductionCuts : Setting cuts for FastTimerRegion
    Electrons: 0.1
    Positrons: 0.1
    Gamma    : 0.1
    Proton   : 0.1
  added EndcapTimingLayer to region FastTimerRegion
  num  1 regionName: FastTimerRegionSensETL, the store of size 17
DDG4ProductionCuts : regionName FastTimerRegionSensETL, the store of size 17
DDG4ProductionCuts : region FastTimerRegionSensETL
DDG4ProductionCuts : new G4Region EModule_Timingactive
DDG4ProductionCuts : Setting cuts for FastTimerRegionSensETL
    Electrons: 0.01
    Positrons: 0.01
    Gamma    : 0.01
    Proton   : 0.01
  added EModule_Timingactive to region FastTimerRegionSensETL
```

```
  num  1 regionName: FastTimerRegion, the store of size 21
DDG4ProductionCuts : regionName FastTimerRegion, the store of size 21
DDG4ProductionCuts : region FastTimerRegion
DDG4ProductionCuts : new G4Region BarrelTimingLayer
DDG4ProductionCuts : Setting cuts for FastTimerRegion
    Electrons: 0.1
    Positrons: 0.1
    Gamma    : 0.1
    Proton   : 0.1
  added BarrelTimingLayer to region FastTimerRegion
  num  1 regionName: FastTimerRegionSensBTL, the store of size 21
DDG4ProductionCuts : regionName FastTimerRegionSensBTL, the store of size 21
DDG4ProductionCuts : region FastTimerRegionSensBTL
DDG4ProductionCuts : new G4Region BModule33Layer1Timingactive
DDG4ProductionCuts : Setting cuts for FastTimerRegionSensBTL
    Electrons: 0.1
    Positrons: 0.1
    Gamma    : 0.1
    Proton   : 0.1
  added BModule33Layer1Timingactive to region FastTimerRegionSensBTL
  num  1 regionName: FastTimerRegionSensBTL, the store of size 22
  added BModule1Layer1Timingactive to region FastTimerRegionSensBTL
  num  1 regionName: FastTimerRegionSensBTL, the store of size 22
  added BModule17Layer1Timingactive to region FastTimerRegionSensBTL
  num  1 regionName: BeamPipeVacuum, the store of size 22
```

### CODE REVIEW

**Comment by fabiocos** [comment]
@ianna @cvuosalo @bsunanda I have realised that the file referenced in the mtdProdCuts.xml and mtdsens.xml do not correspond to the file name itself (being regions.xml and fasttimesens.xml). Apparently this is irrelevant anyway for the model built in memory (otherwise I had realized it earlier).
Are these names totally irrelevant in our existing use? Or is ti anyway better to fix them to the real file name?

**Comment by fabiocos** [comment]
please test

**Comment by cvuosalo** [comment]
@fabiocos Do you mean a file reference like this?
```
<SpecParSection label="regions.xml" eval="true">
```

**Comment by fabiocos** [comment]
@cvuosalo exactly

**Comment by cvuosalo** [comment]
@fabiocos The label looks to me like an arbitrary string that does not have to match an actual file name, unless we want that to be the convention.
@ianna Is it true the `label` below can be any string?
```
<SpecParSection label="regions.xml" eval="true">
```

**Comment by cvuosalo** [comment]
+1

**Comment by bsunanda** [comment]
My understanding is that the label is useful to access constants or vectors - so let it be unique in a given scenario. So all MTD labels should carry MTD as the first 3 characters.
________________________________

**Comment by ianna** [comment]
> @fabiocos The label looks to me like an arbitrary string that does not have to match an actual file name, unless we want that to be the convention.
> @ianna Is it true the `label` below can be any string?
> 
> ```
> <SpecParSection label="regions.xml" eval="true">
> ```

It better be something meaningful since it is used as a namespace.

**Comment by kpedro88** [comment]
+upgrade
only affects development geometry I12

**Comment by fabiocos** [comment]
hold

@ianna @bsunanda thanks, for the old scenarios I will not touch anything, for D50 and D53 (i.e. I11 and I12) I will update the names, although I do not expect so far practically any effect

**Comment by bsunanda** [comment]
It has no effect on DDD. It is only used in DD4HEP. Do for D50, D53 it would not matter.
________________________________

**Comment by fabiocos** [comment]
@bsunanda well, I am using D50 to test the DD4hep migration, and D53 should be supported on both, so better to fix for them, exactly because of DD4hep as you say. D49 is already in production and I am not touching it, D50 is equivalent to D49 as detector description, but I use it to experiment and update the code.

**Comment by fabiocos** [comment]
unhold

ok, better I do it in my next PR already under preparation, @silviodonato please merge this at your earliest convenience

**Comment by silviodonato** [comment]
+1

**Pull request merged**
