### PR TITLE
HLT DQM for 9.3.x

### PR DESCRIPTION
**Pull request by fwyzard**
Reduced version of  #19684.

Merge the following HLT DQM pull requests (in this order):
  - #19178 from physicist87/hltjetmet-promptqdm-updateV2
  - #18994 from anigamova/from-CMSSW_9_2_0
  - #19293 from rappoccio/EXOB2G_HLTMON
  - #19689 from physicist87/Pure-METTrigger-93xV4

### CODE REVIEW

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by fwyzard** [comment]
@cmsbuild, please abort

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by davidlange6** [comment]
sigh - it seems I had not actually looked at #18994 before...

**Comment by dmitrijus** [comment]
+1

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by fwyzard** [comment]
@davidlange6 this looks ready to go as well

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by fwyzard** [comment]
@davidlange6, ok, *now*  this looks ready to go in

**Comment by dmitrijus** [comment]
+1

**Pull request merged**
