### PR TITLE
[12_4_X] Add gen fragment for LLP relval

### PR DESCRIPTION
**Pull request by kakwok**
This PR is for adding the gen-fragment for relval sample for the new LLP seeds as per dicussion here:

https://its.cern.ch/jira/browse/PDMVRELVALS-152

The fragment is taken from the signal sample used in the TSG sample:
https://cms-pdmv.cern.ch/mcm/public/restapi/requests/get_fragment/HCA-Run3Winter20GS-00030/0

This is a backport of https://github.com/cms-sw/cmssw/pull/38496

### CODE REVIEW

**Comment by SiewYan** [comment]
please test

**Comment by perrotta** [comment]
backport of https://github.com/cms-sw/cmssw/pull/38496

**Comment by SiewYan** [comment]
@kakwok , since this is the backport of #38496, could you propagate the corrected version cfi to this PR?

**Comment by kakwok** [comment]
@SiewYan Sorry for the oversight, I've updated the PR.

**Comment by SiewYan** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
