### PR TITLE
Use internal reference counting in CaloCellGeometry

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

This removes the need for std::shared_ptr in PFRecHit and should reduce memory usage.

#### PR validation:

Code compiles. Ran workflow 141.046 and it worked fine.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
This is an extension of #46507

**Comment by Dr15Jones** [comment]
I compared running step3 of workflow 141.046 using  #46507 versus code in the PR. The following memory improvements were seen.

| memory measurement |  #46507 | this PR | improvement |
| -------- | ------- | ------ | ------- |
| requested | 520211052284 | 520162625267 | 48427017 |
| max used | 4793079280 | 4784506936 | 8572344 |
| # allocs |2776919629 | 2775234599 | 1685030 |

**Comment by Dr15Jones** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by jfernan2** [comment]
+1

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
