### PR TITLE
75X 25ns HLT - round four

### PR DESCRIPTION
**Pull request by perrotta**
Based on CMSSW_7_5_X_2015-09-16-1100

It includes (by now...) updates to the HLT menu up to /dev/CMSSW_7_4_0/HLT/V480

It also includes a fix that prevents FastSim crashing if the new menus integrated with #11042 are run

### CODE REVIEW

**Comment by perrotta** [comment]
+1

**Comment by perrotta** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
