### PR TITLE
Replace depreciated StableParameters and use GlobalParameters

### PR DESCRIPTION
**Pull request by rekovic**
93x PR:  Replace depreciated StableParameters and use GlobalParameters wherever used
in the release.

### CODE REVIEW

**Comment by rekovic** [comment]
@Martin-Grunewald 
HLT might need to make additional adjustments in some of its configurations (for testing) ?

**Comment by rekovic** [comment]
please test

**Comment by nsmith-** [comment]
@rekovic this is very likely the same problem as https://github.com/cms-l1t-offline/cmssw/issues/583#issuecomment-316276796
@kkotov and I are looking into it

**Comment by abrinke1** [comment]
@nsmith- I'm not exactly sure what you mean by "same problem" ... I'm trying to figure out how to put in proper switches for the EMTF emulator in the l1t-offline code.  This EMTF emulator is not in central cms-sw yet, and this PR certainly does not pull it in.  So it may be a related problem, but for better or worse, the two issues will have separate solutions.

**Comment by nsmith-** [comment]
@abrinke1, the same [flawed design pattern](https://github.com/cms-sw/cmssw/search?utf8=%E2%9C%93&q=shared_ptr.*getWriteInstance&type=) for passing the conditions object from a local producer to the framework was used for both uGT and EMTF.
It has nothing to do with the emulators themselves.

**Comment by abrinke1** [comment]
Ah, I see - great!  Because we had moved on to other discussions on that thread, I had forgotten about the "shared_ptr" issue.  I've fixed that now in my code:

https://github.com/abrinke1/cmssw/commit/9f268349147feb3f1a3b0f91fbe2106386a5537c

**Comment by nsmith-** [comment]
It seems that actually the issue is still that there are two providers, `StableParameters` and `GlobalParameters` in the process.  For unknown reasons, it causes a segfault in FWCore, rather than the [previously observed](https://github.com/cms-sw/cmssw/pull/19456#issuecomment-312852810) exception about two providers.  Adding the following lines to the bottom of a cmsDriver config from one of the above failed RelVals allows it to succeed:
```python
process.__dict__.pop('StableParameters')
process._Process__esproducers.pop('StableParameters')
# these below are not troublemakers, but the record is defunct so might as well remove it
process.__dict__.pop('StableParametersRcdSource')
process._Process__essources.pop('StableParametersRcdSource')
```
The remaining [locations](https://github.com/cms-sw/cmssw/search?utf8=%E2%9C%93&q=StableParameters+&type=) of `StableParameters` are in https://github.com/cms-sw/cmssw/tree/master/HLTrigger/Configuration/python
@Martin-Grunewald @fwyzard clearly this folder is semi-auto-generated, so I assume you would rather I don't just patch the files?

**Comment by Martin-Grunewald** [comment]
Hmm, frpom the above I gather I should remove these two:
```
*** 3190,3194 ****
! process.StableParametersRcdSource = cms.ESSource( "EmptyESSource",
!     iovIsRunNotTime = cms.bool( True ),
!     recordName = cms.string( "L1TGlobalStableParametersRcd" ),
!     firstValid = cms.vuint32( 1 )
! )
--- 3190,3194 ----
! #process.StableParametersRcdSource = cms.ESSource( "EmptyESSource",
! #    iovIsRunNotTime = cms.bool( True ),
! #    recordName = cms.string( "L1TGlobalStableParametersRcd" ),
! #    firstValid = cms.vuint32( 1 )
! #)
***************
*** 3614,3642 ****
! process.StableParameters = cms.ESProducer( "StableParametersTrivialProducer",
!   NumberL1JetCounts = cms.uint32( 12 ),
!   NumberL1NoIsoEG = cms.uint32( 4 ),
!   NumberL1CenJet = cms.uint32( 4 ),
!   NumberL1Tau = cms.uint32( 8 ),
!   NumberConditionChips = cms.uint32( 1 ),
!   NumberL1EGamma = cms.uint32( 12 ),
!   TotalBxInEvent = cms.int32( 5 ),
!   NumberL1Mu = cms.uint32( 4 ),
!   PinsOnConditionChip = cms.uint32( 512 ),
!   WordLength = cms.int32( 64 ),
!   PinsOnChip = cms.uint32( 512 ),
!   OrderOfChip = cms.vint32( 1 ),
!   IfMuEtaNumberBits = cms.uint32( 6 ),
!   OrderConditionChip = cms.vint32( 1 ),
!   appendToDataLabel = cms.string( "" ),
!   NumberL1TauJet = cms.uint32( 4 ),
!   NumberL1Jet = cms.uint32( 12 ),
!   NumberPhysTriggers = cms.uint32( 512 ),
!   NumberL1Muon = cms.uint32( 12 ),
!   UnitLength = cms.int32( 8 ),
!   NumberL1IsoEG = cms.uint32( 4 ),
!   NumberTechnicalTriggers = cms.uint32( 64 ),
!   NumberL1ForJet = cms.uint32( 4 ),
!   IfCaloEtaNumberBits = cms.uint32( 4 ),
!   NumberPsbBoards = cms.int32( 7 ),
!   NumberChips = cms.uint32( 5 ),
!   NumberPhysTriggersExtended = cms.uint32( 64 )
! )
--- 3614,3642 ----
! #process.StableParameters = cms.ESProducer( "StableParametersTrivialProducer",
! #  NumberL1JetCounts = cms.uint32( 12 ),
! #  NumberL1NoIsoEG = cms.uint32( 4 ),
! #  NumberL1CenJet = cms.uint32( 4 ),
! #  NumberL1Tau = cms.uint32( 8 ),
! #  NumberConditionChips = cms.uint32( 1 ),
! #  NumberL1EGamma = cms.uint32( 12 ),
! #  TotalBxInEvent = cms.int32( 5 ),
! #  NumberL1Mu = cms.uint32( 4 ),
! #  PinsOnConditionChip = cms.uint32( 512 ),
! #  WordLength = cms.int32( 64 ),
! #  PinsOnChip = cms.uint32( 512 ),
! #  OrderOfChip = cms.vint32( 1 ),
! #  IfMuEtaNumberBits = cms.uint32( 6 ),
! #  OrderConditionChip = cms.vint32( 1 ),
! #  appendToDataLabel = cms.string( "" ),
! #  NumberL1TauJet = cms.uint32( 4 ),
! #  NumberL1Jet = cms.uint32( 12 ),
! #  NumberPhysTriggers = cms.uint32( 512 ),
! #  NumberL1Muon = cms.uint32( 12 ),
! #  UnitLength = cms.int32( 8 ),
! #  NumberL1IsoEG = cms.uint32( 4 ),
! #  NumberTechnicalTriggers = cms.uint32( 64 ),
! #  NumberL1ForJet = cms.uint32( 4 ),
! #  IfCaloEtaNumberBits = cms.uint32( 4 ),
! #  NumberPsbBoards = cms.int32( 7 ),
! #  NumberChips = cms.uint32( 5 ),
! #  NumberPhysTriggersExtended = cms.uint32( 64 )
! #)
```
but this gives then the following error:
```
%MSG
----- Begin Fatal Exception 27-Jul-2017 16:36:20 CEST-----------------------
An exception of category 'NoProxyException' occurred while
   [0] Processing  Event run: 1 lumi: 3 event: 102 stream: 3
   [1] Running path 'HLT_HcalNZS_v12'
   [2] Calling method for module L1TGlobalProducer/'hltGtStage2ObjectMap'
Exception Message:
No data of type "L1TGlobalParameters" with label "" in record "L1TGlobalParamet\
ersRcd"
 Please add an ESSource or ESProducer to your job which can deliver this data.
----- End Fatal Exception -------------------------------------------------
```
So I assume the removal requires this PR at the SAME TIME?

**Comment by nsmith-** [comment]
Ahh, I see, since this is just the uGT re-emulation at HLT, you end up never importing `SimL1Emulator`.

Ok, in that case, then unfortunately you would have to remove those lines and then add the contents of [GlobalParameters_cff.py](https://github.com/cms-sw/cmssw/blob/master/L1Trigger/L1TGlobal/python/GlobalParameters_cff.py) in place of them. (although the `GlobalParametersRcdSource` should already be there)  This change should be able to be independent of this PR for all processing that does not involve running the full L1 emulator.

As an aside, is there a strong reason why this stuff is not in a GT?

**Comment by Martin-Grunewald** [comment]
OK, please add to this PR a modification to put this into 
https://github.com/cms-sw/cmssw/blob/master/HLTrigger/Configuration/python/customizeHLTforCMSSW.py
ie, something like
```
# Remove StableParameter dependence in favour of GlobalParameters
def customiseFor19812(process):
    if hasattr(process,'StableParametersRcdSource'):
        delattr(process,'StableParametersRcdSource')
    if hasattr(process,'StableParameters'):
        delattr(process,'StableParameters')
    if not hasattr(process,'GlobalParameters'):
        from L1Trigger.L1TGlobal.GlobalParameters_cff import GlobalParameters
        process.GlobalParameters = GlobalParameters
    return process
```
and further done call this routine:
```
    process = customiseFor19812(process)
```

**Comment by davidlange6** [comment]
please test

**Comment by nsmith-** [comment]
Shoot, Len's branch started from 930_pre1 and `customizeHLTforCMSSW.py` changes all the time.
OK I will make a new PR on _pre2

**Comment by Martin-Grunewald** [comment]
please close this PR as superseeded by #19989

**Pull request closed without merging**
