### PR TITLE
Make the fast parabolic MF parametrization dynamic

### PR DESCRIPTION
**Pull request by namapane**
This is a backport of   #8992 (+ #8814) to 74X.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
Hi Nicola,

Would this solution make sense as an alternative?
https://github.com/cms-sw/cmssw/compare/cms-sw:CMSSW_7_3_X...slava77:CMSSW_7_3_5_patch2/autoPseudoParabolic?expand=1

I made it for 73X, thinking that this is just as good and uses just config update.

**Comment by davidlange6** [comment]
Hi Slava, NIcola

We need a 73x solution ~today if there is one agreed. Which do you suggest?

Cheers-
David

**Comment by slava77** [comment]
Hi David,

I'm testing the one I suggested.
I'd like to get a confirmation from Nicola that it makes sense.

		--slava


On 5/8/15 7:15 AM, David Lange wrote:
> Hi Slava, NIcola
> 
> We need a 73x solution ~today if there is one agreed. Which do you suggest?
> 
> Cheers-
> David
> 
>> On May 8, 2015, at 7:54 AM, Slava Krutelyov <notifications@github.com> wrote:
>> 
>> Hi Nicola,
>> 
>> Would this solution make sense as an alternative?
>> https://github.com/cms-sw/cmssw/compare/cms-sw:CMSSW_7_3_X...slava77:CMSSW_7_3_5_patch2/autoPseudoParabolic?expand=1
>> 
>> I made it for 73X, thinking that this is just as good and uses just config update.
>> 
>> —
>> Reply to this email directly or view it on GitHub.
>> 
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cms-sw/cmssw/pull/8994#issuecomment-100213811>.
> 

-- 
***********************************************************************
 Vyacheslav (Slava) Krutelyov
 TAMU: Physics Dept Texas A&M MS4242, College Station, TX 77843-4242
 CERN: 42-R-027
 AIM/Skype: siava16              googleTalk: slava77@gmail.com
 (630) 291-5128  Cell (US)       +41 76 275 7116 Cell (CERN)

-----------------------------------------------------------------------

**Comment by namapane** [comment]
I have already answered Slava at the link he posted above; essentially I think it is fine for 73X (did not test it myself).

**Comment by slava77** [comment]
For 74X, we need to see that the use of field from DB (#8814) actually goes through OK in pre4,
before this one can go to 74X.

If it were just a change in the delivery of ParabolicMf, it would be more trivial.

**Comment by davidlange6** [comment]
@slava77, sounds like we should proceed with your change for the moment in 73x and get the right solution (this one) in 74x and 75x.  Could you make the 73x PR?

**Comment by namapane** [comment]
Yes but consider that #8814 also addresses a problem with consistency of HLT and offline, so it's effectively desirable to have it in 74X, if that has to be patched.

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/8994	c67f004


- changes in the code are in agreement with what was signed off for 75X
- tested additionally in local test area CMSSW_7_4_1 /test area sign741a/
- as in 75X tests of the map change, the run 1 MC  jenkins tests show differences triggered by numerical differences in the volume boundaries just as discussed in #8814. Local tests reusing the same gen-sim inputs show no differences for these workflows.
- in local tests: very small (numerical precision level) changes show up for cosmic muon tracks in workflows 8.0 (beam halo) and 4.22 (Run2011A cosmics data processing). These have the same origin as above.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
