### PR TITLE
remove `SiPixelCompare*SoAAlpaka` templates and update `customizeHLTforAlpaka` to use the new modules

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

After the integration of the new HLT menu in PR https://github.com/cms-sw/cmssw/pull/45548 (which included the ticket [CMSHLT-3278](https://its.cern.ch/jira/browse/CMSHLT-3278) "[DQM] Use general DQM modules for pixel rechits, tracks and vertices added in cmssw#45302") we can finally proceed with removing the old-style comparison `SiPixelCompare*SoAAlpaka` templates which serve no longer any purpose.
Consequently the `customizeHLTforAlpaka` customization function is updated to use the new modules.
This is a "leftover" of https://github.com/cms-sw/cmssw/pull/45206, see comment at https://github.com/cms-sw/cmssw/pull/45206#discussion_r1637804270. 

#### PR validation:

None, no regressions are expected.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Not a backport, will backport to CMSSW_14_0_X.

@borzari FYI

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
+hlt

**Comment by tjavaid** [comment]
+dqm

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
