### PR TITLE
fix some DQM sequences for phase1 scenario

### PR DESCRIPTION
**Pull request by mtosi**
thanks to @makortel 
I went through the list of python config files which still handle the phase1
by dropping some DQM/Validation modules

I did not update the following ones, though
- DQMOffline/Configuration/python/DQMOffline_CRT_cff.py:phase1Pixel.toReplaceWith(crt_dqmoffline, crt_dqmoffline.copyAndExclude([ # FIXME
- Validation/RecoTrack/python/SiTrackingRecHitsValid_cff.py:phase1Pixel.toReplaceWith(trackingRecHitsValid, trackingRecHitsValid.copyAndExclude([ # FIXME

because the comment suggests that need some work on the DQM side

in addition, I was not able to merge my original updates
because of conflict w/
- DQM/Physics/python/DQMPhysics_cff.py:phase1Pixel.toReplaceWith(dqmPhysics, dqmPhysics.copyAndExclude([ # FIXME
so, it still needs to be updated

I do not think they are super urgent, but I would suggest to integrate this PR as soon as possible ...

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by makortel** [comment]
Thanks Mia! I hope the DQM team could follow up the remaining issues.

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/16589 1258b10
- reco is not affected. Updates are made in dqm/validation configs for phase-1.
- jenkins tests pass and comparisons with baseline show differences only in DQM plots in 2017 workflows. Most visible changes are in the tau plots which appear to be normalized now in a way similar to the 2016 workflows.

**Comment by civanch** [comment]
+1

**Comment by dmitrijus** [comment]
+1

**Pull request merged**
