### PR TITLE
Run3-gex169 Modify the scenarios to have the right SimHit distributions for HF

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Modify the scenarios to have the right SimHit distributions for HF

#### PR validation:

Use the runTheMatrix test workflows

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
+geometry

**Comment by srimanob** [comment]
Hi @bsunanda 
Do I understand correctly that the expected change from this PR is on Run-3 DD4hep XML only (11634.911). This is because the change of geometry is not yet propagated to GT, so no change is expected on normal workflow.

**Comment by bsunanda** [comment]
@srimanob Yes the change is not propagated to the GT. 11634.911 uses XML and not the geometry from DB. So it is affected but not on workflows which get geometry from DB

**Comment by srimanob** [comment]
+Upgrade

Change is expected.

**Comment by perrotta** [comment]
+1

**Pull request merged**
