### PR TITLE
Add header guards to IPTagPlotter_cc.h

### PR DESCRIPTION
**Pull request by Teemperor**
This file looks like a normal header but it doesn't have header
guards, so let's add some.

### CODE REVIEW

**Comment by Teemperor** [comment]
Part of the work going on regarding the C++ modules migration of CMSSW (tracked as issue https://github.com/cms-sw/cmssw/issues/15248). This PR is not meant to refactor things, but just to make these headers compile.

**Comment by davidlange6** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
Your PR is unmergeable. Please have a look and possibly rebase it.

**Comment by Teemperor** [comment]
Already fixed in master, closing this.

**Pull request closed without merging**
