### PR TITLE
MTD RECO Geometry: fix debug statements in MTDGeometryBuilder

### PR DESCRIPTION
**Pull request by fabiocos**
#### PR description:

During the development of the MTD RECO geometry for DD4hep and the new ETL, I have realized that the debug statements in ```MTDGeometryBuilder``` are not functional, not even compiling when executing ```USER_CXXFLAGS="-g -D=EDM_ML_DEBUG" scram b -v``` to enable LogDebug.
This PR proposes a simple fix, that makes them functional (the commented addition to the test configuration added can be used).

#### PR validation:

If ```Geometry/MTDGeometryBuilder/test/mtd_cfg.py``` is run enabling the LogDebug in message logger (commented part), the debug messages are produced:

```
%MSG-d BuildingSubDetTypeMap:  MTDDigiGeometryAnalyzer:prod  14-Feb-2020 13:53:55 CET Run: 1 Event: 1 MTDGeometry.cc:47
MTD GeometricTimingDet and GeomDetEnumerators enumerator values of the subdetectors
%MSG
MTD subdet 0 Geometric Det type 1 Geom Det type 18 detid 6280003f subdetid 1 number of layers 1
MTD subdet 1 Geometric Det type 7 Geom Det type 19 detid 63400000 subdetid 2 number of layers 1
MTD subdet 2 Geometric Det type 7 Geom Det type 19 detid 63000000 subdetid 2 number of layers 1
%MSG-d SubDetTypeMapContent:  MTDDigiGeometryAnalyzer:prod  14-Feb-2020 13:53:55 CET Run: 1 Event: 1 MTDGeometry.cc:60
MTD Content of theSubDetTypeMap
 detid subdet 1 Geom Det type 18
 detid subdet 2 Geom Det type 19

%MSG
%MSG-d NumberOfLayers:  MTDDigiGeometryAnalyzer:prod 14-Feb-2020 13:53:55 CET  Run: 1 Event: 1 MTDGeometry.cc:67
MTD Content of theNumberOfLayers
 detid subdet 1 number of layers 1
 detid subdet 2 number of layers 1

%MSG
%MSG-d ThicknessAndType:  MTDDigiGeometryAnalyzer:prod 14-Feb-2020 13:53:55 CET  Run: 1 Event: 1 MTDGeometry.cc:79
MTD Total Number of Detectors 5892
%MSG
%MSG-d ThicknessAndType:  MTDDigiGeometryAnalyzer:prod 14-Feb-2020 13:53:55 CET  Run: 1 Event: 1 MTDGeometry.cc:80
MTD Dump of sensors names and bounds
%MSG
%MSG-d ThicknessAndType:  MTDDigiGeometryAnalyzer:prod 14-Feb-2020 13:53:55 CET  Run: 1 Event: 1 MTDGeometry.cc:81
62810400 BModule1Layer1NegativeZTimingwafer 0.4
62810800 BModule1Layer1NegativeZTimingwafer 0.4
62810c00 BModule1Layer1NegativeZTimingwafer 0.4
62811000 BModule1Layer1NegativeZTimingwafer 0.4
62811400 BModule1Layer1NegativeZTimingwafer 0.4
62811800 BModule1Layer1NegativeZTimingwafer 0.4
62811c00 BModule1Layer1NegativeZTimingwafer 0.4
62812000 BModule1Layer1NegativeZTimingwafer 0.4
62812400 BModule1Layer1NegativeZTimingwafer 0.4
62812800 BModule1Layer1NegativeZTimingwafer 0.4
62812c00 BModule1Layer1NegativeZTimingwafer 0.4
62813000 BModule1Layer1NegativeZTimingwafer 0.4
```

### CODE REVIEW

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
@silviodonato #28875 should be merged before in order to avoid conflicts

**Comment by cvuosalo** [comment]
+1

**Comment by fabiocos** [comment]
@kpedro88 comments or objections? The PR in itself looks fairly simple.

**Comment by kpedro88** [comment]
+upgrade

**Comment by silviodonato** [comment]
+1

**Pull request merged**
