### PR TITLE
Retuning QTest for 2016 data

### PR DESCRIPTION
**Pull request by fioriNTU**
Adapt the range of mean number of rec-hits to 2016 data

### CODE REVIEW

**Comment by fioriNTU** [comment]
@dmitrijus could you start the tests? (even if there is nothing to test really)

**Comment by vanbesien** [comment]
please test
(since @dmitrijus is on vacation)

**Comment by dmitrijus** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by fioriNTU** [comment]
can someone merge it, it is a fix for Online shifters

**Comment by vanbesien** [comment]
Hey @fioriNTU, we can already plug this on the playback (to test) and later on production. Just put it in the https://twiki.cern.ch/twiki/bin/view/CMS/DQMP5TagCollector

**Comment by fioriNTU** [comment]
@vanbesien this is done, at least the Tracking Summary will be updated in Online

**Comment by davidlange6** [comment]
+1

**Pull request merged**
