### PR TITLE
[12_6_X] Fix `PostDQMOffline*` sequences in cmsDriver.py

### PR DESCRIPTION
**Pull request by elusian**
#### PR description:

When adding a DQM sequence to the command line options (e.g. `DQM:@miniAODDQM`), cmsDriver.py is supposed to add the relative `PostDQMOffline` sequence as selected in autoDQM.py. 
However, due to [this commit](https://github.com/cms-sw/cmssw/commit/fa26238b3adb5eec7c8576add915200d4169a281#diff-cdb26c43130acb8faa9c94529dd55a55671d2621695d7c5a2a47aa20a62e62dfL1979-R1979) in CMSSW_12_6_0_pre3, this does not happen anymore. 

After the commit `sequenceList` and `postSequenceList` are the same object at the same address and filling `sequenceList` inhibits the fill of `postSequenceList` (since `expandMapping` sees no "@" in the array). Since the sequences are the same, no dqmofflineOnPAT_step is produced in the output.

This PR splits the assigment into two lines, which makes `sequenceList` and `postSequenceList` distinct again.

#### PR validation:

Created a simple config file passing `DQM:@miniAODDQM` to cmsDriver.py, requested `PostDQMOffline*` sequences are back in the `process.schedule` as they were in CMSSW_12_6_0_pre2

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport of #40293 for CMSSW 12_6_X

### CODE REVIEW

**Comment by mmusich** [comment]
backport of https://github.com/cms-sw/cmssw/pull/40293

**Comment by mmusich** [comment]
type bug-fix

**Comment by mmusich** [comment]
please test

**Comment by perrotta** [comment]
+1

**Pull request merged**
