### PR TITLE
Clean up cosmic mu reco in pp

### PR DESCRIPTION
**Pull request by trocino**
This is to skip regional-tracker reco and global-muon reco (both 1- and 2-leg) in the cosmic-muon reconstruction sequence used in collisions. (Note that there is no change in cosmic runs.) 
The following modules are removed: 
Tracking: 
regionalCosmicTracksSeq = regionalCosmicTrackerSeedingLayers \* regionalCosmicTrackerSeeds \* regionalCosmicCkfTrackCandidates \* regionalCosmicTracks
Global-muon reco: 
globalCosmicMuons, globalCosmicMuons1Leg
The corresponding event content is also removed. 
This is based on the configuration prepared by @bellan. The tracking changes were discussed and agreed on with @VinInn and @rovere.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
.. I'm checking it

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/7541	f376e26
tested in CMSSW_7_4_X_2015-02-02-0200 /test area sign513, commits cherry-picked)

In general, changes are as expected.

The banchmark sample for run2 TTbar with PU35@25ns shows reduction in used resources:
- CPU reduces by 10% (compared to older tests with an independent input sample of 5%, in both cases driven by ~10 events) ==> about 7% CPU reduction. GOOD.
- AODSIM size decreases by 0.1% (negligible)

- muonsFromCosmics change slightly, the only more visible change is the matching ecal info  (the plot is 10 GeV SingleMuon "dimuon" gun); the standalone muons are not pointing as well to the calorimeter cells as the tracker tracks
all_sign513vsorig_singlemupt10wf20p0c_recomuons_muonsfromcosmics__reco_obj_calenergy_ems9
all_sign513vsorig_singlemupt10wf20p0c_recomuons_muonsfromcosmics__reco_obj_calocompatibility

- muonsFromCosmics1Leg change significantly in muon gun samples (real dimuons)
(same 10 GeV muon gun sample). In this case pointing capabilities are worse to the HCAL as well
all_sign513vsorig_singlemupt10wf20p0c_recomuons_muonsfromcosmics1leg__reco_objat_size
all_sign513vsorig_singlemupt10wf20p0c_recomuons_muonsfromcosmics1leg__reco_obj_calenergy_ecal_time
all_sign513vsorig_singlemupt10wf20p0c_recomuons_muonsfromcosmics1leg__reco_obj_calenergy_hads9
all_sign513vsorig_singlemupt10wf20p0c_recomuons_muonsfromcosmics1leg__reco_obj_calocompatibility

**Comment by davidlange6** [comment]
+1

**Pull request merged**
