### PR TITLE
Run3-gex138 Replace getbylabel using token in CalibCalorimetry/CastorCalib

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Replace getbylabel using token in CalibCalorimetry/CastorCalib

#### PR validation:

Use the runTheMatrix test workflows

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Review by ChrisMisan — COMMENTED** [review]
@bsunanda there are some things outside of this PR scope that can be changed:

- cout is not allowed, consider using logging system

https://github.com/cms-sw/cmssw/blob/2f5d80a5f96bc7e8a0a428fba1b2f0a1fc324a0f/CalibCalorimetry/CastorCalib/plugins/CastorPedestalsAnalysis.cc#L135

https://github.com/cms-sw/cmssw/blob/2f5d80a5f96bc7e8a0a428fba1b2f0a1fc324a0f/CalibCalorimetry/CastorCalib/plugins/CastorPedestalsAnalysis.cc#L140

- this can be simplified into a loop
https://github.com/cms-sw/cmssw/blob/2f5d80a5f96bc7e8a0a428fba1b2f0a1fc324a0f/CalibCalorimetry/CastorCalib/plugins/CastorPedestalsAnalysis.cc#L143

- There is a lot of commented code, which sometimes is not even correct in terms of the syntax
https://github.com/cms-sw/cmssw/blob/2f5d80a5f96bc7e8a0a428fba1b2f0a1fc324a0f/CalibCalorimetry/CastorCalib/plugins/CastorPedestalsAnalysis.cc#L207

**Comment by ChrisMisan** [comment]
please test

**Comment by tvami** [comment]
type bugfix,castor

**Comment by ChrisMisan** [comment]
> type bugfix,castor

@tvami I don't think there's castor label

**Comment by tvami** [comment]
> > type bugfix,castor
> 
> @tvami I don't think there's castor label

@smuzaffar although Castor is decommissioned, the code still exists. I think making the label would be helpful.

**Comment by smuzaffar** [comment]
> > > type bugfix,castor
> > 
> > 
> > @tvami I don't think there's castor label
> 
> @smuzaffar although Castor is decommissioned, the code still exists. I think making the label would be helpful.

if it is just for label then I can update https://github.com/cms-sw/cms-bot/blob/master/githublabels.py#L33 to include `castor` otherwise please suggest a change for `CMSSW_L2` at https://github.com/cms-sw/cms-bot/blob/master/categories.py#L141

**Comment by tvami** [comment]
> if it is just for label then I can update

it's just a label, we dont need the L2 category

**Comment by tvami** [comment]
+alca
 * test pass, failures in MsgL only
 * with the caveat that there is more to do in a follow-up PR as described in https://github.com/cms-sw/cmssw/pull/39176#pullrequestreview-1083850249

**Comment by perrotta** [comment]
+1

**Pull request merged**
