### PR TITLE
Fix static warnings on DT L1T

### PR DESCRIPTION
**Pull request by jfernan2**
#### PR description:

This PR fixes some static warnings in DT L1T emulator detected during integration of AMv2 in https://github.com/cms-sw/cmssw/pull/43390

Out of the 8 warnings (see below), only the first 2 have been fixed by this PR.

Those related to core.uninitialized.Branch look false positives as far as I can see, since the vectors pointed out have been initialized previously at the beginning on purpouse to false in https://github.com/cms-sw/cmssw/blob/master/L1Trigger/DTTriggerPhase2/src/MuonPathAssociator.cc#L123-L127

The last one claims a nonFinite computation but this is exactly what is being tried to avoid.

I am not sure if the code experts like @makortel have any advice on how to proceed. Thanks in advance.

Static Warnings:
/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_14_0_X_2023-11-29-2300/src/L1Trigger/DTTriggerPhase2/src/GlobalCoordsObtainer.cc:222:3: warning: Value stored to 'x_msb' is never read [deadcode.DeadStores]
  222 |   x_msb = from_two_comp(x_msb, PHI_LUT_ADDR_WIDTH);
      |   ^       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_14_0_X_2023-11-29-2300/src/L1Trigger/DTTriggerPhase2/src/GlobalCoordsObtainer.cc:225:3: warning: Value stored to 'tanpsi_msb' is never read [deadcode.DeadStores]
  225 |   tanpsi_msb = from_two_comp(tanpsi_msb, PHIB_LUT_ADDR_WIDTH);
      |   ^            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_14_0_X_2023-11-29-2300/src/L1Trigger/DTTriggerPhase2/src/MuonPathAssociator.cc:592:15: warning: Branch condition evaluates to a garbage value [core.uninitialized.Branch]
  592 |           if (useFitSL3[sl3])
      |               ^~~~~~~~~~~~~~
/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_14_0_X_2023-11-29-2300/src/L1Trigger/DTTriggerPhase2/src/MuonPathAssociator.cc:844:19: warning: Branch condition evaluates to a garbage value [core.uninitialized.Branch]
  844 |               if (useFitSL1[sl1])
      |                   ^~~~~~~~~~~~~~
/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_14_0_X_2023-11-29-2300/src/L1Trigger/DTTriggerPhase2/src/MuonPathAssociator.cc:905:19: warning: Branch condition evaluates to a garbage value [core.uninitialized.Branch]
  905 |               if (useFitSL3[sl3])
      |                   ^~~~~~~~~~~~~~
/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_14_0_X_2023-11-29-2300/src/L1Trigger/DTTriggerPhase2/src/MuonPathAssociator.cc:1011:9: warning: Branch condition evaluates to a garbage value [core.uninitialized.Branch]
 1011 |     if (!useFit[i])
      |         ^~~~~~~~~~
/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_14_0_X_2023-11-29-2300/src/L1Trigger/DTTriggerPhase2/src/MuonPathAssociator.cc:1016:11: warning: Branch condition evaluates to a garbage value [core.uninitialized.Branch]
 1016 |       if (!useFit[j])

/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_14_0_X_2023-11-29-2300/src/L1Trigger/DTTriggerPhase2/src/MuonPathAnalyzerInChamber.cc:245:9: warning: cms.NonFiniteMath [cms.NonFiniteMath]
  245 |     if (isnan(jm_x))
      |         ^
1 warning generated.

### CODE REVIEW

**Comment by epalencia** [comment]
Please test

**Comment by makortel** [comment]
> The last one claims a nonFinite computation but this is exactly what is being tried to avoid.

The static analyzer report https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-e133a0/36189/llvm-analysis/ contains a suggestion for what to do for that warning
> std::isnan / std::isinf does not work when fast-math is used. Please use edm::isNotFinite from 'FWCore/Utilities/interface/isFinite.h'

**Comment by makortel** [comment]
About the "Branch condition evaluates to a garbage value" warnings, the links from the static analyzer report show the exact branch decisions the analyzer did to come to its conclusion. Here is the one about `L1Trigger/DTTriggerPhase2/src/MuonPathAssociator.cc:592`
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-e133a0/36189/llvm-analysis/report-091cc9.html#EndPath

I think the warning in this case is about the case where `not SL1metaPrimitives.empty()` and `SL3metaPrimitives.empty()`. It seems to me the static analyzer either assumes the `SL1metaPrimitives`/`SL3metaPrimitives` containers can change between calls, or doesn't somehow recognize the connection between `empty()`, `size()`, and `begin()`+`end()`.

Note that variable length arrays (VLA, `bool useFitSL1[SL1metaPrimitives.size()];`) are not standard C++ (but an extension by GCC, and clang supports it as well). Zero-length arrays seem to be another extension by GCC. I think it would be much better to avoid at least the zero-length VLAs.

**Comment by epalencia** [comment]
Please test

**Comment by epalencia** [comment]
Please test

**Comment by srimanob** [comment]
+Upgrade

The warnings on `Value stored to XXX is never read` and `cms.NonFiniteMath` are gone in the static check.

**Comment by aloeliger** [comment]
+l1

**Comment by rappoccio** [comment]
+1

**Pull request merged**
