### PR TITLE
Injection of workflows without approving them

### PR DESCRIPTION
**Pull request by fabozzi**
We inject workflows without approving at the same time. Approval of workflows will be done by the submitter via reqmgr2 interface. This procedure comes with removal of 4h "grace" period in Unified before assigning the workflows.

### CODE REVIEW

**Comment by fabozzi** [comment]
please test

**Comment by fabozzi** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Comment by davidlange6** [comment]
hi @fabozzi - could you just remove the line instead of commenting it out. thanks

**Comment by fabozzi** [comment]
please test

**Comment by fabozzi** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
