### PR TITLE
OnlineDQM : Move uGMT output to uGT input comparison histogram to the uGT directory

### PR DESCRIPTION
**Pull request by stahlleiton**
Solves the JIRA Ticket: https://its.cern.ch/jira/browse/CMSLITDPG-325

Description:

- Move uGMT vs uGT comparison Plots and Quality Tests to uGT workspace

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
please test

**Comment by stahlleiton** [comment]
It seems the unit test error is not related to this PR but I might be wrong. Not sure why it failed to open the file 'dqm_missing.root'

**Comment by rekovic** [comment]
please test

**Comment by rekovic** [comment]
+1

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
