### PR TITLE
Change to new method in PoolDBOutputService for SiPixel CPE

### PR DESCRIPTION
**Pull request by tvami**
#### PR description:

Change to new method of `writeOneIOV` in PoolDBOutputService for SiPixel CPE. This also meant changing the pointers to the instance of the object.

As part of https://github.com/cms-AlCaDB/AlCaTools/issues/28

#### PR validation:

`scramv1 b runtests` run fine

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

### CODE REVIEW

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
cc @SanjanaSekhar

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
@cmsbuild , please test with https://github.com/cms-sw/cmssw/pull/36021

**Comment by tvami** [comment]
unit tests are running fine: https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-a090e3/20317/unitTests/src/CondTools/SiPixel/test/testPixelDBs/testing.log

**Comment by tvami** [comment]
+db

**Comment by qliphy** [comment]
+1

**Pull request merged**
