### PR TITLE
Run4-278X Bug fix for allowing more scintillator cells beyond Digi

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Bug fix for allowing more scintillator cells to appear after Digi and Reco

#### PR validation:

Tested using runTheMatrix workflows

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by srimanob** [comment]
Urgent

FYI @qliphy @silviodonato

**Comment by cvuosalo** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

**Comment by qliphy** [comment]
+1

**Pull request merged**
