### PR TITLE
[LLVM Analyzer][Generators] Cleanup LLVM analyzer warnings

### PR DESCRIPTION
**Pull request by iarspider**
#### PR description:

See [report](https://cmssdt.cern.ch/SDT/jenkins-artifacts/ib-static-analysis/CMSSW_14_2_X_2024-10-13-0000/el8_amd64_gcc12/llvm-analysis/index.html)

#### PR validation:

Bot tests

### CODE REVIEW

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
please abort

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
@cmsbuild ignore tests-rejected with external-failure

**Comment by iarspider** [comment]
@cms-sw/generators-l2 gentle ping

**Comment by iarspider** [comment]
@cmsbuild please test

**Comment by lviliani** [comment]
+1

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
