### PR TITLE
Remove Obsolete Packages from BuildFiles

### PR DESCRIPTION
**Pull request by ianna**
* Remove references to deleted packages

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by ptcox** [comment]
Please let me know where the CSC data files have been moved. Thanks.


On June 27, 2017 at 11:44:27 , cmsbuild (notifications@github.com) wrote:

A new Pull Request was created by @ianna (Ianna Osborne) for master.

It involves the following packages:

Geometry/CSCGeometryBuilder
Geometry/DTGeometryBuilder
Geometry/EcalCommonData
Geometry/EcalTestBeam
Geometry/MTCCTrackerCommonData

@civanch, @Dr15Jones, @ianna, @mdhildreth, @cmsbuild, @davidlange6 can you please review it and eventually sign? Thanks.
@ghellwig, @ptcox, @argiro this is something you requested to watch as well.
@davidlange6 you are the release manager for this.

cms-bot commands are listed here

**Comment by ianna** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
