### PR TITLE
Updated Input tags and code additions for TOP Production DQM GEN-SIM-RECO

### PR DESCRIPTION
**Pull request by dsidirop1**
### **Description of PR**

- The main changes expected relate to the histograms for the non mini AOD (RECO) directories of TOP DQM Production now being filled (to previously being empty) after the input tags for Muons, Electrons, Jets and the B-tags were updated to non obsolete tags included in the most recent input files for `CMSSW_14_2_0_pre3`. Fot the updated B-tags from the old CSV ones to deepCSV the working points were updated accordingly based on the 2018 campaign as described on the BTV internal wiki. 
- Other changes made include: 

1. the update from `<reco::PFCandidate>` objects which are obsolete to  f.e. `<reco::Muon>`, `<reco::GsfElectron>` per the relevant objects found in the input files used. 
2.  The update of selection cuts structure to remove unnecessary references and dependencies e.g. `mediumMuonCut = looseMuonCut + " muonRef.innerTrack.validFraction > 0.8"` becomes `mediumMuonCut = looseMuonCut + " innerTrack.validFraction > 0.8"`.
3. Some unnecessary checks in loops like: 
```
 if (muonit->muonRef().isNull())
        continue;
      reco::MuonRef muon = muonit->muonRef();
```
in [TopSingleLeptonDQM.cc](https://github.com/cms-sw/cmssw/blob/48600daa76c0dd3925eb34d216bc756ed556016d/DQM/Physics/src/TopSingleLeptonDQM.cc#L465) were removed completely.
4. Histograms for jets 3 and 4 were added to [SingleTopTChannelLeptonDQM.cc](https://github.com/cms-sw/cmssw/blob/master/DQM/Physics/src/SingleTopTChannelLeptonDQM.cc) for completion purposes and to align it with the [TopSingleLeptonDQM.cc](https://github.com/cms-sw/cmssw/blob/master/DQM/Physics/src/TopSingleLeptonDQM.cc) analysis.
5. Certain comments that were not useful or obsolete were removed to make the code more conscise. 

- There is a minor dependence on a previous PR number #44299 which dealt with the same issues for the miniAOD directories in the TOP DQM where the main focus was tag updating as in here.
- [BTV internal wiki 2018 campaign](https://btv-wiki.docs.cern.ch/ScaleFactors/UL2018/)

#### PR validation:

Changes have been made to the following files:

- DQM/Physics/interface/TopDQMHelpers.h
- DQM/Physics/python/singleTopDQM_cfi.py
- DQM/Physics/python/topSingleLeptonDQM_cfi.py
- DQM/Physics/src/SingleTopTChannelLeptonDQM.cc
- DQM/Physics/src/SingleTopTChannelLeptonDQM.h
- DQM/Physics/src/TopDQMHelpers.cc
- DQM/Physics/src/TopSingleLeptonDQM.cc
- DQM/Physics/src/TopSingleLeptonDQM.h
- DQM/Physics/test/topDQM_harvesting_cfg.py
- DQM/Physics/test/topDQM_production_cfg.py

To verify the results of the aforementioned actions the file `DQM/Physics/test/topDQM_production_cfg.py` was executed with `cmsRun` to produce a .root file that was then used as input for the `DQM/Physics/test/topDQM_harvesting_cfg.py` to produce a tree with the relevant histograms needed that were browsed using the TBrowser root feature. As evidence of the success of the task two of those histograms (one from `TopSingleMuonMediumDQM` and the other from `SingleTopElectronMediumDQM`) are attached on this PR.

TopSingleMuonMediumDQM_step1_Jet1Pt
SingleTopElectronMediumDQM_step2_METPflow

### CODE REVIEW

**Comment by mseidel42** [comment]
Please wait with the new tests, Dimitrios is going to clean up this PR a little

**Comment by dsidirop1** [comment]
PR has been cleaned up properly please test again

**Comment by antoniovagnerini** [comment]
please test

**Comment by antoniovagnerini** [comment]
+1
- spurious differences from HGCal DQM test (open issue  #46416)

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
