### PR TITLE
Offline DQM for BTV:  HLT_BTagMu_AK8Jet170_DoubleMu5_v path.

### PR DESCRIPTION
**Pull request by marinakolosova**
Added Offline DQM for path: HLT_BTagMu_AK8Jet170_DoubleMu5_v.

@defranchis @heppye @tiwariPC

### CODE REVIEW

**Comment by mtosi** [comment]
@cmsbuild, please test

**Comment by mtosi** [comment]
@marinakolosova could you please quantify the increase in #bins ?
thanks

**Comment by marinakolosova** [comment]
@mtosi 
Hi Mia, the number of bins is ~23K, most of them coming from LS profile plots.

**Comment by mtosi** [comment]
I was expecting so, indeed
please, note I prepare a PR [1]
which should --at least partially-- address this
uhmm, just realized hltBTVmonitoring ...
can you please fix it, by decreasing the #bins ?

thanks
  mia
[1]
https://github.com/cms-sw/cmssw/pull/20439

**Comment by mtosi** [comment]
I've updated the PR #20439
=> it should be fine, now

**Comment by davidlange6** [comment]
Your PR is unmergeable. Please have a look and possibly rebase it.

**Comment by davidlange6** [comment]
seems to be obsolete - closing this PR.

**Comment by marinakolosova** [comment]
Hi, we'll reopen a new one after finalizing the studies for this path (HLT_BTagMu_AK8Jet170_DoubleMu5_v)
Thanks, 
Marina

**Pull request closed without merging**
