### PR TITLE
fix name of input collection in pathALCARECOHcalCalMinBias

### PR DESCRIPTION
**Pull request by franzoni**
The alcareco running on HcalNZS, HcalCalMinBias, has a few modules in its path with typo (hcalDigiAlaMB instead of hcalDigiAlcaMB) in the name of the HCAL digis input collection they (try to) consume.
This failure emerges now thanks to the fact that patch2 fixed another problem with the same alcareco.

The issue originated here https://github.com/cms-sw/cmssw/pull/18367/files .
It is understood how such mis-labelling passed the IB tests: the prompt-like relval workflow (1000) processes MinBias PD form 2011 where the rate of events firing HLT_HcalPhiSym* is low; because of the HLT selection at the start of HcalCalMinBias, the misconfigured modules were never executed.

@bsunanda @kpedro88 : may you please Xheck and comment ?
@deguio @hatakeyamak

### CODE REVIEW

**Comment by franzoni** [comment]
please test

**Comment by kpedro88** [comment]
@franzoni the collection name changes here look correct to me

however, this PR also duplicates #18853, which hasn't been merged in master yet - could cause conflicts

**Comment by franzoni** [comment]
thanks @kpedro88
I am willing to bet a coffee that git will handle the case well :-)
In fact this:

```
cmsrel CMSSW_9_2_X_2017-05-22-1100
cd  CMSSW_9_2_X_2017-05-22-1100/src ; esr
git cms-addpkg Calibration/HcalAlCaRecoProducers
git cms-merge-topic 18853
git cms-merge-topic 18892
```

worked ok and gave a history and files content which makes sense.

**Comment by franzoni** [comment]
closing since replaced by : https://github.com/cms-sw/cmssw/pull/18890 
will open a clone of this to the 9_2_X branch

**Pull request closed without merging**
