### PR TITLE
Adding dedicated CaloLayer2 shifter plots

### PR DESCRIPTION
**Pull request by vukasinmilosevic**
Change requested in: https://its.cern.ch/jira/browse/CMSLITDPG-480
The online shifter plots 02-07 needed some work to make them more comprehensible for shifters and other non-experts (the old/expert plots are saved in the same location, while the new plots are placed under a new "shifter" folder).

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by thomreis** [comment]
Hi @vukasinmilosevic 
please provide a 10_1_X PR as well that we can ask to have deployed in the online DQM.

**Comment by dmitrijus** [comment]
assign l1t

**Comment by dmitrijus** [comment]
+1

**Comment by thomreis** [comment]
please test

**Comment by thomreis** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by fabiocos** [comment]
@vukasinmilosevic @thomreis the memory addition is modest, still are both the old and new versions of the plots needed at the same time?

**Comment by fabiocos** [comment]
+1

nevertheless I would like an answer to my question

**Comment by vukasinmilosevic** [comment]
Hi @fabiocos, I'm sorry for the late response. The old plots are needed for the CaloLayer2 experts.

**Comment by thomreis** [comment]
Hi @fabiocos 
I remember typing a reply to the question but I must have forgotten to post it afterwards. Sorry about that. @vukasinmilosevic gave the answer already now. We want to keep the high granularity histograms for the experts but for the shifters they are too confusing.

**Pull request merged**
