### PR TITLE
Adding new substructure triggers to B2G DQM

### PR DESCRIPTION
**Pull request by alefisico**

### CODE REVIEW

**Comment by dmitrijus** [comment]
+1

**Comment by dmitrijus** [comment]
-1
Just noticed, 81x is still missing! It was opened and closed. Please either create a new PR for 81x or close this one.

**Comment by alefisico** [comment]
sorry but the PR for 81X #15874 was merged, or am I missing something? 
Also, maybe I am confused but you are saying that if I open the PR for 80X I should NOT open for 81X and viceversa?

**Comment by dmitrijus** [comment]
+1
Sorry. it means I just failed to find 81x request. That's why you should always link them, by simply pasting a link to a 81x PR in a comment, or vice-versa.

**Comment by dmitrijus** [comment]
81x PR should always go first. The issue here was the 81x one not mentioned, nor this PR indicated that it is backport.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
