### PR TITLE
Fix for Puppi MET and MET significance compatibility between AOD and miniAOD (80X)

### PR DESCRIPTION
**Pull request by mmarionncern**
From what I understood, there is some space for pushing small PRs in 8_0_21 that will be used for MC production as L1 is still missing.

That PR is similar to #16140 for 80X. If we have the opportunity to push it in the release rather than offering a private recipe as it was planned by the MET group, that would be probably less confusing for the analysers.
(N.B. this PR touches the reco sequence, let me know if we cannot push this PR due to that)

### CODE REVIEW

**Comment by slava77** [comment]
@mmarionncern 
please clarify if miniAOD or AOD changes are expected from this PR.
If yes, this PR can not be added to 80X production,
at least until new re-miniAOD campaign is defined for data (rereco now ongoing).

**Comment by mmarionncern** [comment]
@slava77 Yes, mAOD changes are expected for the puppiMET and the MET significance. What would be the best action here? put this PR on hold or close it and reopen it once we are ready for a re-reco?

**Comment by slava77** [comment]
@mmarionncern 
we can test it to confirm it's functional.
Since there is no clearly planned re-miniAOD at this point, I suggest that then this PR is closed and we can open it when the re-miniAOD campaign becomes a reality.
To simplify tracking, I opened #16177

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
-1

@mmarionncern 
this should be made in sync with 81X version.

**Comment by mmarionncern** [comment]
@slava77 the 80X branch is now in sync with the 81X one

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cmsbuild please test
looks like DAS problems were solved

**Comment by slava77** [comment]
@cmsbuild please test
maybe comparisons actually show up this time

**Comment by slava77** [comment]
@cmsbuild please test
comparisons should be fixed now (changes were merged to cms-bot a few hours back)

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
hold

leave on hold until new re-miniAOD campaign opens (candidates for that are tracked in https://github.com/cms-sw/cmssw/issues/16177).

**Comment by slava77** [comment]
backport of #16140

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/16174 e62247d
- backport of features already merged in 81X (as #16140)
- jenkins tests pass and comparisons with baseline show differences in MET significance value in miniAOD METs

This PR is left on hold due to changes in miniAOD values. Do not merge until a new re-miniAOD release.

**Comment by slava77** [comment]
@mmarionncern 
was your latest change submitted to 81X already?
Once it's available as 81X PR, please post "backport of #number " here for info
Thank you.

**Comment by mmarionncern** [comment]
@slava77 There is still one 81X PR to make, I will update the decription accordingly once the 81X is ready and merged

**Comment by mmarionncern** [comment]
Also contains the backport of #16435

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
The error in data relval appears to be related to this PR.

Since the legacy rereco is somewhat firmly in the plans, fix of this PR will be eventually needed if the feature were to go to 80X legacy rereco.

**Comment by slava77** [comment]
@mmarionncern 
please follow up on the issue reported in the data workflow 136.731
I suggest to first reproduce this in the latest release CMSSW_8_0_24

**Comment by mmarionncern** [comment]
Currently working on it, should be done by early next week.

**Comment by slava77** [comment]
@cmsbuild please test

@mmarionncern please make a PR for 81X and 90X with matching changes

**Comment by mmarionncern** [comment]
Last changed documented in the 81X version :
https://github.com/cms-sw/cmssw/pull/16712

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by mmarionncern** [comment]
@slava77 there are still some small fixes to propagate that we identified yesterday evening, no need to start the full review yet

**Comment by slava77** [comment]
On 11/22/16 12:41 AM, mmarionncern wrote:
> @slava77 <https://github.com/slava77> there are still some small fixes
> to propagate that we identified yesterday evening, no need to start the
> full review yet

Uhm. OK.
Is there some clear strategy with these developments?
It looks like we have updates on about a monthly basis in this area.

**Comment by mmarionncern** [comment]
@slava77 we have main developments/large fixes we make usually when conference rushes are over. When recipes are ready, we share them to everybody, but there are always some people not using the tool in the way we designed it, and that report to us some small fixes that we try to fix asap

**Comment by slava77** [comment]
On 11/22/16 2:45 AM, mmarionncern wrote:
> @slava77 <https://github.com/slava77> we have main developments/large
> fixes we make usually when conference rushes are over. When recipes are
> ready, we share them to everybody, but there are always some people not
> using the tool in the way we designed it, and that report to us some
> small fixes that we try to fix asap

OK.
I guess we'll wait until next Monday to review these to leave some time
for cross-checks on your side that everything is reasonably OK.
Please let me know if more time will be needed.

**Comment by mmarionncern** [comment]
Fixes done, ready to resume the signature validation

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/16174 6d30502
- continuing accumulation of backported features: this is now a combination of #16140 #16435 #16713. 
    - due to changes in miniAOD products, this PR is left on hold until we can have updates in 80X
- jenkins tests pass ; comparisons with baseline show only the previously added changes to the miniAOD MET significance computation, additional changes in JetRes plots did not show up even though the new code here and in 81X/90X is the same (no DQM or low statistics?)

**Comment by riga** [comment]
Hi,

are there any news on this PR?

cms-met:METRecipe_8020 cannot be used in the current 8_0_X release (26_patch1) due to the conflict in runMETCorrectionsAndUncertainties.py. As far as I see, #16140 #16435 and #16713 were already merged.

**Comment by mmarionncern** [comment]
@riga This PR is holded till a potential 80X re-miniAOD campaign, and won't be merged in the close future.
The MET people are currently updating the standalone MET recipe, please wait a bit the time we validate everything

**Comment by riga** [comment]
Hi @mmarionncern , thanks for the clarification!

**Comment by slava77** [comment]
@mmarionncern 
there is a merge conflict here.
Please update the pr

**Comment by slava77** [comment]
@mmarionncern 
the last update here apparently goes beyond the initial description of this PR.
Also, some of the new filters do not appear in 90X.
They should be integrated there first.
Please provide the 90X PR number(s)

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by mmarionncern** [comment]
@slava77 currently checking the integration in 90X, this may take me some time to be sure I do everything properly

**Comment by slava77** [comment]
On 2/6/17 7:18 AM, mmarionncern wrote:
> @slava77 <https://github.com/slava77> currently checking the integration
> in 90X, this may take me some time to be sure I do everything properly

If I'm not mistaken,
some filters first appeared in
https://github.com/cms-sw/cmssw/pull/15761

Please make sure that the comments made there are addressed.

Please update the title and the description of this 80X PR if you intend
to keep it the way it is now.

**Comment by mmarionncern** [comment]
Some photon ID used in Puppi is not in the 80X branch, we rolled back to the previous (and working ) configuration

**Comment by slava77** [comment]
@cmsbuild please test

@mmarionncern is everything new in this PR already available in 90X?
If not, please make a PR for 90X

**Comment by mmarionncern** [comment]
@slava77 currently working on the 90X PR, hopefully ready by this afternoon

**Comment by slava77** [comment]
@mmarionncern 
please confirm that ```runTheMatrix.py -l limited``` runs for you locally
I will be able to start jenkins tests after that.

**Comment by mmarionncern** [comment]
@slava77 limited matrix tests are successful locally

**Comment by slava77** [comment]
@cmsbuild please test

@mmarionncern thanks for confirmation

**Comment by slava77** [comment]
current plan for miniAOD in connection with legacy rereco is to 
- have v1 done only on data
- later have v2 to be applied to both data and MC and also aiming to be in sync with the 2017 miniAOD [it may be feasible to have v2 in 91X, still to be confirmed]

This means that changes in miniAOD that affect both data and MC are not going to go to v1
if it modifies behavior of existing algorithms.
From this PR changes: 
- puppi and MET significance fixes do not fit the v1 scope
- bad object filters are OK in v1 scope

I propose to break up this PR in two; otherwise this can only go with v2.
Please note that the bad object filters implementation should still be made in sync with the proposed version in 9X release.

**Comment by mmarionncern** [comment]
@slava77 if I do the following : 
- create a new PR with V1 filter changes
- keep the current PR for V2 updating it accordlingly to reflect the changes of the filters made in the previous v1 PR

Would it be fine for you?
I badly designed that PR as the v1 and v2 material are mixed together in commits, so that would ease the developments, but I would fully understand if you don't want that. (However I am out of office next week and will only be able to work on it today)

**Comment by slava77** [comment]
On 3/17/17 1:51 AM, mmarionncern wrote:
> @slava77 <https://github.com/slava77> if I do the following :
> 
>   * create a new PR with V1 filter changes
>   * keep the current PR for V2 updating it accordlingly to reflect the
>     changes of the filters made in the previous v1 PR
> 
> Would it be fine for you?
> I badly designed that PR as the v1 and v2 material are mixed together in
> commits, so that would ease the developments, but I would fully
> understand if you don't want that. (However I am out of office next week
> and will only be able to work on it today)

At this point in time a fully consistent PR for V2 is not required (it
can be made after the split-off for V1).
So, you can just make that today.
Making a new PR instead of rewriting this one may be easier.

**Comment by mmarionncern** [comment]
That PR is now ready for V2 with the inclusion of V1 filter development included separately in #17968

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@mmarionncern 
now that #17968 is merged , please remove changes from this PR that are already in 80X.
This will be needed towards miniAODv2.
Thank you.

**Comment by mmarionncern** [comment]
@slava77, as the relevant commits are the same as the ones of #17968, I am not sure to understand why the changes should be removed from the PR. The merge should take care automatically of the commit "duplication". Can you clarify?

Thanks

**Comment by slava77** [comment]
On 4/12/17 6:00 AM, mmarionncern wrote:
> @slava77 <https://github.com/slava77>, as the relevant commits are the
> same as the ones of #17968 <https://github.com/cms-sw/cmssw/pull/17968>,
> I am not sure to understand why the changes should be removed from the
> PR. The merge should take care automatically of the commit
> "duplication". Can you clarify?
> 

git diffs in this PR still show these files as changed (it's a feature
of the web interface).
I prefer to have a clean PR.

**Comment by mmarionncern** [comment]
Done, the remnant merge commit is not reverted to avoid touching files that were not touched in #17968

**Comment by slava77** [comment]
diffs show files like  141 RecoMET/METFilters/plugins/BadChargedCandidateSummer16Filter.cc 
IIUC, these do not belong in here

**Comment by mmarionncern** [comment]
@slava77 That file is not overlapping with #17968, this is part of the first commits of the PR.

**Comment by slava77** [comment]
On 4/12/17 7:10 AM, mmarionncern wrote:
> @slava77 <https://github.com/slava77> That file is not overlapping with
> #17968 <https://github.com/cms-sw/cmssw/pull/17968>, this is part of the
> first commits of the PR.

Are you now proposing to add these?
Why are they needed in addition to BadParticleFilter?

Please clarify or clean up.

Thank you.

**Comment by mmarionncern** [comment]
Either I remove them and do an extra merge with the current 80X branch, which basically make this PR similar to its previous status, or I remove the filter calls from the config files as otherwise the current branch won't be able to run in a standalone way as it needs at least one version of the filter.

**Comment by slava77** [comment]
On 4/12/17 8:18 AM, mmarionncern wrote:
> Either I remove them and do an extra merge with the current 80X branch,
> which basically make this PR similar to its previous status, or I remove
> the filter calls from the config files as otherwise the current branch
> won't be able to run in a standalone way as it needs at least one
> version of the filter.

I'm missing something:
- it sounds like you are saying that e.g. BadChargedCandidateFilter.cc
is needed to run something
- there is no config in this PR or in 80X that uses this plugin
(BadChargedCandidateFilter).

The PR has to be clean and self-consistent.

**Comment by mmarionncern** [comment]
Either the BadChargedCandidateFilter or the old filters that are still in this PR are needed to run the filters defined in
https://github.com/cms-sw/cmssw/blob/CMSSW_8_0_X/RecoMET/METFilters/python/metFilters_cff.py

In this PR, the former module does not exists and the PR includes a call to the previous version of the filter, in the same way as the latest an greatest one : 
https://github.com/cms-sw/cmssw/pull/16174/files#diff-09b1dcadbdc74bad980084e7fc64628d

If I remove the old filters, I have to remove the call from the configuration as well, and thus propagate that change to 80X, which is not something wanted. If I do not remove the call, the PR is not self-consistent as filters are missing.

To be correct, I would need to merge the 80X content that is not yet in this PR, but that would lead to the same situation as the one it was this morning, with the inclusion of #17968 in that PR.

**Comment by slava77** [comment]
On 4/12/17 8:57 AM, mmarionncern wrote:
> Either the BadChargedCandidateFilter or the old filters that are still
> in this PR are needed to run the filters defined in
> https://github.com/cms-sw/cmssw/blob/CMSSW_8_0_X/RecoMET/METFilters/python/metFilters_cff.py
> 

Please point me to the line in this PR or in 80X where the plugin named
BadChargedCandidateFilter (and defined in BadChargedCandidateFilter.cc)
is called.

Currently I think that all the Bad* filters should be removed from this
PR, including with edits in
RecoMET/METFilters/python/metFilters_cff.py which are currently
redundant (null diff edits, actually) with what's in 80X.

But you seem to indicate that this is needed for some reason.


> In this PR, the former module does not exists and the PR includes a call
> to the previous version of the filter, in the same way as the latest an
> greatest one :
> https://github.com/cms-sw/cmssw/pull/16174/files#diff-09b1dcadbdc74bad980084e7fc64628d
> 
> If I remove the old filters, I have to remove the call from the
> configuration as well, and thus propagate that change to 80X, which is
> not something wanted. If I do not remove the call, the PR is not
> self-consistent as filters are missing.
> 
> To be correct, I would need to merge the 80X content that is not yet in
> this PR, 

this is a PR for 80X and by construction it should not contain features
that are already in 80X.

**Comment by mmarionncern** [comment]
I am not saying that the BadChargedCandidateFilter is called, I am saying that the removal of the filters in that PR would necessitate the removal of the following config lines 
https://github.com/cms-met/cmssw/blob/eec42610ed5039958968488755acf27723ab4e69/RecoMET/METFilters/python/metFilters_cff.py#L97-L100

which is not wanted in CMSSW, as we explicitely added them in 80X with the #17968 PR already.

I would be happy to remove the old filters that are indeed not needed anymore, but those lines cannot be removed

**Comment by mmarionncern** [comment]
Other possibility, rebase that branch on top of the last 80X developments and recreate a new one

**Comment by slava77** [comment]
On 4/12/17 9:13 AM, mmarionncern wrote:
> I am not saying that the BadChargedCandidateFilter is called, I am
> saying that the removal of the filters in that PR would necessitate the
> removal of the following config lines
> https://github.com/cms-met/cmssw/blob/eec42610ed5039958968488755acf27723ab4e69/RecoMET/METFilters/python/metFilters_cff.py#L97-L100
> 
> which is not wanted in CMSSW, as we explicitely added them in 80X with
> the #17968 <https://github.com/cms-sw/cmssw/pull/17968> PR already.
> 
> I would be happy to remove the old filters that are indeed not needed
> anymore, but those lines cannot be removed

OK, it sounds like your comments are mostly on the technical side
related to individual commit content.
I don't really care how this PR is cleaned up and what is done with
individual old commits (revert/rebase/remake etc).

The goal is that the final web-based diff should show no irrelevant
differences
and the factually unnecessary files should be removed.

**Comment by mmarionncern** [comment]
Rebased on top of 80X in #18341 
Closing this one

**Pull request closed without merging**
