### PR TITLE
Run3-gem82 Change in GE21 setup in view of last minute changes

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Change in GE21 set up in view of the last-minute changes

#### PR validation:

Tested using fireworks

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
+geometry

**Comment by bsunanda** [comment]
@Moanwar, @subirsarkar Could you approve this PR?

**Comment by subirsarkar** [comment]
+Upgrade

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
