### PR TITLE
trim hep top tagger combinatorics, drop hepTopTagPFJetsCHS from RECO sequence

### PR DESCRIPTION
**Pull request by slava77**
somewhat arbitrary upper limit on the number of candidate jets in the HEPTopTagger.
These conditions appear in running on beam splash events.
The limit is 2^15, we could probably handle ~1M without killing the jobs; but even a few K seems beyond anything realistic.
The size of the candidates grows as N^3 in this algorithm, so it runs away pretty quickly.

After feedback from Jim, I also removed hepTopTagPFJetsCHS from recoPFJets sequence

@rappoccio @jdolen please take a look and maybe suggest something else (on a short time scale)

### CODE REVIEW

**Comment by slava77** [comment]
Sal, Jim, Andreas

could you please clarify why we are running hepTopTagPFJetsCHS in RECO?
It's not saved and the only module consuming these is hepTopTagInfos which is not running in standard workflow.

Was a  keep statement forgotten or is this collection actually no needed?

**Comment by jdolen** [comment]
If I recall correctly _top_parts.size()  (the number of subjets found by the mass drop step of the HTT) is typically <10 and I would expect always <20. I emailed Emanuele to confirm this (I believe he made a plot of this last year). Adding this upper limit seems like a good safety measure.

hepTopTagPFJetsCHS should not be run in RECO.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by rappoccio** [comment]
Sorry guys, sorry for the delay, I'm giving a talk at PI today and tomorrow. These were at one point supposed to be kept but perhaps they were dropped without taking them out of the sequence (I don't recall). For now, we can for sure leave them out of RECO of course.

**Comment by slava77** [comment]
@nclopezo 
David, the comparisons link is dead
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_7_3_X_2015-03-15-0200+8330/7113/
The message about comparisons available https://github.com/cms-sw/cmssw/pull/8330#issuecomment-82163290 was sent 4 hours ago. Did something fail?

**Comment by nclopezo** [comment]
Hi Slava, 

The transfer of the files from the node that executed the comparisons had issues. I restarted them.

**Comment by nclopezo** [comment]
The results are here:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_7_3_X_2015-03-15-0200+8330/6704/

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/8330	 cc18cf6
tested originally in CMSSW_7_3_4 /test area splashesA/.
jenkins tests confirm no differences.

In local tests the module was enabled, after the combinatorics trimming, the hepTopTagPFJetsCHS completed within ~7 sec/event on beam splashes from run 144980 lumis [588,895]. 
Without the fix, the module ran up to 45 GB and killed the node at that point (I didn't run debugs in full that far, I suspect this was caused by an event with _top_parts.size() of 207, but it could've been another jet with more top_parts)

**Comment by davidlange6** [comment]
+1

**Pull request merged**
