### PR TITLE
GPUcaloCommon: fix parentheses

### PR DESCRIPTION
**Pull request by mariadalfonso**
this PR fix the warning reported in https://github.com/cms-sw/cmssw/pull/31704#issuecomment-717252465

@fwyzard @davidlange6

### CODE REVIEW

**Comment by slava77** [comment]
enable gpu

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by perrotta** [comment]
+1
- Trivial fix which adheres to the same suggestion provided by clang
- Jenkins tests pass

**Comment by qliphy** [comment]
+1

**Pull request merged**
