### PR TITLE
Fixes bug when SoA has not columns, only scalars.

### PR DESCRIPTION
**Pull request by ericcano**
#### PR description:

This PR fixes and issue in macro generation of code when an SoA contains only scalars and not column. Special cases were
introduced to handle this case gracefully.

#### PR validation:

New SoAs with no columns are added. A successful compilation is enough to validate this PR.

### CODE REVIEW

**Comment by makortel** [comment]
enable gpu

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by fwyzard** [comment]
type bugfix

**Comment by fwyzard** [comment]
LGTM

I'd like to test this on top of the Pixel changes that could make use of a scalar-only SoA.

**Comment by perrotta** [comment]
please test

**Comment by fwyzard** [comment]
`testEigenGPUNoFit_t` does not use the SoA modified by this PR.

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
`testEigenGPUNoFit_t` was already failing in the oldest IB I can still find, `CMSSW_13_3_X_2023-08-06-0000`:
```
[2023-08-15 14:10:49] fwyzard@lxplus8s05:/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02797/el8_amd64_gcc11/cms/cmssw/CMSSW_13_3_X_2023-08-06-0000/test/el8_amd64_gcc11$ cmsenv

[2023-08-15 14:11:01] fwyzard@lxplus8s05:/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02797/el8_amd64_gcc11/cms/cmssw/CMSSW_13_3_X_2023-08-06-0000/test/el8_amd64_gcc11$ ./testEigenGPUNoFit_t
TEST EIGENVALUES
TEST INVERSE 3x3
TEST INVERSE 4x4
TEST INVERSE 5x5
testEigenGPUNoFit_t: /data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/7a1027c19550f663ecdf792af6679f08/opt/cmssw/el8_amd64_gcc11/cms/cmssw/CMSSW_13_3_X_2023-08-06-0000/src/RecoTracker/PixelTrackFitting/test/test_common.h:24: bool isEqualFuzzy(C1, C2, double) [with C1 = Eigen::Matrix<double, 5, 5>; C2 = Eigen::Matrix<double, 5, 5>]: Assertion `std::abs(a(i, j) - b(i, j)) < std::min(std::abs(a(i, j)), std::abs(b(i, j))) * epsilon' failed.
Aborted (core dumped)
```

**Comment by fwyzard** [comment]
@perrotta, the test `testEigenGPUNoFit_t` is already failing in the IBs and in `CMSSW_13_3_0_pre1`.

While of course we should look into the reason and fix it, can we merge this PR (and its backport to 13.2.x) in the meantime ?

**Comment by perrotta** [comment]
+1
- The failing unit test is independent from this PR: issue tracked in https://github.com/cms-sw/cmssw/issues/42460

**Comment by perrotta** [comment]
merge

**Pull request merged**
