### PR TITLE
Use ESGetToken in BufferedBoostIOESProducer

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

Title says it all (part of #26748)

#### PR validation:

Code compiles.

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
Let me use the occasion to ask why there are plugins defined in `CondTools/Hcal/bin`
https://github.com/cms-sw/cmssw/blob/17507fb9bbd5f1db06dda9c95d52758ef2356994/CondTools/Hcal/bin/BuildFile.xml#L16-L20

Could they be moved under `plugins`? @bsunanda

**Comment by ggovi** [comment]
+1

**Comment by fabiocos** [comment]
@makortel I agree this does not sound the desired structure

**Comment by fabiocos** [comment]
+1

**Pull request merged**
