### PR TITLE
removes {using namespace} statemnets from header files

### PR DESCRIPTION
**Pull request by iahmad-khan**

### CODE REVIEW

**Comment by iahmad-khan** [comment]
please test

**Comment by mulhearn** [comment]
+1

**Comment by mmusich** [comment]
+1

**Comment by cvuosalo** [comment]
+1

For #14799 d5b94083cd393ef88d967a1398c42efbfd37e27c

Removing `using namespace` statements from header files. There should be no change in monitored quantities.

The code changes are satisfactory, and Jenkins tests against baseline CMSSW_8_1_X_2016-06-06-2300 show no significant differences, as expected.

**Pull request merged**
