### PR TITLE
New scale for Cluster Width tk maps

### PR DESCRIPTION
**Pull request by ssilvado**
Hello all,

as asked by @fioriNTU I changed the scale of Cluster Width (On and OffTrack) TkMaps.

### CODE REVIEW

**Comment by boudoul** [comment]
Wrong base... Please use a recent 10_2_x  IB. Thanks

**Comment by perrotta** [comment]
-1

**Comment by kpedro88** [comment]
-1

**Comment by fioriNTU** [comment]
@ssilvado maybe I wasn't clear enough, this small changes should go with a bigger PR (you have a much bigger task than this), for the moment we will change manually the scale in the shifter machine. So please close the PR.

**Comment by ssilvado** [comment]
@fioriNTU Ok, now I got it! I will close it now!

**Pull request closed without merging**
