### PR TITLE
Run3-alca238 Modify the output content for 2 isolated bunch AlCaReco modules of HCAL

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Modify the output content for 2 isolated bunch AlCaReco modules of HCAL. The isolated bunch AlCaReco files are rather small (# of isolated bunch events is small as well). The change will affect less than 10% increase.

#### PR validation:

Use the runTheMatrix test workflows

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Need to be back ported to 13_0_X

### CODE REVIEW

**Comment by bsunanda** [comment]
This is a very small dataset (isolated bunch) and the expected change is ~10%

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by tvami** [comment]
Is the ALCARECO the `HcalCalIsolatedBunchFilter` ? I dont see that being part of the AlCaRECO matrix now
https://github.com/cms-sw/cmssw/blob/master/Configuration/AlCa/python/autoAlca.py

**Comment by tvami** [comment]
> @cmsbuild Please test

is the ALCARECO run for the default tests?

**Comment by tvami** [comment]
> is the ALCARECO run for the default tests?

Seems not, @bsunanda please trigger tests that do create this ALCARECO, thanks

**Comment by bsunanda** [comment]
I do not think there is a AlCaReco test for isolated bunch
________________________________

**Comment by bsunanda** [comment]
@tvami Please approve this PR.

**Comment by tvami** [comment]
> Is the ALCARECO the `HcalCalIsolatedBunchFilter` ? I dont see that being part of the AlCaRECO matrix now https://github.com/cms-sw/cmssw/blob/master/Configuration/AlCa/python/autoAlca.py

@bsunanda I didnt receive an answer to this ^

**Comment by bsunanda** [comment]
@tvami It should be. I shall make a PR to make it a part of autoAlca.py

**Comment by bsunanda** [comment]
@tvami I am testing the 2 PR's together. Once the tests are done please approve the PR's. We need them in early 2023 runs in CMSSW_13_0_X

**Comment by bsunanda** [comment]
@tvami Please check the latest test results

**Comment by tvami** [comment]
You didnt test 1002.3 and 1002.4 as I've asked in the other PR. I'll do it now

**Comment by tvami** [comment]
test parameters:
  - workflows = 1002.3,1002.4
  - pull_request  = https://github.com/cms-sw/cmssw/pull/40970

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
Now we are testing the changes...

**Comment by tvami** [comment]
+alca
 * now the `HcalCalIsolatedBunchFilter` is produced in the test

**Comment by perrotta** [comment]
+1

**Pull request merged**
