### PR TITLE
re-enable photons for run3 in nanoAOD

### PR DESCRIPTION
**Pull request by gouskos**
#### PR description:

re-enable photon IDs for run3

#### PR validation:
cmsDriver.py test_nanoTuples_mcRun3 -n 10 --mc --eventcontent NANOAODSIM --datatier NANOAODSIM --conditions auto:phase1_2022_realistic --step NANO --nThreads 1 --era Run3 --filein /store/relval/CMSSW_12_3_0_pre6/RelValQQToHToTauTau_14TeV/MINIAODSIM/123X_mcRun3_2021_realistic_v11-v1/10000/9109f7be-2e01-42a2-926d-5f1dd4ade6dc.root --customise_commands "process.options.wantSummary = cms.untracked.bool(True)"

### CODE REVIEW

**Comment by gouskos** [comment]
please test

**Comment by swagata87** [comment]
Hello @gouskos 
thanks for this, so if I understand correctly the Run2 **photon** ID bits will be available for Run3 nano, right?
That is indeed the correct and very practical approach. Can you please confirm that the Run2 **electron** ID bits will also be stored in Run3 nano? We have checked before that Run2 electron, photon IDs (the so called Fall17 V2 IDs) works quite well in Run3 samples. So, while EGM POG is working for dedicated Run3 IDs, the Run2 IDs need to be present in Run3 nanos, so that the early analysis have something to work with. Thanks again for taking care of this.

**Comment by mariadalfonso** [comment]
This PR gets problems when running mini/nano
 -s RAW2DIGI,L1Reco,RECO,RECOSIM,PAT,NANO,VALIDATION:@standardValidation+@miniAODValidation,DQM:@standardDQM+@ExtraHLT+@miniAODDQM+@nanoAODDQM
as in wf 11634.914

while is ok -s NANO as in wf 11834.21

@swagata87 
this function calling the the tools.vid_id_tools is a but hill defined, can you help ?
https://github.com/cms-sw/cmssw/blob/b54d06d5447f6bb55d1da6c42d3a413f526150a0/PhysicsTools/NanoAOD/python/nano_cff.py#L220

**Comment by swagata87** [comment]
It looks like the issues are triggered by `nanoDQMMC`. 
Not sure how to fix it though.

**Comment by Sam-Harper** [comment]
So as I understand it, there is an issue in producing nanoAOD and miniAOD at the same time.

A value map is keyed to an object in specific collection, ie its indexed by productID and index in that collection.  Therefore if you remake the collection, its a new collection with a new product ID and thus it doesnt work.  I did try a while ago to record the "parent" photon/electron but for various reasons, it fell through. 

The issue is that nano is going off slimmedPhotons and reading the IDs for those. But slimed photons also embeds the ids as part of miniAOD. Thus the egmPhotonIDs needs to be produced (and its value maps only valid for) the input of slimmedPhotons, not the slimed photons itself. 

If nano just read from the miniAOD object which has all the info already there, it would be fine. 

I dont understand how this ever worked in the past? Did we do this exact workflow in run2?

Various solutions present themselves

1) modify PhoVIDNestedWPBitmapProducer to also take the original collection and then associate by SC between them. This means the value maps can be read with correct product
2) modify PhoVIDNestedWPBitmapProducer to read the ID from the photon itself, that would also solve it
3) redo the IDs but with slimmmedPhotons as a source (so run it twice, not a good idea, so probably dont do this one)
4) figure out how on earth this worked in the past, I'm still confused

**Comment by mariadalfonso** [comment]
@Sam-Harper
thanks for looking.

For Run2 we used this function
https://github.com/cms-sw/cmssw/blob/CMSSW_10_6_X/PhysicsTools/NanoAOD/python/nano_cff.py#L278
and we ruined nanoAOD standalone

For Run3 we are running MINI-NANO in the same steps (these are the wf that fail now) and for this we had to replace the Sequences with Tasks.

**Comment by Sam-Harper** [comment]
So MINI-NANO is a new workflow which so far has not been run.  Okay this makes sense because I just couldnt see how it ever worked in the past.

I also dont understand why on earth the photon (and electron) ids were ever disabled to begin with, its a completely baffling decision. Had this decision not being taken, this could have been caught earlier and fixed in more relaxed manor. 

I've already implimented the changes to PhoVIDNestedWPBitmapProducer  but we now hit the problem of the UserData producer having issues which can be fixed in a similar way but I'm wondering if there is a better solution.

**Comment by mariadalfonso** [comment]
> I also dont understand why on earth the photon (and electron) ids were ever disabled to begin with, its a completely baffling decision. Had this decision not being taken, this could have been caught earlier and fixed in more relaxed manor.

The Run3 photons will not be in miniAOD and we will have to have in nanoAOD.
So this functionality of re-running ID should be available

> I've already implimented the changes to PhoVIDNestedWPBitmapProducer but we now hit the problem of the UserData producer having issues which can be fixed in a similar way but I'm wondering if there is a better solution.

We are looking for a solution for the time being, not necessarily elegant.

**Pull request merged**
