### PR TITLE
[GENERATORS] Various fixes/improvements for unit test

### PR DESCRIPTION
**Pull request by smuzaffar**
- Convert unit tests to use `<test ...command="cmd"/>` instead of using `FW unit tests driver`
- Make sure that test can run from its dedicated test directory.

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@cms-sw/generators-l2  can you please review this? This is just a technical update

**Comment by perrotta** [comment]
+1
- Just to relieve the reviewers from the review of such technical and all-identical PRs, let have them merged even bypassing the missing signatures

**Comment by menglu21** [comment]
+1 (though merged)

**Pull request merged**
