### PR TITLE
CTPPS: Diamonds track reconstruction

### PR DESCRIPTION
**Pull request by forthommel**
This PR introduce the track fitting procedure for the CTPPS diamond detector.
* new data format (`CTPPSDiamondLocalTrack`) to store the spatial and temporal track information
* new `EDProducer` with an associated track fitting algorithm (fit procedure: see slide 3 [here](https://indico.cern.ch/event/589581/contributions/2377694/)) using the `CTPPSDiamondRecHit` collection introduced in #17317/#17535 as an input

Built on top of #17535 (diff: https://github.com/cms-sw/cmssw/compare/8083280809638dff8dbde5faf4f1ec63bade0f6f...CTPPS:ctpps_diamond_ltreco)

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by forthommel** [comment]
@slava77 Is a rebase needed (as the commits from #17535) appear here...

**Comment by slava77** [comment]
On 2/18/17 4:13 AM, Laurent Forthomme wrote:
> @slava77 <https://github.com/slava77> Is a rebase needed (as the commits
> from #17535 <https://github.com/cms-sw/cmssw/pull/17535>) appear here...

I'm not sure if a rebase is possible.
If this PR needs code from #17535, we can have either of the following
- wait for #17535 to be merged and rebase from that
- supersede #17535

**Comment by forthommel** [comment]
The first solution might be the safest given the current schedule. Would a code review with https://github.com/cms-sw/cmssw/compare/8083280809638dff8dbde5faf4f1ec63bade0f6f...CTPPS:ctpps_diamond_ltreco be feasible, before we wait for the merging of #17535 and rebase from there?

**Comment by slava77** [comment]
On 2/18/17 5:51 AM, Laurent Forthomme wrote:
> The first solution might be the safest given the current schedule. Would
> a code review with 8083280...CTPPS:ctpps_diamond_ltreco
> <https://github.com/cms-sw/cmssw/compare/8083280809638dff8dbde5faf4f1ec63bade0f6f...CTPPS:ctpps_diamond_ltreco>
> be feasible, before we wait for the merging of #17535
> <https://github.com/cms-sw/cmssw/pull/17535> and rebase from there?

If the plan to build pre5 around Monday stays, the option to wait and
rebase will not work.

**Comment by forthommel** [comment]
Indeed. Is there a chance for this one to be reviewed, approved, and integrated in time for pre5?

**Comment by ianna** [comment]
+1

**Comment by forthommel** [comment]
Since both this PR and #17535 are somehow at the very same point, the code review of this one might determine whether it can supersede the other. What do you think?

**Comment by slava77** [comment]
On 2/19/17 5:03 AM, Laurent Forthomme wrote:
> Since both this PR and #17535
> <https://github.com/cms-sw/cmssw/pull/17535> are somehow at the very
> same point, the code review of this one might determine whether it can
> supersede the other. What do you think?

Please recall that the main goal of 90X release is to be able to make
2017 MC samples
important for further algorithm developments (training/calibrations etc)
in the 91X startup release.
The CTPPS is outside of this scope and the primary need for this PR to
be early is to be able to make a backport of new features to 80X.

**Comment by forthommel** [comment]
Some extra work on the track reconstruction part seems to be needed. Hence, closing this PR to leave only #17535 up to the rechits stage. We will reopen it (or create a new one) when the bug fix is ready to be released.

**Pull request closed without merging**
