### PR TITLE
PPS: use Run3 era in online DQM, backport to 12_0

### PR DESCRIPTION
**Pull request by jan-kaspar**
#### PR description:

The era modifier used in online DQM config of PPS is updated to `Run3`. This is a bug fix - currently `Run2_2018` is used.

#### PR validation:

The following command
`cmsRun DQM/Integration/python/clients/ctpps_dqm_sourceclient-live_cfg.py`
was executed on LXPLUS. The process runs without errors (but obviously it cannot find input data).

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

This is a backport of #35550. The backport is needed to fix ongoing DQM tests at P5.

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by tvami** [comment]
test parameters:
  - pull_request  = https://github.com/cms-sw/cmssw/pull/35561

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
Is the input file really this
https://github.com/cms-sw/cmssw/blob/master/DQM/Integration/python/clients/ctpps_dqm_sourceclient-live_cfg.py#L28
?

Can we change that to something more recent, like
`/store/data/Commissioning2021/Cosmics/RAW/v1/000/344/518/00000/00130ffc-3e69-4106-8151-c69dd735ee2e.root`
?

**Comment by jfernan2** [comment]
No, in the UnitTest the input sample is :
https://github.com/cms-sw/cmssw/blob/master/DQM/Integration/python/config/unittestinputsource_cfi.py#L35-L44
which we can change if that is the source of the problem.

https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-904e9b/19443/unitTests/src/DQM/Integration/test/TestDQMOnlineClient-ctpps_dqm_sourceclient/testing.log

**Comment by tvami** [comment]
This needs to be merged together with https://github.com/cms-sw/cmssw/pull/35561

**Comment by jfernan2** [comment]
We are testing the last versions of these PRs at P5, results coming shortly

**Pull request merged**
