### PR TITLE
[DQM] Fixed filling for TDCfatal in DT Online DQM

### PR DESCRIPTION
**Pull request by jfernan2**
#### PR description:

Fixed a bug which made that Overflows and hit rejections/error were wrongly considered as TDCFatal too

#### PR validation:

Tested with private Online DQM client and run 351168

Checked that runTheMatrix.py -l limited works too

Backport to follow shortly.

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
please test

**Comment by emanueleusai** [comment]
- 77MiB extra histo memory caused by #37995

**Comment by emanueleusai** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
