### PR TITLE
split 25 and 50 ns HLT menu

### PR DESCRIPTION
**Pull request by franzoni**
split 25 and 50 ns HLT menu in relval; both point to GRun, for the moment

### CODE REVIEW

**Comment by fwyzard** [comment]
+1
if Jenkins agrees, as discussed with Giovanni

**Comment by franzoni** [comment]
+1

all "--what pileup" workflows run
No failures in addition to those (HIN + fastsim) already present in the IB report of the same vanilla release https://cms-sw.github.io/relvalLogDetail.html#slc6_amd64_gcc491;CMSSW_7_4_X_2015-03-15-1400

**Comment by franzoni** [comment]
@cmsbuild 
please test

**Comment by franzoni** [comment]
@cmsbuild please test

**Comment by franzoni** [comment]
(thanks @ktf for advice :-P )

**Comment by davidlange6** [comment]
+1

**Pull request merged**
