### PR TITLE
Updates on summary plot of GEM onlineDQM

### PR DESCRIPTION
**Pull request by quark2**
#### PR description:
The criteria of the summary plot of GEM onlineDQM have been changed: From now on it goes red(error)/yellow(warning) which is determined by the ratio of error/warning status on each chamber.

Also binning of some plots have been changed to watch some recHit distribution more carefully.

It will be good for this update to be implemented to the current central DQM, so a backport to 12_0_X will be made soon.

#### PR validation:
Test are done and one can check again by `runTheMatrix` workflows

@jshlee @watson-ij

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
@quark2  I don't understand why the backport of this PR did not produce changes in Offline DQM workflows, 

https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_0_X_2021-11-02-1100+271e3e/46605/dqm-histo-comparison-summary.html

but this master version did produce them:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_2_X_2021-11-02-1100+8402e0/46616/dqm-histo-comparison-summary.html

Any idea? Aren't the PRs identical? From an eye inspection they do look the same

**Comment by quark2** [comment]
Hi @jfernan2, 

Yes, these PRs are identical. But in CMSSW_12_2_X the plots under some changes (change of the bins, see [here](https://github.com/cms-sw/cmssw/pull/35954/files/d4e324c7f9b20c4b44863f43ab138b531fa6e318#r741206321)) are used in the workflow while they are not in CMSSW_12_0_X.

Best regards, 
Byeonghak Ko

**Comment by jfernan2** [comment]
I do not understand @quark2 sorry
Where and when you set to use GEMRecHit source in Offline? I missed that part
Thanks

**Comment by quark2** [comment]
Ahh, some plots on GEM onlineDQM is also used in GEM offlineDQM (and GEM validation). See [this](https://github.com/cms-sw/cmssw/blob/master/DQMOffline/Muon/python/gem_dqm_offline_source_cff.py#L13) one in the master branch, and compare it with [this](https://github.com/cms-sw/cmssw/blob/CMSSW_12_0_X/DQMOffline/Muon/python/gem_dqm_offline_source_cff.py) which is the same file but in CMSSW_12_0_X.

Best regards, 
Byeonghak Ko

**Comment by jfernan2** [comment]
OK, I see, thanks for the explanation

**Comment by jfernan2** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
