### PR TITLE
 multithreading fix for 74x: CSC modules

### PR DESCRIPTION
**Pull request by fwyzard**
Conversion of CLHEP matrices to ROOT::SMatrix in the CSC least-squares fit code of all 5 CSC segment building algorithms, for multithreading compatiiblity.

### CODE REVIEW

**Comment by fwyzard** [comment]
backport #7864 to 74x

**Comment by fwyzard** [comment]
tracked at #11317

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by fwyzard** [comment]
rebased to merge on top of both CMSSW_7_4_X and CMSSW_7_4_12_patch4

**Comment by fwyzard** [comment]
please test

**Comment by slava77** [comment]
@fwyzard 
you omitted RecoLocalMuon/CSCSegment/test/run_on_raw_75x.py and RecoLocalMuon/CSCSegment/test/run_on_simdigi_75x.py from the #7864
Was it intentional?

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/11393	5751c57
- the same technical essential changes are applied in this PR as in https://github.com/cms-sw/cmssw/pull/7864	 b779fc5 (integrated back in 750pre1)
    - two test files are omitted in the backport https://github.com/cms-sw/cmssw/pull/11393#issuecomment-143271024. It should be OK.
- jenkins tests pass and comparisons with baseline show no differences as expected

**Comment by fwyzard** [comment]
Yes, since this PR is for 74x I assumed we did non want them.

.A

**Comment by davidlange6** [comment]
+1

**Pull request merged**
