### PR TITLE
Properly handle a polymorphic exception in DTCCablingMapProducer

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

Fixes a gcc 8 compiler warning.

#### PR validation:

Compiled under gcc7.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by kpedro88** [comment]
+upgrade

**Comment by fabiocos** [comment]
@tocheng this looks a straightforward technical fix (thanks @Dr15Jones ) I will move forward with it, please sign it for future reference unless you have objections

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Pull request merged**
