### PR TITLE
CTPPS: updated DQM for 2018 data taking [10_1_X]

### PR DESCRIPTION
**Pull request by forthommel**
Backport of #23577 

This PR updates the DQM:
* Includes new CTPPS Roman Pot (RP) state (with CTPPSRecord collection) in function of LS. Each state corresponds to a combination of (HV & LV & position for physics).
* States are 0 (not used), 1 (bad), 2 (warning) and 3 (ok).

A test python is available at DQM/CTPPS/test/timing_dqm_test_cfg.py

@dfigueiredo @nminafra @fabferro

### CODE REVIEW

**Comment by forthommel** [comment]
Hello @andrius-k !
Do you think this timeout might have been caused by this PR, or is it completely unrelated?

**Comment by jfernan2** [comment]
please test
Unrelated

**Comment by andrius-k** [comment]
+1
@forthommel Tests fail due to timeout from time to time. As we can see, when we ran tests the second time it worked fine, so this PR seems to be fine.

**Comment by fabiocos** [comment]
@forthommel @jfernan2 @andrius-k as DQM is using 10_2_X could we just close this PR?

**Comment by forthommel** [comment]
Indeed, thanks for the head-up @fabiocos !

**Pull request closed without merging**
