### PR TITLE
Input files for offline TkCommissioner tool, 80X

### PR DESCRIPTION
**Pull request by vdutta**
Production of input root files for the offline TkCommissioner tool. These files contain the information from the tracker maps produced for offline SiStrip DQM indexed by detId for a given run and can be used to get a better understanding of SiStrip DQM issues at the module level.

### CODE REVIEW

**Comment by dmitrijus** [comment]
+1
few comments in https://github.com/cms-sw/cmssw/pull/14232

**Comment by fioriNTU** [comment]
@vdutta please ping to have it merged

**Comment by dmitrijus** [comment]
+1
thanks!

**Comment by davidlange6** [comment]
+1

**Pull request merged**
