### PR TITLE
[12_4_X] WFs to test era Run3_2022_rereco

### PR DESCRIPTION
**Pull request by sunilUIET**
This PR is to add WFs to run with era Run3_2022_rereco introduced by #41581 which is an urgent PR to validate the new HB thresholds. 
This PR has to be validated with #41581.

### CODE REVIEW

**Comment by sunilUIET** [comment]
test parameters:

 relvals_opt= -w upgrade 
 workflows = 14234.0

**Comment by sunilUIET** [comment]
@cmsbuild please test with https://github.com/cms-sw/cmssw/pull/41581

**Comment by sunilUIET** [comment]
test parameters:

relvals_opt= -w upgrade
workflows = 14234.0

**Comment by sunilUIET** [comment]
@cmsbuild please test with https://github.com/cms-sw/cmssw/pull/41581

**Comment by sunilUIET** [comment]
test parameters:

relvals_opt= -w upgrade
workflows = 14034.0

**Comment by sunilUIET** [comment]
test parameters:

relvals_opt= -w upgrade
workflows = 14034.0

**Comment by sunilUIET** [comment]
@cmsbuild please test with https://github.com/cms-sw/cmssw/pull/41581

**Comment by abdoulline** [comment]
Just a small comment: 
GT  auto:phase1_2022_realistic may be suboptimal, as it has very small HCAL pedestals... 

I'd  think the one with some reasonable HCAL pedestals 
'phase1_2022_realistic_postEE' : '124X_mcRun3_2022_realistic_postEE_v1' 
would be better...

**Comment by sunilUIET** [comment]
@cmsbuild please test with https://github.com/cms-sw/cmssw/pull/41581

**Comment by sunilUIET** [comment]
+pdmv

**Comment by AdrianoDee** [comment]
+upgrade
Only note: I'd squash the commits (but it's superseded by the urgency).

**Comment by rappoccio** [comment]
+1

**Comment by srimanob** [comment]
Hi @sunilUIET 
Sorry, I am late on comment. This PR introduce a mismatch number of workflow between 12_4 and master, and this should be fixed.

https://github.com/cms-sw/cmssw/blob/CMSSW_12_4_X/Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py#L29-L32

https://github.com/cms-sw/cmssw/blob/master/Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py#L29-L32

**Comment by sunilUIET** [comment]
Hi @srimanob , This PR is intended only for 12_4_X. Do we need propagate changes to master as well?

**Comment by srimanob** [comment]
Hi @sunilUIET 
Not a change, but a PR to make the workflow ID the same across the release. What you need to work on is the following line:
https://github.com/cms-sw/cmssw/blob/master/Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py#L66-L69
But PR in master will be different than 12_4 because if they are in order (by date they are implemented), it will be
2023FS (master, not in 12_4)
2023FSPU (master, not in 12_4)
2022ReReco (12_4, not in master)
2022ReRecoPU (12_4, not in master)
This is to make sure that in future, for any reasons, if we want to bring 2022ReReco to master, we will not screw up the workflow ID.

**Comment by sunilUIET** [comment]
@tvami As I understood Run3_2022_rereco is included in 12_4_X only so is this PR.

**Comment by srimanob** [comment]
Here are PRs, that make the workflow ID to be unique,
+ (12_4) https://github.com/cms-sw/cmssw/pull/41688 
+ (13_2) https://github.com/cms-sw/cmssw/pull/41689
+ (13_1) to come

I would like to make sure that we always keep unique IDs for upgrade workflows across the release.

**Pull request merged**
