### PR TITLE
Pixel Nose Description from Adrian

### PR DESCRIPTION
**Pull request by ianna**
The following changes are introduced in the new xml files under Run2 directories:
- Run2/cms.xml: introducing new constants, changing TrackBeamZ2:

```
diff Geometry/CMSCommonData/data/cms.xml Geometry/CMSCommonData/data/Run2/.
17c17
<       <Constant name="TrackBeamZ2" value="2.935*m"/>

---
>       <Constant name="TrackBeamZ2" value="2.932*m"/>
19a20
>       <Constant name="TrackBeamR3" value="7.7633*cm"/>
23a25,36
>       <!--Pixel patch pannel sandwiched layers: total thickness-->
>       <Constant name="PIXSandwichLayerThick" value="[PIXSandwichLayer1Thick]+[PIXSandwichLayer2Thick]+[PIXSandwichLayer3Thick]+[PIXSandwichLayer4Thick]"/>
>       <Constant name="PIXSandwichLayer1Thick" value="0.2*mm"/>
>       <Constant name="PIXSandwichLayer2Thick" value="11.0*mm"/>
>       <Constant name="PIXSandwichLayer3Thick" value="0.5*mm"/>
>       <Constant name="PIXSandwichLayer4Thick" value="0.3*mm"/>
>       <!--Pixel patch pannel sandwiched layers-->
>       <Constant name="PIXNoseRin"  value="215*mm"/>
>       <Constant name="PIXNoseRout" value="[PIXNoseRin]+[PIXSandwichLayerThick]"/>
>       <Constant name="PIXSandwichLayerRout2" value="1063*mm"/>
>       <!--Pixel nose length-->
>       <Constant name="PIXNoseLength" value="619.5*mm"/>

```
- Run2/caloBase.xml - volume CALO changes to make space for the nose: 

```
diff -wb Geometry/CMSCommonData/data/caloBase.xml Geometry/CMSCommonData/data/Run2/.
10,11c10,12
<           <ZSection z="-[cms:CalorBeamZ1]" rMin="[cms:CalorBeamR1]" rMax="[cms:CalorMuonR]"/>
<           <ZSection z="-[cms:TrackBeamZ2]" rMin="[cms:TrackBeamR2]" rMax="[cms:CalorMuonR]"/>

---
>       <ZSection z="-[cms:TrackBeamZ2]-[cms:PIXNoseLength]" rMin="[cms:TrackBeamR3]" rMax="[cms:CalorMuonR]"/>
>       <ZSection z="-[cms:TrackBeamZ2]-[cms:PIXNoseLength]" rMin="[cms:PIXNoseRout]" rMax="[cms:CalorMuonR]"/>
>       <ZSection z="-[cms:TrackBeamZ2]" rMin="[cms:PIXNoseRout]" rMax="[cms:CalorMuonR]"/>
14,15c15,17
<           <ZSection z="[cms:TrackBeamZ2]" rMin="[cms:TrackBeamR2]" rMax="[cms:CalorMuonR]"/>
<           <ZSection z="[cms:CalorBeamZ1]" rMin="[cms:CalorBeamR1]" rMax="[cms:CalorMuonR]"/>

---
>       <ZSection z="[cms:TrackBeamZ2]" rMin="[cms:PIXNoseRout]" rMax="[cms:CalorMuonR]"/>
>       <ZSection z="[cms:TrackBeamZ2]+[cms:PIXNoseLength]" rMin="[cms:PIXNoseRout]" rMax="[cms:CalorMuonR]"/>
>       <ZSection z="[cms:TrackBeamZ2]+[cms:PIXNoseLength]" rMin="[cms:TrackBeamR3]" rMax="[cms:CalorMuonR]"/>
```
- Run2/materials.xml - new materials used in the nose description plus correct T_Kapton definition:

```
diff Geometry/CMSCommonData/data/materials.xml  Geometry/CMSCommonData/data/Run2/.
3932,3933c3932,3933
<   <CompositeMaterial name="T_Kapton" density="1.4*g/cm3" symbol=" " method="mixture by weight">
<    <MaterialFraction fraction="0.59985105">

---
>   <CompositeMaterial name="T_Kapton" density="1.42*g/cm3" symbol=" " method="mixture by weight">
>    <MaterialFraction fraction="0.691099">
3936c3936
<    <MaterialFraction fraction="0.080541353">

---
>    <MaterialFraction fraction="0.026178">
3939c3939,3942
<    <MaterialFraction fraction="0.31960759">

---
>    <MaterialFraction fraction="0.073298">
>     <rMaterial name="materials:Nitrogen"/>
>    </MaterialFraction>
>    <MaterialFraction fraction="0.209425">
4571a4575,4596
>   <CompositeMaterial name="T_G10" density="1.9*g/cm3" symbol=" " method="mixture by weight">
>     <MaterialFraction fraction="0.13232243">
>       <rMaterial name="materials:Carbon"/>
>     </MaterialFraction>
>     <MaterialFraction fraction="0.032572448">
>       <rMaterial name="materials:Hydrogen"/>
>     </MaterialFraction>
>     <MaterialFraction fraction="0.48316123">
>       <rMaterial name="materials:Oxygen"/>
>     </MaterialFraction>
>     <MaterialFraction fraction="0.35194389">
>       <rMaterial name="materials:Silicon"/>
>     </MaterialFraction>
>   </CompositeMaterial>
>   <CompositeMaterial name="Tpatch_PN" density="2.35*g/cm3" symbol=" " method="mixture by weight">
>     <MaterialFraction fraction="0.47">
>       <rMaterial name="materials:Inconel600"/>
>     </MaterialFraction>
>     <MaterialFraction fraction="0.53">
>       <rMaterial name="materials:T_Kapton"/>
>     </MaterialFraction>
>   </CompositeMaterial>
```
- Run2/eregalgo.xml - both ECAL and its child EREG volumes change according to the CALO mother volume 

```
diff Geometry/EcalCommonData/data/Run2/eregalgo.xml Geometry/EcalCommonData/data/eregalgo.xml
9,13c9,13
<           <ZSection z="-[eecon:EEFarZC]"  rMin="[cms:PIXNoseRout]" rMax="[eecon:EErNeck]"/>
<           <ZSection z="-[eecon:EEzNeckC]" rMin="[cms:PIXNoseRout]" rMax="[eecon:EErNeck]"/>
<           <ZSection z="-[eecon:EEzNeckC]" rMin="[cms:PIXNoseRout]" rMax="[eecon:EBRMax]"/>
<           <ZSection z="-[eecon:EEzFront]" rMin="[cms:PIXNoseRout]" rMax="[eecon:EBRMax]"/>
<           <ZSection z="-([escon:PRESH_Z_OFFSET] - [escon:PRESH_Z_TOTAL]/2. + [eecon:EEzMagF])" rMin="[cms:PIXNoseRout]" rMax="[eecon:EBRMax]"/>

---
>           <ZSection z="-[eecon:EEFarZC]"  rMin="[eecon:EEIRECR]" rMax="[eecon:EErNeck]"/>
>           <ZSection z="-[eecon:EEzNeckC]" rMin="[eecon:EEIRECR]" rMax="[eecon:EErNeck]"/>
>           <ZSection z="-[eecon:EEzNeckC]" rMin="[eecon:EEIRECR]" rMax="[eecon:EBRMax]"/>
>           <ZSection z="-[eecon:EEzFront]" rMin="[eecon:EEIRECR]" rMax="[eecon:EBRMax]"/>
>           <ZSection z="-([escon:PRESH_Z_OFFSET] - [escon:PRESH_Z_TOTAL]/2. + [eecon:EEzMagF])" rMin="[eecon:EEIRECR]" rMax="[eecon:EBRMax]"/>
16,20c16,20
<           <ZSection z="  [escon:PRESH_Z_OFFSET] - [escon:PRESH_Z_TOTAL]/2. + [eecon:EEzMagF]"  rMin="[cms:PIXNoseRout]" rMax="[eecon:EBRMax]"/>
<           <ZSection z=" [eecon:EEzFront]" rMin="[cms:PIXNoseRout]" rMax="[eecon:EBRMax]"/>
<           <ZSection z=" [eecon:EEzNeckC]" rMin="[cms:PIXNoseRout]" rMax="[eecon:EBRMax]"/>
<           <ZSection z=" [eecon:EEzNeckC]" rMin="[cms:PIXNoseRout]" rMax="[eecon:EErNeck]"/>
<           <ZSection z=" [eecon:EEFarZC]"  rMin="[cms:PIXNoseRout]" rMax="[eecon:EErNeck]"/>

---
>           <ZSection z="  [escon:PRESH_Z_OFFSET] - [escon:PRESH_Z_TOTAL]/2. + [eecon:EEzMagF]"  rMin="[eecon:EEIRECR]" rMax="[eecon:EBRMax]"/>
>           <ZSection z=" [eecon:EEzFront]" rMin="[eecon:EEIRECR]" rMax="[eecon:EBRMax]"/>
>           <ZSection z=" [eecon:EEzNeckC]" rMin="[eecon:EEIRECR]" rMax="[eecon:EBRMax]"/>
>           <ZSection z=" [eecon:EEzNeckC]" rMin="[eecon:EEIRECR]" rMax="[eecon:EErNeck]"/>
>           <ZSection z=" [eecon:EEFarZC]"  rMin="[eecon:EEIRECR]" rMax="[eecon:EErNeck]"/>
23,32c23,32
<           <ZSection z="[escon:PRESH_Z_OFFSET] - [escon:PRESH_Z_TOTAL]/2." rMin="[cms:PIXNoseRout]" rMax="[escon:PRESH_RMAX_FRONT]"/>
<           <ZSection z="[escon:PRESH_Z_OFFSET] + [escon:PRESH_MID_Z]"      rMin="[cms:PIXNoseRout]" rMax="[escon:PRESH_RMAX_BACK]"/>
<           <ZSection z="[escon:PRESH_Z_OFFSET] + [escon:PRESH_Z_TOTAL]/2." rMin="[cms:PIXNoseRout]" rMax="[escon:PRESH_RMAX_BACK]"/>
<           <ZSection z="[eecon:EEzFront]" rMin="[cms:PIXNoseRout]" rMax="[escon:PRESH_RMAX_BACK]"/>
<           <ZSection z="[eecon:EEzFront]" rMin="[cms:PIXNoseRout]" rMax="[eecon:EErMax1]"/>
<           <ZSection z="[eecon:EEzBack]"  rMin="[cms:PIXNoseRout]" rMax="[eecon:EErMax2]"/>
<           <ZSection z="[eecon:EEzBack]"  rMin="[cms:PIXNoseRout]" rMax="[eecon:EBRMax]"/>
<           <ZSection z="[eecon:EEzNeck]"  rMin="[cms:PIXNoseRout]" rMax="[eecon:EBRMax]"/>
<           <ZSection z="[eecon:EEzNeck]"  rMin="[cms:PIXNoseRout]" rMax="[eecon:EErNeck]"/>
<           <ZSection z="[eecon:EEFarZ]"   rMin="[cms:PIXNoseRout]" rMax="[eecon:EErNeck]"/>

---
>           <ZSection z="[escon:PRESH_Z_OFFSET] - [escon:PRESH_Z_TOTAL]/2." rMin="[eecon:EEIRECR]" rMax="[escon:PRESH_RMAX_FRONT]"/>
>           <ZSection z="[escon:PRESH_Z_OFFSET] + [escon:PRESH_MID_Z]"      rMin="[eecon:EEIRECR]" rMax="[escon:PRESH_RMAX_BACK]"/>
>           <ZSection z="[escon:PRESH_Z_OFFSET] + [escon:PRESH_Z_TOTAL]/2." rMin="[eecon:EEIRECR]" rMax="[escon:PRESH_RMAX_BACK]"/>
>           <ZSection z="[eecon:EEzFront]" rMin="[eecon:EEIRECR]" rMax="[escon:PRESH_RMAX_BACK]"/>
>           <ZSection z="[eecon:EEzFront]" rMin="[eecon:EEIRECR]" rMax="[eecon:EErMax1]"/>
>           <ZSection z="[eecon:EEzBack]"  rMin="[eecon:EEIRECR]" rMax="[eecon:EErMax2]"/>
>           <ZSection z="[eecon:EEzBack]"  rMin="[eecon:EEIRECR]" rMax="[eecon:EBRMax]"/>
>           <ZSection z="[eecon:EEzNeck]"  rMin="[eecon:EEIRECR]" rMax="[eecon:EBRMax]"/>
>           <ZSection z="[eecon:EEzNeck]"  rMin="[eecon:EEIRECR]" rMax="[eecon:EErNeck]"/>
>           <ZSection z="[eecon:EEFarZ]"   rMin="[eecon:EEIRECR]" rMax="[eecon:EErNeck]"/>
```
- Run2/trackermaterial.xml - new material added:

```
diff Geometry/TrackerCommonData/data/Run2/trackermaterial.xml Geometry/TrackerCommonData/data/trackermaterial.xml
136,143d135
<     <CompositeMaterial name="Tpatch_PN" density="2.35*g/cm3" symbol=" " method="mixture by weight">
<       <MaterialFraction fraction="0.47">
<         <rMaterial name="materials:Inconel600"/>
<       </MaterialFraction>
<       <MaterialFraction fraction="0.53">
<         <rMaterial name="materials:T_Kapton"/>
<       </MaterialFraction>
<     </CompositeMaterial>
```
-  'Geometry/TrackerCommonData/data/Run2/trackerpatchpannel.xml' and 'Geometry/TrackerCommonData/data/Run2/trackerpixelnose.xml' - actual nose description

There are no new overlaps detected with cmsShow:

screenshot 2016-09-13 16 38 41
screenshot 2016-09-13 16 39 57
screenshot 2016-09-13 11 16 46

### CODE REVIEW

**Comment by ianna** [comment]
@aperiean and @boudoul - please, check

@bsunanda - FYI

**Comment by ianna** [comment]
@davidlange6 and @civanch - which scenarios should include pixel nose? Thanks.

**Comment by ianna** [comment]
@boudoul - T_Kapton is used by Tracker. Has Tracker DPG agreed to change its description? Thanks.

**Comment by ianna** [comment]
please test

**Comment by davidlange6** [comment]
@ianna - how do we move this forward?

**Comment by boudoul** [comment]
Sorry I think you were waiting on me... +1 for the tracker DPG

**Comment by ianna** [comment]
+1

**Comment by davidlange6** [comment]
Hi @ianna - can we a) remove the materials.xml file and b) move this change into the 2017 geometry (where I assume it is still relevant) - we had agreed not to change back-in-time geometries.

**Comment by ianna** [comment]
@davidlange6 - new materials.xml file does change T_Kapton description which means back-in-time geometries will change

**Comment by civanch** [comment]
@ianna , in that case a safe solution is to rename "T_Kapton" - having different materials with the same name in different releases for me would be a potential problem.

**Comment by ianna** [comment]
@civanch - we already have a few Kapton materials defined. I can leave the one in materials.xml unchanged.

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
it is based on https://github.com/cms-sw/cmssw/pull/16050

**Comment by ianna** [comment]
+1

**Comment by ianna** [comment]
@davidlange6 - could you, please, merge it? There are a couple of other pr that need it.

**Pull request merged**
