### PR TITLE
Fix hit eff hit pattern phase I

### PR DESCRIPTION
**Pull request by rovere**
Add the fourth barrel layer and third fwd disk to the computation of the hit efficiencies from hit-patter for the phaseI case.
Also a minor bug fix.
No changes expected (except for the new efficiencies)

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
+1

For #16897 e8761b09b3584f06cd848a2f9a494dbc9bcea161

For Phase 1, fixing the hit pattern efficiency.

The code changes are satisfactory, and Jenkins tests against baseline CMSSW_9_0_X_2016-12-07-1100 show only small changes in the hit efficiencies from hit patterns, as expected (except for Jenkins test errors not related to this PR). An example of the very small changes in efficiencies is shown below from Jenkins workflow 	10024.0_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2017:

eff

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
