### PR TITLE
new fast sim wfs and update premix input

### PR DESCRIPTION
**Pull request by franzoni**
- time per event for GEN
-  assure no GEN-SIM collisions for prod-like premixing workflows
- new fullsim PU wf's; update for premixing GEN-SIM
- new fullsim PU wf's; update for premixing GEN-SIM

### CODE REVIEW

**Comment by franzoni** [comment]
+1
(forward port from 74x)

**Comment by franzoni** [comment]
please test

**Comment by franzoni** [comment]
please test

**Comment by franzoni** [comment]
upps... I swapped fields and tricked myself with tests
thanks @cmsbuild  !
This further update : https://hypernews.cern.ch/HyperNews/CMS/get/dataopsrequests/6540/1/1.html calls for further tuning, put in place.

**Comment by franzoni** [comment]
+1

**Comment by franzoni** [comment]
hello, the errors found in the bot's tests:

%MSG-e FatalSystemSignal:   DQMGenericClient:postProcessorMuonMultiTrackHLT@endJob  26-Mar-2015 18:59:03 CET PostEndRun
A fatal system signal has occurred: segmentation violation
%MSG

I can't imagine they're related to the changes of this PR.
Will trigger tests again, hoping that things got fixed in the meantime.

NOTE: this PR also deploys the fast sim workflows with the new digi scheme which we'd like to see running and could be deployed for the first time here + 740_pre9

**Comment by franzoni** [comment]
please test

**Comment by davidlange6** [comment]
@franzoni - could you rebase this PR? It does not merge now

**Comment by franzoni** [comment]
hello @davidlange6,
all the relevant commits have entered 75x trough other PR's.
We can close this one.
g.

**Comment by davidlange6** [comment]
Hi @franzoni - you can just click close then. Thanks

**Comment by franzoni** [comment]
Hi @davidlange6 , I did close the request at the time of my earlier commit. And it has been showing up in status "Closed" since. Do you see it differently ? Cheers. g.

**Comment by davidlange6** [comment]
No - I just missed the mail before. Thanks!

**Pull request closed without merging**
