### PR TITLE
Fix HLT Setup case for cff (91X)

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
Fix HLT Setup case for cfg (91X)
Based on CMSSW_9_1_X_2017-05-11-2300

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
type bug-fix

**Comment by Martin-Grunewald** [comment]
backport of #18707

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
