### PR TITLE
Remove obsolete records

### PR DESCRIPTION
**Pull request by christopheralanwest**
#### PR description:

This PR removes several obsolete records:

- `L1TMuonEndcapParamsRcd` so that the obsolete class can be removed (see #30109 and #17061)
- `PGeometricDetExtraRcd` to address #31729
- `SiPixelCPEGenericErrorParmRcd`

Nearly all GTs need to have `PGeometricDetExtraRcd` removed, all Phase-1 and later GTs need to have `L1TMuonEndcapParamsRcd` removed, and `SiPixelCPEGenericErrorParmRcd` is removed from the Run 3 GTs.

The GTs used for HLT relvals are modified as well, despite being `101X` and `103X` GTs. The naming has not been updated in order to reflect the starting release of the GT.

The GT diffs are as follows:

**Run 1 design**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/110X_mcRun1_design_v2/112X_mcRun1_design_v1 

**Run 1 realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/110X_mcRun1_realistic_v2/112X_mcRun1_realistic_v1 

**Run 1 heavy ion**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/110X_mcRun1_HeavyIon_v2/112X_mcRun1_HeavyIon_v1 

**Run 1 proton-lead**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/110X_mcRun1_pA_v2/112X_mcRun1_pA_v2 

**Run 2 startup**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/110X_mcRun2_startup_v2/112X_mcRun2_startup_v1 

**Run 2 (L1 trigger stage 1)**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/110X_mcRun2_asymptotic_l1stage1_v2/112X_mcRun2_asymptotic_l1stage1_v1 

**2016 design**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/110X_mcRun2_design_v5/112X_mcRun2_design_v1 

**2016 realistic pre-VFP era**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/111X_mcRun2_asymptotic_preVFP_v1/112X_mcRun2_asymptotic_preVFP_v1 

**2016 realistic post-VFP era**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/111X_mcRun2_asymptotic_v1/112X_mcRun2_asymptotic_v1 

**2016 cosmics**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/111X_mcRun2cosmics_startup_deco_v1/112X_mcRun2cosmics_startup_deco_v1 

**Run 2 heavy ion**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/110X_mcRun2_HeavyIon_v2/112X_mcRun2_HeavyIon_v1 

**Run 2 proton-lead**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/110X_mcRun2_pA_v3/112X_mcRun2_pA_v1 

**Offline data**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_dataRun2_v4/112X_dataRun2_v5 

**Offline data (HEM failure)**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_dataRun2_HEfail_v4/112X_dataRun2_HEfail_v5 

**Offline data relval**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_dataRun2_relval_v4/112X_dataRun2_relval_v5 

**Prompt-like data**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_dataRun2_PromptLike_HI_v1/112X_dataRun2_PromptLike_HI_v2 

**Data (Frozen HLT GT)**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/101X_dataRun2_HLT_frozen_v9/101X_dataRun2_HLT_frozen_v10 

**Run 2 HLT RelVals**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/103X_dataRun2_HLT_relval_v8/103X_dataRun2_HLT_relval_v9 

**Run 2 HI HLT RelVals**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/103X_dataRun2_HLT_relval_HI_v4/103X_dataRun2_HLT_relval_HI_v5 

**Run 2 HLT for HI (not 2018 HI)**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/101X_dataRun2_HLTHI_frozen_v9/101X_dataRun2_HLTHI_frozen_v10 

**Run 3 data (express)**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/111X_dataRun3_Express_v2/111X_dataRun3_Express_v4 

**Run 3 data (prompt)**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/111X_dataRun3_Prompt_v2/111X_dataRun3_Prompt_v4 

**2017 design**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/111X_mc2017_design_v2/112X_mc2017_design_v1 

**2017 realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_mc2017_realistic_v2/112X_mc2017_realistic_v3 

**2017 realistic cosmics (tracker deco mode)**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_mc2017cosmics_realistic_deco_v2/112X_mc2017cosmics_realistic_deco_v3 

**2017 realistic cosmics (tracker peak mode)**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_mc2017cosmics_realistic_peak_v2/112X_mc2017cosmics_realistic_peak_v3 

**2018 design**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_upgrade2018_design_v2/112X_upgrade2018_design_v3 

**2018 realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_upgrade2018_realistic_v3/112X_upgrade2018_realistic_v4 

**2018 heavy ion**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_upgrade2018_realistic_HI_v4/112X_upgrade2018_realistic_HI_v5 

**2018 realistic (HEM15/16 failure)**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_upgrade2018_realistic_HEfail_v3/112X_upgrade2018_realistic_HEfail_v4 

**2018 cosmics (tracker deco mode)**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_upgrade2018cosmics_realistic_deco_v3/112X_upgrade2018cosmics_realistic_deco_v4 

**2018 cosmics (tracker peak mode)**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_upgrade2018cosmics_realistic_peak_v3/112X_upgrade2018cosmics_realistic_peak_v4 

**2021 design**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_mcRun3_2021_design_v8/112X_mcRun3_2021_design_v9 

**2021 realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_mcRun3_2021_realistic_v8/112X_mcRun3_2021_realistic_v9 

**2021 cosmics**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_mcRun3_2021cosmics_realistic_deco_v8/112X_mcRun3_2021cosmics_realistic_deco_v9 

**2021 heavy ion**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_mcRun3_2021_realistic_HI_v9/112X_mcRun3_2021_realistic_HI_v10 

**2023 realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_mcRun3_2023_realistic_v8/112X_mcRun3_2023_realistic_v9 

**2024 realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_mcRun3_2024_realistic_v8/112X_mcRun3_2024_realistic_v9 

**Phase 2 realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/112X_mcRun4_realistic_v2/112X_mcRun4_realistic_v3 

#### PR validation:

`addOnTests.py` and `runTheMatrix.py -l limited --ibeos`

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

This PR is not a backport, though the Run 3 data GTs will be backported to 111X, as that is the release series that is used for online data-taking.

### CODE REVIEW

**Comment by christopheralanwest** [comment]
please test

**Comment by christopheralanwest** [comment]
+1

- The small differences in comparison tests for workflows 23234.0 and 28234.0 are a pre-existing issue (#31644). In the case of this PR, however, the differences in workflow 28234.0 are in the `SiOuterTrackerV/Tracks/FinalResolution/d0Resolution` and `SiOuterTrackerV/Tracks/FinalResolution/PhiResolution` histograms rather than `SiOuterTrackerV/Tracks/FinalResolution/VtxZResolution`.
- This PR should be merged together with PR #31729 in order to avoid a unit test failure in GeometryTrackerGeometryBuilderTestDriver.

**Comment by silviodonato** [comment]
+1

**Comment by mrodozov** [comment]
after this PR this unit test started failing:
https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc820/CMSSW_11_2_X_2020-10-18-2300/unitTestLogs/Geometry/TrackerGeometryBuilder#/37371
@ianna maybe the unit test needs to be updated ?

**Comment by mmusich** [comment]
@mrodozov that's a known feature.
This PR https://github.com/cms-sw/cmssw/pull/31729 needs to be merged to make the failure stop....

**Pull request merged**
