### PR TITLE
RecoLocalTracker/SiPixelClusterizer/test: fix clang warnings in test classes

### PR DESCRIPTION
**Pull request by gartung**

### CODE REVIEW

**Comment by gartung** [comment]
@Dr15Jones test please

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by gartung** [comment]
Seems completely unrelated to my pull request.

**Comment by cvuosalo** [comment]
Please add `override` specifiers to these overloaded functions so any future signature changes will be caught earlier.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by gartung** [comment]
Need to fix this branch and resubmit

**Comment by gartung** [comment]
Resubmitted as https://github.com/cms-sw/cmssw/pull/17039

**Pull request closed without merging**
