### PR TITLE
Update of MTD validation: 4D vertices association with truth

### PR DESCRIPTION
**Pull request by rdelliga**
PR description:
 This PR updates the Primary4DVertexValidation class [1], in particular the matchReco2Sim function. 
Matching between reco and sim vertices is performed based on a Private code from Wolfram Erdmann, which was ported on CMSSW with some issues that the present PR aims to handle. More details are given in the presentation [2].
The cut on MVA in matchReco2Sim [3], that select for RECO-SIM vertex matching only tracks with good time information, was moved in the use of time information to define weights. 
Furthermore, a bug was fixed in the one-to-one match at lines 1766 [4], where the indices of the reco vertices dominated via wos by that simulated vertex are stored with a push back of the index of the recovertex, which not only saves the simulated event corresponding to the wosmatch (i.e. the higher contribution to the wos), but also the lower ones that comes early in the loop, and this happens because saving information about wosmatch and pushing-back the wos_dominated_recv are done at the same time.
In this new version of the code, wos_dominated_recv is correctly filled outside simevent loop, after filling information about wosmatch.

PR validation: 
The code was tested on the workflow TTbar_PU_14TeV

[1]https://github.com/cms-sw/cmssw/blob/master/Validation/MtdValidation/plugins/Primary4DVertexValidation.cc
[2]https://indico.cern.ch/event/1428838/contributions/6010350/attachments/2882474/5050701/MTD_DPG_June_DelliGatti.pdf
[3]https://github.com/cms-sw/cmssw/blob/master/Validation/MtdValidation/plugins/Primary4DVertexValidation.cc#L1744
[4]https://github.com/cms-sw/cmssw/blob/master/Validation/MtdValidation/plugins/Primary4DVertexValidation.cc#L1766

### CODE REVIEW

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
the failures seem unrelated to this PR

**Comment by fabiocos** [comment]
@cms-sw/dqm-l2 any comment?

**Comment by tjavaid** [comment]
+1

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
