### PR TITLE
pybind11 based parameter set reading tools 

### PR DESCRIPTION
**Pull request by davidlange6**
Intended to replace boost_python. Current implementation is not used in any default cmsRun workflow (use cmsRunPB11 instead) and is working in my tests for python2 at least.

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
please test

**Comment by Dr15Jones** [comment]
@davidlange6 remind me what is your integration plan? What tests do you want to be able to do with this not completed version of the transition? My understanding is we do not really need both the boost_python and pybind11 versions of ParameterSet to be available once we switch to pybind11. Therefore in the final change we do not need two different packages in the master repository.

**Comment by davidlange6** [comment]
> On Feb 8, 2019, at 4:56 PM, Chris Jones <notifications@github.com> wrote:
> 
> @davidlange6 remind me what is your integration plan? What tests do you want to be able to do with this not completed version of the transition? My understanding is we do not really need both the boost_python and pybind11 versions of ParameterSet to be available once we switch to pybind11. Therefore in the final change we do not need two different packages in the master repository.

I agree. Once we gain enough confidence, the boost_python version can go away.  That said, I don't yet see a way to make a python2 and a python3 version of things without a second package, so we might just think of this as the python3 interface that isn't fully there yet. 

As for testing, we should figure out how to scale up the set of tests that I can do by hand. I don't yet have a proposal (but should soon)

**Comment by Dr15Jones** [comment]
@davidlange6 what if you just replace the boost::python and make a pull request to the DEVEL branch? That way it IBs would keep testing the pybind11 changes?

**Comment by davidlange6** [comment]
hi @Dr15Jones - i'm not sure we want to deal with such a divergence. but its sorta all the same for me. @smuzaffar 

Your idea is to end up with big bang changeover without the two things co-existing (eg, a python2 and python3 cmsRun)? Its not obvious that all consumers of cmsRun would be ready for that any time soon (eg, there are production workflows and then there is the rest)

**Comment by Dr15Jones** [comment]
@davidlange6 are there perhaps two issues?

1. switching python binding technology to pybind11 since boost::python is not being maintained
1. switching from python 2 to python 3

Both need extensive testing. Do they have to be done at the same time? Could we first change out our use of boost::python for pybind11 and have the latter still use python2? This could be done on our master branch. Then we could possibly open a once per week IB for python3 where we test everything under python 3?

The reason I'm thinking of this approach is I do not see how creating a cmsRunPB11 will help in continuing testing since all of our present tests run via cmsRun. 

How were you envisioning testing the change?

**Comment by davidlange6** [comment]
hi @Dr15Jones 

There is one more wrinkle to consider - to have a python2 and python3 version of the bindings, I need a separate library (just different by the python linked to). In practice this means a separate package (afaik we cannot build two libraries that can be linked against from a single package). 

A potential evolution is 
Step 1 FWCore/PythonParameterSet (boost) + FWCore/Pybind11ParameterSet (pybind11, python2)
Step2 FWCore/PythonParameterSet (pybind11, python2) + FWCore/Pybind11ParameterSet (pybind11, python3)
Step 3 FWCore/PythonParameterSet (pybind11, python3) 

where the default cmsRun is based on whatever is in FWCore/PythonParameterSet

[I should probably pick a different package name if we were to go this way...]

In any case, IB testing would happen in devel until a switchover point is reached (eg, via calling a different cmsRun in runTheMatrix). However, we don't typically make pre-releases from devel, so once things get to a relval check, code should be in mainstream. 

So I don't know how to avoid having a second package around for some period of time (if that is the basis of your concern)

**Comment by Dr15Jones** [comment]
What I'd like to see is maximizing the testing with minimum changes to anything outside of the 'framework'. So to me, I'd think of a variant of 2

FWCore/PythonParameterSet (pybind11, python2) + FWCore/Pybind11ParameterSet (pybind11, python3)

but with cmsRun in _DEVEL using Pybind11ParameterSet and python 3. Or, even better a while new _PYTHON3 release where all of our python is tested using python3.

In that way, ALL tests presently using cmsRun would be tested with python 3 or the python 2 version of pybin11.

**Comment by davidlange6** [comment]
> On Feb 13, 2019, at 9:43 PM, Chris Jones <notifications@github.com> wrote:
> 
> What I'd like to see is maximizing the testing with minimum changes to anything outside of the 'framework'. So to me, I'd think of a variant of 2
> 
> FWCore/PythonParameterSet (pybind11, python2) + FWCore/Pybind11ParameterSet (pybind11, python3)
> 
> but with cmsRun in _DEVEL using Pybind11ParameterSet and python 3. Or, even better a while new _PYTHON3 release where all of our python is tested using python3.
> 
> In that way, ALL tests presently using cmsRun would be tested with python 3 or the python 2 version of pybin11.
> 

I was thinking of these as steps in the process not as variants.. I'm not quite ready for step 2 yet (much closer than yesterday I think). - eg, unit tests with python3 will pass once PRs are merged in (and one more is made).

So I'd propose we do the following 

1) I rename the new package to something like PythonDevParameterSet so that its content can evolve as the development version without naming confusions
2) We merge that into the IB with an alternative cmsRun  binary defined
3) We change the DEVEL IB to use that cmsRun
4) Iterate until that works (it might ootb)
5) Move to step 2 - removing boost_python, make the default PythonParameterSet package use pybind11 and python2 and the devel package provide python3 
6) The DEVEL IB continues to test the cmsRun with the devel python parameter set package (but now with python3, assuming its not totally broken..)
7) Iterate until that works 
8) swap the default PythonParameterSet package to use python3 and keep around the Dev as python2 to give users a migration platform for some period of time.
9) figure out how to drop python2 from cmssw

Steps 7 and 9 being the most uncertain time wise. But yes, no one should have to change anything outside of the fwk aside from having python3 compatible python. (we may or may have a small set of changes left to go at this point) - That may even be true of the framework code outside of the *ParameterSet packages and cmsRun.cpp.

**Comment by Dr15Jones** [comment]
>2) We merge that into the IB with an alternative cmsRun binary defined 

By this do you mean we would have a new executable, e.g `cmsRunPB11`

>3) We change the DEVEL IB to use that cmsRun 

Do you mean we change all references to cmsRun in DEVEL IB to `cmsRunPB11` or do you mean we change `cmsRun` to use the pybind11 code? I'm all for the latter but against the former.

**Comment by davidlange6** [comment]
> On Feb 14, 2019, at 3:41 PM, Chris Jones <notifications@github.com> wrote:
> 
> 	• We merge that into the IB with an alternative cmsRun binary defined
> By this do you mean we would have a new executable, e.g cmsRunPB11

it would make the development easier... yes. I of course can just apply a local patch if you prefer. 

> 
> 	• We change the DEVEL IB to use that cmsRun
> Do you mean we change all references to cmsRun in DEVEL IB to cmsRunPB11 or do you mean we change cmsRun to use the pybind11 code? I'm all for the latter but against the former.

i guess I had thought we had a switch to use a different cmsRun at the command line of runTheMatrix - but we don't.. The latter means a small PR of a few lines.

ok, so I can adjust to remove the new cmsRun and rename the package to something more appropriate and then work on a separate patch for the DEVEL..

**Comment by Dr15Jones** [comment]
@davidlange6 I am fine with having a new cmsRunPB11 executable. My concern is, in order to do full testing in _DEVEL I would want every unit tests/RelVal to run your new code. In order to do that, I think it would be best in _DEVEL to just change what cmsRun uses for its python binding (from boost_python to PB11). 

In order to be very clear, you could also create a cmsRunBoostPy which explicitly uses boost python.  Then in the regular IBs, cmsRun is identical to cmsRunBoostPy while in _DEVEL cmsRun is identical to cmsRunPB11.

**Comment by davidlange6** [comment]
Ok -i'll try to iterate today/tomorrow with a proposal. Thanks!

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by fabiocos** [comment]
@davidlange6 the various steps of the migration that you discuss above in the review are not a goal of 10_5_X strictly speaking, but this PR is anyway not affecting standard workflows and technically not breaking anything asa far as I can see. So I would move forward with its merge before 10_5_0_pre2 so as to make possible the tests in the DEVEL IB

**Comment by fabiocos** [comment]
+1

**Pull request merged**
