### PR TITLE
Phase2-hgc335L Use the right HGCalTopology builder in some of the test scripts

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Use the right HGCalTopology builder in some of the test scripts in Geometry/HGCalCommonData, Geometry/HGCalGeometry, Geometry/GEMGeometry

#### PR validation:

Tested those modified scripts

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by bsunanda** [comment]
@srimanob Please approve this

**Comment by srimanob** [comment]
+Upgrade

**Pull request merged**
