### PR TITLE
Fix python3 interface problem in RecoTauTag/RecoTau

### PR DESCRIPTION
**Pull request by fabiocos**
#### PR description:

In python3, dict no longer has an iteritems method.

#### PR validation:

Identical backport from 11_0_X

### CODE REVIEW

**Comment by fabiocos** [comment]
@Dr15Jones if we want to have in future 10_6_X python3 compatible better to backport your fix

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
please test

**Comment by perrotta** [comment]
+1
- Technical
- Jenkins tests pass

**Comment by perrotta** [comment]
backport of #27189

**Comment by fabiocos** [comment]
+1

**Pull request merged**
