### PR TITLE
Phase2-hgx357 Give correct names of some of the variables and correct their implementation in the HGCal Geometry

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Give correct names of some of the variables and correct their implementation in the HGCal Geometry

#### PR validation:

Use the runTheMatrix test workflows

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

**Comment by bsunanda** [comment]
@rvenditti, @aloeliger, @antoniovagnerini, @epalencia, @syuvivida, @tjavaid Please approve this PR

**Comment by tjavaid** [comment]
+1
- #45298 should fix [lost dict def issue](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-d6a724/40019/dupDict/lostDefs.txt).

**Comment by rappoccio** [comment]
+1

**Pull request merged**
