### PR TITLE
fix offline BS swap for express Run3 [12_0_X]

### PR DESCRIPTION
**Pull request by mmusich**
backport of #35373

#### PR description:

Address discussion at https://github.com/cms-sw/cmssw/pull/35334#issuecomment-925116203.

#### PR validation:

Run successfully wf 138.2 with: ` runTheMatrix.py -l 138.2 -j 8 -t 4` and verified the configuration looks as it should:

```console
$edmConfigDump step2_RAW2DIGI_L1Reco_RECO_DQM.py > dump.py
$more dump.py | grep -A 5 OnlineBeamSpotESProducer
process.BeamSpotESProducer = cms.ESProducer("OnlineBeamSpotESProducer",
    appendToDataLabel = cms.string(''),
    sigmaZThreshold = cms.double(2),
    timeThreshold = cms.int32(48)
)

$more dump.py | grep useTransientRecord
    useTransientRecord = cms.bool(True)
```

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

backport of #35373

### CODE REVIEW

**Comment by mmusich** [comment]
type bug-fix

**Comment by mmusich** [comment]
urgent

**Comment by mmusich** [comment]
again better wait for CMSSW_12_0_X_2021-09-23-1100 to appear before testing.

**Comment by mmusich** [comment]
test parameters:
   * workflow = 138.2

**Comment by pmandrik** [comment]
Hello, @mmusich , please check sistrip client [0] failed at P5 with error "No "BeamSpotTransientObjectsRcd" record found in the EventSetup.n" and probably requiring fix similar to [1].

[0] https://github.com/cms-sw/cmssw/blob/2d0d698cee75454bf05d0a423893588b54aeb0e8/DQM/Integration/python/clients/#L119-L120
[1] https://github.com/cms-sw/cmssw/pull/35397/files#diff-da64c486822399e8d4239a4eab3317c0214af6660d5244839c9a9f2060f46a00L7-L8

**Comment by mmusich** [comment]
@pmandrik not sure how that is possible. It passes the unit tests of `DQM/Integration`.

**Comment by jfernan2** [comment]
The different run used in the Integration test (334393 from Commissioning2019) w.r.t to the one used by @pmandrik (a recent run from this year), could this explain the crash? Anyway, with your last commit, it runs fine in Online DQM at P5

**Comment by mmusich** [comment]
> Anyway, with your last commit, it runs fine in Online DQM at P5.

That's nice.

> The different run used in the Integration test (334393 from Commissioning2019) w.r.t to the one used by @pmandrik (a recent run from this year), could this explain the crash? 

well, I tried the unit test with  a couple of more recent ones that are used e.g in RelVals: 
   * 343498 from `/ExpressCosmics/Commissioning2021-Express-v1/FEVT` (used in 138.2)
   * 344518 from `/ExpressCosmics/Commissioning2021-Express-v1/FEVT` (used in 136.897)
  
And in no case I observed a crash.
It's somewhat worrisome that the unit test is not able to catch such issues.

**Comment by jfernan2** [comment]
I see... we will try to debug in our side @pmandrik

**Comment by tvami** [comment]
@cmsbuild , please test
 * new IB is out

**Comment by jfernan2** [comment]
+1
Tested in Online DQM at P5

**Comment by tvami** [comment]
+alca
 * see conclusions at the master PR

**Comment by francescobrivio** [comment]
Following discussion in https://github.com/cms-sw/cmssw/pull/35373#issuecomment-927271601 and https://github.com/cms-sw/cmssw/pull/35373#issuecomment-927332842 there are few changes to be backported here.
Thus I have created new Run3 realistic MC GTs for 120X:
- 120X_mcRun3_2021_realistic_v8
- 120X_mcRun3_2021cosmics_realistic_deco_v7
- 120X_mcRun3_2021_realistic_HI_v7
- 120X_mcRun3_2023_realistic_v7
- 120X_mcRun3_2024_realistic_v7

More details in: https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/4474/1.html

**Comment by mmusich** [comment]
> More details in: https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/4474/1.html

Thanks @francescobrivio, new Global Tags are introduced here too.

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by tvami** [comment]
+alca

**Comment by jfernan2** [comment]
+1

**Comment by mmusich** [comment]
now on par with master. Wondering if it needs to be tested with a backport of https://github.com/cms-sw/cmssw/pull/35436

**Comment by mmusich** [comment]
In the last push the dedicated GlobalTag is updated by:
  * remove unused tags
  * adding `BeamSpotOnlineObjects` tags
```console
$ conddb diff 120X_mcRun3_2021_realistic_dd4hep_v1 120X_mcRun3_2021_realistic_dd4hep_v4
[2021-09-28 14:31:38,097] INFO: Connecting to pro [frontier://PromptProd/cms_conditions]
Record                          Label  pro::120X_mcRun3_2021_realistic_dd4hep_v1 Tag  pro::120X_mcRun3_2021_realistic_dd4hep_v4 Tag                                             
------------------------------  -----  ---------------------------------------------  ---------------------------------------------------------------------------------------   
BeamSpotOnlineHLTObjectsRcd     -      -                                              BeamSpotOnlineObjects_Realistic25ns_13TeVCollisions_RoundOpticsLowSigmaZ_RunBased_v1_mc   
BeamSpotOnlineLegacyObjectsRcd  -      -                                              BeamSpotOnlineObjects_Realistic25ns_13TeVCollisions_RoundOpticsLowSigmaZ_RunBased_v1_mc   
SiPixelDynamicInefficiencyRcd   50ns   SiPixelDynamicInefficiency_13TeV_50ns_v2_mc    -                                                                                         

```

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by tvami** [comment]
+alca

**Comment by jfernan2** [comment]
+1

**Comment by slava77** [comment]
+reconstruction

for https://github.com/cms-sw/cmssw/pull/35397	465cef7
- code changes are in line with the PR description and the follow up review. The updates are consistent with #35373 but not the same: apparently the differences are in the names of the GTs (121X vs 120X)
- jenkins tests pass and comparisons with the baseline show no (relevant) differences

**Comment by bbilin** [comment]
+1

**Comment by tvami** [comment]
Hi @cms-sw/upgrade-l2 Phat already signed the master PR, please consider signing this backport as well

**Comment by srimanob** [comment]
+Upgrade

Backport of https://github.com/cms-sw/cmssw/pull/35373

**Comment by tvami** [comment]
@perrotta @qliphy this needs to be merged urgently if we want to restore the geometry tags for 12_0_X MCs

**Comment by perrotta** [comment]
> @perrotta @qliphy this needs to be merged urgently if we want to restore the geometry tags for 12_0_X MCs

I was waiting for the results of the 1100 IB for the master, as a quick check that there are no major issues. But those IBs didn't show up yet.
It is not clear to me why you cannot restore the geometry tag on top of this PR...
In any case, let merge this one also in 12_0 since now, just to speed up things. The relevant part of this PR were apparently already tested with its previous versions.

**Comment by perrotta** [comment]
+1
- Differences with the master version (which is merged, although the corresponding master IB is not yet available) are only in the GTs
- As far as I understand, autoCond GTs will get further updated anyhow

**Pull request merged**
