### PR TITLE
Phase2-hgx333B Fix issues of wrong DetID assignment for V17 geometry of HGCal

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Fix issues of wrong DetID assignment for V17 geometry of HGCal

#### PR validation:

Use the runTheMatrix test workflows and test scripts in Validation/HGCalCOmmonData

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by civanch** [comment]
+1

not clear why Run3 WF with MkFit is sensitive to this PR. Phase-2 WFs demonstrate regression on this statistics.

**Comment by bsunanda** [comment]
@srimanob @perrotta @rappoccio Please approve and merge this PR

**Comment by srimanob** [comment]
> +1
> 
> not clear why Run3 WF with MkFit is sensitive to this PR. Phase-2 WFs demonstrate regression on this statistics.

This is because the test is not sensitive with the change in this PR, i.e. no effect on geometry used in the PR test. 
I propose to rerun the test with the geometry with v18 HGCAL (C18,C19,C20), and if everything runs smooth then PR can go.

**Comment by missirol** [comment]
> not clear why Run3 WF with MkFit is sensitive to this PR

It is likely unrelated to this PR, see #39803.

**Comment by srimanob** [comment]
The PR looks OK, D92, D93, and D94 workflows run fine. The failure comparison shows up in D92 in HGCAL which is expected that something should change. 

However, the failure comparison does not show up in D93 and D94 which are also based on C18 (v17 of HGCAL). I am not sure that in which case:
+ technical issue to make reference <== @smuzaffar Do you have some internal if the comparison will not make for this case?
+ or the PR does not effect C19, C20 (which are based on v17) <== @bsunanda  could you please confirm this?

Thanks very much.

**Comment by smuzaffar** [comment]
> technical issue to make reference <== @smuzaffar Do you have some internal if the reference is make, and comparison happen? Or not with 22834.0, 23234.0

@srimanob , baseline ref was built for all workflows, see https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_13_0_X_2022-12-13-1100+71bddf/54652/files/ and all of these workflows have ref.  Note that results on https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_13_0_X_2022-12-13-1100+71bddf/54652/validateJR.html are only shown if there are any changes/failures. Looks like DQM comparison did not find any differences for [22834.0](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_13_0_X_2022-12-13-1100+71bddf/54652/22834.0_TTbar_14TeV+2026D93RelMonComp-22834.0.log),  [23234.0](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_13_0_X_2022-12-13-1100+71bddf/54652/23234.0_TTbar_14TeV+2026D94RelMonComp-23234.0.log)

**Comment by emanueleusai** [comment]
+1

**Comment by bsunanda** [comment]
It only affects V17 geometry of HGCal, not the V16 version. C19 is also a v17 geometry version without cell structure defined at G4 Geometry for full wafers. C20 is also a v17 geometry version with added HFNose. All these versions are essentially v17 HGCal geometry.

**Comment by srimanob** [comment]
> It only affects V17 geometry of HGCal, not the V16 version. C19 is also a v17 geometry version without cell structure defined at G4 Geometry for full wafers. C20 is also a v17 geometry version with added HFNose. All these versions are essentially v17 HGCal geometry.

Hi @bsunanda 
I think I don't get from your answer. My question is NOT about V16. My question is on V17 with C19, C20. Do they expect to change with this PR? Because the PR test does not show that they change, only C18 that shows the change. See [comment](https://github.com/cms-sw/cmssw/pull/40281#issuecomment-1349604254) that I tried to clarify is baseline -vs- baseline+PR are done for them, and we confirm that they are done, but no change is seen.

**Comment by bsunanda** [comment]
The PR takes care of very rare occurrences of hits in some borderline cases of one type of partial wafers. This will include those borderline hits in digitisation and subsequently. Otherwise, the list of valid cells will not change. If such hits do not appear in some simulations, you will not see any difference. That is why regression is not a very clean test to prove any thing. We have made more careful tests for this PR.

**Comment by srimanob** [comment]
+Upgrade

**Comment by rappoccio** [comment]
+1

**Pull request merged**
