### PR TITLE
Toward HLT menu V3.0 (93X)

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
Toward HLT menu V3.0 (93X)
Based on CMSSW_9_3_0_pre4

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Dr15Jones** [comment]
+1
for addOnTests.py change

**Comment by davidlange6** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by Martin-Grunewald** [comment]
@Dr15Jones
Could you please sign this PR again? The core part (addOnTests) has not changed from your previous signature.

**Comment by Dr15Jones** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
