### PR TITLE
remove PPS workflows 11725.0 and 11925.0 

### PR DESCRIPTION
**Pull request by qliphy**
#### PR description:

Missing GEN-SIM input file for 11725.0 and 11925.0 is causing IB/PR test failures.
This PR is to remove PPS workflows before PdmV updates GS string in 11_3_X, see more in
https://github.com/cms-sw/cmssw/issues/33010#

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

No backport intended.

### CODE REVIEW

**Comment by qliphy** [comment]
please test

**Comment by qliphy** [comment]
please test

**Comment by silviodonato** [comment]
please test

**Comment by silviodonato** [comment]
(partial revert of #32983)

**Comment by chayanit** [comment]
+1

**Comment by qliphy** [comment]
@cms-sw/upgrade-l2  Would you please have a check and sign if no problem? This is to fix IB/PR issues.

**Comment by srimanob** [comment]
+Upgrade

**Comment by qliphy** [comment]
+1

**Pull request merged**
