### PR TITLE
Add safety check to spot negative jet energy correction factors

### PR DESCRIPTION
**Pull request by ahinzmann**
#### PR description:

Add a safety check when evaluating jet energy correction factors to spot cases where the functions yield unphysical negative corrections.
A warning is printed and the value is truncated to be small positive.
This should help spotting cases when calibration functions in the conditions are not fully positive defined (as they should).

#### PR validation:

runTheMatrix -l limited

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

To all release down to 10_6 to protect UL/Run3/Phase-2 studies.

### CODE REVIEW

**Comment by santocch** [comment]
+1

**Comment by silviodonato** [comment]
Do you have any comments? @ggovi

**Comment by silviodonato** [comment]
@ggovi Do you have any comments?

**Comment by silviodonato** [comment]
merge
cc: @ggovi

**Pull request merged**
