### PR TITLE
[13.0.X] Add `SiPixelRawDataError` monitoring for `gpuValidation` setup

### PR DESCRIPTION
**Pull request by mmusich**
backport of https://github.com/cms-sw/cmssw/pull/41920

#### PR description:

Somewhat inspired by the discussion at https://github.com/cms-sw/cmssw/issues/41715#issuecomment-1580541189, the main goal of this PR is to add a `DQMEDAnalyzer` (`SiPixelPhase1RawDataErrorComparator`) designed to monitor the difference in terms of SiPixel Raw data errors in the CPU and GPU branches of the workflows running the `gpuValidation` modifier.
As there is no SoA-like data structure used in the CPU workflow (it reads directly the legacy digis) at variance with other heterogeneous data products used in the pixel workflow (recHits, tracks, vertices) I designed the module in order to read the legacy data format `SiPixelRawDataError` (converted from SoA in the GPU workflow and run directly in the CPU one).
I profit of this PR to fix a couple of bugs left from the portable data migration PR:
   * fix a mistake in one of the input tags in `SiPixelCompareRecHitsSoA` 
   * use in `SiPixelCompareRecHitsSoA` the convention Host -> CPU and Device -> GPU as used in other plugins of this package 

#### PR validation:

Successfully run the worfklow `runTheMatrix.py -l 10824.507 --command='-n 100'.`

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Verbatim backport of https://github.com/cms-sw/cmssw/pull/41920 to 13.0.X to be proposed in the 2023 HLT menus.

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by missirol** [comment]
> Verbatim backport of https://github.com/cms-sw/cmssw/pull/41920 to 13.0.X to be proposed in the 2023 HLT menus.

I could use a clarification on the plan, esp. since we plan to cut the next HLT menu soon (hopefully, this week).

Is the idea to add new DQM plugins inside the HLT menu in the Path `DQM_PixelReconstruction_v` ? This is not difficult, but it requires time if any of the plugins is new: a new CMSSW release, the "parsing" of the new release in ConfDB (so the db knows the new plugin), then the update of the HLT menu. This is unlikely to converge in time for the upcoming HLT menu, and it might have to go to the next menu.

Could the relevant collections (e.g. `hltSiPixelDigisFromSoA` ?) be added to the EventContent of the `DQMGPUvsCPU` stream, and then let the new DQM plugins run inside the online-DQM client ? For HLT, this would only be a simple change to one EventContent, and it could be done in time for the next menu (i.e. this week).

FYI: @cms-sw/hlt-l2 @silviodonato @fwyzard

**Comment by fwyzard** [comment]
I would really, really prefer to keep "Host" and "Device" rather than using "CPU" and "GPU" - because the long term goal is that the "Device" could be a CPU with different scheduling, or an FPGA, etc.

In fact, for this kind of comparisons, I think it would be better to use the terms like "Reference" and "Candidate" ?

**Comment by mmusich** [comment]
> I would really, really prefer to keep "Host" and "Device" rather than using "CPU" and "GPU"

sure, but then let's do it consistently and not on selected plugins.

**Comment by emanueleusai** [comment]
+1

- ok from DQM independently of the discussion on naming of the collections (can also be done at a later time in a separate PR from our side)

**Comment by emanueleusai** [comment]
+1

**Comment by perrotta** [comment]
+1
- I take the thumb up of @fwyzard in https://github.com/cms-sw/cmssw/pull/41939#issuecomment-1589415452 as a certification that an agreement on the naming conventions has been reached.
- In any case, in master the variables are already renamed as implemented here

**Comment by mmusich** [comment]
>  a certification that an agreement on the naming conventions has been reached.

thanks Andrea, indeed, I will modify all the plugins in this package according to that suggestion in another PR in master at earliest.

**Pull request merged**
