### PR TITLE
Use unique_ptr in edm::Factory::MakerMap

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

Smart pointer is generally better, and makes the code more consistent with the EventSetup-side `ComponentFactory`, of which I'll make use of in later development.

#### PR validation:

Code compiles.

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by Dr15Jones** [comment]
looks good to me

**Comment by makortel** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
