### PR TITLE
Phase2-hgx359B Update the cfg files in Validation/Geometry in view of recent updates of the scenarios

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Update the cfg files in Validation/Geometry in view of recent updates of the scenarios

#### PR validation:

All the cfg's are tested with the new scenarios

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by bsunanda** [comment]
@antoniovagnerini, @nothingface0, @rvenditti, @syuvivida, @tjavaid Please approve this PR

**Comment by tjavaid** [comment]
+1

**Pull request merged**
