### PR TITLE
Move fireworks exception handling to pybind11

### PR DESCRIPTION
**Pull request by davidlange6**
#### PR description:

Move fireworks exception handling to pybind11 - remove include from src directory as added bonus

#### PR validation:

compiles.

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
so much for my grep ability

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
please test

**Comment by alja** [comment]
+1

**Comment by Dr15Jones** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
