### PR TITLE
Don't forward declare CaloTower in CaloTowerFwd.h

### PR DESCRIPTION
**Pull request by Teemperor**
This header won't compile with just a forward declaration of
CaloTower, because the Ref and RefVector types we declare will check the
ValueTrait of it's containing class, which is in this case CaloTower.
ValueTrait needs to have the definition of CaloTower to work, but
we only have a forward declaration in this header available.

This leads to undefined behavior, so we should replace this forward
declaration with an actual include.

People seem to anyway always include CaloTower too to
avoid this cryptic error, so I don't think this will hit compilation
times that much.

### CODE REVIEW

**Comment by Teemperor** [comment]
Part of the work going on regarding issue https://github.com/cms-sw/cmssw/issues/15248

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
should we instead fix the Ref or remove typedefs that can not be forward-declared from Fwd files?
It seems a bit awkward to keep \*Fwd file which can not serve the purpose  in its name to be a forward header.

@davidlange6 @Dr15Jones

**Comment by slava77** [comment]
@davidlange6 @Dr15Jones 
please let me know what is a good way to go here https://github.com/cms-sw/cmssw/pull/18805#issuecomment-302301298

**Comment by Dr15Jones** [comment]
There is nothing to 'fix' in `Ref`, it is doing what it needs to do. I think the problem is the name of the file itself. The file was never used for 'forwarding', instead it defines a set of common typedefs. So maybe `CaloTowerDefs.h`?

**Comment by slava77** [comment]
On 5/22/17 7:29 AM, Chris Jones wrote:
> There is nothing to 'fix' in |Ref|, it is doing what it needs to do. I
> think the problem is the name of the file itself. The file was never
> used for 'forwarding', instead it defines a set of common typedefs. So
> maybe |CaloTowerDefs.h|?

It seems like the easiest option is to open the scope of "Fwd" to be
just for forward declarations and move on with this and similar PRs.

Migration of file names from Fwd to Defs sounds a bit disruptive.

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/18805	72f73ba
- technical; implemented as described. It looks like we can stay with \*Fwd.h named files, since the alternative (renaming to \*Defs.h is only semantically different and will introduce changes in many files including this).
- jenkins tests pass

**Comment by slava77** [comment]
@davidlange6 
please check this PR and merge or suggest an alternative. IIUC, there are more changes like this pending.
Thank you.

**Comment by davidlange6** [comment]
its on my list

**Comment by davidlange6** [comment]
it seems the "right" solution requires a git mv and 16 lines of code to change.  You are concerned about a bigger change that is in the works?

**Comment by slava77** [comment]
On 5/29/17 7:39 AM, David Lange wrote:
> it seems the "right" solution requires a git mv and 16 lines of code to
> change. You are concerned about a bigger change that is in the works?
> 

The same issue (Ref used in typedefs in Fwd file) applies to many other
files.
There are about 4K files which include various Fwd files.
Are you suggesting we start migration with this PR?

**Comment by davidlange6** [comment]
I would not do it piece by piece, no. sed is a pretty nice thing in the git era. I'm sure it would do 95% of the work of the renaming, which seems not so bad if we are already going to go through and add the missing # include to all the *Fwd.h DataFormat includes (already a bunch of work).

**Comment by slava77** [comment]
On 5/30/17 4:25 AM, David Lange wrote:
> I would not do it piece by piece, no. sed is a pretty nice thing in the
> git era. I'm sure it would do 95% of the work of the renaming, which
> seems not so bad if we are already going to go through and add the
> missing # include to all the *Fwd.h DataFormat includes (already a bunch
> of work).


So, to be explicit, you are asking for a change in the file names.
Which new name would you like?
Please clarify.
Thank you.

**Comment by davidlange6** [comment]
Fwd->Defs or something more descriptive of whats actually happening seemed to be a consensus desired change. *Fwd.h indeed has confused me in the past and thanks to this PR I understand better why that was.

**Comment by slava77** [comment]
OK, I dropped "+1" and expect this PR to have this file renamed.

**Comment by slava77** [comment]
@Teemperor 
please clarify on the status of updates for this PR.
Thank you.

**Comment by Teemperor** [comment]
So, should I create another PR where I fix this for all Fwd.h?

**Comment by slava77** [comment]
On 6/6/17 2:27 AM, Raphael Isemann wrote:
> So, should I create another PR where I fix this for all Fwd.h?
> 

As long as this is justified.
If a file is really a plain forward declaration, it should stay Fwd.h
Files using typedefs of Ref< are clear examples to migrate based on
CaloTowerFwd case

Also, it may be more practical to make this change separately for Fwd
files in DataFormats/,
and separate PRs for files in other subsystems.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by dmitrijus** [comment]
+1

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/18805	5a6e0ab
- technical; 
- jenkins tests pass

**Comment by alja** [comment]
+1

**Comment by Martin-Grunewald** [comment]
+1

**Pull request merged**
