### PR TITLE
Cleanup unit tests in FWCore/Utilities

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

- made compile time test to not run during testing
- changed atomic_value_ptr test to catch2

#### PR validation:

Code compiles and test succeed.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by makortel** [comment]
> * changed atomic_value_ptr test to catch2

This part seems to be missing something, as the diff looks like the test is removed?

**Comment by Dr15Jones** [comment]
> This part seems to be missing something, as the diff looks like the test is removed?

The file was renamed and I thought the tool had done a 'git add' for me. Looks like it did not <sigh/>.

**Comment by Dr15Jones** [comment]
please test

**Comment by makortel** [comment]
The usual
* https://github.com/cms-sw/cmssw/issues/43293
* https://github.com/cms-sw/cmssw/issues/43790

**Comment by makortel** [comment]
+core

**Comment by rappoccio** [comment]
+1

**Pull request merged**
