### PR TITLE
[125X] Fix double counting in HepMC to G4 handoff

### PR DESCRIPTION
**Pull request by tvami**
#### PR description:

See https://github.com/cms-sw/cmssw/pull/39427

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport of https://github.com/cms-sw/cmssw/pull/39427

### CODE REVIEW

**Comment by tvami** [comment]
type bugfix

**Comment by tvami** [comment]
backport of https://github.com/cms-sw/cmssw/pull/39427

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by civanch** [comment]
+1

**Comment by tvami** [comment]
urgent
 * tho I'd hope to get a green light from @jmartinb on how to proceed with this

**Comment by perrotta** [comment]
hold
- Pending the validation campaign in master described in https://its.cern.ch/jira/browse/PDMVRELVALS-165

**Comment by tvami** [comment]
@cmsbuild , please test
 * let's refresh the tests

**Comment by rappoccio** [comment]
+1

As discussed in ORP, no modifier protection is needed for this one.

**Comment by rappoccio** [comment]
untold

**Pull request merged**
