### PR TITLE
Bugfix and c tagging for ParticleLevelProducer (80X)

### PR DESCRIPTION
**Pull request by mseidel42**
* Use pt instead of et for MET, master PR: https://github.com/cms-sw/cmssw/pull/19701
* Add c tagging, master PR https://github.com/cms-sw/cmssw/pull/19747

### CODE REVIEW

**Comment by efeyazgan** [comment]
please test

**Comment by perrozzi** [comment]
+1

**Comment by intrepid42** [comment]
Added c-tagging for jets to this request (backport of https://github.com/cms-sw/cmssw/pull/19747)

**Comment by perrozzi** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
