### PR TITLE
MiniAOD Spring15pass2 7.4.X (collection of all PRs)

### PR DESCRIPTION
**Pull request by gpetruc**
As discussed in the RECO/AT meeting of August 6th, I've made a branch that merges all PRs for the 74X and ready for merge (i.e. once they're fully signed), so that they can be tested as a whole.
At the moment it includes: #10175 #10366 #10361 #10362 #10363 #10364 #10593 
Summary on the [MiniAODSpring15pass2 twiki](https://twiki.cern.ch/twiki/bin/view/CMS/MiniAODSpring15pass2#MiniAODSpring15pass2edittable1)

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild 
I suppose we can keep testing it occasionally as it updates

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by gpetruc** [comment]
Updated #10593 to its head (was fully signed before the trivial update), merged #10556, #10667 (both are fully signed), and updated to `CMSSW_7_4_9`

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by gpetruc** [comment]
Updates: `CMSSW_7_4_10_patch1` + #10604 , #10750 and synch #10598 . 
Tested on top of `CMSSW_7_4_X_2015-08-20-1100`

**Comment by slava77** [comment]
@gpetruc #10598 is not signed yet
I thought you were merging only signed ones.
It his is not the case, checks of this PR in general becomes more complicated.

**Comment by gpetruc** [comment]
Updated to include #10551 

For the record, as we discussed in the reco meeting, #10598 was merged here at the time when it was fully-signed, then some bugfixes were pushed to it.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by gpetruc** [comment]
Including #10760 (fully signed) as requested on that PR's thread.
Now working at cleaning up some un-necessary rerunning of RECO modules

**Comment by slava77** [comment]
@cmsbuild please test

@gpetruc please post what's still missing

**Comment by gpetruc** [comment]
@slava77: things not yet merged are:
 * #10895: L1 prescales, pending AT signature 
 * #10693: e/g scale corrections, pending AT signature (signed off by reco, alca)
 * #10943 : taus, pending AT signature (signed off by reco) + https://github.com/cms-tau-pog/cmssw/pull/10 (which I can also merge here directly instead of having it merged in that PR)
 * #10443: met filters, pending all signatures after the changes for multithreading and the relocation of data (which needs https://github.com/cms-data/CondFormats-JetMETObjects/pull/2 )
 * https://github.com/gpetruc/cmssw/pull/5: don't rerun reco modules

**Comment by davidlange6** [comment]
@gpetruc, @slava77   - any reason that I should not just close the PRs that are incorporated into this one? It would make it easier to see what else is needed

**Comment by slava77** [comment]
@davidlange6 
Fine with me.
I suggested something along the lines already (in a RECO meeting, I think)

**Comment by gpetruc** [comment]
@davidlange6 : fine for me, that would also discourage people from updating those PRs after I have merged them.

I have updated now this with the new PRs that were fully-signed as of today:  #10895  #10693 #10943 and the switches to re-run Taus  ( cms-tau-pog#10 ) and to not re-run reco modules ( gpetruc#5 ).

The only missing MiniAOD PRs for 74X are #10443 (met),  #11007 (pileup jetid),  #10673 (multicore)

**Comment by davidlange6** [comment]
closing PRs included in #10649

**Comment by gpetruc** [comment]
Uhm... #10649 itself should probably stay open.

**Comment by davidlange6** [comment]
good point...

**Comment by gpetruc** [comment]
As discussed today at the PPD coordination meeting, I have changed the default config of MiniAOD 74X to always re-run tau reconstruction.

**Comment by davidlange6** [comment]
@cmsbuild, please test

**Comment by slava77** [comment]
```
Exception Message:
python encountered the error: <class 'urllib2.URLError'>
<urlopen error [Errno -2] Name or service not known>
```
is this a real error?

**Comment by davidlange6** [comment]
@slava77 - doesn't seem to be - but we have these errors all of a sudden

**Comment by davidlange6** [comment]
Merging this PR for 7_4_11.

**Pull request merged**
