### PR TITLE
Run2-gex125 Attempt to make 2017 scenario compatible with dd4hep

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Attempt to make 2017 scenario compatible with dd4hep. There is still an issue in  DTGeometryESModule which was observed earlier for dd4hep version of Phase2 and resolved by Phat. The relevant files for Geometry are in Geometry/HcalCommonData/python/GeometryDD4HepExtended2017... and test codes are in Geometry/HcalCommonData/test/python for steps 1,2,3 derived from 10024.0 

#### PR validation:

Tested using the runTheMatrix test workflows

Details about the test procedure are available below in
- https://github.com/cms-sw/cmssw/pull/37394#issuecomment-1094203966
- https://github.com/cms-sw/cmssw/pull/37394#issuecomment-1094225307

Definitely all these scenarios should be finally made testable in the IBs, with either a unit test or a dedicated workflow.

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@srimanob How did you cure the discrepancy for number of ID's for DT's

**Comment by srimanob** [comment]
Hi @bsunanda 

I follow Run-3 config by using
'Geometry/DTGeometryBuilder/data/dtSpecsFilter/2021/v1/dtSpecsFilter.xml',
instead of
'Geometry/DTGeometryBuilder/data/dtSpecsFilter.xml',

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
Why is `eefixed.xml` being changed? It looks like a small change in the geometry, from toruses to tube segments.

**Comment by bsunanda** [comment]
We found issues with Torus and switched to tube segments for Run3 geometry. I am using the same for 2017 and 2018 which is unchanged in 2021.
________________________________

**Comment by cvuosalo** [comment]
I started a document to record geometry changes required for the Runs 1-2 DD4hep migration: https://docs.google.com/document/d/13PgtGTpk92shgtwWPVy8rCx0s7mmXEjH7kz1veYC7dI/edit?usp=sharing

**Comment by cvuosalo** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

Should we open the git issue which may just have a short description and then point to the gdoc? So that we will not forget the remaining, at least from the list of remaining items on git.

**Comment by perrotta** [comment]
>Tested using the runTheMatrix test workflows

@bsunanda could you please specify how was it tested? Are those workflows the one regularly run during the IB tests (and therefore possible future issues or incompatibilities with other updates can be spotted by them during the usual IB checks)?

**Comment by srimanob** [comment]
@perrotta 
I think this was what we start the discussion during the O&C week on the strategy. Do we need to have something run-able but not validate not test, or we need something to be tested regularly. I think we don't have a clear plan of what to be done. I signed it as considered that it is a starting point to have work XML for DD4hep Run-2. 

If the goal or strategy are still unclear, I think we can find a chance for following up discussion. One possibility is tomorrow SIM meeting. But I think the goal/strategy should come from top-level. This was also stated by @civanch during the meeting.

**Comment by perrotta** [comment]
@bsunanda @srimanob @civanch my first question was simple, and answering it shouldn't delay the merging of this PR.

> Tested using the runTheMatrix test workflows
- Could you please specify how was it tested?

While for the second question (Are those workflows the ones regularly run during the IB tests (and therefore possible future issues or incompatibilities with other updates can be spotted by them during the usual IB checks)?), I imaging from the previous answers of yours that those " runTheMatrix test workflows" were not the ones run regularly on IB tests. In any case, also answering this question shouldn't take that much...

**Comment by cvuosalo** [comment]
@perrotta I would guess that this PR was tested with the test scripts included in the PR. A Run 2 DD4hep workflow that runs correctly to completion is probably some time away. This PR may be a first step in that direction.

**Comment by bsunanda** [comment]
I tested using the cfg's stored in Geometry/HcalCommonData. There are still issues - they are related to some HCAL code which we see for Phase2 dd4hep trials as well. We shall handle this separately. For DDD this works fine till the end. This is a good starting point for transition of Run2 scenario. There will be many steps to go.

**Comment by perrotta** [comment]
> I tested using the cfg's stored in Geometry/HcalCommonData. There are still issues - they are related to some HCAL code which we see for Phase2 dd4hep trials as well. We shall handle this separately. For DDD this works fine till the end. This is a good starting point for transition of Run2 scenario. There will be many steps to go.

Thank you @bsunanda 

Whilch is the test that succeeds, and the one which fails? What is the failing message, to be left here as a reference?
Would it be possible to make those config to be run as unit tests, so that they can be tested automatically at every IB and spot possible issues as soon as they show up?

**Comment by bsunanda** [comment]
It fails in the L1 step related to HCAL - this is most likely related to accessing calibration constant. It is a bit complex and I shall look into this issue later on. I do not want to make it a unit test till the issue is resolved. For DDD, there is no issue - only happend for dd4hep. So it is most likely linked with the specpar analysis The cfg's *10024*.py are the ones used to take care of steps 1, 2, 3 for 2017 scenario. Please let this PR be merged and then I shall start investigating the issue

**Comment by bsunanda** [comment]
The tests performed started with 2 workflows: 10024.0 and 10024.911 and replacing the geometries using process.load('Geometry.HcalCommonData.GeometryDD4HepExtended2017_cff')
process.load('Geometry.HcalCommonData.GeometryDD4HepExtended2017Reco_cff')
The job failed in step2 for the dd4hep side with the message:

An exception of category 'Conditions mismatch' occurred while
   [0] Processing  Event run: 1 lumi: 1 event: 1 stream: 0
   [1] Running path 'HLTAnalyzerEndpath'
   [2] Prefetching for module L1TRawToDigi/'hltGtStage2Digis'
   [3] Prefetching for module RawDataCollectorByLabel/'rawDataCollector'
   [4] Prefetching for module SiStripDigiToRawModule/'SiStripDigiToRaw'
   [5] Calling method for module MixingModule/'mix'
Exception Message:
Requested conditions of type HcalQIETypes for cell (0x45104401) (HE -17,1,1) got
 conditions for cell (0x45386c0b) (HE 27,11,3)

**Comment by perrotta** [comment]
> The tests performed started with 2 workflows: 10024.0 and 10024.911 and replacing the geometries using process.load('Geometry.HcalCommonData.GeometryDD4HepExtended2017_cff') process.load('Geometry.HcalCommonData.GeometryDD4HepExtended2017Reco_cff') The job failed in step2 for the dd4hep side with the message:
> 
> An exception of category 'Conditions mismatch' occurred while [0] Processing Event run: 1 lumi: 1 event: 1 stream: 0 [1] Running path 'HLTAnalyzerEndpath' [2] Prefetching for module L1TRawToDigi/'hltGtStage2Digis' [3] Prefetching for module RawDataCollectorByLabel/'rawDataCollector' [4] Prefetching for module SiStripDigiToRawModule/'SiStripDigiToRaw' [5] Calling method for module MixingModule/'mix' Exception Message: Requested conditions of type HcalQIETypes for cell (0x45104401) (HE -17,1,1) got conditions for cell (0x45386c0b) (HE 27,11,3)

Thank you @bsunanda 
Let accept this PR to let you proceed. However, these scenarios must be made testable in the IBs. The two workflows: 10024.0 and 10024.911 modified as you reported in https://github.com/cms-sw/cmssw/pull/37394#issuecomment-1094225307 should better become two new workflows being regularly run in the IB tests (of course, by keeping the DD4Hep workflow disabled until the exception that you are talking about cannot be fixed).

**Comment by perrotta** [comment]
+1

**Pull request merged**
