### PR TITLE
Update HLT and GT packer for new HI L1 objects (Backport to 10_3_X)

### PR DESCRIPTION
**Pull request by apana**
Backport of PR #25064 

* Update firmware version in cfi for uGT packer (gtStage2Raw_cfi.py) to pack new HI L1 objects
* Update HLT so TriggerFilterObjectWithRefs objects get filled properly for new HI L1 objects

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by rekovic** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
