### PR TITLE
Adding eval=true in ConstantsSection in all PPS xml files

### PR DESCRIPTION
**Pull request by mundim**
#### PR description:
Adding eval="true" in the PPS xml files, as requested in

https://github.com/cms-sw/cmsdist/pull/5954#issuecomment-645925272

#### PR validation:
Tests passed  and the new files were tested again in the PPS simulation, producing properly the hits as expected.

### CODE REVIEW

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by smuzaffar** [comment]
I have restart the test with `DetectorDescription/DDCMS Geometry/DTGeometryBuilder SimG4Core/DD4hepGeometry` extra package to be build along with this PR. Looks like this did not fix the unit test issue. Test still fail with error 
```
===== Test "testDD4hepCompactView" ====
Running .Info in <TGeoManager::TGeoManager>: Geometry DUMMY, Detector Geometry created
PersistencyIO    INFO  +++ Set Streamer to dd4hep::OpaqueDataBlock
CompactLoader    INFO  +++ Processing compact file: /cvmfs/cms-ib.cern.ch/nweek-02633/slc7_amd64_gcc820/cms/cmssw-patch/CMSSW_11_2_X_2020-06-18-2300/src/Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2021.xml with flag (null)
DD4CMS           INFO  +++ Processing the CMS detector description file:///cvmfs/cms-ib.cern.ch/nweek-02633/slc7_amd64_gcc820/cms/cmssw-patch/CMSSW_11_2_X_2020-06-18-2300/src/Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2021.xml
Info in <TGeoManager::SetTopVolume>: Top volume is world_volume. Master volume is world_volume
Info in <TGeoNavigator::BuildCache>: --- Maximum geometry depth set to 100
Detector         INFO  *********** Created World volume with size: 10100 10100 45000
DD4CMS           ERROR Exception while processing xml source:file:///data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_2_X_2020-06-18-2300/src/Geometry/VeryForwardData/data/RP_Hybrid.xml
DD4CMS           ERROR ----> Cannot find a material referenced by name:RP_Materials:CE7
dd4hep: Error interpreting XML nodes of type <LogicalPart/>
dd4hep: Error interpreting XML nodes of type <LogicalPartSection/>
E

##Failure Location unknown## : Error
Test name: testDDCompactView::checkCompactView
uncaught exception of type std::exception (or derived).
- Cannot find a material referenced by name:RP_Materials:CE7
dd4hep: Error interpreting XML nodes of type <LogicalPart/>
dd4hep: Error interpreting XML nodes of type <LogicalPartSection/>
dd4hep: while parsing /cvmfs/cms-ib.cern.ch/nweek-02633/slc7_amd64_gcc820/cms/c
mssw-patch/CMSSW_11_2_X_2020-06-18-2300/src/Geometry/CMSCommonData/data/dd4hep/
cmsExtendedGeometry2021.xml
dd4hep: with plugin:DD4hep_CompactLoader

Failures !!!
Run: 1   Failure total: 1   Failures: 0   Errors: 1

---> test testDD4hepCompactView had ERRORS
```

**Comment by smuzaffar** [comment]
@mundim, did you actuall checkout `DetectorDescription/DDCMS Geometry/DTGeometryBuilder SimG4Core/DD4hepGeometry` while testing locally?

**Comment by mundim** [comment]
> @mundim, did you actuall checkout `DetectorDescription/DDCMS Geometry/DTGeometryBuilder SimG4Core/DD4hepGeometry` while testing locally?

I did the standard tests when submitting the PR (#30268), then in another PR (#5954) that was not created by me, Ianna asked me to include the "eval" tag in some xml files (it was present only in some of them). Then I made the tests in the same working area as in the PR already merged. 
See the comment https://github.com/cms-sw/cmssw/pull/30268#issuecomment-646230887

It seems there is a clash between these PRs...

**Comment by silviodonato** [comment]
@mundim Just to avoid possible misunderstanding, @smuzaffar is saying that if you run the unit tests of those folders we continue to get many errors
```
git cms-merge-topic 30292
git cms-addpkg Geometry/DTGeometryBuilder 
git cms-addpkg DetectorDescription/DDCMS 
git cms-addpkg SimG4Core/DD4hepGeometry
scram b runtests
```
you get many errors (as we had in plain `CMSSW_11_2_X_2020-06-22-1100`).
Example:
```
===== Test "cmsRun validateDTGeometry_cfg.py" ====
Info: Load idToGeo 2021 from ///cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_X_2020-06-22-1100/external/slc7_amd64_gcc820/data/Fireworks/Geometry/data/cmsGeom2021.root
Begin processing the 1st record. Run 1, Event 1, LumiSection 1 on stream 0 at 22-Jun-2020 17:41:46.406 CEST
PersistencyIO    INFO  +++ Set Streamer to dd4hep::OpaqueDataBlock
CompactLoader    INFO  +++ Processing compact file: /cvmfs/cms-ib.cern.ch/nweek-02634/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_X_2020-06-22-1100/src/Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2021.xml with flag (null)
DD4CMS           INFO  +++ Processing the CMS detector description file:///cvmfs/cms-ib.cern.ch/nweek-02634/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_X_2020-06-22-1100/src/Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2021.xml
Detector         INFO  *********** Created World volume with size: 10100 10100 45000
DD4CMS           ERROR Exception while processing xml source:file:///afs/cern.ch/work/s/sdonato/ORP/CMSSW_11_2_X_2020-06-22-1100/src/Geometry/VeryForwardData/data/RP_Hybrid.xml
DD4CMS           ERROR ----> Cannot find a material referenced by name:RP_Materials:CE7
dd4hep: Error interpreting XML nodes of type <LogicalPart/>
dd4hep: Error interpreting XML nodes of type <LogicalPartSection/>
----- Begin Fatal Exception 22-Jun-2020 17:41:46 CEST-----------------------
An exception of category 'StdException' occurred while
   [0] Processing  Event run: 1 lumi: 1 event: 1 stream: 0
   [1] Running path 'p'
   [2] Calling method for module DTGeometryValidate/'valid'
   [3] Using EventSetup component DTGeometryESProducer/'' to make data DTGeometry/'' in record MuonGeometryRecord
   [4] Using EventSetup component MuonNumberingESProducer/'' to make data MuonNumbering/'' in record MuonNumberingRecord
   [5] Using EventSetup component DDSpecParRegistryESProducer/'' to make data DDSpecParRegistry/'MUON' in record DDSpecParRegistryRcd
   [6] Using EventSetup component DDDetectorESProducer/'' to make data DDDetector/'MUON' in record IdealGeometryRecord
Exception Message:
A std::exception was thrown.
Cannot find a material referenced by name:RP_Materials:CE7
dd4hep: Error interpreting XML nodes of type <LogicalPart/>
dd4hep: Error interpreting XML nodes of type <LogicalPartSection/>
dd4hep: while parsing /cvmfs/cms-ib.cern.ch/nweek-02634/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_X_2020-06-22-1100/src/Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2021.xml
dd4hep: with plugin:DD4hep_CompactLoader
----- End Fatal Exception -------------------------------------------------

=============================================

MessageLogger Summary

 type     category        sev    module        subroutine        count    total
 ---- -------------------- -- ---------------- ----------------  -----    -----
    1 Fatal Exception      -s PostModuleEvent                        1        1

 type    category    Examples: run/evt        run/evt          run/evt
 ---- -------------------- ---------------- ---------------- ----------------
    1 Fatal Exception      1/1                               

Severity    # Occurrences   Total Occurrences
--------    -------------   -----------------
System                  1                   1

dropped waiting message count 0
Failure using cmsRun /afs/cern.ch/work/s/sdonato/ORP/CMSSW_11_2_X_2020-06-22-1100/src/Geometry/DTGeometryBuilder/test/python/validateDTGeometry_cfg.py: status 66
status = 16896

---> test GeometryDTGeometryBuilderTestDriver had ERRORS
 
^^^^ End Test GeometryDTGeometryBuilderTestDriver ^^^^

```

**Comment by cvuosalo** [comment]
@mundim I am finding a series of errors in the PPS XML files. I revise a file to fix one error, and then another error is revealed. There are more errors than just these. Here are two I found so far:
```
+++ b/Geometry/VeryForwardData/data/CTPPS_2018/CTPPS_220_Right_Station.xml
@@ -12,14 +12,17 @@
         <Constant name="RP_220_Right_Timing_z" value="1680*mm"/>
         
         <Constant name="RP_220_Right_Rot_Angle_180" value="180"/>
+
+        <Constant name="RP_220_Right_Hor_Vac_Length" value="[RP_Device:RP_Device_Envelope_Radius]+[RP_Device:RP_Device_Length_y]/2-[RP_Horizontal_Device:RP_Device_Hor_Closed_Wall_Thick_Int]"/>
+    </ConstantsSection>
+
+    <RotationSection label="CTPPS_220_Right_Station.xml" eval="true">
         <Rotation name="RP_220_Right_Sec_Rotation_180" 
             phiX="[RP_220_Right_Rot_Angle_180]*deg" thetaX="90*deg" 
             phiY="(90+[RP_220_Right_Rot_Angle_180])*deg" thetaY="90*deg"
             phiZ="0*deg" thetaZ="0*deg"/>
         <Rotation name="PPS_Timing_rot" phiX="0*deg" thetaX="0*deg" phiY="90*deg" thetaY="90*deg" phiZ="0*deg" thetaZ="270*deg"/>
-
-        <Constant name="RP_220_Right_Hor_Vac_Length" value="[RP_Device:RP_Device_Envelope_Radius]+[RP_Device:RP_Device_Length_y]/2-[RP_Horizontal_Device:RP_Device_Hor_Closed_Wall_Thick_Int]"/>
-    </ConstantsSection>
+    </RotationSection>
     
     <SolidSection label="CTPPS_220_Right_Station.xml">  
         <Tube rMin="0*mm" rMax="[RP_Device:RP_Device_Envelope_Radius]*1.1" dz="[RP_220_Right_Station_Length]/2" name="RP_220_Right_Station"/>

+++ b/Geometry/VeryForwardData/data/RP_Materials.xml
@@ -119,7 +119,6 @@
     <rMaterial name="RP_Materials:Hydrogen"/>
    </MaterialFraction>
   </CompositeMaterial>
- </MaterialSection>
   
  <CompositeMaterial name="PCB" density="1.957*g/cm3" symbol=" " method="mixture by weight">
   <MaterialFraction fraction="0.2562774130">
@@ -153,4 +152,5 @@
     <rMaterial name="RP_Materials:Aluminum"/>
    </MaterialFraction>
   </CompositeMaterial>
+ </MaterialSection>
 </DDDefinition>
```

**Comment by cvuosalo** [comment]
@mundim Are you working on fixing the errors I've mentioned?

**Comment by mundim** [comment]
> @mundim Are you working on fixing the errors I've mentioned?
Not yet, I had other urgent buseness to address. 

But I don't understand these errors. These files have been used since long ago and the only modification I made was to include the "eval=true" on them as asked by Ianna. 
I will check them again.

**Comment by mundim** [comment]
I checked all the files in Geometry/VeryForwardData and the only difference is the inclusion of that keyword (apart from different CopyNumbers in a couple of files, on of them not used in the 2018 and 2021 geometry). 

<   <ConstantsSection label="TotemTiming_Dist_Beam_Cent.xml">    -> original file
---
>   <ConstantsSection label="TotemTiming_Dist_Beam_Cent.xml" eval="true">  -> new file

As I said, these files have been used since long ago in the simulation with no problem (using XML geometry). 

I'm not sure I understood what is wrong, but I noticed Rotations block defined inside a ConstantsSection. 

Is that the problem?

**Comment by cvuosalo** [comment]
@mundim These PPS XML files were used with the old DD, which apparently allowed incorrect syntax. But now these PPS files are being included with the DD4hep unit tests, and DD4hep is finding errors. In this comment (https://github.com/cms-sw/cmssw/pull/30292#issuecomment-647824004) I list two errors, one where a Rotation is defined outside of a Rotation block, and one where a Composite Material is defined outside of a Material section.

**Comment by mundim** [comment]
Hopefully all occurrences of the ConstantsSection, RotationSections and MaterialSections are addressed.

**Comment by smuzaffar** [comment]
please test

**Comment by ianna** [comment]
@mundim - there are still errors in the XML files:
```
DD4CMS           ERROR Exception while processing xml source:file:///data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_2_X_2020-06-22-2300/src/Geometry/VeryForwardData/data/CTPPS_2018/CTPPS_220_Right_Station.xml
DD4CMS           ERROR ----> Handle_t::attr_ptr: Element [PosPart] has no attribute of type 'copyNumber'
dd4hep: Error interpreting XML nodes of type <PosPart/>
dd4hep: Error interpreting XML nodes of type <PosPartSection/>
----- Begin Fatal Exception 23-Jun-2020 07:41:47 CEST-----------------------
An exception of category 'StdException' occurred while
   [0] Processing  Event run: 1 lumi: 1 event: 1 stream: 0
   [1] Running path 'p'
   [2] Calling method for module DD4hepTestG4Geometry/'test'
   [3] Using EventSetup component DDVectorRegistryESProducer/'' to make data DDVectorRegistry/'' in record DDVectorRegistryRcd
   [4] Using EventSetup component DDDetectorESProducer/'' to make data DDDetector/'' in record IdealGeometryRecord
Exception Message:
A std::exception was thrown.
Handle_t::attr_ptr: Element [PosPart] has no attribute of type 'copyNumber'
dd4hep: Error interpreting XML nodes of type <PosPart/>
dd4hep: Error interpreting XML nodes of type <PosPartSection/>
dd4hep: while parsing /cvmfs/cms-ib.cern.ch/nweek-02634/slc7_amd64_gcc820/cms/cmssw-patch/CMSSW_11_2_X_2020-06-22-2300/src/Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2021.xml
dd4hep: with plugin:DD4hep_CompactLoader
----- End Fatal Exception -------------------------------------------------
```
@cvuosalo - there is a script that you may want to integrate as an automated IB unit test for all XML files to check the units:
```
python UnitsCheck.py cms.xml
```

**Comment by ianna** [comment]
> @mundim These PPS XML files were used with the old DD, which apparently allowed incorrect syntax. But now these PPS files are being included with the DD4hep unit tests, and DD4hep is finding errors. In this comment ([#30292 (comment)](https://github.com/cms-sw/cmssw/pull/30292#issuecomment-647824004)) I list two errors, one where a Rotation is defined outside of a Rotation block, and one where a Composite Material is defined outside of a Material section.

@mundim - the old DD would ignore the errors in the XML definitions with an unpredicted outcome: sometimes it would overwrite the previous definition, sometimes it would ignore the definition if it’s outside of the section. If it used to work for PPS it’s only by chance. BTW, I used to run a commercial XML validator on all XML files prior their integration to the scenarios. DD4hep does it for you for free :-)

**Comment by mundim** [comment]
> ```
> python UnitsCheck.py cms.xml
> ```

Thanks, I was going to ask for such a tool. As I see, someone changed the files and the tests are ongoing, right? I wonder if we will ever get to an end on this...

**Comment by mundim** [comment]
I tried the script above in the one file and apparently, it is considering a number in a string as a numeric value:

> Geometry/VeryForwardData/data/CTPPS_2018/CTPPS_220_Right_Station.xml: line# 13 warning: numerical value without units: 
        <Constant name="RP_220_Right_Rot_Angle_180" value="180*deg"/>

                                               ^-----                  

Is is complaining about the "_180" in the constant name.

**Comment by ianna** [comment]
Yes, the script is not perfect, but it would point to an occurrence where it thinks the problem is

**Comment by mundim** [comment]
Yes, sure. I found a angle value without the "deg". So, should I proceed with the verification or wait for the ongoing tests? thanks.

**Comment by mundim** [comment]
In fact, I found a lot of other places without the "*deg" in the value field.

**Comment by cvuosalo** [comment]
@mundim Yes, constants should be defined with the units specified.

**Comment by forthommel** [comment]
> @mundim Yes, constants should be defined with the units specified.

This is all a matter of convention, but wouldn't something along:
```.xml
<Constant name="RP_210_Left_Sec_Rot_Angle" value="8*deg"/>
<Rotation name="RP_210_Left_Sec_Rotation" phiX="[RP_210_Left_Sec_Rot_Angle]" thetaX="90*deg"/>
```
be more consistent, i.e. with the unit defined at the constant definition stage instead of its consumer attributes (e.g. whenever a single constant is required at several locations)?

**Comment by cvuosalo** [comment]
@mundim Yes, each constant should have appropriate units, like:
```
<Constant name="RP_210_Left_Sec_Rot_Angle" value="8*deg"/>
```

**Comment by mundim** [comment]
Can you tell me if definitions like:
`<Constant name="RP_Front_Frame_Hole_Bottom_size" value="[RP_Front_Frame_Hole_Bottom_diagonal]*sqrt(2)*0.5"/>`

allowed?

**Comment by mundim** [comment]
I hope all unit problems were solved. I made a mistake and had to test everything again...

**Comment by cvuosalo** [comment]
@mundim  Have your latest changes passed the `DetectorDescription/DDCMS` unit tests?

**Comment by cvuosalo** [comment]
@mundim Concerning `sqrt` in XML constant definitions, I think it is allowed because it appears in many other XML files.

**Comment by mundim** [comment]
> @mundim Have your latest changes passed the `DetectorDescription/DDCMS` unit tests?
You means the script you mentioned: `python UnitsCheck.py cms.xml`?\

If so, yes. The only complaints reported were numbers in the name without unit, which I ignored.

**Comment by smuzaffar** [comment]
You need to checkout these 3 DetectorDescription/DDCMS Geometry/DTGeometryBuilder SimG4Core/DD4hepGeometry packages in your local dev area  and run scram build runtests to see if your changes actually fixed these tests

**Comment by mundim** [comment]
> scram build runtests

It failed. Investigating the problem... thanks @smuzaffar

**Comment by mundim** [comment]
The tests reports:
`ERROR ----> Handle_t::attr_ptr: Element [PosPart] has no attribute of type 'copyNumber'`

I found in the files several blocks like
`        <PosPart>
...
        </PosPart>
`

Instead of 
`        <PosPart copyNumber="3"> ...  </PosPart>`

Some cases, there is the same copyNumber for different block. So, I have two question (I hope they make sense):
1 - does this number needs to be different?
2 - which number I should put in the missing block?

Cheers

**Comment by cvuosalo** [comment]
@mundim Identical PosParts should have different copy numbers. Copy numbers should start from 1 and go up from there. PosParts that are different from each other can probably have the same copy number.

See this page for some background info: https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideGeomDevelopersXMLTutorial

**Comment by mundim** [comment]
I run the tests as recommended by @smuzaffar, corrected the missing copyNumber in PosPart (assigning 1 to all of them since they are all different). Apparently the tests went fine, it prints a huge amount of printouts, filtering it, there is:

---> test test2026Geometry succeeded
---> test testDD4hepExpandedView succeeded
---> test testDD4hepCompactView succeeded
---> test testDD4hepFilteredView succeeded
---> test testDD4hepDDSolidShapes succeeded
---> test DetectorDescriptionDDCMSTestDriver succeeded
---> test testDD4hepFilter succeeded
---> test testDD4hepExpandedNodes succeeded
---> test testDD4hepDDSolid succeeded
---> test testDD4hepDDSolidLegacyShapes succeeded
---> test DD4hepGeometryTestDriver succeeded
---> test GeometryDOMCount succeeded
---> test GeometryDTGeometryBuilderTestDriver succeeded

There are some errors but they don't look related to PPS, as

`===== Test "cmsRun testShapes.py" ====
Begin processing the 1st record. Run 1, Event 1, LumiSection 1 on stream 0 at 24-Jun-2020 05:07:55.674 CEST
PersistencyIO    INFO  +++ Set Streamer to dd4hep::OpaqueDataBlock
CompactLoader    INFO  +++ Processing compact file: /afs/cern.ch/work/m/mundim/public/PPS/CMSSW_11_2_X_2020-06-16-2300/src/DetectorDescription/DDCMS/data/cms-test-shapes.xml with flag (null)
DD4CMS           INFO  +++ Processing the CMS detector description file:///afs/cern.ch/work/m/mundim/public/PPS/CMSSW_11_2_X_2020-06-16-2300/src/DetectorDescription/DDCMS/data/cms-test-shapes.xml
Detector         INFO  *********** Created World volume with size: 10100 10100 45000
PlacedVolume     ERROR ++ Attempt to add already exiting node box1_14
PlacedVolume     ERROR ++ Attempt to add already exiting node box1_15
PlacedVolume     ERROR ++ Attempt to add already exiting node box1_16
PlacedVolume     ERROR ++ Attempt to add already exiting node box1_17
PlacedVolume     ERROR ++ Attempt to add already exiting node box1_18
Detector         INFO  +++ Patching names of anonymous shapes....
DDDefinition     INFO  +++ Finished processing file:///afs/cern.ch/work/m/mundim/public/PPS/CMSSW_11_2_X_2020-06-16-2300/src/DetectorDescription/DDCMS/data/cms-test-shapes.xml
`

**Comment by silviodonato** [comment]
please test

**Comment by smuzaffar** [comment]
test parameters
- addpkg = Geometry/DTGeometryBuilder, DetectorDescription/DDCMS, SimG4Core/DD4hepGeometry

**Comment by smuzaffar** [comment]
please test

**Comment by mundim** [comment]
> The tests are being triggered in jenkins.
> Test Parameters:
> 
>     * **EXTRA_CMSSW_PACKAGES** = Geometry/DTGeometryBuilder,DetectorDescription/DDCMS,SimG4Core/DD4hepGeometry
> 
>     * CMSSW_11_2_X_2020-06-23-2300/slc7_amd64_gcc820: https://cmssdt.cern.ch/jenkins/job/ib-run-pr-tests/7313/console Started: 2020/06/24 11:50

Sorry, it was not my intention to include these packages in the branch. Is it a problem?

**Comment by smuzaffar** [comment]
No it is not a problem, you did the right thing.
As we know that the unit tests of these 3 cmssw packages depend on the changes of this PR, so we wanted to make sure that PR test actually checkout these packages and run tests. That is why  I added the extra test parameter here.

**Comment by smuzaffar** [comment]
by the way, looks like you latest changes have fixed the issue.

**Comment by ianna** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Comment by mundim** [comment]
Thanks a lot to everyone who helped on this.

**Pull request merged**
