### PR TITLE
Validation RecoEgamma esconsumes modifications

### PR DESCRIPTION
**Pull request by archiron**
#### PR description:
Part of #31061.
Migrated to esConsumes the Validation RecoEgamma package (electrons part).

#### PR validation:

all tests passed :
37 36 35 26 16 4 1 1 1 tests passed, 0 0 0 0 0 0 0 0 0 failed

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

@beaudett @guitargeek

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+1
Thanks @archiron !!

**Comment by qliphy** [comment]
@archiron  It seems there are yet additional places to be updated:
https://github.com/cms-sw/cmssw/blob/ddcdca214b23b1da5ef46304b294bccf42ed65b0/Validation/RecoEgamma/plugins/TkConvValidator.cc#L1312
as you can read from the clang-tidy checks:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-7548de/15711/llvm-analysis/cmsclangtidy.txt

**Comment by jfernan2** [comment]
Oooops, sorry I missed them...

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
Sorry @archiron but there seems to be some warnings still:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-7548de/15760/llvm-analysis/esrget-sa.txt

**Comment by qliphy** [comment]
@jfernan2  The warnings are on code (Validation/RecoEgamma/plugins/PhotonValidator.cc) not touched here, and can be ignored for this PR.

**Comment by archiron** [comment]
Hi, 
I did not include the photons modifications because I thought some people could do that, but @guitargeek made a great work and I can include the photons modifications into this PR if you want.

**Comment by jfernan2** [comment]
I'd vote for including it in this PR

**Comment by qliphy** [comment]
> I'd vote for including it in this PR
Agreed on this.

**Comment by jfernan2** [comment]
Thanks @archiron 
There is some conflict yet though

**Comment by archiron** [comment]
about : There are other open Pull requests which might conflict with changes you have proposed:

File Validation/RecoEgamma/plugins/ElectronMcFakeValidator.cc modified in PR(s): #33666
File Validation/RecoEgamma/plugins/ElectronMcSignalValidator.cc modified in PR(s): #33666

there is no conflict with the #33666 modifications. Its concern an other part of the files (filling the histos) and not the esConsumes modifications.

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
