### PR TITLE
[NanoAOD, JMENano] Backport of #42728 (Updates for Nano and JMENano), #42670 (Fix typos in jetsAK4 CHS and Puppi tables) and #42898 to 13_2_X

### PR DESCRIPTION
**Pull request by nurfikri89**
Backport of #42728, #42670 and #42898. This backport is needed for 2022 and 2023 JMENano production with `13_0_X` MiniAODs.

**Original PR description from #42728:**

This PR aims to add changes related to NanoAOD, JMENanoAOD and ensuring consistency of PuppiProducer instances when processing MiniAODs for production and analysis. The following changes are made:

**NanoAOD**
These changes are intended to be for the next NanoAOD campaign (`v13`?)
- Add missing `RUN3WINTER22PUPPIrunsBCDEprompt` JetID version for jets.
- Add (puppi-weighted) charged and neutral multiplicities for jets.
- Add HF energy fractions for AK4 jets.
- Add energy fractions for AK8 jets.
- Add jet area for subjets. Fix the documentation of subjet collection.

**JMENanoAOD**
- Add Run-3 JetIDs.
- Remove AK8CHS jet collection.
- Reduce content for AK4CHS collection by removing PUID/QGL tagger inputs and most flavour-tagging discriminants.
- Increase pT thresholds for AK4CHS, AK4GEN, AK8GEN.
- Rename some branches.
- JMENano size estimates:
Data: 3.52 kb/evt (c.f 1.96 kb/evt central Nano). Tested with 5000 events of Run2022C JetMET dataset.
MC: 4.95 kb/evt (c.f 2.93 kb/evt central Nano). Tested with 5000 events of Summer2022 TT 1-lepton.

**PuppiProducer consistency**
- Improve `setupPuppiForPackedPF()` in `jetTools.py` by adding `packedpuppiNoLep` instance.
- In `runMETCorrectionsAndUncertainties.py`, make it optional to provide a different `PuppiProducer` module label rather than stick to a hard-coded label (`puppiNoLep`). Set the previously hard-coded label as the default option.

**Original PR description from #42670 :**
This pull request fixes a few typos in the jetsAK4 CHS and Puppi tables:

(1) Fix to the `btagRobustParTAK4CvB` definition: the previous definition was using the `pfDeepFlavourJetTags` instead of pfParticleTransformerAK4JetTagsfor the `probbb` and `problepb` scores in the denominator. This affects both the CHS and Puppi AK4 jet tables, and probably(?) affects the official production.

(2) Fix to the `nanoAOD_addDeepInfoAK4()` function in the `jetsAK4_Puppi_cff.py`: this should only affects private/custom productions.

**Original PR description from #42728:**
This PR updates the taggers for AK4 Puppi and CHS jets in JMENano production. All the relevant taggers for AK4 Puppi jets are set to be computed for the newly reclustered collection and only one tagger is made available for AK4 CHS jets (since it is a backup collection). 

#### PR validation:
- passes the standard runTheMatrix test: `runTheMatrix.py -l limited -i all --ibeos`
- passes the following NanoAOD workflows: `runTheMatrix.py -i all --ibeos -l 2500.0,2500.001,2500.002,2500.01,2500.011,2500.012,2500.1,2500.2,2500.21,2500.3,2500.31,2500.4`

### CODE REVIEW

**Comment by simonepigazzini** [comment]
enable nano

**Comment by simonepigazzini** [comment]
please test

**Comment by simonepigazzini** [comment]
please test

(suspect spurious failure)

**Comment by simonepigazzini** [comment]
please test

**Comment by nurfikri89** [comment]
Hi @mandrenguyen & @jfernan2, apologies for pinging here as we would like to get this merge for JMENano production. Is there anything from the `reconstruction` side?

**Comment by mandrenguyen** [comment]
+reconstruction

**Comment by rappoccio** [comment]
+1

* Unit test failures are unrelated to this PR

**Comment by rappoccio** [comment]
merge

**Pull request merged**
