### PR TITLE
Remove depreciated DNN-based tau-Ids [12_4_X]

### PR DESCRIPTION
**Pull request by mbluj**
#### PR description:

This PR is to remove depreciated DNN-based tau-Ids: DPFIsolation (a dedicated module) and DeepTauID v1 (a v1-related part of the deepTauId module). These tau-Ids was superseded by deepTauID v2 and are not present in official workflows.

In addition two outdated and unused modules are also removed.

No changes are expected.

This PR is accompanied by another PR to cms-data removing model files of removed DNN-based tau-Ids (https://github.com/cms-data/RecoTauTag-TrainingFiles/pull/9) or its updated version https://github.com/cms-data/RecoTauTag-TrainingFiles/pull/10.

This is backport of #38063.

#### PR validation:

Limited matrix tests successful in original PR (#38063). Not repeated here as differences between master and 12_4_X are minimal (can be done on request).

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Backport of #38063.

Removal of outdated code and (more importantly) reduction of size of cms-distr thanks to removal of old model files when https://github.com/cms-data/RecoTauTag-TrainingFiles/pull/9 merged. Finally it enables adding to cms-distr of 12_4_X new model files of newest deepTauID v2p5 requested in https://github.com/cms-data/RecoTauTag-TrainingFiles/pull/10.

### CODE REVIEW

**Comment by jpata** [comment]
Sorry if I missed it, but where was the backport requested and what's the motivation?

**Comment by mbluj** [comment]
> Sorry if I missed it, but where was the backport requested and what's the motivation?

The main motivation of the backport is to remove unused code and synchronize cms-data used by 12_4_X and master (12_5_X) which a) removes depreciated model files (size reduction of cms-distr) and b) enables coherent update of model files of deepTau v2p5 (on top of removal of the depreciated ones). However, if you think it that b) (most important for MC production with 124X) is not worth of merging this PR it can be closed. Then we will prepare different update of cms-data with updated deepTau v2p5 model files. I hope this comment is not confusing...

**Comment by clacaputo** [comment]
Hi @mbluj , so the reason for the bp is intended to remove code not used in `cmssw` so that also the related model can be removed from `12_4_X cms-distr`m right? Please, correct me if I'm wrong.

If so, I don't see any problem with doing so, maybe @cms-sw/orp-l2 has a different opinion

**Comment by mbluj** [comment]
> Hi @mbluj , so the reason for the bp is intended to remove code not used in `cmssw` so that also the related model can be removed from `12_4_X cms-distr`m right? Please, correct me if I'm wrong.

It is correct.

**Comment by qliphy** [comment]
> Hi @mbluj , so the reason for the bp is intended to remove code not used in `cmssw` so that also the related model can be removed from `12_4_X cms-distr`m right? Please, correct me if I'm wrong.
> 
> If so, I don't see any problem with doing so, maybe @cms-sw/orp-l2 has a different opinion

Fine with me under the context

**Comment by clacaputo** [comment]
@cmsbuild please test

**Comment by jpata** [comment]
enable profiling

**Comment by jpata** [comment]
@cmsbuild please test with https://github.com/cms-data/RecoTauTag-TrainingFiles/pull/10

**Comment by jpata** [comment]
@gartung I was looking at the profiling here and it seems incomplete

https://cmssdt.cern.ch/SDT/cgi-bin/igprof-navigator/CMSSW_12_4_X_2022-06-06-1100/el8_amd64_gcc10/profiling/11834.21/PR-9279aa/25307/igprofMEM_step3.19 -> ~54MB

http://cms-reco-profiling.web.cern.ch/cms-reco-profiling/cgi-bin/igprof-navigator/releases/CMSSW_12_4_0_pre4/11834.21/step3/mem_live.399 -> 1.9GB

is this expected?

**Comment by gartung** [comment]
@jpata  The igprof used for CMSSW_12_4_0_pre4 used the older version of igprof.  It needs to be tested with the newer version of igprof. It looks like the newer version of igprof was also used in the CMSSW_12_4_X IB.

**Comment by jpata** [comment]
OK, thanks. Let's skip the profiling here.

**Comment by jpata** [comment]
enable none

**Comment by jpata** [comment]
@cmsbuild please test

Yes, the reco changes are from the data PR that is unrelated to this. Running again should return no changes.

**Comment by mbluj** [comment]
> @cmsbuild please test
> 
> Yes, the reco changes are from the data PR that is unrelated to this. Running again should return no changes.

Yes, I confirm, three tauIDs can be changed by the updated model files added in cms-data/RecoTauTag-TrainingFiles#10, while the rest should be unchanged.  Test repeated without updated model is expected to show no changes.

**Comment by clacaputo** [comment]
It seems the profiling job is stuck, but the comparison job ended successfully and plots can be checked here: https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_4_X_2022-06-07-2300+9279aa/50849/validateJR.html

As expected, the PR is not introducing any reco changes

**Comment by clacaputo** [comment]
@cmsbuild please abort

**Comment by clacaputo** [comment]
test parameters:

- enable_test = none

**Comment by clacaputo** [comment]
@cmsbuild please test

**Comment by smuzaffar** [comment]
> As stated in [#38164 (comment)](https://github.com/cms-sw/cmssw/pull/38164#issuecomment-1150136249) , there are NO reco differences after test this PR without [cms-data/RecoTauTag-TrainingFiles#10](https://github.com/cms-data/RecoTauTag-TrainingFiles/pull/10), but it seems that a profiling job pending is not letting the checks to finish. @smuzaffar , could you please check? It seems the bot is ignoring `enable none` command
> 
> I'm ready to sign the PR as soon as the test finish

@clacaputo , there is a known issue with bot that it does not reset status for tests which were initially run (e.g. in this case `profiling`) but in latest tests they are dropped.

**Comment by clacaputo** [comment]
+reconstruction:

- backport of #38063, code changes are in line with the original pr
- no reco changes

**Comment by qliphy** [comment]
+1
tested also with https://github.com/cms-sw/cmsdist/pull/7918

**Pull request merged**
