### PR TITLE
fix for displaced susy relval production (TRK and EXO validation of displaced tracks)

### PR DESCRIPTION
**Pull request by jalimena**
#### PR description:

This PR further updates the "DisplacedSUSY" relvals, for tracking and exotica validation of displaced tracks, on top of #31692 , which introduced a problem with WF 1355. In this PR, the original WF 1355 is re-implemented, and only the upgrade WFs related to DisplacedSUSY are changed wrt CMSSW_11_2_0_pre7.

#### PR validation:

This PR passes the basic unit tests and code quality checks. I have also successfully tested WFs 1355.0 and 23324.0 locally.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

not a backport

FYI @mtosi @vmariani @elusiani @Fernance @lowette @nsaoulid @kdipetri @mcitron @jandrea @blochd @mmasciov @chayanit @srappocc

### CODE REVIEW

**Comment by kpedro88** [comment]
please test

**Comment by chayanit** [comment]
+1

**Comment by agrohsje** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade

**Comment by qliphy** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
