### PR TITLE
Remove Totem Detectors from 2018 Geometry Scenarios

### PR DESCRIPTION
**Pull request by ianna**
* As discussed at Simulation meeting Totem detectors were removed for 2018 run:
https://indico.cern.ch/event/714398/contributions/2938076/attachments/1618558/2573716/VI20180316sum.pdf

@civanch - FYI

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by civanch** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Comment by fabiocos** [comment]
@ianna @civanch this is effectively a bug fix, we were simulating a detector that does not exist. The fact that the 2018 simulation test 10824 is unchanged is due to the fact that in the GEN-SIM workflow the geometry is effectively downloaded from the GT, in this PR we have just the description that is then injected into the GT, right?

The change is needed to have realistic 10_1_X POG MC samples to prepare for the physics simulation production of this summer, as discussed with @franzoni and @klute that I understand agree, but in principle this is removing material in front of HF and might have an effect on the response, to be checked

**Comment by ianna** [comment]
Yes, correct

**Comment by civanch** [comment]
@fabiocos , yes, this is bug fix for HF as #22145 . In my understanding, this PR should have even less impact on HF.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
