### PR TITLE
Phase2-hgx353 add a new scenario 2026D109 utilizing V18 version of HGCAL after removing some of the gaps

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Add a new scenario 2026D109 utilizing the V18 version of HGCAL after removing some of the gaps

#### PR validation:

Use the runTheMatrix test workflow 29234.0

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

To be back ported to 14_0_X

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
+geometry

**Comment by srimanob** [comment]
@cmsbuild please test workflow 29234.0

**Comment by bsunanda** [comment]
@sunilUIET @srimanob Please approve this. I would like to backport this to 14_0_X

**Comment by srimanob** [comment]
Hi, @emiglior @cms-sw/trk-dpg-l2 

I see a warning,
```
%MSG-w UnexpectedMagneticFieldUsingNonIdealPixelTemplate:   SiPixelTemplateDBObjectESProducer:siPixelTemplateDBObjectESProducer@callESModule  09-Feb-2024 08:03:38 CET Run: 1 Event: 1
Magnetic field is 3.8112 Template Magnetic field is 0
%MSG
```
in step-3 (RECO) of D109. Is this because of `T35`? I don't see this warning in D98.

**Comment by mmusich** [comment]
@srimanob, let me take this one.

> in step-3 (RECO) of D109. Is this because of T35? I don't see this warning in D98.

so, it's a bit convoluted, but this happens because of the fact that in the BPix layer1 (both for `T35` included in `D109` *and* `T33` included in `D98`) there are 3D sensors and for these there is no Lorentz Angle simulated (at least in the traditional sense). 
Therefore, in the pixel templates for that detector region the notion that the Lorentz Angle should be zero is "encoded" via setting the magnetic field to zero as well (which is the only way in which it could happen in the current detector), and this is in contradiction with the value of the B-field strength used in the reconstruction, thus the error message. 
For `T33` (which ultimately inherits from `T25`) a special "tweaked" payload was provided in order to encode a zero Lorentz drift but non-zero B-field in the header, but this apparently was not done for `T35`. 
See below snapshot of the template headers obtained via payload inspector:
For `T35`:

image

vs for `T25` / `T33`
image

Notice the value of the "B-field" parameter in the first column.
That said it should be just a warning issued here:

https://github.com/cms-sw/cmssw/blob/4a6d7e831d09c01a92d2381c319f1424a524e651/CalibTracker/SiPixelESProducers/plugins/SiPixelTemplateDBObjectESProducer.cc#L69-L71

with no consequences for reconstruction, but I guess would be better to clean it up.

**Comment by srimanob** [comment]
+Upgrade

New D109 runs fine. The warning message shown up in RECO is explained in https://github.com/cms-sw/cmssw/pull/43903#issuecomment-1935639667. I will leave this to tracker to clean it up in later PR.

**Comment by bsunanda** [comment]
@sunilUIET Please approve this

**Comment by sunilUIET** [comment]
+pdmv

**Comment by bsunanda** [comment]
@rappoccio, @antoniovilela  Please merge this PR

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
