### PR TITLE
ECAL : DB PayloadInspector modification

### PR DESCRIPTION
**Pull request by depasse**
#### PR description:

ECAL : DB PayloadInspector : modification for 2024 of limits for display of EcalPedestals plots (due to noise increase with integrated luminosity)

#### PR validation:

Tested in local with CondCore/Utilities/scripts/getPayloadData.py : Json file produced on a recent iov

### CODE REVIEW

**Comment by thomreis** [comment]
please test

**Comment by thomreis** [comment]
type ecal

**Comment by depasse** [comment]
Yes it is wanted.   Ecal Endcaps (VPTs) are very stable (while APDs in Ecal Barrel becomes more and more noisy with irradiations).
Nevertheless, window limits for endcaps were enlarged, mainly due to very high eta EE channels  (see for example plots EEped1D in https://ecaltrg.web.cern.ch/ecaltrg/users/pierre/pedestals/375600_375217/ )

De : Andrea Perrotta ***@***.***>
Envoyé : jeudi 9 novembre 2023 15:40
À : cms-sw/cmssw ***@***.***>
Cc : Pierre Depasse ***@***.***>; Mention ***@***.***>
Objet : Re: [cms-sw/cmssw] ECAL : DB PayloadInspector modification (PR #43234)


@perrotta commented on this pull request.

________________________________

In CondCore/EcalPlugins/plugins/EcalPedestals_PayloadInspector.cc<https://github.com/cms-sw/cmssw/pull/43234#discussion_r1388101927>:

>        float emin[kGains] = {1.5, 0.8, 0.4};

-      float emax[kGains] = {3.0, 2.0, 1.0};  //  11/01/2023

+      float emax[kGains] = {3.0, 2.0, 1.0};  //  11/11/2023

Just checking: for this line you are updating the data, but not the values of the parameters. Is it wanted?

**Comment by thomreis** [comment]
please test

**Comment by perrotta** [comment]
+db

**Comment by rappoccio** [comment]
+1

**Pull request merged**
