### PR TITLE
Additional Photos options

### PR DESCRIPTION
**Pull request by mseidel42**
#### PR description:

Add additional options for Photos++: Enabling of pair production (`setPairEmission`) and ability to continue after rare erroneus events (`setStopAtCriticalError`) that would halt production otherwise.

#### PR validation:

d02-x01-y01
DeltaR_ptweighted
Ptgamma

> @qliphy Please see here the electron multiplicity in Z->mu+mu- events with pair production on/off. Events with 1/2 electrons (= 1 pair) are suppressed by one order of magnitude if pair production is turned off.
> 
> image
> 
> It seems Photos creates maximal 1 pair while Pythia can do more.

### CODE REVIEW

**Comment by qliphy** [comment]
please test

**Comment by qliphy** [comment]
@intrepid42    Can you elaborate a bit the legends?  How can I see the comparisons between the cases with setPairEmission on and off?

**Comment by intrepid42** [comment]
> @intrepid42 Can you elaborate a bit the legends? How can I see the comparisons between the cases with setPairEmission on and off?

The plots compare Photos ++ single, double, quatro and exponential emission modes with Pythia and QED FSR off.

I did not check setPairEmission on and off, I will submit some jobs for that and post the plots here!

**Comment by intrepid42** [comment]
@qliphy Please see here the electron multiplicity in Z->mu+mu- events with pair production on/off. Events with 1/2 electrons (= 1 pair) are suppressed by one order of magnitude if pair production is turned off.

image

It seems Photos creates maximal 1 pair while Pythia can do more.

**Comment by qliphy** [comment]
Look nice to me. Thanks @intrepid42.

**Comment by qliphy** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
