### PR TITLE
Phase2-hgx341H Modify several test scripts in Geometry/HGCalCommonData to test geometry versions beyond the first V17

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Modify several test scripts in Geometry/HGCalCommonData to test geometry versions beyond the first V17

#### PR validation:

Use the test scripts on the existing codes

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

Modify of test scripts, no change is expected.

**Comment by perrotta** [comment]
+1

**Pull request merged**
