### PR TITLE
Fix comp error in CaloOnlineTools/HcalOnlineDb

### PR DESCRIPTION
**Pull request by mrodozov**
Fix this failure: https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc7_amd64_gcc700/CMSSW_10_6_CLANG_X_2019-03-07-2300/CaloOnlineTools/HcalOnlineDb

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by fabiocos** [comment]
@ggovi could you please check?

**Comment by ggovi** [comment]
+1

**Comment by ggovi** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
