### PR TITLE
[Pixel 3D digitizer] Boundary row/col check in digitizer

### PR DESCRIPTION
**Pull request by duartej**
#### PR description:
This PR fixes the issue spotted and described at #30215 .

The digitizer checks that the estimated row/col for each group of carriers is inside the expected limits. More details at  #30215

#### PR validation:
Check successfully with workflows  26234.0 and 24834.0 (geometries 2026D55 and 2026D54, IT with 3D pixels).

### CODE REVIEW

**Comment by kpedro88** [comment]
please test

**Comment by kpedro88** [comment]
+upgrade

**Comment by civanch** [comment]
+1

**Comment by silviodonato** [comment]
please test 23434.1001

**Comment by silviodonato** [comment]
please test workflow 23434.1001

**Comment by silviodonato** [comment]
+1

**Pull request merged**
