### PR TITLE
itervalues and iteritems replaced by six for python3 compatibility 

### PR DESCRIPTION
**Pull request by davidlange6**
remake of #23574 with translation bugs fixed (hopefully

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
please test

[the unit test errors are unrelated to my changes]

**Comment by davidlange6** [comment]
Your PR is unmergeable. Please have a look and possibly rebase it.

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
Your PR is unmergeable. Please have a look and possibly rebase it.

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
again the unit test failure will not be related to this PR - so please give any comments you have so that we avoid the infinite rebase cycle:)

**Comment by perrotta** [comment]
please test
(just to clean up the comparisons)

**Comment by Dr15Jones** [comment]
please test

**Comment by perrotta** [comment]
+1
- Technical: it applyes the six library to allow Python 2 and Python 3 compatibility 
- Implementations corresponds to what expected
- Jenkins tests pass: unit test testPythonParameterSet failure is not to be related to this PR

**Comment by fabiocos** [comment]
+operations

changes to Configuration packages looks consistent with the PR target

**Comment by fabiocos** [comment]
@davidlange6 @Dr15Jones do you understand what is crashing the Framework unit test?

**Comment by Dr15Jones** [comment]
@fabiocos this happens because it requires the file to come from what it thinks is the working area ($CMSSW_BASE) but the way pull requests are tested, that test fails if the package was checked out.

**Comment by Dr15Jones** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by smuzaffar** [comment]
please test
cms-bot had an issue with unittests, this should be fixed now.

**Comment by fabiocos** [comment]
@arunhep @lpernie @Martin-Grunewald @fabozzi @prebello @jfernan2 @dmitrijus @rekovic @ggovi  @silviodonato could you please check and sign or comment?

**Comment by dmitrijus** [comment]
+1

**Comment by Martin-Grunewald** [comment]
+1

**Comment by fabozzi** [comment]
+1

**Comment by perrotta** [comment]
@smuzaffar 
```
Comparison not run due to Build errors (RelVals and Igprof tests were also skipped)
```
Did anything go wrong with the tests, or is it just a spurious message, given https://github.com/cms-sw/cmssw/pull/23609#issuecomment-400279167 ?

**Comment by smuzaffar** [comment]
please test
this was due to header consistency check which failed due to internal compiler errors. For now I have disabled it and re-starting the tests

**Comment by davidlange6** [comment]
hi @fabiocos - being a while with no comments on this PR, I suggest pushing it forward after pre6 (as we already discussed) unless alca/db/l1 make comments in the next hours... there are a number of steps in this migration

**Comment by davidlange6** [comment]
why?

**Comment by fabiocos** [comment]
@arunhep in my understanding the failing unit test is expected to fail here, the rest looks accidental. I will rerun the test once more for cleanness, but then we should merge this PR to avoid risks of conflicts. Please comment in case you have concerns.

@ggovi @rekovic please check and sign or comment. By tomorrow I plan to merge otherwise this PR so as we move forward with the needed work.

**Comment by davidlange6** [comment]
I fail to see what we hope to learn by testing this PR again.  [or is it standard current practice to test prs every few days?]

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Pull request merged**
