### PR TITLE
Updated CosmicRateAnalyzer: MagField & Hits added, deleted latency

### PR DESCRIPTION
**Pull request by saumyaphor4252**
Updated the Cosmic Rate Analyzer
- Magnetic field and Hits variables are added for Events. 
- Latency (not coming into use) removed.  
- cfi path location updated in Config File.

### CODE REVIEW

**Comment by mmusich** [comment]
@saumyaphor4252 thanks for this.
Can you:
  * change the title of the PR to something more meaningful (e.g.: Updated CosmicRateAnalyzer: MagField & Hits, deleted latency)
  * run the mandatory code-format patches with: `scram b code-format` in your local checkout and push to this branch?

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
@yuanchao, @christopheralanwest 
would it be possible to process the review of this PR at earliest convenience, such at I can rebase  #32301 once this is merged?
Thanks!

**Comment by christopheralanwest** [comment]
+1

- Only differences seen in comparison tests are for workflow 11642.911, which have been seen in other PRs and are unrelated to the changes introduced in this PR
- Deprecated method for accessing EventSetup will be corrected in a dedicated followup PR, #32301

**Comment by qliphy** [comment]
+1

**Pull request merged**
