### PR TITLE
Stand-alone tracker rechits validation cfg, root macro

### PR DESCRIPTION
**Pull request by wmtford**
Changes to test directories only.  Add a cfg that produces a RelVal-format root file with RecHit validation histograms from strips, and from pixels whether phase0 or phase1.  Add also a root macro to compare histograms across pairs of root files.

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
