### PR TITLE
fix run-by-run TkAlignment PV Validation submission script in case of extra conditions

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

Title says it all, discovered during the 13.6TeV alignment campaign when using updated pixel templates (cf [here](https://cms-talk.web.cern.ch/t/new-1d-and-2d-templates/13982) )

#### PR validation:

Private

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Not a backport, but will need to be backported

### CODE REVIEW

**Comment by mmusich** [comment]
type trk, bug-fix

**Comment by tvami** [comment]
@cmsbuild , please test
 * I doubt anything is testing this specific change, but ok...

**Comment by mmusich** [comment]
>    I doubt anything is testing this specific change, but ok...

your doubt is not justified:

https://github.com/cms-sw/cmssw/blob/aef58e8499cb1c19f432d4444ce4910099145102/Alignment/OfflineValidation/test/BuildFile.xml#L18-L21

https://github.com/cms-sw/cmssw/blob/aef58e8499cb1c19f432d4444ce4910099145102/Alignment/OfflineValidation/test/testSubmitters.sh#L4-L5

**Comment by tvami** [comment]
> your doubt is not justified:

Ahh great! This is the case when I'm happy to be wrong :)

**Comment by tvami** [comment]
+alca
 * unit test passes
 * jenkins tests pass (MTD and MsgLogger diffs only)
 * PR according to the desc

**Comment by perrotta** [comment]
+1

**Pull request merged**
