### PR TITLE
Phase2-hgx329E Remove obsolete FastTimer code from Geometry/HCalCommonData

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Remove obsolete FastTimer code from Geometry/HCalCommonData

#### PR validation:

Use the runTheMatrix test workflows

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
+geometry

**Comment by srimanob** [comment]
+Upgrade

**Comment by perrotta** [comment]
+1

**Pull request merged**
