### PR TITLE
[12_3_X] Update the AlCaRecoMatrix for Run 3

### PR DESCRIPTION
**Pull request by francescobrivio**
#### PR description:
Backport of #37590
This PR updates the AlCaRecoMatrix to be used for Run 3:
- Moved the AlCaRecoMatrix[2018|2017|2016|2015] to AlCa/doc/pastAlCaRecoMatrix.py since they are not really used anywhere in CMSSW, but only kept for documentation purposes
- Updated the AlCaRecoMatrix to the values for Run 3, as described in the [AlCaRecoMatrix twiki for 2022](https://twiki.cern.ch/twiki/bin/view/CMS/AlCaRecoMatrix#COLLISIONS_2022)

#### PR validation:
Tested with:
`runTheMatrix.py -l limited -j 16 --ibeos -t 4`

#### Backport:
Backport of #37590

### CODE REVIEW

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
+alca

**Comment by francescobrivio** [comment]
urgent

 - for the next 12_3_X release

**Comment by mmusich** [comment]
please test

**Comment by tvami** [comment]
> [cmsbuild](https://github.com/cmsbuild) commented [5 minutes ago](https://github.com/cms-sw/cmssw/pull/37671#issuecomment-1110110702)
>+1

oh this is surprising

**Comment by tvami** [comment]
test parameters:
  - workflow_threading = 1001.2
  - enable_test = threading

**Comment by makortel** [comment]
I don't see 1001.2 being run in the tests https://github.com/cms-sw/cmssw/pull/37671#issuecomment-1110110702
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-f63eae/24229/runTheMatrix-results/

**Comment by tvami** [comment]
Hi Matti, yes, you are right, so it seems https://github.com/cms-sw/cmssw/pull/37671#issuecomment-1109867653 didnt take effect?

**Comment by tvami** [comment]
@cmsbuild , please test workflow 1001.2

**Comment by makortel** [comment]
> Hi Matti, yes, you are right, so it seems [#37671 (comment)](https://github.com/cms-sw/cmssw/pull/37671#issuecomment-1109867653) didnt take effect?

The comment had thumbs up so I would have expected the bot to run it. I have no idea what happened.

**Comment by tvami** [comment]
@cmsbuild , please test with https://github.com/cms-sw/cmssw/pull/37720

**Comment by perrotta** [comment]
+1

**Pull request merged**
