### PR TITLE
Run3-hcx354 Modify the DetId fo ZDC to accommodate the changes that happened during Run3 and some provision for the future

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Modify the DetId fo ZDC to accommodate the changes that happened during Run3 and some provision for the future

#### PR validation:

Use the runTheMatrix test workflows

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

To be back ported to 13_3_X

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by smuzaffar** [comment]
Milestone for this pull request has been moved to CMSSW_14_0_X.Please open a backport if it should also go in to CMSSW_13_3_X.

**Comment by bsunanda** [comment]
Now back ported to 13_3_X with PR #43206

**Comment by bsunanda** [comment]
The unit test failure has to happen because this changes the DetID format and in the comparison, it compares the raw ID values. The test should be modified to compare the rest of the fields.

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by perrotta** [comment]
(Since I made the comment on the backported PR, let me repeat it here)
@bsunanda with your latest commit you inhibited a unit test that did not succeed: aren't you hiding possible problems, as such?
If the new output of that test is the one that must be expected, wouldn't it be preferable to modify also the reference txt file, so that the test can succeed, instead of removing the check?

**Comment by bsunanda** [comment]
The unit test should compare the public components of the DetID: zside, section, depth, channel and the PF parameters rather than in addition the rawID value. This requires changes in the code as well as the one in the data area which should avoid the rawID value (which is supposed to be a private member of the DetID). Once the unit test is corrected (both code and data) it will be activated again.
________________________________

**Comment by perrotta** [comment]
> The unit test should compare the public components of the DetID: zside, section, depth, channel and the PF parameters rather than in addition the rawID value. This requires changes in the code as well as the one in the data area which should avoid the rawID value (which is supposed to be a private member of the DetID). Once the unit test is corrected (both code and data) it will be activated again.

Thank you @bsunanda 
Do you plan to correct the unit test already in this PR (and, if not: why)?

**Comment by bsunanda** [comment]
Not in this PR. It has to be done in a subsequent PR which needs modification not just CMSSW code but also the CMSData [art
________________________________

**Comment by perrotta** [comment]
> Not in this PR. It has to be done in a subsequent PR which needs modification not just CMSSW code but also the CMSData

Why not to apply modifications not just CMSSW code but also the CMSData already in this PR?

**Comment by civanch** [comment]
@perrotta , I would look on this PR differently: it is OK with the validation, so may be merged.  Unit tests will be modified basing on this merged PR.

**Comment by bsunanda** [comment]
I cannot fix the issue in this PR. It needs to change in the cms-data with a different PR and then modify the test in CMSSW area. It is better to merge this PR first
________________________________

**Comment by bsunanda** [comment]
Please merge this PR. Igor is preparing a second PR #43220 which will later enable the Unit test. But this PR is to be merged first.
________________________________

**Comment by perrotta** [comment]
> Please merge this PR. Igor is preparing a second PR #43220 which will later enable the Unit test. But this PR is to be merged first.

Thank you @igv4321 
@bsunanda please revert the commit that comments out the test in CondTools/Hcal/test/BuildFile.xml. That unit test can remain broken in the IB until #43220 is merged (and you won't need the db signature any more)

**Comment by bsunanda** [comment]
Brought back the unit test. Please test this with Igor's PR

**Comment by perrotta** [comment]
please test with https://github.com/cms-sw/cmssw/pull/43220

**Comment by civanch** [comment]
please test

**Comment by abdoulline** [comment]
Unit test broken as expected, as tested without  https://github.com/cms-sw/cmssw/pull/43220 .

**Comment by perrotta** [comment]
please test with https://github.com/cms-sw/cmssw/pull/43220

**Comment by civanch** [comment]
+1

#43220 is already merged.

**Comment by bsunanda** [comment]
@perrotta @rappoccio @antoniovilela Please approve this

**Comment by antoniovilela** [comment]
> @perrotta @rappoccio @antoniovilela Please approve this

Hi Sunanda,
It is better to ping us with @cms-sw/orp-l2.

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
