### PR TITLE
Conditions classes for Ecal Trigger double weights mechanism

### PR DESCRIPTION
**Pull request by valsdav**
#### PR description:

The Ecal trigger team is working on a double weights mechanism for the trigger primitive generation. 
This PR introduces the necessary condition classes for the CondDB.  
- EcalTPGOddWeight IdMap and Group classes:  essentially a clone of the standard weight classes
- EcalTPGTPMode class:  a new record to handle the configuration of the double weights mechanism. This class will be added also in the online DB and O2O script will be provided in a subsequent PR. 

Details about the format of the new DB classes can be found in slide 10 and 11 of this presentation [1]
A follow-up PR will be prepared for the changes to the Ecal Trigger emulator and O2O scripts. 

This PR should not change any output. 

The PR also adds the xml dump capability for the mustache SC parameters and the dynamic dPhi parameters. 

#### PR validation:

Test payloads have been already uploaded by ECAL experts in the ProdDB for the tags following tags:
- EcalTPGTPMode_v2_hlt  (same as Run2_default)
- EcalTPG_TPMode_Run2_default_v0
- EcalTPG_TPMode_Run3_zeroing_v0
- EcalTPGOddWeightIdMap_v2_hlt
- EcalTPGOddWeightGroup_v2_hlt
- EcalTPGOddWeightGroup_v0
- EcalTPGOddWeightIdMap_v0

The EcalTPG_TPMode_Run2_default_v0 tag  corresponds to the standard Run2 configuration that will be used for back-compability in the new Ecal TPG emulator.

-----------------------------------
[1] https://indico.cern.ch/event/991259/contributions/4257032/attachments/2201014/3722716/21_03_03%20-%20L1%20double%20weight%20CMSSW%20integration.pdf

### CODE REVIEW

**Comment by francescobrivio** [comment]
@cmsbuild please test

**Comment by francescobrivio** [comment]
- Looking at the comparison I see failures in the MessageLogger for WFs 25202.0 and 10224.0, not sure if these were expecetd.
- Also, there are errors in the `Duplicate Dictionaries` section of the tests, although I'm not sure what they are

**Comment by thomreis** [comment]
The MessageLogger failures seem to be coming from the mixing module, and, therefore, unrelated to the changes in this PR.
The log messages for the Duplicate Dictionaries errors suggest that those are related to track trigger and not the ECAL.

**Comment by francescobrivio** [comment]
+alca
- failures an differences in the tests are not related to this PR

**Comment by cecilecaillol** [comment]
+l1

**Comment by thomreis** [comment]
Hi @ggovi do you have any comments?

**Comment by ggovi** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Comment by boudoul** [comment]
Hi @valsdav . I see in the linked presentation that you would like to test it in MWGR from May. I was wondering if you would like to already give a try to the next MWGR (April) ? Thanks.

@amassiro FYI.

**Comment by thomreis** [comment]
Hi @boudoul would we need to make a backport to 11_2 for the April MWGR or is it already going to be with the 11_3 release?

**Comment by boudoul** [comment]
Hi @thomreis , for April a backport is indeed needed .

**Comment by valsdav** [comment]
Hi @boudoul, @amassiro,  since it it not critical for us to test the full chain in the April MWGR and we still need to complete the PR for the emulator, O2O scripts and the updated GT,   we prefer to avoid backporting these changes and test the full chain in the next MWGR (in June).  In the meanwhile we can continue anyway tests in P5 if needed and also re-emulate later the data with the modified emulator, so no problem for the developments. 

Thanks
Davide

**Pull request merged**
