### PR TITLE
CCC PSet migration with HLT for 74X

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
CCC PSet migration with HLT for 74X:
Includes #7673 plus required HLT changes

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
@cmsbot wake up

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by lveldere** [comment]
+1

if tests succeed

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/8343	2342cee
in addition to jenkins, also tested in CMSSW_7_4_X_2015-03-17-0200 /test area sign530/
with a slightly longer set of matrix tests.
No differences observed, no differences expected.

**Comment by VinInn** [comment]
Slava, please test 75X version as well

**Pull request merged**
