### PR TITLE
Simple CSC digi and trigger primitive filter for Run-3 studies

### PR DESCRIPTION
**Pull request by dildick**
#### PR description:

Simple CSC digi and TP filter for Run-3 studies. Can be plugged into a producer+analyzer module to re-emulate and then analyze the CSC trigger primitives from select chambers at P5. Can also be used to mask certain bad chambers.

#### PR validation:

Code compiles. Tested on recent ME+2/1/15 data. The data file below contains histograms from events with the ME+2/1/15 in run 345476 during which we had Phase-2 upgrade firmware enabled. After some internal communication it turned out that the chamber was still incorrectly configured, so the comparisons aren't that useful (but the filter works as expected).

[CSC_dataVsEmul_CMS_Run_345476.pdf](https://github.com/cms-sw/cmssw/files/7367034/CSC_dataVsEmul_CMS_Run_345476.pdf)

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

### CODE REVIEW

**Comment by dildick** [comment]
@ptcox @barvic A simple filter I wrote last week to analyze data from a single chamber...

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cms-sw/csc-dpg-l2 
please comment if this addition looks OK.
Also, is the location in the unpacking code seems OK (EventFilter/CSCRawToDigi)? Offhand, I'd think that a different location may be more appropriate.

**Comment by slava77** [comment]
+reconstruction

for https://github.com/cms-sw/cmssw/pull/35717	04fad7f 
- the new code is in line with the PR description and the follow up review
- jenkins tests pass and comparisons with the baseline show no (relevant) differences; the new code is not running in the tests

**Comment by qliphy** [comment]
+1

**Pull request merged**
