### PR TITLE
Top trigger names for 25 ns 76X

### PR DESCRIPTION
**Pull request by ebouvier**
This PR aims to change Top trigger path names accordingly to the CMSHLT-566 JIRA ticket, both in DQM offline and validation codes. See #11034 for the 75X IB.

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1
provided it passes the tests

**Comment by davidlange6** [comment]
so we do not need to maintain the monitoring for 50ns menus?

**Comment by ebouvier** [comment]
Hi @davidlange6 ,
You're totally right, it is safer to keep 50 ns paths. 
Thanks !

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1

**Pull request merged**
