### PR TITLE
added 2017E/D/F data relvals

### PR DESCRIPTION
**Pull request by prebello**
This follows up discussions from [PR#20404](https://github.com/cms-sw/cmssw/pull/20404) and [PR#20699](https://github.com/cms-sw/cmssw/pull/20699)

- added 2017D/E/F data relvals

### CODE REVIEW

**Comment by prebello** [comment]
+1

**Comment by prebello** [comment]
[@cmsbuild,]

**Comment by prebello** [comment]
[@cmsbuild,] please test workflow 136.807,136.819,136.831

**Comment by fabozzi** [comment]
please test workflow 136.807,136.819,136.831

**Comment by prebello** [comment]
+1

**Comment by davidlange6** [comment]
merge

**Comment by Dr15Jones** [comment]
Workflows 136.810, 136.814, 136.815, 136.822, 136.823, 136.826, 136.827, 136.838, 136.839 are failing in the IB because the raw data files being requested are not available. E.g.
https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc7_aarch64_gcc700/CMSSW_10_0_X_2017-11-28-2300/pyRelValMatrixLogs/run/136.81_RunSingleEl2017D+RunSingleEl2017D+HLTDR2_2017+RECODR2_2017reHLT_Prompt+HARVEST2017/step2_RunSingleEl2017D+RunSingleEl2017D+HLTDR2_2017+RECODR2_2017reHLT_Prompt+HARVEST2017.log

**Comment by fabozzi** [comment]
I have requested Phedex transfer for these

**Pull request merged**
