### PR TITLE
DAQ backport (11_1_X)

### PR DESCRIPTION
**Pull request by smorovic**
#### PR description:

Backport of DAQ PRs merged in CMSSW_11_2_X release cycle. Notable changes:
- data / MC flag which is autodetected in case of data conversion into raw (FRD) format. For HLT it was requested to have this feature for MWGRs / Hilton tests
- support reading TCDS record from a range of FED IDs. MiniDAQs is the primary target to benefit from it with 11_1_X (likely to stay with this release series longer than Central DAQ) and will allow their data to have proper event ID instead of current 24-bit one which wraps frequently.
- additional modes used for the input source reading the new raw FRD format with file header. Allows format to be used with file locking (e.g. in Hilton if FRD rawa dat is produced as the new format).
- bugfixes for some modes of input source reading (although not default in production system).

#### PR validation:

Tested in DAQ VM test cluster (applied to CMSSW_11_1_4)

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Backport of 11_2_X:

https://github.com/cms-sw/cmssw/pull/30206
https://github.com/cms-sw/cmssw/pull/30457 (except DataFormats/TCDS changes)
https://github.com/cms-sw/cmssw/pull/31543

### CODE REVIEW

**Comment by smorovic** [comment]
code-checks

**Comment by smorovic** [comment]
please test

**Comment by mrodozov** [comment]
please test
there was a failure in the comparison job (urlllib failure) it might have been because of wrong communication or a network glitch, 
I'm re-running this to check if it's gonna repeat

**Comment by smorovic** [comment]
+1
Also, one check is stuck (unsure if same as before), but PR seems to pass.

**Comment by mrodozov** [comment]
comparison test ran, the the pr is fine. this checks are new, I'll check why it doesn't tick the comparison check

**Comment by smuzaffar** [comment]
@smorovic , pls ignore the comparison check for this PR. The PR test job and comparison job used different versions of cms-bot . This should not happen for new tests (where both jobs use the same cms-bot)

**Comment by makortel** [comment]
+1

**Comment by perrotta** [comment]
+1
- Correct backport of #30206 , #30457 (except the cnages in DataFormats/TCDS, as mentioned in the PR description) #31543
- Changes in EventFilter/Utilities are relevant for DAQ, and with no inpact on the reco part of the code
- Jenkins tests pass and show no differences in reco outputs

**Comment by qliphy** [comment]
+1

**Pull request merged**
