### PR TITLE
Run3-alca230Y Modify some of the scripts to enable running the IsoTrack calibration of the  HCAL

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Modify some of the scripts to enable running the IsoTrack calibration of the  HCAL

#### PR validation:

Used in obtaining the IsoTrack calibration of HCAL

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by ChrisMisan** [comment]
@bsunanda please squash the commits

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Review by ChrisMisan — COMMENTED** [review]
For the future code improvements, conditional branches in Calibration/HcalCalibAlgos/macros/CalibMain.C should be divided into separate functions. You can also consider using a map to handle all of the parameters to create ordered structure instead of having all of the local variables floating around.

**Comment by ChrisMisan** [comment]
+alca
- No differences aside from msgLogger and MTD

- PR according to the description

**Comment by perrotta** [comment]
+1

**Pull request merged**
