### PR TITLE
Alignment plotting style and other fixes

### PR DESCRIPTION
**Pull request by hroskes**
backport of #15570
(without the phase 1 fixes, of course)

### CODE REVIEW

**Comment by mmusich** [comment]
please tesr

**Comment by hroskes** [comment]
@mmusich I think you made a typo

**Comment by ghellwig** [comment]
please test

**Comment by mmusich** [comment]
please test

**Comment by ghellwig** [comment]
+1

**Comment by hroskes** [comment]
The tests look stuck... can we restart?  This PR is giving so much trouble.

**Comment by mmusich** [comment]
@cmsbuild please test

**Comment by mmusich** [comment]
@hroskes now tests are OK. we'll ask for this one at next ORP

**Pull request merged**
