### PR TITLE
reserve more memory for sistrips to keep on-demand clusters from reallocation

### PR DESCRIPTION
**Pull request by slava77**
@fwyzard @Martin-Grunewald @VinInn @rovere 

In recent IBs we started getting segfaults in step2 in high-PU workflow (25202, ttbar PU35@25ns).
With debugging, the  event (it was event 28 at least in CMSSW_7_5_X_2015-05-16-1100) had a segfault right after the number of clusters grew above 60K.
It looks like recent HLT tables have more reasons to run iterative tracking, probably making the on-demand facility going to essentially full unpacking level.
This situation is much less likely to happen in real HLT with all the prescales in place, but still it could happen.

I doubled the reserve, which is roughly the edge of the cluster multiplicity with full unpacking  scaled to PU50.
 If I trust interactive root, one empty cluster is 32 bytes  ==> +1.9MB increase] due to the reserve, which is fairly small.

I suppose this is needed in 74X as well.

### CODE REVIEW

**Comment by fwyzard** [comment]
Hi Slava,
this sounds familiar, but can you remind me why a relocation causes a
segmentation fault ?

Ciao,
.Andrea

**Comment by slava77** [comment]
@cmsbuild please test
jenkins started running on CMSSW_7_5_X_2015-05-23-1100 already; don't expect failures from broken IBs anymore

**Comment by slava77** [comment]
(messages don't always make it to github threads from my email client)

Hi Andrea,

Apparently some cached pointers in the ClusterStripRef are not smart enough.
Vincenzo, you probably know this more precisely than me.

**Comment by VinInn** [comment]
I suspect this is a undesired feature of the new implementation of edm::Ref that has broken
load on demand.
HLT use case was not taken into account.
I suspect we should either switch off OnDemand or ask the pointer cache in edm::Ref to be rolled back
(or add a hard protection: no more than N clusters allowed if OnDemand)
FYI @mtosi @Dr15Jones @davidlange6 

HLT should be considered broken.

**Comment by fwyzard** [comment]
Hi Vincenzo,
I agree that we should make the on-demand code fail explicitly instead of
segfaulting.
Whether there is a possible fix I leave it to the experts...

Ciao,
.Andrea

**Comment by Dr15Jones** [comment]
Could someone explain what the HLT use case is?

**Comment by Dr15Jones** [comment]
I think I can answer my own question. In this case the container in the event contains an std::vector<>. As hits are requested that container gets filled 'on demand'. If it grows too large all items in the container are moved to a new memory location. So any piece of code holding a pointer to an object in the collection is stuck holding an invalid pointer. An edm::Ref to that container which has already been dereferenced will be holding such a pointer.

It is correct that that use case was overlooked when the code was changed more than a month ago and it is unfortunate that the problem only came to light this week. However, this behaviour must be fixed anyway since multi-threading within one event would also trigger this even without an edm::Ref.

My suggestion for now is to see if we can change the underlying container to be an std::deque or to go directly to a tbb::concurrent_vector<>.

@pcanal can the ROOT 6 iorules accomodate switching from an std::vector to another container type?

**Comment by slava77** [comment]
If the proper fix will take time, I suggest to go with this palliative PR for pre5.

**Comment by Dr15Jones** [comment]
An alternative would be to specialize the particular edm::Ref<> to not cache the element in the container. This would break 'slimming' but that functionality isn't yet in use.

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/9241	bacdf6c
- jenkins tests completed and show no difference in comparisons with the baseline
- local tests of a longer run of 25202 now have no crash (previously failing on event 28)
- this fix is palliative; a proper cure discussed in this thread may take more time

**Comment by VinInn** [comment]
the efficiency (memory and cpu) of DetSetVector is a primary issue, TRK-POG will take care.
a thread safe version (based on RCU) exists, its efficiency is under evaluation. It will most probably do not solve the problem though.
I need to understand where it set faults: Clusters Ref are stored as edm::RefCoreWithIndex which I though was not caching any pointer
@slava77 : how can I reproduce the crash?

In the short term we will simply stop pushing clusters if initial capacity is exhausted

**Comment by Dr15Jones** [comment]
Looks like ```ClusterStripRef``` is defined as a typedef in ```OmniClusterRef``` to an ```edm::Ref<...>```. 
http://cmslxr.fnal.gov/source/DataFormats/TrackerRecHit2D/interface/OmniClusterRef.h?v=CMSSW_7_5_X_2015-05-21-2300#0022

```OmniClusterRef``` does just use an ```edm::RefCoreWithIndex``` which, as Vincenzo said, does not caching on its own
http://cmslxr.fnal.gov/source/DataFormats/TrackerRecHit2D/interface/OmniClusterRef.h?v=CMSSW_7_5_X_2015-05-21-2300#0070

However, the method ```OmniClusterRef::cluster_strip``` returns a ```ClusterStripRef```` and if that ```ClusterStripRef``` is dereferenced than it will wind up caching a pointer to the item inside the ```edmNew::DetSetVector```.

**Comment by VinInn** [comment]
ok. but
cluster_strip is referenced only here
http://cmslxr.fnal.gov/lxr/ident?v=CMSSW_7_5_0_pre4_ROOT5&_i=cluster_strip&_remember=1
and I do not see anyplace where it is "stored" longer than a local scope...

**Comment by VinInn** [comment]
do not understand it crashes here (I reserved only 100)
```
#6  0x00007f5ae5c192fb in accumulate<__gnu_cxx::__normal_iterator<unsigned char const*, std::vector<unsigned char> >, int> (__init=<optimized out>, __last=..., __first=...) at /afs/cern.ch/cms/sw/ReleaseCandidates/volA/slc6_amd64_gcc491/external/gcc/4.9.1-cms/include/c++/4.9.1/bits/stl_numeric.h:127
#7  charge (this=0x7f5aa68e2780) at /afs/cern.ch/cms/sw/ReleaseCandidates/vol1/slc6_amd64_gcc491/cms/cmssw-patch/CMSSW_7_5_X_2015-05-23-2300/src/DataFormats/SiStripCluster/interface/SiStripCluster.h:69
#8  chargePerCM<SiStripCluster> (cl=..., detid=...) at /afs/cern.ch/cms/sw/ReleaseCandidates/vol1/slc6_amd64_gcc491/cms/cmssw-patch/CMSSW_7_5_X_2015-05-23-2300/src/DataFormats/SiStripCluster/interface/SiStripClusterTools.h:32
#9  chargePerCM<SiStripCluster> (tp=..., cl=..., detid=...) at /afs/cern.ch/cms/sw/ReleaseCandidates/vol1/slc6_amd64_gcc491/cms/cmssw-patch/CMSSW_7_5_X_2015-05-23-2300/src/DataFormats/SiStripCluster/interface/SiStripClusterTools.h:38
#10 StripCPEfromTrackAngle::localParameters (this=0x7f5aa5d6df00, cluster=..., det=..., ltp=...) at /home/vin/CMSSW_7_5_X_2015-05-23-2300/src/RecoLocalTracker/SiStripRecHitConverter/src/StripCPEfromTrackAngle.cc:48
#11 0x00007f5ae5c1720d in StripClusterParameterEstimator::localParameters (this=<optimized out>, cluster=..., gd=..., tsos=...) at /afs/cern.ch/cms/sw/ReleaseCandidates/vol1/slc6_amd64_gcc491/cms/cmssw-patch/CMSSW_7_5_X_2015-05-23-2300/src/RecoLocalTracker/ClusterParameterEstimator/interface/StripClusterParameterEstimator.h:38
#12 0x00007f5ae5dca110 in TkClonerImpl::operator()(SiStripMatchedRecHit2D const&, TrajectoryStateOnSurface const&) const () from /afs/cern.ch/cms/sw/ReleaseCandidates/vol1/slc6_amd64_gcc491/cms/cmssw/CMSSW_7_5_X_2015-05-21-1100/lib/slc6_amd64_gcc491/libRecoTrackerTransientTrackingRecHit.so
#13 0x00007f5ae5dca6a8 in TkClonerImpl::makeShared(SiStripMatchedRecHit2D const&, TrajectoryStateOnSurface const&) const () from /afs/cern.ch/cms/sw/ReleaseCandidates/vol1/slc6_amd64_gcc491/cms/cmssw/CMSSW_7_5_X_2015-05-21-1100/lib/slc6_amd64_gcc491/libRecoTrackerTransientTrackingRecHit.so
#14 0x00007f5ae778ea76 in SiStripMatchedRecHit2D::cloneSH(TkCloner const&, TrajectoryStateOnSurface const&) const () from /afs/cern.ch/cms/sw/ReleaseCandidates/vol1/slc6_amd64_gcc491/cms/cmssw/CMSSW_7_5_X_2015-05-21-1100/lib/slc6_amd64_gcc491/libDataFormatsTrackerRecHit2D.so
#15 0x00007f5ae1201dd5 in KFTrajectoryFitter::fitOne(TrajectorySeed const&, std::vector<std::shared_ptr<TrackingRecHit const>, std::allocator<std::shared_ptr<TrackingRecHit const> > > const&, TrajectoryStateOnSurface const&, TrajectoryFitter::fitType) const () from /afs/cern.ch/cms/sw/ReleaseCandidates/vol1/slc6_amd64_gcc491/cms/cmssw/CMSSW_7_5_X_2015-05-21-1100/lib/slc6_amd64_gcc491/libTrackingToolsTrackFitters.so
#16 0x00007f5ac9a58c23 in TransientInitialStateEstimator::innerState(Trajectory const&, bool) const () from /afs/cern.ch/cms/sw/ReleaseCandidates/vol1/slc6_amd64_gcc491/cms/cmssw/CMSSW_7_5_X_2015-05-21-1100/lib/slc6_amd64_gcc491/libRecoTrackerCkfPattern.so
#17 0x00007f5ac9a3e5fa in cms::CkfTrackCandidateMakerBase::produceBase(edm::Event&, edm::EventSetup const&) () from /afs/cern.ch/cms/sw/ReleaseCandidates/vol1/slc6_amd64_gcc491/cms/cmssw/CMSSW_7_5_X_2015-05-21-1100/lib/slc6_amd64_gcc491/libRecoTrackerCkfPattern.so
```

and there should be no relocation in 
```
TkClonerImpl::operator()
```

**Comment by VinInn** [comment]
I start to suspect that it is independent of the edm::Ref cache...
Can we somehow test the new hlt menu with the some old release w/o the cache in the ref?
many it is enough to test 7_4 with a small reserve...

**Comment by slava77** [comment]
Hi Vincenzo, it looks like you reproduced the problem.
The issue is that the relocation happens earlier and for some time you can still read the bad memory area.
valgrind helps.

**Comment by VinInn** [comment]
I can try valgrind.
I cannot find the Ref<StripCluster> that become stales..
7_4_2 is fine even with a tiny reserve...

**Comment by slava77** [comment]
The first invalid read that I've seen was happening in (it was the monoRH from the doubleMatch function)
```
      float siStripClusterTools::chargePerCM<SiStripCluster>(DetId, SiStripCluster const&, LocalTrajectoryParameters const&)
      (anonymous namespace)::Chi2ChargeMeasurementEstimator::preFilter(TrajectoryStateOnSurface const&, MeasurementEstimator::OpaquePayload const&) const
      TkGluedMeasurementDet::HitCollectorForFastMeasurements::add(SiStripMatchedRecHit2D const&)
      void TkGluedMeasurementDet::doubleMatch<TkGluedMeasurementDet::HitCollectorForFastMeasurements>(TrajectoryStateOnSurface const&, MeasurementTrackerEvent const&, TkGluedMeasurementDet::HitCollectorForFastMeasurements&) const
      TkGluedMeasurementDet::measurements(TrajectoryStateOnSurface const&, MeasurementEstimator const&, MeasurementTrackerEvent const&, tracking::TempMeasurements&) const
      LayerMeasurements::measurements(DetLayer const&, TrajectoryStateOnSurface const&, Propagator const&, MeasurementEstimator const&) const
      CkfTrajectoryBuilder::findCompatibleMeasurements(TrajectorySeed const&, TempTrajectory const&, std::vector<TrajectoryMeasurement, std::allocator<TrajectoryMeasurement> >&) const
      CkfTrajectoryBuilder::limitedCandidates(boost::shared_ptr<TrajectorySeed const> const&, std::vector<TempTrajectory, std::allocator<TempTrajectory> >&, std::vector<Trajectory, std::allocator<Trajectory> >&) const
      CkfTrajectoryBuilder::limitedCandidates(TrajectorySeed const&, TempTrajectory&, std::vector<Trajectory, std::allocator<Trajectory> >&) const
      CkfTrajectoryBuilder::buildTrajectories(TrajectorySeed const&, std::vector<Trajectory, std::allocator<Trajectory> >&, TrajectoryFilter const*) const

```

**Comment by VinInn** [comment]
I am suspecting the matching .
still it caches hits not clusters

**Comment by slava77** [comment]
In case it helps,
I've split the step2 in 2:

```
cmsDriver.py step2  --conditions auto:run2_mc --pileup_input das:/RelValMinBias_13/CMSSW_7_5_0_pre4-MCRUN2_75_V1-v1/GEN-SIM -n 10 --eventcontent FEVTDEBUGHLT -s DIGI:pdigi_valid,L1,DIGI2RAW --process DIGI --datatier GEN-SIM-DIGI-RAW-HLTDEBUG --pileup AVE_35_BX_25ns --customise SLHCUpgradeSimulations/Configuration/postLS1Customs.customisePostLS1 --magField 38T_PostLS1  -n 70 --customise Validation/Performance/TimeMemoryInfo.py --filein filelist:step1_dasquery.log --fileout file:step2_DIGI_RAW.root >& step2_DIGI_RAW.log &

cmsDriver.py step2 --conditions auto:run2_mc --eventcontent FEVTDEBUGHLT -s HLT:@relval25ns,RAW2DIGI,L1Reco --datatier GEN-SIM-DIGI-RAW-HLTDEBUG --customise SLHCUpgradeSimulations/Configuration/postLS1Customs.customisePostLS1 --magField 38T_PostLS1 -n 70 --customise Validation/Performance/TimeMemoryInfo.py --filein file:step2_DIGI_RAW.root --fileout file:step2.root &>step2_HLT_L1Reco.log &
```
The last one can be reproduced quicker by adding a skip just up to the event where the crash happens.
It was reproducible event with the code recompiled with -O0.

**Comment by VinInn** [comment]
btw did you notice all those
```
==22170== 
==22170== Invalid read of size 1
==22170==    at 0x402BC68: __strcmp_sse42 (in /afs/cern.ch/cms/sw/ReleaseCandidates/volA/slc6_amd64_gcc491/external/valgrind/3.10.1-jhibmm/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==22170==    by 0x1D22403A: reco::typeCode(edm::TypeWithDict const&) (in /afs/cern.ch/cms/sw/ReleaseCandidates/volA/slc6_amd64_gcc491/cms/cmssw-patch/CMSSW_7_5_X_2015-05-23-2300/lib/slc6_amd64_gcc491/libCommonToolsUtils.so)
==22170==    by 0x1D1FE5EF: reco::parser::ExpressionVarSetter::push(char const*, char const*) const (in /afs/cern.ch/cms/sw/ReleaseCandidates/volA/slc6_amd64_gcc491/cms/cmssw-patch/CMSSW_7_5_X_2015-05-23-2300/lib/slc6_amd64_gcc491/libCommonToolsUtils.so)
==22170==    by 0x1D1FEC5C: reco::parser::ExpressionVarSetter::operator()(char const*, char const*) const (in /afs/cern.ch/cms/sw/ReleaseCandidates/volA/slc6_amd64_gcc491/cms/cmssw-patch/CMSSW_7_5_X_2015-05-23-2300/lib/slc6_amd64_gcc491/libCommonToolsUtils.so)
```

to me valgrind crashed well before 
```
=22170==  Address 0x0 is not stack'd, malloc'd or (recently) free'd
==22170== 
%MSG-e FatalSystemSignal:  AfterModBeginStream 24-May-2015 17:07:56 CEST  BeforeEvents
A fatal system signal has occurred: segmentation violation
%MSG


A fatal system signal has occurred: segmentation violation
The following is the call stack containing the origin of the signal.
NOTE:The first few functions on the stack are artifacts of processing the signal and can be ignored


Thread 1 (process 22170):
#0  0x0000000038157740 in ?? ()
#1  0x0000000000000008 in ?? ()
#2  0x0000000802b95d90 in ?? ()
#3  0x0000000802b95d50 in ?? ()
```

**Comment by slava77** [comment]
On 5/24/15 10:16 AM, Vincenzo Innocente wrote:
> btw did you notice all those
> 
> |==22170== 
> ==22170== Invalid read of size 1
> ==22170==    at 0x402BC68: __strcmp_sse42 (in /afs/cern.ch/cms/sw/ReleaseCandidates/volA/slc6_amd64_gcc491/external/valgrind/3.10.1-jhibmm/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
> ==22170==    by 0x1D22403A: reco::typeCode(edm::TypeWithDict const&) (in /afs/cern.ch/cms/sw/ReleaseCandidates/volA/slc6_amd64_gcc491/cms/cmssw-patch/CMSSW_7_5_X_2015-05-23-2300/lib/slc6_amd64_gcc491/libCommonToolsUtils.so)
> ==22170==    by 0x1D1FE5EF: reco::parser::ExpressionVarSetter::push(char const*, char const*) const (in /afs/cern.ch/cms/sw/ReleaseCandidates/volA/slc6_amd64_gcc491/cms/cmssw-patch/CMSSW_7_5_X_2015-05-23-2300/lib/slc6_amd64_gcc491/libCommonToolsUtils.so)
> ==22170==    by 0x1D1FEC5C: reco::parser::ExpressionVarSetter::operator()(char const*, char const*) const (in /afs/cern.ch/cms/sw/ReleaseCandidates/volA/slc6_amd64_gcc491/cms/cmssw-patch/CMSSW_7_5_X_2015-05-23-2300/lib/slc6_amd64_gcc491/libCommonToolsUtils.so)
> |


Yes. I've seen this one.
I even managed to get a runtime crash for this
with
export MALLOC_CHECK_=3
export MALLOC_PERTURB_=$(($RANDOM % 255 + 1))

cmsRunGlibC a.py

in
   [1] Constructing module: class=AnalyticalTrackSelector
label='hltIter0PFlowTrackSelectionHighPurity'
Exception Message:
Cut parser error:member "tracksSize" has an invalid return type:
"unsigned long" (char 0)




> 
> to me valgrind crashed well before
> 
> |=22170==  Address 0x0 is not stack'd, malloc'd or (recently) free'd
> ==22170== 
> %MSG-e FatalSystemSignal:  AfterModBeginStream 24-May-2015 17:07:56 CEST  BeforeEvents
> A fatal system signal has occurred: segmentation violation
> %MSG
> 



are you running from a local file ?


> 
> A fatal system signal has occurred: segmentation violation
> The following is the call stack containing the origin of the signal.
> NOTE:The first few functions on the stack are artifacts of processing the signal and can be ignored
> 
> 
> Thread 1 (process 22170):
> #0  0x0000000038157740 in ?? ()
> #1  0x0000000000000008 in ?? ()
> #2  0x0000000802b95d90 in ?? ()
> #3  0x0000000802b95d50 in ?? ()
> |
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cms-sw/cmssw/pull/9241#issuecomment-105025289>.
> 

-- 
***********************************************************************
 Vyacheslav (Slava) Krutelyov
 TAMU: Physics Dept Texas A&M MS4242, College Station, TX 77843-4242
 CERN: 42-R-027
 AIM/Skype: siava16              googleTalk: slava77@gmail.com
 (630) 291-5128  Cell (US)       +41 76 275 7116 Cell (CERN)

-----------------------------------------------------------------------

**Comment by VinInn** [comment]
> On 24 May, 2015, at 5:41 PM, Slava Krutelyov <notifications@github.com> wrote:
> 
> are you running from a local file ?

no, from EOS…

**Comment by VinInn** [comment]
@Dr15Jones , where is this infamous pointer cache?
I do not see any pointer in
http://cmslxr.fnal.gov/lxr/source/DataFormats/Common/interface/Ref.h?v=CMSSW_7_5_X_2015-05-23-2300#0295
??

**Comment by Dr15Jones** [comment]
The Ref puts the cached value in the RefCore as a replacement for the EDProductGetter.

**Comment by VinInn** [comment]
so RefCoreWithIndex is affected as well (despite its name...)
I can write my own as in TrackBase, this will change the OmniRef with usual schema evolution consequences....
not for 7_5

as short-term solution I will either throw (and catch) if push_back is attempted when size()==capacity()
or simply silently not push_back() (a local LogError/LogWarning will produce tons of reports)

**Comment by Dr15Jones** [comment]
RefCoreWithIndex is only affected if someone calls ```RefCoreWithIndex::setProductPtr``` or ```RefCoreWithIndex::tryToSetProductPtrForFirstTime```. If they do not then the cache is never used (or it remains pointing at an ```edm::EDProductGetter``` which can be used to get data out of the Event).

**Comment by VinInn** [comment]
I think I have a more robust solution.
This can be closed if #9260 is accepted.

**Comment by fwyzard** [comment]
I am still worried by Chris comment about multithreading. Should I be, or
not ?

.A

**Comment by VinInn** [comment]
@fwyzard, depends when the core team want to do multi-threaded inside the event...
given that now the relocation is excluded RCU is not needed anymore, making OnDemand fully thread-safe is "easy"

**Comment by Dr15Jones** [comment]
@fwyzard it doesn't affect the present threading implementation only the future.

**Comment by slava77** [comment]
superseded by #9260

**Comment by slava77** [comment]
it looks like #9260 needs more work.

**Comment by VinInn** [comment]
little work actually, done.
In any case the reserve is the same as in this one.

**Comment by slava77** [comment]
closing for good this time

**Comment by pcanal** [comment]
> @pcanal <https://github.com/pcanal> can the ROOT 6 iorules accomodate switching from an std::vector to another container type?

Yes.  Both ROOT 5 and 6 will automatically support the conversion from any STL containers to another container with the same content 
(vector<SomeClass> to list<SomeClass> and vice et versa).  Associative container are considered to be containing a std::pair for 
this purpose.

Cheers,
Philippe.

**Pull request closed without merging**
