### PR TITLE
Expand dqmMemoryStats to include 'count' mode

### PR DESCRIPTION
**Pull request by dmitrijus**

### CODE REVIEW

**Comment by dmitrijus** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by rovere** [comment]
@fabiocos the cutoff should be set to 0 to have meaningful results.
The labels have not been customized...

**Comment by fabiocos** [comment]
@rovere thank you, indeed adding -c 0 to the options removes the useless cutoff printout. Just it would be useful to adjust the printout if  args.count is set

**Comment by rovere** [comment]
I leave that to @dmitrijus

**Comment by dmitrijus** [comment]
I think this is fine to go in.

I will disable the cut-off next time I  get the chance (or never).

**Comment by fabiocos** [comment]
@dmitrijus its cosmetics, but the printout could be adjusted (cutoff at the end of the day is an option)

**Comment by fabiocos** [comment]
+1

**Pull request merged**
