### PR TITLE
Remove confusing use of None from _TypedParameterizable constructor

### LINKED ISSUE #133: Remove confusing use of None from _TypedParameterizable
Spin-off from https://github.com/makortel/framework/issues/124

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

En route to https://github.com/cms-sw/cmssw/pull/33354#issuecomment-820580988 I came across somewhat confusing use of `None` in the `_TypedParameterizable` constructor. This PR attempts to clean it up as it does not seem to have any real purpose.

Resolves https://github.com/makortel/framework/issues/133

#### PR validation:

Framework unit tests run.

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
@Dr15Jones Could you review?

**Comment by makortel** [comment]
@cmsbuild, please test

Let's see if a different IB would make a difference

**Comment by Dr15Jones** [comment]
I'd suggest writing a test where a class inherits from __Parameterizable but takes no arguments. Then test clone on that. I believe that is the case the `None` was attempting to deal with.

**Comment by makortel** [comment]
> I'd suggest writing a test where a class inherits from __Parameterizable but takes no arguments. Then test clone on that. I believe that is the case the `None` was attempting to deal with.

`_Parameterizable` does not have `clone()` (that is implemented in `_TypedParameterizable`, that is tested already, except now I noticed a typo in that test, and the fixed test works as well). How would you suggest to proceed towards such test?

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
