### PR TITLE
Backport EMTF report summary 10 1 x

### PR DESCRIPTION
**Pull request by chadfreer**

### CODE REVIEW

**Comment by thomreis** [comment]
backport of #23468

**Comment by thomreis** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by fabiocos** [comment]
@chadfreer the second of your commits refer to a variable that is not used, and causes a compiler warning also in master

https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc6_amd64_gcc630/CMSSW_10_2_X_2018-06-06-2300/DQM/L1TMonitorClient

Could you please fix it in master and here? The rest can easily go without problems IMO

**Comment by chadfreer** [comment]
Hi Thomas,

I checked the most recent commit before I pushed it today and it no longer gives warnings when I undo those changes. That commit was originally a suggestion from cmsbuild for 10_2_X so it seems like an issue only with backporting to 10_1_X.

Removing the commit just returns the file to what it is naturally in 10_1_X so it should not give errors now.

Chad Freer
chadwfreer@gmail.com

**Comment by thomreis** [comment]
The compiler warnings in 10_2_x are fixed by #23502 since PR #23468 is already merged.
For the backport I see three options:
- If you revert the last commit as you did, this PR and the merged master PR differ.
- If you do not revert the commit the backport and the master are the same but you have the compiler warnings.
- If you remove the unused variables you make effectively a backport of #23468 + #23502 and there should be no compiler warnings anymore.
Maybe @fabiocos can advise what is the preferred solution.

**Comment by thomreis** [comment]
Comparing [1] with the last IB before PR #23468 was merged [2] it seems that `const std::string& hName = ...`, that the code checks patch introduced, gives a compiler warning , while the previous `const std::string hName = ...` does not.

[1] https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc6_amd64_gcc630/CMSSW_10_2_X_2018-06-06-2300/DQM/L1TMonitorClient

[2] https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc6_amd64_gcc630/CMSSW_10_2_X_2018-06-05-1100/DQM/L1TMonitorClient

**Comment by boudoul** [comment]
Hello @chadfreer , could you please add in the title of this PR that this is for EMTF, otherwise we cannot guess if this is for Tracker or HCAL or ,  etc... Thanks

**Comment by dmitrijus** [comment]
+1

**Comment by jfernan2** [comment]
Successfully tested and integrated in the Online DQM at P5. https://twiki.cern.ch/twiki/bin/viewauth/CMS/DQMP5TagCollector
Merged in master

**Comment by fabiocos** [comment]
+1

**Pull request merged**
