### PR TITLE
HCALDQM: bad capid/LED misfire sound alarms only for last 60 LSes (10_2_X)

### PR DESCRIPTION
**Pull request by DryRun**
10_2_X backport of https://github.com/cms-sw/cmssw/pull/24757.

Adds "LSmod60" versions of the bad capid and LED misfire vs LS plots, which only record the last 60 LSes. This is so that the error condition goes away after ~25 minutes, so the sound alarms don't keep triggering.

### CODE REVIEW

**Comment by DryRun** [comment]
Hi @andrius-k -- very sorry, I should have mentioned that this PR includes all the commits from https://github.com/cms-sw/cmssw/pull/24516, which has not yet been merged and doesn't factorize with the commits specific to this PR. Let me know if this is/isn't ok.

**Comment by andrius-k** [comment]
Hi @DryRun don't worry, it's ok. Just mention all of the PR that this one is the backport of, please.

**Comment by andrius-k** [comment]
please test

**Comment by andrius-k** [comment]
+1

**Comment by andrius-k** [comment]
Hi @DryRun, as 10_2 is no longer being used maybe this PR should be closed?

**Comment by DryRun** [comment]
Hi @andrius-k , sure, I'll close the PR. Thanks!

**Pull request closed without merging**
