### PR TITLE
/validation/RecoEgamma/ Phase2 miniAOD modification v2

### PR DESCRIPTION
**Pull request by archiron**
#### PR description:

Implemented a workaround in the miniAOD validation to read the electron collections from two different collections (one for the barrel, one for the HGCAL). The values are adjusted for PHASE2 validation via an era modifier
Improved the binning in a few plots.

The modifications are made in Validation/RecoEGamma/plugins folder (ElectronMcMiniAODSignalValidator.cc/h) and into the Validation/RecoEGamma/python folder (ElectronMcSignalValidatorMiniAOD_cfi.py).  We also modified ElectronMcSignalValidator_gedGsfElectrons_cfi.py, ElectronMcFakeValidator_gedGsfElectrons_cfi.py & ElectronMcSignalValidatorPt1000_gedGsfElectrons_cfi.py for binning.

We also made some corrections into DQMOffline/Egamma/python folder (electronDataDiscovery.py) by implementing a new function wich help us with local runs into Validation/RecoEgamma/tests folders (ElectronMcSignalPostValidation_cfg.py, ElectronMcSignalPostValidationMiniAOD_cfg.py, ElectronMcSignalValidationMiniAOD_cfg.py, ElectronMcSignalValidation_gedGsfElectrons_cfg.py, electronValidationCheck_Env.py).

miniAOD_corrections

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

for miniAOD improvement, the différences can be seen : 
before : https://cms-egamma.web.cern.ch/validation/Electrons/Dev/index.php?action=/11_3_0_pre4_PHASE2_miniAOD3_DQM_dev/FullvsFull_CMSSW_11_3_0_pre4/RECO-miniAOD_ZEE_14#TOP
after : https://cms-egamma.web.cern.ch/validation/Electrons/Dev/index.php?action=/11_3_0_pre4_PHASE2_miniAOD6_DQM_dev/FullvsFull_CMSSW_11_3_0_pre4/RECO-miniAOD_ZEE_14#TOP

the binning improvement is only a regularization of the number of bins for histos with primary vertices (80 instead of 81). This avoid some drops into the curves of histograms.

#### PR validation:

compilation is OK, basics tests (scram b runtests or local tests) are OK too.
runTheMatrix.py -l limited -i all --ibeos tests are fine (38 37 36 27 17 4 1 1 1 tests passed, 0 0 0 0 0 0 0 0 0 failed
).
here is the run-log : 
[runall-report-step123-.log](https://github.com/cms-sw/cmssw/files/6303598/runall-report-step123-.log)

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch  -> OK.
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)  -> OK.
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)  -> OK.

@beaudett

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
@archiron could you please check in the following link if the changes in the DQM folders are what you expect?
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_11_3_X_2021-04-12-2300+51693e/42213/dqm-histo-comparison-summary.html
Thanks

**Comment by beaudett** [comment]
Hi,
@archiron may have better chance, but I failed to find a file that contains miniAODs with all the histograms. Could you please point use to a file with miniAOD and for Phase2 ? Thanks

**Comment by archiron** [comment]
perhaps whith:
`runTheMatrix.py -n | grep D76
34634.0 2026D76+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14+DigiTrigger+RecoGlobal+HARVESTGlobal 
34834.999 2026D76PU_PMXS1S2PR+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14+PREMIX_PremixHLBeamSpot14PU+DigiTriggerPU+RecoGlobalPU+HARVESTGlobalPU 
`
and 34634.0 seems to be a candidate.

**Comment by beaudett** [comment]
>  and 34634.0 seems to be a candidate.

Right, but the statistics is way too low to judge.

**Comment by jfernan2** [comment]
What about runing the wf privately setting the desired number of events you consider as enough stats?

**Comment by archiron** [comment]
These plots have been made privately (but not with a standard workflow). Let me know if you want me to nevertheless run a fully standard workflow
standard plots for validation : https://cms-egamma.web.cern.ch/validation/Electrons/Releases/index.php?action=/11_3_0_pre4_PHASE2_DQM_std/FullvsFull_CMSSW_11_3_0_pre4/RECO-miniAOD_ZEE_14#TOP
plots made without correction : https://cms-egamma.web.cern.ch/validation/Electrons/Dev/index.php?action=/11_3_0_pre4_PHASE2_miniAOD3_DQM_dev/FullvsFull_CMSSW_11_3_0_pre4/RECO-miniAOD_ZEE_14#TOP
plots made with correction : https://cms-egamma.web.cern.ch/validation/Electrons/Dev/index.php?action=/11_3_0_pre4_PHASE2_miniAOD6_DQM_dev/FullvsFull_CMSSW_11_3_0_pre4/RECO-miniAOD_ZEE_14#TOP
all these plots are made with 9000 evts but 1000 evts may be sufficient.

**Comment by jfernan2** [comment]
> @archiron could you please check in the following link if the changes in the DQM folders are what you expect?
> https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_11_3_X_2021-04-12-2300+51693e/42213/dqm-histo-comparison-summary.html

Just to be clear: my question was the one above, I am not worried about stats as long as you confirm that seen changes are expected

**Comment by beaudett** [comment]
Ho @jfernan2 
according to @archiron there is only one Phase2 wf, and it has only one entry 
https://tinyurl.com/ykyw42xh
If black is new and blue the reference, then there is one additional entry in the endcaps, while there was none before. In that case, it would be good. Now, this hint makes sense only if the GEN are identical.

**Comment by jfernan2** [comment]
OK, but the PR is producing changes in wfs which are not phase 2, as seen on 
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_11_3_X_2021-04-12-2300+51693e/42213/dqm-histo-comparison-summary.html
Do you only expect changes in Phase2 wfs?

**Comment by archiron** [comment]
Oh, yes other changes are expected. Most of them are issue from the binning improvement in *recOfflineVertices histos i.e. histos with primary vertices (80 bins instead of 81). This avoid some drops into the curves of histograms such as :
nbins_corrections-a

**Comment by jfernan2** [comment]
OK, I see, so then everything is understood unless you correct me. The full stats you privately analyzed confirm that, right?

**Comment by archiron** [comment]
yes.

**Comment by qliphy** [comment]
+1

**Pull request merged**
