### PR TITLE
Clean BuildFiles in ALCA

### PR DESCRIPTION
**Pull request by guitargeek**
#### PR description:

Another quick partially automatic BuildFile cleaning PR in the style of many before (for example #29579), this time covering all ALCA subsystems.

I checked that all the BuildFiles are still well formatted, to not undo any work done by the formatting PRs a few days ago.

#### PR validation:

CMSSW compiles. It was checked that all newly added dependencies are actually required by the package with `git grep`.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by perrotta** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade

**Comment by ggovi** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/29805	590679a 
- technical

**Comment by rekovic** [comment]
+1

**Comment by silviodonato** [comment]
alca:  @pohsun @tlampen @tocheng @christopheralanwest?

**Comment by silviodonato** [comment]
Do you have any comments?
alca:  @pohsun @tlampen @tocheng @christopheralanwest
daq:  @emeschi @mommsen

**Comment by pohsun** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
