### PR TITLE
DQM module for PPS random stream - backport

### PR DESCRIPTION
**Pull request by AndreaBellora**
This PR is a backport of #40895

### CODE REVIEW

**Comment by syuvivida** [comment]
Hi, after building 13_0_0 with this PR at our playback, I was trying to test this client with the streamer provided by AlcaDB, but then found all the streamers at /eos/cms/store/t0streamer/Data/ALCAPPSExpress/000/ are from 2022 runs (created with 12_4_X or even older versions). In this case, we will not be able to read these streamers due to a mismatch of streamer format. @francescobrivio do we have this type of AlcaPPS streamers that are built with 13_0_X?

Also to double check @AndreaBellora did you test your module and client in 13_0_X using these streamers at eos?
Thanks!!

Eiko

**Comment by vavati** [comment]
@syuvivida : i made the request in https://its.cern.ch/jira/browse/CMSHLT-2650 but for the time being no feedback.
@trtomei please let us know when we could run and produce the correct streamer files.

**Comment by syuvivida** [comment]
@vavati When we switched from 12_4_X to 12_6_X for MWGR, at that time, HLT had to re-run 12_6_X at Hilton on an old 12_4_X collision streamer to make it work. On the other hand, there seems to be no streamer mismatch for 12_6_X vs 13_0_X;  so far we are able to run 13_0_0 on the 12_6_3 MWGR cosmic run streamers.

**Comment by vavati** [comment]
@syuvivida the files you are trying to read   were produced during 2022 data taking
So probably with 12_4. I dont understand why you mention 12_6

**Comment by syuvivida** [comment]
@vavati I meant to say there is a mismatch between 12_4_X streamers and newer release(either 12_6_X or 13_0_X), but not 12_6_X with 13_0_X. 
If someone could reproduce these PPS streamers and provide us streamers either with 12_6_X or 13_0_X,  we can test.

**Comment by vavati** [comment]
@syuvivida I don't think it is up to us to provide a conversion of data streamer. The issue is not created by out PR but somewhere else. If data 2022 cannot be used to test then we wait for the new data.
As soon as HLT will provide the stream we will create the new file.

**Comment by emanueleusai** [comment]
@vavati this really depends on how urgently you want this implemented. If this can wait until we get new 13_0 streamers then that's the easiest solution.

**Comment by emanueleusai** [comment]
hold

- waiting for 13_0 streamers to test at P5

**Comment by emanueleusai** [comment]
please test

**Comment by emanueleusai** [comment]
type ctpps

**Comment by emanueleusai** [comment]
backport of https://github.com/cms-sw/cmssw/pull/40895

**Comment by syuvivida** [comment]
@AndreaBellora 
please remove the line 
`process.source.minEventsPerLumi  = 100000`
please also double check this output root file and see if the folder structure is what you corrected now. 
/afs/cern.ch/work/s/syu/public/pps_output

Thanks!!

**Comment by AndreaBellora** [comment]
Personally I'd prefer having an easy way to visualize the results (even if we are considering expert usage). However, I have no experience with the GUI and I will need some guidance to do it. I'll discuss with my colleagues, but I guess that any GUI update should go in a separate thread wrt. this part of the code.

**Comment by syuvivida** [comment]
@AndreaBellora here is the output root file from our playback run (how files arrived are similar to that as in production), please check if the histograms are properly filled with enough events.
/afs/cern.ch/work/s/syu/public/pps_output/DQM_V0001_PPSRANDOM_R000519120.root

For this test, I was running on a DQM machine with another 2 clients. Let me also check this new client on another machine with ~20 clients.

**Comment by AndreaBellora** [comment]
@syuvivida I checked this file too and everything looks right. As soon as the latter file you mention is produced, let me know and I'll check it out immediately.

**Comment by emanueleusai** [comment]
please test

**Comment by syuvivida** [comment]
@AndreaBellora 
  The output of ppsrandom client at the playback when I ran this client with the other 26 clients is here: /afs/cern.ch/work/s/syu/public/pps_output/DQM_V0001_PPSRANDOM_R000519240.root
But we want to remind you, this test is done with the "cosmic runs with PPS random triggers" 365045. A test with online DQM stream and a test with beam will provide more information and are still required.

**Comment by vavati** [comment]
@syuvivida Please it is up to DQM to organize the test. Today HLT said that the key can prepared to make the live test
At the moment the discussion seems to be here
https://its.cern.ch/jira/browse/CMSHLT-2650
There are too many threads with this issue and not all people are following.
Concerning the future tests with beam, well we need first beam. So keep it in DQM list and at the first occasion do the tests.

**Comment by syuvivida** [comment]
@AndreaBellora DQM has made a production release. If HLT is ready to join, we could switch the production and include pps temporarily,
would you or someone from PPS connect to the CR zoom?

**Comment by emanueleusai** [comment]
please test

**Comment by syuvivida** [comment]
@AndreaBellora were you able to test the commit (adding colz, etc) you made yesterday using the streamers we copied to /eos/cms/store/group/comm_dqm/pps_input/? 

Eiko

**Comment by AndreaBellora** [comment]
@syuvivida yes, and things turned out as expected. On our side, no further change is needed, besides @francescobrivio suggestions, which will come in a separate PR

**Comment by emanueleusai** [comment]
Very well then. I will complete the review soon so we can merge this.

**Comment by emanueleusai** [comment]
+1

**Comment by emanueleusai** [comment]
unhold

**Comment by perrotta** [comment]
+1
- Some further cleanup from unnecessary header includes in the new plugin also possible, see #41204 (not really needed to be backported)

**Pull request merged**
