### PR TITLE
use named namespaces for dictionary structs to avoid symbol conflicts (L1TMuon and phase-2 TT)

### PR DESCRIPTION
**Pull request by slava77**
all objects in dictionary definitions should be unique.

this should cleanup numerous warnings when making plots with FWLite

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/21792	995b7c6
- local tests confirm that errors like ``` error: redefinition of 'dictionary' ``` in https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_10_0_X_2017-12-29-1100+21792/24445/validateJR/all_OldVSNew_TTbar13TeV2017wf10024p0/all_OldVSNew_TTbar13TeV2017wf10024p0.log go away

**Comment by davidlange6** [comment]
merge

**Comment by kpedro88** [comment]
+1 (belated, since these errors drove me nuts for a while now)

@slava77 I think this resolves #14564

**Comment by kpedro88** [comment]
actually maybe not, but that seems possibly related

**Pull request merged**
