### PR TITLE
fix the ecal summary report value

### PR DESCRIPTION
**Pull request by mengleisun**
Fix the value of ECAL  DQM summary report, so that it shows "NO DAQ" when ECAL is out.

### CODE REVIEW

**Comment by deguio** [comment]
+1

**Comment by deguio** [comment]
@mengleisun 
could you please back port this to 73 as well?
thanks,
F.

**Comment by davidlange6** [comment]
@cmsbuild, please test

**Comment by davidlange6** [comment]
+1

**Comment by mengleisun** [comment]
@deguio 
Hi Federico,
I have sent another PR for 7_3_X. 

cheers,
Menglei

**Pull request merged**
