### PR TITLE
[102X][updated GT] Offline GT, add HcalRespCorrsRcd TAG

### PR DESCRIPTION
**Pull request by lpernie**
# Update GT:
-  Add new TAG to offline GT: 102X_dataRun2_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/102X_dataRun2_v1/101X_dataRun2_v8
-  Add new TAG to offline relval GT: 102X_dataRun2_relval_v1
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/102X_dataRun2_relval_v1/101X_dataRun2_relval_v8

### CODE REVIEW

**Comment by lpernie** [comment]
please test

**Comment by fabiocos** [comment]
@lpernie is there an issue here. or are you ready to sign it? In that case I would like to integrate it before building CMSSW_10_2_0_pre3

**Comment by arunhep** [comment]
@fabiocos
Luca is on leave this week so that's why the delay. Thanks for considering this.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
