### PR TITLE
Reverting to AK4 CHS jets for DQM PNet monitoring

### PR DESCRIPTION
**Pull request by marinakolosova**
This is a fix to PR [416555](https://github.com/cms-sw/cmssw/pull/41655/)

* After discussing with @missirol, the ParticleNet monitoring should only be in HLTMonitor sequences.
* After discussing with @rgerosa and Stephane Cooperstein, we decided to revert to using CHS jets. The PNet training used currently in the DQM (older training) is not supported for Puppi, only for CHS jets. The new training for 13-0-X is only evaluated at the MiniAOD level, not at RECO, and for this reason, we revert to using CHS jets for the DQM monitoring.

Backports needed in:
CMSSW_13_1_X
CMSSW_13_0_X

### CODE REVIEW

**Comment by perrotta** [comment]
please test workflow 140.031

**Comment by perrotta** [comment]
Thank you @marinakolosova !

**Comment by perrotta** [comment]
type bug-fix

**Comment by emanueleusai** [comment]
+1

**Comment by marinakolosova** [comment]
Hi all, from our side everything looks ok, the PNet scores for AK4 CHS are being evaluated and the workflow is running as expected. No further update is needed for this PR, I will proceed with the backports. Thank you.

> Hi,
> 
> Just to add some further explanations here - the offline ParticleNet jet tagging for AK4 jets was updated recently (including regression+tau ID/reconstruction, on PUPPI jets) and backported to CMSSW_13_0_X #40745. The new network runs on miniAOD updates and cannot be run in the RECO step, whereas the previous version could be evaluated on either RECO or miniAOD inputs, and was trained on CHS jets. Since the DQM workflow is from the RECO/AOD as far as I understood, the new tagger is difficult to integrate. As a solution, we use the older offline tagger on CHS jets for the DQM - the b-tagging outputs should be highly correlated.
> 
> Please hold off on integrating this PR until @marinakolosova has a chance to fully test this.

**Comment by perrotta** [comment]
+1

**Pull request merged**
