### PR TITLE
Do not call methods on EcalTrigTowerConstituentsMap nullptr

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

This fixes an UBSAN related error.

#### PR validation:

Code compiles and workflow 20034.0 does not generate the warning.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by civanch** [comment]
+1

this is pure technical fix.

**Comment by AdrianoDee** [comment]
+upgrade

**Comment by rappoccio** [comment]
+1

technical PR

**Pull request merged**
