### PR TITLE
Replace DecodingStructure struct with local unsigned integers

### PR DESCRIPTION
**Pull request by IzaakWN**
#### PR description:

Replace `DecodingStructure` struct with local unsigned integer to solve issue https://github.com/cms-sw/cmssw/issues/27533.

#### PR validation:

Successfully compiled and ran local test with `SerializationSiPixelObjects`.

### CODE REVIEW

**Comment by fabiocos** [comment]
please test

**Comment by IzaakWN** [comment]
Please hold off merging this. So far it seems to solve the issue #27533, but we found different ones. We still need to test the logic and patch this PR.

**Comment by IzaakWN** [comment]
The new commit, https://github.com/cms-sw/cmssw/pull/27712/commits/4ee24edec85c16ae6bbaca69ac127202e1e7b620, should fix the new issues, which was caused by the difference between
```
*(char_it + int)
```
and 
```
(*char_it + int)
```
where `char_it` is of type `std::vector<char>::const_iterator`. You can see for yourself with this simple test code: http://cpp.sh/7rjar

**Comment by fabiocos** [comment]
please test

**Comment by pohsun** [comment]
+1

**Comment by ggovi** [comment]
+1

**Comment by fabiocos** [comment]
@IzaakWN @pohsun @ggovi are the differences in the DQM tests (all for Run3, almost completely in HLT histograms) expected?

**Comment by mmusich** [comment]
@fabiocos this PR should not change any physics quantity.
Can you please hold it off?

**Comment by mmusich** [comment]
@IzaakWN I see this is completely changing the cluster charges e.g. in 2018A:

https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_11_0_X_2019-08-07-2300+634099/32999/136.85_RunEGamma2018A+RunEGamma2018A+HLTDR2_2018+RECODR2_2018reHLT_skimEGamma_Offline_L1TEgDQM+HARVEST2018_L1TEgDQM/PixelPhase1_Tracks.html

image

image

this cannot be desired.

**Comment by fabiocos** [comment]
hold

**Comment by mmusich** [comment]
@IzaakWN please discard my comment https://github.com/cms-sw/cmssw/pull/27712#issuecomment-520443573, I had apparently looked to the older comparison done still before the bug-fix introduced in  https://github.com/cms-sw/cmssw/pull/27712/commits/4ee24edec85c16ae6bbaca69ac127202e1e7b620.
Still there is some disagreement in the Run3 simulation workflows (where a real HLT menu, as opposed to the fake one run in the other relvals) in the HLT folders:
   * 2021: https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_11_0_X_2019-08-08-2300+634099/33022/11634.0_TTbar_14TeV+TTbar_14TeV_TuneCUETP8M1_2021_GenSimFull+DigiFull_2021+RecoFull_2021+HARVESTFull_2021+ALCAFull_2021/
   * 2023: https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_11_0_X_2019-08-08-2300+634099/33022/12434.0_TTbar_14TeV+TTbar_14TeV_TuneCUETP8M1_2023_GenSimFull+DigiFull_2023+RecoFull_2023+HARVESTFull_2023+ALCAFull_2023/

**Comment by christopheralanwest** [comment]
please test

**Comment by IzaakWN** [comment]
Hi all, sorry for the mess. The new commit, https://github.com/cms-sw/cmssw/pull/27712/commits/b15a7af321e6aec06a876611cb19cf40ed77001c, should fix the issues. Similar to the my previous commit, https://github.com/cms-sw/cmssw/pull/27712/commits/4ee24edec85c16ae6bbaca69ac127202e1e7b620, I had to be careful how to shift a `std::vector<char>::const_iterator` type:
```
*(char_it + 1 + int)
```
instead of
```
*(char_it + int) >> 8
```
I checked the behavior in this simple test code: http://cpp.sh/32ete, and found the same output.

**Comment by ggovi** [comment]
+1

**Comment by fabiocos** [comment]
unhold

no difference is observed any more in the tests

**Comment by pohsun** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
