### PR TITLE
Fix CondTools/Geometry scripts

### LINKED ISSUE #32822: Run 2 geometry DB payload creation scripts terminate with errors
Two scripts that create geometry DB payloads for Run 2 currently terminate with errors:
```
CondTools/Geometry/test/writehelpers/createExtended2017Plan1Payloads.sh
CondTools/Geometry/test/writehelpers/createExtended2018Payloads.sh
```
They need to be debugged and fixed. The misspelling of  "Perecent" in `createExtended2017Plan1Payloads.sh` occurs three times. Also, the `TrackerGeometricDetESModule` has to be deleted from both scripts.

Note that it is not clear at this time whether new Run 2 geometry DB payloads will be needed in the future, so fixing these scripts is not a priority.

### PR DESCRIPTION
**Pull request by mmusich**
fixes #32822 

#### PR description:

   * Addresses https://github.com/cms-sw/cmssw/issues/32822. 
   * Removed `TrackerGeometricDetESModule` from xml writers as discussed [here](https://github.com/cms-sw/cmssw/pull/32361#discussion_r534080377).
   * Profited of this to  `CondDB_cfi` in lieu of `CondDBCommon_cfi` (deprecated)
   * Since 2019 geometry does not exist in https://github.com/cms-sw/cmssw/tree/master/Configuration/Geometry/python I've removed the corresponding scripts.

#### PR validation:

All executable scripts run to completion now.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

No backport needed.

### CODE REVIEW

**Comment by mmusich** [comment]
type bug-fix

**Comment by mmusich** [comment]
@cmsbuild please test

**Comment by ggovi** [comment]
+1

**Comment by qliphy** [comment]
+1

**Comment by cvuosalo** [comment]
@mmusich Thanks for fixing these issues.

**Pull request merged**
