### PR TITLE
Realistic phase1 hf reco retry

### PR DESCRIPTION
**Pull request by igv4321**
The content of this PR is the same as the PR #15324 but with merge conflicts fixed. Below are the original comments which came with PR #15324:

Implementation of the "HFFlexibleTimeCheck" Phase 1 HF reconstruction algorithm with associated database classes. Some refactoring of the existing code to eliminate duplication.

This pull request has been discussed at
https://indico.cern.ch/event/559519/contributions/2257746/attachments/1317838/1975047/notes.pdf

I would appreciate quick approval. There are some changes in DataFormats needed for subsequent developments.

### CODE REVIEW

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by kpedro88** [comment]
@slava77 @mmusich @ggovi please sign if possible

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/15419 	9c259b4
- repeated approval of the same code changes as were available in https://github.com/cms-sw/cmssw/pull/15324	f2734c7
 and signed in https://github.com/cms-sw/cmssw/pull/15324#issuecomment-238028967 . The previous PR apparently became unmergeable due to independent context line changes in CondCore from a mix of #15357 and #15320
- jenkins tests pass and comparisons with baseline show no differences
- local tests done for signoff of #15324 were not repeated: the results should be the same.

**Comment by abdoulline** [comment]
@mmusich @ggovi 
please, revise and make your comments

**Comment by franzoni** [comment]
+1

@igv4321 
with reference to https://github.com/cms-sw/cmssw/pull/15324#issuecomment-238220674
the only class in CondFormats/HcalObjects which is associated to a record is defined in HFPhase1PMTParams.h . 
All other files in that package are not 'HcalObjects' , even though many of them are predisposed for serializations (BOOST_CLASS_EXPORT_KEY) - unless you're planning to match them to a record in the future ?
cheers @franzoni @mmusich

**Comment by igv4321** [comment]
@franzoni
HFPhase1PMTParams is a container of HFPhase1PMTData objects. HFPhase1PMTData by itself includes a polymorphic container which can store anything derived from AbsHcalFunctor. Naturally, in order to keep the full flexibility of polymorphic design, individual records are not associated with various classes derived from AbsHcalFunctor -- we want to be able to change those classes as necessary without replacing the code which fetches them from the event setup.

**Comment by abdoulline** [comment]
@ggovi 
Giacomo, your move, please...

**Comment by ggovi** [comment]
+1

**Comment by kpedro88** [comment]
@igv4321 merge conflicts...

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by igv4321** [comment]
Should be mergeable now...

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/15419 1b9109c
- the same code changes as already approved earlier (https://github.com/cms-sw/cmssw/pull/15419#issuecomment-239302107). Context lines changed in  CondCore/HcalPlugins/src/plugin.cc which apparently has triggered a conflict
- jenkins tests pass and comparisons with baseline show no differences (the new code is not tested in standard workflows)

**Pull request merged**
