### PR TITLE
Puppi candidates for b tagging of Puppi jets in all eras (91X)

### PR DESCRIPTION
**Pull request by ferencek**
This is a 91X backport of https://github.com/cms-sw/cmssw/pull/18666

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by slava77** [comment]
@ferencek 
release 91X is closed for new features 

Please close this PR of provide justification why this has to go in.
Nominally, JME POG has to invalidate the latest 91X campaign for this to go in.

**Comment by ferencek** [comment]
@slava77, can you please clarify what this JME POG campaign is? What release is being used for it?

As far as I see, the final 9_1_0 hasn't yet been cut so I was under the impression that small analysis-level changes to MiniAOD are still allowed.

**Comment by slava77** [comment]
On 5/10/17 7:57 AM, Dinko Ferencek wrote:
> @slava77 <https://github.com/slava77>, can you please clarify what this
> JME POG campaign is? What release is being used for it?

Sorry, I meant "BTV"

> 
> As far as I see, the final 9_1_0 hasn't yet been cut so I was under the
> impression that small analysis-level changes to MiniAOD are still allowed.

miniAOD is a part of the standard workflow.
So, no more changes are expected, unless it's a bug.
And to be declared a bug, the responsible group should invalidate the
release in the latest relval campaing.

**Comment by ferencek** [comment]
@slava77, OK, in this case @imarches and @carolinecollard should comment as well but I think it is fine for the BTV POG to have this feature included starting from the 92X release cycle and there is no need to invalidate the latest 91X relval campaign just for this reason. However, if it gets invalidated for some other reason, I guess we could then sneak in this PR, right?

**Comment by slava77** [comment]
On 5/10/17 8:10 AM, Dinko Ferencek wrote:
> @slava77 <https://github.com/slava77>, OK, in this case @imarches
> <https://github.com/imarches> and @carolinecollard
> <https://github.com/carolinecollard> should comment as well but I think
> it is fine for the BTV POG to have this feature included starting from
> the 92X release cycle and there is no need to invalidate the latest 91X
> relval campaign just for this reason. However, if it gets invalidated
> for some other reason, I guess we could then sneak in this PR, right?

due to issues with pixel geometry, the 91X will be a very short cycle,
aiming [in the context of phase-1/0 standard miniAOD] primarily
for just  May commissioning with beams and CTPPS detectors.

**Comment by ferencek** [comment]
@slava77, if that means that for stable data-taking in June we plan to use 92X, then I think we can close this PR.

**Comment by slava77** [comment]
backport of #18666

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/18667	6d68c61
- the same commit/topic branch as the 92X version #18666 . This changes b-tag discriminator variables in the default miniAOD AK4 puppi jets. 
    - This PR can be merged if other features go in to 91X as part of miniAOD or other related (upstream) changes
    - I put this PR on hold to be more clear that it's not ready to merge by (not)change policy

**Comment by slava77** [comment]
hold

- I put this PR on hold to be more clear that it's not ready to merge by (not)change policy

**Comment by davidlange6** [comment]
Closing PR. CMSSW_9_1_X is for muon TDR upgrade changes only (CMSSW_9_2_X for data taking)

**Pull request closed without merging**
