### PR TITLE
Fix file path forgotten after 2019-->2021 migration (backport) 

### PR DESCRIPTION
**Pull request by boudoul**
as mentioned in this Issue : #26771 (thanks @christopheralanwest , and also @abdoulline , @mazarkin for noticing ) there was a mistake introduced after the 2019-->2021 migration , a file path was incorrect - This PR is fixing this issue.

PR validation:
It should not affect any std WF (where the geometry is read via the DB) , but I ran few events calling explicitely the 2021 XML :
runTheMatrix.py -l 11623 --command '--geometry Extended2021'

#### if this PR is a backport please specify the original PR:
Backport of the 11_X PR #26856

### CODE REVIEW

**Comment by boudoul** [comment]
type bugfix

**Comment by ianna** [comment]
-1

The referenced xml file location does not conform to the CMS coding rules (See rule No 5 in https://github.com/cms-sw/cms-sw.github.io/blob/master/cms_coding_rules.md)

**Comment by ianna** [comment]
please test

**Comment by cvuosalo** [comment]
+1

**Comment by kpedro88** [comment]
backport of #26856

**Comment by kpedro88** [comment]
+upgrade

**Comment by fabiocos** [comment]
+1

**Pull request merged**
