### PR TITLE
Photos createHistoryEntries

### PR DESCRIPTION
**Pull request by mseidel42**
#### PR description:

Photos adjusts the momenta of resonance decay products to compensate for the photon emission. With the `createHistoryEntries` option also it stores copies of the original decay products, needed for Born-level studies. The status code is set to `746` (P-H-O) which does not interfere with Pythia status codes.

#### PR validation:

Z boson and its decay products:
```
 idx  |    ID -       Name |Stat|  Mo1  Mo2  Da1  Da2 |nMo nDa|    pt       eta     phi   |     px         py         pz        m     |
   46 |    23 -         Z0 | 62 |   15   15   59  220 |  1  5 |   6.117      6.611  2.654 |     -5.405      2.863   2273.266   91.033 |
altered by Photos:
   59 |    13 -        mu- |  1 |   46   46   -1   -1 |  1  0 |  45.616      3.950  1.162 |     18.124     41.861   1183.619    0.106 |
   60 |   -13 -        mu+ |  1 |   46   46   -1   -1 |  1  0 |  44.536      3.869 -2.114 |    -23.002    -38.136   1066.140    0.106 |
added by Photos:
  218 |    22 -      gamma |  1 |   46   46   -1   -1 |  1  0 |   1.011      3.840 -2.120 |     -0.527     -0.862     23.506   -0.000 |
  219 |    13 -        mu- | 746 |   46   46   -1   -1 |  1  0 |  45.617      3.950  1.162 |     18.124     41.862   1183.625    0.106 |
  220 |   -13 -        mu+ | 746 |   46   46   -1   -1 |  1  0 |  45.547      3.868 -2.114 |    -23.529    -38.998   1089.641    0.106 |
```
Note that the additional muon copies do not have `status=1`, so they will not be reconstructed.

@bendavid

### CODE REVIEW

**Comment by qliphy** [comment]
please test

**Comment by qliphy** [comment]
please test

**Comment by qliphy** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
