### PR TITLE
updating GENSIM strings

### PR DESCRIPTION
**Pull request by prebello**
This PR aims to update GENSIM strings to be applied in next pre-releases.

FYI @fabiocos @fabozzi

### CODE REVIEW

**Comment by prebello** [comment]
please test

**Comment by fabozzi** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
@smuzaffar what is wrong with the comparison job? 8 hours seem quite a lot of time, and before this looked stuck for about 2 days

**Comment by smuzaffar** [comment]
something must be wrong with either this PR or IB. First comparison started two days ago and was aborted after 6 hours of running ( https://cmssdt.cern.ch/jenkins/job/compare-root-files-short-matrix/26415/console ) and then current comparison is running for last 4 hours ( https://cmssdt.cern.ch/jenkins/job/compare-root-files-short-matrix/26427/console ). 

There is one root.exe process which is running for last 1.5hours, I attached to it and this is where is it hanging

```
> ps
11348 08:09                  \_ /bin/sh -ex /build/cmsbld/jenkins/workspace/compare-root-files-short-matrix/results/alternative-comparison/command-250202.181
11349 08:09                      \_ /bin/bash /build/cmsbld/jenkins/workspace/compare-root-files-short-matrix/results/alternative-comparison/250202.181/makeDiff.sh /build/cmsbld/jenkins/workspace/compare-root-files-short-matrix/results/files/250202.181_TTbar_13UP18+TTbar_13UP18+PREMIXUP18_PU25+DIGIPRMXLOCALUP18_PU25+RECOPRMXUP18_PU25+HARVESTUP18_PU25/CMSSW_10_2_X_2018-05-07-1100-DQM_V0001_R000000001__Global__CMSSW_X_Y_Z
11351 08:09                          \_ root -l -b
11353 08:09                              \_ /cvmfs/cms-ib.cern.ch/nweek-02523/slc6_amd64_gcc630/lcg/root/6.12.07-gnimlf2/bin/root.exe -splash -l -b
....
> gdb -p 11353
#0  0x00007f56f160fa05 in THashList::RecursiveRemove(TObject*) () from /cvmfs/cms-ib.cern.ch/nweek-02523/slc6_amd64_gcc630/lcg/root/6.12.07-gnimlf2/lib/libCore.so
#1  0x00007f56f160fa3b in THashList::RecursiveRemove(TObject*) () from /cvmfs/cms-ib.cern.ch/nweek-02523/slc6_amd64_gcc630/lcg/root/6.12.07-gnimlf2/lib/libCore.so
#2  0x00007f56f160fa3b in THashList::RecursiveRemove(TObject*) () from /cvmfs/cms-ib.cern.ch/nweek-02523/slc6_amd64_gcc630/lcg/root/6.12.07-gnimlf2/lib/libCore.so
#3  0x00007f56f160fa3b in THashList::RecursiveRemove(TObject*) () from /cvmfs/cms-ib.cern.ch/nweek-02523/slc6_amd64_gcc630/lcg/root/6.12.07-gnimlf2/lib/libCore.so
#4  0x00007f56f160fa3b in THashList::RecursiveRemove(TObject*) () from /cvmfs/cms-ib.cern.ch/nweek-02523/slc6_amd64_gcc630/lcg/root/6.12.07-gnimlf2/lib/libCore.so
#5  0x00007f56f160fa3b in THashList::RecursiveRemove(TObject*) () from /cvmfs/cms-ib.cern.ch/nweek-02523/slc6_amd64_gcc630/lcg/root/6.12.07-gnimlf2/lib/libCore.so
#6  0x00007f56f160fa3b in THashList::RecursiveRemove(TObject*) () from /cvmfs/cms-ib.cern.ch/nweek-02523/slc6_amd64_gcc630/lcg/root/6.12.07-gnimlf2/lib/libCore.so
#7  0x00007f56f16182e9 in TList::RecursiveRemove(TObject*) () from /cvmfs/cms-ib.cern.ch/nweek-02523/slc6_amd64_gcc630/lcg/root/6.12.07-gnimlf2/lib/libCore.so
#8  0x00007f56f160fa3b in THashList::RecursiveRemove(TObject*) () from /cvmfs/cms-ib.cern.ch/nweek-02523/slc6_amd64_gcc630/lcg/root/6.12.07-gnimlf2/lib/libCore.so
#9  0x00007f56f14f3133 in TROOT::RecursiveRemove(TObject*) () from /cvmfs/cms-ib.cern.ch/nweek-02523/slc6_amd64_gcc630/lcg/root/6.12.07-gnimlf2/lib/libCore.so
#10 0x00007f56f15a95a9 in TObject::~TObject() () from /cvmfs/cms-ib.cern.ch/nweek-02523/slc6_amd64_gcc630/lcg/root/6.12.07-gnimlf2/lib/libCore.so
#11 0x00007f56e63fcf19 in TFrame::~TFrame() () from /cvmfs/cms-ib.cern.ch/nweek-02523/slc6_amd64_gcc630/lcg/root/6.12.07-gnimlf2/lib/libGraf.so
#12 0x00007f56e6578996 in TPad::Clear(char const*) () from /cvmfs/cms-ib.cern.ch/nweek-02523/slc6_amd64_gcc630/lcg/root/6.12.07-gnimlf2/lib/libGpad.so
#13 0x00007f56e6fa62a6 in compareInDir(TFile*, TFile*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned int, unsigned int) () from /build/cmsbld/jenkins/workspace/compare-root-files-short-matrix/results/alternative-comparison/250202.181/compareValHists_C.so
#14 0x00007f56e6fa7a2b in cmpLRD(TFile*, TFile*, char const*, TPRegexp*, TPRegexp*, unsigned int, unsigned int) () from /build/cmsbld/jenkins/workspace/compare-root-files-short-matrix/results/alternative-comparison/250202.181/compareValHists_C.so
#15 0x00007f56e6fa793e in cmpLRD(TFile*, TFile*, char const*, TPRegexp*, TPRegexp*, unsigned int, unsigned int) () from /build/cmsbld/jenkins/workspace/compare-root-files-short-matrix/results/alternative-comparison/250202.181/compareValHists_C.so
#16 0x00007f56e6fa793e in cmpLRD(TFile*, TFile*, char const*, TPRegexp*, TPRegexp*, unsigned int, unsigned int) () from /build/cmsbld/jenkins/workspace/compare-root-files-short-matrix/results/alternative-comparison/250202.181/compareValHists_C.so
#17 0x00007f56e6fa793e in cmpLRD(TFile*, TFile*, char const*, TPRegexp*, TPRegexp*, unsigned int, unsigned int) () from /build/cmsbld/jenkins/workspace/compare-root-files-short-matrix/results/alternative-comparison/250202.181/compareValHists_C.so
#18 0x00007f56e6fa793e in cmpLRD(TFile*, TFile*, char const*, TPRegexp*, TPRegexp*, unsigned int, unsigned int) () from /build/cmsbld/jenkins/workspace/compare-root-files-short-matrix/results/alternative-comparison/250202.181/compareValHists_C.so
#19 0x00007f56e6fa7dcb in compareAll(TFile*, TFile*, unsigned int, unsigned int, char const*, char const*) () from /build/cmsbld/jenkins/workspace/compare-root-files-short-matrix/results/alternative-comparison/250202.181/compareValHists_C.so
#20 0x00007f56e6f8f090 in ?? ()
#21 0x00007fff239f0760 in ?? ()
#22 0x00007f56e6fa7bc0 in ?? () from /build/cmsbld/jenkins/workspace/compare-root-files-short-matrix/results/alternative-comparison/250202.181/compareValHists_C.so
#23 0x00007f56e6f8e000 in ?? ()
#24 0x00000000ee3ee951 in ?? ()
#25 0x00007f56ee465940 in ?? () from /cvmfs/cms-ib.cern.ch/nweek-02523/slc6_amd64_gcc630/lcg/root/6.12.07-gnimlf2/lib/libCling.so
#26 0x00007fff239f0bd0 in ?? ()
#27 0x0000000001e35af0 in ?? ()
#28 0x00007f56ee3ef1c4 in cling::Interpreter::RunFunction(clang::FunctionDecl const*, cling::Value*) [clone .part.312] () from /cvmfs/cms-ib.cern.ch/nweek-02523/slc6_amd64_gcc630/lcg/root/6.12.07-gnimlf2/lib/libCling.so
#29 0x00007f56ee3f360d in cling::Interpreter::EvaluateInternal(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, cling::CompilationOptions, cling::Value*, cling::Transaction**, unsigned long) () from /cvmfs/cms-ib.cern.ch/nweek-02523/slc6_amd64_gcc630/lcg/root/6.12.07-gnimlf2/lib/libCling.so
#30 0x00007f56ee3f37d1 in cling::Interpreter::process(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, cling::Value*, cling::Transaction**, bool) () from /cvmfs/cms-ib.cern.ch/nweek-02523/slc6_amd64_gcc630/lcg/root/6.12.07-gnimlf2/lib/libCling.so
#31 0x00007f56ee48812f in cling::MetaProcessor::process(llvm::StringRef, cling::Interpreter::CompilationResult&, cling::Value*, bool) () from /cvmfs/cms-ib.cern.ch/nweek-02523/slc6_amd64_gcc630/lcg/root/6.12.07-gnimlf2/lib/libCling.so
#32 0x00007f56ee37422a in HandleInterpreterException(cling::MetaProcessor*, char const*, cling::Interpreter::CompilationResult&, cling::Value*) () from /cvmfs/cms-ib.cern.ch/nweek-02523/slc6_amd64_gcc630/lcg/root/6.12.07-gnimlf2/lib/libCling.so
#33 0x00007f56ee384cab in TCling::ProcessLine(char const*, TInterpreter::EErrorCode*) () from /cvmfs/cms-ib.cern.ch/nweek-02523/slc6_amd64_gcc630/lcg/root/6.12.07-gnimlf2/lib/libCling.so
#34 0x00007f56f15713f2 in TApplication::ProcessLine(char const*, bool, int*) () from /cvmfs/cms-ib.cern.ch/nweek-02523/slc6_amd64_gcc630/lcg/root/6.12.07-gnimlf2/lib/libCore.so
#35 0x00007f56f17f7fce in TRint::ProcessLineNr(char const*, char const*, int*) () from /cvmfs/cms-ib.cern.ch/nweek-02523/slc6_amd64_gcc630/lcg/root/6.12.07-gnimlf2/lib/libRint.so
#36 0x00007f56f17f831f in TRint::HandleTermInput() () from /cvmfs/cms-ib.cern.ch/nweek-02523/slc6_amd64_gcc630/lcg/root/6.12.07-gnimlf2/lib/libRint.so
#37 0x00007f56f16a5fbd in TUnixSystem::CheckDescriptors() () from /cvmfs/cms-ib.cern.ch/nweek-02523/slc6_amd64_gcc630/lcg/root/6.12.07-gnimlf2/lib/libCore.so
#38 0x00007f56f16a72fb in TUnixSystem::DispatchOneEvent(bool) () from /cvmfs/cms-ib.cern.ch/nweek-02523/slc6_amd64_gcc630/lcg/root/6.12.07-gnimlf2/lib/libCore.so
#39 0x00007f56f15d8774 in TSystem::InnerLoop() () from /cvmfs/cms-ib.cern.ch/nweek-02523/slc6_amd64_gcc630/lcg/root/6.12.07-gnimlf2/lib/libCore.so
#40 0x00007f56f15d74df in TSystem::Run() () from /cvmfs/cms-ib.cern.ch/nweek-02523/slc6_amd64_gcc630/lcg/root/6.12.07-gnimlf2/lib/libCore.so
#41 0x00007f56f156dc2f in TApplication::Run(bool) () from /cvmfs/cms-ib.cern.ch/nweek-02523/slc6_amd64_gcc630/lcg/root/6.12.07-gnimlf2/lib/libCore.so
#42 0x00007f56f17f9842 in TRint::Run(bool) () from /cvmfs/cms-ib.cern.ch/nweek-02523/slc6_amd64_gcc630/lcg/root/6.12.07-gnimlf2/lib/libRint.so

```

**Comment by fabozzi** [comment]
Is it stuck at the new premix workflow 250202.181 recently added into short matrix? i.e.

https://github.com/cms-sw/cmssw/pull/23073/files#diff-158552283ab1ecfe0f90deb9c354d862R79

**Comment by smuzaffar** [comment]
@fabozzi , yes looks like it is stuck in the new workflow 250202.181

**Comment by smuzaffar** [comment]
@fabozzi , yes looks like it is stuck in the new workflow 250202.181

**Comment by fabozzi** [comment]
Is this happening only for this PR? I cannot understand how a GENSIM recycling update can have an impact on the comparison of DQM histograms.

**Comment by fabozzi** [comment]
Let me add @makortel in CC

**Comment by prebello** [comment]
it is affecting DQM FSQ code implementation as well #23158 
Test is not ending because of this wf

**Comment by fabozzi** [comment]
I have made a transfer of the new 10_2_0_pre2 MinBias GENSIM input to CERN. It is the only external input for the 250202.181 workflow

**Comment by makortel** [comment]
I have no clue why comparisons would take long time for 250202.181. The workflow itself should look like "2018 ttbar+pileup" to the system (ok, we don't have 2018 classical mixing pileup workflow in the short matrix / PR tests).

Do the comparison scripts have any workflow-specific parts (that could have been forgotten to update for 250202.181)?

Is there any way to see the output of the `makeDiff.sh` (to see what exactly the script is doing)?

**Comment by fabozzi** [comment]
please test

**Comment by fabozzi** [comment]
Even this new attempt of comparison has been aborted.

**Comment by makortel** [comment]
@fabozzi Is the culprit again 250202.181? My best idea would be to get access to the output of `makeDiff.sh` to see what it is doing (in addition to the earlier stack trace). @smuzaffar, is there any way to do that?

**Comment by fabozzi** [comment]
@makortel 
yes, it was stuck again at 250202.181:
https://cmssdt.cern.ch/jenkins/job/compare-root-files-short-matrix/26452/console

**Comment by makortel** [comment]
@smuzaffar @fabozzi 
Let me ask another clarification: how do we know it is 250202.181 that is stuck? From the log it is the last workflow for which the alternative-comparisons is launched (because it is the last workflow in the list?), but it is not clear to me which line(s) in the log say that this workflow is the stuck one (ok, last time 
@smuzaffar checked it explicitly https://github.com/cms-sw/cmssw/pull/23135#issuecomment-387310933).

This PR likely changes ~everything for 250202.181 (as the pileup GEN-SIM is changed). But the scripts should have some minimum thresholds for the level of changes to limit the time and output for such cases, right? Or could it be that there are too many larger-than-highest-threshold changes?

**Comment by smuzaffar** [comment]
@makortel , as you noticed in my comment ( https://github.com/cms-sw/cmssw/pull/23135#issuecomment-387310933 ) , workflow 250202.181 was the last workflow to run and was the only workflow running at that time for more than  3 hours.

Currently there is 6 hours timeout for full comparison job but I agree that we should add some timeout per comparison job too. Is 30mins/comparison is good enough estimate?

**Comment by makortel** [comment]
@smuzaffar Per-comparison-job timeout is fine for me, but I'd still like to understand why 250202.181 is causing problems now (while presumably other pileup workflows have not caused similar problems earlier when their pileup MinBias GEN-SIM has been updated).

**Comment by slava77** [comment]
@cmsbuild please test

looks like the old tests/console are not available anymore

**Comment by makortel** [comment]
`makeDiff.sh` without any limits took 5.5 hours and produced a PDF of 256 MB. But it is not clear to me from the console output
https://cmssdt.cern.ch/jenkins/job/compare-root-files-short-matrix/26507/console
if any thresholds are applied in practice.

**Comment by slava77** [comment]
On 5/16/18 9:34 AM, Matti Kortelainen wrote:
> |makeDiff.sh| without any limits took 5.5 hours and produced a PDF of
> 256 MB. But it is not clear to me from the console output
> https://cmssdt.cern.ch/jenkins/job/compare-root-files-short-matrix/26507/console
> if any thresholds are applied in practice.
> 

what's "grep -c ^Save " in the log file ?

**Comment by makortel** [comment]
I didn't save the log, but the PDF has 81388 pages.

**Comment by slava77** [comment]
it appears that the threshold assignment logic failed for 250202.181
https://github.com/cms-sw/cms-bot/pull/986 should fix it

**Comment by makortel** [comment]
Thanks @slava77 !

**Comment by fabiocos** [comment]
+1 

all the differences are concentrated in the wf 250202.181 , pre2 corresponds to the integration of the new premixing code

@slava77 thank you for catching the problem in cms-bot

**Pull request merged**
