### PR TITLE
Hlt tau validation update 75 x

### PR DESCRIPTION
**Pull request by slehti**
Adding legs X in Tau+X trigger validation.

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by slehti** [comment]
Pull request #9257 is again updated... If it's still not working, could you let me know which pset you are using to test it, the tests in HLTriggerOffline/Tau/test run without problems.

**Comment by slehti** [comment]
Pull request #9257 was updated..

**Comment by slava77** [comment]
-1
rebase?

**Comment by slehti** [comment]
I switched from CMSSW_7_5_X_2015-05-23-2300 to CMSSW_7_5_X_2015-05-30-2300 (since CMSSW_7_5_X_2015-05-23-2300 ceased to exist). How do I rebase? Is it
"git rebase --onto from-CMSSW_7_5_X_2015-05-30-2300 HLTTauValidationUpdate_75X" or
"git rebase --onto from-CMSSW_7_5_X_2015-05-30-2300 official-cmssw/ CMSSW_7_5_X_2015-05-23-2300"?

**Comment by slava77** [comment]
On 6/5/15 1:00 AM, slehti wrote:
> I switched from CMSSW_7_5_X_2015-05-23-2300 to
> CMSSW_7_5_X_2015-05-30-2300 (since CMSSW_7_5_X_2015-05-23-2300 ceased to
> exist). How do I rebase? Is it
> "git rebase --onto from-CMSSW_7_5_X_2015-05-30-2300
> HLTTauValidationUpdate_75X" or
> "git rebase --onto from-CMSSW_7_5_X_2015-05-30-2300 official-cmssw/
> CMSSW_7_5_X_2015-05-23-2300"?
> 

the former.
You need to rebase your code branch, not the official tag

**Comment by slehti** [comment]
lxplus0029 > git rebase --onto from-CMSSW_7_5_X_2015-05-30-2300 HLTTauValidationUpdate_75X
Current branch HLTTauValidationUpdate_75X is up to date.
lxplus0029 >
When I switched to CMSSW_7_5_X_2015-05-30-2300, I cloned (cms-addpkg) the relevant CMSSW_7_5_X_2015-05-30-2300 code and merged (cms-merge-topic) my development branch to it. Then I pushed the code into the same branch HLTTauValidationUpdate_75X.

**Comment by slava77** [comment]
is the from- branch after you merged HLTTauValidationUpdate or is it the initial thing you get after starting (cmsrel ; git cms-init) ?
If the former (not what's needed), then indeed, it's a no-op.

**Comment by slehti** [comment]
It's the from- branch, into which I merged HLTTauValidationUpdate, then made a new branch with the same name HLTTauValidationUpdate and pushed.

**Comment by deguio** [comment]
-1

**Comment by mmusich** [comment]
-1

**Pull request closed without merging**
