### PR TITLE
Phase2 Inner Pixel Barrel layers , new radii 

### PR DESCRIPTION
**Pull request by boudoul**
Greetings
this PR is modifying the T5 Tracker geometry following some mechanics studies towards a more realistic description of the inner Pixel Barrel  (changing radii of the inner pixel barrel layers) 

Please note that since the number of modules is changed in those layers (due to the radius change) , the list of detids should also be taken into account by including this file (external) , see : 
https://github.com/cms-data/SLHCUpgradeSimulations-Geometry/pull/7

I didn't create a new scenario in runthematrix, since this is the natural evolution of T5 (but this should not be backported to 93X it's post TDR developments) , but happy to get comments/advices on this.

Modification  the raddii of three out of four inner pixel barrel layers: 
from : 
r | 29.000 | 70.146 | 117.753 | 157.388 |  
to
r | 29.000 | 60.000 | 100.000 | 140.000 |  

all work done by @ghugo83

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
The relevant changes are only in pixel.xml:

* ~40 composite materials density and composition changed
* Algorithmic positioning of RodFlipped2(3,4), RodUnflipped2(3,4) changed 
* Geometry description of Layer2(3,4), serviceRxxxZxxx changed:

serviceR74Z207 -> serviceR64Z207, serviceR74Z11 -> serviceR64Z11, serviceR74Z44 -> serviceR64Z44, serviceR74Z88 -> serviceR64Z88, serviceR74Z133 -> serviceR64Z133, serviceR74Z177 -> serviceR64Z177, serviceR74Z202 -> serviceR64Z202;

serviceR122Z207 -> serviceR105Z207, serviceR122Z11 -> serviceR105Z11, serviceR122Z44 -> serviceR105Z44, serviceR122Z88 -> serviceR105Z88, serviceR122Z133 -> serviceR105Z133, serviceR122Z177 -> serviceR105Z177, serviceR122Z202 -> serviceR105Z202;

serviceR162Z207 -> serviceR145Z207, serviceR162Z11 -> serviceR145Z11, serviceR162Z44 -> serviceR145Z44, serviceR162Z88 -> serviceR145Z88, serviceR162Z133 -> serviceR145Z133, serviceR162Z177 -> serviceR145Z177, serviceR162Z202 -> serviceR145Z202

```
-<Tubs name="supportR38Z221" rMin="38.1387*mm" rMax="67.0711*mm" dz="1*mm" startPhi="0*deg" deltaPhi="360*deg"/>
-<Tubs name="supportR78Z221" rMin="78.6851*mm" rMax="114.678*mm" dz="1*mm" startPhi="0*deg" deltaPhi="360*deg"/>
-<Tubs name="supportR126Z221" rMin="126.959*mm" rMax="154.313*mm" dz="1*mm" startPhi="0*deg" deltaPhi="360*deg"/>
+<Tubs name="supportR38Z221" rMin="38.1387*mm" rMax="56.925*mm" dz="1*mm" startPhi="0*deg" deltaPhi="360*deg"/>
+<Tubs name="supportR68Z221" rMin="68.6143*mm" rMax="96.925*mm" dz="1*mm" startPhi="0*deg" deltaPhi="360*deg"/>
+<Tubs name="supportR109Z221" rMin="109.4*mm" rMax="136.925*mm" dz="1*mm" startPhi="0*deg" deltaPhi="360*deg"/>

```

@ghugo83 and @boudoul - please, let me know if you've checked the new geometry on overlaps and also the new material composition? All material components ought to add to exactly 100% - otherwise G4 will issue a warning.

**Comment by ghugo83** [comment]
@ianna 
Yes no worry, the overlaps have been checked with 2 independent tools :)
The materials diff with respect to TDR was also looked at.

Yes one should expect a diff in the layers positioning, in the services routed from the Inner Tracker barrel layers, and in few support structures.
The support structure which is modified is a vertical one, local between IT Barrel and first Forward Disk, and which has 'holes' to let the services from the IT Barrel go through (simplified scheme).

All this is mainly concentrated in pixel.xml indeed.

**Comment by slava77** [comment]
@boudoul 
layout slides today had about 5 steps of changes.
Is the plan to integrate them all one by one in the primary tracker T# ?

For my personal convenience for tests of phase-2 software, I wish the geometry [and GEN-SIM] does not become obsolete every pre-release.

**Comment by kpedro88** [comment]
There was some discussion about using 94X for a re-miniAOD of 93X Phase2 samples. If the geometry changes, this will not be possible. We need to consider the best course of action.

**Comment by boudoul** [comment]
@slava77 : having obsolete gensim at each pre-release is also not at all my wish :) therefore the one I provided here is the baseline , the other ones that you saw in the meeting will not be integrated (except one,  I will come further to this one) but instead used in privte studies. The one I'm integrating here (unless we found real issues with it)  is The one..
There is one which is a candidate for another and speatated tracker  instead since this is a potential new concept (which  require the full cmssw release studies )  is the one with the IT tilted barrel geometry, but this is not ready to go and in any case should deserve a different WF (not for tomorrow..) 
@kpedro88 : I missed this story of miniaod in 94X.. what I can propose is meanwhile still keep T5 frozen for this purpose and create T6 ?I'm flexible ,  I was thinking anyway to remove T4 shortly

**Comment by kpedro88** [comment]
@boudoul creating T6 might be the easier/less risky approach right now. If we can use 94X for followup TDR production, it avoids more backporting to 93X.

**Comment by boudoul** [comment]
ok , I will modify accordingly , thanks !

**Comment by boudoul** [comment]
Closing this PR to make a cleaner one without touching T5

**Pull request closed without merging**
