### PR TITLE
Extension of electron matching in nanoAOD

### PR DESCRIPTION
**Pull request by sscruz**
#### PR description:

Electron matching to MC truth has some inefficiency due to FSR. This PR extends the matching to recover such cases, by adding the possibility that electrons can be matched to gendressed particles. This issue has been reported here: 
https://indico.cern.ch/event/962278/contributions/4060711/attachments/2136665/3599026/electron_matching_nano_nov4.pdf

and further discussed here: 

https://github.com/cms-nanoAOD/cmssw/issues/552

The electron matching is performed as follows:

+ Electrons are first matched to a collection of dressed electrons. This collection is identical to the GenDressedLepton collection that is stored in nanoAOD, but with a looser pt cut. If there's a match, the Electron_genPartFlav variable is set to 1 or 15, depending on the mother of the dressed lepton. Electron_genPartIdx is the index of the electron en GenPart that corresponds to the constituent of the matched dressed leptons with highest pt and abs(pdgId)==11.
+ For the electrons not matched in the previous step, the logic is the same as in the previous implementation: electrons are matched to GenPart and then Electron_genPartIdx and Electron_genPartFlav are assigned according to this match.

### CODE REVIEW

**Comment by mariadalfonso** [comment]
please test

**Comment by qliphy** [comment]
please test

**Comment by mariadalfonso** [comment]
differences from the test are minor

**Comment by sscruz** [comment]
@mariadalfonso the level of the differences is the expected one (or at least consistent with the expected ones within the available statistics). This aims to recover a 2% of unmatched electrons, so the number of electrons with genPartFlav should increase by 2% accordingly. This would be ~4 electrons with the sample we are looking at now

**Comment by mariadalfonso** [comment]
@bendavid @peruzzim @kdlong 
any comment from your side ?

**Comment by silviodonato** [comment]
> @bendavid @peruzzim @kdlong
> any comment from your side ?

kind reminder

**Comment by kdlong** [comment]
The implementation could be considerably optimized:

- Sort by pt and then find the first electron rather than visiting every element in the search through constituents (probably not a big deal since the number of constituents is small)
- Use an accessor that gives the constituents by ref rather than sorting through the genParticle collection to find a match by dR. This is important because the ref match is really unambiguous and the looping could be a significant slow down.

**Comment by kdlong** [comment]
sorry I think some of this conversation already happened on the github issue. But surely there is some way to match a ref to a slimmed version of the same product besides matching by dR. In any case, it's really the same object so you could even match on the four vector directly if you have to.

**Comment by kdlong** [comment]
Ok, thinking about it a bit more I'm convinced that the ref is probably not really matchable after the collections have been merged/skimmed.

But since they are really the same object, can you do a std::find_if matching a few unique properties like pdgId, pt, eta, phi (maybe within a small buffer)? In the current code you visit every element regardless of where the match is found which is not necessary. At the very least you could remove the copy in the loop (use a reference) and break when you find the match.

**Comment by sscruz** [comment]
thanks @kdlong I've re-implemented the matching (I believe) along the lines of what you suggest

**Comment by kdlong** [comment]
Thanks @sscruz assuming you tested that the object matching is unchanged (I can't see how it would be) this looks good to me.

**Comment by mariadalfonso** [comment]
please test

**Comment by sscruz** [comment]
hi, validating the new matching with more stats I found an obvious bug in the new implementation, that is fixed now.

**Comment by mariadalfonso** [comment]
please test

**Comment by smuzaffar** [comment]
please test
a newer full IB is available now

**Comment by mariadalfonso** [comment]
> hi, validating the new matching with more stats I found an obvious bug in the new implementation, that is fixed now.

can you upload this large stat validation in the description? 
from the integration results small stat, all seems in order

**Comment by silviodonato** [comment]
unassign analysis

**Comment by sscruz** [comment]
> > hi, validating the new matching with more stats I found an obvious bug in the new implementation, that is fixed now.
> 
> can you upload this large stat validation in the description?
> from the integration results small stat, all seems in order

sure, sorry for the late reply. this is what I have:
https://sesanche.web.cern.ch/projects/electronmatching/validation/Electron_genPartFlav.png
https://sesanche.web.cern.ch/projects/electronmatching/validation/Electron_genPartIdx.png

**Comment by mariadalfonso** [comment]
+xpog

**Comment by silviodonato** [comment]
merge

**Comment by mariadalfonso** [comment]
@sscruz 
can you prepare the backport to 10_6_X ?

note that we need to safeguard the current ongoing v8 production in 10_6_X
`(run2_nanoAOD_106Xv1 & ~run2_nanoAOD_devel).toModify(xyzTable , xyxVariable = None)`

**Comment by santocch** [comment]
+1

**Pull request merged**
