### PR TITLE
Adding capability to write out Ptrs in JetConstituentSelector (Backport of #22092)

### PR DESCRIPTION
**Pull request by rappoccio**
Backport of #22092. 

Summary there:

In order to recluster AK8 jets from MINIAOD (*), we need to write out the jet constituents in a way that can be easily read out. This adds the capability to write out Ptrs and appropriate unpacking of AK8 jets. This should not affect existing workflows. Backports incoming.

(*) This is often needed for JMAR studies. There will also be an upcoming workflow for JMAR development with nanoaod.

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
+1
- Identical to #22092
- The capability to write out the subjets constituents is disabled by default (i.e. standard workflows are not affected) but can be enabled for the possible dedicated use cases
- (In particular, reco and miniAOD outputs are not modified)

**Comment by fabiocos** [comment]
Already integrated in 10_1_0_pre1

**Comment by fabiocos** [comment]
merge

**Pull request merged**
