### PR TITLE
add track algo and originalAlgo to PackedCandidates [13_0_X]

### PR DESCRIPTION
**Pull request by slava77**
backport of #41183 (the same topic branch is used)

This PR adds track algo and originalAlgo to PackedCandidates as `uint8_t` data members; the values are filled with the same selections as other track properties (mainly driven by `pt> minPtForTrackProp`, the cut is at 0.95 GeV)

The primary use case so far is in the tag-and-probe measurements of tracking performance where general and muon tracking iterations need to be separated and the analysis is forced to use AOD, while a switch to miniAOD should be possible.

More use cases can arise for improved track quality selection and lower level debugging in miniAOD.

Tested in CMSSW_13_0_0_pre4 on `/store/relval/CMSSW_13_0_0_pre4/RelValTTbar_14TeV/GEN-SIM-RECO/PU_130X_mcRun3_2022_realistic_v2-v2/00000/{08b3cb94-2a3e-42c8-9374-46b4264dbef7.root,1a2b2a1d-133a-435c-b275-a4e3b651e71c.root,50823067-81cd-459a-baf7-aabc7851cce5.root,902c1d68-aa8e-49ea-94df-228edecdd3e9.root}` with 4000 events running PAT step (step4 from wf 11834.21).

- the sum of all products (using `edmEventSize`) compressed size increases by 238 B/ev or 0.27%
- The `packedPFCandidates` collection size increases by 0.5% or 205 B/event (from 43.3 kiB/ev)

This was proposed to XPOG in the [Jan 25 meeting](https://indico.cern.ch/event/1232579/?note=222311#6-pog-roundtable) (before the code was implemented and consequently before the file size measurements mentioned above)

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
> Hi, maybe it is my ignorance, but not ioread rules are needed to read older version of `PackedCandidate`? Or it will work fine as 0 will be returned in case of access to the missing data-member `trkAlgoPacked_`?

default value should be assigned to all new values. I can't recall if it technically happens because a default constructor is called first for in-memory objects before doing assignments from file.

**Comment by mandrenguyen** [comment]
backport of https://github.com/cms-sw/cmssw/pull/41183

**Comment by mandrenguyen** [comment]
type tracking

**Comment by mandrenguyen** [comment]
+1

**Comment by vlimant** [comment]
+1

**Comment by rappoccio** [comment]
+1

**Pull request merged**
