### PR TITLE
Bug fix so will compile -O0 -g

### PR DESCRIPTION
**Pull request by wddgit**
Fix so that TrackingLayer will compile
with -O0 0g flags.

### CODE REVIEW

**Comment by lveldere** [comment]
please test

**Comment by lveldere** [comment]
@wddgit 

Hi David

Would you mind explaining me what this new line actually does?

Thanks

Lukas

**Comment by wddgit** [comment]
Hi.  There is a static data member of the class TrackingLayer that
is declared, but it is never defined. Normally the definition should
appear once in the .cc file while the declaration is in the header and
appears everywhere the header is included.  In some cases, you
can get away with never defining such statics, but in this case
the variable is used as a functor. The gcc compiler on  the computer
I use gives the following link error because it is not defined. (I think the
compiler is correct in this case, although I do not know enough to
quote the specific section of the C++ standard).

/build/wdd/reldebugbuild/CMSSW_7_5_X_2015-06-20-1100/src/FastSimulation/Tracking/interface/TrackingLayer.h:92: undefined reference to `TrackingLayer::_eqfct'

Finally, the error only shows up when the -O0 -g options are passed to the
compiler. These turn off the optimizer and include debugging information.
I believe in other cases the optimizer removes the offending code before
the linker ever sees it and complains.

**Comment by davidlt** [comment]
@wddgit correct,
```
The member shall still be defined in a namespace scope if it
is odr-used (3.2) in the program and the namespace scope definition
shall not contain an initializer.
```
9.4.2/3 and 9.4.2/4, I have resolve plenty of such cases in CMSSW. Usually it happens once you try to pass it [data member] via reference, then it's definitely odr-used and symbol must be generated.

**Comment by lveldere** [comment]
Thanks you.
One more question before I approve:
Why is there no similar line required for TrackingLayer::_hashfct?

```
const TrackingLayer::hashfct TrackingLayer::_hashfct;
```

**Comment by davidlt** [comment]
It depends on how `_hashfct` is being used in the code. If it's odr-used, then symbol is required.
```
$ git grep _hashfct
FastSimulation/Tracking/interface/TrackingLayer.h:        static const hashfct _hashfct;
FastSimulation/Tracking/interface/TrackingLayer.h:            return _hashfct(*this)<_hashfct(layer);
```
It's not odr-used IIUC.

**Comment by lveldere** [comment]
+1

thanks

**Comment by davidlange6** [comment]
+1

**Comment by wddgit** [comment]
_hashfct is not a problem because it is only used in one inline function and the inline function that uses it is never called. It is not odr used, because it is not used at all. I suspect if it did get used in a part of the code that was compiled it would also be a problem, although these rules are complex enough I could be wrong. I did not test this. I did not fix that one simply because I did not notice it, the compiler  did not give an error.

**Pull request merged**
