### PR TITLE
Refactor ThinningTestAnalyzer::analyze()

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

Also make it a global module. Addresses #31321 point 6.

#### PR validation:

Framework unit tests succeed.

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by Dr15Jones** [comment]
Thanks!

**Comment by makortel** [comment]
@cmsbuild, please test

Hoping comparison would finish as well

**Comment by makortel** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
