### PR TITLE
Move DQMServices/StreamerIO to std::filesystem

### PR DESCRIPTION
**Pull request by camolezi**
#### PR description:
This PR is a merge of #30661 and #30762.
#30661  was already merged with master, but it seems like it was reverted on:
https://github.com/cms-sw/cmssw/commit/cb7971c744513d6a6adf80d0eca7272d66b5c190 

#30762 is a fix to make #30661 work with gcc 9.

#### PR validation:
Passed on basic runTheMatrix test.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

@vgvassilev @davidlange6

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
please test



On 21 Jul 2020, at 22:13, cmsbuild <notifications@github.com> wrote:

﻿

+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-30811/17222

  *   This PR adds an extra 24KB to repository

  *   There are other open Pull requests which might conflict with changes you have proposed:

     *   File DQMServices/StreamerIO/plugins/DQMFileIterator.cc modified in PR(s): #30857<https://github.com/cms-sw/cmssw/pull/30857>
     *   File DQMServices/StreamerIO/plugins/JsonWritingTimeoutPoolOutputModule.cc modified in PR(s): #30857<https://github.com/cms-sw/cmssw/pull/30857>
     *   File DQMServices/StreamerIO/plugins/RamdiskMonitor.cc modified in PR(s): #30857<https://github.com/cms-sw/cmssw/pull/30857>
     *   File DQMServices/StreamerIO/test/DQMStreamerOutputRepackerTest.cc modified in PR(s): #30857<https://github.com/cms-sw/cmssw/pull/30857>
     *   File DQMServices/StreamerIO/test/DQMStreamerWriteJsonAnalyzer.cc modified in PR(s): #30857<https://github.com/cms-sw/cmssw/pull/30857>

**Comment by camolezi** [comment]
can we also trigger a gcc 9 test?

**Comment by silviodonato** [comment]
please test for slc7_amd64_gcc900

**Comment by silviodonato** [comment]
any objections  @jfernan2 @andrius-k @schneiml @fioriNTU @kmaeshima ?

**Comment by jfernan2** [comment]
None so far. The tests looked OK, I did not sign yet since @camolezi asked for a gcc 9 test

**Comment by jfernan2** [comment]
The number of differences grew exponentially with the gcc9 test:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_11_2_X_2020-07-26-2300+35b44f/37983/dqm-histo-comparison-summary.html
Is there any explanation behind? Thanks

**Comment by davidlange6** [comment]
hi @jfernan2 - gcc8 and gcc9 won't give precisely the same answers. So identity is not expected in this comparison.

**Comment by jfernan2** [comment]
Thanks @davidlange6  I was surprised to see the change only in some WFs while others remain the same.

**Comment by jfernan2** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
