### PR TITLE
Add Phase2 L1T products to FEVTDEBUG EventContent

### PR DESCRIPTION
**Pull request by rekovic**
PR 11_2_X 

Adding all Phase2 L1T products to FEVTDEBUG Event Content
Also add missing KBmtf in the Muon L1T sequence.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by rekovic** [comment]
please test

**Comment by rekovic** [comment]
test parameters

 * pull_request = cms-data/L1Trigger-L1TMuon#18

**Comment by rekovic** [comment]
failing due to missing external files for TkMuons... nothing to do with this PR.
added the externals PR in test parameters, needed only for testing.

**Comment by rekovic** [comment]
please test

**Comment by rekovic** [comment]
abort

**Comment by rekovic** [comment]
please test

**Comment by rekovic** [comment]
The reason why this one is failing is that the switch to use the modfier `phase2_trackerV14` to enable in the sequence the phase2 L1T modules that depend on TrackTriggerTracks, is only present in #30482, which is not merged yet (currently failing)

**Comment by silviodonato** [comment]
test parameters

**Comment by silviodonato** [comment]
please test

**Comment by silviodonato** [comment]
moved to #30498

**Pull request closed without merging**
