### PR TITLE
Backport of lhe xml blob memory improvements to 74x

### PR DESCRIPTION
**Pull request by bendavid**
Needed for FastSim production in 74X which reads directly wmLHE output.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by davidlange6** [comment]
@bendavid - did you mean to sign this one?

**Comment by bendavid** [comment]
No, I was never able to properly test this because of global tag issues.  In the meantime this production was done by dropping the XML product on input from the cmsdriver command, so actually this is not needed anymore and can be closed.

**Pull request closed without merging**
