### PR TITLE
Fix setup writing with confdb.py for HLT

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
#### PR description:

Fix setup writing with confdb.py for HLT, as suggested by David Sperka

#### PR validation:

Explicit test - script now works!

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
type bugfix

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
