### PR TITLE
Phase2-hgx336B Make the first step to provide an option for guard ring in HGCal simulation

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Make the first step to provide an option for a guard ring in the HGCal simulation

#### PR validation:

Use the runTheMatrix test workflows

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
+geometry

**Comment by bsunanda** [comment]
@srimanob please approve this PR

**Comment by srimanob** [comment]
+Upgrade

No change is expected from this PR. 

Note that, I think it would be great to have a clear statement in the PR description of what to expect and if this will effect which geometry. Since we don't test all geometry in the PR test, so it is better to specify.

**Comment by rappoccio** [comment]
+1

**Pull request merged**
