### PR TITLE
Revert "Move traceback routine into a separate thread."

### PR DESCRIPTION
**Pull request by smuzaffar**
Reverts cms-sw/cmssw#11239

### CODE REVIEW

**Comment by Dr15Jones** [comment]
@bbockelm

**Comment by Dr15Jones** [comment]
@smuzaffar @davidlange6 @bbockelm Looking at the failures in CMSSW_7_6_X_2015-09-15-1100 I'm not convinced they were caused by this pull request. It looks to me like the failure was a binary incompatibliity because not every package dependent upon #11189 was recompiled. The reason I think this is the crashes I've looked at all happend in the destructor of ```edm::AssociationMap```. Also, the problems appear to go away in the following IB which may have had more code recompiled.

**Comment by Dr15Jones** [comment]
On the positive side for #11239 the IB RelVal logs for CMSSW_7_6_THREADED_X_2015-09-15-1100 for the crashed jobs do show the crashing thread this time. So in principal the change actually worked!

**Comment by bbockelm** [comment]
(FWIW - I ran out of time last night, but hope to fixup the broken unit test and redo the PR by tomorrow-ish)

**Comment by Dr15Jones** [comment]
Looking at the IB page
https://cmssdt.cern.ch/SDT/cgi-bin/showBuildLogs.py/slc6_amd64_gcc493/www/tue/7.6-tue-11/CMSSW_7_6_X_2015-09-15-1100

I can't pull up the full build log, however the library which has the code which is crashing is DataFormats/TrackReco and from what I can tell from this page, it appears that library was not recompiled. This would definitely cause a binary incompatibility.

**Comment by Dr15Jones** [comment]
To further back my claim, the following IB, CMSSW_7_6_X_2015-09-15-2300, didn't have the crashing problems and it did recompile DataFormats/TrackReco

https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc6_amd64_gcc493/CMSSW_7_6_X_2015-09-15-2300/DataFormats/TrackReco

**Comment by smuzaffar** [comment]
couple of strange things here
- first it should have compiled DataFormats/TrackReco in CMSSW_7_6_X_2015-09-15-1100 as your PR #11189 is part of this patch release. You Pr has explicitly modified DataFormats/TrackReco

- unit tests are still failing in CMSSW_7_6_X_2015-09-15-2300 which is a full release.

**Comment by smuzaffar** [comment]
@Dr15Jones , looks like our git-cms-sparse-checkout script ignore the empty lines. That is why your change in DataFormats/TrackReco/BuildFile.xml was not consider important and the package was not part of the patch release

**Comment by Dr15Jones** [comment]
@smuzaffar I fully agree that the unit tests failures are from #11239 which is from the bad interaction between forking and threads. Brian says he is going to fix that case.

**Pull request merged**
