### PR TITLE
Fix the vidNestedWPBitmap_Fall17V2 for electron in NANOAOD 

### PR DESCRIPTION
**Pull request by Prasant1993**
#### PR description:

This PR is to fix the 'vidNestedWPBitmap' variable for electron in NanoAOD in Run2. At present, this is not being correctly filled for Run2.  This variable is being filled by mistakenly from this PR https://github.com/cms-sw/cmssw/pull/40209  by @swertz for the electron/photon  ID variables consistency check.  We just found that this bug. Sorry, we didn't realize this mistake before.   

#### PR validation:

runTheMatrix tests have been successfully run for the following workflows :

- runTheMatrix.py -l 12434.0
- runTheMatrix.py -l 11834.0

#### Backport:

Need input from  Cross-POG convenors if  backport to CMSSW_12_6_X is needed.  It will surely go to NANOAOD V13 production. 

Tagging E/Gamma convenors for more input :   @swagata87 , @a-kapoor  @RSalvatico

### CODE REVIEW

**Comment by swagata87** [comment]
type bugfix

**Comment by swagata87** [comment]
type egamma

**Comment by a-kapoor** [comment]
enable nano

**Comment by a-kapoor** [comment]
please test

**Comment by simonepigazzini** [comment]
please test

**Comment by simonepigazzini** [comment]
+1

Thanks for the fix. There is no Run2 NanoAOD production scheduled, so at the moment for us just having this in the master is ok. Unless you have a particular use case in mind we do not see a need for any backport.

**Comment by rappoccio** [comment]
+1

**Pull request merged**
