### PR TITLE
Safeguard for nHits==0

### PR DESCRIPTION
**Pull request by AdrianoDee**
#### PR description:

Bug spotted and fixed by @missirol 

Following comments and discussion in #37933 

#### PR Backports:

- 12_3_X in #38160
- 12_4_X in #38161

### CODE REVIEW

**Comment by AdrianoDee** [comment]
type fix, trk

**Comment by AdrianoDee** [comment]
type bugfix

**Comment by AdrianoDee** [comment]
type trk

**Comment by AdrianoDee** [comment]
test parameters:

- enable_tests = gpu
- workflows_gpu = 11634.503, 11634.502, 39434.502
- workflows = 11634.501, 39434.501, 11634.502
- relvals_opt= -w standard,highstats,pileup,generator,extendedgen,production,upgrade,cleanedupgrade,ged

**Comment by AdrianoDee** [comment]
please test

**Comment by qliphy** [comment]
+1

**Pull request merged**
