### PR TITLE
use HBHE Phase1 reco for Run2/legacy, unify M0 parameters

### PR DESCRIPTION
**Pull request by kpedro88**
We now have a significantly improved (from the technical/code side) "Phase1Reconstructor" for HBHE, which was originally developed for use with the Phase 1 upgrades but will be used globally in 2017 (even with 99% of channels still using HPDs). We would prefer not to maintain two separate algorithms for local reconstruction, so we propose to move to the Phase1Reconstructor for all legacy reconstruction going forward. There are no expected changes for Method 0 reconstruction and very minimal changes for Method 2 (due to floating-point arithmetic).

In addition, this PR unifies the standard set of Method 0 parameters, as was already done for Methods 2 and 3.

There will be a subsequent PR to propagate this change to the NZS reconstruction, once all the necessary settings have been determined.

More info from @igv4321:
>Here is a summary about replacing Run 2 HBHE reconstruction code with
Phase 1 reconstruction. The reason for this replacement is, basically,
the need to continue providing reco improvements for Run 2 data.
Naturally, these improvements are made to the current reconstruction
(Phase 1) first. The design of Phase 1 HBHE reco is streamlined compared
to that of Run 2, and it allows for simpler modification and maintenance.
For example, introduction of a class "HBHEChannelInfo" allows for
a relatively straightforward addition of new information to be passed
to energy reconstruction algorithms like "Method 2", while with the
Run 2 code one would have to modify a substantial number of interfaces
and calls to achieve the same effect.
>
>Because of this, we need to replace Run 2 HBHE reconstruction with
Phase 1. This also essentially means the end of Run 2 HBHE reconstruction
maintenance and will free up people's time.
>
>There is a difference between the results obtained with Run 2 reco and
Phase 1 reco. These differences are discussed in detail in several
presentations by Halil Gamsizkan at the Phase 1 Software Task Force
meetings:
>
>https://indico.cern.ch/event/608981/contributions/2455507/attachments/1402669/2141578/rechits_run2vsPh1.pdf
>https://indico.cern.ch/event/614725/contributions/2479322/attachments/1413750/2164286/rechits_run2vsPh1_diagfix.pdf
>https://indico.cern.ch/event/615744/contributions/2484482/attachments/1417404/2170637/rechits_run2vsPh1.pdf
>
>To summarize, there are essentially no differences between Run 2 and
Phase 1 rechit energies reconstructed by "Method 0". For "Method 2",
0.2% of the rechits exhibit relative energy differences above 10^{-5}.
I believe that these differences can be attributed to the sensitivity
of "Method 2" to round-off errors (round-offs are different for Run 2
and Phase 1 codes because in some places floats were replaced with
doubles and otherwise). We have also observed differences in
chi-square which accompany the differences in energy, as well as
switches between 1-pulse and 3-pulse fits.
>
>There is, indeed, some structure to these differences, as explained in
the last talk by Halil. If you want to further investigate the reasons
for these disagreements, a substantial involvement of "Method 2"
experts into these studies will be necessary.
>
>Switch to Phase 1 also means different encoding for the rechit "aux"
words and status bits. Since this switch has to happen for 2017 reco
anyway, I don't think that this will have negative consequences for
Run 2 rereco.

attn: @mariadalfonso, @abdoulline, @hatakeyamak, @deguio

### CODE REVIEW

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
this is for 91X, I suppose.
Please let me know if there is a good reason it has to go in sooner.

**Comment by kpedro88** [comment]
I think 91X is fine but @igv4321 should comment

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by igv4321** [comment]
Well, I guess it can be delayed until 91X. However, that would also delay other things, like streamlining some of the "Method 2" internals, and people will get distracted by other things. Let me return the question: is there a good reason why this should not go into 90X?

**Comment by slava77** [comment]
On 3/1/17 6:34 PM, Igor Volobouev wrote:
> Well, I guess it can be delayed until 91X. However, that would also
> delay other things, like streamlining some of the "Method 2" internals,
> and people will get distracted by other things. Let me return the
> question: is there a good reason why this should not go into 90X?

It's a new feature and 90X is now closed for developments.
Exceptions are possible but need justifications.

**Comment by igv4321** [comment]
"New feature", hmm... HBHEPhase1Reconstructor was introduced in June 2016. Anyway, it is not a good idea to stifle the normal code development process. If you want us to put this into 91X, it should be open for development NOW.

**Comment by kpedro88** [comment]
@igv4321 can you check if all the differences in the comparisons are expected?

**Comment by igv4321** [comment]
I looked at a few comparisons. Can't see anything unexpected so far (aux words changed, etc). Slava probably has a better eye for this.

**Comment by slava77** [comment]
-1

superseded by #17688 
moving to 91X as discussed earlier in the thread

**Pull request closed without merging**
