### PR TITLE
Remove PF candidates with nan for energy [13_0_X]

### PR DESCRIPTION
**Pull request by mandrenguyen**
backport of #41473

### CODE REVIEW

**Comment by mandrenguyen** [comment]
please test

**Comment by perrotta** [comment]
urgent

**Comment by mandrenguyen** [comment]
type pf

**Comment by mandrenguyen** [comment]
+1

**Comment by perrotta** [comment]
+1
- The fix is simple enough, and I don't expect issues from the tests in the master IB
- Since this has been approved by Reco, let also merge in 13_0_X and start building a patch release which includes the fix right after

**Pull request merged**
