### PR TITLE
Cleanup redundant edm ParameterSet exist in PhysicsTools

### PR DESCRIPTION
**Pull request by jeongeun**
#### PR description:  
(Technical PR) Optimization of the module configurations: Improve maintainability by cleaning up redundant cases of edm::ParameterSet calls to `existAs` or `exist` for tracked parameters, where redundancy is based on the value being already defined by `fillDescriptions`.

As follow the previous [PR36746](https://github.com/cms-sw/cmssw/pull/36746),  [PR36989](https://github.com/cms-sw/cmssw/pull/36989), [PR37313](https://github.com/cms-sw/cmssw/pull/37313), [PR37314](https://github.com/cms-sw/cmssw/pull/37314), [PR37548](https://github.com/cms-sw/cmssw/pull/37548), [PR37772](https://github.com/cms-sw/cmssw/pull/37772), [PR37899](https://github.com/cms-sw/cmssw/pull/37899), and [PR38218](https://github.com/cms-sw/cmssw/pull/38218).

In this PR, 5 files were changed.  
PhysicsTools/PatAlgos/plugins/JetCorrFactorsProducer.cc

Here, the `extraJPTOffset`, `primaryVertices`, `rho` parameters were provided in a fillDescription.  cfipython : [cfipython/PhysicsTools/PatAlgos/JetCorrFactorsProducer_cfi.py](https://cmssdt.cern.ch/lxr/source/cfipython/PhysicsTools/PatAlgos/JetCorrFactorsProducer_cfi.py)

PhysicsTools/PatAlgos/plugins/PATElectronProducer.cc
PhysicsTools/PatAlgos/plugins/PATPhotonProducer.cc
PhysicsTools/PatAlgos/plugins/PATMuonProducer.cc
PhysicsTools/PatAlgos/plugins/PATTauProducer.cc

Here, the `userIsolation`, `genParticleMatch` parameters were provided in a fillDescription.  cfipython : [cfipython/PhysicsTools/PatAlgos/PATElectronProducer_cfi.py](https://cmssdt.cern.ch/lxr/source/cfipython/PhysicsTools/PatAlgos/PATElectronProducer_cfi.py),
[cfipython/PhysicsTools/PatAlgos/PATPhotonProducer_cfi.py](https://cmssdt.cern.ch/lxr/source/cfipython/PhysicsTools/PatAlgos/PATPhotonProducer_cfi.py)

#### PR validation:
Tested in CMSSW_12_5_X, the basic test all passed in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by jpata** [comment]
@cmsbuild please test

**Comment by jpata** [comment]
@cmsbuild please test

**Comment by jpata** [comment]
@cmsbuild please test

**Comment by jpata** [comment]
@cmsbuild please test

let's run again to make sure the input tests are OK.

**Comment by jpata** [comment]
+reconstruction
- technical cleanup of config parameters
- no reco changes or issues in tests

**Comment by qliphy** [comment]
+1

**Pull request merged**
