### PR TITLE
Digitizer validation suite updated 

### PR DESCRIPTION
**Pull request by suchandradutta**
The validation suite updated thread safe DQM framework. Cluster validation code updated as well to cope with the common utility code.  @thomaslenzi @delaere please check

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by suchandradutta** [comment]
Could not reproduce the error using 
scram b vclean && scram build -k -j 48 USER_CXXFLAGS='-fsyntax-only' COMPILER='llvm compile'

but a few other warnings are fixed now

**Comment by davidlt** [comment]
Scripts aren't checking only your PR, they check base IB + everything which is approved, but not yet in the IB + your PR. This is way you might not yet see the problem, but with next IB it could become visible.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
+1

For #14355 71f8f94b3c7b5af4c19e397488a70f504db13e97

Minor revisions to the digitizer validation suite. There should be no change in non-Phase 2 workflows. Changes to Reco code are very minimal.

The code changes are satisfactory, and Jenkins tests against baseline CMSSW_8_1_X_2016-05-04-1100 show no significant differences, as expected.

**Comment by davidlange6** [comment]
Hi @suchandradutta - the code in Phase2TrackerDigiCommon (the new and old) should move to TrackerTopology itself (or can be replaced by something already implemented in TrackerTopology). It is certainly not something sim specific. Thanks!

**Comment by suchandradutta** [comment]
@davidlange6 the code  in Phase2TrackerDigiCommon is needed by validation suite and will be move to a more specific package related to Phase2 DQM/Validation. At that point the whole of validation suite as well as the Phase2TrackerDigiCommon code will be moved there. @delaere @thomaslenzi

**Comment by boudoul** [comment]
Dear @davidlange6 and @suchandradutta : I created a branch :  
https://github.com/cms-sw/cmssw/compare/CMSSW_8_1_X...boudoul:digi_sdutta
which is exactly the same as this PR but where Phase2TrackerDigiCommon is moved to TrackerTopology as requested by @davidlange6  (+ merge conflict solved) : 
let me know if you are happy , then I can either make the PR (maybe the easiest way) or @suchandradutta can update her PR with my changes

**Comment by slava77** [comment]
-1
there are merge conflicts here now

**Comment by boudoul** [comment]
Just discussing with @suchandradutta : she will close this PR, and a new one will be created including the changes in trackertopology

**Comment by suchandradutta** [comment]
Closing this PR as a new PR created by @boudoul

**Pull request closed without merging**
