### PR TITLE
Additional info when exception thrown in SharedMemory

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

Add additional info in exception message when buffer allocation fails. This should help identify a rare problem seen with the external generator jobs.

#### PR validation:

Code compiles.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by makortel** [comment]
Comparison differences are in 11634.7 (#39803)

**Comment by makortel** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
