### PR TITLE
Import first bunch of features for NanoAOD v2

### PR DESCRIPTION
**Pull request by arizzi**
- minor fixes (genlevel masses of bosons and isEE is EB) 
- era switches for MiniAOD V1 vs V2 inputs

### CODE REVIEW

**Comment by arizzi** [comment]
please test

**Comment by arizzi** [comment]
+1 all features tested in nanoaod gitlab CI

**Comment by davidlange6** [comment]
hi @arizzi

please consider using Configuration/ProcessModifiers instead of Eras - the functionality and syntax is the same, but they are intended to express things that are not strictly time dependent (which was the intent of Eras)

**Comment by makortel** [comment]
@davidlange6 

> please consider using Configuration/ProcessModifiers instead of Eras

The package `Configuration/ProcessModifiers` does not exist in 94X (only from 10_1_0_pre1 onwards).

**Comment by davidlange6** [comment]
i guess its ~trivial for me to change that if desired [indeed I should have directed my comment to the master branch version of this PR

**Comment by arizzi** [comment]
@davidlange6 this PR is against the AN branch for which we have specific integration policies and this kind of requests are not applicable here.
Concerning the master branch, we had a thread before with a few people in CC before even coding this PR and while it was suggested that we could put that in Configuration/ProcessModifiers it was not expressed as a requirement.
If you want to clean up where eras are defined between ProcessModifier and Eras, I suggest you make a dedicated PR implementing a given policy (btw, what is such policy? how do we decide what goes in Eras and what in process modifiers?) on all existing eras and move also this one (after the master PR is merged)

**Comment by davidlange6** [comment]
> On Mar 21, 2018, at 9:20 AM, arizzi <notifications@github.com> wrote:
> 
> @davidlange6 this PR is against the AN branch for which we have specific integration policies and this kind of requests are not applicable here.
> Concerning the master branch, we had a thread before with a few people in CC before even coding this PR and while it was suggested that we could put that in Configuration/ProcessModifiers it was not expressed as a requirement.

yea - private threads get feedback from limited people - thus GitHub:)

> If you want to clean up where eras are defined between ProcessModifier and Eras, I suggest you make a dedicated PR implementing a given policy (btw, what is such policy? how do we decide what goes in Eras and what in process modifiers?) on all existing eras and move also this one (after the master PR is merged)

 I can attempt to clarify but I tried to keep it simple.  Maybe I can add this: "time of data taking" dependent configurations are eras,  configurations to handle multiple versions of the same data taking period are ProcessModifiers

**Comment by arizzi** [comment]
it doesn't seem to me the two concepts can always be completely factorized.
The eras we are defining are switching both among data taking periods and among multiple versions of the same data taking period.

**Comment by davidlange6** [comment]
There is always the potential for a middle ground yes. though I'm not sure I've seen an actual use case in this instance yet (certainly will come)

**Comment by gpetruc** [comment]
In 9_4_X, the ProcessModifiers package and the related functionality of ConfigBuilder are missing, and I don't think it's a good idea to backport an infrastructure change like that to 9_4_X.

Also, it seems to me even in the master branch the Modifier vs Era separation is not yet correctly implemented as 'run2_miniAOD_80XLegacy', 'run2_miniAOD_94XFall17', 'run2_nanoAOD_92X', are eras and not modifiers.

So, I'd rather just address that in a follow-up PR to the master branch, so that #22680 and this PR stay in sync.

**Comment by slava77** [comment]
On 3/21/18 2:44 AM, Giovanni Petrucciani wrote:
> In 9_4_X, the ProcessModifiers package and the related functionality of
> ConfigBuilder are missing, and I don't think it's a good idea to
> backport an infrastructure change like that to 9_4_X.
> 
> Also, it seems to me even in the master branch the Modifier vs Era
> separation is not yet correctly implemented as 'run2_miniAOD_80XLegacy',
> 'run2_miniAOD_94XFall17', 'run2_nanoAOD_92X', are eras and not modifiers.
> 
> So, I'd rather just address that in a follow-up PR to the master branch,
> so that #22680 <https://github.com/cms-sw/cmssw/pull/22680> and this PR
> stay in sync.

OK, makes sense

**Comment by arizzi** [comment]
@fabiocos this PR is against the AN release, can it be merged as it is ? (or do we need more signatures?)

**Comment by gpetruc** [comment]
fixed the merge conflict in Eras.py so that this is again mergeable (and cms-nanoAOD:master stays mergeable in this one)

**Comment by gpetruc** [comment]
history however now shows all commits of MAOD branch (someone with write access or @arizzi can solve it by changing the target branch twice)

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/22679	4a9085a

There is no new reco code compared to CMSSW_9_4_MAOD_X based on 
https://github.com/cms-sw/cmssw/compare/cms-sw:CMSSW_9_4_MAOD_X...cms-nanoAOD:masterUpTo128 or more precisely at the moment of the check https://github.com/cms-sw/cmssw/compare/9a0cd8d7127107bc8115badd31001d078905c0f2...4a9085a8b37f04de6ad77eb5b998b7e4203a3e92

I'd still prefer plain forward ports to be separated from AN features.

**Comment by arizzi** [comment]
please test

**Comment by arizzi** [comment]
@slava77 I think they were separated, it was just github not recomputing the base.

**Comment by fabiocos** [comment]
@arizzi @gpetruc I understand that this PR is submitted only in the 9_4_AN_X and not in the 9_4_X release because it is based on the port of 9_4_MAOD_X that will not be done in 9_4_X until the code is validated. But then of course it should, I do not see reasons to leave it behind

**Comment by arizzi** [comment]
it is submitted to 9_4_AN_X also because we need it integrated and built on short timescale, possibly bypassing some code review checks as agreed in the scope of AN releases.
Please note that a second PR will follow today.

**Comment by prebello** [comment]
+1
(based on approved tests)

**Pull request merged**
