### PR TITLE
[CPP20][L1,UPGRADE] Remove deprecated enum arithmetic

### PR DESCRIPTION
**Pull request by iarspider**
#### PR description:

Some arithmetic and logic operations on enums are deprecated in C++20. This PR aims to fix these.

#### PR validation:

Bot tests.

### CODE REVIEW

**Comment by iarspider** [comment]
please test for CMSSW_14_1_CPP20_X

**Comment by iarspider** [comment]
please test for CMSSW_14_1_CPP20_X

**Comment by makortel** [comment]
Arithmetic with enums is a sign that maybe the `enum` should really be replaced with ` constexpr` constants. I think this alternative should be explored first before going the `static_cast` route.

**Comment by iarspider** [comment]
hold
As suggested, I will replace enums with constexpr ints.

**Pull request closed without merging**
