### PR TITLE
tune variations for CP1-4 tunes

### PR DESCRIPTION
**Pull request by efeyazgan**

### CODE REVIEW

**Comment by efeyazgan** [comment]
+1

**Comment by fabiocos** [comment]
@efeyazgan this test is not really testing the addition of these fragments. I will merge them, but I assume checks were done, in case could link a reference to the studies bout these variations?

**Comment by fabiocos** [comment]
+1

**Comment by efeyazgan** [comment]
@fabiocos yes, they are verified through the usual comparisons to data we do for tunes: http://desy.de/~gunnep/TuneVariations/

**Pull request merged**
