### PR TITLE
Hcal phase1 fastsim updates

### PR DESCRIPTION
**Pull request by kpedro88**
* HF dual anode splitting:
  * introduced in https://github.com/cms-sw/cmssw/commit/12e98bd14c38e0dbeab5d976dcd67260912bae4e
  * (accidentally?) removed in https://github.com/cms-sw/cmssw/commit/f3ad3409d666dfed66dcbd0b55ca9446aec1a7c7
  * reimplemented here in a different place (to split each PE from the shower library instead of the final hit at the end, perhaps more statistically accurate)
  * extend corrections to HF depths 3, 4
* HE depth segmentation:
  * Fastsim already uses CMS database geometry by default
  * Fullsim uses TestNumbering setting to save hits per layer from 2017 onward - fastsim doesn't do this (no need, we don't store/reuse SIM info from fastsim)
  * remove TestNumbering-related settings from digitization and validation

I confirmed by looking at `hfprereco` and `hbheprereco` collections that the appropriate depths are seen in the 2017 configuration with these changes, using a recipe provided by @ssekmen.

attn: @bsunanda

### CODE REVIEW

**Comment by kpedro88** [comment]
please test

**Comment by ssekmen** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by kpedro88** [comment]
@vazzolini, @kmaeshima, @dmitrijus, @jfernan2, @vanbesien please sign

**Comment by fabiocos** [comment]
+1

**Pull request merged**
