### PR TITLE
Moved headers from src to interface in FWCore/Framework

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

These headers were being used by other packages in FWCore.

#### PR validation:

Code compiles.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by makortel** [comment]
Mmh, `all_OldVSNew_TTbar14TeV2026D60wf28234p0c_ticlTracksters_ticlSimTracksters__RECO_obj_ticlIteration.png` reco comparison shows differences for 23234.0, 28234.0, 34634.0, 34834.999. I'd guess those are random (to be reported), but let's try again.

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
No change, but other PRs seem to be showing those differences as well.

**Comment by makortel** [comment]
+1

**Comment by qliphy** [comment]
@Dr15Jones  There is conflict now after https://github.com/cms-sw/cmssw/pull/34697 is merged.
Would you please resolve it?

**Comment by Dr15Jones** [comment]
please test

**Comment by makortel** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
