### PR TITLE
Revert "migrating to multithreading of RPCPointProducer" (75X)

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
Reverts cms-sw/cmssw#9100

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
I am using this PR to check whether the problem is indeed from #9100

**Comment by Martin-Grunewald** [comment]
@smuzaffar @nclopezo 
Looks like cmsbot is in a loop stuck here, sending messages every 10 mins on "PR updated" while this is certainly not the case

**Comment by Martin-Grunewald** [comment]
@Dr15Jones  @HuguesBrun @davidlange6 
I can confirm that this revert-PR fixes the problem I observe in 75X!
Hence, for 750final to be useful for TSG, either accept this PR or fix the original PR.

**Comment by HuguesBrun** [comment]
Dear all, 

I don't understand what is happening and I am even not able yet to reproduce the problem so maybe the best is to revert the PR. 
I will resubmit it when I will have fixed this problem.

Sorry for having introduced this mess ! 
Hugues

**Pull request merged**
