### PR TITLE
[backport from 93x to 92x] Dijet Prompt DQM for JEC (#19873)

### PR DESCRIPTION
**Pull request by bobaekim**
///Trigger Paths///
HLT_DiPFJetAve40
HLT_DiPFJetAve60
HLT_DiPFJetAve80
HLT_DiPFJetAve140
HLT_DiPFJetAve200
HLT_DiPFJetAve260
HLT_DiPFJetAve320
HLT_DiPFJetAve400
HLT_DiPFJetAve500
HLT_DiPFJetAve60_HFJEC
HLT_DiPFJetAve80_HFJEC
HLT_DiPFJetAve100_HFJEC
HLT_DiPFJetAve160_HFJEC
HLT_DiPFJetAve220_HFJEC
HLT_DiPFJetAve300_HFJEC

///Histograms///
jetpt1 : pt of leading jet passed trigger and w/o offline selection
jetpt2 : pt of second leading jet passed trigger and w/o offline selection
jetptAvgB : Fill using (pt_1 + pt_2) * 0.5 , pt average before offline selection
jetptAvgA: Fill using (pt_1 + pt_2) * 0.5 , pt average after offline selection
jetptAvgAThr : Fill using (pt_1 + pt_2) * 0.5 , pt average after offline selection using dijetPtThrPSet
jetptTag : tag jet passed trigger and offline selection satisfied with fabs(eta) < 1.3
jetptPrb : probe jet passed trigger and offline selection, satisfied with fabs(eta) > 1.3 among pt_1 and pt_2
(If both pt_1 and pt_2 are satisfied with fabs(eta) < 1.3, tag and probe are randomly selected.)
jetptAsym : using (pt_prb - pt_tag)/(pt_tag + pt_prb), asymmetry of pt_tag and pt_prb
jetetaPrb : eta of probe jet
jetetaTag : eta of tag jet
ptAsymVSetaPrb : 2D historgram of pt_asym and eta_prb
etaPrbVSphiPrb : 2D historgram of eta_prb and phi_prb
jetphiPrb : phi of probe jet

### CODE REVIEW

**Comment by mtosi** [comment]
@cmsbuild, please test

**Comment by mtosi** [comment]
@bobaekim do you think we can proceed w/ the integration test, now ?

**Comment by bobaekim** [comment]
@mtosi  Dear Mia, when I did 'cms-addpkg DQMOffline/Trigger'  in 92X, there is no DQMOffline/Trigger/plugins/TriggerDQMBase.h file.
So, I copied this file from 93X to 92X then compiled, there is no compile error.
Therefore, I added 'DQMOffline/Trigger/plugins/TriggerDQMBase.h' file.

**Comment by bobaekim** [comment]
Dear Mia,

Could you let us know that how many steps left to complete this PR and when
the PR will be merge, please?
Thank you.

Bobae


2017-08-16 18:01 GMT+09:00 mia tosi <notifications@github.com>:

**Comment by mtosi** [comment]
@cmsbuild, please test

**Comment by mtosi** [comment]
@cmsbuild, please test

**Pull request closed without merging**
