### PR TITLE
add WToLNu and WprimeToLNu genFragments at 14 TeV [backport #33407]

### PR DESCRIPTION
**Pull request by mtosi**
#### PR description:
backport of https://github.com/cms-sw/cmssw/pull/33407

### CODE REVIEW

**Comment by qliphy** [comment]
assign pdmv

**Comment by qliphy** [comment]
please test

**Comment by agrohsje** [comment]
+generators

**Comment by chayanit** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
