### PR TITLE
Generalize makeTrackValidationPlots.py script

### PR DESCRIPTION
**Pull request by makortel**
This PR generalizes the `makeTrackValidationPlots.py` script introduced in #9882 to make plots for all subfolders of "Tracking/Track" folder of the first of the DQM files given as command line arguments (feature requested by @lveldere). Add also `--ignoreMissing` command line flag to allow skipping missing histograms/subfolders.

In addition, switch the plotting to use the profile histograms in the DQM files instead of the 2D histograms nhits_vs_eta and chi2_vs_eta that were cleaned up in #9524.

There should be no effect on standard workflows.

@rovere @VinInn

### CODE REVIEW

**Comment by makortel** [comment]
Noticed a small bug right after pushing "submit PR" button, fixed and squashed to the existing commit.

**Comment by lveldere** [comment]
Hi Matti

I have some troubles running this.
I've put 2 DQM files in ~lveldere/public/matti

I run 
```
./Validation/RecoTrack/scripts/makeTrackValidationPlots.py fullsim_harvest.root fastsim_harvest.root
```

This complaints about some histograms not found.
Which I fixed by setting drawArgs["ignoreMissing"] = True,
but after that I still don't get pdf files...

Thanks

Lukas

**Comment by makortel** [comment]
Thanks, I'll take a look (and close for time being).

**Comment by makortel** [comment]
@lveldere The missing histograms were due to 2D-histograms nhits_vs_eta and chi2_vs_eta that were cleaned up in #9524. As they were used only to make "ProfileX()", I switched the plotting to use the profiles existing in DQM file (should've done this in #9524...). In addition, I added `--ignoreMissing` flag to makeTrackValidationPlots.py that allows the script to continue making plots if some histograms/folders are missing (e.g. your example fastsim-file does not have `jetCoreRegionalStepSeeds_quickAssociatorByHits` folder), and made sure to loop over only subdirectories of Tracking/Track (#9201 added also summary histograms there).

**Comment by lveldere** [comment]
Great, that works! Thanks.

**Comment by deguio** [comment]
+1

**Pull request merged**
