### PR TITLE
L1GtBoard is a class not an enum -

### PR DESCRIPTION
**Pull request by davidlange6**
remove incorrect entry from classes_def.xml. Perhaps it should have been L1GtBoardType, but it seems the code works fine without it.

### CODE REVIEW

**Comment by davidlange6** [comment]
please test



On 2 Dec 2019, at 20:03, cmsbuild <notifications@github.com> wrote:

﻿

+code-checks

Logs: https://cmssdt.cern.ch/SDT/code-checks/cms-sw-PR-28523/12988

  *   This PR adds an extra 16KB to repository

**Comment by pohsun** [comment]
+1

**Comment by ggovi** [comment]
+1

**Comment by fabiocos** [comment]
@rekovic please check this, it is purely technical, I will integrate it in next IB

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Pull request merged**
