### PR TITLE
patch for passing reference for tauspinner - pythia8 problem

### PR DESCRIPTION
**Pull request by inugent**

### CODE REVIEW

**Comment by davidlange6** [comment]
is this PR obsolete?

**Comment by inugent** [comment]
Hello, 
 No this patch is still required. For some reason I have several pull request in this situation. Best regards,
Ian

**Comment by davidlange6** [comment]
Hi Ian- maybe you can follow up with the gen conveners about signing these..

**Comment by bendavid** [comment]
We're behind on pull requests in general.  Things are being prioritized according to what is most urgent for the main run 2 campaign.

**Comment by davidlange6** [comment]
seems this PR should be obsolete..

**Pull request closed without merging**
