### PR TITLE
CTPPS Pixel DQM add clusters

### PR DESCRIPTION
**Pull request by popovvp**
2 files modified:
plugins/CTPPSPixelDQMSource.cc: add clusters, update some histograms
python/ctppsPixelDQMSource_cfi.py: update clusters tag

scram build code-checks done

### CODE REVIEW

**Comment by dmitrijus** [comment]
please apply the code checks

**Comment by popovvp** [comment]
$ scram b code-checks
CMSSW_9_3_0_pre4/src/.*' src/DQM/CTPPS/plugins/CTPPSPixelDQMSource.cc
1938 warnings generated.
/afs/cern.ch/user/p/popov/scratch_bk/workCTPPSraw/CMSSW_9_3_0_pre4/src/DataFormats/Common/interface/Wrapper.h:70:5: warning: deleted member function should be public [modernize-use-equals-delete]
    Wrapper(Wrapper<T> const& rh) = delete; // disallow copy construction
    ^
/afs/cern.ch/user/p/popov/scratch_bk/workCTPPSraw/CMSSW_9_3_0_pre4/src/DataFormats/Common/interface/Wrapper.h:71:17: warning: deleted member function should be public [modernize-use-equals-delete]
    Wrapper<T>& operator=(Wrapper<T> const&) = delete; // disallow assignment
                ^
/afs/cern.ch/user/p/popov/scratch_bk/workCTPPSraw/CMSSW_9_3_0_pre4/src/FWCore/Framework/interface/stream/EDAnalyzer.h:64:7: warning: deleted member function should be public [modernize-use-equals-delete]
      EDAnalyzer(const EDAnalyzer&) = delete; // stop default
      ^
/afs/cern.ch/user/p/popov/scratch_bk/workCTPPSraw/CMSSW_9_3_0_pre4/src/FWCore/Framework/interface/stream/EDAnalyzer.h:66:25: warning: deleted member function should be public [modernize-use-equals-delete]
      const EDAnalyzer& operator=(const EDAnalyzer&) = delete; // stop default
                        ^
/afs/cern.ch/user/p/popov/scratch_bk/workCTPPSraw/CMSSW_9_3_0_pre4/src/FWCore/Framework/interface/stream/EDAnalyzerAdaptor.h:176:7: warning: deleted member function should be public [modernize-use-equals-delete]
      EDAnalyzerAdaptor(const EDAnalyzerAdaptor&) = delete; // stop default
      ^
/afs/cern.ch/user/p/popov/scratch_bk/workCTPPSraw/CMSSW_9_3_0_pre4/src/FWCore/Framework/interface/stream/EDAnalyzerAdaptor.h:178:32: warning: deleted member function should be public [modernize-use-equals-delete]
      const EDAnalyzerAdaptor& operator=(const EDAnalyzerAdaptor&) = delete; // stop default
                               ^
/afs/cern.ch/user/p/popov/scratch_bk/workCTPPSraw/CMSSW_9_3_0_pre4/src/FWCore/Framework/interface/stream/EDAnalyzerBase.h:59:7: warning: deleted member function should be public [modernize-use-equals-delete]
      EDAnalyzerBase(const EDAnalyzerBase&) = delete; // stop default
      ^
/afs/cern.ch/user/p/popov/scratch_bk/workCTPPSraw/CMSSW_9_3_0_pre4/src/FWCore/Framework/interface/stream/EDAnalyzerBase.h:61:29: warning: deleted member function should be public [modernize-use-equals-delete]
      const EDAnalyzerBase& operator=(const EDAnalyzerBase&) = delete; // stop default
                            ^
/afs/cern.ch/user/p/popov/scratch_bk/workCTPPSraw/CMSSW_9_3_0_pre4/src/FWCore/Framework/src/OutputModuleCommunicator.h:72:5: warning: deleted member function should be public [modernize-use-equals-delete]
    OutputModuleCommunicator(const OutputModuleCommunicator&) = delete; // stop default
    ^
/afs/cern.ch/user/p/popov/scratch_bk/workCTPPSraw/CMSSW_9_3_0_pre4/src/FWCore/Framework/src/OutputModuleCommunicator.h:74:37: warning: deleted member function should be public [modernize-use-equals-delete]
    const OutputModuleCommunicator& operator=(const OutputModuleCommunicator&) = delete; // stop default
                                    ^
/afs/cern.ch/user/p/popov/scratch_bk/workCTPPSraw/CMSSW_9_3_0_pre4/src/FWCore/ParameterSet/interface/ParameterSetDescriptionFiller.h:53:5: warning: deleted member function should be public [modernize-use-equals-delete]
    ParameterSetDescriptionFiller(const ParameterSetDescriptionFiller&) = delete; // stop default
    ^
/afs/cern.ch/user/p/popov/scratch_bk/workCTPPSraw/CMSSW_9_3_0_pre4/src/FWCore/ParameterSet/interface/ParameterSetDescriptionFiller.h:54:42: warning: deleted member function should be public [modernize-use-equals-delete]
    const ParameterSetDescriptionFiller& operator=(const ParameterSetDescriptionFiller&) = delete; // stop default
                                         ^
/afs/cern.ch/user/p/popov/scratch_bk/workCTPPSraw/CMSSW_9_3_0_pre4/src/FWCore/ParameterSet/interface/ParameterSetDescriptionFiller.h:186:5: warning: deleted member function should be public [modernize-use-equals-delete]
    DescriptionFillerForESSources(const DescriptionFillerForESSources&) = delete; // stop default
    ^
/afs/cern.ch/user/p/popov/scratch_bk/workCTPPSraw/CMSSW_9_3_0_pre4/src/FWCore/ParameterSet/interface/ParameterSetDescriptionFiller.h:187:42: warning: deleted member function should be public [modernize-use-equals-delete]
    const DescriptionFillerForESSources& operator=(const DescriptionFillerForESSources&) = delete; // stop default
                                         ^
/afs/cern.ch/user/p/popov/scratch_bk/workCTPPSraw/CMSSW_9_3_0_pre4/src/FWCore/ParameterSet/interface/ParameterSetDescriptionFiller.h:219:5: warning: deleted member function should be public [modernize-use-equals-delete]
    DescriptionFillerForESProducers(const DescriptionFillerForESProducers&) = delete; // stop default
    ^
/afs/cern.ch/user/p/popov/scratch_bk/workCTPPSraw/CMSSW_9_3_0_pre4/src/FWCore/ParameterSet/interface/ParameterSetDescriptionFiller.h:220:44: warning: deleted member function should be public [modernize-use-equals-delete]
    const DescriptionFillerForESProducers& operator=(const DescriptionFillerForESProducers&) = delete; // stop default
                                           ^
/afs/cern.ch/user/p/popov/scratch_bk/workCTPPSraw/CMSSW_9_3_0_pre4/src/FWCore/Utilities/interface/LuminosityBlockIndex.h:62:5: warning: deleted member function should be public [modernize-use-equals-delete]
    LuminosityBlockIndex()= delete;
    ^
/afs/cern.ch/user/p/popov/scratch_bk/workCTPPSraw/CMSSW_9_3_0_pre4/src/FWCore/Utilities/interface/RunIndex.h:59:5: warning: deleted member function should be public [modernize-use-equals-delete]
    RunIndex() = delete;
    ^
/afs/cern.ch/user/p/popov/scratch_bk/workCTPPSraw/CMSSW_9_3_0_pre4/src/FWCore/Utilities/interface/Signal.h:73:7: warning: deleted member function should be public [modernize-use-equals-delete]
      Signal(const Signal&) = delete; // stop default
      ^
/afs/cern.ch/user/p/popov/scratch_bk/workCTPPSraw/CMSSW_9_3_0_pre4/src/FWCore/Utilities/interface/Signal.h:75:21: warning: deleted member function should be public [modernize-use-equals-delete]
      const Signal& operator=(const Signal&) = delete; // stop default
                    ^
/afs/cern.ch/user/p/popov/scratch_bk/workCTPPSraw/CMSSW_9_3_0_pre4/src/FWCore/Utilities/interface/StreamID.h:58:5: warning: deleted member function should be public [modernize-use-equals-delete]
    StreamID() = delete;
    ^
/afs/cern.ch/user/p/popov/scratch_bk/workCTPPSraw/CMSSW_9_3_0_pre4/src/FWCore/Utilities/interface/TypeToGet.h:68:5: warning: deleted member function should be public [modernize-use-equals-delete]
    TypeToGet() = delete;
    ^
Suppressed 1868 warnings (1866 in non-user code, 2 with check filters).
Use -header-filter=.* to display errors from all non-system headers. Use -system-headers to display errors from system headers as well.
gmake[2]: Leaving directory '/afs/cern.ch/user/p/popov/scratch_bk/workCTPPSraw/CMSSW_9_3_0_pre4'
gmake[2]: Entering directory '/afs/cern.ch/user/p/popov/scratch_bk/workCTPPSraw/CMSSW_9_3_0_pre4'
>> Local Products Rules ..... started
>> Local Products Rules ..... done
clang-apply-replacements tmp/slc6_amd64_gcc630/code-checks

**Comment by popovvp** [comment]
could someone proceed this PR. Thanks.

**Comment by dmitrijus** [comment]
@popovvp you were asked to apply code checks, the commit for that is still missing

**Comment by popovvp** [comment]
@dmitrijus
$ scram b code-checks - is it what you ask ?
If not,  could you provide information (www-page or else) what I have to do.

**Comment by fabferro** [comment]
@popovvp : please Vladimir implement the changes suggested here: https://cmssdt.cern.ch/SDT/code-checks/PR-20413/549/git-diff.patch

**Comment by dmitrijus** [comment]
@popovvp 
> Code check has found code style and quality issues which could be resolved by applying a patch in https://cmssdt.cern.ch/SDT/code-checks/PR-20413/549/git-diff.patch
e.g. curl https://cmssdt.cern.ch/SDT/code-checks/PR-20413/549/git-diff.patch | patch -p1

You did it... but simply forgot to make a commit / push the changes which were made.

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
