### PR TITLE
JetMET DQM and MET Validation unscheduled mode fix

### PR DESCRIPTION
**Pull request by webermat**
All modules which are modified are now cloned first. This should fix the issues observed in the unscheduled modes for MET Validation and JetMET DQM. As consequence the type1 MET folders will be renamed. Updated the PUJetID producers to the latest version (training still based on 53X though).

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
@webermat - this branch does not merge any more - is this PR superceded? @deguio

**Comment by deguio** [comment]
actually no. there is no recent PR that supersedes this one. it should be rebased.
the same is true for: #9939 

@webermat please provide an update asap. this is now urgent.
thanks in advance,
F.

**Comment by webermat** [comment]
PR superceded by #10295

**Pull request closed without merging**
