### PR TITLE
[DB] Apply code-checks/format with misc-definitions-in-headers

### PR DESCRIPTION
**Pull request by smuzaffar**
code-checks/format applied on full cmssw

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
ping @cms-sw/db-l2

**Comment by qliphy** [comment]
kindly ping @cms-sw/db-l2

**Comment by smuzaffar** [comment]
@ggovi , can youplease sign this?

**Comment by ggovi** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
