### PR TITLE
Era support for the BMTF Packer

### PR DESCRIPTION
**Pull request by panoskatsoulis**
backport of #32365 to be used in any 112X MC campaign

### CODE REVIEW

**Comment by panoskatsoulis** [comment]
backport of #32365

**Comment by panoskatsoulis** [comment]
hold

**Comment by silviodonato** [comment]
please test

**Comment by silviodonato** [comment]
@panoskatsoulis please push on "Ready for review", when the PR is ready

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
abort
This branch `panoskatsoulis:bmtf_eraconfig_packer_unpacker` is used to create PRs for cmssw `master` and `CMSSW_11_2_X`. Bot is testing the same commit for both PRs (#32365 and #32367) , the confuses both. I would suggest to only test it at one place or  create two branches

**Comment by panoskatsoulis** [comment]
@smuzaffar 
we were testing it in the PR for the master only but after changes in the discrepancies that were seen in the tests, I was thinking of that these discrepancies might exist because of the baseline used in the tests.
For this reason, I asked to test in the backport.

**Pull request closed without merging**
