### PR TITLE
change Selector from bit pattern to bit number for the pattern [12.5]

### PR DESCRIPTION
**Pull request by vlimant**
#### PR description:

forward part of #38943 to 12.5

### CODE REVIEW

**Comment by mariadalfonso** [comment]
assign xpog

**Comment by vlimant** [comment]
@smuzaffar is the a “please patch” command that we could have to push the patch as a PR to my branch?

**Comment by smuzaffar** [comment]
> @smuzaffar is the a “please patch” command that we could have to push the patch as a PR to my branch?

good idea @vlimant , yes we can improve bot to patch the user branch on demand (e.g. using `please patch` or `apply code-checks`). Note that this will only work if user has allowed owner of `cms-sw` to apply changes to PR branch.

I will look in to it once back from vacations ( after 10th Aug)

**Comment by mariadalfonso** [comment]
please test

**Comment by mariadalfonso** [comment]
please test

**Comment by jpata** [comment]
This PR is the master version: can we please put all the changes here and merge this one first?

**Comment by mariadalfonso** [comment]
@vlimant
we need the change to this file DQM/GEM/python/gemEfficiencyAnalyzer_cff.py as well as was done in the 12_4

**Comment by jpata** [comment]
btw, now that MC production was started, should we protect the changes with a modifier (for the backport)?

**Comment by mariadalfonso** [comment]
> btw, now that MC production was started, should we protect the changes with a modifier (for the backport)?

For nano, the modifier is not back ported ( any nano made any PPD out of Run3,  need anyway to be deleted ) 
The official Run3 with 12_4 of MINI has not started, as far as I know.

**Comment by jpata** [comment]
@vlimant kind ping here. can you please update this PR to be consistent with the 12_4 version?

**Comment by vlimant** [comment]
done

**Comment by jpata** [comment]
@cmsbuild please test

**Comment by qliphy** [comment]
please test with #39090

**Comment by jpata** [comment]
+reconstruction
- fix for https://github.com/cms-sw/cmssw/issues/38899
- changes to NANO muons and nothing else

**Comment by perrotta** [comment]
@cms-sw/dqm-l2 @cms-sw/xpog-l2 you already signed the backport PR in 12_4_X, I imagine you could also sign this master version of it...

**Comment by mariadalfonso** [comment]
+xpog

**Comment by emanueleusai** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
