### PR TITLE
add missing include in FWCore/Framework / dependencies  and MagneticField/Engine

### PR DESCRIPTION
**Pull request by davidlange6**
Missing items found in modules build.

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by makortel** [comment]
I'm a bit curious to learn how modules build lead up to finding out these includes were missing. I mean, does it check missing includes also outside of the packages generating dictionaries, or is there a dependency chain from such package to `FWCore/Framework`? Or something else?

**Comment by davidlange6** [comment]
Its more sensitive to capturing things that you directly use via #include and via BuildFiles as if a module is not yet built and no dependency (at the include level rather than just .so level) is declared the built fails. Of course often the low level package is built first due to some indirect dependency or via a race condition (just as with .so dependencies), so things tend to come one by one.

(I’m not sure why my build reported a missing #include of cassert today, but it did..)


On Aug 31, 2020, at 3:28 PM, Matti Kortelainen <notifications@github.com<mailto:notifications@github.com>> wrote:



I'm a bit curious to learn how modules build lead up to finding out these includes were missing. I mean, does it check missing includes also outside of the packages generating dictionaries, or is there a dependency chain from such package to FWCore/Framework? Or something else?

**Comment by perrotta** [comment]
+1
- Technical
- Jemkims tests pass

**Comment by qliphy** [comment]
+1

**Pull request merged**
