### PR TITLE
Use the ratio timing method for ECAL online DQM

### PR DESCRIPTION
**Pull request by thomreis**
#### PR description:

This PR sets the ECAL timing algorithm used in the online DQM reconstruction to the ratio method. Like this the online DQM monitors the algorithm that is used at the HLT and can also directly use the calibrations and offsets from the HLT GT.

#### PR validation:

Ran ecal_dqm_sourceclient-live_cfg.py configuration locally.

### CODE REVIEW

**Comment by thomreis** [comment]
type ecal

**Comment by thomreis** [comment]
please test

**Comment by thomreis** [comment]
Updated this PR to explicitly set the record labels for the time calibration and time offset conditions.

**Comment by thomreis** [comment]
please test

**Comment by tjavaid** [comment]
+1

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
