### PR TITLE
Adding Pixel Phase I TkMap

### PR DESCRIPTION
**Pull request by chenxvan**
This PR adds the possibility to produce Pixel Phase 1 maps for Offline shifts

It introduce a new python script to generate the maps, and the needed files (vertices) to have them in TH2Poly format

Finally it adjust some ranges on the available maps

### CODE REVIEW

**Comment by dmitrijus** [comment]
@chenxvan WHo are you? @fioriNTU

**Comment by fioriNTU** [comment]
@dmitrijus she is a brand new Pixel DQM developer. However, please, don't start the tests here, this PR needs quite some review, I am waiting Xuan to be back from vacations to get it in shape

**Comment by vanbesien** [comment]
Hey Francesco,
Can you send us (by email) her full name and github user name so that we can add her to the list?
Thanks
b

**Comment by chenxvan** [comment]
A new PR with updated scripts has be sent #19253

**Pull request closed without merging**
