### PR TITLE
Removed unused headers from GeneratorInterface/HydjetInterface

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

The headers removed are deprecated.

#### PR validation:

Code compiles.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by rappoccio** [comment]
Similar to https://github.com/cms-sw/cmssw/pull/39609

**Comment by rappoccio** [comment]
See comment: https://github.com/cms-sw/cmssw/pull/39609#issuecomment-1267515753

**Comment by perrotta** [comment]
merge
(removing unused and deprecated headers can be merged even without an explicit https://github.com/orgs/cms-sw/teams/generators-l2 signature, to clean up the long queue a bit)

**Pull request merged**
