### PR TITLE
Add GEM alignment in all Run3 GTs and update BeamSpot in Run3 MC GTs

### PR DESCRIPTION
**Pull request by francescobrivio**
#### PR description:
In this PR we add:
 - the new GEM Alignment and AlignmentErrors tags to all Run3 GTs ([CMSTalk post](https://cms-talk.web.cern.ch/t/full-track-validation-hlt-express-prompt-update-of-mual/12237))
   - In order to be consistent with these new tags (and with the GEM geometry already in use in HLT/Express/Prompt), the data and data_relval GTs have also been updated with the latest GEMRECO_Geometry tag (from v2 to v3)
 - the new BeamSpot for Run 3 collisions at 13.6 TeV in all Run3 MC GTs
   - Compatible with the VtxSmearing parameters `Realistic25ns13p6TeVEarly2022Collision` introduced in #38616
   - The new reco BeamSpot was derived from the RelVal produced in [JIRA-PDMVRELVALS-156](https://its.cern.ch/jira/browse/PDMVRELVALS-156)
 - new DroboxMetaData tag for the Express and Prompt frozen GTs and in the data and data_relval GTs ([CMSTalk post](https://cms-talk.web.cern.ch/t/new-dropbox-meta-data-tag-for-express-for-12-4-x/12176))

The new GEM tags are:
`GEMAlignment_hlt_v2`
`GEMAlignment_express_v2`
`GEMAlignment_prompt_v2`
`GEMAlignment_v2`
`GEMAlignment_MC_v1`
`GEMAlignment_ideal_MC_v1`

`GEMAlignmentErrorExtended_6x6_hlt_v2`
`GEMAlignmentErrorExtended_6x6_express_v2`
`GEMAlignmentErrorExtended_6x6_prompt_v2`
`GEMAlignmentErrorExtended_6x6_v2`
`GEMAlignmentErrorExtended_6x6_MC_v1`
`GEMAlignmentErrorExtended_6x6_ideal_MC_v1`

The GEMRECO geometry tag is:
`GEMRECO_Geometry_v3_hlt`

The new BeamSpot tags are:
`BeamSpotObjects_Realistic25ns_13p6TeVCollisions_Early2022_v1_mc`
`BeamSpotOnlineObjects_Realistic25ns_13p6TeVCollisions_Early2022_v1_mc`

The new DMD tag is:
`DropBoxMetadata_v8_express`

GT Diffs:
- **Frozen HLT**  https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/124X_dataRun3_HLT_frozen_v4/124X_dataRun3_HLT_frozen_v6
- **HLT relval**  https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/124X_dataRun3_HLT_relval_v6/124X_dataRun3_HLT_relval_v8
- **Frozen Express**  https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/124X_dataRun3_Express_frozen_v2/124X_dataRun3_Express_frozen_v4
- **Frozen Prompt**  https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/124X_dataRun3_Prompt_frozen_v2/124X_dataRun3_Prompt_frozen_v4
- **Data Run3**  https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/124X_dataRun3_v5/124X_dataRun3_v9
- **Data Run3 relval**  https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/124X_dataRun3_relval_v5/124X_dataRun3_relval_v8
- **MC Run3 design**  https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/124X_mcRun3_2022_design_v6/124X_mcRun3_2022_design_v7
- **MC Run3 realistic**  https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/124X_mcRun3_2022_realistic_v8/124X_mcRun3_2022_realistic_v9
- **MC Run3 cosmics realistic**  https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/124X_mcRun3_2022cosmics_realistic_deco_v9/124X_mcRun3_2022cosmics_realistic_deco_v10
- **MC Run3 cosmics design**  https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/124X_mcRun3_2022cosmics_design_deco_v6/124X_mcRun3_2022cosmics_design_deco_v7
- **MC Run3 realistic HI**  https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/124X_mcRun3_2022_realistic_HI_v8/124X_mcRun3_2022_realistic_HI_v9
- **MC Run3 2023 realistic**  https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/124X_mcRun3_2023_realistic_v9/124X_mcRun3_2023_realistic_v10
- **MC Run3 2024 realistic**  https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/124X_mcRun3_2024_realistic_v9/124X_mcRun3_2024_realistic_v10
- **Open HLT**  https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/124X_dataRun3_HLT_v3/124X_dataRun3_HLT_v4
- **Open Express**  https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/124X_dataRun3_Express_v3/124X_dataRun3_Express_v4
- **Open Prompt**  https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/124X_dataRun3_Prompt_v3/124X_dataRun3_Prompt_v4

#### PR validation:
Tested with
`runTheMatrix.py -l 139.001,138.4,138.5,12034.0,11634.0,7.23,159.0,12434.0,12834.0 --ibeos -j 16`

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Not a backport, but a 12_4_X backport will be provided soon

### CODE REVIEW

**Comment by francescobrivio** [comment]
test parameters:
 - pull_request = #38666
 - workflows = 12034.0,11634.0,7.23,159.0,12434.0,12834.0

**Comment by francescobrivio** [comment]
@cmsbuild please test

**Comment by francescobrivio** [comment]
@cmsbuild please test

**Comment by tvami** [comment]
type gem

**Comment by francescobrivio** [comment]
> for the record, the PR is still failing because the `run2_data` is hardcoded around in online DQM clients in case the unit tests are run (despite the Run3 era is used):
> 
> https://github.com/cms-sw/cmssw/blob/bf84f5a873d0af0f58f08a8c0f29652208144b24/DQM/Integration/python/clients/beam_dqm_sourceclient-live_cfg.py#L80
> 
> https://github.com/cms-sw/cmssw/blob/bf84f5a873d0af0f58f08a8c0f29652208144b24/DQM/Integration/python/clients/mutracking_dqm_sourceclient-live_cfg.py#L102
> 
> etc.

Thanks Marco!
I'm already preparing a PR to update all the DQM clients to Run 3.

**Comment by francescobrivio** [comment]
test parameters:
 - pull_request = #38666,#38712
 - workflows = 12034.0,11634.0,7.23,159.0,12434.0,12834.0

**Comment by francescobrivio** [comment]
@cmsbuild please test

**Comment by francescobrivio** [comment]
Since the GEM fix for DQM might take a while (see https://github.com/cms-sw/cmssw/pull/38666#issuecomment-1184118227) I want to test this PR without that PR.

**Comment by francescobrivio** [comment]
test parameters:
*

**Comment by francescobrivio** [comment]
test parameters:
 - workflows = 12034.0,11634.0,7.23,159.0,12434.0,12834.0

**Comment by francescobrivio** [comment]
@cmsbuild please test

**Comment by tvami** [comment]
+alca 
 * tests pass, changes are widespread, but in line with the conditions changes in the GT

**Comment by perrotta** [comment]
+1
- Differences in the run3 workflows had been [evaluated](https://github.com/cms-sw/cmssw/pull/38692#issuecomment-1185529311) as being compatible with the GT changed

**Comment by mmusich** [comment]
@perrotta @cms-sw/alca-l2 merging this PR as is has been a mistake. 
The reconstruction level beamspot is now totally out of synch with the vertex smearing used for the Run3 workflows, completely destroying tracking performance.
Please either revert or fix ASAP.

**Comment by francescobrivio** [comment]
> Please either revert or fix

How do we update the Run 3 workflow? (sorry if the question is naive....)
I'll be able to work on this only tomorrow btw

**Pull request merged**
