### PR TITLE
online dqm HLT objects monitoring module

### PR DESCRIPTION
**Pull request by BetterWang**
adding online DQM HLT objects monitoring module for 5 TeV pp ref run.
Same PR as #21205 (closed) but based on 9_2_14 for P5TagCollector.

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by dmitrijus** [comment]
+1

**Comment by Martin-Grunewald** [comment]
@BetterWang 
Is this still relevant for legacy studies with 92X and/or mid-week global runs in case they will be done with 92X?

**Comment by BetterWang** [comment]
Hi @Martin-Grunewald , this is for the 5 TeV reference run only.
So I would say it is not relevant for legacy studies.

**Comment by davidlange6** [comment]
CMSSW_9_2_X developement work is completed. Closing remaining PRs

**Pull request closed without merging**
