### PR TITLE
Run3-gex92X Add the modified scenarios for Run3

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Add the modified scenarios for Run3

#### PR validation:

Use the runTheMatrix test workflows

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Backport already integrated PR's in 12_1_X. Ready for RUN3 geometry using DDD/DD4Hep XML's

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by srimanob** [comment]
Hi @bsunanda 

Thanks for the backport. 
Do you miss 2021FlatPlus05PercentReco_cff.py and 2021FlatPlus10PercentReco_cff.py for both DDD and DD4hep?

**Comment by srimanob** [comment]
The error comes from missing FlatPlus config as mentioned above,
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-2aac94/18374/unitTests/src/Configuration/Geometry/test/test2021Geometry/testing.log

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by srimanob** [comment]
The failure comes from the .911 DD4hep XML workflow. It can be expected from this PR as changed XML used for both DD4hep and DDD. If I understand correctly, we don't see the difference in DDD because all of the DDD short matrix uses DB. We should be able to spot it when GT is updated.

The new round of validation should be done with new CMSSW_12_0 when GT is updated for DDD.

**Comment by srimanob** [comment]
+Upgrade

By the way, are all of these PRs in master available with pre2, or still wait for pre3? If it is in pre3, it means we never validate them centrally using relvals.

**Comment by bsunanda** [comment]
Do we have to backport #35119?
________________________________

**Comment by srimanob** [comment]
I think so.

**Comment by bsunanda** [comment]
@srimanob Can you put that PR? Also several PR's were integrated after 12_1_0_pre2.

**Comment by srimanob** [comment]
Here is it, https://github.com/cms-sw/cmssw/pull/35198

**Comment by cvuosalo** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
