### PR TITLE
IsoPhotonEB skim (13_1_X)

### PR DESCRIPTION
**Pull request by lathomas**
#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport of https://github.com/cms-sw/cmssw/pull/42150

### CODE REVIEW

**Comment by perrotta** [comment]
backport of https://github.com/cms-sw/cmssw/pull/42150

**Comment by perrotta** [comment]
please test

**Comment by youyingli** [comment]
@cms-sw/pdmv-l2 , please test again

**Comment by youyingli** [comment]
@sunilUIET please sign

**Comment by sunilUIET** [comment]
+pdmv

**Comment by perrotta** [comment]
+1

**Pull request merged**
