### PR TITLE
apply whitespace python2->3 modernizer to core (and other low-level) packages

### PR DESCRIPTION
**Pull request by davidlange6**
rebased version of #23213

### CODE REVIEW

**Comment by perrotta** [comment]
@davidlange6 
The title of this PR is the same as the one of #23208: maybe you could differentiate them a bit ("- part 2"?)

**Comment by kpedro88** [comment]
+1

**Comment by alberto-sanchez** [comment]
+1

**Comment by perrotta** [comment]
please test
(Trying to clean up the comparisons: all reco changes show up in the premix workflow)

**Comment by davidlange6** [comment]
ha - it got the wrong title. Fixing that

**Comment by perrotta** [comment]
The changes in the reco sector are quite trivial, and I will sign for  
reco as soon as tests show no differences (besides the known ones...)

David Lange <notifications@github.com> ha scritto:

> I can rebase if its essentially ready to be merged... otherwise it  
> will just happen again
>

**Comment by Martin-Grunewald** [comment]
Please remove the changes to Configuration/HLT - the current status is way more human readable.

**Comment by davidlange6** [comment]
Your PR is unmergeable. Please have a look and possibly rebase it.

**Comment by Dr15Jones** [comment]
+1

**Comment by davidlange6** [comment]
Your PR is unmergeable. Please have a look and possibly rebase it.

**Comment by perrotta** [comment]
-1
- Rebase needed (since a while...)

**Pull request closed without merging**
