### PR TITLE
 ability to set origin to one of primary vertices (tested on 94X release)

### PR DESCRIPTION
**Pull request by alja**
29183468-a4f990da-7db7-11e7-9e29-17dd80798df5

### CODE REVIEW

**Comment by alja** [comment]
The PR is created based on master branch and CMSSW_9_4_0_pre1 release.
Closed outdated #19871.

**Comment by alja** [comment]
+1

**Comment by Dr15Jones** [comment]
@alja you have to apply the -code-checks patch and then push the change to your github branch before the pull request tests can begin.

**Comment by Dr15Jones** [comment]
please test

**Comment by alja** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
