### PR TITLE
Code to turn on VINCIA plugin

### PR DESCRIPTION
**Pull request by mkirsano**

### CODE REVIEW

**Comment by perrozzi** [comment]
please test

**Comment by perrozzi** [comment]
@mkirsano can you please have a look?

**Comment by mkirsano** [comment]
Yes, I will check it with clang

**Comment by mkirsano** [comment]
I wrote to Skands about this problem. Vincia can be patched, but may be it is better to upgrade it.

**Comment by davidlange6** [comment]
hi all - any plans for this PR?

**Comment by mkirsano** [comment]
I will upgrade VINCIA in cmsdist, after that it should work

**Comment by davidlange6** [comment]
lets just plan to reopen this PR when vincia is updated...

**Pull request closed without merging**
