### PR TITLE
Adding HGCAL simhit validation histograms

### PR DESCRIPTION
**Pull request by indra-ehep**
#### PR description:

  - Few validation histograms will be added in the HGCal SimHitValidation folder of DQM root file
  - It does not depend upon other PR
  - This is following the presentation at https://indico.cern.ch/event/1085122/contributions/4563005/attachments/2327395/3965157/2021-10-13_HGCal_in_CMSSW.pdf
    and plan discussed in HGCAL GEANT activity at https://indico.cern.ch/event/1099648/contributions/4627667/attachments/2354197/4016902/2021-11-26_Plan_for_Documentation_and_PR.pdf

#### PR validation:

   All the suggested tests are perfomed as mentioned in https://cms-sw.github.io/PRWorkflow.html including 'scram build code-checks' and 'scram build code-format'

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

   Not applicable.

### CODE REVIEW

**Comment by jfernan2** [comment]
@indra-ehep can you please add yourself along with your github username in the comments filed to the HGCAL Validation developers e-group to keep track of the people working on it?
https://twiki.cern.ch/twiki/bin/viewauth/CMS/DQMContacts#HGCAL
Thanks

**Comment by indra-ehep** [comment]
> @indra-ehep can you please add yourself along with your github username in the comments filed to the HGCAL Validation developers e-group to keep track of the people working on it? https://twiki.cern.ch/twiki/bin/viewauth/CMS/DQMContacts#HGCAL Thanks

Dear Javier, 
Thank you for prompt response. I have added myself to the list that you have mentioned. Now waiting for approval.
regards
Indra
Screenshot at 2021-12-14 17-18-11

**Comment by jfernan2** [comment]
please test

**Comment by indra-ehep** [comment]
> please test

Thank you. I see that I am a member now.

**Comment by perrotta** [comment]
please test
(CMSSW_12_3_X_2021-12-13-2300, now available, contains the needed external)

**Comment by jfernan2** [comment]
I am sorry @indra-ehep but your PR is adding more than 400MB of new MEs to the DQM root file.
You should reduce the memory footprint, I suggest reducing the number of MEs and/or the binning (1k bins in 1D and 600x600 in 2D plots is too much)
Please inspect the results and reduce accordingly:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_3_X_2021-12-13-2300+44816f/47470/dqm-histo-comparison-summary.html
Thanks

**Comment by indra-ehep** [comment]
> I am sorry @indra-ehep but your PR is adding more than 400MB of new MEs to the DQM root file. You should reduce the memory footprint, I suggest reducing the number of MEs and/or the binning (1k bins in 1D and 600x600 in 2D plots is too much) Please inspect the results and reduce accordingly: https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_3_X_2021-12-13-2300+44816f/47470/dqm-histo-comparison-summary.html Thanks

Dear Javier,

The main issue of large memory footprint is due to TH2. Earlier we have used TGraph instead of TH2 which contains the same information but with a significantly smaller size. However, I did not find any handler for TGraph in DQMStore.h. May be it is mentioned in other files that I missed. So how do we proceed now ? 

Plan A : I can switch off the TH2 for now, re-optimize binning of 1D histograms. Then commit the changes. Later we add the TGraph features when available in DQMStore.h after contacting DQM experts. 

Plan B : I add TGraph feature in DQMStore.h and then modify HGCalSimHitValidation.cc for TGraph and 1D histograms.      

Or if you have other plan. Please let me know your feedback.

regards
Indra

**Comment by indra-ehep** [comment]
> I am sorry @indra-ehep but your PR is adding more than 400MB of new MEs to the DQM root file. You should reduce the memory footprint, I suggest reducing the number of MEs and/or the binning (1k bins in 1D and 600x600 in 2D plots is too much) Please inspect the results and reduce accordingly: https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_3_X_2021-12-13-2300+44816f/47470/dqm-histo-comparison-summary.html Thanks

Dear Javier,
Sorry for multiple posts. Is there any tool in CMSSW to check how much extra storage requirement is added in DQM.root file due to the new changes ? Then I can run such tests locally before making the git push.
regards
Indra

**Comment by jfernan2** [comment]
@indra-ehep  TGraph should be supported, see for example: 
https://github.com/cms-sw/cmssw/blob/bfabeecf71b25d486f3a8b4d47e3eaf57543afee/DQM/TrackerRemapper/src/Phase1PixelMaps.cc
or
https://github.com/cms-sw/cmssw/blob/6d2f66057131baacc2fcbdd203588c41c885b42c/DQM/SiStripCommissioningAnalysis/src/CalibrationScanAlgorithm.cc

**Comment by jfernan2** [comment]
On the other hand, there are tools to compare DQM root file outputs in:
https://github.com/cms-sw/cmssw/tree/master/DQMServices/FileIO/scripts

In particular:
https://github.com/cms-sw/cmssw/blob/master/DQMServices/FileIO/scripts/dqmMemoryStats.py

You can compare before and after your changes, although the own root files show a larger (compressed) size, e.g.

https://cmssdt.cern.ch/SDT/jenkins-artifacts/ib-baseline-tests/CMSSW_12_3_X_2021-12-13-2300/slc7_amd64_gcc900/-GenuineIntel/matrix-results/38634.0_TTbar_14TeV+2026D86+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14+DigiTrigger+RecoGlobal+HARVESTGlobal/DQM_V0001_R000000001__Global__CMSSW_X_Y_Z__RECO.root
69MB
vs
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-44816f/21259/runTheMatrix-results/38634.0_TTbar_14TeV+2026D86+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14+DigiTrigger+RecoGlobal+HARVESTGlobal/DQM_V0001_R000000001__Global__CMSSW_X_Y_Z__RECO.root
74MB

**Comment by indra-ehep** [comment]
> @indra-ehep TGraph should be supported, see for example: https://github.com/cms-sw/cmssw/blob/bfabeecf71b25d486f3a8b4d47e3eaf57543afee/DQM/TrackerRemapper/src/Phase1PixelMaps.cc or https://github.com/cms-sw/cmssw/blob/6d2f66057131baacc2fcbdd203588c41c885b42c/DQM/SiStripCommissioningAnalysis/src/CalibrationScanAlgorithm.cc

Thanks. I check and comeback with update.

**Comment by indra-ehep** [comment]
Dear Javier,
This is to keep you informed that I am on it. The delay is due to various tests before I push it. It is expected to be pushed by today.
regards
Indra

**Comment by rovere** [comment]
> @indra-ehep TGraph should be supported, see for example: https://github.com/cms-sw/cmssw/blob/bfabeecf71b25d486f3a8b4d47e3eaf57543afee/DQM/TrackerRemapper/src/Phase1PixelMaps.cc or https://github.com/cms-sw/cmssw/blob/6d2f66057131baacc2fcbdd203588c41c885b42c/DQM/SiStripCommissioningAnalysis/src/CalibrationScanAlgorithm.cc

Ciao @jfernan2 it has been quite a while since I touched the DQM code. I think that @indra-ehep is looking for is support for `TGraph` from within the DQM Framework, booked and stored by the `DQMStore`, written to the final DQM output file in the harvesting step and handled by the `DQMGUI`.
Can you confirm that this is the case? Looking quickly at the example you linked, they all seem to be standalone code that does not go through `DQMStore`. 
Thanks for clarifying that and for the help and review.

**Comment by bsunanda** [comment]
SimHitValidation is used in standard relval's so there is some restriction in how much storage space needed for all the plots. For detailedIndra make a separate class with detailed studies

**Comment by rovere** [comment]
Ciao @bsunanda,
the added value of having the plots regularly produced is that we can perform a thorough validation at each RelVal production, i.e. at each pre-release, w/o manually rerunning part of the validation suite.
If at all possible, I'd try and have it integrated in a way that is deemed reasonable by the proper stakeholders.

Thanks!

**Comment by jfernan2** [comment]
Hi @rovere 
My apologies, I totally misunderstood the issue and mixed it with TProfile..... I am sorry.
You are right and indeed TGraph is not yet supported by DQMstore. I can try to include it but I am afraid it was excluded for some deep reason which still prevents it to be displayed into the GUI, though the new DQM GUI may help in this sense. Do you recall by chance why TGraph was not supported since the beginning when you were in DQM team?

**Comment by indra-ehep** [comment]
> > @indra-ehep TGraph should be supported, see for example: https://github.com/cms-sw/cmssw/blob/bfabeecf71b25d486f3a8b4d47e3eaf57543afee/DQM/TrackerRemapper/src/Phase1PixelMaps.cc or https://github.com/cms-sw/cmssw/blob/6d2f66057131baacc2fcbdd203588c41c885b42c/DQM/SiStripCommissioningAnalysis/src/CalibrationScanAlgorithm.cc
> 
> Ciao @jfernan2 it has been quite a while since I touched the DQM code. I think what @indra-ehep is looking for is support for `TGraph` from within the DQM Framework, booked and stored by the `DQMStore`, written to the final DQM output file in the harvesting step and handled by the `DQMGUI`. Can you confirm that this is the case? Looking quickly at the example you linked, they all seem to be standalone code that does not go through `DQMStore`. Thanks for clarifying that and for the help and review.

@rovere  I confirm that this is what I am looking for. 
@all (@jfernan2 , @rovere , @bsunanda) In last two days I have tried various ways to implement TGraph in HGCalSimHitValidation.cc. I realized this can not be done unless change of Framework to otherways as shown in the example codes above. So I will not proceed in that direction. As alternate option, I have dropped 3 out of 7 TH2s and reduced the bin size of 1D histograms by 10 times. This adjustments are made so that we do not loose any physics message that we want to see in DQM histograms. In terms of the file size of compressed DQM file, it increases by 2.2%.  If this is fine I can push them in git. Or if you  suggest I will wait for TGraph in DQMStore.

**Comment by jfernan2** [comment]
@indra-ehep how much increase do you get now in uncompressed ROOT file? Please use tool https://github.com/cms-sw/cmssw/blob/master/DQMServices/FileIO/scripts/dqmMemoryStats.py   to get a proper measure

**Comment by indra-ehep** [comment]
@jfernan2 The default set without modification has 422 MB (*_Ref.root). The modification mentioned above adds 225 MB (*_binsize1_2D_HR.root ). If I further reduce the bins of TH2 histograms it becomes 7 MB extra (*_binsize1_2D.root).

Screenshot at 2021-12-17 00-02-11

**Comment by jfernan2** [comment]
Thank you @indra-ehep 
That's totally acceptable, please proceed
Thanks

**Comment by indra-ehep** [comment]
> Thank you @indra-ehep That's totally acceptable, please proceed Thanks

@jfernan2 : Which one ? The one which is adding 225 MB and contains the proper physics information ? Or the one which adds 7MB but with deteriorate the physics information ?

**Comment by jfernan2** [comment]
225MB is not acceptable, 7MB is acceptable, if you want to tune something in between I believe we could go up to 20MB

**Comment by indra-ehep** [comment]
@jfernan2 I have pushed the file that has been agreed. Thanks.

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by perrotta** [comment]
+1
- The size increase of the DQM root files, all below 7 MB, is deemed acceptable by DQM

**Pull request merged**
