### PR TITLE
Made all BuildFile.xml files easier to parse.

### PR DESCRIPTION
**Pull request by Teemperor**
This patch makes all BuildFile.xml a bit closer to valid XML and removes some duplicate build targets. This should make it easier for third-party tools to handle SCRAM based projects.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by slava77** [comment]
@cmsbuild please test
the last build got lost, apparently

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/18010	9071b17
- reco-related change is only in RecoHI/HiEgammaAlgos/plugins/BuildFile.xml  fixing a typo ```use   mane="DataFormats/EgammaReco"``` -> ```use   name="DataFormats/EgammaReco"```.
- jenkins tests  pass and show no differences in comparisons

**Pull request merged**
