### PR TITLE
 Fix l1 emulation in HLT scripts (101X)  

### PR DESCRIPTION
**Pull request by silviodonato**
Backport of #22813

### CODE REVIEW

**Comment by silviodonato** [comment]
please test

**Comment by silviodonato** [comment]
+1

**Comment by Martin-Grunewald** [comment]
-1
submitted to the wrong branch - (master is 102, not 101)

**Comment by Martin-Grunewald** [comment]
Replaced by #22822 .
Please close this PR, Silvio @silviodonato

**Pull request closed without merging**
