### PR TITLE
Mixing module multithreading

### PR DESCRIPTION
**Pull request by dan131riley**
Change MixingModule base class from edm::one::EDProducer to edm::stream::EDProducer.  This includes making the MixingModule base class and derived classes thread safe, adds stream interfaces to the PileUp and SecondaryEventProvider, plus mechanical changes to the interfaces of many of the associated producers.  Most of the changes outside of Mixing/Base are simple type changes.

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by lveldere** [comment]
+1

**Comment by davidlange6** [comment]
Nice to see no change in physics results in this PR. Thanks @dan131riley

**Comment by lgray** [comment]
Were the tests run multithreaded?

**Comment by dan131riley** [comment]
@lgray I'd assume with 1 thread.  With multiple threads, I'd expect to see small changes in the physics output because the sequence of pileup events won't be the same.  I'm working on quantifying that now.

**Comment by lgray** [comment]
Sure, but one must check the output is reasonable in single and multithread modes. 
Thanks again for this!

**Comment by davidlange6** [comment]
like everything, yes. But its already as good as what we had before:)

**Comment by slava77** [comment]
@dan131riley 
Does mixing replay still work in multithreaded mode?

**Comment by mdhildreth** [comment]
Slava: good question.  I have no idea.

**Comment by mdhildreth** [comment]
+1

**Comment by dan131riley** [comment]
@slava77

I agree, it's a good question.  I think replay should work, but I'm definitely not an expert on this part, I barely looked at the VectorInputSource or the crossing frame playback info.  As I understand it, the crossing frame playback info records the event id and the hash of the file each pileup event came from, so the VectorInputSource gets everything it needs to find the right inputs, we aren't relying on the pileup inputs being read in a particular order.  However, I don't believe there's any guarantee that playback will happen on the same threads as originally, same as any multi-threaded processing, so if there's a problem that depends on the past history of previous events that exact history may not be reproduced on playback.

But that's just my best guess, I should do a replay test to check.

-dan

**Comment by davidlange6** [comment]
+1

**Pull request merged**
