### PR TITLE
Run2-hcx182 Take care of analyzer checks in PR #24367

### PR DESCRIPTION
**Pull request by bsunanda**

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by ianna** [comment]
+1

**Comment by perrotta** [comment]
- What is CaloTowersReCreator::produce actually producing? IOW, why CaloTowersReCreator is a edm::stream::EDProducer? 
- Is "algo_" thread safe as such?
- Is CaloTowersReCreator ever used or needed? Why not simply remove the whole class?
- Is RecoLocalCalo/CaloTowersCreator/python/calotowerremaker_cfi.py needed, given the fillDescription in the class? It is never used, in fact

**Comment by bsunanda** [comment]
@perrotta algo_ is thread safe and the same algorithm is used for CaloTowersCreator. I am not sure if it will be used in the future. That is why I am hesitant to remove it and consequently the cfi file.

**Comment by abdoulline** [comment]
@perrotta @bsunanda 
This producer was designed in 2007 [*] to re-make regular "towermaker" collection (from AOD or similar end-user tier) into another one by using different weights of cells or other parameters. 
I don't think it was planned for regular workflows, apparently more for internal HCAL usage/studies. 
I'd suggest *not* to remove it right away.

[*] http://cmscvs.web.cern.ch/cmscvs/cgi/viewvc.cgi/cvsroot/CMSSW/RecoLocalCalo/CaloTowersCreator/src/CaloTowersReCreator.cc?view=log

**Comment by perrotta** [comment]
Thank you @bsunanda and @abdoulline 

Could you please comment about ```CaloTowersReCreator``` not being a producer, in fact, as it misses the "Step D" of the ```CaloTowersCreator``` (previously also in this class, according to the historical record)?

About ```algo_```'s thread safety: it is modified internally in the ```produce()``` method, and this is potentially dangerous. On the other hand, looking at the code I can see that before being used inside ```produce()``` it always gets reset, and therefore its thread-safety should be restored as such, although this is obviously not the safest way of writing thread-safe code. (Of course, this applies to the ```CaloTowersCreator```, while ```CaloTowersReCreator``` isn't producing anything, and if so the problem is non-existent)

**Comment by Dr15Jones** [comment]
@perrotta For a stream module, having a member data modify itself is not a thread-safety issue since each stream would have its own copy and the framework guarantees the same instance of a stream module is never run on multiple threads simultaneously. The only thread safety issue would be if the code modified global data (e.g. class statics, functional local statics, etc.). I do not see that to be the case with `algo_`.

**Comment by perrotta** [comment]
Thank you Chris!

Still the (main) question remain, whether this has to be a EDProducer  
at all, or not. If it doesn't care remaining an EDProducer even if it  
is not actually producing anything (in particular for this code which  
is not planned to be used in regular workflows), then the PR as a  
whole is fine with me.

Chris Jones <notifications@github.com> ha scritto:

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by perrotta** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by perrotta** [comment]
+1
- It fixes a few issues reported by the static analyzer
- Jenkins tests pass with no differences

**Comment by kpedro88** [comment]
+1

**Pull request merged**
