### PR TITLE
Print function migration for DQMOffline_CalibTracker

### PR DESCRIPTION
**Pull request by davidlange6**
Using futurize -n -w --no-diffs -j 4 -f libfuturize.fixes.fix_print_with_import

### CODE REVIEW

**Comment by perrotta** [comment]
+1
- Reco content identical to the already signed #23868

**Comment by fabiocos** [comment]
+1

failure is unrelated

**Comment by fabiocos** [comment]
merge

@jfernan2 changes look technical and simple enough

**Comment by andrius-k** [comment]
+1

Signing for the sake of completeness.

**Pull request merged**
