### PR TITLE
FPix Occupancy

### PR DESCRIPTION
**Pull request by fioriNTU**
Restore FPix cluster occupancy plots

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
@fioriNTU 
please clarify why two similar PR have been submitted. this one and #9463 
thanks,
F.

**Comment by fioriNTU** [comment]
I have to say I am not very expert in git, what I did is to submit 2 PR, 
in 7_4_X and 7_5_X with the same fix, and the same branch name, the 
original branch name was FPix2D for both. But once made the PR in 7_5_X, 
the system seems not accepting the same PR with the same branch name in 
7_4_X, so I switched to a new branch and made the PR again ... I guess 
this created the issue.
Hope this can help, let me know if you need more infos.

FF

Il 05/06/2015 11.56, deguio ha scritto:
>
> @fioriNTU <https://github.com/fioriNTU>
> please clarify why two similar PR have been submitted. this one and 
> #9463 <https://github.com/cms-sw/cmssw/pull/9463>
> thanks,
> F.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/cms-sw/cmssw/pull/9463#issuecomment-109240331>.
>



---
Questa e-mail è stata controllata per individuare virus con Avast antivirus.
https://www.avast.com/antivirus

**Comment by fioriNTU** [comment]
I realized I have made the pull request, with different name for the same 7_5_X
I will submit a new one for 7_4_X

**Comment by fioriNTU** [comment]
I do not see any clear relation indication on the nature of the error, 
in the log I found this

  "Assertion `sequential_ || engine != nullptr' failed"

what action shall I take?

Il 05/06/2015 13.52, cmsbuild ha scritto:
>
> -1
> Tested at: ffc084c 
> <https://github.com/cms-sw/cmssw/commit/ffc084c1bbbd57ff8c2014a7382314c56519380f>
> When I ran the RelVals I found an error in the following worklfows:
> 50202.0 step2
>
> runTheMatrix-results/50202.0_TTbar_13+TTbar_13+DIGIUP15_PU50+RECOUP15_PU50+HARVESTUP15_PU50+MINIAODMCUP1550/step2_TTbar_13+TTbar_13+DIGIUP15_PU50+RECOUP15_PU50+HARVESTUP15_PU50+MINIAODMCUP1550.log
>
> you can see the results of the tests here:
> https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-9463/5321/summary.html 
>
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/cms-sw/cmssw/pull/9463#issuecomment-109267751>.
>



---
Questa e-mail è stata controllata per individuare virus con Avast antivirus.
https://www.avast.com/antivirus

**Comment by Dr15Jones** [comment]
The error is unrelated to this pull request so you can safely ignore it.

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
@cmsbuild, please test

**Comment by davidlange6** [comment]
@cmsbuild, please test

**Comment by davidlange6** [comment]
+1

**Pull request merged**
