### PR TITLE
HLT V3.6 for development menus (102X)

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
HLT V3.5 for development menus (102X)
Does NOT touch production ("frozen") menus
Based on CMSSW_10_2_5.
Updated to V3.6

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
backport of #24512

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
