### PR TITLE
Add HCAL DPG HO filter modules

### PR DESCRIPTION
**Pull request by kfjack**
PR for the newly proposed HO filter skims from HCAL DPG (back port from PR #15557).

### CODE REVIEW

**Comment by fabozzi** [comment]
please test

**Comment by fabozzi** [comment]
@smuzaffar 
can you please restart the test also here as in #15557 ?

**Comment by kfjack** [comment]
Replaced with the standard deltaR & deltaPhi functions already. Please check. Many thanks.

**Comment by fabozzi** [comment]
please test

**Comment by fabozzi** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
