### PR TITLE
Herwig++: Add new cm energy and fix a typo

### PR DESCRIPTION
**Pull request by mharrend**

### CODE REVIEW

**Comment by mharrend** [comment]
I added also a config for the CUETHppS1 tune provided by Paolo Gunnellini-

**Comment by bendavid** [comment]
+1

**Comment by mharrend** [comment]
Fixed the compilation error.

**Comment by covarell** [comment]
please test

**Comment by mharrend** [comment]
The compilation error should now be fixed.

**Comment by covarell** [comment]
:-) "pls test" is not for you, it is a statement triggering automatic test

**Comment by mharrend** [comment]
okay sorry. :-)

**Comment by covarell** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
