### PR TITLE
Update clang-tidy test

### PR DESCRIPTION
**Pull request by smuzaffar**
PGO changes ( e.g. using relative source path instead of full path ) broke `scram build code-checks` rule. So it has not been running properly on PR. code-format was working but only `code-checks i.e. clang-tidy` did not work as it required correct `compiler_command.json` with correct source file paths.

Updated clang-tidy unit test now makes sure
- `scram build code-checks` and `scram build code-checks-all` rules work correctly
- `scram build code-format-all` also works

This will require also cmsdist update with correct code-checks rule

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

though test will fail as currently `code-checks` is not working correctly

**Comment by smuzaffar** [comment]
please test with ms-sw/cmsdist#9575

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@makortel , this is ready to go in. It add a new unit tests which makes sure that `scram build code-checks` and `scram build code-format` rules are working properly.

**Comment by makortel** [comment]
+core

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
