### PR TITLE
New GTs for 76X: L1,HLT,Geometry and HCAL changes

### PR DESCRIPTION
**Pull request by mmusich**
# Summary of changes
## Run I Simulation:
- _Ideal_: [76X_mcRun1_design_v4](https://cms-conddb.cern.ch/browser/#list/Prod/gts/76X_mcRun1_design_v4) as [76X_mcRun1_design_v2](https://cms-conddb.cern.ch/browser/#list/Prod/gts/76X_mcRun1_design_v2) with the following [changes](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/76X_mcRun1_design_v4/76X_mcRun1_design_v2):
  - updated HCAL response corrections from Data/MC studies
  - adding BTV tagger as GBRForest payloads for GBRWrapperRcd
- _Realistic_: [76X_mcRun1_realistic_v4](https://cms-conddb.cern.ch/browser/#list/Prod/gts/76X_mcRun1_realistic_v4) as [76X_mcRun1_realistic_v2](https://cms-conddb.cern.ch/browser/#list/Prod/gts/76X_mcRun1_realistic_v2) with the following [changes](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/76X_mcRun1_realistic_v4/76X_mcRun1_realistic_v2):
  - updated HCAL response corrections from Data/MC studies  
  - adding BTV tagger as GBRForest payloads for GBRWrapperRcd
- _Heavy Ion_: [76X_mcRun1_HeavyIon_v4](https://cms-conddb.cern.ch/browser/#list/Prod/gts/76X_mcRun1_HeavyIon_v4) as [76X_mcRun1_HeavyIon_v2](https://cms-conddb.cern.ch/browser/#list/Prod/gts/76X_mcRun1_HeavyIon_v2) with the following [changes](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/76X_mcRun1_HeavyIon_v4/76X_mcRun1_HeavyIon_v2):
  - Adding BDT taggers as GBRForest payloads with new labels for GBRWrapperRcd
  - Adding new label for HeavyIonRcd handling HF Towers HydjetDrum method;
  - Updating HCAL response corrections to take into account the change of scale in Method3
- _proton-Lead_:  [76X_mcRun1_pA_v4](https://cms-conddb.cern.ch/browser/#list/Prod/gts/76X_mcRun1_pA_v4) as [76X_mcRun1_pA_v2](https://cms-conddb.cern.ch/browser/#list/Prod/gts/76X_mcRun1_pA_v2) with the following [changes](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/76X_mcRun1_pA_v4/76X_mcRun1_pA_v2):
  - updated HCAL response corrections from Data/MC studies
  - adding BTV tagger as GBRForest payloads for GBRWrapperRcd
## Run II Simulation:
- _Ideal_: [76X_mcRun2_design_v4](https://cms-conddb.cern.ch/browser/#list/Prod/gts/76X_mcRun2_design_v4) as [76X_mcRun2_design_v2](https://cms-conddb.cern.ch/browser/#list/Prod/gts/76X_mcRun2_design_v2) with the following [changes](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/76X_mcRun2_design_v4/76X_mcRun2_design_v2):
  - updated HCAL response corrections from Data/MC studies
  - adding BTV tagger as GBRForest payloads for GBRWrapperRcd
  - adding new offline JEC from 2015 data analysis 
  - adding new HLT JEC from 2015 data anaylsis
  - moving to V5 version of L1Trigger Menu for Stage1
  - fixing L1 RCT parameters
  - updating Zero Suppression threshold for HCAL: HF is non-ZS 
  - adding L1TCaloParams payload
- _Asymptotic_: [76X_mcRun2_asymptotic_v4](https://cms-conddb.cern.ch/browser/#list/Prod/gts/76X_mcRun2_asymptotic_v4) as [76X_mcRun2_asymptotic_v2](https://cms-conddb.cern.ch/browser/#list/Prod/gts/76X_mcRun2_asymptotic_v2) with the following [changes](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/76X_mcRun2_asymptotic_v4/76X_mcRun2_asymptotic_v2):
  - Adding Calorimeter Parameters for L1T
  - Adding BDT taggers as GBRForest payloads with new labels for GBRWrapperRcd
  - Updating L1T menu to be in synch with online data taking
  - Updating L1T RCT parameters to be in synch with online data taking
  - Updating Pixel bad channel map as at the beginning of Run2015D era
  - Updating Zero Suppression threshold for HCAL: HF is non-ZS
  - Updating HCAL response corrections to take into account the change of scale in Method3
  - Updating JEC for HLT and RECO (also supporting Puppi).
- _Startup_ [76X_mcRun2_startup_v4](https://cms-conddb.cern.ch/browser/#list/Prod/gts/76X_mcRun2_startup_v4) as [76X_mcRun2_startup_v2](https://cms-conddb.cern.ch/browser/#list/Prod/gts/76X_mcRun2_startup_v2) with the following [changes](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/76X_mcRun2_startup_v4/76X_mcRun2_startup_v2):
  - updated HCAL response corrections from Data/MC studies
  - adding BTV tagger as GBRForest payloads for GBRWrapperRcd
  - adding new offline JEC from 2015 data analysis 
  - moving to V5 version of L1Trigger Menu for Stage1
  - fixing L1 RCT parameters
  - updating Zero Suppression threshold for HCAL: HF is non-ZS
  - adding L1TCaloParams payload
  - updating SiPixelQuality dead channel map to v28
- _Heavy Ion_ [76X_mcRun2_HeavyIon_v4](https://cms-conddb.cern.ch/browser/#list/Prod/gts/76X_mcRun2_HeavyIon_v4) as [76X_mcRun2_HeavyIon_v2](https://cms-conddb.cern.ch/browser/#list/Prod/gts/76X_mcRun2_HeavyIon_v2) with the following [changes](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/76X_mcRun2_HeavyIon_v4/76X_mcRun2_HeavyIon_v2):
  - updated HCAL response corrections from Data/MC studies
  - adding BTV tagger as GBRForest payloads for GBRWrapperRcd
  - adding new offline JEC from 2015 data analysis 
  - adding new HLT JEC from 2015 data anaylsis
  - moving to V5 version of L1Trigger Menu for Stage1
  - fixing L1 RCT parameters
  - updating Zero Suppression threshold for HCAL: HF is non-ZS
  - adding L1TCaloParams payload
  - updating SiPixelQuality dead channel map to v28
  - adding new label for HeavyIonRcd handling HF Towers HydjetDrum5 method;
## Run2 data
- _Offline Processing_ [76X_dataRun2_v3](https://cms-conddb.cern.ch/browser/#list/Prod/gts/76X_dataRun2_v3)  as [76X_dataRun2_v2](https://cms-conddb.cern.ch/browser/#list/Prod/gts/76X_dataRun2_v2) with the following [changes](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/76X_dataRun2_v3/76X_dataRun2_v2):
  - taxonomy changes for DT and CSC Alignment parameter errors
  - updated HCAL response corrections from Data/MC studies
  - fixing ECAL pulse shapes for ECAL multifit 
  - updated HCAL channel quality
  - adding BTV tagger as GBRForest payloads for GBRWrapperRcd
  - adding new offline JEC from 2015 data analysis 
  - adding new HLT JEC from 2015 data analysis
  - taxonomy change for the SiStrip O2O tags 
  - updating HF Towers label for HeavyIonRcd
- _HLT Processing_ [76X_dataRun2_HLT_frozen_v3](https://cms-conddb.cern.ch/browser/#list/Prod/gts/76X_dataRun2_HLT_frozen_v3) as [76X_dataRun2_HLT_frozen_v2](https://cms-conddb.cern.ch/browser/#list/Prod/gts/76X_dataRun2_HLT_frozen_v2) (snapshot time 2015-10-01 16:41:00 UTC) with the following [changes](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/76X_dataRun2_HLT_frozen_v3/76X_dataRun2_HLT_frozen_v2):
  - Taxonomy change for CSC and DT APE
  - Taxonomy change for SiStrip Backplane corrections in deconvolution mode
## Run1 Data
- _Offline Processing_ [76X_dataRun1_v3](https://cms-conddb.cern.ch/browser/#list/Prod/gts/76X_dataRun1_v3) as [76X_dataRun1_v2](https://cms-conddb.cern.ch/browser/#list/Prod/gts/76X_dataRun1_v2) with the following [changes](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/76X_dataRun1_v3/76X_dataRun1_v2):
  - Taxonomy change for CSC and DT APE
  - Adding BDT taggers as GBRForest payloads with new labels for GBRWrapperRcd
  - Updating SiStrip O2O tags (bad channels, FED cabling, latency, pedestals, threshold) with the prompt version. BEWARE: the noise tag is not updated yet, so it does not cover Run2.
  - Updating ECAL pulse shapes for Multi fit method in local reco: first IOV covering Run1 as in MC, second IOV covering Run2 as per Run2015B analysis
  - Updating HCAL bad channel map as per Run2015B-C analysis
  - Updating HCAL response corrections to take into account the change of scale in Method3 starting from Run2015B
  - Updating HF Towers centrality for Heavy Ion
- _HLT Processing_ [76X_dataRun1_HLT_frozen_v3](https://cms-conddb.cern.ch/browser/#list/Prod/gts/76X_dataRun1_HLT_frozen_v3) as [76X_dataRun1_HLT_frozen_v2](https://cms-conddb.cern.ch/browser/#list/Prod/gts/76X_dataRun1_HLT_frozen_v2) (snapshot time 2015-10-01 16:41:00 UTC) with the following [changes](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/76X_dataRun1_HLT_frozen_v3/76X_dataRun1_HLT_frozen_v2):
  - Taxonomy change for CSC and DT APE
  - Taxonomy change for SiStrip Backplane corrections in deconvolution mode
## Upgrades
- _Upgrade (phase-I)_ [76X_upgrade2017_design_v0](https://cms-conddb.cern.ch/browser/#list/Prod/gts/76X_upgrade2017_design_v0) as [75X_upgrade2017_design_v4](https://cms-conddb.cern.ch/browser/#list/Prod/gts/75X_upgrade2017_design_v4) with the following [changes](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/76X_upgrade2017_design_v0/75X_upgrade2017_design_v4):
  - Added L1T Calorimeter Parameters
  - Added HCAL parameters in new version of the condition object
  - Updated HCAL RECO geometry as for Run2
  - Updated SIM geometry in the `Ideal` scenario (as a placeholder for Run2)
  - Removed unused SIM geometries.

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
@Martin-Grunewald I suppose this will not pass the tests because due to the inconsistent L1 and HLT menus....

**Comment by mmusich** [comment]
please aknowlegde changes

**Comment by diguida** [comment]
@Martin-Grunewald we cherry-picked `Configuration/HLT/python/autoHLT.py` change as in #11391

**Comment by diguida** [comment]
please test

**Comment by mmusich** [comment]
+1

**Comment by Martin-Grunewald** [comment]
Correct action indeed!

**Comment by Martin-Grunewald** [comment]
+1

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
#11584

**Comment by diguida** [comment]
@Martin-Grunewald see my comments therein: we should make sure `TMath` is either not used or is supported.

**Comment by Martin-Grunewald** [comment]
@diguida  @mmusich @slava77
Does the new v5 L1T menu not enter the run2_hlt GT? @slava77 complains about failing workflow 134.805 in 76X which seems to indicate that GT still contains the old V4 L1T menu.

**Comment by Martin-Grunewald** [comment]
@diguida @mmusich @slava77
Is this via O2O? So the GT used to take the original data is used via auto::run2_hlt (and that was using v4 L1T in the GT and an older HLT menu)? but the worflow executed today wants to run the current HLT menu (requiring the v5 L1T menu)...?

**Comment by diguida** [comment]
@Martin-Grunewald that's correct. The HLT GT gets the L1T menu from O2O directly triggered online.
This means that the new L1T menu has not been deployed for the runs you are using for tests...

**Comment by diguida** [comment]
@Martin-Grunewald can you try by customising the HLT menu in `autoCondHLT` and check if this works?

**Comment by Martin-Grunewald** [comment]
@hengne
Yes, we do that already with the GT then named 'run2_hlt_25ns14e33_v3' or ''run2_hlt_25ns14e33_v4'
to indicate which HLT menu to be used, but that would have to be propagated to the workflow
test, or alternatively the specific workflow tests (but not all!) updated to use a specific frozen HLT menu compatible with the L1T menu used at the time of data taking.

**Comment by diguida** [comment]
ah I see. So, the driver commands should be customised in order to pick the HLT keys!

**Comment by diguida** [comment]
@mulhearn @kkotov this is something you might want to watch as well.

**Comment by hengne** [comment]
@mmusich @diguida @Martin-Grunewald you can just cherry-pick this commit here to fix the addOn test failure:
https://github.com/hengne/cmssw/commit/50f18c237f2cebd978b37ccebe2dc20fdc7bfffc

**Comment by Martin-Grunewald** [comment]
No! (I should not have signed #11424) That is a different test and the solution does not scale!
The addOn tests always need to run the most recent combination.

**Comment by hengne** [comment]
@mmusich @diguida @Martin-Grunewald OK, sorry, this doesn't apply here...

**Comment by diguida** [comment]
@hengne what you propose is to roll back the L1T menu... here we'd like to push forward. @Martin-Grunewald am I right?

**Comment by hengne** [comment]
@diguida sorry, forget what I proposed.. i am wrong here.

**Comment by Martin-Grunewald** [comment]
Well, what is the test supposed to test? That we can run new L1T and new HLT on old data?
Or that we can run with the new CMSSW code the old menus on old data? Probably the former...

**Pull request merged**
