### PR TITLE
change return type of geomTracker to derived class (TrackerGeometry vs TrackingGeometry)

### PR DESCRIPTION
**Pull request by davidlange6**
#31192 plus review changes (I messed up the rebase so started over..)

nominally this PR is to work around errors flagged by modules build. There is a mix of TrackerGeometry and TrackingGeometry (esp in Egamma) that I don't fully understand the logic of as there is presumably only one relevant derived type from TrackingGeometry (which is TrackerGeometry) for anything that is not a muon algorithm

This is a minimal change - I didn't attempt a cleanup in RecoEgamma.

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/31196	8585095
- code changes are technical; they are in line with the PR description and the follow up review in #31192 
- jenkins tests pass and comparisons with the baseline show no differences

**Comment by Martin-Grunewald** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
