### PR TITLE
Backport #9964 Muon CITK fix for 75X

### PR DESCRIPTION
**Pull request by jhgoh**
Backport of #9964 to fix wrong veto cone size in the muon CITK configuration.
CITK based isolation value becomes consistent to the standard isodeposit one after the fix.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
+1

For #9965 cb488b349751619b3dbee8e343cd8b1ec6cee540

Small fix for CITK muon isolation cone size. The 76X version of this PR, #9964, has already been approved by Reco.

The code changes are satisfactory, and Jenkins [tests](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-9965/5839/summary.html) against baseline CMSSW_7_5_X_2015-06-29-2300 show no significant differences.

**Comment by slava77** [comment]
@monttj we need an AT signature here.
Please check.

**Comment by monttj** [comment]
+1
Nice to see the consistent result between CITK and isodeposit.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
