### PR TITLE
Throw GetByLabelWithoutRegistration exception also when no module in a job registered consumption of a given branch

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

https://github.com/cms-sw/cmssw/pull/38864 reported a case where an EDAnalyzer using `Event::getByLabel()`  without declaring the consumed data products got a `ProductNotFound` exception instead of more explanatory `GetByLabelWithoutRegistration` exception. I traced this down to `ProductResolverIndexHelper` not being populated (from `ProductRegistry` with ~~non-consumed branches~~ branches that have product type that is not consumed in the job (either via the same or different branch)
https://github.com/cms-sw/cmssw/blob/db4ff9a6cf2fea967f3d80ca084d195e6f5a17ed/DataFormats/Provenance/src/ProductRegistry.cc#L419-L422
leading to `ProductResolverIndexHelper::index()` returning a `ProductResolverIndexInvalid` and  `Principal::findProductByLabel()` returning `nullptr`, which is interpreted as `ProductNotFound` by calling code.

This PR proposes to change the `Principal::findProductByLabel()` to check the branch existence directly from `ProductRegistry` after getting `ProductResolverIndexInvalid`, and throw `GetByLabelWithoutRegistration` exception if the branch in question is present. This adds some cost, but only in case
* code calls consumes but uses (deprecated) `getByLabel()` to get the data, and
* product in question does not exist, and
* code checks the `Handle` validity and is able to ignore the missing product

I would expect this case to be rare, and therefore the cost to be acceptable. I also think we should make an effort to address the remaining `getByLabel()` calls in the near-to-medium-future.

#### PR validation:

Checked that the test configuration in #38864 now throws `GetByLabelWithoutRegistration` exception.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
I don't think this is the proper solution. It seems to miss the case where
1. module A calls `getByLabel` without doing the `consumes`
2. module B just happens to `consumes` that exact same data

This would cause a race condition as to whether A gets the data if A does not also happen to always be scheduled to run after B.

**Comment by Dr15Jones** [comment]
My point being that `getByLabel` should throw an exception for not calling `comsumes` for that data product even if the data product happens to be accessible in the Event at the time of the call.

**Comment by makortel** [comment]
If B `consumes` the exact same data, this code (referring now to code in `master`)
https://github.com/cms-sw/cmssw/blob/db4ff9a6cf2fea967f3d80ca084d195e6f5a17ed/FWCore/Framework/src/Principal.cc#L805-L806
should return a valid index. In that case the code I added in this PR will not get run, and the existing check
https://github.com/cms-sw/cmssw/blob/db4ff9a6cf2fea967f3d80ca084d195e6f5a17ed/FWCore/Framework/src/Principal.cc#L814-L816
should check if this module declared the consumption of the data product, and throw the `GetByLabelWithoutRegistration` exception.

I think this case was already covered, and I don't see how changes in this PR would impact that.

**Comment by Dr15Jones** [comment]
What made it not possible to re-use the logic on line 814?

**Comment by Dr15Jones** [comment]
How about adding a unit test option for this case?

**Comment by makortel** [comment]
> What made it not possible to re-use the logic on line 814?

The `index` in line 814 would be `ProductResolverIndexInvalid` in this case, and
https://github.com/cms-sw/cmssw/blob/db4ff9a6cf2fea967f3d80ca084d195e6f5a17ed/FWCore/Framework/src/EDConsumerBase.cc#L348-L358
would then return `false` always.

**Comment by makortel** [comment]
> How about adding a unit test option for this case?

I was hoping to get away by `getByLabel()` being deprecated etc, but since you suggested it, I'll craft one.

**Comment by makortel** [comment]
I added a test that (in the first commit) demonstrates what happens when a data product is obtained via `getByLabel()` with and without `consumes()` calls when
* data product comes from the input file, no other consumers of the same product type (the problematic case of this PR)
* data product of the same type is produced+consumed by other modules
* data product of different type is produced+consumed by other modules

The changes in the test in the second commit demonstrate the effect of the changes.

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
@Dr15Jones Does the added test address your concern?

**Comment by Dr15Jones** [comment]
I'm good with the change once the build system decides to finish its tests :).

**Comment by makortel** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
