### PR TITLE
Update Run3 CSC conditions in 2022, 2023, 2024 realistic MC GTs and offline data GT

### PR DESCRIPTION
**Pull request by saumyaphor4252**
#### PR description:

This PR updates the Run3 CSC conditions in the following GTs:
- 2022, 2023, 2024 realistic MC GTs
- Run3 offline data GT for future ReReco 

requested in [1] and [2] respectively. More details and internal validations can be found in [3]. The tag updates are as follows:

**For MC GTs**:

|Rcd | Label | Tag |
| -- | -- | -- | 
| CSCDBGainsRcd | - | CSCDBGains_Dec_2023_v1 | 
| CSCDBPedestalsRcd | - | CSCDBPedestals_Dec_2023_v1 |  
| CSCDBCrosstalkRcd | - | CSCDBCrosstalk_Dec_2023_v1 |
  
**For Run3 Offline Data GT** :

|Rcd | Label | Tag |
| -- | -- | -- | 
| CSCDBGainsRcd | - | CSCDBGains_v3_offline | 
| CSCDBPedestalsRcd | - | CSCDBPedestals_v3_offline |  
| CSCDBCrosstalkRcd | - | CSCDBCrosstalk_v4_offline |

the new conditions are effective from [Run 347687](https://cmsoms.cern.ch/cms/runs/report?cms_run=347687) (2022-02-15)

[1] https://cms-talk.web.cern.ch/t/mc-gt-update-csc-conditions-for-run3-mc-gts/33583
[2] https://cms-talk.web.cern.ch/t/full-track-validation-hlt-express-prompt-offline-csc-run3-condition-updates-for-2024-data-taking/33776 
[3] https://indico.cern.ch/event/1358549/#9-csc-conditions-update-for-20

**GT Differences with the last ones are here**:

- **Run3 data Offline**:
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/140X_dataRun3_v1/140X_dataRun3_v3 

- **Phase1 2022 realistic**:
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/140X_mcRun3_2022_realistic_v1/140X_mcRun3_2022_realistic_v3 

- **Phase1 2022 realistic postEE**:
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/140X_mcRun3_2022_realistic_postEE_v1/140X_mcRun3_2022_realistic_postEE_v3 

- **Phase1 2022 cosmics realistic**: 
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/140X_mcRun3_2022cosmics_realistic_deco_v1/140X_mcRun3_2022cosmics_realistic_deco_v3

- **Phase1 2022 realistic hi**: 
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/140X_mcRun3_2022_realistic_HI_v1/140X_mcRun3_2022_realistic_HI_v3

- **Phase1 2023 realistic**: 
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/140X_mcRun3_2023_realistic_v1/140X_mcRun3_2023_realistic_v3
	
- **Phase1 2023 realistic postBPix**: 
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/140X_mcRun3_2023_realistic_postBPix_v1/140X_mcRun3_2023_realistic_postBPix_v3

- **Phase1 2023 cosmics reaslistic**:
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/140X_mcRun3_2023cosmics_realistic_deco_v1/140X_mcRun3_2023cosmics_realistic_deco_v3 

- **Phase1 2023 cosmics reaslistic postBPix**:
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/140X_mcRun3_2023cosmics_realistic_postBPix_deco_v1/140X_mcRun3_2023cosmics_realistic_postBPix_deco_v3

- **Phase1 2023 realistic hi**: 
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/140X_mcRun3_2023_realistic_HI_v1/140X_mcRun3_2023_realistic_HI_v3

- **Phase1 2024 realistic**: 
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/140X_mcRun3_2024_realistic_v1/140X_mcRun3_2024_realistic_v3

- **Phase1 2024 cosmics realistic**:
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/140X_mcRun3_2024cosmics_realistic_deco_v1/140X_mcRun3_2024cosmics_realistic_deco_v3

#### PR validation:
Tested successfully with 
- `runTheMatrix.py -l 7.23,141.001,141.044,140.022,140.069,159.1,160.1,312.0,12834.0, -j 8 --ibeos`
- `runTheMatrix.py -l 12401.0,12404.0,12412.0,12423.0,12425.0,12430.0,12431.0,12444.0,12447.0,12450.0,12504.0,12634.586,12650.0,12737.0, --what upgrade -j 8 --ibeos`

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:
Not a backport. But backport will be followed up for 140X (considering the Full 2022+2023 ReReco campaign)

### CODE REVIEW

**Comment by saumyaphor4252** [comment]
test parameters:
- workflows = 140.022,140.069,159.1,160.1,312.0,12834.0,12401.0,12404.0,12412.0,12423.0,12425.0,12430.0,12431.0,12444.0,12447.0,12450.0,12504.0,12634.586,12650.0,12737.0
- relvals_opt = --what upgrade,standard

**Comment by saumyaphor4252** [comment]
@cmsbuild please test

**Comment by saumyaphor4252** [comment]
test parameters:

- workflows = 140.022,140.069,159.1,160.1,312.0,12834.0,12401.0,12404.0,12412.0,12423.0,12425.0,12430.0,12431.0,12444.0,12447.0,12450.0,12504.0,12634.586,12650.0,12737.0
- relvals_opt = --what upgrade,standard,pileup

**Comment by saumyaphor4252** [comment]
> ValueError: Undefined workflows: 312.0

https://github.com/cms-sw/cmssw/pull/43900#issuecomment-1933410403 should fix it. (Tested locally with `runTheMatrix.py -nel 312.0 --what upgrade,standard,pileup`)

> [12634.0](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-854324/37286/runTheMatrix-results/12634.0_TTbar_14TeV+2023PU)
> [14234.0](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-854324/37286/runTheMatrix-results/14234.0_TTbar_14TeV+2023FSPU)

I am unable to reproduce the issue locally with `runTheMatrix.py -n -l 12634.0,14234.0  --what upgrade,standard,pileup`. 

Let's test again with the updated test parameters to see if the errors still show-up.

**Comment by saumyaphor4252** [comment]
please test

**Comment by perrotta** [comment]
> I am unable to reproduce the issue locally with `runTheMatrix.py -l 12634.0,14234.0 --what upgrade,standard,pileup -j 10 --ibeos`.

I rerun the two workflow with the same architecture as in the PR tests (el8_amd64_gcc12) and the error does reproduce: it happens in a few events only, and different architectures may not hit in the 10 events tested in the wfs.

So definitely there is a problem with the MC payloads. 
@cms-sw/csc-dpg-l2 this is something to be investigated

**Comment by ptcox** [comment]
It's clear from the exception messages that there is something wrong with some of the NoiseMatrix conditions data. Israr is investigating and will have to produce new payloads. (These NoiseMatrix values are used only in simulation, and not in local reco, so the real data tests were unaffected.)

**Comment by perrotta** [comment]
> (These NoiseMatrix values are used only in simulation, and not in local reco, so the real data tests were unaffected.)

Thank you Tim, and Israr!
This explains also why only MC workflows are affected, and why it wasn't catched by the Full Track Validation made on data

**Comment by saumyaphor4252** [comment]
PR updated to revert the NoiseMatrix tag update in the GTs and proceed with the other 3 tags, following discussions in https://cms-talk.web.cern.ch/t/mc-gt-update-csc-conditions-for-run3-mc-gts/33583/10

**Comment by saumyaphor4252** [comment]
please test

**Comment by perrotta** [comment]
+1
- Once the tag for the updated noise matris had been taken out, this PR succeeds also in MC tests, and it is therefore good to go

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
