### PR TITLE
recover multi-thread reproducibility in CTPPS diamond local track y position

### PR DESCRIPTION
**Pull request by slava77**
clear yPosition and width after the fit; test for first hit using yPositionInitial and yWidthInitial instead of hardcoded 0,0

The issue was discovered in 80X.

I'm actually not fully capturing the logic of ```yPosition_``` assignment based on the first hit y position. It looks partially as a way to cache the detector alignment.

In my test job in 80X (running on run 283877) I used 8 threads. The original CTPPSDiamondTrackRecognition.cc can possibly make 2 (arms) * 8 (threads) different values of track y depending which event and which hit ends up on the thread first. The fixed version corresponds to position setting in each event.
On 200 events:  the original getY0 values (with repeat counts)
```
valueIndex   count value
     1        2 3.670e-15
     2       10 5.456e-15
     3        5 5.573e-15
     4        8 5.849e-15
     5        9 7.961e-15
     6        3 8.508e-15
     7        8 9.089e-15
     8        3 9.142e-15
     9        4 9.959e-15
    10        6 1.010e-14
    11        2 1.023e-14
    12        5 1.349e-14
    13        7 1.424e-14
    14       14 1.468e-14
    15        7 1.568e-14
```

The fixed:
```
     1        3 -9.37e-12
     2        4 7.961e-15
     3        2 8.508e-15
     4        3 8.705e-15
     5        1 8.795e-15
     6        1 9.089e-15
     7        2 9.744e-15
     8       10 9.959e-15
     9        2 1.010e-14
    10        9 1.023e-14
    11        4 1.035e-14
    12        3 1.050e-14
    13        1 1.062e-14
    14        1 1.073e-14
    15       10 1.092e-14
    16        5 1.305e-14
    17        3 1.349e-14
    18        8 1.388e-14
    19        3 1.424e-14
    20        4 1.468e-14
    21        1 1.505e-14
    22        7 1.539e-14
    23        1 1.568e-14
    24        5 1.594e-14
```

If these positions are in cm, they look like random roundoffs of zeros.
Still, the assignment should be made without dependence on event order or the number of threads.

@forthommel please check and either confirm that this fix has a meaning or provide a replacement PR.
Thank you.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by forthommel** [comment]
Hi @slava77,
Many thanks for this very nice follow-up!
Indeed, this original y position is parsed from the config file and cached for the whole station, and this is certainly more reasonable to define it as you did than to count on the numerical stability of this variable (originating from a parsed xml) wrt the hardcoded 0.0.
Maybe @nminafra can comment furthermore?

Anyway, thanks again @slava77!

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/18779	 	08e9f21
- jenkins tests pass; there are no differences in comparisons because the CTPPS diamond data periods are not in jenkins tests

**Comment by davidlange6** [comment]
+1

**Pull request merged**
