### PR TITLE
Jingyu 80x stage2 layer2 dqm module

### PR DESCRIPTION
**Pull request by jingyucms**
DQM for L1T Stage2 Calo Layer2
Implemented plots for layer2 in DQM/L1TMonitor. And made data emulator ratio plots of pt eta phi distribution for each object via DQM/L1TMonitorClient. 
Only put C++ in, will be included in central sequences a couple months later.

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
