### PR TITLE
76X HLT (further updates to) round three

### PR DESCRIPTION
**Pull request by perrotta**
Update the HLT menu up to /frozen/2015/25ns14e33/v4.2
It is based on CMSSW_7_6_X_2015-09-12-1100
It keeps the HLT menu in 76X in synchro with the developments integrated in #11041 (74X) and #11042 (75X).

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
