### PR TITLE
Apply HCal noise thresholds to HCal detector-based isolation of electrons

### PR DESCRIPTION
**Pull request by swagata87**
#### PR description:

It looks like HCal noise thresholds are not used in HCal detector-based isolation of electrons. Fixing that in this PR. This isolation is used in HEEP ID. There could be other use-cases also. This bug/feature affects 2022 and 2023. Before that, this variable was built from caloTowers, where HCal thresholds are generally applied. At the beginning of Run3, EGamma dropped the usage of caloTower, and HCal detector-based isolation variable was built instead from HCal recHits (https://github.com/cms-sw/cmssw/pull/33666). It's not clear why at that point it was decided to not use the HCal noise thresholds, most probably it's an oversight. In any case, given the HCal noise issues in Run3, which caused severe data/MC disagreement, there is no good reason to not apply the noise cuts which at least helps to some extent to match data and MC better.

It was understood in the context of https://github.com/cms-sw/cmssw/pull/43164. Most of the reco differences observed there (https://github.com/cms-sw/cmssw/pull/43164#issuecomment-1815921379) are likely due to this bug/feature. 

#### PR validation:

Tested with a Run3 workflow.

### CODE REVIEW

**Comment by mandrenguyen** [comment]
please test

**Comment by swagata87** [comment]
type egamma

**Comment by mandrenguyen** [comment]
+reconstruction
Will this be backported?

**Comment by antoniovilela** [comment]
+1

**Comment by swagata87** [comment]
> Will this be backported?

In general, a backport might not be very necessary, as the variable in question (HCAL detector-based isolation) is not widely used by POGs or PAGs. Most people use HCAL PF cluster based isolation, or PF-candidate based isolation, which are better variables. 

If EGM POG wants (since HEEP ID use it), and if there is a re-reco of 2022 and 2023 data in a release older than where this is merged, then a backport can be made. Tagging EGamma convenors @cms-sw/egamma-pog-l2

**Comment by swagata87** [comment]
Just confirmed from PPD that the rereco of 2022+2023 will be with 14_0_X, where this PR is merged. So I think no backport is needed.

**Pull request merged**
