### PR TITLE
New CPE for 1 MIP clusters (default off)

### PR DESCRIPTION
**Pull request by wmtford**
Back port to 7_3_X new CPE for clusters passing a cut on chargePerCM.  Default is not activated.  New customize py will activate.

### CODE REVIEW

**Comment by perrotta** [comment]
Hi Bill.

Please, notice that the same backport was already proposed by #7225

This pull request contains the additional configuration file
RecoLocalTracker/SiStripRecHitConverter/python/customiseNewStripCPE.py
with respect to both the original #6831 and #7225, and it is therefore different from both them.

Could you please specify whether that file is needed (and why), so that release managers can decide whether to merge this pull request or #7225?

Thank you,
Andrea

**Comment by davidlange6** [comment]
or #7224 for that matter. Many PRs to chose from in this case...

________________________________

**Comment by wmtford** [comment]
Hi Andrea and David,

These three PRs are equivalent so far as I can tell, except that the 
discussion over 7_4_X led to the request for a customization file.  I 
just assumed that it might be wanted here (where it works in reverse of 
the way it does in 7_4_X).  Your call as far as I'm concerned whether to 
use my PR that includes it or one of the others.

Bill

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/7241	970482d
changes appear to be the same as made in 74X (without the actual switch to the new CPE).
jenkins confirms no changes

**Comment by davidlange6** [comment]
+1

**Pull request merged**
