### PR TITLE
TrackingTools/TransientTrack: change return type of ESProducer

### PR DESCRIPTION
**Pull request by gartung**
Remove class member not needed.
Change return type to unique_ptr.

### CODE REVIEW

**Comment by gartung** [comment]
@Dr15Jones  this is the last of the low hangning fruit.

**Comment by Dr15Jones** [comment]
looks good

**Comment by Dr15Jones** [comment]
please test

**Comment by slava77** [comment]
@cmsbuild please test

it looks like the failures are gone based on the recent jenkins tests

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/21987	5382a05
- technical
- jenkins tests pass

**Comment by fabiocos** [comment]
+1

**Pull request merged**
