### PR TITLE
Trigger primitives - fixed the TTClusters & TTStubs 

### PR DESCRIPTION
**Pull request by sudhaahuja**
Removed StackedTrackerGeomtery. Uses new dataformats.
Produces stubs with TrackerGeometry and TrackerTopology.
Modified the TTCluster and TTStubs classes - respective producers , algorithms for each.
TTCluster, TTStub, TTTrack use the Phase2TrackerDigi's instead of PixelDigi's.

### CODE REVIEW

**Comment by boudoul** [comment]
ok better in SLHCDEV :) Now you may want to : 
1) Edit your title to make it more explicit (L1 tk primitives fix bis is not explicit)
2) Change the comment 'Branch fixed to produce stubs with the tab2013 algo' to also explained what are the changes you did apply in this PR

**Comment by delaere** [comment]
Dear all, could somebody have a look? 
This is a long awaited PR to fix the TK primitives in SLHCDEV. It will allow us to re-enable part of the track trigger sequence. Also, we want to move forward and prepare a PR with part of these developments for 81X.
Thanks.

**Comment by mulhearn** [comment]
I'm happy to accept this into CMSSW_6_2_SLHCDEV_X but to get into mainline CMSSW, there will be more review needed.

**Comment by mulhearn** [comment]
+1

**Comment by sudhaahuja** [comment]
@All - Are there any pending issues remaining or the branch can be merged into CMSSW_SLHCDEV?

**Pull request merged**
