### PR TITLE
[12_5_X] L1 DT AM - heap-buffer-overflow fix + slight logic improvement in confirmed TPs

### PR DESCRIPTION
**Pull request by jaimeleonh**
Backport from #39411.

### CODE REVIEW

**Comment by cecilecaillol** [comment]
backport of https://github.com/cms-sw/cmssw/pull/39411

**Comment by cecilecaillol** [comment]
please test

**Comment by cecilecaillol** [comment]
+l1

**Comment by cecilecaillol** [comment]
please test

**Comment by cecilecaillol** [comment]
+l1

**Comment by srimanob** [comment]
+Upgrade

**Comment by perrotta** [comment]
This PR also implicitely backport #39263, which was later reverted by https://github.com/cms-sw/cmssw/pull/39411, and that's why the differences in github look different here and in the master version.
In any case, when this PR will get merged, the  code of L1Trigger/DTTriggerPhase2/src/MuonPathAssociator.cc will become identical in master and in 12_5, wich is what is wanted.
Just relaunching the tests, because the old ones are expired nowadays

**Comment by perrotta** [comment]
please testt

**Comment by missirol** [comment]
please test

**Comment by perrotta** [comment]
+1
- RelValInputs errors are unrelated

**Comment by perrotta** [comment]
merge

**Pull request merged**
