### PR TITLE
CaloParticles in the barrel for Phase2 and generalization of the LC associators

### PR DESCRIPTION
**Pull request by brusale**
#### PR description:

This PR enables the building of the CaloParticles in the barrel for Phase2 and generalizes the LCToCP and LCToSC associators (described [here](https://hgcal.web.cern.ch/Validation/LayerClusterValidation/))  to be run in the barrel.
Also, `HGCalRecHitMapProducer` has been replaced by `RecHitMapProducer` that may be used to create a map in the barrel as well.
In addition, the associators have been moved to `namespace ticl`.

#### PR validation:
 
 Tested on wfs `24896.0`, `24900.0`, `24834.0` and `224834.0`.

@felicepantaleo @rovere

### CODE REVIEW

**Comment by felicepantaleo** [comment]
@cmsbuild please test

**Comment by felicepantaleo** [comment]
@cmsbuild please test

**Comment by jfernan2** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by jfernan2** [comment]
type hgcal

**Comment by jfernan2** [comment]
There seem to be duplicated dictionaries:
Searching for 'classes_def.xml' in '/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_14_1_X_2024-04-01-2300/src'.

./DataFormats/HGCRecHit/src/classes_def.xml
  DetId : unordered_map< DetId, constunsigned int >
  DetId : edm::Wrapper< unordered_map< DetId, constunsigned int > >

**Comment by makortel** [comment]
> Searching for 'classes_def.xml' in '/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_14_1_X_2024-04-01-2300/src'.
> 
> ./DataFormats/HGCRecHit/src/classes_def.xml DetId : unordered_map< DetId, constunsigned int > DetId : edm::Wrapper< unordered_map< DetId, constunsigned int > >

IIUC the checker is (rightfully) complaining that these dictionaries should be defined in `DataFormats/DetId`.

**Comment by rovere** [comment]
Out of curiosity: how many copies of Rechits are introduced by this single PR?
@felicepantaleo

**Comment by brusale** [comment]
> Out of curiosity: how many copies of Rechits are introduced by this single PR? @felicepantaleo

Hi Marco! Indeed I am making too many copies of the RecHits collection, I will take care of it. Thanks for pointing it out!

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by tjavaid** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by srimanob** [comment]
@cmsbuild please test
Just refresh the test after a month. Very sorry to miss this.

**Comment by srimanob** [comment]
+Upgrade

**Comment by felicepantaleo** [comment]
A kind reminder to merge this, as other PRs need to be rebased on top of these changes and signed again.
@antoniovilela @rappoccio @sextonkennedy

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
