### PR TITLE
Run3-hcx337 Fix a bug for wrong DetID assignment in HCAL - relevenat for Runs 1,2,3,4

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Fix a bug for wrong DetID assignment in HCAL - relevenat for Runs 1,2,3,4

#### PR validation:

Use the runTheMatrix test workflows

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for

Need to be back ported to all earlier CMSSW versions

### CODE REVIEW

**Comment by bsunanda** [comment]
type bugfix

**Comment by bsunanda** [comment]
type urgent

**Comment by bsunanda** [comment]
@cmsbuild please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by srimanob** [comment]
FYI @cms-sw/pdmv-l2 @cms-sw/l1-l2

**Comment by perrotta** [comment]
urgent

**Comment by bsunanda** [comment]
+geometry

**Comment by civanch** [comment]
+1

**Comment by srimanob** [comment]
@cmsbuild please test with 20834.911

It seems that with this PR, the error message of HCAL reported in https://github.com/cms-sw/cmssw/issues/37087 for Phase-2 DD4hep is gone.

**Comment by srimanob** [comment]
As [PR test](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-61788e/28775/runTheMatrix-results/20834.911_TTbar_14TeV+2026D88_DD4hep+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14+DigiTrigger+RecoGlobal+HARVESTGlobal+ALCAPhase2/) shows the error message with Phase-2 DD4hep workflow is gone.

**Comment by perrotta** [comment]
+1

**Comment by mmusich** [comment]
> Reco comparison results: 46895 differences found in the comparisons

There's a gazillion changes here. Do we understand them?

**Comment by bsunanda** [comment]
A serious bug in the older version and a fix of that bug in this PR will show zillions of difference showing the earlier bug has serious effect on the outcome of MC predictions
________________________________

**Comment by makortel** [comment]
Does the change impact simulation history?

**Comment by bsunanda** [comment]
It does not change the history in SIM step but surely changes history in DIGI step due to use of thresholds applying to different channels
________________________________

**Comment by makortel** [comment]
Thanks @bsunanda. Then large number of differences in small-scale test is expected, right? (and the statistical compatibility can be assessed only with much larger samples)

**Comment by abdoulline** [comment]
@bsunanda @civanch     it looks like there is a change in GEANT history.
Please, find below HCAL (usual private) test with 50 k single pions (e=50 GeV) randomly distributed in eta-phi.
NB: 
  - GEN (input) is identical in both the cases, so changes come from downstream (SIM) modules;
  - GT is identical ("phase1_2022_realistic" = '125X_mcRun3_2022_realistic_v3').
 One can see that the first row (SimHits plots) differ. 
https://cms-docs.web.cern.ch/hcal-sw-validation/calo_scan_single_pi/12_6_X/12_6_X_2022-11-03-2300_FIX_run3_vs_12_6_X_2022-11-03-2300_run3_SinglePi/ 
  
Otherwise this test doesn't allow to reveal/prove anything other than changes could (probably) be rather small.
Well, HCAL experience tells me that regular RelVals with their 9k stat, when used _regenerated(new)_ GENSIM, may not be sensitive to global variables change <1% and to binned distributions variation <5-7%, unfortunately.

**Pull request merged**
