### PR TITLE
Scouting producers now ignore missing input collections

### PR DESCRIPTION
**Pull request by duanders**
HLTScoutingCaloProducer and HLTScoutingPFProducer no longer return when they fail to find an input collection.  Instead they pack whatever information is available and ignore the missing collection.

This change is needed to complete the integration of the latest scouting trigger paths into the HLT menu.

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
We'd need PRs for 75X and 76X as well!

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
