### PR TITLE
HLT updates on top of CMSSW_7_4_3 for 75X

### PR DESCRIPTION
**Pull request by perrotta**
Updates for the HLT menus, including the B-field taken from DB.
Same as #9292, for 75X

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
+1

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
Sigh, 75X is currently br0ken.

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
Rebased

**Comment by Martin-Grunewald** [comment]
+1

**Comment by Martin-Grunewald** [comment]
@mulhearn 
Please check and sign. Thanks!

**Pull request merged**
