### PR TITLE
saving the collections of ECAL selective readout flags (SrFlags) matc…

### PR DESCRIPTION
**Pull request by cippy**
…hed to digis in the output

We are adding the collection of ECAL Selective Readout (SR) flags in the output of the pi0/eta stream.
These flags are needed to study the impact of the SR thresholds on the pi0/eta reconstruction from low energy photons.

The change affects

    HLTrigger/special/src/HLTRechitsToDigis.cc
    HLTrigger/special/BuildFile.xml
    (the HLT configuration for the pi0/eta stream paths will have to be modified as well adding some parameters)

The source file implements the producer that saves the digis collection in the stream output (only those digis matched to rechits used to build pi0/eta are saved). Similarly, the change we implemented takes the SrFlags collection and produce a new collections storing only the flags matched to digis that are finally kept in the stream output.

The BuildFile.xml must have a new line to include a header used by the source.

Tested from release CMSSW_9_2_12_patch1 running the (updated) HLT configuration on HLTPhysics dataset. The new collections are created and stored in the output dataset.
The event size changes by 2% from 1.96 kB/event to 1.99 kB/event

A similar pull request has been opened from 9_4_X release to master branch (see https://github.com/cms-sw/cmssw/pull/20973)

### CODE REVIEW

**Comment by cippy** [comment]
I just committed the fix for backward compatibility that was asked for PR #20973  as well.
The code was tested again in the new release.

**Comment by Martin-Grunewald** [comment]
backport of #20973

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
