### PR TITLE
Update 2017 EXO paths in offline validation code

### PR DESCRIPTION
**Pull request by sudhaahuja**
This PR covers an update of the offline RelVal validation code with the 2017 HLT paths proposed in the EXOTICA group.

### CODE REVIEW

**Comment by kpedro88** [comment]
-1
nope
To undo what you just did:
```
git checkout -b EXOTrigger_offlineVal sudhaahuja/EXOTrigger_offlineVal
git push -f my-cmssw EXOTrigger_offlineVal
```
Then follow http://cms-sw.github.io/tutorial-resolve-conflicts.html to rebase correctly

**Comment by mtosi** [comment]
@cmsbuild, please test

**Comment by davidlange6** [comment]
Your PR is unmergeable. Please have a look and possibly rebase it.

**Comment by fwyzard** [comment]
@dmitrijus do you have any comments for this PR ?
@davidlange6 do you have any comments for this PR ?

I plan to include it in a second "merged" PR to fix the various conflicts.

**Comment by dmitrijus** [comment]
+1
To answer Andrea's comment, I will have to resign once the conflict is fixed.

**Comment by fwyzard** [comment]
Please do not rebase this.
As soon as @dmitrijus (done) and @davidlange6 let me know that the PR is fine (apart from the conflict) I will fix it in a separate PR.

**Comment by sudhaahuja** [comment]
What else is needed for this PR to be merged? It is written not to rebase but I see conflicts here.

**Comment by davidlange6** [comment]
hi @fwyzard - is this PR integrated in 93x?

**Comment by fwyzard** [comment]
No, I think it never made it into my branch, since it was not OK'ed.

**Comment by davidlange6** [comment]
ok, so lets get it rebased and reviewed. @sudhaahuja

**Comment by davidlange6** [comment]
looks to be obsolete. Closing.

**Comment by mtosi** [comment]
@sudhaahuja 
can you please confirm that the needed update has been integrated via a different PR ?
if not (!?!?!?!) please prepare a PR asap !!!
thanks

**Comment by sudhaahuja** [comment]
@mtosi - Sorry I did not realize that this PR was not merged automatically along with some other PR's. I prepared a new PR - #20932 proposing similar changes in the package HLTriggerOffline/Exotica .

**Pull request closed without merging**
