### PR TITLE
Castor DQM online client python -  for condition DB access use official GT only

### PR DESCRIPTION
**Pull request by popovvp**
might be too late - the same as 16687 done by Salvatore.

### CODE REVIEW

**Comment by dmitrijus** [comment]
Looks fine, but I will ask Salvatore to find out what to merge.

**Comment by popovvp** [comment]
it is the same PR as PR 16687 by Salvatore.

**Comment by diguida** [comment]
@dmitrijus This contains the very same changes as #16687, which I made as a backport of #16564 in order to catch up with the `CMSSW_8_0_24` deployment in online DQM.
You can safely reject this as a duplicate of #16687 
@popovvp please close this PR

**Comment by popovvp** [comment]
closed due to duplicate of PR # 16687

**Pull request closed without merging**
