### PR TITLE
Electron and Photon Regressions in RECO (75X)

### PR DESCRIPTION
**Pull request by lgray**
Backport of #11367.

### CODE REVIEW

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
Some observations in 302.0 (Zeemm) workflow in HI (200 events) in 7_5_3_patch1:
- timing increases significantly for only one module ```         gedPhotonsTmp    121.84 ms/ev -> 329.011 ms/ev ``` this, however, is only 0.7% of the total CPU per event.
- event size has some increase in egamma candidates
    - for gedPhotonsTmp is up by 27% from 1781 to 2340 bytes per event 
    - ecalDrivenGsfElectrons, mvaElectrons, and gedGsfElectronsTmp each go up by 6 to 8% (compared to electrons, twice as many values are added to the ShowerShapes ... and does it mean that electrons don't have the ful5x5 filled or is it compressed so much better?)
- on the physics content side:
    - pfCandidates are essentially unchanged (small diffs in pf photons are present), this is due to absent relinking step in HI 
    - DQM plots are not very helpful: looks like only gedPhotonAnalyzer is configured for the new objects (no electron validator which has the reco/gen plots)
    - gedPhotons change energy .. since most of them are near threshold, the change is  just suggestive of a smearing of the threshold
all_orig-histatvssign594-histat_zeemmhiwf302p0c_recophotons_gedphotonstmp__reco_obj_et
    - gedGsfElectons (gedGsfElectronsTmp collection name) now has the new shape variables filled; however, there is no change in the momentum of the objects.

**Comment by lgray** [comment]
@slava77 There are 6 (x2 for full5x5) shower shapes added to electrons, where there are 15 (x2) new shower shapes for photons.

**Comment by lgray** [comment]
@slava77 and the photon is a smaller object to start with.

**Comment by slava77** [comment]
@lgray is the lack of pt change in GsfElectrons a feature of HI reco, or did something not make it to the HI setup but should have?

**Comment by lgray** [comment]
@slava77 all the electron energy changes come in the relinking step, which is not executed (so far) in the HI reco. It will have to be included at some point if these regressions are important for HI.

**Comment by slava77** [comment]
@mandrenguyen please note the comments above.

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/11402	ccec979
- the same changes are applied in this PR as in the 76X version #11367 
- signoff is based on observations made in 76X and, additionally on some extra detail posted earlier in this PR in the HI (HIMIX MC)
    - since HIMIX appears to be still broken in 76X, I suppose that this feature will not be tested in 760pre6 for HI reco

If I understand correctly, the PR can be merged not sooner than some feedback from 760pre6 relvals appears.

**Comment by davidlange6** [comment]
Hi - I'm cleaning up the 75x CMSSW release queue, so closing issues not directly related to analysis or finalizing the HI MC production. Please make sure these requests are included in the 80x release already. Thanks!

**Pull request closed without merging**
