### PR TITLE
clean up hcal phase2 validation settings

### PR DESCRIPTION
**Pull request by kpedro88**
Noticed some leftover cruft while preparing #22990. (I don't think there will be a merge conflict between this one and that one, but it's possible.)

### CODE REVIEW

**Comment by kpedro88** [comment]
please test

**Comment by kpedro88** [comment]
@vazzolini, @kmaeshima, @dmitrijus, @jfernan2, @vanbesien please sign

**Comment by fabiocos** [comment]
@kpedro88 this needs to be rebased

**Comment by kpedro88** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by fabiocos** [comment]
please test

**Comment by kpedro88** [comment]
@fabiocos can this be merged?

**Comment by fabiocos** [comment]
+1

**Pull request merged**
