### PR TITLE
[92X] Offline DQM extensions for L1T EGamma (calo layer 2) and fixes - backport

### PR DESCRIPTION
**Pull request by kreczko**
Backport of PR #20227 (Jira ticket [CMSLITDPG-171](https://its.cern.ch/jira/browse/CMSLITDPG-171)).

The main PR is not merged yet, this backport might receive code changes based on the review of the main PR.

### CODE REVIEW

**Comment by rekovic** [comment]
please test

**Comment by rekovic** [comment]
@kreczko 
Please change the title to "[92X] Offline DQM extensions for L1T EGamma (calo layer 2) and fixes - backport"

**Comment by rekovic** [comment]
+1

**Comment by rekovic** [comment]
backport of #20227

**Comment by dmitrijus** [comment]
it's not a proper backport, you need to add code-checks commit - which you already added in master version

otherwise, the PR is fine.

**Comment by kreczko** [comment]
As @dmitrijus suggested, I've added the code-checks commit now as well.

@rekovic & @dmitrijus  please resign.

**Comment by rekovic** [comment]
please test

**Comment by rekovic** [comment]
+1

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
