### PR TITLE
Fix the `NVProfilerService` and `ProcessCallGraph`

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Implement a couple of fixes for the `ProcessCallGraph`:
  - check that the `Source` module is added exactly once to the `ProcessCallGraph`;
  - avoid static variables, that would result in invalid process ids when multiple
    `ProcessCallGraph` instances are used _e.g._ by different Services.

Fix the `NVProfilerService` to for the case where the number of modules in the current process is not a valid indicator of the highest module id, for example if some modules have been destroyed because they cannot be part of any schedule. Instead, use a `ProcessCallGraph` to get the highest possible module id.

#### PR validation:

With these changes, adding the `NVProfilerService` to complex configurations (_e.g._ a full HLT menu) works, instead of failing with an assertion.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

To be backported to 12.4.x and 12.5.x for data taking.

### CODE REVIEW

**Comment by fwyzard** [comment]
type bugfix

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
+heterogeneous

**Comment by missirol** [comment]
+hlt

Simply trusting @fwyzard. I don't know enough to judge these changes.

**Comment by perrotta** [comment]
+1

**Pull request merged**
