### PR TITLE
Clean unused dependencies from BuildFiles

### PR DESCRIPTION
**Pull request by guitargeek**
#### PR description:

Another quick BuildFile cleaning PR in the style of many before (for example https://github.com/cms-sw/cmssw/pull/40906).

In some cases, the dependencies had to be moved to the appropriate BuildFile, for example from a plugins directory to the library directory or vice versa.

This PR cleans unnecessary includes from CMSSW BuildFiles that were added in the last months.

#### PR validation:

CMSSW compiles.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

No backport intended.

### CODE REVIEW

**Comment by smorovic** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by francescobrivio** [comment]
+1

**Comment by simonepigazzini** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

**Comment by clacaputo** [comment]
+1

**Comment by emanueleusai** [comment]
+1

**Comment by guitargeek** [comment]
@perrotta Looks like this PR has all the necessary signatures besides yours. Can this be merged? Thanks!

**Comment by tvami** [comment]
> @perrotta 

Andrea is on vacation. Sal needs to be pinged @rappoccio

**Comment by perrotta** [comment]
+1
- Technical: this is a simple "+1" even from vacations ;-)

**Pull request merged**
