### PR TITLE
CSC Beam Halo filter update

### PR DESCRIPTION
**Pull request by lathomas**
(Copy of the PR for 74X) 
CSC Beam Halo Filter update. 
-Pairs of segments in opposite endcaps are now matched with a dr/dz condition (rather than dr previously) 
-New flat CSC segment matching added (the old one remains the default for now): unvetoing CSC segments associated to tracker muons with pt < 3 gev 
-Optional dt matching of opposite endcaps segments 
-Testing a CSC segment/calorechit  matching. 
-Two new working points added in BeamHaloSummary.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

@lathomas please make a PR for 76X

**Comment by lathomas** [comment]
I will try to male the PR for 76X today. In the mean time, is it already possible to integrate this PR to 75X as it was done for 74X? 
Thanks a lot

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
+1

For #11137 be6eaf6a74be067de0380181c838b05beec60e54

Small improvements to the CSC beam halo filter. #11136 is the 74X version of this PR, and it has already been approved by Reco.

The code changes are satisfactory, and Jenkins tests against baseline CMSSW_7_5_X_2015-09-13-2300 show no significant differences. See #11136 for a performance summary that shows no significant change in timing with this PR.

**Comment by lathomas** [comment]
@cvuosalo  @slava77  @davidlange6
I have updated this PR to synchronize it with the recent 76X PR update (now merged): 
https://github.com/cms-sw/cmssw/pull/11528

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@lathomas 
we don't have #11182 in 75X yet.
So, your change with HcalStripHaloFilter will not work.

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
+1

For #11137 e81a87d4d07ec36380cf475a9af75a96ec7b0d09

Second approval, after addition of analysis code from #11528. New Jenkins tests still show no significant differences.
#11136 is the 74X version of this PR, and it has already been approved by Reco again.
Extended tests for #11136 also show no significant differences or changes in timing.

**Comment by lathomas** [comment]
Copy of the following PR for 75X: 
https://github.com/cms-sw/cmssw/pull/11737

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
+1

For #11137 0c4a36b8f7024322a1e86e3f5816777901cd1a1d

Third approval of this PR for new, small adjustments to the CSC beam halo filter that come from 76X #11737, which has already been approved by Reco. #11136 is the matching PR to this one for 74X.

The code changes are satisfactory, and Jenkins tests against baseline CMSSW_7_5_X_2015-10-12-2300 show no significant differences. An additional test of workflow 25202.0_TTbar_13 was done for #11737, and it showed no significant differences.

**Pull request merged**
