### PR TITLE
Hcal: Fix the TDC Simulation Algorithm 

### PR DESCRIPTION
**Pull request by lwang046**
Correct the TDC algorithm based on the understanding that precise calo sample bin represents the integral of the charge in fC over 0.5ns, in that sense, the preciseData is the current going into the QIE.

### CODE REVIEW

**Comment by abdoulline** [comment]
@civanch  Vladimir, could you do "please test"?

**Comment by civanch** [comment]
please test

**Comment by abdoulline** [comment]
The same comment (as for PR #32730 ) holds here 
https://github.com/cms-sw/cmssw/pull/32730#issuecomment-767457972

**Comment by civanch** [comment]
+1

changes expected; failed WF is due to files absence not this PR.

**Comment by qliphy** [comment]
+1

**Comment by qliphy** [comment]
merge

**Pull request merged**
