### PR TITLE
bug fix in TrackerGeometry

### PR DESCRIPTION
**Pull request by suchandradutta**

### CODE REVIEW

**Comment by davidlange6** [comment]
cmsbuild, please test

**Comment by suchandradutta** [comment]
L1TrackTrigger_step should be skipped in the tests. It will take time to restore that part. This was the
case also for earlier PRs. @boudoul please confirm

**Comment by delaere** [comment]
I confirm that this error is expected and has nothing to do with this PR.
This PR introduces an important bugfix in the way sensor types are identified.

**Comment by davidlange6** [comment]
please test

**Comment by delaere** [comment]
#13112 was merged... tests should now work better.

**Pull request merged**
