### PR TITLE
Use the right era modification for 2017 HCAL TPs

### PR DESCRIPTION
**Pull request by matz-e**
While customizations are in place already, era modifications were missing.

### CODE REVIEW

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by kpedro88** [comment]
Looks like this has to wait until #15994 gets merged to clean up the 2017 workflows. Some of the intermediate workflows from pre12 have the HE_2017 Era but no other HCAL 2017 changes, and I suspect that is causing the matrix test failures.

**Comment by matz-e** [comment]
@kpedro88 that seems to be the case. I dug in a little bit, and the `10024.0` scenario uses that era, but does not provide QIE11 dataframes to the TP algorithm. "Bad things will happen" applies. Not sure if a crash is really what should happen…

I could add some warnings for configuration mismatches (printed before such a crash), if requested.

**Comment by matz-e** [comment]
@kpedro88 I see that #15994 got merged. Could we re-test this, please?

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by kpedro88** [comment]
@cmsbuild please test

**Pull request merged**
