### PR TITLE
GEM online DQM bug fix - full GE1/1, backport to 11_0_X

### PR DESCRIPTION
**Pull request by quark2**
#### PR description:
This backport PR to 11_0_X which fixes a bug on the part of onlineDQM for GEM. The previous version uses `endRun` to draw summary plots, which is not a good idea in online DQM. This new version moves it to `dqmEndLuminosityBlock`.

#### PR validation:
Test are done and one can check again by `runTheMatrix` workflows

@jshlee @watson-ij

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by andrius-k** [comment]
Hi quark2, 
Now it looks good for the Online, but in order for the harvester to be working in the Offline, you also have to provide the harvesting functionality in the `endJob` method.

**Comment by quark2** [comment]
Hi @andrius-k, 

Thanks for the check. And okay, I'll note that. Offline DQM is still in progress so that we will update `endJob` for it.

Best regards, 
Byeonghak Ko

**Comment by jfernan2** [comment]
backport #28978

**Comment by jfernan2** [comment]
Hi @quark2 there are Clan warnings to fix:
DQM/GEM/plugins/GEMDQMHarvester.cc
/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_0_X_2020-02-17-1100/src/DQM/GEM/plugins/GEMDQMHarvester.cc:31:8: warning: 'dqmEndLuminosityBlock' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]

**Comment by quark2** [comment]
Hi @jfernan2, 

I added the missed keyword and tested. Thanks!

Best regards, 
Byeonghak Ko

**Comment by andrius-k** [comment]
please test

**Comment by andrius-k** [comment]
Hi @quark2,
I will deploy this PR to the playback system. What about the GUI? Are all recently added changes reflected in the playback apart from harvesting plots not being filled in?

**Comment by quark2** [comment]
Hi @andrius-k, 

I think if this PR works well (I mean, the summary plot is created well), we can see all of what I want in the current GUI.

Best regards, 
Byeonghak Ko

**Comment by andrius-k** [comment]
@quark2,
Cool, I'll let you know once the PR is deployed.

**Comment by quark2** [comment]
Hi, @andrius-k, 

Okay, thanks a lot!

Best regards, 
Byeonghak Ko

**Comment by andrius-k** [comment]
@quark2,
I just deployed this PR to DQM playback system and summary plot is getting filled. Please have a look and let us know if we can deploy the CMSSW as well as DQM GUI changes to the production.

**Comment by quark2** [comment]
Hi @andrius-k, 

Although it looks not beautiful, I think it's enough.

Umm, btw I found that the percentage is not working well; all blank, but it says 100%. I'll check that.

Best regards, 
Byeonghak Ko

**Comment by jfernan2** [comment]
@quark2  do you plan to fix the percentage issue in this same PR?

**Comment by quark2** [comment]
Hi @jfernan2, 

Yep, I have, and I'm still working on it. Sorry for late of that...

Best regards, 
Byeonghak Ko

**Comment by jfernan2** [comment]
hold
Waiting for fix from GEM

**Comment by quark2** [comment]
Sorry for late fix. This new one is for fix of the percentage issue and the crash-by-geometry issue.

**Comment by jfernan2** [comment]
I am sorry @quark2  but the commit in this PR is not the same as in the 11_1_X master PR https://github.com/cms-sw/cmssw/pull/28978 , where you modified 4 files, including:
DQM/Integration/python/clients/gem_dqm_sourceclient-live_cfg.py 

And my understanding was that you should load the GEM geometry from the GlobalTag (after inclusion by AlCa on the DB), and not using 
Configuration.Geometry.GeometryExtended2021Reco_cff

Something like:
process.load("Configuration.StandardSequences.GeometryRecoDB_cff") 
and then the GT should load the appropiate Geometry, am I correct?

**Comment by quark2** [comment]
Hi, @jfernan2, 

As I know too, you're right, it should be used `process.load("Configuration.StandardSequences.GeometryRecoDB_cff")`. But we've found that this standard sequences has no GEM geometry so that we use a temporary way to fix this issue. We have also checked that with `Configuration.Geometry.GeometryExtended2021Reco_cff` DQM works.

Btw, the difference from #28978 is because of some problem on my dealing with git. I've fixed it.

Best regards, 
Byeonghak Ko

**Comment by quark2** [comment]
Hi all, 

New GTs with GEM geometry has been presented: 

110X_dataRun3_HLT_GEMRecoGEO_v1
111X_dataRun3_HLT_GEMRecoGEO_v1

They are tested in local and everything works well. Could you guys make a playback with them?

Best regards, 
Byeonghak Ko

**Comment by jfernan2** [comment]
@quark2 please include them in the corresponding config of the PRs so that we can test them directly.
Thanks

**Comment by quark2** [comment]
Hi @jfernan2, 

As I know, the GT can be inserted into this line: 
https://github.com/quark2/cmssw/blob/GEMOnlineDQMBugFix_toMaster/DQM/Integration/python/config/FrontierCondition_GT_cfi.py#L3

Did you mean to change the GT in this line to the new ones?

Best regards, 
Byeonghak Ko

**Comment by jfernan2** [comment]
Yes, exactly
Thanks.

**Comment by jfernan2** [comment]
@quark2 please bear also in mind that P5 is down/closed, hence the machines there two. Once P5 comes back to live, and there are no plans for that yet, we will make the test.
Thanks

**Comment by quark2** [comment]
Dear @jfernan2, 

Okay, I'll note that. And the GT has been update. Also, some minor update is included. They are also patched to the PR to master.

Best regards, 
Byeonghak Ko

**Comment by silviodonato** [comment]
#28978 was integrated. @quark2 can you synchronize this backport to #28978?

**Comment by quark2** [comment]
Hi @silviodonato, 

The changes of this PR and #28978 coincides (except the GT field which must be different) at least in the GEM onlineDQM part. Is there another thing I have to synchonize?

Best regards, 
Byeonghak Ko

**Comment by silviodonato** [comment]
@quark2 I thought @jfernan2 was waiting for an update of this PR.
@jfernan2 this PR is still on hold from you.

**Comment by jfernan2** [comment]
unhold

**Comment by jfernan2** [comment]
@silviodonato since we could not test the PR that's why held it, but I understand you want to merge it for the future.

**Comment by jfernan2** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
