### PR TITLE
Add standard open file message; minor updates

### PR DESCRIPTION
**Pull request by namapane**
#### PR description:

Adding the standard open file message as requested in #44293.

This PR also incudes 2 minor updates:
- add support for short int branches
- close optional histogram files in the proper place

#### PR validation:

Mods checked with runtests and local tests.

### CODE REVIEW

**Comment by hqucms** [comment]
please test

**Comment by namapane** [comment]
> please test

it will fail until somebody puts back in place the test file that was moved away by the archive scripts, cf #44293.

**Comment by iarspider** [comment]
I have moved the file back and restarted the tests.

**Comment by hqucms** [comment]
+1

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
