### PR TITLE
[GEOMETRY-UPGRADE] [CLANG] Fix warnings reported by llvm16 in CLANG IBs

### PR DESCRIPTION
**Pull request by aandvalenzuela**
Fixes set but unused warnings from clang-16 in CLANG IBs.

### CODE REVIEW

**Comment by aandvalenzuela** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by aandvalenzuela** [comment]
Hello! Any news from @cms-sw/upgrade-l2 regarding this issue? We would like to integrate llvm16 in our master branch for IBs :)
Many thanks!

**Comment by perrotta** [comment]
+1
- @aandvalenzuela the fix is so simple that we can bypass here the @cms-sw/upgrade-l2 signature and move forward

**Comment by aandvalenzuela** [comment]
Thanks @perrotta!

**Comment by srimanob** [comment]
+Upgrade

**Pull request merged**
