### PR TITLE
HLT Offline DQM: add HLT_Ele30_WPTight_Gsf and change E/gamma IDs [`13_1_X`]

### PR DESCRIPTION
**Pull request by missirol**
backport of #42049
backport of #42294

#### PR description:

Verbatim backport of #42049 and #42294 by @RSalvatico. From the descriptions of the two PRs:

> The purpose of this PR is to:
> 
>   * add `HLT_Ele30_WPTight_Gsf` to the OfflineDQM among the monitored paths in `HLT/EGM/TagAndProbeEffs`, as requested by TSG in [CMSHLT-2810](https://its.cern.ch/jira/browse/CMSHLT-2810);
> 
>   * change the offline electron and photon IDs for EGM to the newest Run3 ones ([electrons](https://github.com/cms-sw/cmssw/blob/master/RecoEgamma/ElectronIdentification/python/Identification/cutBasedElectronID_Winter22_122X_V1_cff.py), [photons](https://github.com/cms-sw/cmssw/blob/master/RecoEgamma/PhotonIdentification/python/Identification/cutBasedPhotonID_RunIIIWinter22_122X_V1_cff.py));
> 
>   * clean up, removing HEM/HEP plots (which were relevant in 2017) and removing trigger paths which are no longer in the menu.

and

> This PR is a follow up of #42049 . In the latter, the update of the `egmGsfElectronIDsForDQM` module to include (via VID) only new Run3 electron IDs had created issues to non-EGM DQM, such as TOP, B2G and ParticleNet. In order to address this, the current PR updates the electron IDs used by non-EGM DQM too. Other POGs and PAGs have been informed and have followed up on [CMSHLT-2876](https://its.cern.ch/jira/browse/CMSHLT-2876).

FYI: @cms-sw/egamma-pog-l2

#### PR validation:

None.

#### If this PR is a backport, please specify the original PR and why you need to backport that PR. If this PR will be backported, please specify to which release cycle the backport is meant for:

#42049
#42294

Update of EGM-HLT offline DQM relevant to 2023 pp data-taking.

### CODE REVIEW

**Comment by missirol** [comment]
please test

**Comment by missirol** [comment]
hold

> You potentially added 2171 lines to the logs

This requires a closer look.

**Comment by missirol** [comment]
please test

**Comment by missirol** [comment]
unhold

Including the backport of #42294 fixed the issue causing log warnings, as expected.

**Comment by emanueleusai** [comment]
+1

**Comment by rappoccio** [comment]
+1

**Pull request merged**
