### PR TITLE
PPS diamond mapping XML for 2023 run (backport)

### PR DESCRIPTION
**Pull request by grzanka**
#### PR description:

This PR updates the XML mappings for PPS diamond detectors for 2023 run campaign.
The change is due to hardware changes needed to be implemented in PPS to cope with higher trigger rate.
Unfortunately we come up late with this PS, as detectors will be installed end of February 2023.
Backward compatibility is sustained.
Backport of https://github.com/cms-sw/cmssw/pull/40763

#### PR validation:

This PR was validated with relvals 136.793, 1043 and 1044 (which run PPS reconstruction), as in https://github.com/cms-sw/cmssw/pull/40763

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

This is a backport of https://github.com/cms-sw/cmssw/pull/40763 into 13_0_X,  as requested in https://github.com/cms-sw/cmssw/pull/40763#issuecomment-1438925498

### CODE REVIEW

**Comment by mandrenguyen** [comment]
type ctpps

**Comment by mandrenguyen** [comment]
backport of #40763

**Comment by mandrenguyen** [comment]
test parameters:

    workflows = 136.793,1043,1044

**Comment by mandrenguyen** [comment]
please test

**Comment by tvami** [comment]
+alca
 * as agreed in the master PR, this really needs to go to the EventSetup -- will be done in a followup PR

**Comment by mandrenguyen** [comment]
+reconstruction
Needed for data taking

**Comment by perrotta** [comment]
+1

**Pull request merged**
