### PR TITLE
[14_0_X] Add option to sort candidates by pT in Unified Particle Transformer and PR 45689

### PR DESCRIPTION
**Pull request by stahlleiton**
#### PR description:

Backport of: https://github.com/cms-sw/cmssw/pull/45843 and https://github.com/cms-sw/cmssw/pull/45689

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by stahlleiton** [comment]
> please test

why is the test still pending?

**Comment by jfernan2** [comment]
+1

**Comment by jfernan2** [comment]
Test failure is unrelated

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
