### PR TITLE
add possibility of using getPU_NumInteractions

### PR DESCRIPTION
**Pull request by mtosi**
as discussed w/ tracking POG
there is the need of selecting events by using getPU_NumInteractions
@makortel

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by fabiocos** [comment]
@mtosi this PR looks forgotten since lot of time with no good reason. Recovering a comment of @davidlange6 from my notes: it looks to me ok, but may be the parameter name might be a bit more explicative, say "useTrueNumInteraction", or perhaps "useNumSimulatedVertices"?

**Comment by mtosi** [comment]
@fabiocos apologies for the delay, I really missed your message
I've just updated the code, by changing the name into `useTrueNumInteraction` (hope it is fine, now)
and thanks !

**Comment by mtosi** [comment]
@cmsbuild, please test

**Comment by mtosi** [comment]
@cmsbuild, please test

**Comment by fabiocos** [comment]
@mtosi thank you, @santocch FYI, I would like to merge it and finally close it, unless you have further comments

**Comment by santocch** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
