### PR TITLE
IOMC/RandomEngine/test fix bug in initialization of sleep timer.

### PR DESCRIPTION
**Pull request by gartung**
This is a bug because the intent was to sleep 0.025 seconds not 0 seconds.

  /build/cmsbld/jenkins-workarea/workspace/build-any-ib/w/tmp/BUILDROOT/f60d4bf7e099ce1e597b02cf09f0745b/opt/cmssw/slc6_amd64_gcc530/cms/cmssw-patch/CMSSW_9_1_CLANG_X_2017-03-15-2300/src/IOMC/RandomEngine/test/TestRandomNumberServiceGlobal.cc:191:11: warning: implicit conversion from 'double' to 'unsigned int' changes value from 0.025 to 0 [-Wliteral-conversion]
     sleep(0.025);
    ~~~~~ ^~~~~

### CODE REVIEW

**Comment by wddgit** [comment]
I could be wrong, but I think this fix will still round to 0 even if it evades the warning because the argument of sleep is an unsigned int. I am not sure what the best alternative is. There is nanosleep and also std::this_thread::sleep_for, although I have not actually ever used either one and do not know if they are appropriate for this situation. The second one is in <thread> and I do not know whether that is OK or not.

**Comment by gartung** [comment]
How about usleep(25000)?

**Comment by wddgit** [comment]
Looks good to me. I looked and usleep is used other places in CMSSW.

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
Please test

**Comment by Dr15Jones** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
