### PR TITLE
SimG4Core packages: clean up clang warnings:

### PR DESCRIPTION
**Pull request by gartung**
SimG4Core/HelpfulWatchers/src/SimTracer.h:67:1: warning: 'update' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
 UPDATE(DDDWorld)
^
SimG4Core/HelpfulWatchers/src/SimTracer.h:43:27: note: expanded from macro 'UPDATE'
                          ^

SimG4Core/HelpfulWatchers/src/G4StepStatistics.h:156:1: warning: 'update' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
 UPDATE(DDDWorld)
^

SimG4Core/HelpfulWatchers/src/G4StepStatistics.h:129:27: note: expanded from macro 'UPDATE'
                          ^

SimG4Core/PhysicsLists/interface/CMSFTFPNeutronBuilder.hh:33:10: warning: 'SetMinEnergy' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
     void SetMinEnergy(G4double aM) {theMin = aM;}
         ^

SimG4Core/PhysicsLists/interface/CMSFTFPNeutronBuilder.hh:34:10: warning: 'SetMaxEnergy' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
     void SetMaxEnergy(G4double aM) {theMax = aM;}
         ^

SimG4Core/PhysicsLists/interface/CMSFTFPPiKBuilder.hh:38:10: warning: 'SetMinEnergy' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
     void SetMinEnergy(G4double aM) {theMin = aM;}
         ^

SimG4Core/PhysicsLists/interface/CMSFTFPPiKBuilder.hh:39:10: warning: 'SetMaxEnergy' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
     void SetMaxEnergy(G4double aM) {theMax = aM;}
         ^

SimG4Core/PhysicsLists/interface/CMSFTFPProtonBuilder.hh:31:10: warning: 'SetMinEnergy' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
     void SetMinEnergy(G4double aM) {theMin = aM;}
         ^

SimG4Core/PhysicsLists/interface/CMSFTFPProtonBuilder.hh:32:10: warning: 'SetMaxEnergy' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
     void SetMaxEnergy(G4double aM) {theMax = aM;}
         ^

### CODE REVIEW

**Comment by gartung** [comment]
@Dr15Jones

**Comment by Dr15Jones** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by fabiocos** [comment]
The differences are concentrated in a FastSim workflow, and looks unrelated to this PR, most likely due to the fastsim muon fix included in the merge

**Comment by fabiocos** [comment]
+1

**Pull request merged**
