### PR TITLE
Geometry 2017 Payload Scripts

### PR DESCRIPTION
**Pull request by ianna**
- New scripts to dump 2017 geometry payloads

### CODE REVIEW

**Comment by ianna** [comment]
@cmsbuild please test

**Comment by ianna** [comment]
+1

**Comment by ianna** [comment]
@ggovi - please, have a look at this PR. Thanks.

**Comment by ianna** [comment]
@ggovi - ping

**Comment by ggovi** [comment]
+1

**Comment by ianna** [comment]
@davidlange6 please do take it to pre6

**Comment by davidlange6** [comment]
+1

**Pull request merged**
