### PR TITLE
Condition DB modules for HLT workflow: clean up old lumi information source from DAQ 

### PR DESCRIPTION
**Pull request by ggovi**
#### PR description:

Changes for the modules serving the HLT condition workflows:

- Old DAQ http-based function to get lumisection info has been removed
- Defaults with externally-provided run number have been restored
- Integration tests modified accordingly

#### PR validation:

Integration tests

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Back-port of https://github.com/cms-sw/cmssw/pull/32876
Required to run in the online environment

### CODE REVIEW

**Comment by ggovi** [comment]
please test

**Comment by ggovi** [comment]
please test

**Comment by christopheralanwest** [comment]
please test

**Comment by ggovi** [comment]
+1

**Comment by silviodonato** [comment]
do you have any comment @cms-sw/alca-l2 ?

**Comment by yuanchao** [comment]
+1
* matrix tests and unit tests all passed
* no build warnings / errors
* (commented "lastLumiFile" still needed?)

**Comment by qliphy** [comment]
+1

**Pull request merged**
