### PR TITLE
Susybsmhlt

### PR DESCRIPTION
**Pull request by alibordi**
These are all updated new HLTOffline paths for SUSYBSM from the latest fills/runs. Paths has been compared for same old thresholds and also for the new thresholds. Few paths has not been updated because they were not available in list of latest fills/runs.

### CODE REVIEW

**Comment by slava77** [comment]
-1

bad submission
commit history suggests it had to go to 92X, but was submitted to master

**Comment by arunhep** [comment]
-1
seems like need a rebase

**Comment by Martin-Grunewald** [comment]
-1

**Comment by kpedro88** [comment]
-1
wrong branch?

**Pull request closed without merging**
