### PR TITLE
Include the staggered GE21 geometry in M2

### PR DESCRIPTION
**Pull request by pietverwilligen**
inclusion of the staggered gap geometry for ge21 in M2
continuation of PR #17970 #18047

### CODE REVIEW

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by kpedro88** [comment]
+1

**Comment by ianna** [comment]
+1

**Comment by calabria** [comment]
can we have this PR integrated? Thanks.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
