### PR TITLE
bsunanda:Run2-alca38 Backporting the additional protection from PR 13720

### PR DESCRIPTION
**Pull request by bsunanda**
The protection is needed if Pythia8 is used instead of Pythia6

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by covarell** [comment]
+1

**Comment by bsunanda** [comment]
@davidlange6 Could we get a new patch version of 7_1 so that we can request for a MC production

**Comment by davidlange6** [comment]
its on the to do list (obviously not urgent since we did one already for this same request:) )

**Comment by bsunanda** [comment]
@davidlange6 Please integrate this backporting

**Comment by davidlange6** [comment]
+1

**Pull request merged**
