### PR TITLE
Fix elements_with_stride_nd when the index is outside the extent [13.1.x]

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Extend `testKernel.dev.cc` with a 2D kernel test that uses large block sizes and redundant blocks.

Fix `elements_with_stride_nd` when the initial index is outside the extent; this fixes the issue revealed by the new test.

Also:
  - add support for the `AccCpuThreads` accelerator;
  - rename member variables for consistency;
  - improve comments.

#### PR validation:

The new unit tests completes successfully.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport of #42558.

### CODE REVIEW

**Comment by fwyzard** [comment]
type bugfix

**Comment by fwyzard** [comment]
backport #42558

**Comment by fwyzard** [comment]
enable gpu

**Comment by fwyzard** [comment]
please test with cms-sw/cmsdist#8647

**Comment by fwyzard** [comment]
+heterogeneous

**Comment by rappoccio** [comment]
+1

**Pull request merged**
