### PR TITLE
Drop PhotosInterface, support for tauola 27.x from TauolaInterface

### PR DESCRIPTION
**Pull request by iarspider**
#### PR description:

Drop PhotosInterface due to removal of legacy MC generators (https://github.com/cms-sw/cmsdist/pull/7763).

### CODE REVIEW

**Comment by iarspider** [comment]
please test

**Comment by iarspider** [comment]
please test with #37612,https://github.com/cms-sw/cmsdist/pull/7807

**Comment by iarspider** [comment]
please test with https://github.com/cms-sw/cmsdist/pull/7807

**Comment by iarspider** [comment]
please test with cms-sw/cmsdist#7807,cms-sw/cmsdist#7806

**Comment by iarspider** [comment]
please test with cms-sw/cmsdist#7807,cms-sw/cmsdist#7806

**Comment by iarspider** [comment]
please test with cms-sw/cmsdist#7807,cms-sw/cmsdist#7806,#37612

**Comment by smuzaffar** [comment]
@cms-sw/generators-l2 , I suggest that we merge this (along with cmsdist PRs) in DEVEL IBs to test full runTheMatrix. If DEVEL IBs show no failure then we can backport these for `master` branch.

**Comment by smuzaffar** [comment]
@qliphy @perrotta , we would like to test these changes first in DEVEL IBs, if @cms-sw/generators-l2 has no objections then please include these for next DEVEL IBs ( along with the cmsdist PRs)

**Comment by smuzaffar** [comment]
please test with cms-sw/cmsdist#7807

**Comment by perrotta** [comment]
@cms-sw/generators-l2 do you have any objection in merging these PRs in the devel branch (not yet in the main release)?

**Comment by Saptaparna** [comment]
No objections. +1

**Comment by perrotta** [comment]
merge

**Pull request merged**
