### PR TITLE
Fix #28803 (GenParticles2HepMC with exotic LHE)

### LINKED ISSUE #28803: Crash in RivetInterface (NanoAOD) when only 1 incident parton is found
Following the recent report on infinite loop in RECOSIM which bug-fix PR is placed in https://github.com/cms-sw/cmssw/pull/28802

Another issue is found in NanoAOD step when local test is done. It seems that in the event mentioned, example at the end (*), somehow parton1 is matched, while parton2 is NULL. This leads to a crash in
https://github.com/cms-sw/cmssw/blob/568c52a6ce12d5bbe3608f58be8f9d66fb02c489/GeneratorInterface/RivetInterface/plugins/GenParticles2HepMCConverter.cc#L139-L154

To test: files (LHE, configuration, root) can be found in
/afs/cern.ch/user/s/srimanob/public/ForPdmV/McM/PPS-RunIIFall18GS-00004

CMSSW_10_2_11_patch1 is used in DR/MiniAOD steps
+ PPS-RunIIFall18GS-00004_1_cfg.py for GEN-SIM
+ PPS-RunIIAutumn18DRPremix-00004_1_cfg.py for DIGI
+ PPS-RunIIAutumn18DRPremix-00004_2_cfg.py for RECO => success if #28802 is integrated
   + Output = PPS-RunIIAutumn18DRPremix-00004.root
+ PPS-RunIIAutumn18MiniAOD-00004_1_cfg.py for MINIAOD
   + Output = PPS-RunIIAutumn18MiniAOD-00004.root

CMSSW_10_2_18 is used for NanoAOD step
+ NanoAOD_PPS_cfg.py

(*)
/afs/cern.ch/user/s/srimanob/public/ForPdmV/McM/PPS-RunIIFall18GS-00004/LPAIR_gammagammaMuMu_inel-el_pt40.lhe.xz

### PR DESCRIPTION
**Pull request by mseidel42**
#### PR description:

Fixes crash in GenParticles2HepMCConverter (#28803) by adding fake beam particles for exotic LHE files with only one beam-particle candidate. This was used for NeutrinoGun samples (no beam particles) before.

#### PR validation:

* Processed NanoAod from problematic events
* Processed MiniAod events to produce Rivet histograms

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Backport of https://github.com/cms-sw/cmssw/pull/28876

### CODE REVIEW

**Comment by srimanob** [comment]
@intrepid42 
Which workflow you are testing?
I assume we did not run Run-2 workflows anymore, I can have a look.

**Comment by intrepid42** [comment]
Hi Phat, I just tried your `NanoAOD_PPS_cfg.py` in CMSSW 11_1_X. I fixed the general Rivet problem there, so I will do the PR to master soon.

**Comment by qliphy** [comment]
please test

**Comment by qliphy** [comment]
+1

**Comment by silviodonato** [comment]
+1
please make a backport also for 10_6_x

**Pull request merged**
