### PR TITLE
Run2-hcx197 Modify testing of Run3 geometry

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Make test codes  relevant for Run3 HCAL geometry
 
#### PR validation:

Tested with runTheMatrix.py with -l limited

#### if this PR is a backport please specify the original PR:

None

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
+1

**Comment by jfernan2** [comment]
+1

**Comment by fabiocos** [comment]
@bsunanda @cvuosalo it seems to me that the test geometries modified here are then no more used in the test cfgs, which are now based on DB. Could you please clarify the purpose of the changes?

**Comment by fabiocos** [comment]
@bsunanda @cvuosalo could you please address my question?

**Comment by cvuosalo** [comment]
@fabiocos: The purpose of this PR would be best explained by @bsunanda.

**Comment by bsunanda** [comment]
I was checking if the changes which I made to geometry code works fine with all earlier geometries and there I wanted to check with the XML geometry first. If the tests are successful with XML geometry it will work for DB geometry.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
