### PR TITLE
[12_6_X] TriggerObjectTableProducer configuration and bug fixes

### PR DESCRIPTION
**Pull request by vlimant**
#### PR description:

this is a back port of #40145, as most changes there are actually relevant for a 12.6 nano

#### PR validation:

all done in #40145

### CODE REVIEW

**Comment by vlimant** [comment]
enable nano

**Comment by vlimant** [comment]
please test

**Comment by vlimant** [comment]
+1

**Comment by rappoccio** [comment]
Sorry, I think I'm losing track here. Didn't we decide NOT to have a remini / renano in 12_6?

**Comment by vlimant** [comment]
we would still want this, in particular the bug fix part on matching to be in 12.6 to make it "usable for something"

**Comment by perrotta** [comment]
I imagine that the much larger number of TriggerObject selected enters the "bug fixes" part of this PR:
image

Can you please confirm @vlimant ?

**Comment by vlimant** [comment]
yes, getting more photon trigger objects is what we want to fix here (among other things)

**Comment by perrotta** [comment]
+1

**Pull request merged**
