### PR TITLE
[14_0_X] Revert "Workaround to produce exactly same data products in Serial and CUDA backends in Alpaka modules possibly used at HLT"

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

Reverts cms-sw/cmssw#44699, to be used in conjunction with https://github.com/cms-sw/cmssw/pull/44978

#### PR validation:

None

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport of https://github.com/cms-sw/cmssw/pull/45080

### CODE REVIEW

**Comment by makortel** [comment]
enable gpu

**Comment by antoniovilela** [comment]
@smuzaffar @makortel @cms-sw/orp-l2 @cms-sw/ppd-l2 
Confirming:
Plan is to merge in 14_1_X https://github.com/cms-sw/cmssw/pull/45080 together with https://github.com/cms-sw/cmssw/pull/44892
Then, this PR https://github.com/cms-sw/cmssw/pull/45081 plus https://github.com/cms-sw/cmssw/pull/44978 will go in the special 14_0_X branch, starting from 14_0_7_patch1.

**Comment by smuzaffar** [comment]
> Then, this PR https://github.com/cms-sw/cmssw/pull/45081 plus https://github.com/cms-sw/cmssw/pull/44978 will go in the special 14_0_X branch, starting from 14_0_7_patch1.

@antoniovilela , just to be sure,  #45081 and #44978  will also go in CMSSW_14_0_X ... right? and once these PR are merged then we want to have CMSSW_14_0_7_HLT release (or please suggest a better name) which should have 14_0_7_patch1 + #45081 and  #44978 ... right?

**Comment by mmusich** [comment]
> just to be sure, https://github.com/cms-sw/cmssw/pull/45081 and https://github.com/cms-sw/cmssw/pull/44978 will also go in CMSSW_14_0_X ... right?

I thought the whole point of the special branch was to NOT have https://github.com/cms-sw/cmssw/pull/45081 and https://github.com/cms-sw/cmssw/pull/44978 in 14_0_X until tested (in the special release). What am I missing?

**Comment by malbouis** [comment]
> I thought the whole point of the special branch was to NOT have #45081 and #44978 in 14_0_X until tested (in the special release). What am I missing?

I think we do not yet want to merge 44978 into 140X. It should first be tested and when we’re certain it is doing what’s intended, then we merge. 
this is why we need the special release with 44978 (the definite solution) in and 44968 (the workaround) out.

**Comment by smuzaffar** [comment]
> > just to be sure, #45081 and #44978 will also go in CMSSW_14_0_X ... right?
> 
> I thought the whole point of the special branch was to NOT have #45081 and #44978 in 14_0_X until tested (in the special release). 

ok, understood now

**Comment by antoniovilela** [comment]
> > > just to be sure, #45081 and #44978 will also go in CMSSW_14_0_X ... right?
> > 
> > 
> > I thought the whole point of the special branch was to NOT have #45081 and #44978 in 14_0_X until tested (in the special release).
> 
> ok, understood now

Many thanks @smuzaffar @mmusich @malbouis

**Comment by smuzaffar** [comment]
@makortel @Dr15Jones @antoniovilela @rappoccio , both #45080 and #44892 are merged in 14.1.X and will be part of 11h00 IB today. 
I have created CMSSW_14_0_HLTTest branch which has CMSSW_14_0_7_patch1 + changes from #45081 and #44978 . The changes w.r.t 14.0.7.patch1 are https://github.com/cms-sw/cmssw/compare/CMSSW_14_0_7_patch1...CMSSW_14_0_HLTTest?expand=1 . I can start the build of CMSSW_14_0_7_HLTTest release later today(around 16h00) and can upload it once we have good results from 14.1.X 11h IB. Let me know if all look good for CMSSW_14_0_7_HLTTest branch.

By the way, do we need all archs for this test release or production arch (i.e. el8_amd64_gcc12) is enough? Do we a MULTIARCHS release too ?

**Comment by francescobrivio** [comment]
> By the way, do we need all archs for this test release or production arch (i.e. el8_amd64_gcc12) is enough? Do we a MULTIARCHS release too ?

- I think we can stick to the production arch only
- we do need MULTIARCHS too (for DAQ/HLT)

Thanks!
Francesco

**Comment by makortel** [comment]
> The changes w.r.t 14.0.7.patch1 are https://github.com/cms-sw/cmssw/compare/CMSSW_14_0_7_patch1...CMSSW_14_0_HLTTest?expand=1 . I can start the build of CMSSW_14_0_7_HLTTest release later today(around 16h00) and can upload it once we have good results from 14.1.X 11h IB. Let me know if all look good for CMSSW_14_0_7_HLTTest branch.

Looks good to me.

**Comment by smuzaffar** [comment]
thanks @makortel . Note that #44978 is backport of #44892 which was integrated in today's 11h 14.1.X IB and one [unit test failed](https://github.com/cms-sw/cmssw/pull/44892#issuecomment-2139443543) . Is it safe to go ahead with CMSSW_14_0_7_HLTTest release ?

**Comment by makortel** [comment]
> Note that #44978 is backport of #44892 which was integrated in today's 11h 14.1.X IB and one [unit test failed](https://github.com/cms-sw/cmssw/pull/44892#issuecomment-2139443543) . 

Given the nature of the test, the failure is expected (https://github.com/cms-sw/cmssw/pull/44892#issuecomment-2139517042). The test itself is brittle and will need an update.

> Is it safe to go ahead with CMSSW_14_0_7_HLTTest release ?

Yes.

Thanks!

**Comment by fwyzard** [comment]
+heterogeneous

**Comment by jfernan2** [comment]
+1

**Comment by perrotta** [comment]
+alca
- As it was [confirmed at the Join Ops meeting of June 10](https://docs.google.com/document/d/1VscH-ZO-E_R1NPP541SBoiK9AL-OcyvALSvnSoyg8Mw/edit), tests of the event meta data changes in streamer files went fine with CMSSW_14_0_7_HLTTest, therefore this workaround can be removed from 14_0_X (this has to be merged together with #44978)

**Comment by rappoccio** [comment]
+1

**Pull request merged**
