### PR TITLE
Cmssw 7 6 x Change the way Sherpa Tar Balls are retrieved

### PR DESCRIPTION
**Pull request by thuer**
Changed the way the SherpaInterface copies the tarballls, now a simple cp is used instead of the frontier fn-fileget

### CODE REVIEW

**Comment by bendavid** [comment]
So the user gives the absolute path now?
/cvmfs/cms.cern.ch/phys_generator/...

**Comment by thuer** [comment]
yes

**Comment by bendavid** [comment]
+1

**Comment by covarell** [comment]
+1

**Comment by covarell** [comment]
We also need this in 80X

**Comment by thuer** [comment]
@covarell that is already done #12462

**Comment by vciulli** [comment]
Will this be backported to 7_1_X too? 
This is the version that is still being used for the GEN-SIM production, right? 

Vitaliano

**Comment by thuer** [comment]
@vciulli  I opened a new pull request for 7_1_X #12837

**Comment by davidlange6** [comment]
I am cleaning up the 76x queue aside from things for analysis workflows. I'm closing this pull request, please make sure the PR is in 80x. Thanks!

**Pull request closed without merging**
