### PR TITLE
Phase2-sim156Z Modify the scripts in Validation/HGCalValidation for all new scenarios

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Modify the scripts in Validation/HGCalValidation for all new scenarios

#### PR validation:

Tested all the modified scripts for the new scenarios

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@nothingface0, @syuvivida, @antoniovagnerini, @tjavaid, @rvenditti Please approve this PR

**Comment by tjavaid** [comment]
please test

- triggering for fresh tests

**Comment by tjavaid** [comment]
+1

**Pull request merged**
