### PR TITLE
adding e-mu btag paths to BTVHLTOfflineSource

### PR DESCRIPTION
**Pull request by HeinerTholen**

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by HeinerTholen** [comment]
Please don't merge just yet, I'm still testing as well.

**Comment by HeinerTholen** [comment]
The PR is tested, please go ahead and merge.

**Comment by HeinerTholen** [comment]
Would it be possible (or: does it make sense?) to backport this PR to CMSSW_10_1_X?

**Comment by fabiocos** [comment]
+1

**Pull request merged**
