### PR TITLE
Modify the track type to allow for L2 muons to pass through

### PR DESCRIPTION
**Pull request by folguera**
Just in case we want to use this feature at some point, we will need to change this fix, in case the innerTrack() is not defined.

### CODE REVIEW

**Comment by silviodonato** [comment]
please test

**Comment by silviodonato** [comment]
+1

**Comment by perrotta** [comment]
In order to have the inlined documentation self-consistent, shouldn't you better rephrase also the description in 
https://github.com/folguera/cmssw/blob/f7be21954f21d34f3134d8bcd9396eeb650515f6/RecoMuon/L3MuonProducer/src/L3MuonCandidateProducerFromMuons.cc#L3
and replace "tracker muons (which are reco::Muons)" with just "reco::Muons" (or whatever else you find appropriate)?

**Comment by perrotta** [comment]
@folguera : this PR is quite simple, and basically ready to be merged.

I think that the only missing thing is to adapt the documentation in the class so that it can correspond to its modified features, as I already pointed out in https://github.com/cms-sw/cmssw/pull/22183#issuecomment-365966693. Otherwise that description is misleading.

Please do so (or  write here why you believe you shouldn't) so that we can proceed.

**Comment by Martin-Grunewald** [comment]
@folguera 
Please address Andrea's comment on this PR!

**Comment by folguera** [comment]
Dear @Martin-Grunewald, @perrotta, sorry for the late response I've missed the email.  I've followed the suggestion by Andrea.

**Comment by perrotta** [comment]
+1
- L3MuonCandidateProducerFromMuons is used by HLT
- The update allows it creating candidates candidates also with muons with no inner track (e.g. STA/L2 muons)
- (With the last commit only one commented out line was modified: I don't expect surprises from the tests)

**Comment by fabiocos** [comment]
Signature by HLT was already provided before the fix in the comment, and integration has been explicitly asked by Martin at the ORP of 2018/02/20

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Comment by Martin-Grunewald** [comment]
+1

**Pull request merged**
