### PR TITLE
Revert "Revert "Default data set for D35""

### PR DESCRIPTION
**Pull request by fabiocos**
Reverts cms-sw/cmssw#26107

Restore the fix by @kpedro88, as the TTbar samples are now available it should work both for PR tests and for IBs

### CODE REVIEW

**Comment by fabiocos** [comment]
please test workflow 27434.0,27434.21,27634.21

**Comment by prebello** [comment]
+1

thank you @fabiocos  @siddhesh86

**Comment by kpedro88** [comment]
+upgrade

**Comment by fabiocos** [comment]
+1

**Pull request merged**
