### PR TITLE
Fixing HLTOffline BTV Validation

### PR DESCRIPTION
**Pull request by andrzejnovak**
and adding some automation, when script needs to be run manually

### CODE REVIEW

**Comment by jfernan2** [comment]
@anovak10 We don't have you identified as DQM developer on:
https://twiki.cern.ch/twiki/bin/viewauth/CMS/DQMContacts#Btag_and_vertexing
Can you please add yourself to the corresponding e-group in the link above?
Thanks

**Comment by anovak10** [comment]
I don't seem to be able to add myself. @defranchis

**Comment by defranchis** [comment]
@jfernan2 I just added @anovak10 to the egroup

**Comment by jfernan2** [comment]
please test
Thanks @defranchis !

**Comment by anovak10** [comment]
bump

**Comment by fabiocos** [comment]
@jfernan2 could you please check and sign in case?

**Comment by jfernan2** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
