### PR TITLE
<Backport of #19585> SUSY VBF trigger monitoring 92X

### PR DESCRIPTION
**Pull request by tankit**

### CODE REVIEW

**Comment by mtosi** [comment]
@cmsbuild, please test

**Comment by dmitrijus** [comment]
This is will probably go into conflict because of TriggerDQMBase.
Please provide a full description. Is this a backport? Does not look like one :(

**Comment by tankit** [comment]
This is the back port of #19585.
Please see another backport: #19561 that has TriggerDQMBase (and METDQM/JetDQM).
Since my codes inherit TriggerDQMBase, please let me know how to make a backport.
What do you mean by providing a full description?

**Comment by tankit** [comment]
Closing this PR because all HLT DQM backports are in #19961

**Pull request closed without merging**
