### PR TITLE
Remove some const-away casts from analysis

### PR DESCRIPTION
**Pull request by makortel**
To clean up static analyzer reports.

Tested in CMSSW_10_4_X_2018-10-25-2300, no changes expected.

### CODE REVIEW

**Comment by makortel** [comment]
So we still have code that has not gone through the style checks?

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
@cmsbuild, please abort

**Comment by makortel** [comment]
Added one case in `PatJetHitFitTranslator.cc` that I missed earlier. Also took the opportunity to remove `catch(...)` from `MuScleFitMuonSelector.cc` that the "CMSSW Code Rules" complained about.

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Pull request merged**
