### PR TITLE
[L1T] DQM bug fix

### PR DESCRIPTION
**Pull request by cecilecaillol**
#### PR description:

Addressing issue https://github.com/cms-sw/cmssw/issues/39100 (bug fixes in L1T Phase-2 DQM)

### CODE REVIEW

**Comment by cecilecaillol** [comment]
please test

**Comment by cecilecaillol** [comment]
+l1

**Comment by emanueleusai** [comment]
+1

**Comment by perrotta** [comment]
+1
- Simple bug fix, it should not internfere with the current attempts at fixing the IB

**Pull request merged**
