### PR TITLE
NanoAOD for MiniAODv2 - part 2, e/gamma (94ANX)

### PR DESCRIPTION
**Pull request by gpetruc**
Second set of NanoAOD updates: e/gamma smearing, Fall17 photon id, LHE particles, b-jet energy regression (https://github.com/cms-sw/cmsdist/pull/3888)
PR to master will also arrive quite soon (integration tests for that are still running)

### CODE REVIEW

**Comment by gpetruc** [comment]
please test

**Comment by gpetruc** [comment]
backport of #22755
(strictly speaking is the other way around, 22755 is a rebase of this to the master, but it doesn't matter)

**Comment by gpetruc** [comment]
ok, updating the nanoAOD unit test and matrix relvals

**Comment by gpetruc** [comment]
please test

**Comment by gpetruc** [comment]
+1

**Comment by arizzi** [comment]
please test with cms-sw/cmsdist#3888

**Comment by gpetruc** [comment]
+1

**Comment by fabiocos** [comment]
please test workflow 1325.6,1325.7,1325.8,1325.9

**Comment by fabiocos** [comment]
+1

back-port of NanoAOD code already integrated in master (+ corresponding new relVal workflows already approved by PdmV)

**Comment by fabiocos** [comment]
merge

**Pull request merged**
