### PR TITLE
Updated soft electron dR cut to better match the jet size

### PR DESCRIPTION
**Pull request by ferencek**
Updating the soft electron dR cut from 0.5 to 0.4 to better match the jet size.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test
we also need a 75X version of this

Also, this feature looks more like an improvement than a normal bugfix. Is it fixing some issue found during 74X validation?

**Comment by ferencek** [comment]
The soft muon and soft electron taggers select leptons in different ways. While muons are selected from the jet constituents, electrons are selected by matching gedGsfElectrons to jets. So the soft muon tagger does not apply an explicit dR requirement but its effective value is 0.4 (ignoring special cases of overlapping jets, etc.). This PR therefore makes the lepton selection more consistent between the two taggers. In terms of the performance, it is expected to get slightly worse for low-pT jets. So this PR probably goes more into the category of bugfixes than performance improvements.

A 75X version will follow.

**Comment by davidlange6** [comment]
@cmsbuild, please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/8581	ce5e5aa
this is the same code change as in https://github.com/cms-sw/cmssw/pull/8588	ce5e5aa
(with tests already available).

From the 75X summary:
changes are as expected: a few less tags in softPFElectronBJetTags due to smaller cone size.
The only downstream effect in monitored objects is in pfCombinedMVABJetTags.

**Comment by davidlange6** [comment]
@cmsbuild, please test

**Comment by davidlange6** [comment]
+1

**Pull request merged**
