### PR TITLE
Concurrently run beginStreams

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

Run all streams concurrently during beginStream transition.

#### PR validation:

This had previously been added to _DEVEL and no problems were seen.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
@makortel ping

**Comment by Dr15Jones** [comment]
please test

**Comment by makortel** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
