### PR TITLE
MET+MHT+b-tag Offline DQM 93X

### PR DESCRIPTION
**Pull request by jmduarte**
93X version of #19508

### CODE REVIEW

**Comment by mtosi** [comment]
in the silvio's google doc I find

HLT_PFMET100_PFMHT100_IDTight_BTagCaloCSV_p7_v*
HLT_PFMET110_PFMHT110_IDTight_BTagCaloCSV_p7_v*
HLT_PFMET120_PFMHT120_IDTight_BTagCaloCSV_p7_v*
HLT_PFMET130_PFMHT130_IDTight_BTagCaloCSV_p7_v*
HLT_PFMET140_PFMHT140_IDTight_BTagCaloCSV_p7_v*
!!!!

can we converge to the name of those trigger paths, please ?

**Comment by jmduarte** [comment]
Yes, sorry, I renamed them as requested by TSG rather late... I asked @silviodonato to rename them in the google doc and the master table in the JIRA ticket:

https://its.cern.ch/jira/browse/CMSHLT-1391

The DQM PR here always refer to the p05 (mistag efficiency) names.

Thanks,

Javier

**Comment by mtosi** [comment]
the config in DQM code has to match the name in the menu, of course
  mia

**Comment by fwyzard** [comment]
The names match the latest menu.
Mia, is there any other pending item ?

**Comment by mtosi** [comment]
i do not think so
+1

**Comment by dmitrijus** [comment]
+1

**Comment by mtosi** [comment]
is this error related to this PR ?

**Comment by jmduarte** [comment]
I don't think so. 

The only error I can find in the logs, e.g. https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-19596/21298/addOnTests/logs/cmsDriver-fastsim1_cmsDriver.py_TTbar_13TeV_TuneCUETP8M1_cfi_--conditions_auto:run2_mc_--fast__-n_100_--eventcontent_AODSIM,DQM_--relval_100000,1000_-s_GEN,SIM,RECOBEFMI.log is:

```
----- Begin Fatal Exception 10-Jul-2017 13:34:20 CEST-----------------------
An exception of category 'FileInPathError' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing ESSource: class=XMLIdealGeometryESSource label='magfield'
Exception Message:
edm::FileInPath unable to find file MagneticField/GeomBuilder/data/MagneticFieldVolumes_1_v7_large.xml anywhere in the search path.
The search path is defined by: CMSSW_SEARCH_PATH
${CMSSW_SEARCH_PATH} is: /build/cmsbld/jenkins-workarea/workspace/ib-any-integration/CMSSW_9_3_X_2017-07-09-2300/src:/build/cmsbld/jenkins-workarea/workspace/ib-any-integration/CMSSW_9_3_X_2017-07-09-2300/external/slc6_amd64_gcc530/data:/cvmfs/cms-ib.cern.ch/nweek-02480/slc6_amd64_gcc530/cms/cmssw-patch/CMSSW_9_3_X_2017-07-09-2300/src:/cvmfs/cms-ib.cern.ch/nweek-02480/slc6_amd64_gcc530/cms/cmssw-patch/CMSSW_9_3_X_2017-07-09-2300/external/slc6_amd64_gcc530/data
Current directory is: /build/cmsbld/jenkins-workarea/workspace/ib-any-integration/CMSSW_9_3_X_2017-07-09-2300/src/addOnTests/fastsim2
----- End Fatal Exception -------------------------------------------------
```

And I can reproduce this error. I guess it has to do with this magnetic field geometry xml file missing in the CMSSW_SEARCH_PATH. And this PR doesn't have anything to do with that...

**Comment by fwyzard** [comment]
@davidlange6 this PR is signed by DQM, and I think all comments have been addressed.

Do you have any objections if I include it in a second "merged" PR to fix the various conflicts ?

**Comment by jmduarte** [comment]
For this PR and #19508, it looks like I have to rename the paths:

HLT_PFMET100_PFMHT100_IDTight_BTagCaloCSV_p05_v*  (Calo 0.7 -> Fake 3.07%)
HLT_PFMET110_PFMHT110_IDTight_BTagCaloCSV_p05_v*  (Calo 0.7 -> Fake 3.07%)
HLT_PFMET120_PFMHT120_IDTight_BTagCaloCSV_p05_v*  (Calo 0.7 -> Fake 3.07%)
HLT_PFMET130_PFMHT130_IDTight_BTagCaloCSV_p05_v* (Calo 0.7 -> Fake 3.07%)
HLT_PFMET140_PFMHT140_IDTight_BTagCaloCSV_p05_v*  (Calo 0.7 -> Fake 3.07%)
->
HLT_BTagCSV_3p1_PFMET100_PFMHT100_IDTight_v*
HLT_BTagCSV_3p1_PFMET110_PFMHT110_IDTight_v*
HLT_BTagCSV_3p1_PFMET120_PFMHT120_IDTight_v*
HLT_BTagCSV_3p1_PFMET130_PFMHT130_IDTight_v*
HLT_BTagCSV_3p1_PFMET140_PFMHT140_IDTight_v*

according to https://its.cern.ch/jira/browse/CMSHLT-1463.

How should I handle it? Change these two PRs?

Thanks,

Javier

**Comment by fwyzard** [comment]
Hi Javier,
please don't update the PR once signed by DQM, or we will never converge.

Can you make a new PR (or just a new branch in your github area) with the renaming on top of the existing PR ?

**Comment by davidlange6** [comment]
hi @jmduarte - did you already make a new PR? If so, close this - if not, please rebase. Thanks

**Comment by davidlange6** [comment]
-1
pending answers

**Comment by jmduarte** [comment]
I am rebasing now

**Comment by jmduarte** [comment]
sorry for the undescriptive commit messages. i cherry picked my previous commits and didn't realize those commit messages would be lost.. in the end, you can see from the comparison, that this PR is only additions to two configuration files.

thanks,

javier

**Comment by davidlange6** [comment]
please test

**Comment by fwyzard** [comment]
tracked by #19142

**Comment by fwyzard** [comment]
@jmduarte , did you take care of renaming the paths already here ?  or is there a separate PR / branch for it ?

**Comment by jmduarte** [comment]
@fwyzard Yes, I renamed the paths already in this PR.

**Comment by dmitrijus** [comment]
+1

**Comment by fwyzard** [comment]
I have merged this in #19916.
Please DO NOT TOUCH this PR/branch, and leave it open.

**Pull request merged**
