### PR TITLE
[NanoAOD] Correct filter name for Run3 Isomu triggers

### PR DESCRIPTION
**Pull request by khaosmos93**
Adding correct filter name for Run 3 IsoMu triggers.

### CODE REVIEW

**Comment by mariadalfonso** [comment]
please test

**Comment by mariadalfonso** [comment]
+xpog

minor change in the size of muon TrigObj
only changes in Run3 as expected

https://gitlab.cern.ch/cms-nanoAOD/nanoAOD-integration/-/issues/170

**Comment by qliphy** [comment]
please abort
seems to be stuck

**Comment by qliphy** [comment]
please test

**Comment by qliphy** [comment]
+1

**Pull request merged**
