### PR TITLE
Phase2-sim156 Update the scripts to enable run on new scenarios of Phase2 geometry

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Update the scripts to enable run on new scenarios of Phase2 geometry

#### PR validation:

Use the script to run validation plots with the new scenarios

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
Fail likely is not connected with this PR:

**Comment by civanch** [comment]
+1

no needs to repeat testing. The problem #44666 is known and will be fixed soon

**Comment by tjavaid** [comment]
+1

**Comment by rappoccio** [comment]
+1

**Comment by rappoccio** [comment]
merge

**Pull request merged**
