### PR TITLE
JME bugfixes

### PR DESCRIPTION
**Pull request by rappoccio**
Several JME bugs fixed here:

- AK8 jets needed rawFactor to reapply jet corrections
- AK4 jets needed muon fraction, addressing [this issue](https://github.com/cms-nanoAOD/cmssw/issues/169)
- Trigger objects needed AK8 jets, addressing [this issue](https://github.com/cms-nanoAOD/cmssw/issues/81)

10.1.x version will be forthcoming next.

### CODE REVIEW

**Comment by fabiocos** [comment]
please test

**Comment by davidlange6** [comment]
Your PR is unmergeable. Please have a look and possibly rebase it.

**Comment by gpetruc** [comment]
I'll include a rebased version of this fix in a new nanoAOD PR today

**Comment by rappoccio** [comment]
Thanks Giovanni, sorry, I'm at boost this week and the wifi is awful.

**Pull request closed without merging**
