### PR TITLE
[DT Emulator] First cleaned version AMv2 with SL2

### PR DESCRIPTION
**Pull request by jfernan2**
#### PR description:

Forward port of https://github.com/cms-l1t-offline/cmssw/pull/1166

This PR integrates the new version (v2) of the Analytical Method for the Phase-2 DT Emulator.

It has been presented in the DT Upgrade (trigger primitives and test systems)[1] and in the Level-1 Muon DPG meeting [2].

Needs data files from PR https://github.com/cms-data/L1Trigger-DTTriggerPhase2/pull/3

Credits of the code to @jaimeleonh [3], SL2 emulation addition from [4] and theta coordinates fix from @mcepeda 

#### PR validation:
The software goes hand by hand with the developments being implemented in the firmware. In links [1] and [2] are presented performance results with the new AMv2 algorithm :

- In simulation with the emulator

- Comparing emulator and firmware in the laboratory

- Similar (or even improved) performance w.r.t. previous AM version (v1, already in CMSSW)

[1] https://indico.cern.ch/event/1262475/contributions/5308462/attachments/2607937/4505149/230309_NewAM_DTUpgrade_JLH.pdf
[2] https://indico.cern.ch/event/1263362/contributions/5305755/attachments/2607489/4504221/230308_NewAM_L1MuonDPG_JLH.pdf

[3] https://github.com/jaimeleonh/cmssw/tree/AM_12_4_2_new_fitter
[4] https://github.com/jfernan2/cmssw/tree/AM_12_4_2_new_fitter_withThetas

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

No backport needed

### CODE REVIEW

**Comment by epalencia** [comment]
Please test with https://github.com/cms-data/L1Trigger-DTTriggerPhase2/pull/3

**Comment by aloeliger** [comment]
@jfernan2 There is an error with an unused variable:
```
L1Trigger/DTTriggerPhase2/src/MuonPathAnalyzerInChamber.cc
/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_14_0_X_2023-11-24-2300/src/L1Trigger/DTTriggerPhase2/src/MuonPathAnalyzerInChamber.cc:720:7: warning: variable 'validHits' set but not used [-Wunused-but-set-variable]
```

**Comment by jfernan2** [comment]
please test with https://github.com/cms-data/L1Trigger-DTTriggerPhase2/pull/3

Last commit and final test

**Comment by jfernan2** [comment]
please abort
Test seems stuck

**Comment by aloeliger** [comment]
+l1
- Already reviewed as part of https://github.com/cms-l1t-offline/cmssw/pull/1166

**Comment by srimanob** [comment]
I just copy the static log check which relate to `L1Trigger/DTTriggerPhase2` here. So you can check and implement in the next PR. I don't think they directly relate to this PR.

```
/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_14_0_X_2023-11-29-2300/src/L1Trigger/DTTriggerPhase2/src/GlobalCoordsObtainer.cc:222:3: warning: Value stored to 'x_msb' is never read [deadcode.DeadStores]
  222 |   x_msb = from_two_comp(x_msb, PHI_LUT_ADDR_WIDTH);
      |   ^       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_14_0_X_2023-11-29-2300/src/L1Trigger/DTTriggerPhase2/src/GlobalCoordsObtainer.cc:225:3: warning: Value stored to 'tanpsi_msb' is never read [deadcode.DeadStores]
  225 |   tanpsi_msb = from_two_comp(tanpsi_msb, PHIB_LUT_ADDR_WIDTH);
      |   ^            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_14_0_X_2023-11-29-2300/src/L1Trigger/DTTriggerPhase2/src/MuonPathAssociator.cc:592:15: warning: Branch condition evaluates to a garbage value [core.uninitialized.Branch]
  592 |           if (useFitSL3[sl3])
      |               ^~~~~~~~~~~~~~
/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_14_0_X_2023-11-29-2300/src/L1Trigger/DTTriggerPhase2/src/MuonPathAssociator.cc:844:19: warning: Branch condition evaluates to a garbage value [core.uninitialized.Branch]
  844 |               if (useFitSL1[sl1])
      |                   ^~~~~~~~~~~~~~
/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_14_0_X_2023-11-29-2300/src/L1Trigger/DTTriggerPhase2/src/MuonPathAssociator.cc:905:19: warning: Branch condition evaluates to a garbage value [core.uninitialized.Branch]
  905 |               if (useFitSL3[sl3])
      |                   ^~~~~~~~~~~~~~
/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_14_0_X_2023-11-29-2300/src/L1Trigger/DTTriggerPhase2/src/MuonPathAssociator.cc:1011:9: warning: Branch condition evaluates to a garbage value [core.uninitialized.Branch]
 1011 |     if (!useFit[i])
      |         ^~~~~~~~~~
/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_14_0_X_2023-11-29-2300/src/L1Trigger/DTTriggerPhase2/src/MuonPathAssociator.cc:1016:11: warning: Branch condition evaluates to a garbage value [core.uninitialized.Branch]
 1016 |       if (!useFit[j])

/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_14_0_X_2023-11-29-2300/src/L1Trigger/DTTriggerPhase2/src/MuonPathAnalyzerInChamber.cc:245:9: warning: cms.NonFiniteMath [cms.NonFiniteMath]
  245 |     if (isnan(jm_x))
      |         ^
1 warning generated.
```

**Comment by jfernan2** [comment]
Thanks @srimanob 
Indeed it is not related to this PR but I will implement a fix for that in the next iteration

**Comment by rappoccio** [comment]
+1

**Pull request merged**
