### PR TITLE
Turn on New Truth Matching

### PR DESCRIPTION
**Pull request by Jingyan95**
#### PR description:

A new MC truth matching is set as our default option, expected consequences are:

-Tracking efficiency goes up by 1.3% 
-Almost no impact on eta, z0 resolution
-Modest impact on phi, pT resolution

This is a relevant talk I gave at L1TK algo meeting:
[https://indico.cern.ch/event/907491/contributions/3827940/attachments/2020524/3378294/AlgoMeeting_April_15.pdf]()

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by rekovic** [comment]
+1

**Comment by skinnari** [comment]
hi @rekovic , @Jingyan95 put this PR in on the request of the L1 tracking group. It is just changing to use as default a better MC truth matching, and has no impact to the tracking / stub finding or similar.

**Comment by civanch** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
