### PR TITLE
New Run3 pileup scenarios for max PU studies

### PR DESCRIPTION
**Pull request by knollejo**
New pileup scenarios for Run3, corresponding to a maximum pileup of 60, 65, and 70 in the hybrid filling scheme. The methodology used for the creation of these scenarios is the same that was used for #34460, now with the available predictions for 2023 conditions (as provided by LHC experts over a year ago), a minimum bias cross section of 80mb, and with the instantaneous luminosity profile scaled to different leveling luminosities. The three scenarios are:
- `2023_LHC_Simulation_14h_10h_hybrid2p05` ("pileup 60")
  - 2440 bunches, initial inst. lumi 2.05e34 Hz/m2, 14h fill with 10h leveling
  - Run3_2023_LHC_Simulation_14h_10h_hybrid2p05
  - actual peak at pileup 59
- `2023_LHC_Simulation_12p5h_9h_hybrid2p23` ("pileup 65")
  - 2440 bunches, initial inst. lumi 2.23e34 Hz/m2, 12.5h fill with 9h leveling
  - Run3_2023_LHC_Simulation_12p5h_9h_hybrid2p23
  - actual peak at pileup 64
- `2023_LHC_Simulation_11h_8h_hybrid2p40` ("pileup 70")
  - 2440 bunches, initial inst. lumi 2.40e34 Hz/m2, 11h fill with 8h leveling
  - Run3_2023_LHC_Simulation_11h_8h_hybrid2p40
  - actual peak at pileup 69

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
@knollejo , please have a look - abnormal end of each file. This may be OK but may be not.

**Comment by missirol** [comment]
> (unless HLT moves the development version to 12_6 as soon as 12_6_0 will become available, likely in the next few days): please @cms-sw/hlt-l2 let us know

@perrotta , HLT-menu development already moved to `12_6_X` (see description of https://github.com/cms-sw/cmssw/pull/40220).

**Comment by knollejo** [comment]
> @knollejo , please have a look - abnormal end of each file. This may be OK but may be not.

Fixed.

**Comment by perrotta** [comment]
@smuzaffar I think bot is stuck: code-checks and tests are stuck in all PRs since some while.

**Comment by smuzaffar** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
