### PR TITLE
Phase2-hgx359T Modify the testing code in Validation/HGCalValidation in view of changes made in the Configuration/Geometry area for Phase2 scenarios

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Modify the testing code in Validation/HGCalValidation in view of changes made in the Configuration/Geometry area for Phase2 scenarios

#### PR validation:

Tested the changed scripts

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@antoniovagnerini, @nothingface0, @rvenditti, @syuvivida, @tjavaid Please approve this PR

**Comment by tjavaid** [comment]
+1

**Pull request merged**
