### PR TITLE
L1TCalo: Add new caloParams with updated HI centrality v1_4_1

### PR DESCRIPTION
**Pull request by bundocka**
New centrality tuning.

### CODE REVIEW

**Comment by bundocka** [comment]
I've just added a new offline config with updated HI parameters. Nothing in the standard WFs should be affected.

**Comment by thomreis** [comment]
Those configs have been tested locally then?

**Comment by bundocka** [comment]
Yes, I didn't see any problems

**Comment by thomreis** [comment]
+1

**Comment by fabiocos** [comment]
@bundocka @thomreis for my understanding, where is this new customise used? In the release out of the box nowhere I would say...

**Comment by fabiocos** [comment]
@bundocka @thomreis could you please clarify? I assume this is needed in production

**Comment by fabiocos** [comment]
@rekovic @bundocka @thomreis could you please clarify? I assume this is needed in production

**Comment by bundocka** [comment]
Hi, 
This customisation isn't used in any central workflows, but provides the latest HI centrality classes that are used online. This would only be used to configure the emulator manually.

**Comment by fabiocos** [comment]
@bundocka ok thanks

**Comment by fabiocos** [comment]
+1

**Pull request merged**
