### PR TITLE
[13_0_X] lhcInfo split: per fill and per LS PopCon

### PR DESCRIPTION
**Pull request by JanChyczynski**
#### PR description:

Backport of #40817 

Adding the PopCon scripts and plugins to populate the `LHCInfoPerLS` and `LHCInfoPerFill` records. Includes the unit test for the new PopCons.

#### PR validation:

See master PR for validation description

#### Backport

Backport of #40817

### CODE REVIEW

**Comment by francescobrivio** [comment]
backport of #40817

**Comment by francescobrivio** [comment]
@cmsbuild please test

 - eventually need a new 13_0_X for putting in production the new LHCInfo O2Os

**Comment by francescobrivio** [comment]
@cmsbuild please test

 - timed out relvals are not critical, but we have time to re-try them since this PR is not super critical

**Comment by francescobrivio** [comment]
+1

 - tests clean

**Comment by rappoccio** [comment]
We also need a CMSSW_13_1_X branch of this, please.

**Comment by francescobrivio** [comment]
> We also need a CMSSW_13_1_X branch of this, please.

Hi Sal, the master PR https://github.com/cms-sw/cmssw/pull/40817 is already in 13_1_X, but back in that time we did not made a 13_0_X backpor, which we now realized we need.

**Comment by perrotta** [comment]
+1

**Pull request merged**
