### PR TITLE
DetUnitContainer and GeomDetUnit Cleanup

### PR DESCRIPTION
**Pull request by ianna**
* Replace DetUnitContainer with DetContainer since GeomDet is used to define GeomDetUnit
* Apply code checks to modified files

@slava77 - FYI, TrackingGeometry cleanup has been presented here:
https://indico.cern.ch/event/648883/contributions/2638075/attachments/1486221/2308006/Geometry_Reco_Development_2017.pdf

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Comment by ianna** [comment]
@slava77 - please, have a look asap

**Comment by slava77** [comment]
On 9/25/17 11:08 AM, Ianna Osborne wrote:
> @slava77 <https://github.com/slava77> - please, have a look asap

please explain the urgency.
IMHO, this can wait for 95X to open.

**Comment by ianna** [comment]
@slava77 - this is required for the next step - move to smart pointers. It is confusing to have both container types and some fill both with the same content. I prefer to break changes in smaller manageable parts rather then bundle it all together.

**Comment by perrotta** [comment]
+1
- It does what it says: replace DetUnitContainer -> DetContainer and GeomDetUnit -> GeomDet everywhere, thus removing redundant code (GeomDetUnit is aliased to GeomDet in https://cmssdt.cern.ch/lxr/source/Geometry/CommonDetUnit/interface/GeomDet.h#0168)
- No effect on jenkins outputs, as it should
- (reco only touched in two test analyzers)

**Comment by arunhep** [comment]
+1

**Comment by davidlange6** [comment]
merge

**Pull request merged**
