### PR TITLE
Advanced configuration of Geant4 simulation

### PR DESCRIPTION
**Pull request by civanch**
#### PR description:
Several improvements for Geant4 simulation were prepared but not enabled in 12_5 in order do not disturb 2022 GEN SIM production. In this PR following modifications proposed:
1) gamma general process enabled
2) CMSTDormandPrince45 stepper in magnetic field is used (reduced number of calls to the sqrt with the same argument)
3) Tracking cut for charged particles increased from 1 keV to 25 keV, which is below lowest production threshold for delta-electrons

These modifications change simulation histories, so the regression is not expected. CPU should be improved (~5% for ttbar). 

#### PR validation:
there was PdmV campaign to check the general gamma process, which was approved. Other modifications were validated privately

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

Regression is not expected in this PR. Validation was partially (for gamma general) done previously, remaining validation may be at the next pre-release.

**Comment by perrotta** [comment]
+1

**Pull request merged**
