### PR TITLE
Make using ROOT's ImplicitMT the default

### PR DESCRIPTION
**Pull request by Dr15Jones**
Switch to turning on ROOT's implicit MT by default.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
@bbockelm thought you'd be interested.

**Comment by Dr15Jones** [comment]
@dan131riley found that using `ROOT::EnableImplicitMT()` improved event throughput for AOD and miniAOD writing.

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by davidlange6** [comment]
merge

**Pull request merged**
