### PR TITLE
fix missing leftover Timing parameter in fed_dqm_sourceclient-live_cfg.py

### LINKED ISSUE #33623: TestDQMOnlineClient-fed_dqm_sourceclient test fails
TestDQMOnlineClient-fed_dqm_sourceclient test fails in CMSSW_12_0_X_2021-05-04-1100
```
edmFileUtil --catalog file:/cvmfs/cms-ib.cern.ch/SITECONF/local/PhEDEx/storage.xml?protocol=xrootd --events /store/express/Commissioning2019/ExpressCosmics/FEVT/Express-v1/000/334/393/00000/FE21789A-F777-0B43-A1F5-E43F1FD52D19.root | tail -n +9 | head -n -5 | awk '{ print $3 }'
Got 2 files.
----- Begin Fatal Exception 04-May-2021 16:07:58 CEST-----------------------
An exception of category 'ConfigFileReadError' occurred while
   [0] Processing the python configuration file named ./src/DQM/Integration/python/clients/fed_dqm_sourceclient-live_cfg.py
Exception Message:
 unknown python problem occurred.
TypeError: Timing does not already exist, so it can only be set to a CMS python configuration type

At:
  /cvmfs/cms-ib.cern.ch/nweek-02679/slc7_amd64_gcc900/cms/cmssw/CMSSW_12_0_X_2021-05-04-1100/python/FWCore/ParameterSet/Mixins.py(300): __raiseBadSetAttr
  /cvmfs/cms-ib.cern.ch/nweek-02679/slc7_amd64_gcc900/cms/cmssw/CMSSW_12_0_X_2021-05-04-1100/python/FWCore/ParameterSet/Mixins.py(245): __addParameter
  /cvmfs/cms-ib.cern.ch/nweek-02679/slc7_amd64_gcc900/cms/cmssw/CMSSW_12_0_X_2021-05-04-1100/python/FWCore/ParameterSet/Mixins.py(277): __setattr__
  ./src/DQM/Integration/python/clients/fed_dqm_sourceclient-live_cfg.py(51): <module>

----- End Fatal Exception -------------------------------------------------

---> test TestDQMOnlineClient-fed_dqm_sourceclient had ERRORS
```
https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc900/CMSSW_12_0_X_2021-05-04-1100/unitTestLogs/DQM/Integration#/

### PR DESCRIPTION
**Pull request by mmusich**
resolves https://github.com/cms-sw/cmssw/issues/33623

#### PR description:

Title says it all 

#### PR validation:

Tested with:

```
cd DQM/Integration/python/clients
mkdir upload
voms-proxy-init -voms cms
cmsRun fed_dqm_sourceclient-live_cfg.py
```

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Not a backport, no backport needed

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
Thanks for the fast reaction @mmusich , as usual!

**Comment by qliphy** [comment]
type bugfix

**Comment by jfernan2** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
