### PR TITLE
HcalDQM: Add FED integrity module, backport to 12_4_X

### PR DESCRIPTION
**Pull request by lwang046**
PR description:

Add HCAL FED integrity monitoring module, backport of PR #38387 to 12_4_X upon [request](https://github.com/cms-sw/cmssw/pull/38387#issuecomment-1165254635).

PR validation:

Testes and verified with actual data from recent Run#352567

### CODE REVIEW

**Comment by emanueleusai** [comment]
type ecal

**Comment by emanueleusai** [comment]
type hcal

**Comment by emanueleusai** [comment]
please test

**Comment by emanueleusai** [comment]
backport of #38387

**Comment by emanueleusai** [comment]
type feature

**Comment by emanueleusai** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
