### PR TITLE
Phase2-hgx274 Use constexpr rather than const in Geometry/HGCalCommonData

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Use constexpr rather than const in Geometry/HGCalCommonData

#### PR validation:

Use the runTheMatrix test workflows 

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

**Comment by qliphy** [comment]
+1

**Pull request merged**
