### PR TITLE
Run2-alca104 Make changes for Hcal Calibration with MIPS

### PR DESCRIPTION
**Pull request by bsunanda**
Add a propagation tool so that one can go to the beginning and end of a given Hcal tower whose extension is provided
The offline analyzer code is extensively revised for computing pileup correction

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by lpernie** [comment]
Could You add a description?
It is mostly to propagate tracks to HCAL?

**Comment by bsunanda** [comment]
@lpernie Made some comment

**Comment by lpernie** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
