### PR TITLE
[93X backport of PR20723] Make muon HLT (L3/TkMu) work in phaseII scenarios

### PR DESCRIPTION
**Pull request by battibass**
This PR (backport of [PR 20723](https://github.com/cms-sw/cmssw/pull/20723)):
- makes `TSGForOI` work in Phase2  (as done for offline the outside-in muon iteration in [PR 18553](https://github.com/cms-sw/cmssw/pull/18553))
- fixes a small initilaization issue in `MaskedMeasurementTrackerEventProducer`

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by slava77** [comment]
backport of #20723

**Comment by slava77** [comment]
assign upgrade

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/20724	42e27ec
- updates to make TSGForOI used in HLT to work in phase2; the backport of #20723 looks correct
- jenkins tests pass

This is supposedly needed for HLT developments in phase 2 workflows in connection with EC TDR production.

**Comment by kpedro88** [comment]
+1

**Comment by davidlange6** [comment]
merge

**Pull request merged**
