### PR TITLE
Add two more PV variables requested by H->gammagamma conveners

### PR DESCRIPTION
**Pull request by JunquanTao**
#### PR description:

This PR is to add the PV sum_px and sum_py of pf charged particles associated to PV in NanoAOD, as suggested by Hgg conveners @lfinco , @fcouderc , for the vertex probability estimator.

Since 2 variables (float type) for each event are proposed to add, the expected additional size in nanoAOD will be 2-3 bytes per event, depending on the precision to store this variable (8 or 10 bits). By default we propose to store it in the precision with 10 bits.

#### PR validation:

runTheMatrix tests have been successfully run for the following workflow :
• runTheMatrix.py -l 12434.0

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

We target this to go in the next nano production, V14 .

### CODE REVIEW

**Comment by hqucms** [comment]
@JunquanTao Please add the new variables to [nanoDQM](https://github.com/cms-sw/cmssw/blob/85c8117751a37223e789fa5849903e548e10b859/PhysicsTools/NanoAOD/python/nanoDQM_cfi.py#L617).

**Comment by hqucms** [comment]
enable nano

**Comment by hqucms** [comment]
please test

**Comment by hqucms** [comment]
@JunquanTao Please make a backport to 14_0_X for Nano V14 production.

**Comment by JunquanTao** [comment]
> @JunquanTao Please make a backport to 14_0_X for Nano V14 production.

@hqucms Should I submit a new PR with CMSSW 14_0_X?

**Comment by hqucms** [comment]
> > @JunquanTao Please make a backport to 14_0_X for Nano V14 production.
> 
> @hqucms Should I submit a new PR with CMSSW 14_0_X?

@JunquanTao Yes please do. Thanks a lot!

**Comment by rappoccio** [comment]
+

**Comment by rappoccio** [comment]
+1

**Comment by JunquanTao** [comment]
> > > @JunquanTao Please make a backport to 14_0_X for Nano V14 production.
> > 
> > 
> > @hqucms Should I submit a new PR with CMSSW 14_0_X?
> 
> @JunquanTao Yes please do. Thanks a lot!

@hqucms  Please review it: https://github.com/cms-sw/cmssw/pull/44325

**Pull request merged**
