### PR TITLE
Update condformat serialization script to use python3

### PR DESCRIPTION
**Pull request by smuzaffar**
This is needed by cms-sw/cmsdist#7095 but can be merged before cmsdist update.

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
test parameters:
- addpkg = CondFormats,CondCore,CommonTools

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
please test

**Comment by ggovi** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
