### PR TITLE
Add header guard EventSelectors.h

### PR DESCRIPTION
**Pull request by Teemperor**
This file looks like a normal header but has no header guard,
so let's add them.

### CODE REVIEW

**Comment by Teemperor** [comment]
Part of the work going on regarding the C++ modules migration of CMSSW (tracked as issue https://github.com/cms-sw/cmssw/issues/15248). This PR is not meant to refactor things, but just to make these headers compile.

**Comment by Teemperor** [comment]
The header guards are implemented in this non-traditional way because the other headers in this directory are doing the same, just to be consistent.

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
Your PR is unmergeable. Please have a look and possibly rebase it.

**Pull request closed without merging**
