### PR TITLE
GEM TnP efficiency plots with bad VFAT masking and Etapartition-wise measurements

### PR DESCRIPTION
**Pull request by jo100sun**
PR description:
Bad VFAT masking is needed to measure efficiency of properly-working chambers. Plots generates respectively for status flag of each component of GEM. Contribution of each component for efficiency loss can be figured out.

Etapartition-wise measurements plots efficiency of separate etapartition device. We changed matching objective of TrackerMuons from GEM chamber to GEM etapartition. Muon can be matched to more than one etapartition in a single chamber if the muon passes boundary between etapartitions.

Changes:
Status-wise efficiency measurement : Components of GEM chamber has status tag which tells functionality of individual object. For those plots added, only the hits living in components which doesn't include error or warning tag of interest.
Currently we have OH error, OH missing, VFAT error 

Etapartion-wise efficiency : Each GE11 chamber consists of 8 etapartition module, which has 3 VFAT readout chips for each. By replacing propagation of TrackerMuons to each etapartition from each chamber, we can measure efficiency of each etapartition. If one or more VFAT is bad for certain hit, it is not joining measurement of bad VFAT masked efficiency.
Station Separation: GE11 and GE21 were overlapping on certain plots. These plots have been separated for each station for clarity.

PR validation:
Validation was performed using the command `runTheMatrix.py -l limited -i all --ibeos`. We verified that the plots after the PR reflect all the changes listed above.

### CODE REVIEW

**Comment by jo100sun** [comment]
please test

**Comment by tjavaid** [comment]
please test

**Comment by jo100sun** [comment]
@jshlee @watson-ij

**Comment by jo100sun** [comment]
please test

**Comment by tjavaid** [comment]
please test

**Comment by mandrenguyen** [comment]
This PR appears to change the `type()` of `recoMuons`:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_14_1_X_2024-08-11-0000+c67be8/63960/validateJR/13034.0_TTbar_14TeV+2024PU/all_RECO_step3/c_recoMuons_muons__RECO_obj_type.png
Was that your expectation?  It wasn't clear to me from the PR description.

**Comment by watson-ij** [comment]
Hi @mandrenguyen, we are changing slightly the matching to GEM (from chamber to eta partition), so there could be some difference in GEMMuon since the total eta partition area can be slightly smaller than the full chamber. However, I would have expected this to be a tiny effect, and not noticeable at this testing scale. @jo100sun is looking into this now.

**Comment by watson-ij** [comment]
please test

**Comment by mandrenguyen** [comment]
+reconstruction

**Comment by tjavaid** [comment]
@jo100sun , I see the new plots; however, those are empty for all WFs (e.g. [see plots](https://tinyurl.com/23wanuyy) for `WF 140.023`). Also, do you expect [these changes](https://tinyurl.com/26yuxobs) ?

**Comment by watson-ij** [comment]
Hi @tjavaid the empty plots are because these data don't produce Z bosons to be used. For the changes you pointed out, we understand where they come from (multiple eta partitions generating extra hits). We are now discussing in the GEM DPG how we want to handle this issue, thank you for pointing these plots out.

**Comment by antoniovilela** [comment]
ping (to make bot change milestone)

**Comment by watson-ij** [comment]
+commit-count

**Comment by watson-ij** [comment]
I guess I can only tests

**Comment by jo100sun** [comment]
To do Etapartition-wise efficiency measurements, we'd changed Trackermuon to propagates to surface of etapartition instead of chamber (To find etapartition number of the Trackermuon) .
 Trackermuon matches to the detector (chambermatch) as long as distance from its surface stays within a cut (5cm default). So matching region is bigger than the real detector surface and it overlaps with other chambers within same plane.
Therefore two or more matches of different surfaces (on the same plane, but different chamber) can be matched to a muon passing those overlapping region. As we changed chamber surface to etapartition surface, overlapping region for has changed. This is the reason why we've seen change in nNumChambers.  
 This is unintended behavior, so we're now including etapartition finding in DQM process. With the new code, there's no any change in propagation side.

**Comment by tjavaid** [comment]
please test

**Comment by tjavaid** [comment]
+1

- several spurious differences seen from unstable WF `12834.7` (open issue #39803 )
- @jo100sun , milestone for this PR was changed to `CMSSW_14_2_X`. Do you plan to open a backport PR to `CMSSW_14_1_X` (and `CMSSW_14_0_X`) ?

**Comment by mandrenguyen** [comment]
+1

**Comment by jo100sun** [comment]
@tjavaid Yes we want to open backport PR.

**Pull request merged**
