### PR TITLE
move away from boost::uint and boost::int in favor of C++11 classes

### PR DESCRIPTION
**Pull request by davidlange6**
#### PR description:

removed usage of boost::uint<8,16,32,64>_t in favor of uint<8,16,32,64>_t
removed usage of boost::int<8,16,32,64>_t in favor of int<8,16,32,64>_t
removed include boost/cstdint.hpp and added include cstdint in an file modified. 

Many other CMSSW files should also include <cstdint> based on their existing usage of these types.  Fixing that is not a part of this pull request

#### PR validation:

compiles and runs tests in runTheMatrix - should be transparent.

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by fabiocos** [comment]
@davidlange6 @Dr15Jones in order to avoid troubles such a PR should enter quickly given that it should be purely technical and transparent. In my understanding the change in DataFormats and CondFormats (@ggovi please check) should be transparent, as the type definition is the same.

Browsing the changes I see:

- in some cases clang-format seems to format some code (@smuzaffar not sure whether it was initially left out or an effect of latest update);

- in several cases the boost implementation of cstdint is not replaced by the standard one: @davidlange6 this is because you found it was redundant and not needed?

**Comment by davidlange6** [comment]
> On Sep 24, 2019, at 3:24 PM, Fabio Cossutti <notifications@github.com> wrote:
> 
> @davidlange6 @Dr15Jones in order to avoid troubles such a PR should enter quickly given that it should be purely technical and transparent. In my understanding the change in DataFormats and CondFormats (@ggovi please check) should be transparent, as the type definition is the same.
> 
> Browsing the changes I see:
> 
> 	• in some cases clang-format seems to format some code (@smuzaffar not sure whether it was initially left out or an effect of latest update);
> 
> 	• in several cases the boost implementation of cstdint is not replaced by the standard one: @davidlange6 this is because you found it was redundant and not needed?

Yes - if uint_t* or init_t* are not used, then I didn't add the include...

**Comment by Dr15Jones** [comment]
+1
For DataFormats/Common and FWCore/Framework

**Comment by ianna** [comment]
+1 
for Geometry/EcalCommonData

**Comment by mommsen** [comment]
+1

**Comment by Martin-Grunewald** [comment]
+1

**Comment by jfernan2** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by perrotta** [comment]
+1
- Technical
- Changes in reco-related classes correspond to what declared in the PR description
- Jenkins tests pass

**Comment by fabiocos** [comment]
@ggovi @christopheralanwest @rekovic @kpedro88 @pohsun @santocch please check, I will merge this RP for the next IB

**Comment by tlampen** [comment]
+1

**Comment by santocch** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade
thanks @davidlange6 !

**Comment by fabiocos** [comment]
+1

@ggovi @rekovic please check and possibly comment

**Comment by fabiocos** [comment]
merge

**Pull request merged**
