### PR TITLE
Move eta phi region from reco egamma to math

### PR DESCRIPTION
**Pull request by perrotta**
In a discussion started in https://hypernews.cern.ch/HyperNews/CMS/get/recoDevelopment/1576.html @fwyzard noticed that there was an unwanted remaining dependence of Geometry on Reco.

The ```RecoEcal/EgammaCoreTools/interface/EcalEtaPhiRegion.h``` was not specific for reco, and not even strictly to ECAL, as it just provides a method to verify whether a given (eta,phi) direction is inside a given rectangular region in the eta,phi plane.

The idea was therefore to move the class into ```DataFormats/Math```, where there are already other similar classes, and rename it more generically and without any reference to ECAL. The name "EtaPhiRegion" was already taken by a struct defined in ```RecoEgamma/EgammaHLTProducers/interface/HLTCaloObjInRegionsProducer.h```. Therefore, in order to avoid possible duplicates, I opted to "RectangularEtaPhiRegion".

Comments about the name and the position of the moved package are welcome.

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by ianna** [comment]
+1

**Comment by Martin-Grunewald** [comment]
+1

**Comment by arunhep** [comment]
+1

**Comment by perrotta** [comment]
@argiro : do you see any possible issue for ECAL DPG because of this PR?

**Comment by perrotta** [comment]
Let me also add EGamma contacts here: @Sam-Harper @jainshilpi @varuns23 
If nobody complains, by next week I will sign this for reco

**Comment by perrotta** [comment]
+1
- (No complains arrived from ECal or EGamma)
- Remove unwanted remaining dependence of Geometry on Reco by moving EcalEtaPhiRegion from RecoEcal/EgammaCoreTools to DataFormats/Math
   - Since the method is general enough, the reference to "Ecal" is dropped from its name
   - All dependencies in CMSSW are updated accordingly

**Comment by fabiocos** [comment]
+1

**Pull request merged**
