### PR TITLE
Remove empty plots from HLT DQM in Express

### PR DESCRIPTION
**Pull request by fioriNTU**
This PR delete a bunch of empty files in Express DQM. In particular removes the Pixel, Strip and Tracking plots which are not filled in Express.

### CODE REVIEW

**Comment by fioriNTU** [comment]
@jfernan2 and @fabiocos this PR only removes Tracker DQM sequences from HLT, all other plots are unchanged

**Comment by jfernan2** [comment]
Hi @fioriNTU I am not sure why DQMHistosizes is increased for HLT/EXO, HLT/EGM and HLT/Vertexing folders if we are only removing histograms with this PR

**Comment by fioriNTU** [comment]
@jfernan2 I noticed myself, it can be something different in the tested IB, for sure I am not adding histograms

**Comment by jfernan2** [comment]
@fioriNTU but your changes involve creating a new sequence which uses:
BTVHLTOfflineSource *
+  trackingMonitorHLTDisplacedJet* #DisplacedJet Tracking
+    egmTrackingMonitorHLT * # egm tracking
+    vertexingMonitorHLT

So at least EGM and Vertexing folders are touched, right? Not sure about where EXO may be coming from...

**Comment by mtosi** [comment]
`trackingMonitorHLTDisplacedJet*`

**Comment by jfernan2** [comment]
@mtosi So changes in EXO are expected from that module you quote I understand from your comment. Is HLT happy with this PR anyway? Thanks

**Comment by fioriNTU** [comment]
@jfernan2 and @mtosi I am only replacing this sequence https://github.com/cms-sw/cmssw/pull/23735/files#diff-40066f7f8423517dcab6c4358f9cac62R186 with the same excluding trackingMonitorHLT, sistripMonitorHLTsequence and sipixelMonitorHLTsequence. All the others modules are present also in the old sequence. Is it possible that the IB used for the test already contained my previous PR? In this case I would expect changes in POG monitoring at HLT

**Comment by mtosi** [comment]
if it applies only to Express (and not to HLTMonitor PD) +1
thanks

**Comment by mtosi** [comment]
sequence
https://github.com/fioriNTU/cmssw/blob/fcb324a2b77a868e25be3f6f02ed44999ffb8d2c/DQMOffline/Trigger/python/DQMOffline_Trigger_cff.py#L185
--as it is written in the comment-- is meant to be run on HLTMonitor PD

on Express we should run either the sequence used in "standard" PDs processed in PromptReco
or a new sequence meant to be run *only* on Express PD

since your PR seems to go towards the latter,
I would then suggest to
1. make sure the HLTMonitor PD makes use of sequence defined in the https://github.com/fioriNTU/cmssw/blob/fcb324a2b77a868e25be3f6f02ed44999ffb8d2c/DQMOffline/Trigger/python/DQMOffline_Trigger_cff.py#185
2. change the name of your new sequence in order to highlight its goal (be run on Express)

thanks

**Comment by fioriNTU** [comment]
@mtosi hltMon should not be touched, it will use the complete sequence:

https://github.com/fioriNTU/cmssw/blob/fcb324a2b77a868e25be3f6f02ed44999ffb8d2c/DQMOffline/Configuration/python/autoDQM.py#L49

for the name of the sequence itself, I would keep it like this, because effectively that sequence is the "standard" minus the Tracker stuff.

**Comment by fioriNTU** [comment]
@jfernan2 @fabiocos @mtosi what is the decision on this? I still believe this sequence will remove only empty plots.

**Comment by jfernan2** [comment]
@fioriNTU, Mia is not convinced, can we discuss this on Tuesday DQM meeting?

**Comment by fioriNTU** [comment]
@jfernan2 ok no problem, I will be connected.

**Comment by fioriNTU** [comment]
We understood this is not the right way to go, I close.

**Pull request closed without merging**
