### PR TITLE
Hcal qie extension only cond formats

### PR DESCRIPTION
**Pull request by clemencia**
update only CondFormats part of PR #7569

### CODE REVIEW

**Comment by clemencia** [comment]
update only CondFormats part of PR #7569

**Comment by abdoulline** [comment]
Looks to me (from runTheMatrix) it's 74X Offline DB issue, not really the PR one...

**Comment by abdoulline** [comment]
May we have the tests got re-run? 

In the most recent CMSSW_7_4_X_2015-02-16-1400  
I have runTheMatrix (--useInput all) passed with this PR:
10 10 9 7 6 tests passed, 0 0 0 0 0 failed

**Comment by davidlange6** [comment]
closing in 74x - there is the same PR open in 75x (now the development release)

**Pull request closed without merging**
