### PR TITLE
HCAL MC: adding pulse shape 208 for signal reconstruction

### PR DESCRIPTION
**Pull request by yihui-lai**
#### PR description:

- added pulse Shape 208, it is a resulting pulse from phase scan of MC Digi of Shape 206.

#### Link to related slides: 

  - https://indico.cern.ch/event/936151/#110-mc-hbhe-signal-shape-time
  - https://indico.cern.ch/event/935592/#3-mc-hbhe-signal-shape-time-sc
  - https://indico.cern.ch/event/943042/#5-mc-hbhe-signal-shape-time-sc
  - https://indico.cern.ch/event/943042/#6-2021-mcreco-with-pulse-shape

#### PR validation:

Code compiles.

### CODE REVIEW

**Comment by pohsun** [comment]
please test

**Comment by abdoulline** [comment]
@yihui-lai   could you edit the PR title this (more self-explanatory) way: "HCAL MC: adding reco pulse shape 208"?

**Comment by christopheralanwest** [comment]
Is an update to `HcalMCParams` and/or `HcalRecoParams` planned to enable this change?

**Comment by civanch** [comment]
+1

**Comment by abdoulline** [comment]
@christopheralanwest  yes, HcalRecoParams for Run3 MC, once this PR is merged.

**Comment by pohsun** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
