### PR TITLE
Run3-gex143 Update RecoEgamma/EgammaElectronProducers to avoid compilation warnings

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Update RecoEgamma/EgammaElectronProducers to avoid compilation warnings

#### PR validation:

Use the runTheMatrix test workflows

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by mandrenguyen** [comment]
+1

**Comment by perrotta** [comment]
@bsunanda please rebase, giving the conflicts

**Comment by rappoccio** [comment]
@bsunanda ping for the rebase :)

**Comment by perrotta** [comment]
-1
- Just to keep this PR out of our radars until a proper rebase is applied

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by mandrenguyen** [comment]
+1
Code cleanup, no reco changes

**Comment by rappoccio** [comment]
+1

technical PR

**Pull request merged**
