### PR TITLE
Pixel Digitizer: Cluster charge re-weighting for 10_1_X

### PR DESCRIPTION
**Pull request by schuetzepaul**
Pixel Digitizer for simulated data:

The possibility to apply a re-weighting to the charge was added for a proper modelling of radiation damage in the silicon sensors. The re-weighting is based on the 2D cluster templates for the Phase 1 Pixel Detector introduced in #22458 and therefore dependent on this PR. However, the diff from this PR to #22458 is only in the digitizer part.

The newly added code is _by default turned off_, a flag in the configuration is needed to run it. Therefore the changes in the digitizer are fully backwards compatible.
We still open a PR for the upcoming release in order to simplify the testing and future development of the re-weighting.

For running the new code, the following lines serve as an example:
```
from SimGeneral.MixingModule.pixelDigitizer_cfi import *
process.mix.digitizers.pixel.UseTemplateAgeing = cms.bool(True)

process.mix.digitizers.pixel.TemplateIDnumerator = cms.int32(3002)
process.mix.digitizers.pixel.TemplateIDdenominator = cms.int32(2403)

process.GlobalTag.toGet = cms.VPSet (
    cms.PSet(record = cms.string('SiPixel2DTemplateDBObjectRcd'),
             label = cms.untracked.string("numerator"),
             tag = cms.string('SiPixel2DTemplateDBObject_phase1_38T_2017_rereco_v9_num_largeangles'),
             connect = cms.string('frontier://FrontierPrep/CMS_CONDITIONS')
             ),
    cms.PSet(record = cms.string('SiPixel2DTemplateDBObjectRcd'),
             label = cms.untracked.string("denominator"),
             tag = cms.string('SiPixel2DTemplateDBObject_phase1_38T_mc_v3_den_unirradiated_largeangles'),
             connect = cms.string('frontier://FrontierPrep/CMS_CONDITIONS')
             )
    )
```

The IDs (3002 / 2403) as well as the tags for the db objects are changeable, but the code was tested with those.

Here is a quick note on the concept and plots with tests in the current status: https://desycloud.desy.de/index.php/s/63lG4vCeMNf7XaE

### CODE REVIEW

**Comment by schuetzepaul** [comment]
With this code being built on top of PR #22458 I'm adding an additional bugfix from there, made by @pmaksim1 .

**Comment by civanch** [comment]
please test

**Comment by makortel** [comment]
Even if the code is more for testing, let me ask how should this feature to be (eventually) taken into account for premixing (namely stage1 vs. stage2)? IIUC the current implementation gets applied in stage1, but to me the feature sounds like it should go to stage2 (but I could be wrong)

**Comment by schuetzepaul** [comment]
@makortel 
I'm not entirely sure whether I can answer this question to full satisfaction, since I'm not too familiar with the terminologies of stage1 and stage2, but let me can explain where the re-weighting sets in:
The re-weighting is applied inside the `accumulatePixelHits`/`accumulateSimHits` methods, more precisely during `induce_signal`. So this is before any digitization happens. This is necessary, since it's an effect of the sensor, not of the digitization or the readout chip. Hence they can and should be accumulated. Furthermore there are no thresholds applied to the charges during the re-weighting - this should only happen at the digitization step, which comes with the `finalizeEvent` call.
Does this help?

**Comment by slava77** [comment]
@schuetzepaul @pmaksim1 
would it be practical for you to have the review moved to this PR and close #22458 as superseded?

If not, I'm going to ignore this PR until the review of #22458 is done and it is merged.

**Comment by pmaksim1** [comment]
@slava77  You should do whatever is the easiest for you guys and the most expedient.  I have no strong feelings, as long as both PR get integrated as soon as you think they are ready.

**Comment by pmaksim1** [comment]
I don't know how this is handled, but I presume that the this PR then subsumes #22458 (that is, code from both PRs in integrated, even though we formally close #22458).

**Comment by makortel** [comment]
@schuetzepaul Thanks for the explanation. Then, I believe, in premixing this development goes correctly in stage1 as it is and we don't need to do anything else with that respect. (for more details on premixing see https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideSimulation#Pre_Mixing_Documentation)

(@mdhildreth @kpedro88 )

**Comment by schuetzepaul** [comment]
@makortel Ok, good to hear.

@slava77 I agree with @pmaksim1 . We were opening the two PRs since it is apparently two separate features being added, but with overlap in the code. So yes, do as it works best for you.

**Comment by schuetzepaul** [comment]
@perrotta I'm having troubles doing the rebase. Is opening a new PR also an option?

**Comment by perrotta** [comment]
@schuetzepaul : perfectly fine with me, and probably faster.
If I am not wrong you only need to include in the PR the three files in ```SimTracker/SiPixelDigitizer/plugins```, and none of the reco ones: correct?

**Comment by schuetzepaul** [comment]
Yes, that's correct.

**Comment by schuetzepaul** [comment]
@perrotta Correction: I had to fix one bug in the template definition, hence in the reco folder. The new PR is opened, hence we can close this one and move the discussion to #22911

**Comment by perrotta** [comment]
Ok, I will also look at your new PR, then...
@schuetzepaul please close this PR, as this is up to you

**Pull request closed without merging**
