### PR TITLE
[14_1] Add L1TCaloLayer1Summary and necessary changes to emulator

### PR DESCRIPTION
**Pull request by max-zhao0**
#### PR description:

Backport of [45605](https://github.com/cms-sw/cmssw/pull/45605) for use on online release.

#### PR validation:

Validated locally on CMSSW_14_1_0_pre5, running DQM/Integration/python/clients/l1tstage2_dqm_sourceclient-live_cfg.py modified for testing on lxplus. Also validated for online running in online DQM playback test.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport of [45605](https://github.com/cms-sw/cmssw/pull/45605). Backporting is necessary for running on online release.

### CODE REVIEW

**Comment by tjavaid** [comment]
please test

**Comment by tjavaid** [comment]
backport of #45605

**Comment by tjavaid** [comment]
+1

- spurious differences seen from unstable WF `12834.7` (open issue #39803 )

**Comment by aloeliger** [comment]
+l1

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
