### PR TITLE
Update RelVal input to CMSSW_7_6_0_pre4

### PR DESCRIPTION
**Pull request by ferencek**
**Update (Sep. 9, 2015):** Rebased to CMSSW_7_6_X_2015-09-09-2300 to avoid merge conflicts.

### CODE REVIEW

**Comment by ferencek** [comment]
@monttj, @slava77, can one of you please trigger the tests. Thanks

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by ferencek** [comment]
@monttj, can you please sign this PR. I would like to expedite this PR so further developments on top of it can proceed. Thanks.

**Comment by monttj** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
