### PR TITLE
finecalo: No longer count reentries into the calorimeter as boundary crossings

### PR DESCRIPTION
**Pull request by tklijnsma**
#### PR description:

No longer counts reentries into the calorimeter as boundary crossings. The boundary-crossing position and momentum for tracks that started in the calorimeter or entered before are no longer (over)written.

#### PR validation:

Verified with debug statements in the code.

### CODE REVIEW

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by perrotta** [comment]
@cmsbuild please test

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by civanch** [comment]
+1

**Comment by silviodonato** [comment]
assign upgrade
(related to hgcal)

**Comment by srimanob** [comment]
Hi @tklijnsma 
Do I understand correctly that we don't expect to see any changes on PR test? The PR description seems to mention about the change of behaviour of the module, but not clear if we expect to see change in (low) stat PR test.

Thx.

**Comment by tklijnsma** [comment]
Hi @srimanob , this PR only changes results when the `fineCalo` process modifier (https://github.com/cms-sw/cmssw/blob/49cd0eb9a47e85d38023c5c158e60be18687ee04/SimG4Core/Application/python/g4SimHits_cfi.py#L65) is turned on. I don't think there are any PR tests right now that have that, I am just testing locally. We'll work on getting something in runTheMatrix.py.

**Comment by silviodonato** [comment]
test parameters:
- relvals_opt = --procModifiers fineCalo

**Comment by silviodonato** [comment]
this should turnon finecalo

**Comment by silviodonato** [comment]
please test

**Comment by srimanob** [comment]
Please test

Just give it another try.

**Comment by silviodonato** [comment]
test parameters:
- relvals_opt = --command '--procModifiers fineCalo'

**Comment by silviodonato** [comment]
@cmsbuild  please abort

**Comment by silviodonato** [comment]
test parameters:

**Comment by silviodonato** [comment]
@smuzaffar  It looks like we cannot pass `--command '--procModifiers fineCalo'` as a option of the PR test (see above).
Maybe this is a side effect of https://github.com/cms-sw/cms-bot/pull/1541. Do you think we can add `"` and/or `'` among the allowed parameters in https://github.com/cms-sw/cms-bot/blob/master/process_pr.py#L42 or you think there are security issues? Thanks!

**Comment by smuzaffar** [comment]
we can allow `'`  for the `relvals_opt` but problem is also at https://github.com/cms-sw/cms-bot/blob/master/pr_testing/test_multiple_prs.sh#L1002 where you have to merge the two `--command` optiosn. feel free to open a  cms-bot PR to make it work

**Comment by civanch** [comment]
please test

**Comment by srimanob** [comment]
Do we want to hold this PR and https://github.com/cms-sw/cmssw/pull/34597 until we can make the test, or we would like to merge them first ?

Thanks.

**Comment by srimanob** [comment]
hold

**Comment by civanch** [comment]
@srimanob, from my today understanding both PRs are fine and are useful. I do not understand what happens with testing scripts and how we should proceed, so sign PRs for any case.

**Comment by srimanob** [comment]
unhold

**Comment by srimanob** [comment]
+Upgrade

**Comment by perrotta** [comment]
test parameters:
- relvals_opt = --command '--procModifiers fineCalo'

**Comment by perrotta** [comment]
please test

**Comment by smuzaffar** [comment]
@perrotta , please note that  `--command '--procModifiers fineCalo'` will override `--command  '--customise Validation/Performance/TimeMemoryJobReport.customiseWithTimeMemoryJobReport'`  option ( https://github.com/cms-sw/cms-bot/blob/master/pr_testing/test_multiple_prs.sh#L1002-L1005 ). In order to let runTheMatrix use both options we need to update https://github.com/cms-sw/cmssw/blob/master/Configuration/PyReleaseValidation/scripts/runTheMatrix.py#L229-L232 and added `action="append",`

**Comment by perrotta** [comment]
Ah, ok. Thank you @smuzaffar 

Anyhow, at this point I think that we can let the test going: even if not customizing with the `TimeMemoryJobReport` we can check whether the updates (and the whole `fineCalo` related modifications) can run smoothly.

**Comment by perrotta** [comment]
@tklijnsma are we learning anything with these tests with the `fineCalo` procModifier enabled?
Can you comment on the test failures?

**Comment by srimanob** [comment]
test parameters:
- relvals_opt = --command '--customise Validation/Performance/TimeMemoryJobReport.customiseWithTimeMemoryJobReport --procModifiers fineCalo'

**Comment by civanch** [comment]
11634.911 and 11634.912 WFs are for DD4Hep, I suspect that modifier does not applicable in a simple way. I would merge this and another PRs for finecalo, because it pass ordinary set of tests and not affect mainstream. In fact, finecalo is a special option needed for development.

**Comment by perrotta** [comment]
+1
- Simple addition
- Tests succeed with no changes in output on standard workflows
-  '--procModifiers fineCalo' will be selected in dedicated workflows, now under development

**Comment by srimanob** [comment]
> @perrotta , please note that `--command '--procModifiers fineCalo'` will override `--command '--customise Validation/Performance/TimeMemoryJobReport.customiseWithTimeMemoryJobReport'` option ( https://github.com/cms-sw/cms-bot/blob/master/pr_testing/test_multiple_prs.sh#L1002-L1005 ). In order to let runTheMatrix use both options we need to update https://github.com/cms-sw/cmssw/blob/master/Configuration/PyReleaseValidation/scripts/runTheMatrix.py#L229-L232 and added `action="append",`

I make a PR in
https://github.com/cms-sw/cmssw/pull/34722
not sure it is all we need. @smuzaffar @perrotta

**Comment by srimanob** [comment]
+Upgrade

**Comment by perrotta** [comment]
merge

**Comment by srimanob** [comment]
@civanch 
Should we disable it from https://github.com/cms-sw/cmssw/blob/master/SimG4Core/Application/python/g4SimHits_cfi.py#L65-L69 first?

The error also shows in reminiaod data workflow also, 136.88811.

**Comment by civanch** [comment]
@srimanob, I am not sure if we should disable modifier inside g4SimHits_cfi. Also I am not sure if modifier for this option is the best solution. I personally prefer customization for such parameters. Inside g4SimHits_cfi there are many parameters, the modifier for these HGCal parameters should be re-discussed.

**Pull request merged**
