### PR TITLE
[DT DQM] Fix some minor style bugs 14_0_X

### PR DESCRIPTION
**Pull request by jfernan2**
#### PR description:

Verbatim backport of https://github.com/cms-sw/cmssw/pull/44800

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by tjavaid** [comment]
backport of #44800

**Comment by tjavaid** [comment]
+1

- P5 tests Ok with `14_0_7` release.

**Comment by rappoccio** [comment]
+1

**Pull request merged**
