### PR TITLE
OMTF emulator corresponding to the 2024 OMTF firmware

### PR DESCRIPTION
**Pull request by kbunkow**
#### PR description:

Changes to the OMTF algorithm which were introduced in the firmware after the previous OMTF emulator PR was merged.
Mainly fixes related to the triggering on the displaced muons. With this update, the OMTF data-to-emulator agreement in the online DQM should be at the level of 99.5%. The firmware was deployed in the CMS on 19th March 2024.

#### PR validation:

The version was checked by running the online DQM on the data from a collision run taken in April 2024. 

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported 

This PR is not a backport

### CODE REVIEW

**Comment by epalencia** [comment]
Please test

**Comment by missirol** [comment]
Hi, I don't know enough to review this PR, but I have a couple of naive questions.

> With this update, the OMTF data-to-emulator agreement in the online DQM should be at the level of 99.5%. The firmware was deployed in the CMS on 19th March 2024.

Is the plan to backport this to 14_0_X ?

I guess the answer is 'yes', for the purpose of both online-dqm in 2024 and using the emulator corresponding to the 2024 firmware in the upcoming 2024 MC production in 14_0_X.

At the same time, 14_0_X will also be used to make new "re-reco MC" samples for 2022 and 2023 conditions ([link](https://indico.cern.ch/event/1409985/contributions/5926588/attachments/2849136/4981441/24-05-02_News_PPD.pdf#page=11)). Once this PR is integrated in 14_0_X, what guarantees that the 2022/23 MCs in 14_0_X will use the emulator corresponding to the 2022/23 OMTF firmware (while the 2024 MC in the same release, 14_0_X, will use the 2024 version of the emulator) ?

**Comment by missirol** [comment]
Okay, thanks for the clarification, @kbunkow.

**Comment by mbluj** [comment]
> Okay, thanks for the clarification, @kbunkow.

For records: this development was backported in https://github.com/cms-sw/cmssw/pull/44920

**Pull request merged**
