### PR TITLE
multithreading fix for 74x: AlCa modules

### PR DESCRIPTION
**Pull request by fwyzard**
backport #10957 / #10969 to 74x

### CODE REVIEW

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
tracked at #11317

**Comment by mmusich** [comment]
please test

**Comment by fwyzard** [comment]
rebased to merge on top of both CMSSW_7_4_X and CMSSW_7_4_12_patch4

**Comment by fwyzard** [comment]
please test

**Comment by davidlange6** [comment]
+1

**Comment by fwyzard** [comment]
@mmusich, @diguida, @franzoni, can you please sign again ?

**Comment by diguida** [comment]
+1

**Pull request merged**
