### PR TITLE
esConsumes migration of CalibMuon/DTCalibration

### PR DESCRIPTION
**Pull request by swagata87**
#### PR description:

This PR aims to partially migrate `CalibMuon/DTCalibration` package to use esConsumes. Technical PR, no change in physics is expected.

#### PR validation:

code compiles. 
`runTheMatrix.py -l 1330` ran fine

This PR is not a backport.
Backport not needed.

### CODE REVIEW

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
Hi @swagata87 the SA shows these errors of the EDAnalyzers needed to be a `one` module, if I understand correctly you plan to deal with that in a follow up PR, right?

**Comment by swagata87** [comment]
Hi @tvami, 
indeed, that will be a follow up PR soon. 
In this one I just focussed on esConsumes.

**Comment by tvami** [comment]
+alca
 * EDAnalyzers migration is expected in a separate PR

**Comment by perrotta** [comment]
+1

**Pull request merged**
