### PR TITLE
Update `PrimaryVertexMonitor`

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

The purpose of this PR is to rationalize the code of `PrimaryVertexMonitor` in order to avoid unnecessary repetitions, also I am adding profile plots of the transverse and longitudinal impact parameter errors as a function of track eta and phi.

#### PR validation:

Privately checked `runTheMatrix.py -l 140.063 -t 4 -j 8 --ibeos` output.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Not a backport, but to be backported.

### CODE REVIEW

**Comment by mmusich** [comment]
hold

**Comment by mmusich** [comment]
unhold

**Comment by mmusich** [comment]
please test

**Comment by emanueleusai** [comment]
+1

**Comment by perrotta** [comment]
+1

**Comment by slava77** [comment]
type tracking

**Pull request merged**
