### PR TITLE
Modifier to apply energy corrections to photons and electrons (miniAOD)

### PR DESCRIPTION
**Pull request by matteosan1**
Weight files are temporarily stored in RecoEgamma/EgammaTools/data. They will removed once the weights will be integrated into the GT.
Working on comparison plots for the resolution.

### CODE REVIEW

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by matteosan1** [comment]
I have updated this PR to read from the DB. The payloads have been loaded into the dropbox.

**Comment by ferencek** [comment]
This PR will bring into CMSSW code tree more than 15 MB of binary ROOT files. Please rewrite history. Same for #10613

**Comment by slava77** [comment]
.db files are still here, please remove (and update to read from the DB proper)
I suppose, more updates are needed.
76X PR is needed as well.
This is where the feature will be integrated and checked first

**Comment by ferencek** [comment]
Indeed, there are also .db files together with .root files left in the branch history. So in total more than 30 MB of binary files would be pulled in.

**Comment by slava77** [comment]
@cmsbuild please test

I'm not done with the review of the 76X version. So, this may be not the end of this PR changes yet.

**Comment by slava77** [comment]
Matteo, please provide a fix to the matrix test error

**Comment by lgray** [comment]
@slava77 @matteosan1 ditto

**Comment by matteosan1** [comment]
For 76 and 74 should be done.
There was a typo in one of the tags.


On 8/11/15 16:24, Slava Krutelyov wrote:
>
> Matteo, please provide a fix to the matrix test error
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/cms-sw/cmssw/pull/10611#issuecomment-129902627>.
>

+++++++++++
Matteo Sani
University of California, San Diego, US.
Tel: +41227671577
CERN Office: 40-3-A02

**Comment by lgray** [comment]
@slava77 can you give this a -1 since it is superseded? thanks!

**Comment by slava77** [comment]
-1
... it's better for Matteo to hit the "Close" button.

**Comment by slava77** [comment]
@davidlange6 please close this PR

**Comment by matteosan1** [comment]
Done.

On 8/11/15 17:28, Slava Krutelyov wrote:
>
> -1
> ... it's better for Matteo to hit the "Close" button.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/cms-sw/cmssw/pull/10611#issuecomment-129929867>.
>

+++++++++++
Matteo Sani
University of California, San Diego, US.
Tel: +41227671577
CERN Office: 40-3-A02

**Pull request closed without merging**
