### PR TITLE
[PowerPC] Fix unit tests in DataFormats/Scouting

### PR DESCRIPTION
**Pull request by iarspider**
#### PR description:

The new unit tests introduced in https://github.com/cms-sw/cmssw/pull/41093 by @missirol are failing on PowerPC due to an extra line being printed out:

```
$ diff -u testDataFormatsScoutingRun2_expected.log testDataFormatsScoutingRun2_step2.log
--- testDataFormatsScoutingRun2_expected.log    2023-03-25 23:03:42.000000001 +0100
+++ testDataFormatsScoutingRun2_step2.log     2023-03-25 23:26:09.000000001 +0100
@@ -1,3 +1,4 @@
+Disabling gnu++: clang has no __float128 support on this target!
 --------------------------------------------------
 Run             = 1
 LuminosityBlock = 291048
```

#### PR validation:

Test ran locally.

### CODE REVIEW

**Comment by iarspider** [comment]
please test for el8_ppc64le_gcc11

**Comment by iarspider** [comment]
please test

**Comment by missirol** [comment]
Thanks for the fix, @iarspider .

**Comment by iarspider** [comment]
please test for el8_ppc64le_gcc11

**Comment by missirol** [comment]
If I can make a suggestion, this [*] would also work, and doesn't depend on the specifics of the stderr message.

Once this PR converges, I will include it in the backport of the unit test (#41168).

[*]
```diff
diff --git a/DataFormats/Scouting/test/testDataFormatsScoutingRun2.sh b/DataFormats/Scouting/test/testDataFormatsScoutingRun2.sh
index d531d53f8d9..62e437751ca 100755
--- a/DataFormats/Scouting/test/testDataFormatsScoutingRun2.sh
+++ b/DataFormats/Scouting/test/testDataFormatsScoutingRun2.sh
@@ -21,8 +21,8 @@ cat testDataFormatsScoutingRun2_step1.log
 
 # validate content of Scouting collections
 "${SCRAM_TEST_PATH}"/scoutingCollectionsDumper.py -v 1 -n 1 --skip 81 -i testDataFormatsScoutingRun2_step1.root -k Scouting \
-  &> testDataFormatsScoutingRun2_step2.log \
-  || die "Failure running scoutingCollectionsDumper.py" $? testDataFormatsScoutingRun2_step2.log
+  > testDataFormatsScoutingRun2_step2.log 2> testDataFormatsScoutingRun2_step2_stderr.log \
+  || die "Failure running scoutingCollectionsDumper.py" $? testDataFormatsScoutingRun2_step2_stderr.log
 
 diff -q "${SCRAM_TEST_PATH}"/testDataFormatsScoutingRun2_expected.log testDataFormatsScoutingRun2_step2.log \
   || die "Unexpected differences in outputs of testDataFormatsScoutingRun2 (step 2)" $?
diff --git a/DataFormats/Scouting/test/testDataFormatsScoutingRun3.sh b/DataFormats/Scouting/test/testDataFormatsScoutingRun3.sh
index 3b117b836f7..75e22237a70 100755
--- a/DataFormats/Scouting/test/testDataFormatsScoutingRun3.sh
+++ b/DataFormats/Scouting/test/testDataFormatsScoutingRun3.sh
@@ -21,8 +21,8 @@ cat testDataFormatsScoutingRun3_step1.log
 
 # validate content of Scouting collections
 "${SCRAM_TEST_PATH}"/scoutingCollectionsDumper.py -v 1 -n 1 --skip 137 -i testDataFormatsScoutingRun3_step1.root -k Run3Scouting \
-  &> testDataFormatsScoutingRun3_step2.log \
-  || die "Failure running scoutingCollectionsDumper.py" $? testDataFormatsScoutingRun3_step2.log
+  > testDataFormatsScoutingRun3_step2.log 2> testDataFormatsScoutingRun3_step2_stderr.log \
+  || die "Failure running scoutingCollectionsDumper.py" $? testDataFormatsScoutingRun3_step2_stderr.log
 
 diff -q "${SCRAM_TEST_PATH}"/testDataFormatsScoutingRun3_expected.log testDataFormatsScoutingRun3_step2.log \
   || die "Unexpected differences in outputs of testDataFormatsScoutingRun3 (step 2)" $?
```

**Comment by smuzaffar** [comment]
these tests are also failing for root master and root 628 IBs ( https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_amd64_gcc11/CMSSW_13_1_ROOT6_X_2023-03-24-2300/unitTestLogs/DataFormats/Scouting#/381-381 )

**Comment by iarspider** [comment]
> If I can make a suggestion, this [*] would also work, and doesn't depend on the specifics of the stderr message.

Sure, I was also thinking of redirecting stderr to a different file, but wasn't sure. I will update my PR.

**Comment by missirol** [comment]
> these tests are also failing for root master and root 628 IBs ( https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_amd64_gcc11/CMSSW_13_1_ROOT6_X_2023-03-24-2300/unitTestLogs/DataFormats/Scouting#/381-381 )

I don't know what's causing the failures in `ROOT6*` IBs.

Testing with `CMSSW_13_1_ROOT628_X_2023-03-24-2300`, I see a similar failure with the simple test in [1]. A similar test with a different input file [2] does not fail. So, somehow it seems related to the content of the input files, not the specifics of `DataFormats/Scouting/test/scoutingCollectionsDumper.py`.

[1] (this fails; the input file is one of the two used in the `DataFormats/Scouting` unit tests)
```
python3 DataFormats/FWLite/test/pyroot_multichain.py inputFiles=file:/eos/cms/store/user/cmsbuild/store/mc/Run3Summer22DR/GluGlutoHHto2B2Tau_kl-5p00_kt-1p00_c2-0p00_TuneCP5_13p6TeV_powheg-pythia8/GEN-SIM-RAW/124X_mcRun3_2022_realistic_v12-v2/2550000/bbfb86f3-4073-47e3-967b-059aa6b904ad.root
```

[2] (this works; the input file below was chosen arbitrarily)
```
python3 DataFormats/FWLite/test/pyroot_multichain.py inputFiles=file:/eos/cms/store/user/cmsbuild/store/mc/Run3Winter22MiniAOD/TTToSemiLeptonic_TuneCP5_13p6TeV-powheg-pythia8/MINIAODSIM/FlatPU0to70_122X_mcRun3_2021_realistic_v9-v2/60000/0080ab4b-fbf8-44ae-b676-456335db4798.root
```

**Comment by iarspider** [comment]
please test for el8_ppc64le_gcc11

**Comment by iarspider** [comment]
please test for el8_ppc64le_gcc11

**Comment by iarspider** [comment]
please test for el8_ppc64le_gcc11

**Comment by aandvalenzuela** [comment]
Hello @Dr15Jones,
I could reproduce the issue with `CMSSW_13_1_ROOT628_X_2023-03-27-2300`:
```
28-Mar-2023 10:02:46 CEST  Closed file root://eoscms.cern.ch//eos/cms/store/user/cmsbuild/store/mc/RunIISummer20UL18RECO/DoubleElectron_Pt-1To300-gun/AODSIM/FlatPU0to70EdalIdealGT_EdalIdealGT_106X_upgrade2018_realistic_v11_L1v1_EcalIdealIC-v2/270000/4CDD9457-E14C-D84A-9BD4-3140CB6AEEB6.root
/tmp/avalenzu/CMSSW_13_1_ROOT628_X_2023-03-27-2300/src/DataFormats/Scouting/test/testDataFormatsScoutingRun2.sh: line 25: 19155 Segmentation fault      "${SCRAM_TEST_PATH}"/scoutingCollectionsDumper.py -v 1 -n 1 --skip 81 -i testDataFormatsScoutingRun2_step1.root -k Scouting &> testDataFormatsScoutingRun2_step2.log

 *** Break *** abort
malloc(): unsorted double linked list corrupted
 *** Break *** abort
```

**Comment by Dr15Jones** [comment]
@aandvalenzuela does the crash happen in cmsRun or in the python executable?

**Comment by aandvalenzuela** [comment]
@Dr15Jones, I think it fails when running `scoutingCollectionsDumper.py` (https://github.com/cms-sw/cmssw/blob/master/DataFormats/Scouting/test/testDataFormatsScoutingRun2.sh#L23)

**Comment by smuzaffar** [comment]
@iarspider , instead of squashing you last push added an extra commit :-)

**Comment by iarspider** [comment]
I will redo these changes in a new PR.

**Pull request closed without merging**
