### PR TITLE
python3 compatibility change in autoCondPhase2.py

### PR DESCRIPTION
**Pull request by davidlange6**
#### PR description:

python3 compatibility change in autoCondPhase2.py
(DEVEL builds are totally broken without this fix)

#### PR validation:

Compiles and python2 workflows run

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
please test

**Comment by christopheralanwest** [comment]
+1

**Comment by Dr15Jones** [comment]
@fabiocos @kpedro88 can we get this in the IB to fix DEVEL?

**Comment by kpedro88** [comment]
+1

**Pull request merged**
