### PR TITLE
[10.2.X]Change GT. Add ExtendedDetailedCavern Geom in 2018 MC

### PR DESCRIPTION
**Pull request by lpernie**
Added new geometry [1] as requested in [2] to 2018 MC GTs.

.  https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/102X_upgrade2018_design_v7/102X_upgrade2018_design_v9
.  https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/102X_upgrade2018_realistic_v12/102X_upgrade2018_realistic_v14
.  https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/102X_upgrade2018_realistic_v12HEfail_v1/102X_upgrade2018_realistic_v12HEfail_v2
.  https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/102X_upgrade2018cosmics_realistic_deco_v11/102X_upgrade2018cosmics_realistic_deco_v12

[1]
  Tag: XMLFILE_Geometry_103YV4_ExtendedDetailedCavern2018_mc
  Record: GeometryFileRcd
  Label: ExtendedDetailedCavern
[2] https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3958.html

### CODE REVIEW

**Comment by lpernie** [comment]
please test

**Comment by lpernie** [comment]
+1

**Comment by lpernie** [comment]
+1

**Comment by fabiocos** [comment]
+1

not affecting production workflows

**Pull request merged**
