### PR TITLE
Phase2-hgx342C Modify the tester to check correctly the  wafer ID from position for HGCal

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Modify the tester to check correctly the  wafer ID from position for HGCal

#### PR validation:

Use this to understand the difference in ID setting from position in DDD and DD4hep

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
+geometry

**Comment by bsunanda** [comment]
@srimanob Please approve this

**Comment by srimanob** [comment]
+Upgrade

**Comment by perrotta** [comment]
+1

**Pull request merged**
