### PR TITLE
Add functions for memory allocation on a single byte basis

### PR DESCRIPTION
**Pull request by bfonta**
#### PR description:
Added functions which allocate memory on the GPU and CPU (device and host) on a single byte basis, instead of requiring multiples of ```sizeof```. This addition allows the usage of a single contiguous chunk of memory to store different types (as an example, two ```double```s and two ```float```s).
This PR has no dependencies.

#### PR validation:
The functions were successfully tested within CMSSW with a producer yet to be released, but the code can be provided upon request.

### CODE REVIEW

**Comment by makortel** [comment]
How about allocating an array of  `char`s, i.e. `cms::cuda::make_device_unique<char[]>(nbytes)`, instead?

**Comment by b-fontana** [comment]
I had not thought about that possibility, which is indeed very simple. However, creating a different method makes the code clearer, since one immediately knows that the memory will be likely using different types, while your suggestion is potentially more ambiguous.
In addition, your option forces a cast in case the user does not want to use ```char``` in the first few elements. This will be often the case, as the most common practice for structuring multiple-type chunks of memory is to start by the types that occupy more bytes. As a consequence, the code gets more cluttered. My option, instead, immediately displays the first type being considered.
Still, this is just a detail. Feel free to choose the option you prefer.

**Comment by fwyzard** [comment]
@b-fontana in your proposal, what is purpose of passing a type `T` along with the number of bytes ?

**Comment by b-fontana** [comment]
@fwyzard 

Again, I suppose that different coding styles could be adopted here. I feel that it is more informative to explicitly specify the type of the pointer to the first element rather than always cast it later (when calling the ```get()``` method). Assuming a descriptive name for the new functions, anyone reading the code will anyways expect some pointer casting later in the code (using another pointer that does not point to the first element).

**Comment by fwyzard** [comment]
It's not only about coding style, but also about the C++ memory model and aliasing rules - but I'm not criticizing, I am actually interested in this for an other reason (or maybe for the very same reason, a dynamically-sized structure) !

If you have a `T *` that points to a chunk of memory of size `s` bigger than than `sizeof(T)`, C++ doesn't properly model what you do to the rest of the memory (*i.e.* from `s` to `sizeof(T)`).

While a `char*` or `void*` are allowed to alias any other type, so should be safer to use.

**Comment by makortel** [comment]
I'd say that with all this casting business it would be much clearer to hide the explicit casting from the code using the arrays, i.e. define a class that holds the `unique_ptr` to the raw memory, and provides an interface that gives the correct types. Then the cost of the "extra" `reinterpret_cast` becomes negligible.

I *could* think of adding `device::unique_ptr<void>` (and same for host) to represent raw memory with a given amount of bytes. The added benefit compared to plain `void *` would be the automatic call of the correct `free()`.

**Comment by fwyzard** [comment]
I think that `device::unique_ptr<char>` would be preferable to `device::unique_ptr<void>` - because one can do arithmetic on a `char *` (*i.e.* add an offset, *etc.*), but not on a `void *`.

Or possibly `device::unique_ptr<std::byte>` (either from C++ 17 or a reimplementation within `cuda_std`).

**Comment by makortel** [comment]
> I think that `device::unique_ptr<char>` would be preferable to `device::unique_ptr<void>` - because one can do arithmetic on a `char *` (_i.e._ add an offset, _etc._), but not on a `void *`.

Good point. I thought the `void` because after educating myself with random googling, it seemed to be that accessing a `char` object through a `T *` pointer (`T != char`) would be illegal, and `device_unique_ptr<char>` looks like it would hold pointer to `char` object(s) (strictly speaking that is not the case because the `char *` is `reinterpret_cast`ed from `void *` instead of "creating an object" with placement new). Unless I've missed/overlooked something.

> Or possibly `device::unique_ptr<std::byte>` (either from C++ 17 or a reimplementation within `cuda_std`).

I suppose `unique_ptr<std::byte[]>` would work out of the box.

**Comment by b-fontana** [comment]
I might be missing something, but according to the [documentation](https://en.cppreference.com/w/cpp/types/byte) ```std::byte``` is not an arithmetic type and only bit-wise operators are defined for it. A justification for this behavior can be found in [this answer](https://stackoverflow.com/questions/48355242/use-cases-of-stdbyte) and in references and comments therein.

**Comment by fwyzard** [comment]
I don't mean arithmetic on values of type `std::byte`, I mean on pointers of type `std::byte *`, which is needed to *e.g.* identify an address inside a buffer.

Here is an example to hopefully explain better what I mean:
```c++
#include <cstddef>
#include <cstdlib>
#include <iostream>
#include <string>

int main(void) {
  void * p1 = malloc(1024);
  auto i1 = reinterpret_cast<int *>(p1);
  auto f1 = reinterpret_cast<float *>(p1 + sizeof(int));
  std::cout << "Got buffer at     " << p1 << std::endl;
  std::cout << "Allocate int at   " << i1 << std::endl;
  std::cout << "Aloocate float at " << f1 << std::endl;
  std::cout << std::endl;

  auto p2 = reinterpret_cast<char *>(malloc(1024));
  auto i2 = reinterpret_cast<int *>(p2);
  auto f2 = reinterpret_cast<float *>(p2 + sizeof(int));
  std::cout << "Got buffer at     " << p2 << std::endl;
  std::cout << "Allocate int at   " << i2 << std::endl;
  std::cout << "Aloocate float at " << f2 << std::endl;
  std::cout << std::endl;

  auto p3 = reinterpret_cast<std::byte *>(malloc(1024));
  auto i3 = reinterpret_cast<int *>(p3);
  auto f3 = reinterpret_cast<float *>(p3 + sizeof(int));
  std::cout << "Got buffer at     " << p3 << std::endl;
  std::cout << "Allocate int at   " << i3 << std::endl;
  std::cout << "Aloocate float at " << f3 << std::endl;
  std::cout << std::endl;

  return 0;
}
```

Compiling with `g++-9 -std=c++17 -O2 -Wall test.cc -o test` gives
```
test.cc: In function ‘int main()’:
test.cc:8:42: warning: pointer of type ‘void *’ used in arithmetic [-Wpointer-arith]
    8 |   auto f1 = reinterpret_cast<float *>(p1 + sizeof(int));
      |                                       ~~~^~~~~~~~~~~~~
```
*i.e.* a warning that one shouldn't do arithmetic on pointers of type `void *`.

Running gives
```
$ ./test 
Got buffer at     0x55999919ae70
Allocate int at   0x55999919ae70
Aloocate float at 0x55999919ae74

Got buffer at     
Allocate int at   0x55999919b690
Aloocate float at 0x55999919b694

Got buffer at     0x55999919baa0
Allocate int at   0x55999919baa0
Aloocate float at 0x55999919baa4
```

where you can see that the `char *` is interpreted as a `NULL`-terminated string, rather than a pointer.

`std::byte` seems to avoid both (minor) problems.

**Comment by b-fontana** [comment]
Thanks for clarifying and for the very nice example.

**Comment by VinInn** [comment]
What about alignment?

**Comment by makortel** [comment]
> What about alignment?

Do you refer to the alignment of "later columns" in the allocated memory block? With the `unique_ptr` API that is solely on the responsibility of the caller (the beginning of the block is aligned as by `cudaMalloc()`/`cudaHostAlloc()`).

**Comment by fwyzard** [comment]
@makortel remind me, please - the allocator simply caches blocks of memory returned by `cudaMalloc()`, it never tries to split a block in smaller chunks, does it ?

**Comment by makortel** [comment]
> remind me, please - the allocator simply caches blocks of memory returned by `cudaMalloc()`, 

Correct.

> it never tries to split a block in smaller chunks, does it ?

Correct, currently it never splits a block.

**Comment by b-fontana** [comment]
> I suppose unique_ptr< std::byte[] > would work out of the box.

I can indeed confirm that, at least in my use case, it seems to work. I am doing something similar to the following:
```c++
      auto mem = cms::cuda::make_device_unique<std::byte[]>(number_hits * soa_size, 0);

      soa->first_soa_float_variable  = reinterpret_cast<float*>(mem.get());
```

**Comment by VinInn** [comment]
mem as local variable will make the buffer to be  deallocated as soon as it goes out of scope...
please have a look to the code-patterns used in CudaDataFormats

**Comment by b-fontana** [comment]
@VinInn I was solely trying to use a contained example for demonstration purposes. The variable ```mem``` is not local in the real one.

**Comment by silviodonato** [comment]
@b-fontana What's the plan of this PR? If I understood correctly, there is some consensus about using `std::byte` instead of the generic `<T>`

**Comment by silviodonato** [comment]
@b-fontana?

**Comment by b-fontana** [comment]
I think ```std::byte``` works as required, but do not know if it is desirable to create a new non-templated function with a specific name, or if one just continues to use the same function with ```T = std::byte``` whenever one needs byte-level control. I would wait for @fwyzard and @makortel 's opinion before taking any action on this PR.

**Comment by makortel** [comment]
To me all `make_device_unique<unsigned char[]>(size, stream)`,  `make_device_unique<uint8_t[]>(size, stream)` and `make_device_unique<std::byte[]>(size, stream)` are sufficient, convey the intention, and are consistent with the interface of `std::make_unique`, so I would prefer to stay with those.

**Comment by silviodonato** [comment]
what do you think @fwyzard ?

**Comment by fwyzard** [comment]
I agree with Matti, I'd stay with `make_device_unique<std::byte[]>(size, stream)`.

**Pull request closed without merging**
