### PR TITLE
[120X] Add GTs for Run-3 test beam data taking + edit DQM unit test run number and dataset

### PR DESCRIPTION
**Pull request by tvami**
#### PR description:

Global Tag change:
 * it is needed for https://github.com/cms-sw/cmssw/pull/35551
 * this PR can be part of a commit in 35551 if preferred (this PR was submitted just to make things go faster)
 * Here are the differences with respect to the CRUZET GTs:
HLT:
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/113X_dataRun3_HLT_v3/120X_dataRun3_HLT_v3
Express:
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/113X_dataRun3_Express_v4/120X_dataRun3_Express_v2
Prompt:
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/113X_dataRun3_Prompt_v3/120X_dataRun3_Prompt_v2

HN: 
https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/4488.html

Edit: 
 * now this PR contains changes in the DQM unit tests, to test a more recent CRUZET run 

#### PR validation:

Was tested at P5 for DQM

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

This is a backport, needed for DQM testing

### CODE REVIEW

**Comment by tvami** [comment]
@cmsbuild , ping

**Comment by tvami** [comment]
code-checks

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
@cmsbuild , please test with https://github.com/cms-sw/cmssw/pull/35551

**Comment by tvami** [comment]
> * @tvami please fix the HLT GT diff in the description (the correct link should be https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/113X_dataRun3_HLT_v3/120X_dataRun3_HLT_v3)

Done

**Comment by tvami** [comment]
@perrotta @qliphy as mentioned in the other PR, this needs to be merged together with https://github.com/cms-sw/cmssw/pull/35551

**Comment by qliphy** [comment]
+1

**Comment by qliphy** [comment]
merge

**Comment by qliphy** [comment]
+1

**Pull request merged**
