### PR TITLE
Phase2 era from run3

### PR DESCRIPTION
**Pull request by kpedro88**
Now that 2018 and 2019/Run3 scenarios are actively being developed, the Phase2 Era should inherit from Run3 in order to stay consistent with the latest changes.

However, to avoid potential confusion, I excluded the Phase1 pixel & tracking eras from Phase2. @boudoul @makortel @VinInn can you confirm that this is the right thing?

Some changes are expected in Phase2 workflows due to the 10TS->8TS change in HB.

### CODE REVIEW

**Comment by kpedro88** [comment]
please test

**Comment by makortel** [comment]
@kpedro88 

> However, to avoid potential confusion, I excluded the Phase1 pixel & tracking eras from Phase1. @boudoul @makortel @VinInn can you confirm that this is the right thing?

Yes, this is correct. The phase1 and phase2 modifiers are mutually exclusiv (at least for tracking simultaneous use will cause weird things to happen, not sure on the top of my head what exactly would happen for tracker).

**Comment by davidlange6** [comment]
hi @kpedro88 - did you confirm also with muons that this change  works?

**Comment by kpedro88** [comment]
@davidlange6 no, I probably should (but they're just adding new detectors, not removing anything, so hopefully not as complicated as tracker)

@jshlee do you see any problem on the muon side with this change in the eras?

**Comment by jshlee** [comment]
@kpedro88 - yes this should be fine.
we will need to test run3_GEM later.

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
+operations

**Pull request merged**
