### PR TITLE
Update clone_ptr

### LINKED ISSUE #45323: [GCC13 only] array-bounds error during compilation of testFWCoreUtilitiesCatch2
In GCC13 IB, the following errors were emitted when building `testFWCoreUtilitiesCatch2`:

```
>> Building binary testFWCoreUtilitiesCatch2
<...>
In member function '__dt_base ',
    inlined from '__dt_base ' at src/FWCore/Utilities/interface/clone_ptr.h:11:10,
    inlined from '__dt_base ' at src/FWCore/Utilities/test/test_catch2_clone_ptr.cc:26:10,
    inlined from 'destroy' at /data/cmsbld/jenkins/workspace/build-any-ib/w/el9_amd64_gcc13/external/gcc/13.2.0-1b0a3367d04f48f01ad3ccf40e55475c/include/c++/13.2.0/bits/new_allocator.h:194:13,
    inlined from 'destroy' at /data/cmsbld/jenkins/workspace/build-any-ib/w/el9_amd64_gcc13/external/gcc/13.2.0-1b0a3367d04f48f01ad3ccf40e55475c/include/c++/13.2.0/bits/alloc_traits.h:557:15,
    inlined from '_M_realloc_insert' at /data/cmsbld/jenkins/workspace/build-any-ib/w/el9_amd64_gcc13/external/gcc/13.2.0-1b0a3367d04f48f01ad3ccf40e55475c/include/c++/13.2.0/bits/vector.tcc:507:28,
    inlined from 'push_back' at /data/cmsbld/jenkins/workspace/build-any-ib/w/el9_amd64_gcc13/external/gcc/13.2.0-1b0a3367d04f48f01ad3ccf40e55475c/include/c++/13.2.0/bits/stl_vector.h:1289:21,
    inlined from '____C_A_T_C_H____T_E_S_T____0' at src/FWCore/Utilities/test/test_catch2_clone_ptr.cc:84:19:
  /data/cmsbld/jenkins/workspace/build-any-ib/w/el9_amd64_gcc13/external/gcc/13.2.0-1b0a3367d04f48f01ad3ccf40e55475c/include/c++/13.2.0/bits/unique_ptr.h:403:19: error: array subscript 0 is outside array bounds of 'struct B[0:]' [-Werror=array-bounds=]
   403 |         if (__ptr != nullptr)
      |                   ^
In function '____C_A_T_C_H____T_E_S_T____0':
lto1: note: source object is likely at address zero
In member function '__dt_base ',
    inlined from 'destroy' at /data/cmsbld/jenkins/workspace/build-any-ib/w/el9_amd64_gcc13/external/gcc/13.2.0-1b0a3367d04f48f01ad3ccf40e55475c/include/c++/13.2.0/bits/new_allocator.h:194:13,
    inlined from 'destroy' at /data/cmsbld/jenkins/workspace/build-any-ib/w/el9_amd64_gcc13/external/gcc/13.2.0-1b0a3367d04f48f01ad3ccf40e55475c/include/c++/13.2.0/bits/alloc_traits.h:557:15,
    inlined from '_M_realloc_insert' at /data/cmsbld/jenkins/workspace/build-any-ib/w/el9_amd64_gcc13/external/gcc/13.2.0-1b0a3367d04f48f01ad3ccf40e55475c/include/c++/13.2.0/bits/vector.tcc:507:28,
    inlined from 'push_back' at /data/cmsbld/jenkins/workspace/build-any-ib/w/el9_amd64_gcc13/external/gcc/13.2.0-1b0a3367d04f48f01ad3ccf40e55475c/include/c++/13.2.0/bits/stl_vector.h:1289:21,
    inlined from '____C_A_T_C_H____T_E_S_T____0' at src/FWCore/Utilities/test/test_catch2_clone_ptr.cc:84:19:
  src/FWCore/Utilities/test/test_catch2_clone_ptr.cc:26:10: error: array subscript 0 is outside array bounds of 'struct B[0:]' [-Werror=array-bounds=]
    26 |   struct B {
      |          ^
In function '____C_A_T_C_H____T_E_S_T____0':
lto1: note: source object is likely at address zero
```

[full log](https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/el9_amd64_gcc13/CMSSW_14_1_X_2024-06-26-1200/FWCore/Utilities)

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

- clone_ptr no longer inherits from std::unique_ptr
- worked around an apparent gcc13 link-time-optimization incorrect warning about incorrect indexing of the internal storage of a std::vector.

#### PR validation:

Code compiles without the warning and unit tests pass.

fixes #45323

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by smuzaffar** [comment]
please test for el9_amd64_gcc13

**Comment by smuzaffar** [comment]
gcc 13 build errors for [FWCore/Utilities](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-6c5653/40139/build-logs/FWCore/Utilities/log.html ) are fixed

**Comment by Dr15Jones** [comment]
+1

**Comment by rappoccio** [comment]
+1

**Comment by rappoccio** [comment]
merge

**Pull request merged**
