### PR TITLE
Have L1TGlobalUtil use std::string_view internally

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

This decreases the per event allocation by nearly 10x.

#### PR validation:

Ran step3 of workflow 12861.0 including an improved version of ModuleAllocMonitor to watch allocations.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
@makortel FYI

**Comment by Dr15Jones** [comment]
please test

**Comment by makortel** [comment]
type performance-improvements

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
@cmsbuild, ping

**Comment by mmusich** [comment]
@smuzaffar tests seem stuck here, can you please restart them? thank you.

**Comment by smuzaffar** [comment]
I have restarted the comparison job

**Comment by antoniovagnerini** [comment]
+dqm
- spurious differences from HGCal DQM test (open issue  #46416)

**Comment by mmusich** [comment]
> This decreases the per event allocation by nearly 10x.

I am still trying to understand from where I can see that.  Is this visible in any of the matrix test logs?

**Comment by perrotta** [comment]
+alca

**Comment by makortel** [comment]
> > This decreases the per event allocation by nearly 10x.
> 
> I am still trying to understand from where I can see that. Is this visible in any of the matrix test logs?

2024.202001 step 3 shows a decrease from [2372298522 allocation calls](https://cmssdt.cern.ch/SDT/jenkins-artifacts/ib-baseline-tests/CMSSW_14_2_X_2024-11-07-1100/el8_amd64_gcc12/-GenuineIntel/matrix-results/2024.202001_RunJetMET02024D_10k/step3_RunJetMET02024D_10k.log) to [2343161877 allocation calls](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-6b5b39/42679/runTheMatrix-results/2024.202001_RunJetMET02024D_10k/step3_RunJetMET02024D_10k.log), i.e. by 29 million calls (or by 1.2 %) for 100 events. Poking a few other random workflows did not show as clear reduction.

**Comment by mmusich** [comment]
+hlt
   * see https://github.com/cms-sw/cmssw/pull/46628#issuecomment-2468370347

**Comment by Dr15Jones** [comment]
> I am still trying to understand from where I can see that. Is this visible in any of the matrix test logs?

In principle, you could run a cmsRun job with and without this change and use the [AllocMonitorPreload](https://github.com/cms-sw/cmssw/tree/master/PerfTools/AllocMonitorPreload) and then at the end of the job you could compare lines beginning with
```
Memory Report:  # allocations calls:   
```
and you should see a difference. However it will not be a factor of 10x as that would be the difference in allocations across the entire job. As far as I can tell, the matrix logs do have that at the end but I do not know how to find the base-line logs to do the comparison. The memory base-line comparisons only looks at how much memory was being used in the job, it does not compare the number of allocations that were done (even though that information is in the logs).

What I did was

1. ran workflow 12861.0
2. changed step3 to use the [ModuleAllocMonitor](https://github.com/cms-sw/cmssw/tree/master/PerfTools/AllocMonitor)
3. ran step3 with and without this change
4. compared the information in the files written by ModuleAllocMonitor between the two runs and see the decrease in allocations

**Comment by mmusich** [comment]
> thanks, where can I find the log for the baseline (navigating from the summary)?

nevermind, I've found it out: https://cmssdt.cern.ch/SDT/jenkins-artifacts/ib-baseline-tests/CMSSW_14_2_X_2024-11-07-1100

**Comment by Dr15Jones** [comment]
@cms-sw/l1-l2 ping

**Comment by aloeliger** [comment]
+l1

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
