### PR TITLE
ignore empty paths when determining the first and last [End]Path

### PR DESCRIPTION
**Pull request by fwyzard**
fix the message

```
attempting to stop a stopped timer
```

caused by the fact the empty paths do not generate any pre/postPathEvent signal

### CODE REVIEW

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
The main effect of the fix is that the all_paths histograms should now properly be filled if there is at least one non-empty path.
The time spent in the unscheduled modules will be assigned to the Path or EndPath causing them to run, and enter the all_paths or all_endpaths plots accordingly.

**Comment by fwyzard** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
