### PR TITLE
Better handling of strings in ExternalGeneratorFilter [10_6]

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

Now handle case where strings have embedded \n which must be properly propagated to the external workers.
This was uncovered when I tried to convert an inefficient GEN job to use ExternalGeneratorFilter and it failed to parse.

#### PR validation:

A previously failing configuration now runs.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
Please test

**Comment by qliphy** [comment]
backport of #35611

**Comment by SiewYan** [comment]
please test

**Comment by qliphy** [comment]
@cms-sw/generators-l2  Any comment?

**Comment by SiewYan** [comment]
Its look good now!

**Comment by SiewYan** [comment]
+1

**Pull request merged**
