### PR TITLE
Adding PUPPI jets and METs to offline DQM

### PR DESCRIPTION
**Pull request by rseidita**
#### PR description:

Adding the PUPPI collection for both jets and METs to the offline DQM JetMET sequence, as presented [here](https://indico.cern.ch/event/1386418/#3-updates-on-puppi-for-dc).

#### PR validation:

```
echo '{
"369978" : [[1, 800]]
}' > step1_lumiRanges.log  2>&1

(dasgoclient --limit 0 --query 'lumi,file dataset=/JetMET0/Run2023D-v1/RAW run=369978' --format json | das-selected-lumis.py 1,800 ) | sort -u > step1_dasquery.log  2>&1

cmsDriver.py step2  --process reHLT -s L1REPACK:Full,HLT:@relval2023 --conditions auto:run3_hlt_relval --data  --eventcontent FEVTDEBUGHLT --datatier FEVTDEBUGHLT --era Run3_2023 -n 1000 --filein filelist:step1_dasquery.log --lumiToProcess step1_lumiRanges.log --fileout file:step2.root  --nThreads 8

cmsDriver.py step3  --conditions auto:run3_data_prompt_relval -s RAW2DIGI,L1Reco,RECO,PAT,NANO,DQM:@jetmet --datatier RECO,MINIAOD,NANOAOD,DQMIO --eventcontent RECO,MINIAOD,NANOEDMAOD,DQM --data  --process reRECO --scenario pp --era Run3_2023 --customise Configuration/DataProcessing/RecoTLR.customisePostEra_Run3 --hltProcess reHLT -n 1000 --filein  file:step2.root  --fileout file:step3.root  --nThreads 8

cmsDriver.py step4  -s HARVESTING:@jetmet --conditions auto:run3_data --data  --filetype DQM --scenario pp --era Run3_2023 -n 1000 --filein file:step3_inDQM.root --fileout file:step4.root
```

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Not a backport

### CODE REVIEW

**Comment by tjavaid** [comment]
please test

**Comment by rseidita** [comment]
@tjavaid I tried running the following workflows locally: 1001.4 1002.3 1002.4 1001.3 141.901 1001.2 1040.0 140.56 1000.0 1001.0 140.57 140.56 1003.0

Run successfully: 1001.4 1002.3 1002.4 1001.3 141.901 1001.2 1040.0

Fail because raw files are on tape:
- 140.56 RunHI2018 → [On tape](https://cmsweb.cern.ch/das/request?instance=prod/global&input=site+file%3D%2Fstore%2Fhidata%2FHIRun2018A%2FHIHardProbes%2FRAW%2Fv1%2F000%2F326%2F479%2F00000%2F0E2CC5D5-9D87-7348-9219-B00CD718C847.root)
- 140.57 RunHI2018Reduced → [On tape](https://cmsweb.cern.ch/das/request?instance=prod/global&input=site+file%3D%2Fstore%2Fhidata%2FHIRun2018A%2FHIMinimumBiasReducedFormat0%2FRAW%2Fv1%2F000%2F326%2F479%2F00000%2F55E14EDF-63DF-A94B-92EA-B4D23BD65BE4.root)
- 140.56 RunHI2018 → [On tape](https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fglobal&input=site+file%3D%2Fstore%2Fhidata%2FHIRun2018A%2FHIHardProbes%2FRAW%2Fv1%2F000%2F326%2F479%2F00000%2F0E2CC5D5-9D87-7348-9219-B00CD718C847.root)

Fail because DAS query at step0 fails:

- 1000.0 RunMinBias2011A → [DAS query](https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fglobal&input=file+dataset%3D%2FMinimumBias%2FRun2011A-v1%2FRAW+run%3D165121+site%3DT2_CH_CERN) in step0 fails
- 1001.0 RunMinBias2011A → [DAS query](https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fglobal&input=file+dataset%3D%2FMinimumBias%2FRun2011A-v1%2FRAW+run%3D165121+site%3DT2_CH_CERN) in step0 fails
- 1003.0 RunMinBias2012A → [DAS query](https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fglobal&input=file+dataset%3D%2FMinimumBias%2FRun2012A-v1%2FRAW+run%3D191226+site%3DT2_CH_CERN) in step0 fails

Assuming I'm testing the correct things, I don't see issues in the execution of the actual code. Please let me know if I'm looking in the wrong place

**Comment by AdrianoDee** [comment]
please test

**Comment by tjavaid** [comment]
please test

**Comment by AdrianoDee** [comment]
This is just to make public what we were discussing “in private” : )

The issue there is that you at the moment there’s any difference between JME DQM for HIon or pp, but this PR is introducing a discrepancy: namely you want to use PUPPI jets that are not defined in HIon conditions. So you need to change your modifications in order to be discarded in case of HIon run. So for example in 

https://github.com/cms-sw/cmssw/blob/1ebe746a84aa7254058310de88b7c75d5328ca54/DQMOffline/JetMET/python/jetAnalyzer_cff.py#L7-L10

You need to change to something like

```python
from Configuration.ProcessModifiers.pp_on_AA_cff import pp_on_AA

jetDQMAnalyzerSequence = cms.Sequence(jetDQMAnalyzerAk4CaloCleaned
                                      *jetDQMAnalyzerAk4PFUncleaned*jetDQMAnalyzerAk4PFCleaned
                                      *jetDQMAnalyzerAk4PFCHSCleaned
                                   ) #common pp and HI

_jetDQMAnalyzerSequenceWithPUPPI = cms.Sequence(jetDQMAnalyzerAk4CaloCleaned
                                      *jetDQMAnalyzerAk4PFUncleaned*jetDQMAnalyzerAk4PFCleaned
                                      *jetDQMAnalyzerAk4PFCHSCleaned*jetDQMAnalizerAk4PUPPICleaned
                                   ) #only for pp with PUPPI

(~pp_on_AA).toReplaceWith(jetDQMAnalyzerSequence, _jetDQMAnalyzerSequenceWithPUPPI) # if NOT HIon use PUPPI
```

**Comment by rseidita** [comment]
Thanks a lot @AdrianoDee, I will proceed like this

**Comment by AdrianoDee** [comment]
please test

**Comment by nothingface0** [comment]
@smuzaffar we noticed failures when histograms are uploaded to the Dev DQMGUI:

```
Using SSL private key /afs/cern.ch/user/c/cmsbuild/.globus/userkey.pem
Using SSL public key /afs/cern.ch/user/c/cmsbuild/.globus/usercert.pem
Uploading output:
visDQMUpload.py https://cmsweb.cern.ch/dqm/dev /pool/condor/dir_2749906/jenkins/workspace/compare-root-files-short-matrix/cms-bot/dqm-comparison/dqmComparisonOutput/pr/DQM_V0001_R000000001__RelVal_wf25_0_pr__CMSSW_14_1_X-PRcmssw_44336-62360__DQMIO.root
ERROR HTTP Error 403: Forbidden
Status code:  None
Message:      None
Detail:       None
```

Could it be an expired certificate?

Logs [here](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_14_1_X_2024-04-15-2300+35c537/62360/dqmBinByBinLog.log)

**Comment by tjavaid** [comment]
please test

- just to populate the bin-by-bin comparison plots, after certificate issues fix.

**Comment by AdrianoDee** [comment]
please test with https://github.com/cms-data/RecoBTag-Combined/pull/57

**Comment by tjavaid** [comment]
Hi @rseidita, @AdrianoDee , I am wondering whether [changes](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_14_1_X_2024-04-17-1100+35c537/62392/11634.0_TTbar_14TeV+2021/) to `WF 11634.0` are expected with this update? (see for [muons](https://cmsweb.cern.ch/dqm/dev/session/7Tq483) and [L1TEMU](https://cmsweb.cern.ch/dqm/dev/session/5B8yz6))

**Comment by rseidita** [comment]
Hi @tjavaid, I can't open the links apparently, did you use the "Link me" feature of the DQM GUI?

**Comment by rseidita** [comment]
Regardless, this PR only touches files in the `DQMOffline/JetMET` package, so no it should not affect anything in other workspaces as far as I know

**Comment by tjavaid** [comment]
Hi @rseidita , sure. Please consider corresponding links for [muons](https://tinyurl.com/2azncrex) and [L1TEMU](https://tinyurl.com/2d6mklg6) workspaces.

**Comment by rseidita** [comment]
Thanks @tjavaid, the links work now. Looking at the logs, I see that the difference is in the HLT results for some events:
```
Found 10 matching events, out of which 3 have different HLT results

      Events    Accepted      Gained        Lost       Other  Trigger
          10           9          +1          -2           -  Flag_ecalLaserCorrFilter
```
Could this be due to a change in ECAL laser corrections? My changes are entirely restricted to the JetMET offline DQM sequence, so I don't see how they can have anything to do with trigger results and/or the muon/L1T DQM sequence. Are we sure that the tests were run on exactly matching conditions?

**Comment by AdrianoDee** [comment]
Difference for `11634.0` are related to the specific IB used in the tests. See https://github.com/cms-sw/cmssw/issues/44779#issuecomment-2064828687.

**Comment by mandrenguyen** [comment]
urgent
DQM signaled that the 14_0_X backport of this (#44752) is needed for the next-data taking release at joint ops yesterday. 
If that's indeed the case, @cms-sw/dqm-l2 please review. 
- Matt (ORM)

**Comment by syuvivida** [comment]
+1

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
