### PR TITLE
Backport of POWHEG EmissionVeto1 updates

### PR DESCRIPTION
**Pull request by AndrewLevin**
This is a backport of my recent pull request https://github.com/cms-sw/cmssw/pull/24763 which updates the POWHEG EmissionVeto1 userhook for the WGamma special case. It was also necessary to backport the pull request https://github.com/cms-sw/cmssw/pull/23469/ since  https://github.com/cms-sw/cmssw/pull/24763 is built on top of https://github.com/cms-sw/cmssw/pull/23469. @grohsjea and @agrohsje, please check that I backported your pull request properly.

### CODE REVIEW

**Comment by efeyazgan** [comment]
please test

**Comment by efeyazgan** [comment]
+1

**Comment by AndrewLevin** [comment]
done

**Comment by fabiocos** [comment]
+1

**Pull request merged**
