### PR TITLE
Phase2-hgx233 Enable processing a full scenario

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

In dd4hep, the xml files are processed in order. So the scenario has to be selected accordingly. Also namespace is handled specially - change is needed to one of the plugins

#### PR validation:

Tested with some of the cfg's in test area. But it also needs some of the PR's which are waiting to be integrated to the IB

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
+1

**Comment by bsunanda** [comment]
@cvuosalo @kpedro88 With this, #29185 and Ianna's PR which enables vectors to be fully evaluated, we can go through some phase2 scenario. This will enable debugging implementation for HGCal

**Comment by kpedro88** [comment]
@bsunanda we should remember to propagate this to https://github.com/cms-sw/cmssw/blob/master/Configuration/Geometry/python/dict2026Geometry.py when the migration is complete

**Comment by kpedro88** [comment]
+upgrade

**Comment by silviodonato** [comment]
+1

**Pull request merged**
