### PR TITLE
Lmastrol hgc l1 calib upg jb

### PR DESCRIPTION
**Pull request by mastrolorenzo**
Added calibration for trigger cells + creation of the HGCalTriggerCellCalibration class and modification to the run member function to accomodate the EventSetup as input parameter + creation of the calib folder with an example of EDAnalyzer to run over the calibrated trigger cell collection

### CODE REVIEW

**Comment by lgray** [comment]
@mastrolorenzo This has a conflict with the base branch, you need to rebase.

@jbsauvan Wouldn't you want to integrate this internally (over on the private github) first?

**Comment by jbsauvan** [comment]
@lgray @mastrolorenzo Yes, this should be first integrated in our internal development branch.

@rekovic @mulhearn @davidlange6 Please ignore this PR.

**Comment by davidlange6** [comment]
please close it. Thanks

**Comment by lgray** [comment]
@mastrolorenzo You have to press the button at the bottom of this page to close it!

**Pull request closed without merging**
