### PR TITLE
RPC DQM: change merger input as default

### PR DESCRIPTION
**Pull request by minerva1993**
#### PR description:

As data from merger is default in Run3 (#37948), change in online DQM is required. Simply change 'AllHitsMerger' folder to 'AllHits' (default), and put legacy plots to 'AllHitsLegacy'.

#### PR validation:

Private validation
'cmsRun rpc_dqm_sourceclient-live_cfg.py inputFiles=438297ee-bc1f-4a5c-9a6c-bf4e6a427f8b.root', 50k events from Run 350561

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

None. To be backported on 12_4_X

### CODE REVIEW

**Comment by pmandrik** [comment]
please test

**Comment by pmandrik** [comment]
Hi, the release used at P5 at the moment for testing is CMSSW_12_3_X based

**Comment by minerva1993** [comment]
@pmandrik Hello, I'm aware of it. But the PR mentioned above was not backported to 123X thus it is not meaningful to create backport to 123X. (I can do it but it is really the matter of presentation)

**Comment by emanueleusai** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
