### PR TITLE
Delete alca legacy module types, cleanup

### PR DESCRIPTION
**Pull request by wddgit**
#### PR description:

Delete a couple of legacy type modules in alca code (part of a minor campaign to delete all references in CMSSW to legacy module types). These two files reference FWCore/Framework/interface/EDAnalyzer.h.

Neither of these two files could have compiled since January 2023 when we removed the headers. I am assuming they are not compiled. Upon cursory inspections these files look like ancient garbage.

CalibMuon/CSCCalibration/test/Compare_template.txt
* last substantive edits in 2011
* .txt suffix, supposed to be a template but you wouldn't want to copy and start from this
* cout's, weird ifstream I/O, getByLabel, no consumes
* All nontrivial work is in the constructor

CondFormats/CSCObjects/test/stubs/CSCGasGainCorrectionDBReadAnalyzer.c
* Not modified since initial commit in 2011
* 61 lines with no interesting content
* mostly cout, ofstream calls
* an EventSetup get without a consumes
* plugin name duplicates another plugin name and makes no sense "CSCChipSpeedCorrectionDBReadAnalyzer"

#### PR validation:

None necessary. Deletes files currently not compiled.

### CODE REVIEW

**Comment by wddgit** [comment]
please test

FYI @makortel

**Comment by francescobrivio** [comment]
+db

 - tests clean
 - technical cleanup, FYI @ptcox @cms-sw/csc-dpg-l2

**Comment by perrotta** [comment]
+alca

**Comment by rappoccio** [comment]
+1

**Pull request merged**
