### PR TITLE
Do not build/run cuda tests if cuda does not support gcc version

### PR DESCRIPTION
**Pull request by smuzaffar**
Follow up on https://github.com/cms-sw/cmssw/pull/24983

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by perrotta** [comment]
+1
- Technical, same as #24983
- Jenkins tests pass

**Comment by smuzaffar** [comment]
@fabiocos , can we get this

**Comment by fabiocos** [comment]
+1

**Pull request merged**
