### PR TITLE
Precise RPCTime in muons

### PR DESCRIPTION
**Pull request by jhgoh**
The RPCTime information is computed based on the bunch crossing x 25ns, not taking the precise timing information which is available from the phase-II upgrade.

With this PR, the RPCTime in the reco::Muon is computed using the precise time measurement if available.

@ptraczyk

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by perrotta** [comment]
In this PR the RPCTime is filled with the precise timing information if not
  hitRPC->timeError() < 0

If I read correctly, timeError is initialized to 0 in the RPCRecHit constructor (DataFormats/RPCRecHit/src/RPCRecHit.cc) and it is only modified if timeError>=0: https://cmssdt.cern.ch/lxr/source/RecoLocalMuon/RPCRecHit/src/RPCRecHitBaseAlgo.cc#0043

If so, the bx should never be used  here, not even for rpc in phase0/1: could you please check?

(If my observation is correct, I would expect this PR may affect also phase0/1 reco, and not only phase 2. On the other hand, I can't see any modification in jenkins outputs, not even for RPC in phase 2: could you please suggest me which distribution I should look at, and possibly also provide yourself here some evidence that this update behaves as you want, and does not affect current reco)?

**Comment by slava77** [comment]
On 5/15/17 3:58 AM, perrotta wrote:
> In this PR the RPCTime is filled with the precise timing information if not
> hitRPC->timeError() < 0
> 
> If I read correctly, timeError is initialized to 0 in the RPCRecHit
> constructor (DataFormats/RPCRecHit/src/RPCRecHit.cc) and it is only
> modified if timeError>=0:
> https://cmssdt.cern.ch/lxr/source/RecoLocalMuon/RPCRecHit/src/RPCRecHitBaseAlgo.cc#0043
> 
> If so, the bx should never be used here, not even for rpc in phase0/1:
> could you please check?
> 
> (If my observation is correct, I would expect this PR may affect also
> phase0/1 reco, and not only phase 2. On the other hand, I can't see any
> modification in jenkins outputs, not even for RPC in phase 2:

what about this
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_9_2_X_2017-05-09-2300+18681/19931/validateJR/all_OldVSNew_RunPhoton2012Bwf4p53/
?

**Comment by jhgoh** [comment]
@perrotta Thank you for checking details. I missed the point.
I'm updating this PR to set the default values of time and its error - time and its error are initialized to be (0,-1) by default.

-> Use bx based time if timeError < 0 (phase0/1)
-> Use precise time if timeError >= 0 (phase2)

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
Your latest commit is also going to affect (fix, I'd say...) validations:
https://cmssdt.cern.ch/lxr/source/Validation/RPCRecHits/src/RPCRecHitValid.cc#0545

In fact, that line was merged with #18632 five days ago, so probably nobody still checked its outcome. It would be interesting to see how the fix implemented here will act on RPC time plots (I expect that you get now some result different from 0 also for phase1/0)

**Comment by jhgoh** [comment]
The timing of RPCRecHits are new variables from 92X (91X backport is not merged yet). So, we did not have a chance to make comparisons yet.

What do I expect with this change in Phase1/0?
- Change of RPCRecHit::timeError(), always set to -1 (no RPC with precise timing, therefore all RPCRecHit should have the default value)
- No change in muons - RPC timing not used in tracking, identification.
- No change of muon::RPCTime(), this was always =25ns x bx. And even wit h this PR, this should remain same as before for phase1/0 since there's no RPC with precise timing therefore all RPCRecHits will have timeError<0 and it will just use (25ns x bx).

**Comment by perrotta** [comment]
With the latest fix, now RPC time only gets modified for Phase 2, e.g. (TTbar14TeV2023D4):
image

Corresponding entries remain unchanged in Phase1 RPC, as it should.

As expected, the DQM plots for RPC are modified also in Phase 1, but this is simply due to the bug fix applied here which avoids having all rpcTIme=0 at phase 1 (as it was after #18632, see above https://github.com/cms-sw/cmssw/pull/18681#issuecomment-301500383. Example for 10024.0_TTbar_13+TTbar_13TeV_TuneCUETP8M1_2017:
image

Thus everything goes as expected, now. 

I remain with only one doubt: does hitRPC->time() refer to an "absolute time" computed with respect to BX=0, or does it refer to the time diff with respect to hitRPC->BunchX() instead? 
I am asking because in the new distributions of rpcTIme I see only values close to 0 ns, while there are cases in which the BunchX() stays some N times 25 ns apart. If hitRPC->time() is the difference with the time of the corresponding BX, then probably BX times 25 should be added to it when computing
const double time = hitRPC->timeError() < 0 ? hitRPC->BunchX()*25. : hitRPC->time();

@jhgoh : could you please verify and let us know?

**Comment by jhgoh** [comment]
@perrotta thank you for comments and providing comparison plots.
The time from the RPCRecHit is absolute one. You can see timing distribution below, which gives peaks in every 25ns spacing:
screenshot
This plot was done using the pre3 ZMM relval sample with PU200, the time is directly taken from the RPCRecHit.

**Comment by perrotta** [comment]
+1
Given https://github.com/cms-sw/cmssw/pull/18681#issuecomment-301807525 and https://github.com/cms-sw/cmssw/pull/18681#issuecomment-301825570
Precise rpc timing is used, when available, instead of bx. It does not affect Phase0/1 reco

**Comment by davidlange6** [comment]
+1

**Pull request merged**
