### PR TITLE
[13_0_X] update relval matrix to add WFs for 2022E era

### PR DESCRIPTION
**Pull request by sunilUIET**
This PR adds 140.071-140.078 WFs for release validation that use 2022 era E data.

This is a backport of PR #41664

### CODE REVIEW

**Comment by sunilUIET** [comment]
test parameters:

workflows = 140.071,140.072,140.073,140.074,140.075,140.076,140.077,140.078
relvals_opt = -w standard

**Comment by sunilUIET** [comment]
please test

**Comment by sunilUIET** [comment]
+pdmv

**Comment by perrotta** [comment]
backport of https://github.com/cms-sw/cmssw/pull/41664

**Comment by srimanob** [comment]
+Upgrade

**Comment by perrotta** [comment]
@sunilUIET could you please create a backport also for the intermediate release 13_1_X?
We'll keep this PR in standby till that 13_1_X PR is made available, so that it won't be forgotten

**Comment by perrotta** [comment]
> @perrotta Here it is #41729

Thank you Sunil!

**Comment by perrotta** [comment]
+1

**Pull request merged**
