### PR TITLE
Fix return type in vid::CutFlowResult accessor (75X)

### PR DESCRIPTION
**Pull request by lgray**
Backport of  #10290

### CODE REVIEW

**Comment by lgray** [comment]
Can someone start test again here too? Thanks!

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@lgray, now you should be able to request the jenkins tests too. All you need is to write "please test" in the first line of your comment

**Comment by lgray** [comment]
@smuzaffar Thanks, I will use my new powers for good.

**Comment by monttj** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
