### PR TITLE
NanoAOD developments: 190508 version, part 1 for UL

### PR DESCRIPTION
**Pull request by peruzzim**
#### PR description:

This PR contains the developments accumulated so far for NanoAOD in 10_6_X, for UL and full Run2 analyses. No change is expected outside of NANOAOD content.

Main updates:
- Add low-pt jets to recalculate T1 MET correction (exc. uncertainties)
- Updated QGL, jet ID bits
- MET covariance and significance re-added
- New DeepBoostedJet training (V2), more discriminators stored
- Added DeepJet c-tagger
- Added gain of seed crystal for energy calibration studies and systematics
- New lepton MVA training for electrons and muons (using DeepJet)
- Pre-calculated L1 pre-firing weights
- Higgs simplified template cross sections re-added
- Bugfixes: correct trigger objects for 2016, added L1 trigger bit decisions, correct tau generator-level information

Depends on cms-sw/cmsdist#4937 for updated lepton MVA weights.

Further optimization (in particular, using some added content to 10_6_X MINIAOD instead of recalculating the same information) will come as a future PR, together with what depends on still-open items for the UL, and minor additions if available in time.

Please test all available NANOAOD workflows with #26672.

Includes a new feature (deactivated by default) in the JetCleanerForType1METT class, to produce a ValueMap with the muon-subtracted raw jet pt as it is used inside the T1 MET correction algorithm. This feature is used in NANOAOD production.

#### PR validation:

The base branch was tested in several releases as a part of the integration in the cms-nanoAOD repository, and in a subset of them for the branch merged with a recent IB.

### CODE REVIEW

**Comment by peruzzim** [comment]
A small note in view of backporting to 10_2_X: it has been checked that these developments can be backported, with obvious exceptions (e.g. L1 unprefireable bit), and identical results - with the exception of a muon ID flag that has to be recalculated on 80X datasets, and is calculated in a different way in 10_2_X and 10_6_X. This has nothing to do with nanoAOD code base, though.

**Comment by peruzzim** [comment]
please test with #26672 cms-sw/cmsdist#4937

**Comment by mrodozov** [comment]
please test with #26672, https://github.com/cms-data/PhysicsTools-NanoAOD/pull/5

**Comment by mrodozov** [comment]
please test with #26672, cms-sw/cmsdist#4937, cms-data/PhysicsTools-NanoAOD#5

**Comment by peruzzim** [comment]
please test workflow 1325.6,1325.7,1325.8,1329.1,136.7722,136.7952,136.8521 with #26672, cms-sw/cmsdist#4937, cms-data/PhysicsTools-NanoAOD#5

**Comment by peruzzim** [comment]
+xpog

runs for all NANOAOD validation workflows

**Comment by perrotta** [comment]
Which is the purpose within this PR of the modifications in  JetMETCorrections/Type1MET/interface/JetCleanerForType1METT.h, i.e. the calculation of  muon-subtracted raw pt? They are disbled by default, and they would also need a further addition to the event content to become effective, but I wonder how do they relate with the other nanoAOD related updates,
Please add a line in the PR description to explain it.

**Comment by peruzzim** [comment]
The feature is used in nanoAOD production to store that definition of raw pt for jets, so they can be used for T1 MET correction. I update the description.

**Comment by perrotta** [comment]
+1
- Changes in reco are limited to JetMETCorrections/Type1MET/interface/JetCleanerForType1METT.h:
  - Computation of raw pt for jets can be requested on demand
  - It is switched off for normal workflows, only enabled for nanoAOD production, see https://github.com/cms-sw/cmssw/pull/26703#issuecomment-491532774
- Jenkins tests pass and show no differences nor new products in reco or miniAOD outputs, as expected

**Comment by perrotta** [comment]
@smuzaffar FYI

There is a long list od header checks error. They are real but do not refer to this PR:
  - Usage of obsolete CommonTools/Utils/interface/deltaPhi.h in CommonTools/Utils/interface/MasslessInvariantMass.h
  - Usage of obsolete CommonTools/Utils/interface/deltaR.h in CommonTools/Utils/interface/MaxObjectPairSelector.h
  - Issues with DataFormats/Math/interface/AVXVec.h 
  - Non existent PhysicsTools/Utilities/interface/Math.h included in PhysicsTools/IsolationUtils/interface/CalIsolationAlgoNoExp.h and PhysicsTools/IsolationUtils/interface/TauConeIsolationAlgo.h
  - Issue with DataFormats/Candidate/interface/Candidate.h and DataFormats/Candidate/interface/VertexCompositePtrCandidate.h
  - CommonTools/UtilAlgos/interface/TFileDirectory.h is obsolete and to be removed
  - CommonTools/UtilAlgos/interface/ChargeSelector.h is obsolete and to be removed
  - Issue with SimG4Core/PhysicsLists/interface/G4Version.h 
  - Issues with OnlineDB/EcalCondDB/interface/FEConfigFgrEEStripDat.h and OnlineDB/EcalCondDB/interface/ITimeIOV.h
  - PhysicsTools/Utilities/interface/Likelihood.h: PhysicsTools/Utilities/interface/Selector.h has moved to PhysicsTools/SelectorUtil
  - Same in PhysicsTools/Utilities/interface/Product.h 
  - Issues with SimCalorimetry/CaloSimAlgos/interface/CaloVSimParameterMap.h 
  - Non-existent (since a while) ConvGaussZLineShape.h included in ElectroWeakAnalysis/ZMuMu/interface/ZMuTrackFunction.h
  - Wrong includes in Validation/EventGenerator/interface/TauDecay_GenParticle.h
  - ​CondFormats/​GeometryObjects/​interface/​GeometryFile.h should be removed, as well as all references to it in cmssw
  - FastSimulation/Utilities/interface/RandomEngine.h to be removed as obsolete
  - Non existent MCCandMatcher linked from PhysicsTools/HepMCCandAlgos/interface/MCTruthCompositeMatcher.h
  - Non existent CondCore/DBCommon/interface/Time.h linked from CondCore/PopCon/interface/VerifyState.h 
  - Remove obsloete CondFormats/Calibration/interface/EfficiencyPayloads.h and all references to it
  - Issues in CondFormats/SiPixelObjects/interface/SerializationManual.h
  - Non existent PhysicsTools/Utilities/interface/Math.h included in PhysicsTools/IsolationUtils/interface/CalIsolationAlgoNoExp.h
  - Remove usages of deprecated GenericJetfwd.h, BasicJetfwd.h, GenJetfwd.h
  - Remove usages of deprecated DF/BTau/JTA
  - Issues with DQMOffline/PFTau/interface/MatchCandidateBenchmark.h
  - Usage of non supported classes in JetMETCorrections/Modules/interface/JetCorrectionProducer.h
  - Non existent CommonTools/Utilities/interface/cutParser.h included in CommonTools/CandAlgos/interface/NamedCandCombiner.h
  - Issues with CommonTools/ParticleFlow/interface/TopProjectors.h
  - Issues with hysicsTools/UtilAlgos/interface/NullPostProcessor.h
  - Non existent EGamma/EGammaAnalysisTools/src/PFIsolationEstimator.cc included in PhysicsTools/UtilAlgos/interface/AdHocNTupler.h
  - Issues with SelectorUtils/interface/Expressions.h
  - Non existent ElectronVPlusJetsIDSelectionFunctor.h  included In PhysicsTools/PatUtils/interface/ElectronVPlusJetsIDSelectionFunctor.h
  - Issues with RecoVertex/LinearizationPointFinders/interface/GenericLinearizationPointFinder.h
  - Non existent WPlusJetsEventSelector.h used in PhysicsTools/PatExamples/interface/WPlusJetsEventSelector.h
  - Issues with RecoVertex/GhostTrackFitter/interface/AnnealingGhostTrackFitter.h
  - Issues with Alignment/MillePedeAlignmentAlgorithm/interface/MillePedeMonitor.h 
  - CondFormats/Serialization/interface/Equal.h:1:9: warning: #pragma once in main file

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Comment by santocch** [comment]
+1

**Comment by VinInn** [comment]
if 
```
Non existent CommonTools/Utilities/interface/cutParser.h included in CommonTools/CandAlgos/interface/NamedCandCombiner.h
```
and similar

does this means that 
```
CommonTools/CandAlgos/interface/NamedCandCombiner.h
```
is actually never references an shall be removed?

**Comment by perrotta** [comment]
> if
> 
> ```
> Non existent CommonTools/Utilities/interface/cutParser.h included in CommonTools/CandAlgos/interface/NamedCandCombiner.h
> ```
> 
> and similar
> 
> does this mean that
> 
> ```
> CommonTools/CandAlgos/interface/NamedCandCombiner.h
> ```
> 
> is actually never references an shall be removed?

See #26663

**Pull request merged**
