### PR TITLE
JPTJECbugfixV1

### PR DESCRIPTION
**Pull request by kodolova**
Corrections chain for JPT jets that used L1FastJetCalo as L1 offset corrections are modified. It uses now L1JPTOffsetCorrectorProducer with offsetService = cms.InputTag('ak4CaloL1FastjetCorrector').
ak4L1JPTFastjetCorrector is included in all JPT chains.

### CODE REVIEW

**Comment by ptcox** [comment]
Obviously shouldn't touch RecoLocalMuon/CSCRecHitD. Something wrong here??

________________________________

**Comment by kpedro88** [comment]
-1 needs rebase

**Comment by kpedro88** [comment]
-1
needs rebase

**Comment by kodolova** [comment]
I did not touch anything apart 3 files in JetMETCorrections/Configuration. Moreover I took only this package from repository and commit only these 3 files. All other happens while requests from different people are merged.

**Comment by abdoulline** [comment]
I guess for Olga would be even better to close this PR and to restart from scratch (recent 91X IB)...  
As far as can I see, the actual "JPT JEC with L1Fastjet" changes are relatively small...

**Comment by kodolova** [comment]
Following request I close this thread and reopen pul with CMSSW_9_1_X_2017-03-12-1100

**Pull request closed without merging**
