### PR TITLE
Fix collapsed status in HCAL topology

### PR DESCRIPTION
**Pull request by kpedro88**
#21842 unintentionally introduced some discrepancies in the 2018 "collapsed" workflow. The underlying problem is that `HcalTopology::withSpecialRBXHBHE()` is set by the underlying geometry, and since we use a geometry that allows collapsing for 2018, it is always true, even if the collapsing is not actually performed.

Instead, from now on we will use `HcalTopology::getMergePositionFlag()`, which can be set in Python. This parameter will be set by the same modifier that puts the RecHit combiner module into the HCAL local reco sequence.

This change is propagated to all necessary areas of the code. @abdoulline has confirmed that it works as expected for CaloTowers (with thresholds removed, since sometimes there can be weird threshold effects for collapsed vs uncollapsed RecHits): https://cms-cpt-software.web.cern.ch/cms-cpt-software/General/Validation/SVSuite/HCAL/calo_scan_single_pi/10_0_0/10_0_0_2018C_fixNocuts_vs_10_0_0_2018UC_fixNocuts_SinglePi/

@Martin-Grunewald for HLT, the parameter `process.HcalTopologyIdealEP.MergePosition` should be false by default, except for collapsed menus (2017 and 2018). What is the best way to specify this in the customization?

This PR will be backported to 100X.

attn: @bsunanda

### CODE REVIEW

**Comment by kpedro88** [comment]
please test

**Comment by kpedro88** [comment]
Comparison changes are only for 2018 MC workflow and are expected - the default workflow is uncollapsed, but topology was incorrectly being treated as collapsed, as noted in the PR description.

**Comment by slava77** [comment]
@kpedro88 

> You potentially added 30322 lines to the logs

please cleanup the debugs

**Comment by prebello** [comment]
+1

**Comment by prebello** [comment]
Hi @kpedro88,  so 2018 MC in 10_0_0 relval campaign focused on collapsed scenario will be affected. Would you expect changes in all distributions?

**Comment by Martin-Grunewald** [comment]
At this stage the HLT menus in 100 and 101 are 2018 only (with Fake menus not doing anything nor Hcal for 2017 and earlier). Hence please put the setting you want for 2018 for HLT!

**Comment by mariadalfonso** [comment]
@prebello 

The main impact is 15% difference in the tower 28 only for the non standard collapsed scenario
https://cms-cpt-software.web.cern.ch/cms-cpt-software/General/Validation/SVSuite/HCAL/calo_scan_single_pi/10_0_0/10_0_0_2018collapsed_vs_10_0_0_2018_SinglePi/Ratio.gif

The changes are not significant when looking the energy spectrum on the whole HE
The size can be seen comparing plots from @abdoulline
After the fix
https://cms-cpt-software.web.cern.ch/cms-cpt-software/General/Validation/SVSuite/HCAL/calo_scan_single_pi/10_0_0/10_0_0_2018collapsed_vs_10_0_0_2018_SinglePi/RecHits_energy_HE.gif
Before the fix
https://cms-cpt-software.web.cern.ch/cms-cpt-software/General/Validation/SVSuite/HCAL/calo_scan_single_pi/10_0_0/10_0_0_2018C_fixNocuts_vs_10_0_0_2018UC_fixNocuts_SinglePi/RecHits_energy_HE.gif

**Comment by kpedro88** [comment]
@slava77 whoops, didn't mean to commit that, fixed
@Martin-Grunewald done
@prebello actually it affects more the uncollapsed workflow (default for offline) - in some places it would have been incorrectly treated as collapsed

**Comment by kpedro88** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by kpedro88** [comment]
+1

**Comment by Martin-Grunewald** [comment]
+1

**Comment by jfernan2** [comment]
+1

**Comment by perrotta** [comment]
@kpedro88 : while looking at the jenkins tests outputs, I notice significant differences in the standard, "non-collapsed", 10824.0 TTbar 2018 workflow (even outside the HE region, by the way), e.g.:

image

Can you check and comment on it?

**Comment by kpedro88** [comment]
@perrotta the previous PR had some inconsistencies, but the problem actually started when we updated the geometry in the GT to use the collapsible version. The CaloTower plot changes (outside of 28/29) look like random fluctuations to me due to the change in HcalGeometry which could affect GEN-SIM.

**Comment by abdoulline** [comment]
@kpedro88, @perrotta

actually a single-pion test (one-Go from scratch) shows some randomness 
(with this branch=PR=fix) coming not at SIM, but rather at the DIGI 
level (see N_HO Digis plot) 
https://cms-cpt-software.web.cern.ch/cms-cpt-software/General/Validation/SVSuite/HCAL/calo_scan_single_pi/10_0_0/10_0_0_2018C_fix_vs_10_0_0_2018UC_fix_SinglePi/

**Comment by abdoulline** [comment]
Sorry for being too fast...  Kevin, you're right, there are small SimHits changes visible in the plots linked above...

**Comment by perrotta** [comment]
Thank you @kpedro88 and @abdoulline for the explanations.

I would have liked to check in the jenkins tests outputs of #21854 (the PR which supposedly exposed the bug fixed here) the change in shape witnessing the use of the collapsed scenario even for "standard" 2018 workflows. However, they already disappeared.

Therefore, I checked with one of the "collapsed" workflows the same eta distribution above of the CaloTowers, and I can verify that the collapsed distribution
calotowersorted_collapsed
does correspond to what is black in https://github.com/cms-sw/cmssw/pull/22001#issuecomment-361890870.

That confirms the issue, and the efficacy of the fix applied here.

**Comment by perrotta** [comment]
+1
- The fix recovers the "non-collapsed" geometry for the "standard" 2018 workflows
- Changes in jenkins outputs are consistent with that fix and with the random fluctuations due to the change in HcalGeometry which affects SimHits
- "Collapsed" workflows, not in the standard jenkins tests, were also tested to work

**Comment by fabiocos** [comment]
@prebello you had already signed it the pdmv part of the PR, so I understand that this is ok for you

**Comment by fabiocos** [comment]
merge

**Pull request merged**
