### PR TITLE
added esConsumes to modules in SimCalorimetry/ EcalEBTrigPrimProducers

### PR DESCRIPTION
**Pull request by JamminJones**
#### PR description:

added esConsumes to 1 module
#### PR validation:

the code compiles

### CODE REVIEW

**Comment by Dr15Jones** [comment]
this code change was done under my supervision

**Comment by Dr15Jones** [comment]
please test

**Comment by kpedro88** [comment]
+upgrade

**Comment by silviodonato** [comment]
merge
@rekovic

**Pull request merged**
