### PR TITLE
Migrate dqm & validation  plugins from Sioutertracker to Sitrackerphase2

### PR DESCRIPTION
**Pull request by sroychow**
#### PR description:
The motivation for the PR can be found in this [talk](https://indico.cern.ch/event/1242120/contributions/5230280/attachments/2579402/4449460/DQM_Tracker.pdf).
The basic idea is to move the plugins form
- ```DQM/SiOuterTracker```  to ```DQM/SiTrackerPhase2V```
- ```Validation/SiOuterTrackerV```   to ```Validation/SiTrackerPhase2V```
The  top level DQM folders have been renamed accordingly.

#### PR validation:
Wf 24834.0 runs.
#### If this PR is a backport please specify the original PR and why you need to 
Not a backport

### CODE REVIEW

**Comment by sroychow** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by tjavaid** [comment]
please test

**Comment by tjavaid** [comment]
+1

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
