### PR TITLE
New option to the ExternalLHEProducer to enable UNLOPS merging

### PR DESCRIPTION
**Pull request by yiiyama**
Following a presentation made at the Generator meeting in November: [Event](https://indico.cern.ch/event/746822/overview) and [Presentation](https://indico.cern.ch/event/746822/contributions/3168659/attachments/1745485/2825857/unlops.pdf)

We would like to merge multijet NLO samples using the UNLOPS scheme. Most of the infrastructure already exists in CMSSW. In the presentation I reported that we still need a new LHE parsing module that can read from multiple gridpacks (NLO and LO), but Josh pointed out that there is a feature in MG5_aMC@NLO that allows a creation of a single NLO/LO mixed gridpack (using directive [ LOonly=QCD ]), which means the existing ExternalLHEProducer suffices. The only feature we need is then to have `npLO` and `npNLO` correctly set in the LHEEvent. MG5_aMC@NLO does this only when `ickkw = 4`, but for processes such as gamma+jets, this option is not available.

The proposal with this PR is to enable the users of ExternalLHEProducer to specify the npLO and npNLO values by hand. These values simply correspond to the number of "j"s in the MG5 proc card, so they are uniquely determined by the process id (e.g. "0" in `p p > a j @0`). The process id is stored in IDPRUP of the HEPEUP block, so a simple map (IDPRUP -> (order, nparton)) created in the constructor  does the job.

The feature is optional and can be turned on by giving a VPSet in the job configuration
```
process.externalLHEProducer = cms.EDProducer("ExternalLHEProducer",
    args = cms.vstring('gridpack.tar.xz'),
    numberOfParameters = cms.uint32(1),
    nEvents = cms.untracked.uint32(100),
    outputFile = cms.string('cmsgrid_final.lhe'),
    scriptName = cms.FileInPath('GeneratorInterface/LHEInterface/data/run_generic_tarball_cvmfs.sh'),
    ## new option ##
    nPartonMapping = cms.VPSet(
        cms.PSet(
            idprup = cms.uint32(0),
            order = cms.string('NLO'),
            np = cms.uint32(0)
        ),
        cms.PSet(
            idprup = cms.uint32(1),
            order = cms.string('LO'),
            np = cms.uint32(1)
        )
    )
)
```

### CODE REVIEW

**Comment by qliphy** [comment]
adding @bendavid

**Comment by qliphy** [comment]
please test

**Comment by qliphy** [comment]
please test workflow 523.0, 551.0

**Comment by bendavid** [comment]
(Aside from this PR, it would be worth asking the madgraph authors to correctly set the npLO and npNLO tags also for other icckw modes, since I guess this is ~trivial for them and would simplify things for the future)

**Comment by yiiyama** [comment]
@bendavid Indeed. I will ask. Thanks!

**Comment by fabiocos** [comment]
@yiiyama @qliphy @efeyazgan @alberto-sanchez what are the plans for this PR?

**Comment by yiiyama** [comment]
I would like to have it merged. I did write a feature request to the MG5 authors but they were not really supportive of the idea of adding new attributes LHE produced in standard configurations, fearing that LHE parsers that people write would break.

**Comment by efeyazgan** [comment]
+1

**Comment by fabiocos** [comment]
+1

workflows 522.0 and 523.0 tested to pass smoothly

**Pull request merged**
