### PR TITLE
Prepare HLT for New Conditions needed by update of uGT Emulation

### PR DESCRIPTION
**Pull request by mulhearn**
ALCA/DB: you are of course welcome to look, but your sign-off here is not actually needed, you are seeing this only via smaller, separate PR #14201.  This PR can be rebased once you sign that PR!  

HLT:  This adds new ESProducers for (presently unused) new Conditions, which will be needed by the updated uGT emulator which provides bitwise correct emulation of all correlation conditions.

Please pre-emptively update the HLT configs to provide the ES content as in:

```
   L1Trigger/L1TGlobal/python/GlobalParameters_cff.py
```

This will have no effect currently, but having these conditions ready will mean that we can turn on the update to uGT with no change to HLT configs.  @fwyzard suggested this approach, which I believe is wise.

Note that the Prescales/Vetos ES object will _not_ be requested by uGT emulator when those are not re-emulated... so you should never need such a dummy producer in HLT configs.

### CODE REVIEW

**Comment by mulhearn** [comment]
@Martin-Grunewald please have a look, and let me know if you like this approach.

**Comment by Martin-Grunewald** [comment]
Hmm, you talk about ESProducers but refer only to one, L1TGlobalParamsESProducer.
What are the other ones needed in the HLT config?

It seems that one is more or less the same as the "old" StableParametersTrivialProducer.
Well, renaming is not progress; this stuff should come from the DB directly via the GT,
not as parameters of some renamed ES module.

IOW, sorry, but I do not like this approach.

**Comment by fwyzard** [comment]
I think this is moving forward because the new ESProducer uses CondFormats that will eventually come from the global tag, while the old one used CondFormats that could only be hardcoded.

**Comment by Martin-Grunewald** [comment]
No: for the HLT config, it is about the module and module parameters: so better change the old StableParametersTrivialProducer internally to use the new format (with fillDescriptions taking care of added parameters if any).

**Comment by mulhearn** [comment]
Its not a rename, the old condition was merely a copy of legacy format.  Once the hardware was more nailed down we able to produce the updated CondFormat.  They are similar but not one to one.

If you are happy to use defaulted parameters, I can work it that way instead.

We can simply deprecate that module once this is available in GT.  Its a fine solution too.

**Comment by mulhearn** [comment]
You will still need our updated HLTL1TSeed filter to use new DataFormat, but I already have that working and no config changes needed...

**Comment by Martin-Grunewald** [comment]
Ah, OK, great!

**Comment by fwyzard** [comment]
To make it clear, I am *not* happy with relaying on parameters hard-coded in C++.

**Comment by mulhearn** [comment]
To run the HLT addOn tests myself locally I guess should follow these instructions:
https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideGlobalHLT#Trigger_development_for_Run_2
e.g.:
```
...
cd HLTrigger/Configuration/test
./cmsDriver.csh              # if you want to execute the shell script which creates various ready-to-run cfg files
./runAll.csh all                # runs a series of test jobs - see the log files for your favorite trigger
```
or are there other instructions elsewhere?  Ideally I'd reproduce what Jenkins would do before locally...

**Comment by Martin-Grunewald** [comment]
You can run the addOn tests yourself: execute ```addOnTests.py```

**Comment by mulhearn** [comment]
Oh, nice!  Running now...

**Comment by davidlange6** [comment]
@mulhearn - is this now obsolete?

**Pull request closed without merging**
