### PR TITLE
Run3-hgx304 Replace cout with messagelogger statements in man classes of Geometry/CaloTopology

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

 Replace cout with messagelogger statements in man classes of Geometry/CaloTopology

#### PR validation:

Use the runTheMatrix test workflows and several cfg's in Geometry/CaloTopology/test

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
+1

**Comment by perrotta** [comment]
+1

**Comment by perrotta** [comment]
ping bot

**Pull request merged**
