### PR TITLE
Fixed slot number to read all slots up to 12

### PR DESCRIPTION
**Pull request by jfernan2**
Fix for bug in reading number of slots which prevented form reading last ones.

### CODE REVIEW

**Comment by jfernan2** [comment]
+1

**Comment by jfernan2** [comment]
This is needed for MWGR1.
Thanks

**Comment by fabiocos** [comment]
@jfernan2 sorry, why is the number hardcoded and the function is not giving back the correct value? Is this going to stay or a simple temporary patch?

**Comment by jfernan2** [comment]
The number is hardcoded because is the total number of slots present in DT chambers (12 sectors), so it is fixed. The function getnslots returns only the number of slots with data/hits. 
So, with previous code not all the sectors/slots were read despite they had data, but just the first nSlots...
This is going to stay, it is not a patch, sorry for the confusion.

**Comment by davidlange6** [comment]
this is for online dqm only? If not, it needs to be more flexible (and in any case documented)

**Comment by fabiocos** [comment]
@jfernan2 ok, but it might be advisable for code clarity to have it as a pre-declared parameter (which is what David is meaning, I guess)

**Comment by jfernan2** [comment]
I have updated to use the documented value from the unpacker.
Thanks

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
