### PR TITLE
ParticleLevelProducer: check for leptonic decays of tag particles

### PR DESCRIPTION
**Pull request by mseidel42**
#### PR description:

Adds lepton+neutrino daughters of jet tag particles (heavy hadrons) to allow for calculation and correction of semileptonic branching ratios.

#### PR validation:

Output is as expected:
```
root [3] Events->Scan("recoGenParticles_particleLevel_tags_TQAF.obj.m_state.pdgId_")
***********************************
*    Row   * Instance * recoGenPa *
***********************************
*        0 *        0 *       421 *
*        0 *        1 *      -421 *
*        0 *        2 *       521 *
*        0 *        3 *       431 * <-- this one decays leptonically
*        0 *        4 *       -13 * <-- decay product
*        0 *        5 *        14 * <-- decay product
```

Validated by @swertz to recover the Pythia 8 input BRs of B hadrons:

### CODE REVIEW

**Comment by SiewYan** [comment]
please test

**Comment by silviodonato** [comment]
please test

**Comment by qliphy** [comment]
@cms-sw/generators-l2  Can you have a look and sign?

**Comment by SiewYan** [comment]
Hi, its look good to me.

**Comment by SiewYan** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
