### PR TITLE
Validation/Geometry: Integrate geometry comparison to MaterialBudget.py

### PR DESCRIPTION
**Pull request by vargasa**
This set of commits only affects the plotting side of the module (i.e it doesn't touch the data itself). `TrackerMaterialBudgeComparison.C` functionality has been integrated into `MaterialBudget.py`, the main reason for these changes is to make things clearer and organized. 

* Every geometry ROOT file will have its geometry label and won't impose the renaming  of `_old` `_new` ambiguous labels previously used. That was always confusing after the third time testing geometry you never knew which one was `_old` and what exactly was `_new`. 

* Some reusable code on `MaterialBudget.py` has been collected into functions to avoid code redundancy. @rovere If you can do a review of this we will greatly appreciate it. 

* Some labels on the plots were restored to make it consistent with existent twiki documentation.

* Overlapping issues on previous plots were addressed.

For details please check commit description

### CODE REVIEW

**Comment by andrius-k** [comment]
please test

**Comment by cvuosalo** [comment]
+1

**Comment by andrius-k** [comment]
+1

**Comment by fabiocos** [comment]
@Dr15Jones @smuzaffar @davidlange6 I assume that the request of core signature comes from the proposed modification to the main ".gitignore" file proposed here. I am not sure whether we have a defined policy for this file, looking in the repository I see there are some of them specialized per package/directory:

https://cmssdt.cern.ch/lxr/search?%21v=CMSSW_10_4_X_2018-12-04-2300&_filestring=.gitignore&_string=

I would imagine that the use case of this PR could be managed by an ad-hoc ".gitignore" file in the Validation/Geometry/test directory, like we already have in

https://cmssdt.cern.ch/lxr/source/SimTracker/TrackerMaterialAnalysis/test/.gitignore

where the problem is very similar, probably it might be preferable to leave the main file untouched for general instructions and add specific changes to subdirectories where explicitly needed

**Comment by davidlange6** [comment]
I agree - the changes would better be placed in the individual package (where they will also be properly picked up when using cms-addpkg).

**Comment by fabiocos** [comment]
@vargasa could you please move the update to ".gitignore" into a new one in Validation/Geometry/test ? After this I think the PR is ready to go, and unblock the following one #25397

**Comment by vargasa** [comment]
@fabiocos Thanks for pointing it out. Addressed in latest commit

**Comment by andrius-k** [comment]
please test

**Comment by cvuosalo** [comment]
+1

**Comment by fabiocos** [comment]
+1

@andrius-k could you please sign it so as we move forward?

**Pull request merged**
