### PR TITLE
HLTL1MuonNoL2Selector fix to avoid the need of duplicating the class

### PR DESCRIPTION
**Pull request by folguera**
This is needed to avoid using filter-objects and hence duplicating this module for every different L1 seed.

### CODE REVIEW

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
@folguera can you add the second commit as in the 9.1.x PR ?

**Comment by folguera** [comment]
@fwyzard The code is identical, 91X had an intermediate commit with the commented lines I simply started from scratch for this PR instead of inheriting the history of the other branch.

**Comment by Martin-Grunewald** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
