### PR TITLE
[131X] use qScale in charge reweighting

### PR DESCRIPTION
**Pull request by tvami**
#### PR description:

See https://github.com/cms-sw/cmssw/pull/41623

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport of https://github.com/cms-sw/cmssw/pull/41623

### CODE REVIEW

**Comment by tvami** [comment]
backport of https://github.com/cms-sw/cmssw/pull/41623

**Comment by tvami** [comment]
test parameters:
  - workflow = 250202.184

**Comment by perrotta** [comment]
@cms-sw/simulation-l2 would you agree with having this in 13_1_0 so that it can be considered in the simulation campaigns to be opened with this release cycle? If so, please sign it.

**Comment by civanch** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
