### PR TITLE
Fixing neglected gen filters from HepMC renaming

### PR DESCRIPTION
**Pull request by kurtejung**
HepMC naming migration from commit (here: https://github.com/cms-sw/cmssw/commit/f719245b0f6537cf9b1de74fd1aa19d7d9a2d43b) neglected to rename the inputs to a few gen filters needed for HI production

Also pinging @mandrenguyen @yetkinyilmaz @bendavid

### CODE REVIEW

**Comment by govoni** [comment]
+1

**Comment by perrozzi** [comment]
@kurtejung please port this PR also to 81X and cross-reference it, thanks

**Comment by perrozzi** [comment]
also, I see that you only changed 3 filters. Did you check them all? If there are others that need this fix, may I very kindly ask you to change them all in one PR? That would be a great service for the whole GEN community, thanks

**Comment by kurtejung** [comment]
Most of the gen filters seem to already have this fix, e.g. https://github.com/cms-sw/cmssw/blob/CMSSW_8_0_X/GeneratorInterface/GenFilters/src/PythiaFilter.cc

Some of the filters clearly require the user to override the default settings (e.g. https://github.com/cms-sw/cmssw/blob/CMSSW_8_0_X/GeneratorInterface/GenFilters/src/MCLongLivedParticles.cc)  and others use the genParticles.

It may be good to go through these filters in a more systematic way and change all the default values of those that use a HepMC input to "generator::unsmeared" but I was afraid of breaking filters.  Please advise.

**Comment by kurtejung** [comment]
Maybe @wmtan can describe why only some of the gen filters default collections were renamed from "generator" to "generator : unsmeared"

**Comment by perrozzi** [comment]
as mentioned by George via mail, also
https://github.com/kurtejung/cmssw/blob/f9288b2da3c9dba45f9ecfbd3f8ad4a8010375c7/GeneratorInterface/GenFilters/src/PythiaMomDauFilter.cc#L14
should be checked

**Comment by kurtejung** [comment]
Please don't rerun tests yet - there are some build errors that need to be cleaned up - push was an accident

**Comment by kurtejung** [comment]
All gen filters (both HI and pp) should be updated to properly use the unsmeared HepMC collections now - can one of the managers run tests? Thanks.

**Comment by perrozzi** [comment]
please test

**Comment by perrozzi** [comment]
please port this PR also to 81X and cross-reference it, thanks

**Comment by perrozzi** [comment]
+1

**Comment by perrozzi** [comment]
corresponding PR in 81X here https://github.com/cms-sw/cmssw/pull/16331

**Comment by perrozzi** [comment]
hi @davidlange6, this should have gone to 8_0_22
sorry if there has been any miscommunication.
can it be merged asap? thanks

**Comment by davidlange6** [comment]
+1

**Comment by davidlange6** [comment]
as usual a note in the ORP is what will get your PRs merged…

**Comment by mandrenguyen** [comment]
@davidlange6 :  A note in the google doc or the twiki?  Can anyone add a note or is that only for those who sign?

**Comment by davidlange6** [comment]
anyone can add a note (though indeed the idea is that the signing areas take responsibility for knowing what code in their area is needed where...

**Pull request merged**
