### PR TITLE
Sensitive detectors update 7 

### PR DESCRIPTION
**Pull request by civanch**
This is the last PR for clean up of Geant4 sensitive detector classes. Only forward detectors are updated:

1) A new class TimingSD surves for common computations. Duplicated codes in several classes are removed, instead inheritance is used.
2) Comments of @VinInn are implemented in a good part
3) Improved debug printouts
4) removed unused headers, commented and empty lines

Run-1 and run-2 workflows are expected to be unchanged.

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by fabiocos** [comment]
@civanch I understand that this is the latest code migration you are planning for 10_2_X. Concerning the timing detectors, MtdSD was almost a clone of FastTimerSD, that should be dropped as soon as we get rid of the old scenario. Anyway I fear that many, if not all, of these SD are not really tested in the short matrix (for instance not MTD). Did you check offline the identity of the output? Is this expected?

In your communication you were also mentioning an issue with the order in which particles are processed in the timing detectors. Is this addressed as well or not in this PR?

**Comment by fabiocos** [comment]
partly answering myself, in 2018 the geometry includes ZDC, and scenario D21 probed in the matrix touches FastTimerSD

**Comment by civanch** [comment]
@fabiocos , I agree with your comment on usage and validation of forward SD. The reason of this clean-up is to reduce code duplication, which make a problem for newcomer and provoke copy/paste  of old code and propagation of old patterns from class to class. Forward SD classes , of course, do not affect CPU performance of situation but in this modification minor problems in hits are fixed, namely fastest particle is chosen for a hit, hit position and exit point of a hit is computed and filled correctly. The rest is pure technical - implementation of CMS code rules. This is the last general PR for developments for 10_2.

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
for timing detectors for Phase2 we may have a closer dedicated check later on, in any case that code is still under potential development

**Pull request merged**
