### PR TITLE
[HGCal] Updating HGCalValidator with SimHits, Digis, RecHits and MultiClusters

### PR DESCRIPTION
**Pull request by apsallid**
#### PR description:

This PR updates the HGCalValidator package to be able to handle: 

1. SimHits, Digis, RecHits (@tmengke, @deguio, @skunori)

As part of the Validation of campaigns regularly announced from PdmV and UPSG, we want to monitor and validate SimHits, Digis and Rechits objects. Usually, RelMon and DQM GUI is being used for this task. However, in order to quantify the performance of certain clustering algorithms or optimizing the same algorithm or checking different calibration algorithms or inspect the plots in the DQM file easier, we include in our webpage results from the above mentioned objects.

@bsunanda: This slightly touches the [HGCalSimHitValidation.cc](https://github.com/cms-sw/cmssw/blob/master/Validation/HGCalValidation/plugins/HGCalSimHitValidation.cc), [HGCalDigiValidation.cc](https://github.com/cms-sw/cmssw/blob/master/Validation/HGCalValidation/plugins/HGCalDigiValidation.cc), [HGCalRecHitValidation.cc](https://github.com/cms-sw/cmssw/blob/master/Validation/HGCalValidation/plugins/HGCalRecHitValidation.cc) by adding a zero to the names of the DQM histograms, so the results in our web page to be ordered by layer number. 

2. Multiclusters (@rovere, @felicepantaleo, @apsallid, @amartelli)

With the inclusion of TICL multiclusters in CMSSW being imminent, we update the HGCalValidator package with the capability of monitoring as well as associating MultiClusters wiith CaloParticles. In the HGCal webpage [1] there is a "Validation" section where we document and describe all the relevant plots. This is a first work based on the standard "hgcalMultiClusters" object that if needed will be refined in the very near future with the study of the TICL multiclusters. 

#### PR validation:

We tested locally that all objects plots are populated [2-4] and will continue the validation of the code as soon as TICL multiclusters are available.

#### if this PR is a backport please specify the original PR:

Not a backport.

[1] http://hgcal.web.cern.ch/hgcal/

[2] http://tmengke.web.cern.ch/tmengke/HGCHitValidation_front/

[3] http://apsallid.web.cern.ch/apsallid/HGCValidmulticlusters_testing/

[4] http://apsallid.web.cern.ch/apsallid/HGCValidlayerclusters_testing/

### CODE REVIEW

**Comment by kpedro88** [comment]
please test

**Comment by jfernan2** [comment]
@apsallid  You did an exhaustive validation of this PR, thank you!!
Could you please do a last check to see if everything looks as expected from the point of view of DQM GUI?
These are the differences spotted by the Bin by Bin tool, any phase2 workflow at the bottom shows the histograms removed and those added now (Please bear in mind that the number of 2D histos you are handling is huge and the rendering may take a while in the DQM GUI):
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_11_0_X_2019-06-24-2300+ce8454/32405/dqm-histo-comparison-summary.html

**Comment by apsallid** [comment]
Hi @jfernan2 ,
I checked and indeed I see the extra histos we added. To me it looks ok. There will be a 
meticulous recheck of the package when we will have the TICL multiclusters for sure.

**Comment by jfernan2** [comment]
+1
Thanks @apsallid  I understand these hundreds of new histos are placed there to check in case of problems in a particular region, but not actually used all of them in the Validation

**Comment by fabiocos** [comment]
+1

**Pull request merged**
