### PR TITLE
MTD geometry: update tests to scenario D95

### PR DESCRIPTION
**Pull request by fabiocos**
#### PR description:

In all (unit) test configurations used for MTD geometry scrutiny, the default scenario to be used is moved to D95, following the proposed update of the default for general tests. The test of the BTL RectangularMTDTopology is at the same time extended to probe the conversion from module to crystal reference frame.

This update requires also the update of the unit test reference files in ```cms-data/Geometry-TestReference```.

#### PR validation:

The code is running, and it has been used to produce the references. The additional test is showing no error.

### CODE REVIEW

**Comment by fabiocos** [comment]
please test with https://github.com/cms-data/Geometry-TestReference/pull/12

**Comment by bsunanda** [comment]
+geometry

**Comment by srimanob** [comment]
@cmsbuild please test

Let's make the clean PR test

**Comment by fabiocos** [comment]
please test with https://github.com/cms-data/Geometry-TestReference/pull/12

@srimanob withou the external update, the unit tests are bound to fail

**Comment by srimanob** [comment]
+Upgrade

**Comment by emanueleusai** [comment]
+1

**Comment by mandrenguyen** [comment]
+reconstruction

**Comment by fabiocos** [comment]
@cms-sw/orp-l2 please recall to merge in parallel the external https://github.com/cms-data/Geometry-TestReference/pull/12 at the time of the integration

**Comment by perrotta** [comment]
+1

**Pull request merged**
