### PR TITLE
HCAL CMT tool update for Run3

### PR DESCRIPTION
**Pull request by zhokin2**
Hcal certification monitoring tool (CMT) and corresponding CMT web site:
https://cms-conddb.cern.ch/eosweb/hcal/HcalRemoteMonitoring/CMT
are provided since 2013 for much easy and faster certification of lumi sections
 in global runs. 

 CMT preparation for Run3: full validation chain up to visualization on CMT site, including condor scripts running

### CODE REVIEW

**Comment by zhokin2** [comment]
these codes are prepared and tested in framework of CMT preparation for Run3

**Comment by silviodonato** [comment]
@zhokin2  you need to fix the code-checks as explained above

**Comment by silviodonato** [comment]
Please edit the title and description of this PR.

**Comment by zhokin2** [comment]
from dir. DPGAnalysis/HcalTools the compilation(scram b) is OK.

**Comment by zhokin2** [comment]
now the command used:
scram build code-format

after that, commited are:
   interface/CMTRawAnalyzer.h
   macros/cmt/RemoteMonitoringGLOBAL.cc
   macros/cmt/RemoteMonitoringMAP_Global.cc
   src/CMTRawAnalyzer.cc

**Comment by jfernan2** [comment]
@zhokin2  can you please add [HCAL] to tag to the PR title so that it can be easily classified and identified? Thanks

**Comment by zhokin2** [comment]
OK, HCAL is added to tag to the PR .
AZ
________________________________

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
@zhokin2  there is a CMSSW code rule error:
Rule1 : https://raw.githubusercontent.com/cms-sw/cmssw/master/Utilities/ReleaseScripts/python/cmsCodeRules/config.py
Search for "using namespace" or "using std::" in header files

/DPGAnalysis/HcalTools/interface/CMTRawAnalyzer.h
[12, 22]

**Comment by zhokin2** [comment]
OK, corrections done following Rule 1.
AZ
________________________________

**Comment by jfernan2** [comment]
please test

**Comment by abdoulline** [comment]
@zhokin2 
Please, don't use/keep branch name for PR title. 
The latter should be clear and possibly self-explanatory, while kept short. Something like this:  
HCAL CMT tool update. 
Could you modify it accordingly,  Alexandr ?

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
