### PR TITLE
Add check of Tracker HV in BeamSpot DQM clients

### PR DESCRIPTION
**Pull request by francescobrivio**
#### PR description:
In this PR a few improvements to the BeamSpot DQM clients are made:
- A check on the Tracker HV (both pixels and strips) is added in order not to run on events which are by construction not useful for the BeamSpot determination
   - This will alleviate the stress on the CondDB unfrastructure by reducing the number of "fake-failing" BeamSpot logs that are uploaded to the DB and that are monitored by the DB Experts on call (FYI @cms-sw/db-l2)
   - The HV check in the `beamhlt` client requires a change in the event content of the `streamDQMOnlineBeamspot` to include the raw data from FED 1022 _via_ a new `hltFEDSelectorOnlineMetaData` <br> This is being implemented by @missirol as described in [JIRA-CMSHLT-2464](https://its.cern.ch/jira/browse/CMSHLT-2464)
   - No additional changes are needed for the HV check in the `beam` client as the full raw data information is already available in the standard `streamDQM` event content
- An explicit printout of the Global Tag used by the client is added to the client logs
- A new `unitteststreamerinputsource_cfi.py` config file has been added for the specific cases where the unitTests are running on streamer files
   - Currently only the `beamhlt` DQM client is using this feature, but more clients could be adapted in the future
   - The new config allows to avoid querying DAS uselessly since the input streamer files are read from [cms-data/DQM-Integration](https://github.com/cms-data/DQM-Integration)
- A typo in the `LogInfo` printout of `RecoVertex/BeamSpotProducer/plugins/OnlineBeamSpotESProducer.cc` has been fixed

#### PR validation:
Code compiles plus successfully run:
```
scram b runtests_TestDQMOnlineClient-beam_dqm_sourceclient 
scram b runtests_TestDQMOnlineClient-beamhlt_dqm_sourceclient
```

#### Backport:
Not a backport but 12_5_X and 12_4_X backports will be opened soon.

FYI @gennai @dzuolo @mmusich @ggovi

### CODE REVIEW

**Comment by francescobrivio** [comment]
type performance-improvement

**Comment by francescobrivio** [comment]
@cms-sw/dqm-l2 please advise if you agree with the `unitteststreamerinputsource_cfi.py` name or if you prefer a different nomenclature.
Also, please let me know if you agree with the default options that are registered in this new config file.

**Comment by francescobrivio** [comment]
@cmsbuild please test

**Comment by francescobrivio** [comment]
@cms-sw/reconstruction-l2 just FYI the `reco` change here is only a typo in a `LogInfo` printout :D

**Comment by mandrenguyen** [comment]
+reconstruction
reco only triggered b/c a typo was fixed in a LogInfo

**Comment by tvami** [comment]
+alca

**Comment by perrotta** [comment]
+1

**Comment by syuvivida** [comment]
+1

**Pull request merged**
