### PR TITLE
SimG4: DD Direct Dependency Cleanup

### PR DESCRIPTION
**Pull request by ianna**
#### PR description:

* Move ```DDG4ProductionCuts``` class from ```SimG4Core/Physics``` package to ```SimG4Core/Geometry``` package to avoid direct dependency of the first on ```DetectorDescription/Core```. Only the latter should depend on ```DetectorDescription/Core```.

#### PR validation:

There is no code change - just move. The usual workflows should show no difference.

#### if this PR is a backport please specify the original PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
