### PR TITLE
fix vertex validation@HLT

### PR DESCRIPTION
**Pull request by mtosi**
while developing tracking @HLT for pixel phase1,
I realized that the vertex validation for HLT reconstruction was still using association map between offline quantities ...
this PR should fix it

### CODE REVIEW

**Comment by VinInn** [comment]
@cmsbuild , please test

**Comment by makortel** [comment]
Note that this (81X) PR conflicts with #14663 (which removes parameters `sigma_z_match` and `recoTrackProducer` as unused).

The effects of this bug should be (on the top of my head)
- all vertex plots using track<->TrackingParticle association should be empty
- in case vertex is associated to multiple TrackingVertices (by their position), and vice versa, the "best match" is not the intended one (the matches are ordered by the fraction of track<->TrackingParticle matches shared by vertex and TrackingVertex)

Especially e.g. the efficiencies and fake rates should be unaffected.

**Comment by makortel** [comment]
@mtosi 

I'm not planning to back-port in 80X (can be done if there is a need though). Your #14703 should be fine as it is for 80X.

I'm a bit hesitant to include these changes to #14663 because that PR does not introduce changes in validation plots while this one does, sorry. We could try to get it merged soon (only reco signature is missing) so that this PR could be rebased soon too.

**Comment by mtosi** [comment]
ok, thanks @makortel 
I'll wait for the conflict trigger, thus :P

**Comment by mtosi** [comment]
these errors are driven by the fact that one pretend to make a tracking and vertex validation @HLT while no reconstruction @HLT is done

**Comment by makortel** [comment]
Obviously we can't let the workflows to break. I think the problem is that in absence of `hltPixelTracks` collection, `tpToHLTpixelTrackAssociation` does not put anything to the event (intentionally, see https://github.com/cms-sw/cmssw/blob/CMSSW_8_1_X/SimTracker/TrackAssociation/plugins/TrackAssociatorEDProducer.cc#L90), and then `hltVertexAssociatorByPositionAndTracks` complains of the missing product (https://github.com/cms-sw/cmssw/blob/CMSSW_8_1_X/SimTracker/VertexAssociation/plugins/VertexAssociatorByPositionAndTracksProducer.cc#L71).

I can think of following options to fix the situation

1. Make `TrackAssociatorEDProducer` to return empty association collections in absence of input track collection
2. Make `VertexAssociatorByPositionAndTracksProducer` and `PrimaryVertexAnalyzer4PUSlimmed` resilient against missing collections (with a configuration flag in the spirit as in `TrackAssociatorEDProducer`)
3. We define a separate DQM/validation sequence for fake HLT menu (or does HLT DQM/validation with fake HLT menu sense in the first place?)

I would say option 1. would be the easiest/fastest fix, but I don't know if it has any unwanted consequences (given that the current behaviour was done on purpose in bf121bcd147e0e61648d241b0d7219db8f8e8440). What do others think?

**Comment by mtosi** [comment]
ciao
thanks @makortel for the details

my 2 cents are
it does not make any sense to me to have HLT validation (at least the tracking one) on a fake menu,
where no tracking is run
but for this I think one has to modify the matrix .... in the same place where the fake menu is set for the specific workflow, the validation sequence should be modify ....

between your point 1 and 2
I think VertexAssociatorByPositionAndTracksProducer is used only by the vertex validation (at least in CMSSW) and the same applies to the PrimaryVertexAnalyzer4PUSlimmed
=> a change in those should be transparent to others users
what is not clear to me is how to handle it (w/ the getByToken)

**Comment by davidlange6** [comment]
this looks obsolete - closing

**Comment by fwyzard** [comment]
As far as I know it is *not* obsolete. Please re-open and merge.

**Comment by makortel** [comment]
I agree we need to fix the HLT vertex validation as currently it is misbehaving a bit (https://github.com/cms-sw/cmssw/pull/14702#issuecomment-222661302).

Concerting the options to fix the failing workflows I outlined in https://github.com/cms-sw/cmssw/pull/14702#issuecomment-224204047, my personal feeling that option 3 would be the most correct solution, while option 2 would be the easiest "fix" (although I don't know any other reason than option 3 not being the case for need of options for "missing track collections").

**Comment by fwyzard** [comment]
>     We define a separate DQM/validation sequence for fake HLT menu (or does HLT DQM/validation with fake HLT menu sense in the first place?)

running the HLT DQM on workflows that use the fake HLT menu is completely meaningless; the DQM sequence should be adapted *not* to run any HLT-related validation in those workflows.

**Comment by davidlange6** [comment]
the PR doesn’t merge and has no action since weeks..Not much I can do to help there.

**Comment by perrotta** [comment]
@mtosi: could you please tell us if this PR is actually needed (and in that case: re-open and fix it), or if it is now obsolete (and therefore also close #14703 in 80X)?
Thank you, A.

**Comment by mtosi** [comment]
ciao
i'm on holiday
i'll work again on this when I'll be back

thanks
  mia

**Pull request closed without merging**
