### PR TITLE
Modify HG PCL Alignment movement histograms for use in the DQM GUI

### PR DESCRIPTION
**Pull request by mteroerd**
#### PR description:

This PR is in preparation of style changes for the movement histograms displayed in the DQM GUI. This includes the following changes:
- Fixing the order of labels in the status histogram to correctly match the variables
- Adding 5 Additional bins to each movement histogram. The first additional bin is empty, the other ones include cut values on movement threshold, significance, maximum error, and maximum movement. These can be read out in the DQM GUI.

#### PR validation:

Mille & Pede steps were execute to produce ROOT files usable by the DQM GUI. It was confirmed that the changes to the histograms are as intended.

Will probably have to be backported to 12_4_X.

### CODE REVIEW

**Comment by mmusich** [comment]
test parameters:
   * worklfow = 1001.2, 1001.3

**Comment by mmusich** [comment]
type trk, bug-fix

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by tvami** [comment]
urgent
 * backport should go into the next 12_4_X

**Comment by tvami** [comment]
I see this in the SA


Dead increment | /Alignment/MillePedeAlignmentAlgorithm/src/MillePedeFileReader.cc | initializeIndexHelper | 504 | 1 | View Report
-- | -- | -- | -- | -- | --


Dead increment	/Alignment/MillePedeAlignmentAlgorithm/src/MillePedeFileReader.cc	initializeIndexHelper	504	1	[View Report](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-4088c1/26372/llvm-analysis/report-c6096e.html#EndPath)

const_cast used on pointer to class	/Alignment/MillePedeAlignmentAlgorithm/src/PedeSteererWeakModeConstraints.cc	unknown	537	1	[View Report](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-4088c1/26372/llvm-analysis/report-88eec6.html#EndPath)

For a follow-up PR maybe @mteroerd  ?

**Comment by tvami** [comment]
+alca
 * tests pass, changes in 1001.2 are expected, the rest is MsgLogger and MTD 
 * some suggestions for a follow-up PR in https://github.com/cms-sw/cmssw/pull/38815#issuecomment-1191824021


<br class="Apple-interchange-newline">[1001.2](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_5_X_2022-07-21-1100+4088c1/51732/1001.2_RunZeroBias2017F+RunZeroBias2017F+TIER0EXPRUN2+ALCAEXPRUN2+ALCAHARVDSIPIXELCAL+ALCAHARVDSIPIXELCALLA+ALCAHARVD4+ALCAHARVDSIPIXELALIHG)

**Comment by tvami** [comment]
@mteroerd please prepare the 12_4_X backport, thanks!

**Comment by mmusich** [comment]
> const_cast used on pointer to class /Alignment/MillePedeAlignmentAlgorithm/src/PedeSteererWeakModeConstraints.cc unknown 537 1 [View Report](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-4088c1/26372/llvm-analysis/report-88eec6.html#EndPath)

@tvami please clarify what's the expected pattern here.  Thanks

**Comment by perrotta** [comment]
+1

**Comment by makortel** [comment]
> > const_cast used on pointer to class /Alignment/MillePedeAlignmentAlgorithm/src/PedeSteererWeakModeConstraints.cc unknown 537 1 [View Report](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-4088c1/26372/llvm-analysis/report-88eec6.html#EndPath)
> 
> @tvami please clarify what's the expected pattern here. Thanks

(@tvami asked via mattermost) I took a quick look on the `MomentumDependentPedeLabeler` and `RunRangeDependentPedeLabeler` (the only classes I found inheriting from `PedeLabelerBase`). Both classes use the argument `Alignable *` as an argument to two `std::map<Alignable *, X>::find()` (with different `X`). As far as I can tell, in both classes all uses of these two maps give only `const` access to the map elements (including the key). Therefore it seems to me that the two maps could be changed to `std::map<const Alignable *, X>` that would allow changing 
https://github.com/cms-sw/cmssw/blob/089a546286db311e407accd17bceeb3d9906725e/Alignment/MillePedeAlignmentAlgorithm/interface/PedeLabelerBase.h#L63-L65
to take `const Alignable *alignable` avoiding the `const_cast`.

**Comment by dmeuser** [comment]
> (@tvami asked via mattermost) I took a quick look on the `MomentumDependentPedeLabeler` and `RunRangeDependentPedeLabeler` (the only classes I found inheriting from `PedeLabelerBase`). Both classes use the argument `Alignable *` as an argument to two `std::map<Alignable *, X>::find()` (with different `X`). As far as I can tell, in both classes all uses of these two maps give only `const` access to the map elements (including the key). Therefore it seems to me that the two maps could be changed to `std::map<const Alignable *, X>` that would allow changing
> 
> https://github.com/cms-sw/cmssw/blob/089a546286db311e407accd17bceeb3d9906725e/Alignment/MillePedeAlignmentAlgorithm/interface/PedeLabelerBase.h#L63-L65
> 
> to take `const Alignable *alignable` avoiding the `const_cast`.

If I'm not mistaken, one would need change all `Alignable *` to `const Alignable *` in `PedeLabeler`, `MomentumDependentPedeLabeler`, `RunRangeDependentPedeLabeler`. This would in the end lead to problems when using the `alignableFromLabel` method in https://github.com/cms-sw/cmssw/blob/089a546286db311e407accd17bceeb3d9906725e/Alignment/MillePedeAlignmentAlgorithm/src/PedeReader.cc#L166
But maybe I am missing something.

**Comment by makortel** [comment]
Thanks, so I missed all code that actually needs non-`const` access to the `Alignable*`. My next suggestion would be to define an explicit Comparator class to use in the map type definition, along
```cpp
struct AlignableComparator {
    using is_transparent = void; // needs to be defined, actual type is not relevant
    bool operator()(Alignable* a, Alignable* b) const {
        return a < b;
    }
    bool operator()(Alignable* a, const Alignable* b) const {
        return a < b;
    }
    bool operator()(const Alignable* a, Alignable* b) const {
        return a < b;
    }
};

typedef std::map<Alignable *, unsigned int, AlignableComparator> AlignableToIdMap;
```
The important part is the `AlignableComparator::is_transparent` type alias, which is needed for `std::map::find()` to allow other argument types as long as they work together with the explicit Comparator (this feature was added for `std::map` in C++14, and for `std::unordered_map` in C++17). i have [here](https://godbolt.org/z/nxfYT8YT7) a toy example in Compiler Explorer.

But I'd like to add that a `const` member function returning a pointer-to-non-`const` object that is held in the member data of the class is a code smell. It is hard to tell without a deep analysis on the code (possibly extending to all alignment code) how `const`-correct these patterns are.

**Comment by dmeuser** [comment]
> Thanks, so I missed all code that actually needs non-`const` access to the `Alignable*`. My next suggestion would be to define an explicit Comparator class to use in the map type definition, along
> 
> ```c++
> struct AlignableComparator {
>     using is_transparent = void; // needs to be defined, actual type is not relevant
>     bool operator()(Alignable* a, Alignable* b) const {
>         return a < b;
>     }
>     bool operator()(Alignable* a, const Alignable* b) const {
>         return a < b;
>     }
>     bool operator()(const Alignable* a, Alignable* b) const {
>         return a < b;
>     }
> };
> 
> typedef std::map<Alignable *, unsigned int, AlignableComparator> AlignableToIdMap;
> ```
> 
> The important part is the `AlignableComparator::is_transparent` type alias, which is needed for `std::map::find()` to allow other argument types as long as they work together with the explicit Comparator (this feature was added for `std::map` in C++14, and for `std::unordered_map` in C++17). i have [here](https://godbolt.org/z/nxfYT8YT7) a toy example in Compiler Explorer.
> 
> But I'd like to add that a `const` member function returning a pointer-to-non-`const` object that is held in the member data of the class is a code smell. It is hard to tell without a deep analysis on the code (possibly extending to all alignment code) how `const`-correct these patterns are.

In https://github.com/cms-sw/cmssw/pull/38894 this should be fixed now.

**Pull request merged**
