### PR TITLE
HLT menu development for `14_0_X` (9/N) [`14_1_X`]

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

Development of HLT menus for CMSSW_14_0_X (branch CMSSW_14_1_X).
   * This is the PR for the master branch, which will then be backported down to 14_0_X (the latter is the release cycle currently used for Run-3 HLT-menu development).
   * This version of the GRun HLT menu corresponds to the list of updates to the **"V1.4"** (last) menu for the 2024 pp data-taking period.

This update includes the integration of the following JIRA tickets:
   * [CMSHLT-3224](https://its.cern.ch/jira/browse/CMSHLT-3224) [CSC] Update configuration of CSC-RecHit builder (Run2024)
   * [CMSHLT-3237](https://its.cern.ch/jira/browse/CMSHLT-3237) [ECAL] Remove hltGtStage2Digis from EvenContent of ALCAP0 and ALCAPHISYM streams
   * [CMSHLT-3238](https://its.cern.ch/jira/browse/CMSHLT-3238) [RPC] Remove digi/reco products from EvenContent of RPCMON stream
   * [CMSHLT-3239](https://its.cern.ch/jira/browse/CMSHLT-3239) [RPC] Unpack RPC from TwinMux+OMTF+CPPF FEDs
   * [CMSHLT-3241](https://its.cern.ch/jira/browse/CMSHLT-3241) [TSG] Remove "source" from EventContents of the HLT combined table
   * [CMSHLT-3245](https://its.cern.ch/jira/browse/CMSHLT-3245) [TAU] Fixing L2 Cut in VBF DiTau Monitoring Trigger
   * [CMSHLT-3264](https://its.cern.ch/jira/browse/CMSHLT-3264) [EXO,JME,SUS] Set PS=0 for HLT_PFMETNoMu110_PFMHTNoMu110_IDTight_FilterHF_v
   * [CMSHLT-3268](https://its.cern.ch/jira/browse/CMSHLT-3268) [DQM] DQMEventDisplay: replace HLT_ZeroBias_v with HLT_Physics_v
   * [CMSHLT-3269](https://its.cern.ch/jira/browse/CMSHLT-3269) [TSG] Split streams and datasets of SpecialHLTPhysics by 20
   * [CMSHLT-3270](https://its.cern.ch/jira/browse/CMSHLT-3270) [TRK] Set "SiStripClusterChargeCut" to "Loose" for tracks with pT<15 GeV (non-HIon menus)
   * [CMSHLT-3273](https://its.cern.ch/jira/browse/CMSHLT-3273) [L1T] Integration of CICADA Pass-Through Triggers
   * [CMSHLT-3274](https://its.cern.ch/jira/browse/CMSHLT-3274) [DQM] Update EventContent of DQM stream (post Run2024F)
   * [CMSHLT-3275](https://its.cern.ch/jira/browse/CMSHLT-3275) [DQM] Cleanup of EventContent of HLTMonitor stream (post Run2024F)
   * [CMSHLT-3276](https://its.cern.ch/jira/browse/CMSHLT-3276) [BPH] Increase splitting of ParkingSingleMuon PDs and streams from 8 to 12
   * [CMSHLT-3277](https://its.cern.ch/jira/browse/CMSHLT-3277) [MUO] Relaxed Muon Tracker Isolation cut
   * [CMSHLT-3278](https://its.cern.ch/jira/browse/CMSHLT-3278) [DQM] Use  general DQM modules for pixel rechits, tracks and vertices added in cmssw#45302
   * [CMSHLT-3280](https://its.cern.ch/jira/browse/CMSHLT-3280) [L1T] L1TGlobalProducer: new CICADA InputTag
   * [CMSHLT-3281](https://its.cern.ch/jira/browse/CMSHLT-3281) [HCAL] ALPAKA implementation of HCAL local reconstruction
   * [CMSHLT-3285](https://its.cern.ch/jira/browse/CMSHLT-3285) [Scouting] Set PS=0 for DST_PFScouting_SinglePhotonEB_v in "2p0E34_NoScouting" column
   * [CMSHLT-3288](https://its.cern.ch/jira/browse/CMSHLT-3288) [TRK] Update pixel doublet recovery iteration following the FPix1- issue
   * [CMSHLT-3289](https://its.cern.ch/jira/browse/CMSHLT-3289) [TSG] Adjust PSs for Ephemeral in "2p0E34+ZeroBias+HLTPhysics" column (2024F)
  * [CMSHLT-3292](https://its.cern.ch/jira/browse/CMSHLT-3292) [TSG] Prescale HLT_L1AXOVTight_v (L1T-2024_v1_3_0)
  
In addition, the following changes are included:
   * 916cab1fafa08c4afe7c7737c28346a034f5a2da: update of L1T FULL,GRun,2024v14,Special menus in TSG GTs to `L1Menu_Collisions2024_v1_3_0_xml`
   * 4bf8d069b7894d6ad9db2e09e0fe86be5048f87c: Preparation for next version of Special menus
   * 816e257ee1e8009e593cfe0c0ea07f0672ca9269: update of `hltPathOwners.json` for menu V1.4 (as per recent TSG survey)
   * 2a1af64a1880d9bd833f3dc64d7f829d2dcba443: Introduce 2024v1.4 frozen menu and remove 2024v1.3
  
#### PR validation:

TSG Integration tests

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Not a backport, but it will be backported to CMSSW_14_0_X.

### CODE REVIEW

**Comment by mmusich** [comment]
type hlt-integration

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
> -1 

failure is unrelated, see https://github.com/cms-sw/cmssw/pull/45419#issuecomment-2248914527

**Comment by mmusich** [comment]
ignore tests-rejected with ib-failure

**Comment by mmusich** [comment]
+hlt

**Comment by mmusich** [comment]
@cms-sw/orp-l2 we have more updates coming up after this, please merge at earliest convenience.

**Comment by mandrenguyen** [comment]
+1
I'm going to leave it to @rappoccio and @antoniovilela to merge into the production release, as I'm still getting up to speed.

**Pull request merged**
