### PR TITLE
Fix Tracker Alignment overlap validation

### LINKED ISSUE #39031: tk alignmen fix for overlap validation
Hello,

When running TkAlOverlapValidation.py, this problem pops up:

```
plot("/afs/cern.ch/cms/CAF/CMSALCA/ALCA_TRACKERALIGN2/data/commonValidation/results/venturaa/Collisions2022/overlap/OverlapValidationPlots/",subdet_ids,module_directions,overlap_directions,profile_directions,("root://eoscms.cern.ch//eos/cms/store/group/alca_trackeralign/AlignmentValidation/AlignmentValidation/Collisions2022/overlap/OverlapValidation_collisions_PCL_alignment.root", "PCL alignment", 1, 2001),
  File "/afs/cern.ch/cms/CAF/CMSALCA/ALCA_TRACKERALIGN/data/commonValidation/CMSSW_12_4_3/python/Alignment/OfflineValidation/overlapValidationPlot.py", line 202, in plot
    h = hist(files,files.replace("/",""),subdet_ids,module_directions,overlap_directions,profile_directions)
  File "/afs/cern.ch/cms/CAF/CMSALCA/ALCA_TRACKERALIGN/data/commonValidation/CMSSW_12_4_3/python/Alignment/OfflineValidation/overlapValidationPlot.py", line 29, in hist
    if subdetConditon(subdet,module,overlap):
NameError: name 'subdetConditon' is not defined
```

### PR DESCRIPTION
**Pull request by mmusich**
resolves https://github.com/cms-sw/cmssw/issues/39031

#### PR description:

As per suggestion at https://github.com/cms-sw/cmssw/issues/39031#issuecomment-1211958241

#### PR validation:

script compiles (notice that I need to include 98d8b945195d22288ca45c1c4ba8ce31f80e1972 in order to make it compile under python3)

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Not a backport, but needs to be backported

### CODE REVIEW

**Comment by tvami** [comment]
> script compiles (

can you please include that as a unit test? Or is the idea to have a PR that adds several unit test later?

**Comment by mmusich** [comment]
> can you please include that as a unit test? Or is the idea to have a PR that adds several unit test later?

Once https://github.com/cms-sw/cmssw/pull/38304 is integrated it will come from free.

**Comment by mmusich** [comment]
please test

**Comment by tvami** [comment]
+alca

**Comment by tvami** [comment]
type trk,bugfix

**Comment by qliphy** [comment]
+1

**Pull request merged**
