### PR TITLE
Added random particles to CloseByParticleGun generator

### PR DESCRIPTION
**Pull request by tonydp03**
#### PR description:

This pull request is made because we want to add, in the CloseByParticleGunProducer Workflow, the possibility to shoot a random number of particles (or a fixed one) chosen randomly from a vector of partIDs set in the snippet. In addition, the particles are shooted in random (phi,R) windows. Now in the configuration file the number of particles should be set, along with a boolean parameter (RandomShoot) which will be used in the producer to select either that number of particles or a random one in the range 1 - NParticles+1.
In addition, the working snippet in the Generators folder has been modified properly.

@rovere 
@felicepantaleo

### CODE REVIEW

**Comment by tonydp03** [comment]
Applied code checks.

**Comment by efeyazgan** [comment]
please test

**Comment by efeyazgan** [comment]
+1

**Review by fabiocos — COMMENTED** [review]
I have some comments about the use of random numbers that should be addressed before merging this PR

**Comment by fabiocos** [comment]
hold

**Comment by tonydp03** [comment]
Modified according to @fabiocos requests.

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
unhold

@tonydp03 thanks for updating the code, this addresses my problems
@efeyazgan @qliphy @alberto-sanchez it looks ok for me to go, if it was properly tested (not in this PR, there is no workflow probing it)

**Comment by qliphy** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
