### PR TITLE
[HeaderCheck][Reco] DataFormats/Math

### PR DESCRIPTION
**Pull request by mrodozov**
- Remove unused header

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by slava77** [comment]
this PR removes some code that's not marked as obsolete.
Why?

**Comment by mrodozov** [comment]
abort 
I didn't check properly lxr the files is used

**Comment by smuzaffar** [comment]
@mrodozov ,  this is not obsolete code. It is used when we have avx enabled builds. We need to add exception to headers checks to not fail for this or try using the correct flags.

**Pull request closed without merging**
