### PR TITLE
[101X][L1T][DQMOffline] Minor adjustments to Jets & energy sums plots

### PR DESCRIPTION
**Pull request by kreczko**
Backport of #23493

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by thomreis** [comment]
+1

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
Your PR is unmergeable. Please have a look and possibly rebase it.

**Comment by fabiocos** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by fabiocos** [comment]
@rekovic is this ok for you?

**Comment by rekovic** [comment]
+1

**Comment by thomreis** [comment]
Hi @kreczko 
since the T0 has moved to the 10_2 release now this PR can be closed.

**Pull request closed without merging**
