### PR TITLE
pr80x L1T GT packer of ExternalConditions

### PR DESCRIPTION
**Pull request by rekovic**
80X version of 90x #16794: Needed for HI MC production (80x).

Put back packing of ExternalConditions in packer GTSetup.
Configure default to use simGtExtFakeStage2Digis which is part of SimL1Emulator sequence by default.

Also fix L1REPACK:uGT configuration to use the same default ExtInputTag=simGtExtFakeStage2Digis.

### CODE REVIEW

**Comment by rekovic** [comment]
please test

**Comment by rekovic** [comment]
+1

**Comment by rekovic** [comment]
+1

**Comment by rekovic** [comment]
please test

**Comment by rekovic** [comment]
@davidlange6 This is all understood now.  Can merge.
HLT for p-p does not use BPTX (Externals) and Moriond 2017 MC Production was validated as OK
without the ExternalConditions packed.

**Comment by stahlleiton** [comment]
This PR is needed for the DIGI production of pA MC. Would be great if it could be merged as soon as possible.

**Comment by davidlange6** [comment]
please test

**Comment by rekovic** [comment]
@davidlange6 
At least the RelVal  test job  25202.0 step2 crashed due to problems opening input file (to MixingModule):

<pre>
%MSG-w XrdAdaptorInternal:  MixingModule:mix@ctor 24-Jan-2017 17:11:24 CET  pre-events
Failed to open file at URL root://cms-xrd-global.cern.ch:1094//store/relval/CMSSW_7_6_0_pre7/RelValMinBias_13/GEN-SIM/76X_mcRun2_asymptotic_v9_realBS-v1/00000/42571E6D-407C-E511-8246-0025905964BA.root?tried=+1213xrootd.ba.infn.it,+1213xrootd-redic.pi.infn.it,eoscms.cern.ch,eoscms-srv-m2.cern.ch,llrxrd-redir.in2p3.fr.
%MSG
24-Jan-2017 17:11:24 CET  Closed file file:step1.root
----- Begin Fatal Exception 24-Jan-2017 17:11:25 CET-----------------------
An exception of category 'FallbackFileOpenError' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing module: class=MixingModule label='mix'
   [2] Calling RootFileSequenceBase::initTheFile()
   [3] Calling StorageFactory::open()
   [4] Calling XrdFile::open()
Exception Message:
Failed to open the file 'root://cms-xrd-global.cern.ch//store/relval/CMSSW_7_6_0_pre7/RelValMinBias_13/GEN-SIM/76X_mcRun2_asymptotic_v9_realBS-v1/00000/42571E6D-407C-E511-8246-0025905964BA.root'
   Additional Info:
      [a] XrdCl::File::Open(name='root://eoscms.cern.ch//eos/cms/store/user/cmsbuild/store/relval/CMSSW_7_6_0_pre7/RelValMinBias_13/GEN-SIM/76X_mcRun2_asymptotic_v9_realBS-v1/00000/42571E6D-407C-E511-8246-0025905964BA.root', flags=0x10, permissions=0660) => error '[FATAL] Socket timeout' (errno=0, code=103)
      [b] Remote server already encountered a fatal error; no redirections were performed.
      [c] Input file root://eoscms.cern.ch//eos/cms/store/user/cmsbuild/store/relval/CMSSW_7_6_0_pre7/RelValMinBias_13/GEN-SIM/76X_mcRun2_asymptotic_v9_realBS-v1/00000/42571E6D-407C-E511-8246-0025905964BA.root could not be opened.
Fallback Input file root://cms-xrd-global.cern.ch//store/relval/CMSSW_7_6_0_pre7/RelValMinBias_13/GEN-SIM/76X_mcRun2_asymptotic_v9_realBS-v1/00000/42571E6D-407C-E511-8246-0025905964BA.root also could not be opened.
Original exception info is above; fallback exception info is below.
      [d] XrdCl::File::Open(name='root://cms-xrd-global.cern.ch//store/relval/CMSSW_7_6_0_pre7/RelValMinBias_13/GEN-SIM/76X_mcRun2_asymptotic_v9_realBS-v1/00000/42571E6D-407C-E511-8246-0025905964BA.root', flags=0x10, permissions=0660) => error '[ERROR] Operation expired' (errno=0, code=206). No additional data servers were found.
      [e] Last URL tried: root://cms-xrd-global.cern.ch:1094//store/relval/CMSSW_7_6_0_pre7/RelValMinBias_13/GEN-SIM/76X_mcRun2_asymptotic_v9_realBS-v1/00000/42571E6D-407C-E511-8246-0025905964BA.root?tried=+1213xrootd.ba.infn.it,+1213xrootd-redic.pi.infn.it,eoscms.cern.ch,eoscms-srv-m2.cern.ch,llrxrd-redir.in2p3.fr
      [f] Problematic data server: cms-xrd-global.cern.ch:1094
      [g] Disabled source: cms-xrd-global.cern.ch:1094
----- End Fatal Exception -------------------------------------------------
</pre>

**Comment by rekovic** [comment]
problems with eos ?

**Comment by rekovic** [comment]
please test

**Pull request merged**
