### PR TITLE
Modification to #11868 (configuring flat BS + DQM GUI)

### PR DESCRIPTION
**Pull request by mark-grimes**
This is a slight change to pull request #11868, where the `bsStudyStep1` and `bsStudyStep2` functions are merged into one `bsStudy` function, with `hasattr` guards to select the right parts.  This should make it easier to use.

I'll start the auto tests, but they don't use the new customisation functions so I've already tested privately with:

```
cmsDriver.py FourMuPt_1_200_cfi --conditions PH2_1K_FB_V6::All -n 10 --eventcontent FEVTDEBUG --relval 10000,100 -s GEN,SIM --datatier GEN-SIM --beamspot Flat --customise RecoParticleFlow/PandoraTranslator/customizeHGCalPandora_cff.cust_2023HGCalPandoraMuon,SLHCUpgradeSimulations/Configuration/combinedCustoms.customise_bsStudy_15 --geometry Extended2023HGCalMuon,Extended2023HGCalMuonReco --magField 38T_PostLS1 --no_exec --fileout file:step1.root
cmsDriver.py step2 --conditions PH2_1K_FB_V6::All -n 10 --eventcontent FEVTDEBUGHLT -s DIGI:pdigi_valid,L1,DIGI2RAW --datatier GEN-SIM-DIGI-RAW --customise RecoParticleFlow/PandoraTranslator/customizeHGCalPandora_cff.cust_2023HGCalPandoraMuon,SLHCUpgradeSimulations/Configuration/combinedCustoms.customise_bsStudy_15 --geometry Extended2023HGCalMuon,Extended2023HGCalMuonReco --magField 38T_PostLS1 --no_exec --filein file:step1.root --fileout file:step2.root
cmsDriver.py step3 --conditions PH2_1K_FB_V6::All -n 10 --eventcontent RECOSIM -s RAW2DIGI,L1Reco,RECO --datatier GEN-SIM-RECO --customise RecoParticleFlow/PandoraTranslator/customizeHGCalPandora_cff.cust_2023HGCalPandoraMuon,SLHCUpgradeSimulations/Configuration/combinedCustoms.customise_bsStudy_15 --geometry Extended2023HGCalMuon,Extended2023HGCalMuonReco --magField 38T_PostLS1 --no_exec --filein file:step2.root --fileout file:step3.root
```

(basically upgrade workflow 15600 but with `customise_bsStudy_15` customisation and the beamspot set to `Flat`).  And:

```
runTheMatrix.py -w upgrade -l 12200 --command="--beamspot Flat --customise SLHCUpgradeSimulations/Configuration/combinedCustoms.cust_2023HGCalMuon,SLHCUpgradeSimulations/Configuration/combinedCustoms.customise_bsStudy_15"
```

(`cust_2023HGCalMuon` has to be respecified, since the new customise command overrides the original).  Everything runs fine and the correct parameters are changed.

@boudoul

### CODE REVIEW

**Comment by mark-grimes** [comment]
please test

**Comment by boudoul** [comment]
looks great, thanks

**Comment by davidlange6** [comment]
Hi Mark - did you need more requests to finalize the SLHC release?

**Comment by mark-grimes** [comment]
merge

@davidlange6 no this is everything.  Sorry, got tied up with other things.  As soon as the bot merges this I'll put in the request.

**Pull request merged**
