### PR TITLE
Factorise PreSplitting configuration from InitialStep

### PR DESCRIPTION
**Pull request by rovere**
Completely factorize PreSplitting from InitialStep configuration, so that they can be tuned independently. Fix order of python import logic. No regression expected.

See also #10580

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@smuzaffar is this a broken IB as well?
Changes in this PR are not compatible with the errors.

**Comment by davidlange6** [comment]
yes, fallout from the duplicate plugins

**Comment by smuzaffar** [comment]
yes it is a broken IB. 
13h00 IB is being build to fix this.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
+1

For #10583 a49367c40e414e7239ba35df38695b845caecc96

For Tracking, factorizing PreSplitting configuration from the InitialStep. This code improvement to facilitate tuning should have no effect on monitored quantities. The 76X version of this PR, #10580, has already been approved by Reco.

The code changes are satisfactory, and Jenkins tests against baseline CMSSW_7_4_X_2015-08-05-2300 show no significant differences, as expected. Correct inclusion of the code change into the config was verified for #10580.

**Comment by slava77** [comment]
@rovere @VinInn 
is this PR essential for 74X?

**Comment by rovere** [comment]
@slava77 
strictly speaking it is not essential, but nice to have. Not a big deal if it's not either.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
