### PR TITLE
TRK PR #13062 redone (bug fixes, typos, remove existsAs etc.) to make it mergable (80X)

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
TRK PR #13062 redone (bug fixes, typos, remove existsAs etc.) to make it mergable (80X).
Based on CMSSW_8_0_X_2016-02-01-2300

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
This PR has only 21 files changed as opposed to 22 files in #13062,
but I believe the one file is simply the same change as already
integrated with https://github.com/cms-sw/cmssw/pull/13055

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
@mtosi 
Runtime errors - didn't you test your PR?

**Comment by Martin-Grunewald** [comment]
@mtosi 
customizeHLTfor2016trackingTemplate.py creates runtime errors for the PIon and PRef menus,
probably you tested only GRun?

```
Creating HLT PIon_MC
HLT:PIon,ENDJOB
entry file:RelVal_Raw_PIon_MC.root
 ################################################################### 
 # WARNING: this module is deprecated.                             # 
 # Please use CondCore.CondDB.CondDB_cfi.py                        # 
 ################################################################### 
Step: HLT Spec: ['PIon']
Traceback (most recent call last):
  File "/afs/cern.ch/cms/sw/ReleaseCandidates/vol0/slc6_amd64_gcc493/cms/cmssw/CMSSW_8_0_X_2016-02-01-2300/bin/slc6_amd64_gcc493/cmsDriver.py", line 55, in <module>
    run()
  File "/afs/cern.ch/cms/sw/ReleaseCandidates/vol0/slc6_amd64_gcc493/cms/cmssw/CMSSW_8_0_X_2016-02-01-2300/bin/slc6_amd64_gcc493/cmsDriver.py", line 27, in run
    configBuilder.prepare()
  File "/afs/cern.ch/cms/sw/ReleaseCandidates/vol0/slc6_amd64_gcc493/cms/cmssw/CMSSW_8_0_X_2016-02-01-2300/python/Configuration/Applications/ConfigBuilder.py", line 2058, in prepare
    self.addStandardSequences()
  File "/afs/cern.ch/cms/sw/ReleaseCandidates/vol0/slc6_amd64_gcc493/cms/cmssw/CMSSW_8_0_X_2016-02-01-2300/python/Configuration/Applications/ConfigBuilder.py", line 741, in addStandardSequences
    getattr(self,"prepare_"+stepName)(sequence = '+'.join(stepSpec))
  File "/afs/cern.ch/cms/sw/ReleaseCandidates/vol0/slc6_amd64_gcc493/cms/cmssw/CMSSW_8_0_X_2016-02-01-2300/python/Configuration/Applications/ConfigBuilder.py", line 1549, in prepare_HLT
    self.loadAndRemember('HLTrigger/Configuration/HLT_%s_cff'       % sequence)
  File "/afs/cern.ch/cms/sw/ReleaseCandidates/vol0/slc6_amd64_gcc493/cms/cmssw/CMSSW_8_0_X_2016-02-01-2300/python/Configuration/Applications/ConfigBuilder.py", line 323, in loadAndRemember
    self.process.load(includeFile)
  File "/afs/cern.ch/cms/sw/ReleaseCandidates/vol0/slc6_amd64_gcc493/cms/cmssw/CMSSW_8_0_X_2016-02-01-2300/python/FWCore/ParameterSet/Config.py", line 511, in load
    module = __import__(moduleName)
  File "/scratch/CMS2/CMSSW_8_0_X_2016-02-01-2300/python/HLTrigger/Configuration/HLT_PIon_cff.py", line 8967, in <module>
    fragment = customizeHLTforCMSSW(fragment,"PIon")
  File "/scratch/CMS2/CMSSW_8_0_X_2016-02-01-2300/python/HLTrigger/Configuration/customizeHLTforCMSSW.py", line 66, in customizeHLTforCMSSW
    process = customiseFor2016trackingTemplate(process)
  File "/scratch/CMS2/CMSSW_8_0_X_2016-02-01-2300/python/HLTrigger/Configuration/customizeHLTfor2016trackingTemplate.py", line 664, in customiseFor2016trackingTemplate
    process = new_selector(process)
  File "/scratch/CMS2/CMSSW_8_0_X_2016-02-01-2300/python/HLTrigger/Configuration/customizeHLTfor2016trackingTemplate.py", line 524, in new_selector
    iter02seq.insert( iter02seq.index( iter1HP ), iter1merge )
  File "/afs/cern.ch/cms/sw/ReleaseCandidates/vol0/slc6_amd64_gcc493/cms/cmssw/CMSSW_8_0_X_2016-02-01-2300/python/FWCore/ParameterSet/SequenceTypes.py", line 296, in index
    return self._seq.index(item)
  File "/afs/cern.ch/cms/sw/ReleaseCandidates/vol0/slc6_amd64_gcc493/cms/cmssw/CMSSW_8_0_X_2016-02-01-2300/python/FWCore/ParameterSet/SequenceTypes.py", line 175, in index
    return self._collection.index(item)
ValueError: cms.EDProducer("TrackCollectionFilterCloner",
    cloner = cms.untracked.PSet(
        copyExtras = cms.untracked.bool(False),
        copyTrajectories = cms.untracked.bool(False)
    ),
    minQuality = cms.string('highPurity'),
    originalMVAVals = cms.InputTag("hltIter1PFlowTrackCutClassifierMerged","MVAValues"),
    originalQualVals = cms.InputTag("hltIter1PFlowTrackCutClassifierMerged","QualityMasks"),
    originalSource = cms.InputTag("hltIter1PFlowCtfWithMaterialTracks")
)
 is not in list
```

**Comment by mtosi** [comment]
yes, I tested
but also the error message in the cmsbuild is weird !
I tested that all "MaxDispacement" instances were replaced by
"MaxDisplacement"
 mia

**Comment by mtosi** [comment]
there is an other issue
 OnLine_HLT_FULL.py has now MaxDispacement ...

do you know how I can replace that string ?
 mia

**Comment by Martin-Grunewald** [comment]
All HLT menus still have ```MaxDispacement```; it is not suffiecient to add the new ```MaxDisplacement```, one also needs to remove the old ```MaxDispacement```
in the customisation part!

**Comment by Martin-Grunewald** [comment]
@mtosi 
see most recent commit - for now I have removed the call to the 2016 function!

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
@mtosi 
This is a nightmare! How about these errors:
```
DQMStore: MultiThread option is enabled
02-Feb-2016 18:38:54 CET  Initiating request to open file file:RelVal_Raw_PRef_\
MC.root
02-Feb-2016 18:38:54 CET  Successfully opened file file:RelVal_Raw_PRef_MC.root
02-Feb-2016 18:38:58 CET  Closed file file:RelVal_Raw_PRef_MC.root
----- Begin Fatal Exception 02-Feb-2016 18:38:58 CET-----------------------
An exception of category 'Configuration' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing module: class=SeedGeneratorFromRegionHitsEDProducer label='\
hltPAIter1PixelSeeds'
Exception Message:
MissingParameter: Parameter 'useMultipleScattering' not found.
----- End Fatal Exception -------------------------------------------------
```

or this one

```
DQMStore: MultiThread option is enabled
02-Feb-2016 18:29:30 CET  Initiating request to open file file:RelVal_Raw_HIon_\
MC.root
02-Feb-2016 18:29:31 CET  Successfully opened file file:RelVal_Raw_HIon_MC.root
02-Feb-2016 18:29:34 CET  Closed file file:RelVal_Raw_HIon_MC.root
----- Begin Fatal Exception 02-Feb-2016 18:29:34 CET-----------------------
An exception of category 'Configuration' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing module: class=PixelTrackProducer label='hltHIPixel3PrimTrac\
ksForGlobalPt8'
Exception Message:
MissingParameter: Parameter 'useFakeVertices' not found.
----- End Fatal Exception -------------------------------------------------
```

**Comment by Martin-Grunewald** [comment]
Missing parameters should be automatically inserted if there is a proper fillDescriptions.
Otherwise, we need to add them in the custom file!

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
@mtosi 
Please check whether my recent commits in the std. custom file make "physics" sense!
The 2016 file is still disabled and needs a fix.

**Comment by Martin-Grunewald** [comment]
+1
please consider for pre6!

**Comment by Martin-Grunewald** [comment]
@slava77 
please have a look (for pre6)

**Comment by Martin-Grunewald** [comment]
@mtosi 
The idea would be to get THIS (with the C++ code changes) into pre6,
and then do the 2016 tk update (python only) , once working, in another PR.

**Comment by slava77** [comment]
@Martin-Grunewald 
this topic was originally reviewed by @cvuosalo 

I looked at the jenkins diffs: there is nothing in reco, but run2 data and MC HLT have changes in iterative tracking plots (track parameters and also in SiStrip plots likely triggered by changes in on-demand unpacked clusters). Are the changes in HLT expected?

**Comment by mtosi** [comment]
if we are making use of the tracking@HLT for 2016
these changes are expected

the strip related ones (@HLT) should be on the on/off tracks distributions
because the reconstructed tracks are slightly different
 mia

**Comment by cvuosalo** [comment]
+1

For #13164 5ff6f7c3a1e33cc3b4808676f61270993c469326

Small bug fixes and clean-up of the tracking code.

The code changes are satisfactory. Jenkins [tests](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-13164/10965/summary.html) against baseline CMSSW_8_0_X_2016-02-02-2300 show numerous, tiny, insignificant differences in the DQM plots related to HLT tracking and SiStrips. These differences are expected, as discussed above.

**Comment by Martin-Grunewald** [comment]
@mtosi 
The 4 modules have the parameter=True already in the config, so no need for special treatment
(```if hasattr``` is checking this)

**Comment by Martin-Grunewald** [comment]
@davidlange6
please integrate for pre6.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
