### PR TITLE
Updating MET Significance Parameters with 80X Run2016 tune

### PR DESCRIPTION
**Pull request by danbarto**
Updating the parameters for MET Significance with the latest tune (as used in JME-17-001).

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
@danbarto Can you provide a link to the studies/presentations that lead to these new parameters?

**Comment by danbarto** [comment]
@perrotta Results are presented in JME-17-001. You can find a presentation from the JetMET workshop here: https://indico.cern.ch/event/639724/contributions/2593794/attachments/1459666/2254181/METSig_JMEWorkshopHelsinki.pdf

**Comment by perrotta** [comment]
This PR updates the patMET significance in all workflows, see e.g. RunSinglePh2017B wf 136.788 from jenkins:
image

The (almost one year old) slides linked in https://github.com/cms-sw/cmssw/pull/22315#issuecomment-368528035 do not show the improvement with respect to what was the previous tune, unless it was what in the slides is labelled as "pure MET". Therefore, let ask for a POG endorsement through the MET reco contacts:  @gouskos @jdamgov 

Moreover: this "Run2016 tune" is applied to all data, older and newer that 2016: is it correct?

**Comment by gouskos** [comment]
Hi @perrotta, the comparison in these slides is vs "pure MET". The MET significance parameters in this PR are the latest we have in the MET group using the 2016 data. These are consistent with the ones used for the results presented in the run 2 paper [preapproved]. We will prepare a recipe so users can update the parameters on the fly., but the ones currently in miniAOD are quite old.

**Comment by perrotta** [comment]
+1
- MET significance parameters updated in miniAOD following the latest prescriptions of the MET group

**Comment by fabiocos** [comment]
+1

**Pull request merged**
