### PR TITLE
Mtd parameters update for D49 and D60 geometries (Bug fix)

### PR DESCRIPTION
**Pull request by parbol**
#### PR description:

This PR fixes a bug introduced by https://github.com/cms-sw/cmssw/pull/33340, affecting the D49 and D60 geometries. That PR reinterpreted the numbers in the BTL and ETL number vectors in the mtdParameters.xml file as interpad/and pad-to-border distances to define the dead areas around the pads, however the change was not made for the mtdParameters.xml being used by the D49 and D60 geometries. This PR updates also those numbers setting the distances as "0" to exactly reproduce the behaviour of the D49 and D60 geometries.

### CODE REVIEW

**Comment by fabiocos** [comment]
please test

minor effects expected

**Comment by fabiocos** [comment]
@parbol changes as naively expected I would say. The numbers incorrectly used as microns describing a gap were all quite small.

**Comment by parbol** [comment]
@fabiocos Yes, I think this is the expected behaviour.

**Comment by cvuosalo** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

**Comment by qliphy** [comment]
+1

**Comment by fabiocos** [comment]
This fix was already in #33598 , anyway this can be merged earlier. It would be useful for consistency to get it in 11_3_X in case someone wants to use D49, in order to avoid small but non properly defined differences with earlier versions.

**Pull request merged**
