### PR TITLE
another apptainer workaround [12_6_X]

### PR DESCRIPTION
**Pull request by kpedro88**
backport of #45652

### CODE REVIEW

**Comment by kpedro88** [comment]
please test

**Comment by makortel** [comment]
Not signing this one yet in the hope that we can close the 12_6_X release cycle

**Comment by makortel** [comment]
-heterogeneous

We'll stop building 12_6_X (https://github.com/cms-sw/cmssw/issues/45763#issuecomment-2326126188)

**Comment by makortel** [comment]
@cmsbuild, please close

**Pull request closed without merging**
