### PR TITLE
Code-cleanup of RPC-DQM

### PR DESCRIPTION
**Pull request by jhgoh**
#### PR description:
This PR updates current RPC DQM codes to have better code structure and modernize C++ syntax.
We'd like to have some advantage for the possible new developments.
The amount of code change in this PR is big, but they are technical ones - we don't expect any change in the output.

**1. Better helper class design for the chamber naming, histogram decoration.**
There is a class 'RPCGeomServ' which is widely used to map RPCDetId to the RPC nomenclature such as RB#in/out_W#_S##_B/F/M etc. This class stores flags as private member variables during some function calls, therefore developers could not declare it as const object.
There is another object rpcdqm::utils mainly used to set the axis labels. (and the name of the class is too generic).

We add a lightweight interface, RPCNameHelper, RPCSummaryMapHisto and RPCRollMapHisto, hopefully replace RPCGeomServ and rpcdqm::utils.
For the smooth and transparent migration (+ there are some items still to go), existing classes are kept for now.

**2. Migration to fmt::format()**
std::stringstream have been massively used in the RPC DQM modules. 
Existing code works without any problem, but fmt::format gives better readability (and known to have a better performance).

**3. Separating library and plugins**
Some classes are used across the DQM/RPCMonitorDigi and DQM/RPCMonitorClient plugin modules.
In addition, RPC DPG analyzers uses features in the rpcdqm::utils (which hopefully to be replaced by RPCRollMapHisto class) in their modules. 
These common features are factored out and moved to the DQM/RPCMonitorClient/src. The plugin modules are moved to the plugins directory. 

**4. Code cleanup**
Cleaned up unnecessary includes, simplify for-loops, etc.

**5. Fix potential memory allocation problem in the RPCDqmClient module**
This module registers 'client modules' by appending pointer to the dynamically allocated objects but it is not deleted anywhere. We use smart pointers to be properly cleaned up at the termination.

We haven't observe any serious memory leak before this fix, because the new allocations happens only for the initialization step.

#### PR validation:

Tested runTheMatrix.py command and passes the tests.

Related presentation in 2020 Oct: [slide](https://indico.cern.ch/event/969469/contributions/4080244/attachments/2132962/3592107/[2020.10.29]%20RPC%20DQM%20development%20-%20RPC%20weekly%20meeting.pdf#page=5)
  - There are other items such as plot removal or unused modules, they will be followed after this PR for the technical updates.
  - The code in this PR is not identical to the one shown in the presentation slide.

Related issue #33761 : please consider this PR as the first step to cleanup of unused modules, although any modules are not removed (yet).

@mileva @andresib

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
Thanks @jhgoh !!

**Comment by jhgoh** [comment]
Fixed compile warning from clang about the unused variable.

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
@jhgoh all histograms are now dubbed sector01, see e.g.
https://tinyurl.com/yz5cl9yq

**Comment by jhgoh** [comment]
@jfernan2 thank you for checks. 
There was bug in histogram naming, but also in the bin labelling. Fix done.

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
