### PR TITLE
PR 81X Fix sporadic crashes in HLT when Seeding with correlations.

### PR DESCRIPTION
**Pull request by rekovic**
This is a fix for the sporadic crashes in the HLT in case of L1T correlation triggers are used.

The problem was in the HLTL1TSeed module which was making ghost combinations in case of cross-object triggers. What effectively was a double loop (once over the vector SingleCombinationInCondition and once over the object types) was causing seeding combinations to be n^2, where n is the larger number of seeds of the two object types.  Some of the objects of the type with smaller number of passing objects were not necessarily passing the L1T conditions but were still being promoted as seeds, creating ghosts.

The code was previously looping both over object types and over vector SingleCombinationInCondition.
This is fixed by now only looping over SingleCombinationInCondition while tracking the object
type to seed properly.

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
@rekovic 
Thanks!

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
