### PR TITLE
FastSim: fix L1 muons (bug fix)

### PR DESCRIPTION
**Pull request by lveldere**
make L1 muon collections available under the same label as in FullSim and data

### CODE REVIEW

**Comment by lveldere** [comment]
please test

**Comment by lveldere** [comment]
+1

**Comment by lveldere** [comment]
@davidlange6 

please merge this one: it's a trivial bug fix

**Comment by lveldere** [comment]
@davidlange6

please merge this one: it's a trivial bug fix

**Comment by davidlange6** [comment]
+1

**Pull request merged**
