### PR TITLE
[Backport] Adding offlineVerticesWithBS to miniAOD to 10_6_X

### PR DESCRIPTION
**Pull request by AdrianoDee**
#### PR description:

This is a backport of #33778. The same results apply.

#### PR validation:

All tests run. Given no `bParking` wf is included (AFAIK) in the recommended test, the `1304.181`has been tested (successfully). See results [here](https://adiflori.web.cern.ch/adiflori/1304.181_ProdZEE_13UP18+ProdZEE_13UP18+DIGIUP18PROD1+RECOPRODUP18bParking+MINIAODMCUP18bParking/).

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
A few observations:
- The new collection is added to miniAOD in case of `bParking` OR if `run2_miniAOD_devel`: bParking production in 10_6 has not yet been done AFAIK, therefore, this shouldn't actually add anything to current productions in 10_6
- In any case, this PR only eventually adds new products, and it doesn't touch any existing one
- HI related modifications are not backported: aren't they needed in 10_6 HI miniAOD? I don't think any miniAOD HI production is foreseen with 10_6, but @mandrenguyen could you please confirm?
- @AdrianoDee I cannot check the output of your test: could you please confirm that you verified that the expected extra output was present there?

**Comment by AdrianoDee** [comment]
> * @AdrianoDee I cannot check the output of your test: could you please confirm that you verified that the expected extra output was present there?

I've checked it locally with the `1304.181` and the new collection is in the miniAOD output. Worth to run a test with this workflow added as extra?

**Comment by perrotta** [comment]
> > * @AdrianoDee I cannot check the output of your test: could you please confirm that you verified that the expected extra output was present there?
> 
> I've checked it locally with the `1304.181` and the new collection is in the miniAOD output. Worth to run a test with this workflow added as extra?

Do you mean, running with this PR instead of your local setup? Yes, please do so: it should be fast, anyhow

**Comment by AdrianoDee** [comment]
I meant running cmsbuild tests with the extra workflow, anyhow I'm testing the wf with the PR merged on a clean 10_6_X IB, let's see the outcome.

**Comment by AdrianoDee** [comment]
Checked, everything was smooth and the collection was there (just for information `step4.root` in [here](https://adiflori.web.cern.ch/adiflori/1304.181_ProdZEE_13UP18+ProdZEE_13UP18+DIGIUP18PROD1+RECOPRODUP18bParking+MINIAODMCUP18bParking/))

**Comment by mandrenguyen** [comment]
@perrotta That's correct, there is no HI miniAOD production intended for 10_6.   I don't know whether any future PbPb re-miniAOD will happen in 12_X_Y or in 11_2_X, as the previous one.  In the latter case, I guess one should consider backporting to 11_2.

**Comment by perrotta** [comment]
+1
- `offlineVerticesWithBS` added to miniAOD only if `bParking` OR `run2_miniAOD_devel`: no changes to the usual workflow outputs in other cases
- Differently from the master version of this PR, the same additions do not apply for HI miniAOD: this is correct, because no re-miniAOD is foreseen for HI with 10_6: **if needed**, backport in the relevant release for a possible future HI re-miniAOD will have to be prepared
- Jenkins tests pass and show no differences, coherently to what above

**Comment by perrotta** [comment]
> @perrotta That's correct, there is no HI miniAOD production intended for 10_6. I don't know whether any future PbPb re-miniAOD will happen in 12_X_Y or in 11_2_X, as the previous one. In the latter case, I guess one should consider backporting to 11_2.

Thank you @mandrenguyen : I expect that HI will take care of organizing the possible backport in the relevant release, only if and when needed

**Comment by qliphy** [comment]
+1

**Comment by AdrianoDee** [comment]
Thanks!

**Pull request merged**
