### PR TITLE
Set the SOI for HCAL TP samples when packing.

### PR DESCRIPTION
**Pull request by matz-e**
See title. The information is accessed on a per-sample basis when unpacking, but the raw samples in MC don't have the corresponding bit set. Set it when packing. Note that this will only have an effect for newly generated MC.

Backport of #19804. Needed for #20222, as per discussion in #20221.

### CODE REVIEW

**Comment by dmitrijus** [comment]
+1

**Comment by slava77** [comment]
I think that it is better to have one complete PR for a backport instead of rebuilding a chain that has to be merged in a specific sequence

**Comment by kpedro88** [comment]
@slava77 since we're now going with the solution in #20267, there's no explicit interdependence between these PRs. I think they can proceed separately, though both are nice to have in 92X.

**Comment by kpedro88** [comment]
please test

**Comment by slava77** [comment]
@kpedro88 
This PR is relevant only for MC.
if this is not required for the v1 MC campaign in 92X, I think that this PR is not needed in 92X.
Please clarify how this will be used in 92X.

**Comment by kpedro88** [comment]
It is a matter of consistency with #20267, which restores packing of premixed TPs. It is not explicitly needed for the v1 MC (as far as I know), but if someone were to look at the unpacked TPs, we want them to get the right values.

**Comment by slava77** [comment]
On 8/25/17 9:59 AM, Kevin Pedro wrote:
> It is a matter of consistency with #20267
> <https://github.com/cms-sw/cmssw/pull/20267>, which restores packing of
> premixed TPs.

> It is not explicitly needed for the v1 MC (as far as I
> know), but if someone were to look at the unpacked TPs, we want them to
> get the right values.

Sorry, I still miss the point.
If neither 20267 nor this PR are required for v1, what is it needed for
in 92X?
My understanding is that 92X is closed for new features (or fixes) for
what concerns MC generation.
Is there some other new MC campaign expected in 92X?
If the update is needed "for some studies", the nominal policy is to
keep the default unchanged and allow a configuration level change.

**Comment by kpedro88** [comment]
#20267 is needed for HCAL validation of premixing in 92X. That PR also contains a fix for packing of premixed TPs, which becomes buggy without the fix in this PR. Maybe I should just take out the commit that fixes packing premixed TPs in the backport (it will be kept for 93X), so this PR won't be necessary?

**Comment by slava77** [comment]
backport of #19804

**Comment by slava77** [comment]
> Maybe I should just take out the commit that fixes packing premixed TPs in the backport (it will be kept for 93X), so this PR won't be necessary?

If this is satisfactory for HCAL, please go ahead. In that case this PR will not be necessary.

**Comment by kpedro88** [comment]
done

**Comment by matz-e** [comment]
I guess I can close this, then?

**Comment by abrinke1** [comment]
Is there any reason this should not be re-opened and go into 94X?  It's literally a 7 line change.

**Comment by kpedro88** [comment]
@abrinke1 this is a backport of #19804. That PR was merged in 93X and so it's also in 94X already.

**Comment by abrinke1** [comment]
Ah, OK, great!  Good to know.

**Pull request closed without merging**
