### PR TITLE
add monitoring of tracks stopping source

### PR DESCRIPTION
**Pull request by mtosi**
as suggested/requested in https://github.com/cms-sw/cmssw/pull/13628
open in 80x

this PR is meant to add monitoring plots for the stopping source

3 plots (1 1D and 2 2D) are added in the general properties directories
3 plots (1 1D and 2 2D) x each step of the iterative tracking are added in the TrackBuilding directory

the 1D plot has 10bins (one per source type)
the 2D plots give this info as function of the track eta and phi, respectively (using the usual eta and phi binning)

@rovere @VinInn

### CODE REVIEW

**Comment by VinInn** [comment]
@cmsbuild please test

**Comment by deguio** [comment]
+1

**Comment by mtosi** [comment]
as in PR https://github.com/cms-sw/cmssw/pull/13637
I followed David suggestion, and fix the initialization of a vector

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
