### PR TITLE
[14_0_X backport] Get AXOL1TL model version from menu as of utm v0.12.0

### PR DESCRIPTION
**Pull request by quinnanm**
#### PR description:

This is a backport of https://github.com/cms-sw/cmssw/pull/44054 to update the AXOL1TL emulator to be consistent with new [utm grammar v0_12_0](https://globaltrigger.web.cern.ch/globaltrigger/release/utm/latest_doc/html/releaseNotes/v0_12_0.html) and menu as of L1Menu_Collisions2024_v1_0_1_xml. Changes are identical to [44054](https://github.com/cms-sw/cmssw/pull/44054)  See: https://cms-talk.web.cern.ch/t/update-of-the-2024-l1-menu-tag-l1menu-collisions2024-v1-0-1/36759. 

#### PR validation:

This must be tested and merged together with https://github.com/cms-sw/cmsdist/pull/9065 and upcoming backport of https://github.com/cms-sw/cmssw/pull/44389.

Passes basic code formats and checks. 

backport of [44054](https://github.com/cms-sw/cmssw/pull/44054) to 14_0_X

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
@perrotta 
Now that we have this L1T backprt PR, we'd also need the 14_0 backport of your https://github.com/cms-sw/cmssw/pull/44389 .

**Comment by perrotta** [comment]
> @perrotta Now that we have this L1T backprt PR, we'd also need the 14_0 backport of your #44389 .

Here it is: https://github.com/cms-sw/cmssw/pull/44398

**Comment by mmusich** [comment]
test parameters:
   * pull_request = #44398
   * pull_request = https://github.com/cms-sw/cmsdist/pull/9065

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by perrotta** [comment]
https://github.com/cms-sw/cmssw/pull/44398

**Comment by mmusich** [comment]
backport of https://github.com/cms-sw/cmssw/pull/44054

**Comment by mmusich** [comment]
> test parameters:
>   * pull_request = #44398
>  * pull_request = https://github.com/cms-sw/cmsdist/pull/9065
   
Ok, this syntax is not correct.

**Comment by mmusich** [comment]
test parameters:
   * pull_request = #44398, https://github.com/cms-sw/cmsdist/pull/9065

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by aloeliger** [comment]
test parameters:
- pull_request = https://github.com/cms-sw/cmssw/pull/44398, https://github.com/cms-sw/cmsdist/pull/9065

**Comment by aloeliger** [comment]
please test

**Comment by quinnanm** [comment]
@mmusich Thank you for the suggested changes to `[HLTrigger/Configuration/python/customizeHLTforCMSSW.py](https://github.com/cms-sw/cmssw/pull/44397/commits/abcff63d870719f300a569640da23f4c0d590f97)`. I committed the suggestions

**Comment by mmusich** [comment]
> test parameters:

why are these commands repeated every time?

**Comment by aloeliger** [comment]
I don't know if they need to be, but I didn't want to miss them in case they were required.

**Comment by mmusich** [comment]
> I don't know if they need to be, but I didn't want to miss them in case they were required.

the bot doesn't forget them after they are applied, unless they are overridden from a conflicting command.

**Comment by mmusich** [comment]
Now there are differences in the [TriggerResults](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_14_0_X_2024-03-14-1100+220365/61673/triggerResults): found differences in 2 / 47 workflows.
In both cases it's AXO:
- https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_14_0_X_2024-03-14-1100+220365/61673/triggerResults/141.044_RunJetMET2023D/reHLT.log
- https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_14_0_X_2024-03-14-1100+220365/61673/triggerResults/13034.0_TTbar_14TeV+2024PU/HLT.log

**Comment by aloeliger** [comment]
Which is truly unexpected and should not be happening. @quinnanm this should be examined. @quinnanm Out of curiosity, was the axo model updated or upgraded at all between 14_0 and 14_1?

**Comment by aloeliger** [comment]
@caruta Also out of curiosity, have any changes been made in any menus for AXO nominal or Tight thresholds?

**Comment by mmusich** [comment]
hold

**Comment by quinnanm** [comment]
the axo model should be v3 for both cases. I can run a test and look closely at the calculated scores in 14_0_X and 14_1_X for the same file and menu now.

**Comment by aloeliger** [comment]
@eyigitba & @slaurila FYI

**Comment by aloeliger** [comment]
> the axo model should be v3 for both cases. I can run a test and look closely at the calculated scores in 14_0_X and 14_1_X for the same file and menu now. 

So, presumably not the AXO scores changing in the workflow. _but that should still be checked_. Okay. Is it possible the menu change implied here changed thresholds or results or something?

**Comment by quinnanm** [comment]
would a different menu be associated with 14_0_X other than L1Menu_Collisions2024_v1_0_1.xml, if so which one?

**Comment by mmusich** [comment]
> would a different menu be associated with 14_0_X other than L1Menu_Collisions2024_v1_0_1.xml, if so which one?

No other menu is associated with 14_0_X. You are forcing (in your own PR) to use `L1Menu_Collisions2024_v1_0_1` in the data workflows, and via https://github.com/cms-sw/cmssw/pull/44398 (tested together with this PR) for the MC ones.

**Comment by quinnanm** [comment]
that was what I thought, thanks. I will post here shortly when I finish some additional tests

**Comment by quinnanm** [comment]
Ok, so I'm testing both 14_0 and 14_X with identical models and menus (v3 , L1Menu_Collisions2024_v1_0_1), RAW2DIGI, and I find the following from the events I've looked at:

- the inputs are identical
- the menu thresholds are identical
- the model versions are identical (including input/output types)
- _the scores change._

this is similar I think to the inconsistencies Artur was seeing, but I can keep looking to confirm. Here are some codimd logs: https://codimd.web.cern.ch/s/R7khbdJqm

**Comment by caruta** [comment]
> @caruta Also out of curiosity, have any changes been made in any menus for AXO nominal or Tight thresholds?

Hi @aloeliger, yes, the AXO thresholds in the v1_0_1  are updated to the latest set of thresholds provided by the AXO team (see [here](https://its.cern.ch/jira/browse/CMSLITDPG-1208?focusedId=6307599&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-6307599)), while in v1_0_0 menu, old thresholds were used.

**Comment by aloeliger** [comment]
@mmusich Unfortunately, upon further examination, it looks like there is genuinely un-explainable things going on. AXOL1TL demonstrably has the same inputs and the same model, but gives different outputs :grimacing:. We were pushing this for release in 14_0 as fast as possible, but this may take some time to fully understand...

@eyigitba We should talk worst cases, where this may not be ready in time for systems to switch to a release with it for data-taking. Does this affect operations and data-taking and do we need to have a contingency?

**Comment by mmusich** [comment]
>  We were pushing this for release in 14_0 as fast as possible, but this may take some time to fully understand...

right, that's why we took the decision to descope this from the release of the GRu1 menu v1.0. This (and related updates of the L1T menu - including threshold updates) will have to go into the next available train.

**Comment by Martin-Grunewald** [comment]
The 14_1 PR is in - is 14_1 affected or not?

**Comment by aloeliger** [comment]
@Martin-Grunewald As far as I understand, 14_1 gives expected results so far. @quinnanm is still debugging.

**Comment by mmusich** [comment]
> As far as I understand, 14_1 gives expected results so far

[here](https://github.com/cms-sw/cmssw/pull/44397#issuecomment-1998520704) there is written:

> The 14_0 results/scores are actually the correct ones compared to compiling and evaluating the model locally outside of a CMSSW environment, but they are different in 14_1. 

so I would think the contrary is true.

**Comment by mmusich** [comment]
trying to make sense of this.
IF:
   * The 14_0 results/scores are actually the correct ones compared to compiling and evaluating the model locally outside of a CMSSW environment, but they are different in 14_1.
   * the AXO thresholds in the `L1T-v1_0_1` (used here) are updated to the latest set of thresholds provided by the AXO team (see [here](https://its.cern.ch/jira/browse/CMSLITDPG-1208?focusedId=6307599&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-6307599)) - and following the link I see that the thresholds are increased:
   
   ```
  L1_AXO_VLoose (bit 438):  15717 (currently 9773)
  L1_AXO_Loose (bit 439):   17596 (currently 11757)
  L1_AXO_Nominal (bit 440): 18580 (currently 15717)
  L1_AXO_Tight (bit 441):   20486 (currently 17596)
  L1_AXO_VTight (bit 442):  30161 (currently 18580) 
```

it should make sense that in this PR we loose events firing the AXO triggers:

```
     Events    Accepted      Gained        Lost       Other  Trigger
         100           2           -          -2           -  DST_PFScouting_AXONominal_v1
         100           1           -          -1           -  DST_PFScouting_AXOTight_v1
```

On the other hand it's not clear to me why in CMSSW_14_1_X instead we don't observe [changes in the trigger results](https://github.com/cms-sw/cmssw/pull/44054#issuecomment-1996266443)

**Comment by perrotta** [comment]
Can the reason be because in 14_1_X https://github.com/cms-sw/cmssw/pull/44054 was not yet merged ? See https://github.com/cms-sw/cmssw/pull/44054#issuecomment-1999962942

**Comment by quinnanm** [comment]
Update: I was just now able to resolve the issue I was seeing in testing by disabling the CICADA sequence in my cmsDriver test command, as suggested by @aloeliger 

```
#test command 
cmsDriver.py l1Ntuple -s RAW2DIGI --python_filename=data.py -n 10 --no_output --era=Run3 --data --conditions=130X_dataRun3_Prompt_v4 --customise=L1Trigger/Configuration/customiseReEmul.L1TReEmulFromRAW  --customise=L1Trigger/L1TNtuples/customiseL1Ntuple.L1NtupleRAWEMU --customise=L1Trigger/Configuration/customiseUtils.L1TGlobalMenuXML --customise=L1Trigger/Configuration/customiseSettings.L1TSettingsToCaloParams_2023_v0_4 --filein=/store/data/Run2023C/JetMET0/RAW/v1/000/368/566/00000/81c206fd-f1d4-4f09-905b-4a185cf097c2.root --fileout=L1Ntuple.root

#in data.py add the following to line 105
process.L1TReEmulPath.remove(process.simCaloStage2Layer1Summary)

cmsRun  data.py
```

Something with a related change between 14_0_X and 14_1_X must be causing this issue. I am not sure why this is the case or if this has implications for any other trigger seeds. But this means that the code in this PR and https://github.com/cms-sw/cmssw/pull/44054 and the AXOL1TL model externals are unrelated. With the above modification and the L1Menu_Collisions2024_v1_0_1 menu, I find the scores and outputs in my test file are exactly identical in 14_0_X and 14_1_X as expected.

I apologize for the confusion. I have documented notes here: https://codimd.web.cern.ch/s/R7khbdJqm

FYI @caruta @aloeliger @Martin-Grunewald @mmusich @perrotta @eyigitba

**Comment by mmusich** [comment]
test parameters:
   * pull_request = #44398

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
To elaborate on https://github.com/cms-sw/cmssw/pull/44397#issuecomment-2001594195

> Can the reason be because in 14_1_X https://github.com/cms-sw/cmssw/pull/44054 was not yet merged ? See https://github.com/cms-sw/cmssw/pull/44054#issuecomment-1999962942

It appears that https://github.com/cms-sw/cmssw/pull/44054 was tested without https://github.com/cms-sw/cmsdist/pull/9064 because of the way the bot commands were formulated at https://github.com/cms-sw/cmssw/pull/44054#issuecomment-1996066427 (apparently when a bullet list is passed all the entries but the last one are ignored). 
Let's see what happens here doing the same (i.e. testing without the external)

**Comment by mmusich** [comment]
@perrotta 

> [TriggerResults](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_14_0_X_2024-03-15-2300+220365/61714/triggerResults): found differences in 2 / 47 workflows

so it doesn't depend on the external update inclusion or not (as one would expect).

**Comment by artlbv** [comment]
> On the other hand it's not clear to me why in CMSSW_14_1_X instead we don't observe [changes in the trigger results](https://github.com/cms-sw/cmssw/pull/44054#issuecomment-1996266443)

Is there a way to see the actual counts? Not the differences.
What is actually the reference for these comparisons?

My suspicion is that the AXO results in 14_1 are off due the issue @quinnanm described [above](https://github.com/cms-sw/cmssw/pull/44397#issuecomment-2001002086). The AXO score in 14_1 is huge and therefore might fire most events.
If that was also the case for the reference in 14_1, then it would explain why changing the thresholds in the L1 Menu had no effect on the trigger results.

We are investigating if some upstream changes might have caused AXO scores change when moving from 14_0 to 14_1.

**Comment by mmusich** [comment]
For the record:

> Is there a way to see the actual counts? Not the differences.

If you click on the [test results](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_14_0_X_2024-03-15-2300+220365/61714/triggerResults) you can click on the workflow of interest and then you will have several JSON files. For each trigger path you will have the number of counts for the baseline and for the PR.

> What is actually the reference for these comparisons?

the reference is the last IB for the corresponding cycle, it's actually written in the summary if you click e.g. [here](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-220365/38185/summary.html) you can see that this was tested against [CMSSW_14_0_X_2024-03-15-2300](https://cmssdt.cern.ch/SDT/html/cmssdt-ib/#/ib/CMSSW_14_0_X) 

Screenshot from 2024-03-16 12-27-05

**Comment by artlbv** [comment]
Thanks @mmusich for the pointers. 
I now took the trigger test result for the workflow with discrepancies `141.044` for both PRs:

```
## 14_0 Backport results: 
## JSON https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_14_0_X_2024-03-15-2300+220365/61714/triggerResults/141.044_RunJetMET2023D/reHLT.json
## from tests https://github.com/cms-sw/cmssw/pull/44397#issuecomment-2001893129 
## "reHLT_140_backport.json"

## 14_1 PR results:
## JSON https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_14_1_X_2024-03-13-1100+5aa5c5/61657/triggerResults/141.044_RunJetMET2023D/reHLT.json
## From comment https://github.com/cms-sw/cmssw/pull/44054#issuecomment-1996266443
# fname = "reHLT_141.json"
```

See the code here: https://gist.github.com/artlbv/f82845607b5fe18c9e35c58502874cc5


And these are the results: 

index | 140 backport_old | 140 backport_new | 141 PR_old | 141 PR_new
 -- | -- | -- | -- | --
DST_PFScouting_AXONominal_v1 | 2 | 0 | 100 | 100
DST_PFScouting_AXOTight_v1 | 1 | 0 | 100 | 100
HLT_L1AXOVTight_v1 | 0 | 0 | 100 | 100
Dataset_ScoutingPFMonitor | 1 | 1 | 2 | 2
Dataset_ScoutingPFRun3 | 75 | 75 | 100 | 100

So as I expected above, in 14_1 we did not see any differences in the AXO results since ALL events were firing even in the baseline.

**Comment by artlbv** [comment]
To summarise for @perrotta @mmusich @Martin-Grunewald @missirol @eyigitba @slaurila @caruta @aloeliger @epalencia  @quinnanm et al:
 
**IMO in 14_0 everything is fine with AXO, including this PR**. 
The only reason this PR changes the trigger results is due to the update of the L1 Menu where _only_ the AXO seed thresholds were modified (corrected [according to the JIRA](https://its.cern.ch/jira/login.jsp?permissionViolation=true&os_destination=%2Fbrowse%2FCMSLITDPG-1208%3FfocusedId%3D6307599%26page%3Dcom.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel&page_caps=&user_role=#comment-6307599). The rest of the L1 menu is unaffected as the results show.

These corrected AXO thresholds also correspond to those used in the HLT timing and rate studies in https://its.cern.ch/jira/browse/CMSHLT-3049 by @jpearkes -> which were signed off by TSG.

**Would this be enough to justify keeping AXO in for the first HLT menu?**

As for 14_1 we ought to debug this within L1, but given this release will not be built until August, I imagine this has another timeline.

**Comment by mmusich** [comment]
@artlbv 

> IMO in 14_0 everything is fine with AXO, including this PR.

thanks for the detailed analysis. I tend to agree, as already reported in https://github.com/cms-sw/cmssw/pull/44397#issuecomment-2000115930.

> These corrected AXO thresholds also correspond to those used in the HLT timing and rate studies in https://its.cern.ch/jira/browse/CMSHLT-3049 by @jpearkes -> which were signed off by TSG.

hmm, no. 
TSG signed-off based on the hlt integration results (see attachment at https://its.cern.ch/jira/secure/attachment/554837/test.log) which as the log clearly reports were based on `L1Menu_Collisions2024_v0_0_0_xml` not on a different menu using different thresholds. Actually I myself learned that `L1Menu_Collisions2024_v1_0_1_xml` contained updated thresholds only thanks to this message from @caruta https://github.com/cms-sw/cmssw/pull/44397#issuecomment-1999158692. I think there has been a serious lack of communication between LT1 DPG and TSG in this respect.

> Would this be enough to justify keeping AXO in for the first HLT menu?

I am removing the hold as given the explanations provided I don't have reason to think that the AXO triggers produce irreproducibiities in the trigger results, but I am not going to sign off until the deployment strategy is clarified within TSG: the new 2024 GRun menu v1.0 was already delivered and handed off to TSG/FOG for deployment (based on CMSSW_14_0_2 without this PR and `L1Menu_Collisions2024_v1_0_0_xml`).

> As for 14_1 we ought to debug this within L1, but given this release will not be built until August, I imagine this has another timeline.

I opened https://github.com/cms-sw/cmssw/issues/44435 to track progress on that.

**Comment by mmusich** [comment]
unhold

**Comment by aloeliger** [comment]
@artlbv, @quinnanm, @mmusich  I'm catching up after other work yesterday afternoon.

Melissa has seen that removing the CICADA emulator changes AXO's answers.

The CICADA team (myself actually) caught this one earlier this week looking at CICADA firmware/emulator matching. We could run multiple CICADA emulators at the same time and get different answers from a model than we would running only one emulator. I couldn't figure it out and reverted to only doing one at a time because that's how the emulator works anyways and I suspected it was some strange internal CICADA version that could be sorted out at some point later.

What I suspect now now is that this issue is fundamentally symbol collision. Strictly, there isn't anything wrong with CICADA or AXO, the issue is that they share c++ code/symbols that are not specific to themselves in the dynamic linking case used by the emulator technique.

My theory on what is happening is this:

 n 14_1 we updated the CICADA model to 1.1.1. One of the layers of CICADA 1.1.1 is weights w2, seen here: https://github.com/cms-hls4ml/CICADA/blob/2baca92cc3f6041e98d43c7391b9e7eba6ed249a/CICADA_v1p1p1/cicada.cpp#L36
https://github.com/cms-hls4ml/CICADA/blob/2baca92cc3f6041e98d43c7391b9e7eba6ed249a/CICADA_v1p1p1/weights/w2.h#L12. Note that before, in model 2.1, w2 was not in use: https://github.com/cms-hls4ml/CICADA/blob/2baca92cc3f6041e98d43c7391b9e7eba6ed249a/CICADA_v2p1/myproject.cpp#L57

AXO, by extension, uses w2 (and b2) as well: https://github.com/cms-hls4ml/AXOL1TL/blob/f21d72bc08ab6e7a86292db9ff0637532a311c2c/AXOL1TL_v3/NN/GTADModel_v3.cpp#L65 https://github.com/cms-hls4ml/AXOL1TL/blob/f21d72bc08ab6e7a86292db9ff0637532a311c2c/AXOL1TL_v3/NN/weights.h#L5 (notably, they are also sized such that AXO could comfortably use CICADA's weights).

These weights are defined globally for both models. As the CMSSW job runs, CICADA gets loaded and created, and these weights loaded into the symbol table here by the dlopen here: https://github.com/cms-hls4ml/hls4mlEmulatorExtras/blob/17790de8f2f2892dfd8ff20fead8eedd3cf59b49/src/hls4ml/emulator.cc#L21. Later, the AXO model gets created, and the load also attempted. I suspect that behind the scenes, dlopen sees that it would be loading things into the symbol table that are already defined, and quietly drops it in favor of things that are already defined.

In essence, when we upgraded CICADA to 1.1.1, by no real fault of our own, we ended up accidentally switching AXO to CICADA's weights.

I suspect a quick and dirty solution would be to do to CICADA what AXOL1TL has accidentally been doing (and we've all been asking AXO to stop ironically), which is create and destroy itself in one swoop, with no real persistence for model objects beyond creating a result.

In the longer run, the usage of this emulator technique needs to be fixed or changed.

**Comment by fwyzard** [comment]
> In the longer run, the usage of this emulator technique needs to be fixed or changed.

By "in the longer run" you mean "before this can be run reliably within the L1T emulator running at HLT and in the online DQM", right ?

**Comment by Martin-Grunewald** [comment]
@aloeliger 
Could you please comment on the plans and timeline for this PR? IOW, imminent or delayed, etc.?

**Comment by Martin-Grunewald** [comment]
code-checks

**Comment by mmusich** [comment]
-hlt
   * as discussed in the L1T DPG section of the joint operations [meeting of 18th March](https://docs.google.com/document/d/1qNrrmaGCMTFdytBK-jw2zqMs29CHIY5v25fD-MrBVeM/edit#heading=h.94pe6ztmuo2l), the plan is:
      * close the 14.0.X AXO PR (not needed)
      * revert the 14.1.X AXO PR
      * after the L1T code is rendered backward compatible a better PR will be opened in both 14.1.X and 14.0.X. 
      * In the meanwhile data will be acquired with the L1T menu `L1T_v1_0_0` (old AXO thresholds) and current online GRun HLT menu v1.0.
   * A general fix for the model loading to avoid symbols collisions in `hls4ml` is needed in the long run before being able to run anomaly detection triggers safely.

**Comment by Martin-Grunewald** [comment]
Hmm, I suppose that means we need to revert from v1_0_1 of the L1T menu back to v1_0_0 of the LT1 menu in the GTs in 14_0 and 14_1? @perrotta

**Comment by perrotta** [comment]
> Hmm, I suppose that means we need to revert from v1_0_1 of the L1T menu back to v1_0_0 of the LT1 menu in the GTs in 14_0 and 14_1? @perrotta

Yes, this was indeed the outcome of the JointOps meeting yesterday

**Comment by perrotta** [comment]
-alca
@quinnanm this can probably get closed, given what summarized in https://github.com/cms-sw/cmssw/pull/44397#issuecomment-2006084165

**Comment by artlbv** [comment]
This can be closed as superseded by #44510

**Comment by mmusich** [comment]
@cmsbuild, please close

**Pull request closed without merging**
