### PR TITLE
cleanup of some static analyzer issues in isolation-related code

### PR DESCRIPTION
**Pull request by slava77**
this clears a few 
- non-const statics
- a const cast
- possibly thread unsafe mutable members
- possibly uninitialized case
- also, some replacement of boost::regex with std::regex

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/26829	2909c88
- technical
- jenkins tests pass; IsoDep\*-related static analyzer warnings no longer appear, as expected.

**Comment by fabiocos** [comment]
@santocch I would move forward with the integration, please check and in case comment

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Comment by santocch** [comment]
+1

**Pull request merged**
