### PR TITLE
[MkFit] Per iteration / eta region track candidate scoring function

### PR DESCRIPTION
**Pull request by osschar**
#### PR description:

* Allow track/candidate scoring function to be defined per iteration and eta region.

* Configure through standard function catalog and JSON files.

* Default is to pick the existing scoring function so there is no need to provide new JSON files until new scoring functions are actually implemented.

* Definitions of function types used in standard function catalogs are moved from MkFitCore/interface/IterationConfig.h to FunctionTypes.h

The purpose of this PR is to allow further work on improvements of MKFit performance.

#### PR validation:

This is a technical change, there should be no changes in physics performance.

### CODE REVIEW

**Comment by mmusich** [comment]
type tracking

**Comment by mmusich** [comment]
please test

**Comment by osschar** [comment]
Sigh, I wrongly assumed JSON parser wouldn't mind the missing members ... that they would just keep the default values.
I will prepare a parallel PR for the JSON files in the cms-data/RecoTracker-MkFit.

I apologize for the omission and noise.

**Comment by osschar** [comment]
I have added the JSON changes: cms-data/RecoTracker-MkFit#11

**Comment by slava77** [comment]
test parameters:
- pull_request = cms-data/RecoTracker-MkFit#11

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
> Reco comparison results: 1576 differences found in the comparisons

it's unclear if these are from the other 6 PRs merged with these tests

@smuzaffar 
IIUC, presence of an external data file PR triggers checkout of the head of the cms-sw/cmssw. Is there a way to avoid it?

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by smuzaffar** [comment]
> IIUC, presence of an external data file PR triggers checkout of the head of the cms-sw/cmssw. Is there a way to avoid it?

No , currently no way to avoid it

**Comment by smuzaffar** [comment]
The header consistency error [a] looks related to this PR
[a]
```
src/RecoTracker/MkFitCore/interface/SteeringParams.h:97:5: error: 'track_score_func' does not name a type
   97 |     track_score_func m_track_scorer;
      |     ^~~~~~~~~~~~~~~~
```

**Comment by smuzaffar** [comment]
looks like missing `#include "RecoTracker/MkFitCore/interface/FunctionTypes.h"` statement in `RecoTracker/MkFitCore/interface/SteeringParams.h`

**Comment by osschar** [comment]
Thanks @smuzaffar ... I added the include.

**Comment by slava77** [comment]
@cmsbuild please test

the differences are now understood and no further changes are planned to this PR, unless some are requested in the review

**Comment by mmasciov** [comment]
> the differences are now understood and no further changes are planned to this PR, unless some are requested in the review

For completeness:
- There are slight differences in physics performance visible in the MTV results for individual mkFit iterations introduced with this PR; e.g., in TTbar events with PU: http://uaf-10.t2.ucsd.edu/~mmasciov/MIC/PR40490/MTV_TTbarPU_mkFit_PR40490_EL8/ 
- After further investigations, it became apparent that these slight differences are related to the presence of the fast-math flag in the `MkFitCore` buildfile, and to the fact that previously inline functions are now declared as regular functions. In fact, if one removes the fast-math flag from the `MkFitCore` buildfile, the corresponding MTV results show zero differences:  http://uaf-10.t2.ucsd.edu/~mmasciov/MIC/PR40490/MTV_TTbarPU_mkFit_PR40490_EL8_nofastmathMkFitCoreOnly/
As the above-mentioned slight differences are related to compilation and not to the actual changes introduced by this PR, we would consider the PR itself validated in terms of performance.

**Comment by mandrenguyen** [comment]
+reconstruction
Small changes to comparisons are due to change to compiler setting, as described in this [comment](https://github.com/cms-sw/cmssw/pull/40490#issuecomment-1398918431)

**Comment by perrotta** [comment]
+1
- Differences in tha last test outputs are due to fastmath usage, see https://github.com/cms-sw/cmssw/pull/40490#issuecomment-1398918431, and to the additional PRs built together, in particular https://github.com/cms-sw/cmssw/pull/40554

**Pull request merged**
