### PR TITLE
SiPixelDigitizer modification for reading inefficiency factors from DB

### PR DESCRIPTION
**Pull request by bartokm**
The necessary changes for the Digitizer to read inefficiency factors from DataBase. The factors which are read from the DB are the same as previously read from python files (which are now commented out).
For the Phase1 detector there is only trivial efficiency loss included therefor there is no payload for it, those factors are still set from the  SLHCUpgradeSimulations package.

@diguida @mmusich you've asked to review this PR.

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild why this PR is not acknowledged?

**Comment by slava77** [comment]
On 6/1/15 8:41 AM, Marco Musich wrote:
> @cmsbuild <https://github.com/cmsbuild> why this PR is not acknowledged?
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cms-sw/cmssw/pull/9383#issuecomment-107480129>.
> 

cms-bot is likely not running.
I noticed in a few other PRs already

**Comment by mmusich** [comment]
pleas test

**Comment by bartokm** [comment]
please test

**Comment by civanch** [comment]
please test

**Comment by bartokm** [comment]
The error is due to the mixNoPU_cfi.py file which has bunchspacing value of 450 for which I haven't prepared the code to interpret. As for the 0 PU case, inefficiency is irrelevant of bunchspace (or energy). Therefore I'm going to make a commit with a change of treating bunchspace 450 same as 25ns.

**Comment by bartokm** [comment]
I've made the commit and pushed it to my branch. Does anyone know why doesn't it appear here?
I can see it in the git log:
Author: Marton <marton.bartok@cern.ch>
Date:   Wed Jun 3 09:59:59 2015 +0200
    mixNoPUcase
commit 9f2f8eba9097073b829f6641e8f9bd461368acaa

**Comment by davidlange6** [comment]
I don't see it in your repo
https://github.com/bartokm/cmssw/tree/SiPixelDigitizer_DynIneff_DB_implementation

**Comment by mmusich** [comment]
@bartokm the commit seems to be into another branch: https://github.com/bartokm/cmssw/tree/bartokm/SiPixelDigitizer_DynIneff_DB_implementation

**Comment by bartokm** [comment]
I see now the difference. The commit is in "bartokm/SiPixelDigitizer_DynIneff_DB_implementation", but the PR here is "SiPixelDigitizer_DynIneff_DB_implementation" (without bartokm). How can I easily fix this?

**Comment by bartokm** [comment]
I've figured it out! Thanks David and Marco!

**Comment by mmusich** [comment]
@cmsbuild please acknowledge changes

**Comment by bartokm** [comment]
please test

**Comment by mmusich** [comment]
please test

**Comment by bartokm** [comment]
The tests are approved, @civanch, @mdhildreth could you review this PR?

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
@bartokm - two issues I have
 -- please remove instead of commenting all the lines that you have removed
 -- there are a bunch of lines like process.mix.digitizers.pixel.thePixelColEfficiency_BPix1 = cms.double(0.999) - do these have any function now?

**Comment by bartokm** [comment]
@davidlange6
-- I commented out (instead of deleting it) only to have an example of a full configuration of factors, if one wants to run locally with private settings (s)he can see easily what needs to be set. But if you think it's obsolete and disturbing I can remove it.
-- In the SLHCUpgradeSimulations files those lines are for the PhaseI upgrade detector which doesn't have proper inefficiency yet. Therefore we haven't prepared a separate payload for the upgrade.

**Comment by davidlange6** [comment]
@bartokm - actually the phase I settings are here:

The PhaseI config is actually in SLHCUpgradeSimulations/Configuration/python/phase1TkCustoms.py - I think what you changed is obsolete. You might ask in the tracker.

its indeed good to have example of a full config - but it should be uncommented and in a separate file so that then someone can then just use the alternative cfi if they would like to use numbers different from the db, that cfi can be used directly.

**Comment by bartokm** [comment]
@davidlange6
I've made a new commit, implementing your suggestions.

**Comment by bartokm** [comment]
@davidlange6
Could you please review the changes and if you agree merge it? Since tests are irrelevant, and others previously signed it.

**Comment by davidlange6** [comment]
@bartokm - i think the changes are ok - however, in the meanwhile I believe the SIM group realized that these changes will break pre-mixing without further changes. @mdhildreth is looking at that (with your help I believe)

**Comment by bartokm** [comment]
@davidlange6
I see, this means, that the PR will be merged only when the pre-mixing code is ready?
When I created this PR, I contacted Mike and offered help if needed. (So far they haven't asked me for help)

**Comment by davidlange6** [comment]
@bartokm - Right. We should break workflows that are working well at this stage of the release cycle.

**Comment by davidlange6** [comment]
#9672 contains this pr now - closing this and accepting that

**Pull request closed without merging**
