### PR TITLE
FormulaEvaluator now ignores white space

### PR DESCRIPTION
**Pull request by Dr15Jones**

### CODE REVIEW

**Comment by slava77** [comment]
@Dr15Jones 
Please clarify if another update for the ```^``` operator is going to be added in this PR.
Thanks.

**Comment by Dr15Jones** [comment]
> Please clarify if another update for the ^ operator is going to be added in this PR.

I was considering just creating a separate pull request for that fix.

**Comment by forthommel** [comment]
Thanks a lot for coming up with this solution, @Dr15Jones ! Will you provide this extra `^` operator fix (new PR, or here directly) in a short while? So we know where we stand with #25465.

**Comment by forthommel** [comment]
Thanks, @Dr15Jones ! Let me/us know we can be any helpful in your bug tracking...

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/25603	8fb1fe7
- code changes are in line with the PR description
- jenkins tests pass and comparisons with the baseline show no relevant differences

**Comment by Dr15Jones** [comment]
See #25622

**Comment by slava77** [comment]
this is now fully included in #25622
shouldn't this PR be closed as superseded ?

**Comment by Dr15Jones** [comment]
I don't care either way. The two pull requests have the exact same commit so are guaranteed to merge correctly. If you want me to close this one, I will.

**Comment by fabiocos** [comment]
@slava77 so what is your preference here? I think we could just converge on #25622 and then close this earlier version.

**Comment by slava77** [comment]
> @slava77 so what is your preference here? I think we could just converge on #25622 and then close this earlier version.

no preference from my side considering that the same commit (same SHA) is in the other PR.

**Comment by fabiocos** [comment]
as #25622 has been merged this one may likely be closed, am I correct?

**Comment by Dr15Jones** [comment]
Is part of another pull request.

**Pull request closed without merging**
