### PR TITLE
Clean-up of Tracker conditions for Phase-2 

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

Follow-up of https://github.com/cms-sw/cmssw/pull/30645 and pursuant of https://github.com/cms-sw/cmssw/issues/30512.
As Tracker geometries `T6` and `T14` have been removed from the release, the corresponding symbolic Global Tags can go as well.
For the remaining geometries (`T15`,`T17`,`T19`,`T20`) for the sake of clarity new symbolic Global Tags are introduced (even if they employ the same tags as for `T15`, excepted the Pixel 3D geomery one `T19`) and are deployed in the corresponding `runTheMatrix` workflows.
Moreoever there is no need for the `SLHCUpgradeSimulations/Geometry/python/fakeConditions_phase2TkT*_cff.py` files either because the corresponding geometry has been removed, or because they don't serve any purpose aymore; the dictionary  at `dict2026Geometry.py` is changed accordingly.
Finally the Global Tag used in the test ` SLHCUpgradeSimulations/Geometry/test/phase2_reco_pixelntuple_cfg.py` is bumped up, accordingly to migration to `T15` performed in #30645.

#### PR validation:
Branch passes:
```
runTheMatrix.py -l limited --ibeos 
```
and 
```
scramv1 b runtests
```

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

This PR is not a backport, and no backport is needed.

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by kpedro88** [comment]
+upgrade
thanks @mmusich, I had forgotten about this part of the cleanup

**Comment by chayanit** [comment]
+1

**Comment by cvuosalo** [comment]
+1

**Comment by mmusich** [comment]
@civanch,@christopheralanwest, @tocheng, @tlampen, @pohsun

can you please have a look and comment at earliest convenience? We have more PRs that need to build up on this one.

**Comment by pohsun** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
