### PR TITLE
Add missing include to FitWithRooFit.h

### PR DESCRIPTION
**Pull request by iarspider**
#### PR description:

All RooFit functions now return an owning pointer (`std::unique_ptr`) instead of a raw pointer. A destructor of `std::unique_ptr` calls wrapped class' destructor, so that class needs to be fully defined, or the compilation will fail with 
```
/data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/el8_amd64_gcc11/external/gcc/11.4.1-30ebdc301ebd200f2ae0e3d880258e65/include/c++/11.4.1/bits/unique_ptr.h:83:23: error: invalid application of 'sizeof' to incomplete type 'RooFitResult'
   83 |         static_assert(sizeof(_Tp)>0,
      |                       ^~~~~~~~~~~
gmake: *** [tmp/el8_amd64_gcc11/src/DQMOffline/Alignment/src/DQMOfflineAlignment/DiMuonMassBiasClient.cc.o] Error 1
```

#### PR validation:

Tested in https://github.com/cms-sw/cmsdist/pull/8734

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
ping bot

**Comment by tjavaid** [comment]
please test

**Comment by iarspider** [comment]
@cms-sw/alca-l2 @cms-sw/dqm-l2 could you please review? The change is purely technical.

**Comment by perrotta** [comment]
@iarspider maybe you can remove the [TEST] flag from the title, if you want it reviewed.

In the FitWithRooFit class the call to RooFitResult is in a commented out line (which would be a dead branch even if uncommented) in the implementation file. My questions:
- why to add the include in the header file of the class rather than in the implementation file?
- why to add it at all?

In GenericTnPFitter.h I don't even see why this include is missing: if it is really needed, could you please explain it in the PR description?

**Comment by iarspider** [comment]
@perrotta thanks for the review.

> @iarspider maybe you can remove the [TEST] flag from the title, if you want it reviewed.
My bad, done.

> In the FitWithRooFit class the call to RooFitResult is in a commented out line (which would be a dead branch even if uncommented) in the implementation file. My questions:
> 
>     * why to add the include in the header file of the class rather than in the implementation file?

No patricular reason, I can test if it will still work when includes are inside implementation file
 
>     * why to add it at all?

> In GenericTnPFitter.h I don't even see why this include is missing: if it is really needed, could you please explain it in the PR description?

ROOT change all RooFit function to return owning pointer (`std::unique_ptr`), so calling code now needs to know about wrapped type, even if it doesn't use the result.

**Comment by perrotta** [comment]
> ROOT changed all RooFit function to return owning pointer (`std::unique_ptr`), so calling code now needs to know about wrapped type, even if it doesn't use the result.

Uhm, not sure I understand where RooFitResult is wrapped in these codes, but I imagine you verified it somehow.
For me it's fine, no need to move the header include to the implementation file, then.
Just please add some justification of the fix in the PR descritpion field, so that some documentation can remain of it.

**Comment by iarspider** [comment]
@perrotta done.

**Comment by perrotta** [comment]
+alca
- Thank you @iarspider

**Comment by tjavaid** [comment]
+1

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
