### PR TITLE
Using dasgoclient for das queries in runTheMatrix (53X)

### PR DESCRIPTION
**Pull request by fabozzi**
MIgration to dasgoclient for older production releases

### CODE REVIEW

**Comment by fabozzi** [comment]
please test

**Comment by fabozzi** [comment]
please test

**Comment by kpedro88** [comment]
+1

**Comment by fabozzi** [comment]
+1

**Comment by fabiocos** [comment]
@vkuznet  FYI

**Comment by fabiocos** [comment]
+1

**Pull request merged**
