### PR TITLE
Adding Run2 Comsics Global Tag to autoCond and make wf 1307.0 use it

### PR DESCRIPTION
**Pull request by mmusich**
# Changes in GT
- adding the `run2_mc_cosmics` autoCond key: [76X_mcRun2cosmics_startup_peak_v0](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/76X_mcRun2cosmics_startup_peak_v0) as [76X_mcRun2_asymptotic_v14](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/76X_mcRun2_asymptotic_v14) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/76X_mcRun2cosmics_startup_peak_v0/76X_mcRun2_asymptotic_v14):
  - Startup Tracker, DT and CSC alignment
  - L1 configuration for top-bottom cosmics triggering

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
@battibass you might want to watch this is as wel.

**Comment by hengne** [comment]
+1

**Comment by mmusich** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
