### PR TITLE
Back port feature allowing special value @currentProcess for InputTag process name

### PR DESCRIPTION
**Pull request by wddgit**
This back port of PR #19491 was requested by @fwyzard.

(I also included in this the bug fix for skipCurrentProcess because the test code for the 2 PRs was intertwined. That bug fix should only affect code run in SubProcesses so it shouldn't do any harm because it is usually not executed. If it did actually get run, then the bug fix is probably needed).

### CODE REVIEW

**Comment by wddgit** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by fwyzard** [comment]
Thank you !

**Comment by Dr15Jones** [comment]
@smuzaffar did the unit test build time out again?

**Comment by smuzaffar** [comment]
@Dr15Jones , yes looks like timed out after 15520 secs

**Comment by Dr15Jones** [comment]
@davidlange6 please ignore the test failure. The version in 9_3 works fine.

**Pull request merged**
