### PR TITLE
add PU=0 at the start of vectors (94x)

### PR DESCRIPTION
**Pull request by capalmer85**

### CODE REVIEW

**Comment by franzoni** [comment]
@capalmer85 
by adding a 0 also in front of probValue
you're shifting the distribution of PU up by one unit.

Is such shift consistent with the plots I refer to here https://hypernews.cern.ch/HyperNews/CMS/get/prep-ops/4550/2/2/1/1/1/1.html
  ?

**Comment by capalmer85** [comment]
@franzoni, you were right.  I compared with my histogram.  The PU vector was off by 1 in the original.  This should be fixed now.

**Comment by franzoni** [comment]
ok - this PR does, in the substance, the same as used by @GurpreetSinghChahal in the submission explained here
https://hypernews.cern.ch/HyperNews/CMS/get/prep-ops/4550/2/2/1/1/1.html

thanks!

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
merge

**Pull request merged**
