### PR TITLE
Run3-gex174B Backport the most recent version of Run3 geometries of 2021 and 2023 from #43418 and earlier pull requests for GE21 and HCAL

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Backport the most recent version of Run3 geometries of 2021 and 2023 from #43418 and earlier pull requests for GE21 and HCAL

#### PR validation:

Use the runTheMatrix test workflows

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backport xml, cfi, cff files from https://github.com/cms-sw/cmssw/pull/43418 and other earlier pull requests

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
@bsunanda , please, update the title in order to have explicitly "ZDC" in the title to avoid confusions.

**Comment by antoniovilela** [comment]
@cms-sw/simulation-l2 @cms-sw/geometry-l2 
@cms-sw/ppd-l2 @cms-sw/reconstruction-l2 @cms-sw/orp-l2 
Vladimir, Sunanda,
PPD and reconstruction may comment, but it seems that the best is to disentangle what is needed for ZDC from the rest.
If there is something else needed in the GEN-SIM release (we assume it is 13_0_X) for the HI MC, than this should be further disentangled from the rest that is included in this PR.
Thanks.

**Comment by antoniovilela** [comment]
hold

**Comment by civanch** [comment]
@antoniovilela , geometry description update is not the same thing as code update. Code may be updated via small increments, geometry include several components: xml description for subdetectors, a set of geometry scenarios, pilots for DB record, new GT. It will bring a mess and will require much more efforts and time.

@bsunanda  , there are differences in WF 11634.911, is it expected?


<br class="Apple-interchange-newline">
</body>
</html>[11634.911](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_13_2_X_2023-11-28-1100+9e5393/59998/11634.911_TTbar_14TeV+2021_DD4hep)

**Comment by makortel** [comment]
> there are differences in WF 11634.911, is it expected?

Could they be related to https://github.com/cms-sw/cmssw/issues/35109?

**Comment by malbouis** [comment]
Hi @antoniovilela , thanks for holding this PR. PPD would prefer if nothing other than the ZDC geometry is backported. And even for the ZDC geometry, the backport should only be done in case it is deemed essential for the Heavy Ion MC production. We are discussing it with the HI coordinators.

**Comment by bsunanda** [comment]
Close this in favour of #43443

**Pull request closed without merging**
