### PR TITLE
MiniAOD: fix bug in charge()

### PR DESCRIPTION
**Pull request by arizzi**
fix sign of leptons in miniaod packed candidates

### CODE REVIEW

**Comment by arizzi** [comment]
@gpetruc

**Comment by TaiSakuma** [comment]
The commit seems correct for e, mu, tau. 

However,  I think that the charge will be opposite for W. I think that +24 is W+ and -24 is W-.

**Comment by arizzi** [comment]
I think you are right, I just fixed the fact that they were giving always -1.

**Comment by arizzi** [comment]
btw... I doubt we have W in packedCandidates!

**Comment by davidlange6** [comment]
@cmsbuild, please test

**Comment by arizzi** [comment]
is the IB broken? how can the change of 4 signs in an accessor have any effect on that producer?

**Comment by davidlange6** [comment]
yes, it is.. i just fixed it

________________________________

**Comment by arizzi** [comment]
can some L2 or above retrigger jenkins tests?

**Comment by davidlange6** [comment]
@cmsbuild, please test

**Pull request merged**
