### PR TITLE
Post LS2 Beam-pipe v5.4.0

### PR DESCRIPTION
**Pull request by ianna**
- v5.4.0 engineering description up to 16377 mm
- Add current description up to the end of the hall
- Remove Castor and Totem in 2019 scenario
- Modify Tracker envelopes to avoid overlaps with Pixels support

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
@ghugo83 - please, check and update 2023 Tracker envelopes accordingly.

**Comment by makortel** [comment]
@ianna For my education, does any of this affect 2017 (from cursory look I can't exclude that)? Thanks.

**Comment by boudoul** [comment]
Hi @ianna , naive question , why this PostLs2 BP is impacting  Geometry/TrackerCommonData/data/PhaseI/pixfwd.xml

**Comment by boudoul** [comment]
also this new file : Geometry/TrackerCommonData/data/PostLS2/tracker.xml
is not used yet in any scenario, I guess we should find a way of incorporating it ?

**Comment by boudoul** [comment]
oh I see the new filw is in 2019 sceanrio , I guess we should propagate to 2023xx too

**Comment by ianna** [comment]
@boudoul - thanks for pointing it out. I've renamed the files accordingly. All the changes are now in PostLS2 directories. However, in order to modify 2023xx scenarios we need updated Tracker files from @ghugo83.

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
@makortel - no, it does not affect 2017. The new beampipe will be installed during Long Shutdown 2 (~2020)

**Comment by ghugo83** [comment]
Dear @ianna ,
Sorry I am in a huge rush right now :)
Does this correspond to the Beam Pipe description you sent me a few weeks ago ?
I had uploaded the matching Tracker XMLs at the usual path : /afs/cern.ch/user/g/ghugo/public/prepare_TDR
From what I remember, I had made boundaries of the Tracker as close as possible to the Tracker. In the prospect of any further Beam Pipe volumes modifications :)
Please let me know if this is fine

**Comment by makortel** [comment]
Thanks @ianna. I guess I got confused by what @boudoul mentioned in https://github.com/cms-sw/cmssw/pull/15693#issuecomment-244044284.

**Comment by ianna** [comment]
@ghugo83 - Thanks! Full description would not fit. However, the support is a ring with four "ears". I'll keep the first and drop the latter. This reduced description will (almost) fit. You should probably include the rest of it in the Pixel envelop if more details are needed in the future.

screenshot 2016-09-01 17 07 51

**Comment by ianna** [comment]
@boudoul and @kpedro88 - Heads up on updating 2023 scenarios (not in this PR): the good news is that the workflows will be faster to run - there are fewer detectors. The bad news: some customizations are needed. Removing Castor from the scenarios causes step2 failure:

```
Begin processing the 1st record. Run 1, Event 1, LumiSection 1 at 01-Sep-2016 17:15:39.926 CEST
----- Begin Fatal Exception 01-Sep-2016 17:15:42 CEST-----------------------
An exception of category 'ProductNotFound' occurred while
   [0] Processing run: 1 lumi: 1 event: 1
   [1] Running path 'digitisation_step'
   [2] Calling event method for module MixingModule/'mix'
Exception Message:
Principal::getByLabel: Found zero products matching all criteria
Looking for type: std::vector<PCaloHit>
Looking for module label: g4SimHits
Looking for productInstanceName: CastorFI

   Additional Info:
      [a] If you wish to continue processing events after a ProductNotFound exception,
add "SkipEvent = cms.untracked.vstring('ProductNotFound')" to the "options" PSet in the configuration.

----- End Fatal Exception -------------------------------------------------
Another exception was caught while trying to clean up files after the primary fatal exception.
```

**Comment by kpedro88** [comment]
@ianna yes, I expected as much. When the update to the 2023 geometries is made, it should include the necessary customizations (removal of Castor processes) so the workflows do not break. (As I commented on #15662, `Configuration/Geometry/test/dict2023Geometry.py` should be updated accordingly rather than modifying 2023 geometries by hand.)

**Comment by ianna** [comment]
@ghugo83, @boudoul and @kpedro88 - there are no overlaps with 2023 variations of Tracker anymore. The beam-pipe is ready to be integrated into 2023 scenarios.

**Comment by ianna** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Comment by ghugo83** [comment]
Dear @ianna,
Thanks :) I will have a look at the truncated part you mention.
I was just wondering sth : Since this piece is part of a support structure included in the beampipe description, why not re-introducing this truncated part later on with the rest of its support structure (once the XMLs from prepare_TDR with minimal Tracker enveloppe will be incorporated) ?
Cheers

**Comment by ianna** [comment]
@ghugo83 - yes, this is an option to discuss among Tracker DPG. Another option is to assign full weight to the ring around the beam-pipe. I'm still waiting for its details from TC.

**Pull request merged**
