### PR TITLE
Functional changes as follow-up to 36176, related to SiPixelDigisCUDA SOA 

### PR DESCRIPTION
**Pull request by czangela**
#### PR description:

Some minor changes left from the review of #36176 

#### PR validation:

compiles (no functional changes, results are not changing)

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

no

### CODE REVIEW

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
+heterogeneous

**Comment by VinInn** [comment]
enable gpu

**Comment by slava77** [comment]
@cmsbuild please test
to get the GPU checked

**Comment by slava77** [comment]
@czangela please edit the PR title to be more self-descriptive, perhaps mention pixel SOA or pixel GPU tracking
Thank you.

**Comment by slava77** [comment]
+reconstruction

for https://github.com/cms-sw/cmssw/pull/36430	bac75c3 
- code changes are technical in line with the earlier PR (#36176) comments
- jenkins tests pass and the differences in 11634.506 are not from changes in this PR (the tracking GPU workflow is known to be not repeatable)

**Comment by qliphy** [comment]
+1

**Pull request merged**
