### PR TITLE
backport of LumiProducerFromBrilcalc for 10_6_X

### PR DESCRIPTION
**Pull request by plujan**
This PR is a backport of LumiProducerFromBrilcalc (PR #29271 ) for 10_6_X. I've run the test job to verify that it runs correctly in 10_6_X.

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
backport of #29271

**Comment by perrotta** [comment]
+1
- Identical backport of #29271
- A new luminosity producer is implemented, which reads a csv file produced by brilcalc.
- It has to be used in analyses: not integrated in any central workflow
- Jenkins tests pass and show no differences (besides the known spurious ones, see github issue #29237: evidently the problem was also ported to 10_6...)

**Comment by silviodonato** [comment]
+1

**Pull request merged**
