### PR TITLE
Run2-sim29 Avoid crashes in SteppingVerboseAction

### PR DESCRIPTION
**Pull request by bsunanda**

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
@bsunanda , inside g4SimHits main configuration file there are options allowing different level of stepping verbosity. I do not think, that this sub-library can provide anything more detailed. 

In the main script there are possibilities to select event but number, track by id, use different level of printout. Please, try out these features.

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1
now it is working but I would simply remove this sub-library

**Comment by fabiocos** [comment]
@civanch @bsunanda sorry but I am confused about this PR as there is no description at all, and I am not sure about which sub-library you are discussing. Could you please specify the problem addressed by this PR? What should be removed?

**Comment by fabiocos** [comment]
hold

pending a clarification

**Comment by fabiocos** [comment]
unhold

I see the effect of this PR, this anyway means that the SteppingVerbose is no more an option. I have verified that if this setting is activated it runs smoothly without crashing:

 TV: Get the Tracking Manager: 0 and the SteppingVerbose: 0

**Comment by fabiocos** [comment]
+1

**Pull request merged**
