### PR TITLE
bsunanda:Phase2-hgx27  (HE Rebuild integrated with HGCAL)

### PR DESCRIPTION
**Pull request by bsunanda**
The geometry codes for Hcal, several cfi/cff files and the validation code for HGCal is modified to go upto Digi stage for HGCAL with HE rebuild. Subsequent steps are needed in PFlow code.

### CODE REVIEW

**Comment by fratnikov** [comment]
Looks like we have a problem on DIGI step:
Begin processing the 2nd record. Run 1, Event 2, LumiSection 1 at 12-Feb-2015 16:41:43.558 CET
%MSG-e HGCDigitizer:  MixingModule:mix 12-Feb-2015 16:41:43 CET Run: 1 Event: 2
 @ accumulate : can't find HGCHitsHEback collection of g4SimHits

**Comment by bsunanda** [comment]
This is not a problem. This is a false warning. I shall remove this warning at some later stage. For V6 HGCal geometry there is no HGCHitsHEback and this is replaced by standard Hcal HE hits. I tested that using the HGcal validation tools.
________________________________

**Comment by fratnikov** [comment]
please test

**Comment by fratnikov** [comment]
merge

**Pull request merged**
