### PR TITLE
Unique TFormula name

### PR DESCRIPTION
**Pull request by felicepantaleo**
Many TFormulas were created in a for loop with exactly the same name "rr". 
It was verified that the TFormulas are not overwritten, but this causes ROOT to loose track of all of them.  
@tommasoboccali

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by felicepantaleo** [comment]
@cmsbuild Please test again.
The failure of the test has nothing to do with the changes committed.

**Comment by degano** [comment]
@cmsbuild please test

**Comment by ggovi** [comment]
+1

**Comment by mmusich** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
