### PR TITLE
Use the latest geometry option for HB/HE depth indexing

### PR DESCRIPTION
**Pull request by bsunanda**
Just leaving as a PR. It need not be merged for official version

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by mdhildreth** [comment]
please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by ianna** [comment]
@bsunanda and @davidlange6 - is this PR still needed for 6.2.X?

**Comment by ianna** [comment]
@bsunanda and @davidlange6 - please close this PR

**Comment by ianna** [comment]
@bsunanda, @davidlange6 - please close this PR

**Pull request closed without merging**
