### PR TITLE
Add more Pixel tracks SoA monitoring

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

The goal of this PR is two-fold:
   * add more monitoring histograms for SoA Tracks (done in commit 218cbd4153bab0cddc8928f9c127d6e5919b044a)
   * add 1D projections of the 2D scatter plot histograms of GPU vs CPU quantities for selected variables (done in commit 6a143ccddcdb267eb603a9ab97a397714a2abd8c).

#### PR validation:

Run successfully: `runTheMatrix.py -l 21034.507, 20834.507 -t 4 -j 8 --ibeos`

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

N/A

### CODE REVIEW

**Comment by mmusich** [comment]
test parameters:
   * enable_tests = gpu
   * workflows_gpu = 21034.507, 20834.507
   * relvals_opt= -w upgrade
   * relvals_opt_gpu = -w upgrade

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
@cms-sw/dqm-l2 it would be good to have this integrated prior to start testing https://github.com/cms-sw/cmssw/pull/40465. 
Do you have any objections to sign it?

**Comment by rappoccio** [comment]
@cms-sw/dqm-l2 ping on this one as well

**Comment by emanueleusai** [comment]
+1

- adds new plots

**Comment by perrotta** [comment]
+1

**Pull request merged**
