### PR TITLE
PPS: use Run3 era in online DQM

### PR DESCRIPTION
**Pull request by jan-kaspar**
#### PR description:

The era modifier used in online DQM config of PPS is updated to `Run3`. This is a bug fix - currently `Run2_2018` is used.

#### PR validation:

The following command
`cmsRun DQM/Integration/python/clients/ctpps_dqm_sourceclient-live_cfg.py`
was executed on LXPLUS. The process runs without errors (but obviously it cannot find input data).

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
I believe the crash is due to the GT, which is not using the last one compatible with CT-PPS in 

DQM/Integration/python/config/FrontierCondition_GT_cfi.py
->"120X_dataRun3_HLT_Candidate_2021_09_30_19_21_44"

DQM/Integration/python/config/FrontierCondition_GT_autoExpress_cfi.py
->  '120X_dataRun3_Express_Candidate_2021_09_30_18_36_13'

With these GTs above we see no crash in Online DQM at P5 using this PR. 

However since the unitTest done here by the bot is taking run 334393 from 2019, I am not sure if the test will succeed.
Any idea @francescobrivio @tvami ?

**Comment by jfernan2** [comment]
OK, sorry, yes I should have commented in the backport, my apologies.
Anyway, since I am assuming this is a temporary situation, for running in Online DQM at P5, we can tune GT manually until the situation gets stable. Until now we were using autoCond['run3_hlt'] and autoCond['run3_data_express´] resp.

The thing is to get a working version for master and 12_0_X I assume

**Comment by qliphy** [comment]
+1

**Pull request merged**
