### PR TITLE
Update the GPU alpaka workflows

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Update the list of alpaka-based GPU workflows to test all the available ones.

#### PR validation:

All workflows should pass.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

May be backported to 14.0.x to enable testing all workflows there, as well.

### CODE REVIEW

**Comment by fwyzard** [comment]
test parameters:
  - enable = gpu
  - workflows_gpu = 12434.402,12434.403,12434.404,12434.412,12434.422,12434.423,12434.424,12434.492,12450.402,12450.403,12450.404,12461.402,12634.402,12634.403,12634.404,12634.412,12634.422,12634.423,12634.424,12634.492,12650.402,12650.403,12650.404,12661.402

**Comment by fwyzard** [comment]
please test

**Comment by srimanob** [comment]
+Upgrade

**Comment by AdrianoDee** [comment]
+pdmv

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
