### PR TITLE
HCAL 25ns reco update

### PR DESCRIPTION
**Pull request by kfiekas**
Modified negative energy cut and optimized fit limits for Method2

### CODE REVIEW

**Comment by slava77** [comment]
Hi Katharina,

Please include some plots (or a link to a presentation) and a brief summary describing the physics impact of the change.

Thank you.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by kfiekas** [comment]
@slava77  the change mainly improoves the convergence of the fit for very low energy pulses. In addition, it removes the small dip in the single pion response.
rawbarrelhcal_response

**Comment by slava77** [comment]
Hi Katharina and all,

I ran tests in CMSSW_7_5_0_pre5 /test area sign563/.

For response to real things, what I see in response plots in DQM is in agreement with your plot.


However, there is a pretty large increase in the "hcal-only" component with the new reconstruction 
(random noise becomes hits).
I think it is an issue
In the following, I'm using electron gun pt=35 sample to illustrate.

Run1 and Run2 setups differ: there is much more noise picked up in run2
(is there a GT issue in the digitizer that triggers more noise?)
run1 electron 35:
wf17_hcalhits1_ieta

run2 electron 35:
- rechits with E above 1 GeV show a large increase; 
wf1317_hcalhits1_ieta

This recasts in many more distributions
the caloMET RMS practically doubles (MET noise component is up from about 2 to about 5 GeV)
all_sign563vsorig_singleelectron13pt35wf1317p0c_log10recocalomets_calomet__reco_obj_et

the rate of PF neutral hadrons blows up 
all_sign563vsorig_singleelectron13pt35wf1317p0c_log10recopfcandidates_particleflow__reco_obj_pt50

pfMet is slightly less affected than caloMet  (MET noise component is up from ~1 GeV to 2.5 GeV)
all_sign563vsorig_singleelectron13pt35wf1317p0c_log10recopfmets_pfmet__reco_obj_pt

The effect of the noise is clearly much smaller in more realistic events,
but it will still remain significant:
It's an extra smearing and degradation in resolution at low energies as well as an additional inefficiency for particle ID (H/E cuts) and  isolation.

Unless there is a clear benefit that outweighs the impact of the increased noise "particles",
I propose to move this update to 76X release.

@bachtis @jdolen @ahinzmann @lgray @trocino

**Comment by slava77** [comment]
single-muon pt=10
pf isolation changes are not large, but it's still likely a ~1-2% efficiency loss for a cut at 0.1
(with a much smaller effect for higher momenta)
wf1320_pfisorel4

**Comment by slava77** [comment]
Here are several jet-level response plots 

High-et jet response goes up slightly (~1-2%) in both calo and pf jets, looking at 3 TeV dijet sample
wf1313_ak4calo_recoovergen_b
wf1313_ak4pf_recoovergen_b

Response vs genJet pt has a small increase across the board
- dijet flat-pt (no PU) sample
wf1338_ak4calo_corovergen_b_genpt
wf1338_ak4calo_corovergen_e_genpt

the effect is similar in pf
wf1338_ak4pf_corovergen_b_genpt

Similar behavior is in TTbar with PU=35 (25 ns) sample [the statistics is small here though: only 70 events used in the tests]
wf25202_ak4pfchs_corovergen_b_genpt

**Comment by kfiekas** [comment]
PR has been updated to combine the positive effects of PR9154 and PR9481. The changes and the performance of the updated version are described in https://indico.cern.ch/event/400319/contribution/7/material/slides/0.pdf .

**Comment by slava77** [comment]
@cmsbuild please test

@kfiekas Thank you for detailed slides. From the slides it looks like we can integrate it.

**Comment by slava77** [comment]
Looking at the same variables as in the previous iteration https://github.com/cms-sw/cmssw/pull/9481#issuecomment-109617334 there is a clear improvement on the size of the noise pickup.
It's still there, but at a much smaller rate.

run2 single electron sample:
pass-3dbaa7b_wf1317_hcal_hits_e1


all_sign563-pass-3dbaa7bvsorig_singleelectron13pt35wf1317p0c_log10recocalomets_calomet__reco_obj_et

about 2/3 more pf neutral hadrons in these empty events
all_sign563-pass-3dbaa7bvsorig_singleelectron13pt35wf1317p0c_log10recopfcandidates_particleflow__reco_obj_pt50

all_sign563-pass-3dbaa7bvsorig_singleelectron13pt35wf1317p0c_log10recopfmets_pfmet__reco_obj_pt


========
jet response vs gen goes up a bit, smaller effect than in https://github.com/cms-sw/cmssw/pull/9481#issuecomment-109796636

======
compared to https://github.com/cms-sw/cmssw/pull/9481#issuecomment-109617946, the effect on isolation of muons in empty events is now negligible

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/9481	3dbaa7b
- changes in the code are OK (the increased fit limit is a bit ad hoc, but appears to deliver the desired effect of better convergence at lower energies)
- tested locally with higher statistics samples (compared to jenkins tests) in CMSSW_7_5_0_pre5 /test area sign563/, comparisons with the baseline are as expected with a summary presented above
    - there is still a minor increase in the noise pick up, which should be balanced by a larger benefit of getting the real hits in realistic events ... the available DQM/validation plots are not particularly conclusive on this point though; so, I'm relying more on conclusions from HCAL studies as posted by Katharina

**Comment by davidlange6** [comment]
+1

**Pull request merged**
