### PR TITLE
Use of new AlCa GTs for run3 relval in TSG tests

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
#### PR description:

Use of new AlCa GTs for run3 relval in TSG tests
Based on CMSSW_12_3_X_2022-03-07-2300
Requires #37171 

#### PR validation:

TSG tests

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test with #37171

**Comment by tvami** [comment]
urgent
 * this is needed for pre6 IIUC

**Comment by francescobrivio** [comment]
The [failure in the unitTest](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-07b358/22938/unitTests/src/Configuration/PyReleaseValidation/test/test-das-selected-lumis/testing.log) (tanks @tvami for the link to the log 😄) is in the `X509 proxy` parsing, probably related to the cmsweb issues occurred this afternoon (https://cms-talk.web.cern.ch/t/cmsweb-unscheduled-downtime-and-mitigation/7902).

**Comment by Martin-Grunewald** [comment]
+1
DAS error in unit tests unrelated to this PR

**Comment by perrotta** [comment]
+1

**Comment by perrotta** [comment]
merge

**Pull request merged**
