### PR TITLE
[L1T] Backport: New low pt muon LUT

### PR DESCRIPTION
**Pull request by cecilecaillol**
#### PR description:

Backport of https://github.com/cms-sw/cmssw/pull/38315 needed for Phase-2 L1 MC production

New LUT with tighter hwQual requirement for low pt muons (changes to the first PtBin only, gmtTkMuon Pt < 8 GeV)

### CODE REVIEW

**Comment by cecilecaillol** [comment]
please test

**Comment by cecilecaillol** [comment]
please test

**Comment by cecilecaillol** [comment]
+l1

**Comment by qliphy** [comment]
+1

**Pull request merged**
