### PR TITLE
Add missing newlines in Analysis modules

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Add missing newlines at the end of the files under
```

```
.

#### PR validation:

None.

### CODE REVIEW

**Comment by fwyzard** [comment]
please test

**Comment by perrotta** [comment]
+1
- Technical, whitespace-only changes.

**Comment by tvami** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by tjavaid** [comment]
+1

- spurious differences seen from unstable WF `12434.7` (open issue #39803 )

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
