### PR TITLE
Fix gcc9 warning in L1TriggerConfig

### PR DESCRIPTION
**Pull request by mrodozov**
#### PR description:

Fixes warning in L1TriggerConfig

#### PR validation:

Builds without warning

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by fabiocos** [comment]
@rekovic this looks straightforward to me, please cross check and propose a change in case

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Pull request merged**
