### PR TITLE
PPS DQM error plots

### PR DESCRIPTION
**Pull request by fabferro**
#### PR description:

This PR introduces new plots for monitoring the errors in PPS Pixel data taking and unpacking.
The plots are created per FED and per DetId to ease the error understanding and debugging.

#### PR validation:

Use of Run2 data via 136 WFs

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by emanueleusai** [comment]
please test

**Comment by emanueleusai** [comment]
+1

**Comment by emanueleusai** [comment]
If you need this code for the upcoming data taking period, could you please provide a backport to 12_6?

**Comment by perrotta** [comment]
+1

**Comment by fabferro** [comment]
> If you need this code for the upcoming data taking period, could you please provide a backport to 12_6?

Ok. Does this mean that I also have to backport PR #40660 that fixes a bug in error identification at the Event filter level?

**Comment by emanueleusai** [comment]
apologies, my language wasn't precise enough. The backport is needed is you need this PR for the upcoming MWGR. If you need it only for actual collision data, assuming we will use 13_X for that, then a backport to 12_6 is not needed.

**Comment by fabferro** [comment]
> apologies, my language wasn't precise enough. The backport is needed is you need this PR for the upcoming MWGR. If you need it only for actual collision data, assuming we will use 13_X for that, then a backport to 12_6 is not needed.

Ah, ok. Then I'll do no backport.

**Pull request merged**
