### PR TITLE
HLT menu development for `12_4_X` (5/N): HLT V1.3

### PR DESCRIPTION
**Pull request by missirol**
backport of #38816

#### PR description:

Development of HLT menus for `CMSSW_12_4_X`.

This version of the `GRun` HLT menu corresponds to HLT V1.3 for 2022 pp data-taking.

Includes the integration of the following JIRA tickets.

  - [CMSHLT-2261](https://its.cern.ch/jira/browse/CMSHLT-2261): [BPH] added `ParkingDoubleMuonLowMass` (8 PDs, 4 Streams)
  - [CMSHLT-2273](https://its.cern.ch/jira/browse/CMSHLT-2273): [BPH] added `ParkingDoubleElectronLowMass` (6 PDs, 3 Streams)
  - [CMSHLT-2356](https://its.cern.ch/jira/browse/CMSHLT-2356): [HIG] emu control triggers for 4J2B-PNET triggers
  - [CMSHLT-2357](https://its.cern.ch/jira/browse/CMSHLT-2357): [HIG] control triggers for boosted Hbb-PNET triggers
  - [CMSHLT-2359](https://its.cern.ch/jira/browse/CMSHLT-2359): [TSG] cleanup of EventContent of DQM stream
  - [CMSHLT-2362](https://its.cern.ch/jira/browse/CMSHLT-2362): [BPH] `ParkingSingleMuon` PD for 2022
  - [CMSHLT-1716](https://its.cern.ch/jira/browse/CMSHLT-1716): [TSG] set `ThroughputService.dqmPathByProcesses` to `True`
  - [CMSHLT-2371](https://its.cern.ch/jira/browse/CMSHLT-2371): [TSG] backup seeds for Scouting Path
  - [CMSHLT-2358](https://its.cern.ch/jira/browse/CMSHLT-2358): [JME] added AlCaRawLowPt stream for low pT jets
  - [CMSHLT-2390](https://its.cern.ch/jira/browse/CMSHLT-2390): [TSG] merging of Muon and JetMET datasets (`SingleMuon+DoubleMuon=Muon`, `JetHT+MET=JetMET`)
  - [CMSHLT-2361](https://its.cern.ch/jira/browse/CMSHLT-2361): [EXO] triggers for displaced dimuons with large lifetimes
  - [CMSHLT-2382](https://its.cern.ch/jira/browse/CMSHLT-2382): [EXO] backup and monitoring triggers for displaced dimuons with large lifetimes
  - [CMSHLT-2349](https://its.cern.ch/jira/browse/CMSHLT-2349): [HIG] update of VBF-tau monitoring triggers (mu+tau)
  - [CMSHLT-2398](https://its.cern.ch/jira/browse/CMSHLT-2398): [JME] changed PS of `HLT_Photon30EB_TightID_TightIso` from 150 to 6
  - [CMSHLT-2401](https://its.cern.ch/jira/browse/CMSHLT-2401): [TSG] added `drop *` statement to AlCaPPS EventContent
  - [CMSHLT-2391](https://its.cern.ch/jira/browse/CMSHLT-2391): [TSG] cleanup of GRun menu (removal of disabled triggers)
  - [CMSHLT-2404](https://its.cern.ch/jira/browse/CMSHLT-2404): [RPC] update of `maxEta` cut in `AlCa_RPCMuonNormalisation` triggers
  - [CMSHLT-2403](https://its.cern.ch/jira/browse/CMSHLT-2403): [TSG] re-align offline menu with online (seed and PS of GPU-DQM Paths, splitting of Ephemeral PDs)
  - [CMSHLT-2400](https://its.cern.ch/jira/browse/CMSHLT-2400): [JME] added `PFJet110` control trigger
  - [CMSHLT-2402](https://its.cern.ch/jira/browse/CMSHLT-2402): [HIG] update of `HLTMonitor` PD and stream for HLT-PNET monitoring
  - [CMSHLT-2406](https://its.cern.ch/jira/browse/CMSHLT-2406): [BPH] enable new dimuon exclusive triggers (only for double-muon Parking PDs)
  - [CMSHLT-2407](https://its.cern.ch/jira/browse/CMSHLT-2407): [TSG] use noise-cleaned e/gamma SigmaIEtaIEta for Scouting

In addition, the input file used for the HLT-Validation tests in IBs is updated to a recent collisions run:
`/store/data/Run2022B/HLTPhysics0/RAW/v1/000/355/558/00000/cd851cf4-0fca-4d76-b80e-1d33e1371929.root`

#### PR validation:

TSG tests.

#### If this PR is a backport, please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

#38816

Development of HLT menus for 2022 pp data-taking.

### CODE REVIEW

**Comment by missirol** [comment]
please test

**Comment by missirol** [comment]
please test

**Comment by missirol** [comment]
+hlt

**Comment by clacaputo** [comment]
+reconstruction

**Comment by missirol** [comment]
@cms-sw/orp-l2 , a kind ping for the review of this PR.

The PR to `master` tested okay in IBs.

**Comment by qliphy** [comment]
+1

**Pull request merged**
