### PR TITLE
handle error returns from poll() in InitRootHandlers signal handler

### PR DESCRIPTION
**Pull request by dan131riley**
In full_read(), if the call to poll() returned an error the read() on the fd would still be attempted.  Since the error return provides no guarantee that the read() would succeed, this could lead to the signal handler blocking on the read() indefinitely.  This patch treats any error return similar to a timeout, returning without attempting the read.

ref:
https://hypernews.cern.ch/HyperNews/CMS/get/edmFramework/3798/1/1/2.html

### CODE REVIEW

**Comment by Dr15Jones** [comment]
Please test

**Comment by Dr15Jones** [comment]
+1

**Review by bbockelm — CHANGES_REQUESTED** [review]
We should allow the `poll` to be attempted in the case of things like `EAGAIN` or `EINTR`, provided that we continue to respect the overall timeout.

`EINTR`, in particular, can be triggered by `gdb`.

**Comment by Dr15Jones** [comment]
hold
until we resolve Brian's request

**Comment by dan131riley** [comment]
I should get to this early next week.

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
untold

**Comment by Dr15Jones** [comment]
unhold

**Comment by Dr15Jones** [comment]
+1

**Review by bbockelm — APPROVED** [review]
LGTM.

**Comment by davidlange6** [comment]
merge

**Pull request merged**
