### PR TITLE
[Sim][clang-tidy] make deleted function public

### PR DESCRIPTION
**Pull request by smuzaffar**
Cleanup for clang-tidy warning `deleted member function should be public [modernize-use-equals-delete]`

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by srimanob** [comment]
Please test

Give it another try on PR testing.

**Comment by perrotta** [comment]
+1
(@cms-sw/generators-l2 @cms-sw/upgrade-l2  this PR is technical, and changes are quite trivial: just complain in case you have problems with it, and we'll revert it)

**Comment by perrotta** [comment]
merge

**Comment by srimanob** [comment]
+Upgrade

**Comment by agrohsje** [comment]
+generators
Although indeed trivial I didn't want to sign on Friday when the label was still "tests rejected" .  All good now.

**Pull request merged**
