### PR TITLE
Run4-hgx288 Make V16 of HGCAl ready for the SIM step

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Make V16 of HGCAl ready for the SIM step

#### PR validation:

Use the runTheMatrix test workflows and some cfg's in SimG4CMS/Calo/test/python

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
Comparison differences are due to a problem recently fixed by #34409.

**Comment by cvuosalo** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by bsunanda** [comment]
@srimanob Please approve

**Comment by qliphy** [comment]
+1

**Pull request merged**
