### PR TITLE
Allow a boost on particles in MCSingleParticle Filters [90X Backport]

### PR DESCRIPTION
**Pull request by stahlleiton**
Backport of #18532

### CODE REVIEW

**Comment by perrozzi** [comment]
please test

**Comment by govoni** [comment]
please test

**Comment by perrozzi** [comment]
+1

**Comment by govoni** [comment]
+1

**Comment by davidlange6** [comment]
Closing PR. CMSSW_9_0_X development has completed (CMSSW_9_2_X is for data taking)

**Pull request closed without merging**
