### PR TITLE
BPH skim update: adding L1 information

### PR DESCRIPTION
**Pull request by kfjack**
Proposed to add muon L1 information into the output content of BPH skim. Back port from PR #15854.

### CODE REVIEW

**Comment by fabozzi** [comment]
please test

**Comment by kfjack** [comment]
Looks like an IB problem. Should I move back to use an older IB?

**Comment by fabozzi** [comment]
please test

**Comment by fabozzi** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
