### PR TITLE
MTV fast cleaning

### PR DESCRIPTION
**Pull request by mtosi**
#### PR description:
the Multi Track Validator (MTV) is one of the main computational and memory offenders in the VALIDATION step.
there are some not that necessary plots, and with this PR they are removed 
and a new flag has been added in order to make the dzcut related performance plots on-demand

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
Thanks for this PR @mtosi !!
Apart from the plot removal, I see that some histograms are also being modified, mainly efficiencies, I understand they are expected due to the changes introduced, can you confirm?
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_0_X_2021-04-22-1100+13f6e8/42364/dqm-histo-comparison-summary.html

**Comment by jfernan2** [comment]
ping @mtosi

**Comment by silviodonato** [comment]
kind reminder @mtosi

**Comment by mtosi** [comment]
apologies for the delay, there was a "feature" (aka bug), indeed
thanks for the support and patience

it should be fixed, now

**Comment by mtosi** [comment]
I'm going to rebase ....

**Comment by mtosi** [comment]
@cmsbuild, please test

**Comment by qliphy** [comment]
please test

**Comment by jfernan2** [comment]
+1
Thanks a lot @mtosi

**Comment by silviodonato** [comment]
I see that this PR, for example in  `10224.0_TTbar_13+2017PU+TTbar_13TeV_TuneCUETP8M1_GenSim+DigiPU+RecoFakeHLTPU+HARVESTFakeHLTPU+Nano`:
- Remove 660 plots in Tracks.
Specifically, the following 11 plots in 60 subfolders
```
effic_vs_dzpvsigcut
effic_vs_dzpvsigcut2
fakerate_vs_dzpvsigcut
globalEfficiencies
num_assoc(recoToSim)_dzpvsigcut
num_assoc(simToReco)_dzpvsigcut
num_pileup_dzpvsigcut
num_reco_dzpvsigcut
num_simul2_dzpvsigcut
num_simul_dzpvsigcut
pileuprate_dzpvsigcut
```
- Remove 336 plots in TrackTPPtLess09. 
Specifically, the following 6 plots in 56 subfolders
```
effic_vs_dzpvsigcut
effic_vs_dzpvsigcut2
globalEfficiencies
num_assoc(simToReco)_dzpvsigcut
num_simul2_dzpvsigcut
num_simul_dzpvsigcut
```

- Change 60 `globalEfficiencies` plots in Tracks and 56 `globalEfficiencies` plots TrackTPPtLess09 (see example below)

Many of the removed plots were *not* empty.

@mtosi could you confirm that these changes are expected? Thanks


image

**Pull request merged**
