### PR TITLE
Transient vector bugfix

### PR DESCRIPTION
**Pull request by andrewj314**
Bugfix: Added ioread rules to clear transient vectors in DataFormats/TauReco/src/classes_def_2.xml

Hypernews: https://hypernews.cern.ch/HyperNews/CMS/get/physTools/3315/1/1.html

### CODE REVIEW

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cmsbuild the comparisons got stuck, apparently. Please check.

**Comment by nclopezo** [comment]
Hi Slava, 
A glitch in Jenkins killed the comparison, I restarted it.

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/8061	ea1c44d

 tested in CMSSW_7_5_X_2015-03-04-0200 /sign524/ with a longer version of the matrix run by jenkins.

There are no changes in monitored quantities as expected from changes in this code.

**Comment by jpavel** [comment]
Hi @slava77 , can we backport this PR also to 72x ? (it is being used for Phys14 studies and it is there where the problem originally appeared)

**Comment by slava77** [comment]
I guess you'd want this to be in 73X as well.

Please clarify where the issue appears. 
Is it affecting miniAOD workflows (the standard workflow now), or does it show up in more specific analysis tests?

I suggest to make PRs, we can sign off depending on implications.

**Comment by jpavel** [comment]
It affects the analysis workflows (only when one uses fwlite to run analysis on miniAODs). Actually, for this particular analysis it is a blocker as it prevents usage of fwlite to analyze tau strips, so analysts must write c++ code. The other problem is that the problem does not signalize itself at all and only after careful inspection we found that there are actually buggy results. So the motivation would be to prevent such a buggy results for other unaware users.

@andrewj314 Can you prepare PR's for 72x and 73x ?

**Comment by andrewj314** [comment]
You bet! I'm on it.

**Comment by slava77** [comment]
ok, changes with  effects on cases only downstream should be easier to propagate

**Comment by davidlange6** [comment]
+1

**Pull request merged**
