### PR TITLE
bsunanda:Run2-TB08 Add for 8 module version

### PR DESCRIPTION
**Pull request by bsunanda**
This is the second version of 8 module run of HGCal Test Beam

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@ianna Could you approve this?

**Comment by ianna** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
