### PR TITLE
Vertex smearing parameter for early 2017 MC

### PR DESCRIPTION
**Pull request by rmanzoni**
@franzoni @arunhep

### CODE REVIEW

**Comment by arunhep** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
hi- @rmanzoni -could you clarify the need for this addition?

**Comment by rmanzoni** [comment]
92X MC production for early 2017 if I recall correctly.
@franzoni and @arunhep can provide more details

**Comment by franzoni** [comment]
clarified at ORP
documented in the added scenario itself

**Comment by franzoni** [comment]
hello @rmanzoni 
does this scenario need be modified as a consequence of " a cogging correction has been put in place which should have shifted the beamspot by 12mm" , see for details 
https://hypernews.cern.ch/HyperNews/CMS/get/beamspot/159/1.html
 ?

**Comment by rmanzoni** [comment]
Gio, I guess you're right: after the cogging adjustment, Z seems to be constantly below +1 cm...
It might not be the end of the world, but perhaps it's good to take the chance and fix it now?

I can do the change on the fly if you give me green light.

**Comment by franzoni** [comment]
this PR is merged, hence we need another one.
922 might be in the making: I don't know if it's building yet .
@davidlange6 has the process started ?

It would help a lot if we could have the cogging-updared Z beamspot in 922,
so that such release can be used for the relval needed by the measurement of the RECO BS

**Pull request merged**
