### PR TITLE
HLT bugfixes and removal of obsolete menus

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
HLT bugfixes and removal of obsolete menus
Based on CMSSW_10_0_X_2018-01-11-2300.

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
@smuzaffar 
Could you please trigger code-check? For some reason the label does not update.
Thanks!

**Comment by smuzaffar** [comment]
code-checks
@Martin-Grunewald , you can do it yourself. Code  checks can be triggered by any more.

**Comment by Martin-Grunewald** [comment]
+1

**Comment by Martin-Grunewald** [comment]
@Dr15Jones 
Hi Chris,

Please sign for core!

Thanks!

**Comment by Martin-Grunewald** [comment]
@smuzaffar 
Great, thanks!

**Comment by Dr15Jones** [comment]
+1
For addOnTests change

**Comment by fabiocos** [comment]
+1

**Pull request merged**
