### PR TITLE
Run3-hcx377A Correct a few test scripts in CondTools/Geometry

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Correct a few test scripts in CondTools/Geometry

#### PR validation:

Use the runTheMatrix test workflows

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Backported to 14_1_X (in #46387)

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@perrotta Please sign this

**Comment by perrotta** [comment]
+db

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
