### PR TITLE
Make TritonCpuShmResource class compile with C++20

### PR DESCRIPTION
**Pull request by iarspider**
#### PR description:

Title says it all

#### PR validation:

Code compiles

### CODE REVIEW

**Comment by iarspider** [comment]
please test

**Comment by kpedro88** [comment]
thanks @iarspider !

**Comment by makortel** [comment]
Another occurrence of #41200 in workflow 12434.0

**Comment by makortel** [comment]
+heterogeneous

**Comment by perrotta** [comment]
+1

**Pull request merged**
