### PR TITLE
[10.2.X][Update GTs] new JEC MC TAGs + 2D Pixel Templates

### PR DESCRIPTION
**Pull request by lpernie**
Added JEC MC Tags to:
## 2018 MC GT
.  [102X_upgrade2018_design_v7](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/102X_upgrade2018_design_v7/102X_upgrade2018_design_v6)
.  [102X_upgrade2018_realistic_v12](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/102X_upgrade2018_realistic_v12/102X_upgrade2018_realistic_v11)
.  [102X_upgrade2018cosmics_realistic_deco_v11](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/102X_upgrade2018cosmics_realistic_deco_v11/102X_upgrade2018cosmics_realistic_deco_v10)

## 2017 MC GT
.  [102X_mc2017_design_IdealBS_v3](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/102X_mc2017_design_IdealBS_v3/102X_mc2017_design_IdealBS_v4)
.  [102X_mc2017_realistic_v4](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/102X_mc2017_realistic_v4/102X_mc2017_realistic_v3)
.  [102X_mc2017cosmics_realistic_deco_v4](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/102X_mc2017cosmics_realistic_deco_v4/102X_mc2017cosmics_realistic_deco_v3)
.  [102X_mc2017cosmics_realistic_peak_v4](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/102X_mc2017cosmics_realistic_peak_v4/102X_mc2017cosmics_realistic_peak_v3)

Pixel Template + HEFilter add to:
## DataRun2 GT
.  [102X_dataRun2_v4](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/102X_dataRun2_v4/102X_dataRun2_v3)
.  [102X_dataRun2_relval_v5](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/102X_dataRun2_relval_v5/102X_dataRun2_relval_v4)
.  [102X_dataRun2_PromptLike_v7](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/102X_dataRun2_PromptLike_v7/102X_dataRun2_PromptLike_v4)

### CODE REVIEW

**Comment by lpernie** [comment]
please test

**Comment by lpernie** [comment]
please test

**Comment by lpernie** [comment]
please test

**Comment by lpernie** [comment]
+1

**Comment by lpernie** [comment]
backport #24381

**Comment by kpedro88** [comment]
+1

**Pull request merged**
