### PR TITLE
[14_0_X SIM] Optimization of stepping when ZDC is ON

### PR DESCRIPTION
**Pull request by civanch**
#### PR description:
When ZDC simulation is enabled, CPU time for MinBias events increased in ~5.5 times, for ttbar - in ~1.5 times. In this PR some optimization is introduced, which is not significant: ~9% for MinBias and ~3% for ttbar. In the default simulation (ZDC is not enabled), no change is expected. Having not a big improvement, this PR is useful, because remove from simulation relatively rare tracks going out of ZDC, further tracking of these tracks has no sense.

#### PR validation:
private

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by bsunanda** [comment]
@civanch Please hold this PR till my PRs 43546 and 43499 are merged

**Comment by civanch** [comment]
hold

**Comment by civanch** [comment]
Is closed in favor of #43576

**Pull request closed without merging**
