### PR TITLE
HLT menu development for `13_3_X` (1/N)

### PR DESCRIPTION
**Pull request by mmusich**
backport of https://github.com/cms-sw/cmssw/pull/43788

#### PR description:

Development of HLT menus for CMSSW_13_3_X:
   * this is an intermediate update towards the 2024 proton-proton run data-taking
   
This update includes the integration of the following JIRA tickets:
- [CMSHLT-2975](https://its.cern.ch/jira/browse/CMSHLT-2975) [EXO,TSG]: Bug in configuration of `*...NoFiltersNoVertex...*` HLT/MC paths
- [CMSHLT-2982](https://its.cern.ch/jira/browse/CMSHLT-2982) [EXO,TSG]: Misconfiguration of `hltL3fL1DoubleMuf0L2NVf15f7L3SingleMuNVf18DisplacedHybDxy0p1cm`
- [CMSHLT-2979](https://its.cern.ch/jira/browse/CMSHLT-2979) [EXO,HIG,TSG]: Misconfiguration of `hltDiPFJet45MJJ1050` (VBF-parking triggers)
- [CMSHLT-2985](https://its.cern.ch/jira/browse/CMSHLT-2985) [EXO,TSG]: Set `hltStoppedHSCPIterativeCone4CaloJets.srcPVs `to empty `InputTag`
- [CMSHLT-2986](https://its.cern.ch/jira/browse/CMSHLT-2986) [MUO,TSG]: Remove refs to offline products in `MuonIdProducer` instances at HLT

In addition it integrates in the combined table "Special" FOG trigger paths for non-physics production menus and updates table and testing scripts accordigly.
This addresses the following JIRA tickets:
- [CMSHLT-2860](https://its.cern.ch/jira/browse/CMSHLT-2860) [TSG]: The FOG "Ubermenu" (merge of FOG's "special" menus)
- [CMSHLT-2972](https://its.cern.ch/jira/browse/CMSHLT-2972) [TSG]: Circulating, Cosmics, CRUZET, MWGR -- port to 13_3_X

#### PR validation:

TSG integration tests.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Verbatim backport of https://github.com/cms-sw/cmssw/pull/43788 to CMSSW_13_3_X to address FOG data-taking needs for early 2024 data-taking.

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
enable gpu

**Comment by Martin-Grunewald** [comment]
please test

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by rappoccio** [comment]
+1

**Pull request merged**
