### PR TITLE
Update PPS DMD tag, remove deprecated SiStrip DMD tag

### PR DESCRIPTION
**Pull request by francescobrivio**
#### PR description:
As requested in this [CMSTalk post](https://cms-talk.web.cern.ch/t/new-tag-for-pps-pcl/14915), we update the DropBoxMetadata for PPS PCL:
 - `CTPPSRPAlignment_byPCL_v0_prompt` --> `CTPPSRPAlignment_byPCL_v1_prompt`
 - `CTPPPSTimingCalibration_SAMPIC_byPCL_v0_prompt` --> `CTPPPSTimingCalibration_SAMPIC_byPCL_v1_prompt`
 
I also profit of this PR for two further updates of the DMD scripts:
  - Removed the `SiStripApvGainRcdAfterAbortGap` key which is deprecated in favor of `SiStripApvGainAAG` as described in https://github.com/cms-AlCaDB/AlCaTools/issues/77
  - Updated the correct keys in `CondFormats/Common/test/DropBoxMetadataReader.py`

#### PR validation:
Code runs and creates the correct payload.
PayloadInspector link: https://cern.ch/go/f6pG
This payload will be appended to the Express tag
  - Difference wrt Express last IOV: https://cern.ch/go/7RPQ

#### Backport:
Not a backport, but a 12_5_X backport will be opened soon.
A 12_4_X backport might be nice, but not strictly necessay - under discussion.

### CODE REVIEW

**Comment by francescobrivio** [comment]
@cmsbuild please test

**Comment by malbouis** [comment]
+alca

- PR according to description
- passes tests (failures are only the usual message logger and MTD)

**Comment by malbouis** [comment]
+db

**Comment by perrotta** [comment]
+1

**Pull request merged**
