### PR TITLE
Run3-TB39 Update the cfg files, now that the analyzers work with simulation

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

With the changes in bigly, one can run the analyzers, filters in the same step of simulation. The configuration files are updated accordingly

#### PR validation:

Tested with private runs. They are not affecting any production workflows

#### if this PR is a backport please specify the original PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by fabiocos** [comment]
@kpedro88 this PR does not affect production workflows, the tests look to run ok (checked the first one), so I will move it forward without waiting for your signature. Please comment it in case later

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Comment by kpedro88** [comment]
+upgrade

**Pull request merged**
