### PR TITLE
Run2-hcx207 Take care of memory issue in loading constants for calib channels

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Take care of memory issue in loading constants for calibration channels

#### PR validation:

Tested for the loading process and also for standard workflows

#### if this PR is a backport please specify the original PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by abdoulline** [comment]
@bsunanda  thank you for promptly submitting the fix, I'll test it tomorrow morning.

**Comment by abdoulline** [comment]
@bsunanda 
Now it's all fine:  
(1) Calib. DB container is initiated with size 929 
(2) re-dumping of both QIETypes and QIEData conditions is fine with all HOX/HBX/HEX channels included

**Comment by cvuosalo** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
