### PR TITLE
Use ZDC digis in uGT DQM

### PR DESCRIPTION
**Pull request by dinyar**
#### PR description:

Add unpacked ZDC digis to uGT DQM. This was overlooked when the ZDC unpacker was added to CMSSW.

attn: @aloeliger @epalencia @vukasinmilosevic

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by syuvivida** [comment]
Hi @dinyar could you create a backport to this PR? In addition, if we want to test this PR in a playback machines online, do you have a suggestions regarding which run to use?
Thanks!!

**Comment by aloeliger** [comment]
@dinyar Do you know whether we would need to modify the unpacking sequence described here: https://github.com/cms-sw/cmssw/blob/master/DQM/Integration/python/clients/l1temulator_dqm_sourceclient-live_cfg.py

DQM directly uses the `RawToDigi` standard L1 sequence, which when I looked at it doesn't include the ZDC unpacker explicitly. I didn't see a setup file for it under `EventFilter` either, so I'm not sure if this is genuinely run in the unpacker stage...

**Comment by dinyar** [comment]
> @dinyar Do you know whether we would need to modify the unpacking sequence described here: https://github.com/cms-sw/cmssw/blob/master/DQM/Integration/python/clients/l1temulator_dqm_sourceclient-live_cfg.py
> 
> DQM directly uses the `RawToDigi` standard L1 sequence, which when I looked at it doesn't include the ZDC unpacker explicitly. I didn't see a setup file for it under `EventFilter` either, so I'm not sure if this is genuinely run in the unpacker stage...

I *think* we don't have to explicitly call the ZDC unpacker, because we use the unpacked uGT  inputs which should include the ZDC digis if the modifications made to that unpacker were correct..

**Comment by aloeliger** [comment]
@dinyar I did some more research after I wrote that, and I think they wrote themselves into the GT setup so it should be okay.

**Comment by tjavaid** [comment]
+1

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
