### PR TITLE
fix vertex validation@HLT

### PR DESCRIPTION
**Pull request by mtosi**
back-port of PR https://github.com/cms-sw/cmssw/pull/14702

### CODE REVIEW

**Comment by VinInn** [comment]
@cmsbuild , please test

**Comment by mtosi** [comment]
these errors are triggered by the fact that the validation of the tracking and vertexing @HLT are run on a workflow where no tracking and vertex reco are done @HLT

**Comment by dmitrijus** [comment]
+1
The old one, but I believe still a necessary change.

**Comment by dmitrijus** [comment]
please test

**Comment by dmitrijus** [comment]
please test

**Pull request closed without merging**
