### PR TITLE
Updated configurations in Alignment to new MessageLogger syntax

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

All configurations in Alignment subsystem which explicitly create a MessageLogger have been converted to the new syntax.
#### PR validation:

All files were passed to `python` and no failures as a result of these change were seen.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
ping @cms-sw/alca-l2

**Comment by yuanchao** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
