### PR TITLE
CTPPS Pixel unpacker patch (backport)

### PR DESCRIPTION
**Pull request by fabferro**
adding small patch in the unpacker to prevent corrupted row/col from making the jobs crash (as in PR #20120 )

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/20121	3529436
- the same change as in 92X; fixes the issue reported in t0 processing in https://hypernews.cern.ch/HyperNews/CMS/get/recoDevelopment/1545.html
- jenkins tests pass
- local test in 928 with a crashing job confirms that the fix works and there are no problems downstream.

**Comment by slava77** [comment]
urgent

a rough guess is that we may start having o(1%) failure rate per job in promptreco without this fix.

**Comment by slava77** [comment]
backport of #20120

**Comment by davidlange6** [comment]
+1

**Pull request merged**
