### PR TITLE
Backport RNTuple NanoAOD output module from ROOT6 branch

### PR DESCRIPTION
**Pull request by smuzaffar**
backport of https://github.com/cms-sw/cmssw/pull/33825
#33825 was included in 12.0.ROOT6 (which was based on root 6.24) to add new output module that generates ROOT RNTuple NanoAODs. As cmssw 13.0.X now uses root 6.26, so lets backport these changes to  master branch.

FYI @mxxo

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@cms-sw/xpog-l2 , can you please review this. These are the changes we had in root/master based CMSSW ROOT6 IBs (please see https://github.com/cms-sw/cmssw/pull/33825 ).

**Comment by swertz** [comment]
Thanks @smuzaffar , it's good to have it in master even if it's not quite production ready yet (and there are no tests running it). It will make future developments easier.

The only thing I was wondering is whether we should synchronize it will all the branch types now supported in master, see https://github.com/cms-sw/cmssw/blob/master/DataFormats/NanoAOD/interface/FlatTable.h#L40

**Comment by swertz** [comment]
> I would suggest to add all these in a separate plugin e.g move all the newly added files under PhysicsTools/NanoAOD/plugins/rntuple and update PhysicsTools/NanoAOD/plugins/BuildFile.xml to create a new plugin out of these files. This way it will not interfere with existing plugin.

Yes, that sounds good. That way it's clear it's not production-ready yet (we cannot even add test workflows for it yet).

**Comment by makortel** [comment]
> That way it's clear it's not production-ready yet (we cannot even add test workflows for it yet).

Umm, why (after this PR gets merged) a test workflow using it could not be added?

**Comment by swertz** [comment]
> Umm, why (after this PR gets merged) a test workflow using it could not be added?

AFAIU it is not yet production ready because of the missing backfilling feature in RNTuple (creating branches on the fly and filling them with a default value for all previous events seen in a file)... Still, if you're fine with having a test workflow as it is now, we can consider it...

**Comment by swertz** [comment]
Hi @smuzaffar , will you then do what you suggested above?

> move all the newly added files under PhysicsTools/NanoAOD/plugins/rntuple

**Comment by vlimant** [comment]
@smuzaffar : are you going forward with the changes mentioned ?

**Comment by smuzaffar** [comment]
> @smuzaffar : are you going forward with the changes mentioned ?

done

**Comment by smuzaffar** [comment]
please test

**Comment by perrotta** [comment]
+1

**Pull request merged**
