### PR TITLE
merge from clang branch for RecoTracker/TkDetLayers

### PR DESCRIPTION
**Pull request by VinInn**
I do understand even less here: looks that tin the HEAD some of the most obvious bugs where fixed already!

### CODE REVIEW

**Comment by davidlt** [comment]
I did some work on Clang fixes back in November and all went into plain CMSSW. There are only 4 packages left to fix if compiled with Clang pre-3.6, which is available in DEVEL IBs for testing. I just queued fixes for 3 packages and the last one of `DataFormats/Math` (about to start working on it). 

If this is correct and no new breakage will be visible I will propose updating Clang in the main branch and nuking the current CLANG branch (i.e., making it equal to plain CMSSW).

**Comment by Dr15Jones** [comment]
I second the nuke plan. :)

**Comment by slava77** [comment]
are we still going to know all the million warnings without a _CLANG_ ? will the main branch just be built with clang in addition to the gcc?

**Comment by Dr15Jones** [comment]
We'd still build with clang in its own 'release' but we'd just make sure the main git branch and the clang git branch are identical.

**Comment by davidlt** [comment]
"Nuke" means drop current content of CLANG branch as it's too rotten/stale, and then build plain CMSSW, which should have all fixes for Clang integrated.

**Comment by VinInn** [comment]
+1 for the nuke.
the clang branch is confusing.

**Comment by slava77** [comment]
Sorry, I got confused by changes that were made but not propagated or not necessary.
Is this PR still needed (fixing anything)?

**Comment by VinInn** [comment]
It fixes the hiding warning about DiskSectorBounds::inside

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/7217	 5967075
this just removes unused variable /function. jenkins compiles -> good

**Pull request merged**
