### PR TITLE
remove SiOuterTracker dqm and validation packages

### PR DESCRIPTION
**Pull request by sroychow**
#### PR description:

This is a follow up of #43857 . Here ```DQM/SiOuterTracker``` & ```Validation/SiOuterTrackerV``` are removed. All the plugins have already been moved to corresponding package with names ```SiTrackerPhase2``` in #43857 . 

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:
Not needed.

### CODE REVIEW

**Comment by sroychow** [comment]
please test

**Comment by sroychow** [comment]
please test

**Comment by sroychow** [comment]
@smuzaffar  failures are due to #45116 ? should I re-run the tests?

**Comment by smuzaffar** [comment]
these failures are not due to #45116. Error is 
```
ModuleNotFoundError: No module named 'Validation.SiOuterTrackerV.SiOuterTrackerMCHarvesting_cff' 
```

which you have remived in this PR. If Validation/SiOuterTrackerV/oython.SiOuterTrackerMCHarvesting_cff.py is not needed then all ref to it should be removed

**Comment by sroychow** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by sroychow** [comment]
@cms-sw/dqm-l2 can you please review?

**Comment by tjavaid** [comment]
+1

**Pull request merged**
