### PR TITLE
Remove redundant unique_ptr constructor calls from L1Trigger

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

This PR is a follow-up to #27097 to remove now-redundant calls to `unique_ptr` constructor.

I also removed redundant exception throws from `PackingSetupFactory` (`PluginFactory::create()` already throws for missing plugin).

#### PR validation:

Code compiles.

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by kpedro88** [comment]
+upgrade

**Comment by fabiocos** [comment]
@rekovic this PR is technical and looks straightforward to me. I will integrate it in next IB, please have a look at it anyway and comment in case

**Comment by rekovic** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
