### PR TITLE
[14_0_X backport] Stop `dz` from being `NaN` in `PackedCandidates`

### PR DESCRIPTION
**Pull request by swagata87**
Backport of https://github.com/cms-sw/cmssw/pull/45009, as discussed in https://github.com/cms-sw/cmssw/issues/44976#issuecomment-2125654589

### CODE REVIEW

**Comment by swagata87** [comment]
type pf

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by vlimant** [comment]
+1

**Comment by rappoccio** [comment]
+1

**Pull request merged**
