### PR TITLE
[UBSAN] fix zero size array runtime error

### PR DESCRIPTION
**Pull request by smuzaffar**
UBSAN IBs generates runtime errors [a]. This change should fix these error. UBSAN complains here https://github.com/cms-sw/cmssw/blob/master/L1Trigger/DTTriggerPhase2/src/MuonPathAssociator.cc#L122-L127 and this can happen when any of `SL1metaPrimitives` or `SL3metaPrimitives` is zero size

[a]
https://cmssdt.cern.ch/SDT/jenkins-artifacts/ubsan_logs/CMSSW_13_2_X_2023-05-22-2300/
- 22 L1Trigger/DTTriggerPhase2/src/MuonPathAssociator.cc:122:48: runtime error: variable length array bound evaluates to non-positive value 0
- 20 L1Trigger/DTTriggerPhase2/src/MuonPathAssociator.cc:125:48: runtime error: variable length array bound evaluates to non-positive value 0

### CODE REVIEW

**Comment by aloeliger** [comment]
@smuzaffar I'm afraid I'm not as familiar with this part of L1 code, but this would seem to me to be a fundamental change in function?

**Comment by smuzaffar** [comment]
@aloeliger , correct this is a  fundamental change in function. Someone should review this code. To me continuing the loop if either `SL1metaPrimitives or SL3metaPrimitives` is empty does not make any sense.

**Comment by aloeliger** [comment]
> @aloeliger , correct this is a fundamental change in function. Someone should review this code. To me continuing the loop if either `SL1metaPrimitives or SL3metaPrimitives` is empty does not make any sense.

@smuzaffar That's very probably true. I can take a look tomorrow myself, and see if I know an expert who can also weigh in. Does this have a timescale like the ppc fix?

**Comment by folguera** [comment]
I can look at it tomorrow

**Comment by perrotta** [comment]
type bug-fix

**Comment by aloeliger** [comment]
@folguera If you are okay with it, then I will sign off on it.

**Comment by folguera** [comment]
I think the fix is OK, however, there are similar errors on L989 that should be fixed, should we create another PR or should we include this here @smuzaffar I've created a PR to your branch with my proposed solutions https://github.com/smuzaffar/cmssw/pull/3

**Comment by perrotta** [comment]
> @smuzaffar Apologies, this is off topic, however I was reminded reading this, @cecilecaillol would like to be removed from the l1-l2 github organization, and off of buildbot's ping/permission list. What does it take to do that?

Here is the bot pr to do so: https://github.com/cms-sw/cms-bot/pull/1999

**Comment by smuzaffar** [comment]
thanks @folguera , I have merged your https://github.com/smuzaffar/cmssw/pull/3

**Comment by smuzaffar** [comment]
please test

**Comment by aloeliger** [comment]
> I think the fix is OK, however, there are similar errors on L989 that should be fixed, should we create another PR or should we include this here @smuzaffar I've created a PR to your branch with my proposed solutions [smuzaffar#3](https://github.com/smuzaffar/cmssw/pull/3)

Okay, then this is good by me. I'll sign when the tests come back.

**Comment by AdrianoDee** [comment]
+1

**Comment by aloeliger** [comment]
+l1

**Comment by perrotta** [comment]
+1

**Pull request merged**
