### PR TITLE
Extruded Polygone Visualization

### PR DESCRIPTION
**Pull request by ianna**
* Interface between DDExtrudedPolygone and TGeo shape

@bsunanda - FYI.

The shape definition in DDL XML and its view in cmsShow:
```
		<ExtrudedPolygon name="extrudedpgon">
		  <XYPoint x="-30*cm" y="-30*cm"/>
		  <XYPoint x="-30*cm" y=" 30*cm"/>
		  <XYPoint x=" 30*cm" y=" 30*cm"/>
		  <XYPoint x=" 30*cm" y="-30*cm"/>
		  <XYPoint x=" 15*cm" y="-30*cm"/>
		  <XYPoint x=" 15*cm" y=" 15*cm"/>
		  <XYPoint x="-15*cm" y=" 15*cm"/>
		  <XYPoint x="-15*cm" y="-30*cm"/>
		  <ZXYSection z="-60*cm" x="0*cm" y="30*cm" scale="0.8*cm"/>
		  <ZXYSection z="-15*cm" x="0*cm" y="-30*cm" scale="1.*cm"/>
		  <ZXYSection z="10*cm" x="0*cm" y="0*cm" scale="0.6*cm"/>
		  <ZXYSection z="60*cm" x="0*cm" y="30*cm" scale="1.2*cm"/>
		</ExtrudedPolygon>

```
screenshot 2017-05-04 17 07 15

@davidlange6 and @civanch - this PR is based on https://github.com/cms-sw/cmssw/pull/18552

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by alja** [comment]
+1
Wonderful!

**Comment by ianna** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
