### PR TITLE
Improve CSC digi print-out

### PR DESCRIPTION
**Pull request by dildick**
#### PR description:

Improve CSC digi print-out. 

#### PR validation:

Code compiles. Tested with 11634.0.

```
11634.0_TTbar_14TeV+2021+TTbar_14TeV_TuneCP5_GenSim+Digi+Reco+HARVEST+ALCA Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Fri Feb 26 12:39:02 2021-date Fri Feb 26 11:57:24 2021; exit: 0 0 0 0 0
1 1 1 1 1 tests passed, 0 0 0 0 0 failed
```

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

there are DAS errors not related to this PR

**Comment by qliphy** [comment]
+1

**Comment by qliphy** [comment]
merge

**Pull request merged**
