### PR TITLE
`PhotonXGBoostEstimator` : set `XGBoost` to use one thread to avoid spawning hundreds of OpenMP threads

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

Title says it all, see #44923 for details

#### PR validation:

Run the script https://github.com/cms-sw/cmssw/issues/44923#issuecomment-2128937695 and verified with `gdb` and `info threads` that the amount of threads is limited, see also https://github.com/cms-sw/cmssw/issues/44923#issuecomment-2130124566 and https://github.com/cms-sw/cmssw/issues/44923#issuecomment-2130273419

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Not a backport to be backported to 14.0.X for data-taking purposes

### CODE REVIEW

**Comment by mmusich** [comment]
type egamma, bug-fix

**Comment by mmusich** [comment]
enable gpu

**Comment by mandrenguyen** [comment]
+1

**Comment by francescobrivio** [comment]
@cms-sw/orp-l2  @cms-sw/core-l2 could we merge this asap so that we can have an IB with this PR?
The backport #45043 is needed for a semi-urgent patch for HLT.

**Comment by VinInn** [comment]
to be precise in the worse case on a HLT Milan machine the total number of threads spawn by openMP will be 65280
(255*256)

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
