### PR TITLE
run stage1 emulator for l1t dqm

### PR DESCRIPTION
**Pull request by jingyucms**

### CODE REVIEW

**Comment by jingyucms** [comment]
@mulhearn need ValL1Emulator_cff.py to run Stage1 emulator and also need L1Compare.cc handle isolated tau, DQM is going to use these changes.
@deguio make stage1 emulator histograms in L1TdeGCT.cc

**Comment by jingyucms** [comment]
@cmsbuild Please test again

**Comment by jingyucms** [comment]
@cmsbuild Please test again

**Comment by deguio** [comment]
-1
ciao @jingyucms 
I would like to see this one merged in 75 first. please see my comments at:
https://github.com/cms-sw/cmssw/pull/9143

rejecting for now.
ciao,
F.

**Comment by deguio** [comment]
+1

**Comment by jingyucms** [comment]
Hi @mulhearn 
Can you review and approve this.
Cheers
Jingyu

**Comment by deguio** [comment]
+1

**Comment by mulhearn** [comment]
+1

**Comment by deguio** [comment]
ciao @jingyucms 
the application l1tstage1emulator_dqm_sourceclient-live_cfg.py crashes on the playback with error:
http://fu-c2f13-41-01:9215/utils/show_log/dqm-source-state-run247398-hostfu-c2f13-41-01-pid075428
(tunnel to p5 needed)
could you have a look please?

**Comment by jingyucms** [comment]
ciao @deguio 
Can you let know which release are you running and which PR you have checked out? I cannot repeat this error. Under:
fu-c2f13-41-03: /home/l1tlocal/Jingyu/CMSSW_7_4_6/src/DQM/Integration/python/test, I downloaded cms-merge-topic 9118 and run l1tstage1emulator_dqm_sourceclient-live_cfg.py and It seems have no problem. 
Cheers
Jingyu

**Comment by deguio** [comment]
ciao @jingyucms 
this is what I did as well. 746 is used.
did you try with pp_run runkey?
F.

**Comment by deguio** [comment]
forget about it. it was my fault. everything seems ok now.
sorry for the noise

**Comment by deguio** [comment]
this one is in use on the online prod system

**Comment by davidlange6** [comment]
+1

**Pull request merged**
