### PR TITLE
Backport for OuterTrackingMonitorTrackingParticle

### PR DESCRIPTION
**Pull request by emacdonald16**
#### PR description:
Heavily modified nLayers variable; runs much faster now (~2.5 s/evt at 200PU, compared to ~400)

#### PR validation:
Compared output file before and after changes, and they were identical. Only difference is in run time.

#### if this PR is a backport please specify the original PR:
Original PR: #27090

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by fabiocos** [comment]
@emacdonald16 is this backport needed because of the UL processing validation?

**Comment by emacdonald16** [comment]
@fabiocos What is the UL processing validation? I thought a backport would be necessary since it was first reported in #26915 that the producer ran very slow at high PU. @jfernan2 also voted for the backport in the original PR, #27090.

**Comment by fabiocos** [comment]
+1

**Pull request merged**
