### PR TITLE
Get compressed LHE weights in Pythia8GeneratorFilter

### PR DESCRIPTION
**Pull request by mseidel42**
This is needed to read the compressed weights format via the Pythia8Interface.
It is used by the Powheg-RES generator.

### CODE REVIEW

**Comment by perrozzi** [comment]
@intrepid42 can you please clone this PR to 90X?

**Comment by perrozzi** [comment]
please test

**Comment by intrepid42** [comment]
@perrozzi Yes, I will create a PR for 90X, and also backport to 71X so that we have the bb4l working everywhere

**Comment by perrozzi** [comment]
+1

**Comment by intrepid42** [comment]
@davidlange6 Could you merge this PR, please?

It is needed to read the compressed LHE weights format used in the Powheg-res/bb4l generator (the Pythia UserHook code for showering is already merged here: https://github.com/cms-sw/cmssw/pull/16546)

**Pull request closed without merging**
