### PR TITLE
use edm::createGlobalIdentifier instead of boost::uuids::random_generator

### PR DESCRIPTION
**Pull request by slava77**
This is a follow up to https://github.com/cms-sw/cmsdist/issues/5657

All 3 cases were using ```boost::uuids::random_generator``` to generate a random string.
Somewhat equivalent functionality is available as ```edm::createGlobalIdentifier```.

I only tested that the problematic case described in https://github.com/cms-sw/cmsdist/issues/5657 runs with this update

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by pohsun** [comment]
+1

**Comment by ggovi** [comment]
+1

**Comment by silviodonato** [comment]
please test

**Comment by silviodonato** [comment]
+1

**Pull request merged**
