### PR TITLE
Fix D51 and D52 reco geometry configurations after #28500

### PR DESCRIPTION
**Pull request by fabiocos**
#### PR description:

The code reorganization implied by #28500 was not taken into account in #28503 that was developed and integrated in parallel. This causes the newly added test workflows 23634.0 and 24034.0 to crash. This PR fixes the reco geometry configuration.

#### PR validation:

```
18:23 cmsdev25 2854> less runall-report-step123-.log 
23634.0_TTbar_14TeV+TTbar_14TeV_TuneCUETP8M1_2026D51_GenSimHLBeamSpotFull14+DigiFullTrigger_2026D51+RecoFullGlobal_2026D51+HARVESTFullGlobal_2026D51 Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED  - time date Wed Dec  4 18:18:04 2019-date Wed Dec  4 18:03:23 2019; exit: 0 0 0 0
24034.0_TTbar_14TeV+TTbar_14TeV_TuneCUETP8M1_2026D52_GenSimHLBeamSpotFull14+DigiFullTrigger_2026D52+RecoFullGlobal_2026D52+HARVESTFullGlobal_2026D52 Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED  - time date Wed Dec  4 18:18:04 2019-date Wed Dec  4 18:03:23 2019; exit: 0 0 0 0
2 2 2 2 tests passed, 0 0 0 0 failed
```

### CODE REVIEW

**Comment by fabiocos** [comment]
please test workflow 23634.0,24034.0

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
abort

**Comment by smuzaffar** [comment]
please test workflow 23634.0,24034.0

**Comment by fabiocos** [comment]
please test workflow 23634.0,24034.0

**Comment by fabiocos** [comment]
+1

Changes are unrelated to this PR

**Comment by fabiocos** [comment]
@smuzaffar there is something I do not understand in the report fo the bot, the list of added merges includes things that should ne already in the baseline

**Comment by fabiocos** [comment]
merge

**Comment by smuzaffar** [comment]
looks like tests were run against 11.0.X. I am checking why it happened.

**Comment by kpedro88** [comment]
+upgrade

**Comment by cvuosalo** [comment]
+1

**Pull request merged**
