### PR TITLE
Migrate BMixingModule and EcalShapeBase-derived classes to esConsumes

### LINKED ISSUE #221: Migrate last pieces of MixingModule and PreMixingModule to esConsumes
Done in https://github.com/cms-sw/cmssw/pull/34902

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

Part of #31061. This PR should cover the last uses of the deprecated `EventSetupRecord::get()` in `MixingModule` and `PreMixingModule`. In addition I removed all bare `new` calls from `EcalMixingModuleValidation`.

In `EcalDigiProducer` and `EcalDigiProducer_Ph2` (used by `MixingModule` and `PreMixingModule`) the changes were in `APDShape`, `EBShape`, and `EBShape` classes, that are also used several places outside of the `MixingModule`s.

Within the `BMixingModule` infrastructure there are still some calls in `DataMixingModule` that would either need to be migrated or removed (in a timescale of 9 months or so). I'm not planning to touch those.

Resolves https://github.com/makortel/framework/issues/221

#### PR validation:

Code compiles.

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by slava77** [comment]
@makortel 
I'm struggling to associate the changes related to `EcalShapeBase` and derived classes with mixingModule in the title. The PR description isn't making it more clear either.

**Comment by slava77** [comment]
+reconstruction

for https://github.com/cms-sw/cmssw/pull/34902	89a4f12
- code changes in reco code follow the changes in the interface of the `EBShape` and `EEShape` classes, including the consumesCollector percolation
    - The PR title and description look a bit as if the commits are not on the subject; some improvement to both may be useful
- jenkins tests pass and comparisons with the baseline show no relevant differences

**Comment by makortel** [comment]
> I'm struggling to associate the changes related to `EcalShapeBase` and derived classes with mixingModule in the title. The PR description isn't making it more clear either.

They are used in `EcalDigiProducer` and `EcalDigiProducer_Ph2`, that are used by `MixingModule` and `PreMixingModule`. I added the following to the PR description.

> In `EcalDigiProducer` and `EcalDigiProducer_Ph2` (used by `MixingModule` and `PreMixingModule`) the changes were in `APDShape`, `EBShape`, and `EBShape` classes, that are also used several places outside of the `MixingModule`s.

**Comment by jfernan2** [comment]
+1

**Comment by tvami** [comment]
+alca 
* I assume the `EventSetupRecord::get` warnings will be touched on in a separate PR
* I second Slava's comment about the update of the title and PR description

**Comment by makortel** [comment]
> * I assume the `EventSetupRecord::get` warnings will be touched on in a separate PR

I strongly hope this will be done by the authors or maintainers of the corresponding code.

**Comment by civanch** [comment]
+1

**Comment by makortel** [comment]
I see there are conflicts now, fixing.

**Comment by makortel** [comment]
Rebased on top of CMSSW_12_1_X_2021-08-19-1100.

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by jfernan2** [comment]
+1

**Comment by tvami** [comment]
+alca

**Comment by civanch** [comment]
+1

**Comment by slava77** [comment]
+reconstruction

for https://github.com/cms-sw/cmssw/pull/34902	9ebd1a9 
- this was rebased since the last reco signoff; the rebase apparently affected only Validation/EcalDigis/
- jenkins tests pass

**Comment by makortel** [comment]
@cms-sw/l1-l2 Could you review and sign, please?

**Comment by makortel** [comment]
ping @cms-sw/l1-l2

**Comment by makortel** [comment]
ping @cms-sw/l1-l2

**Comment by makortel** [comment]
ping @cms-sw/l1-l2

**Comment by tvami** [comment]
Hi @perrotta @qliphy since this PR waits on the L1 signature for more than 10 days, would you consider merging the PR without it?

**Comment by rekovic** [comment]
+1

**Comment by perrotta** [comment]
please test
(to refresh them)

**Comment by smuzaffar** [comment]
please test

**Comment by perrotta** [comment]
+1

**Pull request merged**
