### PR TITLE
Adding cosmics path for HLT validation (106X)

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
#### PR description:

Adding cosmics path for HLT validation (106X)
Based on CMSSW_10_6_X_2019-10-06-2300.

#### PR validation:

TSG tests

#### if this PR is a backport please specify the original PR:

#28125

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
backport of #28125

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
