### PR TITLE
New plots for the Strips PI

### PR DESCRIPTION
**Pull request by jozzez1**
@mmusich 

Would like to merge the new plots per layer for the payload inspector. They're done using tracker topology.

### CODE REVIEW

**Comment by mmusich** [comment]
Hi @jozzez1 
there is gonna be conflicts with my other PR on the same code: https://github.com/cms-sw/cmssw/pull/20184, do you mind if I cherry-pick your commits there?

**Comment by jozzez1** [comment]
@mmusich no problem, it's. Perhaps I can close the PR and try to merge your branch with mine and then make a PR against your branch.

**Comment by jozzez1** [comment]
Will let Marco make a with my changes.

**Comment by mmusich** [comment]
@jozzez1 I've cherry-picked your commits at #20184

**Pull request closed without merging**
