### PR TITLE
HLT scouting event content and producers [80X]

### PR DESCRIPTION
**Pull request by kpedro88**
#### PR description:

While producing private signal samples for analysis with the Run 2 HLT scouting data, we noticed that the scouting collections were not present in the output files when following the UL16 MC recipe (unlike UL17 and UL18, which do have scouting collections). There were two contributing factors:
1. The producers for the scouting collections were not in the MC HLT menu.
2. The event content definitions did not include the scouting collection names.

This PR solves both issues. (Thanks to @dsperka for providing an updated HLT menu with the producers included, from which I extracted only the relevant and necessary configurations and added them to the existing menu.)

No content is changed; just new scouting collections are added. Therefore, this should be a viable update for future UL16 MC requests.

#### PR validation:

Reran private signal production and observed the desired collections with the expected content (jets, etc.).

attn: @tresreid @cericeci

### CODE REVIEW

**Comment by kpedro88** [comment]
please test

**Comment by missirol** [comment]
-hlt

Files for HLT menus and EventContent are updated via scripts (this is done by TSG), and they are not meant to be edited manually by users. In this particular case, what is needed is likely a backport of https://github.com/cms-sw/cmssw/pull/21297 (not verbatim). I will need to take a closer look next week.

**Comment by missirol** [comment]
#40708 supersedes this PR.

**Comment by perrotta** [comment]
> #40708 supersedes this PR.

**Pull request closed without merging**
