### PR TITLE
Updating Data GT for 2015 Run2 EOY Re-Reco

### PR DESCRIPTION
**Pull request by mmusich**
# Summary of changes in Global Tags
## RunII simulation
- **RunII Ideal scenario** : [76X_mcRun2_design_v13](https://cms-conddb.cern.ch/browser/#list/Prod/gts/76X_mcRun2_design_v13) as [76X_mcRun2_design_v12](https://cms-conddb.cern.ch/browser/#list/Prod/gts/76X_mcRun2_design_v12) with the following [changes](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/76X_mcRun2_design_v12/76X_mcRun2_design_v13): 
  -  adding additional labels for Castor SIM geometry 
- **RunII Asymptotic scenario** : [76X_mcRun2_asymptotic_v13](https://cms-conddb.cern.ch/browser/#list/Prod/gts/76X_mcRun2_asymptotic_v13) as [76X_mcRun2_asymptotic_v12](https://cms-conddb.cern.ch/browser/#list/Prod/gts/76X_mcRun2_asymptotic_v12) with the following [changes](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/76X_mcRun2_asymptotic_v12/76X_mcRun2_asymptotic_v13): 
  - adding additional labels for Castor SIM geometry 
- **RunII Startup scenario** : [76X_mcRun2_startup_v12](https://cms-conddb.cern.ch/browser/#list/Prod/gts/76X_mcRun2_startup_v12) as [76X_mcRun2_startup_v11](https://cms-conddb.cern.ch/browser/#list/Prod/gts/76X_mcRun2_startup_v11) with the following [changes](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/76X_mcRun2_startup_v11/76X_mcRun2_startup_v12): 
  -  adding additional labels for Castor SIM geometry 
- **RunII Heavy Ions scenario** : [76X_mcRun2_HeavyIon_v13](https://cms-conddb.cern.ch/browser/#list/Prod/gts/76X_mcRun2_HeavyIon_v13) as [76X_mcRun2_HeavyIon_v12](https://cms-conddb.cern.ch/browser/#list/Prod/gts/76X_mcRun2_HeavyIon_v12) with the following [changes](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/76X_mcRun2_HeavyIon_v12/76X_mcRun2_HeavyIon_v13): 
  - adding additional labels for Castor SIM geometry 
  - updated centrality table for HFtowers in 200 bins 
  - updated underlying event table with latest estimations from PbPb first collisions 
  - updated JEC with HI tracking 
  - updated L1T menu with the version used in PbPb collisions 
  - introducing L1T calo params configuration for HI 
## RunI data
- **RunI HLT processing** : [75X_dataRun1_HLT_frozen_v10](https://cms-conddb.cern.ch/browser/#list/Prod/gts/75X_dataRun1_HLT_frozen_v10) as [75X_dataRun1_HLT_frozen_v9](https://cms-conddb.cern.ch/browser/#list/Prod/gts/75X_dataRun1_HLT_frozen_v9) with the following [changes](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/75X_dataRun1_HLT_frozen_v9/75X_dataRun1_HLT_frozen_v10): 
  - adding negative energy filter payload
- **RunI Offline processing** : [76X_dataRun1_v13](https://cms-conddb.cern.ch/browser/#list/Prod/gts/76X_dataRun1_v13) as [76X_dataRun1_v11](https://cms-conddb.cern.ch/browser/#list/Prod/gts/76X_dataRun1_v11) with the following [changes](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/76X_dataRun1_v11/76X_dataRun1_v13): 
  - **with updates for 2015 data Run2 EOY re-reco**
  - updated lumi based beamspot 
  - updated Tracker alignment (including APE and surface deformations) 
  - updated DT,CSC and muon GPR alignment - updated DT vdrif an ttrig 
  - updated CSC electronics caibrations 
  - updated SiStrip bad channel and particle gain 
  - updated Hcal gains and response corrections 
  - updated Castor local reco calibration for 0T re-reco 
  - updated Ecal IC, AdcToGeV, time calibrations, alignment and preshower intercalibrations 
  - updated centrality table with HFtowers label
## RunII data
- **RunII HLT processing** : [75X_dataRun1_HLT_frozen_v10](https://cms-conddb.cern.ch/browser/#list/Prod/gts/75X_dataRun1_HLT_frozen_v10) as [75X_dataRun1_HLT_frozen_v9](https://cms-conddb.cern.ch/browser/#list/Prod/gts/75X_dataRun1_HLT_frozen_v9) with the following [changes](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/75X_dataRun1_HLT_frozen_v9/75X_dataRun1_HLT_frozen_v10): 
  - adding negative energy filter payload
- **RunII HI HLT processing** : [76X_dataRun2_HLTHI_v1](https://cms-conddb.cern.ch/browser/#list/Prod/gts/75X_dataRun2_HIHLT_v1) as [76X_dataRun2_HLT_frozen_v10](https://cms-conddb.cern.ch/browser/#list/Prod/gts/76X_dataRun2_HLT_frozen_v10) with the following [changes](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/76X_dataRun2_HLTHI_v1/76X_dataRun2_HLT_frozen_v10): 
  - adding Tracking MVA selection for HI
  - changing the AK4CaloHLT Jet Energy corrections to pick tag for Heavy Ions
  - using full Strip pedestals for Tracker Zero Suppression at HLT
- **RunII Offline processing** : [76X_dataRun2_v13](https://cms-conddb.cern.ch/browser/#list/Prod/gts/76X_dataRun2_v13) as [76X_dataRun2_v11](https://cms-conddb.cern.ch/browser/#list/Prod/gts/76X_dataRun2_v11) with the following [changes](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/76X_dataRun2_v11/76X_dataRun2_v13): 
  - **with updates for 2015 data Run2 EOY re-reco (tags contain run history)**
  - updated lumi based beamspot 
  - updated Tracker alignment (including APE and surface deformations) 
  - updated DT,CSC and muon GPR alignment - updated DT vdrif an ttrig 
  - updated CSC electronics caibrations 
  - updated SiStrip bad channel and particle gain 
  - updated Hcal gains and response corrections 
  - updated Castor local reco calibration for 0T re-reco 
  - updated Ecal IC, AdcToGeV, time calibrations, alignment and preshower intercalibrations 
  - updated centrality table with HFtowers label
## Upgrade
- **PhaseI design scenario** : [76X_upgrade2017_design_v8](https://cms-conddb.cern.ch/browser/#list/Prod/gts/76X_upgrade2017_design_v8) as [76X_upgrade2017_design_v7](https://cms-conddb.cern.ch/browser/#list/Prod/gts/76X_upgrade2017_design_v7) with the following [changes](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/76X_upgrade2017_design_v8/76X_upgrade2017_design_v7): 
  - New Pixel SIM LA for Phase-I
  - New Pixel LA for Phase-I 
  - New Pixel templates for Phase-I 
  - New Pixel SIM gains for Phase-I
  - New Pixel GenErrors for Phase-I
  - New Pixel gains for Phase-I
  - New Pixel quality for Phase-I

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
@cmsbuild please acknowledge changes

**Comment by diguida** [comment]
@mmusich @Martin-Grunewald the issue with HI appears here in the add-ons, as the short matrix does not perform the HI MC tests, as in https://github.com/cms-sw/cmssw/pull/12637#issuecomment-161293883.
At this point, I propose the following:
- keep the data GT as they are
- roll-back the HI MC GT, as there are things to check in 75X that will be likely forward ported here.

Any objections?

**Comment by mmusich** [comment]
@diguida already rolled back the HI MC GT. Let's have 75X  working first then we can forward port here and 8.0.X.

**Comment by mmusich** [comment]
please test

**Comment by Martin-Grunewald** [comment]
HIon HLT menu: https://github.com/cms-sw/cmssw/pull/12644

**Comment by mmusich** [comment]
doesnt' seem related to conditions changes...

**Comment by mmusich** [comment]
@Martin-Grunewald I reverted the change in the HI MC global tag. We'll wait when the menu is available here (if ever).

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
+1

**Comment by mmusich** [comment]
@mulhearn trying to port in the MC HIon Global Tag the same L1 changes as for 7.5.X (https://github.com/cms-sw/cmssw/pull/12644) namely [GT diff](https://cms-conddb.cern.ch/browser/#diff/Prod/gts/76X_mcRun2_HeavyIon_v12/76X_mcRun2_HeavyIon_v13), the addOn tests segfaults. Has this anything to do with the fact that [Stage1Layer2EtSumAlgorithmImpHI.cc](https://github.com/cms-sw/cmssw/tree/CMSSW_7_6_X/L1Trigger/L1TCalorimeter/src/firmware/Stage1Layer2EtSumAlgorithmImpHI.cc) doesn't exist in 76X?

**Comment by diguida** [comment]
@mmusich from a quick look to `L1Trigger/L1TCalorimeter` it looks like 76X lags behind:
https://github.com/cms-sw/cmssw/commits/CMSSW_7_5_X/L1Trigger/L1TCalorimeter/src/firmware
https://github.com/cms-sw/cmssw/commits/CMSSW_7_6_X/L1Trigger/L1TCalorimeter/src/firmware

**Comment by diguida** [comment]
ahhh my fault: it lagged behind because I forgot to sign #12176 and #12180 back-port to 76X.

**Comment by davidlange6** [comment]
@mmusich - I'm a bit surprised to see major changes in run 1 (ok, major but for castor..) - is there a presentation about this someplace (and if there is some dependency that would need changing due to these changes?)

**Comment by hengne** [comment]
@diguida Hi Salvatore, I tried after you talked with me yesterday, I see the same crash in the mixing module as you experienced.

**Comment by mmusich** [comment]
@hengne which workflow?

**Comment by mmusich** [comment]
@davidlange6 https://indico.cern.ch/event/368364/contribution/1/2/attachments/1180173/1708191/alcadbmeeting_021115_v3.pdf.
From CASTOR we got this message:

Upon inspecting 76X_dataRun2_v11 I noticed that actually none of our existing Castor*_v3.00_offline tags are included yet.
These were made to include all Run1 data conditions, and already exist since end 2013.
Thus for consistency I would like to request all of them to be put in the 76X offline GT, so that all conditions are at the v3.00 level.

**Comment by hengne** [comment]
@mmusich sorry, i mean the crash Salvatore mentioned in the HI PR at 75x. I wrote the message into the wrong PR...

**Comment by diguida** [comment]
@mmusich @hengne the crash happens in 75X, not here. Replying on the correct PR :-)

**Comment by mmusich** [comment]
@davidlange6 indeed it is a bit suspicious to see changes also in ES, let me dig further

**Comment by mmusich** [comment]
Indeed it seems that the ES intercalibration have not preserved the Run1 history:
```
$ conddb diff ESIntercalibConstants_V02_offline ESIntercalibConstants_V04_offline
[2015-12-03 11:54:09,339] INFO: Connecting to pro [frontier://PromptProd/cms_conditions]
Range               pro::ESIntercalibConstants_V02_offline Payload  pro::ESIntercalibConstants_V04_offline Payload  
------------------  ----------------------------------------------  ----------------------------------------------  
[1, 144115)         f18f20e5caabec0408a628d4661ff4ee6e695b56        6ca699f6b1514207520fd41b058adb7d8d6c381f        
[144115, 162561)    7c6ec80e6accb5d868ff4dc28d28cdc150a7427e        6ca699f6b1514207520fd41b058adb7d8d6c381f        
[162561, 162853)    da12218291d506b005cefc4ce738e6214bb1cc4a        6ca699f6b1514207520fd41b058adb7d8d6c381f        
[162853, 190178)    5b0c942539ab50f429f95f25a7443a987fab8b13        6ca699f6b1514207520fd41b058adb7d8d6c381f        
[190178, 190617)    47d2c1dd70b6701867dafbc53cbe7e816327237a        6ca699f6b1514207520fd41b058adb7d8d6c381f        
[190617, 201394)    bb56ed4de7cba5ae38517c949b31ed100eca986e        6ca699f6b1514207520fd41b058adb7d8d6c381f        
[201394, 201502)    47d2c1dd70b6701867dafbc53cbe7e816327237a        6ca699f6b1514207520fd41b058adb7d8d6c381f        
[201502, 203268)    bb56ed4de7cba5ae38517c949b31ed100eca986e        6ca699f6b1514207520fd41b058adb7d8d6c381f        
[203268, 203859)    47d2c1dd70b6701867dafbc53cbe7e816327237a        6ca699f6b1514207520fd41b058adb7d8d6c381f        
[203859, 203860)    bb56ed4de7cba5ae38517c949b31ed100eca986e        6ca699f6b1514207520fd41b058adb7d8d6c381f        
[203860, 237410)    9b6a412e8fa9beb1f10646fe91f10435ad30c3b6        6ca699f6b1514207520fd41b058adb7d8d6c381f        
[237410, 246908)    47d2c1dd70b6701867dafbc53cbe7e816327237a        6ca699f6b1514207520fd41b058adb7d8d6c381f        
[246908, 251577)    47d2c1dd70b6701867dafbc53cbe7e816327237a        647b67cfdb6e98aa580777bd9f6493297589d2f4        
[251577, 251604)    6ca699f6b1514207520fd41b058adb7d8d6c381f        647b67cfdb6e98aa580777bd9f6493297589d2f4        
[251604, Infinity)  6ca699f6b1514207520fd41b058adb7d8d6c381f        a3bb97a3837d26b2ac12f6e78a9ffc78d56fd2bd
```

**Comment by emanueledimarco** [comment]
strange. Jean and Pierre prepared the tag as follow, with 3 IOVs:

1      same as Run 1 (extracted from ESIntercalibConstants_V03_offline IOV 1)
246908 new HG payload
251604 new LG payload

while from the dump it seems that for Run1 there is a single IOV, which is wrong, it seems the last one of Run2 in the ESIntercalibConstants_V02_offline. Was this in the GT making or in what we provided?
Including also @amartelli @cmkuo

**Comment by mmusich** [comment]
@emanueledimarco that's what was provided. I asked direct confirmation to Jean and Pierre about the tag names before submitting it here, but didn't check the payload IOVs (too bad)

**Comment by diguida** [comment]
https://cms-conddb-int.cern.ch/cmsDbBrowser/diff/Prod/tags/ESIntercalibConstants_V02_offline/ESIntercalibConstants_V04_offline is clear: the IOV [1,246908[ in ESIntercalibConstants_V04_offline is pointing to the payload referenced by IOV [251577, INF[ in ESIntercalibConstants_V02_offline

**Comment by amartelli** [comment]
As additional comment: both the tags ESIntercalibConstants_V03_offline and ESIntercalibConstants_V04_offline are needed, ESIntercalibConstants_V03_offline to be used for next CMSSW8X and ESIntercalibConstants_V04_offline for the coming reco in 7X. Both tags are indeed missing the exact IOVs for Run1, which should be copied. The 2 IOVs corresponding to Run2 are ok.

**Comment by mmusich** [comment]
@amartelli fix for both is underway

**Comment by mmusich** [comment]
fixed tags are available:
https://cms-conddb.cern.ch/browser/#list/Prod/tags/ESIntercalibConstants_V03a_offline
https://cms-conddb.cern.ch/browser/#list/Prod/tags/ESIntercalibConstants_V04a_offline

**Comment by mmusich** [comment]
please acknowledge changes

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
@emanueledimarco @aramartelli should be fixed now, thanks for fast feedback

**Comment by diguida** [comment]
ahh we made a mistake... we kept the snapshot time of the previous GT, but the fixed tag arrived after.
Building a new GT...

**Comment by diguida** [comment]
-1
superseded by #12664

**Pull request closed without merging**
