### PR TITLE
fix CaloTowerTopology for HGCal/BH

### PR DESCRIPTION
**Pull request by kpedro88**
Testing #14713 revealed an issue with `CaloTowerHardcodeGeometryLoader`. This was fixed by modifying the definition of `CaloTowerTopology::lastHERing_` for correct handling of the case where HE is skipped (currently, no CaloTowers are desired for the Phase2 endcap with HGCal). I also switched to using `std::vector::at()` in `CaloTowerHardcodeGeometryLoader` to make the proximate cause of the issue more visible in case something similar pops up in the future, and added a bunch of debug statements behind a preprocessor flag.

I noticed that some of the changes in #14713 messed up the dense indexing for CaloTowers, because the CaloTower ieta was not continuous. This is fixed now, even though it leads to the somewhat strange convention of Phase2 HF CaloTowers starting at ieta=17.

NB: To test Phase2 workflows (I used 11000.0) in the latest IB, #14755 is also needed.

attn: @bsunanda

### CODE REVIEW

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by kpedro88** [comment]
@ianna the comparison looks good to me. This shouldn't have any effect on Run2 or historical workflows, it's just a fix for the BH stuff.

**Comment by kpedro88** [comment]
@ianna reminder...

**Comment by ianna** [comment]
+1

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by kpedro88** [comment]
@ebrondol noticed another issue, which is fixed in the new commit.

**Comment by kpedro88** [comment]
@slava77 Something seems to be wrong with the IB... for many of the comparisons, there is just a log file with this:
```
Traceback (most recent call last):
  File "/cvmfs/cms-ib.cern.ch/2016-24/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_X_2016-06-05-0000/bin/slc6_amd64_gcc530/compare_using_files.py", line 263, in <module>
    set(black_listed)
  File "/cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc530/cms/cmssw-patch/CMSSW_8_1_X_2016-06-06-2300/python/Utilities/RelMon/dqm_interfaces.py", line 546, in __init__
    self.stat_test=Statistical_Tests[stat_test](test_threshold)
  File "/cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc530/cms/cmssw-patch/CMSSW_8_1_X_2016-06-06-2300/python/Utilities/RelMon/utils.py", line 304, in __init__
    StatisticalTest.__init__(self, threshold)
  File "/cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc530/cms/cmssw-patch/CMSSW_8_1_X_2016-06-06-2300/python/Utilities/RelMon/utils.py", line 104, in __init__
    self.threshold=float(threshold)
ValueError: could not convert string to float: --standalone
Exception AttributeError: "'DirWalkerFile' object has no attribute 'workdir'" in <bound method DirWalkerFile.__del__ of <Utilities.RelMon.dqm_interfaces.DirWalkerFile object at 0x7f78fb363e50>> ignored
```

**Comment by slava77** [comment]
@cmsbuild please test
in case comparisons come back
(sometimes copy/rsync from the node with results to the node that does comparisons fails)

**Comment by kpedro88** [comment]
@slava77, @ianna - the comparison worked this time and I observe no changes. Can you sign again? Hopefully the Phase 2 workflows will work again with this...

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/14786	656037d
- reco code change is minimal: commented out lines were removed in RecoJets/Configuration/python/CaloTowersES_cfi.py 
- jenkins tests pass and comparisons with baseline show no differences
- in CMSSW_8_1_X_2016-06-07-1100 10600.0 (2023 GReco wflow) now runs

**Comment by kpedro88** [comment]
@ianna please sign again so we can merge ASAP

**Comment by ianna** [comment]
+1

**Comment by kpedro88** [comment]
@davidlange6 please merge ASAP (needed to fix Phase2 workflows)

**Comment by davidlange6** [comment]
+1

**Pull request merged**
