### PR TITLE
Updated pixel track efficiency codes for phase 1 detector

### PR DESCRIPTION
**Pull request by chenxvan**
Added offline cuts for all the pixel detector. Added fiducial cuts and backpropagation for Layer 1 detector.

### CODE REVIEW

**Comment by chenxvan** [comment]
Submitted a PR for the category:
https://github.com/cms-sw/cms-bot/pull/982

**Comment by smuzaffar** [comment]
assign dqm

**Comment by boudoul** [comment]
Hi @chenxvan , please edit your title : "Updated code for phase 1 detector" could mean that you updated the local reco (for example, since I don't know which code you updated) for hcal (which is also a phase1 detector ...) , and for which purpose ? please be more explicit in the title , thank you.

**Comment by chenxvan** [comment]
Hi @boudoul, I update the title. Please let me know if you need more info. Thanks

**Comment by boudoul** [comment]
dear @jfernan2, @vazzolini, @vanbesien, @kmaeshima, @dmitrijus   , could you please consider this PR for review ?

**Comment by fabiocos** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by fabiocos** [comment]
@chenxvan are the changes as expected? I see that also 2011 HI plots are modified

**Comment by chenxvan** [comment]
Hi @fabiocos , we ran the changes and value of the efficiency changed as we expected. May I ask what are the 2011 HI plots?

**Comment by fioriNTU** [comment]
@fabiocos  if the era mechanism works as expected the 2011 data should be processed using the Phase 0 code, which, of course, is not touched by this PR. Maybe something else in the same IB is changing those plots

**Comment by chenxvan** [comment]
@boudoul I removed the PXBDetid

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
@chenxvan @fioriNTU please check in the link provided above the differences for 140.53, i.e.

https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_10_2_X_2018-05-16-2300+23160/26539/140.53_RunHI2011+RunHI2011+RECOHID11+HARVESTDHI/

one should at least ensure that just adding this PR only there is no change there

**Comment by davidlange6** [comment]
@makortel pointed me to #23105 ....

**Comment by makortel** [comment]
On the other hand the changes shown in @fabiocos's link do not seem to be among the "usual suspects" of #23105.

**Comment by fioriNTU** [comment]
@fabiocos checking the diff link you sent it looks like the PV plots perfectly match on top of each other, but they are flagged as "failing comparison" please check here:

https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_10_2_X_2018-05-16-2300+23160/26539/140.53_RunHI2011+RunHI2011+RECOHID11+HARVESTDHI/OfflinePV_Alignment.html

For what concern this PR, it doesn't touch any reconstruction module, it only change the way the Layer 1 efficiency for Pixels is computed in DQM, it neither changes the total number of bins in DQM histograms. I would expect only a slight increase in processing time, but nothing can happen outside the Phase1 DQM.

**Comment by makortel** [comment]
The differences indeed look numerical-only. If they are produced by fits, then the underlying cause may be the same as discussed in #23105.

**Comment by fabiocos** [comment]
@davidlange6 @makortel yes, this is why I was suspicious, normally the problem of non reproducibility is seen in the Tracking and HLT folders, in this case the pattern of discrepancies is different. I have checked on the same machine rerunning manually the wf 140.53 with and without only this PR merged. Indeed the observed difference looks an artefact of the comparison done by the bot as far as I can see, as I manage to get agreement for 140.53 with the bot compare_using_files.py sequence 

 - summary of 59557 tests:
 o Failiures: 0.00% (0/59557)
 o Nulls: 0.00% (0/59557) 
 o Successes: 100.00% (59557/59557) 
 o Skipped: 0.00% (0/59557) 
 o Missing objects: 0

so provided there is no further comment and DQM signs I would say this PR could move forward

**Comment by fabiocos** [comment]
@dmitrijus @jfernan2 this PR was already signed by Dmitrijus and the change since then looks trivial, I merge it

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Comment by boudoul** [comment]
Hi @chenxvan ( the question is also for @fioriNTU and @arossi83 ) Maybe I missed it but I didn't see any backport of this PR in 10_1_X, should be not also considering backporting this ? Thanks.

**Comment by fioriNTU** [comment]
@boudoul thanks for pointing this out, @chenxvan a backport to 10_1_X is needed, please provide it as soon as possible

**Comment by boudoul** [comment]
Hi @chenxvan , could you please backport asap ?

**Comment by chenxvan** [comment]
@boudoul @fioriNTU sorry I missed the message. I just backport to 10_1_X. Here is the PR: https://github.com/cms-sw/cmssw/pull/23378

**Pull request merged**
