### PR TITLE
Fixes for low-level alpaka based utilities

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Fix various low-level alpaka based utilities that were inadvertently mixing host and device code.

Required to build with alpaka in GPU-only mode.

#### PR validation:

Unit tests pass.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

These changes should improve the correctness of the alpaka-based algorithms, and it would be a good idea to backport them to CMSSW 14.0.x for data taking.

### CODE REVIEW

**Comment by fwyzard** [comment]
type vugfix

**Comment by fwyzard** [comment]
enable gpu

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
+heterogeneous

**Comment by antoniovilela** [comment]
+1

**Comment by fwyzard** [comment]
@jsamudio FYI

**Pull request merged**
