### PR TITLE
Update the HLT alpaka customisation [14.0.x]

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Customise the GPU checks to use the `AlpakaBackendFilter`:
  - customise the `Status_On{CPU|GPU}` HLT paths and the `DQM_{Ecal|Hcal|Pixel}Reconstruction_v*` HLT paths to use the `AlpakaBackendProducer` and `AlpakaBackendFilter` modules.

Delete legacy modules and tasks after defining the alpaka ones.
Clean up white space and indentation.

#### PR validation:

The online HLT menu 2024 v1 was run with and without these changes.

#### Backport status

Backport of #44439 for data taking.

### CODE REVIEW

**Comment by fwyzard** [comment]
Note: this PR includes some of the changes from #44416, and may need to be rebased once that one is merged.

**Comment by fwyzard** [comment]
backport #44439

**Comment by fwyzard** [comment]
enable gpu

**Comment by fwyzard** [comment]
please test

**Comment by mmusich** [comment]
hold
   * waiting for https://github.com/cms-sw/cmssw/pull/44416 to be merged.

**Comment by mmusich** [comment]
unhold
   * this needs to be rebased now

**Comment by fwyzard** [comment]
Rebased on top of the current HEAD of CMSSW_14_0_X.

**Comment by fwyzard** [comment]
please test

**Comment by fwyzard** [comment]
please test with #44388

**Comment by Martin-Grunewald** [comment]
+1

**Comment by antoniovilela** [comment]
type hlt-int

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
