### PR TITLE
Btag DQM: move from binomial error to ClopperPearson error for Efficiency

### PR DESCRIPTION
**Pull request by acaudron**
- Change the way to assign error on Efficiency: binomial -> ClopperPearson as should give better error estimation for low efficiency cases.
- Take the opportunity to add missing Efficiency Flag for efficiency plots.

### CODE REVIEW

**Comment by acaudron** [comment]
please test

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
