### PR TITLE
Added CMS stepping verbose for SIM 

### PR DESCRIPTION
**Pull request by civanch**
Added CMS custom stepping verbose class allowing debug problematic events. Should not affect production but will allow to speed-up CMS production if Geant4 native verbosity will be disabled.  

Removed obsolete class; fixed typo in the new PhysicsList name.

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by davidlange6** [comment]
@civanch - you have introduced a strange mix of pointers and smart pointers. Is there a logic behind the inconsistency?

**Comment by civanch** [comment]
@davidlange6 , pointers come from G4 interfaces, one extra unique_pointer - object from CMSSW.

**Comment by civanch** [comment]
@davidlange6 , may be you mean to  use unique_ptr<CMSSteppingVerbose> in all downstream classes?

**Comment by davidlange6** [comment]
+1
thanks @civanch - I remember the issue now

**Pull request merged**
