### PR TITLE
[backport] MTD geometry and reconstruction: synchronise with master up to PR 33762

### PR DESCRIPTION
**Pull request by fabiocos**
#### PR description:

This PR backports to branch 11_3_X the following recent MTD updates added to 12_0_X:

- revert https://github.com/cms-sw/cmssw/pull/33657
- cherry-pick https://github.com/cms-sw/cmssw/pull/33453
- cherry-pick https://github.com/cms-sw/cmssw/pull/33647
- cherry-pick https://github.com/cms-sw/cmssw/pull/33598
- cherry-pick https://github.com/cms-sw/cmssw/pull/33649
- cherry-pick https://github.com/cms-sw/cmssw/pull/33762

The technical code cleaning of #33680 is not relevant for physics performances, and is left out from this backport. 
It requires https://github.com/cms-data/Geometry-TestReference/pull/9 (a cmsdist backport is provided in parallel).

This reverts  https://github.com/cms-sw/cmssw/pull/33793 , restoring PR #33779

#### PR validation:

Code tested in master, and in #33779

### CODE REVIEW

**Comment by jfernan2** [comment]
+1

**Comment by cvuosalo** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by srimanob** [comment]
backport

**Comment by jpata** [comment]
+reconstruction
- no issues from the reco side with the backport (contains only the needed changes)
- no modifier protections are applied for a backport of MTD/Phase2 (none are needed)

**Comment by srimanob** [comment]
+Upgrade

This backport needs https://github.com/cms-sw/cmsdist/pull/6928

**Comment by qliphy** [comment]
+1

**Pull request merged**
