### PR TITLE
Step 2 amendment: Simulation Clang tidy code-checks-all and Clang Warnings Removed

### PR DESCRIPTION
**Pull request by ianna**
* Unused variables removed
* This PR is based on https://github.com/cms-sw/cmssw/pull/20525

@civanch - FYI, just to make sure that modifications by hand do not introduce any changes. When #20525 is merged, I'll rebase this one if needed.

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by civanch** [comment]
@ianna , the difference with #20525  is in one line only with the fix, which is obvious, so I would keep #20525 only for memory and try to merge only this one.

**Comment by ianna** [comment]
hold

**Comment by davidlange6** [comment]
hi @civanch - this is ready to go, no?

**Comment by civanch** [comment]
@davidlange6 , the PR is OK but just recently you merge exotica fix PR. There is , at least, one common file in which  modifications are orthogonal, but I am not sure if re-base of this PR on top of the new IB is needed or not.

**Comment by ianna** [comment]
unhold

**Comment by ianna** [comment]
@civanch - there are no conflicts, so it should be ready to go IMHO

**Comment by davidlange6** [comment]
merge

**Comment by civanch** [comment]
+1

**Pull request merged**
