### PR TITLE
Miscellaneous updates to CaloLayer1 DQM services

### PR DESCRIPTION
**Pull request by nsmith-**
This is a 94x 'backport' of #20465 as it has diverged from master
Both #20464 and #20465 have been fully signed and in DQM tag collector for 2 months!

### CODE REVIEW

**Comment by nsmith-** [comment]
@thomreis @rekovic here it is

**Comment by rekovic** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by thomreis** [comment]
backport of #20465

**Comment by nsmith-** [comment]
Online DQM now in 10_0_X, no reason to need this

**Pull request closed without merging**
