### PR TITLE
Fix jet ordering in MvaMEtUtilities class

### PR DESCRIPTION
**Pull request by mmarionncern**
Fix the jet ordering in the mva met utility class, improves slightly the MVA MET performances and makes results consistents

This PR does not impact the standard sequences, no changes expected at all in the tests.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
@cmsbuild please test
Comparisons are still queued, so try again.

**Comment by slava77** [comment]
@cmsbuild please test
hopefully DAS has more like finding files

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by cvuosalo** [comment]
+1

For #9961 ae02dcd301e4b212c99143690d92e2b8e8d374d5

Small change to improve sorting of jets for MET MVA. It should not have an effect on standard sequences.

The code change is satisfactory, and Jenkins [tests](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-9961/4413/summary.html) against baseline CMSSW_7_4_X_2015-07-01-2300 show no significant differences, as expected.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
