### PR TITLE
Deep csv template

### PR DESCRIPTION
**Pull request by tiwariPC**
This PR contains changes made in following PR( for 92X):
https://github.com/cms-sw/cmssw/pull/18515

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
backport of #18515

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/18643	a6efa25
- trivial backport of 92X PR #18515: the same topic branch is used.  This is a technical change for the deep NN tagger to allow use in HLT
- jenkins tests pass and comparisons with baseline show no differences (deep NN running in reco is not modified)

**Comment by tiwariPC** [comment]
May I know when this PR can be merged?

**Comment by tiwariPC** [comment]
Will this PR be merged?

**Comment by JyothsnaKomaragiri** [comment]
> https://github.com/cms-sw/cmssw/pull/18643#issuecomment-300526832


What else needs to be done from our side to merge this pull request?

**Comment by slava77** [comment]
assign hlt

@Martin-Grunewald 
given that 920 is available, is HLT going to move to it or do you keep developments still in 91X?
Since this feature is needed only for HLT at this point, I added a signature so that HLT sw managers can keep track of it more easily.

**Comment by Martin-Grunewald** [comment]
@slava77 
We'll move to 92X asap (pending a GT).

**Comment by Martin-Grunewald** [comment]
I assume we can close this PR?

**Comment by JyothsnaKomaragiri** [comment]
Yes Martin.

@tiwariPC can you close this PR?

**Pull request closed without merging**
