### PR TITLE
DAQ limited output module (10_5_X)

### PR DESCRIPTION
**Pull request by smorovic**
This is DAQ (HLT/Filter Farm) output module implementation based on limited::OutputModule. This implementation removes limitation of handling only one LS at the time present in current one DAQ module.

- New module also rely on changes introduced here: https://github.com/cms-sw/cmssw/pull/21830

- StreamerOutputModuleBase (inheriting one::OutputModule) base is restructured and serializer code (shared with the new, limited implementation) extracted to a common class which can be used by both one and limited module. Currently, "base" is used by: DQM test module, Streamer writer module and previous DAQ output module which we'll still keep.

- new module is called EvFOutputModule while previous DAQ module remains as ShmStreamConsumer (this name is currently still used in production configurations).

- Limited OutputModule transitions used to write event and end global lumisection are const functions. There are a few problems associated with this, for which a workaround is to apply const_cast:

1. This is too strict for streamer serializer, which is therefore included in a helper class stored in RunCache. Serializer keeps internally a buffer which is reallocated only if too small to accommodate serialized event. To allow access, const_cast is applied in event write callback.

2. File writer in LuminosityBlockCache object also needs const_cast in event write and global EoL ( where file is written to / closed). Also it needs to update the object to do per-LS event count bookkeeping.

3. JSON writer, which is initialized once with JSON definitions, is also stored in RunCache, and needs to be allowed modification at the time of global EoL.

- Those const_casts should be thread-safe since this limited output module strictly requires concurrencyLimit = 1 at runtime, and will throw exception if another configuration value is set.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
@dan131riley could you help review this?

**Comment by Dr15Jones** [comment]
hold

**Comment by Dr15Jones** [comment]
@smorovic 
> * Those const_casts should be thread-safe since this limited output module strictly requires concurrencyLimit = 1 at runtime, and will throw exception if another configuration value is set.

Making such a restriction is highly not recommended by the framework group. We had recently introduced the ability to use Run and LuminosityBlock caches with all the other edm::one type modules except the OutputModule. We could do the same for edm::one::OutputModule which would allow inheriting modules to process LuminosityBlocks out of order.

**Comment by smorovic** [comment]
@Dr15Jones 
That would also be suitable because out of order LuminosityBlocks were the only reason to switch to the limited type. It would also pull less changes (if any) to the StreamerOutputModuleBase.

**Comment by dan131riley** [comment]
Updating the `edm::one::OutputModule` looks much better to me, using a limited restricted to concurrency one seemed squirrelly.  I had some minor comments but I guess I'll save them for the next iteration.

**Comment by slava77** [comment]
@smorovic 
please clarify on the status of updates expected in this PR, based on comments from @dan131riley 
Thank you.

**Comment by smorovic** [comment]
Hi,
I agree with comments from @dan131riley and @Dr15Jones. If necessary features will be provided in edm::one::OutputModule, we should then not merge this PR and will instead follow up to use one::OutputModule as base class for the module.

**Comment by slava77** [comment]
> we should then not merge this PR and will instead follow up to use one::OutputModule as base class for the module.

Should this PR be closed then?
@smorovic if you agree, please close.
Thank you.

**Comment by smorovic** [comment]
I agree - closed it.

**Comment by Dr15Jones** [comment]
The feature for `edm::one::OutputModule` is available in  #26196

**Comment by smorovic** [comment]
Thanks, I will proceed basedon #26196.

**Pull request closed without merging**
