### PR TITLE
Switch AddOn tests to use Run 2 eras

### PR DESCRIPTION
**Pull request by mark-grimes**
This changes the AddOn tests to use the Run 2 eras instead of the postLS1 customisations.  Basically all that's changed is `--customise SLHCUpgradeSimulations/Configuration/postLS1Customs.customisePostLS1` goes to `--era Run2_25ns`; `...customisePostLS1_50ns` to `--era Run2_50ns`; and `...customisePostLS1_HI` to `--era Run2_HI`.
#11466 is a PR to change over the standard runTheMatrix workflows.  The latest diff of the configs produced by the two different methods is at http://grimes.web.cern.ch/grimes/eraProcessDiffs/processDiffs-7_6_X_2015-10-07-1710-PR11466.html

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
I suggest to look at the std GEN-SIM-DIGI-L1 job "hlt_mc_GRun"
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-11690/8694/addOnTests/hlt_mc_GRun/

which has as error:
```

# Conditions read from  CMS_CONDITIONS  via FrontierProd 
disableME1a = 0
----- Begin Fatal Exception 08-Oct-2015 16:51:19 CEST-----------------------
An exception of category 'NoRecord' occurred while
   [0] Processing run: 1
   [1] Calling global beginRun for module L1TStage1Layer2Producer/'simCaloStage1Digis'
Exception Message:
No "L1TCaloConfigRcd" record found in the EventSetup for synchronization value
Run: 1 LuminosityBlock: 0 Event: 0 Time: 1
 Please add an ESSource or ESProducer that delivers such a record.
----- End Fatal Exception -------------------------------------------------
terminate called after throwing an instance of 'cms::Exception'
  what():  An exception of category 'Assert' occurred.
Exception Message:
Geant4 is still alive, master thread state must be set to EndRun before Destruct

```

**Comment by mark-grimes** [comment]
I've submitted #11707 to fix this.  Closing until that is merged, then I'll reopen.  This wasn't noticed before because the L1 step was always run with L1Reco.

**Comment by mark-grimes** [comment]
Now that #11817 has been merged, this should be fine.

**Comment by mark-grimes** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by mark-grimes** [comment]
Doh! Should have waited for an IB with #11817.  I'll leave it open then rerun tests when the next IB is out.

**Comment by mark-grimes** [comment]
please test

CMSSW_7_6_X_2015-10-16-1100 has #11817 in now, so tests should pass.

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
Can you add a dummy era which does nothing? Called Null or None?
This way I can use in my script --era=$Era also for Run1 workflows

Thanks!

**Comment by mark-grimes** [comment]
Technically it's trivial, unless you want something to guarantee that no one later adds any commands to it.  There was an agreement to discuss new eras in the release planning meeting, I'll raise it this afternoon.

**Comment by Martin-Grunewald** [comment]
OK, maybe then we should have an era called "Run1" which is (currently) empty and presumably nobody will touch it...

**Comment by mark-grimes** [comment]
Another option is that I fix the parsing scripts so that `--era=""` is the same as not specifying an era at all.  It currently doesn't work but I should be able to fix that fairly easily, and doesn't risk people adding commands to it.

**Comment by Martin-Grunewald** [comment]
ah yes!

**Comment by davidlange6** [comment]
I’m in favor of an era=“Run1” so that we can later change the default

**Comment by mark-grimes** [comment]
@Martin-Grunewald - Run1 era added with #12023 for 8_0_X.  Let me know if you need it in other releases.

**Comment by Martin-Grunewald** [comment]
76X also , would be great!
Thanks!

**Comment by davidlange6** [comment]
@cmsbuild, please test

**Comment by davidlange6** [comment]
+1

**Pull request merged**
