### PR TITLE
Update customisePixelL1ClusterThresholdForRun2Input to adjust also the GPU producer

### PR DESCRIPTION
**Pull request by fwyzard**
#### PR description:

Update `customisePixelL1ClusterThresholdForRun2Input()` to adjust also the GPU producer with the Run 2 settings.

#### PR validation:

None.

### CODE REVIEW

**Comment by missirol** [comment]
please abort

**Comment by missirol** [comment]
test parameters:
  - pull_request = #35890

**Comment by missirol** [comment]
please test

**Comment by missirol** [comment]
+hlt

 * despite the label, this PR did not require any externals (and the other PR, which fixed one of the tests, is already merged)

**Comment by qliphy** [comment]
+1

**Pull request merged**
