### PR TITLE
Added esConsumes to ConversionSeedFinder

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

This is part of the esConsumes migration.

#### PR validation:

The code compiles.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
FYI @makortel 

This is needed for ConversionTrackCandidateProducer.

**Comment by Dr15Jones** [comment]
please test

**Comment by slava77** [comment]
+reconstruction

for https://github.com/cms-sw/cmssw/pull/35475	526fd42 
- code changes are technical, in line with the PR description/title
- jenkins tests pass and comparisons with the baseline show no (relevant) differences

**Comment by qliphy** [comment]
+1

**Pull request merged**
