### PR TITLE
fix in PixelTrackBuilder and MuonIdProducer to get debug build work for static ana

### PR DESCRIPTION
**Pull request by slava77**

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/32675	b1c94cb 
- static analysis does not show compilation errors anymore

**Comment by qliphy** [comment]
+1

**Pull request merged**
