### PR TITLE
Migrate calotower code to use HCAL thresholds from GT

### PR DESCRIPTION
**Pull request by swagata87**
#### PR description:

While our final aim is to fully deprecate calotowers, there is no clear ETA for that. Several POGs still use calotowers, specially at HLT. So, to ensure that correct HCAL thresholds are used in making calotowers,  the safest way is to use the thresholds from GT.
That is what is done in this PR. Related github issue: https://github.com/cms-sw/cmssw/issues/43312 

This is a technical PR. In principle there should not be any change in physics. But I expect there will be some changes. 

For Phase2 HLT, there might be some changes seen in PR tests, because the thresholds from DB and thresholds written here would not match:
https://github.com/cms-sw/cmssw/blob/40d9d46f15f482f8fa72892ffc76f5bce8d618ce/HLTrigger/Configuration/python/HLT_75e33/modules/caloTowerForTrk_cfi.py#L23-L25
https://github.com/cms-sw/cmssw/blob/40d9d46f15f482f8fa72892ffc76f5bce8d618ce/HLTrigger/Configuration/python/HLT_75e33/modules/towerMaker_cfi.py#L23-L25

In offline reco also, some changes can be seen in barrel for Run3, because the correct thresholds present in DB and thresholds written here does not seem to match:
https://github.com/cms-sw/cmssw/blob/e9b40ab5975f05832f3e6a9fcaffa1cbd3315fbb/RecoLocalCalo/CaloTowersCreator/python/calotowermaker_cfi.py#L173-L176

#### PR validation:

Checked with `12434.0_TTbar_14TeV+2023`

FYI @missirol  @cms-sw/hlt-l2  @cms-sw/alca-l2 @cms-sw/hcal-dpg-l2

### CODE REVIEW

**Comment by swagata87** [comment]
please test with https://github.com/cms-sw/cmssw/pull/43305

**Comment by mmusich** [comment]
> For Phase2 HLT, there might be some changes seen in PR tests, because the thresholds from DB and thresholds written here would not match

Is that out of sloppiness in updating the configurations or is there some deeper reason? 

@rovere @SohamBhattacharya FYI

**Comment by swagata87** [comment]
> Is that out of sloppiness in updating the configurations or is there some deeper reason?

This is not sloppiness. In those Phase2 HLT configs people have written the thresholds corresponding to 1000 fb-1 ageing, which is the most commonly used ageing scenario for studying physics in Phase2. But for some reasons, PR tests are done without any ageing; and in that special case one should fall back to Run3 thresholds, but that is not happening here for config-based approach, but happens for GT-based approach. It seem to be similar issue like the one discussed here: https://github.com/cms-sw/cmssw/pull/43025#issuecomment-1814745057 , so to fix it one should write Run3 thresholds in Phase HLT config, and if one uses proper ageing then those will be overwritten via https://github.com/cms-sw/cmssw/blob/d59e80b6862b73d0497919044d19841844f164b3/SLHCUpgradeSimulations/Configuration/python/aging.py#L88-L124

**Comment by mandrenguyen** [comment]
Looking at the comparisons, they seem in line with the PR description
I was a bit surprised to see that the changes in the barrel are this large, for example:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_14_0_X_2023-11-19-0000+2e268c/59842/validateJR/14034.0_TTbar_14TeV+2023FS/all_RECO_step2/c_CaloTowersSorted_towerMaker__RECO_obj_obj_eta.png

@swagata87 Is this in line with your expectation?

**Comment by swagata87** [comment]
> @swagata87 Is this in line with your expectation?

I think this is what has happened-->
Noise cuts before  and after this PR in HCAL depths (for 2023): 
HB: 0.1, 0.2, 0.3, 0.3 --> 0.4, 0.3, 0.3, 0.3 [Changes in depth 1 and 2]
HE: 0.1, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2 -> 0.1, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2 [No change]
That's why we see changes only in barrel. I'd say this is expected.

**Pull request merged**
