### PR TITLE
Remove a dead initialization, and a few other cleanings in EcalTPGParamBuilder

### PR DESCRIPTION
**Pull request by perrotta**
#### PR description:

Starting from a dead initialization (of the `base` local variable) reported by the static analyzer, a few additional rather trivial clean ups in the code that jumped to my eyes were also implemented.

#### PR validation:

It builds.
No changes expected.

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by yuanchao** [comment]
+1
* code cleaned up on initialization and branch logic as this PR described
* matrix tests and unit tests all passed
* CLang tidy and build warnings on esConsumes migration on EcalTPGParamBuilder.cc and EcalTPGDBCopy.cc though not the purpose of this PR (?).

**Comment by cecilecaillol** [comment]
+l1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
