### PR TITLE
Extended 2018 Scenario with Detailed Cavern and MB4 Shield

### PR DESCRIPTION
**Pull request by ianna**
* Add a new scenario based on extended 2018 to include detailed cavern and the MB4 shields as they are in 2018 (see the snapshot attached).
* No new overlaps introduced.

This is needed to study the neutron background. The MC production is planned for September/October. The scenario tag will be added to the 10.3.x, 10.2.x, and earlier GTs if needed with a label.

screen shot 2018-08-08 at 14 24 58

### CODE REVIEW

**Comment by ianna** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

@kpedro88 it is an addition of new configuration files, no change in existing workflows

**Pull request merged**
