### PR TITLE
Modification of cone based tau algorithm to furbish it as fallback solution for the HLT for upcoming data taking (91X)

### PR DESCRIPTION
**Pull request by mbluj**
Dear colleagues, 

this is a backport of #18429 which has just been merged to newly opened 92X (current master). For convenience I quote description of the original PR:

Dear colleagues,

this is a pull request by @mbluj that contains modifications of the cone based tau reconstruction algorithm as used for the HLT to make it fit for upcoming data taking periods, as fallback in case that the planned HPS-port to the HLT won't be ready in time. I'm citing Michal's comments (*) and refer to him for further questions.

Cheers,
Roger

(*)
This PR is to modify the Cone-based tau builder (used at HLT) to fill some additional data members of produced PFTau not filled so far:
* Size of signal cone (cone for PiZeros used);
* Pt carried by signal PiZeros outside of the signal cone; it is important shape variable supporting isolation in rejecting jet->tau fakes;
* Charge, pdgId, tau decay mode hypothesis.

The changes do not modify current HLT work-flow (the builder is used only at HLT), but provides new features (cf. 2) allowing better jet->tau fake rejection during 2017 data-taking.

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
+1
Identical to #18429, already approved (in origin for 91X)

**Comment by Martin-Grunewald** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
