### PR TITLE
Reorganize `Alignment/OfflineValidation` unit tests

### LINKED ISSUE #40566: Decrease number of event for GeneralTrackAnalyser unit test
Hello,

We have noticed in the IBs that test `GeneralTrackAnalyser` (`Alignment/OfflineValidation`) is taking more than 1h in running. In concrete, the first subtest https://github.com/cms-sw/cmssw/blob/master/Alignment/OfflineValidation/test/test_unitGeneralTrackAnalyser.sh#L6 is taking already around an hour, probably because it is analysing 2600 events (https://github.com/cms-sw/cmssw/blob/master/Alignment/OfflineValidation/test/test_all_cfg.py#L35).

Could it be possible to reduce the number of events to 200-500 events?
In this range, execution times on the same machine are from 10 to 25 min.

Thanks,
Andrea.

### PR DESCRIPTION
**Pull request by mmusich**
resolves https://github.com/cms-sw/cmssw/issues/40566

#### PR description:

  * de-clutter `Alignment/OfflineValidation/test` by moving the testing bash scripts into a dedicated sub-folder (4d3cda7294e95671237aa29a10c357e603df638e)
  * reduce the verbosity of the goemetry comparison plotter (6cfc315fcba2b3506251393caedf696e4fc24f93)
  * reduce the number of events in `GeneralTrackAnalyser` unit test (87d68c4564e4d8a712202cbb530da8a3b11e092c)

#### PR validation:

Run `scram b runtests use-ibeos`

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

N/A

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by tvami** [comment]
+alca
 * unit tests pass (from a new location, with new settings)

**Comment by rappoccio** [comment]
+1

Technical reorganization.

**Comment by aandvalenzuela** [comment]
Hello @mmusich,
Although this PR decreased the number of events, the test is still timing out for non-amd64 architectures. Do you suspect if it could be any reason why it takes longer to run in aarch64 or ppc64le? I am running the tests locally to identify where it could be hanging or taking longer in processing. Thank you!

**Comment by mmusich** [comment]
> Do you suspect if it could be any reason why it takes longer to run in aarch64 or ppc64le? I

no.

>  I am running the tests locally to identify where it could be hanging or taking longer in processing.

please go ahead and feel free to post in original issue https://github.com/cms-sw/cmssw/issues/40566

**Comment by mmusich** [comment]
@aandvalenzuela 

by the way how is one supposed to work with those archs? On `lxplus8:`
```
$ setenv SCRAM_ARCH el8_aarch64_gcc11
$ cmsrel CMSSW_13_0_X_2023-01-23-2300
$ cd CMSSW_13_0_X_2023-01-23-2300/src/
$ cmsenv
$ echo $CMSSW_RELEASE_BASE/
/cvmfs/cms-ib.cern.ch/sw/aarch64/week1/el8_aarch64_gcc11/cms/cmssw-patch/CMSSW_13_0_X_2023-01-23-2300/
$ git cms-addpkg Alignment/OfflineValidation
/cvmfs/cms-ib.cern.ch/sw/aarch64/week1/el8_aarch64_gcc11/cms/cmssw-patch/CMSSW_13_0_X_2023-01-23-2300/external/el8_aarch64_gcc11/bin/git: Exec format error. Binary file not executable.
```

...

**Comment by smuzaffar** [comment]
@mmusich , please use `lxplus8-arm` nodes for aarch64 arch

**Comment by mmusich** [comment]
> please use `lxplus8-arm` nodes for aarch64 arch.

thanks. For some reason `scram b runtests_GeneralTrackAnalyser` doesn't work in that release (`CMSSW_13_0_X_2023-01-23-2300`),  as it yields:

```bash
scram b runtests_GeneralTrackAnalyser
>> Local Products Rules ..... started
>> Local Products Rules ..... done
gmake: Nothing to be done for 'runtests_GeneralTrackAnalyser'.
```

despite the test being defined here:

https://github.com/cms-sw/cmssw/blob/907d99116df35884936b6f5eb76018d4352ad482/Alignment/OfflineValidation/test/BuildFile.xml#L30-L33

on the other hand I can execute the bash script locally to success.

https://github.com/cms-sw/cmssw/blob/907d99116df35884936b6f5eb76018d4352ad482/Alignment/OfflineValidation/test/testingScripts/test_unitGeneralTrackAnalyser.sh#L1-L9

I noticed some warnings (seemingly unrelated) in the execution of the second command:

```bash
25-Jan-2023 10:12:28 CET  Initiating request to open file root://eoscms.cern.ch//eos/cms/store/relval/CMSSW_12_5_3/RelValMinBias_14TeV/GEN-SIM-RECO/125X_mcRun4_realistic_v5_2026D88PU-v1/2590000/22e22ae6-a353-4f2e-815e-cc5efee37af9.root
In file included from DataFormatsL1TrackTrigger_xr dictionary payload:76:
In file included from /cvmfs/cms-ib.cern.ch/sw/aarch64/week1/el8_aarch64_gcc11/cms/cmssw-patch/CMSSW_13_0_X_2023-01-23-2300/src/DataFormats/L1TrackTrigger/interface/TTTypes.h:19:
In file included from /cvmfs/cms-ib.cern.ch/sw/aarch64/week1/el8_aarch64_gcc11/cms/cmssw-patch/CMSSW_13_0_X_2023-01-23-2300/src/DataFormats/L1TrackTrigger/interface/TTTrack.h:18:
In file included from /cvmfs/cms-ib.cern.ch/sw/aarch64/week1/el8_aarch64_gcc11/cms/cmssw-patch/CMSSW_13_0_X_2023-01-23-2300/src/DataFormats/L1TrackTrigger/interface/TTTrack_TrackWord.h:20:
In file included from /cvmfs/cms-ib.cern.ch/sw/aarch64/nweek-02769/el8_aarch64_gcc11/external/hls/2019.08-fd724004387c2a6770dc3517446d30d9/include/ap_int.h:20:
In file included from /cvmfs/cms-ib.cern.ch/sw/aarch64/nweek-02769/el8_aarch64_gcc11/external/hls/2019.08-fd724004387c2a6770dc3517446d30d9/include/ap_common.h:252:
/cvmfs/cms-ib.cern.ch/sw/aarch64/nweek-02769/el8_aarch64_gcc11/external/hls/2019.08-fd724004387c2a6770dc3517446d30d9/include/etc/ap_private.h:1535:34: warning: format specifies type 'unsigned long long *' but the argument has type 'uint64_t *' (aka 'unsigned long *') [-Wformat]
        sscanf(strStart, "%llo", &tmpVAL);
                          ~~~~   ^~~~~~~
                          %lo
/cvmfs/cms-ib.cern.ch/sw/aarch64/nweek-02769/el8_aarch64_gcc11/external/hls/2019.08-fd724004387c2a6770dc3517446d30d9/include/ap_int_base.h:354:13: note: in instantiation of member function 'ap_private<64, false, true>::fromString' requested here
    Base::V.fromString(s, length, rd);
            ^
/cvmfs/cms-ib.cern.ch/sw/aarch64/nweek-02769/el8_aarch64_gcc11/external/hls/2019.08-fd724004387c2a6770dc3517446d30d9/include/ap_int.h:275:51: note: in instantiation of member function 'ap_int_base<64, false>::ap_int_base' requested here
  INLINE ap_uint(const char* s, signed char rd) : Base(s, rd) {}
                                                  ^
/cvmfs/cms-ib.cern.ch/sw/aarch64/week1/el8_aarch64_gcc11/cms/cmssw-patch/CMSSW_13_0_X_2023-01-23-2300/src/DataFormats/L1Trigger/interface/VertexWord.h:143:43: note: in instantiation of member function 'ap_uint<64>::ap_uint' requested here
    vtxword_t vertexWord() const { return vtxword_t(vertexWord_.to_string().c_str(), 2); }
                                          ^
In file included from DataFormatsL1TrackTrigger_xr dictionary payload:76:
In file included from /cvmfs/cms-ib.cern.ch/sw/aarch64/week1/el8_aarch64_gcc11/cms/cmssw-patch/CMSSW_13_0_X_2023-01-23-2300/src/DataFormats/L1TrackTrigger/interface/TTTypes.h:19:
In file included from /cvmfs/cms-ib.cern.ch/sw/aarch64/week1/el8_aarch64_gcc11/cms/cmssw-patch/CMSSW_13_0_X_2023-01-23-2300/src/DataFormats/L1TrackTrigger/interface/TTTrack.h:18:
In file included from /cvmfs/cms-ib.cern.ch/sw/aarch64/week1/el8_aarch64_gcc11/cms/cmssw-patch/CMSSW_13_0_X_2023-01-23-2300/src/DataFormats/L1TrackTrigger/interface/TTTrack_TrackWord.h:20:
In file included from /cvmfs/cms-ib.cern.ch/sw/aarch64/nweek-02769/el8_aarch64_gcc11/external/hls/2019.08-fd724004387c2a6770dc3517446d30d9/include/ap_int.h:20:
In file included from /cvmfs/cms-ib.cern.ch/sw/aarch64/nweek-02769/el8_aarch64_gcc11/external/hls/2019.08-fd724004387c2a6770dc3517446d30d9/include/ap_common.h:252:
/cvmfs/cms-ib.cern.ch/sw/aarch64/nweek-02769/el8_aarch64_gcc11/external/hls/2019.08-fd724004387c2a6770dc3517446d30d9/include/etc/ap_private.h:1546:34: warning: format specifies type 'unsigned long long *' but the argument has type 'uint64_t *' (aka 'unsigned long *') [-Wformat]
        sscanf(strStart, "%llu", &tmpVAL);
                          ~~~~   ^~~~~~~
                          %lu
/cvmfs/cms-ib.cern.ch/sw/aarch64/nweek-02769/el8_aarch64_gcc11/external/hls/2019.08-fd724004387c2a6770dc3517446d30d9/include/etc/ap_private.h:1557:34: warning: format specifies type 'unsigned long long *' but the argument has type 'uint64_t *' (aka 'unsigned long *') [-Wformat]
        sscanf(strStart, "%llx", &tmpVAL);
                          ~~~~   ^~~~~~~
                          %lx
```

which are also present in the build logs: https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_ppc64le_gcc11/CMSSW_13_0_X_2023-01-24-2300/unitTestLogs/Alignment/OfflineValidation#/1788

**Comment by smuzaffar** [comment]
@mmusich , please try CMSSW_13_0_X_2023-01-24-2300 or above IB (where https://github.com/cms-sw/cmsdist/pull/8262 has been integrated) and  `scram b runtests_GeneralTrackAnalyser` should work there.

**Comment by mmusich** [comment]
> (where https://github.com/cms-sw/cmsdist/pull/8262 has been integrated)

ah, great.

**Comment by aandvalenzuela** [comment]
For me, it is the second cmsRun command: https://github.com/cms-sw/cmssw/blob/907d99116df35884936b6f5eb76018d4352ad482/Alignment/OfflineValidation/test/testingScripts/test_unitGeneralTrackAnalyser.sh#L7 the one that now takes around 80 min.

**Comment by mmusich** [comment]
>  the one that now takes around 80 min.

I cannot confirm. In my setup the test ends in about 20 minutes.
Also the [test logs](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_ppc64le_gcc11/CMSSW_13_0_X_2023-01-24-2300/unitTestLogs/Alignment/OfflineValidation#/1925) point to a segfault not a timeout.

**Comment by aandvalenzuela** [comment]
I think the external termination request comes from our side if the tests is taking more than 90 min.

**Comment by mmusich** [comment]
> I think the external termination request comes from our side if the tests is taking more than 90 min.

I see, it would be useful to make that clearer from the test logs.
On the other hand I am still puzzled, because in my local checkout it takes much less time than that (also it looks like in the other builds it works nicely). In any case we can try to reduce the amount of event processed and see if it fixes - though I suspect it's a symptom of something deeper.

**Pull request merged**
