### PR TITLE
Fix CaloParticle Debugger

### PR DESCRIPTION
**Pull request by rovere**
Adapt the CaloParticle debugger code to handle also TDR geometries of
HGCAL.

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
please test

**Comment by rovere** [comment]
I doubt that those errors are in any way related to this PR. I saw them also in other PR. Could someone please re-trigger the tests?

**Comment by fabiocos** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
