### PR TITLE
Disable clang's bitwise-instead-of-logical warnings for some parts of code

### PR DESCRIPTION
**Pull request by iarspider**
#### PR description:

Silences clang warnings as discussed in https://github.com/cms-sw/cmssw/issues/39105#issuecomment-1220479108

#### PR validation:

Cosmetic changes, should not affect the actual execution of the code.

### CODE REVIEW

**Comment by iarspider** [comment]
please test for CMSSW_13_1_CLANG_X

**Comment by smuzaffar** [comment]
@VinInn , what do you think about this approach ? If this is fine then may be we can define some macros in some common headers file and do
```
DISABLE_WARNING(warnings-type)

code

ENABLE_WARNING(warnings-type)
```

**Comment by iarspider** [comment]
please test for CMSSW_13_1_CLANG_X

**Comment by smuzaffar** [comment]
please test

@mandrenguyen, comparisons are done between default IB and clang based IB that is why you see differences.

**Comment by mandrenguyen** [comment]
+reconstruction
As explained by @smuzaffar the differences in comparisons come from using a different compiler in the baseline and test.
https://github.com/cms-sw/cmssw/pull/40914#issuecomment-1451875448
Purely technical PR, just suppresses some clang warnings.

**Comment by perrotta** [comment]
+1

**Pull request merged**
