### PR TITLE
Run3-gem50 Simplify access to fv and a dump utility

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Simplify access to fv and a dump utility

#### PR validation:

Tested using cfg's in test area of Geometry/RPCGeometryBuilder

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing sepial

### CODE REVIEW

**Comment by cvuosalo** [comment]
I just noticed that there is a problem with `ME0GeometryBuilder.cc`. If one compiles it with `-DEDM_ML_DEBUG -DEDM_ML_LOGDEBUG`, there will be a link error. I haven't figured out the fix yet. Line 391 and `ME0DetId::chamberIdMask_` are causing the problem:
```
#ifdef EDM_ML_DEBUG
    edm::LogVerbatim("ME0Geometry") << fv.name() << " with " << history.tags.size() << " Levels and ID " << detId
                                    << " Mask " << std::hex << ME0DetId::chamberIdMask_ << ":" << ME0DetId::layerIdMask_
                                    << std::dec << " and " << ME0DetId(((detId.rawId()) & ME0DetId::chamberIdMask_))
                                    << ":" << ME0DetId(((detId.rawId()) & ME0DetId::layerIdMask_)) << " Sector Level "
                                    << theSectorLevel << ":" << history.tags.size() << ":" << fv.copyNos().size();
    for (unsigned int k = 0; k < history.tags.size(); ++k)
      edm::LogVerbatim("ME0Geometry") << "[" << k << "] Tag " << history.tags[k] << " Offset " << history.offsets[k]
                                      << " copy " << history.copyNos[k];
#endif
```

**Comment by cvuosalo** [comment]
@bsunanda I tried your fixes, but they don't solve the problem when I tried. I found a cast was necessary:
```
<< " Mask " << std::hex << ((unsigned int) ME0DetId::chamberIdMask_) << ":" << ((unsigned int) ME0DetId::layerIdMask_)
```
There is some problem with the template in ​`FWCore/​MessageLogger/​interface/​ErrorObj.icc` and these `static const unint32_t` data members.

**Comment by cvuosalo** [comment]
@bsunanda Chris says, "The real fix is to change all the `static const` in ME0DetId to be `static constexpr`."  Can you please add this fix to this PR?

**Comment by cvuosalo** [comment]
@bsunanda Thanks for the fixes.

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade

**Comment by qliphy** [comment]
+1

**Pull request merged**
