### PR TITLE
Run3-hcx329 move std::cout to edm::LogVerbatim for the codes of Geometry/HcalTowerAlgo amd also update the cfg's

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

move std::cout to edm::LogVerbatim for the codes of Geometry/HcalTowerAlgo amd also update the cfg's

#### PR validation:

Use the runTheMatrix test workflows and cfg's in the test area

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
