### PR TITLE
Fix sign error in expression in GEM digitizer

### PR DESCRIPTION
**Pull request by watson-ij**
#### PR description:

A sign error was introduced when turning magic numbers into named parameter in the following commit:
https://github.com/cms-sw/cmssw/commit/334761919eca55c5c93f6e58574b55432c4f42ef#diff-a4f2f038afa58c34cba02c63dd10a0a5e318afd43c03b05dd941b99c6e00b3a4
The negative sign is used twice, once in the parameter, once in the expression.

@jshlee @yeckang 

#### PR validation:

Checked on a small test. The GEM digi and rechit distributions changed slightly.

Plotting the eff. expression with the correct (i.e. the original expression, and the expression reverted to by this PR) or incorrect signs (i.e. the expression after the changes to add named parameters instead of magic), you can see that the eff. should be lower for the particular branch:
eff_check

and you can see slightly less gem hits in the cluster size plot for instance:
all_OldVSNew_TTbar14TeV2026D76PUwPRMXwf34834p999c_GEMDetIdGEMRecHitsOwnedRangeMap_gemRecHits__RECO_obj_collection__data__clusterSize

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

@watson-ij , may be you can add some plot(s) to description?

**Comment by watson-ij** [comment]
@civanch, yep added a plot showing what the different expressions give for the eff. and how this corresponds to number of gemhits after the update. It looks like theres some minor knock-on effects to the muon parameters in a few of the workflows, and the test picked up some differences from #34103 maybe. I think between those they explain the differences in the plots that are shown in the tests.

**Comment by srimanob** [comment]
type bug-fix

**Comment by srimanob** [comment]
+Upgrade

**Comment by qliphy** [comment]
+1

**Pull request merged**
