### PR TITLE
Run2-hcx184: Clear some warnings during compilations

### PR DESCRIPTION
**Pull request by bsunanda**
Also treat the subdetid method correctly

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by ianna** [comment]
@bsunanda - it seems strange to compare eta and phi with their mask.

**Comment by bsunanda** [comment]
@ianna The mask somehow gives the maximum possible value. Most likely that is why they are used in many places. I did not realize it till I see it.

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by vkhristenko** [comment]
device code is compiled with clang or nvcc? I can't seem to find the actual cmd used, but i guess it's nvcc. 

nvcc needs a `--expt-relaxed-constexpr` added to the compiler flags to consider constexpr funcs as `__host__ __device__`

**Comment by kpedro88** [comment]
@vkhristenko is the error actually caused by this PR?

**Comment by bsunanda** [comment]
@vkhristenko Yes the message is /build/cmsbld/jenkins/workspace/ib-any-integration/CMSSW_10_3_X_2018-09-21-1100/src/DataFormats/HcalDetId/test/test_hcal_detid.cu(10): error: calling a constexpr __host__ function("DetId") from a __global__ function("test_gen_detid") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this

But can the code be changed such that '--expt-relaxed-constexpr'  is not needed? If there is no constexpr - just a simple const  would it compile without the extra compilation flag?

**Comment by vkhristenko** [comment]
I did not mean the error msg, I meant compiler invocation cmd

Cleanest is to include this flag. I’m a bit puzzled that this has not come
up before... meaning all the builds with gcc for instance.

VK

**Comment by bsunanda** [comment]
I believe Shahzad can introduce this flag for the "clang" test. What might have happened is that the choice of compiler was changed sometimes in-between since last time this package was compiled

**Comment by kpedro88** [comment]
@smuzaffar what do we need to modify to include an extra flag in the clang build?

**Comment by smuzaffar** [comment]
@kpedro88 , for clang tests, we still use `nvcc` to compile .cu files. We can pass `USER_CUDA_FLAGS='--expt-relaxed-constexpr'` to clang tests to avoid this.

**Comment by smuzaffar** [comment]
@kpedro88 , looks like a bug in the build rules. cuda tool file does include this flag
```
<flags CUDA_FLAGS="-O3 -std=c++14 --expt-relaxed-constexpr --expt-extended-lambda"/>
```
and it was not picked up by the PR tests. I am looking in to it.

**Comment by smuzaffar** [comment]
please test
for now I passed `USER_CUDA_FLAGS='--expt-relaxed-constexpr'` for PR clang tests. I will provide a proper fix for build rules later.

**Comment by ianna** [comment]
@smuzaffar - it looks like ```catch (...)``` is not in the code checks: see
CalibCalorimetry/CaloMiscalibTools/interface/CaloMiscalibMapHcal.h

**Comment by davidlange6** [comment]
Your PR is unmergeable. Please have a look and possibly rebase it.

**Comment by bsunanda** [comment]
close this in favour of #24701

**Pull request closed without merging**
