### PR TITLE
another apptainer workaround [14_0_X]

### PR DESCRIPTION
**Pull request by kpedro88**
backport of #45652

### CODE REVIEW

**Comment by kpedro88** [comment]
please test

**Comment by makortel** [comment]
@cmsbuild, please test for slc7_amd64_gcc12

**Comment by makortel** [comment]
el8 comparison differences are related to https://github.com/cms-sw/cmssw/issues/39803 and https://github.com/cms-sw/cmssw/issues/45505

slc7 unit test failure should get fixed with https://github.com/cms-sw/cmssw/pull/45614

**Comment by makortel** [comment]
+heterogeneous

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
