### PR TITLE
Prompt skims for PbPb and pp at 5 TeV

### PR DESCRIPTION
**Pull request by mandrenguyen**
Note that the final HLT emulation has not been added to the release yet.
However these skims will not crash, they just bail if the trigger path isn't present.

We tested the reco-level filters on a sample with the HLT menu which is about to be put into the release, following a recipe provided by DDT.

If anyone is interested, the recipe follows.

Example for PbPb:
cmsDriver.py skims -s SKIM:Photon --scenario HeavyIons --data --filein=file:/afs/cern.ch/work/m/mnguyen/public/promptSkimTestInput/hiReco_RAW2DIGI_L1Reco_RECO_forPromptSkim_ttbar_FEVTDEBUGHLT.root -n 1000 --conditions auto:com10 --python_filename=test.py --processName=SKIM --no_exec

Example for pp:
skims -s SKIM:Onia --data --filein=file:/afs/cern.ch/work/m/mnguyen/public/promptSkimTestInput/ppReco_RAW2DIGI_L1Reco_RECO_forPromptSkim_ttbar_FEVTDEBUGHLT.root -n 1000 --conditions auto:com10 --python_filename=oniaZMM.py --processName=SKIM --no_exec 

The HLT re-emulation was done with a different label, so you need to add the following snippet by hand to the cfg:
from HLTrigger.Configuration.CustomConfigs import MassReplaceInputTag
process = MassReplaceInputTag(process,cms.InputTag("TriggerResults","","HLT"),cms.InputTag("TriggerResults","","TEST"))

### CODE REVIEW

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
@mandrenguyen - could you move these configs to Configuration/Skimming? I would prefer that the analysis packages are kept for non-production analysis rather than for production.

**Comment by mandrenguyen** [comment]
@davidlange6 
I updated according to your request.

**Comment by davidlange6** [comment]
Thanks ! (as a added benefit those organizing the skims now are on the signature list)

**Comment by mandrenguyen** [comment]
@davidlange6 How about a please test  ?

**Comment by davidlange6** [comment]
please test

(good point..)

**Comment by fabozzi** [comment]
+1

**Pull request merged**
