### PR TITLE
Fix -1 precision in SimpleFlatTableProducer

### PR DESCRIPTION
**Pull request by kdlong**
When using a string function for the precision in SimpleFlatTableProducer, -1 does not actually result in full precision. This is because reduceMantissaToNbitsRounding doesn't actually accept -1 as an argument, in other places where this is used, the call to reduceMantissaToNbinsRounding is bypassed: https://github.com/kdlong/cmssw/blob/ece4581e13b78bc0f0fb87c93296bcbe90c79500/DataFormats/NanoAOD/interface/FlatTable.h#L28

I'm not aware of this showing up in the normal nano production, but we use it in the Wmass customisation here [1], and have only realised that the pt precision, which should be -1 => full precision, is actually set incorrectly to quite low precision (not 100% sure how it is treated).

[1] https://github.com/kdlong/cmssw/blob/ece4581e13b78bc0f0fb87c93296bcbe90c79500/PhysicsTools/NanoAOD/python/nano_cff.py#L206

### CODE REVIEW

**Comment by vlimant** [comment]
enable nano

**Comment by vlimant** [comment]
please test

**Comment by vlimant** [comment]
I thought that the weird looking C++ was a GitHub viewing artifact, but instead it is a plain missing `;` typo.
@kdlong please modify, and confirm that it compiles locally.

**Comment by kdlong** [comment]
Will close and reopen this, I've messed up branches.

**Pull request closed without merging**
