### PR TITLE
Unit test for EventFilter modules (11_1_X)

### PR DESCRIPTION
**Pull request by smorovic**
#### PR description:

* Addition of unit test to verify functionality of DAQ input source, services and output modules in a simple HLT configuration. In addition, HLTRates and DQMHistograms streams are produced.

* DQMFileSaver(PB) configuration in test configurations is updated for 11_1_X changes.

#### PR validation:

New unit tests will be checked by cmsbuild and should pass prior to integrating these changes.

### CODE REVIEW

**Comment by smorovic** [comment]
Test is being added based on discussion on the issue #28786 (notifying @makortel ).

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by smorovic** [comment]
Test fails due to the provenance problem reported earlier. We should retest after #28791 is merged.

**Comment by makortel** [comment]
> Test fails due to the provenance problem reported earlier.

Right, that's what I wanted to see. I was thinking to re-test with https://github.com/cms-sw/cmssw/pull/28791 after the comparisons finish.

**Comment by makortel** [comment]
@cmsbuild, please test with #28791

**Comment by makortel** [comment]
Seems to work, thanks @smorovic.

**Comment by smorovic** [comment]
great @makortel , thanks for testing.
Pinging @mommsen oe @emeschi to sign from DAQ side.

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/28799	12ca70a 
- this PR does not affect any reco category files in the modified package EventFilter/Utilities, which is shared with the DAQ category
- jenkins tests pass

**Comment by mommsen** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
