### PR TITLE
remove nano specific setting for IMT

### PR DESCRIPTION
**Pull request by vlimant**
#### PR description:

following up on #43123 this PR removes the specific setting for merging NANO files

#### PR validation:

I don't think there exist a T0 merge testing workflow in the matrix as it is, hence I let the cmsbot test do it's thing, and we will check with Tier0 operation how to test

FYI : @drkovalskyi

### CODE REVIEW

**Comment by vlimant** [comment]
enable nano

**Comment by vlimant** [comment]
please test

**Comment by vlimant** [comment]
+1

**Comment by rappoccio** [comment]
+1

**Pull request merged**
