### PR TITLE
Link slimmed muons to lost tracks

### PR DESCRIPTION
**Pull request by stahlleiton**
#### PR description:

This PR add the option to link slimmed muons to lost tracks and add the muon ID information to lost tracks.
This is useful to find the corresponding packed candidate associated to the slimmed muon and recover additional muons using the maps produced by PackedCandidateMuonSelectorProducer.

#### PR validation:

Tested with workflow 140.5611 (PbPb 2018 MiniAOD)

### CODE REVIEW

**Comment by clacaputo** [comment]
@cmsbuild please test

**Comment by stahlleiton** [comment]
Looking at the reco differences, they all come from lost track muon ID related branches as expected. Not sure I understand the differences on the edmErrorSummaryEntrys_logErrorHarvester related branches.

**Comment by jpata** [comment]
type muon

**Comment by jpata** [comment]
@cms-sw/muon-pog-l2 @CeliaFernandez @trocino there are changes to lost tracks muon flags in standard MINI. Do you expect issues from this?

https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_4_X_2022-04-19-1100+b20169/49700/validateJR/all_mini_OldVSNew_TTbarPUwf25202p0/all_mini_OldVSNew_TTbarPUwf25202p0c_patPackedCandidates_lostTracks_eleTracks_RECO_obj_isStandAloneMuon.png

all_mini_OldVSNew_TTbarPUwf25202p0c_patPackedCandidates_lostTracks_eleTracks_RECO_obj_isStandAloneMuon

**Comment by stahlleiton** [comment]
I would not expect an impact for muons, since currently the lost tracks have the muon ID flags always set to false (so not filled). However, I could decouple the inclusion of muon ID to lost tracks from this PR into a new PR, if that helps the review.

**Comment by jpata** [comment]
@cmsbuild please test

**Comment by jpata** [comment]
+reconstruction
- changes to patPackedCandidates_lostTracks (muon link is now set) and nothing else

**Comment by perrotta** [comment]
+1

**Pull request merged**
