### PR TITLE
Add FEDRawDataCollection to RAWMINIAOD skim event content

### PR DESCRIPTION
**Pull request by kfjack**
Adding FEDRawDataCollection to RAW+MINIAOD event content, which is used in the MuTau skim.

### CODE REVIEW

**Comment by fabozzi** [comment]
please test

**Comment by davidlange6** [comment]
hi @kfjack - seems a clear fix - but any idea how this was missed in the validation last fall (when the event content was updated previously)?

**Comment by kfjack** [comment]
Hi @davidlange6 - not sure. It might be correlated with miniAOD updates. I was looking into the blame history but no clear clue. Sounds like it is better to have a tighter cross check from my side. 

Do you know how to implement an automatic check for every build? Now the cross check with relval is done by myself from time to time with a private script, and it is not very smart/efficient.

**Comment by davidlange6** [comment]
> On Jul 26, 2017, at 11:01 AM, Kai-Feng Chen <notifications@github.com> wrote:
> 
> Hi @davidlange6 - not sure. It might be correlated with miniAOD updates. I was looking into the blame history but no clear clue. Sounds like it is better to have a tighter cross check from my side.

nah - it was a bug from day one - it should have been found in the relval checks that I asked for  (and got confirmation of) at theme..

> 
> Do you know how to implement an automatic check for every build? Now the cross check with relval is done by myself from time to time with a private script, and it is not very smart/efficient.

we have lots of automatic checks. What sort of check do you have in mind?

**Comment by kfjack** [comment]
Ok. So the bug was there at beginning. Apparently this is not good... 
I want to do 
1) make sure all of the active skims have their output in relval.
2) make sure the event content is correct (or the same as before).

The current lazy script in my hand is just listing relval files and check if the corresponding skim files are there, without checking the contents.

**Comment by davidlange6** [comment]
> On Jul 26, 2017, at 11:24 AM, Kai-Feng Chen <notifications@github.com> wrote:
> 
> Ok. So the bug was there at beginning. Apparently this is not good...
> I want to do
> 
> 	• make sure all of the active skims have their output in relval.
> 	• make sure the event content is correct (or the same as before).

neither of these addresses the current issue.. which is when someone makes a new skim that they check its contents in relval and confirm to pdmv that things are working.,.. (pdmv confirmed this skim was validated..) 

but ok - for the first one - you can consider writing a unit test that greps through runTheMatrix.py -l all -ne to see what skims are running? If you want to actually check the output of relval production for a prerelease, I guess you'd want to script against das and have that run as part of the validation campaign.

for the second - its not so simple - event contents do change. Eg, people add products to the AOD or RECO. pdmv of course signs whenever someone asks to change a skim event content definition. What sort of check do you want to implement?

**Comment by kfjack** [comment]
Indeed implementing those checks cannot resolve this current issue (or prevent from it for future updates; the content should be checked by skim users in any case), but better than nothing I think...

Anyway for the check one - do you have a recommended starting point? Given I still have ~few working days I can dig a little bit here.
for the check two - no clear idea for now (was thinking to compare the list of event contents with a reference version or so).

**Comment by davidlange6** [comment]
merge

**Pull request merged**
