### PR TITLE
HGCal - bugfix: Fix clamp range in tiling

### PR DESCRIPTION
**Pull request by felicepantaleo**
#### PR description:
The upper limit when using `std::clamp` on the number of bins should be the number of bins minus 1.
When hitting the very last bin, this could lead to SEGFAULT.

@rovere @ZihengChen

### CODE REVIEW

**Comment by felicepantaleo** [comment]
type bugfix

**Comment by felicepantaleo** [comment]
please test workflow 20493.52

**Comment by perrotta** [comment]
It is strange that in wf 11634.0 there are differences in the number of conversion photons
The very same was observed in PR #28016, and both here and there I don't see any possible reason for it, It looks like some non-reproducibility was recently introduced.
Let retry running the tests, just to verify if anything changed

**Comment by perrotta** [comment]
please test workflow 20493.52

**Comment by perrotta** [comment]
+1
- Fixes are correct
- Jenkins tests pass

**Comment by kpedro88** [comment]
+upgrade

**Comment by fabiocos** [comment]
+1

**Pull request merged**
