### PR TITLE
Activate Simulation of the Pixel Bad Components on the FED channel basis

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:
Based on the feedback received so far in https://its.cern.ch/jira/browse/PDMVRELVALS-30, the goal of this PR is to:
   * switch on simulation of the Pixel Bad Components on the FED channel basis (a.k.a. stuck-TBM simulation)
   * supply default payloads for the new record `SiPixelStatusScenarioProbabilityRcd `and `SiPixelStatusScenariosRcd` introduced in PR https://github.com/cms-sw/cmssw/pull/25466/, to all the phase-1 Global Tags.

As the `SiPixelStatusScenario` payload used in all the updated Global Tags contains (still) no bad components and the `SiPixelStatusScenarioProbability` payload defaults this "empty" scenario for all the PU bins, no changes in the physics outcome are expected from this PR, which then can be qualified as technical. 
2017 and 2018 simulation Global Tags will be updated in a later time once appropriate conditions will be available. 

#### PR validation:
The branch was tested via:
```
runTheMatrix.py -l limited -i all -j 8 --ibeos
```
and no failing workflows are observed: 32 31 30 24 12 2 1 1 1 tests passed, 0 0 0 0 0 0 0 0 0 failed.

### CODE REVIEW

**Comment by mmusich** [comment]
@tsusa FYI

**Comment by tocheng** [comment]
@cmsbuild please test

**Comment by mmusich** [comment]
> DQMHistoTests: Total failures: 17436

as expected changes affect only phase1 + run3 MC workflows and are all small and I think compatible with random fluctuations due to update of the digitizer sequence.

**Comment by mmusich** [comment]
In the last push I propose commit https://github.com/cms-sw/cmssw/pull/26275/commits/5ffe308def88e2dbb0829a06b81a4006e790f7d2  from @tocheng, including full-fledged Global Tags instead of Global Tag candidates.

**Comment by tocheng** [comment]
@cmsbuild please test

**Comment by civanch** [comment]
+1

**Comment by tocheng** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
@tocheng @mmusich are the added new tags up to date? After their integration we have wf 10424.0 failing with the error

```
----- Begin Fatal Exception 02-Apr-2019 10:01:54 CEST-----------------------
An exception of category 'NoRecord' occurred while
   [0] Processing global begin Run run: 1
   [1] Calling method for module GEMDigiToRawModule/'gemPacker'
Exception Message:
No "GEMeMapRcd" record found in the EventSetup.n
 Please add an ESSource or ESProducer that delivers such a record.
----- End Fatal Exception -------------------------------------------------
```

Apparently GEMs are not included...

**Comment by mmusich** [comment]
@fabiocos not that this is of my concern as it has nothing to do with suck-TBM simulation, but I made the point with @tocheng about lots of spurious differences in the GT he provided:

```
$ conddb diff 106X_mc2017_design_IdealBS_v1 105X_mc2017_design_IdealBS_v6
[2019-04-02 10:16:19,069] INFO: Connecting to pro [frontier://PromptProd/CMS_CONDITIONS]
Record                               Label  pro::106X_mc2017_design_IdealBS_v1 Tag                    pro::105X_mc2017_design_IdealBS_v6 Tag   
-----------------------------------  -----  --------------------------------------------------------  ---------------------------------------  
GEMeMapRcd                           -      -                                                         GEMeMap_v1_mc                            
PFCalibrationRcd                     -      PFCalibration_v9_mc                                       PFCalibration_v10_mc                     
PFCalibrationRcd                     HLT    PFCalibration_HLT_2017_25ns_Spring17_V3_newCodeCompliant  PFCalibration_HLT_2018_25ns_Spring19_V1  
SiPixelStatusScenarioProbabilityRcd  -      SiPixelStatusScenarioProbabilities_default_v0_mc          -                                        
SiPixelStatusScenariosRcd            -      SiPixelFEDChannelContainer_Empty_mc                       -     
```
And he said this was OK.
I think AlCa should provide a fix.

**Comment by tocheng** [comment]
@fabiocos This is my bad. The issue is 2017 Ideal GT. Fixing now.

**Pull request merged**
