### PR TITLE
Filter to select HLT paths corresponding to peripheral HI events

### PR DESCRIPTION
**Pull request by mandrenguyen**
For a reprocessing of peripheral PbPb events with pp reco.

Tested with:
cmsDriver.py step3 --process ppRECO --repacked --conditions 75X_dataRun2_PromptHI_v3 -s FILTER:RecoHI/Configuration/peripheralHLTFilter_cff.peripheralHLTFilterSequence,RAW2DIGI,L1Reco,RECO --datatier AOD --customise Configuration/DataProcessing/RecoTLR.customiseDataRun2Common_50nsRunsAfter253000 --customise RecoHI/Configuration/customise_PPwithHI.customisePPwithHI --data --scenario pp --eventcontent AOD --no_exec

### CODE REVIEW

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
FILTER: method doesn't work with PAT, ALCA, and probably not even with DQM (although DQM in 75X has its own issue with --repacked flag). ConfigBuilder doesn't track all cases with filters.
I will not make attempts to fix it in 75X, but will try to get a fix in 81X.

@mandrenguyen 
please confirm that you are not planning any extra steps in the RECO sequence for this processing.

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/13776	4033648
- code changes are in line with the description: add HLT filter for RECO reprocessing of HI events with pp sequence
- jenkins tests pass (compilation only; the jenkins tests do not include the new feature test)
- tested locally in CMSSW_7_5_8_patch3 together with #13604 to get the customise_PPwithHI.customisePPwithHI method as well
    - cmsDriver setup works up to RECO and EI. Addition of other steps will fail because they are not modified by the ConfigBuilder correctly to prepend the filter sequence. The extra steps are apparently not going to be used in the  75X  reprocessing workflow. #13807 is added aiming to fix this issue for 81X.
    - test on 100 events from HIHardProbesPeripheral2015 in run 262768 LS 378 shows that all events pass the filter (consistent with the PD definition); average time/event here is 70s/evt
    - test on 100 events from HIHardProbes2015 run 262694 LS 100 shows that only 33 events pass the filter and the passing events take much less time (33 s/evt average with still a rather large spread: max is ~300 s/evt) somewhat consistent with time/event in HIHardProbesPeripheral2015.

**Comment by mandrenguyen** [comment]
@slava77 confirmed.

**Pull request merged**
