### PR TITLE
Updated Z->ee skim for Run2

### PR DESCRIPTION
**Pull request by emanueledimarco**
This is an updated skim for Z->ee for Run2. The T&P pairs have been removed to keep the efficiency on DoubleElectron sufficiently low to have the skim run centrally. 

The cuts are:
- pT > 20 / 10 GeV
- electron ID veto (including PF isolation)
- 40 < mass < 140 GeV

the selection has been synchronised with the AlcaElectron stream.

### CODE REVIEW

**Comment by franzoni** [comment]
@alkaloge 
have you been able to test this ?

**Comment by alkaloge** [comment]
cmsDriver crashes for me (7_5_0_pre3)
cmsDriver.py skims -s SKIM:ZElectron --data --dasquery="file dataset=/SingleElectron/CMSSW_7_4_0-GR_R_74_V10A_RelVal_electron2012A-v1/RECO" -n 100 --conditions auto:com10 --python_filename=ZElectron_SKIM.py --processName=SKIMZElectron

complains for "NameError: name 'tagGsfSeq' is not defined" (basically you need to change accordingly the Skims_DPG_cff.py file

@emanueledimarco can you check  ? Also please remove DPGAnalysis/Skims/python/test_ZeeSkim.py from this dir

**Comment by emanueledimarco** [comment]
Sorry, I didn't know about the summary cff file. Now I have updated it and tested on DoubleElectron [1]
@shervin86 please also follow this.

[1] cmsDriver.py skims -s SKIM:ZElectron --data --dasquery="file dataset=/DoubleElectron/CMSSW_7_4_3-GR_R_74_V12A_RelVal_zEl2012D-v5/RECO" -n 100 --conditions auto:com10 --python_filename=ZElectron_SKIM.py --processName=SKIMZElectron

**Comment by alkaloge** [comment]
tested - looks good to go

**Comment by franzoni** [comment]
thanks @alkaloge

**Comment by franzoni** [comment]
please test

**Comment by emanueledimarco** [comment]
Any news on this?

**Comment by franzoni** [comment]
+1

**Comment by davidlange6** [comment]
@emanueledimarco - could you remove the new printout?

**Comment by emanueledimarco** [comment]
@davidlange6 done here and in the 74X back port #9549

**Comment by franzoni** [comment]
please test

**Comment by franzoni** [comment]
+1
sicne the only change is print

**Pull request merged**
