### PR TITLE
OfflineDQM: Offline L1T muon DQM with coordinates extrapolated to the muon system CMSLITDPG-729

### PR DESCRIPTION
**Pull request by stahlleiton**
Solves https://its.cern.ch/jira/browse/CMSLITDPG-729

Description: The offline muon DQM efficiency and resolution calculations are now done with the reco muon coordinates extrapolated to the 2nd muon station. The legacy code used to perform the extrapolation in Run-1 has been replaced with the current one used in the L1 ntuple generation. In addition, the pT thresholds of the tag and the probe muons have been updated to the 2018 values.

### CODE REVIEW

**Comment by thomreis** [comment]
please test

**Comment by andrius-k** [comment]
@stahlleiton Could you please make sure that the name of the subsystem is mentioned in the title of the PR?

**Comment by thomreis** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
