### PR TITLE
Make L1TMuonOverlapTrackProducer a one module

### PR DESCRIPTION
**Pull request by Dr15Jones**
The L1TMuonOverlapTrackProducer is showing up as stalling during DIGI workflows.

The module could not be made into a stream module since it has a mode where it can write out an XML file. I highly recommend that this mode be removed so a more thread efficient module type can be used.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by thomreis** [comment]
Hi @konec 
do you think there is a possibility to move the writing of the XML to some other place in order to be able to make this a stream module?

**Comment by thomreis** [comment]
+1
We are discussing internally how this could be made a stream module. The writing to XML is a mode that is only used in expert operation and not in production. @Dr15Jones could a stream module be acting as a one module depending on a configuration parameter?

**Comment by fabiocos** [comment]
+1

**Comment by Dr15Jones** [comment]
@thomreis since deciding on a `::one` or `::global` depends on inheritance, it is not possible to change their _type_ based on configuration.

**Comment by konec** [comment]
@Dr15Jones, @thomreis  
XML writing is there only for debugs, used by experts, not in normal production running.
If it is not possible to keep there this XML writer, maybe it can be hide under #ifndef ?
(ie. two constructors). Otherwise please remove XML part, we will add additional producer with XML code.
@akalinow

**Pull request merged**
