### PR TITLE
Fix bug in PVAssignment: missing abs for dxy

### PR DESCRIPTION
**Pull request by arizzi**
This fixes the bug found by  @VinInn  of missing abs in PV association

Same as #8721 

@davidlange6 @slava77  can we include this in 741 in the shadow of the PF nan fix?

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
@cmsbuild please test
trying one more time

**Comment by slava77** [comment]
I ran tests in CMSSW_7_4_0 /my test area sign537/
and see that there is a fairly high rate of changes (~20%) in low-pileup minbias data samples (I manually checked 2011A from matrix wflow 1000.0).
This seems too large.

The phase space of affected vertices will have to correspond to those that have tracks closest to them in dZ but are not so close (|dz|> 0.03 .AND. |dZ|/errZ > 2).

What seems to happen is that per event there are frequently tracks with large z and x,y values that don't really have much to do with any reconstructed vertex: the  "bug-fixed" PVAssignment attaches them to the closest vertex in dz as OtherDz, while the buggy one was assigning them to the same vertex as NotReconstructedPrimary. The NotReconstructedPrimary is not considered in the vertex score computation, which is actually a good thing for random "noise" tracks. 
Event 165121:62:23715214 (from 1000.0 workflow) was just the first one and seemed to fit the hypothesis of unrelated tracks association.

The bugfix effectively doubles the rate of random noise tracks entering the vertex score computation.
Of course, it also doubles the number of real highly displaced tracks connected to the vertex.

My feeling is that the bugfix is likely doing more harm for events with prompt physics signatures and probably some extra selections would be better to keep tracks just in the OtherDz category.
Does this make sense, or is there some good reasoning that all tracks (even outside of the luminous region or with very large dxy still have to be assigned to a vertex closest in dz)?

**Comment by slava77** [comment]
a23715214

note that my comment above may just primarily be relevant to  the sub-leading vertices:
in this event (above) there is a fairly energetic vertex at z~1.8 cm which is probably the origin of the highlighted tracks (all with z< -1.5 cm), which end up being assigned to the vertex at z= -1.4 cm by "OtherDz"

**Comment by davidlange6** [comment]
@slava77 - it seems what you really say is that the intended algorithm is worse than some other options. What is currently implemented is clearly physically incorrect

**Comment by slava77** [comment]
if a bug in one part of the logic cancels out shortcoming in the other
part of the logic,
with other things equal, I'd rather either see both resolved or to keep
the current state unchanged.

On 4/14/15 7:32 PM, David Lange wrote:
> @slava77 - it seems what you really say is that the intended algorithm
> is worse than some other options. What is currently implemented is
> clearly physically incorrect
> 
> 
>> On Apr 15, 2015, at 1:51 AM, Slava Krutelyov <notifications@github.com> wrote:
>> 
>> I ran tests in CMSSW_7_4_0 /my test area sign537/
>> and see that there is a fairly high rate of changes (~20%) in low-pileup minbias data samples (I manually checked 2011A from matrix wflow 1000.0).
>> This seems too large.
>> 
>> The phase space of affected vertices will have to correspond to those that have tracks closest to them in dZ but are not so close (|dz|> 0.03 .AND. |dZ|/errZ > 2).
>> 
>> What seems to happen is that per event there are frequently tracks with large z and x,y values that don't really have much to do with any reconstructed vertex: the "bug-fixed" PVAssignment attaches them to the closest vertex in dz as OtherDz, while the buggy one was assigning them to the same vertex as NotReconstructedPrimary. The NotReconstructedPrimary is not considered in the vertex score computation, which is actually a good thing for random "noise" tracks. 
>> Event 165121:62:23715214 (from 1000.0 workflow) was just the first one and seemed to fit the hypothesis of unrelated tracks association.
>> 
>> The bugfix effectively doubles the rate of random noise tracks entering the vertex score computation.
>> Of course, it also doubles the number of real highly displaced tracks connected to the vertex.
>> 
>> My feeling is that the bugfix is likely doing more harm for events with prompt physics signatures and probably some extra selections would be better to keep tracks just in the OtherDz category.
>> Does this make sense, or is there some good reasoning that all tracks (even outside of the luminous region or with very large dxy still have to be assigned to a vertex closest in dz)?
>> 
>> —
>> Reply to this email directly or view it on GitHub.
>> 
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cms-sw/cmssw/pull/8722#issuecomment-93123744>.
> 

-- 
***********************************************************************
 Vyacheslav (Slava) Krutelyov
 TAMU: Physics Dept Texas A&M MS4242, College Station, TX 77843-4242
 CERN: 42-R-027
 AIM/Skype: siava16              googleTalk: slava77@gmail.com
 (630) 291-5128  Cell (US)       +41 76 275 7116 Cell (CERN)

-----------------------------------------------------------------------

**Comment by arizzi** [comment]
@slava77 the behaviour you want is obtained just raising the threshold for
usage in score from 2 to 3.
Il 15/apr/2015 04:49, "Slava Krutelyov" <notifications@github.com> ha
scritto:

**Comment by arizzi** [comment]
PS: the current state makes no sense as it throws away a random half of the
tracks.
If you want to remove them all just rais the threshold above OtherDz.
 Il 15/apr/2015 07:02, "Andrea Rizzi" <andrea.rizzi@cern.ch> ha scritto:

**Comment by arizzi** [comment]
@slava77 btw what is the point of testing on minbias? I would say that by definition on minbias the output of the PV choice should be more or less random (i.e. any PV is more or less equivalent).

**Comment by arizzi** [comment]
I updated the PR so that we get consistent on the conservative side (i.e. count only tracks assigned with criteria better than OtherDz )... I'll make few tests on several sample but we really have to fix it one way or the other... the intermediate solution where we randomly throw away tracks with a given ip sign and keep those with another makes no sense

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by arizzi** [comment]
the first couple of signal samples finished, the effect seems to be at level of ~0.1% typically showing an improvement (signal PV picked up more often)... more numbers when all samples are done

**Comment by slava77** [comment]
great.
I'm running the integration tests already.

**Comment by arizzi** [comment]
udpate: 
- variations are in the order 0.1-0.5% (to be compared with improvements wrt nominal PV of ~10%)
- the performance is slightly better on VBF samples and slightly worse on VHBB samples

my 2cents: let's take the PR as is and then optimize further the PV choices when many more samples will be available (anyhow the PF version of this kind of association is available in MiniAOD so that analyses groups can do studies and tuning and provide feedback for 75X or 76X)

**Comment by arizzi** [comment]
Here some more number testing also the original version of this PR (i.e. including "OtherDZ")

ZH->nunubb 
  no preselection
  82.5%(current PR) 83.0% (buggy) 83.3%(original version of this PR) vs 71% (old PV assignment)

  high pt preselection (analysis like)
  89.4% (current) 90.0% (buggy) 90.3% (original PR) vs 81% (old PV ranking)

VBF Hbb
  leading jet preselection (analysis like)
  95.8% (current)  95.7% (buggy) 95.6% (original PR)  vs 92.3 (old PV ranking)

so we can stay with current version because  it is considered safer and then fine tune in next released (for example using the unassigned category for stuff that would be "OtherDZ" but with unreasonably high I.P.)

**Comment by slava77** [comment]
there was an operator error on my end in running the tests, restarted to run correctly now

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/8722	17da848
tested additionally locally  in CMSSW_7_4_0 /test area sign537/

In the tests running, differences in monitored quantities are  most visible in min-bias-like events (several similar vertices): fairly rarely the leading vertex changes the downstream effects are then in PF neutrals (slight momentum change) and then more downstream plots.
There are no useful plots to attach here.

Looking at subleading vertices: the order changes more frequently.

I looked manually at larger changes in the score values (stored in value maps) and the ones with changes of more than a few units ("GeV**2") are from cases where there are tracks or clusters of tracks fairly far away (at least 5 cm away from the vertex that had this track counted in the vertex score earlier).
This was a low stat check of just 2 events (out of 100 running, among the cases with vertex order changes). Still, the behavior is as expected: skipping of OtherDz tracks in score computation just throws away unrelated tracks.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
