### PR TITLE
Optimise muon seed MVA classifier

### PR DESCRIPTION
**Pull request by Parsifal-2045**
#### PR description:

Implement light C++ optimisation for the muon MVA module responsible for selecting high-quality muon seeds in the pixel detector by matching them with L1 Tracker muons:
- Add early return in case either input collection is empty
- Swap std::sort with std::partial_sort

These changes improve the timing of the module by [about 30%](https://indico.cern.ch/event/1460055/contributions/6147459/attachments/2941712/5168585/2024_10_08_thesis_results.pdf#page=20) with no changes in the output. 

#### PR validation:

No changes in the output.

### CODE REVIEW

**Comment by mmusich** [comment]
test parameters:
   * enable = hlt_p2_integration, hlt_p2_timing

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
> HLT P2 Timing: [chart](https://cmssdt.cern.ch/circles/web/piechart.php?data_name=hlt-p2-timing&resource=time_thread&filter=CMSSW_15_0_X_2024-12-03-2300&dataset=CMSSW_15_0_X_2024-12-03-2300-cmssw46861/el8_amd64_gcc12/58/Phase2Timing_resources)

there is a 1ms reduction visible also in the PR tests for `hltIter2Phase2L3FromL1TkMuonPixelSeedsFiltered`:

| CMSSW_15_0_X_2024-12-03-2300 |  CMSSW_15_0_X_2024-12-03-2300 + this PR |
| ------------- | ------------- |
| Screenshot from 2024-12-04 12-33-31 | Screenshot from 2024-12-04 12-33-53 |

OTOH, I don't find this module in the right category where I would be expecting to find it (`Muons`), but rather in the "Unassigned" slice of the pie.

@smuzaffar is it possible to cherry-pick from Andrea's repository the latest changes in the category assignment (see [diff](https://github.com/cms-sw/circles/compare/master...fwyzard%3Acircles%3Amaster)) in the instance used by cmsbot?

**Comment by smuzaffar** [comment]
> @smuzaffar is it possible to cherry-pick from Andrea's repository the latest changes in the category assignment (see [diff](https://github.com/cms-sw/circles/compare/master...fwyzard%3Acircles%3Amaster)) in the instance used by cmsbot?

done @mmusich

**Comment by jfernan2** [comment]
+1

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
