### PR TITLE
Add missing L1 jet collection to event (Phase 2)

### PR DESCRIPTION
**Pull request by EmyrClement**
#### PR description:

Add missing seeded cone jet collection to event, which are produced using the "extended track" collection.

These are required as #40670 adds an `edm::ValueMap<float>` to the event and produces the corresponding reference objects, but the reference objects are not stored in the output.  Therefore these changes are nominally on top of #40670.

For completeness, we also add the intermediate inputs that are used to produce these new seeded cone jet collection i.e. the puppi candidates produced using the "extended tracks", as is done for the existing seeded cone jet collection (those produced using the regular tracks).

The corresponding PR to the L1T integration branch is [here](https://github.com/cms-l1t-offline/cmssw/pull/1090).

#### PR validation:

Ran standard cmsDriver command from runTheMatrix.  By itself, this PR doesn't change anything.  On top of #40670, I see the new objects are present in the output root file.

### CODE REVIEW

**Comment by epalencia** [comment]
Please test

**Comment by aloeliger** [comment]
Corresponds to https://github.com/cms-l1t-offline/cmssw/pull/1090

**Comment by aloeliger** [comment]
+l1

**Comment by perrotta** [comment]
@EmyrClement is there a reason why this (technically) simple addition to the L1Trigger_EventContent is made in a separate PR with respect to #41260, where the same event content is also updated? Since they refer to the same correlated additions, I would find natural that this is added as an additional commit to #41260, so that they can be tested and merged all at once. Please let me know if I am missing anything.

In any case, when addditional collections are added to an event content, is good habit to report in the corresponding PR the additional event size which is generated by them. Please do so either here or in #41260.

**Comment by aloeliger** [comment]
@perrotta The original owner of the correlator PR was having a difficult time getting the PR to work properly, and so asked for no more additions to it. Since the decision was made to make this PR separately, I have taken the correlator PR over. I have no objection to adding this PR onto it if this PR is too trivial.

**Comment by perrotta** [comment]
@aloeliger I see you are having hard times with the other PR :-)

These two must go together. Let say, mine is not a strict request, but I'm convinced it can be easier for you to include this simple commit in the other PR (whatever its number will be). As such you won't risk to have to rebase it once again if this one is merged; you can have a better control on the overall additional event content and its size (which should be reported in the PR descriptions at some time).

Overall, I think that it will be easier for you to include this commit in the other PR. But if you believe otherwise, please keep them separated. We will put this one on hold till the other one is merged, then, in order not to mess it up even further.

**Comment by perrotta** [comment]
hold
(It has to wait that the L1T phase2 correlator PR is merged first)

**Comment by aloeliger** [comment]
@EmyrClement Please open a PR to the new squashed branch containing the correlator PR info in #41279

**Comment by EmyrClement** [comment]
Closing, as now included in #41279 as discussed.

**Pull request closed without merging**
