### PR TITLE
[HGCAL trigger] Configurations fixes and updates

### PR DESCRIPTION
**Pull request by jbsauvan**
#### PR description:
- Configurations fixes and updates
- In particular to work with V16 geometry

Associated internal PRs and reviews:
- hgc-tpg#87
- hgc-tpg#89
- hgc-tpg#97

#### PR validation:
Tested D86, D92, D94 workflows
```
runTheMatrix.py -w upgrade -l 20034.0 --maxSteps=2 & # D86
runTheMatrix.py -w upgrade -l 22434.0 --maxSteps=2 & # D92
runTheMatrix.py -w upgrade -l 23234.0 --maxSteps=2 & # D94
```

### CODE REVIEW

**Comment by aloeliger** [comment]
please test

**Comment by aloeliger** [comment]
@pallabidas & @artlbv Just bringing this to your attention, pallabi because this is HF inputs to calo, and artur because that means it may be physics affecting.

**Comment by aloeliger** [comment]
+l1

**Comment by artlbv** [comment]
@jbsauvan does this actually change anything performance-wise in the HGCAL TPs? If yes, could you link to some slides etc showing this? merci!

**Comment by jbsauvan** [comment]
> @jbsauvan does this actually change anything performance-wise in the HGCAL TPs? If yes, could you link to some slides etc showing this? merci!

Hi @artlbv 
It has some impact on the TPs energy in V16+ eras, coming from a fix in the layer weights used to calibrate trigger cell energies.
The level of the impact can be seen in this comment [here](https://github.com/hgc-tpg/cmssw/pull/89#issuecomment-1865995995)

**Comment by artlbv** [comment]
hi, I wonder why this PR did not make it into 140?

also, out of curiosity, @jbsauvan you mention
> In particular to work with V16 geometry

Does it mean there are some issues with older or newer geometries?

@epalencia noted some anticipated geometry cleanup and move to D98/99: https://indico.cern.ch/event/1377836/#84-phase-2-geometry-baseline-s

**Comment by srimanob** [comment]
Hi @jbsauvan 

Could you please elaborate more on this PR on geometry dependency? The current baseline version is HGCal V17 (in D98). And for production, we are planning to use V19 (as in D99).

If need also in 14_0, please backport. Sorry for delay.

**Comment by srimanob** [comment]
@cmsbuild please test

Just to refresh the test after 3 weeks, and test also in new HGCal geometry version

**Comment by jbsauvan** [comment]
Hi @artlbv @srimanob 
Before this PR, the numbers of CE-E and CE-H layers used in the configuration for the TPG were those pre-V16 (i.e. 28 CE-E layers) even for post-V16 geometries. 
These numbers of layers impact the definition of the trigger layers (only alternate layers in CE-E and all layers in CE-H) as well as the extraction of the calibration coefficients layer-by-layer.

Now era modifiers have been added to change this for post-V16 geometries, using the correct numbers.

So before this PR the trigger layers definition and layer calibration were incorrect for geometries >=V16. Which is fixed here.

**Comment by srimanob** [comment]
Hi @jbsauvan 

The fresh test comes out. Changes have been seen in L1T of all Phase-2 workflows. So I assume it is expected from your comment, https://github.com/cms-sw/cmssw/pull/43706#issuecomment-1929899266

**Comment by srimanob** [comment]
+Upgrade

Changes are seen in all L1T DQM of all Phase-2 workflows. This should be expected from the update of the config.

**Comment by antoniovilela** [comment]
@jbsauvan
It seems we could squash most or all commits in this PR?
Thanks.

**Comment by jbsauvan** [comment]
@antoniovilela 
I squashed the commits that can be squashed

**Comment by antoniovilela** [comment]
> @antoniovilela I squashed the commits that can be squashed

Thanks.

**Comment by antoniovilela** [comment]
@smuzaffar 
Hi Shahzad,
Should the L2 signatures have been reset in this case?
Thanks.

**Comment by smuzaffar** [comment]
@antoniovilela , no ideally bot should not have reset the signatures but looks like it was rebase + squash  so that is why bot had reset the sign. `rebase` changes the parent e.g. previously https://github.com/cms-sw/cmssw/commits/19e40529a474eb3f839582d6d1b38ab176849ca1/ was the history of this PR ( i.e parent was f5cbbf1ab5806ffc54ccaab6a77201f35d63fca7 ) and now https://github.com/cms-sw/cmssw/commits/d87e63341a18735ecb4a5830aa23939b8bb588e4/ is based on 93f14ae8b3fa6fb1cf1a14c73f651f6b01d17340. In such case bot will see differences and will reset all the signs.

**Comment by jbsauvan** [comment]
I indeed did a rebase on `14_1_X` (from `14_0_X`) before squashing.

**Comment by antoniovilela** [comment]
> @antoniovilela , no ideally bot should not have reset the signatures but looks like it was rebase + squash so that is why bot had reset the sign. `rebase` changes the parent e.g. previously https://github.com/cms-sw/cmssw/commits/19e40529a474eb3f839582d6d1b38ab176849ca1/ was the history of this PR ( i.e parent was [f5cbbf1](https://github.com/cms-sw/cmssw/commit/f5cbbf1ab5806ffc54ccaab6a77201f35d63fca7) ) and now https://github.com/cms-sw/cmssw/commits/d87e63341a18735ecb4a5830aa23939b8bb588e4/ is based on [93f14ae](https://github.com/cms-sw/cmssw/commit/93f14ae8b3fa6fb1cf1a14c73f651f6b01d17340). In such case bot will see differences and will reset all the signs.

Ok, many thanks for checking.

**Comment by antoniovilela** [comment]
> I indeed did a rebase on `14_1_X` (from `14_0_X`) before squashing.

Ok, let's ger the L2 signatures again and then merge.
@cms-sw/l1-l2 @cms-sw/upgrade-l2

**Comment by smuzaffar** [comment]
@antoniovilela , @iarspider and I believe bot should not have reset sign in this case. Even though PR was rebased but there were no changes difference between original PR and squashed PR. I order to test why bot resetted signs I am manually editing https://github.com/cms-sw/cmssw/pull/43706#issuecomment-1889267925 to see what bot did

**Comment by antoniovilela** [comment]
> @antoniovilela , @iarspider and I believe bot should not have reset sign in this case. Even though PR was rebased but there were no changes difference between original PR and squashed PR. I order to test why bot resetted signs I am manually editing [#43706 (comment)](https://github.com/cms-sw/cmssw/pull/43706#issuecomment-1889267925) to see what bot did

Ok, many thanks.

**Comment by antoniovilela** [comment]
> @antoniovilela , there was a bug and bot was not proerly reading the previously cached information. This is fixed now and bot has properly kept the signatures

Great, thanks!

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
