### PR TITLE
updated online DQM config for PbPb collision

### PR DESCRIPTION
**Pull request by sushilchauhan**
online DQM client config for BeamSpot is update for PbPb HI collision. This PR also include changes in PR # 12084 (for 74X).

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
please submit the same for 76 and 80 as well.
thanks,
F.

**Comment by deguio** [comment]
+1

**Comment by deguio** [comment]
@sushilchauhan 
please don't forget to have this ported to 76 and 80. otherwise the changes will be lost.

**Comment by davidlange6** [comment]
+1

**Comment by deguio** [comment]
@sushilchauhan 
please submit to 76 and 80 as well. can you confirm that you will take care of this?
thanks,
F.

**Comment by sushilchauhan** [comment]
Yes I will do that. I need to test in 76 and 80.

Thanks, sushli

**Comment by deguio** [comment]
ciao @sushilchauhan 
what is stopping you from porting this one as it is to 76 and 80?
special tests are needed?
sorry for insisting. just don't want to loose this dev for future branches and future HI running.
thanks,
F.

**Pull request merged**
