### PR TITLE
Muon alignment alcareco producers for run2 v2

### PR DESCRIPTION
**Pull request by pakhotin**
This is NEW pull request following previous made by Anthony:
https://github.com/cms-sw/cmssw/pull/8310

New pull request includes several changes to the ALCARECO Producers used by during MuonAlignment:
- changed thresholds pT and eta for muons and general tracks (!)
- added several new collections to the output files (tracks, vertexes, etc.)
- changed some of the detector DCS status flags
- fixed a bug that existed in the Overlaps stream during Run-1

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
@cmsbuild please acknowledge changes

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
@pakhotin the failure in the relval test is due to the fact there is no `generalTracks` collection in the cosmics and beam halo reconstruction. I think we have two ways out, either you create a separate path that is run on cosmics only reco, or we modify the relval matrix to avoid running the `pathALCARECOMuAlCalIsolatedMuGeneralTracks` on the cosmics and beam halo samples (we will need to remember that when running the paths in production mode through the AlCaMatric). Please provide a fix in order for us to continue reviewing your PR. 
Best
M.

**Comment by pakhotin** [comment]
Hi Marco,
I don't understand your first proposed option "create a separate path that is run on cosmics only reco", but the second option is what I think. The path pathALCARECOMuAlCalIsolatedMuGeneralTracks is not supposed to be ran over cosmics or beam halo. Please advise!
Best,
Yuriy

**Comment by mmusich** [comment]
Hi @pakhotin, 
since you have added [here](https://github.com/cms-sw/cmssw/pull/9482/files#diff-d7b81b20c730f361eff46bfb2bc478c9R403) the path `pathALCARECOMuAlCalIsolatedMuGeneralTracks` to the `ALCARECOStreamMuAlCalIsolatedMu` stream, that path will be exercised everywere in the relval matrix where it is called through: `ALCA:MuAlCalIsolatedMu`. If you check in `https://github.com/cms-sw/cmssw/blob/CMSSW_7_5_X/Configuration/PyReleaseValidation/python/relval_steps.py` [link](https://github.com/cms-sw/cmssw/blob/CMSSW_7_5_X/Configuration/PyReleaseValidation/python/relval_steps.py), this has 3 occurrencies:
   - steps['RECOCOSD']
   - steps['RECOCOS']
   - steps['RECOHAL']
all those three refer either to cosmics or beam halo samples.
Instead it looks like you want to have it run over some collision sample where the `generalTracks` reco product is available, for example in `step4Defaults` and `step4Up2015Defaults` where the tracker alignment cousin of your path is run. This calls to change the matrix of course. 
At that point I don't know if you still want instead to run the other path: `pathALCARECOMuAlCalIsolatedMu` over the cosmics samples. But for doing that you will need to add a separate `FilteredStream` that doesn't run the one for the `generalTracks`.
@diguida @franzoni this goes in line with our rejuvination plan, do you agree?

**Comment by mmusich** [comment]
@pakhotin now the PR doesn't merge anymore. Can you please rebase it?

**Comment by pakhotin** [comment]
@mmusich, @diguida would you please check if it merges now? I did rebase as suggested and checked that modified file relval_steps.py has all upstream changes from main CMSSW_7_5_X branch.

**Comment by pakhotin** [comment]
@mmusich, @diguida any news on the pull request? I believe I fixed merge conflict, please confirm or let me know if I need to do anything else. Thanks!

**Comment by mmusich** [comment]
@pakhotin still doesn't merge. Moreover the last commit looks suspicious. Have you rebased onto the last IB? It would be also useful to squash the commits for readability

**Comment by franzoni** [comment]
-1
The changes to Configuration/PyReleaseValidation/python/relval_steps.py must have been accidental and should not happen. Can you please rebase ?

**Comment by mmusich** [comment]
@pakhotin since the PR was not merging and is pdmv-rejected I opened a new one here #9957. Can you please cross-check that it's what you wish? I picked-up your commits, squashed them and fixed merge conflicts. There was still an issue with the fact that `MuAlGlobalCosmics` was run on `generalTracks` which are not available in Cosmic reco. 
Best,
M.

**Comment by mmusich** [comment]
-1 superseded by #9482

**Pull request closed without merging**
