### PR TITLE
Adapt python code to updated ML software

### PR DESCRIPTION
**Pull request by riga**
#### PR description

This PR adds some minimal changes to ML related python code in `PhysicsTools/PythonAnalyses` and `PhysicsTools/TensorFlow` that came up in the integration process of updated python packages in https://github.com/cms-sw/cmsdist/pull/6649 which was merged yesterday.

Changes:
- One [unit test](https://github.com/cms-sw/cmsdist/pull/6649#issuecomment-780067874) in `PhysicsTools/PythonAnalyses` used an import that was working for Python2 but not for Python3. This is now fixed for both versions.
- The `cmsml` package was introduced in the linked PR and deprecates a few tools previously located in `PhysicsTools/TensorFlow/python/tools.py`. As far as I see, these tools were only used in the `PhysicsTools/TensorFlow` tests, which I updated accordingly.

#### PR validation

The unit tests of both packages are passing now.

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by jpata** [comment]
+reconstruction
- removes some testing code which now lives in an external package
- nothing is changed for the reco tests as expected

**Comment by silviodonato** [comment]
merge

**Comment by santocch** [comment]
+1

**Pull request merged**
