### PR TITLE
Update SiPixel bad components in Run 3 MC GTs

### PR DESCRIPTION
**Pull request by saumyaphor4252**
#### PR description:

This PR updates the SiPixel bad component tags in the Run 3 realistic MC GTs, requested in https://cms-talk.web.cern.ch/t/mc-gt-updating-sipixel-bad-components-for-2023-2024/17736.
The tags updated are:

- `SiPixelQuality_phase1_2023_v4_mc`
For 2023 realistic GT
- `SiPixelQuality_forDigitizer_phase1_2023_v4_mc`  with label `forDigitizer`
For 2023 realistic GT
- `SiPixelQuality_phase1_2024_v4_mc`
For 2024 realistic GT
- `SiPixelQuality_forDigitizer_phase1_2024_v4_mc` with label `forDigitizer`
For 2024 realistic GT

The new GTs and their diff wrt to the last GTs in autoCond are here:
**2023 realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/130X_mcRun3_2023_realistic_v1/125X_mcRun3_2023_realistic_v5
**2024 realistic**
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/130X_mcRun3_2024_realistic_v1/125X_mcRun3_2024_realistic_v5

#### PR validation:
```
test parameters:
  - workflows = 12434.0,12834.0
```
#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Not a backport and No backport needed.

### CODE REVIEW

**Comment by tvami** [comment]
test parameters:
  - workflows = 12034.0,11634.0,7.23,159.0,12434.0,12834.0

**Comment by tvami** [comment]
@cmsbuild , please test

**Comment by tvami** [comment]
+alca
  * tests pass, small changes all over the place in 2023 and 2024 wfs, expected due to the change of conditions

**Comment by perrotta** [comment]
+1

**Pull request merged**
