### PR TITLE
Fix D97 unit test and clean up Phase2 XMLs

### PR DESCRIPTION
**Pull request by srimanob**
#### PR description:
This technical PR is to fix the unit test failure after D97 is added, and clean up all Phase-2 XML files as suggested in https://github.com/cms-sw/cmssw/pull/39841

#### PR validation:
None.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:
No need to backport. Clean up is only technical.

### CODE REVIEW

**Comment by srimanob** [comment]
@cmsbuild please test

**Comment by srimanob** [comment]
type bug-fix

**Comment by srimanob** [comment]
+Upgrade

Technical PR as described in the PR description.

**Comment by civanch** [comment]
+1

it seems to be a correct update.

**Comment by rappoccio** [comment]
+1

technical cleanup

**Pull request merged**
