### PR TITLE
Add frontier security option, and cleanup Standard Sequences

### PR DESCRIPTION
**Pull request by diguida**
This PR adds the possibility to configure Frontier connection in order to request the server sends digital signatures on every response. This is done by setting a `string` data member in `ConnectionPool` or the corresponding parameter in a `ParameterSet`. An unit test has been added. The default is `""`, so the current behaviour is kept.
In `Configuration/StandardSequences/python/FrontierConditions_GlobalTag_cfi.py` I cleaned up the old `ParameterSet` pointing to the CondDBv1 implementation, and replaced it with the CondDBv2 values.
No regression expected.

### CODE REVIEW

**Comment by diguida** [comment]
@DrDaveD @bbockelm this is something you might want to watch as well.

**Comment by diguida** [comment]
please test

**Comment by diguida** [comment]
For the reviewers: use the w=1 option to look at file differences:
https://github.com/cms-sw/cmssw/pull/12941/files?w=1

**Comment by ggovi** [comment]
+1

**Comment by ggovi** [comment]
@davidlange6 
Hi David, can we have this one merged in one of the next IBs? It is required to properly merge our next PR ( a big one ), devoted to the conddb v1 code clan up.

**Comment by diguida** [comment]
superseded by #12960

**Pull request closed without merging**
