### PR TITLE
[Pixel 3D Digitizer] Fix wrong channel assignation

### PR DESCRIPTION
**Pull request by duartej**
#### PR description:

Fix bug in channel assignation, by using `PixelDigi::pixelToChannel` function instead of `PixelTopology::channel`. 
- Brief description of the problem and the fix: https://indico.cern.ch/event/879045/contributions/3914362/attachments/2060899/3465619/20200622_digiChannelBug.pdf

@emiglior and @skinnari as conveners of the upgrade simulation group are aware and agree. 
cc: @suchandradutta 

#### PR validation:

This PR is affecting the Phase 2 upgrade 3D geometry only, checked with workflows 26234.0 and 24834.0 succesfully. 

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Not a backport

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild please test

**Comment by mmusich** [comment]
@duartej 
I had a look to your attached presentation, the lines which you claim are giving inconsistent results for the phase1 digitizer are actually protected by a conditional inclusions
https://github.com/cms-sw/cmssw/blob/518b6ef93fde1b3778e58e785a495237c6d33304/SimTracker/SiPixelDigitizer/plugins/SiPixelDigitizerAlgorithm.cc#L1515-L1523

in any case in the phase1 case the class `PixelTopology` is used, while here you are using `Phase2TrackerTopology`

**Comment by duartej** [comment]
> @duartej
> I had a look to your attached presentation, the lines which you claim are giving inconsistent results for the phase1 digitizer are actually protected by a conditional inclusions
> https://github.com/cms-sw/cmssw/blob/518b6ef93fde1b3778e58e785a495237c6d33304/SimTracker/SiPixelDigitizer/plugins/SiPixelDigitizerAlgorithm.cc#L1515-L1523
> 
> in any case in the phase1 case the class `PixelTopology` is used, while here you are using `Phase2TrackerTopology`

ahh, yes, you are right. I can see it is using the pixelToChannel function there as well. 

However, regarding the `Phase2TrackerTopology`, it is actually `PixelTopology` (see https://github.com/cms-sw/cmssw/blob/master/SimTracker/SiPhase2Digitizer/plugins/Phase2TrackerDigitizerFwd.h#L12, which is included in https://github.com/cms-sw/cmssw/blob/master/SimTracker/SiPhase2Digitizer/plugins/Phase2TrackerDigitizerAlgorithm.h#L17).

**Comment by civanch** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade

**Comment by silviodonato** [comment]
+1

**Pull request merged**
