### PR TITLE
L1T2016 is completely transported to L1T

### PR DESCRIPTION
**Pull request by EsmaeelEskandari**

### CODE REVIEW

**Comment by dmitrijus** [comment]
+1

**Comment by threus** [comment]
@EsmaeelEskandari @thomreis is there a 90X back port of this PR?

**Comment by thomreis** [comment]
@EsmaeelEskandari please confirm that this is also included in #18043 . The commit messages differ.

**Comment by EsmaeelEskandari** [comment]
@thomreis : This PR includes just the last commit of #18403
https://github.com/cms-sw/cmssw/pull/18043/commits/06f78689fe01443fbc162d0ef787456cfda0670a
 not all of its commits.

**Comment by thomreis** [comment]
@EsmaeelEskandari OK, so this together with #17818 and #18352 gives us the complete set that is also in 91x already.

**Comment by threus** [comment]
@EsmaeelEskandari @thomreis thanks for the info. Do I understand correctly, that the remaining commit of this PR: https://github.com/cms-sw/cmssw/pull/18352/commits/9bd7a42f404314a2e0ffa9497cac3a345a2fe666 is not back ported to 90X yet? If so, could you please back port it if you need it? The point is, we merged (by our mistake) this PR in the online DQM, which is running on 90X, not 91X, so we need a 90X back port. Thanks and sorry for the inconvenience.

**Comment by EsmaeelEskandari** [comment]
@threus  @thomreis : Sorry, I am a little bit confused. I don't understand when PR #18352 is merged now what is the difference between its commits, one of them is back ported and one of them is not!
I should clarify that I made three PRs: #17818 #18043 and #18352. PRs #17818 and #18352 are merged with 91X. We just need #18043 to be merged. 
Also PRs #18043 and #18352 have one common commit https://github.com/cms-sw/cmssw/pull/18043/commits/06f78689fe01443fbc162d0ef787456cfda0670a.
Is it possible PR  #18043  to be mereged now or I should drop the common commit?

**Comment by threus** [comment]
@EsmaeelEskandari, don't worry, please keep everything as it is now :) sorry, maybe I was not clear. 
I only wanted to know if this PR is fully back ported to 90X, because we (DQM) will have to drop this PR from online DQM, which is running CMSSW_9_0_2 and I was looking for the 90X version of this PR.
Maybe easiest is to call me on Skype if you want (tomas.hreus)..

**Comment by thomreis** [comment]
@EsmaeelEskandari I think there is indeed no backport for this commit https://github.com/cms-sw/cmssw/pull/18352/commits/9bd7a42f404314a2e0ffa9497cac3a345a2fe666

#18043 does not contain the changes made in that commit.

**Comment by EsmaeelEskandari** [comment]
@threus : So please let me know about any problem in merging #18043?

**Comment by thomreis** [comment]
@EsmaeelEskandari if the accidentally merged (at P5) PR #18352 is removed from the online DQM system and only #18043 is merged the L1T2016 directory will reappear again since the commit https://github.com/cms-sw/cmssw/pull/18352/commits/9bd7a42f404314a2e0ffa9497cac3a345a2fe666 is not included in #18043 

Therefore we need an additional PR to 90x with only the commit https://github.com/cms-sw/cmssw/pull/18352/commits/9bd7a42f404314a2e0ffa9497cac3a345a2fe666

**Comment by threus** [comment]
@thomreis exactly.
@EsmaeelEskandari you can see the result without this PR in the playback GUI: https://cmsweb.cern.ch/dqm/online-playback

**Comment by thomreis** [comment]
The missing commit is in https://github.com/cms-sw/cmssw/pull/18474 that I just made.

**Comment by threus** [comment]
great, thanks!

**Comment by EsmaeelEskandari** [comment]
@thomreis : Thanks for your help. 
@threus : Thank you too. I am seeing https://cmsweb.cern.ch/dqm/online-playback, as Thomas said the L1T2016 is re-appeared which by deploying PR #18474, this issue will be solved and everything will be fine.

**Pull request merged**
