### PR TITLE
Fix warnings for gcc9 in DQMServices/Core

### PR DESCRIPTION
**Pull request by mrodozov**
#### PR description:

Fixes warnings in gcc9 IB

#### PR validation:
Builds without warnings

### CODE REVIEW

**Comment by mrodozov** [comment]
please test

**Comment by mrodozov** [comment]
please test

**Comment by VinInn** [comment]
The new code is producing results different than the previous.
One of the two is NOT what was intended by the original coder

**Comment by mrodozov** [comment]
Well I guess this code should be moved out of switch statement then

**Comment by makortel** [comment]
> Well I guess this code should be moved out of switch statement then

The warning can be also silenced with the `[[fallthrough]]` since the fallthrough is intended. (I think I've seen @Dr15Jones to use that to silence similar gcc9 warnings)

**Comment by mrodozov** [comment]
> The warning can be also silenced with the `[[fallthrough]]` since the fallthrough is intended. (I think I've seen @Dr15Jones to use that to silence similar gcc9 warnings)

I'm reading on how to do this when the fallthrough is indeed on purpose. I'll change the PRs accordingly

**Comment by mrodozov** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Pull request merged**
