### PR TITLE
Changes to handle userhooks and not create clashing copies

### PR DESCRIPTION
**Pull request by smrenna**
#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by agrohsje** [comment]
thanks @smrenna . working well.

**Comment by agrohsje** [comment]
please test

**Comment by agrohsje** [comment]
@smrenna should we move forward?

**Comment by agrohsje** [comment]
bb4l as well as resonance filter are also ok.

**Comment by agrohsje** [comment]
+generators

**Comment by qliphy** [comment]
+1

**Pull request merged**
