### PR TITLE
Phase2-gex64 Make a scenario with V14 version of HGCal and HFNose

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Make a scenario with V14 version of HGCal, T21 version of Tracker, M9 version of Muons, I13 version of MTD and HFNose

#### PR validation:

Use the runTheMatrix test workflow 37034.0

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
+1

**Comment by chayanit** [comment]
+1

**Comment by srimanob** [comment]
@mariadalfonso @bsunanda @chayanit 
If basically, the central detector is the same between D76 and the new D82, except for the addition of HFNose, would it be better to move relvals to D82 instead? As central is the same, it should have no effect on the validation result so far.

**Comment by srimanob** [comment]
+Upgrade

**Comment by srimanob** [comment]
Please test with 37034.0

**Comment by srimanob** [comment]
please test workflow 37034.0

**Comment by srimanob** [comment]
please abort

**Comment by srimanob** [comment]
@silviodonato @qliphy 
I accidentally sign this PR. However, I would like to test with new workflow first. The fist test trigger does not include new geometry test. And I also have the comment for this PR.

**Comment by silviodonato** [comment]
> @silviodonato @qliphy
> I accidentally sign this PR. However, I would like to test with new workflow first. The fist test trigger does not include new geometry test. And I also have the comment for this PR.

I deleted your comment, and it seems to work

**Comment by srimanob** [comment]
@bsunanda 
If this will replace the old HFNose D60, should it be replaced also in the short matrix?
https://github.com/cms-sw/cmssw/blob/master/Configuration/PyReleaseValidation/scripts/runTheMatrix.py#L91

**Comment by srimanob** [comment]
please test workflow 37034.0

**Comment by srimanob** [comment]
+Upgrade

The new D82 workflow runs fine. We can make another PR if we would like to change the short matrix to this one, instead of D60.

**Comment by silviodonato** [comment]
+1

**Pull request merged**
