### PR TITLE
Fix memory leak in DQMGenericClient

### PR DESCRIPTION
**Pull request by dmitrijus**
Fixes https://its.cern.ch/jira/browse/CMSCOMPPR-1606

backport of https://github.com/cms-sw/cmssw/pull/21181

### CODE REVIEW

**Comment by dmitrijus** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
merge

**Comment by mtosi** [comment]
I've just seen this PR,
do we have the analogous one for 92x ?
as far as I understood, we have a similar issue in recent relval production done in 9_2_14
@fabozzi do you confirm ?

**Comment by fabozzi** [comment]
yes, and it is already been merged as well

**Comment by fabozzi** [comment]
https://github.com/cms-sw/cmssw/pull/21199

**Comment by mtosi** [comment]
thanks ! (I did not see it)

**Pull request merged**
