### PR TITLE
Changed CorrPCCProducer from EDProducer to DQMEDAnalyzer for LumiPOG

### PR DESCRIPTION
**Pull request by samhiggie**
We've changed the CorrPCCProducer from an EDProducer to a DQMEDAnalyzer so that we can extract histograms for systematics.

### CODE REVIEW

**Comment by arunhep** [comment]
please test

**Comment by arunhep** [comment]
@samhiggie can you also make a backport to 10.1.X ? We will then add that to the list of things needed for 10.1.1 release

**Comment by samhiggie** [comment]
@arunhep  Yes, I can start the backport. I should mention, that I started this PR with 10.1.0.pre3, so it should be quick.  Thanks.

**Comment by arunhep** [comment]
@fabiocos this looks strange to me. i see the tests passed and comparisons available but it says RelVals Error as well.

**Comment by fabiocos** [comment]
@arunhep sorry, where do you see relval errors? I see everything clean, what am I missing?

**Comment by samhiggie** [comment]
Does anyone have good documentation on how to test the DQM analyzer? It would be very beneficial if I could have a simple configuration file detailing how to organize the output etc... 
While I'm at it, there are new type_2 parameters that we would like to incorporate. I have these configurable with the file I am using to generate the DQM output. We would like these new ones at PCL as well. Should I do that all here or try to request a PR to @cerminar ?

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
@arunhep @lpernie this PR looked urgent one week ago but now it is apparently waiting. 
@samhiggie Did you manage to perform the tests you were mentioning?

**Comment by arunhep** [comment]
+1

**Comment by arunhep** [comment]
@samhiggie as @fabiocos asked. it would be good to see the outcome of tests you may have carried out with this DQM module. I dont think github is the place to ask for help. You should contact cms-dqm-coreTeam@cern.ch

**Comment by fabiocos** [comment]
please test workflow 1020.0

**Comment by fabiocos** [comment]
@samhiggie @arunhep FYI, running standalone wf 1020 I see that the new ME are produced. But I would like to understand whether more checks were done by the author or what are the plans for further developments, as discussed in a previous comment

**Comment by fabiocos** [comment]
@samhiggie sorry, do you have already a list of files to be used for test?

**Comment by fabiocos** [comment]
@samhiggie in cmdLog you have as a first step

dasgoclient --limit 0 --query 'file dataset=/AlCaLumiPixels1/Run2016H-v1/RAW run=283383 site=T2_CH_CERN'

you may set your favourite file here...

**Comment by samhiggie** [comment]
@fabiocos Thank you, I've tried this and to implement this method I need a good RAW file. There are none for 2017, and it has taken a while to find a run from 2016 that works - I'll try to find a run that has pixel clusters in the meantime. Perhaps I have bad luck, but most runs that had the RAW AlCaLumiPixels data that I find in wbm for 2016 are special runs like mu-scans, they don't have the pixel clusters I need to make the comparison. Where as in 2017 we have all the AlCaPCC we want. It would be nice to know how to set the input data to AlCaPCC for the cmdLog or figure out how to run with AlCaPCC as input locally vis cmsRun.

**Comment by fabiocos** [comment]
@samhiggie I assume you should just run the harvesting step on that file, right? @cerminar can in case confirm. It would be good to converge and integrate this PR, if you confirm it

**Comment by cerminar** [comment]
@samhiggie I still don't understand what the exact problem is, sorry for being slow.
 
- Do you have a good run? 
- Can you access the corresponding RAW files?
Actually can't you use the RAW used in the latest T0 replay for the test?
- Once you have the file list from DAS you can edit by hand the configuration files produced by runTheMatrix.py -l 1020 (most likely only the step2 file) chaning the input files and the maxEvents parameter and run.

If you have a specific failure we can look at it, just post the details.

Does this answer your questions about the procedure?

**Comment by samhiggie** [comment]
Commits have been added. Thank you @cerminar and @fabiocos for the help. The issue was finding the right Run with enough LSs that we could test the lumiblock merge and mapping. I found a way to test this locally. It was failing to fetch a file before we had enough LS, thus I was delayed. Sorry for the headache and thanks for following up.

**Comment by capalmer85** [comment]
@cerminar are these the commits you were thinking about?

**Comment by capalmer85** [comment]
Can someone please "please check"?

**Comment by arunhep** [comment]
please test

**Comment by kpedro88** [comment]
+1

**Comment by fabozzi** [comment]
+1

**Comment by kpedro88** [comment]
backport of #22868

**Pull request merged**
