### PR TITLE
b-tag-calib-8_0_X

### PR DESCRIPTION
**Pull request by HeinerTholen**
This is the back-port of #14148 to CMSSW_8_0_X. 

We think this is needed, as people are going to use 8_0_X releases in analysis for some time from now.

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
+1 
backport of https://github.com/cms-sw/cmssw/pull/14148 already approved

**Comment by ggovi** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
