### PR TITLE
Added a small producer that selects L1's that did not result on a L2 (back port of #18414)

### PR DESCRIPTION
**Pull request by folguera**
Backport of #18414 so it can be used in ConfDB.

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by folguera** [comment]
@davidlange6 @Martin-Grunewald, @smuzaffar   do we have an estimate on when this would be merged, we do need this to be inside CMSSW to be ported to ConfDB and finish the Muon HLT template for 2017

**Comment by Martin-Grunewald** [comment]
It has been requested several times. The equivalent PR is already in 91X and will thus be in 910pre3.
We'll move HLT development to that pre-release anyway. In the meantime you could work offline with
a python file so that things are ready to go.

**Comment by folguera** [comment]
This is what I've been doing, and I believe things are ready to go but I cannot import them to ConfDB until this is merged.

**Comment by davidlange6** [comment]
+1

"several times"would appear to be once on Tuesday...(which was the first opportunity after the 91x version got merged)

**Pull request merged**
