### PR TITLE
Prepare for table set 160812; general cleanup

### PR DESCRIPTION
**Pull request by namapane**
As #19454, but for 93X as requested.
No change in default behavior.
This PR includes:
-new MF geometry XML files;
-remove old XML files;
-cleanup obsolete download.url files;
-update tools for table conversion and for generation of .db payloads for MF geometry and configuration;
-update validation, field visualization and regression tools;
-allow for the larger boundary of map version 160812.

For information about maps, cf. https://indico.cern.ch/event/642366/contributions/2606389/ .

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by slava77** [comment]
@namapane 
please clarify if the new set 160812 is exercised already in this PR unit tests
(else, I probably need to run an integration level test to see sensible outputs [no crash and similar])

**Comment by slava77** [comment]
please remove  MagneticField/Interpolation/data/.gitignore

**Comment by namapane** [comment]
No - as actually explained in the PR comment, this commit changes nothing in the actual default behavior. Switch to new maps goes through new tags published in GTs, which I am ready to push for, but cannot happen before the PR is integrated.

Regarding .gitignore do you mind keeping it? I adeed it to keep the data directory existing in git since this is where I have to put tables before they get into a release.

**Comment by slava77** [comment]
On 6/30/17 9:57 AM, Nicola Amapane wrote:
> No - as actually explained in the PR comment, this commit changes
> nothing in the actual default behavior. Switch to new maps goes through
> new tags published in GTs, which I am ready to push for, but cannot
> happen before the PR is integrated.

My question had a different scope (but seems irrelevant after checking):
there are quite a few unit-test looking files in MagneticField/ subsystem
which I thought were actually active unit tests to exercise
e.g. loading the field from XML etc.
It looks like none of these are actual unit tests.


> 
> Regarding .gitignore do you mind keeping it? I adeed it to keep the data
> directory existing in git since this is where I have to put tables
> before they get into a release.

For tests like this,
instead of copying files to $CMSSW_BASE/src/Subsystem/Package/data
you can put the data files in
$CMSSW_BASE/external/$SCRAM_ARCH/data/Subsystem/Package/data

IMO, this is the right way to test the data external files.

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/19469	9eb089a
- configuration setup, including MF geometry xml files and also mostly test updates, to advance to a new version of the magnetic field
- jenkins tests pass (the new field setup is not exercised)

**Comment by slava77** [comment]
@franzoni @arunhep 
this PR needs AlCa signature
please check and comment or sign.
Thank you.

**Comment by franzoni** [comment]
+1
@slava77 
we've today come to an understanding w/ @namapane

**Comment by slava77** [comment]
@davidlange6

please proceed with checkout of this
so that we can advance with the needed GT updates soon.

Thank you.

**Comment by davidlange6** [comment]
+1

**Comment by smuzaffar** [comment]
@namapane , looks like this broke few addOn tests 
https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc6_amd64_gcc530/CMSSW_9_3_X_2017-07-09-2300/addOnTests/logs/cmsDriver-hlt_mc_GRun_cmsDriver.py_TTbar_Tauola_13TeV_TuneCUETP8M1_cfi_-s_GEN,SIM,DIGI,L1,DIGI2RAW_--mc_--scenario=pp_-n_10_--conditions_auto:run2_mc_GRun_--relval_9000,50_.log

```
----- Begin Fatal Exception 10-Jul-2017 04:33:33 CEST-----------------------
An exception of category 'FileInPathError' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing ESSource: class=XMLIdealGeometryESSource label='magfield'
Exception Message:
edm::FileInPath unable to find file MagneticField/GeomBuilder/data/MagneticFieldVolumes_1_v7_large.xml anywhere in the search path.
The search path is defined by: CMSSW_SEARCH_PATH
${CMSSW_SEARCH_PATH} is: /tmp/cmsbuild/workspace/ib-run-addons/CMSSW_9_3_X_2017-07-09-2300/src:/tmp/cmsbuild/workspace/ib-run-addons/CMSSW_9_3_X_2017-07-09-2300/external/slc6_amd64_gcc530/data:/cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc530/cms/cmssw-patch/CMSSW_9_3_X_2017-07-09-2300/src:/cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc530/cms/cmssw-patch/CMSSW_9_3_X_2017-07-09-2300/external/slc6_amd64_gcc530/data
Current directory is: /tmp/cmsbuild/workspace/ib-run-addons/CMSSW_9_3_X_2017-07-09-2300/addOnTests/hlt_mc_GRun
----- End Fatal Exception -------------------------------------------------
```

**Comment by namapane** [comment]
Well it looks like cmsDriver is picking the wrong magnetic field map 
configuration. The right one should not access the xml files but read 
them from db. Besides that, this xml is used for Run 1 maps only or maps 
for B!=3.8T, which suggests that possibly even the wrong config is used.

I could not track where cmsDriver adds the MF .py from a quick look, if 
you know please let me know, otherwise I will debug later today.

Cheer,s
	Nicola

**Comment by smuzaffar** [comment]
It is failing for addOn tests. cms glimpse shows that it is ref from
```
>cmsglimpse MagneticFieldVolumes_1_v7_large
src/MagneticField/Engine/python/volumeBasedMagneticField_120812_cfi.py:         'MagneticField/GeomBuilder/data/MagneticFieldVolumes_1_v7_large.xml',
src/MagneticField/Engine/python/volumeBasedMagneticField_120812_largeYE4_cfi.py:         'MagneticField/GeomBuilder/data/MagneticFieldVolumes_1_v7_large.xml',
src/MagneticField/GeomBuilder/test/Visualization/displayMFGeom_cfg.py: #         'MagneticField/GeomBuilder/data/MagneticFieldVolumes_1_v7_large.xml',
src/MagneticField/GeomBuilder/test/mfxmlwriter.py:         'MagneticField/GeomBuilder/data/MagneticFieldVolumes_1_v7_large.xml',
```
running ```addOnTests.py -t fastsim1``` shows that it was loaded via MagneticField/Engine/python/volumeBasedMagneticField_120812_largeYE4_cfi.py
@ianna might have any details about it.

**Comment by namapane** [comment]
On 10-Jul-17 10:27, Malik Shahzad Muzaffar wrote:
> It is failing for addOn tests. cms glimpse shows that it is ref from
>
> |>cmsglimpse MagneticFieldVolumes_1_v7_large
> src/MagneticField/Engine/python/volumeBasedMagneticField_120812_cfi.py:
> 'MagneticField/GeomBuilder/data/MagneticFieldVolumes_1_v7_large.xml',
> src/MagneticField/Engine/python/volumeBasedMagneticField_120812_largeYE4_cfi.py:
> 'MagneticField/GeomBuilder/data/MagneticFieldVolumes_1_v7_large.xml',
> src/MagneticField/GeomBuilder/test/Visualization/displayMFGeom_cfg.py: #
> 'MagneticField/GeomBuilder/data/MagneticFieldVolumes_1_v7_large.xml',
> src/MagneticField/GeomBuilder/test/mfxmlwriter.py:
> 'MagneticField/GeomBuilder/data/MagneticFieldVolumes_1_v7_large.xml', |

Sure, but these are not intended to be used in production,
Configuration/​StandardSequences/​python/​MagneticField_cff.py
should be used instead.

Hardcoding a specific field map instead of using the StandardSequences 
means you get stuck with it and do not follow subsequent developments.

The bug appears to be here:

http://cmslxr.fnal.gov/source/Utilities/ReleaseScripts/scripts/addOnTests.py?v=CMSSW_9_2_4#0090

where "--magField 38T_PostLS1" should be remvoed. Same in the following 
line.

It is quite difficult for me to figure out where such misuses happen, 
the only thing I can do is to move awat all non-standard configuration 
snippets from MagneticField/Engine/python (some of them cannot be used 
anyhow, since we removed the xml files upon Slava's request).

This is probably going to break some other private/test .py that use 
these sequences instead of the StandardSequences.

Cheers
	Nicola

**Comment by Martin-Grunewald** [comment]
Is removal of --magField sufficient or does it need to be replaces by something else?

**Comment by namapane** [comment]
If you remove it, it will pick the default, which is 
Configuration/StandardSequences/python/MagneticField_cff.py; this is set 
here as far as I can see:

http://cmslxr.fnal.gov/source/Configuration/Applications/python/ConfigBuilder.py?v=CMSSW_9_2_4#0032

http://cmslxr.fnal.gov/source/Configuration/Applications/python/ConfigBuilder.py?v=CMSSW_9_2_4#1042

Cheers,
	Nicola

**Comment by Martin-Grunewald** [comment]
Thanks! PR is submitted: https://github.com/cms-sw/cmssw/pull/19667

**Pull request merged**
