### PR TITLE
Run2-hcx162 Remove remaining geometry bugs for HCAL

### PR DESCRIPTION
**Pull request by bsunanda**
Thought some of the changes were made in PR#20976 but the merged version does not contain the changes

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@ianna Please approve this

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by ianna** [comment]
+1

**Comment by davidlange6** [comment]
merge

**Pull request merged**
