### PR TITLE
MTD reconstruction validation: tracks and vertices

### PR DESCRIPTION
**Pull request by fabiocos**
#### PR description:

This PR extends the previous work integrated in #35482 in several ways:

- cleaning of existing plots for 4D vertex validation;
- move into vertex class plots for vertex validation previously in track validation;
- addition in track validation class of plots based on a reco-sim truth matching using ```GenParticle```s associated to the true PV, as done for the selection sued to compute the MVA MTD quality flag.

An harvester has been introduced also for ```MtdTracksValidation``` class

#### PR validation:

Test wf 34634.0 and 34834.0 (PU privately built) runs and produces expected plots.

### CODE REVIEW

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
@gsorrentino18 FYI

**Comment by fabiocos** [comment]
Any comment? Otherwise can we move forward?

**Comment by emanueleusai** [comment]
@fabiocos can you please greenlight the new MEs here?
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_2_X_2021-11-04-1100+2ba253/46670/dqm-histo-comparison-summary.html
especially:
https://tinyurl.com/yzesl6lu and https://tinyurl.com/ykxfjbw9

Some of the new ME appear to be empty, is this because of the small statistics of the unit tests?

**Comment by fabiocos** [comment]
@emanueleusai I did extensive checks of the histograms, and they look reasonable to me. Besides the newly added histograms, those removed or whose definition has been changed, all the tests involving multiple reconstructed vertices are empty if there is just a single reconstructed vertex (for no PU samples).

For samples with PU, some histograms (DeltaZ and DeltaT between vertices) may anyway have a limited number of entries for low PU. In particular DeltaT histograms are filled only for vertices close in Z, see for instance https://github.com/cms-sw/cmssw/pull/35989/files#diff-ad794caa0fa59947d715316dd1617c612e41544f6f43043f13b5a28321e81d1fR1406 .This could explain why even for PU samples some of these histograms are not filled. The idea is to monitor to which extent the time information may separate vertices very close in Z.

To give you an idea, in a private test with PU = 200, for 5 events I find just 1 entry for DeltaTfakefake, and 71 for DeltaTfakereal.

**Comment by fabiocos** [comment]
[DeltaTfakefake.pdf](https://github.com/cms-sw/cmssw/files/7512281/DeltaTfakefake.pdf)

100 events with PU = 200 (comparing this PR and an additional update to the time reconstruction to be proposed soon)

**Comment by emanueleusai** [comment]
Thank you very much for the feedback!

**Comment by emanueleusai** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
