### PR TITLE
Dynamic strip reco 75 x

### PR DESCRIPTION
**Pull request by andrewj314**
Backport of PR #10805 to 7_5_X

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/10925	33f9993
- backport is done correctly (the same code changes are applied as in the 76X version https://github.com/cms-sw/cmssw/pull/10805	83ed5d2)
- tested additionally locally in CMSSW_7_5_X_2015-08-20-2300 /test area sign573/ with a short matrix and a run2 prompt-reco workflow. Changes are consistent with the changes observed in 76X tests (spot checks of a few performance numbers and plots show essentially the same differences)
    - DQM and fwlite reco comparisons show differences only in tau plots
    - 7 producers removed, 11 producers added: net change in CPU is within 10ms/evt (0.1% of the job)

**Comment by slava77** [comment]
@monttj 
please check
we are waiting for your signature here

**Comment by monttj** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
