### PR TITLE
[81X] update RECO & SIM phase-1 geometry 

### PR DESCRIPTION
**Pull request by mmusich**
backport of #16804 

# Summary of changes in Global Tags 
 
## Upgrade 
 
   * **PhaseI realistic scenario** : [81X_upgrade2017_realistic_v26](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_upgrade2017_realistic_v26) as [81X_upgrade2017_realistic_v25](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_upgrade2017_realistic_v25) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_upgrade2017_realistic_v26/81X_upgrade2017_realistic_v25): 
      * **RECO geom**: un-do the assignment of passive material outside the TK volume to the last layer of TK
      * **SIM geom**: Fix overlaps in Pixel support structure. Subtraction with Union solid replacement in ES support structure (no changes in sensitive volumes) . Pixel support structure material density has been corrected to compensate for the (very minimal) shape changes
 
   * **PhaseI design scenario** : [81X_upgrade2017_design_IdealBS_v10](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_upgrade2017_design_IdealBS_v10) as [81X_upgrade2017_design_IdealBS_v9](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_upgrade2017_design_IdealBS_v9) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_upgrade2017_design_IdealBS_v10/81X_upgrade2017_design_IdealBS_v9): 
      * **RECO geom**: un-do the assignment of passive material outside the TK volume to the last layer of TK
      * **SIM geom**: Fix overlaps in Pixel support structure. Subtraction with Union solid replacement in ES support structure (no changes in sensitive volumes) . Pixel support structure material density has been corrected to compensate for the (very minimal) shape changes
 
   * **PhaseI cosmics scenario** : [81X_upgrade2017cosmics_realistic_peak_v9](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_upgrade2017cosmics_realistic_peak_v9) as [81X_upgrade2017cosmics_realistic_peak_v8](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/81X_upgrade2017cosmics_realistic_peak_v8) with the following [changes](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/81X_upgrade2017cosmics_realistic_peak_v9/81X_upgrade2017cosmics_realistic_peak_v8): 
      * **RECO geom**: un-do the assignment of passive material outside the TK volume to the last layer of TK
      * **SIM geom**: Fix overlaps in Pixel support structure. Subtraction with Union solid replacement in ES support structure (no changes in sensitive volumes) . Pixel support structure material density has been corrected to compensate for the (very minimal) shape changes

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
+1

**Comment by mmusich** [comment]
@davidlange6 this supersedes also #16706 which the change in the Hcal ZS that you've just been discussing at the PPD general meeting with @abdoulline. Shall it be reverted? (It is already included in 90x via https://github.com/cms-sw/cmssw/pull/16705)

**Comment by davidlange6** [comment]
personally I’m against anything that is not a bug fix at this point in 810.. but maybe you’ve already gotten agreement from management (as I don’t think this is my decision)

**Comment by mmusich** [comment]
apologies, I had actually missed the last version of the GT (picked up only the ZS change). 
Now in this PR there is both the ZS change and the geometry update. 
I am waiting on @abdoulline confirmation to go ahead with this version at this point, or to roll-back the ZS change.

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
seems no one is against..

**Comment by mmusich** [comment]
+1
(for the record)

**Comment by franzoni** [comment]
@davidlange6 @ianna 

the discussion on the SIM geometry yesterday at the PPD general meeting 
referred  to the changes which were already entered in XMLFILE_Geometry_81YV15_Extended2017_mc

https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideDataBaseGeometry#Payloads_In_the_Production_Datab

**before** this PR. 
XMLFILE_Geometry_81YV16_Extended2017_mc is the SIM geometry which has entered the GT's of this PR ; for the sake of clarity / peace of mind, it remains imho useful having the comparison between V15 and V16 (the text-file diff is very large between the two) to assess if there are any actual differences

**Pull request merged**
