### PR TITLE
Run3-TB47 Test and validate TB simulation of HGCal

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Validate the wafer numbering in the new TB simulation setup

#### PR validation:

Use the cfg file in Geometry/HGCalCommonData/test/python apart from the standard matrix

#### if this PR is a backport please specify the original PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade

**Comment by civanch** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
