### PR TITLE
Clean BuildFiles before DataFormats

### PR DESCRIPTION
**Pull request by guitargeek**
#### PR description:

Another quick partially automatic BuildFile cleaning PR in the style of many before (for example https://github.com/cms-sw/cmssw/pull/29906), this time covering all subsystems before **DataFormats**.

Some plugins which were not merged with their header files actually had their header files in the `interface` directory, even though they are not needed by the library (only the plugins). This confuses my BuildFile/includes checker, which does not expect this entanglement between the library and the plugins. For these cases, I merged the plugin header with the `cc` file.

#### PR validation:

CMSSW compiles. It was checked that all newly added dependencies are actually required by the package with `git grep`.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by jfernan2** [comment]
+1

**Comment by guitargeek** [comment]
Thanks for your comment, @pieterdavid! Of course your developments have priority and the BuildFile cleaning can be easily rebased. I don't know if this PR could make it into 11_2_0_pre1, maybe @silviodonato can comment more. Otherwise there is no problem to leave the changes to the plugin code out.

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/30139	59fea5f
- this is quite technical for reco, only some cleanups in BuildFiles

**Comment by pohsun** [comment]
+1

**Comment by guitargeek** [comment]
Hi @pieterdavid, I'm a bit confused now because this PR got the `alca-approved` a few days ago even thought you were asking for it to be delayed. Does this mean that there is actually no problem and it should be merged, of was the signature just a misunderstanding? Thanks for any clarification.

**Comment by pieterdavid** [comment]
Hi @guitargeek thanks for checking, but there's no need to delay this (I brought it up because having it in last week's pre-release would have been convenient, but we will manage).

**Comment by ggovi** [comment]
+1

**Comment by silviodonato** [comment]
code-checks

**Comment by silviodonato** [comment]
+1

**Pull request merged**
