### PR TITLE
[102X][L1T][DQMOffline] L1TEGammaOffline fixes (CMSLITDPG-585)

### PR DESCRIPTION
**Pull request by kreczko**
Backport of #23679

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by andrius-k** [comment]
+1

**Comment by thomreis** [comment]
+1

**Comment by thomreis** [comment]
+1

**Comment by thomreis** [comment]
Hi @fabiocos 
can this PR be merged please so that it can run at the T0 as soon as possible?

**Comment by fabiocos** [comment]
@thomreis the master version of this and other PRs has been merged in 10_3_0_pre1. As soon as we see a positive validation of it I will merge it, according to the usual procedure

**Comment by fabiocos** [comment]
+1

**Pull request merged**
