### PR TITLE
Run4-hgx281z Fix the debug statements for algorithms of HGCAL

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

 Fix the debug statements for algorithms of HGCAL

#### PR validation:

Use the runTheMatrix test workflows

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
+1

**Comment by srimanob** [comment]
+Upgrade

**Comment by silviodonato** [comment]
+1

**Pull request merged**
