### PR TITLE
Temporarily revert "Adapt @express sequence for T0"

### PR DESCRIPTION
**Pull request by fabiocos**
Reverts cms-sw/cmssw#23276

The discussion about the best possible definition for the @express sequence to be used is still ongoing, see comments to #23351 (backport to 10_1_X of @23276). Following the objections raised by the tracker community and the following discussion with @schneiml , the old version of the express sequence is temporarily restored.

### CODE REVIEW

**Comment by fabiocos** [comment]
@schneiml @mmusich @boudoul following the discussion in #23351 

In this way the addition of "@egamma+@L1TMuon+@L1TEgamma+@HLTMon" is temporarily lost. As the concern is with replacing @commonSiStripZeroBias with @common, do you see interferences between restoring @commonSiStripZeroBias and the addition of the new part?

**Comment by boudoul** [comment]
sounds like a good suggestion to me ,thanks

**Comment by schneiml** [comment]
@fabiocos adding the new sequences should not really hurt, except for causing more confusion, since then we have one more config to talk about (next to: T0 prod, old relval, new unified relval/prod).

Another proposal would be to move `@express` to what is used in T0 prod today.

**Comment by fabiocos** [comment]
@schneiml having @express and the T0 sequence to converge is the target. My question indeed was to which extent you are able to reproduce it exactly in the release. The other point is to review it, adding what is possibly missing and removing what not needed (if any at all)

**Comment by schneiml** [comment]
To make them converge, the proper way would be to modify Configuration/PyReleaseValidation/python/relval_steps.py:1460 to say just `DQM` (rather than `DQM:@express`). That is closest to what T0 runs. The content of the `@express` sequence is irrelevant then.

We can also change `@express` to what the empty DQM parameter means, `DQMOffline` (I am not entirely sure what happens to harvesting, I'd have to look that up).

Neither of these really helps in the discussion what `@express` should contain, and how to represent the Express DQM in terms of Prompt DQM sequences.

**Comment by fabiocos** [comment]
@schneiml I would say that we should not rush with intermediate solutions that are not well understood and could potentially cause further confusion. We keep for the time being the old situation by merging this PR, while you and the DQM team iterate further with the DPGs so as to converge on an agreed proposal for an @express definition that can be moved also at the T0. 

Do you see this feasible by CMSSW_10_2_0_pre6?

**Comment by schneiml** [comment]
@fabiocos for the timescale, I guess that is up to the concerned groups (@mmusich, @boudoul?). We did ask to the subsystems what they need, and got some responses, but in case of the Tracker PCL, it seems nobody is really sure what is needed atm.

If some additional information (which modules are in which sequence, which MEs come from which modules) is needed, I can provide it in two weeks -- but we (core-DQM) cannot take a decision there. We got more or less explicit greenlight from all subsystems except Tracker, where it was more along the lines of "this is probably ok".

**Comment by boudoul** [comment]
I'm getting more and more confused since I'm keeping reading what I would call contradictory statements / proposals  - Since I guess (hope..) it cannot be, then I should take a bit of time to understand what is even the proposal (or the goal ...) - I might discuss directly with @schneiml to achieve this .

**Comment by mmusich** [comment]
> but in case of the Tracker PCL, it seems nobody is really sure what is needed atm.

@schneiml uhmm, if you are referring to the Bad components PCL I am afraid you got this information wrong (or maybe misunderstood?). 
Actually that's the only thing I checked explicitly and it goes through via the `SiStripCalZeroBias` AlCaReco DQM sequence, which is **fortunately** unaffected by your PR. 

About  the other modules which seem not to be in your new definition, I think I already gave you an answer in https://github.com/cms-sw/cmssw/pull/23351#issuecomment-393479569, based on your analysis posted at https://mschneid.web.cern.ch/mschneid/expressdifferences (shall we trust it??) so:

```
process.MonitorTrackResiduals
process.refittedForPixelDQM
```

should probably be put back in the sequence, but should be the experts (@fioriNTU,@jandrea @arossi83) to have the final word.
Frankly about this whole statement:

> If some additional information (which modules are in which sequence, which MEs come from which modules) is needed, I can provide it in two weeks -- but we (core-DQM) cannot take a decision there. 

I find it unacceptable: you are proposing the changes. Tracker answer is: "please build the sequence in a way that produces *exactly* the same output as it is run in express now". I think it's actually on you, who are proposing the changes to secure that.

Finally about: 

> We got more or less explicit greenlight from all subsystems" 

have you re-checked with them based on the output of https://mschneid.web.cern.ch/mschneid/expressdifferences ?

**Comment by schneiml** [comment]
@mmusich 

> have you re-checked with them based on the output of https://mschneid.web.cern.ch/mschneid/expressdifferences

No, I expected that to be a bit easier -- given Prompt uses a, lets call it, "modular" configuration for a long time and people usually know what they need.

> I find it unacceptable: you are proposing the changes. Tracker answer is: "please build the sequence in a way that produces exactly the same output as it is run in express now". I think it's actually on you, who are proposing the changes to secure that.

Roughly the same goes here -- I don't see much point in a bug-for-bug reproduction. And if we have no way to validate even fairly obvious changes ("what runs"), then our software is in a way worse state than I hoped it to be. Of course my guess for `@common` rather than `@commonSiStripZeroBias` was based on what runs on production atm. I don't expect you to be able to interpret what the T0 config does there, but then you have to trust me that my interpretation is correct. If you need more information, I can provide that, but not in the next days (for independent reasons).

> which is fortunately unaffected by your PR

Towards bigger architectural complaints, I am worried that anything in the PCL depends on "normal" DQM output. ALCA can use DQM infrastructure for their purposes, but IMO the DQM "for human consumption" and the output "for PCL machinery" should be strictly separated. But we won't change anyting about that in these PRs.

> (shall we trust it??)

For now no, I'll convince myself that I did the right thing when I have time (not next week). Though the lists look plausible for now, I don't expect them to change.

**Comment by mmusich** [comment]
>  I don't see much point in a bug-for-bug reproduction. And if we have no way to validate even fairly obvious changes ("what runs"), then our software is in a way worse state than I hoped it to be.

Maybe I am a bit dense today, but I am unable to follow your logic. What is bugged? What currently is run on real express? I totally understand that you want to attach to the Tier-0 configuration a tag which the same that is run in the relvals (so that for once we will be running what we validate), but I miss where the difficulty lies in constructing a new `@express` definition that contains *verbatim* the same sequence which run in real express data. Is it technical?

> , I am worried that anything in the PCL depends on "normal" DQM output. ALCA can use DQM infrastructure for their purposes, but IMO the DQM "for human consumption" and the output "for PCL machinery" should be strictly separated.

provided PPD core groups (DQM,ALCA,whatnot) develop a viable alternative I think that's more than welcome (as it will allow to avoid threading on each other's feet).

**Comment by schneiml** [comment]
> What currently is run on real express?
https://github.com/cms-sw/cmssw/pull/23416#issuecomment-393893493 is probably my clearest summary on that. I am willing to call this a bug, at least the fact that 1001.2 does not represent that is one.

> provided  PPD core groups (DQM,ALCA,whatnot) develop a viable alternative I think  that's more than welcome (as it will allow to avoid threading on each  other's feet).

Let's put that into "LS2 goals".

**Comment by 15826717775** [comment]
imap

**Comment by dmitrijus** [comment]
+1
(as discussed during core DQM meeting)

**Comment by fabiocos** [comment]
+1

keep the old sequence definition until a clarification is finally reached on the new one

**Pull request merged**
