### PR TITLE
Pr100x L1T integration development and fixes upto v97.16 (backport)

### PR DESCRIPTION
**Pull request by rekovic**
PR 10_0_X:

This is back-port of 10_1_X PR #22368

### CODE REVIEW

**Comment by rekovic** [comment]
please test

**Comment by rekovic** [comment]
back-port of #22368

**Comment by thomreis** [comment]
backport of #22368

**Comment by rekovic** [comment]
+1

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
@rekovic after the move to 10_1_X this PR can be closed

**Pull request closed without merging**
