### PR TITLE
NanoAODv7 code updates, part 1

### PR DESCRIPTION
**Pull request by peruzzim**
#### PR description:

This PR includes updates for NanoAODv7.
A second PR will come very soon with minor additions, but in the meanwhile we can start checking this.
No other workflows are expected to be modified.

Summary of changes:
- updated betastar variables for jets
- fixed gen-photon matching
- updated b-jet and c-jet energy regressions
- consolidate electron trigger object filter bit definitions across years
- added filter bits for high pt electron and muon triggers
- updated muon selectors
- minor fixes and additional variables in fat jets
- added isolated gen-level photons
- fixes to event counters and weight sums
- fix muon IP sign
- updated photon IDs (esp. added Fall17v2 to 2016)
- JetMET info additions (unclustered MET, PUPPI MET total uncertainties)
- added SC energy for electrons
- critical fixes to gen weights storage in randomized parameter scans
- additional LHE info for MG reweighting

### CODE REVIEW

**Comment by peruzzim** [comment]
please test workflow 1325.6,1325.7,1325.8,1329.1,136.7722,136.7952,136.8521 with cms-data/PhysicsTools-NanoAOD#12

**Comment by peruzzim** [comment]
+xpog

Changes in NanoAOD output, as expected. I also validated externally that it runs in all supported configurations of datasets and eras.

**Comment by peruzzim** [comment]
@perrotta @slava77 could you please review this? thank you!

**Comment by perrotta** [comment]
+1
- Changes in reco code refer to
  - PhysicsTools/PatAlgos/plugins/LeptonUpdater.cc, where two configuration parameters needed to fix the sign of the impact parameter were added: their default settings do not affect reco outputs
  - Modifications in RecoJets/JetProducers/plugins/BetaStarVarProducer.cc only affect nanoAOD, which is the only user of the "BetaStarPackedCandidateVarProducer" by now
- Jenkins tests show no differences in reco outputs; changes observed in the nanoAOD outputs have been validated by @peruzzim, as reported in https://github.com/cms-sw/cmssw/pull/29179#issuecomment-598192393

**Comment by silviodonato** [comment]
Kind reminder @santocch

**Comment by peruzzim** [comment]
superseded by #29212

**Pull request closed without merging**
