### PR TITLE
Fix try/catch in Vx3DHLTAnalyzer

### PR DESCRIPTION
**Pull request by francescobrivio**
#### PR description:
In #38687 a `try/catch` statement was added in the DQM client `Vx3DHLTAnalyzer` to protect the client against Minuit2 FatalRootError, but the return codes were not set properly, as reported in https://github.com/cms-sw/cmssw/pull/38687#discussion_r952423487.
This PR provides a bugfix.

#### PR validation:
Code compiles + run the unitTest.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Not a backport.
Backports to 12_5_X and 12_4_X will be provided soon.

FYI @dinardo @mmusich

### CODE REVIEW

**Comment by francescobrivio** [comment]
type bug-fix

**Comment by francescobrivio** [comment]
test parameters:
 - addpkg = DQM/Integration

**Comment by mmusich** [comment]
> Code compiles + run the unitTest.

was this tested against the problematic data leading to the crash online?

**Comment by francescobrivio** [comment]
> > Code compiles + run the unitTest.
> 
> was this tested against the problematic data leading to the crash online?

I tried running it on the RAW data of the problematic run, but I observed no crash...I don't think we still have the streamer files for that run...

I increased manually the VtxError parameter in order to make the same crash appear (FatalRootError: @SUB=Minuit2) and it is catched correctly, but yes I agree it's not the same thing...

**Comment by mmusich** [comment]
> I tried running it on the RAW data of the problematic run, but I observed no crash...I don't think we still have the streamer files for that run...

according to https://github.com/cms-sw/cmssw/pull/38687#discussion_r960574478 there are streamer files, or did I misunderstand?

**Comment by francescobrivio** [comment]
> > I tried running it on the RAW data of the problematic run, but I observed no crash...I don't think we still have the streamer files for that run...
> 
> according to [#38687 (comment)](https://github.com/cms-sw/cmssw/pull/38687#discussion_r960574478) there are streamer files, or did I misunderstand?

please see my answer to that post, the misunderstanding is from the DQM-DOC size 😄 
bottomline, at the moment, we do not have streamer files to reproduce the issue.

**Comment by francescobrivio** [comment]
ok I'm in contact with DQM-DOC (@vicha-w) to get hold of the needed streamer files. I will update you once I can run a test on them.

**Comment by mmusich** [comment]
@cmsbuild, please test
   * I guess, testing this in the meanwhile won't harm.

**Comment by vicha-w** [comment]
Vichayanun Wachirapusitanand (he/him, no PhD)
Department of Physics, Faculty of Science
Chulalongkorn University
Sent from Outlook for Android
________________________________

**Comment by francescobrivio** [comment]
> ok I'm in contact with DQM-DOC (@vicha-w) to get hold of the needed streamer files. I will update you once I can run a test on them.

I tried running on LSs 1-2-3 of the problematic run (`357900`) but I could not reproduce the crash originally observed by DQM experts (which I attach here for reference: [beampixel_crash_run357900.txt](https://github.com/cms-sw/cmssw/files/9488516/beampixel_crash_run357900.txt)).

The only way I have to _mimic_ this error is to enlarge the `VtxError` parameter so I get the Minuit failure which is correctly catch-ed by the try/catch that I had already implemented in my previous PR, but of course this is not the real crash observed online.

**Comment by syuvivida** [comment]
@francescobrivio 
I just did a test by running the beampixel client locally at lxplus. The CMSSW is built in CMSSW_12_4_7. The input files are the same one copied from Vicha, (DQM-DOC last week): /afs/cern.ch/work/s/syu/run357900_stream/run357900. If I ran each lumi sections (1, 2, 3) separately in 3 jobs, the job finished OK. But if I ran all 3 lumisections together (one after the other in the same job), I started seeing a crash. Hope this [Log357900.txt](https://github.com/cms-sw/cmssw/files/9495611/Log357900.txt) helps. It seems similar to the text file from the original DQM crash?

**Comment by mmusich** [comment]
@syuvivida 

> I just did a test by running the beampixel client locally at lxplus. The CMSSW is built in CMSSW_12_4_7. 

does this test include the changes proposed in this PR?

**Comment by syuvivida** [comment]
@mmusich 
My original idea was to try to see if we can reproduce the crash under the same condition when the first crash happened in run 357900 on August 23. At that time, DQM only ran CMSSW_12_4_7 without this PR. Therefore, I didn't test this PR.

**Comment by mmusich** [comment]
@syuvivida 

> My original idea was to try to see if we can reproduce the crash under the same condition when the first crash happened in run 357900 on August 23. At that time, DQM only ran CMSSW_12_4_7 without this PR. Therefore, I didn't test this PR.

thanks for the clarification. Can you try again including commit ee5b0ec96421c37e9820270ec88655bdd5780c64 in order to test the validity of this patch?

**Comment by syuvivida** [comment]
@mmusich 
I saw the same crash after including the commit and rebuilding it. Note, another finding also confirmed by our DQM team Petr. If we run only lumi sections 2 & 3 together, jobs finished OK (this is true for both without /with patch). 

Eiko
Below is the log file. 
[withPR39285.txt](https://github.com/cms-sw/cmssw/files/9495950/withPR39285.txt)

**Comment by syuvivida** [comment]
Just to summarize, the jobs finished ok if running on each LS separately in separate jobs. Crashed if running on LS2 as the second input file (i.e. run LS 1&2 or 1&2&3, but OK with LS 2&3)

**Comment by mmusich** [comment]
@syuvivida 

> /afs/cern.ch/work/s/syu/run357900_stream/run357900. 

can you move these files somewhere public? I don't seem to be able to list these files.

**Comment by syuvivida** [comment]
@mmusich 
@francescobrivio is looking into this. 

I was using the command below to run CMSSW with a "scanOnce=True" flag [1]. 

cmsRun DQM/Integration/python/clients/beampixel_dqm_sourceclient-live_cfg.py runInputDir=/afs/cern.ch/work/s/syu/run357900_stream/ runNumber=357900 runkey=pp_run scanOnce=True

The files are actually copied from this EOS area of Vicha. 
/eos/user/v/vwachira/public/run_357900/
You can also see the files in EOS. 

[1] 
https://github.com/cms-sw/cmssw/blob/9a9304188953022c7fb63318b62823ed466590f8/DQM/DTMonitorModule/python/test/inputsource_live_cfi.py#L25-L29

**Comment by francescobrivio** [comment]
@mmusich @syuvivida I confirm I can now reproduce the crash. I'm working on testing my commint and providing a new fix. Will let you know asap.

**Comment by francescobrivio** [comment]
In the last commit ([2de5b5f](https://github.com/cms-sw/cmssw/pull/39285/commits/2de5b5f634dffb2987eae904a2b8467ab499bd58)), together with @dinardo, we have fixed the function that was causing the crash.
Now the ROOT Minuit2 failure is correctly catched and the program continues without crashing:
```
%MSG
%MSG-e Vx3DHLTAnalyzer:  Vx3DHLTAnalyzer:pixelVertexDQM@endLumi  07-Sep-2022 17:23:08 CEST Run: 357900 Lumi: 2
	Caught Minuit2 exception @ Final fit: 
An exception of category 'FatalRootError' occurred.
   Additional Info:
      [a] Fatal Root Error: @SUB=Minuit2
VariableMetricBuilder Initial matrix not pos.def.


%MSG
Begin processing the 3rd record. Run 357900, Event 3204845, LumiSection 3 on stream 0 at 07-Sep-2022 17:23:09.448 CEST
%MSG-w DAClusterizerinZ_vect:  PrimaryVertexProducer:pixelVertices  07-Sep-2022 17:23:09 CEST Run: 357900 Event: 3204845
rejected track t_tkwt 1.29845e-16
%MSG
%MSG-w DAClusterizerinZ_vect:  PrimaryVertexProducer:pixelVertices  07-Sep-2022 17:23:09 CEST Run: 357900 Event: 3204845
rejected track t_tkwt 1.67157e-24
%MSG
...
```

@syuvivida @pmandrik could you please re-run your test in the playback machine with commit [2de5b5f](https://github.com/cms-sw/cmssw/pull/39285/commits/2de5b5f634dffb2987eae904a2b8467ab499bd58)?

I will open the 12_5_X and 12_4_X backports later today.

**Comment by francescobrivio** [comment]
@cmsbuild please test

**Comment by mmusich** [comment]
```
%MSG-w DAClusterizerinZ_vect:  PrimaryVertexProducer:pixelVertices  07-Sep-2022 17:23:09 CEST Run: 357900 Event: 3204845
rejected track t_tkwt 1.67157e-24
%MSG
```

all of these warnings with ludicrous track weights are indicating that the DA is getting in input some tracks with very large IP significance, indications that they are not correctly associated to the right vertex. Perhaps it is worth checking how the DA vertexing is setup for this application.

**Comment by francescobrivio** [comment]
> ```
> %MSG-w DAClusterizerinZ_vect:  PrimaryVertexProducer:pixelVertices  07-Sep-2022 17:23:09 CEST Run: 357900 Event: 3204845
> rejected track t_tkwt 1.67157e-24
> %MSG
> ```
> 
> all of these warnings with ludicrous track weights are indicating that the DA is getting in input some tracks with very large IP significance, indications that they are not correctly associated to the right vertex. Perhaps it is worth checking how the DA vertexing is setup for this application.

I agree with you, but I'd prefer to leave this to a future PR since it is addressing a different issue.
Do you agree Marco?

**Comment by mmusich** [comment]
> I agree with you, but I'd prefer to leave this to a future PR since it is addressing a different issue.
Do you agree Marco?

It might be that the Minuit exception is linked to the vertices given in input, but sure let's deal with that later as this PR offers a safety net against crashes at P5.
Opening a gitHub issue to remind us about it would be good though.

**Comment by francescobrivio** [comment]
> It might be that the Minuit exception is linked to the vertices given in input

Good point!

> Opening a gitHub issue to remind us about it would be good though.

Please see https://github.com/cms-sw/cmssw/issues/39339

**Comment by tvami** [comment]
+db
 * trusting private results from the author

**Comment by emanueleusai** [comment]
+1

**Comment by perrotta** [comment]
+1

**Pull request merged**
