### PR TITLE
Run endStream concurrently as part of endJob

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

- Run the different streams and SubProcesses concurrently at the EndStream transition.

#### PR validation:

Code compiles and framework unit tests pass.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by makortel** [comment]
From visual inspection the only question I have is if we should eventually do the same for beginStream?

**Comment by Dr15Jones** [comment]
please test

**Comment by makortel** [comment]
+1

**Comment by qliphy** [comment]
+1

**Comment by makortel** [comment]
Could this PR be causing many failures at the end of the jobs in IBs along
```
dropped waiting message count 0
----- Begin Fatal Exception 01-Sep-2021 19:40:33 CEST-----------------------
An exception of category 'MultipleExceptions' occurred while
   [0] Calling endJob
Exception Message:
Multiple exceptions were thrown while executing endJob. An exception message follows for each.
1
An exception of category 'NotFound' occurred while
   [0] Calling endStream for module MixingModule/'mix'
Exception Message:
Service no ServiceRegistry has been set for this thread 
2
An exception of category 'NotFound' occurred while
   [0] Calling endStream for module MixingModule/'mix'
Exception Message:
Service no ServiceRegistry has been set for this thread 
3
An exception of category 'NotFound' occurred while
   [0] Calling endStream for module MixingModule/'mix'
Exception Message:
Service no ServiceRegistry has been set for this thread 
----- End Fatal Exception -------------------------------------------------
```
https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc900/CMSSW_12_1_X_2021-09-01-1100/pyRelValMatrixLogs/run/300.0_Pyquen_GammaJet_pt20_2760GeV+Pyquen_GammaJet_pt20_2760GeV+DIGIHIMIX+RECOHIMIX+HARVESTHI2018PPRECO/step1_Pyquen_GammaJet_pt20_2760GeV+Pyquen_GammaJet_pt20_2760GeV+DIGIHIMIX+RECOHIMIX+HARVESTHI2018PPRECO.log#/

**Comment by qliphy** [comment]
@Dr15Jones 
I could reproduce the IB issue using "runTheMatrix.py -l 200 --job-reports -t 4 --ibeos"

CMSSW_12_1_X_2021-08-31-2300:  works well
CMSSW_12_1_X_2021-08-31-2300 + this PR:  give the issue

while "runTheMatrix.py -l 200" with this PR also runs well, that is why the PR test doesn't catch this error.

Do you have a workaround quickly? Or otherwise we revert this PR as quite many workflows in IB are failing?

**Comment by Dr15Jones** [comment]
@qliphy I'll have a fix in a few minutes.

**Comment by Dr15Jones** [comment]
@qliphy  fixed in #35120

**Pull request merged**
