### PR TITLE
disable ZS mark and pass for 2017

### PR DESCRIPTION
**Pull request by deguio**
backport of #20115

### CODE REVIEW

**Comment by slava77** [comment]
if this changes MC and data behavior, this PR can not go in to the production setup.
If settings are needed for special rerecos, they can be passed with a customization.

If this affects only data, perhaps it may still go in, but needs some coordination with a data rereco release

**Comment by deguio** [comment]
Hi @slava77 
this affects data only. there is no ZS emulated in MC.
and yes, we need to make sure that this gets merged in the release that will be used for the early 2017 data rereco.

**Comment by slava77** [comment]
On 8/10/17 8:17 AM, Federico De Guio wrote:
> Hi @slava77 <https://github.com/slava77>
> this affects data only. there is no ZS emulated in MC.
> and yes, we need to make sure that this gets merged in the release that
> will be used for the early 2017 data rereco.

What is the size of the effect (perhaps I should wait for response to my
q in 93X PR).
Was this change discussed in PPD already? I haven't seen anything on
this in the general meeting.
(the slides there are somewhat suggestive that 9_2_8 released on Aug 5
is to be used for data rereco).

Some comments on this in the reco meeting tomorrow would be nice as well.

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by abdoulline** [comment]
@slava77 
there was quite a live discussion yesterday at PPD on JME results at slide No.7 (comparing middle and right side)
https://indico.cern.ch/event/659010/contributions/2687022/attachments/1506909/2348470/PPD.pdf
JetMET wants to have the right-side result for early 2017 data, which is provided by this PR.

**Comment by slava77** [comment]
On 8/10/17 10:39 PM, Salavat Abdullin wrote:
> @slava77 <https://github.com/slava77>
> there was quite a live discussion yesterday at PPD on JME results at
> slide No.7 (comparing middle and right side)
> https://indico.cern.ch/event/659010/contributions/2687022/attachments/1506909/2348470/PPD.pdf
> JetMET wants to have the right-side result for early 2017 data, which is
> provided by this PR.

I was in the meeting, but the effects of this PR were not clear,
specifically the impact on pre and post-TS1.
Fede has covered it by now.

**Comment by perrotta** [comment]
+1
- Tested in 93X with the corresponding PR #20115, which is identical to this one
- The effect on pre-TS1 data (2017B) is as expected from the description of this PR
- No effect on pst-TS1 (2017C) data, as anticipated
- Jenkins tests report no differences at all, but 2017B data are not tested in 92X 
- In particular, there is no effect on MC wfs, as expected: this PR is is therefore suitable for being backported to 92X

**Comment by franzoni** [comment]
hello @davidlange6 @perrotta 
this PR is necessary for the 2017 rereco being prepared
Is there more feedback or input you need to get it merged in 92 ?
thanks!

@cerminar @deguio @hatakeyamak

**Comment by davidlange6** [comment]
merge

**Pull request merged**
