### PR TITLE
Convert BeamMonitor to be a one::DQMEDAnalyzer

### PR DESCRIPTION
**Pull request by Dr15Jones**
-Replaced the direct calls to DQMStore with implicit calls via the internals of one::DQMEDAnalyzer. This also has the benefit of making this no longer a legacy module.
-Added the one::DQMEDAnalyzer class to explicitly handle the case where a module must be a one module and must communicate with the DQM infrastructure.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
I used the test described here:
https://github.com/cms-sw/cmssw/pull/24346#issuecomment-414791372

the results showed that this pull request results in identical output with the original.

**Comment by schneiml** [comment]
Hi Chris,

how does `one::DQMEDAnalyzer` differ from the normal `DQMEDAnalyzer` as of today? Could we drop the normal `DQMEDAnalyzer` and replace it with a typedef that instantiates  `one::DQMEDAnalyzer` with the per-lumi options? I don't like having multiple implementations of the `DQMEDAnalyzer` around, esp. if some of them are only used in these not-tested-in-ib special modules. 

That said, in the long term we might want to switch back to `stream` by default, so having this explicit is a good idea.

**Comment by Dr15Jones** [comment]
@schneiml 
> Could we drop the normal DQMEDAnalyzer and replace it with a typedef that instantiates one::DQMEDAnalyzer with the per-lumi options?

Yes. I didn't do that initially since I didn't want to be too disruptive (plus having to recompile a huge number of packages :) ). Do you want me to do that change in this pull request?

> That said, in the long term we might want to switch back to stream by default, so having this explicit is a good idea.

That was my motivation for creating the class.

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
please test

**Comment by fabiocos** [comment]
+1

**Pull request merged**
