### PR TITLE
Update Run3 Tracker (Pixel and Strips) conditions

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

The aim of this PR is to update the conditions used for the simulation of Run3 (all three years: 2021, 2023, 2024), correcting few mistakes, inaccuracies observed in the previous round of MC production in 10.6.X.
Namely:
   * the Pixel digitizer threshold is updated in BPix L1 from the unrealistic (too optimistic) threshold of 1300e to 2000e (more in line with lab measurement, see details [here](https://indico.cern.ch/event/841666/contributions/3586406/)).
   * the Pixel CPE conditions are all updated taking into account the updated digi threshold.
   * the Strip conditions are updated using the latest updates introduced for 2018 simulation introduced in PR #28234.
   * the Strip noise extrapolation has been re-done using the updated value for 2018, which yields better Data/MC agreement for 2018 simulation.

#### PR validation:

Extensive validation through production of dedicated private samples has been carried out within the Tracker DPG. A full report has been gathered [here](https://indico.cern.ch/event/841678/?showDate=all&showSession=6#33-feedback-on-the-new-run-3-c).
In addition the alignment performance of the previous misalignment scenario has been checked using samples produced with the updated conditions, and a compelling reason to update it has not been found (report is available [here](https://indico.cern.ch/event/841678/?showDate=all&showSession=0#36-run-iii-studies-virtual)).

#### if this PR is a backport please specify the original PR:

This PR is not a backport, though possibly updated GTs in 10.6.X will be requested as well for further samples production.
Cc:
@tsusa @tvami @pieterdavid @robervalwalsh @connorpa @adewit

### CODE REVIEW

**Comment by mmusich** [comment]
@christopheralanwest @tlampen @tocheng the GT candidates can be made full fledged  GTs. For ease of book-keeping you can find the updates in this [table](https://docs.google.com/spreadsheets/d/1TX3v7O7PZqsOtCcDduiNU-oKKTuhxAhqj7cyBgkUmnY/edit?usp=drivesdk)

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
@christopheralanwest @tocheng @civanch as this PR is listed among those desirable to close the development, could you please review it?

**Comment by tlampen** [comment]
> @christopheralanwest @tlampen @tocheng the GT candidates can be made full fledged GTs. For ease of book-keeping you can find the updates in this [table](https://docs.google.com/spreadsheets/d/1TX3v7O7PZqsOtCcDduiNU-oKKTuhxAhqj7cyBgkUmnY/edit?usp=drivesdk)

The full fledges GTs now exist: 
110X_mcRun3_2021_realistic_v6
110X_mcRun3_2021cosmics_realistic_deco_v4
110X_mcRun3_2023_realistic_v6
110X_mcRun3_2024_realistic_v6

**Comment by tlampen** [comment]
please test

**Comment by mmusich** [comment]
Thanks @tlampen. New GTs included in https://github.com/CMSTrackerDPG/cmssw/commit/9b47d2981f2981cd4cc1f27988828a058ac547de

**Comment by civanch** [comment]
+1

**Comment by fabiocos** [comment]
@christopheralanwest @tocheng @tlampen what is the conclusion about this GT update?

**Comment by tlampen** [comment]
+1

There is a summary presentation in AlCaDB meeting next Monday, but we can go ahead with this PR

**Comment by fabiocos** [comment]
+§

**Comment by fabiocos** [comment]
+1

**Pull request merged**
