### PR TITLE
Improve DQMStreamerOutputRepackerTest to no longer "create" lumisections.

### PR DESCRIPTION
**Pull request by dmitrijus**
This test output module now gets the file offset (which is usually a lumisection) from the event data itself.

### CODE REVIEW

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
strange that there are lots of "differences" in DQM plots for this PR test. Should be fake. will retest

**Comment by davidlange6** [comment]
please test

**Comment by davidlange6** [comment]
Interesting  - DQM histogram failures (eg, in 4.53) are reproducible..

**Comment by davidlange6** [comment]
+1
i see this happening elsewhere too..

**Pull request merged**
