### PR TITLE
Run4-hgx283 Next step for V15 geometry of HGCal

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Creation of cells which will go inside a full wafer for HGCal

#### PR validation:

Use the runTheMatrix test workflow 32634.0 with printouts for G4Regions

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
+1

**Comment by srimanob** [comment]
+upgrade

**Comment by silviodonato** [comment]
+1

**Pull request merged**
