### PR TITLE
Herwig7.1.4 to 94X

### PR DESCRIPTION
**Pull request by Andrej-CMS**
#### PR description:

This PR introduces Herwig7 to 94X to be able to run the generator in the 5TeV campaign.
The PR introduces the Interface, the python configuration files to be used in official production, and the workflow 535 with which this PR should be tested.

#### PR validation:

Was tested with WF 535 (backported here). Tested with fragment from TOP-RunIIFall18wmLHEGS-00358 with :
cmsDriver.py GeneratorInterface/Herwig7Interface/python/TOP-RunIIFall18wmLHEGS-00358-fragment.py --fileout file:TOP-RunIIFall18wmLHEGS-00358.root --mc --eventcontent RAWSIM,LHE --datatier GEN-SIM,LHE --conditions 94X_mc2017_realistic_forppRef5TeV --beamspot Realistic5TeVppCollision2017 --step LHE,GEN,SIM --nThreads 8 --geometry DB:Extended --era Run2_2017_ppRef

Also ran a test with numberEventsInLuminosityBlock= cms.untracked.uint32(20) with 350 events.

#### if this PR is a backport please specify the original PR:
#26905

### CODE REVIEW

**Comment by Andrej-CMS** [comment]
to be tested with https://github.com/cms-sw/cmsdist/pull/5439 and WorkFlow 535 introduced in this PR for 94X.

**Comment by kpedro88** [comment]
test parameters
workflows = 535.0
pull_requests = cms-sw/cmsdist#5439

**Comment by kpedro88** [comment]
@mrodozov @smuzaffar is that the correct syntax for the new feature?

**Comment by smuzaffar** [comment]
yes, but you still need to explicitly start the tests using "please test" comment

**Comment by kpedro88** [comment]
please test

**Comment by kpedro88** [comment]
@Andrej-CMS do you understand the source of the error?

**Comment by kpedro88** [comment]
@Andrej-CMS what is the status of this PR?

**Comment by silviodonato** [comment]
@Andrej-CMS do you have any news on this PR?

**Comment by silviodonato** [comment]
I'm closing this PR since there was no activity in the last weeks. You can open it back again as soon as you have any news.

**Pull request closed without merging**
