### PR TITLE
remove Patatrack-related RelVals for 2018 conditions

### PR DESCRIPTION
**Pull request by missirol**
#### PR description:

This PR removes Patatrack-related RelVals for 2018 conditions from tests running in PRs and IBs, based on https://github.com/cms-sw/cmssw/issues/41410#issuecomment-1523293069 by @fwyzard.

#### PR validation:

None.

#### If this PR is a backport, please specify the original PR and why you need to backport that PR. If this PR will be backported, please specify to which release cycle the backport is meant for:

N/A

### CODE REVIEW

**Comment by missirol** [comment]
enable gpu

**Comment by srimanob** [comment]
+Upgrade

**Comment by sunilUIET** [comment]
+pdmv

**Comment by perrotta** [comment]
+1

**Pull request merged**
