### PR TITLE
Improve Pixel Templates Payload Inspector messages

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

Small technical update, in order not to forego the case in which a certain template payload has less entries than expected for phase-1 detector, but more than phase-0, which means certain `DetIds` were not populated.
The use-case is documented [here](https://hypernews.cern.ch/HyperNews/CMS/get/tk-alignment/1899.htm).
I profit of this PR to add a missing include `CondCore/SiPixelPlugins/interface/SiPixelPayloadInspectorHelper.h` which prevents to use the file from other packages.

#### PR validation:

See e-mail thread at: https://hypernews.cern.ch/HyperNews/CMS/get/tk-alignment/1899.html

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

This PR is not a backport.

### CODE REVIEW

**Comment by mmusich** [comment]
@cmsbuild please test

**Comment by mmusich** [comment]
please test

**Comment by ggovi** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
