### PR TITLE
Phase2-hgx125 Add a scenario D30 with C5 version of calorimeters

### PR DESCRIPTION
**Pull request by bsunanda**
C4 (Yes) version differs from C5 (No) version in the use of virtual wafers.
Close PR#23726 which I could not get rid of merge conflicts

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by kpedro88** [comment]
+1

**Comment by kpedro88** [comment]
@bsunanda do you also want to add workflows here?

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@kpedro88 I don't understand why code checks are not running

**Comment by kpedro88** [comment]
code-checks

**Comment by kpedro88** [comment]
@smuzaffar can you check on the bot

**Comment by smuzaffar** [comment]
there are some issues with CVMFS and every thing is basically blocked. I have opened couple of issues with CERN Service NOW to look in the issue.

**Comment by smuzaffar** [comment]
looks like CERN Squid servers are down, they are looking in to the issue.

**Comment by fabiocos** [comment]
please test

**Comment by ianna** [comment]
+1

**Comment by fabiocos** [comment]
+operations 

addition of new geometry scenario to the StandardSequences

**Comment by kpedro88** [comment]
+upgrade

**Comment by civanch** [comment]
+1

**Comment by kpedro88** [comment]
@prebello @fabozzi please sign

**Comment by fabozzi** [comment]
+1

**Comment by fabiocos** [comment]
+1

it affects Phase2 scenarios

**Pull request merged**
