### PR TITLE
Serialization GCC 7 / Clang cleanup

### PR DESCRIPTION
**Pull request by davidlt**
Please, especially review changed done in `SmallWORMDict` to make sure it does a correct thing.

### CODE REVIEW

**Comment by davidlt** [comment]
please test

**Comment by davidlt** [comment]
I have compared the output of `SmallWORMDict_t` test and it was the same.
```
===== Test "SmallWORMDict_t" ====
7 7
38 38
7 10 15 21 26 32 38
BashfulDocDopeyGrumpyHappySleepySneezy
Dopey
Doc at 1
Sleepy at 5

---> test SmallWORMDict_t succeeded

^^^^ End Test SmallWORMDict_t ^^^^
```

But unit test does not do any testing, just printing stuff.

**Comment by davidlt** [comment]
ping

**Comment by ggovi** [comment]
+1

**Comment by davidlt** [comment]
Do we have any updates from ALCA?

**Comment by ghellwig** [comment]
+1

**Comment by davidlt** [comment]
@davidlange6 could we get this integrated? My hopes are that this should resolve high number of build issues in GCC 7 builds.

**Pull request merged**
