### PR TITLE
[HGCAL trigger] Migrate to esConsumes

### PR DESCRIPTION
**Pull request by jbsauvan**
#### PR description:
- Part of #31061
- Migrate to use esConsumes for modules in   `L1Trigger/L1THGCal` and `L1Trigger/L1THGCalUtilities`

#### PR validation:
Private tests in `L1Trigger/L1THGCalUtilities/test`:
```
cmsRun testHGCalL1T_RelValV11_cfg.py
```

Tested D49, D60 and D68 workflows
```
runTheMatrix.py -w upgrade -l 23234.0 --maxSteps=2 
runTheMatrix.py -w upgrade -l 28234.0 --maxSteps=2 
runTheMatrix.py -w upgrade -l 31434.0 --maxSteps=2
```

### CODE REVIEW

**Comment by makortel** [comment]
Thanks!

**Comment by srimanob** [comment]
@cmsbuild please test

**Comment by jbsauvan** [comment]
Seems that I forgot to migrate `L1Trigger/L1THGCalUtilities/plugins/CaloTruthCellsProducer.cc`, I'll update it.

There is still a deprecated call of `EventSetupRecord::get(ESHandle&)` in `L1Trigger/L1THGCal/src/HGCalTriggerTools.cc`, but this was kept because the `HGCalTriggerTools::eventSetup` function that makes this call is used outside L1THGCal packages in  `L1Trigger/L1CaloTrigger/test`

**Comment by makortel** [comment]
> There is still a deprecated call of `EventSetupRecord::get(ESHandle&)` in `L1Trigger/L1THGCal/src/HGCalTriggerTools.cc`, but this was kept because the `HGCalTriggerTools::eventSetup` function that makes this call is used outside L1THGCal packages in `L1Trigger/L1CaloTrigger/test`

That call needs to be eventually migrated as well. Is the code in `L1Trigger/L1CaloTrigger/test` being run as part of unit tests (`scram b runtests`)? If yes, addressing it rather soon would be appreciated (still a separate PR would be fine).

**Comment by jbsauvan** [comment]
> > There is still a deprecated call of `EventSetupRecord::get(ESHandle&)` in `L1Trigger/L1THGCal/src/HGCalTriggerTools.cc`, but this was kept because the `HGCalTriggerTools::eventSetup` function that makes this call is used outside L1THGCal packages in `L1Trigger/L1CaloTrigger/test`
> 
> That call needs to be eventually migrated as well. Is the code in `L1Trigger/L1CaloTrigger/test` being run as part of unit tests (`scram b runtests`)? If yes, addressing it rather soon would be appreciated (still a separate PR would be fine).

Unfortunately I cannot tell as I'm not responsible of this part (which is why I didn't want to modify the code there). Maybe @cecilecaillol and @rekovic know who in the L1T group could have a look.

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by rekovic** [comment]
+1

**Comment by rekovic** [comment]
@markotel 
> https://github.com/cms-sw/cmssw/pull/35459#issuecomment-930153642

No, the code in L1Trigger/L1CaloTrigger/test is not run as part of unit tests.

**Comment by makortel** [comment]
@cms-sw/upgrade-l2 Could you please review and sign? Thanks!

**Comment by qliphy** [comment]
+1
A deprecated call of EventSetupRecord::get(ESHandle&) in L1Trigger/L1THGCal/src/HGCalTriggerTools.cc will be fixed in a separate PR.

**Pull request merged**
