### PR TITLE
[TRK POG Validation] Added residuals vs phi in MTV histos

### PR DESCRIPTION
**Pull request by emiglior**
#### PR description:

This PR adds histos of residuals vs phi in MultiTrackValidator useful to monitor tracking performance with evolving phase2 Tracker layouts 

No deps on other PRs

#### PR validation:

Code checks: scram b code-checks
Validated with runTheMatrix

This PR is sot a backport

### CODE REVIEW

**Comment by jfernan2** [comment]
Hi @emiglior, could you please make sure that subsystem name appears in the title of the PR?

**Comment by jfernan2** [comment]
Ernesto, we don't have you identified as Tracking DQM Validation contact. Please add yourself to the appropiate e-group:
https://twiki.cern.ch/twiki/bin/viewauth/CMS/DQMContacts#Tracking

**Comment by emiglior** [comment]
@jfernan2 
About changing the title of the PR, is it ok just editing it in the web interface (or is there some other prescription to be followed...)?
About e-group membership:

**Comment by jfernan2** [comment]
> @jfernan2
> About changing the title of the PR, is it ok just editing it in the web interface or is there some other prescription to be followed? I guess pre-pending "[TRK POG Validation]"
Correct. It is just to keep track of where it belongs to. Thanks
> About e-group membership: is this cms-dqm-offline-developers-tracking the right e-group?
I believe   cms-dqm-validation-developers-tracking matches better since this is Validation
> (BTW: very likely, mine will be an occasional contribution...)
OK, but please do it in anycase

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
@emiglior the PR is adding plots which depend on the workflow. In some cases they are empty (mainly in HLT folder), in others just modifications. For example I don't understand why there are RPC changes in wf12434 but perhaps this is expected.
Can you please check the changes and evaluate if you expect them?
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_11_1_X_2020-02-17-2300+73c518/35117/dqm-histo-comparison-summary.html
Thanks

**Comment by emiglior** [comment]
Maybe I am too naive, but it seems to me that many of the differences are in the decimals of the mean and RMS of the trend plots (but correct me if I am misunderstanding something...)

[Screen Shot 2020-02-18 at 17 30 18](https://user-images.githubusercontent.com/5084076/74756359-b2f05400-5274-11ea-87fa-e53f517c246b.png)

About empty plots, I think they appear in workflows with two few events (added histos are trend plots obtained projecting 2d histos in phi-bins  and fitting them to extract sigma and mean).

**Comment by jfernan2** [comment]
> Maybe I am too naive, but it seems to me that many of the differences are in the decimals of the mean and RMS of the trend plots (but correct me if I am misunderstanding something...)

No, you are NOT too naive, that's the case for many of the differences, but not always:
https://tinyurl.com/vlypkdv
and others should not be changing with this PR like https://tinyurl.com/w6ogdxj

> About empty plots, I think they appear in workflows with t0o few events (added histos are trend plots obtained projecting 2d histos in phi-bins and fitting them to extract sigma and mean).

OK, but did you expect to be changing plots in HLT folder? E.g. https://tinyurl.com/to8xmm5

**Comment by mtosi** [comment]
ciao,
sorry for jumping in
I think the "differences" spotted by the statistical test are false positive, driven by the threshold chosen 
while, the appearance of plots under the HLT directory is expected, because the MTV is used for the validation of the tracking used in both the PF reconstruction and the GSF one at HLT
for instance, looking at the standard relval in recent release one can see all the rest of plots produced by the MTV [relval GUI](https://tinyurl.com/ssmwdyz)

hope it helps
have a nice day

**Comment by jfernan2** [comment]
@mtosi I am not sure what threshold do you mean, there is no statistical test, just a bin by bin comparison of the plots produced with the PR w.r.t. those in baseline.

**Comment by mtosi** [comment]
i thought you were using the KS or the chi2

**Comment by jfernan2** [comment]
About " the appearance of plots under the HLT directory is expected, because the MTV is used for the validation of the tracking used in both the PF reconstruction and the GSF one at HLT", it was not clear to me since the PR description only mentions the MTV, but no comment about the GSF at HLT, hence my question

**Comment by jfernan2** [comment]
+1
Tracking confirmed and agreed on changes

**Comment by silviodonato** [comment]
+1

**Pull request merged**
