### PR TITLE
DQM: Allow end lumi work in DQMOneEDAnalyzer

### PR DESCRIPTION
**Pull request by schneiml**
#### PR description:

This PR adds `dqmEndLuminosityBlock` to `DQMOneEDAnalyzer`.

Turns out we can set `EndLuminosityBlockProducer` without using `WatchLuminosityBlocks`?
(Edit: no, this also blocks concurrent lumis. Back to the drawing board then.)

That gives an option to enable `dqmEndLuminosityBlock` by default.

This is once again risky, since the semantics now are subtly different compared to 2018:
The same callbacks exist, but events of multiple lumis can arrive alternatingly.
This could lead to subtle bugs. The good thing is, we have eliminated almost
all usages of the old API, so we know there are not many places where such bugs
could happen.

`globalEndLuminosityBlock` in DQM modules is banned in favor of `dqmEndLuminosityBlock` now for consistency, and all existing users changed. The semantics might be slightly different (the EDM docs hint that some lumi products might not be availale in `ennLuminosityBlockProduce`, but in `globalEndLuminostyBlock`, let's see if this survives validation.

#### PR validation:

Compiles.

Further validation needed.

### CODE REVIEW

**Comment by schneiml** [comment]
Ok, the result of the code checks does not compile, and the version that compiles does not code-check. I feared sth. along those lines. 

I'll see it there is a better solution, @Dr15Jones @makortel @smuzaffar let me know if you have any ideas.

**Comment by smuzaffar** [comment]
@schneiml , may be inlining is issue here?

**Comment by Dr15Jones** [comment]
@schneiml the compiler is telling you about a real problem. You made DQMOneEDAnalyzer always be an `EndLuminosityBlockProducer` which is fine. However, the function

```
void globalEndLuminosityBlock(const edm::LuminosityBlock&, const edm::EventSetup&) final{};
```

is not part of the `EndLuminosityBlockProducer` interface, it is part of the `edm::LuminosityBlockCache<>` interface. The reason L1TStage2CaloLayer1 is failing is it does not use a `edm::LuminosityBlockCache<>`.

**Comment by schneiml** [comment]
@Dr15Jones The error not is obvious. The problem is this:
I want to ban using `globalEndLuminosityBlock` in classes derived from `DQMOneEDAnalyzer`, so I declare a `final` `globalEndLuminosityBlock` there.

But the `edm::one::LuminosityBlockCache` that enables this feature in EDM is 1) optional, and 2) depends on a parameter from the derived class that `DQMOneEDAnalyzer` just forwards.

Now, the version from 49cce0f works fine: It declares a `virtual final` `globalEndLuminosityBlock` in all instances, with the wanted effect. But, in the cases where there is no `LuminosityBlockCache`, this class needs to be `virtual final` since it cannot be only `final`, but then in the cases where a `LuminosityBlockCache` is added, the compiler warns about the redundant `virtual`.

**Comment by schneiml** [comment]
Ok, I went with _1)_ (don't ban `globalEndLuminosityBlock`; hope that people don't try to use it and get confused by the fact that they can't use per-lumi histograms there).

Lets see if this works at all.

**Comment by schneiml** [comment]
please test

**Comment by schneiml** [comment]
hold

Turns out this does block concurrent lumis. Nevermind, then.

**Comment by makortel** [comment]
> Turns out this does block concurrent lumis. Nevermind, then.

Correct (I was actually first surprised as well, but it actually makes sense). I clarified in the [documentation](https://twiki.cern.ch/twiki/bin/view/CMSPublic/FWMultithreadedFrameworkOneModuleInterface#edm_BeginLuminosityBlockProducer) that the `Begin`/`EndLuminosityBlockProducer` extension leads to system effectively processing events from one lumi at a time.

The only way to support concurrent lumis with any of `WatchLuminosityBlocks`/`BeginLuminosityBlockProducer`/`EndLuminosityBlockProducer` is to use `LuminosityBlockCache`.

**Comment by schneiml** [comment]
@makortel I think I'll give it another try with the caches and global transitions. That will require yet another `DQM*Analyzer` base class, but should work.

**Comment by schneiml** [comment]
Actually, I don't plan to try this with global transitions, it might work but would violate the "DQM behaves like products" principle. So, as long as nobody has a real need for this, I'll close it.

**Pull request closed without merging**
