### PR TITLE
Preserve electron mass after FastSim Bremsstrahlung emmision

### PR DESCRIPTION
**Pull request by sbein**
Tracked down a cause of the seg fault reported here https://github.com/cms-sw/cmssw/issues/24051, found that FastSim bremsstrahlung emissions were being treated like decays (e->e+gamma), where the 4-vector of the photon is subtracted from the electron, but this causes the electron mass to go to zero approximately once in 10k events. Fixed code to preserve electron mass to prevent it from going to 0. CMS is not really sensitive to the electron mass, so the change to physics should be negligible. This should be percolated through the various active releases.

### CODE REVIEW

**Comment by sbein** [comment]
please test

**Comment by sbein** [comment]
please test

**Comment by sbein** [comment]
+1

**Comment by perrotta** [comment]
Looking at the code I think that a further fix could be necessary.

The method `math::XYZTLorentzVector fastsim::Bremsstrahlung::brem(...)` returns a fraction xp of the LorentzVector `particle.momentum()`. Therefore this "photon" ends up with a non zero mass.

This leads currently to the necessity of inserting the lines [L147-L149](https://github.com/cms-sw/cmssw/blob/8cf798e22db448755d01bd936752aa899b1ade46/FastSimulation/SimplifiedGeometryPropagator/plugins/Bremsstrahlung.cc#L147-L149).

I think that one should resize instead the energy of the brem gamma as a fraction of the total `particle.momentum().Rho()`

@sbein what do you think? Please tell me if I am wrong.

**Comment by sbein** [comment]
Hi @perrotta maybe I'm wrong but as far as I could tell, line 
[https://github.com/cms-sw/cmssw/blob/8cf798e22db448755d01bd936752aa899b1ade46/FastSimulation/SimplifiedGeometryPropagator/plugins/Bremsstrahlung.cc#L192C3-L192C107](https://github.com/cms-sw/cmssw/blob/8cf798e22db448755d01bd936752aa899b1ade46/FastSimulation/SimplifiedGeometryPropagator/plugins/Bremsstrahlung.cc#L192C3-L192C107)
```
return xp * particle.momentum().E() * math::XYZTLorentzVector(stheta * cphi, stheta * sphi, ctheta, 1.);
```
is returning a massless 4-vector because a number (the fraction of the 3-momentum) is used to scale a massless (0 magnitude) 4-vector. My understanding is that replacing the scaling factor E() with Rho() would result in only the transverse momentum being used, since Rho and pT are the same, and this would soften the brem photon energy spectrum.

**Comment by perrotta** [comment]
> is returning a massless 4-vector because a number (the fraction of the 3-momentum) is used to scale a massless (0 magnitude) 4-vector

Yes, you are right @sbein : I got confused, sorry for the noise

Then I let you another thought (but not for this PR): probably the check in [L147-L149](https://github.com/cms-sw/cmssw/blob/8cf798e22db448755d01bd936752aa899b1ade46/FastSimulation/SimplifiedGeometryPropagator/plugins/Bremsstrahlung.cc#L147-L149) should be moved inside `brem()` and a new photon energy can be generated then, so that in case of (unphysical) very high energy photons are generated the number of photons to be radiated is not affected.

**Comment by perrotta** [comment]
+1

**Pull request merged**
