### PR TITLE
bsunanda:Run2-gem18 Correct positions of GE21 chambers

### PR DESCRIPTION
**Pull request by bsunanda**
This was discussed in GEM validation meeting and it is validated

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@ianna Could you approve this?

**Comment by ianna** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
