### PR TITLE
New MillePede production system

### PR DESCRIPTION
**Pull request by ghellwig**
Has been presented in https://indico.cern.ch/event/512679/session/0/contribution/8/attachments/1252066/1849483/Alignment-UpdateMPS_CMS-TkAl_20160406.pdf

Summary of changes:
- Partial rewrite of the Perl scripts in Python -> Easier to maintain in the future
- Update the unversioned scripts and put them under version control
- Use a unified config and put it under version control
  - Makes use of the unified track selection and refitting sequence
- General streamlining
  - Replaced deprecated modules in the configuration
  - Replaced some ancient (unsupported) commands

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
error in unit tests is unrelated

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
