### PR TITLE
ECAL - Remove obsolete test beam code

### PR DESCRIPTION
**Pull request by thomreis**
#### PR description:

The ECAL test beam digis producer module in SimCalorimetry/EcalTestBeam is not used anymore and is removed.

The `EcalTBReadout` class in SimCalorimetry/EcalTestBeamAlgos is also removed because the `EcalTBDigiProducer` was the only user of the class to my knowledge. Since the class is the only one in the SimCalorimetry/EcalTestBeamAlgos package it can be removed as well.

Discussed in #37760 
Removing `EcalTBReadout` will affect #37992 as well.

#### PR validation:

Passes the standard matrix tests

### CODE REVIEW

**Comment by thomreis** [comment]
hold

Putting this on hold until we have clarified a couple of concerns.

**Comment by perrotta** [comment]
please test

**Comment by civanch** [comment]
This PR was discussed at the recent SIM meeting orally. Arguments to drop this sub-library is that in order to use this test beam the code should be completely revised. Moreover for Phase-2 the electronics will be very different from electronics used in the test. The argument to keep the sub-library is following: may be in future manpower to recover the test will be identified.

The final decision depends on ECAL managers and test-beam experts. SIM group cannot conclude if this sub-library is needed or not.

**Comment by civanch** [comment]
+1

**Comment by thomreis** [comment]
unhold

Test beam experts confirmed that this code is not used anymore since 2007 and will not be needed in the foreseeable future. It can therefore be removed.

**Comment by perrotta** [comment]
please test
(Just to check that no unwanted features did show up during the last three weeks)

**Comment by perrotta** [comment]
+1

**Pull request merged**
