### PR TITLE
Tau Validation/DQM: switching deepTau version from v2 to v2p1 for CMSSW10_6_X

### PR DESCRIPTION
**Pull request by aspiezia**
#### PR description:
This is a backport of https://github.com/cms-sw/cmssw/pull/28176
The pull request is intendend to update the deepTau ID from the v2 version to the new v2p1 version.
@rmanzoni @roger-wolf

### CODE REVIEW

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
