### PR TITLE
Migrate ESProducers in Calib* and Cond* from setConsumes() to type-deducing consumes()

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

Migrating `setConsumes()` calls to the simpler consumes introduced in https://github.com/cms-sw/cmssw/pull/31223.

#### PR validation:

Code compiles

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by makortel** [comment]
FYI @Dr15Jones

**Comment by pohsun** [comment]
+1

**Comment by kpedro88** [comment]
+upgrade

**Comment by rekovic** [comment]
+1

**Comment by ggovi** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
