### PR TITLE
Use standard file names in DQM/HcalTasks config files

### PR DESCRIPTION
**Pull request by Dr15Jones**
#### PR description:

Added cfi or cff extensions. This avoids name collision with auto generated files from fillDescriptions.

#### PR validation:

I used `git grep --cached` to look for all references in CMSSW to the files and modified them all.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
@makortel FYI

**Comment by Dr15Jones** [comment]
NOTE: to fully comply to our standard file naming conventions, these files should start will lower case letters to correspond to the module labels for the modules the files are defining.

**Comment by Dr15Jones** [comment]
please test

**Comment by tjavaid** [comment]
@Dr15Jones , could you please create another PR viz. its backport for `14_0_X` ? Thanks!

**Comment by tjavaid** [comment]
+1

-  spurious differences seen from unstable WF `12834.7` (open issue #39803 )
- P5 tests OK. Thanks @nothingface0 !

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
