### PR TITLE
Remove PHcalParameters

### PR DESCRIPTION
**Pull request by ianna**
- Remove PHcalParameters which is replaced by HcalParameters

### CODE REVIEW

**Comment by ianna** [comment]
@cmsbuild please test

**Comment by mmusich** [comment]
please test

**Comment by ianna** [comment]
@diguida - this PR removes PHcalParameters from CMSSW.

**Comment by ianna** [comment]
+1

**Comment by diguida** [comment]
@ianna it seems that the cleanup is not complete yet...

**Comment by ianna** [comment]
@cmsbuild please test

**Comment by ianna** [comment]
@cmsbuild  - very strange - the plugin builds just fine. Why it is missing?

**Comment by smuzaffar** [comment]
Looks like one plugin definition (PHcalParametersRcd@NewProxy) is dropped in this PR. May be some workflows still ask for it that is why plugin manager is trying to load it from poison plugin cache.

**Comment by ianna** [comment]
@smuzaffar - I see PHcalParametersRcd in the release base:
```
/afs/cern.ch/cms/sw/ReleaseCandidates/vol0/slc6_amd64_gcc493/cms/cmssw/CMSSW_7_6_X_2015-08-05-1300/src/Geometry/Records/src/PHcalParametersRcd.cc:#include "Geometry/Records/interface/PHcalParametersRcd.h"
/afs/cern.ch/cms/sw/ReleaseCandidates/vol0/slc6_amd64_gcc493/cms/cmssw/CMSSW_7_6_X_2015-08-05-1300/src/Geometry/Records/src/PHcalParametersRcd.cc:EVENTSETUP_RECORD_REG(PHcalParametersRcd);
```
but when I checkout Geometry/Records locally, I do not get these files:
```
[yana@cmsdev03 src]$ ls Geometry/Records/src/PHcal*
Geometry/Records/src/PHcalRcd.cc
```
I do not see any other reference to it anywhere.

**Comment by smuzaffar** [comment]
@ianna , If I hack my lib.<arch>.edmplugincache and add PHcalParametersRcd then plugin manager gives me this error
```The plugin 'PHcalParametersRcd@NewProxy' should have been in loadable
 '..../CMSSW_7_6_X_2015-08-05-2300/lib/slc6_amd64_gcc493/pluginCondCoreGeometryPluginsPlugins.so'
 but was not there.  This means the plugin cache is incorrect.  Please run 'EdmPluginRefresh ..../CMSSW_7_6_X_2015-08-05-2300/lib/slc6_amd64_gcc493/pluginCondCoreGeometryPluginsPlugins.so'
```
do definitely something is asking for PHcalParametersRcd (may be some condition object stored in GT)

**Comment by ianna** [comment]
@diguida - I suspect this PR will not pass relval tests without removing the tag from GT.

**Comment by ianna** [comment]
@smuzaffar and @diguida - just to confirm - this PR needs a new GT without PHcalParameters tag. The relval tests run just fine if I manually choose an older GT which does not have this tag in.

**Comment by ianna** [comment]
+1

**Comment by smuzaffar** [comment]
please test

**Comment by ianna** [comment]
@diguida - Do you still want this one or shall I close it?

**Comment by ggovi** [comment]
@cmsbuild 
please test

**Comment by ggovi** [comment]
@ianna 
is this still open?

**Comment by diguida** [comment]
@ianna given that 76X is closed, can we move this to 80X?

**Comment by ianna** [comment]
@diguida - ok, I'll rebase it.

**Comment by diguida** [comment]
@ianna I suggest to:

1. close this PR
2. make a new branch on top of `CMSSW_8_0_X`
3. cherry pick https://github.com/ianna/cmssw/commit/981a2f1f0d2f8672ba768182554b499b32d11c2c and https://github.com/ianna/cmssw/commit/dabdd7ddaf0d2c3011184ac6cfbe9e5fe7179e62
4. make a new PR targeting 80X.

**Pull request closed without merging**
