### PR TITLE
HLT menu V3.4

### PR DESCRIPTION
**Pull request by Martin-Grunewald**
HLT menu V3.4
Based on CMSSW_10_3_X_2018-08-14-2300

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1
for Utilities/ReleaseScripts/scripts/addOnTests.py

**Comment by Martin-Grunewald** [comment]
please test

**Comment by Martin-Grunewald** [comment]
@Dr15Jones 
Thanks!!

**Comment by Martin-Grunewald** [comment]
+1

**Comment by fabiocos** [comment]
@Martin-Grunewald I understand that TSG is not interested in keeping the previous frozen menu in 10_3_X. This is relevant in 10_2_X of course, I just would like to understand the rationale behind this replacement in 10_3_X

**Comment by Martin-Grunewald** [comment]
@fabiocos 
This is only for 10_3, no change in 10_2. We'd like to have the most recent one in 10_3 as long as 10_3 is still not frozen for such changes. With this we profit from (relval) validation in 10_3 pre releases.

**Comment by fabiocos** [comment]
@Martin-Grunewald sure, I was just wondering about the choice to keep only the newest one and not the older. I may guess this is for simplicity of maintenance, and that there is no interest in the 10_2_X frozen version

**Comment by fabiocos** [comment]
+1

**Comment by Martin-Grunewald** [comment]
Indeed!

**Pull request merged**
