### PR TITLE
Phase2-hgx348 Make provision for the new positions of the guard rings and sizes of partial wafers (V17 to V18 transition)

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Make provision for the new positions of the guard rings and sizes of partial wafers (V17 to V18 transition)

#### PR validation:

Use the runTheMatrix test workflows

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by civanch** [comment]
+1

**Comment by bsunanda** [comment]
@srimanob Please approve this

**Comment by bsunanda** [comment]
@srimanob @rappoccio, @antoniovilela Please integrate this PR. We need this urgently for the next step

**Comment by srimanob** [comment]
A note on code to review after this PR (not relate to this PR):

- /data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_13_3_X_2023-10-29-2300/src/SimG4CMS/Calo/src/CaloSD.cc:415:102: warning: Called C++ object pointer is null [core.CallAndMessage]
      edm::LogVerbatim("CaloSim") << "CaloSD: EndofEvent entered for container " << k << " with " << theHC[0]->entries()
- unused parameter: 
```
Geometry/HGCalCommonData/plugins/dd4hep/DDHGCalMixRotatedCassette.cc:531:7: warning: Value stored to 'zpos' is never read [deadcode.DeadStores]
      zpos += hthickl;
```
and
```
Geometry/HGCalCommonData/plugins/DDHGCalMixRotatedCassette.cc:598:5: warning: Value stored to 'zpos' is never read [deadcode.DeadStores]
    zpos += hthickl;
```

**Comment by srimanob** [comment]
+Upgrade

**Comment by antoniovilela** [comment]
> @srimanob @rappoccio, @antoniovilela Please integrate this PR. We need this urgently for the next step

@bsunanda 
Hi Sunanda,
Try to ping us with @cms-sw/orp-l2, I will pick it up faster.
Thanks,

**Comment by antoniovilela** [comment]
+1

**Pull request merged**
