### PR TITLE
Fastsim: new cfg structure, premixing

### PR DESCRIPTION
**Pull request by lveldere**
This pr is far from ready for merging, but is opened to bookkeep discussions.

Restructuring FastSim cfg to mirror better the FullSim/Reco cfg,
and to make changes with respect to FullSim/Reco cfg more transparent.

FastSim gets the same steps as FullSim/Reco

Each step X is now configured for FastSim in a file
FastSimulation/Configuration/python/X_cff.py,
which imports all objects from the corresponding FullSim/Reco cfg file
Configuration/StandardSequences/python/X_cff.py
and then edits those objects according to FastSim's needs.
# Exceptions:
- Simideal_cff does not import the corresponding FullSim file, since no objects are shared
- Reconstruction_BefMix_cff configures the part of reconstruction to be done before pileup mixing (i.e. iterative tracking)
- Reconstrcution_AftMix_cff imports Configuration/StandardSequences/python/Reconstruction_cff.py and removes all reconstruction sequences to be run before mixing (i.e. iterative tracking)
# Test this pr for classic mixing:

```
cmsRun FastSimulation/Configuration/test/minbias_fast_cfg.py              # generate minbias events, simulate and do fast track reconstruction
cmsRun FastSimulation/Configuration/test/test_mix_allsteps_cfg.py       # generate ttbar events, simulate, do fast track reconstruction, mix with pu / digitize, ... , reconstruction 
```
# Test this pr for premixing:

```
cmsRun FastSimulation/Configuration/test/minbias_fast_cfg.py                   # generate minbias events, simulate and do fast track reconstruction
cmsRun FastSimulation/Configuration/test/minbias_premixed_fast_cfg.py  # premix the minbias events
cmsRun FastSimulation/Configuration/test/test_premix_allsteps_cfg.py      # generate ttbar events, simulate, do fast track reconstruction, mix with premixed pu, ... , reconstruction 
```
# Issues:

in cmsRun FastSimulation/Configuration/test/test_mix_allsteps_cfg.py
- several warnings in reconstruction and digitization to be understodd
- a few reconstruction models were disabled because they cause crashes
# todos
- include Validation and HLT steps
- carefully compare dumped cfgs before and after these changes

### CODE REVIEW

**Comment by lveldere** [comment]
@mdhildreth 

I tweaked the data mixing module a bit:
Instead of the FastSim switch, I implemented a TrackerMergeType.
Does that look okay?

Despite our earlier communication I still don't understand how the DataMixingModule does not depend on SimHits. Reading the code, I'm under the impression the calorimeter simhits from signal are digitized inside the DataMixingModule. Would you mind commenting?

**Comment by mdhildreth** [comment]
Hi - so, the replacement of the "IsThisFastSim" with a tracker merging option would be completely fine and a much better way of doing things.

**Comment by mdhildreth** [comment]
As far as the calorimeters go: what happens is that the PreMixed digis are converted back into raw calorimeter signals and injected into the electronics simulation as noise during the digitization step that is conducted in the DataMixer.  There is no dependence on SimHits for the pileup.  When the DataMixer runs the digitizer, it does use the SimHits from the hard-scatter event in the "standard" way.  So, the signals from the pileup are treated as "noise" in the standard digitization.   Your comment above, then, is correct.

**Comment by mdhildreth** [comment]
Another question: I haven't looked at your whole configuration, but I noticed you were making provisions for a DigiToRaw step.  Do you really want to do that?  Why not just run Reco on the digis right then? (You may be doing that anyway, I was just confused by the need for the configurations.)

**Pull request closed without merging**
