### PR TITLE
EGM ID Updates from recipes (75X)

### PR DESCRIPTION
**Pull request by lgray**
Backport of #11738.

Externals PR is here: cms-data/RecoEgamma-ElectronIdentification#6
Please wait until this is in an IB before testing.

@ikrav

### CODE REVIEW

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
Is this really needed for heavy ions processing?
If not, please close.

**Comment by slava77** [comment]
-1

this is not needed for HeavyIons data processing
complain if there is use case in 75X

**Comment by lgray** [comment]
@slava77 Agree, it is not needed for heavy ions.

**Pull request closed without merging**
