### PR TITLE
Topic conversion tools

### PR DESCRIPTION
**Pull request by matteosan1**
Fix long long standing bug with parameter mismatch in a function call.

### CODE REVIEW

**Comment by matteosan1** [comment]
There has been something wrong with this PR.
The code is not

**Comment by slava77** [comment]
Matteo,
is this a combination with something else?
The PR description suggests a rather simple change, while there are quite a few nontrivial changes, mostly  from the fillDescriptions.
If it's indeed a combination, please update the PR description and also the subject so that it's more evident what's in the proposed code change.

**Comment by matteosan1** [comment]
Hi Slava,
I don't know what happened but the fix should be indeed trivial (4 lines).
I'll try to understand and fix the request.

On 2/23/15 17:51, Slava Krutelyov wrote:
>
> Matteo,
> is this a combination with something else?
> The PR description suggests a rather simple change, while there are 
> quite a few nontrivial changes, mostly from the fillDescriptions.
> If it's indeed a combination, please update the PR description and 
> also the subject so that it's more evident what's in the proposed code 
> change.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/cms-sw/cmssw/pull/7902#issuecomment-75581535>.
>

+++++++++++
Matteo Sani
University of California, San Diego, US.
Tel: +41227671577
CERN Office: 40-3-A02

**Comment by matteosan1** [comment]
Hi Slava,
I have submitted two new PR 7917 and 7918 on the same subject. This one 
can be closed.

On 23.02.2015 17:51, Slava Krutelyov wrote:
>
> Matteo,
> is this a combination with something else?
> The PR description suggests a rather simple change, while there are 
> quite a few nontrivial changes, mostly from the fillDescriptions.
> If it's indeed a combination, please update the PR description and 
> also the subject so that it's more evident what's in the proposed code 
> change.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/cms-sw/cmssw/pull/7902#issuecomment-75581535>.
>

-- 
Matteo Sani
University of California, San Diego
+41227671577

**Pull request closed without merging**
