### PR TITLE
Configurable hardcode conditions for HCAL

### PR DESCRIPTION
**Pull request by kpedro88**
This PR modifies HcalHardcodeConditions and HcalDbHardcode to make basic parameters configurable using Python. This change is intended to aid reconstruction development for the 2017 HF and HE upgrades, respectively: dual anode readout with QIE10 and SiPMs with QIE11 and increased depth segmentation.

**NB**: Nothing should change in existing workflows, because the hardcode conditions are only used for development.

Elements of this PR:
1. New class HcalHardcodeParameters (modeled after HcalSimParameters), currently contains pedestal, pedestal width, gain, gain width, QIE type, QIE offsets (range 0-3), QIE slopes (range 0-3)
2. HcalDbHardcode now a class (instead of a namespace)
3. Fixed any HcalDbHardcode dependencies accordingly (or removed unnecessary includes, in one case deleted an unused piece of code after [discussion on HCAL CMSSW hypernews](https://hypernews.cern.ch/HyperNews/CMS/get/hcal-cmssw/175.html))
4. Hcal_Conditions_forGlobalTag_cff has PSets for:HB, HE, HF, HO, HB upgrade, HE upgrade, HF upgrade
5. Each subdetector can be set to Run1 or upgrade independently (testHFQIE10 “mixed case” still available)
6. Run1 parameters based on dump of DB conditions from 7_6_3 (GT auto:run2_mc) + HcalQIEData_NormalMode_v7.05_mc for QIEData (newer tag)
7. SiPM lumi offset and pedestal width lumi dependence parameters also now configurable (may be supplanted by new noise & raddam models in the future)
8. Added a customization function customise_HcalPhase0p5 ("Phase 0.5"). Currently this enables QIE10 digitization for all HF cells, but keeps Run1 conditions for HE (SiPM + QIE11 not ready yet).

I've tested the 2017 mode in CMSSW_8_1_X_2016-03-29-2300 with customise_HcalPhase0p5 and the Extended2017dev geometry, which has HF depths 3/4 and HE depths up to 7. I used the following script:

```
#!/bin/bash

 cmsDriver.py SinglePiE50HCAL_pythia8_cfi  --conditions auto:phase1_2017_design -n 10 --era Run2_2017 --geometry "Configuration.Geometry.GeometryExtended2017dev_cff,Configuration.Geometry.GeometryExtended2017devReco_cff" --eventcontent FEVTDEBUG -s GEN,SIM --datatier GEN-SIM --beamspot Realistic50ns13TeVCollision --fileout file:step1.root --customise SLHCUpgradeSimulations/Configuration/HCalCustoms.customise_HcalPhase0p5 > step1_SinglePiE50_UP15+SinglePiE50_UP15+DIGIUP15+RECOUP15+HARVESTUP15.log  2>&1


 cmsDriver.py step2  --conditions auto:phase1_2017_design -s DIGI:pdigi_valid,L1,DIGI2RAW,HLT:@relval25ns --datatier GEN-SIM-DIGI-RAW-HLTDEBUG -n 10 --era Run2_2017 --geometry "Configuration.Geometry.GeometryExtended2017dev_cff,Configuration.Geometry.GeometryExtended2017devReco_cff" --eventcontent FEVTDEBUGHLT --filein file:step1.root  --fileout file:step2.root --customise SLHCUpgradeSimulations/Configuration/HCalCustoms.customise_HcalPhase0p5 > step2_SinglePiE50_UP15+SinglePiE50_UP15+DIGIUP15+RECOUP15+HARVESTUP15.log  2>&1


 cmsDriver.py step3  --runUnscheduled  --conditions auto:phase1_2017_design -s RAW2DIGI,L1Reco,RECO,EI,PAT --datatier GEN-SIM-RECO,MINIAODSIM -n 10 --era Run2_2017 --geometry "Configuration.Geometry.GeometryExtended2017dev_cff,Configuration.Geometry.GeometryExtended2017devReco_cff" --eventcontent RECOSIM,MINIAODSIM --filein file:step2.root  --fileout file:step3.root --customise SLHCUpgradeSimulations/Configuration/HCalCustoms.customise_HcalPhase0p5 > step3_SinglePiE50_UP15+SinglePiE50_UP15+DIGIUP15+RECOUP15+HARVESTUP15.log  2>&1


 cmsDriver.py step4  --runUnscheduled  --conditions auto:phase1_2017_design -s VALIDATION:@standardValidation+@miniAODValidation,DQM:@standardDQM+@miniAODDQM --datatier GEN-SIM-RECO,MINIAODSIM,DQMIO -n 10 --era Run2_2017 --geometry "Configuration.Geometry.GeometryExtended2017dev_cff,Configuration.Geometry.GeometryExtended2017devReco_cff" --eventcontent RECOSIM,MINIAODSIM,DQM --filein file:step3.root  --fileout file:step4.root --customise SLHCUpgradeSimulations/Configuration/HCalCustoms.customise_HcalPhase0p5 > step4_SinglePiE50_UP15+SinglePiE50_UP15+DIGIUP15+RECOUP15+HARVESTUP15.log  2>&1
```

The DIGI and RECO steps both actually succeed, though with some errors that need to be resolved. Validation/DQM fail, which is why I moved them to a separate step.

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by kpedro88** [comment]
@mmusich @ggovi @civanch - The comparison looks good to me. Again, no changes expected in standard workflows. Nevertheless, there should probably be some code review, since this is a moderately large change, even though it's only used for testing new features.

@davidlange6 - OnlineDB/HcalCondDB should probably be added to the 'db' category...

**Comment by kpedro88** [comment]
NB: I just updated the 2017 dev testing recipe in the PR message so that the RECO step can actually run.

**Comment by civanch** [comment]
please test

**Comment by kpedro88** [comment]
@civanch - noticed a typo, can you restart the tests?

**Comment by civanch** [comment]
please test

**Comment by kpedro88** [comment]
@mmusich @ggovi @civanch - The comparison still looks good to me.

@slava77 - In case you want to look at it too...

**Comment by civanch** [comment]
@kpedro88 , I think that the PR is OK in general. 

However, in HcalDbHardcode.cc double/float types are mixed in many places, this may be not a big problem but I would make code more clean.

in line 71-74:
for (int i = 0; i < 4; i++) {
      value [i] = CLHEP::RandGauss::shoot (value0, width.getWidth (i) / 100.); 
      while (value [i] <= 0) value [i] = CLHEP::RandGauss::shoot (value0, width.getWidth (i));
    }
I would replace to 
for(int i=0; i<4; ++i) {
  while(value[i] <0.0) { value[i] = value0 + (float)CLHEP::RandGauss::shoot(0.0, width.getWidth (i));
}

in lines 98-103:
for (int i = 0; i < 4; i++) {
    double width = value;
    for (int j = 0; j < 4; j++) {
      result.setSigma (i, j, i == j ? width * width : 0);
    }
  } 
one can propose:
double width2 = value*value;
for (int i = 0; i < 4; ++i) {
    for (int j = 0; j < 4; ++j) {
      result.setSigma (i, j, 0.0);
    }
    result.setSigma (i, i, width2);
  } 
in line 111:
if (fSmear) for (int i = 0; i < 4; i++) value [i] = CLHEP::RandGauss::shoot (value0, width.getValue (i));
can be replaced by
if (fSmear) {
  for (int i = 0; i < 4; ++i) { 
     value [i] = value0 + (float)CLHEP::RandGauss::shoot (0.0, width.getValue (i)); 
  }
}
in line 145:
for (int i = 0; i < 64; i++) lowEdges[i] = -1.5 + i*1.0;
can be replaced by
for (int i = 0; i < 64; ++i) { lowEdges[i] = -1.5f + i; }

in line 196:
  float phase      = -25.0;                  // [-25.0,25.0]
  float Xphase     = (phase + 32.0) * 4.0;   // never change this line 
can be replaced by
  float phase      = -25.0f;                             // [-25.0,25.0]
  float Xphase     = (phase + 32.0f) * 4.0f;   // never change this line 

in line 207:
   phase        = 5.0f;                    // a2  [-25.0,25.0]
    Xphase       = (phase + 32.0f) * 4.0f;   // never change this line 
the same in lines 221, 234, 250, 

in line 278:
    int j=k+1;
    rshift[j]=rshift[k]+r1bit[k];
can be replaced by
    rshift[k+1]=rshift[k]+r1bit[k];

lines 290-340 may be removed

**Comment by kpedro88** [comment]
@civanch - I addressed the code review comments.

> by the way, here negative value[i] is allowed, is it OK?

The gain smearing is never used in practice, so it doesn't matter.

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by civanch** [comment]
@kpedro88 , extra minor questions:

in line 72
 while (value [i] <= 0.0f) value [i] = value0 + (float)CLHEP::RandGauss::shoot (value0, width.getWidth (i) / 100.);

this means that pedestal smearing is exactly 1/100 of width?

the line 98 is not needed within the loop unless you foresee in future have this different.

**Comment by kpedro88** [comment]
@civanch: Fedor added this feature for the pedestal mean smearing many years ago. The comment says "assume a 10k pedestal run", so that the standard error on the measured mean would be width/sqrt(10k) = width/100. This way, each cell gets a slightly different pedestal mean (more realistic). I discussed this with @abdoulline and we decided this feature should be preserved.

re: line 98, you're right, but I don't think it's worth rerunning tests again...

@mmusich @ggovi - can you take a look and sign off? This should have no effect on standard workflows, and is only to be used for 2017+ testing.

**Comment by ggovi** [comment]
+1

**Comment by kpedro88** [comment]
@mmusich - can you sign off if these changes are acceptable? Again, only to be used for HCAL development, not in central workflows.

**Comment by mmusich** [comment]
@kpedro88 looks like now the branch is not merging anymore.

**Comment by kpedro88** [comment]
@mmusich - rebased

@cmsbuild please test

**Comment by kpedro88** [comment]
@cmsbuild please test

**Comment by kpedro88** [comment]
Comparison still looks fine. Rebase just had to include the technical change auto_ptr -> unique_ptr from #13999.

@civanch @ggovi @mmusich can you sign again?

**Comment by kpedro88** [comment]
@civanch @ggovi @mmusich @davidlange6 - please sign and merge ASAP as discussed in ORP this morning...

**Comment by mmusich** [comment]
+1

**Comment by abdoulline** [comment]
@civanch 
@ggovi

please, approve.

**Comment by civanch** [comment]
+1

**Comment by ggovi** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
