### PR TITLE
Adding new paths to the monitoring - Backport of #20536 to 92X

### PR DESCRIPTION
**Pull request by sscruz**
Monitoring for Muon POG paths.

Should be added on top of #19961

Output of the modules: /afs/cern.ch/work/s/sesanche/public/DQM/sep14/DQM_V0001_R000000001__Global__CMSSW_X_Y_Z__RECO.root

This PR will add 178540 bins

### CODE REVIEW

**Comment by heppye** [comment]
@dmitrijus,@mia PR is to support higgs trigger proposal targeting for v4. May DQM and STEAM please provide a quick look. Please push the integration if possible. Thanks, Ye (for HIGGS)

**Comment by sscruz** [comment]
hi, just to complement to what Ye just said. This PR corresponds mostly to developments in the MUO monitoring, but also includes a few other paths proposed by HIG

**Comment by mtosi** [comment]
do you need a rebase ?

**Comment by sscruz** [comment]
hi @mtosi , 
I don't understand what you mean... This PR is mergeable, but indeed it's built on top of #19961

**Comment by davidlange6** [comment]
Your PR is unmergeable. Please have a look and possibly rebase it.

**Comment by davidlange6** [comment]
Your PR is unmergeable. Please have a look and possibly rebase it.

**Comment by davidlange6** [comment]
CMSSW_9_2_X developement work is completed. Closing remaining PRs

**Pull request closed without merging**
