### PR TITLE
Migrate the code to DQMGlobalEDAnalyzer 

### PR DESCRIPTION
**Pull request by ebecheva**
We updated the validation code for HGCal Trigger Primitives:
- migration to DQMGlobalEDAnalyzer 
- update the configuration file in order to be able to save the produced histograms.

### CODE REVIEW

**Comment by sroychow** [comment]
@ebecheva can you run scram build code-checks  followed by scram build code-format and push the updated files?

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
