### PR TITLE
updated sistrip configuration for online dqm in 75x

### PR DESCRIPTION
**Pull request by threus**
forward port of #9444

### CODE REVIEW

**Comment by danduggan** [comment]
@cmsbuild please test
@threus can you please change the title to something like "updated sistrip configuration for online dqm in 75x"? Otherwise the PR title is fairly ambiguous

**Comment by threus** [comment]
@danduggan ah, right, done :)

**Comment by danduggan** [comment]
thanks @threus!

**Comment by deguio** [comment]
+1

**Pull request merged**
