### PR TITLE
[CPP20][GEOMETRY] Remove deprecated enum arithmetic

### PR DESCRIPTION
**Pull request by iarspider**
#### PR description:

Some arithmetic and logic operations on enums are deprecated in C++20. This PR aims to fix these.

#### PR validation:

Bot tests.

### CODE REVIEW

**Comment by iarspider** [comment]
please test for CMSSW_14_1_CPP20_X

**Comment by makortel** [comment]
The arithmetic on enum is a sign that maybe the value would be better expressed as `constexpr` constant. I think it would be good to explore that approach before going with `static_cast`.

**Comment by antoniovilela** [comment]
> The arithmetic on enum is a sign that maybe the value would be better expressed as `constexpr` constant. I think it would be good to explore that approach before going with `static_cast`.

@iarspider 

I already merged two similar PRs. In case you change the implementation, please go back to those two as well.

**Comment by iarspider** [comment]
hold
Will redo using constexprs

**Pull request closed without merging**
