### PR TITLE
modernize `CalibTracker/SiStripDCS`

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

Modernize `CalibTracker/SiStripDCS`:
   * merge headers with plugin implementation
   * transformed legacy `EDAnalyzer`s into `edm::one::EDAnalyzer`s
   * add `fillDescriptions` methods  

#### PR validation:

It compiles.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

### CODE REVIEW

**Comment by tvami** [comment]
@cmsbuild , please test

  * I have no comments after visual inspection of the code changes

**Comment by tvami** [comment]
+alca

 * jenkins comparison failures are in the msg logger, otherwise everything is ok

**Comment by perrotta** [comment]
@mmusich why not simply removing FilterTrackerOn.h (which now contains only an empty line)?

**Comment by mmusich** [comment]
> why not simply removing FilterTrackerOn.h (which now contains only an empty line)?

No reason, git history got somehow messed up.

**Comment by perrotta** [comment]
> > why not simply removing FilterTrackerOn.h (which now contains only an empty line)?
> 
> No reason, git history got somehow messed up.

Can you please remove it, then?

**Comment by mmusich** [comment]
> Can you please remove it, then?

Didn't I already :) ?

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by tvami** [comment]
+alca

**Comment by qliphy** [comment]
+1

**Pull request merged**
