### PR TITLE
Add GEM to MuonRecoAnalyzer

### PR DESCRIPTION
**Pull request by seungjin-yang**
#### PR description:
Add a plot about the number of valid GEM hits of the global muon for GEM Offline DQM. DT/CSC-version of the plot is already included.

#### PR validation:
This PR was tested with workflow 11611.0 and 27411.0.

Plots can be found on page 2 of the following link.
https://indico.cern.ch/event/924681/contributions/3885765/attachments/2049065/3436092/GEM_DPG_200601_Offline_DQM.pdf

@jshlee

### CODE REVIEW

**Comment by jfernan2** [comment]
@seungjin-yang we don't have you identified as GEM DQM developer. Can you plase addyourself with your git username to the corresponding e-group?
https://twiki.cern.ch/twiki/bin/viewauth/CMS/DQMContacts#GEM
Thanks in advance

**Comment by jshlee** [comment]
@jfernan2 - I will add @seungjin-yang to this

**Comment by jfernan2** [comment]
please test

**Comment by jfernan2** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
