### PR TITLE
Backport jetid updates #27184 #27691 to 106X 

### PR DESCRIPTION
**Pull request by knash**
#### PR description:
Backport of jetid updates to 106X
#27184,  #27691

### CODE REVIEW

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
+1
- With this PR PhysicsTools/SelectorUtils/interface/PFJetIDSelectionFunctor.h becomes identical to the one in the master
- Only affected output is expected to be nanoAOD: this PR is therefore suitable to be backported into a closed release.
- Jenkins tests pass and show no differences but in the nanoAOD for jet-id

**Comment by santocch** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
