### PR TITLE
CTPPS: DAQ mapping per interval-of-validity (backport of #16074)

### PR DESCRIPTION
**Pull request by jan-kaspar**
This is a backport of #16074.

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by slava77** [comment]
backport of #16074

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/16115 d0acf3f
- code change is as described: to use different xml text files in the RP DAQ mapping ES producer
- jenkins tests pass and comparisons with baseline show no difference (136.731 includes pre-TS2 CTPPS data and has not changes)
- local tests show expected behavior for more recent data:
    - "gap period" data from 281201 SingleMuon shows empty VFATStatus digis, in agreement with no coverage for this period without data. Jobs run OK (no warnings)
    - recent (post-TS2) data with CTPPS included shows that the new map file is picked up as expected: on run 282730 LS 160 in JetHT PD  (black is with the old "incorrect" map as used in the baseline; red is with the correct map). Plot with this PR shows drop in chip=3 VFATStatus which corresponds to two channels not present anymore in the new map (they are commented out). The actual unpacked data (hits to LocalTrack) have some non-zero entries and are not affected by the change in the map file.
all_sign778vsorig_jetht282730ls160c_totemvfatstatusedmdetsetvector_totemrprawtodigi_rp_rereco_obj__sets_data_getchipposition
or the same with standard DQM and more clearly localized to the removed channel
wfjetht282730ls160_ctpps_rp45_210_missing
wfjetht282730ls160_ctpps_rp45_210_problem



BTW, I noticed that out of 480 hw_id, there are only 440 unique values in the new map. Is this expected to be a problem somewhere?

**Comment by jan-kaspar** [comment]
> BTW, I noticed that out of 480 hw_id, there are only 440 unique values in the new map. Is this expected to be a problem somewhere?

Well spotted! It should not be a problem because the duplication occurs in the 56-210-nr-hr pot which has problems and doesn't send data. Thus the corresponding part of the mapping is irrelevant (at the moment). Nevertheless, I think it would be better to put there the real hw_ids - I will investigate with Valentina why she made the mapping as is.

**Comment by jan-kaspar** [comment]
> Nevertheless, I think it would be better to put there the real hw_ids - I will investigate with Valentina why she made the mapping as is.

Valentina has confirmed that it was not done on purpose. I will make a fix soon.

**Comment by jan-kaspar** [comment]
Hardware VFAT IDs corrected. The same correction also applied to #16074.

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
+1

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/16115 999dad9
- after DAQ mapping file update; the same update as was done in 81X PR

**Comment by ggovi** [comment]
+1

**Comment by slava77** [comment]
I expect that this should be made in sync with the latest updates to #16074 unless there is a good reason not to.

**Comment by mmusich** [comment]
please test

**Comment by jan-kaspar** [comment]
I've back-ported the leak fix from 8_1_X. The cherry pick had a strange side effect:
https://github.com/cms-sw/cmssw/pull/16115/commits/12e715610bc9fde67ca1db2a9053e4d0be8344e7#diff-f53315c3297cec839386f5dc92536bbeL1
Is this OK or shall it be reverted?

**Comment by mmusich** [comment]
@jan-kaspar indeed. The PR has also acquired L1 signature while it should not.
Please revert that. Thanks

**Comment by jan-kaspar** [comment]
@mmusich The unwanted change has been undone.

**Comment by mmusich** [comment]
please test
@jan-kaspar thanks!

**Comment by mmusich** [comment]
+1

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/16115 f1156c1
- the same update as was done in 81X to properly keep track of lifetime of the parser object and not leak
- jenkins tests pass and comparisons with baseline show no differences

**Comment by ggovi** [comment]
+1

**Comment by jan-kaspar** [comment]
@slava77 , @davidlange6 Is there a reason why this PR has been merged yet?

**Comment by davidlange6** [comment]
+1
nope - trying to work on the next 80x release this week

**Pull request merged**
