### PR TITLE
limited:: module types

### PR DESCRIPTION
**Pull request by Dr15Jones**
An edm::limited module is similar to an edm::global module (they share the same interface design), however in the edm::limited module's configuration you specify how many concurrent threads are allowed to call the module at any instance in time.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
@dan131riley here is the new module type intended to be used for your new implemention of the PoolOutputModule.

**Comment by Dr15Jones** [comment]
Many of the 'code checks' are already in #20327. I'd rather wait for that one to be merged and then do a rebase of this pull request.

**Comment by Dr15Jones** [comment]
please abort

**Comment by Dr15Jones** [comment]
type new-feature

**Comment by Dr15Jones** [comment]
please test

**Comment by Dr15Jones** [comment]
+1

**Comment by davidlange6** [comment]
yes, lets save this for 94X

**Comment by dan131riley** [comment]
For the ParallelPoolOutputModule I believe this will need implementations of subProcessParentageHelper() and non-placeholder preActionBeforeRunEventAsync().  These, of course, can be done later, and are trivial to copy from the one::OutputModuleBase.

**Comment by davidlange6** [comment]
merge

**Pull request merged**
