### PR TITLE
Make units dd4hep-dependent in Run3 Tracker algo

### PR DESCRIPTION
**Pull request by ghugo83**
Make units dd4hep-dependent.
This is in preparation of DD4hep unit change.

@cvuosalo @civanch @ianna 

Tested against all regressions: compared all coordinates.

### CODE REVIEW

**Comment by civanch** [comment]
please test

**Comment by civanch** [comment]
please test

**Comment by cvuosalo** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
