### PR TITLE
Run3-sim58 Adding eval=true for a number of xml files

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

Adding the required eval="true" in some of the ConstantsSection to allow dd4hep to proceed

#### PR validation:

Use runTheMatrix.py for validation
 
#### if this PR is a backport please specify the original PR and why you need to backport that PR:

Nothing special

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by cvuosalo** [comment]
@bsunanda In this PR, you are changing old XML files, like from 2015. We are not likely to run those scenarios with DD4hep. Also, how does adding `eval="true"` affect the comparison of geometry XML files and XML in the Conditions DB?

**Comment by bsunanda** [comment]
eval="true" does not change any evaluation using DDD. The default is eval="true". But when one tries to use dd4hep, they create problem. It is absolutely safe to have this change.

**Comment by cvuosalo** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
