### PR TITLE
Run2-alca145 Update the calibration code using isolated  tracks

### PR DESCRIPTION
**Pull request by bsunanda**
1. Selection of events in calibration now uses limits on ieta of the track at the calorimeter surface.
2. Instead of storing one track in IsoTrackStudy one now stores all tracks in an event which satisfy the isolation condition

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by lpernie** [comment]
Hi @bsunanda can you add a description?

**Comment by bsunanda** [comment]
Done

**Comment by bsunanda** [comment]
@lpernie Added the description

**Comment by lpernie** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
