### PR TITLE
[14_0] use ReadPrescalesFromFile=False in the GenericTriggerEventFlag of a bunch of DQM modules

### PR DESCRIPTION
**Pull request by srimanob**
#### PR description:
Verbatim backport of https://github.com/cms-sw/cmssw/pull/46530

#### PR validation:
-

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:
-

### CODE REVIEW

**Comment by srimanob** [comment]
@cmsbuild please test

**Comment by mandrenguyen** [comment]
backport of https://github.com/cms-sw/cmssw/pull/46530

**Comment by antoniovagnerini** [comment]
+1

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
