### PR TITLE
[124X] Improve unprotected areas of GSF code to avoid segfault

### PR DESCRIPTION
**Pull request by swagata87**
Backport of https://github.com/cms-sw/cmssw/pull/40084

Addresses https://github.com/cms-sw/cmssw/issues/39987#issuecomment-1316832648

### CODE REVIEW

**Comment by swagata87** [comment]
@cmsbuild  please test

**Comment by francescobrivio** [comment]
urgent

 - to be included in next 12_4_X (attn. of the ORM @ebrondol) for data-taking

**Comment by francescobrivio** [comment]
type tracking,egamma

**Comment by francescobrivio** [comment]
@cms-sw/reconstruction-l2 please consider reviewing this PR urgently. It is needed to fix crashes in prompt reco.

**Comment by perrotta** [comment]
+1
- This is a verbatim backport of #40084, which was already signed by @cms-sw/reconstruction-l2 
- Let have it merged, assuming that reco would also sign it, so that it can enter in the 1100 IBs: this is urgently needed by HLT for a data taking patch release

**Comment by perrotta** [comment]
merge

**Comment by mandrenguyen** [comment]
+1 
for posterity

**Comment by mandrenguyen** [comment]
+1 
for posterity

**Pull request merged**
