### PR TITLE
Setting of Tag access restrictions in command line tools

### PR DESCRIPTION
**Pull request by ggovi**
#### PR description:

We enable the setting of Tag access restriction from command line tools.
The features/functionalities added are:
- resolution of DB KEY principal
- listing of access restrictions and granted permissions
- set/unset of access restriction and permissions

The added functions are reserved to admin users.

#### PR validation:

integration tests and private validation

### CODE REVIEW

**Comment by ggovi** [comment]
please test

**Comment by ggovi** [comment]
please test

**Comment by ggovi** [comment]
@mmusich thanks for clarifying the problem. This has actually spotted a problem in the proposed changes.

**Comment by ggovi** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
