### PR TITLE
Update triggerObjects_cff.py

### PR DESCRIPTION
**Pull request by ATumasyan**
Adding FatJet trigger objects and filters for nanoAOD

#### PR description:

Adding FatJet trigger objects and filters 

#### PR validation:

Tested with CMSSW_13_1_0

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

https://github.com/cms-sw/cmssw/pull/41973

### CODE REVIEW

**Comment by iarspider** [comment]
please test

**Comment by simonepigazzini** [comment]
enable nano

**Comment by simonepigazzini** [comment]
please test

**Comment by perrotta** [comment]
backport of #41973

**Comment by simonepigazzini** [comment]
+1

same changes as in the master PR

**Comment by perrotta** [comment]
+1

**Pull request merged**
