### PR TITLE
Make SimTracker/TrackTriggerAssociation compile with C++20

### PR DESCRIPTION
**Pull request by iarspider**
#### PR description:

Title says it all. Took the liberty to rename lambda function to make code more clear

#### PR validation:

Code compiles

### CODE REVIEW

**Comment by iarspider** [comment]
type bugfix

**Comment by iarspider** [comment]
please test

**Comment by civanch** [comment]
+1

**Comment by aloeliger** [comment]
+l1

**Comment by perrotta** [comment]
+1

**Pull request merged**
