### PR TITLE
edm::Range interface to TrackCandidate recHits

### PR DESCRIPTION
**Pull request by guitargeek**
#### PR description:

A little follow-up to https://github.com/cms-sw/cmssw/pull/29971, making the interface to the recHits of different classes more consistent and adapted for range-based loops. That makes also these overloaded functions in `FakeTrackProducers` unnecessary:

https://github.com/cms-sw/cmssw/pull/30361/files#diff-11165275dc0c3719761c168a2845339fL39

#### PR validation:

CMSSW compiles.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

No backports intended.

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by jfernan2** [comment]
There seems to be Static Check errors in the test

**Comment by perrotta** [comment]
please test

**Comment by perrotta** [comment]
+1
- Similar to what was done in  #29971, where a more user-friendly edm::Range interface was implemented for TrajectorySeed refHits, this PR extends such an interface to TrackCandidate recHits, and propagates its usage to the affected parts of the CMSSW code
- Jenkins tests pass and show no difference in outputs with the baseline, as expected

**Comment by silviodonato** [comment]
do you have any comments @andrius-k @jfernan2 @kmaeshima @fioriNTU @schneiml?

**Comment by jfernan2** [comment]
+1

**Comment by silviodonato** [comment]
+1

**Pull request merged**
