### PR TITLE
Update online beamspot to quadruplet-only and rescale track uncertainties (92X)

### PR DESCRIPTION
**Pull request by makortel**
Backport of #19267. Original description:

> This PR makes the following updates to the online beamspot applications making them more robust:
> 
> rescale pixel track parameter uncertainties to match better the reality
> the uncertainties come from phase0 parametrization, so a difference wrt. phase1 is expected
> @rovere tuned the scale factor such that the pulls of pixel vertex position coordinates were correct
> do pixel tracks only from quadruplets
> triplets produce too many fakes that introduce small biases in the beamspot position
> enlargen the tracking region in Z from +- 3 cm to +- 6 cm
> Tested in CMSSW_9_2_X_2017-06-09-1100. Should have no impact on runTheMatrix workflows.
> 
> @rovere @VinInn @mtosi @JanFSchulte @dinardo @sikler

### CODE REVIEW

**Comment by makortel** [comment]
backport of #19267

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/19438	ebacaf6
- nominal backport of #19267 : the same topic branch is used to open this 92X PR
- jenkins tests pass (the modified workflows are not tested in jenkins)

**Comment by slava77** [comment]
@dmitrijus
please check this PR and comment or sign.
Thank you.

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
