### PR TITLE
Hcal validation update 10_0_X ieta shift fix v2

### PR DESCRIPTION
**Pull request by bcmcms**
Updates include:

(1) fix a few plots in which ieta was shifted

(2) fix error bars for some plots

(3) clean up some obsolete files

(4) fix era setting for digi validation plots

(5) make the digi time sample analysis less hard-coded (uses soi from tool.presamples() everywhere)

(6) For some of energy mean vs ieta plots, we moved from “s” (RMS spread error) to ” ” (error on the mean)

(7) use a separate ME for HO’s “emap”, as HO being plotted at depth=7 caused confusions (plotting at depth=4 can collide with HB depth=4 after HB phase1 upgrade)

This is a cleaner copy of https://github.com/cms-sw/cmssw/pull/21856 which had to be closed.

### CODE REVIEW

**Comment by bcmcms** [comment]
@deguio, @salavat, @hatakeyamak, @fabiocos this is relevant to you as well.

**Comment by hatakeyamak** [comment]
Due to git confusion during rebase, we ended up closing the original #21856, but this is a copy of #21856, fully-signed for quite some time.

**Comment by fabiocos** [comment]
please test

**Review by fabiocos — COMMENTED** [review]
I do not understand: are you booking over and over the same histogram for each depth? Why?

**Comment by fabiocos** [comment]
I understand that just one additional 2D ME is required, how many bins? The memory increase reported by the test look sizeable

**Comment by hatakeyamak** [comment]
Ah, right.

sprintf(histo, "emap_HO");
emap_HO = ibooker.book2D(histo, histo, ieta_bins_, ieta_min_, ieta_max_, iphi_bins_, iphi_min_, iphi_max_);
should be outside the depth loop, because HO has just one depth. @brooks, can you do this asap?

**Comment by brooks** [comment]
Wrong brooks

**Comment by dmitrijus** [comment]
+1

**Comment by fabiocos** [comment]
please test

**Comment by dmitrijus** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
