### PR TITLE
Enable comparison of HF minBias feature bit readout in CaloLayer1

### PR DESCRIPTION
**Pull request by nsmith-**
Prompted by the additions to HCAL unpacker to read this bit into digis.

### CODE REVIEW

**Comment by nsmith-** [comment]
please test

**Comment by thomreis** [comment]
@dmitrijus @jfernan2 please sign.

**Comment by thomreis** [comment]
@dmitrijus @jfernan2 please sign. We would like to get the open PRs into 10_1.

**Comment by dmitrijus** [comment]
+1

**Comment by fabiocos** [comment]
please test

**Comment by fabiocos** [comment]
@thomreis @nsmith- sorry, are the differences concentrated in wf 136.731 expected?

**Comment by nsmith-** [comment]
Yes, there is additional data being unpacked from the event and used to fill plots, hence some changes are expected.  They are consistent with the effects I expect, although I am not sure why it was only in 2016 and not 2017.  @christopheralanwest was the minBias bit enabled for 2017 running? Or is it just that the unpacker is not configured to find it for 2017 era?

**Comment by nsmith-** [comment]
Thanks Chris!
@fabiocos I think we can merge then.

**Comment by fabiocos** [comment]
@nsmith- thanks for the clarification

**Comment by fabiocos** [comment]
+1

**Pull request merged**
