### PR TITLE
TOTEM Timing detectors: backports for 10_1_X

### PR DESCRIPTION
**Pull request by forthommel**
backport of #22796 
(among others)

This PR backports the following three `master`/`10_2_X` PRs for TOTEM vertical timing detectors to be used very soon for the LHC high-β* operations:
* #22796: raw-to-digi unpacker,
* #23101: geometry, and rechits producer,
* #23198: fixed detectors mapping.
This does not yet include the DQM (to be launched in a dedicated backport PR).

This follows the discussion triggered by @fabiocos in #23275.

### CODE REVIEW

**Comment by perrotta** [comment]
@forthommel : please write in the description the full list of pull requests that you are backportig here

**Comment by forthommel** [comment]
Hi @perrotta ! The current description already includes these three PRs ids. Am I missing something?

**Comment by perrotta** [comment]
Don't mind @forthommel , you are correct
I concentrated on "backport of #22796 (among others)" without reading below where the "others" are actually listed indeed

**Comment by perrotta** [comment]
please test

**Comment by forthommel** [comment]
Perfect! I'll treat these first lines as a tl;dr next time ;)
Thanks a lot!

**Comment by forthommel** [comment]
Dear @civanch, @ianna, @arunhep, @ggovi, @slava77, @perrotta, all,
Is there anything we can do to help you review this backport PR?
Thanks a lot!

**Comment by perrotta** [comment]
@forthommel @nminafra 

I'm trying to test with EventFilter/CTPPSRawToDigi/test/test_standard_sequence_cfg.py, as you suggested for the PR in the master. I added an existing input file to it
```
    '/store/data/Commissioning2018/ZeroBias1/RAW/v1/000/314/276/00000/00C813F2-9E3F-E811-BAB4-02163E01A129.root'
```
but still I get the following error:
```
----- Begin Fatal Exception 02-Jun-2018 11:55:55 CEST-----------------------
An exception of category 'NoRecord' occurred while
   [0] Processing  Event run: 314276 lumi: 161 event: 120553701 stream: 0
   [1] Running path 'p'
   [2] Calling method for module CTPPSPixelRawToDigi/'ctppsPixelDigis'
Exception Message:
No "CTPPSPixelDAQMappingRcd" record found in the EventSetup.n
 Please add an ESSource or ESProducer that delivers such a record.
----- End Fatal Exception -------------------------------------------------
```
i.e. conditions must be updated

In order to speed up things and verify that everything works in 10_1_X as it does in the master, could you please provide a working recipe for testing this and the other pull requests meant to the high beta* run?

**Comment by nminafra** [comment]
@perrotta Sorry it took a bit of time. The test file you were using lacked the configuration of the GT used by the pixels. 
I've updated EventFilter/CTPPSRawToDigi/test/test_standard_sequence_cfg.py

In any case, the suggested (in #22796) test file is:
EventFilter/CTPPSRawToDigi/test/test_standard_sequence_cfg.py
that's why we didn't even test the other test files. Sorry about this issue.

**Comment by arunhep** [comment]
+1

**Comment by ggovi** [comment]
+1

**Comment by ianna** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by fabiocos** [comment]
+1

**Pull request merged**
