### PR TITLE
TriggerBxMonitor: add support for 2D plots

### PR DESCRIPTION
**Pull request by fwyzard**
- add support for plots vs BX and vs lumisetion;
    these plots are disabled by default.

  - make the 1D plots vs BX optional;
    these plots are enabled by default.

### CODE REVIEW

**Comment by fwyzard** [comment]
@cmsbuild, please test

**Comment by Martin-Grunewald** [comment]
+1

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
