### PR TITLE
Replace Geometry_cff with GeometryDB_cff in EgammaAnalysis

### PR DESCRIPTION
**Pull request by jeongeun**
**PR description:**
Review on the Reco part of https://github.com/cms-sw/cmssw/issues/31113

`process.load("Configuration.StandardSequences.Geometry_cff")`
 was outdated https://github.com/cms-sw/cmssw/pull/8810 
It should be replaced with
`process.load("Configuration.StandardSequences.GeometryDB_cff")`

In this PR, EgammaAnalysis configuration files (2 files) are fixed.
```
EgammaAnalysis/ElectronTools/test/run_RegressionAndCombination_cfg.py
EgammaAnalysis/ElectronTools/test/run_exampleMva_cfg.py

```

#### PR validation:
Tested in CMSSW_12_5_X, the basic test all passed in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by perrotta** [comment]
@cms-sw/egamma-pog-l2 : these test configs are definitely old and certainly not used since a while. If they are not needed any more a better oprion could be removing them at all, rather than spending time in maintaining them every some while. Please let us know.

**Comment by swagata87** [comment]
Hello @perrotta 

indeed it looks like they are obsolete and can be removed. 
However, before removing anything from egamma related packages, we generally announce it in egamma cmsTalk; wait about 1 week or so for people to react/give their opinion, and only after that we delete stuff. 

if it's ok for you then please have this PR on hold for a week or so, while we check with rest of the egamma group that everyone is fine with deleting these 2 files. I will get back to you here.

**Comment by perrotta** [comment]
Thank you @swagata87 : yes, that's perfectly fine, this is certainly not an urgent PR
@jeongeun please be ready to remove the obsolete configs instead of fixing them, if and when @cms-sw/egamma-pog-l2 will confirm approving it

**Comment by swagata87** [comment]
Hi,
We have not received any objection[1] from egamma group about removing the following two files[2]. So they can be safely removed.

[1]https://cms-talk.web.cern.ch/t/removal-of-obsolete-files-from-egammaanalysis-electrontools-package/14033

[2]https://github.com/cms-sw/cmssw/blob/master/EgammaAnalysis/ElectronTools/test/run_exampleMva_cfg.py and https://github.com/cms-sw/cmssw/blob/master/EgammaAnalysis/ElectronTools/test/run_RegressionAndCombination_cfg.py

**Comment by perrotta** [comment]
@jeongeun could you please go ahead with the suggestion from @swagata87 in https://github.com/cms-sw/cmssw/pull/39092#issuecomment-1226959617 and fully remove the two test files?

**Comment by perrotta** [comment]
`please test`

**Comment by perrotta** [comment]
@cmsbuild please test

**Comment by perrotta** [comment]
merge
Failing tests are untelated

**Pull request merged**
