### PR TITLE
migrate away from deprecated `EDAnalyzer` in `OnlineDB/SiStripESSources`

### PR DESCRIPTION
**Pull request by mmusich**
#### PR description:

Title says it all, missing one in https://github.com/cms-sw/cmssw/pull/36413.

#### PR validation:

`cmssw` compiles.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

### CODE REVIEW

**Comment by mmusich** [comment]
please test

**Comment by mmusich** [comment]
please test

**Comment by tvami** [comment]
+db
 * test pass, code in line with the PR description

**Comment by qliphy** [comment]
+1

**Pull request merged**
