### PR TITLE
Use esConsumes in RandomXiThetaGunProducer

### PR DESCRIPTION
**Pull request by makortel**
#### PR description:

Part of #31061.

#### PR validation:

Code compiles, and tests of `Validation/CTPPS` run successfully with #35588.

### CODE REVIEW

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by SiewYan** [comment]
Looks good. thank you @makortel

**Comment by SiewYan** [comment]
+1

**Comment by qliphy** [comment]
+1

**Pull request merged**
