### PR TITLE
make input products configurable for online and hlt in pixel DQM

### PR DESCRIPTION
**Pull request by VinInn**
Fixed online configuration as well (w/o changing behavior)

### CODE REVIEW

**Comment by VinInn** [comment]
@fioriNTU , @gflouris , please take further action if considered appropriate

**Comment by VinInn** [comment]
@cmsbuild , please test

**Comment by VinInn** [comment]
@makortel

**Comment by VinInn** [comment]
@cmsbuild , please test

**Comment by VinInn** [comment]
@cmsbuild , please test

**Comment by dmitrijus** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
