### PR TITLE
Event Shape and UCC HLT offline DQM

### PR DESCRIPTION
**Pull request by BetterWang**
Q2 and UCC HLT trigger offline DQM
[+] EventShape histograms for Q2 HLT
[+] SumEt and PixelCluster histograms for UCC HLT

### CODE REVIEW

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
-1
ciao @BetterWang 
the tests are failing because the module ventshapeDQM_Q2_top10_cent1030 is not defined.
in addition it is probably better to make a dedicated offlineHLTSource sequence for HI included in DQMOfflineHeavyIons_cff.py. I guess that you are not interested in running all the modules in the sequence at:
https://github.com/cms-sw/cmssw/blob/CMSSW_8_0_X/DQMOffline/Trigger/python/DQMOffline_Trigger_cff.py#L46

we can talk in person.
F.

**Comment by davidlange6** [comment]
please test

**Comment by deguio** [comment]
+1

**Comment by deguio** [comment]
please test

**Comment by deguio** [comment]
+1

**Comment by davidlange6** [comment]
+1

**Pull request merged**
