### PR TITLE
enrich WFs to run in IB with more of  2018

### PR DESCRIPTION
**Pull request by slava77**
this should now match what is running for 2017 already

### CODE REVIEW

**Comment by slava77** [comment]
@cmsbuild please test

**Comment by fabozzi** [comment]
+1

**Comment by slava77** [comment]
@kpedro88 
your signature is missing for this PR.
Please check.


With this PR the IB machinery will keep the files needed for tests of 2018 workflows resident in the cmsbuild area and will allow for easier tests for general PR integration.

**Comment by kpedro88** [comment]
+1
(was hoping #21842 would get merged first so I wouldn't have to rebase again, but it is not ready yet, oh well)

**Comment by kpedro88** [comment]
@fabiocos can you merge this before the next IB?

**Comment by fabiocos** [comment]
+1

**Pull request merged**
