### PR TITLE
Phase2-hgx360D First attempt to make a Phase2 scenario with 0 overlaps with zero tolerance

### PR DESCRIPTION
**Pull request by bsunanda**
#### PR description:

The first attempt to make a Phase2 scenario 2026D116 with no overlaps with zero tolerance

#### PR validation:

Tested using overlap checking tools present in SimG4Core/PrintGeomInfo. The number of overlaps is reduced from 348 to 38. The remaining overlaps are all in EB for reflected Solids

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Nothing special

### CODE REVIEW

**Comment by kpedro88** [comment]
@bsunanda can you add workflows for this new detector version in https://github.com/cms-sw/cmssw/blob/7dc755530ad751991ea10bacdc0dbaecff716186/Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py#L90? Then we can test it directly in this PR.

**Comment by bsunanda** [comment]
@kpedro88 OK I shall do that. I wanted to discuss on the remaining overlaps

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
The new workflow is 32434.0

**Comment by kpedro88** [comment]
test parameters:
workflow = 32434.0

**Comment by kpedro88** [comment]
please test

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by AdrianoDee** [comment]
please test with https://github.com/cms-sw/cmssw/pull/46559

**Comment by bsunanda** [comment]
+geometry

**Comment by kpedro88** [comment]
NB this will conflict with #46582

**Comment by AdrianoDee** [comment]
Given the amount of signatures needed and the good number of those already collected for https://github.com/cms-sw/cmssw/pull/46582, I'd leave that go first.

**Comment by bsunanda** [comment]
Although this PR was made earlier?
________________________________

**Comment by srimanob** [comment]
I see conflict already show up. Just merge this PR asap, and I will fix once.
Note to @cms-sw/orp-l2 Could you please avoid merging PR that cause conflict with https://github.com/cms-sw/cmssw/pull/46582 after this PR? Thanks.

**Comment by AdrianoDee** [comment]
Apparenlty #46582 needs a rebase anyway.

**Comment by AdrianoDee** [comment]
+pdmv

**Comment by srimanob** [comment]
Let's try to merge this PR, and avoid to merge something else. So that the big one can go. Thanks. 
FYI @cms-sw/orp-l2

**Comment by srimanob** [comment]
Kindly ping @cms-sw/upgrade-l2

**Comment by Moanwar** [comment]
+Upgrade

**Comment by bsunanda** [comment]
Since the big file is merged first, I am closing this PR and making a fresh one

**Pull request closed without merging**
