### PR TITLE
Fix sigmaIetaIphi for photon regression (75X)

### PR DESCRIPTION
**Pull request by lgray**
Forward port of #11403.

### CODE REVIEW

**Comment by lgray** [comment]
@cmsbuild please test

**Comment by slava77** [comment]
I suppose this PR goes in only if we kill the RECO-based regression PR #11402, right?

**Comment by lgray** [comment]
Yes.

(Sent from my Nexus 6)

**Comment by slava77** [comment]
+1

for https://github.com/cms-sw/cmssw/pull/11406	3b2a460
- small fix in the definition of the regression input variable for the miniAOD photon energy correction
- the same changes as in 74X https://github.com/cms-sw/cmssw/pull/11405	 93f9992; see details of performance changes there
    - miniAOD photon energies are changed slightly after the fix
- jenkins tests pass and comparisons with baseline showed no differences (the variables are not monitored in current miniAOD monitoring)

This PR is not needed if #11402 can be merged (requires a relval cycle).
If 75X DR campaign/reprocessing release should be cut before 760pre6 relval or another 75X relval cycle is in order, this PR should be merged in 75X.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
