### PR TITLE
HIN Jet DQM module (v3) backport into 75X

### PR DESCRIPTION
**Pull request by rkunnawa**
This PR is the 75X backport of the PR #12194  and needs the PR #12213 centrality bin information. This includes bug fixes and some additions. I tested the matrix with the #12213 merged and was perfectly fine.  

Cheers
Raghav

### CODE REVIEW

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by fabozzi** [comment]
+1

**Comment by cvuosalo** [comment]
@cmsbuild please test

**Comment by srimanob** [comment]
+1 
For PdmV, Changes in Alca step relval looks fine.

**Comment by mmusich** [comment]
+1

**Comment by slava77** [comment]
#12259 is now merged and this PR now has conflicts brought in by merging #12213, which is now closed.
it would be better to "git rebase -i CMSSW_8_0_X" and remove the merge of 12213 (f28a3fe) .. or redo this PR from scratch

**Comment by rkunnawa** [comment]
@slava77 we can now close this PR. I created a new one #12310 which adds the centrality bin and the jet dqm separately. thanks!

**Comment by slava77** [comment]
Hi Raghav.
You should be able to close this PR. (you opened it).

**Pull request closed without merging**
