### PR TITLE
[PUID] Add UL16 and UL16APV training configs

### PR DESCRIPTION
**Pull request by singh-ramanpreet**
#### PR description:
- New training files (UL16 and UL16APV) and configs are added for Pileup Jet Id (AK4CHS)
- New working points, same for both UL16 and UL16APV
- default `algo` is not changed as discussed before in earlier PR https://github.com/cms-sw/cmssw/pull/32418

#### PR validation:
- Test with https://github.com/cms-data/RecoJets-JetProducers/pull/13

FYI: @alefisico @camclean @marinakolosova

### CODE REVIEW

**Comment by mariadalfonso** [comment]
test parameters:

pull_request = cms-data/RecoJets-JetProducers#13

**Comment by mariadalfonso** [comment]
please test

**Comment by singh-ramanpreet** [comment]
Fixed the bug.
Please test again.

**Comment by perrotta** [comment]
please test

**Comment by mariadalfonso** [comment]
@perrotta, @jpata, @slava77
note we need this for the nanov9

**Comment by jpata** [comment]
+reconstruction
- no unexpected reco changes, code changes look OK
- please ensure https://github.com/cms-data/RecoJets-JetProducers/pull/13 is merged before this PR

**Comment by mariadalfonso** [comment]
@singh-ramanpreet 
please backport this to 10_6_X
for the no change policy please have a look at 
https://github.com/cms-sw/cmssw/pull/32872

**Comment by qliphy** [comment]
+1

**Pull request merged**
