### PR TITLE
HLT menu development for `14_1_X` (2/N) 

### PR DESCRIPTION
**Pull request by mmusich**
backport of https://github.com/cms-sw/cmssw/pull/46375

#### PR description:

Development of HLT menus for `CMSSW_14_1_X`
   * This is the PR for the 14_1_X branch which is the release cycle currently used for Run-3 HLT-menu development.

These updates correspond to the changes accumulated in the 14_1_X release cycle for the "**PRef V1.0**" menu: first menu for the 2024 pp reference data-taking period.

This update includes the integration of the following changes:
- migration of the combined HLT table and related subtables to `CMSSW_14_1_1`

In addition we include the integration of the following JIRA tickets:

- [CMSHLT-3325](https://its.cern.ch/jira/browse/CMSHLT-3325) [HIN] Forward/UPC Triggers request for pp Reference Run 2024
- [CMSHLT-3338](https://its.cern.ch/jira/browse/CMSHLT-3338) [HIN] Muon Triggers for PbPb Run 2024
- [CMSHLT-3340](https://its.cern.ch/jira/browse/CMSHLT-3340) [HIN] Jet Triggers for pp Reference Run 2024
- [CMSHLT-3343](https://its.cern.ch/jira/browse/CMSHLT-3343) [HIN] E/gamma Triggers for pp Reference Run 2024
- [CMSHLT-3345](https://its.cern.ch/jira/browse/CMSHLT-3345) [HIN] Remove `PPRefExotica` PD/stream and re-assign paths to `PPRefSingleMuon`
- [CMSHLT-3346](https://its.cern.ch/jira/browse/CMSHLT-3346) [HIN] Justify `Commissioning{ZDC,RawPrime}` PDs in the `PRef` menu
- [CMSHLT-3348](https://its.cern.ch/jira/browse/CMSHLT-3348) [HIN] Add two seeds to `hltL1sUPCHFafterglowCombined`
- [CMSHLT-3350](https://its.cern.ch/jira/browse/CMSHLT-3350) [HIN] Forward/UPC Triggers request for PbPb Run 2024
- [CMSHLT-3356](https://its.cern.ch/jira/browse/CMSHLT-3356) [HIN] E/gamma Triggers for PbPb Run 2024
- [CMSHLT-3357](https://its.cern.ch/jira/browse/CMSHLT-3357) [TSG] Release of special menus V1.6 (for `PRef`, `HIon` runs)
- [CMSHLT-3363](https://its.cern.ch/jira/browse/CMSHLT-3363) [HIN,TSG] Sync offline menu with the 2023 `PRef` online menu

In this PR we also have the following commits:
   * 9be857b180faf2ea2354787f38a4afb6ac806cea update of L1T HIon menu in TSG GTs to `L1Menu_CollisionsHeavyIons2024_v1_0_5_xml` 
   * 9b44c34553d445f91cd27ef9079a6d2989609cc3 Finalize integration of the following tickets
        * [CMSHLT-3310](https://its.cern.ch/jira/browse/CMSHLT-3310) [TSG] update input files for TSG tests to more modern datasets (2024)
   * 0aaf2a4899f363be05c05c9f2e71cc484f4d687b Update `hltPathOwners.json` including paths for menus `PRef` 2024 V1.0 and `HIon` 2024 V1.0
   * 2beed138402dd25bee4084e45d98dcb2c580bd42 Bumped version of Paths for HLT PRef-2024 V1.0

#### PR validation:

TSG Integration tests.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

backport of https://github.com/cms-sw/cmssw/pull/46375 to the 2024 `PRef` and `HIon` production cycle (CMSSW_14_1_X)

### CODE REVIEW

**Comment by mmusich** [comment]
type hlt-integration

**Comment by mmusich** [comment]
enable gpu

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
+hlt
   * [changes](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_14_1_X_2024-10-14-1100+983d4f/65101/dqm-histo-comparison-summary.html) in the `HLTFilters` DQM folders are due the path versioning (https://github.com/cms-sw/cmssw/pull/46376/commits/2beed138402dd25bee4084e45d98dcb2c580bd42).

**Comment by mmusich** [comment]
message to @cms-sw/orp-l2, this PR needs to be merged together with https://github.com/cms-sw/cmssw/pull/46389

**Comment by mmusich** [comment]
test parameters:
   * pull_request = https://github.com/cms-sw/cmssw/pull/46389
   * worfklows = 160, 160.02, 160.03, 160.1, 160.2, 160.3, 160.4, 160.501, 180.0, 180.1

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
@cmsbuild, please abort

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
Ah, now I get it... all the failing workflows are running the 2023 GlobalTag (which wasn't updated in terms of L1T menu). Assuming we don't want to update them to be 2024-like, we should run the fake menu instead.  @mandrenguyen any preference?

**Comment by mandrenguyen** [comment]
Fake would be fine

**Comment by mmusich** [comment]
> Fake would be fine 

see https://github.com/cms-sw/cmssw/pull/46399

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by mmusich** [comment]
@cms-sw/orp-l2 we need to get going with this PR as there are more tickets to integrate. Please merge at earliest convenience. 
About possible IB failures triggered by the update, they will be cured by https://github.com/cms-sw/cmssw/pull/46399 - but they are not caused by this particular update here, but from a lack of organization in the HIon relvals structure that can be figured out at a later time.
Thanks your for the collaboration.

**Comment by mandrenguyen** [comment]
+1

**Pull request merged**
