### PR TITLE
updated relval gridpacks for gcc630

### PR DESCRIPTION
**Pull request by pmillet**
as mentioned in https://github.com/cms-sw/cmsdist/pull/3367

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test workflow 534.0 with #20401

**Comment by perrozzi** [comment]
+1

**Comment by davidlange6** [comment]
hi @pmillet @smuzaffar - how can we make this work for any scram_arch (of course the gridlpacks would have to be there, but thats a second topic)

**Comment by pmillet** [comment]
We could scram_arch and sherpa version from environment variables in a similar way as the openloops version. Not sure about the checksum though. One could add a dict storing the checksums for each scram_arch/sherpa version. We would still need to update the files once there is a new scram_arch or some major sherpa update.

**Comment by davidlange6** [comment]
hi @pmillet - sorry for the slow answer - that sort of lookup table would go a long way to future proof this code - its better to have a clean failure in cases where an architecture is not supported..

**Comment by pmillet** [comment]
@davidlange6 - 
Another way would be to disable the checksum check (ensures that copying of the gridpack was successful) for the release validation samples and get sherpa version / architecture from environment variables. This would remove the need to update these python fragments for each new architecture and sherpa version but does not need a dict for the different checksums. It will still crash when the files are not there.

**Comment by davidlange6** [comment]
Right - a small checksum dictionary is also supportable I think. Anyway, please have a look at what you think is best.

**Comment by davidlange6** [comment]
+1

**Pull request merged**
